### ISSUE TITLE
Restrict an ability to use `dictGet` without type in column default.

### ISSUE THREAD

**Issue by alesapin** [ClickHouse/ClickHouse#10006]
If the user specifies `dictGet` function in column default:
```
...
ClientInstallDate Date MATERIALIZED toDate(dictGet('clients', 'time_added', tuple(ApplicationId)))
....
```
Then the server will try to load the dictionary to deduce type: https://github.com/clickhouse/ClickHouse/blob/master/dbms/Functions/FunctionsExternalDictionaries.h#L1373. But startups of dictionaries and tables are independent processes so on table startup sever don't know anything about dictionary structure and will not be able to load the table with such default. We don't want to introduce complex dependencies between tables and dictionaries startups, so we should just restrict `dictGet` in columns `DEFAULT/ALIAS/MATERIALIZED` expressions.

**Comment by alexey-milovidov** [comment]
Ok. The question is how to name this property of functions?
`isDependentOnCatalog`?

(this property will be also applicable to `joinGet` and `hasColumnInTable`)

**Comment by filimonov** [comment]
Loosely related to https://github.com/ClickHouse/ClickHouse/issues/10729

**Comment by alexey-milovidov** [comment]
> We don't want to introduce complex dependencies between tables and dictionaries startups

It becomes inevitable.

**Comment by alexey-milovidov** [comment]
See #13059 and #13613.

**Comment by kitaisreal** [comment]
We guarantee only that dictionaries are loaded before tables for same database. Also we updated dictGet to load only DictionaryStructure for return_type.
Such example will work and server will successfully startup:
```
CREATE TABLE values(id UInt64, value String) ENGINE=TinyLog;
CREATE DICTIONARY test_dictionary (id UInt64, value String) PRIMARY KEY id LAYOUT(DIRECT()) SOURCE(CLICKHOUSE(TABLE 'values'));
CREATE TABLE test_table (id UInt64, value DEFAULT dictGet('test_dictionary', 'value', id)) ENGINE=TinyLog;
```
If dictionary is in another database, such configuration can fail because then we do not guarantee that there will be any order of database loading.
