### ISSUE TITLE
Clickhouse Connection Error if one of the instance of clickhouse is down.

### ISSUE THREAD

**Issue by chhaya-sharma** [ClickHouse/ClickHouse#10010]
Hi Team.
I am trying to implement fault tolerance system using clickhouse replication feature.
I setup a cluster with 3 machines and a test database with 1 shard and 3 replicas.  I have created a table in database using replicatedMergeTree engine. As replicatedMergeTree itself replicates the data to all the instance having same table and zookeeper path but Whenever an instance goes down, clickhouse java client throws connection error and unable to query on other servers.

Please suggest some ways to achieve high availability.

**Comment by johnatannvmd** [comment]
You could use HaProxy or similar in front of ClickHouse servers and connect to the proxy instead of using the direct connection.

Anyway, if you use Native protocol which is TCP when the instance goes down you should manually reconnect to another or just reconnect if you use the proxy.

**Comment by filimonov** [comment]
AFAIK in JDBC client, you can provide addresses of few servers in connection settings.

**Comment by alexey-milovidov** [comment]
- HAProxy;
- nginx;
- clickhouse-server with Distributed table on localhost;
- application side load balancing;
- LVS;
- load balancer inside your cloud provider, both L3/L7 will do;
- ...
