### ISSUE TITLE
Can't start Clickhouse due to zookeeper metadata node of some replicated table doesn't exist.

### ISSUE THREAD

**Issue by AlexanderJLiu** [ClickHouse/ClickHouse#10037]
**Description**

After I upgrade my Clickhouse to version `20.3.5.21`, I can't start the clickhouse-server. Logs in `clickhouse-server.log` are shown as below:

```
[ 38541 ] {} <Error> Application: Coordination::Exception: Can't get data for node /clickhouse/tables/shard_name/table_name/replicas/replica_name/metadata: node doesn't exist (No node): Cannot attach table `db`.`table` from metadata file.
[ 38541 ] {} <Information> Application: shutting down
[ 38541 ] {} <Debug> Application: Uninitializing subsystem: Logging Subsystem
[ 38545 ] {} <Information> BaseDaemon: Stop SignalListener thread
```

I've checked zookeeper, and `/clickhouse/tables/shard_name/table_name/replicas/replica_name` does exist but there is no `metadata` node in it. Nodes in `replica_name` are show below:

```
 ['queue', 'host', 'flags', 'columns', 'parts', 'max_processed_insert_time', 'log_pointer', 'min_unprocessed_insert_time']
```

If I set the shard and replica in macros to empty stirng, Clickhouse would start with some warning logs, just says `No metadata in ZooKeeper: table will be in readonly mode.`

Previous version (1.1.54343) works well when restart. And it didn't need `metadata` node in zookeeper.

So, is this a bug? And how to handle this with new version of clickhous? Thanks~

**Comment by alesapin** [comment]
Seems like you have updated from the extremely old version. `replica_name/metadata` node was introduced about two years ago. Now you can just copy `/table/metadata` node to `/table/replicas/replica_name/metadata` with `zkCli.sh` util.

**Comment by AlexanderJLiu** [comment]
@alesapin Thanks~, I've solved this problem by copying `metadata` node. Considering that other people who want to upgrade clickhouse will also encounter this  problem, I'll give the `python code` I've  used. Also, `zkCli.sh` maybe work, but I  don't think it's convenient to handle lots of  replicated tables.

In python, I suggest to install `kazoo` [package](https://kazoo.readthedocs.io/en/latest/basic_usage.html) using  `pip install kazoo` . To `copy` node, we should get the node data first, and create new  node with these data. Given the structure `/clickhouse/tables/{shard}/{table_name}/replicas/{replica_name}`, we should copy `/clickhouse/tables/{shard}/{table_name}/metadata` to `/clickhouse/tables/{shard}/{table_name}/replicas/{replica_name}/metadata`. Code shown as below:

```python
from kazoo.client import KazooClient

zk = KazooClient(hosts='ip:2181')
zk.start()
print(zk.server_version())

METADATA = "metadata"
REPLICAS = "replicas"
root_node = "/clickhouse/tables"
if zk.exists(root_node):
    shards = zk.get_children(root_node)
    for shard in shards:
        shard_node = "/".join([root_node, shard])
        tables = zk.get_children(shard_node)
        for table in tables:
            table_meta_node = "/".join([shard_node, table, METADATA])
            if zk.exists(table_meta_node):
                data, stat = zk.get(table_meta_node)
                replica_node = "/".join([shard_node, table, REPLICAS])
                if zk.exists(replica_node):
                    replicas = zk.get_children(replica_node)
                    for replica in replicas:
                        replica_meta_node = "/".join(
                            [replica_node, replica, METADATA])
                        if zk.exists(replica_meta_node):
                            print("replica meta node %s already exist" %
                                  (replica_meta_node))
                        else:
                            zk.create(replica_meta_node, data)
                            if zk.exists(replica_meta_node):
                                print("create meta node %s successfully" %
                                      (replica_meta_node))
                            else:
                                print("create meta node %s failed" %
                                      (replica_meta_node))
                else:
                    print("replica node %s doesn't exsit" % (replica_node))
            else:
                print("table metadata node %s doesn't exist" %
                      (table_meta_node))
else:
    print("root node %s doesn't exist" % (root_node))
```

**Comment by alesapin** [comment]
Fix https://github.com/ClickHouse/ClickHouse/pull/10095.
