### ISSUE TITLE
What is the best way of applying multiple retention limitations for the data in a table?

### ISSUE THREAD

**Issue by th0th** [ClickHouse/ClickHouse#10031]
I have a table with a `DateTime` field that has data from multiple users. I need to delete old data from this table, with a filter. I am trying to apply a retention limit and one user's data should be stored for 30 days and another's for 1 year.

The first thing that came to my mind is to add a `valid_until DateTime` field and filter by this field when deleting. But the thing is, the retention period might change after the data is saved. I can add also a `user_id` field and alter the `valid_until` field of all the data that belongs to that user when necessary, but I thought it would be costly, right?

Did anybody else have to deal with such a case? What would be the correct way of implementing such a retention limitation?

**Comment by filimonov** [comment]
Did you check TTL functionality?

**Comment by th0th** [comment]
Thanks for the reply @filimonov, I saw it but I don't think it would work for my case.

How can I handle different retention periods with TTL? What should my data structure be? Something like this?

```sql
CREATE TABLE example_table
(
    date_time DateTime,
    valid_until DateTime,
    a Int TTL valid_until + INTERVAL 1 HOUR,
    c String
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(date_time)
ORDER BY d;
```

Then I can delete rows with invalid `a` field every day.

But I also need to change this `valid_until` when I decide to store this user's data for a longer time period.

**Comment by den-crane** [comment]
TTL can contain an expression

```
CREATE TABLE example_table 
(
    d DateTime,
    a Int,
    x Int
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(d)
ORDER BY d
TTL d +  INTERVAL if(x=1, 1, 30) day ;
```

**Comment by th0th** [comment]
Thanks a lot @den-crane! I didn't know that.

The TTL is dynamic so that it changes when I change the `x`, right?  It won't change frequently,  maybe once or twice. Also, does changing `x` bring a great cost or is it a pretty common case?

**Comment by filimonov** [comment]
> The TTL is dynamic so that it changes when I change the x, right? It won't change frequently, maybe once or twice. 

If you plan to change TTL, ALTER DELETE will work better for you (with TTL you will need to process the same data 2 times - when column value changed, and then MATERIALIZE TTL)

**Comment by th0th** [comment]
Thanks for the comments!

**Comment by mbaksheev** [comment]
For our system we had the similar requirement to implement dynamic TTL based on a column value. We successfully implemented it by using ClickHouse dictionaries, TTL expression and  UDFs. You can find details about the solution in my article https://nocql.dev/posts/clickhouse-dynamic-ttl/

**Comment by den-crane** [comment]
@mbaksheev Your article full of typos and it cannot work because in the last 4 years TTL allows only deterministic functions

https://fiddle.clickhouse.com/276afcfe-db8c-40ed-b610-bfdabc30fe5c
TTL expression cannot contain non-deterministic functions, but contains function dictGetOrDefault

**Comment by alifirat** [comment]
Hi @mbaksheev

Your article is great and I have a question about it: how do you manage the changes of a TTL for tenant? Let's imagine that you have a billions of rows inserted for a tenant with a retention X but now the retention is Y for this tenant. 

So far, I have the feeling that you have to materialized TTL but it looks like a very expensive operation. What about your use case?

**Comment by mbaksheev** [comment]
Hi @alifirat. Yes, in my case I do not change TTL for the existing rows, since as you said, it's very expensive operation. If TTL value updated in the tenant_ttl dictionary, the new value is applied only for new inserted records.

If you need to have more flexibility, I would suggest  to use [lightweight deletes](https://clickhouse.com/docs/en/guides/developer/lightweight-delete).
