### ISSUE TITLE
how to rebalance the data(distributed table with sharding_key) when i add a new server  ?

### ISSUE THREAD

**Issue by yinjiakang** [ClickHouse/ClickHouse#10034]
i use distributed table with sharding_key (for example use column uin as sharding_key)

so that when i insert data, each uin will insert into fixed server

Suppose i have three server A, B, C:
uin_1 will insert into Server A, uin_2 will insert into Server B, uin_3 will insert into Server C

when i add two new server into the cluster, so now i have 5 servers:  A, B, C, D, E
the result of a uin after sharding might be different.

for example: 
uin_1  store in Server A before.
but now, the new rows with uin = uin_1 will be inserted into Server D,  because the increase in the number of servers leads to different sharding results

now i want to make sure that same uin store in same server.  (in this case , after add new servers , all the rows where uin = uin_1 should store in Server D, include the old data before add two new server into cluster)

is there any efficient way to re-shard the old data to achieve my purpose ?

**Comment by den-crane** [comment]
> is there any efficient way to re-shard the old data to achieve my purpose ?

No. There is no efficient way.
You need to reload all data somehow. 
insert... select 
clickhouse-copier
