### ISSUE TITLE
clickhouse doesn't start

### ISSUE THREAD

**Issue by papolu-sh** [ClickHouse/ClickHouse#10046]
Clickhouse server fails to start inside of a docker conatiner. Below are the logs.
Same behavior on clickhouse version: 20.3.5.21

Logs:
Logging trace to /var/log/clickhouse-server/clickhouse-server.log
Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
Logging trace to console
2020.04.03 18:58:45.205340 [ 1 ] {} <Information> : Starting **ClickHouse 19.17.5.18** with revision 54428
2020.04.03 18:58:45.207388 [ 1 ] {} <Information> Application: starting up
2020.04.03 18:58:45.210187 [ 1 ] {} <Debug> Application: rlimit on number of file descriptors is 1048576
2020.04.03 18:58:45.210225 [ 1 ] {} <Debug> Application: Initializing DateLUT.
2020.04.03 18:58:45.210239 [ 1 ] {} <Trace> Application: Initialized DateLUT with time zone 'Etc/UTC'.
2020.04.03 18:58:45.210528 [ 1 ] {} <Debug> Application: Configuration parameter 'interserver_http_host' doesn't exist or exists and empty. Will use '567ea3d6169a' as replica host.
2020.04.03 18:58:45.213728 [ 1 ] {} <Debug> ConfigReloader: Loading config '/etc/clickhouse-server/users.xml'
Include not found: networks
2020.04.03 18:58:45.214661 [ 1 ] {} <Information> Application: Loading metadata from /var/lib/clickhouse/
2020.04.03 18:58:45.214868 [ 1 ] {} <Information> DatabaseOrdinary (system): Total 0 tables and 0 dictionaries.
2020.04.03 18:58:45.214888 [ 1 ] {} <Information> DatabaseOrdinary (system): Starting up tables.
2020.04.03 18:58:45.218256 [ 1 ] {} <Information> DatabaseOrdinary (default): Total 0 tables and 0 dictionaries.
2020.04.03 18:58:45.218291 [ 1 ] {} <Information> DatabaseOrdinary (default): Starting up tables.
2020.04.03 18:58:45.218321 [ 1 ] {} <Debug> Application: Loaded metadata.
2020.04.03 18:58:45.218399 [ 1 ] {} <Trace> TraceCollector: Pipe capacity is 1.00 MiB
2020.04.03 18:58:45.218496 [ 1 ] {} <Information> BackgroundSchedulePool: Create BackgroundSchedulePool with 16 threads
2020.04.03 18:58:45.220331 [ 1 ] {} <Information> Application: It looks like the process has no CAP_NET_ADMIN capability, 'taskstats' performance statistics will be disabled. It could happen due to incorrect ClickHouse package installation. You could resolve the problem manually with 'sudo setcap cap_net_admin=+ep /usr/bin/clickhouse'. Note that it will not work on 'nosuid' mounted filesystems. It also doesn't work if you run clickhouse-server inside network namespace as it happens in some containers.
2020.04.03 18:58:45.220361 [ 1 ] {} <Information> Application: It looks like the process has no CAP_SYS_NICE capability, the setting 'os_thread_nice' will have no effect. It could happen due to incorrect ClickHouse package installation. You could resolve the problem manually with 'sudo setcap cap_sys_nice=+ep /usr/bin/clickhouse'. Note that it will not work on 'nosuid' mounted filesystems.
2020.04.03 18:58:45.221565 [ 1 ] {} <Information> Application: Shutting down storages.
2020.04.03 18:58:45.222077 [ 1 ] {} <Trace> BackgroundSchedulePool: Waiting for threads to finish.
2020.04.03 18:58:45.222166 [ 1 ] {} <Debug> Application: Shutted down storages.
2020.04.03 18:58:45.222923 [ 1 ] {} <Debug> Application: Destroyed global context.
**2020.04.03 18:58:45.223177 [ 1 ] {} <Error> Application: DB::Exception: Listen [::]:8123 failed: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = DNS error: EAI: -9 (version 19.17.5.18 (official build)**
2020.04.03 18:58:45.223202 [ 1 ] {} <Information> Application: shutting down
2020.04.03 18:58:45.223225 [ 1 ] {} <Debug> Application: Uninitializing subsystem: Logging Subsystem
2020.04.03 18:58:45.223317 [ 24 ] {} <Information> BaseDaemon: Stop SignalListener thread

**Comment by filimonov** [comment]
IPv6 is disabled in docker by default (check docker docs) . Normally it should not fail because config for docker contains listen_try, did you change the default  config?
