### ISSUE TITLE
Export sql query results to prometheus

### ISSUE THREAD

**Issue by Tri0L** [ClickHouse/ClickHouse#10043]
Please add ability to export result of SQL queries through prometheus functionality.

**Use case**
Monitor some params of tables.
For example size, number of parts, etc.

**Describe alternatives you've considered**
For now we use external exporter. And will be better to use only one(internal CH exporter).

**Comment by Tri0L** [comment]
related to #7900

**Comment by filimonov** [comment]
More related:
https://github.com/ClickHouse/ClickHouse/pull/9622
https://github.com/ClickHouse/ClickHouse/pull/7572

**Comment by filimonov** [comment]
See similar in PMM:
https://www.percona.com/blog/2020/06/23/extending-percona-monitoring-and-management-for-mysql-innodb-cluster-with-custom-queries/ 
https://github.com/percona/mysqld_exporter/blob/master/collector/custom_query.go 

There are several (currently 3) folders for resolutions  (high-resolution, med, low ) so we can control from the server-side what folder with queries need to be executed.

In PMM metrics collected by 3 resolutions (for the amount of data and lowering the load on the system). The same is applicable for Custom Queries.

**Comment by filimonov** [comment]
We can also consider generalizing that task a bit and expose the results of those custom queries in system.asynchronios_metrics.

Also we can add possibility to add custom labels to those metrics in system.asynchronios_metrics.

**Comment by UnamedRus** [comment]
Prometheus format https://github.com/ClickHouse/ClickHouse/pull/36206

Can be used in combination with https://github.com/ClickHouse/ClickHouse/pull/7572
