### ISSUE TITLE
Cannot open file /var/lib/clickhouse/data/db/table/tmp_insert_all_192_192_0/d_col3.mrk2 No space left on device

### ISSUE THREAD

**Issue by ssky1** [ClickHouse/ClickHouse#10041]
(you don't have to strictly follow this form)

**Describe the unexpected behaviour**

Hi, 

I am starting using clickhouse 

I have one distributed table with 237 columns pointing one table (ENGINE = MergeTree()) 
In order to insert 200k rows in my table ( through the  distributed table)  , I am using the jdbc driver (clickhouse-jdbc-0.2.4.jar) ==>  addBatch ==> executeBatch 
the batchsize = 1000 rows 

When I run my job, i got this error 
Cannot open file /var/lib/clickhouse/data/db/table/tmp_insert_all_192_192_0/d_col3.mrk2 No space left on device

after the job got failed, i ran this command to check inode 
df -i /var/lib/clickhouse/data/db/table/
Sys. de fichiers         Inœuds IUtil. ILibre IUti% Monté sur
/dev/mapper/rootvg-varlv 131072  40501  90571   31% /var

so there is 40501  free inode, that big no ?!!

I run this command to check free space 

df -h /var/lib/clickhouse/

Sys. de fichiers         Taille Utilisé Dispo Uti% Monté sur
/dev/mapper/rootvg-varlv   2,0G    652M  1,2G  36% /var

652M free space , isn't enough ? (my 200k rows size are less than 300mb in text file) 

I run this command 

ulimit -a 

core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 31122
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 31122
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

is open files  (-n) 1024  not enough ?

I did another  test with just 8 columns of the file 
so i created a second distributed table pointing a table  (ENGINE = MergeTree())  to insert the 200k rows in batch mode    addBatch ==> executeBatch (through the driver (clickhouse-jdbc-0.2.4.jar) )

when i run the job, it's ok but  it's sow slow, it took half a hour to finish !!
so i am saying that's can't be right 
is the problem coming from the driver ?  

thanks for your help !

A clear and concise description of what works not as it is supposed to.

**How to reproduce**
* Which ClickHouse server version to use
ClickHouse server version 20.3.4

* Which interface to use, if matters
jdbc driver  clickhouse-jdbc-0.2.4.jar 

* Non-default settings, if any

* `CREATE TABLE` statements for all tables involved

CREATE TABLE db.tablet(
  col1 String, 
  col2 String, 
  col3 String, 
  col4 String, 
  col5 String, 
  col6 String)
  ENGINE = MergeTree() 
PRIMARY KEY col1
ORDER BY col1;

CREATE TABLE db.tablet_all AS db.tablet
ENGINE = Distributed(test_cluster_two_shards, db, tablet, rand());

* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

public void call(java.util.Iterator<row1Struct> dataIterator)
			throws java.lang.Exception {
		java.sql.Connection connection = tJDBCConfiguration_1_ConnectionPool
				.get(context).borrowObject();
		try {

			java.sql.PreparedStatement pstmt_tJDBCOutput_2 = connection
					.prepareStatement("INSERT INTO "
							+ "clickhouse_distributed_table"
							+ " (col1,col2,col3,col4,col5,col6) VALUES(?,?,?,?,?,?)");
			while (dataIterator.hasNext()) {
				row1Struct conntJDBCOutput_2_1 = dataIterator.next();
				if (conntJDBCOutput_2_1.col1 == null) {
					pstmt_tJDBCOutput_2.setNull(1, java.sql.Types.VARCHAR);
				} else {
					pstmt_tJDBCOutput_2.setString(1,
							conntJDBCOutput_2_1.col1);
				}

				if (conntJDBCOutput_2_1.col2 == null) {
					pstmt_tJDBCOutput_2.setNull(2, java.sql.Types.VARCHAR);
				} else {
					pstmt_tJDBCOutput_2.setString(2,
							conntJDBCOutput_2_1.col2);
				}

				if (conntJDBCOutput_2_1.col3 == null) {
					pstmt_tJDBCOutput_2.setNull(3, java.sql.Types.VARCHAR);
				} else {
					pstmt_tJDBCOutput_2.setString(3,
							conntJDBCOutput_2_1.col3);
				}

				if (conntJDBCOutput_2_1.col4 == null) {
					pstmt_tJDBCOutput_2.setNull(4, java.sql.Types.VARCHAR);
				} else {
					pstmt_tJDBCOutput_2.setString(4,
							conntJDBCOutput_2_1.col4);
				}

				if (conntJDBCOutput_2_1.col5 == null) {
					pstmt_tJDBCOutput_2.setNull(5, java.sql.Types.VARCHAR);
				} else {
					pstmt_tJDBCOutput_2.setString(5,
							conntJDBCOutput_2_1.col5);
				}

				if (conntJDBCOutput_2_1.col6 == null) {
					pstmt_tJDBCOutput_2.setNull(6, java.sql.Types.VARCHAR);
				} else {
					pstmt_tJDBCOutput_2.setString(6,
							conntJDBCOutput_2_1.col6);
				}

				pstmt_tJDBCOutput_2.addBatch();
				batchSizeCounter++;
				if (batchSizeCounter >= batchSize) {
					try {
						pstmt_tJDBCOutput_2.executeBatch();
					} catch (Exception e) {
						throw (e);
					}
					pstmt_tJDBCOutput_2.clearBatch();
					batchSizeCounter = 0;
				}

			} // end while (dataIterator.hasNext())

			if (batchSizeCounter != 0) {
				try {
					pstmt_tJDBCOutput_2.executeBatch();
				} catch (Exception e) {
					throw (e);
				}
				pstmt_tJDBCOutput_2.clearBatch();
			}

			pstmt_tJDBCOutput_2.close();

		} finally {
			if (connection != null) {
				tJDBCConfiguration_1_ConnectionPool.get(context)
						.returnObject(connection);
			}
		}
	}

**Expected behavior**

I was expecting the 200K rows will be inserted quickly 

**Error message and/or stacktrace**

Caused by: ru.yandex.clickhouse.except.ClickHouseException: ClickHouse exception, code: 76, host: 10.37.121.51, port: 8123; Code: 76, e.displayText() = DB::ErrnoException: Cannot open file /var/lib/clickhouse/data/db/table/tmp_insert_all_192_192_0/col112.mrk2, errno: 28, strerror: No space left on device
Total space: 1.91 GiB
Available space: 826.64 MiB
Total inodes: 131.07 thousand
Available inodes: 104.00
Mount point: /var
Filesystem: /dev/mapper/rootvg-varlv (version 20.3.4.10 (official build))

**Additional context**

**Comment by filimonov** [comment]
> so there is 40501 free inode, that big no ?!!

If depends. You have table with 237 columns, so clickhouse with each insert will create 237*2 files + about 5 more.

So you need 480 files / inodes per insert. By looking on the part number i can decuct that you did about 200 inserts before the error. 480*200 = 96000, and your out of inodes. And the error message shows you that at the moment of exeption there were only
```
Available inodes: 104
```
Which is very small.

**Comment by ssky1** [comment]
hi filimonov,

just for my understanding, each insert row is one insert or each batch insert (batchSize = 1000 rows) is one insert !

I explain  myself 

 if I have 500GB dedecated to clickhouse data ( 3 2768 000 inodes) 

32 768 000 indoes / 480 (files  per insert ) = 68k inserts 
as I am using batchInsert with batch size = 1000 rows (each excuteBatch would insert 1000 rows
so I can't insert more than 1000 * 68 000 = 68M rows ! (with 3 2768 000 inodes)

is it right ?

the second question is the insert performance ! 

when I am using ClickHouse-Native-JDBC.jar  for the same insert  to insert the 200k rows in the same table, it takes much less time to insert than clickhouse-jdbc.jar 

is it the normal ?

thanks

**Comment by alexey-milovidov** [comment]
@ssky1 Yes, it's expected that ClickHouse-JDBC driver is slower than ClickHouse-Native-JDBC and it's consequently slower than clickhouse-client.

**Comment by alexey-milovidov** [comment]
No space left on device - is the error we get from the OS. Multiple reasons possible...

**Comment by alexey-milovidov** [comment]
When you insert small amount of data in a short period of time, it may take a few times more space due to write amplification (background merging of data parts). But this write amplification will be cleaned up after 8 minutes (the default lifetime of data parts after background merge).
