### ISSUE TITLE
FORMAT Parquet schema information extraction and map columns

### ISSUE THREAD

**Issue by fhmcn** [ClickHouse/ClickHouse#10048]
**Use case**
Inserting into a table with Parquet format without knowing table structure. There might be cases that table has new columns or dropped columns. Parquet format should be able to handle them using SETTING as similar is done for JSONEachRow using `input_format_skip_unknown_fields=1`

**Describe the solution you'd like**
Using FORMAT Parquet, inserts must be able to match table structure and parquet schema. 

**Describe alternatives you've considered**
Current solution is to extract schema information and table metadata then mapping put columns to query 
`INSERT INTO test.table (<columns_here>) FORMAT Parquet`

**Comment by filimonov** [comment]
Schema inference for parquet was added (check recent clickhouse versions)
