### ISSUE TITLE
Search in documentation does not working properly

### ISSUE THREAD

**Issue by SButterfly** [ClickHouse/ClickHouse#10079]
I tried to find for "dateDiff", but search said that there are not results. But actually this method exists:
https://clickhouse.tech/docs/en/sql_reference/functions/date_time_functions/
![image](https://user-images.githubusercontent.com/4300612/78644648-e0459f80-78be-11ea-9814-f145ad2c9cea.png)

**Comment by blinkov** [comment]
@SButterfly we're working on this. As a workaround you can use docs from some recent stable release, https://clickhouse.tech/docs/v20.3/en/

**Comment by blinkov** [comment]
Fixed.
