### ISSUE TITLE
SQL case sensitive

### ISSUE THREAD

**Issue by gubinjie** [ClickHouse/ClickHouse#10078]
I would like to ask if there is a difference in the case of fields in SQL? Because we are using version 19.16.4.12, no case has been found to cause anomalies before. Recently, Missing Columns due to capitalization of fields have suddenly appeared.

Thank you

**Comment by alexey-milovidov** [comment]
Names of identifiers in ClickHouse SQL dialect are case sensitive.

(and it was not changed in any release)
