### ISSUE TITLE
Max concurrent queries setting

### ISSUE THREAD

**Issue by ernestoeperez88** [ClickHouse/ClickHouse#10089]
Could you please provide some guidance as to how the `max_concurrent_queries` setting can scale up as resources increase?

My assumption is that the default value of `100` is based on a system with the minimum requirements mentioned [here](https://github.com/ClickHouse/ClickHouse/blob/master/docs/en/operations/requirements.md).

We are running clickhouse out of a server with 16 cpu/ 64 cores / 396 GB RAM, and we are wondering how much can we increase `max_concurrent_queries`.

**Comment by den-crane** [comment]
there is no guidance. It is just safe-limiter against spontaneous resource utilization burst.
If your system is able to handle more than 100 you can set any number.
