### ISSUE TITLE
where config insert_quorum

### ISSUE THREAD

**Issue by ZENGJINHUAI** [ClickHouse/ClickHouse#10081]
have seen  https://clickhouse.tech/docs/en/operations/settings/settings/#settings-insert_quorum but not found where to config it.
I config "<insert_quorum>2</insert_quorum>"  in config.xml and metrika.xml. but not work.
"select * from system.settings where name like '%insert_quorum%';"  and it still zero.

**Comment by xiashuijun** [comment]
users.xml ，在这里配置

**Comment by xiashuijun** [comment]
users.xml配置，src/Core/Settings.h

**Comment by filimonov** [comment]
You need to put it info default profile in user.xml

**Comment by BayoNet** [comment]
It looks like the [Settings Introduction](http://localhost/docs/en/operations/settings/) topic also answers this question.
