### ISSUE TITLE
Add origin description to system.part_log

### ISSUE THREAD

**Issue by akuzm** [ClickHouse/ClickHouse#10097]
We can add a column named 'origin', and put query_id there for inserted parts.
Probably we can also put replica path there for downloaded parts.

This will simplify the debugging for insert queries.

**Comment by alexey-milovidov** [comment]
Let's name this column `query_id` for consistency.

**Comment by ucasFL** [comment]
Seems that the `system.part_log` table doesn't exist any more. @akuzm

**Comment by akuzm** [comment]
> Seems that the `system.part_log` table doesn't exist any more. @akuzm

Should exist... Did you enable it in server config? Here: https://github.com/ClickHouse/ClickHouse/blob/master/programs/server/config.xml#L700
