### ISSUE TITLE
build faild on mac

### ISSUE THREAD

**Issue by SalleryWang** [ClickHouse/ClickHouse#10091]
[2237/4393] Building CXX object base/loggers/CMakeFiles/loggers.dir/OwnPatternFormatter.cpp.o
FAILED: base/loggers/CMakeFiles/loggers.dir/OwnPatternFormatter.cpp.o
/usr/bin/clang++  -DBOOST_SYSTEM_NO_DEPRECATED -DPOCO_NO_AUTOMATIC_LIBS -DPOCO_STATIC -DPOCO_UNBUNDLED_ZLIB -DUNALIGNED_OK -DUSE_FASTMEMCPY=0 -DUSE_REPLXX=1 -DWITH_COVERAGE=0 -DWITH_GZFILEOP -DX86_64 -DZLIB_COMPAT -Iincludes/configs -I../base/loggers/.. -Isrc/Core/include -I../src -Isrc -I../base/common/.. -Ibase/common/.. -I../contrib/zlib-ng -Icontrib/zlib-ng -I../contrib/cityhash102/include -I../contrib/replxx/include -isystem ../contrib/libcxx/include -isystem ../contrib/libcxxabi/include -isystem ../contrib/pdqsort -isystem ../contrib/libpcg-random/include -isystem ../contrib/double-conversion -isystem ../contrib/re2 -isystem ../contrib/poco/Net/include -isystem ../contrib/poco/Foundation/include -isystem ../contrib/poco/Util/include -isystem ../contrib/poco/XML/include -isystem ../contrib/poco/JSON/include -isystem ../contrib/boost -isystem ../contrib/ryu -isystem contrib/re2_st -isystem ../contrib/croaring -fdiagnostics-color=always -std=c++2a -fsized-deallocation  -gdwarf-aranges -msse4.1 -msse4.2 -mpopcnt   -Wall -Wno-unused-command-line-argument  -Wnon-virtual-dtor -fno-omit-frame-pointer -stdlib=libc++ -Wl,-U,_inside_main -Werror -mmacosx-version-min=10.15 -O2 -g -DNDEBUG -O3    -D OS_DARWIN -nostdinc++ -Wno-documentation -MD -MT base/loggers/CMakeFiles/loggers.dir/OwnPatternFormatter.cpp.o -MF base/loggers/CMakeFiles/loggers.dir/OwnPatternFormatter.cpp.o.d -o base/loggers/CMakeFiles/loggers.dir/OwnPatternFormatter.cpp.o -c ../base/loggers/OwnPatternFormatter.cpp
In file included from ../base/loggers/OwnPatternFormatter.cpp:6:
In file included from ../src/IO/WriteBufferFromString.h:5:
In file included from ../base/loggers/../common/StringRef.h:8:
../base/loggers/../common/types.h:14:15: error: unknown type name 'char8_t'
using UInt8 = char8_t;
              ^
In file included from ../base/loggers/OwnPatternFormatter.cpp:7:
In file included from ../src/IO/WriteHelpers.h:9:
In file included from ../base/loggers/../common/DateLUT.h:3:
../base/loggers/../Common/DateLUTImpl.h:25:27: error: unknown type name 'UInt8'; did you mean 'Int8'?
enum class WeekModeFlag : UInt8
                          ^~~~~
                          Int8
../base/loggers/../Common/types.h:9:7: note: 'Int8' declared here
using Int8 = int8_t;
      ^
In file included from ../base/loggers/OwnPatternFormatter.cpp:7:
In file included from ../src/IO/WriteHelpers.h:9:
In file included from ../base/loggers/../common/DateLUT.h:3:
../base/loggers/../Common/DateLUTImpl.h:32:36: error: unknown type name 'UInt8'; did you mean 'Int8'?
using YearWeek = std::pair<UInt16, UInt8>;
                                   ^~~~~

[2238/4393] Building CXX object contrib/arrow-cmake/CMakeFiles/arrow_static.dir/__/arrow/cpp/src/arrow/scalar.cc.o
ninja: build stopped: subcommand failed.

**Comment by alexey-milovidov** [comment]
You are using old compiler from OS.
Instead, you should install fresh `clang` version. The minimum version is 9.
This manual should work: https://clickhouse.tech/docs/en/development/build_osx/

**Comment by alexey-milovidov** [comment]
@qoega Please validate that everything is correct.
