### ISSUE TITLE
PREWHERE cannot contain ARRAY JOIN or JOIN action

### ISSUE THREAD

**Issue by akuzm** [ClickHouse/ClickHouse#10092]
With `visits` table from [Yandex.Metrika dataset](https://clickhouse.tech/docs/en/getting_started/example_datasets/metrica/):

```
SELECT 
    arrayJoin([0]) AS browser, 
    arrayJoin([SearchEngineID]) AS search_engine, 
    URL
FROM visits
WHERE 1 AND (SearchEngineID != 0) AND (browser != 0) AND (search_engine != 0)

Received exception from server (version 20.4.1):
Code: 182. DB::Exception: Received from localhost:9000. DB::Exception: PREWHERE cannot contain ARRAY JOIN or JOIN action. Stack trace:
```

Does not reproduce with `set optimize_move_to_prewhere = 0`.

**Comment by alexey-milovidov** [comment]
FYI. In my case it reproduces on `hits` table, not `visits`.

**Comment by alexey-milovidov** [comment]
According to the code, it was broken long time ago.

**Comment by alexey-milovidov** [comment]
More than one year ago, starting from 19.4.

**Comment by alexey-milovidov** [comment]
But it works on 19.4.

**Comment by alexey-milovidov** [comment]
Minimal reproducing example:
`SELECT arrayJoin([SearchEngineID]) AS search_engine, URL FROM test.hits WHERE SearchEngineID != 0 AND search_engine != 0`
