### ISSUE TITLE
when "select * from remote" lost data

### ISSUE THREAD

**Issue by eiffel0311** [ClickHouse/ClickHouse#10116]
when i run: insert into default.tableA select * from remote('x.x.x.x', 'dbName', 'tableB')
no exception and error log, but the count of tableA more then tableB. means tableB lost a lot of data.

**Comment by xiashuijun** [comment]
你是不是tableA的数据没有清除干净，又往里面写。因为clickhouse要过一会才能看到数据

**Comment by den-crane** [comment]
What CH version do you use? 

Can you show 'show create table A' and  'show create table B'

**Comment by eiffel0311** [comment]
> 你是不是tableA的数据没有清除干净，又往里面写。因为clickhouse要过一会才能看到数据

i create new tableA and select * from sysytem.mutations . i am sure the query done

**Comment by eiffel0311** [comment]
> What CH version do you use?
> 
> Can you show 'show create table A' and 'show create table B'
tableB(from table tableB):
CREATE TABLE tutorial.dws_brand_ss (
`industry_id` UInt16,
 `doc_id` UInt64,
 `account_name` String,
 `account_type_id` UInt8,
 `collect_cnt` Nullable(UInt32),
 `reply_cnt` UInt32,
 `forward_cnt` UInt32,
 `praise_cnt` UInt32,
 `view_cnt` UInt32,
 `engagement_cnt` Nullable(UInt32),
 `fans_cnt` Nullable(UInt32),
 `media_id` UInt32,
 `sentiment_type_id` Int8,
 `brand_id` UInt32,
 `pub_day_date` Date,
 `pub_week_date` Date,
 `pub_month_date` Date,
 `pub_quarter_date` Date,
 `pub_year_date` Date,
 `keyword` Array(String),
 `word_frequency` Array(UInt16)
) ENGINE = MergeTree() PARTITION BY toYYYYMM(pub_day_date) ORDER BY (pub_day_date, industry_id, brand_id, media_id, account_type_id, sentiment_type_id) SETTINGS index_granularity = 8192

tableA(insert tableA):
CREATE TABLE metrics.dws_brand_ss on cluster s1r2 (
`industry_id` UInt16,
 `doc_id` UInt64,
 `account_name` String,
 `account_type_id` UInt8,
 `collect_cnt` Nullable(UInt32),
 `reply_cnt` UInt32,
 `forward_cnt` UInt32,
 `praise_cnt` UInt32,
 `view_cnt` UInt32,
 `engagement_cnt` Nullable(UInt32),
 `fans_cnt` Nullable(UInt32),
 `media_id` UInt32,
 `sentiment_type_id` Int8,
 `brand_id` UInt32,
 `pub_day_date` Date,
 `pub_week_date` Date,
 `pub_month_date` Date,
 `pub_quarter_date` Date,
 `pub_year_date` Date,
 `keyword` Array(String),
 `word_frequency` Array(UInt16)
) ENGINE = ReplicatedMergeTree('/clickhouse/metrics/{shard}/dws_brand_ss','{replica}')
PARTITION BY toYYYYMM(pub_day_date) ORDER BY (pub_day_date, industry_id, brand_id, media_id, account_type_id, sentiment_type_id) SETTINGS index_granularity = 8192


then i run
insert into metrics.dws_brand_ss select * from remote('xx.xx.xx.xx', 'tutorial.dws_brand_ss')

the metrics.dws_brand_ss has 106496
tutorial.dws_brand_ss has record 10242093

**Comment by filimonov** [comment]
Maybe remote server just stops the query in the middle? Some query complexity limitation configured + overflow mode = break. Check https://github.com/ClickHouse/ClickHouse/blob/master/docs/en/operations/settings/query_complexity.md

It would be nice to get trace logs from both servers.

**Comment by robot-clickhouse** [comment]
@eiffel0311, do you have any further questions?
