### ISSUE TITLE
CH cluster unable to open remote connection

### ISSUE THREAD

**Issue by fangru07** [ClickHouse/ClickHouse#10111]
when i remove comment,the clickhouse can not start,So what should i do,
 <listen_host>::</listen_host>
This is error log,

2020.04.08 09:59:11.349025 [ 1 ] {} <Error> Application: DB::Exception: Listen [0.0.0.0]:9000 failed: Poco::Exception. Code: 1000, e.code() = 98, e.displayText() = Net Exception: Address already in use: 0.0.0.0:9000 (version 20.1.8.41)
2020.04.08 10:00:02.033031 [ 1 ] {} <Error> Application: DB::Exception: Listen [0.0.0.0]:9000 failed: Poco::Exception. Code: 1000, e.code() = 98, e.displayText() = Net Exception: Address already in use: 0.0.0.0:9000 (version 20.1.8.41)
2020.04.08 10:07:06.471025 [ 1 ] {} <Error> Application: DB::Exception: Listen [::]:9000 failed: Poco::Exception. Code: 1000, e.code() = 98, e.displayText() = Net Exception: Address already in use: [::]:9000 (version 20.1.8.41)
2020.04.08 10:10:01.178051 [ 1 ] {} <Error> Application: DB::Exception: Listen [::]:9000 failed: Poco::Exception. Code: 1000, e.code() = 98, e.displayText() = Net Exception: Address already in use: [::]:9000 (version 20.1.8.41)
2020.04.08 10:20:01.293852 [ 1 ] {} <Error> Application: DB::Exception: Listen [::]:9000 failed: Poco::Exception. Code: 1000, e.code() = 98, e.displayText() = Net Exception: Address already in use: [::]:9000 (version 20.1.8.41)
2020.04.08 10:30:01.421423 [ 1 ] {} <Error> Application: DB::Exception: Listen [::]:9000 failed: Poco::Exception. Code: 1000, e.code() = 98, e.displayText() = Net Exception: Address already in use: [::]:9000 (version 20.1.8.41)

Thank you.

**Comment by qoega** [comment]
have you checked that there is no other application that listen for роrt 9000?

**Comment by fangru07** [comment]
> 您是否检查过没有其他应用可以监听роrt9000？

no,don`t open remote connection can start,so i think port 9000 is no problem

**Comment by filimonov** [comment]
Most probably you have <listen_host> listed twice, and clickhouse trys to listen same interface several times.
