### ISSUE TITLE
Cannot post update query with using file like in select queries. 

### ISSUE THREAD

**Issue by coolpsix** [ClickHouse/ClickHouse#10127]
select like this is work:
...&query=select+ID+from+tmp+where+ID+in+tmp+format+RowBinary&tmp_structure=ID+UInt32&tmp_format=RowBinary
but alter update like this:
...&query=alter+table+tbl+update+a%3D1+where+b+in+tmp&tmp_structure=ID+UInt32&tmp_format=RowBinary
returns thats all ok, but not update data and write to log that cannot find default.tmp table.

latest_fail_reason:         Code: 60, e.displayText() = DB::Exception: Table default.tmp doesn't exist. (version 20.3.5.21 (official build))

2020.04.08 16:25:40.397586 [ 19370 ] {} <Error> void DB::BackgroundProcessingPool::threadFunction(): Code: 60, e.displayText() = DB::Exception: Table default.tmp doesn't exist., Stack trace (when copying this message, always include the
lines below):

0. /build/obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/Exception.cpp:27: Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x1050f0d0 in /usr/lib/debug/
usr/bin/clickhouse
1. /build/obj-x86_64-linux-gnu/../dbms/src/Common/Exception.cpp:29: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x8f3272d in /usr/lib/debug/usr/bin/clickho
use
2. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/optional:324: DB::Context::getTableImpl(DB::StorageID const&, std::__1::optional<DB::Exception>*) const @ 0xcfc92c4 in /usr/lib/debug/usr/bin/clickhouse
3. /build/obj-x86_64-linux-gnu/../dbms/src/Interpreters/Context.cpp:1030: DB::Context::getTable(DB::StorageID const&) const @ 0xcfc945b in /usr/lib/debug/usr/bin/clickhouse
4. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/string:2134: DB::Context::getTable(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<
char>, std::__1::allocator<char> > const&) const @ 0xcfc951d in /usr/lib/debug/usr/bin/clickhouse
5. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:3826: DB::SelectQueryExpressionAnalyzer::isPlainStorageSetInSubquery(std::__1::shared_ptr<DB::IAST> const&) @ 0xd2d8f30 in /usr/lib/debug/usr/bin/clickhouse
6. /build/obj-x86_64-linux-gnu/../dbms/src/Interpreters/ExpressionAnalyzer.cpp:291: DB::SelectQueryExpressionAnalyzer::tryMakeSetForIndexFromSubquery(std::__1::shared_ptr<DB::IAST> const&) @ 0xd2e2ac0 in /usr/lib/debug/usr/bin/clickhouse
7. /build/obj-x86_64-linux-gnu/../dbms/src/Interpreters/ExpressionAnalyzer.cpp:363: DB::SelectQueryExpressionAnalyzer::makeSetsForIndex(std::__1::shared_ptr<DB::IAST> const&) @ 0xd2e3623 in /usr/lib/debug/usr/bin/clickhouse
8. /build/obj-x86_64-linux-gnu/../dbms/src/Interpreters/ExpressionAnalyzer.cpp:348: DB::SelectQueryExpressionAnalyzer::makeSetsForIndex(std::__1::shared_ptr<DB::IAST> const&) @ 0xd2e365b in /usr/lib/debug/usr/bin/clickhouse
9. /build/obj-x86_64-linux-gnu/../dbms/src/Interpreters/ExpressionAnalyzer.cpp:348: DB::SelectQueryExpressionAnalyzer::makeSetsForIndex(std::__1::shared_ptr<DB::IAST> const&) @ 0xd2e365b in /usr/lib/debug/usr/bin/clickhouse
10. /build/obj-x86_64-linux-gnu/../dbms/src/Interpreters/InterpreterSelectQuery.cpp:474: DB::InterpreterSelectQuery::getSampleBlockImpl(bool) @ 0xd121a9e in /usr/lib/debug/usr/bin/clickhouse
11. /build/obj-x86_64-linux-gnu/../dbms/src/Interpreters/InterpreterSelectQuery.cpp:297: DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, std::__1::shared_ptr<DB::IBlockInputSt
ream> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::alloc
ator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&)::'lambda'(bool)::operator()(bool) const @ 0xd12349b in /usr/lib/debug/usr/bin/clickhouse
12. /build/obj-x86_64-linux-gnu/../dbms/src/Interpreters/InterpreterSelectQuery.cpp:371: DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, std::__1::shared_ptr<DB::IBlockInputSt
ream> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::alloc
ator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0xd1240cc in /usr/lib/debug/usr/bin/clickhouse
13. /build/obj-x86_64-linux-gnu/../dbms/src/Interpreters/InterpreterSelectQuery.cpp:191: DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, std::__1::shared_ptr<DB::IStorage> con
st&, DB::SelectQueryOptions const&) @ 0xd125a20 in /usr/lib/debug/usr/bin/clickhouse
14. /build/obj-x86_64-linux-gnu/../dbms/src/Interpreters/MutationsInterpreter.cpp:176: DB::isStorageTouchedByMutations(std::__1::shared_ptr<DB::IStorage>, std::__1::vector<DB::MutationCommand, std::__1::allocator<DB::MutationCommand> > c
onst&, DB::Context) @ 0xd458819 in /usr/lib/debug/usr/bin/clickhouse
15. /build/obj-x86_64-linux-gnu/../dbms/src/Storages/MergeTree/MergeTreeDataMergerMutator.cpp:978: DB::MergeTreeDataMergerMutator::mutatePartToTemporaryPart(DB::FutureMergedMutatedPart const&, DB::MutationCommands const&, DB::MergeListEn
try&, long, DB::Context const&, std::__1::unique_ptr<DB::IReservation, std::__1::default_delete<DB::IReservation> > const&, DB::TableStructureReadLockHolder&) @ 0xd9121ad in /usr/lib/debug/usr/bin/clickhouse
16. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/type_traits:3696: DB::StorageMergeTree::tryMutatePart() @ 0xd71771c in /usr/lib/debug/usr/bin/clickhouse
17. /build/obj-x86_64-linux-gnu/../dbms/src/Storages/StorageMergeTree.cpp:836: DB::StorageMergeTree::mergeMutateTask() @ 0xd717d6b in /usr/lib/debug/usr/bin/clickhouse
18. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:1867: DB::BackgroundProcessingPool::threadFunction() @ 0xd88736b in /usr/lib/debug/usr/bin/clickhouse
19. /build/obj-x86_64-linux-gnu/../dbms/src/Common/ThreadPool.h:159: ThreadFromGlobalPool::ThreadFromGlobalPool<DB::BackgroundProcessingPool::BackgroundProcessingPool(int, DB::BackgroundProcessingPool::PoolSettings const&, char const*, c
har const*)::'lambda'()>(DB::BackgroundProcessingPool::BackgroundProcessingPool(int, DB::BackgroundProcessingPool::PoolSettings const&, char const*, char const*)::'lambda'()&&)::'lambda'()::operator()() const @ 0xd887d60 in /usr/lib/debu
g/usr/bin/clickhouse
20. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/atomic:856: ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x8f567eb in /usr/lib/debug/usr/bin/clickhouse
21. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2615: void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolI
mpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()> >(void*) @ 0x8f54c33 in /usr/lib/debug/usr/bin/clickhouse
22. start_thread @ 0x76db in /lib/x86_64-linux-gnu/libpthread-2.27.so
23. clone @ 0x12188f in /lib/x86_64-linux-gnu/libc-2.27.so
 (version 20.3.5.21 (official build))

**Comment by coolpsix** [comment]
After one error all mutations fails with the same error even if they don't use it and worked before.

**Comment by filimonov** [comment]
Mutations are executed asynchronously, out of current query context.

```
create table x Engine=MergeTree ORDER BY tuple() as SELECT * FROM numbers(100);
create temporary table y as select * from numbers(10);
alter table x update number=number+1000 where number in (y);
alter table x update number=number+1000 where number=80;
```

> After one error all mutations fails with the same error even if they don't use it and worked before.

That is correct. Mutation should executed in sequence (because later change may depend on previus change). You can kill bad mutations to unlock the mutations queue. 


```
e498b14ba680 :) select * from system.mutations;

SELECT *
FROM system.mutations

┌─database─┬─table─┬─mutation_id────┬─command───────────────────────────────────────────────────┬─────────create_time─┬─block_numbers.partition_id─┬─block_numbers.number─┬─parts_to_do_names─┬─parts_to_do─┬─is_done─┬─latest_failed_part─┬────latest_fail_time─┬─latest_fail_reason─────────────────────────────────────────────────────────────────────────────────────────────┐
│ default  │ x     │ mutation_3.txt │ UPDATE number = number + 1000 WHERE number IN (default.y) │ 2020-04-09 13:56:35 │ ['']                       │ [3]                  │ ['all_1_1_0']     │           1 │       0 │ all_1_1_0          │ 2020-04-09 13:56:43 │ Code: 60, e.displayText() = DB::Exception: Table default.y doesn't exist. (version 20.3.5.21 (official build)) │
│ default  │ x     │ mutation_4.txt │ UPDATE number = number + 1000 WHERE number = 80           │ 2020-04-09 13:56:43 │ ['']                       │ [4]                  │ ['all_1_1_0']     │           1 │       0 │ all_1_1_0          │ 2020-04-09 13:56:43 │ Code: 60, e.displayText() = DB::Exception: Table default.y doesn't exist. (version 20.3.5.21 (official build)) │
└──────────┴───────┴────────────────┴───────────────────────────────────────────────────────────┴─────────────────────┴────────────────────────────┴──────────────────────┴───────────────────┴─────────────┴─────────┴────────────────────┴─────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

2 rows in set. Elapsed: 0.002 sec. 

e498b14ba680 :) kill mutation where mutation_id = 'mutation_3.txt';

KILL MUTATION WHERE mutation_id = 'mutation_3.txt' ASYNC

┌─kill_status─┬─database─┬─table─┬─mutation_id────┐
│ waiting     │ default  │ x     │ mutation_3.txt │
└─────────────┴──────────┴───────┴────────────────┘

1 rows in set. Elapsed: 0.004 sec. 

e498b14ba680 :) select * from system.mutations;

SELECT *
FROM system.mutations

┌─database─┬─table─┬─mutation_id────┬─command─────────────────────────────────────────┬─────────create_time─┬─block_numbers.partition_id─┬─block_numbers.number─┬─parts_to_do_names─┬─parts_to_do─┬─is_done─┬─latest_failed_part─┬────latest_fail_time─┬─latest_fail_reason─┐
│ default  │ x     │ mutation_4.txt │ UPDATE number = number + 1000 WHERE number = 80 │ 2020-04-09 13:56:43 │ ['']                       │ [4]                  │ []                │           0 │       1 │                    │ 0000-00-00 00:00:00 │                    │
└──────────┴───────┴────────────────┴─────────────────────────────────────────────────┴─────────────────────┴────────────────────────────┴──────────────────────┴───────────────────┴─────────────┴─────────┴────────────────────┴─────────────────────┴────────────────────┘

1 rows in set. Elapsed: 0.004 sec. 
```
```
