### ISSUE TITLE
Revert alter query/mutations?

### ISSUE THREAD

**Issue by mrAndersen** [ClickHouse/ClickHouse#10123]
By mistake I have executed following alter query
`alter table some_table delete where datetime > time` with incorrect time specified, so more data than expected were removed.

Any chances I can somehow get it back? I saw that there are mutation_* .txt files in data directory + partitions are still in place...

**Comment by alesapin** [comment]
If less than 8 minutes passed you can detach `ALTER TABLE DETACH PARTITION` all partitions from your table and than found source parts for your mutation in `/detached` directory. For example: `all_1_10_1_132` -- mutated part, source part can have name `all_1_10_1_100` (the fifth number is less than in mutated part) or without fifth number `all_1_10_1` if it was the first mutation on your table.  After that, you should attach all partitions with `ALTER TABLE ATTACH PARTITION`. But if 8 minutes already passed all source parts should be already deleted from file system :(

**Comment by mrAndersen** [comment]
@alesapin more than 8 minutes passed :(
