### ISSUE TITLE
Alter table drop column returns DB::Exception: St8bad_cast: std::bad_cast

### ISSUE THREAD

**Issue by cw9** [ClickHouse/ClickHouse#10132]
Sometimes ReplicatedMergeTree table could stuck in a state that both `Alter table add column` and `Alter table drop column` would return error `DB::Exception: St8bad_cast: std::bad_cast.`

**How to reproduce**
This is hard to reproduce, we have the same table built on hundreds of hosts, but only some of them would return this error.

* Which ClickHouse server version to use
20.3.5.21
* Which interface to use, if matters
Both native and HTTP

**Expected behavior**
The add column and drop column should return successfully

**Error message and/or stacktrace**
<Error> executeQuery: std::exception. Code: 1001, type: std::bad_cast, e.what() = std::bad_cast (version 20.3.5.21 (official build)) (from IP:50746) (in query: ALTER TABLE `foo` ADD COLUMN `a1` String ), Stack trace (when copying this message, always include the lines below):

0. /build/contrib/libcxx/include/exception:129: std::bad_cast::bad_cast() @ 0x1109db7a in /usr/lib/debug/usr/bin/clickhouse
1. /build/obj-x86_64-linux-gnu/../contrib/libcxxabi/src/cxa_aux_runtime.cpp:20: __cxa_bad_cast @ 0x1109dbe6 in /usr/lib/debug/usr/bin/clickhouse
2. /build/obj-x86_64-linux-gnu/../dbms/src/Storages/StorageReplicatedMergeTree.cpp:3414: DB::StorageReplicatedMergeTree::alter(DB::AlterCommands const&, DB::Context const&, DB::TableStructureWriteLockHolder&) (.cold) @ 0xd79494c in /usr/lib/debug/usr/bin/clickhouse
3. /build/obj-x86_64-linux-gnu/../dbms/src/Interpreters/InterpreterAlterQuery.cpp:116: DB::InterpreterAlterQuery::execute() @ 0xd08cbf2 in /usr/lib/debug/usr/bin/clickhouse
4. /build/obj-x86_64-linux-gnu/../dbms/src/Interpreters/executeQuery.cpp:328: DB::executeQueryImpl(char const*, char const*, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool, DB::ReadBuffer*, bool) @ 0xd535848 in /usr/lib/debug/usr/bin/clickhouse
5. /build/obj-x86_64-linux-gnu/../dbms/src/Interpreters/executeQuery.cpp:572: DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool, bool) @ 0xd538471 in /usr/lib/debug/usr/bin/clickhouse
6. /build/obj-x86_64-linux-gnu/../dbms/programs/server/TCPHandler.cpp:249: DB::TCPHandler::runImpl() @ 0x9015119 in /usr/lib/debug/usr/bin/clickhouse
7. /build/obj-x86_64-linux-gnu/../dbms/programs/server/TCPHandler.cpp:1235: DB::TCPHandler::run() @ 0x9016100 in /usr/lib/debug/usr/bin/clickhouse
8. /build/obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServerConnection.cpp:57: Poco::Net::TCPServerConnection::start() @ 0xe3867bb in /usr/lib/debug/usr/bin/clickhouse
9. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/atomic:856: Poco::Net::TCPServerDispatcher::run() @ 0xe386c3d in /usr/lib/debug/usr/bin/clickhouse
10. /build/obj-x86_64-linux-gnu/../contrib/poco/Foundation/include/Poco/Mutex_STD.h:132: Poco::PooledThread::run() @ 0x1059d237 in /usr/lib/debug/usr/bin/clickhouse
11. /build/obj-x86_64-linux-gnu/../contrib/poco/Foundation/include/Poco/AutoPtr.h:205: Poco::ThreadImpl::runnableEntry(void*) @ 0x1059903c in /usr/lib/debug/usr/bin/clickhouse
12. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2615: void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void* (*)(void*), Poco::ThreadImpl*> >(void*) @ 0x1059a9dd in /usr/lib/debug/usr/bin/clickhouse
13. start_thread @ 0x8064 in /lib/x86_64-linux-gnu/libpthread-2.19.so
14. clone @ 0xe862d in /lib/x86_64-linux-gnu/libc-2.19.so

Received exception from server (version 20.3.5):
Code: 1001. DB::Exception: Received from HOSTNAME:25604. DB::Exception: St8bad_cast: std::bad_cast.

**Comment by alesapin** [comment]
Does error reproduces if try to execute query again on the same host?

**Comment by cw9** [comment]
Yes it does, there is a column I want to drop from that table and I can neither drop it or add other columns to the table,

**Comment by cw9** [comment]
If there is information else you need me to collect, let me know while I can still reproduce it on that node.
Also would love to know if there are any workarounds for this bug.

**Comment by alesapin** [comment]
Very strange, this error has an incorrect message and type, but it should mean, that we cannot connect to zookeeper. Do tables on this node work properly (you can insert data)?

**Comment by cw9** [comment]
Yes, I can still write to and read from this table

**Comment by alesapin** [comment]
Ok. Strange. Can you provide logs (`/var/log/clickhouse-server/clickhouse-server.log`) from this node? Also is it possible to execute the same query on other replicas of this node?

**Comment by cw9** [comment]
The log is also showting the same stack, nothing much else.
I can confirm the data written to this replica is replicated to the other replica. The `alter table add column` also fails on the other replica.

**Comment by alesapin** [comment]
Probably you have a very silent logging level (`trace` level is recommended). Do you have access to zookeeper? If so, I'd like to see your table schema and data from zookeeper nodes `/path_to_table/metadata` and `/path_to_table/replicas/replica_name/metadata`.

**Comment by alesapin** [comment]
Also `SELECT * FROM system.mutations` is useful.

**Comment by cw9** [comment]
Yes ZK info:
```
get /clickhouse/databases/default/tables/foo/shards/147/replicas/1/metadata
metadata format version: 1
date column:
sampling expression:
index granularity: 8192
mode: 0
sign column:
primary key: _namespace, -_timestampMillis
data format version: 1
partition key: intDiv(_timestampMillis, 3600000)
granularity bytes: 10485760

cZxid = 0x2000020ae
ctime = Wed Apr 01 21:37:46 UTC 2020
mZxid = 0xd037ff256
mtime = Wed Apr 08 03:31:31 UTC 2020
pZxid = 0x2000020ae
cversion = 0
dataVersion = 3
aclVersion = 0
ephemeralOwner = 0x0
dataLength = 252
numChildren = 0

get /clickhouse/databases/default/tables/foo/shards/147/replicas/2/metadata
metadata format version: 1
date column:
sampling expression:
index granularity: 8192
mode: 0
sign column:
primary key: _namespace, -_timestampMillis
data format version: 1
partition key: intDiv(_timestampMillis, 3600000)
granularity bytes: 10485760

cZxid = 0x2000022c6
ctime = Wed Apr 01 21:37:46 UTC 2020
mZxid = 0xd037ff878
mtime = Wed Apr 08 03:31:31 UTC 2020
pZxid = 0x2000022c6
cversion = 0
dataVersion = 3
aclVersion = 0
ephemeralOwner = 0x0
dataLength = 252
numChildren = 0

get /clickhouse/databases/default/tables/foo/shards/147/metadata
metadata format version: 1
date column:
sampling expression:
index granularity: 8192
mode: 0
sign column:
primary key: _namespace, -_timestampMillis
data format version: 1
partition key: intDiv(_timestampMillis, 3600000)
granularity bytes: 10485760

cZxid = 0x200002058
ctime = Wed Apr 01 21:37:46 UTC 2020
mZxid = 0xd0380c12c
mtime = Wed Apr 08 03:31:56 UTC 2020
pZxid = 0x200002058
cversion = 0
dataVersion = 4
aclVersion = 0
ephemeralOwner = 0x0
dataLength = 252
numChildren = 0
```

**Comment by alesapin** [comment]
Do you have `path_to_table/replica/replica_name/metadata_version`?

**Comment by cw9** [comment]
5 for one replica and 3 for the other replica

**Comment by alesapin** [comment]
Have you already performed successful alters after upgrade to 20.3.5?

**Comment by cw9** [comment]
Hmm, so I saw there are 2 `drop column` commands on that table stuck for a long time unfinished in `system.mutation` table, I killed those two commands and now I can drop columns now

**Comment by alesapin** [comment]
Ok, it would be awesome if you will provide verbose server logs. Otherwise, I don't know how to investigate this issue :(

**Comment by alesapin** [comment]
> Hmm, so I saw there are 2 `drop column` commands on that table stuck for a long time unfinished in `system.mutation` table, I killed those two commands and now I can drop columns now

How did they look like? How many records they had in `parts_to_do` column?

**Comment by cw9** [comment]
The value is 0 in `parts_to_do` and 0 in `is_done`, I'll set logging level to `trace` and see if I can find more information

**Comment by cw9** [comment]
btw I have quite a few shards returning that error, and on another shard I tried killing the stuck mutations and that fixed the problem again.

**Comment by alesapin** [comment]
Ok, if you will see this error again just reopen this issue and provide server logs.
