### ISSUE TITLE
Distribute query execute  on local table concurrency is controlled by the parameter max_threads in version 20.3 

### ISSUE THREAD

**Issue by weiyongyuan** [ClickHouse/ClickHouse#10141]
1.settings distributed_product_mode=local;max_threads=auto.
If i have a cluter consisted by 50 local nodes,the cpu is 25 cores,and every core has 2 threads.when i execute a distribute query ,the the query doesn't send the 50 nodes the same time,it will send 1-25 first time,when the local query on 1-25 node  is finished,then the local query will execute  on 26-50 nodes,the query takes 2 seconds.if i set max_threads=50,then the local query will execute on 1-50 nodes the same time,and the distribute qeury takes 1seconds.the bug can reproduce by a small cluster.you can set max_threads=1,then you'll observer the query is executed on local nodes one by one.

**Comment by alexey-milovidov** [comment]
What version of clickhouse-server do you use?
Do I understand correctly that you have 50 clickhouse-servers running on localhost?

**Comment by weiyongyuan** [comment]
> What version of clickhouse-server do you use?
> Do I understand correctly that you have 50 clickhouse-servers running on localhost?
The versions are  20.3.2.1 and 20.3.4.10.I have 3 distribute nodes,50 clickhouse-servers running on localhost.I've test 20.1.6.30 ,20.1.6.30 is ok。but,20.3.2.1 and 20.3.4.10 all has the above problem。you can test it by a small cluster,set max_threads=1,then you query on distribute node ,then you can see query execute on clickhouse local node one by one.

**Comment by genzgd** [comment]
Does this issue exist on older ClickHouse versions?  I'm seeing what looks like similar behavior on 20.3.5 -- my distributed query is not sending all the shard queries at once.  Our cluster is 10 shards on 10 different physical servers.  Running a trace log, I see the distributed query sent to only 3 other shards initially; only 20 seconds later is the query sent to the other 6 remote shards.

On our older cluster on 19.3.3 the same query is immediately sent to all 9 remote shards.

**Comment by filimonov** [comment]
May be related to https://github.com/ClickHouse/ClickHouse/issues/9965

fixed here https://github.com/ClickHouse/ClickHouse/pull/9971 (but not in release yet)

**Comment by genzgd** [comment]
That appears to be the case for our issue -- turning off `experimental_use_processors` fixed the problem.  Interestingly, the query ran fine on the "last" shard of the cluster, since it started all the remote queries before processing the local one.  Hopefully the #9971 PR fixes that behavior.
