### ISSUE TITLE
Conditional function with Decimal and non Decimal.

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#10142]
```
SELECT ifNull(CAST(null as Nullable(Decimal(38,10))), 0) ;

DB::Exception: Conditional function with Decimal and non Decimal.
```

The intention is quite clear - not to take the responsibility of potentially inaccurate casting from floats to decimals.

But casts from int to decimal are safe, and it's not good to force users to use explicit casts everywhere.

**Comment by dmitry3325** [comment]
Same issue, but it works before last version

**Comment by filimonov** [comment]
> Same issue, but it works before last version

Which version worked?

**Comment by dmitry3325** [comment]
Hi, maybe this is different types of problems. In my case query

**Comment by filimonov** [comment]
In newer versions the exception message get is worse:
```
SELECT ifNull(CAST(NULL, 'Nullable(Decimal(38, 10))'), 0)


Received exception from server (version 20.4.6):
Code: 43. DB::Exception: Received from localhost:9000. DB::Exception: Invalid types of arguments 2 and 3 of if. 

0 rows in set. Elapsed: 0.004 sec. 

```

**Comment by alexey-milovidov** [comment]
I've fixed this issue with code removal.
https://github.com/ClickHouse/ClickHouse/pull/25283
