### ISSUE TITLE
crashed after running mutation

### ISSUE THREAD

**Issue by ShadowDAssange** [ClickHouse/ClickHouse#10145]
I have Specified the condition which only deletes one record.
But after running this mutation, Memory continues to grow until clickhouse restarted.
meanwhile, Only one CPU is 100%, others are almost 0%

**Comment by ShadowDAssange** [comment]
20.1.6.30 (official build)

**Comment by ShadowDAssange** [comment]
I think i find the solution.
[#9860](https://github.com/ClickHouse/ClickHouse/pull/9860)

**Comment by alesapin** [comment]
Yes, just update to the latest 20.1 or 20.3.
