### ISSUE TITLE
force_drop_table file still exists when executed drop command on the table partition whose size > 50G

### ISSUE THREAD

**Issue by AlexanderJLiu** [ClickHouse/ClickHouse#10143]
Clickhouse version: `20.3.5.21`

In general, if you want to drop a partition with size >50 G, you should create a `force_drop_table` file in `<clickhouse-path>/flags/force_drop_table`. And after executing, the `force_drop_table` will be removed  to avoid misuse.

But now it still exists. And have to remove it manually.

**Comment by alexey-milovidov** [comment]
It has happened because you have created the file with wrong ownership or access rights and clickhouse-server cannot remove it.

It will write a message
`Can't remove force file to enable table or partition drop`
and continue.
