### ISSUE TITLE
the performance diff between distinct(UInt16) and distinct(UInt32)

### ISSUE THREAD

**Issue by ZonghaoWang** [ClickHouse/ClickHouse#10155]
hi
  I want to know how the performance diff so much when I calculate distinct(UInt16) and distinct(UInt32)
does distinct(UInt16) use array, distinct(UInt32) use map?

![image](https://user-images.githubusercontent.com/11403656/78920657-4fd9ab80-7ac6-11ea-8fe1-a8cb8e8bdd82.png)

**Comment by alexey-milovidov** [comment]
Both of them are using the same data structure (hash table).

The difference in performance is because you have much higher number of distinct values in the second case: 108 514 884 instead of 65 536.

Another possible reason is that UInt32 value is more difficult to read from disk and it is compressed worse due to large amount of distinct values.

You can find the relevant info about columns compression in the `system.columns` table.

**Comment by ZonghaoWang** [comment]
thanks.
     it work with 900millin rows on nvme with 30Gbps
     when I process distinct(UInt32), data read in 7s, the progressbar goes to 98%. the last 2% cost 23s. `system.column` show as follow.
 
![image](https://user-images.githubusercontent.com/11403656/78953238-c26c7a80-7b0a-11ea-8cab-8b33bd7404ca.png)

     with hashtable, it also cost much memory with big-data, if it work with [2**32]int8, can it accelerate？how the masterMemory latency affect?

**Comment by alexey-milovidov** [comment]
Yes, it can be accelerated.

```
SET group_by_two_level_threshold = 1, group_by_two_level_threshold_bytes = 1;
SELECT sum(c) FROM (SELECT uniqCombined(profile_id_hash) AS c FROM clustered_face4 GROUP BY profile_id_hash % 256)
```

Todo: provide explanation.

**Comment by alexey-milovidov** [comment]
Or: simply replace `countDistinct` to `uniq`.

**Comment by ZonghaoWang** [comment]
thank you.

**Comment by amosbird** [comment]
> Both of them are using the same data structure (hash table).

@alexey-milovidov UInt16 uses lookup table which is faster. Though in this case it doesn't matter much :)

**Comment by alexey-milovidov** [comment]
@amosbird We still don't have such optimization for AggregateFunctionUniqExactData.

**Comment by amosbird** [comment]
yeah, I think it's worth doing. Lemme add it along with a perftest

**Comment by alexey-milovidov** [comment]
Yes, it will be great!

**Comment by amosbird** [comment]
wait a sec. There is a problem. FixedHashSet takes quite some space. I just noticed this comment

`    /// When creating, the hash table must be small.
`

**Comment by alexey-milovidov** [comment]
Yes, you're right. I will be worse.

**Comment by alexey-milovidov** [comment]
> Todo: provide explanation.

If we have just a single aggregate function value, the merge operation is not parallelized.
(It's only parallelized across multiple different aggregation states.)

It is possible area for improvement.
