### ISSUE TITLE
max_memory_usage_for_background_operations

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#10154]
From avito meetup:

The exception is better than OOM, so something like 
`max_memory_usage_for_background_operations` 
would be cool.

**Comment by filimonov** [comment]
Test case:
```
set send_logs_level='trace',max_block_size=256, min_insert_block_size_rows=1, min_insert_block_size_bytes=1;
create table test_merge_oom engine=AggregatingMergeTree ORDER BY id as select number%1024 as id, arrayReduce( 'groupArrayState', arrayMap( x-> randomPrintableASCII(1024), range(8192) )) fat_state from numbers(4000000);
```

![Screenshot from 2020-04-10 23-47-36](https://user-images.githubusercontent.com/1549571/79025493-3d26ab80-7b86-11ea-8f09-b06349e81b84.png)

**Comment by alexey-milovidov** [comment]
It is difficult to reliably calculate memory usage for background operations as the memory allocations and deallocations can happen from the scope inside and outside of the operation.
