### ISSUE TITLE
FORMAT JSONAsString

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#10163]
The format is intended only for data import (input format).
It can only parse a table with single field of type String.

It will parse a sequence of JSON objects separated by newlines, spaces and/or comma.
Each JSON object is parsed as a whole to string, without parsing internals.
JSON object may reside multiple lines.

This feature was suggested by Mikhail Filimonov, Altinity.

**Comment by Avogar** [comment]
https://github.com/ClickHouse/ClickHouse/pull/10607

**Comment by Felixoid** [comment]
Looks solved to me. Is it?

**Comment by Felixoid** [comment]
#11514
