### ISSUE TITLE
system.query_log doesn't store server ip

### ISSUE THREAD

**Issue by weiyongyuan** [ClickHouse/ClickHouse#10170]
as show below picture,server15 is a distribute node,server13 is a data node,execute a dsitribute query on server 15,query_log on server 13 doesn't show server13'ip as server ip,there only show the client ip where query is from.and system.query_log table doesn't store server ip.Here is the docment:(https://clickhouse.tech/docs/v20.1/en/operations/system_tables/#system_tables-query_log)
![image](https://user-images.githubusercontent.com/20318636/78986253-71d23d00-7b5d-11ea-99fa-f342661b9062.png)
Why do i need that the query_log store the server ip ?if i have a cluster,a distribute node,10 datanode,the distribute query execute on the data node ,some execute quicklier,some slower.Then I create a distribute query_log table on the cluster,then i can query from the distribute query_log table to find which datanode is the slow.

**Comment by den-crane** [comment]
you can `select hostName(), .... from distribute_query_log ` 
or `select FQDN(), .... from distribute_query_log`

**Comment by weiyongyuan** [comment]
> you can `select hostName(), .... from distribute_query_log `
> or `select FQDN(), .... from distribute_query_log`

thank you a lot!
