### ISSUE TITLE
FR: dynamic dispatch of SIMD algorithms to support AVX2/AVX512

### ISSUE THREAD

**Issue by innerr** [ClickHouse/ClickHouse#1017]
I dived into the code and addressed some SSE optimizations. Well done guys, I appreciate that you delivered and shared such a greate AP system.

And I found nothing about AVX optimizations, it is on the plan ?

**Comment by alexey-milovidov** [comment]
Thank you for appreciation!

We have AVX optimizations in long list of features to implement. Probably we will introduce them in few single places where it could provide maximum benefit (your suggestions?). This will require dynamic dispatching as long as we still have many hardware without AVX support.

**Comment by innerr** [comment]
Look forward to it!

**Comment by alexey-milovidov** [comment]
This task is assigned to @DimasKovas.
He will try to port some optimizations to newer instruction sets with dynamic dispatching and perform some experiment for optimizations targeted to ARM NEON.

**Comment by alexey-milovidov** [comment]
#10058
