### ISSUE TITLE
Support secure connections (SSL) to Zookeeper

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#10174]
**Use case**
Support secure connections from ClickHouse to ZooKeeper.
**Additional context**
[SSL User guide](https://cwiki.apache.org/confluence/display/ZOOKEEPER/ZooKeeper+SSL+User+Guide)
[Reference: Initial support for SSL in zookeeper-client](https://github.com/apache/zookeeper/commit/dded710d07892c6b42380267cd1bb896b852a7ee#diff-86aa95f6bcc4463c09a342a0597d8aed)

**Comment by alexey-milovidov** [comment]
The task is being developed by Kostya (Telegram login: @tkostyan)
