### ISSUE TITLE
Console output of clickhouse-client breaks some terminals

### ISSUE THREAD

**Issue by korjavin** [ClickHouse/ClickHouse#10189]
I use "kitty" terminal emulator, and such type of output
```
↗ Progress: 105.65 thousand rows, 93.17 MB (9.87 thousand rows/s., 8.70 MB/s.) ████████▊                                                                    11%

```

breaks it.

I submitted an issue to kitty, but they answered this:

```
This will be because because clickhouse-client is using an incorrect wcwidth() for the spinning arrow character. As per the unicode standard it must be two cells, clickhouse is almost certainly assuming it is one cell. Report it to them

Oh and if they want it to occupy a single cell, they need to output a U+FE0E character after it



```
(https://github.com/kovidgoyal/kitty/issues/2530)

Hope it can help to improve.

**Comment by qoega** [comment]
Thank you. Actually you can try to fix it by yourself. It looks it should be easy even if you are not a C++ programmer.

**Comment by alexey-milovidov** [comment]
Actually the reason is different.

**Comment by alexey-milovidov** [comment]
It reproduces even if I replace the arrows with ASCII characters.

**Comment by alexey-milovidov** [comment]
The reason is in terminal interpretation of
```
#define SAVE_CURSOR_POSITION "\033""7"
#define RESTORE_CURSOR_POSITION "\033""8"
```
escape sequences.

Please file a report back to Kitty.

**Comment by alexey-milovidov** [comment]
But at least this simple tests passed:

`echo -e '\x1B7 hello \x1B8 world'`

**Comment by alexey-milovidov** [comment]
We can get the same effect by turning the terminal to raw mode and sending "carriage return".

**Comment by alexey-milovidov** [comment]
But it may flicker on slow ssh sessions.

**Comment by alexey-milovidov** [comment]
This task can be fixed together: https://github.com/ClickHouse/ClickHouse/issues/5908

**Comment by alexey-milovidov** [comment]
Slow connections can be tested with https://github.com/sjmulder/trickle

**Comment by trygveaa** [comment]
It seems like kitty doesn't use the same cursor position if you send the restore cursor sequence twice after each other, e.g. like this:

```
echo -e '\x1B7 hello \x1B8 world \x1B8 world'
```

My guess it that's what causes the issue. In e.g. xterm the two restore cursor position sequences will move the cursor to the same position, but in kitty the second one will move the cursor to 0,0.

**Comment by trygveaa** [comment]
According to the author of kitty, it is an error to send multiple restore cursor commands following each other without sending save cursor each time: https://github.com/kovidgoyal/kitty/issues/1264#issuecomment-449788068

It works in xterm though, so I'm not sure which terminal emulator has the correct behavior.

**Comment by alexey-milovidov** [comment]
I'm happy that the root cause is found!
Yes, it also works fine in Konsole.

But I have removed these sequences at all in my PR: #10194
