### ISSUE TITLE
Missing documentation of the "SELECT IN" syntax

### ISSUE THREAD

**Issue by ishirav** [ClickHouse/ClickHouse#10190]
There used to be documentation about the IN operator, but it's missing now.
Some places in the docs still link to https://clickhouse.tech/docs/en/sql_reference/statements/select/#select-in-operators but this anchor is not present on the page. 
It still exists in older versions of the docs, e.g. https://clickhouse.tech/docs/v20.3/en/query_language/select/#select-in-operators but not in the latest docs.

**Comment by BayoNet** [comment]
In progress.
