### ISSUE TITLE
JOIN keys should be converted to the least common type

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#10197]
`SELECT t1.*, t2.* FROM (SELECT 1 AS k) t1 JOIN (SELECT -1 AS k) t2 ON t1.k = t2.k`

`Type mismatch of columns to JOIN by: k UInt8 at left, t2.k Int8 at right.`

Isn't that easy to fix?

**Comment by 4ertus2** [comment]
No chance to fix it inside *Join.cpp. So we have to fix it outside. There we could auto-wrap keys into `toSupertype(t1.k) = toSupertype(t2.k)` in SyntaxAnalyzer. Then it should work. It's not very difficult I think. The main trouble is to get function name from known supertype. We could parse `CAST(x AS Supertype)` and change JOIN keys with these functions.

**Comment by alexey-milovidov** [comment]
Fixed.
