### ISSUE TITLE
How to import a CSV file with a column with YYYYMMDD to a DATE column in ClickHouse

### ISSUE THREAD

**Issue by Arthurjal** [ClickHouse/ClickHouse#10210]
I´d like to import a CSV file with a column with YYYYMMDD to a DATE column in ClickHouse. Sample of CSV content: 20191231. I realized that ClickHouse only import a DATE column in CSV if it in the format as is YYYY-MM-DD (only with "-" between the year, month and day). I can not change the format in the CSV file that is stored in a http server.
Please let me know an easy way or command to import hundred CSV files with YYYYMMDD from a http server or where can I change the configuration in my clickhouse server to accept YYYYMMDD format instead of YYYY-MM-DD?

I already added a new column, imported all files and updated the table. See the query below. The field 'olddatefield' is a STRING and 'newdatefield' is a DATE field.

ALTER TABLE test ADD COLUMN newdatefield  Date AFTER olddatefield;

ALTER TABLE test 
UPDATE newdatefield = toDate(concat(substring(olddatefield, 1, 4), '-' , substring(olddatefield, 5, 2), '-' , substring(olddatefield, 7, 2)))
WHERE olddatefield = '20191231';

It worked very well, but there are thousands files with different DATES to import and I dont want edit  thousands  of 'alter table' queries.

**Comment by alexey-milovidov** [comment]
You don't have to do ALTER UPDATE.
Instead, you can simply create a column with DEFAULT expression.

**Comment by Arthurjal** [comment]
**Alexey,** this create table below is the only way that I could created the table, but with errors during the importation. ( ERROR: Date must be in YYYY-MM-DD format ). In the other ways below I can not created the table. Remember I can not change the file csv and there are a lot of files.

CREATE TABLE my_table (
    my_date DEFAULT toDate(my_date),
    my_name String
) ENGINE=MergeTree(my_date, (my_name), 8192);

Sample file: **file1.csv:**
my_date,my_name
20191231,Arthur
20191029,Igor
20190923,Antony

cat file1.csv | clickhouse-client --query="INSERT INTO my_database.my_table FORMAT CSVWithNames";

Code: 27. DB::Exception: Cannot parse input: expected , before: 
\'Arthur\'\r\n20191029,\'Igor\'\r\n20190923,\'Antony\': (at row 1)
Row 1: 
Column 0,   name: my_date, type: Date,   parsed text: "20191231,"
ERROR: garbage after Date: single quote "Arthur" single quote carriage return line feed "ERROR: Date must be in YYYY-MM-DD format."

======================================
**Other ways:**

CREATE TABLE my_table (
    my_date Date DEFAULT toDate(my_date),
    my_name String
) ENGINE=MergeTree(my_date, (my_name), 8192);

Error: ClickHouse exception, code: 174, host: 192.168.15.4, port: 8123; Code: 174, e.displayText() = DB::Exception: Cyclic aliases: default expression and column type are incompatible. (version 20.3.4.10 (official build))

SQLState:  null
ErrorCode: 174

==================================================

CREATE TABLE my_table (
    my_date Date DEFAULT toDate(concat(substring(my_date, 1, 4), '-' , substring(my_date, 5, 2), '-' , substring(my_date, 7, 2))),
    my_name String
) ENGINE=MergeTree(my_date, (my_name), 8192);

Error: ClickHouse exception, code: 174, host: 192.168.15.4, port: 8123; Code: 174, e.displayText() = DB::Exception: Cyclic aliases: default expression and column type are incompatible. (version 20.3.4.10 (official build))

SQLState:  null
ErrorCode: 174

See the file1.csv attached:
[file1.zip](https://github.com/ClickHouse/ClickHouse/files/4467924/file1.zip)

**Comment by robot-clickhouse** [comment]
@Arthurjal, do you have any further questions?

**Comment by alexey-milovidov** [comment]
Use the `input` table function: INSERT ... SELECT ... FROM input(...).
