### ISSUE TITLE
Drop partition with partition expression is broken

### ISSUE THREAD

**Issue by ChesnakovAlexander** [ClickHouse/ClickHouse#10212]
**Describe the bug**
When I use partition expression instead of string I get a syntax error.
Since upgrade from version 19.13 to 20.3.5.21.

**How to reproduce**
```
DROP TABLE IF EXISTS test1;

CREATE TABLE IF NOT EXISTS test1 (d Date) ENGINE = MergeTree () PARTITION BY d ORDER BY d;

INSERT INTO test1 VALUES (toDate('2020-04-12'));

ALTER TABLE test1 DROP PARTITION toDate('2020-04-12');

ALTER TABLE test1 DROP PARTITION '2020-04-12';
```

**Error message and/or stacktrace**
```
drop partition toDate(yesterday());

Expected one of: LIKE, GLOBAL NOT IN, IS, OR, QuestionMark, BETWEEN, NOT LIKE, AND, IN, NOT, token, NOT IN, GLOBAL IN


drop partition toDate('2020-04-12');

Expected one of: LIKE, GLOBAL NOT IN, IS, OR, QuestionMark, BETWEEN, NOT LIKE, AND, IN, NOT, token, NOT IN, GLOBAL IN
```
drop partition '2020-04-12'; works

**Comment by alexey-milovidov** [comment]
Was intentially removed in https://github.com/ClickHouse/ClickHouse/pull/8835

**Comment by asb-72** [comment]
Also on system.query_log:
```
ALTER TABLE system.query_log
    DROP PARTITION '2020-04-06'


Received exception from server (version 20.3.5):
Code: 72. DB::Exception: Received from 192.168.34.165:9000. DB::Exception: Unsigned type must not contain '-' symbol: Cannot parse UInt32 from String. 
```

**Comment by alexey-milovidov** [comment]
@asb-72 system.query_log has monthly partitions by default, not daily.

**Comment by winofi** [comment]
For me `ALTER TABLE $CLICKHOUSE_DB.rx DROP PARTITION toYYYYMM(subtractMonths(now(), 1));` stopped working after updating to version 20.4.4.18 (official build) recently and fails with the error described above and in #10911. 
While `select toYYYYMM(subtractMonths(now(), 1))` returns 202005 `ALTER TABLE $CLICKHOUSE_DB.rx DROP PARTITION 202005;` does work.

**Comment by kterrita** [comment]
20.4.2.9
Error is still reproduced

**Comment by den-crane** [comment]
@kterrita it's a new behavior for good.

**Comment by den-crane** [comment]
hm, 

tuple is WA ?  

create table xt(A Date) engine=MergeTree partition by toYYYYMM(A) order by A;
insert into xt values(today());

alter table xt drop partition **tuple**(toYYYYMM(today()));
0 rows in set. Elapsed: 0.001 sec.

select  * from xt
0 rows in set. Elapsed: 0.001 sec.
