### ISSUE TITLE
Africa/Casablanca timezone missing

### ISSUE THREAD

**Issue by youssefqarri** [ClickHouse/ClickHouse#10211]
Hello,

Putting **Africa/Casablanca** as a timezone in both config.xml or in queries is not working.

Build : ClickHouse server version 20.3.5.21 (official build).

Regards

**Comment by alexey-milovidov** [comment]
It depends on time zone info in your OS:

```
$ clickhouse-local --query "SELECT toTimeZone(now(), 'Africa/Casablanca')"
2020-04-12 20:42:32
```

**Comment by alexey-milovidov** [comment]
In Linux, time zone info is located in `/usr/share/zoneinfo/`

**Comment by youssefqarri** [comment]
The timezone is available in the OS

[root@xxxx ~]# **ls /usr/share/zoneinfo/Africa/**
Abidjan      Asmara  Banjul       Bujumbura   Conakry        Douala    Harare        Khartoum  Libreville  Lusaka  Mbabane    Ndjamena     Porto-Novo  Tunis
Accra        Asmera  Bissau       Cairo       Dakar          El_Aaiun  Johannesburg  Kigali    Lome        Malabo  Mogadishu  Niamey       Sao_Tome    Windhoek
Addis_Ababa  Bamako  Blantyre     **Casablanca**  Dar_es_Salaam  Freetown  Juba          Kinshasa  Luanda      Maputo  Monrovia   Nouakchott   Timbuktu
Algiers      Bangui  Brazzaville  Ceuta       Djibouti       Gaborone  Kampala       Lagos     Lubumbashi  Maseru  Nairobi    Ouagadougou  Tripoli

FYI, I am using CentOS Linux release 8.1.1911 (Core)

**Comment by alexey-milovidov** [comment]
Is it available both on client and server side?
(client may need it for data formatting)

**Comment by youssefqarri** [comment]
Yes. It is available in both as the client is hosted in the server as the server

**Comment by alexey-milovidov** [comment]
Confirmed. I can reproduce it with the following commands:

```
$ docker run --rm -it --volume /home/milovidov/work/ClickHouse/build:/build centos:8 /build/programs/clickhouse local --query "SELECT toTimeZone(now(), 'Africa/Casablanca')"
Exception: Cannot load time zone Africa/Casablanca
$ docker run --rm -it --volume /home/milovidov/work/ClickHouse/build:/build centos:8 ls -l /usr/share/zoneinfo/Africa/Casablanca
-rw-r--r-- 1 root root 2465 Oct  1  2019 /usr/share/zoneinfo/Africa/Casablanca
```
