### ISSUE TITLE
Does not support Max/Min DateTime value

### ISSUE THREAD

**Issue by soloduev** [ClickHouse/ClickHouse#10229]
I pass (with `C#`: `DateTime.MaxValue`/`DateTime.MinValue`)  the minimum and maximum value for the date field in the request:
```sql
SELECT *
WHERE 
 (
     (recvdt < '9999-12-31T20:59:59' AND date < '9999-12-31') AND (recvdt >='0001-01-01T00:00:00' OR date >= '0001-01-01')
 )
```
And this query returns an **empty result.**
But this query, the data will return:
```sql
SELECT *
WHERE 
 (
     (recvdt < '2021-01-01T00:00:00' AND date < '2021-01-01') AND (recvdt >='2018-01-01T00:00:00' OR date >= '2018-01-01')
 )
```

**Comment by qoega** [comment]
It is well documented https://clickhouse.tech/docs/en/sql_reference/data_types/datetime/
DateTime data type
```
Supported range of values: [1970-01-01 00:00:00, 2105-12-31 23:59:59].
```
C# MaxValue/MinValue has nothing in common with ClickHouse.

```sql
SELECT toDateTime('9999-12-31T20:59:59', 'UTC')

┌─toDateTime('9999-12-31T20:59:59', 'UTC')─┐
│                      1970-01-01 20:59:59 │
└──────────────────────────────────────────┘
```

Actually even DateTime64 data type supports maximum date time in 2106 year, not 9999
``` sql
SELECT toDateTime64(0, 0) - 1

┌─minus(toDateTime64(0, 0), 1)─┐
│          2106-02-07 09:28:15 │
└──────────────────────────────┘
```

**Comment by soloduev** [comment]
Ok, thanks! But, why CH can't do auto down-cast to supported DateTime?

**Comment by soloduev** [comment]
Now, if I understand correctly, day zero is set, if we do not fall into the range?

[Code line common/DateLUTImpl.h 667](https://github.com/ClickHouse/ClickHouse/blob/master/base/common/DateLUTImpl.h#L667)

**Comment by filimonov** [comment]
See https://github.com/ClickHouse/ClickHouse/pull/9404

You can check that / take a build from CI / help with QA.
