### ISSUE TITLE
Not executing log entry MUTATE_PART for part 202004_35760_35760_0_50646 because source parts size (2.56 MiB) is greater than the current maximum (0.00 B).

### ISSUE THREAD

**Issue by anheicang** [ClickHouse/ClickHouse#10225]
Version: 19.16.14.65
ErrorInfo: Not executing log entry MUTATE_PART for part 202004_35760_35760_0_50646 because source parts size (2.56 MiB) is greater than the current maximum (0.00 B).
Desc:
    The problem occurred on 2 out of 6 machines. The 2 machines are replicas each other.   The memory usage 50~60GB, then I dropped the table,  the memory recover.

I want to know : When will this problem occur and how to solve this problem? 
thanks.

**Comment by filimonov** [comment]
duplicate #10224
