### ISSUE TITLE
please make table lines align in pdf again by restoring old fonts

### ISSUE THREAD

**Issue by l1t1** [ClickHouse/ClickHouse#10223]
the issue is an update of this (https://github.com/ClickHouse/ClickHouse/issues/9681)
as the problem of Chinese version exists yet.
https://clickhouse.tech/docs/zh/single/clickhouse_zh.pdf
and the English version also has same problem.
https://clickhouse.tech/docs/en/single/clickhouse_en.pdf

**Comment by alexey-milovidov** [comment]
@blinkov I have downloaded the latest version and confirm that tables don't align.

**Comment by blinkov** [comment]
1. There's actually a much more serious issue with rendering around page breaks, I've tried some easy approaches, but they didn't work.
2. As of “tables” that are pretty-printed query results, we'd better just get rid of them in favor of normal HTML tables.
3. Why font stops being monospace during print also deserves some research.

**Comment by l1t1** [comment]
yes, it is not only the table align question, but also the mono font for script and keywords question.

**Comment by l1t1** [comment]
the pdf at 2020-11-11 is still has the problem, page 23 shows
![2020-11-11_142945](https://user-images.githubusercontent.com/23301704/98776584-29983780-242a-11eb-800a-65691c1b2f8f.png)

**Comment by l1t1** [comment]
the following Chinese pdf font is good. 
https://raw.githubusercontent.com/JuliaCN/JuliaZH.jl/pdf/dev/Julia%E4%B8%AD%E6%96%87%E6%96%87%E6%A1%A3.pdf
