### ISSUE TITLE
clickhouse-client: refresh completion hash

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#10236]
Need the ability to refresh autocomplete dictionary - on demand (like in mysql), or automatically (after each DDL command). 

Just like \# in mysql

**Comment by filimonov** [comment]
Related #9339

**Comment by alexey-milovidov** [comment]
No one is going to manually request refreshing the autocompletion info. The proposed feature will be almost useless.
And the `#` command in MySQL is an example of worst pattern (a command represented by obscure character).

Workaround: quit from clickhouse-client and start it again.
