### ISSUE TITLE
Bitmask functions for FixedSting data type

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#10254]
**Use case**
FixedString data type is good to store binary data. For some cases FixedString data type can be used to fit large numbers, that are unsupported in ClickHouse.

**Describe the solution you'd like**
At least implement
- AND/OR/XOR
- test N bit
- set/reset
- flip

https://clickhouse.tech/docs/en/sql_reference/functions/bit_functions/#bit-functions
https://clickhouse.tech/docs/en/sql_reference/functions/bitmap_functions/

**Comment by alexey-milovidov** [comment]
Already done: #9091

**Comment by alexey-milovidov** [comment]
> AND/OR/XOR

bitAnd, bitOr, bitXor, bitNot.
