### ISSUE TITLE
Partitions have  active and is_frozen  both flags at the same time

### ISSUE THREAD

**Issue by vvchistiakov** [ClickHouse/ClickHouse#10252]
Hi mates.
I couldn't find any information about my trouble
So,
I have big table with engine ReplicatedMergeTree. I hold the data during 90 days there.
the structure is
```
CREATE TABLE IF NOT EXISTS default.message_by_chid (
...
)
ENGINE = ReplicatedMergeTree('/clickhouse/cluster_cross_r1/tables/{shard}/message_by_chid', '{replica}')
PARTITION BY toMonday(logs_SendDateTime)
ORDER BY (logs_SMSChannelId, logs_SendDateTime, prices_SMSChannelId) TTL logs_SendDateTime + toIntervalDay(90)
SETTINGS index_granularity = 8192;
```
So, I have a problem that old data was not deleted.
I've checked  system.parts table to get more information about it. I saw that a lot partitions have flags
active and is_frozen = 1. However, I had not setup these partitions like snapshots. I have other tables  with TTL and  the same engine, but I don't see the same behavior there. 

```
 | database | table | partition | name | rows | is_frozen | active | refcount | level | data_version | modification_time | remove_time | min_time | max_time |
 | default | message_by_chid | 2019-12-30 | 20191230_0_639598_7365_639615 | 0 | 1 | 1 | 1 | 7365 | 639615 | 2020-04-14 08:50:59 | 0000-00-00 00:00:00 | 0000-00-00 00:00:00 | 0000-00-00 00:00:00 |
 | default | message_by_chid | 2020-01-06 | 20200106_0_606705_8405_606719 | 0 | 1 | 1 | 1 | 8405 | 606719 | 2020-04-14 08:50:59 | 0000-00-00 00:00:00 | 0000-00-00 00:00:00 | 0000-00-00 00:00:00 |
 | default | message_by_chid | 2020-01-13 | 20200113_0_537334_6644_537348 | 559835705 | 1 | 1 | 1 | 6644 | 537348 | 2020-04-14 08:50:59 | 0000-00-00 00:00:00 | 2020-01-13 00:00:00 | 2020-01-19 23:59:59 |
 | default | message_by_chid | 2020-01-20 | 20200120_0_452519_8594_466711 | 684299622 | 1 | 1 | 1 | 8594 | 466711 | 2020-04-14 08:50:59 | 0000-00-00 00:00:00 | 2020-01-20 00:00:00 | 2020-01-26 23:59:59 |
 | default | message_by_chid | 2020-01-20 | 20200120_452520_466699_47_466711 | 28731947 | 1 | 1 | 1 | 47 | 466711 | 2020-04-14 08:50:59 | 0000-00-00 00:00:00 | 2020-01-21 09:00:00 | 2020-01-26 15:21:11 |
 | default | message_by_chid | 2020-01-27 | 20200127_0_337054_4649_337066 | 885381133 | 1 | 1 | 1 | 4649 | 337066 | 2020-04-14 08:50:59 | 0000-00-00 00:00:00 | 2020-01-27 00:00:00 | 2020-02-02 23:59:59 |
 | default | message_by_chid | 2020-02-03 | 20200203_0_412266_7930_412278 | 802769920 | 1 | 1 | 1 | 7930 | 412278 | 2020-04-14 08:50:59 | 0000-00-00 00:00:00 | 2020-02-03 00:00:00 | 2020-02-09 23:59:59 |
 | default | message_by_chid | 2020-02-10 | 20200210_0_210652_42_412585 | 974574244 | 0 | 1 | 1 | 42 | 412585 | 2020-04-14 09:16:57 | 0000-00-00 00:00:00 | 2020-02-10 00:00:00 | 2020-02-16 18:39:43 |
 | default | message_by_chid | 2020-02-10 | 20200210_210653_348867_4786_412585 | 70452324 | 0 | 1 | 1 | 4786 | 412585 | 2020-04-14 08:52:50 | 0000-00-00 00:00:00 | 2020-02-11 13:15:54 | 2020-02-16 23:59:59 |
 | default | message_by_chid | 2020-02-10 | 20200210_348868_360495_36_412585 | 12137004 | 1 | 1 | 1 | 36 | 412585 | 2020-04-14 08:51:00 | 0000-00-00 00:00:00 | 2020-02-15 13:00:00 | 2020-02-16 07:10:47 |
 | default | message_by_chid | 2020-02-10 | 20200210_367751_371362_35_412585 | 4304951 | 1 | 1 | 1 | 35 | 412585 | 2020-04-14 08:51:00 | 0000-00-00 00:00:00 | 2020-02-16 03:00:00 | 2020-02-16 10:28:42 |
 | default | message_by_chid | 2020-02-10 | 20200210_360496_367750_34_412585 | 2074170 | 1 | 1 | 1 | 34 | 412585 | 2020-04-14 08:51:00 | 0000-00-00 00:00:00 | 2020-02-16 03:00:00 | 2020-02-16 08:59:59 |
 | default | message_by_chid | 2020-02-10 | 20200210_371363_387310_37_412585 | 7889891 | 1 | 1 | 1 | 37 | 412585 | 2020-04-14 08:51:00 | 0000-00-00 00:00:00 | 2020-02-16 09:00:00 | 2020-02-16 14:59:59 |
 | default | message_by_chid | 2020-02-10 | 20200210_387311_398516_53_412585 | 4373265 | 1 | 1 | 1 | 53 | 412585 | 2020-04-14 08:51:00 | 0000-00-00 00:00:00 | 2020-02-16 09:00:00 | 2020-02-16 22:59:59 |

```

Could  you explain a logic for that?

**Comment by den-crane** [comment]
is_frozen -- is not related to TTL or to active.

is_frozen -- means that part folder has `-r--r--r--` filesystem flags instead of  `-rw-rw-r--` it means that this part was fetched from other replica or freeze command (backup) was executed against this part.

**Comment by vvchistiakov** [comment]
Hi @den-crane
Yep, partitions with is_frozen flag have only read permission on filesystem on my server. However. I've checked the replica for this nodes. And I've got the same flags for same partitions. Nobody had made a backup for that.

**Comment by den-crane** [comment]
>it means that this part was fetched from other replica

**Comment by vvchistiakov** [comment]
Sorry @den-crane. It still is not clear for me. Is it ok when partitions have these same statuses on all replicas?
Could you suggest a direction where I should search problem with TTL? I've checked  error log for few days and  haven't found any interest errors.

**Comment by vvchistiakov** [comment]
#6462

**Comment by vvchistiakov** [comment]
Maybe, I'm wrong.
I was continue investigate this trouble.
I found interest thing. I have the partition _20191230_961638_1264729_10079_1279734_. And, there is ttl.txt file with content
`{"table":{"min":1585753056,"max":1586044799}}`
1585753056 = 2020-04-01T14:57:36
1586044799 = 2020-04-04T23:59:59
Does it mean CH will try delete the data after 2020-06-30?

**Comment by den-crane** [comment]
it means that TTL should start to remove rows after 2020-04-01T14:57:36

**Comment by vvchistiakov** [comment]
Oh...I see
Look's like trouble with TTL for me is #7701
So, as I could understand using `is_frozen` flag on all replicas at the same time for partitions without creating snapshots is normal behaviour for CH.
I guess I've finished my investigation here.
Thanks @den-crane

**Comment by robot-clickhouse** [comment]
@vvchistiakov, do you have any further questions?

**Comment by vvchistiakov** [comment]
> @vvchistiakov, do you have any further questions?

Nope:)
