### ISSUE TITLE
Add setting "aggregate_functions_null_for_empty"

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#10273]
This option will rewrite all aggregate functions in a query, adding `-OrNull` suffix to them.
This must be implemented via query rewrite (similar to `count_distinct_implementation` setting) to get consistent results for distributed queries.

Follow-up for #2509.

**Comment by filimonov** [comment]
BTW it is not clear how to use OrNull with stored aggregation function states.

**Comment by Alex-Cheng** [comment]
how to handle groupArray which does not support -OrNull?

**Comment by alexey-milovidov** [comment]
@Alex-Cheng these functions should return the default value instead of NULL.

Now it's not the case:
```
SELECT groupArray(x) FROM (SELECT toNullable(1) AS x) SETTINGS aggregate_functions_null_for_empty = 1

Code: 43. DB::Exception: Nested type Array(UInt8) cannot be inside Nullable type. (ILLEGAL_TYPE_OF_ARGUMENT)
```

And should be improved.
