### ISSUE TITLE
Options to turn on fsync on write for some cases.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#10286]
This feature was ordered by Yandex Cloud.

On decent SSD we can simply fsync every written data part. On slower devices we can support sync of large enough parts in background.

Note that data parts are 100% immutable (in versions 20.3+). If data part was written it's never modified.

1. MergeTree settings to do fsync of data part after background merge of sufficient size:
`min_rows_to_sync_after_merge`
`min_compressed_bytes_to_sync_after_merge`

Note that we also have a setting `min_merge_bytes_to_use_direct_io` but it's only loosely related because it doesn't sync metadata.

2. MergeTree settings to do fsync of data part after fetching from replica:
`min_rows_to_sync_after_fetch`
`min_compressed_bytes_to_sync_after_fetch`

Maybe we should introduce a setting `min_fetch_bytes_to_use_direct_io` and set it to the same default value as `min_merge_bytes_to_use_direct_io`.

3. Sync of merged data part on removal of any of source data parts.
`min_rows_to_sync_before_removing_source`
`min_compressed_bytes_to_sync_before_removing_source`

4. Sync on INSERT. 
The most dangerous option - simply issue fsync for every part files before returning from INSERT.
For ReplicatedMergeTree this step should be done after writing temporary data part on disk. And then, after renaming the directory, additional fsync command should be issued for directory.

5. Options to control sync of directories. It may be or may not be needed depending on filesystem.

References: http://danluu.com/file-consistency/

**Comment by alexey-milovidov** [comment]
> Sync of merged data part on removal of any of source data parts.

This is in question because fsync of a file that was written and closed is not guaranteed to work properly on Linux: https://stackoverflow.com/questions/37288453/calling-fsync2-after-close2

**Comment by qoega** [comment]
Just to make it clear. If we suppose the most paranoid setup(and have no bugs):
```
min_rows_to_sync_after_merge=1
min_rows_to_sync_before_removing_source=1
sync_on_insert=1
```
+ using RAID under fs.
We can't lose data after answering OK to user in case of sudden power failure or single disk failure?

**Comment by CurtizJ** [comment]
Some benchmarks.
Used table `hits` with query `INSERT INTO hits_compact(CounterID) SELECT rand() from numbers(100)`

Regular `hits` table.
```
Queries executed: 1000.

localhost:9000, queries 1000, QPS: 102.008, RPS: 10200.778, MiB/s: 0.078, result RPS: 0.000, result MiB/s: 0.000.

0.000%          0.006 sec.
10.000%         0.007 sec.
20.000%         0.008 sec.
30.000%         0.008 sec.
40.000%         0.008 sec.
50.000%         0.008 sec.
60.000%         0.008 sec.
70.000%         0.009 sec.
80.000%         0.009 sec.
90.000%         0.010 sec.
95.000%         0.011 sec.
99.000%         0.037 sec.
99.900%         0.250 sec.
99.990%         0.361 sec.
```

```SETTINGS sync_after_insert = 1, min_compressed_bytes_to_sync_after_merge = 1 ```
```
Queries executed: 2.

localhost:9000, queries 2, QPS: 0.089, RPS: 8.933, MiB/s: 0.000, result RPS: 0.000, result MiB/s: 0.000.

0.000%          11.142 sec.
10.000%         11.142 sec.
20.000%         11.142 sec.
30.000%         11.142 sec.
40.000%         11.142 sec.
50.000%         11.247 sec.
60.000%         11.247 sec.
70.000%         11.247 sec.
80.000%         11.247 sec.
90.000%         11.247 sec.
95.000%         11.247 sec.
99.000%         11.247 sec.
99.900%         11.247 sec.
99.990%         11.247 sec.
```

```SETTINGS min_bytes_for_wide_part = '10M'```
```
Queries executed: 1000.

localhost:9000, queries 1000, QPS: 364.336, RPS: 36433.606, MiB/s: 0.278, result RPS: 0.000, result MiB/s: 0.000.

0.000%          0.002 sec.
10.000%         0.002 sec.
20.000%         0.002 sec.
30.000%         0.002 sec.
40.000%         0.002 sec.
50.000%         0.002 sec.
60.000%         0.003 sec.
70.000%         0.003 sec.
80.000%         0.003 sec.
90.000%         0.003 sec.
95.000%         0.003 sec.
99.000%         0.009 sec.
99.900%         0.026 sec.
99.990%         0.036 sec.
```

```SETTINGS min_bytes_for_wide_part = '10M', sync_after_insert = 1, min_compressed_bytes_to_sync_after_merge = 1 ```
```
Queries executed: 186.

localhost:9000, queries 186, QPS: 12.967, RPS: 1296.736, MiB/s: 0.010, result RPS: 0.000, result MiB/s: 0.000.

0.000%          0.036 sec.
10.000%         0.043 sec.
20.000%         0.050 sec.
30.000%         0.055 sec.
40.000%         0.060 sec.
50.000%         0.068 sec.
60.000%         0.076 sec.
70.000%         0.083 sec.
80.000%         0.096 sec.
90.000%         0.117 sec.
95.000%         0.133 sec.
99.000%         0.255 sec.
99.900%         0.322 sec.
99.990%         0.322 sec.
```

**Comment by CurtizJ** [comment]
I've run benchmark on my cloud VM and it's very strange that fsyncs took so long. On my laptop queries with fsync were executed about 10 times faster, while other queries took the same time. Need to investigate.

**Comment by alexey-milovidov** [comment]
> We can't lose data after answering OK to user in case of sudden power failure or single disk failure?

No, you cannot.
There are multiple reasons why it's possible to lose your data if you use single replica:

- RAID write hole;
- non-atomic update of single sector on HDD;
- filesystem does not report fsync error due to bug;
- silent data corruption;

**Comment by socketpair** [comment]
So, what are the options finally ? I don't see any in the documentation.

**Comment by socketpair** [comment]
Finally, here are *undocumented*! options:
```
M(UInt64, min_rows_to_fsync_after_merge, 0, "Minimal number of rows to do fsync for part after merge (0 - disabled)", 0)
M(UInt64, min_compressed_bytes_to_fsync_after_merge, 0, "Minimal number of compressed bytes to do fsync for part after merge (0 - disabled)", 0)
M(UInt64, min_compressed_bytes_to_fsync_after_fetch, 0, "Minimal number of compressed bytes to do fsync for part after fetch (0 - disabled)", 0)
M(Bool, fsync_after_insert, false, "Do fsync for every inserted part. Significantly decreases performance of inserts, not recommended to use with wide parts.", 0)
M(Bool, fsync_part_directory, false, "Do fsync for part directory after all part operations (writes, renames, etc.).", 0)
```

**Comment by socketpair** [comment]
@nikitamikhaylov in what contexts these wars are supposed to be used ?
I mean at least three:
1. server config
2. table settings
3. query options.

Regarding `fsync_after_insert`. What's wrong if I set the option during data migration (`insert into new_table select from old_table`) ? I want to fsync the new table before dropping the old one.
