### ISSUE TITLE
Rename fails due to large amount of data in a single table

### ISSUE THREAD

**Issue by gubinjie** [ClickHouse/ClickHouse#10284]
I have a table with more than 500 columns and a data volume of 40 million. An exception occurred during the rename operation.
abnormal:
Timeout exceeded while receiving data from server.waited for 300 seconds, timeout is 300 seconds.
I want to ask why this problem occurs, is there any way to solve it? #8306

**Comment by alexey-milovidov** [comment]
What is the engine of a table that you are renaming?
And what is the version of clickhouse-server?

Also you can investigate the issue by turning on logs on client:
```
SET send_logs_level = 'trace'
```
before executing RENAME query.

Please attach these logs here.
