### ISSUE TITLE
Test for correctness of SQL-processing

### ISSUE THREAD

**Issue by Schaefer-Thomas** [ClickHouse/ClickHouse#10294]
Hi guys,
I love clickhouse, the attitude you adopted and your effort to make clickhouse a great open source tool and community! Thank you very much!

To improve the credibility of clickhouse, I would like to make you aware of the recent work of Manuel Rigger, who is already supporting other open-source DBMS with bug hunting.
You'll find more information on his website https://www.manuelrigger.at
https://www.manuelrigger.at/dbms-bugs/
It would be cool, if clickhouse would stand out also in terms of correctness against other open-source data projects.

Happy hacking!

**Comment by alexey-milovidov** [comment]
Ok, but the tool does not look available: https://github.com/sqlancer/sqlancer

**Comment by Schaefer-Thomas** [comment]
not yet, send him an email!

**Comment by mrigger** [comment]
Thanks a lot for pointing out our work @Schaefer-Thomas! SQLancer is now freely available at https://github.com/sqlancer/sqlancer. I even started with a very preliminary ClickHouse implementation, but did not have time to continue working on it. @alexey-milovidov, feel free to reach out to me if you have any plans in using SQLancer, or one of the testing approaches we developed, to test ClickHouse. A T-shirt would be awesome :grin:

**Comment by alexey-milovidov** [comment]
🎉 SQLancer has been successfuly integrated and already found some issues:
https://twitter.com/sqlancer_dbms/status/1286211595455082497
Thanks, @qoega.

**Comment by alexey-milovidov** [comment]
Next step is to add it to CI.

**Comment by alexey-milovidov** [comment]
> A T-shirt would be awesome

Easy. Just send your mailing address to clickhouse-feedback@yandex-team.com and we will send a t-shirt!
