### ISSUE TITLE
Total memory tracker should account all server memory usage, not only queries.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#10293]
This feature is ordered by Yandex.Metrica and it has very long story.

**Use case**
If the setting `max_memory_usage_for_all_queries` is set, the server may throw exceptions that the limit on memory usage is exceeded when actual memory usage is small.

This can be explained by the "drift" of memory usage. When memory is allocated while query execution and freed outside of query execution context, then free operation will not be accounted and the counter of queries memory usage will grow. Examples: loading of index for data parts; loading of data that will reside in caches.

We have some countermeasures to eliminate this "drift": when there are no queries in process list, then the counter of total memory usage for all queries is reset to zero. This countermeasure does not work in presense of long running queries or, specifically, when the number of simultaneously running queries never goes to zero.

We also tried to implement other countermeasures to make the counter of "memory_usage_for_all_queries" work properly. For example, when query is finished, we can subtract it's memory usage despite the fact that memory was not deallocated yet. This leads to even more inconsistent values.

**Describe the solution you'd like**
Deprecate the setting `max_memory_usage_for_all_queries`. It should have no effect.
Introduce a setting `max_server_memory_usage` that will limit memory usage in server as a whole (technically - only in threads where we initialize ThreadStatus).

Side note: this task was assigned to @abyss7 but he has moved to other task (implement build in Arcadia build system) that has higher priority.

Bonus: server wide memory profiler will be easy to implement.

**Comment by filimonov** [comment]
BTW: maybe we can just use jemalloc stats? Or you prefer not to rely on particular allocator?

**Comment by alexey-milovidov** [comment]
Yes, it was the idea but there are three considerations:
- surprisingly enough, there is no counter from jemalloc stats that correspond to process' resident set size;
- we also allocate some memory without jemalloc using mmap/munmap (but not enough to explain the previous consideration);
- we should not depend on specific allocator.

Current idea is to calculate total memory usage in complete different way:
- directly use process RSS from OS: https://github.com/ClickHouse/ClickHouse/commit/fdc5688d2d955da65628c5df0c6c57b88389af00
- update it with some period and sum up with delta.

This will allow to limit total RSS of the process. In contrast, our internal counters don't allow to account allocator caches.

**Comment by azat** [comment]
Refs: #16121
