### ISSUE TITLE
[FEATURE REQUEST] implements rfc1866 part 8.2.1 compatible parsing for decodeURLComponent

### ISSUE THREAD

**Issue by Slach** [ClickHouse/ClickHouse#10298]
**Use case**
Javascript `decodeURIComponent('1%202+3')`
and ClickHouse `decodeURLComponent('1%202+3')`
return same result
```
"1 2+3"
```
which compatible with http://www.faqs.org/rfcs/rfc3986.html

but other popular languages also follow http://www.faqs.org/rfcs/rfc1866.html 
```
8.2.1. The form-urlencoded Media Type

   The default encoding for all forms is `application/x-www-form-
   urlencoded'. A form data set is represented in this media type as
   follows:

        1. The form field names and values are escaped: space
        characters are replaced by `+'
``` 
PHP
`<? echo urldecode('1+2%203');?>`
Python
```
import urllib.parse
print(urllib.parse.unquote_plus('1+1%201'))
```
Golang
```
package main

import (
	"fmt"
	"net/url"
)
func main() {
	fmt.Println(url.QueryUnescape("1+2%203"))
}
```

return same
"1 2 3"
A clear and concise description of what is the intended usage scenario is.

Solution which I can propose, add second boolean parameter to `decodeURLComponent()`
or implements separately function `decodeXWWWFormURLEncoded`

current workaround replaceAll(decodeURLComponent("1+2%203"),'+',' ') corrupt data when data already contains "+" encoded as "%xx"

**Comment by alexey-milovidov** [comment]
@Slach We can name it `decodeURLFormComponent`.

**Comment by Slach** [comment]
@alexey-milovidov yep I think a separate function will better

**Comment by cmsxbc** [comment]
correct behavior should be `decodeURLFormComponent('1%2B2+3') == decodeURLComponent(replaceAll('1%2B2+3','+',' ')) == '1+2 3'`
