### ISSUE TITLE
column name is "interval"， select error

### ISSUE THREAD

**Issue by land012** [ClickHouse/ClickHouse#10300]
my ck version 20.1.4.14

### my table
merge table: trace_local
DESCRIBE TABLE trace_local
┌─name──────────┬─type─────┬
│ Logid         │ UInt64   │
│ Key           │ String   │
│ timestamp_us  │ Float64  │
│ module_name   │ String   │
│ interval      │ Float64  │
└───────────────┴──────────┴

distributed table: trace
DESCRIBE TABLE trace
┌─name──────────┬─type─────┬
│ Logid         │ UInt64   │
│ Key           │ String   │
│ timestamp_us  │ Float64  │
│ module_name   │ String   │
│ interval      │ Float64  │
└───────────────┴──────────┴

**problem is my table has a column "interval"**

### when i connect server by client
**select * from trace_local (success)**
**select \`interval\` from trace_local (failed)**
sh01-www-mola0117.sh01.baidu.com :) select \`interval\` from trace_local limit 3

SELECT interval
FROM trace_local
LIMIT 3

Received exception from server (version 20.1.4):
Code: 62. DB::Exception: Received from localhost:9000. DB::Exception: Syntax error: failed at position 22: trace_local LIMIT 3. Expected one of: S, N, AND, OR, alias, token, AS, NOT, BETWEEN, LIKE, IS, NOT LIKE, IN, NOT IN, GLOBAL IN, GLOBAL NOT IN, Comma, Dot, Arrow, QuestionMark, SECOND, SQL_TSI_SECOND, SS, MINUTE, SQL_TSI_MINUTE, MI, HOUR, SQL_TSI_HOUR, HH, DAY, SQL_TSI_DAY, DD, D, WEEK, SQL_TSI_WEEK, WK, WW, MONTH, SQL_TSI_MONTH, MM, M, QUARTER, SQL_TSI_QUARTER, QQ, Q, YEAR, SQL_TSI_YEAR, YYYY, YY. 

**select * from trace(failed)**
↗ Progress: 0.00 rows, 0.00 B (0.00 rows/s., 0.00 B/s.) Received exception from server (version 20.1.4):
Code: 62. DB::Exception: Received from localhost:9000. DB::Exception: Received from sh01-www-mola0170.sh01:9000. DB::Exception: Syntax error: failed at position 198: FROM testdb.trace_local LIMIT 1. Expected one of: token, Comma, Arrow. 

### connect server by go api
github.com/ClickHouse/clickhouse-go

**select \`interval\` from trace_local(success)**

**select \`interval\` from trace(failed)**
[clickhouse]host(s)=sh01-www-mola0117.sh01:9000, database=default, username=default
[clickhouse][dial] secure=false, skip_verify=false, strategy=random, ident=1, server=0 -> 10.201.30.44:9000
[clickhouse][connect=1][hello] -> Golang SQLDriver 1.1.54213
[clickhouse][connect=1][hello] <- ClickHouse 20.1.54431 (Asia/Shanghai)
[clickhouse][connect=1][prepare] select hostName() AS HostName, url, "interval" FROM testdb.trace ORDER BY Logid limit 10
[clickhouse][connect=1][send query] select hostName() AS HostName, url, "interval" FROM testdb.trace ORDER BY Logid limit 10
[clickhouse][connect=1][read meta] <- data: packet=1, columns=3, rows=0
[clickhouse][connect=1][rows] <- exception
[clickhouse][connect=1][rows] close
[clickhouse][connect=1][stmt] close

**Comment by alexey-milovidov** [comment]
Fixed in https://github.com/ClickHouse/ClickHouse/pull/9142

**Comment by alexey-milovidov** [comment]
You should update the version either to 20.1.9+ or 20.3.6+.

**Comment by land012** [comment]
thank you!
