### ISSUE TITLE
toUInt64(DateTime64) cuts milliseconds (fractions of a second)

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#10310]
```
SELECT
    '1586275212.123' AS x,
    toDateTime64(x, 3) AS t,
    toUnixTimestamp(t) AS y,
    toUInt64(t) AS z

┌─x──────────────┬───────────────────────t─┬──────────y─┬──────────z─┐
│ 1586275212.123 │ 2020-04-07 16:00:12.123 │ 1586275212 │ 1586275212 │
└────────────────┴─────────────────────────┴────────────┴────────────┘
```

extected z= 1586275212123 (I would like the same for toUnixTimestamp but it's questionable).

**Comment by filimonov** [comment]
Why do you think it's a bug?

Current behavior is compatible with Decimal:
```sql
select toUInt64(toDecimal64(1586275212.123,3));
```
with usual DateTime (returns seconds) 

and makes roundtrip possible: 
```
select toDateTime64(toUInt64(1586275212),3);
``` 
May be we should add support for reinterpretAsInt64 for toDateTime64 abd Decimal64...

**Comment by filimonov** [comment]
I think that FR will cover the usecase: #10672 ?

**Comment by den-crane** [comment]
it does.

**Comment by den-crane** [comment]
```
SELECT
    now64() AS x,
    toFloat64(x) AS y,
    toUInt64(replace(toString(y), '.', '')) AS w,
    toDateTime64(w / 1000, 3) AS z

┌───────────────────────x─┬──────────────y─┬─────────────w─┬───────────────────────z─┐
│ 2020-07-14 15:28:55.863 │ 1594740535.863 │ 1594740535863 │ 2020-07-14 15:28:55.863 │
└─────────────────────────┴────────────────┴───────────────┴─────────────────────────┘
```

**Comment by maxuewen** [comment]
`
SELECT
    '1586275212.123' AS x,
    toDateTime64(x, 3) AS t,
    toUnixTimestamp(t) AS y,
    toUnixTimestamp64Milli(t) AS z

┌─x──────────────┬───────────────────────t─┬──────────y─┬─────────────z─┐
│ 1586275212.123 │ 2020-04-08 00:00:12.123 │ 1586275212 │ 1586275212123 │
└────────────────┴─────────────────────────┴────────────┴───────────────┘
`
