### ISSUE TITLE
When we insert the MergeTree engine table, all the data in the table is cleared

### ISSUE THREAD

**Issue by gubinjie** [ClickHouse/ClickHouse#10319]
When we insert the MergeTree engine table, all the data in the table is cleared, which is a very serious problem.
Our version number: 19.16.4.12
table_examples_hdfs table data is 400 million rows with more than 500 columns
Table examples: 1. table_examples (MergeTree engine)
                 2. table_examples_tmp (MergeTree engine)
                 3. table_examples_hdfs (HDFS engine)
The three table fields are the same
I inserted data from table_examples_hdfs table into table_examples_tmp (sql: insert into table_examples_tmp (***) select *** from table_examples_hdfs where ****), during the execution process, we found that the data in table_examples_tmp table is growing, but When the insert is completed, we find that the data in the table_examples_tmp table is cleared.
We found no useful logs.
We looked at this table_examples_tmp table file and found that the user of the folder is the same as the user of the folder of the other table is Clickhouse, but we found that the user group is different from the other table, the folder user group of the table_examples_tmp table is Clickhouse, and The user group of other tables is root.

**Comment by filimonov** [comment]
>  Our version number: 19.16.4.12

Update to the latest 19.16 release.

>  gubinjie closed this 4 hours ago

Please write some note about why did you close the issue

Also please provide the required information in https://github.com/ClickHouse/ClickHouse/issues/10284

**Comment by gubinjie** [comment]
@filimonov Sorry, we checked for a few days and found that it was a problem with our application, which caused data loss, so I closed this bug.
