### ISSUE TITLE
Add more ON CLUSTER functionality to ALTER TABLE

### ISSUE THREAD

**Issue by pic-Nick** [ClickHouse/ClickHouse#10314]
It would be useful if the functionality of ALTER TABLE dest REPLACE PARTITION partition_expr FROM source were extended by ON CLUSTER clause like it does for ALTER TABLE ... DROP PARTITION.

**Use case**
Faster and convenient way to replace partition in distributed table.

**Describe the solution you'd like**
If all shards in the cluster have dest and source tables, the operation runs on each shard normally.
If any shard misses partition in source table, partition in this shard is skipped.
If any shard misses the source table, the whole operation fails.

**Additional context**
ALTER TABLE dest_tbl ON CLUSTER cluster REPLACE PARTITION part FROM src_tbl

Code: 48, e.displayText() = DB::Exception: Unsupported type of ALTER query (version 20.3.5.21 (official build))

**Comment by tavplubix** [comment]
Most of `ALTER ... PARTITION` queries are supported now
