### ISSUE TITLE
Possibility to call a lamda

### ISSUE THREAD

**Issue by crakjie** [ClickHouse/ClickHouse#10327]
I would be nice to be able to call user defined function directly. 

**Use case**
I came to this idea because if I do something like 
`if(condition(heavy_function_call), heavy_function_call_value, anotherValue) `
in this case `heavy_function_call` is called twice, consuming twice as cpu needed

**Describe the solution you'd like**
But if we were able to do something like this : 
` apply(heavy_function_call, x-> if(condition(x),x,anotherValue)` the value would be computed only once. We could even imagine to have the first this parameter memoize to be computed only if used. 

**Describe alternatives you've considered**
With x-> x +1 as u  //which seems to already suported
select u(1)

At first glance this solution look like cleaner but it's a lot more context bonded while define and a call a function directly in the query could be way easier when query is programmatically generated.

**Additional context**
function like `andThen` or `compose` could aslo be a good addon.

**Comment by filimonov** [comment]
> if(condition(heavy_function_call), heavy_function_call_value, anotherValue)
> in this case heavy_function_call is called twice, consuming twice as cpu needed

Why do you think so?

```
SELECT count(if(sleepEachRow(0.1), sleepEachRow(0.1), 0))
FROM numbers(100)

┌─count(if(sleepEachRow(0.1), sleepEachRow(0.1), 0))─┐
│                                                100 │
└────────────────────────────────────────────────────┘

1 rows in set. Elapsed: 10.002 sec. 

```

In that sample - if the sleepEachRow would be executed twice the execution time would be 20 sec.

**Comment by den-crane** [comment]
```
SELECT
    rand() = rand(),
    rand(),
    rand()
FROM numbers(10)

┌─equals(rand(), rand())─┬─────rand()─┬─────rand()─┐
│                      1 │  391924423 │  391924423 │
│                      1 │ 1383619981 │ 1383619981 │
│                      1 │ 1060033606 │ 1060033606 │
│                      1 │ 1876756544 │ 1876756544 │
│                      1 │ 1200991990 │ 1200991990 │
│                      1 │ 3673036002 │ 3673036002 │
│                      1 │ 4209145600 │ 4209145600 │
│                      1 │  654336070 │  654336070 │
│                      1 │ 2630643631 │ 2630643631 │
│                      1 │ 1592936181 │ 1592936181 │
└────────────────────────┴────────────┴────────────┘
```

**Comment by crakjie** [comment]
@filimonov maybe it's a bad understanding of the documentation but [here](https://clickhouse.tech/docs/en/sql_reference/functions/conditional_functions/#if) it's wrote that :

> The function executes then and else expressions and returns its result, depending on whether the condition cond ended up being zero or not. 

And I read that like "both then and else are executed what every the result of cond is".

So what we so here is clickhouse is able to memoize function call even when they are inside other functions 


@den-crane I dont see your point here.
