### ISSUE TITLE
Materialized view from local replicated table calculates the wrong result

### ISSUE THREAD

**Issue by BernieJiangDL** [ClickHouse/ClickHouse#10326]
First, I created  replicatedMergeTree tables on each node of the cluster  and  distributed tables among them.
 
And My workers insert records into local replicatedMergeTree tables directly instead of distributed tables.

Then I have to created materialized view with replicatedAggregateMergeTree engine based on replicatedMergeTree.

And I created a distributed table on the  tables of replicatedAggregateMergeTree engine. When I execute "select sum" statement, It gets the wrong answer comparing with totally the same statement on replicatedMergeTree tables.

Any ideas?

**Comment by den-crane** [comment]
Materialized view is an insert trigger it catches data from inserts. 
Did you create your MV at all CH nodes? 

It would be nice to see DDL of MV. Very often users create MV table with wrong partition by / order by inconsistent with MV select.

**Comment by BernieJiangDL** [comment]
> Materialized view is an insert trigger it catches data from inserts.
> Did you create your MV at all CH nodes?
> 
> It would be nice to see DDL of MV. Very often users create MV table with wrong `partition by` / `order by` -- inconsistent with MV select.

Thanks for your reply.

**Comment by BernieJiangDL** [comment]
> Materialized view is an insert trigger it catches data from inserts.
> Did you create your MV at all CH nodes?
> 
> It would be nice to see DDL of MV. Very often users create MV table with wrong `partition by` / `order by` -- inconsistent with MV select.

Thanks for your reply. 
1. Yes, I created MV at all my CH nodes. 

2. the all DDL of tables are below:
(1) The local replicatedMergeTree Table:
CREATE TABLE report.t_diagnosis_analysis_data_new on cluster ch_cluster(
`hour` String, 
`minute` String, 
`scene` String, 
`page_type` String,
`device_os_type` String, 
`count` Int64) 
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{layer}-{shard}/t_diagnosis_analysis_data_new', '{replica}') 
PARTITION BY hour 
ORDER BY (minute, scene, page_type, device_os_type) 
SETTINGS index_granularity = 8192
-----> NOTICE: there is also a distributed table on t_diagnosis_analysis_data_new which named t_diagnosis_analysis_data_new_view and engine is Distributed.

(2) The MV DDL:
CREATE MATERIALIZED VIEW materialized.t_minute_scene_monitor_local_replica on cluster ch_cluster (
`hour` String, 
`minute` String, 
`scene` String, 
`count` Int64) 
ENGINE = ReplicatedAggregatingMergeTree('/clickhouse/tables/{layer}-{shard}/t_minute_scene_monitor_local_replica', '{replica}') 
PARTITION BY hour ORDER BY (hour, minute, scene) SETTINGS index_granularity = 8192 
AS SELECT hour, minute, scene, sum(count) AS count FROM report.t_diagnosis_analysis_data_new  
GROUP BY hour, minute, scene

(3) the DDL of distributed table:
CREATE TABLE materialized.t_minute_scene_monitor_local_replica_view on cluter ch_cluster(
`hour` String, `minute` String, `scene` String, `count` Int64) 
ENGINE = Distributed(xsad_ck_cluster, materialized, t_minute_scene_monitor_local_replica, rand())

Question is:
the insertions happen on ReplicatedMergeTree tables directly, which means, as you mentioned, the MV could catches data from insertions of ReplicatedMergeTree table. But when I query a certain data set, the diffrence between t_diagnosis_analysis_data_new_view and t_minute_scene_monitor_local_replica_view  is found.

Is anything wrong with those?

Thanks.~

**Comment by den-crane** [comment]
ReplicatedAggregatingMergeTree -- is incompatible with sum(count). 
it does not calculate sums automatically as summingMT does.

1. The easiest and the most efficient way in case is to use SummingMergeTree

```
CREATE MATERIALIZED VIEW materialized.t_minute_scene_monitor_local_replica on cluster ch_cluster (
hour String,
minute String,
scene String,
count Int64)
ENGINE = ReplicatedSummingMergeTree('/clickhouse/tables/{layer}-{shard}/t_minute_scene_monitor_local_replica', '{replica}')
PARTITION BY hour ORDER BY (hour, minute, scene)
AS SELECT hour, minute, scene, sum(count) AS count 
FROM report.t_diagnosis_analysis_data_new
GROUP BY hour, minute, scene
```

2. Or to use AggregatingMergeTree + SimpleAggregatingFunctions
````
CREATE MATERIALIZED VIEW t_minute_scene_monitor_local_replica(
hour String,
minute String,
scene String,
count SimpleAggregateFunction(sum,Int64)
)
ENGINE = ReplicatedAggregatingMergeTree('/clickhouse/tables/{layer}-{shard}/t_minute_scene_monitor_local_replica', '{replica}')
PARTITION BY hour ORDER BY (hour, minute, scene)
AS SELECT hour, minute, scene, sum(count) AS count 
FROM t_diagnosis_analysis_data_new
GROUP BY hour, minute, scene
```


3. Or to sum states , but it's inefficient and not recommended way for sums

```
CREATE MATERIALIZED VIEW t_minute_scene_monitor_local_replica(
hour String,
minute String,
scene String,
count AggregateFunction(sum,Int64)
)
ENGINE = ReplicatedAggregatingMergeTree('/clickhouse/tables/{layer}-{shard}/t_minute_scene_monitor_local_replica', '{replica}')
PARTITION BY hour ORDER BY (hour, minute, scene)
AS SELECT hour, minute, scene, sumState(count) AS count 
FROM t_diagnosis_analysis_data_new
GROUP BY hour, minute, scene ```
and requiers to use sumMerge in selects 
```
select hour, minute, scene, sumMerge(count) 
from t_minute_scene_monitor_local_replica
group by hour, minute, scene```

**Comment by BernieJiangDL** [comment]
> ReplicatedAggregatingMergeTree -- needs AggregateFunctions. It does not calculate sums automatically as summingMT does.
> 
> 1. The easiest and the most efficient way in case is to use SummingMergeTree
> 
> ```
> CREATE MATERIALIZED VIEW materialized.t_minute_scene_monitor_local_replica on cluster ch_cluster (
> hour String,
> minute String,
> scene String,
> count Int64)
> ENGINE = ReplicatedSummingMergeTree('/clickhouse/tables/{layer}-{shard}/t_minute_scene_monitor_local_replica', '{replica}')
> PARTITION BY hour ORDER BY (hour, minute, scene)
> AS SELECT hour, minute, scene, sum(count) AS count 
> FROM report.t_diagnosis_analysis_data_new
> GROUP BY hour, minute, scene
> ```
> 
> 1. Or to use AggregatingMergeTree + SimpleAggregatingFunctions
> 
> ```
> CREATE MATERIALIZED VIEW materialized.t_minute_scene_monitor_local_replica on cluster ch_cluster (
> hour String,
> minute String,
> scene String,
> count SimpleAggregateFunction(sum,Int64)
> )
> ENGINE = ReplicatedAggregatingMergeTree('/clickhouse/tables/{layer}-{shard}/t_minute_scene_monitor_local_replica', '{replica}')
> PARTITION BY hour ORDER BY (hour, minute, scene)
> AS SELECT hour, minute, scene, sum(count) AS count 
> FROM report.t_diagnosis_analysis_data_new
> GROUP BY hour, minute, scene
> ```
> 
> 1. Or to use sum states , but it's inefficient and not recommended way for sums
> 
> ```
> CREATE MATERIALIZED VIEW materialized.t_minute_scene_monitor_local_replica on cluster ch_cluster (
> hour String,
> minute String,
> scene String,
> count AggregateFunction(sum,Int64)
> )
> ENGINE = ReplicatedAggregatingMergeTree('/clickhouse/tables/{layer}-{shard}/t_minute_scene_monitor_local_replica', '{replica}')
> PARTITION BY hour ORDER BY (hour, minute, scene)
> AS SELECT hour, minute, scene, sumState(count) AS count 
> FROM report.t_diagnosis_analysis_data_new
> GROUP BY hour, minute, scene
> ```
> 
> and requires to use sumMerge in selects
> 
> ```
> select hour, minute, scene, sumMerge(count) 
> from t_minute_scene_monitor_local_replica
> group by hour, minute, scene
> ```

Thanks for your suggestions. I am going to try the most efficient way you mentioned. 

I would reply this message if there are other problems. Thanks a lot.

**Comment by BernieJiangDL** [comment]
> ReplicatedAggregatingMergeTree -- needs AggregateFunctions. It does not calculate sums automatically as summingMT does.
> 
> 1. The easiest and the most efficient way in case is to use SummingMergeTree
> 
> ```
> CREATE MATERIALIZED VIEW materialized.t_minute_scene_monitor_local_replica on cluster ch_cluster (
> hour String,
> minute String,
> scene String,
> count Int64)
> ENGINE = ReplicatedSummingMergeTree('/clickhouse/tables/{layer}-{shard}/t_minute_scene_monitor_local_replica', '{replica}')
> PARTITION BY hour ORDER BY (hour, minute, scene)
> AS SELECT hour, minute, scene, sum(count) AS count 
> FROM report.t_diagnosis_analysis_data_new
> GROUP BY hour, minute, scene
> ```
> 
> 1. Or to use AggregatingMergeTree + SimpleAggregatingFunctions
> 
> ```
> CREATE MATERIALIZED VIEW materialized.t_minute_scene_monitor_local_replica on cluster ch_cluster (
> hour String,
> minute String,
> scene String,
> count SimpleAggregateFunction(sum,Int64)
> )
> ENGINE = ReplicatedAggregatingMergeTree('/clickhouse/tables/{layer}-{shard}/t_minute_scene_monitor_local_replica', '{replica}')
> PARTITION BY hour ORDER BY (hour, minute, scene)
> AS SELECT hour, minute, scene, sum(count) AS count 
> FROM report.t_diagnosis_analysis_data_new
> GROUP BY hour, minute, scene
> ```
> 
> 1. Or to use sum states , but it's inefficient and not recommended way for sums
> 
> ```
> CREATE MATERIALIZED VIEW materialized.t_minute_scene_monitor_local_replica on cluster ch_cluster (
> hour String,
> minute String,
> scene String,
> count AggregateFunction(sum,Int64)
> )
> ENGINE = ReplicatedAggregatingMergeTree('/clickhouse/tables/{layer}-{shard}/t_minute_scene_monitor_local_replica', '{replica}')
> PARTITION BY hour ORDER BY (hour, minute, scene)
> AS SELECT hour, minute, scene, sumState(count) AS count 
> FROM report.t_diagnosis_analysis_data_new
> GROUP BY hour, minute, scene
> ```
> 
> and requires to use sumMerge in selects
> 
> ```
> select hour, minute, scene, sumMerge(count) 
> from t_minute_scene_monitor_local_replica
> group by hour, minute, scene
> ```

By the way, I have another question: 
Is MV supports “join” clause when using "AS SELECT ..."

**Comment by den-crane** [comment]
Yes, it does support but:
MV is an insert trigger. It watches inserts into LEFT FROM TABLE only.
So you can create MV `as select ... from SOMELEFT join SOMERIGHT`, but MV will be triggered by inserts into SOMELEFT. 
Plus another problem that JOINs are slow and MV with JOIN with large SOMERIGHT will slow down inserts significantly.

**Comment by BernieJiangDL** [comment]
> Yes, it does support but:
> MV is an insert trigger. It watches inserts into LEFT FROM TABLE only.
> So you can create MV `as select ... from SOMELEFT join SOMERIGHT`, but MV will be triggered by inserts into SOMELEFT.
> Plus another problem that JOINs are slow and MV with JOIN with large SOMERIGHT will slow down inserts significantly.

Got it! Thank! Haha, after a whole day`s thinking(yesterday), I got two more questions:
1. If I create too many MV tables on a certain mergeTree table, do them slow down the inserts on that base table(mergeTree), or do them have impact on that table's query performance.
eg: each MV with summingMergeTree engine of that mergeTree table would merge and aggregate data, when a insert happens on base table. It seems that the inserts and queries on that base table will be slower?

2. As we discussed before, maybe 2 mouth ago, if I create a MV on a table, are the inserts on that table actomic? If not, why a external table(MV) would change the way of inserts on "base" mergeTree Table?

Thanks~

**Comment by BernieJiangDL** [comment]
> Yes, it does support but:
> MV is an insert trigger. It watches inserts into LEFT FROM TABLE only.
> So you can create MV `as select ... from SOMELEFT join SOMERIGHT`, but MV will be triggered by inserts into SOMELEFT.
> Plus another problem that JOINs are slow and MV with JOIN with large SOMERIGHT will slow down inserts significantly.

Hi~~~ here~~~ need help~~~thanks~~~

**Comment by den-crane** [comment]
1. Yes, MV impacts on system performance and `Insert` works longer, it finishes when all MVs inserted their data.

2. No atomicity. No consistency. 
MV can break insert into source table in the middle.
MV can insert part of the rows inserted into the source table.
see explantion https://clickhouse.tech/docs/en/operations/settings/settings/#settings-deduplicate-blocks-in-dependent-materialized-views
