### ISSUE TITLE
 load_balancing & prefer_localhost_replica ignored for inserts 

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#10328]
Inserts go through the Distributed table and can come to any of the cluster nodes. THen data get distributed across the cluster with some sharding key. 

We need always to do insert into the first replica of the shard (unless it's broken). That is needed to make some hand-made deduplication schema work.

So we use load_balancing=in_order and prefer_localhost_replica=0 for inserts into Distributed, but it ignores those settings.

**Comment by alexey-milovidov** [comment]
Do you use synchronous or asynchronous INSERTs?

**Comment by filimonov** [comment]
Did try both, normally async.
