### ISSUE TITLE
Error when execute alter ** delete query

### ISSUE THREAD

**Issue by onine007** [ClickHouse/ClickHouse#10324]
version: 19.15.4

┌─host──────┬─port─┬─status─┬─error─────────────────────────────────────────┬─num_hosts_remaining─┬─num_hosts_active─┐
│ sdapck005 │ 9000 │     48 │ Cannot execute replicated DDL query on leader │                   1 │                1 │
└───────────┴──────┴────────┴───────────────────────────────────────────────┴─────────────────────┴──────────────────┘
┌─host──────┬─port─┬─status─┬─error─────────────────────────────────────────┬─num_hosts_remaining─┬─num_hosts_active─┐
│ sdapck006 │ 9000 │     48 │ Cannot execute replicated DDL query on leader │                   0 │                0 │
└───────────┴──────┴────────┴───────────────────────────────────────────────┴─────────────────────┴──────────────────┘
→ Progress: 5.00 rows, 310.00 B (0.36 rows/s., 22.52 B/s.)  82%Received exception from server (version 20.3.5):
Code: 48. DB::Exception: Received from localhost:9000. DB::Exception: There was an error on [sdapck005:9000]: Cannot execute replicated DDL query on leader. 

 log: 

2020.04.17 15:05:17.678873 [ 44 ] {} <Error> my_sdap.crowd_bitmap_result_replicated (ReplicatedMergeTreeRestartingThread): void DB::ReplicatedMergeTreeRestartingThread::run(): Code: 27, e.displayText() = DB::Exception: Cannot parse input: expected eof before: \nalter version: -1, Stack trace:

0. 0x33ddd00 StackTrace::StackTrace() /usr/bin/clickhouse
1. 0x33e7f4f DB::Exception::Exception(std::string const&, int) /usr/bin/clickhouse
2. 0x3404104 DB::throwAtAssertionFailed(char const*, DB::ReadBuffer&) /usr/bin/clickhouse
3. 0x3404f0f DB::assertEOF(DB::ReadBuffer&) /usr/bin/clickhouse
4. 0x639c9a2 DB::ReplicatedMergeTreeMutationEntry::parse(std::string const&, std::string) /usr/bin/clickhouse
5. 0x63b011d DB::ReplicatedMergeTreeQueue::updateMutations(std::shared_ptr<zkutil::ZooKeeper>, std::function<void (Coordination::WatchResponse const&)>) /usr/bin/clickhouse
6. 0x63b0aaa DB::ReplicatedMergeTreeQueue::pullLogsToQueue(std::shared_ptr<zkutil::ZooKeeper>, std::function<void (Coordination::WatchResponse const&)>) /usr/bin/clickhouse
7. 0x63bc212 DB::ReplicatedMergeTreeRestartingThread::tryStartup() /usr/bin/clickhouse
8. 0x63bcf28 DB::ReplicatedMergeTreeRestartingThread::run() /usr/bin/clickhouse
9. 0x65380a4 DB::BackgroundSchedulePoolTaskInfo::execute() /usr/bin/clickhouse
10. 0x6538c72 DB::BackgroundSchedulePool::threadFunction() /usr/bin/clickhouse
11. 0x6538cd4 ? /usr/bin/clickhouse
12. 0x341fb13 ThreadPoolImpl<std::thread>::worker(std::_List_iterator<std::thread>) /usr/bin/clickhouse
13. 0x7733adf ? /usr/bin/clickhouse
14. 0x7fb2ce70ae65 start_thread /usr/lib64/libpthread-2.17.so
15. 0x7fb2ce02788d clone /usr/lib64/libc-2.17.so
 (version 19.15.4.10)
2020.04.17 15:05:18.054974 [ 24 ] {} <Error> my_sdap.bookmark_task_bitmap_result_replicated (ReplicatedMergeTreeRestartingThread): void DB::ReplicatedMergeTreeRestartingThread::run(): Code: 27, e.displayText() = DB::Exception: Cannot parse input: expected eof before: \nalter version: -1, Stack trace:

0. 0x33ddd00 StackTrace::StackTrace() /usr/bin/clickhouse
1. 0x33e7f4f DB::Exception::Exception(std::string const&, int) /usr/bin/clickhouse
2. 0x3404104 DB::throwAtAssertionFailed(char const*, DB::ReadBuffer&) /usr/bin/clickhouse
3. 0x3404f0f DB::assertEOF(DB::ReadBuffer&) /usr/bin/clickhouse
4. 0x639c9a2 DB::ReplicatedMergeTreeMutationEntry::parse(std::string const&, std::string) /usr/bin/clickhouse
5. 0x63b011d DB::ReplicatedMergeTreeQueue::updateMutations(std::shared_ptr<zkutil::ZooKeeper>, std::function<void (Coordination::WatchResponse const&)>) /usr/bin/clickhouse
6. 0x63b0aaa DB::ReplicatedMergeTreeQueue::pullLogsToQueue(std::shared_ptr<zkutil::ZooKeeper>, std::function<void (Coordination::WatchResponse const&)>) /usr/bin/clickhouse
7. 0x63bc212 DB::ReplicatedMergeTreeRestartingThread::tryStartup() /usr/bin/clickhouse
8. 0x63bcf28 DB::ReplicatedMergeTreeRestartingThread::run() /usr/bin/clickhouse
9. 0x65380a4 DB::BackgroundSchedulePoolTaskInfo::execute() /usr/bin/clickhouse
10. 0x6538c72 DB::BackgroundSchedulePool::threadFunction() /usr/bin/clickhouse
11. 0x6538cd4 ? /usr/bin/clickhouse
12. 0x341fb13 ThreadPoolImpl<std::thread>::worker(std::_List_iterator<std::thread>) /usr/bin/clickhouse
13. 0x7733adf ? /usr/bin/clickhouse
14. 0x7fb2ce70ae65 start_thread /usr/lib64/libpthread-2.17.so
15. 0x7fb2ce02788d clone /usr/lib64/libc-2.17.so
 (version 19.15.4.10)

**Comment by alesapin** [comment]
Unfortunately, you have to update all servers of your cluster to 20.3 to execute `ALTER` queries because this functionality significantly changed under the hood. As I can see from your log you have a problem with 19.15  when alter started from 20.3 server.
