### ISSUE TITLE
HDFS Engine and TOO MUCH PARTS

### ISSUE THREAD

**Issue by gubinjie** [ClickHouse/ClickHouse#10321]
We are HADOOP users and need to synchronize data from HDFS to ClickHouse every day. The current method is HDFS Engine: https://clickhouse.tech/docs/en/engines/table_engines/integrations/hdfs/

The current daily data volume is 500 million, 550 columns, most of which are successfully synchronized.

But recently we encountered the problem of too much parts (300), we tried to adjust the parameters: parts_to_delay_insert is 10000. For now, everything is normal.

For long-term system stability considerations, I would like to ask how the HDFS Engine triggers too many parts, and how can it be completely avoided, rather than adjusting the parameters by chance.

Thank you very much ClickHouse team for developing such an excellent product, thank you again.

**Comment by nickevin** [comment]
I encountered a similar problem, are there configurable parameters that can be provided when using the hdfs engine?

**Comment by gj-zhang** [comment]
> We are HADOOP users and need to synchronize data from HDFS to ClickHouse every day. The current method is HDFS Engine: https://clickhouse.tech/docs/en/engines/table_engines/integrations/hdfs/
> 
> The current daily data volume is 500 million, 550 columns, most of which are successfully synchronized.
> 
> But recently we encountered the problem of too much parts (300), we tried to adjust the parameters: parts_to_delay_insert is 10000. For now, everything is normal.
> 
> For long-term system stability considerations, I would like to ask how the HDFS Engine triggers too many parts, and how can it be completely avoided, rather than adjusting the parameters by chance.
> 
> Thank you very much ClickHouse team for developing such an excellent product, thank you again.

@gubinjie hi  do you resolve it? can we talk on wechat?

**Comment by gubinjie** [comment]
@gj-zhang 
We were using the 19.x version at the time. The too many parts problem occurred due to the failure to arrange the partition key properly, and the Zookeeper service was terminated.
Our approach: 1, re-optimize the partition field
2. Modify the similar attribute value: max_partitions_per_insert_*
The new version of ClickHouse has optimized this anomaly at the bottom layer, and uses the WAL pre-write function. You can check it out.

**Comment by gj-zhang** [comment]
> @gj-zhang
> We were using the 19.x version at the time. The too many parts problem occurred due to the failure to arrange the partition key properly, and the Zookeeper service was terminated.
> Our approach: 1, re-optimize the partition field
> 2. Modify the similar attribute value: max_partitions_per_insert_*
> The new version of ClickHouse has optimized this anomaly at the bottom layer, and uses the WAL pre-write function. You can check it out.

thank you

**Comment by gj-zhang** [comment]
the usage:
insert into clickhouse_table select * from hdfs_engine_table?   
whether it takes up a lot of memory

**Comment by gubinjie** [comment]
@gj-zhang When we first used the Hdfs engine, the Hive orc format table used was required to be decompressed for synchronization, which occupied a lot of memory resources. Later, we converted **the orc table into a text format table,** and it was normal.

**Comment by gj-zhang** [comment]
> @gj-zhang When we first used the Hdfs engine, the Hive orc format table used was required to be decompressed for synchronization, which occupied a lot of memory resources. Later, we converted **the orc table into a text format table,** and it was normal.

thank you

**Comment by gj-zhang** [comment]
> @gj-zhang When we first used the Hdfs engine, the Hive orc format table used was required to be decompressed for synchronization, which occupied a lot of memory resources. Later, we converted **the orc table into a text format table,** and it was normal.

hi, I have two questions, please help to check
1. What format does hive use for the default delimiter (0x001)?
2. Column "xxx" is not presented in input data.: While executing HDFS. do you know what's this?

**Comment by gubinjie** [comment]
@gj-zhang 
1. Format \001
2. It may be that your field was added by alter after the table was created, resulting in that the field data does not exist in some partitions

**Comment by gj-zhang** [comment]
> @gj-zhang
> 
> 1. Format \001
> 2. It may be that your field was added by alter after the table was created, resulting in that the field data does not exist in some partitions

OK thanks
