### ISSUE TITLE
access only from localhost doen't work

### ISSUE THREAD

**Issue by TimonKK** [ClickHouse/ClickHouse#10336]
I have setting for default user in users.xml:
```xml
            <networks replace="replace">
                <ip>::1</ip>
                <ip>127.0.0.1</ip>
            </networks>
```
But I can connect to Clickhouse not from localhost. In log I see
2020.04.17 19:26:27.477646 [ 15238 ] {} <Trace> HTTPHandler: Request URI: /?query=SHOW%20TABLES
2020.04.17 19:26:27.477983 [ 15238 ] {176e3f94-bf95-47cb-9acd-e021798054e3} <Debug> executeQuery: (from **MY_EXTERNAL_IP**:38648) SHOW TABLES 
2020.04.17 19:26:27.478278 [ 15238 ] {176e3f94-bf95-47cb-9acd-e021798054e3} <Debug> executeQuery: (internal) SELECT name FROM system.tables WHERE database = 'default'
2020.04.17 19:26:27.478833 [ 15238 ] {176e3f94-bf95-47cb-9acd-e021798054e3} <Trace> AccessRightsContext (default): Access granted: SELECT(database, name) ON system.tables

ClickHouse client version 20.3.7.46 (official build).
Connecting to 185.86.92.19:9000 as user default.
Connected to ClickHouse server version 20.3.7 revision 54433.

**Comment by den-crane** [comment]
could not reproduce

cat /etc/clickhouse-server/conf.d/user_default.xml
<?xml version="1.0" ?>
<yandex>
    <users>
        <default>
            <networks>
                <ip>::1</ip>
                <ip>127.0.0.1</ip>
            </networks>
        </default>
    </users>
</yandex>

clickhouse-client -h xxxx -q 'select 1'
Code: 516. DB::Exception: Received from xxxx:9000. DB::Exception: default: Authentication failed: password is incorrect or there is no user with such name.

2020.04.17 17:09:35.449495 [ 413492 ] {} <Trace> TCPHandlerFactory: TCP Request. Address: [::ffff:10.xxxx]:40036
2020.04.17 17:09:35.449568 [ 413492 ] {} <Debug> TCPHandler: Connected ClickHouse client version 19.13.0, revision: 54425, user: default.
2020.04.17 17:09:35.449957 [ 413492 ] {} <Error> ServerErrorHandler: Code: 516, e.displayText() = DB::Exception: default: Authentication failed: password is incorrect or there is no user with such name, Stack trace (when copying this message, always include the lines below):

 (version 20.3.7.46 (official build))

**Comment by TimonKK** [comment]
What does attribute  **replace="replace"** mean in networks tags?

**Comment by den-crane** [comment]
it means replace values inherited from default profile

**Comment by TimonKK** [comment]
I have empty password tag
```xml
<password></password>
```
And if I delete this tag than I got message like your

**Comment by den-crane** [comment]
>But If I set empty password

What do you mean?


I could not reproduce
```
cat /etc/clickhouse-server/conf.d/user_test.xml
<?xml version="1.0" ?>
<yandex>
    <users>
        <test>
            <password>test</password>
            <profile>default</profile>
            <quota>default</quota>
	    <networks replace="replace">
                <ip>127.0.0.1</ip>
		<ip>::1</ip>
            </networks>
        </test>
    </users>
</yandex>
```

clickhouse-client -q 'select 1' -u test --password test
1

curl 'http://test:test@localhost:8123/?query=select%201'
1

clickhouse-client -q 'select 1' -u test --password test -h remotech
Code: 516. DB::Exception: Received from remotech:9000. DB::Exception: test: Authentication failed: password is incorrect or there is no user with such name.


curl 'http://test:test@remotech:8123/?query=select%201'
Code: 516, e.displayText() = DB::Exception: test: Authentication failed: password is incorrect or there is no user with such name (version 20.3.7.46 (official build))


The same correct behavior with empty password
```<password></password>```

**Comment by den-crane** [comment]
it could be that you corrupted settings for default user and your xml is not applied at all. So default settings works -- empty password and access from everywhere.

**Comment by TimonKK** [comment]
I mean what If I have empty password tag into users.xml:
```xml
<?xml version="1.0" ?>
<yandex>
    <users>
        <test>
            <password></password>
	    <networks replace="replace">
                <ip>127.0.0.1</ip>
		<ip>::1</ip>
            </networks>
        </test>
    </users>
</yandex>
```
and query
curl https://domain.com/?query=SELECT%20*%20FROM%20system.functions
returns data with functions list
I mean what If I have empty password tag into users.xml:
```xml
<?xml version="1.0" ?>
<yandex>
    <users>
        <test>
            <password></password>
	    <networks replace="replace">
                <ip>127.0.0.1</ip>
		<ip>::1</ip>
            </networks>
        </test>
    </users>
</yandex>
```
and query
curl https://domain.com/?query=SELECT%20*%20FROM%20system.functions
returns data with functions list

**Comment by den-crane** [comment]
Still nothing, please show all configs.

Two different users: `test` VS `default`

<users>  <test>

curl https://domain.com/?

**Comment by TimonKK** [comment]
Yes, I have error "Could not parse user" If I delete <password></password> 
It is my config.xml https://pastebin.com/gF5P9BqT with two users. And I do query
https://somedomain.com/?query=SELECT%20*%20FROM%20system.functions

 For test user the query
https://somedomain.com/?query=SELECT%20*%20FROM%20system.functions&user=test
works as expected and I got error
 

> Code: 516, e.displayText() = DB::Exception: test: Authentication failed: password is incorrect or there is no user with such name (version 20.3.7.46 (official build))

But for default user the query
https://somedomain.com/?query=SELECT%20*%20FROM%20system.functions
returns data

**Comment by den-crane** [comment]
So it's your responsibility to check that config is valid. 
If config is invalid. It's not used. Then a default settings applied. User `default` without a password and without network restrictions.

**Comment by TimonKK** [comment]
[It](https://pastebin.com/eSX3BzMz) is my correct valid users.xml and the clickhouse-server starts without errors.
This config contains:
-  empty password for default user
- section with limitation of non localhost query

and allows execute query

```sql
SELECT * FROM system.functions
```
which returns data.

**Comment by den-crane** [comment]
I could not reproduce the issue using your users.xml

Do you have nginx at the same host?
Do you have any files at /etc/clickhouse-server/conf.d/ or /etc/clickhouse-server/users.d ?

**Comment by TimonKK** [comment]
Thanks for your help. I have only one nginx. Directories /etc/clickhouse-server/conf.d/ and /etc/clickhouse-server/users.d are empty. 
I looked preprocessed /clickhouse/preprocessed_configs/users.xml - it is same like /etc/clickhouse-server/users.xml

**Comment by den-crane** [comment]
I meant does Nginx shares a host with CH or not ?

**Comment by TimonKK** [comment]
Yes, nginx and CH places at the same server

**Comment by den-crane** [comment]
>proxy_pass http://somedomain.com:8123/;

And somedomain.com = MY_EXTERNAL_IP at this host? not 127.0.0.1 ?

**Comment by TimonKK** [comment]
Yes, and I see my MY_EXTERNAL_IP in clickhouse-server.log

**Comment by den-crane** [comment]
I  configured my system CH+nginx exactly as your settings

I am getting:
```
curl 'http://host.domain/?query=select%201'
Code: 195, e.displayText() = DB::Exception: User default is not allowed to connect from address ::ffff:xxx.xxx.xxx.xxx (version 19.13.7.57 (official build))
```

**Comment by DingZhengCN** [comment]
I encountered the same situation, and I find that the owner of the /etc/clickhouse-server/users.d/default-password.xml  is **ROOT**.

I fix it by those steps:
```sudo chown clickhouse:clickhouse default-password.xml
sudo mv default-password.xml  default-password.xml.bak
sudo service clickhouse-server restart
sudo mv default-password.xml.bak  default-password.xml
sudo service clickhouse-server restart```
