### ISSUE TITLE
neighbor + LowCardinality = wrong result

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#10333]
```
SELECT
    neighbor(n, -2) AS int,
    neighbor(s, -2) AS str,
    neighbor(lcs, -2) AS lowCstr
FROM
(
    SELECT
        number % 5 AS n,
        toString(n) AS s,
        CAST(s, 'LowCardinality(String)') AS lcs
    FROM numbers(10)
)

┌─int─┬─str─┬─lowCstr─┐
│   0 │     │         │
│   0 │     │         │
│   0 │ 0   │ 0       │
│   1 │ 1   │ 1       │
│   2 │ 2   │ 2       │
│   3 │ 3   │         │
│   4 │ 4   │         │
│   0 │ 0   │ 0       │
│   1 │ 1   │ 1       │
│   2 │ 2   │ 2       │
└─────┴─────┴─────────┘
```

**Comment by shacuros** [comment]
newest version still is affected by this, as i have had to notice in some usecases lately.

There are not only missing results like in the Example by denny, but also totally different ones as well:

`
CREATE TABLE neighbor_test (
  rowNr UInt8,
  val_string String, 
  val_low LowCardinality(String)
) ENGINE=MergeTree() ORDER BY rowNr PARTITION BY tuple();

INSERT INTO neighbor_test
VALUES
(1, 'String 1', 'String 1'),
(2, 'String 1', 'String 1'),
(3, 'String 2', 'String 2');

SELECT
    rowNr,
    val_string,
    neighbor(val_string, -1) AS str_m1,
    neighbor(val_string, 1) AS str_p1,
    val_low,
    neighbor(val_low, -1) AS low_m1,
    neighbor(val_low, 1) AS low_p1

FROM 
(
    SELECT *
    FROM neighbor_test
    ORDER BY val_string ASC
)

┌─rowNr─┬─val_string─┬─str_m1───┬─str_p1───┬─val_low──┬─low_m1───┬─low_p1───┐
│     1 │ String 1   │          │ String 1 │ String 1 │          │ String 2 │
│     2 │ String 1   │ String 1 │ String 2 │ String 1 │          │ String 2 │
│     3 │ String 2   │ String 1 │          │ String 2 │ String 1 │          │
└───────┴────────────┴──────────┴──────────┴──────────┴──────────┴──────────┘



`
