### ISSUE TITLE
How to compute the difference between all successive values of a column, from first to last row?  

### ISSUE THREAD

**Issue by XavierQuiniou** [ClickHouse/ClickHouse#10334]
This issue is a continuation of : #8975
We know that  <tt>runningDifference(), neighbor()</tt> functions ,  reset their value with each data block. So, how to do when we want addressing all column content ?

Fact :
Our test table has more than 7 million rows, all including a date field, with no missing values. 

Counting number of data blocks : 
<pre>select count() from (
        select * from MY_TABLE
        order by Date 
        --In reality this has no importance in this test case
)
where ( neighbor(Date, -1 ) = toDate('0000-00-00') )
</pre>
result : 128 (expected : 1).

Adding settings <code>optimize_read_in_order=0</code> at the end of request, only slightly reduces the result 

 Measurement of the block size variability 
<pre>select DISTINCT(bs) from (
    select * , blockSize() as bs
    from (
        select Date from MY_TABLE
        order by Date
    ) 
)</pre>

result : 25 distinct sizes found- Variability is excessively high 

![block-size-variability](https://user-images.githubusercontent.com/58552786/79579280-aac36200-80c7-11ea-94dd-b6481023bcbc.png)
How to get around the problem  ?

**Comment by den-crane** [comment]
using Arrays?
```

SELECT
    n,
    nn
FROM
(
    SELECT
        groupArray(n) AS na,
        arrayMap(y -> y, arrayPushFront(arraySlice(na, 1, -1), na[1])) AS na1
    FROM
    (
        SELECT number AS n
        FROM numbers(10)
        ORDER BY n ASC
    )
)
ARRAY JOIN
    na AS n,
    na1 AS nn

┌─n─┬─nn─┐
│ 0 │  0 │
│ 1 │  0 │
│ 2 │  1 │
│ 3 │  2 │
│ 4 │  3 │
│ 5 │  4 │
│ 6 │  5 │
│ 7 │  6 │
│ 8 │  7 │
│ 9 │  8 │
└───┴────┘
```

**Comment by XavierQuiniou** [comment]
Thanks,
One more, it’s great.
Yes, I had already found a solution by using arrays.
Principle of code to compute diff:
<pre>Select …
  groupArray(Date)  as Date_arr,
  arrayEnumerate(Date_arr)  as indexes,
  groupArray(Qty)  as Qty_arr,  
  arrayMap( i -> Qty _arr[i] - Qty_arr[i-1], indexes) as Qty_arr,

 … two other computations of this kind …
array join ….</pre>
We have observed a high memory consumption : 
<tt>duration : 22.705 sec. memory (pic) : 8.82 GiB.  read lines : 7 775 685.</tt>

P.S. About your example : <tt>arrayMap()</tt>  is really useful ?

**Comment by den-crane** [comment]
Obviously for millions rows pivoted into Array it will require a lot of memory.
I was trying to avoid arrayEnumerate and do not create additional array but I am not sure that it helped because of arraySlice.
