### ISSUE TITLE
how to change ReplicatedReplacingMergeTree to ReplicatedSummingMergeTree

### ISSUE THREAD

**Issue by imkouga** [ClickHouse/ClickHouse#10332]
how to change ReplicatedReplacingMergeTree to ReplicatedSummingMergeTree

**Comment by den-crane** [comment]
The official way is to `create a new table`, `insert into new select from old`, `rename old to old_old , new to old`

**Comment by imkouga** [comment]
@den-crane  thank you . but i need to change the engine keeping on serving .

**Comment by den-crane** [comment]
You can do it with a 2 seconds downtime, using Materialized View.

**Comment by alexey-milovidov** [comment]
It is also possible to change it with manually editing metadata files in filesystem and in ZooKeeper. But it's not recommended because it will require knowledge of ClickHouse internals and extra care.
