### ISSUE TITLE
neighbor function unexpected result

### ISSUE THREAD

**Issue by zplzpl** [ClickHouse/ClickHouse#10352]
**Describe the unexpected behaviour**

* table has 20Mil rows. 2 days.
* product_id = 2102982256 has 2 rows, but prev value always is 0. 

```
SELECT 
    *, 
    neighbor(sold_cnt, -1) AS prev_sold_cnt
FROM 
(
    SELECT 
        snapshot_time, 
        product_id, 
        sold_cnt
    FROM fact_product
    WHERE product_id = 2102982256
    ORDER BY snapshot_time ASC
)

┌─snapshot_time─┬─product_id─┬─sold_cnt─┬─prev_sold_cnt─┐
│    2020-02-11 │ 2102982256 │   179819 │             0 │
└───────────────┴────────────┴──────────┴───────────────┘
┌─snapshot_time─┬─product_id─┬─sold_cnt─┬─prev_sold_cnt─┐
│    2020-02-12 │ 2102982256 │   180663 │             0 │
└───────────────┴────────────┴──────────┴───────────────┘
```

prev_sold_cnt is not working....
how to locate this problem?

* Which ClickHouse server version to use
os : win10 WSL
clickhouse version 20.3.4.10

* `CREATE TABLE` statements for all tables involved

```
create table fact_product
(
    snapshot_time     Date,
    product_id        UInt64,
    sold_cnt          UInt32
)
    engine = MergeTree
        PARTITION BY snapshot_time
        PRIMARY KEY (product_id, snapshot_time)
        ORDER BY (product_id, snapshot_time)
        TTL snapshot_time + toIntervalMonth(12)
        SETTINGS index_granularity = 8192;
```

**Comment by nauu** [comment]
Maybe it was caused by #8545.

**Comment by den-crane** [comment]
Because the subquery  returned 2 blocks

try

SELECT 
        snapshot_time, 
        product_id, 
        sold_cnt
    FROM fact_product
    WHERE product_id = 2102982256
    ORDER BY snapshot_time ASC **setttings optimize_read_in_order=0**

or

 **ORDER BY snapshot_time ASC, product_id+0**

https://github.com/ClickHouse/ClickHouse/issues/8975#issuecomment-582000077

**Comment by zplzpl** [comment]
1. SETTINGS optimize_read_in_order = 0

```
SELECT 
    *, 
    neighbor(sold_cnt, -1) AS prev_sold_cnt
FROM 
(
    SELECT 
        snapshot_time, 
        product_id, 
        sold_cnt
    FROM fact_product_sn
    WHERE product_id = 2102982256
    ORDER BY snapshot_time ASC
    SETTINGS optimize_read_in_order = 0
)

┌─snapshot_time─┬─product_id─┬─sold_cnt─┬─prev_sold_cnt─┐
│    2020-02-11 │ 2102982256 │   179819 │             0 │
└───────────────┴────────────┴──────────┴───────────────┘
┌─snapshot_time─┬─product_id─┬─sold_cnt─┬─prev_sold_cnt─┐
│    2020-02-12 │ 2102982256 │   180663 │             0 │
└───────────────┴────────────┴──────────┴───────────────┘
```

2.ORDER BY snapshot_time ASC, product_id+0

```
SELECT 
    *, 
    neighbor(sold_cnt, -1) AS prev_sold_cnt
FROM 
(
    SELECT 
        snapshot_time, 
        product_id, 
        sold_cnt
    FROM fact_product_sn
    WHERE product_id = 2102982256
    ORDER BY 
        snapshot_time ASC, 
        product_id + 0 ASC
)

┌─snapshot_time─┬─product_id─┬─sold_cnt─┬─prev_sold_cnt─┐
│    2020-02-11 │ 2102982256 │   179819 │             0 │
└───────────────┴────────────┴──────────┴───────────────┘
┌─snapshot_time─┬─product_id─┬─sold_cnt─┬─prev_sold_cnt─┐
│    2020-02-12 │ 2102982256 │   180663 │             0 │
└───────────────┴────────────┴──────────┴───────────────┘
```

3.ORDER BY toString(snapshot_time) ASC

```
SELECT 
    *, 
    neighbor(sold_cnt, -1) AS prev_sold_cnt
FROM 
(
    SELECT 
        snapshot_time, 
        product_id, 
        sold_cnt
    FROM fact_product_sn
    WHERE product_id = 2102982256
    ORDER BY toString(snapshot_time) ASC
)

┌─snapshot_time─┬─product_id─┬─sold_cnt─┬─prev_sold_cnt─┐
│    2020-02-11 │ 2102982256 │   179819 │             0 │
└───────────────┴────────────┴──────────┴───────────────┘
┌─snapshot_time─┬─product_id─┬─sold_cnt─┬─prev_sold_cnt─┐
│    2020-02-12 │ 2102982256 │   180663 │             0 │
└───────────────┴────────────┴──────────┴───────────────┘

```

**Comment by den-crane** [comment]
WA:
```
insert into fact_product values('2020-02-11',2102982256,179819), ('2020-02-12',2102982256,180663 )

SELECT
    *,
    neighbor(sold_cnt, -1) AS prev_sold_cnt
FROM
(
    SELECT *
    FROM
    (
        SELECT
            snapshot_time,
            product_id,
            sold_cnt
        FROM fact_product
        WHERE product_id = 2102982256
        ORDER BY snapshot_time ASC
    )
    ORDER BY snapshot_time ASC
)

┌─snapshot_time─┬─product_id─┬─sold_cnt─┬─prev_sold_cnt─┐
│    2020-02-11 │ 2102982256 │   179819 │             0 │
│    2020-02-12 │ 2102982256 │   180663 │        179819 │
└───────────────┴────────────┴──────────┴───────────────┘
```

**Comment by windylcx** [comment]
> WA:
> 
> ```
> insert into fact_product values('2020-02-11',2102982256,179819), ('2020-02-12',2102982256,180663 )
> 
> SELECT
>     *,
>     neighbor(sold_cnt, -1) AS prev_sold_cnt
> FROM
> (
>     SELECT *
>     FROM
>     (
>         SELECT
>             snapshot_time,
>             product_id,
>             sold_cnt
>         FROM fact_product
>         WHERE product_id = 2102982256
>         ORDER BY snapshot_time ASC
>     )
>     ORDER BY snapshot_time ASC
> )
> 
> ┌─snapshot_time─┬─product_id─┬─sold_cnt─┬─prev_sold_cnt─┐
> │    2020-02-11 │ 2102982256 │   179819 │             0 │
> │    2020-02-12 │ 2102982256 │   180663 │        179819 │
> └───────────────┴────────────┴──────────┴───────────────┘
> ```

it works,thx

**Comment by azubkokshe** [comment]
> WA:
> 
> ```
> insert into fact_product values('2020-02-11',2102982256,179819), ('2020-02-12',2102982256,180663 )
> 
> SELECT
>     *,
>     neighbor(sold_cnt, -1) AS prev_sold_cnt
> FROM
> (
>     SELECT *
>     FROM
>     (
>         SELECT
>             snapshot_time,
>             product_id,
>             sold_cnt
>         FROM fact_product
>         WHERE product_id = 2102982256
>         ORDER BY snapshot_time ASC
>     )
>     ORDER BY snapshot_time ASC
> )
> 
> ┌─snapshot_time─┬─product_id─┬─sold_cnt─┬─prev_sold_cnt─┐
> │    2020-02-11 │ 2102982256 │   179819 │             0 │
> │    2020-02-12 │ 2102982256 │   180663 │        179819 │
> └───────────────┴────────────┴──────────┴───────────────┘
> ```

why does it work ???

**Comment by theprometeus** [comment]
I'm experiencing this exact issue right now.
`neighbor()` sometimes returns NULL and sometimes returns the desired value.

An example with the same query and same values below, by just executing the query multiple times:
![image](https://user-images.githubusercontent.com/3390576/176978047-99301d5b-2c41-4d0f-8962-cdff33816756.png)
![image](https://user-images.githubusercontent.com/3390576/176978054-3bbf1f4d-cc59-4483-8731-eb74907d5bda.png)
![image](https://user-images.githubusercontent.com/3390576/176978071-ac3be727-5916-48ca-a5fa-3d22a8faffc4.png)

**Comment by den-crane** [comment]
@theprometeus do not use pictures please. They are unreadable.
This is expected behaviour. Use window functions instead of neighbor.
