### ISSUE TITLE
Add netloc function for url

### ISSUE THREAD

**Issue by imfht** [ClickHouse/ClickHouse#10357]
**Use case**
I have some url with different port like `http://a.com:8080/`,`http://a.com:8081/`. and I want get `a.com:8080` `a.com:8081`.

**Describe the solution you'd like**
select netloc('http://a.com:8080') -> a.com:8080
select netloc('http://b.com:8080') -> a.com:8081

**Describe alternatives you've considered**
Look like this is no good way to do is now

**Additional context**
python urllib moule support this:
![image](https://user-images.githubusercontent.com/15059493/79688652-3c76cf00-8282-11ea-81ec-c3111dbb6da4.png)

**Comment by alexey-milovidov** [comment]
Maybe @YiuRULE is interested in this task?

**Comment by YiuRULE** [comment]
@alexey-milovidov Yep, I could work on it, I cannot work on it right now at the moment, but when I have some free time, I can take a look :)

**Comment by fibersel** [comment]
Can i take this task if @YiuRULE has not started it yet?

**Comment by alexey-milovidov** [comment]
@fibersel Yes, it's yours!

**Comment by YiuRULE** [comment]
@fibersel Did you have time to work on it yet ? I have a bit of free time now, but I will let you the task if you are already on it :)

**Comment by alexey-milovidov** [comment]
@YiuRULE I think, it's perfectly Ok to grab this task :)

**Comment by fibersel** [comment]
@YiuRULE yes, take it, I have overestimated my free time.
