### ISSUE TITLE
Does topKWeighted take UInt8 or any integer types for the weight param?

### ISSUE THREAD

**Issue by knoguchi** [ClickHouse/ClickHouse#10360]
Does `topKWeighted(N)(x, weight)` take UInt8 or any integer types for the `weight` parameter?

According to the [document](https://clickhouse.tech/docs/en/sql_reference/aggregate_functions/reference/#topkweighted
) the weight parameter has to be UInt8 but the example uses larger numbers than 256.

I tested with UInt64.  It was accepted without errors, and it seemed to work fine.   As far as I've read the code [it checks the type by `isInteger`](https://github.com/ClickHouse/ClickHouse/blob/master/src/AggregateFunctions/AggregateFunctionTopK.cpp#L69-L70), and the type is consistent through out the other part of the code.

The counter implementation is uint64, and the weights are just summed up in the counter.  Hence there is no reason to limit the type to UInt8, I believe.  (of course the counter can't exceed uint64.max though)

Please let me know if it's an error in the document, or the param has to be UInt8 but the code is not strictly checking the type.

**Comment by alexey-milovidov** [comment]
Documentation is wrong.

CC @BayoNet

**Comment by alexey-milovidov** [comment]
@BayoNet ?

**Comment by BayoNet** [comment]
I've missed this message somewhere. I'll do.

**Comment by robot-clickhouse** [comment]
@knoguchi, do you have any further questions?

**Comment by adevyatova** [comment]
Completed: https://clickhouse.tech/docs/en/sql-reference/aggregate-functions/reference/topkweighted/
