### ISSUE TITLE
Some merges may stuck

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#10368]
This bug is discovered on Yandex.Metrica servers.

If there is assigned merge but some parts in between of the range of parts to merge get lost on all replicas, the merge cannot proceed and the following messages will be printed in log:

```
Executing log entry to merge parts ...
Don't have all parts for merge ...; will try to fetch it instead
No active replica has part ...
Checking part ...
Checking if anyone has a part covering ...
Found parts with the same min block and with the same max block as the missing part ... Hoping that it will eventually appear as a result of a merge.
```

And in system.replication_log you will see the following entries:
```
Not executing log entry for part ... because it is covered by part ... that is currently executing
No active replica has part ... or covering part
```

Actually this logic exists as a safety measure when automated action is not possible: https://github.com/ClickHouse/ClickHouse/pull/1251

And it's unclear how to fix it in code.

**Comment by alexey-milovidov** [comment]
Maybe simply check all parts participating in merge?

**Comment by alexey-milovidov** [comment]
How to fix it manually:

1. `SELECT * FROM system.replication_queue WHERE create_time < now() - INTERVAL 1 DAY AND type = 'MERGE_PARTS' AND last_exception LIKE '%No active replica has part%' \G`
2. `SELECT replica_path || '/queue/' || node_name FROM system.replication_queue JOIN system.replicas USING (database, table) WHERE create_time < now() - INTERVAL 1 DAY AND type = 'MERGE_PARTS' AND last_exception LIKE '%No active replica has part%'`
3. Delete these nodes from ZooKeeper.
4. `SYSTEM RESTART REPLICAS`

Do all these steps on all replicas.

**Comment by den-crane** [comment]
>will try to fetch it instead

a) Some counter fetch_try and give up after 10 (100 ( configurable)) tries?
b) Without automation. Alter table drop part xxx force. optimize table partition yyyy force

**Comment by nvartolomei** [comment]
related #2755

**Comment by amosbird** [comment]
I've encountered similar issue twice. In both cases it happened when all replicas were restarting while there were many active inserts. Then some table in some shard failed to merge anymore with bloated replication_queue (> 1000 entries)

**Comment by nvartolomei** [comment]
Related #25168 (posting here to have cross-references between these related issues)

**Comment by intfish123** [comment]
if you use clickhouse-keeper, can do like this: https://github.com/ClickHouse/ClickHouse/issues/53143#issuecomment-2569032959
