### ISSUE TITLE
Error compiling latest source code on Docker environment

### ISSUE THREAD

**Issue by marising** [ClickHouse/ClickHouse#10392]
I want build clickhouse on docker environment，
docker's mage come from https://hub.docker.com/r/yandex/clickhouse-server/

**Operating system**
Ubuntu 18.04.4 LTS of docker 

**Cmake version**
cmake version 3.10.2

**Ninja version**
1.8.2

**Compiler name and version**
g++ --version
g++ (Ubuntu 9.3.0-10ubuntu2~18.04) 9.3.0
gcc --version
gcc (Ubuntu 9.3.0-10ubuntu2~18.04) 9.3.0

**Full cmake and/or ninja output**
root@1b9c2a48fdb4:/ClickHouse/build# ninja -j1
[1/4039] Building CXX object contrib/capnproto-cmake/CMakeFiles/capnpc.dir/__/capnproto/c++/src/capnp/compiler/type-id.c++.o
FAILED: contrib/capnproto-cmake/CMakeFiles/capnpc.dir/__/capnproto/c++/src/capnp/compiler/type-id.c++.o
/usr/bin/g++-9   -isystem ../contrib/libunwind/include -isystem ../contrib/capnproto/c++/src -isystem ../contrib/libc-headers/x86_64-linux-gnu -isystem ../contrib/libc-headers -fdiagnostics-color=always -std=c++2a -fsized-deallocation  -pipe -msse4.1 -msse4.2 -mpopcnt   -Wall  -Wnon-virtual-dtor -Wno-array-bounds -Werror -stdlib=libc++ -O2 -g -DNDEBUG -O3  -fno-pie   -D OS_LINUX -Wno-non-virtual-dtor -Wno-sign-compare -Wno-strict-aliasing -Wno-maybe-uninitialized -Wno-deprecated-declarations -Wno-class-memaccess -std=c++1z -MD -MT contrib/capnproto-cmake/CMakeFiles/capnpc.dir/__/capnproto/c++/src/capnp/compiler/type-id.c++.o -MF contrib/capnproto-cmake/CMakeFiles/capnpc.dir/__/capnproto/c++/src/capnp/compiler/type-id.c++.o.d -o contrib/capnproto-cmake/CMakeFiles/capnpc.dir/__/capnproto/c++/src/capnp/compiler/type-id.c++.o -c ../contrib/capnproto/c++/src/capnp/compiler/type-id.c++
g++-9: error: unrecognized command line option ‘-stdlib=libc++’
ninja: build stopped: subcommand failed.

**Comment by alexey-milovidov** [comment]
You can compile in Docker simply by running `make` inside `docker/builder` directory.

**Comment by marising** [comment]
I found the cause of the problem, because the network speed is not very good, contrib /libcxx is not updated completely, I delete the empty directory, and then use git submodule update --init --recursive

**Comment by alexey-milovidov** [comment]
Ok, great.
