### ISSUE TITLE
How can I skip the code: 117. DB error::Exception: Expected end of line when importing from CSV?

### ISSUE THREAD

**Issue by bimkos** [ClickHouse/ClickHouse#10419]
I import a lot of data via CSV, but some rows may not have a separator, how do I skip them? If you can, please write a command. The command I'm using now:

`cat data.csv | clickhouse-client --query="INSERT INTO db.database_test (product,id,date,type) SELECT col1, col2, '2020-01-04' AS date,'cheese' AS type FROM input('col1 String, col2 String') FORMAT CSV" --format_csv_delimiter=":" --compression 0 --format_csv_allow_double_quotes=0 --format_csv_allow_single_quotes=0`

I get this error message:

`Code: 117. DB::Exception: Expected end of line`

**Comment by alexey-milovidov** [comment]
Look at the `input_format_allow_errors_num`, `input_format_allow_errors_ratio` settings.

**Comment by bimkos** [comment]
This command

`cat data.csv | clickhouse-client --query="INSERT INTO db.database_test (product,id,date,type) SELECT col1, col2, '2020-01-04' AS date,'cheese' AS type FROM input('col1 String, col2 String') FORMAT CSV" --format_csv_delimiter=":" --compression 0 --format_csv_allow_double_quotes=0 --format_csv_allow_single_quotes=0 --input_format_allow_errors_num=10 --input_format_allow_errors_ratio=0.1`

But get 
`
Code: 117. DB::Exception: Expected end of line`

**Comment by filimonov** [comment]
We can't help you unless you provide minimal reproducable sample (file with sample data in your case and ClickHouse version)
