### ISSUE TITLE
Suspected memory leak in  20.3.5.21

### ISSUE THREAD

**Issue by gglinux** [ClickHouse/ClickHouse#10436]
Memory usage, rising slowly all the time. 
![image](https://user-images.githubusercontent.com/7273957/79967479-797cd480-84c1-11ea-9264-23c926f6810e.png)

**How to reproduce**
* Which ClickHouse server version to use:  20.3.5.21
* Which interface to use, if matters: HTTP and clickhouse-client
* Non-default settings, if any: http port,tcp port,timezone

**Comment by filimonov** [comment]
Do you use ALTER UPDATE / ALTER DELETE? 

(There is a known memory leak in your version, please update - see #9850)

**Comment by gglinux** [comment]
> Do you use ALTER UPDATE / ALTER DELETE?
> 
> (There is a known memory leak in your version, please update to the latest release. see #9850 #9873)

Yes, frequently used

**Comment by gglinux** [comment]
After 20 hours, the clickhouse crashed. Also, there is no valid error log

**Comment by gglinux** [comment]
DB::ExpressionBlockInputStream::readImpl, Get this, from core dump.

![image](https://user-images.githubusercontent.com/7273957/80170458-8f51dd00-861a-11ea-9001-d01afacc23df.png)

**Comment by filimonov** [comment]
> And my version 20.3.5.21, is the latest release.

It is NOT. There were 3 bugfix releases since that (look on their third number in version) 
https://github.com/ClickHouse/ClickHouse/releases/tag/v20.3.8.53-lts

The log fragments you send are not useful. 

Please update.

**Comment by gglinux** [comment]
Thank you. I'll try v20.3.8.53-lts.

In addition, which version is the most stable between tls and stable.

**Comment by filimonov** [comment]
Any update here?

**Comment by gglinux** [comment]
Thanks, It didn't happen in v20.3.8.53-lts
