### ISSUE TITLE
Ordering with group by with totals

### ISSUE THREAD

**Issue by pic-Nick** [ClickHouse/ClickHouse#10432]
**Describe the unexpected behaviour**
After using GROUP BY WITH TOTALS new row with totals appears and trying to order the result set does not affect that new row. It always appears at the end.

**How to reproduce**
```
select * from (
  select k, sum(v) from (
    select '1' as k, 5 as v
    union all
    select '2', 5
    union all
    select '1', 3
    union all
    select '4', 9
  )
  group by k with totals
)
order by k
```

**Expected behavior**
I want to display totals row as first row. How to do this?

**Comment by alexey-milovidov** [comment]
It's not possible. Totals are represented as a separate part of the resultset and this is the intended behaviour. When you use formats like Pretty, TabSeparated, JSON... you can see that this part of result is semantically separated.

**Comment by alexey-milovidov** [comment]
But you can emulate the desired behaviour with `group by arrayJoin([k, 0])`

**Comment by alexey-milovidov** [comment]
Also you can use `GROUP BY k WITH ROLLUP` (this is probably the best variant)

**Comment by alexey-milovidov** [comment]
This is exactly what you need:

```
SELECT *
FROM 
(
    SELECT 
        k, 
        sum(v)
    FROM 
    (
        SELECT 
            '1' AS k, 
            5 AS v
        UNION ALL
        SELECT 
            '2', 
            5
        UNION ALL
        SELECT 
            '1', 
            3
        UNION ALL
        SELECT 
            '4', 
            9
    )
    GROUP BY k
        WITH ROLLUP
)
ORDER BY k ASC
```

**Comment by pic-Nick** [comment]
Thank you! Did find it in docs.
