### ISSUE TITLE
Missing rows and duplicated rows when insert into buffer table

### ISSUE THREAD

**Issue by hydra-yl** [ClickHouse/ClickHouse#10455]
**Missing rows and duplicated rows when insert into buffer table**

**How to reproduce**
1. Create local table on 12 servers
`CREATE TABLE some_table_local(uuid String) ENGINE = MergeTree PRIMARY KEY uuid ORDER BY uuid SETTINGS index_granularity = 8192
`
2. Create distributed table
`CREATE TABLE some_table_all(uuid String) ENGINE = Distributed(my_cluster, dbname, some_table_local, rand())
`
3. Create buffer table which is associated to distributed table
`CREATE TABLE some_table_all_buffer(uuid String)) ENGINE = Buffer(dbname, some_table_all, 16, 10, 10000, 1000000, 10000000, 100000000)
`
4. Batch insert into buffer table through HTTP interface
Each client randomly connected one of the twelve servers and insert into buffer table. There are no overlap between each client's dataset(60 clients in total). Verified there were no repeated insertion.

5. When insertion is over, check duplicated rows and missing rows 

- Result1: select count(uuid) from some_table_all;
- Result2: select count(distinct(uuid)) from some_table_all;
- Result3: actual rows. e.g. wc -l raw.data

Duplicate rows: Result1 != Result2
Missing rows: Result3 > Result2

* Which ClickHouse server version to use
19.13.3.26

* Which interface to use, if matters
HTTP interface

**Expected behavior**
Result1 == Result2 == Result3

**Comment by den-crane** [comment]
Why do you use Buffer over Distributed ? But not over MergeTree?

**Comment by hydra-yl** [comment]
@den-crane Thanks for the reply. 

Actually, the reproduce steps are not identical to our production usage: a java application consume message from kafka and do a bit of processing then insert into clickhouse. The main purpose to use buffer table is to accelerate insertion speed. The goal is to insert 5billion rows in one hour on 12 nodes clsuter. 

Since the reproduce steps are more like a stripp-down description of the production environment envisioned by us, it's not helpful to solve the problem. We will first try distriubted -> Buffer -> MergeTree as opposed to the current method then post back.

**Comment by hydra-yl** [comment]
@den-crane After change to distriubted -> Buffer -> MergeTree structure, problem is solved: No missing rows or/and duplicate rows. Maybe Clickhouse should not allow buffer over distributed table

**Comment by den-crane** [comment]
The root cause still unclear. It needs a reproduction.

**Comment by mrAndersen** [comment]
Seems like a have the same issue. Consider Following:

1) Create MergeTree table on 4 shards track_shard
2) Create Distributed table on master server track_main
3) Create MergeTree table on master server track_old

track_old has ~ approx 5 Bil rows, i am trying to load the data to track_main and respectively split the data, track_main is created with rand() sharding_key key which is okay for my needs.

If i am doing something like ```insert into track_main select from track_old``` i am getting about 1-2% of rows missing from the final table track_main if i compare them by dates. If i directly insert into track_shard - i am getting correct number of rows.
