### ISSUE TITLE
How to insert more records or bytes via http api

### ISSUE THREAD

**Issue by zhouxiujue** [ClickHouse/ClickHouse#10450]
I have a table with  26 columns.
I used http api to insert records. 
But when I insert more than about 50 records,it failed. And it seems limited 11800 bytes.
Is it a bytes count limited about the query of insert ? And how to resolve the limit? 
I submit the rquest with java, or postman.

POST method:
http://192.168.1.23:8123?password=123456&query=INSERT into default.is_bu_log values
(1111,'2020040812','2020-04-08 12:00:00','HK232343','8060','3c2a','9afb','18ca','a2a6','03e8','270e','123124','5f5b','1','1111',1111,11111,'r476568654','6r74856fhdjf','20200408103240291','2019-12-04 00:08:01','1','f444','lw01lw02','12'),(...... other 50 records)

table:
CREATE TABLE default.is_bu_log (
`num` Int64,
 `date` String,
 `paramDate` datetime,
 `downID` String,
 `conName` String,
 `coopd` String,
 `accId` String,
 `secId` String,
 `speCode` String,
 `speName` String,
 `busId` String,
 `servictCode` String,
 `proName` String,
 `opeType` String,
 `opeTypeDesc` String,
 `price` Float32,
 `salePrice` Float32,
 `reqRefId` String,
 `responseRefId` String,
 `requTime` String,
 `respoTime` datetime,
 `retuateCode` String,
 `returteMsg` String,
 `fielumnCode` String,
 `fielumnValue` String,
 `createTime` datetime DEFAULT now()
) ENGINE = MergeTree() PARTITION BY toYYYYMM(createTime) ORDER BY createTime SETTINGS index_granularity = 8192

Thank you!

**Comment by den-crane** [comment]
>&query=INSERT into default.is_bu_log values (1111,'2020040812','2020-04-08 

Seems that you send your data in URL. URL is obviously limited and you don't use POST.

Check https://clickhouse.tech/docs/en/interfaces/http/

Insert and values in POST body
```
echo 'INSERT INTO t VALUES (1),(2),(3)' | curl 'http://localhost:8123/' --data-binary @-
```

Values in POST body
```
echo '(4),(5),(6)' | curl 'http://localhost:8123/?query=INSERT%20INTO%20t%20VALUES' --data-binary @-
```

**Comment by zhouxiujue** [comment]
Yes, I sent my data in URL.  Maybe it is the reason.
But in java, I can't send the insert data in body, do you know why?
I hava wrote another issue at #10475.
