### ISSUE TITLE
Can Dictionary refresh trigger Materialized View update?

### ISSUE THREAD

**Issue by rsurgiewicz** [ClickHouse/ClickHouse#10454]
Can materialized view be "triggered"/"recalculated" by source table that is an External Dictionary based (table Engine=Dictionary(...)) ?

In other words:
Can refresh/end of lifetime be a trigger for MV update?
Seems not to work in my case. 

If not any ideas how to automate the MV update/calculation that use External Dictionary as a source?
Thanks!

**Comment by qoega** [comment]
1) I guess not.
2) You can try to do something like source table join with this dictionary. And store last updated version in this source table.
``` sql
INSERT INTO local_table 
key, dictGet('dict_name', 'value', key) as value, dictGet('dict_name', 'version', key) as version
(
   SELECT key, max(version)
   FROM local_table
   HAVING dictGet('dict_name', 'version', key) > max(version)
)
```

**Comment by rsurgiewicz** [comment]
Thanks, that's an unfortunate storing big dict as a mv would be a performance impact.

Is it possible to force/schedule mv update manually anyhow?

**Comment by den-crane** [comment]
> Is it possible to force/schedule mv update manually anyhow?

No, it's not possible. 
Try Live View https://www.altinity.com/blog/tag/Live+Views
