### ISSUE TITLE
Memory issue when importing Parquet data with S3 table function

### ISSUE THREAD

**Issue by brenoarosa** [ClickHouse/ClickHouse#10461]
Hello,
I'm trying to import parquet files from a S3 datalake into a Clickhouse MergeTree table.
The total size of the compressed parquet files is around 20GB distributed between ~200 files.
I'm running Clickhouse version 20.1.2.4 on a server with 32GB.
Since this version don't support wildcard with the S3 function I'm using a script like the following:
```sql
SET max_memory_usage=0;
INSERT INTO my_table SELECT * FROM s3('http://s3.amazonaws.com/bucket/path/part-00000-057cd7c2-2958-436f-864d-c32cef4fefea-c000.snappy.parquet', XXXXXX, YYYYYY, 'Parquet', 'id Int64, ...');
INSERT INTO my_table SELECT * FROM s3('http://s3.amazonaws.com/bucket/path/part-00001-057cd7c2-2958-436f-864d-c32cef4fefea-c000.snappy.parquet', XXXXXX, YYYYYY, 'Parquet', 'id Int64, ...');
INSERT INTO my_table SELECT * FROM s3('http://s3.amazonaws.com/bucket/path/part-00002-057cd7c2-2958-436f-864d-c32cef4fefea-c000.snappy.parquet', XXXXXX, YYYYYY, 'Parquet', 'id Int64, ...');
...
```
It easily reaches the default query memory limit, so the max_memory_usage needs to be raised/removed.
Most of the time it runs until it fills all the memory and get OOM killed and in fewer occasions it runs successfully.
The memory usage follows this sawtooth pattern:
![Screenshot from 2020-04-17 15-59-09](https://user-images.githubusercontent.com/6242862/80119467-20b04900-8560-11ea-9117-319eff553532.png)

I tried to use the wildcard with Clickhouse version 20.3.7.46 but it is worse than this current approach, the memory usage ramps up until the OOM, like if it was trying to load all files into RAM.

Are there any suggestion to improve this? Any way to force this flush to disk to free some memory between files?

Thanks in advance.

**Comment by den-crane** [comment]
SET max_threads=1, max_insert_block_size=65536, max_insert_block_size=65536;

How many columns in your table?

**Comment by brenoarosa** [comment]
Thanks for the suggestion, I'm trying it right now.

The table has around 40 columns, which 2 are partition columns and other 2 are sorting columns.
There are around 900M rows in total.

**Comment by alexey-milovidov** [comment]
It happens because ParquetReader copies all file content in memory if file is not seekable.
The same happens for ORC reader (but unconditionally).

**Comment by alexey-milovidov** [comment]
Maybe we can implement `arrow::io::RandomAccessFile` from our ReadBuffer if Arrow library can only seek forward when reading Parquet or ORC.

@oandrew @proller @wesm

**Comment by wesm** [comment]
You might be interested to take a closer look at the IO read coalescing work that has been happening for Parquet files lately specifically to address S3 use cases (note we also have bindings to the AWS C++ SDK in the core Arrow platform).

https://github.com/apache/arrow/pull/6744

I haven't looked at Clickhouse's bridge to libparquet but in general a tighter integration with the IO abstractions would enable you to tune the settings to achieve good performance.

**Comment by oandrew** [comment]
There is another issue -  aws s3 sdk  reads the entire file into memory  before returning it as an  `std::istream`. 
So for S3 + Parquet each file is loaded into memory twice.

https://github.com/ClickHouse-Extras/aws-sdk-cpp/blob/45dd8552d3c492defca79d2720bcc809e35654da/aws-cpp-sdk-core/source/http/curl/CurlHttpClient.cpp#L187
https://github.com/ClickHouse-Extras/aws-sdk-cpp/blob/45dd8552d3c492defca79d2720bcc809e35654da/aws-cpp-sdk-core/source/utils/stream/ResponseStream.cpp#L19-L24

**Comment by wesm** [comment]
You might be interested in our C++ filesystem wrapper for the SDK which implements seek, range reads, and other APIs required for Parquet files

https://github.com/apache/arrow/blob/master/cpp/src/arrow/filesystem/s3fs.cc

**Comment by brenoarosa** [comment]
Hi,
I'm giving some updates since there were relevant merges in the most recent version (20.5.2.7).
Since them my table raised from 900M rows to 2200M rows, its size as compacted parquet files raised from 20GB to 30GB, still split between 200 files.
I'm running this in the same server with 8 cores and 32GB.

Even with the increase in size I was able to the table more reliably than before.
Here is the memory consumption while importing with the following script:
```
SET max_memory_usage=0;
INSERT INTO my_table SELECT * FROM s3('http://s3.amazonaws.com/bucket/path/part-00000-057cd7c2-2958-436f-864d-c32cef4fefea-c000.snappy.parquet', XXXXXX, YYYYYY, 'Parquet', 'id Int64, ...');
INSERT INTO my_table SELECT * FROM s3('http://s3.amazonaws.com/bucket/path/part-00001-057cd7c2-2958-436f-864d-c32cef4fefea-c000.snappy.parquet', XXXXXX, YYYYYY, 'Parquet', 'id Int64, ...');
INSERT INTO my_table SELECT * FROM s3('http://s3.amazonaws.com/bucket/path/part-00002-057cd7c2-2958-436f-864d-c32cef4fefea-c000.snappy.parquet', XXXXXX, YYYYYY, 'Parquet', 'id Int64, ...');
...
```
![Screenshot from 2020-07-06 15-28-36](https://user-images.githubusercontent.com/6242862/86629261-86c63d00-bfa1-11ea-9be7-6af4f71f5a23.png)

Importing with wildcard as follows still ramps up the memory until OOM as can be seen bellow.
```
SET max_memory_usage=0;
INSERT INTO my_table SELECT * FROM s3('http://s3.amazonaws.com/bucket/path/*.snappy.parquet', XXXXXX, YYYYYY, 'Parquet', 'id Int64, ...');
```
![Screenshot from 2020-07-06 15-37-36](https://user-images.githubusercontent.com/6242862/86629645-1a980900-bfa2-11ea-8aac-bb6e5a80c422.png)

**Comment by alexey-milovidov** [comment]
https://github.com/ClickHouse/ClickHouse/pull/20128#issuecomment-932892698

**Comment by alexey-milovidov** [comment]
Parquet format has metadata at end of file. It requires either seeking (range requests) or buffering to read.

https://parquet.apache.org/documentation/latest/

PS. This website looks almost abandoned, maybe there is more recent doc.

**Comment by alexey-milovidov** [comment]
The culprit:

ArrowBufferedStreams.cpp:
```
std::shared_ptr<arrow::io::RandomAccessFile> asArrowFile(ReadBuffer & in)
{
    if (auto * fd_in = dynamic_cast<ReadBufferFromFileDescriptor *>(&in))
    {
        struct stat stat;
        auto res = ::fstat(fd_in->getFD(), &stat);
        // if fd is a regular file i.e. not stdin
        if (res == 0 && S_ISREG(stat.st_mode))
            return std::make_shared<RandomAccessFileFromSeekableReadBuffer>(*fd_in, stat.st_size);
    }

    // fallback to loading the entire file in memory
    std::string file_data;
    {
        WriteBufferFromString file_buffer(file_data);
        copyData(in, file_buffer);
    }

    return std::make_shared<arrow::io::BufferReader>(arrow::Buffer::FromString(std::move(file_data)));
}
```
