### ISSUE TITLE
Why user defined http handlers not detected?

### ISSUE THREAD

**Issue by rsurgiewicz** [ClickHouse/ClickHouse#10464]
Hello,

I'm trying to setup a simple HTTP handler according to the docs:
https://clickhouse.tech/docs/en/interfaces/http/#predefined_http_interface

On the bottom of config.xml i placed
`<http_handlers>
  <predefine_query_handler>
      <url>/metrics</url>
        <method>GET</method>
        <queries>
            <query>SELECT 1;
        </queries>
  </predefine_query_handler>
</http_handlers>
`

then I query
`curl --location --request GET 'http://localhost:8123/metrics'`

but All I'm getting with postman/curl
is 

> There is no handle /metrics
>
> Use / or /ping for health checks.
> Or /replicas_status for more sophisticated health checks.

Nothing connected to this issue in logfile, config is processed correctly

Is it not implemented yet ? 

Thanks!

**Comment by den-crane** [comment]
http handlers -- not released yet https://github.com/ClickHouse/ClickHouse/pull/7774

master documentation -- https://clickhouse.tech/docs/en/interfaces/http/#predefined_http_interface

20.3 documentation https://clickhouse.tech/docs/v20.3/en/interfaces/http/

**Comment by ryanmickler** [comment]
For reference, you'll get this error if you exclude the `defaults`. see **https://github.com/ClickHouse/ClickHouse/pull/11628**
```
<http_handlers>
        <defaults/> <!-- enable default HTTP handlers -  otherwise prometheus exporter will not work -->
        <rule>
            <url>/custom_query</url>
            <methods>POST,GET</methods>
            <handler>
                <type>predefined_query_handler</type>
                <query>...</query>
            </handler>
        </rule>
    </http_handlers>
```
