### ISSUE TITLE
Live view query throws Storage Blocks doesn't support PREWHERE exception on CH version > 20

### ISSUE THREAD

**Issue by shawel** [ClickHouse/ClickHouse#10460]
I cannot query live view because of the following error. 
```
Received exception from server (version 20.3.7):
Code: 182. DB::Exception: Received from localhost:9000. DB::Exception: Storage Blocks doesn't support PREWHERE.
```
Live view works on CH version 19.17.6.  I tried on version 20.3.5 and 20.3.7

**Comment by vzakaznikov** [comment]
@KochetovNicolai, any ideas what changed between 19.* and 20.* to cause this?

**Comment by vzakaznikov** [comment]
In the materialized views we have the following

**Comment by qoega** [comment]
Have you tried it?

**Comment by KochetovNicolai** [comment]
I've lost this issue.
How to reproduce it?
