### ISSUE TITLE
Can CH reschedule queries when one of the replica fails?

### ISSUE THREAD

**Issue by gauravphoenix** [ClickHouse/ClickHouse#10462]
Can CH distributed queries recover from replica failures? e.g. if I have three replicas and I am using a distributed table to query them, and during the query, if one of the replica fails, can CH automatically schedule query on remaining either of the two replicas to recover from the failure with no impact on the client?

**Comment by den-crane** [comment]
No. You need to repeat your query and it will be executed on a live replica.
