### ISSUE TITLE
How to request http api by java

### ISSUE THREAD

**Issue by zhouxiujue** [ClickHouse/ClickHouse#10475]
In java, I want to send the insert data in post body. But it is failed.

CREATE TABLE default.test0 (
`id` String,
 `name` String
) ENGINE = MergeTree PARTITION BY id ORDER BY id SETTINGS index_granularity = 8192

**case 1:** 
the url with no password:
```
	public void doPost2() throws ClientProtocolException, IOException {
		String url = "http://192.168.1.23:8123";
		String sql = "insert into default.test0 values ('id1','aa1')";
		List<NameValuePair> paramList = new ArrayList<NameValuePair>();
		paramList.add(new BasicNameValuePair("query", sql));
                paramList.add(new BasicNameValuePair("password", "123456"));
		CloseableHttpResponse response = null;

		HttpPost httpPost = new HttpPost(url);
		httpPost.setEntity(new UrlEncodedFormEntity(paramList, "UTF-8"));
		response = httpClient.execute(httpPost);

		String resultString = EntityUtils.toString(response.getEntity(),"utf-8");
		System.out.println(resultString);
	}
```
It throws execption:
> Code: 194, e.displayText() = DB::Exception: Password required for user default (version 19.9.2.4 (official build))

And the same in postman, I put the password in body parameter, it return 401Unauthorized.
if I add password in url ,it worked well: 
`http://192.168.1.23:8123?password=123456`

**case 2:** 
the url with password:
```
	public void doPost2() throws ClientProtocolException, IOException {
		String url = "http://192.168.1.23:8123?password=123456";
		String sql = "insert into default.test0 values ('id1','aa1')";
		List<NameValuePair> paramList = new ArrayList<NameValuePair>();
		paramList.add(new BasicNameValuePair("query", sql));
		CloseableHttpResponse response = null;

		HttpPost httpPost = new HttpPost(url);
		httpPost.setEntity(new UrlEncodedFormEntity(paramList, "UTF-8"));
		response = httpClient.execute(httpPost);

		String resultString = EntityUtils.toString(response.getEntity(),"utf-8");
		System.out.println(resultString);
	}
```
It throws execption in java and clickouse-server.log:

in java IDE:
> Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 1: query=insert+into+default.test0+values+%28%27id1%27%2C%27aa1%27%29. Expected one of: CREATE TABLE or ATTACH TABLE query, SELECT query, possibly with UNION, SHOW [TEMPORARY] TABLES|DATABASES [[NOT] LIKE 'str'], SELECT query, subquery, possibly with UNION, Query, CREATE, EXISTS, ATTACH, DETACH, DROP, SHOW, DESCRIBE, DESC, USE, SET, SELECT, WITH, KILL, TRUNCATE, SELECT subquery, list of elements, ALTER query, ALTER TABLE, Query with output, SHOW PROCESSLIST query, SHOW PROCESSLIST, RENAME query, RENAME TABLE, SET query, SYSTEM query, EXISTS or SHOW CREATE query, USE query, CHECK TABLE, DESCRIBE query, DROP query, INSERT query, INSERT INTO, KILL QUERY query, OPTIMIZE query, OPTIMIZE TABLE, SELECT query (version 19.9.2.4 (official build))

in clickhouse-server.log:
2020.04.24 16:06:40.100246 [ 111 ] {f3dab91a-dea8-49a3-8e11-5b497a2e47ba} <Error> executeQuery: Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 1: query=insert+into+default.test0+values+%28%27id1%27%2C%27aa1%27%29. Expected one of: CREATE TABLE or ATTACH TABLE query, SELECT query, possibly with UNION, SHOW [TEMPORARY] TABLES|DATABASES [[NOT] LIKE 'str'], SELECT query, subquery, possibly with UNION, Query, CREATE, EXISTS, ATTACH, DETACH, DROP, SHOW, DESCRIBE, DESC, USE, SET, SELECT, WITH, KILL, TRUNCATE, SELECT subquery, list of elements, ALTER query, ALTER TABLE, Query with output, SHOW PROCESSLIST query, SHOW PROCESSLIST, RENAME query, RENAME TABLE, SET query, SYSTEM query, EXISTS or SHOW CREATE query, USE query, CHECK TABLE, DESCRIBE query, DROP query, INSERT query, INSERT INTO, KILL QUERY query, OPTIMIZE query, OPTIMIZE TABLE, SELECT query (version 19.9.2.4 (official build)) (from 10.9.12.77:57968) (in query: query=insert+into+default.test0+values+%28%27id1%27%2C%27aa1%27%29), Stack trace:

0. /usr/bin/clickhouse-server(StackTrace::StackTrace()+0x16) [0x7285206]
1. /usr/bin/clickhouse-server(DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)+0x22) [0x39a84d2]
2. /usr/bin/clickhouse-server(DB::parseQuery(DB::IParser&, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long)+0xac) [0x6eff11c]
3. /usr/bin/clickhouse-server() [0x67e8a22]
4. /usr/bin/clickhouse-server(DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, DB::Context&, std::function<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>, std::function<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>)+0x134) [0x67eaac4]
5. /usr/bin/clickhouse-server(DB::HTTPHandler::processQuery(Poco::Net::HTTPServerRequest&, HTMLForm&, Poco::Net::HTTPServerResponse&, DB::HTTPHandler::Output&)+0x1902) [0x39bd5e2]
6. /usr/bin/clickhouse-server(DB::HTTPHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&)+0x3f1) [0x39c00f1]
7. /usr/bin/clickhouse-server(Poco::Net::HTTPServerConnection::run()+0x32c) [0x7398e9c]
8. /usr/bin/clickhouse-server(Poco::Net::TCPServerConnection::start()+0xf) [0x7393dbf]
9. /usr/bin/clickhouse-server(Poco::Net::TCPServerDispatcher::run()+0xe9) [0x73944f9]
10. /usr/bin/clickhouse-server(Poco::PooledThread::run()+0x81) [0x7445171]
11. /usr/bin/clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0x38) [0x7441578]
12. /usr/bin/clickhouse-server() [0xb1a1c9f]
13. /lib/x86_64-linux-gnu/libpthread.so.0(+0x76db) [0x7fcbe04b86db]
14. /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7fcbdfa3788f]

How should I edit the java code to request the http api, please?
Thank you!

**Comment by AlexanderJLiu** [comment]
I think  you should better use  [clickhouse-jdbc](https://github.com/ClickHouse/clickhouse-jdbc).

These test [examples](https://github.com/ClickHouse/clickhouse-jdbc/tree/master/src/test/java/ru/yandex/clickhouse) may be help.

**Comment by zhouxiujue** [comment]
> I think you should better use [clickhouse-jdbc](https://github.com/ClickHouse/clickhouse-jdbc).
> 
> These test [examples](https://github.com/ClickHouse/clickhouse-jdbc/tree/master/src/test/java/ru/yandex/clickhouse) may be help.

Thank you！I had used jdbc in some project. But now I need to use chproxy which via http api. 
So I need to use httpclient to post my request.

**Comment by AlexanderJLiu** [comment]
Try to change `httpPost.setEntity(new UrlEncodedFormEntity(paramList, "UTF-8"));`  to `httpPost.setEntity(new StringEntity(sql));`

**Comment by zhouxiujue** [comment]
> Try to change `httpPost.setEntity(new UrlEncodedFormEntity(paramList, "UTF-8"));` to `httpPost.setEntity(new StringEntity(sql));`

It worked！Thank you very much！
