### ISSUE TITLE
Need Bulk load - Fast Write into ClickHouse files outside of ClickHouse engine

### ISSUE THREAD

**Issue by huang--yijian** [ClickHouse/ClickHouse#10473]
**Use case**
We want to load history data from HDFS into ClickHouse files, without using online ClickHouse engine.

1. Need some utility to write history data from HDFS into ClickHouse files, minimizing the cost of parsing and part merging.
2. Attach these files into ClickHouse online servers.

By doing so, the query performance of ClickHouse online servers is not severely impacted by loading historical data.

**Describe the solution you'd like**
A bulk load tool of ClickHouse, similar to:
bulk load for RocksDB: https://rocksdb.org/blog/2017/02/17/bulkoad-ingest-sst-file.html
bulk load for HBase: http://people.apache.org/~stack/site/bulk-loads.html

**Describe alternatives you've considered**
Maybe setup another ClickHouse cluster to load history data, and then copy data into online ClickHouse cluster, by clickhouse-copier.

This incurs performance cost with an additional copy between clusters. Not direct enough.

**Additional context**
None

**Comment by nikitamikhaylov** [comment]
Maybe you can use `clickhouse-local`?

**Comment by pgeek** [comment]
> Maybe you can use `clickhouse-local`?

The clickhouse-local is more likely to use clickhouse engine to query local data without deployment. It is not used to bulk load data into clickhouse server.

[https://clickhouse.tech/docs/en/operations/utilities/clickhouse-local/](https://clickhouse.tech/docs/en/operations/utilities/clickhouse-local/)

**Comment by huang--yijian** [comment]
Thanks. I am looking for a tool to write ClickHouse part files outside ClickHouse server, not a tool to query them outside ClickHouse server such as clickhouse-local.

**Comment by alexey-milovidov** [comment]
@huang--yijian You can use `clickhouse-local` to generate MergeTree partitions.
Just CREATE TABLE and do INSERT SELECT.

The data will appear in /tmp directory,
alternatively you can specify path with `-- --path` parameter in command line
or provide a config file similar to server's config.xml

**Comment by godliness** [comment]
@huang--yijian did you find any solutions about this?

**Comment by MaxWk** [comment]
is there any update?

**Comment by alexey-milovidov** [comment]
The solution is to generate data parts with `clickhouse-local` and then copy to the server and ATTACH them to ClickHouse .
