### ISSUE TITLE
Can I change clickhouse logger level without restart service (I use docker)?

### ISSUE THREAD

**Issue by ermin24** [ClickHouse/ClickHouse#10480]
Hello!  According to documentation, I "can modify the cluster, users, and their settings without restarting the server"(c).  But when I'm trying to change the log level on my servers, changes applied only after a service restart. I use docker and clickhouse:19.17, but was experimenting with latest version too. I checked preprocessed/config.xml after change config.yml, and saw my changes before  restarting service. The preprocessed file had changed but without affecting the server behavior.
    Can I change clickhouse logger level on the fly, or I have to always restart service?

**Comment by azat** [comment]
>Can I change clickhouse logger level on the fly, or I have to always restart service?

I guess the answer is [no](https://github.com/ClickHouse/ClickHouse/blob/f34a6dc4821accaaa1b4f01b784abd3446c9df60/programs/server/Server.cpp#L471-L474)

**Comment by ermin24** [comment]
Thanks)

**Comment by robot-clickhouse** [comment]
@ermin24, do you have any further questions?
