### ISSUE TITLE
Apt signature error for official Clickhouse repository

### ISSUE THREAD

**Issue by adrian17** [ClickHouse/ClickHouse#10482]
On Ubuntu 18, when following the instructions:

```
sudo apt-get install dirmngr
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv E0C56BD4

echo "deb http://repo.clickhouse.tech/deb/stable/ main/" | sudo tee \
    /etc/apt/sources.list.d/clickhouse.list
sudo apt-get update
```

On the update step, I got the following signature error:
```
W: GPG error: http://repo.clickhouse.tech/deb/stable main/ Release: The following signatures were invalid: BADSIG C8F1E19FE0C56BD4 ClickHouse Repository Key <milovidov@yandex-team.ru>
E: The repository 'http://repo.clickhouse.tech/deb/stable main/ Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

Which prevents me from being able to update repo, and thus install/update Clickhouse.

**Comment by adrian17** [comment]
Seems like it was fixed already? I'll keep the issue open for confirmation.

**Comment by blinkov** [comment]
@adrian17 I think we weren't doing anything to fix it, probably you have just had some temporary issue. Can't reproduce on fresh Ubunut 18 at the moment.

**Comment by adrian17** [comment]
I was able to reproduce on two separate machines, but indeed looks like a temporary issue.

**Comment by browcio** [comment]
Same issue here. Fresh ubuntu 18.
