### ISSUE TITLE
Distributed table Sharding key

### ISSUE THREAD

**Issue by byx313** [ClickHouse/ClickHouse#10493]
Hello guys.
When I create a distributed table in sharding key is `intHash64(channel)`.When I do a insert `channel = a`,I know this row will be sharding to a shard,like shard one,then I do a query like 'WHERE channel = a',will this query redirect to shard one? Or redirect to all shards?
Hope got the reply,thx

**Comment by weiqxu** [comment]
it will send the query to all shard. 

if the `channel` is the PARTATION KEY  or PK column. other shards that didn't contain the value will return empty result very soon.

**Comment by byx313** [comment]
> it will send the query to all shard.
> 
> if the `channel` is the PARTATION KEY or PK column. other shards that didn't contain the value will return empty result very soon.

What if `channel` is not the partition key or pk?Obviously,send the query to the direct shard will speed up the query time,i can not figure out the reason.

**Comment by den-crane** [comment]
https://clickhouse.tech/docs/en/operations/settings/settings/#settings-optimize_skip_unused_shards

**optimize_skip_unused_shards**

_Enables or disables skipping of unused shards for SELECT queries that have sharding key condition in PREWHERE/WHERE (assumes that the data is distributed by sharding key, otherwise do nothing).

Default value: 0_

**Comment by byx313** [comment]
> https://clickhouse.tech/docs/en/operations/settings/settings/#settings-optimize_skip_unused_shards
> 
> **optimize_skip_unused_shards**
> 
> _Enables or disables skipping of unused shards for SELECT queries that have sharding key condition in PREWHERE/WHERE (assumes that the data is distributed by sharding key, otherwise do nothing)._

thx!

**Comment by byx313** [comment]
> https://clickhouse.tech/docs/en/operations/settings/settings/#settings-optimize_skip_unused_shards
> 
> **optimize_skip_unused_shards**
> 
> _Enables or disables skipping of unused shards for SELECT queries that have sharding key condition in PREWHERE/WHERE (assumes that the data is distributed by sharding key, otherwise do nothing)._

So,for which reason this parameter default value is disable(0)?I think enable this featuer may be better?

**Comment by den-crane** [comment]
> > https://clickhouse.tech/docs/en/operations/settings/settings/#settings-optimize_skip_unused_shards
> > **optimize_skip_unused_shards**
> > _Enables or disables skipping of unused shards for SELECT queries that have sharding key condition in PREWHERE/WHERE (assumes that the data is distributed by sharding key, otherwise do nothing)._
> 
> So,for which reason this parameter default value is disable(0)?I think enable this featuer may be better?

Because for most of the users it will provide wrong results. 
There is no guarantee that data under Distrbuted table sharded properly. One can do inserts directly into underlying mergetree tables or change cluster configuration or change sharding expression.
