### ISSUE TITLE
Can not start with `daemon` mode

### ISSUE THREAD

**Issue by royguo** [ClickHouse/ClickHouse#10495]
Hi, I am trying to install pre-compiled binary and start it, but after I copied everything to install dir, I can't start clickhouse with:

```
./usr/bin/clickhouse-server --config-file=./etc/clickhouse-server/config.xml --daemon
```

There's no output and no clickhouse process been started.

Then, I remove `--daemon` and everything goes well, clickhouse started, after the first time clickhouse started without `daemon`, I tried it again with `--daemon` and it turns out work.

I tried several times and the results are the same.

Clickhouse version: ClickHouse server version 20.2.1.2120 (official build).
System: Debain, 4.19

**Comment by xiashuijun** [comment]
clickhouse-server --daemon --config-file=/etc/clickhouse-server/config.xml,兄弟你把deamon放到前面试试

**Comment by robot-clickhouse** [comment]
@royguo, do you have any further questions?

**Comment by alexey-milovidov** [comment]
Check server logs. The server can start up, print error message to log and shut down.
Check access rights to the logs directory.

(See `<logger>` in config).

**Comment by alexey-milovidov** [comment]
@xiashuijun Position of arguments in command line should not matter.
