### ISSUE TITLE
Not executing log entry for part because source parts size is greater than the current maximum

### ISSUE THREAD

**Issue by BernieJiangDL** [ClickHouse/ClickHouse#10506]
Describe the bug or unexpected behaviour
All mutations got stuck, and server.log keep printing this log,
only half of our servers have this kind of problem

Expected behavior
All mutations being done in minuates

Error message and/or stacktrace
server.log

`2020.04.26 12:06:14.663756 [ 15 ] {} <Debug> db.table (ReplicatedMergeTreeQueue): Not executing log entry MUTATE_PART for part 2020040816_819_1509_27_7240 because source parts size (9.27 MiB) is greater than the current maximum (4.45 MiB).`

Any solutions to this problem?

btw:

The result of top command  on one of the servers is below:

> top - 16:25:20 up 338 days, 15:53,  3 users,  load average: 16.12, 15.99, 15.85
Threads: 2072 total,  17 running, 2054 sleeping,   0 stopped,   1 zombie
%Cpu(s): 20.0 us,  0.1 sy,  0.0 ni, 79.9 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 19590153+total, 50483028 free, 75521680 used, 69896816 buff/cache
KiB Swap:        0 total,        0 free,        0 used. 11950400+avail Mem 

>    PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND                                        
 75109 clickho+  20   0   91.3g  69.1g  19624 R 99.9 37.0   1613:33 BackgrProcPool                                 
 75111 clickho+  20   0   91.3g  69.1g  19624 R 99.9 37.0   1639:10 BackgrProcPool                                 
 75112 clickho+  20   0   91.3g  69.1g  19624 R 99.9 37.0   1571:22 BackgrProcPool                                 
 75113 clickho+  20   0   91.3g  69.1g  19624 R 99.9 37.0   1605:00 BackgrProcPool                                 
 75115 clickho+  20   0   91.3g  69.1g  19624 R 99.9 37.0   1637:14 BackgrProcPool                                 
 75116 clickho+  20   0   91.3g  69.1g  19624 R 99.9 37.0   1585:15 BackgrProcPool                                 
 75118 clickho+  20   0   91.3g  69.1g  19624 R 99.9 37.0   1693:24 BackgrProcPool                                 
 75119 clickho+  20   0   91.3g  69.1g  19624 R 99.9 37.0   1649:12 BackgrProcPool                                 
 75120 clickho+  20   0   91.3g  69.1g  19624 R 99.9 37.0   1645:11 BackgrProcPool                                 
 75122 clickho+  20   0   91.3g  69.1g  19624 R 99.9 37.0   1632:54 BackgrProcPool                                 
 75107 clickho+  20   0   91.3g  69.1g  19624 R 99.7 37.0   1731:06 BackgrProcPool                                 
 75108 clickho+  20   0   91.3g  69.1g  19624 R 99.7 37.0   1974:51 BackgrProcPool                                 
 75110 clickho+  20   0   91.3g  69.1g  19624 R 99.7 37.0   1826:02 BackgrProcPool                                 
 75114 clickho+  20   0   91.3g  69.1g  19624 R 99.7 37.0   1677:27 BackgrProcPool                                 
 75117 clickho+  20   0   91.3g  69.1g  19624 R 99.7 37.0   1609:37 BackgrProcPool                                 
 75121 clickho+  20   0   91.3g  69.1g  19624 R 99.7 37.0   1599:40 BackgrProcPool `

**Comment by BernieJiangDL** [comment]
How dose this happen from very beginning ?

**Comment by den-crane** [comment]
It's not a problem. It's a debug message that currently all free space are booked by running merges/mutations and this mutation will wait for free resources.

**Comment by BernieJiangDL** [comment]
> It's not a problem. It's a debug message that currently all free space is booked by running merges/mutations and this mutation will wait for free resources.
> 
> Mutations and merges book twice space as their parts sizes.

Thanks Denis. But this did cause other side-effects like the inserts and DDL queries which happen on  this “problem” node would fail with high probability which would cause upstream tasks fail as well.

I found the reason why this log keep being printed is that  one of my relicatedMergeTree table's many partitions(from a week ago untill now) are all waiting for merge and the inserts to this table happens nomally during this period. It seems like background merge threads got stuck or hang up or something else like that. This may lead to failure of other table's inserts.

Finally I force drop that table to solve this kind of issue.

I`m wondering that if merges are processing significantly slower than inserts, clickhouse will throw an exception to user side. But it seems doesn`t work on this case I run into. (The merge is happening on partitions a week ago can be checked out on system.merges )

**Comment by den-crane** [comment]
The root cause of everything is "merges are processing significantly slower than inserts".

**Comment by BernieJiangDL** [comment]
> The root cause of everything is "merges are processing significantly slower than inserts".
> 
> [#6720 (comment)](https://github.com/ClickHouse/ClickHouse/issues/6720#issuecomment-526045768)

Thanks~
