### ISSUE TITLE
DB::Exception: Cannot schedule a task

### ISSUE THREAD

**Issue by hydra-yl** [ClickHouse/ClickHouse#10504]
It seems the maximum threads for one clickhouse node is 4096. After reach this limit, any command at any node in a cluster will result a _DB::Exception: Cannot schedule a task_ error.

Below is a breakdown of different clickhouse thread type(command: `ps -el -o user,pid,psr,comm,args | grep -v grep | grep clickhouse | awk '{print $4}' | sort -r | uniq -c | sort -rn`)
```
2317 DistrDirMonitor
1361 HTTPHandler
310 BufferFlush
59 TCPHandler
7 clickhouse-serv
2 ConfigReloader
1 ZookeeperSend
1 ZookeeperRecv
1 SessionCleaner
1 DDLWorkderClnr
1 DDLwzorker
1 BckSchPoolDelay
1 AsyncMetrics
1 AsyncBlockInput
```
The question is: How should we handle the above situation?

**Comment by azat** [comment]
> It seems the maximum threads for one clickhouse node is 4096. After reach this limit, any command at any node in a cluster will result a DB::Exception: Cannot schedule a task error

AFAIR the threads limit is 10000, looks related to #9154

> 2317 DistrDirMonitor

After #10263 this can be configured, but there is no stable release with this pr included yet
