### ISSUE TITLE
Unknown Format Parquet 

### ISSUE THREAD

**Issue by Crazylearner30** [ClickHouse/ClickHouse#10519]
Hi,

Trying to export the data from table in Parquet format using below:

clickhouse-client --query="SELECT * FROM {some_table} FORMAT Parquet" > {some_file.pq}

**Error:**  Code: 73. DB::Exception: Unknown format Parquet

Please let me know the correct format to export the file or is there anything else i have missed.

**Comment by AlexanderJLiu** [comment]
I think you used the low version of clickhouse that doesn't support Parquet format.
Try to update your clickhouse to 19.4.0.49 or higher version.

**Comment by Crazylearner30** [comment]
Thanks for the quick response. Will try to upgrade version.

**Comment by alexey-milovidov** [comment]
> Is it same for importing data into table as well?

Yes.
