### ISSUE TITLE
array join  ErrnoException: Allocator: Cannot mmap 64.00 MiB

### ISSUE THREAD

**Issue by LvKeWechat** [ClickHouse/ClickHouse#10524]
Clickhouse  version 19.15.1.1  query on  distributed node  failed
`select uniq(uid,sid) as value,l.1 as from ,l.2 as to
from (
select uid,sid,s_t
from (
select
distinct_id as uid,
arraySort((x)->x.1,groupArray(tuple(toUnixTimestamp(ums_ts_),toString(event_id)))) as cur,
arrayDifference((x)->x.1,cur) as cur_diff,
arrayPushBack(
arrayFilter(
(x,y)->y>1800,
arrayEnumerate(cur_diff),
cur_diff
),
length(cur)+1
) as cur_split,
arrayFilter((x)->length(x)>0,
arrayMap((x)->arrayMap((x)->x.2,arraySlice(x,arrayFirstIndex((y)->y.2='1301',x))),
arrayMap((x,y)->arraySlice(cur,
multiIf(y==1,1,cur_split[y-1]),multiIf(y==1,cur_split[y]-1,cur_split[y]-cur_split[y-1])),cur_split,arrayEnumerate(cur_split)))) as t,
arrayMap((x)->arrayMap((y,z,q)->tuple(concat(toString(y),'_$$_',z),concat(multiIf(y==length(arrayEnumerate(x)),'',toString(y+1)),'_$$_',q)),arrayEnumerate(x),x,arrayPushBack(arrayPopFront(x),'_waste')),t) as tx
from event_data.event_wos_p15  where  event_id in (1301,1310,1303,1305,1429) and  event_date>='2020-03-01' and event_date<='2020-03-31'
group by distinct_id
) array join tx as s_t,arrayEnumerate(tx) as sid
) array join s_t as l  group by from ,to`
throw this error on distributed node. check system.query_log table  found that array join  executed on distributed node, not  mergetree node.why?
query mergetree node query_log table

- type:                 QueryFinish
event_date:           2020-04-27
event_time:           2020-04-27 15:34:54
query_start_time:     2020-04-27 15:34:53
query_duration_ms:    628
read_rows:            4955184
read_bytes:           355066855
written_rows:         0
written_bytes:        0
result_rows:          76798
result_bytes:         4636864
memory_usage:         660752320
query:                SELECT distinct_id AS uid, arrayMap(x -> arrayMap((y, z, q) -> (concat(toString(y), '_$$_', z), concat(multiIf(y = length(arrayEnumerate(x)), '', toString(y + 1)), '_$$_', q)), arrayEnumerate(x), x, arrayPushBack(arrayPopFront(x), '_waste')), arrayFilter(x -> (length(x) > 0), arrayMap(x -> arrayMap(x -> (x.2), arraySlice(x, arrayFirstIndex(y -> ((y.2) = '1301'), x))), arrayMap((x, y) -> arraySlice(arraySort(x -> (x.1), groupArray((toUnixTimestamp(ums_ts_), toString(event_id)))) AS cur, multiIf(y = 1, 1, (arrayPushBack(arrayFilter((x, y) -> (y > 1800), arrayEnumerate(arrayDifference(x -> (x.1), cur) AS cur_diff), cur_diff), length(cur) + 1) AS cur_split)[y - 1]), multiIf(y = 1, (cur_split[y]) - 1, (cur_split[y]) - (cur_split[y - 1]))), cur_split, arrayEnumerate(cur_split)))) AS t) AS tx FROM event_data.event_wos_p15 WHERE (event_id IN (1301, 1310, 1303, 1305, 1429)) AND (event_date >= '2020-03-01') AND (event_date <= '2020-03-31') GROUP BY distinct_id

**Comment by qoega** [comment]
19.15 is no longer supported.
>this error
I can't see any error/stacktrace

**Comment by 4ertus2** [comment]
It's not clear in your sample which tables are distributed and which are not. It's even hard to find tables in your query :) It's better to simplify it as much as possible before makeing an issue.

Anyway. ClickHouse tryes to calculate as much as possible on remote nodes and fetch as low data as possible via network. It's OK in most of cases. If you have some special case - let's discuss.

**Comment by LvKeWechat** [comment]
this query only  has one distributed table  `event_data.event_wos_p15`
simplified SQL
`select uniq(uid,sid) as value,l.1 as from ,l.2 as to from (
select uid,sid,s_t from (
select distinct_id as uid ,groupArray((XXX,XXX,XXX,)) as cur,... array-function-transformation(cur) as tx  
from event_data.event_wos_p15 where ...  group by uid 
) array join tx as s_t,arrayEnumerate(tx) as sid
) array join s_t as l group by from,to`

the innermost subquery  `select distinct_id as uid ,groupArray((XXX,XXX,XXX,)) as cur,... array-function-transformation(cur) as tx  from event_data.event_wos_p15 where ...  group by uid 
` get a two-dimensional array(**tx**) .

1. in default mode(distributed_group_by_no_merge=0), subquery `from distributed_table` will be executed on shards ,and the outside `()` query  will be executed on distributed node. [why not array join execute on mergetree](https://stackoverflow.com/questions/61453369/why-not-array-join-execute-on-mergetree-node)

2. using distributed_group_by_no_merge=1 at the same level of subquery,the-same-level subquery will be executed on shards,  and the outside aggregate query will be executed on distributed node. [distributed_group_by_no_merge](https://stackoverflow.com/questions/61743180/what-is-the-effect-of-distributed-group-by-no-merge)

so ,it works well when  using distributed_group_by_no_merge=1
but ,if not using distributed_group_by_no_merge=1,get an error **ErrnoException: Allocator: Cannot mmap 64.00 MiB**. why it throws this error? is it that distributed node needs to copy large amounts of data  from shards to aggregate？
I view the trace log. **<Debug> MemoryTracker: Peak memory usage (total): 2.93 GiB.**,but total 64GB RAM

_2020.04.26 17:10:37.579171 [ 29 ] {4d818c2e-113b-4b32-a212-592d0828d808} <Debug> executeQuery: (from [::1]:36912, user: root) SE
LECT uniq(uid, sid) AS value, l.1 AS from, l.2 AS to FROM (SELECT uid, sid, s_t FROM (SELECT distinct_id AS uid, arraySort(x ->
(x.1), groupArray((toUnixTimestamp(ums_ts_), toString(event_id)))) AS cur, arrayDifference(x -> (x.1), cur) AS cur_diff, arrayPu
shBack(arrayFilter((x, y) -> (y > 1800), arrayEnumerate(cur_diff), cur_diff), length(cur) + 1) AS cur_split, arrayFilter(x -> (l
ength(x) > 0), arrayMap(x -> arrayMap(x -> (x.2), arraySlice(x, arrayFirstIndex(y -> ((y.2) = '1301'), x))), arrayMap((x, y) ->
arraySlice(cur, multiIf(y = 1, 1, cur_split[y - 1]), multiIf(y = 1, (cur_split[y]) - 1, (cur_split[y]) - (cur_split[y - 1]))), c
ur_split, arrayEnumerate(cur_split)))) AS t, arrayMap(x -> arrayMap((y, z, q) -> (concat(toString(y), '_$$_', z), concat(multiIf
(y = length(arrayEnumerate(x)), '', toString(y + 1)), '_$$_', q)), arrayEnumerate(x), x, arrayPushBack(arrayPopFront(x), '_waste
')), t) AS tx FROM event_data.event_wos_p15 WHERE (event_id IN (1301, 1310, 1303, 1305, 1429)) AND (event_date >= '2020-03-01')
AND (event_date <= '2020-03-31') GROUP BY distinct_id) ARRAY JOIN tx AS s_t, arrayEnumerate(tx) AS sid) ARRAY JOIN s_t AS l GROU
P BY from, to LIMIT 100
2020.04.26 17:10:37.704854 [ 29 ] {4d818c2e-113b-4b32-a212-592d0828d808} <Trace> InterpreterSelectQuery: WithMergeableState -> C
omplete
2020.04.26 17:10:37.837405 [ 29 ] {4d818c2e-113b-4b32-a212-592d0828d808} <Trace> InterpreterSelectQuery: FetchColumns -> Complet
e
2020.04.26 17:10:37.837540 [ 29 ] {4d818c2e-113b-4b32-a212-592d0828d808} <Trace> InterpreterSelectQuery: FetchColumns -> Complet
e
2020.04.26 17:10:37.838168 [ 29 ] {4d818c2e-113b-4b32-a212-592d0828d808} <Debug> executeQuery: Query pipeline:
Limit
 Expression
  Expression
   Aggregating
    Concat
     Expression
      Expression
       Expression
        Expression
         Expression
          MergingAggregated
           Union
            Remote × 6

2020.04.26 17:10:37.839510 [ 30 ] {4d818c2e-113b-4b32-a212-592d0828d808} <Trace> Aggregator: Aggregating
2020.04.26 17:10:37.839626 [ 30 ] {4d818c2e-113b-4b32-a212-592d0828d808} <Trace> Aggregator: Reading blocks of partially aggrega
ted data.
2020.04.26 17:10:37.840678 [ 31 ] {4d818c2e-113b-4b32-a212-592d0828d808} <Trace> Connection (10.126.65.211:9001): Connecting. Da
tabase: (not specified). User: writer
2020.04.26 17:10:37.840983 [ 32 ] {4d818c2e-113b-4b32-a212-592d0828d808} <Trace> Connection (10.126.65.211:9002): Connecting. Da
tabase: (not specified). User: writer
2020.04.26 17:10:37.841338 [ 33 ] {4d818c2e-113b-4b32-a212-592d0828d808} <Trace> Connection (10.126.65.211:9003): Connecting. Da
tabase: (not specified). User: writer
2020.04.26 17:10:37.841616 [ 31 ] {4d818c2e-113b-4b32-a212-592d0828d808} <Trace> Connection (10.126.65.211:9001): Connected to C
lickHouse server version 19.15.1.
2020.04.26 17:10:37.841636 [ 32 ] {4d818c2e-113b-4b32-a212-592d0828d808} <Trace> Connection (10.126.65.211:9002): Connected to C
lickHouse server version 19.15.1.
2020.04.26 17:10:37.841721 [ 34 ] {4d818c2e-113b-4b32-a212-592d0828d808} <Trace> Connection (10.126.65.212:9001): Connecting. Da
tabase: (not specified). User: writer
2020.04.26 17:10:37.841904 [ 33 ] {4d818c2e-113b-4b32-a212-592d0828d808} <Trace> Connection (10.126.65.211:9003): Connected to C
lickHouse server version 19.15.1.
2020.04.26 17:10:37.842213 [ 32 ] {4d818c2e-113b-4b32-a212-592d0828d808} <Trace> Connection (10.126.65.212:9003): Connecting. Da
tabase: (not specified). User: writer
2020.04.26 17:10:37.842249 [ 35 ] {4d818c2e-113b-4b32-a212-592d0828d808} <Trace> Connection (10.126.65.212:9002): Connecting. Da
tabase: (not specified). User: writer
2020.04.26 17:10:37.842504 [ 34 ] {4d818c2e-113b-4b32-a212-592d0828d808} <Trace> Connection (10.126.65.212:9001): Connected to C
lickHouse server version 19.15.1.
2020.04.26 17:10:37.842854 [ 35 ] {4d818c2e-113b-4b32-a212-592d0828d808} <Trace> Connection (10.126.65.212:9002): Connected to C
lickHouse server version 19.15.1.
2020.04.26 17:10:37.848826 [ 32 ] {4d818c2e-113b-4b32-a212-592d0828d808} <Trace> Connection (10.126.65.212:9003): Connected to C
lickHouse server version 19.15.1.
2020.04.26 17:10:38.348554 [ 31 ] {4d818c2e-113b-4b32-a212-592d0828d808} <Debug> MemoryTracker: Current memory usage: 1.00 GiB.
2020.04.26 17:10:38.523624 [ 30 ] {4d818c2e-113b-4b32-a212-592d0828d808} <Trace> Aggregator: Read 1536 blocks of partially aggre
gated data, total 458726 rows.
2020.04.26 17:10:38.529452 [ 30 ] {4d818c2e-113b-4b32-a212-592d0828d808} <Trace> Aggregator: Merging partially aggregated two-le
vel data.
2020.04.26 17:10:38.621253 [ 40 ] {4d818c2e-113b-4b32-a212-592d0828d808} <Debug> MemoryTracker: Current memory usage: 2.00 GiB.
2020.04.26 17:10:38.740732 [ 30 ] {4d818c2e-113b-4b32-a212-592d0828d808} <Trace> Aggregator: Merged partially aggregated two-lev
el data.
2020.04.26 17:10:38.756994 [ 30 ] {4d818c2e-113b-4b32-a212-592d0828d808} <Trace> Aggregator: Converting aggregated data to block
s
2020.04.26 17:10:38.847175 [ 30 ] {4d818c2e-113b-4b32-a212-592d0828d808} <Trace> Aggregator: Converted aggregated data to blocks
. 458726 rows, 444.787 MiB in 0.090 sec. (5119676.624 rows/sec., 4964.112 MiB/sec.)
2020.04.26 17:10:38.982754 [ 30 ] {4d818c2e-113b-4b32-a212-592d0828d808} <Trace> Aggregator: Aggregation method: serialized
2020.04.26 17:10:39.133429 [ 30 ] {4d818c2e-113b-4b32-a212-592d0828d808} <Trace> Aggregator: Destroying aggregate states
2020.04.26 17:10:39.491220 [ 29 ] {4d818c2e-113b-4b32-a212-592d0828d808} <Error> executeQuery: Code: 173, e.displayText() = DB::
ErrnoException: Allocator: Cannot mmap 64.00 MiB., errno: 12, strerror: Cannot allocate memory (version 19.15.1.1) (from [::1]:3
6912) (in query: SELECT uniq(uid, sid) AS value, l.1 AS from, l.2 AS to FROM (SELECT uid, sid, s_t FROM (SELECT distinct_id AS u
id, arraySort(x -> (x.1), groupArray((toUnixTimestamp(ums_ts_), toString(event_id)))) AS cur, arrayDifference(x -> (x.1), cur) A
S cur_diff, arrayPushBack(arrayFilter((x, y) -> (y > 1800), arrayEnumerate(cur_diff), cur_diff), length(cur) + 1) AS cur_split,
arrayFilter(x -> (length(x) > 0), arrayMap(x -> arrayMap(x -> (x.2), arraySlice(x, arrayFirstIndex(y -> ((y.2) = '1301'), x))),
arrayMap((x, y) -> arraySlice(cur, multiIf(y = 1, 1, cur_split[y - 1]), multiIf(y = 1, (cur_split[y]) - 1, (cur_split[y]) - (cur
_split[y - 1]))), cur_split, arrayEnumerate(cur_split)))) AS t, arrayMap(x -> arrayMap((y, z, q) -> (concat(toString(y), '_$$_',
 z), concat(multiIf(y = length(arrayEnumerate(x)), '', toString(y + 1)), '_$$_', q)), arrayEnumerate(x), x, arrayPushBack(arrayP
opFront(x), '_waste')), t) AS tx FROM event_data.event_wos_p15 WHERE (event_id IN (1301, 1310, 1303, 1305, 1429)) AND (event_dat
e >= '2020-03-01') AND (event_date <= '2020-03-31') GROUP BY distinct_id) ARRAY JOIN tx AS s_t, arrayEnumerate(tx) AS sid) ARRAY
 JOIN s_t AS l GROUP BY from, to LIMIT 100), Stack trace:

0. 0x35a34d0 StackTrace::StackTrace() /data/ch-project/develop/ClickHouse-v19.13.5.44-stable/dbms/src/Common/StackTrace.cpp:227
1. 0x35b362f DB::ErrnoException::ErrnoException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >
const&, int, int, std::optional<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > const&) /usr/l
ocal/include/c++/9.1.0/optional:132
2. 0x31e76d1 DB::throwFromErrno(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int
) /usr/local/include/c++/9.1.0/bits/basic_string.h:222
3. 0x35c0baa Allocator<false, false>::allocNoTrack(unsigned long, unsigned long) /data/ch-project/develop/ClickHouse-v19.13.5.44
-stable/dbms/src/Common/Allocator.h:225
4. 0x35cd826 Allocator<false, false>::realloc(void*, unsigned long, unsigned long, unsigned long) /data/ch-project/develop/Click
House-v19.13.5.44-stable/dbms/src/Common/Allocator.h:159
5. 0x668a4eb COW<DB::IColumn>::immutable_ptr<DB::IColumn> DB::ColumnArray::replicateNumber<unsigned int>(DB::PODArray<unsigned l
ong, 4096ul, Allocator<false, false>, 15ul, 16ul> const&) const /data/ch-project/develop/ClickHouse-v19.13.5.44-stable/dbms/src/
Common/PODArray.h:143
6. 0x6687384 DB::ColumnArray::replicate(DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 15ul, 16ul> const&) const [
clone .constprop.0] /data/ch-project/develop/ClickHouse-v19.13.5.44-stable/dbms/src/Columns/ColumnArray.cpp:713
7. 0x66876c3 DB::ColumnArray::replicateTuple(DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 15ul, 16ul> const&) co
nst /usr/local/include/c++/9.1.0/bits/stl_vector.h:1043
8. 0x6687f66 DB::ColumnArray::replicate(DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 15ul, 16ul> const&) const /
data/ch-project/develop/ClickHouse-v19.13.5.44-stable/dbms/src/Columns/ColumnArray.cpp:724
9. 0x669f970 DB::ColumnFunction::replicate(DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 15ul, 16ul> const&) cons
t /data/ch-project/develop/ClickHouse-v19.13.5.44-stable/contrib/boost/boost/smart_ptr/intrusive_ptr.hpp:115
10. 0x5430c35 DB::FunctionArrayMapped<DB::ArrayMapImpl, DB::NameArrayMap>::executeImpl(DB::Block&, std::vector<unsigned long, st
d::allocator<unsigned long> > const&, unsigned long, unsigned long) /data/clickhouse-v19.13.5.44/bin/clickhouse
11. 0x638216d DB::PreparedFunctionImpl::execute(DB::Block&, std::vector<unsigned long, std::allocator<unsigned long> > const&, u
nsigned long, unsigned long, bool) /data/ch-project/develop/ClickHouse-v19.13.5.44-stable/dbms/src/Functions/IFunction.cpp:464
12. 0x6bede2e DB::ExpressionAction::execute(DB::Block&, bool) const /usr/local/include/c++/9.1.0/bits/stl_vector.h:677
13. 0x6bef4e5 DB::ExpressionActions::execute(DB::Block&, bool) const /data/ch-project/develop/ClickHouse-v19.13.5.44-stable/dbms
/src/Interpreters/ExpressionActions.cpp:760
14. 0x6a995ec DB::ExpressionBlockInputStream::readImpl() /data/ch-project/develop/ClickHouse-v19.13.5.44-stable/dbms/src/DataStr
eams/ExpressionBlockInputStream.cpp:37
15. 0x63fc6e4 DB::IBlockInputStream::read() /usr/local/include/c++/9.1.0/bits/stl_vector.h:108
16. 0x6a995d0 DB::ExpressionBlockInputStream::readImpl() /data/ch-project/develop/ClickHouse-v19.13.5.44-stable/dbms/src/DataStr
eams/ExpressionBlockInputStream.cpp:34
17. 0x63fc6e4 DB::IBlockInputStream::read() /usr/local/include/c++/9.1.0/bits/stl_vector.h:108
18. 0x6a995d0 DB::ExpressionBlockInputStream::readImpl() /data/ch-project/develop/ClickHouse-v19.13.5.44-stable/dbms/src/DataStr
eams/ExpressionBlockInputStream.cpp:34
19. 0x63fc6e4 DB::IBlockInputStream::read() /usr/local/include/c++/9.1.0/bits/stl_vector.h:108
20. 0x6a995d0 DB::ExpressionBlockInputStream::readImpl() /data/ch-project/develop/ClickHouse-v19.13.5.44-stable/dbms/src/DataStr
eams/ExpressionBlockInputStream.cpp:34
21. 0x63fc6e4 DB::IBlockInputStream::read() /usr/local/include/c++/9.1.0/bits/stl_vector.h:108
22. 0x6a995d0 DB::ExpressionBlockInputStream::readImpl() /data/ch-project/develop/ClickHouse-v19.13.5.44-stable/dbms/src/DataStr
eams/ExpressionBlockInputStream.cpp:34
23. 0x63fc6e4 DB::IBlockInputStream::read() /usr/local/include/c++/9.1.0/bits/stl_vector.h:108
24. 0x654ee18 DB::ConcatBlockInputStream::readImpl() /usr/local/include/c++/9.1.0/bits/stl_vector.h:110
25. 0x63fc6e4 DB::IBlockInputStream::read() /usr/local/include/c++/9.1.0/bits/stl_vector.h:108
26. 0x6b20cf5 DB::Aggregator::execute(std::shared_ptr<DB::IBlockInputStream> const&, DB::AggregatedDataVariants&) /data/ch-proje
ct/develop/ClickHouse-v19.13.5.44-stable/dbms/src/Interpreters/Aggregator.cpp:864
27. 0x6a632b5 DB::AggregatingBlockInputStream::readImpl() /usr/local/include/c++/9.1.0/x86_64-pc-linux-gnu/bits/gthr-default.h:7
48
28. 0x63fc6e4 DB::IBlockInputStream::read() /usr/local/include/c++/9.1.0/bits/stl_vector.h:108
29. 0x6a995d0 DB::ExpressionBlockInputStream::readImpl() /data/ch-project/develop/ClickHouse-v19.13.5.44-stable/dbms/src/DataStr
eams/ExpressionBlockInputStream.cpp:34
30. 0x63fc6e4 DB::IBlockInputStream::read() /usr/local/include/c++/9.1.0/bits/stl_vector.h:108
31. 0x6a995d0 DB::ExpressionBlockInputStream::readImpl() /data/ch-project/develop/ClickHouse-v19.13.5.44-stable/dbms/src/DataStr
eams/ExpressionBlockInputStream.cpp:34

2020.04.26 17:10:39.498717 [ 29 ] {4d818c2e-113b-4b32-a212-592d0828d808} <Debug> MemoryTracker: Peak memory usage (for query): 2
.93 GiB.
2020.04.26 17:10:39.503499 [ 29 ] {4d818c2e-113b-4b32-a212-592d0828d808} <Trace> UnionBlockInputStream: Waiting for threads to f
inish
2020.04.26 17:10:39.503563 [ 29 ] {4d818c2e-113b-4b32-a212-592d0828d808} <Trace> UnionBlockInputStream: Waited for threads to fi
nish
2020.04.26 17:10:39.503659 [ 29 ] {4d818c2e-113b-4b32-a212-592d0828d808} <Debug> MemoryTracker: Peak memory usage (total): 2.93
GiB.
2020.04.26 17:10:39.503726 [ 29 ] {4d818c2e-113b-4b32-a212-592d0828d808} <Information> TCPHandler: Processed in 1.929 sec._

**Comment by robot-clickhouse** [comment]
@LvKeWechat, do you have any further questions?

**Comment by alexey-milovidov** [comment]
Does it reproduce on version 20.8?
