### ISSUE TITLE
Versioned CollapsingMergeTree  primary key support?

### ISSUE THREAD

**Issue by templarzq** [ClickHouse/ClickHouse#10522]
(you don't have to strictly follow this form)

**Describe the issue**
 It seems that Versioned CollapsingMergeTree does not support primary key.

**How to reproduce**

ClickHouse server version: v19.16

CREATE TABLE testcollapse.tversion on cluster ck_cluster
(
    UserID UInt64,
    PageViews UInt8,
    Duration UInt8,
    Sign Int8,
    Version UInt32
)
ENGINE = VersionedCollapsingMergeTree(Sign, Version)
PRIMARY KEY (UserID)
ORDER BY UserID
SETTINGS index_granularity=8192;

* Queries to run that lead to unexpected result

INSERT INTO tversion VALUES (4324182021466249494, 5, 147, 1, 1);
INSERT INTO tversion VALUES (4324182021466249494, 5, 147, 1, 1);

select * from tversion;
(same as select * from tversion final;)

4324182021466249494	5	147	1	1
4324182021466249494	5	147	1	1

**Expected behavior**
if the table primary key is enabled,the result should be:

4324182021466249494	5	147	1	1

**Comment by alexey-milovidov** [comment]
This is how it is documented:

> When ClickHouse merges data parts, it deletes each pair of rows that have the same primary key and version and **different Sign**. The order of rows does not matter.

When you SELECT with FINAL, the logic is the same that for background merge.
