### ISSUE TITLE
Balance the query load between replicas in a shard

### ISSUE THREAD

**Issue by cw9** [ClickHouse/ClickHouse#10564]
Hi, I sometimes saw an imbalanced query load distribution between the replicas in a shard.

e.g:
![image](https://user-images.githubusercontent.com/6710599/80538563-f271a580-8973-11ea-889d-c592e491be87.png)

I'm using random as the load_balancing policy. The two replicas are using similar HW resource throughout the time, the replication queue remains very low so I don't think any of them got stale.

Sometimes when a flood of queries come in, they could be sent to one node way more than the other as the graph indicates so the one received most of the query could reach max_concurrent_queries. Is there anything I can do to force an even distribution between them?

I tried to list the nodes from the node receiving the distributed query:
```
SELECT
    shard_num,
    shard_weight,
    replica_num,
    errors_count,
    estimated_recovery_time
FROM system.clusters
LIMIT 4

┌─shard_num─┬─shard_weight─┬─replica_num─┬─errors_count─┬─estimated_recovery_time─┐
│         1 │            1 │           1 │            1 │                       0 │
│         1 │            1 │           2 │            1 │                       0 │
│         2 │            1 │           1 │            1 │                       0 │
│         2 │            1 │           2 │            1 │                       0 │
│         3 │            1 │           1 │            1 │                       0 │
│         3 │            1 │           2 │            1 │                       0 │
│         4 │            1 │           1 │            1 │                       0 │
│         4 │            1 │           2 │            0 │                       0 │
└───────────┴──────────────┴─────────────┴──────────────┴─────────────────────────┘

4 rows in set. Elapsed: 36.449 sec.
```
A lot of the nodes have errors_count as 1, is there any way for me to check what is that error? Is it possible that a bunch of queries came in and when one replica had 1 error and one replica had 0, so they all got sent to the replica with 0 errors like shard 4 above?

Also the above query took a really long time, is that expected? There are 300+ nodes in the table.

* Which ClickHouse server version to use
20.3.5

**Comment by azat** [comment]
>Sometimes when a flood of queries come in, they could be sent to one node way more than the other as the graph indicates so the one received most of the query could reach max_concurrent_queries

I guess the graph shows queries that are currently executed, in this case maybe one replica handle queries faster then the other, hence the spike.

>A lot of the nodes have errors_count as 1, is there any way for me to check what is that error?

Some details (but not too much) should be in logs with the "Connection failed at try ..., reason:" messages

> Is it possible that a bunch of queries came in and when one replica had 1 error and one replica had 0, so they all got sent to the replica with 0 errors like shard 4 above?

You can play with `distributed_replica_error_half_life` it may helps (since default is 60 seconds, which is pretty huge, regardless comments)

Refs: #6399

**Comment by cw9** [comment]
> I guess the graph shows queries that are currently executed, in this case maybe one replica handle queries faster then the other, hence the spike.

What would cause this? The two replicas are running in same HW and replicating the same data.

**Comment by azat** [comment]
>The two replicas are running in same HW and replicating the same data.

This is just a guess and I seems unlikely situation, so I think that right now you can play with `distributed_replica_error_half_life` to get replica online sooner (i.e. make replicas selectable for querying with random load_balancing).

**Comment by cw9** [comment]
Got it, can I set `distributed_replica_error_cap` to 0?  would that + `load_balancing = random` give me basically round-robin load balancing? Cause there is no round-robin strategy natively in CH. 

For my use case, I actually prefer returning partial data with better latency so I'm also using `skip_unavailable_shards = 1`

**Comment by azat** [comment]
> can I set distributed_replica_error_cap to 0? 

Nope, it will trigger division by zero error :) (will fix that)
So you need to use at least 1 second and see if this will work for your (since this is second, and can be pretty long)

> Cause there is no round-robin strategy natively in CH.

Actually it is pretty simple to add...

**Comment by azat** [comment]
>Got it, can I set distributed_replica_error_cap to 0? would that + load_balancing = random give me basically round-robin load balancing? Cause there is no round-robin strategy natively in CH.

Sorry, I misread your message (thought that you wrote `distributed_replica_error_half_life`), so yes `distributed_replica_error_cap=0` may work more or less like round-robin

**Comment by azat** [comment]
>Is there anything I can do to force an even distribution between them?

Looks this will be resolved after #11645 (+ #11669) ?

**Comment by cw9** [comment]
Awesome! Will try the new features out, thanks for the help!

**Comment by azat** [comment]
So, looks like this can be closed? (after https://github.com/ClickHouse/ClickHouse/issues/10564#issuecomment-646296199)

**Comment by cw9** [comment]
I have not tried the feature yet, still waiting for the release, but feel free to close for now. Thanks for the help!
