### ISSUE TITLE
Kafka engine virtual column "_timestamp" is only precise to the nearest second

### ISSUE THREAD

**Issue by ctlaltdefeat** [ClickHouse/ClickHouse#10565]
**Describe the bug**
The virtual column ```_timestamp``` created by the Kafka engine always casts the timestamp retrieved from the Kafka record to the nearest second, regardless of their exact values. This level of accuracy is arbitrary and undocumented and leads to inaccurate timestamps.

**Expected behavior**
I believe the timestamp of a Kafka record always represents the number of milliseconds since epoch, so one of the following should happen:

1) Simply let ```_timestamp```  be ```UInt64```.
2) Convert to the nearest millisecond, i.e ```_timestamp``` should be ```DateTime64(3)```.
3) Make it user-configurable.

**Comment by filimonov** [comment]
1 - will brake backward compatibity
2 - may work (some extra checks needed)
3 - quite safe option, but schema migration may be tricky from the user perspecive.

also there is a 4: create a new columns _timestamp_ms or similar.
