### ISSUE TITLE
Prometheus metrics contain illegal character sequence \'

### ISSUE THREAD

**Issue by browcio** [ClickHouse/ClickHouse#10571]
**Describe the bug**
According to https://github.com/prometheus/common/blob/master/expfmt/text_parse.go#L561
`\'` is not recognized escape sequence but it is present in metrics exposed for prometheus:
```
# HELP ClickHouseProfileEvents_Seek Number of times the \'lseek\' function was called.
```
This line breaks applications using official parser (my case: https://github.com/influxdata/telegraf/issues/7423)

**How to reproduce**
* Which ClickHouse server version to use 20.3.8.53

**Comment by fzyzcjy** [comment]
Hi I have the same problem. Is there any updates? Thanks! @filimonov

**Comment by alexey-milovidov** [comment]
Fixed long time ago.
