### ISSUE TITLE
Server display name not updated on client reconnect

### ISSUE THREAD

**Issue by akuzm** [ClickHouse/ClickHouse#10577]
I have two servers, #4 and #2, and I can run one of them localhost:9000. First, I run #4 and connect to it with clickhouse-client. I verify that it is indeed the #4 server from the build option that mentions the corresponding directory:
```
/4/ :) select * from system.build_options where name = 'BUILD_INCLUDE_DIRECTORIES'

┌─name──────────────────────┬─value───────────────────────────────────────────┐
│ BUILD_INCLUDE_DIRECTORIES │ /home/akuzm/ch4/build-gcc9-rel/includes/configs │
└───────────────────────────┴─────────────────────────────────────────────────┘
```

Then, I kill #4 and start #2 instead, on the same port. I keep the client and run the same query from it -- it runs OK. Apparently it reconnected to #2, but the prompt is still from #4
```
/4/ :) select * from system.build_options where name = 'BUILD_INCLUDE_DIRECTORIES'

┌─name──────────────────────┬─value───────────────────────────────────────────┐
│ BUILD_INCLUDE_DIRECTORIES │ /home/akuzm/ch2/build-gcc9-rel/includes/configs │
└───────────────────────────┴─────────────────────────────────────────────────┘
```

I'm not sure that it its a good idea in general to reconnect silently like this. IIRC clickhouse-client stores the session variables so we'll have some continuity over the reconnect, but it might be a completely different server that we've connected to, so who knows what can break.

**Comment by filimonov** [comment]
I think the only safe option to reconnect is to reuse the previosly created session (which should support that, like for http).

It should not reconnect silenly in any other scenarios, as you can in between of some  sequence of DDLs, like 
```
create new_table as select * from old
-- Do some checks
Drop old table 
```

If you will reconnect just after the checks you will drop old table w/o copying its data. 

It can have temporary tables etc.

**Comment by filimonov** [comment]
Today faced the similar - after updating/restarting the server (to version 20.5.1) get back to some old clickhouse-client session, and error message had 'Received exception from server (version 20.4.1):' which is misleading.

**Comment by spanningwings** [comment]
This sounds like a tricky issue in that the correct behavior seems to disconnect all the clients when the server is gone. Like you pointed out, server #2 should not continue serving all the client requests that are meant for server #4.  However, I suspect users would like to keep the behavior as-is for convenience reasons. 

There are two ways to solve it. One way is to be strict and all the stale clients will not be able to talk to the new servers listening to the same port. The other way is to provide an option to give users some options to say whether they want to allow this behavior and be bug-to-bug compatible.
