### ISSUE TITLE
Data duplication In ClickHouse Kafka engine table

### ISSUE THREAD

**Issue by ZhangchengHu0923** [ClickHouse/ClickHouse#10573]
As far as I know：
1、when the two data primary keys are the same, ClickHouse may retain them for a period of time. 
2、When Kafka auto commit is used, when Kafka consumer is restarted, data may be subscribed more than once. 

I guess “ClickHouse Kafka engine tables” maintain their own kafka Consumers to subscribe the data of kafka，and the consumers may restarted by themselfs, and I don't know it at all, which could data duplication.

Is my guess correct, how to avoid this data duplication problem.

**Comment by den-crane** [comment]
1. This statement is valid for only for some engines.
2. CH does not use ` Kafka auto commit `.

What ClickHouse version do you use?

**Comment by ZhangchengHu0923** [comment]
if needed, I will use latest version of CH, some data of CH come from kafka, and I dont know weather "CH kafka engine table" ganrantee the exactly-once  semantics

**Comment by ZhangchengHu0923** [comment]
Of course, we do not consider the duplication of Kafka ’s own data

**Comment by robot-clickhouse** [comment]
@ZhangchengHu0923, do you have any further questions?

**Comment by filimonov** [comment]
Currenlty engine=Kafka provides at-least-once guarnatee. In some corner cases you can get duplicates. Improvements in that part are planned (no concrete date).
