### ISSUE TITLE
arrayJoin() uses too much memory

### ISSUE THREAD

**Issue by user919lx** [ClickHouse/ClickHouse#10590]
I have a table with an array type column ,and want to explode it.
Before that,I do a subquery to make dataset smaller.

Table DDL like that:
```
CREATE TABLE t (
  `id` Int32 ,
  `array_column` Array(String) ,
  `dt` Date ,
) ENGINE = MergeTree PARTITION BY dt ORDER BY id SETTINGS index_granularity = 8192
```

The SQL is bellow:
```
select *,arrayJoin(array_column) from (
    SELECT * FROM t
    WHERE condition
)
```

And then receive an error:
```
ClickHouse exception, code: 241, host: {hostname}, port: {port]; Code: 241, e.displayText() = DB::Exception: Memory limit (for query) exceeded: would use 20.19 GiB (attempt to allocate chunk of 4297064448 bytes), maximum: 18.63 GiB: 
Code: 241, e.displayText() = DB::Exception: Memory limit (for query) exceeded: would use 32.11 GiB (attempt to allocate chunk of 17179869184 bytes), maximum: 18.63 GiB (version 19.17.4.11 (official build)) (version 19.17.4.11 (official build))
```

I know that means the data is too large.However, when I add limit to subquery ,even though limit size is larger much then subquery result size,the SQL still can work well. New SQL is like that:
```
select *,arrayJoin(array_column) from (
    SELECT * FROM t 
    WHERE condition limit 10000000000000000
)
```

env desc:
- Clickhouse version:  19.17.4.11
- Memory limit: 18G
- array_column avg length: 250
- subquery result size: 200,000

I don't find out how to explain Clickhouse sql, but I guess sql query optimizer executes arrayJoin first,and then do subquery's where clause to filter result. Target table is too large without where clause,so memory limit exceeded . But if add limit ,Clickhouse will execute subquery first,and then execute arrayJoin.Subquery result is much smaller,so I can execute it to get a result.

Maybe this is a bug?

**Comment by den-crane** [comment]
Try `set max_threads=1`

Probably it just not enough memory for `select *` in many threads with max_blocks_size=65536
and limit reduces the number of blocks then number or threads

**Comment by 4ertus2** [comment]
It's not clear how much memory uses each query. I.e. first one could need 18.5G and second one needs 17.5G. Could ypu create a sample with smaller data set that would successed for both queries and show max memory usage and spent time for them?
