### ISSUE TITLE
Documentation site not working correctly

### ISSUE THREAD

**Issue by ceyhunkerti** [ClickHouse/ClickHouse#10602]
Clicking on nav. items not working

![image](https://user-images.githubusercontent.com/6328046/80727896-f685fa80-8b0e-11ea-98d9-72706c8494e1.png)

**Comment by BayoNet** [comment]
@blinkov In production I don't see such behavior, but I see it when building locally. Left TOC bar and lang switcher doesn't work.

**Comment by blinkov** [comment]
@ceyhunkerti afaik this issue has already been fixed a while ago. Could you try again to see if it still affects you?
