### ISSUE TITLE
KPIs and metrics of ClickHouse community

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#10616]
**Preface**

We don't calculate any metrics and KPIs systematically. We only do it occasionally.
This task is needed if we want to start doing that, but now we just collect the list of possible metrics and for some of them (if available in public) we can provide direct links.

All metrics should be presented with graph over time.
We're not going to optimize for any metrics or to focus on them specifically.

**GitHub repo:**

Number of stars. Number of issues and pull requests. Number of opened/closed issues and pull requests. Total number of contributors. Number of unique authors for issues and pull requests. Distribution of top authors by issues/pull requests. The impact of top contributors. Ratio of external/internal pull requests by number and by diff size. Distribution of pull requests by their types: code / documentation and website / build infrastructure. Distribution of pull requests by diff size. Distribution of number of comments in issues. Number of open issues without any comments. Resolution time. Time to first comment. Distribution of issues by types (labels) and resultion status (fixed, won't fix). The number of forks. The number of third-party GitHub repositories related to ClickHouse. Cumulative number of their stars. Codesearch for the code borrowed from ClickHouse.

**Social media:**

Number of mentions in comments on Hackers News, Twitter, third-party Telegram chats, Facebook (available with YouScan). Google trends comparisons. The number of people on LinkedIn with mentions. The number of jobs on LinkedIn and hh.ru. The number of YouTube videos mentioning ClickHouse. The number of events on Meetup.com and Eventbrite with mentions.

**Telegram chats:**

Number of messages in Telegram chats. Number of unique and new authors in Telegram chats. Total number of users in Telegram chat. Distribution of top users by the number of messages.

**Specialized comparisons:**

DB-Engines ranking: total / across relational DBMS.

**Website:**

Amount of traffic (unique visitors and visits), distribution by countries; referrals. We alrady have this stat thanks to Yandex.Metrica.
The number of feedback emails.

**Comment by alexey-milovidov** [comment]
Pull request approvals:https://gh-api.clickhouse.tech/play?user=play#U0VMRUNUIGFjdG9yX2xvZ2luLCBjb3VudCgpIEFTIGMgRlJPTSBnaXRodWJfZXZlbnRzIApXSEVSRSByZXBvX25hbWUgSU4gKCd5YW5kZXgvQ2xpY2tIb3VzZScsICdDbGlja0hvdXNlL0NsaWNrSG91c2UnKSAKICBBTkQgZXZlbnRfdHlwZSA9ICdQdWxsUmVxdWVzdFJldmlld0V2ZW50JwogIEFORCByZXZpZXdfc3RhdGUgPSAnYXBwcm92ZWQnCiAgQU5EIGFjdG9yX2xvZ2luIE5PVCBJTiAoJ3JvYm90LWNsaWNraG91c2UnLCAnZGVwZW5kYWJvdC1wcmV2aWV3W2JvdF0nLCAnaW1nYm90W2JvdF0nKQogIEFORCBhdXRob3JfYXNzb2NpYXRpb24gSU4gKCdNRU1CRVInLCAnQ09OVFJJQlVUT1InKQogIEFORCBjcmVhdGVkX2F0ID49IHRvZGF5KCkgLSA5MApHUk9VUCBCWSBhY3Rvcl9sb2dpbiBPUkRFUiBCWSBjIERFU0M=

**Comment by alexey-milovidov** [comment]
Issue comments:

https://gh-api.clickhouse.tech/play?user=play#U0VMRUNUIGFjdG9yX2xvZ2luLCBjb3VudCgpIEFTIGMgRlJPTSBnaXRodWJfZXZlbnRzIApXSEVSRSByZXBvX25hbWUgSU4gKCd5YW5kZXgvQ2xpY2tIb3VzZScsICdDbGlja0hvdXNlL0NsaWNrSG91c2UnKSAKICBBTkQgZXZlbnRfdHlwZSA9ICdJc3N1ZUNvbW1lbnRFdmVudCcKICBBTkQgYWN0b3JfbG9naW4gTk9UIExJS0UgJ3JvYm90LSUnIEFORCBhY3Rvcl9sb2dpbiBOT1QgTElLRSAnJVtib3RdJwotLSAgQU5EIGNyZWF0ZWRfYXQgPj0gdG9kYXkoKSAtIDkwCkdST1VQIEJZIGFjdG9yX2xvZ2luIE9SREVSIEJZIGMgREVTQw==

**Comment by alexey-milovidov** [comment]
Authors involved in discussions, by months:

https://gh-api.clickhouse.tech/play?user=play#U0VMRUNUIHRvU3RhcnRPZk1vbnRoKGNyZWF0ZWRfYXQpIEFTIGRhdGUsIGNvdW50KCksIHVuaXEoYWN0b3JfbG9naW4pIEFTIHUsIGJhcih1LCAwLCAxMDAwLCAxMDApIEZST00gZ2l0aHViX2V2ZW50cyAKV0hFUkUgcmVwb19uYW1lIElOICgneWFuZGV4L0NsaWNrSG91c2UnLCAnQ2xpY2tIb3VzZS9DbGlja0hvdXNlJykgCiAgQU5EIGV2ZW50X3R5cGUgPSAnSXNzdWVDb21tZW50RXZlbnQnCiAgQU5EIGFjdG9yX2xvZ2luIE5PVCBMSUtFICdyb2JvdC0lJyBBTkQgYWN0b3JfbG9naW4gTk9UIExJS0UgJyVbYm90XScKR1JPVVAgQlkgZGF0ZSBPUkRFUiBCWSBkYXRl

**Comment by alexey-milovidov** [comment]
Number of active contributors per month:

https://gh-api.clickhouse.tech/play?user=play#U0VMRUNUIHRvU3RhcnRPZk1vbnRoKGNyZWF0ZWRfYXQpIEFTIGRhdGUsIGNvdW50KCksIHVuaXEoYWN0b3JfbG9naW4pIEFTIHUsIGJhcih1LCAwLCAyMDAsIDEwMCkgRlJPTSBnaXRodWJfZXZlbnRzIApXSEVSRSByZXBvX25hbWUgSU4gKCd5YW5kZXgvQ2xpY2tIb3VzZScsICdDbGlja0hvdXNlL0NsaWNrSG91c2UnKSAKICBBTkQgZXZlbnRfdHlwZSA9ICdQdWxsUmVxdWVzdEV2ZW50JyBBTkQgYWN0aW9uID0gJ29wZW5lZCcKICBBTkQgYWN0b3JfbG9naW4gTk9UIExJS0UgJ3JvYm90LSUnIEFORCBhY3Rvcl9sb2dpbiBOT1QgTElLRSAnJVtib3RdJwpHUk9VUCBCWSBkYXRlIE9SREVSIEJZIGRhdGU=

**Comment by alexey-milovidov** [comment]
New stars per month:

https://gh-api.clickhouse.tech/play?user=play#U0VMRUNUIHRvU3RhcnRPZk1vbnRoKGNyZWF0ZWRfYXQpIEFTIGRhdGUsIGNvdW50KCkgQVMgYywgYmFyKGMsIDAsIDIwMDAsIDEwMCkgRlJPTSBnaXRodWJfZXZlbnRzIApXSEVSRSByZXBvX25hbWUgSU4gKCd5YW5kZXgvQ2xpY2tIb3VzZScsICdDbGlja0hvdXNlL0NsaWNrSG91c2UnKSAKICBBTkQgZXZlbnRfdHlwZSA9ICdXYXRjaEV2ZW50JwpHUk9VUCBCWSBkYXRlIE9SREVSIEJZIGRhdGU=

**Comment by alexey-milovidov** [comment]
Forks per month:

https://gh-api.clickhouse.tech/play?user=play#U0VMRUNUIHRvU3RhcnRPZk1vbnRoKGNyZWF0ZWRfYXQpIEFTIGRhdGUsIGNvdW50KCkgQVMgYywgYmFyKGMsIDAsIDIwMCwgMTAwKSBGUk9NIGdpdGh1Yl9ldmVudHMgCldIRVJFIHJlcG9fbmFtZSBJTiAoJ3lhbmRleC9DbGlja0hvdXNlJywgJ0NsaWNrSG91c2UvQ2xpY2tIb3VzZScpIAogIEFORCBldmVudF90eXBlID0gJ0ZvcmtFdmVudCcKR1JPVVAgQlkgZGF0ZSBPUkRFUiBCWSBkYXRl

**Comment by alexey-milovidov** [comment]
Approved PRs by week:

https://gh-api.clickhouse.tech/play?user=play#U0VMRUNUIHRvTW9uZGF5KGNyZWF0ZWRfYXQpIEFTIGRhdGUsIGNvdW50KCkgQVMgYywgYmFyKGMsIDAsIDUwMCwgMTAwKSBGUk9NIGdpdGh1Yl9ldmVudHMgCldIRVJFIHJlcG9fbmFtZSBJTiAoJ3lhbmRleC9DbGlja0hvdXNlJywgJ0NsaWNrSG91c2UvQ2xpY2tIb3VzZScpIAogIEFORCBldmVudF90eXBlID0gJ1B1bGxSZXF1ZXN0UmV2aWV3RXZlbnQnCiAgQU5EIHJldmlld19zdGF0ZSA9ICdhcHByb3ZlZCcKR1JPVVAgQlkgZGF0ZSBPUkRFUiBCWSBkYXRl

**Comment by alexey-milovidov** [comment]
Opened PRs per month:

https://gh-api.clickhouse.tech/play?user=play#U0VMRUNUIHRvU3RhcnRPZk1vbnRoKGNyZWF0ZWRfYXQpIEFTIGRhdGUsIGNvdW50KCkgQVMgYywgYmFyKGMsIDAsIDIwMDAsIDEwMCkgRlJPTSBnaXRodWJfZXZlbnRzIApXSEVSRSByZXBvX25hbWUgSU4gKCd5YW5kZXgvQ2xpY2tIb3VzZScsICdDbGlja0hvdXNlL0NsaWNrSG91c2UnKSAKICBBTkQgZXZlbnRfdHlwZSA9ICdQdWxsUmVxdWVzdEV2ZW50JyBBTkQgYWN0aW9uID0gJ29wZW5lZCcKR1JPVVAgQlkgZGF0ZSBPUkRFUiBCWSBkYXRl

**Comment by alexey-milovidov** [comment]
https://clickhousebootcamp.grafana.net/goto/vzGFy5Inz?orgId=1

**Comment by alexey-milovidov** [comment]
ClickHouse ranking by growth across GitHub repositories: https://gh-api.clickhouse.tech/play?user=play#U0VMRUNUIHJvd19udW1iZXIoKSBPVkVSIChPUkRFUiBCWSBzdGFycyBERVNDKSBBUyByYW5rLCByZXBvX25hbWUsIHN0YXJzCkZST00KKAogICAgU0VMRUNUIHJlcG9fbmFtZSwgY291bnQoKSBBUyBzdGFycwogICAgRlJPTSBnaXRodWJfZXZlbnRzCiAgICBXSEVSRSBldmVudF90eXBlID0gJ1dhdGNoRXZlbnQnIEFORCBjcmVhdGVkX2F0ID49ICcyMDIxLTAxLTAxJwogICAgR1JPVVAgQlkgcmVwb19uYW1lCiAgICBPUkRFUiBCWSBjb3VudCgpIERFU0MgTElNSVQgMTAwMAop

**Comment by alexey-milovidov** [comment]
Ranking by median daily stars since 2021:
https://gh-api.clickhouse.tech/play?user=play#U0VMRUNUIHJvd19udW1iZXIoKSBPVkVSIChPUkRFUiBCWSBtZWRpYW5fZGFpbHlfc3RhcnMgREVTQykgQVMgcmFuaywgcmVwb19uYW1lLCBtZWRpYW5fZGFpbHlfc3RhcnMKRlJPTQooCiAgICBTRUxFQ1QgcmVwb19uYW1lLCBtZWRpYW5FeGFjdChzdGFycykgQVMgbWVkaWFuX2RhaWx5X3N0YXJzIEZST00KICAgICgKICAgICAgICBTRUxFQ1QgcmVwb19uYW1lLCB0b0RhdGUoY3JlYXRlZF9hdCkgQVMgZGF0ZSwgY291bnQoKSBBUyBzdGFycyAKICAgICAgICBGUk9NIGdpdGh1Yl9ldmVudHMKICAgICAgICBXSEVSRSBldmVudF90eXBlID0gJ1dhdGNoRXZlbnQnIEFORCBjcmVhdGVkX2F0ID49ICcyMDIxLTAxLTAxJwogICAgICAgICAgICBBTkQgcmVwb19uYW1lIElOCiAgICAgICAgICAgICgKICAgICAgICAgICAgICAgIFNFTEVDVCByZXBvX25hbWUKICAgICAgICAgICAgICAgIEZST00gZ2l0aHViX2V2ZW50cwogICAgICAgICAgICAgICAgV0hFUkUgZXZlbnRfdHlwZSA9ICdXYXRjaEV2ZW50JyBBTkQgY3JlYXRlZF9hdCA+PSAnMjAyMS0wMS0wMScKICAgICAgICAgICAgICAgIEdST1VQIEJZIHJlcG9fbmFtZQogICAgICAgICAgICAgICAgT1JERVIgQlkgY291bnQoKSBERVNDIExJTUlUIDEwMDAwCiAgICAgICAgICAgICkKICAgICAgICBHUk9VUCBCWSByZXBvX25hbWUsIGRhdGUKICAgICkKICAgIEdST1VQIEJZIHJlcG9fbmFtZSAKICAgIEhBVklORyBhbnlJZihzdGFycywgZGF0ZSA9ICcyMDIxLTAxLTAxJykgPiAwIEFORCBhbnlJZihzdGFycywgZGF0ZSA9ICcyMDIxLTA5LTAxJykgPiAwCiAgICBPUkRFUiBCWSBtZWRpYW5fZGFpbHlfc3RhcnMgREVTQwogICAgTElNSVQgMTAwMAop

**Comment by alexey-milovidov** [comment]
Google Trends: https://trends.google.com/trends/explore?date=today%205-y&q=Greenplum,ClickHouse,SingleStore

(difficult to use for non-unique terms)

**Comment by den-crane** [comment]
https://trends.google.com/trends/explore?date=all&q=ClickHouse,vertica

**Comment by alexey-milovidov** [comment]
Monthly median of unique daily active committers (approximation of ClickHouse core team size):

https://gh-api.clickhouse.com/play?user=play#U0VMRUNUIHRvU3RhcnRPZk1vbnRoKGQpIEFTIG1vbnRoLCBtZWRpYW4odSkgRlJPTSAoU0VMRUNUIHRpbWU6OkRhdGUgQVMgZCwgdW5pcShhdXRob3IpIEFTIHUgRlJPTSBnaXRfY2xpY2tob3VzZS5jb21taXRzIEdST1VQIEJZIGQgT1JERVIgQlkgZCkgR1JPVVAgQlkgbW9udGggT1JERVIgQlkgbW9udGg=

**Comment by tisonkun** [comment]
Hi @alexey-milovidov,

Thanks for this excellent work! I'm happy to exploring statistics on communities I participant in.

Apart from the website UI, I wonder if there is a programming interface to retrieve this data? The website UI is good for exploring and adhoc querying but for setting up a dashboard a programming interface would be great to use.

**Comment by alexey-milovidov** [comment]
@tisonkun It is ClickHouse Playground: https://clickhouse.com/docs/en/getting-started/playground/
