### ISSUE TITLE
How kafka_skip_broken_messages should works

### ISSUE THREAD

**Issue by preved911** [ClickHouse/ClickHouse#10647]
I try use kafka for write messages to clickhouse. I am creating consumer like this:
```
CREATE TABLE queue (
  timestamp UInt64,
  level String,
  message String
) ENGINE = Kafka()
  SETTINGS
    kafka_broker_list = 'kafka-kafka-bootstrap:9092',
    kafka_topic_list = 'events',
    kafka_group_name = 'clickhouse',
    kafka_format = 'JSONEachRow',
    kafka_skip_broken_messages = 1,
    kafka_row_delimiter = '\n';
````
Then I write messages to kafka over `kafka-console-producer.sh`. It's work ok when message format is a valid json. But if I am sending invalid json to kafka, clickhouse will show me exception and finish receiving any new messages.
Didn't `kafka_skip_broken_messages = 1` should ignore this situation and continue consume from kafka?

**Comment by filimonov** [comment]
Currently, it is not very intuitive. It is not an on/off flag, but maximum number of broken messages per block. Size of the block depends on kafka_max_block_size, poll_interval, and number of messages currently available in the topic.  

That feature will be redesigned (i hope soon). It will just have an `_error` virtual column instead.

**Comment by preved911** [comment]
I can't understand how configure consumer right now, because after JSONEachRow is causing exception, it is not continue getting messages from kafka. It is a bug? Should I create issue?

**Comment by filimonov** [comment]
JSONEachRow support only some special type of the JSONs. When whole JSON object is in the single line.

**Comment by preved911** [comment]
So, I should use another `kafka_format` for to avoid this error? Which format's you can to recommend for my case?

**Comment by filimonov** [comment]
Check that: https://www.altinity.com/blog/clickhouse-kafka-engine-faq

**Comment by RO-29** [comment]
I am facing the same issue, the Kafka engine consumer is just trying to parse the faulty message in the loop despite me having configured `kafka_skip_broken_messages` 

It's not processing new messages at all

```
ENGINE = Kafka SETTINGS kafka_broker_list = 'localhost:9092',
kafka_topic_list = 'events',
kafka_group_name = 'group1',
kafka_format = 'JSONEachRow',
kafka_num_consumers = 1,
kafka_skip_broken_messages = 100,
kafka_max_block_size = 100;
```

**Comment by gopala000** [comment]
I have related question to make ingestion resilient to faults [parsing error](https://stackoverflow.com/questions/63841020/clickhouse-kafka-engine-how-to-move-messages-with-parsing-error-to-a-different)

Hope the issues related to fault handling is addressed soon.
