### ISSUE TITLE
Disable merges for a volume

### ISSUE THREAD

**Issue by alex-zaitsev** [ClickHouse/ClickHouse#10650]
**Use case**

With multi-tier configuration, it should be possible to disable merges for slow volumes.

**Describe the solution you'd like**

1. Extend current 'stop merges' syntax:

```
SYSTEM START|STOP MERGES [ON <volume>]
```

2. Add a setting to volume configuration to disable merges:

```
<volumes>
  <cold>
    <disable_merges>1</disable_merges>
    <disk> ...
```

**Comment by den-crane** [comment]
implemented

**Comment by Slach** [comment]
=( `prefer_not_to_merge` is proper name for this
