### ISSUE TITLE
Error converting UInt64 column (of nanoseconds since epoch) to DateTime64(9)

### ISSUE THREAD

**Issue by mdelvecchio-wasabi** [ClickHouse/ClickHouse#10661]
Our ClickHouse schema has a DateTime column, with the standard 1-second precision.  We then added a DateTimeNS column, which has nanosecond precision:

```
CREATE TABLE db.table (
   ...
  `EndTime` DateTime,
  `EndTimeNS` UInt64,
   ...
```

The EndTimeNS column contains the number of nanoseconds since the epoch.

I am trying to convert the EndTimeNS column into the DateTime64(9) type.  But when I do so, I get an error:

```
ALTER TABLE db.table
    MODIFY COLUMN 
    `EndTimeNS` DateTime64(9)


Received exception from server (version 20.3.5):
Code: 407. DB::Exception: Received from localhost:9000. DB::Exception: DateTime64 convert overflow. 
```

Am I on the right track here?  Is it possible to convert the UInt64 column to DateTime64(9)?  And if so, how?

Is this just a side-effect of https://github.com/ClickHouse/ClickHouse/issues/9786?

Thanks.

**Comment by den-crane** [comment]
the only way is
```

ALTER TABLE db.table add COLUMN `EndTimeNS1` DateTime64(9) default cast(substr(toString(EndTimeNS), 1, 10) ||'.'|| substr(toString(EndTimeNS), 11, 9), 'DateTime64(9)');
alter table db.table update EndTimeNS1 = EndTimeNS1;
alter table db.table rename column EndTimeNS to EndTimeNS_old;
alter table db.table rename column EndTimeNS1 to EndTimeNS;
```

**Comment by mdelvecchio-wasabi** [comment]
Is it possible that this could change?

I guess I am asking if a DateTime64(9) is stored on disk in the same way as my UInt64 "nanoseconds since the epoch" column is.  I believe they are both 64-bit counts of nanoseconds since the epoch.

Is the above necessary because of the bug described in https://github.com/ClickHouse/ClickHouse/issues/9786?  Or is there a fundamental difference that would make it impossible to change the type without effectively creating a new column?

Thanks.

**Comment by den-crane** [comment]
Yes, it's related to  #9786. But now I have doubts that  #9786. It seems that is expected behaviour.

**Comment by den-crane** [comment]
>Is it possible that this could change?

it seems it will not  https://github.com/ClickHouse/ClickHouse/issues/10672
