### ISSUE TITLE
More functions for DateTime64

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#10672]
1) toStartOfSecond - return DateTime64 rounded (floor) to seconds. UPD: implemented #10722
2) cast from DateTime64 to epoch milli microseconds and back. We can make something similar to existing in [bigquery](https://cloud.google.com/bigquery/docs/reference/standard-sql/timestamp_functions)
- UNIX_MICROS  / TIMESTAMP_MICROS 
- UNIX_MILLIS / TIMESTAMP_MILLIS 
UPD: implemented #10923
3) cast from DateTime64 to UInt64 (as stored internally) and back - reinterpretAs... ?

**Comment by alex-zaitsev** [comment]
Let's add those functions for UInt64 <-> DateTime64 conversion:
toUnixTimeMillies
fromUnixTimeMillies

**Comment by Dexig** [comment]
Hello. 
You can add support for the **toStartOf** family of functions for **DateTime64**.
Because if you use these functions with **DateTime64** now, then there is an implicit conversion to just **DateTime**.

**Comment by alexey-milovidov** [comment]
The reinterpret has been implemented:
```
SELECT reinterpret(now64(3), 'UInt64')
```

**Comment by alexey-milovidov** [comment]
As all three points were implemented, I will close this task.

@Dexig

> You can add support for the toStartOf family of functions for DateTime64?
Because if you use these functions with DateTime64 now, then there is an implicit conversion to just DateTime.

This is not part of this task, you should create another feature request for that.

**Comment by filimonov** [comment]
Thanks!
