### ISSUE TITLE
Unable to upgrade from 19.17 to 20.x

### ISSUE THREAD

**Issue by oik741** [ClickHouse/ClickHouse#10676]
Hi guys! I've got v19.17 and planning to migrate to 20.3
but I can't do that because of this bug: https://github.com/ClickHouse/ClickHouse/pull/9412
and if I understand correctly I can't roll back due to https://github.com/ClickHouse/ClickHouse/blob/master/docs/en/whats-new/changelog/2019.md#backward-incompatible-change-backward-incompatible-change

Since this fix all branches was released except 19.17, is this branch reached EOL? Do you have plans to release it?

**Comment by 4ertus2** [comment]
The setting that was needed for roll back to 19.16 has been backported. So it should be possible to downgrade to 19.16 and upgrade to newer version. https://github.com/ClickHouse/ClickHouse/blob/19.16/dbms/src/Core/Settings.h#L383
