### ISSUE TITLE
UInt16" is greater than max allowed Date value

### ISSUE THREAD

**Issue by Crazylearner30** [ClickHouse/ClickHouse#10673]
Hi, can someone quickly clarify what error is this?

I tried loading Parquet file into table i have not used UInt16 data type anywhere in the table but getting the below error

ERROR:  Input value 4294941729 of a column "UInt16" is greater than max allowed Date value, which is 49710

**Comment by alexey-milovidov** [comment]
It looks like you are importing some column from Parquet into Date type in ClickHouse.
Date type is represented by UInt16 containing the number of days since 1970-01-01.
But in Parquet file you have some big number (4294941729) or negative number (-25566) instead.

**Comment by Crazylearner30** [comment]
Yes!! we were using a wrong date 1900-01-01.

We changed it and its working fine.
