### ISSUE TITLE
Parquet files generated in hive has missing columns after downloading the files to ClickHouse server

### ISSUE THREAD

**Issue by Crazylearner30** [ClickHouse/ClickHouse#10680]
Hi,

Please help me with the below issue 

**Issue:**  Parquet files generated in hive has missing columns after downloading the files to ClickHouse server.
  But when i created table in athena using the same files(downloaded to ClickHouse ) I could see all the columns present.
ClickHouse client version 20.1.11.73.

**Comment by 4ertus2** [comment]
Do you have a sample file? Columns of which type are missed?

**Comment by filimonov** [comment]
We need details to be able to help you. Schemas on both end for example

**Comment by Crazylearner30** [comment]
Parquet file generated in hive have the below schema 

Create table test
(
id BigInt,
company String,
Email String,
Date1 String,
Date2 String
)

Destination table in clickhouse have the below schema

create table temp
(
id UInt64,
Company String,
Email String,
Date1 Date,
Date2 Date
ENGINE = MergeTree

Table created in Athena has all the columns 
When i downloaded the files in clickhouse and tried to load it into the temp table its throwing an exception saying company and email columns are missing from the input file.

**Comment by filimonov** [comment]
Can you create a parquet files with just a few rows which are failing during import and zip / attach them here?

**Comment by Crazylearner30** [comment]
Hi,  I am attaching the sample failing data here 

Note: Schema given above is not the exact Schema we have used its just the example.
Let me know if i have to send the schema privately if required for further investigation.

[Failing_data.zip](https://github.com/ClickHouse/ClickHouse/files/4592048/Failing_data.zip)

**Comment by Crazylearner30** [comment]
Hi Any updates here ?

**Comment by robot-clickhouse** [comment]
@Crazylearner30, do you have any further questions?

**Comment by Algunenano** [comment]
Current exception:
```
SELECT *
FROM file('/tmp/Failing_data.parquet')

Query id: 07eeb3d9-9838-444a-8ed3-53e049eb3c60


Elapsed: 0.008 sec. 

Received exception:
Code: 636. DB::Exception: Cannot extract table structure from Parquet format file. Error: std::exception. Code: 1001, type: parquet::ParquetInvalidOrCorruptedFileException, e.what() = Invalid: Parquet magic bytes not found in footer. Either the file is corrupted or this is not a parquet file. (version 23.11.1.1). You can specify the structure manually: (in file/uri /tmp/Failing_data.parquet). (CANNOT_EXTRACT_TABLE_STRUCTURE)
 ```

Same with pyarrow:
```
>>> import pyarrow.parquet as pq
>>> table2 = pq.read_table('/tmp/Failing_data.pq')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.11/site-packages/pyarrow/parquet/core.py", line 2955, in read_table
    dataset = _ParquetDatasetV2(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pyarrow/parquet/core.py", line 2495, in __init__
    [fragment], schema=schema or fragment.physical_schema,
                                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow/_dataset.pyx", line 1357, in pyarrow._dataset.Fragment.physical_schema.__get__
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Could not open Parquet input source '/tmp/Failing_data.pq': Parquet magic bytes not found in footer. Either the file is corrupted or this is not a parquet file.
```

Same for duckdb:
```
./duckdb 
v0.9.1 401c8061c6
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D Select * from 'Failing_data.parquet' ;
Error: Invalid Input Error: No magic bytes found at end of file 'Failing_data.parquet'
```

It seems it was a problem in the generator.
