### ISSUE TITLE
Optimize data on INSERT

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#10683]
This feature was suggested on recent ClickHouse Meetup Online on April 2.

Add a setting `optimize_on_insert`. When enabled, do the same transformation for INSERTed block of data as if merge was done on this block (e.g. Replacing, Collapsing, Aggregating...).

Example:

Current behaviour:
```
CREATE TABLE merge (x String) ENGINE = ReplacingMergeTree ORDER BY x
INSERT INTO merge VALUES ('Hello'), ('Hello')
SELECT * FROM merge

┌─x─────┐
│ Hello │
│ Hello │
└───────┘
```

With this setting enabled:
```
CREATE TABLE merge (x String) ENGINE = ReplacingMergeTree ORDER BY x
INSERT INTO merge VALUES ('Hello'), ('Hello')
SELECT * FROM merge

┌─x─────┐
│ Hello │
└───────┘
```

I'd say that the transformation is very cheap comparing to INSERT query and the setting can be enabled by default.

**Comment by naorlov** [comment]
@alexey-milovidov I want to do this task

**Comment by alexey-milovidov** [comment]
@naorlov How is it going, btw?

**Comment by pod2metra** [comment]
Hello, What's about this task? Do you have any progress?

**Comment by alexey-milovidov** [comment]
The progress just started, @Avogar is doing this task.
