### ISSUE TITLE
Add a setting 'input_format_enum_as_number'

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#10682]
**Use case**
https://github.com/ClickHouse/ClickHouse/issues/7971

**Comment by alexey-milovidov** [comment]
We can recognize numbers and check for symbolic values if the value is not a number.
It can be done even automatically without any settings if the Enum type does not have any symbolic values that can be ambiguously parsed as numbers.

**Comment by pavigor** [comment]
Will this setting added in the near future?

**Comment by alexey-milovidov** [comment]
This task is on hold. It's easy to implement, it's open to take for community members.
If you are interested implementing this, there is a green light, we will help to review as quick as possible.

**Comment by vivarum** [comment]
https://github.com/ClickHouse/ClickHouse/pull/15685

**Comment by ucasFL** [comment]
This task has been done in [#15685](https://github.com/ClickHouse/ClickHouse/pull/15685) @alexey-milovidov
