### ISSUE TITLE
Database xxx doesn't exist

### ISSUE THREAD

**Issue by IcefireCgrbza** [ClickHouse/ClickHouse#10692]
My application consume kafka and insert data into clickhouse distribute table using http client, it works well normaly, but sometimes it will reports error, I log clickhouse http response body, it looks like: 
Code: 81, e.displayText() = DB::Exception: Received from xxx. DB::Exception: Database xxx doesn't exist. (version 19.11.8.46)
The error continued for about 5 minutes and will auto recover.
why it happens?

**Comment by AlexanderJLiu** [comment]
Do you insert data to multiple clickhouse instances or just one?
Is the distributed table located in this `Database`?
Is the local table of distributed located in this `Database`?

**Comment by den-crane** [comment]
Do you use circle replication? 
Can you show clickhouse server logs with this error?
