### ISSUE TITLE
clickhouse 19.17.4.11 type: std::bad_alloc

### ISSUE THREAD

**Issue by testlujing** [ClickHouse/ClickHouse#10693]
when i insert data to clickhosue table(ReplacingMergeTree)

error is:
```
2020.05.06 17:09:35.123072 [ 77 ] {0499ac89-211e-4a30-9b0e-627e722f74ab} <Debug> DiskSpaceMonitor: Reserving 1.00 MiB on disk `default`, having unreserved 5.48 TiB.
2020.05.06 17:09:35.126157 [ 77 ] {0499ac89-211e-4a30-9b0e-627e722f74ab} <Debug> MemoryTracker: Peak memory usage (total): 32.20 MiB.
2020.05.06 17:09:35.126189 [ 77 ] {0499ac89-211e-4a30-9b0e-627e722f74ab} <Debug> MemoryTracker: Peak memory usage (for query): 32.20 MiB.
2020.05.06 17:09:35.126216 [ 77 ] {0499ac89-211e-4a30-9b0e-627e722f74ab} <Error> HTTPHandler: std::exception. Code: 1001, type: std::bad_alloc, e.what() = std::bad_alloc, version = 19.17.4.11
2020.05.06 17:09:38.093758 [ 4 ] {} <Trace> SystemLog (system.trace_log): Flushing system log
2020.05.06 17:09:38.093954 [ 4 ] {} <Debug> DiskSpaceMonitor: Reserving 1.00 MiB on disk `default`, having unreserved 5.48 TiB.
2020.05.06 17:09:38.094530 [ 4 ] {} <Error> void DB::SystemLog<LogElement>::flushImpl(DB::SystemLog<LogElement>::EntryType) [with LogElement = DB::TraceLogElement]: Code: 173, e.displayText() = DB::ErrnoException: Allocator: Cannot malloc 1.00 MiB., errno: 12, strerror:
 Cannot allocate memory, Stack trace:
```

**Comment by filimonov** [comment]
Few questions:
1 - did you have enough RAM during insert (check free)
2 - does the issue reproduces
3 - copt log with stracktrace please.

**Comment by testlujing** [comment]
1：ram is enough：
<max_memory_usage>100000000000</max_memory_usage>
2： the issue is not  reproduces temporary
3:    when the problem happen next ,i will copy log with stracktrace

**Comment by testlujing** [comment]
the problem is happen today,messge is:

2020.05.09 12:33:27.871731 [ 594 ] {019cb4e7-89d3-4b65-b6b1-0654767dbc9b} <Error> executeQuery: Code: 173, e.displayText() = DB::ErrnoException: Allocator: Cannot malloc 128.00 KiB., errno: 12, strerror: Cannot allocate memory: (while reading column id): (while reading from part /home/service/var/data/clickhouse/data/data/shared_ods/prd_property_value/202004_70_70_0/ from mark 0 with max_rows_to_read = 8192) (version 19.17.4.11) (from 10.56.106.155:35119) (in query: SELECT id, max(rksj) FROM shared_ods.prd_property_value GROUP BY id), Stack trace:

0. 0x3512b60 StackTrace::StackTrace() /usr/bin/clickhouse
1. 0x35298db DB::ErrnoException::ErrnoException(std::string const&, int, int, std::optional<std::string> const&) /usr/bin/clickhouse
2. 0x35254fe DB::throwFromErrno(std::string const&, int, int) /usr/bin/clickhouse
3. 0x611fc8d ? /usr/bin/clickhouse
4. 0x61261f0 DB::DataTypeString::deserializeBinaryBulk(DB::IColumn&, DB::ReadBuffer&, unsigned long, double) const /usr/bin/clickhouse
5. 0x6998205 DB::MergeTreeReader::readData(std::string const&, DB::IDataType const&, DB::IColumn&, unsigned long, bool, unsigned long, bool) /usr/bin/clickhouse
6. 0x69987c2 DB::MergeTreeReader::readRows(unsigned long, bool, unsigned long, std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >&) /usr/bin/clickhouse
7. 0x6992a73 ? /usr/bin/clickhouse
8. 0x6993386 DB::MergeTreeRangeReader::DelayedStream::finalize(std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >&) /usr/bin/clickhouse
9. 0x6994ec5 DB::MergeTreeRangeReader::startReadingChain(unsigned long, std::vector<DB::MarkRange, std::allocator<DB::MarkRange> >&) /usr/bin/clickhouse
10. 0x699624a DB::MergeTreeRangeReader::read(unsigned long, std::vector<DB::MarkRange, std::allocator<DB::MarkRange> >&) /usr/bin/clickhouse
11. 0x696ef35 DB::MergeTreeBaseSelectProcessor::readFromPartImpl() /usr/bin/clickhouse
12. 0x696fa01 DB::MergeTreeBaseSelectProcessor::generate() /usr/bin/clickhouse
13. 0x65a462f DB::ISource::work() /usr/bin/clickhouse
14. 0x65ca17a DB::TreeExecutorBlockInputStream::execute() /usr/bin/clickhouse
15. 0x65cac63 DB::TreeExecutorBlockInputStream::readImpl() /usr/bin/clickhouse
16. 0x6073008 DB::IBlockInputStream::read() /usr/bin/clickhouse
17. 0x676900b DB::ExpressionBlockInputStream::readImpl() /usr/bin/clickhouse
18. 0x6073008 DB::IBlockInputStream::read() /usr/bin/clickhouse
19. 0x67a353e DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>::loop(unsigned long) /usr/bin/clickhouse
20. 0x67a3cba DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>::thread(std::shared_ptr<DB::ThreadGroupStatus>, unsigned long) /usr/bin/clickhouse
21. 0x67a414b ThreadFromGlobalPool::ThreadFromGlobalPool<void (DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>::*)(std::shared_ptr<DB::ThreadGroupStatus>, unsigned long), DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>*, std::shared_ptr<DB::ThreadGroupStatus>, unsigned long&>(void (DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>::*&&)(std::shared_ptr<DB::ThreadGroupStatus>, unsigned long), DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>*&&, std::shared_ptr<DB::ThreadGroupStatus>&&, unsigned long&)::{lambda()#1}::operator()() const /usr/bin/clickhouse
22. 0x3554f13 ThreadPoolImpl<std::thread>::worker(std::_List_iterator<std::thread>) /usr/bin/clickhouse
23. 0x791d69f ? /usr/bin/clickhouse
24. 0x7f1650360dd5 start_thread /usr/lib64/libpthread-2.17.so
25. 0x7f164fe8602d __clone /usr/lib64/libc-2.17.so

**Comment by alexey-milovidov** [comment]
You are not using official build.
If it is debug build, the issue may happen due to the shortage of memory maps.

**Comment by alexey-milovidov** [comment]
#4086
#6732
#10488
