### ISSUE TITLE
Ambigious datetime in HTTP protocol

### ISSUE THREAD

**Issue by hhell** [ClickHouse/ClickHouse#10726]
HTTP protocol displays datetime values as ISO8601 format without offset.

For non-UTC values this leads to ambiguity:

```(sql)
select
    toDateTime('2010-10-31 01:30:00', 'Europe/Moscow') + arrayJoin(range(7)) * 60 * 30 as val,
    groupArray(cast(val as Int64)) as val_ts
group by val order by val
format TabSeparatedWithNamesAndTypes
```

```
val     val_ts
DateTime(\'Europe/Moscow\')     Array(Int64)
2010-10-31 01:30:00     [1288474200]
2010-10-31 02:00:00     [1288476000]
2010-10-31 02:30:00     [1288477800]
2010-10-31 02:00:00     [1288479600]
2010-10-31 02:30:00     [1288481400]
2010-10-31 03:00:00     [1288483200]
2010-10-31 03:30:00     [1288485000]
```

It would be more correct to either:

1. Serialize datetime values for HTTP with the effective offset, e.g.:
```
DateTime(\'Europe/Moscow\')     Array(Int64)
2010-10-31 02:30:00+04:00     [1288477800]
2010-10-31 02:30:00+03:00     [1288481400]
```

2. Serialize datetime as the underlying integer values, e.g.:
```
DateTime(\'Europe/Moscow\')     Array(Int64)
1288477800     [1288477800]
1288481400     [1288481400]
```

and to configure the serialization over settings (HTTP query parameters).

**Comment by 4ertus2** [comment]
Just duplicate here from mail. It's possible to extract difference betwee dates with same text representation with `dateDiff()` function

```
SELECT  
   toDateTime('2010-10-31 02:30:00', 'Europe/Moscow') AS a,  
   a + 3600 AS b,  
   dateDIff('hour', a, b) AS diff

┌───────────────────a─┬───────────────────b─┬─diff─┐
│ 2010-10-31 02:30:00 │ 2010-10-31 02:30:00 │    1 │
└─────────────────────┴─────────────────────┴──────┘
```
Then it could be adopted to extract diff from UTC into separeate column.

**Comment by hhell** [comment]
> `dateDiff()` function

Other SQL-level hacks to do this:

  * `cast(val as Int64)` (as in the example above) – returns unix timestamp (UTC)
  * `(cast(val as DateTime('UTC'), toTypeName(val))` – UTC isoformat + original timezone (also sufficient to reconstruct the value).

However, those are hacks, and it would be much better to receive some unambiguous value for a single column.

**Comment by alexey-milovidov** [comment]
The issue is not about HTTP protocol but about text format (TSV, CSV, etc).

**Comment by hhell** [comment]
> The issue is not about HTTP protocol but about text format (TSV, CSV, etc).

Yes, but this is still an issue.

**Comment by alexey-milovidov** [comment]
I've created another task: https://github.com/ClickHouse/ClickHouse/issues/10862
