### ISSUE TITLE
the update of Dictionary table

### ISSUE THREAD

**Issue by wenwen2019** [ClickHouse/ClickHouse#10725]
I created a clickhouse table,the engine is 'Dictionary',the source is a mysql table ,when I updated the data of the mysql table ,I found the xshell client of the clickhouse couldn't execute any sql.the version of the clickhouse is 19.3.7.

**Comment by sundy-li** [comment]
@wenwen2019  please use English to submit the issue.

**Comment by wenwen2019** [comment]
Is the version lower？

**Comment by wenwen2019** [comment]
Can the dictionary be updated only after restarting clickhouse？

**Comment by robot-clickhouse** [comment]
@wenwen2019, do you have any further questions?

**Comment by alexey-milovidov** [comment]
@wenwen2019 The dictionary is updated according to the `lifetime` settings, see
https://clickhouse.tech/docs/en/sql-reference/dictionaries/external-dictionaries/external-dicts-dict-lifetime/
You can also update dictionary manually with `SYSTEM RELOAD DICTIONARY` query.
https://clickhouse.tech/docs/en/sql-reference/statements/system/

Consider the `system.dictionaries` table for the last update time.
Dictionary update happens automatically and does not require server restart.
