### ISSUE TITLE
The parameters of Send timeout and receive timeout.

### ISSUE THREAD

**Issue by toby080508050805** [ClickHouse/ClickHouse#10739]
My clickhouse version is 19.17.5.18. I set  following parameters in /etc/clickhouse-server/users.xml. 

>  <receive_timeout>900</receive_timeout>
>  <send_timeout>900</send_timeout>
>  <tcp_keep_alive_timeout>600</tcp_keep_alive_timeout>

<img width="802" alt="users" src="https://user-images.githubusercontent.com/55230942/81367438-d44c3800-911f-11ea-9965-cbb362832857.PNG">

However, when we insert or attach a large data ,  it still encounter timeout error in the shell. 

> Code: 209. DB::NetException: Timeout exceeded while reading from socket (127.0.0.1:9000): while receiving packet from 127.0.0.1:9000
> 
> Timeout exceeded while receiving data from server. Waited for 300 seconds, timeout is 300 seconds.
> 

After observing log, I found data was success inputed into table in 600 conds in the same session and no error in clickhouse log. What setting should I need to add?  

> 	Line 94873: 2020.05.08 01:46:04.263150 [ 144 ] {e21373b2-f49b-4dcd-93de-0d7446d979b7} <Debug> executeQuery: (from [::ffff:127.0.0.1]:60536) insert into table_call_lte.recent format TSV
> 	Line 95735: 2020.05.08 01:46:14.875342 [ 144 ] {e21373b2-f49b-4dcd-93de-0d7446d979b7} <Debug> MemoryTracker: Current memory usage: 1.00 GiB.
> 	Line 95758: 2020.05.08 01:46:15.255125 [ 144 ] {e21373b2-f49b-4dcd-93de-0d7446d979b7} <Debug> DiskSpaceMonitor: Reserving 502.45 MiB on disk `default`, having unreserved 19.15 TiB.
> 	Line 105313: 2020.05.08 01:50:57.521007 [ 144 ] {e21373b2-f49b-4dcd-93de-0d7446d979b7} <Debug> MemoryTracker: Current memory usage: 2.00 GiB.
> 	Line 111187: 2020.05.08 01:54:12.946256 [ 144 ] {e21373b2-f49b-4dcd-93de-0d7446d979b7} <Trace> table_call_lte.recent: Renaming temporary part tmp_insert_20200508-7357-100_6417_6417_0 to 20200508-7357-100_6417_6417_0.
> 	Line 111190: 2020.05.08 01:54:12.947880 [ 144 ] {e21373b2-f49b-4dcd-93de-0d7446d979b7} <Debug> MemoryTracker: Peak memory usage (for query): 2.35 GiB.
> 	Line 111191: 2020.05.08 01:54:12.948203 [ 144 ] {e21373b2-f49b-4dcd-93de-0d7446d979b7} <Information> TCPHandler: Processed in 488.685 sec.

Thanks

**Comment by den-crane** [comment]
clickhouse-client --receive_timeout 900

**Comment by toby080508050805** [comment]
> clickhouse-client --receive_timeout 900

It is work. It seems like server and client have different timeout parameters.

Thanks for your replying.
