### ISSUE TITLE
click-house service not started

### ISSUE THREAD

**Issue by viputh6** [ClickHouse/ClickHouse#10738]
I am getting below error message when i check the status of the service [after service start]..kindly note no error message in log or error files... Please help me to resolve this issue..

UBUNTU:~$ sudo service clickhouse-server status
● clickhouse-server.service - ClickHouse Server (analytic DBMS for big data)
   Loaded: loaded (/etc/systemd/system/clickhouse-server.service; enabled; vendor preset: enabled)
   Active: inactive (dead) (Result: exit-code) since Fri 2020-05-08 08:16:06 IST; 7s ago
  Process: 18079 ExecStart=/usr/bin/clickhouse-server --config=/etc/clickhouse-server/config.xml --pid-file=/run/clickhouse-server/clickhouse-server.pid (code=exited, status=232/ADDRESS_FAMILIES)
 Main PID: 18079 (code=exited, status=232/ADDRESS_FAMILIES)

**Comment by SixFootFall** [comment]
Check priveleges to this folder /etc/clickhouse-server/config.xml

**Comment by viputh6** [comment]
Thanks for your comments... after restarting the system, it started working... issue has been resolved...
