### ISSUE TITLE
Regression, mysql protocol has corrupted content for zero-size responses

### ISSUE THREAD

**Issue by slawomir-pryczek** [ClickHouse/ClickHouse#10735]
Clickhouse server version 20.3.8.53 seems to have issues with mysql protocol for EMPTY RESPONSES only... this will cause issues with thirdparty tools.

How to reproduce:
- Server version 20.3.8 revision 54433.
- mariadb client or php mysql client, using mysql protocol to connect ( mysql -h 127.0.0.1 -P9004 -u default --protocol tcp --plugin-dir=/usr/lib/mysql/plugin/ )

This works correctly:
CREATE TABLE default.b (i UInt8) ENGINE=MergeTree() PRIMARY KEY(i) ORDER BY (i);
INSERT INTO default.b VALUES (1), (2), (3);
SELECT * FROM default.b WHERE i>=3;
> 1 row in set. Elapsed: 0.002 sec.

This will cause issues:
SELECT * FROM default.b WHERE i>=300;
> Query OK, 67 rows affected, 17952 warnings (0.002 sec)

Expected behaviour:
SELECT * FROM default.b WHERE i>=300;
> 0 rows in set. Elapsed: X sec.

Additional info:
- This will also cause php mysqlnd extension to output:
mysqli::query(): Premature end of data (mysqlnd_wireprotocol.c:1075) [..]
Warning: mysqli::query(): RSET_HEADER packet 4 bytes shorter than expected [..] 

- Old version 20.3 also seems to have this issue, while version 19.17 seems to be working ok so probably that's a regression in recent versions

**Comment by slawomir-pryczek** [comment]
Bump... any ideas? Maybe there is some vm which can be used for easily testing / compiling clickhouse?

**Comment by alexey-milovidov** [comment]
I checked it on the latest version and it works Ok:

```
milovidov@milovidov-desktop:~/work/ClickHouse$ mysql --port 9004 --host 127.0.0.1 --user default
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MySQL connection id is 1
Server version: 21.9.1.1-ClickHouse 

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MySQL [(none)]> SELECT * FROM default.b WHERE i>=3;
+------+
| i    |
+------+
|    3 |
+------+
1 row in set (0.001 sec)

MySQL [(none)]> SELECT * FROM default.b WHERE i>=300;
Empty set (0.001 sec)

MySQL [(none)]>
```
