### ISSUE TITLE
Renaming column that is used inside the TTL expression breaks TTL operations

### ISSUE THREAD

**Issue by vzakaznikov** [ClickHouse/ClickHouse#10747]
Renaming column that is used inside the TTL expression breaks TTL operations.

To reproduce the issue see test https://github.com/ClickHouse/ClickHouse/blob/089371ddfb596a7b052ac709a5c2778e76f349c0/tests/integration/test_rename_column/test.py#L408 and comment out line https://github.com/ClickHouse/ClickHouse/blob/089371ddfb596a7b052ac709a5c2778e76f349c0/tests/integration/test_rename_column/test.py#L421 where we rename the column back to its original name.
Without this line test will fail and no parts are moved according to the TTL expression.

**Comment by alesapin** [comment]
Cannot reproduce, this test works if I comment this line.
