### ISSUE TITLE
Select query with some threads hanging

### ISSUE THREAD

**Issue by cw9** [ClickHouse/ClickHouse#10759]
I have a select query that should return very fast, but some of the query threads may hang for a few seconds which cam delay the latency for the whole query.

For example in the query log below, 3 out of 5 threads finishes < 0.5s, but 2 out of 5 threads took 10s to finish. I replayed the same query 10 minutes later and it took 0.5s to finish.

During the hang the host is not using much HW resource.
![image](https://user-images.githubusercontent.com/6710599/81442691-138b8080-9142-11ea-8ec5-d290d17886f6.png)

Around the same time there are other queries going on in the system at same time and many of them had similar hanging behaviour as well. 

What could be the cause for the hanging? The host should have plenty of CPU resource to supply query threads. Is there a CH configuration that limits total number of query threads allowed globally?

I also saw a spike of RWActiveReaders
![image](https://user-images.githubusercontent.com/6710599/81443282-2783b200-9143-11ea-9650-a56975e66483.png) 

Please let me know if you need anything else to debug this issue.

Example Logs:
{"log":"2020.05.08 17:45:58.757241 [ 534 ] {1a862180-7a77-4f95-80af-aa619ff52067} <Debug> executeQuery: (from 10.84.65.190:38096, initial_query_id: 6b0c1358-100a-45b5-92cc-427a36036e8a) SELECT floor(_timestampMillis / 1800000) * 1800000 AS _timestampMillis_fixed_bucket, countIf(position(`message.String`, 'Workflow succeeded') > 0) AS `globalagg.0.0.doc_count`, countIf(position(`message.String`, 'Workflow failed') > 0) AS `globalagg.1.1.doc_count` FROM default.`Merge.foo` WHERE (_namespace = 'foo') AND ((_timestampMillis >= 1588787158227) AND (_timestampMillis < 1588959958227)) AND (f1 = 'v') GROUP BY _timestampMillis_fixed_bucket ORDER BY _timestampMillis_fixed_bucket ASC SETTINGS max_threads = 5, max_execution_time = 30, timeout_overflow_mode = 'break'\n"}
{"log":"2020.05.08 17:45:58.771157 [ 534 ] {1a862180-7a77-4f95-80af-aa619ff52067} <Trace> AccessRightsContext (default): Access granted: SELECT(_namespace, _timestampMillis, `f1`) ON default.`Merge.foo`\n"}
{"log":"2020.05.08 17:45:58.781935 [ 534 ] {1a862180-7a77-4f95-80af-aa619ff52067} <Debug> default.`ReplicatedMergeTree.foo` (SelectExecutor): Key condition: (column 0 in ['foo', 'foo']), unknown, unknown, and, and, unknown, unknown, or, unknown, and, and\n"}
{"log":"2020.05.08 17:45:58.781979 [ 534 ] {1a862180-7a77-4f95-80af-aa619ff52067} <Debug> default.`ReplicatedMergeTree.foo` (SelectExecutor): MinMax index condition: unknown, (column 0 in [1588787158227, +inf)), (column 0 in (-inf, 1588959958226]), and, and, unknown, unknown, or, unknown, and, and\n"}
{"log":"2020.05.08 17:45:58.793467 [ 534 ] {1a862180-7a77-4f95-80af-aa619ff52067} <Debug> default.`ReplicatedMergeTree.foo` (SelectExecutor): Selected 388 parts by date, 329 parts by key, 924 marks to read from 329 ranges\n"}
{"log":"2020.05.08 17:45:58.863594 [ 534 ] {1a862180-7a77-4f95-80af-aa619ff52067} <Trace> default.`ReplicatedMergeTree.foo` (SelectExecutor): Reading approx. 1861120 rows with 5 streams\n"}
{"log":"2020.05.08 17:45:58.864980 [ 534 ] {1a862180-7a77-4f95-80af-aa619ff52067} <Trace> InterpreterSelectQuery: FetchColumns -> WithMergeableState\n"}
{"log":"2020.05.08 17:45:59.239875 [ 357 ] {1a862180-7a77-4f95-80af-aa619ff52067} <Trace> AggregatingTransform: Aggregated. 0 to 0 rows (from 0.000 MiB) in 0.372 sec. (0.000 rows/sec., 0.000 MiB/sec.)\n"}
{"log":"2020.05.08 17:45:59.240256 [ 512 ] {1a862180-7a77-4f95-80af-aa619ff52067} <Trace> AggregatingTransform: Aggregated. 0 to 0 rows (from 0.000 MiB) in 0.373 sec. (0.000 rows/sec., 0.000 MiB/sec.)\n"}
{"log":"2020.05.08 17:45:59.240297 [ 253 ] {1a862180-7a77-4f95-80af-aa619ff52067} <Trace> AggregatingTransform: Aggregated. 0 to 0 rows (from 0.000 MiB) in 0.373 sec. (0.000 rows/sec., 0.000 MiB/sec.)\n"}
**{"log":"2020.05.08 17:46:09.691886 [ 178 ] {1a862180-7a77-4f95-80af-aa619ff52067} <Trace> AggregatingTransform: Aggregated. 0 to 0 rows (from 0.000 MiB) in 10.824 sec. (0.000 rows/sec., 0.000 MiB/sec.)\n"}
{"log":"2020.05.08 17:46:09.726457 [ 341 ] {1a862180-7a77-4f95-80af-aa619ff52067} <Trace> AggregatingTransform: Aggregated. 0 to 0 rows (from 0.000 MiB) in 10.859 sec. (0.000 rows/sec., 0.000 MiB/sec.)\n"}**
{"log":"2020.05.08 17:46:09.726484 [ 341 ] {1a862180-7a77-4f95-80af-aa619ff52067} <Trace> Aggregator: Merging aggregated data\n"}
{"log":"2020.05.08 17:46:09.727106 [ 534 ] {1a862180-7a77-4f95-80af-aa619ff52067} <Information> executeQuery: Read 1834136 rows, 339.64 MiB in 10.970 sec., 167199 rows/sec., 30.96 MiB/sec.\n"}
{"log":"2020.05.08 17:46:09.727183 [ 534 ] {1a862180-7a77-4f95-80af-aa619ff52067} <Debug> MemoryTracker: Peak memory usage (for query): 19.52 MiB.\n"}

* Which ClickHouse server version to use
20.3.5

**Comment by filimonov** [comment]
Set log_queries=1 and check the counters in system.query_log and system.query_thread_log

**Comment by cw9** [comment]
I've found the following data from system.query_log for the replayed queries, but the hang is no longer happening, the replays are all pretty fast now. I feel the hanging is not particularly caused by this query itself, is it possible that other process in the background (merges, replications or other queries) at the time are the causes for the hang?

The cluster sill would show that similar behaviour every once a while: light queries took a much longer time to execute than usual, I guess I have to enable log_queries at all times to collect more forensic? Is there anything else I can check retrospectively to debug this?

`
[('Query',1),('SelectQuery',1),('FileOpen',6156),('Seek',3829),('ReadBufferFromFileDescriptorRead',6291),('ReadBufferFromFileDescriptorReadBytes',99234254),('ReadCompressedBytes',98835401),('CompressedReadBufferBlocks',7662),('CompressedReadBufferBytes',573963153),('IOBufferAllocs',12304),('IOBufferAllocBytes',562086741),('ArenaAllocChunks',5),('ArenaAllocBytes',20480),('FunctionExecute',8995),('MarkCacheHits',6156),('CreatedReadBufferOrdinary',6156),('DiskReadElapsedMicroseconds',40000),('NetworkSendElapsedMicroseconds',173),('SelectedParts',324),('SelectedRanges',324),('SelectedMarks',922),('ContextLock',83),('RWLockAcquiredReadLocks',2),('RealTimeMicroseconds',1313621),('UserTimeMicroseconds',832000),('SystemTimeMicroseconds',116000),('SoftPageFaults',11538)] │ [('connect_timeout_with_failover_ms','500'),('use_uncompressed_cache','1'),('load_balancing','random'),('skip_unavailable_shards','1'),('merge_tree_max_rows_to_use_cache','2147483647'),('log_queries','1'),('max_bytes_before_external_group_by','20056289768'),('max_bytes_before_external_sort','20056289768'),('timeout_overflow_mode','break'),('max_memory_usage','25070362210'),('max_memory_usage_for_all_queries','100281448840'),('cancel_http_readonly_queries_on_client_close','0'),('allow_introspection_functions','1')]
`

**Comment by cw9** [comment]
btw, during that period of time `17:45:59 - 17:46:09`, other queries are also not logging any logs like `AggregatingTransform: Aggregated.`, they all halted after 17:45:59 and resumed after 17:46:09. 

During that 10s, some new select queries came in as well but also no progress like `AggregatingTransform: Aggregated.`. There are a few `INSERT`, a few `DataPartsExchange` came in but those seems to be progressing.

**Comment by filimonov** [comment]
Page cache?

**Comment by cw9** [comment]
What about the page cache?

I found these page in/out metrics, seems there is a spike after the query hang. (although seems there are other higher spikes without query performance issues)
![image](https://user-images.githubusercontent.com/6710599/81484666-6c781900-9215-11ea-97a7-2a41106b65db.png)

There is also a pretty high disk read latency, is this because the queries trying to read too many parts?
![image](https://user-images.githubusercontent.com/6710599/81484336-bf040600-9212-11ea-94c3-0305fcde7655.png)

**Comment by cw9** [comment]
> Set log_queries=1 and check the counters in system.query_log and system.query_thread_log

So I've enabled log_queries for all queries and found some more examples of this case.

This distributed query took 11s to run:
```

┌──────────event_time─┬────query_start_time─┬─initial_query_id─────────────────────┬─query_id─────────────────────────────┬─query_duration_ms─┬─arrayZip(ProfileEvents.Names, ProfileEvents.Values)────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─arrayZip(Settings.Names, Settings.Values)──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ 2020-05-16 21:32:32 │ 2020-05-16 21:32:21 │ b9044fef-ed5a-4e69-ae6b-921564b4ab7d │ b9044fef-ed5a-4e69-ae6b-921564b4ab7d │             11187 │ [('Query',1),('SelectQuery',1),('ReadCompressedBytes',45970),('CompressedReadBufferBlocks',503),('CompressedReadBufferBytes',42513),('IOBufferAllocs',3767),('IOBufferAllocBytes',265505995),('FunctionExecute',20),('NetworkReceiveElapsedMicroseconds',33524003),('NetworkSendElapsedMicroseconds',14842),('ContextLock',313),('RWLockAcquiredReadLocks',2),('RealTimeMicroseconds',2794338354),('UserTimeMicroseconds',204000),('SystemTimeMicroseconds',236000),('SoftPageFaults',229)] │ [('connect_timeout_with_failover_ms','500'),('use_uncompressed_cache','1'),('load_balancing','random'),('skip_unavailable_shards','1'),('merge_tree_max_rows_to_use_cache','2147483647'),('log_queries','1'),('max_bytes_before_external_group_by','20056289768'),('max_bytes_before_external_sort','20056289768'),('timeout_overflow_mode','break'),('max_memory_usage','25070362210'),('max_memory_usage_for_all_queries','100281448840'),('cancel_http_readonly_queries_on_client_close','0'),('allow_introspection_functions','1')] │
└─────────────────────┴─────────────────────┴──────────────────────────────────────┴──────────────────────────────────────┴───────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

The distributed query fanned out to 250 shards, and most shard finished in <100ms, only one shard took 11s.

query_log for a fast shard:
```
b9044fef-ed5a-4e69-ae6b-921564b4ab7d    f8210e67-57e7-4ef0-9aab-d44d33a89442    41      [('Query',1),('SelectQuery',1),('ReadCompressedBytes',36),('CompressedReadBufferBlocks',1),('CompressedReadBufferBytes',10),('UncompressedCacheHits',40),('IOBufferAllocs',2),('IOBufferAllocBytes',1048680),('FunctionExecute',144),('MarkCacheHits',36),('NetworkSendElapsedMicroseconds',119),('SelectedParts',3),('SelectedRanges',3),('SelectedMarks',6),('ContextLock',96),('RWLockAcquiredReadLocks',5),('RealTimeMicroseconds',118833),('UserTimeMicroseconds',16000),('SystemTimeMicroseconds',24000),('SoftPageFaults',120)]  [('max_threads','2'),('connect_timeout_with_failover_ms','500'),('queue_max_wait_ms','0'),('use_uncompressed_cache','1'),('load_balancing','random'),('skip_unavailable_shards','1'),('merge_tree_max_rows_to_use_cache','2147483647'),('log_queries','1'),('max_bytes_before_external_group_by','20056289768'),('max_bytes_before_external_sort','20056289768'),('max_execution_time','30'),('timeout_overflow_mode','break'),('max_memory_usage','25070362210'),('max_memory_usage_for_all_queries','100281448840'),('cancel_http_readonly_queries_on_client_close','0'),('allow_introspection_functions','1')]
```

query_log for a slow shard:
```
b9044fef-ed5a-4e69-ae6b-921564b4ab7d    562764b6-df84-4f31-8dd1-2f5df0c39d12    11116   [('Query',1),('SelectQuery',1),('ReadCompressedBytes',36),('CompressedReadBufferBlocks',1),'CompressedReadBufferBytes',10),('UncompressedCacheHits',41),('IOBufferAllocs',2),('IOBufferAllocBytes',1048680),('FunctionExecute',194),('MarkCacheHits',36),('NetworkSendElapsedMicroseconds',161),'SelectedParts',3),('SelectedRanges',3),('SelectedMarks',11),('ContextLock',94),('RWLockAcquiredReadLocks',5),('RealTimeMicroseconds',11130689),('UserTimeMicroseconds',40000),('SoftPageFaults',15),'QueryProfilerSignalOverruns',11)]      [('max_threads','2'),('connect_timeout_with_failover_ms','500'),('queue_max_wait_ms','0'),('use_uncompressed_cache','1'),('load_balancing','random'),'skip_unavailable_shards','1'),('merge_tree_max_rows_to_use_cache','2147483647'),('log_queries','1'),('max_bytes_before_external_group_by','20056289768'),('max_bytes_before_external_sort',20056289768'),('max_execution_time','30'),('timeout_overflow_mode','break'),('max_memory_usage','25070362210'),('max_memory_usage_for_all_queries','100281448840'),'cancel_http_readonly_queries_on_client_close','0'),('allow_introspection_functions','1')]
```
One thing to note about the slow shard is that it has `QueryProfilerSignalOverruns,11` in profile, non of the fast shards have this.

query_thread_log on the slow shard:
```

SELECT
    event_time,
    query_start_time,
    initial_query_id,
    query_id,
    query_duration_ms,
    arrayZip(ProfileEvents.Names, ProfileEvents.Values)
FROM system.query_thread_log
WHERE initial_query_id = 'b9044fef-ed5a-4e69-ae6b-921564b4ab7d'


┌──────────event_time─┬────query_start_time─┬─initial_query_id─────────────────────┬─query_id─────────────────────────────┬─query_duration_ms─┬─arrayZip(ProfileEvents.Names, ProfileEvents.Values)────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ 2020-05-16 21:32:32 │ 2020-05-16 21:32:32 │ b9044fef-ed5a-4e69-ae6b-921564b4ab7d │ 562764b6-df84-4f31-8dd1-2f5df0c39d12 │                13 │ [('UncompressedCacheHits',41),('FunctionExecute',140),('MarkCacheHits',36),('ContextLock',7),('RealTimeMicroseconds',13415),('UserTimeMicroseconds',12000),('SoftPageFaults',10)]                                                                          │
│ 2020-05-16 21:32:32 │ 2020-05-16 21:32:21 │ b9044fef-ed5a-4e69-ae6b-921564b4ab7d │ 562764b6-df84-4f31-8dd1-2f5df0c39d12 │             11117 │ [('Query',1),('SelectQuery',1),('ReadCompressedBytes',36),('CompressedReadBufferBlocks',1),('CompressedReadBufferBytes',10),('IOBufferAllocs',2),('IOBufferAllocBytes',1048680),('FunctionExecute',54),('NetworkSendElapsedMicroseconds',161),('SelectedParts',3),('SelectedRanges',3),('SelectedMarks',11),('ContextLock',87),('RWLockAcquiredReadLocks',5),('RealTimeMicroseconds',11117274),('UserTimeMicroseconds',28000),('SoftPageFaults',5),('QueryProfilerSignalOverruns',11)] │
└─────────────────────┴─────────────────────┴──────────────────────────────────────┴──────────────────────────────────────┴───────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

HW usage was very low throughout the query time on the node, I'm now trying to increase profiling frequency to see if we can catch anything interesting there.

**Comment by yonzhang** [comment]
@cw9 I have similar "query hangs" issue. Do you have any progress on solving your issue?

**Comment by azat** [comment]
@cw9 

>One thing to note about the slow shard is that it has QueryProfilerSignalOverruns,11 in profile, non of the fast shards have this.

This is likely because the query execution took longer (hence it is more likely that there will be si_overrun)

>query_log for a slow shard:

It has:
- 40e3 ms user time
- 11sec realtime
- no sys time reported

And since you have QueryProfilerSignalOverruns, then you have one of the following enabled:
- query_profiler_cpu_time_period_ns
- query_profiler_real_time_period_ns

Since you don't have anything in settings, the value is default, 1000000000ns - 1 second.

So I guess the problem can be because of one of the profilers, and 11 signal overrun (equals to the real time of the query) can be a signal that by some reason profiling wasn't that fast (if there will be greater user time then it can show that for example unwind is slow)

Can you try turn it off and see if you can reproduce the spikes?

**Comment by alexey-milovidov** [comment]
@azat 

> Can you try turn it off and see if you can reproduce the spikes?

We have profiler enabled ("always on profiling") by default on >1000 servers in >60 production clusters without any troubles.

In fact, you can enable it with even higher frequency for some subset of queries and actually figure out the cause of latency spikes.
