### ISSUE TITLE
Upgrade from 19 to 20 version has lot of restrictions on clickhouse data import 

### ISSUE THREAD

**Issue by Crazylearner30** [ClickHouse/ClickHouse#10767]
When i tried to import CSV file to clickhouse table its giving me the below error which was working perfectly fine in the older versions.

Please suggest any solution for this.

"Its affecting our production."

Issue:  Stack trace (when copying this message, always include the lines below):

0. 0xb21ba6c Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int)  in /usr/bin/clickhouse
1. 0x4d91839 DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int)  in /usr/bin/clickhouse
2. 0x8407f16 void DB::readIntTextImpl<unsigned int, void, (DB::ReadIntTextCheckOverflow)0>(unsigned int&, DB::ReadBuffer&)  in /usr/bin/clickhouse
3. 0x840d465 DB::DataTypeNumberBase<unsigned int>::deserializeTextCSV(DB::IColumn&, DB::ReadBuffer&, DB::FormatSettings const&) const  in /usr/bin/clickhouse
4. 0x8401d04 void DB::DataTypeNullable::deserializeTextCSV<void>(DB::IColumn&, DB::ReadBuffer&, DB::FormatSettings const&, std::__1::shared_ptr<DB::IDataType const> const&)::'lambda0'(DB::IColumn&)::operator()(DB::IColumn&) const  in /usr/bin/clickhouse
5. 0x84014cf DB::DataTypeNullable::deserializeTextCSV(DB::IColumn&, DB::ReadBuffer&, DB::FormatSettings const&) const  in /usr/bin/clickhouse
6. 0x8a95334 DB::CSVRowInputFormat::readField(DB::IColumn&, std::__1::shared_ptr<DB::IDataType const> const&, bool)  in /usr/bin/clickhouse
7. 0x8a95aaa DB::CSVRowInputFormat::readRow(std::__1::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn> > >&, DB::RowReadExtension&)  in /usr/bin/clickhouse
8. 0x9047e82 DB::IRowInputFormat::generate()  in /usr/bin/clickhouse
9. 0x8a32647 DB::ISource::work()  in /usr/bin/clickhouse
10. 0x89fabcd DB::InputStreamFromInputFormat::readImpl()  in /usr/bin/clickhouse
11. 0x834eabf DB::IBlockInputStream::read()  in /usr/bin/clickhouse
12. 0x8d851a0 DB::ParallelParsingBlockInputStream::parserThreadFunction(unsigned long)  in /usr/bin/clickhouse
13. 0x4dcbfea ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>)  in /usr/bin/clickhouse
14. 0x4dccc00 ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()&&...)::'lambda'()::operator()() const  in /usr/bin/clickhouse
15. 0x4dcb33a ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>)  in /usr/bin/clickhouse
16. 0x4dc9e4c ?  in /usr/bin/clickhouse
17. 0x7e65 start_thread  in /usr/lib64/libpthread-2.17.so
18. 0xfe88d clone  in /usr/lib64/libc-2.17.so
 (version 20.1.11.73)
Code: 72. DB::Exception: Unsigned type must not contain '-' symbol: (at row 4)

**Comment by den-crane** [comment]
**Describe the bug**

**How to reproduce**
* Which ClickHouse server version to use
* Which interface to use, if matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary

**Comment by alexey-milovidov** [comment]
@Crazylearner30 It happens because your data file or table structure is incorrect.
You are trying to insert negative number into unsigned type.

> Unsigned type must not contain '-' symbol

**Comment by jakesyl** [comment]
In case it's helpful to anyone coming across this issue, in our case we were inserting dates instead of unix timestamps
