### ISSUE TITLE
Cannot parse DateTime from String

### ISSUE THREAD

**Issue by qinzl1** [ClickHouse/ClickHouse#10768]
insert data 
DB::Exception: Cannot parse datetime: Cannot parse DateTime from String. 

already  CAST(filed AS DateTime)  
why

**Comment by qinzl1** [comment]
![image](https://user-images.githubusercontent.com/20242930/81467199-af33f400-9209-11ea-8269-2c6c89f6e400.png)

![image](https://user-images.githubusercontent.com/20242930/81467205-b65b0200-9209-11ea-8793-ca8253a2e755.png)

**Comment by qinzl1** [comment]
if  cast   or toxxx function  can't  work   , What does it do

**Comment by den-crane** [comment]
**Describe the bug**


**How to reproduce**
* Which ClickHouse server version to use
* Which interface to use, if matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

**Comment by filimonov** [comment]
Most probably you have a bad string there which cant be casted to DateTime.

**Comment by filimonov** [comment]
There are
- toDateTimeOrNull 
 - toDateTimeTimeOrZero
- parseDateTimeBestEffort
- parseDateTimeBestEffortOrNull
- parseDateTimeBestEffortOrZero

Pick the one depending or your needs. Variants with 'or' don't throw exceptions on bad strings.
