### ISSUE TITLE
Cannot drop partition on CH cluster in MergeTree table: "Table isn't replicated, but shard #1 is replicated"

### ISSUE THREAD

**Issue by VitoLiao** [ClickHouse/ClickHouse#10769]
We have 3 servers, and make it clickhouse cluster.When I drop partition in some MergeTree table,the sql like this:
```sql
alter table bi.launcher_tab_play_long2 on CLUSTER bi_cluster drop PARTITION '2017-01-01'
```
but got error log like this:

> An error occurred before execution: Code: 371, e.displayText() = DB::Exception: Table 'launcher_tab_play_long2' isn't replicated, but shard #1 is replicated according to its cluster definition (version 19.16.14.65 (official build))

> An error occurred before execution: Code: 371, e.displayText() = DB::Exception: Table 'launcher_tab_play_long2' isn't replicated, but shard #2 is replicated according to its cluster definition (version 19.16.14.65 (official build))

> An error occurred before execution: Code: 371, e.displayText() = DB::Exception: Table 'launcher_tab_play_long2' isn't replicated, but shard #3 is replicated according to its cluster definition (version 19.16.14.65 (official build))

I can create table or drop table by 'on cluster', but why cannot I drop partition ?
This is our clickhosue cluster config:

```xml
<clickhouse_remote_servers>
  <bi_cluster>
    <shard>
      <weight>1</weight>
      <internal_replication>true</internal_replication>
      <replica>
        <host>dc-o-ch-11</host>
        <port>9000</port>
      </replica>
    </shard>
    <shard>
      <weight>1</weight>
      <internal_replication>true</internal_replication>
      <replica>
        <host>dc-o-ch-12</host>
        <port>9000</port>
      </replica>
    </shard>
    <shard>
      <weight>1</weight>
      <internal_replication>true</internal_replication>
      <replica>
        <host>dc-o-ch-13</host>
        <port>9000</port>
      </replica>
    </shard>
  </bi_cluster>
</clickhouse_remote_servers>
```

**Comment by den-crane** [comment]
Please provide `show create table bi.launcher_tab_play_long2 ` output

**Comment by VitoLiao** [comment]
> Please provide `show create table bi.launcher_tab_play_long2 ` output

Thanks for your reply, and here it is
```sql
CREATE TABLE bi.launcher_tab_play_long2
(
  `recordDate`  String,
  `deviceType`  String,
  `licenceName` String,
  `tabName`     String,
  `columnsID`   String,
  `columnsName` String,
  `resourceID`  String,
  `movieName`   String,
  `channel`     String,
  `playLong`    Float64,
  `vv`          UInt64,
  `uv`          UInt64
) ENGINE = MergeTree PARTITION BY recordDate ORDER BY recordDate SETTINGS index_granularity = 8192
```

**Comment by BernieJiangDL** [comment]
> > Please provide `show create table bi.launcher_tab_play_long2 ` output
> 
> Thanks for your reply, and here it is
> 
> ```sql
> CREATE TABLE bi.launcher_tab_play_long2
> (
>   `recordDate`  String,
>   `deviceType`  String,
>   `licenceName` String,
>   `tabName`     String,
>   `columnsID`   String,
>   `columnsName` String,
>   `resourceID`  String,
>   `movieName`   String,
>   `channel`     String,
>   `playLong`    Float64,
>   `vv`          UInt64,
>   `uv`          UInt64
> ) ENGINE = MergeTree PARTITION BY recordDate ORDER BY recordDate SETTINGS index_granularity = 8192
> ```

The engine should be ReplicatedMergeTree instead of mergeTree.

**Comment by VitoLiao** [comment]
> > > Please provide `show create table bi.launcher_tab_play_long2 ` output
> > 
> > 
> > Thanks for your reply, and here it is
> > ```sql
> > CREATE TABLE bi.launcher_tab_play_long2
> > (
> >   `recordDate`  String,
> >   `deviceType`  String,
> >   `licenceName` String,
> >   `tabName`     String,
> >   `columnsID`   String,
> >   `columnsName` String,
> >   `resourceID`  String,
> >   `movieName`   String,
> >   `channel`     String,
> >   `playLong`    Float64,
> >   `vv`          UInt64,
> >   `uv`          UInt64
> > ) ENGINE = MergeTree PARTITION BY recordDate ORDER BY recordDate SETTINGS index_granularity = 8192
> > ```
> 
> The engine should be ReplicatedMergeTree instead of mergeTree.

Yeah, I know that ReplicatedMergeTree can works, but we have only 3 servers and needn't make data replicated,and I wonder why CH can't support 'alter table xxx on cluster drop partition xxx' operation on MergeTree but ReplicatedMergeTree?

**Comment by filimonov** [comment]
It is rather a bug, similar to https://github.com/ClickHouse/ClickHouse/issues/3268

Workaround - create one more cluster which will list all nodes as shards, and run DDL on that.

**Comment by den-crane** [comment]
@VitoLiao you just need to change `<internal_replication>true</internal_replication>` to
`<internal_replication>false</internal_replication>`
