### ISSUE TITLE
Ideal schema for log files?

### ISSUE THREAD

**Issue by nwmcsween** [ClickHouse/ClickHouse#10762]
Assuming no structure and just generic log format I've come up with this:

````
create table if not exists logging.logs (
  id        Uint64                             /* process id, etc */
  host      LowCardinality(String)  /* hostname */
  tags      String                           /* tags */
  content   String,
  timestamp DateTime Codec(DoubleDelta, LZ4)

  index tags_index (lower(tags), tags) tokenbf_v1(3, 256, 2, 0) granularity 8
  index content_index (lower(content), content) tokenbf_v1(3, 256, 2, 0) granularity 8
) ....
````

Is there any issues with this schema, should it be extended or will I end up with headaches down the road?

**Comment by den-crane** [comment]
It's completely depends on your queries.
You can make `partition by toYYYYMMDD(timestamp) order by host, timestamp` or  `partition by to toYYYYMM(timestamp) order by toDate(timestamp)` 
Or you can you can create additional table -- `tags (tags_key)` and create logging.logs `partition by toYYYYMMDD(timestamp) order by tags_key`
