### ISSUE TITLE
Adding other parameters to Replicated non-primary MergeTree types not clearly documented

### ISSUE THREAD

**Issue by jakesyl** [ClickHouse/ClickHouse#10771]
I'd submit a PR to fix this, but it's not clear to me how to best achieve this the way the current documentation is structured. This applies for almost everything but the `MergeTree()` engine, but I'll use `ReplicatedReplacingMergeTree()` as an example since this is where I ran into some brief confusion.

So the documentation around using the `ver` argument for the `ReplacingMergeTree() engine is pretty clear`:

![image](https://user-images.githubusercontent.com/6392429/81470891-5d647d00-91bb-11ea-88b2-0eefd69e8757.png)

Where it gets fuzzy is when this becomes `Replicated`. There's no documentation on the order the zookeeper arguments go with reference to the `ver` argument. The only way I could figure this out quickly was by checking out [this test](https://github.com/ClickHouse/ClickHouse/blob/97f2a2213e754ba25dabba4bc8ddf507cd67660c/tests/queries/0_stateless/00620_optimize_on_nonleader_replica_zookeeper.sql#L5)

![image](https://user-images.githubusercontent.com/6392429/81470916-8c7aee80-91bb-11ea-9c10-8798f6c0a650.png)

So I think this should be made clearer in the docs either on individual `Replicated[type]MergeTree` pages (which don't currently exist) or on the `ReplicatedMergeTree` page

**Comment by BayoNet** [comment]
Thanks for your participation. I'll add it to the https://clickhouse.tech/docs/en/engines/table-engines/mergetree-family/replication/ page because the order of the parameters is a common rule for all the Replicated*MergeTree engines.

**Comment by jakesyl** [comment]
Awesome, thanks @BayoNet
