### ISSUE TITLE
Introduce io_uring support to ClickHouse

### ISSUE THREAD

**Issue by chhetripradeep** [ClickHouse/ClickHouse#10787]
Linux kernel has released a new asynchronous I/O APIs : [io_uring](https://unixism.net/loti/) and has added support for all network and disk I/O syscalls over last 1.5 year and it looks very promising.

Few of the other project has started adopting it and have seen performance benefits:
- Ceph: https://github.com/ceph/ceph/pull/27392
- Qemu: https://lists.gnu.org/archive/html/qemu-devel/2019-07/msg06733.html

Many others frameworks like Netty are planning to adopt it too: https://twitter.com/normanmaurer/status/1257597649705893888

In context with the scale at which everyone runs clickhouse, I think it will be of great performance improvement.

**Comment by alexey-milovidov** [comment]
Now we have the notion of `read_method` to select between various read engines.
And we can start experimenting with io_uring.

CC @azat maybe you will find this interesting?

**Comment by azat** [comment]
>CC @azat maybe you will find this interesting?

Yep, this idea already visited me (added these to my internal to-do/to-look list)

**Comment by alexey-milovidov** [comment]
There was an experiment adding uring by @sauliusvl 
Unfortunately, it proves to be unsustainable.

There is only a marginal improvement in performance. But the code becomes way more complicated. It became so complicated that even an experienced C++ engineer cannot figure out why there are rare hangs of queries.

**Comment by alexey-milovidov** [comment]
Done.

**Comment by REASY** [comment]
Linking PR that has added io_uring support 
https://github.com/ClickHouse/ClickHouse/pull/36103
