### ISSUE TITLE
Materialized view from ReplacingMergeTree loosing data

### ISSUE THREAD

**Issue by inakivb** [ClickHouse/ClickHouse#10789]
Hello,

I've created a Materialized view that is loosing new rows.

I have a table with this structure 
```SQL
CREATE TABLE AAAAA.hits (
  UserID UUID,
  SessionID UUID,
  PageID UUID,
  siteID UInt32,
  editorialID UInt64,
  EventTime DateTime,
  EventDate Date,
  UTMSource String,
  UTMMedium String,
StartTime DateTime,
  RequestNum UInt32,

 ....

  ) ENGINE = ReplacingMergeTree(RequestNum) PARTITION BY (toYYYYMM(EventDate),siteID)
ORDER BY
  (
    EventDate,
    siteID,
    editorialID,
    cityHash64(UserID),
    cityHash64(SessionID),
    cityHash64(PageID)
  ) SAMPLE BY cityHash64(UserID) SETTINGS index_granularity = 8192
```
And a MATERIALIZED VIEW with this structure

```SQL
CREATE MATERIALIZED VIEW AAA.hits_daily
ENGINE = AggregatingMergeTree() PARTITION BY (toYYYYMM(EventTime),siteID) ORDER BY (siteID,editorialID,EventTime,PageType,IsMobile,UTMSource,UTMMedium,UTMCampaign)
POPULATE
AS SELECT
  siteID,
  editorialID,
  toStartOfDay(StartTime) as EventTime,
  PageType,
  IsMobile,
  UTMSource,
  UTMMedium,
  UTMCampaign,
  groupUniqArray(UserID) as UserIds,
  any(URLDomain) as URLDomain,
  uniq(UserID) as UserCount,
  uniq(PageID) as PageCount,
  AVG(Duration) as AvgDuration,
  AVG(Scroll) as AvgScroll,

....

  FROM AAA.hits GROUP BY siteID,editorialID,toStartOfDay(StartTime),PageType,IsMobile,UTMSource,UTMMedium,UTMCampaign
```

all the previous information is properly populated with the `POPULATE` but huge percentage of new rows are lost after creation in the materialized view.

Here you could find an image attached with the difference starting on 2020-05-07 that the view was created
![image](https://user-images.githubusercontent.com/8626495/81507489-18952f00-92fe-11ea-938b-e5bce2825458.png)

I'm using last stable release of clickhouse on Ubuntu 16.04
Is there something I'm missing?

Thank you!

**Comment by den-crane** [comment]
You have to use aggregatingFunctions or simpleAggregatingFunctions with AggregatingMergeTree

groupUniqArrayState(UserID) as UserIds
uniqState(UserID) as UserCount,
uniqState(PageID) as PageCount,
avgState(Duration) as AvgDuration,
avgState(Scroll) as AvgScroll,

https://gist.github.com/den-crane/32cac4f069f4227b35ab86553bbc649b
https://gist.github.com/den-crane/048ce66bc59f5577d56e42d76934682e
https://gist.github.com/den-crane/a72614fbe6d23eb9c2f1bce40c66893f
https://gist.github.com/den-crane/6eff375752a236a456e1b3dc2ca7db62

**Comment by inakivb** [comment]
Solved!

Thank you @den-crane !
