### ISSUE TITLE
Usability improvements of performance test.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#10790]
The new comparison-based performance test is very powerful but not convenient to use.
Let's collect feature requests to make it better.

1. Remove ugly extra escaping of queries in HTML report.
* [x] Provide some average metric of difference across test groups and as a whole. It is intended to measure general changes in compiler options. Now we have mean change for tests with changed queries, also need geometric mean for all queries, and maybe CDF plots for time change.
3. Provide info about how many times every query was run. Also it's reasonable to provide comparison as statistics summary plot (box plot).
4. Overview histogram of all queries, sorted by amount of change and colored by the type of result, optionally grouped by test groups.
5. It's very difficult to extract flame graphs. Make them available by direct links.
6. Firefox web browser fails to open these files from terminal: `$ firefox 'SELECT count() FROM numbers(10000000) WHERE NOT ignore(trim(LEADING \'\''012345\'\'' FROM toString(number))).right.svg'`, I had to rename them before open.
7. It's a pain to find these files. Put them in directories named as test groups.
9. Save every single run of every query into public ClickHouse instance... also export all trace_log. We should be able to calculate all the reports dynamically from raw data.
10. Clearly indicate the level of statistical significance and mark the result as "green" if the number of individual outliers is statistically expected.
11. If a few queries has been changed, rerun them more times for more confidence.
13. Improve error messages that are cryptic and indecent: `Code: 62, e.displayText() = DB::Exception: Cannot parse columns declaration list. (version 20.5.1.3317)`.
* [x] Publish progress in the check status when it is running -- e.g. `15/100 tests finished`
* [ ] Fail with good errors where is no disk space left. Now we have an empty report: https://clickhouse-test-reports.s3.yandex.net/11971/2efca8e397ce2fd4466ea0e2da9813f7615768f9/performance_comparison/report.html#fail1
* [x] Fix the thing where the master chosen for comparison is too new, because github has updated the pull/*/merge since we've built the binary, and the performance comparison task thinks it uses a newer branch than it atcually does.
* [x] "Short" queries are now determined implicitly, when query run time is below 0.02 s. This can lead to subtle errors when the author didn't want a short query, but it is hard to notice that the query is treated as "short". To fix this, require explicit annotations for short queries -- e.g. `<query short="true">`.
* [x] When adding a test that uses new function, it can't run on old version. PR author and reviewer can't check that their query runs and that it's stable and has appropriate run time, so they have to fix it after merging the PR, in master. This is inconvenient. Provide a special mode for queries that can't run on old version. Don't make a comparison for them, but show the query time and deviation, and report errors if it's not satisfactory. -- added "Partial queries"
* [x] Ignore unknown settings and still run the query -- can be useful for cases when a new setting is introduced in a PR.
* [x] It's unclear how to compare flame graphs. I see some difference but I cannot figure out anything from it. Provide some kind of differential flame graphs, or just differential report as a table. -- We now have differential flame graphs.
* [x] Provide a means to quickly evaluate correctness of test XML files from local machine without Docker. -- see https://github.com/ClickHouse/ClickHouse/tree/master/docker/test/performance-comparison#run-a-single-test-on-the-already-configured-servers

**Comment by akuzm** [comment]
A couple of issues introduced in https://github.com/ClickHouse/ClickHouse/pull/10773:
* red-green color contrast is not accessible for people with deuteranopia
* measurement units are not abbreviations, periods are not used after them

**Comment by alexey-milovidov** [comment]
Ok. Only one checkbox is unchecked and it is not very important.
Considering this task done :rocket:

**Comment by alexey-milovidov** [comment]
But there is strange markup and I see that

> Remove ugly extra escaping of queries in HTML report.

is not fixed yet.

**Comment by alexey-milovidov** [comment]
> It's very difficult to extract flame graphs. Make them available by direct links.

Also not implemented. Maybe @nikitamikhaylov will do.
