### ISSUE TITLE
Change log error "DNS error: EAI: -9" to "Can`t use ipv6"

### ISSUE THREAD

**Issue by patsevanton** [ClickHouse/ClickHouse#10813]
I very long time search can't understend why clickhouse don't run.
Error "DNS error: EAI: -9" not show information about problem.

Related issue
https://github.com/ClickHouse/ClickHouse/issues/2987
https://github.com/ClickHouse/ClickHouse/issues/4406
https://github.com/ClickHouse/ClickHouse/issues/5983

**Comment by alexey-milovidov** [comment]
It's an issue of Poco library, we have to patch it:
https://clickhouse.tech/codebrowser/html_report/ClickHouse/contrib/poco/Net/src/DNS.cpp.html#392
And it's rather easy to do.

It should use the `gai_strerror` function.
