### ISSUE TITLE
play.clickhouse.tech displays Int64 incorrectly 9223372033328794000 instead of 9223372033328793741

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#10824]
```

SELECT '- '||toString(max(WatchID))||' -', max(WatchID), toString(max(WatchID)) 
FROM hits_100m_obfuscated
where WatchID = 9223372033328793741


- 9223372033328793741 - | 9223372033328794000   | 9223372033328794000

```
https://stackoverflow.com/questions/61739114/condition-on-uint64-field-in-where-clause-in-clickhouse/61740693#61740693

```
select toUInt64(-1) x, toString(x) y, '['||y||']'
18446744073709552000 | 18446744073709552000 | [18446744073709551615]
```

```
JS issue

> d=18446744073709551615
18446744073709552000
> d='18446744073709551615'
'18446744073709551615'
```

**Comment by filimonov** [comment]
A bit too long opened for crit. Any movements here?

**Comment by alexey-milovidov** [comment]
@qoega ?

**Comment by alexey-milovidov** [comment]
In version 20.11 we have completely new web UI:
http://localhost:8123/play
that does not have such an embarrassing issue.

It's still in question, if the Playground even theoretically fixable, see https://github.com/ClickHouse/clickhouse-playground/issues

**Comment by alexey-milovidov** [comment]
We will close the old Playground unless the issues will be fixed:
https://github.com/ClickHouse/clickhouse-playground/issues

**Comment by alexey-milovidov** [comment]
There are more complaints about playground from external users: 
https://habr.com/en/company/tensor/blog/536696/#comment_22528138

**Comment by alexey-milovidov** [comment]
Replacing it with https://gh-api.clickhouse.tech/play?user=play looks viable, only need to add "Powered by Yandex.Cloud" link.

**Comment by sundy-li** [comment]
Hello, another issue about play web is to support `MetaKey + Enter` hotkey to execute query (it's common used in macos). 

But it's not javascript standard to have that.  Can we have jquery.min.js  dependency? (The origin style may not be happy)

**Comment by alexey-milovidov** [comment]
JQuery is a bit too large for this small feature (and also it's old-fashioned).
Maybe just add `metaKey` here?: https://github.com/ClickHouse/ClickHouse/blob/master/programs/server/play.html#L430

**Comment by sundy-li** [comment]
> https://github.com/ClickHouse/ClickHouse/blob/master/programs/server/play.html#L430

I tried, it never works. Because meta key is not awarded by Javascript.

**Comment by alexey-milovidov** [comment]
Maybe just extract the snippet to detect meta key from jQuery?
