### ISSUE TITLE
Is table TTL replicated?

### ISSUE THREAD

**Issue by Zer0Divis0r** [ClickHouse/ClickHouse#10842]
Does the command ALTER TABLE MODIFY TTL replicates to other replicas?

If yes, do other replicas must have the same storage policy (or policy name?) and same disks/volumes names? 

This is not clear from, the docs: it says "different storage policies can be specified for the same table on different replicas", but it looks like TTL still has to be identical.

**Comment by Zer0Divis0r** [comment]
@excitoon , any news? I am eager to implement data life cycles, but there is this blank point about replication. Thanks.

**Comment by alexey-milovidov** [comment]
Need help from @excitoon

**Comment by alexey-milovidov** [comment]
@excitoon did not respond.

**Comment by alexey-milovidov** [comment]
@excitoon did not help to answer this issue.

As far as I know, the TTL still has to be identical.
I don't like the feature of TTL MOVE and prefer automatic data movement by disk space.
