### ISSUE TITLE
Incorrect batch insert data

### ISSUE THREAD

**Issue by shizhenchina** [ClickHouse/ClickHouse#10845]
(you don't have to strictly follow this form)

**Describe the bug**
I use https://github.com/housepower/ClickHouse-Native-JDBC and https://github.com/ClickHouse/clickhouse-jdbc in two ways, when inserting data, has appeared in a total number is correct, but writes data column of chaotic situation.For example, the original data is ('aaa',...', 'aaa'), turns out to be ('aaa'..., 'BBB').This' BBB 'should be some other row

**How to reproduce**
* Which ClickHouse server version to use
19.17.4.11

* Which interface to use, if matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
`CREATE TABLE log_center.basiclog_gw_admin ON CLUSTER ck_cluster2
(
  timestamp DateTime,
  http_x_request_id String,
  traceId String,
  server_name String,
  upstream_status String,
  request String,
  request_length UInt32,
  http_x_app_id String,
  upstr_addr String, 
  hostname String,
  request_method String,
  http_cookie String,
  body_bytes_sent UInt32,
  http_user_agent String,
  remote_user String,
  xes_request_type String,
  remote_addr String,
  request_body String,
  xes_app String,
  http_referrer String,
  connection_requests UInt32,
  url String, 
  upstream_response_time String, 
  status UInt16,
  rpcId String,
  http_x_forwarded_for String,
  request_time Float64,
  scheme String
) ENGINE = ReplicatedMergeTree('/clickhouse/tables/{layer}-{shard}/log_center/basiclog_gw_admin', '{replica}') 
PARTITION BY toDate(timestamp) 
ORDER BY (timestamp) 
TTL timestamp + toIntervalDay(30)
SETTINGS index_granularity = 8192,storage_policy='ssd';

CREATE TABLE log_center.basiclog_gw_admin_all ON CLUSTER ck_cluster2 AS log_center.basiclog_gw_admin ENGINE = Distributed(ck_cluster2, log_center, basiclog_gw_admin, rand());`

* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

**Expected behavior**
`select count(*) from basiclog_gw_admin_all where server_name='xxx' AND domain!='xxx' ;`
It should be 0, but it's greater than 0

**Error message and/or stacktrace**
no error

**Additional context**

**Comment by den-crane** [comment]
1. I don't see `domain` column in your tables.
2. Need datasample/insert queries to reproduce

**Comment by shizhenchina** [comment]
1.Sorry, domain is a later column that I forgot to write down.
2. I will send the datasample/insert queries later

**Comment by shizhenchina** [comment]
`public class ClickHouse3Sink implements AllWindowFunction<CommonData, Object, TimeWindow> {

    static {

    }

    @Override
    public void apply(TimeWindow timeWindow, Iterable<CommonData> iterable, Collector<Object> collector) throws Exception {
        Connection connection = null;
        PreparedStatement pstmt = null;
        try {
            Class.forName("ru.yandex.clickhouse.ClickHouseDriver");
            connection = DriverManager.getConnection("jdbc:clickhouse://ip:port/log_center","default","");
            String sql = "insert into log_center.basiclog_gw_admin_all " +
                    "values(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
            pstmt = connection.prepareStatement(sql);
        } catch (Exception e) {
            e.printStackTrace();
        }

        for (CommonData commonData : iterable){
            if (commonData == null){
                break;
            }
            Date date = DateUtil.getDate("yyyy-MM-dd HH:mm:ss",
                    StringUtils.trimString(commonData.getTimestamp(),"+08:00").replace("T"," "));
            pstmt.setTimestamp(1,new Timestamp(date.getTime()-8*60*60*1000));
            pstmt.setString(2,commonData.getHttp_x_app_id());
            pstmt.setString(3,commonData.getTraceId());
            pstmt.setString(4,commonData.getServer_name());
            pstmt.setString(5,commonData.getUpstream_status());
            pstmt.setString(6,commonData.getRequest());
            pstmt.setInt(7,commonData.getRequest_length());
            pstmt.setString(8,commonData.getHttp_x_app_id());
            pstmt.setString(9,commonData.getUpstr_addr());
            pstmt.setString(10,commonData.getHostname());
            pstmt.setString(11,commonData.getRequest_method());
            pstmt.setString(12,commonData.getHttp_cookie());
            pstmt.setInt(13,commonData.getBody_bytes_sent());
            pstmt.setString(14,commonData.getHttp_user_agent());
            pstmt.setString(15,commonData.getRemote_user());
            pstmt.setString(16,commonData.getXes_request_type());
            pstmt.setString(17,commonData.getRemote_addr());
            pstmt.setString(18,commonData.getRequest_body());
            pstmt.setString(19,commonData.getXes_app());
            pstmt.setString(20,commonData.getHttp_referrer());
            pstmt.setInt(21,commonData.getConnection_requests());
            pstmt.setString(22,commonData.getUrl());
            pstmt.setString(23,commonData.getUpstream_response_time());
            pstmt.setShort(24,commonData.getStatus());
            pstmt.setString(25,commonData.getRpcId());
            pstmt.setString(26,commonData.getHttp_x_forwarded_for());
            pstmt.setDouble(27,commonData.getRequest_time());
            pstmt.setString(28,commonData.getScheme());
            pstmt.setString(29,commonData.getDomain());
            pstmt.addBatch();
        }
        try {
            pstmt.executeBatch();
            pstmt.clearBatch();
            pstmt.close();
            if (connection!=null)
                connection.close();
        }catch (Exception e){
            e.printStackTrace();
        }
    }
}
`
This is how I insert data into clickhouse.For the data source, I created several pieces of data randomly, where the values of domain and server_name are the same.Here is an example of a log

`{
    "@timestamp":"2020-05-12T20:52:51+08:00",
    "hostname":"xxxxx",
    "domain":"test.com",
    "server_name":"test.com",
    "http_x_forwarded_for":"-",
    "xes-app":"XXXX",
    "remote_addr":"10.20.30.71",
    "remote_user":"-",
    "body_bytes_sent":5719,
    "request_time":0.003,
    "upstream_response_time":"0.003",
    "status":200,
    "upstream_status":"200",
    "connection_requests":1,
    "request":"POST /pzcenter/getAppDownloadFileInfo HTTP/1.1",
    "request_length":"1842",
    "request_method":"POST",
    "request_body":"-",
    "http_referrer":"-",
    "http_cookie":"-",
    "http_user_agent":"-",
    "url":"test.com/",
    "upstr_addr":"XXXX",
    "request_trace_id":"736d96c01ae4dba4e5caa963a2b004ae",
    "xes-request-type":"-",
    "traceId":"-",
    "rpcId":"-"
}`

**Comment by shizhenchina** [comment]
I used flink by mistake
