### ISSUE TITLE
'if' function not working with Nullable condition.

### ISSUE THREAD

**Issue by LittleMaverick** [ClickHouse/ClickHouse#10846]
I try to execute such query:
`SELECT if(isFinite(toUInt64OrZero(toNullable('123'))), 1, 0)`

But it throws an exception:

`Code: 44, e.displayText() = DB::Exception: Illegal column Const(Nullable(UInt8)) of first argument of function if. Must be ColumnUInt8 or ColumnConstUInt8. (version 20.3.8.53 (official build))`

`SELECT toTypeName(isFinite(toUInt64OrZero(toNullable('123')))) - Nullable(UInt8) `

**Comment by den-crane** [comment]
WA: SELECT if(materialize(isFinite(toUInt64OrZero(toNullable('123')))), 1, 0)
