### ISSUE TITLE
Got "Sharding key expression does not evaluate to an integer type." when using siphash() to LowCardinality(String)

### ISSUE THREAD

**Issue by liwanxue** [ClickHouse/ClickHouse#10853]
This is about clickhouse sharding key in distributed table. 
I have a  replicatedmergetree table with field A with "LowCardinality(String)" type, and I use  sipHash64(A) as sharding key in distributed table.
But when I set optimize_skip_unused_shards=true, got exception "Sharding key expression does not evaluate to an integer type." when I query distributed table with filter A=xxxx.  

Does this mean sharding key can't apply to string field?  I'm using 19.16.

**Comment by azat** [comment]
So `sipHash64(cast('foo', 'LowCardinality(String)'))`returns `LowCardinality(UInt64)` and sharing key for `LowCardinality` has been fixed in #10611
