### ISSUE TITLE
Ideas on how to rework cache dictionaries.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#10863]
The code of cache dictionaries is unnesessarily complicated.

1. Template specialization on types (all integers and strings) is unnecessary.
2. It does not make sense to have separate `cache` and `complex_key_cache` - the performance of generic case won't be lower.
3. It stores all attributes in separate hash tables that leads to higher complexity and higher memory usage. Instead, let's serialize all attributes of every record into single contiguous memory region (in ArenaWithFreeLists) along with offsets to every column. This will also allow to support more data types. Serialize and desirialize with IColumn methods.
4. Intrusive LRU linked list may work better than cache table and as we collect all attributes together, memory overhead won't be high.

We can create new type of dictionary layout, then provide for `cache` and `complex_key_cached` and remove their code.

**Comment by nikitamikhaylov** [comment]
I looked throw some articles. Here are the best 

[High-Throughput, Thread-Safe, LRU Caching from Ebay](https://tech.ebayinc.com/engineering/high-throughput-thread-safe-lru-caching/)

[High Concurrency LRU Caching written in Go](https://www.openmymind.net/High-Concurrency-LRU-Caching/)

[Just cool idea](https://www.codeproject.com/Articles/23396/A-High-Performance-Multi-Threaded-LRU-Cache)

**Comment by kitaisreal** [comment]
Will fix https://github.com/ClickHouse/ClickHouse/issues/20194
