### ISSUE TITLE
A setting date_time_output_format.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#10862]
With values `simple`, `iso` and `unix_timestamp`.

Simple: `2010-10-31 02:30:00`
ISO: `2010-10-31T02:30:00+03:00`
Unix timestamp: `1288481400`

**Comment by hhell** [comment]
> With values `simple`, `iso` and `unix_timestamp`

A more general way would be to support date formatting expressions in the setting,
i.e. modifiers from https://clickhouse.tech/docs/en/single/#formatdatetime
But for that, the timestamp and tzoffset would need to be added as modifiers too.

**Comment by hhell** [comment]
> date formatting

Related: should this option affect `toString(toDateTime(…))`?

**Comment by alexey-milovidov** [comment]
> Related: should this option affect toString(toDateTime(…))?

No, it's only loosely related to output formats.

**Comment by alexey-milovidov** [comment]
Implemented in version 20.11-testing.
