### ISSUE TITLE
Dictionary couldn't update

### ISSUE THREAD

**Issue by wenwen2019** [ClickHouse/ClickHouse#10879]
I created a dictionary, and the data source is mysql table. When I updated the data of mysql table, the dictionary was not updated, and no dictionary could be created. The data source also had local files tested, and as long as the data source was updated, the dictionary could not be updated or created.
the version of the clickhouse is 19.3.7.

**Comment by den-crane** [comment]
Please provide xml with dictionary description ( at least lifecycle / layout , sections)
Do you observe any related messages in `/var/log/clickhouse-server//clickhouse-server.log` ?

**Comment by robot-clickhouse** [comment]
@wenwen2019, do you have any further questions?

**Comment by alexey-milovidov** [comment]
#10725
