### ISSUE TITLE
From Subquery is much slower than expected

### ISSUE THREAD

**Issue by IVitamin-C** [ClickHouse/ClickHouse#10876]
hi
**I am conducting a test, and currently found that the following two sections of SQL have very large performance differences, how should I set up, so that the execution efficiency of the two SQL is not much different**

SQL1:
SELECT app_version AS app_version,
       count(distinct if(connect_net_cnt >= 0,user_id, null)) AS use_user_id_cnt,
       count(distinct if(connect_net_cnt >= 0,user_id, null)) AS connect_user_id_cnt,
       count(distinct multiIf(login_cnt > 0 or is_read_online > 0 or read_time > 0,user_id,null)) AS login_user_id_cnt
FROM
  (
        select ds,
          user_id,
          app_version,
          is_read_online,
          read_time,
          connect_net_cnt,
          login_cnt
   from test1.test1_ck_count_a1
   where platform in ('Android',
                      'IOS')) AS expr_qry
WHERE ds >= toDate('2020-05-06')
  AND ds <= toDate('2020-05-13')
GROUP BY app_version
ORDER BY use_user_id_cnt DESC
LIMIT 10000;
time:
605 rows in set. Elapsed: 36.904 sec. Processed 475.89 million rows, 37.58 GB (12.90 million rows/s., 1.02 GB/s.)

SQL2:
select app_version AS app_version,
       count(distinct if(connect_net_cnt >= 0, user_id, null)) AS use_user_id_cnt,
       count(distinct multiIf(login_cnt > 0 or is_read_online > 0 or read_time > 0, user_id,null)) AS login_user_id_cnt
   from test1.test1_ck_count_a1
   where platform in ('Android',
                      'IOS')
and ds >= toDate('2020-05-06')
  AND ds <= toDate('2020-05-13')
GROUP BY app_version
ORDER BY use_user_id_cnt DESC
LIMIT 10000;
time:
605 rows in set. Elapsed: 8.087 sec. Processed 475.89 million rows, 37.58 GB (58.85 million rows/s., 4.65 GB/s.)
TABLE INFO:
The total number of rows in the table is 2.2 billion and the size is 68.89 GiB
CREATE TABLE:

CREATE  TABLE  test.test1_ck_count_a1  on cluster *****
(
    ds DATE,
    user_id String DEFAULT '',
    app_version String DEFAULT '',
    is_read_online Int32 DEFAULT -1,
    read_time Float64 DEFAULT 0.0,
    connect_net_cnt Int64 DEFAULT 0,
    login_cnt Int64 DEFAULT 0
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/test1.test1_ck_count_a1', '{replica}')
PARTITION BY toYYYYMMDD(ds)
ORDER BY (user_id)
SETTINGS index_granularity = 8192

CREATE  TABLE  test1.test1_ck_count_a1  on cluster *****
(
    ds DATE,
    user_id String DEFAULT '',
    app_version String DEFAULT '',
    is_read_online Int32 DEFAULT -1,
    read_time Float64 DEFAULT 0.0,
    connect_net_cnt Int64 DEFAULT 0,
    login_cnt Int64 DEFAULT 0
)
ENGINE = Distributed(*******, 'test', 'test1_ck_count_a1', rand())

Is my configuration not modified correctly, or is the index not effective for such a subquery？

Thanks

**Comment by IVitamin-C** [comment]
clickHouse version:20.3.5
The cluster has 10 nodes, each node has 64 cores and 256G memory

**Comment by den-crane** [comment]
It's an expected behavior. Only first level of `( )`  (expr_qry) inside brackets is executed on shards. Everything outside brackets is executed at an initiator. So the single server does groupby in the first query and more ungroupped data volume needed to be transferred from shards to the initiator.

**Comment by IVitamin-C** [comment]
> It's expected behavior. Only first level of `( )` (expr_qry) inside brackets is executed on shards. Everything outside brackets is executed at an initiator. So only one server does groupby in the first query and it needed more ungroupped data volume to be transferred from shards to the initiator.


I think this query scenario is very common, such as superset. In this case, the syntax requirements are too strict
