### ISSUE TITLE
clickhouse-copier Exception: Empty query

### ISSUE THREAD

**Issue by byx313** [ClickHouse/ClickHouse#10881]
hello guys,I met a error when I use clickhouse-copier.
ch version:19.9.5.36
error info:

> 2020.05.13 17:12:46.059558 [ 1 ] {} <Error> : virtual int DB::ClusterCopierApp::main(const std::vector<std::basic_string<char> >&): Code: 62, e.displayText() = DB::Exception: Empty query, Stack trace:

0. clickhouse-copier(StackTrace::StackTrace()+0x16) [0x65cbc16]
1. clickhouse-copier(DB::Exception::Exception(std::string const&, int)+0x1f) [0x2ffea8f]
2. clickhouse-copier(DB::parseQuery(DB::IParser&, std::string const&, unsigned long)+0x20a) [0x641e6ea]
3. clickhouse-copier() [0x30af203]
4. clickhouse-copier(DB::ClusterCopier::init()+0x43a) [0x30b0a8a]
5. clickhouse-copier(DB::ClusterCopierApp::mainImpl()+0x5fa) [0x30a096a]
6. clickhouse-copier(DB::ClusterCopierApp::main(std::vector<std::string, std::allocator<std::string> > const&)+0x1a) [0x2fe046a]
7. clickhouse-copier(Poco::Util::Application::run()+0x26) [0x677b836]
8. clickhouse-copier(mainEntryClickHouseClusterCopier(int, char**)+0x9a) [0x309d81a]
9. clickhouse-copier(main+0x22e) [0x2fd60ce]
10. /lib64/libc.so.6(__libc_start_main+0xfd) [0x31a541ed5d]
11. clickhouse-copier() [0x2ffae49]
 (version 19.9.5.36)

its my schema.xml

> <yandex>
    
    <remote_servers>
        <source_cluster>
            <shard>
                <weight>1</weight>
                    <replica>
                        <host>127.0.0.1</host>
                       
                        <port>19008</port>
                    </replica>
            </shard>
        </source_cluster>

        <destination_cluster>
            <shard>
                <weight>1</weight>
                    <replica>
                        <host>[ip]</host>
                        <port>19008</port>
                    </replica>
            </shard>
        </destination_cluster>
    </remote_servers>
    <max_workers>2</max_workers>
    <settings_pull>
        <readonly>1</readonly>
    </settings_pull>
    <settings_push>
        <readonly>0</readonly>
    </settings_push>
    <settings>
        <connect_timeout>3</connect_timeout>
        
        <insert_distributed_sync>1</insert_distributed_sync>
    </settings>
    
    <tables>
        
        <table_hits>
            
            <cluster_pull>[CLUSTER]</cluster_pull>
            <database_pull>[DATABASE]</database_pull>
            <table_pull>[TABLE]</table_pull>
            
            <cluster_push>[CLUSTER]</cluster_push>
            <database_push>[DATABASE]</database_push>
            <table_push>[TABLE]</table_push>
            
            <sharding_key>rand()</sharding_key>
            <engine/>
            <enabled_partitions>
                <partition>'2019-02-26'</partition>
            </enabled_partitions>
        </table_hits>
    </tables>
</yandex>

Hope for replying!

**Comment by nikitamikhaylov** [comment]
Hello! Your `schema.xml` is  not informative. You don't provide us any information, especially table schema. However I noticed that you have an error near the tag '**engine**'. I think the problem is that you didn't specify the engine of your table. That's why copier сan't parse this (empty string). Please read this article [from Altinity blog.](https://www.altinity.com/blog/2018/8/22/clickhouse-copier-in-practice).

**Comment by byx313** [comment]
> Hello! Your `schema.xml` is not informative. You don't provide us any information, especially table schema. However I noticed that you have an error near the tag '**engine**'. I think the problem is that you didn't specify the engine of your table. That's why copier сan't parse this (empty string). Please read this article [from Altinity blog.](https://www.altinity.com/blog/2018/8/22/clickhouse-copier-in-practice).

thx for the reply.
I specify the empty `engine` because I have create the table manually.I will try your suggestion.

**Comment by byx313** [comment]
> Hello! Your `schema.xml` is not informative. You don't provide us any information, especially table schema. However I noticed that you have an error near the tag '**engine**'. I think the problem is that you didn't specify the engine of your table. That's why copier сan't parse this (empty string). Please read this article [from Altinity blog.](https://www.altinity.com/blog/2018/8/22/clickhouse-copier-in-practice).

thanks my man,I delete the table created before and add the `engine` tag,it works.but I still think it's a bug,because the official document never mention we can't create the table manually before.

**Comment by byx313** [comment]
> Hello! Your `schema.xml` is not informative. You don't provide us any information, especially table schema. However I noticed that you have an error near the tag '**engine**'. I think the problem is that you didn't specify the engine of your table. That's why copier сan't parse this (empty string). Please read this article [from Altinity blog.](https://www.altinity.com/blog/2018/8/22/clickhouse-copier-in-practice).

I do the test.I create the table manually and i still specify the `engine` tag,it works well.It seems that the `engine` tag can not be empty.
