### ISSUE TITLE
Broker: Request timed out on ClickHouse engine=Kafka

### ISSUE THREAD

**Issue by brefre** [ClickHouse/ClickHouse#10884]
Hi,

I have five servers running "identical workload", they are all run 18.12.17, except for one that is running 20.3.8.53. The new version has a lower workload, as it only ingests data, and is not queried.

Unfortunately I'm getting errors in the log (only the 20.3.8.53 version has this problem):

```
2020.05.12 21:03:03.465847 [ 11164 ] {} <Error> void DB::StorageKafka::threadFunc(): std::exception. Code: 1001, type: cppkafka::HandleException, e.what() = Broker: Request timed out, Stack trace (when copying this message, always include the lines below):

0. cppkafka::HandleException::HandleException(cppkafka::Error) @ 0xb98c69a in /usr/bin/clickhouse
1. ? @ 0x4e95323 in /usr/bin/clickhouse
2. DB::ReadBufferFromKafkaConsumer::commit() @ 0x979b234 in /usr/bin/clickhouse
3. DB::KafkaBlockInputStream::commit() @ 0x9787eb5 in /usr/bin/clickhouse
4. DB::StorageKafka::streamToViews() @ 0x9385930 in /usr/bin/clickhouse
5. DB::StorageKafka::threadFunc() @ 0x938636c in /usr/bin/clickhouse
6. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x939fb77 in /usr/bin/clickhouse
7. DB::BackgroundSchedulePool::threadFunction() @ 0x93a014a in /usr/bin/clickhouse
8. ? @ 0x93a024d in /usr/bin/clickhouse
9. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x4ffe407 in /usr/bin/clickhouse
10. ? @ 0x4ffca5f in /usr/bin/clickhouse
11. start_thread @ 0x7dc5 in /usr/lib64/libpthread-2.17.so
12. clone @ 0xf776d in /usr/lib64/libc-2.17.so
 (version 20.3.8.53)
2020.05.12 21:03:03.465896 [ 11164 ] {} <Trace> StorageKafka (table_name): Execution took 7334 ms.
```

Question #1: Is this error related to *table_name*, or is it accidental that table_name comes after this exception? I see different tables here, but they are normally kafka-tables with high throughput.

Question #2: What parameters can I tune to prevent this? I have tried to increase various timeouts, but I don't know which causes the error. I guess that I for some topics should increase the commit timeout, or make it commit less often (increasing max_insert_block_size, perhaps?)

I don't think this is a problem with my production kafka cluster, since none of the other four  clickhouse versions has this problem. I also suspect that these errors cause me to either loose data or get duplicates (This is happening for sure, but I'm not sure if it is the clickhouse restarts that causes it, or the errors themselves). 

I want to upgrade the clickhouse version for all my servers, but unfortunately, I cant do this until kafka ingestion is more stable.

**Comment by filimonov** [comment]
Check that: https://github.com/edenhill/librdkafka/issues/1470

So your broker rejected commit because during `offsets.commit.timeout.ms` (5000 by default),
there were not enough replicas available for the `__consumer_offsets` topic.

You can try to increase `offsets.commit.timeout.ms` (on broker side) and/or monitor the status of __consumer_offsets topic. 

We now do few commit retries (check #9884) but we prefer not to continue consumption unless we get the acknowledgment of successful commit (otherwise the risk of duplicates go high).

**Comment by brefre** [comment]
Hi,

Thank you for your response.

It's weird that this is a broker problem, when none of the other servers has the same issue. I grepped my logs, and can see these messages on many of my brokers:

```
[2020-01-15 17:12:53,359] INFO [Partition __consumer_offsets-31 broker=10] Expanding ISR from 10,11,15 to 10,11,15,14 (kafka.cluster.Partition)
```

(This is from a hardware failure that date)

I see no messages after that date.

I have increased session.timeout.ms, as suggested by the link you gave me
```synchronous commit() uses the session.timeout.ms, not socket.timeout.ms.```

```
<session_timeout_ms>30000</session_timeout_ms><!-- 10k default -->  
```

What should I do if I wanted to commit less often? 

I was thinking about increasing these settings:
```
<fetch_max_bytes>
<fetch_message_max_bytes>
<receive_message_max_bytes>
```

**Comment by brefre** [comment]
I also increased retries from 2 to 3, to see if it helps. I don't have many errors during the day, so it takes some time before I can see how it behaves

**Comment by filimonov** [comment]
>What should I do if I wanted to commit less often?

Increase kafka_max_block_size or flush interval

**Comment by brefre** [comment]
I have increased kafka_max_block_size for all large topics, and tried to adjust various other settings, but the errors are still coming (3-4 per day).

I will now try to set  offsets.commit.timeout.ms to 10k for my brokers, and set retries to 4, to see if that helps.

**Comment by brefre** [comment]
This didn't have any effect. I'm setting retries to 10 to see if that will help. 

 Do you have other suggestions of where to look for errors?

**Comment by filimonov** [comment]
You did quite a lot of changes which seems unrelated

Did you read my message above? The only possible reason for the problem was mentioned, together with options to solve. Why do you change all those parameters which has nothing to it? 

read that very carefully, please:

> your broker rejected commit because during offsets.commit.timeout.ms (5000 by default), there were not enough replicas available for the __consumer_offsets topic.

> You can try to increase offsets.commit.timeout.ms (*on broker side*) and/or monitor the status of __consumer_offsets topic.

**Comment by brefre** [comment]
Hi,

Thank you for your patience. I did read your message.

I grepped the logs on all my brokers, and I can see no evidence for the __consumer_offsets topic getting out of sync.

This is the method I used:
`grep -i isr /var/log/kafka/console.log* | grep __consumer_offsets | grep 2020 `

I did find evidence that this happened once in januar, when there was a hardware failure, and once in may, when I restarted all my brokers to apply your suggested change of offsets.commit.timeout.ms

This leads me to conclude:
1) The brokers do log when __consumer_offsets goes out of sync (seen by evidence two times)
2) __consumer_offsets does NOT go out of sync, contrary to your claim (by lack of evidence)
3) There are other reasons clickhouse produces that error

Are there other ways than grepping the logs, you wan't me to verify that __consumer_offsets is in sync? Is there a possibility there is another reason for these error messages in my clickhouse log?

**Comment by filimonov** [comment]
How many brokers do you have, aren't they over loaded? Are they in the same DC? 
Did you try the approach with `request.required.acks`?
Check https://stackoverflow.com/questions/54039216/how-come-kafka-fails-to-commit-offset-for-a-particular-partition and other similar questions

Give a try with clickhouse-20.5 - there is a lot of Kafka related changes there.

**Comment by brefre** [comment]
Hi,

I have 5 brokers with ~90% idle CPU (16 core systems), 80/96GiB ram available, in two racks next to each other. They do not look overloaded.

__consumer_offsets have a replication factor of 4, and min.insync.replicas is 2 

I have gotten some progress by setting kafka_num_consumers = 1, that got rid of most of the duplicate messages, and most of the errors.

I will try setting request.required.acks = 2 today, and see if get's even better.

I'm looking forward to clickhouse-20.5, but I will probably wait for the RPM package by altinity, it's only on 20.3 now.

**Comment by brefre** [comment]
Hi,

I'm now running version 20.5.3.27, and it has been stable for two weeks. 

Initially, I had some problems with messages like these:

```
2020.08.03 00:12:13.542775 [ 29507 ] {} <Warning> StorageKafka (table_name_x): [rdk:SESSTMOUT] [thrd:main]: Consumer group session timed out (in join-state started) after 10000 ms without a successful response from the group coordinator (broker 12, last error was Success): revoking assignment and rejoining group                                                                                                      2020.08.03 00:12:16.619600 [ 29478 ] {} <Error> StorageKafka (table_name_x): Exception during commit attempt: Broker: Unknown member
2020.08.03 00:12:16.822036 [ 29478 ] {} <Error> StorageKafka (table_name_x): Exception during commit attempt: Broker: Unknown member
2020.08.03 00:12:17.024360 [ 29478 ] {} <Error> StorageKafka (table_name_x): Exception during commit attempt: Broker: Unknown member
2020.08.03 00:12:17.226506 [ 29478 ] {} <Error> StorageKafka (table_name_x): Exception during commit attempt: Broker: Unknown member
2020.08.03 00:12:17.428403 [ 29478 ] {} <Error> StorageKafka (table_name_x): Exception during commit attempt: Broker: Unknown member
2020.08.03 00:12:17.430223 [ 29478 ] {} <Error> void DB::StorageKafka::threadFunc(): Code: 518, e.displayText() = DB::Exception: All commit attempts failed. Last block was already written to target table(s), but
 was not commited to Kafka., Stack trace (when copying this message, always include the lines below):       
```               

These errors also caused duplicate data.

After increasing session_timeout_ms from 10k to 60k milliseconds, and I have not had errors or duplicate data since. 

Best regards,
Fredrik
