### ISSUE TITLE
Multiple clusters, same servers

### ISSUE THREAD

**Issue by thyn** [ClickHouse/ClickHouse#10883]
I have  a distributed table with replication (using zookeeper).

```

create table s_actions (...)
PARTITION BY toMonday(createdon)
ORDER BY
  (createdon, user__id) SAMPLE BY user__id SETTINGS index_granularity = 8192
 
```

I have primary replicas with 3 servers with a lot of memory and cpu . Second replica  has slow ssd ,less cpu and ram and is used for replication backup and then daily backups (FREEZE PARTITION).

I have distributed table like

````
 CREATE TABLE actions (
....
) ENGINE = Distributed(
  rep,
  actions,
  s_actions,
  cityHash64(toString(user__id))
)

```` 
rep cluster has only one replica for each shard. So If any server from primary replica fails everything will be broken. I want to create rep_write cluster in clickhouse config with secondary replicas to allow writes to secondary or primary replicas . Reads are not needed to be protected. 

Problem is that I'm using hashing function instead of random to optimize performance. Is it safe to define separate clusters with same (by order) servers (with extra replicas) and use distributed tables with same hashing function?

**Comment by den-crane** [comment]
Yes. It is safe. If you make cluster with the same shards/servers order it will be the same shard numbers. 
You can verify it in `select * from system.clusters`

**Comment by thyn** [comment]
It's great, thank you
