### ISSUE TITLE
Tuple creation functions

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#10882]
**Use case**
We can not construct large Tuples automatically and can't convert arrays to Tuples.
**Describe the solution you'd like**
New functions like for arrays(https://clickhouse.tech/docs/en/sql-reference/functions/array-functions/)
- For given type T `range(T ,end), range(T start, end [, step])`
- `tupleConcat` - we can concatenate arrays of different types
- etc.

Additionally conversion from Array(T) to Tuple(T,T,...) with explicit length of tuple. We can use default values if Array is shorter and trim Array if it is too long.

For example in #10874 I wanted to test corner cases and performance for large tuples.

**Comment by hczhcz** [comment]
> New functions like for arrays

I like the idea!

Probably we can also add a special function `tupleJoin` which converts tuple elements to columns, function parameters, etc.

**Comment by alexey-milovidov** [comment]
tupleConcat - Ok.

But I don't like the idea to allow creation of tuples of arbitrary size, because tuples are not cheap comparing to arrays (every tuple element is a column).

**Comment by qoega** [comment]
I think the main application will be for test purposes. 
Also interested if it would easier/faster to parse array in `IN` clause and convert it to Tuple rather than write Tuple explicitly in query. Something like
```sql
... IN toTuple(range(1000))
... IN toTuple(['aa', 'ab', ..., 'az'])
... IN toTuple(arrayZip(range(1000), range(0,10000,10), range(0,100000,100))
```

**Comment by alexey-milovidov** [comment]
This feature is hardly ever needed.

**Comment by bdrgn** [comment]
@alexey-milovidov 
I want elements of array to be in separate columns like with [untuple](https://clickhouse.com/docs/ru/sql-reference/functions/tuple-functions/#untuple) function. I cannot do that because I can't convert array to tuple.

**Comment by den-crane** [comment]
@bdrgn There is a problem. SQL assumes that number of columns, types and names are known before query execution. In case of Tuple we know the number of elements in a tuple beforehand, and in case of array we don't. One more issue (though it's the same) is that number of columns must be the same for all rows, but each array may have different number of elements.
