### ISSUE TITLE
How to create table with MATERIALIZED column as select from

### ISSUE THREAD

**Issue by xap9i** [ClickHouse/ClickHouse#10891]
Please? Help me.

I want to know how create table with MATERIALIZED column from another select with input variables.
I do next:

CREATE TABLE ANALYST.DATA_TEST1 (
 `ids` UInt16,
 `timestamp` String,
 `code` UInt64,
 `id` UUID MATERIALIZED generateUUIDv4(),
 `timemoment` DateTime MATERIALIZED CAST(formatDateTime(toDateTime(substring(timestamp, 1, 19)), '%Y-%m-%d %T'), 'DateTime'),
 `adate` Date MATERIALIZED toDate(timemoment),
 `idate` Date MATERIALIZED toDate(now()),
 `moduleid` UInt16 MATERIALIZED (SELECT if((SELECT uniqExact(ANALYST.HOME.moduleid) FROM ANALYST.HOME WHERE ANALYST.HOME.id_soa = ids) > 1, 379, 339))
) ENGINE = MergeTree(adate, (moduleid, timemoment, code), 8192);

but execution finshed with error DB::Exception: Missing columns: 'ids' while processing query: 'SELECT uniqExact(ANALYST.HOME.moduleid) FROM ANALYST.HOME WHERE id_soa = ids', required columns: 'ids' 'moduleid' 'id_soa', source columns: 'moduleid' 'description' 'host_min' 'id_soa' 'network' 'host_max'

Maybe I'm wrong and it's impossible!?

**Comment by den-crane** [comment]
It's impossible. You can use `select from` in MATERIALIZED column. You can use only dictGet<Type>.

**Comment by xap9i** [comment]
Sorry, thanks!
