### ISSUE TITLE
The user may accidentially set background pool size lower than `number_of_free_entries_in_pool_to_execute_mutation` and it will prevent ALTERs to process.

### ISSUE THREAD

**Issue by silviucpp** [ClickHouse/ClickHouse#10897]
Hello,

I upgrade to Clickhouse c811e1f0d0c439b74843770082569aa7fd5f9743 (master 2 days ago) and I'm facing lot of problems (https://github.com/ClickHouse/ClickHouse/issues/10892) .

For example:

```bash
CREATE DATABASE tb1
CREATE TABLE tb1.collection_ops_SUITE(`string` Nullable(String),`int` Nullable(Int64),`timestamp` DateTime,`created_at` DateTime) ENGINE = MergeTree PARTITION BY toYYYYMM(timestamp) ORDER BY (timestamp)
INSERT INTO tb1.collection_ops_SUITE(`created_at`,`timestamp`,`int`,`string`) VALUES (1589395126,1589395126,1,'str'),(1589395126,1589395126,2,'str')
ALTER TABLE tb1.collection_ops_SUITE DROP COLUMN `int`
```

Running following queries with HTTP client or tabbix will hang forever in the ALTER table.

In logs I see:

```
2020.05.13 18:44:13.557064 [ 2579621 ] {00000000-0000-4000-8000-000000000000} <Information> tb1.collection_ops_SUITE: Added mutation: mutation_2.txt
2020.05.13 18:44:13.557266 [ 2579621 ] {00000000-0000-4000-8000-000000000000} <Information> tb1.collection_ops_SUITE: Waiting mutation: mutation_2.txt
```

Then nothing more

Silviu

**Comment by den-crane** [comment]
No issue for me.

20.5.1.3327 https://repo.yandex.ru/clickhouse/deb/testing/main/ 
https://github.com/ClickHouse/ClickHouse/commit/c811e1f0d0c439b74843770082569aa7fd5f9743

Tested 4 times (clickhouse-client & http)

**Comment by silviucpp** [comment]
@den-crane Testing on linux ? I'm testing on OSX .

**Comment by den-crane** [comment]
Linux. I do not have OSX

**Comment by silviucpp** [comment]
Can you paste the config files :) I want to try with your config files to see maybe something related from config

**Comment by den-crane** [comment]
No configs. Only vendor's from deb.

**Comment by silviucpp** [comment]
Will try to replace the config files with the default one and see. Can you please test https://github.com/ClickHouse/ClickHouse/issues/10900 as well to see if for you crashes ?

Silviu

**Comment by den-crane** [comment]
Did you build it? 
Try official binary clang-10-darwin https://clickhouse-builds.s3.yandex.net/0/c811e1f0d0c439b74843770082569aa7fd5f9743/report.html

**Comment by silviucpp** [comment]
I build myself and disabled some modules :)) but same build instruction are used on past version which works fine. I'll try to use a precompiled binary to see.

**Comment by silviucpp** [comment]
Ok thanks for links I see the prebuild works just fine. will recompile mine with all modules enabled then isolate the problem and post here the results.

**Comment by den-crane** [comment]
I would check a compiler and a build options https://clickhouse-builds.s3.yandex.net/0/c811e1f0d0c439b74843770082569aa7fd5f9743/build_log_673063988_1589261189.txt

**Comment by silviucpp** [comment]
Hmm that seems a build did on linux for osx.. https://clickhouse.tech/docs/en/development/build-cross-osx/

**Comment by silviucpp** [comment]
@alexey-milovidov  I can replicate this problem on OSX no matter what build I'm using. The offcial build or building myself...

Anything that can generate this ?

**Comment by alexey-milovidov** [comment]
@qoega Please validate.

**Comment by silviucpp** [comment]
If helps in my canse the code freeze in the `mutation_wait_event.wait(lock, check);` (see image)
<img width="1133" alt="Screen Shot 2020-05-14 at 6 18 07 PM" src="https://user-images.githubusercontent.com/4814731/81952635-66b47600-960f-11ea-872a-62a1528c2a10.png">

In the file system I see a new file created mutation_2.txt with the following content:

```
format version: 1
create time: 2020-05-14 15:17:44
commands: DROP COLUMN int 
```

**Comment by silviucpp** [comment]
@alexey-milovidov  Problem seems related to            `<background_schedule_pool_size>1</background_schedule_pool_size>` . Increasing this to 8 works just fine.

**Comment by silviucpp** [comment]
Pretty strange . That setting was added by me for improving the replicated tables. Are you using it now for more other stuffs ?

**Comment by silviucpp** [comment]
OK so I found the real problem.   background_pool_size If is less than 11 mutations are freezing forever. If is 11 or more works like charm.

I have a feeling that's because of :

M(SettingUInt64, number_of_free_entries_in_pool_to_execute_mutation, 10, "When there is less than specified number of free entries in pool, do not execute part mutations. This is to leave free threads for regular merges and avoid \"Too many parts\"", 0) \

Silviu

**Comment by filimonov** [comment]
The issue caused by PR: https://github.com/ClickHouse/ClickHouse/pull/6617 (the feature was introduced in 19.14).

**Comment by sneakythr0ws** [comment]
Same with ALTER TABLE DROP PARTITION
