### ISSUE TITLE
How stable is the last master ?

### ISSUE THREAD

**Issue by silviucpp** [ClickHouse/ClickHouse#10892]
Hello,

I was planning to update my clickhouse server from 19.11.9.52 to the last master and while running our unit tests we have very bad experience:

1. We found queries that are crashing the clickhouse server (we found out to be a problem with the query parsers itself)

2. We found that queries like ALTER TABLE something DROP COLUMN `mycolumn` blocks forever and we get back 

DynamicQueryHandler: Code: 473, e.displayText() = DB::Exception: WRITE locking attempt on "...." has timed out! (120000ms) Possible deadlock avoided. Client should retry., Stack trace (when copying this message, always include the lines below)

We are testing now on simple MergeTree tables only one node with almost no data inside .. are those known bugs or we should investigate more ?

Silviu

**Comment by den-crane** [comment]
Obviously it's not stable enough for you. You did the right thing and tested it first. Just open issues related to your problems.

**Comment by silviucpp** [comment]
@den-crane Can you replicate the problem I'm describing here https://github.com/ClickHouse/ClickHouse/issues/10897 ?

**Comment by den-crane** [comment]
Try official build 20.5.1.3327 https://repo.yandex.ru/clickhouse/deb/testing/main/ 
https://github.com/ClickHouse/ClickHouse/releases

**Comment by yingshikong186** [comment]
i replicate the problem in version 21.6.1

**Comment by alexey-milovidov** [comment]
@yingshikong186 What issues do you have with this version?

**Comment by den-crane** [comment]
@yingshikong186 `alter table drop column` can be blocked for hours by a running merge.

**Comment by alexey-milovidov** [comment]
@den-crane It works instantly in recent ClickHouse releases.

**Comment by SaltTan** [comment]
> @den-crane It always works instantly in recent ClickHouse releases, no locking is performed.

@alexey-milovidov Metadata changes are applied instantly.
But actual dropping is a mutation, and it gets queued and waits for running merges.

**Comment by den-crane** [comment]
21.7.1.7020

```sql
create table xx ( A DateTime, B Float64, C UInt8) Engine=MergeTree order by A;
insert into xx select now(), 1/(number+1), 1 from numbers(1000000000)
alter table xx modify column B Float64 CODEC(DoubleDelta, ZSTD(22));  -- artificially slowsdown merges
```

session 1 | session 2
----------|----------
optimize table xx final; | alter table xx drop column C;
0 rows in set. Elapsed: 280.584 sec.|0 rows in set. Elapsed: 277.943 sec.

**Comment by den-crane** [comment]
```
create table xx ( A DateTime, B Float64, C UInt8, D UInt8) Engine=MergeTree order by A;
insert into xx select now(), 1/(number+1), 1, 1 from numbers(1000000000)　;
alter table xx modify column B Float64 CODEC(DoubleDelta, ZSTD(22));
```
session 1 | session 2 | session 3
----------|----------|----------
optimize table xx final; | alter table xx drop column C; | alter table xx drop column D;
0 rows in set. Elapsed: 280.654 sec. | 0 rows in set. Elapsed: 277.577 sec. | 0 rows in set. Elapsed: 120.001 sec. Received exception from server (version 21.7.1): Code: 473. DB::Exception: Received from localhost:9000. DB::Exception: WRITE locking attempt on "dw.xx" has timed out! (120000ms) Possible deadlock avoided. Client should retry..

**Comment by alexey-milovidov** [comment]
Maybe we forgot to remove some locks from the code :cry:

**Comment by yingshikong186** [comment]
> @yingshikong186 What issues do you have with this version?
i have resolve this problem with 
` KILL MUTATION WHERE database = 'default' AND table = 'table' `。
This problem may be  due to the wrong sql

**Comment by yingshikong186** [comment]
> @yingshikong186 `alter table drop column` can be blocked for hours by a running merge.

thank you。I execute sql  "ALTER TABLE  XX ON CLUSTER YYY DELETE WHERE COLUMN = 'ZZZZ' "， but the column value is illegal
