### ISSUE TITLE
Data Replication cant be achieved with encryption?

### ISSUE THREAD

**Issue by cshivashgit** [ClickHouse/ClickHouse#10909]
I was trying data replication. It worked without encryption using ports 8123,9000 and 9009.
But when i changed the configs to encryption by providing certificates and port to 8443, 9440 and 9009 clickhouse-server didnt come up.
There was always an error "<Error> Application: Not found: tcp_port"
So it seems its looking for tcp_port instead of tcp_port_secure.

If this is not the way , please suggest a way to replicate between servers with encryption.

**Comment by den-crane** [comment]
For replication you have to set `interserver_https_port` 

https://github.com/ClickHouse/ClickHouse/blob/97f2a2213e754ba25dabba4bc8ddf507cd67660c/tests/integration/test_https_replication/configs/ssl_conf.xml

And CH still needs `tcp_port` does not remove it.
