### ISSUE TITLE
How to use the two parameters http_receive_timeout and http_send_timeout

### ISSUE THREAD

**Issue by gubinjie** [ClickHouse/ClickHouse#10905]
In order to test the execution of SQL timeout, we configured these two parameters in the profiles-default of users.xml, 
such as <http_receive_timeout> 5000 </ http_receive_timeout>
             <http_send_timeout> 5000 </ http_send_timeout>,
And In headers of http request，we configured http_receive_timeout = 5000 and http_send_timeout = 5000.
But we found that there is no timeout after 5 seconds, can you answer how to use these two parameters?

**Comment by den-crane** [comment]
These parameters play role when CH is an http client not an http server.

_Added settings: http_connection_timeout, http_send_timeout, http_receive_timeout. In particular, these settings are used for downloading data parts for replication. Changing these settings allows for faster failover if the network is overloaded._

If you need timeouts in your client you should set them in your client / API.

**Comment by gubinjie** [comment]
@decaseal 
Thank you
I configured these two parameters behind the jdbc connection string, for example:
jdbc: clickhouse: // xxxxxxxxx? http_send_timeout = 5000; http_receive_timeout = 5000
We found that it worked, but I have a question?
What is the difference between http_receive_timeout, http_send_timeout and socket_timeout? If we configure socket_timeout, do we not need to configure these two parameters (http_receive_timeout, http_send_timeout)

**Comment by den-crane** [comment]
>If we configure socket_timeout, do we not need to configure these two parameters 

IF YOU USE OFFICIAL JDBC https://github.com/ClickHouse/clickhouse-jdbc:
Yes. You should configure only `socket_timeout` using JDBC parameters.

**Comment by gubinjie** [comment]
@den-crane 
Thank you!
