### ISSUE TITLE
No such name in Block::erase()

### ISSUE THREAD

**Issue by leoones** [ClickHouse/ClickHouse#10907]
SQL:
SELECT
       campaignName AS campaign_name,
       sum(impressions) / 10000 AS impressions,
       sum(clicks) / 10000 AS clicks,
       if(impressions = 0, 0, round(clicks / impressions * 100, 2)) AS ctr,
       sum(toFloat64(cost * exchange_rate)) / 10000 / 10000 AS spend,
       if(clicks = 0, 0, round(spend / clicks, 2)) AS cpc,
       sum(attributedConversions7d) / 10000 AS orders,
       if(clicks = 0, 0, round(orders / clicks * 100, 2)) AS cvr,
       if(orders = 0, 0, round(spend / orders, 2)) AS cpa,
       sum(toFloat64(attributedSales7d * exchange_rate)) / 10000 / 10000 AS sales,
       if(sales = 0, 0, round(spend / sales * 100, 2)) AS acos
FROM ptx_db.fct_apa_report_sp_campaigns AS A
ANY LEFT JOIN ptx_db.c_exchange_rate_day AS B
    ON A.report_date = toString(formatDateTime(B.exchange_date, '%Y%m%d')) AND A.country = B.countrys
WHERE flag = 1 AND campaignName != '' AND account = 'OT' AND country = 'CA'
AND A.report_date >= '20200507' AND A.report_date <= '20200513' GROUP BY campaignName ORDER BY campaign_name desc LIMIT 0,25；

ERROR:
 ClickHouse exception, code: 10, host: 172.16.6.210, port: 8123; Code: 10, e.displayText() = DB::Exception: No such name in Block::erase(): 'exchange_date' (version 20.4.2.9 (official build))

Solution：
Replace （PTX dB. C exchange rate as B ） with subquery：
SELECT
       campaignName AS campaign_name,
       sum(impressions) / 10000 AS impressions,
       sum(clicks) / 10000 AS clicks,
       if(impressions = 0, 0, round(clicks / impressions * 100, 2)) AS ctr,
       sum(toFloat64(cost * exchange_rate)) / 10000 / 10000 AS spend,
       if(clicks = 0, 0, round(spend / clicks, 2)) AS cpc,
       sum(attributedConversions7d) / 10000 AS orders,
       if(clicks = 0, 0, round(orders / clicks * 100, 2)) AS cvr,
       if(orders = 0, 0, round(spend / orders, 2)) AS cpa,
       sum(toFloat64(attributedSales7d * exchange_rate)) / 10000 / 10000 AS sales,
       if(sales = 0, 0, round(spend / sales * 100, 2)) AS acos
FROM ptx_db.fct_apa_report_sp_campaigns AS A
ANY LEFT JOIN (select formatDateTime(exchange_date, '%Y%m%d') as exchange_date,exchange_rate,countrys from ptx_db.c_exchange_rate_day ) AS B
    ON A.report_date =B.exchange_date  AND A.country = B.countrys
WHERE flag = 1 AND campaignName != '' AND account = 'OT' AND country = 'CA' AND A.report_date >= '20200507' AND A.report_date <= '20200513' GROUP BY campaignName ORDER BY campaign_name desc LIMIT 0,25；

Why not compatible  ？？？？

**Comment by doom369** [comment]
Same here.

**Comment by 4ertus2** [comment]
Could you add trace in server log related to to the error, please?

**Comment by 4ertus2** [comment]
As temporary workaround `set optimize_move_to_prewhere = 0` should helps.

**Comment by leoones** [comment]
> As temporary workaround `set optimize_move_to_prewhere = 0` should help.

ok, I try .

**Comment by leoones** [comment]
> Could you add trace in server log related to to the error, please?

error.log
(version 20.4.2.9 (official build))
2020.05.14 15:05:19.859835 [ 22692 ] {0e5e5c31-0d77-46c3-becc-49f0a6a2c5ef} <Error> executeQuery: Code: 10, e.displayText() = DB::Exception: No such name in Block::erase(): 'exchange_date' (version 20.4.2.9 (official build)) (from 172.16.6.230:56728) (in query: SELECT campaignName AS campaign_name,sum(impressions) / 10000 AS impressions,sum(clicks) / 10000 AS clicks,if(impressions = 0, 0, round(clicks / impressions * 100, 2)) AS ctr,sum(toFloat64(cost * exchange_rate)) / 10000 / 10000 AS spend,if(clicks = 0, 0, round(spend / clicks, 2)) AS cpc,sum(attributedConversions7d) / 10000 AS orders,if(clicks = 0, 0, round(orders / clicks * 100, 2)) AS cvr,if(orders = 0, 0, round(spend / orders, 2)) AS cpa,sum(toFloat64(attributedSales7d * exchange_rate)) / 10000 / 10000 AS sales,if(sales = 0, 0, round(spend / sales * 100, 2)) AS acos FROM ptx_db.fct_apa_report_sp_campaigns AS A ANY LEFT JOIN ptx_db.c_exchange_rate_day AS B ON A.report_date = toString(formatDateTime(B.exchange_date, '%Y%m%d')) AND A.country = B.countrys WHERE flag = 1 AND campaignName != '' AND account = 'SY' AND country = 'UK' AND A.report_date >= '20200507' AND A.report_date <= '20200513' GROUP BY campaignName ORDER BY campaign_name desc LIMIT 0,25 FORMAT JSON), Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x10406ef0 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x8ff88ad in /usr/bin/clickhouse
2. ? @ 0xcd78850 in /usr/bin/clickhouse
3. DB::ExpressionActions::finalize(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0xd1d6fee in /usr/bin/clickhouse
4. DB::ExpressionActionsChain::finalize() @ 0xd1d974e in /usr/bin/clickhouse
5. DB::ExpressionAnalysisResult::ExpressionAnalysisResult(DB::SelectQueryExpressionAnalyzer&, bool, bool, bool, std::__1::shared_ptr<DB::FilterInfo> const&, DB::Block const&) @ 0xd3be7a0 in /usr/bin/clickhouse
6. DB::InterpreterSelectQuery::getSampleBlockImpl(bool) @ 0xd225fa3 in /usr/bin/clickhouse
7. ? @ 0xd2274bb in /usr/bin/clickhouse
8. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, std::__1::shared_ptr<DB::IBlockInputStream> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0xd22843d in /usr/bin/clickhouse
9. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0xd229939 in /usr/bin/clickhouse
10. DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0xd3fa361 in /usr/bin/clickhouse
11. DB::InterpreterFactory::get(std::__1::shared_ptr<DB::IAST>&, DB::Context&, DB::QueryProcessingStage::Enum) @ 0xd197474 in /usr/bin/clickhouse
12. ? @ 0xd5375ae in /usr/bin/clickhouse
13. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, DB::Context&, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>) @ 0xd53b4b0 in /usr/bin/clickhouse
14. DB::HTTPHandler::processQuery(Poco::Net::HTTPServerRequest&, HTMLForm&, Poco::Net::HTTPServerResponse&, DB::HTTPHandler::Output&) @ 0x90dd7fc in /usr/bin/clickhouse
15. DB::HTTPHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&) @ 0x90e1256 in /usr/bin/clickhouse
16. Poco::Net::HTTPServerConnection::run() @ 0x102b78a3 in /usr/bin/clickhouse
17. Poco::Net::TCPServerConnection::start() @ 0x102f2c6b in /usr/bin/clickhouse
18. Poco::Net::TCPServerDispatcher::run() @ 0x102f30fb in /usr/bin/clickhouse
19. Poco::PooledThread::run() @ 0x104a0cc6 in /usr/bin/clickhouse
20. Poco::ThreadImpl::runnableEntry(void*) @ 0x1049bf80 in /usr/bin/clickhouse
21. start_thread @ 0x7e25 in /usr/lib64/libpthread-2.17.so
22. clone @ 0xfebad in /usr/lib64/libc-2.17.so

2020.05.14 15:05:19.860348 [ 22692 ] {} <Error> DynamicQueryHandler: Code: 10, e.displayText() = DB::Exception: No such name in Block::erase(): 'exchange_date', Stack trace (when copying this message, always include the lines below):
