### ISSUE TITLE
Memory footprint of distributed table's ClickHouse server grows linearly and drops suddenly, and repeats

### ISSUE THREAD

**Issue by huang--yijian** [ClickHouse/ClickHouse#10917]
**Describe the situation**
As in the following screenshot, the ClickHouse server holding distributed tables has an constantly, linearly increasing memory footprint, and it drops suddenly. It looks like some kind of memory leak.
![image](https://user-images.githubusercontent.com/7484190/81931209-51921400-961c-11ea-85e5-4c4a4ae88004.png)

The other servers holding local MergeTree tables don't not have this problem.
So this unstable memory footprint is caused by distributed tables.

**How to reproduce**
* Which ClickHouse server version to use
20.1.4.14

* Which interface to use, if matters
Query via JDBC driver

* Non-default settings, if any
None

* `CREATE TABLE` statements for all tables involved
There are multiple tables. The major ones are:
`CREATE TABLE edw.user_behavior_v3_all (`appId` Int32, `channel` Int32, `os` Int32, `version` Int32, `sessionId` Int64, `mostDeviceId` Int64, `leastDeviceId` Int64, `deviceName` Int32, `deviceType` Int32, `serverTime` DateTime, `timestamp` UInt64, `location` Int32, `manufacturer` Int32, `networkMode` Int32, `carrierOperator` Int32, `uid` Int64, `dataId` Int32, `propsKey` Array(Int32), `propsValue` Array(String), `clientTime` DateTime, `clientTimestamp` UInt64, `seq` UInt64, `event` Int32, `clientAb` Array(Int64)) ENGINE = Distributed(edw, edw, user_behavior_v3, rand())`

`CREATE TABLE edw.user_behavior_user_20nodes_all (`trackTypeId` Int32, `channel` Int32, `version` Int32, `sessionId` Int64, `deviceName` Int32, `deviceType` Int32, `serverTime` DateTime, `timestamp` UInt64, `location` Int32, `carrierOperator` Int32, `dt` Int32, `uid` Int64, `dataId` Int32, `propsKey` Array(Int32), `propsValue` Array(String), `clientTime` DateTime, `clientTimestamp` UInt64, `seq` UInt64, `clientAb` Array(Int64)) ENGINE = Distributed(edw, edw, user_behavior_user_20nodes, rand())`

* Queries to run that lead to slow performance
Not sure if there is one deadly query, or it is caused by multiple queries.

**Expected performance**
What are your performance expectation, why do you think they are realistic? Has it been working faster in older ClickHouse releases? Is it working faster in some specific other system?

We expect not only a stable increase in memory footprint, but also a stable decrease in it, instead of dropping the memory footprint suddenly.
We don't have strong evidence that it is related to version 20.1.4.14.

**Additional context**
None.

**Comment by den-crane** [comment]
I you sure that CH does not restart? Can you show `select uptime()`
Try the latest 20.1.11.73.

**Comment by huang--yijian** [comment]
Is there any related issue fixed in 20.1.11.73 ?

Upgrading to 20.1.11.73 is a serious decision for our production environment.
We would like to see some evidence showing better memory footprint of 20.1.11.73.

**Comment by huang--yijian** [comment]
> I you sure that CH does not restart? Can you show `select uptime()`
> Try the latest 20.1.11.73.

Our operations confirm that since May 5, the server was manually started only once on May 13:
![image](https://user-images.githubusercontent.com/7484190/82036798-e9066e00-96d3-11ea-963a-d7b7ee32af3f.png)

**Comment by den-crane** [comment]
>Our operations confirm that since May 5,

CH has an autorespawn skill. Check /etc/cron.d/clickhouse-server

**Comment by huang--yijian** [comment]
Now is 2020-5-16 10:41:35. The current memory footprint is high, as below graph shows.
The related log of around 1 minute is attached. Let us know if you need more log.
![image](https://user-images.githubusercontent.com/7484190/82108583-f36f4900-9761-11ea-86b9-130983a90cb7.png)
[long_text_2020-05-16-10-36-50.txt](https://github.com/ClickHouse/ClickHouse/files/4637707/long_text_2020-05-16-10-36-50.txt)

**Comment by huang--yijian** [comment]
As below, the memory footprint of ClickHouse server increases every 6 hours, in a zig-zag fashion.
![image](https://user-images.githubusercontent.com/7484190/82291132-ff197480-99da-11ea-91c0-49833a386735.png)

We identified an applicaiton which launches memory-consuming ClickHouse queries, right every 6 hours. 
So definitely, this ClickHouse server memory footprint is caused by these queries.

However, as below screenshot shows, the query_duration_ms of these heavy queries is less than 5 minute.
![image](https://user-images.githubusercontent.com/7484190/82292208-0a6d9f80-99dd-11ea-8005-bcec7643416b.png)

In every 6-hour period, ClickHouse server should have enough time to free up memory consumed by these queries, which do not happen as expected.

So we suspect there is a memory leak in ClickHouse server, not sure if it is fixed in later versions.

**Comment by den-crane** [comment]
Then I believe it's expected behavior. 
Jemalloc does not free allocated memory immediately. To save CPU resources on deallocation/allocation cycles.

**Comment by huang--yijian** [comment]
Is there a gurantteed deadline to free memory finally in jemalloc, so that the memory footprint is contained at certain level?

Is it possible for users to configure ClickHouse to use an alternative memory allocator, so that memory is freed earlier?

**Comment by den-crane** [comment]
I don't really understand what is the problem here. CH able to use all server's memory. What is the difference is it used all the time or only part of time?

**Comment by azat** [comment]
>Jemalloc does not free allocated memory immediately

looks too huge even for jemalloc  + thread pool (with taking into account that only allocations < 64MB done via jemalloc, other with direct mmap)

actually it is very easy to verify, @huang--yijian can you try use one of the following and get back with results?

- `MALLOC_CONF=background_thread:true` (you can track number of background operations in `system.asynchornous_metrics` - `jemalloc.background_thread.%`)
- `MALLOC_CONF=percpu_arena:percpu` (but please note that it is not recommended to use this in production for common setup, you can take a look [here](https://github.com/jemalloc/jemalloc/issues/713) for some details, i.e. why it is not enabled by default in jemalloc)

The above is environment variable, you should set it before starting clickhouse-server (i.e. modify systemd `clickhouse-server.service`)

There is also another way to try the same settings, by using symlink:

```sh
ln -s 'percpu_arena:percpu' /etc/malloc.conf
```

**Comment by huang--yijian** [comment]
> I don't really understand what is the problem here. CH able to use all server's memory. What is the difference is it used all the time or only part of time?
> 
> > Is it possible for users to configure ClickHouse to use an alternative memory allocator, so that memory is freed earlier?
> 
> Old versions of CH used tcmalloc and [#6515 (comment)](https://github.com/ClickHouse/ClickHouse/issues/6515#issuecomment-624227717).

If ClickHouse frees memory in a more timely manner, Linux Page Cache will gain memory earlier, important of file IO performance.
If ClickHouse eats up most of hardware memory, Linux Page Cache hurts.

**Comment by den-crane** [comment]
I re-read a thread. So every 6 hours the query eat +30GB, and after 2 days memory usage drops itself? Is it right?

**Comment by huang--yijian** [comment]
> I re-read a thread. So every 6 hours the query eat +30GB, and after 2 days memory usage drops itself? Is it right?

Yes, you are right

"every 6 hours the query eat +30GB" is caused by every-6 hour big application queries, resolved.

"after 2 days memory usage drops"  is not expected, too late because most hardware memory hs been occupied by ClickHouse, affecting Page Cache performance.

**Comment by alexey-milovidov** [comment]
It may simply indicate that 32 GiB is not enough.
