### ISSUE TITLE
Drop partition cannot use expression

### ISSUE THREAD

**Issue by leoones** [ClickHouse/ClickHouse#10911]
new version ：20.4.2.9
SQL：
ALTER TABLE ptx_dw.c_finance_transaction_rebuild drop partition toYYYYMM(toDate(concat('2020-05', '-01')))

error：
Syntax error: failed at position 107 (end of query): . Expected one of: LIKE, GLOBAL NOT IN, IS, OR, QuestionMark, BETWEEN, NOT LIKE, AND, IN, NOT, token, NOT IN, GLOBAL IN (version 20.4.2.9 (official build))

Modify SQL:
ALTER TABLE ptx_dw.c_finance_transaction_rebuild drop partition 202005;
That's good

old version 19.15  execute  no problem ！！！！！！

**Comment by den-crane** [comment]
https://github.com/ClickHouse/ClickHouse/issues/10212#issuecomment-612676750
