### ISSUE TITLE
SSL connection unexpectedly closed

### ISSUE THREAD

**Issue by saravsars** [ClickHouse/ClickHouse#10935]
**Describe the bug**
`SSL connection unexpectedly closed` exception is getting printed for every 2 seconds (added the exception below). It is generating from HTTPHandler thread but there are no active connections from the server or to the server. It is getting printed even when the server is idle.
But there are no issues in replication or connecting from client.

**How to reproduce**
* ClickHouse server version: 20.3.8.53
* Using ReplicatedMergeTree table with three nodes

**Error message and/or stacktrace**
```2020.05.15 05:30:43.124426 [ 3275 ] {} <Error> ServerErrorHandler: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = SSL connection unexpectedly closed, Stack trace (when copying this message, always include the lines below):```

```0. Poco::IOException::IOException(int) @ 0x1054b5af in /usr/bin/clickhouse
1. Poco::Net::NetException::NetException(int) @ 0xe39ca7d in /usr/bin/clickhouse
2. Poco::Net::SSLConnectionUnexpectedlyClosedException::SSLConnectionUnexpectedlyClosedException(int) @ 0xe35bedd in /usr/bin/clickhouse
3. ? @ 0xe36f66b in /usr/bin/clickhouse
4. Poco::Net::SecureSocketImpl::completeHandshake() @ 0xe36e7b3 in /usr/bin/clickhouse
5. Poco::Net::SecureSocketImpl::receiveBytes(void*, int, int) @ 0xe36ea29 in /usr/bin/clickhouse
6. Poco::Net::HTTPSession::receive(char*, int) @ 0xe38c968 in /usr/bin/clickhouse
7. Poco::Net::HTTPSession::get() @ 0xe38c9d3 in /usr/bin/clickhouse
8. Poco::Net::HTTPHeaderStreamBuf::readFromDevice(char*, long) @ 0xe381bca in /usr/bin/clickhouse
9. Poco::BasicBufferedStreamBuf<char, std::__1::char_traits<char>, Poco::Net::HTTPBufferAllocator>::underflow() @ 0xe37e438 in /usr/bin/clickhouse
10. std::__1::basic_streambuf<char, std::__1::char_traits<char> >::uflow() @ 0x1105dfbe in ?
11. std::__1::basic_istream<char, std::__1::char_traits<char> >::get() @ 0x110655b6 in ?
12. Poco::Net::HTTPRequest::read(std::__1::basic_istream<char, std::__1::char_traits<char> >&) @ 0xe384f97 in /usr/bin/clickhouse
13. Poco::Net::HTTPServerRequestImpl::HTTPServerRequestImpl(Poco::Net::HTTPServerResponseImpl&, Poco::Net::HTTPServerSession&, Poco::Net::HTTPServerParams*) @ 0xe38aa75 in /usr/bin/clickhouse
14. Poco::Net::HTTPServerConnection::run() @ 0xe389b79 in /usr/bin/clickhouse
15. Poco::Net::TCPServerConnection::start() @ 0xe3b9a4b in /usr/bin/clickhouse
16. Poco::Net::TCPServerDispatcher::run() @ 0xe3b9ecd in /usr/bin/clickhouse
17. Poco::PooledThread::run() @ 0x105d05b7 in /usr/bin/clickhouse
18. Poco::ThreadImpl::runnableEntry(void*) @ 0x105cc3bc in /usr/bin/clickhouse
19. ? @ 0x105cdd5d in /usr/bin/clickhouse
20. start_thread @ 0x740b in /usr/lib64/libpthread-2.26.so
21. __clone @ 0xece7f in /usr/lib64/libc-2.26.so
 (version 20.3.8.53 (official build))

**Comment by filimonov** [comment]
Some health check maybe?

**Comment by saravsars** [comment]
Yes, when TCP health check is configured in the AWS Target Group this exception is getting printed. When the target group is deleted the exceptions stopped.
Thanks

**Comment by alexey-milovidov** [comment]
This is the expected behaviour. When client connects to ClickHouse and unexpectedly disconnects, the server correctly informs that the `SSL connection unexpectedly closed`.

**Comment by filimonov** [comment]
Maybe we just need to decrease error level to information?

**Comment by filimonov** [comment]
Many health checks just open/close port to check the connectivity. That's definitely should not spam in clickhouse-server.err.log

**Comment by filimonov** [comment]
https://github.com/ClickHouse-Extras/poco/blob/a71e0776531861873144e4c4081204ea1a1258fb/NetSSL_OpenSSL/src/SecureSocketImpl.cpp#L514-L528

https://github.com/ClickHouse/ClickHouse/blob/25f941020b578f2e9d479ae7df02d0148619fdb1/base/common/ErrorHandlers.h#L21-L37

**Comment by filimonov** [comment]
https://github.com/ClickHouse/ClickHouse/issues/23059#

**Comment by alexey-milovidov** [comment]
@filimonov Let's create another task with a feature request to decrease the logging level in this place.
