### ISSUE TITLE
How to load hive data what type is map to clickhouse

### ISSUE THREAD

**Issue by Zhushatianxia** [ClickHouse/ClickHouse#10939]
Hi,who can help me?
I want use  "ENGINE = HDFS(URI, format)" to load data from hive,but the data type is map.
I'm trying to replace "Nested(id String ,name String)" with map when creating the clickhouse engine = I found I had failed. "Select * from table",can not found nothing from hive。
What should I do?;
please hellp me！！

**Comment by robot-clickhouse** [comment]
@Zhushatianxia, is this question still relevant?

**Comment by alexey-milovidov** [comment]
You should use the Map data type.
