### ISSUE TITLE
How table get user create by create user?

### ISSUE THREAD

**Issue by Fanduzi** [ClickHouse/ClickHouse#10949]
Is there a table like mysql.user to get all mysql user create by `create user` statement?

**Comment by den-crane** [comment]
Not yet. Probably it will be the next stable release 20.4 or 20.5 https://github.com/ClickHouse/ClickHouse/pull/10387

**Comment by Fanduzi** [comment]
> Not yet. Probably it will be the next stable release 20.4 or 20.5 #10387

Where is the user information now stored?

**Comment by den-crane** [comment]
/var/lib/clickhouse/access/

quotas.list
roles.list
row_policies.list
settings_profiles.list
users.list
