### ISSUE TITLE
There is no synchronization between replicas, neither in readonly state nor in synchronization

### ISSUE THREAD

**Issue by wujieaiyan** [ClickHouse/ClickHouse#10941]
2020.05.15 16:50:06.800472 [ 84 ] {} <Error> k19_test.replica_shard (ReplicatedMergeTreeRestartingThread): void DB::ReplicatedMergeTreeRestartingThread::run(): Code: 27, e.displayText() = DB::Exception: Cannot parse input: expected format version:  at end of stream., Stack trace (when copying this message, always include the lines below):

0. 0x100ac1bc Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int)  in /usr/bin/clickhouse
1. 0x8e74849 DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int)  in /usr/bin/clickhouse
2. 0x8eaacd5 ?  in /usr/bin/clickhouse
3. 0x8ea8caa DB::assertString(char const*, DB::ReadBuffer&)  in /usr/bin/clickhouse
4. 0xd78dd1b DB::ReplicatedMergeTreeLogEntryData::readText(DB::ReadBuffer&)  in /usr/bin/clickhouse
5. 0xd78f04b DB::ReplicatedMergeTreeLogEntry::parse(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Stat const&)  in /usr/bin/clickhouse
6. 0xd7b49c1 DB::ReplicatedMergeTreeQueue::load(std::__1::shared_ptr<zkutil::ZooKeeper>)  in /usr/bin/clickhouse
7. 0xd7d7393 DB::ReplicatedMergeTreeRestartingThread::tryStartup()  in /usr/bin/clickhouse
8. 0xd7d7cf8 DB::ReplicatedMergeTreeRestartingThread::run()  in /usr/bin/clickhouse
9. 0xcd939f1 DB::BackgroundSchedulePoolTaskInfo::execute()  in /usr/bin/clickhouse
10. 0xcd93fca DB::BackgroundSchedulePool::threadFunction()  in /usr/bin/clickhouse
11. 0xcd94100 ?  in /usr/bin/clickhouse
12. 0x8e97347 ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>)  in /usr/bin/clickhouse
13. 0x8e9580f ?  in /usr/bin/clickhouse
14. 0x7e25 start_thread  in /usr/lib64/libpthread-2.17.so
15. 0xfebad __clone  in /usr/lib64/libc-2.17.so
 (version 20.1.6.30 (official build))

**Comment by alesapin** [comment]
According to trace, you have some incorrect log entry (empty) in your replication queue. How is it related to synchronization?
