### ISSUE TITLE
Scaling out a live cluster by adding incremental capacity(online resharding)

### ISSUE THREAD

**Issue by yfinkelstein** [ClickHouse/ClickHouse#10943]
**Use case**
As data set in the cluster grows, new shards need to be added with the purpose of both placing new(future) data on them as well as offloading existing data to free up space and other resources on the existing shards. An important requirement is **do it without a downtime** as well as **without sacrificing data consistency**. The second requirement can be formalized as follows:
* Every physical row of data ever successfully stored in the cluster must be seen once and only once by any matching query at all times - even when resharding activity is taking place.
* The effect of all ongoing row mutation activities in Collapsing-, Aggregating-, Summing-, etc xxMergeTrees must not be altered by resharding operations from the point of view of correctness of corresponding xxMergeTrees algorithms

**Describe alternatives you've considered**
We first looked at clickouse-copier which obviously is closely related to the task of adding new shards. However, there is no evidence that the 2 requirements mentioned above have been taken into account. Specifically, 
1) the outcome of copying a live mutable partition from one shard to another is undefined in terms of any consistency guarantees, right? Some parts can be copied, some may not, and future writes will continue to go to the same partition in the source but not in the target. 
2) copying of a partition from one shard to another in a live cluster results in duplication of this partition's data such that a query running on both From and To shards may end up seeing the same data in both places. Even if the intended use of the copier is to first build out a new shard and only then add it to the cluster - there is still an obvious consistency problem with this because addition of a shard and dropping of partitions/parts in the previous shards locations  **is not atomic**

**Describe the solution you'd like**
The purpose of this ticket is not necessarily to suggest how clickhouse SHOULD solve this problem but to seek feedback on whether the following implementation even makes sense. We can implement it ourselves in a private fork of clickhouse and use it in our deployment first.
Please consider that we are by no means experts in CH design and internals, so this idea may simply not be sound. 
 
Here is the idea that we have. 
The key observation is that if some partition is **immutable** because, for instance, `PARTITION BY` includes an insertion date column and all the dates except for "today" are no longer being written to then using clickhouse-copier is safe. 

1. Define PARTITION BY to be `hash_range (some business fields) + toYYYYMMDD(insert_date) `- i.e. a tuple of 2 values of type int32 and Date. Hash range is an idea from stateful consistent hashing algorithms where the range of [0,Int_Max) is divided into some number of equal sub-ranges. Given a list of column values in some deterministic order, we first serialize them into a byte string,  take a hash of this byte string, and finally determine which of the sub-ranges this hash value belongs to. The number of hash ranges is chosen to be rather small and approximately equal to initial number of shards, say **10**. This means that every day there will be 10 new partitions created in the system. In a year there will be 3650 partitions in the system. Later we can probably collapse old partitions somehow.
2. Each partition is mapped to exactly one shard in some mapping table which can be kept in a clickhouse dictionary. This map has an entry for each pair of partition=>shard. 
3. Each of the ranges (10 in our example) has a default shard it's pinned to, i.e. all future partitions that include this range will be placed on that shard _initially_. But they can be _moved_ to another shard later.
4. To enable moving of the partitions, the partition map needs to be **versioned**. Say version 5 of the mapping table maps partition `(2, 2020-05-01) => shard 1`. In version 6 of the mapping table, a new shard 11 was added and this partition was moved over there. So, in version 6, there will be a record: `(2,2020-05-01) => shard 11` and previous record for that partition is gone. Note that several most recent partition map versions along with their partitions(data) are kept in the system such that if a given version of this map  is needed it can be  found. Old versions are eventually trimmed.
5. At query time, the latest known version of the map is looked up during early stages of the query processing, and saved into the context as a variable `_sharding_map_version_`. This variable becomes the basis for a snapshot of the system in terms of the list and location of the partitions in the cluster. 
6. The query goes to a distributed table instance, which then dispatches it to all shards (or some shard subset based on primary key based routing optimization which is not relevant at the moment). All shards receive the same query i.e, they see the same value of `_sharding_map_version_` associated with this query.
7. **Now, the key idea**: while going over the list of parts in _MergeTreeDataSelectExecutor.cpp_ _Pipes MergeTreeDataSelectExecutor::readFromParts_  **we filter out those parts that do not belong to the current shard based on the current partition _sbarding_map_version**. More formally, we check invariant `Map.get(_sharding_map_version_).get(partition) == current_shard_id`. If not TRUE, the part is ignored.
8. In Distributed Table, the definition of Distributed engine will look approximately like this:
`engine=Distributed(cluster, database, table, versionedConsistentHash(toYYYYMMDD(date), c1, c2, ...);` Here, versionedConsistentHash is a new built-in function which we will add which will perform the partition map lookup. The fuzzy part here is how to make Distributed engine recognize the shard id as the value returned by this function, but it probably can be done somehow (question: are the buckets in jumpConsitentMap and other such functions meant to correspond to shards?)

8. What is the overall process/workflow to add a new shard?
a) provision a new shard with its replicas and add it to the cluster in distributed table instances right away. 
b) pick some immutable partitions (with dates in the past with some safety margin, say at least 3 days ago) and copy them to the new shard using clickhouse-copier.
c) create a new partition map version reflecting moved partitions and their new location.
d) activate the new version, i.e make it **current**. The clients will start seeing it for new queries/sessions. Old version is still readable and is still valid because the partitions that have been moved in the now-current version are still there in their original shards based on previous version.
e) after some conservatively chosen time when it can be guaranteed that all queries/sessions that were using the previous version of the map are gone, it's safe to drop partitions in the original shards that were moved, and also drop the old version of the map.

9. Simplified proof that this algorithm achieves the 2 key consistency goals that we mentioned in the beginning.
* each query runs in the context of a single shard mapping version i.e. each partition is read at most once during the query execution
* addition of a new shard can be done without a downtime on a live cluster (already supported by CH)
* addition of a new shard results in immediate rebalancing of the data and soon after - freeing up space (deleting migrated partitions) in the existing shards which is the ultimate purpose of this process.

**Additional context**
it's quite possible that we missed some conner cases and some additional changes are required to make this implementation safe and sound. Please point out to these issues.

**Comment by marising** [comment]
hi @yfinkelstein 
I take the liberty to ask,  how is the feature you describe now progressing? Because we are also troubled by the problem of scaling.

**Comment by silashansen** [comment]
Any update, @yfinkelstein? :-)

**Comment by parikshit223933** [comment]
Is any work going on this? @yfinkelstein ?

**Comment by alexey-milovidov** [comment]
This task is abandoned (nothing has happened).
