### ISSUE TITLE
groupArray(max_size)(col) with max_size defined in WITH clause

### ISSUE THREAD

**Issue by pic-Nick** [ClickHouse/ClickHouse#10945]
**Describe the unexpected behaviour**
When using groupArray function with max_size parameter defined as constant in WITH clause got error message:
`Code: 47, e.displayText() = DB::Exception: Missing columns: 'max_size' while processing query: 'WITH 1 AS max_size SELECT groupArray(max_size)(col) FROM (SELECT 1 AS col UNION ALL SELECT 2)', required columns: 'col' 'max_size', source columns: 'col' (version 20.3.8.53 (official build))`

**How to reproduce**
ClickHouse server version 20.3.8.53
```
with 1 as max_size
select groupArray(max_size)(col) from (
select 1 as col
UNION ALL
select 2
)
```

**Expected behavior**
It would be nice to have this function accept max_size parameter as defined in WITH clause.

**Comment by UnamedRus** [comment]
When a function in clickhouse has multiple ()() in it's definition, parameters being passed to the first brackets can't be dynamically set during execution and should be constant.

```

SELECT
    1 AS max_size,
    groupArray(max_size)(col)
FROM
(
    SELECT 1 AS col
    UNION ALL
    SELECT 2
)

Query id: 4113a11a-bd97-4acb-8055-c29f1e1c7019


Received exception from server (version 20.13.1):
Code: 134. DB::Exception: Received from localhost:9000. DB::Exception: Parameters to aggregate functions must be literals. Got parameter 'max_size'.
```

So it looks like a misleading error message.

**Comment by alexey-milovidov** [comment]
There's no reason to not allow constant expressions in aggregate function parameters.

Changed to "feature request".

**Comment by alexey-milovidov** [comment]
The same for SAMPLE n / m ...
