### ISSUE TITLE
CREATE AS SELECT casting data types

### ISSUE THREAD

**Issue by calebeaires** [ClickHouse/ClickHouse#10955]
**Use case**
Take advantage of CREATE AS SELECT in favor os clean code an performance and also (and eventually) change some field data type .

**Describe the solution you'd like**
FROM: Consider a table *world* that has this **Decimal** columns continent
TO: Want replicate this table, but change this **Decimal** column to i.e: **String**

```sql
CREATE TABLE world
(continent String)
engine MergeTree() 
as select `continent` from `example_world`;
```

Problem: when I inform the data type of the column to be created from select, ClickHouse give me an error.

**Describe alternatives you've considered**
Right now I am creating the table first then using INSERT AS SELECT. I came from MySQL where I used to CREATE WITH SELECT informing columns data types.

**Additional context**
My concern is that as my app does many sequencial create as select, and sometimes I need to change the column type, using INSERT AS SELECT after first CREATE the table will drop performance of complete tasks

**Comment by alexey-milovidov** [comment]
Proposal:
Allow to explicitly specify table structure in CREATE AS SELECT.
Currently the query does not parse.

Example:
```
milovidov-desktop :) CREATE TABLE test (x String) ENGINE = Memory AS SELECT 1

Syntax error: failed at position 46 ('AS'):

CREATE TABLE test (x String) ENGINE = Memory AS SELECT 1
                                             ^
Expected one of: PRIMARY KEY, INTO OUTFILE, TTL, ORDER BY, SETTINGS, PARTITION BY, SAMPLE BY, FORMAT
```
