### ISSUE TITLE
Server not reacting to SIGINT, stuck at "Application: Shutting down storages"

### ISSUE THREAD

**Issue by myrrc** [ClickHouse/ClickHouse#10961]
(you don't have to strictly follow this form)

**Describe the bug**
The server, being run on various databases (or without ones), receiving Ctrl + C (or SIGINT), stucks at "Application: Shutting down storages" step.
After sending second SIGINT it terminates (as expected)

**How to reproduce**
* Which ClickHouse server version to use -- d0b56a4c7d
273267ca8b
* Queries to run that lead to unexpected result -- no queries

**Expected behavior**
Server exiting (graceful shutdown) on first SIGINT receive.

**Error message and/or stacktrace**
No error message.

Used standard config.xml and own one, attached.
Server log attached
[config.xml.txt](https://github.com/ClickHouse/ClickHouse/files/4638519/config.xml.txt)
[log.txt](https://github.com/ClickHouse/ClickHouse/files/4638521/log.txt)

**Comment by alexey-milovidov** [comment]
Does not reproduce.

Need stack traces of all threads at this moment.
(attach with gdb and type `thread apply all backtrace`)

**Comment by myrrc** [comment]
[trace.txt](https://github.com/ClickHouse/ClickHouse/files/4641341/trace.txt)

**Comment by alexey-milovidov** [comment]
`/home/kot/clickhouse/build/programs/clickhouse`
\- this is alternative ClickHouse build.

You can download the official build in "ClickHouse Build Check" and see what will happen:
https://clickhouse-builds.s3.yandex.net/0/6f1d522b6aa2dd119e452f20c5cd4ca12da6d072/report.html

**Comment by alexey-milovidov** [comment]
We have figured out that the issue only happened in development version of ClickHouse with your modifications.
