### ISSUE TITLE
clickhouse database in docker container should not be available externally until it is initialized

### ISSUE THREAD

**Issue by KorneiDontsov** [ClickHouse/ClickHouse#10963]
I believe that clickhouse-server process should accept only local connections during execution of scripts in `/docker-entrypoint-initdb.d/`. I viewed [docker/server/entrypoint.sh](https://github.com/ClickHouse/ClickHouse/blob/a55c6763d6add428ba0816aca43fdc0f73794dba/docker/server/entrypoint.sh) and I didn't find this behaviour. Correct me if I am wrong.

What I expect at [first launch of  `clickhouse-server`](https://github.com/ClickHouse/ClickHouse/blob/a55c6763d6add428ba0816aca43fdc0f73794dba/docker/server/entrypoint.sh#L92) is like
`$gosu /usr/bin/clickhouse-server --config-file=$CLICKHOUSE_CONFIG -- listen_host=127.0.0.1 &`
where `-- listen_host=127.0.0.1` gives the behaviour I search for.

If I understand CLI correctly I guess I could get this behaviour if I specify `<listen_host>127.0.0.1</listen_host>` in `config.xml` and execute `docker run` with `-- listen_host=0.0.0.0`. But as I said I believe that this should be done differently.

To be compatible with the existing behaviour a new environment variable may be used to configure behaviour.

**Comment by filimonov** [comment]
Makes sense.

**Comment by KorneiDontsov** [comment]
> If I understand CLI correctly I guess I could get this behaviour if I specify <listen_host>127.0.0.1</listen_host> in config.xml and execute docker run with -- listen_host=0.0.0.0.

I checked this workaround. It works.

**Comment by filimonov** [comment]
> What I expect at first launch of clickhouse-server is like
> $gosu /usr/bin/clickhouse-server --config-file=$CLICKHOUSE_CONFIG -- listen_host=127.0.0.1 &
where -- listen_host=127.0.0.1 gives the behaviour I search for

That sounds more universal. Can you test it and send a PR?

**Comment by KorneiDontsov** [comment]
I can, but I'm busy until weekend. Does it suit you?
