### ISSUE TITLE
Query parameters don't work for mutations

### ISSUE THREAD

**Issue by th0th** [ClickHouse/ClickHouse#10976]
**Describe the bug**

When a parameter is used in `UPDATE` part of the query ```Query parameter `field` was not set``` occurs on an `ALTER` query.

**How to reproduce**

* ClickHouse server version 20.4.2.9 (official build).
* HTTP interface
* Non-default settings, if any

Table: 

```sql
CREATE TABLE table
(
  id UUID,
  date_time DateTime,
  x UInt32,
  y UInt32
) ENGINE = MergeTree()
PARTITION BY toYYYYMMDD(date_time)
ORDER BY (date_time);
```

Query: 

```sql
ALTER TABLE table
UPDATE x = {x:UInt32}
WHERE y = {y:UInt32};
```

request:

<img width="1479" alt="Screen Shot 2020-05-17 at 11 33 08" src="https://user-images.githubusercontent.com/698079/82139661-41538200-9832-11ea-8554-b16b43c4e373.png">

curl:

```sh
$ curl --location --request POST 'http://clickhouse-url/?query=ALTER%20TABLE%20table%0AUPDATE%20x%20%3D%20{x:UInt32}%0AWHERE%20y%20%3D%20{y:UInt32};&param_x=1&param_y=7'
```

**Expected behavior**

Update query should run without any issues.

**Error message and/or stacktrace**

```
Code: 456, e.displayText() = DB::Exception: Query parameter `x` was not set (version 20.4.2.9 (official build))
```

**Comment by liuxun666** [comment]
I have the same problem

**Comment by liuxun666** [comment]
I have a table that is partitioned by date, and I want to drop the specified partition with the passed date parameter
