### ISSUE TITLE
One and a half billion data, very slow to execute, the results come out and it's much faster to execute again

### ISSUE THREAD

**Issue by zhbdesign** [ClickHouse/ClickHouse#10971]
![微信图片_20200517121452](https://user-images.githubusercontent.com/50901800/82135686-09e7d400-9838-11ea-9167-b4b701f353bd.png)

**Comment by zhbdesign** [comment]
With 1.5 billion data, the execution takes 633 seconds to complete

**Comment by alexey-milovidov** [comment]
The screenshot shows abysmally low performance but there is no info about the hardware and the data structure.

**Comment by alexey-milovidov** [comment]
It may happen if you have built ClickHouse without optimizations.
