### ISSUE TITLE
helm3 chart for openshift - ssc error with privileged and runAsUser

### ISSUE THREAD

**Issue by haarchri** [ClickHouse/ClickHouse#10993]
**Use case**
We want install sentry in combination with clickhouse on openshift - but we have a problem with ssc because of 

```
        securityContext:
          privileged: true
          runAsUser: 0
```

**Describe the solution you'd like**
Please give us a solution that the pod can run without privileged and make the runAsUser configurable

**Comment by blinkov** [comment]
@haarchri I think you'd better post this to the repository where you got that helm chart.
