### ISSUE TITLE
Issues when use S3 when using Amazon bucket

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#10998]
2 blocker issues with AWS s3:
1) can't parse one of the (proper) URL format (`Bucket name length out of bounds in S3 URI`)
i.e. (https://s3.us-east-2.amazonaws.com/bucketname/).
2) can't login to non default region `AuthorizationHeaderMalformed: the region 'XXXX' is wrong; expecting 'YYYY'`  (see https://github.com/aws/aws-sdk-cpp/issues/1057)

And 3rd (rather minor/cosmetic/need to be rechecked):
not showing the real error / reason of the issue here:
https://github.com/ClickHouse/ClickHouse/blob/f981649213fb519c57fda3dc2c51ab709cb327f4/src/Storages/StorageS3.cpp#L242-L248

**Comment by den-crane** [comment]
https://github.com/ClickHouse/ClickHouse/issues/10417 
https://github.com/ClickHouse/ClickHouse/issues/9988

**Comment by alexey-milovidov** [comment]
Reopened.

1. Need to be verified that it is fixed in master.
2. The issue with bad error message is still relevant.

**Comment by alexey-milovidov** [comment]
Fix: https://github.com/ClickHouse/ClickHouse/pull/15646

**Comment by excitoon** [comment]
It was not a fix actually, shall be fixed in #19750
