### ISSUE TITLE
OpenShift startup 

### ISSUE THREAD

**Issue by haarchri** [ClickHouse/ClickHouse#11003]
(you don't have to strictly follow this form)

**Describe the issue**
We have the following issues:
```Necessary directory '/var/lib/clickhouse/' isn't owned by user with id '1016890000'```
```        2 drwxrwsr-x. 3 root 1016890000 4.0K May 18 09:24 clickhouse```

looks like we are unable to set the UID - but you checked this in the entrypoint - is there a other solution available to setup the docker images without root ?

**How to reproduce**
* Which ClickHouse server version to use
20

possible solution could be: https://github.com/Uglykoyote/clickhouse

**Comment by azat** [comment]
>looks like we are unable to set the UID - but you checked this in the entrypoint - is there a other solution available to setup the docker images without root ?

Looks like you have docker with userns enabled and you tried `CLICKHOUSE_DO_NOT_CHOWN=1`, i.e. something like this:

```
docker run -e CLICKHOUSE_DO_NOT_CHOWN=1 -v /tmp/ch-docker:/var/lib/clickhouse --rm -it yandex/clickhouse-server:20.1
```

Is [`CLICKHOUSE_UID`/`CLICKHOUSE_GID`](https://github.com/ClickHouse/ClickHouse/blob/master/docker/server/README.md#start-server-from-root-useful-in-case-of-userns-enabled) what you are looking for?

```
docker run --rm -e CLICKHOUSE_UID=0 -e CLICKHOUSE_GID=0 -v /tmp/ch-docker:/var/lib/clickhouse yandex/clickhouse-server:20.3
# implicitly set CLICKHOUSE_DO_NOT_CHOWN
```

> Which ClickHouse server version to use: 20

This had been added in #8844, so works on 20.3+ (i.e. yandex/clickhouse-server:20.3)

**Comment by haarchri** [comment]
so it looks like the same error ... i set the both ENV variables - but in real we are in an openshift environment

**Comment by azat** [comment]
>so it looks like the same error ... i set the both ENV variables

Are you sure you are using 20.3? Can you post the command output and `ls -l /path/to/data/volume/*`?
> - but in real we are in an openshift environment

I did not use openshift and don't know what restrictions it has? You cannot pass environment variables or what?

**Comment by haarchri** [comment]
hello, the problem in openshift is that the clickhouse image is with root and openshift sets a other id like 1016890000 and if we map a volume (pvc) to the container then it looks like: 

`2 drwxrwsr-x. 3 root 1016890000 4.0K May 18 09:24 clickhouse`

here is a example of an working docker image for clickhouse:

https://github.com/Uglykoyote/clickhouse/blob/master/docker/Dockerfile#L50

**Comment by azat** [comment]
>openshift sets a other id

How?

>here is a example of an working docker image for clickhouse:

You have tons of `ch*` (chown/chmod) commands, does not looks as a basic image

Original question that I was answering:

> is there a other solution available to setup the docker images without root ?

If you need to run without root I suppose you have:

- [docker + userns](https://docs.oracle.com/cd/E37670_01/E75728/html/ol-docker-userns-remap.html)
- subgid/subuid configured
- clickhouse-server:20.3+ image

And when all above is true and you are using such command:

``shell
docker run --rm -e CLICKHOUSE_UID=0 -e CLICKHOUSE_GID=0 -v /tmp/ch-docker:/var/lib/clickhouse yandex/clickhouse-server:20.3
```

Then clikchouse-server will be executed as a root in the container, but since you have userns + subuid/subgid configured root in the container user is translated using subuid/subgid into the host.

**Comment by filimonov** [comment]
https://docs.openshift.com/enterprise/3.0/admin_guide/manage_scc.html#enable-images-to-run-with-user-in-the-dockerfile

**Comment by rrati** [comment]
You can run a container that requires root using scc on openshift, however that is generally not the way to run containers on openshift.  The creation of an scc requires elevated privileges and in a secure environment may not be given.  The better way to do this is for the container image not to require root in order to run.

When openshift runs a container, it assigns a random UID to the user that is running the container.  That is why user ids in containers running on openshift look like the one in this issue.  When running a container on openshift without elevated privileges you can not rely upon a specific uid.  Using scc of course you can define the uid for the container, but as mentioned this isn't the best expectation to set.

I'm not familiar with the clickhouse image creation at all or the requirements, but you might be able to do something similar to this in the dockerfile:

RUN groupadd -r clickhouse && useradd -r -m -g clickhouse clockhouse
...
chown clickhouse:clickhouse /var/lib/clickhouse

In the dockerfile, you can also chmod 777 the dir where clickhouse would write.

**Comment by filimonov** [comment]
ClickHouse container can work rootless. 
Just set user uid 101 / gid 101 and mount in the folders writable for uid/gid 101.

**Comment by rrati** [comment]
That won't work on openshift without creating an scc, which isn't a good practice.

From my previous message:
When openshift runs a container, it assigns a random UID to the user that is running the container.

Setting a UID explicitly requires elevated privs which are not available by default on openshift.

**Comment by filimonov** [comment]
I mean smth like

```yml
 apiVersion: v1
 kind: Pod
 metadata:
   name: ch
 spec:
   securityContext:
     runAsUser: 101
     runAsGroup: 101
     fsGroup: 101
   containers:
   - name: ch-cont
     image: yandex/clickhouse-server:v21.1.2.15-stable # on older versions you may need to mount in the entrypoint from the latest clickhouse
     securityContext:
       capabilities:
         add: ["SYS_PTRACE","NET_ADMIN", "IPC_LOCK", "SYS_NICE"] # that should be optional
```

See also
 https://github.com/ClickHouse/ClickHouse/pull/18954
 https://github.com/ClickHouse/ClickHouse/pull/19096

**Comment by rrati** [comment]
Yep.  RunAsUser can not be set by users by default on openshift.  That requires elevated privs.

**Comment by filimonov** [comment]
Ok. Will fix that tomorrow. It seems only single chmod should be added to dockerfile. Other parts are already there.

**Comment by rrati** [comment]
Think of openshift kind of like linux when running pods/containers.  It runs pods as a non-root user. Anything a non-root user would be prevented from doing on linux will probably also be disallowed by default on openshift.

I did a quick test with a dockerfile and it seems that the solutions I provided won't work.  The container is checking that the owner of /var/lib/clickhouse is the user running the container, and that will never be true on openshift since the uid for the user running the pod is random.  Maybe instead check for the ability to write to the dir?  Not sure the requirements trying to be met.

**Comment by haarchri** [comment]
this is exact at the moment the problem:

`I did a quick test with a dockerfile and it seems that the solutions I provided won't work. The container is checking that the owner of /var/lib/clickhouse`

**Comment by filimonov** [comment]
@haarchri  @rrati guys please check https://github.com/ClickHouse/ClickHouse/pull/19374 (i have no openshift to try it out):

Images to test:
filimonovq/clickhouse-server:21.1.2.15-alpine
filimonovq/clickhouse-server:21.1.2.15

Should work with arbitrary uid.

**Comment by rrati** [comment]
Both of those images start on openshift.  I'm not yet in a position to test functionality, but I can see in the logs that the previous error message is a warning now:

2021.01.22 15:17:29.106915 [ 36 ] {} <Warning> Application: Effective user of the process (1000810000) does not match the owner of the data (101).


FYI, you can test on openshift 4.x locally for free using Code Ready Containers:
https://github.com/code-ready/crc

**Comment by rrati** [comment]
When would these changes get into official clickhouse images?

**Comment by sag1** [comment]
Any update on this ? When will it allow arbitary uid ?

**Comment by alexey-milovidov** [comment]
It should be already available since version 21.2.

**Comment by sag1** [comment]
Good, but I found latest version as 20.12.8.15 on docker hub. Is it published under another name?

**Comment by alexey-milovidov** [comment]
21.2 is in the list: https://hub.docker.com/r/yandex/clickhouse-server/tags?page=1&ordering=last_updated

I have no idea why latest points to some other version.

**Comment by alexey-milovidov** [comment]
I checked, it's alright:

`docker run --rm --network=host yandex/clickhouse-server:latest` downloads version 21.2.5 - the latest stable release with all patches.

**Comment by sag1** [comment]
Great ! Thanks @alexey-milovidov

**Comment by ErrorPro** [comment]
> I mean smth like
> 
> ```yaml
>  apiVersion: v1
>  kind: Pod
>  metadata:
>    name: ch
>  spec:
>    securityContext:
>      runAsUser: 101
>      runAsGroup: 101
>      fsGroup: 101
>    containers:
>    - name: ch-cont
>      image: yandex/clickhouse-server:v21.1.2.15-stable # on older versions you may need to mount in the entrypoint from the latest clickhouse
>      securityContext:
>        capabilities:
>          add: ["SYS_PTRACE","NET_ADMIN", "IPC_LOCK", "SYS_NICE"] # that should be optional
> ```
> 
> See also #18954 #19096
@filimonov 
Could you please elaborate a bit more on what to do with the older versions? I have `imageVersion: 20.8.9.6` and I need to run it as non-root. Trying to only use securityContext provided in the quote resolved in `log":"Necessary directory '/var/lib/clickhouse/' isn't owned by user with id '101'\n"`. Thanks!

**Comment by ErrorPro** [comment]
Probably worth mentioning: I am trying to deploy the latest sentry-helm chart. The error mentioned above comes from the [initContainer](https://github.com/sentry-kubernetes/charts/blob/develop/clickhouse/templates/statefulset-clickhouse.yaml#L71) that tries to create that folder. @alexey-milovidov Maybe you have any idea?
