### ISSUE TITLE
Copier deletes a MATERIALIZED column even if it was in the partitioning key. 

### ISSUE THREAD

**Issue by nikitamikhaylov** [ClickHouse/ClickHouse#11007]
ClusterCopier uses distributed tables to insert data to target cluster and to perform resharding. It creates internal distributed tables on each shard with a subset of original columns (It deletes `MATERIALIZED` columns and columns with `ALIAS` not to send useless data over the network) : https://github.com/ClickHouse/ClickHouse/blob/c76a82777c8b28608a3dfa0640cc6a003b1746bb/dbms/programs/copier/ClusterCopier.cpp#L2159-L2161

However, these columns could be in PARTITION key, SAMPLE key or whatever.  And it leads to exceptions.

**Comment by nikitamikhaylov** [comment]
Will be fixed by allowing to copy this columns. #23518

**Comment by bondarevpavel** [comment]
Anyone who facing with same issue just pay attention `allow_to_copy_alias_and_materialized_columns` setting should be declared in `tables.<table_name>` section not in `settings` section
