### ISSUE TITLE
build ClickHouse on ARM 64，and plus(id, 1) not return correct result

### ISSUE THREAD

**Issue by wushiming540** [ClickHouse/ClickHouse#11011]
we build ClickHouse(19.17.4) on ARM 64， then test like this:
```
CREATE TABLE default.test_001
(
    `id` Int32
)
ENGINE = MergeTree()
ORDER BY id
SETTINGS index_granularity = 8192
```
```
insert into default.test_001 values(1);
```
```
SELECT
    id,
    id + 1
FROM default.test_001

┌─id─┬─plus(id, 1)─┐
│  1 │           0 │
└────┴─────────────┘

```

we expect plus(id, 1)=2， but it not.

can you give us some sugesstion  ？

**Comment by wushiming540** [comment]
we use  ClickHouse version : 19.17.4

**Comment by nikitamikhaylov** [comment]
Try to test official build for ARM, which you can download from [here](https://clickhouse-builds.s3.yandex.net/0/3d5e8e0f2c070a17bdfd4cf47f8ce2184dce433c/clang-10-aarch64_relwithdebuginfo_none_bundled_unsplitted_disable_binary/clickhouse). 
Note, that it is master with newer version of ClickHouse. If it is reproduced on official build, then it is simply a bug. 
Also, you can inspect [logs](https://clickhouse-builds.s3.yandex.net/0/3d5e8e0f2c070a17bdfd4cf47f8ce2184dce433c/report.html)  of release build and parse cmake string from there. Then you can build exactly the same binary.

**Comment by wushiming540** [comment]
it is build error, we have solved.。 thank  you
