### ISSUE TITLE
FR: REPLACE TABLE statement 

### ISSUE THREAD

**Issue by ramazanpolat** [ClickHouse/ClickHouse#1102]
If users need to reject(delete) some data from a table, they can create a new table and fill it with a select statement which doesn't retrieve unwanted data, then rename it to old table name.

Example:

    CREATE TABLE myNewTable AS myOldTable;

Then load data with:

    INSERT INTO myNewTable SELECT * FROM myOldTable WHERE CounterID <12345

Drop old table and rename:

    DROP TABLE myOldTable;
    RENAME TABLE myNewTable TO myOldTable

Instead of above, being able to use the following would be nice:

    REPLACE TABLE myOldTable SELECT * FROM myOldTable WHERE CounterID <12345;

Behind the scenes, CH can do the creating, dropping and renaming.

**Comment by alexey-milovidov** [comment]
We are planning to implement a set of related operations:
```
TRUNCATE TABLE
CREATE OR REPLACE TABLE
REPLACE TABLE
```

The main downside is that in first implementation they will be supported for all table engines except `Replicated-` tables. This is because for Replicated tables, CREATE and DROP just add or remove single replica for table.

**Comment by ramazanpolat** [comment]
Looking forward to it.
I would like to contribute to this project, unfortunately I'm far from being good at C++. I'll do my best if there is any other way to help.

**Comment by henyihanwobushi** [comment]
GOOD Suggestion!!!
Let the rename statement support multi renames, and support transaction for the renames, like mysql, will solve my problem.

**Comment by filimonov** [comment]
Rename support  renaming multiple tables at once. Syntax is usual.
```
RENAME TABLE a1 TO b1, a2 TO b2, a3 TO b3
```

Operation can be considered atomic but "but only in cases when there was no exceptions during this process and server does not fall" (see [comment](https://github.com/yandex/ClickHouse/blob/303cc7242f0ac98e3dbaad74764fcddab001e2f7/dbms/src/Interpreters/InterpreterRenameQuery.cpp#L116)).

**Comment by tetafro** [comment]
Waiting for `REPLACE`. The usecase is switching application to another table by re-creating view like this
```
CREATE VIEW my_table AS SELECT * FROM my_table_v1
...
REPLACE TABLE my_table WITH
CREATE VIEW AS SELECT * FROM my_table_v2
```
and application (which queries `my_table`) seamlessly switches from one table to another.

**Comment by alexey-milovidov** [comment]
Now this feature can be easily implemented on top of DatabaseAtomic.
@tavplubix said that he is ready to take.
