### ISSUE TITLE
ClickHouse create MergeTree.

### ISSUE THREAD

**Issue by vladimirteddy** [ClickHouse/ClickHouse#11035]
I use Tabix, create table follow example Merge ClickHouse:
"https://clickhouse.tech/docs/en/engines/table-engines/special/merge/"

> CREATE TABLE WatchLog_old(date Date, UserId Int64, EventType String, Cnt UInt64)
ENGINE=MergeTree(date, (UserId, EventType), 8192);
### Log: Code: 79, e.displayText() = DB::Exception: MergeTree storages require data path (version 20.4.2.9 (official build)).
![screenshot_3](https://user-images.githubusercontent.com/29521357/82312895-de104e00-99f1-11ea-8a5e-1d40f5366173.png)
Please help me.
Version ClickHouse: 20.4.2.9.

**Comment by candledragle** [comment]
how solved?
