### ISSUE TITLE
Upsert support

### ISSUE THREAD

**Issue by templarzq** [ClickHouse/ClickHouse#11059]
**Use case**
upsert row data on replacing merge tree
ensuring primary key to be exact one

**Describe the solution you'd like**
the replacing merge tree now must use query with final keyword to ensure the exact one primary key result. and the final query execution is slow.

**Describe alternatives you've considered**
(1) optimize the merge algorithm of replacingmerge tree , 
(2) optimize the wirte procedure of replacingmerge tree
(3) optimize the storage file format to ensure the primary key exactly one
    e.g   lsm-tree , 
   

**Additional context**

**Comment by den-crane** [comment]
Also we need a warp drive and laser guns

**Comment by templarzq** [comment]
i've finished the optimization of  the merge algorithm of replacingmerge tree and get 30% speedup on final query , and the remained work is not very difficult.

**Comment by templarzq** [comment]
it's just need people work days..

**Comment by templarzq** [comment]
> Also we need a warp drive and laser guns

so why not build warp ship and laser guns?

**Comment by filimonov** [comment]
> i've finished the optimization of the merge algorithm of replacingmerge tree and get 30% speedup on final query , and the remained work is not very difficult.

Do you plan to share your improvements / findings?

**Comment by compasses** [comment]
@templarzq Waiting you sharing your story about optimize of  merge algorithm of replacingmerge tree 👍 :)

**Comment by templarzq** [comment]
new version clickhouse  final query is fast enough.
