### ISSUE TITLE
Get the value for the previous point of time. IOT case

### ISSUE THREAD

**Issue by Shanginre** [ClickHouse/ClickHouse#11056]
I have the table with keys (time, facility). For each key, the (value) received from the sensor is stored. For instance:

┌─date────┬facility┬value┬
│ 2017-09-09 │ 10002│ 10  │
│ 2017-09-10 │ 10001│ 12      │
│ 2017-09-12 │ 10002│ 15      │
│ 2017-09-15 │ 10001│ 17      │
└────────┴────┘──┘

I want to calculate an increase in the current value compared to the previous one. Something like this:

┌─date────┬facility┬─value┬
│ 2017-09-12 │ 10002│ 15/10 │ // 15 current, 10 previous for facility 10002
│ 2017-09-15 │ 10001│ 17/12 │ // 17 current, 12 previous for facility 10002
└────────┴────┘────┘

To get this result, I need to use JOIN, but as I understood from the documentation, the comparison condition in JOIN operation is only for equality, and inequalities cannot be used.

Of course, I can do a Cartesian product, then do a date comparison (get all dates less than the current one) in the WHERE section and then select the maximum date from the filtered ones. But it is very time and memory consuming!

Please help me create an optimal query, because this case is typical for IOT

**Comment by den-crane** [comment]
There is no good solution, this task is not typical for OLAP.

select groupArray(date), facility, groupArray(value) from 
  (select date,  facility, value from 
         (select '2017-09-09' date, 10002 facility, 10 value union all
          select '2017-09-10' , 10001, 12 union all
          select '2017-09-12' , 10002, 15 union all
          select '2017-09-15' , 10001, 17 ) 
   order by date desc)
group by facility

┌─groupArray(date)────────────┬─facility─┬─groupArray(value)─┐
│ ['2017-09-15','2017-09-10'] │    10001 │ [17,12]           │
│ ['2017-09-12','2017-09-09'] │    10002 │ [15,10]           │
└─────────────────────────────┴──────────┴───────────────────┘

**Comment by Shanginre** [comment]
thanks for the answer. I'm used to working with relational databases, this is a common case there. Please tell me in which DBMS such a query will be executed quickly for 100 million rows? Cassandra, InfluxDB, ....? I am now choosing a DBMS for IOT project.

**Comment by den-crane** [comment]
Yes, Cassandra, InfluxDB much better for such queries.
