### ISSUE TITLE
Replace the data in replecated table

### ISSUE THREAD

**Issue by asurovenko** [ClickHouse/ClickHouse#11061]
Hello,
My goal is reaggregate the date from hour aggregation to daily aggregation. All I need to achieve it is replace **GROUP BY date** to **GROUP BY toStartOfDay(date)**
And it must be executed for the date older than month.
So, I have old data and query for get new one, and my question is: how I can replace the data.
How I can understend I need temporary table for storage data from query, after that I need remove old data older that month, and fill data from temporary table, isn't it?
But for my replicated table query like **alter table ... delete where date < toDateTime('2020-02-20 06:00:00');** do not work. What's the good solution for my situation?

Maybe it will be need: engine = ReplicatedMergeTree('/clickhouse/tables/{shard}/.../...', '{replica}') PARTITION BY date ORDER BY date SETTINGS index_granularity = 8192;

**Comment by den-crane** [comment]
Your table is partitioned by date. You can just drop partitions https://clickhouse.tech/docs/en/sql-reference/statements/alter/#alter_drop-partition and attach partition from temporary tables https://clickhouse.tech/docs/en/sql-reference/statements/alter/#alter_attach-partition-from

---

Engine GraphiteMergeTree https://clickhouse.tech/docs/en/engines/table-engines/mergetree-family/graphitemergetree/ able to Rollup data itself.

---

The same can be achieved by `clear column` in SummingMergeTree + optimize

```
create table XXXSMT (a Int64, b Int64, c Int64, d Int64, f Float64) Engine=SummingMergeTree 
primary key (a)
order by (a,b,c,d);

insert into XXXSMT select 1,1,1,number,1 from numbers(10)

alter table XXXSMT clear column d in partition tuple();

optimize table XXXSMT final;

SELECT *
FROM XXXSMT

┌─a─┬─b─┬─c─┬─d─┬──f─┐
│ 1 │ 1 │ 1 │ 0 │ 10 │
└───┴───┴───┴───┴────┘

```

**Comment by asurovenko** [comment]
**den-crane**, thanks. Could you say me how I can drop all partitions older that month? As I search in Google, there is no way to drop partitions by condition?

**Comment by den-crane** [comment]
@asurovenko there is no such feature in CH. I use bash script - 3 lines.
```

sql="select distinct partition_id from system.parts
	where database = '$db' and table='$table'  and active
	and min_date < today()-$days format TabSeparatedRaw
	"

for partition in `$ch_client "$sql"`
do
   sql="alter table \`$table\` drop partition id '$partition'"
   $ch_client "$sql"
done
```
