### ISSUE TITLE
Is it a good Idea to put a high cardinality column in primary key ?

### ISSUE THREAD

**Issue by hoseiney** [ClickHouse/ClickHouse#11063]
We have a table with 100 million/day inserts. 
```
CREATE TABLE table (
	 user_id UInt32,
	 time_col DateTime,
	 date_col Date,
         field_1 LowCardinality(String)
 ) ENGINE = MergeTree() 
 PARTITION BY date_col
 ORDER BY (date_col, field_1) 
```
We need to give users ability to search by date_col and time_col.
Is it good idea to have this structure ? 
```
PARTITION BY date_col
ORDER BY (time_col, field_1)
```
The question is :
- Can we have high cardinality columns in primary key ?
- What is the general recommendation to choose primary key and order by clause?

**Comment by nvartolomei** [comment]
https://clickhouse.tech/docs/en/engines/table-engines/mergetree-family/mergetree/#selecting-the-primary-key

High cardinality is good as just by looking at the index (which is in memory) a large set of rows will be discarded.

**Comment by hoseiney** [comment]
> https://clickhouse.tech/docs/en/engines/table-engines/mergetree-family/mergetree/#selecting-the-primary-key
> 
> High cardinality is good as just by looking at the index (which is in memory) a large set of rows will be discarded.

thanks. so having DateTime column in primary key is OK ?

**Comment by hoseiney** [comment]
> > https://clickhouse.tech/docs/en/engines/table-engines/mergetree-family/mergetree/#selecting-the-primary-key
> > High cardinality is good as just by looking at the index (which is in memory) a large set of rows will be discarded.
> 
> thanks. so having DateTime column in primary key is OK ?
> 
> based on the doc(you also shared):
> 
> > Long data ranges (several times longer than the index_granularity) with identical values for (a, b) are common
> > for one value of (a,b) we should have thousands of records, right ?
> > so if we have : primary key (DateTime , other_field), it seems we do not follow that approach

**Comment by den-crane** [comment]
if you need queries like this ` where   other_field_1=? and DateTime between ? and ?`

`   primary key ( other_field_1 , other_field_2, DateTime)`
Or 
`  primary key ( toStartOfHour(DateTime), other_field_1 , other_field_2, )`

**Comment by hoseiney** [comment]
yes this is exactly our use case.

why we can not have primary key ( DateTime, other_field_1 , other_field_2) ?

Honestly I do not completely understand the concept of index in Clickhouse, I read the doc but I am not sure how to design it.
How can I read more about the concept (in addition to Clickhouse MergeTree doc ) ?

**Comment by den-crane** [comment]
>why we can not have primary key ( DateTime, other_field_1 , other_field_2) ?

Because high cardinality column `DateTime` makes `other_field_1` values far from each other and reduces effectiveness  of descending to `where other_field_1=?` 

>Honestly I do not completely understand the concept of index in Clickhouse, I read the doc but I am not sure how to design it.

It's pretty same concept as RDBMS btree indexes. The same is true for mysql or MSsql. 
For effective search `where other_field_1=? and DateTime between ? and ?` your index MUST be `(other_field_1 , DateTime)`
