### ISSUE TITLE
Number of inserts per second

### ISSUE THREAD

**Issue by sundarv85** [ClickHouse/ClickHouse#11067]
We ran recently into the issue [Merges are processing significantly slower than inserts  #1510](https://github.com/ClickHouse/ClickHouse/issues/1510) and we did reduce number of inserts and it seems to be better.

How to really see the number of inserts that are happening?

We found the call

```
SELECT * FROM system.metrics LIMIT 10
```

In this we see the Query as 40-110 - Does this mean we are only doing an insert of 40-110 per second? 

Are there any other administrator tools for ClickHouse using which we can see how the query performance is, how many inserts are happening over a period of time.

**Comment by den-crane** [comment]
```
SELECT value
FROM system.events
WHERE event LIKE 'InsertQuery'


SELECT
    event_time,
    ProfileEvent_InsertQuery,
    runningDifference(ProfileEvent_InsertQuery) ins_per_sec
FROM system.metric_log
WHERE event_date = today()
ORDER BY event_time DESC
LIMIT 50
```

**Comment by sundarv85** [comment]
Thanks @den-crane 

`InsertQuery` returns a number - which I assume it is the number of inserts at this point in time. Which UI based tools do you use to keep a tab on how the inserts are done over a period of time.

For the other query, we get the error

```
DB::Exception: Table system.metric_log doesn't exist.. 
```
Should this be something that needs to be enabled separately.

**Comment by den-crane** [comment]
>Which UI based tools do you use to keep

zabbix.

>DB::Exception: Table system.metric_log doesn't exist.. 

it's enabled by default. But this table exists only in the recent versions 19.3 or something.
