### ISSUE TITLE
Unexpected behaviour when insert into LowCardinality(FixedString(2)) large string

### ISSUE THREAD

**Issue by asamr** [ClickHouse/ClickHouse#11078]
**Describe the unexpected behaviour**
Clickhouse doesn't throw exception "Too large value for FixedString(N)" when insert large string into LowCardinality(FixedString(2))

**How to reproduce**
Clickhouse 19.16.10.44

```
CREATE TABLE IF NOT EXISTS test(
  id UInt64,
  val LowCardinality(FixedString(2))
)
ENGINE = ReplacingMergeTree()
PARTITION by id
ORDER BY id;

INSERT INTO test VALUES (1, 'ru');
INSERT INTO test VALUES (2, 'ruuuu');
```

**Expected behavior**
Throws ```Too large value for FixedString(N)``` after second insert.

**Actual behaviour**
Row has been inserted
```select * from test;```

![2020-05-20_21-59-46](https://user-images.githubusercontent.com/7774356/82488782-2d857580-9ae9-11ea-9ed8-dd1dd7ed31f4.png)

**Comment by den-crane** [comment]
20.3.9

```
SELECT *
FROM test

┌─id─┬─val─┐
│  1 │ ru  │
└────┴─────┘
```

**Comment by asamr** [comment]
Cool! It's time to upgrade. Thank you
