### ISSUE TITLE
Is there a way to pass WITH expr values as parameters to sharding_key expression of Distributed engine?

### ISSUE THREAD

**Issue by yfinkelstein** [ClickHouse/ClickHouse#11070]
Every query that I submit to Distributed Table against certain table has a WITH clause:
`WITH 'a' as myparam SELECT * from mytable WHERE ...`

I want to shard this table with a sharding_key expression that takes `myparam` value as a parameter:
`Distributed(cluster, default, mytable, my_sharding_key_func(myparam))`.

I tried this but got an error: DB::Exception: `Missing columns: 'myparam' while processing query ...`

If I get the story right, in theory this should be possible because the sharding key expression is evaluated in the context of a SELECT query and all such queries of mine will have myparam defined.

I understand that sharding_key expression is also evaluated during insert operation to determine which shard to send the row to. In that case, myparam won't be defined explicitly (unfortunately), but the function can handle unspecified/undefined value itself.  This is my own custom function in a modified build of clickhouse. 

I'm just looking for a way to pass query-time context variable to sharding_key expression somehow. Perhaps there is a workaround?
Thanks!

**Comment by yfinkelstein** [comment]
What if I add another virtual column in the distributed engine based on extraction of the value from AST right here: https://github.com/ClickHouse/ClickHouse/blob/master/src/Interpreters/ClusterProxy/executeQuery.cpp#L70

**Comment by yfinkelstein** [comment]
May be virtual columns can be used for this? I presume a virtual column can be passed to sharding key function as a parameter?

**Comment by azat** [comment]
So you want to select the shard based on the parameters that you passed in `WITH` statement (so you are using `optimize_skip_unused_shards`), is my understanding correct?

>I want to shard this table with a sharding_key expression that takes myparam value as a parameter: Distributed(cluster, default, mytable, my_sharding_key_func(myparam)).

Sounds too specific (but looks like this can be implemented by introducing separate function, say `getVariable` that will return variable from `WITH`, but this is not generic, adding variables support will be generic), and `WITH` support is pretty limited AFAIK.

>This is my own custom function in a modified build of clickhouse.

Why not implement this logic in your function itself?

~P.S. there is actually internal function, `__getScalar` that can be used to obtain value from the subqueries, but it is not intended to be used by anyone, and you need to know "hash of the subquery"~

<details>

```
WITH 
    (
        SELECT 'foo' AS foo
    ) AS foo
SELECT __getScalar('3959081863401655453_7744625192132479120')

Row 1:
──────
__getScalar('3959081863401655453_7744625192132479120'): foo
```

</details>

**Comment by yfinkelstein** [comment]
Ok, thanks. getScalar is indeed relevant. We figured out most of the issues, so this question is answered. By the real topic we are trying to advance is this one: https://github.com/ClickHouse/ClickHouse/issues/10943. It would be great if you could review it and comment on it.
