### ISSUE TITLE
"select @@version" error when using mysql_port

### ISSUE THREAD

**Issue by phuslu** [ClickHouse/ClickHouse#11089]
It's very very exciting clickhouse introduced mysql support.

We're start migrate some existing OLAP service to ClickHouse now. Currently we found many services/softwares need  "select @@version" support.

Could you please add "select @@version" support? thanks!

**Comment by alexey-milovidov** [comment]
Yes, we are planning to support these queries.
The proposed implementation is the following:

1. Support `@@identifier` expressions in parser and translate them to functions `globalVariable('identifier')`.
2. Implement this function and add support for MySQL global variables that required for compatibility. It's Ok to return dummy values for some cases.
3. Remove ugly compatibility code from MySQLHandler that will be no longer relevant.

**Comment by alexey-milovidov** [comment]
This task is currently addressed in this PR: #11901
