### ISSUE TITLE
Real time updates

### ISSUE THREAD

**Issue by shubham721** [ClickHouse/ClickHouse#11094]
Hi guyz,

I work in a company which have a usecase something like this

suppose I have a table with primary keys (a,b,c) and there is one column of timestamp(time) and there is one more column of status.

I want to replace the row with same primary key row with latest timestamp. we have evaluated these options and found the following problems, Is there a better way to do it?

1. AggregatingMergeTree -> SimpleAggregateFunction doesn't support argMax, we have usecase something like SimpleAggregateFunction(argMax(status, time), string)

2. ReplacingMergeTree -> This engine replaces the whole row with latest time stamp, Problem with this is we would need to fetch first the whole row using primary key identifiers, as update event might not contain all data. And then insert new row with latest timestamp. we don't want to fetch whole row every time for update.

3. MergeTree -> Here we will insert multiple records with same primary keys. But this will increase disk utilization and also performance will be affected assuming we have 5-10 updates for every combination of primary key identifier.

Is there any other way to do it? Is there a plan to support argMax in SimpleAggregationFunction?
Any help would be Appreciated. Thanks

**Comment by den-crane** [comment]
SimpleAggregateFunction could not support argMax, because argMax require State and SimpleAggregateFunction made for functions without State (sum/min/max)

But AggregateFunction(argMax can: https://gist.github.com/den-crane/d03524eadbbce0bafa528101afa8f794

CH designed fast queries against immutable data that's why it's unable to handle Real time updates

**Comment by shubham721** [comment]
Hey @den-crane 
Thanks. But in this case, we would need to create a source raw table, Which will contain all of the duplicate rows with the same primary keys.
And whenever we want to insert, we have to insert only in the source table and materialized view will trigger updates on the table.
Is there a way we can achieve this using one single table of Aggregating merge tree? otherwise disk usage will shot up.

**Comment by den-crane** [comment]
But there is no REAL table in my example https://gist.github.com/den-crane/d03524eadbbce0bafa528101afa8f794
```
CREATE TABLE states_raw(
...
) ENGINE = Null;
```
Engine=Null has no stored data.
 
Or you can use input function https://clickhouse.tech/docs/en/sql-reference/table-functions/input/ and insert into AggregatingMergeTree directly without Materialized View.

**Comment by shubham721** [comment]
Okay, we can achieve it with Engine = Null.
Thanks @den-crane 
https://clickhouse.tech/docs/en/sql-reference/data-types/aggregatefunction/
Here, why does it says uniq, anyif and quantiles are only aggregate functions supported in click house. I suppose Its not updated, right?

**Comment by den-crane** [comment]
@shubham721 it's just an example. The documentation does not state that only these functions are supported. Almost any function can be used including combinators i.e. `groupUniqArrayArrayState` 

https://gist.github.com/den-crane/048ce66bc59f5577d56e42d76934682e
https://gist.github.com/den-crane/6eff375752a236a456e1b3dc2ca7db62
https://gist.github.com/den-crane/49ce2ae3a688651b9c2dd85ee592cb15
