### ISSUE TITLE
When readonly replica become active data can't sync between replicas

### ISSUE THREAD

**Issue by weiyongyuan** [ClickHouse/ClickHouse#11098]
**Describe the bug**
I'm testing replicated table.I have two servers as a shard with two replicas and a zookeeper cluster with 2 nodes.
First,when i insert data into one replica ,i kill the process of zk munually which the replica has established a connection with it.
second,the replica become readonly and another become leader.the readonly replicas has a connection with another zk process.
third,i start the zk process which is killed.the readonly replica still is readonly.
forth,i restart the readonly replica ck server,then the readonly replica become active（query through the system.replicas）, not as a leader,**but,the active replicas is 1.**,and now i can insert data into it.
But,the two replicas don't sync data. I tail the leader replica's log,can see some infos like this:
**iplog_local (ReplicatedMergeTreePartCheckThread): Checking if anyone has a part covering 441683_25_25_0.
iplog_local (ReplicatedMergeTreePartCheckThread): Found part 441683_25_25_0 on 1 that covers the missing part 441683_25_25_0**
And throguth the zkclient, i can see the leader replica's queue is stacking ,and can't consume the queue's data.

Here the metrika configuration:

<clickhouse_replicas>
   
   <shard>
       <internal_replication>true</internal_replication>
       <replica>
           <host>platform-server-4</host>
           <port>9000</port>
       </replica>
       <replica>
           <host>platform-server-4</host>
           <port>9000</port>
       </replica>
   </shard>
 </clickhouse_replicas>

**How to reproduce**
you can reproduce it  like what i did.
* Which ClickHouse server version to use
20.1.6.30

**Comment by weiyongyuan** [comment]
BTW,the replicated table has a dependency on zookeeper,can we provide some tools or commands revover the replica status from readonly to active .And in my tests,there is a chance two replicas is nethier leader nor active,this seems like what brain splits .It willi be very useful if we can provide sool tools or commands to handle these situations.Thanks!

**Comment by alexey-milovidov** [comment]
Most likely it is caused by misconfiguration. Check server logs that replica is being able to connect to another replica and download data. If not, you will see error messages with explanation.
