### ISSUE TITLE
when set max_parallel_replicas=n, count query's result change to n*correct result.

### ISSUE THREAD

**Issue by weiyongyuan** [ClickHouse/ClickHouse#11092]
(you don't have to strictly follow this form)

**Describe the bug**
I have as cluster,one distribute node,two local node to consist  a shard.
when set max_parallel_replicas=n,count query'sresult change to n*correct result.
**How to reproduce**
use a replicated table,and one shard has tow or more replicas,then set set max_parallel_replicas=n.
* Which ClickHouse server version to use
20.1.6.30

* Queries to run that lead to unexpected result
>**select count()from default.iplog;**
>this count result is 387000.
>**then set max_parallel_replicas=2;**
>execute the same query.
>**select count()from default.iplog;**
>this count result is 774000.
**Expected behavior**
why is the result not 387000 but 774000 when  i set max_parallel_replicas=2?Obveriously,the result is the sum of two replicas's count result:387000 +387000 =774000 .
can we select one of the max result or most correct result of replicas?

**Comment by den-crane** [comment]
Do you have sampling on the table ? `Sample by` section?

max_parallel_replicas -- supposed to  work against sampled tables. Each replica processes part of samples.

Duplicate https://github.com/ClickHouse/ClickHouse/issues/5733

**Comment by weiyongyuan** [comment]
> Do you have sampling on the table ? `Sample by` section?
> 
> max_parallel_replicas -- supposed to work against sampled tables. Each replica processes part of samples.
> 
> Duplicate #5733

ye

**Comment by den-crane** [comment]
> yes,my table support sample data,the table has sample key.

then it's another issue. Not #5733

**Comment by weiyongyuan** [comment]
In my tests,only count query result is not correct.

**Comment by den-crane** [comment]
Then I guess it is related to select count() optimization which uses parts metadata

**Comment by weiyongyuan** [comment]
> Then I guess it is related to select count() optimization which uses parts metadata

Yes,i think so!

**Comment by phatak-dev** [comment]
Any update on this bug?

**Comment by alexey-milovidov** [comment]
@amosbird It should be very easy to fix - just don't optimize if we have `parallel_replicas_count` != 0.
