### ISSUE TITLE
re2 match issue 

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#11101]
```
SELECT match('Too late', 'Too late')
1
select match('Too late','(?i)Too late');
1
select match('Too late','(?i)too late');
0 -- ??? 

-- that helps
select match('Too late','(?i:too late)');
1 

--looks like it somehow relates to double o
select match('Too late','(?i)to{2} late');
1
select match('Too late','(?i)to(?)o late');
1
select match('Too late','(?i)to+ late');
1
select match('Too late','(?i)to(?:o|o) late');
1
```

**Comment by alexey-milovidov** [comment]
Yes, case insensitive regexps are simply not supported due to the use of OptimizedRegularExpression.

**Comment by filimonov** [comment]
@alexey-milovidov why doesn't it just bypass that? I think it should NOT do any magic with regexps if they seems complex, and contain some special regex syntax.

**Comment by alexey-milovidov** [comment]
@filimonov It will lose performance benefits.

**Comment by alexey-milovidov** [comment]
I saw that in re2 library, developers are trying to implement something similar in more accurate way.
It was named "filtered_re2". And I noticed that in recent versions of re2 it becomes better.
Maybe it can possibly replace OptimizedRegularExpression.
