### ISSUE TITLE
More than 10 'like or' catch null values

### ISSUE THREAD

**Issue by anomianne** [ClickHouse/ClickHouse#11105]
**Describe the bug**

More than 10 'like or' catch null values

**How to reproduce**

    select val
    from (
        select
            toString(
                if(
                    (arrayJoin(range(1000)) as val_base) % 2 = 0,
                    NULL,
                    val_base
                )
            ) as val
    ) as sq
    where (
        val like '%99%'
        or val like '%99%'
        or val like '%99%'
        or val like '%99%'
        or val like '%99%'
        or val like '%99%'
        or val like '%99%'
        or val like '%99%'
        or val like '%99%'
        or val like '%99%'
        or val like '%99%'
    )
	

returns 

	...
	null
	null
	99
	null
	null
	...

* Which ClickHouse server version to use

19.17.6.36

* Which interface to use, if matters
either

**Expected behavior**

Query should return 

	99
	199
	299
    ...

**Additional context**

Different values in the like pattern cause the same problem.

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/8469
already  fixed 

```
20.3.9.70

┌─val─┐
│ 99  │
│ 199 │
│ 299 │
│ 399 │
│ 499 │
│ 599 │
│ 699 │
│ 799 │
│ 899 │
│ 991 │
│ 993 │
│ 995 │
│ 997 │
│ 999 │
└─────┘
```
