### ISSUE TITLE
protobuf multiple schemafiles

### ISSUE THREAD

**Issue by hanguyen6** [ClickHouse/ClickHouse#11110]
When inserting protobuf format, ClickHouse requires external format schema : 

e.g. 
cat protobuf_messages.bin | clickhouse-client --query "INSERT INTO test.table FORMAT Protobuf SETTINGS format_schema='schemafile:MessageType'"

is it possible to specify multiple schema .proto files ? we use import statement to define dependencies between schema files.

**Comment by filimonov** [comment]
Yes, you can use imports.

If you use it on server - put those extra schemas in /var/lib/clickhouse/format_schemas folder (all paths in your import will use that as a base folder).

If you use it on client - it will use current working directory as a base folder for your includes.
