### ISSUE TITLE
Input Protobuf format for multi-levels nested data type  

### ISSUE THREAD

**Issue by hanguyen6** [ClickHouse/ClickHouse#11117]
Hi, 

The document mentions that nested messages are supported. e.g

```
message MessageType {
  message XType {
    message YType {
      int32 z;
    };
    repeated YType y;
  };
  XType x;
};
ClickHouse tries to find a column named x.y.z (or x_y_z or X.y_Z and so on).
```

I am trying to create the ClickHouse table to map the above nested structure. But look like ClickHouse supports only single nesting level as it is mentioned [here](https://clickhouse.tech/docs/en/sql-reference/data-types/nested-data-structures/nested/)

```
create table nested (x Nested (y Nested (z Int64))) ENGINE MergeTree ORDER BY tuple();

Received exception from server (version 19.11.4):

Code: 62. DB::Exception: Syntax error (data type): failed at position 21: Int64))). Expected one of: NOT, BETWEEN, AND, alias, AS, OR, NOT LIKE, LIKE, GLOBAL IN, IN, GLOBAL NOT IN, NOT IN, Comma, Dot, Arrow, QuestionMark, IS, token.
```

So does that mean we only can input Protobuf format data with single nesting level ?

**Comment by vitlibar** [comment]
Fixed, the example turned into the test `00825_protobuf_format_nested_in_nested`.
