### ISSUE TITLE
random permutation/selection for arrays

### ISSUE THREAD

**Issue by akuzm** [ClickHouse/ClickHouse#11125]
Implement functions for generating random permutations and random selections of an array.

I need permutations for generating randomization distribution in performance tests, and now have to emulate it with `order by rand()` which becomes painfully slow for big arrays. In contrast, shuffle algorithms work in linear time.

Selections would also be useful in performance tests for bootstrapping confidence intervals for query run time.

**Comment by timofeytt** [comment]
If you only need to select a single element from an array, you could do something like the following:
`SELECT arrayElement(range(3), ((rand() % length(range(3))) + 1))`

**Comment by alexey-milovidov** [comment]
`arrayShuffle(arr)`
`arrayPartialShuffle(arr, limit)`
`arrayPartialSort(lambda_func, limit, arr...)`
`arrayPartialReverseSort(lambda_func, limit, arr...)`

**Comment by jh0x** [comment]
Do you mean something like this (and related functions):
```
SELECT arrayShuffle([1, 2, 3, 4, 5, 6, 7, 8])

┌─arrayShuffle([1, 2, 3, 4, 5, 6, 7, 8])─┐
│ [4,1,2,8,6,5,3,7]                      │
└────────────────────────────────────────┘

SELECT arrayShuffle(x -> (-x), [1, 2, 3, 4, 5, 6, 7, 8])

┌─arrayShuffle(lambda(tuple(x), negate(x)), [1, 2, 3, 4, 5, 6, 7, 8])─┐
│ [-6,-4,-1,-5,-2,-7,-8,-3]                                           │
└─────────────────────────────────────────────────────────────────────┘
```

If yes, then I could have a go.

**Comment by jh0x** [comment]
I've a question about `arrayPartialSort` and `arrayPartialReverseSort`. What is the desired syntax? Above we have:
```
arrayPartialSort(lambda_func, limit, arr...)
arrayPartialReverseSort(lambda_func, limit, arr...)
```
I guess it would be nice to have a version with and without `lambda_func`?

Also, I was thinking about using `FunctionArrayMapped` - but I think it is fixed that it takes `(lambda, arr)`, `(lambda, arr...)` or `(arr)`, `(arr...)`. If that's the case should I see if it's OK to refactor and templatize it a bit more to support this new use case?
