### ISSUE TITLE
Error: Cannot read from istream at offset 0

### ISSUE THREAD

**Issue by vladimirteddy** [ClickHouse/ClickHouse#11126]
I query with format INSERT INTO MY_TABLE with option JSONEachRow, my data have one billion records, I splice and write up 1000 each time, and write from record 79k I have a bug Error: Cannot read from istream at offset 0.
My query "INSERT INTO " + table + " FORMAT JSONEachRow " + data.
![logs](https://user-images.githubusercontent.com/29521357/82631840-bc48de00-9c20-11ea-95ff-3a57cdfec5bc.png)
Log error on the server.

Please help my issue, thank.

**Comment by sneakythr0ws** [comment]
Hi! How did you fix it?

**Comment by lanceleedev** [comment]
I also have this quesion, How to check and fix it?

**Comment by vladimirteddy** [comment]
> Hi! How did you fix it?

You should log your data, maybe your data bring '/n'. if not case this, please capture your screen: data and log error.

**Comment by vladimirteddy** [comment]
> I also have this quesion, How to check and fix it?

Please check your data input to query.
