### ISSUE TITLE
Support asterisks for complex JOINs (enable multiple_joins_rewriter_version = 2 by default)

### ISSUE THREAD

**Issue by samz406** [ClickHouse/ClickHouse#11127]
hi there are 3 left join, run it's error ,please help

Multiple JOIN do not support asterisks for complex queries yet (version 19.15.3.6 (official build)

![image](https://user-images.githubusercontent.com/3055810/82634713-13ef4580-9c31-11ea-8b86-d0b031be7487.png)

**Comment by blinkov** [comment]
@samz406 as a workaround, you can just list all columns that need to be returned.

**Comment by 4ertus2** [comment]
Also you may try `multiple_joins_rewriter_version=2`, but it disabled for now cause of issues in push down predicate. You may try the query with `settings multiple_joins_rewriter_version=2, enable_optimize_predicate_expression=0` and push needed predicates manually.

**Comment by 4ertus2** [comment]
Related #10481
