### ISSUE TITLE
Duplicated codes

### ISSUE THREAD

**Issue by fastio** [ClickHouse/ClickHouse#11131]
Hi team,

When reading the codes of CH, I found the duplicated codes in the function `BlocksWithPartition MergeTreeDataWriter::splitBlockIntoParts(const Block & block, size_t max_parts)`` as follow:

```
 data.check(block, true);
 block.checkNumberOfRows();
```
In the function `void IStorage::check(const Block & block, bool need_all) const`, the method of Block.checkNumberOfRows() is invoked. So after the data.check(block, true), it's no need to call it again.

```
void IStorage::check(const Block & block, bool need_all) const
{
    const NamesAndTypesList & available_columns = getColumns().getAllPhysical();
    const auto columns_map = getColumnsMap(available_columns);

    NameSet names_in_block;

    block.checkNumberOfRows()

...
}
```

 The line ```block.checkNumberOfRows();``` in the splitBlockIntoParts function should be removed. Thanks.

**Comment by alexey-milovidov** [comment]
You're right, thank you!
I will remove this line: #11685.
