### ISSUE TITLE
TABLE xxx modify  column xxx     int; (string to in ) , session is hang .

### ISSUE THREAD

**Issue by donghy-coredumped** [ClickHouse/ClickHouse#11166]
when execute alter TABLE xxx modify column xxx int; (string to in ) , session is hang .

ClickHouse version 20.5.1 (BUILD SOURCE)
macOS

CREATE TABLE default.t1( user_id UInt32, ev_time DateTime, ev_date Date, event String)ENGINE = MergeTree(ev_date, user_id,8192);

coredumped :) CREATE TABLE default.t1( user_id UInt32, ev_time DateTime, ev_date Date, event String)ENGINE = MergeTree(ev_date, user_id,8192);

CREATE TABLE default.t1
(
user_id UInt32,
ev_time DateTime,
ev_date Date,
event String
)
ENGINE = MergeTree(ev_date, user_id, 8192)

Ok.

0 rows in set. Elapsed: 0.005 sec.

coredumped :) insert into t1 values(20,'2020-12-30:12:30:00', '2020-12-30', '1_2');

INSERT INTO t1 VALUES

Ok.

1 rows in set. Elapsed: 0.039 sec.

coredumped :) alter TABLE t1 modify column event int;

ALTER TABLE t1
MODIFY COLUMN
event int

HANG....

Error message and/or stacktrace
Error Log:
2020.05.24 16:53:29.788033 [ 776557 ] {} void DB::BackgroundProcessingPool::threadFunction(): Code: 6, e.displayText() = DB::Exception: Cannot parse string '1_2' as Int32: syntax error at position 1 (parsed just '1'). Note: there are toInt32OrZero and toInt32OrNull functions, which returns zero/NULL instead of throwing exception.: (while reading from part ./data/default/t1/20201230_20201230_1_1_0/), Stack trace (when copying this message, always include the lines below):

**Comment by alesapin** [comment]
You can this query with `KILL MUTATION id_from_system.mutations`. But what is the expected behavior?

**Comment by donghy-coredumped** [comment]
@alesapin Thank you, I think you should report an error because this conversion is not safe

**Comment by alesapin** [comment]
Actually this conversion is safe if you don't have NULLs in your Nullable column. But we cannot understand this fact without attempt to execute alter.

**Comment by donghy-coredumped** [comment]
in version 20.1.6 , I execute the same operation and return the information as follows:


localhost :) alter table tt modify column event  UInt32;

ALTER TABLE tt
    MODIFY COLUMN 
    `event` UInt32


Received exception from server (version 20.1.6):
Code: 6. DB::Exception: Received from localhost:9000. DB::Exception: Cannot parse string '1_2' as UInt32: syntax error at position 1 (parsed just '1'). Note: there are toUInt32OrZero and toUInt32OrNull functions, which returns zero/NULL instead of throwing exception..

**Comment by alesapin** [comment]
Yes, in `20.3` alters became completely asynchronous operation, and errors are not checked. I have created the feature request for such a check in https://github.com/ClickHouse/ClickHouse/issues/11329.
