### ISSUE TITLE
Buffer Table not clearing | merge table always merging | ttl not cleared 

### ISSUE THREAD

**Issue by shivakumarss** [ClickHouse/ClickHouse#11167]
- I have clickhouse installed in a machine with following configurations.
  - 16 GB RAM
  - 4 cpu core
  - 1.5 TB Non SSD Machine.

- There is a table with 80 columns which is of mergeTree Table. It has a ttl of 5 days. 
- Every day on an average we ingest around 250 ~ million rows.
- This ingestion is happening from a spark cluster in a batch of 250,000 rows.
- This ingestion is happening in buffer table.  with default configuration. ( from buffer table it is automatically going to destination table ) .
- Concurrent ingestion threads 3.
- This table has around 5300 partitions. 
  - SELECT     partition,    name,    active FROM system.parts WHERE table = '{table}'

I have noticed couple of things : 

1. Buffer table is not getting cleared, it still has a count of 5 days data.
2. Looks like the merge is ever ending . pls have a look at the attached logs. 
[merge_logs.txt](https://github.com/ClickHouse/clickhouse-jdbc/files/4673673/merge_logs.txt)
3. Even thought i have set a ttl on the main table of 5 day. it has data of 7 days.

Can you please help me with these 3 queries. 

Thanks.

**Comment by shivakumarss** [comment]
+ Another point to highlight is, day by day the partition size is being increased. ( yes the partition key has YYYY,DD,HH )

**Comment by alexey-milovidov** [comment]
> Buffer table is not getting cleared, it still has a count of 5 days data.

Could you please show the configuration of your Buffer table?

> Looks like the merge is ever ending . pls have a look at the attached logs.
merge_logs.txt

I see that the table `system.metric_log` is periodically merged in background. This is expected. The table contains information about system metrics for every second.

> yes the partition key has YYYY,DD,HH

There is no point to have so granular partition key. The number of partitions will be large and it does not have any performance benefit over just single partition with ORDER BY Date...
