### ISSUE TITLE
Possible deadlock avoided. Client should retry

### ISSUE THREAD

**Issue by zhbdesign** [ClickHouse/ClickHouse#11173]
Insert the error log below the data. The client fails to connect to the database. After a few minutes, it can connect to the database again！！！

2020.05.25 14:06:21.632933 [ 136 ] {f4176cf0-f8b9-4881-a272-116c2434c818} <Error> HTTPHandler: Code: 473, e.displayText() = DB::Exception: Possible deadlock avoided. Client should retry., Stack trace:

0. 0x3503c40 StackTrace::StackTrace() /usr/bin/clickhouse
1. 0x350de6f DB::Exception::Exception(std::string const&, int) /usr/bin/clickhouse
2. 0x6b7c989 DB::RWLockImpl::getLock(DB::RWLockImpl::Type, std::string const&) /usr/bin/clickhouse
3. 0x634be59 DB::IStorage::lockStructureForShare(bool, std::string const&) /usr/bin/clickhouse
4. 0x5f83766 DB::StoragesInfoStream::next() /usr/bin/clickhouse
5. 0x5f8612c DB::StorageSystemPartsBase::read(std::vector<std::string, std::allocator<std::string> > const&, DB::SelectQueryInfo const&, DB::Context const&, DB::QueryProcessingStage::Enum, unsigned long, unsigned int) /usr/bin/clickhouse
6. 0x61a857b void DB::InterpreterSelectQuery::executeFetchColumns<DB::InterpreterSelectQuery::Pipeline>(DB::QueryProcessingStage::Enum, DB::InterpreterSelectQuery::Pipeline&, std::shared_ptr<DB::SortingInfo> const&, std::shared_ptr<DB::PrewhereInfo> const&, std::vector<std::string, std::allocator<std::string> > const&) /usr/bin/clickhouse
7. 0x61add71 void DB::InterpreterSelectQuery::executeImpl<DB::InterpreterSelectQuery::Pipeline>(DB::InterpreterSelectQuery::Pipeline&, std::shared_ptr<DB::IBlockInputStream> const&) /usr/bin/clickhouse
8. 0x618a962 DB::InterpreterSelectQuery::executeWithMultipleStreams() /usr/bin/clickhouse
9. 0x61af914 DB::InterpreterSelectWithUnionQuery::executeWithMultipleStreams() /usr/bin/clickhouse
10. 0x61b1426 DB::InterpreterSelectWithUnionQuery::execute() /usr/bin/clickhouse
11. 0x6297579 ? /usr/bin/clickhouse
12. 0x6299daa DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, DB::Context&, std::function<void (std::string const&)>, std::function<void (std::string const&)>) /usr/bin/clickhouse
13. 0x358f7b1 DB::HTTPHandler::processQuery(Poco::Net::HTTPServerRequest&, HTMLForm&, Poco::Net::HTTPServerResponse&, DB::HTTPHandler::Output&) /usr/bin/clickhouse
14. 0x35927f1 DB::HTTPHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&) /usr/bin/clickhouse
15. 0x6d6b449 Poco::Net::HTTPServerConnection::run() /usr/bin/clickhouse
16. 0x6d680af Poco::Net::TCPServerConnection::start() /usr/bin/clickhouse
17. 0x6d687a5 Poco::Net::TCPServerDispatcher::run() /usr/bin/clickhouse
18. 0x71edc41 Poco::PooledThread::run() /usr/bin/clickhouse
19. 0x71e99c8 Poco::ThreadImpl::runnableEntry(void*) /usr/bin/clickhouse
20. 0x78c857f ? /usr/bin/clickhouse
21. 0x7f859a0ade65 start_thread /usr/lib64/libpthread-2.17.so
22. 0x7f8599bd288d clone /usr/lib64/libc-2.17.so
 (version 19.16.12.49)

**Comment by filimonov** [comment]
https://github.com/ClickHouse/ClickHouse/issues/9637

**Comment by filimonov** [comment]
Fixed in 20.4.
