### ISSUE TITLE
table system.query_log doesn't exist

### ISSUE THREAD

**Issue by amy108** [ClickHouse/ClickHouse#11194]
in config.xml i have set this table ,but it's also not be created.
![image](https://user-images.githubusercontent.com/48902828/82865847-5333d400-9f5a-11ea-858e-14144f0b03d8.png)

**Comment by amy108** [comment]
i have solved it.

**Comment by amitsharma100** [comment]
hi @amy108 how did you solve?

**Comment by tetafro** [comment]
@amitsharma100 check your `log_query` setting. 
```
SELECT name, value FROM system.settings WHERE name LIKE 'log_queries'

┌─name────────┬─value─┐
│ log_queries │ 1     │
└─────────────┴───────┘
```

It can be set in users.xml
```
<yandex>
    <profiles>
        <default>
            <log_queries>1</log_queries>
        </default>
    </profiles>
</yandex>
```

or just inside session by this command `SET log_queries = 1`

**Comment by amy108** [comment]
@amitsharma100 sorry， i overlooked my email，what @tetafro said is the perfect solution.

**Comment by Unalian** [comment]
I still find the same problem. I don't have the system.query_log althoug the logs_queries is setted 1.
<img width="1089" alt="截屏2023-12-24 19 51 35" src="https://github.com/ClickHouse/ClickHouse/assets/54164389/9d447935-5897-4164-98dc-08dacbfa4138">

**Comment by allegrinisante** [comment]
@Unalian, probably your config.xml is missing the **query log configuration** section.
You can run the server with a custom config.xml using the `--config-file=` [option](https://clickhouse.com/docs/en/operations/configuration-files).

In your config.xml add the query_log configuration 
```
    <query_log>
        <database>system</database>
        <table>query_log</table>
        <engine>Engine = MergeTree PARTITION BY event_date ORDER BY event_time TTL event_date + INTERVAL 30 day</engine>
        <flush_interval_milliseconds>7500</flush_interval_milliseconds>
        <max_size_rows>1048576</max_size_rows>
        <reserved_size_rows>8192</reserved_size_rows>
        <buffer_size_rows_flush_threshold>524288</buffer_size_rows_flush_threshold>
        <flush_on_crash>false</flush_on_crash>
    </query_log>
```
Documentation [here](https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings#query-log)
