### ISSUE TITLE
Skip useless values in primary key in memory.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#11191]
Suppose there is primary key `(x, y)` when `x` is arbitrary column and `y` is variable length column like `String`.

When loading index in memory, we can avoid storing actual value of y if the value of x is different from the value in previous and next mark. We can store default value instead.

Example:

Instead of:
`... (123, 'hello'), (124, 'world'), (125, 'goodbye') ...`

We can store:
`... (123, 'hello'), (124, ''), (125, 'goodbye') ...`

Because 124 is not equal to 123 and 125.
And the actual value of `y` column is not important.

**Comment by alexey-milovidov** [comment]
@CurtizJ RFC.

**Comment by alexey-milovidov** [comment]
@UnamedRus You are right, we need some modification to this scheme.

**Comment by amosbird** [comment]
> What will happen, if we run query like this: SELECT * FROM table WHERE x = 124 and y = 'zoo' Isn't it would scan 2 granules instead of 1?

How does `y = 'zoo'` make a difference? IIUC, `zoo > ''` and `zoo > 'world'`

**Comment by alexey-milovidov** [comment]
#60091

**Comment by alexey-milovidov** [comment]
This is proven to be wrong. But see https://github.com/ClickHouse/ClickHouse/issues/60091
