### ISSUE TITLE
How to set maximum number of merge threads in the background via parameters?

### ISSUE THREAD

**Issue by BernieJiangDL** [ClickHouse/ClickHouse#11193]
Is there any parameters in the config.xml to set maximum number of background merge threads besides set "parts_to_throw_insert" and batchsize of inserts?

The 'Too many parts ...' exception happens sometime when inserting batch of  parts into multiple partitions.

**Comment by filimonov** [comment]
Background merges are executed by thread from so called 'background thread pool'.
Check the `background_pool_size` setting. 

And usually, if you face 'Too many parts ...'  it's NOT caused by background pool. Most common reason is bad schema (too granular partitioning, too aggressive compression, etc) creating too many merges, or making them slow.

**Comment by BernieJiangDL** [comment]
> Background merges are executed by thread from so called 'background thread pool'.
> Check the `background_pool_size` setting.
> 
> And usually, if you face 'Too many parts ...' it's NOT caused by background pool. Most common reason is bad schema (too granular partitioning, too aggressive compression, etc) creating too many merges, or making them slow.

Got it. But I found another parameter "max_replicated_merges_in_queue" which is described as "How many tasks of merging and mutating parts are allowed simultaneously in ReplicatedMergeTree queue".

Whats the significant difference between max_replicated_merges_in_queue and background_pool_size? Those seem the same literally.


BTW, the thought to have the number of threads up is came up with our high performance servers which might have made it more stable and faster than before.

**Comment by BigRantLing** [comment]
@filimonov Hi !  Is `background_pool`  used by all MergeTree() engine on single node?

**Comment by alexey-milovidov** [comment]
Yes, background pool is shared for all tables.

**Comment by alexey-milovidov** [comment]
The default value of the size of background pool is mostly optimal, there is little sense tweaking it.

**Comment by alexey-milovidov** [comment]
> Most common reason is bad schema (too granular partitioning, too aggressive compression, etc) creating too many merges, or making them slow.

+1 Absolutely true.

**Comment by alexey-milovidov** [comment]
> Whats the significant difference between max_replicated_merges_in_queue and background_pool_size?

The first is the limit on scheduled merges and the second is on currently running merges.
