### ISSUE TITLE
Distributed engine data loss

### ISSUE THREAD

**Issue by pcode93** [ClickHouse/ClickHouse#11195]
Hey, I'm using a Distributed engine on top of a replicated table. 
I want to insert data using the Distributed table (instead of inserting directly into replicas).

The documentation states that
```If the server ceased to exist or had a rough restart (for example, after a device failure) after an INSERT to a Distributed table, the inserted data might be lost```

Can such data loss be prevented ? Would using `insert_distributed_sync` help?

**Comment by alexey-milovidov** [comment]
> Would using insert_distributed_sync help?

Yes, this setting will ensure that the data is successfully sent to replicas.
