### ISSUE TITLE
Buffer tables with KafkaEngine? When?

### ISSUE THREAD

**Issue by xmariachi** [ClickHouse/ClickHouse#11209]
I have a KafkaStreams topology where I connect the output topics (~15 of them) to KafkaEngine tables (then using usual MV > ReplicatedReplacingMergeTree > Distributed table). 
Some of my topics have a lot of messages but some other ones may have a few by minute, and that can fluctuate. 
Would it make sense to set a Buffer table layer in between those MV > *MergeTree tables with lower number of messages in order to group them?

What is the reliability of Buffer tables here? Being them in RAM, and since consuming from KafkaEngine would advance the offset, would I be facing a higher message loss if server breaks (or e.g. container is shut down by Docker daemon)?

I had a couple of TooManyParts errors in the past, although I cannot be certain that they are caused by these topics with smaller inserts.

**Comment by filimonov** [comment]
You don't need Buffer tables after Kafka. Kafka flushed the data in blocks of kafka_max_block_size, or by timeout controlled by `stream_flush_interval_ms` setting.
