### ISSUE TITLE
JSONEachRow format does not support inserting numeric value into a column of type Enum

### ISSUE THREAD

**Issue by vzakaznikov** [ClickHouse/ClickHouse#11227]
**Describe the issue**
When a table has a column of type Enum then using Values format it is possible to 
insert into this column numerical values. The same is not possible when using
JSONEachRow format.

**How to reproduce**
```
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 20.5.1 revision 54435.

user-node :) INSERT INTO messages FORMAT JSONEachRow {"message_keyword":"NONE"}
INSERT INTO messages FORMAT JSONEachRow
Ok.
1 rows in set. Elapsed: 0.026 sec. 

user-node :) INSERT INTO messages (message_keyword) VALUES (5)
INSERT INTO messages (message_keyword) VALUES
Ok.
1 rows in set. Elapsed: 0.033 sec. 

user-node :) INSERT INTO messages FORMAT JSONEachRow {"message_keyword":5}
INSERT INTO messages FORMAT JSONEachRow
Exception on client:
Code: 26. DB::Exception: Cannot parse JSON string: expected opening quote: (while read the value of key message_keyword): (at row 1)
```

**Comment by vzakaznikov** [comment]
The problem is at https://github.com/ClickHouse/ClickHouse/blob/1658705f7c82839906b9d9b40afde08f2d37f428/src/DataTypes/DataTypeEnum.cpp#L195

**Comment by alexey-milovidov** [comment]
Yes, it can be fixed - not only for JSONEachRow but also for TSV/CSV.
In the latter case we also have to ensure that Enum does not contain values that are ambiguous with numbers.

**Comment by alexey-milovidov** [comment]
This is the relevant task: https://github.com/ClickHouse/ClickHouse/issues/10682
