### ISSUE TITLE
How to match character classes in regular expression string functions

### ISSUE THREAD

**Issue by hydra-yl** [ClickHouse/ClickHouse#11239]
`select extract('hello', '[a-z]+')`
Result: hello

`select extract('άλφα', '\p{Greek}+')`
Result: 

`select extract('你好', '\p{Han}+')`
Result:

**Comment by filimonov** [comment]
You need to escape slashes one more time.
```
SELECT extract('你好άλφα', '\\p{Han}+')

┌─extract('你好άλφα', '\\p{Han}+')─┐
│ 你好                             │
└──────────────────────────────────┘
```

See https://github.com/ClickHouse/ClickHouse/issues/10922
