### ISSUE TITLE
 Cannot reserve 1.00 MiB, not enough space

### ISSUE THREAD

**Issue by leobelive** [ClickHouse/ClickHouse#11247]
DB::ExceptionDB::Exception: Cannot reserve 1.00 MiB, not enough space. Stack trace:
0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xbb8c1cc in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x4ff4bb9 in /usr/bin/clickhouse
2. ? @ 0x4c55fe5 in /usr/bin/clickhouse
3. DB::MergeTreeData::reserveSpacePreferringTTLRules(unsigned long, DB::MergeTreeDataPartTTLInfos const&, long, unsigned long) const @ 0x8ef9fc6 in /usr/bin/clickhouse
4. DB::MergeTreeDataWriter::writeTempPart(DB::BlockWithPartition&) @ 0x8f906dc in /usr/bin/clickhouse
5. DB::MergeTreeBlockOutputStream::write(DB::Block const&) @ 0x8eee305 in /usr/bin/clickhouse
6. DB::PushingToViewsBlockOutputStream::write(DB::Block const&) @ 0x9469458 in /usr/bin/clickhouse
7. DB::SquashingBlockOutputStream::writeSuffix() @ 0x9482b3a in /usr/bin/clickhouse
8. DB::TCPHandler::processInsertQuery(DB::Settings const&) @ 0x504df32 in /usr/bin/clickhouse
9. DB::TCPHandler::runImpl() @ 0x504f5b3 in /usr/bin/clickhouse
10. DB::TCPHandler::run() @ 0x504faa9 in /usr/bin/clickhouse
11. Poco::Net::TCPServerConnection::start() @ 0x9c68017 in /usr/bin/clickhouse
12. Poco::Net::TCPServerDispatcher::run() @ 0x9c6840d in /usr/bin/clickhouse
13. Poco::PooledThread::run() @ 0xbbfaf4f in /usr/bin/clickhouse
14. Poco::ThreadImpl::runnableEntry(void*) @ 0xbbf81b8 in /usr/bin/clickhouse
15. ? @ 0xbbf98e9 in /usr/bin/clickhouse
16. start_thread @ 0x7e65 in /usr/lib64/libpthread-2.17.so
17. clone @ 0xfe88d in /usr/lib64/libc-2.17.so

can anyone help ， how to resolved  this issue? 
when i  insert   about 20k data with clickhouse-jdbc  , the error comes ?

**Comment by mdianjun** [comment]
+1

```
:) insert into hive_data SELECT number, number+100 FROM numbers(10);

INSERT INTO hive_data SELECT
    number,
    number + 100
FROM numbers(10)

Received exception from server (version 20.4.2):
Code: 243. DB::Exception: Received from localhost:9000. DB::Exception: Cannot reserve 1.00 MiB, not enough space.

0 rows in set. Elapsed: 0.100 sec.
```

**Comment by den-crane** [comment]
Check inodes

df -i

**Comment by dannyeuu** [comment]
I have the same error:

![Screenshot from 2020-09-01 14-26-51](https://user-images.githubusercontent.com/6808348/91886114-401e5780-ec5f-11ea-8edf-d49d59611beb.png)


With disks space ok

![Screenshot from 2020-09-01 14-27-56](https://user-images.githubusercontent.com/6808348/91886195-57f5db80-ec5f-11ea-86d1-dce265161a0d.png)

And disks inode ok:

![Screenshot from 2020-09-01 14-28-26](https://user-images.githubusercontent.com/6808348/91886239-6c39d880-ec5f-11ea-8abc-673e46f20537.png)

**Comment by den-crane** [comment]
@dannyeuu your pictures proves nothing because they reflect current state. 
Probaly you had zero space available in the moment of the error happened. The reason of that is that you have only 42GB available and inactive parts are stored 8 minutes. During this 8 minutes all free disk space were occupied.

Try to monitor disk space during massive inserts. And reconfigure mergetree setting `old_parts_lifetime`  https://github.com/ClickHouse/ClickHouse/issues/11724#issuecomment-645112896
for example for table `alter table mytable MODIFY SETTING old_parts_lifetime=10`

**Comment by alexey-milovidov** [comment]
In recent versions we have added better diagnostics on free space. It will show you the filesystem path, the amount of total and free space and inodes.

**Comment by jazdw** [comment]
@alexey-milovidov 
> In recent versions we have added better diagnostics on free space. It will show you the filesystem path, the amount of total and free space and inodes.

Where would this be located in the logs? I have the latest Clickhouse and cannot see anything like this?

```
2022.05.17 17:07:10.132881 [ 631250 ] {} <Error> void DB::SystemLog<DB::AsynchronousMetricLogElement>::flushImpl(const std::vector<LogElement> &, uint64_t) [LogElement = DB::AsynchronousMetricLogElement]: Code: 243. DB::Exception: Cannot reserve 1.00 MiB, not enough space. (NOT_ENOUGH_SPACE), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xb6fc2fa in /usr/bin/clickhouse
1. DB::MergeTreeData::reserveSpacePreferringTTLRules(std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, unsigned long, DB::MergeTreeDataPartTTLInfos const&, long, unsigned long, bool, std::__1::shared_ptr<DB::IDisk>) const @ 0x16a57083 in /usr/bin/clickhouse
2. DB::MergeTreeDataWriter::writeTempPart(DB::BlockWithPartition&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::Context const>) @ 0x16b82276 in /usr/bin/clickhouse
3. DB::MergeTreeSink::consume(DB::Chunk) @ 0x16b7c926 in /usr/bin/clickhouse
4. DB::SinkToStorage::onConsume(DB::Chunk) @ 0x1728bc1d in /usr/bin/clickhouse
5. ? @ 0x1720d317 in /usr/bin/clickhouse
6. ? @ 0x1720d0c9 in /usr/bin/clickhouse
7. DB::ExceptionKeepingTransform::work() @ 0x1720c97f in /usr/bin/clickhouse
8. DB::ExecutionThreadContext::executeTask() @ 0x170544c8 in /usr/bin/clickhouse
9. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x17047b3e in /usr/bin/clickhouse
10. DB::PipelineExecutor::executeStep(std::__1::atomic<bool>*) @ 0x17047340 in /usr/bin/clickhouse
11. DB::SystemLog<DB::AsynchronousMetricLogElement>::flushImpl(std::__1::vector<DB::AsynchronousMetricLogElement, std::__1::allocator<DB::AsynchronousMetricLogElement> > const&, unsigned long) @ 0x162a1c0c in /usr/bin/clickhouse
12. DB::SystemLog<DB::AsynchronousMetricLogElement>::savingThreadFunction() @ 0x162a0040 in /usr/bin/clickhouse
13. ? @ 0xb7c9c91 in /usr/bin/clickhouse
14. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xb7a7ba7 in /usr/bin/clickhouse
15. ? @ 0xb7ab5dd in /usr/bin/clickhouse
16. ? @ 0x7fec9c644609 in ?
17. __clone @ 0x7fec9c569133 in ?
 (version 22.4.5.9 (official build))
```

**Comment by kernel288** [comment]
may be                 <keep_free_space_bytes>9895604649</keep_free_space_bytes>  this is too big 
check it

**Comment by qloog** [comment]
> may be <keep_free_space_bytes>9895604649</keep_free_space_bytes> this is too big check it

It works, thank you very much.
