### ISSUE TITLE
visitParamExtractRaw does not work if the JSON contains a string with unmatched { or [

### ISSUE THREAD

**Issue by devwout** [ClickHouse/ClickHouse#11254]
### Query

`select visitParamExtractRaw('{"k":"{"}', 'k')`

### Expected result

`'"{"'`

### Actual result

`''`

### Clickhouse version

20.4.4.18-stable

### Additional information

Also applicable for `[` instead of `{`.

**Comment by qoega** [comment]
20.3 has no problem.
Also not reproducing in 20.5/master
```
│ VERSION_GITHASH           │ 91df18a906dcffdbee6816e5389df6c65f86e35f                                                                                                     
```

``` sql
SELECT visitParamExtractRaw('{"k":"{"}', 'k')

┌─visitParamExtractRaw('{"k":"{"}', 'k')─┐
│                                        │
└────────────────────────────────────────┘
```
Need to check on exact same version.

**Comment by devwout** [comment]
The behavior described is also applicable to `20.3.10.75` and older versions. The blank output in your comment is not what I would expect. As described in the ticket, I would expect `'"{"'`.

```
$ docker run -i yandex/clickhouse-server:20.3.10.75 clickhouse-local --format JSONEachRow -q "select visitParamExtractRaw('{\"k\":\"{\"}', 'k')"
{"visitParamExtractRaw('{\"k\":\"{\"}', 'k')":""}
```

Expected

```
{"visitParamExtractRaw('{\"k\":\"{\"}', 'k')":"{"}
```
