### ISSUE TITLE
Using clickhouse-client to import CSV/TSV treat zero as null/empty

### ISSUE THREAD

**Issue by calebeaires** [ClickHouse/ClickHouse#11250]
To this table:
```sql

CREATE TABLE base (
type Nullable(String)
qtd Nullable(Double)
) ENGINE MergeTree
ORDER BY tuple()

```

I have this TabSeparated data into a file (to be imported with clickhouse-client)

```csv
type,qtd
Car,12
Bike,0
Other,
```
Issue: after import with clickhouse whit args FORMAT TabSeparated the **values with zero becomes NULL/Empty**

| type  |qtd   |
|---|---|
|  Car | 12  |
|  Bike |   |
|  Other |   |

Question: how to make sure the number ZERO will be inputed as 0, not NULL/Empty?

**Comment by den-crane** [comment]
I could not reproduce it.

20.5.1.3496
```

CREATE TABLE base (
type Nullable(String), qtd Nullable(Double)) ENGINE MergeTree ORDER BY tuple();

cat test.tsv
Car	12
Bike	0
Other	

cat test.tsv |clickhouse-client -q "insert into base format TSV" --input_format_tsv_empty_as_default=1

┌─type──┬──qtd─┐
│ Car   │   12 │
│ Bike  │    0 │
│ Other │ ᴺᵁᴸᴸ │
└───────┴──────┘


cat test.tsv |clickhouse-client -q "insert into base format TSV"

┌─type──┬─qtd─┐
│ Car   │  12 │
│ Bike  │   0 │
│ Other │   0 │
└───────┴─────┘

```

**Comment by calebeaires** [comment]
input_format_tsv_empty_as_default  help me with some issue. Thanks to clarify.
