### ISSUE TITLE
CREATE TABLE as remote

### ISSUE THREAD

**Issue by Tri0L** [ClickHouse/ClickHouse#11251]
Hello.

ClickHouse: **20.1.2.4**

Don't know, bug or feature, but I think it is unexpected behavior.

I try create table as copy of table from another server:
```
CREATE TABLE dest_table AS remote('another.clickhouse.host', 'schema', 'src_table', 'user', 'pwd');
```

**Expected behavior**
As written in docs 

*Creates a table with the structure and data returned by a table function.*

**Really do:**
Really CH create something like foreign table, without data and schema.
Selects/inserts sends to remote server.
```
SHOW CREATE TABLE dest_table

┌─statement───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ CREATE TABLE dest_table AS remote('another.clickhouse.host', 'schema', 'src_table', 'user', 'pwd') │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

**Comment by alexey-milovidov** [comment]
It works exactly as it was designed.
The documentation has to be updated.

**Comment by alexey-milovidov** [comment]
@BayoNet Proposed wording:

It creates a table that is the same as the result of the table function. The created table will work in the same way as the corresponding table function.

**Comment by kitaisreal** [comment]
Fixed in https://github.com/ClickHouse/ClickHouse/pull/19682.

**Comment by 3fen** [comment]
How to create an empty table as a remote one? 
I dont find it in [here](https://clickhouse.com/docs/en/sql-reference/statements/create/table). Thanks

**Comment by alexey-milovidov** [comment]
`CREATE TABLE t EMPTY AS SELECT * FROM remote(...)`

**Comment by ei-grad** [comment]
It’s not so easy to remember that `ENGINE` must come before `EMPTY`, the error message isn’t very helpful, and it's not immediately obvious which part of the documentation applies [relevant documentation section](https://clickhouse.com/docs/sql-reference/statements/create/table#from-select-query). So, for the next person coming here from Google, there’s a more complete query:
```sql
CREATE TABLE t ENGINE = MergeTree ORDER BY (...) EMPTY AS SELECT * FROM remote(...)
```
