### ISSUE TITLE
truncate + on cluster + replicatedMergeTree operation haves the servers down.

### ISSUE THREAD

**Issue by BernieJiangDL** [ClickHouse/ClickHouse#11277]
**Describe the bug**
The target database seems to be down after running truncate on cluster pattern.

**How to reproduce**
1. ClickHouse server version 19.9.5 revision 54421
2. ClickHouse client version 19.9.5.36 or spark jdbc whichever I use have the database on servers down. 
3. The table engine is replicatedMergeTree
4. The query sql is like "truncate table {database}.{table_name} on cluster {cluster_name}"

**Expected behavior**
The records on each table have been removed correctly.

**Error message and/or stacktrace**
Some of the server threw "Cannot execute replicated DDL query on leader" , then stuck all the way untill disconnection.  

And when login into the stuck server, run "use test(database)",  and "show tables" which would make the client stuck and hang in there.

Only restart server can solve this problems currently.

Additionally, "truncate table {database}.{table_name}" on single server is running correctly.

**Comment by qoega** [comment]
can you reproduce problem with newer version? 19.9 is not supported for a while. You can check 19.14 LTS, 20.3 LTS or 20.1, 20.4 versions.

**Comment by filimonov** [comment]
The issue is most probable caused by
https://github.com/ClickHouse/ClickHouse/issues/6725
+ additionally
https://github.com/ClickHouse/ClickHouse/issues/9259

You need to update.
