### ISSUE TITLE
Fail to downgrade from 20.4. to 19.14, unknown setting min_bytes_for_wide_part in query_log

### ISSUE THREAD

**Issue by winter7** [ClickHouse/ClickHouse#11281]
**Describe the issue**
I plan to upgrade my clickhouse version from `19.4.7.15` to `20.4.4.18` and did upgrade test successfully. 
And in order to prepare for possible risks, I need to test downgrade. 
But after I tried to downgrade, clickhouse server failed to restart.
I read about https://clickhouse.tech/docs/en/whats-new/changelog/#backward-incompatible-change. And I tried to delete `clickhouse/data/system/query_log/` and `clickhouse/metadata/system/query_log/` and restart to ensure that `query_log` no longer exist in system database. (There is no other system log table in my `clickhouse/data/system`). But I still failed to downgrade to 19.14.7.15.
The <Error> logs are just same as it was before I tried to delete the `query_log`.

**How to reproduce**
* Downgrade clickhouse version from 20.4.4.18 to 19.14.7.15.

**Error message and/or stacktrace**
```
2020.05.29 07:51:31.138155 [ 1 ] {} <Error> Application: Caught exception while loading metadata: Code: 132, e.displayText() = DB::Exception: Cannot create table from metadata file /var/lib/clickhouse/metadata/system//query_log.sql, error: DB::Exception: Unknown setting min_bytes_for_wide_part for storage MergeTree, stack trace:
0. 0x55cf752311e0 StackTrace::StackTrace() /usr/bin/clickhouse
1. 0x55cf75230fb5 DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int) /usr/bin/clickhouse
2. 0x55cf7502e0a3 ? /usr/bin/clickhouse
3. 0x55cf788a564f ? /usr/bin/clickhouse
4. 0x55cf788a72f5 std::_Function_handler<std::shared_ptr<DB::IStorage> (DB::StorageFactory::Arguments const&), std::shared_ptr<DB::IStorage> (*)(DB::StorageFactory::Arguments const&)>::_M_invoke(std::_Any_data const&, DB::StorageFactory::Arguments const&) /usr/bin/clickhouse
5. 0x55cf786d2211 DB::StorageFactory::get(DB::ASTCreateQuery&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, DB::Context&, DB::Context&, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, bool, bool) const /usr/bin/clickhouse
6. 0x55cf7843b631 DB::createTableFromDefinition(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, DB::Context&, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /usr/bin/clickhouse
7. 0x55cf78b0681f ? /usr/bin/clickhouse
8. 0x55cf78b06e5f ? /usr/bin/clickhouse
9. 0x55cf7526e8de ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::_List_iterator<ThreadFromGlobalPool>) /usr/bin/clickhouse
10. 0x55cf7526eeee ThreadFromGlobalPool::ThreadFromGlobalPool<ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::function<void ()>, int, std::optional<unsigned long>)::{lambda()#3}>(ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::function<void ()>, int, std::optional<unsigned long>)::{lambda()#3}&&)::{lambda()#1}::operator()() const /usr/bin/clickhouse
11. 0x55cf7526c38c ThreadPoolImpl<std::thread>::worker(std::_List_iterator<std::thread>) /usr/bin/clickhouse
12. 0x55cf7aedab60 ? /usr/bin/clickhouse
13. 0x7f86b187a6db start_thread /lib/x86_64-linux-gnu/libpthread-2.27.so
14. 0x7f86b119788f clone /lib/x86_64-linux-gnu/libc-2.27.so
```
**Additional context**
I made sure there were no system log tables in `clickhouse/data/system` folder, but when I restarted the server I always got the exact same error as above about `min_bytes_for_wide_part` settings in system log table. Did I miss anything when deleting table data?
By the way I started clickhouse with [clickhouse-operator](https://github.com/Altinity/clickhouse-operator) in EKS, I can't manually remove `min_bytes_for_wide_part` setting from `query_log.sql`.

**Comment by alesapin** [comment]
You just need to delete the metadata file and data directory for each log table. In your case, it seems like you didn't delete `clickhouse/metadata/system/query_log.sql`.

**Comment by qoega** [comment]
This case is covered in changelog for 20.4 release
https://clickhouse.tech/docs/en/whats-new/changelog/#backward-incompatible-change
