### ISSUE TITLE
complex SQL on MATERIALIZED VIEW

### ISSUE THREAD

**Issue by jencoldeng** [ClickHouse/ClickHouse#11282]
1-Table `Detail` storages the detail data, including domains , request count, and flow in bytes, it maybe duplicate, because one `stattime`(that is , one minute) and one domain maybe more than one report data inserted in the `Detail` table. 
```
CREATE TABLE Detail_local(
  statdate UInt64,
  stattime UInt64, 
  domain String, 
  flow UInt64, 
  request UInt64)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/Detail/{shard}', '{replica}') 
PARTITION BY statdate
ORDER BY (statdate,stattime,domain);

CREATE TABLE IF NOT EXISTS Detail AS Detail_local
ENGINE = Distributed(kstat_shard, kstat, Detail_local, rand());
```

2-Table `Summary` is MATERIALIZED VIEW, and I want it to summary data group by `date-domain`. My method is, the `flow` of date-domain, is the max number of the specified statdate and domain, and the `request` is the summary result of the specified statdate and domain.

```
CREATE MATERIALIZED VIEW Summary_local
ENGINE = ReplicatedAggregatingMergeTree('/clickhouse/tables/Summary/{shard}', '{replica}') 
ORDER BY (statdate,domain)
AS 
  select 
    statdate,
    domain,
    maxState(minute_flow) as daily_flow,
    sumState(minute_request) as daily_request
  from
     (SELECT 
        statdate,
        stattime,
        domain,
        sum(flow) as minute_flow,
        sum(request) as minute_request
      FROM Detail_local
      group by statdate,stattime,domain)
  group by statdate,domain;

CREATE TABLE IF NOT EXISTS Summary AS Summary_local
ENGINE = Distributed(kstat_shard, kstat, Summary_local, rand());
```

3-My question is, the `sum` number (that is `daily_request`) in Table `Summary ` is correct, but the `max` number (`daily_flow`) is wrong.

```
insert into Detail values(1,1,'domain1',100,200);
insert into Detail values(1,1,'domain1',200,300);

-- The following maxMerge(flow) is WRONG RESULT, 
select statdate,domain,maxMerge(daily_flow) as daily_flow,sumMerge(daily_request) as daily_request
from Summary
group by statdate,domain
order by statdate,domain;

┌─statdate─┬─domain──┬─daily_flow─┬─daily_request─┐
│        1 │ domain1 │        300 │           500 │
└──────────┴─────────┴────────────┴───────────────┘

-- The following is correct
select statdate,domain,max(minute_flow) as daily_flow, sum(minute_request) as daily_request
from
  (select statdate,stattime,domain,sum(flow) as minute_flow, sum(request) as minute_request
  from Detail
  group by statdate,stattime,domain)
group by statdate,domain
order by statdate ,domain;
┌─statdate─┬─domain──┬─daily_flow─┬─daily_request─┐
│        1 │ domain1 │        300 │           500 │
└──────────┴─────────┴────────────┴───────────────┘
```

I want to know, what is wrong with my  MATERIALIZED VIEW??

**Comment by BernieJiangDL** [comment]
CREATE MATERIALIZED VIEW Summary_local
ENGINE = ReplicatedSummingMergeTree

**Comment by jencoldeng** [comment]
> CREATE MATERIALIZED VIEW Summary_local
> ENGINE = ReplicatedSummingMergeTree
> 
> this might help

Thans, but it dos not work....  :)

**Comment by den-crane** [comment]
>maxState(minute_flow) as daily_flow,
>      sum(flow) as minute_flow

it could not work because MV does not read source table. It reads data from INSERTs, moreover it reads in blocks.
For example Insert breaks into two blocks 
First block: stattime = 10:00:00 flow = 1
Second block: stattime = 10:00:00 flow = 1
It will calculate two different sum(flow), both == 1 , instead of 2.
The same with 2 different inserts.

It could not be solved without AggregatingMergeTree with minute aggregation.

-----

instead of maxState / sumState you can use SimpleAggregateFunctions, they are cheaper.

https://gist.github.com/den-crane/d88f9ef887f879c7be71fb40ae943a94#file-gistfile1-txt-L75
https://clickhouse.tech/docs/en/sql-reference/data-types/simpleaggregatefunction/

**Comment by jencoldeng** [comment]
> > maxState(minute_flow) as daily_flow,
> > sum(flow) as minute_flow
> 
> it could not work because MV does not read the source table. It reads only data from INSERTs, moreover it reads data in blocks.
> For example Insert broke into two blocks
> First block: stattime = 10:00:00 flow = 1
> Second block: stattime = 10:00:00 flow = 1
> It will calculate two different sum(flow), both == 1 , instead of 2.
> The same with 2 different inserts.
> 
> It could not be solved without AggregatingMergeTree with minute aggregation.
> 
> instead of maxState / sumState you can use SimpleAggregateFunctions, they are cheaper.
> 
> https://gist.github.com/den-crane/d88f9ef887f879c7be71fb40ae943a94#file-gistfile1-txt-L75
> https://clickhouse.tech/docs/en/sql-reference/data-types/simpleaggregatefunction/

that means, I should create a minute aggregation table MV, and the Daily aggregation MV will read from the minute agregation MV's `local inner` table ?

**Comment by jencoldeng** [comment]
This is my code:

```
--Detail table, nothing to change

CREATE TABLE Detail_local(
  statdate UInt64,
  stattime UInt64, 
  domain String, 
  flow UInt64, 
  request UInt64)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/Detail/{shard}', '{replica}') 
PARTITION BY statdate
ORDER BY (statdate,stattime,domain);

--minute summary, all data accumulate group by statdate,stattime and domain

CREATE MATERIALIZED VIEW MinuteSummary_local
ENGINE = ReplicatedAggregatingMergeTree('/clickhouse/tables/MinuteSummary/{shard}', '{replica}') 
PARTITION BY statdate
ORDER BY (statdate,stattime,domain)
AS 
  select statdate,stattime,domain,sumState(flow) as flow, sumState(request) as request
  from Detail_local
  group by statdate,stattime,domain;

--This is the daily MV

CREATE MATERIALIZED VIEW DailySummary_local
ENGINE = ReplicatedAggregatingMergeTree('/clickhouse/tables/DailySummary/{shard}', '{replica}') 
PARTITION BY statdate
ORDER BY (statdate,domain)
AS
  select 
    statdate,
    domain,
    maxState(minute_flow) as flow,
    sumState(minute_request) as request
  from
      (SELECT
          statdate,
          stattime,
          domain,
          sumMerge(flow) as minute_flow,
          sumMerge(request) as minute_request
      FROM `.inner.MinuteSummary_local`
      GROUP BY
          statdate,
          stattime,
          domain)
  GROUP BY
      statdate,
      domain;
```

My problem is , the daily result is not change at all....Maybe something is wrong in the daily MV.

**Comment by den-crane** [comment]
I meant you can only calculate MAX from preadaggregated by minute MV.

It's impossible in CH to calculate `MAX ( SUM() group by minute) group by day` using MV.
I think it have no sense to built such MV, it easier to use Detail_local. Or calculate `MAX ( SUM() group by minute) group by day` after day ended using cron.

**Comment by jencoldeng** [comment]
thanks for your answer. I konw what to do.

I will make a cron task, calculate a **Daily Summary Table** data using data in **Minute Summary table**, every a few minute.

The Daily Summary Table will use **ReplacingMergeTree**, and use **insert_time** as its version.

Then, a view (not MV) is used to query data in Daily Summary Table, it looks like `select statdate,domain,max(flow) as flow, max(request) as request from DailyView group by statdate,domain;`
