### ISSUE TITLE
toStartOfDay function always returning "09:00:00" hour

### ISSUE THREAD

**Issue by defusevenue** [ClickHouse/ClickHouse#11287]
When using the `toStartOfDay` function the hour always seems to be `09:00:00`. Is this expected behavior? I thought the time should always be `00:00:00` since that is when the day starts.

This is an example from my table.

Table data:
date|
------------ |
2020-05-05 10:11:28
2020-05-07 06:16:28
2020-05-08 06:16:28
2020-05-09 06:16:28
2020-05-29 21:16:28

Running the sql query below I get the following result.
```sql
SELECT toStartOfDay(date) FROM temp ORDER BY date

2020-05-05 09:00:00
2020-05-06 09:00:00
2020-05-07 09:00:00
2020-05-08 09:00:00
2020-05-29 09:00:00
```

**Comment by champtar** [comment]
@defusevenue what is the timezone on your server and client ?

**Comment by defusevenue** [comment]
The server's timezone is `Etc/UTC`. Not sure about the client, I'm using DBeaver and the driver property for `use_time_zone` is empty. 

Should I be setting the driver timezone to UTC as well?

**Comment by qoega** [comment]
What is the type of `date` column? You can define its timezone explicilty.
For debug purposes you can format values on server as strings to omit driver with formatDateTime as in ClickHouse Playground example https://play.clickhouse.tech/?file=datetime

Is your question answered?

**Comment by defusevenue** [comment]
Yes, it seems like the issue was with DBeaver as the time is displayed correctly with Tabix and the playground.

Thank you so much for the quick reply. I'll be closing this issue.

**Comment by den-crane** [comment]
SELECT toStartOfDay(date) FROM temp ORDER BY date -- toStartOfDay in UTC TZ

JDBC converts 00:00 UTC to your client timezone +09
Try 
SELECT toStartOfDay(date,  **'Asia/Tokyo'**) FROM temp
