### ISSUE TITLE
Add separate max_memory_usage setting for distributed nodes 

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#11292]
**Use case**
Suppose we set max_memory_usage constraints on all nodes in cluster
There are several scenarios:
1) Large initiator and lots of small distributed nodes. We can not set small to limit by max_memory_usage on distributed nodes as it will limit memory usage on large initiator.
2) Small initiator and large distributed nodes. We can not set limit on distributed nodes larger than constraint on initiator.

- We may want to limit memory usage on distributed nodes in per user manner but have common limit/constraint on initiator node. We can use this setting in initiator users config to set separate limits.

**Describe the solution you'd like**
- [ ] Add user setting named like `distributed_max_memory_usage`
- [ ] Add min/max constraint for `distributed_max_memory_usage` in profile config
- [ ] If distributed_max_memory_usage is not set use old logic: distributed_max_memory_usage= max_memory_usage.
- [ ] If distributed_max_memory_usage is set, initiator max_memory_usage constraints are applied only on initiator node and `distributed_max_memory_usage` is sent to distributed nodes as max_memory_usage.
- [ ] We have to choose if distributed_max_memory_usage is not set, in which scope initiator constraint is applied: currently it also limits the `max_memory_usage` sent to distributed nodes.

**Additional context**
In cloud environment heterogeneous cluster is usually used, as it is easy to select size for different types of nodes.
We currently encounter problems during cluster update, when memory usage on initiator can be higher in transitional state and can't increase memory limit only on initiator.

**Comment by azat** [comment]
FWIW

There are also the following settings, that one may want to change in similar cases:
- `max_bytes_before_external_group_by`
- `max_bytes_before_external_sort`
- `max_bytes_before_remerge_sort`

And it looks like all of this can be archived by using separate user for distributed queries, by changing `user` in `remote_servers` configuration.
But this will not allow to manage this on fly (for example if one want to calculate `distributed_max_memory_usage` dynamically, but is this a real case?)

**Comment by chicofranchico** [comment]
@azat 

I have a use case where I want a specific user to perform distributed queries using some of these parameters without giving the *default* user these configs (which I currently have as the one connecting to the remote servers).

If I understood correctly, the remote query queries each replica using the `user` defined in remote_servers and not the `initial_user` from where it was initiated.

Is there a way to make those remote queries use the same user as the initial one?

**Comment by azat** [comment]
>Is there a way to make those remote queries use the same user as the initial one?

Yes. Take a look at inter-server secret, there is an example in the [doc](https://clickhouse.tech/docs/en/engines/table-engines/special/distributed/) or here is the snippet from the config https://github.com/ClickHouse/ClickHouse/blob/9282e0f5b72172e00065b5a0da0e1f940110712a/programs/server/config.xml#L593-L613

The reason it works this way by default, because there is no trust for remote nodes.
By configuring inter-server secret remote node may trust the initiator, and can use user that initiates the query.

**Comment by chicofranchico** [comment]
@azat thank you so much, I missed that snippet of information on the comment. 

So, I can issue my query as user `Alice` (`initial_user`) and my user `Bob` is defined as the inter-server user but user `Alice` will be performing the end query locally then?

**Comment by azat** [comment]
>So, I can issue my query as user Alice (initial_user) and my user Bob is defined as the inter-server user but user Alice will be performing the end query locally then?

Yep.

**Comment by alexey-milovidov** [comment]
An ad-hoc solution for this problem (introducing more settings) looks non-viable.
No better solution proposed.
