### ISSUE TITLE
OPTIMIZE with FINAL should wait for already running merges.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#11309]
Otherwise it can just exit quickly and be effectively no-op.
We cannot reliably write tests with this behaviour.

**Comment by alexey-milovidov** [comment]
We can simply assign the merge regardless to the already running merges.
This is perfectly legal when we are merging whole partition (so no intersecting parts were created).

**Comment by alexey-milovidov** [comment]
It's done for non-Replicated MergeTree but still to-do for ReplicatedMergeTree.

**Comment by Algunenano** [comment]
It’s done for RMT https://github.com/ClickHouse/ClickHouse/pull/62067
