### ISSUE TITLE
Aggregate merge tree table query

### ISSUE THREAD

**Issue by shubham721** [ClickHouse/ClickHouse#11328]
Hi Guyz,
I am running the following query on the returns_agg table which is an aggregating merge tree table populated by merge tree engine. The size of returns_agg table is around 3.4GB in a compressed format and 18 GB in uncompressed size.
I am getting the following exception
Code: 241. DB::Exception: Received from localhost:9000. DB::Exception: Memory limit (for query) exceeded: would use 55.88 GiB (attempt to allocate a chunk of 137983608 bytes), maximum: 55.88 GiB: While executing AggregatingTransform.

I have a few questions
1. It seems like It is trying to read the whole table in memory, Why isn't this query able to read based on filters which we specified above?
2. Is there a way we can directly apply this filter condition on the aggregating merge tree table? (Base: account id is a nonprimary key field, So when we get updates on this table we insert empty string instead of actual account id, So If we apply the filter directly on the aggregated table, It won't work)

select * from (
SELECT
return_ref_id,
return_id,
tenant_id,
max(account_id) AS max_account_id,
max(order_id) AS order_id,
max(order_item_unit_id) AS order_item_unit_id,
max(seller_id) AS seller_id,
max(product_id) AS product_id,
max(listing_id) AS listing_id,
max(return_amount) AS return_amount,
max(currency) AS currency,
max(product_category) AS product_category,
max(return_reason) AS return_reason,
max(return_channel) AS return_channel,
max(return_address) AS return_address,
max(return_address_pincode) AS return_address_pincode,
max(customer_history_based_score) AS customer_history_based_score,
max(linked_account_history_score) AS linked_account_history_score,
max(pincode_risk_score) AS pincode_risk_score,
max(seller_goodness_score) AS seller_goodness_score,
max(returns_flip_score) AS returns_flip_score,
max(account_creation_date) AS account_creation_date,
max(max_order_created_at) AS order_created_at,
max(return_date) AS return_date,
max(is_tainted) AS is_tainted,
max(rule_name) AS rule_name,
max(order_decision_action) AS order_decision_action,
max(order_decision_reasoncodes) AS order_decision_reasoncodes,
max(order_decision_tags) AS order_decision_tags,
max(user_decision_action) AS user_decision_action,
max(user_decision_reasoncodes) AS user_decision_reasoncodes,
max(user_decision_tags) AS user_decision_tags,
max(customer_rvp_quantity_90days) AS customer_rvp_quantity_90days,
max(customer_rvp_rate_90days) AS customer_rvp_rate_90days,
max(customer_missing_reason_rvp_quantity_90days) AS customer_missing_reason_rvp_quantity_90days,
max(customer_fraud_rvp_quantity_90days) AS customer_fraud_rvp_quantity_90days,
max(customer_rvp_quantity_30days) AS customer_rvp_quantity_30days,
max(customer_rvp_rate_30days) AS customer_rvp_rate_30days,
max(customer_missing_reason_rvp_quantity_30days) AS customer_missing_reason_rvp_quantity_30days,
max(customer_fraud_rvp_quantity_30days) AS customer_fraud_rvp_quantity_30days,
max(linked_account_rvp_rate_90days) AS linked_account_rvp_rate_90days,
max(linked_account_missing_reason_rvp_quantity_90days) AS linked_account_missing_reason_rvp_quantity_90days,
max(linked_account_fraud_quantity_90days) AS linked_account_fraud_quantity_90days,
max(linked_account_rvp_rate_30days) AS linked_account_rvp_rate_30days,
max(linked_account_missing_reason_rvp_quantity_30days) AS linked_account_missing_reason_rvp_quantity_30days,
max(linked_account_fraud_quantity_30days) AS linked_account_fraud_quantity_30days,
max(seller_rvp_rate_30days) AS seller_rvp_rate_30days,
max(seller_sale_quantity_90days) AS seller_sale_quantity_90days,
max(seller_rvp_rate_90days) AS seller_rvp_rate_90days,
max(seller_sale_quantity_30days) AS seller_sale_quantity_30days,
max(locality_missing_rvp_rate_90days) AS locality_missing_rvp_rate_90days,
max(locality_fraud_rate_90days) AS locality_fraud_rate_90days,
max(locality_rvp_rate_30days) AS locality_rvp_rate_30days,
max(locality_missing_rvp_rate_30days) AS locality_missing_rvp_rate_30days,
max(locality_fraud_rate_30days) AS locality_fraud_rate_30days,
max(agent_assigned) AS agent_assigned,
argMaxMerge(case_status) AS case_status,
max(agent_action) AS agent_action,
argMaxMerge(event_status) AS event_status
FROM returns_agg
GROUP BY (tenant_id, return_ref_id, return_id)
) where account_id='ACC14002975663275913'

**Comment by den-crane** [comment]
What CH version do you use?

**Comment by shubham721** [comment]
20.3.8.53

**Comment by den-crane** [comment]
try to use `having`

```
SELECT
return_ref_id,
return_id,
tenant_id,
max(account_id) AS max_account_id,
...
GROUP BY (tenant_id, return_ref_id, return_id)
having account_id='ACC14002975663275913'

```

try to execute the same query in single thread `set max_threads=1`

**Comment by shubham721** [comment]
Thanks @den-crane 
I have added account_id in the sorting key. Now, This OOM issue is not coming up but query is still taking around 500ms. 
I was just wondering that in the following documentation
https://clickhouse.tech/docs/en/engines/table-engines/mergetree-family/mergetree/#primary-keys-and-indexes-in-queries
when DateTime=3, Why It tries to read the data in marks of range [1,10]. Why it is not able to filter the data based on DateTime? Can you give some insight on algorithm to select granules in part?
