### ISSUE TITLE
merge tree aggregation query

### ISSUE THREAD

**Issue by shubham721** [ClickHouse/ClickHouse#11331]
Hi guyz, 
I am new to click house. I have a query regarding aggregating merge tree table results. Suppose I have a table like this

create table exp(
return_id String,
status String,
rto_count UInt32,
time DateTime('Asia/Kolkata')
)
Engine=MergeTree()
PARTITION BY tuple()
order by (return_id)

Three types of inserts

1. Normal 

INSERT INTO exp values('xyz', 'open', 2, 104546467)

2. Insertion of event again for same return_id

INSERT INTO exp values('xyz', 'open', 1, 104546468)

3. Update status of event for same return_id

INSERT INTO exp(return_id,status,time) values('xyz', 'resolved', 104546469)

In this scenario, I have inserted 3 rows for same primary key. But when I want to merge these results such that status comes always updated. So the result should be

return_id	status	rto_count	time
xyz		resolved	 1	           104546469

I have tried to use aggregated merge tree.. But I am not able to write query, Which will fetch this result. Can someone help?

**Comment by den-crane** [comment]
Examples:
https://gist.github.com/den-crane/49ce2ae3a688651b9c2dd85ee592cb15
https://gist.github.com/den-crane/d03524eadbbce0bafa528101afa8f794
https://gist.github.com/den-crane/6eff375752a236a456e1b3dc2ca7db62

**Comment by shubham721** [comment]
Hi @den-crane 
Thanks for the reply.
I have checked queries which you have shared, But still, none of it satisfies the functionality I need. I would describe What I did 

create table exp(
return_id String,
status String,
rto_count UInt32,
time DateTime('Asia/Kolkata')
)
Engine=MergeTree()
PARTITION BY tuple()
order by (return_id)

create table exp_agg(
return_id String,
final_status AggregateFunction(argMax, String, DateTime('Asia/Kolkata')),
final_rto_count AggregateFunction(max, UInt32),
final_time AggregateFunction(max, DateTime('Asia/Kolkata'))
)
Engine = AggregatingMergeTree()
PARTITION BY tuple()
order by (return_id)

create materialized view exp_mv to exp_agg AS
SELECT
return_id,
argMaxState(status, time) as final_status,
maxState(rto_count) as final_rto_count,
maxState(time) as final_time
FROM exp
GROUP BY return_id

These are the tables, Raw tables is where I am doing the inserts. I have done the inserts in the following way

1. INSERT INTO exp values('xyz', 'open', 2, 104546467)
2. Suppose this event comes again with decreased rto_count But It is latest, so we want this as final
 INSERT INTO exp values('xyz', 'open', 1, 104546468)
3. Now the third type of event comes as update event, where we don't know rto_count. ONly we have return_id
INSERT INTO exp(return_id,status,time) values('xyz', 'resolved', 104546469)

So we do three inserts 
INSERT INTO exp values('xyz', 'open', 2, 104546467)
INSERT INTO exp values('xyz', 'open', 1, 104546468)
INSERT INTO exp(return_id,status,time) values('xyz', 'resolved', 104546469)

So, I have ran the following query to aggregate the results.
SELECT
return_id,
argMaxMerge(final_status) as status,
maxMerge(final_rto_count) as rto_count,
maxMerge(final_time) as time
FROM exp_agg
GROUP BY return_id

I got this result from this query

return_id | status | rto_count | time
xyz | resolved | 2 | 104546468

But the result should be

return_id | status | rto_count | time
-- | -- | -- | --
xyz | resolved | 1 | 104546468

Its happening Of I am using max on rto_count, If I use argMax then It will come zero in final result. what can be done here?

**Comment by den-crane** [comment]
You can get this , but probably AggregatingMergeTree is a bad idea for this task. You should use CollapsingMergeTree or ReplacingMergeTree and prepare data at ETL stage.

```
create table exp(
return_id String,
status String,
rto_count UInt32,
time DateTime('Asia/Kolkata')
)
Engine=MergeTree()
PARTITION BY tuple()
order by (return_id);

create table exp_agg(
return_id String,
final_status AggregateFunction(argMax, String, DateTime('Asia/Kolkata')),
final_rto_count AggregateFunction(argMax, UInt32, DateTime('Asia/Kolkata')),
final_time AggregateFunction(max, DateTime('Asia/Kolkata'))
)
Engine = AggregatingMergeTree()
PARTITION BY tuple()
order by (return_id);

create materialized view exp_mv to exp_agg AS
SELECT
return_id,
argMaxState(status, time) as final_status,
argMaxState(rto_count, if(rto_count=0,toDateTime(1000, 'Asia/Kolkata'),time)) as final_rto_count,
maxState(time) as final_time
FROM exp
GROUP BY return_id;

INSERT INTO exp values('xyz', 'open', 2, 104546467)
INSERT INTO exp values('xyz', 'open', 1, 104546468)
INSERT INTO exp(return_id,status,time) values('xyz', 'resolved', 104546469)

SELECT
return_id,
argMaxMerge(final_status) as status,
argMaxMerge(final_rto_count) as rto_count,
maxMerge(final_time) as time
FROM exp_agg
GROUP BY return_id;


┌─return_id─┬─status───┬─rto_count─┬────────────────time─┐
│ xyz       │ resolved │         1 │ 1973-04-25 06:11:09 │
└───────────┴──────────┴───────────┴─────────────────────┘
```

**Comment by shubham721** [comment]
Thanks @den-crane 
With replacingmergetree and collapsingmergetree, problem I am facing for update queries. In update queries, we don't have data for all the columns. Only the primary keys with updated columns are present. These tree structures replace the row completely so we would need to have complete data in the updated row. For that, we would need to fetch the data first from click house and then insert.
Am I right, Is there any other alternative to this?

**Comment by den-crane** [comment]
>In your query, you have use argmax based on rto_count = 0,

You  can use some fake default Null or 65536 (rto_count UInt32 default 65536)
But I agree that it's an ugly solution. A much better way is Replacingmergetree.

>With replacingmergetree and collapsingmergetree, problem 
>I am facing for update queries. In update queries, we don't have data for all the columns. 

Usually users store them in ETL (mysql/cassandra/redis).
