### ISSUE TITLE
optimize_trivial_count_query ignores row-level security

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#11352]
```
select count(*) from table1
```

returns all rows of the table despite the fact that the table has row-level security enabled. 

Setting `optimize_trivial_count_query=0` resolves the issue.

Related: https://github.com/ClickHouse/ClickHouse/pull/7510

**Comment by alexey-milovidov** [comment]
@vitlibar It's a simple task - just disable optimization if row-level security present.
