### ISSUE TITLE
Bad cast from type DB::ColumnConst to DB::ColumnVector<char8_t>

### ISSUE THREAD

**Issue by akuzm** [ClickHouse/ClickHouse#11360]
```
ATTACH TABLE constrained
(
    `URL` String, 
    CONSTRAINT is_yandex CHECK domainWithoutWWW(URL) = domainWithoutWWW(URL), 
    CONSTRAINT is_utf8 CHECK isValidUTF8(URL)
)
ENGINE = TinyLog;

insert into constrained values ('a');

Code: 368. DB::Exception: Received from localhost:9000. DB::Exception: Bad cast from type DB::ColumnConst to DB::ColumnVector<char8_t>. Stack trace
```

**Comment by alexey-milovidov** [comment]
You forgot to attach the stack trace.

**Comment by akuzm** [comment]
> You forgot to attach the stack trace.

I always skip them for easily reproducible issues (i.e. just copy+paste to clickhouse-client) to reduce visual clutter. Do you find it more convenient to always have the trace? Maybe I should start attaching them even in simple cases.

**Comment by alexey-milovidov** [comment]
It does not reproduce in release build (that I use on my workstation). But it's easy, I already have the fix.
