### ISSUE TITLE
DB::geohashesInBox(): Assertion `items <= args.items_count'

### ISSUE THREAD

**Issue by akuzm** [ClickHouse/ClickHouse#11369]
```
SELECT arraySort(geohashesInBox(-1., -1., 1., inf, 3))
```

**Comment by akuzm** [comment]
@Enmk FYI

**Comment by Enmk** [comment]
> @Enmk FYI

could you please add a link to the test run ?

**Comment by akuzm** [comment]
> > @Enmk FYI
> 
> could you please add a link to the test run ?

It's not a test run, I just found it locally with some experimental fuzzer I'm making. The query from the description should reproduce the problem.
