### ISSUE TITLE
LimitTransform::makeChunkWithPreviousRow(): Assertion `row < chunk.getNumRows()' failed.

### ISSUE THREAD

**Issue by akuzm** [ClickHouse/ClickHouse#11372]
```
SELECT number FROM numbers(100) ORDER BY number ASC LIMIT 2, 9223372036854775807  WITH TIES
```

@KochetovNicolai The query is similar to https://github.com/ClickHouse/ClickHouse/issues/11359, but the error is different.

**Comment by KochetovNicolai** [comment]
This case is integer overflow, because `SELECT number FROM numbers(100) ORDER BY number ASC LIMIT 2, 100000000  WITH TIES` works fine.
Don't know how to fix it properly.

**Comment by akuzm** [comment]
> This case is integer overflow, because `SELECT number FROM numbers(100) ORDER BY number ASC LIMIT 2, 100000000 WITH TIES` works fine.
> Don't know how to fix it properly.

Is there some place where signed int is used for row number? Maybe if we convert it all to UInt64, it will work? And if we have some other kind of literal for LIMIT, we should report an error (we probably do so already).

**Comment by KochetovNicolai** [comment]
> Is there some place where signed int is used for row number?

Yes. It is not so easy for fix.
https://github.com/ClickHouse/ClickHouse/blob/06446b4f08a142d6f1bc30664c47ded88ab51782/src/Processors/LimitTransform.cpp#L283-L286

**Comment by akuzm** [comment]
> > Is there some place where signed int is used for row number?
> 
> Yes. It is not so easy for fix.
> https://github.com/ClickHouse/ClickHouse/blob/06446b4f08a142d6f1bc30664c47ded88ab51782/src/Processors/LimitTransform.cpp#L283-L286

It should be possible to calculate absolute row numbers for chunk start and chunk end, and then compare these numbers to offset and limit. They all fit UInt64, so it must work. It also will be easier to read -- now I'm not even sure the calculations are correct (they must be correct, but it's not immediately clear from the code). In cases like these, when there is a lot of conditions, it can be helpful to make a decision table and then just write it down as code: https://www.hillelwayne.com/post/decision-tables/
It's easy to miss something when the conditions are not explicit and embedded into a chain of min's.

**Comment by alexey-milovidov** [comment]
@KochetovNicolai Signed integer overflow will be also reported by UBSan. We should fix it.

**Comment by alexey-milovidov** [comment]
Duplicate of #10470
