### ISSUE TITLE
Code: 40, e.displayText() = DB::Exception: Checksum doesn't match: corrupted data. Reference: 8a58086e26544cb09217aa1bba09a1d9. Actual: 7c7a5cd56cac83a714e286dbbd46acb5.

### ISSUE THREAD

**Issue by shizihao123** [ClickHouse/ClickHouse#11398]
(you don't have to strictly follow this form)

**Describe the unexpected behaviour**
when I complie a new client with the same code，it just returns  Code 40, DB::Exception: Checksum doesn't match: corrupted data.  But The Server side && Client side doesn't change
anything. The error stack from the server side is as  following:
![image](https://user-images.githubusercontent.com/15273058/83602894-feb9d580-a5a5-11ea-936e-f263fbc86d3a.png)

**How to reproduce**
just use client to visit server
* Which ClickHouse server version to use
ClickHouse server version 19.14.7 revision 54425
* Which interface to use, if matters
ClickHouse client version 19.14.7.15
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

**Expected behavior**
Should have no error.

**Error message and/or stacktrace**
![image](https://user-images.githubusercontent.com/15273058/83602894-feb9d580-a5a5-11ea-936e-f263fbc86d3a.png)

**Additional context**

**Comment by den-crane** [comment]
What API do you use cpp / go ?

**Comment by den-crane** [comment]
No info. Closing.

**Comment by haiya512** [comment]
same problem, clickhouse 22.9.6.20

> rMsg=规则执行完成,规则执行完成,规则执行完成,规则执行完成,规则执行完成,rule exec exception : com.github.housepower.exception.ClickHouseSQLException: DB::ExceptionDB::Exception: Checksum doesn't match: corrupted data. Reference: ff713b50b2ba22f171a2212cac5a4c8b. Actual: 5586abbb71ea5cabb7538ee01547c9a7. Size of compressed block: 19. Stack trace:

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x78d90fa in /usr/bin/clickhouse
1. ? @ 0x113a6a3e in /usr/bin/clickhouse
2. DB::CompressedReadBufferBase::readCompressedData(unsigned long&, unsigned long&, bool) @ 0x113a5a56 in /usr/bin/clickhouse
3. DB::CompressedReadBuffer::readBig(char*, unsigned long) @ 0x113a52c4 in /usr/bin/clickhouse
4. DB::SerializationNumber<unsigned int>::deserializeBinaryBulk(DB::IColumn&, DB::ReadBuffer&, unsigned long, double) const @ 0x770e1d7 in /usr/bin/clickhouse
5. DB::ISerialization::deserializeBinaryBulkWithMultipleStreams(COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, DB::ISer, dataLevel=WAFER, isFirstWafer=true), 开始更新wafer 状态
2025-08-22 00:10:30.681 [] [Rule-redis-consumer-7] INFO  c.g.o.r.c.s.b.BatchHandlerService[267] - 当前wafer:A547617_03, 阶段 :RUN， 状态:FAIL， error msg:规则执行完成,规则执行完成,规则执行完成,规则执行完成,规则执行完成,rule exec exception : com.github.housepower.exception.ClickHouseSQLException: DB::ExceptionDB::Exception: Checksum doesn't match: corrupted data. Reference: ff713b50b2ba22f171a2212cac5a4c8b. Actual: 5586abbb71ea5cabb7538ee01547c9a7. Size of compressed block: 19. Stack trace:

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x78d90fa in /usr/bin/clickhouse

**Comment by haiya512** [comment]
> same problem, clickhouse 22.9.6.20
> 
> > rMsg=规则执行完成,规则执行完成,规则执行完成,规则执行完成,规则执行完成,rule exec exception : com.github.housepower.exception.ClickHouseSQLException: DB::ExceptionDB::Exception: Checksum doesn't match: corrupted data. Reference: ff713b50b2ba22f171a2212cac5a4c8b. Actual: 5586abbb71ea5cabb7538ee01547c9a7. Size of compressed block: 19. Stack trace:
> 
> 0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&, int, bool) @ 0x78d90fa in /usr/bin/clickhouse
> 1. ? @ 0x113a6a3e in /usr/bin/clickhouse
> 2. DB::CompressedReadBufferBase::readCompressedData(unsigned long&, unsigned long&, bool) @ 0x113a5a56 in /usr/bin/clickhouse
> 3. DB::CompressedReadBuffer::readBig(char*, unsigned long) @ 0x113a52c4 in /usr/bin/clickhouse
> 4. DB::SerializationNumber::deserializeBinaryBulk(DB::IColumn&, DB::ReadBuffer&, unsigned long, double) const @ 0x770e1d7 in /usr/bin/clickhouse
> 5. DB::ISerialization::deserializeBinaryBulkWithMultipleStreams(COWDB::IColumn::immutable_ptrDB::IColumn&, unsigned long, DB::ISer, dataLevel=WAFER, isFirstWafer=true), 开始更新wafer 状态
>    2025-08-22 00:10:30.681 [] [Rule-redis-consumer-7] INFO  c.g.o.r.c.s.b.BatchHandlerService[267] - 当前wafer:A547617_03, 阶段 :RUN， 状态:FAIL， error msg:规则执行完成,规则执行完成,规则执行完成,规则执行完成,规则执行完成,rule exec exception : com.github.housepower.exception.ClickHouseSQLException: DB::ExceptionDB::Exception: Checksum doesn't match: corrupted data. Reference: ff713b50b2ba22f171a2212cac5a4c8b. Actual: 5586abbb71ea5cabb7538ee01547c9a7. Size of compressed block: 19. Stack trace:
> 6. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&, int, bool) @ 0x78d90fa in /usr/bin/clickhouse

openjdk 1.8.262
