### ISSUE TITLE
Does CK support sharding_key policy that write to all shards?

### ISSUE THREAD

**Issue by AlexanderChiuluvB** [ClickHouse/ClickHouse#11396]
Hey guys, I'm new to CK. So now I want to build a distributed table with a sharding_key policy that when I write data to the distributed table, the data will be sent to all shards. 

I know CK now only supports rand() or built-in hash functions or UserID. Btw, does it mean that each time the data will only be sent to one shard?

**Comment by den-crane** [comment]
Do you need data distributed among all nodes or duplicated to all nodes?

For example you have 2 servers and inserted 10 rows. Do you need 5 rows at one firsts and another 5 at the second? Or do you need data duplicated? Both node have all 10 rows?

**Comment by AlexanderChiuluvB** [comment]
> Do you need data distributed among all nodes or duplicated to all nodes?
> For example you have 2 servers and inserted 10 rows. Do you need 5 rows at the first node and another 5 at the second node? Or do you need data duplicated? Both nodes have all 10 rows?

Both nodes have all 10 rows

**Comment by AlexanderChiuluvB** [comment]
> Do you need data distributed among all nodes or duplicated to all nodes?
> For example you have 2 servers and inserted 10 rows. Do you need 5 rows at the first node and another 5 at the second node? Or do you need data duplicated? Both nodes have all 10 rows?
> 
> Both nodes have all 10 rows

Actually I want to implement dimenstion table in CK. Suppose I have many servers, and I want to create a local small dimension table in each servers. So my idea is that I can create a distributed table, and then when I want to write data to the dimenstion table, the data will be sent to all the local dimenstion table in each servers. The problem is how do I define the sharding_key policy?

**Comment by YiuRULE** [comment]
If you want to set the same record on all of your server, why not just set a replicated table on each of your server ?

**Comment by AlexanderChiuluvB** [comment]
> If you want to set the same record on all of your server, why not just set a replicated table on each of your server ?

Because replica table can only be replicated between replicas of the same shard, but can not be replicated between diffetent shards. 

I want that the small dimension table can be replicated between all the shards nodes, then I have a super big fact table(it's sharded) want to join the dimension table.So all the shards of the big fact table can join the complete small dimension table on each shard node.

**Comment by den-crane** [comment]
@AlexanderChiuluvB Do you use Replicated Engine or plain MergeTree ?

**Comment by AlexanderChiuluvB** [comment]
> @AlexanderChiuluvB Do you use Replicated Engine or plain MergeTree ?
> If you don't use Replicated you need to describe one more cluster with with one shard many replicas.
> If you use Replicated table then just omit {shard} macros in ZK table path and don't use Distributed table.

alright thanks~
