### ISSUE TITLE
How to deal with (insert into xxx select xxx from xxx where xxx) is too slow

### ISSUE THREAD

**Issue by gubinjie** [ClickHouse/ClickHouse#11409]
We found that with the long-term use of CH, it felt slower and slower when executing (insert into xxx select xxx from xxx where xxx).

Our tables are using the mergeTree engine, we are not sure whether it is when selecting or inserting, which takes longer.

Our table has partitions according to the day, but in reality, the table only has data for the current day, and no historical data.

So, are there any good suggestions to optimize and reduce the execution time?

**Comment by den-crane** [comment]
Do you mean you have constant number of rows and xxx does not grow with time?

**Comment by gubinjie** [comment]
@den-crane The total amount of data in the table has basically not changed much

**Comment by den-crane** [comment]
Can you provide the table DDL and the output of the query debug `SET send_logs_level = 'debug'`

**Comment by den-crane** [comment]
Unclear how to reproduce the issue. It's needed clarification.

**Comment by gubinjie** [comment]
@den-crane 
Very sorry, did not see your reply.
Because this process is also a long-term process, it feels slower in long-term use, and there is no specific performance in the log.
You can pay attention to it for a long time, because we use quartz to run the same script every day, and the calculated time is different.
We also have a look, maybe you have any better suggestions. Thank you

**Comment by den-crane** [comment]
No idea. It could be anything. Maybe number of partitions -> parts grow over time.
