### ISSUE TITLE
Question with row policies 

### ISSUE THREAD

**Issue by davidpsv17** [ClickHouse/ClickHouse#11400]
Using 20.4.2.9

I have a table in clickhouse and I want that some users can only access to certain rows.
For that, I've created a row policy:
 
CREATE ROW POLICY user1_filter ON default.table1 FOR SELECT USING account_id = 120 TO user1

After the creation of that policy the user1 only can see the rows with account_id 120, that's correct.
The problem is that the other users when try to do a query on table1, they don't see any column.

How can I solve that? I have to add a row policy for each user that want to query this table?

Thanks!

**Comment by vitlibar** [comment]
The following should work:

```
CREATE ROW POLICY filter1 ON default.table1 FOR SELECT USING account_id = 120 TO ALL
```

or 

```
CREATE ROW POLICY filter1 ON default.table1 FOR SELECT USING account_id = 120 TO ALL EXCEPT admin;
CREATE ROW POLICY filter2 ON default.table1 FOR SELECT USING 1 TO admin;
```

i.e. setup row policies for each of who should have access.
