### ISSUE TITLE
Replication direction

### ISSUE THREAD

**Issue by asurovenko** [ClickHouse/ClickHouse#11412]
Hello,

I have cluster with 2 machines, each have follow config.xml:
```
 <remote_servers incl="clickhouse_remote_servers" >
        <shard_prod>
            <shard>
               <internal_replication>false</internal_replication>
               <replica>
                    <host>clickhouse-00</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>clickhouse-01</host>
                    <port>9000</port>
                </replica>
            </shard>
        </shard_prod>
    </remote_servers>
```
And all was great, all data replicated from 00 to 01 clickhouse.
There was an incident. And from that config clickhouse-01 was removed. After some time that changes was reverted. Right now replication going on from 01 to 00 only. The direction for replication is changed. Why? How I can change it again?

**Comment by den-crane** [comment]
```
<internal_replication>false</internal_replication>
               <replica>
                    <host>clickhouse-00</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>clickhouse-01</host>
                    <port>9000</port>
                </replica>
```

This config means that Distributed table will insert into both nodes clickhouse-00, clickhouse-01 the same data (it's not replication like Replicated Engines it's insert MULTIPLICATION). 
Please check that this config is the same at both nodes. Check errors in clickhouse.log and check Distributed table folder size and content /var/lib/clickhouse/data/{db}/{distributed_table_name}/

**Comment by asurovenko** [comment]
Yes, configuration the same in both nodes. Both table schemas the same. And it's engine = ReplicatedMergeTree('/clickhouse/tables/{shard}/db/table_repl', '{replica}') PARTITION BY date ORDER BY date SETTINGS index_granularity = 8192;
What's right configuration? Is there any solution to continue populated tables in 01 from 00? Because I hasn't ability to change table engline right now in my production.

**Comment by den-crane** [comment]
>ReplicatedMergeTree

Check `select * from system.replication_queue ` at both servers. Seems one server could not connect to another. They (ReplicatedMergeTree) use `uname -f` hostnames and announce each other using zookeeper. 
ReplicatedMergeTree does't use `remote_servers`.


BTW it must be true `<internal_replication>true</internal_replication>` but it's not related the issue.

**Comment by asurovenko** [comment]
One of my node has empty replication_queue, second one has a lot of follow errors:
```
Code: 86, e.displayText() = DB::Exception: Received error from remote server ?endpoint=DataPartsExchange%3A%2Fclickhouse%2Ftables%2Fprod%2Fevents_dev%2Fconsent_aggregate%2Freplicas%2Fclickhouse-200&part=1591092000_1_1_0&client_protocol_version=2&compress=false. HTTP status code: 500 Internal Server Error, body: Code: 480, e.displayText() = DB::Exception: Unsupported fetch protocol version, Stack trace (when copying this message, always include the lines below):

0. 0xbc3212c Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int)  in /usr/bin/clickhouse
1. 0x4f6cbc9 DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int)  in /usr/bin/clickhouse
2. 0x4bec9c8 ?  in /usr/bin/clickhouse
3. 0x5007409 DB::InterserverIOHTTPHandler::processQuery(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&, DB::InterserverIOHTTPHandler::Output&)  in /usr/bin/clickhouse
4. 0x5007d27 DB::InterserverIOHTTPHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&)  in /usr/bin/clickhouse
5. 0x9bb8f7c Poco::Net::HTTPServerConnection::run()  in /usr/bin/clickhouse
6. 0x9bb5a07 Poco::Net::TCPServerConnection::start()  in /usr/bin/clickhouse
7. 0x9bb5dfd Poco::Net::TCPServerDispatcher::run()  in /usr/bin/clickhouse
8. 0xbca488f Poco::PooledThread::run()  in /usr/bin/clickhouse
9. 0xbca1958 Poco::ThreadImpl::runnableEntry(void*)  in /usr/bin/clickhouse
10. 0xbca31f9 ?  in /usr/bin/clickhouse
11. 0x7dd5 start_thread  in /usr/lib64/libpthread-2.17.so
12. 0xfdead __clone  in /usr/lib64/libc-2.17.so
 (version 20.1.3.7 (official build)) (version 20.3.8.53 (official build))
```
I don't change the versions, all works well for such versions, any right now diff in the versions make my problem? Or the cause is another?

**Comment by asurovenko** [comment]
So, I updated my clickhouse-server version and replication started. Thanks.
