### ISSUE TITLE
Add SHOW CLUSTER(S) queries.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#11411]
SHOW CLUSTER name
SHOW CLUSTERS
SHOW CLUSTERS LIKE ...

**Comment by alexey-milovidov** [comment]
It can be simply translated to SELECT * FROM system.clusters WHERE ...

**Comment by filipecaixeta** [comment]
I want this one

**Comment by hexiaoting** [comment]
this issue can be closed. @alexey-milovidov
