### ISSUE TITLE
Ch read queue is empty

### ISSUE THREAD

**Issue by wujieaiyan** [ClickHouse/ClickHouse#11423]
The replica node is not in the active state. After checking, the value is empty when it is going to get the queue. It should be judged when it is added to the queue again res.data Empty or not

                ops.emplace_back(zkutil::makeCreateRequest(
                    replica_path + "/queue/queue-", res.data, zkutil::CreateMode::PersistentSequential));

**Comment by alexey-milovidov** [comment]
Sorry, I don't understand the question. Could you please provide more details?
