### ISSUE TITLE
Can't drop partition when update clickhouse-server

### ISSUE THREAD

**Issue by asurovenko** [ClickHouse/ClickHouse#11434]
Hello, I update my clickhouse server from 20.1 to 20.4.4
And my follow code was broken.
`ALTER TABLE my_table DROP PARTITION toDateTime('2020-06-04 08:00:00');`

`Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 78 (end of query) (line 2, col 53): . Expected one of: LIKE, GLOBAL NOT IN, IS, OR, QuestionMark, BETWEEN, NOT LIKE, AND, IN, NOT, token, NOT IN, GLOBAL IN (version 20.4.4.18 (official build))`

In my schema I have
`data DateTime,`
How I can drop all data for hour?

The table has engline **ReplicatedMergeTree** and **delete where** doesn't work.

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/10212

**Comment by den-crane** [comment]
CH does not `delete` only `alter table .. delete` https://clickhouse.tech/docs/en/sql-reference/statements/alter/#alter-mutations
