### ISSUE TITLE
Store data oldest than 1970

### ISSUE THREAD

**Issue by calebeaires** [ClickHouse/ClickHouse#11441]
I have searched on documention and foruns about oldest data. I have found that date is stored in two bytes as the number of days since 1970-01-01 (unsigned).

Have you plans to add new Date and DateTime types, to store dates before 1970 and after 2038?
Date32 = a signed Int32 of days before/after 1970-01-01, for easy conversion to/from Date (same integer value)

In many cases we want store age/born dates. 1970 is too early to store data about people. Store date less then 1970 will be a game change in favor of analyse people data.

**Comment by den-crane** [comment]
Work in progress https://github.com/ClickHouse/ClickHouse/pull/9404

Duplicate https://github.com/ClickHouse/ClickHouse/issues/7316
