### ISSUE TITLE
DELETE WHERE doesn't work by some reason in exeisting cluster

### ISSUE THREAD

**Issue by asurovenko** [ClickHouse/ClickHouse#11468]
Hello,
I have ReplicatedMergeTree table wich replicated into 2 nodes.
One on production where a lot of data present and one on my stg cluster where I just created test copy of the table.
I prepare 2 query:
`select count() from my_table where date < toDataTime('2020-06-05 08:00:00') - interval 3 month;`
and
`ALTER TABLE my_table  delete where date < toDataTime('2020-06-05 08:00:00') - interval 3 month;`
I expect that after second query first query must return zero value, at least other value. But the returned value stay the same.
I checked **system.mutations** table and looks like there is some proccess it there, **parts_to_do** follow to 0, and after some time **is_done** going to be 1. But as I already said the result still the same, all data untouched.
But on my stg cluster wich the same as production, the queries works as expect. But on my stg cluster I have small amount of data, it's the single diff.

**Comment by den-crane** [comment]
What CH version do you use?
Can you provide `show create table my_table`?
Do you have a sample data to reproduce such behavior?

**Comment by asurovenko** [comment]
I use  **20.1.3.7** version.
And query for creating table(some fields hidden):
`CREATE TABLE my_table (`date` DateTime, `value` String, `value2` LowCardinality(String), `value3` Int32) ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/dev/my_table', '{replica}') PARTITION BY date ORDER BY date SETTINGS index_granularity = 8192;`
I can't catch such behavior for my "test" tables in production cluster where I have the problem.
All I did: create the copy of "problem" table with different name, insert some test data with help of insert into query, execute the query alter table delete where and see that all work great, but existing tables with data can't show me such behavior.

**Comment by den-crane** [comment]
You need to upgrade to 20.1.12.86.
Probably you are experiencing https://github.com/ClickHouse/ClickHouse/issues/9019 https://github.com/ClickHouse/ClickHouse/issues/8982 and then you need to reload data / re-create the table because a primary key index is corrupted.

**Comment by asurovenko** [comment]
Is there any way to recreate the table if there is small amount of empty disk place? My table size is 900Gb and I have aboun 100Gb free space.

**Comment by den-crane** [comment]
>Is there any way to recreate the table
No

Have you upgrade CH ? Has it solve the issue?
