### ISSUE TITLE
(Mac OS X) ninja: build stopped: subcommand failed

### ISSUE THREAD

**Issue by LiemLin** [ClickHouse/ClickHouse#11461]
Make sure that `git diff` result is empty and you've just pulled fresh master. Try cleaning up cmake cache. Just in case, official build instructions are published here: https://clickhouse.yandex/docs/en/development/build/

**Operating system**
macos 10.15.5 

**Cmake version**
3.15.2

**Ninja version**
1.9.0

**Compiler name and version**
Apple clang version 11.0.3 (clang-1103.0.32.62)

**Full cmake and/or ninja output**
clickhouse tag version 20.4.4.18

[3940/3940] Linking CXX executable programs/clickhouse
FAILED: programs/clickhouse 
: && /usr/bin/clang++  -fdiagnostics-color=always -std=c++2a -fsized-deallocation  -gdwarf-aranges -msse4.1 -msse4.2 -mpopcnt   -Wall -Wno-unused-command-line-argument  -Wnon-virtual-dtor -fno-omit-frame-pointer -stdlib=libc++ -Wl,-U,_inside_main -Werror -mmacosx-version-min=10.15 -O2 -g -DNDEBUG -O3  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names -rdynamic -mmacosx-version-min=10.15 src/CMakeFiles/clickhouse_malloc.dir/Common/malloc.cpp.o programs/CMakeFiles/clickhouse.dir/main.cpp.o  -o programs/clickhouse  src/libclickhouse_new_delete.a src/libclickhouse_common_io.a src/Common/StringUtils/libstring_utils.a programs/server/libclickhouse-server-lib.a programs/client/libclickhouse-client-lib.a programs/local/libclickhouse-local-lib.a programs/benchmark/libclickhouse-benchmark-lib.a programs/copier/libclickhouse-copier-lib.a programs/extract-from-config/libclickhouse-extract-from-config-lib.a programs/compressor/libclickhouse-compressor-lib.a programs/format/libclickhouse-format-lib.a programs/obfuscator/libclickhouse-obfuscator-lib.a programs/server/libclickhouse-server-lib.a programs/client/libclickhouse-client-lib.a base/daemon/libdaemon.a base/loggers/libloggers.a src/Functions/libclickhouse_functions.a src/Dictionaries/libclickhouse_dictionaries.a contrib/consistent-hashing/libconsistent-hashing.a contrib/consistent-hashing-sumbur/libconsistent-hashing-sumbur.a contrib/libfarmhash/libfarmhash.a contrib/libmetrohash/libmetrohash.a contrib/murmurhash/libmurmurhash.a contrib/base64-cmake/libbase64.a contrib/h3-cmake/libh3.a contrib/simdjson-cmake/libsimdjson.a src/Functions/URL/libclickhouse_functions_url.a contrib/hyperscan/lib/libhs.a src/Functions/array/libclickhouse_functions_array.a src/Functions/GatherUtils/libclickhouse_functions_gatherutils.a src/AggregateFunctions/libclickhouse_aggregate_functions.a src/TableFunctions/libclickhouse_table_functions.a src/Storages/System/libclickhouse_storages_system.a src/libdbms.a src/Common/Config/libclickhouse_common_config.a src/Common/ZooKeeper/libclickhouse_common_zookeeper.a src/Parsers/libclickhouse_parsers.a contrib/libbtrie/libbtrie.a contrib/poco/MongoDB/libPocoMongoDB.a contrib/poco/Redis/libPocoRedis.a src/Dictionaries/Embedded/libclickhouse_dictionaries_embedded.a src/libclickhouse_common_io.a src/Common/StringUtils/libstring_utils.a base/common/libcommon.a contrib/replxx-cmake/libreplxx.a contrib/cctz-cmake/libcctz.a base/widechar_width/libwidechar_width.a contrib/ryu-cmake/libryu.a contrib/re2/libre2.a contrib/re2_st/libre2_st.a contrib/cityhash102/libcityhash.a contrib/boost-cmake/libboost_program_options_internal.a contrib/croaring/libroaring.a contrib/libcpuid/libcpuid.a contrib/poco/NetSSL_OpenSSL/libPocoNetSSL.a contrib/poco/Net/libPocoNet.a contrib/poco/Util/libPocoUtil.a contrib/poco/XML/libPocoXML.a contrib/poco/JSON/libPocoJSON.a contrib/poco/Crypto/libPocoCrypto.a contrib/poco/Foundation/libPocoFoundation.a contrib/brotli-cmake/libbrotli.a contrib/cppkafka-cmake/libcppkafka.a contrib/librdkafka-cmake/librdkafka.a contrib/openssl-cmake/libssl.a contrib/openssl-cmake/libcrypto.a contrib/libgsasl/liblibgsasl.a contrib/capnproto-cmake/libcapnpc.a contrib/capnproto-cmake/libcapnp.a contrib/capnproto-cmake/libkj.a contrib/arrow-cmake/libparquet_static.a contrib/arrow-cmake/libarrow_static.a contrib/double-conversion-cmake/libdouble-conversion.a contrib/boost-cmake/libboost_filesystem_internal.a contrib/boost-cmake/libboost_system_internal.a contrib/lz4-cmake/liblz4.a contrib/zstd-cmake/libzstd.a contrib/flatbuffers/libflatbuffers.a contrib/arrow-cmake/libthrift_static.a contrib/boost-cmake/libboost_regex_internal.a contrib/avro-cmake/libavrocpp.a contrib/boost-cmake/libboost_iostreams_internal.a contrib/zlib-ng/libzlib.a contrib/snappy/libsnappy.a contrib/protobuf/cmake/libprotobuf.a contrib/libcxx-cmake/libcxx.a contrib/libcxxabi-cmake/libcxxabi.a -nodefaultlibs  -lc -lm -lpthread -ldl && :
Undefined symbols for architecture x86_64:
  "_HIST_countFast_wksp", referenced from:
      _ZSTD_compressBlock_internal in libzstd.a(zstd_compress.c.o)
  "_HIST_count_simple", referenced from:
      _HUF_writeCTable in libzstd.a(huf_compress.c.o)
      _ZSTD_compressBlock_btopt in libzstd.a(zstd_opt.c.o)
      _ZSTD_compressBlock_btultra in libzstd.a(zstd_opt.c.o)
      _ZSTD_compressBlock_btultra2 in libzstd.a(zstd_opt.c.o)
      _ZSTD_initStats_ultra in libzstd.a(zstd_opt.c.o)
      _ZSTD_compressBlock_btopt_dictMatchState in libzstd.a(zstd_opt.c.o)
      _ZSTD_compressBlock_btultra_dictMatchState in libzstd.a(zstd_opt.c.o)
      ...
  "_HIST_count_wksp", referenced from:
      _FSE_compress_wksp in libzstd.a(fse_compress.c.o)
      _HUF_compress_internal in libzstd.a(huf_compress.c.o)
  "_ZSTD_DDict_dictContent", referenced from:
      _ZSTD_decompressMultiFrame in libzstd.a(zstd_decompress.c.o)
      _ZSTD_decompressBegin_usingDDict in libzstd.a(zstd_decompress.c.o)
      _ZSTD_decompressStream in libzstd.a(zstd_decompress.c.o)
  "_ZSTD_DDict_dictSize", referenced from:
      _ZSTD_decompressMultiFrame in libzstd.a(zstd_decompress.c.o)
      _ZSTD_decompressBegin_usingDDict in libzstd.a(zstd_decompress.c.o)
      _ZSTD_decompressStream in libzstd.a(zstd_decompress.c.o)
  "_ZSTD_buildCTable", referenced from:
      _ZSTD_compressBlock_internal in libzstd.a(zstd_compress.c.o)
  "_ZSTD_buildFSETable", referenced from:
      _ZSTD_loadDEntropy in libzstd.a(zstd_decompress.c.o)
  "_ZSTD_compressLiterals", referenced from:
      _ZSTD_compressBlock_internal in libzstd.a(zstd_compress.c.o)
  "_ZSTD_copyDDictParameters", referenced from:
      _ZSTD_decompressMultiFrame in libzstd.a(zstd_decompress.c.o)
      _ZSTD_decompressBegin_usingDDict in libzstd.a(zstd_decompress.c.o)
      _ZSTD_decompressStream in libzstd.a(zstd_decompress.c.o)
  "_ZSTD_createDDict_advanced", referenced from:
      _ZSTD_DCtx_loadDictionary_advanced in libzstd.a(zstd_decompress.c.o)
      _ZSTD_DCtx_loadDictionary_byReference in libzstd.a(zstd_decompress.c.o)
      _ZSTD_DCtx_loadDictionary in libzstd.a(zstd_decompress.c.o)
      _ZSTD_DCtx_refPrefix_advanced in libzstd.a(zstd_decompress.c.o)
      _ZSTD_DCtx_refPrefix in libzstd.a(zstd_decompress.c.o)
      _ZSTD_initDStream_usingDict in libzstd.a(zstd_decompress.c.o)
  "_ZSTD_decompressBlock_internal", referenced from:
      _ZSTD_decompressMultiFrame in libzstd.a(zstd_decompress.c.o)
      _ZSTD_decompressContinue in libzstd.a(zstd_decompress.c.o)
  "_ZSTD_encodeSequences", referenced from:
      _ZSTD_compressBlock_internal in libzstd.a(zstd_compress.c.o)
  "_ZSTD_freeDDict", referenced from:
      _ZSTD_freeDCtx in libzstd.a(zstd_decompress.c.o)
      _ZSTD_decompressDCtx in libzstd.a(zstd_decompress.c.o)
      _ZSTD_decompress in libzstd.a(zstd_decompress.c.o)
      _ZSTD_DCtx_loadDictionary_advanced in libzstd.a(zstd_decompress.c.o)
      _ZSTD_DCtx_loadDictionary_byReference in libzstd.a(zstd_decompress.c.o)
      _ZSTD_DCtx_loadDictionary in libzstd.a(zstd_decompress.c.o)
      _ZSTD_DCtx_refPrefix_advanced in libzstd.a(zstd_decompress.c.o)
      ...
  "_ZSTD_getcBlockSize", referenced from:
      _ZSTD_findFrameSizeInfo in libzstd.a(zstd_decompress.c.o)
      _ZSTD_decompressMultiFrame in libzstd.a(zstd_decompress.c.o)
      _ZSTD_decompressContinue in libzstd.a(zstd_decompress.c.o)
  "_ZSTD_selectEncodingType", referenced from:
      _ZSTD_compressBlock_internal in libzstd.a(zstd_compress.c.o)
  "_ZSTD_sizeof_DDict", referenced from:
      _ZSTD_sizeof_DCtx in libzstd.a(zstd_decompress.c.o)
      _ZSTD_sizeof_DStream in libzstd.a(zstd_decompress.c.o)
  "_rd_fnv1a", referenced from:
      _rd_kafka_msg_partitioner_fnv1a in librdkafka.a(rdkafka_msg.c.o)
      _rd_kafka_msg_partitioner_fnv1a_random in librdkafka.a(rdkafka_msg.c.o)
  "_rd_kafka_coord_cache_destroy", referenced from:
      _rd_kafka_destroy_internal in librdkafka.a(rdkafka.c.o)
  "_rd_kafka_coord_cache_expire", referenced from:
      _rd_kafka_1s_tmr_cb in librdkafka.a(rdkafka.c.o)
  "_rd_kafka_coord_cache_init", referenced from:
      _rd_kafka_new in librdkafka.a(rdkafka.c.o)
  "_rd_kafka_coord_reqs_init", referenced from:
      _rd_kafka_new in librdkafka.a(rdkafka.c.o)
  "_rd_kafka_coord_rkb_monitor_cb", referenced from:
      _rd_kafka_broker_add in librdkafka.a(rdkafka_broker.c.o)
  "_rd_kafka_error_destroy", referenced from:
      _rd_kafka_op_destroy in librdkafka.a(rdkafka_op.c.o)
  "_rd_kafka_error_new", referenced from:
      _rd_kafka_consumer_group_metadata_read in librdkafka.a(rdkafka_cgrp.c.o)
  "_rd_kafka_error_string", referenced from:
      _unittest_cgrp in librdkafka.a(rdkafka_cgrp.c.o)
  "_rd_kafka_mock_cgrp_check_state", referenced from:
      _rd_kafka_mock_handle_OffsetCommit in librdkafka.a(rdkafka_mock_handlers.c.o)
      _rd_kafka_mock_handle_Heartbeat in librdkafka.a(rdkafka_mock_handlers.c.o)
      _rd_kafka_mock_handle_LeaveGroup in librdkafka.a(rdkafka_mock_handlers.c.o)
      _rd_kafka_mock_handle_SyncGroup in librdkafka.a(rdkafka_mock_handlers.c.o)
  "_rd_kafka_mock_cgrp_destroy", referenced from:
      _rd_kafka_mock_cluster_destroy in librdkafka.a(rdkafka_mock.c.o)
  "_rd_kafka_mock_cgrp_find", referenced from:
      _rd_kafka_mock_handle_OffsetCommit in librdkafka.a(rdkafka_mock_handlers.c.o)
      _rd_kafka_mock_handle_Heartbeat in librdkafka.a(rdkafka_mock_handlers.c.o)
      _rd_kafka_mock_handle_LeaveGroup in librdkafka.a(rdkafka_mock_handlers.c.o)
      _rd_kafka_mock_handle_SyncGroup in librdkafka.a(rdkafka_mock_handlers.c.o)
  "_rd_kafka_mock_cgrp_get", referenced from:
      _rd_kafka_mock_handle_JoinGroup in librdkafka.a(rdkafka_mock_handlers.c.o)
  "_rd_kafka_mock_cgrp_member_active", referenced from:
      _rd_kafka_mock_handle_Heartbeat in librdkafka.a(rdkafka_mock_handlers.c.o)
      _rd_kafka_mock_handle_SyncGroup in librdkafka.a(rdkafka_mock_handlers.c.o)
  "_rd_kafka_mock_cgrp_member_add", referenced from:
      _rd_kafka_mock_handle_JoinGroup in librdkafka.a(rdkafka_mock_handlers.c.o)
  "_rd_kafka_mock_cgrp_member_assignment_set", referenced from:
      _rd_kafka_mock_handle_SyncGroup in librdkafka.a(rdkafka_mock_handlers.c.o)
  "_rd_kafka_mock_cgrp_member_find", referenced from:
      _rd_kafka_mock_handle_OffsetCommit in librdkafka.a(rdkafka_mock_handlers.c.o)
      _rd_kafka_mock_handle_Heartbeat in librdkafka.a(rdkafka_mock_handlers.c.o)
      _rd_kafka_mock_handle_LeaveGroup in librdkafka.a(rdkafka_mock_handlers.c.o)
      _rd_kafka_mock_handle_SyncGroup in librdkafka.a(rdkafka_mock_handlers.c.o)
  "_rd_kafka_mock_cgrp_member_leave", referenced from:
      _rd_kafka_mock_handle_LeaveGroup in librdkafka.a(rdkafka_mock_handlers.c.o)
  "_rd_kafka_mock_cgrp_member_sync_set", referenced from:
      _rd_kafka_mock_handle_SyncGroup in librdkafka.a(rdkafka_mock_handlers.c.o)
  "_rd_kafka_mock_cgrp_protos_destroy", referenced from:
      _rd_kafka_mock_handle_JoinGroup in librdkafka.a(rdkafka_mock_handlers.c.o)
  "_rd_kafka_mock_cgrps_connection_closed", referenced from:
      _rd_kafka_mock_connection_close in librdkafka.a(rdkafka_mock.c.o)
  "_rd_kafka_txn_coord_query", referenced from:
      _rd_kafka_idemp_pid_fsm in librdkafka.a(rdkafka_idempotence.c.o)
  "_rd_kafka_txn_coord_set", referenced from:
      _rd_kafka_idemp_request_pid_failed in librdkafka.a(rdkafka_idempotence.c.o)
  "_rd_kafka_txn_idemp_state_change", referenced from:
      _rd_kafka_idemp_set_state in librdkafka.a(rdkafka_idempotence.c.o)
  "_rd_kafka_txn_schedule_register_partitions", referenced from:
      _rd_kafka_txn_add_partition in librdkafka.a(rdkafka_msg.c.o)
  "_rd_kafka_txn_set_abortable_error", referenced from:
      _rd_kafka_msgbatch_handle_Produce_result in librdkafka.a(rdkafka_request.c.o)
  "_rd_kafka_txn_set_fatal_error", referenced from:
      _rd_kafka_msgbatch_handle_Produce_result in librdkafka.a(rdkafka_request.c.o)
      _rd_kafka_idemp_check_error in librdkafka.a(rdkafka_idempotence.c.o)
      _rd_kafka_idemp_pid_fsm in librdkafka.a(rdkafka_idempotence.c.o)
      _rd_kafka_idemp_request_pid_failed in librdkafka.a(rdkafka_idempotence.c.o)
  "_rd_kafka_txns_init", referenced from:
      _rd_kafka_idemp_init in librdkafka.a(rdkafka_idempotence.c.o)
  "_rd_kafka_txns_term", referenced from:
      _rd_kafka_idemp_term in librdkafka.a(rdkafka_idempotence.c.o)
  "_unittest_fnv1a", referenced from:
      l___const.rd_unittest.unittests in librdkafka.a(rdunittest.c.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

**Comment by LiemLin** [comment]
@proller Please take a look at it，thanks

**Comment by alexey-milovidov** [comment]
Need help from any developer with Mac OS.

**Comment by ortho** [comment]
I've tried to build ClickHouse using native apple clang compiler on two different source versions one is `v21.1.3.32-stable` and the other main branch (commit: `0db2aa3c2e8aa39eb814b8c8a22e904cb8528025`). The result is build success with some warnings. My environment is

**Operating system**

MacOS BigSur 11.2
```
$ sw_vers
ProductName:    macOS
ProductVersion: 11.2
BuildVersion:   20D64
```

**Cmake version**

3.19.4


**Compiler name and version**

Apple clang version 12.0.0
```
$ clang --version
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin20.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
a
```

**Ninja version**

1.10.2

**Bash commands to run build**
```
mkdir -p build
cd build
cmake ../ -DCMAKE_C_COMPILER=`which clang` -DCMAKE_CXX_COMPILER=`which clang++`
ninja
```

**Linker warnings** (commit: `0db2aa3c2e8aa39eb814b8c8a22e904cb8528025`)
```
[1911/1924] Linking CXX executable programs/clickhouse
ld: warning: direct access in function '_SSL_load_client_CA_file' from file 'contrib/boringssl-cmake/libssl.a(ssl_file.cc.o)' to global weak symbol '_sk_X509_NAME_call_free_func' from file 'contrib/grpc/libgrpc.a(ssl_transport_security.cc.o)' means the w
eak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'bssl::ssl_crypto_x509_hs_flush_cached_ca_names(bssl::SSL_HANDSHAKE*)' from file 'contrib/boringssl-cmake/libssl.a(ssl_x509.cc.o)' to global weak symbol '_sk_X509_NAME_call_free_func' from file 'contrib/grpc/libgrpc
.a(ssl_transport_security.cc.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'bssl::ssl_crypto_x509_ssl_config_free(bssl::SSL_CONFIG*)' from file 'contrib/boringssl-cmake/libssl.a(ssl_x509.cc.o)' to global weak symbol '_sk_X509_NAME_call_free_func' from file 'contrib/grpc/libgrpc.a(ssl_trans
port_security.cc.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'bssl::ssl_crypto_x509_ssl_flush_cached_client_CA(bssl::SSL_CONFIG*)' from file 'contrib/boringssl-cmake/libssl.a(ssl_x509.cc.o)' to global weak symbol '_sk_X509_NAME_call_free_func' from file 'contrib/grpc/libgrpc.
a(ssl_transport_security.cc.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'bssl::ssl_crypto_x509_ssl_ctx_free(ssl_ctx_st*)' from file 'contrib/boringssl-cmake/libssl.a(ssl_x509.cc.o)' to global weak symbol '_sk_X509_NAME_call_free_func' from file 'contrib/grpc/libgrpc.a(ssl_transport_secu
rity.cc.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'bssl::ssl_crypto_x509_ssl_ctx_flush_cached_client_CA(ssl_ctx_st*)' from file 'contrib/boringssl-cmake/libssl.a(ssl_x509.cc.o)' to global weak symbol '_sk_X509_NAME_call_free_func' from file 'contrib/grpc/libgrpc.a(
ssl_transport_security.cc.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function '_SSL_dup_CA_list' from file 'contrib/boringssl-cmake/libssl.a(ssl_x509.cc.o)' to global weak symbol '_sk_X509_NAME_call_free_func' from file 'contrib/grpc/libgrpc.a(ssl_transport_security.cc.o)' means the weak symb
ol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function '_SSL_set_client_CA_list' from file 'contrib/boringssl-cmake/libssl.a(ssl_x509.cc.o)' to global weak symbol '_sk_X509_NAME_call_free_func' from file 'contrib/grpc/libgrpc.a(ssl_transport_security.cc.o)' means the we
ak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function '_SSL_CTX_set_client_CA_list' from file 'contrib/boringssl-cmake/libssl.a(ssl_x509.cc.o)' to global weak symbol '_sk_X509_NAME_call_free_func' from file 'contrib/grpc/libgrpc.a(ssl_transport_security.cc.o)' means th
e weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function '_SSL_add_client_CA' from file 'contrib/boringssl-cmake/libssl.a(ssl_x509.cc.o)' to global weak symbol '_sk_X509_NAME_call_free_func' from file 'contrib/grpc/libgrpc.a(ssl_transport_security.cc.o)' means the weak sy
mbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function '_SSL_CTX_add_client_CA' from file 'contrib/boringssl-cmake/libssl.a(ssl_x509.cc.o)' to global weak symbol '_sk_X509_NAME_call_free_func' from file 'contrib/grpc/libgrpc.a(ssl_transport_security.cc.o)' means the wea
k symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
[1924/1924] Linking CXX executable src/Interpreters/tests/hash_map_lookup
```

**Comment by filimonov** [comment]
@ortho your issue looks completely different. Please open the new one.

**Comment by alexey-milovidov** [comment]
Duplicate #21904
