### ISSUE TITLE
>= 20.3.x: Select on a buffer table doesn't work with FINAL

### ISSUE THREAD

**Issue by adubovikov** [ClickHouse/ClickHouse#11476]
Since we have upgraded the system from 19.16.19 to 20.4.4.18( same on 20.3.8) a SELECT on the table (ENGINE = Buffer) that pointed to another table with ENGINE = ReplacingMergeTree , doesn't work with FINAL param:

Code: 171. DB::Exception: Received from 10.0.0.1:9000. DB::Exception: Received from 10.0.0.1:9000. DB::Exception: Block structure mismatch in
QueryPipeline stream: different names of columns:
Correlations Array(String) Array(size = 0, UInt64(size = 0), String(size = 0)), CustomString.Key Array(String) Array(size = 0, UInt64(size = 0),

if you don't use FINAL - we have result. Unfortunately we have rolled back to 19.16.19 - and now the query with FINAL works without any problem. Can you please check it ?

**Comment by adubovikov** [comment]
any updates on this ?

**Comment by alexey-milovidov** [comment]
Please provide a reproducing example.
