### ISSUE TITLE
DB::Exception: Received from localhost:9000. DB::Exception: Memory limit (total) exceeded

### ISSUE THREAD

**Issue by gbakthavatchalam** [ClickHouse/ClickHouse#11473]
(you don't have to strictly follow this form)

**Describe the situation**
I intended to load test the join capacity of Clickhouse MergeTree engine.
I have 2 tables (table1 and table2) with the below schema
No of cols -> 2250 (str cols - 1125, int cols - 1125)
No of rows -> 225000
Engine -> MergeTree

I perform an inner join between these 2 tables using an integer column
`select * from table1 inner join table2 using join_column`

I ran the setup in an EC2 instance with 16GB RAM and I got the below error.

![image](https://user-images.githubusercontent.com/26194642/83881367-2489da80-a75e-11ea-9ab8-deaa37b3dfc1.png)

When I ran the same setup in an EC2 instance with 32GB RAM, it again failed due to the below error.

![image](https://user-images.githubusercontent.com/26194642/83881391-2e134280-a75e-11ea-8aef-f4e2c52755d4.png)

**How to reproduce**
* Clickhouse Version 20.4.4.18
* clickhouse-client,
* Queries to run that lead to slow performance
clickhouse-client --max_memory_usage 0 -d 'default' -q 'SELECT * FROM table1 INNER JOIN table2 using join_column FORMAT CSVWithNames' > output.csv

**Expected performance**
When the join query failed in a 16G ram , I spun up a 32G RAM and I thought the query would run fine. But again the query failed due to memory limit error.

Is this an expected behaviour or is a memory leak issue ? Kindly suggest

**Comment by den-crane** [comment]
It's rather expected behavior.
`select *` is a mis-usage. Try to select only required columns.

try `set join_algorithm = 'auto', max_block_size=1000`

**Comment by gbakthavatchalam** [comment]
Hi @den-crane , No luck. 

I did try the above approaches but ended up with same error .

Apart from the above, I also set `max_memory_usage = 0` and `max_rows_in_join = 100000`

Memory limit (total) exceeded: would use 28.27 GiB (attempt to allocate chunk of 4208640 bytes), maximum: 28.27 GiB
--

**Comment by den-crane** [comment]
Probably it's just impossible to query 2250 columns with joining 1125 of them.

**Comment by gbakthavatchalam** [comment]
Oh I see okay. Yeah I am trying to query `2250 (table1) + 2250 (table2) = 4500` columns while joining `table1 and table2` using a `single` column
