### ISSUE TITLE
The query `SELECT *, xyz.*` is executing successfully but should not

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#11488]

**Comment by 4ertus2** [comment]
Should `select *` work as `select * from system.one` or we need disable both `select *` and `select xyz.*`?

**Comment by hexiaoting** [comment]
In which situation, will 
```
select xyz.*
```
sucessful? 

If xyz is a database name , it also should be failed, right？
I'm new to clickhouse, and I want to try to fix this.

**Comment by 4ertus2** [comment]
If `xyz` is a correct table name it should return columns from it. And it should return an error otherwise.

**Comment by hexiaoting** [comment]
Does the feature of select xyz.*  already implemented? 
Why I try below command failed?
Need I implement this feature first?
```
dell124 :) show tables;

SHOW TABLES

┌─name──────┐
│ hits_v1   │
│ visits_v1 │
└───────────┘

2 rows in set. Elapsed: 0.003 sec.

dell124 :) select hits_v1.*

SELECT hits_v1.*

Received exception from server (version 20.5.1):
Code: 47. DB::Exception: Received from localhost:9000. DB::Exception: Unknown qualified identifier: hits_v1.

0 rows in set. Elapsed: 0.002 sec.

dell124 :)

```

**Comment by 4ertus2** [comment]
There's not special feature here. The table should be present in query itself or via an alias. In this issue we need just a fail on second `xyz.*`.
