### ISSUE TITLE
DB::NetException: Timeout: connect timed out

### ISSUE THREAD

**Issue by zhbdesign** [ClickHouse/ClickHouse#11505]
When inserting data, the connection timeout occurs. When connecting to the replica machine, the connection timeout occurs.log:

2020.06.08 16:19:21.184975 [ 170 ] {d04037f8-0107-464f-b86d-983eb3aa40b7} <Error> HTTPHandler: Code: 209, e.displayText() = DB::NetException: Timeout: connect timed out: ***.**.**.**:9002 (hadoop-master2:9002), Stack trace:

0. 0x3503c40 StackTrace::StackTrace() /usr/bin/clickhouse
1. 0x350de6f DB::Exception::Exception(std::string const&, int) /usr/bin/clickhouse
2. 0x337bf3c ? /usr/bin/clickhouse
3. 0x652789d DB::Connection::getServerRevision(DB::ConnectionTimeouts const&) /usr/bin/clickhouse
4. 0x653532e DB::MultiplexedConnections::sendQuery(DB::ConnectionTimeouts const&, std::string const&, std::string const&, unsigned long, DB::ClientInfo const*, bool) /usr/bin/clickhouse
5. 0x6051487 DB::RemoteBlockInputStream::sendQuery() /usr/bin/clickhouse
6. 0x6059640 DB::copyData(DB::IBlockInputStream&, DB::IBlockOutputStream&, std::atomic<bool>*) /usr/bin/clickhouse
7. 0x63d8a66 DB::StorageReplicatedMergeTree::sendRequestToLeaderReplica(std::shared_ptr<DB::IAST> const&, DB::Context const&) /usr/bin/clickhouse
8. 0x63d94d8 DB::StorageReplicatedMergeTree::optimize(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::IAST> const&, bool, bool, DB::Context const&) /usr/bin/clickhouse
9. 0x6173990 DB::InterpreterOptimizeQuery::execute() /usr/bin/clickhouse
10. 0x6297579 ? /usr/bin/clickhouse
11. 0x6299daa DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, DB::Context&, std::function<void (std::string const&)>, std::function<void (std::string const&)>) /usr/bin/clickhouse
12. 0x358f7b1 DB::HTTPHandler::processQuery(Poco::Net::HTTPServerRequest&, HTMLForm&, Poco::Net::HTTPServerResponse&, DB::HTTPHandler::Output&) /usr/bin/clickhouse
13. 0x35927f1 DB::HTTPHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&) /usr/bin/clickhouse
14. 0x6d6b449 Poco::Net::HTTPServerConnection::run() /usr/bin/clickhouse
15. 0x6d680af Poco::Net::TCPServerConnection::start() /usr/bin/clickhouse
16. 0x6d687a5 Poco::Net::TCPServerDispatcher::run() /usr/bin/clickhouse
17. 0x71edc41 Poco::PooledThread::run() /usr/bin/clickhouse
18. 0x71e99c8 Poco::ThreadImpl::runnableEntry(void*) /usr/bin/clickhouse
19. 0x78c857f ? /usr/bin/clickhouse
20. 0x7fe19d079e65 start_thread /usr/lib64/libpthread-2.17.so
21. 0x7fe19cb9e88d clone /usr/lib64/libc-2.17.so
 (version 19.16.12.49)
2020.06.08 16:19:31.583238 [ 178 ] {} <Error> ServerErrorHandler: Poco::Exception. Code: 1000, e.code() = 104, e.displayText() = Connection reset by peer (version 19.16.12.49
2020.06.08 16:23:38.177374 [ 171 ] {} <Error> ServerErrorHandler: Poco::Exception. Code: 1000, e.code() = 104, e.displayText() = Connection reset by peer (version 19.16.12.49

**Comment by den-crane** [comment]
Can you please describe your environment? As I can you have issues with select from hadoop? 
Is it immediate error or you query? works for some time before the error?

**Comment by zhbdesign** [comment]
We have a lot of tables that need to be inserted. This error occurs when a large number of tables are inserted. The server load is also high

**Comment by den-crane** [comment]
Still unclear what is going on. Need more info about queries, tables, environment.

>DB::NetException: Timeout: connect timed out: ...*:9002 (hadoop-master2:9002)

How this error is related to inserts? What is `hadoop-master2:9002`?

**Comment by den-crane** [comment]
No info.

**Comment by zhbdesign** [comment]
Execute 'optimize table ods.user 'click house exception, code: 209, host: null, port: 0; Code: 209, e.displaytext() = DB:: netexception: timeout: connect timed out: 192.168.10.178:9002 (hadoop-node7:9002) (version 19.16.12.49)), 192.168.10.178 is the replica machine. At this time, the load and network are normal
