### ISSUE TITLE
clickhouse-copier --daemon dose not work

### ISSUE THREAD

**Issue by Fanduzi** [ClickHouse/ClickHouse#11507]
# Q1 --daemon dose not work
```
# clickhouse-copier --daemon --config zookeeper.xml --task-path /clickhouse/copytasks/rattax_dml --task-file rttax_dml.xml --task-upload-force=true 
# echo $?
0
```
zk
```
[zk: localhost:2181(CONNECTED) 9] ls /clickhouse/copytasks
[]
```
nothing happed

but if remove the --daemon, it works as expected
```
bj2-all-clickhouse-test-01 :)  select count(*) from test_migration.rttax_dml;

SELECT count(*)
FROM test_migration.rttax_dml

┌──count()─┐
│ 70269053 │
└──────────┘

1 rows in set. Elapsed: 0.004 sec. 

bj2-all-clickhouse-test-01 :)  select count(*) from mysql_monitor.rttax_dml;

SELECT count(*)
FROM mysql_monitor.rttax_dml

┌──count()─┐
│ 70269053 │
└──────────┘

1 rows in set. Elapsed: 0.004 sec. 
```

# Q2
In the doc
https://clickhouse.tech/docs/en/operations/utilities/clickhouse-copier/#running-clickhouse-copier
The utility should be run manually:
```
$ clickhouse-copier copier --daemon --config zookeeper.xml --task-path /task/path --base-dir /path/to/dir
```
there is a option `copier`, but the doc and command help dosen't describe it

# Q3
```
--task-upload-force=task-upload-force            Force upload task-file even 
                                                 node already exists
```
--task-upload-force should be a boolean type, help information is confusing

**Comment by nikitamikhaylov** [comment]
Hello! 
Q1: I debug it and created an issue #11526 
Q2: There is no option `copier`, it is a typo
Q3: `task-upload-force` is interpreted as a boolean in our codebase 

You can contribute to our documentation by clicking the pencil in the top of the site :wink:

**Comment by Fanduzi** [comment]
> Hello!
> Q1: I debug it and created an issue #11526
> Q2: There is no option `copier`, it is a typo
> Q3: `task-upload-force` is interpreted as a boolean in our codebase
> 
> You can contribute to our documentation by clicking the pencil in the top of the site 😉

thanks!
