### ISSUE TITLE
Permission to precision of data fraction part exceed S in field definition

### ISSUE THREAD

**Issue by calebeaires** [ClickHouse/ClickHouse#11518]
I can create and insert data to a Decimal field. This is simple and easy. Some case when doing calculations or when importing data or when changing date I get this error:

```
Error: **Code: 69 - DB::Exception: Decimal value is too small: at row 0**
ClickHouse version 20.4.2.9
```

Descriptions of the problem
```sql
-- CREATE TABLE with DECIMAL FIELD
CREATE TABLE bucket_18.mytable(
	some_base Decimal(10, 3)
) ENGINE = MergeTree
ORDER BY tuple();

-- TRY to insert value

-- SUCCESS
insert into table bucket_18.mytable (some_base) VALUES (1.1);

-- SUCCESS
insert into table bucket_18.mytable (some_base) VALUES (1.12);

-- SUCCESS
insert into table bucket_18.mytable (some_base) VALUES (1.123);

-- ERR, FAIL, you cant!
insert into table bucket_18.mytable (some_base) VALUES (1.1234);
```

**I ask to myself**
1.  Why decimal sizes with less then the precision does not fail but with more then the given precision fails?
2. Is there some configuration/settings that I can set to make this work?

**FEATURE REQUEST: Describe the solution you'd like**

A. SOLUTION/Suggestion ONE: 
Give permission/function to ClickHouse to lead with precision bigger then that one of the field doing operation like round or ceil or just throw away the sizes that exceeds.

B. SOLUTION/Suggestion TWO:
While create a MergeTree table, make use of a CHECK function that works with the values while you execute a INSERT operation, something like that: 

```sql
-- CREATE TABLE with DECIMAL FIELD
CREATE TABLE bucket_18.mytable(
	some_base Decimal(10, 3) check(round(some_base))
) ENGINE = MergeTree
ORDER BY tuple();
````

Obs.:
I am aware that clickhouse users can transform data while insert, but sometimes the values comes with diferente decimal sizes. It would be great to have one of those suggestions on the great clickhouse

**Comment by filimonov** [comment]
You will not see that exception anymore on newer version.
See https://github.com/ClickHouse/ClickHouse/pull/11831
