### ISSUE TITLE
support `countIf(DISTINCT col1, <cond_expr>)`

### ISSUE THREAD

**Issue by zzn01** [ClickHouse/ClickHouse#11517]
(you don't have to strictly follow this form)

**Use case**
when trying to translate postgres sql to clickhouse sql,  `COUNT(col1) FILTER (WHERE <cond_expr>)`  is equal with `countIf(col1, <cond_expr>)`. it would be much more consistent if 
`COUNT(DISTINCT col1) FILTER (WHERE <cond_expr>)` can translate as `countIf(DISTINCT col1, <cond_expr>)`.

**Describe the solution you'd like**
As `count(DISTINCT col1)` is supported, looks like it's reasonable to support `countIf(DISTINCT col1, <cond_expr>)` .

**Describe alternatives you've considered**
`uniqExactIf(col1, <cond_expr>)`

**Additional context**

**Comment by CurtizJ** [comment]
This feature is already in development #10930. It will be possible to appy `DISTINCT` for any aggregate function.

**Comment by alexey-milovidov** [comment]
@CurtizJ But the case for countIf should be special with more simple implementation.

**Comment by alexey-milovidov** [comment]
Need to validate the comment above :)

**Comment by CurtizJ** [comment]
`CountIfDistinct` now is replaced to `uniqExactIf` (More accuratly to `count_distinct_implementation` + `If`).

**Comment by alexey-milovidov** [comment]
Perfect!
