### ISSUE TITLE
Copier --daemon option doesn't work.

### ISSUE THREAD

**Issue by nikitamikhaylov** [ClickHouse/ClickHouse#11526]
Copier forks its process, then a child try to do main work. But it fails here:
https://github.com/ClickHouse/ClickHouse/blob/42acb627fbd1f5c155d2e6ea589a6471b2a46e94/programs/copier/ClusterCopierApp.cpp#L35

```
(gdb) next 
34	    process_path = Poco::Path(base_dir + "/clickhouse-copier_" + process_id).absolute().toString();
(gdb) next 
35	    Poco::File(process_path).createDirectories();
(gdb) next 
[Inferior 1 (process 1024) exited with code 0350]
(gdb) 
```
To reproduce you can print `pid` https://github.com/ClickHouse-Extras/poco/blob/be2ab90ba5dccd46919a116e3fe4fa77bb85063b/Util/src/ServerApplication.cpp#L667 and add a `sleep` in child process.

**Comment by SaltTan** [comment]
It works if absolute paths are specified:
```
clickhouse-copier --daemon --config /opt/copier/copier.xml --task-path /clickhouse/copier/task --task-file /opt/copier/task.xml
```
