### ISSUE TITLE
WITH with functions leads to `Unknown column` error

### ISSUE THREAD

**Issue by 4ertus2** [ClickHouse/ClickHouse#11535]
```
select a
from (
    with a+1 as aa,
        sumIf(aa, b > 0) as aaif
    select a, aaif
    FROM (select 1 as a, 2 as b)
    GROUP BY a
) as V;
```
```
DB::Exception: Unknown column: aa, there are only columns a, b.
```

**Comment by selitsky** [comment]
The same problem with sum(if()):
`select a
from (
    with a+1 as aa
        -- , sumIf(c, b > 0) as aaif
        , sum(if(b>0,c,0))  as aaif2
    select a, aaif2
    FROM
        (select 1 as a, 2 as b, 3 as c)
    GROUP BY a
) as V;`

`Code: 47, e.displayText() = DB::Exception: Unknown column: if(greater(b, 0), c, 0), there are only columns a, b, c (version 20.1.12.86 (official build))`

But it work without **WITH**:
`select a
from (
    with a+1 as aa
        -- , sumIf(c, b > 0) as aaif
        -- , sum(if(b>0,c,0))  as aaif2
    select a, sumIf(c, b > 0) as aaif3
    FROM
        (select 1 as a, 2 as b, 3 as c)
    GROUP BY a
) as V`

**Comment by filimonov** [comment]
Maybe related: https://github.com/ClickHouse/ClickHouse/issues/4432

**Comment by c3mb0** [comment]
this is still present in 20.9

a single alias in with works fine, 2+ aliases give the unknown column error

**Comment by alexey-milovidov** [comment]
All queries work perfectly.
