### ISSUE TITLE
ClickHouse & Event-based statistics

### ISSUE THREAD

**Issue by AlexVo1d** [ClickHouse/ClickHouse#11549]
Hi,
I have application with relational data model. Simplified example:
```
Employee {
    String id;
    String name;
    String email;
    String orgId;
}
Organization {
    String id;
    String name;
}
```
My app sends CRUD **events to ClickHouse** in denormalized form:
```
{“eventDate”: “2020-06-04 11:11:28.461”, “id”: “442700df-bc18-4a84-ac2a-e882d787f9e6”, “name”: “Employee 1”, "email": "mail@mail.com", “orgId”: “fc6d4a3d-e4f1-4d08-ac9d-22edbbe3fcad”, “orgName”: “Organization 1”, “operation”: “CREATE”}
{“eventDate”: “2020-06-04 12:13:27.567”, “id”: “442700df-bc18-4a84-ac2a-e882d787f9e6”, “name”: “Employee 1”, "email": "newmail@mail.com", “orgId”: “fc6d4a3d-e4f1-4d08-ac9d-22edbbe3fcad”, “orgName”: “Organization 1”, “operation”: “UPDATE”}
{“eventDate”: “2020-06-04 13:11:16.376”, “id”: “442700df-bc18-4a84-ac2a-e882d787f9e6”, “name”: “Employee 1”, "email": "newmail@mail.com", “orgId”: “fc6d4a3d-e4f1-4d08-ac9d-22edbbe3fcad”, “orgName”: “Organization 1”, “operation”: “DELETE”}
```
I need to get statistics on these events:
1. Actual number of employees (created but not deleted)
2. Number of employees for each organization (Organization Name : NNN)
3. Number of employees for specified organization by day
4. Reports: list of all employees (not events!) & employees for given condition

Questions and problems:
1. Is it right way to use events for such statistics?
2. What is the best way to get actual number of employees (created but not deleted)? Are there any special features for this in Clickhouse?
3. How to get actual information for reports (get fields from last create/update event for not deleted employees)? Are there any special features for this in Clickhouse?
4. If the organization has been renamed, I must send update event for all employees of this organization. There are hundreds of employees in organization and application does not send events for related entities now. What is the best way? Dont use denormalization? Use JOINs?

**Comment by melvynator** [comment]
For this type of use cases you might want to consider different types of table than the traditional merge tree one.

> Is it right way to use events for such statistics?

Well it depends initially how your data are being collected. If you can collect your data in a different way it might be better than receiving the event based user.

> What is the best way to get actual number of employees (created but not deleted)? Are there any special features for this in Clickhouse?

Maybe the [collapsing mergetree](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/collapsingmergetree/) could help you with this specific scenario.

> How to get actual information for reports (get fields from last create/update event for not deleted employees)? Are there any special features for this in Clickhouse?

The [collapsing mergetree](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/collapsingmergetree/) could also help you here.

> If the organization has been renamed, I must send update event for all employees of this organization. There are hundreds of employees in organization and application does not send events for related entities now. What is the best way? Dont use denormalization? Use JOINs?

Denormalization is usually the way to go but you can also use joins.
