### ISSUE TITLE
Integration Test Issue -- can not find docker_compose.yml

### ISSUE THREAD

**Issue by AlexanderChiuluvB** [ClickHouse/ClickHouse#11569]
I follow the steps in dbms/tests/intregration/readme.md
Everything is installed, but then when I use  `pytest -k test_extreme-deduplication`, an error occurs like this:
```
.FileNotFoundError: [Errno 2] No such file or directory: '/run/damon/clickhouse-server/dbms/tests/integration/test_extreme_deduplication/_instances/node1/docker_compose.yml'
```
Should I manually add a docker_compose.yml in the node1 dir? If so, what should I add in the yml?
There's no specification in readme.md :(

**Comment by alesapin** [comment]
This `.yml` file is generated on fly. Please, show full logs for pytest and your env variables.

**Comment by AlexanderChiuluvB** [comment]
> This .yml file is generated on fly. Please, show full logs for pytest and your env variables.

Thanks, I have solve the problem. After the compilation, I change the config dirs and binary dirs in cluster.py. And it works.
