### ISSUE TITLE
Handling heavy requests concurrently 

### ISSUE THREAD

**Issue by maison2710** [ClickHouse/ClickHouse#11566]
The context is that we have a dashboard of 10 charts, which make query requests to ClickHouse. Each query is only performed in 1 table using group by, order by. 

If we run each query individually, it is always successful and may take 10-20 seconds. However, when the whole dashboard is loaded, multiple request will be sent to CH at same time and put a high load on ClickHouse. Sometimes, it makes the ClickHouse server terminate due to OOM.

So my question is how ClickHouse handle the scenario when there are multiple heavy queries concurrently? How can we avoid OOM in such case?

For our ClickHouse setting, we have cluster of 3 instances, each have 8 cpus and 28 GB RAM. 
I configure `max_bytes_before_external_sort` to be 8GB and `max_bytes_before_external_group_by` to be 5GB.

**Comment by qoega** [comment]
Which version do you use? 
What is the current `max_memory_usage` on your cluster?
We have significantly improved memory tracking in 20.4 release.

max_bytes_before_external_sort/max_bytes_before_external_group_by flushed data on disk if sort and group by can't allocate more memory. Probably it is not used as your query runs 10-20 seconds.
 Your case is about overall memory usage.

**Comment by alexey-milovidov** [comment]
Fixed in https://github.com/ClickHouse/ClickHouse/pull/10362.
