### ISSUE TITLE
Extend load_balancing first_or_random to first_2th_or_random

### ISSUE THREAD

**Issue by qixiaogang** [ClickHouse/ClickHouse#11565]
**Use case**
In https://clickhouse.tech/docs/en/operations/settings/settings/#load_balancing-first_or_random, `first_or_random` works for 1 replica per AZ, but doesn't work for 2 replicas per AZ.
Let's say, there are two AZs (A and B), and 1 shard and 2 replicas in each AZ. 4 hosts are like below.
```
A_shard1_replicas1
A_shard1_replicas2
B_shard1_replicas1
B_shard1_replicas2
```
Configure load_balancing = first_or_random
In AZ A, remote_servers.xml is 
```
<yandex>
    <remote_servers>
        <cross-az>
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                    <host>A_shard1_replicas1</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>A_shard1_replicas2</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>B_shard1_replicas1</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>B_shard1_replicas2</host>
                    <port>9000</port>
                </replica>
            </shard>
        </cross-az>
    </remote_servers>
</yandex>
```
In AZ B, remote_servers.xml is
```
<yandex>
    <remote_servers>
        <cross-az>
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                    <host>B_shard1_replicas1</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>B_shard1_replicas2</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>A_shard1_replicas1</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>A_shard1_replicas2</host>
                    <port>9000</port>
                </replica>
            </shard>
        </cross-az>
    </remote_servers>
</yandex>
```
In AZ A, if `A_shard1_replicas1` is unavailable, then the first_or_random algorithm chooses randomly from the left 3 hosts, but it is better to choose `A_shard1_replicas2`. 

**Describe the solution you'd like**
In AZ A, we want first_2th_or_random load_balance, which will act as below:
- If `A_shard1_replicas1` and `A_shard1_replicas2` are available, randomly choose one of them, 
- If one of `A_shard1_replicas1` and `A_shard1_replicas2` is available, choose the available one,
- If `A_shard1_replicas1` and `A_shard1_replicas2` are unavailable, randomly choose one of `B_shard1_replicas1` and `B_shard1_replicas2`

**Comment by azat** [comment]
Looks too tricky, I'm guess simple round-robin will be enough?

**Comment by nvartolomei** [comment]
This gets complicated, but a more flexible solution might be nested replica lists/groups.

```xml
<shard>
  <internal_replication>true</internal_replication>
  <replica_list load_balancing="in_order">
    <replica_list load_balancing="random">
      <replica>
        <host>AZ_A_shard1_replicas1</host>
        <port>9000</port>
      </replica>
      <replica>
        <host>AZ_A_shard1_replicas2</host>
        <port>9000</port>
      </replica>
    </replica_list>
    <replica_list load_balancing="random">
      <replica>
        <host>AZ_B_shard1_replicas1</host>
        <port>9000</port>
      </replica>
      <replica>
        <host>AZ_B_shard1_replicas2</host>
        <port>9000</port>
      </replica>
    </replica_list>
  </replica_list>
</shard>
```

When picking a replica for a shard you hit go to first `replica_list`, look at balancing policy and pick a nested replica/replica_list based on that. Apply recursively until you have picked a `replica`.

This also solves another problem with `first_or_random`. That is when you have a circular replication topology with 3 replicas and one of them dies and you want to remove it from topology. Currently first_or_random will degrade to the in_order policy and the hack is to put a unavailable host in place of the first replica, with nested pools you could do this:

```
<shard>
  <internal_replication>true</internal_replication>
  <replica_list load_balancing="first_or_random">
    <replica_list>
      <replica>
        <host>replica1</host>
        <port>9000</port>
      </replica>
    </replica_list>
    <replica_list load_balancing="random">
      <replica>
        <host>replica2</host>
        <port>9000</port>
      </replica>
      <replica>
        <host>replica3</host>
        <port>9000</port>
      </replica>
    </replica_list>
  </replica_list>
</shard>
```

Removing `replica1` from the list will work as expected.

**Comment by filimonov** [comment]
Maybe just adding smth like `priority` would be enough? I.e. do random / round-robin between nodes of same (highest) priority, if none of them is avaliable - check nodes with lower priority, etc.

**Comment by qixiaogang** [comment]
https://github.com/ClickHouse/ClickHouse/issues/11565#issuecomment-643674741 simple round-robin will not work for my case, as my case across AZs. For query hit A AZ, we would like it go to replica AZ_A_shard1_replicas1 and A_shard1_replicas2 first if all 4 replica has same errors.

https://github.com/ClickHouse/ClickHouse/issues/11565#issuecomment-643747448 and https://github.com/ClickHouse/ClickHouse/issues/11565#issuecomment-643764790 will work for my requirement, can team support it in the future?
