### ISSUE TITLE
merge_with_ttl_timeout trigger should clean all expired parts

### ISSUE THREAD

**Issue by fhmcn** [ClickHouse/ClickHouse#11576]
**Describe the bug**
Only drop single partition is dropped per merge_with_ttl_timeout period. Other expired partitions stays there. 

**How to reproduce**
* Version: 20.3.8.53
* Setting: 
--  ttl_only_drop_parts=1 
-- system.part_log is on
* create any table partitioned table load data into. Wait for timeout TTL and observe parts changes from system.part_log table.

**Expected behavior**
It should drop whole expired parts once it checks for TTL. 

**Additional context**
As workaround 'ALTER TABLE events MATERIALIZE TTL' command is run, it triggers to remove parts.

**Comment by filimonov** [comment]
#10128

**Comment by den-crane** [comment]
It needs to apply TTL to **ALL parts** of all partitions. 
It seems TTL drops only one **PART** per merge_with_ttl_timeout.

**Comment by jondeandres** [comment]
Any update on this?

**Comment by alex-zaitsev** [comment]
@jondeandres , this is scheduled for development already. Should be fixed fairly soon. For now just set merge_with_ttl_timeout to some smaller value, like 1800.

**Comment by filimonov** [comment]
Fixed in #12548
