### ISSUE TITLE
Shell exit code overflow when exception code > 255

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#11581]
Reported by @vzakaznikov 

https://github.com/ClickHouse/ClickHouse/blob/e144e78b31ffc16ea1626d5471d4748aae1c9454/programs/client/Client.cpp#L1923

**Comment by vzakaznikov** [comment]
My recommendation is leave exit codes as is and close this issue. Any changes might break more things that it will fix. For example, all the CI tests that check exit codes. It is very unfortunate that due to legacy stuff exit codes are limited to 256.

**Comment by alexey-milovidov** [comment]
@vzakaznikov The only issue is that they can possibly overflow to 0. We should not return 0 exit code on error, it's a bug.
