### ISSUE TITLE
How to distinguish which result is cube？

### ISSUE THREAD

**Issue by sundy-li** [ClickHouse/ClickHouse#11594]
```
:) select toString(number%2) as a, toString(number % 3)  as b, count() from numbers(10000) group by  cube(a,b) format JSONEachRow;

SELECT
    toString(number % 2) AS a,
    toString(number % 3) AS b,
    count()
FROM numbers(10000)
GROUP BY
    a,
    b
    WITH CUBE
FORMAT JSONEachRow

{"a":"0","b":"0","count()":"1667"}
{"a":"0","b":"1","count()":"1666"}
{"a":"0","b":"2","count()":"1667"}
{"a":"1","b":"2","count()":"1666"}
{"a":"1","b":"1","count()":"1667"}
{"a":"1","b":"0","count()":"1667"}
{"a":"0","b":"0","count()":"5000"}
{"a":"1","b":"0","count()":"5000"}
{"a":"0","b":"0","count()":"3334"}
{"a":"0","b":"2","count()":"3333"}
{"a":"0","b":"1","count()":"3333"}
{"a":"0","b":"0","count()":"10000"}
```

1. Why the last entry is not `{"a":"","b":"","count()":"10000"}`?  I think this may be a bug.
2. How to distinguish the result if the original column contains empty String?

**Comment by den-crane** [comment]
Using cast to Nullable.


**SELECT
    cast(toString(number % 2), 'Nullable(String)') AS a,
    cast(toString(number % 3), 'Nullable(String)') AS b,
    count()
FROM numbers(10000)
GROUP BY
    a,
    b
    WITH CUBE

┌─a─┬─b─┬─count()─┐
│ 0 │ 2 │    1667 │
│ 1 │ 2 │    1666 │
│ 1 │ 1 │    1667 │
│ 0 │ 1 │    1666 │
│ 0 │ 0 │    1667 │
│ 1 │ 0 │    1667 │
└───┴───┴─────────┘
┌─a─┬─b────┬─count()─┐
│ 1 │ ᴺᵁᴸᴸ │    5000 │
│ 0 │ ᴺᵁᴸᴸ │    5000 │
└───┴──────┴─────────┘
┌─a────┬─b─┬─count()─┐
│ ᴺᵁᴸᴸ │ 2 │    3333 │
│ ᴺᵁᴸᴸ │ 0 │    3334 │
│ ᴺᵁᴸᴸ │ 1 │    3333 │
└──────┴───┴─────────┘
┌─a────┬─b────┬─count()─┐
│ ᴺᵁᴸᴸ │ ᴺᵁᴸᴸ │   10000 │
└──────┴──────┴─────────┘**

**Comment by den-crane** [comment]
it will be addressed in https://github.com/ClickHouse/ClickHouse/issues/10540

**Comment by crakjie** [comment]
What if the column is already Nullable ?

**Comment by den-crane** [comment]
@crakjie Then nothing. What do you think?

psql> SELECT a,b, count(*)
FROM (select 1 a, 2 b union all select 1 a, 1 b union all select null a, 1 b) t
GROUP BY CUBE (a, b)
ORDER BY a,b;

   a    |   b    | count
--------+--------+-------
      1 |      1 |     1
      1 |      2 |     1
      1 | <null> |     2
 <null> |      1 |     2
 <null> |      1 |     1
 <null> |      2 |     1
 <null> | <null> |     3
 <null> | <null> |     1
(8 rows)


:) SELECT a,b, count(*)
FROM (select 1 a, cast(2,'Nullable(Int8)') b union all select 1 a, 1 b union all select null a, 1 b) t
GROUP BY CUBE (a, b)
ORDER BY a,b;

┌────a─┬────b─┬─count()─┐
│    1 │    1 │       1 │
│    1 │    2 │       1 │
│    1 │ ᴺᵁᴸᴸ │       2 │
│ ᴺᵁᴸᴸ │    1 │       2 │
│ ᴺᵁᴸᴸ │    1 │       1 │
│ ᴺᵁᴸᴸ │    2 │       1 │
│ ᴺᵁᴸᴸ │ ᴺᵁᴸᴸ │       3 │
│ ᴺᵁᴸᴸ │ ᴺᵁᴸᴸ │       1 │
└──────┴──────┴─────────┘

```

**Comment by crakjie** [comment]
@den-crane I'm not sure to understand what you are proposing.
What is `GROUP BY CUBE` compared to `WITH CUBE` ?
In your exemple totals are not differenciated from than null column ? How can you know if it's a totals or a row ?

**Comment by simPod** [comment]
How would we distinguish empty strings vs null in cube? It always gives empty string.

```sql
SELECT
    cast(toString(''), 'Nullable(String)') AS a,
    cast(toString(number % 3), 'Nullable(String)') AS b,
    count()
FROM numbers(10000)
GROUP BY
    a,
    b
    WITH CUBE
```
