### ISSUE TITLE
The distributed table query performance is equal to the serial execution of the local table of each node

### ISSUE THREAD

**Issue by kainever7** [ClickHouse/ClickHouse#11597]
I deployed 29 nodes.
version : 20.3.2.1
sql   :   select count() from [table] where  has(apps, 123) and pt_d='20200610'

when the table is distributed table : it cost 12 s.
when the table is local table,  I execute on 29 nodes ， Every node cost 0.45s.

Using distributed table query is parallel on each node, then the execution time should be within 1s.
but now is 12s = 0.45 * 29.
so, I think the query using distributed tables in my environment is serial. 
How should I solve this problem?

Thanks.

**Comment by SaltTan** [comment]
Duplicate https://github.com/ClickHouse/ClickHouse/issues/10655

**Comment by den-crane** [comment]
@kainever7 try to upgrade to 20.3.9.70
