### ISSUE TITLE
"limit n, m" doesn't work in some case

### ISSUE THREAD

**Issue by 1818hero** [ClickHouse/ClickHouse#11618]
Sometimes use "limit [offset], [pageSize]" fail to query data.
For example, 
```
SELECT xxx FROM tablename
WHERE 1=1    and recordDate >= '2020-05-01' and recordDate <= '2020-06-30' 
order by eventTime desc 
```
It can  return 72 records. I want to paging it ,so 
```
SELECT xxx FROM tablename
WHERE 1=1    and recordDate >= '2020-05-01' and recordDate <= '2020-06-30' 
order by eventTime desc  limit 0, 10
```
It can return the latest 10 records, fine.
But 
```
SELECT xxx FROM tablename
WHERE 1=1    and recordDate >= '2020-05-01' and recordDate <= '2020-06-30' 
order by eventTime desc  limit 20, 10
```
It just return 8 records, and if the offset changed, the records number changed. I can't find the laws of clickhouse. Is there Anyone know it ?

**Comment by 1818hero** [comment]
In addition, using LIMIT BY sometimes can change the case, but why?

**Comment by den-crane** [comment]
What CH version do you use?
Can you show `show create table tablename` ?

It was an issue https://github.com/ClickHouse/ClickHouse/issues/10566

**Comment by 1818hero** [comment]
> What CH version do you use?
> Can you show `show create table tablename` ?
> 
> It was an issue #10566

Thank you for your reply.

I use version 20.3.8.53-2

CREATE TABLE gec.tablename (`id` Int64, `meCode` String, `deCode` String, `dataValue` String, `eventTime` DateTime, `recordDate` Date DEFAULT toDate(eventTime)) ENGINE = MergeTree() PARTITION BY toYYYYMMDD(recordDate) ORDER BY (eventTime, recordDate) SETTINGS index_granularity = 8192

**Comment by 1818hero** [comment]
I have solved this problem by upgrade clickhouse  to version 20.4.5.36
