### ISSUE TITLE
plaintext password in metrika.xml is not secure

### ISSUE THREAD

**Issue by wallace-clickhouse** [ClickHouse/ClickHouse#11625]
Firstly,Thanks for excellent performance of clickhouse.

When I configure the metrika.xml to create a distributed cluster,I find I must put the plaintext password into <password> </password> field, and then the shard can connect to other shards with this password,I think plaintext password in metrika.xml is not secure.

I hope we can fill a encrypted string into  <password> </password> field, the encrypted string can be encrypted with AES-512,and when the shard needs to visit other shards,it can decrypt firstly and then connect other shards with the decrypted password.

Thank you!

**Comment by den-crane** [comment]
>when the shard needs to visit other shards,it can decrypt firstly 

Decrypt how? Using another password stored in /etc/secret.aes ?

You can configure passwordless schema and restrict access by ip addresses 

For example it opens access to  a user `default` from only these 3 ip / network.

```
cat /etc/clickhouse-server/conf.d/user_default.xml
<?xml version="1.0" ?>
<yandex>
    <users>
        <default>
            <networks replace="replace">
                <ip>::1</ip>
                <ip>127.0.0.1</ip>
                <ip>10.253.86.3</ip>
                <ip>10.253.215.3</ip>
            </networks>
        </default>
    </users>
</yandex>
```

**Comment by wallace-clickhouse** [comment]
@den-crane Thank you for your reply!
I thought of the method you mentioned. I think it is a risk reduction measure, but in fact it is still unsafe. Can this be modified? For example, we configure a reversible ciphertext in the metrika.xml file, and when clickhouse needs to connect to other shards, it automatically decrypts and obtains the real password to connect, I think this will be better.

**Comment by den-crane** [comment]
>>Decrypt how? Using another password stored in /etc/secret.aes ?
>when clickhouse needs to connect to other shards, it automatically decrypts

@wallace-clickhouse OK. Excellent idea. Please explain how CH automatically decrypts encrypted passwords? By what password? Hard-coded in CH ? 12345678?

**Comment by wallace-clickhouse** [comment]
Can we do like this?
We can preset a default password (for example, 123456) in users.xml for the "default" user, and then recommend that users change it when using clickhouse. At the same time, we use a system-generated secure random number as the key (the key shoud be  stored in a certain file) to encrypt the default password using AES-512, and fill the encrypted ciphertext into the metrika.xml file. When connecting to other shards, firstly use AES-512 and the key to decrypt the ciphertext in metrika.xml, get the plaintext password and use it to connect to other shards.

Thank you!

**Comment by den-crane** [comment]
You talking about  metrika.xml . Do you understand that usage of this file is not mandatory? You can put a password directly in /etc/clickhouse-server/users.d/user_name.xml ?

>the key shoud be stored in a certain file)

What is the difference where to store password in user_name.xml  or `certain file` ?
You just add one more step for intruder decrypt the password after reading `certain file`. No sense.
