### ISSUE TITLE
whether interserver_http_credential is necessary

### ISSUE THREAD

**Issue by wallace-clickhouse** [ClickHouse/ClickHouse#11626]
I configure replication on my cluster with interserver_http_port and interserver_http_host,But I am puzzled that whether the interserver_http_credential(include user and password) is necessary?because I don't want to configure plaintext password into configuretion file.If interserver_http_credential is not necessary and I don't configure the user&password, does it mean that there is no authentication between replications. 

Thank you!

**Comment by den-crane** [comment]
By default replication is password-less so malicious replica can still your parts (data).
You can use `interserver_http_credential` or restrict access using `networks` for default user

```
cat /etc/clickhouse-server/conf.d/user_default.xml
<?xml version="1.0" ?>
<yandex>
    <users>
        <default>
            <networks replace="replace">
                <ip>::1</ip>
                <ip>127.0.0.1</ip>
                <ip>10.253.86.3</ip>
                <ip>10.253.215.3</ip>
            </networks>
        </default>
    </users>
</yandex>
```

Or/And additionally restrict access to replication port 9009 using OS firewall.

**Comment by wallace-clickhouse** [comment]
Great! I like password-less communication beetween replications,haha...
However why we don't  use passdword-less way also for the data exchange among shards,it leads to a problem that I have to configure a plaintext password in metrika.xml,it's really not secure.
Thank you!

**Comment by den-crane** [comment]
>However why we don't use passdword-less way also for the data exchange among shards

It's unrelated to replication. You have not. I replied in https://github.com/ClickHouse/ClickHouse/issues/11625
