### ISSUE TITLE
Why not supply a SQL command(such as load or copy) for importing batch data into clickhouse

### ISSUE THREAD

**Issue by wallace-clickhouse** [ClickHouse/ClickHouse#11624]
Currently When I want to import batch data into clickhouse,I have to use clickhouse-client CLI and I must put the username and password as parameters of clickhouse-client CLI.then I find  a secure problem,that is anybody who login on the server can get the password by using 'ps -ef' or 'history' command,also the  clickhouse-client CLI containing the password is recorded in the OS message logfile.
So I suggest a solution, that is clickhouse can supply a SQL command 'load' or 'copy'(like postgresql) to import data into database when user has logined in.

thank you!

**Comment by den-crane** [comment]
You can use prompted password input 

```
cl -u test --password -q "select 1"
Password for user (test):

```

And you can hide a password in `ps` using shell variables. 

And cli-client probably should hide password in ps by itself https://unix.stackexchange.com/questions/88665/how-does-ps-know-to-hide-passwords

**Comment by wallace-clickhouse** [comment]
Thank you very much!
For my situation, I expect to call clickhouse-client by java code,so I think it's difficult for me to use prompted way to input the password,is there any other way for me to achieve it?

**Comment by den-crane** [comment]
And why do you need cl-client if you use java? Why not HTTP or JDBC ?

**Comment by den-crane** [comment]
@wallace-clickhouse 

Oh, I just realized that you wanted to load data by clickhouse-server process from files at server. It actually possible using file function https://clickhouse.tech/docs/en/sql-reference/table-functions/file/

But still I would use HTTP or JDBC in case of JAVA. 

HTTP https://clickhouse.tech/docs/en/interfaces/http/

https://github.com/ClickHouse/clickhouse-jdbc#importing-file-into-table

https://github.com/blynkkk/clickhouse4j#insert-from-file-to-db

**Comment by wallace-clickhouse** [comment]
@den-crane 
Thank you for your reply!
I use ClickHouse-Native-JDBC as JDBC Driver in my program because I think HTTP is not secure.so is there any similar interface in ClickHouse-Native-JDBC foro importing data?

**Comment by blinkov** [comment]
@wallace-clickhouse both protocols (HTTP and Native) are not secure by default but can be configured to be encrypted.

**Comment by wallace-clickhouse** [comment]
@blinkov Thank you!
I have tried to merge the code of "Clear password from command line" to my version(20.3.2.1). Fortunately it works fine and shows no plaintext password  while execute 'ps'.History log still records the comand line with plaintext password,so I decide to shield it by using HISTIGNORE.

@den-crane @blinkov @alexey-milovidov 
Thank you very much!
