### ISSUE TITLE
RFC: automatic type cast of literals in obvious cases

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#11630]
```
select * from numbers(100) where number = '1';
```
literals can be casted to the column type. 

In general case there are too many side effects.

**Comment by den-crane** [comment]
Usual issue with other databases: in case col_string = 1 need to cast col_string to Int and this breaks index access.

**Comment by filimonov** [comment]
Yep, that why I'm saying only of allowing cast of literal (i.e. constants used in the query) to column type, and never opposite (that sounds relatively safe, but maybe there are some other issues).

**Comment by alexey-milovidov** [comment]
We have to implement it for SQL compatibility.
But it is not in development.

It will be more handy if we can postpone it after implementation of #3775 but that task is abandoned, and we may find simpler solution.

Example: a setting to enable cast of constants in comparison operators.
Note that it was already implemented for date and datetime: you can write `d = '2000-01-01'`.
