### ISSUE TITLE
build clickhouse in arm archtech with gcc-10.1.0, link error

### ISSUE THREAD

**Issue by bookeezhou** [ClickHouse/ClickHouse#11642]
Scanning dependencies of target parallel_aggregation
[ 85%] Building CXX object src/Common/tests/CMakeFiles/parallel_aggregation.dir/parallel_aggregation.cpp.o
[ 85%] Linking CXX executable parallel_aggregation
ld.lld: error: undefined symbol: ZSTD_compressLiterals
>>> referenced by zstd_compress.c:1974 (/root/cksrc/ClickHouse/contrib/zstd/lib/compress/zstd_compress.c:1974)
>>>               zstd_compress.c.o:(ZSTD_compressBlock_internal) in archive ../../../contrib/zstd-cmake/libzstd.a

ld.lld: error: undefined symbol: HIST_countFast_wksp
>>> referenced by zstd_compress.c:2016 (/root/cksrc/ClickHouse/contrib/zstd/lib/compress/zstd_compress.c:2016)
>>>               zstd_compress.c.o:(ZSTD_compressBlock_internal) in archive ../../../contrib/zstd-cmake/libzstd.a
>>> referenced by zstd_compress.c:2042 (/root/cksrc/ClickHouse/contrib/zstd/lib/compress/zstd_compress.c:2042)
>>>               zstd_compress.c.o:(ZSTD_compressBlock_internal) in archive ../../../contrib/zstd-cmake/libzstd.a
>>> referenced by zstd_compress.c:2070 (/root/cksrc/ClickHouse/contrib/zstd/lib/compress/zstd_compress.c:2070)
>>>               zstd_compress.c.o:(ZSTD_compressBlock_internal) in archive ../../../contrib/zstd-cmake/libzstd.a

ld.lld: error: undefined symbol: ZSTD_selectEncodingType
>>> referenced by zstd_compress.c:2019 (/root/cksrc/ClickHouse/contrib/zstd/lib/compress/zstd_compress.c:2019)
>>>               zstd_compress.c.o:(ZSTD_compressBlock_internal) in archive ../../../contrib/zstd-cmake/libzstd.a
>>> referenced by zstd_compress.c:2048 (/root/cksrc/ClickHouse/contrib/zstd/lib/compress/zstd_compress.c:2048)
>>>               zstd_compress.c.o:(ZSTD_compressBlock_internal) in archive ../../../contrib/zstd-cmake/libzstd.a
>>> referenced by zstd_compress.c:2074 (/root/cksrc/ClickHouse/contrib/zstd/lib/compress/zstd_compress.c:2074)
>>>               zstd_compress.c.o:(ZSTD_compressBlock_internal) in archive ../../../contrib/zstd-cmake/libzstd.a

ld.lld: error: undefined symbol: ZSTD_buildCTable
>>> referenced by zstd_compress.c:2026 (/root/cksrc/ClickHouse/contrib/zstd/lib/compress/zstd_compress.c:2026)
>>>               zstd_compress.c.o:(ZSTD_compressBlock_internal) in archive ../../../contrib/zstd-cmake/libzstd.a
>>> referenced by zstd_compress.c:2054 (/root/cksrc/ClickHouse/contrib/zstd/lib/compress/zstd_compress.c:2054)
>>>               zstd_compress.c.o:(ZSTD_compressBlock_internal) in archive ../../../contrib/zstd-cmake/libzstd.a
>>> referenced by zstd_compress.c:2080 (/root/cksrc/ClickHouse/contrib/zstd/lib/compress/zstd_compress.c:2080)
>>>               zstd_compress.c.o:(ZSTD_compressBlock_internal) in archive ../../../contrib/zstd-cmake/libzstd.a

ld.lld: error: undefined symbol: ZSTD_encodeSequences
>>> referenced by zstd_compress.c:2097 (/root/cksrc/ClickHouse/contrib/zstd/lib/compress/zstd_compress.c:2097)
>>>               zstd_compress.c.o:(ZSTD_compressBlock_internal) in archive ../../../contrib/zstd-cmake/libzstd.a

ld.lld: error: undefined symbol: HIST_count_simple
>>> referenced by huf_compress.c:104 (/root/cksrc/ClickHouse/contrib/zstd/lib/compress/huf_compress.c:104)
>>>               huf_compress.c.o:(HUF_writeCTable) in archive ../../../contrib/zstd-cmake/libzstd.a
>>> referenced by zstd_opt.c:176 (/root/cksrc/ClickHouse/contrib/zstd/lib/compress/zstd_opt.c:176)
>>>               zstd_opt.c.o:(ZSTD_rescaleFreqs) in archive ../../../contrib/zstd-cmake/libzstd.a

ld.lld: error: undefined symbol: HIST_count_wksp
>>> referenced by huf_compress.c:672 (/root/cksrc/ClickHouse/contrib/zstd/lib/compress/huf_compress.c:672)
>>>               huf_compress.c.o:(HUF_compress_internal.isra.0) in archive ../../../contrib/zstd-cmake/libzstd.a
>>> referenced by huf_compress.c:672 (/root/cksrc/ClickHouse/contrib/zstd/lib/compress/huf_compress.c:672)
>>>               huf_compress.c.o:(HUF_compress1X_wksp) in archive ../../../contrib/zstd-cmake/libzstd.a
>>> referenced by huf_compress.c:672 (/root/cksrc/ClickHouse/contrib/zstd/lib/compress/huf_compress.c:672)
>>>               huf_compress.c.o:(HUF_compress1X) in archive ../../../contrib/zstd-cmake/libzstd.a
>>> referenced by huf_compress.c:672 (/root/cksrc/ClickHouse/contrib/zstd/lib/compress/huf_compress.c:672)
>>>               huf_compress.c.o:(HUF_compress4X_wksp) in archive ../../../contrib/zstd-cmake/libzstd.a
>>> referenced by huf_compress.c:672 (/root/cksrc/ClickHouse/contrib/zstd/lib/compress/huf_compress.c:672)
>>>               huf_compress.c.o:(HUF_compress2) in archive ../../../contrib/zstd-cmake/libzstd.a
>>> referenced by fse_compress.c:675 (/root/cksrc/ClickHouse/contrib/zstd/lib/compress/fse_compress.c:675)
>>>               fse_compress.c.o:(FSE_compress2.part.0) in archive ../../../contrib/zstd-cmake/libzstd.a
>>> referenced by fse_compress.c:675 (/root/cksrc/ClickHouse/contrib/zstd/lib/compress/fse_compress.c:675)
>>>               fse_compress.c.o:(FSE_compress_wksp) in archive ../../../contrib/zstd-cmake/libzstd.a

ld.lld: error: undefined symbol: ZSTD_sizeof_DDict
>>> referenced by zstd_decompress.c:82 (/root/cksrc/ClickHouse/contrib/zstd/lib/decompress/zstd_decompress.c:82)
>>>               zstd_decompress.c.o:(ZSTD_sizeof_DCtx) in archive ../../../contrib/zstd-cmake/libzstd.a
>>> referenced by zstd_decompress.c:82 (/root/cksrc/ClickHouse/contrib/zstd/lib/decompress/zstd_decompress.c:82)
>>>               zstd_decompress.c.o:(ZSTD_sizeof_DStream) in archive ../../../contrib/zstd-cmake/libzstd.a

ld.lld: error: undefined symbol: ZSTD_freeDDict
>>> referenced by zstd_decompress.c:150 (/root/cksrc/ClickHouse/contrib/zstd/lib/decompress/zstd_decompress.c:150)
>>>               zstd_decompress.c.o:(ZSTD_freeDCtx) in archive ../../../contrib/zstd-cmake/libzstd.a
>>> referenced by zstd_decompress.c:150 (/root/cksrc/ClickHouse/contrib/zstd/lib/decompress/zstd_decompress.c:150)
>>>               zstd_decompress.c.o:(ZSTD_decompressDCtx) in archive ../../../contrib/zstd-cmake/libzstd.a
>>> referenced by zstd_decompress.c:150 (/root/cksrc/ClickHouse/contrib/zstd/lib/decompress/zstd_decompress.c:150)
>>>               zstd_decompress.c.o:(ZSTD_decompress) in archive ../../../contrib/zstd-cmake/libzstd.a
>>> referenced by zstd_decompress.c:150 (/root/cksrc/ClickHouse/contrib/zstd/lib/decompress/zstd_decompress.c:150)
>>>               zstd_decompress.c.o:(ZSTD_decompress) in archive ../../../contrib/zstd-cmake/libzstd.a
>>> referenced by zstd_decompress.c:150 (/root/cksrc/ClickHouse/contrib/zstd/lib/decompress/zstd_decompress.c:150)
>>>               zstd_decompress.c.o:(ZSTD_freeDStream) in archive ../../../contrib/zstd-cmake/libzstd.a
>>> referenced by zstd_decompress.c:150 (/root/cksrc/ClickHouse/contrib/zstd/lib/decompress/zstd_decompress.c:150)
>>>               zstd_decompress.c.o:(ZSTD_DCtx_loadDictionary_advanced) in archive ../../../contrib/zstd-cmake/libzstd.a
>>> referenced by zstd_decompress.c:150 (/root/cksrc/ClickHouse/contrib/zstd/lib/decompress/zstd_decompress.c:150)
>>>               zstd_decompress.c.o:(ZSTD_DCtx_loadDictionary_byReference) in archive ../../../contrib/zstd-cmake/libzstd.a
>>> referenced by zstd_decompress.c:150 (/root/cksrc/ClickHouse/contrib/zstd/lib/decompress/zstd_decompress.c:150)
>>>               zstd_decompress.c.o:(ZSTD_DCtx_loadDictionary) in archive ../../../contrib/zstd-cmake/libzstd.a
>>> referenced by zstd_decompress.c:150 (/root/cksrc/ClickHouse/contrib/zstd/lib/decompress/zstd_decompress.c:150)
>>>               zstd_decompress.c.o:(ZSTD_DCtx_refPrefix_advanced) in archive ../../../contrib/zstd-cmake/libzstd.a
>>> referenced by zstd_decompress.c:150 (/root/cksrc/ClickHouse/contrib/zstd/lib/decompress/zstd_decompress.c:150)
>>>               zstd_decompress.c.o:(ZSTD_DCtx_refPrefix) in archive ../../../contrib/zstd-cmake/libzstd.a
>>> referenced 8 more times

ld.lld: error: undefined symbol: ZSTD_getcBlockSize
>>> referenced by zstd_decompress.c:493 (/root/cksrc/ClickHouse/contrib/zstd/lib/decompress/zstd_decompress.c:493)
>>>               zstd_decompress.c.o:(ZSTD_findFrameSizeInfo) in archive ../../../contrib/zstd-cmake/libzstd.a
>>> referenced by zstd_decompress.c:909 (/root/cksrc/ClickHouse/contrib/zstd/lib/decompress/zstd_decompress.c:909)
>>>               zstd_decompress.c.o:(ZSTD_decompressContinue.part.0) in archive ../../../contrib/zstd-cmake/libzstd.a
>>> referenced by zstd_decompress.c:646 (/root/cksrc/ClickHouse/contrib/zstd/lib/decompress/zstd_decompress.c:646)
>>>               zstd_decompress.c.o:(ZSTD_decompressMultiFrame) in archive ../../../contrib/zstd-cmake/libzstd.a

ld.lld: error: undefined symbol: ZSTD_decompressBlock_internal
>>> referenced by zstd_decompress.c:943 (/root/cksrc/ClickHouse/contrib/zstd/lib/decompress/zstd_decompress.c:943)
>>>               zstd_decompress.c.o:(ZSTD_decompressContinue.part.0) in archive ../../../contrib/zstd-cmake/libzstd.a
>>> referenced by zstd_decompress.c:656 (/root/cksrc/ClickHouse/contrib/zstd/lib/decompress/zstd_decompress.c:656)
>>>               zstd_decompress.c.o:(ZSTD_decompressMultiFrame) in archive ../../../contrib/zstd-cmake/libzstd.a

ld.lld: error: undefined symbol: ZSTD_buildFSETable
>>> referenced by zstd_decompress.c:1061 (/root/cksrc/ClickHouse/contrib/zstd/lib/decompress/zstd_decompress.c:1061)
>>>               zstd_decompress.c.o:(ZSTD_loadDEntropy) in archive ../../../contrib/zstd-cmake/libzstd.a
>>> referenced by zstd_decompress.c:1074 (/root/cksrc/ClickHouse/contrib/zstd/lib/decompress/zstd_decompress.c:1074)
>>>               zstd_decompress.c.o:(ZSTD_loadDEntropy) in archive ../../../contrib/zstd-cmake/libzstd.a
>>> referenced by zstd_decompress.c:1087 (/root/cksrc/ClickHouse/contrib/zstd/lib/decompress/zstd_decompress.c:1087)
>>>               zstd_decompress.c.o:(ZSTD_loadDEntropy) in archive ../../../contrib/zstd-cmake/libzstd.a

ld.lld: error: undefined symbol: ZSTD_DDict_dictContent
>>> referenced by zstd_decompress.c:711 (/root/cksrc/ClickHouse/contrib/zstd/lib/decompress/zstd_decompress.c:711)
>>>               zstd_decompress.c.o:(ZSTD_decompressMultiFrame) in archive ../../../contrib/zstd-cmake/libzstd.a
>>> referenced by zstd_decompress.c:1168 (/root/cksrc/ClickHouse/contrib/zstd/lib/decompress/zstd_decompress.c:1168)
>>>               zstd_decompress.c.o:(ZSTD_decompressMultiFrame) in archive ../../../contrib/zstd-cmake/libzstd.a
>>> referenced by zstd_decompress.c:1168 (/root/cksrc/ClickHouse/contrib/zstd/lib/decompress/zstd_decompress.c:1168)
>>>               zstd_decompress.c.o:(ZSTD_decompressBegin_usingDDict) in archive ../../../contrib/zstd-cmake/libzstd.a
>>> referenced by zstd_decompress.c:1168 (/root/cksrc/ClickHouse/contrib/zstd/lib/decompress/zstd_decompress.c:1168)
>>>               zstd_decompress.c.o:(ZSTD_decompressStream) in archive ../../../contrib/zstd-cmake/libzstd.a
>>> referenced by zstd_decompress.c:1539 (/root/cksrc/ClickHouse/contrib/zstd/lib/decompress/zstd_decompress.c:1539)
>>>               zstd_decompress.c.o:(ZSTD_decompressStream) in archive ../../../contrib/zstd-cmake/libzstd.a

ld.lld: error: undefined symbol: ZSTD_DDict_dictSize
>>> referenced by zstd_decompress.c:712 (/root/cksrc/ClickHouse/contrib/zstd/lib/decompress/zstd_decompress.c:712)
>>>               zstd_decompress.c.o:(ZSTD_decompressMultiFrame) in archive ../../../contrib/zstd-cmake/libzstd.a
>>> referenced by zstd_decompress.c:1169 (/root/cksrc/ClickHouse/contrib/zstd/lib/decompress/zstd_decompress.c:1169)
>>>               zstd_decompress.c.o:(ZSTD_decompressMultiFrame) in archive ../../../contrib/zstd-cmake/libzstd.a
>>> referenced by zstd_decompress.c:1169 (/root/cksrc/ClickHouse/contrib/zstd/lib/decompress/zstd_decompress.c:1169)
>>>               zstd_decompress.c.o:(ZSTD_decompressBegin_usingDDict) in archive ../../../contrib/zstd-cmake/libzstd.a
>>> referenced by zstd_decompress.c:1169 (/root/cksrc/ClickHouse/contrib/zstd/lib/decompress/zstd_decompress.c:1169)
>>>               zstd_decompress.c.o:(ZSTD_decompressStream) in archive ../../../contrib/zstd-cmake/libzstd.a
>>> referenced by zstd_decompress.c:1540 (/root/cksrc/ClickHouse/contrib/zstd/lib/decompress/zstd_decompress.c:1540)
>>>               zstd_decompress.c.o:(ZSTD_decompressStream) in archive ../../../contrib/zstd-cmake/libzstd.a

ld.lld: error: undefined symbol: ZSTD_copyDDictParameters
>>> referenced by zstd_decompress.c:1177 (/root/cksrc/ClickHouse/contrib/zstd/lib/decompress/zstd_decompress.c:1177)
>>>               zstd_decompress.c.o:(ZSTD_decompressMultiFrame) in archive ../../../contrib/zstd-cmake/libzstd.a
>>> referenced by zstd_decompress.c:1177 (/root/cksrc/ClickHouse/contrib/zstd/lib/decompress/zstd_decompress.c:1177)
>>>               zstd_decompress.c.o:(ZSTD_decompressBegin_usingDDict) in archive ../../../contrib/zstd-cmake/libzstd.a
>>> referenced by zstd_decompress.c:1177 (/root/cksrc/ClickHouse/contrib/zstd/lib/decompress/zstd_decompress.c:1177)
>>>               zstd_decompress.c.o:(ZSTD_decompressStream) in archive ../../../contrib/zstd-cmake/libzstd.a

ld.lld: error: undefined symbol: ZSTD_createDDict_advanced
>>> referenced by zstd_decompress.c:1269 (/root/cksrc/ClickHouse/contrib/zstd/lib/decompress/zstd_decompress.c:1269)
>>>               zstd_decompress.c.o:(ZSTD_DCtx_loadDictionary_advanced) in archive ../../../contrib/zstd-cmake/libzstd.a
>>> referenced by zstd_decompress.c:1269 (/root/cksrc/ClickHouse/contrib/zstd/lib/decompress/zstd_decompress.c:1269)
>>>               zstd_decompress.c.o:(ZSTD_DCtx_loadDictionary_byReference) in archive ../../../contrib/zstd-cmake/libzstd.a
>>> referenced by zstd_decompress.c:1269 (/root/cksrc/ClickHouse/contrib/zstd/lib/decompress/zstd_decompress.c:1269)
>>>               zstd_decompress.c.o:(ZSTD_DCtx_loadDictionary) in archive ../../../contrib/zstd-cmake/libzstd.a
>>> referenced by zstd_decompress.c:1269 (/root/cksrc/ClickHouse/contrib/zstd/lib/decompress/zstd_decompress.c:1269)
>>>               zstd_decompress.c.o:(ZSTD_DCtx_refPrefix_advanced) in archive ../../../contrib/zstd-cmake/libzstd.a
>>> referenced by zstd_decompress.c:1269 (/root/cksrc/ClickHouse/contrib/zstd/lib/decompress/zstd_decompress.c:1269)
>>>               zstd_decompress.c.o:(ZSTD_DCtx_refPrefix) in archive ../../../contrib/zstd-cmake/libzstd.a
>>> referenced by zstd_decompress.c:1269 (/root/cksrc/ClickHouse/contrib/zstd/lib/decompress/zstd_decompress.c:1269)
>>>               zstd_decompress.c.o:(ZSTD_initDStream_usingDict) in archive ../../../contrib/zstd-cmake/libzstd.a
collect2: error: ld returned 1 exit status
make[2]: *** [src/Common/tests/parallel_aggregation] Error 1
make[1]: *** [src/Common/tests/CMakeFiles/parallel_aggregation.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 85%] Linking CXX static library libclickhouse_functions_gatherutils.a
[ 85%] Built target clickhouse_functions_gatherutils
make: *** [all] Error 2

**Comment by bookeezhou** [comment]
in ARM platform , clickhouse build system can't find zstd.
solve the problem,need dowload zstd and 
make && make install
then build goes ok.

**Comment by alexey-milovidov** [comment]
@abyss7 How does it happen?

**Comment by abyss7** [comment]
I will take a look

**Comment by abyss7** [comment]
@bookeezhou Do you build on a native ARM platform? What is your distribution? What is your cmake configuration command-line?
