### ISSUE TITLE
Strange Behavior, Random Query Result

### ISSUE THREAD

**Issue by mjodeh** [ClickHouse/ClickHouse#11673]
**Describe the bug**
When I run the following query it gives different output event though there is no new data inserted
```
SELECT 
    userId, 
    minIf(eventTime, eventName = 'event1') AS step0_time, 
    arrayFilter(time -> ((step0_time > 0) AND ((time - step0_time) > 0)), groupArrayIf(eventTime, eventName = 'event2'))[1] AS step1_time, 
    step1_time - step0_time AS timeToStep1
FROM 
(
    SELECT 
        userId, 
        eventTime, 
        eventName
    FROM test_db.test
    WHERE (eventName = 'event1') OR (eventName = 'event2')
)
GROUP BY userId
```

* Which ClickHouse server version to use: `20.1.2 revision 54431`
* Which interface to use, if matters: native client & http interface
* `CREATE TABLE` statements for all tables involved
```
 CREATE TABLE test_db.test (`userId` String, `eventTime` UInt32, `eventName` String) ENGINE = MergeTree PARTITION BY toDate(toDateTime(eventTime)) ORDER BY (userId, eventTime) SETTINGS index_granularity = 8192 

```
* Queries to run that lead to unexpected result
The query gives different output on a random manner per run, the data is not touched at all
example outputs I'm getting:

| userId        | step0_tim           | step1_time  | timeToStep1 |
| ------------- |:-------------:| -----:| -----:|
| user1      | 0     | 0     | 0     | 
| user2      |  0      | 0      | 0      | 
| user3       | 1591611996      | **1592028051**      | **416055**       |

another output example
| userId        | step0_tim           | step1_time  | timeToStep1 |
| ------------- |:-------------:| -----:| -----:|
| user1      | 0     | 0     | 0     | 
| user2      |  0      | 0      | 0      | 
| user3       | 1591611996      | **1591618927**      | **6931**       |

The wrong is for **user3**

Any help would be appreciated!

**Comment by mjodeh** [comment]
the solution is here https://github.com/ClickHouse/ClickHouse/issues/2739

**Comment by arashkhavari** [comment]
```sql
SELECT 
    userId, 
    minIf(eventTime, eventName = 'event1') AS step0_time, 
    arrayFilter(time -> ((step0_time > 0) AND ((time - step0_time) > 0)), groupArrayIf(eventTime, eventName = 'event2'))[1] AS step1_time, 
    step1_time - step0_time AS timeToStep1
FROM 
(
    SELECT 
        userId, 
        eventTime, 
        eventName
    FROM test_db.test
    WHERE (eventName = 'event1') OR (eventName = 'event2') ORDER BY eventTime
)
GROUP BY userId
```
**ORDER BY** sort the layer 2 select execution and fix this issue

**Comment by mjodeh** [comment]
Thanx @arashkhavari
