### ISSUE TITLE
Using `path` and disk's path causing problems

### ISSUE THREAD

**Issue by fr05t1k** [ClickHouse/ClickHouse#11678]
**Use case**
```
    <storage_configuration>
        <disks>
            <disk_hdd>
                <path>/var/lib/clickhouse-hdd/</path>
            </disk_hdd>
            <disk_ssd>
                <path>/var/lib/clickhouse-ssd/</path>
            </disk_ssd>
        </disks>
        <policies>
            <moving_to_ssd>
                <volumes>
                    <hot>
                        <disk>disk_ssd</disk>
                    </hot>
                    <cold>
                        <disk>disk_hdd</disk>
                    </cold>
                </volumes>
                <move_factor>0.2</move_factor>
            </moving_to_ssd>
        </policies>
    </storage_configuration>
    <!-- Path to data directory, with trailing slash. -->
    <path>/var/lib/clickhouse-hdd/</path>
```
If we use such a configuration it will produce an error:
```
2020.06.15 05:54:59.867745 [ 195173 ] {} <Error> Application: DB::Exception: Part `201811_0_2998_6` was found on disk `default` which is not defined in the storage policy: Cannot attach table `default`.`clicks` from metadata file
```

Because CH checks `/var/lib/clickhouse-hdd/data/default/clicks/` and CH thinks that this part is located on `default` disk, but storage policy doesn't have `default` disk.

**Describe the solution you'd like**
It's better to check that multiple disks has a same path and don't start server because of bad configuration.

**Comment by vladimir-golovchenko** [comment]
I encountered the same issue after restart *clickhouse-server* service on the node (CH version 20.3.12.112).

My original storage-configuration was borrowed from official doc [Using Multiple Block Devices for Data Storage](https://clickhouse.tech/docs/en/engines/table-engines/mergetree-family/mergetree/#table_engine-mergetree-multiple-volumes).

I could fix it by modifying it this way (the main idea is use *default*-disk instead of *ssd*):

```xml
<yandex>
  <path replace="replace">/var/lib/clickhouse/</path>

  <storage_configuration>
  <disks>
    <!-- Hot storage (SDD) -->
    <default>
      <!-- Its path defined in <path>-tag above. -->
    </default>

    <!-- Cold storage (HDD) -->
    <hdd_1>
      <path>/data/datadisk02/</path>
    </hdd_1>
  </disks>

  <policies>
      <moving_from_ssd_to_hdd>
        <volumes>
          <hot>
            <disk>default</disk>
          </hot>
          <cold>
            <disk>hdd_1</disk>
          </cold>
        </volumes>
        <move_factor>0.1</move_factor>
      </moving_from_ssd_to_hdd>
  </policies>
  </storage_configuration>
</yandex>
```

------------

This configuration _NOT_ work:

```xml
<yandex>
  <path replace="replace">/var/lib/clickhouse/</path>

  <storage_configuration>
  <disks>
    <!-- Do NOT remove this disk. -->
    <default>
      <!-- Its path defined in <path>-tag above. -->
    </default>

    <!-- Hot storage (SDD) -->
    <ssd_1>
      <path>/var/lib/clickhouse/</path>
    </ssd_1>

    <!-- Cold storage (HDD) -->
    <hdd_1>
      <path>/data/datadisk02/</path>
    </hdd_1>
  </disks>

  <policies>
      <!-- Do NOT remove this policy. -->
      <default>
        <volumes>
          <default>
            <disk>default</disk>
          </default>
        </volumes>
      </default>

      <moving_from_ssd_to_hdd>
        <volumes>
          <hot>
            <disk>ssd_1</disk>
          </hot>
          <cold>
            <disk>hdd_1</disk>
          </cold>
        </volumes>
        <move_factor>0.1</move_factor>
      </moving_from_ssd_to_hdd>
  </policies>
  </storage_configuration>
</yandex>
```

**Comment by alexey-milovidov** [comment]
It is not allowed to use identical paths for different disks,
the path for any non-default disks should not collide with the default path.

**Comment by Another2033** [comment]
“default” disk path should be provided in <path> not it <stroage_configuration>
if i do like https://github.com/ClickHouse/ClickHouse/issues/11678#issuecomment-686871180 ,this error was printed

**Comment by deemon87** [comment]
I have the same warning, but I have the following configuration:

`<path>/var/lib/clickhouse/</path>`

`<yandex>
      <storage_configuration>
            <disks>
                  <disk_ssd_1>
                        <path>/var/lib/clickhouse/ssd1/</path>
                        <keep_free_space_bytes>1073741824</keep_free_space_bytes>
                  </disk_ssd_1>
                  <disk_hdd_1>
                        <path>/var/lib/clickhouse-hdd1/</path>
                        <keep_free_space_bytes>1073741824</keep_free_space_bytes>
                  </disk_hdd_1>
            </disks>
            <policies>
                  <default>
                        <volumes>
                            <vol_ssd_1>
                                    <disk>disk_ssd_1</disk>
                            </vol_ssd_1>
                        </volumes>
                  </default>
                  <stor_pol_hot_cold_1>
                        <volumes>
                            <vol_ssd_1>
                                    <disk>disk_ssd_1</disk>
                            </vol_ssd_1>
                            <vol_hdd_1>
                                    <disk>disk_hdd_1</disk>
                            </vol_hdd_1>
                        </volumes>
                        <move_factor>0.1</move_factor>
                  </stor_pol_hot_cold_1>
                  <stor_pol_only_ssd_1>
                        <volumes>
                            <vol_ssd_1>
                                    <disk>disk_ssd_1</disk>
                            </vol_ssd_1>
                        </volumes>
                  </stor_pol_only_ssd_1>
                  <stor_pol_only_hdd_1>
                        <volumes>
                            <vol_hdd_1>
                                    <disk>disk_hdd_1</disk>
                            </vol_hdd_1>
                        </volumes>
                  </stor_pol_only_hdd_1>
            </policies>
      </storage_configuration>
</yandex>`

Why do I have this warning if the `path` is different everywhere?
