### ISSUE TITLE
How to connect to zookeeper under safe mode (kerberos authentication required)

### ISSUE THREAD

**Issue by wallace-clickhouse** [ClickHouse/ClickHouse#11708]
I want to configure replications in my clickhouse cluster.For the zookeeper configuration,I find only the zookeeper host and port information is needed in metrika.xml, is that to say that the clickhouse node can visit zk only on unsafe mode?
So if I want to connect to a zookeeper under safe mode which requires kerberos authentication,how can I do?
Thank you!

**Comment by filimonov** [comment]
https://github.com/ClickHouse/ClickHouse/issues/5747
