### ISSUE TITLE
Add support for inline query optimizer hints

### ISSUE THREAD

**Issue by siradjev** [ClickHouse/ClickHouse#11719]
**Use case**
Hints is quite popular method of traditional DBs of tweaking particular queries or hardcoding specific behavior (e.g. full scan vs index scan, pushing predicates, merging views, transformation, force execute on coordinator). 
Many of those are implemented as session parameters in clickhouse, however there are frequently cases when it is not possible to use them:
- multi-statement cannot be passthrough across multiple "hops" one of them is stateless (app->clickhouse-proxy->clickhouse )
- session is not supported in driver
- application users can only submit query or part of queries
- BI-tool imposing specific limitations

**Describe the solution you'd like**
Simplest way is to allow special syntax inside comments with special character ('+') after the first keyword (similar to Oracle, Vertica, other clones of those). 

```
select /*+ max_thread=1 max_block_size=100 */ * from system.parts; -- could be space delimited as comma can be in value of parameter

insert /*+ max_insert_threads=4 min_insert_block_size_rows=2000 max_thread=16 max_block_size=100 */ into test_parts 
select * from system.parts; -- could be space delimited as comma can be in value of parameter
```

Another way could be to use special syntax, but that would impact SQL compliance, e.g. OPTION keyword for MSSQL (https://docs.microsoft.com/en-us/sql/t-sql/queries/option-clause-transact-sql?view=sql-server-ver15). I'd rather use this reference as example of how NOT to do it. 

**Describe alternatives you've considered**
There are no real alternatives to this solution except usage of session variables, but that's not true alternative, rather a workaround and not a complete one. 

**Additional context**
Using hints open the way to allow users optimizing below use cases with further improvements:
- Forcing more than one level of queries to run on distributed nodes. Example, typically "argMax-style" additional subquery is used to make sure latest data is used with ReplacingMergeTrees to avoid using FINAL. Current use of this pattern forces nearly raw data to be sent to coordinator for processing. By using /*+ run_distributed=1 */ in this subquery it could be forced to run on shard and then sending reduced data set to coordinator. 
- Playing with individual thread counts, memory limitations, block-size on each level of subquery
- Forcing hash-joins vs merge-joins on specific table pairs
- Force index usage on specific subquery
- Prohibit moving certain conditions/conditions on certain fields to prewhere (https://t.me/clickhouse_ru/11343)
- Custom "help" to optimizer through using of cardinality hints (https://oracle.readthedocs.io/en/latest/sql/hints/types/miscellaneous.html) or likely/unlikely hints on conditions (https://docs.omnisci.com/latest/5_dml.html#likely-unlikely)

**Comment by filimonov** [comment]
It seems you're trying to reinvent SETTINGS clause.

Try 
```sql
select * from system.parts settings max_threads=1, max_block_size=100;
```

Does it satisfy your requirements?

**Comment by siradjev** [comment]
> It seems you're trying to reinvent SETTINGS clause.
True, I was not aware of this clause, as when it was discussed on previous meetup there was no mention of this functionality. Seems clickhouse went with "MSSQL-way", which is good enough as it still covers major use-cases. 

> Does it satisfy your requirements?
If it can be further enhanced to be applied on individual subqueries that would work too and further enhancements/constructs can be built on top of SETTINGS clause with further improvements. 

> Also most of the drivers can send the settings with query w/o making adjustments inside the query itself.
We had to ask driver maintainers for improvement, I guess it's true for most popular languages. 

I believe this improvement can be closed as-is, since it's already implemented in another specific way.

**Comment by 4ertus2** [comment]
It's quite clear that it's posible to translate `/*+ <some> */` into `SETTINGS <some>` at query parser level. The only reason for this as I know is to pass queries through BI system that allows comments and do not allow our `SETTINGS` syntax.

**Comment by filimonov** [comment]
@4ertus2 but it looks like @siradjev is happy with Settings, so let's keep it open for now and collect feedback.

If you need that feature and `settings` clause does not satisfy your requirements - please send a commect here with your usecase.
