### ISSUE TITLE
Consider implementing ILIKE operator

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#11710]
Case insensitive variant of LIKE.
It should respect UTF-8 and work similar to `positionCaseInsensitiveUTF8`.

It is not in SQL standard but people who work with Postgres will appreciate that.

**Comment by siradjev** [comment]
It may be better to use ANSI SQL way using COLLATE settings of db/table/column/session/statement, even if in limited way in the beginning supporting only _CI suffix in statement level itself.

https://oracle-base.com/articles/12c/column-level-collation-and-case-insensitive-database-12cr2
https://stackoverflow.com/questions/1831105/how-to-do-a-case-sensitive-search-in-where-clause-im-using-sql-server
https://stackoverflow.com/a/18627707

Postgres use of ILIKE was there as a workaround to compensate the lack of _CI collations in the first place.

**Comment by alexey-milovidov** [comment]
BTW, we support COLLATE modifier for ORDER BY.
It's also nice to implement it for LIKE, but the performance of proper unicode collation algorithm will be much worse.

**Comment by siradjev** [comment]
It could be hardcoded on implementation level to replicate ILIKE for a start. 
Essentially, ILIKE is syntactic sugar, and adding it to syntax for sake of optimizing `lower(col) like '%searchtxt%'` sounds strange. It sounds more logical to fix it on the code level, to have "lower(xxx) like" and "upper (xxx) like" optimized. Most ORMs/smaller BI tools also generate code in this dialect (either COLLATE or "lower(col) like").

**Comment by filimonov** [comment]
> sake of optimizing lower(col) like '%searchtxt%' sounds strange

When you type lit of queries by hand it is really useful. Also it should give some performance gain as two operations can be executed in single round without copiing.

> Most ORMs/smaller BI tools also generate code in this dialect

Because ILIKE is not a part of sql standard.

**Comment by myrrc** [comment]
I'll take that.
