### ISSUE TITLE
Asynchronous metrics on data volume

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#11714]
We can add metrics on total amount of rows and bytes in MergeTree tables.
It involves lock of data parts and iteration over all of them. We can make it more efficient by maintaining additional variable with that value.

**Comment by ucasFL** [comment]
Hi, I implemented this, but I don't know how to test it...... @alexey-milovidov

**Comment by alexey-milovidov** [comment]
Just check that metrics exist and show non-zero value if there are MergeTree tables with some data.

**Comment by ucasFL** [comment]
I found I totally misunderstand this task, I thought we need to use two variables to track total bytes and total rows of `Committed` parts in each MergeTree table, so when invoke `totalRows` and `totalBytes`, just return these two variables value, like [https://github.com/ClickHouse/ClickHouse/blob/master/src/Storages/StorageMemory.h#L100](https://github.com/ClickHouse/ClickHouse/blob/master/src/Storages/StorageMemory.h#L100), however, it doesn't.

**Comment by alexey-milovidov** [comment]
That's the most of this task. Then we should add metrics on total data volume into AsynchronousMetrics.
I think you have understand everything right.
