### ISSUE TITLE
Add custom "-Map" aggregate function combinator

### ISSUE THREAD

**Issue by siradjev** [ClickHouse/ClickHouse#11721]
**Use case**
Currently, there are sumMap/minMap/maxMap aggregate function combinator that allows calculating aggregated values in bins. 
It's quite a frequent use case considering lack of window functions. Examples include:
- Multiple random attributes are stored in row with id/values (and attributes may not match across rows), when custom aggregate function across attributes is needed with some precondition (e.g. median, quantile, etc.). Currently, the only way to achieve is to do fold/unfold with 2 level subqueries or double pass over an array with further arrayReduce. https://t.me/clickhouse_ru/148608
- Reducing two arrays for by keys as in `arrayReduce('medianMap', arr1, arr2);` (basically in-row custom  function), allowing making different aggregations with one fold/unfold loop. 
- Getting top-X% queries (e.g. top 10 percentile, or top-10) by multiple dimensions, now requires running separate subqueries with array group to calculate threshold value. 

**Describe the solution you'd like**
Having -Map generic aggregate function combinator would allow much simpler understanding and creating of multi-dimensional aggregates. 
Alternative could be defining arrayReduceByKeys function that would take two input arrays and bin them by keys array with custom aggregation function as discussed in https://t.me/clickhouse_ru/148584. 

**Additional context**
#4933 may address this request partially, or vice versa. -Map combinator would be more concise syntax (given already existing functions)
https://t.me/clickhouse_ru/148608

**Comment by siradjev** [comment]
Hardcoding escalated further :) 
https://clickhouse.tech/docs/en/sql-reference/aggregate-functions/parametric-functions/#summapfilteredkeys-to-keepkeys-values
```
sumMapFiltered(keys_to_keep)(keys, values) 
Same behavior as sumMap except that an array of keys is passed as a parameter. This can be especially useful when working with a high cardinality of keys.
```

**Comment by crakjie** [comment]
@siradjev I'm also looking for this kind of processing.
I think the following exemple could be a work around for sumMapFiltered
```
WITH arrayFilter(x -> ((x.2) = 'abc'), arrayZip(Array1, Array2, ArrayMetrics)) AS filteredArrays
SELECT sumMap(filteredArrays.1, filteredArrays.3)
FROM Table
```
It's filter both array by the values of a third array and apply sumMap.

**Comment by UnamedRus** [comment]
Implemented by https://github.com/ClickHouse/ClickHouse/pull/24539, starting from 21.12

**Comment by alexey-milovidov** [comment]
@UnamedRus But the quality of implementation is in question.
