### ISSUE TITLE
TTL don't work

### ISSUE THREAD

**Issue by byx313** [ClickHouse/ClickHouse#11723]
ClickHouse version:19.9.5.36
In 15 June,I alter our SummingMergeTree engine table to add the TTL expression,and now out table is
![image](https://user-images.githubusercontent.com/37653716/84844216-814d9500-b07c-11ea-95ea-c4477857d8cf.png)
But two days pass,I don't see our expried data deleted.
Many thanks for reply!

**Comment by den-crane** [comment]
Check this https://github.com/ClickHouse/ClickHouse/issues/6462

**Comment by byx313** [comment]
> Check this #6462

"TTL works only for new parts after alter."
Our TTL time is 30 days,is it mean that only 30 days after my 'alter' action data  will be drop?

**Comment by den-crane** [comment]
Yes. And try some newer CH version. For example 19.14.11.16 or other stable https://repo.yandex.ru/clickhouse/deb/stable/main/ or lts https://repo.yandex.ru/clickhouse/deb/lts/main/ 

19.9.5.36 is out of support

**Comment by byx313** [comment]
> Yes. And try some newer CH version. For example 19.14.11.16 or other stable https://repo.yandex.ru/clickhouse/deb/stable/main/ or lts https://repo.yandex.ru/clickhouse/deb/lts/main/
> 
> 19.9.5.36 is out of support

Our environment is centos6,so 19.9.5.36 is our newest version
Thanks again for reply

**Comment by den-crane** [comment]
>Our environment is centos6,so 19.9.5.36 is our newest version

Are you sure? I think newer versions should work as well https://repo.yandex.ru/clickhouse/rpm/stable/x86_64/

**Comment by byx313** [comment]
> > Our environment is centos6,so 19.9.5.36 is our newest version
> 
> Are you sure? I think newer versions should work as well https://repo.yandex.ru/clickhouse/rpm/stable/x86_64/

I think we have made the mistake.
We get rpm from [https://packagecloud.io/Altinity/clickhouse](url),and in this page the newest for centos6 is 19.9.5.36 so we think the newer version is work only for centos7.
We will try the newer version!
