### ISSUE TITLE
Improve performance of FINAL modifier for Collapsing/Replacing MergeTree

### ISSUE THREAD

**Issue by siradjev** [ClickHouse/ClickHouse#11722]
**Use case**
Clickhouse is a very good DB for load-and-analyze type of pattern, but its lack of primary key enforcement constraints limits it for typical monitoring case, when there is a need to query both most-recent (live) and historical data at the same time.
Some implementation is available with Replacing MergeTree allowing to collapse rows with same keys, however there is no 100% assureness on avoiding duplicates when data is flowing live, except using FINAL clause. 
Other descriptions of use case are in #8223,  #5125.  
Parallel FINAL #10463 is not really the solution here, since data may be queried from 3 month ago to today spanning across billions of rows. 

**Describe the solution you'd like**
1. Allow to specify parameter to not-do merge across partitions (merge-tree setting or system setting). This will let CH to assume that each partition already owns unique set of PKs. 
1. Skip merging of partitions when FINAL is specified IF (there is only one active part left in partition AND part.level>0 (has been merged at least once))

This will guarantee that previous days/hours/weeks/month data that has been optimized and merged to single part (by OPTIMIZE FINAL for partition that could be managed by ETL/externally by whatever is loading the data) won't require additional merges, and merge will only be done on most recent partition for which the data is being loaded. 

**Describe alternatives you've considered**
There are many alternatives in other issues #8223,  #5125, but they don't seem to be feasible for analytics DB. 
There is no real way to do it relatively easier in application.

**Comment by filimonov** [comment]
> specify parameter to not-do merge across partitions

You can just add partition key to your ORDER BY

**Comment by siradjev** [comment]
> You can just add partition key to your ORDER BY

True. Could be achieved this way too at the expense of minor increase of primary key. 

However, it would still worth to have it in merge-tree setting level, as some people may expect this behavior to be default (consistent behavior and result for background merges/optimize and merges caused by select...final).  https://t.me/clickhouse_ru/166957

**Comment by filimonov** [comment]
> IF (there is only one active part left in partition AND part.level>0 (has been merged at least once))

BTW: Why `AND part.level>0` (has been merged at least once)? To remove duplicate arrived inside a single select?

**Comment by siradjev** [comment]
> To remove duplicates arrived inside a single select?

To remove duplicates arrived within single *insert batch*.
As per my understanding data collapsing is not made during insert itself, so a single part that has just been inserted may have duplicates.

**Comment by alexey-milovidov** [comment]
Both variants will be good to implement and not very hard... Let's do it.
This task is currently not in our nearest plans.
