### ISSUE TITLE
Support RENAME COLUMN for sorting keys

### ISSUE THREAD

**Issue by YiuRULE** [ClickHouse/ClickHouse#11731]
(you don't have to strictly follow this form)

**Use case**
Right now, the `ALTER TABLE RENAME COLUMN` command doesn't work for sorting and partition key, it could be great if this command accept also to rename columns used as a key as a renaming of a key affect only his metadatas and not the actual sorting/partition.

**Comment by alexey-milovidov** [comment]
I don't think it's easy to do, let's ask @alesapin who has implemented RENAME COLUMN.

**Comment by alexey-milovidov** [comment]
Yes, this is not easy to do.
