### ISSUE TITLE
Datatype Time, why not?

### ISSUE THREAD

**Issue by calebeaires** [ClickHouse/ClickHouse#11747]
Time, without date, is a common data to analyze. Why Clickhouse does not have this datatype on its core?

**Comment by filimonov** [comment]
Actually you can't fit with Time into 2 bytes (65536 seconds = 18h), and if you will use 4bytes for that - you get to DateTime (rounded to some 'zero' day).

Check [toTime](https://clickhouse.tech/docs/en/sql-reference/functions/date-time-functions/#totime) function. 

Sidenote: it is possible to add such a type (will still use 4b and works almost the same as DateTime on the storage level, but will be presented without date part).

**Comment by alexey-milovidov** [comment]
Workaround: use UInt32 with the number of seconds after midnight.
