### ISSUE TITLE
Deleting rows causes Bad size of marks file error

### ISSUE THREAD

**Issue by kanadaj** [ClickHouse/ClickHouse#11740]
**Describe the bug**
After executing the following command:
```
ALTER TABLE table DELETE WHERE pageviews < '2020-06-17'
```
The query executes and running `SELECT COUNT(*) FROM pageviews` runs correctly; however, running the following query on the table throws an error:
```
SELECT DISTINCT topic_id, uniqExact(content_id) content_count FROM pageviews WHERE user_id = 1 GROUP BY topic_id
```

The error is as follows:
```
Code: 246, e.displayText() = DB::Exception: Bad size of marks file '/var/lib/clickhouse/data/default/pageviews/20191222_0_21_2_46/content_id.null.mrk2': 0, must be: 4440: While executing MergeTreeThread (version 20.3.5.21 (official build))
```

**How to reproduce**
* ClickHouse 20.3.5.21 via Docker in Kubernetes
* Any interface
* Table is a ReplicatedMergeTree

From what I've noticed, the issue happens with any ReplicatedMergeTree regardless of schema. The delete operation involved deleting approximately 170 million rows.

I can't see any errors in the server logs for the actual delete command, so it just seems like the files in question aren't updated as intended?

**Comment by kanadaj** [comment]
Restarting the server resulted in even more errors; had to resort to setting force_restore_data but I imagine deletes normally shouldn't have to do it.

**Comment by alesapin** [comment]
Hi. To investigate the issue, please, provide server logs, table schema, and data samples if possible. Also, I recommend you to update to the latest 20.3 version, we had several fixes for mutations since 20.3.5.

**Comment by jerome-leclercq-contentsquare** [comment]
we have the same problem in 20.3.8.53 using non-replicated CollapsingMergeTree
however using 20.3.12 seems to work fine

**Comment by geronsv** [comment]
We have the same problem in 20.3.10. Upgrading to 20.3.17 revision 54433 did not help.

**Comment by filimonov** [comment]
@geronsv @jerome-leclercq-contentsquare  @kanadaj 

Guys, can some of you help to build a reproducible case (`CREATE TABLE ...; INSERT INTO ... ; ALTER ... ;`)?

'Me too' messages don't help too much...
