### ISSUE TITLE
GROUP BY capable of aggregating a single row to multiple groups

### ISSUE THREAD

**Issue by adrian17** [ClickHouse/ClickHouse#11752]
Originally asked in
https://stackoverflow.com/questions/61911990/way-to-achieve-overlapping-group-by-groups-with-correct-subtotals-in-clickhouse/

**Use case**

Example use cases:
- given a table containing answers to a survey with single- and multiple choice question (eg "which colors do you like? red/green/blue", "which devices do you own? pc/phone/tablet") stored as `Array(UInt8)` or `Array(String)` column per question, make a query resulting in a single table answering "how many users like red/gree/blue"?
- given a similar table, make a more complex query (partially user-defined via some interface) answering questions like "how many users like red and own a pc, compared to users who like blue and own a tablet or phone?" or "how many users were born between 1970 and 1990, compared to 1980 and 2000?"

Note that in all these cases, the groups are overlapping - a single user may need to be aggregated into multiple groups.

Additionally: these queries might use `ROLLUP` or `CUBE` and use more grouping levels (group by date, country, gender... maybe by 2-3 user-defined grouping sets at once)

**Solutions I tried**
All my current solutions are based on `arrayJoin`, for example:
for use case 1:
```
select
	date,
	arrayJoin(liked_color) as color,
	uniqExact(user) as num_users,
	sum(other_metrics) as other_metrics
from survey
group by date, color;
```

for use case 2:
```
select
	date,
	arrayJoin(arrayConcat(
		if(has(liked_color, 'red') and has(devices, 'pc'), [1], []),
		if(has(liked_color, 'blue') and (has(devices, 'tablet') or has(devices, 'phone')), [2], []),
		if(born between '1970-01-01' and '1990-01-01', [3], []),
		if(born between '1980-01-01' and '2000-01-01', [4], [])
	)) as custom_group,

	uniqExact(user) as num_users,
	sum(other_metrics) as other_metrics
from survey
group by date, custom_group;
```

They _do_ work for simple cases, but have two big issues:
- `arrayJoin` seems quite slow in general
- as soon as you use `ROLLUP`, `CUBE` or `WITH TOTALS`, the partial aggregations completely "break" - since `arrayJoin` "duplicates" rows, the same row will get added into the totals several times and `other_metrics` will be too big. This is not a bug - it's technically what I asked for in SQL, but not at all what I actually want. This forces me to either make separate queries for partial sums, or add extra bookkeeping into queries to only add each "duplicated row" into totals once - which slows down the query even more.

**Describe the solution you'd like**
Something that aggregates by each _element_ of the array. In other words, semantically similar to `arrayJoin` + `group by`, except when combined with `rollup` or `totals` the row would still count only once.
In SQL syntax, maybe something like `group by date, UNPACK liked_color` or new variant of `arrayJoin`?

**Comment by alexey-milovidov** [comment]
Recently we've added support for GROUP BY GROUPING SETS ...
But it does not help with this specific issue.

A workaround is to just run more than a single query.

An extension for SQL specifically for this case does not sound easy.
Maybe better to close?
