### ISSUE TITLE
Optimize Table FINAL bug

### ISSUE THREAD

**Issue by vngrv** [ClickHouse/ClickHouse#11758]
When i wan't optimaze my table in syntax:

`OPTIMIZE TABLE nameTable PARTITION toYYYYMMDD(today()-1) FINAL;`
I have this error.
`Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 68: FINAL. Expected one of: AND, OR, token, NOT, BETWEEN, LIKE, IS, NOT LIKE, IN, NOT IN, GLOBAL IN, GLOBAL NOT IN, QuestionMark (version 20.3.11.97)`

Don't understand what i must do. Also yesterday it works but after updating DB its wrong. I did not find anything new in the documentation. Maybe i doing something wrong?

(you don't have to strictly follow this form)

**Describe the bug**
A clear and concise description of what works not as it is supposed to.

**How to reproduce**
* Which ClickHouse server version to use
* Which interface to use, if matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

**Expected behavior**

**Error message and/or stacktrace**

**Additional context**

**Comment by filimonov** [comment]
Duplicate #10212

You can't use expressions in PARTITION clause anymore
It was intentionally removed in #8835
