### ISSUE TITLE
Clean znodes while DROP PARTITION or TRUNCATE table by providing settings or clause

### ISSUE THREAD

**Issue by slimtom95** [ClickHouse/ClickHouse#11779]
**Use case**
Most of our reports partitioned by day, and every day we need to replace 1-30 (may be even more) previous days of data per table from new calculated sources. In order to minimize etl interruption, we use a temporary table to do this, truncate, insert, and then replace partitions with the product table. Using this pattern, we saw truncates slow down every day ( also, the znodes growing is worrying) .

In current design, drop partition doesn't remove partition znodes in block_numbers for some racing consideration. #3322 #6267 But as a user, we do know, with our current usage pattern, insert/drop racing cannot happen. 

**Describe the solution you'd like**
Please consider to provide the ability to **let user control whether the DROP/truncate can safely delete zk partition nodes** as well.

**Describe alternatives you've considered**
Add setting like `enable_drop_partition_clean_znodes`. With this settings enabled, DROP PARTITION/TRUNCATE will delete related partition within block_numbers... or
Add clause like `TRUNCATE TABLE .... [FINAL]` ...

**Comment by filimonov** [comment]
If I understand correctly in your case you can just recreate the temporary table (or create new one each time) instead of truncating/dropping partition in a 'stale' temporary table.

**Comment by slimtom95** [comment]
Thanks for the advice. However, recreating table demands maintaining latest table definition in the etl workflow, i.e.Replicated Engine parameters, order by keys, which is not our optimal solution. (also, for security, we forbade using drop keyword
