### ISSUE TITLE
Kinesis Support

### ISSUE THREAD

**Issue by mauidude** [ClickHouse/ClickHouse#11776]
I would like to be able to consume data from AWS Kinesis the same way it is done with Kafka. It would make it easier for those working in AWS to quickly integrate with ClickHouse without having to create and maintain EC2 instances running Kafka.

**Comment by filimonov** [comment]
It can be implemented but priority is low: it's a vendor-specific message system (like Google PubSub).

Currenlty support for RabbitMQ is in development, I would say the [Pulsar](https://github.com/ClickHouse/ClickHouse/issues/4226) is the most probable next candidate. 

Others open-source includes: NATS, NSQ, hmbdc, Synapse, Redis pub/sub, ActiveMQ

But clickhouse is an open-source project and you can collaborate / find a developer who can create that, and just send a PR.

**Comment by filimonov** [comment]
> without having to create and maintain EC2 instances running Kafka.

Actually AWS also offers managed Kafka: https://aws.amazon.com/msk/

**Comment by maxkferg** [comment]
@alexey-milovidov 
This could be a great feature for the Clickhouse project in general. 

Amazon Kinesis is widely used and having an officially supported Kinesis connector is probably an essential feature for anyone using Kinesis

**Comment by alexey-milovidov** [comment]
The current plan is to normalize the support for Kafka first and to forget about Kinesis until it is done.
