### ISSUE TITLE
No clear motivation of too big timeouts in Zookeeper config in docs

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#11781]
https://clickhouse.tech/docs/en/operations/tips/#zookeeper

initLimit & maxSessionTimeout about 16h. What is motivation for that?

**Comment by alexey-milovidov** [comment]
> maxSessionTimeout

It is the maximum value that client may request and the server will accept.
It is Ok to have high `maxSessionTimeout` on server to allow clients to work with high session timeout if they want.
But we request session timeout of 30 seconds by default (you can change it with `session_timeout_ms` in ClickHouse config).

**Comment by alexey-milovidov** [comment]
> initLimit

Yes, it is the actual value, we this value in our ZK config.

**Comment by alexey-milovidov** [comment]
The link 
http://hadoop.apache.org/zookeeper/docs/current/zookeeperAdmin.html
in documentation is outdated, 
@BayoNet need to replace.

**Comment by alexey-milovidov** [comment]
So we have 60 000 seconds for `initLimit`, that seems wrong.
Maybe admins just set this value to be large enough from despair.

**Comment by alexey-milovidov** [comment]
```
velom, [02.07.20 15:48]
[In reply to Alexey Milovidov]
мы когда то подбирали эти параметры, чтобы zk хотя бы работал
```

**Comment by alexey-milovidov** [comment]
I've edited the page (english).
@BayoNet @filimonov Could you please update other languages if you like?

**Comment by filimonov** [comment]
https://github.com/ClickHouse/ClickHouse/commit/4d01fb3cbce2971f19a66ac97e85092523487125

**Comment by filimonov** [comment]
Increasing `initLimit` may be desired as the size of the snapshot can be quite big. See https://efod.se/zookeeper-initlimit/
The value of `initLimit` should be reasonably big to give time to download the snapshot. 

But to 16h sounds too drastic -  so if it can't sync up from snapshot it will hang for 16h  before throwing 'timeout' exception.

From one of the reports:

> ...when all zookeeper pods came-up simultaneously during startup they struggled to form a quorum because every pod saw its peers as not available. Within few pod restarts they eventually all form a quorum but with 16hrs to wait for a quorum, the pods never restarted and they keep waiting and waiting.

**Comment by alexey-milovidov** [comment]
We usually have snapshot size in a range of 10..30 GiB, the worst case network between our servers is 1Gbit, if we consider it overloaded, so download rate will be 50 MB/sec, the download will take 600 seconds.

I've cut two zeros here: https://github.com/ClickHouse/ClickHouse/commit/5cc886b5ba97494a98ce5fa8d00668ce77b9f1d0
