### ISSUE TITLE
How to share data among readonly replicas/computation nodes

### ISSUE THREAD

**Issue by slimtom95** [ClickHouse/ClickHouse#11780]
In order to handle the expected high load during some peak period like Black-Friday in retailing, we may  
 need to prepare more machines and launch more replicas, this means preparing more data copies ahead.
With distributed file system storage, I wonder is there any way to not copy even more data, but to share them among the new launched nodes? These nodes can be read-only or computation-only.

**Comment by alexey-milovidov** [comment]
It is possible with the experimental "zero-copy replication" option:
https://clickhouse.com/docs/en/operations/storing-data/#zero-copy

Although I don't recommend it for production usage, it's better to set up full replicas.
