### ISSUE TITLE
How to configure different Kafka clusters in clickhouse ?

### ISSUE THREAD

**Issue by hoseiney** [ClickHouse/ClickHouse#11849]
we have 2 Kafka clusters, in one of them we are setting up SASL security and another one does not have it.
The Kafka configuration is global, how we should deal with different Kafka cluster configuration ?

**Comment by filimonov** [comment]
You can make different configurations per topic in config.xml, like that:

```
<yandex>
    <kafka>
      <!-- global configuration -->
    </kafka>

    <kafka_events>
     <!-- configuration for topic 'events' -->
    </kafka_events>

    <kafka_users>
     <!-- configuration for topic 'users' -->
    </kafka_users>
</yandex>
```

Bit more flexible solution for that (passing any rdkafka settings during table creation) is planned.

**Comment by hoseiney** [comment]
it is good to have customized config for each topic
but we are using Debezium and topics name contain dot 
for example : mysql.users 
can we have this config ?
```
<kafka_mysql.users>
</kafka_mysql.users>
```

**Comment by filimonov** [comment]
No i think it will not work :\ Dot has a special meaning in used XML parser.
