### ISSUE TITLE
is there any configuration to change the deafult port of clickhouse-client?

### ISSUE THREAD

**Issue by wallace-clickhouse** [ClickHouse/ClickHouse#11850]
I find if I change the default port(such as 9000 for TCP) of the server,I must add parameter "--port xx" to connection to the server with clickhouse-client.
So is there any parameter which can be configured for clickhouse-client to change the default port,which can lead to no need of adding parameter "--port xx"?
Thank you!

**Comment by filimonov** [comment]
Just put a line `<port>4444</port>` inside /etc/clickhouse-client/config.xml

```
clickhouse-client 
ClickHouse client version 20.5.1.3716 (official build).
Connecting to localhost:4444 as user default.
````

**Comment by wallace-clickhouse** [comment]
OK, verified! It's fine.Thanks!
Can this directory '/etc/clickhouse-client/config.xml' be configured to an other directory?

**Comment by den-crane** [comment]
> OK, verified! It's fine.Thanks!
> Can this directory '/etc/clickhouse-client/config.xml' be configured to an other directory?

yes it can, https://clickhouse.tech/docs/en/interfaces/cli/#configuration_files
