### ISSUE TITLE
Question about the Cluster.h

### ISSUE THREAD

**Issue by wallace-clickhouse** [ClickHouse/ClickHouse#11861]
I find 2 construcation functions of Cluster in Cluster.h file, for the first one,the input parameter is 'config,settings,cluster_name',for the second one,the input patameter is 'settings,names<vector>,username,password,port..'.
My question is why we have these 2 construcation functions.I can understand the first one is firstly to resolve the cluster.xml and then get the cluster info,How about the second one'usage, under what situation, the second construcation function takes effect?
Thank you!

**Comment by azat** [comment]
>under what situation, the second construcation function takes effect?

Used for `remote`:

https://github.com/ClickHouse/ClickHouse/blob/e76941b52cbb722a5b6f4e7252df58ba14d8d910/src/TableFunctions/TableFunctionRemote.cpp#L179-L187

**Comment by wallace-clickhouse** [comment]
How can I reference extern variables defined in Server.h and initialized in Server.cpp to Cluster.cpp.Because I am trying to achieve a feature,for which I need to initialize the extern variables in Server.cpp once the  server starts up,and then  I want get the variable values and reference in Cluster.cpp at anytime while the server is runnning. I have tried to achieve it by '#include<server/Server.h>' in Cluster.cpp.However compiler reported 'No such file or directory' error.
So Can you give me some instructions? Thank you very much!

**Comment by azat** [comment]
>How can I reference extern variables defined in Server.h and initialized in Server.cpp to Cluster.cpp.

So if I understand you right, then you trying initialize variables that are already initialized in Server.cpp, in this case you will get multiple declarations error at the end

>I have tried to achieve it by '#include<server/Server.h>' in Cluster.cpp.However compiler reported 'No such file or directory' error.

Yes, because `programs` are not in the include path for the common code I guess.

>So Can you give me some instructions?

Maybe you can share what you trying to do?

P.S. I don't see any extern/static variables in `Server.h`

**Comment by wallace-clickhouse** [comment]
@azat Thank you for your reply!
My scenario is that I don’t want to configure the clear text password into the cluster configuration file metrika.xml, so I designed to call an external interface to get the password when starting the database, and then the password is kept in memory during the database server runninng, when distributed query, assign the password in memory to the password variable in Cluster.cpp to avoid reading from metrika.xml. The reason for not calling the external interface to obtain the password in Cluster.cpp is to worry about performance problems when distributed query everytime. Do you have any good suggestions?

**Comment by azat** [comment]
> I don’t want to configure the plaintext password into the cluster configuration file metrika.xml

Why you don't want to write it in the file? Setting  permissions to 600 should be secure enough (if you worry about users will not be able to get the cluster topology, then you shouldn't, since there is `system.clusters` table).

>so I designed to call an external interface to get the password when starting the database, and then the password is kept in memory by an extern variable during the database server runninng

Looks hackish.

>The reason for not calling the external interface

What is your "external interface"?

>to obtain the password in Cluster.cpp is to worry about performance problems when distributed query everytime

And I guess now you creates own Cluster for each query? (since you need to pass password and you asked about Cluster constructors) This is also suboptimal, since it will initialize connections every time.

**Comment by wallace-clickhouse** [comment]
Yeah,thank you for your reply.
I don't want to write a plaintext password in the file because my customer doesn't allow me to write plaintext password in any file and will scan my file system to find if plaintext password exists.
"And I guess now you creates own Cluster for each query? (since you need to pass password and you asked about Cluster constructors) This is also suboptimal, since it will initialize connections every time."
I don't need to create cluster for each query,I just want to initialize the password(how to initialize: call a thirdparty interface to obtain the password) as a global variable in somewhere once the server is startted,and when the server resolves the password value from metrika.xml in the construction method
"Cluster::Address::Address(const Poco::Util::AbstractConfiguration & config, const String & config_prefix, UInt32 shard_index_, UInt32 replica_index_) :
    shard_index(shard_index_), replica_index(replica_index_) " ,
I can just change "password = config.getString(config_prefix + ".password", "");" to  "password = _global_password_variable_value_".
In this way, the server doesn't need to call the thirdparty interface every time when it connects to other shards,Thus I think there is less performance influence in the connection establishment process.
How can I achieve this,Can you give me some advise? Thank you!

**Comment by den-crane** [comment]
@wallace-clickhouse did you try to pass a password using from_env ? 
`
<password from_env="SECRET" />`

and then set env variable SECRET for CH process ?

**Comment by wallace-clickhouse** [comment]
@den-crane I want to pass a password by using a global variable,which can avoid writing password in the metrika.xml.But I don't know where to define the global variable is situable.Can you give me some advise? Thank you!
PS:By this way,because I can get the password from a password management service by calling the service interface,it's unnecessary for me to write password(whether encrypted or not) in the metrika.xml.

**Comment by den-crane** [comment]
>password using from_env 
BTW, I never checked is it possible or not. So first thing - check this.

Obviously you need own start script which will prompt for a password then set an environment and will run CH.
Probably the password will be available for root user `ps ewww` , I don't remember the way how to solve this, google it yourself.
