### ISSUE TITLE
ROLLUP and HAVING together (totals_mode = 'after_having_auto')

### ISSUE THREAD

**Issue by igla123** [ClickHouse/ClickHouse#11867]
Hi,

I'm trying to make a query which will return lines with sums, less then some value, in a rollup view.

For instance, for this query:
``` sql
-- totals_mode = 'after_having_auto'
select a, sum(b)
from
(
select 1 a, -100 b
union all
select 2, -200
union all
select 2, -300
union all
select 3, 300
) t
group by a with rollup
having sum(b) < 100
order by a
```

I expect to have:

``` sql
a   sum(b)
------------
0  -600
1  -100
2  -500
```

But I get:

``` sql
a   sum(b)
------------
0  -300
1  -100
2  -500
```

So HAVING is applied after ROLLUP even if I use `totals_mode = 'after_having_auto'` parameter.

Is this correct behavior or did I miss something?
CH version is 19.14.11.16.

Thanks.

**Comment by igla123** [comment]
Hi guys,

Any news about this topic?

Thanks!

**Comment by alexey-milovidov** [comment]
`totals_mode` affects only WITH TOTALS, not WITH ROLLUP / WITH CUBE.

**Comment by alexey-milovidov** [comment]
If you group by single column, you can just replace WITH ROLLUP to WITH TOTALS to get the desired result.

**Comment by igla123** [comment]
Thanks for the info! Unfortunately I group by several columns, so I need rollup(
Any plans for development this feature for WITH ROLLUP?

**Comment by melvynator** [comment]
I haven't seen any issue about implementing it. An alternative solution is to filter based on specific group by conditions and then do rollup, I would use a subquery or cte expression first and then add the filter.
