### ISSUE TITLE
Allow to initialize aggregate function state with given arguments

### ISSUE THREAD

**Issue by akuzm** [ClickHouse/ClickHouse#11866]
i.e., now I can write:
```
select state from (select minState(x) from (select 1 x));
```
This doesn't work when there are other columns, I have to put them under group by which is cumbersome and wasteful.

I want to be able to write:
```
select a, initializeAggregation('minState', b) from (select 1 a, 2 b);
```
The name is by analogy with `finalizeAggregation`, but not sure it's the best.

Currently it can be emulated with arrayReduce, which is not obvious and inefficient:
```
select a, arrayReduce('minState', [b]) from (select 1 a, 2 b);
```

Having a proper feature for this would simplify working with aggregate function states as normal values, like we do for e.g. bitmaps.

**Comment by alexey-milovidov** [comment]
Ok.

> initializeAggregation('minState', b)

Should it have "State" or better to assume that the user wants to create state?

Also I want a function to create empty aggregation state.
Like `emptyAggregation('minState', b)` where `b` is used only for type inference.

**Comment by filimonov** [comment]
One of the usecases:

```sql
CREATE TABLE ... 
(
last_value aggregateFunction(argMax, String, DateTime) DEFAULT arrayReduce('argMaxState', ['lack of value'], [0])
...
)
```

**Comment by amosbird** [comment]
Shouldn't we also implement `emptyAggregation` for this task?

**Comment by hrissan** [comment]
We probably have a use case for `emptyAggregation`.

 Large table is filled via MatView. Target table contains `AggregateFunction(argMin, String, Float64)` and `AggregateFunction(argMax, String, Float64)` columns, but they make sense for around 1% of rows, which are easily determined by condition depending only on row.

We try to optimize insert speed and disk size by using

```
       initializeAggregation('argMinState', if(condition, key, ''), if(condition, value, 0))
```

It works 1.5x faster and takes 1.5x less space, than simple

```
       initializeAggregation('argMinState', key, value)
```

But what we actually need is

```
       if(condition, 
               initializeAggregation('argMinState', key, value), 
               emptyAggregation('argMinState', key, value))
```

If we remove columns completely from MatView (for benchmark), inserts will work 2x faster and take 2x less space, so probably that should be around theoretical speed for our case with `emptyAggregation`.
