### ISSUE TITLE
Formatting a query with column name as a parameter using http client

### ISSUE THREAD

**Issue by ozeno** [ClickHouse/ClickHouse#11879]
I want to format a select query using the HTTP client which has its column specified as a parameter as well but I couldn't find a type that helps what I want to achieve. An example query is as below:

```bash
curl -sS "<address>?param_p1=column_name&param_p2=string_value" -d "SELECT * FROM table WHERE {p1: ??? } like {p2:String}"
```

**Comment by filimonov** [comment]
Loosely related to https://github.com/ClickHouse/ClickHouse/issues/3474

**Comment by den-crane** [comment]
But it against the idea that parameters allows to define values only.

**Comment by filimonov** [comment]
Only constants can be substituted, not column names (by design & no plans to change that)
