### ISSUE TITLE
Materialized view is not merged correctly.

### ISSUE THREAD

**Issue by xiemeilong** [ClickHouse/ClickHouse#11876]
**Describe the bug**
Materialized view is not merged correctly.

**How to reproduce**
* Which ClickHouse server version to use
20.3

* `CREATE TABLE` statements for all tables involved

```
CREATE TABLE test (
`__deviceId` Int64,
 `__eventTime` DateTime CODEC(DoubleDelta,
 LZ4),
 `discrete` String
) ENGINE = MergeTree PARTITION BY toYYYYMM(__eventTime) ORDER BY (__deviceId, __eventTime);

```
```
CREATE MATERIALIZED VIEW IF NOT EXISTS test_hourly_mv 
 ENGINE = AggregatingMergeTree
 PARTITION BY toYYYYMM(`__day`) ORDER BY (`__deviceId`, `__day`, `__hour`) AS
 SELECT `__deviceId`,
 toDate(`__eventTime`) AS `__day`,
 toHour(`__eventTime`) AS `__hour`,
 arrayReduce('sumMap',[groupArray(`discrete`) as groupeddiscrete],
        [arrayResize(CAST([], 'Array(UInt64)'), length(groupeddiscrete), toUInt64(1))]) AS _discrete

 FROM  test
 GROUP BY (`__deviceId`, `__day`, `__hour`);
```

* Sample data for all these tables, use [clickhouse-obfuscator]
```
insert into test values (1,'2020-06-19 17:13:34', 'a'),(1,'2020-06-19 17:13:34', 'b'),(1,'2020-06-19 17:13:34', 'b'),(1,'2020-06-19 17:13:34', 'b');
insert into test values (1,'2020-06-19 17:13:34', 'a'),(1,'2020-06-19 17:13:34', 'b'),(1,'2020-06-19 17:13:34', 'b'),(1,'2020-06-19 17:13:34', 'b');
insert into test values (1,'2020-06-19 17:13:34', 'a'),(1,'2020-06-19 17:13:34', 'b'),(1,'2020-06-19 17:13:34', 'b'),(1,'2020-06-19 17:13:34', 'b');
```
* Queries to run that lead to unexpected result

```
SELECT `__deviceId`,
 toDate(`__eventTime`) AS `__day`,
 toHour(`__eventTime`) AS `__hour`,
 arrayReduce('sumMap',[groupArray(`discrete`) as groupeddiscrete],
        [arrayResize(CAST([], 'Array(UInt64)'), length(groupeddiscrete), toUInt64(1))]) AS _discrete

 FROM  test
 GROUP BY (`__deviceId`, `__day`, `__hour`);
```
```
select * from test_hourly_mv final;
```

**Expected behavior**
The two query should have the same result.

**Comment by xiemeilong** [comment]
Resovle by change to sql below, this maybe not a bug.
```
CREATE MATERIALIZED VIEW IF NOT EXISTS test_hourly_mv 
 ENGINE = AggregatingMergeTree
 PARTITION BY toYYYYMM(`__day`) ORDER BY (`__deviceId`, `__day`, `__hour`) AS
 SELECT `__deviceId`,
 toDate(`__eventTime`) AS `__day`,
 toHour(`__eventTime`) AS `__hour`,
 arrayReduce('sumMapState',[groupArray(discrete ) as groupeddiscrete],
        [arrayResize(CAST([], 'Array(UInt64)'), length(groupeddiscrete), toUInt64(1))]) AS _discrete
 FROM  test
 GROUP BY (`__deviceId`, `__day`, `__hour`);
```

```
select sumMapMerge(_discrete)  from test_hourly_mv final;
``

**Comment by xiemeilong** [comment]
I found it is still not having expected behave.

**Comment by xiemeilong** [comment]
I found it is still not having expected behave.

**Comment by den-crane** [comment]
it is impossible with AggregatingMergeTree. AggregatingMergeTree does not know that you need arrayReduce('sumMap' and just rewrite value in _discrete by function ANY.

You can use SummingMT and nested https://clickhouse.tech/docs/en/engines/table-engines/mergetree-family/summingmergetree/#nested-structures


```


CREATE TABLE test (
`__deviceId` Int64,
 `__eventTime` DateTime CODEC(DoubleDelta,
 LZ4),
 `discrete` String
) ENGINE = MergeTree PARTITION BY toYYYYMM(__eventTime) ORDER BY (__deviceId, __eventTime);


CREATE MATERIALIZED VIEW IF NOT EXISTS test_hourly_mv 
 ENGINE = SummingMergeTree
 PARTITION BY toYYYYMM(`__day`) ORDER BY (`__deviceId`, `__day`, `__hour`) AS
 SELECT `__deviceId`,
 toDate(`__eventTime`) AS `__day`,
 toHour(`__eventTime`) AS `__hour`,
 (arrayReduce('sumMap',[groupArray(`discrete`) as groupeddiscrete],
        [arrayResize(CAST([], 'Array(UInt64)'), length(groupeddiscrete), toUInt64(1))]) as v).1 AS `_discreteMap.name`,
  v.2 `_discreteMap.value`

 FROM  test
 GROUP BY (`__deviceId`, `__day`, `__hour`);


 insert into test values (1,'2020-06-19 17:13:34', 'a'),(1,'2020-06-19 17:13:34', 'b'),(1,'2020-06-19 17:13:34', 'b'),(1,'2020-06-19 17:13:34', 'b');
 insert into test values (1,'2020-06-19 17:13:34', 'a'),(1,'2020-06-19 17:13:34', 'b'),(1,'2020-06-19 17:13:34', 'b'),(1,'2020-06-19 17:13:34', 'b');
 insert into test values (1,'2020-06-19 17:13:34', 'a'),(1,'2020-06-19 17:13:34', 'b'),(1,'2020-06-19 17:13:34', 'b'),(1,'2020-06-19 17:13:34', 'b');


 SELECT
    __deviceId,
    toDate(__eventTime) AS __day,
    toHour(__eventTime) AS __hour,
    arrayReduce('sumMap', [groupArray(discrete) AS groupeddiscrete], [arrayResize(CAST([], 'Array(UInt64)'), length(groupeddiscrete), toUInt64(1))]) AS _discrete
FROM test
GROUP BY (__deviceId, __day, __hour)

┌─__deviceId─┬──────__day─┬─__hour─┬─_discrete─────────┐
│          1 │ 2020-06-19 │     17 │ (['a','b'],[3,9]) │
└────────────┴────────────┴────────┴───────────────────┘


SELECT *
FROM test_hourly_mv
FINAL

┌─__deviceId─┬──────__day─┬─__hour─┬─_discreteMap.name─┬─_discreteMap.value─┐
│          1 │ 2020-06-19 │     17 │ ['a','b']         │ [3,9]              │
└────────────┴────────────┴────────┴───────────────────┴────────────────────┘


```

**Comment by xiemeilong** [comment]
Clickhouse is so powerful，Thanks.    Should it be rejected when createing unaggregatable  column with AggregatingMergeTree?

**Comment by xwydq** [comment]
> it is impossible with AggregatingMergeTree. AggregatingMergeTree does not know that you need arrayReduce('sumMap' and just rewrites a value in _discrete column by function ANY on each insert.
> 
> You can use SummingMT and nested https://clickhouse.tech/docs/en/engines/table-engines/mergetree-family/summingmergetree/#nested-structures
> 
> ```
> 
> 
> CREATE TABLE test (
> `__deviceId` Int64,
>  `__eventTime` DateTime CODEC(DoubleDelta,
>  LZ4),
>  `discrete` String
> ) ENGINE = MergeTree PARTITION BY toYYYYMM(__eventTime) ORDER BY (__deviceId, __eventTime);
> 
> 
> CREATE MATERIALIZED VIEW IF NOT EXISTS test_hourly_mv 
>  ENGINE = SummingMergeTree
>  PARTITION BY toYYYYMM(`__day`) ORDER BY (`__deviceId`, `__day`, `__hour`) AS
>  SELECT `__deviceId`,
>  toDate(`__eventTime`) AS `__day`,
>  toHour(`__eventTime`) AS `__hour`,
>  (arrayReduce('sumMap',[groupArray(`discrete`) as groupeddiscrete],
>         [arrayResize(CAST([], 'Array(UInt64)'), length(groupeddiscrete), toUInt64(1))]) as v).1 AS `_discreteMap.name`,
>   v.2 `_discreteMap.value`
> 
>  FROM  test
>  GROUP BY (`__deviceId`, `__day`, `__hour`);
> 
> 
>  insert into test values (1,'2020-06-19 17:13:34', 'a'),(1,'2020-06-19 17:13:34', 'b'),(1,'2020-06-19 17:13:34', 'b'),(1,'2020-06-19 17:13:34', 'b');
>  insert into test values (1,'2020-06-19 17:13:34', 'a'),(1,'2020-06-19 17:13:34', 'b'),(1,'2020-06-19 17:13:34', 'b'),(1,'2020-06-19 17:13:34', 'b');
>  insert into test values (1,'2020-06-19 17:13:34', 'a'),(1,'2020-06-19 17:13:34', 'b'),(1,'2020-06-19 17:13:34', 'b'),(1,'2020-06-19 17:13:34', 'b');
> 
> 
>  SELECT
>     __deviceId,
>     toDate(__eventTime) AS __day,
>     toHour(__eventTime) AS __hour,
>     arrayReduce('sumMap', [groupArray(discrete) AS groupeddiscrete], [arrayResize(CAST([], 'Array(UInt64)'), length(groupeddiscrete), toUInt64(1))]) AS _discrete
> FROM test
> GROUP BY (__deviceId, __day, __hour)
> 
> ┌─__deviceId─┬──────__day─┬─__hour─┬─_discrete─────────┐
> │          1 │ 2020-06-19 │     17 │ (['a','b'],[3,9]) │
> └────────────┴────────────┴────────┴───────────────────┘
> 
> 
> SELECT *
> FROM test_hourly_mv
> FINAL
> 
> ┌─__deviceId─┬──────__day─┬─__hour─┬─_discreteMap.name─┬─_discreteMap.value─┐
> │          1 │ 2020-06-19 │     17 │ ['a','b']         │ [3,9]              │
> └────────────┴────────────┴────────┴───────────────────┴────────────────────┘
> ```


why arrayFilter not working for sumMap result in MATERIALIZED VIEW ?....
```
CREATE MATERIALIZED VIEW IF NOT EXISTS test_hourly_mv
            ENGINE = SummingMergeTree
                PARTITION BY toYYYYMM(`__day`) ORDER BY (`__deviceId`, `__day`, `__hour`)
AS
SELECT `__deviceId`,
       toDate(`__eventTime`)                                                                                AS `__day`,
       toHour(`__eventTime`)                                                                                AS `__hour`,
       (arrayReduce('sumMap', [groupArray(`discrete`) as groupeddiscrete],
                    [arrayResize(CAST([], 'Array(UInt64)'), length(groupeddiscrete),
                                 toUInt64(1))]) as v).1                                                     AS `_discreteMap.name`,
       v.2                            `_discreteMap.value`,
        arrayFilter((i,x) -> x%2=0, v.1, v.2) bm
FROM test
GROUP BY (`__deviceId`, `__day`, `__hour`);
```
