### ISSUE TITLE
Code: 225, e.displayText() = DB::Exception: Can't create replicated table without ZooKeeper

### ISSUE THREAD

**Issue by boy-xiaozhang** [ClickHouse/ClickHouse#11880]
The configuration files are under ETC
```xml
<!--zookeeper相关配置-->
<zookeeper-servers>
<node index="1">
<host>node1</host>
<port>2181</port>
</node>
<node index="2">
<host>node2</host>
<port>2181</port>
</node>
<node index="3">
<host>node3</host>
<port>2181</port>
</node>
</zookeeper-servers>
```
There is data in ClickHouse but no restart

**Comment by filimonov** [comment]
The error message is self-explaining: you can't create replicated table without ZooKeeper

If you have some issues connecting to zookeeper, check the clickhouse logs (`/var/log/clickhouse-server/clickhouse-server.log`) to find the reason.

**Comment by boy-xiaozhang** [comment]
> 错误消息不解自明：没有ZooKeeper，您将无法创建复制表
> 
> 如果您在连接Zookeeper时遇到问题，请查看Clickhouse日志（`/var/log/clickhouse-server/clickhouse-server.log`）以查找原因。

Two machines, one can be created, one can not be created, Zookeeper,log does not print exceptions

**Comment by filimonov** [comment]
Sorry, there is no way to help you based on provided info. Check the logs.

**Comment by boy-xiaozhang** [comment]
> 抱歉，无法根据所提供的信息为您提供帮助。检查日志，在这种情况下不可能有有效的日志（除非您配置错误）

Two versions of ClickHouse were found to be incompatible have already solved,thank you for your help
