### ISSUE TITLE
Clickhouse sharding rebalance records

### ISSUE THREAD

**Issue by arashkhavari** [ClickHouse/ClickHouse#11887]
Hello
In my scenario for testing have a 2 shard hosts
If a host-A in shard‌s turn off 
And the query data are INSERT into host-b in shards
What happens after host-A in shards if turned on?
are records evenly balance equal in shards?

**Comment by den-crane** [comment]
If you insert into Distributed table then your inserted data will wait for node-A in a Distributed table folder. Data will be unavailable for queries until it inserted into MergeTree at node-A.

**Comment by arashkhavari** [comment]
My concern about local databases in shard distributed clickhouse. the tables count in local database on each hosts not equal

**Comment by arashkhavari** [comment]
> If you insert into Distributed table then your inserted data will wait for node-A in a Distributed table folder. Data will be unavailable for queries until it inserted into MergeTree at node-A.

My concern about local databases in shard distributed clickhouse. the tables count in local database on each hosts not equal

**Comment by den-crane** [comment]
>the tables count in local database on each hosts not equal

You mean replicas? 

>tables count

You mean rows count?

**Comment by mjodeh** [comment]
I guess what @arashkhavari meant is that suppose that we have 3 shards and the insertion is being distributed between them then for any reason one of the shards went down. In this case the load will be distributed over 2 shards? and when the 3rd shard is back online does it go back to 3 shards? and the data which was not inserted in shard 3 will it be re-balanced between the 3 shards?
@den-crane What do you think about it?

**Comment by den-crane** [comment]
when insert into Distributed engine, CH creates .bin files in Distributed tables folder for each shard and process them async.

We have 3 shards. Shard 2 is down. We insert into Distributed table at node1 (shard1).

```
node1 (shard1)
     /var/lib/clickhouse/data/db/distributed_table/
           shard1
                 insert1.bin
                 insert2.bin
           shard2
                 insert1.bin
                 insert2.bin
                 insert3.bin
                 ....
                 insert55555.bin
           shard3
                 insert1.bin
                 insert2.bin
```

While shard2 is down. The Inserted data is stored at node1 in .bin files (insert1.bin .... insert55555.bin) and waits for shard2 is up back to reinsert into real MergeTree table at shard2 and make it visible for selects.

**Comment by mjodeh** [comment]
So once the shard is back online clickhouse will re-blance the data, during that the query will be distributed between the live shards, right? 
Ho much resources does this re-insert requires?
Does this unbalanced shards affects the query performance?

**Comment by den-crane** [comment]
No any re-balance. Because nothing to re-balance. 
Data is not inserted until node is alive. 

>Ho much resources does this re-insert requires?

There is no additional work. 

>Does this unbalanced shards affects the query performance?

No unbalanced shards. Nowhere to affect.

Probably you still don't understand how Distributed engine work. Read documentation.
