### ISSUE TITLE
Multithreading reading the same FD problem.

### ISSUE THREAD

**Issue by nicelulu** [ClickHouse/ClickHouse#11888]
```seek``` and ```read``` are not atomic operations.I didn't see the lock.Will there be concurrency issues?

**Comment by alexey-milovidov** [comment]
We don't read from one fd from multiple threads.
If we read from multiple threads, file is opened multiple times.

**Comment by nicelulu** [comment]
> We don't read from one fd from multiple threads.
> If we read from multiple threads, file is opened multiple times.

Thanks for your reply, i get it.
