### ISSUE TITLE
Integration test error -- host network can't connect to docker container ip.

### ISSUE THREAD

**Issue by AlexanderChiuluvB** [ClickHouse/ClickHouse#11882]
**Describe the unexpected behaviour**
I'm struggling with integration test for almost a week.
All the integration test case can't run because of docker network issue. 
for example, when I run `pytest -k test_extreme_deduplication` , it got stuck until times out. 
So I set the `use_zookeeper=false`, it shows that the localhost network can't connect to CK container ip.**Now the problem comes to I can't connect to or ping the container ip address, so all the testcase failed** 

I thought it will be a firewall issue, but even I shut down the firewall service it still can't work. 

Or do I need to add some iptables rules so the localhost can connect to container ip?

**Error message and/or stacktrace**
![image](https://user-images.githubusercontent.com/31793655/85384029-4b744900-b573-11ea-86ce-6a1d5625c433.png)

**Comment by filimonov** [comment]
Did you try runner script?
https://github.com/ClickHouse/ClickHouse/tree/master/tests/integration#running-with-runner-script 

Also you can try adding `--privileged` flag for docker run.
