### ISSUE TITLE
joining tables with like

### ISSUE THREAD

**Issue by catalina-ch** [ClickHouse/ClickHouse#11890]
Currently using 20.3 clickhouse version and wanna join two tables with like

select * from table_1 join table_2 on table_1.col1 like table_2.col2

got error: invalid expression for JOIN ON. Expected equals expression ...

**Comment by den-crane** [comment]
CH does not support such JOIN expression.

You can only use `cartesian product` and filter in `where` section

select * from table_1, table_2 
where table_1.col1 like table_2.col2

**Comment by filimonov** [comment]
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/5736#issuecomment-505543614
