### ISSUE TITLE
Table was not dropped because ZooKeeper session has expired

### ISSUE THREAD

**Issue by cw9** [ClickHouse/ClickHouse#11891]
**Describe the unexpected behaviour**
Sometimes `drop table foo` would return error `Table was not dropped because ZooKeeper session has expired` and this could continue forever without auto recovery.
I have to `detach` the table and `attach` again to be able to `drop` it. 
Is this the expected behavior? 

**How to reproduce**
* Which ClickHouse server version to use
20.3.7

* Queries to run that lead to unexpected result
drop table foo

**Expected behavior**
ClickHouse server should try to fix the expired ZK session so that retries of `drop table` could go through without manual `detach` + `attach`

**Comment by hieunguyen1809** [comment]
I got same issue on version 19.17.9.60

**Comment by hohaftf** [comment]
I got the same issue on version 20.4.5.36 and database engine Atomic

**Comment by alexey-milovidov** [comment]
Every ClickHouse version is affected.
