### ISSUE TITLE
Example of using Redis dictonary?

### ISSUE THREAD

**Issue by alfexandr** [ClickHouse/ClickHouse#11910]
Hello. I try to using Redis dictonary in CH but it is lack of documentation.
How I understand when I add redis dictonary to CH tn run KEYS * then try do type in all keys.
First one How I now using KEYS are not recommended. Maybe beter use scan with custom pattern?
Second can I use patterns for keys? Scanning all keys for type is too long.
Have anybody working examle of using redis dictonary?

**Comment by CurtizJ** [comment]
> How I understand when I add redis dictonary to CH tn run KEYS * then try do type in all keys.
Yes, now `KEYS *` is used.

> Second can I use patterns for keys? Scanning all keys for type is too long.
Do you want to set this pattern in dictionary config? Now it's impossible, but it's easy to implement.

We will try to make some improvements in Redis dictionaries.

**Comment by bzon** [comment]
Can we have a simple example of Redis, please?

**Comment by pachico** [comment]
@bzon you something like this be helpful to you?
https://pachicohub.com/posts/clickhouse-redis-as-source-for-dictionaries/

**Comment by ywangtht** [comment]
Any roadmap to add the pattern support for redis?
