### ISSUE TITLE
Trying to ingest ORC files into Clickhouse

### ISSUE THREAD

**Issue by santoshdvn** [ClickHouse/ClickHouse#11932]
Hi ,

Trying to load ORC file into table . I am using below syntax to load ORC file.table has 2 columns and both are string datatype

clickhouse-client --query="INSERT INTO table_orc FORMAT ORC" -h <localhost> -u <username> --multiline  --password=<password> --database="test" < orc_file

Code: 399 DB::Exception: Format ORC ist no suitable for output

for Ingesting the data is this right syntax ? 

Can anyone help on this ?

Thanks,
Santosh

**Comment by KochetovNicolai** [comment]
Hi,
Could you please show your table structure and stacktrace for exception (add `--stacktrace` to `clickhouse-client` or copy it from server log)?

**Comment by santoshdvn** [comment]
Please find stacktrace log


Code: 399. DB::Exception: Received from 
 DB::Exception: Format ORC is not suitable for output. Stack trace:

0. 0xbc3212c Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int)  in /usr/bin/clickhouse
1. 0x4f6cbc9 DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int)  in /usr/bin/clickhouse
2. 0x4c2d26a ?  in /usr/bin/clickhouse
3. 0x8eb6b04 DB::StorageFileBlockOutputStream::StorageFileBlockOutputStream(DB::StorageFile&, DB::CompressionMethod, DB::Context const&)  in /usr/bin/clickhouse
4. 0x8eb2cae DB::StorageFile::write(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&)  in /usr/bin/clickhouse
5. 0x94efd4d DB::PushingToViewsBlockOutputStream::PushingToViewsBlockOutputStream(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::IStorage> const&, DB::Context const&, std::__1::shared_ptr<DB::IAST> const&, bool)  in /usr/bin/clickhouse
6. 0x8bead8d DB::InterpreterInsertQuery::execute()  in /usr/bin/clickhouse
7. 0x8dc0778 ?  in /usr/bin/clickhouse
8. 0x8dc3814 DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool, bool)  in /usr/bin/clickhouse
9. 0x4fefd49 DB::TCPHandler::runImpl()  in /usr/bin/clickhouse
10. 0x4ff0c5c DB::TCPHandler::run()  in /usr/bin/clickhouse
11. 0x9bb5a07 Poco::Net::TCPServerConnection::start()  in /usr/bin/clickhouse
12. 0x9bb5dfd Poco::Net::TCPServerDispatcher::run()  in /usr/bin/clickhouse
13. 0xbca488f Poco::PooledThread::run()  in /usr/bin/clickhouse
14. 0xbca1958 Poco::ThreadImpl::runnableEntry(void*)  in /usr/bin/clickhouse
15. 0xbca31f9 ?  in /usr/bin/clickhouse
16. 0x7e65 start_thread  in /usr/lib64/libpthread-2.17.so
17. 0xfe88d __clone  in /usr/lib64/libc-2.17.so

**Comment by filimonov** [comment]
It seem like you are trying to insert into Table with engine = file and want to write it in format ORC. 

Writing ORC format is not merged yet, so you can use it for reading currently (and your intent is not clear).

**Comment by filimonov** [comment]
See also #11662 #4903

**Comment by santoshdvn** [comment]
I am trying to ingest ORC files from HDFS into Clickhouse. I tried different compression types(None,Snappy,zlib). I wast not able to ingest data in Clickhouse , where as I could able to ingest parquet files from HDFS to Clickhouse tables. This is how I am loading parquet files 

 hdfs dfs -cat <hdfs_parquetfiles> | ~/ch/chc -h <servername> -u <username> --password <password> --query="insert into test.testing_clickhouse_FORMAT Parquet";

any thoughts or suggestions for ORC?

**Comment by filimonov** [comment]
According to the exception problem is not with reading / parsing ORC (which is supported) but with writing ORC.

What is the definitions of table in which you trying to insert the data?

**Comment by santoshdvn** [comment]
I have created table with below definition
CREATE TABLE test.testing_clickhouse (
column1 String,
column2 String
) ENGINE = Log;

**Comment by alexey-milovidov** [comment]
@santoshdvn 

> hdfs dfs -cat <hdfs_parquetfiles> | ~/ch/chc -h -u --password --query="insert into test.testing_clickhouse_FORMAT Parquet";

Your query has extra underscore.
The correct query is:

> hdfs dfs -cat <hdfs_parquetfiles> | ~/ch/chc -h -u --password --query="insert into test.testing_clickhouse FORMAT Parquet";
