### ISSUE TITLE
Float64 to Float32 produce Connection loss

### ISSUE THREAD

**Issue by asurovenko** [ClickHouse/ClickHouse#11933]
Hello,
I trying to change column type from Float64 to Float32 and I got the following message: **Code: 999, e.displayText() = Coordination::Exception: Connection loss (version 20.4.4.18 (official build))**
Any other query work well. Is it related to any limitations?
I have ReplicatedMergeTree tables, each of my tables have more than 30Gb data.
Thanks.

**Comment by den-crane** [comment]
Check logs /var/log/clickhouse-server/clickhouse-server.log  /var/log/clickhouse-server/clickhouse-server.err.log for an error
Check  `sudo dmesg|tail -100` for oom-killer messages

**Comment by asurovenko** [comment]
dmesg did not give any message from oom-killer, but I caught the error from err.log
`2020.06.24 22:01:39.433307 [ 277430 ] {} <Error> zkutil::EphemeralNodeHolder::~EphemeralNodeHolder(): Code: 999, e.displayText() = Coordination::Exception: Session expired (Session expired), Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x104191d0 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x8fff8ad in /usr/bin/clickhouse
2. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int) @ 0xdddf7d8 in /usr/bin/clickhouse
3. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xdddfe02 in /usr/bin/clickhouse
4. ? @ 0xde14ff8 in /usr/bin/clickhouse
5. Coordination::ZooKeeper::remove(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, std::__1::function<void (Coordination::RemoveResponse const&)>) @ 0xde0f542 in /usr/bin/clickhouse
6. zkutil::ZooKeeper::tryRemove(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xdde81ee in /usr/bin/clickhouse
7. std::__1::__shared_ptr_emplace<zkutil::EphemeralNodeHolder, std::__1::allocator<zkutil::EphemeralNodeHolder> >::__on_zero_shared() @ 0x91d0cfe in /usr/bin/clickhouse
8. std::__1::__shared_ptr_emplace<zkutil::LeaderElection, std::__1::allocator<zkutil::LeaderElection> >::__on_zero_shared() @ 0xd77be4a in /usr/bin/clickhouse
9. DB::StorageReplicatedMergeTree::exitLeaderElection() @ 0xd71602a in /usr/bin/clickhouse
10. DB::ReplicatedMergeTreeRestartingThread::partialShutdown() @ 0xda6ad07 in /usr/bin/clickhouse
11. DB::ReplicatedMergeTreeRestartingThread::run() @ 0xda70458 in /usr/bin/clickhouse
12. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0xcfe9619 in /usr/bin/clickhouse
13. DB::BackgroundSchedulePool::threadFunction() @ 0xcfe9c42 in /usr/bin/clickhouse
14. ? @ 0xcfe9d72 in /usr/bin/clickhouse
15. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x902526b in /usr/bin/clickhouse
16. ? @ 0x9023753 in /usr/bin/clickhouse
17. start_thread @ 0x7dd5 in /usr/lib64/libpthread-2.17.so
18. __clone @ 0xfdead in /usr/lib64/libc-2.17.so
 (version 20.4.4.18 (official build))
`

**Comment by asurovenko** [comment]
Hi,
My Zookeepers logs have the errors too:
```
2020-06-25 04:48:46,914 [myid:2] - INFO  [SyncThread:2:FileTxnLog@216] - Creating new log file: log.50006d002
2020-06-25 04:48:46,914 [myid:2] - INFO  [Snapshot Thread:FileTxnSnapLog@301] - Snapshotting: 0x50006d004 to /var/lib/zookeeper/version-2/snapshot.50006d004
2020-06-25 04:48:47,025 [myid:2] - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@383] - Exception causing close of session 0x2027a2d6439002b: Len error 1157648
2020-06-25 04:48:47,026 [myid:2] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@1056] - Closed socket connection for client /10.130.129.10:47158 which had sessionid 0x2027a2d6439002b
2020-06-25 04:48:47,032 [myid:2] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@222] - Accepted socket connection from /10.130.129.10:47406
2020-06-25 04:48:47,032 [myid:2] - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@903] - Connection request from old client /10.130.129.10:47406; will be dropped if server is in r-o mode
2020-06-25 04:48:47,032 [myid:2] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@949] - Client attempting to establish new session at /10.130.129.10:47406
2020-06-25 04:48:47,033 [myid:2] - INFO  [CommitProcessor:2:ZooKeeperServer@694] - Established session 0x2027a2d6439002c with negotiated timeout 30000 for client /10.130.129.10:47406
2020-06-25 04:49:18,806 [myid:2] - INFO  [SessionTracker:ZooKeeperServer@355] - Expiring session 0x2027a2d6439002b, timeout of 30000ms exceeded
2020-06-25 04:49:18,813 [myid:2] - INFO  [ProcessThread(sid:2 cport:-1)::PrepRequestProcessor@487] - Processed session termination for sessionid: 0x2027a2d6439002b
```

**Comment by filimonov** [comment]
Too big zookeeper transaction? How many partitions do you have in the table (check `select count() from system.parts where active=1 and table='...'`)

**Comment by asurovenko** [comment]
filimonov, the query returns **2907**, for other my table it's **5652**.
And I have 1 table with the same engine but by some reason exactly in that table I successfully changed the column type and for that table count of partitions is **1897**.

**Comment by filimonov** [comment]
the bigger number of partitions you have, the bigger zookeeper transaction it tries to start.

**Comment by den-crane** [comment]
>Len error 1157648

Bigger than 1MB (ZK 1MB default for jute.maxbuffer   https://zookeeper.apache.org/doc/r3.3.2/zookeeperAdmin.html)
CH supports bigger buffer https://github.com/ClickHouse/ClickHouse/pull/4398
You can set bigger value in your ZK -Djute.maxbuffer=

**Comment by den-crane** [comment]
And it's actually strange  2**20/2907 = 360 bytes. 
It means that a length of  part name is about 360 bytes.

@asurovenko  can you show
`select partition, name from system.parts where active=1 and table='...' limit 10`

**Comment by keliss** [comment]
Hello everyone. I'm working on a project that Alexey used to work on. @den-crane here are a few examples of the output:
```
table 1, 2809 partititions
2020-04-20 13:00:00,1587387600_1_1_0
2020-04-20 14:00:00,1587391200_1_1_0
2020-04-20 15:00:00,1587394800_1_1_0
2020-04-20 16:00:00,1587398400_1_1_0
2020-04-20 17:00:00,1587402000_1_1_0
2020-04-20 18:00:00,1587405600_1_1_0
2020-04-20 19:00:00,1587409200_1_1_0
2020-04-20 20:00:00,1587412800_1_1_0
2020-04-20 21:00:00,1587416400_1_1_0
2020-04-20 22:00:00,1587420000_1_1_0
```
```
table 2, 5425 partitions
2020-04-20 13:00:00,1587387600_1_6_1_14
2020-04-20 13:00:00,1587387600_7_7_0_14
2020-04-20 13:00:00,1587387600_8_12_1_14
2020-04-20 14:00:00,1587391200_1_6_1_16
2020-04-20 14:00:00,1587391200_7_14_1_16
2020-04-20 15:00:00,1587394800_1_6_1_16
2020-04-20 15:00:00,1587394800_7_14_1_16
2020-04-20 16:00:00,1587398400_1_6_1_16
2020-04-20 16:00:00,1587398400_7_14_1_16
2020-04-20 17:00:00,1587402000_1_6_1_16
```

**Comment by den-crane** [comment]
>2809 partititions 

You mean parts?  `select count() from system.parts where active=1 and table='table 2'`

Did you try to increase `-Djute.maxbuffer` https://github.com/ClickHouse/ClickHouse/issues/11933#issuecomment-654286261

**Comment by keliss** [comment]
Yes, parts, I guess. Sorry, got confused by the naming.
I didn't try increasing that yet, will let you know after I do.

**Comment by den-crane** [comment]
As I can see you have by hour partitions. CH was designed for monthly partitioning.
What was your goal to hour partitions? 
And what is the data retention? For how long do you store your data (week ? month?)?
With such partitioning you will have a hard journey.

**Comment by keliss** [comment]
We do data aggregation hourly and it is convenient to do the partitioning using the same time interval. Plus querying the database for data for some hour should be faster if I understand correctly how it works. The data retention is set to be three months generally. But can you please tell me what are the disadvantages of such an approach and what problems are possible here?

**Comment by den-crane** [comment]
repro:
```

20.7.1

CREATE TABLE testAlter
( A Int64, T DateTime, X Float64) ENGINE = ReplicatedReplacingMergeTree ('/clickhouse/testAlter','xxx') partition by toStartOfHour(T) ORDER BY  A;

set max_partitions_per_insert_block=0

insert into testAlter select number, toDateTime('2000-01-01 00:00:00') + number*3600, 0 from numbers(10000);
0 rows in set. Elapsed: 186.044 sec. Processed 10.00 thousand rows

select count() from system.parts where active=1 and table='testAlter'
┌─count()─┐
│   10000 │
└─────────┘
alter table testAlter modify column X Float32;
Code: 999. DB::Exception: Received from localhost:9000. DB::Exception: Connection loss.

ZK LOG java.io.IOException: Len error 1540069

        

export SERVER_JVMFLAGS="-Djute.maxbuffer=50000000"
bin/zkServer.sh restart

alter table testAlter modify column X Float32;
0 rows in set. Elapsed: 91.637 sec.


export SERVER_JVMFLAGS=""
bin/zkServer.sh restart

alter table testAlter delete where 1
Received from localhost:9000. DB::Exception: Connection loss.

ZK log java.io.IOException: Len error 1540069

```

**Comment by den-crane** [comment]
>Plus querying the database for data for some hour should be faster if I understand correctly how it works.

Only if your query process data for only single digit number of hours.

>But can you please tell me what are the disadvantages 

Big number of partitions -> parts -> 
* slow CH start (CH reads every part and open each primarykey.idx and other files)
* issue with ZK mutations / alters
* need to clean block_numbers znodes manually in ZK https://github.com/ClickHouse/ClickHouse/issues/3322

**Comment by den-crane** [comment]
Summary: need to increase -Djute.maxbuffer or reduce a number of active parts by any way.

**Comment by keliss** [comment]
Got it, thank you.
