### ISSUE TITLE
Add support for setting query_id in SETTING block

### ISSUE THREAD

**Issue by siradjev** [ClickHouse/ClickHouse#11987]
**Use case**
Query_id is used for troubleshooting of applications when analyzing query logs. Currently the only method is to use it are:
- HTTP interface - if driver does not support it - rely on multiline comment
- clickhouse-client - only supplying query id in non-interactive mode. 

**Describe the solution you'd like**
allow specifying SETTINGS query_id='dqdwqdq'

**Describe alternatives you've considered**
Putting query id in part of actual query as one of the fields or constant conditions, or in WITH clause.

**Comment by alexey-milovidov** [comment]
The difficulty is that query_id is generated too early - before parsing stage. That's why we can report query_id in case of parse errors.

**Comment by siradjev** [comment]
As a workaround, it would also be reasonable if we can support some custom key, so that it can be found from query text. It would be less intrusive than using query text itself. 
E.g. if you define some sort of custom_identifiers allowed to be passed as settings and then recorded in settings column or additional custom-settings column of query log. 
Example:
```
select 1 
settings max_threads=1, 
   customsetting.query_id='2222', 
   customsetting.process='worker5', 
   customsetting.machine_id='myhostname', 
   customsetting.reason='user-ran-report xxy', 
   customsetting.request_id='somelongguidhere', 
   customsetting.callchain='service1[guid]->service2[guid]->service3[guid]'
```

And then have a json column or key-value nested column in query log from which data can be extracted (can also use query text but separate column is "nicer"). 
Currently, the problem is that any setting that is not valid is returning direct error.

**Comment by alexey-milovidov** [comment]
There was an idea to add dedicated `comment` column to query log and to allow to specify comment in HTTP and native interfaces.

**Comment by siradjev** [comment]
> There was an idea to add dedicated `comment` column to query log and to allow to specify comment in HTTP and native interfaces.

that would work too, but if there are naturally multiple comments in multiple places, how would it look in logs? is there an associated issue for that?

**Comment by amosbird** [comment]
Custom settings are now available https://github.com/ClickHouse/ClickHouse/blob/bb832f204c6ae49e7d8dc93ed5da9fe2c0ac2751/tests/queries/0_stateless/01418_custom_settings.sql
