### ISSUE TITLE
duplicated row inserted after I batch insert data into a distributed table

### ISSUE THREAD

**Issue by phillipcheng** [ClickHouse/ClickHouse#11990]
I got duplicated data after I batch insert data into a distributed table.

ClickHouse server version 20.4.4.18 (official build).
I have setup 3 nodes cluster.
the product-cluster is defined as following:
```
<prd_cluster>
    <shard>
        <internal_replication>true</internal_replication>
        <replica>
            <default_database>s1</default_database>
            <host>map01</host>
            <port>9000</port>
        </replica>
        <replica>
            <default_database>s1</default_database>
            <host>lop05</host>
            <port>9000</port>
        </replica>
    </shard>
    <shard>
        <internal_replication>true</internal_replication>
        <replica>
            <default_database>s2</default_database>
            <host>map02</host>
            <port>9000</port>
        </replica>
        <replica>
            <default_database>s2</default_database>
            <host>map01</host>
            <port>9000</port>
        </replica>
    </shard>
    <shard>
        <internal_replication>true</internal_replication>
        <replica>
            <default_database>s3</default_database>
            <host>lop05</host>
            <port>9000</port>
        </replica>
        <replica>
            <default_database>s3</default_database>
            <host>map02</host>
            <port>9000</port>
        </replica>
    </shard>
</prd_cluster>
```
the cluster has 3 shards, each shard has 2 replica, to provide HA.
i have setup zookeeper for replica, still using these 3 nodes.
```
<zookeeper>
    <node index="1">
        <host>map01</host>
        <port>2181</port>
    </node>
    <node index="2">
        <host>map02</host>
        <port>2181</port>
    </node>
    <node index="3">
        <host>lop05</host>
        <port>2181</port>
    </node>
</zookeeper>
```
my data insertion logic is following:
i will do a query to the target db(clickhouse) to check what is the last timestamp inserted, then i will generated a new query from source table(mysql) to get new time-windowed data, then batch insert to clickhouse.

in order to reach atomic insertion, the data i inserted is less than 1,000,000bytes, and belongs to the same partition. (same shop_id).
following is the sample schema i used.
```
CREATE TABLE if not exists s1.work_order
(
    `id` Int64,
    `gmt_created` DateTime,
    `gmt_modified` DateTime,
    `created_by` String,
    `modified_by` String,
    `is_deleted` Int8,
    `comment` Nullable(String),
    `attributes` Nullable(String),
    `merchant_id` Int64,
    `shop_id` Int64,
)
Engine=ReplicatedMergeTree('/clickhouse/tables/{shard1}/work_order', '01')
PARTITION BY shop_id
ORDER BY id;

CREATE TABLE if not exists s2.work_order as s1.work_order
Engine=ReplicatedMergeTree('/clickhouse/tables/{shard2}/work_order', '02')
PARTITION BY shop_id
ORDER BY id;

CREATE TABLE if not exists work_order as s1.work_order ENGINE = Distributed('prd_cluster', '', work_order, rand());
```
i do insertion via command line interface, insert to node map02's distributed table.
```
cat file.csv | clickhouse-client --host map02 --database=default --query="INSERT INTO work_order FORMAT TSV";
```
i found lots of duplicated data doing this way. 1%
then i chatted on slack, expert suggested to try to insert to local table to see whether this goes away.
i tried, and this problem goes away.
but i have to use the sharded feature, so  i have to insert into distributed table.
then i add logic to wait till the previous insert succeeded (to avoid non-atomic behavior), i wait till the intended inserted rows (i do a query for that) >= the rows i inserted, if less then i need to wait more, if equals, that is great, if more, that means duplicated occurs, and i recorded all the duplicates.
by doing this, the duplicated data drops, but still like 0.001% duplicates.

any suggestions?

The workaround i am using now is, first when i do a next batch insert, i will check the previous batch insert by query, making sure the number of records in the target equals to what i inserted, wait if less than, if more than then there is an internal error, i will record the query and the data file I used in this batch insert, then I will do a delete using that query, and redo a batch insert using the saved data file.

**Comment by den-crane** [comment]
1. It's not recommended to share CH with ZK. CH uses all hosts resources and it cases ZK issues.
2. Check  CH logs for insertion errors (/var/log/clickhouse/clickhouse.err.log /var/log/clickhouse/clickhouse.log ) .
3. Replace a sharding key  `rand()` with something more stable i.e. `id` because rand makes your inserts undeduplicatable on repeat.

**Comment by phillipcheng** [comment]
I have tried all your suggestions.
but it still happens and happens a lot.

<img width="1398" alt="截屏2020-07-04 上午7 05 45" src="https://user-images.githubusercontent.com/7891324/86500606-e4516280-bdc4-11ea-9229-4327d96c0a85.png">
i just insert once (3 records) into the distributed table, but the result is 5 records, and in 2 blocks.

any clue?

**Comment by phillipcheng** [comment]
i changed to insert to local tables, i am doing the host and db selection on the client side, but still, there is duplication and missing problems. i am doing parallel insertion to the same table.
clickhouse does not support this?

**Comment by den-crane** [comment]
CH supports parallel insertion. Probably something wrong with your client. How do you handle insertion errors and how re-tries implemented? 

https://clickhouse.tech/docs/en/engines/table-engines/mergetree-family/replication/
_Data blocks are deduplicated. For multiple writes of the same data block (data blocks of the same size containing the same rows in the same order), the block is only written once. The reason for this is in case of network failures when the client application doesn’t know if the data was written to the DB, so the INSERT query can simply be repeated. It doesn’t matter which replica INSERTs were sent to with identical data. INSERTs are idempotent. Deduplication parameters are controlled by merge_tree server settings._
