### ISSUE TITLE
Join engine   database error

### ISSUE THREAD

**Issue by peaksnail** [ClickHouse/ClickHouse#12012]
Hi team

I find some problem about Join Engine

there is a database named test,and a table named goods_join with Join Engine in the db test,

I execute select sql and it works, but I execute alter ... update sql like 

```
alter table goods update value=joinGet(goods_join,'value',id)  where value=0
```
It has the following error

```
2020.06.28 19:09:25.785605 [ 9 ] {} <Error> void DB::BackgroundProcessingPool::threadFunction(): Code: 60, e.displayText() = DB::Exception: Table default.good
s_join doesn't exist., Stack trace:
```

But I create the table in database test not default

It works until I create table goods_join in the database default

**Comment by filimonov** [comment]
Duplicate of #7699

Use `joinGet('dbname.tablename',...) ` for `on cluster`.

**Comment by peaksnail** [comment]
Hi,
It's not work for me,
clickhouse version 19.17.4.11 and it's not cluster
