### ISSUE TITLE
Instability

### ISSUE THREAD

**Issue by mjodeh** [ClickHouse/ClickHouse#12023]
**Describe the bug**
Clickhouse keeps crashing and brings the server down

**How to reproduce**
* Which ClickHouse server version to use: `ClickHouse server version 20.1.2 revision 54431`
* Which interface to use, if matters: `both HTTP and native client`
* Non-default settings, if any: `None`
* `CREATE TABLE` statements for all tables involved: `On a wide different tables`
* Queries to run that lead to unexpected result
`insert or select` even simple select `count()` with `groupUniqArray` sometimes crashes the server!

**Additional context**
The clickhouse keeps crashing under insertion or querying, even though the insertions are bulked but it just keeps crashing and once it crashed the kernal crashes too and we have to restart the server.
We have `83 databases`, each contains a very wide and sparse table (a lot of nulls), all of them have insertions while query rate is too low, this might cause the problem?
Is it in general a bad practice to have this wide ans sparse table?
We can put all the databases in `Single database` this might solve the problem?
The insertions are bulked per database and on each database the insertion rate is between 1 to 3 insertions per 10 seconds, but on all databases it's much higher than that, so should the insertion rate be 1 insertion per server or per database?
any suggestions to fix this overwhelming issue?
Once our team backs online I will provide you with more details regarding the monitoring

**Comment by den-crane** [comment]
You are using very early 20.1 version. Try to upgrade to 20.1.16.120.
Do you use mutations? Alter delete/update?

**Comment by mjodeh** [comment]
Will update the version.
No we don't have alter delete/update but we have `alter add column`

**Comment by mjodeh** [comment]
I see from your releases that `v20.4.6.53-stable` is it production ready?

**Comment by filimonov** [comment]
Yes.
