### ISSUE TITLE
Limit on numbers_mt can't be finished when some streams have no threads assigned

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#12027]
```
SELECT count()
FROM 
(
    SELECT number
    FROM system.numbers_mt
    WHERE number <= 100000000
    LIMIT 100000000
    UNION ALL
    SELECT number
    FROM system.numbers_mt
    WHERE number <= 100000000
    LIMIT 100000000
)

↓ Progress: 29.44 billion rows, 235.48 GB (2.58 billion rows/s., 20.62 GB/s.) Cancelling query.
↙ Progress: 29.68 billion rows, 237.41 GB (2.58 billion rows/s., 20.61 GB/s.) Ok.
Query was cancelled.

0 rows in set. Elapsed: 11.521 sec. Processed 29.68 billion rows, 237.41 GB (2.58 billion rows/s., 20.61 GB/s.) 
-- never finishes.
```

**Comment by KochetovNicolai** [comment]
It doesn't seem to me as a bug pretty much.
You read from infinite multithreaded storage, and filter all the rows after limit. Some streams from storage are not even executing.

It may be solved in two ways:
1. Implement unlimited `numbers_mt` the same way as limited table function `numbers_mt(limit)` (add shared atomic for streams).
2. Try to evenly distribute work between streams from storage.


1) is generally ok, but probably may affect some perftests
2) is more difficult and may affect performance if we reschedule tasks too often.  

If you need first 100000000 rows, just use `numbers_mt(100000000)`.

**Comment by filimonov** [comment]
It is the synthetic example showing the issue. IRL it was a normal table which (probably) stopped being limited, leading to significant performance degradation.

Smth like this:

```
create table test engine=MergeTree order by tuple() as select * from numbers(30000000);


set experimental_use_processors=0;
select count() from (select number from test group by number order by number limit 10 union all select number from test group by number order by number limit 10);
-- Elapsed: 2.664 sec


set experimental_use_processors=1;
select count() from (select number from test group by number order by number limit 10 union all select number from test group by number order by number limit 10);
-- Elapsed: 3.656 sec
```

**Comment by filimonov** [comment]
Discussed in Telegram, it seems like different issues. I will clean it up a bit.

**Comment by filimonov** [comment]
It's was a bit incorrect attempt to reproduce the performance issue, the real issue is here:  https://github.com/ClickHouse/ClickHouse/issues/12030

The issue with infinite table and unfortunate streams / threads scheduling is quite interesting, but out of the scope for now.

Maybe we can initiate rescheduling if there were several reads returning no data.
