### ISSUE TITLE
IP_trie dictionary larger than 32M segfaults

### ISSUE THREAD

**Issue by johndickinson** [ClickHouse/ClickHouse#1205]
`$ cat  ip2geo_dictionary.xml 
<dictionaries>
  <comment>IP to Geo</comment>
  <dictionary>
    <name>ip2geo</name>
    <source>
      <file>
        <path>/opt/dictionaries/ip2geo.tsv</path>
        <format>TabSeparated</format>
      </file>
    </source>
    <lifetime>300</lifetime>
    <layout>
      <ip_trie/>
    </layout>
    <structure>
      <key>
        <attribute>
          <name>prefix</name>
          <type>String</type>
        </attribute>
      </key>
      <attribute>
        <name>latitude</name>
        <type>Float32</type>
	<null_value>0.0</null_value>
      </attribute>
      <attribute>
        <name>longitude</name>
        <type>Float32</type>
	<null_value>0.0</null_value>
      </attribute>
      <attribute>
        <name>Country</name>
        <type>String</type>
        <null_value/>
      </attribute>
      <attribute>
        <name>City</name>
        <type>String</type>
        <null_value/>
      </attribute>
    </structure>
  </dictionary>
</dictionaries>
`

I have a TSV file like this
2.232.198.0/24	40.9078	14.1858	Italy	Calvizzano
37.32.80.0/23	40.9078	14.1858	Italy	Calvizzano
...
If the file contains more than 645230 rows clickhouse server segfaults
With 645230 rows the tsv file is 32MB on disk but according to clickhouse (SELECT * FROM system.dictionaries) 1361424933760 bytes have been allocated!

**Comment by vavrusa** [comment]
Hi John, this is a simple binary trie, so it branches on every bit. I have a note to reimplement it with poptries (since the original implementation is encumbered by a restrictive license), but haven't had a time for that yet.

**Comment by johndickinson** [comment]
I was more concerned with the fact that the server segfaulted rather than handling the error gracefully.

**Comment by KochetovNicolai** [comment]
Thank you for report. It's true that ip_trie may cause segmentation fault if dictionary has more than 2^20 different ip addresses. Will fix that problem soon.

**Comment by vavrusa** [comment]
@KochetovNicolai are you reworking the dictionary?

**Comment by alexey-milovidov** [comment]
Fixed by @vdimir in #16804, starting from version 20.13-testing.
