### ISSUE TITLE
ClickHouse documentation does not cover the HTTPS interserver tags

### ISSUE THREAD

**Issue by hodgesrm** [ClickHouse/ClickHouse#12066]
**Describe the issue**
ClickHouse documentation is missing a section to describe the interserver_https_port and interserver_https_host tags.  See https://clickhouse.tech/docs/en/operations/server-configuration-parameters/settings/, which documents the HTTP settings.  HTTPS settings are omitted.  

**Additional context**
Currently the only way to get full information on interserver port configuration is to read the code at https://github.com/ClickHouse/ClickHouse/blob/master/programs/server/Server.cpp.

**Comment by qoega** [comment]
Original PR #2760

**Comment by olgarev** [comment]
@alexey-milovidov Documented, please remove the doc-alert tag
