### ISSUE TITLE
input_format_skip_unknown_fields does not work when importing CSVWithNames

### ISSUE THREAD

**Issue by Perlovka** [ClickHouse/ClickHouse#12078]
Hi,

When importing CSV files that have more fields than the table we import to, clickhouse-client fails with 
```
Code: 117. DB::Exception: Expected end of line
```

Documentation says that **input_format_skip_unknown_fields** is supported for **CSVWithNames** format.
https://clickhouse.tech/docs/en/operations/settings/settings/#settings-input-format-skip-unknown-fields

table:
```
clickhouse-client --query="CREATE TABLE IF NOT EXISTS mapRegions (regionID UInt32, regionName String) ENGINE=MergeTree() ORDER BY (regionID) SETTINGS index_granularity = 8192"
```
file.csv:
```
regionID,regionName,someField
1,MyRegion,foo
2,YourRegion,baz
```
import:
```
clickhouse-client --input_format_skip_unknown_fields=1 --query="INSERT INTO mapRegions FORMAT CSVWithNames" < file.csv
```

ClickHouse server version 20.4.6 revision 54434

Thanks.

**Comment by Akazz** [comment]
It is worth noting that this behaviour does not reproduce with CH v20.5. What's also interesting is that file `src/Processors/Formats/Impl/CSVRowInputFormat.cpp` did not change since v20.4. I will continue looking into it

**Comment by filimonov** [comment]
Doesn't reproduced on >= 20.5
