### ISSUE TITLE
hdfs: Can't use virtual column _file

### ISSUE THREAD

**Issue by oheldib** [ClickHouse/ClickHouse#12077]
Hello 

I created an HDFS table pointing to some CSV files
`CREATE TABLE RT_PROG (
TimeStamp DateTime,
 Customer String
) ENGINE = HDFS('hdfs://IP:PORT/PATH/TO/FILES/*.csv', 'CSVWithNames');
`

then, i tried to count number of customers in each file using this query
`select count(Customer) as Custs_cnt, _file as ACT
from RT_PROG
group by _file`

But i get the following error: 
`DB::Exception: Missing columns: '_file' while processing query: 'SELECT count(Customer) as Custs_cnt, _file AS ACT FROM RT_PROG GROUP BY _file', required columns: '_file' 'Customer', source columns: 'Customer' 'TimeStamp' (version 20.1.4.14 (official build))`

Any help ?
Is there a flag should be set in config file to enable virtual columns ?

**Comment by kssenii** [comment]
@oheldib it does not work because `_file` and `_path` virtual columns were added starting from version `20.2`, and your version is `20.1`.
