### ISSUE TITLE
WindowFunnel document error

### ISSUE THREAD

**Issue by osenlin** [ClickHouse/ClickHouse#12087]
![图片](https://user-images.githubusercontent.com/7776208/86365778-8893b600-bcac-11ea-8813-e9b1ea641aca.png)

 Length of the sliding window in milliseconds, instead of seconds

**Comment by zzn01** [comment]
neither seconds nor milliseconds. but depends on `timestamp`,  something like `timestamp of cond2 < timestamp of cond1 + window`

https://github.com/ClickHouse/ClickHouse/blob/b8fcd75de75c908a422b221a6d10c30b53fe8aa4/src/AggregateFunctions/AggregateFunctionWindowFunnel.h#L200

**Comment by akuzm** [comment]
Fixed here https://github.com/ClickHouse/ClickHouse/pull/19681
