### ISSUE TITLE
Nested: array columns have different array sizes

### ISSUE THREAD

**Issue by natemccallum** [ClickHouse/ClickHouse#12113]
It looks similar to #2445 that shows closed.

CREATE TABLE cmdts_test (  cmdts Nested( cmdty_id Nullable(UInt16), cmdty_name Nullable(String), cmdty_group_id Nullable(UInt16), cmdty_group_name Nullable(String)) ) ENGINE = Log

CREATE TABLE cmdts_test`
(
    \`cmdts\` Nested(
    cmdty_id Nullable(UInt16),
    cmdty_name Nullable(String),
    cmdty_group_id Nullable(UInt16),
    cmdty_group_name Nullable(String))
)
ENGINE = Log

Ok.

0 rows in set. Elapsed: 0.003 sec.

INSERT INTO cmdts_test VALUES ([5], ['myname'], [], ['fafa'])

INSERT INTO cmdts_test VALUES

Received exception from server (version 20.4.5):
Code: 190. DB::Exception: Received from localhost:9000. DB::Exception: Elements 'cmdts.cmdty_id' and 'cmdts.cmdty_group_id' of Nested data structure 'cmdts' (Array columns) have different array sizes..

1 rows in set. Elapsed: 0.003 sec.`

**Comment by den-crane** [comment]
Nested means that all properties should be filled
cmdty_id, cmdty_name, cmdty_group_id, cmdty_group_name
[5], ['myname'], [], ['fafa']

you have to fill cmdty_group_id , you can not pass empty  []

and empty array is not means Null.
`INSERT INTO cmdts_test VALUES ([5], ['myname'], [Null], ['fafa'])`
