### ISSUE TITLE
SimpleAggregateFunction If Not Default

### ISSUE THREAD

**Issue by thyn** [ClickHouse/ClickHouse#12127]
I have a table

```

CREATE TABLE temp.mmaxtest (
  d Date,

  sValue SimpleAggregateFunction(anyLast,String)

)
ENGINE = SummingMergeTree()
PARTITION BY tuple()
ORDER BY d
```

Sometimes I have sValue = '' (defaultvalue). Is it possible to ignore that values.Something like anyLastNotDefault? Is it possible to with current functionality of SimpleAggregateFunction? I know about AggregateFunction but It seems to me it's also simple feature that can increase performance.

**Comment by thyn** [comment]
It also can help to combine data from different sources. For example 

I have userid , userName and actioncount from one source (source 1) and userid, revenue from other source (source 2). With such aggregation I can insert separately data from source 1 by materialized view and data from the second source manually.

**Comment by filimonov** [comment]
Did you try inserting `anyLastIf()` ?

BTW:  https://github.com/ClickHouse/ClickHouse/issues/10754#issuecomment-625891916

**Comment by thyn** [comment]
SummingMergeTree - Thanks ,I've already fixed it by changing engine to AggregatingMergeTree

example:

1. create table
```
CREATE TABLE temp.test4 (
  d Date,

  f1  SimpleAggregateFunction(anyLast, UInt8),
  f2  SimpleAggregateFunction(anyLast, UInt8)
  

)
ENGINE = AggregatingMergeTree()
PARTITION BY tuple()
ORDER BY d

```

2. insert to f1
insert into  temp.test4 (d,f1) select  toDate('2020-01-01'), 1

|  d | f1| f2|
| --- | --- |---|
| 2020-01-01 | 1 | 0 |

3. insert to 

insert into  temp.test4 (d,f2) select  toDate('2020-01-01'), 2

|  d | f1| f2|
| --- | --- |---|
| 2020-01-01 | 0 | 2 |

I'm trying to find the way to have in result 

|  d | f1| f2|
| --- | --- |---|
| 2020-01-01 | 1 | 2 |

anyLastIf is not working because it produces default value which rewrites value to 0.
 I'm currently can do it with AggregateFunction (argMax,....) with little crunches but it seems to me a little overhead for that task and I will have hundreds of such dimensions ( user properties like Name , Fio, and etc). I need last of them, So max is not suitable for it.

**Comment by filimonov** [comment]
> anyLastIf in select is not working because it produces default value which rewrites current value. 

Hm... With nulls - too?

**Comment by thyn** [comment]
> > anyLastIf in select is not working because it produces default value which rewrites current value.
> 
> Hm... With nulls - too?



Thank you for idea. Didn't use NULL values because didn't see any reason for that.

```

CREATE TABLE temp.test6 (
  d Date,

  f1  SimpleAggregateFunction(anyLast, Nullable(UInt8)),
  f2  SimpleAggregateFunction(anyLast, Nullable( UInt8))

)
ENGINE = AggregatingMergeTree()
PARTITION BY tuple()
ORDER BY d


```

Well it works but in different manner

```
insert into temp.test5 (d,f2) select toDate('2020-01-01'), anyLastIf(toNullable(10), 1!=1)
```

anyLastIf became null

```
insert into temp.test5 (d,f2) select toDate('2020-01-01'), anyLast(if(1=1, NULL,0))
```
it works fine. I will use it. 

But, I have some AggregateFunction. How can it be used  with medianState? Are NULL values should be ignored?
```

CREATE TABLE temp.test6 (
  d Date,

  f3  AggregateFunction (median, Nullable(UInt32)),
   f4  AggregateFunction (median, UInt32)

)
ENGINE = AggregatingMergeTree()
PARTITION BY tuple()
ORDER BY d
```

I simple can't insert to test it

```
insert into temp.test6 (d,f3,f4) select toDate('2020-01-01'), medianState(t), medianState(t2)  from (select toNullable(toUInt32( 1))  as t, 2 as t2 ) 
```

**Comment by thyn** [comment]
Another Test. Nullable before SimpleAggregateFunction.

```
CREATE TABLE temp.test7 (
  d Date,

  f1  Nullable(SimpleAggregateFunction(anyLast, UInt8)),
  f2  Nullable(SimpleAggregateFunction(anyLast, UInt8))

)
ENGINE = AggregatingMergeTree()
PARTITION BY tuple()
ORDER BY d

```

II see that anyLast is not working:

insert into temp.test7 (d,f1,f2) select toDate('2020-01-01'),NULL ,null

then

insert into temp.test7 (d,f1,f2) select toDate('2020-01-01'),1 ,2

 | d | f1 | f2 | 
|---|---|---|
 | 2020-01-01 |  NULL |  NULL  | 


If I insert 

```
insert into temp.test7 (d,f1,f2) select toDate('2020-01-01'),1 ,2
insert into temp.test7 (d,f1,f2) select toDate('2020-01-01'),NULL ,null
insert into temp.test7 (d,f1,f2) select toDate('2020-01-01'),3 ,4
```

 | d | f1 | f2 | 
|---|---|---|
 | 2020-01-01 | 1 | 2 |

**Comment by filimonov** [comment]
i've meant `SimpleAggregateFunction(anyLast, Nullable(UInt8))`

**Comment by thyn** [comment]
I've performed 2 tests. Please, read that comment

https://github.com/ClickHouse/ClickHouse/issues/12127#issuecomment-654453942

**Comment by thyn** [comment]
As I understand AggregateFunction is working as I need. Am I right?

`
CREATE TABLE temp.test11 (
  d Date,


   f4  AggregateFunction (medianExact, UInt32)

)
ENGINE = AggregatingMergeTree()
PARTITION BY tuple()
ORDER BY d
```

```

insert into temp.test11 (d,f4) select toDate('2020-01-01'), medianExactState(toUInt32(t))  from (select 1  as t, 2 as t2 ) 
```

than multiple inserts of 
``
insert into temp.test11 (d) select toDate('2020-01-01')

```

select   finalizeAggregation(f4) from temp.test11 final

Result is 1. 

It's working ok, but I can't insert emty state, Is it possible?

something like
```
insert into temp.test11 (d,f4) select toDate('2020-01-01'), medianExactEmptyState  from (select 1  as t, 2 as t2 ) 
```

I've tried using 

```
CREATE TABLE temp.test12 (
  d Date,

  f1  Nullable(SimpleAggregateFunction(anyLast, UInt8)),
  f2  Nullable(SimpleAggregateFunction(anyLast, UInt8)),
   f4  AggregateFunction (medianExactIf,UInt32, UInt8)

)
ENGINE = AggregatingMergeTree()
PARTITION BY tuple()
ORDER BY d

```
select   finalizeAggregation(f4) from temp.test12 final


insert into temp.test12 (d,f4) select toDate('2020-01-01'), medianExactIfState(toUInt32(t), t!=1)  from (select 1  as t, 2 as t2 ) 


insert into temp.test12 (d,f4) select toDate('2020-01-01'), medianExactIfState(toUInt32(t), t==1)  from (select 1  as t, 2 as t2 ) 
```
Is it right solution?
