### ISSUE TITLE
GraphiteMergeTree seemingly not aggregating data?

### ISSUE THREAD

**Issue by mzealey** [ClickHouse/ClickHouse#12144]
I've got a GraphiteMergeTree table defined like:

```
CREATE TABLE default.graphite
(
    `Path` String, 
    `Value` Float64, 
    `Time` UInt32, 
    `Date` Date, 
    `Timestamp` UInt32
)
ENGINE = GraphiteMergeTree('graphite_rollup')
PARTITION BY toYYYYMM(Date)
ORDER BY (Path, Time)
SETTINGS index_granularity = 8192
```

The relevant rollup section is:

```
                <pattern>
                        <regexp>^foo\..*</regexp>
                        <function>max</function>
                        <retention>
                                <age>0</age>
                                <precision>10</precision>
                        </retention>
                        <retention>
                                <age>86400</age>
                                <precision>60</precision>
                        </retention>
                        <retention>
                                <age>518400</age>
                                <precision>600</precision>
                        </retention>
                        <retention>
                                <age>2592000</age>
                                <precision>7200</precision>
                        </retention>
                        <retention>
                                <age>31536000</age>
                                <precision>86400</precision>
                        </retention>
                </pattern>
```

However the 1+day old data doesn't seem to be being aggregated:

```
SELECT *
FROM graphite
WHERE Path = 'foo.CPU'
ORDER BY Time ASC
LIMIT 10

┌─Path─┬──────────Value─┬───────Time─┬───────Date─┬──Timestamp─┐
│ foo.CPU │ 8371310.335419 │ 1593791930 │ 2020-07-03 │ 1593791938 │
│ foo.CPU │ 2445045.007139 │ 1593791940 │ 2020-07-03 │ 1593791948 │
│ foo.CPU │  231271.279249 │ 1593791950 │ 2020-07-03 │ 1593791958 │
│ foo.CPU │  258739.250085 │ 1593791960 │ 2020-07-03 │ 1593791968 │
```

As Time is greater than 86400 seconds ago I would have expected the resolution to have been compressed to 60 seconds rather than the input of 10 seconds?

**Comment by den-crane** [comment]
A rolling-up happens during a merge process.
Probably this part is not merged yet in background automatically (by any reason) you can force a merge manually using `optimize table` https://clickhouse.tech/docs/en/sql-reference/statements/misc/#misc_operations-optimize

**Comment by mzealey** [comment]
Thanks, trying that now.

What would the lag usually be before data is merged? We have quite high insert rate on this table and from what I can see it hasn't been merged in the past 4-5 days even though most rollup merges are specified to happen within 1d of the data being created. Anything we can do to speed this up? We have plenty of IO, CPU and memory headspace to work with

**Comment by den-crane** [comment]
Check this project https://github.com/innogames/graphite-ch-optimizer

**Comment by mzealey** [comment]
I had tried that before but it also had said nothing to do.

I had to `optimize table final` to get it to run but it has now done the aggregations.

Given that most of my partitions are based around days rather than months & I'm taking about 10b row/day, does it make sense to change `partition by` to `toyyyymmdd()`, would that change anything in terms of the optimizations?

**Comment by den-crane** [comment]
> does it make sense to change partition by to toyyyymmdd()

Probably daily partitions would be easier to merge (CPU/disk IO) but still you need to call `optimize`

**Comment by mzealey** [comment]
Is there a way to debug why the merge is not being run in the background as often as I might expect? Are there any guarantees around when clickhouse will run this operation?

Also something I cannot find in the manual; is there any way to alter the partitioning scheme or do i have to create a new table?

**Comment by den-crane** [comment]
Merges have another goal -- minimization a number of part with minimum CPU / disk I/O. 
They not aware about a rollup. Rollup is just a byproduct.

>Are there any guarantees around when clickhouse will run this operation?

No. In the contrary. CH never do final merge automatically and after last insert into partition after some time (i.e. a week) parts will never be merged again. So 100% you have to run `optimize` manually to do month / year rollup.


>Also something I cannot find in the manual; is there any way to alter the partitioning scheme or 
>do i have to create a new table?

create a new table

**Comment by mzealey** [comment]
Many thanks for your help!

**Comment by den-crane** [comment]
One more thing.

>PARTITION BY toYYYYMM(Date) ORDER BY (Path, Time)

I don't know how your queries where section looks.
If it does not have `Date` filter. For example where Path = .... and Time between ....
Then consider Time as partitioning column.

`PARTITION BY toYYYYMM(toDateTime(Time)) ORDER BY (Path, Time)`
or 
`PARTITION BY toYYYYMMDD(toDateTime(Time)) ORDER BY (Path, Time)`

It will enable partition pruning.


Date type column was mandatory for partitioning when CH did not support arbitrary partition expressions ( before  Dec. 2017 ).
