### ISSUE TITLE
Distributed table is slower than query local table(stand-alone)

### ISSUE THREAD

**Issue by liubaochuan** [ClickHouse/ClickHouse#12155]
1 rows in set. Elapsed: 0.229 sec. Processed 18.92 million rows, 756.70 MB (82.66 million rows/s., 3.31 GB/s.) --query local table
1 rows in set. Elapsed: 0.751 sec. Processed 18.92 million rows, 756.70 MB (25.21 million rows/s., 1.01 GB/s.) --query distributed table

**Comment by filimonov** [comment]
Please show the query and schema.

**Comment by qoega** [comment]
hardware/network setup is also relevant. 756MB should be sent to initiator and to client.
You can check if there is difference if you wrap it into simple aggregation with almost no output like SUM/MAX. This can show if data transfer is slower than aggregation in your case

**Comment by Rafael-Luo** [comment]
one shard two replica also  Distributed table is slower than query local table

there are two node

local table trace log
`Limit
 Expression
  MergeSorting
   PartialSorting
    Expression
     ParallelAggregating
      Expression × 24
       Filter
        Expression
         Expression
          Filter
           Expression
            Expression
             Filter
              MergeTreeThread`

Distributed 
`Limit
 Expression
  MergeSorting
   PartialSorting
    Expression
     Aggregating
      Concat
       Expression
        Filter
         Expression
          Expression
           Filter
            Union
             Expression × 24
              Expression
               Filter
                MergeTreeThread`

executeQuery: Read 117847707 rows, 16.89 GiB in 3.824 sec., 30815014 rows/sec., 4.42 GiB/sec.
executeQuery: Read 117847707 rows, 16.89 GiB in 13.651 sec., 8633189 rows/sec., 1.24 GiB/sec.

 is different between ParallelAggregating and Aggregating

**Comment by Rafael-Luo** [comment]
@filimonov

**Comment by den-crane** [comment]
> executeQuery: Read 117847707 rows, 16.89 GiB in 3.824 sec., 30815014 rows/sec., 4.42 GiB/sec.
> executeQuery: Read 117847707 rows, 16.89 GiB in 13.651 sec., 8633189 rows/sec., 1.24 GiB/sec.

It is expected behavior in some cases. When CH needs to transfer huge volume from shards to an initiator (and network is a bottleneck) and do the final aggregation at the initiator (aggregation is done twice).

Please show the query and schema.

**Comment by filimonov** [comment]
> @filimonov

1) The suggestions above are relevant.
2) you didn't give answers 
3} try to rerun your query from the same node where clickhouse server works.
