### ISSUE TITLE
Ability to set default password via CLI during install?

### ISSUE THREAD

**Issue by dkoston** [ClickHouse/ClickHouse#12150]
Is there a configuration option I can pass to `apt-get install clickhouse-server` so it will specify the default password and not force an interactive UI? I cannot find this in the docs and my terraform configs for launching clickhouse no longer work as they aren't designed to type stuff into the shell. How are other people automating clickhouse installs with this new change?

**Comment by alexey-milovidov** [comment]
The password configuration is implemented via "debconf".
https://unix.stackexchange.com/questions/106552/apt-get-install-without-debconf-prompt

PS. If you don't have debconf in your system (e.g. you install `rpm` or `tgz` package on non-debian system) it will not ask.

**Comment by alexey-milovidov** [comment]
Reference: https://github.com/ClickHouse/ClickHouse/blob/master/debian/clickhouse-server.postinst#L131

**Comment by dkoston** [comment]
Thanks @alexey-milovidov!

**Comment by dkoston** [comment]
Been a few years but pretty sure I made a custom config for users and set `CLICKHOUSE_CONFDIR` which gets picked up by the post install script: https://github.com/ClickHouse/ClickHouse/blob/6b330e30b025291e4a114d6ba19472eea658680c/packages/clickhouse-server.postinstall#L25


Users config reference: https://clickhouse.com/docs/en/operations/configuration-files#example
