### ISSUE TITLE
Add time function "addIntervals" and "subtractIntervals"

### ISSUE THREAD

**Issue by shinoi2** [ClickHouse/ClickHouse#12185]
**Use case**
addIntervals(datetime, amount, interval-unit)
subtractIntervals(datetime, amount, interval-unit)
interval-unit same as "toStartOfInterval" and "dateDiff" function

For example:
```
WITH
    toDate('2018-01-01') AS date,
    toDateTime('2018-01-01 00:00:00') AS date_time
SELECT
    addIntervals(date, 1, 'year') AS add_years_with_date,
    addIntervals(date, 1, 'year') AS add_years_with_date_time
```

**Comment by blinkov** [comment]
@shinoi2 isn't it similar to <https://clickhouse.tech/docs/en/sql-reference/operators/#operator-interval>?

**Comment by filimonov** [comment]
Is it what you are looking for?

```
WITH
    toDate('2018-01-01') AS date,
    toDateTime('2018-01-01 00:00:00') AS date_time
SELECT
    date + INTERVAL 1 YEAR AS add_years_with_date,
    date_time + INTERVAL 1 YEAR AS add_years_with_date_time

┌─add_years_with_date─┬─add_years_with_date_time─┐
│          2019-01-01 │      2019-01-01 00:00:00 │
└─────────────────────┴──────────────────────────┘
```

**Comment by shinoi2** [comment]
In my case, I have a table to save vip recharge table. like this

**Comment by ucasFL** [comment]
:) with toDate('2018-01-01') as d, toDateTime('2018-01-01 00:00:00') as dt select DATE_ADD(year, 1, d), DATE_ADD(year, 1, dt)

```sql
WITH
    toDate('2018-01-01') AS d,
    toDateTime('2018-01-01 00:00:00') AS dt
SELECT
    d + toIntervalYear(1),
    dt + toIntervalYear(1)
```
Query id: dc30ac7a-11ec-42e6-8f78-72dfe43a1ea3

┌─plus(d, toIntervalYear(1))─┬─plus(dt, toIntervalYear(1))─┐
│                 2019-01-01 │         2019-01-01 00:00:00 │
└────────────────────────────┴─────────────────────────────┘

1 rows in set. Elapsed: 0.002 sec.

Looks like what you want is `DATE_ADD` function.
