### ISSUE TITLE
Partition pruning for mutations

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#12188]
Now every mutation touches/renames all parts in all partition (even if they were not touched by mutation).

That has the following disadvantages:
1) losing immutable property - if I do mutation affecting only current day / current partition all old parts get renamed. It is really bad (for example - for backups: to find that the files inside renamed folders were not changed you need to compare inodes which makes backup scripts really complicated).
2) lot of unnecessary filesystem operation if there are lot of partitions
3) huge zookeeper transactions

It seems it should be possible to split huge mutations to per-partition mutations OR  introduce IN PARTITION for ALTER UPDATE / DELETE OR use some other approach to avoid that.

P.S. Also it is possible to apply smth like `optimize_skip_unused_shards` for ON CLUSTER.

**Comment by filimonov** [comment]
```
DROP TABLE IF EXISTS test_mut;

CREATE TABLE test_mut
ENGINE = MergeTree
PARTITION BY k
ORDER BY k AS
SELECT 
    number % 5 AS k, 
    0 AS val
FROM numbers(20);

SELECT 
    _part, 
    k, 
    groupArray(val)
FROM test_mut
GROUP BY 
    _part, 
    k
ORDER BY k ASC

┌─_part───┬─k─┬─groupArray(val)─┐
│ 0_1_1_0 │ 0 │ [0,0,0,0]       │
│ 1_2_2_0 │ 1 │ [0,0,0,0]       │
│ 2_3_3_0 │ 2 │ [0,0,0,0]       │
│ 3_4_4_0 │ 3 │ [0,0,0,0]       │
│ 4_5_5_0 │ 4 │ [0,0,0,0]       │
└─────────┴───┴─────────────────┘

5 rows in set. Elapsed: 0.008 sec.


ALTER TABLE test_mut UPDATE val = 1 WHERE k = 3 SETTINGS mutations_sync = 1;

SELECT 
    _part, 
    k, 
    groupArray(val)
FROM test_mut
GROUP BY 
    _part, 
    k
ORDER BY k ASC

┌─_part─────┬─k─┬─groupArray(val)─┐
│ 0_1_1_0_6 │ 0 │ [0,0,0,0]       │
│ 1_2_2_0_6 │ 1 │ [0,0,0,0]       │
│ 2_3_3_0_6 │ 2 │ [0,0,0,0]       │
│ 3_4_4_0_6 │ 3 │ [1,1,1,1]       │
│ 4_5_5_0_6 │ 4 │ [0,0,0,0]       │
└───────────┴───┴─────────────────┘

5 rows in set. Elapsed: 0.004 sec. 
```

**Comment by alex-zaitsev** [comment]
Another option is to introduce partition based mutations, similar to CLEAR COLUMN for example:
```
ALTER TABLE table_name UPDATE/DELETE expr IN PARTITION partition_expr
```

**Comment by compasses** [comment]
I thought the mutation operation should only modify the parts constrained by the where condition in mutation SQL. If it not work like that, the mutation performance will be very poor for large tables. Am I right?

**Comment by filimonov** [comment]
> If it not work like that, the mutation performance will be very poor for large tables.0 Am I right?

Non-affected parts are not processes just renamed (renames are cheap) . That FR is about avoiding renames when it is not neccessary.

Anyway ALTER rename/delete is quite heavy operation (that's why it called ALTER)

**Comment by compasses** [comment]
OK thanks

**Comment by azat** [comment]
>Now every mutation touches/renames all parts in all partition (even if they were not touched by mutation).

For regular MergeTree the MR is #21326

**Comment by alexey-milovidov** [comment]
It is not possible to skip mutations of unrelated parts because some of the internal invariants will be broken.
