### ISSUE TITLE
How to use ReplicatedReplacingMergeTree for deduplication

### ISSUE THREAD

**Issue by gubinjie** [ClickHouse/ClickHouse#12184]
We created two tables
1. The test.pool engine: ReplicatedReplacingMergeTree
2.test.pool _dis engine: Distributed

When I insert some duplicate data into pool _dis, and execute
optimize table test.pool on cluster xxxx final, duplicate data has not been removed.
Is this what is the reason?

And sometimes this error occurs: cannot execute replicated DDL query on leader

**Comment by den-crane** [comment]
Duplicates are removed from ReplacingMergeTree during parts a merge process. 
Merge combines parts over partition. If you have duplicates in different partitions or at different servers they will not be removed / merged. 
Try select ... from test.pool _dis  **FINAL**

>And sometimes this error occurs: cannot execute replicated DDL query on leader

What CH version do you use?

**Comment by gubinjie** [comment]
@den-crane 20.3.9
