### ISSUE TITLE
About roaringbitmap state sizes

### ISSUE THREAD

**Issue by luojttttt** [ClickHouse/ClickHouse#12261]
I use function **groupBitmapState** to create a roaringbitmap for storing 1 ~ 50million.
And finally the capacity of it is 190MB. As I know, 1 ~ 50million can be stored as  RunContainer in roaringbitmap which can be much more smaller than 190MB. WHY IS THAT？

Here is my code:
```
CREATE TABLE test ( 
ext1 UInt16, 
ext2 AggregateFunction(groupBitmap, UInt32), 
ds UInt32
) ENGINE = ReplacingMergeTree PARTITION BY (ds,ext1) ORDER BY ext1 SETTINGS
index_granularity = 8192;

insert into test
select ext1, groupBitmapState(ext2), 20200706
FROM middle
group by ext1;
```

The data in table middle is like :
`select *  from middle limit 5` 
return:
```
┌ext1┬ext2┬─-ds─┐
│    1 │    1 │ 15618 │
│    1 │    2 │ 15618 │
│    1 │    3 │ 15618 │
│    1 │    4 │ 15618 │
│    1 │    5 │ 15618 │
└──┴──┴────┘
```
column ext2 is Consecutive integers 1~50million

**Comment by jessicacheun** [comment]
Good question! I test it ! Same result ! Is there anybody know it ?

**Comment by jessicacheun** [comment]
@andyyzh help

**Comment by filimonov** [comment]
1) Why ReplacingMergeTree not AggregatingMergeTree? 
2) How do you examine the size? 


```
clickhouse-local  -q 'select groupBitmapState(number) as state from numbers(50000000)' | clickhouse-local --structure 'state String' -q'select length(state) from table'
6256613
```

**Comment by jessicacheun** [comment]
> 1. AggregatingMergeTree

I tried AggregatingMergeTree either, returning the same result

**Comment by filimonov** [comment]
Please show show you get that result (exact queries you run)

**Comment by jessicacheun** [comment]
> Please show how you get that result (exact queries you run), where that 190 Mb number cames from. And you didn't answer other questions above.

select
    table as "table name",
    sum(rows) as "total lines",
    formatReadableSize(sum(data_uncompressed_bytes)) as "origin size",
    formatReadableSize(sum(data_compressed_bytes)) as "compressed size",
    round(sum(data_compressed_bytes) / sum(data_uncompressed_bytes) * 100, 0) "compressed rate"
from system.parts
where table in('test')
group by table;

**Comment by jessicacheun** [comment]
> 1. Why ReplacingMergeTree not AggregatingMergeTree?
> 2. How do you examine the size? Do you do optimize before, how many states (i.e. different ds,ext1 combinations) do your table store?
> 
> ```
> clickhouse-local  -q 'select groupBitmapState(number) as state from numbers(50000000)' | clickhouse-local --structure 'state String' -q'select length(state) from table'
> 6256613
> ```
> 
> 6256613*8 = 50052904 looks correct.
> 
> At the same time if most of the bits will be off it will be only 10 bytes to store single value 50000000
> 
> ```
> clickhouse-local  -q 'select groupBitmapState(number + 50000000) as state from numbers(1)' | clickhouse-local --structure 'state String' -q'select length(state), hex(state) from table'
> 10	000180F0FA0200000000
> ```

I have optimized, there is no difference.
There is only one state in my table

**Comment by filimonov** [comment]
```
CREATE TABLE test
(
    `ext1` UInt16,
    `ext2` AggregateFunction(groupBitmap, UInt32),
    `ds` UInt32
)
ENGINE = AggregatingMergeTree
PARTITION BY (ds, ext1)
ORDER BY ext1
SETTINGS index_granularity = 8192

Ok.

0 rows in set. Elapsed: 0.008 sec. 

INSERT INTO test SELECT 
    toUInt16(1) AS ext1,
    groupBitmapState(toUInt32(number)),
    20200706
FROM numbers(50000000)
GROUP BY ext1

SELECT 
    table AS `table name`,
    sum(rows) AS `total lines`,
    formatReadableSize(sum(data_uncompressed_bytes)) AS `origin size`,
    formatReadableSize(sum(data_compressed_bytes)) AS `compressed size`,
    round((sum(data_compressed_bytes) / sum(data_uncompressed_bytes)) * 100, 0) AS `compressed rate`
FROM system.parts
WHERE table IN ('test')
GROUP BY table

┌─table name─┬─total lines─┬─origin size─┬─compressed size─┬─compressed rate─┐
│ test       │           1 │ 5.97 MiB    │ 30.21 KiB       │               0 │
└────────────┴─────────────┴─────────────┴─────────────────┴─────────────────┘

1 rows in set. Elapsed: 0.030 sec. 
```

**Comment by jessicacheun** [comment]
> ```
> CREATE TABLE test
> (
>     `ext1` UInt16,
>     `ext2` AggregateFunction(groupBitmap, UInt32),
>     `ds` UInt32
> )
> ENGINE = AggregatingMergeTree
> PARTITION BY (ds, ext1)
> ORDER BY ext1
> SETTINGS index_granularity = 8192
> 
> Ok.
> 
> 0 rows in set. Elapsed: 0.008 sec. 
> 
> INSERT INTO test SELECT 
>     toUInt16(1) AS ext1,
>     groupBitmapState(toUInt32(number)),
>     20200706
> FROM numbers(50000000)
> GROUP BY ext1;
> 
> Ok.
> 
> 0 rows in set. Elapsed: 3.409 sec. Processed 50.00 million rows, 400.03 MB (14.67 million rows/s., 117.34 MB/s.) 
> 
> SELECT 
>     table AS `table name`,
>     sum(rows) AS `total lines`,
>     formatReadableSize(sum(data_uncompressed_bytes)) AS `origin size`,
>     formatReadableSize(sum(data_compressed_bytes)) AS `compressed size`,
>     round((sum(data_compressed_bytes) / sum(data_uncompressed_bytes)) * 100, 0) AS `compressed rate`
> FROM system.parts
> WHERE table IN ('test')
> GROUP BY table
> 
> ┌─table name─┬─total lines─┬─origin size─┬─compressed size─┬─compressed rate─┐
> │ test       │           1 │ 5.97 MiB    │ 30.21 KiB       │               0 │
> └────────────┴─────────────┴─────────────┴─────────────────┴─────────────────┘
> 
> 1 rows in set. Elapsed: 0.030 sec. 
> ```
> 
> What did i wrong?

CREATE TABLE test
(
    `ext1` UInt16, 
    `ext2` AggregateFunction(groupBitmap, UInt32), 
    `ds` UInt32
)
ENGINE = AggregatingMergeTree
PARTITION BY (ds, ext1)
ORDER BY ext1
SETTINGS index_granularity = 8192

Ok.

0 rows in set. Elapsed: 0.002 sec. 

INSERT INTO test SELECT 
    toUInt16(1) AS ext1, 
    groupBitmapState(toUInt32(number)), 
    20200706
FROM numbers(50000000) 
GROUP BY ext1

Ok.

0 rows in set. Elapsed: 1.475 sec. Processed 50.00 million rows, 400.03 MB (33.91 million rows/s., 271.27 MB/s.) 

SELECT 
    table AS `table name`, 
    sum(rows) AS `total lines`, 
    formatReadableSize(sum(data_uncompressed_bytes)) AS `origin size`, 
    formatReadableSize(sum(data_compressed_bytes)) AS `compressed size`, 
    round((sum(data_compressed_bytes) / sum(data_uncompressed_bytes)) * 100, 0) AS `compressed rate`
FROM system.parts 
WHERE table IN 'test'
GROUP BY table

┌─table name─┬─total lines─┬─origin size─┬─compressed size─┬─compressed rate─┐
│ test       │           1 │ 190.73 MiB  │ 191.49 MiB      │             100 │
└────────────┴─────────────┴─────────────┴─────────────────┴─────────────────┘

1 rows in set. Elapsed: 0.003 sec. 

emme.....what's the problem?

**Comment by jessicacheun** [comment]
> ```
> CREATE TABLE test
> (
>     `ext1` UInt16,
>     `ext2` AggregateFunction(groupBitmap, UInt32),
>     `ds` UInt32
> )
> ENGINE = AggregatingMergeTree
> PARTITION BY (ds, ext1)
> ORDER BY ext1
> SETTINGS index_granularity = 8192
> 
> Ok.
> 
> 0 rows in set. Elapsed: 0.008 sec. 
> 
> INSERT INTO test SELECT 
>     toUInt16(1) AS ext1,
>     groupBitmapState(toUInt32(number)),
>     20200706
> FROM numbers(50000000)
> GROUP BY ext1;
> 
> Ok.
> 
> 0 rows in set. Elapsed: 3.409 sec. Processed 50.00 million rows, 400.03 MB (14.67 million rows/s., 117.34 MB/s.) 
> 
> SELECT 
>     table AS `table name`,
>     sum(rows) AS `total lines`,
>     formatReadableSize(sum(data_uncompressed_bytes)) AS `origin size`,
>     formatReadableSize(sum(data_compressed_bytes)) AS `compressed size`,
>     round((sum(data_compressed_bytes) / sum(data_uncompressed_bytes)) * 100, 0) AS `compressed rate`
> FROM system.parts
> WHERE table IN ('test')
> GROUP BY table
> 
> ┌─table name─┬─total lines─┬─origin size─┬─compressed size─┬─compressed rate─┐
> │ test       │           1 │ 5.97 MiB    │ 30.21 KiB       │               0 │
> └────────────┴─────────────┴─────────────┴─────────────────┴─────────────────┘
> 
> 1 rows in set. Elapsed: 0.030 sec. 
> ```
> 
> What did i wrong?

My version is :
SELECT version()

┌─version()─┐
│ 19.5.2.6  │
└───────────┘

**Comment by yingfeng** [comment]
19.5.2.6 is too old. 
The serialization of groupBitmapState has been adjusted, additionally, previous aggregation data format requires to be escaped with Base64 encoding, which leads to remarkable overhead.

**Comment by jessicacheun** [comment]
> 19.5.2.6 is too old.
> The serialization of groupBitmapState has been adjusted, additionally, previous aggregation data format requires to be escaped with Base64 encoding, which leads to remarkable overhead.

Done!!!!

**Comment by yinjiakang** [comment]
> 19.5.2.6 is too old.
> The serialization of groupBitmapState has been adjusted, additionally, previous aggregation data format requires to be escaped with Base64 encoding, which leads to remarkable overhead.

so , from which version is this feature available ?  thx
