### ISSUE TITLE
https://yandex.ru/dev/clickhouse/ web page is outdated.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#12281]
It contains only some fragmentary four year old information.

**Comment by alexey-milovidov** [comment]
Still outdated.

**Comment by alexey-milovidov** [comment]
Still outdated, contains incomplete info.

**Comment by alexey-milovidov** [comment]
Outdated still.

**Comment by Algunenano** [comment]
I don't see anything odd and it's out of our control
