### ISSUE TITLE
matrix entrywise addition

### ISSUE THREAD

**Issue by 01egen** [ClickHouse/ClickHouse#12282]
Need an analog function SumForEach() for sum 2D arrays

What is the proper and fastest way to calculate entrywise sum of matrix in table?

```
create TABLE t1 (
s String,
m Array(Array(UInt8))
) ENGINE = MergeTree() order by s;

INSERT INTO 1 VALUES ('key1', [[1,2], [3,4] ]), ('key2', [[5,6], [7,8]]) ;

```
as a result, I want to see one row with the resulting matrix

```
┌─m─────────────┐
│[[6,8],[10,12]]│
└───────────────┘

```

https://en.wikipedia.org/wiki/Matrix_addition
https://proofwiki.org/wiki/Definition:Matrix_Entrywise_Addition

**Comment by 01egen** [comment]
The answer turned out to be very simple and was found elsewhere
(https://stackoverflow.com/questions/62814185/clickhouse-matrix-entrywise-addition-how-to-sum-2-dimensional-arrays)

`SELECT sumForEachForEach(m) FROM t1`

**Comment by mrcrypster** [comment]
This doesn't work with 22.12.1:

```sql
SELECT sumForEachForEach(m)
FROM
(
    SELECT [[1, 2], [3, 4]] AS m
    UNION ALL
    SELECT [[4, 3], [2, 1]] AS m
)

Code: 184. DB::Exception: Received from p1s7zepm0o.eu-central-1.aws.clickhouse.cloud:9440. DB::Exception: Nested identical combinator 'ForEach' is not supported. (ILLEGAL_AGGREGATION)
```
