### ISSUE TITLE
superset connect to clickhouse via mysql protocol, report error

### ISSUE THREAD

**Issue by mdianjun** [ClickHouse/ClickHouse#12283]
When add a database in superset, connect to clickhouse，it report this error: 

![image](https://user-images.githubusercontent.com/12122541/86885194-6a540d00-c127-11ea-9fee-69195a5ef6d6.png)

Because clickhouse doesn't support "SHOW VARIABLES"。 

If the code about "show variables" is commented from superset, another error will be reported:

![image](https://user-images.githubusercontent.com/12122541/86885317-a0918c80-c127-11ea-832d-5012c6c83208.png)

Clickhouse doesn't support "select database()" either.

Will clickhouse be planned to support the integration with superset?

**Comment by filimonov** [comment]
Why do you connect from SuperSet using Mysql protocol? 

It have native support for clickhouse: https://github.com/apache/incubator-superset/pull/1844

About MySQL compatibility - see https://github.com/ClickHouse/ClickHouse/issues/9336 @BohuTANG is working on that, AFAIK.
