### ISSUE TITLE
Predicate push down for views containing WITH clause.

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#12293]
```
drop table IF EXISTS numbers_indexed;
drop table IF EXISTS squares;

create table numbers_indexed Engine=MergeTree ORDER BY number PARTITION BY bitShiftRight(number,8) SETTINGS index_granularity=8 AS SELECT * FROM numbers(16384); 

CREATE VIEW squares AS WITH number*2 AS square_number SELECT number, square_number FROM numbers_indexed;

SET max_rows_to_read=8, read_overflow_mode='throw';

-- ok
WITH number*2 AS square_number SELECT number, square_number FROM numbers_indexed WHERE number = 999;

-- fail
SELECT * FROM squares WHERE number = 999;
```

**Comment by alexey-milovidov** [comment]
CC @zhang2014

**Comment by zhang2014** [comment]
https://github.com/ClickHouse/ClickHouse/blob/master/src/Interpreters/PredicateRewriteVisitor.cpp#L88

Is expected, but i thought maybe we could remove it.

**Comment by filimonov** [comment]
I though about it and didnt find any obvious use cases when it can lead to problems. Do you know some?

**Comment by filimonov** [comment]
Also may be we should have a possibility to push down predicates somehow in other cases which are currently forbinned (final, limit etc).

Either by special setting (push the respinsibility to the user) either by implementing smth like prewhere for views, either by distinguishing which column are real and not affected by any limit / final etc. (last one sounds complicated)

**Comment by 4ertus2** [comment]
We could have troubles with `prefer_alias_to_column_name` logic if we enable it. Probably we need some investigation here.
