### ISSUE TITLE
missing documentation for SHOW ROW POLICIES statement

### ISSUE THREAD

**Issue by MyroTk** [ClickHouse/ClickHouse#12309]
**Describe the issue**
The command `show row policies` exists and works in client, but there's no documentation on the website for the syntax or usage.

**Additional context**
```ClickHouse client version 20.5.2.7 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 20.5.2 revision 54435.

clicktest :) show row policies

SHOW ROW POLICIES

┌─name───────────────────────┐
│ policy0 ON datasets.ontime │
└────────────────────────────┘

1 rows in set. Elapsed: 0.008 sec.

clicktest :)

**Comment by bharatnc** [comment]
This looks like it was resolved via: https://github.com/ClickHouse/ClickHouse/pull/12328

**Comment by adevyatova** [comment]
Completed: https://clickhouse.tech/docs/en/sql-reference/statements/show/#show-policies-statement
