### ISSUE TITLE
Incomplete documentation of ALTER SETTINGS PROFILE statement

### ISSUE THREAD

**Issue by MyroTk** [ClickHouse/ClickHouse#12312]
**Describe the issue**
The statement `ALTER SETTINGS PROFILE` uses `TO` assignment clause, but documentation syntax does not show this.

**Additional context**
https://clickhouse.tech/docs/en/sql-reference/statements/alter/#alter-settings-profile-statement
```ClickHouse client version 20.5.2.7 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 20.5.2 revision 54435.

clicktest :) ALTER SETTINGS PROFILE prof0 TO user0

ALTER SETTINGS PROFILE prof0 TO user0

Ok.

0 rows in set. Elapsed: 0.006 sec.

clicktest :)

**Comment by bharatnc** [comment]
Looks like this is fixed by the above referenced PR i.e https://github.com/ClickHouse/ClickHouse/pull/14515. Uses `TO` assignment now.
