### ISSUE TITLE
Incomplete documentation of CREATE SETTINGS PROFILE statement

### ISSUE THREAD

**Issue by MyroTk** [ClickHouse/ClickHouse#12311]
**Describe the issue**
The statement `CREATE SETTINGS PROFILE` uses a `TO` assignment clause, but the syntax on the documentation doesn't mention this.

**Additional context**
https://clickhouse.tech/docs/en/sql-reference/statements/create/#create-settings-profile-statement
```ClickHouse client version 20.5.2.7 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 20.5.2 revision 54435.

clicktest :) CREATE SETTINGS PROFILE prof0 TO user0

CREATE SETTINGS PROFILE prof0 TO user0

Ok.

0 rows in set. Elapsed: 0.003 sec.

clicktest :)

**Comment by adevyatova** [comment]
Completed: https://clickhouse.tech/docs/en/sql-reference/statements/create/settings-profile/
