### ISSUE TITLE
clickhouse select is not effect when the condition contains fixstring field

### ISSUE THREAD

**Issue by thomasbryant1024** [ClickHouse/ClickHouse#12324]
the SQL doesn't query any data but the table has the project data ：

* select * from access_log where entity_type = 'project';

By the way, all the fixString field isn't effect.

My clickhouse version is  19.17.9.60

**Comment by filimonov** [comment]
It looks like duplicate of https://github.com/ClickHouse/ClickHouse/issues/9272

**Comment by filimonov** [comment]
Update to 20.4 or pad/cast the strings manually
