### ISSUE TITLE
sql execution result is incorrect

### ISSUE THREAD

**Issue by hiliuxg** [ClickHouse/ClickHouse#12329]
![image](https://user-images.githubusercontent.com/39675622/87034746-f2670f00-c21a-11ea-8c82-183b2156d76d.png)

the version : 20.4.4.18

**Comment by realyota** [comment]
It's not a bug, after you aliased the column it is used globally. Have a look at: https://clickhouse.tech/docs/en/sql-reference/syntax/#syntax-expression_aliases

**Comment by den-crane** [comment]
Use table specification  if you need  aliased column

select a, **t.a**, a/2 as a, a from (select 3 a) as t
```
┌───a─┬─a─┬───a─┬───a─┐
│ 1.5 │ 3 │ 1.5 │ 1.5 │
└─────┴───┴─────┴─────┘
```

**Comment by hiliuxg** [comment]
@realyota @den-crane Is this the standard sql syntax? This is different from the syntax of hive and presto. It is also different from the public's usage habits. I just thought it was a bug.

**Comment by den-crane** [comment]
@hiliuxg No it's against standard sql. CH feature.

pssql

```
select a, t.a, a/2 as a, a from (select 3 a) as t
 a | a | a | a
---+---+---+---
 3 | 3 | 1 | 3
```
