### ISSUE TITLE
alter table tablename drop partition erro Cannot execute replicated DDL query on leader

### ISSUE THREAD

**Issue by wanghaifen** [ClickHouse/ClickHouse#12322]
i build a clickhouse cluster with 3 nodes,the metrika.xml detail information:use * replcace the ip in there

<yandex>
<clickhouse_remote_servers>
    <test_ck_cluster>
        <shard>
            <internal_replication>true</internal_replication>
            <replica>
                <host>10-200-2-*.office.17zuoye.net</host>
                <port>9001</port>
                <user>default</user>
                <password>17ck-test-wr</password>
            </replica>
        </shard>
        <shard>
            <internal_replication>true</internal_replication>
            <replica>
                <host>10-200-2-*.office.17zuoye.net</host>
                <port>9001</port>
                <user>default</user>
                <password>17ck-test-wr</password>
            </replica>
        </shard>
        <shard>
            <internal_replication>true</internal_replication>
            <replica>
                <host>10-200-2-*.office.17zuoye.net</host>
                <port>9001</port>
                <user>default</user>
                <password>17ck-test-wr</password>
            </replica>
        </shard>
    </test_ck_cluster>
</clickhouse_remote_servers>
<macros>
    <cluster>test_ck_cluster</cluster>
    <shard>01</shard>
    <replica>10.200.2.*</replica>
</macros>
<networks>
   <ip>::/0</ip>
</networks>

<zookeeper-servers>
  <node index="1">
    <host>10.200.2.*</host>
    <port>2181</port>
  </node>
  <node index="2">
    <host>10.200.2.*</host>
    <port>2181</port>
  </node>
  <node index="3">
    <host>10.200.2.*</host>
    <port>2181</port>
  </node>
</zookeeper-servers>

<clickhouse_compression>
<case>
  <min_part_size>10000000000</min_part_size>
  <min_part_size_ratio>0.01</min_part_size_ratio>
  <method>lz4</method>
</case>
</clickhouse_compression>
</yandex>

the partition is exist,operation: on cluster drop

ALTER TABLE market.vb_xue_order_sku_user_lesson_detail_5_minutes_replica ON CLUSTER test_ck_cluster DROP PARTITION (20200709, 168)

bug information:
ALTER TABLE market.vb_xue_order_sku_user_lesson_detail_5_minutes_replica ON CLUSTER test_ck_cluster DROP PARTITION (20200709, 168)

┌─host────────────────────────────┬─port─┬─status─┬─error─┬─num_hosts_remaining─┬─num_hosts_acti┐
│ 10-200-2-124.office.17zuoye.net │ 9001 │      0 │       │                   2 │                1 │
│ 10-200-2-125.office.17zuoye.net │ 9001 │      0 │       │                   1 │                1 │
└─────────────────────────────────┴──────┴────────┴───────┴──────────────────────────────────────┘
┌─host────────────────────────────┬─port─┬─status─┬─error─────────────────────────────────────────┬─num_hosts_remainin
g─┬─num_hosts_active─┐│ 10-200-2-126.office.17zuoye.net │ 9001 │     48 │ Cannot execute replicated DDL query on leader │                   
0 │                0 │└─────────────────────────────────┴──────┴────────┴───────────────────────────────────────────────┴───────────────────
──┴──────────────────┘? Progress: 2.00 rows, 150.00 B (0.25 rows/s., 18.86 B/s.)  66%Received exception from server (version 19.16.14):
Code: 48. DB::Exception: Received from 10.200.2.126:9001. DB::Exception: There was an error on [10-200-2-126.office.17
zuoye.net:9001]: Cannot execute replicated DDL query on leader

single node drop:
ALTER TABLE market.vb_xue_order_sku_user_lesson_detail_5_minutes_replica      DROP 
PARTITION (20200709, 168);

bug information:
Code: 292. DB::Exception: Received from 10.200.2.126:9001. DB::Exception: Leader was suddenly changed or logical error
..

**Comment by den-crane** [comment]
>cluster with 3 nodes

Do you mean 1shard with 3 replicas or you mean cross-replication (circle replication)?

**Comment by wanghaifen** [comment]
Thanks Denis：
the mean is 1shard with 1replicas，why set this，because the cluster is test cluster




| |
18101350634
|
|
邮箱：18101350634@163.com
|

Signature is customized by Netease Mail Master

On 07/10/2020 02:29, Denis Zhuravlev wrote:

cluster with 3 nodes

Do you mean 1shard with 3 replicas or you mean cross-replication (circle replication)?

**Comment by den-crane** [comment]
BTW I don't understand is it work OK or not
```
single node drop:
ALTER TABLE market.vb_xue_order_sku_user_lesson_detail_5_minutes_replica DROP
PARTITION (20200709, 168);
```

**Comment by wanghaifen** [comment]
it is not work sometimes single node drop




| |
18101350634
|
|
邮箱：18101350634@163.com
|

Signature is customized by Netease Mail Master

On 07/10/2020 04:37, Denis Zhuravlev wrote:

BTW I don't understand is it work OK or not

single node drop:
ALTER TABLE market.vb_xue_order_sku_user_lesson_detail_5_minutes_replica DROP
PARTITION (20200709, 168);

**Comment by wanghaifen** [comment]
it is not work sometimes single node drop，it is not work sometimes use on cluster ck_test_cluster。
accessory is the clickhouse cluster  configuration files and the detailed information of the bug and the  create table  sql  file of  ReplicatedMergeTree table,Distributed table
I hope I can make that clear,Thanks for the great product Clickhouse








| |
18101350634
|
|
邮箱：18101350634@163.com
|

Signature is customized by Netease Mail Master

On 07/10/2020 04:37, Denis Zhuravlev wrote:

BTW I don't understand is it work OK or not

single node drop:
ALTER TABLE market.vb_xue_order_sku_user_lesson_detail_5_minutes_replica DROP
PARTITION (20200709, 168);

**Comment by den-crane** [comment]
It's unclear what is wrong here. Probably it's a circle replication. On cluster now is supported for circle replication. 
I am closing it.
