### ISSUE TITLE
Round function does not behave as it should be

### ISSUE THREAD

**Issue by eleong08** [ClickHouse/ClickHouse#12393]
**Issue:** 
The round function does not work on -0.1 to -0.5.

**ClickHouse server version:**
19.16.7.24
20.3.12.112

**How to reproduce**
Execute the following query,

     select -1/2 as x,round(x)

> Returned output: -0

**Expected behavior**
It should return -1

**Additional context**
According to Clickhouse documentation, if decimal-places < 0, then the function rounds the value to the left of the decimal point. Correct me if I'm wrong.

Thanks!!

**Comment by den-crane** [comment]
https://clickhouse.tech/docs/en/sql-reference/functions/rounding-functions/#rounding_functions-round

round(x[, N]) 

Rounds a value to a specified number of decimal places.

The function returns the nearest number of the specified order. In case when given number has equal distance to surrounding numbers, the function uses **banker’s rounding** for float number types and rounds away from zero for the other number types.

**Comment by lhuang09287750** [comment]
Is there a round-like function that rounds away from zero for float number types ?
Thanks for reply!
