### ISSUE TITLE
how joinGet with multiple keys ?

### ISSUE THREAD

**Issue by mbtolou** [ClickHouse/ClickHouse#12409]
```sql
CREATE TABLE [IF NOT EXISTS] [db.]table_name [ON CLUSTER cluster]
(
    name1 [type1] [DEFAULT|MATERIALIZED|ALIAS expr1] [TTL expr1],
    name2 [type2] [DEFAULT|MATERIALIZED|ALIAS expr2] [TTL expr2],
) ENGINE = Join(join_strictness, join_type, k1[, k2, ...])
```

in defenition of join table can define multiple keys :
`
ENGINE = Join(join_strictness, join_type, k1[, k2, ...])
`
but cannot use multiple keys in **joinGet** like:

select joinGet('TEST_TABLE','TEST_VALUE',1)
from system.one

**Comment by den-crane** [comment]
joinGet only supports StorageJoin containing exactly one key.

**Comment by alexey-milovidov** [comment]
CC @amosbird

**Comment by adrian17** [comment]
(You can work around this by having a tuple (k1, k2) column and using it as a key.)

**Comment by den-crane** [comment]
> (You can work around this by having a tuple (k1, k2) column and using it as a key.)

it's not true.

**Comment by adrian17** [comment]
I meant having `key` be a tuple type column:

```sql
create table jtest(
    key Tuple(String, String),
    value Float64
) engine=Join(any, left, key);
insert into jtest values(('a', 'b'), 15)
select joinGet(jtest, 'value', ('a', 'b'))
=> 15
```

Might not work for all use cases, but for "joinGet with a complex key" this does work.

**Comment by den-crane** [comment]
@adrian17 good catch, I did not know that.

**Comment by mbtolou** [comment]
thanks

> I meant having `key` be a tuple type column:
> 
> ```sql
> create table jtest(
>     key Tuple(String, String),
>     value Float64
> ) engine=Join(any, left, key);
> insert into jtest values(('a', 'b'), 15)
> select joinGet(jtest, 'value', ('a', 'b'))
> => 15
> ```
> 
> Might not work for all use cases, but for "joinGet with a complex key" this does work.

thanks

**Comment by amosbird** [comment]
It's fixed in https://github.com/ClickHouse/ClickHouse/pull/13015
