### ISSUE TITLE
Way to optimize out unused sub-expressions?

### ISSUE THREAD

**Issue by mzealey** [ClickHouse/ClickHouse#12419]
I'm trying to integrate with Grafana and allow values to sometimes be 'All' or sometimes filter by a specific number. I have set it so that if 'all' the number will be 0, if > 0 it will search a couple of columns. I've tried several ways to do this:

```
WHERE (($port = 0) OR ((DstPort = $port) OR (SrcPort = $port))
```

```
WHERE IF($port = 0, 1, DstPort = $port OR SrcPort = $port)
```

The `IF` version seems to work a bit quicker but they are both adding ~15-20% on to my query times (typically 6-8s). I would have thought a static optimizer could see that as `0=0` is a fixed expression it wouldn't need to pull in DstPort/SrcPort columns, but I'm guessing its doing this and this is the reason for the slowdown?

I am using the clickhouse:20 docker image.

**Comment by den-crane** [comment]
yes such optimization is not implemented 
duplicate https://github.com/ClickHouse/ClickHouse/issues/658
