### ISSUE TITLE
Materialized Views

### ISSUE THREAD

**Issue by mauidude** [ClickHouse/ClickHouse#12415]
How does clickhouse handle updates to materialized views built from another table? If something is written to the underlying table, when and how does that update get applied to the materialized view? What happens if the process is stopped (either gracefully or ungracefully) after the update occurs to the base table before making it to the materialized view? Will the update be applied when the process starts back up or is the update to the base table in an uncommitted state and rolled back?

**Comment by den-crane** [comment]
Materialized view (MV) is a post-insert trigger. Insert to a source table pushes an inserted buffer to MV as well. 
MV does select over the inserted buffer (MV never reads the source table except populate stage).

MV does not see `alter  update/delete`. 
MV does not see changes any changes from merge process collapsing/replacing.

No transactions. No atomicity. Partial insert is possible. 
Insert into the source table can succeed and fail into MV. A client will gate an error message in this case.

**Comment by mauidude** [comment]
Thanks for answering that, I couldn't find it in the docs anywhere. Is there any way to get atomicity between a table and a materialized view?

**Comment by den-crane** [comment]
You can implement idempotent inserts and get consistent tables with retries against replicated tables.
But it's tricky. Check this https://clickhouse.tech/docs/en/operations/settings/settings/#settings-deduplicate-blocks-in-dependent-materialized-views

**Comment by mauidude** [comment]
Thanks for pointing that out. Ok so if I understand correctly, by enabling that setting, if that scenario happens where an insert succeeds in the table but not the MV, the client would receive an error and would need to retry the insert. When it retries, the table will see it as a duplicate insert and ignore it but the MV will see it as a new insert and will get the new data?
Are there any side effects caused by enabling that setting? Like is performance worse? Or will duplicates be more likely? Or anything else like that?

**Comment by den-crane** [comment]
A1: Yes.

A2: Doc: _This behaviour exists to enable insertion of highly aggregated data into materialized views, for cases where inserted blocks are the same after materialized view aggregation but derived from different INSERTs into the source table._
https://github.com/ClickHouse/ClickHouse/issues/5274
