### ISSUE TITLE
need the doc of postgres wire interface

### ISSUE THREAD

**Issue by l1t1** [ClickHouse/ClickHouse#12420]
(you don't have to strictly follow this form)
version 20.5 changelog says it supports that feature, but cannot find the example in the document
**Describe the issue**
A clear and concise description of what's wrong in documentation.

**Additional context**

**Comment by alexey-milovidov** [comment]
CC @MovElb

**Comment by DanRoscigno** [comment]
closed by https://github.com/ClickHouse/ClickHouse/commit/72b0cbbb538f344f61169fb74d369c1bc1d16d83
