### ISSUE TITLE
Codec for Huffman coding?

### ISSUE THREAD

**Issue by mzealey** [ClickHouse/ClickHouse#12429]
Let's say we are wanting to logs of record traffic between different servers. The TCP port value may be anything that is UInt16, however we know that 90% of the data will be split between 10 well known ports eg 443, 80, 53, ... however the data will be coming in randomly so I don't see that any of the existing CODECs support this use-case? As I understand it, LowCardinality is not really meant for this. Perhaps the solution is just to stick with the standard LZ4 compression or whatever but is there a way to use something like Huffman coding to optimize this data type? Appreciating that it is probably difficult to do Huffman coding before you have a good sample of the data, but perhaps when optimizing it would recode all the values?

**Comment by den-crane** [comment]
Zstandard includes Huffman coding. You can use ZSTD CODEC.
