### ISSUE TITLE
Question about JSON functions？

### ISSUE THREAD

**Issue by vkingnew** [ClickHouse/ClickHouse#12471]
Do you have a plan to implements the MySQL's JSON functions?
https://dev.mysql.com/doc/refman/8.0/en/json-function-reference.html
 
As of version 20.5.2.7,JSON function as following:
>Clickhouse> select * from functions where name like '%JSON%';
>SELECT *
FROM functions
WHERE name LIKE '%JSON%'
>┌─name────────────────────────┬─is_aggregate─┬─case_insensitive─┬─alias_to─┐
│ JSONExtractRaw              │            0 │                0 │          │
│ JSONExtractKeysAndValues    │            0 │                0 │          │
│ JSONExtract                 │            0 │                0 │          │
│ JSONExtractString           │            0 │                0 │          │
│ JSONExtractFloat            │            0 │                0 │          │
│ JSONExtractInt              │            0 │                0 │          │
│ JSONType                    │            0 │                0 │          │
│ JSONKey                     │            0 │                0 │          │
│ JSONExtractArrayRaw         │            0 │                0 │          │
│ JSONExtractKeysAndValuesRaw │            0 │                0 │          │
│ JSONHas                     │            0 │                0 │          │
│ JSONLength                  │            0 │                0 │          │
│ JSONExtractUInt             │            0 │                0 │          │
│ JSONExtractBool             │            0 │                0 │          │
│ isValidJSON                 │            0 │                0 │          │
└─────────────────────────────┴──────────────┴──────────────────┴──────────┘

15 rows in set. Elapsed: 0.002 sec.

**Comment by alexey-milovidov** [comment]
New version 21.8 has partial support for SQL/JSON.
