### ISSUE TITLE
Avro: Allow insert specific columns 

### ISSUE THREAD

**Issue by hanguyen6** [ClickHouse/ClickHouse#12481]
**Describe the bug**
I have a table with some Nullable(T) columns and trying to insert Avro file while mentioning column names in the INSERT query 

```
┌─name─────┬─type───────────── ┬─default_type─┬─default_expression─┬
│ dim1                 │ String                                  │ DEFAULT          │ ''                                 │
│ dim2                 │ String                                  │ DEFAULT          │ ''                                 │
│ metric1             │ Nullable(Int64)  │               │                          │
│ metric2             │ Nullable(Float64)│              │                         │
│ metric3             │ Nullable(Float64)│              │                         │
└──────────────────────────────────--───────────────────
```

`cat /tmp/file.avro  | clickhouse-client --query='INSERT INTO db.table(dim1, dim2) FORMAT Avro'`

The insert did not go through, throwing exception: 

> std::exception. Code: 1001, type: std::__1::bad_function_call, e.what() = std::exception (version 20.3.12.112 (official build))

**Expected behavior**
- Insert values of mentioned columns

**Comment by oandrew** [comment]
Could you provide a file sample?

**Comment by alexey-milovidov** [comment]
@hanguyen6 We need more details on this issue, at lease the stack trace.

**Comment by hanguyen6** [comment]
I no longer see the issue. Will reopen this ticket with stack trace if the issue happens again. Thanks
