### ISSUE TITLE
CSVWithNames via HTTP lacks header row on 20.4.7.67

### ISSUE THREAD

**Issue by laingawbl** [ClickHouse/ClickHouse#12504]
**Describe the bug**
When using the HTTP interface, the CSVWithNames result format looks like just CSV, lacking the header row. It behaves properly via `clickhouse-client` though.

**How to reproduce**
```bash
~$ echo "select * from system.build_options
> where name='VERSION_DESCRIBE' format CSVWithNames" |
> curl localhost:8123 --data-binary @-
"VERSION_DESCRIBE","v20.4.7.67-stable"
```
```sql
host :) select * from system.build_options where name='VERSION_DESCRIBE' format CSVWithNames

SELECT *
FROM system.build_options
WHERE name = 'VERSION_DESCRIBE'
FORMAT CSVWithNames

"name","value"
"VERSION_DESCRIBE","v20.4.7.67-stable"
```

**Expected behavior**
The two results should match, and both have the header row with field names.

**Additional context**
TSVWithNames seems to work OK on both interfaces. Both were working on the last 20.4.6... version.

**Comment by pankajsoni19** [comment]
I am using clickhouse ami on aws `Debian GNU/Linux 9.13 (stretch)`
I recently updated to v20.6.4.44-stable using `apt upgrade`. This has effected the reports that we are using.

When will this be released and available for upgrade on the debian instance?
