### ISSUE TITLE
Random server tcp connection failed

### ISSUE THREAD

**Issue by toby080508050805** [ClickHouse/ClickHouse#12509]
We use clickhouse version: 19.17.5.18
We have some application servers randomly failed to connect by tcp protocol but can connect via curl(curl 'http://10.2.3.153:8123/?query=SELECT%201). If use clickhouse-client to login it will show code:210. DB::NetException: connection reset by peer.

Our  clickhouse setting  most of parameters are the default except following 3 settings.
use_uncompressed_cache = 0 
load_balancing =In_order
max_memory_usage=50000000000

I also foud there has 32 queries which try to get data via distributed table to get data from other servers and it already process 45907 to 60916 seconds.  Each distributed table has 44 instance in cluster.

Is the stock queries  is a root cause to failed tcp connection?
Do I have any settings to avoid these queries stock in database?

Thank you

**Comment by den-crane** [comment]
Do you observe any messages about incoming connection in clickhouserver.log ?

**Comment by toby080508050805** [comment]
In log, our grafana still grep data from system.metrics. Also we have some other data insert to our buffer table via distributed table.

**Comment by toby080508050805** [comment]
Following is the scenario I encounter today. I cannot access into clickhouse via tcp port 9000 but i can access it by curl via 8123. There has no query in DATA BASE. I try apply telnet to access 9000 and it disconnect immediately. 

` curl 'http://10.2.3.152:8123/?query=SELECT%20*%20from%20system.processes;'`

> 1       default 5feda61f-75dc-4ecc-8e85-7a15070f9470    ::ffff:10.2.3.152       57846   default 5feda61f-75dc-4ecc-8e85-7a15070f9470    ::ffff:10.2.3.152       57846   2                               0       0 00       1       curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.19.1 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2          0.000901489     0       0       0       0       0       0       0       0 SELECT * from system.processes;\n        [260]   [171938]        ['Query','SelectQuery','IOBufferAllocs','IOBufferAllocBytes','ContextLock','RWLockAcquiredReadLocks']   [1,1,2,2097182,15,1]    ['max_distributed_connections','tcp_keep_alive_timeout','distributed_connections_pool_size','use_uncompressed_cache','load_balancing','distributed_aggregation_memory_efficient','skip_unavailable_shards','optimize_skip_unused_shards','mark_cache_min_lifetime','log_queries','readonly','max_memory_usage']       ['1024','600','1024','0','in_order','1','1','1','5000','0','2','50000000000']


<img width="332" alt="disconnect" src="https://user-images.githubusercontent.com/55230942/87926381-33c9ab00-cab4-11ea-8d53-ed28b3183457.PNG">

**Comment by den-crane** [comment]
Check CH logs at this moment in time. 
The issue is unclear. 
No proof that the reason is CH not a network or a firewall. 
No steps to reproduce.

**Comment by toby080508050805** [comment]
I found some clues. There has a query which stock at clickhouse. The query is sent from remote server via distribute table. It seems like wait over 15 mins so our procedures try to cancel(kill)  queries but it still stock at system. After a while, the 9000 port cannot be connected.

```
2020.07.28 10:58:16.060644 [ 390 ] {1271c3c8-8f46-4b01-85a7-4eee6d79a94b} <Debug> executeQuery: (from [::ffff:192.168.177.4]:39208, initial_query_id: da045f5e-07b6-404f-b69f-ff75280cd647) SELECT ID AS id, sum(VOLUME) / 1024 AS val, NULL AS height FROM merge_table.table_position AS fact WHERE (DATA_DATE = '2020-07-24') AND (ID IN (7144, 7141, 7142)) AND (ID2 > 0) AND ((id >= 5476377362770542592) AND (id <= 5476377362770558975)) GROUP BY id HAVING val > 0
2020.07.28 10:58:16.211347 [ 390 ] {1271c3c8-8f46-4b01-85a7-4eee6d79a94b} <Debug> table_position.archive (SelectExecutor): Key condition: unknown, unknown, and, unknown, and, unknown, unknown, and, and
2020.07.28 10:58:16.211464 [ 390 ] {1271c3c8-8f46-4b01-85a7-4eee6d79a94b} <Debug> table_position.archive (SelectExecutor): MinMax index condition: (column 0 in [18467, 18467]), (column 1 in 3-element set), and, unknown, and, unknown, unknown, and, and
2020.07.28 10:58:16.211519 [ 390 ] {1271c3c8-8f46-4b01-85a7-4eee6d79a94b} <Debug> table_position.archive (SelectExecutor): Selected 1 parts by date, 1 parts by key, 49012 marks to read from 1 ranges
2020.07.28 10:58:16.212149 [ 390 ] {1271c3c8-8f46-4b01-85a7-4eee6d79a94b} <Trace> table_position.archive (SelectExecutor): Reading approx. 401066382 rows with 44 streams
2020.07.28 10:58:16.309208 [ 390 ] {1271c3c8-8f46-4b01-85a7-4eee6d79a94b} <Debug> table_position.recent (SelectExecutor): Key condition: unknown, unknown, and, unknown, and, unknown, unknown, and, and
2020.07.28 10:58:16.309346 [ 390 ] {1271c3c8-8f46-4b01-85a7-4eee6d79a94b} <Debug> table_position.recent (SelectExecutor): MinMax index condition: (column 0 in [18467, 18467]), (column 2 in 3-element set), and, unknown, and, unknown, unknown, and, and
2020.07.28 10:58:16.309405 [ 390 ] {1271c3c8-8f46-4b01-85a7-4eee6d79a94b} <Debug> table_position.recent (SelectExecutor): Selected 0 parts by date, 0 parts by key, 0 marks to read from 0 ranges
2020.07.28 10:58:16.322429 [ 390 ] {1271c3c8-8f46-4b01-85a7-4eee6d79a94b} <Debug> table_position.recent_20200727 (SelectExecutor): Key condition: unknown, unknown, and, unknown, and, unknown, unknown, and, and
2020.07.28 10:58:16.322517 [ 390 ] {1271c3c8-8f46-4b01-85a7-4eee6d79a94b} <Debug> table_position.recent_20200727 (SelectExecutor): MinMax index condition: (column 0 in [18467, 18467]), (column 2 in 3-element set), and, unknown, and, unknown, unknown, and, and
2020.07.28 10:58:16.322544 [ 390 ] {1271c3c8-8f46-4b01-85a7-4eee6d79a94b} <Debug> table_position.recent_20200727 (SelectExecutor): Selected 0 parts by date, 0 parts by key, 0 marks to read from 0 ranges
2020.07.28 10:58:16.342540 [ 390 ] {1271c3c8-8f46-4b01-85a7-4eee6d79a94b} <Debug> table_position.recent_20200728 (SelectExecutor): Key condition: unknown, unknown, and, unknown, and, unknown, unknown, and, and
2020.07.28 10:58:16.342614 [ 390 ] {1271c3c8-8f46-4b01-85a7-4eee6d79a94b} <Debug> table_position.recent_20200728 (SelectExecutor): MinMax index condition: (column 0 in [18467, 18467]), (column 2 in 3-element set), and, unknown, and, unknown, unknown, and, and
2020.07.28 10:58:16.342636 [ 390 ] {1271c3c8-8f46-4b01-85a7-4eee6d79a94b} <Debug> table_position.recent_20200728 (SelectExecutor): Selected 0 parts by date, 0 parts by key, 0 marks to read from 0 ranges
2020.07.28 10:58:16.342788 [ 390 ] {1271c3c8-8f46-4b01-85a7-4eee6d79a94b} <Trace> InterpreterSelectQuery: FetchColumns -> WithMergeableState
2020.07.28 10:58:16.364887 [ 390 ] {1271c3c8-8f46-4b01-85a7-4eee6d79a94b} <Debug> executeQuery: Query pipeline:
2020.07.28 10:58:16.507918 [ 486 ] {1271c3c8-8f46-4b01-85a7-4eee6d79a94b} <Trace> ParallelAggregatingBlockInputStream: Aggregating
2020.07.28 11:10:01.534979 [ 390 ] {1271c3c8-8f46-4b01-85a7-4eee6d79a94b} <Information> TCPHandler: Query was cancelled.

2020.07.28 11:10:01.824251 [ 389 ] {81fa8bd3-295e-427f-9ec4-932bbf1261f0} <Debug> executeQuery: (from [::ffff:127.0.0.1]:49178) KILL QUERY WHERE query_id = '1271c3c8-8f46-4b01-85a7-4eee6d79a94b' ASYNC
2020.07.28 11:10:01.825748 [ 389 ] {81fa8bd3-295e-427f-9ec4-932bbf1261f0} <Debug> executeQuery: (internal) SELECT query_id, user, query FROM system.processes WHERE query_id = '1271c3c8-8f46-4b01-85a7-4eee6d79a94b'
2020.07.29 06:45:13.722543 [ 353 ] {84ae4597-9f93-45c9-9b17-6ace39b19da2} <Debug> executeQuery: (from [::1]:56314) kill query where query_id = '1271c3c8-8f46-4b01-85a7-4eee6d79a94b';
2020.07.29 06:45:13.722669 [ 353 ] {84ae4597-9f93-45c9-9b17-6ace39b19da2} <Debug> executeQuery: (internal) SELECT query_id, user, query FROM system.processes WHERE query_id = '1271c3c8-8f46-4b01-85a7-4eee6d79a94b'


```

**Comment by toby080508050805** [comment]
I  got the root cause. It is because the linux soft limit limited the clickhouse thread. After increasing a number of a limit, it is find now.
