### ISSUE TITLE
Removing and re-adding the same user to users.xml block it from successfully authenticating.

### ISSUE THREAD

**Issue by traceon** [ClickHouse/ClickHouse#12500]
Affected version: `master` branch.

Discovered during testing of #11234

Steps to reproduce:

1. Stop the clickhouse server.
2. Add some user to `users.xml`:
```
<abc>
    <password>xyz</password>
</abc>
```
3. Start clickhouse server.
4. Execute a query on behalf of this user (expected and actual behavior: success).
5. Without stopping clickhouse remove the user entry added at step 2 from `users.xml` (expected and actual behavior: clickhouse config reloader detects the change and reloads `users.xml`).
6. Execute a query on behalf of this user (expected and actual behavior: auth failure with `DB::Exception: abc: Authentication failed: password is incorrect or there is no user with such name.`).
7. Without stopping clickhouse re-add the **same** user as in step 2 (expected and actual behavior: clickhouse config reloader detects the change and reloads `users.xml`).
8. Execute a query on behalf of this user (expected behavior: success; actual behavior: **auth failure** as during step 6).

**Comment by alexey-milovidov** [comment]
I checked and found that the issue not longer exists.
