### ISSUE TITLE
Update/Delete Issue found

### ISSUE THREAD

**Issue by Crazylearner30** [ClickHouse/ClickHouse#12511]
Hi,

There is a strange issue found with the below statement.

alter table test_table update column1=10 where column2 =0
alter table test_table1 delete where column1=2

above two alter statements works perfectly fine without any errors, but it doesn't reflect in the table(basically values are not changing at all).
in system.mutations table "is_done" is not changed to 1 
ClickHouse server version 20.1.11 revision 54431.

Can somebody please help me to rectify this.

Thanks in advance.

**Comment by CurtizJ** [comment]
Is the field `latest_fail_reason` empty in `system.mutations` table? And are there any exceptions in log?

Also it will be helpful if you will share table create statement.

**Comment by Crazylearner30** [comment]
latest_fail_reason is empty in system.mutations table.
No exceptions found in the log.

here is the create table statement of the table

 CREATE TABLE database.test_table (
  `column1` UInt32,
  `column2` UInt32,
  `column3` String,
  `column4` String,
  `date` Date
) ENGINE = MergeTree
ORDER BY
  column3 SETTINGS index_granularity = 8192

**Comment by alexey-milovidov** [comment]
The mutation can require some free space to run.
Check the server logs related to this mutation.
