### ISSUE TITLE
GLOBAL LEFT OUTER JOIN return more rows than GLOBAL LEFT JOIN

### ISSUE THREAD

**Issue by hydra-yl** [ClickHouse/ClickHouse#12516]
**Describe the unexpected behaviour**
GLOBAL LEFT OUTER JOIN return more rows than GLOBAL LEFT JOIN.

**How to reproduce**
Both left and right table were created using StripeLog table engine. Run:

1. Test1: join left and right table using `GLOBAL LEFT OUTER JOIN`
2. Test2: join left and right table using `GLOBAL LEFT JOIN`
3. Compare the difference between `SELECT count(1) FROM test1` and `SELECT count(1) FROM test2`

* Which ClickHouse server version to use
19.13.3.26

* Which interface to use, if matters
clickhouse-client

* Non-default settings, if any
NONE

* JOIN statement
```
CREATE TABLE IF NOT EXISTS xx_table
ENGINE StripeLog()
AS

SELECT DISTINCT column_1, column_2, column_3, ..., column_30, column_right_table_only
FROM (
SELECT DISTINCT column_1, column_2, column_3, ..., column_30 FROM left_table
) GLOBAL LEFT JOIN (
SELECT DISTINCT column_1, column_2, column_3, ..., column_right_table_only FROM right_table
) USING (column_1, column_2, column_3);
```

**Expected behavior**
Test1 and test2 should have same number of rows. Since [the documentation of JOIN](https://clickhouse.tech/docs/en/sql-reference/statements/select/join/) says: Keyword OUTER can be safely omitted

**Comment by 4ertus2** [comment]
Most probable you have not deterministic result of the query. It's not correlated to OUTER keyword for sure. This word is just ignored at parser level.

**Comment by hydra-yl** [comment]
> Most probable you have not deterministic result of the query. It's not correlated to `OUTER` keyword for sure. This word is just ignored at parser stage of query analisys.
> In future version it could force `ALL JOIN` to override `set join_default_strictness=ANY`. But for now parser reads and ignores `OUTER` keyword.

The query is deterministic:

1. There is no where or group by clause in the query.
2. The purpose of join is to add dimension properties.
3. Both tables hold static data.

**Comment by alexey-milovidov** [comment]
@hydra-yl 
`LEFT JOIN`
and
`LEFT OUTER JOIN`
are equivalent.

The described issue does not look possible.

Please reopen if it reproduces.
