### ISSUE TITLE
Default database is not used for dictionaries

### ISSUE THREAD

**Issue by Deninc** [ClickHouse/ClickHouse#12512]
**Describe the bug**
Default database is not used when selecting dictionaries. It works normally with tables.

**How to reproduce**
* ClickHouse server version 20.5.2 revision 54435.

```sql
CREATE DICTIONARY organizations (...)
```

```bash
$ use default

USE default

Ok.

0 rows in set. Elapsed: 0.001 sec.

$ show tables

SHOW TABLES

┌─name──────────┐
│ organizations │
└───────────────┘
```

```bash
$ SELECT dictGet('organizations', 'name', toUInt64(2))

Received exception from server (version 20.5.2):
Code: 36. DB::Exception: Received from localhost:9000. DB::Exception: external dictionary 'organizations' not found.
```

```bash
$ SELECT dictGet('default.organizations', 'name', toUInt64(2))

┌─dictGet('default.organizations', 'name', toUInt64(2))─┐
│ CA Test                                               │
└───────────────────────────────────────────────────────┘
```

**Comment by den-crane** [comment]
Database qualifier is mandatory for  dictGet with dictionaries created by `CREATE DICTIONARY`. 
It needed to distinguish old xml and new dml dictionaries.

**Comment by Deninc** [comment]
@den-crane thanks for the information, but maybe this should be noted in the documentation? It took me hours to figure this out. So it might help others.

Either add [here](https://clickhouse.tech/docs/en/sql-reference/statements/create/dictionary/) or [here](https://clickhouse.tech/docs/en/sql-reference/dictionaries/external-dictionaries/external-dicts-dict/).
