### ISSUE TITLE
Can't grant using dictGet - syntax error

### ISSUE THREAD

**Issue by nuget1991** [ClickHouse/ClickHouse#12524]
I am trying to perform grant privileges for dictGet for user but can't perform it at all.

GRANT dictGet ON dbname.dictname TO username

Syntax error: failed at position 15:
Expected one of: EXCEPT, Comma, At, TO, token

I've tried to perfomr different combinations of this command but still no luck. Can somebody suggest me sollution?

**Comment by cronzevid** [comment]
Same here, using the exact syntax from [documentation](https://clickhouse.tech/docs/en/sql-reference/statements/grant/#grant-dictget). 
Even though it is possible to use `GRANT ALL ON db.* to username`, this works only during runtime. If you have `access_management` enabled, this query would leave clickhouse-server instance without specified user completely. Fixing this, would require editing `/var/lib/clickhouse/access/*sql` by hand.

**Comment by nuget1991** [comment]
Connected to ClickHouse server version 20.3.8 revision 54433. Получил ответ что гранты только в релизе с 20.4. После того как обновимся вернусь с результатом.

**Comment by den-crane** [comment]
probably it supported only in 20.4+

```
20.6.1.4066 

GRANT dictGet ON default.item_dict TO test0
Ok.
```

**Comment by nuget1991** [comment]
Thanks, we updated to latest version of clickhouse and solved the issue.
