### ISSUE TITLE
Setting Primary Key specifically in Create statement

### ISSUE THREAD

**Issue by Crazylearner30** [ClickHouse/ClickHouse#12533]
How to explicitly set primary key in mergetree table?

**Comment by den-crane** [comment]
https://clickhouse.tech/docs/en/engines/table-engines/mergetree-family/mergetree/#choosing-a-primary-key-that-differs-from-the-sorting-key

https://clickhouse.tech/docs/en/engines/table-engines/mergetree-family/mergetree/#table_engine-mergetree-creating-a-table
```

CREATE TABLE PK
(
    `A` Int64,
    `B` Int64
)
ENGINE = MergeTree
PRIMARY KEY A
ORDER BY (A, B)
```
