### ISSUE TITLE
clickhouse服务宕机

### ISSUE THREAD

**Issue by spihiker** [ClickHouse/ClickHouse#12539]
操作系统：Centos7.6 x86_64
CH Version:20.3.8   20.3.12

描述：
     线上环境使用时，服务会突然宕机。出现过多次。开始使用的20.3.8的版本，升级到20.3.12还是一样。

排查线索：
     根据错误日志的记录，排查query_id，发现执行的sql。有包括关联mysql表的语法。如SELECT c1,c2....FROM t1 LEFT JOIN   mysql('host,','username','dbname'.....) t2 ON ....
     截取2段不同时间的错误日志：
2020.07.14 16:11:12.277882 [ 40905 ] {} <Fatal> BaseDaemon: ########################################
2020.07.14 16:11:12.277987 [ 40905 ] {} <Fatal> BaseDaemon: (version 20.3.8.53 (official build)) (from thread 20811) (query_id: 6a90eb55-e6bb-4454-a1a8-b93e3bcba064) Received signal Segmentation fault (11).
2020.07.14 16:11:12.278027 [ 40905 ] {} <Fatal> BaseDaemon: Address: 0xffffffff5b9c5d00 Access: read. Address not mapped to object.
2020.07.14 16:11:12.278065 [ 40905 ] {} <Fatal> BaseDaemon: Stack trace: 0x90308af 0xd350729 0xd566d59 0xd569cdf 0xd463185 0xd149ca6 0xd14ab89 0xd34fcd6 0xd80084d 0xd6692ec 0xd187c49 0xd18ab2e 0xd14c0f3 0xd34cdb0 0xd34d09a 0xd4ebf6a 0xd4ebfd6 0xd323df5 0xce5701f 0xd2f72ce 0xd2f9277 0xce5593a 0xce55899 0xce55899 0xce55899 0xce55899 0xce55899 0xce55899 0xce55899
2020.07.14 16:11:12.278162 [ 40905 ] {} <Fatal> BaseDaemon: 3. DB::Block::Block(DB::Block const&) @ 0x90308af in /usr/bin/clickhouse
2020.07.14 16:11:12.278216 [ 40905 ] {} <Fatal> BaseDaemon: 4. DB::InterpreterSelectWithUnionQuery::getSampleBlock(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&) @ 0xd350729 in /usr/bin/clickhouse
2020.07.14 16:11:12.278243 [ 40905 ] {} <Fatal> BaseDaemon: 5. ? @ 0xd566d59 in /usr/bin/clickhouse
2020.07.14 16:11:12.278270 [ 40905 ] {} <Fatal> BaseDaemon: 6. DB::getDatabaseAndTablesWithColumns(std::__1::vector<DB::ASTTableExpression const*, std::__1::allocator<DB::ASTTableExpression const*> > const&, DB::Context const&) @ 0xd569cdf in /usr/bin/clickhouse
2020.07.14 16:11:12.278300 [ 40905 ] {} <Fatal> BaseDaemon: 7. DB::JoinedTables::resolveTables() @ 0xd463185 in /usr/bin/clickhouse
2020.07.14 16:11:12.278376 [ 40905 ] {} <Fatal> BaseDaemon: 8. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, std::__1::shared_ptr<DB::IBlockInputStream> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0xd149ca6 in /usr/bin/clickhouse
2020.07.14 16:11:12.278422 [ 40905 ] {} <Fatal> BaseDaemon: 9. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0xd14ab89 in /usr/bin/clickhouse
2020.07.14 16:11:12.278454 [ 40905 ] {} <Fatal> BaseDaemon: 10. DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0xd34fcd6 in /usr/bin/clickhouse
2020.07.14 16:11:12.278502 [ 40905 ] {} <Fatal> BaseDaemon: 11. DB::StorageView::read(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, DB::SelectQueryInfo const&, DB::Context const&, DB::QueryProcessingStage::Enum, unsigned long, unsigned int) @ 0xd80084d in /usr/bin/clickhouse
2020.07.14 16:11:12.278537 [ 40905 ] {} <Fatal> BaseDaemon: 12. DB::IStorage::readStreams(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, DB::SelectQueryInfo const&, DB::Context const&, DB::QueryProcessingStage::Enum, unsigned long, unsigned int) @ 0xd6692ec in /usr/bin/clickhouse
2020.07.14 16:11:12.278587 [ 40905 ] {} <Fatal> BaseDaemon: 13. void DB::InterpreterSelectQuery::executeFetchColumns<DB::InterpreterSelectQuery::Pipeline>(DB::QueryProcessingStage::Enum, DB::InterpreterSelectQuery::Pipeline&, std::__1::shared_ptr<DB::PrewhereInfo> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, DB::QueryPipeline&) @ 0xd187c49 in /usr/bin/clickhouse
2020.07.14 16:11:12.278613 [ 40905 ] {} <Fatal> BaseDaemon: 14. void DB::InterpreterSelectQuery::executeImpl<DB::InterpreterSelectQuery::Pipeline>(DB::InterpreterSelectQuery::Pipeline&, std::__1::shared_ptr<DB::IBlockInputStream> const&, std::__1::optional<DB::Pipe>, DB::QueryPipeline&) @ 0xd18ab2e in /usr/bin/clickhouse
2020.07.14 16:11:12.278651 [ 40905 ] {} <Fatal> BaseDaemon: 15. DB::InterpreterSelectQuery::executeWithMultipleStreams(DB::QueryPipeline&) @ 0xd14c0f3 in /usr/bin/clickhouse
2020.07.14 16:11:12.278683 [ 40905 ] {} <Fatal> BaseDaemon: 16. DB::InterpreterSelectWithUnionQuery::executeWithMultipleStreams(DB::QueryPipeline&) @ 0xd34cdb0 in /usr/bin/clickhouse
2020.07.14 16:11:12.278705 [ 40905 ] {} <Fatal> BaseDaemon: 17. DB::InterpreterSelectWithUnionQuery::execute() @ 0xd34d09a in /usr/bin/clickhouse
2020.07.14 16:11:12.278749 [ 40905 ] {} <Fatal> BaseDaemon: 18. ? @ 0xd4ebf6a in /usr/bin/clickhouse
2020.07.14 16:11:12.278771 [ 40905 ] {} <Fatal> BaseDaemon: 19. ? @ 0xd4ebfd6 in /usr/bin/clickhouse
2020.07.14 16:11:12.278800 [ 40905 ] {} <Fatal> BaseDaemon: 20. DB::LazyBlockInputStream::readImpl() @ 0xd323df5 in /usr/bin/clickhouse
2020.07.14 16:11:12.278845 [ 40905 ] {} <Fatal> BaseDaemon: 21. DB::IBlockInputStream::read() @ 0xce5701f in /usr/bin/clickhouse
2020.07.14 16:11:12.278872 [ 40905 ] {} <Fatal> BaseDaemon: 22. DB::CreatingSetsBlockInputStream::createOne(DB::SubqueryForSet&) @ 0xd2f72ce in /usr/bin/clickhouse
2020.07.14 16:11:12.278895 [ 40905 ] {} <Fatal> BaseDaemon: 23. DB::CreatingSetsBlockInputStream::readPrefixImpl() @ 0xd2f9277 in /usr/bin/clickhouse
2020.07.14 16:11:12.278917 [ 40905 ] {} <Fatal> BaseDaemon: 24. DB::IBlockInputStream::readPrefix() @ 0xce5593a in /usr/bin/clickhouse
2020.07.14 16:11:12.278938 [ 40905 ] {} <Fatal> BaseDaemon: 25. DB::IBlockInputStream::readPrefix() @ 0xce55899 in /usr/bin/clickhouse
2020.07.14 16:11:12.278957 [ 40905 ] {} <Fatal> BaseDaemon: 26. DB::IBlockInputStream::readPrefix() @ 0xce55899 in /usr/bin/clickhouse
2020.07.14 16:11:12.278974 [ 40905 ] {} <Fatal> BaseDaemon: 27. DB::IBlockInputStream::readPrefix() @ 0xce55899 in /usr/bin/clickhouse
2020.07.14 16:11:12.278992 [ 40905 ] {} <Fatal> BaseDaemon: 28. DB::IBlockInputStream::readPrefix() @ 0xce55899 in /usr/bin/clickhouse
2020.07.14 16:11:12.279009 [ 40905 ] {} <Fatal> BaseDaemon: 29. DB::IBlockInputStream::readPrefix() @ 0xce55899 in /usr/bin/clickhouse
2020.07.14 16:11:12.279024 [ 40905 ] {} <Fatal> BaseDaemon: 30. DB::IBlockInputStream::readPrefix() @ 0xce55899 in /usr/bin/clickhouse
2020.07.14 16:11:12.279039 [ 40905 ] {} <Fatal> BaseDaemon: 31. DB::IBlockInputStream::readPrefix() @ 0xce55899 in /usr/bin/clickhouse

2020.07.16 10:44:32.795196 [ 41367 ] {} <Fatal> BaseDaemon: ########################################
2020.07.16 10:44:32.795310 [ 41367 ] {} <Fatal> BaseDaemon: (version 20.3.12.112 (official build)) (from thread 15677) (query_id: bf02bad0-cb38-4143-9ca5-2acc9a1b9a0a) Received signal Segmentation fault (11).
2020.07.16 10:44:32.795355 [ 41367 ] {} <Fatal> BaseDaemon: Address: 0xffffffff02df9000 Access: read. Address not mapped to object.
2020.07.16 10:44:32.795397 [ 41367 ] {} <Fatal> BaseDaemon: Stack trace: 0x8f5d071 0x903dc2b 0xd32a606 0xd53f549 0xd5424cf 0xd43cf45 0xd1258f6 0xd1267d9 0xd329a86 0xd32a56a 0xd53f549 0xd5424cf 0xd43cf45 0xd1258f6 0xd1267d9 0xd329a86 0xd32a56a 0xd53f549 0xd5424cf 0xd43cf45 0xd1258f6 0xd1267d9 0xd329a86 0xd7d13b5 0xd641b4c 0xd163e3b 0xd166d7e 0xd127d43 0xd326b40
2020.07.16 10:44:32.795477 [ 41367 ] {} <Fatal> BaseDaemon: 3. ? @ 0x8f5d071 in /usr/bin/clickhouse
2020.07.16 10:44:32.795522 [ 41367 ] {} <Fatal> BaseDaemon: 4. DB::Block::Block(DB::Block const&) @ 0x903dc2b in /usr/bin/clickhouse
2020.07.16 10:44:32.795555 [ 41367 ] {} <Fatal> BaseDaemon: 5. DB::InterpreterSelectWithUnionQuery::getSampleBlock(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&) @ 0xd32a606 in /usr/bin/clickhouse
2020.07.16 10:44:32.795575 [ 41367 ] {} <Fatal> BaseDaemon: 6. ? @ 0xd53f549 in /usr/bin/clickhouse
2020.07.16 10:44:32.795599 [ 41367 ] {} <Fatal> BaseDaemon: 7. DB::getDatabaseAndTablesWithColumns(std::__1::vector<DB::ASTTableExpression const*, std::__1::allocator<DB::ASTTableExpression const*> > const&, DB::Context const&) @ 0xd5424cf in /usr/bin/clickhouse
2020.07.16 10:44:32.795621 [ 41367 ] {} <Fatal> BaseDaemon: 8. DB::JoinedTables::resolveTables() @ 0xd43cf45 in /usr/bin/clickhouse
2020.07.16 10:44:32.795676 [ 41367 ] {} <Fatal> BaseDaemon: 9. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, std::__1::shared_ptr<DB::IBlockInputStream> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0xd1258f6 in /usr/bin/clickhouse
2020.07.16 10:44:32.795724 [ 41367 ] {} <Fatal> BaseDaemon: 10. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0xd1267d9 in /usr/bin/clickhouse
2020.07.16 10:44:32.795751 [ 41367 ] {} <Fatal> BaseDaemon: 11. DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0xd329a86 in /usr/bin/clickhouse
2020.07.16 10:44:32.795773 [ 41367 ] {} <Fatal> BaseDaemon: 12. DB::InterpreterSelectWithUnionQuery::getSampleBlock(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&) @ 0xd32a56a in /usr/bin/clickhouse
2020.07.16 10:44:32.795798 [ 41367 ] {} <Fatal> BaseDaemon: 13. ? @ 0xd53f549 in /usr/bin/clickhouse
2020.07.16 10:44:32.795826 [ 41367 ] {} <Fatal> BaseDaemon: 14. DB::getDatabaseAndTablesWithColumns(std::__1::vector<DB::ASTTableExpression const*, std::__1::allocator<DB::ASTTableExpression const*> > const&, DB::Context const&) @ 0xd5424cf in /usr/bin/clickhouse
2020.07.16 10:44:32.795846 [ 41367 ] {} <Fatal> BaseDaemon: 15. DB::JoinedTables::resolveTables() @ 0xd43cf45 in /usr/bin/clickhouse
2020.07.16 10:44:32.795873 [ 41367 ] {} <Fatal> BaseDaemon: 16. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, std::__1::shared_ptr<DB::IBlockInputStream> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0xd1258f6 in /usr/bin/clickhouse
2020.07.16 10:44:32.795897 [ 41367 ] {} <Fatal> BaseDaemon: 17. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0xd1267d9 in /usr/bin/clickhouse
2020.07.16 10:44:32.795927 [ 41367 ] {} <Fatal> BaseDaemon: 18. DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0xd329a86 in /usr/bin/clickhouse

盼回复。谢谢！

**Comment by jackpgao** [comment]
MySQL引擎在最近的版本里偶发报错，跟使用的MySQL版本也有一定的关系，我猜你用的是阿里的RDS？

**Comment by spihiker** [comment]
是官方mysql. mysql5.6的版本。这个比较严重，直接导致CH的服务闪退，导致服务不可用。我认为正常的处理逻辑，应该是查询异常，最多把这个查询kill掉。

**Comment by alexey-milovidov** [comment]
You should upgrade to the latest 20.3 patch release (20.3.13), it contains important bugfixes.

**Comment by alexey-milovidov** [comment]
Duplicate? https://github.com/ClickHouse/ClickHouse/issues/8889

**Comment by spihiker** [comment]
非常感谢！我先升级试试看。

**Comment by spihiker** [comment]
你好。升级后，观察了几天。没有发现闪退的情况。

**Comment by spihiker** [comment]
已经升级到了20.3.13.127.今天再次出现由于select语句，出现CH服务闪退，服务挂掉的情况。请关注!
2020.07.30 10:56:24.089512 [ 4322 ] {} <Fatal> BaseDaemon: ########################################
2020.07.30 10:56:24.089599 [ 4323 ] {} <Fatal> BaseDaemon: ########################################
2020.07.30 10:56:24.089654 [ 4322 ] {} <Fatal> BaseDaemon: (version 20.3.13.127 (official build)) (from t
hread 68052) (query_id: d4390dc2-4425-4050-bc50-df667b43a669) Received signal Segmentation fault (11).
2020.07.30 10:56:24.089692 [ 4322 ] {} <Fatal> BaseDaemon: Address: 0x2c0ae9fa1e27 Access: read. Address 
not mapped to object.
2020.07.30 10:56:24.089663 [ 4323 ] {} <Fatal> BaseDaemon: (version 20.3.13.127 (official build)) (from t
hread 68000) (query_id: d4390dc2-4425-4050-bc50-df667b43a669) Received signal Segmentation fault (11).
2020.07.30 10:56:24.089725 [ 4322 ] {} <Fatal> BaseDaemon: Stack trace: 0x8f99f2d 0x907ad4b 0xd389f76 0xd
5a03e9 0xd5a336f 0xd49c8c5 0xd181866 0xd182749 0xd3893f6 0xd833b35 0xd6a398c 0xd1bfe8b 0xd1c2dce 0xd183cb
3 0xd3864b0 0xd38679a 0xd52590a 0xd525976 0xd35d595 0xce8c9cf 0xd33048e 0xd332437 0xce8b2ea 0xce8b249 0xc
e8b249 0xce8b249 0xce8b249 0xce8b249 0xce8b249
2020.07.30 10:56:24.089731 [ 4323 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Address n
ot mapped to object.
2020.07.30 10:56:24.089801 [ 4322 ] {} <Fatal> BaseDaemon: 3. ? @ 0x8f99f2d in /usr/bin/clickhouse
2020.07.30 10:56:24.089804 [ 4323 ] {} <Fatal> BaseDaemon: Stack trace: 0x8f99fa8 0x907ad4b 0xd389f76 0xd
5a03e9 0xd5a336f 0xd49c8c5 0xd181866 0xd182749 0xd3893f6 0xd833b35 0xd6a398c 0xd1bfe8b 0xd1c2dce 0xd183cb
3 0xd3864b0 0xd38679a 0xd52590a 0xd525976 0xd35d595 0xce8c9cf 0xd33048e 0xd332437 0xce8b2ea 0xce8b249 0xc
e8b249 0xce8b249 0xce8b249 0xce8b249 0xce8b249
2020.07.30 10:56:24.089854 [ 4322 ] {} <Fatal> BaseDaemon: 4. DB::Block::Block(DB::Block const&) @ 0x907a
d4b in /usr/bin/clickhouse

**Comment by 4ertus2** [comment]
It looks like crash appears in `mysql()` table function columns resolution in some cases. We need mysql table schema to reproduce. Does `select * from mysql('host,','username','dbname'.....)` works?
