### ISSUE TITLE
enable_mixed_granularity_parts + delete mutation lead to broken parts

### ISSUE THREAD

**Issue by alesapin** [ClickHouse/ClickHouse#12536]
**Describe the bug**
Imagine that we have a table with old non-adaptive parts (.mrk extension) and enabled mixed granularity in the server's config in section (`<enable_mixed_granularity_parts>1<enable_mixed_granularity_parts>`) or using `ALTER SETTING` query. 
In this case, when we execute `ALTER DELETE` mutation (actually use `MergedBlockOutputStream`) we will take information about index granularity from our source part https://github.com/ClickHouse/ClickHouse/blob/master/src/Storages/MergeTree/MergeTreeDataMergerMutator.cpp#L1066-L1067, and mark file extension will be the same as in source part https://github.com/ClickHouse/ClickHouse/blob/master/src/Storages/MergeTree/MergeTreeDataPartWide.cpp#L65 `.mrk` for the old part. But on the other hand, in the stream settings, we will write index granularity using information from storage https://github.com/ClickHouse/ClickHouse/blob/master/src/Storages/MergeTree/MergedBlockOutputStream.cpp#L49 which will be set to `true`. So we will get part with `.mrk` extension and adaptive granularity which server will not be able to read and mark as broken.

Broken since #8290.

**Comment by alexey-milovidov** [comment]
Ok.

Maybe as a workaround we can autodetect mark format from the file size?

**Comment by alesapin** [comment]
> Maybe as a workaround we can autodetect mark format from the file size?

It's possible, but I think it can lead to confusing bugs, especially when the marks file is broken. Also in the code, we rely on invariant that if the extension is `.mrk` then the part has fixed marks if `.mrk2` then it has adaptive marks if `.mrk3` then it's compact part marks.

**Comment by alesapin** [comment]
however, I'll try

**Comment by alesapin** [comment]
Maybe we can do renames of files ones at server startup.

**Comment by alesapin** [comment]
Related fix https://github.com/ClickHouse/ClickHouse/pull/12545
