### ISSUE TITLE
Add option to disable redirects in S3 requests

### ISSUE THREAD

**Issue by ianton-ru** [ClickHouse/ClickHouse#12531]
*There must be an option to disable redirects, otherwise malicious S3 server (by user-provided URL) can perform SSRF attacks.* (c) Alexey Milovidov (https://github.com/ClickHouse/ClickHouse/pull/12464)

Check option in *src/IO/S3/PocoHTTPClient.cpp* in method **PocoHTTPClient::MakeRequestInternal** to disable redirects (by set **MAX_REDIRECT_ATTEMPTS** to zero, for example)

**Comment by bharatnc** [comment]
Where would this option go i.e would this be user configurable? If so, would it go under the storage config xml file - with an option like `<s3_disable_redirects>true</s3_disable_redirects>` ?

Thinking about it, I'm not entirely sure if this is apt for it to be a setting under `storage_configuration` section.
