### ISSUE TITLE
How to find the previous row after the data is sorted

### ISSUE THREAD

**Issue by lzy305** [ClickHouse/ClickHouse#12547]
Is there a similar oracle lag, lead function？

select department_id, employ_id, sal_day,
       neighbor(sal_day, 1) as next_day
 from 
(select 'a' as department_id, 1 as employ_id, toDate('2019-12-01') as sal_day
UNION ALL
select 'b' as department_id, 2 as employ_id, toDate('2018-12-01') as sal_day
UNION ALL
select 'a' as department_id, 1 as employ_id, toDate('2019-06-01') as sal_day
UNION ALL
select 'a' as department_id, 3 as employ_id, toDate('2020-04-01') as sal_day
UNION ALL
select 'b' as department_id, 2 as employ_id, toDate('2017-12-01') as sal_day
UNION ALL
select 'b' as department_id, 4 as employ_id, toDate('2015-06-01') as sal_day
UNION ALL
select 'a' as department_id, 2 as employ_id, toDate('2026-04-01') as sal_day
)
order by department_id, employ_id, sal_day asc。

This method is wrong

**Comment by lzy305** [comment]
@den-crane  thanks. another case .
select department_id, employ_id,product, sal_day,
       neighbor(sal_day, 1) as next_day
 from 
(select 'a' as department_id, 1 as employ_id, 'milk1' as product, toDate('2019-12-01') as sal_day
UNION ALL
select 'b' as department_id, 2 as employ_id, 'milk2' as product, toDate('2018-12-01') as sal_day
UNION ALL
select 'a' as department_id, 1 as employ_id,'milk3' as product, toDate('2019-06-01') as sal_day
UNION ALL
select 'a' as department_id, 3 as employ_id, 'milk3' as product, toDate('2020-04-01') as sal_day
UNION ALL
select 'b' as department_id, 2 as employ_id, 'milk3' as product, toDate('2017-12-01') as sal_day
UNION ALL
select 'b' as department_id, 4 as employ_id, 'milk4' as product,toDate('2015-06-01') as sal_day
UNION ALL
select 'a' as department_id, 2 as employ_id, 'milk4' as product,toDate('2026-04-01') as sal_day
)
order by department_id, employ_id, sal_day asc.

**Comment by den-crane** [comment]
```
select department_id, employ_id, y.1.1 sal_day, y.1.2 next_day, y.2.1 prod, y.2.2 nex_prod from (
select department_id, employ_id, 
    arrayJoin(arrayMap(i-> (x[i],x[i+1]),arrayEnumerate(arraySort(j->j.1, groupArray((sal_day, product))) as x))) as y
from
(select 'a' as department_id, 1 as employ_id, 'milk1' as product, toDate('2019-12-01') as sal_day
UNION ALL
select 'b' as department_id, 2 as employ_id, 'milk2' as product, toDate('2018-12-01') as sal_day
UNION ALL
select 'a' as department_id, 1 as employ_id,'milk3' as product, toDate('2019-06-01') as sal_day
UNION ALL
select 'a' as department_id, 3 as employ_id, 'milk3' as product, toDate('2020-04-01') as sal_day
UNION ALL
select 'b' as department_id, 2 as employ_id, 'milk3' as product, toDate('2017-12-01') as sal_day
UNION ALL
select 'b' as department_id, 4 as employ_id, 'milk4' as product,toDate('2015-06-01') as sal_day
UNION ALL
select 'a' as department_id, 2 as employ_id, 'milk4' as product,toDate('2026-04-01') as sal_day
)
group by department_id, employ_id)


┌─department_id─┬─employ_id─┬────sal_day─┬─next_day─┬───────prod─┬─nex_prod─┐
│ b             │         2 │ 2017-12-01 │ milk3    │ 2018-12-01 │ milk2    │
│ b             │         2 │ 2018-12-01 │ milk2    │ 0000-00-00 │          │
│ a             │         2 │ 2026-04-01 │ milk4    │ 0000-00-00 │          │
│ a             │         3 │ 2020-04-01 │ milk3    │ 0000-00-00 │          │
│ a             │         1 │ 2019-06-01 │ milk3    │ 2019-12-01 │ milk1    │
│ a             │         1 │ 2019-12-01 │ milk1    │ 0000-00-00 │          │
│ b             │         4 │ 2015-06-01 │ milk4    │ 0000-00-00 │          │
└───────────────┴───────────┴────────────┴──────────┴────────────┴──────────┘
```
