### ISSUE TITLE
how to design the partition key for dimension table

### ISSUE THREAD

**Issue by peaksnail** [ClickHouse/ClickHouse#12558]
hi team,
   I have dimension table named goods
goods table scheme
```
create table goods (
storeId String,
goodsId String
name String,
price UInt32,
createDate Date
) engine =  MergeTree() PARTITION BY toYYYYMM(createDate)
order by createDate
```

the partition key is createDate and when I query goods with storeId, It may read all parts to get the data(the createDate may over 1 year)

And I want to set the partition key with storeId, But I have more than 5000 stores.
you have metioned in the [docuemnt](https://clickhouse.tech/docs/en/engines/table-engines/mergetree-family/custom-partitioning-key/)
```
Info

A merge only works for data parts that have the same value for the partitioning expression. This means you shouldn’t make
overly granular partitions (more than about a thousand partitions). Otherwise, the SELECT query performs poorly because of 
an unreasonably large number of files in the file system and open file descriptors.
```

So,It may read all parts when using partition key createDate, and there will be much partitions when using partition key storeId, how to make a choice, has any suggestion? 

Thanks

**Comment by nvartolomei** [comment]
Have you considered using a single partition? `PARTITION BY tuple()` or omit it completely.

**Comment by peaksnail** [comment]
Goods idea, It worth a try
