### ISSUE TITLE
Codecs for data types with multiple streams.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#12551]
See #11397 and #4609.

### Variant 1

Method `IDataType::enumerateStreams` should return a property for each stream about "is specialized codecs applicable".

For example, for Nullable type, specialized codecs are applicable for stream with elements but not applicable to the stream of null mask. For Array type, specialized codecs are applicable for stream with elements but not applicable to the stream of sizes. For Tuple type, specialized codecs are applicable for all streams.

Every codec should have a property about "is this codec specialized".

For example, every non-compressing codec is specialized, e.g. Delta. Also DoubleDelta codec (I strongly dislike it's name) compresses something but it's specialized.

When serializing data types with multiple streams, codecs should be transformed in the following way: specialized codec is dropped; for multiple codecs, every specialized codec is dropped.

### Variant 2

Method `IDataType::enumerateStreams` should be able to transform the codec (or the list of codecs) according to whatever rules appropriate.

### Caveats

There is strange logic when codec takes info about data type (the number of bytes). This logic does not fit the needs.
For example, how it should work when passing `Tuple(UInt32, Array(UInt64))`?

**Comment by alesapin** [comment]
`> When serializing data types with multiple streams, codecs should be transformed in the following way: specialized codec is dropped; for multiple codecs, every specialized codec is dropped.`
Only for streams which shouldn't be serialized with specialized codecs (array sizes, null mask, etc. )?
