### ISSUE TITLE
Support configuration hot reload of merge_tree_settings?

### ISSUE THREAD

**Issue by kekekedeng** [ClickHouse/ClickHouse#12565]
Hi team:
    I found there no hot reload ability of merge_tree_settings like max_parts_in_total, parts_to_delay_insert and so on. Are there any ways to implement hot reload?

**Comment by den-crane** [comment]
you can apply it to the table 
```
alter  table foobar modify setting max_parts_in_total  = 6000;

```

**Comment by kekekedeng** [comment]
@den-crane It works, thanks!
