### ISSUE TITLE
clickhouse-server memory usage not release

### ISSUE THREAD

**Issue by peaksnail** [ClickHouse/ClickHouse#12563]
hi team
the memory usage of clickhouse-server will be more and more and not release
It recover when I restart the clickhouse-server

How to explain it?

thanks
 
![image](https://user-images.githubusercontent.com/1744607/87775184-447de500-c858-11ea-8dfe-82154fd9e9e4.png)

**Comment by den-crane** [comment]
it could be mark cache (5GB by default). Try `system drop mark cache` instead reboot and check memory after it.

**Comment by peaksnail** [comment]
hi
I set `<mark_cache_size>1073741824</mark_cache_size>(1GB)` in config.xml
when I execute  `system drop mark cache`, It release 2GB memory  but I just set 1GB for  mark cache

![image](https://user-images.githubusercontent.com/1744607/90383294-85b12100-e0b2-11ea-810d-31da8a01abb1.png)

And the memory usage is more than the mark cache

![image](https://user-images.githubusercontent.com/1744607/90384448-20f6c600-e0b4-11ea-8c27-fbf6d36d436c.png)

Now I have to restart the service regularly, how to solve it?

thanks!

**Comment by little-circle-circle** [comment]
I have the same problem, I read the code about mark cache, Found this

- mark_cache_size: this config item only control mark file data size, but mark cache has some meta data for lru

- lru meta data: lru meta data size depend on number of mark files, if your mark file is small, lru meta data size will be greater than mark file data size

- system drop mark cache: this command will clear mark file data and lru meta data

so you just need to set mark_cache_size fewer, if you have less memory

finally, hope the new version can support check and control the whole mark cache

**Comment by peaksnail** [comment]
@little-circle-circle  👍 thanks

**Comment by den-crane** [comment]
@peaksnail What CH version do you use? How much memory does your server have?

**Comment by peaksnail** [comment]
@den-crane 
ch version 19.17.6.19
server memory 12G

**Comment by alexey-milovidov** [comment]
In old versions, mark cache can grow above the mark_cache_size.
