### ISSUE TITLE
Clickhouse on GPU ?

### ISSUE THREAD

**Issue by vkingnew** [ClickHouse/ClickHouse#12572]
As so far,clickhouse is running very fast compare with Bigdata software like Elasticsearch or Apache spark.
https://tech.marksblogg.com/benchmarks.html
As this Blogger's Benchmark,some Database running on GPU,it looks more faster. they use GPU to accelerate compute.
I noticed some key word like 'GPU',CUDA(#10232,#11083) IN clickhouse issues,I want to know:
Do you have a plan to develop Clickhouse on GPU to accelerate compute and make clickhouse faster?

**Comment by 4ertus2** [comment]
Hi,

In short, we are interested in combined CPU+GPU solution.

For now it's a research task. #10232 is an attempt to use OpenCL and #11083 is attempt to use CUDA.
Theoretically the main trouble with GPU is to move data to its memory and back. In practive there're some other issues to solve.

1. CUDA needs its own compiler to build sources that is usually to old for bleeding edge C++ development.
2. We need special GPU accelerated servers in our CI for build and tests.
3. Chicken or the egg dilemma: no one would use GPU version for several minor improvements. No one would make more features while no one use GPU version.

For now it's possible to use our code base for DBMS + GPU reserch. I.e. if some strudent want to implement OpenCL function in ClickHouse he or she could make it using #10232 as a sample. We also has a discussion with CUDA experts about CUDA support.

**Comment by qoega** [comment]
If you have further questions, fell free to reopen this issue.
