### ISSUE TITLE
Questions about Clickhouse Version number

### ISSUE THREAD

**Issue by vkingnew** [ClickHouse/ClickHouse#12573]
After read the clickhouse change log,I Find as following:
1. 1.1.54245, 2017-07-04   ----  1.1.54394, 2018-07-12
  This is a stage 1.1 version,the version number named rule maybe:Major.Minor.patch

2.18.1.0, 2018-07-23  --- 19.17.6.36, 2019-12-27
the version number rule changd as :Year.Major.Minor.patch
>Changed the numbering scheme for release versions. Now the first part contains the year of release (A.D., Moscow timezone, minus 2000), the second part contains the number for major changes (increases for most releases), and the third part is the patch version. Releases are still backward compatible, unless otherwise stated in the changelog.

in this period:the second version number look increase random,but end with year's end date. the new feaure appears in random version. And hard to distinguish the stable and testing version.

3.v20.1.2.4, 2020-01-22 -- now
the version number maybe： v+Year.Month.Minor.patch
vYear.Month.1.x  always testing version，the v.Year.month.2.x always to introduce new feature

The period is devide by me.Could You help to introduce the history of Clickhouse Relase Number and why change the named rule. Also can introduce the release  interval  in every period.  Wish  the explain from Official,above just guess.

**Comment by 4ertus2** [comment]
Hi,

I.e. we have recent stable version 'v20.5.2.7-stable'. You may read it as as 'the 5th version in 20 year, patchset 2'. '7' is some internal number. Do not look at it. `stable` here means we have looked at it for some time and it's expected to be stable enough.

The Major in `Year.Major.Minor.SomeNumber` means `always to introduce new feature` in your terms. We make a branch for it from our main development stream and try to make it stable. So every `Year.Major` is an attampt to make a stable version. Every `Minor` means patchset that fixes some known bugs in `Year.Major`. The difference between `testing` and `stable` is just a decision to mark it stable. All testing version are shipped to become stable.

For now we make patchesets to 3 newest versions and 2 LTS versions. LTS versions are some special `stable` versions that have longer support. Anfortunatelly we cannot guaranty that they would have all fixes in patchesets cuase code base changes too fast and we cannot backport some fixes to old versions.

You may look at all releases here https://github.com/ClickHouse/ClickHouse/releases
