### ISSUE TITLE
Short circuit function evaluation

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#12587]
**Use case**

Don't evaluate all arguments for some functions.
The list of functions:

- if
- multiIf
- and
- or

**Describe the solution you'd like**

Add a method `isShortCircuit` for `IFunction`. If it returns 1, the function arguments (except first argument?) should be evaluated lazily.
Arguments will not be evaluated (prepared) before function call (unless they are also used somewhere else).
Instead, function will be evaluated with special method `executeShortCurcuit` that will take Block and array of ExpressionActionsPtr representing expressions to calculate arguments (so, arguments are passed lazily).

With intended implementation, the function will evaluate expressions on filtered block by itself.
Temporary results of this evaluation cannot be reused.

If short-curcuit evaluation is possible, it is not neccessarily to be enabled. It should be enabled if any of expressions for arguments may throw. Also it's better to be enabled if any of expressions of arguments are computationally heavy. But it should not be enabled for simple expressions.

**Bonus**

Functions like `toTypeName` can avoid evaluation of its arguments at all.

Thoughts?

**Comment by KochetovNicolai** [comment]
Another approach is to implement it via new type column + expression analyzer.

We may add new type of column: `ColumnProjection(inner_column, mask)`, where `inner_column` may be column of any type, and `mask` is a boolean mask. `ColumnProjection.size() == mask.size()` and `inner_column.size() == sum(mask)`.

Also we may add function `projection(x, y)  -> ColumnProjection(x.filter(y), y)`.

Then, if short circuit is on, we may rewrite expressions with proper projection support. E.g. `if(x > 0, a + b, a + c)` will be rewritten into `if(x > 0, projection(a, x > 0) + projection(b, x > 0), projection(a, not(x > 0)) + projection(c, not(x > 0))`.
Functions which support short circuit should implement special logic for `ColumnProjection`. For other functions, if they are projected to the same expression, we automatically execute them on inner columns, so `projection(a, x > 0) + projection(b, x > 0) := projection(a + b, x > 0)`. It may be done inside `ExpressionActions` (which I like more) or as default implementation for function.

**Comment by 4ertus2** [comment]
@KochetovNicolai The idea of masked execution is cool. But I cannot understand why we need a new column here. We colud use ColumnFunction.

Espression `if(x > 0, a + b, a + c)`

Normal case:
Block before `if()`: `a, b, add(a, b), add(a, c)`

Short circuit case:
Block before `if()`: `a, b, func('add', a, b), func('add', a, c)`, where `func` mean ColumnFunction.

Here we just do not instantiate functions with expressions but make them ColumnFunction there. Then we add masked execution for ColumnFunction that do not change column sizes but touch only needed values.
So, we make mask in from `if()` and then call `maskedExecute(func_add, a, b, res, mask)` and `maskedExecute(func_add, a, c, res, inversed_mask)` for branches. Here `res` column is the same for both `maskedExecute`.

**Comment by KochetovNicolai** [comment]
@4ertus2 Approach with `ColumnFunction` is also good.
I cannot say which one is better by now. I think projections are more explicit. And if you create `ColumnFunction`, you also create separate subexpression for it. It may make some possible, imaginary expression-level optimisations more difficult (or not).

Also, in approach with projections it is not necessary to create column too. We may replace `projection` function to specific action and store information about current projections inside `ExpressionActions` only (it will require more changes in ExpressionActions thought). Anyway, I don't see why new column type is a problem.

**Comment by KochetovNicolai** [comment]
The approach with `ColumnFunction` is probably the faster to implement.

**Comment by azat** [comment]
Looks promising! Any ETA for this?

**Comment by alexey-milovidov** [comment]
No ETA.

**Comment by alexey-milovidov** [comment]
#18663
