### ISSUE TITLE
Cannot reference a nested column in a MATERIALIZED expression during CREATE TABLE

### ISSUE THREAD

**Issue by fpacifici** [ClickHouse/ClickHouse#12586]
Hi,
I am trying to create a table with a MATERIALIZED column. The expression of the MATERIALIZED column contains a reference to a field from a nested column. This causes a `Missing columns` error during the CREATE TABLE statement.

```
CREATE TABLE tab1 (
    col1 Nested(key String, value String), 
    col2 Array(String) MATERIALIZED col1.key)  # really any expression that references col1.key or col2.value
ENGINE MergeTree() ORDER BY col1.key
```

Produces:
```
Code: 47. DB::Exception: Received from localhost:9000. DB::Exception: Missing columns: 'col1.key' while processing query: 'CAST(col1.key AS col2_tmp, 'Array(String)') AS col2, col2_tmp', required columns: 'col1.key', source columns: 'col2' 'col1'. 
```

While adding the materialized clause after the creation works just fine
```
CREATE TABLE tab1 (col1 Nested(key String, value String), col2 Array(String)) ENGINE MergeTree() ORDER BY col1.key;
ALTER TABLE tab1 MODIFY COLUMN col2 MATERIALIZED col1.key;
```

I could not find on the doc whether this behavior is expected or not. Is it expected?

**How to reproduce**
* Clickhouse 19.17.4
* Reproduces on the command line interface as well as with the python native driver

Thanks

**Comment by den-crane** [comment]
Nested is just a syntax sugar for `CREATE TABLE`.

WA (provides the same result as Nested): 
```
CREATE TABLE tab1 (
    `col1.key` Array(String),
    `col.value` Array(String), 
    col2 Array(String) MATERIALIZED `col1.key`) 
ENGINE MergeTree() ORDER BY col1.key
```

**Comment by fpacifici** [comment]
Indeed, this way it works. So I guess it is expected, right ?

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/7677
