### ISSUE TITLE
Read kafka data and merge it automatically

### ISSUE THREAD

**Issue by boy-xiaozhang** [ClickHouse/ClickHouse#12588]
Scenario: Consider that the data is in binlog form and changes frequently
Purpose :ClickHouse creates views after consuming KAFKA data to automatically merge data with the same primary key and retain the latest data
If there is a solution, I hope the ClikHouse team can help reply. Thank you

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/5125
