### ISSUE TITLE
'select count(*) from mysql()' returns String instead of UInt64

### ISSUE THREAD

**Issue by M1NGc** [ClickHouse/ClickHouse#12597]
![image](https://user-images.githubusercontent.com/26264126/87934868-8f029a00-cac2-11ea-8982-ff23334a6749.png)
DB::Exception: Bad get: has String, requested UInt64 (version 20.1.11.73 (official build))

**Comment by 4ertus2** [comment]
The error means: ClickHouse expects to get data with type`UInt64` value for `select count(*) from something` but `mysql()` table function returns `String` instead. It could be an error in `mysql()` table function or some unexpected behaviour we could detect.

What result do you have in mysql console for `select count(*) from <you_table>`?
