### ISSUE TITLE
"Not found column" when using two columns with the same name and GROUP BY

### ISSUE THREAD

**Issue by wendelb** [ClickHouse/ClickHouse#12604]
**Describe the bug**
Clickhouse seems to be unable to find the source for a column for the aggregation function for a column where the name is ambigious but specified with alias.

**How to reproduce**
* Which ClickHouse server version to use: 20.5.2.7
* Which interface to use, if matters: HTTP (but should not matter)
* Non-default settings, if any: None that I am aware of

```sql
CREATE TABLE `source` (
	`key` FixedString(15),
	`name` Int8,
	`value` Int8
) ENGINE = Log();

CREATE TABLE `target` (
	`key` FixedString(15),
	`name` Int8,
	`flower` Int8
) ENGINE = Log();

-- Query 1: Exception
SELECT 
	`source`.`key`,
	max(dummy.`key`)
FROM `source`
INNER JOIN (
	SELECT `key`, name, flower FROM `target`
) AS dummy ON `source`.name = dummy.name
GROUP BY `source`.`key`;

-- Query 2: Working
SELECT 
	`source`.`key`,
	max(dummy.`key2`)
FROM `source`
INNER JOIN (
	SELECT `key` as `key2`, name, flower FROM `target`
) AS dummy ON `source`.name = dummy.name
GROUP BY `source`.`key`
```

**Expected behavior**
Clickhouse should be able to distinguish between the the column `source.key` that is used in the `GROUP BY` statement and the column `dummy.key` (or `target.key`).

**Error message and/or stacktrace**
When running the first query, the following exception is returned from the database:
```
ClickHouse exception, code: 10, host: my.clickhouse.host, port: 8080; Code: 10, e.displayText() = DB::Exception: Not found column dummy.key in block. There are only columns: key (version 20.5.2.7 (official build))
```

**Additional context**
As you can see in the second query, if you remove any ambigious columns from the `SELECT` part, the problem seems to be gone.
This may be related to https://github.com/ClickHouse/ClickHouse/issues/12601

**Comment by 4ertus2** [comment]
Reproduced. `GROUP BY` eats column.

```
SELECT source.key, target.key FROM (SELECT 1 key, 'x' name) source
INNER JOIN (SELECT 2 key, 'x' name) target
ON source.name = target.name
ORDER BY source.key; -- OK

SELECT source.key, max(target.key) FROM (SELECT 1 key, 'x' name) source
INNER JOIN (SELECT 2 key, 'x' name) target
ON source.name = target.name
GROUP BY source.key; -- FAIL
```

**Comment by shacuros** [comment]
as a workaround, you can temporary disable this setting:
set optimize_aggregators_of_group_by_keys = 1;

**Comment by sdienelt** [comment]
Unfortunately this issue still appears with the latest stable version 20.10.3.30 and hinders us upgrading our production instances.
Is this an intended behaviour, so we need to check and modify all of our queries, which are affected?
