### ISSUE TITLE
GRANT PRIVILEGE: certain privileges cannot be granted at column level on specific tables

### ISSUE THREAD

**Issue by ritaank** [ClickHouse/ClickHouse#12600]
**Describe the bug**
On tables of the form `{table, database.table}`, granting one of these privileges `{dictGet, CREATE, DROP, TRUNCATE, OPTIMIZE, SYSTEM}` fails with exception `Exception: {privilege} cannot be granted on the column level.`

**How to reproduce**
The example below shows column level grants failing for the `SYSTEM` privilege on both tables. These failures also happen for the `dictGet`, `CREATE`, `DROP` and `TRUNCATE` privileges as well, in the exact same way.
```
ClickHouse client version 20.7.1.4119 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 20.7.1 revision 54437.

clicktest :) grant system(x) on db0 to user0
GRANT SYSTEM(x) ON db0 TO user0

Received exception from server (version 20.7.1):
Code: 509. DB::Exception: Received from localhost:9000. DB::Exception: SYSTEM cannot be granted on the column level.
0 rows in set. Elapsed: 0.002 sec.

clicktest :) grant system(x) on db0.table0 to user0
GRANT SYSTEM(x) ON db0.table0 TO user0

Received exception from server (version 20.7.1):
Code: 509. DB::Exception: Received from localhost:9000. DB::Exception: SYSTEM cannot be granted on the column level.
0 rows in set. Elapsed: 0.003 sec.
```

**Expected behavior**
For all other combinations of privilege and table, the column level grants appear to work fine.
Additionally, when using `REVOKE PRIVILEGE`, we are able to revoke, at the column level, the above failing combinations of `{privilege, table}`. See examples for `REVOKE` shown for `SYSTEM` privilege:

`REVOKE SYSTEM(x) ON db0 FROM user0` ---> OK
`REVOKE SYSTEM(x) ON db0.table0 FROM user0` ---> OK

The same is the case when revoking the other privileges from  `{dictGet, CREATE, DROP, TRUNCATE, OPTIMIZE, SYSTEM}`. I would imagine that if a certain privilege can be REVOKED at the column level on a certain table, it should be able to be GRANTED at the column level for that table as well.

**Comment by vitlibar** [comment]
The `SYSTEM` privilige can be granted on global, database, or table level. It cannot be granted on column level because it doesn't make sense.

```
GRANT SYSTEM ON db0.* TO user0
```
should work.

The command `REVOKE SYSTEM(x) ON db0.table0 FROM user0` doesn't throw an exception but it does nothing.
