### ISSUE TITLE
Build/run ClickHouse on Itanium

### ISSUE THREAD

**Issue by ppokrovsky** [ClickHouse/ClickHouse#12612]
Hi. I could not find any relevant docs or links. I have an old HP server with Itanium CPU. Itanium is not listed on clickhouse.tech among supported architectures. Is it possible to build and run ClickHouse on Itanium, e.g. if I build it from sources?

**Comment by alexey-milovidov** [comment]
It is not officially supported and will not compile and work out of the box.
It should be possible with some modifications.
As far as I know, no one tried it yet.

Adding a new platform (64bit little endian platform with modern compilers support) for ClickHouse is mostly straightforward if you disable some libraries, but you should expect that it will require at least a few days of efforts.

As Itanium is going away, it doesn't make sense to maintain it.

**Comment by alexey-milovidov** [comment]
I don't see IA64 in the list of targets for LLVM: https://github.com/llvm/llvm-project/tree/master/llvm/lib/Target
But gcc is available (still). https://www.phoronix.com/scan.php?page=news_item&px=Intel-IA-64-GCC-Deprecation
