### ISSUE TITLE
setup tls in clickhouse server

### ISSUE THREAD

**Issue by gane5hvarma** [ClickHouse/ClickHouse#12628]
i have uncommited this line `<tcp_port_secure>9440</tcp_port_secure>` in config.xml and restarted the clickhouse server. But then port 9440 wasnt showing in lsof output. is there something i'm missing.
i did native installation
`sudo apt-get install -y clickhouse-server clickhouse-client`

**Comment by alexey-milovidov** [comment]
@gane5hvarma If the server cannot start listening on port with TLS it will print explanation in it's log.
You can read it in `/var/log/clickhouse-server/clickhouse-server.log`

**Comment by gane5hvarma** [comment]
@alexey-milovidov looked into the logs. i was missing server.key file. it worked after adding these files server.crt, server.key and dhpharam.pem
