### ISSUE TITLE
Alter storage policy for existing table

### ISSUE THREAD

**Issue by keliss** [ClickHouse/ClickHouse#12632]
Hello. Could you please provide me with an example of a query that switches the storage policy of a table? And Is it possible at all or the only option that I have is to add disks to an existing policy?

**Comment by jsding** [comment]
Hi, Any comments on changing existing table's storage policy? No document found.

Thanks for your help

**Comment by jsding** [comment]
I found
> Once a table is created, its storage policy cannot be changed
https://clickhouse.tech/docs/en/engines/table-engines/mergetree-family/mergetree/

So there is no way to change the storage policy for existing tables. :(

**Comment by den-crane** [comment]
It's not true and documentation is incorrect.

` alter table sp modify setting storage_policy='default1'`

New policy should include all disks / volumes which were included into old one.
After that you can move all tables to a new volume. And remove old volumes from the new policy.

**Comment by keliss** [comment]
Cool, thank you

**Comment by jsding** [comment]
> It's not true and documentation is incorrect.
> 
> ` alter table sp modify setting storage_policy='default1'`
> 
> New policy should include all disks / volumes which were included into old one.
> After that you can move all tables to a new volume. And remove old volumes from the new policy.

Thanks. Do you need to restart clickhouse to apply the new storage policy?

**Comment by woozhijun** [comment]
> It's not true and documentation is incorrect.
> 
> ` alter table sp modify setting storage_policy='default1'`
> 
> New policy should include all disks / volumes which were included into old one. After that you can move all tables to a new volume. And remove old volumes from the new policy.

I am same problem, The configuration is as follows:
```
<yandex>
  <storage_configuration>
    <disks>
        <default> <!-- disk name -->
            <keep_free_space_bytes>161061273600</keep_free_space_bytes>
        </default>
        <hdd>
            <path>/home/data/clickhouse/</path>
            <keep_free_space_bytes>386547056640</keep_free_space_bytes>
        </hdd>
    </disks>

    <policies>
        <hot_and_cold>
            <volumes>
                <hot>
                    <disk>default</disk>
                </hot>
                <cold>
                    <disk>hdd</disk>
                </cold>
            </volumes>
            <move_factor>0.1</move_factor>
        </hot_and_cold>
    </policies>
  </storage_configuration>
</yandex>
```
Execute:
```ALTER TABLE xx.xx MODIFY SETTING storage_policy = 'hot_and_cold';```

Version: 21.3.xx

@den-crane 
Ask for help! Thx.

**Comment by arvindeybram** [comment]
Yes, agreeing with @woozhijun - the documentation is not correct,
I am also facing issues with changing storage settings when the default is specified.

**Comment by wanton** [comment]
I think the problem in @woozhijun's case is the volume name in the new policy. Try changing the name of the volume in the new policy from `hot` to `default` (if that was the old name). Maybe that solves the problem for you too @arvindeybram?

**Comment by alanpaulkwan** [comment]
If we alter storage policy of an existing table, will clickhouse be able to move the data for us? It's really painful otherwise.

**Comment by juangentile** [comment]
just in case someone needs an answer to the last question, it's explained in the documentation link above
https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/mergetree/
```
You could change storage policy after table creation with [ALTER TABLE ... MODIFY SETTING] query, new policy should include all old disks and volumes with same names.
The number of threads performing background moves of data parts can be changed by [background_move_pool_size](https://clickhouse.com/docs/en/operations/settings/settings/#background_move_pool_size) setting.
```

**Comment by kaitoan2000** [comment]
> It's not true and documentation is incorrect.
> 
> ` alter table sp modify setting storage_policy='default1'`
> 
> New policy should include all disks / volumes which were included into old one. After that you can move all tables to a new volume. And remove old volumes from the new policy.

DB::Exception: New storage policy `default` shall contain volumes of old one. (BAD_ARGUMENTS)
23.3.1.2823 (official build)
Can't change this policy to encrypted volume too.
┌─policy_name─┬─volume_name──────┬─volume_priority─┬─disks──────────────┬─volume_type─┬─max_data_part_size─┬─move_factor─┬─prefer_not_to_merge─┐
│ default     │ default          │               1 │ ['default']        │ JBOD        │                  0 │           0 │                   0 │
│ encrypted   │ encrypted_volume │               1 │ ['encrypted_disk'] │ JBOD        │                  0 │           0 │                   0 │
└─────────────┴──────────────────┴─────────────────┴────────────────────┴─────────────┴────────────────────┴─────────────┴─────────────────────┘

**Comment by Boomboomdunce** [comment]
Since minio is composed of a single mechanical disk, the read and write speed is too slow. I want to change it to default storage (on solid state disk). The data already stored in minio can be discarded. What do I need to do next?

storage_configuration.xml
```
<clickhouse>
	<storage_configuration>
		<disks>
			<hdd>
				<type>s3</type>
				<endpoint>http://127.0.0.1:7000/clickhouse//</endpoint>
				<access_key_id>minioadmin</access_key_id>
				<secret_access_key>XXXXXXXXXXX</secret_access_key>
				<connect_timeout_ms>500000</connect_timeout_ms>
				<request_timeout_ms>500000</request_timeout_ms>
				<retry_attempts>20</retry_attempts>
				<skip_access_check>true</skip_access_check>
				<single_read_retries>10</single_read_retries>
				<s3_max_put_rps>10</s3_max_put_rps>
			</hdd>
		</disks>
		<policies>
			<moving_from_ssd_to_hdd>
				<volumes>
					<default>
						<disk>default</disk>
					</default>
					<cold>
						<disk>hdd</disk>
					</cold>
				</volumes>
			</moving_from_ssd_to_hdd>
		</policies>
	</storage_configuration>
</clickhouse>
```

```sql
ENGINE = MergeTree
PARTITION BY toYYYYMM(TS)
ORDER BY TS
TTL TS + toIntervalDay(4) TO DISK 'hdd'
SETTINGS index_granularity = 8192, storage_policy = 'moving_from_ssd_to_hdd'
```
When I execute `ALTER TABLE default.tb_original MODIFY SETTING storage_policy = 'default' ` 
An error will be displayed
```
Code: 36. DB::Exception: New storage policy `moving_from_ssd_to_hdd` shall contain volumes of old one. (BAD_ARGUMENTS) (version 22.5.1.2079 (official build)) , server ClickHouseNode [uri=http://127.0.0.1:8123/default, options={custom_http_params=session_id=DataGrip_a80ad35e-f5b0-465b-8ca8-ca510c58a74e}]@-1427160284
```

**Comment by Boomboomdunce** [comment]
> 由于minio是由单个机械磁盘组成，因此读写速度太慢。我想将其更改为默认存储（在固态磁盘上）。已经存储在minio中的数据可以被丢弃。接下来我需要做什么？
> 
> 存储配置.xml
> 
> ```
> <clickhouse>
> 	<storage_configuration>
> 		<disks>
> 			<hdd>
> 				<type>s3</type>
> 				<endpoint>http://127.0.0.1:7000/clickhouse//</endpoint>
> 				<access_key_id>minioadmin</access_key_id>
> 				<secret_access_key>XXXXXXXXXXX</secret_access_key>
> 				<connect_timeout_ms>500000</connect_timeout_ms>
> 				<request_timeout_ms>500000</request_timeout_ms>
> 				<retry_attempts>20</retry_attempts>
> 				<skip_access_check>true</skip_access_check>
> 				<single_read_retries>10</single_read_retries>
> 				<s3_max_put_rps>10</s3_max_put_rps>
> 			</hdd>
> 		</disks>
> 		<policies>
> 			<moving_from_ssd_to_hdd>
> 				<volumes>
> 					<default>
> 						<disk>default</disk>
> 					</default>
> 					<cold>
> 						<disk>hdd</disk>
> 					</cold>
> 				</volumes>
> 			</moving_from_ssd_to_hdd>
> 		</policies>
> 	</storage_configuration>
> </clickhouse>
> ```
> 
> ```sql
> ENGINE = MergeTree
> PARTITION BY toYYYYMM(TS)
> ORDER BY TS
> TTL TS + toIntervalDay(4) TO DISK 'hdd'
> SETTINGS index_granularity = 8192, storage_policy = 'moving_from_ssd_to_hdd'
> ```
> 
> 当我执行时`ALTER TABLE default.tb_original MODIFY SETTING storage_policy = 'default' ` 会显示错误
> 
> ```
> Code: 36. DB::Exception: New storage policy `moving_from_ssd_to_hdd` shall contain volumes of old one. (BAD_ARGUMENTS) (version 22.5.1.2079 (official build)) , server ClickHouseNode [uri=http://127.0.0.1:8123/default, options={custom_http_params=session_id=DataGrip_a80ad35e-f5b0-465b-8ca8-ca510c58a74e}]@-1427160284
> ```

If you don't consider the data on minio and find a method, can modify the Sql statement under metadata directly.
example
`find /var/lib/clickhouse/metadata/default/ -type f -name "*.sql"|xargs sed  -i "s/TO DISK 'hdd'//g"  {} > {}`
