### ISSUE TITLE
Additional metrics added to Prometheus endpoint

### ISSUE THREAD

**Issue by jameshartig** [ClickHouse/ClickHouse#12647]
I noticed that Prometheus support is now available, which is great, but there are some metrics missing that we use in our dashboards and alerts.

**Use case**
We need various replica and part process metrics to alert on replication and to alert/display number of parts per table. Some example queries:
```
SELECT database, table, replica_name, queue_size, absolute_delay, total_replicas, active_replicas, future_parts, parts_to_check, inserts_in_queue, merges_in_queue FROM system.replicas
```
(https://github.com/levenlabs/clickhouse_exporter/blob/master/exporter/exporter.go#L179)

Most important ones are `queue_size` and `absolute_delay`.

```
SELECT database, table, sum(bytes) AS bytes, count() as parts, sum(rows) AS rows, max(max_date) as max_date, max(max_time) as max_time FROM system.parts WHERE active GROUP BY database, table
```
(https://github.com/levenlabs/clickhouse_exporter/blob/master/exporter/exporter.go#L278)

Most important ones is number of `parts`.

We also use some metrics from `system.processes` and `system.mutations` but those are less important compared to the ones above.

**Describe the solution you'd like**
Ideally all of the fields from the replicas table on a per-table basis and a summary of the parts information from each table can be exposed from the Prometheus endpoint.

**Describe alternatives you've considered**
The current way we're going to be operating is running both prometheus's built-in exporter and the external exporter side-by-side until the built-in one is feature complete.

**Additional context**
Original implementation was: https://github.com/ClickHouse/ClickHouse/pull/7900

**Comment by azat** [comment]
prometheus exporter exports only global metrics and hence there is no per-table metrics, besides this may be too specific.

Instead you can use custom http handlers (#7572) to export everything you want, i.e.:

```xml
<!-- cat /etc/clickhouse-server/config.d/http_handlers.xml -->
<yandex>
    <http_handlers>
        <defaults/> <!-- enable default HTTP handlers - https://github.com/ClickHouse/ClickHouse/pull/11628 otherwise prometheus exporter will not work -->

        <!-- custom prometheus metrics for system.distribution_queue  -->
        <rule>
            <url>/metrics/distribution_queue</url>
            <methods>GET</methods>
            <handler>
                <type>predefined_query_handler</type>
                <query>
                    SELECT
                        format('data_paths{{database="{}",table="{}",replica_name="{}"}}', database, table, replica_name),
                        queue_size
                    FROM system.replicas
                    UNION ALL
                    SELECT
                        format('data_paths{{database="{}",table="{}",replica_name="{}"}}', database, table, replica_name),
                        absolute_delay
                    FROM system.replicas
                    <!-- just copy-paste here everything else similarly -->
                </query>
            </handler>
        </rule>
    </http_handlers>
</yandex>
```
