### ISSUE TITLE
Different query result on distributed table (group by issue?)

### ISSUE THREAD

**Issue by xuyatian** [ClickHouse/ClickHouse#12640]
Hi Experts,
    We have a cluster with 20 shards. We get different result when query from distributed table on different shards.
Table Def:
`
CREATE TABLE LocalTable
(
    dateTime String,
    dt String,
    a String,
    b Array(String),
    c String,
    d String,
    e String,
    f String,
    g String,
    h Float64,
    i String,
    j String,
    k String,
    l Float64,
    m String,
    n String,
    o String
)
ENGINE = ReplicatedMergeTree('/tables/DatabaseName/LocalTable/{shard}', '{replica}')
PARTITION BY dt
ORDER BY (dateTime, n, a, i, g, b, d)
SETTINGS index_granularity = 8192

CREATE TABLE DistributedTable
(
    dateTime String,
    dt String,
    a String,
    b Array(String),
    c String,
    d String,
    e String,
    f String,
    g String,
    h Float64,
    i String,
    j String,
    k String,
    l Float64,
    m String,
    n String,
    o String
)
ENGINE = Distributed(Cluster, DatabaseName, LocalTable, rand())
`

SQL1:
`select uniq(e) ,sum(l) ,uniq(f) ,sum(h) , d from DatabaseName. DistributedTable where dateTime >='2020-07-13' and dateTime <= '2020-07-19' and i in ('16946','36713','172439','184613') and g in ('6221','6220','11978','6212','6223','11150','6225','6224','16821','6217','11149') and 1=arrayExists( x-> (x in ('zjtxwlkj')) ,b) and a in ('1','2','3','4','5') and d in ('100007252161') and n in ('pop','out') group by d
`
SQL2: (Remove "group by" from SQL1)
`
select * from DatabaseName. DistributedTable where dateTime >='2020-07-13' and dateTime <= '2020-07-19' and i in ('16946','36713','172439','184613') and g in ('6221','6220','11978','6212','6223','11150','6225','6224','16821','6217','11149') and 1=arrayExists( x-> (x in ('zjtxwlkj')) ,b) and a in ('1','2','3','4','5') and d in ('100007252161') and n in ('pop','out') 
`

When we run SQL1 on different shard, clickhouse returns different result:
shard 1 - 13 returns 137 rows.
shard 14 - 20 returns 0 rows.
When we run SQL2(removed group by) on different shard, clickhouse returns exactly the same result(137 rows)

Is it a group by bug? 

Clickhouse version: v1.1.54385-stable

Thanks.

**Comment by den-crane** [comment]
Please provide a results for 
```
select groupArray(shard_num), groupArray(host_name), groupArray(is_local) 
from system.clusters where cluster = 'Cluster';
```
from shards 1 and 14


And

```
Q1:
SELECT count(),
       hostName() h,
       d
FROM DatabaseName.DistributedTable
WHERE dateTime >= '2020-07-13'
AND   dateTime <= '2020-07-19'
AND   i IN ('16946','36713','172439','184613')
AND   g IN ('6221','6220','11978','6212','6223','11150','6225','6224','16821','6217','11149')
AND   1 = arrayExists(x ->(x IN ('zjtxwlkj')),b)
AND   a IN ('1','2','3','4','5')
AND   d IN ('100007252161')
AND   n IN ('pop','out')
GROUP BY d, h

Q2:
SELECT hostName() h
FROM DatabaseName.DistributedTable
WHERE dateTime >= '2020-07-13'
AND   dateTime <= '2020-07-19'
AND   i IN ('16946','36713','172439','184613')
AND   g IN ('6221','6220','11978','6212','6223','11150','6225','6224','16821','6217','11149')
AND   1 = arrayExists(x ->(x IN ('zjtxwlkj')),b)
AND   a IN ('1','2','3','4','5')
AND   d IN ('100007252161')
AND   n IN ('pop','out')

```
from shards 1 and 14

And 

```
select name,value from system.settings where changed;
```
from shards 1 and 14

**Comment by xuyatian** [comment]
Hi @den-crane ,
  Thanks for quick response.  Let me give more real details. (shard 1-13/14-20 in my previous comments was just an example)
My cluster has 160 nodes (20shard X 8 replica)
### The real result of SQL1:
[sql1_result.txt](https://github.com/ClickHouse/ClickHouse/files/4957474/sql1_result.txt)
### The real result of SQL2:
[sql2_result.txt](https://github.com/ClickHouse/ClickHouse/files/4957475/sql2_result.txt)

### Cluster Info:
[cluster_info.txt](https://github.com/ClickHouse/ClickHouse/files/4957472/cluster_info.txt)
### The mapping of hostname and IP address:
[host_ip_mapping.txt](https://github.com/ClickHouse/ClickHouse/files/4957473/host_ip_mapping.txt)

### A1:
[A1.txt](https://github.com/ClickHouse/ClickHouse/files/4957517/A1.txt)

### A2:
[A2.txt](https://github.com/ClickHouse/ClickHouse/files/4957518/A2.txt)

### Changed Settings:
max_query_size  1524288
use_uncompressed_cache  0
background_pool_size    32
load_balancing  random
log_queries     1
empty_result_for_aggregation_by_empty_set       1
max_memory_usage        100000000000

**Comment by xuyatian** [comment]
I simplify the SQL1 and SQL2 as below:
### SQL1 and Result:
```sql
select count(e) from DatabaseName.DistributedTable where dateTime ='2020-07-13' and d ='100007252161' group by d
```
Result on 160 nodes:
[sql1_result.txt](https://github.com/ClickHouse/ClickHouse/files/4958067/sql1_result.txt)


### SQL2(removed group by) and Result:
```sql
select count(e) from DatabaseName.DistributedTable where dateTime ='2020-07-13' and d ='100007252161'
```
Result on 160 nodes:
[sql2_result.txt](https://github.com/ClickHouse/ClickHouse/files/4958069/sql2_result.txt)

**Comment by den-crane** [comment]
Try to disable distributed_aggregation_memory_efficient 
set distributed_aggregation_memory_efficient = 0 
and check query with group by

**Comment by xuyatian** [comment]
@den-crane，
    set distributed_aggregation_memory_efficient = 0 does not work ..All hosts are the same 1.1.54385. The clickhouse cluster was set up 2 years ago...
   will upgrade to latest version.
thanks.
