### ISSUE TITLE
Header of CSVWithNames missing in HTTP queries

### ISSUE THREAD

**Issue by hczhcz** [ClickHouse/ClickHouse#12654]
**Describe the bug**
If we make a query with `format CSVWithNames` via HTTP, ClickHouse would not return the CSV header.

**How to reproduce**
* Which ClickHouse server version to use
Git: 1893d8

* Which interface to use, if matters
HTTP

* Queries to run that lead to unexpected result
`echo 'select 1 as x format CSVWithNames' | curl 'localhost:8123' --data-binary @-`
It returns `1\n`.

**Expected behavior**
It should return `"x"\n1\n`.

**Comment by den-crane** [comment]
duplucate https://github.com/ClickHouse/ClickHouse/issues/12504
