### ISSUE TITLE
dictGet query exception

### ISSUE THREAD

**Issue by templarzq** [ClickHouse/ClickHouse#12651]
**Describe the bug**
dictGet funtion query with group by failed.

**How to reproduce**
* Which ClickHouse server version to use
version 20.5.2.7
* Which interface to use, if matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
CREATE DICTIONARY IF NOT EXISTS db.test_dict  ON CLUSTER test_cluster
(
	key String ,
	valueCode String DEFAULT ''
)
PRIMARY KEY key 
SOURCE(	FILE(path '/home/xxxx/user_files/test_dict.csv' format 'CSV'))  
LAYOUT(COMPLEX_KEY_HASHED())
LIFETIME(MIN 10 MAX 30)
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result
	select key,dictGet('db.test_dict','valueCode', tuple(key)) as c1 from   db.test_dict tb 
	group by key,c1

   if i use query:
         select key,dictGet('db.test_dict','valueCode', tuple(key)) as c1 from   db.test_dict tb 
   the result is correct.

**Expected behavior**
      get result of group by 

**Error message and/or stacktrace**
ClickHouse exception, code: 42, host: xxxx, port: xxx; Code: 42, e.displayText() = DB::Exception: Function dictGet... takes 3 or 4 arguments (version 20.5.2.7)

**Additional context**
 maybe the parser has bug?

**Comment by den-crane** [comment]
Use WA:
```
select key,dictGet('db.test_dict','valueCode', tuple(key)) as c1 from db.test_dict tb
group by key
```
or
```
select key,dictGetString('db.test_dict','valueCode', tuple(key)) as c1 from db.test_dict tb
group by key,c1
```

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/11469
