### ISSUE TITLE
how to kill optimize FINAL  in backgroud

### ISSUE THREAD

**Issue by zhlovy** [ClickHouse/ClickHouse#12694]
i optimize a big table (replicedReplacingMergeTree)   , it makes io  100%   ,so i want to kill this optimize FINAL  
how can i do ?

<Debug> default.users (ReplicatedMergeTreeQueue): Not executing log entry MERGE_PARTS for part 20200630_0_307423_23 because source parts size (67.06 GiB) is greater than the current maximum (7.58 GiB).

thanks advance

**Comment by zhlovy** [comment]
select *  FROM system.processes  ;   the result is null   ,  so can`t kill it

**Comment by alesapin** [comment]
The only way is to call `SYSTEM STOP MERGES table_name`. **All merges** will be aborted, after that, you should start them again with `SYSTEM START MERGES table_name`. After that normal merges will start again, without FINAL merges from optimize.

**Comment by zhlovy** [comment]
thanks ~ 
Thanks a lot for the trouble you've taken to help me!
