### ISSUE TITLE
DateTime conversion error

### ISSUE THREAD

**Issue by grmorozov** [ClickHouse/ClickHouse#12740]
The following code works fine with CH versions 19.13 up to 19.17:
```CREATE DATABASE test;

CREATE TABLE IF NOT EXISTS test.event (
    date Date,
    time DateTime,
    session UInt64 DEFAULT CAST(0, 'UInt64'),
    duration UInt32 DEFAULT CAST(0, 'UInt32')
)
ENGINE = MergeTree()
PARTITION BY toYYYYMM(date)
ORDER BY (date, session);

CREATE MATERIALIZED VIEW IF NOT EXISTS test.event_hourly_aggregate
(
    date Date,
    hour DateTime,
    session UInt64,
    start_time AggregateFunction(min, DateTime),
    end_time AggregateFunction(max, DateTime),
    time ALIAS hour
)
ENGINE = AggregatingMergeTree()
PARTITION BY toYYYYMM(date)
ORDER BY (date, hour, session)
AS
SELECT
	date,
	toStartOfHour(time) hour,
	session,
	minState(time - duration) AS start_time,
	maxState(time) AS end_time
FROM test.event
GROUP BY (date, hour, session);

insert into test.event(date, time, session, duration)
values ('2020-07-23', '2020-07-23 01:02:03', 1, 5);
```

However, running the same code on ClickHouse version 20.1 returns an error: `Code: 70. DB::Exception: Received from localhost:9000. DB::Exception: Conversion from AggregateFunction(min, DateTime('Etc/UTC')) to AggregateFunction(min, DateTime) is not supported: while converting source column start_time to destination column start_time: while pushing to view test.event_hourly_aggregate.`

On the later versions (I checked 20.3 and 20.4), error looks the same, except the name of the timezone: `Code: 70. DB::Exception: Received from localhost:9000. DB::Exception: Conversion from AggregateFunction(min, DateTime('UTC')) to AggregateFunction(min, DateTime) is not supported: while converting source column start_time to destination column start_time: while pushing to view test.event_hourly_aggregate.`

I didn't find anything related in the change log (https://github.com/ClickHouse/ClickHouse/blob/master/CHANGELOG.md).

Is it expected behaviour? What is the best way to make my code work with newer versions?

**Comment by den-crane** [comment]
>time - duration 

because of
```
DESCRIBE TABLE
(
    SELECT
        now() - 5 AS x,
        now() AS y,
        toDateTime(x, '') AS z
)

┌─name─┬─type────────────────┬─
│ x    │ DateTime('Etc/UTC') │
│ y    │ DateTime            │
│ z    │ DateTime            │
└──────┴─────────────────────┴─
```

WA: minState(**toDateTime(time - duration,''**) AS start_time,

**Comment by grmorozov** [comment]
Thank you! I'll use this workaround.

My point was that it works with older versions. Was it intended backward incompatible change?

**Comment by grmorozov** [comment]
Also, is it enough to alter existing MV to upgrade CH version, or do I need to recreate it?

**Comment by den-crane** [comment]
>My point was that it works with older versions. 

I understand.

>Was it intended backward incompatible change?

Probably it was intentional change to fix something. But it became an issue in your case. Unfortunately it seems it does not covered by integration tests. And actually you are the first who complain about it, probably it kinda rare case.

>is it enough to alter existing MV to upgrade CH version

it's  enough to alter existing MV.

option 1 (recommended):

```
detach table test.event_hourly_aggregate;

attach MATERIALIZED VIEW IF NOT EXISTS test.event_hourly_aggregate
(
    date Date,
    hour DateTime,
    session UInt64,
    start_time AggregateFunction(min, DateTime),
    end_time AggregateFunction(max, DateTime),
    time ALIAS hour
)
ENGINE = AggregatingMergeTree()
PARTITION BY toYYYYMM(date)
ORDER BY (date, hour, session)
AS
SELECT
	date,
	toStartOfHour(time) hour,
	session,
	minState(toDateTime(time - duration,'')) AS start_time,
	maxState(time) AS end_time
FROM test.event
GROUP BY (date, hour, session);
```


option 2 (experimental):
```
set allow_experimental_alter_materialized_view_structure=1;
ALTER TABLE test.event_hourly_aggregate MODIFY QUERY 
SELECT
	date,
	toStartOfHour(time) hour,
	session,
	minState(toDateTime(time - duration,'')) AS start_time,
	maxState(time) AS end_time
FROM test.event
GROUP BY (date, hour, session);
```
