### ISSUE TITLE
why doesn't my ngrambf_v1 index  work well

### ISSUE THREAD

**Issue by weiyongyuan** [ClickHouse/ClickHouse#12743]
### 2.table ddl
 CREATE TABLE default.ip_test2
(
    `found_time` UInt32,
    `d_ip` String,
    INDEX d_ip_bl_idx d_ip TYPE bloom_filter(0.001) GRANULARITY 1,
    INDEX d_ip_idx2 d_ip TYPE ngrambf_v1(3, 315119, 6, 0) GRANULARITY 1
)
ENGINE = MergeTree()
PARTITION BY toRelativeHourNum(toDateTime(found_time))
ORDER BY found_time
SETTINGS index_granularity = 8192;
### 3.the data count is 10000000. the sample data like below
┌─found_time─┬─d_ip────────────────────────────────────┐
│ 1592591894 │ 3200:1010:1100:0100:0110:1110:1100:0001 │
│ 1592591894 │ 8010:1100:1010:0100:0000:1010:1010:2031 │
│ 1592591894 │ 102.171.195.13                          │
│ 1592591894 │ d110:1100:0100:1000:0100:0010:1100:1310 │
│ 1592591894 │ 3110:0010:0000:0110:1100:0110:1100:0012 │
│ 1592591894 │ a300:0100:1110:1000:0000:0010:1110:0000 │
│ 1592591894 │ 2200:1000:0000:0100:1110:0100:1000:3131 │
│ 1592591894 │ 5210:0110:0100:0100:1000:1000:1000:0001 │
│ 1592591894 │ 3001:1000:0110:0000:1010:0110:0100:2320 │
│ 1592591894 │ 116.184.47.2                            │
└────────────┴─────────────────────────────────────────┘
### 4.my query sql:select * from default.ip_test2 where d_ip like '%171.195%' limit 10;the below is query log.My question is why doesn't d_ip_idx2 drop 0 granules?are the prameters i give to the ngrambf_v1 wrong?
>The query result is 10 rows,if every result is in a index_granularity 8192,10 rows locates in 81920 rows,but the query shows that it scan 400million rows!
>
[bd-server-19] 2020.07.24 09:07:18.203411 [ 127961 ] {b5d1900f-6870-4c13-8383-03de0b0f126e} <Debug> InterpreterSelectQuery: MergeTreeWhereOptimizer: condition "d_ip LIKE '%171.195%'" moved to PREWHERE
[bd-server-19] 2020.07.24 09:07:18.203639 [ 127961 ] {b5d1900f-6870-4c13-8383-03de0b0f126e} <Trace> ContextAccess (default): Access granted: SELECT(found_time, d_ip) ON default.ip_test2
[bd-server-19] 2020.07.24 09:07:18.203816 [ 127961 ] {b5d1900f-6870-4c13-8383-03de0b0f126e} <Debug> default.ip_test2 (SelectExecutor): Key condition: unknown
[bd-server-19] 2020.07.24 09:07:18.203847 [ 127961 ] {b5d1900f-6870-4c13-8383-03de0b0f126e} <Debug> default.ip_test2 (SelectExecutor): MinMax index condition: unknown
[bd-server-19] 2020.07.24 09:07:18.219786 [ 127961 ] {b5d1900f-6870-4c13-8383-03de0b0f126e} <Debug> default.ip_test2 (SelectExecutor): Index `d_ip_idx2` has dropped 0 granules.
[bd-server-19] 2020.07.24 09:07:18.248175 [ 127961 ] {b5d1900f-6870-4c13-8383-03de0b0f126e} <Debug> default.ip_test2 (SelectExecutor): Index `d_ip_idx2` has dropped 0 granules.
[bd-server-19] 2020.07.24 09:07:18.281673 [ 127961 ] {b5d1900f-6870-4c13-8383-03de0b0f126e} <Debug> default.ip_test2 (SelectExecutor): Index `d_ip_idx2` has dropped 0 granules.
[bd-server-19] 2020.07.24 09:07:18.306771 [ 127961 ] {b5d1900f-6870-4c13-8383-03de0b0f126e} <Debug> default.ip_test2 (SelectExecutor): Index `d_ip_idx2` has dropped 0 granules.
[bd-server-19] 2020.07.24 09:07:18.330602 [ 127961 ] {b5d1900f-6870-4c13-8383-03de0b0f126e} <Debug> default.ip_test2 (SelectExecutor): Index `d_ip_idx2` has dropped 0 granules.
[bd-server-19] 2020.07.24 09:07:18.345376 [ 127961 ] {b5d1900f-6870-4c13-8383-03de0b0f126e} <Debug> default.ip_test2 (SelectExecutor): Index `d_ip_idx2` has dropped 0 granules.
[bd-server-19] 2020.07.24 09:07:18.361686 [ 127961 ] {b5d1900f-6870-4c13-8383-03de0b0f126e} <Debug> default.ip_test2 (SelectExecutor): Index `d_ip_idx2` has dropped 0 granules.
[bd-server-19] 2020.07.24 09:07:18.377417 [ 127961 ] {b5d1900f-6870-4c13-8383-03de0b0f126e} <Debug> default.ip_test2 (SelectExecutor): Index `d_ip_idx2` has dropped 0 granules.
[bd-server-19] 2020.07.24 09:07:18.384960 [ 127961 ] {b5d1900f-6870-4c13-8383-03de0b0f126e} <Debug> default.ip_test2 (SelectExecutor): Index `d_ip_idx2` has dropped 0 granules.
[bd-server-19] 2020.07.24 09:07:18.392819 [ 127961 ] {b5d1900f-6870-4c13-8383-03de0b0f126e} <Debug> default.ip_test2 (SelectExecutor): Index `d_ip_idx2` has dropped 0 granules.
[bd-server-19] 2020.07.24 09:07:18.401857 [ 127961 ] {b5d1900f-6870-4c13-8383-03de0b0f126e} <Debug> default.ip_test2 (SelectExecutor): Index `d_ip_idx2` has dropped 0 granules.
[bd-server-19] 2020.07.24 09:07:18.409763 [ 127961 ] {b5d1900f-6870-4c13-8383-03de0b0f126e} <Debug> default.ip_test2 (SelectExecutor): Index `d_ip_idx2` has dropped 0 granules.
[bd-server-19] 2020.07.24 09:07:18.418204 [ 127961 ] {b5d1900f-6870-4c13-8383-03de0b0f126e} <Debug> default.ip_test2 (SelectExecutor): Index `d_ip_idx2` has dropped 0 granules.
[bd-server-19] 2020.07.24 09:07:18.426288 [ 127961 ] {b5d1900f-6870-4c13-8383-03de0b0f126e} <Debug> default.ip_test2 (SelectExecutor): Index `d_ip_idx2` has dropped 0 granules.
[bd-server-19] 2020.07.24 09:07:18.434560 [ 127961 ] {b5d1900f-6870-4c13-8383-03de0b0f126e} <Debug> default.ip_test2 (SelectExecutor): Index `d_ip_idx2` has dropped 0 granules.
[bd-server-19] 2020.07.24 09:07:18.441925 [ 127961 ] {b5d1900f-6870-4c13-8383-03de0b0f126e} <Debug> default.ip_test2 (SelectExecutor): Index `d_ip_idx2` has dropped 0 granules.
[bd-server-19] 2020.07.24 09:07:18.457873 [ 127961 ] {b5d1900f-6870-4c13-8383-03de0b0f126e} <Debug> default.ip_test2 (SelectExecutor): Index `d_ip_idx2` has dropped 0 granules.
[bd-server-19] 2020.07.24 09:07:18.457909 [ 127961 ] {b5d1900f-6870-4c13-8383-03de0b0f126e} <Debug> default.ip_test2 (SelectExecutor): Selected 17 parts by date, 17 parts by key, 1230 marks to read from 17 ranges
[bd-server-19] 2020.07.24 09:07:18.458151 [ 127961 ] {b5d1900f-6870-4c13-8383-03de0b0f126e} <Trace> default.ip_test2 (SelectExecutor): Reading approx. 10076160 rows with 28 streams

the resultis :
┌─found_time─┬─d_ip───────────┐
│ 1592601429 │ 46.171.195.198 │
└────────────┴────────────────┘
┌─found_time─┬─d_ip───────────┐
│ 1592633446 │ 90.180.171.195 │
└────────────┴────────────────┘
┌─found_time─┬─d_ip──────────┐
│ 1592613116 │ 122.171.195.5 │
└────────────┴───────────────┘
┌─found_time─┬─d_ip─────────┐
│ 1592593924 │ 76.171.195.1 │
└────────────┴──────────────┘
┌─found_time─┬─d_ip───────────┐
│ 1592623000 │ 184.171.195.78 │
└────────────┴────────────────┘
┌─found_time─┬─d_ip─────────┐
│ 1592597161 │ 17.171.195.3 │
└────────────┴──────────────┘
┌─found_time─┬─d_ip───────────┐
│ 1592643661 │ 171.195.229.10 │
│ 1592643661 │ 213.171.195.8  │
└────────────┴────────────────┘
┌─found_time─┬─d_ip──────────┐
│ 1592601429 │ 171.195.231.7 │
└────────────┴───────────────┘
┌─found_time─┬─d_ip───────────┐
│ 1592625726 │ 78.218.171.195 │
└────────────┴────────────────┘

**_10 rows in set. Elapsed: 0.334 sec. Processed 4.00 million rows,_** 139.73 MB (11.97 million rows/s., 418.41 MB/s.)

**Comment by genzgd** [comment]
Skip indexes work by skipping blocks of data that are guaranteed not to contain the requested values.  They improve efficiency by reducing the amount of data that needs to be read and evaluated to accurately respond to the query.   Your skip index uses a granularity of 1, meaning that each block the index is applied to contains one granule.  By default those granules will contain 8192 values.

An ngram skip index uses a bloom filter to determine if the requested ngram is present in each granule.  You are using an ngram size of 3, meaning your filter value of `171.195` will be broken into five ngrams -- `171`, `71.1`, `1.1`, `1.19`, and `195`.  If **any** of those ngrams is contain within **any** of the 8192 IP values in the granule, ClickHouse cannot skip that granule and must read all of the data, so the skip index gains nothing.   The chances of at least one of those ngrams being present in a granule of 8192 values is very high.

 You might get better result if you use a larger ngram size, but chances are still high that you would not skip a meaningful number of granules.  Other approaches to improve your query performance, since as including the IP address as part of your primary key, will almost certainly be more effective.
