### ISSUE TITLE
 How to import csv file with multiple delimiter character

### ISSUE THREAD

**Issue by melin** [ClickHouse/ClickHouse#12744]
How to import csv file with multiple delimiter character, example:
```csv
name$$city$$age
ss$$hangzhou$$28
dd$$shanghai$$30
```

```
(base) [admin@datainsight-d-006052 ~]$ clickhouse-client --password ck2020 --format_csv_delimiter="$$" --query="insert into default.users FORMAT CSVWithNames" < test.csv
Code: 19, e.displayText() = DB::Exception: A setting's value string has to be an exactly one character long, Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x10f1e130 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x95f82cd in /usr/bin/clickhouse
2. ? @ 0xd97cb2e in /usr/bin/clickhouse
3. boost::function1<void, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>::operator()(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const @ 0x96ef582 in /usr/bin/clickhouse
4. boost::program_options::variables_map::notify() @ 0xed23245 in /usr/bin/clickhouse
5. DB::Client::init(int, char**) @ 0x96e9390 in /usr/bin/clickhouse
6. mainEntryClickHouseClient(int, char**) @ 0x96c720f in /usr/bin/clickhouse
7. main @ 0x95f3919 in /usr/bin/clickhouse
8. __libc_start_main @ 0x22555 in /usr/lib64/libc-2.17.so
9. _start @ 0x95f302e in /usr/bin/clickhouse
 (version 20.5.3.27 (official build))
```

spark 3.0 version is supported
http://blog.madhukaraphatak.com/spark-3-introduction-part-1/

**Comment by den-crane** [comment]
```
create table XC(name String, city String, age Int64) Engine=Memory;

cat xx.csv
name$$city$$age
ss$$hangzhou$$28
dd$$shanghai$$30


cat xx.csv |clickhouse-client -q "insert into XC FORMAT CustomSeparated SETTINGS format_custom_escaping_rule = 'CSV', format_custom_field_delimiter = '\$\$', format_custom_result_before_delimiter='name\$\$city\$\$age\n'"

 select *  from XC
┌─name─┬─city─────┬─age─┐
│ ss   │ hangzhou │  28 │
│ dd   │ shanghai │  30 │
└──────┴──────────┴─────┘
```

**Comment by melin** [comment]
> ```
> create table XC(name String, city String, age Int64) Engine=Memory;
> 
> cat xx.csv
> name$$city$$age
> ss$$hangzhou$$28
> dd$$shanghai$$30
> 
> 
> cat xx.csv |clickhouse-client -q "insert into XC FORMAT CustomSeparated SETTINGS format_custom_escaping_rule = 'CSV', format_custom_field_delimiter = '\$\$', format_custom_result_before_delimiter='name\$\$city\$\$age\n'"
> 
>  select *  from XC
> ┌─name─┬─city─────┬─age─┐
> │ ss   │ hangzhou │  28 │
> │ dd   │ shanghai │  30 │
> └──────┴──────────┴─────┘
> ```

 Failed to import data using clickhouse-jdbc

```
ckStatement.write()
        .sql("INSERT INTO " + tableName + " (" + StringUtils.join(fields, ",") + ")")
        .option("input_format_allow_errors_num", allowErrNum.toString())
        .withDbParams(additionalDBParams)
        .option("format_custom_escaping_rule", "CSV")
        .option("format_custom_field_delimiter", '\$\$')
        .option("format_custom_result_before_delimiter", "name\$\$city\$\$age\n")
        .data(file, ClickHouseFormat.CustomSeparated)
        .send();
```

```
Delimiter 0: "name<BACKSLASH>$<BACKSLASH>$city<BACKSLASH>$<BACKSLASH>$age<LINE FEED>"
Column 0: "data" (mapped to table column 0), Format None
Delimiter 1: <EMPTY>
 (version 20.5.2.7 (official build))
; nested exception is ru.yandex.clickhouse.except.ClickHouseException: ClickHouse exception, code: 474, host: 192.168.6.52, port: 8123; Code: 474, e.displayText() = DB::Exception: Invalid format string for Template: Cannot parse input: expected 'name\\$\\$city\\$\\$age\n' before: 'ss$$hangzhou$$28\ndd$$shanghai$$30' While parsing prefix (near column 0). Parsed format string:

Delimiter 0: "name<BACKSLASH>$<BACKSLASH>$city<BACKSLASH>$<BACKSLASH>$age<LINE FEED>"
Column 0: "data" (mapped to table column 0), Format None
Delimiter 1: <EMPTY>
 (version 20.5.2.7 (official build))
(String)
```

**Comment by BigRantLing** [comment]
@den-crane 
hi!
I tried to use KafkaEngine to consume the message from Kafka topic. The messages format is CSV, and the delimiter is `\1` (\u0001), a special character. We use it cause the message will not contain this special character. But when I execute the DDL , the '\1' will change to  `\ \1` like this:
```sql
---DDL
CREATE TABLE realtime.kafkaSource
(
    `name` String,
    `age` Int32,
    `clazz` String,
    `mates` Array(String)
)
ENGINE = Kafka
SETTINGS kafka_broker_list = 'localhost:9092',  
 kafka_topic_list = 'clickhouse_csv_hehe_111',  
 kafka_group_name = 'clickhouse_csv_787_group',  
 kafka_format = 'CSV',   
format_csv_delimiter = '\1',   
kafka_num_consumers = 1,   
kafka_skip_broken_messages = 1000;

---the message return like this
CREATE TABLE realtime.kafkaSource
(
    `name` String,
    `age` Int32,
    `clazz` String,
    `mates` Array(String)
)
ENGINE = Kafka
SETTINGS kafka_broker_list = 'localhost:9092',   
kafka_topic_list = 'clickhouse_csv_hehe_111',   
kafka_group_name = 'clickhouse_csv_787_group',  
 kafka_format = 'CSV',   
format_csv_delimiter = '\\1',   
kafka_num_consumers = 1,   
kafka_skip_broken_messages = 1000


Received exception from server (version 20.10.3):
Code: 19. DB::Exception: Received from localhost:9000. DB::Exception: A setting's value string has to be an exactly one character long.

0 rows in set. Elapsed: 0.003 sec.
```
When I use `\0` , everything is ok.
Could you give me some advice on how to use \1 as delimiter for CSV format.
Thanks!

**Comment by filimonov** [comment]
> @den-crane
> hi!
> I tried to use KafkaEngine to consume the message from Kafka topic. The messages format is CSV, and the delimiter is `\1` (\u0001), a special character. We use it cause the message will not contain this special character. But when I execute the DDL , the '\1' will change to `\ \1` like this:
> 
> ```sql
> ---DDL
> CREATE TABLE realtime.kafkaSource
> (
>     `name` String,
>     `age` Int32,
>     `clazz` String,
>     `mates` Array(String)
> )
> ENGINE = Kafka
> SETTINGS kafka_broker_list = 'localhost:9092',  
>  kafka_topic_list = 'clickhouse_csv_hehe_111',  
>  kafka_group_name = 'clickhouse_csv_787_group',  
>  kafka_format = 'CSV',   
> format_csv_delimiter = '\1',   
> kafka_num_consumers = 1,   
> kafka_skip_broken_messages = 1000;
> 
> ---the message return like this
> CREATE TABLE realtime.kafkaSource
> (
>     `name` String,
>     `age` Int32,
>     `clazz` String,
>     `mates` Array(String)
> )
> ENGINE = Kafka
> SETTINGS kafka_broker_list = 'localhost:9092',   
> kafka_topic_list = 'clickhouse_csv_hehe_111',   
> kafka_group_name = 'clickhouse_csv_787_group',  
>  kafka_format = 'CSV',   
> format_csv_delimiter = '\\1',   
> kafka_num_consumers = 1,   
> kafka_skip_broken_messages = 1000
> 
> 
> Received exception from server (version 20.10.3):
> Code: 19. DB::Exception: Received from localhost:9000. DB::Exception: A setting's value string has to be an exactly one character long.
> 
> 0 rows in set. Elapsed: 0.003 sec.
> ```
> 
> When I use `\0` , everything is ok.
> Could you give me some advice on how to use \1 as delimiter for CSV format.
> Thanks!

Try `format_csv_delimiter = '\x01' `

**Comment by etah000** [comment]
@den-crane when a multiple-char delimiter is used,  it is often because a one-char delimiter occurs in field values. For examle:
```
cat xx.csv
sss^hangzhous^28
dds^shanghais^30

cat xx.csv |clickhouse-client -q "insert into XC FORMAT CustomSeparated SETTINGS format_custom_escaping_rule = 'CSV', format_custom_field_delimiter = 's^'"
```
The above importing command will fail.

**Comment by den-crane** [comment]
now Clickhouse does not allow `... FORMAT.. SETTINGS ...` should be `... SETTINGS...FORMAT... `

```
cat xx.csv |clickhouse-client --input_format_parallel_parsing=1 -q "insert into XC SETTINGS format_custom_escaping_rule = 'CSV', format_custom_field_delimiter = '\$\$', format_custom_result_before_delimiter='name\$\$city\$\$age\n' FORMAT CustomSeparated"

select * from XC;
┌─name─┬─city─────┬─age─┐
│ ss   │ hangzhou │  28 │
│ dd   │ shanghai │  30 │
└──────┴──────────┴─────┘
```
