### ISSUE TITLE
Unexpected result of visitParamExtractString function

### ISSUE THREAD

**Issue by millin** [ClickHouse/ClickHouse#12753]
**Describe the bug**
Unexpected result of visitParamExtractString function when the nested object has an attribute with the same name

**How to reproduce**
ClickHouse server version 20.4.6.53

```
SELECT 
    '{"obj":{"name":"Bob"},"name":"Roger"}' AS json,
    visitParamExtractString(json, 'name') AS message

┌─json──────────────────────────────────┬─message─┐
│ {"obj":{"name":"Bob"},"name":"Roger"} │ Bob     │
└───────────────────────────────────────┴─────────┘
```

Expected the same result as JSONExtractString function
```
SELECT 
    '{"obj":{"name":"Bob"},"name":"Roger"}' AS json,
    JSONExtractString(json, 'name') AS message

┌─json──────────────────────────────────┬─message─┐
│ {"obj":{"name":"Bob"},"name":"Roger"} │ Roger   │
└───────────────────────────────────────┴─────────┘
```

**Comment by den-crane** [comment]
https://clickhouse.tech/docs/en/sql-reference/functions/json-functions/#functions-for-working-with-json

.... **If there are multiple matching fields, the first occurrence is used.** ....

**Comment by millin** [comment]
Really not a bug, expected behavior. Closed
