### ISSUE TITLE
Selecting large/wide column with ORDER BY + LIMIT

### ISSUE THREAD

**Issue by vmihailenco** [ClickHouse/ClickHouse#12757]
**Describe the situation**

Suppose I have following table and ClickHouse 20.4.7.67

```sql
CREATE TABLE test (
    project_id UInt32,
    time DateTime,
    data String, // large column with 1-5kb of data
    ... // other columns omitted for brevity
)
ENGINE = MergeTree()
PARTITION BY toDate(time)
ORDER BY (project_id, time)
```

Following query works fast thanks to optimize_read_in_order

```sql
SELECT data FROM test ORDER BY project_id LIMIT 10

Elapsed: 0.238 sec. Processed 191.30 thousand rows, 82.60 MB
```

With `optimize_read_in_order = 0` the result is slow as expected:

```
Elapsed: 5.081 sec. Processed 10.86 million rows, 4.80 GB
```

The problem is when I change `ORDER BY` to any other column the query becomes slow no matter if `optimize_read_in_order` is enabled or not

```sql
SELECT data FROM test ORDER BY time LIMIT 10

Elapsed: 4.727 sec. Processed 10.86 million rows, 4.80 GB
```

**Expected performance**

I assume that ClickHouse should be able to execute WHERE, ORDER & LIMIT before selecting any data and roughly determine which parts of wide column must be read. Then read only the part of the column instead of reading the whole column which is huge compared to other data in the table.

**Comment by vmihailenco** [comment]
As a workaround now I rewrite this query:

```sql
SELECT data FROM test ORDER BY time LIMIT 1
```

to these 2 queries
sql
```
SELECT project_id, time, id FROM test ORDER BY time LIMIT 10
SELECT data FROM test WHERE project_id = ? AND time = ? AND id = ?
```

and get significant performance boost - 5 seconds to 200ms.

I also tried this but it is not faster

```sql
SELECT data
FROM test AS t,
  (SELECT project_id, time, id FROM test ORDER BY time LIMIT 10) AS todo
WHERE t.project_id = todo.project_id AND t.time = todo.time AND t.id = todo.id
```

But it is even slower.

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/7187
