### ISSUE TITLE
Add possibility to skip merged partitions for OPTIMIZE TABLE ... FINAL

### ISSUE THREAD

**Issue by hashbash** [ClickHouse/ClickHouse#12759]
Optimizing merged partitions (1 part in partition and level > 0) usually have no sense, but takes a lot of time.

**Describe the solution you'd like**
Add special parameter to allow users to skip merged parts. For example `optimize_skip_merged_partitions`

**Describe alternatives you've considered**
Manually detect only non-merged partitions:
```
select table, partition, count()
from system.parts
where active = 1
  and level > 0
group by table, partition
having count() > 1
```

Do `optimize table ... partition 'xxx' final` for each row in result (only specific tables)

**Comment by siradjev** [comment]
shall probably use this query as workaround to list partitions to be optimized.
```
select distinct table, partition 
from system.parts
where active and 
(
  level=0 OR (table, partition) IN (
    select table, partition
    from system.parts
    where active = 1
    group by table, partition
    having count() > 1
  )
)
```
