### ISSUE TITLE
About the problem of logging in query_log when executing on cluster xxxx

### ISSUE THREAD

**Issue by gubinjie** [ClickHouse/ClickHouse#12768]
The clusterOne cluster contains 2 shards and 4 copies.
Execute alter table database.table on cluster clusterOne
When where id not in (.....), why is this sql not executed in the system.query_log of some copies?
Version number: 20.3.9.70

**Comment by abyss7** [comment]
Please, describe properly what is your cluster description? What are the "copies" - is it replicas?

If they are replicas of some ReplicatedMergeTree, then the ALTER TABLE query is executed only on the leader replica - all other replicas gets changes using another mechanism. For more details you can read this description in the source code: https://github.com/ClickHouse/ClickHouse/blob/master/src/Storages/StorageReplicatedMergeTree.cpp#L4665

To investigate current state of mutations on replicas you can query `system.replication_queue` or `system.mutations` table. For the log of already complete mutations unfortunately we don't have convenient interface.

**Comment by gubinjie** [comment]
@abyss7 
Yes, it is replicas.
sql:
alter table lndata.table1 on cluster mycluster
delete where sync_id in (select sync_id from ln.table1 where op_day >'2019-08-08') and id not in (select id from ln.table1 where op_day >'2019-08-08' order by updated_date desc limit 1 by sync_id)

Question 1. Will the leader replicas in both shards be executed?
Question 2: If I turn on query_log, will the execution record of this SQL be recorded in the system.query_log of each replicas?
