### ISSUE TITLE
Old parts aren't removed according to TTL settings

### ISSUE THREAD

**Issue by macEar** [ClickHouse/ClickHouse#12773]
* Docker image: yandex/clickhouse-server:20.5.3.27

-------------------

CREATE TABLE example with TTL settings:

```sql
CREATE TABLE test.test
(
    `TimeStamp` DateTime,
    `TimeStampMsg` String,
    `FilterName` LowCardinality(String),
    `EnvelopeSender` LowCardinality(String),
    `EnvelopeRecipients` String,
    `Subject` String,
    `filenames` String,
    `MatchedContent` String,
    `Prefix` String
)
ENGINE = MergeTree()
PARTITION BY toYYYYMM(TimeStamp)
ORDER BY TimeStamp
TTL TimeStamp + toIntervalMonth(6)
SETTINGS index_granularity = 8192
```
-------------------

There are old parts that should have been removed according to TTL settings but the are still present. 

I tried separately:

* `ALTER TABLE test.test MATERIALIZE TTL`
* `SYSTEM START TTL MERGES test.test`
* `ALTER TABLE test.test MODIFY TTL TimeStamp + toIntervalMonth(6)`
`OPTIMIZE TABLE test.test FINAL`

But nevertheless those parts aren't removed.

```sql
SELECT *
FROM system.mutations m
WHERE database = 'test'
	AND `table` = 'test'
```

|database|table                     |mutation_id|command|create_time|block_numbers.partition_id|block_numbers.number|parts_to_do_names|parts_to_do|is_done|latest_failed_part|latest_fail_time   |latest_fail_reason|
|--------|--------------------------|-----------|-------|-----------|--------------------------|--------------------|-----------------|-----------|-------|------------------|-------------------|------------------|
|test    |test                      |mutation_5554.txt|MATERIALIZE TTL|2020-07-27 07:23|[u'']                     |[u'5554']           |[]               |0          |1      |                  |0000-00-00 00:00:00|                  |
|test    |test                      |mutation_5555.txt|MATERIALIZE TTL|2020-07-27 07:51|[u'']                     |[u'5555']           |[]               |0          |1      |                  |0000-00-00 00:00:00|                  |
|test    |test                      |mutation_5556.txt|MATERIALIZE TTL|2020-07-27 08:04|[u'']                     |[u'5556']           |[]               |0          |1      |                  |0000-00-00 00:00:00|                  |
|test    |test                      |mutation_5557.txt|MATERIALIZE TTL|2020-07-27 08:05|[u'']                     |[u'5557']           |[]               |0          |1      |                  |0000-00-00 00:00:00|                  |

---------------------

Check active table parts after the abovementioned queries:

```sql
SELECT *
FROM system.parts
WHERE `database`='test'
  AND `table`='test'
  AND active
```

|partition|name                      |part_type|active|marks|rows|bytes_on_disk|data_compressed_bytes|data_uncompressed_bytes|marks_bytes|modification_time|remove_time        |refcount|min_date  |max_date  |min_time           |max_time           |partition_id|min_block_number|max_block_number|level|data_version|primary_key_bytes_in_memory|primary_key_bytes_in_memory_allocated|is_frozen|database|table  |engine   |disk_name|path                                                            |hash_of_all_files               |hash_of_uncompressed_files      |uncompressed_hash_of_compressed_files|delete_ttl_info_min|delete_ttl_info_max|move_ttl_info.expression|move_ttl_info.min|move_ttl_info.max|
|---------|--------------------------|---------|------|-----|----|-------------|---------------------|-----------------------|-----------|-----------------|-------------------|--------|----------|----------|-------------------|-------------------|------------|----------------|----------------|-----|------------|---------------------------|-------------------------------------|---------|--------|-------|---------|---------|----------------------------------------------------------------|--------------------------------|--------------------------------|-------------------------------------|-------------------|-------------------|------------------------|-----------------|-----------------|
|201903   |201903_1_3247_2800_5557   |Wide     |1     |0    |0   |5            |0                    |0                      |0          |2020-07-27 08:05 |0000-00-00 00:00:00|1       |0000-00-00|0000-00-00|0000-00-00 00:00:00|0000-00-00 00:00:00|201903      |1               |3247            |2800 |5557        |0                          |0                                    |0        |test     |test|MergeTree|default  |/var/lib/clickhouse/data/test/test/201903_1_3247_2800_5557/   |aca596725c655cf0dfd14a994ca5eae4|3c7e6558135db0da01e212ada3a60e01|e03f32352ae9f5f8208131f213564e06     |0000-00-00 00:00:00|0000-00-00 00:00:00|[]                      |[]               |[]               |
|201904   |201904_3248_5553_1873_5557|Wide     |1     |0    |0   |5            |0                    |0                      |0          |2020-07-27 08:05 |0000-00-00 00:00:00|1       |0000-00-00|0000-00-00|0000-00-00 00:00:00|0000-00-00 00:00:00|201904      |3248            |5553            |1873 |5557        |0                          |0                                    |0        |test     |test|MergeTree|default  |/var/lib/clickhouse/data/test/test/201904_3248_5553_1873_5557/|095931136a6c1d7c9661033d80372677|25053248052fe5a669e8f6d0efb932bc|e03f32352ae9f5f8208131f213564e06     |0000-00-00 00:00:00|0000-00-00 00:00:00|[]                      |[]               |[]               |

------------------

**Expected behavior**
The expired parts are removed.

**Comment by macEar** [comment]
Sorry, only parts with 0 rows remained. 
The corresponding issue already exists: https://github.com/ClickHouse/ClickHouse/issues/5491

Should we close this issue to continue on the existing one?

**Comment by alexey-milovidov** [comment]
Yes, it's a duplicate.
