### ISSUE TITLE
 Buffer has gone when importing large files.

### ISSUE THREAD

**Issue by calebeaires** [ClickHouse/ClickHouse#12975]
ClickHouse client version 20.5.2.7 (official build)
Settings: format_csv_allow_single_quotes and input_format_null_as_default

Tried to import with clickhouse-client a csv file with 1,500,000 rows. This csv file is very clean and well made. There are no estrange char or something that is not escaped.

```
Code: 27, e.displayText() = DB::Exception: Cannot parse input: expected ',' at end of stream.: 
(at row 650) Buffer has gone, cannot extract information about what has been parsed., 
Stack trace (when copying this message, always include the lines below): 
<Empty trace> (version 20.5.1.1) Code: 27 . DB::Exception: 
Cannot parse input: expected ',' at end of stream.: (at row 650) Buffer has gone, 
cannot extract information about what has been parsed.
```

**Comment by abyss7** [comment]
Can you please provide obfuscated CSV contents if possible? It will be much easier to reproduce and fix an issue.

I.e. you can just replace all the characters in strings with 'a' char, and all the digits in numbers with '1'.

**Comment by calebeaires** [comment]
This csv take 1.6 GB size with many columns. I have tried to simulate all possible mistakes I could make, but i seems very clean and well formatted.

```csv
1,12,a,a,a,a,a,a,444,a,2016-04-01,2017-02-28,201604,201702,a,2017-03-01,201703,a,a,01185702,a,123.538.166-98,a,a,a,(34) 1234-1234,,2344-24,a,a,,,2002-11-26,,15,0 a 18 year,a,345660571,2016-04-11,2013-02-28,201604,201702,a,001331071,a,21.567.123/1234-05,a,a,(34) 1234-1234,,32999-242,a,a,"name ,with comma inside,, 456, - type b",some@email.com,some@email.com,,,name/ name,,,sfsd,al,a,,,abe,,adw,ab,ada,a,2020-01-01,,12,,aa,a,00.000.072/0001-05,a,a,al,a,al,aa,a,a,abses,aa,a,a-a-a,a,2.00.00.01 - a,aa a,a
1,12,a,a,a,a,a,a,444,a,2016-04-01,2017-02-28,201604,201702,a,2017-03-01,201703,a,a,01185702,a,123.538.166-98,a,a,a,(34) 1234-1234,,2344-24,a,a,,,2002-11-26,,15,0 a 18 year,a,345660571,2016-04-11,2013-02-28,201604,201702,a,001331071,a,21.567.123/1234-05,a,a,(34) 1234-1234,,32999-242,a,a,"name ,with comma inside,, 456, - type b",some@email.com,some@email.com,,,name/ name,,,sfsd,al,a,,,abe,,adw,ab,ada,a,2020-01-01,,12,,aa,a,00.000.072/0001-05,a,a,al,a,al,aa,a,a,abses,aa,a,a-a-a,a,2.00.00.01 - a,aa a,a

```

The only part more complex on it is this one: comma inside double quotes
```csv
"name ,with comma inside,, 456, - type b"
```
For the sake of testing I have tried a different approach like TAB, some unique char like (~ ) as separator or even cleared the first (**csvclean**) CSV and even FORMAT (**csvformat**) with CSVKit = https://csvkit.readthedocs.io/. 

I even have tried to isolate a range of rows on those the error pops up. If I upload less the 260.000 rows it is ok, more than that it is not. 

Server: 30 GB Memory, 8 Cores. There is machine to run it like a charm. Tell me if you need more info.

**Comment by alexey-milovidov** [comment]
@calebeaires We have the following hypothesis:

1. When setting `format_csv_allow_single_quotes` is enabled, ClickHouse will recognize both single and double quotes. But usually CSV files have only one type of quoting (double quotes by RFC) and parsing single quotes as the beginning of the string literal may break the format.

**Comment by alexey-milovidov** [comment]
2. Maybe the issue is related to the `input_format_parallel_parsing` setting. The setting is enabled by default. You can check this hypothesis by disabling the setting.

**Comment by alexey-milovidov** [comment]
3. It argues about the `row 650`. Could you please copy-paste the contents of this row verbatim?
