### ISSUE TITLE
Add support for a positive settings constraints model (as opposed to negative)

### ISSUE THREAD

**Issue by nvartolomei** [ClickHouse/ClickHouse#13012]
Today it is possible to configure constraints for settings on user profiles (https://clickhouse.tech/docs/en/operations/settings/constraints-on-settings/).

The problem with this feature is that the number of settings a user can change is ~400. I have a use-case where I want to prevent users modifying settings except a few allowed ones, ie timeout and max_execution_speed_bytes. In order to do this I would have to first configure *~400*-2 constraints on all the other settings to mark them as readonly.

The proposal is to allow constraints to work in opposite way.

Ie defining a profile as ~

```xml
<analyst>
  <readonly>1</readonly>

  <constraints>
    <max_execution_speed_bytes>
      <min>10000</min>
      <max>500000</max>
    </max_execution_speed_bytes >
  </constraints>
</analyst>
```

would allow an analyst user to change only the `max_execution_speed_bytes` as long as it satisfies the constraints.

Alternatively

```xml
<analyst>
  <readonly>2</readonly>

  <constraints default="deny">
    <max_execution_speed_bytes>
      <min>10000</min>
      <max>500000</max>
    </max_execution_speed_bytes >
  </constraints>
</analyst>
```

**Comment by alexey-milovidov** [comment]
@vitlibar @nvartolomei 

How about to always allow to change settings within constraints?

So, negative constraints will be set up as usual
and for positive constraints you just specify `<readonly>1</readonly>`
and then specify your constraints to allow something.

**Comment by alexey-milovidov** [comment]
But it will prevent doing non-readonly queries.

**Comment by nvartolomei** [comment]
@bharatnc would you be interested by chance?

**Comment by alexey-milovidov** [comment]
#40244
