### ISSUE TITLE
Add function `DATE_TRUNC` for compatibility.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#13033]
Similar of `toStartOfInterval`, just for convenience.

**Comment by vladimir-golovchenko** [comment]
@alexey-milovidov As a sample of a function should be taken [Postgress date_trunc](https://www.postgresql.org/docs/9.1/functions-datetime.html#FUNCTIONS-DATETIME-TRUNC)?

The signature should looks like this? -
```sql
date_trunc(datepart, time_or_data, [timezone])

/*
- datepart - the name of datepart or timepart (such as, 'year', .. 'second')
- time_or_data - the date or date with time (not IntervalType)
*/
```

**Comment by alexey-milovidov** [comment]
Yes, it will be perfect.

**Comment by vladimir-golovchenko** [comment]
#13888
