### ISSUE TITLE
user `default` doesn't have enough grants for creating another user \ role \ row policy for 20.4 and 20.5

### ISSUE THREAD

**Issue by Slach** [ClickHouse/ClickHouse#13057]
**Describe the bug**
user `default` doesn't have enough grants for creating another user \ role \ row policy for 20.4 and 20.5

**How to reproduce**
I use following docker-compose.yaml
```
version: '3'

services:
  clickhouse:
    image: docker.io/yandex/clickhouse-server:latest
    ports:
      - 8123:8123
      - 8443:8443
      - 9000:9000
      - 9009:9009
```

```bash
docker-compose up -d clickhouse
docker-compose exec clickhouse clickhouse-client
```

```sql
SHOW GRANTS;
```

```
┌─GRANTS─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ GRANT SHOW, SELECT, INSERT, ALTER, CREATE, DROP, TRUNCATE, OPTIMIZE, KILL QUERY, SYSTEM, dictGet, INTROSPECTION, SOURCES ON *.* TO default │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

according to documentation https://clickhouse.tech/docs/en/sql-reference/statements/grant/#grant-privileges 
look like `default` user lost "ACCESS MANAGEMENT" grant groups in 20.4 and 20.5 version

cause
```sql
CREATE USER OR REPLACE monitoring IDENTIFIED WITH NO_PASSWORD HOST ANY SETTINGS PROFILE 'default';
```
return
```
Code: 497. DB::Exception: Received from localhost:9000. DB::Exception: default: Not enough privileges. To execute this query it's necessary to have the grant CREATE USER ON *.*.
```

* Which ClickHouse server version to use
20.5.3
20.4.7

for 20.3
all works fine
```sql
SHOW GRANTS;
```
return
```
┌─GRANTS────────────────────────────────────────┐
│ GRANT ALL ON *.* TO default WITH GRANT OPTION │
└───────────────────────────────────────────────┘
```
and
```sql
CREATE USER OR REPLACE monitoring PROFILE 'default';
```
return
```
Ok.
0 rows in set. Elapsed: 0.002 sec.
```

**Comment by qoega** [comment]
Do you have access_management enabled?
https://clickhouse.tech/docs/en/operations/access-rights/#enabling-access-control
It is done by setting  `access_management` to 1 in `users.xml`

**Comment by filimonov** [comment]
I think the bug is 'misleading exception'

**Comment by Slach** [comment]
hmm, ok, I understood,
I think exception with clarified message when we try to CREATE USER \ ROLE etc. about enabling access control will be good solution

**Comment by Slach** [comment]
@vitlibar @abyss7 @filimonov 

Also, misleading error messages for default user I get when run the following SQL queries:

```sql
SHOW USERS;
SHOW ROLES;
SELECT * FROM system.quota_usage;
```

**Comment by alexey-milovidov** [comment]
Exception message is correct but it can be more detailed.

**Comment by filimonov** [comment]
> Exception message is correct but it can be more detailed.

I think if we can't create user because of  `access_management` is disabled, we should say smth like `Can't create user because access_management is disabled` the message about 'not enough permissions is very misleading'.

**Comment by alexey-milovidov** [comment]
@vitlibar This is a small tech debt, need to fix.

**Comment by chenziliang** [comment]
Look like there are something changed ? In recent code base, I run into very similar problems.
I tried to run query by using HTTP interface without specifying any username/password. It reported `DB::Exception: default: Authentication failed: password is incorrect or there is no user with such name (version 20.12.1.1)`, but this issue doesn't exist in prior versions. 

Then i use the clickhouse-client to login without specifying any user/password neither. It worked. And then I run the following command to try to fix the HTTP issue.

```
CREATE USER default IDENTIFIED with no_password HOST ANY; 
ALTER USER default DEFAULT ROLE ALL;  
```
I then tried to issue the HTTP query again, it reported an different message like below and now clickhouse-client login as default had the same issue as well.

```
Code: 497, e.displayText() = DB::Exception: default: Not enough privileges. To execute this query it's necessary to have the grant SELECT(s) ON default.alias_cols (version 20.12.1.1)
```

**Comment by sandeep-devarapalli** [comment]
Please fix this 👍

**Comment by baltic-tea** [comment]
До сих эта ошибка встречается.

Fit this bug, please.

`ValueError: Code: 497. DB::Exception: admin: Not enough privileges. To execute this query it's necessary to have grant CREATE TABLE ON default.table. (ACCESS_DENIED) (version 22.3.5.5 (official build))`

**Comment by sagungargs15** [comment]
Still experiencing this on a new setup

```
Code: 497. DB::Exception: default: Not enough privileges. To execute this query it's necessary to have grant CREATE ROLE ON *.*. (ACCESS_DENIED) (version 22.4.2.1 (official build))
```

**Comment by den-crane** [comment]
>I tried to run query by using HTTP interface without specifying any username/password.

In this case you automatically specify `user=default/password=''`

**Comment by yugin-pro** [comment]
Установил CH для теста на vps. Делаю админа по инструкции с добавлением  access_management.
И пока такая же ситуация, ребут не помогает
Code: 497. DB::Exception: default: Not enough privileges. To execute this query it's necessary to have grant SHOW, SELECT, INSERT, ALTER, CREATE, DROP, UNDROP TABLE, TRUNCATE, OPTIMIZE, BACKUP, KILL QUERY, KILL TRANSACTION, MOVE PARTITION BETWEEN SHARDS, ACCESS MANAGEMENT, NAMED COLLECTION CONTROL, SYSTEM, dictGet, INTROSPECTION, SOURCES ON *.* WITH GRANT OPTION. (ACCESS_DENIED) (version 23.4.2.11 (official build))

**Comment by Slach** [comment]
@FedericoCeratto please read https://github.com/ClickHouse/ClickHouse/issues/13057#issuecomment-665670166

**Comment by movy** [comment]
The misleading `default: Not enough privileges.` message is still there. Setting `access_management` to 1 in `users.xml` for sure helps, but it requires a redundant round trip to google-github for most users, while a proper error message could have saved time and effort on this chore.

**Comment by PedroXT** [comment]
I use 23.3.14.78 and this error still exists

**Comment by alexey-milovidov** [comment]
The default has changed in 23.11.

**Comment by Slach** [comment]
for work GRANT ALL
users.d/grant_all.xml

```xml
<yandex>
    <users>
        <default>
            <access_management>1</access_management>
            <named_collection_control>1</named_collection_control>
            <show_named_collections>1</show_named_collections>
            <show_named_collections_secrets>1</show_named_collections_secrets>
        </default>
    </users>
</yandex>

```
