### ISSUE TITLE
Clickhouse incorrectly returning zero counts, when data does exist

### ISSUE THREAD

**Issue by veqryn** [ClickHouse/ClickHouse#13060]
**Describe the bug**
Clickhouse is returning zero results when data does exist for the query.
When we change the dates around slightly, data is returned, including data for the dates that previously said it had no rows for.

**How to reproduce**
Clickhouse server version 20.5.2.7
Clickhouse clients tried: dbeaver and clickhouse-go both gave the same results.

The first query successfully returns results:
```sql
select eventday, count(*) from mytable
where toYYYYMM(eventday) = 202007
  AND user_id = 742522
  AND eventday >= '2020-07-01'
  AND eventday <= '2020-07-25'
group by eventday
order by eventday;
```
Results:
```
2020-07-01	8180782
2020-07-02	8654577
2020-07-03	8165184
2020-07-04	7315179
2020-07-05	8423453
2020-07-06	6658727
...etc...
```

The second query says there are no results / no rows:
```sql
select eventday, count(*) from mytable
where toYYYYMM(eventday) = 202007
  AND user_id = 742522
  AND eventday >= '2020-07-03'
  AND eventday <= '2020-07-25'
group by eventday
order by eventday;
```

The only change was that `eventday >= '2020-07-03'`.
You can see from the results above, that we do have data on every day.
This results are the same every time I run the two queries. We have paused all data ingestion while for a bit while we investigate this, so the counts are not changing either.

Things that don't change the zero-row result:
* Changing the dates to anything from 2020-07-02 to 2020-07-25.
* Changing to a different user_id.
* Using `toYYYYMM(eventday) >= 202007 AND toYYYYMM(eventday) <= 202007` instead of `toYYYYMM(eventday) = 202007`

Things that do change the result, and give the correct results:
* Removing the `user_id = 742522` filter.
* Removing the `toYYYMM(eventday) = 202007` filter.
* Remove either or both of the eventday filters (`eventday >= '2020-07-03' AND eventday <= '2020-07-25'`).
* Change the dates on the eventday filters to be outside of July, or the include the 1st of July (such as `eventday <= '2020-08-25'`), even though the `toYYYYMM(eventday) = 202007` means the results would be the same.
* Change the order by of the table to have user_id in front: `(user_id, eventday, eventhour, eventminute, sipHash64(toaddress), integrationkey)`

Here is my create table statement:
```sql
CREATE TABLE IF NOT EXISTS mytable_local (
    created          DateTime
    eventday         Date
    eventhour        DateTime
    eventminute      DateTime
    user_id          UInt32
    toaddress        String
    integrationkey   String
    -- bunch of other fields
)
    ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/mydb.mytable', '{replica}')
    PARTITION BY toYYYYMM(eventday)
    ORDER BY (eventday, eventhour, eventminute, user_id, sipHash64(toaddress), integrationkey)
    TTL eventday TO VOLUME 'fast', eventday + toIntervalDay(93) TO VOLUME 'slow', eventday + toIntervalDay(732) DELETE
    SAMPLE BY sipHash64(toaddress);

CREATE TABLE IF NOT EXISTS mytable AS mytable_local ENGINE = Distributed(mycluster, mydb, mytable_local, rand());
```

**Expected behavior**
The first query clearly shows that data exists (and it does, as I put in data for every day), so I expect the second query to return those counts.

**Error message and/or stacktrace**
No error messages were returned by the dbeaver client or the golang driver.
I have a colleague confirm he was seeing the same thing from his computer, and he was using the clickhouse client docker container.

**Comment by abyss7** [comment]
Thank you for your report!

Can you please provide the full results of both queries run over `mytable_local` - separately for 5-10 hosts of your cluster.

**Comment by filimonov** [comment]
Reproduces:
```
CREATE TABLE IF NOT EXISTS mytable_local (
    created          DateTime,
    eventday         Date,
    eventhour        DateTime,
    eventminute      DateTime,
    user_id          UInt32,
    toaddress        String,
    integrationkey   String
)
ENGINE = MergeTree()
PARTITION BY toYYYYMM(eventday)
ORDER BY (eventday, eventhour, eventminute, user_id, sipHash64(toaddress), integrationkey)
SAMPLE BY sipHash64(toaddress);


INSERT INTO mytable_local
SELECT 
toDateTime('2020-06-01 00:00:00') + interval number minute as created,
toDate(created) as eventday,
toStartOfHour(created) as eventhour,
toStartOfMinute(created) as eventminute,
if(rand()%100 > 50, 742522, rand()) as user_id,
'' as toaddress,
'' as integrationkey
FROM numbers(100000);


-- this works 

select eventday, count(*) from mytable
where toYYYYMM(eventday) = 202007
  AND user_id = 742522
  AND eventday >= '2020-07-01'
  AND eventday <= '2020-07-25'
group by eventday
order by eventday;


-- this return empty result 

select eventday, count(*) from mytable
where toYYYYMM(eventday) = 202007
  AND user_id = 742522
  AND eventday >= '2020-07-03'
  AND eventday <= '2020-07-25'
group by eventday
order by eventday;

```

**Comment by veqryn** [comment]
I don't have access to the individual clickhouse hosts, so I'll just run it once against local and it will give me a random one.

For the sake of brevity, I've edited the dates, as it gives the same problem.
Query with first of month:
```sql
select eventday, count(*) from mytable
where toYYYYMM(eventday) = 202007
  AND user_id = 742522
  AND eventday >= '2020-07-01'
  AND eventday <= '2020-07-04'
group by eventday
order by eventday;
```
Result:
```
2020-07-01	3161082
2020-07-02	3367218
2020-07-03	3271356
2020-07-04	3066934
```

Query without first of month:
```sql
select eventday, count(*) from mytable
where toYYYYMM(eventday) = 202007
  AND user_id = 742522
  AND eventday >= '2020-07-02'
  AND eventday <= '2020-07-04'
group by eventday
order by eventday;
```
Result:
`no counts / nothing`

Local query with first of month:
```sql
select eventday, count(*) from mytable_local
where toYYYYMM(eventday) = 202007
  AND user_id = 742522
  AND eventday >= '2020-07-01'
  AND eventday <= '2020-07-04'
group by eventday
order by eventday;
```
Result:
```
2020-07-01	262716
2020-07-02	280102
2020-07-03	272856
2020-07-04	254963
```

Local query without first of month:
```sql
select eventday, count(*) from mytable_local
where toYYYYMM(eventday) = 202007
  AND user_id = 742522
  AND eventday >= '2020-07-02'
  AND eventday <= '2020-07-04'
group by eventday
order by eventday;
```
Result:
`no counts / nothing`

**Comment by filimonov** [comment]
That seems very similar to https://github.com/ClickHouse/ClickHouse/issues/12406 

Setting higher priority to raise attention, as that reproduces, affects core functionality, and leads to silent & wrong query results.

**Comment by veqryn** [comment]
thank you!

**Comment by den-crane** [comment]
@veqryn BTW, if you add this condition `toYYYYMM(eventday) = 202007` in order to do a partition elimination because the table partitioned by YYYYMM(eventday) you actually don't need to do it. CH does partition pruning using `eventday >=` condition.

**Comment by veqryn** [comment]
@den-crane thanks!
I actually figured that out during some benchmark tests, which were the same tests that surfaced this bug. It was a bad assumption on my part, but it also isn't clear from the documentation that you shouldn't use the actual partition function for partition elimination.

**Comment by veqryn** [comment]
@filimonov which version of clickhouse `20.5.x.x` will include the patch?
