### ISSUE TITLE
Results of casting functions - toFloat32 and toFloat64 - are different

### ISSUE THREAD

**Issue by MaximStanovov** [ClickHouse/ClickHouse#13067]
Results of casting functions - toFloat32 and toFloat64 - are different

Version: 20.5.3.27

**How to reproduce**
1. Get ClickHouse server ```docker run -d --name some-clickhouse-server --ulimit nofile=262144:262144 yandex/clickhouse-server```
1. Connect via ClickHouse client ```docker run -it --rm --link some-clickhouse-server:clickhouse-server yandex/clickhouse-client --host clickhouse-server```
1.  Run query with casting int to Float32 / Float64 using toFloat32 / toFloat64 functions: 
```
SELECT
    toFloat32(79083738),
    toFloat64(79083738)

┌─toFloat32(79083738)─┬─toFloat64(79083738)─┐
│            79083736 │            79083738 │
└─────────────────────┴─────────────────────┘
```
4. Run query with casting int to Float32 / Float64 using CAST() function: 
```

SELECT
    CAST(79083738, 'Float32'),
    CAST(79083738, 'Float64')

┌─CAST(79083738, 'Float32')─┬─CAST(79083738, 'Float64')─┐
│                  79083736 │                  79083738 │
└───────────────────────────┴───────────────────────────┘
```

**Expected behavior**
Results of all casting functions are the same and equal to 79083738 (ends with 8)

**Actual behavior**
Results of casting toFloat32() is 79083736 (ends with 6), but for toFloat64() is 79083738 (ends with 8)

It also reproduces while extracting float from json
```
SELECT
    '{"xxx":79083738}' AS my_json,
    CAST(JSONExtractFloat(my_json, 'xxx'), 'Float32'), -- not ok
    CAST(JSONExtractFloat(my_json, 'xxx'), 'Float64'), -- ok
    JSONExtractFloat(my_json, 'xxx') -- ok

┌─my_json──────────┬─CAST(JSONExtractFloat('{"xxx":79083738}', 'xxx'), 'Float32')─┬─CAST(JSONExtractFloat('{"xxx":79083738}', 'xxx'), 'Float64')─┬─JSONExtractFloat('{"xxx":79083738}', 'xxx')─┐
│ {"xxx":79083738} │                                                     79083736 │                                                     79083738 │                                    79083738 │
└──────────────────┴──────────────────────────────────────────────────────────────┴──────────────────────────────────────────────────────────────┴─────────────────────────────────────────────┘
```

**Comment by alexey-milovidov** [comment]
Float32 contains 24 mantissa bits and cannot represent the number 79083738 exactly.
https://en.wikipedia.org/wiki/Single-precision_floating-point_format

**Comment by alexey-milovidov** [comment]
The behaviour is 100% correct and better implementation is impossible even theoretically.
