### ISSUE TITLE
What does the tailing number of system.query_log_N mean?

### ISSUE THREAD

**Issue by achimbab** [ClickHouse/ClickHouse#13066]
ClickHouse is an excellent OLAP database

While I'm looking for the slow queries, I found many `query_log_N` and `query_thread_log_N` tables.

```SQL

SHOW TABLES

...
│ query_log                      │
│ query_log_0                    │
│ query_log_1                    │
│ query_log_2                    │
│ query_log_3                    │
│ query_log_4                    │
│ query_thread_log               │
│ query_thread_log_0             │
│ query_thread_log_1             │
│ query_thread_log_2             │
│ query_thread_log_3             │
│ query_thread_log_4             │
...
```

I am developing a `monitoring system for slow queries` and considered to use the query_log table,

but there are other tables with the same postfix of names.

I wonder what the tailing numbers of tables mean.

Thank you.

**Comment by den-crane** [comment]
It's renamed after each upgrade which changes table's schema

**Comment by achimbab** [comment]
@den-crane 
Thank you for your answer.
