### ISSUE TITLE
Add support for Nullable columns to MySQL database engine

### ISSUE THREAD

**Issue by vzakaznikov** [ClickHouse/ClickHouse#13149]
**Use case**
MySQL database engine does not currently provide a way to support `Nullable` column types. For example, if I have a table in MySQL with `AUTO_INCREMENT` `id` column and I'd like to insert `NULL` as the value for the `id` it complains that type is not `Nullable`. The workaround is to use MySQL table engine where I can explicitly specify data type as `Nullable(Int32)` for the `id` column. Here is an example of MySQL table: 

```sql 
 CREATE TABLE my_table(
        id INT NOT NULL AUTO_INCREMENT,
        date DATE,
        name VARCHAR(100),
        secret BLOB,
        PRIMARY KEY ( id )
        );
```

**Describe the solution you'd like**
Maybe can be implemented with SETTINGS clause in CREATE DATABASE query and could work similar to `external_table_functions_use_nulls`.

**Comment by stigsb** [comment]
I believe this issue may be closed now? (MySQL database engine converts to Nullable(...)  just fine.)
