### ISSUE TITLE
CTE with JDBC table function

### ISSUE THREAD

**Issue by zhicwu** [ClickHouse/ClickHouse#13159]
It looks like CTE is not supported well when using along with JDBC table function. I tried to run below query on ClickHouse `20.5.2.7` but ended up with error message saying `DB::Exception: Missing columns: 'x' while processing query: 'concat('select ', x)', required columns: 'x', source columns: '_dummy' (version 20.5.2.7)`.
```sql
with '1' as x
select * from jdbc('some-database', concat('select ', x))
```
I'm not sure if this is expected behavior by design, but could you consider future enhancement to address this? And perhaps applies to all other table functions?

Let me explain why I need this. Usually with JDBC bridge I can run query like below:
```sql
select * from jdbc('some-database-1', 'select * from sometable')
union all
select * from jdbc('some-database-2', 'select * from sometable')
...
select * from jdbc('some-database-n', 'select * from sometable')
```
Or with query parameter to run dynamic query like this one:
```sql
-- now the inner query will be "select * from sometable where somecolumn in (1,2,3)"
select * from jdbc('some-database-1?param1=where somecolumn in (1,2,3)', 'select * from sometable {{param1}}')
union all
select * from jdbc('some-database-2?param1=where somecolumn in (1,2,3)', 'select * from sometable {{param1}}')
...
select * from jdbc('some-database-n?param1=where somecolumn in (1,2,3)', 'select * from sometable {{param1}}')
```

However, it's tedious when you want to repeat the long query with different parameters, so maybe we can try something else like:
```sql
with 'where somecolumn in (1,2,3)' as filter
select * from jdbc(concat('some-database-1?param1=', filter), 'select * from sometable {{param1}}')
...
```
Or simply
```sql
with 'where somecolumn in (1,2,3)' as filter
select * from jdbc('some-database-1', concat('select * from sometable ', filter)
...
```

Feel free to close this issue if you think it's a misusage, and please let me know if there's any alternative approach.

**Comment by amosbird** [comment]
There is no CTE in clickhouse yet. I'd like to denote the current `WITH` statement as CST (common scalar expression) and table functions are not scalars.

**Comment by amosbird** [comment]
Close because it's a misusage of WITH statement in ClickHouse. It doesn't work in postgres either.

```
with x as (select 10) select  * from generate_series(1, x);
```
