### ISSUE TITLE
Type mismatch in WHERE field IN (toUUID(const))

### ISSUE THREAD

**Issue by hohaftf** [ClickHouse/ClickHouse#13173]
**Describe the bug**
Exception when using IN condition with toUUID function and constant values

**How to reproduce**
```
create table default.test(value UUID) engine=MergeTree order by value;

select * from default.test where value in (toUUID('a40ff1f2-d875-4276-ab15-141afda9985a'));
```

**Expected behavior**
no exception

**Error message and/or stacktrace**

> 2020.07.31 17:16:17.652272 [ 69 ] {} <Error> DynamicQueryHandler: Code: 53, e.displayText() = DB::Exception: Type mismatch in IN or VALUES section. Expected: UUID. Got: UInt128, Stack trace (when copying this message, always include the lines below):
> 
> 0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x103fa390 in /usr/bin/clickhouse
> 1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x900b8ad in /usr/bin/clickhouse
> 2. ? @ 0xd524ad9 in /usr/bin/clickhouse
> 3. DB::convertFieldToType(DB::Field const&, DB::IDataType const&, DB::IDataType const*) @ 0xd521ae7 in /usr/bin/clickhouse
> 4. ? @ 0xd3c7f13 in /usr/bin/clickhouse
> 5. DB::makeExplicitSet(DB::ASTFunction const*, DB::Block const&, bool, DB::Context const&, DB::SizeLimits const&, std::__1::unordered_map<DB::PreparedSetKey, std::__1::shared_ptr<DB::Set>, DB::PreparedSetKey::Hash, std::__1::equal_to<DB::PreparedSetKey>, std::__1::allocator<std::__1::pair<DB::PreparedSetKey const, std::__1::shared_ptr<DB::Set> > > >&) @ 0xd3c8c57 in /usr/bin/clickhouse
> 6. DB::SelectQueryExpressionAnalyzer::makeSetsForIndex(std::__1::shared_ptr<DB::IAST> const&) @ 0xd3b6dd9 in /usr/bin/clickhouse
> 7. DB::ExpressionAnalysisResult::ExpressionAnalysisResult(DB::SelectQueryExpressionAnalyzer&, bool, bool, bool, std::__1::shared_ptr<DB::FilterInfo> const&, DB::Block const&) @ 0xd3b6f8e in /usr/bin/clickhouse
> 8. DB::InterpreterSelectQuery::getSampleBlockImpl() @ 0xd21ac98 in /usr/bin/clickhouse
> 9. ? @ 0xd21bd02 in /usr/bin/clickhouse
> 10. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, std::__1::shared_ptr<DB::IBlockInputStream> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0xd21ed9f in /usr/bin/clickhouse
> 11. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0xd220499 in /usr/bin/clickhouse
> 12. DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0xd3f2521 in /usr/bin/clickhouse
> 13. DB::InterpreterFactory::get(std::__1::shared_ptr<DB::IAST>&, DB::Context&, DB::QueryProcessingStage::Enum) @ 0xd18d944 in /usr/bin/clickhouse
> 14. ? @ 0xd52e7ee in /usr/bin/clickhouse
> 15. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, DB::Context&, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>) @ 0xd532700 in /usr/bin/clickhouse
> 16. DB::HTTPHandler::processQuery(Poco::Net::HTTPServerRequest&, HTMLForm&, Poco::Net::HTTPServerResponse&, DB::HTTPHandler::Output&) @ 0x90efb4c in /usr/bin/clickhouse
> 17. DB::HTTPHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&) @ 0x90f35a6 in /usr/bin/clickhouse
> 18. Poco::Net::HTTPServerConnection::run() @ 0x102aad43 in /usr/bin/clickhouse
> 19. Poco::Net::TCPServerConnection::start() @ 0x102e610b in /usr/bin/clickhouse
> 20. Poco::Net::TCPServerDispatcher::run() @ 0x102e659b in /usr/bin/clickhouse
> 21. Poco::PooledThread::run() @ 0x10494166 in /usr/bin/clickhouse
> 22. Poco::ThreadImpl::runnableEntry(void*) @ 0x1048f420 in /usr/bin/clickhouse
> 23. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
> 24. __clone @ 0xfe8dd in /usr/lib64/libc-2.17.so
>  (version 20.4.5.36 (official build))

**Additional context**
version 20.4.5.36

**Comment by CurtizJ** [comment]
Seems, that it works in 20.5.

```
create table default.test(value UUID) engine=MergeTree order by value;
insert into test values ('a40ff1f2-d875-4276-ab15-141afda9985a');

select * from default.test where value in (toUUID('a40ff1f2-d875-4276-ab15-141afda9985a'));

┌────────────────────────────────value─┐
│ a40ff1f2-d875-4276-ab15-141afda9985a │
└──────────────────────────────────────┘

select version();

┌─version()─┐
│ 20.5.3.27 │
└───────────┘

```

I will try to find what patch fixed this issue, and if it won't be too hard we could backport it to 20.4.

**Comment by CurtizJ** [comment]
Now version 20.4 is outdated and out of support.
