### ISSUE TITLE
Ошибка импорта из CSV из-за несоответствия имен заголовков

### ISSUE THREAD

**Issue by PrizmaPic** [ClickHouse/ClickHouse#13171]
После обновления до версии 20.4.1.3169 перестали работать загрузки из CSV с заголовками.
clickhouse-client -u default --password root --format_csv_delimiter="|" --query="INSERT INTO ...

Ранее проверялось только соответствие типов данных в столбцах, теперь стали сверяться и имена столбцов в CSV с именами столбцов в целевой таблице.

Работать с CSV без заголовков неудобно с точки зрения поиска возможных ошибок или изменений в их формировании.
Постоянное предварительное удаление заголовков неудобно по ряду причин.

Нужно если не постановление прежнего режима работы, то хотя бы возможность параметром отменить проверку.

**Comment by den-crane** [comment]
Ранее? Про какую версию речь?
я не вижу у вас флага input_format_with_names_use_header у вас же заголовок вставится как первая строка?

**Comment by PrizmaPic** [comment]
Пардон, была 20.4.1 а сейчас 20.5.2 revision 54435
"FORMAT CSVWithNames" - заголовок не вставляется.

**Comment by den-crane** [comment]
да странно, но input_format_with_names_use_header=0 помогает

```
create table csvWithNames( A String, B Float64) Engine= Memory;

echo -e "a,b\n1,1"|clickhouse-client -q 'insert into csvWithNames FORMAT CSVWithNames'
Code: 117. DB::Exception: Unknown field found in CSV header: 'a' at position 0
Set the 'input_format_skip_unknown_fields' parameter explicitly to ignore and proceed

echo -e "a,b\n1,1"|clickhouse-client -q 'insert into csvWithNames FORMAT CSVWithNames' --input_format_with_names_use_header=0

select * from csvWithNames
┌─A─┬─B─┐
│ 1 │ 1 │
└───┴───┘
```

**Comment by PrizmaPic** [comment]
Отлично, спасибо!
Тогда если нет плана возвращать прежнее поведение, таск можно закрывать.

**Comment by den-crane** [comment]
Оставим пока issue, это похоже на случайно изменение

**Comment by alexey-milovidov** [comment]
Включение `input_format_with_names_use_header` по-умолчанию есть в 20.5 и отмечено в changelog как пункт, на который следует обратить внимание: https://github.com/ClickHouse/ClickHouse/blob/master/CHANGELOG.md#backward-incompatible-change

В версии 20.4 настройка, по прежнему, выставлена в ноль:
```
server/clickhouse-20.4.6 local --query "SELECT name, value FROM system.settings WHERE name = 'input_format_with_names_use_header'"
input_format_with_names_use_header      0
```
