### ISSUE TITLE
the equal function like MySQL's group_concat

### ISSUE THREAD

**Issue by vkingnew** [ClickHouse/ClickHouse#13195]
is there a function as MySQL's group_concat?
the example show in MySQL:
>create table kpi(emp_no varchar(8),performance varchar(32),month varchar(32));
>insert into kpi values (10,'A','2020-01'),(10,'A','2020-02'),(10,'C','2020-03'),(10,'B','2020-04'),(10,'A','2020-05'),(10,'A','2020-06');
>insert into kpi values (20,'A','2020-01'),(20,'B','2020-02'),(20,'C','2020-03'),(20,'C','2020-04'),(20,'A','2020-05'),(20,'D','2020-06'); 
>insert into kpi values (30,'C','2020-03'),(30,'C','2020-04'),(30,'B','2020-05'),(30,'B','2020-06');

>mysql> select emp_no,group_concat(performance order by month separator '-') kpi_list,group_concat(distinct performance order by month separator '-') kpi_uniq,group_concat(distinct performance order by month desc separator '-') kpi_uniq_desc from kpi group by emp_no;  
>+--------+-------------+----------+---------------+
| emp_no | kpi_list    | kpi_uniq | kpi_uniq_desc |
+--------+-------------+----------+---------------+
| 10     | A-A-C-B-A-A | A-C-B    | B-C-A         |
| 20     | A-B-C-C-A-D | A-B-C-D  | D-C-B-A       |
| 30     | C-C-B-B     | C-B      | B-C           |
+--------+-------------+----------+---------------+
3 rows in set (0.00 sec)

By the way i want to get each user's the count of performance level ,for examle emp_no=10 have A 4 times

**Comment by alexey-milovidov** [comment]
There is `groupArray` aggregate function, it returns array of all values.
There is `groupUniqArray` that returns array of all distinct values.

And you can convert array to string with `arrayStringConcat` function.

**Comment by vkingnew** [comment]
ok by your tips,i get it.
>SELECT 
    emp_no,
    groupArray(performance) AS kpi_asc,
    arrayStringConcat(kpi_asc, '-') AS kpi_list,
    groupUniqArray(performance) AS kpi_uniq,
    countEqual(kpi_asc, 'A') AS A_cnt,
    countEqual(kpi_asc, 'B') AS B_cnt,
    countEqual(kpi_asc, 'C') AS C_cnt,
    countEqual(kpi_asc, 'D') AS D_cnt
FROM kpi
GROUP BY emp_no
ORDER BY emp_no ASC
>┌─emp_no─┬─kpi_asc───────────────────┬─kpi_list────┬─kpi_uniq──────────┬─A_cnt─┬─B_cnt─┬─C_cnt─┬─D_cnt─┐
│ 10     │ ['A','A','C','B','A','A'] │ A-A-C-B-A-A │ ['B','A','C']     │     4 │     1 │     1 │     0 │
│ 20     │ ['A','B','C','C','A','D'] │ A-B-C-C-A-D │ ['B','A','D','C'] │     2 │     1 │     2 │     1 │
│ 30     │ ['C','C','B','B']         │ C-C-B-B     │ ['B','C']         │     0 │     2 │     2 │     0 │
└────────┴───────────────────────────┴─────────────┴───────────────────┴───────┴───────┴───────┴───────┘

3 rows in set. Elapsed: 0.004 sec.

**Comment by fzhedu** [comment]
`groupUniqArray ` and `grougArray ` just accept only only expression, but `group_concat(x,x,x...)` could accept more expressions and order by. So how Clickhouse compeletly support `group_concat(x,x,x...)` of mysql?
