### ISSUE TITLE
Datetime64 millisecond integers in HTTP protocol do not parse correctly

### ISSUE THREAD

**Issue by mcgrawia** [ClickHouse/ClickHouse#13194]
**Describe the bug**
When using the HTTP protocol with DateTime64 types, numerical timestamps in milliseconds do not parse correctly. This is an issue when using the Clickhouse JDBC driver with Avro Kafka records because the timestamps are integers. 

**How to reproduce**
I'm using the following CH version: yandex/clickhouse-server:20.4.5.36

Create a sample table with: 
```sql
create table tst(ts DateTime64(3)) engine TinyLog();
```

Attempt to insert millisecond timestamp into the column:
```bash
echo "1596215121682" | http -v :8123 query=="insert into tst format TSV"
```

Error:
```bash
Code: 27, e.displayText() = DB::Exception: Cannot parse input: expected '\n' before: '682\n': (at row 1)

Row 1:
Column 0,   name: ts, type: DateTime64(3), parsed text: "1596215121"
ERROR: garbage after DateTime64(3): "682<LINE FEED>"

 (version 20.4.5.36 (official build))
```

Oddly, specifying a raw query, this works:
```bash
echo 'insert into tst values(1596215121682)' | curl 'http://localhost:8123/' --data-binary @-
```
Result:
```bash
SELECT *
FROM tst

┌──────────────────────ts─┐
│ 2020-07-31 17:05:21.682 │
└─────────────────────────┘
```

**Expected behavior**
I expect to be able to insert integer millisecond timestamps using the HTTP batch insert protocol. 

Again, this issue is preventing us from using the Clickhouse JDBC driver because it fails to parse our Avro records from Kafka.

Appreciate the help!

**Comment by den-crane** [comment]
CH expects 1596215121.682

```
create table tst(ts DateTime64(3)) engine TinyLog();

insert into tst format TSV 1596215121682;
DB::Exception: Cannot parse input: expected '\n' before: '682;': (at row 1)

insert into tst format TSV 1596215121.682
Ok.

insert into tst format CSV '1596215121.682'
Ok.

insert into tst format CSV 1596215121.682
Ok.

SELECT *
FROM tst

┌──────────────────────ts─┐
│ 2020-07-31 17:05:21.682 │
│ 2020-07-31 17:05:21.682 │
│ 2020-07-31 17:05:21.682 │
└─────────────────────────┘


```

**Comment by mcgrawia** [comment]
hi @den-crane , thank you for the fast response! Glad to know it's not just the HTTP protocol. 

Do you know if there is a way others have gotten around the lack of integer parsing? Without it, it seems like almost all of the open source Kafka ecosystem tools will break. For how integrated Clickhouse is with Kafka, I am surprised this hasn't been an issue before. 

Would it be possible to add a feature request to allow this to work so we can use Avro timestamps with Clickhouse?

**Comment by alexey-milovidov** [comment]
CC @Enmk

**Comment by den-crane** [comment]
@mcgrawia you just need to describe kafka table column as Int64 and use fromUnixTimestamp64Milli in kafka MV
```

SELECT fromUnixTimestamp64Milli(toInt64(1596215121682))

┌─fromUnixTimestamp64Milli(toInt64(1596215121682))─┐
│                          2020-07-31 17:05:21.682 │
└──────────────────────────────────────────────────┘
```

**Comment by den-crane** [comment]
@alexey-milovidov what do you expect from @Enmk ? 

>insert into tst format TSV 1596215121682;

this should work or not?

>insert into tst values(1596215121682)

this should work or not?

**Comment by mcgrawia** [comment]
thank you @den-crane, that makes sense. We were actually able to find a work-around specific to the Kafka Connect use case. If anyone else stumbles on this issue, you can use the [Kafka Connect Timestamp Converter](https://docs.confluent.io/current/connect/transforms/timestampconverter.html) to transform the Avro longs into a string representation that Clickhouse can understand.

**Comment by alexey-milovidov** [comment]
DateTime64 expects unix timestamp with fractional number of seconds in decimal format.

If large integer is passed as you have proposed, overflow will occur. Attempt to distinguish these cases will impose performance penalty.

It can be implemented in a tricky way (only assuming 10 digit before point) with small or neglible performance penalty.

**Comment by alexey-milovidov** [comment]
> @alexey-milovidov what do you expect from @Enmk?

@Enmk is the developer of DateTime64, he can have thoughts on this (but did not answer).

**Comment by phamtai97** [comment]
Hi @den-crane, @alexey-milovidov
I also have these issues. I wonder about this random error. The table with the type field is Datatime64, the row I inserted successfully, no row. That makes users very uncomfortable. If it can report errors from the beginning it will help users find other ways to use them.
Have you got the solution to this problem yet, and how to fix it now?

**Comment by den-crane** [comment]
@phamtai97 

CH expects 1576225796.097 as Decimal because DateTime64 based on Decimal

INSERT INTO  log   VALUES (1, 1576225796.097);

**Comment by alexey-milovidov** [comment]
@den-crane It works in inconsistent fashion:

```
milovidov-desktop :) CREATE TEMPORARY TABLE t (x DateTime64(3))

CREATE TEMPORARY TABLE t
(
    `x` DateTime64(3)
)

Query id: bd64042b-f59a-4239-98eb-17cdbb8c650d

Ok.

0 rows in set. Elapsed: 0.001 sec. 

milovidov-desktop :) INSERT INTO t VALUES (1111111111222)

INSERT INTO t VALUES

Query id: 40a50c67-0f3a-4a0e-8fe1-e3b703dc1998

Ok.

1 rows in set. Elapsed: 0.004 sec. 

milovidov-desktop :) SELECT * FROM t

SELECT *
FROM t

Query id: c535f2d4-f391-440f-83ec-a74830b369fa

┌───────────────────────x─┐
│ 2005-03-18 04:58:31.222 │
└─────────────────────────┘

1 rows in set. Elapsed: 0.002 sec. 

milovidov-desktop :) SELECT toDateTime(1111111111)

SELECT toDateTime(1111111111)

Query id: c923fc01-4586-414a-a379-a037e19d677b

┌─toDateTime(1111111111)─┐
│    2005-03-18 04:58:31 │
└────────────────────────┘

1 rows in set. Elapsed: 0.002 sec. 

milovidov-desktop :) SELECT toDateTime64(1111111111.222, 3)

SELECT toDateTime64(1111111111.222, 3)

Query id: 8dc55551-5eb6-4b41-949a-868789f74642

┌─toDateTime64(1111111111.222, 3)─┐
│         2005-03-18 04:58:31.000 │
└─────────────────────────────────┘

1 rows in set. Elapsed: 0.001 sec. 

milovidov-desktop :) SELECT toDateTime64(1111111111222, 3)

SELECT toDateTime64(1111111111222, 3)

Query id: 4976ec80-0482-4c1e-b213-9d90daf17b05

┌─toDateTime64(1111111111222, 3)─┐
│        2106-02-07 09:28:15.000 │
└────────────────────────────────┘

1 rows in set. Elapsed: 0.002 sec. 

milovidov-desktop :) SELECT toDateTime64('1111111111222', 3)

SELECT toDateTime64('1111111111222', 3)

Query id: 3a084cc8-c013-4160-8d6a-5bfd265a1f2e


0 rows in set. Elapsed: 0.018 sec. 

Received exception from server (version 21.3.1):
Code: 6. DB::Exception: Received from localhost:9000. DB::Exception: Cannot parse string '1111111111222' as DateTime64(3): syntax error at position 10 (parsed just '1111111111'): While processing toDateTime64('1111111111222', 3).
```

**Comment by den-crane** [comment]
@alexey-milovidov 

I don't see consistency.

```
CREATE TEMPORARY TABLE t (x DateTime64(3));
INSERT INTO t VALUES (1111111111222);
ok

INSERT INTO t Format TSV 1111111111222;
Error on processing query 'INSERT INTO t Format TSV 1111111111222;':
Code: 27, e.displayText() = DB::ParsingException: Cannot parse input: expected '\n' before: '222;': (at row 1)

```

**Comment by alexey-milovidov** [comment]
@den-crane Yes, it is inconsistent:

> It works in inconsistent fashion
