### ISSUE TITLE
Assertion "Cannot read out of marks range"

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#13248]
See https://clickhouse-test-reports.s3.yandex.net/13238/6f690b7c0da14335dc28ae29adfc0b40038f6fe6/fuzzer/fuzzer.log#fail1

**Comment by akuzm** [comment]
```

SELECT 
    toUInt32(x),
    y,
    z
FROM pk
WHERE (x >= toDateTime(1023)) AND (x <= toDateTime(7))
```

https://clickhouse-test-reports.s3.yandex.net/13283/45b57f2df588154b6f766efe28bdfd19985eb6f3/fuzzer/fuzzer.log#fail1

**Comment by alexey-milovidov** [comment]
This simple query works on 19.14 but segfaults on 20.3..20.8:

`SELECT count() FROM test.hits WHERE (CounterID <= 1025) AND (CounterID > 107931)`

**Comment by amosbird** [comment]
> This simple query works on 19.14 but segfaults on 20.3..20.8:
> 
> `SELECT count() FROM test.hits WHERE (CounterID <= 1025) AND (CounterID > 107931)`

I just checked locally and found that it's still related to https://github.com/ClickHouse/ClickHouse/pull/12277
