### ISSUE TITLE
Ошибка при создании пользователя командой CREATE USER

### ISSUE THREAD

**Issue by handgunman** [ClickHouse/ClickHouse#13256]
ClickHouse server version 20.5.4 revision 54435

<access_management>1</access_management>

Code: 514. DB::Exception: Received from localhost:9000. DB::Exception: Not found a storage to insert user

**Comment by handgunman** [comment]
в тракеровке вроде ничего информативного
Code: 514. DB::Exception: Received from 127.0.0.1:9000. DB::Exception: Not found a storage to insert user `okraina`. Stack trace:

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x11b9acc0 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x9f3e2cd in /usr/bin/clickhouse
2. ? @ 0xe508201 in /usr/bin/clickhouse
3. ? @ 0xe5000c8 in /usr/bin/clickhouse
4. DB::IAccessStorage::insert(std::__1::vector<std::__1::shared_ptr<DB::IAccessEntity const>, std::__1::allocator<std::__1::shared_ptr<DB::IAccessEntity const> > > const&) @ 0xe500e9f in /usr/bin/clickhouse
5. DB::InterpreterCreateUserQuery::execute() @ 0xe9cd24d in /usr/bin/clickhouse
6. ? @ 0xed3c7ed in /usr/bin/clickhouse
7. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool) @ 0xed3fe2a in /usr/bin/clickhouse
8. DB::TCPHandler::runImpl() @ 0xf36443c in /usr/bin/clickhouse
9. DB::TCPHandler::run() @ 0xf365190 in /usr/bin/clickhouse
10. Poco::Net::TCPServerConnection::start() @ 0x11ab8aeb in /usr/bin/clickhouse
11. Poco::Net::TCPServerDispatcher::run() @ 0x11ab8f7b in /usr/bin/clickhouse
12. Poco::PooledThread::run() @ 0x11c37aa6 in /usr/bin/clickhouse
13. Poco::ThreadImpl::runnableEntry(void*) @ 0x11c32ea0 in /usr/bin/clickhouse
14. start_thread @ 0x76db in /lib/x86_64-linux-gnu/libpthread-2.27.so
15. clone @ 0x121a3f in /lib/x86_64-linux-gnu/libc-2.27.so

**Comment by den-crane** [comment]
Check that you have configured  access_control_path in config.xml

```
    <!-- Path to folder where users and roles created by SQL commands are stored. -->
    <access_control_path>/var/lib/clickhouse/access/</access_control_path>
```

**Comment by handgunman** [comment]
Спасибо! Его не было в старом конфиге, который я использовал, потопу проглядел.

**Comment by draev** [comment]
> Check that you have configured access_control_path in config.xml
> 
> ```
>     
>     <access_control_path>/var/lib/clickhouse/access/</access_control_path>
> ```

А Сервер нужно перезагружать после изменения конфига ?

**Comment by alexey-milovidov** [comment]
Скорее всего да.
