### ISSUE TITLE
joinGet result invalid.

### ISSUE THREAD

**Issue by templarzq** [ClickHouse/ClickHouse#13327]
**Describe the bug**
clickhouse version: 20.6.1.4066

* Queries to run that lead to unexpected result
 select joinGet('db.T2','id',tid) as nodeId,count(*) from db.T1 where tid='1000' group by nodeId
（db.T2 use storageJoin engine, join type parameter: left)
result:
nodeId  count(*)
0	593
43	70

**Expected behavior**
expected result:
nodeId  count(*)
43	663

**Comment by templarzq** [comment]
db.T2  column id type: int32

**Comment by den-crane** [comment]
@templarzq  Do you have reproducible example? 

Do you expect that joinGet have to return something instead of 0 in case of `left` ?

**Comment by templarzq** [comment]
it works before version 20.5 (include 20.5.1.1)

**Comment by den-crane** [comment]
OK. And how to reproduce it?

@templarzq 
```

create table T1 Engine=MergeTree order by tuple() as select intDiv(number,1000) tid from numbers(1000000);
create table T2 Engine=Join(any, left,tid) as select number%1000+5 id, intDiv(number,1000)+100 tid from numbers(1000000);

select joinGet('db.T2','id',tid) as nodeId,count() from T1 where tid='333' group by nodeId
┌─nodeId─┬─count()─┐
│      5 │    1000 │
└────────┴─────────┘
```

**Comment by templarzq** [comment]
create table xxx on cluster bench_cluster(
xxx
)
ENGINE =Join(ANY, LEFT, Id)

**Comment by templarzq** [comment]
maybe the option "on cluster xxx"  lead to this result?

**Comment by den-crane** [comment]
> maybe the option "on cluster xxx" lead to this result?

I don't see how. 
Please provide reproducible example.

**Comment by templarzq** [comment]
create table T1 on cluster bench_cluster Engine=MergeTree order by tuple() as select intDiv(number,1000) tid from numbers(1000000);
create table T2 on cluster bench_cluster(
  id UInt32,
  tid UInt64
) Engine=Join(any, left,tid);
insert into T2 select number%1000+5 id, intDiv(number,1000)+100 tid from numbers(1000000);
create table T3 on cluster bench_cluster as T1   ENGINE  = Distributed(bench_cluster, default,  T1, sipHash64(tid)); 


select joinGet('default.T2','id',tid) as nodeId,count(*) from T3 where tid='333' group by nodeId

**Comment by templarzq** [comment]
bench_cluster have more than 1 node.

**Comment by den-crane** [comment]
It's because Join is empty on shards (it's not replicated engine). And joinGet works on shards against empty table.
You can fill T2 at all nodes with the same data or perform joinGet at initiator using `from()`.

```SQL
create table T1 on cluster segmented (tid UInt64) Engine=MergeTree order by tuple();
create table T3 on cluster segmented as T1 ENGINE = Distributed(segmented, currentDatabase(), T1, sipHash64(tid));

-- data sharded on cluster
insert into T3  select intDiv(number,1000) tid from numbers(1000000);

create table T2 on cluster segmented(id UInt32, tid UInt64) Engine=Join(any, left,tid);

-- data only at current node in Engine=Join
insert into T2 select number%1000+5 id, intDiv(number,1000)+100 tid from numbers(1000000);

-- WRONG result
SELECT
    joinGet('default.T2', 'id', tid) AS nodeId,
    count(*)
FROM T3
WHERE tid = 333
GROUP BY nodeId

┌─nodeId─┬─count()─┐
│      0 │    1000 │
└────────┴─────────┘

-- RIGTH result - joinGet executed at current node only
SELECT
    joinGet('default.T2', 'id', tid) AS nodeId,
    count(*)
FROM
(
    SELECT tid
    FROM T3
    WHERE tid = 333
)
GROUP BY nodeId

┌─nodeId─┬─count()─┐
│      5 │    1000 │
└────────┴─────────┘

--  RIGTH result - joinGet executed at all nodes but it has data at all nodes as well
-- execute at all nodes
node2: insert into T2 select number%1000+5 id, intDiv(number,1000)+100 tid from numbers(1000000);
node3: insert into T2 select number%1000+5 id, intDiv(number,1000)+100 tid from numbers(1000000);
node4: insert into T2 select number%1000+5 id, intDiv(number,1000)+100 tid from numbers(1000000);
node5: insert into T2 select number%1000+5 id, intDiv(number,1000)+100 tid from numbers(1000000);

SELECT
    joinGet('default.T2', 'id', tid) AS nodeId,
    count(*)
FROM T3
WHERE tid = 333
GROUP BY nodeId

┌─nodeId─┬─count()─┐
│      5 │    1000 │
└────────┴─────────┘

```

ClickHouse server version 19.13.7

**Comment by templarzq** [comment]
ok,thanks.
