### ISSUE TITLE
20.3 two-level aggregation is not compatible with 20.4+

### ISSUE THREAD

**Issue by SaltTan** [ClickHouse/ClickHouse#13331]
When I run a query across nodes with different 20.x versions, the initiator does not fully aggregate the results if group_by_two_level is enabled.

**How to reproduce**
```
SELECT
    event_date,
    type,
    count()
FROM remote('ch_20.3,ch_20.4_or_20.5', system, query_log)
WHERE event_date = today()
GROUP BY
    event_date,
    type
ORDER BY type ASC
SETTINGS group_by_two_level_threshold_bytes = 1, group_by_two_level_threshold = 1

┌─event_date─┬─type────────┬─count()─┐
│ 2020-08-04 │ QueryStart  │   74000 │
│ 2020-08-04 │ QueryStart  │   75701 │
│ 2020-08-04 │ QueryFinish │   74000 │
│ 2020-08-04 │ QueryFinish │   75700 │
└────────────┴─────────────┴─────────┘

SELECT
    event_date,
    type,
    count()
FROM remote('ch_20.3,ch_20.4_or_20.5', system, query_log)
WHERE event_date = today()
GROUP BY
    event_date,
    type
ORDER BY type ASC
SETTINGS group_by_two_level_threshold_bytes = 1, group_by_two_level_threshold = 0

┌─event_date─┬─type────────┬─count()─┐
│ 2020-08-04 │ QueryStart  │  149708 │
│ 2020-08-04 │ QueryFinish │  149707 │
└────────────┴─────────────┴─────────┘
```

**Comment by alexey-milovidov** [comment]
It can happen if you don't use the latest patch release for 20.3, 20.4 or 20.5.

**Comment by alexey-milovidov** [comment]
From changelog:

> Fix incompatibility of two-level aggregation between versions 20.1 and earlier. This incompatibility happens when different versions of ClickHouse are used on initiator node and remote nodes and the size of GROUP BY result is large and aggregation is performed by a single String field. It leads to several unmerged rows for a single key in result. #10952 (alexey-milovidov).

**Comment by SaltTan** [comment]
I use 20.3.13.127, I think it's recent enough.
#10952 was backported to 20.3.10

**Comment by SaltTan** [comment]
Also the issue does not reproduce when I group by a single column, only when I group by two columns. And they don't have to be String, I found this problem when grouping by a Date and an Int32.
