### ISSUE TITLE
DB::Exception: Too many parts (600). Merges are processing significantly slower than inserts

### ISSUE THREAD

**Issue by mjodeh** [ClickHouse/ClickHouse#13360]
we keep getting this exception `Merges are processing significantly slower than inserts`, some insertions have small data (less than 10 rows), others have more than 1k rows.

The insertion rate is 1 insertion per database every 10 seconds, we have 80 databases and every database has a single table in which the insertions are done.
In 1 second there might be more insertions on the server but the above restriction is kept. Also the tables have a lot of nullable columns. We are not using SSDs.

1- How to avoid this exception? should the insertion rate be 1 insertion request per second per server or per database? I tried https://github.com/ClickHouse/ClickHouse/issues/1510#issuecomment-345690572 and didn't solve the problem

2- Also the clickhouse brings the node down in a random manner (eats 100%cpu for a long time, 24 cores!) on some queries during the insertions, how this should be avoided?

3- Also I tried optimize table with/without final and checked system.merges table and the optimize had no effect on the merges performance at all! this is expected behavior?

4- Also we are facing this issue on a cluster of 4 nodes (2 sharded, 2 replicated), 3 instances of zookeeper (on different servers on the same network), with a `database read only error`

Any help will be appreciated!

**Comment by qoega** [comment]
Which version do you use?

**Comment by mjodeh** [comment]
20.3.8.53

**Comment by den-crane** [comment]
check this comment https://github.com/ClickHouse/ClickHouse/issues/3174#issuecomment-423435071

How many columns in your tables?
How many merges do you see simultaneously usually ? `select count() from system.merges`  ?

**Comment by mjodeh** [comment]
thanks @den-crane 
the columns number varies from 20 column to 837 columns and only 3 columns in every table are not nullables the rest are nullables.

`select count() from system.merges` is always `16` **this count does not change after executing `optimize table` with or without `final` keyword also the progress does not change!**
`select database, progress, num_parts from system.merges` shows repeated dbs (2 or 3 rows), and it's not only 1 db it keeps changing which is normal I think

I use insertion in both Distributed and local merge tree tables, and the behavior is the same on both single node or on 4 node cluster

I checked https://github.com/ClickHouse/ClickHouse/issues/3174#issuecomment-423435071 and got the feeling that the insertions should be 1 insertion per server not per database or per table, am I right?

**Comment by mjodeh** [comment]
I stopped the insertions for 3 hours, and once I started it again it worked fine for 45 minutes then the exceptions were there again and the exceptions are not for all dbs for some of them, I tried to connect them to the column's count and had no connection, the db which had 837 columns did not throw the exception

**Comment by den-crane** [comment]
>1 insertion per server not per database

yes. But this number 1 part / per second / per server is highly approximate value. 
It depends on many parameters, number of columns, partitioning schema, volume of data in bytes, disks.

`optimize table` makes everything worse. It causes unplanned merges and overloads I/O and CPU by excessive merges.

What table persists in  system.merges ? What is the insertion rate into this table?

Enable distributed_directory_monitor_batch_inserts for insertion into Distributed tables.
_distributed_directory_monitor_batch_inserts "Should StorageDistributed DirectoryMonitors try to batch individual inserts into bigger ones."_

**Comment by mjodeh** [comment]
Thanks for reply @den-crane 

> What table persists in system.merges ? What is the insertion rate into this table?  

There is no single table which persists in system.merges since every db has only 1 table and the insertion rate is 1 insertion per db, system.merges keeps changing but always shows 16 dbs

> It depends on many parameters, number of columns, partitioning schema, volume of data in bytes, disks.  

Is there any formula or estimation to be used?

**Comment by mjodeh** [comment]
when I execute `select databse, progress, elapsed, num_parts from system.merges`  I see the same database in multiple rows, is it ok?
  |   database   |   progress   | elapsed | num_parts |
 | database1      │  0.7091122321270097 │  84.209726576 │        17 │
│ database1      │  0.9967329158725837 │  80.834683612 │        16 │
│ database1      │                   0 │  80.281498498 │        96 │
│ database1      │ 0.06533687526128729 │  76.051238386 │       100 │
│ database1      │                   0 │  55.981111812 │        97 │
│ database1      │                   0 │  52.243383859 │        78 │
│ database1      │                   0 │  31.760010774 │        60 |

**Comment by den-crane** [comment]
>is it ok?

yes. Probably it's for different partitions. Check `partition_id` column in system.merges.

>Is there any formula or estimation to be used?

No. It's a very system specific. NVME for example could perform 10 times better than HDD raid.
Try to reduce insert rate somehow: engine=Buffer / ch-bulk ...

**Comment by mjodeh** [comment]
> yes. Probably it's for different partitions. Check partition_id column in system.merges.  

I checked it and it's for the same partition id!

**Comment by mjodeh** [comment]
I stopped the insertion and `tail -f /var/log/clickhouse-server/clickhouse-server.log` I see the following:

`2020.08.11 10:08:56.670500 [ 2603 ] {} <Error> void DB::SystemLog<LogElement>::flushImpl(const std::__1::vector<_Tp>&, uint64_t) [with LogElement = DB::TraceLogElement; uint64_t = long unsigned int]: Code: 252, e.displayText() = DB::Exception: Too many parts (600). Merges are processing significantly slower than inserts., Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xbb8c1cc in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x4ff4bb9 in /usr/bin/clickhouse
2. ? @ 0x4c57e23 in /usr/bin/clickhouse
3. DB::MergeTreeBlockOutputStream::write(DB::Block const&) @ 0x8eee25b in /usr/bin/clickhouse
4. DB::PushingToViewsBlockOutputStream::write(DB::Block const&) @ 0x9469458 in /usr/bin/clickhouse
5. DB::SquashingBlockOutputStream::writeSuffix() @ 0x9482b3a in /usr/bin/clickhouse
6. DB::SystemLog<DB::TraceLogElement>::flushImpl(std::__1::vector<DB::TraceLogElement, std::__1::allocator<DB::TraceLogElement> > const&, unsigned long) @ 0x5041d52 in /usr/bin/clickhouse
7. DB::SystemLog<DB::TraceLogElement>::savingThreadFunction() @ 0x5042103 in /usr/bin/clickhouse
8. ThreadFromGlobalPool::ThreadFromGlobalPool<DB::SystemLog<DB::TraceLogElement>::SystemLog(DB::Context&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long)::'lambda'()>(DB::TraceLogElement&&, DB::SystemLog<DB::TraceLogElement>::SystemLog(DB::Context&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long)::'lambda'()&&...)::'lambda'()::operator()() const @ 0x50422ad in /usr/bin/clickhouse
9. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x4ffe407 in /usr/bin/clickhouse
10. ? @ 0x4ffca5f in /usr/bin/clickhouse
11. start_thread @ 0x7e65 in /usr/lib64/libpthread-2.17.so
12. clone @ 0xfe88d in /usr/lib64/libc-2.17.so
 (version 20.3.8.53)`

Keeps complaining about `Merges are processing significantly slower than inserts` even though the insertion is stopped 15 min before!

**Comment by den-crane** [comment]
>Keeps complaining about Merges are processing significantly 
>slower than inserts even though the insertion is stopped 15 min before!

Because you inserted data into Distributed table with async mode. Distributed does real insertions later until when it stores data in .bin files in own folder.

**Comment by mjodeh** [comment]
Does the `ORDER BY` affect the merge's speed?
Right now we are using `ORDER BY (userId, eventTime)`, userId: String, eventTime: UInt32
the number of userId is 900k distinct values

**Comment by mjodeh** [comment]
is there any way to access the merge tasks queue and the current real parts that need to be merged? since in `system.merges` it shows only 16 tasks at maximum with there related `num_parts`

**Comment by alexey-milovidov** [comment]
Most likely you have very slow or overloaded IO subsystem on the server.
Running `dstat` and `iostat` on the server will help to quantify it.
