### ISSUE TITLE
Kafka engine settings param kafka_max_block_size doesn't work in 20.5.4.40

### ISSUE THREAD

**Issue by andrei-karpliuk** [ClickHouse/ClickHouse#13385]
Since my update to 20.5.4.40 
independs on **kafka_max_block_size** param in SETTINGS block of CREATE statement for Kafka engine 
I have the same 
`<Trace> StorageKafka (events_kafka): Polled batch of 65536 messages. Offset position: [ events[0:118227815] ]`

P.S. this parameter worked without any problem in version  20.4.4.18

**Comment by den-crane** [comment]
it seems now it's kafka_poll_max_batch_size
https://github.com/ClickHouse/ClickHouse/pull/11388

**Comment by andrei-karpliuk** [comment]
> it seems now it's kafka_poll_max_batch_size
> 
> kafka_poll_max_batch_size, 0, "Maximum amount of messages to be polled in a single Kafka poll.
> kafka_max_block_size, 0, "Number of row collected by poll(s) for flushing data from Kafka.
> 
> #11388

thanks, it works
