### ISSUE TITLE
Change MySQL engine configuration when the mysql is not accessable

### ISSUE THREAD

**Issue by shwangdev** [ClickHouse/ClickHouse#13398]
I have a database in clickhouse which is using MySQL engine. However, for some reason the IP of that mysql server was changed.  I can not drop the db in clickhouse , cause it reports can not access the old mysql ip.
So, how can I change the db engine configuration in clickhouse?

**Comment by tavplubix** [comment]
Reopen, because #28054 was reverted (so we don't forget to fix the test and merge it again)

**Comment by baxitashraf** [comment]
Yes, you can change the Table engine.

CREATE TABLE example_table (id UInt32, data Float64) 
ENGINE=MergeTree() ORDER BY id;

Insert into example_table values(1,1), (1,1), (2,1);


CREATE TABLE example_table1 (id UInt32, data Float64) 
ENGINE=SummingMergeTree() ORDER BY id;

-- this does not copy any data (instant & almost free command)
alter table example_table1 attach partition tuple() from example_table;


optimize table example_table1 final;

**Comment by tbragin** [comment]
@tavplubix does this still need to be open due to text not being fixed?

**Comment by melvynator** [comment]
I cannot seem to reproduce on recent version, deleted my DB:

```
DROP DATABASE mysql_db2

Query id: 3b604411-78be-4226-874e-2708eee5c390

Ok.

0 rows in set. Elapsed: 0.004 sec.
```
