### ISSUE TITLE
Shard macros per cluster

### ISSUE THREAD

**Issue by ghuname** [ClickHouse/ClickHouse#13418]
Let's say that I have 6 servers s1-s6 and I have created a cluster with two shards and triple replication.
hypothetical metrika.xml looks like this:

```
<yandex>
	<clickhouse_remote_servers>
		<triple_replication>
			<shard>
				<replica>
					<host>s1</host>
					<port>9000</port>
				</replica>
				<replica>
					<host>s2</host>
					<port>9000</port>
				</replica>
				<replica>
					<host>s3</host>
					<port>9000</port>
				</replica>
			</shard>
			<shard>
				<replica>
					<host>s4</host>
					<port>9000</port>
				</replica>
				<replica>
					<host>s5</host>
					<port>9000</port>
				</replica>
				<replica>
					<host>s6</host>
					<port>9000</port>
				</replica>
			</shard>
		</triple_replication>
	</clickhouse_remote_servers>
</yandex>
```

I have to specify macros as well, so I will create a macros.xml file on each server with contents:

```
<yandex>
	<macros>
		<layer>01</layer>
		<shard>01</shard>
		<replica>01</replica>
	</macros>
</yandex>
```

and changing key `<shard>` from 01 on servers s1-s3 and 02 on servers s4-s6, and `<replica>` from 01-06.

When I want to create a replicated table I will use:

```
CREATE TABLE table_name on cluster triple_replication
(
..
) ENGINE = ReplicatedMergeTree('/clickhouse/tables/{layer}-{shard}/table_name', '{replica}')
PARTITION BY ...
```

As you can see in the statement above "{shard}" placeholder will be replaced with `<shard>` from macros.xml file, so it will be 01 on s1-s3 or 02 on s4-s6

Let's say that I would like to create another cluster with 3 shards and double replication and use both clusters at the same time.
Now metrika.xml would look like:

```
<yandex>
	<clickhouse_remote_servers>
		<triple_replication>
			<shard>
				<replica>
					<host>s1</host>
					<port>9000</port>
				</replica>
				<replica>
					<host>s2</host>
					<port>9000</port>
				</replica>
				<replica>
					<host>s3</host>
					<port>9000</port>
				</replica>
			</shard>
			<shard>
				<replica>
					<host>s4</host>
					<port>9000</port>
				</replica>
				<replica>
					<host>s5</host>
					<port>9000</port>
				</replica>
				<replica>
					<host>s6</host>
					<port>9000</port>
				</replica>
			</shard>
		</triple_replication>

		<double_replication>
			<shard>
				<replica>
					<host>s1</host>
					<port>9000</port>
				</replica>
				<replica>
					<host>s2</host>
					<port>9000</port>
				</replica>
			<shard>
				<replica>
					<host>s3</host>
					<port>9000</port>
				</replica>
				<replica>
					<host>s4</host>
					<port>9000</port>
				</replica>
			</shard>
			<shard>
				<replica>
					<host>s5</host>
					<port>9000</port>
				</replica>
				<replica>
					<host>s6</host>
					<port>9000</port>
				</replica>
			</shard>
		</double_replication>
	</clickhouse_remote_servers>
</yandex>
```

Now I have to two different sharding schemas that I have to support in macros.xml file. 
In order to do so, I will have to introduce new macro `<shard_double>` for new cluster, that will be 01 on s1,s2, 02 on s3,s4 and 03 on s5,s6.

```
<yandex>
	<macros>
		<layer>01</layer>
		<shard>01</shard>
		<replica>01</replica>

		<shard_double>01</shard>
	</macros>
</yandex>
```

From now on, when I am creating replicating tables for the new (double_replication) cluster, I will have to use modified syntax, something like this (there is `{shard_double}` instead of `{shard}`):

```
CREATE TABLE table_name on cluster double_replication
(
..
) ENGINE = ReplicatedMergeTree('/clickhouse/tables/{layer}-{shard_double}/table_name', '{replica}')
PARTITION BY ...
```

Is there a better way of setting macros?
For example, It would be better if I have an opportunity to set macros per cluster?
In that case I would be able to use the same syntax for creation of replicated tables, and clickhouse will take care of applying proper values which would minimize the chance for an error.
Something like this (`<shard_num>01</shard_num>`):
```
<yandex>
	<clickhouse_remote_servers>
		<triple_replication>
			<shard>
				<shard_num>01</shard_num>
				<replica>
					<host>s1</host>
					<port>9000</port>
				</replica>
				<replica>
					<host>s2</host>
					<port>9000</port>
				</replica>
				<replica>
					<host>s3</host>
					<port>9000</port>
				</replica>
			</shard>
			<shard>
				<shard_num>02</shard_num>
				<replica>
					<host>s4</host>
					<port>9000</port>
				</replica>
				<replica>
					<host>s5</host>
					<port>9000</port>
				</replica>
				<replica>
					<host>s6</host>
					<port>9000</port>
				</replica>
			</shard>
		</triple_replication>

		<double_replication>
			<shard>
				<shard_num>01</shard_num>
				<replica>
					<host>s1</host>
					<port>9000</port>
				</replica>
				<replica>
					<host>s2</host>
					<port>9000</port>
				</replica>
			<shard>
				<shard_num>02</shard_num>
				<replica>
					<host>s3</host>
					<port>9000</port>
				</replica>
				<replica>
					<host>s4</host>
					<port>9000</port>
				</replica>
			</shard>
			<shard>
				<shard_num>03</shard_num>
				<replica>
					<host>s5</host>
					<port>9000</port>
				</replica>
				<replica>
					<host>s6</host>
					<port>9000</port>
				</replica>
			</shard>
		</double_replication>
	</clickhouse_remote_servers>
</yandex>
```

And than use (`{shard_num}`) for all tables:

```
CREATE TABLE table_name on cluster any_cluster
(
..
) ENGINE = ReplicatedMergeTree('/clickhouse/tables/{layer}-{shard_num}/table_name', '{replica}')
PARTITION BY ...
```

At the moment I have to be very careful whether about which shard macros I will choose.
Maybe there is an approach that I am not aware of at the moment.
Please do advise.

**Comment by den-crane** [comment]
You can create own macros in any combination and use them as you want.  layer / shard / replica -- just a recommendation. 
You don't need layer because it's for huge clusters like 100+ nodes.

so for example create to shard macros

shard_double and shard_triple

```
s1 shard_double=1  shard_triple=1  replica=s1
s2 shard_double=1 shard_triple=1  replica=s2
s3 shard_double=1 shard_triple=2  replica=s3
s4 shard_double=2 shard_triple=2  replica=s4
s5 shard_double=2 shard_triple=3  replica=s5
s6 shard_double=2 shard_triple=3  replica=s6

CREATE TABLE table_name on cluster triple_replication
(
..
) ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard_double}/table_name', '{replica}')
PARTITION BY ...

CREATE TABLE table_name on cluster double_replication
(
..
) ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard_triple}/table_name', '{replica}')
PARTITION BY ...


```

**Comment by ghuname** [comment]
I hoped that I will be able to use the same {shard} variable placeholder because it is very convenient if you are creating tables (for example kafka, view, shard, distributive tables for many kafka streams, each stream these four tables) by using script automation. 

Because the fact that cluster is specified at the time of creating shard table `CREATE TABLE table_name on cluster double_replication` clickhouse could use {shard} variable for that specific cluster instead of general macros.

Anyway, if it is not possible, I will use procedure you have described above. 
Thanks

**Comment by qoega** [comment]
In your automaton you can use something like `{CLUSTER_PLACEHOLDER_shard}` and replace `CLUSTER_PLACEHOLDER` in query to cluster name before query execution.

**Comment by dalei2019** [comment]
Same issue!

**Comment by brightzheng100** [comment]
Not sure why this has been closed as I don't think it's solved.

Macros are a great mechanism for scaling out CH with shards and replicas.
And having cluster-specific macros might be more helpful to simplify things with similar and even the same naming patterns.

For example:

Instead of flat macros:

```yaml
<clickhouse>
    <macros>
        <cluster>cluster_1s_3r</cluster>
        <shard>01</shard>
        <replica>01</replica>
    </macros>
</clickhouse>
```

We can introduce hierarchical, cluster-specific macros, on top of the flat ones, like:

```yaml
<clickhouse>
    <!-- flat macros -->
    <macros>
        <shard>01</shard>
        <replica>01</replica>
    </macros>

    <!-- cluster-specific macros -->
    <macros>
        <cluster_1s_3r>
            <shard>01</shard>
            <replica>01</replica>
        </cluster_1s_3r>
    </macros>
    <macros>
        <cluster_2s_2r>
            <shard>01</shard>
            <replica>01</replica>
        </cluster_2s_2r>
    </macros>
</clickhouse>
```

So in a 4-node CH setup:
1. The `cluster_1s_3r` can have node{1..3} with:
    - node1: cluster_1s_3r/shard and cluster_1s_3r/replica with 01, 01
    - node2: cluster_1s_3r/shard and cluster_1s_3r/replica with 01, 02
    - node3: cluster_1s_3r/shard and cluster_1s_3r/replica with 01, 03
2. Meanwhile, the macros can well support  `cluster_2s_2r` too, with:
    - node1: cluster_2s_2r/shard and cluster_2s_2r/replica with 01, 01
    - node2: cluster_2s_2r/shard and cluster_2s_2r/replica with 01, 02
    - node3: cluster_2s_2r/shard and cluster_2s_2r/replica with 02, 01
    - node4: cluster_2s_2r/shard and cluster_2s_2r/replica with 02, 01

In this case, we can still enjoy the same naming convention while creating tables, with things like:

```SQL
# in cluster cluster_1s_3r
:) create table if not exists my_table on cluster cluster_1s_3r (
...) engine=ReplicatedMergeTree('/clickhouse/tables/{cluster}/{shard}/my_table','{replica}')

# in cluster cluster_2s_2r
:) create table if not exists my_table on cluster cluster_2s_2r (
...) engine=ReplicatedMergeTree('/clickhouse/tables/{cluster}/{shard}/my_table','{replica}')
```

Doesn't it make more sense?
