### ISSUE TITLE
OpenTelemetry support: a prototype

### ISSUE THREAD

**Issue by akuzm** [ClickHouse/ClickHouse#13444]
What I'm going to implement, in order:

1. `system.opentelemetry_log` -- store `Span`s in a table, like other `system.log`s. Just a bare minimum of data as described [here](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/overview.md#span). Add some basic spans like the entire query, top-level execution stages, distributed requests. Doesn't matter which ones, this is just a foundation.

2. `SpanContext` propagation for incoming queries over HTTP. Parse the [`traceparent` header](https://www.w3.org/TR/trace-context/)

3. `SpanContext` propagation over native protocol -- for distributed queries.

4. Propagate span context to external table engines and dictionaries. Pick a couple of engines, just to see how it works.

These steps should make it possible to use ClickHouse as a part of a larger system of services that uses OpenTelemetry. There will be some basic observability into ClickHouse, and the traces will be connected when passing through ClickHouse to the downstream services.

After implementing this foundation, we'll have to show it to someone who actually uses OpenTelemetry to know if it's helpful. Hopefully I haven't missed anything crucial and at least we won't have to scrap it. We can also accept external contribution with improvements -- e.g. adding more spans, more metrics for them, propagating to more kinds of external services, etc.

**Comment by akuzm** [comment]
We now have `system.opentelemetry_span_log`, accept trace context headers over HTTP and Native protocols, add a few spans for some stages of query execution, and propagate trace context to remote ClickHouse servers and to URL engine.

https://clickhouse.tech/docs/en/operations/opentelemetry/

#14195
#16535

**Comment by zdyj3170101136** [comment]
@akuzm 
hello, i am using clickhouse, but seems system.opentelemetry_span_log is not exist.
do we support it now?

https://github.com/ClickHouse/ClickHouse/issues/41962
