### ISSUE TITLE
SELECT * from subqueries with repeated columns return only unique columns

### ISSUE THREAD

**Issue by jrogov** [ClickHouse/ClickHouse#13453]
**Describe the unexpected behaviour**
Currently Clickhouse interpretes `SELECT *` from subqueries as "select all unique columns from this subquery", although saving the order, but stripping repeated columns.

It's best demonstrated with queries below

**How to reproduce**
* Tested on Clickhouse 19+
* Any interface
* Default settings
* No tables
* No data
* Queries to run that lead to unexpected result
```
90be848025f1 :) select sum(number), sum(number) from numbers(10)

SELECT
    sum(number),
    sum(number)
FROM numbers(10)

┌─sum(number)─┬─sum(number)─┐
│          45 │          45 │
└─────────────┴─────────────┘

1 rows in set. Elapsed: 0.007 sec.

90be848025f1 :) select * from (select sum(number), sum(number) from numbers(10))

SELECT *
FROM
(
    SELECT
        sum(number),
        sum(number)
    FROM numbers(10)
)

┌─sum(number)─┐
│          45 │
└─────────────┘
```

**Expected behavior**
Order for such queries, for both unique and repeated columns, must be preserved.

**Error message and/or stacktrace**
None

**Additional context**
None

**Comment by alexey-milovidov** [comment]
I have checked how it works in other DBMS just in case.

MySQL:

`SELECT * FROM (SELECT 1 AS x, 1 AS x) t`
> Duplicate column name 'x'
`SELECT * FROM (SELECT 1, 1) t`
> Duplicate column name '1'
`SELECT * FROM (SELECT avg(x), avg(x) FROM (SELECT 1 AS x) t1) t2`
> Duplicate column name 'avg(x)'

Postgres:

All queries work perfectly.

**Comment by alexey-milovidov** [comment]
How it should work according to SQL standard?

**Comment by arikai** [comment]
Not really sure if it's dictated by the standard, since in Postgres I get this:
```psql
# select * from (select sum(id), sum(id) from users) s;
 sum  | sum
------+------
 8923 | 8923
```
