### ISSUE TITLE
self-describing formats + auto-parsing

### ISSUE THREAD

**Issue by alanpaulkwan** [ClickHouse/ClickHouse#13526]
Hi Clickhouse

I am wondering if it makes sense to support reading without specifying a schema for self-described file formats. In particular, I am hoping Parquet (one day SAS) can be directly queried without resorting to defining the column structure. I am sure for most data types there exists a reasonable isomorphism from Parquet to Clickhouse - hence Parquet support. 

Thus, all of the syntax around bolded below would not be necessary...

file('filepath','Parquet'**,' name String,value Float64'**)

I am hoping a pipe to clickhouse-client or clickhouse-local via the command line can follow this principle. Thus for both create table + select queries. And while we're talking wish list, another awesome thing would be is if there was some way to auto-gen a feasible schema based on the Parquet table, so if I say something like

``
create table a.b Engine=MergeTree ORDER BY date as select date,blah from file('filepath','Parquet')
``
or 
``
clickhouse-client 'create table a.b Engine=MergeTree ORDER BY date as select * Format Parquet' < filepath
``

An obvious reason to do this is user friendliness. Right now, I might need Drill / Python / R currently to inspect a Parquet file and write a schema so I can import into Clickhouse. Instead, I can cut out those intermediary steps and have Clickhouse take care of the thinking for me. I happen to have automated R to Clickhouse schema creation for the most part, it'd be great to do this directly.

Another justification for this is performance. Maybe I'm wrong but right now it seems like to manage a Parquet file, one has to specify every column in the Parquet file. Though I think it'd be in keeping with Clickhouse principles to avoid unnecessary column scans.

**Comment by alanpaulkwan** [comment]
While we're at it, although I know there's plenty of reasons why Clickhouse uses a proprietary format, I would suggest that Clickhouse is a little bit slow right now when dealing with Parquet. DuckDB is much faster for example on the same file.

**Comment by amosbird** [comment]
> While we're at it, although I know there's plenty of reasons why Clickhouse uses a proprietary format, I would suggest that Clickhouse is a little bit slow right now when dealing with Parquet. DuckDB is much faster for example on the same file. I have a 96 million row with a 33k group by (just count()). The proprietary Clickhouse format does this in 0.5 seconds, DuckDB does it on the Parquet file in 2-3 seconds and Clickhouse does this on the Parquet file in 21 seconds using a file table engine.

`count()` isn't suitable for benchmarking. Each engine would have different optimization rules to count rows. Perhaps you can try scanning one column out of some parquet files and blackhole the results right away. It's also necessary to set a fixed thread number for fair comparision. That being said, there are a lot of optimization opportunities for clickhouse + parquet.

**Comment by alanpaulkwan** [comment]
Thanks. I was doing this off my laptop and also I re-did the test using count distinct or sum, still Clickhouse is quite slow right now. Also Clickhouse requires a single file, whereas most Parquet files are now partitioned.

**Comment by filimonov** [comment]
#14450

**Comment by alexey-milovidov** [comment]
Solved.

**Comment by alexey-milovidov** [comment]
https://www.youtube.com/watch?v=gP7I2SUBXig
