### ISSUE TITLE
cosine distance is too slow

### ISSUE THREAD

**Issue by cmdares** [ClickHouse/ClickHouse#13527]
100m row vector compute cosine distance with one row，use 300 seconds ，if can be improve vector compute？

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by filimonov** [comment]
How do you calculate it? Can you share some sample data?

**Comment by alexey-milovidov** [comment]
@cmdares ClickHouse does not have builtin feature to calculate cosine distance.
It depends on how do you perform it in your query.

**Comment by lochv** [comment]
@alexey-milovidov maybe  

With [1.1,1.2] as a
select uid, (arraySum((a_i, feature_i) -> (a_i * feature_i), a, feature) / sqrt(arraySum(x -> (x * x), a) * arraySum(x -> (x * x), feature)))  as distance from features

**Comment by alexey-milovidov** [comment]
Yes, this will work.

Also `arrayReduce('corr', arr1, arr2)` will calculate the cosine distance.
