### ISSUE TITLE
How could I import kafka message with json object in CH?

### ISSUE THREAD

**Issue by chu1070y** [ClickHouse/ClickHouse#13543]
I have a json message in kafka.
```json
{
  "payload": {
    "id": 3,
    "name": "c",
    "__op": "c",
    "__lsn": 367383816,
    "__schema": "ec_mall66",
    "__deleted": "false"
  }
}
```
Can I import the message in CH?
I saw documents but it seems CH only supports nested json object with [].

**Comment by filimonov** [comment]
Use 20.5 and newer and JSONAsString format. After that parse the string with JSON functions

**Comment by chu1070y** [comment]
Great. It worked :)
