### ISSUE TITLE
Table TTL support DataTime64 type

### ISSUE THREAD

**Issue by hzhaop** [ClickHouse/ClickHouse#13567]
**Use case**
Currently, TTL supports only DataTime or Date type. 
We have a DateTime64 field and want to set a table ttl on it.

**Describe the solution you'd like**
Table TTL support DateTime64 type.

**Comment by den-crane** [comment]
WA expression (cast - toDateTime(d) ):

 ```
CREATE TABLE example_table
 (
     d DateTime64(3),
     a Int
 )
 ENGINE = MergeTree
 PARTITION BY toYYYYMM(d)
 ORDER BY d
 TTL toDateTime(d) + INTERVAL 1 MONTH;

```
