### ISSUE TITLE
Select from different tables based on condition

### ISSUE THREAD

**Issue by mbtolou** [ClickHouse/ClickHouse#13563]
who to select from different tables based on condition ?

```
SELECT *
FROM A
PREWHERE A.N='GOOGLE'
WHERE :KIND=1
UNION ALL
SELECT *
FROM B
PREWHERE A.N='BING'
WHERE :KIND=2
```

```
SELECT *
FROM
  (
    CASE WHEN :kind THEN
      SELECT *
      FROM A
    ELSE
      SELECT *
      FROM B
    END
  );
```

**Comment by den-crane** [comment]
The first should work. The second is against SQL (in general ANSI/SQL) .

**Comment by filimonov** [comment]
Sometimes i need something like Engine=Merge but picking the first matching table only (and empty row if no matching tables found), i think that issue is about smth similar.

@mbtolou am I right, can you describe the use case a bit?

**Comment by mbtolou** [comment]
TABLE 1 is VOLTAGE_A 
TABLE 2 is VOLTAGE_B
TABLE 3 is VOLTAGE_C

All table contain 1.5B records.

i want to megre voltages table (a,b,c) for report 

when merge 2 of three table ram of server growth and then query failed.

```
SELECT V_A,V_B
FROM SEARCH_RESULT SR,VOLTAGE_A VA,VOLTAGE_B VB
WHERE 
        VA.DATA_ID=VB.DATA_ID
        AND SR.DATA_ID=VA.DATA_ID
        AND VA.DATE_R=VB.DATE_R
        AND VA.DATE_R BETWEEN toDateTime('2020-01-01 00:00:00') AND toDateTime('2020-02-01 00:00:00')
```

SEARCH_RESULT is temporary table that contains list of meters.

**Comment by alexey-milovidov** [comment]
I recommend to store all data in single table (and differentiate by some field like `sensor_id`) instead of three tables with identical structure.
