### ISSUE TITLE
ReplacingMergeTree get the older record but not the latest record with key final

### ISSUE THREAD

**Issue by peaksnail** [ClickHouse/ClickHouse#13570]
Hi team,

there is a table call goods_sale 
```
create table goods_sale (
storeId String,
no String,
goodsList   Nested (
 name String,
 total Int64
),
createDate Int64,
updateDate Int64,
eventDate Date default toDate(createDate/1000)
)  engine = ReplacingMergeTree(eventDate, (storeId, no,  createDate, eventDate), 8192)
```

In 2020.6.22 I Insert into one record 
```
storeId no  goodsList.name goodsList.total createDate updateDate
a92e8d33-34b2-40d1-a325-18069d7518a9 W0200622033330313473 1592768014810 1592768014809  ['怪兽利口酒','魔爪']  [0,0]      
```

In 2020.7.5 I update the record
```
storeId no  goodsList.name goodsList.total createDate updateDate
a92e8d33-34b2-40d1-a325-18069d7518a9 W0200622033330313473 1592768014810 1593961745804  ['怪兽利口酒','魔爪']  [0.6,2] 
```

the difference with the record is `goodsList.total` and `updateDate`

totay I execute the query 
```
select storeId,no,eventDate,createDate,updateDate,goodsList.name,goodsList.total from goods_sale final  where no='W0200622033330313473' and eventDate>today()-120
```

It return the older record but not the latest record which field `updateDate` equal 1592768014809  and `goodsList.total` equal [0,0] (the record is produced in 2020.6.22)

I use ReplacingMergeTree to update record, and this is the first time the result is not expected

is't a bug with ReplacingMergeTree?

**Comment by peaksnail** [comment]
I execute sql 
```
optimize table goods_sale final
```

the latest record disappear and the older record is saved, it's so weird

**Comment by den-crane** [comment]
You've missed to define a `version` column  

https://clickhouse.tech/docs/en/engines/table-engines/mergetree-family/replacingmergetree/

    _ver — column with version. Type UInt*, Date or DateTime. Optional parameter.

    When merging, ReplacingMergeTree from all the rows with the same sorting key leaves only one:
        Last in the selection, if ver not set.
        With the maximum version, if ver specified._

Should be    engine = ReplacingMergeTree(eventDate, (storeId, no,  createDate, eventDate), **updateDate** , 8192)
BTW, this syntax is obsolete try to use only new syntax:

```
engine = ReplacingMergeTree(updateDate)
partition by  toYYYYMM(eventDate) order by (storeId, no,  createDate, eventDate) 
settings index_granularity = 8192
```

**Comment by peaksnail** [comment]
thanks
```
ver — column with version. Type UInt*, Date or DateTime. Optional parameter.

When merging, ReplacingMergeTree from all the rows with the same sorting key leaves only one:

Last in the selection, if ver not set.
With the maximum version, if ver specified.
```

It has said that if  I don't define a version column, It will choose the last

**Comment by den-crane** [comment]
@peaksnail it will It will choose the row from the last **insert**.

1592768014809    1st insert
1593961745804    2nd insert <-- **the last insert**

MERGE process uses part number to find the last insert.

**Comment by peaksnail** [comment]
thanks, I resync the data and the result is right ,  I will keep to observe

**Comment by den-crane** [comment]
Closed for, now. Reopen if needed.
