### ISSUE TITLE
Question on whether the data will be lost when update server

### ISSUE THREAD

**Issue by sliontc** [ClickHouse/ClickHouse#13577]
My CK server version now is 18.14, and I want to update to the latest. So the origin data will be lost?

**Comment by den-crane** [comment]
No. Nothing will be lost. CH supports upgrades. 

But you should test a new version first because there are backward incompatible changes https://github.com/ClickHouse/ClickHouse/blob/master/CHANGELOG.md
And should test an upgrade procedure as well.

**Comment by sliontc** [comment]
Thanks a lot. In your opinion what version should I upgrade to?

**Comment by sliontc** [comment]
And for safety should I upgrade from 18 to 19 and then to 20 step by step?

**Comment by den-crane** [comment]
> Thanks a lot. In your opinion what version should I upgrade to?

Any stable version. Try the latest -- 20.6.3.28. **BUT you should test your application for compatibility.**

>And for safety should I upgrade from 18 to 19 and then to 20 step by step?

No need for 99.99% cases. It could be needed for complicated huge environments with many shards/replicas. That's why you should test the upgrade at stage env. as well.

**Comment by alexey-milovidov** [comment]
We guarantee that new server will work with the data from old server.

**Comment by sliontc** [comment]
ClickHouse Update 
If ClickHouse was installed from deb packages, execute the following commands on the server:

sudo apt-get update
sudo apt-get install clickhouse-client clickhouse-server
sudo service clickhouse-server restart

So I just go with this guide to upgrade?

**Comment by den-crane** [comment]
Yes, but I would use 

sudo apt-get install **clickhouse-common-static** clickhouse-client clickhouse-server

or specified the desired version 

apt-get install clickhouse-server=20.6.2.15  clickhouse-client=20.6.2.15  clickhouse-common-static=20.6.2.15

And test it at your testing environment first. Your application could be incompatible with a new CH.

**Comment by sliontc** [comment]
Thank you so much guys.
