### ISSUE TITLE
Changelog  of v20.6.3.28-stable

### ISSUE THREAD

**Issue by vkingnew** [ClickHouse/ClickHouse#13571]
I noticed Clickhouse v20.6.3.28-stable had released，please add release note
https://clickhouse.tech/docs/en/whats-new/changelog/
without theses information,hard to know what's new and what fix

**Comment by filimonov** [comment]
Check / help review: https://github.com/ClickHouse/ClickHouse/pull/13421/files

**Comment by alexey-milovidov** [comment]
Changelog is published here: https://github.com/ClickHouse/ClickHouse/blob/master/CHANGELOG.md
Website https://clickhouse.tech/docs release is lagged behind in a few hours.
