### ISSUE TITLE
 antlr4 grammar Analysis sql Failure

### ISSUE THREAD

**Issue by melin** [ClickHouse/ClickHouse#13585]
https://github.com/ClickHouse/ClickHouse/tree/master/utils/grammar
```sql
CREATE TABLE access_log (
              addtime DateTime,
              big_app_id String,
              app_id String,
              seq_id Nullable (String),
              uuid Nullable(String),
              time Nullable(String),
              device_key Nullable(String),
              manufacturer Nullable(String),
              ds Date
            ) ENGINE = MergeTree() 
            PARTITION BY toYYYYMM(ds)
            ORDER BY (add_time, big_app_id, app_id) 
```
 antlr4 grammar Analysis sql Failure

![image](https://user-images.githubusercontent.com/1145830/89799586-40e03400-db60-11ea-8007-f7735ca4b0ca.png)

**Comment by alexey-milovidov** [comment]
We don't support this grammar: https://github.com/ClickHouse/ClickHouse/blob/master/utils/grammar/README.md
The new experimental ANTLR grammar is being prepared in #11298
