### ISSUE TITLE
TTL Merges do not work after RENAME TABLE

### ISSUE THREAD

**Issue by wedi-dev** [ClickHouse/ClickHouse#13583]
During migration from Deprecated method for creating table to the new method decided to use TTL Merges.

Created table with `TTL date + toIntervalDay(91)` reinserted the date from old table. 
Data older than 91 days was deleted during merges.

Then to use the same Distributed tables I renamed the old table to free up name and then renamed new table with the old name to make Distirbuted tables work again. 

After that noticed that data is not deleted. 

`merge_with_ttl_timeout` has default value

Consulted on telegram and as advised detached / attached table - it helped, TTL Merges work again.

`ClickHouse server version 20.3.8 revision 54433.`

**Comment by CurtizJ** [comment]
Do I understand right, that merges with TTL stopped after table rename? What time did pass from moment beetween moment, when data should be deleted and moment, when you noticed, that is's actually not deleted?
