### ISSUE TITLE
Way to purge replication queue

### ISSUE THREAD

**Issue by simPod** [ClickHouse/ClickHouse#13619]
Is there a way to purge replication queue?

I have two replicas and we upgraded replica A while B stayed on lower version for a few minutes. Meanwhile replication_queue filled up with invalid partitions.

```
2020.08.11 14:53:44.947932 [ 216643 ] {} <Warning> default.a (ReplicatedMergeTreePartCheckThread): Checking part 20200702_136728_136733_1
2020.08.11 14:53:44.948391 [ 216643 ] {} <Warning> default.a (ReplicatedMergeTreePartCheckThread): Checking if anyone has a part covering 20200702_136728_136733_1.
2020.08.11 14:53:44.949465 [ 216643 ] {} <Error> default.a (ReplicatedMergeTreePartCheckThread): No replica has part covering 20200702_136728_136733_1 and a merge is impossible: we didn't find smaller parts with either the same min block or the same max block.
2020.08.11 14:53:44.951121 [ 216643 ] {} <Error> default.a (ReplicatedMergeTreePartCheckThread): Part 20200702_136728_136733_1 is lost forever.
```

Clickhouse started processing it but in a very slow pace. There was like 1500 lost parts and it was going 1 part per 5 minutes. I had to drop the table to clean the queue. Is there easier way to do this? To tell clickhouse to skip those parts and continue?

**Comment by den-crane** [comment]
>I have two replicas and we upgraded replica A while B stayed on lower version for a few minutes. Meanwhile re
> plication_queue filled up with invalid partitions.

This is incorrect behavior. Which version did you use?

> Is there easier way to do this? 

https://github.com/ClickHouse/ClickHouse/issues/10368

**Comment by simPod** [comment]
There was 20.6.3.28 and 20.1.11.73 running alongside.

If there were no exceptions in replication_queue, should `SYSTEM RESTART REPLICAS` do the trick?

**Comment by den-crane** [comment]
>Clickhouse started processing it but in a very slow pace. There was like 1500 lost parts and it was going 1 part per 5 minutes.

Then I don't really understand the issue. What was in system.replication_queue? Postpone reason?

**Comment by den-crane** [comment]
>should SYSTEM RESTART REPLICAS do the trick

It could for example in case if outgoing http connections are hanged because of network issues.

**Comment by simPod** [comment]
> What was in system.replication_queue? Postpone reason?

Nothing was postponed, currently executing, throwing exceptions etc. It was just sitting there.

**Comment by den-crane** [comment]
Then next time try detach table x ; attach table x

**Comment by simPod** [comment]
Ayrigh, thanks!
