### ISSUE TITLE
concurrency control and lock variables

### ISSUE THREAD

**Issue by etah000** [ClickHouse/ClickHouse#13635]
Currently, there are serveral kinds of lock variables/methods in StorageMergeTree/StorageReplicatedMergeTree codes.

1) action lock: merge, move, send
2) IStorage: lockStructructure**, lockAlter**, lockExclusiely
3) MergeTreeData:  lockParts()

and other mutex/locks.  The new developers, including me, are totally confused with all these locks. Can anyone give a simple explainatioin?  We will all appriciate your work.  

Thanks!

**Comment by alexey-milovidov** [comment]
1. Is an object that does not lock anything but prevents some actions to start or continue during the lifetime of the object (merge, move, send, respectfully).
2. Table-level RWLock to control DDL operations like DROP, RENAME, ALTER. Recently we have mostly eliminated the usages of this lock.
3. Just a mutex to access/modify the set of data parts in MergeTree.
