### ISSUE TITLE
ClickHouseResultSet not support LocalDateTime of java

### ISSUE THREAD

**Issue by nettm** [ClickHouse/ClickHouse#13644]
When i use mybatis read data from clickhouse, application throw an exception, that is "Not implemented for type=class java.time.LocalDateTime".

**Comment by nettm** [comment]
I use clickhouse jdbc connnect to the database, jdbc driver is ru.yandex.clickhouse.ClickHouseDriver,version is 0.2.4.

**Comment by den-crane** [comment]
A wrong code repo. Open your issue here https://github.com/ClickHouse/clickhouse-jdbc/issues

**Comment by xuelinchao** [comment]
does this bug fixed?

**Comment by den-crane** [comment]
> how to use LocalDateTime?

https://github.com/ClickHouse/clickhouse-jdbc/issues
