### ISSUE TITLE
Unexpected type inequality

### ISSUE THREAD

**Issue by greenbergjosh** [ClickHouse/ClickHouse#13653]
select [(toUInt8(3), toUInt8(3))] = [(toInt16(3), toInt16(3))]  -- true

select hasAny([(toInt16(3), toInt16(3))],[(toInt16(3), toInt16(3))])  -- true

select arrayFilter(x -> x = (toInt16(3), toInt16(3)), arrayZip([toUInt8(3)], [toUInt8(3)]))  -- [(3,3)]

select hasAny([(toUInt8(3), toUInt8(3))],[(toInt16(3), toInt16(3))])  -- false, odd man out

I would have expected the last one to return true (1).  I am being explicit with types to show the issue.  This actually came up when doing something more like:

-- x.a and x.b are columns of type array(Int16)

-- clickhouse makes the constant literal 3 have type UInt8

select hasAny(arrayZip(x.a, x.b), (3,3)) from table 

The query above never returns true (1).  I can make it work with explicit casting.

select hasAny(arrayZip(x.a, x.b), (toInt16(3),toInt16(3))) from table 

But, that feels a bit heavy and inconsistent.

Is this maybe related to covariant typing for clickhouse functions?  Is it expected behavior?  Is there a better workaround than the explicit casting.

**Comment by greenbergjosh** [comment]
Does anyone have any thoughts on this? I am writing a code generator to generate clickhouse queries, and this issue will require me to carry along superfluous type information so I can do the casts.  Any chance this could be corrected at some point?

**Comment by alexey-milovidov** [comment]
Fixed:

```
milovidov-desktop :) select hasAny([(toUInt8(3), toUInt8(3))],[(toInt16(3), toInt16(3))])

SELECT hasAny([(toUInt8(3), toUInt8(3))], [(toInt16(3), toInt16(3))])

Query id: ac4c3cdc-4531-4843-b796-37ea8248298c

┌─hasAny(array(tuple(toUInt8(3), toUInt8(3))), array(tuple(toInt16(3), toInt16(3))))─┐
│                                                                                  1 │
└────────────────────────────────────────────────────────────────────────────────────┘
```
