### ISSUE TITLE
DISTINCT works incorrectly if was already applied to one of the subqueries

### ISSUE THREAD

**Issue by L4vlet** [ClickHouse/ClickHouse#13666]
Hello, there. Run into the problem with DISTINCT expression. It works incorrectly on the main query if it was already applied to one of the subqueries bond with UNION ALL.

**How to reproduce**
Server version: 20.5.4.40. 19.17.6.36 was free of the bug.
Using Datagrip for running queries.
Non-default settings:
```
input_format_defaults_for_omitted_fields: 1
decimal_check_overflow: 0
joined_subquery_requires_alias: 0
```

Consider following query
```
select distinct number
from ((select number from numbers(10)) union all (select number from numbers(20)));
```
It works fine, returning 20 rows as expected.

But if we add distinct to subqueries (it doesn't matter to the first, the second or both)
```
select distinct number
from ((select distinct number from numbers(10)) union all (select distinct number from numbers(20)));
```

Then in 20.5.4.40 we'll see 30 rows with numbers from 0 to 9 duplicated.
However, `count(distinct number)` returns the correct number of rows.

**Comment by lizhichao** [comment]
`ClickHouse client version 20.5.3.27 (official build).`
`Connected to ClickHouse server version 20.5.3 revision 54435.`

```sql
MiWiFi-R4A-srv :) select distinct number from ((select number from numbers(10)) union all (select number from numbers(20)));

SELECT DISTINCT number
FROM
(
    SELECT number
    FROM numbers(10)
    UNION ALL
    SELECT number
    FROM numbers(20)
)

┌─number─┐
│      0 │
│      1 │
│      2 │
│      3 │
│      4 │
│      5 │
│      6 │
│      7 │
│      8 │
│      9 │
└────────┘
┌─number─┐
│     10 │
│     11 │
│     12 │
│     13 │
│     14 │
│     15 │
│     16 │
│     17 │
│     18 │
│     19 │
└────────┘

20 rows in set. Elapsed: 0.004 sec.
```

**Comment by alexey-milovidov** [comment]
It's a wrong optimization #10067.
To disable it, turn off the `optimize_duplicate_order_by_and_distinct` setting.

```
SET optimize_duplicate_order_by_and_distinct = 0
```
