### ISSUE TITLE
SummingMergeTree from table using ReplacingMergeTree engine.

### ISSUE THREAD

**Issue by mbtolou** [ClickHouse/ClickHouse#13669]
when insert new record ReplacingMergeTree and delete old rows ، SummingMergeTree  not affected !

**Comment by den-crane** [comment]
Do you mean you have Materialized View? 

Materialized View is an insert trigger and it reflects (sees) only inserts into source tables. 
It does not reflect any other change like drop / truncate / alter update/ alter delete/ ...

**Comment by mbtolou** [comment]
Can i refresh Materialized View manually?

**Comment by den-crane** [comment]
> Can i refresh Materialized View manually?

No, by you can re-create MV somehow:

truncate table /  insert into select ...
or
drop / create materialized view ... populate ...
