### ISSUE TITLE
SYSTEM STOP TTL MERGES call order matters

### ISSUE THREAD

**Issue by simPod** [ClickHouse/ClickHouse#13674]
https://github.com/ClickHouse/ClickHouse/issues/6200  
https://github.com/ClickHouse/ClickHouse/pull/6274

I'd expect that following statement order would 

1) disable merges
2) create table
3) insert row
4) insert another row
5) table `test` contains 2 rows

Instead, table `test` contains 1 rows (the second one inserted).

```sql
SYSTEM STOP TTL MERGES;

CREATE TABLE test
(
    `evaluated_at` DateTime,
    `is_up`        UInt8
) ENGINE = MergeTree
    PARTITION BY toDate(evaluated_at)
    ORDER BY tuple()
    TTL evaluated_at + toIntervalMinute(5);

INSERT INTO test
VALUES ('2020-02-29 00:21:17', 1);
INSERT INTO test
VALUES ('2020-02-29 00:21:17', 1);
```

If I want to achieve described behaviour, I have to change order:

```sql
CREATE TABLE test
(
    `evaluated_at` DateTime,
    `is_up`        UInt8
) ENGINE = MergeTree
    PARTITION BY toDate(evaluated_at)
    ORDER BY tuple()
    TTL evaluated_at + toIntervalMinute(5);

SYSTEM STOP TTL MERGES;

INSERT INTO test
VALUES ('2020-02-29 00:21:17', 1);
INSERT INTO test
VALUES ('2020-02-29 00:21:17', 1);
```

But the behaviour seems somewhat inconsistent. I'd expect that calling `SYSTEM STOP TTL MERGES;` disables TTL fully.

**Comment by alexey-milovidov** [comment]
Yes, this is how it works.

The query `SYSTEM STOP [TTL] MERGES` stops merges for all *existing* tables.
Newly created tables are not affected.

**Comment by simPod** [comment]
Oh I thought it sets a global behaviour. Thanks.
