### ISSUE TITLE
Issue with 20.5.3.27 -  DB::Exception: File not found:  mark file

### ISSUE THREAD

**Issue by amitsharma10** [ClickHouse/ClickHouse#13682]
(you don't have to strictly follow this form)

**Describe the bug**
Getting this issue often after upgrading to 20.5.3.27. We were using 19.16* earlier. 
DB::Exception: File not found: /mount/data/system/query_log/202008_146167_149307_2598/event_date.mrk2. (version 20.5.3.27 (official build)) 
**How to reproduce**
Not sure how to reproduce. This error happens every now and then. But it is consistent after it happens, until the server is restarted. 
* Which ClickHouse server version to use - 20.5.3.27.
* Which interface to use, if matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

**Expected behavior**

**Error message and/or stacktrace**

**Additional context**

**Comment by den-crane** [comment]
try to upgrade to 20.5.4.40
try to set enable_mixed_granularity_parts 1 in config.xml in merge_tree section
```
 
    <merge_tree>
	...
	<enable_mixed_granularity_parts>1</enable_mixed_granularity_parts>

    </merge_tree>
```

**Comment by amitsharma10** [comment]
Output of ls. 
ls: cannot access /mount/data/system/query_log/202008_146167_149307_2598/: No such file or directory

Do we need to upgrade and enable enable_mixed_granularity_parts or just enabling enable_mixed_granularity_parts is fine for now ?

**Comment by den-crane** [comment]
>Do we need to upgrade and enable enable_mixed_granularity_parts or just 
>enabling enable_mixed_granularity_parts is fine for now ?

not related. I would do both. It's a good idea to upgrade to higher minor release because it has a lot of bugfixes.
