### ISSUE TITLE
ClickHouse on AWS S3 with IAM role auth enabled

### ISSUE THREAD

**Issue by davidshtian** [ClickHouse/ClickHouse#13707]
As S3 is supported within ClickHouse for both function and table engine, however when using S3 feature, AWS access key and secret key will be provided, or the S3 object are public. 

If ClickHouse are deployed on Amazon EC2 instances that was launched with an IAM role, it would be safer to leverage this IAM role, instead of using access key & secret key. 

Hope ClickHouse would support this for security concerns using S3 functions and table engines. Thanks~

**Comment by tooptoop4** [comment]
how to specify S3 access/secret key? I couldn't see in the docs

**Comment by alexey-milovidov** [comment]
CC @excitoon @filimonov

**Comment by alex-zaitsev** [comment]
Fixed by #16856

**Comment by davidshtian** [comment]
Thanks~ And I'm not sure how to configure ClickHouse to enable this feature?

**Comment by davidshtian** [comment]
For CH 20.12.5, the config was set as below:

```
<yandex>
    <s3>
       <my_endpoint>
           <endpoint>https://s3.us-east-1.amazonaws.com:443</endpoint>
           <access_key_id>***</access_key_id>
           <secret_access_key>***</secret_access_key>
       </my_endpoint>
   </s3>
</yandex>
```

But still select * s3(path, format, structure) failed due to "AccessDenied" error.

**Comment by davidshtian** [comment]
> For CH 20.12.5, the config was set as below:
> 
> ```
> <yandex>
>     <s3>
>        <my_endpoint>
>            <endpoint>https://s3.us-east-1.amazonaws.com:443</endpoint>
>            <access_key_id>***</access_key_id>
>            <secret_access_key>***</secret_access_key>
>        </my_endpoint>
>    </s3>
> </yandex>
> ```
> 
> But still select * s3(path, format, structure) failed due to "AccessDenied" error.

Worked as shown in #18721. Thanks~

**Comment by filimonov** [comment]
See #16856 , set  use_environment_credentials=true
