### ISSUE TITLE
Attach exception: bin file has unexpected size

### ISSUE THREAD

**Issue by kendnone** [ClickHouse/ClickHouse#13716]
**Describe the bug**

Received exception from server (version 20.5.4):
Code: 228. DB::Exception: Received from localhost:9009. DB::Exception: /home/clickhouse/data/default/device_param_raw_old/detached/attaching_20200625_11144_22378_4/paramCode.bin has unexpected size: 3504204 instead of 20962355. 

**How to reproduce**
``` sql
ALTER TABLE `default`.`device_param_raw_old` ATTACH PART '20200625_11144_22378_4';
```
* Which ClickHouse server version to use
ClickHouse server version 20.6.3.28 (official build).

* Which interface to use, if matters

* Non-default settings, if any
use default settings

* `CREATE TABLE` statements for all tables involved
``` sql
CREATE TABLE default.device_param_raw_file
(
    `code` UInt64,
    `device_no` String,
    `Timestamp` UInt32,
    `DataDate` Date,
    `DataTime` DateTime,
    `paramCode` String,
    `paramValue` String,
    `Unit` String,
    `Status` String
)
ENGINE = MergeTree()
PARTITION BY DataDate
ORDER BY DataTime
SETTINGS index_granularity = 819
```
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result
```
ALTER TABLE `default`.`device_param_raw_old` ATTACH PART '20200625_11144_22378_4';
```
**Expected behavior**

no error;

**Error message and/or stacktrace**
![image](https://user-images.githubusercontent.com/27141040/90242523-c9f8b300-de5f-11ea-89c9-3c590f2f6305.png)

**Additional context**
I use this command just want to restore data, then it happens.

**Comment by kendnone** [comment]
this is the origin issue https://github.com/AlexAkulov/clickhouse-backup/issues/20

**Comment by filimonov** [comment]
Are you sure the file is full and not damaged?

**Comment by den-crane** [comment]
-SETTINGS index_granularity = 819

+SETTINGS index_granularity = 8192
