### ISSUE TITLE
quantileExactLow, quantileExactHight

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#13742]
Users want to get rounding mode in `quantileExact` equivalent to "median_low" from Python:
https://docs.python.org/3/library/statistics.html#statistics.median_low
while current implementation works equivalent to "median_high" (?)

**Comment by alexey-milovidov** [comment]
The proposal is to add two more functions: `quantileExactLow`, `quantileExactHight` that will produce result equivalent to `median_low` and `median_high` from Python (and add the corresponding variants with quantiles*, median*).

Even if `quantileExactHight` is 100% equivalent to `quantileExact`, we should add it as a synonim for consistency.

**Comment by bharatnc** [comment]
@alexey-milovidov I think I can take a stab at this.

**Comment by alexey-milovidov** [comment]
@bharatnc Perfect!
