### ISSUE TITLE
Code: 173, e.displayText() = DB::ErrnoException: Allocator: Cannot malloc 4.00 KiB., errno: 12, strerror: Cannot allocate memory

### ISSUE THREAD

**Issue by judeshawn** [ClickHouse/ClickHouse#13798]
The database suddenly hangs and shows that the memory cannot be allocated for 1 hour and it cannot be restarted automatically

clickhouse 20.4.3.16

Set parameters
 <max_memory_usage>20000000000</max_memory_usage>
 <max_memory_usage_for_user>10000000000</max_memory_usage_for_user>
 <max_memory_usage_for_all_queries>18000000000</max_memory_usage_for_all_queries>
  <max_execution_time>60</max_execution_time>
  
  <max_bytes_before_external_group_by>6000000000</max_bytes_before_external_group_by>
<max_rows_to_group_by>1000000</max_rows_to_group_by>
<group_by_overflow_mode>any</group_by_overflow_mode>
<max_rows_to_sort>1000000</max_rows_to_sort>
<max_bytes_to_sort>1000000000</max_bytes_to_sort>
<result_overflow_mode>break</result_overflow_mode>
<min_execution_speed>1000000</min_execution_speed>
<timeout_before_checking_execution_speed>15</timeout_before_checking_execution_speed>

* `CREATE TABLE` statements for all tables involved
The table building statement is basically like this
CREATE TABLE kingkoo2.cdc_im_ba_cust ( 
cust_id String,
cust_sname String,
.......
clickhouse_data Date ) ENGINE = MergeTree(clickhouse_data,cust_id, 8192)

Queries to run that lead to unexpected result

2020.08.16 15:06:36.169064 [ 9897 ] {} <Error> void DB::SystemLog<LogElement>::flushImpl(const std::__1::vector<_Tp>&, uint64_t) [with LogElement = DB::MetricLogElement; uint64_t = long unsigned int]: Code: 173, e.displayText() = DB::ErrnoException: Allocator: Cannot malloc 4.00 KiB., errno: 12, strerror: Cannot allocate memory, Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x10418760 in ?
1. DB::ErrnoException::ErrnoException(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int, std::__1::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > const&) @ 0x9003cfb in ?
2. DB::throwFromErrno(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int) @ 0x900368a in ?
3. Allocator<false, false>::allocNoTrack(unsigned long, unsigned long) @ 0x9030d9d in ?
4. DB::ColumnVector<unsigned long>::insert(DB::Field const&) @ 0x924924c in ?
5. DB::MetricLogElement::appendToBlock(DB::Block&) const @ 0xd4635c6 in ?
6. DB::SystemLog<DB::MetricLogElement>::flushImpl(std::__1::vector<DB::MetricLogElement, std::__1::allocator<DB::MetricLogElement> > const&, unsigned long) @ 0x908033b in ?
7. DB::SystemLog<DB::MetricLogElement>::savingThreadFunction() @ 0x9080938 in ?
8. ThreadFromGlobalPool::ThreadFromGlobalPool<DB::SystemLog<DB::MetricLogElement>::startup()::'lambda'()>(DB::MetricLogElement&&, DB::SystemLog<DB::MetricLogElement>::startup()::'lambda'()&&...)::'lambda'()::operator()() const @ 0x9080b56 in ?
9. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x902526b in ?
10. ? @ 0x9023753 in ?
11. start_thread @ 0x7e25 in /usr/lib64/libpthread-2.17.so
12. clone @ 0xf834d in /usr/lib64/libc-2.17.so
 (version 20.4.3.16 (official build))

2020.08.16 15:05:41.310764 [ 9890 ] {} <Error> void DB::BackgroundProcessingPool::threadFunction(): std::exception. Code: 1001, type: std::bad_alloc, e.what() = std::bad_alloc, Stack trace (when copying this message, always include the lines below):

2020.08.16 15:00:00.963626 [ 10088 ] {} <Error> virtual DB::WriteBufferFromHTTPServerResponse::~WriteBufferFromHTTPServerResponse(): Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = Assertion violation: !_pStream in file "../contrib/poco/Net/src/HTTPServerResponseImpl.cpp", line 114, Stack trace (when copying this message, always include the lines below):

**Expected behavior**
The database often appears suddenly Cannot allocate memory
And it won’t recover automatically for 1 hour

**Error message and/or stacktrace**

![image](https://user-images.githubusercontent.com/40844897/90329397-28946d00-dfd7-11ea-916e-f042a17a27bf.png)

**Comment by den-crane** [comment]
1. https://github.com/ClickHouse/ClickHouse/blob/master/CHANGELOG.md
Added a setting max_server_memory_usage to limit total memory usage of the server. The metric MemoryTracking is now calculated without a drift. The setting **max_memory_usage_for_all_queries** is now obsolete and does nothing. 

2. <max_memory_usage>20 000 000 000
<max_memory_usage_for_user>10 000 000 000
<max_memory_usage_for_all_queries>18 000 000 000
max_memory_usage > max_memory_usage_for_user > max_memory_usage_for_all_queries -- that is just has no sense.
max_memory_usage -- a query will never be able to use more than max_memory_usage_for_user.

3. Check `cat /proc/sys/vm/overcommit_memory` 
https://clickhouse.tech/docs/en/operations/tips/#ram
_**Do not disable overcommit. The value cat /proc/sys/vm/overcommit_memory should be 0 or 1.**_

**Comment by judeshawn** [comment]
thank you for your reply
Followed your prompt upgraded the database
cat /proc/sys/vm/overcommit_memory   Set up 0 

Ask questions：
Does the mechanical hard drive also have a big impact?

**Comment by judeshawn** [comment]
> 1. https://github.com/ClickHouse/ClickHouse/blob/master/CHANGELOG.md
>    Added a setting max_server_memory_usage to limit total memory usage of the server. The metric MemoryTracking is now calculated without a drift. The setting **max_memory_usage_for_all_queries** is now obsolete and does nothing.
> 2. <max_memory_usage>20 000 000 000
>    <max_memory_usage_for_user>10 000 000 000
>    <max_memory_usage_for_all_queries>18 000 000 000
>    max_memory_usage > max_memory_usage_for_user > max_memory_usage_for_all_queries -- that is just has no sense.
>    max_memory_usage -- a query will never be able to use more than max_memory_usage_for_user.
> 3. Check `cat /proc/sys/vm/overcommit_memory`
>    https://clickhouse.tech/docs/en/operations/tips/#ram
>    _**Do not disable overcommit. The value cat /proc/sys/vm/overcommit_memory should be 0 or 1.**_


thank you for your reply
Followed your prompt upgraded the database
cat /proc/sys/vm/overcommit_memory Set up 0

Ask questions：
Does the mechanical hard drive also have a big impact?  raid 0

**Comment by den-crane** [comment]
>Does the mechanical hard drive also have a big impact? raid 0

mechanical hard drive does not affect on memory usage and the error "Allocator: Cannot malloc 4.00"

mechanical hard drive is OK for ClickHouse from performance perspective. 
RAID of 12 HDD drives able to read 1GB/s -- it's close to a single SSD.

**Comment by judeshawn** [comment]
> > Does the mechanical hard drive also have a big impact? raid 0
> 
> mechanical hard drive does not affect on memory usage and the error "Allocator: Cannot malloc 4.00"
> 
> mechanical hard drive is OK for ClickHouse from performance perspective.
> RAID of 12 HDD drives able to read 1GB/s -- it's close to a single SSD.

Thank you for your answer

I use yesterday debugging run a few days, whether there will be problems

Previously, the installation of Clickhouse on SSD was very stable

After the server (mechanical disk Reid 1) is switched, the problem that it cannot be allocated appears

**Comment by den-crane** [comment]
I don't see how SSD/HDD can be related to the error "Cannot allocate memory". 

`overcommit_memory = 0` - did it help?

**Comment by den-crane** [comment]
No reply, closing.
