### ISSUE TITLE
Is there a way to add multiple columns in one statement？

### ISSUE THREAD

**Issue by pyscala** [ClickHouse/ClickHouse#13827]
I can add one column at a time through the following statement.
`ADD COLUMN [IF NOT EXISTS] name [type] [default_expr] [codec] [AFTER name_after]`
 [doc link](https://clickhouse.tech/docs/en/sql-reference/statements/alter/column/#alter_add-column)

Is there a way to add multiple columns in one statement？

**Comment by filimonov** [comment]
```
ALTER TABLE table_name ADD COLUMN a UInt8, ADD COLUMN b String, ADD COLUMN c Float32;
```

**Comment by pyscala** [comment]
Effective. @filimonov Thanks for your reply.
