### ISSUE TITLE
ninja fail

### ISSUE THREAD

**Issue by xiaobao3315** [ClickHouse/ClickHouse#13821]
checkout branch 'v20.5.4.40-stable' then 'cmake' command success , command 'ninja' fail

**Operating system**
10.15.3

**Cmake version**
3.16.5

**Ninja version**
1.10.0

**Compiler name and version**
Apple clang version 11.0.0 (clang-1100.0.33.17)

**Full cmake and/or ninja output**
[491/1689] Building CXX object src/CMakeFiles/dbms.dir/Storages/Kafka/StorageKafka.cpp.o
FAILED: src/CMakeFiles/dbms.dir/Storages/Kafka/StorageKafka.cpp.o
/Library/Developer/CommandLineTools/usr/bin/c++  -DLZ4_DISABLE_DEPRECATE_WARNINGS=1 -DPOCO_ENABLE_CPP11 -DPOCO_HAVE_FD_POLL -DPOCO_OS_FAMILY_UNIX -DSNAPPY_CODEC_AVAILABLE -DUNALIGNED_OK -DUSE_FASTMEMCPY=0 -DUSE_JEMALLOC=0 -DUSE_REPLXX=1 -DUSE_XXHASH=1 -DWITH_COVERAGE=0 -DWITH_GZFILEOP -DX86_64 -DZLIB_COMPAT -Iincludes/configs -I../src -Isrc -Isrc/Core/include -I../base/common/.. -Ibase/common/.. -I../contrib/cityhash102/include -Icontrib/zlib-ng -I../contrib/zlib-ng -I../base/pcg-random/. -I../contrib/lz4/lib -I../contrib/zstd/lib -I../contrib/libuv/include -isystem ../contrib/protobuf/src -isystem ../contrib/sparsehash-c11 -isystem ../contrib/openldap/include -isystem ../contrib/avro/lang/c++/include -isystem ../contrib/pdqsort -isystem ../contrib/libcxx/include -isystem ../contrib/libcxxabi/include -isystem ../contrib/libdivide/. -isystem ../contrib/cppkafka/include -isystem ../contrib/librdkafka-cmake/include -isystem ../contrib/librdkafka/src -isystem ../contrib/libbtrie/include -isystem ../contrib/boost -isystem ../contrib/msgpack-c/include -isystem ../contrib/re2 -isystem ../contrib/poco/Net/include -isystem ../contrib/poco/Foundation/include -isystem ../contrib/poco/NetSSL_OpenSSL/include -isystem ../contrib/poco/Crypto/include -isystem ../contrib/openssl-cmake/linux_x86_64/include -isystem ../contrib/openssl/include -isystem ../contrib/poco/Util/include -isystem ../contrib/poco/JSON/include -isystem ../contrib/poco/XML/include -isystem ../contrib/replxx/include -isystem ../contrib/fmtlib-cmake/../fmtlib/include -isystem ../contrib/double-conversion -isystem ../contrib/ryu -isystem contrib/re2_st -isystem ../contrib/croaring -isystem ../contrib/capnproto/c++/src -isystem ../contrib/arrow/cpp/src -isystem ../contrib/arrow-cmake/cpp/src -isystem ../contrib/avro/lang/c++/api -fdiagnostics-color=always -std=c++2a -fsized-deallocation  -gdwarf-aranges -msse4.1 -msse4.2 -mpopcnt   -Wall -Wno-unused-command-line-argument  -stdlib=libc++ -fdiagnostics-absolute-paths -Werror -mmacosx-version-min=10.15 -Wextra -Wpedantic -Wno-vla-extension -Wno-zero-length-array -Wcomma -Wconditional-uninitialized -Wcovered-switch-default -Wdeprecated -Wembedded-directive -Wempty-init-stmt -Wextra-semi-stmt -Wextra-semi -Wgnu-case-range -Winconsistent-missing-destructor-override -Wnewline-eof -Wold-style-cast -Wrange-loop-analysis -Wredundant-parens -Wreserved-id-macro -Wshadow-field -Wshadow-uncaptured-local -Wshadow -Wstring-plus-int -Wundef -Wunreachable-code-return -Wunreachable-code -Wunused-exception-parameter -Wunused-macros -Wunused-member-function -Wzero-as-null-pointer-constant -Weverything -Wno-c++98-compat-pedantic -Wno-c++98-compat -Wno-c99-extensions -Wno-conversion -Wno-deprecated-dynamic-exception-spec -Wno-disabled-macro-expansion -Wno-documentation-unknown-command -Wno-double-promotion -Wno-exit-time-destructors -Wno-float-equal -Wno-global-constructors -Wno-missing-prototypes -Wno-missing-variable-declarations -Wno-nested-anon-types -Wno-packed -Wno-padded -Wno-return-std-move-in-c++11 -Wno-shift-sign-overflow -Wno-sign-conversion -Wno-switch-enum -Wno-undefined-func-template -Wno-unused-template -Wno-vla -Wno-weak-template-vtables -Wno-weak-vtables -O2 -g -DNDEBUG -O3  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk   -D OS_DARWIN -nostdinc++ -MD -MT src/CMakeFiles/dbms.dir/Storages/Kafka/StorageKafka.cpp.o -MF src/CMakeFiles/dbms.dir/Storages/Kafka/StorageKafka.cpp.o.d -o src/CMakeFiles/dbms.dir/Storages/Kafka/StorageKafka.cpp.o -c ../src/Storages/Kafka/StorageKafka.cpp
/Users/dukang/workspace/CLionProjects/ClickHouse/src/Storages/Kafka/StorageKafka.cpp:366:15: error: no member named 'set_destroy_flags' in 'cppkafka::Consumer'
    consumer->set_destroy_flags(RD_KAFKA_DESTROY_F_NO_CONSUMER_CLOSE);
    ~~~~~~~~  ^
1 error generated.
[494/1689] Building CXX object src/Functions/GatherUtils/CMakeFiles/clickhouse_functions_gatherutils.dir/concat.cpp.o

**Comment by KochetovNicolai** [comment]
Probably, your submodules are configurated wrongly.
We use this to fix it:
```
git submodule sync --recursive && git submodule update --init --recursive && git submodule foreach git submodule foreach git reset --hard && git submodule foreach git submodule foreach git clean -xfd
```
Also try to remove `CMakeCache.txt` or the whole build folder.

We use clang-10 in ci, results you may find [here](https://clickhouse-builds.s3.yandex.net/11870/009ddd5c8d46d1427c2775b67918e0165e50844f/clickhouse_build_check/report.html). The build log is [accessible](https://clickhouse-builds.s3.yandex.net/11870/009ddd5c8d46d1427c2775b67918e0165e50844f/clickhouse_build_check/build_log_737947340_1596283058.txt) from report. You may follow the commands from there to reproduce the build.
