### ISSUE TITLE
How to force dropping readonly replicated table

### ISSUE THREAD

**Issue by tldzyx** [ClickHouse/ClickHouse#13836]
I created a ReplicatedMergeTree table, then the data in zookeeper has been reoved `rmr /clickhouse_perftest`.

And then I try to run `DROP TABLE hits_replica;`, but it's always say 'Received exception from server (version 20.3.17):
Code: 242. DB::Exception: Received from 127.0.0.1:19000. DB::Exception: Can't drop readonly replicated table (need to drop data in ZooKeeper as well).'

Next I stop clickhouse-server delete the table data by comand 'sudo rm -rf /var/lib/clickhouse/data/tutorial/hits_replica', then restart clickhouse-server, but the table clickhouse-server still in database, and can't drop it.

Is there any way just drop the table hits_replica?

**Comment by den-crane** [comment]
you can use 
sql: "detach table hits_replica"
sh: rm -rf /var/lib/clickhouse/data/tutorial/hits_replica ; **rm -rf /var/lib/clickhouse/metadata/tutorial/hits_replica.sql**
