### ISSUE TITLE
ALTER MODIFY ORDER BY does not work

### ISSUE THREAD

**Issue by fastio** [ClickHouse/ClickHouse#13835]
Hi guys,

My clickhouse version is 20.3.10.75. When altering the table order by expression, I got the exception message as follows:

```
Code: 36. DB::Exception: Received from localhost:9000. DB::Exception: Existing column version is used in the expression that was added to the sorting key. You can add expressions that use only the newly added columns.
```

The table is defined as follows:
```
CREATE TABLE default.users_online
(
    `when` DateTime,
    `uid` UInt64,
    `duration` UInt64,
    `version` Int32
)
ENGINE = MergeTree()
PARTITION BY toYYYYMM(when)
ORDER BY (uid, when)
SETTINGS index_granularity = 8192
```

The ALTER MODIFY ORDER BY command is ```ALTER TABLE users_online MODIFY ORDER BY (uid, when, version)```.

The expected behavior is table's order by expression should be modified.
Thanks.

**Comment by den-crane** [comment]
Code: 36. DB::Exception: Received from localhost:9000. DB::Exception: Existing column version is used in the expression that was added to the sorting key. **You can add expressions that use only the newly added columns.**


CREATE TABLE default.users_online
(
    `when` DateTime,
    `uid` UInt64,
    `duration` UInt64
)
ENGINE = MergeTree()
PARTITION BY toYYYYMM(when)
ORDER BY (uid, when)
SETTINGS index_granularity = 8192


ALTER TABLE default.users_online
    **ADD COLUMN `version` Int32,**
    MODIFY ORDER BY (uid, when, version)

Ok.

**Comment by fastio** [comment]
@den-crane Thank you for reply. I got it. If the ORDER BY expression modified with existing column,  the existing data of table should be re-sorted which will pay a huge cost.

**Comment by den-crane** [comment]
yes. 
BTW, MODIFY ORDER BY does not change primary index, it changes only rows sorting.


SHOW CREATE TABLE default.users_online

CREATE TABLE default.users_online
(
    when DateTime,
    uid UInt64,
    duration UInt64,
    version Int32
)
ENGINE = MergeTree()
PARTITION BY toYYYYMM(when)
**PRIMARY KEY (uid, when)**
**ORDER BY (uid, when, version)**
SETTINGS index_granularity = 8192
