### ISSUE TITLE
has no symbols

### ISSUE THREAD

**Issue by xiaobao3315** [ClickHouse/ClickHouse#13844]
checkout branch 'v20.5.4.40-stable' print out 'has no symbols'

Operating system
10.15.3

Cmake version
3.16.5

Ninja version
1.10.0

Compiler name and version
Apple clang version 11.0.0 (clang-1100.0.33.17)

Full cmake and/or ninja output
0/2] Re-checking globbed directories...
[69/4643] Linking CXX static library contrib/libcxxabi-cmake/libcxxabi.a
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: contrib/libcxxabi-cmake/libcxxabi.a(cxa_unexpected.cpp.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: contrib/libcxxabi-cmake/libcxxabi.a(cxa_unexpected.cpp.o) has no symbols
[99/4643] Linking CXX static library contrib/libcxx-cmake/libcxx.a
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: contrib/libcxx-cmake/libcxx.a(functional.cpp.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: contrib/libcxx-cmake/libcxx.a(typeinfo.cpp.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: contrib/libcxx-cmake/libcxx.a(functional.cpp.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: contrib/libcxx-cmake/libcxx.a(typeinfo.cpp.o) has no symbols
[124/4643] Linking CXX static library contrib/capnproto-cmake/libkj.a
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: contrib/capnproto-cmake/libkj.a(filesystem-disk-win32.c++.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: contrib/capnproto-cmake/libkj.a(filesystem-disk-win32.c++.o) has no symbols
[125/4643] Linking CXX static library contrib/capnproto-cmake/libcapnp.a
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: contrib/capnproto-cmake/libcapnp.a(list.c++.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: contrib/capnproto-cmake/libcapnp.a(list.c++.o) has no symbols
[148/4643] Linking CXX static library ...oost-cmake/lib_boost_program_options.a
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: contrib/boost-cmake/lib_boost_program_options.a(winmain.cpp.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: contrib/boost-cmake/lib_boost_program_options.a(winmain.cpp.o) has no symbols
[156/4643] Linking CXX static library contrib/boost-cmake/lib_boost_filesystem.a
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: contrib/boost-cmake/lib_boost_filesystem.a(windows_file_codecvt.cpp.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: contrib/boost-cmake/lib_boost_filesystem.a(windows_file_codecvt.cpp.o) has no symbols

**Comment by filimonov** [comment]
It looks like warnings that should not affect the compilation. 
Some libs which have no mac-related code will be empty (the list contains windows-related object files) 

MacOS is not a primary platform for us, so we just check very basic things / do smoke tests  - code compiles and can be started. 
If you want to improve that  / avoid those warnings - please collaborate. Feel free to send PR with darwin related adjustments.
