### ISSUE TITLE
 Adding a new column will cause the error "table columns structure in zookeeper is different from local table structure"

### ISSUE THREAD

**Issue by IVitamin-C** [ClickHouse/ClickHouse#13848]
When I execute this command to add a new column, it will continue to run normally after adding. If you restart the server or execute "deache table", it will not be able to continue running. The error "table columns structure in zookeeper is different from local table structure" is returned

version: 20.3.5.21
table engine:ReplicatedMergeTree
execute command : alter table  test.test1 on cluster testcluster add column if not exists test_add_column Int64 default 0 comment 'test add column';
error :DB::Exception: There was an error on [ck1.:9000]: Code: 122, e.displayText() = DB::Exception: Table columns structure in ZooKeeper is different from local table structure (version 20.3.5.21 (official build)).

**Comment by IVitamin-C** [comment]
If the server restarts, if the table of new fields is not deleted, the server will not be able to start. If you execute "deache table", "DB:: exception: table columns structure in zookeeper is different from local table structure (version 20.3.5.21)" will be returned after "attach table on cluster testcluster"

**Comment by Fanduzi** [comment]
I also face a similar situation in our RC environment.
we add one column to a table A yesterday,
>structure of table A
>```
>CREATE TABLE inno_topping_user.active_duration (
>`I_USER_ID` UInt64 COMMENT '用户id',
>`I_PROVINCE_ID` UInt64 COMMENT '省份id',
>`I_DEVICE_TYPE` UInt8 COMMENT '设备类型',
>`I_CHANNEL_ID` UInt8 COMMENT '渠道号',
>`V_DEVICE_UUID` String COMMENT '设备uuid',
>`V_VERSION` String COMMENT '版本号',
>`D_ACTIVE_START` Int64 COMMENT '开始活跃时间',
>`D_ACTIVE_END` Int64 COMMENT '结束活跃时间',
>`I_DURATION` Int64,
>`D_DATE` Date DEFAULT toDate(now()) COMMENT '日期') ENGINE = Distributed('ck_cluster', 'inno_topping_user', >'active_duration_local', rand())
>```
>the alter query is
>```
>alter table inno_topping_user.active_duration_local on cluster ck_cluster add column V_IP String DEFAULT 1 after V_VERSION;
>```
>so after alter the structure of table A is
>```
>CREATE TABLE inno_topping_user.active_duration (
>`I_USER_ID` UInt64 COMMENT '用户id',
>`I_PROVINCE_ID` UInt64 COMMENT '省份id',
>`I_DEVICE_TYPE` UInt8 COMMENT '设备类型',
>`I_CHANNEL_ID` UInt8 COMMENT '渠道号',
>`V_DEVICE_UUID` String COMMENT '设备uuid',
>`V_VERSION` String COMMENT '版本号',
>`V_IP` String DEFAULT 1,
>`D_ACTIVE_START` Int64 COMMENT '开始活跃时间',
>`D_ACTIVE_END` Int64 COMMENT '结束活跃时间',
>`I_DURATION` Int64,
>`D_DATE` Date DEFAULT toDate(now()) COMMENT '日期') ENGINE = Distributed('ck_cluster', 'inno_topping_user', >'active_duration_local', rand())
>```

it all runs ok, data were inseterted, nothing wrong happened. But today our clickhouse kill by oom-killer, then we restart the clickhouse, but get these error

```
2020.08.18 14:10:11.445420 [ 26758 ] {} <Error> Application: Caught exception while loading metadata: Code: 122, e.displayText() = DB::Exception: Table columns structure in ZooKeeper is different from local table structure: Cannot attach table `inno_toppin
g_user`.`active_duration_local` from metadata file /data/clickhouse/node1/metadata/inno_topping_user/active_duration_local.sql from query ATTACH TABLE active_duration_local (`I_USER_ID` UInt64 COMMENT '用户id', `I_PROVINCE_ID` UInt64 COMMENT '省份id', `I_D
EVICE_TYPE` UInt8 COMMENT '设备类型', `I_CHANNEL_ID` UInt8 COMMENT '渠道号', `V_DEVICE_UUID` String COMMENT '设备uuid', `V_VERSION` String COMMENT '版本号', `V_IP` String DEFAULT 1, `D_ACTIVE_START` Int64 COMMENT '开始活跃时间', `D_ACTIVE_END` Int64 COMMEN
T '结束活跃时间', `I_DURATION` Int64, `D_DATE` Date DEFAULT toDate(now()) COMMENT '日期') ENGINE = ReplicatedMergeTree('/clickhouse/inno_topping_user/tables/{layer}-{shard}/active_duration', '{replica}') PARTITION BY D_DATE ORDER BY (I_PROVINCE_ID, I_DEVIC
E_TYPE, I_CHANNEL_ID, V_VERSION) SETTINGS index_granularity = 8192, Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x102e0d8c in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x8f2d989 in /usr/bin/clickhouse
2. ? @ 0xd5fab04 in /usr/bin/clickhouse
3. DB::StorageReplicatedMergeTree::StorageReplicatedMergeTree(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, 
DB::StorageID const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::StorageInMemoryMetadata const&, DB::Context&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > cons
t&, DB::MergeTreeData::MergingParams const&, std::__1::unique_ptr<DB::MergeTreeSettings, std::__1::default_delete<DB::MergeTreeSettings> >, bool) @ 0xd5da56b in /usr/bin/clickhouse
4. ? @ 0xd9585da in /usr/bin/clickhouse
5. std::__1::__function::__func<std::__1::shared_ptr<DB::IStorage> (*)(DB::StorageFactory::Arguments const&), std::__1::allocator<std::__1::shared_ptr<DB::IStorage> (*)(DB::StorageFactory::Arguments const&)>, std::__1::shared_ptr<DB::IStorage> (DB::Storage
Factory::Arguments const&)>::operator()(DB::StorageFactory::Arguments const&) @ 0xd95baf3 in /usr/bin/clickhouse
6. DB::StorageFactory::get(DB::ASTCreateQuery const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, DB::Context&, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, bool) const @ 
0xd4fc66c in /usr/bin/clickhouse
7. DB::createTableFromAST(DB::ASTCreateQuery, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool) @ 
0xcedc88e in /usr/bin/clickhouse
8. ? @ 0xced33bf in /usr/bin/clickhouse
9. ? @ 0xced3b71 in /usr/bin/clickhouse
10. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0x8f51c4b in /usr/bin/clickhouse
11. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<
void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()&&...)::'lambda'()::operator()() const @ 0x8f528c4 in /usr/bin/clickhouse
12. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x8f50b4b in /usr/bin/clickhouse
13. ? @ 0x8f4f00f in /usr/bin/clickhouse
14. start_thread @ 0x7dd5 in /usr/lib64/libpthread-2.17.so
15. clone @ 0xfdead in /usr/lib64/libc-2.17.so
 (version 20.3.4.10 (official build))
```

this is not the first time we see this error. 
I don’t know if it should be handled like this, but when I perform the following operations clickhouse starts successfully and the table is restored

rename metadata sql file
>```
>cd /data/clickhouse/node1/metadata/inno_topping_user
>mv active_duration_local.sql active_duration_local.sql.bak
>```
then, start clickhouse-server. 


check metadata in zookeeper
>```
>[zk: localhost:2181(CONNECTED) 20] get /clickhouse/inno_topping_user/tables/01-01/active_duration/replicas/bj2-all-clickhouse-test-01/columns
>columns format version: 1
>11 columns:
>`I_USER_ID` UInt64      COMMENT \'用户id\'
>`I_PROVINCE_ID` UInt64  COMMENT \'省份id\'
>`I_DEVICE_TYPE` UInt8   COMMENT \'设备类型\'
>`I_CHANNEL_ID` UInt8    COMMENT \'渠道号\'
>`V_DEVICE_UUID` String  COMMENT \'设备uuid\'
>`V_VERSION` String      COMMENT \'版本号\'
>`V_IP` String   DEFAULT 1
>`D_ACTIVE_START` Int64  COMMENT \'开始活跃时间\'
>`D_ACTIVE_END` Int64    COMMENT \'结束活跃时间\'
>`I_DURATION` Int64
>`D_DATE` Date   DEFAULT toDate(now())   COMMENT \'日期\'
>```

remove ``V_IP` String   DEFAULT 1`, reset columns value
>```
>zkCli.sh set /clickhouse/inno_topping_user/tables/01-01/active_duration/replicas/bj2-all-clickhouse-test-01/columns "columns format version: 1
>10 columns:
>\`I_USER_ID\` UInt64      COMMENT \'用户id\'
>\`I_PROVINCE_ID\` UInt64  COMMENT \'省份id\'
>\`I_DEVICE_TYPE\` UInt8   COMMENT \'设备类型\'
>\`I_CHANNEL_ID\` UInt8    COMMENT \'渠道号\'
>\`V_DEVICE_UUID\` String  COMMENT \'设备uuid\'
>\`V_VERSION\` String      COMMENT \'版本号\'
>\`D_ACTIVE_START\` Int64  COMMENT \'开始活跃时间\'
>\`D_ACTIVE_END\` Int64    COMMENT \'结束活跃时间\'
>\`I_DURATION\` Int64
>\`D_DATE\` Date   DEFAULT toDate(now())   COMMENT \'日期\'
>"
>```

restore table
>```
>vim active_duration_local.sql.bak , remove line ``V_IP` String DEFAULT 1,`
>mv active_duration_local.sql.bak active_duration_local.sql
>```

attach table
>```
>ATTACH TABLE inno_topping_user.active_duration_local;
>```
the table was stored, and is able to select/insert


I realy don't know why... It's really uncomfortable, I don't know if the production environment will encounter this problem.

**Comment by filimonov** [comment]
Similar:  https://github.com/ClickHouse/ClickHouse/issues/13673

**Comment by IVitamin-C** [comment]
After testing, it is found that if the newly added column is of string type, this problem will not occur. If it is of int type, it will appear, with 100% recurrence

**Comment by Fanduzi** [comment]
> After testing, it is found that if the newly added column is of string type, this problem will not occur. If it is of int type, it will appear, with 100% recurrence

hi. 
alter table inno_topping_user.active_duration_local on cluster ck_cluster add column V_IP String DEFAULT 1 after V_VERSION;

maybe string default int will appear too? 
I did not test, if you are interested, you can help test it, my case is this situation

**Comment by IVitamin-C** [comment]
String is not allowed to default to 1

> > 经过测试，发现如果新添加的列是字符串类型，则不会发生此问题。如果它是int类型，它将以100％重复出现
> 
> 你好
> 更改群集ck_cluster上的表inno_topping_user.active_duration_local，在V_VERSION之后添加列V_IP字符串DEFAULT 1；
> 
> 也许字符串默认int也会出现吗？
> 我没有测试，如果您有兴趣，可以帮助测试一下，我的情况就是这种情况



> > After testing, it is found that if the newly added column is of string type, this problem will not occur. If it is of int type, it will appear, with 100% recurrence
> 
> hi.
> alter table inno_topping_user.active_duration_local on cluster ck_cluster add column V_IP String DEFAULT 1 after V_VERSION;
> 
> maybe string default int will appear too?
> I did not test, if you are interested, you can help test it, my case is this situation

String is not allowed to default to 1

**Comment by IVitamin-C** [comment]
> > After testing, it is found that if the newly added column is of string type, this problem will not occur. If it is of int type, it will appear, with 100% recurrence
> 
> hi.
> alter table inno_topping_user.active_duration_local on cluster ck_cluster add column V_IP String DEFAULT 1 after V_VERSION;
> 
> maybe string default int will appear too?
> I did not test, if you are interested, you can help test it, my case is this situation

String is not allowed to default to 1. It can be '1' and converted once during upper processing

**Comment by IVitamin-C** [comment]
At present, the upgrade version can solve this problem. We will upgrade the production environment cluster

**Comment by filimonov** [comment]
I've got one more error report about the same:

> After attempting to update a DDL for one of our clickhouse tables, our alter query command halted. We rolled back the column addition, but after restarting one of the hosts we see this error: Table columns structure in ZooKeeper is different from local table

**Comment by alesapin** [comment]
> At present, the upgrade version can solve this problem. We will upgrade the production environment cluster

Yes we had several bugs in early 20.3 versions with different metadata structure. Just try to update and check that issue reproduces.

**Comment by IVitamin-C** [comment]
> > At present, the upgrade version can solve this problem. We will upgrade the production environment cluster
> 
> Yes we had several bugs in early 20.3 versions with different metadata structure. Just try to update and check that issue reproduces.
> 
> I'll try to investigate, it reproduces only when the added column has a comment?

At present, it is found that distributed DDL for updating or deleting columns cannot be executed in some tables,progress 0%
Version has been updated to 20.6.

**Comment by IVitamin-C** [comment]
> > > At present, the upgrade version can solve this problem. We will upgrade the production environment cluster
> > 
> > 
> > Yes we had several bugs in early 20.3 versions with different metadata structure. Just try to update and check that issue reproduces.
> > I'll try to investigate, it reproduces only when the added column has a comment?
> 
> At present, it is found that distributed DDL for updating or deleting columns cannot be executed in some tables,progress 0%
> Version has been updated to 20.6.

DB::Exception: Metadata on replica is not up to date with common metadata in Zookeeper. Cannot alter, Stack trace (when copying this message, always include the lines below):

**Comment by IVitamin-C** [comment]
> > > > At present, the upgrade version can solve this problem. We will upgrade the production environment cluster
> > > 
> > > 
> > > Yes we had several bugs in early 20.3 versions with different metadata structure. Just try to update and check that issue reproduces.
> > > I'll try to investigate, it reproduces only when the added column has a comment?
> > 
> > 
> > At present, it is found that distributed DDL for updating or deleting columns cannot be executed in some tables,progress 0%
> > Version has been updated to 20.6.
> 
> DB::Exception: Metadata on replica is not up to date with common metadata in Zookeeper. Cannot alter, Stack trace (when copying this message, always include the lines below):

The current situation is that new fields can be added. If the new fields are deleted immediately, some problems may occur. After these problems, all DDL statements will execute exceptions. progress 0%
Restarting the cluster did not solve the problem, so for stability, we migrated the data in the table to a new table and deleted the table
