### ISSUE TITLE
[PATCH] MemoryTracking FreeBSD support

### ISSUE THREAD

**Issue by urgordeadbeef** [ClickHouse/ClickHouse#13859]
Clickhouse for FreeBSD updating no memory usage stats. In the case build without NDEBUG,  allocator use 4KB chunk, those dont account when freeing and MemoryTracking metric grow up to ~6TB, after this clickhouse stop query processing with error "Memory limit (total) exceeded: would use 6.24 TiB" due skipping calc allocation < 4MB

Attached patch against 20.4.8.99 prevent this memory value drifted under FreeBSD.
[patch-memtrack.bsd.txt](https://github.com/ClickHouse/ClickHouse/files/5090608/patch-memtrack.bsd.txt)
[patch-cmake_freebsd_default__libs.cmake.txt](https://github.com/ClickHouse/ClickHouse/files/5090610/patch-cmake_freebsd_default__libs.cmake.txt)

**Comment by ssotik** [comment]
Thanks. Helped for me.

**Comment by olevole** [comment]
There have been several reports from FreeBSD Clickhouse users about this issue. The patches fix the problem and are applied now at the FreeBSD ports level: https://svnweb.freebsd.org/ports?view=revision&revision=548207 for 20.7.2.30 ( https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=249205 ).

Hope to see it upstreamed, thanks!

**Comment by mergar** [comment]
same here:

```
% uname -a
FreeBSD **.org 12.1-RELEASE-p7 FreeBSD 12.1-RELEASE-p7 r363767 GENERIC  amd64
```
Clickhouse version: **20.10.1.4650 (official build)**

Patch solve the issue. @KochetovNicolai any plan to merge #13869 ?

**Comment by alexey-milovidov** [comment]
This task has been abandoned.
