### ISSUE TITLE
Multiple INNER JOIN perfomance (20.6.3.54436)

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#13862]
**Describe the situation**
While executing a query with multiple inner join's clickhouse doesn't use all of the available threads and spends a lot of time in pthread_cond_wait.

**How to reproduce**
Clickhouse 20.6.3.54436
max_threads=32;

```
SELECT
    t.key_1,
    count()
FROM
(
    SELECT
        intDiv(number, 5000000) AS key_1,
        toUInt64(rand() % 75000000) AS key_2
    FROM system.numbers_mt
    LIMIT 15000000000
) AS t
INNER JOIN
(
    SELECT number AS key_1
    FROM numbers(75000000)
    WHERE (number % 5) = 0
) AS t1 ON t.key_1 = t1.key_1
INNER JOIN
(
    SELECT number AS key_2
    FROM numbers(5000000)
    WHERE (number % 5) = 0
) AS t2 ON t.key_2 = t2.key_2
GROUP BY
    t.key_1

601 rows in set. Elapsed: 120.177 sec. Processed 15.08 billion rows, 120.65 GB (125.49 million rows/s., 1.00 GB/s.)
```
Cpu usage limited by ~ 380%.
<img width="1230" alt="firefox_1VacDIWJF1" src="https://user-images.githubusercontent.com/9449405/90527735-8c0ad000-e17a-11ea-8ab4-af120becec28.png">

But if we remove second inner join, performance will increase a lot and clickhouse will use all available cpu(3200%):
```
SELECT
    t.key_1,
    count()
FROM
(
    SELECT
        intDiv(number, 5000000) AS key_1,
        toUInt64(rand() % 75000000) AS key_2
    FROM system.numbers_mt
    LIMIT 15000000000
) AS t
INNER JOIN
(
    SELECT number AS key_1
    FROM numbers(75000000)
    WHERE (number % 5) = 0
) AS t1 ON t.key_1 = t1.key_1
GROUP BY t.key_1
603 rows in set. Elapsed: 8.405 sec. Processed 15.08 billion rows, 120.60 GB (1.79 billion rows/s., 14.35 GB/s.)
```
![изображение](https://user-images.githubusercontent.com/9449405/90529703-afcf1580-e17c-11ea-98ad-05306a580f3e.png)
**Expected performance**
Clickhouse uses more cpu cores with multiple joins.

**Additional context**
On real table data, amount of time spend in pthread_cond_wait variates from 61k samples to 106k samples with different PARTITION BY and ORDER BY.

106k samples in pthread_cond_wait 
PARTITION BY toYYYYMM(date)
ORDER BY (toISOWeek(date), key_2, date)
80 parts
![изображение](https://user-images.githubusercontent.com/9449405/90530649-cd50af00-e17d-11ea-95a4-147119ab1586.png)

61k samples in pthread_cond_wait 
PARTITION BY toYear(date)
ORDER BY (key_2, date)
46 parts
![изображение](https://user-images.githubusercontent.com/9449405/90530624-c629a100-e17d-11ea-9bfa-fe2a7c4cc8f8.png)

**Comment by 4ertus2** [comment]
> flamegraph from debug build

Debug flame graph shows that we are waiting in `PipelineExecutor::executeStepImpl()`

**Comment by w00420043** [comment]
> > Probably need better example.
> 
> It means optimizing the JOIN order is non-trivial :).

Are there any optimization rules similar to reorder join of the computing engine?

**Comment by DoubleWei-go** [comment]
> > Probably need better example.
> 
> It means optimizing the JOIN order is non-trivial :).

Are there any optimization rules similar to reorder join of the computing engine?

**Comment by UnamedRus** [comment]
It looks like it was fixed in master, so that query is using all available threads.

```
SELECT
    t.key_1,
    count()
FROM
(
    SELECT
        intDiv(number, 5000000) AS key_1,
        toUInt64(rand() % 75000000) AS key_2
    FROM system.numbers_mt
    LIMIT 15000000000
) AS t
INNER JOIN
(
    SELECT number AS key_1
    FROM numbers(75000000)
    WHERE (number % 5) = 0
) AS t1 ON t.key_1 = t1.key_1
INNER JOIN
(
    SELECT number AS key_2
    FROM numbers(5000000)
    WHERE (number % 5) = 0
) AS t2 ON t.key_2 = t2.key_2
GROUP BY t.key_1
FORMAT Null

601 rows in set. Elapsed: 120.177 sec. Processed 15.08 billion rows, 120.65 GB (125.49 million rows/s., 1.00 GB/s.) /clickhouse 20.6

607 rows in set. Elapsed: 16.989 sec. Processed 15.08 billion rows, 120.65 GB (887.69 million rows/s., 7.10 GB/s.) /master branch
```
