### ISSUE TITLE
Cannot quickly remove directory brings clickhouse serve down

### ISSUE THREAD

**Issue by mjodeh** [ClickHouse/ClickHouse#13875]
(you don't have to strictly follow this form)

**Describe the bug**
A clear and concise description of what works not as it is supposed to.
Cannot quickly remove directory /var/lib/clickhouse/data/./delete_tmp_20200818_6048_6048_0 by removing files; fallback to recursive removal. Reason: Code: 458, e.displayText() = DB::ErrnoException: Cannot unlink file /var/lib/clickhouse/data/./delete_tmp_20200818_6048_6048_0/checksums.txt, errno: 2, strerror: No such file or directory (version 20.3.8.53)

This brought clickhouse down!

* Which interface to use, if matters
HTTP

**Comment by filimonov** [comment]
Can you check (in the logs /var/log/clickhouse-server )
1) what was happening with that directory before (grep 20200818_6048_6048 )
2) show the stacktrace of error (lines after that error message till next start)

**Comment by mjodeh** [comment]
After updating to 20.3.17.173, it did the same but more severe this time
{f783d746-ab20-43c9-ba2a-14e61628bca7} <Error> executeQuery: Code: 241, e.displayText() = DB::Exception: Memory limit (total) exceeded: would use 26.08 GiB (attempt to allocate chunk of 4502728 bytes), maximum: 26.08 GiB (version 20.3.17.173 (official build)) (from 10.10.104.120:46452) (in query: INSERT INTO .....  FORMAT TabSeparated ), Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::_1::basic_string<char, std::1::char_traits<char>, std::_1::allocator<char> > const&, int) @ 0x1059b460 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::_1::basic_string<char, std::1::char_traits<char>, std::_1::allocator<char> > const&, int) @ 0x8f9972d in /usr/bin/clickhouse
2. ? @ 0x8f98ed9 in /usr/bin/clickhouse
3. MemoryTracker::alloc(long) @ 0x8f96ed3 in /usr/bin/clickhouse
4. MemoryTracker::alloc(long) @ 0x8f96ed3 in /usr/bin/clickhouse
5. MemoryTracker::alloc(long) @ 0x8f96ed3 in /usr/bin/clickhouse
6. DB::CompressedWriteBuffer::CompressedWriteBuffer(DB::WriteBuffer&, std::__1::shared_ptr<DB::ICompressionCodec>, unsigned long) @ 0xce3ca82 in /usr/bin/clickhouse
7. DB::IMergeTreeDataPartWriter::Stream::Stream(std::_1::basic_string<char, std::1::char_traits<char>, std::1::allocator<char> > const&, std::1::shared_ptr<DB::IDisk>, std::1::basic_string<char, std::1::char_traits<char>, std::1::allocator<char> > const&, std::1::basic_string<char, std::1::char_traits<char>, std::1::allocator<char> > const&, std::1::basic_string<char, std::1::char_traits<char>, std::1::allocator<char> > const&, std::1::basic_string<char, std::1::char_traits<char>, std::1::allocator<char> > const&, std::_1::shared_ptr<DB::ICompressionCodec> const&, unsigned long, unsigned long, unsigned long) @ 0xd9e3c62 in /usr/bin/clickhouse
8. ? @ 0xd9eaa77 in /usr/bin/clickhouse
9. DB::DataTypeNullable::enumerateStreams(std::_1::function<void (std::1::vector<DB::IDataType::Substream, std::1::allocator<DB::IDataType::Substream> > const&)> const&, std::1::vector<DB::IDataType::Substream, std::_1::allocator<DB::IDataType::Substream> >&) const @ 0xcf716ba in /usr/bin/clickhouse
10. DB::MergeTreeDataPartWriterWide::MergeTreeDataPartWriterWide(std::_1::shared_ptr<DB::IDisk>, std::1::basic_string<char, std::1::char_traits<char>, std::1::allocator<char> > const&, DB::MergeTreeData const&, DB::NamesAndTypesList const&, std::1::vector<std::1::shared_ptr<DB::IMergeTreeIndex const>, std::1::allocator<std::1::shared_ptr<DB::IMergeTreeIndex const> > > const&, std::1::basic_string<char, std::1::char_traits<char>, std::1::allocator<char> > const&, std::_1::shared_ptr<DB::ICompressionCodec> const&, DB::MergeTreeWriterSettings const&, DB::MergeTreeIndexGranularity const&) @ 0xd9eaee4 in /usr/bin/clickhouse
11. DB::MergeTreeDataPartWide::getWriter(DB::NamesAndTypesList const&, std::_1::vector<std::1::shared_ptr<DB::IMergeTreeIndex const>, std::1::allocator<std::1::shared_ptr<DB::IMergeTreeIndex const> > > const&, std::_1::shared_ptr<DB::ICompressionCodec> const&, DB::MergeTreeWriterSettings const&, DB::MergeTreeIndexGranularity const&) const @ 0xd9d0fe3 in /usr/bin/clickhouse
12. DB::MergedBlockOutputStream::MergedBlockOutputStream(std::_1::shared_ptr<DB::IMergeTreeDataPart const> const&, DB::NamesAndTypesList const&, std::1::vector<std::1::shared_ptr<DB::IMergeTreeIndex const>, std::1::allocator<std::1::shared_ptr<DB::IMergeTreeIndex const> > > const&, std::1::shared_ptr<DB::ICompressionCodec>, std::1::map<std::1::basic_string<char, std::1::char_traits<char>, std::1::allocator<char> >, unsigned long, std::1::less<std::1::basic_string<char, std::1::char_traits<char>, std::1::allocator<char> > >, std::1::allocator<std::1::pair<std::1::basic_string<char, std::1::char_traits<char>, std::_1::allocator<char> > const, unsigned long> > > const&, unsigned long, bool) @ 0xdada360 in /usr/bin/clickhouse
13. DB::MergedBlockOutputStream::MergedBlockOutputStream(std::_1::shared_ptr<DB::IMergeTreeDataPart const> const&, DB::NamesAndTypesList const&, std::1::vector<std::1::shared_ptr<DB::IMergeTreeIndex const>, std::1::allocator<std::1::shared_ptr<DB::IMergeTreeIndex const> > > const&, std::_1::shared_ptr<DB::ICompressionCodec>, bool) @ 0xdada723 in /usr/bin/clickhouse
14. DB::MergeTreeDataWriter::writeTempPart(DB::BlockWithPartition&) @ 0xda1c483 in /usr/bin/clickhouse
15. DB::MergeTreeBlockOutputStream::write(DB::Block const&) @ 0xd91f025 in /usr/bin/clickhouse
16. DB::PushingToViewsBlockOutputStream::write(DB::Block const&) @ 0xd10b6d0 in /usr/bin/clickhouse
17. DB::SquashingBlockOutputStream::writeSuffix() @ 0xd11963a in /usr/bin/clickhouse
18. DB::copyData(DB::IBlockInputStream&, DB::IBlockOutputStream&, std::__1::atomic<bool>*) @ 0xcecd3de in /usr/bin/clickhouse
19. DB::NullAndDoCopyBlockInputStream::readImpl() @ 0xd104f5a in /usr/bin/clickhouse
20. DB::IBlockInputStream::read() @ 0xce8e68f in /usr/bin/clickhouse
21. DB::copyData(DB::IBlockInputStream&, DB::IBlockOutputStream&, std::__1::atomic<bool>*) @ 0xcecd2b3 in /usr/bin/clickhouse
22. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, DB::Context&, std::_1::function<void (std::1::basic_string<char, std::1::char_traits<char>, std::1::allocator<char> > const&, std::1::basic_string<char, std::1::char_traits<char>, std::1::allocator<char> > const&, std::1::basic_string<char, std::1::char_traits<char>, std::1::allocator<char> > const&, std::1::basic_string<char, std::1::char_traits<char>, std::_1::allocator<char> > const&)>) @ 0xd5a18df in /usr/bin/clickhouse
23. DB::HTTPHandler::processQuery(DB::Context&, Poco::Net::HTTPServerRequest&, HTMLForm&, Poco::Net::HTTPServerResponse&, DB::HTTPHandler::Output&) @ 0x90448a8 in /usr/bin/clickhouse
24. DB::HTTPHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&) @ 0x9047cee in /usr/bin/clickhouse
25. Poco::Net::HTTPServerConnection::run() @ 0xe3d2bf4 in /usr/bin/clickhouse
26. Poco::Net::TCPServerConnection::start() @ 0xe402b9b in /usr/bin/clickhouse
27. Poco::Net::TCPServerDispatcher::run() @ 0xe40301d in /usr/bin/clickhouse
28. Poco::PooledThread::run() @ 0x106295c7 in /usr/bin/clickhouse
29. Poco::ThreadImpl::runnableEntry(void*) @ 0x106253cc in /usr/bin/clickhouse
30. ? @ 0x10626d6d in /usr/bin/clickhouse
31. start_thread @ 0x7e65 in /usr/lib64/libpthread-2.17.so

**Comment by mjodeh** [comment]
{f783d746-ab20-43c9-ba2a-14e61628bca7} <Error> executeQuery: Code: 241, e.displayText() = DB::Exception: Memory limit (total) exceeded: would use 26.08 GiB (attempt to allocate chunk of 4502728 bytes), maximum: 26.08 GiB (version 20.3.17.173 (official build)) (from 10.10.104.120:46452) (in query: INSERT INTO .... FORMAT TabSeparated ), Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x1059b460 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x8f9972d in /usr/bin/clickhouse
2. ? @ 0x8f98ed9 in /usr/bin/clickhouse
3. MemoryTracker::alloc(long) @ 0x8f96ed3 in /usr/bin/clickhouse
4. MemoryTracker::alloc(long) @ 0x8f96ed3 in /usr/bin/clickhouse
5. MemoryTracker::alloc(long) @ 0x8f96ed3 in /usr/bin/clickhouse
6. DB::CompressedWriteBuffer::CompressedWriteBuffer(DB::WriteBuffer&, std::__1::shared_ptr<DB::ICompressionCodec>, unsigned long) @ 0xce3ca82 in /usr/bin/clickhouse
7. DB::IMergeTreeDataPartWriter::Stream::Stream(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::IDisk>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::ICompressionCodec> const&, unsigned long, unsigned long, unsigned long) @ 0xd9e3c62 in /usr/bin/clickhouse
8. ? @ 0xd9eaa77 in /usr/bin/clickhouse
9. DB::DataTypeNullable::enumerateStreams(std::__1::function<void (std::__1::vector<DB::IDataType::Substream, std::__1::allocator<DB::IDataType::Substream> > const&)> const&, std::__1::vector<DB::IDataType::Substream, std::__1::allocator<DB::IDataType::Substream> >&) const @ 0xcf716ba in /usr/bin/clickhouse
10. DB::MergeTreeDataPartWriterWide::MergeTreeDataPartWriterWide(std::__1::shared_ptr<DB::IDisk>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::MergeTreeData const&, DB::NamesAndTypesList const&, std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeIndex const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeIndex const> > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::ICompressionCodec> const&, DB::MergeTreeWriterSettings const&, DB::MergeTreeIndexGranularity const&) @ 0xd9eaee4 in /usr/bin/clickhouse
11. DB::MergeTreeDataPartWide::getWriter(DB::NamesAndTypesList const&, std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeIndex const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeIndex const> > > const&, std::__1::shared_ptr<DB::ICompressionCodec> const&, DB::MergeTreeWriterSettings const&, DB::MergeTreeIndexGranularity const&) const @ 0xd9d0fe3 in /usr/bin/clickhouse
12. DB::MergedBlockOutputStream::MergedBlockOutputStream(std::__1::shared_ptr<DB::IMergeTreeDataPart const> const&, DB::NamesAndTypesList const&, std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeIndex const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeIndex const> > > const&, std::__1::shared_ptr<DB::ICompressionCodec>, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned long, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, unsigned long> > > const&, unsigned long, bool) @ 0xdada360 in /usr/bin/clickhouse
13. DB::MergedBlockOutputStream::MergedBlockOutputStream(std::__1::shared_ptr<DB::IMergeTreeDataPart const> const&, DB::NamesAndTypesList const&, std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeIndex const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeIndex const> > > const&, std::__1::shared_ptr<DB::ICompressionCodec>, bool) @ 0xdada723 in /usr/bin/clickhouse
14. DB::MergeTreeDataWriter::writeTempPart(DB::BlockWithPartition&) @ 0xda1c483 in /usr/bin/clickhouse
15. DB::MergeTreeBlockOutputStream::write(DB::Block const&) @ 0xd91f025 in /usr/bin/clickhouse
16. DB::PushingToViewsBlockOutputStream::write(DB::Block const&) @ 0xd10b6d0 in /usr/bin/clickhouse
17. DB::SquashingBlockOutputStream::writeSuffix() @ 0xd11963a in /usr/bin/clickhouse
18. DB::copyData(DB::IBlockInputStream&, DB::IBlockOutputStream&, std::__1::atomic<bool>*) @ 0xcecd3de in /usr/bin/clickhouse
19. DB::NullAndDoCopyBlockInputStream::readImpl() @ 0xd104f5a in /usr/bin/clickhouse
20. DB::IBlockInputStream::read() @ 0xce8e68f in /usr/bin/clickhouse
21. DB::copyData(DB::IBlockInputStream&, DB::IBlockOutputStream&, std::__1::atomic<bool>*) @ 0xcecd2b3 in /usr/bin/clickhouse
22. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, DB::Context&, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>) @ 0xd5a18df in /usr/bin/clickhouse
23. DB::HTTPHandler::processQuery(DB::Context&, Poco::Net::HTTPServerRequest&, HTMLForm&, Poco::Net::HTTPServerResponse&, DB::HTTPHandler::Output&) @ 0x90448a8 in /usr/bin/clickhouse
24. DB::HTTPHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&) @ 0x9047cee in /usr/bin/clickhouse
25. Poco::Net::HTTPServerConnection::run() @ 0xe3d2bf4 in /usr/bin/clickhouse
26. Poco::Net::TCPServerConnection::start() @ 0xe402b9b in /usr/bin/clickhouse
27. Poco::Net::TCPServerDispatcher::run() @ 0xe40301d in /usr/bin/clickhouse
28. Poco::PooledThread::run() @ 0x106295c7 in /usr/bin/clickhouse
29. Poco::ThreadImpl::runnableEntry(void*) @ 0x106253cc in /usr/bin/clickhouse
30. ? @ 0x10626d6d in /usr/bin/clickhouse
31. start_thread @ 0x7e65 in /usr/lib64/libpthread-2.17.so

**Comment by mjodeh** [comment]
we 48 cpu cores, 32 GB of ram

**Comment by mjodeh** [comment]
@den-crane I update to 20.3.17.173 to weeks ago and at the beginning it worked perfectly, and starting from yesterday we are getting `Cannot quickly remove` and `Memory limit exceeded` exceptions, and yesterday those brought the server down! and the file system was also corrupted!
now the insertion rate is 1 bulk insertion per second

**Comment by den-crane** [comment]
> file system was also corrupted

What do you mean by that? CH is a userlevel application. It cannot corrupt FS.
What FS do you use, BTW ?

**Comment by mjodeh** [comment]
> What FS do you use, BTW ?

xfs

**Comment by mjodeh** [comment]
> What do you mean by that? CH is a userlevel application. It cannot corrupt FS.

It might do it if the file cache is too big, I don't know I'm just guessing what happened
and the insertion rate was 20 bulk insertion per second and the bulk size did not exceed 2000 rows

**Comment by mjodeh** [comment]
Any suggestions to overcome those two errors? `Cannot quickly remove` and `Memory limit exceeded`?
I updated the merge config like this
`<merge_tree>
        <max_suspicious_broken_parts>5</max_suspicious_broken_parts>
        <parts_to_delay_insert>300</parts_to_delay_insert>
        <parts_to_throw_insert>600</parts_to_throw_insert>
    </merge_tree>`
Engine we use is `MergeTree` and data is `partitioned daily` also tested the `monthly partitioning` and it has the same behavior keeps throwing those 2 errors
`ClickHouse server version 20.3.17 revision 54433`

**Comment by den-crane** [comment]
Check how much memory CH is uses -- RES htop/top

**Comment by mjodeh** [comment]
> It might do it if the file cache is too big, I don't know I'm just guessing what happened

`from top`
 `  clickho+  20   0  279.8g   4.7g  40932 S   0.3 13.4   1489:08 clickhouse-serv`

`free -h`
Mem:            35G         12G        8.8G         46M         13G         21G
Swap:            0B          0B          0B

`df -Th`: size `199G` used `82G` avail `118G` type `xfs`

**Comment by den-crane** [comment]
> 4.7g

quite small 

Do you have some graphs? To see how 4.7 changes.

**Comment by mjodeh** [comment]
Unfortunately it was not added to the monitoring we will add it to track the memory usage of CH
But from log checking the following happened
1- Merges are too slow (for almost 1 hour)
then loops between
2- Cannot quickly remove directory
3- Memory limit exceeded
it looped for 3 hours then the server went down
this happened at night in which the traffic is at its minimum the bulk size won't even reach 100 whereas at its peek when it reaches 2k/sec it did not even hit any of those errors!

**Comment by mjodeh** [comment]
log sample https://github.com/ClickHouse/ClickHouse/issues/13875#issuecomment-679441776

**Comment by den-crane** [comment]
What API do  you use for "in query: INSERT INTO .... FORMAT TabSeparated )" ? JDBC ?

**Comment by mjodeh** [comment]
> What API do you use for "INSERT INTO .... FORMAT TabSeparated " ?  

Yes

> JDBC ?  

No I use Node js https://github.com/TimonKK/clickhouse

**Comment by mjodeh** [comment]
`iowait` on the server jumps suddenly from 4% to 88% and then the `Memory Limit Exceeded` exception is fired after that the server is down.
Also the `context switch` starts rising from 3.2 ksps to 13 ksps and suddenly drops to 0!
1 - Does the partitioning `daily` or `monthly` affect iowait time?
2- We have about 150 bulk insertions on 90 different dbs per minute, the bulk size on average is small, so we multiple mini insertions on different dbs (we simulated a single db and did not have an issue), also the tables are daily partitioned, we think of using [Compact Format](https://github.com/ClickHouse/ClickHouse/issues/14764), does it help?

**Comment by mjodeh** [comment]
@filimonov 
After the server went down and the `fs` was repaired it takes too long time till it's up, till now it took more than `30 hours` and the service is up but can not connect to it, and the logs it has is exactly https://github.com/ClickHouse/ClickHouse/issues/13875#issue-681555416 on all databases, is there anything can be done to increase its boot?

**Comment by alexey-milovidov** [comment]
1. The issue may happen if you have huge number of data parts and low amount of memory.
2. The performance of directory removal was fixed in version 21.2 here https://github.com/ClickHouse/ClickHouse/pull/19086.
3. With daily partitions you will have more data parts and this is bad for server startup - monthly partitioning is preferred.
4. Compact format is enabled by default in recent versions for small data parts and it will help.
