### ISSUE TITLE
Is there a plan to consider adding settings "min_compress_block_size" and "max_compress_block_size" for each MergeTable ranther than in the global settings?

### ISSUE THREAD

**Issue by wangxi19** [ClickHouse/ClickHouse#13890]
I want to these:

create table tbnm( field1 Int32) ENGINE = MergeTree() SETTINGS min_compress_block_size = 12345, max_compress_block_size = 123456, index_granularity = 10

**Comment by wangxi19** [comment]
Hope you get a glimpse of me

**Comment by alexey-milovidov** [comment]
Yes, it will be way more natural to have these settings in MergeTreeSettings.

But these settings are "expert level" - rarely needed to be changed and attempt to change often makes things worse.

**Comment by alexey-milovidov** [comment]
Proposal: add settings to MergeTreeSettings. They will have higher priority than the global settings and take effect when they are set.

**Comment by ucasFL** [comment]
> Proposal: add settings to MergeTreeSettings. They will have higher priority than the global settings and take effect when they are set.

Hi, How can this be tested? @alexey-milovidov

**Comment by alexey-milovidov** [comment]
@ucasFL You can test that table size will be slightly lower (after OPTIMIZE) if min_compress_block_size is larger.
