### ISSUE TITLE
Allowed to pass an empty string as timezone-parameter

### ISSUE THREAD

**Issue by vladimir-golovchenko** [ClickHouse/ClickHouse#13908]
**Describe the bug**

```sql
SELECT toStartOfMinute(now(), '')
```

```text
┌─toStartOfMinute(now(), '')─┐
│        2020-08-20 00:16:00 │
└────────────────────────────┘
```

**Expected behavior**
I would throw an exception.

**Comment by den-crane** [comment]
SELECT toStartOfMinute(now(), '')

Received exception from server (version 20.9.3):
Code: 43. DB::Exception: Received from localhost:9000. DB::Exception: Function toStartOfMinute supports a 2nd argument (optional) that must be non-empty and be a valid time zone.

Fixed in #14509
