### ISSUE TITLE
Materialized view has wrong data after ALTER TABLE tablename DELETE WHERE colname = 'SomeValue'

### ISSUE THREAD

**Issue by davidcsisk** [ClickHouse/ClickHouse#13931]
(you don't have to strictly follow this form)

**Describe the bug**
Any materialized views on table that has had an ALTER TABLE...DELETE WHERE...run against it has the old data still visible in it.   I would assume this is also true if an ALTER TABLE...UPDATE WHERE...has been run.  The version I'm using is 20.6.3.28.

**How to reproduce**
1) Create a table with MergeTree engine.
2) Load some data.
3) Create a materialized view from that table.
4) Issue the ALTER TABLE...DELETE FROM...on some subset of rows in the underlying table.
5) Query the materialized view...the rows deleted from the base table will still be returned.

* Which ClickHouse server version to use
20.6.3.28
* Which interface to use, if matters
Doesn't matter.
* Non-default settings, if any
Non-default port...shouldn't matter.
* `CREATE TABLE` statements for all tables involved
1) create table covid_data_stage (date Date, county LowCardinality(String), state LowCardinality(String), fips String, cases UInt32, deaths UInt32) ENGINE = MergeTree ORDER BY (date, county, state);
2) wget https://covid19-lake.s3.us-east-2.amazonaws.com/rearc-covid-19-nyt-data-in-usa/csv/us-counties/us-counties.csv
3) cat us-counties.csv | tail -n +2 | clickhouse-client -d test1 --port 9001 --query "INSERT INTO covid_data_stage FORMAT CSV"
4) create table covid_data_daily ENGINE = MergeTree ORDER BY (date, county, state) as select b.state, b.county, b.fips, b.date, b.cases today_cum_cases, b.deaths today_cum_deaths, (b.cases - a.cases) today_new_cases, (b.deaths - a.deaths) today_new_deaths from covid_data1 b join covid_data1 a on (b.state = a.state and b.county = a.county and subtractDays(b.date,1) = a.date) order by state, county, date;
5) select toYear(date) year, toWeek(date) iso_week, state, sum(today_new_cases) total_new_reported_cases, sum(today_new_deaths) total_new_reported_deaths from covid_data_daily where state = 'North Carolina' group by toYear(date), toWeek(date), state order by toYear(date) desc, toWeek(date) desc;
6) CREATE MATERIALIZED VIEW mv_covid_data_byweek \
ENGINE = SummingMergeTree \
PARTITION BY (year) ORDER BY (state, week, year) \ 
POPULATE \
AS SELECT \
 toYear(date) year, toWeek(date) week, state, sum(today_new_cases) total_new_reported_cases, sum(today_new_deaths) total_new_reported_deaths \
 from covid_data_daily group by toYear(date), toWeek(date), state; 
7) select * from mv_covid_data_byweek where state = 'North Carolina' order by year desc, week desc;
8) ALTER TABLE covid_data_daily DELETE WHERE state = 'North Carolina';
9) select * from mv_covid_data_byweek where state = 'North Carolina' order by year desc, week desc;

* Sample data for all these tables, use [clickhouse-obfuscator]
wget https://covid19-lake.s3.us-east-2.amazonaws.com/rearc-covid-19-nyt-data-in-usa/csv/us-counties/us-counties.csv
* Queries to run that lead to unexpected result
select toYear(date) year, toWeek(date) iso_week, state, sum(today_new_cases) total_new_reported_cases, sum(today_new_deaths) total_new_reported_deaths from covid_data_daily where state = 'North Carolina' group by toYear(date), toWeek(date), state order by toYear(date) desc, toWeek(date) desc;
select * from mv_covid_data_byweek where state = 'North Carolina' order by year desc, week desc;
**Expected behavior**
The results returned from the materialized view should reflect the rows deleted from the base table (or updated in the base table).  I do realize this fix could be some pretty involved code.
A short term work-around fix would be to provide a means to force a refresh of the materialized view without having to drop and re-created the materialized view...for instance, an 'ALTER MATERIALIZE VIEW mv_name REFRESH;' that truncates the view table and re-inserts the correct data without needing to completely drop and re-create the MV.
**Error message and/or stacktrace**

**Additional context**

**Comment by den-crane** [comment]
Materialized view (MV) is a post-insert trigger. Insert to a source table pushes an inserted buffer to MV as well.
MV does select over the inserted buffer (MV never reads the source table except populate stage).

MV does not see `alter update/delete`.
MV does not see changes changes from merge process collapsing/replacing.

No transactions. No atomicity. Partial insert is possible.
Insert into the source table can succeed and fail into MV. A client will gate an error message in this case.

duplicate: https://github.com/ClickHouse/ClickHouse/issues/12415

**Comment by davidcsisk** [comment]
Thank you for the quick reply.  So, would it also be true then that materialized views won't see rows deleted because of TTL settings on the underlying table?  That's also handled by the merge process, correct? It sure seems that there needs to be a simple way to at least force a refresh of a materialized view without needing to completely drop/re-create the materialized view.  An ALTER MATERIALIZED VIEW REFRESH would be sufficient for most cases, I believe.

**Comment by den-crane** [comment]
>So, would it also be true then that materialized views won't see rows deleted because of TTL settings on the underlying table? That's also handled by the merge process, correct? 

Correct.

>It sure seems that there needs to be a simple way to at least force a refresh of a materialized view without needing to completely drop/re-create the materialized view. An ALTER MATERIALIZED VIEW REFRESH would be sufficient for most cases, I believe.

vote for this here https://github.com/ClickHouse/ClickHouse/issues/3685
