### ISSUE TITLE
Input format for Json

### ISSUE THREAD

**Issue by divyankgarg** [ClickHouse/ClickHouse#13968]
{"DEVICE_GROUP":null,"DEVICE":"10.84.130.44","RULE":"check-in-traffic","TOPIC1":"interface.statistics","FIELDS_HIGH_THRESHOLD":800000000,"FIELDS_LOW_THRESHOLD":500000000,"FIELDS_OUT_OCTETS_STATS_VALUE":null,"FIELDS_TANDINGESTTIMESTAMP":1598127990844870700,"FIELDS_TANDTIMEOFFSET":"719.508643ms","KEYS_INTERFACE_NAME":"em3","KEYS_PLAYBOOK_NAME":"interface-kpis-playbook","KEYS_INSTANCE_ID":"[\"i1\"]"

Above is the Json i am getting from Kafka. I am able to create table using most of the keys just want to know what data type should I provide for KEYS_INSTANCE_ID and DEVICE_GROUP to create table using MergerTree and Kafka engine using Materialized view. I tried string and Nullable(String) respectively but didn't worked for me for creating the table.

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/13957
