### ISSUE TITLE
JSONExtract returns 0 for numbers with floating-point for type float / Float32

### ISSUE THREAD

**Issue by vladimir-golovchenko** [ClickHouse/ClickHouse#13962]
**Describe the bug**

JSONExtract returns 0 for numbers with floating-point for type *float / Float32*.

**How to reproduce**

```sql
WITH '{ "v":1.1}' AS raw
SELECT 
    JSONExtract(raw, 'v', 'float') AS float32_1,
    JSONExtract(raw, 'v', 'Float32') AS float32_2,
    JSONExtractFloat(raw, 'v') AS float64_1,
    JSONExtract(raw, 'v', 'double') AS float64_2

/*
┌─float32_1─┬─float32_2─┬─float64_1─┬─float64_2─┐
│         0 │         0 │       1.1 │       1.1 │
└───────────┴───────────┴───────────┴───────────┘
*/
```

```sql
WITH '{ "v":1E-2}' AS raw
SELECT 
    JSONExtract(raw, 'v', 'float') AS float32_1,
    JSONExtract(raw, 'v', 'Float32') AS float32_2,
    JSONExtractFloat(raw, 'v') AS float64_1,
    JSONExtract(raw, 'v', 'double') AS float64_2

/*
┌─float32_1─┬─float32_2─┬─float64_1─┬─float64_2─┐
│         0 │         0 │      0.01 │      0.01 │
└───────────┴───────────┴───────────┴───────────┘
*/
```

**Expected behavior**

I think either need to add support *float / Float32* type or throw an exception to point to need to use *double / Float64* type.

**Additional context**
CH v. 20.6.4.44

**Comment by alexey-milovidov** [comment]
@vitlibar Maybe you can help?

**Comment by alexey-milovidov** [comment]
The reason is quite stupid: 0.1 in JSON is treat as double and Float64(0.1) is not representable in Float32.

**Comment by alexey-milovidov** [comment]
Also note that we do accurate conversions to integers. Example: `JSONExtract('{"v":1.1}', 'v', 'UInt64')` will return 0 and `JSONExtract('{"v":1.1}', 'v', 'Nullable(UInt64)')` will return NULL.
