### ISSUE TITLE
Pipe(line) involving both a Concat and a Copy transform _may_ break the PipelineExecutor

### ISSUE THREAD

**Issue by markpapadakis** [ClickHouse/ClickHouse#13994]
I've been thinking about this situation, and I think it is likely a Pipeline defined as described below may break the PipelineExecutor.

Suppose you have an `ISource` providing chunks to a CopyTransform, which in turn duplicates the chunks to a Concat, which eventually forwards everything to a`PullingOutputFormat`, like so:

![image](https://user-images.githubusercontent.com/222134/91032524-bccf8700-e60a-11ea-8faf-1b9b3507e38d.png)

I think that in such pipelines, where concat and copy transforms are both included, the executor will stop prematurely based on their respective prepare() implementations. I should probably put this to the test by writing some code to test this hypothesis, but I thought I 'd submit this here in case someone can tell me that I am flat out wrong so that I wouldn't need to go through this  :)

**Comment by KochetovNicolai** [comment]
I expect that such a pipeline will never stop execution (or, probably, will stuck).
In general, it's possible that ill-formed pipeline will stuck or go into infinite loop. Pipeline may also depend on data it reads. Code which creates pipeline is responsible creating correct pipelines.
