### ISSUE TITLE
how to create mysqlengine database in 20.8

### ISSUE THREAD

**Issue by l1t1** [ClickHouse/ClickHouse#14008]
I copy the command from the document, but failed, please help

```
]# clickhouse-client
ClickHouse client version 20.8.1.4447 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 20.8.1 revision 54438.

VM_0_52_centos :)  CREATE DATABASE mysql_db ENGINE = MySQL('localhost:3306', 't', 'root', 'A123b_456');

CREATE DATABASE mysql_db
ENGINE = MySQL('localhost:3306', 't', 'root', 'A123b_456')


Received exception from server (version 20.8.1):
Code: 501. DB::Exception: Received from localhost:9000. DB::Exception: Cannot create MySQL database, because Poco::Exception. Code: 1000, e.code() = 2002, e.displayText() = mysqlxx::ConnectionFailed: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2) ((nullptr):0),

0 rows in set. Elapsed: 0.017 sec.
```
the mysql client can connect the mysql server
```
]# mysql -h localhost -uroot -pA123b_456 -A t
mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 28
Server version: 5.7.31 MySQL Community Server (GPL)

Copyright (c) 2000, 2020, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> exit;
Bye
```

Make sure to check documentation https://clickhouse.yandex/docs/en/ first. If the question is concise and probably has a short answer, asking it in Telegram chat https://telegram.me/clickhouse_en is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

If you still prefer GitHub issues, remove all this text and ask your question here.

**Comment by zhang2014** [comment]
Maybe you can try:
```sql
CREATE DATABASE mysql_db ENGINE = MySQL('127.0.0.1:3306', 't', 'root', 'A123b_456');
```

**Comment by l1t1** [comment]
it works, thank, but why? is the document's content wrong?
```
VM_0_52_centos :)  CREATE DATABASE mysql_db ENGINE = MySQL('127.0.0.1:3306', 't', 'root', 'A123b_456');

CREATE DATABASE mysql_db
ENGINE = MySQL('127.0.0.1:3306', 't', 'root', 'A123b_456')

Ok.

0 rows in set. Elapsed: 0.094 sec.
```

**Comment by zhang2014** [comment]
By default, MySQL uses UNIX socket to process to `localhost` client.(For some distribution formats, the directory might be different, such as /var/lib/mysql for RPMs.)

This may need to fixed in ClickHouse.
See for more information: https://dev.mysql.com/doc/refman/8.0/en/problems-with-mysql-sock.html, https://dev.mysql.com/doc/c-api/5.7/en/mysql-real-connect.html

**Comment by l1t1** [comment]
ok.

**Comment by bkarlson** [comment]
wow, spent 1 hour debugging this, what a nasty bug
