### ISSUE TITLE
Too many parts (600) on cluster

### ISSUE THREAD

**Issue by mjodeh** [ClickHouse/ClickHouse#14007]
**Describe the bug**
`Too many parts (600) exception` on a 4 shards cluster, the insertion rate at peak is `20 insertions each insertion is on a single database`. The infrastructure we have is `HAPROXY for load balancing` in front of the shards and we are using the` http` interface

* Which ClickHouse server version to use
`20.3.17.173`
* Which interface to use, if matters
`http`

Ideally an `n` shards cluster how many insertions can it handle per second?
does the rule of `1 insert/sec` stay or can be extended to more?
does the insertion rate increase linearly with the number of shards using the described infrastructure?

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/13360

**Comment by den-crane** [comment]
Do you still run `optimize table` manually ? If yes then don't do it.

Can you show a table DDL and example of your insert query? How many rows do you insert by  one query?

**Comment by mjodeh** [comment]
Do you still run optimize table manually ? If yes then don't do it.
No

How many rows do you insert by one query?
between 1 and 1k rows every 10 seconds per database, it depends on the traffic

CREATE TABLE db.mainTableSingle (`userId` String, `eventTime` UInt32 CODEC(DoubleDelta), `eventName` LowCardinality(String), `registerTs` Nullable(String), `installDate` Nullable(String), `launchCount` Nullable(Float64), `osVersion` Nullable(String), `deviceModel` Nullable(String), `segments` Array(Nullable(String)), `appId` Nullable(String), `deviceType` Nullable(String), `timeZone` Nullable(String), `tokenStatus` Nullable(String), `locale` Nullable(String), `clientVersion` Nullable(String), `deviceManufacturer` Nullable(String), `screenResolution` Nullable(String), `defaultTracker` Nullable(String), `tags` Array(Nullable(String)), `trackerId` Nullable(String), `trackerName` Nullable(String), `adNetwork` Nullable(String), `deviceId` Nullable(String), `key_8886442f75e0fba45dc440fa5359f334f01fe1c7` Nullable(String), `key_69b03f8cfe9d35dcbb26d95cda5cd16342548a01` Nullable(String), `key_81cd27f15f74059cea2763f142886ea150215c65` Nullable(String), `key_c692273deb2772da307ffe37041fef77bf4baa97` Nullable(Float64), `isGuest` Nullable(UInt8), `key_6421a0e2c7c43863279c51780d4d1a74f17e02cb` Nullable(String), `key_4900980a88faa36eb26a5ec5547b8fa81b5978c5` Nullable(String), `adGroup` Nullable(String), `creative` Nullable(String), `campaignName` Nullable(String), `key_07b3437e71e92b1351d4b94ca477c53b8ba76486` Nullable(Float64), `key_3cce7314ec7648a242815bdafbbf8e36434ecb88` Array(Nullable(String)), `key_496b2ea321013ccf081e15f4ed49128dc03fe016` Nullable(Float64), `key_a24872eb8859ee8bf5bfe25740d15ba561ff7c79` Array(Nullable(String)), `key_1dbc255e423606edfba84a8c309aa6a0990e0be7` Nullable(Float64), `key_d74701f013cec2e6c95cbff9781c9bc5f074e11d` Nullable(String), `key_1e086b67ed7b8aef764640b8f70c979cc9d27390` Nullable(String), `key_3b68c56c17280aa3bd61f85b2c6646bf154201b3` Nullable(String), `key_e9168ad8fa483ed1d09a2d2030fc9390a14f4daf` Nullable(String)) ENGINE = Distributed('ShardedAndReplicated', 'db', 'local', rand())

and the local table:

CREATE TABLE db.local (`userId` String, `eventTime` UInt32 CODEC(DoubleDelta), `eventName` LowCardinality(String), `registerTs` Nullable(String), `installDate` Nullable(String), `launchCount` Nullable(Float64), `osVersion` Nullable(String), `deviceModel` Nullable(String), `segments` Array(Nullable(String)), `appId` Nullable(String), `deviceType` Nullable(String), `timeZone` Nullable(String), `tokenStatus` Nullable(String), `locale` Nullable(String), `clientVersion` Nullable(String), `deviceManufacturer` Nullable(String), `screenResolution` Nullable(String), `defaultTracker` Nullable(String), `tags` Array(Nullable(String)), `trackerId` Nullable(String), `trackerName` Nullable(String), `adNetwork` Nullable(String), `deviceId` Nullable(String), `key_8886442f75e0fba45dc440fa5359f334f01fe1c7` Nullable(String), `key_69b03f8cfe9d35dcbb26d95cda5cd16342548a01` Nullable(String), `key_81cd27f15f74059cea2763f142886ea150215c65` Nullable(String), `key_c692273deb2772da307ffe37041fef77bf4baa97` Nullable(Float64), `isGuest` Nullable(UInt8), `key_6421a0e2c7c43863279c51780d4d1a74f17e02cb` Nullable(String), `key_4900980a88faa36eb26a5ec5547b8fa81b5978c5` Nullable(String), `adGroup` Nullable(String), `creative` Nullable(String), `campaignName` Nullable(String), `key_07b3437e71e92b1351d4b94ca477c53b8ba76486` Nullable(Float64), `key_3cce7314ec7648a242815bdafbbf8e36434ecb88` Array(Nullable(String)), `key_496b2ea321013ccf081e15f4ed49128dc03fe016` Nullable(Float64), `key_a24872eb8859ee8bf5bfe25740d15ba561ff7c79` Array(Nullable(String)), `key_1dbc255e423606edfba84a8c309aa6a0990e0be7` Nullable(Float64), `key_d74701f013cec2e6c95cbff9781c9bc5f074e11d` Nullable(String), `key_1e086b67ed7b8aef764640b8f70c979cc9d27390` Nullable(String), `key_3b68c56c17280aa3bd61f85b2c6646bf154201b3` Nullable(String), `key_e9168ad8fa483ed1d09a2d2030fc9390a14f4daf` Nullable(String)) ENGINE = ReplicatedMergeTree('/clickhouse/ShardedAndReplicated/tables/db.local/{shard}', '{replica}') PARTITION BY toYYYYMM(toDateTime(eventTime)) ORDER BY (userId, eventTime, eventName) SETTINGS index_granularity = 8192

**Comment by mjodeh** [comment]
stopped the insertion and executed `select database, table, future_parts, parts_to_check, queue_size, inserts_in_queue, merges_in_queue from system.replicas` and all columns were `0`s and still the CH error logs shows `too many parts` exceptions

**Comment by mjodeh** [comment]
`select database, table, progress, partition_id, num_parts from system.merges` always have 16
system                 │ metric_log │                   0                 │ 202009       │        91
system                 │ trace_log   │  0.9829424307036247 │ 202009       │        93

This is on 2 shards whereas the other 2 shards have an empty merges table!
