### ISSUE TITLE
How to set: joined_subquery_requires_alias=0 in config.xml

### ISSUE THREAD

**Issue by mvcalder-xbk** [ClickHouse/ClickHouse#14009]
We recently upgraded our Clickhouse server and started getting: 

```
DB::Exception: No alias for subquery or table function in JOIN (set joined_subquery_requires_alias=0 to disable restriction).
```

I can change this setting in the command line client, but I want to change it in the server's config.xml. I've tried putting it under the `<yandex>` tag, and under the default user profile but neither work. Is there some special tagging that needs to be used around this specific setting? Thanks,

Matt

**Comment by den-crane** [comment]
Not config.xml
This parameter must be set in users profile in users.xml

for example
```

cat any_join_distinct_right_table_keys.xml
<?xml version="1.0"?>
<yandex>
    <profiles>
        <default>
            <any_join_distinct_right_table_keys>1</any_join_distinct_right_table_keys>
	    <joined_subquery_requires_alias>0</joined_subquery_requires_alias>
        </default>
    </profiles>
</yandex>
```

**Comment by mvcalder-xbk** [comment]
@den-crane thanks.
