### ISSUE TITLE
DB::NetException: Host not found: (container Id) - after correct by-name connections

### ISSUE THREAD

**Issue by xmariachi** [ClickHouse/ClickHouse#14018]
**Describe the bug**
 
I have a program that is intended to perform some consolidation of data and run periodically.
It moves data from "daily" tables to "historical" tables, running OPTIMIZE on them before it. They all are ReplicatedReplacingMergeTree. 
I am running a three-instances cluster that are running full replicas.

I am using `com.ecwid` Clickhouse Client in a Scala application to perform these operations. The instances are running on docker.
I can run a number of operations, but at some point, I find the issue below.
I have tried creating an HttpTransport and from it, a raw or typed client (depending) on every operation, so connection problems should be left out of it or highly reduced.

```
Exception in thread "main" com.ecwid.clickhouse.ClickHouseHttpException: HTTP 500 (Internal Server Error): Code: 210, e.displayText() = DB::NetException: Host not found: 6cf503fe389f (6cf503fe389f:9000) 
```
Clickhouse URL connection string, and server configuration, is domain-based(e.g. `clickhouse-1.mycluster.com,clickhouse-1.mycluster.com,`), not container-id based, like it is suggested here.

What can be causing it to change connection to a container? 
Locally, with a 1-replica cluster, I'm unable to reproduce. Seems to be related to domain name connection.

Logs: 

```
17:26:58.985 [main] INFO  c.d.d.c.c.ClickhouseConsolidatorSync - Calling: ALTER TABLE db.pageviews_data_daily DETACH PARTITION 20200812 
17:26:59.020 [main] INFO  c.d.d.c.c.ClickhouseConsolidatorSync - DETACHED DAILY PARTITION: 20200812
17:26:59.020 [main] INFO  c.d.d.c.c.ClickhouseConsolidatorSync - Calling: ALTER TABLE db.pageviews_data_daily DETACH PARTITION 20200814 
17:26:59.055 [main] INFO  c.d.d.c.c.ClickhouseConsolidatorSync - DETACHED DAILY PARTITION: 20200814
17:26:59.055 [main] INFO  c.d.d.c.c.util.LogicUtils$ - Run DETACHED DAILY PARTITIONS in 229 ms
17:26:59.056 [main] INFO  c.d.d.c.c.ClickhouseConsolidatorSync - DETACH MONTHLY PARTITION: 202008
17:26:59.056 [main] INFO  c.d.d.c.c.ClickhouseConsolidatorSync - Calling: ALTER TABLE db.pageviews_data_auxiliary DETACH PARTITION 202008 
Exception in thread "main" com.ecwid.clickhouse.ClickHouseHttpException: HTTP 500 (Internal Server Error): Code: 210, e.displayText() = DB::NetException: Host not found: 6cf503fe389f (6cf503fe389f:9000) (version 20.4.5.36 (official build))
 (query: ALTER TABLE db.pageviews_data_auxiliary DETACH PARTITION 202008 )
```

Seems to be trying to connect to container, instead of the domain name (clickhouse-1.mydomain.com).
Server config also uses the domain names for internal connection.

**How to reproduce**
* Which ClickHouse server version to use
`Connected to ClickHouse server version 20.4.5 revision 54434.`

* Which interface to use, if matters

ECWID Clickhouse Client https://github.com/Ecwid/clickhouse-client 

* `CREATE TABLE` statements for all tables involved

Uploaded, just in case it helps.
[table-structure-pageviews.sql.txt](https://github.com/ClickHouse/ClickHouse/files/5119914/table-structure-pageviews.sql.txt)

**Comment by alexey-milovidov** [comment]
We have cleaned up some places where DNS responce can be cached for longer time than needed.
Does the issue reproduce with version 20.9?
