### ISSUE TITLE
Sanity check for index_granularity_bytes.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#14014]
> Hello! I've accidentally set index_granularity_bytes = 1 (I thought it's a toggle)... and now I got some giant parts (100GB) with 80GB marks....   and the marks_size is insane. Is there anyway to fix that part?

Maybe stop working if index size is larger than data size and larger than some threshold?

**Comment by alexey-milovidov** [comment]
Simply don't allow too low values of `index_granularity_bytes` - less than 1024. Throw an exception if value is lower and non zero.
The threshold should be controlled by MergeTreeSetting `min_index_granularity_bytes`.

**Comment by alexey-milovidov** [comment]
CC @amosbird

**Comment by bharatnc** [comment]
@alexey-milovidov  I would be interested in working on this. Can I take this?

**Comment by alesapin** [comment]
> @alexey-milovidov I would be interested in working on this. Can I take this?

I think it's a good idea to implement this feature. First of all, we need to introduce a new setting in MergeTreeSettings https://github.com/clickhouse/ClickHouse/blob/master/src/Storages/MergeTree/MergeTreeSettings.h#L93 and than perform validation somewhere below this line https://github.com/clickhouse/ClickHouse/blob/master/src/Storages/MergeTree/registerStorageMergeTree.cpp#L528. I'll assign this issue.

**Comment by bharatnc** [comment]
@alesapin I was able to add few checks in place but found something weird while using the following query:

```
tower :) CREATE TABLE indexed_table (     `tm` DateTime,     `log_message` String,     INDEX log_message log_message TYPE tokenbf_v1(4096, 2, 0) GRANULARITY 1 ) ENGINE = MergeTree ORDER BY (tm) SETTINGS min_index_granularity_bytes=1024, index_granularity_bytes=0;
```

The above query doesn't seem to pass the values specified via SETTINGS to [registerStorageMergeTree.cpp](https://github.com/clickhouse/ClickHouse/blob/master/src/Storages/MergeTree/registerStorageMergeTree.cpp#L528).

I found out by adding some debugging:

```
    auto index_granularity_bytes = storage_settings->index_granularity_bytes;
    auto min_index_granularity_bytes = storage_settings->min_index_granularity_bytes;
    std::cerr << ">>>>>> >>>>>>>>>>>>>>> the index_granularity_bytes: " << index_granularity_bytes << " min_index_granularity_bytes: " << min_index_granularity_bytes << std::endl;

....
#  server logs

>>>>>> >>>>>>>>>>>>>>> the index_granularity_bytes: 10485760 min_index_granularity_bytes: 1024
```

So it looks like it always takes the default value from [MergeTreeSettings.h](https://github.com/clickhouse/ClickHouse/blob/master/src/Storages/MergeTree/MergeTreeSettings.h#)  file

Am I missing something or doing wrong with the query here or have you seen something similar?

**Comment by bharatnc** [comment]
@alesapin I wanted to test the checks that I had implemented and for that I'm using the following query:

```
CREATE TABLE indexed_table (     `tm` DateTime,     `log_message` String,     INDEX log_message log_message TYPE tokenbf_v1(4096, 2, 0) GRANULARITY 1 ) ENGINE = SummingMergeTree ORDER BY (tm) SETTINGS min_index_granularity_bytes=1024, index_granularity_bytes=1;
```
Through some debug statements right under [registerStorageMergeTree.cpp ](https://github.com/clickhouse/ClickHouse/blob/master/src/Storages/MergeTree/registerStorageMergeTree.cpp#L528 )L528, I realized that the value of `storage_settings->index_granularity_bytes` `storage_settings->min_index_granularity_bytes` always seem to only take the values from under [MergeTreeSetting.h.](https://github.com/clickhouse/ClickHouse/blob/master/src/Storages/MergeTree/MergeTreeSettings.h)

Is there something wrong with my query that these default settings are not being overidden by the values under SETTINGS in the query? Am I missing something here?

**Comment by alesapin** [comment]
> @alesapin I wanted to test the checks that I had implemented and for that I'm using the following query:
> 
> ```
> CREATE TABLE indexed_table (     `tm` DateTime,     `log_message` String,     INDEX log_message log_message TYPE tokenbf_v1(4096, 2, 0) GRANULARITY 1 ) ENGINE = MergeTree ORDER BY (tm) SETTINGS min_index_granularity_bytes=1024, index_granularity_bytes=1;
> ```
> 
> Through some debug statements right under [registerStorageMergeTree.cpp ](https://github.com/clickhouse/ClickHouse/blob/master/src/Storages/MergeTree/registerStorageMergeTree.cpp#L528)L528, I realized that the value of `storage_settings->index_granularity_bytes` `storage_settings->min_index_granularity_bytes` always seem to only take the values from under [MergeTreeSetting.h.](https://github.com/clickhouse/ClickHouse/blob/master/src/Storages/MergeTree/MergeTreeSettings.h)
> 
> Is there something wrong with my query that these default settings are not being overidden by the values under SETTINGS in the query? Am I missing something here?

I'm sorry for the wrong link, they are updated here from `SETTINGS` section in table DDL https://github.com/clickhouse/ClickHouse/blob/master/src/Storages/MergeTree/registerStorageMergeTree.cpp#L591-L594
