### ISSUE TITLE
TSVRaw does not work with Kafka Engine as kafka_format

### ISSUE THREAD

**Issue by ramazanpolat** [ClickHouse/ClickHouse#14035]
**Describe the bug**
While `CSV` and `TSV` format works in Kakfa Engine as `kafkaf_format`, `TSVRaw` doesn't seem to work.

**How to reproduce**
**Version**: 20.6.4.44

TSV:
```sql
CREATE TABLE format_tsv(s String) ENGINE = MergeTree ORDER BY s;

CREATE TABLE format_tsv_kafka(s String) 
ENGINE = Kafka 
SETTINGS kafka_broker_list = 'kafka1test:9092,kafka2test:9092,kafka3test:9092', 
kafka_topic_list = 'format_tsv', 
kafka_num_consumers = 1, 
kafka_group_name='format_tsv', 
kafka_format = 'TSV';

CREATE MATERIALIZED VIEW format_tsv_mv TO format_tsv(s String) AS SELECT s FROM format_tsv_kafka;

insert into format_tsv_kafka values('format_tsv');
```

TSVRaw:
```
CREATE TABLE format_tsvraw(s String) ENGINE = MergeTree ORDER BY s;

CREATE TABLE format_tsvraw_kafka(s String) 
ENGINE = Kafka 
SETTINGS kafka_broker_list = 'kafka1test:9092,kafka2test:9092,kafka3test:9092', 
kafka_topic_list = 'format_tsvraw', 
kafka_num_consumers = 1, 
kafka_group_name='format_tsvraw', 
kafka_format = 'TSVRaw';

CREATE MATERIALIZED VIEW format_tsvraw_mv TO format_tsvraw(s String) AS SELECT s FROM format_tsvraw_kafka;

insert into format_tsvraw_kafka values('format_tsvraw');
```

Checking tables:
```sql
SELECT *
FROM format_tsv

┌─s──────────┐
│ format_tsv │
└────────────┘
1 rows in set. Elapsed: 0.006 sec.

SELECT *
FROM format_tsvraw

Ok.
0 rows in set. Elapsed: 0.004 sec.
```

**Comment by den-crane** [comment]
BTW, TSVRaw is an alias for TabSeparatedRaw

**Comment by ramazanpolat** [comment]
> BTW, TSVRaw is an alias for TabSeparatedRaw

Yeah I know, [this is why](https://stackoverflow.com/questions/63528287/consuming-nested-json-message-from-kafka-with-clickhouse/63531820?noredirect=1#comment112397161_63531820) I'm trying TSVRaw.

**Comment by filimonov** [comment]
TSVRaw is output only format, it can be used with Kafka to produce the data, not for consume.

**Comment by vladimir-golovchenko** [comment]
@ramazanpolat try to use *JSONAsString* input formatter - [test_storage_kafka/test.py](https://github.com/ClickHouse/ClickHouse/blob/dffd0a82130367805a3834d790238bde92840c6d/tests/integration/test_storage_kafka/test.py#L138).

**Comment by den-crane** [comment]
@filimonov TSVRaw is an input format https://github.com/ClickHouse/ClickHouse/pull/12009

```
create table TS (a String, b String) Engine=Memory;

echo -e 'a\t\\b'|clickhouse-client -q 'insert into TS format TSVRaw'
echo -e 'a\t\\b'|clickhouse-client -q 'insert into TS format TSV'
select * from TS
┌─a─┬─b──┐
│ a │ \b │
└───┴────┘
┌─a─┬─b─┐
│ a │  │
└───┴───┘

```

**Comment by ramazanpolat** [comment]
> TSVRaw is output only format, it can be used with Kafka to produce the data, not for consume.

[Documentation ](https://clickhouse.tech/docs/en/interfaces/formats/#tabseparatedraw) says that it is both input and output format.

![image](https://user-images.githubusercontent.com/3527695/91206961-af042980-e710-11ea-8ad2-b8c37775660e.png)

**Comment by ramazanpolat** [comment]
Ok. It it now obvious that TSVRaw is not suitable for input:
```
2020.08.25 19:47:26.959421 [ 148 ] {} <Error> void DB::StorageKafka::threadFunc(): Code: 85, e.displayText() = DB::Exception: Format TSVRaw is not suitable for input,
 Stack trace (when copying this message, always include the lines below):
```
