### ISSUE TITLE
Submodule contrib/icu checkout is not working

### ISSUE THREAD

**Issue by epochslee** [ClickHouse/ClickHouse#14036]
The cloning of your project is breaking on this:
`Unable to checkout 'faa2f9f9e1fe74c5ed00eba371d2830134cdbea1' in submodule path 'contrib/icu'`

I'm on:

MacOs: 10.14.6 (18G4032)

**Comment by alexey-milovidov** [comment]
It points here and it looks alright: https://github.com/unicode-org/icu/tree/faa2f9f9e1fe74c5ed00eba371d2830134cdbea1

Does the issue reproduce? Does it work if you clone the https://github.com/unicode-org/icu/ repository manually and checkout faa2f9f9e1fe74c5ed00eba371d2830134cdbea1 commit?

**Comment by epochslee** [comment]
I can give that a try. I'm trying to see how do I modify the .gitmodules files to point locally. Do you know off hand how? Meanwhile I'm googling around for it.......

**Comment by epochslee** [comment]
Actually, I noticed this error during cloning of that icu url you gave me:

```
$ git clone https://github.com/unicode-org/icu/
Cloning into 'icu'...
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 483631 (delta 1), reused 1 (delta 1), pack-reused 483627
Receiving objects: 100% (483631/483631), 226.97 MiB | 4.85 MiB/s, done.
Resolving deltas: 100% (383007/383007), done.
git-lfs smudge 'icu4j/main/shared/data/icudata.jar': git-lfs: command not found
error: external filter 'git-lfs smudge %f' failed 127
error: external filter 'git-lfs smudge %f' failed
fatal: icu4j/main/shared/data/icudata.jar: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

Then attempting 'git restore --source=HEAD :/' returned this error:

```
slee@~/icu$ git restore --source=HEAD :/
git-lfs smudge 'icu4j/main/shared/data/icudata.jar': git-lfs: command not found
error: external filter 'git-lfs smudge %f' failed 127
error: external filter 'git-lfs smudge %f' failed
fatal: icu4j/main/shared/data/icudata.jar: smudge filter lfs failed
```

**Comment by alexey-milovidov** [comment]
Looks like you need `git-lfs`.
By the way, I don't have it on my machine and everything is working fine... maybe it's embedded into git?

**Comment by epochslee** [comment]
Looks like that was it! Thank you Alexey!

**Comment by Smelly-calf** [comment]
> Looks like that was it! Thank you Alexey!

I wanna know how you fix it using git-lfs, I haven't ever used git-lfs

**Comment by darrenfu** [comment]
> It points here and it looks alright: https://github.com/unicode-org/icu/tree/faa2f9f9e1fe74c5ed00eba371d2830134cdbea1
> 
> Does the issue reproduce? Does it work if you clone the https://github.com/unicode-org/icu/ repository manually and checkout faa2f9f9e1fe74c5ed00eba371d2830134cdbea1 commit?

I am also experiencing the similar issue (see error msg below). @epochslee did you end up resolving this issue by checkout the commit manually?

> Unable to checkout 'a56dde820dc35665a66f2e9ee8ba58e75049b668' in submodule path 'contrib/icu'
