### ISSUE TITLE
Cannot lock file /data/clickhouse/status. Another serverinstance in same directory is already running.

### ISSUE THREAD

**Issue by lecranek** [ClickHouse/ClickHouse#14042]
Hi there, I have a problem when starting my clickhouse-server. 
I use `sudo /etc/init.d/clickhouse-server start` to start clickhouse and then type `clickhouse-client --port 9002` to test some queries. All of the queries seem to work well. BUT the following content has always been output in err.log:
```
2020.08.25 14:46:44.572853 [ 51428 ] {} <Error> Application: DB::Exception: Cannot lock file /data/clickhouse/status. Another serverinstance in same directory is already running.
2020.08.25 14:47:15.040157 [ 51435 ] {} <Error> Application: DB::Exception: Cannot lock file /data/clickhouse/status. Another serverinstance in same directory is already running.
2020.08.25 14:47:45.319636 [ 51442 ] {} <Error> Application: DB::Exception: Cannot lock file /data/clickhouse/status. Another serverinstance in same directory is already running.
2020.08.25 14:48:15.815258 [ 51450 ] {} <Error> Application: DB::Exception: Cannot lock file /data/clickhouse/status. Another serverinstance in same directory is already running.
2020.08.25 14:48:46.316107 [ 51458 ] {} <Error> Application: DB::Exception: Cannot lock file /data/clickhouse/status. Another serverinstance in same directory is already running.
```
I checked the status file and it records current process correctly. 
ps: I have changed the tcp_port in config.xml from 9000 to 9002

**Comment by lecranek** [comment]
I've checked status file again and found it records this process：
```
clickhouse-server --daemon --pid-file=/var/run/clickhouse-server/clickhouse-server.pid --config-file=/etc/clickhouse-server/config.xml
```
The problem is that i've never start server like that.

**Comment by lecranek** [comment]
Maybe that process is a child process of init? 
Once I killed the process mentioned above, there will be another clickhouse process like `/usr/bin/clickhouse-server --config=/etc/clickhouse-server/config.xml --pid-file=/run/clickhouse-server/clickhouse-server.pid` working several seconds later. And the err.log returned normal after this step.

**Comment by den-crane** [comment]
/etc/init.d/clickhouse-server  -- a bash script which runs `/usr/bin/clickhouse-server --config=/etc/clickhouse-server/config.xml --pid-file=/run/clickhouse-server/clickhouse-server.pid`

/etc/cron.d/clickhouse-server -- another bash script which runs  `/usr/bin/clickhouse-server --config=/etc/clickhouse-server/config.xml --pid-file=/run/clickhouse-server/clickhouse-server.pid` if CH crashed.

**Comment by den-crane** [comment]
What distro do you use? CentOS? Debian?

in case of systemd you should use `sudo systemctl start clickhouse-server` not `/etc/init.d/clickhouse-server`

**Comment by lecranek** [comment]
Thanks for reply. I've solved it.

**Comment by sliontc** [comment]
@den-crane Hi, I got same error, how to fix it? My CK suddenly crashed after a SQL query with the error "AST is too big...". Then I couldn't connect the CK. It always output 
![image](https://user-images.githubusercontent.com/6959147/101632014-3a0af480-3a60-11eb-844e-9e4844186f1b.png)

**Comment by sliontc** [comment]
> Thanks for reply. I've solved it.

Hi, How did you solve it?

**Comment by den-crane** [comment]
@sliontc service start clickhouse-server

Version 18.14 is out of support.

**Comment by sliontc** [comment]
> @sliontc service start clickhouse-server
> 
> Version 18.14 is out of support.

Could you help in remote control? 
I'v tried service clickhouse-server start, but still can't connect. It makes me crazy .

**Comment by alexey-milovidov** [comment]
@sliontc Check the logs.

If it will not help, run clickhouse-server manually with the command:
```
sudo -u clickhouse /usr/bin/clickhouse server --config-file /etc/clickhouse-server/config.xml
```

**Comment by JensJI** [comment]
This happened to me after accidently started two docker containers at the same time. So very much like the error describes, this occurs because multiple programs of clickhouse are running at the same time.
