### ISSUE TITLE
How to consume huge Kafka topic with lot of data coming every sec

### ISSUE THREAD

**Issue by jmalicevic** [ClickHouse/ClickHouse#14046]
Ingesting a very large kafka topic with 200k messages per second and 120 partitions. 

I am curious whether you have a suggestion on parameters to tune when ingesting such a topic. We have many fields and a lot of messags coming. I have currently 8 pods in k8s with 6 CPU threads. Each pod has a kafka engine and a materialized view which pushes the data from kafka into a MergeTree table, partitioned by the kafka event time.  I tried a few things such as :

- Increasing the kafka_max_block_size, 
- having num_consumers per kafka engine to 4 and 5
- creating multiple kafka engines per pod with one consumer and one materialized view, each materialized view pushes data into the MergeTree tables. 

I am using Clickhouse server 20.6. So I have at most 40 consumers for 120 partitions and I am not sure what is the best performance I can expect. Right now, during the day, we load at most a few hours of data. If yo uhave any advice, it is highly appreciated. 

Thanks,
Jasmina

**Comment by den-crane** [comment]
now it's **kafka_poll_max_batch_size**  increase kafka_poll_max_batch_size gradually

How wide (long) is your kafka messages in bytes?

kafka_poll_max_batch_size, 0, "Maximum amount of messages to be polled in a single Kafka poll.
kafka_max_block_size, 0, "Number of row collected by poll(s) for flushing data from Kafka.

#11388

**Comment by jmalicevic** [comment]
Hi @den-crane ,
Approximately 3600 bytes/message (~600 fields with 4 or 8 bytes). I will check out the issue you linked, thanks a lot. If this number rings any new bells, let me know, and I'll write an update once I experiment with a few settings.

**Comment by den-crane** [comment]
200.000*3600/1024/1024 = 686 MB/s. It pretty huge. I doubt that 8 consumers able to ingest that even in theory.
Probably you will have to use `creating multiple kafka engines per pod` way.

**Comment by jmalicevic** [comment]
Yes, so right now I have more consumers per pod. I just tried it different ways. Having one kafka engine with kafka_num_consumers=5 and having 5 kafka engines with kafka_num_consumers=1. However, having 5 engines and one materialized view might shift the bottleneck to multiple writes into the MergeTree table.

**Comment by den-crane** [comment]
>However, having 5 engines and one materialized view might shift the bottleneck to multiple writes into the MergeTree table.

Parallel inserts is OK and maybe even more preferable for such huge stream.
