### ISSUE TITLE
Incompatibility with optimize_* settings

### ISSUE THREAD

**Issue by 4ertus2** [ClickHouse/ClickHouse#14044]
Settings `optimize_move_functions_out_of_any`, `optimize_arithmetic_operations_in_aggregate_functions` (and probably `optimize_injective_functions_inside_uniq` and `optimize_if_transform_strings_to_enum`) lead to incompatibility in distributed queries when one version expects rewritten query and another does not.

Example of error messge:
```
DB::Exception: Not found column sum(multiply(Sign, W)) in block. There are only columns: ... sum(Sign) ...
```

**Comment by 4ertus2** [comment]
One of solutions is to disable this optimisation for distributed queries. But there's no simple way to implement it.
Another solution is to disable them by default. But we would have the same troubles in future.
It's expected that release 20.7 (or 20.8) would have some backward incompatible changes. So the best solution is to disable them in 20.6- and ebabled in 20.7+.

**Comment by alexey-milovidov** [comment]
The way to go is to wait one year after optimizations are introduced and then enable by default.
