### ISSUE TITLE
data type "String" support maximal length contraint

### ISSUE THREAD

**Issue by etah000** [ClickHouse/ClickHouse#14040]
Data type "String" is very smilar to "VARCHAR" in other RDBMS, but it has no max length constraint. This is difficult for schema mapping between Clickhouse and other RDBMS. 

Can we add support for max length constraints so that its syntax meaning will be the same as "VARCHAR"?

**Comment by filimonov** [comment]
To cut off strings 'longer than' ?.. 

Use case is not clear (you can alway crop string using `left` when needed)

**Comment by etah000** [comment]
Yes, such as "String(32)".  We want to map  "String" to "VARCHAR".

**Comment by den-crane** [comment]
@etah000 What do you mean by "maximal length contraint" ?

I don't see an issue.

```
CREATE TABLE v1
(
    `A` varchar(255)
)
ENGINE = MergeTree
ORDER BY tuple()

Ok.

0 rows in set. Elapsed: 0.005 sec.
```

**Comment by etah000** [comment]
I need a reverse mapping, that is, I need map "String" to "VARCHAR". If there is no length contraint, I cannot define the length parameter N for "VARCHAR(N)".

**Comment by alexey-milovidov** [comment]
Don't understand why the issue is closed.
We don't have length constraints in data types and we can consider implementing this feature.

Right now you can use separate constraints:
```
CREATE TABLE v1
(
    `A` varchar(255),
    CONSTRAINT length_A CHECK length(A) <= 255
)
ENGINE = MergeTree
ORDER BY tuple()
```

**Comment by den-crane** [comment]
> I need a reverse mapping, that is, I need map "String" to "VARCHAR". If there is no length contraint, I cannot define the length parameter N for "VARCHAR(N)".

You can map to the max length your other DB can support. For example if you use mysql you can map String -> varchar(65536)

**Comment by etah000** [comment]
@alexey-milovidov  I plan to implement the feature, but just as "den-crane" suggested, I think I can use a rather large number for  the default length constraint. Maybe there is no obvious performance difference between VARCH(32)  and VARCHAR(65536) if the actually stored data length is smaller than 32 as some RDBMS, such as H2, postgres, both support "VARCHAR" without length parameter. So I closed the issue.

**Comment by alexey-milovidov** [comment]
Ok, perfect.

PS. AFAIK, MySQL does not have significant performance decrease if you use VARCHAR(65535).
Two bytes are used for length instead of one but it barely affects anything.
