### ISSUE TITLE
show create table breaks formatting with \n characters

### ISSUE THREAD

**Issue by ipoese** [ClickHouse/ClickHouse#14096]
When running queries via the clickhouse-client command directly with the -q argument, the output for "show create table" adds extra \n characters that break the formatting. This causes clickhouse to not be able to reads its own output when fed back into it.

**How to reproduce**

create a table
```
$ clickhouse-client -q "create table default.Test (t UInt8) ENGINE=MergeTree Partition by t order by t"
```
change the table name via a simple sed command and see that it changed the create table command correctly
```
$ clickhouse-client -q "show create table default.Test" | sed 's/\.Test/\.Test2/'
CREATE TABLE default.Test2\n(\n    `t` UInt8\n)\nENGINE = MergeTree\nPARTITION BY t\nORDER BY t\nSETTINGS index_granularity = 8192
```

feed the create table back into clickhouse
```
$ clickhouse-client -q "$(clickhouse-client -q "show create table default.Test" | sed 's/\.Test/\.Test2/')"
Code: 62. DB::Exception: Syntax error: failed at position 27: \n(\n    `t` UInt8\n)\nENGINE = MergeTree\nPARTITION BY t\nORDER BY t\nSETTINGS index_granularity = 8192. Unrecognized token
```
I can currently find no console output format that allows me to feed clickhouse back its own statement via the commandline as it either adds new lines or \n to *show create table* 

Note that this issues also exists when running the command inside the clickhouse-client. So a simple "copy'n'paste" approach to quickly modify an existing statement is not possible anymore.  

** Which ClickHouse server version to use **
```
ClickHouse client version 20.6.3.28 (official build).
Connecting to clickhouse-process00:9000 as user default.
Connected to ClickHouse server version 20.6.3 revision 54436.
```
and 

```
ClickHouse client version 20.6.4.44 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 20.6.4 revision 54436.
```

** how this worked before **
In the previous clickhouse-version we ran, this worked as such (here is the sample output from a 19.15.3.6 server
```$ clickhouse-client
ClickHouse client version 19.15.3.6 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 19.15.3 revision 54426.

clickhouse :) create table default.Test (t UInt8) ENGINE=MergeTree Partition by t order by t

CREATE TABLE default.Test
(
    `t` UInt8
)
ENGINE = MergeTree
PARTITION BY t
ORDER BY t

Ok.

0 rows in set. Elapsed: 0.011 sec. 

clickhouse :) show create table default.Test format CSV

SHOW CREATE TABLE default.Test
FORMAT CSV

"CREATE TABLE default.Test (`t` UInt8) ENGINE = MergeTree PARTITION BY t ORDER BY t SETTINGS index_granularity = 8192"

1 rows in set. Elapsed: 0.003 sec. 

clickhouse :) Bye.

$ clickhouse-client -q "show create table default.Test"
CREATE TABLE default.Test (`t` UInt8) ENGINE = MergeTree PARTITION BY t ORDER BY t SETTINGS index_granularity = 8192
$ clickhouse-client -q "$(clickhouse-client -q "show create table default.Test" | sed 's/\.Test/\.Test2/')"
$ clickhouse-client -q "show create table default.Test2"
CREATE TABLE default.Test2 (`t` UInt8) ENGINE = MergeTree PARTITION BY t ORDER BY t SETTINGS index_granularity = 8192

```
Note the missing  "\n" characters in the create statement and the ability to directly copy this back into clickhouse via copy and paste

**Comment by filimonov** [comment]
clickhouse-client -q "show create table default.Test" --format=TSVRaw

**Comment by den-crane** [comment]
it was intentional change https://github.com/ClickHouse/ClickHouse/pull/10049 
and \n is showed because default format is TSV 

I don't see UB here. 

https://github.com/ClickHouse/ClickHouse/blob/master/CHANGELOG.md#clickhouse-release-v20429-2020-05-12
ClickHouse release v20.4.2.9, 2020-05-12
Backward Incompatible Change
Make SHOW CREATE TABLE multiline. Now it is more readable and more like MySQL. #10049 (Azat Khuzhin)

**Comment by filimonov** [comment]
> it was intentional change #10049
> and \n is showed because default format is TSV
> 
> I don't see UB here. 

Agree :) changed because there is no bug here either :) 

Actually the issue not in the newlines but in escaping which happens by default in TSV. 

TSVRaw is the answer.
