### ISSUE TITLE
default_database in the remote_servers decreases the query performance

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#14099]
```
cat << EOF > /etc/clickhouse-server/config.d/test_cluster_two_shards_localhost2.xml
<?xml version="1.0"?>
<yandex>
    <remote_servers incl="clickhouse_remote_servers" >
        <test_cluster_two_shards_localhost2>
             <shard>
                 <replica>
                     <host>localhost</host>
                     <port>9000</port>
                     <default_database>default</default_database>
                 </replica>
             </shard>
             <shard>
                 <replica>
                     <host>localhost</host>
                     <port>9000</port>
                     <default_database>default</default_database>
                 </replica>
             </shard>
        </test_cluster_two_shards_localhost2>
    </remote_servers>
</yandex>
EOF
```

```
echo 'select * from cluster(test_cluster_two_shards_localhost,system,one)' | clickhouse-benchmark -i 1000 -d 0
```

QPS: 490.118

vs

```
echo 'select * from cluster(test_cluster_two_shards_localhost2,system,one)' | clickhouse-benchmark -i 1000 -d 0
```

QPS: 167.504

**Comment by alexey-milovidov** [comment]
Please share `perf report`s.

**Comment by alexey-milovidov** [comment]
Maybe it because localhost optimization will be disabled?

**Comment by alexey-milovidov** [comment]
CC @azat

**Comment by azat** [comment]
>Maybe it because localhost optimization will be disabled?

Confirmed.

`default_database` use case looks a little bit superfluous.

By the way there is not a tiny note about `default_database` in the documentation (https://clickhouse.tech/docs/en/single/), but example exists in `config.xml`

But back to the issue, actually I don' see the reason of disabling localhost optimization for this case, since you cannot create distributed database w/o specifying database, @alexey-milovidov maybe I'm missing something?

**Comment by alexey-milovidov** [comment]
@azat 

`default_database` was invented for cross-replication when multiple servers may run on the same host.
Now it depends on how localhost optimization is performed. If it takes both host and port into account - everything is ok.
If only host - then it must be disabled.

Most likely the reason why it is disabled is that long time ago port was not taken into accound.

**Comment by azat** [comment]
>Now it depends on how localhost optimization is performed. If it takes both host and port into account - everything is ok.

Yes, host and port and AFAICS from the git history it was from beginning (1c86e58), well it was definitely there when default_database has been added.
Anyway, here is a patch (#17585), let's try.

**Comment by filimonov** [comment]
AFAIR it was originally observed on a cluster with prefer_localhost=0, and definitely not on localhost-only queries (5 shards, 2 replicas arair).

So i'm not sure it it's the correct reason, but i had no chances to recheck it by my own.

**Comment by filimonov** [comment]
Here are some details. 
https://altinity.com/blog/2018/5/10/circular-replication-cluster-topology-in-clickhouse

BTW: quite a lot of people are interested in that, but the concept described in that article works badly...
