### ISSUE TITLE
experimental MaterializeMySQL in 20.8 cannot synchronize "create table" commands

### ISSUE THREAD

**Issue by l1t1** [ClickHouse/ClickHouse#14114]
i use
my steps
1. create a new database ckdb on mysql, then  create table t1(a int, primary key(a)); and insert some rows
2. SET allow_experimental_database_materialize_mysql=1; at clickhouse, 
3. CREATE DATABASE ckdb ENGINE = MaterializeMySQL('127.0.0.1:3306', 'ckdb', 'root', 'A123b_456');
4. use ckdb and select * from t1 ok
5. create table dzm as select * from others in mysql ----> cannot see dzm in clickhouse, but if select * from t1, reports
```
Code: 48. DB::Exception: Received from localhost:9000. DB::Exception: The ckdb.dzm cannot be materialized, because there is no primary keys..
```
6. create table t2(a int,b int primary a);----> cannot see t2 in clickhouse, , but if select * from t1, reports
```
Code: 44. DB::Exception: Received from localhost:9000. DB::Exception: Sorting key cannot contain nullable columns.
```
<del>7. if i drop ckdb and recreate it, all tables can be selected </del>
7.if there are some 'bad' tables in a database, all tables in that database cannot be selected

Make sure to check documentation https://clickhouse.yandex/docs/en/ first. If the question is concise and probably has a short answer, asking it in Telegram chat https://telegram.me/clickhouse_en is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

If you still prefer GitHub issues, remove all this text and ask your question here.

**Comment by l1t1** [comment]
if there is no 'bad' tables,drop ckdb and recreate it, all tables can be selected.
```
mysql> create database ckdb3;
Query OK, 1 row affected (0.02 sec)

mysql> use ckdb3;
Database changed
```
create db in clickhouse now
```
CREATE DATABASE ckdb3
ENGINE = MaterializeMySQL('127.0.0.1:3306', 'ckdb3', 'root', 'A123b_456')

Ok.

0 rows in set. Elapsed: 0.028 sec.

```
create a table in mysql's db
```
mysql> create table ta(a int,primary key(a));
Query OK, 0 rows affected (0.14 sec)

mysql> insert into ta values(1),(2);
Query OK, 2 rows affected (0.00 sec)
Records: 2  Duplicates: 0  Warnings: 0

mysql> commit;
Query OK, 0 rows affected (0.03 sec)
```
cannot see ta in clickhouse
```
USE ckdb3

Ok.

0 rows in set. Elapsed: 0.013 sec.

SHOW TABLES

Ok.

0 rows in set. Elapsed: 0.018 sec.

SELECT *
FROM ta

Received exception from server (version 20.8.1):
Code: 60. DB::Exception: Received from localhost:9000. DB::Exception: Table ckdb3.ta doesn't exist..

0 rows in set. Elapsed: 0.012 sec.
```
drop and recreate db, ok
```
DROP DATABASE ckdb3

Ok.

0 rows in set. Elapsed: 0.008 sec.

CREATE DATABASE ckdb3
ENGINE = MaterializeMySQL('127.0.0.1:3306', 'ckdb3', 'root', 'A123b_456')

Ok.

0 rows in set. Elapsed: 0.043 sec.

SHOW TABLES

┌─name─┐
│ t1   │
└──────┘

1 rows in set. Elapsed: 0.016 sec.

USE ckdb3

Ok.

0 rows in set. Elapsed: 0.007 sec.

SHOW TABLES

┌─name─┐
│ ta   │
└──────┘

1 rows in set. Elapsed: 0.023 sec.

SELECT *
FROM ta

┌─a─┐
│ 1 │
└───┘
┌─a─┐
│ 2 │
└───┘

2 rows in set. Elapsed: 0.031 sec.

```

**Comment by BohuTANG** [comment]
1. Bad 'table' will break the MaterializeMySQL replciation thread, you should drop and re-create it.
2.  CREATE TABLE ... SELECT statements are not allowed when using GTID-based replication(and the new version MaterializeMySQL ONLY support GTID mode), it's not safe or you will get:
```
ERROR 1786 (HY000): Statement violates GTID consistency: CREATE TABLE ... SELECT.
```

see [16.1.3.6 Restrictions on Replication with GTIDs](https://dev.mysql.com/doc/refman/5.7/en/replication-gtids-restrictions.html)

**Comment by BohuTANG** [comment]
> if there is no 'bad' tables,drop ckdb and recreate it, all tables can be selected.
> 
> ```
> mysql> create database ckdb3;
> Query OK, 1 row affected (0.02 sec)
> 
> mysql> use ckdb3;
> Database changed
> ```
> 
> create db in clickhouse now
> 
> ```
> CREATE DATABASE ckdb3
> ENGINE = MaterializeMySQL('127.0.0.1:3306', 'ckdb3', 'root', 'A123b_456')
> 
> Ok.
> 
> 0 rows in set. Elapsed: 0.028 sec.
> ```
> 
> create a table in mysql's db
> 
> ```
> mysql> create table ta(a int,primary key(a));
> Query OK, 0 rows affected (0.14 sec)
> 
> mysql> insert into ta values(1),(2);
> Query OK, 2 rows affected (0.00 sec)
> Records: 2  Duplicates: 0  Warnings: 0
> 
> mysql> commit;
> Query OK, 0 rows affected (0.03 sec)
> ```
> 
> cannot see ta in clickhouse
> 
> ```
> USE ckdb3
> 
> Ok.
> 
> 0 rows in set. Elapsed: 0.013 sec.
> 
> SHOW TABLES
> 
> Ok.
> 
> 0 rows in set. Elapsed: 0.018 sec.
> 
> SELECT *
> FROM ta
> 
> Received exception from server (version 20.8.1):
> Code: 60. DB::Exception: Received from localhost:9000. DB::Exception: Table ckdb3.ta doesn't exist..
> 
> 0 rows in set. Elapsed: 0.012 sec.
> ```
> 
> drop and recreate db, ok
> 
> ```
> DROP DATABASE ckdb3
> 
> Ok.
> 
> 0 rows in set. Elapsed: 0.008 sec.
> 
> CREATE DATABASE ckdb3
> ENGINE = MaterializeMySQL('127.0.0.1:3306', 'ckdb3', 'root', 'A123b_456')
> 
> Ok.
> 
> 0 rows in set. Elapsed: 0.043 sec.
> 
> SHOW TABLES
> 
> ┌─name─┐
> │ t1   │
> └──────┘
> 
> 1 rows in set. Elapsed: 0.016 sec.
> 
> USE ckdb3
> 
> Ok.
> 
> 0 rows in set. Elapsed: 0.007 sec.
> 
> SHOW TABLES
> 
> ┌─name─┐
> │ ta   │
> └──────┘
> 
> 1 rows in set. Elapsed: 0.023 sec.
> 
> SELECT *
> FROM ta
> 
> ┌─a─┐
> │ 1 │
> └───┘
> ┌─a─┐
> │ 2 │
> └───┘
> 
> 2 rows in set. Elapsed: 0.031 sec.
> ```
MaterializeMySQL has 2 steps for datas replication:
Step1: full dumping with `select ... from ...` in transaction
Step2: incremental dumping by binlog events

Here it works because it's Step1, not Step2.
this works since it's a normal table create and data dump,
