### ISSUE TITLE
Add table function null.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#14121]
**Use case**
For convenience writing tests and demos.

**Comment by filimonov** [comment]
Vote up. Should accept any inserts with any columns and drop them away.

**Comment by alexey-milovidov** [comment]
But see no way to accept arbitrary data. We just don't have a concept of table without structure.

**Comment by alexey-milovidov** [comment]
Actually `file` table function with `Null` format will do the trick.

**Comment by alexey-milovidov** [comment]
null('table structure'), example: `null('x UInt64')`

**Comment by filimonov** [comment]
May be it can have only dummy column, and inherit the structure from inserted block dinamically?

**Comment by alexey-milovidov** [comment]
No... INSERT checks table structure and it is implemented in general way.
