### ISSUE TITLE
Clickhouse unable to start with unclear error if Distributed table have unexpected folders

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#14130]
```
create table default.DFA(A Int64) Engine=MergeTree  order by tuple();
create table default.DFAD as default.DFA Engine=Distributed(test_shard_localhost, default, DFA)

 mkdir /var/lib/clickhouse/data/default/DFAD/shard1_replica1,shard1_replica2
chown -R clickhouse.clickhouse /var/lib/clickhouse/data/default/DFAD/shard1_replica1,shard1_replica2/

/etc/init.d/clickhouse-server restart


<Fatal> BaseDaemon: ########################################
<Fatal> BaseDaemon: (version 20.8.1.4436, build id: 30B7E2A4815769B9) (from thread 21305) (no query) Received signal Segmentation fault (11)
<Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
<Fatal> BaseDaemon: Stack trace: 0x17a585f5 0x1783c5de 0x17841b4e 0x17841ea0 0x1715a672 0xff3df97 0xff3e70a 0xff3d4a7 0xff3bae3 0x7f411ecd9fa3 0x7f411ebfb4

<Fatal> BaseDaemon: 3. DB::StorageDistributedDirectoryMonitor::createPool(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<cha
t&) @ 0x17a585f5 in /usr/bin/clickhouse
<Fatal> BaseDaemon: 4. DB::StorageDistributed::requireDirectoryMonitor(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>
td::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x1783c5de in /usr/bin/clickhouse
<Fatal> BaseDaemon: 5. DB::StorageDistributed::createDirectoryMonitors(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>
house
<Fatal> BaseDaemon: 6. DB::StorageDistributed::startup() @ 0x17841ea0 in /usr/bin/clickhouse
<Fatal> BaseDaemon: 7. ? @ 0x1715a672 in /usr/bin/clickhouse
<Fatal> BaseDaemon: 8. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0xff3df97 in /usr/bin/clickho

<Fatal> BaseDaemon: 9. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>
```

**Comment by alexey-milovidov** [comment]
I see dumb code in this line: https://clickhouse.tech/codebrowser/html_report/ClickHouse/src/Storages/Distributed/DirectoryMonitor.cpp.html#217

**Comment by fibersel** [comment]
As long as distributed table doesn't store any data, we can just skip checking shards and replicas across whole cluster and remove code from 217 to 236 lines, isn't so?
Correct me if i'm wrong.

**Comment by den-crane** [comment]
@fibersel 
These folders for async inserts. Distributed table stores .bin files with data which should be inserted.
shard1_replica1 -- means that data in this folder should be inserted into the shard1.

`shard1_replica1,shard1_replica2` -- I am not sure how this folder happen, and it does not matter. The error message should be clear.

**Comment by fibersel** [comment]
@den-crane 
Oh, I've heard you.So, the correct behavior is to check shard existence and throw an exceptions is one is abscent

**Comment by den-crane** [comment]
I think the best behavior is to 
1. move unexpected folders to $broken (not sure where).
 or leave them as is if it's not make a mess for the distributed sender.
2. alert into logs with clear message that found some unexpected folder and moved
3. start successfully

**Comment by fibersel** [comment]
I can fix that bug, but the only obstacle is how to write test for that case?
I've set all environment and run some integrations tests from repo, but I don't know, how to create folder into running container properly.Can someone point to similar example?

**Comment by fibersel** [comment]
@alexey-milovidov , can you suggest where the folder for garbage files in ClickHouse located is?
I would move unexpected files and folder there

**Comment by den-crane** [comment]
@fibersel check tests/integration/test_backup_with_other_granularity/test.py

node1.exec_in_container(['bash', '-c', 'cp -r /var/lib/clickhouse/shadow/1/data/default/source_table/all_1_1_0/ /var/lib/clickhouse/data/default/dest_table/detached'])

you can execute node1.exec_in_container(['bash', '-c', 'mkdir ...

**Comment by alexey-milovidov** [comment]
@azat 

The "dumb code"
`return shards_info[address.shard_index - 1].per_replica_pools[address.replica_index - 1];`
is still there.

**Comment by alexey-milovidov** [comment]
Priority is minor, because the issue requires manual intervention in filesystem to reproduce.
