### ISSUE TITLE
orc requires tzdata: 'orc::getLocalTimezone(): Can't open /etc/localtime."

### ISSUE THREAD

**Issue by jjtjiang** [ClickHouse/ClickHouse#14156]
when i  use "SELECT *
FROM hdfs()"   with version 20.6 .but it works well when use version 19.14.
Code: 1001. DB::Exception: Received from hadoop:9000. DB::Exception: N3orc13TimezoneErrorE: Can't open /etc/localtime. 
 I am searching for a long time on net. But no use. Please help or try to give some ideas how to achieve this.

**Comment by filimonov** [comment]
> N3orc13TimezoneErrorE 

1) do you use some custom build? 
2) Do you have a full stack trace of the error? In logs it should be just below the error, or you can run clickhouse-client with parameter `clickhouse-client --stacktrace` and retry the problematic command. (please paste the stack trace)
3) what is your OS / environment?

**Comment by jjtjiang** [comment]
一、 I use  clickhouse with docker  having  not  other custom build  . it work well with  version 19.14 、20.1、20.2、20.3、20.4. it will not working with version 20.5 、20.6、20.7.
二. stack trace is below:
2020.08.28 03:04:22.776710 [ 112 ] {744e3e0f-c7b7-4a24-bbca-1c0f94f8ae18} <Error> executeQuery: std::exception. Code: 1001, type: orc::TimezoneError, e.what() = Can't open /etc/localtime (version 20.6.4.44 (official build)) (from [::ffff:172.17.0.1]:41144) (in query:  SELECT * FROM hdfs('hdfs://hdpuat/test/dws_stellr_consumption_azure_usage_1d_j1', ORC, '  billing_year    Nullable(Int32), date_flag    Date' ) LIMIT 2;), Stack trace (when copying this message, always include the lines below):

0. std::runtime_error::runtime_error(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x133ab715 in ?
1. ? @ 0x12c46ad2 in /usr/bin/clickhouse
2. orc::getLocalTimezone() @ 0x12c4380e in /usr/bin/clickhouse
3. orc::RowReaderImpl::RowReaderImpl(std::__1::shared_ptr<orc::FileContents>, orc::RowReaderOptions const&) @ 0x12c15d2d in /usr/bin/clickhouse
4. orc::ReaderImpl::createRowReader(orc::RowReaderOptions const&) const @ 0x12c1606b in /usr/bin/clickhouse
5. arrow::adapters::orc::ORCFileReader::Read(std::__1::shared_ptr<arrow::Table>*) @ 0x12bde7b3 in /usr/bin/clickhouse
6. DB::ORCBlockInputFormat::generate() @ 0xfce0419 in /usr/bin/clickhouse
7. DB::ISource::work() @ 0xfba50db in /usr/bin/clickhouse
8. DB::InputStreamFromInputFormat::readImpl() @ 0xfb69edd in /usr/bin/clickhouse
9. DB::IBlockInputStream::read() @ 0xede92cd in /usr/bin/clickhouse
10. DB::OwningBlockInputStream<DB::ReadBuffer>::readImpl() @ 0xd066bb9 in /usr/bin/clickhouse
11. DB::IBlockInputStream::read() @ 0xede92cd in /usr/bin/clickhouse
12. ? @ 0xf669e74 in /usr/bin/clickhouse
13. DB::ISource::work() @ 0xfba50db in /usr/bin/clickhouse
14. DB::SourceWithProgress::work() @ 0xfded8f7 in /usr/bin/clickhouse
15. ? @ 0xfbd5511 in /usr/bin/clickhouse
16. ? @ 0xfbdae36 in /usr/bin/clickhouse
17. DB::PipelineExecutor::executeImpl(unsigned long) @ 0xfbdb62d in /usr/bin/clickhouse
18. DB::PipelineExecutor::execute(unsigned long) @ 0xfbdc0b1 in /usr/bin/clickhouse
19. ? @ 0xfbe0d5d in /usr/bin/clickhouse
20. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa271f67 in /usr/bin/clickhouse
21. ? @ 0xa2704a3 in /usr/bin/clickhouse
22. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
23. clone @ 0x122103 in /usr/lib/x86_64-linux-gnu/libc-2.31.so

三、 CentOS Linux release 7.5.1804 (Core)

in addition，when use  hdfs table function  ，whether the user name can be passed,HDFS user permissions are different. 
thanks.

**Comment by filimonov** [comment]
Thank you. It relates to https://github.com/ClickHouse/ClickHouse/pull/11827/files

Workaround is to install tzdata inside docker container. 
For example you can create a script like install_tzsata.sh
```
apt-get update
apt-get install  --yes tzdata
```
And mount a folder with that script inside container as `/docker-entrypoint-initdb.d` - all sql and shell scripts from that folder are fired when container start (see https://github.com/ClickHouse/ClickHouse/blob/25f55bb5ddc9d52da4542339fee4174ec924be18/docker/server/entrypoint.sh#L91)

**Comment by filimonov** [comment]
> in addition，when use hdfs table function ，whether the user name can be passed,HDFS user permissions are different.
thanks.

If you see the problem - please open one more issue with details of how to reproduce that.

**Comment by jjtjiang** [comment]
The problem is solved . Thanks

**Comment by den-crane** [comment]
hit the same issue with the latest CH 20.3

```
clickhouse-client -q "select number int, toString(number) str, 1/number flt, toDecimal64( 1/(number+1) , 9) dcml, 
toDateTime('2020-01-01 00:00:00') + number time from numbers(100) format ORC"> test_sample.orc

CREATE TABLE test.orc_stream_compressed (int Int64, str String, flt Float64, dcml Decimal64(9), time DateTime) ENGINE = Log();


insert into test.orc1_stream_compressed format ORC
```

orc::TimezoneError, e.what() = Can't open /etc/localtime (version 21.2.3.15 (official build))

**Comment by alexey-milovidov** [comment]
We can add it to Docker containers.

There is no reason to add dependency on tzdata in regular ClickHouse packages.
tzdata is either already installed on server or user can install it manually if they need ORC.

**Comment by alexey-milovidov** [comment]
@filimonov Could you please edit our Dockerfiles?

**Comment by alexey-milovidov** [comment]
@filimonov I will edit Dockerfiles for you... but Alpine images remain.

**Comment by filimonov** [comment]
> @filimonov Could you please edit our Dockerfiles?

Sorry, missed that comment earlier.
