### ISSUE TITLE
Why LEFT JOIN RIGHT JOIN return different result? How to resolve it?

### ISSUE THREAD

**Issue by Fanduzi** [ClickHouse/ClickHouse#14160]
it seems that in clickhouse we must put small table on the right
```
clickhouse --query="SELECT count(*) from dwh.full_orders b RIGHT JOIN dwh.app_users a on a.uid=b.id 
6897617 --count(*)
11.601 --query spent time


clickhouse --query="SELECT count(*) from dwh.app_users a LEFT JOIN dwh.full_orders b on a.id=b.uid 
6042735 --count(*)
873.462 --query spent time
```
but the result is different..(data in tables are not changed)

So I did the following test

Table structure
```
bj2-clickhouse-all-prod-05 default@localhost:9000 [dwh]
:) show create table t1;

SHOW CREATE TABLE t1

┌─statement─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ CREATE TABLE dwh.t1 (`I_ID` String, `CTIME` DateTime) ENGINE = Distributed('ch_cluster_all', 'dwh', 't1_local', rand()) │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

1 rows in set. Elapsed: 0.001 sec. 

bj2-clickhouse-all-prod-05 default@localhost:9000 [dwh]
:) show create table t2;

SHOW CREATE TABLE t2

┌─statement─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ CREATE TABLE dwh.t2 (`I_ID` String, `CTIME` DateTime) ENGINE = Distributed('ch_cluster_all', 'dwh', 't2_local', rand()) │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

1 rows in set. Elapsed: 0.001 sec. 

bj2-clickhouse-all-prod-05 default@localhost:9000 [dwh]
:) show create table t1_local;

SHOW CREATE TABLE t1_local

┌─statement──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ CREATE TABLE dwh.t1_local (`I_ID` String, `CTIME` DateTime) ENGINE = ReplicatedReplacingMergeTree('/clickhouse/dwh/tables/{layer}-{shard}/t1', '{replica}') PARTITION BY toDate(CTIME) ORDER BY I_ID SETTINGS index_granularity = 8192 │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

1 rows in set. Elapsed: 0.001 sec. 

bj2-clickhouse-all-prod-05 default@localhost:9000 [dwh]
:) show create table t2_local;

SHOW CREATE TABLE t2_local

┌─statement──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ CREATE TABLE dwh.t2_local (`I_ID` String, `CTIME` DateTime) ENGINE = ReplicatedReplacingMergeTree('/clickhouse/dwh/tables/{layer}-{shard}/t2', '{replica}') PARTITION BY toDate(CTIME) ORDER BY I_ID SETTINGS index_granularity = 8192 │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

1 rows in set. Elapsed: 0.001 sec. 
````

Data
```
bj2-clickhouse-all-prod-05 default@localhost:9000 [dwh]
:) select * from t1;

SELECT *
FROM t1

┌─I_ID─┬───────────────CTIME─┐
│ 1    │ 2020-08-27 15:24:05 │
│ 2    │ 2020-08-27 15:24:50 │
│ 8    │ 2020-08-27 15:24:50 │
└──────┴─────────────────────┘
┌─I_ID─┬───────────────CTIME─┐
│ 3    │ 2020-08-27 15:24:50 │
│ 5    │ 2020-08-27 15:24:50 │
│ 9    │ 2020-08-27 15:24:50 │
└──────┴─────────────────────┘
┌─I_ID─┬───────────────CTIME─┐
│ 10   │ 2020-08-27 15:24:50 │
│ 3    │ 2020-08-27 15:24:50 │
│ 6    │ 2020-08-27 15:24:50 │
│ 7    │ 2020-08-27 15:24:50 │
└──────┴─────────────────────┘

10 rows in set. Elapsed: 0.003 sec. 

bj2-clickhouse-all-prod-05 default@localhost:9000 [dwh]
:) select * from t2;

SELECT *
FROM t2

┌─I_ID─┬───────────────CTIME─┐
│ 1    │ 2020-08-27 15:25:14 │
└──────┴─────────────────────┘
┌─I_ID─┬───────────────CTIME─┐
│ 2    │ 2020-08-27 15:25:33 │
│ 5    │ 2020-08-27 15:25:33 │
└──────┴─────────────────────┘
┌─I_ID─┬───────────────CTIME─┐
│ 3    │ 2020-08-27 15:25:33 │
│ 3    │ 2020-08-27 15:25:33 │
└──────┴─────────────────────┘

5 rows in set. Elapsed: 0.003 sec. 

bj2-clickhouse-all-prod-05 default@localhost:9000 [dwh]
:) SELECT 
:-]     _shard_num, 
:-]     count(*)
:-] FROM 
:-] (
:-]     SELECT 
:-]         _shard_num, 
:-]         a.*
:-]     FROM dwh.t1 AS a
:-] )
:-] GROUP BY _shard_num
:-]     WITH ROLLUP;

SELECT 
    _shard_num, 
    count(*)
FROM 
(
    SELECT 
        _shard_num, 
        a.*
    FROM dwh.t1 AS a
)
GROUP BY _shard_num
    WITH ROLLUP

┌─_shard_num─┬─count()─┐
│          3 │       3 │
│          2 │       3 │
│          1 │       4 │
└────────────┴─────────┘
┌─_shard_num─┬─count()─┐
│          0 │      10 │
└────────────┴─────────┘

4 rows in set. Elapsed: 0.004 sec. 

bj2-clickhouse-all-prod-05 default@localhost:9000 [dwh]
:) SELECT 
:-]     _shard_num, 
:-]     count(*)
:-] FROM 
:-] (
:-]     SELECT 
:-]         _shard_num, 
:-]         a.*
:-]     FROM dwh.t2 AS a
:-] )
:-] GROUP BY _shard_num
:-]     WITH ROLLUP;

SELECT 
    _shard_num, 
    count(*)
FROM 
(
    SELECT 
        _shard_num, 
        a.*
    FROM dwh.t2 AS a
)
GROUP BY _shard_num
    WITH ROLLUP

┌─_shard_num─┬─count()─┐
│          3 │       2 │
│          2 │       1 │
│          1 │       2 │
└────────────┴─────────┘
┌─_shard_num─┬─count()─┐
│          0 │       5 │
└────────────┴─────────┘

4 rows in set. Elapsed: 0.005 sec. 
```

In Oralce/MySQL, the result are same, but in clickhouse
```
bj2-clickhouse-all-prod-05 default@localhost:9000 [dwh]
:) SELECT 
:-]     a.I_ID, 
:-]     b.I_ID
:-] FROM dwh.t2 AS a
:-] LEFT JOIN dwh.t1 AS b ON a.I_ID = b.I_ID
:-] ORDER BY a.I_ID ASC;

SELECT 
    a.I_ID, 
    b.I_ID
FROM dwh.t2 AS a
LEFT JOIN dwh.t1 AS b ON a.I_ID = b.I_ID
ORDER BY a.I_ID ASC

┌─I_ID─┬─b.I_ID─┐
│ 1    │ 1      │
└──────┴────────┘
┌─I_ID─┬─b.I_ID─┐
│ 2    │ 2      │
│ 3    │ 3      │
│ 3    │ 3      │
│ 3    │ 3      │
│ 3    │ 3      │
└──────┴────────┘
┌─I_ID─┬─b.I_ID─┐
│ 5    │ 5      │
└──────┴────────┘

7 rows in set. Elapsed: 0.006 sec. 

bj2-clickhouse-all-prod-05 default@localhost:9000 [dwh]
:) SELECT 
:-]     a.I_ID, 
:-]     b.I_ID
:-] FROM dwh.t1 AS b
:-] RIGHT JOIN dwh.t2 AS a ON a.I_ID = b.I_ID
:-] ORDER BY a.I_ID ASC;

SELECT 
    a.I_ID, 
    b.I_ID
FROM dwh.t1 AS b
RIGHT JOIN dwh.t2 AS a ON a.I_ID = b.I_ID
ORDER BY a.I_ID ASC

┌─a.I_ID─┬─I_ID─┐
│ 1      │      │
│ 1      │ 1    │
│ 1      │      │
│ 2      │      │
│ 2      │ 2    │
└────────┴──────┘
┌─a.I_ID─┬─I_ID─┐
│ 2      │      │
└────────┴──────┘
┌─a.I_ID─┬─I_ID─┐
│ 3      │ 3    │
│ 3      │ 3    │
└────────┴──────┘
┌─a.I_ID─┬─I_ID─┐
│ 3      │      │
│ 3      │      │
│ 3      │ 3    │
│ 3      │ 3    │
│ 5      │      │
└────────┴──────┘
┌─a.I_ID─┬─I_ID─┐
│ 5      │      │
└────────┴──────┘
┌─a.I_ID─┬─I_ID─┐
│ 5      │ 5    │
└────────┴──────┘

15 rows in set. Elapsed: 0.006 sec. 
```

**Comment by filimonov** [comment]
ClickHouse version?

**Comment by Fanduzi** [comment]
> ClickHouse version?

my fault 
```
:) select version();

SELECT version()

┌─version()─┐
│ 20.3.5.21 │
└───────────┘
```

**Comment by 4ertus2** [comment]
Most probably It's cause JOIN/IN over Distributed table special logic https://clickhouse.tech/docs/en/sql-reference/operators/in/#select-distributed-subqueries

You may expect that JOIN over Distributed would result the same as if tables are placed on one node but it's not always true. At least for now. By default ClickHouse's passes JOIN over Distributed as if dwh.t1 and dwh.t2 are cosharded by some exclusive sharding key so there's no cross-sharded JOINed keys in result. And source node just merge the per-node JOINs altogether without warry about cross-node keys. It's fast but not a general solution.

There's alternative that's called GLOBAL JOIN in ClickHouse SQL dialect. It's a way to first make tables colocated by joining key and then make a JOIN. It makes temporary table on Distributed nodes for right table data. It's slower but works as expected for INNER and LEFT JOIN even if tables are not cosharded right way. It works cause in this case we have all joined rows and could not have unexpected not-joined rows from different nodes. For other OUTER JOINs there's no general solution to return expected result yet. They could return more results than needed for GLOBAL JOIN. It's not OK but you still able to make OUTER JOIN with future filter that removes unexpected rows. Probably we should disable such JOINs by default.

There's also an option https://clickhouse.tech/docs/en/operations/settings/settings/#distributed-product-mode that decide how would ClickHouse interpret a JOIN of Distributed table over Distributed table.

**Comment by Fanduzi** [comment]
> Most probably It's cause JOIN/IN over Distributed table special logic https://clickhouse.tech/docs/en/sql-reference/operators/in/#select-distributed-subqueries
> 
> You may expect that JOIN over Distributed would result the same as if tables are placed on one node but it's not always true. At least for now. By default ClickHouse's passes JOIN over Distributed as if dwh.t1 and dwh.t2 are cosharded by some exclusive sharding key so there's no cross-sharded JOINed keys in result. And source node just merge the per-node JOINs altogether without warry about cross-node keys. It's fast but not a general solution.
> 
> There's alternative that's called GLOBAL JOIN in ClickHouse SQL dialect. It's a way to first make tables colocated by joining key and then make a JOIN. It makes temporary table on Distributed nodes for right table data. It's slower but works as expected for INNER and LEFT JOIN even if tables are not cosharded right way. It works cause in this case we have all joined rows and could not have unexpected not-joined rows from different nodes. For other OUTER JOINs there's no general solution to return expected result yet. They could return more results than needed for GLOBAL JOIN. It's not OK but you still able to make OUTER JOIN with future filter that removes unexpected rows. Probably we should disable such JOINs by default.
> 
> There's also an option https://clickhouse.tech/docs/en/operations/settings/settings/#distributed-product-mode that decide how would ClickHouse interpret a JOIN of Distributed table over Distributed table.

Does this mean that if I want to use OUTER JOIN, I can only use local tables and cannot use sharding, that is, I cannot scale horizontally, otherwise I will not be able to get the correct result set

In fact, I want to optimize the SQL execution speed. I found that clickhouse needs to write the small table at the end of SQL, so my LEFT JOIN was changed to RIGHT JOIN. Is there any way that I can write the small table in the front and get the same query speed as the RIGHT JOIN in my example?
>In my test , put the small table to the end of sql really make sql faster!
>```
>clickhouse --query="SELECT count(*) from dwh.full_orders b RIGHT JOIN dwh.app_users a on a.uid=b.id 
>6897617 --count(*)
>11.601 --query spent time
>
>
>clickhouse --query="SELECT count(*) from dwh.app_users a LEFT JOIN dwh.full_orders b on a.id=b.uid 
>6042735 --count(*)
>873.462 --query spent time
>```

Why does clickhouse decide who to use to drive the table by the order of the table in the SQL? This is too bad..

It seems that clickhouse's usage scenario is really a bit strict. This makes me have to go back to use TIDB, even if I don't want to use it, because we measured that this LEFT JOIN takes 20s in TIDB, which is slower than clickhouse but the result is correct

**Comment by 4ertus2** [comment]
You may try rewrite LEFT JOIN with INNER JOIN and UNION ALL like this
```
SELECT a.id from dwh.app_users a
LEFT JOIN dwh.full_orders b
ON a.id = b.uid
```
```
SELECT a.id FROM dwh.app_users a
GLOBAL INNER JOIN dwh.full_orders b
ON a.id = b.uid
UNION ALL
SELECT a.id FROM dwh.app_users a
WHERE a.id GLOBAL NOT IN (SELECT id FROM dwh.full_orders)
```
Then it's possible to swap tabled in INNER JOIN and filter `dwh.full_orders` with smaller `dwh.app_users`
```
SELECT a.id FROM dwh.full_orders b
GLOBAL INNER JOIN dwh.app_users a
ON a.id = b.uid
UNION ALL
SELECT a.id FROM dwh.app_users a
WHERE a.id GLOBAL NOT IN
(
    SELECT id FROM dwh.full_orders
    WHERE id GLOBAL IN (SELECT id FROM dwh.app_users)
)
```

**Comment by Fanduzi** [comment]
> You may try rewrite LEFT JOIN with INNER JOIN and UNION ALL like this
> 
> ```
> SELECT a.id from dwh.app_users a
> LEFT JOIN dwh.full_orders b
> ON a.id = b.uid
> ```
> 
> ```
> SELECT a.id FROM dwh.app_users a
> GLOBAL INNER JOIN dwh.full_orders b
> ON a.id = b.uid
> UNION ALL
> SELECT a.id FROM dwh.app_users a
> WHERE a.id GLOBAL NOT IN (SELECT id FROM dwh.full_orders)
> ```
> 
> Then it's possible to swap tables in INNER JOIN and filter `dwh.full_orders` with smaller `dwh.app_users`
> 
> ```
> SELECT a.id FROM dwh.full_orders b
> GLOBAL INNER JOIN dwh.app_users a
> ON a.id = b.uid
> UNION ALL
> SELECT a.id FROM dwh.app_users a
> WHERE a.id GLOBAL NOT IN
> (
>     SELECT id FROM dwh.full_orders
>     WHERE id GLOBAL IN (SELECT id FROM dwh.app_users)
> )
> ```

Thank you very much. That's really solved a big problem!

**Comment by l1t1** [comment]
GLOBAL in

**Comment by helifu** [comment]
It is recommended to reopen this issue since it's an implicit and dangerous problem :(
