### ISSUE TITLE
Could I reference the performance test result in a conference?

### ISSUE THREAD

**Issue by achimbab** [ClickHouse/ClickHouse#14162]
@alexey-milovidov 

Hello, 

ClickHouse is an awesome analytical database.

I got a chance to introduce ClickHouse in my company's conference.

This conference isn't world wide, but it's the most biggest one in South Korea.

Could I reference the [performance test result](https://clickhouse.tech/benchmark/dbms/) in the conference?

Sincerely,
Thank you.

**Comment by alexey-milovidov** [comment]
Yes, sure.

Don't forget to mention about the setup (what hardware was used) and keep in mind that some results are outdated (see disclaimer below). Also you can link to instructions to reproduce the results if needed: https://github.com/ClickHouse/ClickHouse/tree/master/benchmark

**Comment by achimbab** [comment]
@alexey-milovidov 
Thank you very much.

**Comment by alexey-milovidov** [comment]
It's also good to pick a couple of third-party benchmarks from the internet.

**Comment by achimbab** [comment]
@alexey-milovidov 
OK, I will search the internet and do benchmark test by myself between clickhouse and other open source column-oriented databases, such as infiniDB and crateDB.

**Comment by achimbab** [comment]
@alexey-milovidov 

Hello.

From my company, developer's online conference has just begun. It was supposed to take place offline but because of pandemic, it is going on online. You can access https://if.kakao.com/session/117 

I decided not to use `performance test result`, but introduced features of ClickHouse to Korea.

Sorry for not translating slides into English, but maybe it is enough to understand for you.

Thank you.

**Comment by alexey-milovidov** [comment]
Thank you! I can read almost 100% info from the slides :)
Maybe we can add Kakao to the page: https://clickhouse.tech/docs/en/introduction/adopters/ ?

**Comment by achimbab** [comment]
@alexey-milovidov 
Of course, Why not?
Thank you!

**Comment by alexey-milovidov** [comment]
@achimbab There is a new version of this benchmark:
https://github.com/ClickHouse/ClickBench

Now it contains more than 20 different analytical DBMS, and it has a 100% open and reproducible methodology.
Many results have been submitted by independent contributors.

**Comment by achimbab** [comment]
@alexey-milovidov 
Thank you a lot.
