### ISSUE TITLE
tmp_fetch_XXX folder prevents the replica from recovering from a failed fetchPart attemp

### ISSUE THREAD

**Issue by yfinkelstein** [ClickHouse/ClickHouse#14197]
**Describe the bug**
While using quorum replication, one of shards was found in a state when quorum was not being achieved because 3 replicas out of 4 were reporting the same error:
```
"Directory tmp_fetch_XXX already exists."
```

 which is thrown here: https://github.com/ClickHouse/ClickHouse/blob/master/src/Storages/MergeTree/DataPartsExchange.cpp#L340

After manually removing this temp folder on one of the replicas the replica has successfully downloaded the missing part and has caught up.

Looking at the code closely, once this temp dir is created there seems to be no code path that would remove it.
In several other places in the same function, there is 
```
disk->removeRecursive(part_download_path);
throw ...
```
kind of code that clears up the temp opening up a path for successful retry. But in the case above retries will fail forever.

**Comment by yfinkelstein** [comment]
Apparently the temp dir is a left-over as a result of possible IO exception thrown by `copyData` here:
https://github.com/ClickHouse/ClickHouse/blob/master/src/Storages/MergeTree/DataPartsExchange.cpp#L365
The solution may be simply to surround copyData with try/catch, invoke `disk->removeRecursive(part_download_path);`, and then rethrow the exception. 
But on line 340 above, id the folder exists - there also should be some sort of recovery code path.

**Comment by yfinkelstein** [comment]
Please confirm that my understanding of the problem is correct and that this simple bug fix will take care of the problem. I can then submit a PR if desired.

**Comment by amosbird** [comment]
I've encountered similar issues and I think your understanding is correct. tmp dir will only be removed after reaching https://github.com/ClickHouse/ClickHouse/blob/master/src/Storages/MergeTree/DataPartsExchange.cpp#L392

**Comment by bobelev** [comment]
Got this errors dozens of times while replicating huge cluster to new hosts
