### ISSUE TITLE
Superset connectivity with clickhouse

### ISSUE THREAD

**Issue by sanjaypocket52** [ClickHouse/ClickHouse#14192]
**Describe the issue**
How to connect clickhouse with superset clickhouse://default@IP:9000/data_lake

It is gave me below error
ERROR: Could not load database driver: clickhouse

while i have installed pip install clickhouse-sqlalchemy

**Comment by den-crane** [comment]
Not related to Clickhouse server. It's a question for Superset community or python-driver community
