### ISSUE TITLE
(ReplicatedMergeTreeRestartingThread): Couldn't start replication: Replica 

### ISSUE THREAD

**Issue by yd1261137568** [ClickHouse/ClickHouse#14208]
version:19.9.5.36
The service suddenly failed to connect
/var/log/clickhouse-server/clickhouse- server.err.log There are hundreds of errors in the file
What is the cause?

2020.08.28 16:25:04.931772 [ 58 ] {} <Error> data_usergroup.t_person_custom_group_imei_3_shard (ReplicatedMergeTreeRestartingThread): Couldn't start replication: Replica /clickhouse/tables/user_group/t_person_custom_group_imei_3_shard/02/replicas/02 appears to be already active. If you're sure it's not, try again in a minute or remove znode /clickhouse/tables/user_group/t_person_custom_group_imei_3_shard/02/replicas/02/is_active manually, DB::Exception: Replica /clickhouse/tables/user_group/t_person_custom_group_imei_3_shard/02/replicas/02 appears to be already active. If you're sure it's not, try again in a minute or remove znode /clickhouse/tables/user_group/t_person_custom_group_imei_3_shard/02/replicas/02/is_active manually, stack trace:
0. clickhouse-server(StackTrace::StackTrace()+0x16) [0x65cbc16]
1. clickhouse-server(DB::Exception::Exception(std::string const&, int)+0x1f) [0x2ffea8f]
2. clickhouse-server(DB::ReplicatedMergeTreeRestartingThread::activateReplica()+0x8b1) [0x5f3cd01]
3. clickhouse-server(DB::ReplicatedMergeTreeRestartingThread::tryStartup()+0x24) [0x5f3ce84]
4. clickhouse-server(DB::ReplicatedMergeTreeRestartingThread::run()+0x520) [0x5f3db20]
5. clickhouse-server(DB::BackgroundSchedulePoolTaskInfo::execute()+0xd1) [0x5a17511]
6. clickhouse-server(DB::BackgroundSchedulePool::threadFunction()+0xaa) [0x5a17dea]
7. clickhouse-server() [0x5a17f94]
8. clickhouse-server(ThreadPoolImpl<std::thread>::worker(std::_List_iterator<std::thread>)+0x1b8) [0x65d4bf8]
9. clickhouse-server() [0x711163f]
10. /lib64/libpthread.so.0() [0x3a0cc079d1]
11. /lib64/libc.so.6(clone+0x6d) [0x3a0c8e89dd]

2020.08.28 16:25:04.934293 [ 58 ] {} <Error> data_usergroup.t_person_custom_group_imei_4_shard (ReplicatedMergeTreeRestartingThread): Couldn't start replication: Replica /clickhouse/tables/user_group/t_person_custom_group_imei_4_shard/02/replicas/02 appears to be already active. If you're sure it's not, try again in a minute or remove znode /clickhouse/tables/user_group/t_person_custom_group_imei_4_shard/02/replicas/02/is_active manually, DB::Exception: Replica /clickhouse/tables/user_group/t_person_custom_group_imei_4_shard/02/replicas/02 appears to be already active. If you're sure it's not, try again in a minute or remove znode /clickhouse/tables/user_group/t_person_custom_group_imei_4_shard/02/replicas/02/is_active manually, stack trace:
0. clickhouse-server(StackTrace::StackTrace()+0x16) [0x65cbc16]
1. clickhouse-server(DB::Exception::Exception(std::string const&, int)+0x1f) [0x2ffea8f]
2. clickhouse-server(DB::ReplicatedMergeTreeRestartingThread::activateReplica()+0x8b1) [0x5f3cd01]
3. clickhouse-server(DB::ReplicatedMergeTreeRestartingThread::tryStartup()+0x24) [0x5f3ce84]
4. clickhouse-server(DB::ReplicatedMergeTreeRestartingThread::run()+0x520) [0x5f3db20]
5. clickhouse-server(DB::BackgroundSchedulePoolTaskInfo::execute()+0xd1) [0x5a17511]
6. clickhouse-server(DB::BackgroundSchedulePool::threadFunction()+0xaa) [0x5a17dea]
7. clickhouse-server() [0x5a17f94]
8. clickhouse-server(ThreadPoolImpl<std::thread>::worker(std::_List_iterator<std::thread>)+0x1b8) [0x65d4bf8]
9. clickhouse-server() [0x711163f]
10. /lib64/libpthread.so.0() [0x3a0cc079d1]
11. /lib64/libc.so.6(clone+0x6d) [0x3a0c8e89dd]

2020.08.28 16:25:04.935748 [ 58 ] {} <Error> data_usergroup.t_person_custom_group_imei_52_shard (ReplicatedMergeTreeRestartingThread): Couldn't start replication: Replica /clickhouse/tables/user_group/t_person_custom_group_imei_52_shard/02/replicas/02 appears to be already active. If you're sure it's not, try again in a minute or remove znode /clickhouse/tables/user_group/t_person_custom_group_imei_52_shard/02/replicas/02/is_active manually, DB::Exception: Replica /clickhouse/tables/user_group/t_person_custom_group_imei_52_shard/02/replicas/02 appears to be already active. If you're sure it's not, try again in a minute or remove znode /clickhouse/tables/user_group/t_person_custom_group_imei_52_shard/02/replicas/02/is_active manually, stack trace:
0. clickhouse-server(StackTrace::StackTrace()+0x16) [0x65cbc16]
1. clickhouse-server(DB::Exception::Exception(std::string const&, int)+0x1f) [0x2ffea8f]
2. clickhouse-server(DB::ReplicatedMergeTreeRestartingThread::activateReplica()+0x8b1) [0x5f3cd01]
3. clickhouse-server(DB::ReplicatedMergeTreeRestartingThread::tryStartup()+0x24) [0x5f3ce84]
4. clickhouse-server(DB::ReplicatedMergeTreeRestartingThread::run()+0x520) [0x5f3db20]
5. clickhouse-server(DB::BackgroundSchedulePoolTaskInfo::execute()+0xd1) [0x5a17511]
6. clickhouse-server(DB::BackgroundSchedulePool::threadFunction()+0xaa) [0x5a17dea]
7. clickhouse-server() [0x5a17f94]
8. clickhouse-server(ThreadPoolImpl<std::thread>::worker(std::_List_iterator<std::thread>)+0x1b8) [0x65d4bf8]
9. clickhouse-server() [0x711163f]
10. /lib64/libpthread.so.0() [0x3a0cc079d1]
11. /lib64/libc.so.6(clone+0x6d) [0x3a0c8e89dd]

2020.08.28 16:25:04.937905 [ 58 ] {} <Error> data_usergroup.t_person_custom_group_imei_55_shard (ReplicatedMergeTreeRestartingThread): Couldn't start replication: Replica /clickhouse/tables/user_group/t_person_custom_group_imei_55_shard/02/replicas/02 appears to be already active. If you're sure it's not, try again in a minute or remove znode /clickhouse/tables/user_group/t_person_custom_group_imei_55_shard/02/replicas/02/is_active manually, DB::Exception: Replica /clickhouse/tables/user_group/t_person_custom_group_imei_55_shard/02/replicas/02 appears to be already active. If you're sure it's not, try again in a minute or remove znode /clickhouse/tables/user_group/t_person_custom_group_imei_55_shard/02/replicas/02/is_active manually, stack trace:
0. clickhouse-server(StackTrace::StackTrace()+0x16) [0x65cbc16]
1. clickhouse-server(DB::Exception::Exception(std::string const&, int)+0x1f) [0x2ffea8f]
2. clickhouse-server(DB::ReplicatedMergeTreeRestartingThread::activateReplica()+0x8b1) [0x5f3cd01]
3. clickhouse-server(DB::ReplicatedMergeTreeRestartingThread::tryStartup()+0x24) [0x5f3ce84]
4. clickhouse-server(DB::ReplicatedMergeTreeRestartingThread::run()+0x520) [0x5f3db20]
5. clickhouse-server(DB::BackgroundSchedulePoolTaskInfo::execute()+0xd1) [0x5a17511]
6. clickhouse-server(DB::BackgroundSchedulePool::threadFunction()+0xaa) [0x5a17dea]
7. clickhouse-server() [0x5a17f94]
8. clickhouse-server(ThreadPoolImpl<std::thread>::worker(std::_List_iterator<std::thread>)+0x1b8) [0x65d4bf8]
9. clickhouse-server() [0x711163f]
10. /lib64/libpthread.so.0() [0x3a0cc079d1]
11. /lib64/libc.so.6(clone+0x6d) [0x3a0c8e89dd]

2020.08.28 16:25:04.939375 [ 58 ] {} <Error> data_usergroup.t_person_custom_group_imei_56_shard (ReplicatedMergeTreeRestartingThread): Couldn't start replication: Replica /clickhouse/tables/user_group/t_person_custom_group_imei_56_shard/02/replicas/02 appears to be already active. If you're sure it's not, try again in a minute or remove znode /clickhouse/tables/user_group/t_person_custom_group_imei_56_shard/02/replicas/02/is_active manually, DB::Exception: Replica /clickhouse/tables/user_group/t_person_custom_group_imei_56_shard/02/replicas/02 appears to be already active. If you're sure it's not, try again in a minute or remove znode /clickhouse/tables/user_group/t_person_custom_group_imei_56_shard/02/replicas/02/is_active manually, stack trace:
0. clickhouse-server(StackTrace::StackTrace()+0x16) [0x65cbc16]
1. clickhouse-server(DB::Exception::Exception(std::string const&, int)+0x1f) [0x2ffea8f]
2. clickhouse-server(DB::ReplicatedMergeTreeRestartingThread::activateReplica()+0x8b1) [0x5f3cd01]
3. clickhouse-server(DB::ReplicatedMergeTreeRestartingThread::tryStartup()+0x24) [0x5f3ce84]
4. clickhouse-server(DB::ReplicatedMergeTreeRestartingThread::run()+0x520) [0x5f3db20]
5. clickhouse-server(DB::BackgroundSchedulePoolTaskInfo::execute()+0xd1) [0x5a17511]
6. clickhouse-server(DB::BackgroundSchedulePool::threadFunction()+0xaa) [0x5a17dea]
7. clickhouse-server() [0x5a17f94]
8. clickhouse-server(ThreadPoolImpl<std::thread>::worker(std::_List_iterator<std::thread>)+0x1b8) [0x65d4bf8]
9. clickhouse-server() [0x711163f]
10. /lib64/libpthread.so.0() [0x3a0cc079d1]
11. /lib64/libc.so.6(clone+0x6d) [0x3a0c8e89dd]

2020.08.28 16:25:04.942390 [ 58 ] {} <Error> data_usergroup.t_person_custom_group_imei_5_shard (ReplicatedMergeTreeRestartingThread): Couldn't start replication: Replica /clickhouse/tables/user_group/t_person_custom_group_imei_5_shard/02/replicas/02 appears to be already active. If you're sure it's not, try again in a minute or remove znode /clickhouse/tables/user_group/t_person_custom_group_imei_5_shard/02/replicas/02/is_active manually, DB::Exception: Replica /clickhouse/tables/user_group/t_person_custom_group_imei_5_shard/02/replicas/02 appears to be already active. If you're sure it's not, try again in a minute or remove znode /clickhouse/tables/user_group/t_person_custom_group_imei_5_shard/02/replicas/02/is_active manually, stack trace:
0. clickhouse-server(StackTrace::StackTrace()+0x16) [0x65cbc16]
1. clickhouse-server(DB::Exception::Exception(std::string const&, int)+0x1f) [0x2ffea8f]
2. clickhouse-server(DB::ReplicatedMergeTreeRestartingThread::activateReplica()+0x8b1) [0x5f3cd01]
3. clickhouse-server(DB::ReplicatedMergeTreeRestartingThread::tryStartup()+0x24) [0x5f3ce84]
4. clickhouse-server(DB::ReplicatedMergeTreeRestartingThread::run()+0x520) [0x5f3db20]
5. clickhouse-server(DB::BackgroundSchedulePoolTaskInfo::execute()+0xd1) [0x5a17511]
6. clickhouse-server(DB::BackgroundSchedulePool::threadFunction()+0xaa) [0x5a17dea]
7. clickhouse-server() [0x5a17f94]
8. clickhouse-server(ThreadPoolImpl<std::thread>::worker(std::_List_iterator<std::thread>)+0x1b8) [0x65d4bf8]
9. clickhouse-server() [0x711163f]
10. /lib64/libpthread.so.0() [0x3a0cc079d1]
11. /lib64/libc.so.6(clone+0x6d) [0x3a0c8e89dd]

2020.08.28 16:25:04.943719 [ 58 ] {} <Error> data_usergroup.t_person_custom_group_imei_61_shard (ReplicatedMergeTreeRestartingThread): Couldn't start replication: Replica /clickhouse/tables/user_group/t_person_custom_group_imei_61_shard/02/replicas/02 appears to be already active. If you're sure it's not, try again in a minute or remove znode /clickhouse/tables/user_group/t_person_custom_group_imei_61_shard/02/replicas/02/is_active manually, DB::Exception: Replica /clickhouse/tables/user_group/t_person_custom_group_imei_61_shard/02/replicas/02 appears to be already active. If you're sure it's not, try again in a minute or remove znode /clickhouse/tables/user_group/t_person_custom_group_imei_61_shard/02/replicas/02/is_active manually, stack trace:
0. clickhouse-server(StackTrace::StackTrace()+0x16) [0x65cbc16]
1. clickhouse-server(DB::Exception::Exception(std::string const&, int)+0x1f) [0x2ffea8f]
2. clickhouse-server(DB::ReplicatedMergeTreeRestartingThread::activateReplica()+0x8b1) [0x5f3cd01]
3. clickhouse-server(DB::ReplicatedMergeTreeRestartingThread::tryStartup()+0x24) [0x5f3ce84]
4. clickhouse-server(DB::ReplicatedMergeTreeRestartingThread::run()+0x520) [0x5f3db20]
5. clickhouse-server(DB::BackgroundSchedulePoolTaskInfo::execute()+0xd1) [0x5a17511]
6. clickhouse-server(DB::BackgroundSchedulePool::threadFunction()+0xaa) [0x5a17dea]
7. clickhouse-server() [0x5a17f94]
8. clickhouse-server(ThreadPoolImpl<std::thread>::worker(std::_List_iterator<std::thread>)+0x1b8) [0x65d4bf8]
9. clickhouse-server() [0x711163f]
10. /lib64/libpthread.so.0() [0x3a0cc079d1]
11. /lib64/libc.so.6(clone+0x6d) [0x3a0c8e89dd]

2020.08.28 16:25:04.946173 [ 58 ] {} <Error> data_usergroup.t_person_custom_group_imei_63_shard (ReplicatedMergeTreeRestartingThread): Couldn't start replication: Replica /clickhouse/tables/user_group/t_person_custom_group_imei_63_shard/02/replicas/02 appears to be already active. If you're sure it's not, try again in a minute or remove znode /clickhouse/tables/user_group/t_person_custom_group_imei_63_shard/02/replicas/02/is_active manually, DB::Exception: Replica /clickhouse/tables/user_group/t_person_custom_group_imei_63_shard/02/replicas/02 appears to be already active. If you're sure it's not, try again in a minute or remove znode /clickhouse/tables/user_group/t_person_custom_group_imei_63_shard/02/replicas/02/is_active manually, stack trace:
0. clickhouse-server(StackTrace::StackTrace()+0x16) [0x65cbc16]
1. clickhouse-server(DB::Exception::Exception(std::string const&, int)+0x1f) [0x2ffea8f]
2. clickhouse-server(DB::ReplicatedMergeTreeRestartingThread::activateReplica()+0x8b1) [0x5f3cd01]
3. clickhouse-server(DB::ReplicatedMergeTreeRestartingThread::tryStartup()+0x24) [0x5f3ce84]
4. clickhouse-server(DB::ReplicatedMergeTreeRestartingThread::run()+0x520) [0x5f3db20]
5. clickhouse-server(DB::BackgroundSchedulePoolTaskInfo::execute()+0xd1) [0x5a17511]
6. clickhouse-server(DB::BackgroundSchedulePool::threadFunction()+0xaa) [0x5a17dea]
7. clickhouse-server() [0x5a17f94]
8. clickhouse-server(ThreadPoolImpl<std::thread>::worker(std::_List_iterator<std::thread>)+0x1b8) [0x65d4bf8]
9. clickhouse-server() [0x711163f]
10. /lib64/libpthread.so.0() [0x3a0cc079d1]
11. /lib64/libc.so.6(clone+0x6d) [0x3a0c8e89dd]

2020.08.28 16:25:04.947533 [ 58 ] {} <Error> data_usergroup.t_person_custom_group_imei_64_shard (ReplicatedMergeTreeRestartingThread): Couldn't start replication: Replica /clickhouse/tables/user_group/t_person_custom_group_imei_64_shard/02/replicas/02 appears to be already active. If you're sure it's not, try again in a minute or remove znode /clickhouse/tables/user_group/t_person_custom_group_imei_64_shard/02/replicas/02/is_active manually, DB::Exception: Replica /clickhouse/tables/user_group/t_person_custom_group_imei_64_shard/02/replicas/02 appears to be already active. If you're sure it's not, try again in a minute or remove znode /clickhouse/tables/user_group/t_person_custom_group_imei_64_shard/02/replicas/02/is_active manually, stack trace:
0. clickhouse-server(StackTrace::StackTrace()+0x16) [0x65cbc16]
1. clickhouse-server(DB::Exception::Exception(std::string const&, int)+0x1f) [0x2ffea8f]
2. clickhouse-server(DB::ReplicatedMergeTreeRestartingThread::activateReplica()+0x8b1) [0x5f3cd01]
3. clickhouse-server(DB::ReplicatedMergeTreeRestartingThread::tryStartup()+0x24) [0x5f3ce84]
4. clickhouse-server(DB::ReplicatedMergeTreeRestartingThread::run()+0x520) [0x5f3db20]
5. clickhouse-server(DB::BackgroundSchedulePoolTaskInfo::execute()+0xd1) [0x5a17511]
6. clickhouse-server(DB::BackgroundSchedulePool::threadFunction()+0xaa) [0x5a17dea]
7. clickhouse-server() [0x5a17f94]
8. clickhouse-server(ThreadPoolImpl<std::thread>::worker(std::_List_iterator<std::thread>)+0x1b8) [0x65d4bf8]
9. clickhouse-server() [0x711163f]
10. /lib64/libpthread.so.0() [0x3a0cc079d1]
11. /lib64/libc.so.6(clone+0x6d) [0x3a0c8e89dd]

2020.08.28 16:25:04.947843 [ 52 ] {} <Error> data_usergroup.t_person_custom_group_imei_26_shard (ReplicatedMergeTreeRestartingThread): Couldn't start replication: Replica /clickhouse/tables/user_group/t_person_custom_group_imei_26_shard/02/replicas/02 appears to be already active. If you're sure it's not, try again in a minute or remove znode /clickhouse/tables/user_group/t_person_custom_group_imei_26_shard/02/replicas/02/is_active manually, DB::Exception: Replica /clickhouse/tables/user_group/t_person_custom_group_imei_26_shard/02/replicas/02 appears to be already active. If you're sure it's not, try again in a minute or remove znode /clickhouse/tables/user_group/t_person_custom_group_imei_26_shard/02/replicas/02/is_active manually, stack trace:
0. clickhouse-server(StackTrace::StackTrace()+0x16) [0x65cbc16]
1. clickhouse-server(DB::Exception::Exception(std::string const&, int)+0x1f) [0x2ffea8f]
2. clickhouse-server(DB::ReplicatedMergeTreeRestartingThread::activateReplica()+0x8b1) [0x5f3cd01]
3. clickhouse-server(DB::ReplicatedMergeTreeRestartingThread::tryStartup()+0x24) [0x5f3ce84]
4. clickhouse-server(DB::ReplicatedMergeTreeRestartingThread::run()+0x520) [0x5f3db20]
5. clickhouse-server(DB::BackgroundSchedulePoolTaskInfo::execute()+0xd1) [0x5a17511]
6. clickhouse-server(DB::BackgroundSchedulePool::threadFunction()+0xaa) [0x5a17dea]
7. clickhouse-server() [0x5a17f94]
8. clickhouse-server(ThreadPoolImpl<std::thread>::worker(std::_List_iterator<std::thread>)+0x1b8) [0x65d4bf8]
9. clickhouse-server() [0x711163f]
10. /lib64/libpthread.so.0() [0x3a0cc079d1]
11. /lib64/libc.so.6(clone+0x6d) [0x3a0c8e89dd]

2020.08.28 16:25:04.948965 [ 58 ] {} <Error> data_usergroup.t_person_custom_group_imei_65_shard (ReplicatedMergeTreeRestartingThread): Couldn't start replication: Replica /clickhouse/tables/user_group/t_person_custom_group_imei_65_shard/02/replicas/02 appears to be already active. If you're sure it's not, try again in a minute or remove znode /clickhouse/tables/user_group/t_person_custom_group_imei_65_shard/02/replicas/02/is_active manually, DB::Exception: Replica /clickhouse/tables/user_group/t_person_custom_group_imei_65_shard/02/replicas/02 appears to be already active. If you're sure it's not, try again in a minute or remove znode /clickhouse/tables/user_group/t_person_custom_group_imei_65_shard/02/replicas/02/is_active manually, stack trace:
0. clickhouse-server(StackTrace::StackTrace()+0x16) [0x65cbc16]
1. clickhouse-server(DB::Exception::Exception(std::string const&, int)+0x1f) [0x2ffea8f]
2. clickhouse-server(DB::ReplicatedMergeTreeRestartingThread::activateReplica()+0x8b1) [0x5f3cd01]
3. clickhouse-server(DB::ReplicatedMergeTreeRestartingThread::tryStartup()+0x24) [0x5f3ce84]
4. clickhouse-server(DB::ReplicatedMergeTreeRestartingThread::run()+0x520) [0x5f3db20]
5. clickhouse-server(DB::BackgroundSchedulePoolTaskInfo::execute()+0xd1) [0x5a17511]
6. clickhouse-server(DB::BackgroundSchedulePool::threadFunction()+0xaa) [0x5a17dea]
7. clickhouse-server() [0x5a17f94]
8. clickhouse-server(ThreadPoolImpl<std::thread>::worker(std::_List_iterator<std::thread>)+0x1b8) [0x65d4bf8]
9. clickhouse-server() [0x711163f]
10. /lib64/libpthread.so.0() [0x3a0cc079d1]
11. /lib64/libc.so.6(clone+0x6d) [0x3a0c8e89dd]

**Comment by woozhijun** [comment]
version: 19.13.3.16，
we have the same problem.

**Comment by filimonov** [comment]
You are using the version which is not supported anymore. Please update to one of the recent versions, and if the issue reproduces - open a new issue with details.

**Comment by filimonov** [comment]
`appears to be already active. If you're sure it's not, try again in a minute or remove znode` it may mean some misconfiguratio (check the macros)

**Comment by saurabhdaga-merkle** [comment]
@woozhijun @yd1261137568 
were you able to fix this ?

I am seeing the same error in 19.17.5

For me, it's happening on one of the machines in a 4 node cluster.

**Comment by woozhijun** [comment]
> @woozhijun @yd1261137568 were you able to fix this ?
> 
> I am seeing the same error in 19.17.5
> 
> For me, it's happening on one of the machines in a 4 node cluster.
> 
> Did you do a version upgrade ?

We have upgraded v21.3.6.55, but it has not been solved.  
I Hope to seek help， Thx
