### ISSUE TITLE
is it necessary the clickhouse server has access on the mysql server when using MaterializeMySQL?

### ISSUE THREAD

**Issue by l1t1** [ClickHouse/ClickHouse#14205]
since the binlog file is on the mysql server.

Make sure to check documentation https://clickhouse.yandex/docs/en/ first. If the question is concise and probably has a short answer, asking it in Telegram chat https://telegram.me/clickhouse_en is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

If you still prefer GitHub issues, remove all this text and ask your question here.

**Comment by zhang2014** [comment]
The MaterializeMySQL database engine uses the MySQL protocol to access MySQL historical data and consume MySQL new data(so, we need to ensure that ClickHouse has access to the given MySQL port and the given MySQL user must have the required privileges. required privileges: `SELECT`, `RELOAD`, `SUPER`, `REPLICATION SLAVE`, `REPLICATION CLIENT`)

**Comment by l1t1** [comment]
thanks

**Comment by zhang2014** [comment]
Maybe we can close this issue?
