### ISSUE TITLE
Secondary index performance expectation

### ISSUE THREAD

**Issue by iameugenejo** [ClickHouse/ClickHouse#14200]
Hello,

I'm testing out the secondary index feature, and I'd like to know what to expect.

I have this Replicated Materialized View (obfuscated irrelevant field names) - 
```sql
CREATE MATERIALIZED VIEW sample_1d.logs
(
    `a` UInt64 DEFAULT CAST(0, 'UInt64'),
    `b` UInt64 DEFAULT CAST(0, 'UInt64'),
    `c` UInt64,
    `d` LowCardinality(String),
    `e` UInt8 DEFAULT 1,
    `f` Date DEFAULT toDate(toStartOfDay(timestamp)),
    `timestamp` DateTime,
    `partition_code` String,
    `h` LowCardinality(String),
    `i` LowCardinality(String) DEFAULT CAST('', 'LowCardinality(String)'),
    `j` LowCardinality(String),
    `k` LowCardinality(String),
    `l` LowCardinality(String) DEFAULT CAST('', 'LowCardinality(String)'),
    `m` LowCardinality(String),
    `n` UInt32,
    `o` LowCardinality(String),
    `p` String,
    `q` String,
    `r` String,
    `user_agent` LowCardinality(String),
    `s` LowCardinality(String) DEFAULT CAST('', 'LowCardinality(String)'),
    `asn` UInt32 DEFAULT 0,
    `as_org` LowCardinality(String) DEFAULT CAST('', 'LowCardinality(String)'),
    `isp` LowCardinality(String) DEFAULT CAST('', 'LowCardinality(String)'),
    `region_name` LowCardinality(String) DEFAULT CAST('', 'LowCardinality(String)'),
    `city_name` LowCardinality(String) DEFAULT CAST('', 'LowCardinality(String)'),
    `t` String,
    `u` String,
    `v` String,
    `cnt` UInt64
)
ENGINE = ReplicatedSummingMergeTree('/clickhouse/tables/{layer}-{shard}/sample_1d.logs', '{replica}')
PARTITION BY partition_code
ORDER BY (a, b, c, d, e, f, timestamp, h, i, j, k, l, m, n, o, p, q, r, user_agent, s, asn, as_org, isp, region_name, city_name, t, u, v)
TTL timestamp + toIntervalDay(94)
SETTINGS index_granularity = 8192 AS
SELECT
    a,
    b,
    c,
    d,
    e,
    f,
    toStartOfDay(timestamp) AS timestamp,
    substring(partition_code, 1, 10) AS partition_code,
    h,
    i,
    j,
    k,
    l,
    m,
    n,
    o,
    p,
    q,
    r,
    user_agent,
    s,
    asn,
    as_org,
    isp,
    region_name,
    city_name,
    t,
    u,
    v,
    sum(cnt) AS cnt
FROM sample.logs
GROUP BY
    a,
    n,
    c,
    d,
    e,
    f,
    timestamp,
    partition_code,
    h,
    i,
    j,
    k,
    l,
    m,
    n,
    o,
    p,
    q,
    r,
    user_agent,
    s,
    asn,
    as_org,
    isp,
    region_name,
    city_name,
    t,
    u,
    v
```

I ran the following query before adding a secondary index - 
```sql
     select timestamp, city_name, count() 
       from sample_1d.logs 
     where timestamp >= '2020-08-01 00:00:00' and timestamp < '2020-08-25 00:00:00' 
         and user_agent = '' 
group by timestamp, city_name 
order by timestamp
```

And produced the following stats -
```bash
1611707 rows in set. Elapsed: 7.318 sec. Processed 223.95 million rows, 2.00 GB (30.60 million rows/s., 273.84 MB/s.)
```

Number of rows with `user_agent = ""` within the time range is 107393773

Total number of rows within the time range is 293180409

About **63%** of the data within the range is what I'm filtering out with the query.

I ran the following to add an index on `user_agent` - 
```sql
ALTER TABLE sample_1d.`.inner.logs` ADD INDEX idx_user_agent user_agent TYPE set(0) GRANULARITY 1
OPTIMIZE TABLE sample_1d.`.inner.logs` FINAL
```

After that, I ran the same query and that produced the following stats -
```
1611707 rows in set. Elapsed: 6.084 sec. Processed 202.48 million rows, 1.80 GB (33.28 million rows/s., 295.56 MB/s.)
```

I'm only seeing 10% improvement with this index.

What are the variables that cause such little improvement?

Is it possible the optimization to finish creating the index didn't work?

I tried `MATERIALIZE INDEX idx_user_agent` and it didn't do anything.

That command is even stuck in `system.mutations` for days, with error -
```Code: 49, e.displayText() = DB::Exception: Part a83fd13795ab07f06fd6504529d5d912_2239_9526_32_14698 intersects previous part a83fd13795ab07f06fd6504529d5d912_2228_2243_3 (state Committed). It is a bug. (version 20.5.4.40 (official build))```

I tried `MATERIALIZE INDEX idx_user_agent ON PARTITION {PARTITION_CODE}` for all the partitions the above query is supposed to touch, and all of those commands are stuck like above.

Please advise.

**Comment by genzgd** [comment]
ClickHouse does not have conventional secondary b-tree indexes.  Indexes are skip indexes, and in most cases if the indexed expression is not correlated with the ClickHouse primary/ORDER BY index, data cannot be skipped and the index provides no meaningful benefit.   You can find additional detail on the web, and ClickHouse Inc. will soon be publishing a brief article that explains in more depth.

The stuck mutation is not specific to secondary indexes, and was presumably caused by a bug.  Several bugs in this area have been fixed since version 20.5.
