### ISSUE TITLE
Make a kafka_error_log table to save kafka msg error.

### ISSUE THREAD

**Issue by amuluowin** [ClickHouse/ClickHouse#14201]
**Use case**
When Kafka engine consumes an error, it will stop consumes and i don't know what happen.

**Describe the solution you'd like**
When Kafka engine consumes an error, I can skip the error message and continue to consume, prevent the message backlog, and record the error message body and the cause of the error to facilitate tracking of the problem.

**Comment by ramazanpolat** [comment]
I would like to add some more detail for this feature.

* Since KafkaEngine is bidirectional, both producer and consumer errors should be logged. 
* Error log should indicate the database and table name which uses KafkaEngine.
* Error log should have a DateTime column indicating date and time of the incident.
* Error log for a producer should contain data to be inserted in KafkaEngine table.

**Comment by filimonov** [comment]
I was thinking about just put the errors (together with unparsed messages) inside a rows generated by Kafka engine.

And later on MV level you can decide what to do with them (drop/store in table/push somewhere etc)

Logfile - not sure if good (they are not accessible if you have only clickhouse shell). 

For producer - questionable. What kind of producer  errors you want to catch this way?

**Comment by ramazanpolat** [comment]
@filimonov putting unparsed rows into KafkaEngine is a great idea but how come a MV can know if it is an unparsed message or not? How do we differ between valid and invalid messages?

For example, `MV1` watches the KafkaEnfine table and tries to parse the message and if its is a valid message, `MV1` puts it into the `TABLE1`. In the same time `MV2` also watching the same KafkaEngine table for errors and it directs the unparsed messages to `TABLE1_PARSE_ERROR` table. So how would `MV2` know that `MV1` couldn't parse it?

For producer errors, if somehow producer cannot send the message to Kafka (cluster down/there is no available leader/acks not fullfilled etc) after some retry (if producer is configured with `retries>0` ) producer stops sending that particular message to Kafka (Note: I'm new to Kafka, I may be wrong on this). Users would want to know about this.

**Comment by filimonov** [comment]
> How do we differ between valid and invalid messages?

# MV collecting errors
 Select _error_message, _topic, _partition, _offset, _raw_messafe from kafka_table where _error_code <> 0;
# MV collecting data 
Select * from kafka_table where _error_code=0;

Or smth similar

**Comment by filimonov** [comment]
> Users would want to know about this.

They will know with exception message, why suppress exceptions and write logs silently?

**Comment by ramazanpolat** [comment]
Let's say there are more than 50 clients each has a different software inserting data to my table (KafkaEngine). 
In this scenario, each and every one of the client software has to notify me about unsuccessful inserts and I have to ask for the data which they couldn't insert to see what is wrong with the data. Or maybe data is fine but somehow there was a problem in my Kafka cluster.

Or, if there would be an error table for failed inserts into KafkaEngine, I could write a single WATCH query(LiveView) to watch the error table to be notified about failed inserts instantly and I would be able to see the data and the problem without even clients contact me.

You see I like to put ClickHouse in the center of my architecture, it's not just a database, it is much more than that.

I also have a dream that one day, the output of WATCH queries would be chainable to other SQL queries. Therefore I would chain the WATCH output to an URL table engine which is a REST service that sends a Telegram message to me : )

**Comment by filimonov** [comment]
> Let's say there are more than 50 clients each has a different software inserting data to my table (KafkaEngine).
> In this scenario, each and every one of the client software has to notify me about unsuccessful inserts and I have to ask for the data which they couldn't insert to see what is wrong with the data. Or maybe data is fine but somehow there was a problem in my Kafka cluster.

That sounds like you just need a counter like `KafkaProducerErrors` inside system.events and an alert when it grows.

**Comment by azat** [comment]
>When Kafka engine consumes an error, I can skip the error message and continue to consume, prevent the message backlog, and record the error message body and the cause of the error to facilitate tracking of the problem.

As a workaround **for now** the following can be used:

```sql
select * from system.text_log where logger_name like '%Kafka%'
```

This will include not only parsing errors, but they will be included too.

**Comment by amuluowin** [comment]
> > When Kafka engine consumes an error, I can skip the error message and continue to consume, prevent the message backlog, and record the error message body and the cause of the error to facilitate tracking of the problem.
> 
> As a workaround **for now** the following can be used:
> 
> select * from system.text_log where logger_name like '%Kafka%'
> ![](chrome-extension://mdcffelghikdiafnfodjlgllenhlnejl/icons/copy.png)
> This will include not only parsing errors, but they will be included too.

**Comment by amuluowin** [comment]
> > When Kafka engine consumes an error, I can skip the error message and continue to consume, prevent the message backlog, and record the error message body and the cause of the error to facilitate tracking of the problem.
> 
> As a workaround **for now** the following can be used:
> 
> select * from system.text_log where logger_name like '%Kafka%'
> ![](chrome-extension://mdcffelghikdiafnfodjlgllenhlnejl/icons/copy.png)
> This will include not only parsing errors, but they will be included too.

but `system.text_log` has no save the msg body and the log will more and more

**Comment by amuluowin** [comment]
> > When Kafka engine consumes an error, I can skip the error message and continue to consume, prevent the message backlog, and record the error message body and the cause of the error to facilitate tracking of the problem.
> 
> As a workaround **for now** the following can be used:
> 
> select * from system.text_log where logger_name like '%Kafka%'
> ![](chrome-extension://mdcffelghikdiafnfodjlgllenhlnejl/icons/copy.png)
> This will include not only parsing errors, but they will be included too.

but system.text_log has no save the msg body and the log will more and more

**Comment by amuluowin** [comment]
but system.text_log has no save the msg body and the log will more and more

> > When Kafka engine consumes an error, I can skip the error message and continue to consume, prevent the message backlog, and record the error message body and the cause of the error to facilitate tracking of the problem.
> 
> As a workaround **for now** the following can be used:
> 
> select * from system.text_log where logger_name like '%Kafka%'
> ![](chrome-extension://mdcffelghikdiafnfodjlgllenhlnejl/icons/copy.png)
> This will include not only parsing errors, but they will be included too.

but `system.text_log` has no save the msg body and the log will more and more

**Comment by azat** [comment]
First of all https://github.com/ClickHouse/ClickHouse/issues/14201#issuecomment-683350463 was just a work around, I'm not insisting, but

>but system.text_log has no save the msg body

There is `message` column.

>and the log will more and more

You can use materialize view to duplicate the into separate table.

But again this is just a work around (i.e. if you need this now, and don't want to wait, since even if this will be done it is unlikely will be backported)

**Comment by amuluowin** [comment]
> First of all [#14201 (comment)](https://github.com/ClickHouse/ClickHouse/issues/14201#issuecomment-683350463) was just a work around, I'm not insisting, but
> 
> > but system.text_log has no save the msg body
> 
> There is `message` column.
> 
> > and the log will more and more
> 
> You can use materialize view to duplicate the into separate table.
> 
> But again this is just a work around (i.e. if you need this now, and don't want to wait, since even if this will be done it is unlikely will be backported)

Thanks! Is a good temporary solution

**Comment by amuluowin** [comment]
> I was thinking about just put the errors (together with unparsed messages) inside a rows generated by Kafka engine.
> 
> And later on MV level you can decide what to do with them (drop/store in table/push somewhere etc)
> 
> Logfile - not sure if good (they are not accessible if you have only clickhouse shell).
> 
> For producer - questionable. What kind of producer errors you want to catch this way?

I think mark a error flag to the Kafka engine just find,then i can MV to TABLE by mark flag.

**Comment by alexey-milovidov** [comment]
BTW, it's Ok to implement this feature with another SystemLog table.

**Comment by ramazanpolat** [comment]
> BTW, it's Ok to implement this feature with another SystemLog table.

I think proposal @filimonov 's proposal (using a MV to get parse errors like `Select * from kafka_table where _error_code=0;`) is way better than a SystemLog table since it will give users more freedom.

**Comment by UnamedRus** [comment]
It has been done in this pr: https://github.com/ClickHouse/ClickHouse/pull/21850

It available starting from 21.6

**Comment by filimonov** [comment]
See also https://github.com/ClickHouse/ClickHouse/pull/20249#issuecomment-779054737

**Comment by filimonov** [comment]
Let's close it. It's possible to redirect the errors manually where needed now. Other options described https://github.com/ClickHouse/ClickHouse/pull/20249#issuecomment-779054737 can also be implemented one day.
