### ISSUE TITLE
Update documentation on Docker hub

### ISSUE THREAD

**Issue by ZarubinArtem** [ClickHouse/ClickHouse#1421]
Clickhouse docs on Docker Hub is very poor. There are a lot of questions what to do next:

- how to connect from CLI, how to install specific one. What about connection string for 3rd-party tools, like Datagrip, etc?
- are there any environment variables? Root name, passwords, etc
It is just a few quick questions when container is running.
Just compare ClickHouse documentation on Docker Hub with Postgres/Redis/Mongo/whatever one. All of them has a much more confidence what to do and how to do things.

**Comment by ztlpn** [comment]
Great suggestion. I'll try to improve it a bit.

**Comment by alexey-milovidov** [comment]
We did not solve this issue.
