### ISSUE TITLE
MaterializeMySQL unable to handle 'COMMIT' log may cause synced DB inaccessible

### ISSUE THREAD

**Issue by liangli1213** [ClickHouse/ClickHouse#14235]
It seems MaterializeMySQL not able to handle below bin log events, hence cause exception, the problem is high frequency occur of the exception may cause MaterializeMySQLSyncThread crash (I guess, the phenomenon is the synced DB in ClickHouse is not accessible)

My suggestion is, if such log event is harmless, we just skip it.

> #200829 16:15:00 server id 936  end_log_pos 710243420 CRC32 0x0fe88b7e  Xid = 13469366
> COMMIT/*!*/;

Exception:

> 2020.08.29 16:41:02.696328 [ 104835 ] {} <Error> MaterializeMySQLSyncThread(): Query EXTERNAL DDL FROM MySQL(host_monitor, host_monitor) COMMIT wasn't finished successfully: Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 115 ('COMMIT'): COMMIT. Expected one of: RENAME DATABASE, TRUNCATE, RENAME TABLE, DROP query, RENAME DICTIONARY, DETACH, RENAME query, DROP, create query, CREATE, EXCHANGE TABLES, ALTER TABLE, alter query, Stack trace (when copying this message, always include the lines below):
> 
> 0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x1a7d7400 in /usr/bin/clickhouse
> 1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xff8f78d in /usr/bin/clickhouse
> 2. ? @ 0x183f6741 in /usr/bin/clickhouse
> 3. ? @ 0x177a3d6e in /usr/bin/clickhouse
> 4. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool) @ 0x177a5e7f in /usr/bin/clickhouse
> 5. ? @ 0x17367e84 in /usr/bin/clickhouse
> 6. DB::MaterializeMySQLSyncThread::onEvent(DB::MaterializeMySQLSyncThread::Buffers&, std::__1::shared_ptr<DB::MySQLReplication::EventBase> const&, DB::MaterializeMetadata&) @ 0x1736ee86 in /usr/bin/clickhouse
> 7. DB::MaterializeMySQLSyncThread::synchronization(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x173707bf in /usr/bin/clickhouse
> 8. ? @ 0x17370ba6 in /usr/bin/clickhouse
> 9. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xffbf517 in /usr/bin/clickhouse
> 10. ? @ 0xffbdb53 in /usr/bin/clickhouse
> 11. start_thread @ 0x7dd5 in /usr/lib64/libpthread-2.17.so
> 12. clone @ 0xfdead in /usr/lib64/libc-2.17.so
>  (version 20.8.1.4474 (official build))
> 2020.08.29 16:41:02.696498 [ 104835 ] {} <Error> MaterializeMySQLSyncThread: Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 115 ('COMMIT'): COMMIT. Expected one of: RENAME DATABASE, TRUNCATE, RENAME TABLE, DROP query, RENAME DICTIONARY, DETACH, RENAME query, DROP, create query, CREATE, EXCHANGE TABLES, ALTER TABLE, alter query, Stack trace (when copying this message, always include the lines below):
> 
> 0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x1a7d7400 in /usr/bin/clickhouse
> 1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xff8f78d in /usr/bin/clickhouse
> 2. ? @ 0x183f6741 in /usr/bin/clickhouse
> 3. ? @ 0x177a3d6e in /usr/bin/clickhouse
> 4. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool) @ 0x177a5e7f in /usr/bin/clickhouse
> 5. ? @ 0x17367e84 in /usr/bin/clickhouse
> 6. DB::MaterializeMySQLSyncThread::onEvent(DB::MaterializeMySQLSyncThread::Buffers&, std::__1::shared_ptr<DB::MySQLReplication::EventBase> const&, DB::MaterializeMetadata&) @ 0x1736ee86 in /usr/bin/clickhouse
> 7. DB::MaterializeMySQLSyncThread::synchronization(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x173707bf in /usr/bin/clickhouse
> 8. ? @ 0x17370ba6 in /usr/bin/clickhouse
> 9. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xffbf517 in /usr/bin/clickhouse
> 10. ? @ 0xffbdb53 in /usr/bin/clickhouse
> 11. start_thread @ 0x7dd5 in /usr/lib64/libpthread-2.17.so
> 12. clone @ 0xfdead in /usr/lib64/libc-2.17.so
>  (version 20.8.1.4474 (official build))

**Additional context**
I'm using MySQL slave as the source of ClickHouse

**Comment by liangli1213** [comment]
@zhang2014 @BohuTANG

**Comment by liangli1213** [comment]
I have dig more and found that there's continuous empty transaction generated, like follows, 

```
# at 25921966
#200829 18:10:39 server id 936  end_log_pos 25922034 CRC32 0x7615ebf4   Query   thread_id=948   exec_time=0     error_code=0
SET TIMESTAMP=1598695839/*!*/;
BEGIN
/*!*/;
# at 25922034
#200829 18:10:39 server id 936  end_log_pos 25922103 CRC32 0x0edec313   Query   thread_id=948   exec_time=0     error_code=0
SET TIMESTAMP=1598695839/*!*/;
COMMIT
/*!*/;
```

it seems MaterializeMySQLSyncThread are able to handle ```COMMIT/*!*/```, but unable to handle

```
COMMIT
/*!*/;
```
So please fix it.

**Comment by BohuTANG** [comment]
what's the MySQL side SQL looks like?

**Comment by BohuTANG** [comment]
To get the sql what's slave executed, you can enable the general log:
```
mysql> set global log_output='table';
Query OK, 0 rows affected (0.00 sec)

mysql> set global general_log=1;
Query OK, 0 rows affected (0.05 sec)

mysql> begin;
Query OK, 0 rows affected (0.00 sec)

mysql> commit;
Query OK, 0 rows affected (0.00 sec)

mysql> select * from mysql.general_log;
+----------------------------+----------------------------+-----------+-----------+--------------+---------------------------------+
| event_time                 | user_host                  | thread_id | server_id | command_type | argument                        |
+----------------------------+----------------------------+-----------+-----------+--------------+---------------------------------+
| 2020-08-29 23:47:43.866639 | root[root] @  [172.17.0.1] |        29 |         1 | Query        | begin                           |
| 2020-08-29 23:47:45.840707 | root[root] @  [172.17.0.1] |        29 |         1 | Query        | commit                          |
| 2020-08-29 23:47:54.716496 | root[root] @  [172.17.0.1] |        29 |         1 | Query        | select * from mysql.general_log |
+----------------------------+----------------------------+-----------+-----------+--------------+---------------------------------+
3 rows in set (0.00 sec)
```

**Comment by liangli1213** [comment]
@BohuTANG , I find the root cause of empty transaction, I use replicate-ignore-table to filter no needed tables on the slave side, which cause the empty transaction.
So it is better to recognize the empty transaction to previent exception.

**Comment by BohuTANG** [comment]
MySQL master not write empty transactions to binlog in gereral case.
This is a slave work that to populate the ignore event with special empty transaction, and this empty transaction should be processed.

**Comment by zhang2014** [comment]
The COMMIT query will not have any effect on MaterializeMySQL engine(this is just a warning, and I will change this log to waring log level)

**Comment by BohuTANG** [comment]
This issue has been fixed in https://github.com/ClickHouse/ClickHouse/commit/0586f0d555f7481b394afc55bbb29738cd573a1c
