### ISSUE TITLE
LDAP and Kerbores Integration

### ISSUE THREAD

**Issue by meshpaul** [ClickHouse/ClickHouse#1424]
Is there an approach on how to integrate with LDAP or Kerbores

**Comment by zhanglistar** [comment]
Not yet

**Comment by alexey-milovidov** [comment]
This task is in progress and it is being developed by @vitlibar

**Comment by hodgesrm** [comment]
@alexey-milovidov Is there a PR for this yet?  Thx.

**Comment by alexey-milovidov** [comment]
No, it is in initial stage of development.

**Comment by traceon** [comment]
LDAP authentication for preconfigured users ("Simple Bind" method) will be added with #11234
