### ISSUE TITLE
Exception on macOS. Client: TimeoutSetter: Can't reset timeouts: Invalid argument

### ISSUE THREAD

**Issue by DOBRO** [ClickHouse/ClickHouse#14254]
Hi,

I'm on _macOS Catalina 10.15.6_, 
ClickHouse 20.8.1, revision 54438.

I'm working on Erlang client with native interface (TCP) support. 
Connection, handshake, and ping - are all OK.
But when it sends query (e.g. `SHOW DATABASES`), I get the exception: 

`Client: TimeoutSetter: Can't reset timeouts: Invalid argument`

Here is what I see in server log for query `SHOW DATABASES` with query ID `Id123`:
```
2020.08.30 15:52:42.733646 [ 148810 ] {Id123} <Debug> executeQuery: (internal) SELECT name FROM system.databases
2020.08.30 15:52:42.734228 [ 148810 ] {Id123} <Trace> ContextAccess (default): Access granted: SELECT(name) ON system.databases
2020.08.30 15:52:42.734359 [ 148810 ] {Id123} <Trace> ContextAccess (default): Access granted: SHOW DATABASES ON *.*
2020.08.30 15:52:42.734450 [ 148810 ] {Id123} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2020.08.30 15:52:42.735347 [ 148810 ] {Id123} <Error> Client: TimeoutSetter: Can't reset timeouts: Invalid argument
```

Seems the exception thrown from this line: https://github.com/ClickHouse/ClickHouse/blob/master/src/Client/TimeoutSetter.cpp#L38

**Comment by filimonov** [comment]
Did you pick clickhouse build from Yandex CI ? Or build your own? In second case - did you use Poco from system of from contrib?

**Comment by DOBRO** [comment]
I'm using precompiled binary. So it was just downloaded: 
`curl -O 'https://builds.clickhouse.tech/master/macos/clickhouse' && chmod a+x ./clickhouse`

following the instructions from https://clickhouse.tech/docs/en/getting-started/install/#from-binaries-non-linux

**Comment by alexey-milovidov** [comment]
This is not a bug and the message can be safely ignored.
