### ISSUE TITLE
Possible to write pgsql functions using array operations? (EMA)

### ISSUE THREAD

**Issue by pavitrakumar78** [ClickHouse/ClickHouse#14268]
Hi,

I just started using ClickHouse to explore a stock database. I'm trying to create a query to calculate the exponential moving average ([EMA](https://www.investopedia.com/ask/answers/122314/what-exponential-moving-average-ema-formula-and-how-ema-calculated.asp)) of a column. This is relatively easy to do in PL/pgsql function which can be defined as:
```
create or replace function ema_func(state numeric, inval numeric, alpha numeric)
  returns numeric
  language sql as $$
select case
       when $1 is null then $2
       else $3 * $2 + (1-$3) * $1
       end
$$;

create aggregate ema(numeric, numeric) (sfunc = ema_func, stype = numeric);

-- 10 EMA of open_price with 0.5 as alpha: 

select ema(open_price, 0.5) over (partition by symbol_id order by symbol_date rows 10 preceding) from eod_table;
```

But I can't figure out how to emulate or convert this into something that can be done in ClickHouse. I've looked at the array documentation, but so far I'm not able to figure out a combination of existing functions or operates to achieve the same result as the function above. 

Am I missing something? or is this not possible to do with ClickHouse at the moment?

Edit: Another issue is using functions like `lag` to access preceding rows. For example, if I want to calculate today's price - price 10 days ago, a possible solution in ClickHouse would be to use a arrayMap with the price and the shifted price array. But by looking at the [array documentation](https://clickhouse.tech/docs/en/sql-reference/functions/array-functions/) and the [higher order functions documentation](https://clickhouse.tech/docs/en/sql-reference/functions/higher-order-functions/), I understand that there isn't such a function (arrayshift) yet?

**Comment by alexeyerm** [comment]
There is a chance to get your results via `groupArrayMovingAvg` function.

**Comment by pavitrakumar78** [comment]
@alexeyerm Thanks for the suggestion. I'm using `groupArrayMovingAvg` for simple moving average ([SMA](https://www.investopedia.com/terms/s/sma.asp#:~:text=A%20simple%20moving%20average%20(SMA)%20is%20an%20arithmetic%20moving%20average,periods%20in%20the%20calculation%20average.)) calculation, but EMA calculation requires the use of previous values which I'm not sure how to achieve.

**Comment by alexey-milovidov** [comment]
Currently there is no support for UDF in ClickHouse, #11.

**Comment by pavitrakumar78** [comment]
@alexey-milovidov Ah.. Ok. Thanks for clarifying! Any idea about arrayshift or emulating `lag` function? The edit in my original post shows an example: calculation of price - price 10 days ago.

**Comment by filimonov** [comment]
> @alexey-milovidov Ah.. Ok. Thanks for clarifying! Any idea about arrayshift or emulating `lag` function? The edit in my original post shows an example: calculation of price - price 10 days ago.

https://github.com/ClickHouse/ClickHouse/issues/5485

https://github.com/ClickHouse/ClickHouse/issues/1469

**Comment by pavitrakumar78** [comment]
@alexey-milovidov Thank you! `neighbor` function is what I was looking for for the second question related to `lag`! 
I'll try to solve the EMA calculation problem in another way!
