### ISSUE TITLE
`No active replica has part..` stuck for few days already

### ISSUE THREAD

**Issue by simPod** [ClickHouse/ClickHouse#14296]
Clickhouse replication queue contains such error message for several entries that are stuck there for a while.

> Code: 234, e.displayText() = DB::Exception: No active replica has part 20200521_0_206813_403_206815 or covering part (version 20.6.3.28 (official build))

I tried detaching and attaching the table but the issue persists. Reattaching table only resets `num_postponed`. 

What can I do to skip the part?

**Comment by den-crane** [comment]
https://github.com/ClickHouse/ClickHouse/issues/10368

**Comment by simPod** [comment]
I'll try ZK fix, reattaching partition does not seem to have any effect.

**Comment by den-crane** [comment]
>reattaching partition does not seem to have any effect

It's kinda strange, because it recreates ZK data completely and after it no one can have knowledge about 20200521_0_206813_403_206815.

**Comment by simPod** [comment]
You were right, I tried again and it disappeared. Thanks!

**Comment by den-crane** [comment]
@simPod check other replicas detached folder. They should have parts detached by `detach parition` command. You need to delete them (because they eat disk space and you can accidentally attach them and get duplicated data).

**Comment by simPod** [comment]
Thanks for pro tip!

**Comment by apetrov88** [comment]
Just for anybody out there facing the same issue. 

Our cluster got disconnected because of a network failure and after fixing that, one of the nodes had a GET_PART stuck. 

No active replica has part 202012_1813039_1814532_573 or covering part  

DETACHing and ATTACHing the partitions did the trick.
