### ISSUE TITLE
CSV column cannot start with backslash when inserting into Nullable(String)  

### ISSUE THREAD

**Issue by ToucheSir** [ClickHouse/ClickHouse#14318]
**Describe the unexpected behaviour**
Trying to insert data from a CSV file (format `CSVWithNames`) into a table with a nullable string column fails if the data for that column starts with a backslash. This happens regardless of the character after the backslash. 

**How to reproduce**
(Tested on 20.6.3.28)

1. Create a basic table with nullable string columns, e.g.:
```sql
CREATE TABLE test
(
    `id` Int,
    `word` Nullable(String)
)
ENGINE = MergeTree()
PRIMARY KEY id
ORDER BY id
```
2. Create a single row CSV file with matching headers (note the leading backslash):
```
id,word
1234,\asdf
```
3. Try to insert the CSV data into the table:
```clickhouse-client --query "insert into test format CSVWithNames" < test.csv```

**Expected behavior**
The insert should succeed and the `word` column should contain the value `\asdf`.

**Error message and/or stacktrace**
```
Code: 27. DB::Exception: Cannot parse input: expected '\\N' before: 'asdf\n': (at row 1)

Row 1:
Column 0,   name: id,   type: Int32,            parsed text: "1234"
Column 1,   name: word, type: Nullable(String), parsed text: "<BACKSLASH>"ERROR
```

**Additional context**
This works perfectly fine if the String column is not Nullable. It also works if there is any text before the backslash (e.g. `as\df`). Is there a way to disable the check for "\\\\N" altogether so that clickhouse doesn't mistakenly raise an error here?

**Comment by den-crane** [comment]
As a workaround you can use quotes `1234,"\asdf"`

**Comment by den-crane** [comment]
fixed now

```
clickhouse-client --query "insert into test format CSVWithNames" < test.csv

 select * from test;
┌───id─┬─word──┐
│ 1234 │ \asdf │
└──────┴───────┘
```
