### ISSUE TITLE
Certain value are not deleted, immediately

### ISSUE THREAD

**Issue by RoyBellingan** [ClickHouse/ClickHouse#1432]
Table defined as
```
CREATE TABLE rt_analytics.transactions ( 
	id Int64,
	timestamp UInt32, 
/** omissis */
ENGINE = MergeTree(date, timestamp, 8192)

SELECT 
    max(timestamp), 
    toDateTime(max(timestamp))
FROM transactions 

┌─max(timestamp)─┬─toDateTime(max(timestamp))─┐
│     1509565623 │        2017-11-01 19:47:03 │

ALTER TABLE rt_analytics.transactions
DROP PARTITION 201711

┌─max(timestamp)─┬─toDateTime(max(timestamp))─┐
│     1509496216 │        2017-11-01 00:30:16 │

```

I also deleted October, but, there is still this single row, 

While opening this bug, I executed the select again, and now it was flushed...

I'll just leave there, maybe some bell rings.

Bye

**Comment by alexey-milovidov** [comment]
It is not obvious from your test case that the `date` column is consistent with `timestamp`.
Could you please provide more detailed test case?

**Comment by RoyBellingan** [comment]
Hi, you are right date is a materialized column 
date Date MATERIALIZED toDate(timestamp)

Maybe that is the reason... 
@George3d6

**Comment by blinkov** [comment]
@RoyBellingan do you have any further questions?

**Comment by RoyBellingan** [comment]
@blinkov  this bug is related to a now quite old version.
I have not checked with the lasted neither if is happening again.

As said Date is a materialized column from the timestamp, that is the only thing I can say.
