### ISSUE TITLE
Create view from Multiple MergeTree table columns files.

### ISSUE THREAD

**Issue by mbtolou** [ClickHouse/ClickHouse#14322]
Hi,

Is it possible that create view or new table engine and bind columns file in **_/clickouse/data_** directory ?

in other words share **.bin** and **.mrk2** between view and table without creating it for view.

```
CREATE TABLE TEST.BIG_TABLE_VOLTAGE
(
    `DATA_ID` String,
    `DTime` DateTime,
    `V_A` Nullable(UInt64),
    `V_B` Nullable(UInt64),
    `V_C` Nullable(UInt64)
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(DTime)
ORDER BY (DTime,  DATA_ID);
```

```
CREATE TABLE TEST.BIG_TABLE_CURRENT
(
    `DATA_ID` String,
    `DTime` DateTime,
    `I_A` Nullable(UInt64),
    `I_B` Nullable(UInt64),
    `I_C` Nullable(UInt64)
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(DTime)
ORDER BY (DTime,  DATA_ID);
```

suggested query for table :

```
CREATE VIEW TEST.BIG_TABLE_CURRENT_VOLTAGE
(
    `DATA_ID` String,
    `DTime` DateTime,
    `V_A` Nullable(UInt64),
    `V_B` Nullable(UInt64),
    `V_C` Nullable(UInt64)
)
ENGINE = BindMergeTree (DTime,  DATA_ID)
SELECT V.DATA_ID,V.DTime, I_A,I_B,I_C,V_A,V_B,V_C
from TEST.BIG_TABLE_VOLTAGE LEFT V JOIN TEST.BIG_TABLE_CURRENT I ON V.DATA_ID=I.DATA_ID AND V.DTime=I.DTime;
```

for example **BindMergeTree** is table that not contain **.bin** file , and use **.bin** of tables [BIG_TABLE_VOLTAGE,BIG_TABLE_CURRENT] for fast join .

**Comment by den-crane** [comment]
No difference with usual `CREATE VIEW`.

>for fast join

No such thing as `fast join`, and no magic, and no Santa.

**Comment by mbtolou** [comment]
i suggest create view or table with another table **.bin** file.

**Comment by den-crane** [comment]
> i suggest create view or table with another table **.bin** file.

For what? Why you cannot use simple `CREATE VIEW` ?

**Comment by mbtolou** [comment]
i join triple big table with 6 billion record and filter by date .
when i filter 4 days ,db exception occurred .

but when create one table with join of all tables , my query execute very fast with lower memory usage .

**Comment by mbtolou** [comment]
i found this page :
https://clickhouse.tech/docs/en/engines/table-engines/special/merge/

but my table schema is same in order and partition key and not same in columns .
can i merge my triple tables ?

**Comment by den-crane** [comment]
>i join triple big table with 6 billion record and filter by date .
>when i filter 4 days ,db exception occurred .

Show your SQL I'll try to re-write it.

>but when create one table with join of all tables , my query execute very fast with lower memory usage .

Yes. It's expected. And it's a preferred approach: do join at ETL stage before loading into CH. 
And your idea (about .bin) unable to solve this. It will be exactly the same long memory eating join.
