### ISSUE TITLE
v20.5 increase memory usage reported by MemoryTracking in system.metrics

### ISSUE THREAD

**Issue by peaksnail** [ClickHouse/ClickHouse#14367]
hi team,

the version 20.5.4.40 has increase memory usage by queries

I upgrade clickhouse server from 19.7 to 20.5.4.40, I don't change any configuration， how to explain ？

configuration
```
<profiles>
        <!-- Default settings. -->
        <default>
            <!-- Maximum memory usage for processing single query, in bytes. -->
            <max_memory_usage>3221225472</max_memory_usage>
            <max_bytes_before_external_group_by>1000000000</max_bytes_before_external_group_by>
            <max_query_size>1048576</max_query_size>

            <max_ast_elements>100000</max_ast_elements>
            <max_expanded_ast_elements>100000</max_expanded_ast_elements>

            <enable_optimize_predicate_expression>1</enable_optimize_predicate_expression>
            <optimize_move_to_prewhere>1</optimize_move_to_prewhere>
            <any_join_distinct_right_table_keys>1</any_join_distinct_right_table_keys>
            <joined_subquery_requires_alias>0</joined_subquery_requires_alias>

            <!-- record query info -->
            <log_queries>1</log_queries>

            <!-- Use cache of uncompressed blocks of data. Meaningful only for processing many of very short queries. -->
            <use_uncompressed_cache>0</use_uncompressed_cache>

            <!-- How to choose between replicas during distributed query processing.
                 random - choose random replica from set of replicas with minimum number of errors
                 nearest_hostname - from set of replicas with minimum number of errors, choose replica
                  with minumum number of different symbols between replica's hostname and local hostname
                  (Hamming distance).
                 in_order - first live replica is choosen in specified order.
            -->
            <load_balancing>random</load_balancing>
        </default>

        <!-- Profile that allows only read queries. -->
        <readonly>
            <readonly>1</readonly>
        </readonly>
    </profiles>
```

thanks

![image](https://user-images.githubusercontent.com/1744607/91922087-a1960300-ecff-11ea-906d-dea5c0f83c68.png)

**Comment by den-crane** [comment]
19.7 or 19.17 ?
Try 20.5.5.74
Your old version is used less than 1 GB ? I don't see the first digit on your graph.

**Comment by alexey-milovidov** [comment]
How the metric is measured?
How does the RSS of clickhouse-server process look on the graph (for comparison)?

**Comment by peaksnail** [comment]
@den-crane  sorry ,the old version is 19.17.6.19 and most used less than 1G, some used 2Gb, but after upgrade most used more than 2GB,I don't change anything

**Comment by peaksnail** [comment]
@alexey-milovidov  I use the template from [template](https://github.com/Altinity/clickhouse-zabbix-template)

I do nothing except upgrade, so I doubt the version change it

**Comment by filimonov** [comment]
It plots `MemoryTracking` from `system.metrics`.

That metric was misbehaving in prev versions (since switching to jemalloc, afair) and the behavior of that was changed, see
* https://github.com/ClickHouse/ClickHouse/issues/10293
* https://github.com/ClickHouse/ClickHouse/pull/10361  
* https://github.com/ClickHouse/ClickHouse/pull/10362
* https://github.com/ClickHouse/ClickHouse/pull/10496
* https://github.com/ClickHouse/ClickHouse/pull/12182

For clickhouse >=20.5 the description of the metric should be smth like "ClickHouse memory usage (RSS)"

**Comment by filimonov** [comment]
20.7
```
│ MemoryTracking                                    │ 4122058752 │ Total amount of memory (bytes) allocated by the server.
```
20.1
```
│ MemoryTracking                               │        0 │ Total amount of memory (bytes) allocated in currently executing queries. Note that some memory allocations may not be accounted.  │
```

**Comment by filimonov** [comment]
I've talked with @Slach about that:

> 
> Mikhail Filimonov  08:45
> Привет, Жень. Может быть надо поправить описание метрики у нас в заббикс шаблоне (там в 20.5 поменялось её значение)? См.  https://github.com/ClickHouse/ClickHouse/issues/14367#issuecomment-685353507
> 
> Eugene Klimov  08:51
> а там описание метрики поменялось в самом ClickHouse?
> 
> Mikhail Filimonov  08:53
> Да. Кстати, надо бы добавить в тот тикет тоже. :+1: (добавил)
> 
> Eugene Klimov  08:55
> чето на мой взгляд как то все сломали нафиг, непонятно зачем
> если была метрика и она отображала то что написано
> пусть и неккоректно
> то лучше б убрали метрику и новую назвали MemoryTrackingTotal
> потому что если кто-то мониторит шаблоном разные версии ClickHouse
> то у него сломается мозг
> 
> Mikhail Filimonov  08:58
> Мне нечего возразить ¯\_(ツ)_/¯
> С другой стороны сейчас менять - опять же безобразие будет какое-то. Впочем может быть ещё не поздно.
> Давай спросим мнения общественности
> 
> Eugene Klimov  09:03
> ну давай там спросим. я боюсь просто это пошло уже дофига куда

**Comment by doom369** [comment]
I have a similar issue (probably). after updating 20.3 to 20.6 - our usual queries are no longer executed and failed due to memory limits.
"Memory limit (total) exceeded: would use 961.69 MiB (attempt to allocate a chunk of 4676694 bytes), maximum: 886.67 MiB".
I updated only 1 QA env (1 core, 1 GB of RAM). However, in my case, I accepted the config changes from the new version.
Look like right after start CH uses all the available memory for something and there is no longer memory for queries.

**Comment by Slach** [comment]
@doom369 you have total different error
for @peaksnail use case we have just changed system.mertics value behavior

in your case probably you need look to 
```
SELECT * FROM system.settings WHERE name LIKE '%max_mem%' OR name LIKE '%max_thead%' OR name LIKE '%background%';
```
and decrease `max_threads` and `background_pool_size` values
1 GB RAM is too low for ClickHouse

**Comment by doom369** [comment]
@Slach thanks for the answer.

> and decrease max_threads and background_pool_size values

That's what I did and that helped. However, top commands still show 100% memory usage. That's wasn't like that for the previous versions. It was at the level of 40-50%.

> 1 GB RAM is too low for ClickHouse

But it's QA and it has like zero loads, it sounds strange for me that with low memory CH can't perform even simple inserts/selects.

**Comment by den-crane** [comment]
@doom369 try to set in config.xml `<mlock_executable>false</mlock_executable>`

**Comment by doom369** [comment]
@den-crane thanks. It helped. Now memory dropped to 14% and to 28% during query execution. Look like it now defaults due to https://github.com/ClickHouse/ClickHouse/pull/11139. Thanks for pointing out.

**Comment by alexey-milovidov** [comment]
@doom369 There is ongoing PR for improvement: https://github.com/ClickHouse/ClickHouse/pull/14929
