### ISSUE TITLE
The ltv stat feature

### ISSUE THREAD

**Issue by levsion** [ClickHouse/ClickHouse#14369]
Hello ! how can I achieve the feature like this:

select sum0,sum1,sum2,sum3 from (
WITH toDate('2020-08-27') AS first_date
select sum0,sum1,sum2,sum3 from (
    with 
    (select sum(money) from act_event where act_date = first_date) as sum0,
    (select sum(money) from act_event where act_date >= first_date AND act_date <= first_date + INTERVAL 1 DAY) as sum1,
    (select sum(money) from act_event where act_date >= first_date AND act_date <= first_date + INTERVAL 2 DAY) as sum2,
    (select sum(money) from act_event where act_date >= first_date AND act_date <= first_date + INTERVAL 3 DAY) as sum3
    select sum0,sum1,sum2,sum3
)
);

**Comment by den-crane** [comment]
Achieve what? Cumulative sum or what?  arrayCumSum?
Please show the input and output and describe algorithm.

```
select toString(arrayCumSum(groupArray(sum_amount))) from (
     SELECT     
        toStartOfDay(create_time) t,     
        (sum(amount)) as sum_amount
    FROM (select today() create_time, 1000  amount union all select today() -100, 1000 union all select today()+100, 1000)
    GROUP BY t 
    ORDER BY t)


SELECT
    d,
    n
FROM
(
    SELECT
        groupArray(date) AS dg,
        arrayCumSum(groupArray(n)) AS ng
    FROM
    (
        SELECT
            arrayJoin(['2020-01-01', '2020-01-02', '2020-01-03']) AS date,
            1 AS n
        ORDER BY date ASC
    )
)
ARRAY JOIN
    dg AS d,
    ng AS n
```
https://stackoverflow.com/search?tab=newest&q=%5bclickhouse%5darraycumsum

**Comment by levsion** [comment]
> Achieve what? Cumulative sum or what? arrayCumSum?
> Please show the input and the desired output and describe an algorithm.
> 
> ```
> select toString(arrayCumSum(groupArray(sum_amount))) from (
>      SELECT     
>         toStartOfDay(create_time) t,     
>         (sum(amount)) as sum_amount
>     FROM (select today() create_time, 1000  amount union all select today() -100, 1000 union all select today()+100, 1000)
>     GROUP BY t 
>     ORDER BY t)
> 
> 
> SELECT
>     d,
>     n
> FROM
> (
>     SELECT
>         groupArray(date) AS dg,
>         arrayCumSum(groupArray(n)) AS ng
>     FROM
>     (
>         SELECT
>             arrayJoin(['2020-01-01', '2020-01-02', '2020-01-03']) AS date,
>             1 AS n
>         ORDER BY date ASC
>     )
> )
> ARRAY JOIN
>     dg AS d,
>     ng AS n
> ```
> 
> https://stackoverflow.com/search?tab=newest&q=%5bclickhouse%5darraycumsum

Yes ! That is what I want. Thank you !!!
