### ISSUE TITLE
WHERE clause not working in materialized view

### ISSUE THREAD

**Issue by pdrtrifork** [ClickHouse/ClickHouse#1436]
Hi,

We are facing a weird issue using a materialized view to select a subset of the rows inserted in to a table.

Currently we have two ClickHouse servers (version 1.1.54292) running on two separate virtual boxes, s1.node.consul and s4.node.consul.

metrika.xml looks like this on s1.node.consul:

	<?xml version="1.0"?>

	<yandex>
		<macros>
			<shard>01</shard>
			<replica>s1.node.consul</replica>
		</macros>

		<remote_servers>
			<analytics>
				<shard>
					<weight>1</weight>
					<internal_replication>true</internal_replication>
					<replica>
						<host>s1.node.consul</host>
						<port>9000</port>
					</replica>
				</shard>
				<shard>
					<weight>1</weight>
					<internal_replication>true</internal_replication>
					<replica>
						<host>s4.node.consul</host>
						<port>9000</port>
					</replica>
				</shard>
			</analytics>
		</remote_servers>

		<zookeeper>
			<node>
				<host>s1.node.consul</host>
				<port>2181</port>
			</node>
		</zookeeper>

		<networks>
			<ip>::/0</ip>
		</networks>

		<clickhouse_compression>
		</clickhouse_compression>
	</yandex>

s4.node.consul is similar, except

    <macros>
        <shard>02</shard>
        <replica>s4.node.consul</replica>
    </macros>

We have a distributed table, testmv.events, where we insert rows. We also have a materialized view, testmv.some_events, where we only want the events with EventType=100. But if I insert a row with EventType=1, it will end up in the some_events table.

In production we have a similar setup, except we only have one shard with two replicas, and the distributed tables have no sharding key defined. And the materialized view selects from the distributed table, and not the local table. Somewhat similar to some_events_v2 below.

Interestingly some_events_v2 behaves as expected, only containing rows with EventType=100.

Here is a complete test case:

	CREATE DATABSE testmv;

	USE testmv;

	CREATE TABLE testmv.events_replica (
		EventDate Date,
		SessionUuid FixedString(16),
		EventType UInt8,
		EventText String
	) ENGINE = ReplicatedMergeTree(
		'/clickhouse/tables/analytics/{shard}/testmv_events',
		'{replica}',
		EventDate,
		cityHash64(SessionUuid),
		(EventDate, cityHash64(SessionUuid)),
		8192
	);

	CREATE TABLE testmv.events AS testmv.events_replica
		ENGINE = Distributed(analytics, testmv, events_replica, cityHash64(SessionUuid));

	CREATE MATERIALIZED VIEW testmv.some_events_replica
	ENGINE = ReplicatedMergeTree(
		'/clickhouse/tables/analytics/{shard}/testmv_some_events',
		'{replica}',
		EventDate,
		cityHash64(SessionUuid),
		(EventDate, cityHash64(SessionUuid)),
		8192
	)
	POPULATE
	AS SELECT
		EventDate,
		SessionUuid,
		EventText
	FROM testmv.events_replica
	WHERE EventType=100;

	CREATE TABLE testmv.some_events AS testmv.some_events_replica
		ENGINE = Distributed(analytics, testmv, some_events_replica);

	CREATE MATERIALIZED VIEW testmv.some_events_replica_v2
	ENGINE = ReplicatedMergeTree(
		'/clickhouse/tables/analytics/{shard}/testmv_some_events_v2',
		'{replica}',
		EventDate,
		cityHash64(SessionUuid),
		(EventDate, cityHash64(SessionUuid)),
		8192
	)
	POPULATE
	AS SELECT
		EventDate,
		SessionUuid,
		EventText
	FROM testmv.events
	WHERE EventType=100;

	CREATE TABLE testmv.some_events_v2 AS testmv.some_events_replica_v2
		ENGINE = Distributed(analytics, testmv, some_events_replica_v2);

	INSERT INTO events (EventDate, SessionUuid, EventType, EventText) VALUES (toDate('2017-11-02'), 'aaaaaaaaaaaaaaaa', 1, 'EventType=1');
	INSERT INTO events (EventDate, SessionUuid, EventType, EventText) VALUES (toDate('2017-11-02'), 'bbbbbbbbbbbbbbbb', 1, 'EventType=1');
	INSERT INTO events (EventDate, SessionUuid, EventType, EventText) VALUES (toDate('2017-11-02'), 'cccccccccccccccc', 100, 'EventType=100');

	SELECT * FROM some_events;

	┌──EventDate─┬─SessionUuid──────┬─EventText───┐
	│ 2017-11-02 │ aaaaaaaaaaaaaaaa │ EventType=1 │
	└────────────┴──────────────────┴─────────────┘
	┌──EventDate─┬─SessionUuid──────┬─EventText─────┐
	│ 2017-11-02 │ cccccccccccccccc │ EventType=100 │
	└────────────┴──────────────────┴───────────────┘
	┌──EventDate─┬─SessionUuid──────┬─EventText───┐
	│ 2017-11-02 │ bbbbbbbbbbbbbbbb │ EventType=1 │
	└────────────┴──────────────────┴─────────────┘

	SELECT * FROM some_events_v2;

	┌──EventDate─┬─SessionUuid──────┬─EventText─────┐
	│ 2017-11-02 │ cccccccccccccccc │ EventType=100 │
	└────────────┴──────────────────┴───────────────┘

**Comment by pdrtrifork** [comment]
I made a simplified test case of the above without using replicated or distributed tables with the exact same result:

	CREATE DATABASE testmv3;

	USE testmv3;

	CREATE TABLE testmv3.events (
		EventDate Date,
		SessionUuid FixedString(16),
		EventType UInt8,
		EventText String
	) ENGINE = MergeTree(
		EventDate,
		(EventDate, SessionUuid),
		8192
	);

	CREATE MATERIALIZED VIEW testmv3.some_events
	ENGINE = MergeTree(
		EventDate,
		(EventDate, SessionUuid),
		8192
	)
	POPULATE
	AS SELECT
		EventDate,
		SessionUuid,
		EventText
	FROM testmv3.events
	WHERE EventType=100;

	INSERT INTO testmv3.events (EventDate, SessionUuid, EventType, EventText) VALUES (toDate('2017-11-02'), 'aaaaaaaaaaaaaaaa', 1, 'EventType=1');

	INSERT INTO testmv3.events (EventDate, SessionUuid, EventType, EventText) VALUES (toDate('2017-11-02'), 'aaaaaaaaaaaaaaaa', 1, 'EventType=1');
	INSERT INTO testmv3.events (EventDate, SessionUuid, EventType, EventText) VALUES (toDate('2017-11-02'), 'bbbbbbbbbbbbbbbb', 1, 'EventType=1');
	INSERT INTO testmv3.events (EventDate, SessionUuid, EventType, EventText) VALUES (toDate('2017-11-02'), 'cccccccccccccccc', 100, 'EventType=100');

	SELECT * FROM testmv3.some_events;

	┌──EventDate─┬─SessionUuid──────┬─EventText───┐
	│ 2017-11-02 │ aaaaaaaaaaaaaaaa │ EventType=1 │
	└────────────┴──────────────────┴─────────────┘
	┌──EventDate─┬─SessionUuid──────┬─EventText─────┐
	│ 2017-11-02 │ cccccccccccccccc │ EventType=100 │
	└────────────┴──────────────────┴───────────────┘
	┌──EventDate─┬─SessionUuid──────┬─EventText───┐
	│ 2017-11-02 │ bbbbbbbbbbbbbbbb │ EventType=1 │
	└────────────┴──────────────────┴─────────────┘

Then I redid both tests on ClickHouse version 1.1.54198, which worked as expected - only having rows with EventType=100 in the some_events view.

**Comment by alex-zaitsev** [comment]
We had intermittent issues with MV consistency as well, and it may be perfectly related to not respecting WHERE condition sometimes.

**Comment by pdrtrifork** [comment]
A bit more information: If I use the Memory table engine for the events table, the materialized view behaves as expected. But that is not an option in our case :-)

**Comment by ztlpn** [comment]
Thanks for a simple and reproducible test case @pdrtrifork ! I've been able to pinpoint the cause of the issue - when materialized view is populated from a MergeTree table, the optimizer moves WHERE condition to PREWHERE and thus garbles the original query.

While the fix is waiting to be released, here is a simple workaround: just restart the server after creating and populating a materialized view (or don't use POPULATE at all).

**Comment by perez1987** [comment]
This problem has been resolved? We are encountering problems when generating a materialized table with a "Where" and "Populate"

The initial load of the data works well, but when making insertions in background to the materialized table the data is inconsistent and we do not have the same number of events between the original table (with the Where) and the number of events in the materialized table

Restarting the service / server works? Why? @ztlpn  @pdrtrifork
