### ISSUE TITLE
InActive part are not getting deleted in one of the MergeTree replicas

### ISSUE THREAD

**Issue by shantam04** [ClickHouse/ClickHouse#14403]
**Issue description**
InActive part are not getting deleted in one of the merge tree replicas, even though I have setup old_parts_lifetime to 180 seconds inactive part are not getting deleted for hours and inactive part count is reaching in thousands. 
Is there any way to debug this further as to why inactive parts are getting deleted with this much delay ? 

**Merge tree part removal settings**
```
SELECT 
    name, 
    value, 
    changed
FROM system.merge_tree_settings
WHERE name IN ('old_parts_lifetime', 'max_part_removal_threads')

┌─name─────────────────────┬─value─┬─changed─┐
│ old_parts_lifetime       │ 180   │       1 │
│ max_part_removal_threads │ 10    │       1 │
└──────────────────────────┴───────┴─────────┘
2 rows in set. Elapsed: 0.002 sec. 
```

**Table create query**
```
CREATE TABLE 
events.incident_task_events_new (`csIncident` String, `partnerVendor` Nullable(String), `lastActionTaken` Nullable(String), `formStatus` Nullable(String), `issueName` LowCardinality(String), `partnerVertical` Nullable(String), `createdOn` DateTime, `lastActionTakenBy` Nullable(String), `lastUpdatedOn` Nullable(DateTime), `formResponseDataValue4` Nullable(String), `partnerCourierPartner` Nullable(String), `mpsDetails` Nullable(String), `formCreatedOn` Nullable(String), `formResponseDataType1` Nullable(String), `partnerStatus` Nullable(String), `partnerCurrentPartner` Nullable(String), `partnerOrder_id` Nullable(String), `formResponseDataName1` Nullable(String), `firstActionDeadline` Nullable(DateTime), `lastActionTakenAt` Nullable(DateTime), `globalTrackingId` Nullable(String), `partnerAddress` Nullable(String), `formResponseDataValue2` Nullable(String), `allocationAssignedAgentOn` Nullable(DateTime), `partnerId` Nullable(String), `formTaskId` Nullable(String), `taskOrderItemIds` Nullable(String), `allocationLastSolvedBy` Nullable(String), `lastActionDeadline` Nullable(DateTime), `formResponseDataType2` Nullable(String), `formResponseDataValue1` Nullable(String), `partnerSeller_id` Nullable(String), `partnerHubName` Nullable(String), `taskOrderItemUnitIds` Nullable(String), `formResponseDataType3` Nullable(String), `taskSellerIds` Nullable(String), `lastUpdatedBy` Nullable(String), `formResponseDataName3` Nullable(String), `taskOrderIds` Nullable(String), `formRequestAgentId` Nullable(String), `formRequestDataName1` Nullable(String), `issueId` LowCardinality(String), `formRequestDataType1` Nullable(String), `taskStatus` LowCardinality(Nullable(String)), `taskIncidentId` String, `partnerType` LowCardinality(String), `partnerService` Nullable(String), `partnerEklIssueId` Nullable(String), `taskTrackingIds` Nullable(String), `csIncidentStatus` Nullable(String), `partnerPinCode` Nullable(String), `partnerModel` Nullable(String), `partnerCustomer_name` Nullable(String), `allocationAssignedTo` Nullable(String), `incidentPriority` Nullable(String), `formRequestDataValue1` Nullable(String), `partnerBrand` Nullable(String), `formRequestPartnerType` Nullable(String), `formResponseDataName4` Nullable(String), `partnerPhone` Nullable(String), `allocationQueueName` Nullable(String), `allocationAddedToQueueAt` Nullable(DateTime), `formRequestData` Nullable(String), `allocationReadyOrQueueChangeAt` Nullable(DateTime), `formResponseDataValue3` Nullable(String), `fromUpdatedOn` Nullable(String), `formResponseDataName2` Nullable(String), `formResponseDataType4` Nullable(String), `partnerEmail_id` Nullable(String), `eventTime` DateTime) 
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/events.incident_task_events_new', '{replica}') 
PARTITION BY toYYYYMMDD(eventTime) 
ORDER BY (partnerType, createdOn) 
TTL eventTime + toIntervalMonth(1) 
SETTINGS index_granularity = 8192
```

**Part count**
```
SELECT 
    count(), 
    table, 
    active
FROM system.parts
WHERE table = 'incident_task_events_new'
GROUP BY (database, table, active)
ORDER BY (active, table) ASC

┌─count()─┬─table────────────────────┬─active─┐
│    8209 │ incident_task_events_new │      0 │
│      11 │ incident_task_events_new │      1 │
└─────────┴──────────────────────────┴────────┘
2 rows in set. Elapsed: 6.113 sec. Processed 8.22 thousand rows, 4.00 MB (1.34 thousand rows/s., 655.09 KB/s.) 
```

**Last part removal time for the table**
Here last parts where deleted few hours from the current time even though  old_parts_lifetime is 180 seconds, not sure whats causing this delay and will there be any unexpected issues on clickhouse sever that's running.
```
SELECT 
    partition, 
    name, 
    active, 
    remove_time, 
    rows, 
    toDateTime(now()) AS currentTime
FROM system.parts
WHERE (database = 'events') AND (table = 'incident_task_events_new') AND (active = 0)
ORDER BY remove_time ASC
LIMIT 10

┌─partition─┬─name────────────────────┬─active─┬─────────remove_time─┬─rows─┬─────────currentTime─┐
│ 20200902  │ 20200902_13819_13819_0  │      0 │ 2020-09-02 09:38:45 │    1 │ 2020-09-02 14:01:23 │
│ 20200902  │ 20200902_13821_13821_0  │      0 │ 2020-09-02 09:38:45 │    2 │ 2020-09-02 14:01:23 │
│ 20200902  │ 20200902_13820_13820_0  │      0 │ 2020-09-02 09:38:45 │    4 │ 2020-09-02 14:01:23 │
│ 20200902  │ 20200902_13823_13823_0  │      0 │ 2020-09-02 09:38:45 │    2 │ 2020-09-02 14:01:23 │
│ 20200902  │ 20200902_13822_13822_0  │      0 │ 2020-09-02 09:38:45 │    1 │ 2020-09-02 14:01:23 │
│ 20200902  │ 20200902_13605_13818_18 │      0 │ 2020-09-02 09:38:45 │ 1891 │ 2020-09-02 14:01:23 │
│ 20200902  │ 20200902_13826_13826_0  │      0 │ 2020-09-02 09:38:56 │   13 │ 2020-09-02 14:01:23 │
│ 20200902  │ 20200902_13825_13825_0  │      0 │ 2020-09-02 09:38:56 │    2 │ 2020-09-02 14:01:23 │
│ 20200902  │ 20200902_13827_13827_0  │      0 │ 2020-09-02 09:38:56 │   80 │ 2020-09-02 14:01:23 │
│ 20200902  │ 20200902_13824_13824_0  │      0 │ 2020-09-02 09:38:56 │    9 │ 2020-09-02 14:01:23 │
└───────────┴─────────────────────────┴────────┴─────────────────────┴──────┴─────────────────────┘
10 rows in set. Elapsed: 2.436 sec. Processed 8.29 thousand rows, 4.04 MB (3.40 thousand rows/s., 1.66 MB/s.) 
```

**Cluster stats**
```
Nodes - 3
Cores - 20 per node
Ram - 94G

Top command state on the server :
15:26:07 up 130 days,  5:52,  1 user,  load average: 27.06, 24.55, 24.13
Tasks: 334 total,   1 running, 333 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.4 us,  0.2 sy,  0.0 ni, 94.4 id,  4.9 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 99009592 total,  1386144 free, 19366152 used, 78257296 buff/cache
KiB Swap:        0 total,        0 free,        0 used. 78540672 avail Mem 
```

**Comment by den-crane** [comment]
1. CH version?
2. Did you change other settings except old_parts_lifetime ?
3. Do you observe error messages in /var/log/clickhouse-server/clickhouse-server.err.log /var/log/clickhouse-server/clickhouse-server.log  ? 
4. Do you use "Google Compute Environment SSD Persistent Disks" as disks/storage?

**Comment by shantam04** [comment]
1) CH version: 19.17.5.18
2) Config changed "max_part_removal_threads": auto(10) -> 10

3) in err.log getting these exception - 
`2020.09.02 14:27:27.866274 [ 9 ] {} <Error> events.incident_task_events_new: DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = Timeout: connect timed out: 10.32.239.191:9009 (version 19.17.5.18 (official build)
2020.09.02 14:47:01.847058 [ 16 ] {} <Error> events.incident_task_events_new: DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = Timeout: connect timed out: 10.33.141.107:9009 (version 19.17.5.18 (official build)
2020.09.02 15:04:56.653394 [ 18 ] {} <Error> events.incident_task_events_new: DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = Timeout: connect timed out: 10.33.141.107:9009 (version 19.17.5.18 (official build)
2020.09.02 15:11:16.325430 [ 17 ] {} <Error> events.incident_task_events_new: DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = Timeout: connect timed out: 10.33.141.107:9009 (version 19.17.5.18 (official build)
2020.09.02 15:13:39.379607 [ 11 ] {} <Error> events.incident_task_events_new: DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = Timeout: connect timed out: 10.33.141.107:9009 (version 19.17.5.18 (official build)
2020.09.02 15:16:22.390921 [ 4 ] {} <Error> events.incident_task_events_new: DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = Timeout: connect timed out: 10.32.239.191:9009 (version 19.17.5.18 (official build)
2020.09.02 15:34:08.581559 [ 4 ] {} <Error> events.incident_task_events_new: DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = Timeout: connect timed out: 10.33.141.107:9009 (version 19.17.5.18 (official build)
2020.09.02 16:20:00.205380 [ 18 ] {} <Error> events.incident_task_events_new: DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = Timeout: connect timed out: 10.32.239.191:9009 (version 19.17.5.18 (official build)
2020.09.02 16:33:57.747523 [ 7 ] {} <Error> events.incident_task_events_new: DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = Timeout: connect timed out: 10.32.239.191:9009 (version 19.17.5.18 (official build)
2020.09.02 19:39:50.282712 [ 5 ] {} <Error> events.incident_task_events_new: DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = Timeout: connect timed out: 10.33.141.107:9009 (version 19.17.5.18 (official build)
2020.09.02 20:33:12.985432 [ 13 ] {} <Error> events.incident_task_events_new: DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = Timeout: connect timed out: 10.33.141.107:9009 (version 19.17.5.18 (official build)
2020.09.02 21:25:12.177762 [ 8 ] {} <Error> events.incident_task_events_new: DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = Timeout: connect timed out: 10.33.141.107:9009 (version 19.17.5.18 (official build)
2020.09.02 21:36:57.166527 [ 3 ] {} <Error> events.incident_task_events_new: DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = Timeout: connect timed out: 10.33.141.107:9009 (version 19.17.5.18 (official build)
2020.09.02 21:59:59.077764 [ 4 ] {} <Error> events.incident_task_events_new: DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = Timeout: connect timed out: 10.32.239.191:9009 (version 19.17.5.18 (official build)`

4. HDD spec: HGST Ultrastar He12 12TB SAS, disk_type: SAS-HDD-D3

**Comment by shantam04** [comment]
@den-crane any pointers on how to debug the further?

**Comment by den-crane** [comment]
Is it grow constantly? Did you try to restart CH ?

**Comment by shantam04** [comment]
1) Is it grow constantly?
Yes, it grows constantly, and part deleting happens with few hours of delay so, in case of an increase in qps from the source part count increases by a lot.

2) Did you try to restart CH?
Yes, we tried restarting. On the restart, inactive parts are removed but it starts growing again.

**Comment by den-crane** [comment]
Check `select refcount system.parts where not active` for these parts.
Only inactive parts with refcount=1 can be deleted.

_refcount (UInt32) – The number of places where the data part is used. 
A value greater than 2 indicates that the data part is used in queries or merges._

**Comment by shantam04** [comment]
@den-crane Sorry for the late response , I checked both of the queries and all our inactive part have refcount=1 and mutation count is zero.
This looks to me that part removal itself is slow is there a way to speed this up.
Also i checked by when are parts getting removed ad found the removal time for old part is - "0000-00-00 00:00:00" not sure what this implies.

SELECT 
    partition, 
    name, 
    active, 
    remove_time, 
    rows, 
    is_frozen
FROM system.parts
WHERE (database = 'events') AND (table = 'incident_task_events_new') AND (active = 0)
ORDER BY remove_time ASC
LIMIT 50

`┌─partition─┬─name─────────────────────┬─active─┬─────────remove_time─┬──rows─┬─is_frozen─┐
│ 20200925  │ 20200925_14243_14243_0   │      0 │ 0000-00-00 00:00:00 │     2 │         0 │
│ 20200925  │ 20200925_14692_14692_0   │      0 │ 0000-00-00 00:00:00 │     2 │         0 │
│ 20200925  │ 20200925_15929_15934_1   │      0 │ 0000-00-00 00:00:00 │    41 │         0 │
│ 20200925  │ 20200925_16014_16014_0   │      0 │ 0000-00-00 00:00:00 │     6 │         0 │
│ 20200925  │ 20200925_15328_15328_0   │      0 │ 0000-00-00 00:00:00 │     7 │         0 │
│ 20200925  │ 20200925_14614_14614_0   │      0 │ 0000-00-00 00:00:00 │     6 │         0 │`

**Comment by den-crane** [comment]
There are a setting (merge_tree section config.xml)

_max_part_removal_threads                                   │ 'auto(8)'    │       0 │ The number of threads for concurrent removal of inactive data parts. One is usually enough, but in 'Google Compute Environment SSD Persistent Disks' file removal (unlink) operation is extraordinarily slow and you probably have to increase this number (recommended is up to 16)._

maybe it's your case
