### ISSUE TITLE
Can't start clickhouse 20.7.2.30 to centos7.5, last line in logs is "Will mlockall to prevent executable memory"

### ISSUE THREAD

**Issue by levsion** [ClickHouse/ClickHouse#14400]
I install the 20.7.2.30 version from the rpm. When I start the clickhouse-server it cannot run, I get the log:

2020.09.02 17:16:35.859880 [ 25885 ] {} <Information> SentryWriter: Sending crash reports is disabled
2020.09.02 17:16:35.865925 [ 25885 ] {} <Trace> Pipe: Pipe capacity is 1.00 MiB
2020.09.02 17:16:36.012988 [ 25885 ] {} <Information> : Starting ClickHouse 20.7.2.30 with revision 54437, no build id, PID 25885
2020.09.02 17:16:36.013097 [ 25885 ] {} <Information> Application: starting up
2020.09.02 17:16:36.026676 [ 25885 ] {} <Trace> Application: Will mlockall to prevent executable memory from being paged out. It may take a few seconds

What does it mean???

**Comment by levsion** [comment]
I have send the crash log to : https://6f33034cfe684dd7a3ab9875e57b1c8d@o388870.ingest.sentry.io/5226277

**Comment by den-crane** [comment]
Please run it in foreground and show stdout output

`sudo -u clickhouse clickhouse-server --pid-file=/var/run/clickhouse-server/clickhouse-server.pid --config-file=/etc/clickhouse-server/config.xml`

**Comment by filimonov** [comment]
Let me guess: you have a tiny VM? like VM in vagrant with 500 Mb of RAM by default? 

ClickHouse enabled `mlock_executable` by default since 20.5  https://github.com/ClickHouse/ClickHouse/pull/11139

And the whole executable should now live in RAM, otherwise oomkiller will kill it during the attempt to mlock (check `dmesg`).

Please give more RAM to your VM, or add  
```xml
<mlock_executable>false</mlock_executable>
```
to your clickhouse config.

**Comment by levsion** [comment]
> Let me guess: you have a tiny VM? like VM in vagrant with 500 Mb of RAM by default?
> 
> ClickHouse enabled `mlock_executable` by default since 20.5 #11139
> 
> And the whole executable should now live in RAM, otherwise oomkiller will kill it during the attempt to mlock (check `dmesg`).
> 
> Please give more RAM to your VM, or add
> 
> ```
> <mlock_executable>false</mlock_executable>
> ```
> 
> to your clickhouse config.

Haha, yes, your guess is right！my linux server is google cloud with 1GB RAM and 2 core CPU, and it works well with version 20.3. then in the version20.7 i change the "mlock_executable" config to false, it works success !!! Thank you, you are so excellent.

**Comment by levsion** [comment]
> Please run it in foreground and show stdout output
> 
> ```
> sudo -u clickhouse clickhouse-server --pid-file=/var/run/clickhouse-server/clickhouse-server.pid --config-file=/etc/clickhouse-server/config.xml
> ```

Thank you for your suggest. I have solve it by change the "mlock_executable" config to false. Thank you twice !!!

**Comment by filimonov** [comment]
(Added backward compatibility label, because you can't run clickhouse on the same machine with default config)
