### ISSUE TITLE
MaterializeMySQL start/stop/show replication status

### ISSUE THREAD

**Issue by liangli1213** [ClickHouse/ClickHouse#14401]
Something like in MySQL:
```
start slave;
stop slave;
show slave status\G
```

**Comment by poorX** [comment]
i make a MaterializeMySQL database like this
```sql
CREATE DATABASE DB_NAME on cluster cluster01 ENGINE = MaterializeMySQL('ip:port', 'db', 'user, 'pass');
```

and all server in cluster crashed, log detail is  

```2020.09.02 17:29:16.532814 [ 309295 ] {} <Fatal> BaseDaemon: ########################################
2020.09.02 17:29:16.532879 [ 309295 ] {} <Fatal> BaseDaemon: (version 20.8.1.4513 (official build), no build id) (from thread 308655) (no query) Received signal Segmentation fault (11)
2020.09.02 17:29:16.532905 [ 309295 ] {} <Fatal> BaseDaemon: Address: 0x10680 Access: write. Address not mapped to object.
2020.09.02 17:29:16.532928 [ 309295 ] {} <Fatal> BaseDaemon: Stack trace: 0x178020d8 0x177f81e8 0x177fb9e5 0x17440e82 0x177d4432 0x177d5d5f 0x17397bd4 0x173a1d65 0x173a3493 0x173df669 0x173e1a9e 0x1739b6c1 0x173a03bb 0x173a08d6 0xffce517 0xffccb53 0x7f1cbf219dc5 0x7f1cbeb3b21d
2020.09.02 17:29:16.533061 [ 309295 ] {} <Fatal> BaseDaemon: 3. std::__1::enable_if<(std::__1::__is_cpp17_forward_iterator<std::__1::__wrap_iter<std::__1::shared_ptr<DB::IAST>*> >::value) && (std::__1::is_constructible<std::__1::shared_ptr<DB::IAST>, std::__1::iterator_traits<std::__1::iterator_traits>::reference>::value), std::__1::__wrap_iter<std::__1::shared_ptr<DB::IAST>*> >::type std::__1::vector<std::__1::shared_ptr<DB::IAST>, std::__1::allocator<std::__1::shared_ptr<DB::IAST> > >::insert<std::__1::__wrap_iter<std::__1::shared_ptr<DB::IAST>*> >(std::__1::__wrap_iter<std::__1::shared_ptr<DB::IAST> const*>, std::__1::iterator_traits, std::__1::iterator_traits) @ 0x178020d8 in /usr/bin/clickhouse
2020.09.02 17:29:16.533106 [ 309295 ] {} <Fatal> BaseDaemon: 4. ? @ 0x177f81e8 in /usr/bin/clickhouse
2020.09.02 17:29:16.533142 [ 309295 ] {} <Fatal> BaseDaemon: 5. DB::MySQLInterpreter::InterpreterCreateImpl::getRewrittenQueries(DB::MySQLParser::ASTCreateQuery const&, DB::Context const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x177fb9e5 in /usr/bin/clickhouse
2020.09.02 17:29:16.533174 [ 309295 ] {} <Fatal> BaseDaemon: 6. DB::InterpreterExternalDDLQuery::execute() @ 0x17440e82 in /usr/bin/clickhouse
2020.09.02 17:29:16.533195 [ 309295 ] {} <Fatal> BaseDaemon: 7. ? @ 0x177d4432 in /usr/bin/clickhouse
2020.09.02 17:29:16.533222 [ 309295 ] {} <Fatal> BaseDaemon: 8. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool) @ 0x177d5d5f in /usr/bin/clickhouse
2020.09.02 17:29:16.533254 [ 309295 ] {} <Fatal> BaseDaemon: 9. ? @ 0x17397bd4 in /usr/bin/clickhouse
2020.09.02 17:29:16.533269 [ 309295 ] {} <Fatal> BaseDaemon: 10. ? @ 0x173a1d65 in /usr/bin/clickhouse
2020.09.02 17:29:16.533286 [ 309295 ] {} <Fatal> BaseDaemon: 11. ? @ 0x173a3493 in /usr/bin/clickhouse
2020.09.02 17:29:16.533313 [ 309295 ] {} <Fatal> BaseDaemon: 12. DB::commitMetadata(std::__1::function<void ()> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x173df669 in /usr/bin/clickhouse
2020.09.02 17:29:16.533347 [ 309295 ] {} <Fatal> BaseDaemon: 13. DB::MaterializeMetadata::transaction(DB::MySQLReplication::Position const&, std::__1::function<void ()> const&) @ 0x173e1a9e in /usr/bin/clickhouse
2020.09.02 17:29:16.533368 [ 309295 ] {} <Fatal> BaseDaemon: 14. DB::MaterializeMySQLSyncThread::prepareSynchronized(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x1739b6c1 in /usr/bin/clickhouse
2020.09.02 17:29:16.533386 [ 309295 ] {} <Fatal> BaseDaemon: 15. DB::MaterializeMySQLSyncThread::synchronization(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x173a03bb in /usr/bin/clickhouse
2020.09.02 17:29:16.533404 [ 309295 ] {} <Fatal> BaseDaemon: 16. ? @ 0x173a08d6 in /usr/bin/clickhouse
2020.09.02 17:29:16.533429 [ 309295 ] {} <Fatal> BaseDaemon: 17. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xffce517 in /usr/bin/clickhouse
2020.09.02 17:29:16.533451 [ 309295 ] {} <Fatal> BaseDaemon: 18. ? @ 0xffccb53 in /usr/bin/clickhouse
2020.09.02 17:29:16.533478 [ 309295 ] {} <Fatal> BaseDaemon: 19. start_thread @ 0x7dc5 in /usr/lib64/libpthread-2.17.so
2020.09.02 17:29:16.533506 [ 309295 ] {} <Fatal> BaseDaemon: 20. __clone @ 0xf621d in /usr/lib64/libc-2.17.so
```

maybe same table struct make this problem 

so if can create MaterializeMySQL table use right data type before replicate，and support 
```sql
CHANGE MASTER TO pos/gtid
```

smell better

**Comment by BohuTANG** [comment]
> i make a MaterializeMySQL database like this
> 
> ```sql
> CREATE DATABASE DB_NAME on cluster cluster01 ENGINE = MaterializeMySQL('ip:port', 'db', 'user, 'pass');
> ```
> 
> and all server in cluster crashed, log detail is
> 
> ```
> 2020.09.02 17:29:16.532879 [ 309295 ] {} <Fatal> BaseDaemon: (version 20.8.1.4513 (official build), no build id) (from thread 308655) (no query) Received signal Segmentation fault (11)
> 2020.09.02 17:29:16.532905 [ 309295 ] {} <Fatal> BaseDaemon: Address: 0x10680 Access: write. Address not mapped to object.
> 2020.09.02 17:29:16.532928 [ 309295 ] {} <Fatal> BaseDaemon: Stack trace: 0x178020d8 0x177f81e8 0x177fb9e5 0x17440e82 0x177d4432 0x177d5d5f 0x17397bd4 0x173a1d65 0x173a3493 0x173df669 0x173e1a9e 0x1739b6c1 0x173a03bb 0x173a08d6 0xffce517 0xffccb53 0x7f1cbf219dc5 0x7f1cbeb3b21d
> 2020.09.02 17:29:16.533061 [ 309295 ] {} <Fatal> BaseDaemon: 3. std::__1::enable_if<(std::__1::__is_cpp17_forward_iterator<std::__1::__wrap_iter<std::__1::shared_ptr<DB::IAST>*> >::value) && (std::__1::is_constructible<std::__1::shared_ptr<DB::IAST>, std::__1::iterator_traits<std::__1::iterator_traits>::reference>::value), std::__1::__wrap_iter<std::__1::shared_ptr<DB::IAST>*> >::type std::__1::vector<std::__1::shared_ptr<DB::IAST>, std::__1::allocator<std::__1::shared_ptr<DB::IAST> > >::insert<std::__1::__wrap_iter<std::__1::shared_ptr<DB::IAST>*> >(std::__1::__wrap_iter<std::__1::shared_ptr<DB::IAST> const*>, std::__1::iterator_traits, std::__1::iterator_traits) @ 0x178020d8 in /usr/bin/clickhouse
> 2020.09.02 17:29:16.533106 [ 309295 ] {} <Fatal> BaseDaemon: 4. ? @ 0x177f81e8 in /usr/bin/clickhouse
> 2020.09.02 17:29:16.533142 [ 309295 ] {} <Fatal> BaseDaemon: 5. DB::MySQLInterpreter::InterpreterCreateImpl::getRewrittenQueries(DB::MySQLParser::ASTCreateQuery const&, DB::Context const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x177fb9e5 in /usr/bin/clickhouse
> 2020.09.02 17:29:16.533174 [ 309295 ] {} <Fatal> BaseDaemon: 6. DB::InterpreterExternalDDLQuery::execute() @ 0x17440e82 in /usr/bin/clickhouse
> 2020.09.02 17:29:16.533195 [ 309295 ] {} <Fatal> BaseDaemon: 7. ? @ 0x177d4432 in /usr/bin/clickhouse
> 2020.09.02 17:29:16.533222 [ 309295 ] {} <Fatal> BaseDaemon: 8. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool) @ 0x177d5d5f in /usr/bin/clickhouse
> 2020.09.02 17:29:16.533254 [ 309295 ] {} <Fatal> BaseDaemon: 9. ? @ 0x17397bd4 in /usr/bin/clickhouse
> 2020.09.02 17:29:16.533269 [ 309295 ] {} <Fatal> BaseDaemon: 10. ? @ 0x173a1d65 in /usr/bin/clickhouse
> 2020.09.02 17:29:16.533286 [ 309295 ] {} <Fatal> BaseDaemon: 11. ? @ 0x173a3493 in /usr/bin/clickhouse
> 2020.09.02 17:29:16.533313 [ 309295 ] {} <Fatal> BaseDaemon: 12. DB::commitMetadata(std::__1::function<void ()> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x173df669 in /usr/bin/clickhouse
> 2020.09.02 17:29:16.533347 [ 309295 ] {} <Fatal> BaseDaemon: 13. DB::MaterializeMetadata::transaction(DB::MySQLReplication::Position const&, std::__1::function<void ()> const&) @ 0x173e1a9e in /usr/bin/clickhouse
> 2020.09.02 17:29:16.533368 [ 309295 ] {} <Fatal> BaseDaemon: 14. DB::MaterializeMySQLSyncThread::prepareSynchronized(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x1739b6c1 in /usr/bin/clickhouse
> 2020.09.02 17:29:16.533386 [ 309295 ] {} <Fatal> BaseDaemon: 15. DB::MaterializeMySQLSyncThread::synchronization(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x173a03bb in /usr/bin/clickhouse
> 2020.09.02 17:29:16.533404 [ 309295 ] {} <Fatal> BaseDaemon: 16. ? @ 0x173a08d6 in /usr/bin/clickhouse
> 2020.09.02 17:29:16.533429 [ 309295 ] {} <Fatal> BaseDaemon: 17. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xffce517 in /usr/bin/clickhouse
> 2020.09.02 17:29:16.533451 [ 309295 ] {} <Fatal> BaseDaemon: 18. ? @ 0xffccb53 in /usr/bin/clickhouse
> 2020.09.02 17:29:16.533478 [ 309295 ] {} <Fatal> BaseDaemon: 19. start_thread @ 0x7dc5 in /usr/lib64/libpthread-2.17.so
> 2020.09.02 17:29:16.533506 [ 309295 ] {} <Fatal> BaseDaemon: 20. __clone @ 0xf621d in /usr/lib64/libc-2.17.so
> ```
> 
> maybe same table struct make this problem
> 
> so if can create MaterializeMySQL table use right data type before replicate，and support
> 
> ```sql
> CHANGE MASTER TO pos/gtid
> ```
> 
> smell better

Please make a new issue.

**Comment by vanloctech** [comment]
@liangli1213 I see this section is closed, have you found a way to check? Please give me instructions, thanks
