### ISSUE TITLE
No data in replicated table

### ISSUE THREAD

**Issue by simPod** [ClickHouse/ClickHouse#14419]
I have two replicas. Data are inserted into table in replica A. Table counterpart in replica B is empty though. Data are not replicated between replicas. I tried recreating table in replica B but it did not trigger the sync.

Replication for other tables is working just fine.

What can I do to debug the issue? `show create table` gives same result for both replicas.

ClickHouse version 20.6

**Comment by den-crane** [comment]
check (at both nodes) : select * from system.replication_queue

**Comment by simPod** [comment]
I don't have multiple shards.

replication queue does not contain any records for the target table

path si the same (reported by show create table)

🤔

**Comment by den-crane** [comment]
Show `grep tablename clickhouseserver.log`

**Comment by simPod** [comment]
I tried grepping `cat /var/log/clickhouse-server/clickhouse-server.log` in both replicas but for this particular table contains no logs (it does have some warnings for larger tables though).

**Comment by den-crane** [comment]
It could be anything. How did you copy/pasted / attached zk path when you created a table?

For example these two strings are different. 
Latin:    /ccccc/ 
Сyrrylic: /ссссс/ 

Check zookeeper select * from system.zookeeper where path = '/..zk_path/replicas
Check select * from system.replicas where table = ...

**Comment by simPod** [comment]
> select * from system.zookeeper where path = '/..zk_path/replicas
Gives result on both replicas. 

But on the B, there's `replicas	last added replica: A` (version: 1)
For fully replicated tables it's `replicas	last added replica: B` (version: 4)

`system.replicas` says the `total_replicas` is 1. Seems like those tables are disconnected on both replicas. Is there a way to get in in sync somehow?

**Comment by den-crane** [comment]
Check at both servers
```

select replica_name, total_replicas, active_replicas, zookeeper_path, cityHash64(zookeeper_path), hex(zookeeper_path) from system.replicas
where table = '....'
```

**Comment by simPod** [comment]
Zookeeper paths differ in a small typo :/ Thank you very much for helping me debug this. I have setup a new monitoring query to catch this in the future.
