### ISSUE TITLE
 Materialized view right table

### ISSUE THREAD

**Issue by chang0391** [ClickHouse/ClickHouse#14434]
**Describe the bug**
I created two tables as below:
CREATE TABLE default.aaa (`id` Int64, `mobile` String, `name` String) ENGINE = MergeTree() ORDER BY id
CREATE TABLE default.bbb (`id` Int64, `mobile` String, `name` String) ENGINE = MergeTree() ORDER BY id

I created Materialized view as below:
CREATE MATERIALIZED VIEW default.mv_ab  ENGINE = SummingMergeTree() ORDER BY mobile  AS SELECT aaa.mobile, count(1) as cnt FROM default.aaa INNER JOIN default.bbb ON aaa.id = bbb.id GROUP BY aaa.mobile

bug descripation as below
 I inserted data into left table "aaa" which affected materialied view, but I inserted into right table "bbb" that did not affect  materialied view

**How to reproduce**
step1:
 insert into aaa values(10,'aaa','dddd')
step2:
 insert into bbb values(10,'bbb','dddd')

version :20.3.12.112
**Expected behavior**
Can you add new functions which is Inserting the right table will also affect the materialized view, because the data of our more tables will be inserted frequently. and, these tables need join each other, If only the inserting of the left table affect the materialized view, our statistics will be inaccurate, thanks

**Comment by den-crane** [comment]
Works as designed/expected.

Materialized view is an insert trigger which watches **inserts** into the left (first from) table.

**Comment by chang0391** [comment]
Do you mean that the function of inserting the right table to affect materialized view cannot be implemented?

**Comment by chang0391** [comment]
if the function can be implemented , it will be great features

**Comment by den-crane** [comment]
you can create 2 materialized view.

```sql
CREATE TABLE default.aaa (id Int64, mobile String, name String) ENGINE = MergeTree() ORDER BY id;
CREATE TABLE default.bbb (id Int64, mobile String, name String) ENGINE = MergeTree() ORDER BY id;

CREATE TABLE default.mv_ab(mobile String, cnt UInt64) ENGINE = SummingMergeTree() ORDER BY mobile;

CREATE MATERIALIZED VIEW default.mv_ab_mva to default.mv_ab as 
SELECT aaa.mobile, count(1) as cnt FROM default.aaa 
   INNER JOIN default.bbb ON aaa.id = bbb.id GROUP BY aaa.mobile;

CREATE MATERIALIZED VIEW default.mv_ab_mvb to default.mv_ab as 
SELECT aaa.mobile, count(1) as cnt FROM default.bbb 
    INNER JOIN default.aaa  ON aaa.id = bbb.id GROUP BY aaa.mobile;

insert into default.aaa values(10,'aaa','dddd');
insert into default.bbb values(10,'bbb','dddd');

select * from default.mv_ab;

┌─mobile─┬─cnt─┐
│        │   1 │
└────────┴─────┘
```


> Do you mean that the function of inserting the right table to affect materialized view cannot be implemented?

Personally I don't like this idea. It will break some my current workflows and will double/corrupts MV data.
