### ISSUE TITLE
Allow to undo ALTER TABLE ... MODIFY SETTING

### ISSUE THREAD

**Issue by simPod** [ClickHouse/ClickHouse#14449]
I run

```sql
ALTER TABLE target_table on CLUSTER '{cluster}' MODIFY SETTING merge_with_ttl_timeout = 3600
```

But there's no way to undo it. I want the default TTL value to be mirrored for the table so I need to reset this settings.

I can run

```sql
ALTER TABLE target_table on CLUSTER '{cluster}' MODIFY SETTING merge_with_ttl_timeout = 86400
```

but that still would be only static setting and default would not be mirrored.

**Comment by den-crane** [comment]
maybe
ALTER TABLE ... REMOVE SETTINGS
ALTER TABLE ... RESET SETTINGS

**Comment by amosbird** [comment]
Or  ALTER TABLE ... MODIFY SETTINGS xxx = DEFAULT
