### ISSUE TITLE
Misleading exception message on creating a table with double-quoted arguments

### ISSUE THREAD

**Issue by myrrc** [ClickHouse/ClickHouse#14447]
**Describe the bug**
A clear and concise description of what works not as it is supposed to.

```
CREATE TABLE table_repl
(
    number UInt32
)
ENGINE = ReplicatedMergeTree("/clickhouse/{cluster}/tables/{shard}/table_repl", "{replica}")
PARTITION BY intDiv(number, 1000)
ORDER BY number
```

yields an Exception:

`DB::Exception: No macro 'uuid' in config while processing substitutions in '/clickhouse/tables/{uuid}/{shard}' at '20' or macro is not supported here.
`

**How to reproduce**
* Which ClickHouse server version to use: 20.9.1

**Expected**

The error is that the query should contain only single-quoted strings, but the message is quite misleading.
So the exception should be like "You're using double-quoted strings, which is prohibited".

**Comment by tavplubix** [comment]
ReplicatedMergeTree expects two string literal (in single quotes) arguments. Your query has two identifier (in double quotes) arguments. The following works fine:
```
:) CREATE TABLE table_repl (number UInt32) ENGINE = ReplicatedMergeTree('/clickhouse/{cluster}/tables/{shard}/table_repl', '{replica}') PARTITION BY intDiv(number, 1000) ORDER BY number

Ok.
```
However, exception message is confusing and should be fixed.

**Comment by myrrc** [comment]
> ReplicatedMergeTree expects two string literal (in single quotes) arguments. Your query has two identifier (in double quotes) arguments. The following works fine:
> 
> ```
> :) CREATE TABLE table_repl (number UInt32) ENGINE = ReplicatedMergeTree('/clickhouse/{cluster}/tables/{shard}/table_repl', '{replica}') PARTITION BY intDiv(number, 1000) ORDER BY number
> 
> Ok.
> ```
> 
> However, exception message is confusing and should be fixed.

Thanks, updates the ticket.
