### ISSUE TITLE
How to undo ALTER TABLE ... MODIFY SETTING

### ISSUE THREAD

**Issue by simPod** [ClickHouse/ClickHouse#14446]
I run

```sql
ALTER TABLE target_table on CLUSTER '{cluster}' MODIFY SETTING merge_with_ttl_timeout = 3600
```

How to undo it? That said, revert the setting to the default. I did not find any mention of `ALTER TABLE ... MODIFY` in docs

**Comment by simPod** [comment]
What if I change default value later? It would have got out of sync. The best option would be to be able to reset this so the value gets inherited. WDYT?

**Comment by den-crane** [comment]
I have no idea. I am doing triage. 
Feel free to create a feature request to address it.

**Comment by simPod** [comment]
https://github.com/ClickHouse/ClickHouse/issues/14449
