### ISSUE TITLE
TTL does not kick in on v20.6

### ISSUE THREAD

**Issue by simPod** [ClickHouse/ClickHouse#14445]
My parts in target table are due to delete:

```
delete_ttl_info_min	delete_ttl_info_max
2020-09-03 00:46:19	2020-09-03 01:37:49
```

I have set TTL to 1h for my table

```sql
ALTER TABLE target_table on CLUSTER '{cluster}' MODIFY SETTING merge_with_ttl_timeout = 3600
```

Also I tried to ensure that merges are enabled

```sql
SYSTEM START TTL MERGES
```

Though those parts are still not getting removed. I'm on v20.6 where TTL should be fixed already. What can I do to make TTL work?

**Comment by den-crane** [comment]
Check how many rows in these parts. Currently TTL leaves parts empty (with 0 rows), because CH parts design.

**Comment by simPod** [comment]
It has 447172626 rows 🤔

**Comment by simPod** [comment]
Seems like it's running now, not sure what's changed. Thanks.
