### ISSUE TITLE
Schema inference (RFC)

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#14450]
### Level 1:

If the format already contains a schema (Parquet, Avro, Protobuf, Native, TSVWithNamesAndTypes), allow to use it to derive
- the schema argument of table functions file, hdfs, url, s3...
- the structure argument of `clickhouse-local` tool;
- columns definition in CREATE TABLE statement;

Use case: just don't repeat the schema if we already have it in format.

### Level 2 (troublesome):

If the format does not contain the schema, derive "best effort" schema from the data in buffer.
If the format contains names of the columns (e.g. CSVWithNames), use these names. Otherwise use `_1`, `_2`... as column names.
Various tweaks can be used to adjust the derived schema. For example: always treat values as Nullable even if they already present in the first chunk of data in buffer. Or: use Float64 for numbers instead of Int64 / UInt64. Or: treat everything as String. Or: only extract data from subpath in JSON.

Use case:
See https://github.com/dinedal/textql
Provide a similar tool for those who like ClickHouse SQL capabilities.
Also look the discussion of the huge list of similar tools:
https://news.ycombinator.com/item?id=16781294
https://news.ycombinator.com/item?id=7175830
Look at the subthread: https://news.ycombinator.com/item?id=16782355

### How to implement:

I'm not sure that this will work.

If inference is requested:
- make a constructor of the format without the `header` argument;
- start reading data in constructor of the format (fetch first chunk of data into buffer) and derive the header from the first chunk of data in buffer.

Alllow to execute `CREATE TABLE t ENGINE = ...` without specifying the list of columns. It will mean that the list of columns will be automatically constructed in Storage constructor. Provide a Storage constructor without the list of columns and register these constructors in StorageFactory for storages that allow schema inference.

This will be also used to construct ReplicatedMergeTree tables when we add new replicas of existing table.
Merge, Distributed, Buffer will also benefit from that although `CREATE TABLE ... AS` syntax is available.

**Comment by filimonov** [comment]
Also for column ar formats (parquet / arrow) it would be nice to skip / don't read the volumes which exists in file / schema, but was not used in query. See also #13526

**Comment by alexey-milovidov** [comment]
For `LineAsString` and `RawBLOB` schema can be always inferred as `s String`.

**Comment by Avogar** [comment]
> For `LineAsString` and `RawBLOB` schema can be always inferred as `value String`.

And for `JSONAsString` also. It's already done. I will create a PR with schema inference after merging my PR with refactoring and fixing bugs in formats (because I need these changes)

**Comment by alexey-milovidov** [comment]
Solved: https://www.youtube.com/watch?v=gP7I2SUBXig

**Comment by stas-sl** [comment]
Hi! Is it possible to automatically inference schema for creating table from stdin data? What would be the syntax? I tried:

```bash
cat mydata.parquet | \
  clickhouse-client --query "CREATE TABLE data ENGINE = MergeTree ORDER BY (time) FORMAT Parquet"

cat mydata.parquet | \ 
  clickhouse-client --query "CREATE TABLE data ENGINE = MergeTree ORDER BY (time) as SELECT * FROM input() FORMAT Parquet"
```
but it didn't work.

**Comment by Avogar** [comment]
Unfortunately, schema inference from stdin for creating table is not implemented yet for clickhouse-client, but I have it my plans.
