### ISSUE TITLE
"clickhouse-odbc-bridge is not responding" during dictionary initialization: program startup sequence problems

### ISSUE THREAD

**Issue by MrSsunlight** [ClickHouse/ClickHouse#14489]
docker version: 1.13.1
clickhouse version: 20.3.11.97
system: centos7

The **/docker-entrypoint-initdb.d/** path contains the sql file, and the sql contains the **odbc  Dictionary ENGINE**; when the **_entrypoint.sh_** script is executed, there is a certain probability that the dictionary table creation fails: `Code: 410. DB::Exception: Received from 127.0.0.1:9000. DB::Exception: ODBCBridgeHelper: clickhouse-odbc-bridge is not responding.`

Only after the clickhouse-odbc-bridge process is completely started, the creation of the obdc table will be added manually again.

the [ODBC](https://clickhouse.tech/docs/en/engines/table-engines/integrations/odbc/)  `ClickHouse automatically starts clickhouse-odbc-bridge when it is required`, But what is this trigger mechanism? Can the above problems be solved in entrypoint.sh?

**entrypoint.sh  log:**
```
Recreating clickhouse ... done
Attaching to clickhouse
clickhouse           | Processing configuration file '/etc/clickhouse-server/config.xml'.
clickhouse           | Merging configuration file '/etc/clickhouse-server/config.d/config.xml'.
clickhouse           | Include not found: macros
clickhouse           | Include not found: clickhouse_compression
clickhouse           | Logging error to /var/log/clickhouse-server/clickhouse-server.log
clickhouse           | Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
clickhouse           | 
clickhouse           | /entrypoint.sh: running /docker-entrypoint-initdb.d/schema.dnsmon.sql
clickhouse           | Received exception from server (version 20.3.12):
clickhouse           | Code: 410. DB::Exception: Received from localhost:9000. DB::Exception: ODBCBridgeHelper: clickhouse-odbc-bridge is not responding. 
clickhouse           | 
clickhouse           | 
clickhouse           | Processing configuration file '/etc/clickhouse-server/config.xml'.
clickhouse           | Merging configuration file '/etc/clickhouse-server/config.d/config.xml'.
clickhouse           | Include not found: macros
clickhouse           | Include not found: clickhouse_compression
clickhouse           | Logging error to /var/log/clickhouse-server/clickhouse-server.log
clickhouse           | Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
```

**clickhouse-odbc-bridge.log:**
```
2020.09.04 17:40:30.025145 [ 121 ] {} <Trace> Pipe: Pipe capacity is 1.00 MiB
2020.09.04 17:40:30.037783 [ 121 ] {} <Debug> ApplicationStartup: Initializing subsystem: Logging Subsystem
2020.09.04 17:40:30.037858 [ 121 ] {} <Information> ApplicationStartup: Starting up
2020.09.04 17:40:30.039492 [ 121 ] {} <Information> ApplicationStartup: Listening http://[::1]:9018
2020.09.04 17:40:31.234435 [ 122 ] {} <Information> Application: Received termination signal (Terminated)
2020.09.04 17:40:31.234514 [ 121 ] {} <Debug> ApplicationStartup: Received termination signal.
2020.09.04 17:40:31.234534 [ 121 ] {} <Debug> ApplicationStartup: Waiting for current connections to close.
2020.09.04 17:40:31.292217 [ 121 ] {} <Debug> Application: Uninitializing subsystem: Logging Subsystem
2020.09.04 17:40:31.292406 [ 122 ] {} <Information> BaseDaemon: Stop SignalListener thread
```

**Comment by filimonov** [comment]
You can create some bash/sql script which do some dummy select from odbc table function, and sleep for a while. 

i.e. smth like 
```
SELECT * FROM odbc('DSN=dummy', dummy);  -- that will start clickhouse-odbc-bridge 
```

**Comment by MrSsunlight** [comment]
> 您可以创建一些bash / sql脚本，这些脚本从odbc表函数中进行一些虚拟选择，然后休眠一会儿。
> 
> 即像
> 
> ```
> SELECT * FROM odbc('DSN=dummy', dummy);  -- that will start clickhouse-odbc-bridge 
> ```
Okay, I will try it. But I still want to understand the startup mechanism and trigger conditions of clickhouse-odbc-bridge, Because the official documents are too concise.

**Comment by MrSsunlight** [comment]
> You can create some bash/sql script which do some dummy select from odbc table function, and sleep for a while.
> 
> i.e. smth like
> 
> ```
> SELECT * FROM odbc('DSN=dummy', dummy);  -- that will start clickhouse-odbc-bridge 
> ```

Okay, I will try it. But I still want to understand the startup mechanism and trigger conditions of clickhouse-odbc-bridge, Because the official documents are too concise.
