### ISSUE TITLE
how to use MergeState combinator

### ISSUE THREAD

**Issue by dongbin86** [ClickHouse/ClickHouse#14485]
i need some aggregating over aggregating examples .

```
CREATE TABLE t1
(
    `x` Int16,
    `y` String
)
ENGINE = TinyLog


CREATE MATERIALIZED VIEW IF NOT EXISTS mv1
ENGINE = AggregatingMergeTree()
ORDER BY y AS
SELECT
    y,
    countState() AS cnt
FROM t1
GROUP BY y


CREATE MATERIALIZED VIEW IF NOT EXISTS mv2
ENGINE = AggregatingMergeTree()
ORDER BY y AS
SELECT
    y,
    maxMergeState(cnt) AS maxTps
FROM mv1
GROUP BY y

```
 
![image](https://user-images.githubusercontent.com/6269809/92220757-0784b500-eecf-11ea-9ea9-7ac5f1d5b3c6.png)

**Comment by dongbin86** [comment]
31/5000 
I first do the count aggregation of 1-second granularity, and then calculate the extreme value of 1-minute granularity on this basis.

**Comment by dongbin86** [comment]
does Clickhouse currently not support one aggregation method for merging another aggregation state ?

**Comment by filimonov** [comment]
-MergeTree tranforms several states into a single state.  But obviously it should be the same function. 
You can't transform several states of one function (for example avg) to a single state of another function (for example uniq). 
The same for count / max. 

Also MV only 'see' the block which is currently inserted, not the whole table with prev states.
