### ISSUE TITLE
Support subqueries in partition expressions

### ISSUE THREAD

**Issue by antisaa** [ClickHouse/ClickHouse#14491]
**Describe the issue**
I am trying to optimize table on a subset of partitions, but I am getting syntax error:
```
OPTIMIZE TABLE intraday_metrics PARTITION 
(
    SELECT DISTINCT partition
    FROM system.parts
    WHERE (table = 'intraday_metrics') AND (partition LIKE '%2020%')
) FINAL

Code: 62. DB::Exception: Received from clickhouse-2.default.svc.cluster.local:9000. DB::Exception: Syntax error: failed at position 157: FINAL. Expected one of: LIKE, GLOBAL NOT IN, IS, OR, QuestionMark, BETWEEN, NOT LIKE, AND, IN, NOT, token, NOT IN, GLOBAL IN. 
```

**Comment by filimonov** [comment]
That is not supported right now, it can be added but i'm not 100% sure if it's a good idea. 

Workaround is - do that outside:
```bash 
clickhouse-client --query="SELECT 'OPTIMIZE TABLE intraday_metrics PARTITION ID \'' || partition_id || '\' FINAL;' FROM system.parts WHERE (table = 'intraday_metrics') AND (partition LIKE '%2020%') GROUP BY partition_id" --format=TSVRaw | clickhouse-client -mn 
```

**Comment by antisaa** [comment]
> ```shell
> SELECT 'OPTIMIZE TABLE intraday_metrics PARTITION ID \'' || partition_id || '\' FINAL;' FROM system.parts WHERE (table = 'intraday_metrics') AND (partition LIKE '%2020%') GROUP BY partition_id
> ```

Thanks @filimonov , would executing ~300 generated queries produce heavy load on database and affect performance, since the performance is the reason I am not optimizing whole table?

**Comment by den-crane** [comment]
OPTIMIZE command just initiates unplanned merge for partition(s). 
When you run `optimize table ` it iterates through all partitions in similar way as `select ... from system.parts` and call `optimize  .... partition_id` for each partition. The same amount of job.

In general it's not recommended to use OPTIMIZE at all (only exception is graphitMT & rollups). 
CH has a sophisticated algorithm in merge scheduler which plans merges in the most effective way.

**Comment by den-crane** [comment]
>FROM system.parts WHERE (table = 'intraday_metrics') AND (partition LIKE '%2020%') GROUP BY partition_id

BTW this select is too simple and runs excessive optimizes for partitions with a single part of course if it's not for graphitMT.
