### ISSUE TITLE
Is there command in ClickHouse like 'FLUSH TABLES WITH READ LOCK'?

### ISSUE THREAD

**Issue by liangli1213** [ClickHouse/ClickHouse#14512]
Is there command in ClickHouse like 'FLUSH TABLES WITH READ LOCK'?, I need to use LVM snapshot to make backup.

**Comment by amosbird** [comment]
https://clickhouse.tech/docs/en/sql-reference/statements/alter/partition/#alter_freeze-partition

**Comment by liangli1213** [comment]
@amosbird , thanks very much.
