### ISSUE TITLE
users_config and/or access_control_path together with entries from user_directories may produce duplicate access info storages

### ISSUE THREAD

**Issue by traceon** [ClickHouse/ClickHouse#14511]
Discovered during testing of #12736

When `config.xml` contains both (or one of) `users_config` and `access_control_path`, together with the corresponding entries in `user_directories`, and when the paths/values in those sections are the same, duplicate access storage are created in memory.

This leads to unexpected behavior, e.g., when a role is removed - it will be removed in one of `access_control_path`/`local_directory` duplicate and will be preserved in another, effectively making that role still available.

`SHOW ROLES`, for example, before the deletion, will show duplicate roles.

Potential solution would be avoiding creating duplicate storage when old and new corresponding config sections point to the same actual file/path.

**Comment by alexey-milovidov** [comment]
There is a chance for user to make misconfiguration - minor usability issue.

**Comment by traceon** [comment]
Unverified effects of role adjustments may easily introduce security breaches in this case.

**Comment by alexey-milovidov** [comment]
@traceon Do you want to take this task?

**Comment by traceon** [comment]
@alexey-milovidov Nope :)

**Comment by alexey-milovidov** [comment]
Not interested in this.
