### ISSUE TITLE
How to check which pull request or commit has been involved in a specific build?

### ISSUE THREAD

**Issue by liangli1213** [ClickHouse/ClickHouse#14526]
How to check which pull request or commit has been involved in a specific build?

**Comment by alexey-milovidov** [comment]
The answer is: open the commit like here: https://github.com/ClickHouse/ClickHouse/pull/13394/commits/15be6a0dd59075099ef35112ec94b153f80ace26 and look at the list of tags.

It works if commit was merged not cherry-picked or rebased.

Another option: if you are interested whether PR was backported, open the release pull request
example: https://github.com/ClickHouse/ClickHouse/pull/14587
and look at the list of backports.
