### ISSUE TITLE
MaterializeMySQL: support replication from MySQL 5.6

### ISSUE THREAD

**Issue by chang0391** [ClickHouse/ClickHouse#14524]
**Describe the bug**

 when i try to create MaterializeMySQL database, it show below error.
CREATE DATABASE ckdb
ENGINE = MaterializeMySQL('192.168.1.118:3307', 'test', 'root', 'rp123')

Received exception from server (version 20.8.1):
Code: 537. DB::Exception: Received from localhost:9000. DB::Exception: Illegal MySQL variables, the MaterializeMySQL engine requires default_authentication_plugin='mysql_native_password'. 

0 rows in set. Elapsed: 0.013 sec.

mysql version:5.6.35
my.cnf
port            = 3306
socket= /home/mysql/data/mysql.sock
default_authentication_plugin=mysql_native_password
##default-character-set=utf8mb4
[mysqld]
server-id = 118
log-bin = mysql-bin
character_set_server=utf8mb4
socket=/home/mysql/data/mysql.sock
binlog_format = row
max_binlog_size = 1G
binlog_cache_size = 2M
expire-logs-days = 10
slow_query_log = 1
slow_query_log_file = /home/mysql/data/slow.log
lower_case_table_names =1
default_authentication_plugin=mysql_native_password
gtid-mode = on
log-slave-updates = true
enforce-gtid-consistency =1
datadir=/home/mysql/data
thread_cache_size = 256
thread_concurrency = 32
open_files_limit = 10240
sort_buffer_size = 8M
read_rnd_buffer_size = 4M
join_buffer_size = 8M
query_cache_limit = 8M
query_cache_size = 256M
bulk_insert_buffer_size = 64M

#InnoDB
innodb_buffer_pool_size = 10G
innodb_flush_log_at_trx_commit = 2
innodb_log_buffer_size = 16M
innodb_log_file_size = 2G
innodb_log_files_in_group = 3
innodb_thread_concurrency = 0

**Comment by liangli1213** [comment]
@chang0391 , you have a typo, it should be port = 3306, but you use 192.168.1.118:3307

**Comment by BohuTANG** [comment]
create query is ok.
Should check default_authentication_plugin:
```
mysql> show variables like '%default_authentication_plugin';
+-------------------------------+-----------------------+
| Variable_name                 | Value                 |
+-------------------------------+-----------------------+
| default_authentication_plugin | mysql_native_password |
+-------------------------------+-----------------------+
1 row in set (0.01 sec)

```

**Comment by chang0391** [comment]
@BohuTANG  
   
    I don't have this variable as below

Server version: 5.6.35-log Source distribution

Copyright (c) 2000, 2016, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> show variables like '%default_authentication_plugin%'
    -> ;
Empty set (0.01 sec)


but, I found user is using mysql_native_password of plugin
mysql> select distinct plugin from mysql.user;
+-----------------------+
| plugin                |
+-----------------------+
| mysql_native_password |
+-----------------------+
1 row in set (0.00 sec)
clickhouse:
CREATE DATABASE credit_ga
ENGINE = MaterializeMySQL('192.168.1.118:3306', 'credit_ga', 'root', 'rp123456')


Received exception from server (version 20.8.1):
Code: 537. DB::Exception: Received from localhost:9000. DB::Exception: Illegal MySQL variables, the MaterializeMySQL engine requires default_authentication_plugin='mysql_native_password'. 

0 rows in set. Elapsed: 0.011 sec.

**Comment by BohuTANG** [comment]
Oops, please use MySQL 5.7/8.0.

**Comment by chang0391** [comment]
our production envirnment totally are using MySQL5.6, can MaterizlizeMySQL support MySQL5.6

**Comment by BohuTANG** [comment]
is GTID turned on?

**Comment by chang0391** [comment]
yes
gtid-mode = on
enforce-gtid-consistency =1

**Comment by liuzhiqiang123gitHub** [comment]
> yes
> gtid-mode = on
> enforce-gtid-consistency =1

gtid_mode = on
enforce_gtid_consistency =1 ,it's underscore

**Comment by tavplubix** [comment]
#14564

**Comment by leoones** [comment]
> **Describe the bug**
> 
> when i try to create MaterializeMySQL database, it show below error.
> CREATE DATABASE ckdb
> ENGINE = MaterializeMySQL('192.168.1.118:3307', 'test', 'root', 'rp123')
> 
> Received exception from server (version 20.8.1):
> Code: 537. DB::Exception: Received from localhost:9000. DB::Exception: Illegal MySQL variables, the MaterializeMySQL engine requires default_authentication_plugin='mysql_native_password'.
> 
> 0 rows in set. Elapsed: 0.013 sec.
> 
> mysql version:5.6.35
> my.cnf
> port = 3306
> socket= /home/mysql/data/mysql.sock
> default_authentication_plugin=mysql_native_password
> ##default-character-set=utf8mb4
> [mysqld]
> server-id = 118
> log-bin = mysql-bin
> character_set_server=utf8mb4
> socket=/home/mysql/data/mysql.sock
> binlog_format = row
> max_binlog_size = 1G
> binlog_cache_size = 2M
> expire-logs-days = 10
> slow_query_log = 1
> slow_query_log_file = /home/mysql/data/slow.log
> lower_case_table_names =1
> default_authentication_plugin=mysql_native_password
> gtid-mode = on
> log-slave-updates = true
> enforce-gtid-consistency =1
> datadir=/home/mysql/data
> thread_cache_size = 256
> thread_concurrency = 32
> open_files_limit = 10240
> sort_buffer_size = 8M
> read_rnd_buffer_size = 4M
> join_buffer_size = 8M
> query_cache_limit = 8M
> query_cache_size = 256M
> bulk_insert_buffer_size = 64M
> 
> #InnoDB
> innodb_buffer_pool_size = 10G
> innodb_flush_log_at_trx_commit = 2
> innodb_log_buffer_size = 16M
> innodb_log_file_size = 2G
> innodb_log_files_in_group = 3
> innodb_thread_concurrency = 0

How is this problem solved? Is MySQL5.6 not supported?

**Comment by leoones** [comment]
@chang0391 
How is this problem solved ? Is MySQL5.6 not supported ?

**Comment by BohuTANG** [comment]
Already on it , but there are some CI issues to deal, https://github.com/ClickHouse/ClickHouse/pull/14564

**Comment by tavplubix** [comment]
AFAIK MySQL 5.6 will reach its end of life in Feb 2021, it will not be longer officially supported.

Maybe we can close this issue too?
