### ISSUE TITLE
The result of multiplying 0 by a negative real number is -0

### ISSUE THREAD

**Issue by StarWix** [ClickHouse/ClickHouse#1453]
Actual result:
```
SELECT 0 * -0.1
┌─multiply(0, -0.1)─┐
│                -0 │
└───────────────────┘
```
Expected result: 0

**Comment by alexey-milovidov** [comment]
This is documented behaviour.

We can consider implementing some functions or settings to make arithmetic operations filter out special values like infinities, nans and -0. (This will have some runtime cost.)

**Comment by StarWix** [comment]
It would be useful to have a setting to autoconvert -0 to 0.

Otherwise you have to wrap expression with multiply or division operators to `if` function,  `-0` - `0` converting. It looks ugly:
```
SELECT 
    if(x = 0, 0, x) AS y, 
    count()
FROM 
(
    SELECT 0 * -1. AS x
    UNION ALL 
    SELECT 0.
    UNION ALL 
    SELECT 1.
) 
GROUP BY y

┌─y─┬─count()─┐
│ 0 │       2 │
│ 1 │       1 │
└───┴─────────┘
```
