### ISSUE TITLE
How to solve the performance check fail?

### ISSUE THREAD

**Issue by fastio** [ClickHouse/ClickHouse#14544]
Hi guys, I have a pr about Kafka engine, #13939 .  
The performance check is always fail, and the link of details seams broken.
Please help me :)

**Comment by akuzm** [comment]
Was broken in master, fixed now https://github.com/ClickHouse/ClickHouse/commit/0904433c87b8fff3487a86c2076220d9252deccd

**Comment by alexey-milovidov** [comment]
Not quite fixed.
