### ISSUE TITLE
system.processes The table shows a large number of drop partiton jams

### ISSUE THREAD

**Issue by yd1261137568** [ClickHouse/ClickHouse#14568]
system.processes The table shows a large number of drop partiton jams,They can't be killed.Still stuck after restart

version : 20.5.4.40
query
/* ddl_entry=query-0000373376 */ TRUNCATE TABLE data_usergroup.t_person_user_identity_shard
alter table data_usergroup.t_person_imei_event_neirong_v2_shard  drop partition '1980-01-02'
"select hostName(),query_id,query
from `system`.processes_all
FORMAT TabSeparatedWithNamesAndTypes;"
/* ddl_entry=query-0000373361 */ ALTER TABLE data_usergroup.t_person_imei_event_neirong_v2_shard DROP PARTITION '1980-01-01' 
ALTER TABLE t_person_imei_base_effect_shard DROP PARTITION ('2020-09-07');
alter table data_usergroup.t_person_imei_event_neirong_v2_shard  drop partition '1980-01-02'
alter table data_usergroup.t_person_imei_event_neirong_v2_shard  drop partition '1980-01-02'
alter table data_usergroup.t_person_imei_event_neirong_v2_shard  drop partition '1980-01-02'
alter table data_usergroup.t_person_imei_event_neirong_v2_shard  drop partition '1980-01-02'
alter table data_usergroup.t_person_imei_event_neirong_v2_shard  drop partition '1980-01-02'
ALTER TABLE t_person_imei_base_effect_shard DROP PARTITION ('2020-09-07');
SELECT hostName(), query_id, query FROM system.processes
/* ddl_entry=query-0000373361 */ ALTER TABLE data_usergroup.t_person_imei_event_neirong_v2_shard DROP PARTITION '1980-01-01' 
ALTER TABLE t_person_imei_base_effect_shard DROP PARTITION ('2020-09-07');
ALTER TABLE t_person_imei_base_effect_shard DROP PARTITION ('2020-09-07');
ALTER TABLE t_person_imei_base_effect_shard DROP PARTITION ('2020-09-07');
ALTER TABLE t_person_imei_base_effect_shard DROP PARTITION ('2020-09-07');
alter table data_usergroup.t_person_imei_event_neirong_v2_shard  drop partition '1980-01-02'
ALTER TABLE t_person_imei_base_effect_shard DROP PARTITION ('2020-09-07');
alter table data_usergroup.t_person_imei_event_neirong_v2_shard  drop partition '1980-01-02'
alter table data_usergroup.t_person_imei_event_neirong_v2_shard  drop partition '1980-01-02'
alter table data_usergroup.t_person_imei_event_neirong_v2_shard  drop partition '1980-01-02'
ALTER TABLE t_person_imei_base_effect_shard DROP PARTITION ('2020-09-07');
alter table data_usergroup.t_person_imei_event_neirong_v2_shard  drop partition '1980-01-02'
SELECT hostName(), query_id, query FROM system.processes
/* ddl_entry=query-0000373360 */ ALTER TABLE data_usergroup.t_person_imei_event_neirong_v2_shard DROP PARTITION '1980-01-01' 
alter table data_usergroup.t_person_imei_event_neirong_v2_shard  drop partition '1980-01-02'
alter table data_usergroup.t_person_imei_event_neirong_v2_shard  drop partition '1980-01-02'
alter table data_usergroup.t_person_imei_event_neirong_v2_shard  drop partition '1980-01-02'
alter table data_usergroup.t_person_imei_event_neirong_v2_shard  drop partition '1980-01-02'
alter table data_usergroup.t_person_imei_event_neirong_v2_shard  drop partition '1980-01-02'
SELECT hostName(), query_id, query FROM system.processes
/* ddl_entry=query-0000373363 */ ALTER TABLE data_usergroup.t_person_imei_event_neirong_v2_shard DROP PARTITION '1980-01-01' 
alter table data_usergroup.t_person_imei_event_neirong_v2_shard  drop partition '1980-01-02'
SELECT hostName(), query_id, query FROM system.processes
/* ddl_entry=query-0000373360 */ ALTER TABLE data_usergroup.t_person_imei_event_neirong_v2_shard DROP PARTITION '1980-01-01' 
alter table data_usergroup.t_person_imei_event_neirong_v2_shard  drop partition '1980-01-02'
alter table data_usergroup.t_person_imei_event_neirong_v2_shard  drop partition '1980-01-02'
alter table data_usergroup.t_person_imei_event_neirong_v2_shard  drop partition '1980-01-02'
alter table data_usergroup.t_person_imei_event_neirong_v2_shard  drop partition '1980-01-02'
alter table data_usergroup.t_person_imei_event_neirong_v2_shard  drop partition '1980-01-02'
ALTER TABLE data_usergroup.t_person_imei_event_neirong_v2_shard ON cluster cluster2_2shards_2replicas DROP PARTITION '1980-01-01'
SELECT hostName(), query_id, query FROM system.processes

**Comment by yd1261137568** [comment]
My problems and https://github.com/ClickHouse/ClickHouse/issues/13619 Almost the same,system.replication_ There is a lot of data in the queue,I don't know what to do

**Comment by filimonov** [comment]
> My problems and #13619 Almost the same,system.replication_ There is a lot of data in the queue,I don't know what to do

That sounds completely different. If you can't find the reason / you think it's a bug - please open separate issue.

**Comment by filimonov** [comment]
> system.processes The table shows a large number of drop partiton jams,They can't be killed.Still stuck after restart

Maybe they are waiting for somethin (check system.mutations & system.merges). 

If you want force removeing of those - you need to stop the node, clean the /clickhouse/task_queue in zookeeper, and start the node back

**Comment by yd1261137568** [comment]
> > system.processes该表显示大量掉落的分区卡纸，它们无法杀死。重新启动后仍然卡住
> 
> 也许他们正在等待一些东西（检查system.mutations和system.merges）。
> 
> 如果要强制删除这些节点，则需要停止该节点，在zookeeper中清洁/ clickhouse / task_queue，然后重新启动该节点。

This problem is also caused by upgrading the service version and operating system. We first upgraded half of the service and operating system, and then synchronized the data. However, when the data was not synchronized, we upgraded the other half of the server, resulting in the loss of part,

old version:19.9.5.36

new version:20.5.4.40



According to your suggestion, at present, I delete the relevant data on zookeeper, restart the cluster, rebuild the created table and specify a new hookeeper path. At this time, the drop partition can be executed

However, if any on cluster statement is executed again, it will still get stuck, system.mutations There is a lot of data in


> > system.processes The table shows a large number of drop partiton jams,They can't be killed.Still stuck after restart
> 
> Maybe they are waiting for somethin (check system.mutations & system.merges).
> 
> If you want force removeing of those - you need to stop the node, clean the /clickhouse/task_queue in zookeeper, and start the node back

Thank you for your reply

This problem is also caused by upgrading the service version and operating system. We first upgraded half of the service and operating system, and then synchronized the data. However, when the data was not synchronized, we upgraded the other half of the server, resulting in the loss of part,

old version:19.9.5.36

new version:20.5.4.40



According to your suggestion, at present, I delete the relevant data on zookeeper, restart the cluster, rebuild the created table and specify a new hookeeper path. At this time, the drop partition can be executed

However, if any on cluster statement is executed again, it will still get stuck, system.mutations There is a lot of data in

database	table	mutation_id	command	create_time	block_numbers.partition_id	block_numbers.number	parts_to_do_names	parts_to_do	is_done	latest_failed_part	latest_fail_time	latest_fail_reason
data_usergroup	t_sketch_label_shard	0000000059	DELETE WHERE imei IN (SELECT imei FROM data_usergroup.t_sketch_label_tmp_final)	2020-08-18 09:38:49	['19800101','20200727','20200729','20200730','20200731','20200801','20200802','20200803','20200804','20200805','20200806']	[398,106,57,56,55,53,54,52,51,46,46]		0	1		[NULL]	
data_usergroup	t_sketch_label_shard	0000000060	DELETE WHERE imei IN (SELECT imei FROM data_usergroup.t_sketch_label_tmp_final)	2020-08-18 09:39:20	['19800101','20200727','20200729','20200730','20200731','20200801','20200802','20200803','20200804','20200805','20200806']	[399,107,58,57,56,54,55,53,52,47,47]		0	1		[NULL]	
data_usergroup	t_sketch_label_shard	0000000061	DELETE WHERE imei IN (SELECT imei FROM data_usergroup.t_sketch_label_tmp_final)	2020-08-19 08:00:24	['19800101','20200727','20200729','20200730','20200731','20200801','20200802','20200803','20200804','20200805','20200806']	[452,108,59,58,57,55,56,54,53,48,48]		0	1		[NULL]	
data_usergroup	t_sketch_label_shard	0000000062	DELETE WHERE imei IN (SELECT imei FROM data_usergroup.t_sketch_label_tmp_final)	2020-08-19 08:05:26	['19800101','20200727','20200729','20200730','20200731','20200801','20200802','20200803','20200804','20200805','20200806']	[453,109,60,59,58,56,57,55,54,49,49]		0	1		[NULL]	
data_usergroup	t_sketch_label_shard	0000000063	DELETE WHERE imei IN (SELECT imei FROM data_usergroup.t_sketch_label_tmp_final)	2020-08-20 11:28:19	['19800101','20200727','20200729','20200730','20200731','20200801','20200802','20200803','20200804','20200805','20200806']	[507,110,61,60,59,57,58,56,55,50,50]		0	1		[NULL]	
data_usergroup	t_sketch_label_shard	0000000064	DELETE WHERE imei IN (SELECT imei FROM data_usergroup.t_sketch_label_tmp_final)	2020-08-20 11:28:37	['19800101','20200727','20200729','20200730','20200731','20200801','20200802','20200803','20200804','20200805','20200806']	[508,111,62,61,60,58,59,57,56,51,51]		0	1		[NULL]	
data_usergroup	t_sketch_label_shard	0000000065	DELETE WHERE imei IN (SELECT imei FROM data_usergroup.t_sketch_label_tmp_final)	2020-08-21 08:12:28	['19800101','20200727','20200729','20200730','20200731','20200801','20200802','20200803','20200804','20200805','20200806']	[561,112,63,62,61,59,60,58,57,52,52]		0	1		[NULL]	
data_usergroup	t_sketch_label_shard	0000000066	DELETE WHERE imei IN (SELECT imei FROM data_usergroup.t_sketch_label_tmp_final)	2020-08-21 08:17:31	['19800101','20200727','20200729','20200730','20200731','20200801','20200802','20200803','20200804','20200805','20200806']	[562,113,64,63,62,60,61,59,58,53,53]		0	1		[NULL]	
data_usergroup	t_sketch_label_shard	0000000067	DELETE WHERE imei IN (SELECT imei FROM data_usergroup.t_sketch_label_tmp_final)	2020-08-21 18:05:52	['19800101','20200727','20200729','20200730','20200731','20200801','20200802','20200803','20200804','20200805','20200806']	[613,114,65,64,63,61,62,60,59,54,54]		0	1		[NULL]	
data_usergroup	t_sketch_label_shard	0000000068	DELETE WHERE imei IN (SELECT imei FROM data_usergroup.t_sketch_label_tmp_final)	2020-08-21 18:06:25	['19800101','20200727','20200729','20200730','20200731','20200801','20200802','20200803','20200804','20200805','20200806']	[614,115,66,65,64,62,63,61,60,55,55]		0	1		[NULL]	
data_usergroup	t_sketch_label_shard	0000000069	DELETE WHERE imei IN (SELECT imei FROM data_usergroup.t_sketch_label_tmp_final)	2020-08-22 11:09:18	['19800101','20200727','20200729','20200730','20200731','20200801','20200802','20200803','20200804','20200805','20200806']	[671,116,67,66,65,63,64,62,61,56,56]		0	1		[NULL]

**Comment by yd1261137568** [comment]
> > system.processes The table shows a large number of drop partiton jams,They can't be killed.Still stuck after restart
> 
> Maybe they are waiting for somethin (check system.mutations & system.merges).
> 
> If you want force removeing of those - you need to stop the node, clean the /clickhouse/task_queue in zookeeper, and start the node back

May I ask system.mutations How to deal with a large amount of data? Do you need to delete the corresponding table?

**Comment by yd1261137568** [comment]
Sorry, it seems that I can't upload pictures here. After executing on cluster, I will wait until DDL timeout
tjtx-89-77.58os.org :) drop table if exists data_usergroup.aaa on cluster cluster_shard_one;

DROP TABLE IF EXISTS data_usergroup.aaa ON CLUSTER cluster_shard_one

┌─host─────────┬─port─┬─status─┬─error─┬─num_hosts_remaining─┬─num_hosts_active─┐
│ 10.126.89.77 │ 9998 │      0 │       │                   5 │                0 │
└──────────────┴──────┴────────┴───────┴─────────────────────┴──────────────────┘
↓ Progress: 1.00 rows, 56.00 B (4.77 rows/s., 267.30 B/s.)  16%
Received exception from server (version 20.5.4):
Code: 159. DB::Exception: Received from localhost:9998. DB::Exception: Watching task /clickhouse/task_queue/ddl/query-0000373469 is executing longer than distributed_ddl_task_timeout (=180) seconds. There are 5 unfinished hosts (0 of them are currently active), they are going to execute the query in background. 

1 rows in set. Elapsed: 180.025 sec.

**Comment by alexey-milovidov** [comment]
In previous versions there was possibility of deadlocks in ALTER ... PARTITION queries.
In recent versions there is no such possibility.

In previous versions DROP TABLE can be locked by other queries to the same table.
After we enabled `Atomic` database by default it's not longer the case.
