### ISSUE TITLE
GRANT ALTER TTL also grants ALTER MATERIALIZE TTL

### ISSUE THREAD

**Issue by ritaank** [ClickHouse/ClickHouse#14566]
**Describe the bug**
Granting privilege `ALTER TTL` also grants `ALTER MATERIALIZE TTL` to the `user/role`, even though they are listed as distinct privileges.

**How to reproduce**
```
ClickHouse client version 20.9.1.4521 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 20.9.1 revision 54439.

:) CREATE TABLE test2
(
    `d` DATE,
    `a` String,
    `b` UInt8,
    `x` String,
    `y` Int8
)
ENGINE = MergeTree()
PARTITION BY y
ORDER BY d

Ok.

:) CREATE USER user0

Ok.

:) GRANT ALTER TTL ON test2 TO user0

Ok.

:) SHOW GRANTS FOR user0

┌─GRANTS FOR user0──────────────────────────┐
│ GRANT ALTER TTL ON default.test2 TO user0 │

ClickHouse client version 20.9.1.4521 (official build).
Connecting to localhost:9000 as user user0.
Connected to ClickHouse server version 20.9.1 revision 54439.

:) ALTER TABLE test2
    MODIFY TTL d + toIntervalDay(1)

Ok.
```
And this is expected, since `ALTER TTL` was granted to `user0`.

However:

```
ClickHouse client version 20.9.1.4521 (official build).
Connecting to localhost:9000 as user user0.
Connected to ClickHouse server version 20.9.1 revision 54439.

:) ALTER TABLE test2
    MATERIALIZE TTL     IN PARTITION 2

Ok.
```
The `MATERIALIZE TTL` query also works for `user0`, which should not happen.

**Expected behavior**
I would expect that a user with only `ALTER TTL` granted would not also be able to run `ALTER MATERIALIZE TTL` queries.

**Comment by filimonov** [comment]
>  I would expect that a user with only ALTER TTL granted would not also be able to run ALTER MATERIALIZE TTL queries. 

Can you explain why do you think so? My expectations are opposite.

And in recent ClickHouse versions materialize ttl happen automatically when you alter ttl. 

What do you think materialize do?

**Comment by filimonov** [comment]
" even though they are listed as distinct privileges" 

Ah, that's strange actually.

**Comment by ritaank** [comment]
I mean I guess I find it strange as well, but I am just going off of the privilege hierarchy as listed [here](https://clickhouse.tech/docs/en/sql-reference/statements/grant/#grant-privileges)

![image](https://user-images.githubusercontent.com/47439507/92509918-dd2d4300-f1bf-11ea-9d48-b6e85ffd32ac.png)

`TTL` and `MATERIALIZE TTL` are distinct.

**Comment by alexey-milovidov** [comment]
@vitlibar Said that it works as expected, but documentation can be misleading.

**Comment by vitlibar** [comment]
https://github.com/ClickHouse/ClickHouse/pull/23238/files
