### ISSUE TITLE
 "Too many files open" error while "optimizing table table_name"

### ISSUE THREAD

**Issue by lookingGordo** [ClickHouse/ClickHouse#14574]
ClickHouse client version 18.14.8.
  not have zookeeper.
  not have partition by
 
![image](https://user-images.githubusercontent.com/47914603/92439509-8afb1a80-f1dd-11ea-885b-af0ca3b8fb73.png)

  I have a table, using the ReplacingMergeTree engine, with 112 columns, more than 2,000 files on disk(ls database/table_name/* |wc -l  ==> 2074), and insert data normally. When manually triggered "optimizing table table_name" , the table is wrong:  
  Code: 76. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Cannot open file /data/clickhouse/data/database/table_name/20200907_20200907_53_53_0/column.bin, errno: 24, strerror: Too many open files.
 
 ulimit -n
 65535
 
 clickhouse Open file by default (Max)

----  At four o 'clock in the afternoon

"optimizing table table_name" success

 (ls database/table_name/* |wc -l  ==> 2600)

 all processes open file sum is 4900

I often get this error，https://github.com/ClickHouse/ClickHouse/issues/8121.  the mistake is different from mine

**Comment by den-crane** [comment]
This version 18.14.8 is unsupported. Try to upgrade to a stable (20.8, 20.7, 20.6) or LTS (20.3) versions.

**Comment by filimonov** [comment]
ClickHouse distibution has a file to adjust the limits:
https://github.com/ClickHouse/ClickHouse/blob/master/debian/clickhouse.limits

Docker readme file also show how to increate ulimit for number of files.

So most probably you installed clickhouse in some non-standard way.

**Comment by den-crane** [comment]
You need to check ulimits for process, not current shell.

```
ps -ef|grep click
...
clickho+ 32747     1  1 Sep08 ?        00:01:25 clickhouse-server --daemon --pid-file=/var/run/clickhouse-server/clickhouse-server.pid --config-file=/etc/clickhouse-server/config.xml

more /proc/32747/limits
Limit                     Soft Limit           Hard Limit           Units
Max cpu time              unlimited            unlimited            seconds
Max file size             unlimited            unlimited            bytes
Max data size             unlimited            unlimited            bytes
Max stack size            8388608              unlimited            bytes
Max core file size        1073741824           unlimited            bytes
Max resident set          unlimited            unlimited            bytes
Max processes             256878               256878               processes
Max open files            262144               262144               files              <---------
Max locked memory         65536                65536                bytes
Max address space         unlimited            unlimited            bytes
Max file locks            unlimited            unlimited            locks
Max pending signals       256878               256878               signals
Max msgqueue size         819200               819200               bytes
Max nice priority         0                    0
Max realtime priority     0                    0
Max realtime timeout      unlimited            unlimited            us

```

**Comment by lookingGordo** [comment]
![image](https://user-images.githubusercontent.com/47914603/92689774-3d63e680-f372-11ea-98bc-274dff87dc3d.png)
Yes, I did.
After changing the ULimit, Clickhouse does not restart
Thank you for your help！
