### ISSUE TITLE
MaterializeMySQL: CREATE TABLE t1 AS t2 is not supported

### ISSUE THREAD

**Issue by chang0391** [ClickHouse/ClickHouse#14573]
**Describe the bug**
clickhouse :) select count(1) from aaa
SELECT count(1)
FROM aaa
Received exception from server (version 20.8.1):
Code: 48. DB::Exception: Received from localhost:9000. DB::Exception: Cannot convert create like statement to ClickHouse SQL. 
0 rows in set. Elapsed: 0.005 sec. 
**How to reproduce**
mysql> create table table1 like table
**Expected behavior**
I suggest that one table issue don't implact other tables because one database may have two hundard tables
once one table got issue, other tables can not be access, i think that if one table got issue, only need synchronization the table,
other tables can be access normally,it is good idea
if table can be configurable. Only some key tables are synchronized to the Clickhouse. I think most people like this function

**Comment by den-crane** [comment]
Currently CH supports `create table R as L` but not `create table R like L`

**Comment by chang0391** [comment]
yes, CH supports create table R as L ，however, Engine of Materializemysql synchronize data from mysql to CH in real time, if I execute create table R like L in MySQL, CH should execute  create table R as L , but CH reports " Cannot convert create like statement to ClickHouse SQL"

**Comment by zhang2014** [comment]
> yes, CH supports create table R as L ，however, Engine of Materializemysql synchronize data from mysql to CH in real time, if I execute create table R like L in MySQL, CH should execute create table R as L , but CH show this issue " Cannot convert create like statement to ClickHouse SQL"

This is not allowed, because we are not sure if this like table exists in ClickHouse

**Comment by chang0391** [comment]
yes,  if this  is not supported, It's better to only have this table affected
synchronization or accessing  of other tables should not be affected, but I can not access other tables.
or is there any way to skip gtid number or event?

**Comment by chang0391** [comment]
@zhang2014 

      

> yes, CH supports create table R as L ，however, Engine of Materializemysql synchronize data from mysql to CH in real time, if I execute create table R like L in MySQL, CH should execute create table R as L , but CH show this issue " Cannot convert create like statement to ClickHouse SQL"
> 
> This is not allowed, because we are not sure if this like table exists in ClickHouse
感觉clickhouse 转化为create table R as L操作比较好，如果clickhouse 执行的时候发现like的表不存在，可以提示出来，这样用户可以补充这张表，最后再次重新启动同步自动执行这个操作。就像mysql 从库那样，执行 stop slave ，然后修改数据， 最后start  slave

**Comment by zhang2014** [comment]
When synchronization failure(we stop sync for data consistency), we always want the users to see the exception info as much as possible(I think this reasonable for experimental features.)

FYI:
https://github.com/ClickHouse/ClickHouse/pull/10851#issuecomment-669324802
https://github.com/ClickHouse/ClickHouse/pull/10851#issuecomment-670348252

**Comment by zhang2014** [comment]
> yes, CH supports create table R as L ，however, Engine of Materializemysql synchronize data from mysql to CH in real time, if I execute create table R like L in MySQL, CH should execute create table R as L , but CH show this issue " Cannot convert create like statement to ClickHouse SQL"

> This is not allowed, because we are not sure if this like table exists in ClickHouse
感觉clickhouse 转化为create table R as L操作比较好，如果clickhouse 执行的时候发现like的表不存在，可以提示出来，这样用户可以补充这张表，最后再次重新启动同步自动执行这个操作。就像mysql 从库那样，执行 stop slave ，然后修改数据， 最后start slave

This is difficult because synchronizing data based on the database level will make it impossible to guarantee that the table structure in other databases is correct.
