### ISSUE TITLE
Migrating data from old Merge Tree Syntax

### ISSUE THREAD

**Issue by prakharkohq** [ClickHouse/ClickHouse#14576]
Hello Everyone,
I have a table with this signature i will name it as TABLE1
`ENGINE = MergeTree(BookingDate, (Year, EmailID, RouteID, OperatorId, TIN, JourneyDate, BookingDate), 8192)
`
and this table has few billions of records in it and now i want to convert this table to Replicated merge tree of this signature lets call this TABLE2

```
ENGINE = ReplicatedMergeTree('/data/zookeeper/clickhouse/hostone/tables/TABLE2', 'replica_14')
PARTITION BY BookingDate
ORDER BY (Year, EmailID, RouteID, OperatorId, TIN, JourneyDate, BookingDate)
SETTINGS index_granularity = 8192
```
So steps i did was copy the data from old signature table to new signature table under detached folder and run this query 

```

SELECT DISTINCT 
    partition_id,
    name
FROM system.detached_parts
WHERE (database = 'my_db') AND (table = 'TABLE2')
ORDER BY partition_id ASC
FORMAT CSV
```
it gives me result like this 

"20190131","20190101_20190131_2402935_2746802_3978_12240547"
"20190228","20190201_20190228_2746803_5532644_7121_12240547"
"20190331","20190301_20190331_5529373_8583155_7192_12240547"

When i try to attach these partitions by using these 2 methods 

**Method 1 :** 
ALTER TABLE `my_db`.`TABLE2` ATTACH PARTITION 20190131 

Ok.
0 rows in set. Elapsed: 0.021 sec. 

However count() remains zero and logs print something like this
2020.09.08 08:04:14.120203 [ 26624 ] {afdc4b83-1025-46dc-bfe6-84dfc88c9074} <Debug> executeQuery: (from [::ffff:127.0.0.1]:43994, user: admin) ALTER TABLE `my_db`.`TABLE2` ATTACH PARTITION 20190131
2020.09.08 08:04:14.120269 [ 26624 ] {afdc4b83-1025-46dc-bfe6-84dfc88c9074} <Trace> ContextAccess (admin): Access granted: INSERT ON my_db.TABLE2
2020.09.08 08:04:14.120620 [ 26624 ] {afdc4b83-1025-46dc-bfe6-84dfc88c9074} <Debug> my_db.TABLE2: Looking for parts for partition 19700822 in detached/
2020.09.08 08:04:14.120680 [ 26624 ] {afdc4b83-1025-46dc-bfe6-84dfc88c9074} **<Debug> my_db.TABLE2: 0 of them are active**

Method 2 : 

```
ALTER TABLE  my_db.TABLE2
    ATTACH PART '20190301_20190331_5529373_8583155_7192_12240547'



Received exception from server (version 20.5.4):
Code: 233. DB::Exception: Received from localhost:9000. DB::Exception: Unexpected part name: 20190301_20190331_5529373_8583155_7192_12240547.
```

**Comment by den-crane** [comment]
Parts in these tables  (old and new formats) are incompatible. 

The only way is `insert into new select from old`

**Comment by filimonov** [comment]
There is an util to make that convertation, you can build it and try if you want (on own risk) - see
https://github.com/ClickHouse/ClickHouse/blob/master/utils/convert-month-partitioned-parts/main.cpp

**Comment by den-crane** [comment]
btw, this util works only against not replicated tables and nobody tested it for couple years.

**Comment by prakharkohq** [comment]
Thanks @filimonov and @den-crane  I will look into this. https://github.com/ClickHouse/ClickHouse/blob/master/utils/convert-month-partitioned-parts/main.cpp
