### ISSUE TITLE
"Part state Committed already exists" error when moving partitions from 2 tables into third one

### ISSUE THREAD

**Issue by dmgburg** [ClickHouse/ClickHouse#14582]
**Describe the bug**
"DB::Exception: Part 20200101_2_2_0 (state Committed) already exists" when moving same partition from different tables into third one.

**How to reproduce**
* Which ClickHouse server version to use
Tested on versions: 20.7.2.30 (official build), version 20.3.11.97 (official build)

```
drop table if exists A;
drop table if exists B;
drop table if exists C;
create table A (     a Int32,     b Date ) engine MergeTree()       partition by b       order by b;
create table B (     a Int32,     b Date ) engine MergeTree()       partition by b       order by b;
create table C (     a Int32,     b Date ) engine MergeTree()       partition by b      order by b;
insert into A select number as a, toDate('2020-01-01') as b from numbers(100);
insert into B select number as a, toDate('2020-01-01') as b from numbers(100);
select count() from A; -- 100
ALTER TABLE A MOVE PARTITION '2020-01-01' to table C;
select count() from A; -- 0
select count() from C; -- 100
ALTER TABLE B MOVE PARTITION '2020-01-01' to table C; -- Code: 235, e.displayText() = DB::Exception: Part 20200101_2_2_0 (state Committed) already exists (version 20.3.11.97 (official build))
```

**Expected behavior**
Expected to move all data from tables A and B to table C. 

**Error message and/or stacktrace**
Code: 235, e.displayText() = DB::Exception: Part 20200101_2_2_0 (state Committed) already exists (version 20.3.11.97 (official build))

**Additional context**
Use case: 
I need to insert large batches of data to MergeTree and safely retry insert if something goes wrong. 
Current schema is 
1) create a temp table for each partition (with same schema and engine settings as target table)
2) insert data
3) validate data consistency in temp table
4) move partition to target table
5) drop empty temp tables 

It works fine when I do not write same partition from multiple sources, but if I do the exception above happens.

**Comment by amosbird** [comment]
Try https://clickhouse.tech/docs/en/sql-reference/statements/alter/partition/#alter_attach-partition-from  instead. `MOVE PARTITION` has different semantics against your use case.

**Comment by dmgburg** [comment]
It works just fine. Thank you!

**Comment by cyberhuman** [comment]
The bug is in `StorageMergeTree::movePartitionToTable`.
It does this:
```
dest_table_storage->renameTempPartAndReplace(part, &increment, &transaction, lock);
```
but AFAIU it must use `&dest_table_storage->increment` instead.

**Comment by alexey-milovidov** [comment]
Fixed in https://github.com/ClickHouse/ClickHouse/pull/21760.
