### ISSUE TITLE
If the materialized view is incorrectly configured, data writing to the source table will be affected

### ISSUE THREAD

**Issue by IVitamin-C** [ClickHouse/ClickHouse#14584]
version:20.6.3
problem:
If the materialized view is incorrectly configured, data writing to the source table will be affected
Describe:
I created a  ReplicatedMergeTree Table.When the configuration of materialized view is wrong, the data cannot be written normally. This is normal. However, the data writing of the ReplicatedMergeTree table also failed. This is unreasonable in my understanding. It will affect the data writing problem of other materialized views except this materialized view

**Comment by den-crane** [comment]
This is expected behavior by design.

**Comment by IVitamin-C** [comment]
Thanks.
Can it be set by parameters？Because a ReplicatedMergeTree table may have hundreds of materialized views, but because a materialized view has no data due to mismatching of field types, other materialized views will be affected.

**Comment by IVitamin-C** [comment]
![image](https://user-images.githubusercontent.com/35019926/92546690-b6394480-f285-11ea-9154-55cac24c5d41.png)

**Comment by den-crane** [comment]
There is no such parameter. An insert breaks on any error.

**Comment by filimonov** [comment]
> may have hundreds of materialized views

Usually it's not the best idea - this way every insert fan-outs to hundred of inserts / hundred of new parts in derived tables. 
New parts need to be merged...

You can also take a look on `parallel_view_processing`, but as @den-crane said the insert will fail once any of MV failed (it's by design).
