### ISSUE TITLE
How not to make more requests per second while running multiple parallel INSERT queries

### ISSUE THREAD

**Issue by simPod** [ClickHouse/ClickHouse#14592]
[Documentation on insertion performance states](https://clickhouse.tech/docs/en/introduction/performance/#performance-when-inserting-data):
> We recommend inserting data in packets of at least 1000 rows, or no more than a single request per second

and

> To improve performance, you can make multiple INSERT queries in parallel, which scales linearly.

How can I make multiple INSERT queries in parallel to scale linearly while not making more than one per second?

**Comment by filimonov** [comment]
If 10 parallel insert will flush the data every 10 sec each the average QPS will be 1.

**Comment by simPod** [comment]
@filimonov so the point is that I can run huge inserts that take even several seconds and it's fine while I keep 1 QPS pace?

**Comment by filimonov** [comment]
Yes. 

Actually 1 QPS is not a 'hard rule'. Monitor the number of parts / merges during the inserts. If the number stays stable - you can push more insert / more data.

**Comment by simPod** [comment]
Thank you very much, appreciated
