### ISSUE TITLE
FR: Renaming Columns

### ISSUE THREAD

**Issue by fasterharder** [ClickHouse/ClickHouse#146]
Hello!
Thank you for the great DBMS!
It would be nice to have support of renaming columns. For example: 
`ALTER TABLE table_name 
    RENAME [ COLUMN ] column_name TO new_column_name;`
or 
`RENAME COLUMN table_name.column_name TO new_column_name;`
Now we have to create a new table, copy the data to it using the INSERT SELECT, rename table to the old name. It can takes a lot of time.

**Comment by alexey-milovidov** [comment]
We have this feature request from other customers too.

Implementation is not trivial, because ALTERs that changing columns are processed outside of usual replication queue, and adding rename without reworking of ALTERs will introduce race conditions in replicated tables.

**Comment by simPod** [comment]
This feature would be really nice! Does anyone use any workaround for this?

**Comment by fizerkhan** [comment]
+1 Do you have milestone for this feature?

**Comment by blinkov** [comment]
@fizerkhan unfortunately, there's no ETA at the moment.

**Comment by fizerkhan** [comment]
@blinkov Thanks for the update. Do you have any other method to do it?

**Comment by perez1987** [comment]
@blinkov Is it possible to rename fields between source-destination tables between tables using clickhouse-copier?

**Comment by geldot** [comment]
> We have this feature request from other customers too.
> 
> Implementation is not trivial, because ALTERs that changing columns are processed outside of usual replication queue, and adding rename without reworking of ALTERs will introduce race conditions in replicated tables.

Column rename on simple non-replicated tables would be very welcome for prototyping and single workstation data science workflows. Any pointers for how to implement this?

**Comment by alexey-milovidov** [comment]
Current status: this feature is not in progress and is queued after another feature: non-locking ALTERs.

**Comment by alesapin** [comment]
Working here https://github.com/ClickHouse/ClickHouse/pull/9948.
