### ISSUE TITLE
ALTER TABLE UPDATE  COL Nullable(Int32) - incorrect result

### ISSUE THREAD

**Issue by iCloudFly** [ClickHouse/ClickHouse#14606]
![image](https://user-images.githubusercontent.com/70839537/92551396-762b8f00-f290-11ea-8239-f6161819e510.png)

![image](https://user-images.githubusercontent.com/70839537/92551425-8d6a7c80-f290-11ea-8e5c-357152d28eb3.png)

更新一个表的两个列（一个是允许为null，一个是不允许为null）。
结果允许为null的列更新的值是正确的，
但是不允许为null的列更新的值永远是93147008
不知道这是为什么？是bug吗？还是我的配置不对？

UPD (machine translation): 

Update two columns of a table (one is allowed to be null, the other is not allowed to be null).
The result allows the updated value of the null column to be correct,
But the updated value of the column that is not allowed to be null is always 93147008
Don't know why this is? Is it a bug? Or is my configuration wrong?

**Comment by iCloudFly** [comment]
前面的结果说反了，重新发一次。


更新一个表的两个列（selectFlag是不允许为null，downloadFlag允许为null）。
结果不允许为null的列更新的值是正确的，
但是允许为null的列更新的值永远是93147008
不知道这是为什么？是bug吗？还是我的配置不对？

**Comment by filimonov** [comment]
What is your ClickHouse version?

Can you please put your CREATE TABLE statement, and other queries in text format as a comment, so we can try to reproduce that in a lab environment.

Screenshots with code/queries are useless. 

Machine translation below.

机器翻译：

您的ClickHouse版本是什么？

您能否以文本格式将CREATE TABLE语句和其他查询作为注释，以便我们可以尝试在实验室环境中重现该语句。

带有代码/查询的屏幕截图是没有用的。

**Comment by den-crane** [comment]
duplicate: https://github.com/ClickHouse/ClickHouse/issues/14227
https://github.com/ClickHouse/ClickHouse/issues/13634

**Comment by den-crane** [comment]
Fixed in https://github.com/ClickHouse/ClickHouse/pull/14646
