### ISSUE TITLE
dictGet gives error External dictionary not found

### ISSUE THREAD

**Issue by simPod** [ClickHouse/ClickHouse#14613]
Select from `system.dictionaries` shows my external odbc-sourced dictionary with status `LOADED`.

I can SELECT from that dictionary successfully.

However, running `dictGet()` on that dictionary says it was not found.

> Code: 36, e.displayText() = DB::Exception: external dictionary 'my_d' not found (version 20.6.3.28 (official build))

```sql
SELECT dictGet('my_d', 'name', tuple(toUUID('f724ff3c-3302-4abd-b403-b50a4d00e66a')));
```

```sql
CREATE DICTIONARY IF NOT EXISTS my_d ON CLUSTER '{cluster}' (
    id UUID,
    name String
)
PRIMARY KEY id
SOURCE(ODBC(connection_string 'DSN=pg_conn' TABLE 't1'))
LAYOUT(complex_key_hashed())
LIFETIME(MIN 1800 MAX 3600);
```

**Comment by alesapin** [comment]
You have to specify database in the first argument for dictionaries created with `DDL` queries. Probably in your case `default.my_d`?
