### ISSUE TITLE
Joining MySQL table and MergeTree table causes 'Missing columns'

### ISSUE THREAD

**Issue by asabirov** [ClickHouse/ClickHouse#14614]
**Describe the bug**
If you make a query to MySQL Engine Table with joined MergeTree Engine Table, you use any columns of the latter.

**How to reproduce**
* ClickHouse server 20.8.2
* ClickHouse client version 20.8.2.3 (official build).

```sql
CREATE TABLE mysql_table
(
    `id` UInt64,
    `name` Nullable(String),
)
ENGINE = MySQL('test:3306', 'test', 'test', 'test', 'test');
```

```sql
CREATE TABLE ch_table
(
    `id` UInt64,
    `mysql_item_id` UInt64,
    `d` DateTime
)
ENGINE = MergeTree()
PARTITION BY toYYYYMM(d)
ORDER BY d;
```

Query 
```sql
    SELECT *
    FROM mysql_table AS t_mysql_table
    LEFT JOIN ch_table AS t_ch_table 
         ON t_ch_table.mysql_item_id = t_mysql_table.id
    WHERE t_ch_table.id > 100
```

**Expected behavior**
Returns empty result without errors.

**Error message and/or stacktrace**
```
Code: 47. DB::Exception: Received from test:9000. DB::Exception: Missing columns: 't_ch_table.id' while processing query: 't_ch_table.id > 100', required columns: 't_ch_table.id', source columns: 'id', 'name'. 
```

**Comment by yusufozturk** [comment]
We have the same issue. Is this fixed in the newer versions? @4ertus2 

Thanks.

**Comment by 4ertus2** [comment]
> Is this fixed in the newer versions?

Probably not. I'm a bit out of context.

**Comment by yusufozturk** [comment]
@4ertus2 This is now working for us. But nobody changed anything or upgraded in our environment. I don't know what to do now. Should we trust this as "it's working" or we should continue to test it?

**Comment by asabirov** [comment]
I assume the issue occurs when the joined table has more than 1 entry. We started adding GROUP BY with aggregations and it works fine now.  I'm closing the issue. Thanks.
