### ISSUE TITLE
DB::Exception: Cannot read all data

### ISSUE THREAD

**Issue by muligolan** [ClickHouse/ClickHouse#14635]
I'm experiencing the following problem, I assume it is related to replication because the the 10.10.200.208 is the IP of another instance that stores another replica for this shard:
executeQuery: Code: 33, e.displayText() = DB::Exception: Cannot read all data. Bytes read: 93974. Bytes expected: 764646. (version 19.11.4.24) (from 10.10.200.208:29780) (in query: INSERT INTO {table_name}, Stack trace:

/usr/bin/clickhouse-server(StackTrace::StackTrace()+0x30) [0x6d0c010]
/usr/bin/clickhouse-server(DB::Exception::Exception(std::string const&, int)+0x1f) [0x30ee99f]
/usr/bin/clickhouse-server(DB::CompressedReadBufferBase::readCompressedData(unsigned long&, unsigned long&)+0x1706) [0x5b46aa6]
/usr/bin/clickhouse-server(DB::CompressedReadBuffer::nextImpl()+0x28) [0x5b425a8]
/usr/bin/clickhouse-server(DB::NativeBlockInputStream::readImpl()+0x1bbc) [0x5b6989c]
/usr/bin/clickhouse-server(DB::IBlockInputStream::read()+0x238) [0x5b5ce78]
/usr/bin/clickhouse-server(DB::TCPHandler::receiveData()+0x4f) [0x30f75ff]
/usr/bin/clickhouse-server(DB::TCPHandler::receivePacket()+0x85) [0x30f8685]
/usr/bin/clickhouse-server(DB::TCPHandler::readData(DB::Settings const&)+0x19b) [0x30f8b3b]
/usr/bin/clickhouse-server(DB::TCPHandler::processInsertQuery(DB::Settings const&)+0x20b) [0x30f902b]
/usr/bin/clickhouse-server(DB::TCPHandler::runImpl()+0x61c) [0x30f987c]
/usr/bin/clickhouse-server(DB::TCPHandler::run()+0x1c) [0x30fa9bc]
/usr/bin/clickhouse-server(Poco::Net::TCPServerConnection::start()+0xf) [0x68577df]
/usr/bin/clickhouse-server(Poco::Net::TCPServerDispatcher::run()+0x166) [0x6857ba6]
/usr/bin/clickhouse-server(Poco::PooledThread::run()+0x77) [0x6ee0c77]
/usr/bin/clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0x38) [0x6edce38]
/usr/bin/clickhouse-server() [0x74ae81f]
/lib64/libpthread.so.0(+0x7dd5) [0x7f6a61e2cdd5]
/lib64/libc.so.6(clone+0x6d) [0x7f6a61853ead]

**Comment by den-crane** [comment]
CH 19.11.4.24 is out of support.
Supported versions are  20.8, 20.7, 20.6(stable) ,  20.3(LTS).

Try to upgrade to supported version and check is it still relevant issue or not.

**Comment by filimonov** [comment]
One of the possible reason, 10.10.200.208 send data inserted in Distribured table, but the file it tries to send is damaged.

**Comment by den-crane** [comment]
No repro. Unclear is it relevant for the current stable.

**Comment by sliontc** [comment]
I got the same error when using MaterializeMySQL Engine. Any help?

**Comment by smhjamalii** [comment]
I got the same error when trying to send an Object. The Object is converted to byte array with ObjectOutputStream.
