### ISSUE TITLE
now64() documentation | now with miliseconds

### ISSUE THREAD

**Issue by valentinmk** [ClickHouse/ClickHouse#14634]
(you don't have to strictly follow this form)

**Describe the issue**
No documentation at all

**Additional context**
Got answer  at clickhouse_ru telegram chanel
`now64()` return `DateTime64(3)` type value of current time with miliseconds and equals to call of `now64(3)`

**Comment by Algunenano** [comment]
It's now documented: https://clickhouse.com/docs/en/sql-reference/functions/date-time-functions#now64
