### ISSUE TITLE
Debug assertion "Last column should be ColumnNullable"

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#14645]
`SELECT CAST(CAST(count('table with 2 blocks finaltable with 2 bl\0cks finaltable with 2 blocks finaltable with 2 blo\0ks final') * 256, 'Nullable(String)'), 'Enum8(\'Hello\' = 1)')`

**Comment by alexey-milovidov** [comment]
`SELECT CAST(toNullable('hello'), 'Enum8(\'Hello\' = 1)')`

**Comment by alexey-milovidov** [comment]
@azat @akuzm The bug was introduced here: https://github.com/ClickHouse/ClickHouse/pull/12745

**Comment by azat** [comment]
@alexey-milovidov it should been fixed in #14530

**Comment by alexey-milovidov** [comment]
@azat The query is reproducing debug assertion on master.

**Comment by alexey-milovidov** [comment]
It was merged 40 minues ago, I will check again after pull.

**Comment by azat** [comment]
>It was merged 40 minues ago, I will check again after pull.

FWIW I've already tested (just in case):

```sh
$ wget https://clickhouse-builds.s3.yandex.net/14530/4c3c1cdaf3e4064a5d65a40dea5383e522e8f2ee/clickhouse_build_check/gcc9_relwithdebuginfo_none_bundled_unsplitted_disable_False_binary/clickhouse
$ chmod +x clickhouse
$ ./clickhouse local -q "SELECT CAST(CAST(count('table with 2 blocks finaltable with 2 bl\0cks finaltable with 2 blocks finaltable with 2 blo\0ks final') * 256, 'Nullable(String)'), 'Enum8(\'Hello\' = 1)')"
Code: 36, e.displayText() = DB::Exception: Unknown element '256' for type Enum8('Hello' = 1) (version 20.9.1.4575)
```

**Comment by alexey-milovidov** [comment]
Yes, it's fixed.
