### ISSUE TITLE
fromUnixTimestamp64 functions expect Int64 and not UInt64

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#14648]
SELECT toYYYYMMDD(fromUnixTimestamp64Micro(1599672041963889))

Received exception from server (version 20.9.1):
Code: 43. DB::Exception: Received from localhost:9000. 
DB::Exception: Illegal type of argument #0 'value' of function fromUnixTimestamp64Micro, expected Int64, got UInt64.

**Comment by filimonov** [comment]
The workaround is trivial, and exception message is clean. 
```
SELECT toYYYYMMDD(fromUnixTimestamp64Micro(toInt64(1599672041963889)))

┌─toYYYYMMDD(fromUnixTimestamp64Micro(toInt64(1599672041963889)))─┐
│                                                        20200909 │
└─────────────────────────────────────────────────────────────────┘
```

Maybe it can be improved, but overflows can appear...

```
SELECT 
    15996720419638890000 AS x,
    toUInt64(x),
    toInt64(x)

Row 1:
──────
x:                              15996720419638890000
toUInt64(15996720419638890000): 15996720419638890000
toInt64(15996720419638890000):  -2450023654070661616
```

/cc @Enmk

**Comment by Enmk** [comment]
@den-crane what would you expect for values outside of `Int64`-range? if silent implicit overflow (resulting in a negative value) is Ok, then it is trivial to fix.

**Comment by den-crane** [comment]
I've expected silent implicit overflow.

**Comment by Enmk** [comment]
Noted, will do

**Comment by UsedC** [comment]
We've also encountered this exception with fromUnixTimestamp64Milli. The number was quite smaller, as you can expect with milliseconds, and it took us some time before we figured out what's going on.

This behavior was somewhat unexpected, and we weren't even sure if it was a bug or not until stumbling upon this issue
