### ISSUE TITLE
segfault on insert to Engine=Log table

### ISSUE THREAD

**Issue by inkrement** [ClickHouse/ClickHouse#1467]
I tried to append some data to an existing table, but I get the following failure (+ clickhouse-server dies):

> 2017.11.08 15:29:48.600076 [ 31 ] <Error> BaseDaemon: ########################################
> 2017.11.08 15:29:48.600153 [ 31 ] <Error> BaseDaemon: (from thread 28) Received signal Segmentation fault (11).
> 2017.11.08 15:29:48.600182 [ 31 ] <Error> BaseDaemon: Address: 0xf8
> 2017.11.08 15:29:48.654616 [ 31 ] <Error> BaseDaemon: 0. clickhouse-server(DB::LogBlockOutputStream::writeData(std::string const&, DB::IDataType const&, DB::IColumn const&, std::vector<std::pair<unsigned long, DB::Mark>, std::allocator<std::pair<unsigned long, DB::Mark> > >&, std::vector<std::pair<unsigned long, DB::Mark>, std::allocator<std::pair<unsigned long, DB::Mark> > >&, std::set<std::string, std::less<std::string>, std::allocator<std::string> >&, unsigned long)+0x505) [0x336e115]
> 2017.11.08 15:29:48.654642 [ 31 ] <Error> BaseDaemon: 1. clickhouse-server(DB::LogBlockOutputStream::write(DB::Block const&)+0x120) [0x336e990]
> 2017.11.08 15:29:48.654661 [ 31 ] <Error> BaseDaemon: 2. clickhouse-server(DB::PushingToViewsBlockOutputStream::write(DB::Block const&)+0x401) [0x31eaa71]
> 2017.11.08 15:29:48.654681 [ 31 ] <Error> BaseDaemon: 3. clickhouse-server(DB::copyData(DB::IBlockInputStream&, DB::IBlockOutputStream&, std::atomic<bool>*)+0x91) [0x35de811]
> 2017.11.08 15:29:48.654699 [ 31 ] <Error> BaseDaemon: 4. clickhouse-server(DB::PushingToViewsBlockOutputStream::write(DB::Block const&)+0x3ad) [0x31eaa1d]
> 2017.11.08 15:29:48.654716 [ 31 ] <Error> BaseDaemon: 5. clickhouse-server(DB::MaterializingBlockOutputStream::write(DB::Block const&)+0x28) [0x31e8268]
> 2017.11.08 15:29:48.654732 [ 31 ] <Error> BaseDaemon: 6. clickhouse-server(DB::AddingDefaultBlockOutputStream::write(DB::Block const&)+0x235) [0x3507cb5]
> 2017.11.08 15:29:48.654749 [ 31 ] <Error> BaseDaemon: 7. clickhouse-server(DB::ProhibitColumnsBlockOutputStream::write(DB::Block const&)+0x4f) [0x35a894f]
> 2017.11.08 15:29:48.654765 [ 31 ] <Error> BaseDaemon: 8. clickhouse-server(DB::SquashingBlockOutputStream::write(DB::Block const&)+0x391) [0x35b08f1]
> 2017.11.08 15:29:48.654781 [ 31 ] <Error> BaseDaemon: 9. clickhouse-server(DB::CountingBlockOutputStream::write(DB::Block const&)+0x1c) [0x352f20c]
> 2017.11.08 15:29:48.654798 [ 31 ] <Error> BaseDaemon: 10. clickhouse-server(DB::TCPHandler::receiveData()+0x7f) [0x13dbf4f]
> 2017.11.08 15:29:48.654814 [ 31 ] <Error> BaseDaemon: 11. clickhouse-server(DB::TCPHandler::receivePacket()+0x1b5) [0x13dc5e5]
> 2017.11.08 15:29:48.654830 [ 31 ] <Error> BaseDaemon: 12. clickhouse-server(DB::TCPHandler::readData(DB::Settings const&)+0x142) [0x13dc952]
> 2017.11.08 15:29:48.654847 [ 31 ] <Error> BaseDaemon: 13. clickhouse-server(DB::TCPHandler::processInsertQuery(DB::Settings const&)+0x241) [0x13dd611]
> 2017.11.08 15:29:48.654871 [ 31 ] <Error> BaseDaemon: 14. clickhouse-server(DB::TCPHandler::runImpl()+0x647) [0x13dddb7]
> 2017.11.08 15:29:48.654887 [ 31 ] <Error> BaseDaemon: 15. clickhouse-server(DB::TCPHandler::run()+0x1c) [0x13de93c]
> 2017.11.08 15:29:48.654903 [ 31 ] <Error> BaseDaemon: 16. clickhouse-server(Poco::Net::TCPServerConnection::start()+0xf) [0x3b1313f]
> 2017.11.08 15:29:48.654918 [ 31 ] <Error> BaseDaemon: 17. clickhouse-server(Poco::Net::TCPServerDispatcher::run()+0x10b) [0x3b1494b]
> 2017.11.08 15:29:48.654932 [ 31 ] <Error> BaseDaemon: 18. clickhouse-server(Poco::PooledThread::run()+0x87) [0x3c1ad17]
> 2017.11.08 15:29:48.654947 [ 31 ] <Error> BaseDaemon: 19. clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0x96) [0x3c158a6]
> 2017.11.08 15:29:48.654977 [ 31 ] <Error> BaseDaemon: 20. /lib64/libpthread.so.0(+0x7e25) [0x7f7de62cee25]

I am using the newest release (v1.1.54304) and this error is reproducible (but I am not allowed to provide the dataset).

**Comment by valyala** [comment]
@inkrement , try minimizing and then mangling the dataset, so the error is still reproducible. Then post reproducible case here. This should increase chances for fixing the issue.

**Comment by inkrement** [comment]
The data is somehow public, it's from a Kaggle competition. But I am not sure if I am allowed to upload it here. Anyway, you can download the files on kaggle: https://www.kaggle.com/c/kkbox-churn-prediction-challenge/data. The first data set was user_logs.csv.7z and then I tried to add user_logs_v2.csv.7z to the same table. The schema looks like this: 

```
CREATE TABLE user_logs (
	msno FixedString(44),
  date_raw String,
	date Date DEFAULT toDate(concat(concat(concat(substring(date_raw, 1,4),'-') , concat(substring(date_raw, 5, 2), '-')),substring(date_raw, 7, 2))),
	num_25 UInt16,
	num_50 UInt16,
	num_75 UInt16,
	num_985 UInt16,
	num_100 UInt16,
	num_unq UInt16,
	total_secs Float64
)  ENGINE=MergeTree(date, (msno, date), 8192)

```

**Comment by filimonov** [comment]
> ```
> )  ENGINE=MergeTree(date, (msno, date), 8192)
> ```

Looks like it was Engine=Log table (according to stacktrace)

**Comment by alexey-milovidov** [comment]
Steps:

1. Download the data from Kaggle.
2. `unzip kkbox-churn-prediction-challenge.zip`
3. 
```
CREATE TABLE user_logs
(
    `msno` FixedString(44), 
    `date_raw` String, 
    `date` Date DEFAULT toDate(concat(concat(concat(substring(date_raw, 1, 4), '-'), concat(substring(date_raw, 5, 2), '-')), substring(date_raw, 7, 2))), 
    `num_25` UInt16, 
    `num_50` UInt16, 
    `num_75` UInt16, 
    `num_985` UInt16, 
    `num_100` UInt16, 
    `num_unq` UInt16, 
    `total_secs` Float64
)
ENGINE = Log
```
4. `7z x -so user_logs.csv.7z | clickhouse-client --query "INSERT INTO user_logs (msno, date_raw, num_25, num_50, num_75, num_985, num_100, num_unq, total_secs) FORMAT CSVWithNames"`
5. `7z x -so user_logs_v2.csv.7z | clickhouse-client --query "INSERT INTO user_logs (msno, date_raw, num_25, num_50, num_75, num_985, num_100, num_unq, total_secs) FORMAT CSVWithNames"`

**Comment by alexey-milovidov** [comment]
Everything is Ok.
The issue was fixed long time ago.
