### ISSUE TITLE
(unreleased) debug assertion in some arithmetic operations on UInt256

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#14677]
`SELECT bitShiftLeft(toInt256(-2), number)`

`shift left for negative lhsbers is underfined!`

See https://clickhouse-test-reports.s3.yandex.net/14525/44726c37c3003ec8112dbf32efa350bd595163b3/fuzzer/report.html#fail1

**Comment by 4ertus2** [comment]
It's more then debug assert. There's `operator << (...) nothrow` that calls `shiftLeft()` that is not a nothrow func.
