### ISSUE TITLE
How does the HDFS engine use kerberos authentication?

### ISSUE THREAD

**Issue by gubinjie** [ClickHouse/ClickHouse#14676]
Recently, our HADOOP cluster has added kerberos authentication. When using the hdfs engine, when reading hdfs data, an exception will be thrown:
SIMPLE authentication is not enabled.Available:[TOKEN,KERBEROS],
Is there any good solution?

**Comment by filimonov** [comment]
https://github.com/ClickHouse/ClickHouse/issues/5747

**Comment by filimonov** [comment]
Duplicate of #5747

https://github.com/ClickHouse/ClickHouse/blob/7edb911e9179563aa4b8b8e7127fd9b605e70a16/contrib/libhdfs3-cmake/CMakeLists.txt#L20
