### ISSUE TITLE
Protobuf Schema mutations

### ISSUE THREAD

**Issue by yonesko** [ClickHouse/ClickHouse#14686]
Hello

In order to use Protobug schema, I have to put it in `var/lib/clickhouse/format_schemas`.
Should I restart CH if I change this schema, for example adding a field?

**Comment by filimonov** [comment]
Restart is not needed, it rereads the schema every time.

**Comment by yonesko** [comment]
Every time when what? 

I have Kafka engine that consumes protobuf topic and mat view on it.

To my experience I had to restart to reread the schema

**Comment by alexey-milovidov** [comment]
Yes, for Kafka table, DETACH TABLE / ATTACH TABLE is required to reread format schema.
