### ISSUE TITLE
How to delete records/drop partition synchronously from a Materialized view when deleting or dropping operation hanppens on source table?

### ISSUE THREAD

**Issue by BernieJiangDL** [ClickHouse/ClickHouse#14688]
As title mentioned, is there a method to delete records/drop partition synchronously from a Materialized view when deleting or dropping operation hanppens on source table?

Or Any suggestions?

**Comment by den-crane** [comment]
No. 
No transactions.
And the source table has no relation to the Materialized view. Materialized view watches INSERTS.

**Comment by BernieJiangDL** [comment]
> No.
> No transactions.
> And the source table has no relation to the Materialized view. Materialized view watches INSERTS.

When some unexpected results occur(from bussiness side, it might be some wrong/dirty records from upstream) after inserting. Rerunning the task is easiest way and then dropping a relative partition before reinsert to guarantee data is not duplicate.

But at this point, how can we deal with the materialized view on this source table? If we do nothing, the data in materialized view will be double.

Any suggestions for this? many thanks~

**Comment by den-crane** [comment]
There are many approaches. 
You can design partitions in MV the same way as a source table. Drop partitions in the source table and MV.
You can insert into MV the same data with negative sign to cancel rows in MV and drop partition in the source table.
You can truncate MV and re-calculate it (manually) after inserting into the source table.
