### ISSUE TITLE
Add support for secondary index

### ISSUE THREAD

**Issue by itzikiusa** [ClickHouse/ClickHouse#14694]
**Use case**
I have a table which i need to query by 3 different column, which are not dependent on each other.
when querying by the leading index, performance is less then 100 ms,
when query by one of the secondary indexes response takes more then 3 seconds

**Describe the solution you'd like**
A way to add additional index to the table, which will allow us to query by another fields as well as the primary key

**Describe alternatives you've considered**
Use skipping indexes - improved performance in about 5 percent, still not ideal
replicated the table 3 times - use 3 different tables(with same data), only different primary keys - query is returned in under 100 ms, however data size has increased from 50GB to around 200GB

**Additional context**
this is my main table, any suggestions on how to improve it will be helpful

```CREATE TABLE example.transactions
(
  event_time DateTime,
  frb Boolean,
  is_test_account Boolean,
  transaction_key String,
  country LowCardinality(String),
  type LowCardinality(String),
  language LowCardinality(String),
  platform LowCardinality(String),
  currency LowCardinality(String),
  game_id String,
  casino_session_id String,
  round_id String,
  trans_id String,
  account_id String,
  casino_id Int32,
  provider_id Int32,
  amount Float64,
  bonus_money Float64,
  real_money Float64,
  ggr Float64,
  ggr_eur Float64,
  ngr Float64,
  ngr_eur Float64,
  amount_eur Float64,
  bonus_money_eur Float64

)
ENGINE = MergeTree()
PARTITION BY toYYYYMM(event_time)
ORDER BY (transaction_key, round_id,  event_time, trans_id, game_id, casino_id, type)
SETTINGS index_granularity = 8192`

**Comment by amosbird** [comment]
Should be covered by https://github.com/ClickHouse/ClickHouse/issues/14730

**Comment by itzikiusa** [comment]
@amosbird 
sounds interesting, didn't understand the concept that well though.
in general it will allow to display only specific columns with different primary key?
also, the projection should be on table level(like order by/TTL/partition)?

**Comment by amosbird** [comment]
> in general it will allow to display only specific columns with different primary key?

yes

> also, the projection should be on table level(like order by/TTL/partition)?

yes, actually at part level
