### ISSUE TITLE
Is the REPLACE PARTITION operation automatically replicated?

### ISSUE THREAD

**Issue by alvarotuso** [ClickHouse/ClickHouse#14701]
**Describe the issue**
The documentation on https://clickhouse.tech/docs/en/sql-reference/statements/alter/partition/#alter_replace-partition doesn't provide info in 1 way or the other

**Additional context**
I assume it is replicated but for new users it'd be good to add some notes regarding it

**Comment by amosbird** [comment]
It's replicated. Documentation will highlight operations that are not replicated, so that makes it somehow partial-intuitive.

**Comment by den-crane** [comment]
And it means that all replicas need a source table. And they will attach the partition without fetching.

**Comment by alvarotuso** [comment]
@amosbird it also specifies some that are replicated but not others, that's what made me wary of making that assumption initially

Thanks for the response!

**Comment by amosbird** [comment]
> it also specifies some that are replicated but not others, that's what made me wary of making that assumption initially

Indeed. I think it's reasonable.
