### ISSUE TITLE
Точечное редактирование

### ISSUE THREAD

**Issue by glader** [ClickHouse/ClickHouse#14732]
Есть большая таблица (сотни миллионов записей). Там даты и значения. Таблица партиционирована по месяцам. В интерфейсе таблица выводится как в исходном виде, так и агрегированная (суммарный график по датам, пользовательские группировки по столбцам). Все отлично работает, и выборки, и агрегации.

Проблема в том, что в эту таблицу время от времени надо вносить точечные изменения (несколько тысяч в день). Сейчас эти изменения сохраняются в postgres и раз в сутки пересчитываются на большой таблице. Это очень медленно. Хочется видеть изменения почти сразу (минуты).

Я рассматривал варианты:
- `alter table update`. Не подошел, потому что время исполнения не гарантировано. Я бы согласился, если бы это было "точно в течение часа". А так - ненадежно.
- https://clickhouse.tech/blog/en/2016/how-to-update-data-in-clickhouse/#incremental-log . Работает на агрегациях, но непонятно, как выводить исходные данные.
- CollapsingMergeTree с OPTIMIZE. Работает неплохо, но очень медленно (из-за больших партиций).

Можно ли решить эту задачу в CH? Что посоветуете?

**Comment by alexey-milovidov** [comment]
Есть ещё несколько плохих способов. Например, можно писать обновления в отдельную маленькую таблицу (их мало - десятки тысяч в день, просто дописывать в конец, или использовать ReplacingMergeTree с OPTIMIZE). Далее подключить эту таблицу как [словарь](https://clickhouse.tech/docs/en/sql-reference/statements/create/dictionary/), чтобы доставать обновления налету.

**Comment by glader** [comment]
> Есть ещё несколько плохих способов.
Хороших, я так понимаю, нету? :)

**Comment by alexey-milovidov** [comment]
Да.

**Comment by glader** [comment]
Меня устроят варианты среднего качества. Какой из них наименее плохой?

**Comment by glader** [comment]
> Далее подключить эту таблицу как [словарь](https://clickhouse.tech/docs/en/sql-reference/statements/create/dictionary/), чтобы доставать обновления налету.
Ты имел в виду джойнить большую таблицу со словарем? Насколько я помню, клик не очень хорошо джойнит.

**Comment by alexey-milovidov** [comment]
ClickHouse очень хорошо JOIN-ит, лучше чем кто-либо ещё - если использовать словарь.
