### ISSUE TITLE
Projection (RFC) 

### ISSUE THREAD

**Issue by amosbird** [ClickHouse/ClickHouse#14730]
Projections are like materialized views, but defined in part-level. It provides consistency guarantees along with automatic usage in queries. This RFC proposes a way to implement projections in ClickHouse.

### Projection Grammars:

1. 
```
CREATE TABLE [IF NOT EXISTS] [db.]table_name [ON CLUSTER cluster]
(
       name1 [type1] [DEFAULT|MATERIALIZED|ALIAS expr1] [compression_codec] [TTL expr1],
       ...
       PROJECTION projection_name_1 (SELECT <COLUMN LIST EXPR> [WHERE] [GROUP BY] [ORDER BY]),
       ...
) ENGINE = engine ...
```

2. `ALTER TABLE [db.]table ADD PROJECTION name AS SELECT <COLUMN LIST EXPR> [WHERE] [GROUP BY] [ORDER BY];`

3. `ALTER TABLE [db.]table DROP PROJECTION name;`

4. `ALTER TABLE [db.]table MATERIALIZE PROJECTION name IN PARTITION partition_name;`

5. `ALTER TABLE [db.]table CLEAR PROJECTION name IN PARTITION partition_name;`

### Projection Query:

A projection query is what defines a projection. It has the following grammar: `SELECT <COLUMN LIST EXPR> [WHERE] [GROUP BY] [ORDER BY]`. It implicitly selects data from the parent table. Aliases might be disabled first for simplicity.

### Projection Storage:

Projections are stored inside the part directory. It's similar to an index but contains an subdirectory which stores an anonymous MergeTree table's part. The table is induced by the definition query of the projection. If there is a `GROUP BY` clause, the underlying storage engine becomes AggregatedMergeTree, and all aggregate functions are converted to either AggregateFunction or SimpleAggregateFunction. If there is an `ORDER BY` clause, the MergeTree table will use it as its primary key expression. During the merge process, the projection part will be merged via its storage's merge routine. The checksum of the parent table's part will combine the projection's part. Other maintenance jobs are similar to skip indices.

### Replication

Metadata in ZooKeeper might be updated to replicate the newly added DDL actions. `GET_PART` will be extended to send and receive projection subdirectories.

### Query Routing Process:

1. Check if the projection contains all the needed columns and rows.

2. If it's an aggregated projection, also check if it has the right columns inside the `GROUP BY` clause along with required aggregate functions.

3. If it's an sorted projection, also check how many granules will be selected by the KeyCondition.

4. Select the best feasible match.

5. The query pipeline which uses projections will be different from the one that uses the original parts. if the projection is absent in some parts, we can add the pipeline to "project" it on the fly.

### Projection Analysis and Settings:

1. EXPLAIN PROJECTION should show which projection is selected, perhaps we can also add other information

2. Introduce some settings to disable creation of expensive or meaningless projections.

3. Record the resource consumption when inserting and merging projections.

### Questions:

1. Is it possible to have old instances running when doing a grayscale upgrade?

2. Shall we have different projections on different replicas (heterogenous)? If so, what information should be stored in ZooKeeper?

3. What qualifies the best feasible projection match? Is it possible to select multiple different projections in one query?

4. Last but not least. Is "Projection" a good name for this feature?

**Comment by alexey-milovidov** [comment]
> Is it possible to have old instances running when doing a grayscale upgrade?

No, but it is Ok.

First upgrade cluster to the minimum version that supports projections. Then wait until the chance that downgrade may be needed will be low. Then start using the new feature. The same as we had for almost all new features like adaptive granularity, compact parts...

> Shall we have different projections on different replicas (heterogenous)? If so, what information should be stored in ZooKeeper?

It's very tempting but better to postpone and not to do it in first implementation.
The reason is that these replicas will be "not quite replicas" and it complicates everything.

> What qualifies the best feasible projection match? Is it possible to select multiple different projections in one query?

Estimate on data size to read extracted from the index is Ok. We can select single best projection, it will be enough for simplicity and
> if the projection is absent in some parts, we can add the pipeline to "project" it on the fly.

> Last but not least. Is "Projection" a good name for this feature?

Yes (although it mostly familiar for Vertica users). I don't know better name.
I also name it "different physical representations of the same data" but it isn't a name.

**Comment by den-crane** [comment]
AFAIK such table cannot be mutated ? Alter update/delete breaks consistency.
Vertica has two types Projections and LiveAggregatingProjections. Projections are updateable because they have the same not aggregated rows.

**Comment by den-crane** [comment]
Though, I am wrong, these projections can be mutated because they are at a parts level, so they can be re-calculated completely for a new part during mutations / merges.

**Comment by alexey-milovidov** [comment]
@den-crane I'm Ok with all of possible options:
- forbid mutations explicitly;
- allow mutations of main data that will lead to inconsistencies;
- allow mutations of main data and the data that contains columns to evaluate the expression (e.g. we can mutate aggregated data if we delete by key);
- recalculate (this is more difficult to implement as we need to recalculate whole part that can be large - multi-step process with temporary data on disk is required - still not hard to implement but better to avoid).

**Comment by alexey-milovidov** [comment]
This feature is implemented and scheduled for release 21.6 in June.

**Comment by amosbird** [comment]
@zhouxuhua 可以列一下局限性，有好的方向我想办法优化优化

**Comment by variantf** [comment]
> @zhouxuhua 可以列一下局限性，有好的方向我想办法优化优化

我每次添加数据，都需要手工 materilize吗？

**Comment by tangxueming** [comment]
@amosbird
ALTER TABLE [db.]table ADD PROJECTION name AS SELECT <COLUMN LIST EXPR> [WHERE] [GROUP BY] [ORDER BY];

When I use "where"  in  projection , throw exception : Expected one of: DoubleColon, LIKE, GLOBAL NOT IN, AS, DIV, IS, UUID, GROUP BY, OR, identifier, QuestionMark, BETWEEN, NOT LIKE, MOD, AND, ClosingRoundBracket, Comma, alias, ORDER BY, IN, ILIKE, Dot, NOT ILIKE, NOT, Arrow, token, NOT IN, GLOBAL IN

Does [where] still work  in 21.9?
Thanks!
