### ISSUE TITLE
MaterializeMySQL don't support the json,bit,time data type.

### ISSUE THREAD

**Issue by DBA-Ray** [ClickHouse/ClickHouse#14735]
(you don't have to strictly follow this form)

clickhouse version: 20.8.2.3 (official build)
os : CentOS Linux release 7.6.1810 (Core)

**Describe the issue**
If the json data type or the bit data type exists in mysql tables,then execute this statement "CREATE DATABASE xxx ENGINE = MaterializeMySQL(xxx);" for initialing database in clickhouse,it will cause the following erros and it don't dump the mysql datas.

* Queries to run that lead to unexpected result
"CREATE DATABASE xxx ENGINE = MaterializeMySQL(xxx);"

**Error message and/or stacktrace**
[ 2563 ] {} <Error> MaterializeMySQLSyncThread: Code: 50, e.displayText() = DB::Exception: Unknown data type family: json, Stack trace (when copying this message, always include the lines below):

[ 9910 ] {} <Error> MaterializeMySQLSyncThread: Code: 50, e.displayText() = DB::Exception: Unknown data type family: bit, Stack trace (when copying this message, always include the lines below):

**Additional context**
2020.09.11 16:05:24.828416 [ 25946 ] {} <Error> MaterializeMySQLSyncThread: Code: 50, e.displayText() = DB::Exception: Unknown data type family: json, Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x1a80ae30 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xff9e75d in /usr/bin/clickhouse
2. ? @ 0x17081cc6 in /usr/bin/clickhouse
3. DB::DataTypeFactory::get(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::IAST> const&) const @ 0x170809d3 in /usr/bin/clickhouse
4. DB::DataTypeFactory::get(std::__1::shared_ptr<DB::IAST> const&) const @ 0x17081015 in /usr/bin/clickhouse
5. ? @ 0x170f3367 in /usr/bin/clickhouse
6. std::__1::__function::__func<std::__1::shared_ptr<DB::IDataType const> (*)(std::__1::shared_ptr<DB::IAST> const&), std::__1::allocator<std::__1::shared_ptr<DB::IDataType const> (*)(std::__1::shared_ptr<DB::IAST> const&)>, std::__1::shared_ptr<DB::IDataType const> (std::__1::shared_ptr<DB::IAST> const&)>::operator()(std::__1::shared_ptr<DB::IAST> const&) @ 0x17054787 in /usr/bin/clickhouse
7. DB::DataTypeFactory::get(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::IAST> const&) const @ 0x170809ec in /usr/bin/clickhouse
8. DB::DataTypeFactory::get(std::__1::shared_ptr<DB::IAST> const&) const @ 0x17081015 in /usr/bin/clickhouse
9. ? @ 0x177f840d in /usr/bin/clickhouse
10. DB::MySQLInterpreter::InterpreterCreateImpl::getRewrittenQueries(DB::MySQLParser::ASTCreateQuery const&, DB::Context const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x177fc695 in /usr/bin/clickhouse
11. DB::InterpreterExternalDDLQuery::execute() @ 0x17441752 in /usr/bin/clickhouse
12. ? @ 0x177d50d2 in /usr/bin/clickhouse
13. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool) @ 0x177d6a32 in /usr/bin/clickhouse
14. ? @ 0x17398724 in /usr/bin/clickhouse
15. ? @ 0x173a2945 in /usr/bin/clickhouse
16. ? @ 0x173a4073 in /usr/bin/clickhouse
17. DB::commitMetadata(std::__1::function<void ()> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x173e0269 in /usr/bin/clickhouse
18. DB::MaterializeMetadata::transaction(DB::MySQLReplication::Position const&, std::__1::function<void ()> const&) @ 0x173e269e in /usr/bin/clickhouse
19. DB::MaterializeMySQLSyncThread::prepareSynchronized(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x1739c2a1 in /usr/bin/clickhouse
20. DB::MaterializeMySQLSyncThread::synchronization(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x173a0f9b in /usr/bin/clickhouse
21. ? @ 0x173a14b6 in /usr/bin/clickhouse
22. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xffce517 in /usr/bin/clickhouse
23. ? @ 0xffccb53 in /usr/bin/clickhouse
24. start_thread @ 0x7e65 in /usr/lib64/libpthread-2.17.so
25. clone @ 0xfe88d in /usr/lib64/libc-2.17.so
 (version 20.8.2.3 (official build))

2020.09.09 14:59:30.321159 [ 9822 ] {00d2d004-06c5-4c47-89b8-166c3bf82b95} <Error> executeQuery: Code: 50, e.displayText() = DB::Exception: Unknown data type family: bit (version 20.8.2.3 (official build)) (from [::1]:43448) (in query: select * from xxxx;), Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x1a80ae30 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xff9e75d in /usr/bin/clickhouse
2. ? @ 0x17081cc6 in /usr/bin/clickhouse
3. DB::DataTypeFactory::get(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::IAST> const&) const @ 0x170809d3 in /usr/bin/clickhouse
4. DB::DataTypeFactory::get(std::__1::shared_ptr<DB::IAST> const&) const @ 0x17081015 in /usr/bin/clickhouse
5. ? @ 0x177f840d in /usr/bin/clickhouse
6. DB::MySQLInterpreter::InterpreterCreateImpl::getRewrittenQueries(DB::MySQLParser::ASTCreateQuery const&, DB::Context const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x177fc695 in /usr/bin/clickhouse
7. DB::InterpreterExternalDDLQuery::execute() @ 0x17441752 in /usr/bin/clickhouse
8. ? @ 0x177d50d2 in /usr/bin/clickhouse
9. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool) @ 0x177d6a32 in /usr/bin/clickhouse
10. ? @ 0x17398724 in /usr/bin/clickhouse
11. ? @ 0x173a2945 in /usr/bin/clickhouse
12. ? @ 0x173a4073 in /usr/bin/clickhouse
13. DB::commitMetadata(std::__1::function<void ()> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x173e0269 in /usr/bin/clickhouse
14. DB::MaterializeMetadata::transaction(DB::MySQLReplication::Position const&, std::__1::function<void ()> const&) @ 0x173e269e in /usr/bin/clickhouse
15. DB::MaterializeMySQLSyncThread::prepareSynchronized(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x1739c2a1 in /usr/bin/clickhouse
16. DB::MaterializeMySQLSyncThread::synchronization(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x173a0f9b in /usr/bin/clickhouse
17. ? @ 0x173a14b6 in /usr/bin/clickhouse
18. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xffce517 in /usr/bin/clickhouse
19. ? @ 0xffccb53 in /usr/bin/clickhouse
20. start_thread @ 0x7e65 in /usr/lib64/libpthread-2.17.so
21. clone @ 0xfe88d in /usr/lib64/libc-2.17.so

**Comment by DBA-Ray** [comment]
2020.09.17 14:08:35.041259 [ 29778 ] {} <Error> MaterializeMySQLSyncThread: Code: 50, e.displayText() = DB::Exception: Unsupported type Decimal(16, 2), Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x1a80ae30 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xff9e75d in /usr/bin/clickhouse
2. ? @ 0x16f21f47 in /usr/bin/clickhouse
3. DB::MySQLBlockInputStream::MySQLBlockInputStream(mysqlxx::Pool::Entry const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Block const&, unsigned long, bool) @ 0x17eb0d68 in /usr/bin/clickhouse
4. ? @ 0x173a2baa in /usr/bin/clickhouse
5. ? @ 0x173a4073 in /usr/bin/clickhouse
6. DB::commitMetadata(std::__1::function<void ()> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x173e0269 in /usr/bin/clickhouse
7. DB::MaterializeMetadata::transaction(DB::MySQLReplication::Position const&, std::__1::function<void ()> const&) @ 0x173e269e in /usr/bin/clickhouse
8. DB::MaterializeMySQLSyncThread::prepareSynchronized(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x1739c2a1 in /usr/bin/clickhouse
9. DB::MaterializeMySQLSyncThread::synchronization(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x173a0f9b in /usr/bin/clickhouse
10. ? @ 0x173a14b6 in /usr/bin/clickhouse
11. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xffce517 in /usr/bin/clickhouse
12. ? @ 0xffccb53 in /usr/bin/clickhouse
13. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
14. __clone @ 0xfe8dd in /usr/lib64/libc-2.17.so
 (version 20.8.2.3 (official build))

**Comment by zhang2014** [comment]
decimal data type is implemented in https://github.com/ClickHouse/ClickHouse/pull/14535(no merge)
bit and json data type no plan at the moment.

**Comment by BohuTANG** [comment]
Update:
decimal data type patch has been merged to master, you can download and experience it here:
https://clickhouse-builds.s3.yandex.net/0/3e0509af691d715747c8f6e6eb8e0f3e30942fbf/clickhouse_build_check/report.html

**Comment by DBA-Ray** [comment]
Thanks a lot.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: BohuTANG<mailto:notifications@github.com>
发送时间: 2020年9月21日 9:09
收件人: ClickHouse/ClickHouse<mailto:ClickHouse@noreply.github.com>
抄送: Ray<mailto:rulei0501@hotmail.com>; Author<mailto:author@noreply.github.com>
主题: Re: [ClickHouse/ClickHouse] MaterializeMySQL don't support the json,bit,decimal data type. (#14735)


Update:
decimal data type patch has been merged to master, you can download and experience it here:
https://clickhouse-builds.s3.yandex.net/0/3e0509af691d715747c8f6e6eb8e0f3e30942fbf/clickhouse_build_check/report.html

―

**Comment by DBA-Ray** [comment]
Hello! I tested the version 20.10.1.4709 (official build),and i found the time data type is not supported.

2020.09.21 10:57:16.373628 [ 19505 ] {} <Error> MaterializeMySQLSyncThread: Code: 50, e.displayText() = DB::Exception: Unknown data type family: time, Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x114ffed0 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x8367afd in /usr/bin/clickhouse
2. ? @ 0xdfa9479 in /usr/bin/clickhouse
3. DB::DataTypeFactory::get(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::IAST> const&) const @ 0xdfa817b in /usr/bin/clickhouse
4. DB::DataTypeFactory::get(std::__1::shared_ptr<DB::IAST> const&) const @ 0xdfa87fb in /usr/bin/clickhouse
5. ? @ 0xe706cad in /usr/bin/clickhouse
6. DB::MySQLInterpreter::InterpreterCreateImpl::getRewrittenQueries(DB::MySQLParser::ASTCreateQuery const&, DB::Context const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xe70afcb in /usr/bin/clickhouse
7. DB::InterpreterExternalDDLQuery::execute() @ 0xe33e0f5 in /usr/bin/clickhouse
8. ? @ 0xe6e483c in /usr/bin/clickhouse
9. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool) @ 0xe6e6721 in /usr/bin/clickhouse
10. ? @ 0xe299ed4 in /usr/bin/clickhouse
11. ? @ 0xe2a53d3 in /usr/bin/clickhouse
12. ? @ 0xe2a6ae3 in /usr/bin/clickhouse
13. DB::commitMetadata(std::__1::function<void ()> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xe2dec99 in /usr/bin/clickhouse
14. DB::MaterializeMetadata::transaction(DB::MySQLReplication::Position const&, std::__1::function<void ()> const&) @ 0xe2e10ae in /usr/bin/clickhouse
15. DB::MaterializeMySQLSyncThread::prepareSynchronized(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xe29b5e2 in /usr/bin/clickhouse
16. DB::MaterializeMySQLSyncThread::synchronization(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xe2a39eb in /usr/bin/clickhouse
17. ? @ 0xe2a3f36 in /usr/bin/clickhouse
18. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x8395fcf in /usr/bin/clickhouse
19. ? @ 0x83948f3 in /usr/bin/clickhouse
20. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
21. __clone @ 0xfe8dd in /usr/lib64/libc-2.17.so
 (version 20.10.1.4709 (official build))

**Comment by zhang2014** [comment]
Time date type is unsupported.

**Comment by DBA-Ray** [comment]
Is the time data type not included in the plan?

**Comment by itwangxinli** [comment]
the bit type dosen't support

DROP TABLE IF EXISTS `business_pair`;
`CREATE TABLE `business_pair` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `channel_code` varchar(64) NOT NULL,
  `supplier_code` varchar(64) NOT NULL,
  `create_time` datetime NOT NULL,
  `source` varchar(32) NOT NULL,
  `enabled` bit(1) DEFAULT b'0',
  `team` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;`
Clickhouse 20.10.1.4881 MaterializeMySQL can't  synchonize the table business_pair.

**Comment by zhang2014** [comment]
There is currently no planned support for bit and json data types.

**Comment by slimtom95** [comment]
How about MySQL enum type? 
Exception: Unknown data type family: enum. Maybe you meant: ['Enum','Enum8']
It seems to be an easy task.

**Comment by tavplubix** [comment]
> How about MySQL enum type?
> Exception: Unknown data type family: enum. Maybe you meant: ['Enum','Enum8']

#18310

**Comment by yuuch** [comment]
> There is currently no planned support for bit and json data types.


I have tried to support the BIT type through the String type locally. Is this feasible? If possible, then I will submit a pull request. @zhang2014

**Comment by tlightsky** [comment]
also have similar issue

**Comment by tavplubix** [comment]
BIT data type: #32900
TIME data type: #33429
