### ISSUE TITLE
system.parts duplicates result at 30 minutes of the hour

### ISSUE THREAD

**Issue by Slind14** [ClickHouse/ClickHouse#14747]
Querying the `rows` column of the `system.parts` table returns twice the amount at the full hour as well as 30 minutes of the hour.

E.g. `SELECT sum(rows) FROM system.parts WHERE active AND table IN (...);`

When executed at h.00 or h.30 it returns twice the amount as compared to times which are not the full hour or 30 minutes of the hour.

This is occurred with version: 19.16.19.85

**Comment by Slind14** [comment]
This did not happen before with the same version of clickhouse. 

@alexey-milovidov I see you added `obsolete-version`, which one would you recommend upgrading to without the smallest possible risk? (we don't need the new features yet)
(the versioning is a bit unclear, it doesn't seem to follow Semantic Versioning)

**Comment by den-crane** [comment]
@Slind14 do you swap tables using 'rename table xxx to xxx_old, xxx_new to xxx' ?

**Comment by Slind14** [comment]
We don't. In fact, we didn't make any changes to how we work with tables since it started.

Seeing that it is based on the parts data, we might be running into the same issue with select count() if we upgrade, no?

**Comment by den-crane** [comment]
>since it started.

Since what started?

The root cause is unclear. No guarantee that it's fixed in the latest versions.

Label `obsolete-version` means that the issue is not relevant (not important) until it reproduced at stable/master releases.
The current stable 20.6+ (or 20.3 LTS).

**Comment by den-crane** [comment]
What is the table DDL ? Show create table ...
Do you have some cron-jobs at these time?

**Comment by Slind14** [comment]
I looked at the records of what it returned in the past. One month ago, it never occurred that it returned twice the amount. Since last month it has been occurring very regularly. Sometimes every second time we ran the query.

```
CREATE TABLE default.qLZPsR3 (`impressionUUID` FixedString(16), [...] 
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{layer}-{shard}/qLZPsR3 ', '{replica}') 
PARTITION BY toYYYYMM(date) 
ORDER BY (date, timestamp) 
SETTINGS index_granularity = 8192
```

It actually changed now. Last month it was:

![image](https://user-images.githubusercontent.com/3914677/93131675-bf3a7380-f6d4-11ea-8945-a0882f7a118c.png)
It keeps going like this

Now it is like this (it increased and it is no longer only on the full hour and half hour):
![image](https://user-images.githubusercontent.com/3914677/93131702-cfeae980-f6d4-11ea-9da7-65d6f6d79e87.png)

**Comment by den-crane** [comment]
Let's isolate issue from your code.
Can you show an output of this command:
```
for i in `seq 1 3600`; do echo -n  `date`"    "; clickhouse-client -q "select sum(rows) nrows from system.parts where active and table in ('qLZPsR3')"; sleep 1; done;
```
executed during one hour or less if it shows nrows jumping.

**Comment by Slind14** [comment]
Thank you. I should have done that before submitting an issue. Turns out the issue is an unexpected behavior where two records submitted with the same timestamp result in them being summed. Interestingly this wasn't the case before and is likely related to an API behavior change. 

I didn't realize that we were only logging the response from the third party and not the data we sent to it.

Sorry about troubling you and thank you very much for helping :)
