### ISSUE TITLE
LineAsString unexpected results (unreleased)

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#14749]
20.10.1.4616.

```
CREATE TABLE line_as_string(field String) ENGINE = MergeTree order by tuple();

$ clickhouse-client -q "select repeat('aaa',50) from numbers(100000000)" >LineAsString.txt
$ wc -l LineAsString.txt
100000000 LineAsString.txt

$ cat LineAsString.txt |clickhouse-client -q "INSERT INTO line_as_string FORMAT LineAsString"

select count() from line_as_string
┌───count()─┐
│ 100228882 │
└───────────┘

truncate table line_as_string;

$ clickhouse-client -q "INSERT INTO line_as_string FORMAT LineAsString" <LineAsString.txt

select count() from line_as_string
┌───count()─┐
│ 100014305 │
└───────────┘

truncate table line_as_string;

$ clickhouse-client -q "INSERT INTO line_as_string FORMAT TSV" <LineAsString.txt

select count() from line_as_string
┌───count()─┐
│ 100000000 │
└───────────┘

```

**Comment by den-crane** [comment]
@hexiaoting

**Comment by den-crane** [comment]
One more test -- random long string:

$ clickhouse-client -q "SELECT randomString(50000) FROM numbers(1000)" >randomLineAsString.txt

$ wc -l randomLineAsString.txt
1000 randomLineAsString.txt

$ cat randomLineAsString.txt |clickhouse-client -q "INSERT INTO line_as_string FORMAT LineAsString"
Code: 49. DB::Exception: Current position in own buffer before checkpoint in own buffer

$ clickhouse-client -q "INSERT INTO line_as_string FORMAT LineAsString" <randomLineAsString.txt
Code: 49. DB::Exception: Current position in own buffer before checkpoint in own buffer

**Comment by hexiaoting** [comment]
Ok, I will try to fix out this problem

**Comment by hexiaoting** [comment]
https://github.com/ClickHouse/ClickHouse/pull/14842

**Comment by den-crane** [comment]
fixed https://github.com/ClickHouse/ClickHouse/pull/14842
