### ISSUE TITLE
Why use Union All queries for a tenfold faster performance improvement

### ISSUE THREAD

**Issue by yanchaoguo** [ClickHouse/ClickHouse#14750]
SELECT *
FROM work_basic_model
WHERE (product = 'tracker_view') AND (code = 'eDf8fZky' or id = 'eDf8fZky')

#改写之前一次查询十几秒 ，使用union all优化后不到 1s
SELECT 
    id, 
    title
FROM work_basic_model
WHERE (product = 'tracker_view') AND (id = 'eDf8fZky')
UNION ALL
SELECT *
FROM work_basic_model
WHERE (product = 'tracker_view') AND (code = 'eDf8fZky')

**Comment by den-crane** [comment]
What CH version do you use?
Can you provide **show create table work_basic_model**

**Comment by yanchaoguo** [comment]
> **show create table work_basic_model**

ClickHouse client version 20.3.1.2564 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 20.3.1 revision 54433.


---
CREATE TABLE app.work_basic_model (`product` Nullable(String), `id` Nullable(String), `title` Nullable(String), `code` Nullable(String), `total_pv` Nullable(Int64), `total_uv` Nullable(Int64), `total_form` Nullable(Int64), `user_login_id` Nullable(String), `work_form` Nullable(String), `from_work` Nullable(String), `new_platform` Nullable(String), `new_terminal` Nullable(String), `check_type` Nullable(String), `create_type` Nullable(Int32), `valid_work` Nullable(Int32), `source_id` Nullable(String), `product_id` Nullable(String), `attr_group_id` Nullable(String), `create_user` Nullable(String), `new_print_count` Nullable(Int64), `user_type` Nullable(String), `identity` Nullable(Int32), `publishers_id` Nullable(Int64), `is_ad_user` Nullable(Int32), `pv_24h` Nullable(Int32), `total_spv` Nullable(Int32), `spv_24h` Nullable(Int32), `publisher_name` Nullable(String), `product_code` Nullable(String), `work_type` Nullable(String), `sub_type` Nullable(String), `content_create_type` Nullable(Int32), `accord_type` Nullable(Int32), `accord_id` Nullable(Int64), `product_content_name` Nullable(String), `work_platform` Nullable(String), `work_os` Nullable(String), `user_register_platform` Nullable(String), `user_register_os` Nullable(String), `user_register_product` Nullable(String), `product_platform` Nullable(String), `video_duration` Nullable(Float64), `market_like_count` Nullable(Int64), `market_comment_count` Nullable(Int64), `open_application_id` Nullable(String), `open_company_name` Nullable(String), `source_user` Nullable(String), `product_price` Nullable(String), `discount_price` Nullable(Int64), `member_price` Nullable(Int64), `member_type` Nullable(String), `grade_type` Nullable(Int32), `creative_type` Nullable(Int32), `create_identity` Nullable(Int32), `is_member_free` Nullable(Int32), `source_identity` Nullable(Int32), `source_user_is_test` Nullable(Int32), `create_user_is_test` Nullable(Int32), `create_market_type` Nullable(Int32), `create_user_is_black` Nullable(Int32), `eqs_user_xd` Nullable(Float64), `create_time` Nullable(DateTime), `update_time` Nullable(DateTime), `publish_time` Nullable(DateTime), `user_reg_time` Nullable(DateTime), `valid_work_time` Nullable(DateTime), `product_create_time` Nullable(DateTime)) ENGINE = MergeTree PARTITION BY tuple() ORDER BY ifNull(id, '0') SETTINGS index_granularity = 8192

**Comment by den-crane** [comment]
Try to upgrade to 20.3.18.10

**Comment by filimonov** [comment]
Mist probably where vs prewhere issue (different columns are moved to prewhere),

or may be by the way how the condition are written (`a and (b or c)` )

Try using prewhere instead of where
