### ISSUE TITLE
Compact Format

### ISSUE THREAD

**Issue by mjodeh** [ClickHouse/ClickHouse#14764]
@den-crane 
Our insertion rate is 150 insertion per minute in 30 different tables, and on a max every insertions contains 2k rows, and the overall records is about 200 million rows/monthly, and we can not insert all of the sources into one table, also the columns' types are `Nullable`, and the column count per table `<= 100`

The server hardware: 48 CPU, 32 G RAM, but clickhouse consumes 4 to 5 GB or RAM;

1- is this memory consumption normal?

We have a lot of issues with the default `Wide` format and we are thinking of using the `Compact` format.

2 - Is it production ready, our server version `20.3.17 revision 54433`?
3 - How to switch from `Wide` to `Compact`? Does setting `min_bytes_for_wide_part, min_bytes_for_compact_part` automatically switch to `Compact` or we have to drop the tables and recreate them?
4 - How to find the best values to fill in the settings? either `bytes` or `rows`
5- Does the limit `min_bytes_for_wide_part, min_bytes_for_compact_part` applies per partition or on the whole table?
6- Does it degrade the query performance? we execute funnel and cohort queries
7- Does [vm.dirty_ratio](vm.dirty_ratio) affect the insertion performance?
8- Does `Buffer` table helps in such use cases?

Related Issues:
https://github.com/ClickHouse/ClickHouse/issues/13875, https://github.com/ClickHouse/ClickHouse/issues/13360, https://github.com/ClickHouse/ClickHouse/issues/12023

**Comment by alexey-milovidov** [comment]
> 1- is this memory consumption normal?

Yes, it's normal.

> 2 - Is it production ready, our server version 20.3.17 revision 54433?

We are still preparing compact parts for production. It is almost production ready but we still find some issues in corner cases. There are recent bugfixes in version 20.8.

> 3 - How to switch from Wide to Compact? Does setting min_bytes_for_wide_part, min_bytes_for_compact_part automatically switch to Compact or we have to drop the tables and recreate them?

It will switch automatically. After you modify these settings for a table, compact parts will start to be used.

> 4 - How to find the best values to fill in the settings? either bytes or rows

We are going to enable compact parts with 10 MB `min_bytes_for_wide_part`. It looks reasonably optimal. Small freshly inserted parts will appear in compact form and then transformed to wide format when they become larger than 10 MB after merge.

> 5- Does the limit min_bytes_for_wide_part, min_bytes_for_compact_part applies per partition or on the whole table?

Per part. So, when part is less than `min_bytes...`, `min_rows...` it will be compact.
The table can have multiple parts, some compact, some wide.

> 6- Does it degrade the query performance? we execute funnel and cohort queries

Compact parts are slightly slower for SELECT but with the 10 MB threshould you will have only a small portion of data in compact parts and the difference will be neglible. At the same time, compact parts are much faster for INSERT and as INSERTs generate small parts, they will benefit from compact format.

> 7- Does vm.dirty_ratio affect the insertion performance?

It may affect overall performance and latency spikes on server but the relation is complex and depend on hardware and workload. Do not set it to zero (inserted data should be allowed to buffer in memory) and do not set it too large (it may lead to server hangups when using slow IO devices).

> 8- Does Buffer table helps in such use cases?

Yes, Buffer helps to increase the throughput of small inserts. Compact format also helps and it achieves almost the same performance as Buffer table but without its drawbacks.

**Comment by mjodeh** [comment]
Thanx @alexey-milovidov 
9- What about using Buffer tables on cluster? is it possible to do so?
10- Also I tested the `Compact format` on the staging server and `rows=90000` and the insertion rate 2k/sec I noticed that the size it takes is far more the `Wide format`, is it correct or am I missing something here?

**Comment by alexey-milovidov** [comment]
> 9- What about using Buffer tables on cluster? is it possible to do so?

Yes, you can use Buffer tables on every server of your cluster.

> 10- Also I tested the Compact format on the staging server and rows=90000 and the insertion rate 2k/sec I noticed that the size it takes is far more the Wide format, is it correct or am I missing something here?

That most likely not the case - after merging and removal of temporary parts (8 minutes by default) the size will be almost the same.

**Comment by youguanxinqing** [comment]
>> 5- Does the limit min_bytes_for_wide_part, min_bytes_for_compact_part applies per partition or on the whole table?

>Per part. So, when part is less than `min_bytes...`, `min_rows...` it will be compact.
The table can have multiple parts, some compact, some wide.

hi alexey! Is it `min_bytes...` and `min_rows...` or `min_bytes...` or  `min_rows...` ? I created table by `... settings min_bytes_for_wide_part=512, min_rows_for_wide_part=2` and inserted three rows, it is still `compact` format. But if I insert rows that size is more than 512B, it is `wide` format.It seems  `min_rows_for_wide_part` does not work. 

My clickhouse is 21.12.3.32.
