### ISSUE TITLE
DELETE mutation uses extra disk space

### ISSUE THREAD

**Issue by keliss** [ClickHouse/ClickHouse#14777]
Hello. Can you please add more information on disk usage of the DELETE mutation to the documentation? It's better to know something like this before running into some issues on production.
Related question: https://github.com/ClickHouse/ClickHouse/issues/9627
And out of curiosity: why does that need extra disk space? DROP PARTITION seems to effectively do the same, but it operates just fine without such a requirement.
Thanks.

**Comment by den-crane** [comment]
Mutations (and merges) book twice disk space as original parts. It is done this way because mutations re-write original parts (row by row) to the new parts and remove original parts in the end. 

DROP PARTITION just removes files from a disk and from a list with available parts.
