### ISSUE TITLE
arrayCompact for array with tuples

### ISSUE THREAD

**Issue by mshpakov** [ClickHouse/ClickHouse#14778]
Currently arrayCompact doesn't work with tuples like other array functions arraySort or arrayFilter.
Please consider adding such functionality to arrayCompact.
We need something like this... SELECT arrayCompact( (x,y) -> y, arr1, arr2) AS v

Current behavior:
`SELECT
    [('a', 1), ('a', 2), ('c', 3), ('a', 2)] AS arr,
    arrayCompact(x -> (x.1), arr) AS v,
    [('a', 1), ('c', 3), ('a', 2)] AS expected_v
`
![изображение](https://user-images.githubusercontent.com/33029350/93028896-5fca5e00-f617-11ea-9d55-e0a5d3c36697.png)

**Comment by 1340691923** [comment]
Have you solved this problem?

**Comment by nvartolomei** [comment]
```
SELECT
    [('a', 1), ('a', 2), ('c', 3), ('a', 2)] AS arr,
    arrayCompact(x -> (x.1), arr) AS v,
    [('a', 1), ('c', 3), ('a', 2)] AS expected_v

Query id: 7b269133-dd69-46e0-a5f0-d8bf942ed462

┌─arr───────────────────────────────┬─v─────────────────────────┬─expected_v────────────────┐
│ [('a',1),('a',2),('c',3),('a',2)] │ [('a',1),('c',3),('a',2)] │ [('a',1),('c',3),('a',2)] │
└───────────────────────────────────┴───────────────────────────┴───────────────────────────┘
```

this can be closed
