### ISSUE TITLE
securecrt5.1 connect to clickhouse 2.8, show command error

### ISSUE THREAD

**Issue by l1t1** [ClickHouse/ClickHouse#14782]
(you don't have to strictly follow this form)
i input show, and the client show following
**Describe the bug**
[root@centos ~]# clickhouse-client
ClickHouse client version 20.8.1.4513 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 20.8.1 revision 54438.

centos :) sshshoshowshow show tshow showshoshs
centos :) sshshoshowshow 

**How to reproduce**
* Which ClickHouse server version to use
* Which interface to use, if matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

**Expected behavior**

**Error message and/or stacktrace**

**Additional context**

**Comment by l1t1** [comment]
putty 0.7 is ok

**Comment by xiashaohua** [comment]
I have the same problem when i update to clickhouse 20.7.1.1。

**Comment by den-crane** [comment]
Please show ` env|grep -i term `

**Comment by l1t1** [comment]
putty is xterm ,securecrt was vt100, change to xterm too, show command ok, thanks
