### ISSUE TITLE
MaterializeMySQL Data inconsistency between MySQL and Clickhouse 

### ISSUE THREAD

**Issue by chang0391** [ClickHouse/ClickHouse#14781]
**Describe the bug**
mysql:5.7.31
clickhouse:20.10.1.4635 
I  found data inconsistency between MySQL and Clickhouse when I execute update in MySQL with one transaction with 439129 rows
**How to reproduce**
step1:
    I check that the amount of data is consistent between MySQL and Clickhouse
  mysql> select count(1) from mobile_belong 
    -> ;
+----------+
| count(1) |
+----------+
|   439129 |
+----------+
test-1-118.raipeng.com :) select count(1) from mobile_belong;
SELECT count(1)
FROM mobile_belong
┌─count(1)─┐
│   439129 │
└──────────┘
1 rows in set. Elapsed: 0.043 sec. Processed 439.13 thousand rows, 10.98 MB (10.30 million rows/s., 257.46 MB/s.) 
step2: 
   I executed update in MySQL as below
 mysql> update mobile_belong set province='北京',city='北京';
Query OK, 419371 rows affected (1.98 sec)
Rows matched: 439129  Changed: 419371  Warnings: 0
step3:
 checking data in MySQL and ClickHouse, and found  mysql updated data of 439129 rows successfully ,but,clickhouse only have 438459 rows be updated successfully,remian  439129-438459  not be updated.
mysql> select count(1) from mobile_belong where province='北京' and city='北京';
+----------+
| count(1) |
+----------+
|   439129 |
+----------+
1 row in set (0.16 sec)
test-1-118.raipeng.com :) select count(1) from mobile_belong where province='北京' and city='北京';
SELECT count(1)
FROM mobile_belong
WHERE (province = '北京') AND (city = '北京')
┌─count(1)─┐
│   438459 │
└──────────┘
1 rows in set. Elapsed: 0.068 sec. Processed 523.68 thousand rows, 29.88 MB (7.66 million rows/s., 436.86 MB/s.)

**Comment by zhang2014** [comment]
what is the table structure?

**Comment by liangli1213** [comment]
@chang0391 is there any error message in ClickHouse's log?

**Comment by chang0391** [comment]
no error found, table structure as below
CREATE TABLE `mobile_belong_test` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `section` int(11) DEFAULT NULL,
  `provinceId` varchar(10) DEFAULT NULL,
  `province` varchar(30) DEFAULT NULL,
  `cityId` varchar(10) DEFAULT NULL,
  `city` varchar(30) DEFAULT NULL,
  `sign` int(11) DEFAULT NULL,
  `name` varchar(10) DEFAULT NULL,
  `section2` int(11) DEFAULT NULL,
  `provinceId2` varchar(10) DEFAULT NULL,
  `province2` varchar(30) DEFAULT NULL,
  `cityId2` varchar(10) DEFAULT NULL,
  `city2` varchar(30) DEFAULT NULL,
  `sign2` int(11) DEFAULT NULL,
  `name2` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=458746 DEFAULT CHARSET=utf8mb4

**Comment by BohuTANG** [comment]
From the underlying, this issue duplicated https://github.com/ClickHouse/ClickHouse/issues/14786
it's payload.available() caused, and on the fixing
