### ISSUE TITLE
Time series based select queries slower compare to aggregation query

### ISSUE THREAD

**Issue by sounaks01** [ClickHouse/ClickHouse#14784]
We have 2 node cluster and each node has single shard and single replica. Below are my create table statements. 

`"create table archive.d_traffic on cluster '{cluster}' (  a  UInt32,  b  UInt32,  c  UInt32,  d  String,  timestamp  datetime,  metric1  Float32,  outoctets  Float32,  c  String, INDEX idxa (a) TYPE minmax GRANULARITY 4, INDEX idxb (b) TYPE minmax GRANULARITY 4, INDEX idxc (c) TYPE minmax GRANULARITY 4, INDEX idxTime (timestamp) TYPE minmax GRANULARITY 4, INDEX idxh (c) TYPE minmax GRANULARITY 4, INDEX idxbTime (b,timestamp) TYPE minmax GRANULARITY 4, INDEX idxaTime (a,timestamp) TYPE minmax GRANULARITY 4, INDEX idxba (a,b) TYPE minmax GRANULARITY 4, INDEX idxbaTime (b,a,timestamp) TYPE minmax GRANULARITY 4, INDEX idxbacTime (b,a,c,timestamp) TYPE minmax GRANULARITY 4, INDEX idxbacdTime (b,a,c,d,timestamp) TYPE minmax GRANULARITY 4, INDEX idxbaTimeh (b,a,timestamp,c) TYPE minmax GRANULARITY 4, INDEX idxbacTimeh (b,a,c,timestamp,c) TYPE minmax GRANULARITY 4, INDEX idxbacdTimeh (b,a,c,d,timestamp,c) TYPE minmax GRANULARITY 4 ) ENGINE = MergeTree() PARTITION BY toYYYYMM( timestamp ) ORDER BY ( a ,  b , timestamp )"`

`create table archive.d_traffic_distribute on cluster '{cluster}' as archive.d_traffic ENGINE = Distributed(f_cluster, archive, d_traffic, rand());`

Below select query we are running in single and multi-node environment. 

Time series select query :-
`"select metric1 from archive.d_traffic_distribute where timestamp > 1599084720 and timestamp <= (1599084720+72000) and IPv4NumToString(router) = '100' and b in (1,2,3,4,5) order by timestamp";
` 
 *Above query max returns 120K rows*
Single node response time = 12.02 secs  
Multi node response time = 12.06 secs

Aggregation query :- 
`select c,sum(metric1) from archive.d_traffic_distribute group by protocol order by c` 

Single node response time = 8.08 secs  
Multi node response time = 2.019secs

For Aggregation type query we are getting better result in multi node cluster. But normal time series based query response time is almost same. Is this expected? Or we need to do any table creation / cluster configuration changes ?

**Comment by den-crane** [comment]
1. Is not a timeseries DB.

2. ALL your skip **indexes are WRONG. Remove them.**
  INDEX idxTime (timestamp) TYPE minmax
  INDEX idxbTime (b,timestamp) TYPE minmax
  skip indexes  <> BTree. 
  b,timestamp ===  minmax B, minmax timestamp
  idxTime is excessive because it's covered by idxbTime.
