### ISSUE TITLE
Segfault in JOIN with join_algorithm='auto' with Nullable(String) vs LowCardinality(String) in JOIN key

### ISSUE THREAD

**Issue by Jokser** [ClickHouse/ClickHouse#14796]
CH version 20.3.15.133
When I run the following queries:
https://gist.github.com/Jokser/b6143644a5d7fd043c708392b58521db
https://paste.yandex-team.ru/1309221
CH is segfaulted with the following stack trace:
https://gist.github.com/Jokser/494d0af83ba9ecab0a418d4a51595cdd
Table structures:
https://gist.github.com/Jokser/7aff2753834120f8a8828e1e5f6777dc

I suspect that problem is related to the following condition:
`(t.size_name = d.size_name)`

When I add a condition `WHERE size_name != null` to sub-query from:
`FROM crawler.wb_add_info_sizes AS t`

The query is executed successfully. Seems there is a bug with determining whether join condition has nullable columns or not.

**Comment by 4ertus2** [comment]
Related #11414

**Comment by 4ertus2** [comment]
`joinSortedBlock<false, true>` from stack trace says thet it's join on disk. And we call it from CreatingSetsBlockInputStream. That's strange cause the query from issue is not a right join subquery. The crash is for query that countains nested join for right table. Something like
```
select ... from t1 join (select ... from t3 join (select ... t5 join t6 on ...) t4 on ...) t2 on ...
```
There the first CreatingSetsBlockInputStream is for t2, the second - for t4. And there's a MergeJoin on disk between t5 and t6 where we crash. It also could be CreatingSetsBlockInputStream for `IN` but there's no chanses that it's a stack trace for a full query in issue.

**Comment by 4ertus2** [comment]
Probably related `Data compressed with different methods`. Affects `join_algorithm = 'auto'` only.
```
SET join_algorithm = 'auto';
SET max_bytes_in_join = 100;

CREATE TABLE t (`x` UInt32, `s` LowCardinality(String)) ENGINE = Memory;
CREATE TABLE nr (`x` Nullable(UInt32), `s` Nullable(String)) ENGINE = Memory;

INSERT INTO t VALUES (1, 'l');
INSERT INTO nr VALUES (2, NULL);

SELECT l.s FROM t AS l LEFT JOIN nr AS r USING (s);
```

**Comment by 4ertus2** [comment]
Need reproduction with #15088
