### ISSUE TITLE
CH server does not follow memory restrictions while executing certain queries on multithreaded sources

### ISSUE THREAD

**Issue by Akazz** [ClickHouse/ClickHouse#14811]
**Describe the unexpected behaviour**
ClickHouse server would not follow memory restictions while executing queries on multithreaded sources. This behaviour can lead to system running out of memory with subsequent server termination by OOM-killer.

**How to reproduce**
* The problem reproduces on ClickHouse v20.9, v20.10
* `SELECT count(range(1, 65536)) FROM system.numbers_mt LIMIT 1048576`
* This query may succeed with max_threads = 1 or some other small value

**Expected behavior**
Query must terminate with error message similair to the following:
```
Received exception from server (version 20.10.1):
Code: 241. DB::Exception: Received from localhost:9000. DB::Exception: Memory limit (for query) exceeded: would use 16.04 GiB (attempt to allocate chunk of 17180394296 bytes), maximum: 9.31 GiB: While executing AggregatingTransform.
```

**Error message and/or stacktrace**
Server process is Killed by system OOM-killer.

**Comment by alexey-milovidov** [comment]
Fixed #16206
