### ISSUE TITLE
Changes in master broke WITH TIMEOUT clause in LIVE VIEW tables.

### ISSUE THREAD

**Issue by vzakaznikov** [ClickHouse/ClickHouse#14827]
**Describe the bug**
Changes to `LIVE VIEW` storage broke `WITH TIMEOUT` clause (https://github.com/ClickHouse/ClickHouse/commit/70b0fe88b1c6394f4415c020c39d28ac2fc5704a).

**How to reproduce**
```
user-host :) CREATE LIVE VIEW lv WITH TIMEOUT 5 AS SELECT 1

CREATE LIVE VIEW lv WITH TIMEOUT 5 AS
SELECT 1

Ok.

0 rows in set. Elapsed: 0.012 sec. 

user-host :) watch lv

WATCH lv

┌─1─┬─_version─┐
│ 1 │        1 │
└───┴──────────┘
Cancelling query.
Query was cancelled.

1 rows in set. Elapsed: 5.537 sec. 

user-host :) show tables

SHOW TABLES

┌─name─┐
│ lv   │
└──────┘

1 rows in set. Elapsed: 0.003 sec. 

user-host :) show tables

SHOW TABLES

┌─name─┐
│ lv   │
└──────┘

1 rows in set. Elapsed: 0.003 sec. 

user-host :) 
```

* Which ClickHouse server version to use
Current master.

**Expected behavior**
When TIMEOUT is specified the LIVE VIEW table should be deleted after the specified interval has passed when there are no active `WATCH` queries.

**Comment by vzakaznikov** [comment]
@vitlibar, the https://github.com/ClickHouse/ClickHouse/commit/70b0fe88b1c6394f4415c020c39d28ac2fc5704a caused regression :(. 

Looks like some tests are not checking that the view is actually auto-deleted.

```
./00991_temporary_live_view_watch_live.sh.disabled
./00991_temporary_live_view_watch_live.reference
./00963_temporary_live_view_watch_live_timeout.reference
./00961_temporary_live_view_watch.sql
./00980_create_temporary_live_view.reference
./00961_temporary_live_view_watch.reference
./00962_temporary_live_view_watch_live.reference
./00980_create_temporary_live_view.sql
./00991_temporary_live_view_watch_events_heartbeat.reference
./00991_temporary_live_view_watch_events_heartbeat.sh.disabled
./00963_temporary_live_view_watch_live_timeout.py.disabled
./00962_temporary_live_view_watch_live.py
./00991_temporary_live_view_watch_events_heartbeat.python
./00991_temporary_live_view_watch_live.python
```

**Comment by vitlibar** [comment]
> Looks like some tests are not checking that the view is actually auto-deleted.

That's strange. All the tests were passed successfully when I merged https://github.com/ClickHouse/ClickHouse/commit/70b0fe88b1c6394f4415c020c39d28ac2fc5704a.

**Comment by vitlibar** [comment]
I've just checked `00980_create_temporary_live_view` locally and it works.

**Comment by vzakaznikov** [comment]
Yes, the test
