### ISSUE TITLE
MaterializeMySQL count() result is incorrect

### ISSUE THREAD

**Issue by vegastar002** [ClickHouse/ClickHouse#14829]
mysql have table t(a Int, b Int), 2 records: (1,1) and (2, 2), then in ck count
`select count(1) from ckdb.t ` -- 2, that's ok.
then, mysql  delete (2,2) and ck count
`select count(1) from ckdb.t ` -- still 2, that's not correct .

**Comment by vegastar002** [comment]
ck version: clickhouse-common-static-20.8.2.3-2.x86_64

**Comment by tavplubix** [comment]
Probably related #14781

**Comment by BohuTANG** [comment]
Hello @vegastar002 

We've fixed it in this patch https://github.com/ClickHouse/ClickHouse/pull/14852
You can use the latest master build and check it again:
https://clickhouse-builds.s3.yandex.net/0/3e0509af691d715747c8f6e6eb8e0f3e30942fbf/clickhouse_build_check/report.html

**Comment by tavplubix** [comment]
Fixed in #15767
