### ISSUE TITLE
Cant' execute grant SQL

### ISSUE THREAD

**Issue by spihiker** [ClickHouse/ClickHouse#14830]
Clikchouse Version : 20.3.17.173
Problem of RBAC:
When i execute the follow SQL, it's oK.
```
CREATE ROLE devgroup;
GRANT SELECT,INSERT ON *.* TO devgroup;
 ````
  
But when I `GRANT SOURCES` ,don't work;
```
jyw-centos7-bd04 :) GRANT SOURCES ON *.* TO devgroup;

Syntax error: failed at position 15:

GRANT SOURCES ON *.* TO devgroup;

Expected one of: EXCEPT, Comma, At, TO, token
```

How can i grant privileges  about SOURCES? Thanks for you help.

**Comment by filimonov** [comment]
> How can i grant privileges about SOURCES?

Update clickhouse version. 20.3 should not be used for RBAC

**Comment by spihiker** [comment]
When update 20.6 ,work well .thank you .
