### ISSUE TITLE
MaterializedMySQL  Packet payload is not fully read. Stopped after 7372 bytes, while 693 bytes are in buffer

### ISSUE THREAD

**Issue by leoones** [ClickHouse/ClickHouse#14835]
MySQL  INSERT INTO : 
table:  cleanout_asin_info_jp
table count :
select count(1) from  cleanout_asin_info_jp
10308

execution sql:
insert into cleanout_asin_info_jp
(asin
,product_title
,provide
,provide_id
,product_path
,img1
,img2
,img3
,img4
,img5
,currency
,list_price
,sale_price
,price
,deal_price
,price_mc
,price_savings
,price_savings_percent
,bullet_point1
,bullet_point2
,bullet_point3
,bullet_point4
,bullet_point5
,customer_reviews_count
,ask
,best_seller
,best_seller_path
,stars
,five_star
,four_star
,three_star
,two_star
,one_star
,issue_date
,top_bad_reviews
,offer_listing
,item_model_number
,soldby
,seller_id
,fba
,bsr1
,bsr1path
,bsr2
,bsr2path
,bsr3
,bsr3path
,bsr4
,bsr4path
,bsr5
,bsr5path
,AddOn
,add_date_time
,local_date_time)
select 
asin
,product_title
,provide
,provide_id
,product_path
,img1
,img2
,img3
,img4
,img5
,currency
,list_price
,sale_price
,price
,deal_price
,price_mc
,price_savings
,price_savings_percent
,bullet_point1
,bullet_point2
,bullet_point3
,bullet_point4
,bullet_point5
,customer_reviews_count
,ask
,best_seller
,best_seller_path
,stars
,five_star
,four_star
,three_star
,two_star
,one_star
,issue_date
,top_bad_reviews
,offer_listing
,item_model_number
,soldby
,seller_id
,fba
,bsr1
,bsr1path
,bsr2
,bsr2path
,bsr3
,bsr3path
,bsr4
,bsr4path
,bsr5
,bsr5path
,AddOn
,add_date_time
,local_date_time
from cleanout_asin_info_jp ;

 ClickHouse exception, code: 99, host: 172.16.6.207, port: 8123; Code: 99, e.displayText() = DB::Exception: Packet payload is not fully read. Stopped after 7372 bytes, while 693 bytes are in buffer. (version 20.8.2.3 (official build))

err log:
2020.09.15 16:32:49.288707 [ 1552 ] {cc5108a6-0250-4d05-91b2-aea49f5ea3ba} <Error> DynamicQueryHandler: Code: 99, e.displayText() = DB::Exception: Packet payload is not fully read. Stopped after 7372 bytes, while 693 bytes are in buffer., Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x1a80ae30 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xff9e75d in /usr/bin/clickhouse
2. ? @ 0x173bf410 in /usr/bin/clickhouse
3. DB::MySQLProtocol::PacketEndpoint::tryReceivePacket(DB::MySQLProtocol::IMySQLReadPacket&, unsigned long) @ 0x173cbe27 in /usr/bin/clickhouse
4. DB::MySQLClient::readOneBinlogEvent(unsigned long) @ 0x173c9491 in /usr/bin/clickhouse
5. DB::MaterializeMySQLSyncThread::synchronization(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x173a10b0 in /usr/bin/clickhouse
6. ? @ 0x173a14b6 in /usr/bin/clickhouse
7. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xffce517 in /usr/bin/clickhouse
8. ? @ 0xffccb53 in /usr/bin/clickhouse
9. start_thread @ 0x7e65 in /usr/lib64/libpthread-2.17.so
10. clone @ 0xfe88d in /usr/lib64/libc-2.17.so
 (version 20.8.2.3 (official build))

clickhouse-server.log:
2020.09.15 16:32:49.287267 [ 1552 ] {} <Trace> DynamicQueryHandler: Request URI: /?max_result_rows=200&compress=1&user=default&password=clickhouse123&extremes=0&query_id=cc5108a6-0250-4d05-91b2-aea49f5ea3ba&result_overflow_mode=break&database=ptx_db
2020.09.15 16:32:49.287574 [ 1552 ] {cc5108a6-0250-4d05-91b2-aea49f5ea3ba} <Debug> executeQuery: (from 172.16.7.163:1231) SELECT count(1) FROM test_binlog.cleanout_asin_info_jp FORMAT TabSeparatedWithNamesAndTypes;
2020.09.15 16:32:49.288400 [ 1552 ] {cc5108a6-0250-4d05-91b2-aea49f5ea3ba} <Error> executeQuery: Code: 99, e.displayText() = DB::Exception: Packet payload is not fully read. Stopped after 7372 bytes, while 693 bytes are in buffer. (version 20.8.2.3 (official build)) (from 172.16.7.163:1231) (in query: SELECT count(1) FROM test_binlog.cleanout_asin_info_jp FORMAT TabSeparatedWithNamesAndTypes;), Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x1a80ae30 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xff9e75d in /usr/bin/clickhouse
2. ? @ 0x173bf410 in /usr/bin/clickhouse
3. DB::MySQLProtocol::PacketEndpoint::tryReceivePacket(DB::MySQLProtocol::IMySQLReadPacket&, unsigned long) @ 0x173cbe27 in /usr/bin/clickhouse
4. DB::MySQLClient::readOneBinlogEvent(unsigned long) @ 0x173c9491 in /usr/bin/clickhouse
5. DB::MaterializeMySQLSyncThread::synchronization(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x173a10b0 in /usr/bin/clickhouse
6. ? @ 0x173a14b6 in /usr/bin/clickhouse
7. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xffce517 in /usr/bin/clickhouse
8. ? @ 0xffccb53 in /usr/bin/clickhouse
9. start_thread @ 0x7e65 in /usr/lib64/libpthread-2.17.so
10. clone @ 0xfe88d in /usr/lib64/libc-2.17.so

2020.09.15 16:32:49.288707 [ 1552 ] {cc5108a6-0250-4d05-91b2-aea49f5ea3ba} <Error> DynamicQueryHandler: Code: 99, e.displayText() = DB::Exception: Packet payload is not fully read. Stopped after 7372 bytes, while 693 bytes are in buffer., Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x1a80ae30 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xff9e75d in /usr/bin/clickhouse
2. ? @ 0x173bf410 in /usr/bin/clickhouse
3. DB::MySQLProtocol::PacketEndpoint::tryReceivePacket(DB::MySQLProtocol::IMySQLReadPacket&, unsigned long) @ 0x173cbe27 in /usr/bin/clickhouse
4. DB::MySQLClient::readOneBinlogEvent(unsigned long) @ 0x173c9491 in /usr/bin/clickhouse
5. DB::MaterializeMySQLSyncThread::synchronization(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x173a10b0 in /usr/bin/clickhouse
6. ? @ 0x173a14b6 in /usr/bin/clickhouse
7. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xffce517 in /usr/bin/clickhouse
8. ? @ 0xffccb53 in /usr/bin/clickhouse
9. start_thread @ 0x7e65 in /usr/lib64/libpthread-2.17.so
10. clone @ 0xfe88d in /usr/lib64/libc-2.17.so

**Comment by BohuTANG** [comment]
duplicated https://github.com/ClickHouse/ClickHouse/issues/14786#issuecomment-691862955

**Comment by leoones** [comment]
> duplicated #14786

Are you talking about data duplication ?

**Comment by BohuTANG** [comment]
no, issue related, all of them are same root cause, and we are fixing
