### ISSUE TITLE
Count in AggregateMergeTree

### ISSUE THREAD

**Issue by shubham721** [ClickHouse/ClickHouse#14844]
Hi Guyz,
I wanted to understand that how we can keep track of counts for a groupby keys. As In clickhouse, data is not anytime in its final form And when the parts get merged in background then columns for which no aggregate function is specified Any random values is taken.

For Example:
create table exp_raw(
	id UInt64,
	data String
)Engine=Log

create table exp_mergetree(
	id UInt64,
	eval UInt64,
	data SimpleAggregateFunction(max, String)
)
Engine = AggregatingMergeTree()
order by id

create materialized view exp_mv to exp_mergetree
AS select
id,
count() as eval,
max(data) as data
FROM exp_raw
Group BY id
order by id

INSERT INTO exp_raw values(12, 'hey')
INSERT INTO exp_raw values(12, 'Fine')

***************************************
select * from exp_mergetree;
It contains both of these records
┌─id─┬─eval─┬─data─┐
│ 12 │    1 │ Fine │
└────┴──────┴──────┘
┌─id─┬─eval─┬─data─┐
│ 12 │    1 │ hey  │
└────┴──────┴──────┘

When I run optimize table command, The result is
┌─id─┬─eval─┬─data─┐
│ 12 │    1 │ hey  │
└────┴──────┴──────┘

But Thats not what I want. I wanted the eval count to be 2.
Is there a way we can use count as an aggregate function in Aggregate merge tree table?
I can always keep one more column in raw table which has a value 1. But I am looking to solve this with aggregate function.

**Comment by den-crane** [comment]
SummingMergeTree -- does automatic summing of numeric columns, AggregatingMergeTree does not.

AggregatingMT require AggregateFunction   or SimpleAggregateFunction .

eval **SimpleAggregateFunction**(sum,UInt64)


```

create table exp_mergetree(
   id UInt64,
   eval SimpleAggregateFunction(sum,UInt64),    <---------------
   data SimpleAggregateFunction(max, String)
)
Engine = AggregatingMergeTree()
order by id
```

**Comment by shubham721** [comment]
I can do that, But I won't be able to write populate query
As I can't give a aggregate function inside another one
sum(count()) is not supported.

**Comment by den-crane** [comment]
>But I won't be able to write populate query

Not true. Give me example.

>sum(count()) is not supported.

You are mistaken. You don't need `sum(count())`. Try with only `count()`. MV will calculate count. Let's say 301. And will write 301 into a `eval SimpleAggregateFunction`. SimpleAggregateFunction does not require state or function. It works with simple values `301` during merges.
