### ISSUE TITLE
Clickhouse odbc installation error

### ISSUE THREAD

**Issue by sanjaypocket52** [ClickHouse/ClickHouse#14841]
Guys we have followed below link for debian installation clickhouse with odbc driver but we face below error

https://github.com/ClickHouse/clickhouse-odbc#building-from-sources-debianubuntu

perl: warning: Falling back to the standard locale ("C").
Can't locate DBI.pm in @INC (@INC contains: /opt/rh/devtoolset-8/root//usr/lib64/perl5/vendor_perl /opt/rh/devtoolset-8/root/usr/lib/perl5 /opt/rh/devtoolset-8/root//usr/share/perl5/vendor_perl /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /home/centos/clickhouse-odbc/test/detect_driver_manager.pl line 8.
BEGIN failed--compilation aborted at /home/centos/clickhouse-odbc/test/detect_driver_manager.pl line 8.
-- ODBC Driver Manager used by Perl's DBD::ODBC: 
Traceback (most recent call last):
  File "/home/centos/clickhouse-odbc/test/detect_driver_manager.py", line 5, in <module>
    import pyodbc

**Comment by filimonov** [comment]
wrong repo (you can open issue in https://github.com/ClickHouse/ClickHouse-odbc )
