### ISSUE TITLE
Server killed by OOM (was: crash caused by Memory limit (total) exceeded)

### ISSUE THREAD

**Issue by jjtjiang** [ClickHouse/ClickHouse#14862]
i user docker start clcikhosue.when a query use memory is larger ,clickhosue  will crash.i have set max_memory_usage_for_all_queries=9500000000 and  max_server_memory_usage=9500000000.
i think if memory is not enough ，this query should fail but server should not crash.
thanks.
 sudo dmesg -T |grep -i Kill logs are below:
[Tue Sep 15 00:01:24 2020]  [<ffffffff9659ac64>] oom_kill_process+0x254/0x3d0
[Tue Sep 15 00:01:24 2020] Task in /docker/bc8361b978f98b297522f69b7c85da05ac9bf5e84f7ae05fa61030b81cc5cc56 killed as a result of limit of /docker/bc8361b978f98b297522f69b7c85da05ac9bf5e84f7ae05fa61030b81cc5cc56
[Tue Sep 15 00:01:24 2020] Memory cgroup out of memory: Kill process 20423 (QueryPipelineEx) score 1008 or sacrifice child
[Tue Sep 15 00:01:24 2020] Killed process 1295 (clickhouse-serv) total-vm:32828748kB, anon-rss:10494108kB, file-rss:51264kB, shmem-rss:0kB

logs are below:

2020.09.15 15:01:30.650421 [ 133 ] {cdb9ee1f-fd4e-4631-8e5e-66ba0586b1be} <Error> DynamicQueryHandler: Code: 241, e.displayText() = DB::Exception: Memory limit (total) exceeded: would use 9.80 GiB (attempt to allocate chunk of 4315666 bytes), maximum: 8.85 GiB, Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x12400be0 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xa2433fd in /usr/bin/clickhouse
2. ? @ 0xa2422dd in /usr/bin/clickhouse
3. MemoryTracker::alloc(long) @ 0xa240742 in /usr/bin/clickhouse
4. MemoryTracker::alloc(long) @ 0xa240742 in /usr/bin/clickhouse
5. MemoryTracker::alloc(long) @ 0xa240742 in /usr/bin/clickhouse
6. DB::CompressedWriteBuffer::CompressedWriteBuffer(DB::WriteBuffer&, std::__1::shared_ptr<DB::ICompressionCodec>, unsigned long) @ 0xed96ea8 in /usr/bin/clickhouse
7. DB::MergeTreeDataPartWriterOnDisk::Stream::Stream(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::IDisk>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::ICompressionCodec> const&, unsigned long, unsigned long, unsigned long) @ 0xf934486 in /usr/bin/clickhouse
8. ? @ 0xf93b1a4 in /usr/bin/clickhouse
9. DB::DataTypeNullable::enumerateStreams(std::__1::function<void (std::__1::vector<DB::IDataType::Substream, std::__1::allocator<DB::IDataType::Substream> > const&)> const&, std::__1::vector<DB::IDataType::Substream, std::__1::allocator<DB::IDataType::Substream> >&) const @ 0xeeb6d80 in /usr/bin/clickhouse
10. DB::MergeTreeDataPartWriterWide::MergeTreeDataPartWriterWide(std::__1::shared_ptr<DB::IMergeTreeDataPart const> const&, DB::NamesAndTypesList const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeIndex const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeIndex const> > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::ICompressionCodec> const&, DB::MergeTreeWriterSettings const&, DB::MergeTreeIndexGranularity const&) @ 0xf93ad62 in /usr/bin/clickhouse
11. DB::MergeTreeDataPartWide::getWriter(DB::NamesAndTypesList const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeIndex const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeIndex const> > > const&, std::__1::shared_ptr<DB::ICompressionCodec> const&, DB::MergeTreeWriterSettings const&, DB::MergeTreeIndexGranularity const&) const @ 0xf9272c0 in /usr/bin/clickhouse
12. DB::MergedBlockOutputStream::MergedBlockOutputStream(std::__1::shared_ptr<DB::IMergeTreeDataPart const> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::NamesAndTypesList const&, std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeIndex const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeIndex const> > > const&, std::__1::shared_ptr<DB::ICompressionCodec>, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned long, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, unsigned long> > > const&, unsigned long, bool) @ 0xfa276e9 in /usr/bin/clickhouse
13. DB::MergedBlockOutputStream::MergedBlockOutputStream(std::__1::shared_ptr<DB::IMergeTreeDataPart const> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::NamesAndTypesList const&, std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeIndex const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeIndex const> > > const&, std::__1::shared_ptr<DB::ICompressionCodec>, bool) @ 0xfa278f1 in /usr/bin/clickhouse
14. DB::MergeTreeDataWriter::writeTempPart(DB::BlockWithPartition&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&) @ 0xf967159 in /usr/bin/clickhouse
15. DB::MergeTreeBlockOutputStream::write(DB::Block const&) @ 0xf889378 in /usr/bin/clickhouse
16. DB::PushingToViewsBlockOutputStream::write(DB::Block const&) @ 0xf195c66 in /usr/bin/clickhouse
17. DB::AddingDefaultBlockOutputStream::write(DB::Block const&) @ 0xf19ba19 in /usr/bin/clickhouse
18. DB::SquashingBlockOutputStream::finalize() @ 0xf19b267 in /usr/bin/clickhouse
19. DB::SquashingBlockOutputStream::writeSuffix() @ 0xf19b34d in /usr/bin/clickhouse
20. DB::copyData(DB::IBlockInputStream&, DB::IBlockOutputStream&, std::__1::atomic<bool>*) @ 0xee0cbc0 in /usr/bin/clickhouse
21. DB::NullAndDoCopyBlockInputStream::readImpl() @ 0xf18f111 in /usr/bin/clickhouse
22. DB::IBlockInputStream::read() @ 0xede92cd in /usr/bin/clickhouse
23. void DB::copyDataImpl<std::__1::function<bool ()> const&, std::__1::function<void (DB::Block const&)> const&>(DB::IBlockInputStream&, DB::IBlockOutputStream&, std::__1::function<bool ()> const&, std::__1::function<void (DB::Block const&)> const&) @ 0xee0d16b in /usr/bin/clickhouse
24. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, DB::Context&, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>) @ 0xf4e5329 in /usr/bin/clickhouse
25. DB::HTTPHandler::processQuery(DB::Context&, Poco::Net::HTTPServerRequest&, HTMLForm&, Poco::Net::HTTPServerResponse&, DB::HTTPHandler::Output&) @ 0xfaf9a0c in /usr/bin/clickhouse
26. DB::HTTPHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&) @ 0xfafd166 in /usr/bin/clickhouse
27. Poco::Net::HTTPServerConnection::run() @ 0x122e0753 in /usr/bin/clickhouse
28. Poco::Net::TCPServerConnection::start() @ 0x1231ea0b in /usr/bin/clickhouse
29. Poco::Net::TCPServerDispatcher::run() @ 0x1231ee9b in /usr/bin/clickhouse
30. Poco::PooledThread::run() @ 0x1249d9c6 in /usr/bin/clickhouse
31. Poco::ThreadImpl::runnableEntry(void*) @ 0x12498dc0 in /usr/bin/clickhouse
 (version 20.6.4.44 (official build))

**Comment by den-crane** [comment]
https://github.com/ClickHouse/ClickHouse/blob/master/CHANGELOG.md

20.4.2.9
Added a setting max_server_memory_usage to limit total memory usage of the server.
The setting max_memory_usage_for_all_queries is now obsolete and does nothing.

To avoid OOM, set max_server_memory_usage to lower value, for example 8500000000

To avoid "Memory limit (total) exceeded" re-write a query that cause it. And / or use `max_bytes_before_external_group_by`, `max_bytes_before_external_sort`
