### ISSUE TITLE
About data import

### ISSUE THREAD

**Issue by qinglok** [ClickHouse/ClickHouse#14863]
I have a batch of binary data in RocksDB.
How can I import it into ClickHouse in native mode?

**Comment by den-crane** [comment]
clickhouse-client -t "insert into T format Native" <  file.native

**Comment by den-crane** [comment]
Maybe I misunderstood the question.

Export data from RocksDB to CSV file and import to CH as CSV

clickhouse-client -q "insert into T format CSV" < file.CSV

**Comment by qinglok** [comment]
I am using the mode of "export data from rocksdb to CSV file and import to ch as CSV", but I want to improve the overall speed.

I try to analyze the binary data exported by native mode, but I still can't analyze the rules.

**Comment by den-crane** [comment]
> "export data from rocksdb to CSV file and import to ch as CSV"

can you show `wc file.csv`

1. How many rows in your CSV?
2. What size of CSV
3. How long is the import? `-t`  ` clickhouse-client -tq "insert into T format CSV" < file.CSV `

**Comment by qinglok** [comment]
1.超过百亿行
2.接近500GB
3.导入需要5个小时或更久

**Comment by den-crane** [comment]
1. You can transform CSV to Native using clickhouse-local
   but I don't believe that it has sense. Because it's the same amount of job.
   CSV -> native( clickhouse-local ) -> clickhouse
   CSV -> clickhouse

2. Check the speed difference. 
   Download 1bil rows from CH `clickhouse-client -q 'select * from T limit 100000000 format Native'` > test.native
   clickhouse-client -q 'select * from T limit 100000000 format CSV'` > test.CSV
   Create test table `create table test as T`
   try load and compare the speed.  `clickhouse-client -tq "insert into T format Native" < file.native`
 
3. Try load in parallel by running multiple clickhouse-client (with disabled parallel parsing --input_format_parallel_parsing=0)

**Comment by qinglok** [comment]
I did the test in three ways.

Native export time used 3090s, file size 460,223,132 KB.
Native import time used 4423s.

RowBinary export time used 3519s,  file size 460,706,927 KB.
RowBinary import time used 4673s.

CSV export time userd 9745s, file size 890,289,274 KB.
CSV import time used 8670s.

It should be noted that this CSV is exported from ClickHouse (select * from t). Maybe the sorting of CSV will affect the import speed, but the CSV in the production environment are out of order, and the import speed will be longer than the test.

**Comment by den-crane** [comment]
1. you can develop own application which process data from RocksDB into RowBinary or Native.
   You can get description of RowBinary from CH documentation and Native almost the same as RowBinary the same value encoding but in columns not rows. You can copy Native implementation from JDBC driver or GO-driver.

2. you can use `clickhouse-local` and convert from CSV into Native.

3. You can load CSV in parallel by running multiple clickhouse-client (with disabled parallel parsing --input_format_parallel_parsing=0)

**Comment by qinglok** [comment]
**As for the binary file of native mode, I would like to ask: what is the meaning of the first three bytes?**

**The original record here:**
_id     name  age   borthday
1       linx    28      1993-07-01 00:00:00
2       jens    18      1994-07-01 00:00:00
3       rudy    13      1995-07-01 00:00:00_

**This is a binary file(Hexadecimal display)：**
**_04 03 02_** 69 64 06 53 74  
72 69 6E 67 01 31 01 32  
01 33 04 6E 61 6D 65 06  
53 74 72 69 6E 67 04 6C 
69 6E 78 04 6A 65 6E 73  
04 72 75 64 79 03 61 67  
65 05 55 49 6E 74 38 1C  
12 0D 08 62 6F 72 74 68 
64 61 79 08 44 61 74 65  
54 69 6D 65 80 B8 31 2C  
00 EC 12 2E 80 1F F4 2F 

**What does the first three bytes 04 03 02 mean?**
