### ISSUE TITLE
Init script is already running，start clickhouse-server-20.9

### ISSUE THREAD

**Issue by little-tomato** [ClickHouse/ClickHouse#14861]
I have installed clickhouse with the command:rpm -ivh *.rpm 
clickhouse-client-20.9.1.4571-2.noarch.rpm
clickhouse-common-static-20.9.1.4571-2.x86_64.rpm
clickhouse-server-20.9.1.4571-2.noarch.rpm

then，
sudo service clickhouse-server start
======================
Init script is already running
======================
why？

**Comment by den-crane** [comment]
It seems you used systemd based distro.

Use only systemctl command 

sudo systemctl start clickhouse-server
sudo systemctl stop clickhouse-server
sudo systemctl status clickhouse-server

And don't use `service clickhouse-server` or `/etc/init.d/clickhouse-service`

https://github.com/ClickHouse/ClickHouse/issues/14298

**Comment by little-tomato** [comment]
3ks，it‘s ok now。

**Comment by tcjin** [comment]
i installed clickhouse-service,then i used command 'service clickhouse-server start' and 'systemctl start clickhouse-server', but any of them cann't start clickhouse server.please help me,thanks!
