### ISSUE TITLE
Unable to run clickhouse benchmark using TLS connection

### ISSUE THREAD

**Issue by minaevmike** [ClickHouse/ClickHouse#14878]
Hi,

I'm trying to run clickhouse benchmark tool to our cluster in Yandex Cloud. 

Version
```
$ clickhouse client -V
ClickHouse client version 20.10.1.4658 (official build).
```

When I'm trying to run this query I had very strange error 
```
$ echo " select 1" | clickhouse benchmark --host {{host}} --port 9440 --user {{name}} --password {{pass}} -s
Loaded 1 queries.
DB::Exception: Attempt to read after eof
```

But if I run client tool, instead of benchmark, everything works fine
```
$ echo " select 1" | clickhouse client --host {{host}} --port 9440 --user {{name}} --password {{pass}} -s
1
```

Even if I add `--stacktrace` for benchmark - output still the same. 
I think the problem is located near the TLS connection(I tried to run same client for local instance without TLS and it works fine).

**Comment by Avogar** [comment]
Was fixed in https://github.com/ClickHouse/ClickHouse/pull/17365
