### ISSUE TITLE
Create a UDF in ClickHouse 20.8.1.1

### ISSUE THREAD

**Issue by roycyz** [ClickHouse/ClickHouse#14872]
I have create file under the Function file.And it  compiles in libclickhouse_functions.a.After I update the Clickhouse and run it.it's throw the error DB::Exception: Unknown function sayHello.Is there any else I need to do it,f or running my UDF?

**Comment by sundy-li** [comment]
@roycyz  did you register the function? see `registerFunctions.cpp`

**Comment by roycyz** [comment]
thanks for replaying, I have register it in c source.Like this

**Comment by roycyz** [comment]
factory.registerFunction<FunctionZbTest>(FunctionFactory::CaseInsensitive);

**Comment by roycyz** [comment]
> @roycyz did you register the function? see `registerFunctions.cpp`
thanks for replaying, I have register it in cpp source.Like this factory.registerFunction(FunctionFactory::CaseInsensitive);
