### ISSUE TITLE
clickhouse-local and table with 10K columns

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#14881]
need to convert TSV to Native but schema is too big for command-line...

**Comment by alexey-milovidov** [comment]
```
milovidov@milovidov-desktop:~/work/tmp$ cat metadata/local/test.sql
ATTACH TABLE test (x UInt64 /* long list here */) ENGINE = File(TSV, stdin);

milovidov@milovidov-desktop:~/work/tmp$ ls -lR
.:
drwxrwxr-x 3 milovidov milovidov 4096 сен 16 19:42 metadata

./metadata:
drwxrwxr-x 2 milovidov milovidov 4096 сен 16 19:43 local

./metadata/local:
-rw-r--r-- 1 milovidov milovidov 77 сен 16 19:43 test.sql

milovidov@milovidov-desktop:~/work/tmp$ echo 123 | clickhouse-local --query "SELECT * FROM local.test" -- --path=.
123
```

**Comment by alexey-milovidov** [comment]
You can use `clickhouse-local` on top of predefined catalog as in the example above.
In this catalog, you can have a table with engine File and arbitrary long list of columns.

**Comment by alexey-milovidov** [comment]
`-- --path=.`

Can be also specified with `config.xml` in current directory.

**Comment by filimonov** [comment]
Cool! Didn't know that. BTW - it also means clickhouse-local can produce ready to attach parts. 

Just a side note - may be smth like `--queries-file` (as an alternative for --query) is worth adding both for clickhouse-client and clickhouse-local

**Comment by alexey-milovidov** [comment]
> it also means clickhouse-local can produce ready to attach parts

Yes.
Also it can be used for "maintanence mode" on server.

> Just a side note - may be smth like --queries-file (as an alternative for --query) is worth adding both for clickhouse-client and clickhouse-local

It's a good feature request, worth doing...
