### ISSUE TITLE
Rewrite integration tests and clickhouse-test script to python 3.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#14886]

**Comment by bharatnc** [comment]
@alexey-milovidov I think I can take a stab at this (probably assign to me?)

**Comment by alexey-milovidov** [comment]
Azat already started working on it: https://github.com/ClickHouse/ClickHouse/pull/15007

**Comment by bharatnc** [comment]
> Azat already started working on it: #15007

@alexey-milovidov I did start work on it, but looks like @azat  has made more progress on this. You can probably assign this task to him? Thanks!
