### ISSUE TITLE
datasketches support in clickhouse

### ISSUE THREAD

**Issue by guanlisheng** [ClickHouse/ClickHouse#14893]
(you don't have to strictly follow this form)

**Use case**
we wanted to use the data sketch capability (such as Theta Sketch) to do set operation such as  ∩ ∪ ×.  also expect the data would be exchanged with other query engines such as presto and spark.

**Describe the solution you'd like**
integration with https://datasketches.apache.org/ though clickhouse has HLL sketch today.

**Comment by alexey-milovidov** [comment]
The link to C++ library: https://github.com/apache/incubator-datasketches-cpp

**Comment by alexey-milovidov** [comment]
The library looks Ok, it supports all the required parts of AggregateFunction interface.
(the serialize/deserialize functions may be inefficient)

**Comment by guanlisheng** [comment]
hey @alexey-milovidov,  do we have a rough plan to integrate this c++ library?

**Comment by alexey-milovidov** [comment]
This task looks isolated, it fits nicely to ClickHouse architecture, but there is no high demand for it.
I consider it as an experimental task for external contributors. I just listed it here: https://github.com/ClickHouse/ClickHouse/issues/15065
I expect that someone will be interested in this task (it should be confirmed until November).

**Comment by guanlisheng** [comment]
many thanks and look forward

**Comment by ns-gzhang** [comment]
I'd like to add two use cases from our real scenarios: (1) transfer aggregates from Druid to ClickHouse for migration. The challenge is that the summary data are kept longer than the details and we don't have detailed data anymore and won't be able to get equivalent aggregates in Druid into ClickHouse except using the detailed data, which takes longer time to build up. (2) we have updates and there is no way to maintain the aggregates such as uniqState (using HLL) for these updates with materialized views. ThetaSketch can help out.

**Comment by guanlisheng** [comment]
Agreed with @ns-gzhang and we are facing similar issues especially when used multiple tiered query engine solutions.

**Comment by pingyu** [comment]
I'd like to have a try.
Could you please assign to me ? @alexey-milovidov

**Comment by spearson23** [comment]
We also need this functionality.  Is this being worked on?  If not, I may be able to get someone to help.

**Comment by alexey-milovidov** [comment]
@spearson23 
As far as I know @RedClusive is also started to work on this task for his coursework.
But don't be afraid - this task has multiple loosely related parts and it can be tried by multiple developers concurrently.

**Comment by pingyu** [comment]
I'm still working on this task, and I'm sorry for the late...
I will speed up.

**Comment by durchgedreht** [comment]
+1 Highly interested in this as well!

**Comment by pingyu** [comment]
I think we can split this issue to the following subtasks:

- [ ] cmake
- [ ] union (uniqThetaSketch)
- [ ] intersection & difference (by aggregation combinators ?)
- [ ] function to convert Array(UInt8) to intermediate state (to be used for Merge/Intersetion/Difference, to exchange with other query engines)

What do you think ? @alexey-milovidov

**Comment by dengc367** [comment]
we need this functionality, is it working now on latest release?

**Comment by alexey-milovidov** [comment]
@pingyu Ok.
So, @spearson23 and @RedClusive can take some parts if they are interested.

**Comment by alexey-milovidov** [comment]
@dengc367 No, it's in early stage of development.
BTW, what sketches do you need the most?

ClickHouse already have multiple sketches for COUNT DISTINCT, quantiles and topK.

**Comment by fpacifici** [comment]
+1 We would be very interested in this as well.  Specifically being able to exchange sketches with clickhouse.

Our use case includes a  very high load data ingestion pipeline where it would be desirable to aggregate sets or quantiles close to the client to reduce the amount of data transferred and being able to store those sketches into Clickhouse. We would not have the individual data points at this stage anymore. Then ideally we would being able to merge them at query time or in materialized views.

**Comment by dengc367** [comment]
> @dengc367 No, it's in early stage of development.
> BTW, what sketches do you need the most?
> 
> ClickHouse already have multiple sketches for COUNT DISTINCT, quantiles and topK.

I need the sketches like the `Intersect/Except` functionality in Presto 。

**Comment by alexey-milovidov** [comment]
datasketches library is not production ready and cannot be used without thorough code audit and bugfixing:
https://github.com/apache/datasketches-cpp/issues/210

**Comment by alexey-milovidov** [comment]
`uniqTheta` has been added but nothing more.

**Comment by einvince** [comment]
@alexey-milovidov 
https://github.com/apache/datasketches-cpp/issues/210 have been closed, is there any plan to support **intersection & difference**

**Comment by pzhdfy** [comment]
we add UniqThetaSketch support set operation such as union/intersect/not
in https://github.com/ClickHouse/ClickHouse/pull/39919
