### ISSUE TITLE
Syntax error on 4.0E-323

### ISSUE THREAD

**Issue by bgranvea** [ClickHouse/ClickHouse#14909]
**How to reproduce**
I have issues while manipulating the value 4.0E-323. I can indirectly generate it with toFloat64:

```
root@f549d5b3bca6:/# clickhouse-client
ClickHouse client version 20.5.4.40 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 20.5.4 revision 54435.

f549d5b3bca6 :) select 4.0E-323

Syntax error: failed at position 8:
[...]

f549d5b3bca6 :) select toFloat64('4.0E-323')

SELECT toFloat64('4.0E-323')

┌─toFloat64('4.0E-323')─┐
│                4e-323 │
└───────────────────────┘
```

The smallest number which doesn't generate a syntax error seems to be around 3.0E-308 which must correspond to the limit of 2.2250738585072014E-308 that I find on some pages for C++ double type.

I'm confused by this limit: we manipulate 4.0E-323 in our Java programs with a native 8 bytes double type, so I was expecting the limit to be the same. And why does toFloat64('4.0E-323') seem to work?

**Comment by alexey-milovidov** [comment]
The IEEE double precision floating point numbers less than 2^-1022 are called "subnormal" (or "denormal") numbers.
They are supported by CPU but they can lead to significant slowdown:
https://randomascii.wordpress.com/2012/05/20/thats-not-normalthe-performance-of-odd-floats/

There are two different parsers in your examples.
When number appears as literal in SQL query, we are using `strtod` function from C, that returns `ERANGE` when subnormal number is encountered (and we consider it as syntax error).
When number is parsed from string or from input text format, we use more optimized parser that does not treat subnormals in any special way.

Maybe we should not consider subnormal numbers as syntax error?

**Comment by bgranvea** [comment]
Thanks for your response. We are using these special values as a kind of hack to store in a single Float64 either a "normal" value or an error flag. 

I don't know what should be the correct behavior for Clickhouse. Anyway we might consider other options to achieve what we want.

**Comment by alexey-milovidov** [comment]
`nan` should suffice as a flag.
