### ISSUE TITLE
Scalar subquery limitation

### ISSUE THREAD

**Issue by bgranvea** [ClickHouse/ClickHouse#14914]
From what I understand, Clickhouse doesn't support "correlated" scalar subqueries such as:

```
SELECT
   employee_number,
   name,
   (SELECT AVG(salary) 
      FROM employees
      WHERE department = emp.department) AS department_average
   FROM employees emp
```

Can you confirm?

**Comment by den-crane** [comment]
CH does not support this.


https://clickhouse.tech/docs/en/sql-reference/ansi/

E061-13 | Correlated subqueries | No

**Comment by alexey-milovidov** [comment]
I confirm.

The implementation of correlated subqueries (and only for the case when they can be rewritten to JOINs) is not in current roadmap and most likely will be planned for 2021.
