### ISSUE TITLE
Prevent too heavy translation units.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#14925]
Limit the amount of CPU time and memory for building every translation unit.

For example: limit CPU time to 600 seconds and memory to 10 GiB.
(these are conservative numbers, we can lower them down as soon as possible)

It should be activated in CI for release build (with CMake option) and not activated by default (developers may have slow CPUs).

It's possible to do with ulimit:
`ulimit -m 10000000 -t 600`

**Comment by alexey-milovidov** [comment]
How to pass it to every compiler invocation?

Do we need a shell script wrapper
```
#!/bin/sh
ulimit -m 10000000 -t 600
clang $@
```
or there is something more simple?

**Comment by alesapin** [comment]
Maybe we can do it similar to `ccache` compiler launcher, but using `timeout 600 ...` https://github.com/clickhouse/ClickHouse/blob/manual-write-duplicate-parts-to-replicas/cmake/find/ccache.cmake#L33-L34?

**Comment by alexey-milovidov** [comment]
`timeout` will calculate wall clock time - it's unreliable.

**Comment by alexey-milovidov** [comment]
`prlimit --rss=10000000 --cpu=600`

**Comment by alexey-milovidov** [comment]
```
milovidov@milovidov-desktop:~/work/ClickHouse/utils$ time prlimit --rss=10000000 --cpu=1 clickhouse-local --query "SELECT count() FROM system.numbers"
Killed

real    0m0,999s
user    0m0,869s
sys     0m0,137s
milovidov@milovidov-desktop:~/work/ClickHouse/utils$ time prlimit --rss=10000000 --cpu=1 clickhouse-local --query "SELECT count() FROM system.numbers_mt"
Killed

real    0m0,194s
user    0m0,730s
sys     0m0,251s
```
