### ISSUE TITLE
Why not compact multiple files in a part into a single file?

### ISSUE THREAD

**Issue by yiguolei** [ClickHouse/ClickHouse#14927]
I am a new user to Clickhouse.
I find there are too many files under the folder data/default/lineorder/all_99_99_0.  
It seems that there is a single file for every column. Why not compact there files into a single file like parquet or orc file?

**Comment by den-crane** [comment]
And how to add or drop / modify  column without re-writing this file?
And I guess it would much more seek operation when need to read single column.
