### ISSUE TITLE
Tasks stuck in tasks pool

### ISSUE THREAD

**Issue by simplemagik** [ClickHouse/ClickHouse#14931]
I Altered table and deleted some rows
Then (i think before alter finished) i run
OPTIMIZE TABLE FINAL on this table (very large one).
Ch tried to execute it, but hit 300s timeout
Then tired to interrupt query

So, i got locked table and 16 tasks in background

Do i have any method to force kill these tasks?

**Comment by simplemagik** [comment]
maybe i could delete mutation file from 
clickhouse/data/raw/<table> directory?
will it help?

**Comment by den-crane** [comment]
if table is not Replicated then
```
system stop merges TABLE;
system start merges TABLE;
```
if it replicated then need to remove this task from ZK before stop/start

**Comment by simplemagik** [comment]
seems like nothing changed
also notices that
SELECT * FROM system.mutations
also timeouts

maybe it's a hint that mutations are still in progress or stuck?

**Comment by simplemagik** [comment]
also 
SELECT * FROM merges
returns 0
so there is no merges runnig

**Comment by simplemagik** [comment]
deleting file with mutation on disk helped

**Comment by den-crane** [comment]
OPTIMIZE TABLE FINAL  has no relation to mutations

**Comment by den-crane** [comment]
https://clickhouse.tech/docs/en/sql-reference/statements/kill/#kill-mutation

kill mutation where not is_done
