### ISSUE TITLE
How to split a  data area by an  accumulation value 

### ISSUE THREAD

**Issue by somewheve** [ClickHouse/ClickHouse#14930]
I ask it on  StackOverflow but seems no one reply to me 

Here is the description with code. 

https://stackoverflow.com/questions/63934851/how-to-resample-volume-bar-in-clickhouse

**Comment by den-crane** [comment]
I don't understand your question. 

Check https://clickhouse.tech/docs/en/sql-reference/aggregate-functions/combinators/#agg-functions-combinator-resample

**Comment by somewheve** [comment]
[ 10, 120, 300,  20,  136, 70, 60, 20]

will  be split  into  [ 10, 120, 300]  [20, 136],  [70, 60, 20]  if value is set to 150. 

I mean the sum of every array  will more than 150,   you can see the end of this issue [issue](https://github.com/ClickHouse/ClickHouse/issues/13493)

**Comment by den-crane** [comment]
I think it's impossible now in CH.

**Comment by somewheve** [comment]
alright......
