### ISSUE TITLE
Low uniqMerge performance issue in Materialized aggregatingMergetree.

### ISSUE THREAD

**Issue by moweonlee** [ClickHouse/ClickHouse#14941]
I have tried to figure out the low performance problem in MV aggregatingMergeTree.

I think I have read many important documents in your site to understand how aggregatingMergeTree engine works

But the low performance of my case is making me hard to understand the reason.

So I'd like to share this issue with engineers  and solve the problem.

## # Table information 

- First table
![image](https://user-images.githubusercontent.com/16459517/93484389-cfed2280-f93c-11ea-9e00-d9efef8d2bdb.png)

- The second table is materialized view with aggregatingMergeTree engine. 
We use this table to get the number of users in every hour with high performance.

![image](https://user-images.githubusercontent.com/16459517/93484426-dbd8e480-f93c-11ea-839d-5c00b7d925f6.png)

The each data is looking like this.

And we use array to track the users who visited my site in certain period of time ( 10seconds ).

┌───────date─┬───────────starttime─┬─────────────endtime─┬─hour─┬─minute─┬─stname─┬─origin─────────────────────────────┬─age───┬─gender─┬─os──────┬─browser────┬───pv─┬─users──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ 2020-09-14 │ 2020-09-14 00:00:00 │ 2020-09-14 00:00:10 │    0 │      0 │ 0      │ -                                  │ 30-34 │ m      │ iOS     │ CHROME   │    6 │ ['USER-1','USER-212','USER-9992','USER-2221','USER-341223'] 

One thing that I'm really involving is to find the reason of low performance of MV query.

You can see how they are performing in the below screen. 

MV had merged data with same sorting.

So the number of row to calculate is significantly decreased than no-MV table.

But processing time is so slow in MV table. 

Could you explain the reason of this pre-merged and summarized tables's low performance ?

![image](https://user-images.githubusercontent.com/16459517/93485713-522a1680-f93e-11ea-8a2b-2f4a9d702833.png)

**Comment by den-crane** [comment]
It seems your aggregatingMergeTree has only 2 times fewer rows than source table.
Your aggregatingMergeTree aggregates almost nothing because ORDER BY is long.
uniqMerge works slower than uniq.

Make aggregatingMergeTree with shorter ORDER BY and 100 time fewer rows then you get boost.

**Comment by moweonlee** [comment]
Thank you for your response. 

Now I understand that my data in aggregatingMergeTree  is not  well merged because I have so many columns in ORDER BY.

By the way in my application, every column should be provided to get the result except for the time unit change. 

Only thing that I want to be merged is time unit from minute to hour.



 Since I have understood every rows with same sort key are merged into single row in aggregating merge tree, reducing columns in 'ORDER BY' must be mixing data not to be distinguished well in my application. 

So I'm not sure if I can use aggregatingMergeTree in my application now .

Do you the performance that I'm getting from source table is good enough ?

Thank you in advance.

**Comment by den-crane** [comment]
I think you don't need MV & aggregatingMergeTree. You can't get any gain from it.
Just query your original table.

**Comment by moweonlee** [comment]
Thank you very much for your help 👍

**Comment by dongjiyan** [comment]
"When using the uniqMerge function with a small amount of data, it's still very slow. Is there a better solution? Trace log is as follows:"


```log
 2024.06.13 15:34:59.879647 [ 24360 ] {1ff99dc3-4935-45b4-88ee-90d195cd05ee} <Trace> AggregatingTransform: Aggregated. 10171 to 191 rows (from 759.19 KiB) in 3.244068037 sec. (3135.261 rows/sec., 234.02 KiB/sec.)
 2024.06.13 15:34:59.917622 [ 24063 ] {1ff99dc3-4935-45b4-88ee-90d195cd05ee} <Trace> AggregatingTransform: Aggregated. 18865 to 222 rows (from 1.47 MiB) in 3.28185927 sec. (5748.266 rows/sec., 457.39 KiB/sec.)
 2024.06.13 15:35:01.689157 [ 44131 ] {1ff99dc3-4935-45b4-88ee-90d195cd05ee} <Trace> AggregatingTransform: Aggregated. 41496 to 246 rows (from 2.35 MiB) in 5.053388591 sec. (8211.520 rows/sec., 477.08 KiB/sec.)
 2024.06.13 15:35:05.434664 [ 24282 ] {1ff99dc3-4935-45b4-88ee-90d195cd05ee} <Trace> AggregatingTransform: Aggregated. 70195 to 276 rows (from 5.40 MiB) in 8.799120537 sec. (7977.502 rows/sec., 628.62 KiB/sec.)
 2024.06.13 15:35:06.125184 [ 37946 ] {1ff99dc3-4935-45b4-88ee-90d195cd05ee} <Trace> AggregatingTransform: Aggregated. 86522 to 257 rows (from 6.62 MiB) in 9.489607661 sec. (9117.553 rows/sec., 713.83 KiB/sec.)
 2024.06.13 15:35:06.592197 [ 42246 ] {1ff99dc3-4935-45b4-88ee-90d195cd05ee} <Trace> AggregatingTransform: Aggregated. 98422 to 265 rows (from 8.00 MiB) in 9.956632149 sec. (9885.069 rows/sec., 822.91 KiB/sec.)
 2024.06.13 15:35:12.304255 [ 37547 ] {1ff99dc3-4935-45b4-88ee-90d195cd05ee} <Trace> AggregatingTransform: Aggregated. 172032 to 287 rows (from 15.09 MiB) in 15.668449753 sec. (10979.516 rows/sec., 986.44 KiB/sec.)
 2024.06.13 15:35:17.936633 [ 24235 ] {1ff99dc3-4935-45b4-88ee-90d195cd05ee} <Trace> AggregatingTransform: Aggregated. 195035 to 280 rows (from 16.61 MiB) in 21.300989998 sec. (9156.147 rows/sec., 798.35 KiB/sec.)
 2024.06.13 15:35:25.969267 [ 24866 ] {1ff99dc3-4935-45b4-88ee-90d195cd05ee} <Trace> AggregatingTransform: Aggregated. 269465 to 300 rows (from 22.46 MiB) in 29.333556935 sec. (9186.237 rows/sec., 784.01 KiB/sec.)

```
