### ISSUE TITLE
Add write ahead log to buffer table engine to avoid data loss during machine crash.

### ISSUE THREAD

**Issue by yiguolei** [ClickHouse/ClickHouse#14976]
We use buffer table engine as the write cache for ordinary table to reduce small files during load. But data in buffer table engine is lost during machine crash.
Does clickhouse have a plan to add wal to buffer table engine to solve this problem?

**Comment by nvartolomei** [comment]
ClickHouse recently added support for in memory parts for MergeTree* engines (these in theory would make it unnecessary to have a Buffer table for batching writes) #10697. In-memory parts use a WAL.

**Comment by alexey-milovidov** [comment]
Yes, it is integrated into MergeTree tables - it should remove the need for Buffer. And we don't plan to extend Buffer tables.
