### ISSUE TITLE
Is it possible to add index in MaterializeMySQL table?

### ISSUE THREAD

**Issue by liangli1213** [ClickHouse/ClickHouse#14979]
I have 2 questions:

1. I have index in my MySQL table, if it has been synced to ClickHouse, will the index also be created in the ClickHouse's table?
2. Is it possible to add index in MaterializeMySQL table, after the replication has been setup?

@BohuTANG @zhang2014 , if you know the answer, would you please reply? thanks.

**Comment by tavplubix** [comment]
1. "indexes" in MySQL and "indexes" in ClickHouse are very different things. However, ClickHouse automatically choose `ORDER BY` and `PARTITION BY` keys for synced table when it rewrites the `CREATE` query from MySQL syntax to ClickHouse syntax. 
2. No, it's not possible to `ALTER` MaterializeMySQL table manually. Probably we should add a setting to allow it (may be useful for adding data skipping indexes or changing MergeTree settings, for example).

**Comment by zhang2014** [comment]
@liangli1213 @tavplubix Yes, we have this plan. and that should happen in the near future. automatically convert MySQL's secondary index to ClickHouse's skipping index(index type using settings, default it is bloom_filter)

**Comment by liangli1213** [comment]
@tavplubix , thanks for your reply, I begin to use ClickHouse not so long, this afternoon, I make replication from MySQL to ClickHouse successfully, and do a perf test for one of the table.

I found the perf is very low, a query will take 40s, that is because I removed all index from the MySQL table before doing the replication, so do you think if I re-creating the index on MySQL side, then re-establish replication to ClickHouse, the indexing info will also be synced to ClickHouse, then my query will turn to more faster?

**Comment by liangli1213** [comment]
I have one primary key and 2 index in my table, as follows:
```
PRIMARY KEY (`id`),
KEY `vendor_feature_checkDate` (`vendor`,`feature`,`checkDate`),
KEY `site_vendor_checkDate` (`site`,`vendor`,`checkDate`)
```
And ClickHouse convert it to order by clause:
```
ORDER BY (feature, checkDate, site, vendor, id)
```
So my question is:
1. When doing query, only follow the order after where ( WHERE feature = 'aaa' AND checkDate = 'bbb'), will reduce the scanning rows?
2. If ClickHouse was able to convert MySQL's secondary index to ClickHouse's skipping index, will the query reduce the scanning rows?

**Comment by BohuTANG** [comment]
For your question:
A1: 
right, ClickHouse OrderBy is the only physical sort order on the disk. 
But we can use MaterializedView to make many different tables with different OrderBy as MySQL index does.
Here some info about MaterializedView:
https://bohutang.me/2020/08/31/clickhouse-and-friends-materialized-view/

A2:
This was mentioned in the comments above, it is possible to do it.

**Comment by liangli1213** [comment]
@BohuTANG , thanks for your reply, I shall open a feature request since I really need this conversion.

**Comment by liangli1213** [comment]
@BohuTANG , as you mentioned Materialized View, and I have a requirement, to count the unique user name on daily basis for using a product, the usage data is generated randomly by time series, as per the description of Materialized View table, it only process increment data, so Materialized View seems not meet my requirement, do you agree?

**Comment by BohuTANG** [comment]
Will the user name be deleted or updated?

**Comment by liangli1213** [comment]
There is always new record coming into table, but the username is unpredictable, it maybe appeared in same day, or the first time to appear today, the result I need is the unique username's count on daily basis.
