### ISSUE TITLE
replicated_deduplication_window_seconds is ignored in some cases

### ISSUE THREAD

**Issue by FLPhoenix** [ClickHouse/ClickHouse#14999]
Setting replicated_deduplication_window_seconds for a ReplicatedMergeTree table does not actually mean deduplication will be disabled for all blocks older than replicated_deduplication_window_seconds. This may sometimes cause unpredictable endless deduplication of blocks which are not to be deduplicated.

The reason is most probably https://github.com/ClickHouse/ClickHouse/blob/20.6/src/Storages/MergeTree/ReplicatedMergeTreeCleanupThread.cpp
line 327 - CH calculates "age" of the block from the last inserted one, not the current time. Which makes it impossible to avoid deduplication for the last inserted block, or a group of last inserted blocks, if they were inserted close to each other in time. Having all that, there is a chance (we've met it in production) that some fresh pieces of data will never be inserted, if they weren't inserted from the first try.

**How to reproduce**

1. Create any ReplicatedMergeTree table, and make sure replicated_deduplication_window_seconds is set to 1 and cleanup_delay_period is set to 1 as well.
2. Insert any row. The table should now have 1 row.
3. Wait for 5-10 seconds and insert the same row. Since you waited for more than 1 + 1 seconds, it shoud NOT be deduplicated, corresponding zookeeper node must be deleted, and you should have more than 1 row. But it does not work, this row is going to be deduplicated always, unless you insert another one. 

* CH version 20.6.4.44
* replicated_deduplication_window_seconds=600, cleanup_delay_period=30 (when met a bug; use 1 and 1 for quick reproducing)

**Expected behavior**
Any row or block of rows must be inserted without deduplication, if it was previously inserted more than replicated_deduplication_window_seconds ago.

**Additional context**
There is a test on this setting: https://github.com/ClickHouse/ClickHouse/blob/97f2a2213e754ba25dabba4bc8ddf507cd67660c/tests/integration/test_extreme_deduplication/test.py but it is incorrect, it only asserts that the 1 row is no longer deduplicated, although after 2 seconds of sleep both rows must be insertable again.

The case met in production: 
Data consists of 2 blocks. One is inserted successfully, the other one is not, due to a network issue. So, the piece of data is incomplete. On the next try, the same software drops previously inserted rows, then inserts both 2 blocks, now both of them successfully, but the 1st one is deduplicated. So the data is once again incomplete. On the third try all 2 blocks are deduplicated, and the task cannot be completed. Because of the described bug, at least one of the blocks will always be deduplicated, and the task will never be completed.

**Comment by den-crane** [comment]
STR:
```
CREATE TABLE Repl
(
    `A` Integer,
    `S` String
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/testxxx', 'changeme')
ORDER BY A
SETTINGS replicated_deduplication_window_seconds = 3, replicated_deduplication_window = 5555555;

insert into Repl values(1,'');

select sleep(3) from numbers(20) settings max_block_size=1 format Null;

insert into Repl values(1,'');

select * from Repl

┌─A─┬─S─┐
│ 1 │   │ <-------    expected  2 rows.
└───┴───┘



insert into Repl values(2,'');
select sleep(3) from numbers(20) settings max_block_size=1 format Null;
insert into Repl values(1,'');
SELECT *
FROM Repl

┌─A─┬─S─┐
│ 1 │   │
└───┴───┘
┌─A─┬─S─┐
│ 2 │   │
└───┴───┘
┌─A─┬─S─┐
│ 1 │   │
└───┴───┘
```

design of replicated_deduplication_window_seconds not obvious 
unexpected behavior / incorrect incomplete documentation

**Comment by alexey-milovidov** [comment]
The original intent of the developer was to count time from the insertion time, not from real time
-- to keep more nodes instead of less.

Actually the intent is to keep as many deduplication nodes as possible (so ideally, deduplication will work forever) and the setting exists only to lower the amount of nodes in ZooKeeper.

So, the logic:
- we keep nodes at least for specified time;
- if we keep slightly more nodes than expected, it is Ok;
- no guarantees that after specified time deduplication stop to work;
- even if we try to cleanup nodes as soon as possible, it still can be delayed, because it happens asynchronously in background thread.

Resolution:
- not a bug, but incorrect expectations on behavious;
- this behaviour should be stated in the docs.

**Comment by alexey-milovidov** [comment]
> On the next try, the same software drops previously inserted rows

Do you mean dropping rows by ALTER DELETE?
