### ISSUE TITLE
Convert MySQL index to ClickHouse data skipping index

### ISSUE THREAD

**Issue by liangli1213** [ClickHouse/ClickHouse#15021]
So far ClickHouse convert both primary key and key to 'order by' clause, it is not accurate, in case there are multi key in the MySQL table, if the where condition not follow 'order by' order, query will be very slow.

So it is necessary to convert the original index in MySQL table into ClickHouser table.

And also, Not Null is not necessary for columns in the MySQL index, it should be the same for ClickHouse (please help confirm).

**Comment by liangli1213** [comment]
@zhang2014 @BohuTANG , I found PARTITION are set as below after doing MaterializeMySQL convert, so how the number comes? is this by desired?

activity.sql:PARTITION BY intDiv(id, 4294967)
checkins.sql:PARTITION BY intDiv(id, 18446744073709551)
checkouts_kpit.sql:PARTITION BY intDiv(id, 18446744073709551)

**Comment by liangli1213** [comment]
And I have another question, if I delete records from MySQL, will the records also be deleted in ClickHouse?

**Comment by BohuTANG** [comment]
A1:
The code for the conversion strategy from MySQL to ClickHouse is here:
https://github.com/ClickHouse/ClickHouse/blob/master/src/Interpreters/MySQL/InterpretersMySQLDDLQuery.cpp#L254-L282

4294967/18446744073709551/18446744073709551 is the max value of UInt[*] divided by 1000.

A2:
The current deletion in MaterializeMySQL storage is just a marker(we add a virtual column `_sign`: 0 marks deleted and 1 is normal insertion), it does not remove the datas on disk actually, but we filter it on read:
https://github.com/ClickHouse/ClickHouse/blob/master/src/Storages/StorageMaterializeMySQL.cpp#L74-L78

We add a filter expression to the AST,  in SQL it formats as `WHERE _sign=1` .

**Comment by liangli1213** [comment]
@BohuTANG for your A2, do you have plan to let ClickHouse to retrieve the removed row? so space can be released on disk.

**Comment by zhang2014** [comment]
Yep, that's is we plan to do

https://github.com/ClickHouse/ClickHouse/issues/4006#issuecomment-657486437

- [ ]  Add gc thread for remove deleted rows

**Comment by liangli1213** [comment]
@zhang2014 , many thanks.
