### ISSUE TITLE
Intern tasks 2020/2021

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#15065]
This is the list of proposed tasks. It is to be extented. You can propose more tasks.
You can also find the previous list here: https://gist.github.com/alexey-milovidov/4251f71275f169d8fd0867e2051715e9

The tasks should be:
- not too hard (doable within about a month) but usually not less than a week;
- not alter some core components of the system;
- mostly isolated, does not require full knowledge of the system;
- somewhat interesting to implement or have some point of research;
- not in critical path of our roadmap (ok to be throwed away after a year);
- most of them are for C++ developers, but there should be also tasks for frontend developers or tools/research that only require Go/Python/whatever;
- some tasks should allow team work;
- cover various skills, e.g. system programming, algorithm knowledge, etc...

### :wastebasket: Advanced methods of test coverage calculation with LLVM compiler infrastructure

This topic is booked by Michael Kot @myrrc.
Cancelled.

We want to calculate test coverage for each single test (we have about 2500 functional tests). It will allow to answer questions like: what tests cover this file / part of code / function; what tests are the most relevant for the code (something like TF*IDF metric); what code is covered by this test; what is the most relevant/specific code for this test...

The task is challenging, because the default format for generated test coverage data is too heavy (sparse), flushing and analyzing it for every test is too heavy. But LLVM compiler infrastructure has tools to implement our own custom coverage (`-fsanitize=coverage`, `-fxray-instrument`).

As an extension of this task, we can also implement lightweight runtime tracing (or tracing profiler).

### :rocket: PostgreSQL table engine
Done

This topic is booked by Ksenia Sumarokova @kssenii.

ClickHouse can interact and process data from various data sources via table functions and table engines. We already have multitude of them: ODBC, JDBC, MySQL, MongoDB, URL... With ODBC table function it's possible to talk to any ODBC compatible DBMS, including PostgreSQL. But it is less efficient and less convenient than using native PostgreSQL driver to interact with PostgreSQL.

The task is to add native support for PostgreSQL. Interesting detail is to add proper support for Array data types that PostgreSQL has. We should also implement support for PostgreSQL as dictionary source. As an extension to this task we can also investigate performance issues with Poco::ODBC client library and replace it to nanodbc. If everything will be alright we can also consider implementing replication from PostgreSQL to ClickHouse like `pg2ch` does.

### :hourglass: Efficient reading of subcolumns from tables; flexible serialization formats for a single data type
Review stage, almost done.

This topic is booked by Anton Popov @CurtizJ 

See #14196 

### :rocket: Implementation of SQL/JSON in ClickHouse
Done.

Booked by @l1tsolaiki, @ltybc-coder

Modern SQL:2016 standard describes support for querying and managing JSON data with SQL. It's quite sophisticated - it includes mini-language like JSON Path.

ClickHouse already has support for querying JSON with simdjson library. This library has support for JSON Pointer API. But it does not match SQL/JSON. We have to parse and interpret the SQL/JSON language and map it to simdjson API.

### :hourglass: Table constraints and hypothesis on data for query optimization
Review stage, almost done.

Booked by Nikita Vasilev @nikvas0 

ClickHouse has support for table constraints, e.g. `URLDomain = domain(URL)` or `isValidUTF8(Title)`. Constraints are expressions that are checked on data insertion. We can also use constraints for query optimization. Example: if there is a constraint that `URLDomain = domain(URL)` and there is an expression `domain(URL)` in the query, we can assume that constraint is true and replace `domain(URL)` to `URLDomain` if it will be easier to read and calculate. Another example: simply replace `isValidUTF8(Title)` to `1`.

We can implement support for other two notions similar to constraints: "assumptions" and "hypothesis". "Assumption" is similar to constraint: if the user write `ASSUMPTION URLDomain = domain(URL)` in the table definition, we don't check it on insert but still use it for query optimization (like constraint). "Hypothesis" is an expression that is checked on insertion but it's permitted to be false. Instead we will store the result: whether the hypothesis hold or not - as very lightweight index. This index can be used for query optimization when hypothesis was hold.

### :hourglass: Schema inference for text formats
Intermediate stage, will continue.

Booked by Igor Baliuk, @lodthe
Continued by @Avogar 

Given first chunk of data in TSV, CSV or JSON formats, figure out what table structure (data types) is the most appropriate for this data. Various tweaks and heuristics will be involved.

https://github.com/ClickHouse/ClickHouse/issues/14450

### :wastebasket: Advanced compression methods in ClickHouse
The task is done with about 50% finished.

Booked by Abi Palagashvili (MSU)

ClickHouse has support for LZ4 and ZSTD as generic compression methods. The choice of these particular methods is justified: these methods are pareto-optimal for compression level and speed across well known libraries. Nevertheless, there exist less well known compression libraries that can be somewhat better in certain cases. Among potentially faster there are: Lizard, LZSSE, density. Among more strong there are: bsc, csc, lzham. The task is to try and explore these libraries, integrate them to ClickHouse, make a comparison on various datasets.

Extensions to this task: reseach zlib compatible libraries (we have zlib-ng but it has unsatisfactoring quality); add support for Content-Encoding: zstd in HTTP interface and https://github.com/ClickHouse/ClickHouse/issues/8828

### :hourglass: Integration of ClickHouse with Tensorflow
Intermediate stage, the status is questionable.

Booked by Albert @Provet.

Pre-learned models can be plugged in to ClickHouse and made available as functions. We have similar feature for Catboost.

### :rocket: Integration of streaming data sketches in ClickHouse
The task is done with about 25% finished.

Booked by Ivan Novitskiy, @RedClusive

Data sketches (also known as probablistic data structures) are data structures that can give approximate answer while using less memory or computation than with precise answer. We already have implemented the most demanded data sketches in ClickHouse: we have four variants of approx. count distinct and several variants of approx. quantiles. But there are much more unexplored interesting data structures worth trying.

### :rocket: Data processing with external tools in streaming fashion
Intermediate stage, will continue.

Booked by Kilill Shyrma, @ruct
Done by @kitaisreal 

The user may write a program that will accept streams of serialized data to stdin (or multiple streams at several file descriptors), process the data and provide serialized result to stdout. We can allow to use these programs as table function. Table function may accept several SQL queries as arguments, prepare file descriptors, connect them with the program and pipe serialized data into them. This is similar to "map" in "mapreduce" model. It is intented for complex calculations that cannot be expressed in SQL.

There are various options how these programs can run: preinstalled programs available on server (easy part); third-party programs on blob-storage (s3, HDFS) that must be run in constrained environment (Linux namespaces, seccomp...)

### Caching of deserialized data in memory on MergeTree part level

**Available**

Implement a new caching layer. If data part is read as a whole (all rows but maybe subset of columns), cache deserialized blocks in memory. This will make performance of MergeTree tables the same as Memory tables.

Extension to this task is to research various cache eviction algorithms.

### Limited support for correlated subqueries in ClickHouse

**Available**

Figure out the subset of correlated subqieries that can be rewritten to JOINs and implement support for them via query rewrite on AST level.

### :rocket: Implementation of subquery operators in ClickHouse
Done.

Booked by Kirill Ershov.
Continued by @kssenii 

Implement INTERSECT, EXCEPT and UNION DISTINCT operators (easy part). Then implement comparison with ANY/ALL of subquery and EXISTS subquery.

### Implementation of GROUPING SETS in ClickHouse
Review stage.

Booked by Maksim Sipliviy, @MaxTheHuman.
Continued by @KochetovNicolai 

GROUPING SETS is the way to perform multiple different aggregations in a single pass within a single query.

### :wastebasket: Refreshable materialized views and cron jobs in ClickHouse
Cancelled.

Booked by Artem Starantsov.

### :hourglass: User defined data types in ClickHouse
Intermediate stage.

\+ User defined functions with SQL expressions.

Booked by Andrei Staroverov @Realist007
Continued by @kitaisreal 

### Limited support for unique key constraint

**Available**

Unique key constraint assures that there is only one row for some user defined unique key. BTree + in memory Hash Table + Bloom Filter can be used as a data structure for deduplication. It is very difficult to implement proper support for unique key constraint for replicated tables. But it can be implemented for non-replicated MergeTree and for ReplicatedMergeTree in local fashion (data is deduplicated only if inserted to the same replica) - it will have some limited use.

### :rocket: YAML configuration for ClickHouse

Done.

Booked by Denis Bolonin, @BoloniniD.

Some people hate XML. Let's support YAML for configurations files, so XML and YAML can be used interchangingly (for example, main config can remain in XML and config.d files can be provided in YAML). There should be a mapping from YAML to XML features like attributes.

https://github.com/ClickHouse/ClickHouse/issues/3607

### :rocket: Improvements for data formats and the clickhouse-local tool

Low percentage of completeness, will continue.

Booked by Egor Savin @Amesaru
Done by @kssenii 

Output in CapNProto format. Proper support for Arrays in Parquet format. Allow to multiple read from stdin in clickhouse-local if stdin is seekable #11124. Interactive mode in clickhouse-local.

### :hourglass: Incremental data aggregation in memory

Review stage.

Booked by Arthur Petukhovsky.
Continued by @KochetovNicolai 

ClickHouse already has support for incremental aggregation (see AggregatingMergeTree). We can provide an alternative way that can sustain higher query rate, can be used for JOINs and dictionaries efficiently, in price of lost persistency.

When ClickHouse executes GROUP BY it creates data structure in memory to hold intermediate data for aggregation. This data structure only lives for query time and is destroyed when query finished. But we can hold aggregation data in memory and allow to incrementally feed more data into it and also allow to query it as key-value table / JOIN with it / use it as a dictionary. Typical usage example is antifraud filter that need to accumulate some statistics to filter data.

### :rocket: Natural language processing functions in ClickHouse

Done.

Booked by Nikolai Degterinskiy.

Add functions for text processing: lemmatization, stop word filtering, normalization, synonims extension. Look for Elasticsearch and Sphinxsearch for examples.

### Embedded log viewer in ClickHouse

**Available**

A task for frontend developer. Create a single page application that will allow to quickly navigate, search and filter through ClickHouse system.text_log and system.query_log tables. The main goal is to make the interface lightweight, beautiful and neat.

### Implementation of a table engine to consume application log files in ClickHouse

Not started, but still relevant.

Booked by Flynn @ucasFL 

ClickHouse has support for subscription and streaming data consumption from message queues: Kafka, RabbitMQ and also recently, from MySQL replication log. But the most simple example of streaming data - is append-only log on local filesystem. We don't have support to subscribe and consume logs from simple append-only file (generated by some third-party application) and it's possible to implement. With this feature, ClickHouse can be used as a replacement to Logstash.

https://github.com/ClickHouse/ClickHouse/issues/6953

### :rocket: Collection of common system metrics in ClickHouse

Done.

Booked by Egor Levankov, Vyacheslav Lukomski.
Continued by @alexey-milovidov 

ClickHouse has deep introspection capabilities: per-query and per-thread metrics, sampling profiler, etc. But they are mostly metrics about ClickHouse itself. There's lack of metrics related to the server as a whole (e.g. total CPU load in system, amount of free memory, load average, network traffic...).

Usually there is no need to have these metrics in ClickHouse, because they are collected by separate monitoring agents. But there are several reasons why it's better for ClickHouse to collect metrics by itself:
- sometimes people are using ClickHouse but forgot to install any system monitoring at all;
- sometimes ClickHouse is run in some managed cloud service where it's not possible to install our own agents and the capabilities of default monitoring option is unsufficient;
- ClickHouse is good as time series database - it can store metrics with superior precision, for more time range and with better efficiency, it opens more possibilities for in-depth data analysis on top of metrics data.

There are some excellent examples of metric collection software (e.g. Netdata: https://github.com/netdata/netdata). Unfortunately, the code license of most of them is GPL - it means that we have to write our own metrics collection code.

https://github.com/ClickHouse/ClickHouse/issues/9430

### :rocket: Integration of S2 geometry library in ClickHouse

Done.

Booked by Andrey Che, @andr0901
Continued by @alexey-milovidov 

S2 is a library for geospatial data processing with space-filling curves. ClickHouse already has support for another library with similar concept (H3 from Uber - hierarchical coordinate system with hexagons).

The choice between these libraries is motivated by which library is already used inside a company. It means that we have no that choice in ClickHouse and it's better to support both.

### SQL functions for compatibility with MySQL dialect

The task is done with 50% completeness.

Booked by Daniil Kondratyev, @dankondr

ClickHouse has very rich set of functions that are available out of the box. It's mostly superior than what you will find in other DBMS. Our functions are more performant, more consistent in behaviour and usually have better naming and usability.

Also we have a practice to add compatibility aliases for functions from other DBMS - so the functions will be available under their foreign names. It is possible to have compatibility for almost every function from MySQL.

### :wastebasket: Data formats for fast import of nested JSON and XML

Initial stage.

Booked by Sergey Polukhin @sdpolukhin

We already have support for importing data in `JSONEachRow` format (flat JSON, a separate object for every row, a.k.a jsonlines). But when JSON contains deeply nested fields and we want to map subset from them to a table, the import become cumbersome. Also we don't have any means for XML import. 

Example of complex nested JSON: https://www.gharchive.org/
Example of complex nested XML: https://meta.wikimedia.org/wiki/Data_dump_torrents#English_Wikipedia

The proposal is to add a format that will allow the user to specify:
- which object (or path in JSON/XML) we should treat as a record;
- what paths within this object will map to what fields in a table.

When multiple elements are matched, we can map them to Array in ClickHouse.

### :hourglass: Efficient text classification in ClickHouse

Review stage.

Booked by Sergey Katkovskiy @s-kat

Add functions for text classification. They can use bag of words / character n-grams / word shingles models. Simple bayes models can be used. The data for models can be provided in static data files.

Example applications:
- detect charset;
- detect language;
- roughly categorize topic.

The main challenge is to make classification functions as efficient as possible to be applicable to massive datasets for on the fly processing (ClickHouse style).

### :rocket: Reducing tail latency for distributed queries in ClickHouse

Done.

Booked by @Avogar 

### :hourglass: Minimal support for transactions in MergeTree tables

Intermediate stage.

Booked by @tavplubix 

### :rocket: Data encryption on VFS level

Review stage.

Booked by Alexandra Latysheva @alexelex

### NEAR modifier for GROUP BY

Unknown status.

Booked by Philipp Malkovsky, @malkfilipp (MIPT)

It allows to aggregate data not by exact values of the keys but by clusters of values near to each other. Clusters are dynamically formed during aggregation.

### Improvements of aggregate functions and array functions in ClickHouse

**Available**

Booked by Alexander Mustafin.

### Porting ClickHouse SIMD optimizations to ARM NEON

**Available**

### Specialized precompression codecs in ClickHouse

Moved to autumn.

Booked by Aspandiyar.

### :rocket: Integration of SQLite as database engine and data format

Booked by Arslan Gumerov.
Done by @kssenii 

### Implementation of query cache for result datasets

**Available**

### :rocket: Support for INFORMATION SCHEMA in ClickHouse

Booked by Damir Petrov.
Done by @tavplubix 

### Application for GitHub with messenger interface

**Available**

Make a desktop application similar to Telegram Desktop that will represent all issues and pull requests from GitHub repositories as chats, sort them by update time, maintain unread count and highlight when the user was mentioned. This application is intented to allow answering questions very quickly without opening web pages in browser (that often takes multiple seconds).

App should work on Linux. C++ and QT can be used for implementation. Alternatively any other technologies can be used instead (Flutter, Electron, ...). The main requirements are: low resource consumption, low input latency, quick startup time, surprise-free behaviour.

**Comment by filimonov** [comment]
## More array/aggregate functions

* fold / reduce and arrayFold / arrayReduce  - to build some custom logic folding/reducing logic
* maxN / minN / maxUniqN / minUniqN and same for arrays - collect several biggest / smalles elements from column / array without full sorting (complexity should by `N*log(number of collected elements)` instead of `N*log(N)` )
* groupArraySorted - https://github.com/ClickHouse/ClickHouse/issues/3708 
* Arrays as sets  
> Массивы как множеста:
> 1) Пересечение. arrayIntersect(a,b) 👍
> ┌─arrayIntersect([1, 2, 3], [3, 2, 5])─┐
> │ [3,2]                                │
> └──────────────────────────────────────┘
> 2) Объединение. arrayReduce('groupUniqArray', [a,b] ) 😱
> ┌─arrayReduce('groupUniqArrayArray', array([1, 2, 3], [3, 2, 1, 5]))─┐
> │ [5,2,1,3]                                                          │
> └────────────────────────────────────────────────────────────────────┘
> 3) Разность arrayDifference arrayFilter( k -> not(has(b,k)), a  ) 🥴
> ┌─arrayFilter(lambda(tuple(k), not(has([2, 3, 5], k))), [1, 2, 3])─┐
> │ [1]                                                              │
> └──────────────────────────────────────────────────────────────────┘
> 
> Кажется 2 и 3 могут быть сделаны более оптимально и с красивым синтаксисом. 
>

**Comment by filimonov** [comment]
This one seems nice / not too small / isolated: https://github.com/ClickHouse/ClickHouse/issues/4420

**Comment by ucasFL** [comment]
> Implementation of a table engine to consume application log files in ClickHouse

Hi, can I do this task? @alexey-milovidov

**Comment by alexey-milovidov** [comment]
@ucasFL Yes, I will reserve it for you.

**Comment by gonzalezjo** [comment]
> ClickHouse has support for LZ4 and ZSTD as generic compression methods. The choice of these particular methods is justified: these methods are pareto-optimal for compression level and speed across well known libraries. Nevertheless, there exist less well known compression libraries that can be somewhat better in certain cases


I'd volunteer for this, but since it has already been booked, I thought that it may be worth sharing my thoughts. I'm a pretty big fan of compression technology and I've tried to keep pace with the field. **I've provided a summary at the bottom**.


The marginal benefit of using other compression methods over lz4 and/or zstd is likely to be fairly low; that is, switching compressors is unlikely to result in across the board improvements, and whatever improvements you do get will probably be small and at the cost of major sacrifices to some other metrics. I say this even though bsc is my personal favorite compression algorithm.


From my reviews of the literature, it seems like the vast majority of compressor gains today come from three main classes: 

1. Highly optimized routines that sacrifice ratios for performance, like--as you note--LZSSE. 


2. Encoders that are specialized to the dataset, like what TimescaleDB and Facebook's Gorilla use. ClickHouse already supports some of these.


3. Lossy or almost-lossy techniques, like reducing numerical precision using bfloat16 or fp16 to store certain data, employing clever video filters, subsampling certain data, etc. ClickHouse's T64, as I understand it, is fairly similar, though it only seems to reduce numerical precision in cases where it's safe to do so losslessly. That seems to be about as much as anyone can reasonably do in a database.


It seems to me, then, that the first class is where the low-hanging fruit is, distantly followed by the second class. 

On the topic of the first class, however, we're not the only people to recognize this low-hanging fruit: LZSSE's developer saw it, as have countless others. lz4 has implemented a decompression speed optimized compression mode and "ultra-fast" mode designed to plug the niche. zstd has a deceptively named "negative compression" mode aimed at the same niche. (Moreover, zstd has 10% faster decompression in the latest release, even without using any of these settings. That's free performance if zstd has its version bumped.)


On the topic of the second class, there is probably plenty of opportunities for certain datasets, but outside of time-series data, where highly effective heuristics are obvious, this seems like it could be pretty hard; if anything, it's probably closer to the topic of a PhD thesis than an intern project. However, things are far from hopeless. zstd and lz4 both support pre-trained dictionaries. These help specialize the compressor context for the dataset at hand; using zstd's dictionary builder, you can get double or quadruple the compression and decompression throughput _and_ better compression ratios at the same time. lz4 can use these pre-trained dictionaries, too. With the merge of the fast-cover dictionary builder into zstd, I would totally expect dictionary pre-training (using samples of the dataset) to be viable. This is on top of the incredible number of tunables and context-specific options that exist in zstd and lz4, each a knob that can help users get better results with compression.




**To summarize**, most high-performance generic compression algorithms perform fairly similarly when you hold some requirements (compression ratio, decompression speed, etc) constant. Some make certain tradeoffs to get large gains in certain niches, while sacrificing in others; for example, experimental compressors like LZSSE sacrifice compression ratios to get stunning (de)compression speeds. However, as of the last few years, experimental compressors have lost their monopoly on these niches. A wide array of tunables are exposed in mainstream compressors like zstd and lz4, allowing users to tap into similar benefits. Moreover, research into domain-specialized compression (which is where the majority of gains are in compression research) have spilled over into mainstream compressors, like lz4 and zstd; these libraries support a bunch of features like pre-trained dictionaries and context-specific options, the latter of which presents a massive array of knobs for improving performance on a per-dataset basis.

**Comment by MaxTheHuman** [comment]
> Implementation of GROUPING SETS in ClickHouse
Hello, can I do this task? @alexey-milovidov

**Comment by Realist007** [comment]
> User defined data types in ClickHouse
Hello, can I do this task? @alexey-milovidov

**Comment by fibersel** [comment]
@gonzalezjo thanks for such detailed response!I'm getting started with this task soon.I'm not experienced enough in 
optimization with cpp subtitles and sse instructions, but I hope I'll deal with it.I also found fresh paper form VLDB conference on strings compression: http://vldb.org/pvldb/vol13/p2649-boncz.pdf and it's source code respectively: https://github.com/cwida/fsst.I realise, that main goal is about general-purpose compression, but I'll test it too if there would be enough time.

**Comment by fibersel** [comment]
@alexey-milovidov here is a list of proposed libraries:
https://github.com/inikep/lizard
https://github.com/ConorStokes/LZSSE
https://github.com/centaurean/density
https://github.com/IlyaGrebnov/libbsc
https://github.com/fusiyuan2010/CSC
https://github.com/richgel999/lzham_codec

Can you create corresponding issue or that's my responsibility?

**Comment by alexey-milovidov** [comment]
https://github.com/ClickHouse/ClickHouse/issues/16775

**Comment by alexey-milovidov** [comment]
@gonzalezjo We finally need your help in selecting (and understanding) some parameters for bsc and csc, see https://github.com/ClickHouse/ClickHouse/pull/17847#issuecomment-776145339

**Comment by alexey-milovidov** [comment]
Welcome to post more wild ideas here.

**Comment by alexey-milovidov** [comment]
Aggregate functions for graph processing.

Implement aggregate functions in form of `agg(id, parent_id)` that will treat `id -> parent_id` as graph edge and calculate various properties of the graph.

**Comment by alexey-milovidov** [comment]
Key value data marts in ClickHouse.

Add `get` method for IStorage for simple key-value request. Dictionaries of type `cache` and `direct`, `Join` and `EmbeddedRocksDB` storages will implement this interface. Make Distributed tables to support this interface as well. Add memcached and/or subset of Redis compatible interfaces to access these tables. The purpose is to represent prepared datasets for easy access from highly-loaded runtimes (ads, personalization, ab-testing, etc).

**Comment by Slach** [comment]
Hello @Andr0901
any news about `Integration of S2 geometry library in ClickHouse`?

**Comment by alexey-milovidov** [comment]
@Slach the work on this task is just started.

**Comment by chenziliang** [comment]
Hi, may i ask what's the status for  `Caching of deserialized data in memory on MergeTree part level` and `Implementation of query cache for result datasets`

**Comment by pennyfea** [comment]
Hello, can I attempt this task? "Limited support for unique key constraint" @alexey-milovidov

**Comment by alexey-milovidov** [comment]
@pennyfea Yes, this task is available. I can mark it for you.
It is non trivial, but also approachable.

Do you need any help from me for your university?

**Comment by pennyfea** [comment]
@alexey-milovidov No, in regards to help from the university I attended. I'm solely attempting to do this to gain real world experience and improve my C++ skills.

**Comment by alexey-milovidov** [comment]
Implementations of specialized interfaces in ClickHouse:

- an interface for Prometheus long term storage and implementation of PromQL;
- an interface for Graphite Carbon API and implementation of Graphite-web;

(these tasks are just to try and play with something)

**Comment by alexey-milovidov** [comment]
This is Ok for 2nd grade coursework: #3266

**Comment by alexey-milovidov** [comment]
FORMAT PNG for creating simple plots directly in ClickHouse.

It does not aim to compete with full featured plotting libraries (both web based and server side) but it can be made reasonably neat and powerful... and fast and ubiquitous.

**Comment by kreuzerkrieg** [comment]
How about to take a look at FSST compression?

**Comment by alexey-milovidov** [comment]
clickhouse perf-sender - a tool to collect Linix Perf data and send it to ClickHouse for always-on server profiling.

**Comment by alexey-milovidov** [comment]
@kreuzerkrieg I ruled it out for some reason, but don't remember why. Need to take a look again.
Also take a look at https://github.com/ClickHouse/ClickHouse/issues/21426

I'm not sure that it's ok as intern task as it has very high requirement on the quality of implementation. E.g. the internal filtering kernel has to be optimized to the works of https://lemire.me/

**Comment by alexey-milovidov** [comment]
Time series analysis with window functions.

Simple moving average. Exponentially smoothed moving average. Holt-Winters forecast. ARIMA. Discovery of "shock events".
A modifier for ORDER BY WITH FILL or similar to fill data with extrapolation.

**Comment by alexey-milovidov** [comment]
Integrate ClickHouse as Python module for embedded processing of dataframes similar to DuckDB.

**Comment by alexey-milovidov** [comment]
Userspace page cache (already booked).

**Comment by alexey-milovidov** [comment]
Compile expressions to GPU

It is relatively easy as we already have compilation of simple expressions to LLVM IR and LLVM has GPU backends.

**Comment by alexey-milovidov** [comment]
Add a function to calculate BLAKE3 hash from string. Add two implementations: C and Rust with interop and compare performance. Check how to integrate rust code to build system.

**Comment by alexey-milovidov** [comment]
@gonzalezjo it also makes sense to try BCM compressor: https://github.com/FS-make-simple/bcm
It has decent performance, acceptable for some scenarios...

**Comment by stavrolia** [comment]
Hi, I want to book `Implementation of query cache for result datasets`. At first I want to implement version with stored in memory LRU cache.

**Comment by alexey-milovidov** [comment]
Integrate with [MeiliSearch](https://github.com/meilisearch/MeiliSearch) for data import/export and querying it with SQL taking the advantage of full text indices. Standalone and embedded version should be considered.

**Comment by alexey-milovidov** [comment]
A small task: integrate wyhash, meowhash, aquahash, farsh, t1ha and highwayhash.

**Comment by alexey-milovidov** [comment]
Integration with MadLib: #4425

**Comment by alexey-milovidov** [comment]
Inregation of ClickHouse with embedded key-value databases:
TerarkDB: #18487
microsoft/FASTER: https://github.com/microsoft/FASTER

**Comment by alexey-milovidov** [comment]
Manage HTTP handlers (API endpoints) with SQL queries (creating parametrized views a.k.a. table functions).

**Comment by alexey-milovidov** [comment]
ClickHouse as a backend for Istio Telemetry.

**Comment by alexey-milovidov** [comment]
Implicit user credentials for authentication.

Pairs of user and password can be generated by separate system with pregenerated secret key.
clickhouse-server can check the validity of credentials using the same secret key without communicating with external service.

`column = user()` can be used as row-level filter in tables.

Use case: multi-tenant logs/metrics collection service.

**Comment by alexey-milovidov** [comment]
Add PostrgreSQL and MySQL parsers as a library and transform their AST into ClickHouse AST.

**Comment by alexey-milovidov** [comment]
Insane and non-practical idea: virtual filesystem over Git. It runs as usual, but pulls and pushes data to remote Git server (though external command). If there is conflict (e.g. intersecting merges), exception is thrown.

**Comment by Justarone** [comment]
Hi, @alexey-milovidov !
Is it still possible to reserve task from the previous list? [This one](https://gist.github.com/alexey-milovidov/4251f71275f169d8fd0867e2051715e9#%D1%88%D0%B8%D1%84%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85-%D0%B2-clickhouse) looks pretty to me

PS: It seems like 1 subtask [is already implemented](https://clickhouse.tech/docs/ru/sql-reference/functions/encryption-functions/) but is it still needed to implement encryption on block level?

**Comment by alexey-milovidov** [comment]
@Justarone It is already implemented in three ways:
1. Encryption of values with SQL functions: implemented by @Enmk and @alexey-milovidov with encrypt/decrypt functions.
2. Encryption on VFS level: implemented by @alexelex and @vitlibar: #24206, #26377, #26465.
3. Encryption on column level: implemented by @depressed-pho and @FArthur-cmd and @vitlibar in #19896, #27476.

The only remaining things are:
- integration with key management services;
- background re-encryption of old data after key rotation.
But these remaining things are quite boring...

**Comment by alexey-milovidov** [comment]
Maybe you will find interesting to research and implement token based authentication methods: JWT, OAuth...
Also you can try to add and test stream cipher ChaCha in addition to AES - it can be better on ARM machines.

**Comment by alexey-milovidov** [comment]
Another interesting research area is to make ClickHouse MergeTree tables to act like blockchain to support guaranteed protection from data modification. It can be implemented fairly simple:

Data checksums should be cryptographically secure (e.g. SipHash128). Now we have insecure checksums.
Every block should contain references to previous blocks (like git commit).

**Comment by Justarone** [comment]
> Another interesting research area is to make ClickHouse MergeTree tables to act like blockchain to support guaranteed protection from data modification. It can be implemented fairly simple:
> 
> Data checksums should be cryptographically secure (e.g. SipHash128). Now we have insecure checksums.
> Every block should contain references to previous blocks (like git commit).

I have no experience in blockchain development but I am interested in this. Can I reserve this task?

**Comment by alexey-milovidov** [comment]
Ok. It is reserved.

I will prepare a list with descriptions and assignments near the end of September.
Also please remind me when you will need some description / docs for your university.
We will also discuss this task in more detail.

**Comment by alexey-milovidov** [comment]
Support for HDF5 format in ClickHouse for import/export.

**Comment by MiaoMiaoGarden** [comment]
Is this still available? Caching of deserialized data in memory on MergeTree part level

**Comment by k-makarov** [comment]
@alexey-milovidov Application for GitHub with messenger interface
1) is this task still available and can be reserved?
2) any frontend ui/ux designs?
3) can this app be in c++ with imgui via open gl?
4) this app need to be in main repo clickhouse (just like website) or no?
5) does this app must have functionality with merge pull requests (without need to go on web) or can provide weblink for it on the first time?

**Comment by alexey-milovidov** [comment]
> is this task still available and can be reserved?

Yes, this task is available.

> any frontend ui/ux designs?

Initial idea was to take Telegram Desktop. Reuse the UI but provide different data for it.
But it can be difficult to separate.

> can this app be in c++ with imgui via open gl?

Yes, you can use any GUI toolkit for your choice.

> this app need to be in main repo clickhouse (just like website) or no?

No, separate repository is better.

> does this app must have functionality with merge pull requests (without need to go on web) or can provide weblink for it on the first time?

Link is enough. The main purpose is to allow quick answers.

**Comment by k-makarov** [comment]
@alexey-milovidov copy that, pls book this task. And can you describe the process for code-review and demo stable versions in separate repo? Must I contact with you every 1-2 weeks or maybe with someone else? (Btw, i am not yandex intern, just randomly saw this theme and were interested)

If it will be more comfortable I am available on Slack/Discord and Telegram(@overcoded)

**Comment by alexey-milovidov** [comment]
Continued in #29601
