### ISSUE TITLE
nullable поля в view с внешними соединениями

### ISSUE THREAD

**Issue by handgunman** [ClickHouse/ClickHouse#15075]
При создании представлений на основании запроса с внешним соединением по умолчанию присоединяемые поля создаются не nullable. Чтобы они были nullable приходится использовать settings join_use_nulls = 1

Кажется по дефолту должно быть ровно наоборот, а для отключения явное указание settings join_use_nulls = 0
Внешнее соединение подразумевает, что часть значений с внешней стороны могут и должны быть null.

Сейчас, при запросе к представлениям, созданным без явной настройки, возникает ошибка
DB::Exception: Cannot convert NULL value to non-Nullable type

то есть запрос работает, а представление на основе запроса - нет.

**Comment by den-crane** [comment]
1. Изначально CH не умел null в join. Полноценная поддержка null в join полностью совместимая с другими СУБД и ANSI стандартом появилась около года назад. Большинство продакшин систем у пользователей работают (и моя тоже) работают в режиме  join_use_nulls = 0 , если установить  join_use_nulls = 1 все просто сломается после апгрейда.

2. Nullable поля потребляют значительно больше памяти, диска и многие операции работают значительно медленее (group by nullable_column ....). Если установить join_use_nulls = 1 КХ перестанет "не тормозить".

**Comment by den-crane** [comment]
>Сейчас, при запросе к представлениям, созданным без явной настройки, возникает ошибка
>DB::Exception: Cannot convert NULL value to non-Nullable type

это похоже на bug , откройте новое issue с описанием и воспроизведением.

**Comment by handgunman** [comment]
c настройкой join_use_nulls = 1  к CH подключается в частности DataLens
Речь не идет о хранении, речь идет о том, что при создании view поверх селекта CH по умолчанию делает ненулевым поля которые по логике должны быть nullable.

когда в поле могут быть любые допустимые значения, без nullable не обойтись.

**Comment by den-crane** [comment]
>Речь не идет о хранении, речь идет о том, что при создании view поверх
> селекта CH по умолчанию делает ненулевым поля которые по логике должны быть nullable.

я ничего не понял вообще. Пример есть?

>когда в поле могут быть любые допустимые значения, без nullable не обойтись.

это конечно так. ! Но у тысяч пользователей КХ нет ни одного Null в их БД и все просто сломается если они появятся после внезапного join_use_nulls = 1.

**Comment by handgunman** [comment]
select test.id, test.val, test2.val2 
from test 
left join test2 using id

подключаюсь с настройкой join_use_nulls = 1 
выполняю запрос - работает
создаю view
create or replace view tst as 
select test.id, test.val, test2.val2 
from test 
left join test2 using id

делаю 
select * from tst
Code: 349. DB::Exception: . DB::Exception: Cannot convert NULL value to non-Nullable type: while converting source column val2 to destination column val2.

**Comment by handgunman** [comment]
если у них нет null то ничего и не сломается. их же нет :)

у запроса и у представления не должно быть разного поведения, но запрос работает, спокойно возвращает null, а представление нет.

**Comment by den-crane** [comment]
это ожидаемое поведение view. Используйте settings join_use_nulls = 1

create or replace view tst as select test.id, test.val, test2.val2
from (select 1 id, 1 val) test
left join (select 2 id, 2 val2) test2 using id settings join_use_nulls = 1;

**Comment by den-crane** [comment]
>если у них нет null то ничего и не сломается. их же нет :)

SQL запросы написаны таким образом что они ожидают 0 и '' , а не Null

```sql
select test.id, test.val, test2.val2, renamed
from (select 1 id, 1 val) test
left join (select 2 id, 2 val2, val2 renamed) test2 using id
where renamed = 0;
┌─id─┬─val─┬─val2─┬─renamed─┐
│  1 │   1 │    0 │       0 │
└────┴─────┴──────┴─────────┘```

если внезапно установить set join_use_nulls = 1

```sql
set join_use_nulls = 1;

select test.id, test.val, test2.val2, renamed
from (select 1 id, 1 val) test
left join (select 2 id, 2 val2, val2 renamed) test2 using id
where renamed = 0;

0 rows in set. Elapsed: 0.001 sec.

```

плюс ко всему мои некоторые запросы вместо 4 минут, начинают работать 8 минут и это ожидаемое поведение, потому что делается group by по колонке которая результат join-а и нее меняется тип с UInt64, становится Nullable(UInt64)
