### ISSUE TITLE
File not found data.mrk3

### ISSUE THREAD

**Issue by yishanchuan** [ClickHouse/ClickHouse#15086]
Hi guys!

when I search system.query_log, I get the following error:

```
SQL error[1000]: ClickHouse exception, code: 1000, host: 10.60.25.129, port: 8123; Poco::Exception. Code: 1000,
 e.code() = 2, e.displayText() = 
File not found: /data/lib/clickhouse/store/e92/e92da35d-ef72-4a16-a8ac-cd4a25febcdb/202009_1_16_3/data.mrk3
 (version 20.8.2.3 (official build))
```

I tried to copy other server's file to replace the "data.mrk3", but not fine. Thanks for any reply.

**Comment by den-crane** [comment]
Please show your select query

**Comment by yishanchuan** [comment]
select `type`,query,`exception`,written_rows,event_date,event_time from `system`.query_log ql  ORDER BY event_time DESC;;

**Comment by yishanchuan** [comment]
When I remove the "ORDER BY event_time DESC" clause and run by clickhouse-client (TCP)，the strange response appear:
![屏幕截图_20200921215907](https://user-images.githubusercontent.com/16149816/93776276-fd481200-fc55-11ea-97a0-2145f777499d.png)

Previous error is run by other tool by HTTP protocol.

**Comment by filimonov** [comment]
```
SELECT * FROM system.parts WHERE database = 'system' and table='query_log' and part='202009_1_16_3';
```

Also - please grep the logs for: '202009_1_16_3'
