### ISSUE TITLE
Value 0000-00-00 00:00:00 changes to 1970-01-01 00:00:00 since v20.7

### ISSUE THREAD

**Issue by simPod** [ClickHouse/ClickHouse#15081]
```sql
CREATE TEMPORARY TABLE test
(
    `received_at` DateTime
)
ENGINE = Memory;

insert into test VALUES ('0000-00-00 00:00:00');

SELECT * from test FORMAT JSONEachRow;
```

On v20.6 and previous returns 

```json
{"received_at":"0000-00-00 00:00:00"}
```

On v20.7 and v20.8 returns 

```json
{"received_at":"1970-01-01 00:00:00"}
```

**Comment by den-crane** [comment]
https://github.com/ClickHouse/ClickHouse/blob/master/CHANGELOG.md#clickhouse-release-207

Deprecate special printing of zero Date/DateTime values as 0000-00-00 and 0000-00-00 00:00:00. #12442 (alexey-milovidov).


https://github.com/ClickHouse/ClickHouse/pull/12442

**Comment by simPod** [comment]
I wonder what is the reason for the change 🤔

**Comment by den-crane** [comment]
AFAIK for compatibility with foreign DBs.
 
For example CH can work on PostgreSQL wire protocol, and it breaks PostgreSQL clients because 0000-00-00  is invalid date for them. 

Also Java does not support 0000-00-00 as date and it creates huge confusion a lot of questions from users. They see Null dates from NotNullable columns and so on.

**Comment by simPod** [comment]
Thanks for explanation.

Maybe just note that this still returns `0000-00-00` as max when no row is found.

```SELECT max((date, rate)) AS last_rate
FROM exchange_rates
WHERE pair = 'x';```

**Comment by den-crane** [comment]
Maybe it's your outdated client does ?

Check `max((date, rate)) ` vs `toString(max((date, rate)) )`

```
SELECT max((date, rate)) AS last_rate
FROM (select today() date, 0 rate, 'y' pair)
WHERE pair = 'x';

┌─last_rate────────┐
│ ('1970-01-01',0) │
└──────────────────┘
```

**Comment by simPod** [comment]
You're right, my test just caught it.

I have to rework all queries that rely on nil value `'0000-00-00 00:00:00'` now.
