### ISSUE TITLE
Add NuRaft to TestKeeper

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#15090]
And look what will happen.

https://github.com/eBay/NuRaft

**Comment by fastio** [comment]
How about this proj [braft](https://github.com/baidu/braft) ?

**Comment by alexey-milovidov** [comment]
We will first try NuRaft for the following reasons:
- less dependency (`braft` has dependency on `brpc`);
- library is small and neat;
- documentation (`braft` only has chinese);
- examples (allows quick start).

But there is a chance that it will not work as expected, then we will continue with alternatives.

**Comment by alesapin** [comment]
More related PRs:
https://github.com/ClickHouse/ClickHouse/pull/19580
https://github.com/ClickHouse/ClickHouse/pull/20585

**Comment by alexey-milovidov** [comment]
Yes.

**Comment by shiyi23** [comment]
> Yes.

thanks your reply

**Comment by alesapin** [comment]
Now it's added and tested with Jepsen tests. We have to add documentation and some performance tuning, but now it's ready for testing environments.

Next steps:
1) Performance benchmarks & improvements
2) Documentation
3) TLS for internal RAFT communication and client
4) Compressed logs
5) Dynamic cluster configuration.

**Comment by alesapin** [comment]
Performance testing & improvements will be done here https://github.com/ClickHouse/ClickHouse/pull/23038#issuecomment-818700761.

**Comment by alesapin** [comment]
Standalone keeper: https://github.com/ClickHouse/ClickHouse/pull/24059
One more bullet todo:
Auth&ACL (simplest possible version)

**Comment by alesapin** [comment]
ACLs https://github.com/ClickHouse/ClickHouse/pull/24448

**Comment by alexey-milovidov** [comment]
The task is done. Auth and ACL are implemented. Log and snapshot conversion is also implemented.
`clickhouse keeper` is ready for evaluation.
