### ISSUE TITLE
The compilation and linking of ClickHouse become particularly slow now?

### ISSUE THREAD

**Issue by ucasFL** [ClickHouse/ClickHouse#15116]
Make sure to check documentation https://clickhouse.yandex/docs/en/ first. If the question is concise and probably has a short answer, asking it in Telegram chat https://telegram.me/clickhouse_en is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

If you still prefer GitHub issues, remove all this text and ask your question here.

**Comment by alexey-milovidov** [comment]
Do you have some numbers for comparison?

**Comment by ucasFL** [comment]
even if just made a small change, it need more than 20 minitues to link, especially for linking `zookeeper-create-entry-to-download-part`, need almost 15 minutes.

**Comment by alexey-milovidov** [comment]
It's better to use `lld` for linking (in case if you are using `gold` linker).
If it's IO bound, you can switch to shared linking, example: https://github.com/ClickHouse/ClickHouse/pull/14711/files#diff-dd7c954046dc6b55d3bc37bc642e2bbeR3

**Comment by alexey-milovidov** [comment]
Also there is usually no need to link all targets. If you only need clickhouse (server, client), write
```
ninja clickhouse
```

**Comment by ucasFL** [comment]
ok, thanks!
