### ISSUE TITLE
ALTER TABLE table ON CLUSTER cluster DELETE WHERE xxxx   Service unavailable due to using all memory

### ISSUE THREAD

**Issue by lamo-20** [ClickHouse/ClickHouse#15119]
err.log:
Repeated execution  
Removing temporary directory  /opt/clickhouse/data/xxx/xxx/tmp_mut_202009_0_653566_473_787233

merges Table records always exist
select source_part_names ,source_part_paths from `system`.merges
202009_0_653566_473_728278	/opt/clickhouse/data/xxx/xxx/tmp_mut_202009_0_653566_473_787233/

clickhouse  version: 20.3.4.10
cluster :  shard 1, replica 2  
disk:   select * from system.disks
data1       /data1/chdata1/
data2	/data2/chdata2/
data3	/data3/chdata3/
default	/opt/clickhouse/data/
select policy_name,volume_name ,disks from `system`.storage_policies
default	default	default
disk_jbod	disk_jbod	['default','data1','data2','data3']
storage policies:  use disk_jbod

**Comment by alesapin** [comment]
This is a known mutation bug in the early 20.3 versions. Just update to the latest 20.3 version.
