### ISSUE TITLE
Materializemysql delete  issue

### ISSUE THREAD

**Issue by chang0391** [ClickHouse/ClickHouse#15118]
**Describe the bug**
CH version: 20.10.1.4699
SELECT version()
┌─version()────┐
│ 20.10.1.4699 │
└──────────────┘
I executed delete for a table which totally have 439129 rows, mysql has executed successfull
but I got total count(1) with no change in CH, and I executed "select *from mobile_belong limit 1", very slowly, and no data

**How to reproduce**
step1: check data in mysql and ch
check mysql:
mysql> select count(1) from mobile_belong;
+----------+
| count(1) |
+----------+
|   439129 |
+----------+
1 row in set (0.13 sec)
check CH:
test-1-118.raipeng.com :) select count(1) from mobile_belong
SELECT count(1)
FROM mobile_belong
┌─count(1)─┐
│   439129 │
└──────────┘
test-1-118.raipeng.com :) select * from mobile_belong limit 1
SELECT *
FROM mobile_belong
LIMIT 1
┌─section─┬─provinceId─┬─province─┬─cityId─┬─city─┬─sign─┬─name─┐
│ 1       │ 1          │ 1        │ 1      │ 1    │    1 │ 1    │
└─────────┴────────────┴──────────┴────────┴──────┴──────┴──────┘
1 rows in set. Elapsed: 0.014 sec

step2: delete data from mysql
mysql> delete from mobile_belong; (remak: must be have a lot of data, otherwise the problem can not be detected)
Query OK, 439129 rows affected (1.31 sec)
step3: check data in mysql and ch
Check mysql:
  mysql> select count(1) from mobile_belong;
+----------+
| count(1) |
+----------+
|        0 |
+----------+
1 row in set (0.00 sec)
Check CH:
test-1-118.raipeng.com :) select count(1) from mobile_belong
SELECT count(1)
FROM mobile_belong
┌─count(1)─┐
│   439129 │
└──────────┘
1 rows in set. Elapsed: 0.043 sec. Processed 696.68 thousand rows, 17.42 MB (16.13 million rows/s., 403.20 MB/s.) 
(remark: ch row data seems like no delete successfully. but I executed select *from mobile_belong limit 1, got no row data, and very slowly)
test-1-118.raipeng.com :) select * from mobile_belong limit 1
SELECT *
FROM mobile_belong
LIMIT 1
Ok.
0 rows in set. Elapsed: 16.641 sec. Processed 696.68 thousand rows, 81.35 MB (41.86 thousand rows/s., 4.89 MB/s.) 
(remark: I executed select *from mobile_belong limit 1, got no row data, and run very slow, cost 16.641 sec)

**Comment by chang0391** [comment]
@BohuTANG @zhang2014 
Thanks

**Comment by chang0391** [comment]
@zhang2014 
    How is the bug handling going on ?

**Comment by tavplubix** [comment]
Fixed in #15767
