### ISSUE TITLE
MaterializeMySQL: Cannot rename and modify the same column user_age in a single ALTER query

### ISSUE THREAD

**Issue by zhituanchen** [ClickHouse/ClickHouse#15120]
HI：
  I alter table got a error when select table:
Code: 48. DB::Exception: Received from 10.0.0.166:9000. DB::Exception: Cannot rename and modify the same column `user_age` in a single ALTER query. （Because i modify table in MySQL database ）

![image](https://user-images.githubusercontent.com/71009460/93853277-287a4200-fce6-11ea-9b66-600424966b9b.png)

Is a there a way to skip the event or reset the MaterializeMySQL in clickhouse?

**Comment by zhang2014** [comment]
Will be implemented in https://github.com/ClickHouse/ClickHouse/pull/12656
