### ISSUE TITLE
Where can I find changelog for 20.9

### ISSUE THREAD

**Issue by simPod** [ClickHouse/ClickHouse#15122]
Where can I find 20.9 changelog please? Latest master contains only 20.8 https://github.com/ClickHouse/ClickHouse/blob/a5b45dabf20f7eed913f69f061f06790eddc9a1c/CHANGELOG.md

**Comment by den-crane** [comment]
Stay tuned is not ready yet. Usually it delays for 2-4 weeks after release.

**Comment by simPod** [comment]
Aight, thanks for info!

**Comment by den-crane** [comment]
work in progress https://github.com/ClickHouse/ClickHouse/pull/15154/files

**Comment by alexey-milovidov** [comment]
Changelog has been published.

**Comment by alexey-milovidov** [comment]
@den-crane 

> Usually it delays for 2-4 weeks after release.

That's slightly pessimistic overestimation.

**Comment by simPod** [comment]
He meant hours for sure 🙃
