### ISSUE TITLE
Is it possible to change the <PARTITION BY>?

### ISSUE THREAD

**Issue by lzy1g1225** [ClickHouse/ClickHouse#15123]
I was doing wrong to create overly granular partitions. 
Now I have too much records already, so I want to simply change the partitions instead of creating & copying to another table, is that possible?

**Comment by den-crane** [comment]
No. It's not possible. You can only create a new table and copy data there using `insert into new select from old`

**Comment by lzy1g1225** [comment]
Thanks, for convenience I am using clickhouse-copier now, however while copying I saw it is creating <newtable>_piece_0, <newtable>_piece_1 ...., but in taks.xml I only specified one <newtable>, which is following documentation, what are these xxx_piece_x tables? Am I missing something?

**Comment by den-crane** [comment]
It's how copier works nowadays. For idempotent atomic re-tries. 

It creates a table for each partition of a destination table. And after success insert into xxx_piece_x it attaches data from xxx_piece_x to the newtable.

**Comment by alexey-milovidov** [comment]
There is a feature request to allow to convert partition key from
date or toDate(datetime)
to
toMonday(date) or toStartOfMonth(date) or similar.

**Comment by ywangtht** [comment]
@alexey-milovidov 
Can you please tell me what is the feature request link?

**Comment by filimonov** [comment]
https://github.com/ClickHouse/ClickHouse/issues/13826
