### ISSUE TITLE
What data type should I use to store date before 1970-01-01 00:00:00?

### ISSUE THREAD

**Issue by larkwormzyn** [ClickHouse/ClickHouse#15126]
Make sure to check documentation https://clickhouse.yandex/docs/en/ first. If the question is concise and probably has a short answer, asking it in Telegram chat https://telegram.me/clickhouse_en is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

If you still prefer GitHub issues, remove all this text and ask your question here.

**Comment by den-crane** [comment]
It will be implemented in DateTime64 eventually. Stay tuned.

https://github.com/ClickHouse/ClickHouse/pull/9404
