### ISSUE TITLE
subselect in WITH not cloned properly

### ISSUE THREAD

**Issue by akuzm** [ClickHouse/ClickHouse#15129]
`WITH test1 AS (SELECT * FROM numbers(3)) SELECT * FROM test1`

https://clickhouse-test-reports.s3.yandex.net/15061/30f96dc525a6ba3540322346df4a0b790aed5634/fuzzer/report.html#fail1

**Comment by akuzm** [comment]
From the PR:
>The `clone()` method of `ASTWithElement` is broken -- the cloned node references some source nodes. Apparently the reason is that the `IAST::children` is not cleared after copy construction, so it references both the old and the new nodes. As far as I understand, the general model for ASTs should be that `children` owns the child nodes, and other fields such as `subquery` are references into `children`, so they better be non-owning pointers (e.g. raw).

**Comment by amosbird** [comment]
Thanks! It's because I forgot to clear the children...
