### ISSUE TITLE
MaterializeMySQL doesn't remove deleted rows

### ISSUE THREAD

**Issue by liangli1213** [ClickHouse/ClickHouse#15146]
**Describe the bug**
Delete operation take place from MySQL side, and the operation should be synced to ClickHouse, however, the data is still there.

I'm not sure if this is the desired behavior, or not realized yet, please give me some explain.

**Comment by zhang2014** [comment]
Maybe you are using `SELECT COUNT() FROM table_name` to determine if the data was deleted? 

if so, it is a bug about using `count` queries. it was fixed in #15471.
if not, could you describe more detail for this problem?

**Comment by tavplubix** [comment]
Fixed in #15767
