### ISSUE TITLE
Add new EXPLAIN query flavour to describe encountered policies for other queries

### ISSUE THREAD

**Issue by abyss7** [ClickHouse/ClickHouse#15160]
For queries like `SELECT …` it will be useful to have query e.g. `EXPLAIN POLICIES SELECT …` that will follow the execution conveyer and output all met grants and stop on first restriction - to prevent potential security breaches.

It's helpful to understand what policies affect what and to understand what `GRANT` is missing.

TODO: add examples.

**Comment by alexey-milovidov** [comment]
No need for this.
