### ISSUE TITLE
RBAC Distributed Tables - actions on remote servers required less privileges than on local servers.

### ISSUE THREAD

**Issue by MyroTk** [ClickHouse/ClickHouse#15165]
**Describe the bug**
In order to execute `SELECT` or `INSERT` on a distributed table, the user requires additional privileges on the table indicated in the distributed table. However, if that table does not exist locally, or the distributed table is sharded across multiple servers, then the user is not checked for those privileges and is able to execute the command.

**How to reproduce**
* ClickHouse 20.10.1.1 with revision 54440
* `CREATE TABLE` statements
`CREATE TABLE default.dist0 (a UInt64) ENGINE = Distributed(cluster23, default, table0)` - using table0 remotely.
`CREATE TABLE default.dist1 (a UInt64) ENGINE = Distributed(cluster1, default, table0)` - using table0 locally.

* Clusters from remote servers config
```
        <cluster1>
            <shard>
                <replica>
                    <host>clickhouse1</host>
                    <port>9440</port>
                    <secure>1</secure>
                </replica>
            </shard>
        </cluster1>
	<cluster23>
            <shard>
                <replica>
                    <host>clickhouse2</host>
                    <port>9000</port>
                </replica>
            </shard>
            <shard>
                <replica>
                    <host>clickhouse3</host>
                    <port>9000</port>
                </replica>
            </shard>
        </cluster23>
```
* Queries to run that lead to unexpected result
```
root@clickhouse1:/# echo -e "SELECT * FROM dist1" | clickhouse client -n -uuser0
Received exception from server (version 20.8.2):
Code: 497. DB::Exception: Received from localhost:9000. DB::Exception: user0: Not enough privileges. To execute this query it's necessary to have the grant SELECT(a) ON default.table0.

root@clickhouse1:/# echo -e "SELECT * FROM dist0" | clickhouse client -n -uuser0

root@clickhouse1:/# echo -e "SHOW GRANTS FOR user0" | clickhouse client -n
GRANT SELECT ON default.dist0 TO user0
GRANT SELECT ON default.dist1 TO user0
```
**Expected behavior**
Consistent  privilege requirements between local and remote tables.

**Comment by filimonov** [comment]
Can you recheck it with <secret> in cluster config? See https://github.com/ClickHouse/ClickHouse/pull/13156

**Comment by alexey-milovidov** [comment]
@MyroTk You have to setup access rights to the Distributed table.
Internal SELECT or INSERT subqueries that Distributed table is generated are not subjects of access control.

**Comment by filimonov** [comment]
> Internal SELECT or INSERT subqueries that Distributed table is generating are not subjects of access control.

Selects are. Inserts - not sure how it works with `secret`. Do you know it @azat?

**Comment by vitlibar** [comment]
> @MyroTk You have to setup access rights to the Distributed table.
> Internal SELECT or INSERT subqueries that Distributed table is generating are not subjects of access control.

Yes, but it's not how it works right now. If a source table used for a distributed table is located locally, selecting from a distributed table requires the current user to have the SELECT privilege both on the distributed table and the source table, because in that case the internal query is executed in the same query context. I think we should fix it, executing SELECT from a distributed table should require the current user only to have the SELECT privilege on the distributed table no matter where the source table is located.

**Comment by filimonov** [comment]
> I think we should fix it, executing SELECT from a distributed table should require the current user only to have the SELECT privilege on the distributed table no matter where the source table is located.

So to access table X i have no access to i will just create distributed on the top of it / or just use cluster / remote table function?

That is another aspect of DEFINERs problem. What do you think of #19228 ?

PS. With `<secret>` i expect it to work properly. (did't check).

**Comment by azat** [comment]
>Selects are. Inserts - not sure how it works with secret. Do you know it @azat?

AFAICS the problem is that the initiator user on the remote nodes is `default` that do not have constraints for `userX`.
Inter-server secret is about remote nodes not local, and here the problem with local node.
But with inter-server secret you will have the same user on remote nodes so the query should also fail.

@vitlibar maybe in case of inter-server secret we may skip access checks? (although not sure about this).

P.S. I guess `prefer_localhost_replica=0` will allow to workaround the issue.

**Comment by alexey-milovidov** [comment]
@vitlibar Yes, it will be better to fix it.
But you have reopened and nothing happened.
Let's forget about this task because it has low priority.

**Comment by larry-cdn77** [comment]
I have a client who relies on local status of replica (by reading system.clusters) which is only set if default_database is configured for the cluster's replicas

But with default_database configured I found, as this issue decribes, that I need privileges configured not only for the Distributed table but also for the source MergeTree table which often changes as I use names as a sort of versioning scheme:

```sql
CREATE TABLE flights ENGINE = Distributed('cluster', 'default', 'flights_v3', rand())
GRANT alice SELECT ON default.flights
```

I can see some options:

- get the client to stop relying on replicas being marked local, or
- stop using table names as versions, or
- maintain privileges on my versioned tables, or
- implement split context on local replicas

But thought I would ask if anyone has other suggestions

**Comment by larry-cdn77** [comment]
Actually, one more option is to switch my privileges to wildcards which in my case is acceptable

Probably the least effort way out!
