### ISSUE TITLE
[RFC] Tables and dictionaries loading order on server startup and related issues

### ISSUE THREAD

**Issue by tavplubix** [ClickHouse/ClickHouse#15170]
**It's just a draft, I will complete the description later**

**Use case**
If some table depends on another table or dictionary (for example, expression in `MATERIALIZED`, `ALIAS` or `DEFAULT` contains `joinGet(...)` or `dictGet(...)` or `IN` operator with `StorageSet`, maybe there are some other scenarios), then clickhouse-server may fail to start because it doesn't take into account such dependencies. 

**Describe the solution you'd like**
See https://github.com/ClickHouse/ClickHouse/pull/15157#issuecomment-696924255

**Additional context**
It would be great to collect all related issues here to choose the proper solution.
#8004 #13613 #13059 #15157 #13359

**Comment by filimonov** [comment]
topological sorting/dependencies analysis is a very good option, but relatively big/complicated.

That will allow solving issues like https://github.com/ClickHouse/ClickHouse/issues/7944 (needed for example to backup recovery) and will require to detect all possible dependencies between tables (there are a lot of non-obvious) - nice for schema static analysis

There is also the 'naive' option that is easy to implement: https://github.com/ClickHouse/ClickHouse/issues/13059#issuecomment-694127022 (good enough for most of the simple cases) 

Some side nodes: IMHO it's stupid we need to LOAD dictionary data to get the type of the fields which exist in dict definition in explicit form - see https://github.com/ClickHouse/ClickHouse/issues/10729 (if it would work we would be able to init dictionaries w/o loading their data, and after that, we should be able to ATTACH tables which depends on that.

**Comment by filimonov** [comment]
See also https://github.com/ClickHouse/ClickHouse/issues/4717#issuecomment-736346712

**Comment by alexey-milovidov** [comment]
#13359
