### ISSUE TITLE
Add tests for AArch64 version of ClickHouse to CI

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#15174]
AArch64 version is built but not covered by tests.
But it's quite easy to run AArch64 binary on x86_64 Linux.

Step 1: install QEMU and support to run AArch64 binaries:
`sudo apt install qemu-user-static binfmt-support`

Step 2: Obtain the libc binaries from AArch64 Linux.
```
wget 'https://developer.arm.com/-/media/Files/downloads/gnu-a/8.3-2019.03/binrel/gcc-arm-8.3-2019.03-x86_64-aarch64-linux-gnu.tar.xz?revision=2e88a73f-d233-4f96-b1f4-d8b36e9bb0b9&la=en' -O gcc-arm-8.3-2019.03-x86_64-aarch64-linux-gnu.tar.xz
tar xJf gcc-arm-8.3-2019.03-x86_64-aarch64-linux-gnu.tar.xz --strip-components=1
```
And look into `aarch64-linux-gnu/libc/` subdirectory.

Step 3: use the corresponding `.so` files to prepare the chroot environment:
```
mkdir root
pushd root
mkdir lib lib64 etc tmp root
cp ${BUILD_DIR}/programs/clickhouse .
cp ${SRC_DIR}/programs/server/{config,users}.xml .
cp lib/x86_64-linux-gnu/{libc.so.6,libdl.so.2,libm.so.6,libpthread.so.0,librt.so.1,libnss_dns.so.2,libresolv.so.2} lib
cp lib64/ld-linux-x86-64.so.2 lib64
cp /etc/resolv.conf ./etc
mkdir proc
sudo mount --bind /proc proc
```

Step 4: put `clickhouse` AArch64 binary there.

Step 5: run it in chroot:

`sudo chroot . ./clickhouse server -- --mlock_executable false`

As you see, some tweaks may be required.

Step 6: run tests:

`./clickhouse-test --order asc --no-shard`

```
Running 2296 stateless tests.

00001_select_1:                                                         [ OK ]
00002_system_numbers:                                                   [ OK ]
00003_reinterpret_as_string:                                            [ OK ]
00004_shard_format_ast_and_remote_table:                                [ SKIPPED ] - no shard
00005_shard_format_ast_and_remote_table_lambda:                         [ SKIPPED ] - no shard
00006_extremes_and_subquery_from:                                       [ OK ]
00007_array:                                                            [ OK ]
00008_array_join:                                                       [ OK ]
00009_array_join_subquery:                                              [ OK ]
00010_big_array_join:                                                   [ OK ]
00011_array_join_alias:                                                 [ OK ]
00012_array_join_alias_2:                                               [ OK ]
00013_create_table_with_arrays:                                         [ OK ]
00014_select_from_table_with_nested:                                    [ OK ]
00015_totals_having_constants:                                          [ OK ]
00016_totals_having_constants:                                          [ OK ]
00017_in_subquery_with_empty_result:                                    [ OK ]
00018_distinct_in_subquery:                                             [ OK ]
00019_shard_quantiles_totals_distributed:                               [ SKIPPED ] - no shard
00020_sorting_arrays:                                                   [ OK ]
00021_sorting_arrays:                                                   [ OK ]
00022_func_higher_order_and_constants:                                  [ OK ]
00023_agg_select_agg_subquery:                                          [ OK ]
00024_unused_array_join_in_subquery:                                    [ OK ]
00025_implicitly_used_subquery_column:                                  [ OK ]
00026_shard_something_distributed:                                      [ SKIPPED ] - no shard
00027_distinct_and_order_by:                                            [ OK ]
00027_simple_argMinArray:                                               [ OK ]
00028_shard_big_agg_aj_distributed:                                     [ SKIPPED ] - no shard
00029_test_zookeeper_optimize_exception:                                [ SKIPPED ] - no zookeeper
00030_alter_table:                                                      [ OK ]
00031_parser_number:                                                    [ OK ]
00032_fixed_string_to_string:                                           [ OK ]
00033_fixed_string_to_string:                                           [ OK ]
00034_fixed_string_to_number:                                           [ OK ]
00035_function_array_return_type:                                       [ OK ]
00036_array_element:                                                    [ OK ]
00037_totals_limit:                                                     [ OK ]
00038_totals_limit:                                                     [ OK ]
00039_inserts_through_http:                                             [ OK ]
00040_array_enumerate_uniq:                                             [ OK ]
00041_aggregation_remap:                                                [ OK ]
00041_big_array_join:                                                   [ OK ]
00042_set:                                                              [ OK ]
00043_summing_empty_part:                                               [ OK ]
00044_sorting_by_string_descending:                                     [ OK ]
00045_sorting_by_fixed_string_descending:                               [ OK ]
00046_stored_aggregates_simple:                                         [ OK ]
00047_stored_aggregates_complex:                                        [ OK ]
00048_a_stored_aggregates_merge:                                        [ FAIL ] - return code 32
[milovidov-desktop] 2020.09.22 22:03:50.951209 [ 30908 ] <Fatal> BaseDaemon: ########################################
[milovidov-desktop] 2020.09.22 22:03:50.953203 [ 30908 ] <Fatal> BaseDaemon: (version 20.10.1.4715 (official build), build id: BF78A7E6DB73182C) (from thread 30103) (query_id: d2d1bbb2-5451-4888-a025-7398306dac47) Received signal Segmentation fault (11)
[milovidov-desktop] 2020.09.22 22:03:50.954072 [ 30908 ] <Fatal> BaseDaemon: Address: 0x1 Address not mapped to object.
[milovidov-desktop] 2020.09.22 22:03:50.954442 [ 30908 ] <Fatal> BaseDaemon: Stack trace: 0x61aa158 0xa558788
[milovidov-desktop] 2020.09.22 22:03:50.961289 [ 30908 ] <Fatal> BaseDaemon: 0. /build/build_docker/../src/Common/StackTrace.cpp:291: StackTrace::StackTrace(ucontext_t const&) @ 0x61aa158 in /clickhouse
[milovidov-desktop] 2020.09.22 22:03:50.970543 [ 30908 ] <Fatal> BaseDaemon: 1. /build/build_docker/../src/Common/CurrentThread.h:81: signalHandler(int, siginfo_t*, void*) @ 0xa558788 in /clickhouse
Error on processing query: INSERT INTO stored_aggregates
SELECT
        toDate(toUInt16(toDate('2014-06-01')) + intDiv(number, 100)) AS d,
        uniqState(intDiv(number, 10)) AS Uniq
FROM
(
        SELECT * FROM system.numbers LIMIT 1000
)
GROUP BY d;
```

As you see, we definitely need to have this run in CI.

**Comment by l1t1** [comment]
where could I find the benchmark of the AArch64 vs x86 system?

**Comment by alexey-milovidov** [comment]
@l1t1 

Here is the benchmark:
https://clickhouse.tech/benchmark/hardware/

`AWS a...` and `Huawei` are AArch64 servers.

There are multiple variants of server AArch64 CPU, this is incomplete list:
- Amazon Graviton 1 and 2;
- Huawei Taishan;
- Cavium ThunderX 1, 2;
- APM X-Gene;

The results will depend on the chip itself, the number of cores, the memory subsystem...
We see that the most powerful AArch64 servers are competitive with x86 servers.

**Comment by alexey-milovidov** [comment]
Without chroot:

```
sudo apt install qemu-user-static binfmt-support
sudo apt install libc6-arm64-cross

sudo ln -s /usr/aarch64-linux-gnu/lib/ld-linux-aarch64.so.1 /lib/ld-linux-aarch64.so.1

sudo mkdir /lib/aarch64-linux-gnu/
for i in /usr/aarch64-linux-gnu/lib/*.so; do echo sudo ln -s $i $(echo $i | sed -r -e 's!/usr/aarch64-linux-gnu/lib/!/lib/aarch64-linux-gnu/!'); done

sudo ln -s /lib/aarch64-linux-gnu/libpthread-2.30.so /lib/aarch64-linux-gnu/libpthread.so.0
sudo ln -s /lib/aarch64-linux-gnu/libdl-2.30.so /lib/aarch64-linux-gnu/libdl.so.2
sudo ln -s /lib/aarch64-linux-gnu/librt-2.30.so /lib/aarch64-linux-gnu/librt.so.1
sudo ln -s /lib/aarch64-linux-gnu/libc-2.30.so /lib/aarch64-linux-gnu/libc.so.6
sudo ln -s /lib/aarch64-linux-gnu/libm-2.30.so /lib/aarch64-linux-gnu/libm.so.6
```

Now you can run ClickHouse for aarch64 on amd64.

**Comment by alexey-milovidov** [comment]
@azat It stopped to work.
Now every attempt to run ClickHouse under QEMU yields the following message:
```
MADV_DONTNEED does not zeroed page. jemalloc will be broken
```

**Comment by azat** [comment]
>@azat It stopped to work.

I was afraid of that check actually, since it does completely breaks clickhouse under qemu.
Ok, I guess this check can be moved into runtime, will take a look.

**Comment by alexey-milovidov** [comment]
Tests under `qemu-user` trigger segfault in QEMU, although they work perfectly fine on real AArch64 server (e.g. Graviton).

Maybe we have to use full-featured `qemu-system` (that is significantly harder) or to disable some functionality (but it's difficult to figure out the culprit) or to use real server (but we don't have them in CI).

**Comment by alexey-milovidov** [comment]
I have run functional tests on AArch64 server and get the following results:
- ClickHouse is perfectly stable;
- the messages `libunwind: Unsupported .eh_frame_hdr version` are printed in stderr sometimes;
- there are minor differences in results of floating point functions.

**Comment by l1t1** [comment]
> I have run functional tests on AArch64 server and get the following results:
> 
> * ClickHouse is perfectly stable;
> * the messages `libunwind: Unsupported .eh_frame_hdr version` are printed in stderr sometimes;
> * there are minor differences in results of floating point functions.

could you also release an aarch64 version at https://github.com/ClickHouse/ClickHouse/releases/tag/v21.1.2.15-stable, so that i neednt download the 1.9GB binary file, and regular update to stable versions

**Comment by alexey-milovidov** [comment]
We don't release packages (deb, rpm) for AArch64, only binaries.

**Comment by l1t1** [comment]
> We don't release packages (deb, rpm) for AArch64, only binaries.
> Adding packages requires more efforts.

gzip binary file without debug info is enough. thanks

**Comment by alexey-milovidov** [comment]
FYI. I have run the functional stateless tests in Docker (with qemu-user and binfmt-misc):

```
sudo apt install qemu-user-static
docker run --rm --privileged multiarch/qemu-user-static:register --reset
docker run -it --rm multiarch/ubuntu-core:arm64-bionic /bin/bash
apt update
apt install wget
wget https://clickhouse-builds.s3.yandex.net/0/d70b6ee11a5edd394a518a69e22f5e9892d6af4a/clickhouse_special_build_check/clang-11-aarch64_relwithdebuginfo_none_bundled_unsplitted_disable_False_binary/clickhouse
chmod a+x ./clickhouse
./clickhouse server
```

```
docker exec -it ... /bin/bash
apt install git python3
git clone https://github.com/ClickHouse/ClickHouse.git
cd ClickHouse/tests
./clickhouse-test --order asc --client "bash -c '/clickhouse client \$@ 2>&1 | grep -v -F jemalloc' --"
```

All tests has finished, the server did not crash.

**Comment by l1t1** [comment]
nice job. 
will arm64 version be public release now?

**Comment by alexey-milovidov** [comment]
Some issues are unresolved.

**Comment by alexey-milovidov** [comment]
I finally figured out why it has crashed under qemu-user.
It is "obviously" because of the query profiler.

Query profiler setups a signal by timer (either byt CPU or real time).
It's asking the OS kernel to send a signal to the application after some time.
But the application is qemu-user. And it correctly printing the error:

```
qemu:handle_cpu_signal received signal outside vCPU context @ pc=0x7ff4c20c8bc5
qemu:handle_cpu_signal received signal outside vCPU context @ pc=0x7ff4c1a5d943
```

Maybe qemu-user should translare this signal to the emulated application.

If I disable the query profiler, everything started to be Ok.

**Comment by alexey-milovidov** [comment]
Although it is supposed to work: https://qemu.readthedocs.io/en/latest/user/main.html

**Comment by alexey-milovidov** [comment]
Another way to run server in Docker:

```
find config.d users.d -type l | xargs -I {} bash -c 'cp --remove-destination $(dirname {})/$(readlink {}) {}'

docker run -it --rm --network host --volume $(pwd):/ClickHouse --workdir /ClickHouse --user $(id -u) multiarch/ubuntu-core:arm64-bionic ./clickhouse-aarch64 server
```

**Comment by llwdd** [comment]
According to your steps, I found the following error, please help...
`
2021.05.17 13:08:17.969028 [ 2607 ] {} <Trace> BaseDaemon: Received signal 6
2021.05.17 13:08:17.969222 [ 2630 ] {} <Fatal> BaseDaemon: ########################################
2021.05.17 13:08:17.969255 [ 2630 ] {} <Fatal> BaseDaemon: (version 21.5.1.6580 (official build), build id: A3D12C95101AC854DBDFD9A2EA4008CD39714E94) (from thread 2606) (no query) Received signal Aborted (6)
2021.05.17 13:08:17.969302 [ 2630 ] {} <Fatal> BaseDaemon:
2021.05.17 13:08:17.969335 [ 2630 ] {} <Fatal> BaseDaemon: Stack trace: 0xffffb54a24a8
2021.05.17 13:08:17.969414 [ 2630 ] {} <Fatal> BaseDaemon: 0. gsignal @ 0x324a8 in /lib/aarch64-linux-gnu/libc-2.27.so
2021.05.17 13:08:18.058985 [ 2630 ] {} <Fatal> BaseDaemon: Calculated checksum of the binary: 41681F9213F1A149F9E9C64F01710CE5. There is no information about the reference checksum.
2021.05.17 13:08:18.059033 [ 2630 ] {} <Information> SentryWriter: Not sending crash report
Aborted (core dumped)
`

**Comment by azat** [comment]
> Received signal 6

`SIGABRT`
But there is no stacktrace. Can you obtain it from gdb, i.e.:

```
gdb clickhouse /path/to/core
(gdb) bt
```
