### ISSUE TITLE
Partitioned write into s3 table function / S3 table

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#15171]
Allow to specify PARTITION BY expression for S3 table engine.
When writing to this table, multiple files will be created, with names prefixed (?) by partition key.

`PARTITION BY rand() % N` will be also applicable for creation of multiple files instead of one.

Motivation:
- more efficient to read;
- easier manipulation by other data processing systems.

Details of implementation:
- if s3 path contains wildcard (`*`), we will substitute this wildcard by the value of partition key; it can be located in file name or in part of path (in the latter case multiple directories will be created).

**Comment by excitoon** [comment]
@alexey-milovidov @filimonov We can make syntax like python f-strings: `s3('http://bucket.amazonaws.com/key/{_partition_id}.csv', ...)` . What do you think about it?
