### ISSUE TITLE
MaterializeMySQL  Fatal error

### ISSUE THREAD

**Issue by little-tomato** [ClickHouse/ClickHouse#15175]
i use MaterializeMySQL sync mysql database,use the Command：
======================================
SET allow_experimental_database_materialize_mysql=1;
CREATE DATABASE dmp_device ENGINE = MaterializeMySQL('xxxx', 'dmp_device', 'root', 'yyy');
=====================================
then the clickhouse-server.err.log  show:

2020.09.23 08:37:42.213613 [ 9417 ] {} <Fatal> BaseDaemon: ########################################
2020.09.23 08:37:42.213675 [ 9417 ] {} <Fatal> BaseDaemon: (version 20.9.2.20 (official build), no build id) (from thread 9357) (no query) Received signal Segmentation fault (11)
2020.09.23 08:37:42.213695 [ 9417 ] {} <Fatal> BaseDaemon: Address: 0x38cd5c0 Access: write. Attempted access has violated the permissions assigned to the memory area.
2020.09.23 08:37:42.213713 [ 9417 ] {} <Fatal> BaseDaemon: Stack trace: 0x15e474a8 0x15e3d808 0x15e40e35 0x15aae222 0x15e1ac62 0x15e1c5c2 0x15a0c0b4 0x15a16125 0x15a17853 0x15a51ce9 0x15a5411e 0x15a0fae1 0x15a1476b 0x15a14c86 0xe75d547 0xe75bb83 0x7f33c4324dc5 0x7f33c3c4621d
2020.09.23 08:37:42.213811 [ 9417 ] {} <Fatal> BaseDaemon: 3. std::__1::enable_if<(std::__1::__is_cpp17_forward_iterator<std::__1::__wrap_iter<std::__1::shared_ptr<DB::IAST>*> >::value) && (std::__1::is_constructible<std::__1::shared_ptr<DB::IAST>, std::__1::iterator_traits<std::__1::iterator_traits>::reference>::value), std::__1::__wrap_iter<std::__1::shared_ptr<DB::IAST>*> >::type std::__1::vector<std::__1::shared_ptr<DB::IAST>, std::__1::allocator<std::__1::shared_ptr<DB::IAST> > >::insert<std::__1::__wrap_iter<std::__1::shared_ptr<DB::IAST>*> >(std::__1::__wrap_iter<std::__1::shared_ptr<DB::IAST> const*>, std::__1::iterator_traits, std::__1::iterator_traits) @ 0x15e474a8 in /usr/bin/clickhouse
2020.09.23 08:37:42.213835 [ 9417 ] {} <Fatal> BaseDaemon: 4. ? @ 0x15e3d808 in /usr/bin/clickhouse
2020.09.23 08:37:42.213852 [ 9417 ] {} <Fatal> BaseDaemon: 5. DB::MySQLInterpreter::InterpreterCreateImpl::getRewrittenQueries(DB::MySQLParser::ASTCreateQuery const&, DB::Context const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x15e40e35 in /usr/bin/clickhouse
2020.09.23 08:37:42.213896 [ 9417 ] {} <Fatal> BaseDaemon: 6. DB::InterpreterExternalDDLQuery::execute() @ 0x15aae222 in /usr/bin/clickhouse
2020.09.23 08:37:42.213947 [ 9417 ] {} <Fatal> BaseDaemon: 7. ? @ 0x15e1ac62 in /usr/bin/clickhouse
2020.09.23 08:37:42.213993 [ 9417 ] {} <Fatal> BaseDaemon: 8. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool) @ 0x15e1c5c2 in /usr/bin/clickhouse
2020.09.23 08:37:42.214010 [ 9417 ] {} <Fatal> BaseDaemon: 9. ? @ 0x15a0c0b4 in /usr/bin/clickhouse
2020.09.23 08:37:42.214018 [ 9417 ] {} <Fatal> BaseDaemon: 10. ? @ 0x15a16125 in /usr/bin/clickhouse
2020.09.23 08:37:42.214027 [ 9417 ] {} <Fatal> BaseDaemon: 11. ? @ 0x15a17853 in /usr/bin/clickhouse
2020.09.23 08:37:42.214045 [ 9417 ] {} <Fatal> BaseDaemon: 12. DB::commitMetadata(std::__1::function<void ()> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x15a51ce9 in /usr/bin/clickhouse
2020.09.23 08:37:42.214062 [ 9417 ] {} <Fatal> BaseDaemon: 13. DB::MaterializeMetadata::transaction(DB::MySQLReplication::Position const&, std::__1::function<void ()> const&) @ 0x15a5411e in /usr/bin/clickhouse
2020.09.23 08:37:42.214075 [ 9417 ] {} <Fatal> BaseDaemon: 14. DB::MaterializeMySQLSyncThread::prepareSynchronized(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x15a0fae1 in /usr/bin/clickhouse
2020.09.23 08:37:42.214104 [ 9417 ] {} <Fatal> BaseDaemon: 15. DB::MaterializeMySQLSyncThread::synchronization(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x15a1476b in /usr/bin/clickhouse
2020.09.23 08:37:42.214112 [ 9417 ] {} <Fatal> BaseDaemon: 16. ? @ 0x15a14c86 in /usr/bin/clickhouse
2020.09.23 08:37:42.214130 [ 9417 ] {} <Fatal> BaseDaemon: 17. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xe75d547 in /usr/bin/clickhouse
2020.09.23 08:37:42.214139 [ 9417 ] {} <Fatal> BaseDaemon: 18. ? @ 0xe75bb83 in /usr/bin/clickhouse
2020.09.23 08:37:42.214163 [ 9417 ] {} <Fatal> BaseDaemon: 19. start_thread @ 0x7dc5 in /usr/lib64/libpthread-2.17.so
2020.09.23 08:37:42.214178 [ 9417 ] {} <Fatal> BaseDaemon: 20. __clone @ 0xf621d in /usr/lib64/libc-2.17.so

**Comment by zhang2014** [comment]
fixed in https://github.com/ClickHouse/ClickHouse/pull/14852
