### ISSUE TITLE
MaterializeMySQL: support BIT data type

### ISSUE THREAD

**Issue by DBA-Ray** [ClickHouse/ClickHouse#15182]
2020.09.23 16:13:20.829140 [ 24677 ] {} <Error> MaterializeMySQLSyncThread: Code: 1002, e.displayText() = DB::Exception: ParseMetaData: Unhandled data type:16, Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x114ffed0 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x8367afd in /usr/bin/clickhouse
2. ? @ 0xe2b4199 in /usr/bin/clickhouse
3. DB::MySQLReplication::TableMapEvent::parseImpl(DB::ReadBuffer&) @ 0xe2ae6b5 in /usr/bin/clickhouse
4. DB::MySQLReplication::MySQLFlavor::readPayloadImpl(DB::ReadBuffer&) @ 0xe2b2931 in /usr/bin/clickhouse
5. DB::MySQLProtocol::IMySQLReadPacket::readPayload(DB::ReadBuffer&, unsigned char&) @ 0xe2bdc81 in /usr/bin/clickhouse
6. DB::MySQLProtocol::PacketEndpoint::tryReceivePacket(DB::MySQLProtocol::IMySQLReadPacket&, unsigned long) @ 0xe2cc057 in /usr/bin/clickhouse
7. DB::MySQLClient::readOneBinlogEvent(unsigned long) @ 0xe2c9a81 in /usr/bin/clickhouse
8. DB::MaterializeMySQLSyncThread::synchronization(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xe2a3b11 in /usr/bin/clickhouse
9. ? @ 0xe2a3f36 in /usr/bin/clickhouse
10. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x8395fcf in /usr/bin/clickhouse
11. ? @ 0x83948f3 in /usr/bin/clickhouse
12. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
13. __clone @ 0xfe8dd in /usr/lib64/libc-2.17.so
 (version 20.10.1.4709 (official build))

**Comment by tavplubix** [comment]
16 is for `MYSQL_TYPE_BIT`, currently it's not supported in ClickHouse

**Comment by zhaihao** [comment]
is there any update on the issues?

**Comment by scalad** [comment]
is there any solution resolve these issue? I encountered the same problem.

**Comment by alexey-milovidov** [comment]
MaterializeMySQL feature is not ready for production. It is also not being developed.

**Comment by TheAlexCH** [comment]
Its not a productive environment. If its not further developed, it might be better to put it as DEPRECATED. Many seem to like this feature in particular and would not bother about it if its deprecated. Experimental implies that its upcoming rather then stopped. Maybe this would help

**Comment by piggy9512** [comment]
> 16 is for `MYSQL_TYPE_BIT`, currently it's not supported in ClickHouse

data type: 19 is for what MYSQL_TYPE ?

**Comment by tavplubix** [comment]
> data type: 19 is for what MYSQL_TYPE ?

`MYSQL_TYPE_TIME2`
