### ISSUE TITLE
TTL_ONLY_DROP_PARTS does not drop empty parts 

### ISSUE THREAD

**Issue by ikainazarov** [ClickHouse/ClickHouse#15180]
I created table with following structure and inserted some test data. 
Empty parts(rows = 0) still exists even if all rows from the table were deleted over TTL.

create table  temp_ttl_partition_test
 (
        rec_date DateTime,
        user_id String
)
engine = MergeTree
partition by formatDateTime(rec_date, '%Y%m%d%H')
ORDER BY user_id
TTL rec_date + interval 10 minute
SETTINGS ttl_only_drop_parts=1;

CH version = 20.5.2.7

Expected behavior: TTL_ONLY_DROP_PARTS must drop empty parts

![bug](https://user-images.githubusercontent.com/26870989/93976110-244f3280-fd81-11ea-9e63-5eb6cee41b5d.png)

**Comment by fastio** [comment]
The outdated parts were removed in the background. The expired parts were replaced by empty parts with commited state, which generated in the merge phase. If the generated empty parts were not commited, and just remove the outdated parts.

I have fixed this problem in my test env. Can I make a pull request?

**Comment by ikainazarov** [comment]
> The outdated parts were removed in the background. The expired parts were replaced by empty parts with commited state, which generated in the merge phase. If the generated empty parts were not commited, and just remove the outdated parts, this problem will be solved.
> 
> I have fixed this problem in my test env. Can I make a pull request?

can you please give more detail on how you fix it in your env ?

**Comment by alesapin** [comment]
Currently, ClickHouse doesn't delete empty parts from MergeTree for several reasons. It's expected behavior. However, they can be merged with non-empty parts in the background. We already have Draft PR where we try to delete empty parts https://github.com/ClickHouse/ClickHouse/pull/13252.

**Comment by alesapin** [comment]
> The outdated parts were removed in the background. The expired parts were replaced by empty parts with commited state, which generated in the merge phase. If the generated empty parts were not commited, and just remove the outdated parts, this problem will be solved.
> 
> I have fixed this problem in my test env. Can I make a pull request?

You are welcome! We will be glad to see your solution.

**Comment by fastio** [comment]
@ikainazarov As mentioned above, it's unexpected behaviour. I try to make a pr to improvement it.

**Comment by ikainazarov** [comment]
thank you guys

**Comment by SaltTan** [comment]
#5491
