### ISSUE TITLE
clickhouse-copier failed to copy table from older version (18.14.18) to newer version (20.6.4) with field named 'index'

### ISSUE THREAD

**Issue by cmsxbc** [ClickHouse/ClickHouse#15185]
(you don't have to strictly follow this form)

**Describe the issue**
Using clickhouse-copier copy data from older version cluster(18.14.18), which cannot upgrade to latest version, to a newer cluster (20.6.4), the copier will failed becase of syntax error in (create table sql)

**How to reproduce**
* source cluster: 18.14.18
* destination cluster: 20.6.4
* copier version: 20.6.4
* create table sql:
    `CREATE TABLE with_index_table(id Int64, index Float64, date Date) Engine=ReplicatedMergeTree('/clickhouse/tables/default/{shard}/default.with_index_table', '{replica}') PARTITION BY date ORDER BY id`

What is best solution?

**Comment by den-crane** [comment]
related https://github.com/ClickHouse/ClickHouse/issues/4390#issuecomment-463623903

**Comment by cmsxbc** [comment]
> related [#4390 (comment)](https://github.com/ClickHouse/ClickHouse/issues/4390#issuecomment-463623903)

The solution seems not work for copier.... the sql got from older server is not escaped yet....

**Comment by den-crane** [comment]
@cmsxbc I am not offer that solution to you. I just tie tickets for developers to get understanding what is going on.

For you I can offer to "rename" index column to _index. But there is no easy way. You  can add a new column and name it for example _index and place default as index `alter table xxxx add column _index default index. Then remerge the table using `optimize` or mutate using `alter table .... update _index = index where 1`,then drop index column.

Or you can use the old clickhouse-copier (from 19.13 version) and create target (distributed) table by yourself by `create table` when copier failed and continue failed task.

**Comment by cmsxbc** [comment]
> @cmsxbc I am not offer that solution to you. I just tie tickets for developers to get understanding what is going on.
> 
> For you I can offer to "rename" index column to _index. But there is no easy way. You can add a new column and name it for example _index and place default as index `alter table xxxx add column _index default index. Then remerge the table using `optimize`or mutate using`alter table .... update _index = index where 1`,then drop index column.
> 
> Or you can use the old clickhouse-copier (from 19.13 version) and create target (distributed) table by yourself by `create table` when copier failed and continue failed task.

Thx for your offer, i will have a try.

**Comment by alexey-milovidov** [comment]
The version 18.14 is old enough, so this issue lost its relevance.

**Comment by alexey-milovidov** [comment]
ALTER RENAME COLUMN is also implemented in newer versions.
