### ISSUE TITLE
Filtering on nested column doesn't work when joining

### ISSUE THREAD

**Issue by yiquanzhou** [ClickHouse/ClickHouse#15200]
**Describe the bug**
When joining table A with table B and filter by a field of table A, if the field is a nested column, the query throws an exception. 

**How to reproduce**
* Which ClickHouse server version to use
`v20.9.2.20`: https://github.com/ClickHouse/ClickHouse/releases/tag/v20.9.2.20-stable

* `CREATE TABLE` statements for all tables involved
```
CREATE TABLE main_table
(
    `id` String,
    `tag` Nested(
    key String,
    value String),
    `arr` Array(String)
)
ENGINE = Memory
```

```
CREATE TABLE join_table
(
    `id` String
)
ENGINE = Memory
```

* Queries to run that lead to unexpected result
```
SELECT 1
FROM main_table
ALL INNER JOIN join_table USING (id)
WHERE empty(tag.key) = 0
```

**Expected behavior**
The query returns nothing.

**Error message and/or stacktrace**
```
Received exception from server (version 20.9.2):
Code: 47. DB::Exception: Received from clickhouse-server:9000. DB::Exception: Missing columns: 'tag.key' while processing query: 'SELECT id FROM join_table WHERE empty(tag.key) = 0', required columns: 'id' 'tag.key', source columns: 'id'.
```

**Additional context**
It works with the non nested `arr Array(String)` column:
```
SELECT 1
FROM main_table
ALL INNER JOIN join_table USING (id)
WHERE empty(arr) = 0

Ok.

0 rows in set. Elapsed: 0.005 sec.
```

This issue is a regression and seems to relate to the feature `joined_subquery_requires_alias`.
I can reproduce a similar issue with the materialized column in `v20.3.12` but it seems to be fixed in `v20.9.2`

**Comment by den-crane** [comment]
hm,
 ```
`tag.key`
``` 
works

```sql
SELECT 1
FROM main_table
ALL INNER JOIN join_table USING (id)
WHERE empty(`tag.key`) = 0
```

**Comment by yiquanzhou** [comment]
Hi @den-crane,
Although the workaround looks easy by just wrapping the column name with backquotes like for an alias, it's not trivial to do so in our code because we have built a DSL in Java to build and render the queries. It may impact many other queries and our unit tests so it's pretty annoying. Can this issue be quickly fixed? 

Thanks,
Yiquan

**Comment by den-crane** [comment]
It's not a bug. https://clickhouse.tech/docs/en/sql-reference/syntax/#syntax-identifiers
Identifiers with . dot MUST be in backticks or double-quotes.

related https://github.com/ClickHouse/ClickHouse/issues/15877
