### ISSUE TITLE
Create two or many shards on same node.

### ISSUE THREAD

**Issue by yiguolei** [ClickHouse/ClickHouse#15210]
Currently, I only have one machine， but my data will increasing very fast. I want to create 100 shard for the simple table on the machine and create a distribute table on it. 
But I do not know how to do it.

**Comment by den-crane** [comment]
I strongly advice not to do it. 100 tables will kill your single node. 
Much wiser is to use `clickhouse-copier` and re-shard your table when you get 100 nodes.

**Comment by yiguolei** [comment]
In this case, I have to re-shard data if I scale my cluster from 1 one to 2 node. And then have to re-shard again when I scale my cluster from 2 node to 4 node ..... And I have to stop importing data during re-sharding process.
Any better ideas?

**Comment by filimonov** [comment]
With docker (or with Kubernetes) you can run as many instances on a single node as you want, and later move them to a dedicated nodes. But as @den-crane - having 100 shards on a single node sounds like a very bad idea (forget about performance).

**Comment by yiguolei** [comment]
@filimonov I found there is a cluster definition in config.xml.
        <test_cluster_two_shards_localhost>
             <shard>
                 <replica>
                     <host>localhost</host>
                     <port>9000</port>
                 </replica>
             </shard>
             <shard>
                 <replica>
                     <host>localhost</host>
                     <port>9000</port>
                 </replica>
             </shard>
        </test_cluster_two_shards_localhost>
Does that mean the 2 shards on the same instance?

**Comment by den-crane** [comment]
@yiguolei it's for tests in CH developing. The same table (the same data) appears twice in a query result.

**Comment by fedorkosilov** [comment]
I hesitate to open a separate issue since my question is connected to this one, and I'm nearly certain it's not feasible. However, I'd still like to confirm.

Is it possible to have two shards on two machines while simultaneously having replicas of those shards on the same machines?

For instance, on machine 1:
- Shard 1
- Replica of Shard 2

And on machine 2:
- Shard 2
- Replica of Shard 1

**Comment by den-crane** [comment]
>Is it possible to have two shards on two machines while simultaneously having replicas of those shards on the same machines?

It's possible. AKA Circle-replication. But it's very cumbersome and error-prone. Not supported officially. Also it causes performance issues in some setups. Just spin-up two virtual machines or two containers on the same hardware node.

**Comment by gregakinman** [comment]
@den-crane can you elaborate on the issues with that setup?
