### ISSUE TITLE
Replication queue is very slow for items from one table even though there are no more items being inserted

### ISSUE THREAD

**Issue by simPod** [ClickHouse/ClickHouse#15229]
I have a replication queue full on a replica (700 items+)

Those 700 items are of one table `A`.

I stopped insertion into that table, hoped that the queue would get cleared kind of fast.

There were 740 items 5h ago, now there are 700. Seems like very slow pace to me (CPU is on 30 %).

Is there a way to make replication queue run faster or what might be the reason for it to be slow? One item represents few kilobytes of data so it's very small. Therefore the data size should not be an issue.

I'm considering recreating the table to clear it up but wanted to know proper troubleshooting procedure. Thanks!

<details>
<summary>Error log</summary>
0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x18e02790 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xe72fdad in /usr/bin/clickhouse
2. ? @ 0x1622f596 in /usr/bin/clickhouse
3. DB::PushingToViewsBlockOutputStream::writePrefix() @ 0x15abd50c in /usr/bin/clickhouse
4. DB::StorageBuffer::writeBlockToDestination(DB::Block const&, std::__1::shared_ptr<DB::IStorage>) @ 0x161156f2 in /usr/bin/clickhouse
5. DB::StorageBuffer::flushBuffer(DB::StorageBuffer::Buffer&, bool, bool) @ 0x16115f04 in /usr/bin/clickhouse
6. DB::StorageBuffer::flushBack() @ 0x161166ea in /usr/bin/clickhouse
7. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x15865609 in /usr/bin/clickhouse
8. DB::BackgroundSchedulePool::threadFunction() @ 0x15865a92 in /usr/bin/clickhouse
9. ? @ 0x15865bc2 in /usr/bin/clickhouse
10. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xe75d547 in /usr/bin/clickhouse
11. ? @ 0xe75bb83 in /usr/bin/clickhouse
12. start_thread @ 0x74a4 in /lib/x86_64-linux-gnu/libpthread-2.24.so
13. __clone @ 0xe8d0f in /lib/x86_64-linux-gnu/libc-2.24.so
 (version 20.9.2.20 (official build))
2020.09.24 11:43:08.576184 [ 22263 ] {} <Error> void DB::StorageBuffer::flushBack(): Code: 252, e.displayText() = DB::Exception: Too many parts (300). Merges are processing significantly slower than inserts., Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x18e02790 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xe72fdad in /usr/bin/clickhouse
2. ? @ 0x1622f596 in /usr/bin/clickhouse
3. DB::PushingToViewsBlockOutputStream::writePrefix() @ 0x15abd50c in /usr/bin/clickhouse
4. DB::StorageBuffer::writeBlockToDestination(DB::Block const&, std::__1::shared_ptr<DB::IStorage>) @ 0x161156f2 in /usr/bin/clickhouse
5. DB::StorageBuffer::flushBuffer(DB::StorageBuffer::Buffer&, bool, bool) @ 0x16115f04 in /usr/bin/clickhouse
6. DB::StorageBuffer::flushBack() @ 0x161166ea in /usr/bin/clickhouse
7. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x15865609 in /usr/bin/clickhouse
8. DB::BackgroundSchedulePool::threadFunction() @ 0x15865a92 in /usr/bin/clickhouse
9. ? @ 0x15865bc2 in /usr/bin/clickhouse
10. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xe75d547 in /usr/bin/clickhouse
11. ? @ 0xe75bb83 in /usr/bin/clickhouse
12. start_thread @ 0x74a4 in /lib/x86_64-linux-gnu/libpthread-2.24.so
13. __clone @ 0xe8d0f in /lib/x86_64-linux-gnu/libc-2.24.so
 (version 20.9.2.20 (official build))
2020.09.24 11:43:09.577901 [ 22274 ] {} <Error> void DB::StorageBuffer::flushBack(): Code: 252, e.displayText() = DB::Exception: Too many parts (300). Merges are processing significantly slower than inserts., Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x18e02790 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xe72fdad in /usr/bin/clickhouse
2. ? @ 0x1622f596 in /usr/bin/clickhouse
3. DB::PushingToViewsBlockOutputStream::writePrefix() @ 0x15abd50c in /usr/bin/clickhouse
4. DB::StorageBuffer::writeBlockToDestination(DB::Block const&, std::__1::shared_ptr<DB::IStorage>) @ 0x161156f2 in /usr/bin/clickhouse
5. DB::StorageBuffer::flushBuffer(DB::StorageBuffer::Buffer&, bool, bool) @ 0x16115f04 in /usr/bin/clickhouse
6. DB::StorageBuffer::flushBack() @ 0x161166ea in /usr/bin/clickhouse
7. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x15865609 in /usr/bin/clickhouse
8. DB::BackgroundSchedulePool::threadFunction() @ 0x15865a92 in /usr/bin/clickhouse
9. ? @ 0x15865bc2 in /usr/bin/clickhouse
10. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xe75d547 in /usr/bin/clickhouse
11. ? @ 0xe75bb83 in /usr/bin/clickhouse
12. start_thread @ 0x74a4 in /lib/x86_64-linux-gnu/libpthread-2.24.so
13. __clone @ 0xe8d0f in /lib/x86_64-linux-gnu/libc-2.24.so
 (version 20.9.2.20 (official build))
2020.09.24 11:43:10.578982 [ 22336 ] {} <Error> void DB::StorageBuffer::flushBack(): Code: 252, e.displayText() = DB::Exception: Too many parts (300). Merges are processing significantly slower than inserts., Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x18e02790 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xe72fdad in /usr/bin/clickhouse
2. ? @ 0x1622f596 in /usr/bin/clickhouse
3. DB::PushingToViewsBlockOutputStream::writePrefix() @ 0x15abd50c in /usr/bin/clickhouse
4. DB::StorageBuffer::writeBlockToDestination(DB::Block const&, std::__1::shared_ptr<DB::IStorage>) @ 0x161156f2 in /usr/bin/clickhouse
5. DB::StorageBuffer::flushBuffer(DB::StorageBuffer::Buffer&, bool, bool) @ 0x16115f04 in /usr/bin/clickhouse
6. DB::StorageBuffer::flushBack() @ 0x161166ea in /usr/bin/clickhouse
7. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x15865609 in /usr/bin/clickhouse
8. DB::BackgroundSchedulePool::threadFunction() @ 0x15865a92 in /usr/bin/clickhouse
9. ? @ 0x15865bc2 in /usr/bin/clickhouse
10. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xe75d547 in /usr/bin/clickhouse
11. ? @ 0xe75bb83 in /usr/bin/clickhouse
12. start_thread @ 0x74a4 in /lib/x86_64-linux-gnu/libpthread-2.24.so
13. __clone @ 0xe8d0f in /lib/x86_64-linux-gnu/libc-2.24.so
 (version 20.9.2.20 (official build))
2020.09.24 11:43:11.579784 [ 22311 ] {} <Error> void DB::StorageBuffer::flushBack(): Code: 252, e.displayText() = DB::Exception: Too many parts (300). Merges are processing significantly slower than inserts., Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x18e02790 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xe72fdad in /usr/bin/clickhouse
2. ? @ 0x1622f596 in /usr/bin/clickhouse
3. DB::PushingToViewsBlockOutputStream::writePrefix() @ 0x15abd50c in /usr/bin/clickhouse
4. DB::StorageBuffer::writeBlockToDestination(DB::Block const&, std::__1::shared_ptr<DB::IStorage>) @ 0x161156f2 in /usr/bin/clickhouse
5. DB::StorageBuffer::flushBuffer(DB::StorageBuffer::Buffer&, bool, bool) @ 0x16115f04 in /usr/bin/clickhouse
6. DB::StorageBuffer::flushBack() @ 0x161166ea in /usr/bin/clickhouse
7. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x15865609 in /usr/bin/clickhouse
8. DB::BackgroundSchedulePool::threadFunction() @ 0x15865a92 in /usr/bin/clickhouse
9. ? @ 0x15865bc2 in /usr/bin/clickhouse
10. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xe75d547 in /usr/bin/clickhouse
11. ? @ 0xe75bb83 in /usr/bin/clickhouse
12. start_thread @ 0x74a4 in /lib/x86_64-linux-gnu/libpthread-2.24.so
13. __clone @ 0xe8d0f in /lib/x86_64-linux-gnu/libc-2.24.so
 (version 20.9.2.20 (official build))
2020.09.24 11:43:12.580398 [ 22309 ] {} <Error> void DB::StorageBuffer::flushBack(): Code: 252, e.displayText() = DB::Exception: Too many parts (300). Merges are processing significantly slower than inserts., Stack trace (when copying this message, always include the lines below):
</details>

**Comment by den-crane** [comment]
>I have a replication queue full on a replica (700 items+)

check network. Use `ping -l 1500 ` to ping among replicas back and forth.

check `system.replication_queue last_exception` column. It could be a lost of a part.

**Comment by simPod** [comment]
Ping is 0.1 ms and

```sql
SELECT *
FROM system.replication_queue
WHERE table = 't1'
  AND last_exception <> '';
```

is empty 🤔 I have active monitoring on broken items in replication queue, it's without exceptions the whole time

**Comment by den-crane** [comment]
hmm, then maybe it a lack of background jobs because they do merges / mutations / kafka ...

```
SELECT
    name,
    value
FROM system.settings
WHERE name LIKE '%pool%'

┌─name─────────────────────────────────────────┬─value─┐
│ connection_pool_max_wait_ms                  │ 0     │
│ distributed_connections_pool_size            │ 1024  │
│ background_buffer_flush_schedule_pool_size   │ 16    │
│ background_pool_size                         │ 16    │
│ background_move_pool_size                    │ 8     │
│ background_schedule_pool_size                │ 16    │
│ background_message_broker_schedule_pool_size │ 16    │
│ background_distributed_schedule_pool_size    │ 16    │
└──────────────────────────────────────────────┴───────┘
```
try to increase background_pool_size to 32 in default profile and restart CH

**Comment by simPod** [comment]
I dropped the buffer table in order to tweak it's min and max conditions and it has all got processed 🤔 Thanks for help, will definitely try to increase the pool size when similar issue happens.
