### ISSUE TITLE
join issue  when selecting different columns, the number of rows returned is much larger than the correct number

### ISSUE THREAD

**Issue by jjtjiang** [ClickHouse/ClickHouse#15225]
the clickhosue version is 20.6 .the first sql return 2 rows  that is right ; the second sql and other sql return more wrong rows.It's not because of the identified columns that caused the error, but because of many different column combinations.For example , first sql ,it's right when select HL_TXNID,    HL_DB,    HL_TABLE,    HL_PARTITION,    HL_LOCK_STATE,    HL_LOCK_TYPE,     HL_LAST_HEARTBEAT,	 HL_ACQUIRED_AT,    HL_HEARTBEAT_COUNT,	    HL_BLOCKEDBY_EXT_ID,	    HL_BLOCKEDBY_INT_ID,	    offset,		binlog_time,		entry_time from .....  .And second sql ,it's also right when select other cloumns(HL_USER  ,HL_AGENT_INFO) :select HL_USER  ,HL_AGENT_INFO from ......。But when select columns that are the first sql and add column HL_USER  ,it will wrong.
below ,i will paste my sql 、return and table.
table ddl :
CREATE TABLE default.hive_locks_copy
(
    `HL_LOCK_EXT_ID` Int64,
    `HL_LOCK_INT_ID` Int64,
    `HL_TXNID` Nullable(Int64),
    `HL_DB` Nullable(String),
    `HL_TABLE` Nullable(String),
    `HL_PARTITION` Nullable(String),
    `HL_LOCK_STATE` Nullable(String),
    `HL_LOCK_TYPE` Nullable(String),
    `HL_LAST_HEARTBEAT` Nullable(Int64),
    `HL_ACQUIRED_AT` Nullable(Int64),
    `HL_USER` Nullable(String),
    `HL_HOST` Nullable(String),
    `HL_HEARTBEAT_COUNT` Nullable(Int32),
    `HL_AGENT_INFO` Nullable(String),
    `HL_BLOCKEDBY_EXT_ID` Nullable(Int64),
    `HL_BLOCKEDBY_INT_ID` Nullable(Int64),
    `offset` Int64,
    `binlog_time` Int64,
    `entry_time` DateTime64(3),
    `Sign` Int8
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(entry_time)
ORDER BY HL_LOCK_EXT_ID
SETTINGS index_granularity = 8192
.

First sql ：

SELECT 
    HL_TXNID,
    HL_DB,
    HL_TABLE,
    HL_PARTITION,
    HL_LOCK_STATE,
    HL_LOCK_TYPE,
    HL_LAST_HEARTBEAT,
    HL_ACQUIRED_AT,
    HL_HEARTBEAT_COUNT,
    HL_BLOCKEDBY_EXT_ID,
    HL_BLOCKEDBY_INT_ID,
    offset,
    binlog_time,
    entry_time,
    Sign,
    dateDiff('second', toDateTime(b.binlog_time / 1000), now()) AS exec_escape_time
FROM 
(
    SELECT 
        HL_LOCK_EXT_ID,
        HL_LOCK_INT_ID,
        sign,
        arr_offset,
        row_number
    FROM 
    (
        SELECT 
            HL_LOCK_EXT_ID,
            HL_LOCK_INT_ID,
            groupArray(Sign) AS arr_sign,
            groupArray(offset) AS arr_offset,
            arrayEnumerate(arr_offset) AS row_number
        FROM 
        (
            SELECT 
                HL_LOCK_EXT_ID,
                HL_LOCK_INT_ID,
                Sign,
                offset
            FROM default.hive_locks_copy AS hl
            ORDER BY (offset, Sign) DESC
        )
        GROUP BY 
            HL_LOCK_EXT_ID,
            HL_LOCK_INT_ID
    )
    ARRAY JOIN 
        arr_sign AS sign,
        arr_offset,
        row_number
    WHERE (row_number = 1) AND (sign = 1)
) AS t
INNER JOIN default.hive_locks_copy AS b ON (t.HL_LOCK_EXT_ID = b.HL_LOCK_EXT_ID) AND (t.HL_LOCK_INT_ID = b.HL_LOCK_INT_ID) AND (t.arr_offset = b.offset)
WHERE (t.row_number = 1) AND (b.Sign = 1);

First sql return:

HL_TXNID|HL_DB |HL_TABLE                      |HL_PARTITION|HL_LOCK_STATE|HL_LOCK_TYPE|HL_LAST_HEARTBEAT|HL_ACQUIRED_AT|HL_HEARTBEAT_COUNT|HL_BLOCKEDBY_EXT_ID|HL_BLOCKEDBY_INT_ID|offset |binlog_time  |entry_time             |Sign|exec_escape_time|
--------|------|------------------------------|------------|-------------|------------|-----------------|--------------|------------------|-------------------|-------------------|-------|-------------|-----------------------|----|----------------|
 5953368|ods_jp|ods_cis_dbo_order_header      |            |a            |e           |                0| 1600882974000|                 0|                  0|                  0|4385365|1600911774000|2020-09-23 18:43:00.008|   1|           26561|
 5953368|ods_jp|ods_cis_dbo_order_header_trans|            |a            |r           |                0| 1600882974000|                 0|                  0|                  0|4385364|1600911774000|2020-09-23 18:43:00.008|   1|           26561|

Second sql :
SELECT 
HL_USER  ,
HL_AGENT_INFO
FROM 
(
    SELECT 
        HL_LOCK_EXT_ID,
        HL_LOCK_INT_ID,
		sign,
        arr_offset,
        row_number
    FROM 
    (
        SELECT 
            HL_LOCK_EXT_ID,
            HL_LOCK_INT_ID,
			groupArray(Sign) arr_sign,
            groupArray(offset) AS arr_offset,
            arrayEnumerate(arr_offset) AS row_number
        FROM 
        (
            SELECT 
                HL_LOCK_EXT_ID,
                HL_LOCK_INT_ID,
				Sign,
                offset
            FROM default.hive_locks_copy AS hl
            ORDER BY (offset, Sign) DESC
        )
        GROUP BY 
            HL_LOCK_EXT_ID,
            HL_LOCK_INT_ID
    )
    ARRAY JOIN 
	    arr_sign as sign,
        arr_offset,
        row_number
	WHERE (row_number = 1 and sign=1) 
) AS t
 JOIN default.hive_locks_copy AS b ON (t.HL_LOCK_EXT_ID = b.HL_LOCK_EXT_ID) AND (t.HL_LOCK_INT_ID = b.HL_LOCK_INT_ID) AND (t.arr_offset = b.offset)
WHERE  t.row_number = 1
AND b.Sign = 1
Second sql return also 2 rows :
HL_USER|HL_AGENT_INFO                                           |
-------|--------------------------------------------------------|
hive   |hive_20200923184254_4d4abe74-e6a7-41ae-a09c-d4b38564e11b|
hive   |hive_20200923184254_4d4abe74-e6a7-41ae-a09c-d4b38564e11b|
Third sql and other sql :

SELECT 
HL_USER,
    HL_TXNID,
    HL_DB,
    HL_TABLE,
    HL_PARTITION,
    HL_LOCK_STATE,
    HL_LOCK_TYPE,
    HL_LAST_HEARTBEAT,
	HL_ACQUIRED_AT,
    HL_HEARTBEAT_COUNT,
	HL_BLOCKEDBY_EXT_ID,
	HL_BLOCKEDBY_INT_ID,
	offset,
	binlog_time,
	entry_time,
	Sign,
	dateDiff('second', toDateTime(b.binlog_time / 1000), now()) AS exec_escape_time
FROM 
(
    SELECT 
        HL_LOCK_EXT_ID,
        HL_LOCK_INT_ID,
		sign,
        arr_offset,
        row_number
    FROM 
    (
        SELECT 
            HL_LOCK_EXT_ID,
            HL_LOCK_INT_ID,
			groupArray(Sign) arr_sign,
            groupArray(offset) AS arr_offset,
            arrayEnumerate(arr_offset) AS row_number
        FROM 
        (
            SELECT 
                HL_LOCK_EXT_ID,
                HL_LOCK_INT_ID,
				Sign,
                offset
            FROM default.hive_locks_copy AS hl
            ORDER BY (offset, Sign) DESC
        )
        GROUP BY 
            HL_LOCK_EXT_ID,
            HL_LOCK_INT_ID
    )
    ARRAY JOIN 
	    arr_sign as sign,
        arr_offset,
        row_number
	WHERE (row_number = 1 and sign=1) 
) AS t
 JOIN default.hive_locks_copy AS b ON (t.HL_LOCK_EXT_ID = b.HL_LOCK_EXT_ID) AND (t.HL_LOCK_INT_ID = b.HL_LOCK_INT_ID) AND (t.arr_offset = b.offset)
WHERE  t.row_number = 1
AND b.Sign = 1

Third sql return thousands of rows,it's to many to paste ,now only paste  10 rows:
HL_USER|HL_TXNID|HL_DB   |HL_TABLE                                    |HL_PARTITION        |HL_LOCK_STATE|HL_LOCK_TYPE|HL_LAST_HEARTBEAT|HL_ACQUIRED_AT|HL_HEARTBEAT_COUNT|HL_BLOCKEDBY_EXT_ID|HL_BLOCKEDBY_INT_ID|offset |binlog_time  |entry_time             |Sign|exec_escape_time|
-------|--------|--------|--------------------------------------------|--------------------|-------------|------------|-----------------|--------------|------------------|-------------------|-------------------|-------|-------------|-----------------------|----|----------------|
hive   | 5945015|dw_ca   |dwd_stellr_subscription_trans_di            |date_flag=2016-10-29|a            |r           |                0| 1600842311000|                 0|                  0|                  0|4151233|1600871111000|2020-09-23 07:26:00.202|   1|           66761|
hive   | 5919876|ods_us  |ods_dw_prod_dbo_dw_orders_pl_trans          |date_flag=2020-01-13|w            |r           |                0|             0|                 0|                  0|                  0|3589007|1600787865000|2020-09-22 08:18:30.249|   1|          150007|
hive   | 5919876|ods_us  |ods_dw_prod_dbo_dw_orders_pl_trans          |date_flag=2018-12-17|a            |r           |                0| 1600759065000|                 0|                  0|                  0|3592708|1600787865000|2020-09-22 08:18:30.249|   1|          150007|
hive   | 5944049|dw_us   |dwd_stellr_subscription_contract_df         |date_flag=2020-07-13|a            |r           |                0| 1600838171000|                 0|                  0|                  0|4043486|1600866971000|2020-09-23 06:16:30.214|   1|           70901|
hive   | 5944063|dw_ca   |dwd_stellr_subscription_contract_df         |date_flag=2020-06-22|w            |r           |                0|             0|                 0|                  0|                  0|4046205|1600866995000|2020-09-23 06:17:00.192|   1|           70877|
hive   | 5947066|ods_us  |ods_dw_prod_dbo_dw_orders_trans             |date_flag=2004-04-27|a            |r           |                0| 1600855092000|                 0|                  0|                  0|4301326|1600883892000|2020-09-23 10:59:00.301|   1|           53980|
hive   | 5919876|ods_us  |ods_dw_prod_dbo_dw_orders_pl_trans          |date_flag=2009-09-16|a            |r           |                0| 1600759065000|                 0|                  0|                  0|3592455|1600787865000|2020-09-22 08:18:30.249|   1|          150007|
hive   | 5919876|ods_us  |ods_dw_prod_dbo_dw_orders_pl_trans          |date_flag=2009-11-09|w            |r           |                0|             0|                 0|                  0|                  0|3590699|1600787865000|2020-09-22 08:18:30.249|   1|          150007|
hive   | 5947066|ods_us  |ods_dw_prod_dbo_dw_orders_trans             |date_flag=2010-05-21|a            |r           |                0| 1600855092000|                 0|                  0|                  0|4302860|1600883892000|2020-09-23 10:59:30.251|   1|           53980|
hive   | 5947066|ods_us  |ods_dw_prod_dbo_dw_orders_trans             |date_flag=2009-06-28|a            |r           |                0| 1600855092000|                 0|                  0|                  0|4300121|1600883892000|2020-09-23 10:59:00.301|   1|           53980|
hive   | 5945013|dm_wcla |dm_stellr_invoice_license_recurring         |date_flag=2020-09-22|w            |r           |                0|             0|                 0|                  0|                  0|4143969|1600871098000|2020-09-23 07:25:30.196|   1|           66774|
......

**Comment by tbragin** [comment]
Version 20.6 is obsolete. Please upgrade to a supported version e.g. 23.8 (LTS) or ideally the latest 24.4, and let us know if it persists.
