### ISSUE TITLE
INSERT SELECT loses TOTALS data

### ISSUE THREAD

**Issue by akuzm** [ClickHouse/ClickHouse#15227]
```
:)
CREATE TABLE t
ENGINE = File(TSV) AS
SELECT
    number,
    sum(1)
FROM numbers(2)
GROUP BY number
    WITH TOTALS

:) select * from t

┌─number─┬─sum(1)─┐
│      0 │      1 │
│      1 │      1 │
└────────┴────────┘
```

The totals row is missing.

**Comment by alexey-milovidov** [comment]
Totals is not a part of the resultset, in contrast to ROLLUP/CUBE.

**Comment by alexey-milovidov** [comment]
Please make some edits to the documentation.

**Comment by akuzm** [comment]
It is a part of what, then?
Should WITH TOTALS be prohibited for INSERT SELECT?

A query that works differently depending on context is a usability failure.

**Comment by alexey-milovidov** [comment]
> It is a part of what, then?

Totals an extremes are separate (secondary) resultsets.
BTW, in older ClickHouse versions they were output to client even in INSERT SELECT query.

> Should WITH TOTALS be prohibited for INSERT SELECT?

Yes, we can do it.
