### ISSUE TITLE
Block structure mismatch when using transform on String column and default to Null

### ISSUE THREAD

**Issue by durchgedreht** [ClickHouse/ClickHouse#15233]
I have a fact table with a String column and use transform in my view to replace/rename the string values to be human readable. In the default case I'd like to set Null. The creation of the view is successful, but querying the table trows an exception. When I use an empty String all works!? The String column in the fact table is defines as Nullable. 

Clickhouse Version:  20.3.4.10

```
CREATE VIEW IF NOT EXISTS `db`.`my_view`
    AS SELECT

        transform(fact.`sa_type`, ['a', 'b', 'c'],['ReplacmentA', 'ReplacmentB', 'ReplacmentC'], '') as works,
        transform(fact.`sa_type`, ['a', 'b', 'c'],['ReplacmentA', 'ReplacmentB', 'ReplacmentC'], Null) as error
            FROM `db`.`my_table` fact
    ;
```

 SQL Error [171]: ClickHouse exception, code: 171, host: localhost, port: 8003; Code: 171, e.displayText() = DB::Exception: Block structure mismatch in QueryPipeline stream: different columns.

I found some bugs related to the 'Block structure mismatch' but not in this shape. I'll see if I can replicate the issue in a newer version.

**Comment by den-crane** [comment]
try to remove alias `fact.`

and query columns with table `my_table.sa_type` or just `sa_type`

**Comment by durchgedreht** [comment]
No, doesn't work. Can't get any data out of it, even Select ```count(*) from my_table``` leads to:

```
SQL Error [171]: ClickHouse exception, code: 171, host: localhost, port: 8003; Code: 171, e.displayText() = DB::Exception: Block structure mismatch in QueryPipeline stream: different columns:
sa_type Nullable(Nothing) Nullable(size = 0, Nothing(size = 0), UInt8(size = 0))
sa_type Nullable(Nothing) Const(size = 0, Nullable(size = 1, Nothing(size = 1), UInt8(size = 1))) (version 20.3.4.10 (official build))
```

**Comment by durchgedreht** [comment]
That's without the fact already ;-)

**Comment by den-crane** [comment]
Can you show DDL. `show create table my_table` Need to see an engine and column types.

**Comment by den-crane** [comment]
> 20.3.4.10

very old release.

And check that issue exists in the latest 20.3.19.4

**Comment by durchgedreht** [comment]
FYI: I removed a bunch of fields in the ... section. But the most important stuff is there.

```
CREATE TABLE my_db.my_table (`delivery_date` DateTime, `event_records` Int64, `sa_type` Nullable(String), ...) ENGINE = MergeTree ORDER BY (delivery_date, account_id, channel_id, s3_hash) SETTINGS index_granularity = 8192
```

Definitely will test in newer version. We're planning hop on the newest stable version soon.

**Comment by den-crane** [comment]
I could not reproduce it in 20.10

```sql

CREATE TABLE my_table (delivery_date DateTime, event_records Int64, sa_type Nullable(String)) 
ENGINE = MergeTree ORDER BY tuple()

insert into my_table select today(), number, 'a' from numbers(1000);
insert into my_table select today(), number, 'c' from numbers(1000);
insert into my_table select today(), number, null from numbers(1000);

CREATE VIEW IF NOT EXISTS my_view
    AS SELECT
        transform(sa_type, ['a', 'b', 'c'],['ReplacmentA', 'ReplacmentB', 'ReplacmentC'], '') as works,
        transform(sa_type, ['a', 'b', 'c'],['ReplacmentA', 'ReplacmentB', 'ReplacmentC'], Null) as error
            FROM my_table 
    ;


SELECT * FROM my_view format Null;
Ok.


```

**Comment by durchgedreht** [comment]
Hi,
I can confirm the mentioned behaviour, your sample code works here as well! Stripping down our statement line by line I found that we have a dependency to another field that is created by IF statement and is even using the same alias and a join column as well. Even this works ok when I try to add that to your sample code. Unfortunately the joined table and main table include millions of rows (with data I must not share).  

But testing this isolated code I found a strange behaviour that might be related to this behaviour:
When transform is having 'Null' as default ALL columns are nulled!

try executing this stand alone and compare the results or works to error. 

```

CREATE TABLE my_table10 (a_id Nullable(Int64), delivery_date DateTime, event_records Int64, sa_type Nullable(String)) 
ENGINE = MergeTree ORDER BY tuple();

insert into my_table10 select 1 ,today(), number, 'a' from numbers(1);
insert into my_table10 select 2 ,today(), number, 'c' from numbers(1);
insert into my_table10 select null ,today(), number, null from numbers(1);
insert into my_table10 select null ,today(), number, 'd' from numbers(1);

CREATE TABLE my_table20 (b_id Nullable(Int64), delivery_date DateTime, event_records Int64, sa_type Nullable(String)) 
ENGINE = MergeTree ORDER BY tuple();

insert into my_table20 select 1,today(), number, 'a' from numbers(2);
insert into my_table20 select null,today(), number, 'c' from numbers(2);
insert into my_table20 select 3,today(), number, null from numbers(2);
insert into my_table20 select null,today(), number, 'd' from numbers(2);

CREATE VIEW IF NOT EXISTS my_view10
    AS SELECT
    	sa_type,
        transform(sa_type, ['a', 'b', 'c'],['ReplacmentA', 'ReplacmentB', 'ReplacmentC'], Null) as error,
        transform(sa_type, ['a', 'b', 'c'],['ReplacmentA', 'ReplacmentB', 'ReplacmentC'], '') as works,
        transform(sa_type, ['a', 'b', 'c'],['ReplacmentA', 'ReplacmentB', 'ReplacmentC'], 'Foo') as worksB,
		if (error='int' , 'N/A', b.sa_type)  as x
	FROM default.my_table10  a
    Left JOIN default.my_table20  b on a.a_id = b.b_id;
	

SELECT * FROM my_view10;
```

Result:

|sa_type|error|works|worksB|x|
|-------|-----|-----|------|-|
|a|null|ReplacmentA|ReplacmentA|a|
|a|null|ReplacmentA|ReplacmentA|a|
|null|null|null|null|null|
|d|null||Foo|null|
|c|null|ReplacmentC|ReplacmentC|null|

Shouldn't error have same values as works where sa_type equals 'a', 'b' or 'c'?

**Comment by alexey-milovidov** [comment]
@durchgedreht Yes, it is known behaviour of function transform - it does not support nullable arguments.
