### ISSUE TITLE
Rename Clickhouse Index

### ISSUE THREAD

**Issue by iqDF** [ClickHouse/ClickHouse#15234]
Hi Clickhouse team.

Thank you in advance.
I have a question today. I wonder if you guys support  renaming Index. Let's say I have created a table like so:

```
CREATE TABLE [IF NOT EXISTS] [db.]table_name [ON CLUSTER cluster]
(
    name1 [type1] [DEFAULT|MATERIALIZED|ALIAS expr1] [TTL expr1],
    name2 [type2] [DEFAULT|MATERIALIZED|ALIAS expr2] [TTL expr2],
    ...
    INDEX index_name1 expr1 TYPE type1(...) GRANULARITY value1,
    INDEX index_name2 expr2 TYPE type2(...) GRANULARITY value2
) ENGINE = MergeTree()
```

Now let's say I want to rename index_name1.

- What would be the SQL statement to change `index_name1` to `index_newname``
- What clickhouse version support renaming index with the above SQL statement?

Sincerely,
iqDF

**Comment by den-crane** [comment]
No such feature as index rename 

Just create a new index with a new name and drop the old one.

https://clickhouse.tech/docs/en/sql-reference/statements/alter/index/

**Comment by iqDF** [comment]
I see. Thanks!
