### ISSUE TITLE
Why clickhouse server clone and rename parts crazily?

### ISSUE THREAD

**Issue by BernieJiangDL** [ClickHouse/ClickHouse#15270]
The log is below:
`2020.09.25 11:51:57.576717 [ 341875 ] {} <Debug> {db}.{table_name}: Cloning part /data1/clickhouse/data/{db}/{table_name}/2020071011_0_55_8_23697/ to /data1/clickhouse/data/{db}/{table_name}/tmp_clone_2020071011_0_55_8_23698
2020.09.25 11:51:57.577110 [ 341875 ] {} <Trace> {db}.{table_name}: Renaming temporary part tmp_clone_2020071011_0_55_8_23698 to 2020071011_0_55_8_23698.
`

I got a few questions about this:

1. Why CH clone and rename file crazily? What does mean by thoes ops? (As the log shows, logging time is 2020.09.25 11:51:57, but the file seems to be 2020071011's data which should have done at 2020071011)

2. Does those steps have impact on the time cost of listenning 9000 port? (It takes longer than usual when client is able to connect the server on 9000 port)

**Comment by filimonov** [comment]
2020071011_0_55_8_23697
2020071011_0_55_8_23698

Last digit changed. That means some mutation (alter update/delete/modify column etc) was applied to a part.

When mutating data clickhouse touches every part in the table (even if it was noop mutation for that part).

Regarding loading time - what are your observations here? Afair it starts mutations after table is loaded. But maybe it can slow down loading of other tables.

**Comment by BernieJiangDL** [comment]
> 2020071011_0_55_8_23697
> 2020071011_0_55_8_23698
> 
> Last digit changed. That means some mutation (alter update/delete/modify column etc) was applied to a part.
> 
> When mutating data clickhouse touches every part in the table (even if it was noop mutation for that part).
> 
> Regarding loading time - what are your observations here? Afair it starts mutations after table is loaded. But maybe it can slow down loading of other tables.

If the delete op is executed with partition field which is like "alter table xxx delete where {partition_field} = xxxx and ....", the clickhouse still touches every part or only touches the part in that perticular partition folder?

**Comment by den-crane** [comment]
@BernieJiangDL for now clickhouse touches every part for any mutation (alter update/delete)

**Comment by BernieJiangDL** [comment]
> @BernieJiangDL for now clickhouse touches every part for any mutation (alter update/delete).
> This behavior is by design. It needs to do consistent mutations.
> 
> Mutations has been implemented for rare admin operations (twice a year) not for daily business tasks.

Got u! Thanks

**Comment by filimonov** [comment]
See also #12188 #13403
