### ISSUE TITLE
Add summarized column to SummingMergeTree

### ISSUE THREAD

**Issue by byx313** [ClickHouse/ClickHouse#15278]
Hello guys,I have a SummingMergeTree engine table like 
`ENGINE = SummingMergeTree((value_a,value_b))`
Now I would like to add a `value_c` UInt64 to table,is that a way I can add value `value_c` to summarized column array?

**Comment by den-crane** [comment]
There is no easy way to change this list `(value_a,value_b)`. 
Usually it is excessive section and you can create just SummingMergeTree() then Summing will sum all columns except columns in ORDERBY list.

Options how to change it:
1. detach table XXX;
   vi /var/lib/clickhouse/metadata/{db}/{table}.sql # edit file manually and change that list.

2. create a new table YYY with exactly the same structure as XXX but with new ((value_a,value_b)) list . 
    alter table YYY attach partition .... from XXX; # for each partition in XXX
    rename table XXX to XXX_old, YYY to XXX;
    drop table XXX_old

**Comment by byx313** [comment]
thank you den!
