### ISSUE TITLE
`groupBitmapState` RBM slow

### ISSUE THREAD

**Issue by ZonghaoWang** [ClickHouse/ClickHouse#15271]
when I groupBitmapState an UInt32, it can process 250M items per second, it is fast though

our table has two column, face and people, ordered by people, and one people has 10 faces average, so the column has much replcated people ID, can it accerate the groupBitmapState function? (when current item equal last item, we should not access the RBM in memory or cache)

**Comment by ZonghaoWang** [comment]
is here?
![image](https://user-images.githubusercontent.com/11403656/94234893-2bbb3b00-ff3d-11ea-9a81-d4bac1f24cb2.png)

I just think it can accerate the groupAgg speed simply, but I donot benchmark them

**Comment by alexey-milovidov** [comment]
> when current item equal last item, we should not access the RBM in memory or cache

Yes, it is possible and this optimization is easy to implement.
Just track the last value in `RoaringBitmapWithSmallSet` or make this optimization in `SmallSet`.
Compare with the last value on insertion.
