### ISSUE TITLE
Can I create MaterializedView over remote table?

### ISSUE THREAD

**Issue by winter7** [ClickHouse/ClickHouse#15295]
There are 2 clusters.
I create table `base` and table `destination` on `cluster_1`.
```
create table base (id Int8, name String) ENGINE=MergeTree() order by id;
create table destination (id Int8, cnt Int8) ENGINE=MergeTree() order by id;
```
I create materialized view `view` on `cluster_1` and it's working as expected.
```
create MATERIALIZED VIEW view to destination as select id,count(name) as cnt from test;
```
**And here is the problem**. I create table `destination` and materialized view `view` on `cluster_2` which is based on table `test` from `cluster_1`.
```
create table destination (id Int8, cnt Int8) ENGINE=MergeTree() order by id;
create MATERIALIZED VIEW view to destination as select id,count(name) as cnt from remote('cluster_1',default.test,'default','') group by id;
```
I get exception:
```
Received exception from server (version 20.4.4):
Code: 49. DB::Exception: Received from localhost:9000. DB::Exception: Logical error while creating StorageMaterializedView. Could not retrieve table name from select query..
```
It seems like materializedView source cannot be a remote table. And then I try to create a remote materializedView on `cluster_1`.
```
create MATERIALIZED VIEW remote_view to remote('cluster_2',default.destination,'default','') as select id,count(name) as cnt from test
```
Fail again:
```
Syntax error: failed at position 48:
Expected one of: CONSTRAINT, identifier, column declaration, INDEX, list of elements, columns or indices declaration list, table property (column, index, constraint) declaration
```

Do you know how to create MaterializedView over remote tables?

**Comment by winter7** [comment]
The reason I ask this question is that I want to use Kafka Engine. I wonder if I should temporarily add some ClickHouse instances with kafka engine table as consumers when Kafka traffic surges and convert data by materialized View to the original (remote) Clickhouse instances. Is this a good way to deal with the sudden increase in Kafka traffic?

**Comment by den-crane** [comment]
MaterializedView is an insert trigger. 

It gets data from **INSERT**. 

It **never** reads (selects) from table.

You must create MaterializedView at a server where inserts happen. You can re-route MaterializedView output to remote server. `create table xxx as remote(); create Materialized View .... to xxx as select .....`

**Comment by winter7** [comment]
Thank you! I think `create table xxx as remote();` is what I missed in my second attempt.
