### ISSUE TITLE
Incremental restore of a replicated table.

### ISSUE THREAD

**Issue by nikk0** [ClickHouse/ClickHouse#15292]
Hello.
I would like to incrementally restore a table by deleting data parts (in / var / lib / clikhouse / ..) that have been created AFTER the backup (using clikchouse-backup). This could save network and disk bandwith.

 To do this, I use DETACH TABLE / rm data part (locally)  / ATTACH TABLE. On a replicated table, the data part is always retrieved from a remote replica at ATTACH time. The data part created after the backup is thus still present.

 How to get rid of this behaviour ?
 How to delete the remote data parts on the remote replicas ?
 Is there a way to tell CH that my table is now the "initiator"/master of the replication ? ( in order to propagate the deletion of the data part)

 Thanks in advance. 

 nikko

**Comment by den-crane** [comment]
I see you got some help in Telegram. 
@nikk0  Do you need a further assistance? Or it's solved?
