### ISSUE TITLE
Scalar subquery optimization

### ISSUE THREAD

**Issue by vladsaraykin** [ClickHouse/ClickHouse#15294]
**Describe the bug**
Scalar some type doesn't exist
I checked with table, which was be created by engine of memory. And this query is worked.
But MergeTree doesn't work.

**How to reproduce**
1) create table TestTable (`column` String, start DateTime, end DateTime) engine MergeTree order by start;
2) insert into TestTable (column, start, end) values
  ('test', toDateTime('2020-07-20 09:00:00'), toDateTime('2020-07-20 20:00:00')),
  ('test1', toDateTime('2020-07-20 09:00:00'), toDateTime('2020-07-20 20:00:00')),
  ('test2', toDateTime('2020-07-20 09:00:00'), toDateTime('2020-07-20 20:00:00'));

* Which ClickHouse server version to use
(version 20.4.5.36 (official build))

* Queries to run that lead to unexpected result
SELECT column,
       (SELECT d from (select [1, 2, 3, 4] as d)) as d
FROM TestTable
where column == 'test'
GROUP BY column;

**Error message and/or stacktrace**
Code: 486, e.displayText() = DB::Exception: Scalar `12915720423643251111_12130513838789205919` doesn't exist (internal bug) (version 20.4.5.36 (official build))

**Additional context**
When 
SET enable_scalar_subquery_optimization=0;
query is worked

**Comment by den-crane** [comment]
```
20.10.1.4704

┌─column─┬─d─────────┐
│ test   │ [1,2,3,4] │
└────────┴───────────┘
```

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/11621
already fixed: https://github.com/ClickHouse/ClickHouse/pull/11767
