### ISSUE TITLE
system.parts.hash_of_uncompressed_files

### ISSUE THREAD

**Issue by nikk0** [ClickHouse/ClickHouse#15303]
Hello. 

How is computed the field system.parts.hash_of_uncompressed_files ? 

What is its purpose ?

Regards.

nikk0

**Comment by alexey-milovidov** [comment]
There are some files that we don't compress, like `.idx`, `.mrk`.
But we still calculate hash of the data in these files, accumulate it and present in the `hash_of_uncompressed_files` field.

The purpose is the same as for other hashes - to compare them to find possible difference.

**Comment by alexey-milovidov** [comment]
If table is replicated, hashes will be used to ensure that data on replicas will be byte-identical after replication. It protects from bit-flip errors in HDD (bit rot), bit flips in RAM on the server, RAM on the network controller, RAM on the network switches, data corruption during network transfer, memory stomping bugs in software, etc...

**Comment by alexey-milovidov** [comment]
It is computed with `HashingWriteBuffer`, non-cryptographic hash function `CityHash_v1_0_2::CityHash128WithSeed` is used.
