### ISSUE TITLE
Materialized view return duplicates rows

### ISSUE THREAD

**Issue by andrey-potyomkin** [ClickHouse/ClickHouse#15315]
1. I creating materialized view for extract unique tuples using following SQL:

```
CREATE MATERIALIZED VIEW tuples_view
ENGINE = MergeTree()
PARTITION BY (date)
ORDER BY (date)
AS SELECT arrayJoin(tuples_list).1 as val_1,
          arrayJoin(tuples_list).2 as val_2,
          arrayJoin(tuples_list).4 as val_3,
          arrayJoin(tuples_list).3 as val_4
FROM(
SELECT  arrayReduce('groupUniqArray', arrayConcat(groupArray(date_time, column_1, column_2, column_3),
        groupArray(date_time, column_4, column_5, column_6))) as tuples_list
FROM data)
```

2. After that I inserting some data in table with the name 'Data' and following structure:

| date       | column_1 | column_2 | column_3 | column_4 | column_5 | column_6 |
|------------|----------|----------|----------|----------|----------|----------|
| 2020-09-01 | A1       | A2       | A3       | B1       | B2       | B3       |
| 2020-09-01 | B1       | B2       | B3       | A1       | A2       | A3       |
| 2020-09-01 | A1       | A2       | A3       | C1       | C2       | C3       |

3. I hope that materialized view contain the following data:

| date       | val_1 | val_2 | val_3 |
|------------|-------|-------|-------|
| 2020-09-01 | A1    | A2    | A3    |
| 2020-09-01 | B1    | B2    | B3    |
| 2020-09-01 | C1    | C2    | C3    |

4. But materialized view contain data with duplicates:

| date       | val_1 | val_2 | val_3 |
|------------|-------|-------|-------|
| 2020-09-01 | A1    | A2    | A3    |
| 2020-09-01 | A1    | A2    | A3    |
| 2020-09-01 | B1    | B2    | B3    |
| 2020-09-01 | B1    | B2    | B3    |
| 2020-09-01 | C1    | C2    | C3    |
| 2020-09-01 | C1    | C2    | C3    |

5. But if I running following SELECT from SQL command, which I used, when creating materialized view:

```
SELECT arrayJoin(tuples_list).1 as val_1,
          arrayJoin(tuples_list).2 as val_2,
          arrayJoin(tuples_list).4 as val_3,
          arrayJoin(tuples_list).3 as val_4
FROM(
SELECT  arrayReduce('groupUniqArray', arrayConcat(groupArray(date_time, column_1, column_2, column_3),
        groupArray(date_time, column_4, column_5, column_6))) as tuples_list
FROM data)
```

I getting the data without duplicates.

Am I wrong in my strategy?

**Comment by den-crane** [comment]
MaterializedView is an insert trigger.

It gets data from *INSERT*.

It *never* reads (selects) from table.

>groupArray(date_time, column_1, column_2, column_3)

What is it? Such syntax is not supported. Can you show `desc data`

**Comment by andrey-potyomkin** [comment]
> What is it? Such syntax is not supported. 

Oh, sorry. I checked again SQL query from my previous message and it's written with mistake. In my original SQL used syntax groupArray((date_time, column_1, column_2, column_3)) and it's working.

```
SELECT groupArray((date, column_1, column_2, column_3))
FROM db.test_data

[('2020-10-01','A1','A2','A3'),('2020-10-01','B1','B2','B3'),('2020-10-01','A1','A2','A3')]
```

> Can you show desc data

```
DESCRIBE TABLE db.test_data

date    Date
column_1        Nullable(String)
column_2        Nullable(String)
column_3        Nullable(String)
column_4        Nullable(String)
column_5        Nullable(String)
column_6        Nullable(String)
```

> It gets data from INSERT.
It never reads (selects) from table.

Really. Apparently MATERIALIZED VIEW don't supporting SELECT with aggregate functions for the multiple rows.

May be anybody have an idea how I can create VIEW with unique tuples from the multiple columns?
I tried to use ReplacingMergeTree with the ORDER(date, val_1, val_2, val_3), but it's not worked, because val_1, val_2 and val_3 will can Nullable.

**Comment by den-crane** [comment]
> Apparently MATERIALIZED VIEW don't supporting SELECT with aggregate functions for the multiple rows.

MV supports SELECT with aggregate functions, but aggregations from different inserts should be done by a table engine. 
In your case you have used `ENGINE = MergeTree() PARTITION BY (date) ORDER BY (date)` and this engine does not collapse rows (duplicates). 

>I tried to use ReplacingMergeTree with the ORDER(date, val_1, val_2, val_3), 
>but it's not worked, because val_1, val_2 and val_3 will can Nullable.

Nullable OrderBY is under development https://github.com/ClickHouse/ClickHouse/pull/12433 https://github.com/ClickHouse/ClickHouse/pull/12455 and restricted by default `allow_nullable_key, false, "Allow Nullable types as primary keys.`

But I doubt that MV is a right choice for you. I think you should your `select from data` directly.
