### ISSUE TITLE
Fetch Single Row From Select Query Performance

### ISSUE THREAD

**Issue by stcharitak** [ClickHouse/ClickHouse#15314]
In a SELECT query, I want to return a single row record out of billions of rows in ClickHouse. I know that Clickhouse is not meant for single queries but here I have no other choice. I would like to enhance the performance of the query as much as possible. The query is the following:

```select * from products where un_id='us-f032f8df-65c9-4f0b-8df2-ddb3a436ae7e' and organization_id='test' and request_time >= '2020-09-25 00:00:00' limit 1```

organization_id and request_time are both partitioning keys. 

My default settings for max_threads are 4 while for max_block_size is 65505. I have also tried setting max_threads=1, max_block_size=1024 (answer from a previous post here) but this did not really help with the speed of the query. 

 I would like to achieve a response in less than 4 seconds. Is sth like this possible with this amount of data (billions of records)? 

Thanks in advance

**Comment by den-crane** [comment]
You have no choice except to move un_id to the beginning of PRIMARYINDEX.
And try to clean un_id from 'us-' and save UUID as UUID (FIXED String) not a String.

```

create table product (
         country String, 
         un_id UUID, 
         organization_id LowCardinality(String),
         request_time DateTime) 
Engine=MergeTree 
partition by (organization_id, toYYYYMM(request_time))
order by (country, un_id, request_time)
settings index_granularity=1024;

insert into product select 'us', generateUUIDv4(), 'test', toDateTime('2020-01-01 00:00:00') + intDiv(number, 100)
from numbers(1000000000);

0 rows in set. Elapsed: 551.801 sec.


SELECT *
FROM product
LIMIT 100000, 1

┌─country─┬────────────────────────────────un_id─┬─organization_id─┬────────request_time─┐
│ us      │ 755c7b41-89e2-4bc7-8619-74063068dd67 │ test            │ 2020-02-29 20:50:32 │
└─────────┴──────────────────────────────────────┴─────────────────┴─────────────────────┘

------------------------------------------------------------------------------------------------------------------------------------------------

TEST:


SET max_threads = 1;


SELECT *
FROM product
WHERE (organization_id = 'test') AND (country = 'us') AND (un_id = '755c7b41-89e2-4bc7-8619-74063068dd67') AND (request_time >= '2020-02-29 20:50:00')

┌─country─┬────────────────────────────────un_id─┬─organization_id─┬────────request_time─┐
│ us      │ 755c7b41-89e2-4bc7-8619-74063068dd67 │ test            │ 2020-02-29 20:50:32 │
└─────────┴──────────────────────────────────────┴─────────────────┴─────────────────────┘

1 rows in set. Elapsed: 0.004 sec. Processed 15.36 thousand rows, 491.85 KB (4.33 million rows/s., 138.74 MB/s.)




```

**Comment by alexey-milovidov** [comment]
It's better to make ORDER BY `organization_id`, `request_time`, not PARTITION BY.

**Comment by stcharitak** [comment]
> You have no choice except to move un_id to the beginning of PRIMARYINDEX.
> And try to clean un_id from 'us-' and save UUID as UUID (or as hex/FIXED String) not a String.
> 
> ```
> 
> create table product (
>          country String, 
>          un_id UUID, 
>          organization_id LowCardinality(String),
>          request_time DateTime) 
> Engine=MergeTree 
> partition by (organization_id, toYYYYMM(request_time))
> order by (country, un_id, request_time)
> settings index_granularity=1024;
> 
> insert into product select 'us', generateUUIDv4(), 'test', toDateTime('2020-01-01 00:00:00') + intDiv(number, 100)
> from numbers(1000000000);
> 
> 0 rows in set. Elapsed: 551.801 sec.
> 
> 
> SELECT *
> FROM product
> LIMIT 100000, 1
> 
> ┌─country─┬────────────────────────────────un_id─┬─organization_id─┬────────request_time─┐
> │ us      │ 755c7b41-89e2-4bc7-8619-74063068dd67 │ test            │ 2020-02-29 20:50:32 │
> └─────────┴──────────────────────────────────────┴─────────────────┴─────────────────────┘
> 
> ------------------------------------------------------------------------------------------------------------------------------------------------
> 
> TEST:
> 
> 
> SET max_threads = 1;
> 
> 
> SELECT *
> FROM product
> WHERE (organization_id = 'test') AND (country = 'us') AND (un_id = '755c7b41-89e2-4bc7-8619-74063068dd67') AND (request_time >= '2020-02-29 20:50:00')
> 
> ┌─country─┬────────────────────────────────un_id─┬─organization_id─┬────────request_time─┐
> │ us      │ 755c7b41-89e2-4bc7-8619-74063068dd67 │ test            │ 2020-02-29 20:50:32 │
> └─────────┴──────────────────────────────────────┴─────────────────┴─────────────────────┘
> 
> 1 rows in set. Elapsed: 0.004 sec. Processed 15.36 thousand rows, 491.85 KB (4.33 million rows/s., 138.74 MB/s.)
> ```
> 
> Elapsed: 0.004 sec. is less than 4 sec.
> because PRIMARYindex is `(country, un_id, request_time)` and it addresses ` (country = 'us') AND (un_id = '755c7b41-89e2-4bc7-8619-74063068dd67') AND (request_time >= '2020-02-29 20:50:00')`

thanks for the detailed answer. I already test it and I get really fast results.

**Comment by den-crane** [comment]
It's because you partitioned you table by `organization_id`--  `PARTITION BY (organization_id, toMonday(request_time))`
But your queries does not have `organization_id` predicate.

Simply change partition key to `PARTITION BY (toMonday(request_time))`
or better to `PARTITION BY (toYYYYMM(request_time))`

And you can change granularity to 256 `index_granularity=256`

Also if you use sharding you can shard by un_id and enable `optimize_skip_unused_shards`.


And the last thing. Why do you use CH? CH is not designed for K/V. Try K/V databases. Redis, Cassandra. You will speedup your queries 1000 times with a cluster of  Cassandra.
