### ISSUE TITLE
order by does not support  COLUMNS expression

### ISSUE THREAD

**Issue by detailyang** [ClickHouse/ClickHouse#15317]
**Use case**

Here is the table:  there are many columns like `tags_*` which is dynamically generated and don't know the column name

| tags_host  | tags_ns | tags_* and so on|timestamp|value|
| ------------- | ------------- |------|----|-----|
| hosta | ns1 | |2020-09-24 13:51:00|100
| hostb | ns2 ||2020-09-24 13:51:00|100
| hosta | ns1  ||2020-09-24 13:51:30|400
| hostb | ns2  ||2020-09-24 13:51:30|400

I want to group by all tags_ via `COLUMNS('tags_')` and order by `COLUMNS('tags_'`) as the following:

```sql
select
    COLUMNS('tags_'),
    intDiv(toUInt64(timestamp), 30) * 30 AS t,
    max(value)
from
    table
GROUP BY
    t,
    COLUMNS('tags_')
ORDER BY
    COLUMNS('tags_'),
    t
```

But the order by looks like doesn't support the COLUMNS expression.

**Describe the solution you'd like**

Support COLUMNS expression or another SQL way to support this?

**Comment by alexey-milovidov** [comment]
Yes, it will be better to add the support for COLUMNS in ORDER BY.
The only detail is to support ASC/DESC, COLLATE and WITH FILL modifiers.

**Comment by detailyang** [comment]
@alexey-milovidov Hello. So the only solution is to support COLUMNS in ORDER BY?

**Comment by alexey-milovidov** [comment]
@detailyang You can also generate the list of columns by
```
EXPLAIN SYNTAX SELECT COLUMNS('tags_') FROM table
```
And then copy-paste the generated list.

**Comment by detailyang** [comment]
@alexey-milovidov thanks. Gotcha, I will try the SQL or implement COLUMNS in ORDER BY :)

**Comment by amosbird** [comment]
you can also do
```
WITH tuple(COLUMNS('tags_')) AS o
select
    COLUMNS('tags_'),
    intDiv(toUInt64(timestamp), 30) * 30 AS t,
    max(value)
from
    table
GROUP BY
    t,
    COLUMNS('tags_')
ORDER BY o, t
```

**Comment by detailyang** [comment]
@amosbird Many thanks:) It works.

Consider it's solved
