### ISSUE TITLE
Getting lots of ' Connection reset by peer, while reading from socket' and few other issues

### ISSUE THREAD

**Issue by John-belt** [ClickHouse/ClickHouse#15311]
I am running click house version '20.6.4' on cluster(3 instance) with default settings. While walking through the logs i found these logs in abundance.

1)**ServerErrorHandler: Code: 210, e.displayText() = DB::NetException: Connection reset by peer, while reading from socket**

2)**ServerErrorHandler: Code: 210, e.displayText() = DB::NetException: Connection reset by peer, while writing to socket**

3)**ConnectionPoolWithFailover: Connection failed at try №1, reason: Code: 209, e.displayText() = DB::NetException: Timeout: 
      connect timed out: 172.16.A.B:9000**

I am using go-clickhouse client with default setting(no change to any timeout)
Inserting data almost every minute(around 60-70k rows) 
Even though there don't seem to any impact but getting lot of these.
My ping b/w replicas is 3-20ms with around 2-3 % packet loss.

These are my timeout related settings:
	 name											  value       type
	 
	 connect_timeout                                  10          SettingSeconds             
	 connect_timeout_with_failover_ms                 50          SettingMilliseconds        
	 connect_timeout_with_failover_secure_ms          100         SettingMilliseconds        
	 receive_timeout                                  300         SettingSeconds             
	 send_timeout                                     300         SettingSeconds             
	 tcp_keep_alive_timeout                           0           SettingSeconds             
	 idle_connection_timeout                          3600        SettingUInt64              
	 distributed_directory_monitor_sleep_time_ms      100         SettingMilliseconds        
	 distributed_directory_monitor_max_sleep_time_ms  30000       SettingMilliseconds        
	 insert_in_memory_parts_timeout                   600000      SettingMilliseconds        
	 replication_alter_columns_timeout                60          SettingUInt64              
	 insert_quorum_timeout                            600000      SettingMilliseconds        
	 use_client_time_zone                             0           SettingBool                
	 insert_distributed_timeout                       0           SettingUInt64              
	 distributed_ddl_task_timeout                     180         SettingInt64               
	 stream_poll_timeout_ms                           500         SettingMilliseconds        
	 http_connection_timeout                          1           SettingSeconds             
	 http_send_timeout                                1800        SettingSeconds             
	 http_receive_timeout                             1800        SettingSeconds             
	 query_profiler_real_time_period_ns               1000000000  SettingUInt64              
	 query_profiler_cpu_time_period_ns                1000000000  SettingUInt64              
	 max_execution_time                               0           SettingSeconds             
	 timeout_overflow_mode                            throw       SettingOverflowMode        
	 timeout_before_checking_execution_speed          10          SettingSeconds             
	 temporary_live_view_timeout                      5           SettingSeconds             
	 lock_acquire_timeout                             120         SettingSeconds             
	 mark_cache_min_lifetime                          0           SettingUInt64              
	 date_time_input_format                           basic       SettingDateTimeInputFormat 
 
 
 Is there anything settings i can change to minimize these errors??
 Should i worried about these error??
And what does error code 210 and 209 exactly??

**Comment by den-crane** [comment]
https://stackoverflow.com/questions/64064438/getting-lot-of-dbnetexception-connection-reset-by-peer-while-reading-from-s
