### ISSUE TITLE
Question about RPM packages

### ISSUE THREAD

**Issue by spihiker** [ClickHouse/ClickHouse#15356]
From the version 20.3.18.10, The size of official RPM package  is much smaller .why? what happened?
eg:clickhouse-common-static-20.3.18.10-2.x86_64.rpm 
thanks.

**Comment by filimonov** [comment]
I think it's caused by https://github.com/ClickHouse/ClickHouse/pull/14549 

@alesapin build scripts / docker images versioning don't work yet for 20.3?

**Comment by filimonov** [comment]
Binary size changed:

```
root@0bc4d3888cc4:/# ls -la /usr/bin/clickhouse
-rwxr-xr-x 1 root root 284583976 Aug 14 17:58 /usr/bin/clickhouse

root@6315cd265f86:/# ls -la /usr/bin/clickhouse
-rwxr-xr-x 1 root root 246814792 Sep  8 03:20 /usr/bin/clickhouse
```

Diff in build options
![Screenshot-20200928183625-1496x576](https://user-images.githubusercontent.com/1549571/94460793-8b257f00-01b9-11eb-8d07-41d9aad13c46.png)

**Comment by spihiker** [comment]
Thank you.
