### ISSUE TITLE
MaterializeMySQL's query performance

### ISSUE THREAD

**Issue by chrootweili** [ClickHouse/ClickHouse#15359]
I noticed that the `MaterializeMySQL` is using ReplacingMergeTree Engine and rewrite query with FINAL keywords.

But I found this in the document in https://clickhouse.tech/docs/en/sql-reference/statements/select/from/ :
> In most cases, avoid using FINAL. The common approach is to use different queries that assume the background processes of the MergeTree engine have’t happened yet and deal with it by applying aggregation (for example, to discard duplicates).

In my test of ReplacingMergeTree(not MaterializeMySQL) with about 2000M rows of data using a simple group by query,
`final` keywords cost 16.712s while 0.733s without `final`.

Does the `MaterializeMySQL` have the same performance?

**Comment by alexey-milovidov** [comment]
Yes, it will have the same performance as queries with FINAL.
