### ISSUE TITLE
Exception: Stack size too large about materialized table when insert into ....

### ISSUE THREAD

**Issue by zhoupengbo** [ClickHouse/ClickHouse#15352]
(you don't have to strictly follow this form)

**Describe the bug**
my clickhouse version is 19.17.10.1-2.
today , i test the feature of materialized. below is the steps:
```
# 1. create origion table
CREATE TABLE test_view (     `id` Int32,      `execution_time` Date,      `keeper_code` String) ENGINE = MergeTree()  PARTITION BY toYYYYMMDD(execution_time)  ORDER BY id ;
# 2. create view of origion table 
CREATE MATERIALIZED VIEW IF NOT EXISTS test_view_materialized to test_view as select execution_time,count() from test_view group by execution_time;
# insert datas
insert into test_view values (1,'2020-01-02','zhou');
```
then , error is occur. see below errors:
```
Code: 306. DB::Exception: Received from localhost:9000. DB::Exception: Stack size too large. Stack address: 0x7fadaf5fa000, frame address: 0x7fadaf9f9ac0, stack size: 4195648, maximum stack size: 8388608.
```

**Comment by alexey-milovidov** [comment]
> CREATE MATERIALIZED VIEW IF NOT EXISTS test_view_materialized 
**to test_view** as select execution_time,count() **from test_view** group by execution_time;

It means that you are going to store the data of the materialized view in the same table - infinite loop.

**Comment by alexey-milovidov** [comment]
You have to create separate table as a storage for materialized view (for `TO` clause) or remove `TO` clause altogether - then it will create the inner storage automatically.

**Comment by filimonov** [comment]
https://altinity.com/blog/clickhouse-materialized-views-illuminated-part-1

**Comment by zhoupengbo** [comment]
this is my fault, thank you all ! Sorry for not replying！@filimonov @alexey-milovidov
