### ISSUE TITLE
On the problem of sparse index

### ISSUE THREAD

**Issue by qinglok** [ClickHouse/ClickHouse#15360]
I have a table with more than 10 billion data. The structure is like thiss:
`CREATE TABLE test (`a` String, `b` String) ENGINE = MergeTree() ORDER BY (a, b)`
When the query condition is a = '...', it takes less than 1 second.
When the query condition is b = '...', the time consumption is between 3 and 5 seconds.
I need to be able to achieve both query conditions in less than 1 second.
Any good ideas?

**Comment by den-crane** [comment]
It's not related to a sparse index. 

>Any good ideas?

Two tables with duplicated data:
CREATE TABLE test1 (aString,b String) ENGINE = MergeTree() ORDER BY (a, b)
CREATE TABLE test2 (aString,b String) ENGINE = MergeTree() ORDER BY (b, a)

There is solution for this without inverse indexes and without Z indexes.
In general: CH is not designed for these queries.
