### ISSUE TITLE
Mutations seem to be stuck 

### ISSUE THREAD

**Issue by BernieJiangDL** [ClickHouse/ClickHouse#15369]
When exexute the sql like “select is_done,database,table, count(*) from system.mutations group by is_done,table,database;”
There is always a record that is :
┌─is_done─┬─database──┬─table─┬─count()─┐
│       0         │ test                │ tableName                  │     1          │

The type of mutation for this table is “alter delete”, and the table name doesn't show up in clickhouse-server.log which should have been logged like “cloning part ... , rename ...”.

anyway, this table is always undone(is_done equals 0) in systems.mutations. 

Is there anything wrong with that? Or how to locate the point to this problem?

**Comment by filimonov** [comment]
To be able to help you we need more details:
1) clickhouse version
2) table schema
3) result of `select * from system.mutations where is_done=0`

**Comment by BernieJiangDL** [comment]
> To be able to help you we need more details:
> 
> 1. clickhouse version
> 2. table schema
> 3. result of `select * from system.mutations where is_done=0`

1. ClickHouse server version 20.3.8 revision 54433

2. CREATE TABLE test.scene_cnt_table (`day` Int64 , `hour` Int64 ', `minute` Int64 , `scene` Int64 , `cnt` Int64) ENGINE = ReplicatedMergeTree('/clickhouse/k_cluster/test/tables/{layer}-{shard}/scene_cnt_table', '{replica}') PARTITION BY hour ORDER BY (day, minute, scene) SETTINGS index_granularity = 8192

3. ─is_done─┬─database──┬─table───────────────────────────────────────────────┬─count()─┐
│       0 │ test     │ scene_cnt_table      │       1 │

Need any more info?

**Comment by den-crane** [comment]
@BernieJiangDL What about other system.mutations  columns? **latest_fail_reason, latest_fail_time, parts_to_do** for example?

**Comment by filimonov** [comment]
> Need any more info?

Yes. Full row from `system.mutations` please.

Also - you need to update at least to the latest 20.3 release (20.3.19 currently).

**Comment by BernieJiangDL** [comment]
> @BernieJiangDL What about other system.mutations columns? **latest_fail_reason, latest_fail_time, parts_to_do** for example?

**Comment by BernieJiangDL** [comment]
> > Need any more info?
> 
> Yes. Full row from `system.mutations` please.
> 
> Also - you need to update at least to the latest 20.3 release (20.3.19 currently).

Yes， our ch version is  20.3.8,  and the full row of this table I pasted on my last comment.

**Comment by den-crane** [comment]
It seems it need to process  3208 more parts.

Check several times `select parts_to_do from system.mutations where not is_done`. Is parts_to_do changing ?

**Comment by BernieJiangDL** [comment]
> It seems it need to process 3208 more parts.
> 
> Check several times `select parts_to_do from system.mutations where not is_done`. Is parts_to_do changing ?

Nope, parts_to_do remains the same number 3208 for 3 days.

If clickhouse processes this mutation correctly, I guess the action will be logged. But there is no logs  associated with this table in clichouse-server.log.

Anything wrong with that?

**Comment by filimonov** [comment]
Please update to 20.3.19, let us know if issue will remain

**Comment by BernieJiangDL** [comment]
> Please update to 20.3.19, let us know if issue will remain

Got it!

**Comment by wying8349** [comment]
Hi, I am wondering that did you solved this problem after updating? Thank you very much!
