### ISSUE TITLE
Ability to use system tzdb instead of embedded

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#15361]
ClickHouse versions since 20.4 use embedded tzdata as a primary source. 

That makes impossible for admins to update tzdata w/o rebuilding clickhouse. 

EOL for lts versions is 1 year, so next lts will be supported till about sep/oct 2021.

There are big chances that **EU countries will stop using DST in 2021**. If it will happen it will create a lot of headache for people using ClickHouse with embedded tzdb. 

I propose to change the order or checking (use system installed as primary, embedded as secondary).

Even better option is to introduce a switch in settings to change the priority (system only, embedded only, system first, embedded first).

**Comment by alexey-milovidov** [comment]
Let's introduce a setting in config but don't change the default.
People often forget to update anything on their servers (including tzdata) and only update ClickHouse.

**Comment by alexey-milovidov** [comment]
Closing due to low demand.
