### ISSUE TITLE
FETCH FIRST clause

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#15367]
It is SQL standard alternative to the LIMIT clause:
`OFFSET offset_row_count {ROW | ROWS} FETCH {FIRST | NEXT} fetch_row_count {ROW | ROWS} {ONLY | WITH TIES}`

We should parse it and translate into equivalent `LIMIT n[, m [WITH TIES]]` in parser.
Note that we already support all the required features under more convenient syntax.

**Comment by hexiaoting** [comment]
I want this.

**Comment by CurtizJ** [comment]
In master.
