### ISSUE TITLE
Insert Into too slow

### ISSUE THREAD

**Issue by qinzl1** [ClickHouse/ClickHouse#15383]
clickhouse version：19.9
the two tables ENGINE is MergeTree，Its insert performance is poor
 Progress: 300.28 million rows, 2.00 TB (10.22 thousand rows/s., 68.09 MB/s.)
![image](https://user-images.githubusercontent.com/20242930/94417141-48ac7400-01b2-11eb-9291-fc3f36e44ba6.png)

**Comment by filimonov** [comment]
Default settings for `insert ... select ...` are quire conservative (they not use your RAM too aggressively, and formed blocks are not too big). 

Try adjusting min_insert_block_size_bytes / min_insert_block_size_rows.

Try (for example)
```
set max_insert_threads=4, max_threads=4, min_insert_block_size_bytes = 536870912, min_insert_block_size_rows = 16777216;
```

**Comment by qinzl1** [comment]
@filimonov 
I/O is falling during insertion
![image](https://user-images.githubusercontent.com/20242930/94419550-86f76280-01b5-11eb-98b7-e6bdd95eb60a.png)

**Comment by den-crane** [comment]
> @filimonov
> I/O is falling during insertion
> ![image](https://user-images.githubusercontent.com/20242930/94419550-86f76280-01b5-11eb-98b7-e6bdd95eb60a.png)

Try new CH and --max_insert_threads =4  The maximum number of threads to execute the INSERT SELECT query. Values 0 or 1 means that INSERT SELECT is not run in parallel.

**Comment by filimonov** [comment]
>  I/O is falling during insertion

That is expected. You filled page cache, and/or you you create lot of parts (see parts_to_delay_insert). 

For the page cache - you can't write faster than your disks can write the data in long term, and than clickhouse can merge new parts. 

You can only decrease the number of parts by adjusting the settings listed above, or by adding some where conditions to accept a single partition at a time.

**Comment by qinzl1** [comment]
@filimonov 
thx，i will tried the new version
