### ISSUE TITLE
fullscans to find min and max of partitioning key

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#1540]
```
SELECT version()

┌─version()─┐
│ 1.1.54304 │
└───────────┘

1 rows in set. Elapsed: 0.003 sec. 

SELECT min(date) FROM table 

Received exception from server:
Code: 158. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Limit for rows to read exceeded: 1708523520 rows read (or to read), maximum: 1000000000. 

```

date is partitioning key of that table. So that data can be extracted from meta-information of partitions without fullscan.

**Comment by valyala** [comment]
See the related issue #530 .

**Comment by filimonov** [comment]
Found a workaround for getting min/max of partitioning key (not sure how it will work with new custom partitioning keys later):

```
SELECT 
    min(min_date), 
    max(max_date)
FROM system.parts 
WHERE table = 'table_name'
```

**Comment by alexey-milovidov** [comment]
FYI @amosbird it is similar to the "trivial count optimization".

**Comment by amosbird** [comment]
It can be implemented after projection. We can have builtin/virtual projections with these informations and automatically expands query pipelines. And it might be also possible to cooperate with minmax skip indices.

**Comment by amosbird** [comment]
Resovled by https://github.com/ClickHouse/ClickHouse/pull/26286 .
