### ISSUE TITLE
Functions `countMatches`, `countSubstrings`.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#15413]
Calculate the number of regexp matches or substrings in a string.

**Use case**
Group by the number of matches for text analysis.

**Comment by filipecaixeta** [comment]
Let me work on this issue.
Should we have only ASCII case sensitive or should we include CaseInsensitive, UTF8, CaseInsensitiveUTF8 ?

**Comment by alexey-milovidov** [comment]
For `countMatches` there will be only one function as we have only one `match` function.
For `countSubstrings` there should be four variants that mirror the variants of `position` function.

**Comment by azat** [comment]
countMatches - #16277 and #17459 
countSubstrings - #17347 

Looks like can be closed.
