### ISSUE TITLE
Retry Too many simultaneous queries exception (maybe other transient errors like IO errors as well) on other replicas

### ISSUE THREAD

**Issue by nvartolomei** [ClickHouse/ClickHouse#15414]
**Use case**
Currently if a replicas is overloaded with queries the distributed query will fail straight away, instead we should retry it on a different replicas.

**Describe the solution you'd like**
Check exception received from the remote server, retry it if it is in a list of "retriable" errors.

**Describe alternatives you've considered**
Retry on the client, however not ideal since not all clients have proper retries configured and they would need to know specifically how to handle ClickHouse errors. Also when large number of machines are involved retrying the whole query wastes resources on the whole cluster.

Test case:

```py
from threading import Event, Thread

import pytest

from helpers.cluster import ClickHouseCluster

cluster = ClickHouseCluster(__file__)

node1 = cluster.add_instance('node1', main_configs=['configs/remote_servers.xml'])
node2 = cluster.add_instance('node2', main_configs=['configs/remote_servers.xml', 'configs/concurrency_limit.xml'])


@pytest.fixture(scope="module")
def started_cluster():
    try:
        cluster.start()

        for node in (node1, node2):
            node.query('''CREATE TABLE local_table(id UInt32, val String) ENGINE = MergeTree ORDER BY id;''')

        node1.query(
            '''CREATE TABLE distributed_table(id UInt32, val String) ENGINE = Distributed(test_cluster, default, local_table, id);''')

        yield cluster

    finally:
        cluster.shutdown()


exitFlag = Event()


def keep_node2_busy():
    while not exitFlag.isSet():
        node2.query("SELECT sleep(3)")


def test_start_and_stop_replica_send(started_cluster):
    th1 = Thread(target=keep_node2_busy)
    th1.start()

    # iterate a few times to increase the chance of conflicting with the sleep query
    for _ in range(3):
        node1.query("SELECT count() FROM distributed_table")

    exitFlag.set()

    th1.join()
```

```xml
<!-- only for one node2 -->
<yandex>
    <max_concurrent_queries>1</max_concurrent_queries>
</yandex>

<yandex>
    <remote_servers>
        <test_cluster>
            <shard>
                <replica>
                    <host>node1</host>
                    <port>9000</port>
                </replica>
            </shard>
            <shard>
                <replica>
                    <host>node2</host>
                    <port>9000</port>
                </replica>
            </shard>
        </test_cluster>
    </remote_servers>
</yandex>
```

**Comment by nvartolomei** [comment]
Looks like these retries could be added to `RemoteQueryExecutor` to the read method https://github.com/ClickHouse/ClickHouse/blob/c48d212320bab7fb48257165d6e24f81e005f491/src/DataStreams/RemoteQueryExecutor.cpp#L169.

If I'm not mistaken we can't retry the query after we got first data block so this could be used only for retrying exceptions that would be thrown prior to query execution (too many simultaneous queries is ok to retry but io errors during data receiving are not ok to retry).

**Comment by nvartolomei** [comment]
> If I'm not mistaken we can't retry the query after we got first data block so this could be used only for retrying exceptions that would be thrown prior to query execution (too many simultaneous queries is ok to retry but io errors during data receiving are not ok to retry).

Should ClickHouse in this case retry the query by restarting the whole pipeline and all remote queries while explicitly excluding the node that did throw the exception?

**Comment by filimonov** [comment]
(kinda) related https://github.com/ClickHouse/ClickHouse/pull/9900

**Comment by alexey-milovidov** [comment]
The error "Too many simultaneous queries" are happening for one of the following reasons:

1. Hardware errors: replica remain accessible but suddenly was slowdown.
2. Software errors: lack of rate limiting, too heavy queries, a scipt with a loop...

Reason 2 is more common.

The proposed solution will help for case 1 but will lead to cascading failures in case 2.
(Cascading failures will make all your cluster unavailable due to failover).

**Comment by alexey-milovidov** [comment]
Won't fix to prevent cascading failures.
Nevertheless it can be retried by client.
