### ISSUE TITLE
What method should clickhouse use to synchronize single-machine data to the cluster

### ISSUE THREAD

**Issue by gubinjie** [ClickHouse/ClickHouse#15457]
We currently have historical business data in the business table of a single clickhouse. According to business needs, we rebuilt the clickhouse cluster. How can I synchronize the data of a table in a single server to the cluster?

**Comment by nikitamikhaylov** [comment]
Hello, if I understood you correctly, you need to copy your historical data from single server to a cluster of several shards? It could be done with [copier](https://altinity.com/blog/2018/8/22/clickhouse-copier-in-practice). You have to define your cluster and choose the sharding key.
