### ISSUE TITLE
MaterializedView over MaterializedView

### ISSUE THREAD

**Issue by wutchzone** [ClickHouse/ClickHouse#15463]
Hello.

In my current situtation I have Materialized Views above normal tables with MergeTree engine. I have a situation where in normal table are raw data and i need to create percentile from them every minute and hour. Creating pecentil every minute from raw data is fine, but when I create percentil every hour it returns errors while creating percentil (`DB::Exception: Too large t-digest summary size`). So I want to try to create hourly percentil from minute data from that MaterializedView.

Is it possible to create MaterializedView over MaterializedView instread of a normal table?

Thank you for help

**Comment by den-crane** [comment]
Yes. It's possible but it depends on CH version.

In the latest version you need to use  `from .inner` if the first MV created with implicit storage and `from _{to}_table` if the first MV created with explicite storage.

https://github.com/ClickHouse/ClickHouse/issues/7195#issuecomment-538397320

**Comment by wutchzone** [comment]
Thank you for your answer. If you do not mind I have one more question.

This is my table which calculates percentile from the raw data
```
CREATE MATERIALIZED VIEW rtt_99p_graph_second
ENGINE = ReplicatedAggregatingMergeTree(...)
PARTITION BY metric_date ORDER BY (metric_date, metric_time, machine_name)
TTL metric_time + INTERVAL 1 HOUR
AS SELECT
                                                    metric_date,
                                                    machine_name,
  toStartOfInterval(metric_time, INTERVAL 5 second) metric_time,
  quantileTDigestState(0.99)(RTT)                   percentile
FROM metrics
GROUP BY metric_date, machine_name, metric_time;
```

When I am creating second MW over this MW I create it like this:
```
CREATE MATERIALIZED VIEW rtt_99p_graph_hour
ENGINE = ReplicatedAggregatingMergeTree(...)
PARTITION BY metric_date ORDER BY (metric_date, metric_time, machine_name)
AS SELECT
                                                    metric_date,
                                                    machine_name,
  toStartOfInterval(metric_time, INTERVAL 1 hour)   metric_time,
  quantileTDigestState(0.99)(percentile)            percentile
FROM `.inner.rtt_99p_graph_second`
GROUP BY metric_date, machine_name, metric_time;
```

But it is not possible due to error `DB::Exception: Illegal type AggregateFunction(quantileTDigest(0.99), UInt32) of argument for aggregate function quantileTDigest`. Is there I way how to fix the `quantileTDigestState` in hourly statistics to count percentile from the first MW?

**Comment by den-crane** [comment]
Have you tried -MergeState modifier?

https://clickhouse.tech/docs/en/sql-reference/aggregate-functions/combinators/#aggregate_functions_combinators-mergestate

**quantileTDigestMergeState** (0.99)(percentile)

**Comment by wutchzone** [comment]
Thank you, now it is working. I totally missed the `-MergeState modifier`.

**Comment by petr-larin** [comment]
The `.inner` trick won't work anymore for the first MV w/ implicit storage, the implicit table is called like `.inner_id.1d3ef9e7-a1a4-4102-ab19-b7be7caba1cb` and this works, is this the right way forward,
 or is there an alias for the implicit table? Or is this to force me to use explicit tables?
Happy 2024!

![Screenshot 2023-12-31 002706](https://github.com/ClickHouse/ClickHouse/assets/113700952/6a3f4b6c-3dc3-4640-a49f-b64bbfc64045)
