### ISSUE TITLE
DateTime64 wrong seconds value prior to 1920

### ISSUE THREAD

**Issue by zvonand** [ClickHouse/ClickHouse#15486]
To PR #9404
@Enmk 

**toDateTime64() returns incorrect result when passing it date prior to `1920` and `timezone != 'UTC'`
Exact seconds mismatch depends on timezone.

For example: 
`SELECT toDateTime64('1919-07-01 00:00:00', 0, 'Europe/Moscow')` returns `1919-07-01 00:00:41`

**Comment by den-crane** [comment]
It's a hell of the work to support all cases including all 30 February cases and 5 days weeks.

As I see even PG does not support Russia calendar shift.
```
set time zone 'Europe/Moscow';

select timestamp with time zone '1918-02-14 00:00:00.000000+00' - '3 days'::interval;
           ?column?
------------------------------
 1918-02-11 02:31:19+02:31:19
```

**Comment by alexey-milovidov** [comment]
We decided to limit the range with minimum year 1925 for now.
