### ISSUE TITLE
Question: "store" directory in Clickhouse data directory

### ISSUE THREAD

**Issue by Teeeto** [ClickHouse/ClickHouse#15504]
There is a directory called "store" in Clickhouse data folder which is only 32 MB in size but contains 286k+ subfolders and 141k files.
Th database is idle for a day, so there should not be background tasks.
Documentation does not specify the function and importance of this directory, shall it be maintained manually in some way, does it have effect on performance?

**Comment by den-crane** [comment]
It seems you have or had a database named "store".


Can you show a result of SQL **show databases**

**Comment by tavplubix** [comment]
It's not documented for now, but 'store/' directory contains data and metadata of all tables in all databases with `ENGINE=Atomic`. Database `system` is created with Atomic engine by default since 20.8. However, `system` database should not produce so many subfolders and files in `store/`.

Which ClickHouse version do you use?
Is there any files in `metadata_dropped/` directory?
Is there any suspicious messages from `DatabaseCatalog` in server logs? (`grep -Fa "DatabaseCatalog" /var/log/clickhouse-server/clickhouse-server.log` or `clickhouse-server.err.log`)

**Comment by 6ec123321** [comment]
Make a request, all people test your code - afread is ?

**Comment by 6ec123321** [comment]
Take freedom for you hear and life

**Comment by 6ec123321** [comment]
You can going in time ?? not? Yandex need this in feature - if you need this in time - go ahead. Close this isues now.

**Comment by Teeeto** [comment]
> It's not documented for now, but `store/` directory contains data and metadata of all tables in all databases with `ENGINE=Atomic`. Database `system` is created with Atomic engine by default since 20.8. However, `system` database should not produce so many subfolders and files in `store/`.
> 
> Which ClickHouse version do you use?
> Is there any files in `metadata_dropped/` directory?
> Is there any suspicious messages from `DatabaseCatalog` in server logs? (`grep -Fa "DatabaseCatalog" /var/log/clickhouse-server/clickhouse-server.log` or `clickhouse-server.err.log`)

I think its worth mentioning that a lot of design experimentation was going on with the database - creating and dropping tables, columns, changing codecs, re-importing hundreds of gigs of data.

Clickhouse version is 20.9 from deb packages.
metadata_dropped is empty
grep results:
`2. DB::DatabaseCatalog::getTableImpl(DB::StorageID const&, DB::Context const&, std::__1::optional<DB::Exception>*) const @ 0x1722f179 in /usr/bin/clickhouse
3. DB::DatabaseCatalog::getTable(DB::StorageID const&, DB::Context const&) const @ 0x1722f3a4 in /usr/bin/clickhouse
2. DB::DatabaseCatalog::getTableImpl(DB::StorageID const&, DB::Context const&, std::__1::optional<DB::Exception>*) const @ 0x1722f179 in /usr/bin/clickhouse
3. DB::DatabaseCatalog::getTable(DB::StorageID const&, DB::Context const&) const @ 0x1722f3a4 in /usr/bin/clickhouse
2. DB::DatabaseCatalog::getTableImpl(DB::StorageID const&, DB::Context const&, std::__1::optional<DB::Exception>*) const @ 0x1722f179 in /usr/bin/clickhouse
3. DB::DatabaseCatalog::getTable(DB::StorageID const&, DB::Context const&) const @ 0x1722f3a4 in /usr/bin/clickhouse
3. DB::DatabaseCatalog::assertDatabaseExists(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const @ 0x1722f8d6 in /usr/bin/clickhouse
3. DB::DatabaseCatalog::assertDatabaseExists(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const @ 0x1722f8d6 in /usr/bin/clickhouse
3. DB::DatabaseCatalog::getDatabase(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const @ 0x1722f91e in /usr/bin/clickhouse
2. DB::DatabaseCatalog::getTableImpl(DB::StorageID const&, DB::Context const&, std::__1::optional<DB::Exception>*) const @ 0x1722f179 in /usr/bin/clickhouse
3. DB::DatabaseCatalog::getDatabaseAndTable(DB::StorageID const&, DB::Context const&) const @ 0x1722f4e1 in /usr/bin/clickhouse
2. DB::DatabaseCatalog::getTableImpl(DB::StorageID const&, DB::Context const&, std::__1::optional<DB::Exception>*) const @ 0x1722f179 in /usr/bin/clickhouse
3. DB::DatabaseCatalog::getDatabaseAndTable(DB::StorageID const&, DB::Context const&) const @ 0x1722f4e1 in /usr/bin/clickhouse
2. DB::DatabaseCatalog::getTableImpl(DB::StorageID const&, DB::Context const&, std::__1::optional<DB::Exception>*) const @ 0x1722f179 in /usr/bin/clickhouse
3. DB::DatabaseCatalog::getDatabaseAndTable(DB::StorageID const&, DB::Context const&) const @ 0x1722f4e1 in /usr/bin/clickhouse
2. DB::DatabaseCatalog::getTableImpl(DB::StorageID const&, DB::Context const&, std::__1::optional<DB::Exception>*) const @ 0x1722f179 in /usr/bin/clickhouse
3. DB::DatabaseCatalog::getDatabaseAndTable(DB::StorageID const&, DB::Context const&) const @ 0x1722f4e1 in /usr/bin/clickhouse
2. DB::DatabaseCatalog::getTableImpl(DB::StorageID const&, DB::Context const&, std::__1::optional<DB::Exception>*) const @ 0x1722f179 in /usr/bin/clickhouse
3. DB::DatabaseCatalog::getDatabaseAndTable(DB::StorageID const&, DB::Context const&) const @ 0x1722f4e1 in /usr/bin/clickhouse
2. DB::DatabaseCatalog::getTableImpl(DB::StorageID const&, DB::Context const&, std::__1::optional<DB::Exception>*) const @ 0x1722f179 in /usr/bin/clickhouse
3. DB::DatabaseCatalog::getDatabaseAndTable(DB::StorageID const&, DB::Context const&) const @ 0x1722f4e1 in /usr/bin/clickhouse
2. DB::DatabaseCatalog::getTableImpl(DB::StorageID const&, DB::Context const&, std::__1::optional<DB::Exception>*) const @ 0x1722f179 in /usr/bin/clickhouse
3. DB::DatabaseCatalog::getDatabaseAndTable(DB::StorageID const&, DB::Context const&) const @ 0x1722f4e1 in /usr/bin/clickhouse
2. DB::DatabaseCatalog::getTableImpl(DB::StorageID const&, DB::Context const&, std::__1::optional<DB::Exception>*) const @ 0x1722f179 in /usr/bin/clickhouse
3. DB::DatabaseCatalog::getDatabaseAndTable(DB::StorageID const&, DB::Context const&) const @ 0x1722f4e1 in /usr/bin/clickhouse
2. DB::DatabaseCatalog::getTableImpl(DB::StorageID const&, DB::Context const&, std::__1::optional<DB::Exception>*) const @ 0x1722f179 in /usr/bin/clickhouse
3. DB::DatabaseCatalog::getDatabaseAndTable(DB::StorageID const&, DB::Context const&) const @ 0x1722f4e1 in /usr/bin/clickhouse
2. DB::DatabaseCatalog::getTableImpl(DB::StorageID const&, DB::Context const&, std::__1::optional<DB::Exception>*) const @ 0x1722f179 in /usr/bin/clickhouse
3. DB::DatabaseCatalog::getDatabaseAndTable(DB::StorageID const&, DB::Context const&) const @ 0x1722f4e1 in /usr/bin/clickhouse
2. DB::DatabaseCatalog::getTableImpl(DB::StorageID const&, DB::Context const&, std::__1::optional<DB::Exception>*) const @ 0x1722f179 in /usr/bin/clickhouse
3. DB::DatabaseCatalog::getTable(DB::StorageID const&, DB::Context const&) const @ 0x1722f3a4 in /usr/bin/clickhouse
2. DB::DatabaseCatalog::getTableImpl(DB::StorageID const&, DB::Context const&, std::__1::optional<DB::Exception>*) const @ 0x1722f179 in /usr/bin/clickhouse
3. DB::DatabaseCatalog::getTable(DB::StorageID const&, DB::Context const&) const @ 0x1722f3a4 in /usr/bin/clickhouse
2. DB::DatabaseCatalog::getTableImpl(DB::StorageID const&, DB::Context const&, std::__1::optional<DB::Exception>*) const @ 0x158a7729 in /usr/bin/clickhouse
3. DB::DatabaseCatalog::getTable(DB::StorageID const&, DB::Context const&) const @ 0x158a7954 in /usr/bin/clickhouse
3. DB::DatabaseCatalog::assertDatabaseExists(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const @ 0x158a7e86 in /usr/bin/clickhouse
3. DB::DatabaseCatalog::assertDatabaseExists(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const @ 0x158a7e86 in /usr/bin/clickhouse
2. DB::DatabaseCatalog::getTableImpl(DB::StorageID const&, DB::Context const&, std::__1::optional<DB::Exception>*) const @ 0x158a7729 in /usr/bin/clickhouse
3. DB::DatabaseCatalog::getTable(DB::StorageID const&, DB::Context const&) const @ 0x158a7954 in /usr/bin/clickhouse
3. DB::DatabaseCatalog::getDatabase(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const @ 0x158a7ece in /usr/bin/clickhouse
3. DB::DatabaseCatalog::getDatabase(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const @ 0x158a7ece in /usr/bin/clickhouse
`

**Comment by Teeeto** [comment]
> It's not documented for now, but `store/` directory contains data and metadata of all tables in all databases with `ENGINE=Atomic`.
Obviously data is not there, since there s is another directory called "data" which contains the DB data (60 GB compressed)
Also to quantify "a lot" from my previous comment - there was in the range of  hundreds DDL stattements.

**Comment by xuswjtu** [comment]
/var/lib/clickhouse/store
# ll
drwxr-xr-x. 3 clickhouse clickhouse 50 Dec 16 04:32 000
drwxr-xr-x. 2 clickhouse clickhouse  6 Dec 16 04:40 27b
drwxr-xr-x. 3 clickhouse clickhouse 50 Dec 16 04:17 501
drwxr-xr-x. 3 clickhouse clickhouse 50 Dec 16 04:18 554
drwxr-xr-x. 3 clickhouse clickhouse 50 Dec 16 04:17 6d3
drwxr-xr-x. 3 clickhouse clickhouse 50 Dec 16 04:17 7f6
drwxr-xr-x. 3 clickhouse clickhouse 50 Dec 16 04:17 cf4
drwxr-xr-x. 3 clickhouse clickhouse 50 Dec 16 04:17 f80
drwxr-xr-x. 3 clickhouse clickhouse 50 Dec 16 04:17 f97

# ll f97/f974292d-5c75-4a7c-805a-01a046948b4f/202012_27365_27365_0/
total 60
-rw-r--r--. 1 clickhouse clickhouse   260 Dec 18 13:20 checksums.txt
-rw-r--r--. 1 clickhouse clickhouse 11236 Dec 18 13:20 columns.txt
-rw-r--r--. 1 clickhouse clickhouse     1 Dec 18 13:20 count.txt
-rw-r--r--. 1 clickhouse clickhouse  9736 Dec 18 13:20 data.bi
....


This is only available in the new version?     
Was it in the data directory before?

**Comment by alexey-milovidov** [comment]
@xuswjtu Look at the `data` directory. You will find symlinks to the `store` directory.
In previous versions data was stored in the `data` directory directly, not data is liked to the `store` directory.

**Comment by flyly0755** [comment]
> 0 data.bi
I want to know from which version begin to use store dir, that store data and the subdir under data dir which are ink to the store dir?
coz recently i update clickhouse from 20.8.11.17 to 21.12.3.32 and newly install 21.12.3.32 in another machine.
with the updated manchine, i saw the data is still store in data dir, but newly install which is store data in store dir.
This two different results is alright?
