### ISSUE TITLE
insert with format tsv or csv don't  inserts enums as expected

### ISSUE THREAD

**Issue by Grian** [ClickHouse/ClickHouse#15510]
** INSERT INTO table FORMAT TSV fail with message 'Unknown element **

**How to reproduce**
1) Create table
```
CREATE TABLE enum_test
(
    `a` Int32,
    `b` Enum8('a' = 1, 'b' = 2, 'c' = 3)
)
ENGINE = MergeTree()
ORDER BY a
```
2) Create files abc.tsv, abc.csv, abc.values for each format
```
$ cat abc.tsv
1       1
10      2
100     3
$ cat abc.csv
1,      1
10,     2
100,    3
$ cat abc.values
(1,   1)
(10,  2)
(100, 3)
```
3) Execute:
```
$ cat abc.tsv | lhouse --query 'insert into enum_test(a,b) FORMAT TSV'
Code: 36. DB::Exception: Unknown element '1' for type Enum8('a' = 1, 'b' = 2, 'c' = 3)

$ cat abc.csv | lhouse --query 'insert into enum_test(a,b) FORMAT CSV'
Code: 36. DB::Exception: Unknown element '1' for type Enum8('a' = 1, 'b' = 2, 'c' = 3)

$ cat abc.values | lhouse --query 'insert into enum_test(a,b) FORMAT Values'
$ # It's works, all data have been inserted

```

ClickHouse client version 20.5.2.7 (official build).

Interface: clickhouse-client or http

**Expected behavior**

I expect all data to be inserted:
```
$ house --query 'select * from enum_test' 
...
1       a
10      b
100     c
...
$ 
```

**Error message and/or stacktrace**
Code: 36. DB::Exception: Unknown element '1' for type Enum8('a' = 1, 'b' = 2, 'c' = 3)

**Comment by den-crane** [comment]
No way to distinguish in TSV and CSV and JSONEachRow   what is "1" enum_value or enum_id

https://github.com/ClickHouse/ClickHouse/issues/7971#issuecomment-624222686
https://github.com/ClickHouse/ClickHouse/issues/10682

**Comment by Grian** [comment]
Why? You can create hash table of enum values + enum numbers:
```
{
'1': 1,
'a': 1,
'2': 2,
'b': 2,
 ...
} 
```
And parse as string values?

**Comment by den-crane** [comment]
OK, I have in my database  Enum8('1' = 2, '33' = 2, '4' = 3, '11' = 4) -- I am not joking.

cat abc.tsv
1       4

What is "4" in this case?

**Comment by Grian** [comment]
Obviously, you should prefer string values before numbers, because
You may want do 
```
$ house --query "select * from foo FORMAT TSV  | house "insert into bar FORMAT TSV".
```
So 4 ='3'.

And hashtable for parsing should be like
```
{
  '1': 2,
  '33': 2,
  '4': 3,
  '11': 4,
  '2': 2,
  '3': 3, // But there is not '4': 4
}
```  
But in my database there are not such enums like you have.

What is use case for such enums? (Enum8('1' = 2, '33' = 2, '4' = 3, '11' = 4))

You should know what are you doing.

P.S. 
I have enums like 
`10_3` Enum('аннулирован'=0, '[old]'=1, 'ожидание предоплаты'=2, 'в обработке, см. местонахождение заказа'=3, 'ожидание ответа'=4, 'отправлен по почте, но ещё не оплачен'=5, 'доставлен (или отправлен по почте) и оплачен'=6)

**Comment by den-crane** [comment]
My opinion is irrelevant.

Check this comment https://github.com/ClickHouse/ClickHouse/issues/7971#issuecomment-624222686
