### ISSUE TITLE
Missing column names on CSVWithNames with http

### ISSUE THREAD

**Issue by artbeglaryan** [ClickHouse/ClickHouse#15520]
On [12197](https://github.com/ClickHouse/ClickHouse/pull/12197) and [13343](https://github.com/ClickHouse/ClickHouse/pull/13343)  pull requests issue marked as fixed and v20.3-backported label is there, but looks like it's not backported to 20.3.

For reproduce CSVWithNames
```
artur@sv-marmoset206:~$ curl  http://localhost:8123/?query="SELECT+version()+as+T+FORMAT+CSVWithNames"
"20.3.19.4"
```

TSWithNames works
```
artur@sv-marmoset206:~$ curl  http://localhost:8123/?query="SELECT+version()+as+T+FORMAT+TSVWithNames"
T
20.3.19.4
artur@sv-marmoset206:~$ 
```

More versions checked in [comment](https://github.com/ClickHouse/ClickHouse/pull/13343#issuecomment-688299610)

**Comment by filimonov** [comment]
One of backports missing

**Comment by nikitamikhaylov** [comment]
Backported to 20.4 here https://github.com/ClickHouse/ClickHouse/pull/9624/commits/b0e4db3b36c2bdce8b91e4a3916031e9dab57369
