### ISSUE TITLE
Should Nested Fields be Arrays when they are single and should be part of the signle row

### ISSUE THREAD

**Issue by meshpaul** [ClickHouse/ClickHouse#15523]
(you don't have to strictly follow this form)

**Use case**
Currently when Creating a Nested Fileds these created as Arrays.  Ex I can represent something in JSON structure having single inner non repeating fileds.

***Current Behavior***

For a given table 
```sql
CREATE TABLE t
(
    `my_time` DateTime,
    `x` Nested(    a Int8)
)
ENGINE = MergeTree()
ORDER BY my_time
```
When doing a desc
```
DESCRIBE TABLE t

┌─name────┬─type────────┬─default_type─┬─default_expression─┬─comment─┬─codec_expression─┬─ttl_expression─┐
│ my_time │ DateTime    │              │                    │         │                  │                │
│ x.a     │ Array(Int8) │              │                    │         │                  │                │
└─────────┴─────────────┴──────────────┴────────────────────┴─────────┴──────────────────┴────────────────┘
```

**Describe the solution you'd like**

Column `x.a` is represented as array having multiple Int8 when this should be represented just as single Int8.  I get it that its column oriented DB but this is confusing and should be treated as single value internally.   Example of having columns as follows
`
my_tyime is DateTime
x.a is Int8
`
where `x.a` internally can be represented say as `x_a` having `Int8` data not arrays.

`Nested` is somewhat blurred with `Repeated` which it should not be.   In other words think of this as complex JSON 

```json
{ 
   "a" : "some value",
   "b" : { 
           "nestedSingle" : "single",
           "repeadedNested" : [ "a", "b", "c"]
          }
}
```
So when doing a describe this should be as follows

| Name | Type |
|-------|------|
| a | String |
| b.nestedSingle | String |
| b.repeatedNested | Array(String) |

This is exactly what is happening in similar system like Googles BigQuery.

**Describe alternatives you've considered**

**Additional context**
TODO Add select from Google BigQ for similar

**Comment by amosbird** [comment]
The type you need is named tuple, which exists only in the codebase for now. Perhaps we can extend the parser to handle named tuple now based on tons of improvements in the past year.

**Comment by alexey-milovidov** [comment]
See #17175.
