### ISSUE TITLE
Provide ways to cooperate with security scanners.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#15552]
If you go to Shodan and type ClickHouse, you will find several thousand instances of ClickHouse opened to internet.
Some of them allow authentication with default user and empty password and some of them allow full read/write access.

Note that ClickHouse is protected by default: users required special actions after installation to make it open to public internet and also we ask to set a password. It means - we already do everything that we have to do from security standpoint and not much can be improved.

There was an incident 1.5 years ago when someone logged into all that instances, removed all tables and created a table with blackmail message. Btw, there are much more incidents of this kind for MongoDB and Redis.

To prevent these incidents, we should run our own white-hat security scan and warn users.

**Implementation**

1. Add `SYSTEM LOG` command. Example: `SYSTEM LOG ERROR 'This ClickHouse instance has full write access from internet'`. This command will simply emit a message in server log with specified level. Security scanners will go to every acessible instance of ClickHouse and execute this command.

2. Add `system.security_warnings` table. `clickhouse-client` will query all distinct records from this table after connection and display all of them to the client. Security scanners can go and INSERT a message into this table if they can. `clickhouse-server` can also cache the contents of this table in memory and return it on every HTTP request.

3. Provide `SYSTEM` query that will simply revoke all access from the public internet. Security scanners will go and close the instances whenever they can.

**Comment by alexey-milovidov** [comment]
Variants 1, 2 opens more possibilities for ransom attacks.
Variant 3 looks Ok.

It can be implemented with a command like
`SYSTEM LOCAL ACCESS ONLY`
that will create a flag in `flags` directory that the server will check.

**Comment by UnamedRus** [comment]
But, if yandex team runs that kind of command on server and it disrupts someone's server, is there a possibility to issue a lawsuit about hacking and taking down someone's service against yandex?

**Comment by alexey-milovidov** [comment]
@UnamedRus There is no point to run this scanner by ourself but someone else may do.

**Comment by filimonov** [comment]
`SYSTEM STOP GLOBAL ACCESS`

I bet in that scenario valid users may also access ClickHouse via the internet using default passwordless user  :hankey: 

So after 'white-hat hacker' will run that command, the valid user most probably will lose the connection to clickhouse...
And the 'fast fix' the user will apply will be 'give my permissions back'.

**Comment by alexey-milovidov** [comment]
> flooded by issues like 'my clickhouse stop being available sometimes randomly'

We already have seen another kind of issues, like: "All tables on my ClickHouse instance have disappear and there is a table with a request to send one BTC".

**Comment by UnamedRus** [comment]
From chproxy [github](https://github.com/Vertamedia/chproxy)
```
Be careful when configuring limits, allowed networks, passwords etc. By default chproxy tries detecting the most obvious configuration errors such as allowed_networks: ["0.0.0.0/0"] or sending passwords via unencrypted HTTP.

Special option hack_me_please: true may be used for disabling all the security-related checks during config validation (if you are feeling lucky :) ).
```
Probably we can have similar behavior in clickhouse itself: special settings in config or flag file.

**Comment by alexey-milovidov** [comment]
It's typical to make ClickHouse listen `::` or `0.0.0.0` inside company network that's not accessible outside.

**Comment by filimonov** [comment]
> > flooded by issues like 'my clickhouse stop being available sometimes randomly'
> 
> We already have seen another kind of issues, like: "All tables on my ClickHouse instance have disappear and there is a table with a request to send one BTC".

Will will have both :) Black hat guys will remove data and blackmail the victim, white hat guys will close the access and user will reopen them again till black hat guy will come... :)

**Comment by UnamedRus** [comment]
>It's typical to make ClickHouse listen :: or 0.0.0.0 inside company network that's not accessible outside.

At clickhouse start, clickhouse tries to reach itself by interfaces via some preset proxy from the internet, it wouldn't work if clickhouse set behind open to everyone load balancer. And that ofc can be disabled, if user doesn't like it if clickhouse tries to send something on the internet.

**Comment by alexey-milovidov** [comment]
> At clickhouse start, clickhouse tries to reach itself by interfaces via some preset proxy from the internet

Already been considered, but it looks like a worse solution to enable by default: it's suspicious for database server to ping some host on the internet.

**Comment by alexey-milovidov** [comment]
> Will will have both :)

Yes, I'm also thinking this way. But there is one argument remaining...
These kind of ransom attacks are rare but they are destructive.

Security scans can operate on better scale. It's easy to scan all IPv4 addresses for specific port in minutes.

Maybe it's better to emit a predefined warning in clickhouse-client without service interruption? (similar to variant 2)

**Comment by alexey-milovidov** [comment]
This is a good alternative: https://monitor.shodan.io/

**Comment by alexey-milovidov** [comment]
This task is not relevant.

**Comment by alexey-milovidov** [comment]
Good service:

```
$ curl https://internetdb.shodan.io/52.59.38.70
{"cpes":["cpe:/a:openbsd:openssh:8.2p1 Ubuntu-4ubuntu0.3"],"hostnames":["ec2-52-59-38-70.eu-central-1.compute.amazonaws.com","play.clickhouse.com"],"ip":"52.59.38.70","ports":[22,443],"tags":["cloud"],"vulns":[]}
```
