### ISSUE TITLE
debug kafka

### ISSUE THREAD

**Issue by igor9292** [ClickHouse/ClickHouse#15572]
Добрый день! Не могли бы подсказать, как дебажить, есть табличка kafka engine, перестали в неё поступать данные, ошибки в логах: <Trace> StorageKafka (log_waffa5_in_parsed): Re-joining claimed consumer after failure, debug all не отображает доп. Информации. Я предполагаю, что изменился формат сообщения или что то не так с форматом jsonEachRow, которые приходят, поля совпадают, типы тоже. С виду с json все в порядке, но возможно я не отловил «плохие» сообщения. Собственно как это проверить, есть какой либо приклад на проверку соответствия сообщения формату/полям и т.п.? Или может быть кликхаус где то это логирует? Версия 20.8.53

**Comment by filimonov** [comment]
Да, похоже на проблемы с парсингом. 

Ищите записи в логах с severity Error примерно в то же время что и "Re-joining claimed consumer after failure" (возможно чуть позднее, емнип в них не будет упоминаться Kafka).

**Comment by igor9292** [comment]
> Да, похоже на проблемы с парсингом.
> 
> Ищите записи в логах с severity Error примерно в то же время что и "Re-joining claimed consumer after failure" (возможно чуть позднее, емнип в них не будет упоминаться Kafka).

Нет ничего похожего, дебаг надо включить? 

вот при включенном дебаге, что есть в логах

Oct  3 22:53:42 clickhouse-server: %7|1601754822.068|BROKERFAIL|ClickHouse 20.3.8.53#consumer-21| [thrd:progress309:9093/bootstrap]: progress309:9093/bootstrap: failed: err: Local: Broker transport failure: (errno: Connection reset by peer)
 clickhouse-server: %7|1601754822.068|FAIL|ClickHouse 20.3.8.53#consumer-21| [thrd:progress309:9093/bootstrap]: progress309:9093/bootstrap: ApiVersionRequest failed: Local: Broker transport failure: probably due to old broker version (after 0ms in state DOWN)

**Comment by filimonov** [comment]
Простите тикет кажется потерялся. 

>  Connection reset by peer 

Это ошибка соединения. Проверьте адрес / порт / файерволл / ssl и прочие настройки соединения.
