### ISSUE TITLE
HTTP Interface

### ISSUE THREAD

**Issue by mjodeh** [ClickHouse/ClickHouse#15571]
As the documentation says the query should be sent in the URL as a `queryParameter`, and the URL max length is `16K`, what if the query we need to execute exceeds this limit and we can not use native client? we are forced to use HTTP interface since we are using `NodeJS` and there is no native client supported?
Wouldn't it be a lot nicer if the HTTP Request is `POST` and the query is sent in the __body__, in this case theoretically we won't have any limitation?
We are already hitting this limit
Any help will be appreciated.

**Comment by alexey-milovidov** [comment]
> Wouldn't it be a lot nicer if the HTTP Request is POST and the query is sent in the body, in this case theoretically we won't have any limitation?

This is exactly what is supported.

From the docs:
> Send the request as a URL ‘query’ parameter, or as a POST. Or send the beginning of the query in the ‘query’ parameter, and the rest in the POST
