### ISSUE TITLE
Strange connection behavior between replicas of different regions.

### ISSUE THREAD

**Issue by OmarBazaraa** [ClickHouse/ClickHouse#15596]
We are facing unexpected behavior in ClickHouse.

We have a ClickHouse cluster of 30 nodes (10 shards, 3 replicas each). The nodes are deployed in two different regions (20 replicas in region 1 and 10 replicas in region 2). And here is our cluster definition:

```
<yandex>
    <remote_servers>
        <clickhouse_cluster>
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                    <host>ch-01-01-1.my-domain.com</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>ch-01-01-2.my-domain.com</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>ch-01-01-3.my-domain.com</host>
                    <port>9000</port>
                </replica>
            </shard>

            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                    <host>ch-01-02-1.my-domain.com</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>ch-01-02-2.my-domain.com</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>ch-01-02-3.my-domain.com</host>
                    <port>9000</port>
                </replica>
            </shard>

            ...
        </clickhouse_cluster>
    </remote_servers>
</yandex>
```

First, we connected to one of the nodes and created our tables using DDL queries. The tables got created successfully in all the nodes across the two regions. Then when we inserted some rows into a replicated table of one of the nodes of region 1, we found that the rows got replicated in the other replica of region 1, but it didn't get replicated in the other region.

When we tried to further investigate the issue, by trying to connect to nodes of region 2 from within some of the nodes of region 1, we faced some more unexpected behaviors.

We couldn't connect to the other region when we use `remote` function from inside of `clickhouse-client` as follows:

```
:) select hostname() from remote('ch-01-01-3.my-domain.com', system.numbers) limit 1

SELECT hostname()
FROM remote('ch-01-01-3.my-domain.com', system.numbers)
LIMIT 1


Received exception from server (version 20.8.2):
Code: 519. DB::Exception: Received from localhost:9000. DB::Exception: All attempts to get table structure failed. Log:

Code: 279, e.displayText() = DB::NetException: All connection tries failed. Log:

Code: 209, e.displayText() = DB::NetException: Timeout: connect timed out: 10.11.0.13:9000 (ch-01-01-3.my-domain.com:9000) (version 20.8.2.3 (official build))
Code: 209, e.displayText() = DB::NetException: Timeout: connect timed out: 10.11.0.13:9000 (ch-01-01-3.my-domain.com:9000) (version 20.8.2.3 (official build))
Code: 209, e.displayText() = DB::NetException: Timeout: connect timed out: 10.11.0.13:9000 (ch-01-01-3.my-domain.com:9000) (version 20.8.2.3 (official build))

 (version 20.8.2.3 (official build))

.

0 rows in set. Elapsed: 0.155 sec.
```

But when we ran a very similar query as follows, it completed successfully:

```
$ clickhouse-client --query "select hostname() from system.numbers limit 1" --host "ch-01-01-3.my-domain.com"

ch-01-01-3
```

The problem only occurs across regions.
Maybe this happens because of the fact that we can resolve the hostnames of the nodes in the same regions using `ch-XX-XX-X` directly without the need to append the domain name (i.e. `ch-XX-XX-X.my-domain.com`) but we have to append the domain name to resolve nodes of different regions.
But the question is: why the data didn't get replicated successfully and why the `remote` function didn't work as intended when the DDL queries and `clickhouse-client --query "..." --host "..."` are working normally?

**Comment by den-crane** [comment]
>All connection tries failed. Log:

By default connection timeout is 50ms!!!!.

cat /etc/clickhouse-server/conf.d/connection_settings.xml
<?xml version="1.0"?>
<yandex>
    <profiles>
        <default>
            <connect_timeout_with_failover_ms>1000</connect_timeout_with_failover_ms>
        </default> 
    </profiles>
</yandex>

**Comment by OmarBazaraa** [comment]
This solves connecting to another node using the `remote` function.
But the replication problem still exists, when I insert in a region, the data is not replicated in the other region.

**Comment by OmarBazaraa** [comment]
And btw, when I added this setting and restarted the servers, the servers that the `INSERT`s end up into were not able to start because of the following error:

```
<Error> Application: DB::Exception: Part `202009_0_0_0` was found on disk `default` which is not defined in the storage policy: Cannot attach table `mydb`.`mytable_local` from metadata file /mnt/ssd1/clickhouse/metadata/mydb/mytable_local.sql from query

ATTACH TABLE mydb.mytable_local (
    `Timestamp` DateTime,
    …
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/mydb/mytable_local/{layer}-{shard}', '{replica}')
PARTITION BY toYYYYMM(Timestamp)
ORDER BY (...)
SAMPLE BY intHash32(UserId)
TTL Timestamp + toIntervalMonth(3)
SETTINGS storage_policy = 'move_from_ssd_to_hdd', index_granularity = 8192

while loading database `mydb` from path /mnt/ssd1/clickhouse/metadata/mydb

Part was found on disk `default` which is not defined in the storage policy: Cannot attach table from metadata file
```

**Comment by den-crane** [comment]
> This solves connecting to another node using the `remote` function.
> But the replication problem still exists, when I insert in a region, the data is not replicated in the other region.

**select * from system.replication_queue** on all replicas

**Comment by OmarBazaraa** [comment]
> **select * from system.replication_queue** on all replicas

I found this:

```
SELECT *
FROM remote('ch-01-08-3.my-domain.com', system.replication_queue)
FORMAT Vertical

Row 1:
──────
database:               my_db
table:                  my_table_local
replica_name:           3
position:               0
node_name:              queue-0000000000
type:                   GET_PART
create_time:            2020-10-05 12:46:48
required_quorum:        0
source_replica:         2
new_part_name:          202009_0_0_0
parts_to_merge:         []
is_detach:              0
is_currently_executing: 0
num_tries:              13
last_exception:         Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = Host not found: ch-01-08-2.qlycpey12qyudls00h5anwsfzh.cx.internal.cloudapp.net (version 20.8.2.3 (official build))
last_attempt_time:      2020-10-05 12:56:50
num_postponed:          0
postpone_reason:
last_postpone_time:     1970-01-01 00:00:00

1 rows in set. Elapsed: 0.010 sec.
```

**Comment by den-crane** [comment]
>Host not found: ch-01-08-2.qlycpey12qyudls00h5anwsfzh.cx.internal.cloudapp.net

DNS problem? 

On start replica announce itself in ZK. One of replica announce as `hostname -f` as ch-01-08-2.qlycpey12qyudls00h5anwsfzh.

`hostname -f`  -- can be overridden in config.xml using `interserver_http`

**Comment by den-crane** [comment]
`<remote_servers>` -- cluster description is not used for Replication (Replicated engines).

**Comment by OmarBazaraa** [comment]
> `hostname -f` -- can be overridden in config.xml using `interserver_http`

It worked.
Thank you so much, Denny.
But do you have an explanation for [this](https://github.com/ClickHouse/ClickHouse/issues/15596#issuecomment-703591540)?

**Comment by den-crane** [comment]
> > `hostname -f` -- can be overridden in config.xml using `interserver_http`
> 
> It worked.
> Thank you so much, Denny.
> But do you have an explanation for [this](https://github.com/ClickHouse/ClickHouse/issues/15596#issuecomment-703591540)?


```
Part `202009_0_0_0` was found on disk `default` which is not defined in the storage policy: 
Cannot attach table `mydb`.`mytable_local` from metadata file /mnt/ssd1/clickhouse/metadata/mydb/mytable_local.sql from query
```

Obviously I don't know what happened before this, and what is disk `default` , and did you changed or not `storage_policy = 'move_from_ssd_to_hdd'`

**Comment by OmarBazaraa** [comment]
Here are my configurations:

```
<yandex>
    <path>/mnt/ssd1/clickhouse/</path>
    <tmp_path>/mnt/ssd1/clickhouse/tmp/</tmp_path>
    <user_files_path>/mnt/ssd1/clickhouse/user_files/</user_files_path>
    <access_control_path>/mnt/ssd1/clickhouse/access/</access_control_path>
    <format_schema_path>/mnt/ssd1/clickhouse/format_schemas/</format_schema_path>

    <storage_configuration>
        <disks>
            <disk_ssd_1>
                <path>/mnt/ssd1/clickhouse/</path>
            </disk_ssd_1>

            <disk_hdd_1>
                <path>/mnt/hdd1/clickhouse/</path>
            </disk_hdd_1>
        </disks>

        <policies>
            <move_from_ssd_to_hdd>
                <volumes>
                    <hot>
                        <disk>disk_ssd_1</disk>
                        <max_data_part_size_bytes>1073741824</max_data_part_size_bytes>
                    </hot>

                    <cold>
                        <disk>disk_hdd_1</disk>
                    </cold>
                </volumes>

                <move_factor>0.2</move_factor>
            </move_from_ssd_to_hdd>
        </policies>
    </storage_configuration>
</yandex>
```

and my table looks like this:

```
CREATE TABLE IF NOT EXISTS my_db.my_table_local ON CLUSTER clickhouse_cluster
(
    Timestamp                       DateTime,
    Date                            Date DEFAULT toDate(Timestamp),

    ProjectId                       UInt64,
    UserId                          UInt32,
    SessionId                       UInt32,
    PageNum                         UInt8,

    ...
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/my_db/my_table_local/{layer}-{shard}', '{replica}')
PARTITION BY toYYYYMM(Timestamp)
ORDER BY (ProjectId, Date, intHash32(UserId), SessionId, PageNum)
SAMPLE BY intHash32(UserId)
TTL Timestamp + INTERVAL 3 MONTH DELETE
SETTINGS storage_policy = 'move_from_ssd_to_hdd';
```

After your first suggestion, I only changed `connect_timeout_with_failover_ms` to 1000 ms and restarted the servers. I didn't change anything else.
The servers which was holding some data parts were not able to start due to the error I sent previously.

**Comment by OmarBazaraa** [comment]
> ```
>             <connect_timeout_with_failover_ms>1000</connect_timeout_with_failover_ms>
> ```

Can you please further explain the effects of increasing this setting?
Will the insertion latency increase because of this 2-region setup? or the replication occur asynchronously?

**Comment by den-crane** [comment]
>  <path>/mnt/ssd1/clickhouse/</path>
>...
>  <disk_ssd_1> <path>/mnt/ssd1/clickhouse/</path>  </disk_ssd_1>

AFAIK it's a misconfiguration. This disk should named default in storage_configuration not disk_ssd_1 or you should create another folder `/mnt/ssd1/clickhousexxxx` for ` <path>`

expected:
```
    <storage_configuration>
        <disks>
            <default>
                <path>/mnt/ssd1/clickhouse/</path>
            </default>

```

**Comment by den-crane** [comment]
--connect_timeout_with_failover_ms arg Connection timeout for selecting first healthy replica.

For example you have 3 replicas. R1, R2, R3.
R1 is dead right now. And connect_timeout_with_failover_ms = 1000. On distributed query CH will try to connect to R1. Will wait for 1000ms and then re-try to connect to R2 or R3. 
So you query execution time will be +1000ms.

**Comment by OmarBazaraa** [comment]
> or you can omit this default at all because it's already exists from <path section with name default and can point it as `<disk>default</disk>`

It worked. Thanks a lot, Denny. Although, the displayed error message seems strange. xD

**Comment by OmarBazaraa** [comment]
> --connect_timeout_with_failover_ms arg Connection timeout for selecting first healthy replica.
> 
> For example you have 3 replicas. R1, R2, R3.
> R1 is dead right now. And connect_timeout_with_failover_ms = 1000. On distributed query CH will try to connect to R1. Will wait for 1000ms and then re-try to connect to R2 or R3.
> So you query execution time will be +1000ms.
> 
> by default connect_timeout_with_failover_ms=50ms because this value is suitable for Yandex.Metrica. All their servers close enough in Europe with latency less than 50ms.

Just to confirm. This will not affect the insertion latency if we do insertion directly to the replicas (not though a replicated table), correct?

**Comment by den-crane** [comment]
> > --connect_timeout_with_failover_ms arg Connection timeout for selecting first healthy replica.
> > For example you have 3 replicas. R1, R2, R3.
> > R1 is dead right now. And connect_timeout_with_failover_ms = 1000. On distributed query CH will try to connect to R1. Will wait for 1000ms and then re-try to connect to R2 or R3.
> > So you query execution time will be +1000ms.
> > by default connect_timeout_with_failover_ms=50ms because this value is suitable for Yandex.Metrica. All their servers close enough in Europe with latency less than 50ms.
> 
> Just to confirm. This will not affect the insertion latency if we do insertion directly to the shards (not though a replicated table), correct?

it will not impact inserts. It related to only selects from engine=Distributed

**Comment by OmarBazaraa** [comment]
> it will not impact inserts. It's related to only selects from engine=Distributed

What about the INSERTs to a distributed table?
Wouldn't the distributed table try to choose some healthy replicas as well?
