### ISSUE TITLE
Provide the ability to clear the history of clickhouse-client

### ISSUE THREAD

**Issue by OmarBazaraa** [ClickHouse/ClickHouse#15594]
Is it possible to provide commands for `clickhouse-client` to clear the console and clear the history?
Something similar to these Linux commands:
- `clear`
- `history -c`

Thanks

**Comment by den-crane** [comment]
WA: 

```
> ~/.clickhouse-client-history
```

**Comment by abe-winter** [comment]
for future googlers this is ~/.local/state/clickhouse/client-query-history on new installations

https://github.com/ClickHouse/ClickHouse/blob/aacade522213d270d3b20378747021e2152b7e00/src/Client/ClientBase.cpp#L4447
