### ISSUE TITLE
A table keep turning into read-only mode

### ISSUE THREAD

**Issue by OmarBazaraa** [ClickHouse/ClickHouse#15598]
I am facing a strange behavior with ClickHouse.

One of the replicas keep turning into readonly mode. I am detecting this by pinging the server as follows:
```
$ curl localhost:8123/replicas_status

Code: 242, e.displayText() = DB::Exception: Table is in readonly mode (version 20.5.2.7 (official build))
```

The strange behavior is that when I query `system.metrics` table I found that `ReadonlyReplica` metric have value of 0.

```
SELECT
    metric,
    value
FROM system.metrics
WHERE metric = 'ReadonlyReplica'

┌─metric──────────┬─value─┐
│ ReadonlyReplica │     0 │
└─────────────────┴───────┘

1 rows in set. Elapsed: 0.003 sec.
```

And even more, I can do `INSERT` queries to this replica without problems.

When I restart the server and ping it, it returns `Ok`. But after couple of hours, it fall back to the same behavior.

**Comment by den-crane** [comment]
check a table system.replicas is_readonly column

**Comment by sundy-li** [comment]
#15592

**Comment by OmarBazaraa** [comment]
I found a readonly table when checking `system.replicas`.
But why the number were not reflected in `ReadonlyReplica` in `system.metrics`?

**Comment by OmarBazaraa** [comment]
> check a table system.replicas is_readonly column

Thanks Denny.
I found the readonly table when I checked `system.replicas`, but this wasn't reflected in `ReadonlyReplica` metric in `system.metrics` table.

**Comment by akuzm** [comment]
The `ReadonlyReplica` metric was fixed in https://github.com/ClickHouse/ClickHouse/pull/15592
