### ISSUE TITLE
20.8.3.18 DB::RWLockImpl::unlock segfault

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#15610]
_Originally posted by @aubweb9 in https://github.com/ClickHouse/ClickHouse/issues/11940#issuecomment-699988601_

Hello,

I have kind of the same issue in version 20.8.3.18 
```
2020.09.27 21:07:16.306908 [ 23103 ] {} <Fatal> BaseDaemon: ########################################
2020.09.27 21:07:16.316298 [ 23103 ] {} <Fatal> BaseDaemon: (version 20.8.3.18 (official build), build id: E6AA632BFA7BC9A5) (from thread 10426) (query_id: 25afeec8-49ba-4c38-acfd-9740b30240eb) Received signal Segmentation fault (11)
2020.09.27 21:07:16.317599 [ 23103 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Address not mapped to object.
2020.09.27 21:07:16.317693 [ 23103 ] {} <Fatal> BaseDaemon: Stack trace: 0x16f1dece 0x1791e787 0x1791f909 0x181e830e 0x181e859d 0x181ddc6f 0x1763dd33 0x1774b63a 0x1774b6a6 0x1751c465 0x170286bd 0x180dcc3d 0x17f20460 0x17f250ad 0x17f2597$
2020.09.27 21:07:16.318812 [ 23103 ] {} <Fatal> BaseDaemon: 3. std::__1::__hash_iterator<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned l$
2020.09.27 21:07:16.318939 [ 23103 ] {} <Fatal> BaseDaemon: 4. DB::RWLockImpl::unlock(std::__1::__list_iterator<DB::RWLockImpl::Group, void*>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)$
2020.09.27 21:07:16.318976 [ 23103 ] {} <Fatal> BaseDaemon: 5. std::__1::__shared_ptr_emplace<DB::RWLockImpl::LockHolderImpl, std::__1::allocator<DB::RWLockImpl::LockHolderImpl> >::__on_zero_shared() @ 0x1791f909 in /usr/bin/clickhouse
2020.09.27 21:07:16.320705 [ 23103 ] {} <Fatal> BaseDaemon: 6. DB::ReadFromStorageStep::~ReadFromStorageStep() @ 0x181e830e in /usr/bin/clickhouse
2020.09.27 21:07:16.320754 [ 23103 ] {} <Fatal> BaseDaemon: 7. DB::ReadFromStorageStep::~ReadFromStorageStep() @ 0x181e859d in /usr/bin/clickhouse
2020.09.27 21:07:16.320792 [ 23103 ] {} <Fatal> BaseDaemon: 8. DB::QueryPlan::~QueryPlan() @ 0x181ddc6f in /usr/bin/clickhouse
2020.09.27 21:07:16.320848 [ 23103 ] {} <Fatal> BaseDaemon: 9. ? @ 0x1763dd33 in /usr/bin/clickhouse
2020.09.27 21:07:16.320888 [ 23103 ] {} <Fatal> BaseDaemon: 10. ? @ 0x1774b63a in /usr/bin/clickhouse
2020.09.27 21:07:16.320912 [ 23103 ] {} <Fatal> BaseDaemon: 11. ? @ 0x1774b6a6 in /usr/bin/clickhouse
2020.09.27 21:07:16.324712 [ 23103 ] {} <Fatal> BaseDaemon: 12. DB::LazyBlockInputStream::readImpl() @ 0x1751c465 in /usr/bin/clickhouse
2020.09.27 21:07:16.325591 [ 23103 ] {} <Fatal> BaseDaemon: 13. DB::IBlockInputStream::read() @ 0x170286bd in /usr/bin/clickhouse
2020.09.27 21:07:16.325642 [ 23103 ] {} <Fatal> BaseDaemon: 14. DB::CreatingSetsTransform::work() @ 0x180dcc3d in /usr/bin/clickhouse
2020.09.27 21:07:16.325684 [ 23103 ] {} <Fatal> BaseDaemon: 15. ? @ 0x17f20460 in /usr/bin/clickhouse
2020.09.27 21:07:16.325710 [ 23103 ] {} <Fatal> BaseDaemon: 16. ? @ 0x17f250ad in /usr/bin/clickhouse
2020.09.27 21:07:16.325735 [ 23103 ] {} <Fatal> BaseDaemon: 17. ? @ 0x17f25976 in /usr/bin/clickhouse
2020.09.27 21:07:16.325828 [ 23103 ] {} <Fatal> BaseDaemon: 18. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xffce517 in /usr/bin/clickhouse
2020.09.27 21:07:16.325854 [ 23103 ] {} <Fatal> BaseDaemon: 19. ? @ 0xffccb53 in /usr/bin/clickhouse
2020.09.27 21:07:16.325946 [ 23103 ] {} <Fatal> BaseDaemon: 20. start_thread @ 0x7fa3 in /usr/lib/x86_64-linux-gnu/libpthread-2.28.so
2020.09.27 21:07:16.326031 [ 23103 ] {} <Fatal> BaseDaemon: 21. clone @ 0xf94cf in /usr/lib/x86_64-linux-gnu/libc-2.28.so
```

**Comment by aubweb9** [comment]
This issue is happening few times a day on our production server but I can't reproduce it manually.
I checked the queries associated to the query_id in the err.log, it's not always the same the but only common point is this view : 

`CREATE VIEW datasources.view_mysql_last_insert_id_date
(
    `htl_id` Int32,
    `last_insert_id` Int32,
    `stay_date` Date,
    `data_source` String
) AS
SELECT 
    liid.htl_id,
    liid.last_insert_id,
    liid.stay_date,
    liid.data_source
FROM mysql('xxx.xxx.xxx.xxx:3306', 'datasources', 'sys_last_insert_id_date', 'xxx', 'xxx') AS liid`

**Comment by filimonov** [comment]
@aubweb9 the error message contains thread number and query_id (`...(from thread 10426) (query_id: 25afeec8-49ba-4c38-acfd-9740b30240eb)` in your example, plase trace back your log file to find the query with this id and / or last records from the log from that thread id.

**Comment by aubweb9** [comment]
@filimonov  please find the requested : 

[thead-28654.xlsx](https://github.com/ClickHouse/ClickHouse/files/5326382/thead-28654.xlsx)
[err.log](https://github.com/ClickHouse/ClickHouse/files/5326383/err.log)
[query.txt](https://github.com/ClickHouse/ClickHouse/files/5326384/query.txt)

**Comment by aubweb9** [comment]
Here's another log with the  Received signal Segmentation fault (11) we just had but I guess It's completely different ... 

[err.log_2.txt](https://github.com/ClickHouse/ClickHouse/files/5326416/err.log_2.txt)

**Comment by chenkaiyin1201** [comment]
Hello,
I have kind of the same issue with Clickhouse-Copier in version 20.9.2.20

**Comment by filimonov** [comment]
> Hello,
> I have kind of the same issue with Clickhouse-Copier in version 20.9.2.20

Most probably you have completely different issue. Please provide exact error message you have with stacktrace (from logs).

**Comment by KochetovNicolai** [comment]
Possible fix #15645 is in 20.8.4.
@aubweb9 could you please update to last 20.8 stable and check if issue still exists?

**Comment by aubweb9** [comment]
Hi @KochetovNicolai,

It's much better but now I am getting  : 

2020.10.13 11:37:56.521677 [ 13555 ] {071b9ae9-d9e8-43b6-bcf6-6c061b1b535a} <Error> Application: mysqlxx::ConnectionFailed
2020.10.13 11:37:56.524807 [ 13555 ] {071b9ae9-d9e8-43b6-bcf6-6c061b1b535a} <Error> executeQuery: Poco::Exception. Code: 1000, e.code() = 2026, e.displayText() = mysqlxx::ConnectionFailed: Unknown SSL error ((nullptr):3306) (version 20.$

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x18e1b360 in /usr/bin/clickhouse
1. ? @ 0x18c95d86 in /usr/bin/clickhouse
2. mysqlxx::Pool::allocConnection(bool) @ 0x18c9f361 in /usr/bin/clickhouse
3. mysqlxx::Pool::initialize() @ 0x18c9f70d in /usr/bin/clickhouse
4. mysqlxx::Pool::get() @ 0x18c9f918 in /usr/bin/clickhouse
5. DB::TableFunctionMySQL::executeImpl(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const @ 0x15288f50 in /usr/bin/clickhouse
6. DB::ITableFunction::execute(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const @ 0x1588d0d1 in /usr/bin/clickhouse
7. DB::Context::executeTableFunction(std::__1::shared_ptr<DB::IAST> const&) @ 0x1585ad9e in /usr/bin/clickhouse
8. DB::JoinedTables::getLeftTableStorage() @ 0x15cffb64 in /usr/bin/clickhouse
9. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, std::__1::shared_ptr<DB::IBlockInputStream> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&$
10. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::alloca$
11. DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>$
12. DB::StorageView::read(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > $
13. DB::ReadFromStorageStep::ReadFromStorageStep(std::__1::shared_ptr<DB::RWLockImpl::LockHolderImpl>, std::__1::shared_ptr<DB::StorageInMemoryMetadata const>&, DB::SelectQueryOptions, std::__1::shared_ptr<DB::IStorage>, std::__1::vecto$
14. DB::InterpreterSelectQuery::executeFetchColumns(DB::QueryProcessingStage::Enum, DB::QueryPlan&, std::__1::shared_ptr<DB::PrewhereInfo> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allo$
15. DB::InterpreterSelectQuery::executeImpl(DB::QueryPlan&, std::__1::shared_ptr<DB::IBlockInputStream> const&, std::__1::optional<DB::Pipe>) @ 0x15b36a23 in /usr/bin/clickhouse
16. DB::InterpreterSelectQuery::buildQueryPlan(DB::QueryPlan&) @ 0x15b38514 in /usr/bin/clickhouse
17. DB::InterpreterSelectWithUnionQuery::buildQueryPlan(DB::QueryPlan&) @ 0x15cb2258 in /usr/bin/clickhouse
18. DB::InterpreterSelectWithUnionQuery::execute() @ 0x15cb242a in /usr/bin/clickhouse
19. DB::SubqueryForSet::makeSource(std::__1::shared_ptr<DB::InterpreterSelectWithUnionQuery>&, std::__1::vector<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string$
20. DB::SelectQueryExpressionAnalyzer::makeTableJoin(DB::ASTTablesInSelectQueryElement const&) @ 0x15b738bc in /usr/bin/clickhouse
21. DB::SelectQueryExpressionAnalyzer::appendJoin(DB::ExpressionActionsChain&) @ 0x15b73d07 in /usr/bin/clickhouse
22. DB::ExpressionAnalysisResult::ExpressionAnalysisResult(DB::SelectQueryExpressionAnalyzer&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, bool, bool, bool, std::__1::shared_ptr<DB::FilterInfo> const&, DB::Block cons$
23. DB::InterpreterSelectQuery::getSampleBlockImpl() @ 0x15b2aa8d in /usr/bin/clickhouse
24. ? @ 0x15b3144a in /usr/bin/clickhouse
25. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, std::__1::shared_ptr<DB::IBlockInputStream> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const$
26. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::alloca$
27. DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>$
28. DB::JoinedTables::makeLeftTableSubquery(DB::SelectQueryOptions const&) @ 0x15cff9e4 in /usr/bin/clickhouse
29. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, std::__1::shared_ptr<DB::IBlockInputStream> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const$
30. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::alloca$
31. DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>$

and

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x18e1b360 in /usr/bin/clickhouse
1. ? @ 0x18c95d86 in /usr/bin/clickhouse
2. mysqlxx::Pool::allocConnection(bool) @ 0x18c9f361 in /usr/bin/clickhouse
3. mysqlxx::Pool::initialize() @ 0x18c9f70d in /usr/bin/clickhouse
4. mysqlxx::Pool::get() @ 0x18c9f918 in /usr/bin/clickhouse
5. DB::MySQLLazyBlockInputStream::readPrefix() @ 0x164ec668 in /usr/bin/clickhouse
6. DB::SourceFromInputStream::generate() @ 0x1674dd1c in /usr/bin/clickhouse
7. DB::ISource::work() @ 0x1651f65b in /usr/bin/clickhouse
8. DB::SourceFromInputStream::work() @ 0x1674dc05 in /usr/bin/clickhouse
9. ? @ 0x1655b260 in /usr/bin/clickhouse
10. ? @ 0x1655f4bd in /usr/bin/clickhouse
11. ? @ 0x1655fd86 in /usr/bin/clickhouse
12. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xe7645b7 in /usr/bin/clickhouse
13. ? @ 0xe762b03 in /usr/bin/clickhouse
14. start_thread @ 0x7fa3 in /usr/lib/x86_64-linux-gnu/libpthread-2.28.so
15. clone @ 0xf94cf in /usr/lib/x86_64-linux-gnu/libc-2.28.so

2020.10.13 11:38:16.924372 [ 13869 ] {eed82f5b-2ce2-419a-93d4-9bae5b7aaa2f} <Error> Application: mysqlxx::ConnectionFailed

**Comment by alexey-milovidov** [comment]
@aubweb9 But it's totally different issue, let's move it to another task.
And please provide more details - about SSL certificate on MySQL server...
