### ISSUE TITLE
<jemalloc>: perCPU arena getcpu() not available - How to resolve it

### ISSUE THREAD

**Issue by thangntt** [ClickHouse/ClickHouse#15611]
Dear all!
I have a problem when installed clickhouse.
Clickhouse version 20.9.2.20
OS: Centos 6.8 64bit
Error:  <jemalloc>: perCPU arena getcpu() not available, 
![image](https://user-images.githubusercontent.com/12496307/95065963-ee6c5f80-072b-11eb-89c6-280973ae4b42.png)

How to resolve this problem.
Thanks.

**Comment by filimonov** [comment]
It's just a notice saying your kernel doesn't have a newer API, and jemalloc used the fallback setting to determine the number of CPUs. Besides that, everything should work normally. 

You can just ignore it, or use a newer version of OS/kernel. Centos 6 is now in maintenance mode and its hard EOL is November 30th, 2020 (so you will not get even security patches afterward).

**Comment by thangntt** [comment]
> It's just a notice saying your kernel doesn't have a newer API, and jemalloc used the fallback setting to determine the number of CPUs. Besides that, everything should work normally.
> 
> You can just ignore it, or use a newer version of OS/kernel. Centos 6 is now in maintenance mode and its hard EOL is November 30th, 2020 (so you will not get even security patches afterward).

thank you so much.

**Comment by cipriancraciun** [comment]
For some reason this warning also pops-up in OpenSUSE Tumbleweed (rolling release) with an up-to-date kernel.  I'm using the static binaries from GitHub releases tab.

~~~~
>> clickhouse-client --version
<jemalloc>: Number of CPUs detected is not deterministic. Per-CPU arena disabled.
ClickHouse client version 22.3.18.37 (official build).

>> uname -a
Linux xiyipoke 6.1.7-1-default #1 SMP PREEMPT_DYNAMIC Wed Jan 18 11:12:34 UTC 2023 (872045c) x86_64 x86_64 x86_64 GNU/Linux
~~~~

I understand this is no issue at all, however when scripting multiple queries with `clickhouse-client` it does distract the console with lots of warning messages.

**Comment by gq-98** [comment]
我也有这问题，想请教下怎么解决他
![image](https://github.com/ClickHouse/ClickHouse/assets/79391747/7534fe53-b999-4a03-9801-f2c4c511f4b0)
