### ISSUE TITLE
Kafka consumers > partitions may lead to non-stopping rebalances 

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#15613]
It's an incorrect setup (you should have enough partitions for all consumers), but clickhouse behavior in that corner case is not very good currently, it seems some behavior of librdkafka changed in recent versions in that usecase.

We need to report that better, and avoid unneeded / often rebalances.

**Comment by filimonov** [comment]
Not confirmed.

**Comment by Cas-pian** [comment]
@filimonov why this is closed? I think we might hit the same issue, may be this is a bug in the kafka library?

**Comment by qoega** [comment]
Do you have reproducible case or at least diagnostics?
