### ISSUE TITLE
Conditional operators (if/case/ternary) always calculate all branches

### ISSUE THREAD

**Issue by StarWix** [ClickHouse/ClickHouse#1562]
Now ternary operator (function `if`) always calculates two branches.
```
SELECT 0 = 0 ? 0 : modulo(1, 0)
DB::Exception: Division by zero
```
I would like have opportunity to execute this expression. I.e. only correct branch should be calculated.

P.S: `Conditional expression` has the same problem.

**Comment by ludv1x** [comment]
At the moment lazy calculation works only for pure constants, not for constant expressions.
So, queries like `SELECT 1 ? 0 : 1 % 0` work.

**Comment by StarWix** [comment]
In  common case I would like execute query like this: SELECT column_x == 0 ? 0 : modulo(column_y, column_x)

**Comment by filimonov** [comment]
That sucks. Workarounds possible but they look really ugly.

For that case you can get desired result with something like:
`column_y % if(column_x = 0, if(column_y = 0, 1, column_y), column_x)`

```
SELECT 
    if((number % 4) = 0, 0, 12) AS column_x, 
    number AS column_y, 
    column_y % if(column_x = 0, if(column_y = 0, 1, column_y), column_x) AS column_y_modulo_column_x
FROM system.numbers 
WHERE number < 60
LIMIT 60
```

**Comment by StarWix** [comment]
Thanks for the idea.

Query can be more simple:
```sql
SELECT 
    if((number % 4) = 0, 0, 12) AS column_x, 
    number AS column_y, 
    column_y % if(column_x = 0, 1, column_x) AS column_y_modulo_column_x
FROM system.numbers 
WHERE number < 60
LIMIT 60
```

**Comment by ilyshnikova** [comment]
I'll take this issue

**Comment by alexey-milovidov** [comment]
Solutions discussed in #12587.

**Comment by CrystalCat** [comment]
I've got similar issue with demo bellow

drop table demo;
create table demo(id String, total Decimal(20,2), b Decimal(20,2)) ENGINE=Log;

insert into table demo select '1',100.00,20.00;
insert into table demo select '2',0,30.00;

select 
case when (total<>0) then round( ((total - b) /  total)*100, 2)  else 0 end per
from demo
;

┌───per─┐
│ 80.00 │
└───────┘
↗ Progress: 2.00 rows, 64.00 B (19.61 rows/s., 627.59 B/s.) 
Received exception from server (version 20.6.3):
Code: 153. DB::Exception: Received from localhost:9000. DB::Exception: Division by zero.

**Comment by 1332498780** [comment]
hi @CrystalCat , i encounter the similar problem, i resolved with the ways of @filimonov . but i find this way  on the bellow also can resolved this problem . 

```
select 
case when (total<>0) then round( ((total - b) /  case when total <> 0 then total else 1 end)*100, 2)  else 0 end per
from demo
;
```
results:
```
┌──per─┐
│ 0.00       │
└──────┘
┌───per─┐
│ 80.00       │
└───────┘
```

**Comment by Avogar** [comment]
After https://github.com/ClickHouse/ClickHouse/pull/23367 functions `if`, `or`, `and` and `multiIf` don't calculate all branches.

**Comment by billsbooth** [comment]
@Avogar this is not true; here is an example where both branches get calculated using an if statement: 

```
if (greater(first_value(token_stats_7d.first_price), toDecimal128(0, 18)), divideDecimal(first_value(token_stats_7d.last_price), first_value(token_stats_7d.first_price)), 0),
```

Get division by zero here, even if the evaluation of the condition is false.

**Comment by Algunenano** [comment]
Short circuit optimization depends on support from the underlying function: https://github.com/ClickHouse/ClickHouse/issues/74280
