### ISSUE TITLE
Row policy for distributed and replicated tables

### ISSUE THREAD

**Issue by keerthana-kannan-ch** [ClickHouse/ClickHouse#15621]
Hi,

I am trying to make use of the row policy feature to filter data based on the user running the query. I want to implement the policy on a replicated table with a distributed view on top of it.

How do I create the policy so that it is implemented across all the shards and replicas of a table? Is it possible to do so?

**Comment by avzhurav** [comment]
Hi, @alexey-milovidov provided some information about an internal connection usage (with own access rights)  between distributed and replicated tables in the last webinar. This feature is not documented yet. Does it possible to get more details how this internal connection correlates with the current active user, please?
The use case: I need to have several different users with different row policies for the same distributed table. Thank u in advance!

**Comment by thyn** [comment]
Can you share any information about that issue.
Can' set row filter for distributed table . Row Policy works only on none distributed tables
Clickhouse version is 20.12.4.5

**Comment by melvynator** [comment]
It seems that the support has been added: https://github.com/ClickHouse/ClickHouse/pull/8926
