### ISSUE TITLE
INTERVAL operator should be applicable to string literal.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#15637]
`INTERVAL '1 hour'` should be equivalent to `INTERVAL 1 HOUR`

**Use case**
People are used to Postgres.

**Comment by ucasFL** [comment]
If we implement this feature, how to simultaneously support `INTERVAL '1' HOUR` and `INTERVAL '1 HOUR'`? @alexey-milovidov
