### ISSUE TITLE
MaterializeMySQL DB reset criteria

### ISSUE THREAD

**Issue by liangli1213** [ClickHouse/ClickHouse#15702]
@zhang2014 @BohuTANG , I want to know, by what criteria will MaterializeMySQL delete all the table and resync it from source MySQL?
This morning I do reset master on MySQL, and change Executed GTID in .metadata, but I observed above phenomenon, so I want to know is all info in .metadata should consistent?

**Comment by BohuTANG** [comment]
A1:
Drop the MaterializeMySQL database and re-create will work again, this perhaps the only consistent way.

A2:
If you do `reset master` on MySQL side, this breaks the master-slave synchronization consistency design, even for mysql.
Think a case: 
the slave has many GTIDs behinds the Master, if we reset master slave can't find her position.

**Comment by liangli1213** [comment]
@BohuTANG , let me explain more clearly, here is the topology of the replication chain:

`MySQL Master -> MySQL Slave -> ClickHouse`

What I did on MySQL Slave is:
1. reset master
2. set global gtid_purged = 'xxxxxx:1-xxxx'

After this, MySQL Master to Slave's replication can work, but I notice MySQL Slave to ClickHouse's replication has been re-created.

I have changed the .metadata on the ClickHouse carefully (identical as xxxxxx:1-xxxx), so the behavior I expected is it will start replication on xxxx + 1, but thing are not as it, so I want to know why it has trigger the replication's re-create?

**Comment by liangli1213** [comment]
@BohuTANG @zhang2014 , I have done a test, mysqldb is a virtual IP, mysql1 and mysql2 are 2 physical server, at first mysqldb is on mysql2, then I have made MySQL to ClickHouse replication by using mysqldb as MySQL name, then I failover mysqldb to mysql1, obviously the Binlog File and Binlog Position has changed, it trigger the replication re-create, that is the thing I don't want to happen.

And also, this doesn't fully use the benefit of GTID, so please look into it.

```
[root@bdc-clickhouse rs_monitor]# cat .metadata 
Version:	2
Binlog File:	mysql-bin.005406
Executed GTID:	110a53f9-de98-11e9-bf81-00505696d56b:1-71094684,8ff4fda6-df42-11e9-be2a-0050569687c9:1-482203331
Binlog Position:	814457566
Data Version:	14495
```

**Comment by BohuTANG** [comment]
The `Binlog File` and `Binlog Position` in the .metadata is not used, we only use the `Executed GTID` info.
MySQL master or slave is rebuild, the replication channel will not be affected, this is what we use gtid for.

WARNING:
You can't do anything related to gtid, such as `set global gtid_purged`, or the replciation channel will be broken.

**Comment by liangli1213** [comment]
@BohuTANG , my test has different result, an VIP is floating between mysql1 and mysql2 (mysql1 and mysql1 has bi-direction replication), I made ClickHouse replication through VIP, at first, VIP reside on mysql1, then replication built up, then I switch VIP to mysql2, so do you think ClickHouse replication will continue?

**Comment by BohuTANG** [comment]
GTID replication mode works for it.

**Comment by liangli1213** [comment]
@BohuTANG , is that works on your side with my described configuration?

**Comment by BohuTANG** [comment]
We will have a try.

**Comment by liangli1213** [comment]
@BohuTANG , have you got a chance to reproduce it?

**Comment by liangli1213** [comment]
@BohuTANG @zhang2014 , in my environment I have below requirement, I think this is normal one and very useful for HA.

1. Retry to connect to MySQL if failed, just like MySQL slave keep trying to connect to master every 60s if failed
2. Replication keep going on when use VIP switching from one MySQL node to another

**Comment by BohuTANG** [comment]
Hi,
We are working on #15951,  this should be the next to be addressed.

**Comment by liangli1213** [comment]
@BohuTANG , the issue #15951 has been fixed, thanks very much, so I'd like to know if you have some plan for the below requirement?

1. Retry to connect to MySQL if failed, just like MySQL slave keep trying to connect to master every 60s if failed
2. Replication keep going on when use VIP switching from one MySQL node to another

**Comment by BohuTANG** [comment]
It makes sense.
I guess @TCeason is working on that.

**Comment by liangli1213** [comment]
Got it

**Comment by TCeason** [comment]
> @BohuTANG , the issue #15951 has been fixed, thanks very much, so I'd like to know if you have some plan for the below requirement?
> 
> 1. Retry to connect to MySQL if failed, just like MySQL slave keep trying to connect to master every 60s if failed
> 2. Replication keep going on when use VIP switching from one MySQL node to another

We think the ck's `detch database xx; attach database xx;`can work well as mysql `start slave`.

And I think you maybe need some deploy scripts.

Like:

In MySQL run `show slave hosts` to check the ck is synchronizing normally.

If not, detach db, attach db on ck.

We will also consider to support `show sync status` in ck like `show slave status` in MySQL.

**Comment by liangli1213** [comment]
@TCeason , thanks for your suggestion, this is a good way to detect the failure and recover it by script, and I have run the 'show slave hosts' command, and search the command's document, it seems the slave need to report it's information hence on master node, the information can be displayed correctly.

So far the necessary information for ClickHouse client is empty, so what I am thinking is, report <FQDN>_<MaterializeMySQL DB Name> as the host name, so I can get the client status from master, does this make sence?

Or, the 'show sync status' command from ClickHouse will also help me check the sync status, but so far, I only need the status of sync or not sync, no need for like 'Seconds_Behind_Master' or else information, so I think the above request is much easiler to realize.

```
root@bdcmysqldev1:(none)>show slave hosts;
+------------+------+------+-----------+--------------------------------------+
| Server_id  | Host | Port | Master_id | Slave_UUID                           |
+------------+------+------+-----------+--------------------------------------+
|        937 |      | 3306 |       936 | 110a53f9-de98-11e9-bf81-00505696d56b |
| 3806292935 |      |    0 |       936 |                                      |
| 1867918687 |      |    0 |       936 |                                      |
+------------+------+------+-----------+--------------------------------------+
```

**Comment by TCeason** [comment]
> @TCeason , thanks for your suggestion, this is a good way to detect the failure and recover it by script, and I have run the 'show slave hosts' command, and search the command's document, it seems the slave need to report it's information hence on master node, the information can be displayed correctly.
> 
> So far the necessary information for ClickHouse client is empty, so what I am thinking is, report _ as the host name, so I can get the client status from master, does this make sence?
> 
> Or, the 'show sync status' command from ClickHouse will also help me check the sync status, but so far, I only need the status of sync or not sync, no need for like 'Seconds_Behind_Master' or else information, so I think the above request is much easiler to realize.
> 
> ```
> root@bdcmysqldev1:(none)>show slave hosts;
> +------------+------+------+-----------+--------------------------------------+
> | Server_id  | Host | Port | Master_id | Slave_UUID                           |
> +------------+------+------+-----------+--------------------------------------+
> |        937 |      | 3306 |       936 | 110a53f9-de98-11e9-bf81-00505696d56b |
> | 3806292935 |      |    0 |       936 |                                      |
> | 1867918687 |      |    0 |       936 |                                      |
> +------------+------+------+-----------+--------------------------------------+
> ```

Yes, I absolutely agree with you.

**Comment by liangli1213** [comment]
What I want is, report `<FQDN>_<MaterializeMySQL DB Name>` as the host name.

**Comment by TCeason** [comment]
> What I want is, report `<FQDN>_<MaterializeMySQL DB Name>` as the host name.

Yep, already got it.
