### ISSUE TITLE
Question about ceil rows to complete granule

### ISSUE THREAD

**Issue by hustnn** [ClickHouse/ClickHouse#15704]
In `MergeTreeRangeReader::startReadingChain`, there is the logic of `stream.ceilRowsToCompleteGranules(space_left)`,
May I know in which case we need to read part of granule?

Can provide some sql case for to produce this case? Thanks.

**Comment by alexey-milovidov** [comment]
Reading less than one granule is needed when granule is large and we don't want to create large blocks in memory.
As far as I remember, it's controlled by `preferred_block_size_bytes` setting.

Set it to lower value, make a table with wide rows, do SELECT *, and you will notice reading less than one granule.

**Comment by hustnn** [comment]
@alexey-milovidov May I know why some reader (like `MergeTreeReaderCompact`) does not support reading of incomplete granule?

**Comment by alexey-milovidov** [comment]
It's expected that only small portion of data is in compact parts - so reading less than one granule is not worth development for compact parts.
Also now we are using "adaptive granularity" - if table rows are heavy, granules will have less amount of rows automatically (it makes reading less than one granule partially obsolete, thought it still makes sense).
