### ISSUE TITLE
Tuples IN bug

### ISSUE THREAD

**Issue by Fallenyasha** [ClickHouse/ClickHouse#15700]
При указании индексируемого столбца в кортеже при использовании оператора IN вылетает ошибка
DB::Exception: Number of columns in section IN doesn't match. 2 at left, 1 at right. (version 20.9.2.20 (official build))

Воспроизведение:
create table default.test
(
    id1 UInt64,
    id2 UInt64
)
engine = MergeTree order by id1 settings index_granularity = 8192;

select *
from default.test
where (id1, 0) in (select (1, 0));

В случае если в кортеже указать id2, то все будет работать, но любые комбинации с использованием id1 ведут к ошибке, подзапрос может быть любым, и константным и реальным подзапросом.

Если же указать набор без подзапроса, то все будет ок.
select *
from default.test
where (id1, 0) in (1, 0)

Данный баг не воспроизводится в старой версии КХ 19.4.5.1, в версиях 20.5 и 20.9 он уже есть.

**Comment by den-crane** [comment]
Though, may be it's not a bug after all.

select * from test where (id1, 0) in (select toUInt64(1), toUInt64(0));
0 rows in set. Elapsed: 0.001 sec.

Couple years ago we discussed that 

( , ) in (select **tuple()**) -- must be forbidden, because it's incorrect.

**Comment by den-crane** [comment]
( , ) -- круглые скобки создают tuple в КХ
( , ) in (select , ) -- это специальный синтаксис SQL и тут tuple() КХ все немного ломает. Скобки в select не нужны.

Обратите внимание на разницу:
```
SELECT 1,2

┌─1─┬─2─┐
│ 1 │ 2 │
└───┴───┘

SELECT (1, 2)

┌─tuple(1, 2)─┐
│ (1,2)       │
└─────────────┘
```

**Comment by Fallenyasha** [comment]
Такой синтаксис используется для проверки пар значений, например
select * from test where (id1, id2) in (select (filter1, filter2) from filter)

**Comment by Fallenyasha** [comment]
Указание пар значений без кортежа работает без ошибок
select * from test where (id1, id2) in (select filter1, filter2 from filter)

Просто странное поведение получается, что позволяет указывать кортежи, но только в случае, если не используется индексированное поле, причем не в правой части, а в левой.

**Comment by den-crane** [comment]
Я понял, правильное поведение именно выдавать ошибку **"DB::Exception: Number of columns in section IN doesn't match. 2 at left, 1 at right."**

Такой запрос должен падать, начиная с 

https://github.com/ClickHouse/ClickHouse/blob/master/docs/en/whats-new/changelog/2018.md#backward-incompatible-changes-backward-incompatible-changes-8
ClickHouse Release 1.1.54380, 2018-04-21 {#clickhouse-release-1-1-54380-2018-04-21}

_Removed support for expressions like (a, b) IN (SELECT (a, b)) (you can use the equivalent expression (a, b) IN (SELECT a, b)). In previous releases, these expressions led to undetermined WHERE filtering or caused errors._


например version 19.13.7
Received exception from server (version 19.13.7):
Code: 20. DB::Exception: Received from localhost:9000. DB::Exception: Number of columns in section IN doesn't match. 2 at left, 1 at right..

То что такой запрос завершался успешно в каких-то версиях после (1.1.54380, 2018-04-21) является ошибкой.

**Comment by den-crane** [comment]
Т.е. наоборот, то что сейчас работает вот такое: 
```
create table test(id1 UInt64,id2 UInt64)engine = MergeTree order by tuple();
select * from test where (id1, 0) in (select (1, 0));
Ok.

0 rows in set. Elapsed: 0.002 sec.
```
это баг, ожидаемое поведение: DB::Exception: Number of columns in section IN doesn't match. 2 at left, 1 at right..

**Comment by alexey-milovidov** [comment]
@den-crane it looks alright.
@CurtizJ please clarify.
