### ISSUE TITLE
Failed assertion in jemalloc: usize == isalloc(tsd_tsdn(tsd), ptr)

### ISSUE THREAD

**Issue by tavplubix** [ClickHouse/ClickHouse#15718]
https://clickhouse-test-reports.s3.yandex.net/15537/767a525031ccbc8cc77861c0e9ed3b5135af925f/fuzzer/fuzzer.log

**Comment by azat** [comment]
@tavplubix I looked into this a while ago and now, but there is not much I can understand w/o core dump (there was some changes around this in upstream, but this assertion is still preserved, but in another place)

I guess that there is ability to get core dump for this failure?
But is there any chance on adding core dump into fuzzer artifacts? (limited to, say, 50GiB maybe enough, and after compression it will has way more smaller size)

**Comment by tavplubix** [comment]
Forwarded from developers chat (in Russian):
```
Alexander Tokmakov, [03.11.20 10:53]
А есть ли возможность при падении фаззтеста загружать в s3 корку? https://github.com/ClickHouse/ClickHouse/issues/15718#issuecomment-720760400

Alexander Kuzmenkov, [03.11.20 11:00]
[In reply to Alexander Tokmakov]
Теоретически из таски сендбокса можно достать, но я ни разу не пробовал:
https://nda.ya.ru/t/rezGQcg43ZzdCJ

А это воспроизводится? Старую таску я почему-то не могу в сендбоксе найти.

Alexander Tokmakov, [03.11.20 11:01]
Ну я больше не видел таких падений, хотя может и воспроизводится

Alexander Kuzmenkov, [03.11.20 11:10]
В базе CI тоже нет, потому что ассерты из jemalloc не попадали в статус проверки -- там просто греп на некоторые паттерны. Я его добавил, посмотрим, будет ли воспроизводиться ещё.

Alexander Kuzmenkov, [03.11.20 11:14]
[In reply to Alexander Kuzmenkov]
На самом деле ещё и потому, что результаты фаззера туда вообще не заливаются...
```

**Comment by alexey-milovidov** [comment]
It looks similar with the assertion found here: #16836
`<jemalloc>: ../contrib/jemalloc/include/jemalloc/internal/arena_inlines_a.h:45: Failed assertion: "newarena != NULL"`
https://clickhouse-test-reports.s3.yandex.net/16836/6e8945d78c665e8b0155fcb8d8367320f538ebaa/fuzzer/server.log

We can see the possible reason in the log:
`thread constructor failed: Resource temporarily unavailable`
`Allocator: Cannot mmap 4.00 KiB., errno: 12, strerror: Cannot allocate memory`

```
It looks like that the process is near the limit on number of virtual memory mappings.
Current number of mappings (/proc/self/maps): 1048559.
Limit on number of mappings (/proc/sys/vm/max_map_count): 1048576.
You should increase the limit for vm.max_map_count in /etc/sysctl.conf
```

Looks like not a bug but a consequence of using too many separate mmaps in debug build.

It's also indicates the deficiency in jemalloc: it does not correctly handle mmap errors.

**Comment by azat** [comment]
>Looks like not a bug but a consequence of using too many separate mmaps in debug build.

@alexey-milovidov Indeed, this may be related.

>It's also indicates the deficiency in jemalloc: it does not correctly handle mmap errors.

However, at first glance return value of munmap/mmap are checked everywhere.
Although not all madvise calls are checked, need to look further to verify if this can lead to similar problems.

BTW is there any chance to obtain a core dump for analysis?

**Comment by azat** [comment]
Looking into the server logs one more time and I see some corruption (`^@27.0.0.2`) even before the jemalloc assertion:

```
2020.10.06 20:05:53.667989 [ 78 ] {} <Information> DNSResolver: Cached hosts not found: ^@27.0.0.2, ^@27.0.0.3, 127.^@.0.2, 127.^@.0.3, 127.0.0.^@, 127.0.0.2127.0.0.3127.0.0.2127.0.0.3, 127.0.0.3127.0.0.2127.0.0.2127.0.0.2, 127.0.0.3127.0.0.3127.0.0.3127.0.0.2, 127.0.0.3127.0.0.3, 127.0.0.2127.0.0.2127.0.0.3127.0.0.2, 127.0.0.2127.0.0.3127.0.0.3127.0.0.3, 127.0.0.3127.0.0.2127.0.0.3127.0.0.2, 127.0.0.2127.0.0.2, 127.0.0.2127.0.0.2127.0.0.3127.0.0.3, 127.0.0.2127.0.0.2127.0.0.2127.0.0.2, 127.0.0.2127.0.0.3, 127.0.0.3127.0.0.2, 127.0.0.2127.0.0.3127.0.0.2127.0.0.2, 127.0.0.3127.0.0.3127.0.0.2127.0.0.2, 127.0.0.3127.0.0.2127.0.0.3127.0.0.3, 127.0.0.3127.0.0.2127.0.0.2127.0.0.3, 127.0.0.3127.0.0.3127.0.0.2127.0.0.3, 127.0.0.2127.0.0.2127.0.0.2127.0.0.3, 127.0.0.2127.0.0.3127.0.0.3127.0.0.2, 127.0.0.3127.0.0.3127.0.0.3127.0.0.3
```

So I guess that this is not a problem of jemalloc.

@akuzm maybe it worth running fuzzer with ASAN?
Plus maybe it worth adding `MALLOC_CONF=abort_conf:true` (it will fail immediately for `munmap` failures, although this should not affect trigger such assertion)

Also I've looked into jemalloc error code path (madvise/mmap/munmap), and everything looks good, also I tested with fault injection, i.e.:

```
realloc-perf & # debug build
pgrep realloc-perf | xargs -r strace -C -qq -e munmap -f --fault=munmap:error=ENOMEM:when=100+20 -p
# fails in pthread -> free_stacks, not a jemalloc issue
realloc-perf & # debug build
pgrep realloc-perf | xargs -r strace -C -qq -e mmap -f --fault=mmap:error=ENOMEM:when=100+20 -p
# allocation failure and std::terminate
realloc-perf & # debug build
pgrep realloc-perf | xargs -r strace -C -qq -e madvise -f --fault=madvise:error=ENOMEM:when=100+20 -p
# errors are ignored - ok
```

And everything works as "expected" to me

**Comment by azat** [comment]
>@akuzm maybe it worth running fuzzer with ASAN?

Although under ASAN jemalloc will be disabled, so it should be a separate job, but this will make it almost meaningless

**Comment by alexey-milovidov** [comment]
> I see some corruption (^@27.0.0.2

I thought it's not a corruption but it's how the Query Fuzzer works :)

**Comment by azat** [comment]
>I thought it's not a corruption but it's how the Query Fuzzer works :)

I though about this too, but I cannot find anything similar in logs (i.e. `remote` with such address or similar, and actually this is not a valid host and it should not be even passed to `getaddrinfo`):

```
$ fgrep -a -i '.0.0' ~/Downloads/fuzzer.log 
$ fgrep -a -i '.0.0' ~/Downloads/server.log 
2020.10.06 20:05:53.667989 [ 78 ] {} <Information> DNSResolver: Cached hosts not found: 27.0.0.2, 27.0.0.3, 127..0.2, 127..0.3, 127.0.0., 127.0.0.2127.0.0.3127.0.0.2127.0.0.3, 127.0.0.3127.0.0.2127.0.0.2127.0.0.2, 127.0.0.3127.0.0.3127.0.0.3127.0.0.2, 127.0.0.3127.0.0.3, 127.0.0.2127.0.0.2127.0.0.3127.0.0.2, 127.0.0.2127.0.0.3127.0.0.3127.0.0.3, 127.0.0.3127.0.0.2127.0.0.3127.0.0.2, 127.0.0.2127.0.0.2, 127.0.0.2127.0.0.2127.0.0.3127.0.0.3, 127.0.0.2127.0.0.2127.0.0.2127.0.0.2, 127.0.0.2127.0.0.3, 127.0.0.3127.0.0.2, 127.0.0.2127.0.0.3127.0.0.2127.0.0.2, 127.0.0.3127.0.0.3127.0.0.2127.0.0.2, 127.0.0.3127.0.0.2127.0.0.3127.0.0.3, 127.0.0.3127.0.0.2127.0.0.2127.0.0.3, 127.0.0.3127.0.0.3127.0.0.2127.0.0.3, 127.0.0.2127.0.0.2127.0.0.2127.0.0.3, 127.0.0.2127.0.0.3127.0.0.3127.0.0.2, 127.0.0.3127.0.0.3127.0.0.3127.0.0.3
2020.10.06 20:06:08.922136 [ 83 ] {} <Information> DNSResolver: Cached hosts not found: 27.0.0.2, 27.0.0.3, 127..0.2, 127..0.3, 127.0.0., 127.0.0.2127.0.0.3127.0.0.2127.0.0.3, 127.0.0.3127.0.0.2127.0.0.2127.0.0.2, 127.0.0.3127.0.0.3127.0.0.3127.0.0.2, 127.0.0.3127.0.0.3, 127.0.0.2127.0.0.2127.0.0.3127.0.0.2, 127.0.0.2127.0.0.3127.0.0.3127.0.0.3, 127.0.0.3127.0.0.2127.0.0.3127.0.0.2, 127.0.0.2127.0.0.2, 127.0.0.2127.0.0.2127.0.0.3127.0.0.3, 127.0.0.2127.0.0.2127.0.0.2127.0.0.2, 127.0.0.2127.0.0.3, 127.0.0.3127.0.0.2, 127.0.0.2127.0.0.3127.0.0.2127.0.0.2, 127.0.0.3127.0.0.3127.0.0.2127.0.0.2, 127.0.0.3127.0.0.2127.0.0.3127.0.0.3, 127.0.0.3127.0.0.2127.0.0.2127.0.0.3, 127.0.0.3127.0.0.3127.0.0.2127.0.0.3, 127.0.0.2127.0.0.2127.0.0.2127.0.0.3, 127.0.0.2127.0.0.3127.0.0.3127.0.0.2, 127.0.0.3127.0.0.3127.0.0.3127.0.0.3
```

**Comment by alexey-milovidov** [comment]
We are going to enable Query Fuzzer with ASan, MSan, TSan, but after all existing issues will be fixed.
https://github.com/ClickHouse/ClickHouse/issues?q=is%3Aissue+is%3Aopen+label%3Afuzz

Only a few remains...

**Comment by alexey-milovidov** [comment]
Does not reproduce anymore.
