### ISSUE TITLE
Query caching seems to not work while using Distributed Engine

### ISSUE THREAD

**Issue by CaptainParanoid** [ClickHouse/ClickHouse#15730]
**What exactly works slower than expected?**

I have a replica setup for two merge tree tables
Like ch2 and ch3 have the actual table data and ch1 have a distributed engine table.
When a query is run from ch1 via the distributed table the query caching seems to not work. But if I run the queries directly on
ch2 or ch3 the caching works. Then subsequently the queries from ch1 also get faster.

**How to reproduce?**
*  Server version 20.5.4 revision 54435
* Interface used is JDBC
* default database set to testv2
* The issue only affects select statements
* Queries usually have subqueries of tables on different distributed tables with data on different remote servers

**Expected performance**
Enable caching and make the subsequent queries faster while querying from a distributed table.

**Comment by den-crane** [comment]
Please provide an example. Tables DDLs. 
What do you mean by "Enable caching" ? CH does not query cache as far as I know it not merged yet.

**Comment by CaptainParanoid** [comment]
This is not the exact DDL, but resembles our setup. The original table have about 25 columns
The distributed table in CH1:

```
CREATE TABLE testv2.customer_domain(
`domain` String,
 `customer_id` UInt32
) ENGINE = Distributed('ch_replicas',
 'testv2',
 'customer_domain')
```
This is the actual table in ch2 and ch3
```
CREATE TABLE testv2.customer_domain(
`domain` String,
 `customer_id` UInt32
) ENGINE = MergeTree PARTITION BY customer_id ORDER BY (customer_id, domain) SETTINGS index_granularity = 8192

```
This is the config
```
<remote_servers incl="clickhouse_remote_servers" >
	<ch_replicas>
            <shard>
                <replica>
                    <host>173.20.26.58</host>
                    <port>9000</port>
                    <secure>0</secure>
			<user>username</user>
			<password>a_password</password>
                </replica>
                 <replica>
                    <host>173.20.26.59</host>
                    <port>9000</port>
                    <secure>0</secure>
			<user>username</user>
			<password>another_password</password>
                </replica>
            </shard>
        </ch_replicas>	
    </remote_servers>
```

**Comment by CaptainParanoid** [comment]
> What do you mean by "Enable caching"? CH does not have a query cache. As far as I know this feature is not merged yet.
I meant you guys have so some kind off caching or marking to make the subsequent identical queries faster. I have seen it happen.  But it works if I query it directly and not via a distributed table.

**Comment by CaptainParanoid** [comment]
> Please provide an example, tables DDLs?
> What do you mean by "Enable caching" ? CH does not have a query cache. As far as I know this feature is not merged yet.

**Comment by den-crane** [comment]
>I meant you guys have so some kind off caching or marking to make the subsequent identical queries faster. 
>I have seen it happen. But it works if I query it directly and not via a distributed table.

CH does not have a query cache. 
You  are observing something else. Maybe query plan is different in these cases.

Please show an output of your queries in debug mode "set send_logs_level = 'debug'"

**Comment by DEBOJYOTI11** [comment]
Hi @den-crane 
Does this mean that this is incorrect - [https://stackoverflow.com/questions/60660781/how-to-maintain-cache-in-clickhouse](https://stackoverflow.com/questions/60660781/how-to-maintain-cache-in-clickhouse) ?

**Comment by den-crane** [comment]
@DEBOJYOTI11
1. query cache
2. disk cache
3. mark cache
4. dns cache
5. uncompressed cache
6. primary index cache
7. ...
8. ...
9. ...

All of these are completely different caches.
