### ISSUE TITLE
Race conditions in Cassandra library

### ISSUE THREAD

**Issue by alesapin** [ClickHouse/ClickHouse#15754]
Thread sanitizer found a lot of races in Cassandra library, examples: [1](https://gist.github.com/alesapin/96b14caa274a291f12dcf84cddc8ff5c), [2](https://gist.github.com/alesapin/bcb6ad9cd99e0c2e198ea4348db38145) and so on. I've tried to fix about 3 races, but there are much more. 

`RefCount` implementation seems unreliable, also `libuv` is not thread safe. Maybe we have to update library version? Or maybe we use it in the wrong way?

**Comment by tavplubix** [comment]
The first one is false-positive, tsan does not support `std::atomic_thread_fence` with acquire/release order: https://github.com/google/sanitizers/issues/1352
