### ISSUE TITLE
Website: bug in markup: part of the link is not clickable.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#15753]
Video:
https://drive.google.com/file/d/1V2aSELoi4X3aKJerJd30zM9EOBL00mu9/view?usp=sharing

**Comment by bharatnc** [comment]
Looks like this isn't a bug anymore and the link looks clickable.

**Comment by alexey-milovidov** [comment]
@bharatnc It depends on brower window width. With width about 1200 or lower, the link becomes not clickable at all.

This still considered a major bug.

**Comment by bharatnc** [comment]
> @bharatnc It depends on the browser window width. With width about 1200px or lower, the link becomes not clickable at all.
> 
> This still considered a major bug.

Right, I see it now.

**Comment by rfraposa** [comment]
Seems OK now
