### ISSUE TITLE
Update Incorrect

### ISSUE THREAD

**Issue by imperio-wxm** [ClickHouse/ClickHouse#15778]
Update with wrong value.

```sql
`job_state` Nullable(Int8)
```
The current job_state value is 3, I want to update it to 10

```sql
ALTER TABLE xxx UPDATE job_state = 10 WHERE name = 'xxx';
```

But after the execution, the value becomes -24, and does not change when update again.

ClickHouse version 20.3.5.21

**Comment by den-crane** [comment]
duplicate: https://github.com/ClickHouse/ClickHouse/issues/13634
fixed: https://github.com/ClickHouse/ClickHouse/pull/14646

20.3 is out support. 
This bug is fixed in the latest stable versions 20.7 20.8 20.9.
