### ISSUE TITLE
test finish_sorting_stream can not work properly

### ISSUE THREAD

**Issue by baibaichen** [ClickHouse/ClickHouse#15776]
**Describe the bug**

**How to reproduce**
just run test finish_sorting_stream

**Expected behavior**
Work as expection

**Error message and/or stacktrace**
when run finish_sorting_stream in DEBUG mode, i got the following errors:

```
Assertion failed: (false), function Exception, file /Users/xxxxxxx/OpenSource/ClickHouse/src/Common/Exception.cpp, line 45.
Signal: SIGABRT (signal SIGABRT)
Terminated due to signal 6
```

**Additional context**

```C++
            Block res_block = block_header;

            while (Block block = stream->read())
            {
                for (size_t i = 0; i < block.columns(); ++i)
                {
                    MutableColumnPtr ptr = IColumn::mutate(std::move(res_block.getByPosition(i).column));
                    ptr->insertRangeFrom(*block.getByPosition(i).column.get(), 0, block.rows());
                }
            }
```

I believe there were some changed invariants, after the first iteration, 
 `res_block.getByPosition(i).column` becomes null.

**Comment by baibaichen** [comment]
By reading comments from COW.h I can fix the null ptr
```c++
for (size_t i = 0; i < block.columns(); ++i)
{
    MutableColumnPtr ptr = IColumn::mutate(std::move(res_block.getByPosition(i).column));
    ptr->insertRangeFrom(*block.getByPosition(i).column.get(), 0, block.rows());
    res_block.getByPosition(i).column = std::move(ptr);
}
```

BUT, failed at check whether the stream is sorted or not

``` C++
// will failed at check the second cols
for (size_t i = 1; i < res_block.rows(); ++i)
    for (const auto & col : columns)
    {
        int res = col->compareAt(i - 1, i, *col, 1);
        if (res < 0)
            break;
        else if (res > 0)
            throw Exception("Result stream not sorted", ErrorCodes::LOGICAL_ERROR);
    }
``` 

Anyone can share information about how to fix it?

**Comment by alexey-milovidov** [comment]
As the test is not automated (It's not a unit test, it's not a functional test. I wouldn't even say that it's a test - it's just an example program), the simplest solution is to remove it. FinishSorting transform is well covered by functional tests.

**Comment by baibaichen** [comment]
I don't  find enough documentation about the Pipeline and [sorting](https://clickhousedb.slack.com/archives/CU170QE9H/p1601451196008500), so these examples are actually documentation, I hope they are maintained  to exactly reflect the latest usage.

would you please tell me which functional test cover FinishSorting ?

Thanks

**Comment by alexey-milovidov** [comment]
https://github.com/ClickHouse/ClickHouse/blob/master/tests/queries/0_stateless/00940_order_by_read_in_order.sql
