### ISSUE TITLE
Shutdown Server: INSERT INTO FUNCTION file() with glob without exists file 

### ISSUE THREAD

**Issue by Artemeey** [ClickHouse/ClickHouse#15777]
Ошибка возинкает, если в пути к файлу на запись указана звездочка и этого файла нет

`
INSERT INTO 
FUNCTION file('dirname/basename*', 'TabSeparatedRaw', 'void UInt8')
VALUES
(1)
`

Если файлов несколько - выбрасывается  штатное исключение _is in readonly mode because of globs in filepath_ (не ошибка)

Если файл существует и он один - ошибки нет, запись проихсодит (вероятно ошибка, неоднозначное поведение, запись в файл по пути с glob оператором производить не желательно)

**Если файл не найден - сервер завершет работу с ошибкой**

Пример исключения: 
<Fatal> BaseDaemon: ########################################
<Fatal> BaseDaemon: (version 20.6.5.8 (official build), build id: 6A911D3A969CCBFE) (from thread 144) (query_id: 9dcf090b-2c12-4084-915f-75835f2c4c58) Received signal Segmentation fault (11)
<Fatal> BaseDaemon: Address: NULL pointer. Access: read. Address not mapped to object.
<Fatal> BaseDaemon: Stack trace: 0x133af724 0xf65829e 0xf650881 0xf193bc6 0xf188a56 0xf4de46f 0xf4e202e 0xfaf72bc 0xfafaa16 0x122de933 0x1231cbeb 0x1231d07b 0x1249bba6 0x12496fa0 0x7f543169c609 0x7f54315b2103
<Fatal> BaseDaemon: 3. std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::rfind(char, unsigned long) const @ 0x133af724 in ?
 <Fatal> BaseDaemon: 4. DB::chooseCompressionMethod(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xf65829e in /usr/bin/clickhouse
<Fatal> BaseDaemon: 5. DB::StorageFile::write(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::Context const&) @ 0xf650881 in /usr/bin/clickhouse
<Fatal> BaseDaemon: 6. DB::PushingToViewsBlockOutputStream::PushingToViewsBlockOutputStream(std::__1::shared_ptr<DB::IStorage> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::Context const&, std::__1::shared_ptr<DB::IAST> const&, bool) @ 0xf193bc6 in /usr/bin/clickhouse
<Fatal> BaseDaemon: 7. DB::InterpreterInsertQuery::execute() @ 0xf188a56 in /usr/bin/clickhouse
<Fatal> BaseDaemon: 8. ? @ 0xf4de46f in /usr/bin/clickhouse
<Fatal> BaseDaemon: 9. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, DB::Context&, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>) @ 0xf4e202e in /usr/bin/clickhouse
<Fatal> BaseDaemon: 10. DB::HTTPHandler::processQuery(DB::Context&, Poco::Net::HTTPServerRequest&, HTMLForm&, Poco::Net::HTTPServerResponse&, DB::HTTPHandler::Output&) @ 0xfaf72bc in /usr/bin/clickhouse
<Fatal> BaseDaemon: 11. DB::HTTPHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&) @ 0xfafaa16 in /usr/bin/clickhouse
<Fatal> BaseDaemon: 12. Poco::Net::HTTPServerConnection::run() @ 0x122de933 in /usr/bin/clickhouse
<Fatal> BaseDaemon: 13. Poco::Net::TCPServerConnection::start() @ 0x1231cbeb in /usr/bin/clickhouse
<Fatal> BaseDaemon: 14. Poco::Net::TCPServerDispatcher::run() @ 0x1231d07b in /usr/bin/clickhouse
<Fatal> BaseDaemon: 15. Poco::PooledThread::run() @ 0x1249bba6 in /usr/bin/clickhouse
<Fatal> BaseDaemon: 16. Poco::ThreadImpl::runnableEntry(void*) @ 0x12496fa0 in /usr/bin/clickhouse
<Fatal> BaseDaemon: 17. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
<Fatal> BaseDaemon: 18. __clone @ 0x122103 in /usr/lib/x86_64-linux-gnu/libc-2.31.so

**Comment by tavplubix** [comment]
Fixed in #14887, backported to 20.6.7
