### ISSUE TITLE
For tables without a primary key, it is recommended to automatically add a hidden primary key when synchronizing to clickhouse, so that the synchronization can pass.

### ISSUE THREAD

**Issue by dbawangwei** [ClickHouse/ClickHouse#15782]
For tables without a primary key, it is recommended to automatically add a hidden primary key when synchronizing to clickhouse, so that the synchronization can pass.

**Comment by den-crane** [comment]
And your question is ?

**Comment by dbawangwei** [comment]
When the MySQL database is synchronized to clickhouse, the MySQL tables cannot be synchronized without a primary key. In production, many MySQL tables do not have a primary key for various reasons, so data cannot be synchronized to clickhouse.

**Comment by zhang2014** [comment]
This is impossible. Try to consider the following use cases
```
in mysql:> CREATE TABLE test(a int);
in mysql:> INSERT INTO test VALUES(1)(1)(2)(2)
in mysql:> UPDATE test SET a = 2 WHERE a = 1; /// ClickHouse will not know how to merge.
```
