### ISSUE TITLE
 Received signal Segmentation fault

### ISSUE THREAD

**Issue by lansane** [ClickHouse/ClickHouse#15781]
sometimes  a ch machine report:
ClickHouse version 19.17.4.11
2020.10.09 14:05:36.035856 [ 433 ] {} <Fatal> BaseDaemon: ########################################
2020.10.09 14:05:36.035926 [ 433 ] {} <Fatal> BaseDaemon: (version 19.17.4.11) (from thread 377) Received signal Segmentation fault (11).
2020.10.09 14:05:36.035945 [ 433 ] {} <Fatal> BaseDaemon: Address: 0x7f7102b402f0 Access: read. Attempted access has violated the permissions assigned to the memory area.
2020.10.09 14:05:36.035967 [ 433 ] {} <Fatal> BaseDaemon: Stack trace: 0x3523782 0x352384e 0x351f0bf 0x3513f9a 0x35149a1 0x3514d5b 0x333e4b2 0x333ed38 0x333eeca 0x62d72ba 0x359e471 0x35a14b1 0x6dbcc59 0x6db98bf 0x6db9fb5 0x723f481 0x723b208 0x791d69f 0x7f7e51ee1dd5 0x7f7e51a06ead
2020.10.09 14:05:36.036390 [ 434 ] {} <Fatal> BaseDaemon: ########################################
2020.10.09 14:05:36.036433 [ 434 ] {} <Fatal> BaseDaemon: (version 19.17.4.11) (from thread 433) Received signal Segmentation fault (11).
2020.10.09 14:05:36.036451 [ 434 ] {} <Fatal> BaseDaemon: Address: 0x7f7102b402f0 Access: read. Attempted access has violated the permissions assigned to the memory area.
2020.10.09 14:05:36.036463 [ 434 ] {} <Fatal> BaseDaemon: Stack trace: 0x3523782 0x352384e 0x351f0bf 0x3513f9a 0x3514420 0x366d622 0x791d69f 0x7f7e51ee1dd5 0x7f7e51a06ead
2020.10.09 14:05:36.036670 [ 435 ] {} <Fatal> BaseDaemon: ########################################
2020.10.09 14:05:36.036719 [ 435 ] {} <Fatal> BaseDaemon: (version 19.17.4.11) (from thread 434) Received signal Segmentation fault (11).
2020.10.09 14:05:36.036744 [ 435 ] {} <Fatal> BaseDaemon: Address: 0x7f7102b402f0 Access: read. Attempted access has violated the permissions assigned to the memory area.
2020.10.09 14:05:36.036764 [ 435 ] {} <Fatal> BaseDaemon: Stack trace: 0x3523782 0x352384e 0x351f0bf 0x3513f9a 0x3514420 0x366d622 0x791d69f 0x7f7e51ee1dd5 0x7f7e51a06ead
2020.10.09 14:05:36.037013 [ 436 ] {} <Fatal> BaseDaemon: ########################################
2020.10.09 14:05:36.037048 [ 436 ] {} <Fatal> BaseDaemon: (version 19.17.4.11) (from thread 435) Received signal Segmentation fault (11).
2020.10.09 14:05:36.037067 [ 436 ] {} <Fatal> BaseDaemon: Address: 0x7f7102b402f0 Access: read. Attempted access has violated the permissions assigned to the memory area.
2020.10.09 14:05:36.037078 [ 436 ] {} <Fatal> BaseDaemon: Stack trace: 0x3523782 0x352384e 0x351f0bf 0x3513f9a 0x3514420 0x366d622 0x791d69f 0x7f7e51ee1dd5 0x7f7e51a06ead
2020.10.09 14:05:36.037368 [ 437 ] {} <Fatal> BaseDaemon: ########################################
2020.10.09 14:05:36.037428 [ 437 ] {} <Fatal> BaseDaemon: (version 19.17.4.11) (from thread 436) Received signal Segmentation fault (11).
2020.10.09 14:05:36.037457 [ 437 ] {} <Fatal> BaseDaemon: Address: 0x7f7102b402f0 Access: read. Attempted access has violated the permissions assigned to the memory area.
2020.10.09 14:05:36.037478 [ 437 ] {} <Fatal> BaseDaemon: Stack trace: 0x3523782 0x352384e 0x351f0bf 0x3513f9a 0x3514420 0x366d622 0x791d69f 0x7f7e51ee1dd5 0x7f7e51a06ead
2020.10.09 14:05:36.037725 [ 438 ] {} <Fatal> BaseDaemon: ########################################

**Comment by den-crane** [comment]
19.17.4.11 - is out of support. Supported versions are 20.7 , 20.8 , 20.9

Also need more information. Do you get this error at one server or several? 
Can you show stacktraces , or full CH logs ?
