### ISSUE TITLE
Date and time functions fail when DateTime64 is out of normal range

### ISSUE THREAD

**Issue by zvonand** [ClickHouse/ClickHouse#15784]
To PR #9404
@Enmk 

**The following functions return incorrect result when passing it date-time that's out of normal range:**
`toYear()`, `toMonth()`, `toQuarter()`, `toTime()`, `toRelative[....]Num()`, `toStartOf[...]()`, `toMonday()`, `toWeek()`

***For example:***
`SELECT toYear(toDateTime64('1968-12-12 11:22:33', 0, 'UTC'))` returns `2105`
`SELECT toTime(toDateTime64('1800-11-30 18:00:00', 0, 'UTC'))` returns `1970-01-02 06:56:32`: the time must have remained the same
`SELECT toRelativeWeekNum(toDateTime64('1960-11-30 18:00:11.999', 3, 'UTC'))` returns 6627

**`toStartOfYear()`, `toStartOfMonth()`, `toStartOfQuarter()` returns zero timestamp even when in normal range:**
`SELECT toStartOfQuarter(toDateTime64('1990-01-04 12:14:12', 0, 'UTC'))` returns `0000-00-00`

**`toUnixTimestamp()` crashes when out of normal range:**
```
SELECT toUnixTimestamp(toDateTime64('1900-12-12 11:22:33', 0, 'UTC'))

Received exception from server (version 20.5.1):
Code: 407. DB::Exception: Received from localhost:9000. DB::Exception: DateTime64 convert overflow.

0 rows in set. Elapsed: 0.011 sec.
```

**Comment by den-crane** [comment]
@zvonand do you mean current stable CH or about code with PR #9404 ?

**Comment by zvonand** [comment]
> @zvonand do you mean current stable CH or about code with PR #9404 ?

PR #9404

**Comment by alexey-milovidov** [comment]
@zvonand I have finished the PR #9404 and checked your examples:

```
SELECT toYear(toDateTime64('1968-12-12 11:22:33', 0, 'UTC'))
```

Now works correctly.

```
1800-11-30 18:00:00
```

The year 1800 is still out of range, the minimum supported is 1925.

```
SELECT toRelativeWeekNum(toDateTime64('1960-11-30 18:00:11.999', 3, 'UTC'))
```

Returns 65063 which is correct in the sense of signed integer to UInt16 transform.

```
SELECT toStartOfQuarter(toDateTime64('1990-01-04 12:14:12', 0, 'UTC'))
```

Now works correct.

```
SELECT toUnixTimestamp(toDateTime64('1900-12-12 11:22:33', 0, 'UTC'))
```

It correctly gives you an error.

> toUnixTimestamp() crashes when out of normal range

The function is correctly throws an exception and the error message is correct.
You should never say "crash" to describe the correct program behaviour.
