### ISSUE TITLE
Question about primary key: Order of primary keys and performance differences.

### ISSUE THREAD

**Issue by moweonlee** [ClickHouse/ClickHouse#15787]
I have tested pairs of primary key to choose the most efficient composition of my table.

And a curious result is happening. And I'm trying to find reasons.

## TABLE SCHEME 

```
CREATE TABLE default.lcs_stms_array_basic_20190915
(
    `date` Date,
    `starttime` DateTime,
    `endtime` DateTime,
    `hour` UInt32,
    `minute` UInt32,
    `stname` String,
    `origin` String,
    `age` String,
    `gender` String,
    `os` String,
    `browser` String,
    `pv` UInt64,
    `users` Array(String)
)
ENGINE = MergeTree()
PARTITION BY toYYYYMM(date)
ORDER BY ${KEYS}
SETTINGS index_granularity = 8192
```
And two primary key options have been tested so far.

1st case : KEY="(stname, starttime)"
2nd case: KEY="(starttime, stname)"

## test QUERY

```
SELECT 
    hour,
    toUInt64(sum(pv / length(users))) AS pv,
    uniq(arrayJoin(users))
FROM default.lcs_stms_array_basic_20190915
WHERE stname LIKE 'SERVICE1/SERVICE2/SERVICE3%'
GROUP BY hour
ORDER BY hour ASC
```

## Result 

Test query only uses stname in where clause so starttime is not the matter.

But even though both stname and start are in the primary key composition, the number of processed rows are different in two cases.

1st case : KEY="(stname, starttime)"  
#24 rows in set. Elapsed: 0.359 sec. **Processed 1.65 million rows**, 450.02 MB (4.61 million rows/s., 1.25 GB/s.)

2nd case KEY="(starttime, stname)"
#24 rows in set. Elapsed: 0.336 sec. **Processed 2.15 million rows**, 610.71 MB (6.39 million rows/s., 1.82 GB/s.)

## Question

Can someone please explain why partial read works in only 1st case ?

Does partial read algorithm stops when it can not found primary key in where clause in sequence of primary keys?

**Comment by den-crane** [comment]
It's an expected behaviour as with any other database.

Indexes works on a prefix. Combined index on to columns (a,b) it's actually is a combine (ab)
So then you search `SERVICE1/SERVICE2/SERVICE3%` in `stnamestarttime` it works effectively.
And  ineffectively in case of `starttimestname`.
Most of other databases will not use the index in the second case at all (Oracle rdbms can do fast-full scan).

https://orangematter.solarwinds.com/2019/02/05/the-left-prefix-index-rule/

**Comment by moweonlee** [comment]
Thank you. @den-crane 

Thank you for good references too.
