### ISSUE TITLE
TSV/CSV export default value as Null setting.

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#15793]
Give the user the ability to set settings which would convert default values (0 for Int*, "" for String) to null in FORMAT TSV/CSV.

**Use case**
Users don't want to distinguish nulls from empty strings, but prefer to have in exported data nulls instead of default values.

**Describe the solution you'd like**
Add a setting which would allow the user to perform that kind of conversion.

**Describe alternatives you've considered**
Use the function nullIf(column,"") instead.

**Comment by den-crane** [comment]
Never saw a such feature before.
Default for a type? Not a column? Null for any numeric with 0, Null for any date with 1970-01-01 ?

**Comment by aadant** [comment]
I guess it only makes sense for Strings.

**Comment by alex-zaitsev** [comment]
TSV is already done, I guess: https://github.com/ClickHouse/ClickHouse/pull/14586

**Comment by alexey-milovidov** [comment]
@alex-zaitsev No, it is the opposite - to export NULL in custom representation.

**Comment by alexey-milovidov** [comment]
Workaround: just wrap everything to `nullIf(column, '')`.

**Comment by alexey-milovidov** [comment]
`nullIf(x, defaultValueOfArgumentType(x))` if you are generating the query.

**Comment by alexey-milovidov** [comment]
Maybe we can implement a function `nullIfDefault`.
