### ISSUE TITLE
Do not write trailing zeros for decimal values in clickhouse-client or TSV/CSV format

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#15794]
**Use case**
Pretty print and export decimal values which have high accuracy.

**Describe the solution you'd like**
Have a setting which would remove trailing zeros from clickhouse-client and TSV/CSV format output of decimal values.

**Describe alternatives you've considered**
```
taxi9 :) SELECT trim(TRAILING '0' FROM toString(toDecimal128('1312312231.1',20))) as s;

SELECT replaceRegexpOne(toString(toDecimal128('1312312231.1', 20)), concat('[', regexpQuoteMeta('0'), ']*$'), '') AS s

┌─s────────────┐
│ 1312312231.1 │
└──────────────┘

1 rows in set. Elapsed: 0.002 sec.

```

**Comment by alexey-milovidov** [comment]
Makes sense. Also I've found inefficient implementation.
