### ISSUE TITLE
tokenbf_v2 index does not drop rows in aggregation query

### ISSUE THREAD

**Issue by misja-alma** [ClickHouse/ClickHouse#15835]
The tokenbf_v2 index does not drop rows when used in an aggregation query. That is, according to the query trace, it is used and rows are said to be dropped, but eventually all rows are scanned anyway as if the index didn't exist.

In my case I have a (large) table like:

```
CREATE TABLE MY_TABLE
(
    `Year` LowCardinality(String),
    `Route` String,
    `Count` Float64
)
ENGINE = ReplicatedMergeTree
PARTITION BY Year,
ORDER BY (Month, Route, Count),
INDEX route_index (Route) TYPE tokenbf_v1(256, 2, 0) GRANULARITY 1,
SETTINGS index_granularity = 128;
```

Route is a comma separated string of id's, like '242341,345223,12341'. There can be hundreds of id's in a Route.

When I query: 

`select Count(*) from MYTABLE where Year = '2020' and hasToken(Route, '12341')`

the query trace shows this:

Key condition: (column 2 in ['2020, '2020']), unknown, and
MinMax index condition: (column 0 in ['2020', '2020']), unknown, and
Index `route_index` has dropped 254959 granules.
Selected 1 parts by date, 1 parts by key, 17961 marks to read from 7839 ranges
Reading approx. 2299008 rows with 2 streams

which looks good, but then it proceeds to read all rows anyway:

Aggregated. 233990 to 1 rows (from 0.225 MiB) in 5.498 sec. (42560.946 rows/sec., 0.041 MiB/sec.)
Aggregated. 104612 to 1 rows (from 0.102 MiB) in 5.774 sec. (18119.055 rows/sec., 0.018 MiB/sec.)
Aggregated. 130101 to 1 rows (from 0.127 MiB) in 5.775 sec. (22529.594 rows/sec., 0.022 MiB/sec.)
Aggregator: Merging aggregated data
executeQuery: Read **34925324** rows, 16.27 GiB in 5.966 sec., 5853956 rows/sec., 2.73 GiB/sec.

Actually if I run the query like this, which does not invoke the route_index:

`select Count(*) from MYTABLE where Year = '2020' and Route LIKE '%12341%'`

in this case the query will be faster! The reason is it also scans all rows but does not have the extra first step of the tokenbf index.

Expected behaviour:

Since the tokenbf_v2 filter was able to skip 34925324 - 2299008 rows, which is 93% of the total number of rows, I expected the hasToken query to be faster than the LIKE query which didn't use any index.
I don't understand why the hasToken query, after initially dropping all those rows, proceeds to scan all rows anyway.

**Comment by den-crane** [comment]
What CH version do you use?

**Comment by den-crane** [comment]
```sql
CREATE TABLE MY_TABLE
(
    `Year` LowCardinality(String),
    `Route` String,
    `Count` Float64,
    INDEX route_index (Route) TYPE tokenbf_v1(256, 2, 0) GRANULARITY 1
)
ENGINE = MergeTree
ORDER BY tuple()
SETTINGS index_granularity = 128;

insert into MY_TABLE select '2020', arrayStringConcat(arrayMap(i-> toString(intHash32(i*number)) ,range(10)),','), number
from numbers(100000);

insert into MY_TABLE select '2020', '2299008,2299008,2299008', number from numbers(100000000);

OPTIMIZE TABLE MY_TABLE FINAL

select Count(*) from MY_TABLE where hasToken(Route, '3119550599')
Index `route_index` has dropped 781655 / 782032 granules.
┌─Count()─┐
│       2 │
└─────────┘
1 rows in set. Elapsed: 0.219 sec. Processed 48.26 thousand rows, 5.58 MB (220.13 thousand rows/s., 25.46 MB/s.)


select Count(*) from MY_TABLE where Route like '%3119550599%'
┌─Count()─┐
│       2 │
└─────────┘
1 rows in set. Elapsed: 0.643 sec. Processed 100.10 million rows, 3.21 GB (155.56 million rows/s., 4.99 GB/s.)


alter table MY_TABLE drop index route_index;
select Count(*) from MY_TABLE where Route like '%3119550599%'
┌─Count()─┐
│       2 │
└─────────┘
1 rows in set. Elapsed: 0.459 sec. Processed 100.10 million rows, 3.21 GB (217.92 million rows/s., 6.99 GB/s.)


select Count(*) from MY_TABLE where hasToken(Route, '3119550599')
┌─Count()─┐
│       2 │
└─────────┘
1 rows in set. Elapsed: 0.443 sec. Processed 100.10 million rows, 3.21 GB (225.78 million rows/s., 7.24 GB/s.)

```

**Comment by misja-alma** [comment]
Thanks, I checked and you are right. I don't know what went wrong the first time but I recreated the table and now things seem to work correctly. Also nice that the index can also be used in LIKE queries, as long as I add the comma's.

However, I noticed that the difference starts to become smaller when there are more partitions filled in my table. In your example there is no partitioning but my table has partitioning by YEAR. When there is only one partition filled, the query is a lot faster with the route_index. But if I add more years, the difference in speed becomes much smaller.

**Comment by den-crane** [comment]
@misja-alma I don't understand what is you mean about partitions. Partition pruning works before index analysis.



```sql
CREATE TABLE MY_TABLE
(
    `Year` LowCardinality(String),
    `Route` String,
    `Count` Float64,
    INDEX route_index (Route) TYPE tokenbf_v1(256, 2, 0) GRANULARITY 1
)
ENGINE = MergeTree
partition by Year
ORDER BY tuple()
SETTINGS index_granularity = 128;

insert into MY_TABLE select '2020', arrayStringConcat(arrayMap(i-> toString(intHash32(i*number)) ,range(10)),','), number
from numbers(100000);
insert into MY_TABLE select '2020', '2299008,2299008,2299008', number from numbers(100000000);

insert into MY_TABLE select '2019', '2299008,2299008,2299008', number from numbers(100000000);
insert into MY_TABLE select '2019', arrayStringConcat(arrayMap(i-> toString(intHash32(i*number)) ,range(10)),','), number
from numbers(10000000);

optimize table MY_TABLE  final ;

select Count(*) from MY_TABLE where Year = '2020' and hasToken(Route, '3119550599');
1 rows in set. Elapsed: 0.238 sec. Processed 48.26 thousand rows, 5.63 MB (202.61 thousand rows/s., 23.64 MB/s.)

select Count(*) from MY_TABLE where Year = '2020' and  Route like '%3119550599%'
1 rows in set. Elapsed: 0.744 sec. Processed 100.10 million rows, 3.31 GB (134.52 million rows/s., 4.45 GB/s.)

select Count(*) from MY_TABLE where Year = '2020' and  Route like '%,3119550599,%'
1 rows in set. Elapsed: 0.233 sec. Processed 48.26 thousand rows, 5.63 MB (207.27 thousand rows/s., 24.18 MB/s.)

```

**Comment by misja-alma** [comment]
@den-crane I just reported what I was seeing. I also don't quite understand why the index query slowed down when filling more than one partition. But I have a feeling that it might just be the amount of data that made the index grow so large that it didn't fit into memory anymore.
To test this I tried making the index_granularity larger and the index queries started to be fast again, also with multiple partitions. This despite the fact that with larger index granularity the bloom filter cannot be as precise in dropping granules.

**Comment by den-crane** [comment]
>This despite the fact that with larger index granularity the bloom filter cannot be as precise in dropping granules.

Analyzing skip indexes is a super-slow process and they are heavy and need to read them from disk.
When an index granula covers many rows it speeds up the index analyzes but decreases number of dropped rows.
