### ISSUE TITLE
how to convert uuid type to a string or a number?

### ISSUE THREAD

**Issue by l1t1** [ClickHouse/ClickHouse#15834]
(you don't have to strictly follow this form)
```sql
SELECT concat(generateUUIDv4(), 'a')


Received exception from server (version 20.9.2):
Code: 44. DB::Exception: Received from localhost:9000. DB::Exception: Illegal column UInt128 of argument of function concat.

SELECT hex(generateUUIDv4())

Received exception from server (version 20.9.2):
Code: 43. DB::Exception: Received from localhost:9000. DB::Exception: Illegal type UUID of argument of function hex.

0 rows in set. Elapsed: 0.022 sec.
```
**Describe the bug**
A clear and concise description of what works not as it is supposed to.

**How to reproduce**
* Which ClickHouse server version to use
* Which interface to use, if matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

**Expected behavior**

**Error message and/or stacktrace**

**Additional context**

**Comment by den-crane** [comment]
1. toString 
   SELECT concat(toString(generateUUIDv4()), 'a')

2. 
```sql
SELECT hex(reinterpretAsString(generateUUIDv4()))

┌─hex(reinterpretAsString(generateUUIDv4()))─┐
│ DE4714DB26C20FB3D049657C3F60F99F           │
└────────────────────────────────────────────┘
```
