### ISSUE TITLE
kafka engine into ReplicatedMergeTree table

### ISSUE THREAD

**Issue by lddlww** [ClickHouse/ClickHouse#15836]
when ingest data from kafka to clickhouse table A use kafka engine，i have follow questions：
1、table A(ReplicatedMergeTree engine) have 2 replicas，do i need create kafka engine on both replicas？
2、if not；when one of replicas is broken，do i need create kafka engine on the other replica with manually？

**Comment by den-crane** [comment]
You should create all the same at both replicas
replicaA: kafka table, ReplicatedMergeTree table, materialized view
replicaB: kafka table, ReplicatedMergeTree table, materialized view

In this case both replica will ingest data from kafka in parallel (50%+50%).

In cause if replicaA is down another replica replicaB will continue to ingest all 100% kafka messages.

**Comment by lddlww** [comment]
> In this case both replica will ingest data from kafka in parallel (50%+50%).
> 
> In cause if replicaA is down another replica replicaB will continue to ingest all 100% kafka messages.
i think it's shard mode not replicas，or i missing somehting？

**Comment by den-crane** [comment]
You are missing something. 
There is no such things like `shard mode` or `replica mode`.

Everything will work as expected if you go my way.
