### ISSUE TITLE
MaterializeMySQL: support JSON data type

### ISSUE THREAD

**Issue by DBA-Ray** [ClickHouse/ClickHouse#15847]
2020.10.12 11:10:26.959593 [ 25982 ] {} <Error> MaterializeMySQLSyncThread: Code: 1002, e.displayText() = DB::Exception: ParseMetaData: Unhandled data type:245, Stack trace (when copying this message, always include the lines below):

0. DB::MySQLReplication::TableMapEvent::parseMeta(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) @ 0xdad58a5 in /usr/bin/clickhouse
1. DB::MySQLReplication::TableMapEvent::parseImpl(DB::ReadBuffer&) @ 0xdad520b in /usr/bin/clickhouse
2. DB::MySQLReplication::MySQLFlavor::readPayloadImpl(DB::ReadBuffer&) @ 0xdadb267 in /usr/bin/clickhouse
3. DB::MySQLProtocol::IMySQLReadPacket::readPayload(DB::ReadBuffer&, unsigned char&) @ 0xdac3f7d in /usr/bin/clickhouse
4. DB::MySQLProtocol::PacketEndpoint::tryReceivePacket(DB::MySQLProtocol::IMySQLReadPacket&, unsigned long) @ 0xdac4a83 in /usr/bin/clickhouse
5. DB::MaterializeMySQLSyncThread::synchronization(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xdaeea66 in /usr/bin/clickhouse
6. ? @ 0xdb0acbd in /usr/bin/clickhouse
7. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x7b8375d in /usr/bin/clickhouse
8. ? @ 0x7b87273 in /usr/bin/clickhouse
9. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
10. clone @ 0xfe8dd in /usr/lib64/libc-2.17.so
 (version 20.10.1.4881 (official build))

**Comment by zhang2014** [comment]
Can you provide some information on how to reproduce this problem?

**Comment by DBA-Ray** [comment]
I executed these following statements:

**set allow_experimental_database_materialize_mysql=1;
CREATE DATABASE xxx ENGINE = MaterializeMySQL('127.0.0.1:3377','xxx','xxx','xxx');**

Then clickhouse started to full synchronization by MaterializeMySQL from mysql.
But after a time,the log was:

**2020.10.12 11:10:26.329935 [ 25982 ] {} <Information> MaterializeMySQLSyncThread: MySQL dump database position: 
 
=== Binlog Position ===
Binlog: mysql-bin.000016
Position: 69443661
GTIDSets: 3d518df9-c4b2-11ea-b420-005056988658:1-421511,3ddc9e88-b983-11e9-8e6a-5254002e70a4:1-81,68627b42-3246-11ea-95f8-525400023d79:1-296830052,aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa:1-129617699

2020.10.12 11:10:26.959593 [ 25982 ] {} <Error> MaterializeMySQLSyncThread: Code: 1002, e.displayText() = DB::Exception: ParseMetaData: Unhandled data type:245, Stack trace (when copying this message, always include the lines below):

0. DB::MySQLReplication::TableMapEvent::parseMeta(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) @ 0xdad58a5 in /usr/bin/clickhouse
1. DB::MySQLReplication::TableMapEvent::parseImpl(DB::ReadBuffer&) @ 0xdad520b in /usr/bin/clickhouse
2. DB::MySQLReplication::MySQLFlavor::readPayloadImpl(DB::ReadBuffer&) @ 0xdadb267 in /usr/bin/clickhouse
3. DB::MySQLProtocol::IMySQLReadPacket::readPayload(DB::ReadBuffer&, unsigned char&) @ 0xdac3f7d in /usr/bin/clickhouse
4. DB::MySQLProtocol::PacketEndpoint::tryReceivePacket(DB::MySQLProtocol::IMySQLReadPacket&, unsigned long) @ 0xdac4a83 in /usr/bin/clickhouse
5. DB::MaterializeMySQLSyncThread::synchronization(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xdaeea66 in /usr/bin/clickhouse
6. ? @ 0xdb0acbd in /usr/bin/clickhouse
7. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x7b8375d in /usr/bin/clickhouse
8. ? @ 0x7b87273 in /usr/bin/clickhouse
9. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
10. clone @ 0xfe8dd in /usr/lib64/libc-2.17.so
 (version 20.10.1.4881 (official build))**

And i executed a simple query by the clickhouse-client,the result was:
**Code: 1002. DB::Exception: Received from localhost:9000. DB::Exception: ParseMetaData: Unhandled data type:245.**

**Comment by alexey-milovidov** [comment]
@zhang2014 

`MetaData` should be written as `Metadata`.

**Comment by tavplubix** [comment]
245 (0xf5) is for `MYSQL_TYPE_JSON`, it's not supported

**Comment by fengyunyuanyue** [comment]
> 245 (0xf5) is for `MYSQL_TYPE_JSON`, it's not supported

<Error> executeQuery: Code: 1002, e.displayText() = DB::Exception: ParseMetaData: Unhandled data type:16 (version 21.7.3.14 (official build)) (from [::1]:9056) (in query: select count(*) from test;), Stack trace (when copying this message, always include the lines below):

what type is 16???
