### ISSUE TITLE
Must there be enough memory to use GROUP BY?

### ISSUE THREAD

**Issue by qinglok** [ClickHouse/ClickHouse#15848]
The computer used for testing has 16GB of RAM.
These configurations have been set:
`<max_memory_usage_for_all_queries>12000000000</max_memory_usage_for_all_queries>
            <max_bytes_before_external_group_by>6000000000</max_bytes_before_external_group_by>
            <max_memory_usage>12000000000</max_memory_usage>`
But still got an error:
DB::Exception: Memory limit (total) exceeded: would use 13.95 GiB (attempt to allocate chunk of 134217760 bytes), maximum: 13.90 GiB: While executing AggregatingTransform.

**Comment by den-crane** [comment]
What CH version do you use?

Try to lower max_memory_usage  to 10G `<max_memory_usage>10000000000` and max_bytes_before_external_group_by to 4G `<max_bytes_before_external_group_by>4000000000`

**Comment by qinglok** [comment]
Yes, it seems to solve the problem.

Another question about AggregatingMergeTree is why there is no data in the tables of the AggregatingMergeTree engine after the CH service is restarted?

**Comment by den-crane** [comment]
What CH version do you use?

>Another question about AggregatingMergeTree is why there is no data in the 
>tables of the AggregatingMergeTree engine after the CH service is restarted?

Disk corruption? 
Check startup messages **grep table_name /var/log/clickhouse-server/clickhouse-server.log**

**Comment by qinglok** [comment]
CH version is 20.8.2.3-2.
The disk is normal. Because I can see that there are still files in the data directory of CH.
However, after the CH service is restarted, no data can be found by using SELECT.
But now I can’t reproduce the same situation.
