### ISSUE TITLE
How to copy/backup a table efficiently?

### ISSUE THREAD

**Issue by y45398jp123** [ClickHouse/ClickHouse#15846]
Hi, Recently I want to make a copy of my table to backup the data to another server. 
I copied all partitions of the tables (and the corresponding metadata sql file) to a new server and started CH on that new server, and it works perfectly. 
But the table I tried is very small (just for testing). I'm wondering does it work in a big table as well, because the background process is constantly working there, e.g. merging or something. I'm worried that when I copy the part files, some parts may be missed or new-produced due to  the CH background process. Do I have to stop the CH before copying the table parts? what is the best practise to backup a big table?
Thanks a lot.

**Comment by den-crane** [comment]
https://clickhouse.tech/docs/en/sql-reference/statements/alter/partition/#alter_freeze-partition

You can use `alter table T.. freeze`. 
FREEZE creates a snapshot in /var/lib/clickhouse/shadow 
You can copy this snapshot by rsync or any other tool to another server or into backup.
