### ISSUE TITLE
How to remove default value for column?

### ISSUE THREAD

**Issue by MasterGroosha** [ClickHouse/ClickHouse#15851]
Hello. Here's a table for example:
```sql
CREATE TABLE test.table1
(
        EventDate Date,
        Id Int32,
        Value String default 'strstrstr'
)
Engine = MergeTree()
PARTITION BY toYYYYMM(EventDate)
ORDER BY Id;
```

I can modify default value for "Value" column like: `ALTER TABLE test.table1 MODIFY COLUMN Value DEFAULT 'mystring'`
But how can I remove this default value? Even if I execute `ALTER TABLE test.table1 MODIFY COLUMN Value DEFAULT ''`, it just defaults to an empty string.
And also I cannot do this for types like Int32, because this will throw an error on future SELECT

**Comment by den-crane** [comment]
String type:  MODIFY COLUMN Value DEFAULT ''
Int32 type:  MODIFY COLUMN Value DEFAULT 0

**Comment by den-crane** [comment]
And from CH 20.10

```sql
alter table table1 
   MODIFY COLUMN Value 
   REMOVE DEFAULT;
```

**Comment by MasterGroosha** [comment]
@den-crane Thank you! Looking forward to installing 20.10 as soon as it is released.
