### ISSUE TITLE
process '/usr/bin/clickhouse' started with executable stack

### ISSUE THREAD

**Issue by socketpair** [ClickHouse/ClickHouse#15872]
This line is written in my dmesg in Fedora 32. Seems it is security related.

**Comment by socketpair** [comment]
version 20.7.2.30

**Comment by filimonov** [comment]
https://linux.die.net/man/8/execstack

**Comment by socketpair** [comment]
Also, I see `capability: warning: `clickhouse-serv' uses 32-bit capabilities (legacy support in use)`. Is it a separate issue ?

**Comment by alexey-milovidov** [comment]
@filimonov We should not have executable stack. It's build issue. Do we have this issue in recent versions in official build?

@socketpair `capability: warning` and this is not an issue at all.

**Comment by alexey-milovidov** [comment]
```
Wa,--noexecstack 
Wl,'-z noexecstack'
```

should help.

**Comment by filimonov** [comment]
> Do we have this issue in recent versions in official build? 

I don't think so:
```
# 20.9.3.45 (official build)
 execstack -q /usr/bin/clickhouse
- /usr/bin/clickhouse

# 20.7.2.30 (official build)
 execstack -q /usr/bin/clickhouse 
- /usr/bin/clickhouse
```

@socketpair what kind of build do you use?

**Comment by socketpair** [comment]
We use standard Fedora 32 build system (RPM). spec file: https://pastebin.com/tNHsYssE

**Comment by socketpair** [comment]
https://fedoraproject.org/wiki/Packaging_tricks#Executable_stack

Possibly clang-related issue.

**Comment by socketpair** [comment]
No, I have just repeated steps in Fedora 32 exactly as written here: https://clickhouse.tech/docs/ru/development/build/

```
$ execstack -q clickhouse
X clickhouse
```
Please reopen.

**Comment by den-crane** [comment]
it seems an issue is in rpm .spec file

**Comment by socketpair** [comment]
```
/usr/bin/ld.gold: warning: extract/glibc-compatibility/longjmp.s.o: missing .note.GNU-stack section implies executable stack
/usr/bin/ld.gold: warning: extract/glibc-compatibility/syscall.s.o: missing .note.GNU-stack section implies executable stack
```

```
./base/glibc-compatibility/musl/aarch64/longjmp.s
./base/glibc-compatibility/musl/x86_64/longjmp.s
```

Seems handcrafted assembler files miss section definitons

**Comment by alexey-milovidov** [comment]
We don't use `ld.gold` anymore.
We also don't build rpm from "spec".
