### ISSUE TITLE
DB::Exception: Double-distributed IN/JOIN subqueries is denied (distributed_product_mode = 'deny')

### ISSUE THREAD

**Issue by chang0391** [ClickHouse/ClickHouse#15888]
**Describe the bug**
version: 20.9.3
There are two tables with Distributed table engine to join each other.
when I executed "select *from test_all a join (select distinct name from credit_ga.test_all_2 where id<5) b on  a.name=b.name order by a.name", it show error message "DB::Exception: Double-distributed IN/JOIN subqueries is denied"
but  when I execute "select *from (select name from test_all) a join (select distinct name from credit_ga.test_all_2 where id<5) b on  a.name=b.name order by a.name" , it show result no error.
I think that the two SQL sentences is same
**How to reproduce**
test-1-118.raipeng.com :) select *from test_all a join (select distinct name from credit_ga.test_all_2 where id<5) b on  a.name=b.name order by a.name
SELECT *
FROM test_all AS a
INNER JOIN 
(
    SELECT DISTINCT name
    FROM credit_ga.test_all_2
    WHERE id < 5
) AS b ON a.name = b.name
ORDER BY a.name ASC
Received exception from server (version 20.9.3):
Code: 288. DB::Exception: Received from localhost:9000. DB::Exception: Double-distributed IN/JOIN subqueries is denied (distributed_product_mode = 'deny'). You may rewrite query to use local tables in subqueries, or use GLOBAL keyword, or set distributed_product_mode to suitable value.. 
0 rows in set. Elapsed: 0.004 sec. 
test-1-118.raipeng.com :) select *from (select name from test_all) a join (select distinct name from credit_ga.test_all_2 where id<5) b on  a.name=b.name order by a.name
SELECT *
FROM 
(
    SELECT name
    FROM test_all
) AS a
INNER JOIN 
(
    SELECT DISTINCT name
    FROM credit_ga.test_all_2
    WHERE id < 5
) AS b ON a.name = b.name
ORDER BY a.name ASC

┌─name─┬─b.name─┐
│ 1    │ 1      │
│ 1    │ 1      │
│ 1    │ 1      │
│ 2    │ 2      │
│ 2    │ 2      │
│ 3    │ 3      │
│ 3    │ 3      │
│ 4    │ 4      │
│ 4    │ 4      │
│ 5    │ 5      │
└──────┴────────┘

10 rows in set. Elapsed: 0.027 sec.

**Comment by den-crane** [comment]
```sql
1)
select *
from test_all a 
     join (select distinct name from credit_ga.test_all_2 where id<5) b on a.name=b.name 
order by a.name

2)
select *
from (select name from test_all) a 
    join (select distinct name from credit_ga.test_all_2 where id<5) b on a.name=b.name 
order by a.name
```

>I think that the two SQL sentences is same

They are not.
SQL1 executes join at shards. Each shard of `test_all` executes a subquery `b` and does join.
SQL2 executes join at an initiator.  Initiator executes subqueries `a` and `b` and does join by itself.

Both SQL are valid and useful. SQL1 require double join enabled, because all shard will execute subquery `b` (`set distributed_product_mode = 'allow'`).

**Comment by radash123** [comment]
SELECT category_id, COUNT(*)
FROM my_table
WHERE category_id IN
(
  SELECT category_id
  FROM my_table
  WHERE ts BETWEEN '2023-01-01' AND '2023-01-31' AND config_id = 123
  GROUP BY category_id
  ORDER BY COUNT(*) DESC
  LIMIT 5
)
  AND ts BETWEEN '2023-01-01' AND '2023-01-31' AND config_id = 123
GROUP BY category_id
UNION ALL
SELECT category_id, COUNT(*)
FROM my_table
WHERE category_id NOT IN
(
  SELECT category_id
  FROM my_table
  WHERE ts BETWEEN '2023-01-01' AND '2023-01-31' AND config_id = 123
  GROUP BY category_id
  ORDER BY COUNT(*) DESC
  LIMIT 5
)
  AND ts BETWEEN '2023-01-01' AND '2023-01-31' AND config_id = 123
GROUP BY category_id

Code: 288. DB::Exception: Double-distributed IN/JOIN subqueries is denied (distributed_product_mode = 'deny'). You may rewrite query to use local tables in subqueries, or use GLOBAL keyword, or set distributed_product_mode to suitable value.: While processing  repdb.dnsactivity: While processing category_id NOT IN (SELECT category_id FROM repdb.dnsactivity WHERE ((ts >= '2023-01-01') AND (ts <= '2023-01-31')) AND (config_id = 123) GROUP BY category_id ORDER BY COUNT(*) DESC LIMIT 5). (DISTRIBUTED_IN_JOIN_SUBQUERY_DENIED) (version 23.4.2.11 (official build))
