### ISSUE TITLE
How to solve Zookeeper write length exceeding 1M

### ISSUE THREAD

**Issue by gubinjie** [ClickHouse/ClickHouse#15882]
When inserting data using the Clickhouse cluster, Zookeeper throws that the write length exceeds 1M.
1.Under what circumstances will the write length exceed 1M.
2. How to solve this problem?

**Comment by den-crane** [comment]
Check this https://github.com/ClickHouse/ClickHouse/issues/11933#issuecomment-654286261

export SERVER_JVMFLAGS="-Djute.maxbuffer=50000000" bin/zkServer.sh restart
