### ISSUE TITLE
When I execute creating MaterializeMySQL ,I get a error about that Estimated query execution time is too long

### ISSUE THREAD

**Issue by yanchaoguo** [ClickHouse/ClickHouse#15885]
2020.10.13 10:06:53.544988 [ 4013 ] {cdb8f79e-4df8-4199-b971-4ca0426072d7} <Error> DynamicQueryHandler: Code: 160, e.displayText() = DB::Exception: Estimated query execution time (83959.94142256283 seconds) is too long. Maximum: 20. Estimated rows to process: 1630209: While executing MergeTreeThread, Stack trace (when copying this message, always include the lines below):

0. DB::ExecutionSpeedLimits::throttle(unsigned long, unsigned long, unsigned long, unsigned long) const @ 0xd714aad in /usr/bin/clickhouse
1. DB::SourceWithProgress::progress(DB::Progress const&) @ 0xe707700 in /usr/bin/clickhouse
2. DB::MergeTreeBaseSelectProcessor::readFromPartImpl() @ 0xe3f41ed in /usr/bin/clickhouse
3. DB::MergeTreeBaseSelectProcessor::readFromPart() @ 0xe3f4bcd in /usr/bin/clickhouse
4. DB::MergeTreeBaseSelectProcessor::generate() @ 0xe3f347b in /usr/bin/clickhouse

**Comment by zhang2014** [comment]
Can you provide some information on how to reproduce this problem?
