### ISSUE TITLE
DB::Exception: Type mismatch of columns to JOIN by: id Int32 at left, bb.id Int64 at right

### ISSUE THREAD

**Issue by chang0391** [ClickHouse/ClickHouse#15884]
**Describe the bug**
version: 20.9.3

I have two tables join, one table have column of 32-bit numeric type and the other one have column of 64-bit numeric type,
but the data stored is very small, when I executed two table join, it show below error
"" DB::Exception: Type mismatch of columns to JOIN by: id Int32 at left, bb.id Int64 at right""

**How to reproduce**
test-1-118.raipeng.com :) create table aa(id Int32,name String) engine=MergeTree order by id
CREATE TABLE aa
(
    `id` Int32,
    `name` String
)
ENGINE = MergeTree
ORDER BY id
Ok.
0 rows in set. Elapsed: 0.006 sec. 
test-1-118.raipeng.com :) create table bb(id Int64,name String) engine=MergeTree order by id
CREATE TABLE bb
(
    `id` Int64,
    `name` String
)
ENGINE = MergeTree
ORDER BY id
Ok.
0 rows in set. Elapsed: 0.004 sec. 
test-1-118.raipeng.com :) insert into aa values(1,1)
INSERT INTO aa VALUES
Ok.
1 rows in set. Elapsed: 0.007 sec. 
test-1-118.raipeng.com :) insert into bb values(1,1)
INSERT INTO bb VALUES
Ok.
1 rows in set. Elapsed: 0.004 sec. 
test-1-118.raipeng.com :) select *from aa a join bb b on a.id=b.id
SELECT *
FROM aa AS a
INNER JOIN bb AS b ON a.id = b.id
Received exception from server (version 20.9.3):
Code: 53. DB::Exception: Received from localhost:9000. DB::Exception: Type mismatch of columns to JOIN by: id Int32 at left, b.id Int64 at right. 
0 rows in set. Elapsed: 0.006 sec.

**Comment by den-crane** [comment]
Expected behavior , you should use type casting -- toInt64

**select * from aa a join bb b on toInt64(a.id)=b.id**

**Comment by chang0391** [comment]
@den-crane 
 
     Since they are both int type, why need to convert them? I know that other databases not need that like MySQL.

**Comment by den-crane** [comment]
https://clickhouse.tech/docs/en/sql-reference/functions/#strong-typing

Strong Typing 

In contrast **to standard SQL, ClickHouse has strong typing**. In other words, it doesn’t make implicit conversions between types. Each function works for a specific set of types. This means that sometimes you need to use type conversion functions.
