### ISSUE TITLE
Strange error for distributed table engine

### ISSUE THREAD

**Issue by chang0391** [ClickHouse/ClickHouse#15898]
**Describe the bug**
I got error "Table default.test_all_2 doesn't exist.. "  when I executed tables join  with distributed table engine
I already entered database credit_ga, but it report the table doesn't exist in database default, so it's strange
but when I use global join instead of join, I got the result as below.
additional, by my testing, result for global join and join is same for two tables of distributed table engine,
only one table with distributed table engine joins another table with no distributed table engine, which need global join.
so can you explain?thanks

**How to reproduce**
test-1-118.raipeng.com :) use credit_ga
USE credit_ga
Ok.
0 rows in set. Elapsed: 0.001 sec. 
test-1-118.raipeng.com :) select count(1) from test_all a join test_all_2 b on a.name=b.name
SELECT count(1)
FROM test_all AS a
INNER JOIN test_all_2 AS b ON a.name = b.name
↖ Progress: 20.00 rows, 201.00 B (180.34 rows/s., 1.81 KB/s.)  0%
Received exception from server (version 20.9.3):
Code: 60. DB::Exception: Received from localhost:9000. DB::Exception: Received from 192.168.1.187:9000. DB::Exception: Table default.test_all_2 doesn't exist.. 
0 rows in set. Elapsed: 0.112 sec. 

test-1-118.raipeng.com :) select count(1) from test_all a global join test_all_2 b on a.name=b.name
SELECT count(1)
FROM test_all AS a
GLOBAL INNER JOIN test_all_2 AS b ON a.name = b.name
┌─count(1)─┐
│       21 │
└──────────┘
1 rows in set. Elapsed: 0.024 sec.

**Comment by den-crane** [comment]
duplicate: https://github.com/ClickHouse/ClickHouse/issues/10471
