### ISSUE TITLE
same result for global join and join of tables with distributed engine

### ISSUE THREAD

**Issue by chang0391** [ClickHouse/ClickHouse#15891]
version: 20.9.3.45

For distributed table engine, if tables join with column of no primary key , should it use global join or join?
by my testing, I found that if the two tables of distributed table engine join each other by global join and join with Join field is not primary key, it show same correct result.
so, Does it mean that both join and global join can be used when joining distributed tables
for example:
```
remark: primary key is id, and name is column of no primary key, result is same as below:
 test-1-118.raipeng.com :) select distinct name from test_all a global join credit_ga.test_all_2 b on a.name=b.name order by name
SELECT DISTINCT name
FROM test_all AS a
GLOBAL INNER JOIN credit_ga.test_all_2 AS b ON a.name = b.name
ORDER BY name ASC
┌─name─┐
│ 1    │
└──────┘
┌─name─┐
│ 2    │
└──────┘
┌─name─┐
│ 3    │
└──────┘
┌─name─┐
│ 4    │
│ 5    │
│ 7    │
│ 8    │
│ 9    │
└──────┘
8 rows in set. Elapsed: 0.026 sec. 

test-1-118.raipeng.com :) select distinct name from test_all a join credit_ga.test_all_2 b on a.name=b.name order by name

SELECT DISTINCT name
FROM test_all AS a
INNER JOIN credit_ga.test_all_2 AS b ON a.name = b.name
ORDER BY name ASC

┌─name─┐
│ 1    │
└──────┘
┌─name─┐
│ 2    │
└──────┘
┌─name─┐
│ 3    │
└──────┘
┌─name─┐
│ 4    │
│ 5    │
│ 7    │
│ 8    │
│ 9    │
└──────┘
8 rows in set. Elapsed: 0.027 sec. 
```

**Comment by den-crane** [comment]
JOINs and primary keys are not related. CH does not use indexes or keys for joins. There is no restrictions which columns can be used.

```sql
1)
SELECT DISTINCT name
FROM test_all AS a
GLOBAL INNER JOIN credit_ga.test_all_2 AS b ON a.name = b.name
ORDER BY name ASC

2)
SELECT DISTINCT name
FROM test_all AS a
INNER JOIN credit_ga.test_all_2 AS b ON a.name = b.name
ORDER BY name ASC

```

Both queries are valid and useful and should provide the same result.
SQL1 executes at an initiator `SELECT credit_ga.test_all_2 AS b` into temporary table. Propagates this temporary table to shard of the table `test_all AS a`. Shards do join with this temporary table. Table  `credit_ga.test_all_2` is read 1 time.
SQL2 executes double-distributed join. Each shard of table `test_all AS a` selects data from `credit_ga.test_all_2 AS b` and do join. Table `credit_ga.test_all_2 AS b` is read by each shard.
