### ISSUE TITLE
capability: warning: `clickhouse-serv' uses 32-bit capabilities (legacy support in use)

### ISSUE THREAD

**Issue by socketpair** [ClickHouse/ClickHouse#15928]
https://github.com/ClickHouse/ClickHouse/blob/74edcfb87ef79f9c61d5829a9e9db665e5d0bce1/src/Common/hasLinuxCapability.cpp#L28

See also: 
https://kb.isc.org/docs/aa-00823 :

`not using libcap at all, or that it is using the 32-bit libcap library. It is the libcap2 package that provides full 64-bit support`

So, seems CH has reinvented the wheel.

Meanwhile, I don't see any reasons to use `syscall()`. man capget:

```
CAPGET(2)                                                               Linux Programmer's Manual                                                              CAPGET(2)

NAME
       capget, capset - set/get capabilities of thread(s)

SYNOPSIS
       #include <sys/capability.h>

       int capget(cap_user_header_t hdrp, cap_user_data_t datap);

       int capset(cap_user_header_t hdrp, const cap_user_data_t datap);
```

Even Centos 6 uses 2.4.32 (> 2.4.26) so It's time to drop support for very old systems.

**Comment by socketpair** [comment]
And also, I don't see any reasons not to include libcap as a git submodule.

**Comment by ivanprostran** [comment]
> > I don't see any reasons not to include libcap as a git submodule.
> 
> It has GPL license.
> 
> > capget, capset - set/get capabilities of thread(s)
> 
> It depends on new `glibc` version.
> 
> > Even Centos 6 uses 2.4.32
> 
> We support Centos 5.

Hi Alexey, please could you be more specific about "We support Centos 5"?
What exactly do you mean by this.
Thank you for you effort and time.

**Comment by alexey-milovidov** [comment]
@ivanprostran You can install and use ClickHouse on CentOS 5.
It can be installed from tgz, rpm or from binary.

**Comment by ivanprostran** [comment]
> @ivanprostran You can install and use ClickHouse on CentOS 5.
> It can be installed from tgz, rpm or from binary (`chmod a+x clickhouse && sudo ./clickhouse install`).

We installed it on Centos7 x86_64.

Are you suggesting it is not a supported platform?

Thank you for the quick response.

Regards,
Ivan

**Comment by alexey-milovidov** [comment]
CentOS 5 is the minimal supported version,
Centos 7 is supported as well and is way better.

**Comment by ivanprostran** [comment]
> CentOS 5 is the minimal supported version,
> Centos 7 is supported as well and is way better.

Of course.

Thank you.

Regards,
Ivan

**Comment by let4be** [comment]
does it mean I cannot properly run clickhouse in docker?
I see the warning as well, what exactly does it mean?

**Comment by socketpair** [comment]
No, You can. The message from the Linux Kernel means that CH uses an ancient API, although it still works.

**Comment by amosbird** [comment]
I guess we can somehow fix this thanks to Hemetic Build?

**Comment by socketpair** [comment]
I would drop Centos 5 support.

**Comment by alexey-milovidov** [comment]
We can check for Linux kernel version and if it has support for new capabilities, use it.
