### ISSUE TITLE
missing documentation for Merge Tree Settings in english

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#15929]
**Describe the issue**
Clickhouse has a lot of settings which can be applied to certain MergeTree tables or globally, but we don't have information about them in docs and we can't even search by their existence in docs. [Couple](https://clickhouse.tech/docs/en/operations/settings/settings/#ttl_only_drop_parts) of those settings are being described in the global settings section of docs.
We can use ```SELECT * FROM system.merge_tree_settings;```, but it requires us to have an opened connection for clickhouse.

**Additional context**
It exists in russian docs, however it's not complete.

**Comment by den-crane** [comment]
I am working on it. I have it half-ready. Try to finish ASAP.

**Comment by UnamedRus** [comment]
Fixed with https://github.com/ClickHouse/ClickHouse/pull/19221
