### ISSUE TITLE
Can Clickhouse import GZ format text files？

### ISSUE THREAD

**Issue by trollhe** [ClickHouse/ClickHouse#15952]
Can Clickhouse import text files in the format of. GZ,. Snappy, etc?

filename: **xxxx.gz**
cotent:
```
aaa|bbb|ccc|ddd
```

**Comment by Sasasu** [comment]
you can use `zcat` and unix pipe to do this
```shell
zcat xxx.gz | clickhouse-client --format_csv_delimiter="|" --query="INSERT INTO xxx FORMAT CSV"
```

**Comment by trollhe** [comment]
> you can use `zcat` and unix pipe to do this
> 
> ```shell
> zcat xxx.gz | clickhouse-client --format_csv_delimiter="|" --query="INSERT INTO xxx FORMAT CSV"
> ```

thanks sasasu, I want to see if there is direct support for GZ。Because there are massive GZ files to process。

**Comment by den-crane** [comment]
it can be done using http

```
create table ttest(A DateTime, B String) engine=Memory;

echo '0000000011|"dsd"'|gzip -c| curl -sS --data-binary @- -H 'Content-Encoding: gzip' 'http://localhost:8123/?format_csv_delimiter=|&query=insert+into+ttest+format+CSV'


select * from ttest

┌───────────────────A─┬─B───┐
│ 1970-01-01 00:00:11 │ dsd │
└─────────────────────┴─────┘

echo  '0000000011|"dsd"' | gzip > x.csv.gz
curl -sS --data-binary @x.csv.gz -H 'Content-Encoding: gzip' 'http://localhost:8123/?format_csv_delimiter=|&query=insert+into+ttest+format+CSV'
```

**Comment by filimonov** [comment]
AFAIR it also possible file `SELECT * FROM file()` when filename extension is gz.

**Comment by trollhe** [comment]
> it can be done using http
> 
> ```
> create table ttest(A DateTime, B String) engine=Memory;
> 
> echo '0000000011|"dsd"'|gzip -c| curl -sS --data-binary @- -H 'Content-Encoding: gzip' 'http://localhost:8123/?format_csv_delimiter=|&query=insert+into+ttest+format+CSV'
> 
> 
> select * from ttest
> 
> ┌───────────────────A─┬─B───┐
> │ 1970-01-01 00:00:11 │ dsd │
> └─────────────────────┴─────┘
> 
> echo  '0000000011|"dsd"' | gzip > x.csv.gz
> curl -sS --data-binary @x.csv.gz -H 'Content-Encoding: gzip' 'http://localhost:8123/?format_csv_delimiter=|&query=insert+into+ttest+format+CSV'
> ```

thanks den-crane,That's great.

**Comment by trollhe** [comment]
> AFAIR it also possible with `SELECT * FROM file()` when filename extension is gz.

thanks filimonov.
      do you mean: create file engine table -> select table?

**Comment by den-crane** [comment]
@trollhe file -- function. No need to create a table.

https://clickhouse.tech/docs/en/sql-reference/table-functions/file/

**Comment by trollhe** [comment]
> @trollhe file -- function. No need to create a table.
> 
> https://clickhouse.tech/docs/en/sql-reference/table-functions/file/
> 
> And I think you can use wildcards for a file name `*.csv.gz`
> 
> ```
> SELECT *
> FROM file('*.csv.gz', 'CSV', 'column1 UInt32, column2 UInt32, column3 UInt32')
> LIMIT 2
> ```

ok, Thanks :)
