### ISSUE TITLE
clickhouse integrations hdfs csv file

### ISSUE THREAD

**Issue by trollhe** [ClickHouse/ClickHouse#15959]
Hello,How to create a CSV table split by '|'？

hdfs file content
```
ssss|aaaa|pppp|
```

clickhouse create table:
```
create table xxx.xxxx
(
...
)
ENGINE = HDFS('hdfs://xxx:9000/ext/ntbcp/*', 'CSV');
```

**how to setting format_csv_delimiter '|' ?????**

**Comment by den-crane** [comment]
try to set format_csv_delimiter in default profile.
```
cat /etc/clickhouse-server/conf.d/z_user_substitutes.xml
<?xml version="1.0"?>
<yandex>
    <profiles>
        <default>
		<format_csv_delimiter>|</format_csv_delimiter>
        </default>
    </profiles>
</yandex>
```

**Comment by alexey-milovidov** [comment]
We should allow all format settings in File/URL/HDFS/S3 engines.
Also we should respect query-level settings when table function is queried.

**Comment by trollhe** [comment]
> try to set format_csv_delimiter in default profile.
> 
> ```
> cat /etc/clickhouse-server/conf.d/z_user_substitutes.xml
> <?xml version="1.0"?>
> <yandex>
>     <profiles>
>         <default>
> 		<format_csv_delimiter>|</format_csv_delimiter>
>         </default>
>     </profiles>
> </yandex>
> ```

thanks den-crane, Can the field separator be set for a specific table?

**Comment by trollhe** [comment]
> We should allow all format settings in File/URL/HDFS/S3 engines.
> Also we should respect query-level settings when table function is queried.

yes,it`s support hdfs engine.
