### ISSUE TITLE
Table join and subquery join in distribute table engine

### ISSUE THREAD

**Issue by chang0391** [ClickHouse/ClickHouse#15956]
Version:20.9.3.45
I executed two tables with distribute table engine to join.
First time, I executed two tables to join, and got the issue "Memory limit (for query) exceeded"
Second time, I executed two subqueries instand of tables to join, and got the correct result.
Can you explain? Whether the join between tables with distribute table engine must be replaced by subquery. 

Testing as blow:
1) table join
nsj-op-mysql2-205-064 :) select count(1) from rp_credit_sms_cmcc a  global join credit_ga.rp_credit_sms_cucc b on a.id=b.id
SELECT count(1)
FROM rp_credit_sms_cmcc AS a
GLOBAL INNER JOIN credit_ga.rp_credit_sms_cucc AS b ON a.id = b.id
→ Progress: 30.67 million rows, 10.53 GB (9.50 million rows/s., 3.26 GB/s.) ███████████████████▋                                                 28%
Received exception from server (version 20.5.4):
Code: 241. DB::Exception: Received from localhost:9000. DB::Exception: Memory limit (for query) exceeded: would use 19.54 GiB (attempt to allocate chunk of 4223840 bytes), maximum: 19.54 GiB: (while reading column template_id): (while reading from part /data/clickhouse/data/credit_ga/rp_credit_sms_cucc_l/20201001_176_176_0/ from mark 0 with max_rows_to_read = 8192): While executing MergeTreeThread: While executing CreatingSetsTransform. 
0 rows in set. Elapsed: 3.242 sec. Processed 30.67 million rows, 10.53 GB (9.46 million rows/s., 3.25 GB/s.) 

2)subquery join
nsj-op-mysql2-205-064 :) select count(1) from (select id from rp_credit_sms_cmcc) a  global join (select id from credit_ga.rp_credit_sms_cucc) b on a.id=b.id

SELECT count(1)
FROM 
(
    SELECT id
    FROM rp_credit_sms_cmcc
) AS a
GLOBAL INNER JOIN 
(
    SELECT id
    FROM credit_ga.rp_credit_sms_cucc
) AS b ON a.id = b.id

┌─count(1)─┐
│ 91683545 │
└──────────┘
1 rows in set. Elapsed: 22.078 sec. Processed 255.81 million rows, 2.05 GB (11.59 million rows/s., 92.70 MB/s.)

**Comment by den-crane** [comment]
>Version:20.9.3.45
>...
>Received exception from server (version 20.5.4):

It seems you have multiple servers with different versions. Try to upgrade all server to 20.9.3.45

>select count(1) from rp_credit_sms_cmcc a 
>   global join credit_ga.rp_credit_sms_cucc b on a.id=b.id

The first query is executed JOIN **at shards** and the shard with version 20.5.4 failed because of lack of memory.
Each shard of `rp_credit_sms_cmcc a` did join at itself.

>SELECT count(1) FROM (SELECT id FROM rp_credit_sms_cmcc) AS a 
>   GLOBAL INNER JOIN
>   ( SELECT id FROM credit_ga.rp_credit_sms_cucc ) AS b ON a.id = b.id

The second query is executed JOIN **at an initiator**. 
Because **of brackets ( )**  (SELECT id FROM rp_credit_sms_cmcc) AS a

**Comment by chang0391** [comment]
@den-crane
    Why is there not enough memory in shard join for first query,
     but memory is enough for subquery join at second query.
    Does it mean that subquery join need less memory?

**Comment by den-crane** [comment]
It seems you have multiple servers with different versions. Try to upgrade all servers to 20.9.3.45

The first query is executed JOIN at shards **and the shard with version 20.5.4 failed because of lack of memory**.
Each shard of rp_credit_sms_cmcc a did join at itself.
