### ISSUE TITLE
MySQL 5.7 Enhanced Multi-Threaded Slave cause .metadata growing rapidly

### ISSUE THREAD

**Issue by liangli1213** [ClickHouse/ClickHouse#15951]
I found MySQL slave has much delay so I enabled Enhanced Multi-Threaded Slave on MySQL slave, then I found the .metadata in each Clichouse DB growing rapidly, content is as below:

```
[root@bdc-clickhouse license_monitor]# cat .metadata
Version:        2
Binlog File:    mysql-bin.000040
Executed GTID:  110a53f9-de98-11e9-bf81-00505696d56b:1-79418278,8ff4fda6-df42-11e9
be2a-0050569687c9:1-545403746:545403747-545403749:545403750-545403752:545403753-545403758:545403759-545403761
545403762-545403764:545403765-545403767:545403768-545403770:545403771-545403773:545403774-545403790:54540379
-545403797:545403798-545403803:545403804-545403813:545403814-545403819:545403820-545403831:545403832-5454038
0:545403841-545403844:545403845-545403852:545403853-545403858:545403859-545403875:545403876-545403882:5454038
3-545403888:545403889:545403890-545403902:545403903:545403904-545403926:545403927-545403947:545403948-5454039
2:545403983-545403992:545403993-545403997:545403998-545404002:545404003-545404009:545404010-545404028:5454040
9-545404068:545404069-545404086:545404087-545404105:545404106-545404132:545404133-545404148:545404149-545404
06:545404207-545404232:545404233-545404263:545404264-545404298:545404299-545404302:545404303-545404370:545404
71-545404379:545404380-545404393:545404394-545404401:545404402-545404427:545404428-545404432:545404433-54540
437:545404438-545404447:545404448-545404487:545404488-545404494:545404495-545404597:545404598-545404635:54540
636:545404637-545404647:545404648-545404654:545404655:545404656-545404676:545404677-545404687:545404688-54540
701:545404702:545404703-545404707:545404708-545404713:545404714-545404771:545404772-545404779:545404780-54540
7
```

**Comment by liangli1213** [comment]
@BohuTANG @zhang2014

**Comment by BohuTANG** [comment]
Hi,

what the  MySQL `show master status` output?

**Comment by liangli1213** [comment]
@BohuTANG , I forgot to paste the setting I add into my.cnf:

```
# Enable Enhanced Multi-Threaded Slave
slave-parallel-type = LOGICAL_CLOCK
slave-parallel-workers = 16
master_info_repository = TABLE
relay_log_info_repository = TABLE
relay_log_recovery = ON
```
The topology is as below, I think the issue is caused by multi-thread slave, when they fetch events from relay log and replay, and write to bin-log on Slave, it is not strictly follow the GTID sequence.

`MySQL Master -> MySQL Slave -> ClickHouse`

While running 'show slave status', sometimes I can observer like: <UUID>:1-1000:1002, but after a while, it will turn to normal, like <UUID>:1-1002, it seems MySQL has the ability to aggragrate and reorganize the sequencial GTID.

**Comment by BohuTANG** [comment]
It seems like a GTID Sets shrinking issue, we will try to fix it.

**Comment by liangli1213** [comment]
@BohuTANG , have you began to fix it?

**Comment by BohuTANG** [comment]
> @BohuTANG , have you began to fix it?

It's already in our queue.
It should start when this https://github.com/ClickHouse/ClickHouse/pull/15977 is over.

**Comment by liangli1213** [comment]
Noted, thanks very much.

**Comment by TCeason** [comment]
The pr is merged, long time waiting, bro. @liangli1213  If anything goes wrong with your test, @me.

**Comment by liangli1213** [comment]
@TCeason , thanks very much, let me have a try, then back to you.

**Comment by liangli1213** [comment]
The issue has been resolved.
