### ISSUE TITLE
Rest of the cluster is locked up when one node is goes down

### ISSUE THREAD

**Issue by sovietotaku** [ClickHouse/ClickHouse#15966]
Good day.
I experienceng unwanted behaviour with clickhouse cluster.
The problem is when one node is going down - the rest of the cluster is locked up so no writing into the tables is possible
Is it made by design or can be fixed?
One detail: zookeeper is installed onto the same hosts where clickhouse is.

**Comment by nikitamikhaylov** [comment]
Which version of ClickHouse do you use? Is it locked up forever or for a period of time? Do your queries hung or return an error?

**Comment by sovietotaku** [comment]
> Which version of ClickHouse do you use? Is it locked up forever or for a period of time? Do your queries hung or return an error?

It's the latest clichhouse from official repo. Tables are becoming read-only, but if the node that was go down returns up - entire system is unlocking. It was returning an error, but I cannot find it in logs...

**Comment by sovietotaku** [comment]
Nope, it did not helped. Got this code:
Code: 999. DB::Exception: Received from localhost:9000. DB::Exception: Session expired (Session expired).

So, my config now is two Clickhouse nodes and 3 zookeeper nodes. Is it right? Or i need 3 Clickhouse nodes and 3 Zookeeper nodes?

**Comment by den-crane** [comment]
2 CH + 3 zookeeper nodes is right.

>Nope, it did not helped. Got this code:

Show full logs.
You can experience "Session expired (Session expired)." for a short time (several seconds) while CH reconnects to another ZK node.

**Comment by sovietotaku** [comment]
>3 zookeeper nodes is right
Yep, it is. And number of zk nodes should be: n+1, where "1" will be "eyewitness". Or just odd cont with full working nodes.
I solved all of my issues and failover works now just I need.
Last problem was just missconfig (forgot to add third server in <zookeeper> section of Click's config file)
