### ISSUE TITLE
 Circular query hangs with Log table engine [20.3-20.8] 

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#15997]
**How to reproduce**
Clickhouse server version 20.3.12, 20.3.19, 20.8.4
In clickhouse-server 20.9.3.45 the issue doesn't reproduce.
```
CREATE TABLE circular_test
(
    `id` String,
    `value` UInt8
)
ENGINE = Log();
INSERT INTO circular_test VALUES ('123',1), ('234',2), ('345',3);
CREATE TABLE circular_test_2
(
    `id` String,
    `value` UInt8
)
ENGINE = Log();
INSERT INTO circular_test_2 VALUES ('123',1), ('234',2), ('345',3), ('456',4), ('567',5);
INSERT INTO circular_test SELECT *
FROM circular_test_2
WHERE id NOT IN
(
    SELECT id
    FROM circular_test
);
```

**Expected behavior**
Query completion, just like with Memory or MergeTree table engine.

**Additional context**
An example works well with Memory or MergeTree tables.
KILL QUERY doesn't work well and just puts the query in a waiting state, clickhouse-server restart works.

**Comment by filimonov** [comment]
Related #16812

**Comment by alexey-milovidov** [comment]
Fixed in master.
