### ISSUE TITLE
define Decimal128 type fields with two arguments returns wrong message

### ISSUE THREAD

**Issue by l1t1** [ClickHouse/ClickHouse#15996]
if i set the scale value, it failed, it is right, as mentioned at https://clickhouse.tech/docs/en/sql-reference/data-types/decimal/
but say Decimal data type family must have exactly two arguments: precision and scale.
```sql
CREATE TABLE sfz3
(
    `code` Decimal128(38, 0)
)
ENGINE = MergeTree()
ORDER BY code

Received exception from server (version 20.9.2):
Code: 42. DB::Exception: Received from localhost:9000. DB::Exception: Decimal data type family must have exactly two arguments: precision and scale.

0 rows in set. Elapsed: 0.007 sec.

create table sfz3(code Decimal128(38))ENGINE = MergeTree()order by code;

CREATE TABLE sfz3
(
    `code` Decimal128(38)
)
ENGINE = MergeTree()
ORDER BY code

Ok.

0 rows in set. Elapsed: 0.040 sec.
```

(you don't have to strictly follow this form)

**Describe the bug**
A clear and concise description of what works not as it is supposed to.

**How to reproduce**
* Which ClickHouse server version to use
* Which interface to use, if matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

**Expected behavior**

**Error message and/or stacktrace**

**Additional context**

**Comment by l1t1** [comment]
and try to convert Int128 to Decimal(38) failed too
```
INSERT INTO sfz3 SELECT *
FROM sfz2


Received exception from server (version 20.9.2):
Code: 70. DB::Exception: Received from localhost:9000. DB::Exception: Conversion from Int128 to Decimal(38, 38) is not supported: while converting source column code to destination column code.

INSERT INTO sfz3 SELECT toDecimal128(code, 38)
FROM sfz2


Received exception from server (version 20.9.2):
Code: 407. DB::Exception: Received from localhost:9000. DB::Exception: Decimal convert overflow.
```

**Comment by den-crane** [comment]
`code` Decimal128(38, 0) -- is incorrect. 
You should use `Decimal(38, 0)` or `Decimal128(0)`

>INSERT INTO sfz3 SELECT *
>FROM sfz2

`desc sfz2` ?

**Comment by den-crane** [comment]
>INSERT INTO sfz3 SELECT *
>FROM sfz2
>Received exception from server (version 20.9.2):
>Code: 70. DB::Exception: Received from localhost:9000. DB::Exception: Conversion from Int128 to Decimal(38, 0) is not >supported: while converting source column code to destination column code.
>
>INSERT INTO sfz3 SELECT toDecimal128(code, 0) FROM sfz2
>Ok.

It's the expected behavior. No automatic type cast.

**Comment by l1t1** [comment]
note:
when input`code` **Decimal128(38, 0)**, the error msg Decimal data type family must have **exactly two arguments: precision and scale.** is confusing, it should reply as yours
**code Decimal128(38, 0) -- is incorrect. You should use Decimal(38, 0) or Decimal128(0)**
