### ISSUE TITLE
Problem on RBAC

### ISSUE THREAD

**Issue by spihiker** [ClickHouse/ClickHouse#15994]
version:20.8.4.11

(1) 2 roles:
SHOW GRANTS FOR devgroup

┌─GRANTS FOR devgroup─────────────────────────────────────────────────┐
│ GRANT SELECT, INSERT, ALTER UPDATE, ALTER DELETE ON chdb.* TO devgroup
└──────────────────────────────────────────────────────── ────────┘

SHOW GRANTS FOR group_com

┌─GRANTS FOR group_com──────────────────────────────────────┐
│ GRANT CREATE TEMPORARY TABLE, SOURCES ON *.* TO group_com 
└───────────────────────────────────────────────────── ─┘

(2)1 user
SHOW GRANTS FOR webuser

┌─GRANTS FOR webuser────────────────────────┐
│ GRANT devgroup, group_com TO webuser 
└───────────────────────────────────────┘

(3)Error message:
 SELECT user()

┌─user()──┐
│ webuser 
└────── ┘  
SELECT *
FROM mysql('192.168.1.127:3306', 'mydb', 't1', 'dba', 'dba')

Received exception from server (version 20.8.4):
Code: 497. DB::Exception: Received from 192.168.1.221:9999. DB::Exception: webuser: Not enough privileges. To execute this query it's necessary to have the grant CREATE TEMPORARY TABLE, MYSQL ON *.*.

Thanks for your help.

**Comment by vitlibar** [comment]
Probably the role `group_com` was not current for `webuser`. You can check the current roles with the command `SHOW CURRENT ROLES` and see if the list of the current roles includes `group_com`.

**Comment by spihiker** [comment]
After I executed the command SET DEFAULT ROLE...TO ... ,The user has enough privileges as i expected. But when i executed the command SHOW CURRENT ROLES ,the list has nothing.Why?

jyw-test-221 :) set default role devgroup_3399,group_com to webuser;

SET DEFAULT ROLE devgroup_3399, group_com TO webuser

Ok.

0 rows in set. Elapsed: 0.003 sec. 

jyw-test-221 :) SHOW CURRENT ROLES;

SHOW CURRENT ROLES

Ok.

0 rows in set. Elapsed: 0.001 sec. 

    Thank you .

**Comment by spihiker** [comment]
Update to version(20.8.5.45) ,It's ok.
