### ISSUE TITLE
Support Thrift or MsgPack formats

### ISSUE THREAD

**Issue by tacyuuhon** [ClickHouse/ClickHouse#1604]
I use Thrift to compress data in Kafka to save disk space.
Kafka Engine in the future is there a plan to support Thrift or MsgPack?

**Comment by ztlpn** [comment]
Formats support is independent of the Kafka engine. The list is available at https://clickhouse.yandex/docs/en/formats/index.html. Also recently support for the Cap'n proto format was added and there is work under way to support parquet and protobuf. There are no definite plans for the support of thrift or msgpack although they should be straightforward to add (probably a good entry task for someone willing to contribute to ClickHouse).

**Comment by tacyuuhon** [comment]
I already know. Thank you very much.

**Comment by alexey-milovidov** [comment]
@Avogar

**Comment by Avogar** [comment]
@tacyuuhon. Hello, I have a question about Thrift. How do you use it in Kafka and what did you mean by "support Thrift"? Msgpack is a specific data storage format, but Thrift is not. (I could be wrong, correct me please).

**Comment by filimonov** [comment]
I think it is about that 
https://github.com/apache/thrift/blob/master/lib/java/src/org/apache/thrift/TSerializer.java

https://stackoverflow.com/questions/12328896/thrift-is-it-possible-to-do-only-serialization-with-c-thrift-library

https://www.programcreek.com/java-api-examples/?api=org.apache.thrift.TSerializer

**Comment by alexey-milovidov** [comment]
As `MsgPack` format was merged to master, this issue is fixed.

**Comment by filimonov** [comment]
> As MsgPack format was merged to master, this issue is fixed.

:+1: 

If somebody will need Thrift, he should open a separate issue with motivation and it can be linked to this one. 

https://github.com/ClickHouse/ClickHouse/labels/comp-formats
