### ISSUE TITLE
UInt256 is  not supported

### ISSUE THREAD

**Issue by zcw5116** [ClickHouse/ClickHouse#16050]
(you don't have to strictly follow this form)

**Describe the issue**
ClickHouse Document: https://clickhouse.tech/docs/en/sql-reference/data-types/int-uint/
Fixed-length integers, Support UInt256, However, an error was reported when executing the following create table statement:

> CREATE TABLE ttt
(
    `id` UInt256
)
ENGINE = Log

Received exception from server (version 20.1.4):
Code: 50. DB::Exception: Received from localhost:9001. DB::Exception: Unknown data type family: UInt256. Maybe you meant: ['UInt16','Int16'].

ClickHouse Version: version 20.1.4.14

Thanks very much.

**Comment by l1t1** [comment]
you need a higher version and set  allow_experimental_bigint_types .
```sql
CREATE TABLE ttt
(
    `id` UInt256
)
ENGINE = Log


Received exception from server (version 20.9.2):
Code: 44. DB::Exception: Received from localhost:9000. DB::Exception: Cannot create table with column 'id' which type is 'UInt256' because experimental bigint types are not allowed. Set 'allow_experimental_bigint_types' setting to enable..

0 rows in set. Elapsed: 0.024 sec.

SET allow_experimental_bigint_types = 1

Ok.

0 rows in set. Elapsed: 0.018 sec.

CREATE TABLE ttt
(
    `id` UInt256
)
ENGINE = Log

Ok.

0 rows in set. Elapsed: 0.028 sec.
```

**Comment by den-crane** [comment]
https://github.com/ClickHouse/ClickHouse/blob/master/CHANGELOG.md#experimental-feature-1

you need CH version 20.8+
