### ISSUE TITLE
Missing column data when use kafka engine and insert nested json data by MATERIALIZED VIEW 

### ISSUE THREAD

**Issue by gaoyang-projects** [ClickHouse/ClickHouse#16064]
**Describe the bug**
Missing column data when use kafka engine and insert nested json data by MATERIALIZED VIEW
https://clickhouse.tech/docs/en/engines/table-engines/integrations/kafka/#table_engine-kafka-creating-a-table

**How to reproduce**
* Create a kafka engine queue table
* Create a destination table same structure with kafka queue table
* INSERT DATA USE NATIVE SQL
* QUERY destination [OK]
* Create a materialized view 
* QUERY destination [MISSING NESTED JSON DATA]

kafka message structure
```
{ "id": "20008a76d5f46747", "localEndpoint": { "serviceName": "marketing" }, "timestamp": 1600362050763009 }
```
reproduce sql scripts
```
-- create a kafka engine queue table
CREATE TABLE IF NOT EXISTS kafka_queue  (
    timestamp UInt64,
    id Nullable(String),
    `localEndpoint.serviceName` Nullable(String)
  )  ENGINE = Kafka SETTINGS kafka_broker_list = '',
                            kafka_topic_list = '',
                            kafka_group_name = 'ch-group-1',
                            kafka_format = 'JSONEachRow',
                            kafka_num_consumers = 1,
                            kafka_thread_per_consumer = 1,
                            kafka_max_block_size = 1048576;
-- Create a destination table same structure with kafka queue table.
CREATE TABLE IF NOT EXISTS kafka_queue_daily (
    timestamp UInt64,
    id Nullable(String),
    `localEndpoint_serviceName` Nullable(String)
  ) ENGINE = Memory;
-- INSERT DATA USE NATIVE SQL
INSERT INTO kafka_queue_daily  SELECT * FROM kafka_queue limit 10
-- QUERY destination table
SELECT * FROM kafka_queue_daily limit 1000
-- Create a materialized view 
CREATE MATERIALIZED VIEW kafka_queue_consumer TO pupu_monitor.kafka_queue_daily AS SELECT * FROM kafka_queue 
-- QUERY destination table
SELECT * FROM kafka_queue_daily limit 1000
-- clean
DROP TABLE IF EXISTS kafka_queue;
DROP TABLE IF EXISTS kafka_queue_daily;
DROP TABLE IF EXISTS kafka_queue_consumer;
```
![image](https://user-images.githubusercontent.com/6829668/96236024-17171380-0fce-11eb-9308-9f94bcc49ed7.png)
![image](https://user-images.githubusercontent.com/6829668/96238493-1e8bec00-0fd1-11eb-9ccc-1bd40cc94083.png)
![image](https://user-images.githubusercontent.com/6829668/96238550-33687f80-0fd1-11eb-9055-fd49dbc00db6.png)

JDBC Case
```
public class ClickHouseInsertIntoExample {

    public static void main(String[] args) throws Exception {
        String driverClass = "ru.yandex.clickhouse.ClickHouseDriver";
        Class.forName(driverClass);
        String url = "jdbc:clickhouse://192.168.3.190:8123/pupu_monitor";
        String username = "default";
        String password = "";
        String sql = "INSERT INTO kafka_queue_daily SELECT * FROM kafka_queue limit 10";
        Connection connection = DriverManager.getConnection(url, username, password);
        PreparedStatement ps = connection.prepareStatement(sql);
        int affected = ps.executeUpdate();
        ps.close();
        connection.close();
        System.out.println(affected);
    }

}
```
**Expected behavior**
only insert data use native sql in Tabix is ok
MATERIALIZED VIEW or JDBC will miss column data

**Additional context**

`SELECT version( )`
20.9.3.45

`select * from system.settings where changed`
max_block_size	1048576
use_uncompressed_cache	0
load_balancing	random
add_http_cors_header	1
max_result_rows	5000
max_execution_time	5
max_memory_usage	10000000000
input_format_skip_unknown_fields	1
input_format_import_nested_json	1
output_format_json_quote_denormals	1

**Comment by filimonov** [comment]
1) clickhouse version? 
2) `select * from system.settings where changed`

**Comment by gaoyang-projects** [comment]
> 1. clickhouse version?
> 2. `select * from system.settings where changed`
> 3. kafka message structure - please provide / dump "as is" - i see you use JSONEachRow, but the sample you show is multiline.

1-2. updated to Additional context
3. kafka message structure is pretty print for human to read, in fact each message is a json row

**Comment by filimonov** [comment]
Add  `input_format_import_nested_json` to your Kafka table settings. 

```diff
CREATE TABLE IF NOT EXISTS kafka_queue  (
    timestamp UInt64,
    id Nullable(String),
    `localEndpoint.serviceName` Nullable(String)
  )  ENGINE = Kafka SETTINGS kafka_broker_list = '',
                            kafka_topic_list = '',
                            kafka_group_name = 'ch-group-1',
                            kafka_format = 'JSONEachRow',
                            kafka_num_consumers = 1,
                            kafka_thread_per_consumer = 1,
                            kafka_max_block_size = 1048576, 
+                           input_format_import_nested_json=1;
```

BTW:  `max_block_size=1048576` is usually a bad idea, and may lead to suboptimal performance. Keep it default.

**Comment by gaoyang-projects** [comment]
**kafka_max_block_size = 1048576** from https://altinity.com/blog/clickhouse-kafka-engine-faq posted at 04 May 2020
`input_format_import_nested_json=1` already changed in system.settings and it's works.
bug is use same SQL
`INSERT INTO [table]  SELECT * FROM ...` is ok
`CREATE MATERIALIZED VIEW ...` miss column data

**Comment by filimonov** [comment]
> kafka_max_block_size = 1048576 from https://altinity.com/blog/clickhouse-kafka-engine-faq

Yes, and that's ok.

But you have: 
```
select * from system.settings where changed
max_block_size 1048576
```

That was never recommended, and I was referring that.

>  input_format_import_nested_json=1 already changed in system.settings and it's works . 

How exactly did you change that? Can you change it in default profile and restart the clickhouse-server?
