### ISSUE TITLE
How do I import the aggregate results of one table (very large data) into another?

### ISSUE THREAD

**Issue by qinglok** [ClickHouse/ClickHouse#16065]
CH viewsion：20.8.2.3

Now the plan :
    `INSERT INTO table_1
     SELECT ...
     FROM table_2
     GROUP BY ...`
Due to the large amount of data, this scheme can not be successfully implemented.

**Comment by filimonov** [comment]
>  this scheme can not be successfully implemented

what do you mean? 

For large insert ... select you may want to adjust several settings:

```
set
   max_insert_threads=4, /* flush to target table in parallel */ 
   max_threads=4,  /* don't use too many thread during select */
   min_insert_block_size_bytes = 536870912, /* combine smaller data blocks coming from select into larger */ 
   min_insert_block_size_rows = 16777216     /* that way insert will create fewer parts, but each one will be quite big */,
   max_bytes_before_external_group_by = '8G' /* allow on disk group by if your group by don't fit into memory */;
```


After that - just do your:
````
INSERT INTO table_1 SELECT ... FROM table_2 GROUP BY ...
```

Or (bit better/cheaper) - do a lot of INSERT ... SELECT slicing data every time by some condition to pick single (or few) groups at once, or single (of few) partitions at once.

P.S. Those setting are quite aggresive, and suitable only for moving bigger amounts of data. So defaults have more 'convervative' values.

**Comment by qinglok** [comment]
`INSERT INTO table_1 SELECT ... FROM table_2 GROUP BY ...`
This SQL has two parts. 
My problem is that the results from the query section are too large for the memory capacity.
I'm going to try slicing way.

**Comment by den-crane** [comment]
If you insert into SummingMT / AggregatingMT Engines there are other ways. You can insert without groupby for example.
