### ISSUE TITLE
can not drop database of MysQL Engine when the MySQL database has stoped

### ISSUE THREAD

**Issue by imysm** [ClickHouse/ClickHouse#16073]
I create a database test with MySQL Engine.
when I stop the MySQL,I run "drop database test"  on clickhouse ，then :

sha175 :) drop database test;

DROP DATABASE test

Received exception from server (version 20.5.2):
Code: 1000. DB::Exception: Received from localhost:9000. DB::Exception: mysqlxx::ConnectionFailed: Can't connect to MySQL server on '101.10.10.75' (115) ((nullptr):0). 

0 rows in set. Elapsed: 0.001 sec. 

sha175 :)

**Comment by den-crane** [comment]
solution is here https://github.com/ClickHouse/ClickHouse/issues/6063#issuecomment-513620887

**Comment by den-crane** [comment]
fix https://github.com/ClickHouse/ClickHouse/pull/8202

Support DROP DATABASE, DETACH TABLE, DROP TABLE and ATTACH TABLE for MySQL database engine. #8202 (Winter Zhang)

you  need to upgrade CH to 20.7+
