### ISSUE TITLE
Add a format parameter to toDate function

### ISSUE THREAD

**Issue by shsab** [ClickHouse/ClickHouse#16085]
**Use case**
I have a table with Year and week of the year fields and would like to convert it to date. In python, I am using `datetime.strptime(f"20{row['calendar_year']}-{row['calendar_week']}-{week_start}", "%G-%V-%u")` which works fine but the toDate function here is not accepting the format string.

The week_start parameter accepts values 1 to 7. (ISO 8601 weekday as a number with Monday as 1 (1-7))

**Describe the solution you'd like**
Adding a format string to toDate function.

**Describe alternatives you've considered**
As of now, I have to do the conversion in Python using the code provided above. However, it is slow when the data is huge.

**Comment by den-crane** [comment]
https://clickhouse.tech/docs/en/sql-reference/functions/date-time-functions/#formatdatetime
```
select formatDateTime(today(), '%Y-%V-%u')
┌─formatDateTime(today(), '%Y-%V-%u')─┐
│ 2020-42-5                           │
└─────────────────────────────────────┘
```
