### ISSUE TITLE
Пустой результат при постраничных запросах со смещением

### ISSUE THREAD

**Issue by hayrullinmar** [ClickHouse/ClickHouse#16080]
Версия: ClickHouse server version 20.3.2.1 (official build).

Имеется таблица, созданная командой
```sql
create table session (
  start DateTime,
  stop Nullable(DateTime),
  vlan String,
  mac String,
  phone Nullable(String),
  ip Nullable(String),
  contract Nullable(String),
  octets_in Int64,
  octets_out Int64
) ENGINE MergeTree() PARTITION BY (toYYYYMM(start)) ORDER BY start
```

и набор данных для заполнения
[data.txt](https://github.com/ClickHouse/ClickHouse/files/5391478/data.txt)

**Не ожидаемое поведение**
При выполнении постраничных запросов со смещением **OFFSET, LIMIT** база возвращает пустой результат для некоторых промежуточных страниц, отсортированных в порядке убывания **DESC**.

**Как воспроизвести**
* Создать таблицу, заполнить данными из data.txt
* Сделать sql - запрос со смещением 60 и лимитом в 30 записей 

```sql
SELECT session.phone AS session_phone, session.start AS session_start, session.stop AS session_stop,
session.mac AS session_mac, session.vlan AS session_vlan
FROM session WHERE toDate(session.start) >= '2020-08-30'
AND toDate(session.start) <= '2020-08-30'
AND session.vlan IN ('2002:997')
ORDER BY session.start DESC LIMIT 60, 30 FORMAT TabSeparatedWithNamesAndTypes
```
ответ базы данных:
``` shell
session_phone	session_start	session_stop	session_mac	session_vlan
Nullable(String)	DateTime	Nullable(DateTime)	String	String
Ok.

0 rows in set. Elapsed: 0.006 sec. Processed 3.75 thousand rows, 273.82 KB (597.14 thousand rows/s., 43.59 MB/s.) 
```

При этом если установить ```LIMIT 30, 30```  или ```LIMIT 90, 30``` , то запрос отрабатывает корректно и данные возвращаются.

**Comment by den-crane** [comment]
КМК это исправлено очень давно. Вам нужно обновится до 20.3.20.6. 
20.3.20.6 это багфикс релиз, обновление довольно безопасно.
