### ISSUE TITLE
SELECT FROM system.tables should not go to ZooKeeper. SELECT count() FROM table neither.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#16108]
```
SELECT *
FROM system.tables
WHERE name LIKE '%trips%'


Received exception from server (version 20.10.1):
Code: 999. DB::Exception: Received from localhost:9000. DB::Exception: Session expired (Session expired): While executing Tables.
```

in `totalRows`, `getMaxAddedBlocks`.
due to processing of "quorum".

SELECT FROM system.tables should never go to ZooKeeper.
It can return slightly incorrect value in `rows` column.

`SELECT count() FROM table` should go to ZooKeeper and check quorum only if `select_sequential_consistency` is enabled.

Bottomline:
SELECT should never go to ZooKeeper unless user is "paying" for it by enabling `select_sequential_consistency`.

**Comment by alexey-milovidov** [comment]
I thought it's already fixed.

**Comment by amosbird** [comment]
> I thought it's already fixed.

It should.
