### ISSUE TITLE
Reading from S3

### ISSUE THREAD

**Issue by tooptoop4** [ClickHouse/ClickHouse#16114]
Can clickhouse query CSV/Parquet living directly on S3 without inserting it into a table first?

**Comment by Jokser** [comment]
Yes, you can use the S3 table function:
`select * from S3('https://s3_endpoint/bucket/file', 'CSV', 'table format')`

Btw, when you create a table with S3 engine it doesn't store any data on the local disk and you don't need to insert something into table first. It queries a data directly from S3.

**Comment by tooptoop4** [comment]
@Jokser @alexey-milovidov anything in the docs about it? or how to access parquet file from S3? also any idea how much slower these queries run that if the data were inserted onto local disk?
