### ISSUE TITLE
Table with Distributed engine join take so much time than mergetree engine

### ISSUE THREAD

**Issue by chang0391** [ClickHouse/ClickHouse#16131]
**Describe the bug**
 1)`rp_credit_sms_cmcc` is  table with Distributed engine,totally 161472025 rows
 2)`rp_credit_sms_cmcc_bak` is  table with mergetree engine,totally 161472025 rows
 3)`rp_credit_access_log` is  is  table with mergetree engine,totally 9027892 rows

 I executed `rp_credit_sms_cmcc global join rp_credit_access_log`, which spend 6.8s
 but,I executed `rp_credit_sms_cmcc_bak  join rp_credit_access_log`, which spend 1.9s
so, why does table with Distributed engine join spend so much time than mergetree engine

**How to reproduce**
1）table with Distributed engine join  table  of mergetree engine
```
nsj-op-shorturl2-205-062 :) select count(1) from (select * from rp_credit_sms_cmcc) a global join (select * from rp_credit_access_log ) b on a.id=b.sms_id
SELECT count(1)
FROM 
(
    SELECT *
    FROM rp_credit_sms_cmcc
) AS a
GLOBAL INNER JOIN 
(
    SELECT *
    FROM rp_credit_access_log
) AS b ON a.id = b.sms_id
┌─count(1)─┐
│  8611667 │
└──────────┘
1 rows in set. Elapsed: 6.816 sec. Processed 170.50 million rows, 1.37 GB (25.02 million rows/s., 201.45 MB/s.) 
```
2）table with mergetree engine join  table  of mergetree engine
```
nsj-op-shorturl2-205-062 :) select count(1) from (select * from rp_credit_sms_cmcc_bak) a global join (select * from rp_credit_access_log ) b on a.id=b.sms_id
SELECT count(1)
FROM 
(
    SELECT *
    FROM rp_credit_sms_cmcc_bak
) AS a
GLOBAL INNER JOIN 
(
    SELECT *
    FROM rp_credit_access_log
) AS b ON a.id = b.sms_id
┌─count(1)─┐
│  8611667 │
└──────────┘
1 rows in set. Elapsed: 1.930 sec. Processed 170.50 million rows, 1.37 GB (88.36 million rows/s., 711.55 MB/s.) 
```

**Comment by filimonov** [comment]
That is expected:

> When using GLOBAL ... JOIN, first the requestor server runs a subquery to calculate the right table. This temporary table is passed to each remote server, and queries are run on them using the temporary data that was transmitted.

See https://clickhouse.tech/docs/en/sql-reference/statements/select/join/#global-join

That part 'passed to each remote server' is the most possible reason.

**Comment by den-crane** [comment]
@chang0391 CH version ?

**Comment by chang0391** [comment]
@den-crane
     version：20.5.4

**Comment by abyss7** [comment]
You should provide at least your cluster configuration and the logs from all the shards with a part corresponding to your query execution - it would help to better analyze and understand timings.

Also, as mentioned earlier, the `global` join for local MergeTree is the same as non-`global` one. You may try the non-`global` join on distributed table just to assess the performance.

**Comment by compasses** [comment]
BTW, how many shards and local table behind  the  distribute table rp_credit_sms_cmcc?
and the second sql run on one shard, right? since it's all local table.
If the distribute table has more than one shard, the distribute one should be better.
