### ISSUE TITLE
Normalized AST is too deep

### ISSUE THREAD

**Issue by hekaifei** [ClickHouse/ClickHouse#16134]
- When I want to perform an update operation, such as the following statement

```UPDATE status = 7, sniffer_count = sniffer_count + 1, last_sniffer_start_time = toDateTime('2020-10-19 12:03:37') WHERE (id IN (15649430, 15649435, 15649440, 15649443...```

There are more than 1000 ID values

- The following errors will be reported

```Code: 167, e.displayText() = DB::Exception: Normalized AST is too deep. Maximum: 1000 (version 19.16.4.12)```

How can I solve it

**Comment by filimonov** [comment]
Please try increasing `max_ast_depth` setting
