### ISSUE TITLE
 mysqlxx::ConnectionFailed   (MySQL engine is not available)

### ISSUE THREAD

**Issue by leoones** [ClickHouse/ClickHouse#16130]
Clickhouse version 20.8.2.3

mysql version 5.6
mysql connect :  
[root@tixcck]# mysql -uptx -p -h172.16.6.207 -P3306
Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 139425
Server version: 5.7.28-log Source distribution

Copyright (c) 2000, 2019, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

ptx@mysqldb 10:39:  [(none)]> 

--===============================================================

excuting Sql  command:
select * from mysql('172.16.6.207:3306', 'ptx_db', 'c_dim_finance_report', 'ptx', 'ptx123')

error.log
2020.10.19 10:25:54.086437 [ 17763 ] {13fc0400-dad5-4d42-8c5c-380656d129ef} <Error> Application: mysqlxx::ConnectionFailed
2020.10.19 10:25:54.087310 [ 17763 ] {13fc0400-dad5-4d42-8c5c-380656d129ef} <Error> executeQuery: Poco::Exception. Code: 1000, e.code() = 2002, e.displayText() = mysqlxx::ConnectionFailed: Can't connect to MySQL server on '192.168.5.207' (4) ((nullptr):0) (version 20.9.3.45 (official build)) (from 172.16.6.210:53228) (in query: select * from mysql('192.168.5.207:3306', 'ptx_db', 'c_dim_finance_report', 'ptx', 'ptx123') ;), Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x18e1b360 in /usr/bin/clickhouse
1. ? @ 0x18c95d86 in /usr/bin/clickhouse
2. mysqlxx::Pool::allocConnection(bool) @ 0x18c9f361 in /usr/bin/clickhouse
3. mysqlxx::Pool::initialize() @ 0x18c9f70d in /usr/bin/clickhouse
4. mysqlxx::Pool::get() @ 0x18c9f918 in /usr/bin/clickhouse
5. DB::TableFunctionMySQL::executeImpl(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const @ 0x15288f50 in /usr/bin/clickhouse
6. DB::ITableFunction::execute(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const @ 0x1588d0d1 in /usr/bin/clickhouse
7. DB::Context::executeTableFunction(std::__1::shared_ptr<DB::IAST> const&) @ 0x1585ad9e in /usr/bin/clickhouse
8. DB::JoinedTables::getLeftTableStorage() @ 0x15cffb64 in /usr/bin/clickhouse
9. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, std::__1::shared_ptr<DB::IBlockInputStream> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&) @ 0x15b39e3c in /usr/bin/clickhouse
10. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x15b3afd9 in /usr/bin/clickhouse
11. DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x15cb33f7 in /usr/bin/clickhouse
12. DB::InterpreterFactory::get(std::__1::shared_ptr<DB::IAST>&, DB::Context&, DB::QueryProcessingStage::Enum) @ 0x15aa2e8f in /usr/bin/clickhouse
13. ? @ 0x15e2fc48 in /usr/bin/clickhouse
14. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool) @ 0x15e31732 in /usr/bin/clickhouse
15. DB::TCPHandler::runImpl() @ 0x164d93f5 in /usr/bin/clickhouse
16. DB::TCPHandler::run() @ 0x164da160 in /usr/bin/clickhouse
17. Poco::Net::TCPServerConnection::start() @ 0x18d391cb in /usr/bin/clickhouse
18. Poco::Net::TCPServerDispatcher::run() @ 0x18d3965b in /usr/bin/clickhouse
19. Poco::PooledThread::run() @ 0x18eb8136 in /usr/bin/clickhouse
20. Poco::ThreadImpl::runnableEntry(void*) @ 0x18eb3530 in /usr/bin/clickhouse
21. start_thread @ 0x7e25 in /usr/lib64/libpthread-2.17.so
22. __clone @ 0xfebad in /usr/lib64/libc-2.17.so

**Comment by filimonov** [comment]
> Can't connect to MySQL server on '192.168.5.207' (4) 

Check your firewall. It seems ClickHouse host can't establish connection to your mysql host.

**Comment by den-crane** [comment]
select * from mysql('**172.16.6.207**:3306', 
Can't connect to MySQL server on '**192.168.5.207'**
(from 172.16.6.210:53228) (in query: select * from mysql(**'192.168.5.207:**3306',

**Comment by leoones** [comment]
> mysql -uptx -p -h**172.16.6.207** -P3306
> select * from mysql('**172.16.6.207**:3306',
> Can't connect to MySQL server on '**192.168.5.207'**
> (from 172.16.6.210:53228) (in query: select * from mysql( **192.168.5.207:** 3306',
> 
> Clickhouse version **20.8.2.3**
> version **20.9.3.45**

already solved . Thank you for your reply  !
