### ISSUE TITLE
skip_unavaliable_databases[tables] flag [or setting]

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#16143]
**Use case**
In case of some problems on clickhouse startup, now clickhouse will threw an exception and refuse to start, in case of vm/bare-metal deployment usually that not an issue to directly connect to server and provide manipulations for fixing the problem, but in case of k8s, you can't simply do that, and you need to attach PV to another pod or replace entrypoint which can be painful.

**Describe the solution you'd like**
Give the ability to start clickhouse in safe mode, which would allow us to fix problems after clickhouse start.
It can be a flag or setting, but we need to have the ability to easily create that kind of flag via clickhouse-operator.

**Additional context**
Probably it makes sense to disallow remote connections in that mode, so that replica wouldn't fail distributed queries because of non-existing tables.

**Comment by alexey-milovidov** [comment]
> that replica wouldn't fail distributed queries because of non-existing tables

This feature is already implemented. Distributed table will select only from replicas that have the required tables.

**Comment by UnamedRus** [comment]
start in safe mode still not implemented
