### ISSUE TITLE
code compiled 

### ISSUE THREAD

**Issue by fernando1987** [ClickHouse/ClickHouse#16157]
The code compiled by yourself uses more memory than the official version.

CC=clang-10 CXX=clang++-10 cmake . -Bbuild-arm64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=cmake/linux/toolchain-aarch64.cmake -DOBJCOPY_PATH=/usr/lib/llvm-10/bin/llvm-objcopy

**Comment by alexey-milovidov** [comment]
Could you please provide the details?

**Comment by fernando1987** [comment]
It's bad judgment
