### ISSUE TITLE
Whether to consider idempotent to Kafka Engine

### ISSUE THREAD

**Issue by jiaoyang3** [ClickHouse/ClickHouse#16152]
Idempotent is very important to Kafka consumer，
Whether to consider idempotent to Kafka Engine？

**Comment by filimonov** [comment]
Do you mean producer (sending the same messages several times on error) or consumer (flushing to materialized view)? 

Can you explain the exact scenario you expect to have?

**Comment by jiaoyang3** [comment]
If the kafka consumer fails to send ACK, repeated consumption may occur, 
So I want to know whether Kafka engine has done some processing in repeated consumption

**Comment by jiaoyang3** [comment]
> Do you mean producer (sending the same messages several times on error) or consumer (flushing to materialized view)?
> 
> Can you explain the exact scenario you expect to have?

If the kafka consumer fails to send ACK, repeated consumption may occur,
So I want to know whether Kafka engine has done some processing in repeated consumption

**Comment by filimonov** [comment]
So you saying about retrying commits. We already do that, but it not always possible (losing the connection / rebalance etc).

One of the possible solutions is to store offsets on clickhouse side, we considering that (but no timeline for that).

**Comment by jiaoyang3** [comment]
ok，It's great, and I'm thinking about trying to change the code myself
