### ISSUE TITLE
Add settings 'limit' and 'offset'.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#16176]
These settings will act as the separate limit and offset applied to query result
(as if query is put into subquery and additional LIMIT and/or OFFSET is added outside).

They should be implemented by adjusting existing LIMIT and/or OFFSET if any or by adding LIMIT and/or OFFSET if there were not in InterpreterSelectQuery.

Example:

Suppose we have a query:
```
SELECT * FROM table LIMIT 100 OFFSET 1000
```

And the setting `limit` is set to 50 and `offset` is set to `75`.
Then we should execute this query as the following:
```
SELECT * FROM table LIMIT 25 OFFSET 1075
```

**Use case:**

API that allows the user to provide arbitrary queries but wants to apply pagination of the result.
If user did not supply the limit in their query, the settings will allow to paginate the whole result.
If user supplied limit in their query, the settings will allow to paginate within already limited result.

**Comment by naman2403** [comment]
LIMIT and OFFSET are used when you want to retrieve only a few records from your result of query. 

LIMIT will retrieve only the number of records specified after the LIMIT keyword, unless the query itself returns fewer records than the number specified by LIMIT.

OFFSET is used to skip the number of records from the results.


Syntax,

SELECT select_list

    FROM table_exp

    [ ORDER BY ... ]

    [ LIMIT { num | ALL } ] [ OFFSET num ]

**Comment by abyss7** [comment]
> Suppose we have a query:
> 
> SELECT * FROM table LIMIT 100 OFFSET 1000
> And the setting limit is set to 50 and offset is set to 75.
> Then we should execute this query as the following:
> 
> SELECT * FROM table LIMIT 25 OFFSET 1075
> 

1. Why may you need `offset` for pagination? If it's a page number, then settings should be named like `page_size`, `page_num`.
2. How do you get numbers 25, 1075 from 100, 1000?

**Comment by alexey-milovidov** [comment]
@naman2403 The task is about adding separate settings `limit` and `offset` that allow to adjust the query result in off-SQL way.

**Comment by alexey-milovidov** [comment]
@abyss7 

> Why may you need offset for pagination? If it's a page number, then settings should be named like page_size, page_num.

It's better to keep the semantcs of the settings aligned with SQL.

> How do you get numbers 25, 1075 from 100, 1000?

From the description of the task, it should work as the following query:

```
SELECT * FROM (SELECT * FROM table LIMIT 100 OFFSET 1000) LIMIT 50 OFFSET 75
```

**Comment by alexey-milovidov** [comment]
The general intent is to add some simple building blocks into ClickHouse that will make creating some APIs easier.

**Comment by hexiaoting** [comment]
> The general intent is to add some simple building blocks into ClickHouse that will make creating some APIs easier.

I get the usage of setting's limit and offset, and I think it can be implemented in the parser phrase to modify limit and offset value when setting's limit and offset are not null. 
But how to add simple building blocks into ClickHouse？I don't understand.

**Comment by alexey-milovidov** [comment]
@hexiaoting The point of these settings is that they should not affect parser - they should not interfere SQL language in any way.

**Comment by alexey-milovidov** [comment]
> But how to add simple building blocks into ClickHouse？

To implement pagination in a safe way when query is given by the user.

**Comment by hexiaoting** [comment]
@alexey-milovidov 
hi,  I think maybe can implement in this way:
on clickhouse client execute below queries:
1. create table xxxx;
2. select xxxx [not effected by limit and offset settings]
3. set limit=50;
4. set offset=10;
5. select xxxx [this will be affected by the new settings's limit and offset]
We can modify executeOffset and executeLimit function in InterpreterSelectQuery to new offset and limit value.
Is this way match our needs? If so , I will do the implementation.

**Comment by alexey-milovidov** [comment]
Yes, this is the way of implementation.

Care should be taken to adjust existing limit and offset if any.
Also a special case when WITH TIES or WITH FILL are present.

**Comment by alexey-milovidov** [comment]
We can adjust existing limits if there are no WITH TIES, WITH FILL and wrap into another LimitTransform if there are.

**Comment by hexiaoting** [comment]
@alexey-milovidov 
I'm trying to implement this feature on Interpreterxxx part, But I find a small problem :
I cannot judge weather this is a direct SELECT query or a subquery in other Queries, So right now If I add LimitTransform directly in InterpterSelectWithUnionQuery, it will make the result wrong.
Like : 
```
CREATE TABLE xx AS SELECT xxx FROM base; // Above query should not be affected by settings's limit and offset
SELECT xxx from base
```
It think it will be the same problem if implemented in parser AST phase. Am I right?
Can you give me some advice? Thank you.

**Comment by alexey-milovidov** [comment]
@hexiaoting Let's check if it's ASTSelectQuery or ASTSelectWithUnionQuery. In the ASTSelectWithUnionQuery, if it contains a single SELECT without WITH TIES, WITH FILL, adjust limits there, otherwise add transform over the result in InterpreterSelectWithUnionQuery.

**Comment by amosbird** [comment]
#17633
