### ISSUE TITLE
[system.users] How can i delete or update user info?

### ISSUE THREAD

**Issue by Veryfirefly** [ClickHouse/ClickHouse#16178]
When using SQL-driven workflow to create a user, because the host_ip parameter is set incorrectly, when updating / deleting the user, they are told that mutations are not supported by storage systemusers. How to delete or update the user? 

Exception Information:
`Received exception from server (version 20.9.3):
Code: 48. DB::Exception: Received from 127.0.0.1:9000. DB::Exception: Mutations are not supported by storage SystemUsers.`

Thanks.

**Comment by abyss7** [comment]
Please, provide exact queries.

**Comment by Veryfirefly** [comment]
> Please, provide exact queries.

I performed the update and delete operations, the code is as follows

```sql
alter table system.users delete where name='clickhouse';
```
```sql
alter table system.users update host_ip=array('::/0') where name='clickhouse'
```

**Comment by Veryfirefly** [comment]
my clickhouse-server version is `ClickHouse server version 20.9.3.45 (official build).`

**Comment by den-crane** [comment]
You can not use `alter table ` in this case. It's not Mysql.

You have to use `drop user clickhouse` & `alter clickhouse user drop IP 'address'`

**Comment by vitlibar** [comment]
Documentation: [ALTER USER](https://clickhouse.tech/docs/en/sql-reference/statements/alter/user/), [DROP USER](https://clickhouse.tech/docs/en/sql-reference/statements/drop/#drop-user-statement)

**Comment by Veryfirefly** [comment]
> You can not use `alter table ` in this case. It's not Mysql.
> 
> You have to use `drop user clickhouse` & `alter clickhouse user drop IP 'address'`

There are two identical users, but the host_ip is different. How to delete one of them.
Excuse me, does alter have an example? The offical documentation and Google information are not very detailed

**Comment by Veryfirefly** [comment]
> Documentation: [ALTER USER](https://clickhouse.tech/docs/en/sql-reference/statements/alter/user/), [DROP USER](https://clickhouse.tech/docs/en/sql-reference/statements/drop/#drop-user-statement)

Thanks, but the offical documentation are not very detailed.
I don’t know how to solve it. The guide of creation of users on the Internet is all based on files.
