### ISSUE TITLE
Improve execution_speed estimations 

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#16221]
clickhouse queries can be killed by `max_execution_time` due to inaccurate estimations.
This estimate is too vulnerable to network issues, temporary slowness at start, and more to be used as the basis of killing a query too early.

For example estimator sometimes estimates 11500 seconds to complete for a distributed query which actually run for 50 seconds.

Proposal: introduce a number of subsequent bad estimates before killing a query, or some other kind of more robust kill estimation.

**Comment by filimonov** [comment]
Loosely related https://github.com/ClickHouse/ClickHouse/issues/12169

**Comment by alexey-milovidov** [comment]
We already have it - `timeout_before_checking_execution_speed`.

**Comment by filimonov** [comment]
Yes, but the idea is to collect different measurements (not from the query start only) 

Analogy from network: you can have a big ping, bug great speed. So you can wait few seconds till the first byte, but after you get that the download goes fast. If you will measure the speed since sending the request you will have initially poor speed which will grow with time, in contrast if you will measure speed since getting the first byte you will get the correct speed.  The similar effect can be archived by measuring on some intervals.

**Comment by alexey-milovidov** [comment]
Currently hold because the implementation is non-trivial.
