### ISSUE TITLE
DateTime64 extended range fails when date is 1969-12-31 and timezone below UTC

### ISSUE THREAD

**Issue by zvonand** [ClickHouse/ClickHouse#16222]
To PR #9404 
DateTime64 extended range
@Enmk 

**`toDateTime64` returns incorrect result when local date is `1969-12-31` and timezone is below UTC**

For example: 
`SELECT toDateTime64('1969-12-31 18:00:12', 0, 'America/Phoenix')` returns `1970-01-01 18:00:12` (the date is wrong, the time is OK)

This bug appears only in `1969-12-31` for timezones below UTC, for example:
`SELECT toDateTime64('1969-12-30 18:00:12', 0, 'America/Phoenix')` returns `1969-12-30 18:00:12` correctly
`SELECT toDateTime64('1969-12-31 18:00:12', 0, 'Europe/Moscow')` returns `1969-12-31 18:00:12` correctly

**Comment by zvonand** [comment]
> duplicate #15784

Not quite, the #15784 is about out-of normal-range in general, and THIS issue is ONLY about 1969-12-31, it has almost nothing in common with #15784

**Comment by alexey-milovidov** [comment]
@zvonand I have finished #9404 and now all your examples works correctly.

**Comment by alexey-milovidov** [comment]
I will add a test.
