### ISSUE TITLE
In the version 20.4.4.18 when change the receive_timeout parameter that will not work

### ISSUE THREAD

**Issue by mateng0915** [ClickHouse/ClickHouse#16224]
1. I try to change the receive_timeout parameter through two ways
1.1 set receive_timeout = xxxxx
1.2 added receive_timeout into the users.xml
both methods when i check the system.settings table, this will show the value which i changed.

![image](https://user-images.githubusercontent.com/26053753/96718642-e32b5c00-13da-11eb-8ba5-e76e1d7bb663.png)
![image](https://user-images.githubusercontent.com/26053753/96718655-e6bee300-13da-11eb-9929-76662f318e09.png)
However when this changed
i still can get this result
Timeout exceeded while receiving data from server. Waited for 300 seconds, timeout is 300 seconds.
Cancelling query.

2. Then i see the source code about this part, maybe i check the wrong part, but i find this
In the file ConnectionParameters.cpp 
![image](https://user-images.githubusercontent.com/26053753/96719104-8d0ae880-13db-11eb-93a5-416526544f51.png)
and this DBMS_DEFAULT_RECEIVE_TIMEOUT_SEC is the macro
![image](https://user-images.githubusercontent.com/26053753/96719151-9b590480-13db-11eb-9b5f-a9eb1b42f1fe.png)

And this value will be the parameter for the ConnectionTimeouts‘s Constructor
and i see the Server.cpp
![image](https://user-images.githubusercontent.com/26053753/96720510-6fd71980-13dd-11eb-83f7-42a0a1b53edb.png)
looks like this part can read the settings value
so i am not sure why this setting is not working when really execute query

Thanks

**Comment by den-crane** [comment]
I think this parameter is applied to CH server, when CH server is a client itself and executes a query against another server.

And it's not obvious how client should/can use this. Because if ch-client pulls value of this parameter from a server and use it then CH server also have to pull this when it plays as a client?

I think receive_timeout needs a better documentation. But it works as designed.

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/4831

**Comment by den-crane** [comment]
for a client it should be set at a client

 clickhouse-client --receive_timeout=6000

**Comment by mateng0915** [comment]
Thanks reply
