### ISSUE TITLE
-If combinator and NULLs

### ISSUE THREAD

**Issue by mkabilov** [ClickHouse/ClickHouse#16231]
Clickhouse version: 20.9.2 revision 54439

```SQL
SELECT
    sumMapIf([1], [1], nullIf(number, 3) > 0) AS col1,
    countIf(1, nullIf(number, 3) > 0) AS col2,
    sumIf(1, nullIf(number, 3) > 0) AS col3
FROM numbers(1, 5)
```

`col1` is expected to be `([1],[4])` as NULLs must be skipped
`col3` value is expected to be the same as `col2`'s as the condition part is identical and both should return `4`

in fact we get the following values:
```
┌─col1──────┬─col2─┬─col3─┐
│ ([1],[5]) │    4 │    5 │
└───────────┴──────┴──────┘
```

as a workaround one can wrap the condition part with `coalesce(..., 0)`

**Comment by den-crane** [comment]
```
20.3.19.4
SELECT
    sumMapIf([1], [1], nullIf(number, 3) > 0) AS col1,
    countIf(1, nullIf(number, 3) > 0) AS col2,
    sumIf(1, nullIf(number, 3) > 0) AS col3
FROM numbers(1, 5)

┌─col1──────┬─col2─┬─col3─┐
│ ([1],[4]) │    4 │    4 │
└───────────┴──────┴──────┘
```

**Comment by hexiaoting** [comment]
assigne to me

**Comment by alexey-milovidov** [comment]
The behaviour is correct in version 20.11 testing.

**Comment by den-crane** [comment]
hmm? 

test : ([1],[5])	4	4

col1 is expected to be ([1],[4])

not 1,5
