### ISSUE TITLE
Exception: Memory limit (for query) exceeded: would use 9.32 GiB (attempt to allocate chunk of 4197072 bytes), maximum: 9.31 GiB: While executing HDFS.

### ISSUE THREAD

**Issue by trollhe** [ClickHouse/ClickHouse#16236]
ERROR:
```
Exception: Memory limit (for query) exceeded: would use 9.32 GiB (attempt to allocate chunk of 4197072 bytes), maximum: 9.31 GiB: While executing HDFS.
```
run "select * from aaa limit 5" throw this error，How to set up ram?

**Comment by den-crane** [comment]
https://clickhouse.tech/docs/en/operations/settings/query-complexity/#settings_max_memory_usage

**Comment by den-crane** [comment]
@trollhe What CH version do use use? 
It could be https://github.com/ClickHouse/ClickHouse/issues/7650

**Comment by trollhe** [comment]
> @trollhe What CH version do use use?
> It could be #7650

the Clickhouse version is 20.9.3

**Comment by trollhe** [comment]
> https://clickhouse.tech/docs/en/operations/settings/query-complexity/#settings_max_memory_usage

thanks den-crane, my setting max_memory_usage,bug is error:
```
↗ Progress: 8.34 million rows, 1.51 GB (1.88 million rows/s., 341.09 MB/s.) 
Received exception from server (version 20.9.3):
Code: 354. DB::Exception: Received from localhost:9000. DB::Exception: inflate failed: buffer error: While executing HDFS. 

0 rows in set. Elapsed: 4.536 sec. Processed 8.34 million rows, 1.51 GB (1.84 million rows/s., 333.40 MB/s.) 
```

**Comment by trollhe** [comment]
```
SET max_memory_usage = 20000000000000
```

**Comment by den-crane** [comment]
>inflate failed: buffer error

I think it's a bug. How is your file compressed?

**Comment by trollhe** [comment]
> > inflate failed: buffer error
> 
> I think it's a bug. How is your file compressed?

file by zlib compression,is *.gz

**Comment by amosbird** [comment]
Parquet format is very memory intensive for clickhouse to work with currently. You can perhaps lower the concurrency if it's some sort of ETL query: `settings max_threads = 1`

**Comment by trollhe** [comment]
> Parquet format is very memory intensive for clickhouse to work with currently. You can perhaps lower the concurrency if it's some sort of ETL query: `settings max_threads = 1`

thanks amosbird, i setting `max_threads = 1`,but new error to me.bellow, see my command detail:

clickhouse-client
```
SET max_memory_usage = 40000000000;
set max_bytes_before_external_group_by=20000000000;
set max_threads=1;


select count(*) from  ext.ext_logs_csv_hdfs;
```

throw error info:
```
↓ Progress: 8.52 million rows, 1.55 GB (1.43 million rows/s., 259.59 MB/s.) 
Received exception from server (version 20.9.3):
Code: 354. DB::Exception: Received from localhost:9000. DB::Exception: inflate failed: buffer error: While executing HDFS. 

0 rows in set. Elapsed: 6.057 sec. Processed 8.52 million rows, 1.55 GB (1.41 million rows/s., 255.23 MB/s.) 
```

**Comment by trollhe** [comment]
this table is large,about 200billions rows. about 3 tb gz file.Can you help me？

**Comment by amosbird** [comment]
zlib inflate will process as much input as possible using the available output. Once it can neither process input nor produce output, it will return buffer error. So this looks like the input stream is ended unexpectedly. Perhaps something is flaky inside libhdfs3. You may try using native hdfs client to read the file and pipe into clickhouse instead. Or you can play with https://hadoop.apache.org/docs/stable/hadoop-hdfs-httpfs/index.html and use the `url` table function to access those huge gzip files.

BTW, what's the definition of `ext.ext_logs_csv_hdfs` ?

**Comment by trollhe** [comment]
> zlib inflate will process as much input as possible using the available output. Once it can neither process input nor produce output, it will return buffer error. So this looks like the input stream is ended unexpectedly. Perhaps something is flaky inside libhdfs3. You may try using native hdfs client to read the file and pipe into clickhouse instead. Or you can play withhttps://hadoop.apache.org/docs/stable/hadoop-hdfs-httpfs/index.htmland use the`url`table function to access those huge gzip files.
> 
> BTW, what's the definition of`ext.ext_logs_csv_hdfs`?


Thanks amosbird.

bellow , `ext.ext_logs_csv_hdfs` table defind is:
```
create table ext.ext_logs_csv_hdfs
(
log_id String,
log_source String,
_timestamp String,
_arecord String,
_rcode String,
_qtype String,
_cn_name String,
aaaa_record String,
_business_ip String
)
ENGINE = HDFS('hdfs://xxxx:8020/external/csv/logs/*', 'CSV');
```

data  delimited is ','.
