### ISSUE TITLE
Why CH always restart automatically after killing it?

### ISSUE THREAD

**Issue by y45398jp123** [ClickHouse/ClickHouse#16254]
I found that CH server can always restart itself in about half a minute after stopping it, or killing it.
Is there any backgound process to keep the CH server alive?
I tried to remove the file from /etc/init.d/clickhouse-server, but the problem occurs.
Actually, It's not a problem, just wondering why...
Thanks.

**Comment by MeteHanC** [comment]
I think this is about the unit file of ClickHouse (for ubuntu, filepath is : /etc/systemd/system/clickhouse-server.service)

Under the Service section you can see the following lines ;

```
Restart=always
RestartSec=30
```

So this is not actually a ClickHouse specific thing

**Comment by InasaXia** [comment]
systemd

**Comment by y45398jp123** [comment]
Got it, thanks a lot.

**Comment by den-crane** [comment]
for initV systems it's a cron-job.

```
# cat /etc/cron.d/clickhouse-server
*/10 * * * * root (which service > /dev/null 2>&1 && (service clickhouse-server condstart ||:)) || /etc/init.d/clickhouse-server condstart > /dev/null 2>&1
```
