### ISSUE TITLE
ALTER DROP doesn't consider size of a partition correctly

### ISSUE THREAD

**Issue by keliss** [ClickHouse/ClickHouse#16251]
Hi. When I try to drop partition for a certain hour:
```alter table db.table drop partition '2020-10-19 18:00:00';```
I sometimes get this error:
```
[2020-10-22 07:21:16] Code: 359, e.displayText() = DB::Exception: Table or Partition in db.table was not dropped.
[2020-10-22 07:21:16] Reason:
[2020-10-22 07:21:16] 1. Size (52.01 GB) is greater than max_[table/partition]_size_to_drop (50.00 GB)
[2020-10-22 07:21:16] 2. File '/var/lib/clickhouse/flags/force_drop_table' intended to force DROP doesn't exist
```
However, if I run this:
```select formatReadableSize(sum(bytes_on_disk)) from (select bytes_on_disk from system.parts where table = 'table' and partition = '2020-10-19 18:00:00');```
I see that the size of this partition is much lower: 48.43 GiB. So why does it tell me that I'm dropping too big partition and why does CH allow such big partitions at all if it prohibits dropping them in the end?

**Comment by keliss** [comment]
Also, the message telling me to "increase (or set to zero) max_[table/partition]_size_to_drop in server config and restart ClickHouse" seems to be misleading - I don't have to restart CH for these settings to apply. Or it's just some CH magic that made the partitions smaller so I was able to drop them normally.

**Comment by abyss7** [comment]
Can you provide please the `SHOW CREATE TABLE` result for table in question? And please provide the CH version.

**Comment by keliss** [comment]
Of course:
```
CREATE TABLE reports.events_shard (`writeTime` DateTime DEFAULT now(), ...) ENGINE = MergeTree() PARTITION BY toStartOfHour(writeTime) ORDER BY tuple() SETTINGS index_granularity = 8192
```
Version is the latest: 20.9.3.45

**Comment by keliss** [comment]
Of course:
```
CREATE TABLE db.table (`writeTime` DateTime DEFAULT now(), ...) ENGINE = MergeTree() PARTITION BY toStartOfHour(writeTime) ORDER BY tuple() SETTINGS index_granularity = 8192;
```
20.9.3.45

**Comment by den-crane** [comment]
> Also, the message telling me to "increase (or set to zero) max_[table/partition]_size_to_drop in server config and restart ClickHouse" seems to be misleading - I don't have to restart CH for these settings to apply. Or it's just some CH magic that made the partitions smaller so I was able to drop them normally (I've already seen such behaviour but I thought it is impossible for a partition to become smaller without dropping any of its parts).

max_partition_size_to_drop reload/apply without restart was implemented recently and this message should be corrected.

**Comment by den-crane** [comment]
As I understand you just finished to insert data to this partition '2020-10-19 18:00:00'.
It is possible that when you checked the size by select `inactive` parts were deleted already.

**Comment by keliss** [comment]
No, this partition remained intact for sure, we don't insert data for some past period of time.

**Comment by den-crane** [comment]
Ah, it is two different units Gib vs GB.

`    <max_partition_size_to_drop>5000000000</max_partition_size_to_drop> 

SELECT
    formatReadableSize(sum(bytes_on_disk)),
    round(((sum(bytes_on_disk) / 1000) / 1000) / 1000, 2) AS GB
FROM system.parts
WHERE table = 'XX'

┌─formatReadableSize(sum(bytes_on_disk))─┬────GB─┐
│ 9.50 GiB                               │ 10.21 │
└────────────────────────────────────────┴───────┘

alter table XX drop partition tuple();

1. Size (10.21 GB) is greater than max_[table/partition]_size_to_drop (5.00 GB)

```

**Comment by keliss** [comment]
But even in this case the exception is triggered by a lower amount of disk space that the limit :)
48.43 GiB * 1024 / 1000 = 49.59 GB.

**Comment by den-crane** [comment]
No. The limit is also in GB(1000). Check my message 

max_partition_size_to_drop = 5000000000

1. Size (10.21 GB) is greater than max_[table/partition]_size_to_drop (5.00 GB)

**Comment by den-crane** [comment]
and 

48.43 * (1024 * 1024 * 1024) / (1000*1000*1000) = 52.00

>1. Size (52.01 GB) is greater than max_[table/partition]_size_to_drop (50.00 GB)

**Comment by keliss** [comment]
Oh, sorry, I calculated incorrectly. Is there any particular reason to keep some limit for DROP queries at all? I can't imagine a use-case for this setting.

**Comment by abyss7** [comment]
> Oh, sorry, I calculated incorrectly. Is there any particular reason to keep some limit for DROP queries at all? I can't imagine a use-case for this setting.

From documentation:
> In many cases mistakes like these will affect all replicas. ClickHouse has built-in safeguards to prevent some types of mistakes — for example, by default you can’t just drop tables with a MergeTree-like engine containing more than 50 Gb of data.

**Comment by keliss** [comment]
Ok, got it. Thanks for your help.
