### ISSUE TITLE
Delete TTL setting

### ISSUE THREAD

**Issue by igortyulkin** [ClickHouse/ClickHouse#16259]
I read doc here - https://clickhouse.tech/docs/ru/sql-reference/statements/alter/ttl/
and here - https://clickhouse.tech/docs/ru/engines/table-engines/mergetree-family/mergetree/#table_engine-mergetree-ttl

But I didn't find any information about how I can remove the TTL setting from the table.
For example, this could be useful in migration, in the case of a rollback.

**Comment by den-crane** [comment]
You can set TTL to the future + 10 years for example.

`ALTER TABLE example_table MODIFY TTL d + INTERVAL 10 years;`

Starting from CH 20.11 `ALTER TABLE REMOVE TTL`

**Comment by igortyulkin** [comment]
Grateful! but `YEAR`, not `YEARS`
