### ISSUE TITLE
Using HDFS Engine virtual columns as partitions

### ISSUE THREAD

**Issue by yehiaelbehery** [ClickHouse/ClickHouse#16279]
Hello guys,
I'm using HDFS table and need to optimize I/O and read only a subset of files but the virtual column _file is enriched to every row and merely used for row filtering not "partitioning", correct?
And if so is there any way I can partition or simulate partitioning HDFS tables (other than creating a new table with the specified partition that is)?

ClickHouse 20.6.5.8

**Comment by den-crane** [comment]
Feature: Filter (prune) hdfs files by condition in `select from hdfs(*) where _file = ` but not by globe/wildcard in hfds(....).

**Comment by alexey-milovidov** [comment]
We don't support HDFS.
