### ISSUE TITLE
about change config.xml dir question

### ISSUE THREAD

**Issue by vegastar002** [ClickHouse/ClickHouse#16278]
in config.xml, i change all /var to /opt because /var has not enough space, it's first run.
ok, then i start clickhouse. it's show:
Start clickhouse-server service: Path to data directory in /etc/clickhouse-server/config.xml: /opt/lib/clickhouse
Creating directory /opt/lib/clickhouse/
Changing owner of [/opt/lib/clickhouse] to [clickhouse: clickhouse]
UNKNOWN

it's not success start, i think it's about of right, but i don't known how to resolve....

**Comment by den-crane** [comment]
Check /var/log/clickhouse-server/stderr.log and /var/log/clickhouse-server/clickhouse-server.log
