### ISSUE TITLE
Does clickhouse support large-scale deployment of docker or openstack or esxi?

### ISSUE THREAD

**Issue by trollhe** [ClickHouse/ClickHouse#16287]
Does clickhouse support cloud deployment? Are there any reference materials and user cases?

**Comment by alexey-milovidov** [comment]
Yes.

**Comment by alexey-milovidov** [comment]
You can use Managed ClickHouse on
- Yandex Cloud;
- Altinity Cloud;
- Mail.ru Cloud;
- Alibaba Cloud;
- Tencent Cloud.

You can use ClickHouse Kubernetes operator.
https://github.com/Altinity/clickhouse-operator

You can use ClickHouse Docker image.
