### ISSUE TITLE
Code: 202. DB::Exception: Received from localhost:9000. DB::Exception: Too many simultaneous queries. Maximum: 100.

### ISSUE THREAD

**Issue by trollhe** [ClickHouse/ClickHouse#16281]
in clickhouse-client,throw **DB::Exception: Too many simultaneous queries. Maximum: 100. (version 20.9.3.45 (official build))**
```
$ clickhouse-client
ClickHouse client version 20.9.3.45 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 20.9.3 revision 54439.

slave1 :) Cannot load data for command line suggestions: Code: 202, e.displayText() = DB::Exception: Received from localhost:9000. DB::Exception: Too many simultaneous queries. Maximum: 100. (version 20.9.3.45 (official build))
```

**Comment by den-crane** [comment]
There are a limiter `max_concurrent_queries=100`.
https://clickhouse.tech/docs/en/operations/server-configuration-parameters/settings/#max-concurrent-queries
It limits the number simultaneously processed requests.
How many queries you execute simultaneously?

**Comment by trollhe** [comment]
> There are a limiter `max_concurrent_queries=100`.
> https://clickhouse.tech/docs/en/operations/server-configuration-parameters/settings/#max-concurrent-queries
> It limits the number simultaneously processed requests.
> How many queries you execute simultaneously?

thank you . i need to execute about 2000 queries simultaneously.

**Comment by alexey-milovidov** [comment]
@trollhe It's better to put requests in a queue and execute sequentially (or limit parallelism to a relatively small value) than to do all 2000 queries at once.

**Comment by Malibu351** [comment]
@trollhe hello, which item in the system table can view the current number of parallel queries? I tryed "Query" in system.metrics to control, buy it seems not worked.
