### ISSUE TITLE
Do not require structure for table functions used in INSERT SELECT statements

### ISSUE THREAD

**Issue by alex-zaitsev** [ClickHouse/ClickHouse#16295]
**Use case**

In INSERT SELECT statements from table functions it is necessary to specify structure now. However, structure can be inferred from the table that data is inserted into.

For example, insert using pipe is as easy as this:
```
zcat *.gz | clickhouse-client --query "INSERT INTO ssb_druid.lineorder_insert_test FORMAT CSV"
```

However, if file() function is used for the same purpose, it is very bulky:

```
INSERT INTO  lineorder SELECT * FROM file('./lineorder/*','CSV', '    `LO_ORDERKEY` UInt32,     `LO_LINENUMBER` UInt8,     `LO_CUSTKEY` UInt32,     `LO_PARTKEY` UInt32,     `LO_SUPPKEY` UInt32,     `LO_ORDERDATE` Date,     `LO_ORDERPRIORITY` String,     `LO_SHIPPRIORITY` UInt8,     `LO_QUANTITY` UInt8,     `LO_EXTENDEDPRICE` UInt32,     `LO_ORDTOTALPRICE` UInt32,     `LO_DISCOUNT` UInt8,     `LO_REVENUE` UInt32,     `LO_SUPPLYCOST` UInt32,     `LO_TAX` UInt8,     `LO_COMMITDATE` Date,     `LO_SHIPMODE` String,     `C_CUSTKEY` UInt32,     `C_NAME` String,     `C_ADDRESS` String,     `C_CITY` String,     `C_NATION` String,     `C_REGION` String,     `C_PHONE` String,     `C_MKTSEGMENT` String,     `S_SUPPKEY` UInt32,     `S_NAME` String,     `S_ADDRESS` String,     `S_CITY` String,     `S_NATION` String,     `S_REGION` String,     `S_PHONE` String,     `P_PARTKEY` UInt32,     `P_NAME` String,     `P_MFGR` String,     `P_CATEGORY` String,     `P_BRAND` String,     `P_COLOR` String,     `P_TYPE` String,     `P_SIZE` UInt8,     `P_CONTAINER` String');
```

**Describe the solution you'd like**

Ideally, it should work as easy as this and report an error if structure does not match:
```
INSERT INTO  lineorder SELECT * FROM file('./lineorder/*','CSV')
```

Same should work for url(), hdfs() and s3() functions.

**Comment by amosbird** [comment]
This task is already in the Intern List. However I do have another simple implementation in mind. We can provide a `schema` function which accepts a table identifier and evaluates to a const string of column definition list. We can also provide some abilities to transform the result list.

**Comment by alex-zaitsev** [comment]
I think it is different/simpler than a task in interns list (https://github.com/ClickHouse/ClickHouse/issues/14450). When insert/select is considered the destination structure is already given, so source structure should match. clickhouse-client can already do it when accepting insert from stdin.

**Comment by alexey-milovidov** [comment]
> This task is already in the Intern List.

No, the task in intern's list is about schema inference from the data - regardless to the existence of INSERT query.

And what's proposed in this task is to:
- figure out that we have INSERT SELECT;
- make sure SELECT is trivial `SELECT * FROM function(...)`;
- provide a hint from the INSERT query to the table function - that the INSERT query "wants" this table structure.

The implementation looks tricky, because it is:
- context dependent: the behaviour of SELECT query depends on whether it is inside INSERT SELECT or not;
- too specific: it requires trivial query like SELECT * (or a straight list of columns) without GROUP BY, JOIN...

I'm not convinced that we should have it.

**Comment by alex-zaitsev** [comment]
An alternative is to implement something like getTableStructure() method and use it instead. 

```
INSERT INTO  lineorder SELECT * FROM file('./lineorder/*','CSV', getTableStructure('lineorder'))
```

That removes contents dependency. @alexey-milovidov ?

**Comment by amosbird** [comment]
@alex-zaitsev That's what I proposed, but I think it requires additional thinking. This function can somehow be smarter.

**Comment by Slach** [comment]
@amosbird maybe 
COLUMNS expression and EXCEPT clause will usefull for this corner case
https://clickhouse.tech/docs/en/sql-reference/statements/select/#columns-expression
https://clickhouse.tech/docs/en/sql-reference/statements/select/#except-modifier

**Comment by alexey-milovidov** [comment]
This is solved in different way.

When you do `INSERT INTO  lineorder SELECT * FROM file('./lineorder/*.csv')`
SELECT will parse CSV as String/Float64 columns and then types will be converted on INSERT.
