### ISSUE TITLE
why binary file size of version 20.10 is smaller than 20.6

### ISSUE THREAD

**Issue by l1t1** [ClickHouse/ClickHouse#16328]
any module removed in the version 20.10?

**Comment by alexey-milovidov** [comment]
It's the effect of enabled ThinLTO after moving to clang. There is also performance improvement as a bonus.

**Comment by l1t1** [comment]
any datasheet of the performance improvements?

**Comment by alexey-milovidov** [comment]
https://clickhouse-test-reports.s3.yandex.net/15239/677a7e485f511314cd7bfbd349cf6d24ccb2be37/performance_comparison/report.html#fail1

(from here: https://github.com/ClickHouse/ClickHouse/pull/15239)

**Comment by alexey-milovidov** [comment]
Please read the wonderful article from Danila Kutenin: https://danlark.org/2020/10/08/i-need-extra-c-c-performance-now-how/

**Comment by l1t1** [comment]
thanks
