### ISSUE TITLE
does clickhouse benefit from gpu cards?

### ISSUE THREAD

**Issue by l1t1** [ClickHouse/ClickHouse#16345]
if not, will it?

**Comment by den-crane** [comment]
No. Not in near future.

**Comment by den-crane** [comment]
https://youtu.be/7pK-rrmnt8Q?t=6179

**Comment by l1t1** [comment]
the URL is banned in my area

**Comment by alexey-milovidov** [comment]
There are tests of ClickHouse on CPU vs OmniSci on GPU from Deutsche Bank,
the results are that ClickHouse outperforms GPU database in all cases except one query with complex JOINs.

https://www.highload.ru/moscow/2019/abstracts/5905
