### ISSUE TITLE
Code: 354. DB::Exception: Received from localhost:9000. DB::Exception: inflate failed: buffer error: While executing HDFS. 

### ISSUE THREAD

**Issue by trollhe** [ClickHouse/ClickHouse#16348]
Hello,When I query GZ files(compression level is 9) in HDFS through Clickhouse, I throw a problem:Code: 354. DB::Exception: Received from localhost:9000. DB::Exception: inflate failed: buffer error: While executing HDFS. 

```
↗ Progress: 8.52 million rows, 1.55 GB (1.36 million rows/s., 247.52 MB/s.) 
Received exception from server (version 20.9.3):
Code: 354. DB::Exception: Received from localhost:9000. DB::Exception: inflate failed: buffer error: While executing HDFS. 

0 rows in set. Elapsed: 6.347 sec. Processed 8.52 million rows, 1.55 GB (1.34 million rows/s., 243.56 MB/s.) 
```

i settings:
```
SET max_memory_usage = 40000000000;
set max_bytes_before_external_group_by=20000000000;
set max_threads=1;

select count(*) from  ext.ext_logs_csv_hdfs;

```

this table is large,about 200 billions rows. about 3 tb gz file.this one day data size.

**Comment by zhanglistar** [comment]
It seems that inflate buffer problem, eg. buffer too small.

**Comment by trollhe** [comment]
> It seems that inflate buffer problem, eg. buffer too small.

thanks zhanglistar. 

excuse me,it`s table engine buffer?  how to settings?

**Comment by zhanglistar** [comment]
> > It seems that inflate buffer problem, eg. buffer too small.
> 
> thanks zhanglistar.
> 
> excuse me,it`s table engine buffer? how to settings?

It's hard code now, it is a bug for now.

**Comment by alexey-milovidov** [comment]
Cannot reproduce.
