### ISSUE TITLE
how to join oracle on http://ui.tabix.io/ or windows？

### ISSUE THREAD

**Issue by wjce** [ClickHouse/ClickHouse#16388]
on http://ui.tabix.io/, I try join oracle and use remote url but error
Code: 279, e.displayText() = DB::NetException: All connection tries failed. Log: 
Code: 32, e.displayText() = DB::Exception: Attempt to read after eof (version 19.17.5.18 (official build))

**Comment by filimonov** [comment]
We are not making support for tabix. We are not making support for Oracle either. :)

If you need to get a good ansers, please start with asking questions properly :) 

P.S. Tabix can't work with oracle. 

P.P.S. Clickhouse version 19.17.5.18 is not supported.
