### ISSUE TITLE
When creating a materialized view, the order of column fields is different, resulting in abnormal column data

### ISSUE THREAD

**Issue by Veryfirefly** [ClickHouse/ClickHouse#16385]
This is an abnormal working SQL

```sql
CREATE MATERIALIZED VIEW t_daily_player_create
(
    DayCreatePlayerCount UInt32,
    CreateDay Date,
    ConvertServerIndex UInt16,
    Source UInt32
) ENGINE = AggregatingMergeTree()
PARTITION BY CreateDay
ORDER BY (CreateDay, ConvertServerIndex)
POPULATE AS(
    SELECT
        CreateDay,
        count(Id) as DayCreatePlayerCount,
        ConvertServerIndex,
        Source
    FROM t_role
    GROUP BY CreateDay, ConvertServerIndex, Source
);
```

The result is as follows：

![abnormal](http://s2676440002-loahf.gtarcade.com/abnormal.png)

------

This is normal working SQL

```sql
CREATE MATERIALIZED VIEW t_daily_player_create
(
    CreateDay Date,
    DayCreatePlayerCount UInt32,
    ConvertServerIndex UInt16,
    Source UInt32
) ENGINE = AggregatingMergeTree()
PARTITION BY CreateDay
ORDER BY (CreateDay, ConvertServerIndex)
POPULATE AS(
    SELECT
        CreateDay,
        count(Id) as DayCreatePlayerCount,
        ConvertServerIndex,
        Source
    FROM t_role
    GROUP BY CreateDay, ConvertServerIndex, Source
);
```

The result is as follows:

![normal](http://s2676440002-loahf.gtarcade.com/normal.png)

**Comment by filimonov** [comment]
https://github.com/ClickHouse/ClickHouse/issues/13838

**Comment by ILYenBui** [comment]
Hi [Veryfirefly],
For your first query, the first field is Uint32 however, in Populate you use CreateDay, so basically Clickhouse will pickup CreateDay value to populate, however as tables' definition the destination field type is Uint32 thus Clickhouse will interpret the date value into integer data type and that is the reason why 18535 for example. The same for the second field, it was defined as Date data type, however, you populate this date data type field by integer value so it will interpret from integer to date behind the scene and you got 1970.*. This is very normal for data insert/populate that you need to put correct order of source and destination field. Hope this is clear to you. Regards
```
CREATE MATERIALIZED VIEW t_daily_player_create
(
    DayCreatePlayerCount UInt32,
    CreateDay Date,
    ConvertServerIndex UInt16,
    Source UInt32
) ENGINE = AggregatingMergeTree()
PARTITION BY CreateDay
ORDER BY (CreateDay, ConvertServerIndex)
POPULATE AS(
    SELECT
        CreateDay,
        count(Id) as DayCreatePlayerCount,
        ConvertServerIndex,
        Source
    FROM t_role
    GROUP BY CreateDay, ConvertServerIndex, Source
);
```

**Comment by melvynator** [comment]
The provided image doesn't work anymore. The question seems answered.
