### ISSUE TITLE
POST parameters are not parsed as query parameters

### ISSUE THREAD

**Issue by DarkWanderer** [ClickHouse/ClickHouse#16383]
Creating by [request](https://t.me/c/1425947904/8368) of @alexey-milovidov 

**Describe the bug**
`query` parameter is recognized both in 'form' POST data and in URI parameters. However, query parameters (`param_*`) are only recognized in URL and cannot be passed in `multipart/form-data`

**How to reproduce**
* ClickHouse 20.10.2.20
* Run following command: `curl -F "param_id=1" -F "query=SELECT {id:Int32}" --user default: http://localhost:8123/` (substitute host and credentials as needed)

**Observed behavior**
Code: 456, e.displayText() = DB::Exception: Query parameter `id` was not set (version 20.10.2.20 (official build))

**Expected behavior**
Query should complete successfully

**Additional context**
Being able to pass POST parameters in request body allows to process larger queries, as currently parameterized queries with many/large parameters can cause exceptions both in client libraries and in ClickHouse itself due to long URL

**Comment by filimonov** [comment]
Duplicate of #8842
