### ISSUE TITLE
When I start clickhouse-server，return UNKNOWN .   version :20.8.4.11 ,rpm install

### ISSUE THREAD

**Issue by renwei111** [ClickHouse/ClickHouse#16387]
command：service clickhouse-server start

Start clickhouse-server service: <jemalloc>: perCPU arena getcpu() not available. Setting narenas to 160.
Path to data directory in /etc/clickhouse-server/config.xml: /var/lib/clickhouse/
<jemalloc>: perCPU arena getcpu() not available. Setting narenas to 160.
UNKNOWN

**Comment by filimonov** [comment]
You have an old kernel (centos 6?), and jemalloc send a warning about it used a fallback implementation to deteminie the number of cpus. (it detected 160 of them, is it correct?)

Beside that everything should work normally.

**Comment by filimonov** [comment]
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/15611

**Comment by renwei111** [comment]
Thanks
