### ISSUE TITLE
why clickhouse doesn't support ZK certificate authentication

### ISSUE THREAD

**Issue by wallace-clickhouse** [ClickHouse/ClickHouse#16394]
When I use ReplicatedMergeTree with zookeeper,I find clickhouse only supports username/password way to connect ZK,so why clickhouse doesn't support certificate authentication to connect to ZK?
Is there any plan? Thank you!

**Comment by den-crane** [comment]
I think CH does support it.

https://github.com/ClickHouse/ClickHouse/pull/10184/files
