### ISSUE TITLE
Capnproto format

### ISSUE THREAD

**Issue by wutchzone** [ClickHouse/ClickHouse#16392]
Hello, 
I am unable to make inserts of format `CapnProto`

I create the table like this
```
CREATE TABLE default.cap_fin (
    `searchPhrase` String,
    `c` UInt64
    ) 
ENGINE = MergeTree()
order by searchPhrase
```

My `CapnProto` is defined like this
```
@0xa08545c946911363;

struct Message {
  searchPhrase @0 :Text;
  c @1 :UInt64;
}
```

But I am unable to insert the following [data](https://drive.google.com/file/d/1kLTxoPBFJ93SEV_I7w55gOspvMhX3bfu/view?usp=sharing).

ClickHouse returns 
```
cat ch.bin | clickhouse-client --query "INSERT INTO cap_fin FORMAT CapnProto SETTINGS format_schema='schema:Message'"

Code: 33. DB::Exception: Cannot read all data. Bytes read: 3. Bytes expected: 4.
```

I am able to read the binary in other languages where do I use `CapnProto`. So I am 99% sure that binary is serialized correctly. I was following the [doc](https://clickhouse.tech/docs/en/interfaces/formats/#capnproto).
Can you help me please? Thank you

**Comment by alexey-milovidov** [comment]
@wutchzone Why this task is closed?

**Comment by wutchzone** [comment]
Sorry, I have forgotten to add resolution. We have upgraded clickhouse to the latest version and now it is working. Dunno what caused the problem.
