### ISSUE TITLE
macOS: Settings.cpp error: stack frame size of ... bytes in lambda expression 

### ISSUE THREAD

**Issue by lisun** [ClickHouse/ClickHouse#16391]
Make sure that `git diff` result is empty and you've just pulled fresh master. Try cleaning up cmake cache. Just in case, official build instructions are published here: https://clickhouse.yandex/docs/en/development/build/

**Operating system**
OS kind or distribution, specific version/release, non-standard kernel if any. If you are trying to build inside virtual machine, please mention it too.
macOS catalina 10.15.7 
MacBook Pro (Retina, 15-inch, Mid 2015) 
16 GB memory
**Cmake version**
cmake version 3.18.4
**Ninja version**
1.10.1
**Compiler name and version**
llvm   11.0.0
**Full cmake and/or ninja output**
FAILED: src/CMakeFiles/dbms.dir/Core/Settings.cpp.o
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -DBUNDLED_STATIC_JEMALLOC=1 -DLZ4_DISABLE_DEPRECATE_WARNINGS=1 -DPOCO_ENABLE_CPP11 -DPOCO_HAVE_FD_POLL -DPOCO_OS_FAMILY_UNIX -DSNAPPY_CODEC_AVAILABLE -DUNALIGNED_OK -DUSE_FASTMEMCPY=0 -DUSE_JEMALLOC=1 -DUSE_REPLXX=1 -DUSE_XXHASH=1 -DWITH_COVERAGE=0 -DWITH_GZFILEOP -DX86_64 -DZLIB_COMPAT -Iincludes/configs -I../src -Isrc -Isrc/Core/include -I../base/common/.. -Ibase/common/.. -I../contrib/cityhash102/include -I../contrib/cctz/include -Icontrib/zlib-ng -I../contrib/zlib-ng -I../base/pcg-random/. -I../contrib/lz4/lib -I../contrib/zstd/lib -I../contrib/libuv/include -isystem ../contrib/orc/c++/include -isystem contrib/orc/c++/include -isystem ../contrib/protobuf/src -isystem ../contrib/sparsehash-c11 -isystem ../contrib/openldap-cmake/darwin_x86_64/include -isystem ../contrib/openldap/include -isystem ../contrib/avro/lang/c++/include -isystem ../contrib/pdqsort -isystem ../contrib/libcxx/include -isystem ../contrib/libcxxabi/include -isystem ../contrib/jemalloc-cmake/include -isystem ../contrib/libdivide/. -isystem ../contrib/cppkafka/include -isystem ../contrib/librdkafka-cmake/include -isystem ../contrib/librdkafka/src -isystem contrib/librdkafka-cmake/auxdir -isystem ../contrib/AMQP-CPP/include -isystem ../contrib/openssl-cmake/linux_x86_64/include -isystem ../contrib/openssl/include -isystem ../contrib/libbtrie/include -isystem ../contrib/boost -isystem ../contrib/msgpack-c/include -isystem ../contrib/re2 -isystem ../contrib/poco/Net/include -isystem ../contrib/poco/Foundation/include -isystem ../contrib/poco/NetSSL_OpenSSL/include -isystem ../contrib/poco/Crypto/include -isystem ../contrib/poco/Util/include -isystem ../contrib/poco/JSON/include -isystem ../contrib/poco/XML/include -isystem ../contrib/replxx/include -isystem ../contrib/fmtlib-cmake/../fmtlib/include -isystem ../contrib/double-conversion -isystem ../contrib/ryu -isystem contrib/re2_st -isystem ../contrib/croaring -isystem ../contrib/poco/MongoDB/include -isystem ../contrib/capnproto/c++/src -isystem ../contrib/arrow/cpp/src -isystem ../contrib/arrow-cmake/cpp/src -isystem ../contrib/avro/lang/c++/api -fdiagnostics-color=always -std=c++2a -fsized-deallocation  -msse4.1 -msse4.2 -mpopcnt   -Wall -Wno-unused-command-line-argument  -stdlib=libc++ -fdiagnostics-absolute-paths -fexperimental-new-pass-manager -Werror -mmacosx-version-min=10.15 -Wextra -Wframe-larger-than=32768 -Wpedantic -Wno-vla-extension -Wno-zero-length-array -Wno-c11-extensions -Wcomma -Wconditional-uninitialized -Wcovered-switch-default -Wdeprecated -Wembedded-directive -Wempty-init-stmt -Wextra-semi-stmt -Wextra-semi -Wgnu-case-range -Winconsistent-missing-destructor-override -Wnewline-eof -Wold-style-cast -Wrange-loop-analysis -Wredundant-parens -Wreserved-id-macro -Wshadow-field -Wshadow-uncaptured-local -Wshadow -Wstring-plus-int -Wundef -Wunreachable-code-return -Wunreachable-code -Wunused-exception-parameter -Wunused-macros -Wunused-member-function -Wzero-as-null-pointer-constant -Wno-c++98-compat-pedantic -Wno-c++98-compat -Wno-c99-extensions -Wno-conversion -Wno-ctad-maybe-unsupported -Wno-deprecated-dynamic-exception-spec -Wno-disabled-macro-expansion -Wno-documentation-unknown-command -Wno-double-promotion -Wno-exit-time-destructors -Wno-float-equal -Wno-global-constructors -Wno-missing-prototypes -Wno-missing-variable-declarations -Wno-nested-anon-types -Wno-packed -Wno-padded -Wno-return-std-move-in-c++
11 -Wno-shift-sign-overflow -Wno-sign-conversion -Wno-switch-enum -Wno-undefined-func-template -Wno-unused-template -Wno-vla -Wno-weak-template-vtables -Wno-weak-vtables -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk   -D OS_DARWIN -nostdinc++ -MD -MT src/CMakeFiles/dbms.dir/Core/Settings.cpp.o -MF src/CMakeFiles/dbms.dir/Core/Settings.cpp.o.d -o src/CMakeFiles/dbms.dir/Core/Settings.cpp.o -c ../src/Core/Settings.cpp
/private/tmp/clickhouse-20201026-62117-1k7bg85/src/Core/Settings.cpp:20:1: error: stack frame size of 78808 bytes in lambda expression [-Werror,-Wframe-larger-than=]
IMPLEMENT_SETTINGS_TRAITS(SettingsTraits, LIST_OF_SETTINGS)
^
/private/tmp/clickhouse-20201026-62117-1k7bg85/src/Core/BaseSettings.h:817:46: note: expanded from macro 'IMPLEMENT_SETTINGS_TRAITS'
        static const Accessor the_instance = [] \
                                             ^
1 error generated.
[3407/4487] Building CXX object src/CMakeFiles/dbms.dir/Core/SortDescription.cpp.o
[3408/4487] Building CXX object src/CMakeFiles/dbms.dir/Core/iostream_debug_helpers.cpp.o
ninja: build stopped: subcommand failed.

HOMEBREW_VERSION: 2.5.6-132-gde8f487
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: de8f487b8476756fed684cae4f1d721e5ba4748d
Last commit: 19 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core.git
Core tap HEAD: 9c6c9d7a8ef9769cf0fc9ae30ba352c9e6118c87
Core tap last commit: 50 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit haswell
Clang: 12.0 build 1200
Git: 2.29.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 15.0.1, 14, 11.0.7, 1.8.0_262
macOS: 10.15.7-x86_64
CLT: 12.0.32.2
Xcode: 12.1

HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j8
CMAKE_PREFIX_PATH: /usr/local/opt/zlib:/usr/local/opt/readline:/usr/local/opt/llvm:/usr/local
CMAKE_INCLUDE_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_PATH: /usr/local/opt/zlib/lib/pkgconfig:/usr/local/opt/readline/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.15
HOMEBREW_GIT: git
HOMEBREW_SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Homebrew/Library/Homebrew/shims/mac/super:/usr/local/opt/cmake/bin:/usr/local/opt/ninja/bin:/usr/local/opt/libtool/bin:/usr/local/opt/gettext/bin:/usr/local/opt/llvm/bin:/usr/bin:/bin:/us
r/sbin:/sbin

**Comment by filimonov** [comment]
Try to relax the frame size limitation here 
https://github.com/ClickHouse/ClickHouse/blob/54bb5e110d71edb298996ba18294069c75c5c184/cmake/warnings.cmake#L27

Please report back the value which worked for you.

See also: https://github.com/ClickHouse/ClickHouse/commit/4ba8f8960bd4e86a57dafba6a0aa1574b66d97db

**Comment by lisun** [comment]
> Try to relax the frame size limitation here
> https://github.com/ClickHouse/ClickHouse/blob/54bb5e110d71edb298996ba18294069c75c5c184/cmake/warnings.cmake#L27
> 
> For example to 131072
> 
> Please report back if that value worked for you.
> 
> See also: [4ba8f89](https://github.com/ClickHouse/ClickHouse/commit/4ba8f8960bd4e86a57dafba6a0aa1574b66d97db)

That works for me. Thank you!

**Comment by lisun** [comment]
https://github.com/lisun/homebrew-clickhouse/

Add homebrew tap
brew tap lisun/clickhouse
Install ClickHouse
brew upgrade
brew install clickhouse

I fork and update a brew for mac
Welcome to use!
