### ISSUE TITLE
поддержка массивов в словарях

### ISSUE THREAD

**Issue by aCLr** [ClickHouse/ClickHouse#1640]
Приветствую.

Массивы в словарях на текущий момент, насколько я мог понять, не поддерживаются. В качестве источника словаря используем PostgreSQL, массивы в которых имеют вид "{el1, el2, ...}".
Работаем с ними сейчас как со строками, используя примерно такие костыли:

```sql
# вариант с массивом
SELECT count() FROM stats WHERE event_date > '2017-10-01' AND offer_id IN (SELECT cast(id as UInt32) FROM dicts.offers_dict WHERE has(splitByChar(',', substring(countries, 2, length(countries)- 2)), '80'));
# вариант с like
SELECT count() FROM stats WHERE event_date > '2017-10-01' AND offer_id IN (SELECT cast(id as UInt32) FROM dicts.offers_dict WHERE concat(',', substring(countries, 2, length(countries) - 2), ',') like '%,80,%');

```

Подзапрос возвращает id тех offers, у которых поле countries содержит элемент "80". 
Вариант с like при этом быстрее примерно в два раза.

Есть ли возможность ускорить запрос? Или каким-то образом нативно использовать массивы в качестве атрибутов словарей?

**Comment by alexey-milovidov** [comment]
Поддержку массивов в словарях мы хотели бы сделать,
но парсинг массивов в формате PostgreSQL, возможно, придётся вынести в отдельную задачу,
либо реализовать возможность постпроцессинга значений, загруженных из удалённого источника, с помощью выражений в ClickHouse - тогда можно будет парсить эти массивы при загрузке, и затем эффективно с ними работать.

**Comment by alexey-milovidov** [comment]
CC @kitaisreal
