### ISSUE TITLE
TTL Questions about the expired data part which data already be deleted but the data content still exists

### ISSUE THREAD

**Issue by mateng0915** [ClickHouse/ClickHouse#16420]
I set my TTL is 14 days
![image](https://user-images.githubusercontent.com/26053753/97253235-e1ccba00-1846-11eb-9d9d-93a60a4649fc.png)

Today is the 10.27 2020. Then i check the data in the 09.30 2020
I found that the data already deleted however the data context still exist
![image](https://user-images.githubusercontent.com/26053753/97253317-12acef00-1847-11eb-805d-c46ee92fc3ce.png)
I want to know when this content can be deleted or it will never be delete? 

Thanks

**Comment by den-crane** [comment]
> it will never be delete?

It is empty - zero rows parts.
They will never be deleted until this PR is completed https://github.com/ClickHouse/ClickHouse/pull/13252 
Check comments of the PR for more info

**Comment by mateng0915** [comment]
Thanks for you reply
