### ISSUE TITLE
Support for online changes of index granularity

### ISSUE THREAD

**Issue by bobrik** [ClickHouse/ClickHouse#1644]
It'd be nice to have an ability to change index granularity in ClickHouse with a query, like:

```
ALTER TABLE foo SET INDEX GRANULARITY = 4096
```

Only new and merged parts will get new granularity setting, but it seems a lot easier than what one has to do now to change index granularity.

cc @vavrusa, @dqminh

**Comment by vavrusa** [comment]
@ztlpn Could that work with the new CREATE TABLE syntax?

**Comment by alexey-milovidov** [comment]
Currently we use fixed index_granularity for some arithmetic when reading data.

Worth to note, that it's better to have variable size (adaptive) index granularity.
For example, it's better to place "marks" not after each n-th row, but after some amount of data in bytes.

If we do it, it will be possible to also have different index_granularity in different parts.
This requires very accurate code modifications and introducing new format for .mrk files to keep track of number of rows per mark.

An alternative variant is to allow different but fixed index_granularity per each part. Although this looks simpler at first glance, there are some details.

**Comment by filimonov** [comment]
Adaptive index granularity is avaliable since 19.7 and is default since 19.11
