### ISSUE TITLE
Cannot query ALIAS columns in Merge tables.

### ISSUE THREAD

**Issue by JTCunning** [ClickHouse/ClickHouse#16456]
Hello ClickHouse maintainers,

We have recently identified a bug in Merge tables that are preventing us from using them.

We'd like to use a Merge table to query the values from two similarly typed columns with two different names, and thought that `ALIAS` was the best way forward to make the Merge table happy. While attempting to implement an `ALIAS` column, we noticed that it is not identified by the Merge engine and results in the column not being found.

In light of this, we would like to know if you recommended any other way to query same typed but different named columns in two tables with a Merge table.

**Steps to reproduce:**
```
CREATE TABLE strings_old
(
    `str` String
)
ENGINE = MergeTree()
ORDER BY str

Ok.

...

CREATE TABLE strings_new
(
    `str_lc` LowCardinality(String),
    `str` ALIAS toString(str_lc)
)
ENGINE = MergeTree()
ORDER BY str_lc

Ok.

...

CREATE TABLE strings_merge
(
    `str` String
)
ENGINE = Merge('default', '^strings')

Ok.

...

SELECT str
FROM strings_merge


Received exception from server (version 20.10.2):
Code: 16. DB::Exception: Received from localhost:9000. DB::Exception: There is no column with name `str` in table default.strings_new. There are columns: str_lc, _part, _part_index, _partition_id, _sample_factor.
```

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/6051
