### ISSUE TITLE
JSONExtractKey function

### ISSUE THREAD

**Issue by Melchizedek13** [ClickHouse/ClickHouse#16459]
Hi everyone,

Not so long time ago I found that there was no implementation of the function `JSONExtractKey(...)` in ClickHouse mentioned in the [documentation](https://clickhouse.tech/docs/en/sql-reference/functions/json-functions/#isvalidjsonjson).

I will give an example code from the documentation section:
> SELECT JSONExtractKey('{"a": "hello", "b": [-100, 200.0, 300]}', 1) = 'a'
> SELECT JSONExtractKey('{"a": "hello", "b": [-100, 200.0, 300]}', 2) = 'b'

When I run any query using `JSONExtractKey(...)` function, I get the following exception (`Unknown function JSONExtractKey`):
```log
SQL Error [46]: ClickHouse exception, code: 46, host: clickhouse-main-01.prod.local.city-dt.ru, port: 8125; Code: 46, e.displayText() = DB::Exception: Unknown function JSONExtractKey. Maybe you meant: ['JSONExtractRaw','JSONExtract'] (version 20.8.3.18 (official build))
```

I use ClickHouse `20.8.3.18` version.

Could you please tell me whether you plan to implement this `JSONExtractKey(...)` function?

Thanks in advance.

**Comment by den-crane** [comment]
You can use JSONExtractKeysAndValuesRaw or JSONExtractKeysAndValues

```
SELECT JSONExtractKeysAndValuesRaw('{"a": "hello", "b": [-100, 200.0, 300]}')[1].1 = 'a' res
┌─res─┐
│   1 │
└─────┘
```

**Comment by den-crane** [comment]
https://github.com/ClickHouse/ClickHouse/pull/5124#issuecomment-490968666

ah, yes. Documentation should be fixed.

**Comment by Melchizedek13** [comment]
@den-crane thanks a lot for information!

It's a good way to get what I need:
> SELECT JSONExtractKeysAndValuesRaw('{"a": "hello", "b": [-100, 200.0, 300]}')[1].1 = 'a' res

**Comment by melvynator** [comment]
We do have a documentation for it now: https://clickhouse.com/docs/en/sql-reference/functions/json-functions#jsonextractkeys and the function should be there
