### ISSUE TITLE
Code: 79, e.displayText() = DB::Exception: MergeTree storages require data path

### ISSUE THREAD

**Issue by candledragle** [ClickHouse/ClickHouse#16460]
test> CREATE TABLE heros1 ENGINE = MergeTree ORDER BY id AS SELECT * FROM mysql('192.168.159.130:3306', 'test', 'heros', 'root', 'root')
[2020-10-28 15:26:00] Code: 79, e.displayText() = DB::Exception: MergeTree storages require data path (version 20.10.2.20 (official build))

**Comment by tavplubix** [comment]
I cannot reproduce the issue in my environment, could you please provide more information?

Do you have some unusual configuration parameters?
Is it exception from `clickhouse-server` or `clickhouse-local`?
Do you use ClickHouse from official repository or some custom build?
`select * from system.databases`
`select currentDatabase()`

**Comment by tavplubix** [comment]
Related: #11035

**Comment by zhouquan2016** [comment]
DB ENGINE MySQL May not support table engine MergeTree,try to change your DB ENGINE to Atomic!
