### ISSUE TITLE
Possibility of a macro pre-processor for queries as part of the database ?

### ISSUE THREAD

**Issue by George3d6** [ClickHouse/ClickHouse#1646]
**Usecase:**

One thing I really like about clickhouse is it's SQL language, I've sometimes been able to replace what would be complex relational logic with clever queries on a single table and possibly some dictionary lookups.

However the one disadvantage to my style of work is that I end up writing a lot of auxiliary functions in whatever language the infrastructure I'm working on is written, to generate some complex queries.

This is fine when a single backend is calling the database but once I get into adjusting multiple backends to use the same database and having to do manual data "debugging" based on the queries issued from said backends, I start finding the fact that a lot of the query logic is in code quite annoying.

**Proposal**

Whilst I understand that user defined functions may be held of by putting some finishing touches on the database, I think that having an optional macro processor wouldn't affect development much and might encourage people to use some of the more advanced features of the database.

Initially I though it may be hard to implement due to the query processing logic, but after a bit of messing around with the client it seems that it would be quite easy to put the queries through a macro pre-processor, example: 

https://github.com/George3d6/ClickHouse/blob/macro/dbms/src/Server/Client.cpp#L583
(base on 1.1.54310, since it's stable but quite new and compiles easily on my distro)

These changes allow me to write queries like this:

_Export macro_
`$#timeseries=arrayMap( x -> toDateTime(x), arrayMap( x -> toUnixTimestamp($1) + x*$3, range( toUInt64(toUnixTimestamp($2)/$3 - toUnixTimestamp($1)/$3)  )) )`
_Exectue query_
`SELECT arrayJoin(#timeseries$(now() - 9000)$now()$120#) as time`

So I can have more complex query logic that comes into play a lot for my usecases (e.g. timeseries queries) as part of the database itself.

The implementation I have currently is obviously fugly and a bit buggy, I just did it so see if it would be easily doable, but I think that with a single reserved character(e.g. #). With a syntax that could be something like this:

`#macro_name=impl($arg1,$arg2) + impl2($arg3);`
`SELECT blah #my_macro(foo,bar,blax)# blah;`

Would there be any interest in having something like this implemented ?

If yes, how would the syntax have to look for it to be compatible with future changes ?

If not, are there any plans for implementing it on your end in the future or any reasons why you believe it's better left unimplemented ?

P.S: I looked to see if I can find an experimental macro system anywhere in there or a thread on the topic but I couldn't. If there is one already I apologize for creating a new one

**Comment by alexey-milovidov** [comment]
It should be partially solved by:
- WITH clause;
- upcoming support for SQL UDFs.

It is in question should we have a generic macro preprocessor.
I'm against adding syntax-agnostic preprocessor like C-preprocessor, m4 or Jinja into ClickHouse.
But it can be easily implemented in middleware.
