### ISSUE TITLE
Clickhouse create broken symlink for buffer table

### ISSUE THREAD

**Issue by stufently** [ClickHouse/ClickHouse#16482]
Clickhouse from official repo on ubuntu 20.04
clickhouse-server                    20.10.2.20

After create buffer table with name clickhouse_queries_buffer  I see broken symlink from
/var/lib/clickhouse/data/default/clickhouse_queries_buffer
to
/var/lib/clickhouse/store/2a2/2a2feebd-c088-4335-8a36-f92af98f4616

maybe its features

**Comment by alexey-milovidov** [comment]
This behaviour is Ok but can be improved.
