### ISSUE TITLE
clickhouse latest version with ProtobufSingle  problem

### ISSUE THREAD

**Issue by lddlww** [ClickHouse/ClickHouse#16511]
i found document https://clickhouse.tech/docs/en/interfaces/formats/ contains ```ProtobufSingle``` info，however in repo https://repo.clickhouse.tech/rpm/stable/x86_64/  the latest version is ```20.10.3.30```，this version contains nothing with ```ProtobufSingle``` info in docs；am i missing something？

**Comment by alexey-milovidov** [comment]
It's available in the latest testing ("nighly" build), version 20.11.
