### ISSUE TITLE
Different materialized view behavior for different clickhouse version using same sql

### ISSUE THREAD

**Issue by ahutsunshine** [ClickHouse/ClickHouse#16517]
**Describe the bug**
When creating materialized view and corresponding inner table, there are different behaviors for inserting data with same created sql for different clickhouse version. 
For 19.16.14.65 version, there will be the below exception when inserting data `insert into sherlockio.sherlock_test(name, unixtime, course, score) values('Tom',now(), 'Math', 95)`. But for `20.6.8.5` version,  it works for inserting.
```
Code: 70. DB::Exception: Received from localhost:9000. DB::Exception: Conversion from AggregateFunction(min, Float64) to  
 AggregateFunction(min, Nullable(Float64)) is not supported: while converting source column score_min to destination column score_min: while pushing to view sherlockio.amlsrmservice_materilizedview_deyitest.
```
 
**How to reproduce**
There are three tables sherlock_test(concrete table), sherlock_test_inner(inner table)  and sherlock_test_materializedview(materialized view table).  Create these three tables in two clickhouse version to watch its behavior with inserting data.

Insert sql: `insert into sherlockio.sherlock_test(name, unixtime, course, score) values('Tom',now(), 'Math', 95)`

sherlock_test:
```
CREATE TABLE sherlockio.sherlock_test (`unixtime` DateTime('Etc/UTC'), `name` Nullable(String), `course` Nullable(String), `score` Nullable(Float64), `class` Nullable(Int64)) ENGINE = ReplicatedMergeTree('/clickhouse/{installation}/{cluster}/tables/{shard}/{database}/{table}', '{replica}') PARTITION BY toYYYYMMDD(unixtime) ORDER BY (unixtime) SETTINGS index_granularity = 8192
```
sherlock_test_inner:
```
CREATE TABLE sherlockio.sherlock_test_inner (`unixtime` DateTime('Etc/UTC'), `name` String, `score_min` AggregateFunction(min, Nullable(Float64)), `score_average` AggregateFunction(avg, Nullable(Float64)), `_count_` AggregateFunction(count), `score_sum` AggregateFunction(sum, Nullable(Float64))) ENGINE = ReplicatedSummingMergeTree('/clickhouse/{installation}/{cluster}/tables/{shard}/{database}/{table}', '{replica}') PARTITION BY toYYYYMMDD(unixtime) ORDER BY (unixtime, name) SETTINGS index_granularity = 8192
```
sherlock_test_materializedview:
```
CREATE MATERIALIZED VIEW sherlockio.sherlock_test_materializedview TO sherlockio.sherlock_test_inner (`unixtime` DateTime('Etc/UTC'), `name` String,  `score_min` AggregateFunction(min, Nullable(Float64)), `score_average` AggregateFunction(avg, Nullable(Float64)), `_count_` AggregateFunction(count), `score_sum` AggregateFunction(sum, Nullable(Float64))) AS SELECT toStartOfMinute(unixtime) AS unixtime, name, minState(score) AS score_min, avgState(score) AS score_average, countState() AS _count_, sumState(score) AS score_sum FROM sherlockio.sherlock_test GROUP BY (unixtime, name)
```

* Which ClickHouse server version to use
Two versions:
1. `19.16.14.65` version
2. `20.6.8.5` version

*  Question
Seems  the  creating logic for materialized view.  Why happened this? What's the expected now?

**Comment by den-crane** [comment]
CH started to support Nullable aggregateFunction since 20.5.2.7

19.16.14.65 , 20.6.8.5 both are out of support!

Supported versions 20.3.20.6 (LTS) , 20.8.5.45 , 20.9.4.76, 20.10.3.30

Probably you should upgrade and use 20.10.3.30

**Comment by ahutsunshine** [comment]
@den-crane Can you give me the release logs for this? 
1. What's the reason to support such case which changed the behavior  and why didnt support before?
2. We can use the `Nullable` feature in `20.6.8.5`. What do you mean `19.16.14.65, 20.6.8.5 both are out of support`?

**Comment by den-crane** [comment]
https://github.com/ClickHouse/ClickHouse/blob/master/CHANGELOG.md#clickhouse-release-v20527-stable-2020-07-02
It was implemented here :
_Return non-Nullable result from COUNT(DISTINCT), and uniq aggregate functions family. If all passed values are NULL, return zero instead. This improves SQL compatibility. #11661 (alexey-milovidov)._

>What's the reason to support such case which changed the behavior and why didnt support before?

AggregateFunctions did not support Nullable values before 20.5.2.7. It was not implemented.

>What do you mean 19.16.14.65, 20.6.8.5 both are out of support

It means they life-cycle is ended and they are obsolete.
