### ISSUE TITLE
when i used kill query where query_id='xxxx',it is not useful

### ISSUE THREAD

**Issue by yzydtc** [ClickHouse/ClickHouse#16512]
situation:
I want to droping a tablembut it failed.
I use show processlist,it has few processes
I use kill query command to killing these processes,it failed
How can i kill these processes?

reproduce:
clickhourse_version:version 20.3.10.75

create_table_statement:
CREATE TABLE log_center.consumer_log_user_behavior_info_v3 
(`dateline` UInt64 COMMENT '发生时间',`user_info` String COMMENT '用户信息') 
ENGINE = Kafka('hadoop1:9092,hadoop2:9092,hadoop3:9092, 'etl_online_data_001_1', 'etl_online_data_001_consumer_group_5') SETTINGS kafka_format = 'JSONEachRow', kafka_num_consumers = 4

show_processlist_info:
1	default	64b30cdd-adbc-46f3-b015-08109b4f42ec	::ffff:172.31.0.4	60052	default	64b30cdd-adbc-46f3-b015-08109b4f42ec	::ffff:hadoop4	60052	2				0	0	0	0	2	Apache-HttpClient/4.5.2 (Java/1.8.0_231)		106118.023	1	0	0	0	0	0	0	4197700	drop table if exists log_center.consumer_log_user_behavior_info_v3	248478	['Query','IOBufferAllocs','IOBufferAllocBytes','ContextLock']	[1,4,4194364,11]	['extremes','use_uncompressed_cache','load_balancing','max_memory_usage']	['0','0','random','10000000000']

**Comment by alexey-milovidov** [comment]
It is not possible to kill DDL (CREATE, DROP, RENAME...) queries.

The issue with DROP query is related to deadlock in Kafka engine. I assign @filimonov as Kafka expert.

**Comment by filimonov** [comment]
Yes. There is known issue in older versions of ClickHouse - when DROP of kafka table can hang.
see #11145  #10910 #15473

Please update to 20.8 or newer.
