### ISSUE TITLE
maxMap is removing entries with empty string or zero value

### ISSUE THREAD

**Issue by mrodonnpaw** [ClickHouse/ClickHouse#16510]
**Describe the unexpected behaviour**
maxMap is removing entries with empty string or zero value.

**How to reproduce**

*String array*
```
SELECT maxMap(a, b) from values ('a Array(String), b Array(String)',(['A'],['']),(['B'],['']));

┌─maxMap(a, b) ─┐
│ ([],[]) │
└───────────┘
```

*Numeric array*
```
SELECT maxMap(a, b) from values ('a Array(String), b Array(UInt64)',(['A'],[0]),(['B'],[0]));

┌─maxMap(a, b) ─┐
│ ([],[]) │
└───────────┘
```

*Numeric array with negative value*

```
SELECT maxMap(a, b) FROM values('a Array(String), b Array(Int64)', (['A'], [0]), (['B'], [-1]))

┌─maxMap(a, b)─┐
│ (['B'],[-1]) │
└──────────────┘
```

It happens with all versions published.

**Expected behavior**
We expect this to maintain those keys with its value (empty string or zero).

**Comment by alexey-milovidov** [comment]
@ildus The behaviour comes from `sumMap` function that was specifically made this way. But it does not make sense for `minMap`, `maxMap`.

**Comment by den-crane** [comment]
duplicate for https://github.com/ClickHouse/ClickHouse/issues/16087

**Comment by Algunenano** [comment]
Fixed in https://github.com/ClickHouse/ClickHouse/pull/16631
