### ISSUE TITLE
Process killed by  Memory limit (total) exceeded

### ISSUE THREAD

**Issue by xiashaohua** [ClickHouse/ClickHouse#16537]
i start my process 2 hours,only commit not query。

<max_server_memory_usage_to_ram_ratio>0.8</max_server_memory_usage_to_ram_ratio>
server RAM :32g

the error is :
2020.10.29 23:45:16.320714 [ 10473 ] {171eac9e-a25d-45b0-bd59-7ee8f6533105} <Error> executeQuery: Code: 241, e.displayText() = DB::Exception: Memory limit (total) exceeded: would use 24.72 GiB (attempt to allocate chunk of 5075574 bytes), maximum: 24.71 GiB (version 20.7.1.1) (from 127.0.0.1:56612) (in query: INSERT INTO 

0. std::exception::capture() @ 0x66c630e in /usr/bin/clickhouse
1. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x8bff4d4 in /usr/bin/clickhouse
2. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x54039a1 in /usr/bin/clickhouse
3. MemoryTracker::alloc(long) @ 0x53ec389 in /usr/bin/clickhouse
4. MemoryTracker::alloc(long) @ 0x53ec3c5 in /usr/bin/clickhouse
5. MemoryTracker::alloc(long) @ 0x53ec3c5 in /usr/bin/clickhouse
6. MemoryTracker::alloc(long) @ 0x53ec3c5 in /usr/bin/clickhouse
7. Allocator<false, false>::realloc(void*, unsigned long, unsigned long, unsigned long) @ 0x5413acc in /usr/bin/clickhouse
8. void DB::PODArrayBase<1ul, 4096ul, Allocator<false, false>, 15ul, 16ul>::resize<>(unsigned long) @ 0x549cde5 in /usr/bin/clickhouse
9. ? @ 0x763ac77 in /usr/bin/clickhouse
10. DB::DataTypeString::deserializeBinaryBulk(DB::IColumn&, DB::ReadBuffer&, unsigned long, double) const @ 0x763b3fc in /usr/bin/clickhouse
11. DB::NativeBlockInputStream::readData(DB::IDataType const&, DB::IColumn&, DB::ReadBuffer&, unsigned long, double) @ 0x7b080a4 in /usr/bin/clickhouse
12. DB::NativeBlockInputStream::readImpl() @ 0x7b087da in /usr/bin/clickhouse
13. DB::IBlockInputStream::read() @ 0x75e1883 in /usr/bin/clickhouse
14. DB::TCPHandler::receiveData(bool) @ 0x7a1d63b in /usr/bin/clickhouse
15. DB::TCPHandler::receivePacket() @ 0x7a1dbf1 in /usr/bin/clickhouse
16. DB::TCPHandler::readDataNext(unsigned long const&, int const&) @ 0x7a1e0b3 in /usr/bin/clickhouse
17. DB::TCPHandler::readData(DB::Settings const&) @ 0x7a1e388 in /usr/bin/clickhouse
18. DB::TCPHandler::processInsertQuery(DB::Settings const&) @ 0x7a1e586 in /usr/bin/clickhouse
19. DB::TCPHandler::runImpl() @ 0x7a1f371 in /usr/bin/clickhouse
20. DB::TCPHandler::run() @ 0x7a203b1 in /usr/bin/clickhouse
21. Poco::Net::TCPServerConnection::start() @ 0x7e331bb in /usr/bin/clickhouse
22. Poco::Net::TCPServerDispatcher::run() @ 0x7e335b1 in /usr/bin/clickhouse
23. Poco::PooledThread::run() @ 0x8c2dc4a in /usr/bin/clickhouse
24. Poco::ThreadImpl::runnableEntry(void*) @ 0x8c2ced4 in /usr/bin/clickhouse
25. start_thread @ 0x7ea5 in /lib64/libpthread-2.17.so
26. clone @ 0xfe8dd in /lib64/libc-2.17.so

run   select metric,':', formatReadableSize(value) from system.metrics where metric like 'MemoryTracking' the result is:

┌─metric─────────┬─':'─┬─formatReadableSize(value)─┐
│ MemoryTracking │ :   │ 24.71 GiB                 │
└────────────────┴─────┴───────────────────────────┘

but the real RAM usage is less than 100M, What caused the problem. thanks

**Comment by azat** [comment]
> i start my process 2 hours,only commit not query。

Not sure what "only commit" means, but:

>2020.10.29 23:45:16.320714 [ 10473 ] {171eac9e-a25d-45b0-bd59-7ee8f6533105} executeQuery: Code: 241, e.displayText() = DB::Exception: Memory limit (total) exceeded: would use 24.72 GiB (attempt to allocate chunk of 5075574 bytes), maximum: 24.71 GiB (version 20.7.1.1) (from 127.0.0.1:56612) (in query: INSERT INTO

There were some significant improvements in the memory tracking, the most relevant for this issue is - #16121

**Comment by xiashaohua** [comment]
> > i start my process 2 hours,only commit not query。
> 
> Not sure what "only commit" means, but:
> 
> > 2020.10.29 23:45:16.320714 [ 10473 ] {171eac9e-a25d-45b0-bd59-7ee8f6533105} executeQuery: Code: 241, e.displayText() = DB::Exception: Memory limit (total) exceeded: would use 24.72 GiB (attempt to allocate chunk of 5075574 bytes), maximum: 24.71 GiB (version 20.7.1.1) (from 127.0.0.1:56612) (in query: INSERT INTO
> 
> There were some significant improvements in the memory tracking, the most relevant for this issue is - #16121
> 
> P.S. label memory is required

Insert only no select。and the phenomenon is not stable, sometimes appear in a few hours, sometimes not appear in a few days

**Comment by den-crane** [comment]
@xiashaohua 20.7 is obsolete. Try 20.8.5.45

**Comment by den-crane** [comment]
It seems this issue will be fixed in the next stable release 20.11

**Comment by den-crane** [comment]
20.7.1.1 -- is obsolete and not stable. You need to upgrade at least to 20.7.4.11. Or better to 20.8.5.45.

**Comment by xiashaohua** [comment]
> 20.7.1.1 -- is obsolete and not stable. You need to upgrade at least to 20.7.4.11. Or better to 20.8.5.45.

thanks,i will  update to a stable version
