### ISSUE TITLE
can't load ontime dataset

### ISSUE THREAD

**Issue by lambgong** [ClickHouse/ClickHouse#16539]
Document url as follow:
https://clickhouse.tech/docs/en/single/?query=internal_replication#ontime

Run the following code according to the document：
```
for i in *.zip; do echo $i; unzip -cq $i '*.csv' | sed 's/\.00//g' | clickhouse-client --host=*.*.*.* --query="INSERT INTO ontime FORMAT CSVWithNames"; done
```

Get error as follow:
![image](https://user-images.githubusercontent.com/32842606/97658535-77ff1b00-1aa7-11eb-8c7a-bbe77691c972.png)

It seems like the table schema don't match the data

**Comment by den-crane** [comment]
What CH version did you use?

**Comment by alexey-milovidov** [comment]
@lambgong I have edited the instruction accordingly: https://github.com/ClickHouse/ClickHouse/commit/7986dbdfc7a6b57e9924171b46ca9899beb2ad8c
