### ISSUE TITLE
 Mutation "alter table .. delete" completes successfully without deleting data

### ISSUE THREAD

**Issue by sibilkov** [ClickHouse/ClickHouse#16532]
Hello, I have a problem with the mutations. There is a replicated table with 5.5 million old rows. I want to remove them on one of the replicas using mutations: 
`alter table database.statistics delete where provider_id = 301 and channel_id = 0 and date> = '2016-07-01' and date <'2016-08-01'; `
I get an answer 
`0 rows in set. Elapsed: 0.058 sec. `
But at the same time, count() shows 5.5 million rows for the same request conditions. This query is added to the mutation table, where it is marked as completed (`is_done = 1; parts_to_do = 0`). The `block_numbers.partition_id` field is not empty (actually, there is a list of ~70 partitions), as I can understand something has to be executed, but all these records still exist. 
Of course, I tried to ask for advice in the "Кликхаус не тормозит" community, but we could not find the any reasons for this problem. And there were other users (on the different CH versions) who faced the same problem so that this might be a bug.
How can I figure out the reasons for this?

CH version: 20.3.19.4
database.statistics is large ReplicatedCollapsingMergeTree table contains mostly integer values.
Thank you :)

**Comment by den-crane** [comment]
probably the table is corrupted https://github.com/ClickHouse/ClickHouse/issues/9019

**Comment by alesapin** [comment]
> probably the table is corrupted #9019

Can you show your `CREATE TABLE` query? Index corruption during mutation is an extremely rare bug which was quickly fixed. But if it happened to you, not the whole table is currupted, but only the index. You can insert select all data to another table and try to delete data again.

**Comment by alex-karo** [comment]
Seems to I have the same bug with index corruption.
Prerequisites:
1) Table, that ALTER'ed before (on tables, than never changed, everything is fine). 
2) Update clickhouse version from 19.8.3.8 to 20.9.3.45
3) Move data to replicated table via official guide (move/attach partitions)
I checked, only version update doesn't get this effects.

**Comment by alex-karo** [comment]
One of corrupted tables
```
CREATE TABLE kline
(
    `date` Date,
    `time` DateTime,
    `exchangeId` UInt16,
    `tickerId` UInt32,
    `base` String,
    `quote` String,
    `high` Nullable(Decimal(38, 12)),
    `low` Nullable(Decimal(38, 12)),
    `open` Nullable(Decimal(38, 12)),
    `close` Nullable(Decimal(38, 12)),
    `volume` Decimal(38, 8),
    `period` UInt16
)
ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{shard}/kline', '{replica}')
PARTITION BY (toYYYYMM(date), period)
ORDER BY (tickerId, period, time)
SETTINGS index_granularity = 8192
```

**Comment by atercattus** [comment]
We have a similar problem with ReplicatedAggregatingMergeTree table with CH version v20.11.2.1-stable (and at earlier version too).

Neither CHECK TABLE nor DETACH/ATTACH helps. There are no frozen parts, active merges, replication queue.

The only solution: copy the whole partition to the temporary table, drop the partition, and copy data back to the original table.

**Comment by den-crane** [comment]
@atercattus probably you can simply re-merge that partition. Optimize table .. partition id ... final

**Comment by atercattus** [comment]
@den-crane 
It doesn't help either.

**Comment by den-crane** [comment]
@atercattus I think you should share such part with @alesapin

**Comment by atercattus** [comment]
@den-crane I can write to him on Telegram.
But I definitely can't share this partition as is (it contains 106G of our sensitive NDA data :) ). Also, we have a problem with this whole table, not only with one partition.
But I'm ready to do something for testing purposes.

**Comment by atercattus** [comment]
@den-crane Also may be useful.

On replica_num 2 optimize partition elapses for ~1 hour, but replica_num 1 does it instantly: "Ok. 0 rows in set. Elapsed: 0.005 sec.". Both replicas have the same partition 202005_46_51_3_50694.

**Comment by den-crane** [comment]
Do you use clickhouse-backup ? freeze+attach part ? 
could be related to https://github.com/ClickHouse/ClickHouse/issues/18804
