### ISSUE TITLE
[Feature Request] Pivoting Table Engine 

### ISSUE THREAD

**Issue by iShift** [ClickHouse/ClickHouse#1655]
Clickhouse is best for collecting metrics, but metrics usualy come as short table example: 
(example - you get metric from some device, than push it to clickhouse)

![image](https://user-images.githubusercontent.com/426427/34068846-4413f1dc-e254-11e7-8702-8fc80267b4bd.png)

But columnar DB should save them as long table (for perfomance) for now - if you want to convert short table for long one - you need collector  server + script, that transform metrics, when you have distributed arcitecture it is big problem, because some of metrics (from same device) can be handle on one server and another - on second server. Also that add time lag for adding metric (collector should wait all metric for device and after that - insert it).

**I have an idea how to solve that problem.**

Clickhouse should have Pivoting table (like pivot function in MSSQL/Oracle) but it should be not function - it should be table type.  When we create that table type - we set some settings for that engine:

1. static colums (that dont pivoting)
2. Dynamic colums (that pivoting)
3. Backend engine (MergeTree/ReplicatedMergeTree/etc)

![image](https://user-images.githubusercontent.com/426427/34068879-13a9118e-e255-11e7-8f9d-57d6b69e370a.png)

So, if we insert sample table (from my example) clickhouse:

1. Scan incoming rows
2. Find that last 2 colums are dynamic and get that **metric name** are generator column and **metric result** are result column
3. Clickhouse scan table that we have, and look for columns with name in  **metric name**
4. If we have it - add rows to table
5. If not - ALTER table and add new columns then - insert rows

As a result we get that table automaticaly:
![image](https://user-images.githubusercontent.com/426427/34068913-f8895354-e255-11e7-9e4e-864e3bc3f01c.png)

And if clickhouse get new metric (new name in DYNAMIC column) - it ALTER table adding new column, than add new metric.

That function can gain huge performance for metrics usage case (when you have distributed collection network) and when you dont know what metrics you should collect tomorrow =) 

_Russian translation of that:
Очень бы хотелось иметь движок таблиц который позволит на вход принимать два параметра - статический набор колонок (обычные колонки) и две динамические.

Первая динамическая колонка будет являться генератором колонок, а вторая колонка - значение для первой (наглядно можно посмотреть на таблицах выше). 

Другими словами - когда к вам поступает метрики в формате узкой таблицы и чтобы не создавать структуру таблиц под определенный набор метрик - можно будет посылать метрики в универсальном узком формате, а clickhouse уже сам будет создавать нужные колонки (ALTER TABLE) и писать в них нужные данные.

Это очень полезно в том кейсе когда идет распределенная обработка файлов которые в дальнейшем заливаются в clickhouse. Или когда сегодня не известно что завтра собирать надо сильно больше данных. Тк если хранить в узкой таблице - это не оптимально с точки зрения архитектуры CH, если же делать широкую таблицу - то при добавлении метрики надо будет переписывать скрипт который посылает данные в CH + руками делать ALTER.

И да, тут нужно использовать или replacing движок или update тк строки могут приходить не равномерно =)_

**Comment by andrusha** [comment]
If you make your `Dynamic.X` a nested table, then you could do `arrayElement(indexOf(` to put specific key as a column manually.

**Comment by l1t1** [comment]
it this function realized?

**Comment by seanlaff** [comment]
I've discovered there is a way to do something along these lines with the aggregate function combinators https://clickhouse.com/docs/en/sql-reference/aggregate-functions/combinators

```sql
CREATE TABLE mytable(timestamp DateTime, device_id String, metric_name String, metric_value Float64) ENGINE=MergeTree ORDER BY tuple()

INSERT INTO mytable VALUES
    ('2021-10-28 00:00:00', 'device1', 'CPU', 55),
    ('2021-10-28 00:00:00', 'device1', 'Memory', 1001),
    ('2021-10-28 00:00:00', 'device2', 'CPU', 98),
    ('2021-10-28 00:00:00', 'device2', 'Memory', 888),
    ('2021-10-28 00:05:00', 'device1', 'CPU', 56),
    ('2021-10-28 00:05:00', 'device1', 'Memory', 1001),
    ('2021-10-28 00:05:00', 'device2', 'CPU', 99),
    ('2021-10-28 00:05:00', 'device2', 'Memory', 889)

SELECT timestamp, groupArrayMap(map(device_id, map(metric_name, metric_value))) FROM mytable GROUP BY timestamp
```
```
┌───────────timestamp─┬─groupArrayMap(map(device_id, map(metric_name, metric_value)))──────────────────┐
│ 2021-10-28 00:00:00 │ {'device1':[{'CPU':55},{'Memory':1001}],'device2':[{'CPU':98},{'Memory':888}]} │
│ 2021-10-28 00:05:00 │ {'device1':[{'CPU':56},{'Memory':1001}],'device2':[{'CPU':99},{'Memory':889}]} │
└─────────────────────┴────────────────────────────────────────────────────────────────────────────────┘
```
You can shuffle around whether you want to group by timestamp as I did, or by device_id (if you want a row per device with maps of metric_name->(timestamp, metric_value).

Not exactly what OP is asking for, but gets you closer

**Comment by ReferenceFrame** [comment]
it will be the great feature

**Comment by alexey-milovidov** [comment]
It is not possible to implement a true pivoting table engine, as the structure of every query pipeline step (the number of columns, their data types as well as the values of constant expressions) should be determined beforehand.
