### ISSUE TITLE
Support for "Format sqlite"

### ISSUE THREAD

**Issue by siradjev** [ClickHouse/ClickHouse#16564]
**Use case**
SQLite is a frequently used format for internal data in many tools, Complex Event Processing (CEP) and Event Stream Processing (ESP) engines, ETL processes as an interim persistence method. It would be good if CH allows direct insert from SQLite database tables as a single batch, as well as export to SQLite, as well as support using File and URL engines. 

**Describe the solution you'd like**

```
select * from my table Format SQLite
```

```
cat filename.sqlite | clickhouse-client --query="INSERT INTO some_table FORMAT SQLite"
```

```
CREATE TABLE file_engine_table (name String, value UInt32) ENGINE=File(SQLite)
```

**Describe alternatives you've considered**
Currently it is always required to make format change, and given both SQLITE reading and CH inserts are very efficient, it shall provide great benefit.

**Comment by l1t1** [comment]
does sqlite have a command line to convert it to a csv?

**Comment by l1t1** [comment]
and a sqlite datafile may include many tables, you cannot convert it to a table, but a database

**Comment by l1t1** [comment]
full steps
```sql
# sqlite3 test.sqlite
SQLite version 3.7.17 2013-05-20 00:56:22
Enter ".help" for instructions
Enter SQL statements terminated with a ";"
sqlite> create table a as select 'tom' name, 10 age union select 'apple',11;
sqlite> .exit

#  clickhouse-client --query="create table some_table (a String, b Int8) ENGINE=Log"
# sqlite3 -noheader  -separator ',' test.sqlite "select * from a" | clickhouse-client --query="INSERT INTO some_table FORMAT CSV"
#  clickhouse-client --query="select * from some_table"
apple   11
tom     10
```

**Comment by l1t1** [comment]
even use a sql instead of a datafile
```
# sqlite3 -noheader  -separator , :memory: "select 'jerry' name, 9 age union select 'ox',1"
jerry,9
ox,1
# sqlite3 -noheader  -separator , :memory: "select 'jerry' name, 9 age union select 'ox',1"| clickhouse-client --query="INSERT INTO some_table FORMAT CSV"
#  clickhouse-client --query="select * from some_table"
apple   11
tom     10
jerry   9
ox      1
```

**Comment by siradjev** [comment]
thanks @l1t1 for examples!
So the main idea is to do it simpler, similar to CSV, TSV, Parquet, ORC, (they all have similar command line tools, but having it working as part of clickhouse binary provides much better efficiency).

**Comment by alexey-milovidov** [comment]
@siradjev Do you want to have support for data export as SQLite database with a single table and data import of single table from SQLite database?

**Comment by alexey-milovidov** [comment]
We will collect "likes" to this task to estimate the demand. If you need this feature, add "thumbs up" reaction to the first message.

**Comment by siradjev** [comment]
> @siradjev Do you want to have support for data export as SQLite database with a single table and data import of single table from SQLite database?

Yes. Pretty much that. Ability to get data from single table (would be good to specify tablename somehow) and output an sqlite database with single table.

**Comment by alexey-milovidov** [comment]
SQLite table engine and database engine have been implemented by @kssenii.
Now you can use them to import and export data to SQLite and query SQLite tables directly in ClickHouse.
