### ISSUE TITLE
allow reading from a SET storage

### ISSUE THREAD

**Issue by silviucpp** [ClickHouse/ClickHouse#1656]
Hello guys,

Any reason from not allowing reading from a storage of type Set ? Right now a storage of Set type can be used only with an IN clause.

For example I have the following scenario: I need to run a query on table A based on different filters and get from there all unique users, then in the app I need to know which are this users and also I need to run a second query on another table where one of the filter is user_id IN (result from query A).

Right now from what I see the only option is:

1. do first query like : SELECT DISTINCT user_id FROM table_a WHERE ...
2. process the list in my app (let`s say send them an email)
3. run second query like : SELECT a,b,c,d FROM table2 where user_id IN (same query like in point 1) AND ..

This is not optimal as time query from point 1 will run twice.

In my mind the optimal way is :

1. do first query and save result in a SetStorage
2. read all data from the set storage in the app 
3. run second query and in IN clause add the set storage as input

Are you interested in a PR that will add read support for set storage ? Or do you see any other way to implement what I need without running query 1 two times

Silviu

**Comment by alexey-milovidov** [comment]
Look at `SetVariants.h`.
Extracting keys back from Set is possible for all methods except `hashed`.
So, it is possible to implement reading from Set for most all cases.
Even more, if you need to read from Set, you can implement `concat` or `serialized` methods as it is done in Aggregator (look at `Aggregator.h`).

**Comment by alexey-milovidov** [comment]
> Or do you see any other way to implement what I need without running query 1 two times

You can also save the result to a temporary table. Reading from that temporary table and building a set, should be relatively cheap, if the temporary table is not very large.

**Comment by alexey-milovidov** [comment]
> Are you interested in a PR that will add read support for set storage?

Yes, I'm interested (though Set storage is not frequently used feature).
Also I have intent to generalize "key extracting and manipulation" code in `Aggregator`, `Set`, `Join` and `arrayEnumerateUniq`. There are similar, but slightly different code about "how to extract a key from columns to be used in a hash table".

**Comment by silviucpp** [comment]
You totally lost me :) I thought that what I need to do is to:
1. add in Set.h a method to dump the set content into a Block

```c++
Block Set::dumpElements()
{
    std::unique_lock<std::shared_mutex> lock(rwlock);

    if(data_types.empty())
        return Block();

    Block block;
    DataTypePtr type = data_types.at(0);

    for(auto it = ordered_set_elements->begin(); it != ordered_set_elements->end(); ++it)
    {
        ColumnWithTypeAndName col;
        col.type = type;
        col.column = type->createColumnConst(1, *it);
        col.name = "value";
        block.insert(std::move(col));
    }

    return block;
}
```

Add a stream: 

```c++
class SetBlockInputStream : public IProfilingBlockInputStream
{
public:
    SetBlockInputStream(BlocksList list_) :
    list(list_), it(list_.begin()) {}

    String getName() const override { return "Set"; }

    String getID() const override
    {
        std::stringstream res;
        res << "Set(" << &*list.begin() << ", " << &*list.end()<< ")";
        return res.str();
    }

protected:
    Block readImpl() override
    {
        if (it == list.end())
            return Block();

        Block res = *it;
        ++it;
        return res;
    }
private:
    BlocksList list;
    BlocksList::iterator it;
};

```

Then in `StorageSet` to implement the read method

```
BlockInputStreams StorageSet::read(const Names & column_names,
                                             const SelectQueryInfo & ,
                                             const Context & ,
                                             QueryProcessingStage::Enum & processed_stage,
                                             size_t ,
                                             unsigned )
{
    check(column_names);
    processed_stage = QueryProcessingStage::FetchColumns;

    BlocksList list;
    list.push_back(set->dumpElements());

    BlockInputStreams res;
    res.push_back(std::make_shared<SetBlockInputStream>(list));
    return res;
}
```

But I have a feeling I'm on the wrong path :) Also my code gets a bad_alloc in `readImpl` method.. 
Most probably block is no longer valid 

Silviu

**Comment by alexey-milovidov** [comment]
"Ordered set" is created only when the set is used for filtering by primary key.
In other cases, there is no need for ordered set (and it will be too expensive in terms of memory usage).

But there is another way, how to read from Set without using its internal data structure...

StorageSet and StorageJoin create backup in filesystem in Native format - to fill the data structure at server startup. You can look at `StorageSetOrJoinBase::restoreFromFile`. That's trivial :)

**Comment by silviucpp** [comment]
You think this is a good feature ? if not we can close it. I personally don't use it any longer. not sure if others needs it.

**Comment by alexey-milovidov** [comment]
That's good feature. Reading from backup files (with DISTINCT on top) seems fairly straightforward.

**Comment by alex-zaitsev** [comment]
Supporting TRUNCATE for Set tables would be useful as well.

**Comment by alexey-milovidov** [comment]
TRUNCATE is already implemented for Set and Join.

**Comment by alexey-milovidov** [comment]
This task is abandoned.
