### ISSUE TITLE
Support for Hybrid Partitioning using TTL (evolution of multi-volume storage) 

### ISSUE THREAD

**Issue by siradjev** [ClickHouse/ClickHouse#16565]
**Use case**
Clickhouse is used as a main datastore keeping the data for a very long time. Given that "recent" data is frequently queried, it's frequently may be kept as daily partitioned (sometimes even hourly). 
When keeping data for a very long time, historical data is queried much more rarely, and as a result, it simply results in having huge number of files (especially on ultra-wide tables) all of which are being checked on startup. 

**Describe the solution you'd like**
Hybrid partitioning support using TTL or other mechanism would allow to combine multiple partitions into one using different partition key (e.g. monthly). 
Another beneficial thing would be to allow compact parts support after certain TTL. 
Additionally, it would help to have DDL commands to allow combining partitions into one, and turning partitions into compact part via explicit command. 

**Describe alternatives you've considered**
Currently the only alternative is different tables covered by merge engine, or keeping different tables on different nods covered by distributed engine, or some combination of those.

**Comment by UnamedRus** [comment]
>  Additionally, it would help to have DDL commands to allow combining partitions into one, and turning partitions into compact part via explicit command.

related
https://github.com/ClickHouse/ClickHouse/issues/13826
https://github.com/ClickHouse/ClickHouse/issues/8089

**Comment by alexey-milovidov** [comment]
Hybrid partitioning is difficult to implement.
