### ISSUE TITLE
Some Int conversion functions unsupported

### ISSUE THREAD

**Issue by zvonand** [ClickHouse/ClickHouse#16581]
To PR #9404
@Enmk 

Add `toInt128`, `toInt256`, `toUInt256` functions, that are currently unsupported in th PR.

**Comment by den-crane** [comment]
@zvonand you mean?

select toInt128(now64()) 


SELECT toUInt256(now64())

**Comment by zvonand** [comment]
> @zvonand you mean?
> 
> select toInt128(now64())
> 
> SELECT toUInt256(now64())

Yes
But this issue solely concerns PR #9404

**Comment by den-crane** [comment]
я не прикалываюсь :

Interesting question what these function should return in case of dates before 1970. 
Negative number of seconds? And what it should be in case of toUInt256.

**Comment by zvonand** [comment]
> Interesting question what these functions should return in case of dates before 1970.

I guess in case of `Int` it must be a negative number of seconds, like it already is with `toUnixTimestamp64Milli`:

`SELECT toUnixTimestamp64Milli(toDateTime64('1969-12-31 23:59:00', 0, 'UTC'))` gives us `-60000`

Moreover, it already works this way with Int32 and Int64:
`SELECT toInt32(toDateTime64('1970-01-01 06:59:59', 0, 'Asia/Novosibirsk'))` returns `-1`

When it's `UInt64`, `UInt32`, the exception is raised: 
```
SELECT toUInt32(toDateTime64('1970-01-01 06:59:59', 0, 'Asia/Novosibirsk'))

Received exception from server (version 20.5.1):
Code: 407. DB::Exception: Received from localhost:9000. DB::Exception: DateTime64 convert overflow. 
```
In this case the issue is not about returning a valid value, but about adding support for `UInt256` to the PR. At least, the same exception should be raised when date before 1970

**Comment by alexey-milovidov** [comment]
@zvonand the PR #9404 does not cover anything about the experimental 128bit and 256bit types. It's out of scope of that task.

**Comment by alexey-milovidov** [comment]
Conversion between DateTime64 and UInt128, Int128, UInt256, Int256 is not going to be implemented.
