### ISSUE TITLE
Huge .bin files created by clickhouse

### ISSUE THREAD

**Issue by rogeriochaves** [ClickHouse/ClickHouse#16585]
I've been using a very simple clickhouse setup, I run a `yandex/clickhouse-server` docker image, with default config, attached to a docker volume and that's all. This has been running for like a month already, but although there were very very few inserts into the db (less than 100 rows) the docker `_data/store` folder for clickhouse is already at 14G

Digging deeper I see many files like:

1.1G    query_id.bin
1.1G    initial_query_id.bin
530M    ProfileEvents%2EValues.bin

How can I clean this up without loosing data? Also I'd appreciate any links or instructions on how can I debug it better

Thanks!

**Comment by den-crane** [comment]
truncate table system.asynchronous_metric_log;

And you  can disable this logging by 
```
cat /etc/clickhouse-server/conf.d/asynchronous_metric_log_disable.xml
<?xml version="1.0"?>
<yandex>
    <asynchronous_metric_log remove="1">
    </asynchronous_metric_log>
</yandex>
```

**Comment by den-crane** [comment]
And you can disables other loggers

metric_log
query_log
query_thread_log
trace_log

**Comment by den-crane** [comment]
Or you can configure TTL for this tables and remove old records automatically.

**Comment by rogeriochaves** [comment]
it worked perfectly thank you very much! BTW this gist also helped me seeing the tables sizes: https://gist.github.com/sanchezzzhak/511fd140e8809857f8f1d84ddb937015
