### ISSUE TITLE
<Error> executeQuery: Code: 43, e.displayText() = DB::Exception: Illegal type Int64 of last argument for aggregate function with If suffix:

### ISSUE THREAD

**Issue by jjtjiang** [ClickHouse/ClickHouse#16588]
When i use argMaxIf function ，sometimes there will be problems.To be more precise, when I use a smaller amount of data, say 15,000,000 rows of data, I don't get this problem, but when I continue to insert 5,000,000 rows of data, the query sql reports the following error.
When divided into three sql ,three sql separate query HL_LOCK_TYPE,HL_LOCK_STATE,HL_BLOCKEDBY_INT_ID these three fields, is also no problem.
thanks

logs are below:
2020.11.01 18:29:29.947360 [ 160 ] {8c5cab1b-c410-4338-a7e0-4af011c72538} <Error> executeQuery: Code: 43, e.displayText() = DB::Exception: Illegal type Int64 of last argument for aggregate function with If suffix: While executing SourceFromNativeStream (version 20.8.4.11 (official build)) (from [::ffff:10.16.130.50]:52476) (in query: SELECT HL_LOCK_EXT_ID, HL_LOCK_INT_ID, argMaxIf(HL_LOCK_TYPE, offset, Sign > 0) AS HL_LOCK_TYPE, argMaxIf(HL_LOCK_STATE, offset, Sign > 0) AS HL_LOCK_STATE, argMaxIf(HL_BLOCKEDBY_INT_ID, offset, Sign > 0) AS HL_BLOCKEDBY_INT_ID FROM test.hive_locks2 GROUP BY HL_LOCK_EXT_ID, HL_LOCK_INT_ID HAVING sum(Sign) > 0;), Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x18ba03d0 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xe606dad in /usr/bin/clickhouse
2. DB::AggregateFunctionCombinatorIf::transformArguments(std::__1::vector<std::__1::shared_ptr<DB::IDataType const>, std::__1::allocator<std::__1::shared_ptr<DB::IDataType const> > > const&) const @ 0xf8fa4ff in /usr/bin/clickhouse
3. DB::AggregateFunctionFactory::getImpl(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<std::__1::shared_ptr<DB::IDataType const>, std::__1::allocator<std::__1::shared_ptr<DB::IDataType const> > > const&, DB::Array const&, DB::AggregateFunctionProperties&, bool, int) const @ 0x1520b19a in /usr/bin/clickhouse
4. DB::AggregateFunctionFactory::get(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<std::__1::shared_ptr<DB::IDataType const>, std::__1::allocator<std::__1::shared_ptr<DB::IDataType const> > > const&, DB::Array const&, DB::AggregateFunctionProperties&, int) const @ 0x1520b848 in /usr/bin/clickhouse
5. DB::AggregateFunctionFactory::getImpl(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<std::__1::shared_ptr<DB::IDataType const>, std::__1::allocator<std::__1::shared_ptr<DB::IDataType const> > > const&, DB::Array const&, DB::AggregateFunctionProperties&, bool, int) const @ 0x1520af01 in /usr/bin/clickhouse
6. DB::AggregateFunctionFactory::get(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<std::__1::shared_ptr<DB::IDataType const>, std::__1::allocator<std::__1::shared_ptr<DB::IDataType const> > > const&, DB::Array const&, DB::AggregateFunctionProperties&, int) const @ 0x1520b5c1 in /usr/bin/clickhouse
7. ? @ 0x15486aba in /usr/bin/clickhouse
8. std::__1::__function::__func<std::__1::shared_ptr<DB::IDataType const> (*)(std::__1::shared_ptr<DB::IAST> const&), std::__1::allocator<std::__1::shared_ptr<DB::IDataType const> (*)(std::__1::shared_ptr<DB::IAST> const&)>, std::__1::shared_ptr<DB::IDataType const> (std::__1::shared_ptr<DB::IAST> const&)>::operator()(std::__1::shared_ptr<DB::IAST> const&) @ 0x154885a7 in /usr/bin/clickhouse
9. DB::DataTypeFactory::get(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::IAST> const&) const @ 0x154b1efc in /usr/bin/clickhouse
10. DB::DataTypeFactory::get(std::__1::shared_ptr<DB::IAST> const&) const @ 0x154b2525 in /usr/bin/clickhouse
11. DB::DataTypeFactory::get(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const @ 0x154b2714 in /usr/bin/clickhouse
12. DB::NativeBlockInputStream::readImpl() @ 0x15aba47e in /usr/bin/clickhouse
13. DB::IBlockInputStream::read() @ 0x1545e1ad in /usr/bin/clickhouse
14. ? @ 0x16525d5a in /usr/bin/clickhouse
15. DB::ISource::work() @ 0x162b59bb in /usr/bin/clickhouse
16. ? @ 0x162eb140 in /usr/bin/clickhouse
17. ? @ 0x162ef39d in /usr/bin/clickhouse
18. ? @ 0x162efc66 in /usr/bin/clickhouse
19. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xe6345b7 in /usr/bin/clickhouse
20. ? @ 0xe632b03 in /usr/bin/clickhouse
21. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
22. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so

**Comment by jjtjiang** [comment]
Even，when divided into three sql ,three sql separate query HL_LOCK_TYPE,HL_LOCK_STATE,HL_BLOCKEDBY_INT_ID these three fields, is also no problem.

**Comment by jjtjiang** [comment]
When divided into three sql ,three sql separate query HL_LOCK_TYPE,HL_LOCK_STATE,HL_BLOCKEDBY_INT_ID these three fields, is also no problem.

**Comment by den-crane** [comment]
@jjtjiang can you show an output of `desc test.hive_locks2` and `select * from system.settings where changed`

**Comment by jjtjiang** [comment]
@den-crane
DESCRIBE TABLE test.hive_locks2

┌─name────────────────┬─type─────────────┬─default_type─┬─default_expression─┬─comment─┬─codec_expression─┬─ttl_expression─┐
│ HL_LOCK_EXT_ID      │ Int64            │              │                    │         │                  │                │
│ HL_LOCK_INT_ID      │ Int64            │              │                    │         │                  │                │
│ HL_TXNID            │ Nullable(Int64)  │              │                    │         │                  │                │
│ HL_DB               │ Nullable(String) │              │                    │         │                  │                │
│ HL_TABLE            │ Nullable(String) │              │                    │         │                  │                │
│ HL_PARTITION        │ Nullable(String) │              │                    │         │                  │                │
│ HL_LOCK_STATE       │ Nullable(String) │              │                    │         │                  │                │
│ HL_LOCK_TYPE        │ Nullable(String) │              │                    │         │                  │                │
│ HL_LAST_HEARTBEAT   │ Nullable(Int64)  │              │                    │         │                  │                │
│ HL_ACQUIRED_AT      │ Nullable(Int64)  │              │                    │         │                  │                │
│ HL_USER             │ Nullable(String) │              │                    │         │                  │                │
│ HL_HOST             │ Nullable(String) │              │                    │         │                  │                │
│ HL_HEARTBEAT_COUNT  │ Nullable(Int32)  │              │                    │         │                  │                │
│ HL_AGENT_INFO       │ Nullable(String) │              │                    │         │                  │                │
│ HL_BLOCKEDBY_EXT_ID │ Nullable(Int64)  │              │                    │         │                  │                │
│ HL_BLOCKEDBY_INT_ID │ Nullable(Int64)  │              │                    │         │                  │                │
│ offset              │ Int64            │              │                    │         │                  │                │
│ binlog_time         │ Int64            │              │                    │         │                  │                │
│ entry_time          │ DateTime64(3)    │ DEFAULT      │ now64(3)           │         │                  │                │
│ Sign                │ Int8             │              │                    │         │                  │                │
└─────────────────────┴──────────────────┴──────────────┴────────────────────┴─────────┴──────────────────┴────────────────┘



SELECT *
FROM system.settings
WHERE changed

┌─name───────────────────────────────┬─value───────┬─changed─┬─description─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─min──┬─max──┬─readonly─┬─type────────────────┐
│ use_uncompressed_cache             │ 0           │       1 │ Whether to use the cache of uncompressed blocks.                                                                                                    │ ᴺᵁᴸᴸ │ ᴺᵁᴸᴸ │        0 │ Bool                │
│ background_pool_size               │ 20          │       1 │ Number of threads performing background work for tables (for example, merging in merge tree). Only has meaning at server startup.                   │ ᴺᵁᴸᴸ │ ᴺᵁᴸᴸ │        0 │ UInt64              │
│ load_balancing                     │ random      │       1 │ Which replicas (among healthy replicas) to preferably send a query to (on the first attempt) for distributed processing.                            │ ᴺᵁᴸᴸ │ ᴺᵁᴸᴸ │        0 │ LoadBalancing       │
│ log_queries                        │ 1           │       1 │ Log requests and write the log to the system table.                                                                                                 │ ᴺᵁᴸᴸ │ ᴺᵁᴸᴸ │        0 │ Bool                │
│ join_use_nulls                     │ 1           │       1 │ Use NULLs for non-joined rows of outer JOINs for types that can be inside Nullable. If false, use default value of corresponding columns data type. │ ᴺᵁᴸᴸ │ ᴺᵁᴸᴸ │        0 │ Bool                │
│ max_bytes_before_external_group_by │ 2684354560  │       1 │                                                                                                                                                     │ ᴺᵁᴸᴸ │ ᴺᵁᴸᴸ │        0 │ UInt64              │
│ max_bytes_before_external_sort     │ 2684354560  │       1 │                                                                                                                                                     │ ᴺᵁᴸᴸ │ ᴺᵁᴸᴸ │        0 │ UInt64              │
│ max_memory_usage                   │ 5368709120  │       1 │ Maximum memory usage for processing of single query. Zero means unlimited.                                                                          │ ᴺᵁᴸᴸ │ ᴺᵁᴸᴸ │        0 │ UInt64              │
│ max_memory_usage_for_user          │ 6442450944  │       1 │ Maximum memory usage for processing all concurrently running queries for the user. Zero means unlimited.                                            │ ᴺᵁᴸᴸ │ ᴺᵁᴸᴸ │        0 │ UInt64              │
│ input_format_null_as_default       │ 1           │       1 │ For text input formats initialize null fields with default values if data type of this field is not nullable                                        │ ᴺᵁᴸᴸ │ ᴺᵁᴸᴸ │        0 │ Bool                │
│ date_time_input_format             │ best_effort │       1 │ Method to read DateTime from text input formats. Possible values: 'basic' and 'best_effort'.                                                        │ ᴺᵁᴸᴸ │ ᴺᵁᴸᴸ │        0 │ DateTimeInputFormat │
└────────────────────────────────────┴─────────────┴─────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴──────┴──────┴──────────┴─────────────────────┘

**Comment by jjtjiang** [comment]
desc test.hive_locks2
|name|type|default_type|default_expression|comment|codec_expression|ttl_expression|
|----|----|------------|------------------|-------|----------------|--------------|
|HL_LOCK_EXT_ID|Int64||||||
|HL_LOCK_INT_ID|Int64||||||
|HL_TXNID|Nullable(Int64)||||||
|HL_DB|Nullable(String)||||||
|HL_TABLE|Nullable(String)||||||
|HL_PARTITION|Nullable(String)||||||
|HL_LOCK_STATE|Nullable(String)||||||
|HL_LOCK_TYPE|Nullable(String)||||||
|HL_LAST_HEARTBEAT|Nullable(Int64)||||||
|HL_ACQUIRED_AT|Nullable(Int64)||||||
|HL_USER|Nullable(String)||||||
|HL_HOST|Nullable(String)||||||
|HL_HEARTBEAT_COUNT|Nullable(Int32)||||||
|HL_AGENT_INFO|Nullable(String)||||||
|HL_BLOCKEDBY_EXT_ID|Nullable(Int64)||||||
|HL_BLOCKEDBY_INT_ID|Nullable(Int64)||||||
|offset|Int64||||||
|binlog_time|Int64||||||
|entry_time|DateTime64(3)|DEFAULT|now64(3)||||
|Sign|Int8||||||

**Comment by jjtjiang** [comment]
@den-crane This is the result. thanks
desc test.hive_locks2
|name|type|default_type|default_expression|comment|codec_expression|ttl_expression|
|----|----|------------|------------------|-------|----------------|--------------|
|HL_LOCK_EXT_ID|Int64||||||
|HL_LOCK_INT_ID|Int64||||||
|HL_TXNID|Nullable(Int64)||||||
|HL_DB|Nullable(String)||||||
|HL_TABLE|Nullable(String)||||||
|HL_PARTITION|Nullable(String)||||||
|HL_LOCK_STATE|Nullable(String)||||||
|HL_LOCK_TYPE|Nullable(String)||||||
|HL_LAST_HEARTBEAT|Nullable(Int64)||||||
|HL_ACQUIRED_AT|Nullable(Int64)||||||
|HL_USER|Nullable(String)||||||
|HL_HOST|Nullable(String)||||||
|HL_HEARTBEAT_COUNT|Nullable(Int32)||||||
|HL_AGENT_INFO|Nullable(String)||||||
|HL_BLOCKEDBY_EXT_ID|Nullable(Int64)||||||
|HL_BLOCKEDBY_INT_ID|Nullable(Int64)||||||
|offset|Int64||||||
|binlog_time|Int64||||||
|entry_time|DateTime64(3)|DEFAULT|now64(3)||||
|Sign|Int8||||||

select * from system.settings where changed.
|name|value|changed|description|min|max|readonly|type|
|----|-----|-------|-----------|---|---|--------|----|
|use_uncompressed_cache|0|1|Whether to use the cache of uncompressed blocks.|||0|Bool|
|background_pool_size|20|1|Number of threads performing background work for tables (for example, merging in merge tree). Only has meaning at server startup.|||0|UInt64|
|load_balancing|random|1|Which replicas (among healthy replicas) to preferably send a query to (on the first attempt) for distributed processing.|||0|LoadBalancing|
|log_queries|1|1|Log requests and write the log to the system table.|||0|Bool|
|join_use_nulls|1|1|Use NULLs for non-joined rows of outer JOINs for types that can be inside Nullable. If false, use default value of corresponding columns data type.|||0|Bool|
|max_bytes_before_external_group_by|2684354560|1||||0|UInt64|
|max_bytes_before_external_sort|2684354560|1||||0|UInt64|
|max_result_rows|2000|1|Limit on result size in rows. Also checked for intermediate data sent from remote servers.|||0|UInt64|
|result_overflow_mode|break|1|What to do when the limit is exceeded.|||0|OverflowMode|
|max_memory_usage|5368709120|1|Maximum memory usage for processing of single query. Zero means unlimited.|||0|UInt64|
|max_memory_usage_for_user|6442450944|1|Maximum memory usage for processing all concurrently running queries for the user. Zero means unlimited.|||0|UInt64|
|input_format_null_as_default|1|1|For text input formats initialize null fields with default values if data type of this field is not nullable|||0|Bool|
|date_time_input_format|best_effort|1|Method to read DateTime from text input formats. Possible values: 'basic' and 'best_effort'.|||0|DateTimeInputFormat|

**Comment by KochetovNicolai** [comment]
repro:
```
SET max_bytes_before_external_group_by = 200000000;

SET max_memory_usage = 1500000000;
SET max_threads = 12;

SELECT bitAnd(number, pow(2, 20) - 1) as k, argMaxIf(k, number % 2 = 0 ? number : Null, number > 42),  uniq(number) AS u FROM numbers(10000000) GROUP BY k LIMIT 10;

SELECT
    bitAnd(number, pow(2, 20) - 1) AS k,
    argMaxIf(k, if((number % 2) = 0, number, NULL), number > 42),
    uniq(number) AS u
FROM numbers(10000000)
GROUP BY k
LIMIT 10

Query id: 0a6219f1-ff7a-40bd-bfcc-9dc755a04623

→ Progress: 10.02 million rows, 80.18 MB (1.37 million rows/s., 10.96 MB/s.) ███████████████████████████████████ 99%
Received exception from server (version 20.12.1):
Code: 43. DB::Exception: Received from localhost:9000. DB::Exception: Illegal type UInt64 of last argument for aggregate function with If suffix: While executing SourceFromNativeStream. 

```

**Comment by KochetovNicolai** [comment]
Works well on master

**Comment by KochetovNicolai** [comment]
Revert of #13964 helped for 20.8
Will revert for other releases.

**Comment by SaltTan** [comment]
```
SELECT version()

┌─version()─┐
│ 20.11.2.1 │
└───────────┘

SELECT countIf(toInt8(1))
FROM system.one

Received exception from server (version 20.11.2):
Code: 43. DB::Exception: Received from localhost:9000. DB::Exception: Illegal type Int8 of last argument for aggregate function with If suffix.

0 rows in set. Elapsed: 0.001 sec.

SELECT countIf(toUInt8(1))
FROM system.one

┌─countIf(toUInt8(1))─┐
│                   1 │
└─────────────────────┘
```

**Comment by KochetovNicolai** [comment]
Have reverted for release branches.
