### ISSUE TITLE
ClickHouse doesn't return affected rows via MySQL protocol for INSERT queries after 20.5+

### ISSUE THREAD

**Issue by Slach** [ClickHouse/ClickHouse#16605]
**Describe the bug**
ClickHouse doesn't return affected rows via MySQL protocol for INSERT queries after 20.5+

**How to reproduce**
i create clear docker-compose environment for reproduce behavior MySQL + clickhouse + php + python
https://gist.github.com/Slach/aa67440ce856a3a53f64f92eeddfbc1b

**Queries to run that lead to unexpected result**
```
INSERT INTO default.t1(n) SELECT * FROM numbers(1000)
```

**Expected behavior**
MySQL protocol shall return affected rows field for INSERT queries (it works successful in 20.3 and 20.4)
![image](https://user-images.githubusercontent.com/105560/97867431-aa22ae00-1d2f-11eb-8caf-05431ffd29b3.png)

**Actual behavior**
![image](https://user-images.githubusercontent.com/105560/97867401-9f681900-1d2f-11eb-93cc-5ae6f1f5981b.png)

**Comment by den-crane** [comment]
CH simply does not know this.

**Comment by Slach** [comment]
@den-crane 
why CH knew it in 20.3, 20.4 but forget in 20.5+?
and why it successfully save into `system.query_log` `result_rows` field?
it will break MUCH cases for users which expect affected rows to ensure some data was inserted

**Comment by den-crane** [comment]
Not sure Why it was working before.
```

create table A ( A String) Engine=Memory;
insert into A values('a'),('b');
2 rows in set.                  <<<<<<<-----------

create table A1 as A
insert into A1 select * from A
0 rows in set

insert into A1 SELECT toString(number) FROM numbers(1000)
0 rows in set.
```

**Comment by den-crane** [comment]
@Slach Check this in 20.3

INSERT INTO default.t1(n) SELECT * FROM numbers(1000) where number%3

**Comment by Slach** [comment]
@den-crane 
done

```
string(26) "CLICKHOUSE #2 INSERT QUERY"
string(70) "INSERT INTO default.t1(n) SELECT * FROM numbers(1000) where number % 3"
string(6) "RESULT"
bool(true)
string(27) "CLICKHOUSE #2 affected_rows"
int(666)
```

**Comment by Slach** [comment]
add steps to reproduce for python in  https://gist.github.com/Slach/aa67440ce856a3a53f64f92eeddfbc1b

@zhang2014 @BohuTANG could you help us resolve this issue?

**Comment by BohuTANG** [comment]
The problem does exist, but it's not the MySQLHandler/MySQL problem.
When we execute `INSERT INTO default.t1(n) SELECT * FROM numbers(1000) where number % 3`, the packet send to MySQL client is not through the MySQLOutputFormat.cpp:
https://github.com/ClickHouse/ClickHouse/blob/64bd63ca4999297e041fe853c6e4b6a2fa5bd5f0/src/Processors/Formats/Impl/MySQLOutputFormat.cpp#L77-L82

Instead it send  directly here:
https://github.com/ClickHouse/ClickHouse/blob/64bd63ca4999297e041fe853c6e4b6a2fa5bd5f0/src/Server/MySQLHandler.cpp#L338-L339

I am not sure why, maybe @alexey-milovidov could give some hints.

**Comment by Slach** [comment]
@zhang2014 could you look to https://github.com/ClickHouse/ClickHouse/issues/16605#issuecomment-721468826
and help us resolve this issue?
