### ISSUE TITLE
Poor usability of CREATE DICTIONARY query with CLICKHOUSE source.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#16616]
It's not possible to avoid specifying port (server port should be implied).
It's not possible to avoid specifying user (default user should be assumed).
It's not possible to avoid specifying host (localhost should be assumed).

Documentation states that I can specify `LAYOUT(MAX 30)` and omit `MIN`.
https://clickhouse.tech/docs/en/sql-reference/statements/create/dictionary/
It does not work.

**Comment by filimonov** [comment]
https://github.com/ClickHouse/ClickHouse/issues/15607

**Comment by filimonov** [comment]
BTW that does NOT solve problem which was the reason i've opened #15607 - password rotation w/o redeclaring all dictionaries.

**Comment by alexey-milovidov** [comment]
@vdimir Looks like user and password should not be set, the source should just go to current ClickHouse instance.

**Comment by filimonov** [comment]
Loosely coupled with https://github.com/ClickHouse/ClickHouse/issues/19228

**Comment by alexey-milovidov** [comment]
@vdimir I don't remember whether it is fixed.

**Comment by den-crane** [comment]
>it still does not work without specifying an explicit user + password.

It works if the user `default` and password is empty `''` (also default). 
Basically Clickhouse developers assume that `default` user is a special user and it has no password and access to this user is limited using `network` restrictions.

>Is there a reason a dictionary on top of a ClickHouse table cannot assume the role
> of the caller when querying the underlying table?

When a dictionary updates the data from the source a caller does not exist.

**Comment by MubinUmarov** [comment]
The issue still exists. Why it is closed? I'm still not able to specify just table name which is located in the current instance when I create a dictionary.

**Comment by Slach** [comment]
@MubinUmarov which issue exactly is exists?

create new one and describe your use case and error message
