### ISSUE TITLE
Reading parquets using wildcast use too much memory

### ISSUE THREAD

**Issue by GongXiaokang** [ClickHouse/ClickHouse#16623]
When reading parquets using wildcast like:
insert into aaa select * from File("/home/data/*.snappy.parquet",PARQUET);

There are about 1400 million rows and more than 200 parquet files.

A few moments later, it fails like:
executeQuery: Code: 241, e.displayText() = DB::Exception: Memory limit (total) exceeded: would use 74.68 GiB (attempt to allocate chunk of 5075574 bytes), maximum: 74.51 GiB (version 20.4.5)

**Comment by filimonov** [comment]
#10461

**Comment by alexey-milovidov** [comment]
Fixed in version 21.12.
