### ISSUE TITLE
Engine=Memory with persistancy 

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#16624]
Similar to engine=Join or engine=Set

**Use case**
Regular tiny table which should live in RAM, but recover its state at server restart. 

**Describe the solution you'd like**
```
create table x (number UInt64) Engine=Memory settings persistent=1
```

**Describe alternatives you've considered**
Refeed the table manually at server restart - complicated scripting. 
Use Engine=Join / Set / dictionary - non convinient syntax.

**Comment by alexey-milovidov** [comment]
Why table should leave in ram? If it's a tiny table, maybe `StripeLog` will suffice?

**Comment by filimonov** [comment]
Well, it may limit the IO a bit. And since Join / Set tables have that (they are also in-memory) persistence it would be more consistent to be able to enable the same approach for engine=Memory too. 

But it's not an important task - actually I don't care when/if it will be implemented (I just wrote it down because it was the source of some misunderstanding).
