### ISSUE TITLE
join_algorithm=auto It didn't work

### ISSUE THREAD

**Issue by chang0391** [ClickHouse/ClickHouse#16626]
**Describe the bug**
 version:20.9.3.45
  When I set join_algorithm='auto', it should be use hash when memory is enough, and it use partial_merge when memory is not enough , but when I set the parameter to auto, it didn't use hash method when there was enough memory,it was slowly,
 so, can you take care of the bug? 
 By the way, when I set it to partial_ Merge, it is faster than setting to auto,so which method to deal with it when setting to auto?
So I think that it is better to use hash when there is enough memory, and use partial_merge to avoid issue of insufficient memory    when set  join_algorithm='auto'

**How to reproduce**
```
nsj-op-shorturl2-205-062 :) set join_algorithm='hash'
SET join_algorithm = 'hash'
Ok.
0 rows in set. Elapsed: 0.001 sec. 

nsj-op-shorturl2-205-062 :) select count(1) from rp_credit_sms_cmcc_kuan a join rp_credit_sms_ctcc_l b on a.short_url=b.short_url
SELECT count(1)
FROM rp_credit_sms_cmcc_kuan AS a
INNER JOIN rp_credit_sms_ctcc_l AS b ON a.short_url = b.short_url
┌─count(1)─┐
│     2002 │
└──────────┘
1 rows in set. Elapsed: 19.862 sec. Processed 367.85 million rows, 8.83 GB (18.52 million rows/s., 444.49 MB/s.) 

nsj-op-shorturl2-205-062 :) set join_algorithm='partial_merge'
SET join_algorithm = 'partial_merge'
Ok.
0 rows in set. Elapsed: 0.003 sec. 

nsj-op-shorturl2-205-062 :) select count(1) from rp_credit_sms_cmcc_kuan a join rp_credit_sms_ctcc_l b on a.short_url=b.short_url
SELECT count(1)
FROM rp_credit_sms_cmcc_kuan AS a
INNER JOIN rp_credit_sms_ctcc_l AS b ON a.short_url = b.short_url
┌─count(1)─┐
│     2002 │
└──────────┘
1 rows in set. Elapsed: 53.743 sec. Processed 367.85 million rows, 8.83 GB (6.84 million rows/s., 164.27 MB/s.)

nsj-op-shorturl2-205-062 :) set join_algorithm='auto'
SET join_algorithm = 'auto'
Ok.
0 rows in set. Elapsed: 0.001 sec. 

nsj-op-shorturl2-205-062 :) select count(1) from rp_credit_sms_cmcc_kuan a join rp_credit_sms_ctcc_l b on a.short_url=b.short_url
SELECT count(1)
FROM rp_credit_sms_cmcc_kuan AS a
INNER JOIN rp_credit_sms_ctcc_l AS b ON a.short_url = b.short_url
┌─count(1)─┐
│     2002 │
└──────────┘
1 rows in set. Elapsed: 55.285 sec. Processed 367.85 million rows, 8.83 GB (6.65 million rows/s., 159.69 MB/s.) 
```

**Comment by KochetovNicolai** [comment]
> So I think that it is better to use hash when there is enough memory, and use partial_merge to avoid issue of insufficient memory when set join_algorithm='auto'

But that's exactly what happens when `join_algorithm='auto'`. This mode tries to use `hash` when there is enough memory and `partial_merge` on case we reach limit `default_max_bytes_in_join`. It is 1000000000 bytes by default, try increase this limit if possible.

`auto` may be a little bit slower then `partial_merge` because it converts data when switch between algorithms happen. In your case, the difference is not very significant: 53.743 vs 55.285 sec which is about 3%.

**Comment by den-crane** [comment]
>but when I set the parameter to auto, it didn't use hash method when there was enough memory

It because CH uses a prediction to switch to PARTIAL before memory overusage by HASH.

**Comment by chang0391** [comment]
if I set join_algorithm=auto,set default_max_bytes_in_join=max_memory_usage, hash can be used when memory is enough, and merge join is used when memory is not enough, is it right?

**Comment by den-crane** [comment]
> if I set join_algorithm=auto,set default_max_bytes_in_join=max_memory_usage, hash can be used when memory is enough, and merge join is used when memory is not enough, is it right?

Is not. 
CH uses HashJoin until it predicts that HashJoin will overuse memory in the next memory allocation.

**Comment by chang0391** [comment]
If it can automatically select the appropriate method, hash or partial merge, according to the size of the memory used, it will be better
