### ISSUE TITLE
how to merge 12 sql to 1?

### ISSUE THREAD

**Issue by vegastar002** [ClickHouse/ClickHouse#16633]
I need a fine sql. 
select count() from t1 where time1>= toDateTime('2019-01-01 00:00:00')  and time1< toDateTime('2019-02-01 00:00:00');
select count() from t1 where time1>= toDateTime('2019-02-01 00:00:00')  and time1< toDateTime('2019-03-01 00:00:00');
.......
select count() from t1 where time1>= toDateTime('2019-12-01 00:00:00')  and time1< toDateTime('2020-01-01 00:00:00');
so, how can I merge the 12 sql to 1?

**Comment by filimonov** [comment]
```sql
SELECT 
  toDate(time1) date,
  count()
FROM t1
  WHERE  time1>= toDateTime('2019-01-01 00:00:00')  and time1< toDateTime('2020-01-01 00:00:00')
GROUP BY date;
```

**Comment by vegastar002** [comment]
thank u , it's useful.
but I want use neighbor() to get it.
eg:
SELECT 
    d2 AS start,
    neighbor(d2, -1) AS end
FROM 
(
    WITH toDate('2020-04-01') AS d1
    SELECT toStartOfMonth(d1 - (number * 32)) AS d2
    FROM numbers(16)
)

┌──────start─┬────────end─┐
│ 2020-04-01 │ 1970-01-01 │
│ 2020-02-01 │ 2020-04-01 │
│ 2020-01-01 │ 2020-02-01 │
│ 2019-12-01 │ 2020-01-01 │
│ 2019-11-01 │ 2019-12-01 │
│ 2019-10-01 │ 2019-11-01 │
│ 2019-09-01 │ 2019-10-01 │
│ 2019-08-01 │ 2019-09-01 │
│ 2019-07-01 │ 2019-08-01 │
│ 2019-06-01 │ 2019-07-01 │
│ 2019-05-01 │ 2019-06-01 │
│ 2019-04-01 │ 2019-05-01 │
│ 2019-03-01 │ 2019-04-01 │
│ 2019-02-01 │ 2019-03-01 │
│ 2019-01-01 │ 2019-02-01 │
│ 2018-12-01 │ 2019-01-01 │

select count() from t1 where time1>= toDateTime( start  ) and time1< toDateTime( end  );

in this way , how can I instead of start and end ?
