### ISSUE TITLE
Optimize countIf and sum(if(cond, 1, 0))

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#16639]
Provide specialized implementation of `countIf`, choose it in `AggregateFunctionFactory`.
Rewrite `sum(if(cond, 1, 0))` to `countIf` on AST level.

Note: `countIf(x)` differs from `sum(x)` if `x` can have values other than 0 and 1.

**Comment by ucasFL** [comment]
Hi, I want to do this. @alexey-milovidov

**Comment by alexey-milovidov** [comment]
It is wonderful, let's do it!

**Comment by ucasFL** [comment]
This task has been done! @alexey-milovidov
