### ISSUE TITLE
Add atan2 function

### ISSUE THREAD

**Issue by hombit** [ClickHouse/ClickHouse#16632]
`atan2` is used when `x` and `y` coordinates are given, in this case it has better performance and wider range than `atan`. See [Wikipedia article](https://en.wikipedia.org/wiki/Atan2) for the full description and motivation

**Comment by alexey-milovidov** [comment]
Can be added very easily, see `src/Functions/pow.cpp`

**Comment by alexey-milovidov** [comment]
`hypot` can also be added just in case.
