### ISSUE TITLE
Usability of clickhouse-benchmark: allow to pass query with --query parameter instead of stdin.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#16645]
`clickhouse-benchmark --query "..."`

To make it more similar to `clickhouse-client`.

**Comment by amosbird** [comment]
Btw, I feel that we can provide some additional features to `clickhouse-benchmark`. Sometimes we may like to provide a query template with some parameters and rules, and the benchmark tool should generate random queries based on that.
