### ISSUE TITLE
how to use neighbor() to get every month count?

### ISSUE THREAD

**Issue by vegastar002** [ClickHouse/ClickHouse#16654]
I need count every month  in 2019, sql: 
select count() from t1 where time1>= toDateTime(  '2019-01-01 00:00:00'  ) and time1< toDateTime( '2019-02-01 00:00:00'  );

I want use neighbor() to get it.
eg:
SELECT 
    d2 AS start,
    neighbor(d2, -1) AS end
FROM 
(
    WITH toDate('2020-04-01') AS d1
    SELECT toStartOfMonth(d1 - (number * 32)) AS d2
    FROM numbers(16)
)

┌──────start─┬────────end─┐
│ 2020-04-01 │ 1970-01-01 │
│ 2020-02-01 │ 2020-04-01 │
│ 2020-01-01 │ 2020-02-01 │
│ 2019-12-01 │ 2020-01-01 │
│ 2019-11-01 │ 2019-12-01 │
│ 2019-10-01 │ 2019-11-01 │
│ 2019-09-01 │ 2019-10-01 │
│ 2019-08-01 │ 2019-09-01 │
│ 2019-07-01 │ 2019-08-01 │
│ 2019-06-01 │ 2019-07-01 │
│ 2019-05-01 │ 2019-06-01 │
│ 2019-04-01 │ 2019-05-01 │
│ 2019-03-01 │ 2019-04-01 │
│ 2019-02-01 │ 2019-03-01 │
│ 2019-01-01 │ 2019-02-01 │
│ 2018-12-01 │ 2019-01-01 │

select count() from t1 where time1>= toDateTime( start  ) and time1< toDateTime( end  );

in this way , how can I instead of start and end , and count every month number?

UPD: follow up for https://github.com/ClickHouse/ClickHouse/issues/16633

**Comment by den-crane** [comment]
You don't need neighbor.

```
SELECT arrayJoin(arrayMap(i -> (toDate('2019-01-01') + toIntervalMonth(i)), range(12))) AS m


┌──────────m─┐
│ 2019-01-01 │
│ 2019-02-01 │
│ 2019-03-01 │
│ 2019-04-01 │
│ 2019-05-01 │
│ 2019-06-01 │
│ 2019-07-01 │
│ 2019-08-01 │
│ 2019-09-01 │
│ 2019-10-01 │
│ 2019-11-01 │
│ 2019-12-01 │
└────────────┘

select m, m + interval 1 month - 1 day from (
SELECT arrayJoin(arrayMap(i -> (toDate('2019-01-01') + toIntervalMonth(i)), range(12))) AS m)

┌──────────m─┬────────day─┐
│ 2019-01-01 │ 2019-01-31 │
│ 2019-02-01 │ 2019-02-28 │
│ 2019-03-01 │ 2019-03-31 │
│ 2019-04-01 │ 2019-04-30 │
│ 2019-05-01 │ 2019-05-31 │
│ 2019-06-01 │ 2019-06-30 │
│ 2019-07-01 │ 2019-07-31 │
│ 2019-08-01 │ 2019-08-31 │
│ 2019-09-01 │ 2019-09-30 │
│ 2019-10-01 │ 2019-10-31 │
│ 2019-11-01 │ 2019-11-30 │
│ 2019-12-01 │ 2019-12-31 │
└────────────┴────────────┘
```

**Comment by den-crane** [comment]
```
create table events (a Date, some String) Engine=Memory;

insert into events values('2020-01-01' , 'x')

SELECT
    toStartOfMonth(a) AS m,
    sum(c)
FROM
(
    SELECT
        a,
        count() AS c
    FROM events
    GROUP BY a
    ORDER BY a ASC WITH FILL FROM toStartOfMonth(toDate('2020-01-01')) TO toStartOfMonth(toDate('2020-12-01'))
)
GROUP BY m
ORDER BY m ASC

┌──────────m─┬─sum(c)─┐
│ 2020-01-01 │      1 │
│ 2020-02-01 │      0 │
│ 2020-03-01 │      0 │
│ 2020-04-01 │      0 │
│ 2020-05-01 │      0 │
│ 2020-06-01 │      0 │
│ 2020-07-01 │      0 │
│ 2020-08-01 │      0 │
│ 2020-09-01 │      0 │
│ 2020-10-01 │      0 │
│ 2020-11-01 │      0 │
└────────────┴────────┘

**Comment by vegastar002** [comment]
> You don't need neighbor.
> 
> ```
> SELECT arrayJoin(arrayMap(i -> (toDate('2019-01-01') + toIntervalMonth(i)), range(12))) AS m
> 
> 
> ┌──────────m─┐
> │ 2019-01-01 │
> │ 2019-02-01 │
> │ 2019-03-01 │
> │ 2019-04-01 │
> │ 2019-05-01 │
> │ 2019-06-01 │
> │ 2019-07-01 │
> │ 2019-08-01 │
> │ 2019-09-01 │
> │ 2019-10-01 │
> │ 2019-11-01 │
> │ 2019-12-01 │
> └────────────┘
> 
> select m, m + interval 1 month - 1 day from (
> SELECT arrayJoin(arrayMap(i -> (toDate('2019-01-01') + toIntervalMonth(i)), range(12))) AS m)
> 
> ┌──────────m─┬────────day─┐
> │ 2019-01-01 │ 2019-01-31 │
> │ 2019-02-01 │ 2019-02-28 │
> │ 2019-03-01 │ 2019-03-31 │
> │ 2019-04-01 │ 2019-04-30 │
> │ 2019-05-01 │ 2019-05-31 │
> │ 2019-06-01 │ 2019-06-30 │
> │ 2019-07-01 │ 2019-07-31 │
> │ 2019-08-01 │ 2019-08-31 │
> │ 2019-09-01 │ 2019-09-30 │
> │ 2019-10-01 │ 2019-10-31 │
> │ 2019-11-01 │ 2019-11-30 │
> │ 2019-12-01 │ 2019-12-31 │
> └────────────┴────────────┘
> ```

yes, this way is wonderful, but it can't count every month ?

**Comment by den-crane** [comment]
No. Use the first example and join with these calendar
