### ISSUE TITLE
How can get correct array ?

### ISSUE THREAD

**Issue by vegastar002** [ClickHouse/ClickHouse#16666]
sql :
WITH 
    [1, 2, 3] AS d1,
    ['a', 'e', 'f'] AS t1
SELECT 
    arrayJoin(d1),
    arrayJoin(t1)

┌─arrayJoin(d1)─┬─arrayJoin(t1)─┐
│             1 │ a             │
│             1 │ e             │
│             1 │ f             │
│             2 │ a             │
│             2 │ e             │
│             2 │ f             │
│             3 │ a             │
│             3 │ e             │
│             3 │ f             │

it's not I want result,  how can I get result as :
1 a
2 e
3 f
?

**Comment by alexey-milovidov** [comment]
`WITH [1, 2, 3] AS a, ['a', 'b', 'c'] AS b SELECT arrayJoin(arrayZip(a, b))`

**Comment by den-crane** [comment]
```
SELECT d, t from ( WITH
[1, 2, 3] AS d1,
['a', 'e', 'f'] AS t1 select d1, t1)
array Join d1 as d, t1 as t

┌─d─┬─t─┐
│ 1 │ a │
│ 2 │ e │
│ 3 │ f │
└───┴───┘
```
