### ISSUE TITLE
 DB::Exception: A setting 'max_threads' appeared at top level in config

### ISSUE THREAD

**Issue by trollhe** [ClickHouse/ClickHouse#16676]
Hello:
My is evey server configuration is 12cores, 64GB, 4 * 8tb, SAS. Set max_ threads=12,max_ server_ memory_ usage=64GB.
While running the query, an error was thrown and the service could not be started.

please help me,thank u.

error info:
```
2020.11.04 16:00:01.038671 [ 1 ] {} <Error> Application: DB::Exception: A setting 'max_threads' appeared at top level in config /etc/clickhouse-server/config.xml. But it is user-level setting that should be located in users.xml inside <profiles> section for specific profile. You can add it to <profiles><default> if you want to change default value of this setting. You can also disable the check - specify <skip_check_for_incorrect_settings>1</skip_check_for_incorrect_settings> in the main configuration file.
```

**Comment by den-crane** [comment]
A setting 'max_threads' appeared at top level in config /etc/clickhouse-server/config.xml. 
But it is user-level setting that should be located in users.xml inside <profiles> section for specific profile. 
You can add it to <profiles><default> if you want to change default value of this setting. 
You can also disable the check - specify <skip_check_for_incorrect_settings>1</skip_check_for_incorrect_settings> in the main configuration file.

**Comment by den-crane** [comment]
@trollhe Please provide an output of

`cd /etc/clickhouse-server/; grep -Rl max_threads  *`

**Comment by trollhe** [comment]
> @trollhe Please provide an output of
> 
> `cd /etc/clickhouse-server/; grep -Rl max_threads *`


bellow:
```
$:/etc/clickhouse-server# grep max_threads *
grep: config.d: Is a directory
config.xml:    <max_threads>12</max_threads>
grep: preprocessed: No such file or directory
grep: users.d: Is a directory
```

**Comment by den-crane** [comment]
>config.xml:    <max_threads>12</max_threads>

A setting 'max_threads' appeared at top level in config /etc/clickhouse-server/config.xml.
But it is user-level setting that should be located in users.xml inside section for specific profile.
You can add it to if you want to change default value of this setting.
You can also disable the check - specify <skip_check_for_incorrect_settings>1</skip_check_for_incorrect_settings> in the main configuration file.
