### ISSUE TITLE
Support manifest file for s3, url, hdfs, file table functions

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#16682]
**Use case**
Give ability to pass file which would contain list of files to import via table functions.
Description from redshift:
> You can use a manifest to ensure that your COPY command loads all of the required files, and only the required files, from Amazon S3. You can also use a manifest when you need to load multiple files from different buckets or files that don't share the same prefix. 

https://docs.aws.amazon.com/redshift/latest/dg/loading-data-files-using-manifest.html

**Describe alternatives you've considered**
Allow to pass in table functions resultset from queries?
```SELECT * FROM url(view(SELECT url FROM files_to_import), 'CSV', 'key String') ;```
Or even something like this
```SELECT * FROM url(view(SELECT url, format, schema FROM files_to_import)) ;```

**Comment by geertvanbommel** [comment]
Similar use case with the URL table engine (version 21.6.5)

`SELECT * FROM url('https://jsonplaceholder.typicode.com/todos', JSONEachRow, 'userId UInt32, id UInt32, title String, completed UInt8');`
=> Works :)

`SELECT * FROM url(CONCAT('https://jsonplaceholder.typicode.com/','todos'), JSONEachRow, 'userId UInt32, id UInt32, title String, completed UInt8');`
=> Works :)

`WITH 'todos' as q SELECT * FROM url(CONCAT('https://jsonplaceholder.typicode.com/',q), JSONEachRow, 'userId UInt32, id UInt32, title String, completed UInt8');`
=> Doesn't work :(
Error: `Code: 47. DB::Exception: Received from localhost:9000. DB::Exception: Missing columns: 'q' while processing query: 'concat('https://jsonplaceholder.typicode.com/', q)', required columns: 'q' 'q'.`

`SELECT * FROM url(CONCAT('https://jsonplaceholder.typicode.com/', (SELECT 'todos')), JSONEachRow, 'userId UInt32, id UInt32, title String, completed UInt8');`
=> Doesn't work :(
Error: `Code: 36. DB::Exception: Received from localhost:9000. DB::Exception: Element of set in IN, VALUES or LIMIT is not a constant expression (result column not found): concat('https://jsonplaceholder.typicode.com/', __subquery_11226715727837069946_13892335735831538626)`

**Comment by UnamedRus** [comment]
Related https://github.com/ClickHouse/ClickHouse/issues/53176
