### ISSUE TITLE
how to change default CSV FILE format_csv_delimiter?

### ISSUE THREAD

**Issue by trollhe** [ClickHouse/ClickHouse#16695]
Hello,

my setting:
```
# cat /etc/clickhouse-server/config.d/delimiter.xml
<?xml version="1.0"?>
<yandex>
	<profiles>
        <default>
		<format_csv_delimiter>|</format_csv_delimiter>
        </default>
    </profiles>
</yandex>
```

but throw exception 
```
Code: 27. DB::Exception: Cannot parse input: expected ',' before: (at row 1)

Row 1:
Column 0,   name: user_ip,         type: String, parsed text: ""
ERROR: Line feed found where delimiter (,) is expected. It's like your file has less columns than expected.
```

    please, how to change default CSV FILE format_csv_delimiter?

**Comment by den-crane** [comment]
>cat /etc/clickhouse-server/config.d/delimiter.xml

Wrong folder for user settings.
Should be /etc/clickhouse-server/**users.d/**delimiter.xml


config.d -- server settings (config.xml)
users.d -- users settings (user.xml)
conf.d -- any (config.xml and user.xml)

**Comment by trollhe** [comment]
> > cat /etc/clickhouse-server/config.d/delimiter.xml
> 
> Wrong folder for user settings.
> Should be /etc/clickhouse-server/**users.d**/delimiter.xml
> 
> config.d -- server settings (config.xml)
> users.d -- users settings (user.xml)
> conf.d -- any (config.xml and user.xml)

 file already move from  `/etc/clickhouse-server/config.d/` to `/etc/clickhouse-server/users.d/`.

but exception  still.

tips: i used table function file() to select /data/clickhouse/user_files/*.csv. csv delimiter is  "|".

**Comment by trollhe** [comment]
thanks , Successfully processed. config file move to `/etc/clickhouse-server/users.d/ `
