### ISSUE TITLE
When joining tables with Merge engine, which look at tables with MergeTree engine,  'Not found column' error occurs

### ISSUE THREAD

**Issue by microcropoc** [ClickHouse/ClickHouse#16694]
**Describe the bug**
When joining tables with Merge engine, which look at tables with MergeTree engine,  'Not found column' error occurs

**How to reproduce**
```
CREATE TABLE test_table (Id Int32, Foo Int32) ENGINE = MergeTree ORDER BY Id;

CREATE TABLE test_table_merge as test_table ENGINE = Merge(currentDatabase(), 'test_table');

INSERT INTO test_table (Id, Foo) values (1, 1);

SELECT any(t2.Foo) FROM test_table_merge AS t1 GLOBAL ANY LEFT JOIN test_table_merge AS t2 ON t1.Id = t2.Id FORMAT JSONEachRow
```

**Expected behavior**
{"any(t2.Foo)":1}

**Error message and/or stacktrace**
e.displayText() = DB::Exception: Not found column t2.Foo in block. There are only columns: Id (version 20.8.4.11 (official build))

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/11755
