### ISSUE TITLE
Is replicated engine still useful if DiskS3 is used?

### ISSUE THREAD

**Issue by yiguolei** [ClickHouse/ClickHouse#16706]
When  DiskS3 is used, s3 can already guarantee multiple copies of data and ensures data availability. Is the replicated engine still useful in this case?
Is it possible that only one engine does compaction/merge data job, and the other replicated engine just  read data directly without participating in data merging?

**Comment by alex-zaitsev** [comment]
Yes, see https://github.com/ClickHouse/ClickHouse/pull/16240

**Comment by alexey-milovidov** [comment]
@yiguolei S3 as a disk is experimental feature, it is currently in beta.
@alex-zaitsev it is not merged yet.
