### ISSUE TITLE
The atomicity of alter partition?

### ISSUE THREAD

**Issue by baibaichen** [ClickHouse/ClickHouse#16702]
I find that ClickHouse only supports atomicity at the [block level](https://clickhouse.tech/docs/en/engines/table-engines/mergetree-family/replication/),

>  Each block of data is written atomically. The INSERT query is divided into blocks up to max_insert_block_size = 1048576 rows. In other words, if the INSERT query has less than 1048576 rows, it is made atomically.

But this is not robust for offline BI analysis. 

1. It looks like [MOVE PARTITION TO TABLE](https://clickhouse.tech/docs/en/sql-reference/statements/alter/partition/#alter_move_to_table-partition) is atomicity, it isn't? See https://github.com/ClickHouse/ClickHouse/issues/4729, https://github.com/ClickHouse/ClickHouse/pull/6168.
2. How about [REPLACE PARTITION](https://clickhouse.tech/docs/en/sql-reference/statements/alter/partition/#alter_replace-partition)? https://github.com/ClickHouse/ClickHouse/issues/6749  says it doesn't support atomicity.

Those 2 alter operations are useful for appending and updating partition atomically.

Would it be nice to clarify the guarantee of [**Manipulating Partition**](https://clickhouse.tech/docs/en/sql-reference/statements/alter/partition/) in the documentation?

**Comment by baibaichen** [comment]
@hodgesrm  can we discuss here?  Here are quote from slack:

> you are correct, at the level of individual blocks ClickHouse is very good and we rarely see problems.  The transactional guarantees are not very consistent beyond that level.  This is a community concern and I would encourage you to add your voice on the issues you cited above.
>
> At Altinity we're currently looking at ways to fund improvements in this area.  It's important work for all users. Unfortunately I don't have a timeline for when we'll be able to move on it--we are looking for a corporate sponsor on this.

My replies:

It is good to have transactional support in ClickHouse, but now what I am looking for is avoiding partial results in the middle of loading and a simple way for handling error.

The latter is the most important. From the  PR, it looks like that `move partition to` and `replace partition` are atomicity, but I don't find that this is clarified in the documentation.

If those two operations are atomicity, then we can loading data into a temporary table and moving or replacing partition in one shot.

**Comment by baibaichen** [comment]
here are relies from [slack](https://app.slack.com/client/TUEGQCHJT/CU170QE9H/thread/CU170QE9H-1604975270.033500)
![image](https://user-images.githubusercontent.com/3688732/99216332-61c7bd80-2810-11eb-9d24-fe16c9faf422.png)

**Comment by amosbird** [comment]
Currently none of these partition related alter commands are atomic. We only have part-level atomicity.

**Comment by baibaichen** [comment]
@amosbird  would you please write more details about why isn't atomic?

Thanks
