### ISSUE TITLE
MaterializeMySQL: support replication from MariaDB

### ISSUE THREAD

**Issue by maqroll** [ClickHouse/ClickHouse#16726]
**Describe the issue**
MaterializeMySQL doesn't work with MariaDB.

**How to reproduce**
``CREATE DATABASE test ENGINE = MaterializeMySQL('mariadbserver:3301','db','user','pwd');``

**Expected behavior**
Creates the database

**Error message and/or stacktrace**
``
Code: 537. DB::Exception: Received from localhost:9000. DB::Exception: Illegal MySQL variables, the MaterializeMySQL engine requires default_authentication_plugin='mysql_native_password'.
``

**Additional context**
**default_authentication_plugin** variable does not exist in MariaDB. That check makes sense in MySQL but it prevents MaterializeMySQL from working with MariaDb databases. Considering that the rest of the pieces are compatible, wouldn't it make sense to get rid of that check? The connection will fail anyway later if the condition is not met.

**Comment by zhang2014** [comment]
This requires us to implement several authentication methods to MySQL(only mysql_native_password is currently supported)

**Comment by maqroll** [comment]
MariaDB handles **mysql_native_password** just fine. It doesn't provide the **default_authentication_plugin** variable to check beforehand. 

Without that check one of two things could happen: either the database provides that authentication method and the connection will establish or not (in that case the connection will fail). Both for Mysql and MariaDB.

With that check we are missing the opportunity to handle that negotiation (which authentication plugin to use) at the connection level.

Anyway does that check makes sense even in Mysql? I didn't check it myself but I think [that variable](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_default_authentication_plugin) establishes the default authentication plugin to use but can be overriden when creating a new user. So that the default_authentication_plugin
could be 'mysql_native_password' and the user didn't support it.

**Comment by BohuTANG** [comment]
To support MariaDB, the main work is not the auth plugin, MariaDB GTID format is incompatible with MySQL, it's lot work Todo.

**Comment by bruno-lp** [comment]
Hi 
Any update or planned date on this ?
I hesitate moving from mariadb to mysql to use the materializeMySQL feature

**Comment by BohuTANG** [comment]
I guess no plans yet.

**Comment by alderson59** [comment]
Here's my logs from Clickhouse when trying to use MaterializeMySql :
```
Code: 537. DB::Exception: Received from localhost:9000.
DB::Exception: Illegal MySQL variables,
the MaterializeMySQL engine requires
log_bin_use_v1_row_events='OFF',
default_authentication_plugin='mysql_native_password'.
```

I agree that this should be supported.

Using mariadb:10.4.19 by the way.

With mariadb, 
```
MariaDB [(none)]> SELECT DISTINCT PLUGIN FROM mysql.user;
+-----------------------+
| plugin                |
+-----------------------+
| mysql_native_password |
+-----------------------+
1 row in set (0.001 sec)
```

mysql_native_password is supported in mariadb. It's just not found under 
```
MariaDB [(none)]> SHOW VARIABLES LIKE '%default_authentication_plugin%';
Empty set (0.001 sec)
```

```
MariaDB [(none)]> SHOW VARIABLES LIKE '%log_bin%';
+---------------------------------+----------------------------------+
| Variable_name                   | Value                            |
+---------------------------------+----------------------------------+
| log_bin                         | ON                               |
| log_bin_basename                | /var/log/mysql/mariadb-bin       |
| log_bin_compress                | OFF                              |
| log_bin_compress_min_len        | 256                              |
| log_bin_index                   | /var/log/mysql/mariadb-bin.index |
| log_bin_trust_function_creators | OFF                              |
| sql_log_bin                     | ON                               |
+---------------------------------+----------------------------------+
7 rows in set (0.001 sec)

MariaDB [(none)]> SHOW VARIABLES LIKE '%binlog%';
+-----------------------------------------+----------------------+
| Variable_name                           | Value                |
+-----------------------------------------+----------------------+
| binlog_annotate_row_events              | ON                   |
| binlog_cache_size                       | 32768                |
| binlog_checksum                         | CRC32                |
| binlog_commit_wait_count                | 0                    |
| binlog_commit_wait_usec                 | 100000               |
| binlog_direct_non_transactional_updates | OFF                  |
| binlog_file_cache_size                  | 16384                |
| binlog_format                           | ROW                  |
| binlog_optimize_thread_scheduling       | ON                   |
| binlog_row_image                        | FULL                 |
| binlog_stmt_cache_size                  | 32768                |
| encrypt_binlog                          | OFF                  |
| gtid_binlog_pos                         |                      |
| gtid_binlog_state                       |                      |
| innodb_locks_unsafe_for_binlog          | OFF                  |
| max_binlog_cache_size                   | 18446744073709547520 |
| max_binlog_size                         | 104857600            |
| max_binlog_stmt_cache_size              | 18446744073709547520 |
| read_binlog_speed_limit                 | 0                    |
| sync_binlog                             | 0                    |
| wsrep_forced_binlog_format              | NONE                 |
+-----------------------------------------+----------------------+
21 rows in set (0.001 sec)
```

my.cnf:
```
[mysqld]
log_bin=/var/log/mysql/mariadb-bin
log_bin_index=/var/log/mysql/mariadb-bin.index
binlog_format=row
binlog_row_image=full
expire_logs_days= 10
```

Everything works on the mariadb side, except it isn't supported in MaterializeMySql yet!

Definitely think Clickhouse is the best solution for our use case at this point - except with this problem. Any suggestions for a workaround until this gets implemented soon, hopefully? 😊

**Comment by mhmda-83** [comment]
@alexey-milovidov 
problem still exists. why this issue closed?

**Comment by tavplubix** [comment]
> problem still exists. why this issue closed?

As you can see from `st-wontfix` label, it's closed because we have no plans of implementing support for replication from MariaDB. Feel free to open a pull request that resolves this issue.

**Comment by reyjrar** [comment]
I wasn't able to even `SELECT * FROM mysql(...)` on ClickHouse 22.2.2 to MariaDB 10.4.

I've gotten that working by inserting ProxySQL in between ClickHouse and MariaDB. It might also work for `MaterializeMySQL`, but I haven't tested that yet.

Hope this helps other who are pulling their hair out trying to get even the "simplest" things to work :)

**Comment by gkarugi** [comment]
I'm having the same problem. the user already uses mysql_native_password but the default_authentication_plugin on the server is set to caching_sha2_password. 

Getting the same issue with ProxySQL. @reyjrar did you ever find a way to use this with ProxySQL?
