### ISSUE TITLE
[proposed bug] Join Table Engine limitation

### ISSUE THREAD

**Issue by Fallenyasha** [ClickHouse/ClickHouse#16732]
Стоит следующая задача: необходимо мапить одно значение на другое во множестве запросов, таблица мапинга достаточно большая, 100-500М записей, для этого была создана таблица с движком Join с последующим мапингом через joinGet
`CREATE TABLE lookup (key UInt64, id UInt64) ENGINE = Join(ANY, LEFT, key)`

Но вот дальше стали происходить какие-то странности, при вставке данных в эту таблицу вылетает сообщение
` DB::Exception: Memory limit (total) exceeded: would use 1.92 GiB (attempt to allocate chunk of 402654352 bytes), maximum: 1.75 GiB: While executing SinkToOutputStream (version 20.9.2.20 (official build))`

Для вставки использовалась либо обычная таблица MergeTree с исходными данными, либо генерация
`INSERT INTO lookup (key, id) SELECT rand64() + arrayJoin(range(1000000)), 0`

Странность заключается в том, что каждый раз при пересоздании таблицы лимиты на количество записей разные, 8388608, 16777216, 33554432, а иногда и нормально без ограничений, ну или не удалось их достигнуть.

Значения параметров max_rows_in_join, max_bytes_in_join по умолчанию 0.
Проверял на разных серверах и версиях 19.4.5.1 и 20.9.2.20, ситуация везде повторяется.

Соответственно 2 вопроса:
1. может есть иной механизм реализации подобного мапинга, сопоставимый по скорости?
2. откуда берутся лимиты на таблицы типа Join и как их контроллировать?

**Comment by Fallenyasha** [comment]
Чуть больше исследовал, посмотрел потребление памяти при выполнении запросов инсерта, вставлял блоками по ~2М записей, получается следующая картина
`185.00 MiB
353.01 MiB
72.26 MiB
82.23 MiB
452.26 MiB
80.82 MiB
81.38 MiB
82.51 MiB
836.26 MiB
76.76 MiB
83.88 MiB
77.32 MiB
74.88 MiB
77.76 MiB
79.70 MiB
80.13 MiB
1.57 GiB
65.07 MiB
84.38 MiB
79.38 MiB
77.32 MiB
70.38 MiB
77.70 MiB
72.38 MiB
76.32 MiB
85.81 MiB
84.76 MiB
71.45 MiB
88.32 MiB
81.13 MiB
77.32 MiB
78.13 MiB
3.07 GiB
70.01 MiB
61.38 MiB
83.76 MiB
78.88 MiB`

Т.е. похоже на то, что при достижении некоторого лимита записей происходит удвоение алоцируемой для таблицы памяти, при этом эта память поедается из max_memory_usage, что немного странно, т.е. получается что обычную таблицу типа MergeTree можно иметь с неограниченным количеством записей, а типа Join с непонятным ограничением, завязанным на max_memory_usage. Можно ли это обойти?

**Comment by alexey-milovidov** [comment]
@Fallenyasha Лимиты берутся из ограничения на запрос, вставляющий данные.
Аллокация данных для таблицы типа Join происходит в контексте запроса на вставку.

Аллокация одной из структур данных требуется не на каждый запрос, а только если места в буфере таблицы недостаточно - в этом случае выделяется в два раза больше памяти, чем было ранее. Это объясняет наблюдаемые вами результаты.

Для того, чтобы обойти ограничение, выставите:
```
SET max_memory_usage = 0
```
перед вставкой.
