### ISSUE TITLE
feature request: WITH FILL expression values compatible with column type Nullable

### ISSUE THREAD

**Issue by cicihou** [ClickHouse/ClickHouse#16733]
Appreciate for you all teams brilliant work, it's really fast and useful 

**Use case**
A clear and concise description of what is the intended usage scenario is.
my sql
`
    SELECT comment_date
    FROM 
    (
    SELECT comment_time AS comment_date
    FROM kimberly_nlp_wide)
    GROUP BY comment_date 
    ORDER BY comment_date WITH FILL
`

**Describe the solution you'd like**

The comment_time column type is Nullable(DateTime()). so it could not use "WITH FILL"

**Describe alternatives you've considered**
could only change the column type or process it via Python
Hope CK could support it in ur next update, thank u :)

**Additional context**

**Comment by alexey-milovidov** [comment]
Minimal example:

```
SELECT toNullable(today() + number * 10) AS d FROM numbers(2) ORDER BY d WITH FILL
```
