### ISSUE TITLE
Integrate and test experimental compression libraries.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#16775]
See https://github.com/ClickHouse/ClickHouse/issues/15065#issuecomment-723397565
These codecs should be available under the experimental flag in Settings.

https://github.com/inikep/lizard
https://github.com/ConorStokes/LZSSE
https://github.com/centaurean/density
https://github.com/IlyaGrebnov/libbsc
https://github.com/fusiyuan2010/CSC
https://github.com/richgel999/lzham_codec

The task is for @fibersel

**Comment by l1t1** [comment]
```PPMd.
With the 7z format, you can specify the algorithm. PPMd is good for compressing plain text files. It is ideal for Word documents. PPMd does not perform as well on binary data.

PPMd switch -mmem=24b, -mmem=24k, -mmem=24m: These control the amount of memory you use. They are useful and higher is normally better.

PPMd switch -mo=2, -mo=32: These specify the model order in PPMd. They are not normally useful.

Tip: You should use PPMd when you have a large corpus (body) of text. This could include HTML. It can improve ratios by around 30%.```

**Comment by filimonov** [comment]
Nice project with benchmark https://github.com/inikep/lzbench

**Comment by l1t1** [comment]
ref from https://github.com/szcnick/p7zip
fast-lzma2 (https://github.com/conor42/fast-lzma2) mthod is about 4 time faster than lzma2

format | method | encode_size(Byte) | encode_time(ms) | encode_speed(M/s) | decode_time(ms) | decode_speed(M/s) | compression_ratio
-- | -- | -- | -- | -- | -- | -- | --
7z-zip | deflaut-9 | 64727443 | 59170 ms | 3.33 | 1649 | 122.57 | 3.27
7z-7z | lzma-9 | 48752521 | 80680 ms | 2.51 | 3780 | 53.47 | 4.35
7z-7z | lzma2-9 | 48749147 | 81106 ms | 2.50 | 3742 | 54.01 | 4.35
7z-7z | zstd-22 | 52739879 | 134245 ms | 1.51 | 893 | 226.34 | 4.02
7z-7z | lz4-12 | 77788386 | 3548 ms | 56.97 | 409 | 494.18 | 2.72
7z-7z | flzma2-9 | 48676481 | 12619 ms | 16.02 | 3877 | 52.13 | 4.35

**Comment by alexey-milovidov** [comment]
@filimonov Also I suggest to dig into the [encode.su](https://encode.su/forums/2-Data-Compression) forum if someone wants to be really into the topic.

**Comment by alexey-milovidov** [comment]
@filimonov There are also:

https://quixdb.github.io/squash-benchmark/
Pros: Good visualization. Allows to choose dataset and hardware.
Cons: Significantly outdated: hardware and compilers are from several years ago, zstd version looks outdated.

https://github.com/powturbo/TurboBench
Pros: One of the most comprehensive, regularly updated; the author is credible for development of high-performance algorithms.

**Comment by alexey-milovidov** [comment]
@fibersel It looks like you should replace xz-utils to https://github.com/conor42/fxz in https://github.com/ClickHouse/ClickHouse/pull/16578 :) (but only if data format is compatible).

**Comment by fibersel** [comment]
As I have figured out, https://github.com/conor42/fxz is a command-line tool, based on https://github.com/conor42/fast-lzma2 .So I don't need to add whole https://github.com/conor42/fxz, library would be enough.Correct me if I am wrong.

**Comment by alexey-milovidov** [comment]
That's correct.

**Comment by filimonov** [comment]
2 more candidates to check / consider 
https://github.com/Cyan4973/FiniteStateEntropy
https://github.com/lzfse/lzfse

And one more benchmark:
http://mattmahoney.net/dc/text.html

**Comment by alexey-milovidov** [comment]
> https://github.com/Cyan4973/FiniteStateEntropy
https://github.com/lzfse/lzfse

AFAIK, FSE is used inside zstd, and zstd does it better than sequential application of FSE+LZ77, because they are interleaved.

**Comment by filimonov** [comment]
List of codecs supported by redshift: 
https://docs.aws.amazon.com/redshift/latest/dg/c_Compression_encodings.html

**Comment by alexey-milovidov** [comment]
@filimonov Only ZLO and ZSTD are generic purpose compression codecs. We already have ZSTD. And there is zero sense to add ZLO as it is inferior than LZ4.
