### ISSUE TITLE
clickhouse support zstd compression file for file table function ?

### ISSUE THREAD

**Issue by trollhe** [ClickHouse/ClickHouse#16791]
Hello,

dosen't clickhouse support read to zstd file ?

Due to the large number of files, it is considered to compress the files into zstd and use Clickhouse to read them.eg: user_logs_20201108000000_190081200_124_1.zst

eg:
```
aaa|bbb|ccc
....
```

i want use sql to read it:
```
select * from file('user_logs/*20201108*.zst','CSV','xxx String,xxx String,xxx String,xxx String,xxx String,xxx String,xxx String ,xxx String,xxx String') limit 5;
```

but clickhouse no parse it 
```
Code: 27. DB::Exception: Received from localhost:9800. DB::Exception: Cannot parse input: expected '|' before: '\n??PmD0Cw?-?M?Xbil??|#6??jg*????b??R?@????\\???ޓ?C???y??\bg??އ?T\n(4?4fs<Y?v????R??9?Q?0xgA?\bA#Q?r\n?@??*?G??+?n鎱8??-?????H(Fe?1?g?N6': (at row 1)
```

**Comment by alexey-milovidov** [comment]
Only gz, br are currently supported for file compressors.
Yes, we should add zst.

**Comment by trollhe** [comment]
> Only gz, br are currently supported for file compressors.
> Yes, we should add zst.

that`s great!
