### ISSUE TITLE
Clickhouse miscalculates COUNT(right_table.column) with a LEFT JOIN that returns no matches from right table

### ISSUE THREAD

**Issue by noahkawasakigoogle** [ClickHouse/ClickHouse#16796]
**Describe the bug**

If you LEFT JOIN a table where the join condition has no `true` matches to the right hand table (as in, every column from the right table should be empty) a `COUNT(right.column)` will incorrectly return 1 row counted even though it should return 0 rows, since the join had no matches.

**How to reproduce**
```
CREATE DATABASE test;

CREATE TABLE test.left (
  id Int32,
  other_id Int32
)
 ENGINE = MergeTree()
  PRIMARY KEY id
  PARTITION BY tuple()
  ORDER BY (id)
  SETTINGS index_granularity=8192;

INSERT INTO left VALUES (1, 100);

CREATE TABLE test.right (
  id Int32,
  other_id Int32
)
 ENGINE = MergeTree()
  PRIMARY KEY id
  PARTITION BY tuple()
  ORDER BY (id)
  SETTINGS index_granularity=8192;

INSERT INTO right VALUES (5, 500);
```

Notice that the id columns should never match up, 1 != 5.

```
SELECT *
FROM left
LEFT JOIN right ON left.id = right.id
```

Correctly returns nothing from the right table:

![Screen Shot 2020-11-08 at 10 00 25 AM](https://user-images.githubusercontent.com/68556134/98472644-440fae00-21a9-11eb-8850-935d677849ee.png)

But COUNT incorrectly still returns a row:

```
SELECT 
        (COUNT(right.id)) AS `right.count`
FROM left
LEFT JOIN right ON left.id = right.id
```

![Screen Shot 2020-11-08 at 10 01 07 AM](https://user-images.githubusercontent.com/68556134/98472656-5689e780-21a9-11eb-82b7-89ddc2b8fedf.png)

* Which ClickHouse server version to use
19.15, 19.16, 20.1, 20.3 I could reproduce this behavior on all versions, I assume it probably exists past this too

**Expected behavior**
Expect that when two tables have no matching values to join, the COUNT from the right hand table will return `0`

**Error message and/or stacktrace**

**Additional context**

**Comment by den-crane** [comment]
CH does not produce Nullable types by performance reasons.

SELECT *
FROM left
LEFT JOIN right ON left.id = right.id

┌─id─┬─other_id─┬─right.id─┬─right.other_id─┐
│  1 │      100 │        0 │              0 │
└────┴──────────┴──────────┴────────────────┘

set join_use_nulls=1;

SELECT *
FROM left
LEFT JOIN right ON left.id = right.id;

┌─id─┬─other_id─┬─right.id─┬─right.other_id─┐
│  1 │      100 │     ᴺᵁᴸᴸ │           ᴺᵁᴸᴸ │
└────┴──────────┴──────────┴────────────────┘


SELECT COUNT(right.id) AS `right.count`
FROM left
LEFT JOIN right ON left.id = right.id;

┌─right.count─┐
│           0 │
└─────────────┘
```

https://clickhouse.tech/docs/en/operations/settings/settings/#join_use_nulls

You can enable `join_use_nulls` in users profile for one or for all users.

```
$ cat /etc/clickhouse-server/conf.d/join_use_nulls.xml
<?xml version="1.0"?>
<yandex>
    <profiles>
        <default>
          <join_use_nulls>1</join_use_nulls>
        </default>
    </profiles>
</yandex>
```
