### ISSUE TITLE
Is there a library that can we directly build a roaring bitmap with spark, and then bulk upload it?

### ISSUE THREAD

**Issue by litaoyx** [ClickHouse/ClickHouse#16798]
The bitmap operation in Clickhouse is great. But as far as I know, it needs to load the raw data into clickhouse by first, and then use the groupBitmapState function to construct the roaring bitmap. The raw data is very large, so we don't want to load the raw data into clickhouse, and we want to build the roaring bitmap when loading data into clickhouse with spark.

Is there a library that can we directly build a roaring bitmap with spark, and then bulk upload it?

**Comment by sundy-li** [comment]
`roaring bitmap state`  In ClickHouse is not the native way storage as `croaring`, see `AggregateFunctionGroupBitmapData.h`

> Is there a library that can we directly build a roaring bitmap with spark, and then bulk upload it?
 
 No, but you can build one.
- Look at `DataTypeAggregateFunction`, you can implement the `serializeBinary` and `deserializeBinary`  in Java/scala.
- Some other simple DataTypes are implemented in  [Clickhouse-Native-JDBC](https://github.com/housepower/ClickHouse-Native-JDBC/blob/master/clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/DataTypeIPv4.java)

**Comment by litaoyx** [comment]
I implemented a custom serialization roaringbitmap method in spark to make the serialization structure compatible with the roaringbitmap structure in clickhouse. For details, please refer to the article: https://blog.csdn.net/qq_27639777/article/details/111005838

**Comment by sunbc996** [comment]
https://blog.csdn.net/qq_27639777/article/details/111005838
// 创建分布式表
CREATE TABLE stone.bitmap_test ON CLUSTER cluster_name (
  ds Int64,
  user String,
  roaring_bitmap AggregateFunction(groupBitmap, UInt32)  
	            MATERIALIZED base64Decode(user)
)
ENGINE = ReplicatedMergeTree('xxx', '{replica}')  
PARTITION BY ds 
ORDER BY (ds) 
SETTINGS index_granularity = 8192;

Is it true that this table will be created? There will be the following error:
Conversion from String to AggregateFunction(groupBitmap, UInt32) is not supported

**Comment by zhicwu** [comment]
@litaoyx, thanks for sharing your solution. I read through your blog and was able to add RoaringBitmap support. One thing I want to clarify is that we don't need a base64 encoded string, since we can insert serialized value into AggregateFunction column directly. I guess the error you met earlier is related to the `TabSeparatedWithNamesAndTypes` format used by JDBC driver, which requires additional steps for escaping. Anyway, I'll submit a PR to address this later today.

**Comment by zhanglistar** [comment]
> @litaoyx, thanks for sharing your solution. I read through your blog and was able to add RoaringBitmap support. One thing I want to clarify is that we don't need a base64 encoded string, since we can insert serialized value into AggregateFunction column directly. I guess the error you met earlier is related to the `TabSeparatedWithNamesAndTypes` format used by JDBC driver, which requires additional steps for escaping. Anyway, I'll submit a PR to address this later today.

@zhicwu where is the PR?

**Comment by zhicwu** [comment]
@zhanglistar, [this](https://github.com/ClickHouse/clickhouse-jdbc/pull/596) is the PR. You may use the feature in jdbc driver 0.3.0.

**Comment by readme2gh** [comment]
> I implemented a custom serialization roaringbitmap method in spark to make the serialization structure compatible with the roaringbitmap structure in clickhouse. For details, please refer to the article: https://blog.csdn.net/qq_27639777/article/details/111005838

i follow your step,but the udf "rbm_init" comes error
java.lang.Exception: Invalid number of arguments for function rbm_init
