### ISSUE TITLE
Clickhouse backup/restore

### ISSUE THREAD

**Issue by lvdombrkr89** [ClickHouse/ClickHouse#16807]
Hello all,

Can i backup Clickhouse just with scp /var/lib/clickhouse/data  /var/lib/clickhouse/metadata to remote server?
And when i will need to restore just switch existing /data /metadata folders with from remote server?

It should work like this?

Thanks

**Comment by filimonov** [comment]
1) In newer versions (with database engine = Atomic) it's also `/var/lib/clickhouse/store`
2) when multidisk setup is used you need to repeat that for every disk
3) you can safely take the state of those folders only when clickhouse-server is stopped and `sync` command fired. For taking snapshots of active table there is a FREEZE PARTITION command (it will do 
4) to restoring Replicated tables will require recreating the tables and reattaching parts. 

Please check up that project: https://github.com/AlexAkulov/clickhouse-backup 
it help to automate that tasks.

**Comment by lvdombrkr89** [comment]
@filimonov  thanks for quick answer.
so in short it means if im stoping cilckhouse-server before rsync /data /metadata i should be fine later just restore this folders with correct rights, correct?

how i can find is there any  replicated tables? this is legacy db not created be me and its first time when i use clickhouse

**Comment by filimonov** [comment]
> so in short it means if im stoping cilckhouse-server before rsync /data /metadata i should be fine later just restore this folders with correct rights, correct?

If you don't use zookeeper / replicated tables - yes.

> how i can find is there any replicated tables? this is legacy db not created be me and its first time when i use clickhouse

```
grep -R Replicated /var/lib/clickhouse/metadata 
```
or 

```
SELECT * FROM system.tables where engine like 'Replicated%'
```
