### ISSUE TITLE
How to delete data from a Join Engine?

### ISSUE THREAD

**Issue by ZonghaoWang** [ClickHouse/ClickHouse#16831]
Make sure to check documentation https://clickhouse.yandex/docs/en/ first. If the question is concise and probably has a short answer, asking it in Telegram chat https://telegram.me/clickhouse_en is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

If you still prefer GitHub issues, remove all this text and ask your question here.

**Comment by ZonghaoWang** [comment]
Hi, I take join engine, to use the feature 'use_last_row', but how I can delete the old data, and the file in disk can not delete auto?

**Comment by alexey-milovidov** [comment]
There is no way to delete data from Join engine.
