### ISSUE TITLE
Use MaterializeMySQL synchronization problem

### ISSUE THREAD

**Issue by rjfh1980s** [ClickHouse/ClickHouse#16835]
When I used ClickHouse's MaterializeMySQL feature to synchronize data from MySQL to ClickHouse, I had some problems. The Click House version I'm using is 20.10.3.30, and the MySQL version I'm using is 5.7.28-log.

The SQL statement I executed is as follows:
> SET allow_experimental_database_materialize_mysql = 1;
drop database if exists ck_test;
CREATE DATABASE if not exists ck_test ENGINE = MaterializeMySQL('x.x.x.x:3306', 'test', 'user', 'test');

After I executed the SQL statement, I saw the following information from the error log /var/log/clickhouse-server/clickhouse-server.err. Log:

> 2020.11.10 20:27:39.611578 [ 33057 ] {} <Error> MaterializeMySQLSyncThread: Code: 20, e.displayText() = DB::Exception: mysqlxx::UseQueryResult contains 4 columns while 2 expected, Stack trace (when copying this message, always include the lines below):

> 0. DB::MySQLBlockInputStream::MySQLBlockInputStream(mysqlxx::Pool::Entry const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Block const&, unsigned long, bool) @ 0xe587457 in /usr/bin/clickhouse

> 1. DB::MaterializeMetadata::MaterializeMetadata(mysqlxx::Pool::Entry&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xdb1cbf3 in /usr/bin/clickhouse

> 2. DB::MaterializeMySQLSyncThread::prepareSynchronized(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xdaf8bf1 in /usr/bin/clickhouse

> 3. DB::MaterializeMySQLSyncThread::synchronization(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xdaf836a in /usr/bin/clickhouse

> 4. ? @ 0xdb1480d in /usr/bin/clickhouse

> 5. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x7b8963d in /usr/bin/clickhouse

> 6. ? @ 0x7b8d153 in /usr/bin/clickhouse

> 7. start_thread @ 0x7dd5 in /usr/lib64/libpthread-2.17.so

> 8. __clone @ 0xfdead in /usr/lib64/libc-2.17.so

>  (version 20.10.3.30 (official build))

Does anybody have a problem like this?

**Comment by zhang2014** [comment]
This problem looks like an unrecognized result set structure encountered when trying to fetch the MySQL table structure.

Can you try to execute `SHOW CREATE TABLE ${any_table}` ? And paste the result into issues?

**Comment by rjfh1980s** [comment]
> This problem looks like an unrecognized result set structure encountered when trying to fetch the MySQL table structure.
> 
> Can you try to execute `SHOW CREATE TABLE ${any_table}` ? And paste the result(or result set structure) into this issue?

I can see some other errors in the error log when I'm creating and deleting the database, and I don't know if this information is a bug or not?

> 2020.11.10 21:09:54.341567 [ 33246 ] {0320e286-1a5a-4c3c-bf3b-f0b4bd058247} <Error> executeQuery: Code: 390, e.displayText() = DB::Exception: There is no SHOW CREATE TABLE query for DatabaseMaterializeMySQL (version 20.10.3.30 (official build)) (from 192.168.88.1:49461) (in query: show create table `ck_test`.`t1` FORMAT TabSeparatedWithNamesAndTypes;), Stack trace (when copying this message, always include the lines below):

> 0. DB::IDatabase::getCreateTableQueryImpl(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context const&, bool) const @ 0xd7fbf64 in /usr/bin/clickhouse

> 1. DB::InterpreterShowCreateQuery::executeImpl() @ 0xdd82dbf in /usr/bin/clickhouse

> 2. DB::InterpreterShowCreateQuery::execute() @ 0xdd82668 in /usr/bin/clickhouse

> 3. ? @ 0xdec8f18 in /usr/bin/clickhouse

> 4. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, DB::Context&, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>) @ 0xdecbbcf in /usr/bin/clickhouse

> 5. DB::HTTPHandler::processQuery(DB::Context&, Poco::Net::HTTPServerRequest&, HTMLForm&, Poco::Net::HTTPServerResponse&, DB::HTTPHandler::Output&) @ 0xe51341f in /usr/bin/clickhouse

> 6. DB::HTTPHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&) @ 0xe51660c in /usr/bin/clickhouse

> 7. Poco::Net::HTTPServerConnection::run() @ 0x10d16595 in /usr/bin/clickhouse

> 8. Poco::Net::TCPServerConnection::start() @ 0x10d4dd6f in /usr/bin/clickhouse

> 9. Poco::Net::TCPServerDispatcher::run() @ 0x10d4f77e in /usr/bin/clickhouse

> 10. Poco::PooledThread::run() @ 0x10e80a39 in /usr/bin/clickhouse

> 11. Poco::ThreadImpl::runnableEntry(void*) @ 0x10e7c96a in /usr/bin/clickhouse

> 12. start_thread @ 0x7dd5 in /usr/lib64/libpthread-2.17.so

> 13. __clone @ 0xfdead in /usr/lib64/libc-2.17.so

> 2020.11.10 21:09:54.341659 [ 33246 ] {0320e286-1a5a-4c3c-bf3b-f0b4bd058247} <Error> DynamicQueryHandler: Code: 390, e.displayText() = DB::Exception: There is no SHOW CREATE TABLE query for DatabaseMaterializeMySQL, Stack trace (when copying this message, always include the lines below):

> 0. DB::IDatabase::getCreateTableQueryImpl(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context const&, bool) const @ 0xd7fbf64 in /usr/bin/clickhouse

> 1. DB::InterpreterShowCreateQuery::executeImpl() @ 0xdd82dbf in /usr/bin/clickhouse

> 2. DB::InterpreterShowCreateQuery::execute() @ 0xdd82668 in /usr/bin/clickhouse

> 3. ? @ 0xdec8f18 in /usr/bin/clickhouse

> 4. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, DB::Context&, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>) @ 0xdecbbcf in /usr/bin/clickhouse

> 5. DB::HTTPHandler::processQuery(DB::Context&, Poco::Net::HTTPServerRequest&, HTMLForm&, Poco::Net::HTTPServerResponse&, DB::HTTPHandler::Output&) @ 0xe51341f in /usr/bin/clickhouse

> 6. DB::HTTPHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&) @ 0xe51660c in /usr/bin/clickhouse

> 7. Poco::Net::HTTPServerConnection::run() @ 0x10d16595 in /usr/bin/clickhouse

> 8. Poco::Net::TCPServerConnection::start() @ 0x10d4dd6f in /usr/bin/clickhouse

> 9. Poco::Net::TCPServerDispatcher::run() @ 0x10d4f77e in /usr/bin/clickhouse

> 10. Poco::PooledThread::run() @ 0x10e80a39 in /usr/bin/clickhouse

> 11. Poco::ThreadImpl::runnableEntry(void*) @ 0x10e7c96a in /usr/bin/clickhouse

> 12. start_thread @ 0x7dd5 in /usr/lib64/libpthread-2.17.so

> 13. __clone @ 0xfdead in /usr/lib64/libc-2.17.so

 

> (version 20.10.3.30 (official build))

**Comment by zhang2014** [comment]
> I can see some other errors in the error log when I'm creating and deleting the database, and I don't know if this information is a bug or not? ck_test is another database that has been synchronized.

This needs to be execute in MySQL : )

**Comment by rjfh1980s** [comment]
> > I can see some other errors in the error log when I'm creating and deleting the database, and I don't know if this information is a bug or not? ck_test is another database that has been synchronized.
> 
> This needs to be execute in MySQL : )
> 
> by the way: MaterializeMySQL not support `SHOW CREATE TABLE` statement.

Thank you, I understand.
The create statement for one of the MySQL tables is:
> CREATE TABLE `t_circle_theme_liked_history` (
  `id` bigint(20) NOT NULL ,
  `customer_id` bigint(20) NOT NULL,
  `theme_id` bigint(20) NOT NULL ,
  `customer_name` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL ,
  `is_deleted` bit(1) NOT NULL DEFAULT b'0' ,
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  `modified_time` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_theme_liked_theme_id_customer_id` (`customer_id`,`theme_id`),
  KEY `idx_theme_liked_customer_id` (`theme_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC

In the database that requires synchronization, not all tables have primary keys.  

> There is no SHOW CREATE TABLE query for DatabaseMaterializeMySQL

The above mistakes were made many times,  I only executed it once.

**Comment by zhang2014** [comment]
For `SHOW CREATE TABLE t_circle_theme_liked_history`, what result set `structure` for return in MySQL?

It is like this?
```
+------------+------------------------------------------------------------------------------------------------------------------------------------------+
| Table      | Create Table                                                                                                                             |
+------------+------------------------------------------------------------------------------------------------------------------------------------------+
| t_circle_theme_liked_history | CREATE TABLE t_circle_theme_liked_history (
id bigint(20) NOT NULL ,
customer_id bigint(20) NOT NULL,
theme_id bigint(20) NOT NULL ,
customer_name varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL ,
is_deleted bit(1) NOT NULL DEFAULT b'0' ,
created_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ,
modified_time datetime DEFAULT NULL,
PRIMARY KEY (id),
UNIQUE KEY idx_theme_liked_theme_id_customer_id (customer_id,theme_id),
KEY idx_theme_liked_customer_id (theme_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC |
+------------+------------------------------------------------------------------------------------------------------------------------------------------+
```

**Comment by rjfh1980s** [comment]
> SHOW CREATE TABLE t_circle_theme_liked_history

Yes, that's right

**Comment by zhang2014** [comment]
Can you try to execute `SHOW MASTER LOGS`?  And paste the  result set structure into this issue?

**Comment by rjfh1980s** [comment]
> SHOW MASTER LOGS

When I finish executing "SHOW MASTER LOGS;" statement, the output is:

> Log_name,File_size
mysql-bin.000001,177
mysql-bin.000002,177
mysql-bin.000003,1037
mysql-bin.000004,524475347
mysql-bin.000005,524671724
mysql-bin.000006,524845376
mysql-bin.000007,525021222
mysql-bin.000008,524724240
mysql-bin.000009,524563886
mysql-bin.000010,524964100
mysql-bin.000011,525310791
mysql-bin.000012,525744588
mysql-bin.000013,524939033
mysql-bin.000014,524969808
mysql-bin.000015,524473585
mysql-bin.000016,525319283
mysql-bin.000017,525075521
mysql-bin.000018,524892638
mysql-bin.000019,524435270
mysql-bin.000020,524509133
mysql-bin.000021,524879477
mysql-bin.000022,525239481
mysql-bin.000023,524678582
mysql-bin.000024,524322240
mysql-bin.000025,524633234
mysql-bin.000026,524417379
mysql-bin.000027,524628706
mysql-bin.000028,524542980
mysql-bin.000029,524497235
mysql-bin.000030,524733838
mysql-bin.000031,524723275
mysql-bin.000032,524882214
mysql-bin.000033,524793112
mysql-bin.000034,526055878
mysql-bin.000035,524664953
mysql-bin.000036,4051354640
mysql-bin.000037,524475743
mysql-bin.000038,524566278
mysql-bin.000039,524288160
mysql-bin.000040,1574100246
mysql-bin.000041,1750912584
mysql-bin.000042,1457076298
mysql-bin.000043,1372661771
mysql-bin.000044,1624494124
mysql-bin.000045,2772861102
mysql-bin.000046,2922111127
mysql-bin.000047,2969755536
mysql-bin.000048,3124699092
mysql-bin.000049,1586616489
mysql-bin.000050,524290610
mysql-bin.000051,1812535096
mysql-bin.000052,1522364140
mysql-bin.000053,23330492728
mysql-bin.000054,1385510891
mysql-bin.000055,1518757817
mysql-bin.000056,1437369463
mysql-bin.000057,1334995297
mysql-bin.000058,1579220189
mysql-bin.000059,1619583036
mysql-bin.000060,1151549702
mysql-bin.000061,1446438315
mysql-bin.000062,1562165868
mysql-bin.000063,1389940907
mysql-bin.000064,925647247
mysql-bin.000065,1478854003
mysql-bin.000066,1702738201
mysql-bin.000067,1550019796
mysql-bin.000068,524291843
mysql-bin.000069,462841417
mysql-bin.000070,524289044
mysql-bin.000071,524289273
mysql-bin.000072,524290065
mysql-bin.000073,524288524
mysql-bin.000074,524288471
mysql-bin.000075,303418678
mysql-bin.000076,524289107
mysql-bin.000077,524288391
mysql-bin.000078,138665594

**Comment by rjfh1980s** [comment]
> Can you try to execute `SHOW MASTER LOGS`? And paste the result set structure into this issue?

Hello, is there any solution to the above question?
Do I need to upgrade ClickHouse or change any configuration?

**Comment by zhang2014** [comment]
It's in my TODO list, and I'm trying to reproduce it in my environment : )

**Comment by Tffy** [comment]
I have a same problem, but another database  in same instance can sync. MySQL version is 5.7.26-29-31.37-log Percona XtraDB Cluster binary
