### ISSUE TITLE
can't connect to clickhouse-server

### ISSUE THREAD

**Issue by anzi1983** [ClickHouse/ClickHouse#16830]
![image](https://user-images.githubusercontent.com/28052900/98648416-39a01080-2371-11eb-94f9-b750ed4ac262.png)
connect to

**Comment by ucasFL** [comment]
Because your server does not start up succussfully.

**Comment by trollhe** [comment]
you s

> ![image](https://user-images.githubusercontent.com/28052900/98648416-39a01080-2371-11eb-94f9-b750ed4ac262.png)
> connect to

Are you starting in the right way?

try use clickhouse user  to start service , or  'service clickhouse-server start'?

**Comment by hexiaoting** [comment]
@anzi1983 check your configurate file: config1.xml

Chinese: 检查一下你的配置文件config1.xml, 里面的<compression incl="clickhouse_compression">和<remote_servers incl="clickhouse_remote_servers">是否配置正确。
