### ISSUE TITLE
clickhouse集群规划，应该如何考虑做磁盘raid和集群shard，replica?

### ISSUE THREAD

**Issue by trollhe** [ClickHouse/ClickHouse#16832]
你好：

    我有一批下线的数据服务器，每台服务器24块磁盘，想将它们用来搭建clickhouse集群，正在考虑做存储策略。有几个问题需要向大家请教：
1.请问是否可以不做raid0-50，而在clickhouse集群中通过规划shard和副本数来保障冗余？
2.clickhouse支持多目录同时读写吗？
3.clickhouse可以像数据仓库一样做olap，支持几千张表，几百个逻辑分析计算吗？
4.有没有clickhouse直接用来做pb容量数据仓库的案例？

**Comment by akuzm** [comment]
Machine translation:

Hello there:

I have a batch of offline data servers, each with 24 disks. I want to use them to build a clickhouse cluster. I am considering a storage strategy. There are several questions to ask you:
1. Is it possible to avoid raid0-50, and plan the number of shards and replicas in the clickhouse cluster to ensure redundancy?
2. Does clickhouse support simultaneous reading and writing of multiple directories?
3. Can clickhouse do olap like a data warehouse, support thousands of tables and hundreds of logical analysis calculations?
4. Is there a case where clickhouse is directly used as a pb capacity data warehouse?

**Comment by alexey-milovidov** [comment]
1. Yes, you can avoid using RAID, but then I recommend to have at least three replicas to ensure redundancy.
2. Yes, it is configured in https://clickhouse.tech/docs/en/engines/table-engines/mergetree-family/mergetree/#table_engine-mergetree-multiple-volumes_configure
3. Most likely.
4. Yes, we use it in Yandex Metrica for more than hundred petabytes database (measured by uncompressed size).
