### ISSUE TITLE
Code: 354. DB::Exception: Received from localhost:9800. DB::Exception: inflate failed: buffer error: While executing File.

### ISSUE THREAD

**Issue by trollhe** [ClickHouse/ClickHouse#16848]
Hello,

   i import to clickhouse,throw fllowing error:

```
Code: 354. DB::Exception: Received from localhost:9800. DB::Exception: inflate failed: buffer error: While executing File.
```

**Comment by akuzm** [comment]
Do you have some sample data + queries that we can use to reproduce the problem?

**Comment by trollhe** [comment]
> Do you have some sample data + queries that we can use to reproduce the problem?


thank you,my data and query :

data sample
data_file.gz
```
aaa|bbbb|cccc|ddd|eeee
```

import script
```
insert into logs.user_logs_real
select * from file('user_logs_real/*2020061113220100*.gz','CSV','aa String,bb String,cc String,dd String,ee String,ff String,gg String,hh String,ii String') ;
```

**Comment by alexey-milovidov** [comment]
It happens if gzip file is broken or has unsupported format.

**Comment by jilio** [comment]
Hello!
Facing the same issue.
If I decompress my `data.tsv.gz` (~17gb) file everything works fine.
I tried to compress decompressed file with different tools (e.g. pigz) and insert data from newly compressed file again and this error pops up again.
