### ISSUE TITLE
Code: 252. DB::Exception: Received from localhost:9800. DB::Exception: Too many parts (301). Merges are processing significantly slower than inserts.: While executing SinkToOutputStream.

### ISSUE THREAD

**Issue by trollhe** [ClickHouse/ClickHouse#16847]
Hello,

    i import data to clickhouse,throw the error:
```
Code: 252. DB::Exception: Received from localhost:9800. DB::Exception: Too many parts (301). Merges are processing significantly slower than inserts.: While executing SinkToOutputStream.
```

**Comment by akuzm** [comment]
Please refer to these comments explaining the possible reasons for this problem:
https://github.com/ClickHouse/ClickHouse/issues/3174#issuecomment-423435071
https://github.com/ClickHouse/ClickHouse/issues/6720#issuecomment-526045768
