### ISSUE TITLE
how to remove the locked table

### ISSUE THREAD

**Issue by vegastar002** [ClickHouse/ClickHouse#16851]
I use dataX to import data from oracle to clickhouse, will write to tb1 , but  report no right to write clickhouse.  then  tb1 locked , cann't sql ,  cann't delete, that's why?
my config.xml  and user.xml is default setting.

**Comment by vegastar002** [comment]
Ooooo, beacause I use tinyLog,  why  dataX  cann't write tinyLog table?  
I change to mergeTree it's ok.

**Comment by vegastar002** [comment]
but the locked table still cann't use and delete . How to delete it ?

**Comment by akuzm** [comment]
What version of ClickHouse do you use? Do you have some example queries that can reproduce the problem?

**Comment by vegastar002** [comment]
> What version of ClickHouse do you use? Do you have some example queries that can reproduce the problem?

my version is clickhouse 20.8. 
the sql of tb1 :
create table tb1
(
)
engine = TinyLog

then I use dataX  start import data, it will report error 
[https://note.youdao.com/ynoteshare1/index.html?id=d28b46ed74987c2279700496d9369fff&type=note](url)
