### ISSUE TITLE
ORC + HDFS = memory limit exceeded

### ISSUE THREAD

**Issue by lishoulian** [ClickHouse/ClickHouse#16857]
error：
```
DB::Exception: Memory limit (for query) exceeded: would use 256.34 GiB (attempt to allocate chunk of 206158431632 bytes), maximum: 186.26 GiB: While executing HDFS
```
set：
```
SET max_memory_usage =200000000000;
set max_bytes_before_external_group_by=100000000000;
set max_threads=1;
Set enable_scalar_subquery_optimization =0
Set distributed_aggregation_memory_efficient=1
```

execute sql:
```
SELECT phone , SUM(count) totalCount, count(1) days FROM tb_sql5and6 WHERE time >=20200707 AND time <= 20200731 
AND plate = '***' AND plate_type ='2' GROUP BY phone ORDER BY days DESC, totalCount DESC limit 100;
```
The same error is reported after the execution
table size：300GB
create table sql： 
```
CREATE TABLE tb_sql
(
plate String,
plate_type String,
phone String,
count Int32,
imsi String,
fullcount Int32,
time Int32
)
ENGINE = HDFS('hdfs://hacluster/user/clickhouse/table8', 'ORC')
```
ClickHouse client version 20.8.3.18.，

**Comment by lishoulian** [comment]
报错：
DB::Exception: Memory limit (for query) exceeded: would use 256.34 GiB (attempt to allocate chunk of 206158431632 bytes), maximum: 186.26 GiB: While executing HDFS
解决：
SET max_memory_usage =200000000000;
set max_bytes_before_external_group_by=100000000000;
set max_threads=1;
Set enable_scalar_subquery_optimization =0
Set distributed_aggregation_memory_efficient=1
sql:SELECT phone , SUM(count) totalCount, count(1) days FROM  tb_sql5and6  WHERE time >=20200707 AND time <= 20200731 AND plate = '京C5C5E0' AND plate_type ='2' GROUP BY phone  ORDER BY days DESC, totalCount DESC  limit 100;

继续执行后还是报和上面同样的错

**Comment by akuzm** [comment]
If you set `max_bytes_before_external_group_by` lower, say, 50 GB -- does it still fail? 10 GB? 

My guess is that this setting is based on the size of input rows and not the amount of required memory, which might turn out to be larger.

**Comment by filimonov** [comment]
See https://github.com/ClickHouse/ClickHouse/issues/10461#issuecomment-623006030

**Comment by lishoulian** [comment]
> If you set `max_bytes_before_external_group_by` lower, say, 50 GB -- does it still fail? 10 GB?
> 
> My guess is that this setting is based on the size of input rows and not the amount of required memory, which might turn out to be larger.
I set it to a smaller value, and the same error is reported.
There's 6988076760 rows in the table.

**Comment by lishoulian** [comment]
> See [#10461 (comment)](https://github.com/ClickHouse/ClickHouse/issues/10461#issuecomment-623006030)
So how am I supposed to fix it?The format of my table needs to be changed？

**Comment by filimonov** [comment]
> > See [#10461 (comment)](https://github.com/ClickHouse/ClickHouse/issues/10461#issuecomment-623006030)
> 
> So how am I supposed to fix it?The format of my table needs to be changed？

There are no good fixed for now. Use another format, or smaller files, or install more ram.

**Comment by lishoulian** [comment]
> > > See [#10461 (comment)](https://github.com/ClickHouse/ClickHouse/issues/10461#issuecomment-623006030)
> > 
> > 
> > So how am I supposed to fix it?The format of my table needs to be changed？
> 
> There are no good fixed for now. Use another format, or smaller files, or install more ram.

Okay, thank you，filimonov

**Comment by alexey-milovidov** [comment]
https://github.com/ClickHouse/ClickHouse/pull/20128#issuecomment-932892698
