### ISSUE TITLE
my settings Multiple Disk Use To Clickhouse, but data writed not there disk.

### ISSUE THREAD

**Issue by trollhe** [ClickHouse/ClickHouse#16850]
my settings:
config.d/storage.xml
```
<?xml version="1.0"?>
<yandex>
	<storage_configuration>
		<disks>
			<hdd1>
				<path>/mnt/hdd1/clickhouse/</path>
				<keep_free_space_bytes>102400</keep_free_space_bytes>
			</hdd1>
			<hdd2>
				<path>/mnt/hdd2/clickhouse/</path>
				<keep_free_space_bytes>102400</keep_free_space_bytes>
			</hdd2>
			<hdd4>
				<path>/mnt/hdd4/clickhouse/</path>
				<keep_free_space_bytes>102400</keep_free_space_bytes>
			</hdd4>
			<hdd4>
				<path>/mnt/hdd4/clickhouse/</path>
				<keep_free_space_bytes>102400</keep_free_space_bytes>
			</hdd4>
		</disks>
	</storage_configuration>
</yandex>
```

but no data writed to  there disk,only write to default disk.

**Comment by akuzm** [comment]
You have to also configure a Storage Policy that determines how the data is spread across the disks.
Please refer to this guide: https://altinity.com/blog/2019/11/29/amplifying-clickhouse-capacity-with-multi-volume-storage-part-2

**Comment by trollhe** [comment]
> You have to also configure a Storage Policy that determines how the data is spread across the disks.
> Please refer to this guide: https://altinity.com/blog/2019/11/29/amplifying-clickhouse-capacity-with-multi-volume-storage-part-2

thank u
