### ISSUE TITLE
update/delete operation ,connection will die

### ISSUE THREAD

**Issue by 1850177529** [ClickHouse/ClickHouse#16868]
create table with nullable type .here:
CREATE TABLE base_line
(
   id                  String not null,
   name                 Nullable(String),
   control_area_id      Nullable(String),
   create_date          Nullable(datetime),
   modify_date          Nullable(datetime),
   description         Nullable(String)
)ENGINE = ReplacingMergeTree()
order by tuple();

but i use update/delete sql to change data,clickhouse will die.i fetcherror logs like this:
![image](https://user-images.githubusercontent.com/42259161/98805500-9fb09480-2452-11eb-8e14-746e1589e01a.png)

**Comment by akuzm** [comment]
Do you have some simplified query + data that allows you to consistently reproduce the problem? It would be very helpful if we could reproduce it as well.

Also please show the query that fails, and attach full text of exception -- the message itself + all subsequent stack trace lines that start with 1., 2., 3., etc.
