### ISSUE TITLE
Inserts queries are stuck between Distributed and MergeTree tables

### ISSUE THREAD

**Issue by vladimir-miller** [ClickHouse/ClickHouse#16897]
ClickHouse version is 20.3.8.53

`CREATE TABLE local.a (
 t DateTime,
 tm Date MATERIALIZED toDate(t)
) ENGINE = ReplicatedMergeTree() ;`

`CREATE TABLE write.a (
  t DateTime,
  tm Date
) ENGINE = Distributed(cluster, local, a);`

I send inserts in the table `write.a` with both field `t` and `tm` and now data hangs. ClickHouse trying to send it to the table `local.a`, but field `tm` rises error  `Cannot insert column tm, because it is MATERIALIZED column`.
I try system queries `STOP DISTRIBUTED SENDS write.a`, but its doesn't work for me - I need to delete this queries.
Trying to reboot ClickHouse - does not work.
Has anyone got any ideas how to fix it?
Thanks in advance.

**Comment by alexey-milovidov** [comment]
It's not allowed to INSERT into MATERIALIZED column.

Resolution:
1. Update ClickHouse to the latest version.
2. Replace MATERIALIZED column to DEFAULT column with ALTER query to be able to insert data to it.

**Comment by alexey-milovidov** [comment]
Another clarification from @azat:
\- you can make column MATERIALIZED in the Distributed table identically to the local table - then everything will work as expected.

**Comment by azat** [comment]
Actually why Distributed does not respect `insert_allow_materialized_columns` it? Let's try #23349
