### ISSUE TITLE
Amount of memory determined incorrectly in an LXC container

### ISSUE THREAD

**Issue by akuzm** [ClickHouse/ClickHouse#16918]
A user reported that ClickHouse server incorrectly determines the amount of memory available to an LXC container, using the total amount of host memory instead. We could use `/proc/meminfo` which reports the correct value.

Look at `getMemoryAmountOrZero()`.

Somewhat related ticket about cgroups limits: https://github.com/ClickHouse/ClickHouse/issues/2261

**Comment by alexey-milovidov** [comment]
The user who used LXC reported that he no longer use LXC and the issue is no longer relevant.

**Comment by alexey-milovidov** [comment]
If someone will send a pull request it will be appreciated.
