### ISSUE TITLE
What's the difference between nested structure and array?

### ISSUE THREAD

**Issue by ahutsunshine** [ClickHouse/ClickHouse#16916]
Nested structure: https://clickhouse.tech/docs/en/sql-reference/data-types/nested-data-structures/nested/

When I used nested structure to create table, I found the implementation of nested structure is array. So my question is what's the difference between them if we use two same array to implement it, such as query, performance or insert data?

Created sql:
`
CREATE TABLE nested_test 
(
    `__name__` String,
    `unixtime` DateTime('Etc/UTC'),
    `labels` Nested(
    key Nullable(String),
    value Nullable(String))
)
ENGINE = ReplicatedMergeTree('/clickhouse/{installation}/{cluster}/tables/{shard}/{database}/{table}', '{replica}')
PARTITION BY toYYYYMMDD(unixtime)
ORDER BY (__name__, unixtime)
SETTINGS index_granularity = 8192
`

Real table sql:
`
CREATE TABLE nested_test (`__name__` String, `unixtime` DateTime('Etc/UTC'), `labels.key` Array(Nullable(String)), `labels.value` Array(Nullable(String))) ENGINE = ReplicatedMergeTree('/clickhouse/{installation}/{cluster}/tables/{shard}/{database}/{table}', '{replica}') PARTITION BY toYYYYMMDD(unixtime) ORDER BY (__name__, unixtime) SETTINGS index_granularity = 8192
`

**Comment by den-crane** [comment]
No difference.
Nested it's a syntax sugar for a `create table` command and it's stored as arrays.

Nested creates columns with a dot in names (xxx.key , xxx.value). Such columns are treated in a special way during insert. CH validates that number of elements is the same in sub-columns of xxx.

https://github.com/ClickHouse/ClickHouse/issues/15190
