### ISSUE TITLE
MaterializeMySQL while query got error.

### ISSUE THREAD

**Issue by 7omsxx** [ClickHouse/ClickHouse#16923]
MaterializeMySQLSyncThread(): Query EXTERNAL DDL FROM MySQL(bear, clickhouse) B wasn't finished successfully: Code: 62, 
e.displayText() = DB::Exception: Syntax error: failed at position 105 ('B'): B. Expected one of: RENAME DATABASE, TRUNCATE, RENAME TABLE, DROP query, RENAME DICTIONARY,
 DETACH, RENAME query, DROP, create query, CREATE, EXCHANGE TABLES, ALTER TABLE, alter query,
 Stack trace (when copying this message, always include the lines below):

0. DB::parseQueryAndMovePosition(DB::IParser&, char const*&, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, 
unsigned long, unsigned long) @ 0xe937819 in /usr/bin/clickhouse
1. ? @ 0xdec81b7 in /usr/bin/clickhouse
2. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool) @ 0xdec7dbd in /usr/bin/clickhouse
3. ? @ 0xdaff0e4 in /usr/bin/clickhouse
4. DB::MaterializeMySQLSyncThread::onEvent(DB::MaterializeMySQLSyncThread::Buffers&, std::__1::shared_ptr<DB::MySQLReplication::EventBase> const&, DB::MaterializeMetadata&) @ 0xdafb2a2 in /usr/bin/clickhouse
5. DB::MaterializeMySQLSyncThread::synchronization(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xdaf85fc in /usr/bin/clickhouse
6. ? @ 0xdb1480d in /usr/bin/clickhouse
7. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x7b8963d in /usr/bin/clickhouse
8. ? @ 0x7b8d153 in /usr/bin/clickhouse
9. start_thread @ 0x7dd5 in /usr/lib64/libpthread-2.17.so
10. __clone @ 0xfdead in /usr/lib64/libc-2.17.so
 (version 20.10.3.30 (official build))
2020.11.12 17:37:57.583104 [ 25151 ] {} <Error> MaterializeMySQLSyncThread: Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 105 ('B'): B. Expected one of: 
RENAME DATABASE, TRUNCATE, RENAME TABLE, DROP query, RENAME DICTIONARY, DETACH, RENAME query, DROP, create query, CREATE, EXCHANGE TABLES, ALTER TABLE, alter query, Stack trac
e (when copying this message, always include the lines below):

0. DB::parseQueryAndMovePosition(DB::IParser&, char const*&, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, unsigned long, unsigned long) @ 0xe937819 in /usr/bin/clickhouse
1. ? @ 0xdec81b7 in /usr/bin/clickhouse
2. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool) @ 0xdec7dbd in /usr/bin/clickhouse
3. ? @ 0xdaff0e4 in /usr/bin/clickhouse
4. DB::MaterializeMySQLSyncThread::onEvent(DB::MaterializeMySQLSyncThread::Buffers&, std::__1::shared_ptr<DB::MySQLReplication::EventBase> const&, DB::MaterializeMetadata&) @ 0xdafb2a2 in /usr/bin/clickhouse
5. DB::MaterializeMySQLSyncThread::synchronization(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xdaf85fc in /usr/bin/clickhouse
6. ? @ 0xdb1480d in /usr/bin/clickhouse
7. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x7b8963d in /usr/bin/clickhouse
8. ? @ 0x7b8d153 in /usr/bin/clickhouse
9. start_thread @ 0x7dd5 in /usr/lib64/libpthread-2.17.so
10. __clone @ 0xfdead in /usr/lib64/libc-2.17.so
 (version 20.10.3.30 (official build))
2020.11.12 17:37:57.583469 [ 25151 ] {} <Error> MaterializeMySQLSyncThread: Code: 33, e.displayText() = DB::Exception: Cannot read all data. Bytes read: 1. Bytes expected: 5., Stack trace (when copying this message, always include the lines below):

**Comment by zhang2014** [comment]
The reason for this problem may be binlog_checksum = NONE, you can check it with SHOW VARIABLES WHERE Variable_name ='binlog_checksum';

**Comment by 7omsxx** [comment]
@zhang2014  tks，question solved
