### ISSUE TITLE
Bad size of marks file on Index

### ISSUE THREAD

**Issue by BaptisteBdn** [ClickHouse/ClickHouse#16925]
**Describe the bug**
Hello, 
I've been trying to setup a clickhouse server on multiple nodes and while it is working well most of the time, sometimes the SELECT is not working.
```
SELECT max(timestamp)
FROM dns.requests
WHERE (timestamp >= '2020-11-09 23:00:00') AND (timestamp <= '2020-11-09 23:59:59')


Received exception from server (version 20.10.3):
Code: 246. DB::Exception: Received from xxxx:9000. DB::Exception: Received from xxxx:9000. DB::Exception: Bad size of marks file '/var/lib/clickhouse/store/0a0/0a0b87aa-c65c-4c7c-a3ce-cedd7d5e964a/20201109_3333225_3410146_61/skp_idx_timestamp_idx.mrk3': 48, must be: 72. 
```
There is no problem when I insert data, there is almost 3B rows in the cluster and some requests are working and some are not.

**How to reproduce**
ClickHouse server version 20.10.3.30 (official build).
The configs I'm using on the cluster are the following : 
```
CREATE DATABASE shard;
CREATE TABLE shard.requests
(
    timestamp DateTime('UTC'),
    name String,
    products Array(String),
    INDEX timestamp_idx timestamp TYPE minmax GRANULARITY 4
)
ENGINE = MergeTree()
ORDER BY (name, timestamp, intHash32(timestamp))
SAMPLE BY intHash32(timestamp)
PARTITION BY toYYYYMMDD(timestamp)
TTL timestamp + INTERVAL 60 DAY TO VOLUME 'cold_volume', 
    timestamp + INTERVAL 180 DAY DELETE
SETTINGS storage_policy='policy_hot_and_cold';

CREATE DATABASE items;
CREATE TABLE items.requests
(
    timestamp DateTime('UTC'),
    name String,
    products Array(String),
)
ENGINE = Distributed('items_cluster', '', requests, rand());
```
The request I use is the following : 
```
SELECT max(timestamp)
FROM items.requests
WHERE (timestamp >= '2020-11-09 23:00:00') AND (timestamp <= '2020-11-09 23:59:59')
```
However it can works with other timestamps...

**Expected behavior**
The request should work with whatever timestamp I use.

**Error message and/or stacktrace**
In clickhouse log files, I have the following error :
```
2020.11.12 11:26:59.925027 [ 29404 ] {f0852a67-868b-44a5-a41f-376ef2be3eaf} <Error> TCPHandler: Code: 246, e.displayText() = DB::Exception: Received from xxxx:9000. DB::Exception: Bad size of marks file '/var/lib/clickhouse/store/0a0/0a0b87aa-c65c-4c7c-a3ce-cedd7d5e964a/20201109_3333225_3410146_61/skp_idx_timestamp_idx.mrk3': 48, must be: 72. Stack trace:

0. DB::MergeTreeMarksLoader::loadMarksImpl() @ 0xe3facdc in /usr/bin/clickhouse
1. DB::MergeTreeMarksLoader::loadMarks() @ 0xe3f9f99 in /usr/bin/clickhouse
2. DB::MergeTreeReaderStream::MergeTreeReaderStream(std::__1::shared_ptr<DB::IDisk>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange> > const&, DB::MergeTreeReaderSettings const&, DB::MarkCache*, DB::UncompressedCache*, unsigned long, DB::MergeTreeIndexGranularityInfo const*, std::__1::function<void (DB::ReadBufferFromFileBase::ProfileInfo)> const&, int) @ 0xe4014e1 in /usr/bin/clickhouse
3. DB::MergeTreeIndexReader::MergeTreeIndexReader(std::__1::shared_ptr<DB::IMergeTreeIndex const>, std::__1::shared_ptr<DB::IMergeTreeDataPart const>, unsigned long, std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange> > const&, DB::MergeTreeReaderSettings) @ 0xe3b3e15 in /usr/bin/clickhouse
4. DB::MergeTreeDataSelectExecutor::filterMarksUsingIndex(std::__1::shared_ptr<DB::IMergeTreeIndex const>, std::__1::shared_ptr<DB::IMergeTreeIndexCondition>, std::__1::shared_ptr<DB::IMergeTreeDataPart const>, std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange> > const&, DB::Settings const&, DB::MergeTreeReaderSettings const&, Poco::Logger*) @ 0xe39eefb in /usr/bin/clickhouse
5. ? @ 0xe392c4e in /usr/bin/clickhouse
6. ? @ 0xe3a3c47 in /usr/bin/clickhouse
7. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0x7b8c17d in /usr/bin/clickhouse
8. std::__1::__function::__func<ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()&&...)::'lambda'(), std::__1::allocator<ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()&&...)::'lambda'()>, void ()>::operator()() @ 0x7b8e67a in /usr/bin/clickhouse
9. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x7b8963d in /usr/bin/clickhouse
10. ? @ 0x7b8d153 in /usr/bin/clickhouse
11. start_thread @ 0x7fa3 in /lib/x86_64-linux-gnu/libpthread-2.28.so
12. clone @ 0xf94cf in /lib/x86_64-linux-gnu/libc-2.28.so
: While executing Remote, Stack trace:

0. DB::readException(DB::ReadBuffer&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x7ba1f7f in /usr/bin/clickhouse
1. DB::Connection::receiveException() @ 0xe4e9134 in /usr/bin/clickhouse
2. DB::Connection::receivePacket() @ 0xe4efc5c in /usr/bin/clickhouse
3. DB::MultiplexedConnections::receivePacketUnlocked() @ 0xe50081a in /usr/bin/clickhouse
4. DB::MultiplexedConnections::receivePacket() @ 0xe500742 in /usr/bin/clickhouse
5. DB::RemoteQueryExecutor::read() @ 0xd7327fa in /usr/bin/clickhouse
6. DB::RemoteSource::generate() @ 0xe716b16 in /usr/bin/clickhouse
7. DB::ISource::work() @ 0xe5b3a5a in /usr/bin/clickhouse
8. DB::SourceWithProgress::work() @ 0xe71c51a in /usr/bin/clickhouse
9. ? @ 0xe5ed84c in /usr/bin/clickhouse
10. DB::PipelineExecutor::executeStepImpl(unsigned long, unsigned long, std::__1::atomic<bool>*) @ 0xe5ea4d6 in /usr/bin/clickhouse
11. ? @ 0xe5efa3b in /usr/bin/clickhouse
12. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x7b8963d in /usr/bin/clickhouse
13. ? @ 0x7b8d153 in /usr/bin/clickhouse
14. start_thread @ 0x7fa3 in /lib/x86_64-linux-gnu/libpthread-2.28.so
15. clone @ 0xf94cf in /lib/x86_64-linux-gnu/libc-2.28.so
```

**Additional context**
I can see the file /`var/lib/clickhouse/store/0a0/0a0b87aa-c65c-4c7c-a3ce-cedd7d5e964a/20201109_3333225_3410146_61/skp_idx_timestamp_idx.mrk3':` in one of my clickhouse node and if I delete it it seems to be working but I don't know what I'm losing when I do that and it doesn't look very stable that way.

Perhaps I misunderstood something when I created the Index and the configuration I used is not safe ? 
Thank you for your help.

**Comment by den-crane** [comment]
Wondering, your table is partitioned `PARTITION BY toYYYYMMDD(timestamp)` and sorted by `ORDER BY (name, timestamp,`.

Why do you need additional `INDEX timestamp_idx timestamp TYPE minmax GRANULARITY 4`  ?

Does it help at all?

>Bad size of marks file '/var/lib/clickhouse/store/0a0/0a0b87aa-c65c-4c7c-a3ce-cedd7d5e964a
>/20201109_3333225_3410146_61/skp_idx_timestamp_idx.mrk3': 48, must be: 72.

**Comment by BaptisteBdn** [comment]
From what I understood, the Index created with `ORDER BY (name, timestamp, intHash32(timestamp))` would be different from the one I created manually with `INDEX timestamp_idx timestamp TYPE minmax GRANULARITY 4`.

> Does it help at all?

Honestly I'm not sure, I'm still experimenting with clickhouse right now so I'm trying to optimise the tables for the futur.
The tables I shared are only a part of the real tables (missing only somes common fields) and I know that in the futur I will request most of the time the fields `timestamp` and `name`. That is why I created the Index `timestamp_idx`.

Is it possible that the `ORDER BY` and the `INDEX` are conflicting each other ? 
I was planning on removing the index `timestamp_idx` as I thought it was the source of the problem but I would also like to optimise the future queries if possible.

**Comment by filimonov** [comment]
Please try grepping the logs for the part name: `20201109_3333225_3410146_61` 
Maybe file in part was half written / damaged for some external reason?

**Comment by BaptisteBdn** [comment]
> Please try grepping the logs for the part name: `20201109_3333225_3410146_61`

Arround 4k lines with the same exception : `2020.11.12 10:38:03.034229 [ 16520 ] {e0c601ef-bca1-4122-a80f-55793ec018ae} <Error> executeQuery: Code: 246, e.displayText() = DB::Exception: Received from xxxx:9000. DB::Exception: Bad size of marks file '/var/lib/clickhouse/store/0a0/0a0b87aa-c65c-4c7c-a3ce-cedd7d5e964a/20201109_3333225_3410146_61/skp_idx_timestamp_idx.mrk3': 48, must be: 72. Stack trace:`

> Maybe file in part was half written / damaged for some external reason?
It happened to multiple files and clickhouse is the only thing running on the servers.
Could it be because of the cluster configuration ? I inserted the data with the `Distributed` table which then spread randomly to the 4 nodes. Could it damage the files ?

**Comment by den-crane** [comment]
Is it reproducible if you query shard table directly ?

```
SELECT max(timestamp)
FROM shard.requests
WHERE (timestamp >= '2020-11-09 23:00:00') AND (timestamp <= '2020-11-09 23:59:59')
```

**Comment by BaptisteBdn** [comment]
> Is it reproducible if you query shard table directly ?
> 
> ```
> SELECT max(timestamp)
> FROM shard.requests
> WHERE (timestamp >= '2020-11-09 23:00:00') AND (timestamp <= '2020-11-09 23:59:59')
> ```

Same issue only when I query the shard on the node where the file `/var/lib/clickhouse/store/0a0/0a0b87aa-c65c-4c7c-a3ce-cedd7d5e964a/20201109_3333225_3410146_61/skp_idx_timestamp_idx.mrk3` is located.
I have 4 nodes and this file is available only on the first node. 

When I try this query on the others 3 nodes I don't have the issue.

**Comment by den-crane** [comment]
What is the TZ on the server?

**Comment by den-crane** [comment]
`select partition, name, part_type, marks, rows from system.parts where name = '20201109_3333225_3410146_61'`

**Comment by BaptisteBdn** [comment]
On the server we have `UTC+0100`.

The parts with the name `20201109_3333225_3410146_61` does not seems to exist : 
```
SELECT
    partition,
    name,
    part_type,
    marks,
    rows
FROM system.parts
WHERE name = '20201109_3333225_3410146_61'

Ok.

0 rows in set. Elapsed: 0.012 sec.
```

**Comment by den-crane** [comment]
I think it's a CH bug, not the disk corruption.

>Bad size of marks skp_idx_timestamp_idx.mrk3': 48, must be: 72.

>GRANULARITY 4
>index_granularity 8192

71337 rows/8192 = 9 granulas = 9 / 4 = 3 index skip granulas

48 == 2 index skip granulas , must be: 72 3 index skip granulas.

Seems during merge 20201109_3333225_3410146_61 CH formed the incorrect skip index mrk3 file.

**Comment by den-crane** [comment]
@BaptisteBdn Can you show `ls -l /var/lib/clickhouse/store/0a0/0a0b87aa-c65c-4c7c-a3ce-cedd7d5e964a/20201109_3333225_3410146_61`

**Comment by BaptisteBdn** [comment]
```
ls -l /var/lib/clickhouse/store/0a0/0a0b87aa-c65c-4c7c-a3ce-cedd7d5e964a/20201109_3333225_3410146_61

total 1582
-rw-r----- 1 clickhouse clickhouse     369 nov.  11 01:15 checksums.txt
-rw-r----- 1 clickhouse clickhouse     355 nov.  11 01:15 columns.txt
-rw-r----- 1 clickhouse clickhouse       5 nov.  11 01:15 count.txt
-rw-r----- 1 clickhouse clickhouse 1643022 nov.  11 01:15 data.bin
-rw-r----- 1 clickhouse clickhouse    2960 nov.  11 01:15 data.mrk3
-rw-r----- 1 clickhouse clickhouse      10 nov.  11 01:15 default_compression_codec.txt
-rw-r----- 1 clickhouse clickhouse       8 nov.  11 01:15 minmax_timestamp.idx
-rw-r----- 1 clickhouse clickhouse       4 nov.  11 01:15 partition.dat
-rw-r----- 1 clickhouse clickhouse     232 nov.  11 01:15 primary.idx
-rw-r----- 1 clickhouse clickhouse      51 nov.  11 01:15 skp_idx_timestamp_idx.idx
-rw-r----- 1 clickhouse clickhouse      48 nov.  11 01:15 skp_idx_timestamp_idx.mrk3
-rw-r----- 1 clickhouse clickhouse     163 nov.  11 01:15 ttl.txt
```

```
cat /var/lib/clickhouse/store/0a0/0a0b87aa-c65c-4c7c-a3ce-cedd7d5e964a/20201109_3333225_3410146_61/count.txt

71337
```

**Comment by den-crane** [comment]
cc @CurtizJ

**Comment by Amberon** [comment]
We experience a similar problem with minmax index
`    INDEX idx3 FieldNameInt TYPE minmax GRANULARITY 3`

it's also "48, must be: 72"

version 20.11.2.1

This only happens with the most recent parts, 
(we have a buffer table that flushes to disk every few seconds)

Sometimes it fixes itself; sometimes I have to run `MATERIALIZE INDEX idx3`

```
2020.11.24 17:18:36.037448 [ 15006 ] {246599b6-5f6b-4360-8cf9-a4d7f9d55f79} <Error> DynamicQueryHandler: Code: 246, e.displayText() = DB::Exception: Bad size of marks file '/var/lib/clickhouse/data/db/table/20201124_5040_7270_1951_7265/skp_idx_idx3.mrk3': 48, must be: 72, Stack trace (when copying this message, always include the lines below):

0. DB::MergeTreeMarksLoader::loadMarksImpl() @ 0xe1a010c in /usr/bin/clickhouse
1. DB::MergeTreeMarksLoader::loadMarks() @ 0xe19f3b9 in /usr/bin/clickhouse
2. DB::MergeTreeReaderStream::MergeTreeReaderStream(std::__1::shared_ptr<DB::IDisk>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange> > const&, DB::MergeTreeReaderSettings const&, DB::MarkCache*, DB::UncompressedCache*, unsigned long, DB::MergeTreeIndexGranularityInfo const*, std::__1::function<void (DB::ReadBufferFromFileBase::ProfileInfo)> const&, int) @ 0xe1a677c in /usr/bin/clickhouse
3. DB::MergeTreeIndexReader::MergeTreeIndexReader(std::__1::shared_ptr<DB::IMergeTreeIndex const>, std::__1::shared_ptr<DB::IMergeTreeDataPart const>, unsigned long, std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange> > const&, DB::MergeTreeReaderSettings) @ 0xe15a795 in /usr/bin/clickhouse
4. DB::MergeTreeDataSelectExecutor::filterMarksUsingIndex(std::__1::shared_ptr<DB::IMergeTreeIndex const>, std::__1::shared_ptr<DB::IMergeTreeIndexCondition>, std::__1::shared_ptr<DB::IMergeTreeDataPart const>, std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange> > const&, DB::Settings const&, DB::MergeTreeReaderSettings const&, Poco::Logger*) @ 0xe147a0b in /usr/bin/clickhouse
5. ? @ 0xe13a8fe in /usr/bin/clickhouse
6. ? @ 0xe14c767 in /usr/bin/clickhouse
7. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0x7b6147d in /usr/bin/clickhouse
8. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()&&...)::'lambda'()::operator()() @ 0x7b639df in /usr/bin/clickhouse
9. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x7b5e93d in /usr/bin/clickhouse
10. ? @ 0x7b62463 in /usr/bin/clickhouse
11. start_thread @ 0x82de in /usr/lib64/libpthread-2.28.so
12. clone @ 0xfbe83 in /usr/lib64/libc-2.28.so
```

**Comment by Amberon** [comment]
> I think it's a CH bug, not the disk corruption.
> 
> > Bad size of marks skp_idx_timestamp_idx.mrk3': 48, must be: 72.
> 
> > GRANULARITY 4
> > index_granularity 8192
> 
> 71337 rows/8192 = 9 granulas = 9 / 4 = 3 index skip granulas
> 
> 48 bytes === 2 index skip granulas , must be: 72 bytes === 3 index skip granulas.
> 
> Seems during merge 20201109_3333225_3410146_61 CH formed the incorrect skip index mrk3 file.

It seems to me that changing granularity to more traditional even number 2 or 4 may fix the ussue?

**Comment by BaptisteBdn** [comment]
Thanks @Amberon, it seems to work aswell with `GRANULARITY = 1` on my side.

However it would be better if we could choose another value, hope you guys can find a fix.

**Comment by vvhungy** [comment]
Any update on this issue?

We got similar error for some of our partitions. Before the data is in .mrk2 (format) files, after an FULL optimmize (OPTIMIZE ... PARTITION... FINAL), data files in these partitions became .mrk3 format and then those partitions couldn't be read.

**Comment by den-crane** [comment]
@vvhungy your issue is solved https://github.com/ClickHouse/ClickHouse/pull/18381

**Comment by vvhungy** [comment]
@den-crane oh, I've never known as there're no update on this issue thread. We just updated our CH server to 20.12.5.14 and it worked. Tks.

**Comment by mohaa8844** [comment]
Kindly review 
https://kb.altinity.com/altinity-kb-setup-and-maintenance/suspiciously-many-broken-parts/

**Comment by jaddu123** [comment]
Getting this error, what can be the possible reason for this:

SQL Error [33] [07000]: Code: 33. DB::Exception: Too many marks in file payload%2Ecompany%2Edomain%2Egeo_domain%2Ecreated_at.cmrk2, marks expected 5 (bytes size 120): (while reading column payload): (while reading from part /datadir2/store/2ce/2ce0da9e-dee7-4ec6-9f93-f1060e9a680f/all_367294_367294_6231/ in table test_db.log_events (2ce0da9e-dee7-4ec6-9f93-f1060e9a680f) located on disk default2 of type local, from mark 0 with max_rows_to_read = 6444): While executing MergeTreeThread. (CANNOT_READ_ALL_DATA) (version 23.7.4.5 (official build))
