### ISSUE TITLE
Duplicate values of column values used in GROUP BY

### ISSUE THREAD

**Issue by yard** [ClickHouse/ClickHouse#16922]
**Describe the bug**
We are running Clickhouse in distributed setup: 3 shards, no replicas, shards injest data from Kafka; 1 additional server sits in front of those having `Distributed` tables pointing to these shards' tables.

Running a query like SELECT x, COUNT(*) FROM table GROUP BY x _sometimes_ returns duplicate values (roughly 1 out of 5 tries). Running the query on individual shards does not exhibit this issue.

**How to reproduce**
* 20.6.7.4 x86 on "proxy" server, 20.6.7.4 ARM builds on shards (did not try with x86 shards)
* Proxy server: `CREATE TABLE test (x LowCardinality(String)) ENGINE = Distributed('main', 'db', 'test')`
   Shards: `CREATE TABLE test (x LowCardinality(String)) ENGINE = MergeTree()`
* SQL query is `SELECT x, COUNT(*) FROM table GROUP BY x`

**Expected behavior**
The result of aforementioned query should contain a single row per unique `x` value.

**Error message and/or stacktrace**
There are no error messages logged, *but* we did manage to observe a difference in debug output in runs when the problem appears versus runs when the results are correct. 

So, when aggregation completes properly (no duplicates on `x` column) the logs contain the following sequences of messages:
```
2020.11.12 08:58:07.264544 [ 155 ] {25b4c5fb-03a6-49f8-9273-ca78ed7cec9a} <Trace> MergingAggregatedTransform: Reading blocks of partially aggregated data.
2020.11.12 08:58:07.283757 [ 144 ] {25b4c5fb-03a6-49f8-9273-ca78ed7cec9a} <Trace> MergingAggregatedTransform: Read 3 blocks of partially aggregated data, total 30 rows.
2020.11.12 08:58:07.283786 [ 144 ] {25b4c5fb-03a6-49f8-9273-ca78ed7cec9a} <Trace> Aggregator: Merging partially aggregated single-level data.
2020.11.12 08:58:07.283811 [ 144 ] {25b4c5fb-03a6-49f8-9273-ca78ed7cec9a} <Trace> Aggregator: Merged partially aggregated single-level data.
2020.11.12 08:58:07.283818 [ 144 ] {25b4c5fb-03a6-49f8-9273-ca78ed7cec9a} <Trace> Aggregator: Converting aggregated data to blocks
2020.11.12 08:58:07.283848 [ 144 ] {25b4c5fb-03a6-49f8-9273-ca78ed7cec9a} <Trace> Aggregator: Converted aggregated data to blocks. 10 rows, 271.00 B in 1.8122e-05 sec. (551815.4729058603 rows/sec., 14.26 MiB/sec.)
```

When the issue appears, the logs contain a _slightly_ different output:
```
2020.11.12 08:58:09.484942 [ 50 ]  {ac8d2b90-b710-466d-bb04-6cdc6a829da8} <Trace> MergingAggregatedTransform: Reading blocks of partially aggregated data.
2020.11.12 08:58:09.517105 [ 174 ] {ac8d2b90-b710-466d-bb04-6cdc6a829da8} <Trace> MergingAggregatedTransform: Read 21 blocks of partially aggregated data, total 30 rows.
2020.11.12 08:58:09.518164 [ 174 ] {ac8d2b90-b710-466d-bb04-6cdc6a829da8} <Trace> Aggregator: Merging partially aggregated two-level data.
2020.11.12 08:58:09.518250 [ 174 ] {ac8d2b90-b710-466d-bb04-6cdc6a829da8} <Trace> Aggregator: Merged partially aggregated two-level data.
2020.11.12 08:58:09.518257 [ 174 ] {ac8d2b90-b710-466d-bb04-6cdc6a829da8} <Trace> Aggregator: Merging partially aggregated single-level data.
2020.11.12 08:58:09.518279 [ 174 ] {ac8d2b90-b710-466d-bb04-6cdc6a829da8} <Trace> Aggregator: Merged partially aggregated single-level data.
2020.11.12 08:58:09.518288 [ 174 ] {ac8d2b90-b710-466d-bb04-6cdc6a829da8} <Trace> Aggregator: Converting aggregated data to blocks
2020.11.12 08:58:09.518409 [ 174 ] {ac8d2b90-b710-466d-bb04-6cdc6a829da8} <Trace> Aggregator: Converted aggregated data to blocks. 17 rows, 606.00 B in 0.000108663 sec. (156446.996677802 rows/sec., 5.32 MiB/sec.)
```

This output corresponds to slightly more complex queries (involving ```sumIf``` function in SELECT clause), however, a similar difference is observe in simplier cases.

There seems to be no particular reason for intermediate block count changing from 3 to 21 and back - it's just subsequent runs of exactly the same SQL. It seems, however, that as soon as shards return multiple blocks (not fully aggregated or something?), the proxy server fails to complete the aggregation properly.

**Additional context**
Problem happens more often with ```SummingMergeTree``` tables, but does happen with plain ```MergeTree``` as well.
Appending `FINAL` modifier makes the issue go away, however, this does not seem to be right since performance drops significantly.

**Comment by den-crane** [comment]
try to reproduce with test data and `SETTINGS group_by_two_level_threshold_bytes = 1, group_by_two_level_threshold = 1`

https://github.com/ClickHouse/ClickHouse/issues/13331
https://github.com/ClickHouse/ClickHouse/issues/9134

**Comment by yard** [comment]
Hi Denis! You are saving the day, as always 👍 

Setting _event just_ `group_by_two_level_threshold_bytes` seems to be making the problem go away. 

Extra observation: setting `group_by_two_level_threshold_bytes` to 1 makes the resultset be composed of multiple blocks (i.e. `clickhouse-client` prints the result with each row having it's own headers), while setting it to 0 _also resolves_ the issue, but the result set is a single block.

Is it safe to set to 0?

**Comment by den-crane** [comment]
@yard you are describing very weird things.
group_by_two_level_threshold_bytes=1 --- forces two-level-aggregation
group_by_two_level_threshold_bytes=0 --- disables two-level-aggregation 

Please show examples with a sample data.

**Comment by den-crane** [comment]
try to disable distributed_aggregation_memory_efficient as well.

**Comment by yard** [comment]
I think you confused `group_by_two_level_threshold_bytes` and `group_by_two_level_threshold`. The initial value of `group_by_two_level_threshold_bytes` I have in `system.settings` is 100000000.

`distributed_aggregation_memory_efficient` is set to 0 already in my setup.

Unfortunately, I am not able to reliably reproduce the issue with the sample data (it appears to occur waaaay more rarely). However, on "real" data the behaviour is as follows (data mangled since it's bit sensitive, hope you don't mind). I do realize the query is more complicated, but the bug seems to be triggered by some specific amount of data coming from shards, and using functions like `sumIf` help to get over the threshold quicker. Anyway, please see the below.

## Broken case
```
SET group_by_two_level_threshold_bytes = 100000000;
SELECT name, sumIf(`eventsMap.count`, `eventsMap.eventName` = 'test') as value FROM pi.events_charts_overview ARRAY JOIN eventsMap WHERE eventTime >= '2020-10-27 00:00:00' AND eventTime < '2020-11-10 23:59:00' GROUP BY name;
```

Running the above a few times produces either a valid result set:
```
┌─name───────────┬─value───────┐
│ name1          │      806176 │
│ name2          │          30 │
│ name3          │    24523337 │
│ name4          │         474 │
│ name5          │     2410091 │
│ name6          │    11330999 │
│ name7          │    62641723 │
│ name8          │       32531 │
│ name9          │    12617266 │
│ name10         │   145746915 │
└────────────────┴─────────────┘
```
or an invalid one:
```
┌─name──────┬─value───────┐
│ name4     │         168 │
└───────────┴─────────────┘
┌─name──────┬─value───────┐
│ name8     │       21729 │
└───────────┴─────────────┘
┌─name──────┬─value───────┐
│ name10    │    48590989 │
└───────────┴─────────────┘
┌─name──────┬─value───────┐
│ name9     │     4205585 │
└───────────┴─────────────┘
┌─name──────┬─value───────┐
│ name6     │     7556085 │
└───────────┴─────────────┘
┌─name──────┬─value───────┐
│ name6     │     3774914 │
└───────────┴─────────────┘
┌─name──────┬─value───────┐
│ name1     │      806176 │
└───────────┴─────────────┘
┌─name──────┬─value───────┐
│ name5     │     1606670 │
└───────────┴─────────────┘
┌─name──────┬─value───────┐
│ name5     │      803421 │
└───────────┴─────────────┘
┌─name──────┬─value───────┐
│ name7     │    20888324 │
└───────────┴─────────────┘
┌─name──────┬─value───────┐
│ name10    │    97155926 │
└───────────┴─────────────┘
┌─name──────┬─value───────┐
│ name2     │          30 │
└───────────┴─────────────┘
┌─name──────┬─value───────┐
│ name8     │       10802 │
└───────────┴─────────────┘
┌─name──────┬─value───────┐
│ name3     │    24523337 │
└───────────┴─────────────┘
┌─name──────┬─value───────┐
│ name9     │     8411681 │
└───────────┴─────────────┘
┌─name──────┬─value───────┐
│ name7     │    41753399 │
└───────────┴─────────────┘
┌─name──────┬─value───────┐
│ name4     │         306 │
└───────────┴─────────────┘
```

NOTE: you can notice that the data is indeed not aggregated finally, i.e. `name6`'s value in first result set is exactly the sum of two `name6` entries from the second one.

## Correct case
```
SET group_by_two_level_threshold_bytes = 0; // could be 1 as well
SELECT name, sumIf(`eventsMap.count`, `eventsMap.eventName` = 'test') as value FROM pi.events_charts_overview ARRAY JOIN eventsMap WHERE eventTime >= '2020-10-27 00:00:00' AND eventTime < '2020-11-10 23:59:00' GROUP BY name;
```

Running the above seems to be always producing a valid result set:
```
┌─name───────────┬─value───────┐
│ name1          │      806176 │
│ name2          │          30 │
│ name3          │    24523337 │
│ name4          │         474 │
│ name5          │     2410091 │
│ name6          │    11330999 │
│ name7          │    62641723 │
│ name8          │       32531 │
│ name9          │    12617266 │
│ name10         │   145746915 │
└────────────────┴─────────────┘
```

**Comment by yard** [comment]
@den-crane I am trying to prepare an isolated docker-compose stack + seed data to reliably reproduce the issue. Do you know if there is any way to force shards to return data from queries like `SELECT name, count(*) FROM table GROUP BY name` in a form of multiple blocks (since judging by the logs this seems to be the trigger for the issue)?

**Comment by den-crane** [comment]
Usually one server is enough. 

Try this

```sql

create table d(A Int64, B Int64) Engine=MergeTree order by A;
insert into d select toString(cityHash64(number)),number from numbers(1000000);

distributed_aggregation_memory_efficient = 1, group_by_two_level_threshold = 1, group_by_two_level_threshold_bytes=1;

select A, count() cnt from (
select A, count() from remote('127.0.0.1,127.0.0.2',currentDatabase(), d) group by A)
group by A
having cnt >1

```

**Comment by yard** [comment]
Hey, sorry for the late reply!

The above works properly (empty set) whether I change suggested settings or not. I also tried changing the column to `String` (since I noticed the aggregation is using `key64` method with your sample), but the issue does not reproduce. 

I have a suspicion the bug might be related to ARM instances being present in my case, trying to reproduce in this setup now.

**Comment by alexey-milovidov** [comment]
> 20.6.7.4 x86 on "proxy" server, 20.6.7.4 ARM builds on shards (did not try with x86 shards)

This is the reason.
Different hash function is used on different platforms to split data across buckets.
It means that heterogenous clusters (mixed ARM/x86) are not supported.

But I expect that the hash function should be the same nevertheless:
```
inline DB::UInt64 intHashCRC32(DB::UInt64 x)
{
#ifdef __SSE4_2__
    return _mm_crc32_u64(-1ULL, x);
#elif defined(__aarch64__) && defined(__ARM_FEATURE_CRC32)
    return __crc32cd(-1U, x);
#else
    /// On other platforms we do not have CRC32. NOTE This can be confusing.
    return intHash64(x);
#endif
}
```

Maybe you did not enable crc32 instructions for ARM build?
Does the issue reproduce if you use the official ARM build? It can be found here:
https://clickhouse.tech/docs/en/getting-started/install/#from-binaries-non-linux
