### ISSUE TITLE
server start problem

### ISSUE THREAD

**Issue by tianyanchao-tyc** [ClickHouse/ClickHouse#16958]
Systemctl start Clickhouse - Server displays UNKNOWN. Clickhouse cannot be connected. It can be connected after starting with Clickhouse - Server
![image](https://user-images.githubusercontent.com/57435014/99016561-61ba8a00-2592-11eb-971b-7d1b1b4081ea.png)

**Comment by filimonov** [comment]
```
tail -n 500 /var/lib/clickhouse-server/clickhouse-server.err.log
tail -n 500 /var/lib/clickhouse-server/clickhouse-server.log
tail -n 500 /var/lib/clickhouse-server/stderr.log
```
