### ISSUE TITLE
How to set the kafka_format for json message that contains array?

### ISSUE THREAD

**Issue by liangyu-1** [ClickHouse/ClickHouse#16969]
I have a json message that has the schema:
{
"field1":[
{
"field2":"value2",
"field3":"value3"
}
],
"field4":"value4"
}
this is the message I get from the kafka, how should I set the kafka_schema so that I can read the values of each field?
I tried the create the table that has the type array(nested()), but it didn't work.

**Comment by filimonov** [comment]
1) Use clickhouse>20.5
2) create table kafka ( json_string String )  Engine = Kafka settings  ... kafka_format='JSONAsString';
3) `CREATE MATERIALIZED VIEW kafka_mv  TO ... AS SELECT  JSONExtract ... `
4) use combination of JSONExtractRaw JSONExtractArrayRaw and higher-order functions
