### ISSUE TITLE
Executable external dictionary doesn't get any STDIN

### ISSUE THREAD

**Issue by millin** [ClickHouse/ClickHouse#1697]
According to docs when layout of executable dict configured as complex_key_cache list of needed keys will be written in STDIN of program, but it doesn't.

I asked about my issue in [Telegram](https://t.me/clickhouse_ru) and @proller recommended me to try `<command>tee id.log</command>` to log STDIN. As result  I got empty log.

Checked on Clickhouse v1.1.54318, v1.1.54327.
OS: Centos 7 (built using Altinity's script)

**Comment by proller** [comment]
Can you show your dictionary config and minimal queries with this dictionary ?

**Comment by millin** [comment]
Dictionary config example:

    <dictionaries>
    <dictionary>
        <name>geolite2_city</name>
        <source>
           <executable>
                <command>tee /usr/share/GeoIP/test.log | /usr/share/GeoIP/get_country.py</command>
                <format>JSONEachRow</format>
            </executable>
        </source>
        <layout>
            <complex_key_cache>
                <size_in_cells>10000</size_in_cells>
            </complex_key_cache>
        </layout>
        <structure>
            <key>
                <attribute>
                    <name>ip</name>
                    <type>String</type>
                </attribute>
            </key>
            <attribute>
                <name>geoname_id</name>
                <type>UInt32</type>
                <null_value>0</null_value>
            </attribute>
            <attribute>
                <name>iso_code</name>
                <type>String</type>
                <null_value></null_value>
            </attribute>
        </structure>
        <lifetime>
            <min>3500</min>
            <max>3500</max>
        </lifetime>
    </dictionary>
    </dictionaries>

Simple query:
    SELECT dictGetString('geolite2_city', 'iso_code', tuple('8.8.8.8'));

I tried to change source format (TabSeparated, CSV etc.) and executable type (bash/python/c) - no difference.

**Comment by gerasim13** [comment]
столкнулся с этой проблемой. такое впечатление что в stdin кликхаус ничего не пишет

**Comment by proller** [comment]
проверил ровно этот пример - и все хорошо , в логе появилось {"ip":"8.8.8.8"}
Одно замечание - у пользователя под которым работает clickhouse должен быть доступ на запись в /usr/share/GeoIP/test.log

**Comment by millin** [comment]
I checked this issue on latest stable v1.1.54342 - all works fine.
Probably there are some troubles in previous versions (v1.1.54318, v1.1.54327) or something strange happened during building to rpm.
Closed.

**Comment by millin** [comment]
I just faced with this or related issue again.

During the test for more different valid ip-addresses, using query 
`SELECT dictGetString('geolite2_city', 'iso_code', tuple('8.8.8.8'));`
I found that sometimes this query hangs and in this case tee log is empty.

I tried to kill hang query from CH - unsuccessfully. Then I found proc and manually send 
`{"ip":"8.8.8.8"}` to it's stdin > hang query completed.

**Comment by millin** [comment]
I found that CH send data to process's STDIN only when process already send STDOUT.
So, I temporary solved this by adding **`echo ''`** to the top of my script.

Is this an expected behavior?

**Comment by alexey-milovidov** [comment]
It's not expected.

**Comment by alexey-milovidov** [comment]
This issue is still relevant.

**Comment by millin** [comment]
I don't know, I have not used this for a long time

**Comment by alexey-milovidov** [comment]
@nikitamikhaylov Maybe you can look at this?

**Comment by alexey-milovidov** [comment]
@millin `This issue is still relevant.` is not a question :)
