### ISSUE TITLE
DB::Exception: Cannot read all data. Bytes read: 10433. Bytes expected: 87071.: while receiving packet from XXX: While executing SourceFromInputStream

### ISSUE THREAD

**Issue by K4liber** [ClickHouse/ClickHouse#16984]
Hello folks,
I got this error while executing query on Distributed table (the query is heavy): 

> DB::Exception: Cannot read all data. Bytes read: 10433. Bytes expected: 87071.: while receiving packet from <ch node host>: While executing SourceFromInputStream

When i limit the query a little more (from 90 to 60 days) by prewhere on date (where my distributed tables are ENGINE = MergeTree() PARTITION BY toYYYYMM(date)) the error do not appear.
I cannot really guess from the error message what the exact problem is. I only suspect the heaviness of the query to be the reason.

**Comment by den-crane** [comment]
What CH version do you use?

**Comment by K4liber** [comment]
> What CH version do you use?

ClickHouse server version 20.3.8 revision 54433

**Comment by K4liber** [comment]
I moved my conditions from PREWHERE to WHERE and use SAMPLE/OFFSET, and aggregate the results after all, but this is only a workaround not a solution.

**Comment by den-crane** [comment]
Check with the latest version of 20.3 LTS  -- 20.3.21.2

Do you have reproducible example?
