### ISSUE TITLE
DirectoryMonitor processing tmp directory exception

### ISSUE THREAD

**Issue by haiertashu** [ClickHouse/ClickHouse#16987]
hi, i removed one replica from shard in metrika.xml because the server offline,  some server who receive insert requests have a exception while the DirectoryMonitor started processing tmp directory datas like this:

<pre>
2020.11.13 22:11:00.348257 [ 12414 ] {} <Trace> bbb_w.Distributed.DirectoryMonitor: Started processing `/home/disk2/clickhouse/data/aaa/bbb/default:OEghhYSJ@xj01%2Dwww%2D01%2Exj01:9001/844638.bin`
2020.11.13 22:11:00.348413 [ 12414 ] {} <Trace> Connection (xj01-www-01.xj01:9001): Connecting. Database: (not specified). User: default
2020.11.13 22:11:00.370979 [ 12414 ] {} <Error> app_ps_metrics_w.Distributed.DirectoryMonitor: Code: 210, e.displayText() = DB::NetException: Connection refused (xj01-www-01.xj01:9001), Stack trace
(when copying this message, always include the lines below):

0. 0x10335e20 Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) ?
1. 0x8ea65cd DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) ?
2. 0xda0942c ? ?
3. 0xda04953 DB::Connection::forceConnected(DB::ConnectionTimeouts const&) ?
4. 0x8ffc512 DB::ConnectionPool::get(DB::ConnectionTimeouts const&, DB::Settings const*, bool) ?
5. 0xd77bc87 DB::StorageDistributedDirectoryMonitor::processFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) ?
6. 0xd77e605 DB::StorageDistributedDirectoryMonitor::processFiles() ?
7. 0xd77e958 DB::StorageDistributedDirectoryMonitor::run() ?
8. 0xd7816f5 ThreadFromGlobalPool::ThreadFromGlobalPool<void (DB::StorageDistributedDirectoryMonitor::*)(), DB::StorageDistributedDirectoryMonitor*>(void (DB::StorageDistributedDirectoryMonitor::*&&)(), D
B::StorageDistributedDirectoryMonitor*&&)::'lambda'()::operator()() const ?
9. 0x8ec9f9b ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) ?
10. 0x8ec83a3 ? ?
11. 0x318b207851 start_thread ?
12. 0x318aee767d __clone ?
 (version 20.1.9.54 (official build))
</pre>

i found there has a similar issue #7538
but when i delete the corresponds directory to the shard `/home/disk3/clickhouse/data/aaa/bbb/default:OEghhYSJ@xj01%2Dwww%2D01%2Exj01:9001/`
there has another exception like this:
<pre>
2020.11.13 21:31:44.191738 [ 15945 ] {} <Error> bbb_w.Distributed.DirectoryMonitor: Poco::Exception. Code: 1000, e.code() = 2, e.displayText() = File not found: /home/disk2/clickhouse/data/a
aa/bbb/default:OEghhYSJ@xj01%2Dwww%2D01%2Exj01:9001/0. 0x10340060 Poco::FileNotFoundException::FileNotFoundException(std::__1::basic_string<char, std::__1::char_traits<char>, std::__
1::allocator<char> > const&, int) ?
1. 0x1034b6cc Poco::FileImpl::handleLastErrorImpl(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) ?
2. 0x1034bd6a ? ?
3. 0x1032bb32 Poco::DirectoryIteratorImpl::DirectoryIteratorImpl(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) ?
4. 0x1032bf8c Poco::DirectoryIterator::DirectoryIterator(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) ?
5. 0xd77e166 DB::StorageDistributedDirectoryMonitor::processFiles() ?
6. 0xd77e958 DB::StorageDistributedDirectoryMonitor::run() ?
7. 0xd7816f5 ThreadFromGlobalPool::ThreadFromGlobalPool<void (DB::StorageDistributedDirectoryMonitor::*)(), DB::StorageDistributedDirectoryMonitor*>(void (DB::StorageDistributedDirectoryMonitor::*&&)(), D
B::StorageDistributedDirectoryMonitor*&&)::'lambda'()::operator()() const ?
8. 0x8ec9f9b ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) ?
9. 0x8ec83a3 ? ?
10. 0x318b207851 start_thread ?
11. 0x318aee767d __clone ?
 (version 20.1.9.54 (official build))
</pre>
while the log change to Warning after i restart the service, here is the log:
<pre>
2020.11.13 22:40:00.376433 [ 1420 ] {decb658f-2d6c-452b-af56-49ceace209c3} <Warning> ConnectionPoolWithFailover: Connection failed at try �<84><96>1, reason: Code: 32, e.displayText() = DB::Exception: Attempt to read after eof (version 20.1.9.54 (official build))
</pre>
so does this warning log shows it's ok for my case?
it should note that i haven't use zookeeper in my cluster , in this case, how can i remove/change any replica node freely？
thank you for your attention :)

**Comment by filimonov** [comment]
@azat it's very similar to the issue we discussed recently.

**Comment by azat** [comment]
>2020.11.13 22:11:00.370979 [ 12414 ] {}  app_ps_metrics_w.Distributed.DirectoryMonitor: Code: 210, e.displayText() = DB::NetException: Connection refused (xj01-www-01.xj01:9001), Stack trace

This is expected

>but when i delete the corresponds directory to the shard /home/disk3/clickhouse/data/aaa/bbb/default:OEghhYSJ@xj01%2Dwww%2D01%2Exj01:9001/

This is exactly what you need to do

>there has another exception like this:

Yes, you need to restart the server

>2020.11.13 22:40:00.376433 [ 1420 ] {decb658f-2d6c-452b-af56-49ceace209c3}  ConnectionPoolWithFailover: Connection failed at try �<84><96>1, reason: Code: 32, e.displayText() = DB::Exception: Attempt to read after eof (version 20.1.9.54 (official build))

@haiertashu What was the stacktrace? (not sure that this is related)

>it should note that i haven't use zookeeper in my cluster , in this case, how can i remove/change any replica node freely？

zk is not required here (for distirbuted async sent)

Refs: https://github.com/ClickHouse/ClickHouse/issues/11133#issuecomment-719403763

**Comment by haiertashu** [comment]
thanks a lot ^^
the last exception is just a Warning log without stacktrace, and I also found in the normal nodes, maybe really not related.
by the way，Is there a more elegant way when I modify the replica config next time?

**Comment by azat** [comment]
>by the way，Is there a more elegant way when I modify the replica config next time?

If you need to change the host name you can use `use_compact_format_in_distributed_parts_names=1`, this setting changes the format of the directories that will be used for async distributed insert, and will use `shardX_replicaX` instead of `user[:password]@host:port#default_database`, and it will allow change the hostname smoothly.

Also note that with `use_compact_format_in_distributed_parts_names=0` (default, until 20.12), you cannot even change the user/password, since those settings will not be applied and you will constantly get an authentication error.

But if you need to "remove" host from the middle, that you should consider the following things:
- things like `optimize_skip_unused_shards` will be broken
- you still need to manually delete the directory and restart the server to avoid ENOENT (no such file or directory) exception for this case.

P.S. use_compact_format_in_distributed_parts_names has been enabled by default in #16728 (20.12+)
