### ISSUE TITLE
Attach clickhouse-client to an existing session?

### ISSUE THREAD

**Issue by bgranvea** [ClickHouse/ClickHouse#16990]
I have a program which uses temporary tables with a session id that I know. Now, I would like to troubleshoot my program and see what was inserted in these temporary tables.

Is there a way to "attach" clickhouse-client to an existing session so that it sees the temporary tables?

Thanks.

**Comment by alexey-milovidov** [comment]
There is no way, named sessions are managed only by HTTP interface.

It should be easy to extend clickhouse-client to attach to the named sessions (add a command line argument, send it to the server through ClientInfo, use it in TCPHandler to attach to the session similar to how it's implemented in HTTPHandler).

**Comment by bgranvea** [comment]
thanks for the quick response. I'm surprised nobody missed that feature. I do a PR if I find some time.
