### ISSUE TITLE
When after change path for data and log, clickhouse server start failed.

### ISSUE THREAD

**Issue by qinglok** [ClickHouse/ClickHouse#17045]
ClickHouse version: 20.9.5.5-2
OS: Red Hat Enterprise Linux 7 64

Steps：
1.modify config.xml
    `<log>/opt/clickhouse/log/clickhouse-server/clickhouse-server.log</log>`
    `<errorlog>/opt/clickhouse/log/clickhouse-server/clickhouse-server.err.log</errorlog>`
    `<path>/opt/clickhouse/</path>`
    `<tmp_path>/opt/clickhouse/tmp/</tmp_path>`
    `<user_files_path>/opt/clickhouse/user_files/</user_files_path>`
    `<access_control_path>/opt/clickhouse/access/</access_control_path>`
    `<format_schema_path>/opt/clickhouse/format_schemas/</format_schema_path>`
2.mkdir /opt/clickhouse
3.chown -R clickhouse:clickhouse /opt/clickhouse
4.systemctl start clickhouse-server

Then it failed to start, and no log files were generated.
The same operation above is completely OK on CentOS.

**Comment by l1t1** [comment]
try to mv all of the content under old path to the new path

**Comment by l1t1** [comment]
I didn't modify the config and use ln -s

**Comment by den-crane** [comment]
check stdout for

```
sudo -u clickhouse clickhouse-server -pid-file=/var/run/clickhouse-server/clickhouse-server.pid --config-file=/etc/clickhouse-server/config.xml

```
it could be SELINUX.

**Comment by qinglok** [comment]
This command cannot be run.
`sudo -u clickhouse clickhouse-server -pid-file=/var/run/clickhouse-server/clickhouse-server.pid --config-file=/etc/clickhouse-server/config.xml`
`Unknown option specified: pid-file=/var/run/clickhouse-server/clickhouse-server.pid`

**Comment by den-crane** [comment]
I've missed one dash -

```
sudo -u clickhouse clickhouse-server --pid-file=/var/run/clickhouse-server/clickhouse-server.pid --config-file=/etc/clickhouse-server/config.xml

```

**Comment by qinglok** [comment]
[root@localhost ~]# sudo -u clickhouse clickhouse-server --pid-file=/var/run/clickhouse-se                  rver/clickhouse-server.pid --config-file=/etc/clickhouse-server/config.xml
Processing configuration file '/etc/clickhouse-server/config.xml'.
Including configuration file '/etc/clickhouse-server/metrika.xml'.
Include not found: clickhouse_compression
Code: 76, e.displayText() = DB::ErrnoException: Cannot open file /var/run/clickhouse-serve                  r/clickhouse-server.pid, errno: 2, strerror: No such file or directory, Stack trace (when                   copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, st                  d::__1::allocator<char> > const&, int) @ 0x18e2eab0 in /usr/bin/clickhouse
1. DB::ErrnoException::ErrnoException(std::__1::basic_string<char, std::__1::char_traits<c                  har>, std::__1::allocator<char> > const&, int, int, std::__1::optional<std::__1::basic_str                  ing<char, std::__1::char_traits<char>, std::__1::allocator<char> > > const&) @ 0xe73d4cb i                  n /usr/bin/clickhouse
2. DB::throwFromErrnoWithPath(std::__1::basic_string<char, std::__1::char_traits<char>, st                  d::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>                  , std::__1::allocator<char> > const&, int, int) @ 0xe73b8b2 in /usr/bin/clickhouse
3. DB::StatusFile::StatusFile(std::__1::basic_string<char, std::__1::char_traits<char>, st                  d::__1::allocator<char> >, std::__1::function<void (DB::WriteBuffer&)>) @ 0xe7f6b74 in /us                  r/bin/clickhouse
4. BaseDaemon::initialize(Poco::Util::Application&) @ 0x153e4301 in /usr/bin/clickhouse
5. DB::Server::initialize(Poco::Util::Application&) @ 0xe79a488 in /usr/bin/clickhouse
6. Poco::Util::Application::run() @ 0x18d5db39 in /usr/bin/clickhouse
7. DB::Server::run() @ 0xe799bd9 in /usr/bin/clickhouse
8. mainEntryClickHouseServer(int, char**) @ 0xe790c13 in /usr/bin/clickhouse
9. main @ 0xe723891 in /usr/bin/clickhouse
10. __libc_start_main @ 0x21af5 in /usr/lib64/libc-2.17.so
11. _start @ 0xe72302e in /usr/bin/clickhouse
 (version 20.9.5.5 (official build))

**Comment by lhcg** [comment]
chown -R clickhouse:clickhouse /var/run/clickhouse-server
...

**Comment by qinglok** [comment]
chown: cannot access ‘/var/run/clickhouse-server’: No such file or directory
@lhcg

**Comment by alexey-milovidov** [comment]
`Cannot open file /var/run/clickhouse-serve r/clickhouse-server.pid`

For some reason you have whitespace in directory name: `clickhouse-serve r`
It is also possible that you have copied the message incorrectly.

Check the path and access rights.
