### ISSUE TITLE
20.11 start say version error

### ISSUE THREAD

**Issue by vegastar002** [ClickHouse/ClickHouse#17049]
I removed the clickhouse 20.8, then download new version 20.11 and installed.
clickhouse-client-20.11.3.3-2.noarch.rpm
clickhouse-common-static-20.11.3.3-2.x86_64.rpm
clickhouse-server-20.11.3.3-2.noarch.rpm

start command:
systemctl start clickhouse-server
clickhouse-client -m

then give info:
ClickHouse client version 20.11.3.3 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 20.8.1 revision 54438.

ClickHouse server version is older than ClickHouse client. It may indicate that the server is out of date and can be upgraded.

why say clickhouse server is 20.8?
explicit I already remove 20.8.

**Comment by hexiaoting** [comment]
Have you stopped the old clickhouse-server?
and try to use check : the clickhouse server installed by clickhouse-server-20.11.3.3-2.noarch.rpm that really started with port 9000.

**Comment by l1t1** [comment]
rpm -e clickhouse-server
systemctl daemon-reload
systemctl stop  clickhouse-server
rpm -ivh clickhouse-server-20.11.3.3-2.noarch.rpm
systemctl start  clickhouse-server
