### ISSUE TITLE
clickhouse-test executing stateless test case facing the Code: 32. DB::Exception: Attempt to read after eof sometimes

### ISSUE THREAD

**Issue by mateng0915** [ClickHouse/ClickHouse#17050]
## Describe Bug
When i execute the test 01281_join_with_prewhere_fix, Encounter this problem occasionally.
![image](https://user-images.githubusercontent.com/26053753/99210748-9718df00-2801-11eb-9e18-77604a94df52.png)

I am really confused about this problems. 
My ClickHouse Server version is 20.4.4.18

Thanks

**Comment by hexiaoting** [comment]
Does the server crash?

**Comment by mateng0915** [comment]
> Does the server crash?

No.  when facing this problem the server still running successfully. And maybe i executing this test case then i can pass, after receive the fail error.

![image](https://user-images.githubusercontent.com/26053753/99211049-5a011c80-2802-11eb-85f8-07fb0e9d6956.png)

**Comment by hexiaoting** [comment]
Can the error be reproduced using Clickhouse client interactive mode? If we can the detail sql queries in 01281_join_with_prewhere_fix.sql multiply times?

**Comment by den-crane** [comment]
20.4.4.18 is out of support. Supported versions 20.9 20.10 20.11 and LTS.

Please provide excerpts around the error from a logfile

**Comment by mateng0915** [comment]
> Can the error be reproduced using Clickhouse client interactive mode? If we run the detail sql queries in 01281_join_with_prewhere_fix.sql multiply times?

it will not reproduce this error if i using Clickhouse client interactive mode. I think maybe this problems comes from clickhouse-test. Dose any tool can help me to locate the real reason for debug the clickhouse-test ?

**Comment by hexiaoting** [comment]
@mateng0915 clickhouse-test is a python file, you can debug clickhouse-test using 'ipdb'.

**Comment by alexey-milovidov** [comment]
It is expected that when you run `clickhouse-test` with the most fresh test suite over the old version of ClickHouse server, the server will crash. Because we have fixed the old crashes and there are test cases to reproduce them.
