### ISSUE TITLE
why the first 1e8 rows inserted and the 2nd 1e8 rows failed

### ISSUE THREAD

**Issue by l1t1** [ClickHouse/ClickHouse#17054]
```
create table sfz15y engine=MergeTree()order by id as select a.number*10000+b.number id from numbers(50000)a,numbers(10000)b;
insert into  sfz15y select (a.number+50000)*10000+b.number id from numbers(50000)a,numbers(10000)b;
insert into  sfz15y select (a.number)*10000+b.number id from numbers(50000)a,numbers(10000)b where b.number%5=0;
create table sfzcm engine=MergeTree()order by id as select id,count(*)c from sfz15y group by id having count(*)>1;
```
**failed, but the table was created** , then i try to reduce the rows.
```
insert into sfzcm select id,count(*)c from sfz15y where id<100000000  group by id having count(*)>1;
Query id: da659738-3916-466c-a392-718224d9e178

Ok.

0 rows in set. Elapsed: 10.615 sec. Processed 120.01 million rows, 960.10 MB (11.31 million rows/s., 90.45 MB/s.)

DESKTOP-RS3EG9A.localdomain :) select count(*) from sfzcm;

Query id: bd043a67-f81a-475e-90da-ebc6a44aabef

┌──count()─┐
│ 20000000 │
└──────────┘

1 rows in set. Elapsed: 0.002 sec.

insert into sfzcm select id,count(*)c from sfz15y where id>=100000000 and id<200000000  group by id having count(*)>1;
```
Received exception from server (version 20.11.3):
Code: 241. DB::Exception: Received from localhost:9000. DB::Exception: Memory limit (total) exceeded: would use 11.08 GiB (attempt to allocate chunk of 6291456 bytes), maximum: 11.08 GiB: While executing AggregatingTransform.

0 rows in set. Elapsed: 2.440 sec. Processed 92.93 million rows, 743.44 MB (38.08 million rows/s., 304.67 MB/s.)

**Comment by den-crane** [comment]
set max_memory_usage='10G', max_bytes_before_external_group_by='3G';

CREATE TABLE sfz15y
ENGINE = MergeTree()
ORDER BY id AS
SELECT (a.number * 10000) + b.number AS id
FROM numbers(50000) AS a
, numbers(10000) AS b

0 rows in set. Elapsed: 10.107 sec.



INSERT INTO sfz15y SELECT (a.number * 10000) + b.number AS id
FROM numbers(50000) AS a
, numbers(10000) AS b
WHERE (b.number % 5) = 0

0 rows in set. Elapsed: 4.232 sec.


CREATE TABLE sfzcm
ENGINE = MergeTree()
ORDER BY id AS
SELECT
    id,
    count(*) AS c
FROM sfz15y
GROUP BY id
HAVING count(*) > 1

0 rows in set. Elapsed: 53.631 sec.


insert into sfzcm select id,count(*)c from sfz15y where id<100000000  group by id having count(*)>1;

0 rows in set. Elapsed: 11.482 sec.


select count(*) from sfzcm;

┌───count()─┐
│ 120000000 │
└───────────┘


insert into sfzcm select id,count(*)c from sfz15y where id>=100000000 and id<200000000  group by id having count(*)>1;

0 rows in set. Elapsed: 11.149 sec.

```

**Comment by l1t1** [comment]
thanks, and I wonder why those two inserts need different memory size?

**Comment by den-crane** [comment]
Which 2 ?

**Comment by l1t1** [comment]
1.`insert into sfzcm select id,count(*)c from sfz15y where id<100000000  group by id having count(*)>1;`
2.`insert into sfzcm select id,count(*)c from sfz15y where id>=100000000 and id<200000000  group by id having count(*)>1;`

**Comment by den-crane** [comment]
SET send_logs_level = 'debug'

1 insert : MemoryTracker: Peak memory usage (for query): 4.93 GiB.
2 insert : MemoryTracker: Peak memory usage (for query): 4.02 GiB.

set max_memory_usage='40G', max_bytes_before_external_group_by=0

1 insert : MemoryTracker: Peak memory usage (for query): 5.06 GiB.
2 insert : MemoryTracker: Peak memory usage (for query): 5.06 GiB.

**Comment by l1t1** [comment]
thanks, one more question
how to check the current value of  `max_memory_usage, max_bytes_before_external_group_by` etc

**Comment by den-crane** [comment]
```sql
SELECT
    name,
    value
FROM system.settings
WHERE name IN ('max_memory_usage', 'max_bytes_before_external_group_by')

┌─name───────────────────────────────┬─value────────┐
│ max_bytes_before_external_group_by │ 76027960320  │
│ max_memory_usage                   │ 152055920640 │
└────────────────────────────────────┴──────────────┘

```

**Comment by l1t1** [comment]
got it. thanks
