### ISSUE TITLE
why i can not create a MATERIALIZED VIEW include union all

### ISSUE THREAD

**Issue by jinyan2049** [ClickHouse/ClickHouse#17058]
Dear All, Pls help me, why i can not create a MATERIALIZED VIEW include union all

ch :) create materialized view mv_Accounts_view engine=MergeTree() partition by createdAt order by id as select 'trade1' as tenant_id,t1.* from trade1.Accounts t1 left join trade2.Accounts t2 on t1.id=t2.id union all select 'trade2' as tenant_id,t2.* from trade1.Accounts t1 right join trade2.Accounts t2 on t1.id=t2.id;

CREATE MATERIALIZED VIEW mv_Accounts_view
ENGINE = MergeTree()
PARTITION BY createdAt
ORDER BY id AS
SELECT
    'trade1' AS tenant_id,
    t1.*
FROM trade1.Accounts AS t1
LEFT JOIN trade2.Accounts AS t2 ON t1.id = t2.id
UNION ALL
SELECT
    'trade2' AS tenant_id,
    t2.*
FROM trade1.Accounts AS t1
RIGHT JOIN trade2.Accounts AS t2 ON t1.id = t2.id

Query id: 509dfb78-2c5d-452d-ba29-2ca11b32be7b

Received exception from server (version 20.11.3):
**Code: 397. DB::Exception: Received from localhost:9000. DB::Exception: UNION is not supported for MATERIALIZED VIEW.**

0 rows in set. Elapsed: 0.009 sec.

ch :)

**Comment by den-crane** [comment]
MV does not support UNION ALL. You can create 2 MV and write their select results into one destination table using TO.

**Comment by Mr-KIDBK** [comment]
I don't understand why this design...

**Comment by SeeTomorrow** [comment]
if does not support UNION ALL,How can I merge two views

**Comment by jimmykuo** [comment]
> if does not support UNION ALL,How can I merge two views

CREATE TABLE t1()
ENGINE = MergeTree()...

CREATE MATERIALIZED VIEW `v1` TO t1
AS SELECT ...;

CREATE MATERIALIZED VIEW `v2` TO t1
AS SELECT ...;

**Comment by miaoyc666** [comment]
> 

I try this method, but it does not work

**Comment by ddxv** [comment]
Hopefully this helps anyone else looking for how to do UNION ALL like logic in materialized views.

## Combining Multiple Source Tables to Single Target Table
Materialized views can also be used to combine multiple source tables into the same destination table. This is useful for creating a materialized view that is similar to a `UNION ALL` logic.


First, create two source tables representing different sets of metrics.
```sql
CREATE TABLE analytics.impressions
(
    `event_time` DateTime,
    `domain_name` String
) ENGINE = MergeTree ORDER BY (domain_name, event_time)
;

CREATE TABLE analytics.clicks
(
    `event_time` DateTime,
    `domain_name` String
) ENGINE = MergeTree ORDER BY (domain_name, event_time)
;
```


Then create the `Target` table with the combined set of metrics.
```sql
CREATE TABLE analytics.daily_overview
(
    `on_date` Date,
    `domain_name` String,
    `impressions` SimpleAggregateFunction(sum, UInt64),
    `clicks` SimpleAggregateFunction(sum, UInt64)
) ENGINE = AggregatingMergeTree ORDER BY (on_date, domain_name)
```

Create two materialized views pointing to the same `Target` table. Note that you don't need to explicitly include the missing columns.
```sql
CREATE MATERIALIZED VIEW analytics.daily_impressions_mv
TO analytics.daily_overview
AS                                                
SELECT
    toDate(event_time) AS on_date,
    domain_name,
    count() AS impressions,
    0 clicks         ---<<<--- if you omit this, it will be the same 0
FROM                                              
    analytics.impressions
GROUP BY
    toDate(event_time) AS on_date,
    domain_name
;

CREATE MATERIALIZED VIEW analytics.daily_clicks_mv
TO analytics.daily_overview
AS
SELECT
    toDate(event_time) AS on_date,
    domain_name,
    count() AS clicks,
    0 impressions    ---<<<--- if you omit this, it will be the same 0
FROM
    analytics.clicks
GROUP BY
    toDate(event_time) AS on_date,
    domain_name
;
```



Now when you insert values, those values will be aggregated to their respective columns in the `Target` table.
```sql
INSERT INTO analytics.impressions (domain_name, event_time)
VALUES ('clickhouse.com', '2019-01-01 00:00:00'),
       ('clickhouse.com', '2019-01-01 12:00:00'),
       ('clickhouse.com', '2019-02-01 00:00:00'),
       ('clickhouse.com', '2019-03-01 00:00:00')
;

INSERT INTO analytics.clicks (domain_name, event_time)
VALUES ('clickhouse.com', '2019-01-01 00:00:00'),
       ('clickhouse.com', '2019-01-01 12:00:00'),
       ('clickhouse.com', '2019-03-01 00:00:00')
;
```

The combined impressions and clicks together in the `Target` table:
```sql
SELECT
    on_date,
    domain_name,
    sum(impressions) AS impressions,
    sum(clicks) AS clicks
FROM
    analytics.daily_overview
GROUP BY
    on_date,
    domain_name
;
```

```
┌────on_date─┬─domain_name────┬─impressions─┬─clicks─┐
│ 2019-01-01 │ clickhouse.com │           2 │      2 │
│ 2019-03-01 │ clickhouse.com │           1 │      1 │
│ 2019-02-01 │ clickhouse.com │           1 │      0 │
└────────────┴────────────────┴─────────────┴────────┘

3 rows in set. Elapsed: 0.018 sec.
```

**Comment by pkit** [comment]
@den-crane 
I can see that MVs with `UNION ALL` work pretty well in CH 23.12
Is it outdated now?

**Comment by den-crane** [comment]
@pkit ??? https://fiddle.clickhouse.com/aa49494b-552e-45b4-b29f-712faf99523b

DB::Exception: UNION is not supported for MATERIALIZED VIEW. (QUERY_IS_NOT_SUPPORTED_IN_MATERIALIZED_VIEW)

**Comment by pkit** [comment]
@den-crane hmm, interesting
I do have a very complicated MV that has `UNION ALL` that works.
I suppose `UNION` is not supported only in a specific case of straight union between two independent tables.
I need to see how can I simplify the query I have to see what's the difference (it's really 300 lines of SQL).
But the idea is like that:
![UNION drawio](https://github.com/ClickHouse/ClickHouse/assets/805654/b6499360-1fe4-45e5-b4e7-540090c8affd)
