### ISSUE TITLE
Materialized View storage_policy settings

### ISSUE THREAD

**Issue by jsding** [ClickHouse/ClickHouse#17053]
Hi,

Can I use storage_policy settings in Materialized View?

Thanks for your help.

**Comment by den-crane** [comment]
for example:
```
create materialized view mymv Engine=MergeTree partition by .... order by ....
settings index_granularity = 8192, 
              storage_policy = 'default' 
as select * from ....
```

https://den-crane.github.io/Everything_you_should_know_about_materialized_views_commented.pdf
https://youtu.be/ckChUkC3Pns?list=PLO3lfQbpDVI-hyw4MyqxEk3rDHw95SzxJ&t=9370
