### ISSUE TITLE
Materialized view from ReplicatedMergeTree  loosing data

### ISSUE THREAD

**Issue by MrSsunlight** [ClickHouse/ClickHouse#17052]
system: centos 7
clickhouse version: 20.3.11.97

**I have the following table structure：**
```
CREATE TABLE test.rep_log
(
    `tnow` DateTime, 
    ...
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{layer}-{shard}/test/rep_log', '{replica}')
PARTITION BY toYYYYMMDD(tnow)
ORDER BY (tnow, ...)
TTL tnow + toIntervalDay(20)
SETTINGS index_granularity = 16384, storage_policy = 'hdd_in_order', merge_with_ttl_timeout = 7200, use_minimalistic_part_header_in_zookeeper = 1
```

```
CREATE MATERIALIZED VIEW test.rep_log_view TO test.rep_log
(
    `tnow` DateTime, 
    ...
) AS
SELECT 
    a.tnow AS tnow, 
    ...
FROM test.rep_queue AS a
```

```
CREATE TABLE test.rep_log_dis
(
    `tnow` DateTime, 
    ...
)
ENGINE = Distributed('cluster_1st', 'test', 'rep_log')
```

```
CREATE TABLE test.rep_queue (
	`tnow` DateTime,
        ... ,
	INDEX ... GRANULARITY 2
) ENGINE = ReplicatedMergeTree('/clickhouse/tables/{layer}-{shard}/test/rep_queue', '{replica}') 
PARTITION BY toDate(tnow) 
ORDER BY (tnow, ...) 
TTL toDate(tnow) + toIntervalDay(2) 
SETTINGS 
	index_granularity = 16384, merge_with_ttl_timeout = 7200, storage_policy = 'hdd_in_order', use_minimalistic_part_header_in_zookeeper = 1
```

```
CREATE TABLE test.rep_queue_dis (
	`tnow` DateTime,
        ... 
) ENGINE = Distributed('cluster_1st', 'test', 'rep_queue')
```

**Data flow of each machine：**
    data --> rep_queue --> rep_log_view --> rep_log

**Problem phenomenon：**
Data is lost from rep_queue through rep_log_view to rep_log, but it will not be lost by manually executing mv select statement；
The difference is that mv is automatically triggered from **rep_queue**, and the test is queried from **rep_queue_dis**. But the indicators selected in the middle are completely consistent；
```
SELECT 
    a.tnow AS tnow, 
    ...
FROM test.rep_queue_dis AS a
```
The above test data is completely consistent

**Comment by den-crane** [comment]
Does it reproduce with non-replicated tables?

Check this https://clickhouse.tech/docs/en/operations/settings/settings/#settings-deduplicate-blocks-in-dependent-materialized-views

**Comment by MrSsunlight** [comment]
> Does it reproduce with non-replicated tables?
> 
> Check this https://clickhouse.tech/docs/en/operations/settings/settings/#settings-deduplicate-blocks-in-dependent-materialized-views

Default value used for this configuration，The SQL I created acquaintance has not reproduced, but the above process still has problems. Will it be related to zookeeper?

**Comment by den-crane** [comment]
Does it reproduce with non-replicated tables?

**Comment by MrSsunlight** [comment]
> 它可以与非复制表一起复制吗？

**Comment by MrSsunlight** [comment]
> Does it reproduce with non-replicated tables?

No, every node has data flowing in through mv, so replicated is used.

**Comment by den-crane** [comment]
Check this:
https://den-crane.github.io/Everything_you_should_know_about_materialized_views_commented.pdf
https://youtu.be/ckChUkC3Pns?list=PLO3lfQbpDVI-hyw4MyqxEk3rDHw95SzxJ&t=9371

Without a reproduction it hard to say what is wrong with your setup.

**Comment by MrSsunlight** [comment]
> Check this:
> https://den-crane.github.io/Everything_you_should_know_about_materialized_views_commented.pdf
> https://youtu.be/ckChUkC3Pns?list=PLO3lfQbpDVI-hyw4MyqxEk3rDHw95SzxJ&t=9371
> 
> Without a reproduction it's hard to say what is wrong with your setup.

Thanks i study
