### ISSUE TITLE
Can MaterializeMysql engine use keys or index from mysql?

### ISSUE THREAD

**Issue by 7omsxx** [ClickHouse/ClickHouse#17057]
Can materializeMysql engine use keys or index from mysql? if it support mysql index ,how to use it
How can i improve query speed while i'm using  materializeMysql with ClickHouse？
Where are the different features differ with ohthers Engine.
And  where can i get more info what MaterializeMysql .
Thanks.

**Comment by alexey-milovidov** [comment]
No.
