### ISSUE TITLE
update one column, all partitio created an COW dir

### ISSUE THREAD

**Issue by ZonghaoWang** [ClickHouse/ClickHouse#17060]
I have a table partition by `date`, and order by (pid, fid). fid is unique

when I process `alter table $table_name update is_delete = 1 where date = $date and fid = $fid`
then all partition has an COW dir, and the created time of dir is the mutation process time

**Comment by den-crane** [comment]
It's how mutations work now.

will be addressed here https://github.com/ClickHouse/ClickHouse/pull/13403
