### ISSUE TITLE
 The Transfer-Encoding is not chunked and there is no Content-Length header for POST

### ISSUE THREAD

**Issue by RonanMorgan** [ClickHouse/ClickHouse#17073]
Hello,

I am saving data into clickhouse thanks to the ClickHousePreparedStatementImpl of the [official jdbc driver](https://github.com/ClickHouse/clickhouse-jdbc), in a batch way (preparedStatement -> fillStatement -> executeBatch)

I am saving data from many sites, each site having it's own batch, but only one of the 3OO+ sites has the following errors (it happens three times a day) :

> 2020.11.16 01:35:56.630745 [ 1613470 ] {} <Error> DynamicQueryHandler: Code: 381, e.displayText() = DB::Exception: The Transfer-Encoding is not chunked and there is no Content-Length header for POST request, Stack trace (when copying this message, always include the lines below):
> 
> 0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x12405650 in /usr/bin/clickhouse
> 1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xa2423fd in /usr/bin/clickhouse
> 2. ? @ 0xfb083bc in /usr/bin/clickhouse
> 3. Poco::Net::HTTPServerConnection::run() @ 0x122e51c3 in /usr/bin/clickhouse
> 4. Poco::Net::TCPServerConnection::start() @ 0x1232347b in /usr/bin/clickhouse
> 5. Poco::Net::TCPServerDispatcher::run() @ 0x1232390b in /usr/bin/clickhouse
> 6. Poco::PooledThread::run() @ 0x124a2436 in /usr/bin/clickhouse
> 7. Poco::ThreadImpl::runnableEntry(void*) @ 0x1249d830 in /usr/bin/clickhouse
> 8. start_thread @ 0x82de in /usr/lib64/libpthread-2.28.so
> 9. __GI___clone @ 0xfbe83 in /usr/lib64/libc-2.28.so
>  (version 20.6.3.28 (official build))

Of course I am using the same code for each sites, and when I check in the clickhouse's log for other queries the Transfer-Encoding is chunked 
This site might be the biggest one, could it be a threshold effect ? Maybe I am saving too much data in one batch ?

**Comment by filimonov** [comment]
That sounds like client issue. You need to record the trafic beween problematic client and server, and check which headers does it send. (use tcpdump / wireshark or similar tools).

**Comment by RonanMorgan** [comment]
Hello,

thanks for your answer,

I am doing hundred's of queries per seconds and it seems that the error can happen at anytime during the day, so it will pretty hard to find it with wireshark.

I have just created an issue on the [client side](https://github.com/ClickHouse/clickhouse-jdbc/issues/518) to see if they have an idea, else I will give it a try.

Thanks,
