### ISSUE TITLE
Leap seconds support

### ISSUE THREAD

**Issue by zvonand** [ClickHouse/ClickHouse#17079]
To PR #9404 (maybe)
@Enmk (maybe)

Currently [leap seconds](https://en.wikipedia.org/wiki/Leap_second) are neither supported by ClickHouse's DateTime and DateTime64 nor mentioned in [documentation](https://clickhouse.tech/docs/en/) as being unsupported. There are a couple of dozens of them, so adding them may be not-so-complicated. 
It may be also a small nice feature of CH, as other DBMS such as PostgreSQL and MySQL don't support this.

**Comment by den-crane** [comment]
hm, but Gregorian calendar itself does support leap seconds? AFAIK there is no leap seconds in human calendars?

**Comment by filimonov** [comment]
> Gregorian calendar itself does support leap seconds?  human calendars?

They have. 

> Leap seconds just last longer than general seconds ? 

That's how it works with Unix timestamps.  We use unix epoch internally.
Leap seconds are not supported there. 

So '2005-12-31 23:59:60 UTC' (which can be stored as string / human readable format) can not be represented as unix timestamp (or will be represented just like '2005-12-31 23:59:59 UTC'). 

in unix timestamps difference '2006-01-01 00:00:00' - '2005-12-31 23:59:59' is exactly one second (not 2).  

> Not supporting leap seconds means that Unix time does not have any way to represent the leap second in the form of 23:59:60. Instead it just uses the same second twice. In practical terms, that means that Unix time progressed like this during the year transition: 1230767999, 1230768000, 1230768000 and 1230768001. The first 1230768000 represents 2008-12-31 23:59:60 UTC, and the second 1230768000 represents 2009-01-01 00:00:00 UTC. 

There is no way to fix that (w/o changing the internal DateTime representation).

**Comment by alexey-milovidov** [comment]
It's unclear how we should support leap seconds - what the behaviour will be.

We are using unix timespamp internally - it is already aware of the leap seconds and Linux handles it in a way that some value of unix timespamp is either skipped or stretched to two seconds, so every minute interval makes a range of 60 timestamp values, regardless of containing in fact 59 or 61 seconds of real time.

Unix timestamp and Linux makes it that way so we should not try to do anything special.

But what do you expect from the user perspective?

**Comment by alexey-milovidov** [comment]
I'm adding "need info" and also closing with "won't fix" in case no info will be provided :)
