### ISSUE TITLE
system.ddl_(worker)_queue table

### ISSUE THREAD

**Issue by alesapin** [ClickHouse/ClickHouse#17082]
For better `ON CLUSTER` queries usability, we can introduce `system.ddl_worker_queue` table with entries from `DDLWorkers` queue.

**Comment by bharatnc** [comment]
@alesapin I think I can take a stab at this - can I have this assigned to me?

**Comment by alesapin** [comment]
> @alesapin I think I can take a stab at this - can I have this assigned to me?

Of course!

**Comment by filimonov** [comment]
Implemented
