### ISSUE TITLE
FINAL on Union View not propagated

### ISSUE THREAD

**Issue by YordanPavlov** [ClickHouse/ClickHouse#17087]
I have a VIEW table defined as UNION ALL over two tables with identical schemas. Is there a way to propagate a FINAL request for data de-duplication through a SELECT call on the view table. In my tests this is not happening. Let's say the table is defined like so:

```
CREATE VIEW default.merging_table
(
    `address` UInt64
) AS
SELECT address
FROM default.source_table_1
UNION ALL
SELECT address
FROM default.source_table_2
```

what I want to achieve is have a query like:
```
SELECT * FROM merging_table FINAL
```
to result in:

```
SELECT address
FROM default.source_table_1 FINAL
UNION ALL
SELECT address
FROM default.source_table_2 FINAL
```

In my tests this is not happening and the way to do it is to define the view having FINAL in its definition. But this makes all queries through the view forcing de-duplication, which may not be always requested.

Thanks in advance.

**Comment by filimonov** [comment]
There is no way for that (currently). 

As a workaround you can create 2 views: one with final, another without.
