### ISSUE TITLE
MaterializeMySQL not gen parts with mysql primarykey and index

### ISSUE THREAD

**Issue by 7omsxx** [ClickHouse/ClickHouse#17114]
While i'm sync data from mysql to clickHouse  by MaterializeMySQL ,index and primary key not sync to clickhouse.
clickHouse的数据分区不是以mysql的主键和索引分布，分区是以 all_开头分区的
![image](https://user-images.githubusercontent.com/45144402/99353056-bf2a4000-28de-11eb-922d-8e6da6dc4fe8.png)
![image](https://user-images.githubusercontent.com/45144402/99353083-cbae9880-28de-11eb-9064-eddc77a3af85.png)

需要怎么调整mysql的索引才能在clickHouse的数据能分区。

**Comment by tavplubix** [comment]
> clickHouse的数据分区不是以mysql的主键和索引分布，分区是以 all_开头分区的
> 需要怎么调整mysql的索引才能在clickHouse的数据能分区。

Machine translation:
> The data partition of clickHouse is not distributed by the primary key and index of mysql, the partition is partitioned at the beginning of all_
> How to adjust the mysql index to partition the data in clickHouse.

MySQL keys are converted to ClickHouse `ORDER BY` key. You can check it by executing
`cat /var/lib/clickhouse/metadata/database_name/table_name.sql`

As for `PARTITION BY` key in ClickHouse, it does not significantly affect query performance, so it's ok if table does not have `PARTITION BY` key. MaterializeMySQL engine tries to choose some partition key if possible, but it's not a big issue if partition key cannot be chosen automatically.
