### ISSUE TITLE
MySQL add support for SQL_SELECT_LIMIT (compatibility with datastudio)

### ISSUE THREAD

**Issue by god1dog** [ClickHouse/ClickHouse#17115]
**Describe the issue**
Compatibility issue google datastudio is sent by default SQL_SELECT_LIMIT connection occurs via mysql interface. Google ignores this issue https://support.google.com/datastudio/thread/71033546?hl=en
Add option to system.settings table fails _Method write is not supported by storage SystemSettings_

**How to reproduce**
* version 20.11.2.1 (official build)

**Comment by filimonov** [comment]
It's a part of https://github.com/ClickHouse/ClickHouse/issues/9336  /cc @BohuTANG 

I would expect that it can be directly transformed to 

```
set max_result_rows=123,result_overflow_mode='break';
```

But for some reason, it doesn't work properly... 
```
 select * from system.numbers;
--- 65505 rows in set. Elapsed: 0.021 sec. Processed 65.50 thousand rows, 524.04 KB (3.19 million rows/s., 25.55 MB/s.) 
```

**Comment by alexey-milovidov** [comment]
@filimonov It's correct, as it is designed, as in docs.
It means: break after the specified number of rows is received in the result.
Result is formed in blocks. We don't cut blocks.

**Comment by filimonov** [comment]
> @filimonov It's correct, as it is designed, as in docs.
> It means: break after the specified number of rows is received in the result.
> Result is formed in blocks. We don't cut blocks.

That's OK.

**Comment by god1dog** [comment]
Tell me how long to wait for a solution to this problem?

**Comment by filimonov** [comment]
Well it's open source project. If you (or somebody else from community, may be your friend) will pick/fix that today it can be fixed tomorrow. :)

Core team has a lot of bigger stories, and a lot of things todo. It doesn't sound like top priority feature.

**Comment by filimonov** [comment]
https://github.com/ClickHouse/ClickHouse/issues/16176

**Comment by alexey-milovidov** [comment]
I've reproduced the issue with Google Data Studio.
Looks like it's easy to fix.

**Comment by kssenii** [comment]
**Google data studio:**

![Screenshot from 2021-07-05 06-01-29](https://user-images.githubusercontent.com/54203879/124412172-944e0880-dd56-11eb-8c3b-a482d58fe255.png)

**Before:**
```code
2021.07.04 14:59:36.100108 [ 6638 ] {} <Debug> MySQLHandler: Received command: 3. Connection id: 7.
2021.07.04 14:59:36.101071 [ 6638 ] {mysql:7} <Debug> executeQuery: (from 127.0.0.1:38246) SET SQL_SELECT_LIMIT=150042
2021.07.04 14:59:36.101872 [ 6638 ] {mysql:7} <Error> executeQuery: Code: 115, e.displayText() = DB::Exception: Unknown setting SQL_SELECT_LIMIT (version 21.8.1.1) (from 127.0.0.1:38246) (in query: SET SQL_SELECT_LIMIT=150042), Stack trace (when copying this message, always include the lines below):

0. /home/kssenii/workspace/Clicky/build-asan/../contrib/libcxx/include/exception:133: Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x2a0b0e09 in /home/kssenii/workspace/Clicky/build-asan/programs/clickhouse
1. /home/kssenii/workspace/Clicky/build-asan/../src/Common/Exception.cpp:59: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xb28d742 in /home/kssenii/workspace/Clicky/build-asan/programs/clickhouse
2. /home/kssenii/workspace/Clicky/build-asan/../src/Core/BaseSettings.cpp:44: DB::BaseSettingsHelpers::throwSettingNotFound(std::__1::basic_string_view<char, std::__1::char_traits<char> > const&) @ 0x1f9dddd4 in /home/kssenii/workspace/Clicky/build-asan/programs/clickhouse
3. /home/kssenii/workspace/Clicky/build-asan/../src/Access/AccessControlManager.cpp:112: DB::AccessControlManager::CustomSettingsPrefixes::checkSettingNameIsAllowed(std::__1::basic_string_view<char, std::__1::char_traits<char> > const&) const @ 0x1f70f6d5 in /home/kssenii/workspace/Clicky/build-asan/programs/clickhouse


```
**Now:**
![Screenshot from 2021-07-05 05-53-42](https://user-images.githubusercontent.com/54203879/124411590-7f24aa00-dd55-11eb-88ac-4973c5a51e1e.png)
