### ISSUE TITLE
clickhouse-client: allow to set query parameters interactively.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#17113]
**Use case**
```
:) SET ...some syntax... param = 'xyz'
:) SELECT * FROM table WHERE user_name = {param:String}
and maybe
:) SELECT * FROM table WHERE user_name = {param}
```

We can store query parameters in the session. And make a query to manipulate the parameters.

**Comment by amosbird** [comment]
Perhaps we can also implement some SQL action to invoke customized http handlers. It'll look like naive user defined SQL functions.

**Comment by alexey-milovidov** [comment]
Also we can make them available as table functions to allow SELECT from these handlers or INSERT INTO TABLE FUNCTION.
```
SELECT * FROM handler(param1 = 'hello', param2 = 'world')
```

**Comment by alexey-milovidov** [comment]
Another possibility is to allow to create VIEWs with parametrized queries. SELECT from VIEW will work only if parameters are defined.

**Comment by joshxyzhimself** [comment]
Hi, is this possible in the HTTP Interface?

https://clickhouse.tech/docs/en/interfaces/http/

I've been getting

```
Error: Code: 113, e.displayText() = DB::Exception: There is no session (version 20.11.4.13 (official build))
```

**Comment by smagellan** [comment]
@alexey-milovidov, are you talking about 'Prepared Statements' concept (parametrized query AST caching on server side, etc)?

**Comment by alexey-milovidov** [comment]
Wow, this task is solved!

**Comment by alexey-milovidov** [comment]
https://github.com/ClickHouse/ClickHouse/pull/39906
