### ISSUE TITLE
Marks cache accounting in system.parts

### ISSUE THREAD

**Issue by bobrik** [ClickHouse/ClickHouse#1712]
Currently it's only possible to know how much mark cache is used total:

![image](https://user-images.githubusercontent.com/89186/34392471-208c8fc0-eb01-11e7-9b14-5a3f8a55d358.png)

But it seems impossible to have breakdowns per table. It'd be nice to a column about in-memory marks cache usage in `system.parts` table.

**Comment by alexey-milovidov** [comment]
Currently mark cache is shared and we don't have information about a table in mark cache entries.
Nevertheless, it is possible to add.

To do this, we need to add callbacks to LRUCache for storing and eviction; add reference to per-table counter in entries of MarkCache, and use these references in callbacks.
