### ISSUE TITLE
Table ORDER BY wrong "less" comparison with key Date column and DateTime value

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#17122]
**Describe the bug**
If we use WHERE clause with a condition in which we compare the Date column from table ORDER BY and DateTime value that can lead to wrong results for the certain date of DateTime value.

**How to reproduce**
Clickhouse version 20.12, 20.3.21, 20.8.6.6
```
CREATE TABLE test_index(date Date) ENGINE=MergeTree() PARTITION BY toYYYYMM(date) ORDER BY date;
INSERT INTO test_index VALUES('2020-10-30');
SELECT 1
FROM test_index
WHERE date < toDateTime('2020-10-30 06:00:00');

Query id: 2a5ff79c-a109-40be-b23c-7693a0918335

Ok.

0 rows in set. Elapsed: 0.002 sec.

SELECT 1
FROM test_index
WHERE materialize(date) < toDateTime('2020-10-30 06:00:00');

Query id: 807b6095-f26b-48f2-967f-0ad9d4d0471f

┌─1─┐
│ 1 │
└───┘

1 rows in set. Elapsed: 0.002 sec.
```

**Expected behavior**
Clickhouse returns consistent results for both queries.

**Comment by amosbird** [comment]
Heh. It also indicates another issue: `key DateTime column and Date value`. Both are fixed in https://github.com/ClickHouse/ClickHouse/pull/17145
