### ISSUE TITLE
UDAF run slower in 2 nodes than in a single node

### ISSUE THREAD

**Issue by shangshujie365** [ClickHouse/ClickHouse#1713]
I wrote my own udaf function 'MyUdaf', I found it run slower in Distributed tables, and I found many udaf can't run faster in 2 nodes than in a single node.
I add some logs in merge/addImpl/Serielize function, I found only addImpl be called, merge functions is never called. I think the aggregate threads(even in cluster mode) only collect data and passed them to the main thread, no local merge in them.

My table is like this:
table tmp (userId, eventId)
My sql is like this:
select MyUdaf(events) from select groupArray(eventId) as events from tmp group by userId 
And My table is distributed by userId, that means different userIds are in different nodes.
So, why not combine data in local node, and just pass the result of 'MyUdaf' to the query node? It's a small number of data compare to the mass pre-aggregate data

**Comment by alexey-milovidov** [comment]
> So, why not combine data in local node, and just pass the result of 'MyUdaf' to the query node? It's a small number of data compare to the mass pre-aggregate data

This is exactly how ClickHouse works. On each server, it first combines all aggregation states from each thread of execution and then send combined state to the initiator server.

In your query:
```
select MyUdaf(events) from (select groupArray(eventId) as events from tmp group by userId)
```
there are pipeline of two aggregations:

First, data from table `tmp` is fetched with multiple streams and the aggregation `groupArray(eventId)` is calculated in multiple threads.

Then, intermediate result from subquery is passed to outer query and `MyUdaf(events)` is calculated.
But intermediate result after first aggregation is consisted of single stream and thus cannot be parallelized. This explains why you don't see calls to `IAggregateFunction::merge` for your function `MyUdaf`.

This can be improved. Why we return data from the subquery in single stream? And maybe, if it is single stream, but multiple blocks of data, it still can be parallelized? It's not hard to implement.

**Comment by shangshujie365** [comment]
I sugest clickhouse can call merge between the execute threads before they send the results to the initial thread, and that is what merge means.
For execution plan now clickhouse has, the merge/ serialize / deserialize is useless.

**Comment by shangshujie365** [comment]
Hi, after add some debug logs to AggregateFunctionCount, -MinMaxAny, I found even these very common operator (like sum, max, min, count) didn't call merge. If add call to 'merge', I think the speed will faster much.

**Comment by shangshujie365** [comment]
Sorry, I found 'merge' log in 'select count group by', so, my advice is,

**Comment by shangshujie365** [comment]
Hi, after add some debug log and do some tests, I found:
1) the 'inner aggregate function with group by' works just like what I want
2) the 'outer aggregate function' is grouped by the distributed keys, so it should be aggregated first in sub-data-node before the result send to the query-node,  so, it seems ch lack some optimized paln in multi-level group by
3) may be you can introduce some DAG planner?

**Comment by shangshujie365** [comment]
May be ch should add some shardingkey-aware distributed plan

**Comment by qoega** [comment]
Thank you for your interest in ClickHouse optimization.
You can make an issue with more specific proposal what can be done.
Current question is answered.
