### ISSUE TITLE
Scalar subqueries don't work with CTE syntax

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#17136]
ClickHouse alias syntax:
`WITH (SELECT 1) AS x SELECT x`
Ok.

CTE syntax:
`WITH x AS (SELECT 1) SELECT x`
Missing columns: 'x'.

**Comment by amosbird** [comment]
It's by design...  Those identifiers can appear in places where table objects are allowed.  It's like we do `select table_1 from system.numbers`

**Comment by alexey-milovidov** [comment]
Ok.

**Comment by l1t1** [comment]
you should add a col name for const value
```
WITH x AS
    (
        SELECT 1 AS n
    )
SELECT n
FROM x

Query id: 8c1a7afc-6f91-4715-aabf-ca1057025813

┌─n─┐
│ 1 │
└───┘

1 rows in set. Elapsed: 0.036 sec.
```

**Comment by l1t1** [comment]
but this syntax works in oracle,
```
SQL> WITH x(n) AS (SELECT 1 from dual) SELECT n from x;

         N
----------
         1
```
 doesn't work in ch
```
VM_0_52_centos :) WITH x(n) AS (SELECT 1 ) SELECT n from x;

Syntax error: failed at position 14 ('('):

WITH x(n) AS (SELECT 1 ) SELECT n from x;

Expected identifier

```

**Comment by alexey-milovidov** [comment]
Yes, it is the syntax for column names for CTE, it's not supported.
