### ISSUE TITLE
RBAC - User doen't need KILL QUERY grant to execute KILL QUERY.

### ISSUE THREAD

**Issue by MyroTk** [ClickHouse/ClickHouse#17147]
**Describe the bug**
User is able to execute `KILL QUERY` without having the `KILL QUERY` grant.

**How to reproduce**
* ClickHouse server version 20.12.1.1

* Queries to run that lead to unexpected result
```
ClickHouse client version 20.12.1.1.
Connecting to localhost:9000 as user user0.
Connected to ClickHouse server version 20.12.1 revision 54442.

clickhouse1 :) kill query where 1

KILL QUERY WHERE 1 ASYNC

Query id: 45f5ec6a-3fbf-4764-822c-f02921b54a47

Ok.

0 rows in set. Elapsed: 0.002 sec.
```
```
clickhouse1 :) show grants for user0

SHOW GRANTS FOR user0

Query id: 9f65daa0-5465-4b16-ae72-78e5b8b985b1

Ok.

0 rows in set. Elapsed: 0.001 sec.
```

**Comment by alexey-milovidov** [comment]
@MyroTk Isn't it alright if user is always being able to kill their own queries?

**Comment by alexey-milovidov** [comment]
@vitlibar has confirmed that it works perfectly as expected.

**Comment by alexey-milovidov** [comment]
The KILL grant is only needed to kill other users queries.
