### ISSUE TITLE
Can '20201171153700.000' be converted to timestamp directly?

### ISSUE THREAD

**Issue by trollhe** [ClickHouse/ClickHouse#17163]
Hello,

     Can '20201171153700.000' be converted to timestamp directly?Now the conversion efficiency is too low, can there be a very direct way to format conversion?

**Comment by den-crane** [comment]
2020  11  71  15  37  00  .000

What is 71 ?

```
SELECT parseDateTimeBestEffort('20201117153700.000')

Query id: 3ca49955-ea72-480b-807f-daea1b35c4ad

┌─parseDateTimeBestEffort('20201117153700.000')─┐
│                           2020-11-17 15:37:00 │
└───────────────────────────────────────────────┘
```

or `date_time_input_format = 'best_effort';` for inserts

https://clickhouse.tech/docs/en/sql-reference/functions/type-conversion-functions/#parsedatetimebesteffort

**Comment by trollhe** [comment]
> 2020 11 71 15 37 00 .000
> 
> What is 71 ?
> 
> ```
> SELECT parseDateTimeBestEffort('20201117153700.000')
> 
> ┌─parseDateTimeBestEffort('20201117153700.000')─┐
> │                           2020-11-17 15:37:00 │
> └───────────────────────────────────────────────┘
> 
> 
> 
> SELECT parseDateTime64BestEffortOrNull('20201117153700.220')
> 
> ┌─parseDateTime64BestEffortOrNull('20201117153700.220')─┐
> │                               2020-11-17 15:37:00.220 │
> └───────────────────────────────────────────────────────┘
> 
> 
> SELECT parseDateTime64BestEffortOrNull('20201171153700.000')
> ┌─parseDateTime64BestEffortOrNull('20201171153700.000')─┐
> │                                                  ᴺᵁᴸᴸ │
> └───────────────────────────────────────────────────────┘
> ```
> 
> or `date_time_input_format = 'best_effort';` for inserts
> 
> https://clickhouse.tech/docs/en/sql-reference/functions/type-conversion-functions/#parsedatetimebesteffort

thank you ,den-crane, it is `20201117153700.000`
