### ISSUE TITLE
does clickhouse support the create of function custom ？

### ISSUE THREAD

**Issue by trollhe** [ClickHouse/ClickHouse#17162]
hello，

      For some specific scenarios, the built-in functions can not meet the requirements, or the efficiency is too low. I am familiar with C pre research programming. Can I develop functions by myself and put them in the Clickhouse?

**Comment by den-crane** [comment]
Yes. You can.

https://clickhouse.tech/docs/en/development/developer-instruction/

**Comment by trollhe** [comment]
> Yes. You can.
> 
> https://clickhouse.tech/docs/en/development/developer-instruction/

that`s great,thank you.
