### ISSUE TITLE
MySQL add support for UTC_TIMESTAMP() AND TIMEDIFF (comparability with Power BI)

### ISSUE THREAD

**Issue by marrocksd** [ClickHouse/ClickHouse#17177]
**Background**
I can already connect to Power BI using ODBC connector, but it would be so great if I can make a Direct Query connection to utilize the full power of OLAP DB. I tried to achieve that with MySQL interface which has PBI Direct Query support.

**Describe the issue**
Unfortunate, when I make the connection, Power BI automatically runs this function in background:

TIMEDIFF(NOW(), UTC_TIMESTAMP())

I guess it is to set the serverTimeZone.

![image](https://user-images.githubusercontent.com/58497107/99525717-c891d600-29cc-11eb-9987-a9fdda6f012b.png)

**How to reproduce**
Clickhouse version 20.11.3.3 (official build)
Make connection from Power BI Desktop to MySQL Interface

**Final words**
I know that there are several functions to achieve the same result, so I hope this won't take much effort from you guys.
If this is done, I believe it would be a huge advantage for ClickHouse
Thanks in advance

**Comment by hurtmenot271** [comment]
Yeah, I have the same.

**Comment by phongbui81062** [comment]
anybody can help me solving this issue?

**Comment by Long14110** [comment]
> Yeah, I have the same issue
> .

me too

**Comment by alexey-milovidov** [comment]
`UTC_TIMESTAMP` is very easy to implement,
but `TIMEDIFF(NOW(), UTC_TIMESTAMP)` will not work as expected.

To solve this task properly, we need the notion of protocol-specific AST rewriters.

**Comment by alexey-milovidov** [comment]
```
ip-172-31-8-4.eu-central-1.compute.internal :) SELECT TIMEDIFF(NOW(), UTC_TIMESTAMP())

SELECT TIMEDIFF(NOW(), UTC_TIMESTAMP())

Query id: 43e830be-1d71-4d2c-aa5e-c0835a54de26

┌─TimeDiff(now(), UTCTimestamp())─┐
│                               0 │
└─────────────────────────────────┘
```
