### ISSUE TITLE
Движок Buffer + ReplicatedMergeTree

### ISSUE THREAD

**Issue by vklimenkov** [ClickHouse/ClickHouse#17180]
Добрый день!
Вопрос, можно ли использовать таблицу типа Buffer над таблицей ReplicatedMergeTree? У нас идёт порядка 5 инсертов в секунду, хотелось бы буферизировать данные для снижения нагрузки. Но, смущает фраза из документации:

> Если таблица назначения является реплицируемой, то при записи в таблицу Buffer будут потеряны некоторые ожидаемые свойства реплицируемых таблиц

У нас две реплики, инсерты идут только в первую реплику. Таблица типа ReplicatedMergeTree, т.е. порядок вставки не важен. Читать будем только из таблицы, не из буфера. Какие могут быть проблемы? Действительно ли есть риск получить дублирующиеся строки или рассогласование реплик?

**Comment by den-crane** [comment]
Дедупликация инсертов перестанет работать. Вы повторяете идентичный инсерт, а engine Buffer нарушает идентичность потому порежет его на куски и склеит с другими кусками других инсертов.

Возможно вы не используете дедупликацию инсертов, тогда вам это нерелевантно.

https://clickhouse.tech/docs/ru/engines/table-engines/mergetree-family/replication/

_Блоки данных дедуплицируются. При многократной записи одного и того же блока данных (блоков данных одинакового размера, содержащих одни и те же строчки в одном и том же порядке), блок будет записан только один раз. Это сделано для того, чтобы в случае сбоя в сети, когда клиентское приложение не может понять, были ли данные записаны в БД, можно было просто повторить запрос INSERT. При этом не имеет значения, на какую реплику будут отправлены INSERT-ы с одинаковыми данными. Запрос INSERT идемпотентный. Параметры дедуплицирования регулируются настройками сервера merge_tree_

**Comment by vklimenkov** [comment]
Благодарю за ответ! Да, дедупликацию мы не используем. Так что будем пробовать Buffer.
