### ISSUE TITLE
suggest add sql features of latest actian vector

### ISSUE THREAD

**Issue by l1t1** [ClickHouse/ClickHouse#17185]
https://esd.actian.com/product/Vector/6.0/docs/Vector_6.0_Documentation

and add some new benchmark data

**Comment by l1t1** [comment]
[Vector_SQL.pdf](https://github.com/ClickHouse/ClickHouse/files/5563637/Vector_SQL.pdf)
prior version

**Comment by filimonov** [comment]
Do you mean / need something specific?

P.S. We definitely have no plan to "support all the SQL features which product XXX provides"

**Comment by l1t1** [comment]
window functions on page 60~70. I request to support them.

**Comment by l1t1** [comment]
window functions on page 60~70. I request to support them.

**Comment by l1t1** [comment]
window functions on page 60~70. I request to support them.

**Comment by alexey-milovidov** [comment]
We have implemented window functions.
