### ISSUE TITLE
20.3.10.75 TTL can't work

### ISSUE THREAD

**Issue by shangshujie365** [ClickHouse/ClickHouse#17191]
table (dt DateTime) partition by toDate(dt) TTL  toDate(dt) + interval 2 day,  it has 4 days data:
2020-11-15
2020-11-16
2020-11-17
2020-11-18
after 1 day, it's 2020-11-19 now, but nothing deleted

**Comment by shangshujie365** [comment]
The data of '2020-11-17' deleted, but older data in '11-15', '11-16' not deleted

**Comment by den-crane** [comment]
How is table partitioned? Daily ?
