### ISSUE TITLE
The service of clickhouse replica couldn't load successfully

### ISSUE THREAD

**Issue by taylor131415** [ClickHouse/ClickHouse#17199]
Clickhouse version：20.11.3.3
Environment：3shards_2replicas（three server machines and two replicas on every server machine ）
Issue description：
1. Create a 3shards_1replicas cluster environment，it can work successfully。
2. Copy files：config.xml metrial.xml /etc/init.d/clickhouse-server to config1.xml metrial1.xml /etc/init.d/clickhouse-server1 and change these copied files' tcp port/http port/interserver_http_port/related log pathes/cluster info... and so on, in order to create a new service about replica：clickhouse-server1
3. Try to start the new replica's service clickhouse-server1, service couldn't load successfully, but the initial clickhouse service could load successfully：
![clickhouse-server1](https://user-images.githubusercontent.com/74707266/99648958-98127080-2a8e-11eb-9302-897ecc39b098.jpg)
![clickhouse-server](https://user-images.githubusercontent.com/74707266/99648961-99439d80-2a8e-11eb-8d07-79831c7a4eff.jpg)

**Comment by den-crane** [comment]
You need to change path to  --pid-file and /var/lib/clickhouse/status and datapath and temppath in config.xml ( /var/lib/clickhouse/)

**Comment by taylor131415** [comment]
> 您需要将路径更改为--pid-file和/ var / lib / clickhouse / status以及config.xml（/ var / lib / clickhouse /）中的数据路径和temppath
> 
> / etc / clickhouse-server /
> /var/run/clickhouse-server/clickhouse-server.pid
> / var / log / clickhouse-server /
> / var / lib / clickhouse /
> / var / lib / clickhouse / status

All related pathes have been changed like this in replica config file:/etc/clickhouse-server1/config1.xml：
<log>/var/log/clickhouse-server1/clickhouse-server1.log</log>
<errorlog>/var/log/clickhouse-server1/clickhouse-server1.err.log</errorlog>
<path>/var/lib/clickhouse1/</path>
<tmp_path>/var/lib/clickhouse1/tmp/</tmp_path>

And change the replica's init.d file:/etc/init.d/clickhouse-server1 like this：
CLICKHOUSE_USER=clickhouse
CLICKHOUSE_GROUP=${CLICKHOUSE_USER}
SHELL=/bin/bash
PROGRAM=clickhouse-server
CLICKHOUSE_GENERIC_PROGRAM=clickhouse
CLICKHOUSE_PROGRAM_ENV=""
EXTRACT_FROM_CONFIG=${CLICKHOUSE_GENERIC_PROGRAM}-extract-from-config
CLICKHOUSE_CONFDIR=/etc/clickhouse-server1
CLICKHOUSE_LOGDIR=/var/log/clickhouse-server1
CLICKHOUSE_LOGDIR_USER=root
CLICKHOUSE_DATADIR=/var/lib/clickhouse1
if [ -d "/var/lock" ]; then
    LOCALSTATEDIR=/var/lock
else
    LOCALSTATEDIR=/run/lock
fi

if [ ! -d "$LOCALSTATEDIR" ]; then
    mkdir -p "$LOCALSTATEDIR"
fi
CLICKHOUSE_BINDIR=/usr/bin
CLICKHOUSE_CRONFILE=/etc/cron.d/clickhouse-server
CLICKHOUSE_CONFIG=$CLICKHOUSE_CONFDIR/config1.xml
LOCKFILE=$LOCALSTATEDIR/$PROGRAM
CLICKHOUSE_PIDDIR=/var/run/$PROGRAM
CLICKHOUSE_PIDFILE="$CLICKHOUSE_PIDDIR/$PROGRAM-1.pid"

Input：systemctl start clickhouse-server1：
Info：clickhouse-server1.service - LSB: Yandex clickhouse-server daemon
   Loaded: loaded (/etc/rc.d/init.d/clickhouse-server1; bad; vendor preset: disabled)
   Active: active (exited) since Fri 2020-11-20 10:24:57 CST; 9min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 20085 ExecStop=/etc/rc.d/init.d/clickhouse-server1 stop (code=exited, status=0/SUCCESS)
  Process: 20104 ExecStart=/etc/rc.d/init.d/clickhouse-server1 start (code=exited, status=0/SUCCESS)

Nov 20 10:24:57 localhost.localdomain systemd[1]: Starting LSB: Yandex clickhouse-server daemon...
Nov 20 10:24:57 localhost.localdomain clickhouse-server1[20104]: Init script is already running
 
The replica's service：clickhouse-server1 still can't load successfully

**Comment by taylor131415** [comment]
> 您需要将路径更改为--pid-file和/ var / lib / clickhouse / status以及config.xml（/ var / lib / clickhouse /）中的数据路径和temppath
> 
> / etc / clickhouse-server /
> /var/run/clickhouse-server/clickhouse-server.pid
> / var / log / clickhouse-server /
> / var / lib / clickhouse /
> / var / lib / clickhouse / status

Config pictures /etc/init.d/clickhouse-server1 as below：
![etc_init d_clickhouse-server](https://user-images.githubusercontent.com/74707266/99755189-19b4dd80-2b25-11eb-991e-28a3d346eb03.jpg)
systemctl status clickhouse-server1：
![systemctl_status_clickhouse-server1](https://user-images.githubusercontent.com/74707266/99755205-23d6dc00-2b25-11eb-9e12-38ada3f5cf07.png)

**Comment by den-crane** [comment]
please show 
journalctl -u clickhouse-server1
journalctl -u clickhouse-server

**Comment by taylor131415** [comment]
Hello Den,
The info you requiredas below:
[root@localhost init.d]# journalctl -u clickhouse-server
-- Logs begin at Fri 2020-11-20 19:30:27 CST, end at Sun 2020-11-22 11:20:01 CST. --
Nov 20 19:30:37 localhost.localdomain systemd[1]: Started ClickHouse Server (analytic DBMS for big data).
Nov 20 19:30:37 localhost.localdomain systemd[1]: Starting ClickHouse Server (analytic DBMS for big data)...
Nov 20 19:30:42 localhost.localdomain clickhouse-server[1444]: Processing configuration file '/etc/clickhouse-server/config.xml'.
Nov 20 19:30:42 localhost.localdomain clickhouse-server[1444]: Including configuration file '/etc/clickhouse-server/metrika.xml'.
Nov 20 19:30:42 localhost.localdomain clickhouse-server[1444]: Logging trace to /var/log/clickhouse-server/clickhouse-server.log
Nov 20 19:30:42 localhost.localdomain clickhouse-server[1444]: Logging errors to /var/log/clickhouse-server/clickhouse-server.err.l
Nov 20 19:30:52 localhost.localdomain clickhouse-server[1444]: Processing configuration file '/etc/clickhouse-server/users.xml'.
Nov 20 19:30:52 localhost.localdomain clickhouse-server[1444]: Including configuration file '/etc/metrika.xml'.
Nov 20 19:30:52 localhost.localdomain clickhouse-server[1444]: Saved preprocessed configuration to '/var/lib/clickhouse/preprocesse
Nov 20 19:30:53 localhost.localdomain clickhouse-server[1444]: libunwind: Unsupported .eh_frame_hdr version

[root@localhost init.d]# journalctl -u clickhouse-server1
-- Logs begin at Fri 2020-11-20 19:30:27 CST, end at Sun 2020-11-22 11:20:01 CST. --
Nov 20 19:31:39 localhost.localdomain systemd[1]: Starting LSB: Yandex clickhouse-server daemon...
Nov 20 19:31:39 localhost.localdomain clickhouse-server1[4627]: Init script is already running
Nov 20 19:31:39 localhost.localdomain systemd[1]: Started LSB: Yandex clickhouse-server daemon.
Nov 20 19:39:14 localhost.localdomain systemd[1]: Stopping LSB: Yandex clickhouse-server daemon...
Nov 20 19:39:14 localhost.localdomain clickhouse-server1[9034]: Init script is already running
Nov 20 19:39:14 localhost.localdomain systemd[1]: Starting LSB: Yandex clickhouse-server daemon...
Nov 20 19:39:14 localhost.localdomain clickhouse-server1[9067]: Init script is already running
Nov 20 19:39:14 localhost.localdomain systemd[1]: Started LSB: Yandex clickhouse-server daemon.
Nov 20 19:39:26 localhost.localdomain systemd[1]: Stopping LSB: Yandex clickhouse-server daemon...
Nov 20 19:39:26 localhost.localdomain clickhouse-server1[10133]: Init script is already running
Nov 20 19:39:26 localhost.localdomain systemd[1]: Starting LSB: Yandex clickhouse-server daemon...
Nov 20 19:39:26 localhost.localdomain clickhouse-server1[10163]: Init script is already running
Nov 20 19:39:26 localhost.localdomain systemd[1]: Started LSB: Yandex clickhouse-server daemon.

Obviously service 'clickhouse-server' can work and 'clickhouse-server1' can't load. By the way, the error info： "Init script is already running" I have met before,this info appeared because I use command "service clickhouse-server start" like this：
![service_clickhouse-server_start](https://user-images.githubusercontent.com/74707266/99893314-5e717d80-2cb9-11eb-92eb-52b1d74b7367.png)
When i changed command  to "systemctl start clickhouse-server", the service clickhouse-server can load successfully. But now, whatever I used command systemctl or service clickhouse-server1 start, service clickhouse-server1 can't load, I'm so confused and I distrust maybe it's not config files' problem. I'm looking forward to hearing from you, thanks so much.

**Comment by taylor131415** [comment]
> please show
> journalctl -u clickhouse-server1
> journalctl -u clickhouse-server

Hello Den,
The info you required as below:
[root@localhost init.d]# journalctl -u clickhouse-server
-- Logs begin at Fri 2020-11-20 19:30:27 CST, end at Sun 2020-11-22 11:20:01 CST. --
Nov 20 19:30:37 localhost.localdomain systemd[1]: Started ClickHouse Server (analytic DBMS for big data).
Nov 20 19:30:37 localhost.localdomain systemd[1]: Starting ClickHouse Server (analytic DBMS for big data)...
Nov 20 19:30:42 localhost.localdomain clickhouse-server[1444]: Processing configuration file '/etc/clickhouse-server/config.xml'.
Nov 20 19:30:42 localhost.localdomain clickhouse-server[1444]: Including configuration file '/etc/clickhouse-server/metrika.xml'.
Nov 20 19:30:42 localhost.localdomain clickhouse-server[1444]: Logging trace to /var/log/clickhouse-server/clickhouse-server.log
Nov 20 19:30:42 localhost.localdomain clickhouse-server[1444]: Logging errors to /var/log/clickhouse-server/clickhouse-server.err.l
Nov 20 19:30:52 localhost.localdomain clickhouse-server[1444]: Processing configuration file '/etc/clickhouse-server/users.xml'.
Nov 20 19:30:52 localhost.localdomain clickhouse-server[1444]: Including configuration file '/etc/metrika.xml'.
Nov 20 19:30:52 localhost.localdomain clickhouse-server[1444]: Saved preprocessed configuration to '/var/lib/clickhouse/preprocesse
Nov 20 19:30:53 localhost.localdomain clickhouse-server[1444]: libunwind: Unsupported .eh_frame_hdr version

[root@localhost init.d]# journalctl -u clickhouse-server1
-- Logs begin at Fri 2020-11-20 19:30:27 CST, end at Sun 2020-11-22 11:20:01 CST. --
Nov 20 19:31:39 localhost.localdomain systemd[1]: Starting LSB: Yandex clickhouse-server daemon...
Nov 20 19:31:39 localhost.localdomain clickhouse-server1[4627]: Init script is already running
Nov 20 19:31:39 localhost.localdomain systemd[1]: Started LSB: Yandex clickhouse-server daemon.
Nov 20 19:39:14 localhost.localdomain systemd[1]: Stopping LSB: Yandex clickhouse-server daemon...
Nov 20 19:39:14 localhost.localdomain clickhouse-server1[9034]: Init script is already running
Nov 20 19:39:14 localhost.localdomain systemd[1]: Starting LSB: Yandex clickhouse-server daemon...
Nov 20 19:39:14 localhost.localdomain clickhouse-server1[9067]: Init script is already running
Nov 20 19:39:14 localhost.localdomain systemd[1]: Started LSB: Yandex clickhouse-server daemon.
Nov 20 19:39:26 localhost.localdomain systemd[1]: Stopping LSB: Yandex clickhouse-server daemon...
Nov 20 19:39:26 localhost.localdomain clickhouse-server1[10133]: Init script is already running
Nov 20 19:39:26 localhost.localdomain systemd[1]: Starting LSB: Yandex clickhouse-server daemon...
Nov 20 19:39:26 localhost.localdomain clickhouse-server1[10163]: Init script is already running
Nov 20 19:39:26 localhost.localdomain systemd[1]: Started LSB: Yandex clickhouse-server daemon.

Obviously service 'clickhouse-server' can work and 'clickhouse-server1' can't load. By the way, the error info： "Init script is already running" I have met before,this info appeared because I use command "service clickhouse-server start" like this：
![systemctl](https://user-images.githubusercontent.com/74707266/100034029-470bcf00-2e36-11eb-9d65-5963e28853f0.png)

When I changed command to "systemctl start clickhouse-server", the service clickhouse-server can load successfully. But now, whatever I used command systemctl or service clickhouse-server1 start, service clickhouse-server1 can't load,I distruct maybe it's not config files' problem. I'm looking forward to hearing from you, thanks so much.

**Comment by den-crane** [comment]
check errors in /var/log/clickhouse-server1/stderr.log

**Comment by taylor131415** [comment]
> 检查/var/log/clickhouse-server1/stderr.log中的错误

There's no error log produced in this path. Seems like the service exited as soon as it starts.

**Comment by den-crane** [comment]
show the output of 

sudo -u clickhouse clickhouse-server --pid-file=/var/run/clickhouse-server1/clickhouse-server.pid --config-file=/etc/clickhouse-server1/config.xml

**Comment by taylor131415** [comment]
> show the output of
> 
> sudo -u clickhouse clickhouse-server --pid-file=/var/run/clickhouse-server1/clickhouse-server.pid --config-file=/etc/clickhouse-server1/config.xml

Required info as below:
[root@localhost ~]# sudo -u clickhouse clickhouse-server --pid-file=/var/run/clickhouse-server/clickhouse-server-1.pid --config-file=/etc/clickhouse-server1/config1.xml
Processing configuration file '/etc/clickhouse-server1/config1.xml'.
libunwind: Unsupported .eh_frame_hdr version
Poco::Exception. Code: 1000, e.code() = 13, e.displayText() = Access to file denied: /etc/clickhouse-server1/config1.xml, Stack trace (when copying this message, always include the lines below):
0. Poco::FileImpl::handleLastErrorImpl(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x10b61ba6 in /usr/lib/debug/usr/bin/clickhouse
1. Poco::FileStreamBuf::open(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned int) @ 0x10b7216c in /usr/lib/debug/usr/bin/clickhouse
2. Poco::FileInputStream::FileInputStream(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned int) @ 0x10b72c68 in /usr/lib/debug/usr/bin/clickhouse
3. Poco::FileStreamFactory::open(Poco::Path const&) @ 0x10bd2187 in /usr/lib/debug/usr/bin/clickhouse
4. Poco::URIStreamOpener::open(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const @ 0x10bd0c1e in /usr/lib/debug/usr/bin/clickhouse
5. Poco::XML::EntityResolverImpl::resolveEntity(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x10afc37b in /usr/lib/debug/usr/bin/clickhouse
6. Poco::XML::SAXParser::parse(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x10af06a8 in /usr/lib/debug/usr/bin/clickhouse
7. Poco::XML::DOMBuilder::parse(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x10ad4361 in /usr/lib/debug/usr/bin/clickhouse
8. Poco::XML::DOMParser::parse(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x10ad2f6d in /usr/lib/debug/usr/bin/clickhouse
9. DB::ConfigProcessor::processConfig(bool*, zkutil::ZooKeeperNodeCache*, std::__1::shared_ptr<Poco::Event> const&) @ 0xe598ead in /usr/lib/debug/usr/bin/clickhouse
10. DB::ConfigProcessor::loadConfig(bool) @ 0xe59f934 in /usr/lib/debug/usr/bin/clickhouse
11. BaseDaemon::reloadConfiguration() @ 0x7cae691 in /usr/lib/debug/usr/bin/clickhouse
12. BaseDaemon::initialize(Poco::Util::Application&) @ 0x7cb08d5 in /usr/lib/debug/usr/bin/clickhouse
13. DB::Server::initialize(Poco::Util::Application&) @ 0x7b84b30 in /usr/lib/debug/usr/bin/clickhouse
14. Poco::Util::Application::run() @ 0x10aab0d6 in /usr/lib/debug/usr/bin/clickhouse
15. DB::Server::run() @ 0x7b8498f in /usr/lib/debug/usr/bin/clickhouse
16. mainEntryClickHouseServer(int, char**) @ 0x7b8430b in /usr/lib/debug/usr/bin/clickhouse
17. main @ 0x7b27cbd in /usr/lib/debug/usr/bin/clickhouse
18. __libc_start_main @ 0x22555 in /usr/lib64/libc-2.17.so
19. _start @ 0x7ad802e in /usr/lib/debug/usr/bin/clickhouse
 (version 20.11.3.3 (official build))

By the way, the service clickhouse-server1 didn't produce the corresponding pid file：/var/run/clickhouse-server/clickhouse-server-1.pid when the service started.

**Comment by den-crane** [comment]
```
chown -R clickhouse.clickhouse  /etc/clickhouse-server1/
```
and again 

sudo -u clickhouse clickhouse-server --pid-file=/var/run/clickhouse-server/clickhouse-server-1.pid --config-file=/etc/clickhouse-server1/config1.xml

**Comment by taylor131415** [comment]
> ```
> chown -R clickhouse.clickhouse  /etc/clickhouse-server1/
> ```
> 
> and again
> 
> sudo -u clickhouse clickhouse-server --pid-file=/var/run/clickhouse-server/clickhouse-server-1.pid --config-file=/etc/clickhouse-server1/config1.xml

OMG, thank you so so so much, this time after executing this command：'sudo -u clickhouse clickhouse-server --pid-file=/var/run/clickhouse-server/clickhouse-server-1.pid --config-file=/etc/clickhouse-server1/config1.xml', the service clickhouse-server1 can work successfully with the new listen_ports and the corresponding logs and pid file appeared. But when I use command：systemctl start clickhouse-server1, the service still couldn't load, info still shows: Init script is already running.

**Comment by den-crane** [comment]
>when I use command：systemctl start clickhouse-server1, 
>the service still couldn't load, info still shows: Init script is already running.

You  need to stop using " service clickhouse stop / start " , " /etc/init.d/cl ...." and switch to systemctl commands only.

make a copy of `/etc/systemd/system/clickhouse-server.service `
`cp /etc/systemd/system/clickhouse-server.service /etc/systemd/system/clickhouse-server1.service` and edit accordingly.
Stop all CH , check that 'ps -ef' does not show any CH services and start to use `systemctl stop/start` only.

**Comment by taylor131415** [comment]
> > 当我使用命令：systemctl start clickhouse-server1时，
> > 该服务仍然无法加载，信息仍然显示：初始化脚本已在运行。
> 
> 您需要停止使用“ service clickhouse stop / start”，“ /etc/init.d/cl ....”，并仅切换到systemctl命令。
> 
> 复制`/etc/systemd/system/clickhouse-server.service `
> `cp /etc/systemd/system/clickhouse-server.service /etc/systemd/system/clickhouse-server1.service`并进行相应的编辑。
> 停止所有CH，检查'ps -ef'没有显示任何CH服务，`systemctl stop/start`仅开始使用。

Services can work now, wanna say thank you so much again.
