### ISSUE TITLE
ClickHouse use getaddrinfo for reverse resolve and apply only one PTR response value for <host_regexp> compare

### ISSUE THREAD

**Issue by Slach** [ClickHouse/ClickHouse#17202]
**Describe the bug**
ClickHouse use getaddrinfo for reverse resolve https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/DNSResolver.cpp#L124

DNS protocol doesn't restrict how much PTR records we shall set for one IP address
https://en.wikipedia.org/wiki/Reverse_DNS_lookup#Multiple_pointer_records

so, when we receive multiple PTR response value
only one PTR response value apply for <host_regexp> recognition

![image](https://user-images.githubusercontent.com/105560/99423942-eb67b000-2922-11eb-912a-d354a6e5e703.png)

**How to reproduce**
I create a `docker-compose` reproducible environment
https://gist.github.com/Slach/f9e40984168840d9c95da03988ab8283
just run ./reproduce.sh 

* Which ClickHouse server version to use
official docker `clickhouse-server:latest`

**Expected behavior**
All PTR response shall match with `host_regexp` pattern

**Error message and/or stacktrace**
```
Code: 516, e.displayText() = DB::Exception: test_dns: Authentication failed: password is incorrect or there is no user with such name (version 20.1'.3.3 (official build)
```

**Comment by czhfe** [comment]
I'm running clickhouse here in a kubernetes environment and use `host_regexp` also often encounter distributed query errors. What would be an effective way to deal with this issue.
