### ISSUE TITLE
Unable to retrieving Clickhouse schema in Talend

### ISSUE THREAD

**Issue by bilalbilalsheikh** [ClickHouse/ClickHouse#17216]
I am trying to import a Clickhouse schema in Talend Open Studio ETL software. The steps that I have followed are:

I created a connection in Talend Open Studio with ClickHouse using the credentials shown below in screenshot 1. 
In the mapping file option, There is no default file for Clickhouse. That's why I have tried both the Java or Mysql database mapping file and I can create a successful connection with both.

While importing schema, the menu shows me the "default" catalog. When I expand it, it lists all the schemas in it. When I select a schema to import, It keeps on retrieving the "Next" button remains disabled as shown in the image below 
![Capture](https://user-images.githubusercontent.com/58861035/99764542-19b1df00-2b1f-11eb-831e-e0a181d1ff75.PNG):

**Comment by den-crane** [comment]
We don't support Talend. Ask their side.
