### ISSUE TITLE
strange S3 error when using s3 function!

### ISSUE THREAD

**Issue by shawel** [ClickHouse/ClickHouse#17212]
I am getting an error during the following query

`insert into TABLE FUNCTION s3('https://s3.us-east-1.amazonaws.com/<bucketname>/<id>/2020/11/19/test.1605820932981.csv',AWS_KEY,AWS_SECRET_KEY, CSV, ' uid String , price Float32 ') SELECT id, price FROM ...`

the error below 
exception:                     Code: 499, e.displayText() = DB::Exception: <Error><Code>InvalidRequest</Code><Message>You must specify at least one part</Message><RequestId>C81771FD1BEAB818</RequestId><HostId>lEvcHBlaMG2LD4c5x+Ku6Gk5OyjdIIMC9gn4FWTJ0ohK3C/pHsuMeiR6m4ayKGTx1RReb0c9jP0=</HostId></Error> (version 20.11.3.3 (official build))
<img width="1374" alt="Screen Shot 2020-11-19 at 5 27 00 PM" src="https://user-images.githubusercontent.com/625370/99731842-7c0dcf80-2a8c-11eb-9d5e-88a623d2af95.png">

I have had this work before. What is the scenario where this error presents?

**Comment by Jokser** [comment]
It means that your sub-select `SELECT id, price FROM ...` returned no data.
This behaviour was fixed there https://github.com/ClickHouse/ClickHouse/pull/16840

**Comment by shawel** [comment]
Ok thanks @Jokser!
