### ISSUE TITLE
How to Contribute to ClickHouse code?

### ISSUE THREAD

**Issue by trollhe** [ClickHouse/ClickHouse#17217]
Hi,

We have some supplementary code. How can we contribute to the Clickhouse? At present, we choose to use Clickhouse as our Pb level data analysis tool, hoping to make some contributions in the future.

**Comment by filimonov** [comment]
Hi @trollhe 

To check how it works you can try to add some test:
* https://clickhouse.tech/docs/en/development/adding_test_queries/

Some basic info about development is https://clickhouse.tech/docs/en/development/adding_test_queries/

And you can look for some easy tasks - to play with clickhouse code a bit.
https://github.com/ClickHouse/ClickHouse/issues?page=2&q=is%3Aopen+is%3Aissue+label%3A%22easy+task%22
https://github.com/ClickHouse/ClickHouse/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

**Comment by filimonov** [comment]
We don't have any mailing lists for devs, so main communication channel is github issues. 
If you want to work on something / want to discuss something you can open new issue or put a comment in one of existing. 

We also have telegram group, if you will start asking dev-related questions most probabably smbd will be able to pick a question and answer it.

**Comment by trollhe** [comment]
> We don't have any mailing lists for devs, so main communication channel is github issues.
> If you want to work on something / want to discuss something you can open new issue or put a comment in one of existing.
> 
> We also have telegram group, if you will start asking dev-related questions most probabably smbd will be able to pick a question and answer it.

thank u,that`s great.
