### ISSUE TITLE
"Precompiled Binaries for Non-Standard Environments" download links are dead

### ISSUE THREAD

**Issue by athre0z** [ClickHouse/ClickHouse#17229]
All download links in the "[Precompiled Binaries for Non-Standard Environments](https://clickhouse.tech/docs/en/getting-started/install/#from-binaries-non-linux)" section of the documentation are currently dead and result in a 404.

**Comment by alesapin** [comment]
Fixed

**Comment by athre0z** [comment]
That was quick, thanks! :)
