### ISSUE TITLE
Lots of Segmentation Faults inside docker

### ISSUE THREAD

**Issue by henk23** [ClickHouse/ClickHouse#17222]
**Describe the bug**
When run inside docker, ClickHouse server crashes at seemingly random intervals, with many varying error stacks.

**How to reproduce**
* Running Ubuntu 18.04.5 LTS on a virtual server with root access. Docker version 19.03.13, build 4484c46d9d.
* Using `yandex/clickhouse-server:latest` from docker hub (Version 20.11.3.3)
* Docker has all 8G memory available. At any given time `free -h` says 7.5G are free.

* It comes bundled with Plausible Analytics, see this file: https://github.com/plausible/hosting/blob/master/docker-compose.yml
* Default settings, I just added a `restart: always` to docker-compose, because I need ClickHouse running.

**Expected behavior**
ClickHouse runs without crashing.

**Error message and/or stacktrace**
See attached [err.log](https://github.com/ClickHouse/ClickHouse/files/5572795/err.log). (I removed some unrelated ipv6 warnings to make the file shorter.)

**Additional context**
I am pretty sure that the issue is not coming from Plausible's code or broken queries sent to ClickHouse, given the variety of the error stacks. It might have to do something with my configuration of a) Ubuntu, b) Docker, c) ClickHouse.
Since one of the many errors is `Syntax error: failed at position 1 ('RELECT')` (Nowhere in the codebase is there a "RELECT" query...) I guess that something really strange is going on.
Hope someone can help.

**Comment by filimonov** [comment]
Every segfault report has query id.

Please grep /var/log/clickhouse-server/clickhouse-server.log for a several queries. 

I.e.
```
grep 'de75e31d-a7c1-45ee-9477-db2c7ed0537f' /var/log/clickhouse-server/clickhouse-server.log
```

**Comment by henk23** [comment]
Sorry, there is no additional info to any of the query ids. Could be because I set the log level to "warning" (trying to limit I/O of the process to fix the bug.)

Also, my suspicion is that it's not related to the queries, because the error happens so randomly.

**Comment by den-crane** [comment]
I think you container has been killed by a host system. 
Can you show `dmesg -T |grep -i oom-killer` and `grep "Killed process" /var/log/syslog`

**Comment by henk23** [comment]
Both are empty. `dmesg` only has a few entries for UFW blocks. Nothing in `syslog` about killed processes.
Also nothing suspicious in `journalctl -u docker`

**Comment by den-crane** [comment]
can you show the output of
`select name ,value from system.settings where changed`

**Comment by den-crane** [comment]
And try to upgrade. v20.11.4.13-stable just released.

**Comment by alexey-milovidov** [comment]
> Since one of the many errors is Syntax error: failed at position 1 ('RELECT') (Nowhere in the codebase is there a "RELECT" query...) I guess that something really strange is going on.

It looks like a bitflip due to broken RAM module.

**Comment by alexey-milovidov** [comment]
You can migrate to another server and check if the issue will remain.

**Comment by henk23** [comment]
@alexey-milovidov This is probably it. I just realized that my hosting provider uses Virtuozzo for the virtual machines. Checking out `/proc/user_beancounters` shows me a limit of 386 max numproc ("processes and kernel-level threads") which is completely exhausted. (Thanks to [this answer](https://serverfault.com/a/1018402))

That explains the killed processes, all the other problems probably come from that.

As far as I'm concerned this issue can be closed. :) Thanks for your support!
