### ISSUE TITLE
ReplacingMergeTree ver column is not affected

### ISSUE THREAD

**Issue by vhbien000** [ClickHouse/ClickHouse#17221]
This is my table's create script 
```
	CREATE TABLE IF NOT EXISTS replacing_test (
		addr				String,
		ver				UInt64,
                 stt                             String,
		time				DateTime,
	) engine=ReplacingMergeTree(ver)
	PARTITION BY toYYYYMM(time)
	PRIMARY KEY addr
	ORDER BY addr
```

I have 2 rows as follows:
```
ABC | 0 | NEW | 2020-04-17 12:39:52 
ABC | 2 | DONE | 2020-04-17 12:40:52 
```
When I insert 2 rows above in separate times, with the order like above, after merging, I got:
```ABC | 2| DONE | 2020-04-17 12:40:52 ```
It also my expectation.

But, when I try to insert these 2 rows at the same time by reading from backup, with random order, the result will be:
```ABC | 0| DONE | 2020-04-17 12:39:52 ```

Is there any behavior that I don't know about here?

**Comment by den-crane** [comment]
What do you mean by "at the same time by reading from backup"?

**Comment by vhbien000** [comment]
I am using clickhouse in my consensus network, data records are streamed from the network to the server with clickhouse DB (C). The issue occurs when I reload (C) by streaming everything from the first record again.

**Comment by vhbien000** [comment]
When the (C) syncs with network and real-time, merging is right. But when reload and wait for syncing with the network, the merged result of the existed record is wrong.

**Comment by den-crane** [comment]
Do you have exact steps to reproduce? create table  / insert / select ?

>I am using clickhouse in my consensus network, data records are streamed from the network 
>to the server with clickhouse DB (C). The issue occurs when I reload (C) by streaming everything 
>from the first record again.

>When the (C) syncs with network and real-time, merging is right. 
>But when reload and wait for syncing with the network, the merged result of the existed record is wrong.

What stands for "reload (C)" ?

**Comment by vhbien000** [comment]
Yes, I do exactly the mentioned steps. Reload (C) means: drop all old tables  => create new tables => stream all record from network to the server and insert into clickhouse.

**Comment by vhbien000** [comment]
I will show you a few images.

**Comment by vhbien000** [comment]
I use 2 table, (1) to store stream history, (2) to store merged info.

(1) 
![image](https://user-images.githubusercontent.com/32956772/99908075-f51e5880-2d12-11eb-8ea3-56b1b397b77c.png)

(2)
![image](https://user-images.githubusercontent.com/32956772/99908102-26972400-2d13-11eb-845b-4745c803cb4a.png)

as you see `I7Y22GK` is duplicated in (1), so (2) should show the maximum version `11495326` instead of `11495259`

The expectation of (2) should be following.

![image](https://user-images.githubusercontent.com/32956772/99908167-a02f1200-2d13-11eb-8e5c-145a84aa91a6.png)

 It is also the result of the DB when real-time synced with the network (before the reload occurs).

**Comment by vhbien000** [comment]
I know it is hard to image out without my source code. But I hope the miracle happens. Will close this issue if anybody have no idea.

**Comment by vhbien000** [comment]
🔒  closed

**Comment by vhbien000** [comment]
Thank you @den-crane, don't pay attention on this issue, should be my mistake in my setting.
