### ISSUE TITLE
change privileges in users.xml

### ISSUE THREAD

**Issue by AndrewNik** [ClickHouse/ClickHouse#17236]
Hello)
Please answer, how can i change privileges for user, who was created in users.xml? Revoke and grand don't change anything, I just recive an exception: 

```
Received exception from server (version 20.11.3):
Code: 495. DB::Exception: Received from localhost:9000. DB::Exception: Cannot update user `test` in users.xml because this storage is readonly: Couldn't update user `test`. Successfully updated: none. 
```

I have already changed permissions for this file - nothing changes. For example, I want to create user. who can only insert into one table and select from any tables. Is it possible?

**Comment by den-crane** [comment]
You need to RBAC / access_management / create user. 

```sql
create user xxx identified with sha256_password by 'xxx';
grant insert on db.sometable to xxx;
```

https://clickhouse.tech/docs/en/operations/settings/settings-users/#access_management-user-setting
https://clickhouse.tech/docs/en/operations/access-rights/#access-control

**Comment by xinstein** [comment]
I encountered the exact same problem, how have you resolved this? @AndrewNik

**Comment by AndrewNik** [comment]
@xinstein Nope, I had to create user by sql commands. It's not the most user-friendly way, but it is only thing I've found

**Comment by den-crane** [comment]
>It's not the most user-friendly way

??
It was thousands requests to implement user management using SQL in CH. 
Now you can consider XML user management as obsolete.

**Comment by egorbl4** [comment]
@den-crane But is the way ( to grant priveleges to user created by users.xml ) exist ?
