### ISSUE TITLE
Easy way to backfill a Summing/AggregatingMergeTree materialized view

### ISSUE THREAD

**Issue by mzealey** [ClickHouse/ClickHouse#17239]
**Use case**

We create a table using `SummingMergeTree` or `AggregatingMergeTree` and create a materialized view to insert data. This works fine for the live data but we would like to insert old data into it as well.

Obviously we can just do `INSERT INTO ... SELECT ...` for this; however on larger groupings we hit the memory limits, and because these tables are Aggregating it shouldn't actually matter as to whether it is 1 big query or chunked into smaller ones.

Currently the only solution that I know of is to write a script which basically does the `INSERT INTO ... SELECT ...` method but chunking the input table into batches of say 50m records to avoid hitting the memory limits.

But it would be great if there was some way that clickhouse would know 'this underlying table is aggregating' and figure out the chunking internally, allowing us to just run a single INSERT SELECT command to backfill the table.

**Comment by den-crane** [comment]
As temporary WA https://gist.github.com/den-crane/f7382cd4f1f859ff6ac46afe7dc9925a (Populate AggregatingMergeTree through null table )

**Comment by den-crane** [comment]
https://t.me/c/1425947904/8205


https://github.com/ClickHouse/ClickHouse/pull/11593
https://github.com/ClickHouse/ClickHouse/pull/11661

**Comment by mzealey** [comment]
Ah great idea. So as a quick note for anyone else, you can do:

```
  create table if not exists null_xxx ENGINE=Null AS SELECT * FROM xxx LIMIT 1;
```

then clone the mat views to read from `null_xxx`.

Then

```
    set max_insert_threads=8; insert into null_xxx select * from xxx;
```

**Comment by zamoosh** [comment]
Thanks, this just works and is blazingly fast!🙏
@den-crane
