### ISSUE TITLE
What are the Kafka versions supported by the Kafka engine used by the 20.8.7.15 version of Clickhouse?

### ISSUE THREAD

**Issue by gubinjie** [ClickHouse/ClickHouse#17247]
What are the Kafka versions supported by the Kafka engine used by the 20.8.7.15 version of Clickhouse?

**Comment by filimonov** [comment]
TL;DR. Any recent. 

We use librdkafka 1.5 to access kafka.  See compatibility notes in their docs: https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md#compatibility
