### ISSUE TITLE
A function to escape charaters for HTML and XML.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#17250]
`encodeXMLComponent`
`decodeXMLComponent`

(similar to `encodeURLComponent`, `decodeURLComponent`)

Should replace characters like `<`, `&` and `"`, `'` to the corresponding entities.

Question:
- is there a difference between HTML and XML in the set of characters needed to be encoded?
- is it legal to replace zero byte to `&#0;`? If not we will keep it as is.

Additional info:
- we will assume UTF-8 but not check the validity of sequences (leave invalid UTF-8 as is);

**Comment by alexey-milovidov** [comment]
See also: `WriteHelpers.h`, `writeXMLString`.

**Comment by nautaa** [comment]
hello,i want to complete encodeXMLComponent and decodeXMLComponent. Are they a function format similar to function writeXMLString() in WriteHelpers.h? Put the string escape result into the writerbuffer?

**Comment by alexey-milovidov** [comment]
@nautaa Yes, it will be very helpful! Implementation will be similar to `writeXMLString` but with more characters to encode, because we will encode not only for text elements but also for attributes, so we need to encode `"` and `'`.
