### ISSUE TITLE
Support deduplication for partial data(order by key, or any other setting)

### ISSUE THREAD

**Issue by itzikiusa** [ClickHouse/ClickHouse#17251]
Hi, i would like to have the option to 'define' how deduplication will happen
currently when using Replicated*MergeTree duplicate inserts are being ignored, where all columns already exists in table, maybe we can configure it to validate only partial data? or ignore?

currently if we want to secure single occurrence of primary key, then we need to use 'FINAL' which slows queries
if we can ensure deduplication upon insert(don't think it will be slower from current validation), then it will be great

also, if there is a way to ensure deduplication in ReplacingMergeTree it will be great, currently it is not supported as far as i can see:
`SELECT * FROM system.table_engines WHERE name LIKE 'Replacing%'` 
supports_deduplication -> 0

use cases:
1. would like primary key will appear only once
2. would like to allow duplicates(without adding some UUID column)

example:
`create table replica.duplicates (id String, value String) ENGINE = ReplicatedReplacingMergeTree('/replica/duplicates', 'duplcate_1') PARTITION BY id ORDER BY id SETTINGS index_granularity = 8192`

`insert into replica.duplicates (id, value) VALUES('1', '1')`
`insert into replica.duplicates (id, value) VALUES('1', '1')`
`insert into replica.duplicates (id, value) VALUES('1', '2')`
`insert into replica.duplicates (id, value) VALUES('1', '3')`
`insert into replica.duplicates (id, value) VALUES('1', '4')`
`insert into replica.duplicates (id, value) VALUES('1', '1')`

```
current behavior:
select * from replica.duplicates
┌─id─┬─value─┐
│ 1  │ 1     │
│ 1  │ 2     │
│ 1  │ 3     │
│ 1  │ 4     │
└────┴───────┘
expected behavior:
select * from replica.duplicates
┌─id─┬─value─┐
│ 1  │ 1     │
└────┴───────┘

**Comment by den-crane** [comment]
>if we can ensure deduplication upon insert(don't think it will be slower from current validation), then it will be great

It's impossible with MT.
