### ISSUE TITLE
[Question] Distributed tables that look at other Distributed tables

### ISSUE THREAD

**Issue by badvir** [ClickHouse/ClickHouse#1726]
Hi.

Global_Master's distributed table is configured to look at the other two distributed table.
In Global_Master, select query on the distributed table seems to work fine.
It is said that it is not supported in the manual.
Please let me know what the problem is.

version : 1.1.54310

![image](https://user-images.githubusercontent.com/13232284/34596738-847b847a-f225-11e7-8a63-061ea4208819.png)

**Comment by badvir** [comment]
My log data is inserting to each log table 

- select xxx,xxx,xxx,xx from distributed table : Fine!
**- select count() from distributed table : Error!**



2018.01.05 14:56:02.091022 [ 31 ] <Error> executeQuery: Code: 368, e.displayText() = DB::Exception: Bad cast from type N2DB12ColumnVectorImEE to N2DB23ColumnAggregateFunctionE, e.what() = DB::Excep
tion (from [::1]:43414) (in query: select count() from traffic), Stack trace:

0. clickhouse-server(StackTrace::StackTrace()+0x16) [0x2dacdf6]
1. clickhouse-server(DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)+0x1f) [0x13d1e6f]
2. clickhouse-server(std::enable_if<std::is_reference<DB::ColumnAggregateFunction&>::value, DB::ColumnAggregateFunction&>::type typeid_cast<DB::ColumnAggregateFunction&, DB::IColumn>(DB::IColumn&)+
0xda) [0x2789eaa]
3. clickhouse-server(DB::Aggregator::mergeWithoutKeyStreamsImpl(DB::Block&, DB::AggregatedDataVariants&) const+0x58) [0x30f9d18]
4. clickhouse-server(DB::Aggregator::mergeStream(std::shared_ptr<DB::IBlockInputStream> const&, DB::AggregatedDataVariants&, unsigned long)+0xb4b) [0x3103c3b]
5. clickhouse-server(DB::MergingAggregatedBlockInputStream::readImpl()+0x382) [0x3082922]
6. clickhouse-server(DB::IProfilingBlockInputStream::read()+0x1ae) [0x2775e4e]
7. clickhouse-server(DB::ExpressionBlockInputStream::readImpl()+0x1a) [0x3059e4a]
8. clickhouse-server(DB::IProfilingBlockInputStream::read()+0x1ae) [0x2775e4e]
9. clickhouse-server(DB::ExpressionBlockInputStream::readImpl()+0x1a) [0x3059e4a]
10. clickhouse-server(DB::IProfilingBlockInputStream::read()+0x1ae) [0x2775e4e]
11. clickhouse-server(DB::AsynchronousBlockInputStream::calculate(MemoryTracker*)+0x7e) [0x13e0aee]
12. clickhouse-server(ThreadPool::worker()+0x148) [0x3264408]
13. clickhouse-server() [0x35a8fdf]
14. /lib64/libpthread.so.0(+0x76ca) [0x7f7ea5e916ca]
15. /lib64/libc.so.6(clone+0x5f) [0x7f7ea3202f6f]


**Is there a way to solve it?**

**Comment by blinkov** [comment]
@badvir, do you have any further questions?

**Comment by filimonov** [comment]
https://github.com/ClickHouse/ClickHouse/pull/9923

**Comment by azat** [comment]
>In Global_Master, select query on the distributed table seems to work fine.

Looks like your nested distributed table has only one shard (not sure completely about your structure though) and in this case it should work (even before #9923)
