### ISSUE TITLE
Implement JWT for ClickHouse

### ISSUE THREAD

**Issue by jindal-git** [ClickHouse/ClickHouse#17270]
**Use case**
We have multiple end users making queries to CH through API server. API server is connected to CH using its own user. We would like to send end user credentials per query to CH, so CH can verify that the user is indeed allowed to access the database. We currently do this validation in the API server, but it would be more robust if CH validated it again.

**Describe the solution you'd like**
I don't have much experience with CH yet, but thought of one possible solution: 
1. send JWT using query settings
2. CH will decode JWT and validate that the current database specified in the context is allowed.

This might be a very narrow use case, but I would to hear thoughts on usefulness of this feature or other ways to do this.

**Comment by ahmed-adly-khalil** [comment]
maybe CH can use federated auth to send the JWT to a configured 3rd party which will validate the JWT, similar to NATS decentralized auth https://docs.nats.io/running-a-nats-service/configuration/securing_nats/auth_intro/jwt

**Comment by tanleach** [comment]
This would be really useful for NATs authentication as well!

**Comment by maniak89** [comment]
Follow
