### ISSUE TITLE
Last in the selection ReplacingMergeTree.

### ISSUE THREAD

**Issue by vladimirteddy** [ClickHouse/ClickHouse#17282]
I use ReplacingMergeTree, after a while old data versions lose. I want to ask how to configure that time? And I want to configure ReplacingMergeTree every time I push data to save only the latest version?

**Comment by filimonov** [comment]
No way for that. If you need to preserve all versions of your data row - use plain MergeTree (may be with some TTL expression), and argMax aggregate functions go access last values (or create materialized view to access last values using Replacing / Aggregating)

**Comment by vladimirteddy** [comment]
Thank you @filimonov .
