### ISSUE TITLE
Add security advice for self-hosted ClickHouse instances.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#17320]
Near [Usage Recommendations](https://clickhouse.tech/docs/en/operations/tips/).

**Comment by DanRoscigno** [comment]
Thoughts:
Use https://clickhouse.com/docs/en/cloud/security/security-companion-guide as a guide; the things we do for the Cloud customers can be replicated by the self-managed community using things like firewalld, SHA256_hash, etc.

https://clickhouse.com/docs/en/guides/sre/configuring-ssl

quotas
