### ISSUE TITLE
build  clickhouse on readhat7 error

### ISSUE THREAD

**Issue by miaojianxin** [ClickHouse/ClickHouse#17349]
i check out the code
git clone --recursive https://github.com/yandex/ClickHouse.git
cd Clickhouse
git checkout v20.8.6.6-lts
and when i compile  this step
mkdir build
cd build
cmake ../

the error occered like this:

CMake Error at contrib/grpc-cmake/CMakeLists.txt:555 (add_library):
  Cannot find source file:

    /root/ClickHouse/contrib/grpc/src/core/lib/json/json.cc

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx

CMake Error at contrib/grpc-cmake/CMakeLists.txt:964 (add_library):
  Cannot find source file:

    /root/ClickHouse/contrib/grpc/src/cpp/client/generic_stub.cc

 thanks

**Comment by filimonov** [comment]
`git submodule update --init --recursive`?

**Comment by nikitamikhaylov** [comment]
`git submodule sync && git submodule update --init --recursive && git submodule foreach git reset --hard && git submodule foreach git clean -xfd`
