### ISSUE TITLE
Parts exist twice in partition

### ISSUE THREAD

**Issue by ralphM78** [ClickHouse/ClickHouse#17346]
Hello,

OS RH 7
Clickhouse version 20.11.3.3

no idea how this could happen, but after restoring a replicated table, all parts from one partition are shown twice. Size and hash are identical. I'm really sure that I have done something wrong. But how to resolve this problem ?
```Row 1:
──────
partition_id:      202010
name:              202010_626501_626501_0_432445
database:          osb4_metrics_r0
table:             osb4_reverse
bytes_on_disk:     62919223695
modification_time: 2020-11-23 16:13:05
hash_of_all_files: 4e068ae20d44463866cca1d1c8bb0336

Row 2:
──────
partition_id:      202010
name:              202010_626522_626522_0_432445
database:          osb4_metrics_r0
table:             osb4_reverse
bytes_on_disk:     62919223695
modification_time: 2020-11-23 16:13:05
hash_of_all_files: 4e068ae20d44463866cca1d1c8bb0336
```
During first try of recovering, the disk wasn't big enough. So I have stopped it and set replicated_max_parallel_fetches to 2.
After that the table is replicated now, but everything exists twice. I have tried to set one part to inactive with ```alter table update system.parts```, but it looks that this isn't supported.

Is it possible to delete one of these parts ? 

Ralph

**Comment by filimonov** [comment]
> after restoring a replicated table,

Most probably you did backup recovery from the same backup on 2 replicas (some ATTACH / part / partition manipulation commands). You need to recover single replica from backup, on other replicas you need only to recreate the table and it will sync the data from the other one. 

> Is it possible to delete one of these parts ?

No cheap / easy way. You can try OPTIMIZE DEDUPLICATE (but it's quite heavy operation, will dedup on row level).

**Comment by ralphM78** [comment]
Thanks for your answer. ATTACH on the wrong node could be possible. Would it work to delete the duplicate parts in zookeeper and on the nodes disk ? I don't really have a test environment to check.

Ralph

**Comment by filimonov** [comment]
> Would it work to delete the duplicate parts in zookeeper and on the nodes disk ?

It is not safe (it's hard to do it w/o braking some invariants), beside that i guess lot of those parts were merged together already.

**Comment by ralphM78** [comment]
Will PARTITION REPLACE work between a replacingmergetree table and a replicatedreplacingmergetree table? Same host, different databases.

Ralph

**Comment by filimonov** [comment]
If the schema (set of columns / keys / partitioning etc) is the same - then the answer is yes, definitely.

**Comment by ralphM78** [comment]
Transfering data takes very long.
I can run two queries at the same time in parallel ...

```insert into deduplicate.reverse select * from metrics_r0.reverse where (Date = '2020-10-01');```
```insert into deduplicate.reverse select * from metrics_r0.reverse where (Date = '2020-10-02');```

For both transfer rate is nearly 500MB/s.
If I run ...

```insert into deduplicate.reverse select * from metrics_r0.reverse where (Date >= '2020-10-01' AND Date <= '2020-10-02');```

transfer rate is 250 MB/s only. With ...

```insert into deduplicate.reverse select * from metrics_r0.reverse where (Date >= '2020-10-01' AND Date <= '2020-10-31');```

transfer rate is going down to 90 MB/s only.
Can the query be optimized or is this a normal behavior ?

Ralph

**Comment by ralphM78** [comment]
So ```PARTITION REPLACE``` hasn't worked because of different storage policies. But ```DETACH``` and ```ATTACH``` between a ReplacingMergetree and the ReplicatedReplacingMergetree has worked. Thanks for helping.

Ralph
