### ISSUE TITLE
HTTP interface: kill insert queries after disconnect

### ISSUE THREAD

**Issue by ahmeturun** [ClickHouse/ClickHouse#17355]
currently only select queries(readonly) are supported for cancellation on http interface. for insert into queries cancellation is not supported. in the case of canceling insert queries the only way to make the cancellation work is, as suggested [here](https://github.com/ClickHouse/ClickHouse/issues/1403#issuecomment-342909675), to use chproxy, which is a bit of an overkill solution for just being able to cancel hanging queries. it would be good to also have support for cancellation of insert queries.

**Describe alternatives you've considered**
using chproxy does offers an alternative solution, but it is kind of an overkill.

**Comment by alexey-milovidov** [comment]
INSERT queries will be naturally canceled on connection close, as the next attempt to write data to the socket will fail.
Therefore, as long as the INSERT query is trying to insert something, it will be canceled on connection close.
