### ISSUE TITLE
replicated part FAILED fetches between two replicas

### ISSUE THREAD

**Issue by BernieJiangDL** [ClickHouse/ClickHouse#17353]
This happens between two replicas of the CH cluster.

One of the replicas runs well but the other one seems fail to fetch data part from the first one.

The log I pasted below.

This problem's solved after restarting clickhouse server on the pair node.

I am confused that why this would happen and what infos we can gain from the log below.

and how to point and solve this problem without restarting.

Thanks a lot.

2020.11.24 15:33:44.251143 [ 42024 ] {} <Error> {database}.{table_name}: DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Code: 86, e.displayText() = DB::Exception: Received error from remote server ?endpoint=DataPartsExchange%3A%2Fclickhouse%2Fck_cluster%2F{database}%2Ftables%2F01-05%2F{table_name}%2Freplicas%2F{replica_name}&part=20201127_694_723_6&client_protocol_version=2&compress=false. HTTP status code: 500 Internal Server Error, body: Code: 221, e.displayText() = DB::Exception: No interserver IO endpoint named DataPartsExchange:/clickhouse/ck_cluster/{database}/tables/01-05/{table_name}/replicas/{replica_name}, Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xbb8c1cc in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x4ff4bb9 in /usr/bin/clickhouse
2. ? @ 0x49e1048 in /usr/bin/clickhouse
3. DB::InterserverIOHTTPHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&) @ 0x5065294 in /usr/bin/clickhouse
4. Poco::Net::HTTPServerConnection::run() @ 0x9c6b43b in /usr/bin/clickhouse
5. Poco::Net::TCPServerConnection::start() @ 0x9c68017 in /usr/bin/clickhouse
6. Poco::Net::TCPServerDispatcher::run() @ 0x9c6840d in /usr/bin/clickhouse
7. Poco::PooledThread::run() @ 0xbbfaf4f in /usr/bin/clickhouse
8. Poco::ThreadImpl::runnableEntry(void*) @ 0xbbf81b8 in /usr/bin/clickhouse
9. ? @ 0xbbf98e9 in /usr/bin/clickhouse
10. start_thread @ 0x7eb5 in /usr/lib64/libpthread-2.17.so
11. clone @ 0xfe8fd in /usr/lib64/libc-2.17.so
 (version 20.3.8.53), Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xbb8c1cc in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x4ff4bb9 in /usr/bin/clickhouse
2. ? @ 0x4d5f6ba in /usr/bin/clickhouse
3. DB::receiveResponse(Poco::Net::HTTPClientSession&, Poco::Net::HTTPRequest const&, Poco::Net::HTTPResponse&, bool) @ 0x9a4f96f in /usr/bin/clickhouse
4. DB::detail::ReadWriteBufferFromHTTPBase<std::__1::shared_ptr<DB::UpdatablePooledSession> >::call(Poco::URI, Poco::Net::HTTPResponse&) @ 0x8ece233 in /usr/bin/clickhouse
5. DB::detail::ReadWriteBufferFromHTTPBase<std::__1::shared_ptr<DB::UpdatablePooledSession> >::ReadWriteBufferFromHTTPBase(std::__1::shared_ptr<DB::UpdatablePooledSession>, Poco::URI, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<void (std::__1::basic_ostream<char, std::__1::char_traits<char> >&)>, Poco::Net::HTTPBasicCredentials const&, unsigned long, std::__1::vector<std::__1::tuple<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::tuple<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > >, DB::RemoteHostFilter const&) @ 0x8ece7cb in /usr/bin/clickhouse
6. DB::DataPartsExchange::Fetcher::fetchPart(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, DB::ConnectionTimeouts const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x8ecb819 in /usr/bin/clickhouse
7. ? @ 0x8e0c3c3 in /usr/bin/clickhouse
8. DB::StorageReplicatedMergeTree::fetchPart(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, unsigned long) @ 0x8e51966 in /usr/bin/clickhouse
9. DB::StorageReplicatedMergeTree::executeFetch(DB::ReplicatedMergeTreeLogEntry&) @ 0x8e54fb6 in /usr/bin/clickhouse
10. DB::StorageReplicatedMergeTree::executeLogEntry(DB::ReplicatedMergeTreeLogEntry&) @ 0x8e5678d in /usr/bin/clickhouse
11. ? @ 0x8e56bbc in /usr/bin/clickhouse
12. DB::ReplicatedMergeTreeQueue::processEntry(std::__1::function<std::__1::shared_ptr<zkutil::ZooKeeper> ()>, std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&, std::__1::function<bool (std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&)>) @ 0x901eb0e in /usr/bin/clickhouse
13. DB::StorageReplicatedMergeTree::queueTask() @ 0x8e0ddd7 in /usr/bin/clickhouse
14. DB::BackgroundProcessingPool::threadFunction() @ 0x8ec6221 in /usr/bin/clickhouse
15. ? @ 0x8ec6bcd in /usr/bin/clickhouse
16. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x4ffe407 in /usr/bin/clickhouse
17. ? @ 0x4ffca5f in /usr/bin/clickhouse
18. start_thread @ 0x7eb5 in /usr/lib64/libpthread-2.17.so
19. clone @ 0xfe8fd in /usr/lib64/libc-2.17.so
 (version 20.3.8.53)

**Comment by alexey-milovidov** [comment]
It indicates misconfiguration.
