### ISSUE TITLE
Array join incorrect result when requesting distributed table

### ISSUE THREAD

**Issue by crakjie** [ClickHouse/ClickHouse#17367]
When running some specific query with arrayJoin result are not what they are expected to be.
This seems to be correlated to the usage of State Merge modifier.

Clickhouse 20.3.20.6

The following query 
```sql
WITH arrayJoin(['a','b']) as z
SELECT
     z,
     sumMergeForEach(x) as x
FROM
(
     SELECT 
         sumStateForEach([1.0,1.1,1.1300175]) as x
    FROM 
        aDistributedTable
)
GROUP BY z
```
Return [1.5e-323, 3e-323, a value that depends of the number of elements in you table] 

When used on a shard table or `numbers` table the result are correct.

When used with finalizedAggregation without group by the result are correct.

When used with sumForEach the results are correct.

The value above are an exemple but differents inital values can fail with differents results.

Strangly , running the query without the group by return the right results.

**Comment by alexey-milovidov** [comment]
It works perfectly:

```
WITH arrayJoin(['a', 'b']) AS z
SELECT
    z,
    sumMergeForEach(x) AS x
FROM
(
    SELECT sumStateForEach([1., 1.1, 1.1300175]) AS x
    FROM remote('127.0.0.{1,2}', system.one)
)
GROUP BY z
```
