### ISSUE TITLE
I want to load a CSV file with less columns than in table,how can I do?

### ISSUE THREAD

**Issue by wallace-clickhouse** [ClickHouse/ClickHouse#17362]
I tried to load a CSV file into ClickHouse with clickhouse-client, while the number of columns in CSV file is less than the number of columns in the table.Unfortunately I got the error message below:

_ERROR: Line feed found where delimiter (|) is expected. It's like your file has less columns than expected.
And if your file have right number of columns, maybe it have unescaped quotes in values._

I think it's normal to load a CSV file with less columns than in table(reference to other databases,such as Sybase/postgresql) .Tables should ignore the missing columns at the end of line in CSV files when loaded.
So could you give me some suggestions?Thanks a lot.

**Comment by den-crane** [comment]
just mention column names in insert `insert into table(A,B,C,D) format CSV`
or use CSV with columns names.
