### ISSUE TITLE
build master branch on MacOS error

### ISSUE THREAD

**Issue by hoverzheng** [ClickHouse/ClickHouse#17379]
The g++ and gcc version are following: 
```
$ g++ --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.2.0
Thread model: posix

$ gcc --verison
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
```

I got error:
```
$ ninja
FAILED: src/Functions/CMakeFiles/clickhouse_functions.dir/FunctionsHashing.cpp.o 

In file included from ../src/Functions/FunctionsHashing.cpp:1:
In file included from ../src/Functions/FunctionsHashing.h:44:
/Users/hover/opensrc/ClickHouse/src/Functions/TargetSpecific.h:197:1: error: expected unqualified-id
DECLARE_SSE42_SPECIFIC_CODE(
^
/Users/hover/opensrc/ClickHouse/src/Functions/TargetSpecific.h:131:42: note: expanded from macro 'DECLARE_SSE42_SPECIFIC_CODE'
#define DECLARE_SSE42_SPECIFIC_CODE(...) \
                                         ^
/Users/hover/opensrc/ClickHouse/src/Functions/TargetSpecific.h:102:9: note: expanded from macro '\
BEGIN_SSE42_SPECIFIC_CODE'
        _Pragma("clang attribute push(__attribute__((target(\"sse,sse2,sse3,ssse3,sse4,popcnt\"))),apply_to=function)")
        ^
<scratch space>:278:8: note: expanded from here
 clang attribute push(__attribute__((target("sse,sse2,sse3,ssse3,sse4,popcnt"))),apply_to=function)
       ^
In file included from ../src/Functions/FunctionsHashing.cpp:1:
In file included from ../src/Functions/FunctionsHashing.h:44:
/Users/hover/opensrc/ClickHouse/src/Functions/TargetSpecific.h:197:1: error: expected unqualified-id
/Users/hover/opensrc/ClickHouse/src/Functions/TargetSpecific.h:137:3: note: expanded from macro 'DECLARE_SSE42_SPECIFIC_CODE'
} \
  ^
/Users/hover/opensrc/ClickHouse/src/Functions/TargetSpecific.h:104:9: note: expanded from macro '\
END_TARGET_SPECIFIC_CODE'
        _Pragma("clang attribute pop")
        ^
<scratch space>:280:8: note: expanded from here
 clang attribute pop
       ^
In file included from ../src/Functions/FunctionsHashing.cpp:1:
In file included from ../src/Functions/FunctionsHashing.h:44:
/Users/hover/opensrc/ClickHouse/src/Functions/TargetSpecific.h:201:1: error: expected unqualified-id
DECLARE_AVX_SPECIFIC_CODE(
^
/Users/hover/opensrc/ClickHouse/src/Functions/TargetSpecific.h:146:3: note: expanded from macro 'DECLARE_AVX_SPECIFIC_CODE'
} \
  ^
/Users/hover/opensrc/ClickHouse/src/Functions/TargetSpecific.h:104:9: note: expanded from macro '\
END_TARGET_SPECIFIC_CODE'
        _Pragma("clang attribute pop")
        ^
<scratch space>:284:8: note: expanded from here
 clang attribute pop
       ^
In file included from ../src/Functions/FunctionsHashing.cpp:1:
In file included from ../src/Functions/FunctionsHashing.h:44:
/Users/hover/opensrc/ClickHouse/src/Functions/TargetSpecific.h:205:1: error: expected unqualified-id
DECLARE_AVX2_SPECIFIC_CODE(
^
/Users/hover/opensrc/ClickHouse/src/Functions/TargetSpecific.h:155:3: note: expanded from macro 'DECLARE_AVX2_SPECIFIC_CODE'
} \
  ^
/Users/hover/opensrc/ClickHouse/src/Functions/TargetSpecific.h:104:9: note: expanded from macro '\
END_TARGET_SPECIFIC_CODE'
        _Pragma("clang attribute pop")
        ^
<scratch space>:288:8: note: expanded from here
 clang attribute pop
       ^
In file included from ../src/Functions/FunctionsHashing.cpp:1:
In file included from ../src/Functions/FunctionsHashing.h:44:
/Users/hover/opensrc/ClickHouse/src/Functions/TargetSpecific.h:209:1: error: expected unqualified-id
DECLARE_AVX512F_SPECIFIC_CODE(
^
/Users/hover/opensrc/ClickHouse/src/Functions/TargetSpecific.h:164:3: note: expanded from macro 'DECLARE_AVX512F_SPECIFIC_CODE'
} \
  ^
/Users/hover/opensrc/ClickHouse/src/Functions/TargetSpecific.h:104:9: note: expanded from macro '\

  ^
/Users/hover/opensrc/ClickHouse/src/Functions/TargetSpecific.h:104:9: note: expanded from macro '\
END_TARGET_SPECIFIC_CODE'
        _Pragma("clang attribute pop")
        ^
<scratch space>:292:8: note: expanded from here
 clang attribute pop
       ^
In file included from ../src/Functions/FunctionsHashing.cpp:1:
/Users/hover/opensrc/ClickHouse/src/Functions/FunctionsHashing.h:607:1: error: expected unqualified-id
DECLARE_MULTITARGET_CODE(
^
/Users/hover/opensrc/ClickHouse/src/Functions/TargetSpecific.h:187:44: note: expanded from macro 'DECLARE_MULTITARGET_CODE'
DECLARE_DEFAULT_CODE         (__VA_ARGS__) \
                                           ^
/Users/hover/opensrc/ClickHouse/src/Functions/TargetSpecific.h:131:42: note: expanded from macro '\
DECLARE_SSE42_SPECIFIC_CODE'
#define DECLARE_SSE42_SPECIFIC_CODE(...) \
                                         ^
/Users/hover/opensrc/ClickHouse/src/Functions/TargetSpecific.h:102:9: note: expanded from macro '\
BEGIN_SSE42_SPECIFIC_CODE'
        _Pragma("clang attribute push(__attribute__((target(\"sse,sse2,sse3,ssse3,sse4,popcnt\"))),apply_to=function)")
        ^
<scratch space>:189:8: note: expanded from here
 clang attribute push(__attribute__((target("sse,sse2,sse3,ssse3,sse4,popcnt"))),apply_to=function)
       ^
In file included from ../src/Functions/FunctionsHashing.cpp:1:
/Users/hover/opensrc/ClickHouse/src/Functions/FunctionsHashing.h:607:1: error: expected unqualified-id
/Users/hover/opensrc/ClickHouse/src/Functions/TargetSpecific.h:187:44: note: expanded from macro 'DECLARE_MULTITARGET_CODE'
DECLARE_DEFAULT_CODE         (__VA_ARGS__) \
                                           ^
/Users/hover/opensrc/ClickHouse/src/Functions/TargetSpecific.h:137:3: note: expanded from macro '\
DECLARE_SSE42_SPECIFIC_CODE'
```

...

How can I fix it?
Thanks!

**Comment by filimonov** [comment]
Try clang. 
https://clickhouse.tech/docs/en/development/build-osx/

**Comment by hoverzheng** [comment]
Thanks @filimonov.

The previous error come from here:

I build CK like https://clickhouse.tech/docs/en/development/build-osx/：

$ cmake .. -DCMAKE_CXX_COMPILER=`which clang++` -DCMAKE_C_COMPILER=`which clang`
CMake Error at cmake/tools.cmake:21 (message):
  AppleClang is not supported, you should install clang from brew.
Call Stack (most recent call first):
  CMakeLists.txt:44 (include)

-- Configuring incomplete, errors occurred!
See also "/Users/hover/opensrc/ClickHouse/build/CMakeFiles/CMakeOutput.log".

I open the file:
$ vim ../cmake/tools.cmake 

I saw this words:
...
21         message (FATAL_ERROR "AppleClang is not supported, you should install clang from brew.")
...

So, I commit the sentence，then build is ok, but when I run **ninja** command get the above error.

**Comment by filimonov** [comment]
Remove CMakeCache, or... just "install clang from brew" how the message says.

**Comment by hoverzheng** [comment]
Hi @filimonov 

I deleted CMakeCache.txt, and run **ninjia**，but got the same error：

$ ninja
[0/2] Re-checking globbed directories...
[1/2] Re-running CMake...
-- The C compiler identification is AppleClang 10.0.1.10010046
-- The CXX compiler identification is AppleClang 10.0.1.10010046
-- Detecting C compiler ABI info 
-- Detecting C compiler ABI info - done 
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done 
-- Detecting CXX compiler ABI info 
-- Detecting CXX compiler ABI info - done 
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done 
-- Using /usr/local/bin/ccache 4.0
-- CMAKE_BUILD_TYPE is not set, set to default = RelWithDebInfo
-- CMAKE_BUILD_TYPE: RelWithDebInfo
-- Using objcopy: /usr/local/opt/binutils/bin/objcopy.
-- Disabling compiler -pipe option (have only 1690 mb of memory)

... ...

In file included from ../src/Functions/FunctionsHashing.cpp:1:
In file included from ../src/Functions/FunctionsHashing.h:44:
/Users/hover/opensrc/ClickHouse/src/Functions/TargetSpecific.h:197:1: error: expected unqualified-id
DECLARE_SSE42_SPECIFIC_CODE(
^
/Users/hover/opensrc/ClickHouse/src/Functions/TargetSpecific.h:131:42: note: expanded from macro 'DECLARE_SSE42_SPECIFIC_CODE'
#define DECLARE_SSE42_SPECIFIC_CODE(...) \
                                         ^
/Users/hover/opensrc/ClickHouse/src/Functions/TargetSpecific.h:102:9: note: expanded from macro '\
BEGIN_SSE42_SPECIFIC_CODE'
        _Pragma("clang attribute push(__attribute__((target(\"sse,sse2,sse3,ssse3,sse4,popcnt\"))),apply_to=function)")
        ^
<scratch space>:278:8: note: expanded from here
 clang attribute push(__attribute__((target("sse,sse2,sse3,ssse3,sse4,popcnt"))),apply_to=function)
       ^
In file included from ../src/Functions/FunctionsHashing.cpp:1:
In file included from ../src/Functions/FunctionsHashing.h:44:
/Users/hover/opensrc/ClickHouse/src/Functions/TargetSpecific.h:197:1: error: expected unqualified-id
/Users/hover/opensrc/ClickHouse/src/Functions/TargetSpecific.h:137:3: note: expanded from macro 'DECLARE_SSE42_SPECIFIC_CODE'
} \
  ^
/Users/hover/opensrc/ClickHouse/src/Functions/TargetSpecific.h:104:9: note: expanded from macro '\
END_TARGET_SPECIFIC_CODE'
        _Pragma("clang attribute pop")
        ^
<scratch space>:280:8: note: expanded from here
 clang attribute pop
       ^
In file included from ../src/Functions/FunctionsHashing.cpp:1:
In file included from ../src/Functions/FunctionsHashing.h:44:
/Users/hover/opensrc/ClickHouse/src/Functions/TargetSpecific.h:201:1: error: expected unqualified-id
DECLARE_AVX_SPECIFIC_CODE(
^
/Users/hover/opensrc/ClickHouse/src/Functions/TargetSpecific.h:146:3: note: expanded from macro 'DECLARE_AVX_SPECIFIC_CODE'
} \
  ^
...

**Comment by alexey-milovidov** [comment]
> The C compiler identification is AppleClang 10.0.1.10010046

It is AppleClang, not clang.

**Comment by traceon** [comment]
AppleClang works fine for me. My version is the latest, but 10.0.1 should work too.

@hoverzheng try installing Xcode version of CommandLineTools:
```sh
sudo rm -rf /Library/Developer/CommandLineTools
sudo xcode-select --install
```

Clean everything in build folder and run fresh `cmake ..`.

**Comment by traceon** [comment]
> `$ cmake .. -DCMAKE_CXX_COMPILER=which clang++ -DCMAKE_C_COMPILER=which clang`

Meanwhile, the correct way of substituting the compiler in CMake is this:
```sh
$ CC=$(which clang) CXX=$(which clang++) cmake ..
```

**Comment by hoverzheng** [comment]
Hi @traceon, @alexey-milovidov 
I try your method, but the error is the same, Mybe I should Install Clang not AppleClang?

**Comment by traceon** [comment]
@hoverzheng have you installed Command Line Tools from Xcode?

**Comment by traceon** [comment]
@hoverzheng if you want to use vanilla Clang from brew:
```sh
$ brew install llvm
$ CC=$(brew --prefix llvm)/bin/clang CXX=$(brew --prefix llvm)/bin/clang++ cmake ..
```

**Comment by hoverzheng** [comment]
thanks @traceon.
I used the command: 

$ CC=$(brew --prefix llvm)/bin/clang CXX=$(brew --prefix llvm)/bin/clang++ cmake ..
$ ninja

and got the error:

FAILED: contrib/protobuf/protoc-3.13.0.0 
: && ccache /usr/local/opt/llvm/bin/clang++ -fdiagnostics-color=always -std=c++2a -fsized-deallocation  -gdwarf-aranges -msse4.1 -msse4.2 -mpopcnt   -Wall -Wno-unused-command-line-argument  -stdlib=libc++ -fdiagnostics-absolute-paths -fexperimental-new-pass-manager -Werror -w -O2 -g -DNDEBUG -O3  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.15 -Wl,-search_paths_first -Wl,-headerpad_max_install_names -rdynamic -Wl,-U,_inside_main contrib/protobuf/CMakeFiles/protoc.dir/__/src/google/protobuf/compiler/main.cc.o -o contrib/protobuf/protoc-3.13.0.0  contrib/protobuf/libprotoc.a  contrib/protobuf/libprotobuf.a  -lpthread  contrib/libcxx-cmake/libcxx.a  contrib/libcxxabi-cmake/libcxxabi.a  -nodefaultlibs  -lc -lm -lpthread -ldl && :
Undefined symbols for architecture x86_64:
  "google::protobuf::compiler::objectivec::ObjectiveCGenerator::ObjectiveCGenerator()", referenced from:
      google::protobuf::compiler::ProtobufMain(int, char**) in main.cc.o
  "google::protobuf::compiler::objectivec::ObjectiveCGenerator::~ObjectiveCGenerator()", referenced from:
      google::protobuf::compiler::ProtobufMain(int, char**) in main.cc.o
  "google::protobuf::compiler::CodeGenerator::~CodeGenerator()", referenced from:
      google::protobuf::compiler::ProtobufMain(int, char**) in main.cc.o
  "google::protobuf::compiler::CommandLineInterface::AllowPlugins(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      google::protobuf::compiler::ProtobufMain(int, char**) in main.cc.o
  "google::protobuf::compiler::CommandLineInterface::RegisterGenerator(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, google::protobuf::compiler::CodeGenerator*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      google::protobuf::compiler::ProtobufMain(int, char**) in main.cc.o
  "google::protobuf::compiler::CommandLineInterface::Run(int, char const* const*)", referenced from:
      google::protobuf::compiler::ProtobufMain(int, char**) in main.cc.o
  "google::protobuf::compiler::CommandLineInterface::CommandLineInterface()", referenced from:
      google::protobuf::compiler::ProtobufMain(int, char**) in main.cc.o
  "google::protobuf::compiler::CommandLineInterface::~CommandLineInterface()", referenced from:
      google::protobuf::compiler::ProtobufMain(int, char**) in main.cc.o
  "google::protobuf::compiler::cpp::CppGenerator::CppGenerator()", referenced from:
      google::protobuf::compiler::ProtobufMain(int, char**) in main.cc.o
  "google::protobuf::compiler::cpp::CppGenerator::~CppGenerator()", referenced from:
      google::protobuf::compiler::ProtobufMain(int, char**) in main.cc.o
  "google::protobuf::compiler::java::JavaGenerator::JavaGenerator()", referenced from:
      google::protobuf::compiler::ProtobufMain(int, char**) in main.cc.o
  "google::protobuf::compiler::java::JavaGenerator::~JavaGenerator()", referenced from:
      google::protobuf::compiler::ProtobufMain(int, char**) in main.cc.o
  "google::protobuf::compiler::csharp::Generator::Generator()", referenced from:
      google::protobuf::compiler::ProtobufMain(int, char**) in main.cc.o
  "google::protobuf::compiler::csharp::Generator::~Generator()", referenced from:
      google::protobuf::compiler::ProtobufMain(int, char**) in main.cc.o
  "google::protobuf::compiler::python::Generator::Generator()", referenced from:
      google::protobuf::compiler::ProtobufMain(int, char**) in main.cc.o
  "google::protobuf::compiler::python::Generator::~Generator()", referenced from:
      google::protobuf::compiler::ProtobufMain(int, char**) in main.cc.o
  "vtable for google::protobuf::compiler::js::Generator", referenced from:
      google::protobuf::compiler::ProtobufMain(int, char**) in main.cc.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "vtable for google::protobuf::compiler::php::Generator", referenced from:
      google::protobuf::compiler::ProtobufMain(int, char**) in main.cc.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "vtable for google::protobuf::compiler::ruby::Generator", referenced from:
      google::protobuf::compiler::ProtobufMain(int, char**) in main.cc.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "operator delete(void*, unsigned long)", referenced from:
      google::protobuf::compiler::ProtobufMain(int, char**) in main.cc.o
  "operator new(unsigned long)", referenced from:
      google::protobuf::compiler::ProtobufMain(int, char**) in main.cc.o
  "___gxx_personality_v0", referenced from:
      google::protobuf::compiler::ProtobufMain(int, char**) in main.cc.o
      Dwarf Exception Unwind Info (__eh_frame) in main.cc.o
ld: symbol(s) not found for architecture x86_64
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
[3084/5860] Building CXX object contrib/rocksdb-cmake/CMakeFiles/rocksdb.dir/__/rocksdb/file/file_prefetch_buffer.cc.o
[3085/5860] Building CXX object contrib/rocksdb-cmake/CMakeFiles/rocksdb.dir/__/rocksdb/table/block_based/flush_block_policy.cc.o
[3086/5860] Building CXX object contrib/rocksdb-cmake/CMakeFiles/rocksdb.dir/__/rocksdb/table/block_based/parsed_full_filter_block.cc.o
[3087/5860] Building CXX object contrib/rocksdb-cmake/CMakeFiles/rocksdb.dir/__/rocksdb/table/block_based/index_reader_common.cc.o
[3088/5860] Building CXX object contrib/rocksdb-cmake/CMakeFiles/rocksdb.dir/__/rocksdb/table/block_based/hash_index_reader.cc.o
[3089/5860] Building CXX object contrib/rocksdb-cmake/CMakeFiles/rocksdb.dir/__/rocksdb/table/block_based/full_filter_block.cc.o
[3090/5860] Building CXX object contrib/rocksdb-cmake/CMakeFiles/rocksdb.dir/__/rocksdb/table/block_based/index_builder.cc.o
[3091/5860] Building CXX object contrib/rocksdb-cmake/CMakeFiles/rocksdb.dir/__/rocksdb/table/block_based/filter_policy.cc.o
[3092/5860] Building CXX object contrib/rocksdb-cmake/CMakeFiles/rocksdb.dir/__/rocksdb/file/delete_scheduler.cc.o
ninja: build stopped: subcommand failed.

I found there is not protoc-3.13.0.0 path in the contrib/protobuf.  
Should I download protoc-3.13.0.0??

**Comment by traceon** [comment]
@hoverzheng run this in the `ClickHouse/` repo dir:
```sh
git submodule update --init --recursive && git pull --recurse-submodule
```

**Comment by hoverzheng** [comment]
Thanks @traceon!

I solved it !
