### ISSUE TITLE
WITH FILL: How to fill with use char

### ISSUE THREAD

**Issue by vegastar002** [ClickHouse/ClickHouse#17377]
fill with only support number and date ,  the result :
x1  12
x3  34

I want add 
x2 0

how do it ?

**Comment by filimonov** [comment]
I guess the question is about 'WITH FILL'  feature.

No way for that in common case (how should i 'fill' the 'gap' between 'Alaska' and '襄樊市' ?) 

In your case you can split your 'x1' into string part and numeric part, and do WITH FILL against numeric part.
