### ISSUE TITLE
Clickhouse incorrectly returns time

### ISSUE THREAD

**Issue by DmitriZhukov** [ClickHouse/ClickHouse#17387]
I have noticed that server returns all values shifted by one hour. May be it is because of timezone

Sample code
```
create table temp
(
    datetime DateTime
)

insert into temp (datetime) values('2020-11-25 00:10:00')

```
```
select * from temp where
datetime between '2020-11-25 00:00:00' and '2020-11-25 00:10:00';

```
this yields
2020-11-24 23:10:00

How this can be?

**Comment by filimonov** [comment]
1) select timezone();
2) http client vs tcp client?

**Comment by DmitriZhukov** [comment]
```
select timezone()
Europe/Berlin
```
I think it is TCP  as I set connection string by server ip address

Some info in my SQL client I do
`insert into temp (datetime) values('2020-11-24 15:22:00')`

but see what it stores
`select * from temp order by datetime`

results
`2020-11-24 14:22:00`

**Comment by den-crane** [comment]
JDBC client converts DateTime to TZ of JVM (to TZ of your Desktop).

check `select now() , toString(now())`

https://github.com/ClickHouse/clickhouse-jdbc/issues/202

**Comment by DmitriZhukov** [comment]
@den-crane 

sql client time is 18:04

`select now() , toString(now())`
`2020-11-25 15:04:31, 2020-11-25 16:04:31`

Server is located in UTC +2 Germany
My Computer is located in UTC+3 Moscow

So _now()_ gives correct time zone of UTC
_toString(now())_ gives incorrect time zone

**Comment by den-crane** [comment]
hm,

>sql client time is 18:04
>So now() gives correct time zone of UTC

No it's incorrect. You should get 18:04
Check your JDBC settings. 

```
use_time_zone	
use_server_time_zone_for_dates	
use_server_time_zone	

```

Another question what do you want to achieve? Because now you observe a normal behavior. CH server and clients convert time to a local timezone automatically.

**Comment by den-crane** [comment]
I suggest to configure at your desktop

use_time_zone=Europe/Moscow
use_server_time_zone_for_dates=false
use_server_time_zone=false

When JDBC will not convert time.

**Comment by den-crane** [comment]
```
select timezone() -> Europe/Berlin

datetime DateTime

insert into temp (datetime) values('2020-11-25 00:10:00')
```

При инсерте КХ воспринимает ('2020-11-25 00:10:00') как время в  Europe/Berlin, конвертирует в unixtime в UTC и сохраняет в таблице.

```
select * from temp where
datetime between '2020-11-25 00:00:00' and '2020-11-25 00:10:00';
```
КХ конвертирует '2020-11-25 00:00:00' and '2020-11-25 00:10:00' из Europe/Berlin в unixtime в UTC и фильтрует, получает  unixtime в UTC, конвертирует в таймозону Europe/Berlin  в строку '2020-11-25 00:10:00' для HTTP/JDBC (TSV format). JDBC драйвер знает что на сервере  Europe/Berlin, т.е. строки приходят Europe/Berlin и конвертирует это время в Moscow.

**Comment by DmitriZhukov** [comment]
Я все равно не понимаю откуда разница в один час получается,
и как посмотреть настройки JDBC где это

**Comment by den-crane** [comment]
Вы как / чем запросы на от себя выполняете?

**Comment by DmitriZhukov** [comment]
i have

use_server_time_zone | true
use_time_zone |  
use_server_time_zone_for_dates | false

Почему у меня все сдвигается на час
in my SQL client I do
insert into temp (datetime) values('2020-11-24 15:22:00')

but see what it stores
select * from temp order by datetime

results
2020-11-24 14:22:00

**Comment by den-crane** [comment]
Потому что переводится из Берлин в Москва. Видимо JVM старая и не знает про отмену перевода на летнее / зимнее.

Поставьте 
на клиенте поставить
```
use_time_zone=Europe/Moscow
use_server_time_zone_for_dates=false
use_server_time_zone=false
```
и будет конвертировать Europe/Moscow -> UTC ->Europe/Moscow и будет видно время с сервера которое там Europe/Berlin

**Comment by den-crane** [comment]
а что в `select now(), toString(now())`
