### ISSUE TITLE
I added the output information in the source code, but output nothing after compiling

### ISSUE THREAD

**Issue by Joeywzr** [ClickHouse/ClickHouse#17386]
For example, I added some output info in the `BlockIO InterpreterCreateQuery::execute()`, but there is nothing new when I start the server. Then I modified a `throw Exception` in the `src/Storages/StorageFactory.cpp`:
~~~
if (it == storages.end())
{
    auto hints = getHints(name);
    if (!hints.empty())
        throw Exception("Unknown table engine " + name + ". Maybe you meant: " + toString(hints), ErrorCodes::UNKNOWN_STORAGE);
    else
        throw Exception("Unknown table engine " + name, ErrorCodes::UNKNOWN_STORAGE);
}
~~~
Even if I modify the throw Exception message, the output is still the old throw Exception message. It seems that in the new version, there will be no change after compiling the modified code. I'm confused now cuz I have never met this problem in version 19. of ClickHouse.

**Comment by filimonov** [comment]
What do you see when you recompile the project / i.e. when run `ninja`? 
Check timestamp of your binary, and a way how you run it.

**Comment by Joeywzr** [comment]
@filimonov Thanks. Here it is.
~~~
[wzr@sugon205 build]$ ninja
[0/2] Re-checking globbed directories...
[14/14] cd /home/wzr/ch113/ClickH..._symlink clickhouse clickhouse-server
~~~
The whole process is that I modify a code file, then I recompile it using `ninja`, and then generate a new clickhouse file in `build/programs`. Although this `clickhouse` is newly generated, it runs the same as the old one. I do the same with the 19 version of Clickhouse and it works well.

**Comment by filimonov** [comment]
That sounds really strange. I guess some the reason is some silly tiny error like using the wrong path or smth like that. 

Try to remove your builded binary, try to start it (should fail).
Try to make some syntax error in your cpp file and compile (should fail).

**Comment by Joeywzr** [comment]
I think I've found the problem. After I delete the builded binary, I can still run it, but I don't know where the binary is running.
