### ISSUE TITLE
clickhouse sipHash64 hash function and shard implementation

### ISSUE THREAD

**Issue by ahutsunshine** [ClickHouse/ClickHouse#17393]
I'm trying to implement clickhouse sipHash64 function using Golang github.com/dchest/siphash since we use sipHash64 function to do sharding and ingest data to nodes by ourselves and then distributed table can query correctly from the corresponding nodes with the same hash function. 

The below param in hash function is byte array.  Firstly we convert the data value to byte array and get the hash by calling the below hash method.  I can get the same hash result for uint8, uint64 and string with clickhouse sipHash64, but I cannot get the same hash for datetime and float32 and float64 data type. Does clickhouse do something special logic for datatime and float64 type when sharding?
I'm not familiar with C++.

Question:
1. Can you tell me how to get the same hash or specify the sipHash64 C++ code in clickhouse? 
2. How does the multiple columns as shards implement? For example, if I take `host`(string) and `time`(DateTime) as sharding keys, how to calculate the hash and the shard num?
Thanks very much.

```
Golang siphash64 implementation:

func hash(bytes []byte) uint64 {
	zeroKey := make([]byte, 16)
	h := siphash.New(zeroKey)
	_, _ = h.Write(bytes)
	hash := h.Sum64()
	return hash
}
```

**Comment by ahutsunshine** [comment]
Anyone can help this?

**Comment by alexey-milovidov** [comment]
DateTime is processed as UInt32 containing the unix timestamp.
Date is processed as UInt16 containing the number of days since unix epoch.

Float32 is processed as the corresponding 4 bytes in memory. Float64 as 8 bytes.

**Comment by alexey-milovidov** [comment]
Example:
```
milovidov-desktop :) SELECT hex(reinterpretAsString(1.0))

SELECT hex(reinterpretAsString(1.))

Query id: 2cebc77b-aa1f-4a2a-bd48-144fee820f8c

┌─hex(reinterpretAsString(1.))─┐
│ 000000000000F03F             │
└──────────────────────────────┘

1 rows in set. Elapsed: 0.002 sec. 

milovidov-desktop :) SELECT sipHash64(1.0), sipHash64(reinterpretAsString(1.0))

SELECT
    sipHash64(1.),
    sipHash64(reinterpretAsString(1.))

Query id: 36b43338-c899-4087-86d8-391413c6a4d5

┌───────sipHash64(1.)─┬─sipHash64(reinterpretAsString(1.))─┐
│ 3177009167758079239 │                3177009167758079239 │
└─────────────────────┴────────────────────────────────────┘

1 rows in set. Elapsed: 0.001 sec.
```

**Comment by ahutsunshine** [comment]
@alexey-milovidov What's the meaning of  `DateTime is processed as UInt32 containing the unix timestamp.` ? Do you mean the datetime will be converted uint32 unix timestamp and then calculate its hash?

**Comment by ahutsunshine** [comment]
IC. Works for me. Can you explain my second question?
```
How does the multiple columns as shards implement? For example, if I take host(string) and time(DateTime) as sharding keys, how to calculate the hash and the shard num?
```

**Comment by ahutsunshine** [comment]
@alexey-milovidov @den-crane

**Comment by alexey-milovidov** [comment]
For tuples, it is calculated iteratively in the following fashion:

`hash(x, y) = hash(hash(x) || hash(y))`
and 
`hash(..., x_n) = hash(hash(...) || hash(x_n))`

where || is concatenation of two 64bit values to single 128bit chunk in memory.

**Comment by ahmczsy** [comment]
> For tuples, it is calculated iteratively in the following fashion:
> 
> `hash(x, y) = hash(hash(x) || hash(y))`
> and
> `hash(..., x_n) = hash(hash(...) || hash(x_n))`
> 
> where || is concatenation of two 64bit values to single 128bit chunk in memory.

How does the array as shards implement?

`select sipHash64([1])`

**Comment by alexey-milovidov** [comment]
It's more complicated.
First we calculate intHash64 of array size. Then combine it with all array elements in chain.

`combine(prev_hash, x) = hash(prev_hash || hash(x))`

`hash(['a', 'b', 'c']) = hash(hash(hash(intHash64(3) || hash('a')) || hash('b')) || hash('c'))`

**Comment by alexey-milovidov** [comment]
The code is here: https://clickhouse.tech/codebrowser/html_report/ClickHouse/src/Functions/FunctionsHashing.h.html
