### ISSUE TITLE
how to merge 2 sql to 1 ?

### ISSUE THREAD

**Issue by vegastar002** [ClickHouse/ClickHouse#17434]
sql 1
> select * from
(select * from
(WITH ['name1', 'name2', 'name3'] AS name, [110, 102, 90] AS money,  ['20', '29', '10'] AS age select name, money, age ) array join name, money, age)
where toInt8(money)>100;

sql 2
>select * from
(select * from
(WITH ['name1', 'name2', 'name3'] AS name, [110, 102, 90] AS money,  ['20', '29', '10'] AS age select name, money, age ) array join name, money, age)
where toInt8(age)>20;

sql 1 and sql 2 used the same sql :
>(select * from
(WITH ['name1', 'name2', 'name3'] AS name, [110, 102, 90] AS money,  ['20', '29', '10'] AS age select name, money, age ) array join name, money, age)

it calculate 2 times, how can merge to one sql ?

**Comment by l1t1** [comment]
union all, case when

**Comment by l1t1** [comment]
maybe too complex
```
with t as(select * from
(WITH ['name1', 'name2', 'name3'] AS name, [110, 102, 90] AS money, ['20', '29', '10'] AS age select name, money, age ) array join name, money, age)
,
t1 as(select 1 b union all select 2),
t2 as(
select t1.b,case when t1.b=1 then toInt8(money)>100 else toInt8(age) > 20 end c ,t.* from t,t1)
select * from t2 where c=1;
```

**Comment by den-crane** [comment]
Yes, only union all. Other options will return less rows.

```
WITH t AS
    (
        SELECT *
        FROM
        (
            WITH
                ['name1', 'name2', 'name3'] AS name,
                [110, 102, 90] AS money,
                ['20', '29', '10'] AS age
            SELECT
                name,
                money,
                age
        )
        ARRAY JOIN
            name,
            money,
            age
    )
SELECT
    multiIf(toInt8(money) > 100, '1', toInt8(age) >  20, '2', '') AS a,
    t.*
FROM t
WHERE toInt8(money) > 100 or toInt8(age) > 20

┌─a─┬─name──┬─money─┬─age─┐
│ 1 │ name1 │   110 │ 20  │
│ 1 │ name2 │   102 │ 29  │
└───┴───────┴───────┴─────┘

```
