### ISSUE TITLE
"show tables not like 'xx%'",returns the result of "show tables like 'xx%'"

### ISSUE THREAD

**Issue by wallace-clickhouse** [ClickHouse/ClickHouse#17444]
When I submit the command "show tables not like 'xx%'",it returns the result of "show tables like 'xx%'".
I think it's a bug and my clickhouse server version is 20.3.2.1.
Kindly please check and confirm,Thanks.

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/8727
fixed https://github.com/ClickHouse/ClickHouse/pull/8940

upgrade to 20.3.21.2
