### ISSUE TITLE
internal_replication in distributed tables

### ISSUE THREAD

**Issue by AlexProfi** [ClickHouse/ClickHouse#17440]
(you don't have to strictly follow this form)

**Describe the issue**
https://clickhouse.tech/docs/ru/engines/table-engines/special/distributed/#distributed

in documentation text is the same  and I don't see difference in internal_replication flag

У каждого шарда в конфигурационном файле может быть указан параметр internal_replication.

Если он выставлен в true, то для записи будет выбираться первая живая реплика и данные будут писаться на неё. Этот вариант следует использовать, если Distributed таблица «смотрит» на реплицируемые таблицы. **То есть, если таблица, в которую будут записаны данные, будет сама заниматься их репликацией.**

Если он выставлен в false (по умолчанию), то данные будут записываться на все реплики. **По сути, это означает, что Distributed таблица занимается репликацией данных самостоятельно.** Это хуже, чем использование реплицируемых таблиц, так как не контролируется консистентность реплик, и они со временем будут содержать немного разные данные.

Please correct it

**Comment by filimonov** [comment]
В первом случае репликацией занимается нижележащая таблица (таблица в которую будут записаны данные). 

Во втором случае репликацией занимается сам Distributed (а не нижележащая таблица). 

Если есть идеи как написать это понятнее - можно прислылать поправки к документации, это не сложно: 

![2020-11-26_11-44](https://user-images.githubusercontent.com/1549571/100341443-da7f0480-2fdc-11eb-9165-05691d6c4748.png)

**Comment by AlexProfi** [comment]
если используется zookeeper то нужно использовать true значение? ведь таблица через него реплицируется?

**Comment by den-crane** [comment]
true -- репликация реализуется в Replicated движке internally
false -- репликация реализуется в Distributed движке

**Comment by AlexProfi** [comment]
> true -- репликация реализуется в Replicated движке internally
> false -- репликация реализуется в Distributed движке

Так понятнее, спасибо))))
