### ISSUE TITLE
alias a constant the same as partition column name cause where statement ignored

### ISSUE THREAD

**Issue by undeflife** [ClickHouse/ClickHouse#17461]
* Which ClickHouse server version to use
20.10.2.20
* `CREATE TABLE` statements for all tables involved
```sql
 CREATE TABLE service_events
(
    `ldate` Date,
    `event_type` String
)
ENGINE = MergeTree()
PARTITION BY toYYYYMM(ldate)
ORDER BY ldate
SETTINGS index_granularity = 8192 
```
```sql
CREATE TABLE events_all
(
    `ldate` Date,
    `event_type` String
)
ENGINE = Distributed('shard2-repl1', 'default', 'service_events', rand())
```
* Queries to run that lead to unexpected result
```sql
SELECT count(1)
FROM events_all
```
┌─count(1)─┐
 │   176856        │
└──────┘

```sql
SELECT count(1)
FROM events_all
WHERE ldate = '2020-11-01'
```
┌─count(1)─┐
│        0               │
└──────┘

```sql
SELECT
    '2020-11-01' AS ldate,
    count(1)
FROM events_all
WHERE ldate = '2020-11-01'
```
┌─ldate──────┬─count(1)─┐
│ 2020-11-01                │   176856        │
└─────────┴──────┘

**Comment by den-crane** [comment]
Because expr. aliases are global in CH, you can use them in any section, where, order by , group by

https://clickhouse.tech/docs/en/sql-reference/syntax/#syntax-expression_aliases

WA `events_all.ldate = '2020-11-01'` :
```sql
SELECT
    '2020-11-01' AS ldate,
    count(1)
FROM events_all
WHERE events_all.ldate = '2020-11-01'
```
