### ISSUE TITLE
ReplaceMerge Tree 

### ISSUE THREAD

**Issue by sanjaypocket52** [ClickHouse/ClickHouse#17465]
Hi Team,

I have mysql db and i have port to CH by cron job with ReplcaeMerge Tree.

if mysql row any column change with int/float same will be merge into same row in CH.
incase change in string column mysql. IN CH same primary key duplicate row will create. (n number of time chnage in string column mysql n row created in CH with same primary key)

Please any clue to solve this one issue.

**Comment by sanjaypocket52** [comment]
Please anyone have some idea.

**Comment by sanjaypocket52** [comment]
Please find example below on my data. After optimisation merging is not happening.

OPTIMIZE TABLE users_user FINAL DEDUPLICATE

OPTIMIZE TABLE users_user FINAL DEDUPLICATE

Ok.

0 rows in set. Elapsed: 0.129 sec. 

select id,email from users_user where id = 101346

SELECT 
    id,
    email
FROM users_user
WHERE id = 101346

┌─────id─┬─email─────────────────┐
│ 101346 │ dsfsf@hgdfss.com      │
│ 101346 │ sdfvdshfsv@hgdfss.com │
└────────┴───────────────────────┘

2 rows in set. Elapsed: 0.003 sec. Processed 4.24 thousand rows, 457.93 KB (1.53 million rows/s., 165.20 MB/s.) 

ClickHouse client version 20.9.2.20

**Comment by den-crane** [comment]
Please show the output `select id,email, _part from users_user where id = 101346`

and output of `show create table users_user`

and output of 
```
set optimize_throw_if_noop=1;
OPTIMIZE TABLE users_user FINAL
```



https://clickhouse.tech/docs/en/engines/table-engines/mergetree-family/replacingmergetree/
_Thus, ReplacingMergeTree is suitable for clearing out duplicate data in the background in order to save space, but it doesn’t guarantee the absence of duplicates._

**Comment by sanjaypocket52** [comment]
Hi Den

when i removed from order (email,username) its works fine.

`CREATE TABLE users_user
(
    `id` UInt64,
    `created_at` DateTime,
    `updated_at` DateTime,
    `username` FixedString(100),
    `password` Nullable(FixedString(1000)),
    `state` Nullable(FixedString(100)),
    `mobile_no` FixedString(25),
    `mobile_verified` Nullable(Int8),
    `email` FixedString(100),
    `email_verified` Nullable(Int8),
    `signup_promo_code` Nullable(FixedString(100)),
    `signup_ip` Nullable(FixedString(100)),
    `signup_user_agent` Nullable(String),
    `is_app_installed` Nullable(Int8),
    `blocked` Nullable(Int8),
    `test_user` Nullable(Int8),
    `client_referrer_id` Nullable(Int64),
    `user_unique_id` Nullable(FixedString(100))
)
ENGINE = ReplacingMergeTree(id)
PARTITION BY tuple()
PRIMARY KEY id
ORDER BY (id, **username, mobile_no, email**)`

this thing i dit not understand that what is relationship between replacingMerge tree id with ORDER BY (id, **username, mobile_no, email**)` 

if i removed from order 'username, mobile_no, email' then it works fine.

**Comment by den-crane** [comment]
https://clickhouse.tech/docs/en/engines/table-engines/mergetree-family/replacingmergetree/

_The engine differs from MergeTree in that it removes duplicate entries with the same sorting key value._

ORDER BY table section defines the KEY which used to IDENTIFY the uniq rows -- sort of PRIMARY KEY.

**Comment by den-crane** [comment]
note for myself:  Need to emphasize diff order_by VS primary_key in the doc.

**Comment by sanjaypocket52** [comment]
Thanks Dane
