### ISSUE TITLE
Import to CSV - How to escape LINE FEED

### ISSUE THREAD

**Issue by XavierQuiniou** [ClickHouse/ClickHouse#17497]
Can't import CSV file when a (string) field contains LF.

### Case
prostgreSQL - Table system pg_stat_statements ( execution statistics of SQL statements executed by  server )

We want copy its content to CH. `query` column  stores texts of statements.

### Problem 
Some of SQL statements  are splitted by LF.

When generating CSV file to import in CH, lines are so splitted. 
Ex. (separator is '|") :
<pre>
"...|"SELECT 
     ...
     relid,                         --  - long
     schemaname,           --  - string
     relname,                   --  - string
     ...
     tidx_blks_read,          --  - long
     tidx_blks_hit             --  - long
FROM  pg_statio_all_tables"|3|...|....
</pre>
CH complains : `Cannot parse input: expected | before: ...`
We hoped that CH would continue to read from the first delimiter (double) quote to the other one.

It would be nice not to have to substitute `LF `for `<LF>` (for example).

**Comment by den-crane** [comment]
You should use "with csv force quote *;"

```

COPY (select * from crash_test) TO STDOUT  with csv force quote *;

COPY (select * from crash_test) TO PROGRAM 'clickhouse-client --query="INSERT INTO crash_test FORMAT CSV"' with csv force quote *;

```

**Comment by XavierQuiniou** [comment]
I'm using CLICKHOUSE4J (cc.blynk.clickhouse)
It's based upon HTTP client.
I proceed like that :
<pre> 
String sql = "INSERT INTO <i>my-base.my-table</i> FORMAT CSV settings format_csv_delimiter='|'";
copyManager.copyToDb(sql, <i>my-file</i>);
</pre>
How to place with <tt>csv force quote *;</tt>  ? As a setting ?

**Comment by den-crane** [comment]
@XavierQuiniou it's about PG 
```
psql: COPY (select * from crash_test) TO STDOUT  with csv force quote *;
```

**Comment by XavierQuiniou** [comment]
Do I understand that we can not use this feature, when writing sql statement : INSERT INTO ... ?

**Comment by den-crane** [comment]
I do.

I'll try to explain. **The problem is not related to CH!!!!!**
CSV format defines that **ROWS**!!! are separated by new_line character. For multiline ROWS they MUST BE surrounded by " (double quotes) otherwise it's impossible to distinguish rows.

Here is an example:

```
very
long 
row
```
VS
```
"very
long 
row"
```

PG allows you to surrounded long STRING values by " in the copy command by "with csv force quote *;"
