### ISSUE TITLE
Announcement: removal of unsupported documentation languages.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#17508]
The documentation in "tr" and "fa" languages was generated by machine translation with a hope that someone will edit and support it. It never happened. Now it represents a dead material that has negative value.

If there will be no objections, it will be removed on 31th Dec 2020.

**Comment by l1t1** [comment]
the Chinese document has similar problem, could you mark the  machine translation parts?

**Comment by alexey-milovidov** [comment]
Chinese is actually the most active after english along with Russian.

I personally do not like machine translation at all - I think it was a terrible idea to add it. But for Chinese there is a chance to make the translation normal.

PS. It should be already marked in metadata at the beginning of .md files... but I feel it is mixed up.

**Comment by alexey-milovidov** [comment]
Continuation: #20972
