### ISSUE TITLE
CREATE TABLE with INDEX failed with server version 20.10.4 revision 54441

### ISSUE THREAD

**Issue by Grian** [ClickHouse/ClickHouse#17519]
**How to reproduce**
house -m
ClickHouse client version 18.16.1.
Connecting to database test_gg at click.test.int:9000 as user gg.
Connected to ClickHouse server version 20.10.4 revision 54441.
```
rc1a-kzg74htbfsr9vvhw.mdb.yandexcloud.net :) CREATE TABLE IF NOT EXISTS `ord1`                                                    (
:-]         `10_1` UInt32,
:-]         INDEX b (`10_28`) TYPE minmax GRANULARITY 1024,
:-]         `10_28` Date
:-] ) ENGINE=MergeTree()
:-] ORDER BY `10_1`;

Syntax error: failed at position 86 (line 3, col 27):

CREATE TABLE IF NOT EXISTS `ord1` (
        `10_1` UInt32,
        INDEX b (`10_28`) TYPE minmax GRANULARITY 1024,
        `10_28` Date
) ENGINE=MergeTree()
ORDER BY `10_1`;

Expected one of: token, ClosingRoundBracket, Comma, DEFAULT, MATERIALIZED, ALIAS, COMMENT
```

**Expected behavior**
lhouse -m
```
ClickHouse client version 20.5.2.7 (official build).
Connecting to database test_gg at 127.1:9000 as user gg.
Connected to ClickHouse server version 20.5.2 revision 54435.

u28.ru-central1.internal :) CREATE TABLE IF NOT EXISTS `ord1` (
:-]         `10_1` UInt32,
:-]         INDEX b (`10_28`) TYPE minmax GRANULARITY 1024,
:-]         `10_28` Date
:-] ) ENGINE=MergeTree()
:-] ORDER BY `10_1`;

CREATE TABLE IF NOT EXISTS ord1
(
    `10_1` UInt32,
    `10_28` Date,
    INDEX b `10_28` TYPE minmax GRANULARITY 1024
)
ENGINE = MergeTree()
ORDER BY `10_1`

Ok.
```

**Comment by Grian** [comment]
**With more recent client it working:**
ClickHouse client version 20.5.2.7 (official build).
Connecting to database test_gg at click.test.int:9000 as user gg.
Connected to ClickHouse server version 20.10.4 revision 54441.

ClickHouse client version is older than ClickHouse server. It may lack support for new features.

rc1a-kzg74htbfsr9vvhw.mdb.yandexcloud.net :) CREATE TABLE IF NOT EXISTS `ord1` (
:-]         `10_1` UInt32,
:-]         INDEX b (`10_28`) TYPE minmax GRANULARITY 1024,
:-]         `10_28` Date
:-] ) ENGINE=MergeTree()
:-] ORDER BY `10_1`;

CREATE TABLE IF NOT EXISTS ord1
(
    `10_1` UInt32,
    `10_28` Date,
    INDEX b `10_28` TYPE minmax GRANULARITY 1024
)
ENGINE = MergeTree()
ORDER BY `10_1`

Ok.

0 rows in set. Elapsed: 0.028 sec.

**Comment by alexey-milovidov** [comment]
Old client does not support INDEX.
