### ISSUE TITLE
Complete quoting for parameters of some CMake commands

### ISSUE THREAD

**Issue by elfring** [ClickHouse/ClickHouse#17537]
Some parameters (like “[`${CMAKE_CURRENT_BINARY_DIR}/clickhouse-server`](https://github.com/ClickHouse/ClickHouse/blob/0b6f5c75b953f2cd32eddf4a463ed50c0919a7d9/programs/CMakeLists.txt#L250 "Update candidate")”) are passed to CMake commands in your build scripts without enclosing them by quotation marks. I see that these places will result in build difficulties if the contents of the used variables will contain special characters like semicolons.

I would recommend to apply [advices from the software documentation](https://cmake.org/cmake/help/v3.19/manual/cmake-language.7.html#lists "Description for CMake lists").

**Comment by filimonov** [comment]
@elfring may be you can collaborate and just send a PR with fixes?
