### ISSUE TITLE
Function `byteSize`

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#17540]
The function should return an estimate of uncompressed byte size of its arguments in memory.
E.g. for UInt32 argument it will return constant 4, for String argument - the string length + 9.
The function can take multiple arguments. The typical application is `byteSize(*)`.

**Use case**
Suppose you have a service that stores data for multiple clients in one table. Users will pay per data volume. So, you need to implement accounting of users data volume. The function will allow to calculate the data size on per-row basis.

**Comment by pingyu** [comment]
I'd like to have a try.
Would you please assign to me ? @alexey-milovidov

**Comment by alexey-milovidov** [comment]
@pingyu Ok, this task is yours :+1:
