### ISSUE TITLE
Try to replace Ryu with Dragonbox

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#17578]
Someone on the internet said that Dragonbox library is faster than Ryu:
https://github.com/jk-jeon/dragonbox
https://github.com/abolz/Drachennest

We are currently using modified version of Ryu for Float to String conversions.

**Comment by l1t1** [comment]
isn't Ryu good enough for clickhouse?

**Comment by alexey-milovidov** [comment]
It's good enough, but in ClickHouse there is a principle to choose the best available option for performance.

**Comment by l1t1** [comment]
about speed, I found this 
https://arxiv.org/search/cs?searchtype=author&query=Lemire%2C+D

**Comment by alexey-milovidov** [comment]
You posted the link to all the works by Daniel Lemire. I'm trying to follow his works, blog and repositories :)
For example, recentry he has a work about fast float parsing (but this issue is about fast float formatting - the inverse operation).

For float parsing there is a PR in progress: #16787

**Comment by l1t1** [comment]
Daniel also contributed codes for clickhouse. great
