### ISSUE TITLE
format error, argument not found

### ISSUE THREAD

**Issue by thyn** [ClickHouse/ClickHouse#17613]
(you don't have to strictly follow this form)

**Describe the bug**
a lot of background logs of thar error, constantly, on different tables

**How to reproduce**
from 20.3 -20.11.4.13

**Expected behavior**
some error log which I can't see I think

**Error message and/or stacktrace**
2020.11.30 03:21:19.382728 [ 58 ] {} <Error>tracking.s_mergetrackingresult: DB::BackgroundProcessingPoolTaskResult DB::StorageReplicatedMergeTree::queueTask(): std::exception. Code: 1001, type: fmt::v7::format_error, e.what() = argument not found, Stack trace (when copying this message, always include the lines below):

0. fmt::v7::format_error::format_error(char const*) @ 0x7b3c899 in /usr/bin/clickhouse
1. fmt::v7::detail::error_handler::on_error(char const*) @ 0x10c4b280 in /usr/bin/clickhouse
2. char const* fmt::v7::detail::parse_replacement_field<char, fmt::v7::detail::format_handler<fmt::v7::detail::arg_formatter<fmt::v7::detail::buffer_appender<char>, char>, char, fmt::v7::basic_format_context<fmt::v7::detail::buffer_appender<char>, char> >&>(char const*, char const*, fmt::v7::detail::format_handler<fmt::v7::detail::arg_formatter<fmt::v7::detail::buffer_appender<char>, char>, char, fmt::v7::basic_format_context<fmt::v7::detail::buffer_appender<char>, char> >&) @ 0x7b408ca in /usr/bin/clickhouse
3. fmt::v7::basic_format_context<fmt::v7::detail::buffer_appender<char>, char>::iterator fmt::v7::vformat_to<fmt::v7::detail::arg_formatter<fmt::v7::detail::buffer_appender<char>, char>, char, fmt::v7::basic_format_context<fmt::v7::detail::buffer_appender<char>, char> >(fmt::v7::detail::arg_formatter<fmt::v7::detail::buffer_appender<char>, char>::iterator, fmt::v7::basic_string_view<char>, fmt::v7::basic_format_args<fmt::v7::basic_format_context<fmt::v7::detail::buffer_appender<char>, char> >, fmt::v7::detail::locale_ref) @ 0x7b3ca8c in /usr/bin/clickhouse
4. fmt::v7::detail::vformat(fmt::v7::basic_string_view<char>, fmt::v7::format_args) @ 0x10c4b326 in /usr/bin/clickhouse
5. DB::ReplicatedMergeTreeQueue::shouldExecuteLogEntry(DB::ReplicatedMergeTreeLogEntry const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, DB::MergeTreeDataMergerMutator&, DB::MergeTreeData&, std::__1::lock_guard<std::__1::mutex>&) const @ 0xe23c028 in /usr/bin/clickhouse
6. DB::ReplicatedMergeTreeQueue::selectEntryToProcess(DB::MergeTreeDataMergerMutator&, DB::MergeTreeData&) @ 0xe23f034 in /usr/bin/clickhouse7. DB::StorageReplicatedMergeTree::queueTask() @ 0xdf16b04 in /usr/bin/clickhouse
8. DB::BackgroundProcessingPool::workLoopFunc() @ 0xe05e3b3 in /usr/bin/clickhouse9. ? @ 0xe05eef1 in /usr/bin/clickhouse
10. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x7b7293d in /usr/bin/clickhouse
11. ? @ 0x7b76463 in /usr/bin/clickhouse12. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
13. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
 (version 20.11.4.13 (official build))

**Comment by alexey-milovidov** [comment]
The bug was introduced here: https://github.com/ClickHouse/ClickHouse/pull/16555/files#diff-60ac1b8c4ea5fc12319121f5bc970ed065b4cffd2ffd16e81f815ae80a75386eR1108
CC @tavplubix

**Comment by thyn** [comment]
is it possible to apply that fix to 20.11?

**Comment by alexey-milovidov** [comment]
Yes, it will be backported.
