### ISSUE TITLE
There is no way to remove a dictionary without a restart

### ISSUE THREAD

**Issue by SaltTan** [ClickHouse/ClickHouse#1761]
Or is there?

**Comment by filimonov** [comment]
May be that will work?
```sql
SYSTEM RELOAD DICTIONARIES
```

**Comment by SaltTan** [comment]
No, it does not

**Comment by blinkov** [comment]
It has been supported this summer in #2779

**Comment by SaltTan** [comment]
Unfortunately it is not fully supported.
If a dictionary is described in a separate file, and that file gets deleted, the dictionary will not be removed.

**Comment by SaltTan** [comment]
Deleting a dictionary file works in 19.13

**Comment by SulaymonHursanov** [comment]
drop dictionary dict_name; 
-- works on version 19.17
