### ISSUE TITLE
"OR" operator in "ON" section for join

### ISSUE THREAD

**Issue by ilejn** [ClickHouse/ClickHouse#17612]
**Current behaviour**

```
SELECT *
FROM 
(
    SELECT *
    FROM test_data
) AS t1
ANY INNER JOIN 
(
    SELECT *
    FROM test_data_2
) AS t2 ON (t1.id = t2.id) OR (t1.val = t2.val)
LIMIT 10

Received exception from server (version 20.5.2):

Code: 403. DB::Exception: Received from localhost:9000. DB::Exception: Invalid expression for JOIN ON. Expected equals expression, got (id = t2.id) OR (val = t2.val). Supported syntax: JOIN ON Expr([table.]column, ...) = Expr([table.]column, ...) [AND Expr([table.]column, ...) = Expr([table.]column, ...) ...].

```
**Desired behaviour**

Act according to SQL standard, support boolean logic, support all kinds of joins.

**Comment by ilejn** [comment]
I am working on it. 
Started from Hash joins.
Suggestions are highly appreciated.

**Comment by alexey-milovidov** [comment]
So, we have to build multiple hash tables to support OR?

**Comment by ilejn** [comment]
> So, we have to build multiple hash tables to support OR?

Exactly.
One for disjunct.

**Comment by alexey-milovidov** [comment]
Ok.

**Comment by ilejn** [comment]
The issue is **partially** implemented by https://github.com/ClickHouse/ClickHouse/pull/21320
Queries with ON conditions like _t1.id = t2.id OR t1.val = t2.val_ are supported, conditions _t1.id = t2.id OR (t1.val = t2.val AND t1.val1=t2.val1)_ are supported, while conditions like _t1.id = t2.id AND (t1.val = t2.val OR t1.val1=t2.val1)_ are not supported.
Speaking more formally, a condition must be in Disjunctive normal form. 
Normalization is excluded from the PR and will come later.
Note, that this is about conditions based on fields from joined tables. Filter conditions are different. For example, ON condition like _t1.id = t2.id AND (t1.val = 'constant string one' OR t1.val = 'constant string two')_ is perfectly legit.

**Comment by griguolcomerranas** [comment]
> The issue is **partially** implemented by #21320 Queries with ON conditions like _t1.id = t2.id OR t1.val = t2.val_ are supported, conditions _t1.id = t2.id OR (t1.val = t2.val AND t1.val1=t2.val1)_ are supported, while conditions like _t1.id = t2.id AND (t1.val = t2.val OR t1.val1=t2.val1)_ are not supported. Speaking more formally, a condition must be in Disjunctive normal form. Normalization is excluded from the PR and will come later. Note, that this is about conditions based on fields from joined tables. Filter conditions are different. For example, ON condition like _t1.id = t2.id AND (t1.val = 'constant string one' OR t1.val = 'constant string two')_ is perfectly legit.

Does [#21320](https://github.com/ClickHouse/ClickHouse/pull/21320) cover JOIN ON with OR where the OR are checks for NULL ??
Null is not exactly a constant string but I had hopes on this to work.
I tested [v21.11.1.8636-prestable](https://github.com/ClickHouse/ClickHouse/releases/tag/v21.11.1.8636-prestable) release where [#21320](https://github.com/ClickHouse/ClickHouse/pull/21320) is included but I still get this error in my tests:

_SQL Error [1002]: ClickHouse exception, code: 1002, host: xxxxxxxxx, port: 8123; Code: 403. DB::Exception: Unsupported JOIN ON conditions. Unexpected '(`$temp0` = Calculation_812899764915064837) OR ((`$temp0` IS NULL) AND (Calculation_812899764915064837 IS NULL))': While processing (`$temp0` = Calculation_812899764915064837) OR ((`$temp0` IS NULL) AND (Calculation_812899764915064837 IS NULL)). (INVALID_JOIN_ON_EXPRESSION) (version 21.11.1.8636 (official build))_

The query works fine if I remove the OR conditions from the join.
Thanks!

**Comment by vdimir** [comment]
@griguolcomerranas could you please provide query example and describe expected behavior?

**Comment by griguolcomerranas** [comment]
Yes, basically the join keys can have "null" value and the join is to be done where the fields match but also include the case where the fields are null. Therefore the OR condition is added.

I found a previously reported Issue [#22509](https://github.com/ClickHouse/ClickHouse/issues/22509), which shows an example exactly like mine.

To be honest the null values are not interesting for my usecase but the query is created from the Tableau connector and it doesn't work, making my dashboard useless. Maybe what should be improved is the query that comes out of the Tableau connector. I am nor sure the null conditions are really needed at all.

**Comment by griguolcomerranas** [comment]
Hello again.
Everything seems to be working fine with the  [new v1.0.0 stable release of the Altinity Tableau connector](https://github.com/Altinity/clickhouse-tableau-connector-odbc/releases/tag/v1.0.0).
So, probably no need or big rush  to fix the JOIN ON with OR and NULL conditions right now.
Thanks a lot for your help!

**Comment by jnd77** [comment]
Hello.

I was running the example from the documentation:

```
CREATE TABLE t1 (`a` Int64, `b` Int64) ENGINE = MergeTree() ORDER BY a;
CREATE TABLE t2 (`key` Int32, `val` Int64) ENGINE = MergeTree() ORDER BY key;
INSERT INTO t1 SELECT number as a, -a as b from numbers(5);
INSERT INTO t2 SELECT if(number % 2 == 0, toInt64(number), -number) as key, number as val from numbers(5);
SELECT a, b, val FROM t1 INNER JOIN t2 ON t1.a = t2.key OR t1.b = t2.key;
```

Everything works as expected.
However when running this query:
```
SELECT a, b, val FROM t1 INNER JOIN t2 ON t1.a = t2.key OR t1.b = 0
```

I run into the following exception:

```
DB::Exception: Cannot get JOIN keys from JOIN ON section: '(a = key) OR (b = 0)'. (INVALID_JOIN_ON_EXPRESSION)
```

Is it expected ? Thank you.

**Comment by ilejn** [comment]
> Is it expected ?

Hello @jnd77 , yes, it is expected. 

"SELECT a, b, val FROM t1 INNER JOIN t2 ON  t1.b = 0;" does not work and "SELECT a, b, val FROM t1 INNER JOIN t2 ON t1.a = t2.key OR t1.b = 0" does not work therefore.

We have two joining conditions here
The left side  "t1.a = t2.key" is valid, it is enough to establish a relation between two tables
The right side  "t1.b = 0" is not valid, it is not enough to establish a relation between two tables

Note, that t1.a = t2.key AND t1.b = 0 is a single joining condition and it works Ok.

**Comment by jnd77** [comment]
Thanks @ilejn, it makes sense. Sorry I was actually trying to simplify my use case, but went too far.
I was trying to join the tables when keys are identical (including the case of NULL values), similarly to what @griguolcomerranas  was asking earlier in the thread.

"SELECT a, b, val FROM t1 INNER JOIN t2 ON t1.a = t2.key OR (t1.a IS NULL and t2.key IS NULL)"

**Comment by rcolle** [comment]
I've found a workaround for this by testing the equality of the null attribute:
```sql
SELECT a, b, val
FROM t1 INNER JOIN t2
ON t1.b = t2.key OR 
      (isNull(t1.b) = isNull(t2.key) AND t1.b IS NULL);
```

@ilejn do you have any idea of the performance impact of this (notably the last `AND`)? Would it behave similarly to @jnd77 's statement?

**Comment by ilejn** [comment]
@rcolle , very interesting.
I cannot answer off the top of my head.
@vdimir , could you help, please?

**Comment by vdimir** [comment]
Queries
```sql
SELECT a, b, val
FROM t1 INNER JOIN t2
ON t1.b = t2.key OR 
      (isNull(t1.b) = isNull(t2.key) AND t1.b IS NULL);
```
and 
```sql
SELECT a, b, val
FROM t1 INNER JOIN t2
ON t1.b = t2.key OR 
      (isNull(t1.b) = isNull(t2.key));
```

Will provide different results because in second case it will join every non null value with every other non-null value, which is expensive and most likely not what you want to do.

As for  `(isNull(t1.b) = isNull(t2.key) AND t1.b IS NULL);`

I'd expect that query with condition on right-key (`(isNull(t1.b) = isNull(t2.key) AND t2.key IS NULL);`) be more efficient because it should reduce size of hash table, but I've tested it and it mostly the same, need to check how it works.

And the most efficient way to perform join considering nulls is to use just `AND`s, like
`ON COALESCE(t1.a, 0) = COALESCE(t2.key, 0) AND isNull(t1.a) == isNull(t2.key);`


<details>
<summary>testcase and results</summary>

```sql
DROP TABLE IF EXISTS t1;
DROP TABLE IF EXISTS t2;

CREATE TABLE t1 (`a` Nullable(Int64), `b` Int64) ENGINE = MergeTree() ORDER BY b;
CREATE TABLE t2 (`key` Nullable(Int32), `val` Int64) ENGINE = MergeTree() ORDER BY val;

INSERT INTO t1
SELECT
    if(
        number % 12 == 0,
        NULL,
        number
    ) as a, -number as b
FROM numbers(100000);

INSERT INTO t2
SELECT
    if(
        number % 9 == 0,
        NULL,
        if(number % 2 == 0, toInt64(number), -number)
     ) as key,
     number as val
FROM numbers(100000);

-- time: 11.473
SELECT count()
FROM t1 INNER JOIN t2
ON t1.a = t2.key OR
      (isNull(t1.a) = isNull(t2.key) AND t1.a IS NULL);

-- time: 11.497
SELECT count()
FROM t1 INNER JOIN t2
ON t1.a = t2.key OR
      (isNull(t1.a) = isNull(t2.key) AND t2.key IS NULL);

-- time: 11.359
SELECT count()
FROM t1 INNER JOIN t2
ON t1.a = t2.key OR
      (isNull(t1.a) = isNull(t2.key) AND t2.key IS NULL AND t1.a IS NULL);

-- time: 2.233
SELECT count()
FROM t1 INNER JOIN t2
ON COALESCE(t1.a, 0) = COALESCE(t2.key, 0) AND isNull(t1.a) == isNull(t2.key);
```

</details>

**Comment by rcolle** [comment]
Thanks a lot @vdimir , `COALESCE` is in fact exactly what we were looking for! Glad to see it's also the most efficient.
Thanks again to both @ilejn and yourself for the help.

**Comment by SharonCastel** [comment]
Thanks for checking @vdimir!
Sorry for my delayed response... covid just got me..
And last Sorry for misleading you by calling it tables, actually its virtual because those are base on the cte results.
I will check the explain on my query as well thanks!
Unfortunately I cannot share the exact query, but it goes like:
```
with
  A as (select...),
  B as (select....),
  C as (select....)
 
 select A.BLA, B.BLA, C.BLA
from A
FULL OUTER JOIN B ON A.first_customer_number=B.first_customer_number AND A.second_customer_number=B.second_customer_number
FULL OUTER JOIN C ON
(A.first_customer_number=C.first_customer_number AND A.second_customer_number=C.second_customer_number)
OR
(C.first_customer_number=B.first_customer_number AND C.second_customer_number=B.second_customer_number)

**Comment by AlekseiSaff** [comment]
May I ask, what's wrong with that condition?

`ON JSONExtractUInt(opp.data, 'strategy_order_id') = order_resp.oid and JSONExtractUInt(JSONExtractString(opp.data, 'app'), 'start_time') = order_resp.start_time
    and (lower(JSONExtractString(opp.data, 'hedge_order')) = lower(arrayElement(splitByChar('_',order_resp.response_type),1))
            or (JSONExtractString(opp.data, 'hedge_order') = 'New' and (order_resp.response_type = 'ORDER_ERROR' or order_resp.response_type = 'RMS_REJECT'))
            or (JSONExtractString(opp.data, 'hedge_order') = 'Cancel' and order_resp.response_type = 'CANCEL_ORDER_REJECT')
            or (JSONExtractString(opp.data, 'hedge_order') = 'New' and JSONExtractString(opp.data, 'hedge_order_type') = 'IOC' and order_resp.response_type = 'CANCEL_ORDER_CONFIRM')
        )`
        
getting: DB::Exception: Unsupported JOIN ON conditions. Unexpected '

**Comment by SharonCastel** [comment]
What are opp and order_resp? Tables or cte aliases?

**Comment by AlekseiSaff** [comment]
Opp is the main table alias
Order_resp is the alias of join select

**Comment by vdimir** [comment]
@AlekseiSaff you may try it with `SET allow_experimental_analyzer = 1`

**Comment by AlekseiSaff** [comment]
nope. now it's saying 
``Received exception from server (version 22.12.2):
Code: 403. DB::Exception: Received from localhost:9000. DB::Exception: JOIN  lightlog.data__lt_blackbird_hedger_order AS opp ALL LEFT JOIN (SELECT JSONExtractUInt(JSONExtractString(data, 'app'), 'start_time'), JSONExtractUInt(data, 'orderID'), replaceAll(JSONExtractString(data, 'ors_blocked_reason'), 'not blocked', '-'), JSONExtractString(data, 'response_Type') FROM lightlog.data__lt_osprey_shm_response) AS order_resp ON (JSONExtractUInt(data, 'strategy_order_id') = oid) AND (JSONExtractUInt(JSONExtractString(data, 'app'), 'start_time') = start_time) AND ((lower(JSONExtractString(data, 'hedge_order')) = lower(splitByChar('_', response_type)[1])) OR ((JSONExtractString(data, 'hedge_order') = 'New') AND ((response_type = 'ORDER_ERROR') OR (response_type = 'RMS_REJECT'))) OR ((JSONExtractString(data, 'hedge_order') = 'Cancel') AND (response_type = 'CANCEL_ORDER_REJECT')) OR ((JSONExtractString(data, 'hedge_order') = 'New') AND (JSONExtractString(data, 'hedge_order_type') = 'IOC') AND (response_type = 'CANCEL_ORDER_CONFIRM'))) join expression contains column from left and right table. (INVALID_JOIN_ON_EXPRESSION)

2b466ca30a6a :)

**Comment by vdimir** [comment]
@AlekseiSaff try to rewrite join condition to have `OR` on the top level (using https://en.wikipedia.org/wiki/De_Morgan%27s_laws). So condition should looks like `(cond1 AND cond2 AND cond3) OR (cond4 AND cond5 AND cond6) OR (cond7 AND cond8 and cond9)` (some `cond`s can be the same)

Particular example:

```sql

-- error:

SELECT *
FROM (SELECT 1 AS start_time, 1 AS oid, '1_1' AS response_type) AS order_resp
LEFT JOIN (SELECT '{"strategy_order_id":1, "app":1}' AS data) AS opp
ON
    (JSONExtractUInt(data, 'strategy_order_id') = oid) AND (JSONExtractUInt(JSONExtractString(data, 'app'), 'start_time') = start_time)
    AND (
            (lower(JSONExtractString(data, 'hedge_order')) = lower(splitByChar('_', response_type)[1]))
        OR ((JSONExtractString(data, 'hedge_order') = 'New') AND ((response_type = 'ORDER_ERROR') OR (response_type = 'RMS_REJECT')))
        OR ((JSONExtractString(data, 'hedge_order') = 'Cancel') AND (response_type = 'CANCEL_ORDER_REJECT'))
        OR ((JSONExtractString(data, 'hedge_order') = 'New') AND (JSONExtractString(data, 'hedge_order_type') = 'IOC') AND (response_type = 'CANCEL_ORDER_CONFIRM')))
;


-- ok:
SELECT *
FROM (SELECT 1 AS start_time, 1 AS oid, '1_1' AS response_type) AS order_resp
LEFT JOIN (SELECT '{"strategy_order_id":1, "app":1}' AS data) AS opp
ON
    ((((JSONExtractUInt(data, 'strategy_order_id') = oid) AND (JSONExtractUInt(JSONExtractString(data, 'app'), 'start_time') = start_time)) as cond1 ) AND (lower(JSONExtractString(data, 'hedge_order')) = lower(splitByChar('_', response_type)[1])))
    OR (cond1 AND ((JSONExtractString(data, 'hedge_order') = 'New') AND ((response_type = 'ORDER_ERROR') OR (response_type = 'RMS_REJECT'))))
    OR (cond1 AND ((JSONExtractString(data, 'hedge_order') = 'Cancel') AND (response_type = 'CANCEL_ORDER_REJECT')))
    OR (cond1 AND ((JSONExtractString(data, 'hedge_order') = 'New') AND (JSONExtractString(data, 'hedge_order_type') = 'IOC') AND (response_type = 'CANCEL_ORDER_CONFIRM')))
;
```

**Comment by AlekseiSaff** [comment]
still no
cannot get JOIN keys. (INVALID_JOIN_ON_EXPRESSION)

**Comment by vdimir** [comment]
@AlekseiSaff could you, please, provide minimal reproducible example? https://fiddle.clickhouse.com/

**Comment by AlekseiSaff** [comment]
@vdimir have you received fiddle link? I thought I posted it here

**Comment by vdimir** [comment]
@AlekseiSaff no, send it again, pelase

**Comment by AlekseiSaff** [comment]
weird, 
https://fiddle.clickhouse.com/7bf172cc-ad8b-48d7-bd71-37d855231679

**Comment by AlekseiSaff** [comment]
hi @vdimir any ideas. is it wrong on our side? which I can't get as seems OR clause is valid. or it's a bug in CH?

**Comment by SharonCastel** [comment]
I had a similar issue also with json and cte aliases and the or condition on join didn't work for me either, finally I rewrite the query in another way with union instead

**Comment by ilejn** [comment]
Hello @AlekseiSaff , as it is mentioned by @vdimir you have to have ORs at top level.
In your example it is not true.

What does not work
```
ON JSONExtractUInt(opp.data, 'strategy_order_id') = order_resp.oid
    and (lower(JSONExtractString(opp.data, 'hedge_order')) = lower(arrayElement(splitByChar('_',order_resp.response_type),1))
            or (JSONExtractString(opp.data, 'hedge_order') = 'New')
        )
;
```

What works

```
ON JSONExtractUInt(opp.data, 'strategy_order_id') = order_resp.oid
    and (lower(JSONExtractString(opp.data, 'hedge_order')) = lower(arrayElement(splitByChar('_',order_resp.response_type),1)))   
            or (JSONExtractUInt(opp.data, 'strategy_order_id') = order_resp.oid   and JSONExtractString(opp.data, 'hedge_order') = 'New')
;
```

It is how it is implemented.

**Comment by AlekseiSaff** [comment]
that past has no issues. 
the problem is with JOIN

`ON JSONExtractUInt(opp.data, 'strategy_order_id') = order_resp.oid and JSONExtractUInt(JSONExtractString(opp.data, 'app'), 'start_time') = order_resp.start_time
    and (lower(JSONExtractString(opp.data, 'hedge_order')) = lower(arrayElement(splitByChar('_',order_resp.response_type),1))
            or (JSONExtractString(opp.data, 'hedge_order') = 'New' and (order_resp.response_type = 'ORDER_ERROR' or order_resp.response_type = 'RMS_REJECT'))
            or (JSONExtractString(opp.data, 'hedge_order') = 'Cancel' and order_resp.response_type = 'CANCEL_ORDER_REJECT')
            or (JSONExtractString(opp.data, 'hedge_order') = 'New' and JSONExtractString(opp.data, 'hedge_order_type') = 'IOC' and order_resp.response_type = 'CANCEL_ORDER_CONFIRM')
        )`
        
        which I tried to optimize according to @vdimir , but still no luck

**Comment by AlekseiSaff** [comment]
https://fiddle.clickhouse.com/cbb86030-35d8-4c0a-8323-0c843b91667c

**Comment by ilejn** [comment]
@AlekseiSaff  this is exactly the part that has issues.

I've simplified your query
https://fiddle.clickhouse.com/8659ba2e-ae4a-401e-914d-cab762a361e8

Try to apply normalization (move OR to the top) and see that it works.
