### ISSUE TITLE
Error compiling llvm of Clickhouse version 20.6

### ISSUE THREAD

**Issue by marising** [ClickHouse/ClickHouse#17624]
My server doesn't connect https://chromium.googlesource.com, I don't know if it will affect the following llvm compilation errors.

[root@A03-R05-I46-164-035PF74 clickhouse]# git submodule update --init --recursive
Cloning into '/data1/home/lihaibo42/code/clickhouse/contrib/sentry-native/external/breakpad'...
fatal: unable to access 'https://chromium.googlesource.com/breakpad/breakpad.git/': Failed to connect to chromium.googlesource.com port 443: Connection timed out
fatal: clone of 'https://chromium.googlesource.com/breakpad/breakpad.git' into submodule path '/data1/home/lihaibo42/code/clickhouse/contrib/sentry-native/external/breakpad' failed
Failed to clone 'external/breakpad'. Retry scheduled
Cloning into '/data1/home/lihaibo42/code/clickhouse/contrib/sentry-native/external/third_party/lss'...
fatal: unable to access 'https://chromium.googlesource.com/linux-syscall-support/': Failed to connect to chromium.googlesource.com port 443: Connection timed out
fatal: clone of 'https://chromium.googlesource.com/linux-syscall-support' into submodule path '/data1/home/lihaibo42/code/clickhouse/contrib/sentry-native/external/third_party/lss' failed
Failed to clone 'external/third_party/lss'. Retry scheduled
Cloning into '/data1/home/lihaibo42/code/clickhouse/contrib/sentry-native/external/breakpad'...
fatal: unable to access 'https://chromium.googlesource.com/breakpad/breakpad.git/': Failed to connect to chromium.googlesource.com port 443: Connection timed out
fatal: clone of 'https://chromium.googlesource.com/breakpad/breakpad.git' into submodule path '/data1/home/lihaibo42/code/clickhouse/contrib/sentry-native/external/breakpad' failed
Failed to clone 'external/breakpad' a second time, aborting
Failed to recurse into submodule path 'contrib/sentry-native'

[root@A03-R05-I46-164-035PF74 clickhouse]# git diff
diff --git a/contrib/sentry-native b/contrib/sentry-native
--- a/contrib/sentry-native
+++ b/contrib/sentry-native
@@ -1 +1 @@
-Subproject commit f91ed3f95b5653f247189d720ab00765b4899d6f
+Subproject commit f91ed3f95b5653f247189d720ab00765b4899d6f-dirty

**Operating system**
root@c263d22b7bb4:/code/clickhouse/build# cat /etc/issue
Ubuntu 20.04.1 LTS \n \l

**Cmake version**
root@c263d22b7bb4:/code/clickhouse/build# cmake --version
cmake version 3.16.3
CMake suite maintained and supported by Kitware (kitware.com/cmake).

**Ninja version**
root@c263d22b7bb4:/code/clickhouse/build# ninja --version
1.10.0

**Compiler name and version**
g++-10

**Full cmake and/or ninja output**
[3948/8027] Building CXX object contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/CodeGenSchedule.cpp.o
FAILED: contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/CodeGenSchedule.cpp.o
/usr/bin/g++-10  -DSTD_EXCEPTION_HAS_STACK_TRACE=1 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Icontrib/llvm/llvm/utils/TableGen -I../contrib/llvm/llvm/utils/TableGen -I../contrib/sentry-native/include -Icontrib/llvm/llvm/include -I../contrib/llvm/llvm/include -isystem ../contrib/libcxx/include -isystem ../contrib/libcxxabi/include -isystem ../contrib/libunwind/include -isystem ../contrib/libc-headers/x86_64-linux-gnu -isystem ../contrib/libc-headers -fdiagnostics-color=always -std=c++2a -fsized-deallocation  -pipe -msse4.1 -msse4.2 -mpopcnt   -Wall  -Werror -w -fvisibility-inlines-hidden -Werror=date-time -std=c++11 -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-noexcept-type -Wdelete-non-virtual-dtor -fdiagnostics-color -ffunction-sections -fdata-sections -O2 -g -DNDEBUG -O3  -fno-pie   -D OS_LINUX -g0   -nostdinc++ -MD -MT contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/CodeGenSchedule.cpp.o -MF contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/CodeGenSchedule.cpp.o.d -o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/CodeGenSchedule.cpp.o -c ../contrib/llvm/llvm/utils/TableGen/CodeGenSchedule.cpp
In file included from ../contrib/libcxx/include/math.h:311,
                 from ../contrib/libcxx/include/stdlib.h:100,
                 from ../contrib/libcxx/include/cstdlib:85,
                 from ../contrib/libcxx/include/exception:81,
                 from ../contrib/libcxx/include/new:90,
                 from ../contrib/llvm/llvm/include/llvm/Support/Compiler.h:19,
                 from ../contrib/llvm/llvm/include/llvm/ADT/APInt.h:18,
                 from ../contrib/llvm/llvm/utils/TableGen/CodeGenSchedule.h:17,
                 from ../contrib/llvm/llvm/utils/TableGen/CodeGenSchedule.cpp:14:
../contrib/libcxx/include/type_traits: In instantiation of ‘struct std::__1::__decay<const llvm::APInt&, true>’:
../contrib/libcxx/include/type_traits:1347:94:   required from ‘struct std::__1::decay<const llvm::APInt&&>’
../contrib/libcxx/include/utility:392:16:   required by substitution of ‘template<class _Tuple, typename std::__1::enable_if<typename std::__1::conditional<(std::__1::__tuple_like_with_size<_Tuple, 2, typename std::__1::__uncvref<_Tp>::type>::value && (! std::__1::is_same<typename std::__1::decay<_Tp>::type, std::__1::pair<const llvm::Record*, llvm::OpcodeInfo> >::value)), std::__1::pair<const llvm::Record*, llvm::OpcodeInfo>::_CheckTupleLikeConstructor, std::__1::__check_tuple_constructor_fail>::type::__enable_implicit<_Tuple>(), bool>::type <anonymous> > std::__1::pair<const llvm::Record*, llvm::OpcodeInfo>::pair(_Tuple&&) [with _Tuple = const llvm::APInt&&; typename std::__1::enable_if<typename std::__1::conditional<(std::__1::__tuple_like_with_size<_Tuple, 2, typename std::__1::__uncvref<_Tp>::type>::value && (! std::__1::is_same<typename std::__1::decay<_Tp>::type, std::__1::pair<const llvm::Record*, llvm::OpcodeInfo> >::value)), std::__1::pair<const llvm::Record*, llvm::OpcodeInfo>::_CheckTupleLikeConstructor, std::__1::__check_tuple_constructor_fail>::type::__enable_implicit<_Tuple>(), bool>::type <anonymous> = <missing>]’
../contrib/llvm/llvm/utils/TableGen/CodeGenSchedule.cpp:374:69:   required from here
../contrib/libcxx/include/type_traits:1338:30: error: forming pointer to reference type ‘std::__1::remove_extent<const llvm::APInt&>::type’ {aka ‘const llvm::APInt&’}
 1338 |                      >::type type;
      |                              ^~~~
[4045/8027] Building CXX object contrib/flatbuffers/CMakeFiles/flatbuffers.dir/src/idl_parser.cpp.o

**Comment by filimonov** [comment]
1) llvm is an optional component, you can disable it with CMake flag
2) you trying to compile an obsolete version. Use 20.8 at least.

**Comment by helifu** [comment]
I have met the same problem and my env is: v20.8.7.15-lts + gcc-10.2.0.

`[ 56%] Building CXX object contrib/llvm/llvm/utils/TableGen/CMakeFiles/obj.llvm-tblgen.dir/CodeGenSchedule.cpp.o
In file included from /root/ClickHouse/contrib/libcxx/include/math.h:311,
                 from /root/ClickHouse/contrib/libcxx/include/stdlib.h:100,
                 from /root/ClickHouse/contrib/libcxx/include/cstdlib:85,
                 from /root/ClickHouse/contrib/libcxx/include/exception:81,
                 from /root/ClickHouse/contrib/libcxx/include/new:90,
                 from /root/ClickHouse/contrib/llvm/llvm/include/llvm/Support/Compiler.h:19,
                 from /root/ClickHouse/contrib/llvm/llvm/include/llvm/ADT/APInt.h:18,
                 from /root/ClickHouse/contrib/llvm/llvm/utils/TableGen/CodeGenSchedule.h:17,
                 from /root/ClickHouse/contrib/llvm/llvm/utils/TableGen/CodeGenSchedule.cpp:14:
/root/ClickHouse/contrib/libcxx/include/type_traits: In instantiation of ‘struct std::__1::__decay<const llvm::APInt&, true>’:
/root/ClickHouse/contrib/libcxx/include/type_traits:1347:94:   required from ‘struct std::__1::decay<const llvm::APInt&&>’
/root/ClickHouse/contrib/libcxx/include/utility:392:16:   required by substitution of ‘template<class _Tuple, typename std::__1::enable_if<typename std::__1::conditional<(std::__1::__tuple_like_with_size<_Tuple, 2, typename std::__1::__uncvref<_Tp>::type>::value && (! std::__1::is_same<typename std::__1::decay<_Tp>::type, std::__1::pair<const llvm::Record*, llvm::OpcodeInfo> >::value)), std::__1::pair<const llvm::Record*, llvm::OpcodeInfo>::_CheckTupleLikeConstructor, std::__1::__check_tuple_constructor_fail>::type::__enable_implicit<_Tuple>(), bool>::type <anonymous> > std::__1::pair<const llvm::Record*, llvm::OpcodeInfo>::pair(_Tuple&&) [with _Tuple = const llvm::APInt&&; typename std::__1::enable_if<typename std::__1::conditional<(std::__1::__tuple_like_with_size<_Tuple, 2, typename std::__1::__uncvref<_Tp>::type>::value && (! std::__1::is_same<typename std::__1::decay<_Tp>::type, std::__1::pair<const llvm::Record*, llvm::OpcodeInfo> >::value)), std::__1::pair<const llvm::Record*, llvm::OpcodeInfo>::_CheckTupleLikeConstructor, std::__1::__check_tuple_constructor_fail>::type::__enable_implicit<_Tuple>(), bool>::type <anonymous> = <missing>]’
/root/ClickHouse/contrib/llvm/llvm/utils/TableGen/CodeGenSchedule.cpp:374:69:   required from here
/root/ClickHouse/contrib/libcxx/include/type_traits:1338:30: error: forming pointer to reference type ‘std::__1::remove_extent<const llvm::APInt&>::type’ {aka ‘const llvm::APInt&’}
 1338 |                      >::type type;
      |                              ^~~~
make[2]: *** [contrib/llvm/llvm/utils/TableGen/CMakeFiles/obj.llvm-tblgen.dir/CodeGenSchedule.cpp.o] Error 1
make[1]: *** [contrib/llvm/llvm/utils/TableGen/CMakeFiles/obj.llvm-tblgen.dir/all] Error 2
make: *** [all] Error 2
[root@ecs-helf build]# git branch -a
* (HEAD detached at v20.8.7.15-lts)`

**Comment by marising** [comment]
> 1. llvm is an optional component, you can disable it with CMake flag
> 2. you're trying to compile an obsolete version. Use 20.8 at least.

I compiled the branch of ClickHouse 20.6 in docker, and I got the image of docker 20.6. There was no problem in getting the latest image.

docker pull yandex/clickhouse-server:20.6.10

**Comment by eden-shiwm** [comment]
using gcc-9.3.0 to compile can be successful
