### ISSUE TITLE
 Memory limit DB::Exception: Memory limit (total) exceeded: would use 13.94 GiB (attempt to allocate chunk of 4235716 bytes), maximum: 13.94 GiB (version 20.10.3.30 (official build))

### ISSUE THREAD

**Issue by 7omsxx** [ClickHouse/ClickHouse#17631]
DB::Exception: Memory limit (total) exceeded: would use 13.94 GiB (attempt to allocate chunk of 4235716 bytes), maximum: 13.94 GiB (version 20.10.3.30 (official build))
while i'm insert into clikchouse  after insert 12409 rows into clickhouse ,the errer occured 
and i have already set the config as follow 
<yandex>
    
    <profiles>
        
        <default>
            
            <max_memory_usage>5000000000</max_memory_usage>
            <input_format_parallel_parsing>0</input_format_parallel_parsing>
            
            <use_uncompressed_cache>0</use_uncompressed_cache>
and there is my server ram status

[root@RLKJ-MLN-UAT-MongDB preprocessed_configs]# free -m
              total        used        free      shared  buff/cache   available
Mem:   15861        2041       10033         249        3786       12922

![image](https://user-images.githubusercontent.com/45144402/100598251-712f2680-3339-11eb-8318-0cd47fb63f96.png)

**Comment by den-crane** [comment]
it's another parameters, server parameters (config.xml) **max_server_memory_usage_to_ram_ratio** **max_server_memory_usage**


https://clickhouse.tech/docs/en/operations/server-configuration-parameters/settings/#max_server_memory_usage
https://clickhouse.tech/docs/en/operations/server-configuration-parameters/settings/#max_server_memory_usage_to_ram_ratio

Try to set `max_server_memory_usage_to_ram_ratio=2`

**Comment by den-crane** [comment]
And upgrade to 20.10.5.10

**Comment by 7omsxx** [comment]
Try to set max_server_memory_usage_to_ram_ratio=2
it works

**Comment by raman24kumar** [comment]
For me, when I set set max_server_memory_usage_to_ram_ratio=2 on all the host machines of the cluster, then it worked.
