### ISSUE TITLE
Failed to determine user credentials

### ISSUE THREAD

**Issue by gavinju** [ClickHouse/ClickHouse#17648]
(you don't have to strictly follow this form)

**Describe the bug**
The version is : 20.11.4.13
Ubuntu: 18.04.5 LTS
When run command: sudo /etc/init.d/clickhouse-server start, I got an err message:
Dec  1 10:35:24 apps-domain systemd[7878]: clickhouse-server.service: Failed to determine user credentials: No such process
Dec  1 10:35:24 apps-domain systemd[7878]: clickhouse-server.service: Failed at step USER spawning /usr/bin/clickhouse-server: No such process

Whoever has encountered it，can reply to the solution。
Thank you very much!

**Comment by den-crane** [comment]
Do not use `/etc/init.d/clickhouse-server start`

USE: 
`sudo systemctl start clickhouse-server` 
`sudo systemctl status clickhouse-server` 
`sudo systemctl stop clickhouse-server`
`sudo journalctl -u clickhouse-server.service`

**Comment by gavinju** [comment]
hi, den-crane
thanks for your replay!  I tried it, but the same error is displayed.
But, use the following can run correctly:
coclickhouse-server --config-file=/etc/clickhouse-server/config.xml

**Comment by den-crane** [comment]
try 

sudo -u clickhouse clickhouse-server --config-file=/etc/clickhouse-server/config.xml

**Comment by gavinju** [comment]
thank you!   It's ok!
