### ISSUE TITLE
How to find out which feature or bug has been involved or fixed in new version of ClickHouse?

### ISSUE THREAD

**Issue by liangli1213** [ClickHouse/ClickHouse#17663]
@zhang2014 @BohuTANG @TCeason , currently I'm using version 20.11.2.1, it is stable and meet my requirement, but I know there is always new feature involved or bug fixed in new version (I mean Materialize MySQL), which is very important information for me to decide if I need do an upgrade.
And one method I use is to check your commit periodically, it can give me some information but it is low efficiency, so do you have some other ways?

**Comment by liangli1213** [comment]
And also, I'd like to know does below feature has been realized?
1. Materialize MySQL keep alive when MySQL master is down
2. Materialize MySQL can do house keeping for deleted rows
3. Materialize MySQL can keep replication when using VIP to make replication relationship and VIP has failover to another MySQL node

**Comment by alexey-milovidov** [comment]
MaterializeMySQL is not under active development and it continue to remain experimental feature not recommended for production usage.
