### ISSUE TITLE
SQL rewriting based on materialized views

### ISSUE THREAD

**Issue by DoubleWei-go** [ClickHouse/ClickHouse#17672]
**Use case**

Clickhosue provides the materialized view capability. However, you must manually modify the SQL statements when using the silent view, especially the SQL statements generated by some application services are used to query the original tables. Therefore, the materialized view capability is difficult to use.

**Describe the solution you'd like**

Check whether the user SQL can match the materialized view and rewrite the AST based on the materialized view in the current service.
The main steps are as follows:
1. Register each materialized view. All these views exist as AST.
2. Parse user SQL statements into ASTs that facilitate traversal processing and optimize rules to unify the final format.
3. Split the user SQL AST and materialized view AST based on the following elements: project, agg, filter, join, and group.
4. Process the logical plan to be rewritten and recursively match the logical plan with each existing view. If the logical plan matches the logical plan, rewrite the logical plan. If multiple logical plans are matched, select the logical plan.
Matching and rewriting modes:
Customize a match method and a rewrite method for each element. When all elements are matched, all elements are rewritten.

**Comment by filimonov** [comment]
There are too many different materialized view, not all of them can help optimizing the queries on the original table.
They can do enrichements, they can have different keys, they can push the data to another cluster, they can have another lifetime. 

It it not possible to build something like you want in general case. 

For some corner cases you have in your env you can build a query generator/translator in your backend. It will be much simpler and will work much better than attempts to create some generalized solution which most probably will be ugly and work bad in most of the cases and will steal developers time / attention from the issues more important for database engine.

**Comment by den-crane** [comment]
BTW https://github.com/bitquery/activecube can do it.

And maybe in-part projections will do it automatically.  https://github.com/ClickHouse/ClickHouse/issues/14730
