### ISSUE TITLE
Table of Contents of section [Dates and Times] incomplete

### ISSUE THREAD

**Issue by rbeeli** [ClickHouse/ClickHouse#17680]
The **Table of Contents** does not actually list all functions as documented in the section **Dates and Times**.

See: [https://clickhouse.tech/docs/en/sql-reference/functions/date-time-functions/](https://clickhouse.tech/docs/en/sql-reference/functions/date-time-functions/)

For example, `formatDateTime` is not listed in the TOC, but documented on the page. Might be the case for other secions too, I haven't checked.

It's confusing and took me some time to find the documentation I was looking for.

Thanks.

**Comment by den-crane** [comment]
fixed
