### ISSUE TITLE
[GEO] Full set of H3 functions 

### ISSUE THREAD

**Issue by AbelVM** [ClickHouse/ClickHouse#17708]
The current implementation of H3 functionality is partial, including only a subset of the functions actually available in the library

It would be great if the full H3 API was available within ClickHouse :slightly_smiling_face:

**Comment by Draconic** [comment]
Completely agree.
It would be great to get H3ToGeo at least so data can be easily converted both ways within ClickHouse.

**Comment by alexey-milovidov** [comment]
@hombit Do you want to help adding these functions?

**Comment by AbelVM** [comment]
I'd go with the whole set of H3 functions, as they provide almost all the needed geospatial functionality to analyze location data. 

Adding only type conversion does not improve anything, imho


> Completely agree.
> It would be great to get H3ToGeo at least so data can be easily converted both ways within ClickHouse.

**Comment by hombit** [comment]
@alexey-milovidov Sorry, I don't feel I have enough time to do it next few weeks

**Comment by alexey-milovidov** [comment]
Ok. This task is easy to do. Maybe someone can help...

**Comment by nrolf** [comment]
I found this issue on ovio.org and would love to contribute!

**Comment by alexey-milovidov** [comment]
@nrolf We will be happy to help.
https://clickhouse.tech/docs/en/development/developer-instruction/

**Comment by ray-at-github** [comment]
+1 upvote for this. It would be great to have the full set.

**Comment by alexey-milovidov** [comment]
@bharatnc What functions are missing now?

**Comment by bharatnc** [comment]
> @bharatnc What functions are missing now?

I will make a list of missing functions. I'll work on adding the remaining missing ones shortly.

**Comment by bharatnc** [comment]
> > @bharatnc What functions are missing now?
> 
> I will make a list of missing functions. I'll work on adding the remaining missing ones shortly.

It looks to me like after these changes to h3 submodule in #25483 the h3 apis available to us conform to only 4.x(alpha) and not [3.x(stable)]((https://h3geo.org/docs/api/indexing). Example: compare traversal funcs available b/w the two versions, the list is very different (it looks to me like there have been a lot of changes to function names and apis exposed).

Should we only follow the api reference for 4.x (alpha) and add support for those functions that are missing from ClickHouse? 

Also it looks like ClickHouse-Extras/h3 is very out of date. Should that be updated to match the current h3 submodule in contrib/h3 ?  

ClickHouse-Extras/h3  contains some fixes (https://github.com/ClickHouse-Extras/h3/pull/1, https://github.com/ClickHouse-Extras/h3/pull/2) that add some range checks. Though I've not looked into how many of those are still relevant / needed (or if those are included already) in v4.x  submodule that's currently in use.

**Comment by bharatnc** [comment]
@alexey-milovidov  @qoega related to my previous comment regarding the h3 library version in ClickHouse. To continue adding more functions to ClickHouse, we should probably decide to do one of these:

- either revert back to the stable version 3.xx of API and add functions available in stable version.
- or start adding functions available in beta 4.xx version (not released as stable yet) for missing functions. For older functions, we can revisit and add aliases / deprecate wherever applicable. For example [kRing in v 3.xx is now known as girdDistance in v4.xx](https://h3geo.org/docs/next/api/traversal#griddisk).

**Comment by bharatnc** [comment]
> > @bharatnc What functions are missing now?
> 
> I will make a list of missing functions. I'll work on adding the remaining missing ones shortly.

It looks to me like after these changes to h3 submodule in #25483 the h3 api funcs available to us conform to only [4.x(alpha)](https://h3geo.org/docs/next/api/indexing) and not [3.x(stable)](https://h3geo.org/docs/api/indexing). Example: compare traversal funcs available b/w the two versions, the list is different (there has been several changes to function names and apis exposed though functionality remains same).

Should we only follow the api reference for 4.x (alpha) and add support for those functions that are missing from ClickHouse? 

Also it looks like ClickHouse-Extras/h3 is very out of date. Should that be updated to match the current h3 submodule in contrib/h3 ?

**Comment by alexey-milovidov** [comment]
@bharatnc maybe now we finally have all the functions?

**Comment by bharatnc** [comment]
> @bharatnc maybe now we finally have all the functions?

@alexey-milovidov almost there. There are a few more missing functions (mainly related to traversal, unidirectional edges to be added) I'll post a few more PRs to cover the remaining ones.

**Comment by bharatnc** [comment]
After the previous PRs, I went through the functions again. It looks like there are only two functions (region functions) which are still missing and otherwise the functions in CH are mostly on par with what's available upstream:
[polyfill](https://h3geo.org/docs/api/regions#polyfill)
[h3SetToLinkedGeo / h3SetToMultiPolygon](https://h3geo.org/docs/api/regions#h3settolinkedgeo--h3settomultipolygon)

**Comment by alexey-milovidov** [comment]
@bharatnc I cannot find these functions by your links.
Do we need these functions? Maybe we can close this task as complete?

**Comment by bharatnc** [comment]
@alexey-milovidov looks like `polyfill` and `h3SetToLinkedGeo / h3SetToMultiPolygon`  are now named `polygonToCells` & `cellsToLinkedMultiPolygon / cellsToMultiPolygon` respectively in v4.x. Now docs also mark 3.x as deprecated and so we should probably follow 4.x for new funcs.

We can close this issue out. There are already individual issues tracking these two functions:
- `h3SetToMultiPolygon` / `cellsToMultiPolygon` https://github.com/ClickHouse/ClickHouse/issues/35216
- `polyfill` / `polygonToCells`  https://github.com/ClickHouse/ClickHouse/issues/33991
