### ISSUE TITLE
docker entrypoint should chown all folders for multidisk setup

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#17717]
1) clickhouse-extract-from-config should be able to return a list of paths (new line separared) maybe with something like globs:
```
clickhouse-extract-from-config --key='storage_configuration.disks.*.path'
```

2) entrypoint should add those folders for the create & chown loop here:
https://github.com/ClickHouse/ClickHouse/blob/2b3281888afc233cea12f74c35d1462c3ec985d8/docker/server/entrypoint.sh#L43

**Comment by alexey-milovidov** [comment]
Reopen if you will find a contributor to do this task.
