### ISSUE TITLE
Do you have any plan to support overflow check for insert of integer data type?

### ISSUE THREAD

**Issue by zhangjmruc** [ClickHouse/ClickHouse#17714]
When we try to insert a value of 300 into a column with Int8 data type, the overflow value 300 is trucated to the range of Int8, which is [-128,127]. I know this behavior is stardard SQL. However, this may not be expected for users, who want to throw an error for this kind cases. 
   Do we have any plan to support overflow check for different integer data types in future?

**Comment by alexey-milovidov** [comment]
This is not in our plans.
It can be implemented (maybe under a setting) if it will not compromise performance of data parsing in normal cases.
