### ISSUE TITLE
Applying Catboost model with text feature in Clickhouse

### ISSUE THREAD

**Issue by llfelicilda** [ClickHouse/ClickHouse#17713]
I wanted to integrate a CatBoost Classifier that accepts regular text as feature into ClickHouse and run the model inference from SQL. I followed necessary [steps to load the model to clickhouse](https://clickhouse.tech/docs/en/guides/apply-catboost-model/#integrate-catboost-into-clickhouse) but when I ran the query for prediction:

```
select target,
       modelEvaluate('cat_model',
                     text)      AS prediction,
       1. / (1 + exp(-prediction)) AS probability
from test
limit 10;
```

I get this error:
`Code: 36, e.displayText() = DB::Exception: Number of columns is different with number of features: 1 vs 0 + 0 (version 20.9.2.20 (official build))`

This is how my `test` table looks like:
<img width="754" alt="Screenshot 2020-12-02 at 3 18 51 PM" src="https://user-images.githubusercontent.com/9193892/100841072-b8d8be00-34b1-11eb-8d69-4c3fc218d4cc.png">

What's the right way to do it? Thanks.

**Comment by alexey-milovidov** [comment]
Looks like no one wants to implement this feature.
