### ISSUE TITLE
group by with high network traffic

### ISSUE THREAD

**Issue by eiffel0311** [ClickHouse/ClickHouse#17732]
select brand_id, sum(engagement_new), count(1) 
   from(
      select doc_id, brand_id, any(engagement_cnt) as engagement_new  from metrics.dws_3_view
      group by doc_id, brand_id
    ) tmp
group by brand_id

--------------------------------------
table engine likne
ENGINE = ReplicatedReplacingMergeTree('/clickhouse/metrics/{shard}/dws_3', '{replica}', create_time)
PARTITION BY doc_id%100

CREATE TABLE metrics.dws_view_3 AS metrics.dws_3 ENGINE = Distributed(s4r1, metrics, dws_3, doc_id%100)

--------------------------------------

doc_id is a high cardinality  dimension， what can i do with sql above?

**Comment by den-crane** [comment]
Distributed(s4r1, metrics, dws_3, doc_id%100) -- if you insert using distributed then you can use

 --distributed_group_by_no_merge arg                              If 1, Do not merge aggregation states from different servers for distributed query processing - in case it is for certain that there are different keys on different shards. If 2 - same as 1 but also apply ORDER BY and LIMIT stages
  --optimize_distributed_group_by_sharding_key arg                 Optimize GROUP BY sharding_key queries (by avoiding costly aggregation on the initiator server).

**Comment by filimonov** [comment]
Also - only innermost subquery is distributed. Try to push most of the work to shard, let it return less data... 

```
select brand_id, sumIf(engagement_cnt, <condition satisfied once per docid>), unin(doc_id) from metrics.dws_3_view
group by brand_id
```

**Comment by ongbo** [comment]
> 
 I have a question. What I encountered before was said that over query were single -threaded, but from this case, it seems that they are all multi -threaded. Is it only a single thread when the child query and the external query are summarized.

In fact, when I use it, the child query is fast, and the query is very slow, and it feels conflict with this result.

**Comment by nickitat** [comment]
> over query were single -threaded

it is true for the current release and will no longer be true since the upcoming release.

> In fact, when I use it, the child query is fast, and the query is very slow, and it feels conflict with this result.

refer to `explain pipeline` to see which portion of your query will be processed using which number of threads.
