### ISSUE TITLE
Slow start with high memory consumption: log filled with "<Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 16.90 TiB."

### ISSUE THREAD

**Issue by Farfaday** [ClickHouse/ClickHouse#17731]
**Describe the bug**

Since we upgraded to 20.10.3.30, one of our clickhouse cluster takes much more time to start. (Up to 50 minutes, and before it took ~3 minutes)
The log file is filled with
>  <Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 16.90 TiB

Additionally, the memory consumption increases, linearly, a lot (up to arround 230 G for us) and then drop back to normal values once clickhouse finished starting up. During that loading phase, a single CPU core is used at 100%.
If that memory is not available for the machine, clickhouse gets OOMed by the kernel.

**How to reproduce**
* Issue appeared after we upgraded to ClickHouse server version 20.10.3.30

* How could I find wich of our tables may be responsible for that ?

**Expected behavior**
A fast startup :)

**Comment by den-crane** [comment]
Any messages about mutations in the startup logs?

**Comment by Farfaday** [comment]
I could not find the string "mutation" in the logs.
But I filtered out all the 
`    DiskLocal: Reserving 1.00 MiB on disk default, having unreserved 16.90 TiB`
and now I can see messages of the form flowing

```
2020.12.02 16:47:41.580028 [ 40550 ] {} <Trace> SystemLog (system.metric_log): Flushing system log, 8 entries to flush
2020.12.02 16:47:41.589671 [ 40550 ] {} <Trace> system.metric_log: Renaming temporary part tmp_insert_202012_328_328_0 to 202012_267256_267256_0.
2020.12.02 16:47:41.590458 [ 40550 ] {} <Trace> SystemLog (system.metric_log): Flushed system log
2020.12.02 16:47:41.592619 [ 40456 ] {} <Trace> MergeTreeSequentialSource: Reading 2 marks from part 202012_266951_267251_60, total 2261 rows starting from the beginning of the part
2020.12.02 16:47:41.595031 [ 40456 ] {} <Trace> MergeTreeSequentialSource: Reading 2 marks from part 202012_267252_267252_0, total 8 rows starting from the beginning of the part
2020.12.02 16:47:41.597294 [ 40456 ] {} <Trace> MergeTreeSequentialSource: Reading 2 marks from part 202012_267253_267253_0, total 7 rows starting from the beginning of the part
2020.12.02 16:47:41.599577 [ 40456 ] {} <Trace> MergeTreeSequentialSource: Reading 2 marks from part 202012_267254_267254_0, total 8 rows starting from the beginning of the part
2020.12.02 16:47:41.601840 [ 40456 ] {} <Trace> MergeTreeSequentialSource: Reading 2 marks from part 202012_267255_267255_0, total 7 rows starting from the beginning of the part
2020.12.02 16:47:41.604125 [ 40456 ] {} <Trace> MergeTreeSequentialSource: Reading 2 marks from part 202012_267256_267256_0, total 8 rows starting from the beginning of the part
2020.12.02 16:47:41.709171 [ 40456 ] {} <Trace> system.metric_log: Renaming temporary part tmp_merge_202012_266951_267256_61 to 202012_266951_267256_61.
2020.12.02 16:47:41.709703 [ 40456 ] {} <Trace> system.metric_log (MergerMutator): Merged 6 parts: from 202012_266951_267251_60 to 202012_267256_267256_0
```

**Comment by den-crane** [comment]
you can remove or clean this table `truncate table system.metric_log`

**Comment by Farfaday** [comment]
Hi,
Thanks for you reply ! I tried that (truncating the table + removing all the log stuffs from the config (query_log, metric_log, etc.)), but I am still affected by the issue described in https://github.com/ClickHouse/ClickHouse/issues/17731#issue-755226885

**Comment by detailyang** [comment]
same issues here (clickhouse version 20.11.4.13), after heap profiling, guess it's because wal restore too many tiny parts which took more memory when deserializeBinaryBulk. See the jemalloc heap profiling in `--inuse_space` mode [https://gist.github.com/detailyang/0eba31edae8d437ee6cd51555bd5080b](https://gist.github.com/detailyang/0eba31edae8d437ee6cd51555bd5080b)

**Comment by den-crane** [comment]
can you  show an output of

```sql
select count() part_count
from system.parts 
where active = 1 ;

select count() part_count, formatReadableSize(sum(bytes)) size, sum(rows) rows
from system.parts 
where active = 1 
group by database,table
order by part_count desc
limit 10;


```

**Comment by amorphina** [comment]
here are the requested outputs on behalf of @Farfaday 
`HOSTNAME :) select count() part_count
:-] from system.parts
:-] where active = 1 ;

SELECT count() AS part_count
FROM system.parts
WHERE active = 1

┌─part_count─┐
│       1278 │
└────────────┘

1 rows in set. Elapsed: 0.017 sec. Processed 1.28 thousand rows, 725.12 KB (74.15 thousand rows/s., 42.07 MB/s.)

HOSTNAME :) select count() part_count, formatReadableSize(sum(bytes)) size, sum(rows) rows
:-] from system.parts
:-] where active = 1
:-] group by database,table
:-] order by part_count desc
:-] limit 10;

SELECT
    count() AS part_count,
    formatReadableSize(sum(bytes)) AS size,
    sum(rows) AS rows
FROM system.parts
WHERE active = 1
GROUP BY
    database,
    table
ORDER BY part_count DESC
LIMIT 10

┌─part_count─┬─size───────┬───────rows─┐
│        393 │ 23.92 GiB  │ 3710229111 │
│        379 │ 6.55 GiB   │  224636572 │
│        137 │ 21.79 GiB  │ 4604411140 │
│         91 │ 16.63 GiB  │  506617795 │
│         57 │ 9.31 GiB   │  591755892 │
│         44 │ 138.70 MiB │   14926780 │
│         33 │ 73.31 MiB  │    1929674 │
│         25 │ 21.00 GiB  │  272548372 │
│         22 │ 18.75 GiB  │  183052902 │
│         22 │ 484.46 MiB │   28901778 │
└────────────┴────────────┴────────────┘

10 rows in set. Elapsed: 0.018 sec. Processed 1.28 thousand rows, 724.90 KB (71.85 thousand rows/s., 40.76 MB/s.)`

**Comment by den-crane** [comment]
try to disable WAL.

```
# cat /etc/clickhouse-server/conf.d/in_memory_parts_enable_wal.xml
<yandex>
    <merge_tree>
        <in_memory_parts_enable_wal>0</in_memory_parts_enable_wal>
    </merge_tree>
</yandex>

service clickhouse-server restart

select value from system.merge_tree_settings where name ='in_memory_parts_enable_wal'
┌─value─┐
│ 0     │
└───────┘

```

**Comment by amorphina** [comment]
We tried that but it did not help, starting time of clickhouse is unchanged.

**Comment by CurtizJ** [comment]
@detailyang Can you show count and sizes of wal files? They are located in root directory of table and have name `wal.bin` for active log and names in format `wal_N_M.bin` for rotated logs.

**Comment by detailyang** [comment]
@CurtizJ Sorry for the late reply. My wal.bin is too large (300GB) see the below:

```bash
root@553bf0dab02a:/var/lib/clickhouse/store# find . -name wal* | wc -l
417

root@553bf0dab02a:/var/lib/clickhouse/store# find . -name wal* | xargs -I {} du -m {}  | awk '{sum+=$1}END{print sum}'
300252
```

@amorphina can you try this ` find . -name wal* | wc -l` and  `find . -name wal* | xargs -I {} du -m {}  | awk '{sum+=$1}END{print sum}'` in /var/lib/clickhouse

**Comment by Farfaday** [comment]
`find . -name wal* | wc -l ` gives 27
` find . -name wal* | xargs -I {} du -m {} | awk '{sum+=$1}END{print sum}' ` gives 4152

**Comment by detailyang** [comment]
@ctr it looks like your scene doesn't match mine and my wal is too large (my scene is too many tiny requests so i tweak the min_rows_for_compact_part = 8390848)

@CurtizJ what confused me is before the restart all the memory parts is not high memory as the following:

```sql
SELECT
    part_type,
    sum(rows),
    formatReadableSize(sum(data_compressed_bytes)),
    formatReadableSize(sum(data_uncompressed_bytes))
FROM system.parts
WHERE active
GROUP BY part_type

┌─part_type─┬───sum(rows)─┬─formatReadableSize(sum(data_compressed_bytes))─┬─formatReadableSize(sum(data_uncompressed_bytes))─┐
│ InMemory  │     7343679 │ 0.00 B                                         │ 278.77 MiB                                       │
│ Compact   │    50302934 │ 474.58 MiB                                     │ 1.70 GiB                                         │
│ Wide      │ 26503058282 │ 63.74 GiB                                      │ 584.86 GiB                                       │
└───────────┴─────────────┴────────────────────────────────────────────────┴──────────────────────────────────────────────────┘
```

**Comment by detailyang** [comment]
@Farfaday can you try this sql ?

```sql
SELECT
    part_type,
    sum(rows),
    formatReadableSize(sum(data_compressed_bytes)),
    formatReadableSize(sum(data_uncompressed_bytes))
FROM system.parts
WHERE active
GROUP BY part_type
```

**Comment by Farfaday** [comment]
```
SELECT
    part_type,
    sum(rows),
    formatReadableSize(sum(data_compressed_bytes)),
    formatReadableSize(sum(data_uncompressed_bytes))
FROM system.parts
WHERE active
GROUP BY part_type

┌─part_type─┬───sum(rows)─┬─formatReadableSize(sum(data_compressed_bytes))─┬─formatReadableSize(sum(data_uncompressed_bytes))─┐
│ InMemory  │         885 │ 0.00 B                                         │ 200.72 KiB                                       │
│ Compact   │      822690 │ 19.58 MiB                                      │ 194.52 MiB                                       │
│ Wide      │ 10415999360 │ 121.84 GiB                                     │ 2.60 TiB                                         │
└───────────┴─────────────┴────────────────────────────────────────────────┴──────────────────────────────────────────────────┘

3 rows in set. Elapsed: 0.018 sec. Processed 1.32 thousand rows, 750.18 KB (73.36 thousand rows/s., 41.63 MB/s.)
```

**Comment by Farfaday** [comment]
Hi all,
today I tested:

- shutting down clickhouse
- moving out all the wal_x_yyyyy.bin files out of the data/db/table directories
- setting in config.xml
```
    <merge_tree>
        <in_memory_parts_enable_wal>0</in_memory_parts_enable_wal>
    </merge_tree>
```

Then the clickhouse starting time went back to normal.

I noticed that sometimes the wal_x_yyyyy.bin files were really old (more than 3 weeks)... is that "normal" ?

Thanks !

**Comment by azat** [comment]
It is likely that the problem is because old WAL files will not be deleted, #40592 should help with this.
