### ISSUE TITLE
Is it possible to convert column a quantilesExact to quantilesTiming

### ISSUE THREAD

**Issue by spalax** [ClickHouse/ClickHouse#17749]
I have a column
`AggregateFunction(quantilesExact(0.50, 0.75, 0.90, 0.95, 0.99), UInt32)`
and to speedup query for the quantiles i would like to use quantilesTiming
`AggregateFunction(quantilesTiming(0.50, 0.75, 0.90, 0.95, 0.99), UInt32)`

And the main question is - how can i convert quantilesExact to quantilesTiming ?

**Comment by filimonov** [comment]
Afaik no way for that (well - maybe export to some format and import back).

**Comment by filimonov** [comment]
@alexey-milovidov may be we can define a list of compatible aggregatefunctions and allow casting between them?

**Comment by alexey-milovidov** [comment]
Conversion is possible if you export the binary representation of the state and do it by external program.

> a list of compatible aggregatefunctions states and allow casting between them

That's kinda non-trivial to implement.
