### ISSUE TITLE
why int128 not support?

### ISSUE THREAD

**Issue by vegastar002** [ClickHouse/ClickHouse#17753]
> create table ds1_agg(
    date DateTime,
    cnt AggregateFunction(groupBitmap, Int128)
)engine =AggregatingMergeTree() partition by toYear(date) order by date;

Received exception from server (version 20.11.3):
Code: 43. DB::Exception: Received from localhost:9000. DB::Exception: Illegal type Int128 of argument for aggregate function groupBitmap.

**Comment by filimonov** [comment]
Afaik roaring bitmaps don't support it.

You can ask there, similar to
https://github.com/RoaringBitmap/RoaringBitmap/issues/109

**Comment by l1t1** [comment]
the bigmap would be too big(2^128 / 8 =4.2 *10^37
