### ISSUE TITLE
memory not free after query exception

### ISSUE THREAD

**Issue by chenk818** [ClickHouse/ClickHouse#17752]
**Describe the bug**
I ran a sql with count(distinct)  which will consume lots of memory and CH return  DB::Exception: Memory limit (for query) exceeded. after exception the initator node not free all memory.remote servers is ok.

How to reproduce:
ClickHouse server version 20.8.3 revision 54438
CentOS Linux release 7.6.1810 (Core)

![memory](https://user-images.githubusercontent.com/1886495/100957590-b334b400-3555-11eb-9567-b5fc9a27c030.png)

**Comment by chenk818** [comment]
@den-crane  can you help me

**Comment by filimonov** [comment]
Update to 20.8.7, reopen ticket if issue persist after update. 

See:
https://github.com/ClickHouse/ClickHouse/pull/16264

**Comment by chenk818** [comment]
> Update to 20.8.7, reopen ticket if issue persist after update.
> 
> See:
> #16264

thanks
