### ISSUE TITLE
WAL: merge on every insert

### ISSUE THREAD

**Issue by pronvis** [ClickHouse/ClickHouse#17758]
**Describe the bug**
A lot of files created even when using WAL.

**How to reproduce**
* Which ClickHouse server version to use
not important, but I use `20.10.5`
* Non-default settings, if any
```
    <merge_tree>
        <min_rows_for_compact_part>100</min_rows_for_compact_part>
        <min_bytes_for_compact_part>104857600</min_bytes_for_compact_part> <!-- 100MB -->
        <in_memory_parts_enable_wal>true</in_memory_parts_enable_wal>
    </merge_tree>
```
* reproduce stepd
1. create table
```
CREATE TABLE events (
    log String
) ENGINE = MergeTree()
ORDER BY log;
```
2. insert 1000 blocks in a loop, each block have only one row

**Expected behavior**
Small amount of files in data directory: `/var/lib/clickhouse/data/default/events/`

**Actual behavior**
A lot of files created in data directory: `/var/lib/clickhouse/data/default/events/` (close to one directory for each inserted block).
<img width="1246" alt="image" src="https://user-images.githubusercontent.com/228536/101025541-c90e9d00-3586-11eb-8494-e58f8aa2fe9e.png">

**Comment by reedycreek** [comment]
any updates?  encounter the same problem.

**Comment by alexey-milovidov** [comment]
Development of in-memory parts is on pause, we will continue later.
I recommend to turn off in-memory parts, because compact parts are usually good enough.

Also the status is:
- compact parts: production ready and used in production for years;
- in-memory parts: experimental.

**Comment by alexey-milovidov** [comment]
We removed the support for in-memory parts.
