### ISSUE TITLE
Kubernetes is deprecating Docker as a container runtime after v1.20.

### ISSUE THREAD

**Issue by geertvanbommel** [ClickHouse/ClickHouse#17754]
I know Kubernetes and Docker are used by some of us, so for your information I decided to created this issue. https://kubernetes.io/blog/2020/12/02/dont-panic-kubernetes-and-docker/

**Comment by filimonov** [comment]
Thanks for a note :+1: 

It seems no immediate actions are needed. 

> Docker-produced images will continue to work in your cluster with all runtimes, as they always have.

Maybe we can also consider switching from docker to some nicer alternatives - like podman and nicer build tools like buildah, img (in CI). 

But it's not something important for now since everything works and will keep working.
