### ISSUE TITLE
(Replicated)SummingMergeTree is making very strange things with Enum columns which are not a part of PK

### ISSUE THREAD

**Issue by skaurus** [ClickHouse/ClickHouse#1776]
This is a guess based on two things.
1) We are sending ad views and clicks to ClickHouse. Logging on the sending end shows that there are a lot of views and handful of clicks. Each event is 1 row in CH, with column `event_type = Enum8('show' = 1, 'view' = 2, 'click' = 3)`. But select from that table shows that there can be 1000x more clicks than views, and it's not just old data, they are growing faster right now. I remind, sending end logging says that this is actually not true.
2) `SELECT event_type, count(*) FROM ... GROUP BY event_type` fails with message `Unexpected value 4 for type Enum8('show' = 1, 'view' = 2, 'click' = 3)`.

Maybe later I'll provide some proofs or a testcase, but no promises.

**Comment by skaurus** [comment]
And I'm back.

First, let's create a `ReplicatedSummingMergeTree` table and a `Buffer` (or it will be painfully slow):
```
CREATE TABLE break_me (
  aid UInt32,
  bid UInt32,
  cid UInt32,
  event_date Date,
  event_type Enum8('show' = 1, 'view' = 2, 'click' = 3),
  event_revenue Float32
) ENGINE = ReplicatedSummingMergeTree(
  '/clickhouse/tables/{shard}/break_me',
  '{replica}',
  event_date,
  (aid, bid, cid),
  8192
)

CREATE TABLE _buffer_break_me (
  aid UInt32,
  bid UInt32,
  cid UInt32,
  event_date Date,
  event_type Enum8('show' = 1, 'view' = 2, 'click' = 3),
  event_revenue Float32
) ENGINE = Buffer(
  'YOUR_DB_NAME_CHANGE_ME',
  'break_me',
  16,
  10,
  30,
  10000,
  10000,
  100000,
  10000000
)
```

Now let's fill them. Here is the script in everyone favorite language Perl: https://pastebin.com/5hnfg6WC
It should be started like this: `HOST=... PORT=... DB=... USER=... PASS=... ./totally_safe_script_from_internets.pl` (it's best to run it under `root` of course).

It will report progress as it inserts one month of data. In the end, it will print stat on what it actually inserted - counts of rows broken by `aid`, `bid` and `cid` columns values.

Now make a query to that table. Something like `SELECT * FROM break_me`, or even better `SELECT aid, event_type, count(*) FROM break_me GROUP BY aid, event_type ORDER BY aid, event_type`.
Well, for me it ends with an error like `Unexpected value 4 for type Enum8('show' = 1, 'view' = 2, 'click' = 3)`. That was before script even finished running.
Or even better, when script finished and summing happened (`SELECT count(*) FROM break_me` went from 40k to 9k), I got a beatiful `Unexpected value -123 for type Enum8('show' = 1, 'view' = 2, 'click' = 3)`.

We have the latest release, version 1.1.54327.

**Comment by skaurus** [comment]
Tested `ReplicatedMergeTree` with the same script. Works fine.

**Comment by alexey-milovidov** [comment]
Fixed in recent releases.

**Comment by skaurus** [comment]
I'm not sure this is fixed... I tried running this script on the latest version and while there were no errors about unexpected values for Enum, aggregates as reported by the script and as found in the ClickHouse are wildly different.

**Comment by alexey-milovidov** [comment]
Will take a look...

**Comment by alexey-milovidov** [comment]
@skaurus The issue of unintentional summing of enum values is fixed long time ago.

The script is no longer available and, nevertheless, it's a different issue.
