### ISSUE TITLE
Cannot read all data. Bytes read: 15729662. Bytes expected: 268435455.                 20.11.4.13

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#17762]
clickhouse-server                    20.11.4.13
I try fix it run 
check table events; 
but after clickhouse move part to detached , this part replicate from other replica with same problem.
seems this part broken on all replicas

`2020.12.02 12:27:29.607426 [ 144664 ] {} <Warning> default.events (ReplicatedMergeTreePartCheckThread): Checking data of part 20201130_20201130_499695_499707_2.
2020.12.02 12:27:30.317326 [ 144657 ] {} <Warning> default.events (ReplicatedMergeTreePartCheckThread): Checking part 20201130_20201130_499695_499707_2
2020.12.02 12:27:30.322286 [ 144623 ] {} <Error> default.events (8005f254-5c8e-45ed-9a03-8ba6d4b05bce): auto DB::StorageReplicatedMergeTree::queueTask()::(anonymous class)::operator()(DB::StorageReplicatedMergeTree::LogEntryPtr &) const: Code: 33, e.displayText() = DB::Exception: Cannot read all data. Bytes read: 15729662. Bytes expected: 268435455.: (while reading column BillingURL): (while reading from part /var/lib/clickhouse/store/800/8005f254-5c8e-45ed-9a03-8ba6d4b05bce/20201130_20201130_499695_499707_2/ from mark 14 with max_rows_to_read = 8192): While executing MergeTreeSequentialSource: Cannot fetch required block. Stream PipelineExecuting, part 2, Stack trace (when copying this message, always include the lines below):

0. DB::ReadBuffer::readStrict(char*, unsigned long) @ 0x7b6db35 in /usr/bin/clickhouse
1. ? @ 0xd5a8ba1 in /usr/bin/clickhouse
2. DB::DataTypeString::deserializeBinaryBulk(DB::IColumn&, DB::ReadBuffer&, unsigned long, double) const @ 0xd5a81f8 in /usr/bin/clickhouse
3. DB::MergeTreeReaderWide::readData(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::IDataType const&, DB::IColumn&, unsigned long, bool, unsigned long, bool) @ 0xe1c2c79 in /usr/bin/clickhouse
4. DB::MergeTreeReaderWide::readRows(unsigned long, bool, unsigned long, std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >&) @ 0xe1c1f90 in /usr/bin/clickhouse
5. DB::MergeTreeSequentialSource::generate() @ 0xe1d36c9 in /usr/bin/clickhouse
6. DB::ISource::work() @ 0xe36459a in /usr/bin/clickhouse
7. DB::SourceWithProgress::work() @ 0xe4c927a in /usr/bin/clickhouse
8. ? @ 0xe39d37c in /usr/bin/clickhouse
9. DB::PipelineExecutor::executeStepImpl(unsigned long, unsigned long, std::__1::atomic<bool>*) @ 0xe39a4a7 in /usr/bin/clickhouse
10. DB::PipelineExecutor::executeStep(std::__1::atomic<bool>*) @ 0xe39918c in /usr/bin/clickhouse
11. DB::PullingPipelineExecutor::pull(DB::Chunk&) @ 0xe3a5ac8 in /usr/bin/clickhouse
12. DB::PullingPipelineExecutor::pull(DB::Block&) @ 0xe3a5d10 in /usr/bin/clickhouse
13. DB::PipelineExecutingBlockInputStream::readImpl() @ 0xe395444 in /usr/bin/clickhouse
14. DB::IBlockInputStream::read() @ 0xd4f2625 in /usr/bin/clickhouse
15. DB::ColumnGathererStream::fetchNewBlock(DB::ColumnGathererStream::Source&, unsigned long) @ 0xdce085f in /usr/bin/clickhouse
16. void DB::ColumnGathererStream::gather<DB::ColumnString>(DB::ColumnString&) @ 0xdd39a11 in /usr/bin/clickhouse
17. DB::ColumnGathererStream::readImpl() @ 0xdce0650 in /usr/bin/clickhouse
18. DB::IBlockInputStream::read() @ 0xd4f2625 in /usr/bin/clickhouse
19. DB::MergeTreeDataMergerMutator::mergePartsToTemporaryPart(DB::FutureMergedMutatedPart const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::BackgroundProcessListEntry<DB::MergeListElement, DB::MergeInfo>&, std::__1::shared_ptr<DB::RWLockImpl::LockHolderImpl>&, long, DB::Context const&, std::__1::unique_ptr<DB::IReservation, std::__1::default_delete<DB::IReservation> > const&, bool) @ 0xe0fb24b in /usr/bin/clickhouse
20. DB::StorageReplicatedMergeTree::tryExecuteMerge(DB::ReplicatedMergeTreeLogEntry const&) @ 0xdef4c04 in /usr/bin/clickhouse
21. DB::StorageReplicatedMergeTree::executeLogEntry(DB::ReplicatedMergeTreeLogEntry&) @ 0xdee6d6c in /usr/bin/clickhouse
22. ? @ 0xdf5af7c in /usr/bin/clickhouse
23. DB::ReplicatedMergeTreeQueue::processEntry(std::__1::function<std::__1::shared_ptr<zkutil::ZooKeeper> ()>, std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&, std::__1::function<bool (std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&)>) @ 0xe23f2b5 in /usr/bin/clickhouse

`

_Originally posted by @stufently in https://github.com/ClickHouse/ClickHouse/issues/4959#issuecomment-737729205_

**Comment by den-crane** [comment]
@stufently what version did you use before upgrade? 
Do you use mutations?

**Comment by den-crane** [comment]
try to disable WAL.

```
# cat /etc/clickhouse-server/conf.d/in_memory_parts_enable_wal.xml
<yandex>
    <merge_tree>
        <in_memory_parts_enable_wal>0</in_memory_parts_enable_wal>
    </merge_tree>
</yandex>

service clickhouse-server restart

select value from system.merge_tree_settings where name ='in_memory_parts_enable_wal'
┌─value─┐
│ 0     │
└───────┘

```

**Comment by stufently** [comment]
before version  20.10.2.20
Yes we use mutations for clean old data, but data  in part fresh, will delete after 3 month.
Ask about scheme , maybe nda

**Comment by stufently** [comment]
> > before version 20.10.2.20
> > Yes we use mutations for clean old data, but data in part fresh, will delete after 3 month.
> > Ask about scheme , maybe nda
> 
> Which version did you upgrade to fix it ?

Seems problem related with physicals server , after  change server for this replica solve problem.
Update clickhouse and other solutions dont help.
