### ISSUE TITLE
Multiples timezones same materialized view

### ISSUE THREAD

**Issue by inakivb** [ClickHouse/ClickHouse#17765]
**Use case**
When having multiples customers in different timezones you "need" to materialize much daily information to different timezones.
Our current approach is to have as many materialized tables as timezones and do something like
CREATE MATERIALIZED VIEW xxxxx_daily_tz3
(...)
SELECT
  site_id,
  sumMergeState(count),
  toStartOfDay(toDateTime(event_time,'America/Santiago')) as event_time
(...)
FROM xxxxx
WHERE timezone_id = 3
(...)

the problem is that as more new clients are using the tool, the inserts are getting slower.

**Describe the solution you'd like**
We tried to do something like
CREATE MATERIALIZED VIEW xxxxx_daily_all_tz
SELECT
  site_id,
  sumMergeState(count),
  toStartOfDay(event_time,timezone_text) as event_time
FROM xxxxx

being timezone_text a dynamic timezone (ex: America/Santiago) for each client
so we have only a table with all the dates and the app layer knows that it's not UTC

The problem here is that toDateTime expects the timezone to be constant
 DB::Exception: Argument at index 1 for function toStartOfDay must be constant.

**Describe alternatives you've considered**
- Allow dynamic time zones in all datetime methods (I understand that it's not allowed because of some internal optimizations)
or
- Allow some method to change timezone that allows dynamic tz

**Comment by den-crane** [comment]
You can use `case` I think

```sql

SELECT case when y='mos'  then toTimeZone(toStartOfDay(toDateTime(x, 'Europe/Moscow')), 'UTC')
            when y='sant' then toTimeZone(toStartOfDay(toDateTime(x, 'America/Santiago')), 'UTC')
            end event_time
from (select now() x, 'mos' y union all select now(), 'sant') 

┌──────────event_time─┐
│ 2020-12-02 21:00:00 │
└─────────────────────┘
┌──────────event_time─┐
│ 2020-12-03 03:00:00 │
└─────────────────────┘

```

**Comment by filimonov** [comment]
Known issue (p.2 https://github.com/ClickHouse/ClickHouse/issues/1298  ) 

Dynamic timezones switching may be quite costly, and storing timezone names is also costy.
You can just store one more time in client tz.

**Comment by den-crane** [comment]
AFAIK it's another problem. Each site_id has own toStartOfDay UTC timestamp

**Comment by ukutaht** [comment]
I have a similar problem setting up materialized views in the first place. They work great with no concern for timezones but doing daily aggregates in the customer's configured time zone seems very difficult for me.

@inakivb in your proposed solution, how would you handle the customer changing their reporting timezone? Or is it not allowed?

Another question I had was where does `timezone_text` in your context come from? Do you store the timezone name with every event row in your `xxxxx` table? My idea was to have a dictionary loaded from my RDBS that can map site ids to timezones.

**Comment by inakisoriamrf** [comment]
Hi @ukutaht ,
we use different approaches.
In the row data, we store event_time, event_time_client_locale, client_timezone, the locale time is calculated in the ingestion script.
This allows us to materialize information in one table using event_time_client_locale, clickhouse will think that everything is UTC but your app layer knows that each client is in its own TZ.

Other tables are materialized with client_timezone as described in my first comment

We also use event_time for internal performance materializations.

**Comment by ukutaht** [comment]
Yeah that makes sense. We'll move to a similar approach, calculating client time at ingest rather than query time. It's simpler and has additional benefits like making our indexes better aligned with queries.
