### ISSUE TITLE
create dictionary does not support Decimal(20,6) notation

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#17761]
```
create table default.orders(id UInt64, price Decimal(20,6)) Engine = MergeTree() order by id;
insert into default.orders select number, number / 3 from numbers(500);


CREATE DICTIONARY default.orders_hashed (id UInt64, price Decimal(20,6))
PRIMARY KEY id SOURCE(CLICKHOUSE(HOST 'localhost' PORT 9000 
TABLE orders DB 'default' USER 'default')) 
LIFETIME(MIN 0 MAX 0) LAYOUT(HASHED());

DB::Exception: Unknown type Decimal(20, 6).



CREATE DICTIONARY default.orders_hashed (id UInt64, price Decimal32(6))
PRIMARY KEY id SOURCE(CLICKHOUSE(HOST 'localhost' PORT 9000 
TABLE orders DB 'default' USER 'default')) 
LIFETIME(MIN 0 MAX 0) LAYOUT(HASHED());
ok.

```

**Comment by kitaisreal** [comment]
@den-crane could you please specify version. Could not reproduce on current master.

**Comment by den-crane** [comment]
hmm,

20.11.5.18
Received exception from server (version 20.11.5):
Code: 50. DB::Exception: Received from localhost:9000. DB::Exception: Unknown type Decimal(20, 6).

20.12.6.29
Received exception from server (version 20.12.6):
Code: 50. DB::Exception: Received from localhost:9000. DB::Exception: Unknown type Decimal(20, 6).

21.1.2.15
Received exception from server (version 21.1.2):
Code: 50. DB::Exception: Received from localhost:9000. DB::Exception: Unknown type Decimal(20, 6).

21.2.2.8
OK.
