### ISSUE TITLE
Importing *State aggregates from existing data?

### ISSUE THREAD

**Issue by mzealey** [ClickHouse/ClickHouse#17775]
**Use case**

I'm guessing there may well be a way to do this but nothing comes to mind from the docs, and perhaps it is not possible at present.

I have an `AggregatingMergeTree()` and some `AggregateFunction()`s on it like `countState`. The table is being populated just fine by mat views.

BUT, I want to import legacy data from a different database and I don't have the previous non-aggregated rows, I only have the pk + the count data.

Is there (or could there be) an easy way to convert a count number into a `countState`? Could/should I assume that countState and sumState are basically the same and insert a `sumState(<previous count value>)` in? Even though I suspect this would work it feels quite hacky?

**Comment by den-crane** [comment]
countState -- is a bit overhead, now days you can use simpleAggregateFunction (sum)

I think it almost impossible to solve it. 

I see only dumb way like

```sql
SELECT countMerge(x)
FROM
(
    SELECT countState(arrayJoin(range(100))) AS x
)

┌─countMerge(x)─┐
│           100 │
└───────────────┘
```

@azat @YiuRULE

```sql
SELECT countMerge(x)
FROM
(
    SELECT initializeAggregation('countState', 100) AS x
)

┌─countMerge(x)─┐
│             1 │
└───────────────┘
```

**Comment by mzealey** [comment]
Ah I was not aware of `SimpleAggregateFunction` but it looks like it will make life simple.

Strangely though a simple count column (default compression settings in both cases) is taking a lot more space:

```
SELECT
    table,
    column,
    type,
    sum(column_data_compressed_bytes) / sum(rows) AS used_bytes_per_row,
    sum(column_data_uncompressed_bytes) / sum(rows) AS uncompressed_bytes_per_row,
    sum(rows),
    formatReadableSize(sum(column_data_compressed_bytes)) AS compressed,
    formatReadableSize(sum(column_data_uncompressed_bytes)) AS uncompressed
FROM system.parts_columns
WHERE (active = 1) AND (table like '...') and database = 'dnsf'
GROUP BY
    table,
    column,
    type
ORDER BY used_bytes_per_row ASC
...
...    total_state     AggregateFunction(count)        0.7565127564824538      1.0066567764882084      2509745074      1.77 GiB        2.35 GiB
...       total   SimpleAggregateFunction(sum, UInt64)    2.247449672793206       7.99699226479246        2508779357      5.25 GiB 18.68 GiB
```

range of that col is 1-80k

**Comment by den-crane** [comment]
Interesting.
It looks like countState stored not as UInt64. Not sure.

**Comment by den-crane** [comment]
Alexander Kuzmenkov @akuzm: Yes, there are zero high bytes are not written. If their numbers are mostly less than 128, then you will actually get close to one byte per line. The MB T64 codec will give a similar effect to the Simple version.

https://github.com/ClickHouse/ClickHouse/blob/master/src/AggregateFunctions/AggregateFunctionCount.h#L52

**Comment by mzealey** [comment]
Yup that fixes it, a little better than `AggregateFunction` actually:

```
add column total_new SimpleAggregateFunction(sum, UInt64) CODEC(T64, LZ4)

...       total_new       SimpleAggregateFunction(sum, UInt64)    0.7236739151593901      7.997841015209072       2574139486      1.73 GiB  19.17 GiB
```

**Comment by den-crane** [comment]
it needs to be addressed somehow

```sql
SELECT countMerge(x)
FROM
(
    SELECT initializeAggregation('countState', 100) AS x
)

┌─countMerge(x)─┐
│             1 │
└───────────────┘
```

**Comment by azat** [comment]
>it needs to be addressed somehow

Right now it works as expected, `initializeAggregation` accept single value
And you cannot initialize state just from a single value (how `uniqCombined` suppose to work?)

Something like `initializeAggregationArray` can be added, but this will not work fast anyway.

**Comment by amosbird** [comment]
Better to use `SimpleStateFunction(sum, UInt64)` with default value 1. Then you can import the old data directly.

**Comment by alexey-milovidov** [comment]
> Something like initializeAggregationArray can be added

It is named `arrayReduce`.
