### ISSUE TITLE
per-column TTL-like feature to downsample data?

### ISSUE THREAD

**Issue by mzealey** [ClickHouse/ClickHouse#17792]
**Use case**

Lets say we have an `AggregatingMergeTree`, we want 1-minute resolution aggregates for X days, then downsample to 15-min for Y days, 60-min for Z days etc.

**Describe the solution you'd like**

My suggestion would be that similar to per-column TTLs you could do something like

```
  time DateTime
    TTL time + INTERVAL 7 DAY SET time = toStartOfInterval(time, interval 15 minute), -- not sure how this , syntax would work to specify multiple
    TTL time + INTERVAL 14 DAY SET time = toStartOfInterval(time, interval 60 minute)
```

Because it's an `AggregatingMergeTree` it should handle all the aggregations just as `AggregateFunction` does at the moment.

**Describe alternatives you've considered**

`GraphiteMergeTree` provides similar but more complex, more domain-specific rollups whereas `AggregatingMergeTree` is a much more general interface

We could obviously create multiple mat views & rollup tables with different TTLs but this seems pretty inefficient

**Comment by CurtizJ** [comment]
This feature is already implemented. You can set `TTL GROUP BY` for a table  #10537. Data will be aggregated by prefix of the primary key, specified in the `GROUP BY` clause and columns will be updated by aggregate functions, that are specified in the `SET` clause. 

One of possible usage:
```sql
CREATE TABLE metrics 
(
  key UInt64,
  time DataTime,
  bytes UInt64
)
ENGINE=SummingMergeTree()
ORDER BY (key, toStartOfHour(time))
TTL time + INTERVAL 1 HOUR GROUP BY key, toStartOfHour(time)
SET bytes=max(bytes), time = toStartOfHour(any(time));
```

But need to note, that now this feature has several unresolved issues: #17303, #14345.

**Comment by mzealey** [comment]
Yes from #14345 it looks like the PK cannot be updated so it wouldn't actually be downsampling unless we did this in the order by clause

**Comment by den-crane** [comment]
Earlier this was possible by clear_column in SummingMT.
