### ISSUE TITLE
The query sql:'Select * from table where...'  is much faster than sql:'select column1,column2...from table where....'

### ISSUE THREAD

**Issue by taylor131415** [ClickHouse/ClickHouse#17790]
Environment：3shards_1replicas clusters environment.
clickhouse-server version:20.11.3.3

**How to reproduce**
1. create distributed table 'motorvehicle':
（1）Create table motorvehicle_local on cluster perftest_3shards_1replicas (PassTimeHour Int64,DeviceID String,PassTime DateTime64(1,'Asia/Shanghai'),PlateNo String,MotorVehicleID String,StorageUrl1 String,LeftTopX Int64,LeftTopY Int64) ENGINE=MergeTree() order by(PassTimeHour,PassTime,DeviceID) Partition by(modulo(cityHash64(toYYYYMMDD(PassTime), DeviceID), 3))
（2）Create table motorvehicle on cluster perftest_3shards_1replicas as motorvehicle_local ENGINE= Distributed(perftest_3shards_1replicas,default,motorvehicle_local,rand())
2. execute sql：
（1）select * from motorvehicle where PlateNo = '苏E18AX0' and PassTime >= '2019-01-01 00:00:00' and PassTimeHour >= 1546272000 and PassTime <= '2019-01-07 23:59:59' and PassTimeHour <= 1546876799
（2）select PassTime,DeviceID,PlateNo,MotorVehicleID,StorageUrl1 from motorvehicle where PlateNo = '苏E18AX0' and PassTime >= '2019-01-01 00:00:00' and PassTimeHour >= 1546272000 and PassTime <= '2019-01-07 23:59:59' and PassTimeHour <= 1546876799

Compared query time of these two sql, sql(1) is much faster than sql(2). Generally select * would slower than select part columns from table because select * would select all columns.But now 'select *' is much faster and I'm so confused now.
By the way, if left out the condition:'PlateNo = '苏E18AX0'' in these two sql, the sql(2)'s query time would reduce a lot. I don't know what's the matter with the column 'PlateNo'. Looking forward to some reply.

**Comment by l1t1** [comment]
run explain sql
and test to query on motorvehicle_local?

**Comment by taylor131415** [comment]
After changing 'where' to 'prewhere' in sql1, speed  get much faster than before. Close issue.
