### ISSUE TITLE
Openssl: probe different standard paths for ca.

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#17803]
Users from os other than ubuntu often complain that secure connections can not be established because of wrong path to ca is used in the openssl bundled in ClickHouse. 

The solution is to probe common paths for ca (may be that need to be done in Poco), see similar code in rdkafka as example:

https://github.com/edenhill/librdkafka/blob/d5860484fb918d90744222658e4c3f79c6971eb9/src/rdkafka_ssl.c#L845-L937

**Comment by alexey-milovidov** [comment]
BTW, we can also embed root certs into binary to make it more self-contained.
Maybe it is questionable at first glance but if we enable:
- introspection of enabled root CAs via system tables;
- allow to manage them (remove or add more) with config;

it looks reasonable (see for example, Chromium).

**Comment by filimonov** [comment]
Idea itself is ok. But user should have control on that. Few thoughts here.
1. management of embedded certificates can be more painful (imagine you need to update root certs on 100 clickhouse servers, `apt-get install` is much simpler than pushing certs somehow in). 
2. from the other hand installing some clickhouse-specific certs globally in system can also be unsafe. For example once I will install yandex cloud root cert in the system yandex cloud admins can start issuing certificates to 'mybank.com' which will be accepted by different software. So sandboxing the root certs can be nice idea. 

I guess the best option is to make it switchable:
```
<caPath> embedded | probe | /etc/my/path </caPath> 
```

**Comment by alexey-milovidov** [comment]
This issue is still relevant.

**Comment by alexey-milovidov** [comment]
The issue still relevant.

**Comment by cwurm** [comment]
Is this now resolved by https://github.com/ClickHouse/poco/pull/58?

**Comment by yakov-olkhovskiy** [comment]
@cwurm yes
