### ISSUE TITLE
alter update does not work

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#17806]
```
drop table if exists one;
CREATE TABLE one (`id` UInt32,`val` UInt32,`name` String)
ENGINE = MergeTree()
order by id;
insert into one (id, val) values (1,11),(2,12),(3,13);

drop table if exists two;
CREATE TABLE two (`id` UInt32,`word` String)
ENGINE = Join(ANY, LEFT , id);
insert into two values (1,'one'), (3,'three'),(5,'five');

alter table one update name = joinGet('two', 'word', id) where name = '';
```
I want to update the table `one`. But there's no change here. What did I do wrong?
version: 20.10.3.30

_Originally posted by @ygj6 in https://github.com/ClickHouse/ClickHouse/issues/5538#issuecomment-737928085_

**Comment by den-crane** [comment]
@ygj6 check `select table, parts_to_do, is_done from system.mutations`

**Comment by liubo0127** [comment]
joinGet('two','word', id) seems to find the `default.two` table by default, change it to joinGet(‘db.two','word', id) and it is normal.
