### ISSUE TITLE
Can't cast any String decimal to Decimal256

### ISSUE THREAD

**Issue by jmouvill** [ClickHouse/ClickHouse#17828]
**Describe the unexpected behaviour**

Hi,

When trying to cast a String to a `Decimal256`, I encountered 2 different unexpected exceptions:

- The first one is a `Can't compare` exception when casting a decimal with high precision and scale:
```
data :) SELECT CAST('123456789123456789123456789.123456789123456789123456789', 'Decimal256(38)')

SELECT CAST('123456789123456789123456789.123456789123456789123456789', 'Decimal256(38)')


Received exception from server (version 20.11.4):
Code: 407. DB::Exception: Received from 10.170.2.185:9000. DB::Exception: Can't compare. 

0 rows in set. Elapsed: 0.234 sec. 
```

- The second one is a `Decimal math overflow` when trying to cast a simple string decimal, while the casting to `Decimal128` work as intended: 
```
data :) SELECT CAST('1.0', 'Decimal256(38)')

SELECT CAST('1.0', 'Decimal256(38)')


Received exception from server (version 20.11.4):
Code: 407. DB::Exception: Received from 10.170.2.185:9000. DB::Exception: Decimal math overflow: While processing CAST('1.0', 'Decimal256(38)'). 

0 rows in set. Elapsed: 0.196 sec. 

data :) SELECT CAST('1.0', 'Decimal128(18)')

SELECT CAST('1.0', 'Decimal128(18)')

┌─CAST('1.0', 'Decimal128(18)')─┐
│          1.000000000000000000 │
└───────────────────────────────┘

1 rows in set. Elapsed: 0.195 sec. 
```

**How to reproduce**

Please see the above queries to reproduce. 
Server version: `20.11.4`
Client version: `20.10.2.20`

**Expected behavior**
I would expect the casting of both string to `Decimal256(38)` to work and not raise any exception as the numbesr that I'm trying to cast are in the range of the `Decimal256(38)`.

**Error message and/or stacktrace**
2 errors:
```
Code: 407. DB::Exception: Received from 10.170.2.185:9000. DB::Exception: Can't compare. 
```
```
Code: 407. DB::Exception: Received from 10.170.2.185:9000. DB::Exception: Decimal math overflow: While processing CAST('1.0', 'Decimal256(38)'). 
```

**Comment by l1t1** [comment]
https://clickhouse.tech/docs/en/sql-reference/data-types/decimal/ talks about overflow

**Comment by alexey-milovidov** [comment]
I've fixed it :tada: 
#23631
