### ISSUE TITLE
End of line character (0x0A) converted to different non printing character

### ISSUE THREAD

**Issue by RudiAshton** [ClickHouse/ClickHouse#17830]
Is there any reason why "End Of Line" character from input text file is stored as one of the other non printing character (0x00 to 0x1F)?

Given this table:
```
CREATE TABLE l_comment_none (
l_comment String codec(NONE)
)
ENGINE = MergeTree()
ORDER BY l_comment
;
```

When ingesting this text (from CSV):
```
- final requests sle
- ironic grouches cajole over
- quickly regular packages sleep. idly
- regular sheaves sleep along
- regular tithe
-ray furiously un
. accounts are care
```
This is the binary representation of the input text:

![Input_text_marked](https://user-images.githubusercontent.com/75542587/101261558-5bf73500-3749-11eb-88f7-791a10cb9df0.png)

And this is the CH storage file `data/default/l_comment_none/all_1_1_0/l_comment.bin`  for the l_comment_table.
![CH_Store_marked](https://user-images.githubusercontent.com/75542587/101261642-e6d82f80-3749-11eb-88e3-c5fd3b0feaa8.png)

When examining it's binary representation, you can see that the first end of line character '0x0A' (after `- final requests sle`)
Is converted to '0x1D'. This keeps on all occurences of end of line but it is converted to other non printing characters other than '0x1D'.

What is the purpose of this conversion and what do these characters from 0 (0x00) to 31 (0x1F) ASCII stand for? meaning, what is their generation scheme, and where can I find it in the code?

**Comment by alexey-milovidov** [comment]
Strings in binary file are encoded in the following way:
- length of the string in VarUInt format;
- the bytes of the string itself.

If string is unquoted, newline character in CSV is interpreted as record separator and does not belong to the string value.

What you see for special bytes in .bin file - are VarUInt encoded string lengths.
