### ISSUE TITLE
Got Memory limit (for query) exceeded when result set is large

### ISSUE THREAD

**Issue by lucasguo** [ClickHouse/ClickHouse#17839]
I'm doing a query through JDBC on a ReplicatedMergeTree table on a server with 64GB ram.
When the result is approximate 20,000,000 rows, everything goes well.
And in another query, the result is about 80,000,000 rows, the app crashed with exception:

**Code: 241, e.displayText() = DB::Exception: Memory limit (for query) exceeded: would use 9.31 GiB (attempt to allocate chunk of 4300800 bytes), maximum: 9.31 GiB: While executing MergeSortingTransform (version 20.9.2.20 (official build))**

I have checked the config.xml, `max_memory_usage` is not set, so according to the doc, the memory limit is followed by `max_server_memory_usage_to_ram_ratio` which is with default value 0.
So I'm not sure which config limit the memory to 9.31GB, any advice?

**Comment by lucasguo** [comment]
For reference, here is the full config.xml file:

> <?xml version="1.0"?>
> <yandex>
>     <logger>
>         <level>trace</level>
>         <log>/var/log/clickhouse-server/clickhouse-server.log</log>
>         <errorlog>/var/log/clickhouse-server/clickhouse-server.err.log</errorlog>
>         <size>1000M</size>
>         <count>10</count>
>      </logger>
> 
>     <send_crash_reports>
>          <enabled>false</enabled>
>         <anonymize>false</anonymize>
>         <endpoint>https://6f33034cfe684dd7a3ab9875e57b1c8d@o388870.ingest.sentry.io/5226277</endpoint>
>     </send_crash_reports>
> 
>     <http_port>8123</http_port>
>     <tcp_port>9000</tcp_port>
>     <mysql_port>9004</mysql_port>
>     <openSSL>
>         <server>
>             <certificateFile>/etc/clickhouse-server/server.crt</certificateFile>
>             <privateKeyFile>/etc/clickhouse-server/server.key</privateKeyFile>
>             <dhParamsFile>/etc/clickhouse-server/dhparam.pem</dhParamsFile>
>             <verificationMode>none</verificationMode>
>             <loadDefaultCAFile>true</loadDefaultCAFile>
>             <cacheSessions>true</cacheSessions>
>             <disableProtocols>sslv2,sslv3</disableProtocols>
>             <preferServerCiphers>true</preferServerCiphers>
>         </server>
> 
>         <client>
>             <loadDefaultCAFile>true</loadDefaultCAFile>
>             <cacheSessions>true</cacheSessions>
>             <disableProtocols>sslv2,sslv3</disableProtocols>
>             <preferServerCiphers>true</preferServerCiphers>
>             <invalidCertificateHandler>
>                 <name>RejectCertificateHandler</name>
>             </invalidCertificateHandler>
>         </client>
>     </openSSL>
>     <interserver_http_port>9009</interserver_http_port>
>     <listen_host>::</listen_host>
>     <max_connections>4096</max_connections>
>     <keep_alive_timeout>3</keep_alive_timeout>
>     <max_concurrent_queries>100</max_concurrent_queries>
>     <max_server_memory_usage>0</max_server_memory_usage>
>     <max_thread_pool_size>10000</max_thread_pool_size>
>     <max_server_memory_usage_to_ram_ratio>0</max_server_memory_usage_to_ram_ratio>
>     <total_memory_profiler_step>4194304</total_memory_profiler_step>
>     <total_memory_tracker_sample_probability>0</total_memory_tracker_sample_probability>
>     <uncompressed_cache_size>8589934592</uncompressed_cache_size>
>     <mark_cache_size>5368709120</mark_cache_size>
>     <path>/data/clickhouse/</path>
>     <tmp_path>/data/clickhouse/tmp/</tmp_path>
>     <user_files_path>/data/clickhouse/user_files/</user_files_path>
>     <access_control_path>/data/clickhouse/access/</access_control_path>
>     <ldap_servers>
>     </ldap_servers>
>     <users_config>users.xml</users_config>
>     <default_profile>default</default_profile>
>     <custom_settings_prefixes></custom_settings_prefixes>
>     <default_database>default</default_database>
>     <mlock_executable>true</mlock_executable>
>     <remote_servers incl="clickhouse_remote_servers" >
> 	<history_data>
>             <shard>
>                 <replica>
>                     <host>192.169.110.81</host>
>                     <port>9000</port>
> 		    <user>default</user>
> 		    <password>qdPQ0967kb%g</password>
>                 </replica>
>                 <replica>
>                     <host>192.169.110.82</host>
>                     <port>9000</port>
> 		    <user>default</user>
>                     <password>qdPQ0967kb%g</password>
>                 </replica>
>             </shard>
>         </history_data>
>         <test_shard_localhost>
>             <shard>
>                 <replica>
>                     <host>localhost</host>
>                     <port>9000</port>
>                 </replica>
>             </shard>
>         </test_shard_localhost>
>         <test_cluster_two_shards_localhost>
>              <shard>
>                  <replica>
>                      <host>localhost</host>
>                      <port>9000</port>
>                  </replica>
>              </shard>
>              <shard>
>                  <replica>
>                      <host>localhost</host>
>                      <port>9000</port>
>                  </replica>
>              </shard>
>         </test_cluster_two_shards_localhost>
>         <test_cluster_two_shards>
>             <shard>
>                 <replica>
>                     <host>127.0.0.1</host>
>                     <port>9000</port>
>                 </replica>
>             </shard>
>             <shard>
>                 <replica>
>                     <host>127.0.0.2</host>
>                     <port>9000</port>
>                 </replica>
>             </shard>
>         </test_cluster_two_shards>
>         <test_shard_localhost_secure>
>             <shard>
>                 <replica>
>                     <host>localhost</host>
>                     <port>9440</port>
>                     <secure>1</secure>
>                 </replica>
>             </shard>
>         </test_shard_localhost_secure>
>         <test_unavailable_shard>
>             <shard>
>                 <replica>
>                     <host>localhost</host>
>                     <port>9000</port>
>                 </replica>
>             </shard>
>             <shard>
>                 <replica>
>                     <host>localhost</host>
>                     <port>1</port>
>                 </replica>
>             </shard>
>         </test_unavailable_shard>
>     </remote_servers>
>     <remote_url_allow_hosts>
>     </remote_url_allow_hosts>
> 	<include_from>/etc/clickhouse-server/config.d/metrika.xml</include_from>
> 	<zookeeper incl="zookeeper-servers" optional="false"/>
>     <macros>
>         <replica from_env="HOSTNAME" />
>     </macros>
>     <builtin_dictionaries_reload_interval>3600</builtin_dictionaries_reload_interval>
>     <max_session_timeout>3600</max_session_timeout>
>     <default_session_timeout>60</default_session_timeout>
>     <query_log>
>         <database>system</database>
>         <table>query_log</table>
>         <partition_by>toYYYYMM(event_date)</partition_by>
>         <flush_interval_milliseconds>7500</flush_interval_milliseconds>
>     </query_log>
>     <trace_log>
>         <database>system</database>
>         <table>trace_log</table>
> 
>         <partition_by>toYYYYMM(event_date)</partition_by>
>         <flush_interval_milliseconds>7500</flush_interval_milliseconds>
>     </trace_log>
>     <query_thread_log>
>         <database>system</database>
>         <table>query_thread_log</table>
>         <partition_by>toYYYYMM(event_date)</partition_by>
>         <flush_interval_milliseconds>7500</flush_interval_milliseconds>
>     </query_thread_log>
>     <metric_log>
>         <database>system</database>
>         <table>metric_log</table>
>         <flush_interval_milliseconds>7500</flush_interval_milliseconds>
>         <collect_interval_milliseconds>1000</collect_interval_milliseconds>
>     </metric_log>
>     <asynchronous_metric_log>
>         <database>system</database>
>         <table>asynchronous_metric_log</table>
>         <flush_interval_milliseconds>60000</flush_interval_milliseconds>
>     </asynchronous_metric_log>
>     <crash_log>
>         <database>system</database>
>         <table>crash_log</table>
> 
>         <partition_by />
>         <flush_interval_milliseconds>1000</flush_interval_milliseconds>
>     </crash_log>
>     <dictionaries_config>*_dictionary.xml</dictionaries_config>
>     <compression incl="clickhouse_compression">
>     </compression>
>     <distributed_ddl>
>         <path>/clickhouse/task_queue/ddl</path>
>     </distributed_ddl>
>     <graphite_rollup_example>
>         <pattern>
>             <regexp>click_cost</regexp>
>             <function>any</function>
>             <retention>
>                 <age>0</age>
>                 <precision>3600</precision>
>             </retention>
>             <retention>
>                 <age>86400</age>
>                 <precision>60</precision>
>             </retention>
>         </pattern>
>         <default>
>             <function>max</function>
>             <retention>
>                 <age>0</age>
>                 <precision>60</precision>
>             </retention>
>             <retention>
>                 <age>3600</age>
>                 <precision>300</precision>
>             </retention>
>             <retention>
>                 <age>86400</age>
>                 <precision>3600</precision>
>             </retention>
>         </default>
>     </graphite_rollup_example>
>     <format_schema_path>/var/lib/clickhouse/format_schemas/</format_schema_path>
> </yandex>

**Comment by lucasguo** [comment]
For reference, here is the full config.xml

> <?xml version="1.0"?>
> <yandex>
>     <logger>
>         <level>trace</level>
>         <log>/var/log/clickhouse-server/clickhouse-server.log</log>
>         <errorlog>/var/log/clickhouse-server/clickhouse-server.err.log</errorlog>
>         <size>1000M</size>
>         <count>10</count>
>      </logger>
> 
>     <send_crash_reports>
>          <enabled>false</enabled>
>         <anonymize>false</anonymize>
>         <endpoint>https://6f33034cfe684dd7a3ab9875e57b1c8d@o388870.ingest.sentry.io/5226277</endpoint>
>     </send_crash_reports>
> 
>     <http_port>8123</http_port>
>     <tcp_port>9000</tcp_port>
>     <mysql_port>9004</mysql_port>
>     <openSSL>
>         <server>
>             <certificateFile>/etc/clickhouse-server/server.crt</certificateFile>
>             <privateKeyFile>/etc/clickhouse-server/server.key</privateKeyFile>
>             <dhParamsFile>/etc/clickhouse-server/dhparam.pem</dhParamsFile>
>             <verificationMode>none</verificationMode>
>             <loadDefaultCAFile>true</loadDefaultCAFile>
>             <cacheSessions>true</cacheSessions>
>             <disableProtocols>sslv2,sslv3</disableProtocols>
>             <preferServerCiphers>true</preferServerCiphers>
>         </server>
> 
>         <client>
>             <loadDefaultCAFile>true</loadDefaultCAFile>
>             <cacheSessions>true</cacheSessions>
>             <disableProtocols>sslv2,sslv3</disableProtocols>
>             <preferServerCiphers>true</preferServerCiphers>
>             <invalidCertificateHandler>
>                 <name>RejectCertificateHandler</name>
>             </invalidCertificateHandler>
>         </client>
>     </openSSL>
>     <interserver_http_port>9009</interserver_http_port>
>     <listen_host>::</listen_host>
>     <max_connections>4096</max_connections>
>     <keep_alive_timeout>3</keep_alive_timeout>
>     <max_concurrent_queries>100</max_concurrent_queries>
>     <max_server_memory_usage>0</max_server_memory_usage>
>     <max_thread_pool_size>10000</max_thread_pool_size>
>     <max_server_memory_usage_to_ram_ratio>0</max_server_memory_usage_to_ram_ratio>
>     <total_memory_profiler_step>4194304</total_memory_profiler_step>
>     <total_memory_tracker_sample_probability>0</total_memory_tracker_sample_probability>
>     <uncompressed_cache_size>8589934592</uncompressed_cache_size>
>     <mark_cache_size>5368709120</mark_cache_size>
>     <path>/data/clickhouse/</path>
>     <tmp_path>/data/clickhouse/tmp/</tmp_path>
>     <user_files_path>/data/clickhouse/user_files/</user_files_path>
>     <access_control_path>/data/clickhouse/access/</access_control_path>
>     <ldap_servers>
>     </ldap_servers>
>     <users_config>users.xml</users_config>
>     <default_profile>default</default_profile>
>     <custom_settings_prefixes></custom_settings_prefixes>
>     <default_database>default</default_database>
>     <mlock_executable>true</mlock_executable>
>     <remote_servers incl="clickhouse_remote_servers" >
>     <history_data>
>             <shard>
>                 <replica>
>                     <host>192.169.110.81</host>
>                     <port>9000</port>
>                     <user>default</user>
>                     <password>***</password>
>                 </replica>
>                 <replica>
>                     <host>192.169.110.82</host>
>                     <port>9000</port>
>                     <user>default</user>
>                     <password>***</password>
>                 </replica>
>             </shard>
>         </history_data
>     </remote_servers>
>     <remote_url_allow_hosts>
>     </remote_url_allow_hosts>
>     <include_from>/etc/clickhouse-server/config.d/metrika.xml</include_from>
>     <zookeeper incl="zookeeper-servers" optional="false"/>
>     <macros>
>         <replica from_env="HOSTNAME" />
>     </macros>
>     <builtin_dictionaries_reload_interval>3600</builtin_dictionaries_reload_interval>
>     <max_session_timeout>3600</max_session_timeout>
>     <default_session_timeout>60</default_session_timeout>
>     <query_log>
>         <database>system</database>
>         <table>query_log</table>
>         <partition_by>toYYYYMM(event_date)</partition_by>
>         <flush_interval_milliseconds>7500</flush_interval_milliseconds>
>     </query_log>
>     <trace_log>
>         <database>system</database>
>         <table>trace_log</table>
> 
>         <partition_by>toYYYYMM(event_date)</partition_by>
>         <flush_interval_milliseconds>7500</flush_interval_milliseconds>
>     </trace_log>
>     <query_thread_log>
>         <database>system</database>
>         <table>query_thread_log</table>
>         <partition_by>toYYYYMM(event_date)</partition_by>
>         <flush_interval_milliseconds>7500</flush_interval_milliseconds>
>     </query_thread_log>
>     <metric_log>
>         <database>system</database>
>         <table>metric_log</table>
>         <flush_interval_milliseconds>7500</flush_interval_milliseconds>
>         <collect_interval_milliseconds>1000</collect_interval_milliseconds>
>     </metric_log>
>     <asynchronous_metric_log>
>         <database>system</database>
>         <table>asynchronous_metric_log</table>
>         <flush_interval_milliseconds>60000</flush_interval_milliseconds>
>     </asynchronous_metric_log>
>     <crash_log>
>         <database>system</database>
>         <table>crash_log</table>
> 
>         <partition_by />
>         <flush_interval_milliseconds>1000</flush_interval_milliseconds>
>     </crash_log>
>     <dictionaries_config>*_dictionary.xml</dictionaries_config>
>     <compression incl="clickhouse_compression">
>     </compression>
>     <distributed_ddl>
>         <path>/clickhouse/task_queue/ddl</path>
>     </distributed_ddl>
>     <graphite_rollup_example>
>         <pattern>
>             <regexp>click_cost</regexp>
>             <function>any</function>
>             <retention>
>                 <age>0</age>
>                 <precision>3600</precision>
>             </retention>
>             <retention>
>                 <age>86400</age>
>                 <precision>60</precision>
>             </retention>
>         </pattern>
>         <default>
>             <function>max</function>
>             <retention>
>                 <age>0</age>
>                 <precision>60</precision>
>             </retention>
>             <retention>
>                 <age>3600</age>
>                 <precision>300</precision>
>             </retention>
>             <retention>
>                 <age>86400</age>
>                 <precision>3600</precision>
>             </retention>
>         </default>
>     </graphite_rollup_example>
>     <format_schema_path>/var/lib/clickhouse/format_schemas/</format_schema_path>
> </yandex>

**Comment by den-crane** [comment]
https://clickhouse.tech/docs/en/operations/settings/query-complexity/#settings_max_memory_usage

**In the default configuration file, the maximum is 10 GB.**

Check
`select * from system.settings where name = 'max_memory_usage'`

https://clickhouse.tech/docs/en/operations/settings/query-complexity/#settings-max_bytes_before_external_group_by

**Comment by lucasguo** [comment]
Thanks for fast response. Problem resolved. I think get confused with max_server_memory_usage.
