### ISSUE TITLE
Add array functions arrayMin(.), arrayMax(.) and arrayAvg(.)

### ISSUE THREAD

**Issue by rbeeli** [ClickHouse/ClickHouse#17849]
There already exist the functions `least(., .)` and `greatest(., .)` for a variable number of arguments (btw. the docs only show two arguments), and the classic SQL aggregate functions `min(.)`, `max(.)` and `avg(.)`, but there exist no counterparts for arrays, only via `ARRAY JOIN`, which is cumbersome.

I hereby propose to add the array aggregate functions `arrayMin([array])`, `arrayMax([array])` and `arrayAvg([array])` to the collection of array functions.

Those two functions `arrayMin` and `arrayMax` have been mentioned before here: [https://github.com/ClickHouse/ClickHouse/issues/4767](https://github.com/ClickHouse/ClickHouse/issues/4767)

**Use case**
When running analyses based on time windows (`toStartOfInterval`), it is sometimes convenient to work with arrays and perform certain array calculations, i.e. using `arrayMap`, `arraySum`, `arrayFilter` etc. Within this realm, the proposed functions would add a lot of value without having to go through an additional outer query based on `ARRAY JOIN`.

**Describe the solution you'd like**

```
select
	[1,2,3,0,9,-1,5] as arr,
	arrayMin(arr),
	arrayMax(arr),
	arrayAvg(arr)
```

**Describe alternatives you've considered**
Currently, the only solution I'm aware of is via ARRAY JOIN, which becomes cumbersome with more complex queries involving arrays:

```
select min(arr), max(arr), avg(arr)
from (
	select [1,2,3,0,9,-1,5] as arr
)
array join arr
```

**Additional context**
These additions would provide the missing array-counterparts for the top 5 SQL aggregate functions `COUNT`, `SUM`, `AVG`, `MIN`, `MAX`:

```
SQL              ClickHouse       Remarks
---------------------------------------------------------------------------------
COUNT            length           Exists. Maybe add alias arrayCount(.) for consistency reasons?
SUM              arraySum         Exists.
AVG              arrayAvg         Missing!
MIN              arrayMin         Missing!
MAX              arrayMax         Missing!
```

Thanks for the great work.

**Comment by den-crane** [comment]
```
SELECT
    [1, 2] AS arr,
    arrayReduce('min', arr),
    arrayReduce('max', arr),
    arrayReduce('avg', arr)

Query id: f41c09c9-6b7f-49be-ad98-6fb3b1c9840a

┌─arr───┬─arrayReduce('min', [1, 2])─┬─arrayReduce('max', [1, 2])─┬─arrayReduce('avg', [1, 2])─┐
│ [1,2] │                          1 │                          2 │                        1.5 │
└───────┴────────────────────────────┴────────────────────────────┴────────────────────────────┘
```

**Comment by rbeeli** [comment]
Hi @den-crane

Great that there already exists a way of doing this, but unfortunately it's not documented very well, see [https://clickhouse.tech/docs/en/sql-reference/functions/array-functions/#arrayreduce](https://clickhouse.tech/docs/en/sql-reference/functions/array-functions/#arrayreduce). If I search for "min", "max" or "avg", `arrayReduce` never appears, which would be very helpful.

A list of available aggregate functions listed or linked under `arrayReduce` would also greatly help. It looks like all of these functions are supported (great!): [https://clickhouse.tech/docs/en/sql-reference/aggregate-functions/reference/](https://clickhouse.tech/docs/en/sql-reference/aggregate-functions/reference/).

For convenience and since `arraySum` already exists, I think adding `arrayAvg`, `arrayMin`, and `arrayMax` would provide useful shortcuts for the underlying `arrayReduce` implementations, possibly also `arrayCount`.

Could (some) of these points be implemented?
* Update documentation with more examples and link to supported aggregate functions in the `arrayReduce` section
* If possible, searching for "min" / "max" / "avg" should also return `arrayReduce` in the search results (introduction of the `arrayX` functions with a link to `arrayReduce` would also alleviate this and make the user aware of the powerful `arrayReduce` function)
* Add the shortcut alias functions `arrayMin`, `arrayMax`, `arrayAvg`, `arrayCount` for convenience and consistency

**Comment by den-crane** [comment]
JFYI: I don't have an opinion on this. I mentioned `arrayReduce` as a workaround. 
Documentation process is hard. Hundreds of topics and features are not documented at all.

**Comment by rbeeli** [comment]
Hi @den-crane 
I can imagine, it is a lot of work. It's just unfortunate if the end user cannot find functionality that's already there and make use of it, like in my case with `arrayReduce`. If the shortcut alias functions I suggested above get added, I would gladly help with updating the documentation and create a pull request.

**Comment by den-crane** [comment]
@rbeeli  No. I am not a member of CH developing team. I am just a ch community member the same as you.
Yes, it would be nice to see PR with a documentation.

**Comment by alexey-milovidov** [comment]
Implemented by @kitaisreal.
