### ISSUE TITLE
Replicating Replacing Merge - Duplicates/Final

### ISSUE THREAD

**Issue by ben-motiv** [ClickHouse/ClickHouse#1784]
Hello,

I am finding some strange behaviour with a replicatedreplacingmergetree. I need to store time series data and can not have duplicates. I've tried a simple case of loading the exact same dataset of ~1.5million rows twice to test how well it rejects duplicates.

Result - select count(*) from table= ~2.3million rows, so lots of duplicates. Select count(*) from table FINAL - exactly the right number.

So duplicates are being correctly flagged but how do I optimize the database so that they no longer exist without using FINAL? I have tried optimize table <tablename> and it immediately returns OK but with no change to the count, I have also tried optimize table <tablename> deduplicate with the same results.

I understand that optimize should be an intensive process of remerging to sort this out? I'm happy with that as it could be run irregularly as duplicates won't occur in normal service.

How do I force optimize?

Thanks for such an impressive system!

**Comment by ben-motiv** [comment]
Further testing - using ReplacingMergeTree on a single non-replicated machine I found the optimize table <tablename> works, but only if run a number of times in succession. Rapidly calling it ~10 times from tabix will see it successful.

Logs don't suggest any reason for this. Each time I run it I see it do some tidying, so not sure what is going on. Just running it once and leaving it alone doesn't seem to work, 2 or 3 times will see the count(*) reducing but still not fully deduplicated. 10+ times seems to deduplicate completely on this dataset.

**Comment by ben-motiv** [comment]
Further - Trying again on a ReplicatedReplacingMergeTree across two servers. Optimize returns OK on one machine, but doesn't do anything, and on the 2nd machine it complains that the user password is not correct (use the same users.xml, and all DDL 'on cluster' statements work fine, and the data has replicated, so not sure why?) 

Either way, I can't optimize a replicatedreplacingmergetree. I can't get rid of the duplicates.

**Comment by ben-motiv** [comment]
Temporary solution:
Select
  partition,
  partCount
from(
    SELECT
      partition,
      count(*) as partCount
    FROM
      system.parts
    WHERE
      active
      AND (table = 'TABLE')
    group by
      partition
  )
where
  partCount > 1

And run optimize table <TABLE> partition <PARTITION> final. This runs rapidly and seems to force a consolidation of each in turn. Runs in <2 seconds on 3 million duplicates. This works on a ReplicatedReplacingMergeTree on two servers.

**Comment by savelov** [comment]
> Further - Trying again on a ReplicatedReplacingMergeTree across two servers. Optimize returns OK on one machine, but doesn't do anything, and on the 2nd machine it complains that the user password is not correct (use the same users.xml, and all DDL 'on cluster' statements work fine, and the data has replicated, so not sure why?)
> 
> Either way, I can't optimize a replicatedreplacingmergetree. I can't get rid of the duplicates.

does this PR fixes the optimize() error on the second box? https://github.com/yandex/ClickHouse/pull/3742

**Comment by viongpanzi** [comment]
@savelov 
#3742 will work for ReplicatedMergeTree, but I'm not sure also work for ReplicatedReplacingMergeTree

**Comment by xmariachi** [comment]
I found the same issue here, though in my case I am finding duplicates in a ReplicatedReplacingMergeTree even when running it as `OPTIMIZE TABLE tbl FINAL`.
Optimization returns OK but no changes are made on duplicates, still the same number. Is this because of being a Replicated* table?

**Comment by den-crane** [comment]
@xmariachi try

in clickhouse-client:
```
set optimize_throw_if_noop = 1;
OPTIMIZE TABLE tbl FINAL;
```
In this case you'll get a message with a reason why merge could not start.

**Comment by xmariachi** [comment]
Thanks. 
I've found this issue in the logs - may it be the cause? I replied in that permalink where you can see the problem: 
https://github.com/yandex/ClickHouse/issues/6472#issuecomment-527967770

**Comment by xmariachi** [comment]
I upgraded servers to match the same version. I no longer see those errors.
However, the behaviour is still the same: data doesn't get compacted. 
The query finishes fast: 

```
OPTIMIZE TABLE tbl FINAL
Ok.

0 rows in set. Elapsed: 2.502 sec. 
```
However, the table does not do data compaction, or at least not on a certain set of data where duplicates are. Having set the `optimize_throw_if_noop` , nothing gets printed in the logs.

Table is a ReplicatedReplacingMergeTree.

**Comment by NanoBjorn** [comment]
@xmariachi are you sure that primary / order by keys are set correctly and you checking corresponding uniqueness?

**Comment by xmariachi** [comment]
Hi @NanoBjorn, yes, I think so. It works fine with duplicates on smaller table sizes.

**Comment by blinkov** [comment]
@ben-motiv, do you have any further questions?

**Comment by Boris-Barboris** [comment]
We also have this problem on about 200 million rows, OPTIMIZE in any shape and form does nothing and old rows are still duplicated. SELECT FINAL does not help as well.
ClickHouse client version 19.17.2.4 (official build).

**Comment by qoega** [comment]
After successful run of
```
set optimize_throw_if_noop = 1;
OPTIMIZE TABLE tbl FINAL;
```
that was done after replication is done I would expect no duplicates should be guaranteed.

**Comment by Boris-Barboris** [comment]
Why is this closed?
Optimize still does not merge rows on 20.3.8.53 in our case.

**Comment by wozuo** [comment]
Hi everyone, I have the same problem with ReplacingMergeTree - SELECT FINAL works (deduplicates correctly and only shows unique values) but  as soon as I remove the "FINAL" from the SELECT query the duplicates show back up. Running 
``` 
set optimize_throw_if_noop = 1;
OPTIMIZE TABLE mytable FINAL;
```
does not solve the issue. No errors are returned but no rows were modified. Is there a way to guarantee that duplicates are removed?
