### ISSUE TITLE
How can disable CH client echo whatever print when in bash mode

### ISSUE THREAD

**Issue by yuxin-jdwt** [ClickHouse/ClickHouse#17844]
clickhouse-client will echo whatever i print when used in bash mode.How can i disable it?

**Comment by den-crane** [comment]
What do you mean? What is bash mode?

```
echo "select 1" |clickhouse-client
1
```

**Comment by l1t1** [comment]
I think he means the bold part
localhost :) select count(*) from numbers_mt(100000)a,numbers_mt(100000)b;

***SELECT count(*)
FROM numbers_mt(100000) AS a
, numbers_mt(100000) AS b
***
Query id: e6d36818-9d22-46ce-b156-5b9c2fef0117

┌─────count()─┐
│ 10000000000 │
└─────────────┘

**Comment by yuxin-jdwt** [comment]
@den-crane，emmm。。。，when use the clickhouse-client command
what i print will print twice on the console,like this
i find Command Line Options --echo  but how can disable it? 
$ clickhouse-client
:)ss

3Q

**Comment by den-crane** [comment]
I think no way to suppress echo in interactive mode.

**Comment by l1t1** [comment]
you can use a mysql client to connect clickhouse

**Comment by l1t1** [comment]
or you can comment out the souce code of echo inout and comiple ch
