### ISSUE TITLE
Executable file size problem after clickhoue compilation

### ISSUE THREAD

**Issue by xhsky** [ClickHouse/ClickHouse#17852]
**Operating system**
kernel version: 3.10.0-862.14.4.el7.x86_64
I use docker to install the image of ubuntu20 and compile it in the container

**Cmake version**
cmake version 3.16.3

**Ninja version**
1.10.0

**Compiler name and version**
CC=gcc-10
CXX=g++-10

I compile according to the document(https://clickhouse.tech/docs/en/development/build/#how-to-build-clickhouse-for-development), After compiling, a 3.7G clickhouse file will be generated in the build/programs/ directory. The size difference between the file and the installation package provided on the official website is too large. Are other files compiled? How to reduce the executable file size

**Comment by filimonov** [comment]
It is release build with debug info. Just strip debug symbol (`strip --strip-debug executable`) if you need more compact binary.

**Comment by xhsky** [comment]
thank you, filimonov. it works!

**Comment by l1t1** [comment]
what is the option of make

**Comment by alexey-milovidov** [comment]
@l1t1 It is done after build with a separate command (strip or objcopy).
If you want to get the same result during build, you can compile without debug info (Release instead of RelWithDebInfo mode in CMake).
