### ISSUE TITLE
After drop table, create same name(zoo path) replicated table immediately , report error

### ISSUE THREAD

**Issue by JKeyZ** [ClickHouse/ClickHouse#17850]
when I drop replicated table, and create it immediately, server reported table exists. but not found the same case in old version.
config file was using install sample , replace data folder, marcos, remote_servers  and  zk config only

marcos:
```xml
     <macros>
          <layer>01</layer>
          <shard>01</shard>
          <replica>chserver0</replica>
     </macros>
```

remote_servers:
```xml
<remote_servers>
     <click_dist>
         <shard>
             <weight>1</weight>
             <internal_replication>true</internal_replication>
             <replica>
                 <priority>1</priority>
                 <host>chserver0</host>
                 <port>9000</port>
             </replica>
             <replica>
                 <host>chserver1</host>
                 <port>9000</port>
             </replica>
         </shard>
     </click_dist>
 </remote_servers>
```

create table ddl:
> CREATE TABLE streams.streams_apps_ext_log_test on cluster click_dist
> (
>     `server_date` DateTime COMMENT 'server_date',
>     `date` String COMMENT 'date',
>     `channel` String COMMENT 'channel',
>     `language` String COMMENT 'language',
>     `latitude` String COMMENT 'latitude',
>     `longitude` String COMMENT 'longitude',
>     `imsi` String COMMENT 'imsi',
>     `deviceid` String COMMENT 'deviceid',
>     `resolution` String COMMENT 'resolution',
>     `platform` String COMMENT 'platform'
> )
> ENGINE = ReplicatedMergeTree('/clickhouse/tables/{layer}-{shard}/streams.streams_apps_ext_log_test', '{replica}')
> PARTITION BY toYYYYMMDD(server_date)
> ORDER BY (server_date, deviceid)
> TTL server_date + toIntervalDay(7)
> SETTINGS index_granularity = 8192;

drop table ddl:
> 
drop table streams.streams_apps_ext_log_test on cluster click_dist

found error version: ClickHouse server version 20.11.4.13 (official build) / zk version: 3.5.8
old version: ClickHouse server version 20.5.2.7 (official build).

**Comment by den-crane** [comment]
This is a behavior related to Atomic database engine.
When a table in Atomic database been dropped it is not removed immediately but after 480s.

```
config.xml
<database_atomic_delay_before_drop_table_sec>480</database_atomic_delay_before_drop_table_sec>
```
https://github.com/ClickHouse/ClickHouse/blob/master/tests/config/config.d/database_atomic.xml 

You can 
1. use ordinary database instead of atomic. `create database ... Engine=Ordinary.
2. use uniq ZK path `/clickhouse/tables/{layer}-{shard}-{uuid}/streams.streams_apps_ext_log_test`
3. reduce `database_atomic_delay_before_drop_table_sec = 0;` &  `drop table ... sync`

**Comment by JKeyZ** [comment]
thank u, den-crane. it's work. 
is default engine ordinary in old version(20.5.2.7), atomic in newly?

**Comment by den-crane** [comment]
Atomic is default engine starting from 20.11

**Comment by JKeyZ** [comment]
thank u for help
