### ISSUE TITLE
Non-standard environments clickhouse available features

### ISSUE THREAD

**Issue by xhsky** [ClickHouse/ClickHouse#17853]
We are preparing to use the aarch64 environment to install clickhosue. 
However，It is mentioned in this document（https://clickhouse.tech/docs/en/getting-started/install/#from-binaries-non-linux） that only some features of clickhouse are available in a non-standard environment. Which features are available? Or which features are not available?

**Comment by den-crane** [comment]
I think https://github.com/ClickHouse/ClickHouse/blob/master/cmake/target.cmake#L30

these will be unavailable 

             set (ENABLE_PROTOBUF OFF CACHE INTERNAL "")
            set (ENABLE_GRPC OFF CACHE INTERNAL "")
            set (ENABLE_PARQUET OFF CACHE INTERNAL "")
            set (ENABLE_ORC OFF CACHE INTERNAL "")
            set (ENABLE_MYSQL OFF CACHE INTERNAL "")

maybe kafka too

**Comment by alexey-milovidov** [comment]
@xhsky The most easy way to check is to use `SELECT * FROM system.build_options` query.

**Comment by alexey-milovidov** [comment]
You will see explicit list of the disabled features.
