### ISSUE TITLE
Dropping insignificant (tail) items from an AggregatingMergeTree ?

### ISSUE THREAD

**Issue by mzealey** [ClickHouse/ClickHouse#17862]
I'm sure there must be a solution to this, but if we have an `AggregatingMergeTree` collating details of something like path hits by `toStartOfInterval(time, xxx)`, is it easily possible to make it so that it only keeps the top X per time interval where X is in the order of 10k-100k and drop all the tail stuff? So something like a TTL but for a `select item, count() total where time = xxx order by total desc limit 10000` drop anything that isn't in that query? Obviously this is possible to automate using periodically executed manual sql to only copy top items to another table but is there an in-clickhouse way?

**Comment by den-crane** [comment]
Try TTL where. 
It will not give pure result because it operates in a scope of parts in the merge. But eventually it will.

**Comment by alexey-milovidov** [comment]
I remember similar use case that we faced in Yandex.Metrica when we were storing aggregated data.
E.g. keep only top 10000 URLs for every batch of inserted data.

But it was before we started using ClickHouse.
After migrated to ClickHouse, we just decided to not aggregate data at all :rofl: 

Nevertheless, it is possible to solve this task with periodic ALTER DELETE.
