### ISSUE TITLE
insert select * from (select col_1 from t) works much faster than insert select col_1 from t 

### ISSUE THREAD

**Issue by nblagodarnyi** [ClickHouse/ClickHouse#17872]
**Describe the situation**
insert-select with intermediate senseless select work ~10 times faster than insert-select without intermediate senseless select

**How to reproduce**
* Which ClickHouse server version to use
ClickHouse server version 20.8.7 revision 54438.
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"

* Which interface to use, if matters
ClickHouse client version 20.8.7.15 (official build).
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
CREATE TABLE test_hang_target_1 on cluster core (`ID` Int64) engine = MergeTree() ORDER BY ("ID");
CREATE TABLE test_hang_target_2 on cluster core (`ID` Int64) engine = MergeTree() ORDER BY ("ID");
CREATE TABLE test_hang_source_1 on cluster core
(  `ID` Int64,
    N1 Int64,
    N2 Int64,
    N3 Int64,
    N4 Int64,
    N5 Int64
) engine = MergeTree() ORDER BY ("ID");
CREATE TABLE test_hang_source_2 on cluster core
(  `ID` Int64,
    N1 Int64,
    N2 Int64,
    N3 Int64,
    N4 Int64,
    N5 Int64
) engine = MergeTree() ORDER BY ("ID");

* Sample data for all these tables, use [clickhouse-obfuscator]
INSERT INTO test_hang_source_1 select number, number+1, number+2, number+3, number+4, number+5 from numbers(100000000);
INSERT INTO test_hang_source_2 select number, number+1, number+2, number+3, number+4, number+5 from numbers(100000000);
* Queries to run that lead to slow performance
INSERT INTO test_hang_target_1 SELECT SUM( t1.ID + t1.N1 + t1.N2 + t1.N3 + t1.N4 + t1.N5 ) s from test_hang_source_1 t1;
INSERT INTO test_hang_target_2 SELECT * FROM ( SELECT SUM( t1.ID + t1.N1 + t1.N2 + t1.N3 + t1.N4 + t1.N5 ) s from test_hang_source_2 t1 );

**Expected performance**
First insert should not work ten times slower, than second. Their working time should be same

**Additional context**
I tested it on 12 servers with the script below. 
export CH_PWD=\/ery$tr0ngPa$$w0rd
for (( i=1; i <= 12; i++ ))
do
  size=${#i}
  if [ $size -eq 1 ];then
    server="clickhouse0$i"
  else
    server="clickhouse$i"
  fi
  echo "Start testing on $server"
  
  query="/*$server*/ INSERT INTO test_hang_source_1 select number, number+1, number+2, number+3, number+4, number+5 from numbers(100000000)"
  echo "  $query"
  clickhouse-client --host $server --user amilovidov --password $CH_PWD --multiline --secure --time --query "$query"
  echo "+++++++++++++++++++++"

  query="/*$server*/ INSERT INTO test_hang_source_2 select number, number+1, number+2, number+3, number+4, number+5 from numbers(100000000)" 
  echo "  $query"
  clickhouse-client --host $server --user amilovidov --password $CH_PWD --multiline --secure --time --query "$query"
  echo "+++++++++++++++++++++"

  query="/*$server*/ INSERT INTO test_hang_target_1 SELECT SUM( t1.ID + t1.N1 + t1.N2 + t1.N3 + t1.N4 + t1.N5 ) s from test_hang_source_1 t1"
  echo "  $query"
  clickhouse-client --host $server --user amilovidov --password $CH_PWD --multiline --secure --time --query "$query"
  echo "+++++++++++++++++++++"

  query="/*$server*/ INSERT INTO test_hang_target_2 SELECT * FROM ( SELECT SUM( t1.ID + t1.N1 + t1.N2 + t1.N3 + t1.N4 + t1.N5 ) s from test_hang_source_2 t1 )"
  echo "  $query"
  clickhouse-client --host $server --user amilovidov --password $CH_PWD --multiline --secure --time --query "$query"
  echo "+++++++++++++++++++++"

  echo "End testing on $server"
  echo ""
  echo "-------------------------------------------------------------------------------"
  echo ""
done

**Comment by nblagodarnyi** [comment]
Everything is ok in ClickHouse server version 19.16.2 revision 54427. 

clickhouse02 :) INSERT INTO tmp.test_hang_target_1 SELECT SUM( t1.ID + t1.N1 + t1.N2 + t1.N3 + t1.N4 + t1.N5 ) s from tmp.test_hang_source_1 t1;

INSERT INTO tmp.test_hang_target_1 SELECT SUM(((((t1.ID + t1.N1) + t1.N2) + t1.N3) + t1.N4) + t1.N5) AS s
FROM tmp.test_hang_source_1 AS t1

Ok.

0 rows in set. Elapsed: 1.171 sec. Processed 100.00 million rows, 4.80 GB (85.42 million rows/s., 4.10 GB/s.)

clickhouse02 :) INSERT INTO tmp.test_hang_target_2 SELECT * FROM ( SELECT SUM( t1.ID + t1.N1 + t1.N2 + t1.N3 + t1.N4 + t1.N5 ) s from tmp.test_hang_source_2 t1 );

INSERT INTO tmp.test_hang_target_2 SELECT *
FROM
(
    SELECT SUM(((((t1.ID + t1.N1) + t1.N2) + t1.N3) + t1.N4) + t1.N5) AS s
    FROM tmp.test_hang_source_2 AS t1
)

Ok.
0 rows in set. Elapsed: 0.525 sec. Processed 100.00 million rows, 4.80 GB (190.40 million rows/s., 9.14 GB/s.)

**Comment by den-crane** [comment]
20.13.1.5273

```sql
CREATE TABLE test (ID Int64) engine = Null;

INSERT INTO test 
SELECT * FROM ( SELECT SUM( (materialize(number) as x) + materialize(x) +  materialize(x+2) +  materialize(x+3) +  materialize(x+4) ) s from numbers_mt(100000000));

Elapsed: 0.037 sec.


INSERT INTO test 
SELECT SUM( (materialize(number) as x) + materialize(x+1) +  materialize(x+2) +  materialize(x+3) +  materialize(x+4) ) s from numbers_mt(100000000);

Elapsed: 0.827 sec.

```

**Comment by KochetovNicolai** [comment]
https://github.com/ClickHouse/ClickHouse/blob/9be5fa9ef23ab8b82e79601daa5d2ecffc71667e/src/Interpreters/InterpreterInsertQuery.cpp#L280-L290

#14005

```
INSERT INTO test SELECT SUM(((((materialize(number) AS x) + materialize(x + 1)) + materialize(x + 2)) + materialize(x + 3)) + materialize(x + 4)) AS s
FROM numbers_mt(100000000)

Query id: 1931b783-b829-4555-b2be-49635fcae6b8

Ok.

0 rows in set. Elapsed: 1.734 sec. Processed 100.66 million rows, 805.28 MB (58.04 million rows/s., 464.31 MB/s.) 


INSERT INTO test SELECT SUM(((((materialize(number) AS x) + materialize(x + 1)) + materialize(x + 2)) + materialize(x + 3)) + materialize(x + 4)) AS s
FROM numbers_mt(100000000)
SETTINGS optimize_trivial_insert_select = 0

Query id: c342ae81-5ea9-4eba-a891-221fa7efd6aa

Ok.

0 rows in set. Elapsed: 0.234 sec. Processed 100.00 million rows, 800.00 MB (427.67 million rows/s., 3.42 GB/s.) 
```

**Comment by Algunenano** [comment]
The ticket was tagged as `st-wontfix` but it's apparently fixed, because I get the same perf in both queries (with both old and new analyzer)
