### ISSUE TITLE
Confusing error instead of diagnostic when columns not-under-aggregate-function come from a join

### ISSUE THREAD

**Issue by adrian17** [ClickHouse/ClickHouse#17873]
Tested on 20.10.5:

```sql
SELECT
    base.number,
    second.number
from numbers(10) as base
join numbers(10) as second on base.number=second.number
GROUP BY base.number with rollup
```

I get an error: 
> DB::Exception: Not found column second.number in block. There are only columns: number.

What I expected to see:

> DB::Exception: Column `second.number` is not under aggregate function and not in GROUP BY.

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/4222
