### ISSUE TITLE
How to install clickhouse under normal user permissions

### ISSUE THREAD

**Issue by physili** [ClickHouse/ClickHouse#17884]
How to install clickhouse under normal user permissions

**Comment by l1t1** [comment]
you need sudo

**Comment by physili** [comment]
Sudo asked me for root password。But the company does not provide a root password

**Comment by physili** [comment]
> you need sudo
Sudo asked me for root password。But the company does not provide a root password

**Comment by physili** [comment]
Sudo asked me for root password。But the company does not provide a root password

**Comment by den-crane** [comment]
@physili not related to CH. 
Package management requires root privs. If your company  not provide a root password probably it's for a reason.

You can use CH without installation. Downoad server binary or tar with binary Linux tgz package clickhouse-server-20.13.1.5343.tgz https://github.com/ClickHouse/ClickHouse/releases

**Comment by alexey-milovidov** [comment]
@l1t1 ClickHouse can be run without sudo. See the comment from den-crane above.

**Comment by alexey-milovidov** [comment]
Example here: https://clickhouse.tech/docs/en/operations/performance-test/

**Comment by l1t1** [comment]
> Example here: https://clickhouse.tech/docs/en/operations/performance-test/
cannot find the link mentioned.  could you post a picture about this?

Click on the first green check mark or red cross with green “ClickHouse Build Check” and click on the “Details” link near “ClickHouse Build Check”. There is no such link in some commits, for example commits with documentation. In this case, choose the nearest commit having this link

**Comment by l1t1** [comment]
```
root1234@LAPTOP-TJ9I4Q1C:~$ cd /tmp
root1234@LAPTOP-TJ9I4Q1C:~$ tar xf  /mnt/d/ch/clickhouse-common-static-20.12.3.3.tgz
root1234@LAPTOP-TJ9I4Q1C:/tmp$ ls

clickhouse-common-static-20.12.3.3

root1234@LAPTOP-TJ9I4Q1C:/tmp$ cd *3

root1234@LAPTOP-TJ9I4Q1C:/tmp/clickhouse-common-static-20.12.3.3$ cd usr/bin

root1234@LAPTOP-TJ9I4Q1C:/tmp/clickhouse-common-static-20.12.3.3/usr/bin$ ls

clickhouse                      data              format_schemas    preprocessed_configs  tmp

clickhouse-extract-from-config  dictionaries_lib  metadata          status                user_files

clickhouse-odbc-bridge          flags             metadata_dropped  store

root1234@LAPTOP-TJ9I4Q1C:/tmp/clickhouse-common-static-20.12.3.3/usr/bin$ ./clickhouse client

ClickHouse client version 20.12.3.3 (official build).

Connecting to localhost:9000 as user default.

Code: 210. DB::NetException: Connection refused (localhost:9000)



root1234@LAPTOP-TJ9I4Q1C:/tmp/clickhouse-common-static-20.12.3.3/usr/bin$ nohup ./clickhouse server &

[1] 18

root1234@LAPTOP-TJ9I4Q1C:/tmp/clickhouse-common-static-20.12.3.3/usr/bin$ nohup: ignoring input and appending output to 'nohup.out'



root1234@LAPTOP-TJ9I4Q1C:/tmp/clickhouse-common-static-20.12.3.3/usr/bin$ ./clickhouse client

ClickHouse client version 20.12.3.3 (official build).

Connecting to localhost:9000 as user default.

Connected to ClickHouse server version 20.12.3 revision 54442.



LAPTOP-TJ9I4Q1C.localdomain :)
```
