### ISSUE TITLE
Dictionaries not updated on time

### ISSUE THREAD

**Issue by aubweb9** [ClickHouse/ClickHouse#17889]
Hello,

I have some dictionaries that are not updated on time and/or are displaying a wrong last_successful_update_time (1970-01-01 01:00:00) in the system.dictionaries table.
Last_exception column is empty.
All my dictionaries are sourced by MySQL.

Here's one example : 

`CREATE DICTIONARY dict_ref_sc_grp
(

    `sc_grp` String DEFAULT '',

    `sc_grp_order` Float32,

    `sc_attribute` String DEFAULT '',

    `sc_type` String DEFAULT '',

    `sc_sub_type` String DEFAULT ''
)
PRIMARY KEY sc_grp
SOURCE(MYSQL(HOST 'xxx' PORT 3306 USER 'xxx' PASSWORD 'xxx' DB 'grouping' TABLE 'ref_sc_grp'))
LIFETIME(MIN 0 MAX 3600)
LAYOUT(COMPLEX_KEY_HASHED());`

Data in system.dictionaries (pulled now) :

#	Value
database	summary
name	dict_ref_sc_grp
uuid	00000000-0000-0000-0000-000000000000
status	LOADED
origin	summary.dict_ref_sc_grp
type	ComplexKeyHashed
key	(String)
attribute.names	['sc_grp_order','sc_attribute','sc_type','sc_sub_type']
attribute.types	['Float32','String','String','String']
bytes_allocated	56440
query_count	5554923941
hit_rate	1.0
element_count	12
load_factor	0.046875
source	MySQL: grouping.ref_sc_grp
lifetime_min	0
lifetime_max	3600
loading_start_time	'2020-12-07 14:09:56.000'
last_successful_update_time	'2020-12-07 14:09:56.000'    **---> > 3600 seconds**
loading_duration	0.013
last_exception	

CH : version 20.11.3.3

Thanks,
Aubry

**Comment by den-crane** [comment]
Do you use mysql8?

https://github.com/ClickHouse/ClickHouse/issues/11475#issuecomment-643292140
Need to enable `set global information_schema_stats_expiry=0;`  in mysql

**Comment by aubweb9** [comment]
Yes we do.

Thanks I will modify the variable (which has currently a default value of 86400)

👍
