### ISSUE TITLE
how to make groupArray more faster?

### ISSUE THREAD

**Issue by vegastar002** [ClickHouse/ClickHouse#17885]
My query result has 1 million and need to page it,  now implemented by groupArray, but it is slow, is there any way to make it faster ?
eg, when click page "3" , I need return No. 31~40 row.

**Comment by l1t1** [comment]
plz post the full sql

**Comment by den-crane** [comment]
Do not use groupArray for this.

```
create table temp(A Int64) Engine=Log;
insert into temp select * from numbers_mt(100000000);
select * from temp limit 10 offset 99000000;
10 rows in set. Elapsed: 0.124 sec. Processed 99.08 million rows,
```

**Comment by vegastar002** [comment]
yes, finally I found can use this way to page
