### ISSUE TITLE
I encountered this error. The query is unavailable. After restart, the data is cleared and all tables in the library are automatically rebuilt

### ISSUE THREAD

**Issue by xiaojing413332** [ClickHouse/ClickHouse#17890]
2020.12.08 11:37:05.492095 [ 16977 ] {f7e0c126-a6cc-465c-ade4-5995d1263729} <Error> executeQuery: Code: 1002, e.displayText() = DB::Exception: Master maybe lost (version 20.10.5.10 (official build)) (from 127.0.0.1:57532) (in query: select count(*) from candidate_apply_record ;), Stack trace (when copying this message, always include the lines below):

0. DB::MySQLReplication::MySQLFlavor::readPayloadImpl(DB::ReadBuffer&) @ 0xdae6c1a in /usr/bin/clickhouse
1. DB::MySQLProtocol::IMySQLReadPacket::readPayload(DB::ReadBuffer&, unsigned char&) @ 0xdacef2d in /usr/bin/clickhouse
2. DB::MySQLProtocol::PacketEndpoint::tryReceivePacket(DB::MySQLProtocol::IMySQLReadPacket&, unsigned long) @ 0xdacfa33 in /usr/bin/clickhouse
3. DB::MaterializeMySQLSyncThread::synchronization(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xdaf9bb6 in /usr/bin/clickhouse
4. ? @ 0xdb159bd in /usr/bin/clickhouse
5. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x7b8963d in /usr/bin/clickhouse
6. ? @ 0x7b8d153 in /usr/bin/clickhouse
7. start_thread @ 0x7dc5 in /usr/lib64/libpthread-2.17.so
8. clone @ 0xf621d in /usr/lib64/libc-2.17.so

2020.12.08 11:37:05.492328 [ 16977 ] {f7e0c126-a6cc-465c-ade4-5995d1263729} <Error> TCPHandler: Code: 1002, e.displayText() = DB::Exception: Master maybe lost, Stack trace:

0. DB::MySQLReplication::MySQLFlavor::readPayloadImpl(DB::ReadBuffer&) @ 0xdae6c1a in /usr/bin/clickhouse
1. DB::MySQLProtocol::IMySQLReadPacket::readPayload(DB::ReadBuffer&, unsigned char&) @ 0xdacef2d in /usr/bin/clickhouse
2. DB::MySQLProtocol::PacketEndpoint::tryReceivePacket(DB::MySQLProtocol::IMySQLReadPacket&, unsigned long) @ 0xdacfa33 in /usr/bin/clickhouse
3. DB::MaterializeMySQLSyncThread::synchronization(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xdaf9bb6 in /usr/bin/clickhouse
4. ? @ 0xdb159bd in /usr/bin/clickhouse
5. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x7b8963d in /usr/bin/clickhouse
6. ? @ 0x7b8d153 in /usr/bin/clickhouse
7. start_thread @ 0x7dc5 in /usr/lib64/libpthread-2.17.so
8. clone @ 0xf621d in /usr/lib64/libc-2.17.so

2020.12.08 16:13:01.687691 [ 16977 ] {bfe5662c-663b-47bb-b81a-6b4b773759f3} <Error> executeQuery: Code: 1002, e.displayText() = DB::Exception: Master maybe lost (version 20.10.5.10 (official build)) (from 127.0.0.1:50326) (in query: select count(*) from candidate_apply_record ;), Stack trace (when copying this message, always include the lines below):

0. DB::MySQLReplication::MySQLFlavor::readPayloadImpl(DB::ReadBuffer&) @ 0xdae6c1a in /usr/bin/clickhouse
1. DB::MySQLProtocol::IMySQLReadPacket::readPayload(DB::ReadBuffer&, unsigned char&) @ 0xdacef2d in /usr/bin/clickhouse
2. DB::MySQLProtocol::PacketEndpoint::tryReceivePacket(DB::MySQLProtocol::IMySQLReadPacket&, unsigned long) @ 0xdacfa33 in /usr/bin/clickhouse
3. DB::MaterializeMySQLSyncThread::synchronization(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xdaf9bb6 in /usr/bin/clickhouse
4. ? @ 0xdb159bd in /usr/bin/clickhouse
5. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x7b8963d in /usr/bin/clickhouse
6. ? @ 0x7b8d153 in /usr/bin/clickhouse
7. start_thread @ 0x7dc5 in /usr/lib64/libpthread-2.17.so
8. clone @ 0xf621d in /usr/lib64/libc-2.17.so

**Comment by zhang2014** [comment]
We will synchronize the full data when the database is first create or not found binlog file in MySQL after restart.
