### ISSUE TITLE
change clickhosue primary key and order by config

### ISSUE THREAD

**Issue by shadowDy** [ClickHouse/ClickHouse#17901]
Hello!
It would be nice to have support for change of columns included in primary key and order by。
Now we have to create a new table, copy the data to it using the INSERT SELECT, rename table to the old name. 
for example:
ALTER TABLE [db].name [ON CLUSTER cluster] MODIFY ORDER BY new_expression
this command can only changes the sorting key of the table to new_expression，Primary key remains the same.

if it can modify the sorting key and primary key at new tuples（exist columns），That will save a lot of time。

**Comment by den-crane** [comment]
a new feature "ALTER PRIMARY KEY" is planned on 2021
https://github.com/ClickHouse/ClickHouse/issues/17623

**Comment by IVitamin-C** [comment]
Can an existing column be added to the order by ()

**Comment by malikas05** [comment]
Hi @den-crane. Where is it possible to track the progress of the development of this feature?

**Comment by chayuto** [comment]
Is this feature available now? (Jan2023)
