### ISSUE TITLE
Forbid alter TTL on tables created with old syntax.

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#17904]

**Comment by spongedu** [comment]
Why not support ALTER TTL on tables created with old syntax ?

**Comment by ucasFL** [comment]
It seems this only can be distinguished at the time of create table, so if we want to forbid alter TTL on tables created with old syntax, maybe we need to add a flag to `StorageMetaDataInMemory`.

**Comment by CurtizJ** [comment]
Done in #19064.

**Comment by CurtizJ** [comment]
> Why not support ALTER TTL on tables created with old syntax ?

Because TTL definition is stored in table expression, but old syntax doesn't allow it.
