### ISSUE TITLE
build clickhouse20.8.6 error on aarch64

### ISSUE THREAD

**Issue by miaojianxin** [ClickHouse/ClickHouse#17911]
I  compile clickhouse on platform aarch64， i got an error：
../base/daemon/BaseDaemon.cpp: In member function ‘virtual void SignalListener::run()’:
../base/daemon/BaseDaemon.cpp:257:5: error: the frame size of 20512 bytes is larger than 16384 bytes [-Werror=frame-larger-than=]
  257 |     }
      |     ^
how should i modify the makefile to avoid this mistake? thank you

**Comment by alexey-milovidov** [comment]
Remove the following line:

```
cmake/warnings.cmake
27:    add_warning(frame-larger-than=65536)
```
