### ISSUE TITLE
distinct is much slower than group by

### ISSUE THREAD

**Issue by poppinlr** [ClickHouse/ClickHouse#17916]
```
select
  columnName
from
  tableA
where
  columnName global in (
    select
      columnName
    FROM
      tableB
    where
      condition
    group by
      columnName
  )
group by
  columnName 
```
-- 72238529 rows in set. Elapsed: 30.658 sec. Processed 1.33 billion rows, 51.09 GB (43.54 million rows/s., 1.67 GB/s.) 
```
select
  distinct columnName
from
  tableA
where
  columnName global in (
    select
      distinct columnName
    FROM
      tableB
    where
      condition
  ) 
```
-- 72238529 rows in set. Elapsed: 114.806 sec. Processed 1.33 billion rows, 51.09 GB (11.63 million rows/s., 444.99 MB/s.)   

why distinct is so slow in this situation?

**Comment by den-crane** [comment]
Distinct and Groupby use different algorithms.
Distinct produces the first row faster. For example compare the same queries with LIMIT 1.

**Comment by alexey-milovidov** [comment]
Theoretically we can make GROUP BY without aggregate functions to produce records as soon as they are found and to work faster with LIMIT. Also we can make DISTINCT to work as fast as GROUP BY.

Now the difference is just an implementation detail.

**Comment by l1t1** [comment]
if there is no limit and no aggregate functions, can change choose the faster algorithm?

**Comment by alexey-milovidov** [comment]
@l1t1 Yes, faster algorithm is possible and easy to implement.

**Comment by poppinlr** [comment]
is it because distinct is a serial execution and group by is a parallel execution?
if so, can distinct be parallel possible?

**Comment by alexey-milovidov** [comment]
@poppinlr No, both are parallel.
But GROUP BY do it better.

**Comment by Ivlyth** [comment]
so, we should prefer GROUP BY than DISTINCT, right ?

**Comment by orloffv** [comment]
in my tests, distinct faster
