### ISSUE TITLE
`-fuse-ld` is replaced by `--ld-path` in Clang

### ISSUE THREAD

**Issue by hczhcz** [ClickHouse/ClickHouse#17917]
**Operating system**
Linux Mint 19

**Cmake version**
3.16.3

**Ninja version**
1.10.0

**Compiler name and version**
clang 12.0.0

**Full cmake and/or ninja output**
```
clang: warning: '-fuse-ld=' taking a path is deprecated. Use '--ld-path=' instead
```

See also: https://reviews.llvm.org/D83015

**Comment by amosbird** [comment]
https://github.com/ClickHouse/ClickHouse/pull/15481

but it was closed because of no use cases.

**Comment by alexey-milovidov** [comment]
Let's continue. We can test for clang version and use the new option if it is clang 12.
