### ISSUE TITLE
Give the ability to choose float from string parsing algorithms.[Fast/Precise]

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#17933]
In continuation of #1665

It would be useful to be able choose a float parsing algorithm, as some drivers don't support binary formats and that can be done as session setting.

**Use case**
Clickhouse version 20.13.1.5365
```
SELECT
    toFloat64(15008753.),
    toFloat64('1.5008753E7')

Query id: b4376f9b-a74d-4442-9113-5a48ce0e32cf

┌─toFloat64(15008753.)─┬─toFloat64('1.5008753E7')─┐
│             15008753 │       15008753.000000002 │
└──────────────────────┴──────────────────────────┘
```
**Describe alternatives you've considered**
Use Decimal as a data type and later convert it to float64 (via Default for example).

**Comment by alexey-milovidov** [comment]
No one has worked on this issue.

**Comment by UnamedRus** [comment]
```
SELECT toFloat64('1.7091')



┌─toFloat64('1.7091')─┐
│  1.7090999999999998 │
└─────────────────────┘
```

**Comment by UnamedRus** [comment]
@alexey-milovidov 

May be it make sense to reopen this issue?
Because losing fifth position of significant digits looks a bit too much for fast but a **bit** imprecise parsing.

**Comment by aadant** [comment]
This is useful when you replicate data between 2 systems. if the formatting is different, you can not run checksums ...

**Comment by zvonand** [comment]
@UnamedRus how do you think this shall look like? I'm thinking of a setting like `enable_precise_float_parsing` with default value 0

**Comment by UnamedRus** [comment]
Yeah, via setting
