### ISSUE TITLE
arrayMap over neighbor returns unexpected behavior

### ISSUE THREAD

**Issue by TomerRZN** [ClickHouse/ClickHouse#17939]
I'm running this
```
WITH (arrayMap(offset -> offset - 5, range(11))) AS offsets
SELECT
    number,
    arrayMap(offset -> neighbor(number, offset), offsets) AS window
FROM (
    SELECT number
    FROM numbers(100)
    ORDER BY number
)
ORDER BY number LIMIT 10
```
And expecting it to return the following output:
```
┌─number─┬─window──────────────────────┐
│      0 │ [0,0,0,0,0,0,1,2,3,4,5]     │
│      1 │ [0,0,0,0,0,1,2,3,4,5,6]     │
│      2 │ [0,0,0,0,1,2,3,4,5,6,7]     │
│      3 │ [0,0,0,1,2,3,4,5,6,7,8]     │
│      4 │ [0,0,1,2,3,4,5,6,7,8,9]     │
│      5 │ [0,1,2,3,4,5,6,7,8,9,10]    │
│      6 │ [1,2,3,4,5,6,7,8,9,10,11]   │
│      7 │ [2,3,4,5,6,7,8,9,10,11,12]  │
│      8 │ [3,4,5,6,7,8,9,10,11,12,13] │
│      9 │ [4,5,6,7,8,9,10,11,12,13,14]│
└────────┴─────────────────────────────┘
```
This is what it actually returns:
```
┌─number─┬─window─────────────────────┐
│      0 │ [0,0,0,0,0,0,0,0,1,1,1]    │
│      1 │ [0,0,0,1,1,1,1,1,2,2,2]    │
│      2 │ [1,1,1,2,2,2,2,2,3,3,3]    │
│      3 │ [2,2,2,3,3,3,3,3,4,4,4]    │
│      4 │ [3,3,3,4,4,4,4,4,5,5,5]    │
│      5 │ [4,4,4,5,5,5,5,5,6,6,6]    │
│      6 │ [5,5,5,6,6,6,6,6,7,7,7]    │
│      7 │ [6,6,6,7,7,7,7,7,8,8,8]    │
│      8 │ [7,7,7,8,8,8,8,8,9,9,9]    │
│      9 │ [8,8,8,9,9,9,9,9,10,10,10] │
└────────┴────────────────────────────┘
```
Why is this happening and how do I query the expected output?

**Comment by den-crane** [comment]
SELECT rand() ?

```
┌────number─┬─window──────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│   2170931 │ [0,0,0,2170931,2170931,2170931,2170931,2170931,17492443,17492443,17492443]                                      │
│  17492443 │ [2170931,2170931,2170931,17492443,17492443,17492443,17492443,17492443,29662116,29662116,29662116]               │
│  29662116 │ [17492443,17492443,17492443,29662116,29662116,29662116,29662116,29662116,35533993,35533993,35533993]            │
│  35533993 │ [29662116,29662116,29662116,35533993,35533993,35533993,35533993,35533993,133439554,133439554,133439554]         │
```

**Comment by den-crane** [comment]
Probably your task can be solved without neighbor. What is your real task? Calculate what exactly? in sliding window?
groupArrayMovingSum  groupArrayMovingAvg ?

**Comment by TomerRZN** [comment]
I have a table of events, containing the fields `[id, timestamp]`
I'd like to query a specific `id` and get the window of X rows before and Y rows after.

If this it the table:
```
┌───────────────────────────────────id─┬───────────────timestamp─┐
│ 190b52c7-55ee-52ba-b3d2-064247bb9d92 │ 2020-08-24 22:38:17.493 │
│ 37b78554-4fdf-5791-af45-9cf5ac4efe3d │ 2020-08-24 22:38:20.493 │
│ cf9087f1-7786-514c-8af3-0c63535e64af │ 2020-08-24 22:38:23.493 │
│ e102fa52-b721-549c-88a2-d946ee6c3e2b │ 2020-08-24 22:38:26.493 │
│ 528f0572-af11-5867-b9c7-db81ba84ceaa │ 2020-08-24 23:18:24.493 │
│ ca55444f-d61d-547b-847e-05c857cf1ace │ 2020-08-24 23:18:27.493 │
│ 7290160d-413d-5fa6-8df9-081dfa956dd1 │ 2020-08-24 23:18:30.493 │
│ e1913afd-e555-51a5-9321-81950b867dc6 │ 2020-08-24 23:18:33.493 │
└──────────────────────────────────────┴─────────────────────────┘
```
For a query with the following params:
`id = 'e102fa52-b721-549c-88a2-d946ee6c3e2b'`
`before = 1`
`after = 2`

I expect to receive this:
```
┌───────────────────────────────────id─┬───────────────timestamp─┐
│ cf9087f1-7786-514c-8af3-0c63535e64af │ 2020-08-24 22:38:23.493 │
│ e102fa52-b721-549c-88a2-d946ee6c3e2b │ 2020-08-24 22:38:26.493 │
│ 528f0572-af11-5867-b9c7-db81ba84ceaa │ 2020-08-24 23:18:24.493 │
│ ca55444f-d61d-547b-847e-05c857cf1ace │ 2020-08-24 23:18:27.493 │
└──────────────────────────────────────┴─────────────────────────┘

**Comment by TomerRZN** [comment]
> SELECT rand() ?
> 
> ```
> ┌────number─┬─window──────────────────────────────────────────────────────────────────────────────────────────────────────────┐
> │   2170931 │ [0,0,0,2170931,2170931,2170931,2170931,2170931,17492443,17492443,17492443]                                      │
> │  17492443 │ [2170931,2170931,2170931,17492443,17492443,17492443,17492443,17492443,29662116,29662116,29662116]               │
> │  29662116 │ [17492443,17492443,17492443,29662116,29662116,29662116,29662116,29662116,35533993,35533993,35533993]            │
> │  35533993 │ [29662116,29662116,29662116,35533993,35533993,35533993,35533993,35533993,133439554,133439554,133439554]         │
> ```

Accidentally copied the wrong query, fixed it now.

**Comment by alexey-milovidov** [comment]
`neighbor` function is tricky to use - it can obtain neighbour values only within a block.

But the concept of "block" is hidden to user. It also depends on internal details of data processing. And for higher-order functions these details are very specific. The behaviour can be explained but the user cannot rely on it anyway.

Bottom line: `neighbor` function is a hack that cannot be correctly used in your query.
It can be improved (rewritten) later, but this issue will be closed for now.

**Comment by alexey-milovidov** [comment]
@akuzm FYI this is the case for window functions.
