### ISSUE TITLE
Metadata on replica is not up to date with common metadata in Zookeeper

### ISSUE THREAD

**Issue by chenkaiyin1201** [ClickHouse/ClickHouse#17957]
clickhouse version: 20.9.2

the operation of sql: alter table xxx add column xxx String

exception: Code: 517. DB::Exception: Received from 172.0.0.1:9000. DB::Exception: Metadata on replica is not up to date with common metadata in Zookeeper. Cannot alter.

**Comment by alesapin** [comment]
This exception says that the replica has unprocessed alters. If the error doesn't disappear, then provide server logs table schema and query.

**Comment by chenkaiyin1201** [comment]
> This exception says that the replica has unprocessed alters. If the error doesn't disappear, then provide server logs table schema and query.

The problem has been dealt with. There should be an abnormal outage state that causes inconsistency between the version of ZK node metadata and the metadata_version node data, resulting in an error when the table structure changes.

Thanks.
