### ISSUE TITLE
just for ref. other databases new features

### ISSUE THREAD

**Issue by l1t1** [ClickHouse/ClickHouse#17953]
https://docs.oracle.com/en/database/oracle/oracle-database/21/nfcon/

**Comment by l1t1** [comment]
this fun has been realized. 

https://docs.oracle.com/en/database/oracle/oracle-database/21/nfcon/bitwise-aggregate-functions-274057636.html

**Comment by l1t1** [comment]
window functions
https://docs.oracle.com/en/database/oracle/oracle-database/21/nfcon/practice-using-enhanced-analytic-functions-282450990.html

**Comment by alexey-milovidov** [comment]
We have implemented these features.
