### ISSUE TITLE
Settings constraints - readonly all, but allow changing some of

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#17959]
Now you need to list all settings which should be readonly.

We want to limit all, but allow changing some of them.

**Comment by alexey-milovidov** [comment]
I also need this feature :)

**Comment by fastio** [comment]
> Now you need to list all settings which should be readonly.
> 
> We want to limit all, but allow changing some of them.

What do you mean is that updating system.settings table by `alter table update ` ?

**Comment by filimonov** [comment]
> > Now you need to list all settings which should be readonly.
> > We want to limit all, but allow changing some of them.
> 
> What do you mean is that updating system.settings table by `alter table update ` ?

https://clickhouse.tech/docs/en/sql-reference/statements/set/

**Comment by mshustov** [comment]
@alexey-milovidov, we need it to leverage `additional_table_filters` setting for `readonly` users in ad-hoc filters created by Grafana integration. It's a critical problem, considering it's a common practice to give `readonly` access to the visualization tools users. see https://github.com/grafana/clickhouse-datasource#clickhouse-user-for-the-data-source

**Comment by alexey-milovidov** [comment]
@mshustov This feature is scheduled for implementation here: https://github.com/ClickHouse/ClickHouse/issues/40244
