### ISSUE TITLE
mutate was blocked

### ISSUE THREAD

**Issue by allen12921** [ClickHouse/ClickHouse#17962]
Recently we're trying out the latest Clickhouse V20.12.3.3 and encountered below issue while our server is under low load on cpu,memory and disk io.
I got many logs like below and seems clickhouse is not doing any mutations
Any suggestion?

2020.12.10 13:16:22.301510 [ 10777 ] {} <Debug> default.test (269d6d77-a345-47de-9429-72d6a76aeb02): Current max source part size for mutation is 0 but part size 41269. Will not mutate part 47_741280_741280_0. Max size depends not only on available space, but also on settings 'number_of_free_entries_in_pool_to_execute_mutation' and 'background_pool_size'

**Comment by den-crane** [comment]
And free space? `df -h /var/lib` ?

**Comment by allen12921** [comment]
Thanks for reply
There is still more than 70% free space there and also there is low cpu io wait
/dev/nvme1n1    825G  211G  573G   27%  /var/lib/clickhouse
There is enough free space here. it seems like mutate process was blocked by merge process
We're doing batch update 4 seconds a time and we already changed the background_pool_size to 128
Is there any other way to speed up the merge speed or how to find out the bottleneck?

**Comment by allen12921** [comment]
Probably yes, we are doing  each insert&update per 4 seconds
Neither insert nor update number is fixed
 It's working  fine  with  Clickhouse  server V19.13.3.26

**Comment by chenk818** [comment]
how many datas will be insert&updat per 4 seconds?
if not so many,you can do it within one insert/update or else use dictionary table

**Comment by allen12921** [comment]
> how many datas will be insert&updat per 4 seconds?
Depends on the data generating speed some times less than 1k some times more than 10k
> if not so many,you can do it within one insert/update or else use dictionary table
We are not able to wait until have enough data and dictionary table is not suitable for us

Is there any parameters I can change to make the latest version clickhouse merge speed catch up with V19.13.3.26 by tuning parameters while our hardware load is still low?

**Comment by chenk818** [comment]
with V20.6，following parameters were related
max_bytes_to_merge_at_min_space_in_pool,default value is bigger enough( 150GB)
background_processing_pool_thread_sleep_seconds default value is 10s

I can't find these  with V19.x

**Comment by allen12921** [comment]
@chenk818 background_processing_pool_thread_sleep_seconds couldn't help on single merge task duration too as per documents,it's free thread sleep time

@den-crane any suggestion to find out the bottleneck pls?

**Comment by filimonov** [comment]
May be you create too many parts? And your background pool is overloaded with merges leaving no space for mutations? Check how your system.merges table look like when you see that mutation exception

**Comment by allen12921** [comment]
I have already fix the mutation exception by enlarge the background_pool_size 
Now the problem is Current Clickhouse V20.12.3.3 merge speed  is quit more slower than Clickhouse V19.13.3.26

**Comment by allen12921** [comment]
close as no one can help
