### ISSUE TITLE
compile clickhouse ok, but execute got link error

### ISSUE THREAD

**Issue by miaojianxin** [ClickHouse/ClickHouse#17995]
I compile clickhouse on arm (aarch64) OK, but when I execute the clickhouse got link error:

 ./programs/clickhouse --help
./programs/clickhouse: /lib/aarch64-linux-gnu/libpthread.so.0: version `GLIBC_2.30' not found (required by ./programs/clickhouse)

the configure  I write like this:
  cmake ../ -DUSE_UNWIND=1 -DUSE_DEBUG_HELPERS=1 -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=None -DCMAKE_INSTALL_SYSCONFDIR=/etc -DCMAKE_INSTALL_LOCALSTATEDIR=/var -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DENABLE_EMBEDDED_COMPILER=0 -DENABLE_TESTS=0 -DCMAKE_EXE_LINKER_FLAGS="-s -Wl,--dynamic-linker,$ld" 

$ld  is /lib/ld-linux-aarch64.so.1

the gcc is gcc version 9.3.0
ninja  --version
1.9.0.git

**Comment by hexiaoting** [comment]
upgrade gcc to 10+

**Comment by hexiaoting** [comment]
upgrade your glibc

**Comment by xiajingliang** [comment]
你是怎么在 arm (aarch64) 上编译 clickhouse？ 能发一下参考的资料吗？

**Comment by miaojianxin** [comment]
我们公司目前提供编译clickhouse各种平台的服务，可与公司商务人士联系


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ClickHouse/ClickHouse"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月4日(星期五) 下午2:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ClickHouse/ClickHouse] compile clickhouse ok, but execute got link error (#17995)





 
你是怎么在 arm (aarch64) 上编译 clickhouse？ 能发一下参考的资料吗？

**Comment by alexey-milovidov** [comment]
Guaranteed solution is to download the official pre-built binary:
https://clickhouse.tech/docs/en/getting-started/install/#from-binaries-non-linux

About the message `GLIBC_2.30`. It means that the binary has referenced symbols from version 2.30 of the glibc during compile and linking stage and that version of glibc is not available on the target system.

To avoid this issue you can compile on the same version of OS that are installed on the target system.
