### ISSUE TITLE
now()    timezone is client timezone not server timezone?

### ISSUE THREAD

**Issue by jjtjiang** [ClickHouse/ClickHouse#17999]
sql ：select now(),toString(now())
result:
|now()|toString(now())|
|-----|---------------|
|2020-12-11 06:37:09|2020-12-10 22:37:09|

**Comment by den-crane** [comment]
Yes. What API do you use? JDBC ?

clickhouse-client --use_client_time_zone=1

**Comment by filimonov** [comment]
`now()` for native clients the number is send to a client and client do formatting to string.

`toString(now())` server do a formatting and send string.

**Comment by jjtjiang** [comment]
got it, I use JDBC .thanks @den-crane @filimonov
