### ISSUE TITLE
Data lost after reboot one machine in 3shards_2replicas environment

### ISSUE THREAD

**Issue by taylor131415** [ClickHouse/ClickHouse#18003]
clickhouse-version:20.11.3.3

1. Setting up 3shards_2replicas environment like this:
![2020121](https://user-images.githubusercontent.com/74707266/102035312-139bdf00-3dfb-11eb-9606-872225b24425.jpg)

2. Keep insert data via kafka
3. Reboot one machine in cluster during kafka insert data.
4. Check the amount of total insert data，it's less than the amount of data when no reboot action during kafka insert data.

I want to ask if I should change some configuration or some action in case data lost after rebooting machine? Looking for some answer, thanks

**Comment by filimonov** [comment]
Please share log fragments. Nodes don't go readonly when you shutdown another node. Do you also run zookeeper on the same nodes?

**Comment by taylor131415** [comment]
> Please share log fragments. Nodes don't go readonly when you shutdown another node. Do you also run zookeeper on the same nodes?

At first, zookeeper and clickhouse running on the same node. After I found this issue, I change to run all zookeeper on a separate node.(Without any clickhouse process on this node), but this issue still can be reproduced. Check for the log again, error log as below:
2020.12.16 09:20:33.482264 [ 12562 ] {} <Warning> ConnectionPoolWithFailover: Connection failed at try №1, reason: Code: 209, e.displayText()= DB::NetException: Timeout: connect timed out: 192.168.1.184:9000 (server02:9000) (version 20.11.3.3 (official build))
2020.12.16 09:20:58.449479 [ 12571 ] {} <Warning> test.motorvehicle_rep (ReplicatedMergeTreeCleanupThread): Will mark replica cluster01-01-2 as lost, because it has stale log pointer: log-0000007534
2020.12.16 09:21:33.549497 [ 12562 ] {} <Warning> ConnectionPoolWithFailover: Connection failed at try №1, reason: Code: 209, e.displayText()= DB::NetException: Timeout: connect timed out: 192.168.1.184:9000 (server02:9000) (version 20.11.3.3 (official build))
2020.12.16 09:22:33.821867 [ 12562 ] {} <Warning> ConnectionPoolWithFailover: Connection failed at try №1, reason: Code: 210, e.displayText()= DB::NetException: Connection refused (server02:9000) (version 20.11.3.3 (official build))
2020.12.16 09:28:03.682034 [ 12628 ] {e208e522-d468-4e70-bc27-ddc44af7edea} <Warning> ConnectionPoolWithFailover: Connection failed at try №1 reason: Code: 32, e.displayText() = DB::Exception: Attempt to read after eof (version 20.11.3.3 (official build))

As log shows,I reboot node2(server02) at 2020.12.16 09:20:33, and after node2 reboot, no more error log produced. Seems like all replicas work correctly, I don't know where's wrong lead to the total amount of data is less. Looking forward to your help,thanks.
