### ISSUE TITLE
Materialized Views Regression Upgrading from 19.9.2.4 to 20.3.18.10

### ISSUE THREAD

**Issue by abraithwaite** [ClickHouse/ClickHouse#18015]
Hey friends!  We just noticed a regression in stacked materialized views upgrading from 19.9.2.4 to 20.3.18.10.

https://gist.githubusercontent.com/abraithwaite/1e0aa2f22991421a584977c17d1f9cfa/raw/8893b9bb9b9fc12ed4237acb41f2f639a3d9e094/reproduction.sql

The proceeding queries when run on 19.9.2.4 successfully populate the top (hourly) materialized view, whereas on 20.3.18.10, they do not populate the hourly view with data, despite the minutely view being populated correctly.

I couldn't find any other issues or release notes about this issue, hence I'm opening this.  Any ideas about what's going on?

Notably: no errors are thrown during the hourly MV creation.  In our case, since we had existing tables already, the dependent view just stopped getting data altogether after the upgrade, with no logs indicating there is/was an issue.

Edit: while testing with the current official images on dockerhub, it appears that this commit made it into the 19.9.2.4 tag somehow:

https://github.com/ClickHouse/ClickHouse/commit/9319863a5943ed0af204ad98a01a887a4c3cab2b

That commit does not exist in the build of 19.9.2.4 that we built over a year ago.

The result of that commit is that inserts are not possible into a raw table with a dependant MV that has a materialized column, which is a separate issue.

**Comment by den-crane** [comment]
Now you should use .inner.MV name in cascades. 

https://den-crane.github.io/Everything_you_should_know_about_materialized_views_commented.pdf   page18

https://youtu.be/ckChUkC3Pns?list=PLO3lfQbpDVI-hyw4MyqxEk3rDHw95SzxJ&t=10890

**Comment by den-crane** [comment]
FROM r0.**`.inner.minutely_test_events`**

```sql

CREATE MATERIALIZED VIEW r0.hourly_test_events
(
    `hour` DateTime,
    `name` String,
    `sumState` AggregateFunction(sum, UInt64)
)
ENGINE = AggregatingMergeTree()
PARTITION BY toStartOfDay(hour)
PRIMARY KEY (hour, name)
ORDER BY (hour, name) AS
SELECT
    toStartOfHour(minute) AS hour,
    name,
    sumState(toUInt64(1)) AS sumState
FROM r0.`.inner.minutely_test_events`
GROUP BY (hour, name);
```
