### ISSUE TITLE
Performance of inserts with large nubmer of materialized columns

### ISSUE THREAD

**Issue by dpzmick** [ClickHouse/ClickHouse#18011]
Hi,

I'm looking to improve the performance of an insert into a table which has a large number of materialized columns.

First off, I'm running this version of the clickhouse container (happy to update):
```
$ podman images | grep clickhouse
docker.io/yandex/clickhouse-server                latest                                c85f84ea6550   6 weeks ago    519 MB
```

using the command from the docs:
```
$ podman run --ulimit nofile=262144:262144 -p 8123:8123 -p 9000:9000 --ulimit nofile=262144:262144 --volume=/my/data/dir:/var/lib/clickhouse yandex/clickhouse-server
```

In short, I'm creating a table which contains a `keys` array, a `values` array, and many materialized columns which extract kv pairs from the arrays. Some `keys`/`values` sets might be missing some of the keys, so the materialized column query needs to be able to handle these missing values.

For example, a create might look like:
```
CREATE TABLE test.slow(
     keys     Array(String)  CODEC(ZSTD),
     values   Array(String)  CODEC(ZSTD),
     metric0  UInt64  MATERIALIZED toUInt64OrZero(arrayFirst((v,k) -> (k=='metric0'), values, keys)) CODEC(DoubleDelta, ZSTD),
     metric1  UInt64  MATERIALIZED toUInt64OrZero(arrayFirst((v,k) -> (k=='metric1'), values, keys)) CODEC(DoubleDelta, ZSTD),
    --- many more of these
)
ENGINE = MergeTree ORDER BY tuple();                                                                                                                                                           
```

With a large number of materialized columns, the insert performance suffers dramatically.

I have a full test script here: https://gist.github.com/dpzmick/7658c0b0e934e87853025f9fc3227ce3

and this is an example of the performance numbers I am getting:

```
$ python3 sad_perf.py
setup 41.25656270980835s        
fast: 0.07529330253601074s      
slow: 38.57396221160889s        
```

Is there anything I can do to speed this up and/or can anyone explain why exactly this is so slow?

**Comment by dpzmick** [comment]
wow! I updated my clickhouse image:

```
$ podman images | grep clickhouse
docker.io/yandex/clickhouse-server                latest                                8dc37897ab10   2 days ago     818 MB
```

and the performance is now _much much_ better:

```
setup 2.219663143157959s   
fast: 0.06687545776367188s 
slow: 2.0548548698425293s  
```

I'm guessing this is related to #12408 ?

**Comment by filimonov** [comment]
I guess that's the reason. You can check it by enabling/disabling compact parts for a table.

**Comment by dpzmick** [comment]
Indeed, this does seem to be the cause. I don't quite have an intuition for why compact vs wide would make such a large difference, some extremely naive "open lots of files" tests on this host don't show me numbers that seem to agree with the performance difference, but I'm satisfied now with these numbers so there's nothing left to do here. Thanks!

**Comment by chenzhiping007** [comment]
> enabling/disabling compact parts for a table

what is "enabling/disabling compact parts for a table" ,which setting  variables related to
