### ISSUE TITLE
Build clickhouse from docker failed: ubuntu repository doest not have a release file 

### ISSUE THREAD

**Issue by taiyang-li** [ClickHouse/ClickHouse#18024]
My clickhouse version is v20.12.3.3-stable 
When I build clickhosue from docker, run: 
```
cd docker/builder
sudo make image
```
The error came out when executing `apt-get update` like this:
![image](https://user-images.githubusercontent.com/8181003/101970720-15349e00-3c67-11eb-8d60-18cacedc04ae.png)

Then I found the similar [issue](https://askubuntu.com/questions/91815/how-to-install-software-or-upgrade-from-an-old-unsupported-release), which says that the repositories for older releases(ubuntu19) that are not supported fetching from default apt source list(archive.ubuntu.com or security.ubuntu.com). 

When I update dockerfile, `sudo make image` is running ok.  
```
-FROM ubuntu:19.10
+FROM ubuntu:latest
```

**Comment by filimonov** [comment]
See https://github.com/ClickHouse/ClickHouse/tree/master/docker/package

docker/builder was used by some developers, but not used in CI and seems a bit outdated (fill free to send PR with adjustments)

**Comment by alexey-milovidov** [comment]
@filimonov Just replace eoan to focal?

**Comment by taiyang-li** [comment]
I see... I have given up building clickhouse with docker now.
