### ISSUE TITLE
version 20.12.3.3 question

### ISSUE THREAD

**Issue by 16601746291** [ClickHouse/ClickHouse#18026]
when i install ，today ，clickhouse version is： 20.12.3.3   ，finish install has two :/usr/bin/clickhouse /usr/bin/clickhouse.old  
and /etc/clickhouse-server owner is clickhouse,  the config.xml is resd only  ,the pre version 20.10.3.30  owner is root ，  Is it normal？

**Comment by alexey-milovidov** [comment]
This is normal.

1. `clickhouse.old` file is a backup of previous version. It allows to quickly switch to previous version if needed. This file can be safely removed to save space.

2. Minor changes in file ownership and access are insignificant. If you found something not convenient or worse please tell.
