### ISSUE TITLE
Memory Limit Error

### ISSUE THREAD

**Issue by adinindu** [ClickHouse/ClickHouse#18029]
Hello,

We have Clickhouse 20.10.3.30-2 on 3 node cluster. Each server has 16G Ram + 16G Swap. We have php cronjob running at every 10min performing a SELECT INSERT into a specific table. We see following error randomly about 70% of the time. 

DB::Exception: Memory limit (total) exceeded: would use 13.56 GiB (attempt to allocate chunk of 4195893 bytes), maximum: 13.55 GiB

We have following setting in the server. 
<max_memory_usage>14500000000</max_memory_usage>
<max_server_memory_usage_to_ram_ratio>1.5</max_server_memory_usage_to_ram_ratio>

**Comment by den-crane** [comment]
Check clickhouse log, that your settings was applied.

For example
```<Information> Application: Setting max_server_memory_usage was set to 56.53 GiB (62.81 GiB available * 0.90 max_server_memory_usage_to_ram_ratio)
```

**Comment by filimonov** [comment]
Swap is usually a bad idea. Prefer other ways of limitingvram usage - max_bytes_before_external_..., limiting number of threads etc.

**Comment by den-crane** [comment]
no reply
