### ISSUE TITLE
What is the difference between attach/detach and move partition

### ISSUE THREAD

**Issue by RangerWolf** [ClickHouse/ClickHouse#18085]
Hi Team,
My requirement is move partition from one table and another table. 
Both `ATTACH PARTITION FROM` and `MOVE PARTITION TO TABLE` could meet my requirement, but what is the difference and which one has better performance?

Thanks!
Wenjun

**Comment by tavplubix** [comment]
These queries are almost identical, except the following details:
 - `MOVE PARTITION TO TABLE` deletes partition from the source table, `ATTACH PARTITION FROM` doesn't.
 - It's not possible to `MOVE` partitions between replicated and not-replicated tables, `ATTACH` should work fine with `MergeTree` and `ReplicatedMergeTree`.

There is also `REPLACE PARTITION` query, it's similar to `ATTACH PARTITION FROM`, but it deletes partition from the destination table before  attaching.

**Comment by RangerWolf** [comment]
> These queries are almost identical, except the following details:
> 
> * `MOVE PARTITION TO TABLE` deletes partition from the source table, `ATTACH PARTITION FROM` doesn't.
> * It's not possible to `MOVE` partitions between replicated and not-replicated tables, `ATTACH` should work fine with `MergeTree` and `ReplicatedMergeTree`.
> 
> There is also `REPLACE PARTITION` query, it's similar to `ATTACH PARTITION FROM`, but it deletes partition from the destination table before attaching.

Thanks, but which one has better performance?  @tavplubix

**Comment by tavplubix** [comment]
All of them are almost identical, so performance is the same

**Comment by RangerWolf** [comment]
> All of them are almost identical, so performance is the same

Thanks!

**Comment by ivan-tkatchev** [comment]
> All of them are almost identical, so performance is the same

Not at all true.
MOVE has some replication queue magic under the hood. MOV'ing a partition with lots of parts dumped tens of thousands of entries into replication_queue, after which the replication queue stopped processing and data was eventually lost. (Seems like the replication magic has lots of race conditions and bugs.)

ATTACH FROM just copied parts into the table. Not sure if the parts will be replicated eventually or not.

(Both tables are replicated in this case.)
