### ISSUE TITLE
Queries using MaterializeMySQL engine are too slow.

### ISSUE THREAD

**Issue by DBA-Ray** [ClickHouse/ClickHouse#18083]
**Describe the bug**
SELECT count(*)
FROM task_score_log

Query id: 3ba2df0b-f359-48b6-9ee6-39de6c36e03a

┌──count()─┐
│ 66194289 │
└──────────┘

1 rows in set. Elapsed: 4.988 sec. Processed 66.19 million rows, 2.12 GB (13.27 million rows/s., 424.66 MB/s.)

**I use the  MaterializeMySQL to sync data from mysql.But it takes more than 4 seconds to count more than 60 million rows of data！**

version 20.12.3.3 (official build)

**Comment by tavplubix** [comment]
Probably it's because `SELECT count(*) FROM task_score_log` is implicitly converted to `SELECT count(*) FROM task_score_log FINAL where _sign=1`. However, 4 seconds is too much even for SELECT FINAL. Could you please provide output of the following:
```
$ cat /var/lib/clickhouse/db_name/task_score_log.sql
```
and
```
:) select partition, name, rows, bytes from system.parts where table='task_score_log' and active=1
```

**Comment by DBA-Ray** [comment]
Sorry,the tablename is sq_task_score_log.

ATTACH TABLE sq_task_score_log
(
    `id` UInt64,
    `user_id` Nullable(Int32),
    `number` Nullable(Int32),
    `task_id` Nullable(Int32),
    `title` Nullable(String),
    `created_at` Nullable(DateTime),
    `updated_at` Nullable(DateTime),
    `deleted_at` Nullable(DateTime),
    `_sign` Int8 MATERIALIZED 1,
    `_version` UInt64 MATERIALIZED 1
)
ENGINE = ReplacingMergeTree(_version)
PARTITION BY intDiv(id, 18446744073709551)
ORDER BY (assumeNotNull(user_id), assumeNotNull(created_at), id)
SETTINGS index_granularity = 8192

and

SELECT
    partition,
    name,
    rows,
    bytes
FROM system.parts
WHERE (table = 'sq_task_score_log') AND (active = 1)

Query id: ce9e0297-ca91-455e-858f-302bd35471e7

Ok.

0 rows in set. Elapsed: 0.009 sec.
