### ISSUE TITLE
sumMap return empty when value equal 0

### ISSUE THREAD

**Issue by peaksnail** [ClickHouse/ClickHouse#18092]
hi

I execute the sql 
```
select sumMap(code,value) from (
  select [100] as code,[10] as value
  union all
  select [100] as code,[-10] as value
)
```
I get the result ([],[]), but I expect to get the result ([100],[0])

how can I get the result ([100],[0])? 

thanks

**Comment by den-crane** [comment]
This is a special behavior for SummingMT.

As WA you can use

```
select sumMap(code,cast(value as Array(Nullable(Int64)))) from (
  select [100] as code,[10] as value
  union all
  select [100] as code,[-10] as value
)

┌─sumMap(code, cast(value, 'Array(Nullable(Int64))'))─┐
│ ([100],[0])                                         │
└─────────────────────────────────────────────────────┘
```

@alexey-milovidov I think we can introduce another function i.e. sumMapWithZeros 
And behavior with Nullable seems accident / incosistent ?
