### ISSUE TITLE
use 20.12.3.3 clickhouse  ，What is the start command？

### ISSUE THREAD

**Issue by knight11111** [ClickHouse/ClickHouse#18096]
rpm  -ivh *.rpm
![image](https://user-images.githubusercontent.com/53258977/102217735-ff99cf80-3f17-11eb-8c7d-e1d4cadcf734.png)
use  sudo service clickhouse-server start      then  Init script is already running
and use  /etc/init.d/clickhouse-service    then -bash: /etc/init.d/clickhouse-service: No such file or directory
and use  sudo systemctl start clickhouse-server  then  No error is reported, but it cannot be started successfully，No effect！
use  nohub clickhouse-server --config-file=/etc/clickhouse-server/config.xml >> log.out 2>&1 &   ,it can be started successfully,but  It can not be closed correctly, only through kill

**Comment by den-crane** [comment]
`sudo journalctl -u clickhouse-server `

`sudo cat /var/log/clickhouse-server/stderr.log`

` sudo systemctl status clickhouse-server`

**Comment by knight11111** [comment]
Hello，This is the result of the order。I didn't see anything unusual， I've turned it on.but use sudo systemctl status clickhouse-server  ， I see failure。
![image](https://user-images.githubusercontent.com/53258977/102321318-7a1a2c00-3fb8-11eb-843a-7d75551db8b3.png)
[clickhouse-server.err.log](https://github.com/ClickHouse/ClickHouse/files/5701189/clickhouse-server.err.log)

[sudo journalctl -u clickhouse-server.txt](https://github.com/ClickHouse/ClickHouse/files/5701197/sudo.journalctl.-u.clickhouse-server.txt)

**Comment by den-crane** [comment]
I was asking for `stderr.log` not for `clickhouse-server.err.log`

But it seems the problem is in privileges

```
Dec 15 20:25:43 KF1-ClickHouse-187 clickhouse-server[9555]: Processing configuration file '/etc/clickhouse-server/config.xml'.
Dec 15 20:25:43 KF1-ClickHouse-187 clickhouse-server[9555]: std::exception. Code: 1001, type: std::__1::__fs::filesystem::filesystem_error, e.what() = filesystem error: in posix_stat: failed to determine attributes for the specified 
```

Try `chown -R clickhouse.clickhouse /etc/clickhouse-server/`

And test with sudo and clickhouse user `sudo -u clickhouse clickhouse-server --config-file=/etc/clickhouse-server/config.xml `

**Comment by den-crane** [comment]
no reply
