### ISSUE TITLE
Batch data insert error. Server Crashed. Connection reset by peer

### ISSUE THREAD

**Issue by Aureliano-Berlindia** [ClickHouse/ClickHouse#18093]
**Describe the issue**

the clickhouse-server crashed when inserting a .tsv data

**How to reproduce**
* ClickHouse client version 20.8.3.18.
* Sample data for all these tables, use [example](https://clickhouse.tech/docs/en/getting-started/tutorial/) if necessary
* Queries:clickhouse-client --query "INSERT INTO default.hits_v1 FORMAT TSV" --max_insert_block_size=100000 < hits_v1.tsv

**Error message and/or stacktrace**
`Code: 210. DB::NetException: Connection reset by peer, while writing to socket ([::1]:9000)`

**Comment by filimonov** [comment]
Please check logs in /var/log/clickhouse-server/

**Comment by Aureliano-Berlindia** [comment]
Hi, Here is the latest clickhouse-server.log:
not sure what's the problem


2020.12.15 21:32:48.232592 [ 6420 ] {} <Trace> TCPHandlerFactory: TCP Request. Address: [::1]:40420
2020.12.15 21:32:48.232669 [ 6420 ] {} <Debug> TCPHandler: Connected ClickHouse client version 20.8.0, revision: 54438, user: default.
2020.12.15 21:32:48.243404 [ 6420 ] {41bfdab5-7116-4cc3-8099-4891513602fc} <Debug> executeQuery: (from [::1]:40420) INSERT INTO tutorial.hits_v1 FORMAT TSV
2020.12.15 21:32:48.243557 [ 6420 ] {41bfdab5-7116-4cc3-8099-4891513602fc} <Trace> ContextAccess (default): Access granted: INSERT(WatchID, JavaEnable, Title, GoodEvent, EventTime, EventDate, CounterID, ClientIP, ClientIP6, RegionID, UserID, CounterClass, OS, UserAgent, URL, Referer, URLDomain, RefererDomain, Refresh, IsRobot, RefererCategories, URLCategories, URLRegions, RefererRegions, ResolutionWidth, ResolutionHeight, ResolutionDepth, FlashMajor, FlashMinor, FlashMinor2, NetMajor, NetMinor, UserAgentMajor, UserAgentMinor, CookieEnable, JavascriptEnable, IsMobile, MobilePhone, MobilePhoneModel, Params, IPNetworkID, TraficSourceID, SearchEngineID, SearchPhrase, AdvEngineID, IsArtifical, WindowClientWidth, WindowClientHeight, ClientTimeZone, ClientEventTime, SilverlightVersion1, SilverlightVersion2, SilverlightVersion3, SilverlightVersion4, PageCharset, CodeVersion, IsLink, IsDownload, IsNotBounce, FUniqID, HID, IsOldCounter, IsEvent, IsParameter, DontCountHits, WithHash, HitColor, UTCEventTime, Age, Sex, Income, Interests, Robotness, GeneralInterests, RemoteIP, RemoteIP6, WindowName, OpenerName, HistoryLength, BrowserLanguage, BrowserCountry, SocialNetwork, SocialAction, HTTPError, SendTiming, DNSTiming, ConnectTiming, ResponseStartTiming, ResponseEndTiming, FetchTiming, RedirectTiming, DOMInteractiveTiming, DOMContentLoadedTiming, DOMCompleteTiming, LoadEventStartTiming, LoadEventEndTiming, NSToDOMContentLoadedTiming, FirstPaintTiming, RedirectCount, SocialSourceNetworkID, SocialSourcePage, ParamPrice, ParamOrderID, ParamCurrency, ParamCurrencyID, GoalsReached, OpenstatServiceName, OpenstatCampaignID, OpenstatAdID, OpenstatSourceID, UTMSource, UTMMedium, UTMCampaign, UTMContent, UTMTerm, FromTag, HasGCLID, RefererHash, URLHash, CLID, YCLID, ShareService, ShareURL, ShareTitle, `ParsedParams.Key1`, `ParsedParams.Key2`, `ParsedParams.Key3`, `ParsedParams.Key4`, `ParsedParams.Key5`, `ParsedParams.ValueDouble`, IslandID, RequestNum, RequestTry) ON tutorial.hits_v1
2020.12.15 21:32:48.284357 [ 6400 ] {} <Trace> SystemLog (system.metric_log): Flushing system log, 8 entries to flush
2020.12.15 21:32:48.286027 [ 6400 ] {} <Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 21.05 GiB.
2020.12.15 21:32:48.287492 [ 6400 ] {} <Trace> system.metric_log (a6f95d56-e8c9-472a-84f6-3502e2b035f7): Renaming temporary part tmp_insert_202012_22_22_0 to 202012_164708_164708_0.
2020.12.15 21:32:48.287856 [ 6400 ] {} <Trace> SystemLog (system.metric_log): Flushed system log
2020.12.15 21:32:48.288001 [ 6395 ] {} <Trace> system.metric_log (a6f95d56-e8c9-472a-84f6-3502e2b035f7): Found 1 old parts to remove.
2020.12.15 21:32:48.288010 [ 6395 ] {} <Debug> system.metric_log (a6f95d56-e8c9-472a-84f6-3502e2b035f7): Removing part from filesystem 202012_164648_164648_0
2020.12.15 21:32:48.398447 [ 6412 ] {} <Debug> DNSResolver: Updating DNS cache
2020.12.15 21:32:48.398640 [ 6412 ] {} <Debug> DNSResolver: Updated DNS cache
2020.12.15 21:32:51.582300 [ 6420 ] {41bfdab5-7116-4cc3-8099-4891513602fc} <Debug> DiskLocal: Reserving 273.84 MiB on disk `default`, having unreserved 21.06 GiB.
2020.12.15 21:32:53.254870 [ 6420 ] {41bfdab5-7116-4cc3-8099-4891513602fc} <Trace> tutorial.hits_v1: Renaming temporary part tmp_insert_all_1_1_0 to all_4_4_0.
2020.12.15 21:32:55.766322 [ 6420 ] {41bfdab5-7116-4cc3-8099-4891513602fc} <Debug> DiskLocal: Reserving 350.87 MiB on disk `default`, having unreserved 21.02 GiB.
2020.12.15 21:32:55.841432 [ 6385 ] {} <Trace> SystemLog (system.query_log): Flushing system log, 1 entries to flush
2020.12.15 21:32:55.841446 [ 6400 ] {} <Trace> SystemLog (system.metric_log): Flushing system log, 7 entries to flush
2020.12.15 21:32:55.841454 [ 6397 ] {} <Trace> SystemLog (system.trace_log): Flushing system log, 97 entries to flush
2020.12.15 21:32:58.164074 [ 6397 ] {} <Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 20.68 GiB.
2020.12.15 21:32:58.164719 [ 6400 ] {} <Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 20.68 GiB.
