### ISSUE TITLE
Merge is slow

### ISSUE THREAD

**Issue by allen12921** [ClickHouse/ClickHouse#18100]
We are using clickhouse 20.12.3.3 and find the merge process is quite slow than 19.13.3.26
Below is one merge process on 20.12.3.3 which takes more than 404s while the server load is low
Any advises to find out the bottleneck？

SELECT *
FROM system.merges
WHERE result_part_name = '34_726877_731764_11_731813'

Query id: 9eb901e7-7b1c-4004-af59-c9186597be37

Row 1:
──────
database:                    default
table:                       entries
elapsed:                     404.311410382
progress:                    0.9873838281494867
num_parts:                   4
source_part_names:           ['34_726877_729203_10_731813','34_729229_730723_9_731813','34_730751_731033_3_731813','34_731052_731764_3_731813']
result_part_name:            34_726877_731764_11_731813
source_part_paths:           ['/var/lib/clickhouse/store/faa/faa22fd9-637e-415f-a610-0630491c6adb/34_726877_729203_10_731813/','/var/lib/clickhouse/store/faa/faa22fd9-637e-415f-a610-0630491c6adb/34_729229_730723_9_731813/','/var/lib/clickhouse/store/faa/faa22fd9-637e-415f-a610-0630491c6adb/34_730751_731033_3_731813/','/var/lib/clickhouse/store/faa/faa22fd9-637e-415f-a610-0630491c6adb/34_731052_731764_3_731813/']
result_part_path:            /var/lib/clickhouse/store/faa/faa22fd9-637e-415f-a610-0630491c6adb/34_726877_731764_11_731813/
partition_id:                34
is_mutation:                 0
total_size_bytes_compressed: 14367771
total_size_marks:            40
bytes_read_uncompressed:     363394887
rows_read:                   123743
bytes_written_uncompressed:  363394791
rows_written:                123743
columns_written:             288
memory_usage:                7582553
thread_id:                   27926
merge_type:                  REGULAR
merge_algorithm:             Vertical

**Comment by den-crane** [comment]
How I can reproduce it?

**Comment by den-crane** [comment]
Please provide create table at least.

**Comment by allen12921** [comment]
I found there are multiple mutations are running at the same time. maybe that's the reason why normal merge slow？.. is there anyway can limit only one mutation runs at a time

**Comment by den-crane** [comment]
merge_tree setting 

number_of_free_entries_in_pool_to_execute_mutation         │ 10    When there is less than specified number of free entries in pool, do not execute part mutations. This is to leave free threads for regular merges and avoid "Too many parts"

**Comment by allen12921** [comment]
Hi Den,
Below is my create table sql and my CPU mode is 'Intel(R) Xeon(R) Platinum 8175M'
`CREATE TABLE entries(
    user_id FixedString(24),
    serial_number UInt64,
    x_field1 FixedString(24),
    x_field2 String,
    partition_id UInt8,
    flag UInt8,
    x_field3 String,
    x_field4 String,
    x_field5 String,
    x_field6 String,
    x_field7 String,
    x_field8 String,
    x_field9 String,
    x_field10 String,
    x_field11 String,
    x_field12 String,
    x_field13 String,
    x_field14 String,
    x_field15 String,
    x_field16 String,
    x_field17 String,
    x_field18 String,
    x_field19 String,
    x_field20 String,
    x_field21 String,
    x_field22 String,
    x_field23 String,
    x_field24 String,
    x_field25 String,
    x_field26 Float32,
    x_field27 String,
    x_field28 String,
    x_field29 String,
    x_field30 Array(String),
    x_field31 String,
    created_at DATETIME,
    updated_at DATETIME,
    deleted_at Nullable(DATETIME),
    field_1 String,
    field_2 String,
    field_3 String,
    field_4 String,
    field_5 String,
    field_6 String,
    field_7 String,
    field_8 String,
    field_9 String,
    field_10 String,
    field_11 String,
    field_12 String,
    field_13 String,
    field_14 String,
    field_15 String,
    field_16 String,
    field_17 String,
    field_18 String,
    field_19 String,
    field_20 String,
    field_21 String,
    field_22 String,
    field_23 String,
    field_24 String,
    field_25 String,
    field_26 String,
    field_27 String,
    field_28 String,
    field_29 String,
    field_30 String,
    field_31 String,
    field_32 String,
    field_33 String,
    field_34 String,
    field_35 String,
    field_36 String,
    field_37 String,
    field_38 String,
    field_39 String,
    field_40 String,
    field_41 String,
    field_42 String,
    field_43 String,
    field_44 String,
    field_45 String,
    field_46 String,
    field_47 String,
    field_48 String,
    field_49 String,
    field_50 String,
    field_51 String,
    field_52 String,
    field_53 String,
    field_54 String,
    field_55 String,
    field_56 String,
    field_57 String,
    field_58 String,
    field_59 String,
    field_60 String,
    field_61 String,
    field_62 String,
    field_63 String,
    field_64 String,
    field_65 String,
    field_66 String,
    field_67 String,
    field_68 String,
    field_69 String,
    field_70 String,
    field_71 String,
    field_72 String,
    field_73 String,
    field_74 String,
    field_75 String,
    field_76 String,
    field_77 String,
    field_78 String,
    field_79 String,
    field_80 String,
    field_81 String,
    field_82 String,
    field_83 String,
    field_84 String,
    field_85 String,
    field_86 String,
    field_87 String,
    field_88 String,
    field_89 String,
    field_90 String,
    field_91 String,
    field_92 String,
    field_93 String,
    field_94 String,
    field_95 String,
    field_96 String,
    field_97 String,
    field_98 String,
    field_99 String,
    field_100 String,
    field_101 String,
    field_102 String,
    field_103 String,
    field_104 String,
    field_105 String,
    field_106 String,
    field_107 String,
    field_108 String,
    field_109 String,
    field_110 String,
    field_111 String,
    field_112 String,
    field_113 String,
    field_114 String,
    field_115 String,
    field_116 String,
    field_117 String,
    field_118 String,
    field_119 String,
    field_120 String,
    field_121 String,
    field_122 String,
    field_123 String,
    field_124 String,
    field_125 String,
    field_126 String,
    field_127 String,
    field_128 String,
    field_129 String,
    field_130 String,
    field_131 String,
    field_132 String,
    field_133 String,
    field_134 String,
    field_135 String,
    field_136 String,
    field_137 String,
    field_138 String,
    field_139 String,
    field_140 String,
    field_141 String,
    field_142 String,
    field_143 String,
    field_144 String,
    field_145 String,
    field_146 String,
    field_147 String,
    field_148 String,
    field_149 String,
    field_150 String,
    field_151 String,
    field_152 String,
    field_153 String,
    field_154 String,
    field_155 String,
    field_156 String,
    field_157 String,
    field_158 String,
    field_159 String,
    field_160 String,
    field_161 String,
    field_162 String,
    field_163 String,
    field_164 String,
    field_165 String,
    field_166 String,
    field_167 String,
    field_168 String,
    field_169 String,
    field_170 String,
    field_171 String,
    field_172 String,
    field_173 String,
    field_174 String,
    field_175 String,
    field_176 String,
    field_177 String,
    field_178 String,
    field_179 String,
    field_180 String,
    field_181 String,
    field_182 String,
    field_183 String,
    field_184 String,
    field_185 String,
    field_186 String,
    field_187 String,
    field_188 String,
    field_189 String,
    field_190 String,
    field_191 String,
    field_192 String,
    field_193 String,
    field_194 String,
    field_195 String,
    field_196 String,
    field_197 String,
    field_198 String,
    field_199 String,
    field_200 String,
    field_201 String,
    field_202 String,
    field_203 String,
    field_204 String,
    field_205 String,
    field_206 String,
    field_207 String,
    field_208 String,
    field_209 String,
    field_210 String,
    field_211 String,
    field_212 String,
    field_213 String,
    field_214 String,
    field_215 String,
    field_216 String,
    field_217 String,
    field_218 String,
    field_219 String,
    field_220 String,
    field_221 String,
    field_222 String,
    field_223 String,
    field_224 String,
    field_225 String,
    field_226 String,
    field_227 String,
    field_228 String,
    field_229 String,
    field_230 String,
    field_231 String,
    field_232 String,
    field_233 String,
    field_234 String,
    field_235 String,
    field_236 String,
    field_237 String,
    field_238 String,
    field_239 String,
    field_240 String,
    field_241 String,
    field_242 String,
    field_243 String,
    field_244 String,
    field_245 String,
    field_246 String,
    field_247 String,
    field_248 String,
    field_249 String,
    field_250 String,
    field_251 String,
    field_252 String,
    field_253 String,
    field_254 String,
    field_255 String,
    field_256 String,
    field_257 Array(String),
    field_258 Array(String),
    field_259 Array(String),
    field_260 Array(String),
    field_261 Array(String)
)
ENGINE = MergeTree
PARTITION BY (partition_id)
ORDER BY (user_id)
PRIMARY KEY (user_id)
`

The mutations sql is some like:
`ALTER TABLE entries UPDATE flag = (flag + 2) % 3 WHERE (x_field1 IN ('5fd1cfab6194e215078b4ed8',......''5fd1cfab6194e215078b4ed2'') and ) AND (flag != 2)`
I may not able to change number_of_free_entries_in_pool_to_execute_mutation as it may totally  block mutation actions and we can't leave too many undo mutations

I also compared same dataset  between Clickhouse  20.12.3.3 and 19.13.3.26 and found out:
1. Concurrently  mutations can get performance as good as signal mutation on 19.13.3.26
2. Concurrently  mutations performance is too slow to  get 'Too many parts' error while  signal mutation works normal on 20.12.3.3 

Any Advice pls?

**Comment by den-crane** [comment]
Check performance against this exact version: **20.3.8.53**

https://github.com/ClickHouse/ClickHouse/issues/9621

**Comment by allen12921** [comment]
You save my days,It works like a charm
Will we fix it on the latest version in further?

**Comment by alexey-milovidov** [comment]
Yes, we have separated the pools for merges and mutations to avoid this issue.

**Comment by allen12921** [comment]
@alexey-milovidov  May I know how can I change the pools number for both merges and mutations ?

**Comment by allen12921** [comment]
@den-crane 
Hi Den,
   Here I'm again,I have upgraded CH from 20.3.8.53 to 21.7.2.7 which contains  #25371  commit but the merge speed become slow again.
Any idea?
