### ISSUE TITLE
WITH TOTALS in subquery

### ISSUE THREAD

**Issue by orloffv** [ClickHouse/ClickHouse#18116]
1)
i have a simple query
```
SELECT
       field, count() as count
FROM table
GROUP BY field WITH TOTALS
ORDER BY count DESC
LIMIT 10 FORMAT JSON
```
works good, i get `"rows_before_limit_at_least"`. i can use it information for pagination OR info message 'total rows in table'

2)
difficult query with subquery(i add subquery for optimize perfomance)
```
SELECT
       field, count() as count
FROM table
WHERE in (
     field, (
              SELECT field 
              FROM table
              GROUP BY field WITH TOTALS
              ORDER BY COUNT() DESC
              LIMIT 10
     )
)
GROUP BY field
ORDER BY count DESC
LIMIT 10 FORMAT JSON
```
`"rows_before_limit_at_least"` = 10
Can i get total rows without a separate request?

**Comment by alexey-milovidov** [comment]
It's only possible if WITH TOTALS is in the direct subquery in FROM.
