### ISSUE TITLE
Some system tables show too much info to a user without privileges.

### ISSUE THREAD

**Issue by MyroTk** [ClickHouse/ClickHouse#18110]
**Describe the bug**
The following `system` tables are accessible to a user with no privileges and show sensitive information such as queries, table names, user info, etc. :
 * processes 
 * query_log 
 * query_thread_log 
 * clusters 
 * events 
 * graphite_retentions 
 * stack_trace 
 * trace_log
 * user_directories 
 * zookeeper 
 * macros

**How to reproduce**
* ClickHouse server version 20.13.1 revision 54442

**Comment by alexey-milovidov** [comment]
Fixed by #38970.

Note: for compatibility reasons, it needs to enable a switch in the configuration file.
