### ISSUE TITLE
intel qat compression hardware acceleration support ?

### ISSUE THREAD

**Issue by mcarbonneaux** [ClickHouse/ClickHouse#18117]
While be possible to add support Intel QAT compression acceleration ?
Because they are integrate in new intel scalable cpu ! 

seem to 30% boost on hadoop :
https://www.intel.com/content/www/us/en/architecture-and-technology/faster-hadoop-run-times-quickassist-technology.html

**Comment by alexey-milovidov** [comment]
References:
https://github.com/intel/QATzip
https://github.com/ceph/ceph/pull/19714

Do you have some numbers for comparison?

**Comment by mcarbonneaux** [comment]
Other reference:
- https://jira.whamcloud.com/secure/attachment/28344/BGI-Intel-QAT-Performance-2016-09.pdf
- https://indico.cern.ch/event/611563/contributions/2608111/attachments/1474747/2283662/root_io_workshop_hw_compression_engine.pdf
- https://www.servethehome.com/intel-quickassist-technology-and-openssl-setup-insights-and-initial-benchmarks/
- https://www.intel.com/content/www/us/en/architecture-and-technology/intel-quick-assist-technology-overview.html
- https://01.org/intel-quickassist-technology
- https://github.com/Intel-bigdata/IntelQATCodec
- https://wiki.hpdd.intel.com/download/attachments/128517023/3_Online_Compression_with_QAT_in_DAOS.pdf?version=1&modificationDate=1605817929593&api=v2

On crypto they are used in F5 ADC devices to accelerate SSL...
intel announce 100gbit/s of ssl crypto per QAT card...

**Comment by alexey-milovidov** [comment]
Done, see the press release: https://www.anandtech.com/show/17596/intel-demos-sapphire-rapids-accelerators-at-innovation-2022

**Comment by mcarbonneaux** [comment]
in whitch version is in ?

**Comment by alexey-milovidov** [comment]
@mcarbonneaux it is not included in any of the official releases, as it was enabled under a custom build flag.
See also https://github.com/ClickHouse/ClickHouse/issues/42982

**Comment by mcarbonneaux** [comment]
Was intel qat tested on Intel only for a comparable comparison?

**Comment by cangyin** [comment]
> @mcarbonneaux it is not included in any of the official releases, as it was enabled under a custom build flag. See also #42982

What's the difference between the intel QAT and QPL support in #42982, I googled for some time but failed to find relationship between them.
