### ISSUE TITLE
disk full, can not use mutations, how to delete data?

### ISSUE THREAD

**Issue by gj-zhang** [ClickHouse/ClickHouse#18122]
disk full, when i execute "alter table xxx delete where toYYYYMMDD(timestamp) = toYYYYMMDD(toDate('2020-12-05'))",
then i query from system.mutations, error:  Code: 243, e.displayText() = DB::Exception: Cannot reserve 26.31 GiB, not enough space (version 20.9.3.45 (official build))

any other way to delete data?

**Comment by taiyang-li** [comment]
`ALTER DELETE` need extra disk space to reserve  intermediate result. Maybe you can consider `ALTER DROP PARTITION`, which drop a partition each time.

**Comment by gj-zhang** [comment]
> `ALTER DELETE` need extra disk space to reserve intermediate result. Maybe you can consider `ALTER DROP PARTITION`, which drop a partition each time.

Is that the only way?

**Comment by alexey-milovidov** [comment]
@gj-zhang You can DETACH some old partition, then manually move it out to some other server. Then perform ALTER DELETE to delete some data. When disk space will be freed, move partition back and ATTACH.

**Comment by alexey-milovidov** [comment]
If you are using cloud service, just increase the disk size or move all data to another VM with larger disk.

**Comment by alexey-milovidov** [comment]
If table is replicated, you can also migrate to another server with zero downtime by creating a new replica on larger server and then dropping the old replica.
