### ISSUE TITLE
ENABLE S3 and HDFS 

### ISSUE THREAD

**Issue by baibaichen** [ClickHouse/ClickHouse#18125]
Hi

I am developing on apple, I need test and debug s3 and hdfs functionality. I did some investigation with removing `Not APPLE` in s3.cmake and hdfs.cmake.

It looks that only has one link issue on iconv which we can use osx system's lib.

Any Suggestion? 

If there is no more other issues, I can submit PR

**Comment by alexey-milovidov** [comment]
Yes, submitting a PR will be very helpful.
