### ISSUE TITLE
RabbitMQ engine fails to parse string json field

### ISSUE THREAD

**Issue by paul-nameless** [ClickHouse/ClickHouse#18131]
**Describe the bug**
I am trying to use RabbitMQ engine and can't make it work with parsing string json field and String column.
I wonder if it is a bug or I am doing something wrong.

**How to reproduce**
* Which ClickHouse server version to use
```
> curl localhost:8123 -d "select version()"
20.12.3.3
```
* `CREATE TABLE` statements for all tables involved
```
CREATE TABLE default.queue
(
    `key` UInt64,
    `value` UInt64,
    `data` String
)
ENGINE = RabbitMQ
SETTINGS rabbitmq_host_port = 'localhost:5672', rabbitmq_exchange_name = 'exchange2', rabbitmq_format = 'JSONEachRow', rabbitmq_routing_key_li
t = 'test', rabbitmq_exchange_type = 'direct', rabbitmq_num_consumers = 5, rabbitmq_skip_broken_messages = 0
```
* Steps to reproduce
  1. Run rabbitmq
  2. Run query above to create table in clickhouse
  3. Run python script below
```python

import json
import pika

conn = pika.BlockingConnection(pika.ConnectionParameters(host="localhost"))
ch = conn.channel()

ch.basic_publish(
        exchange="exchange2",
        routing_key="test",
        body=json.dumps({"key": 1, "value": 2, "data": "test"}),
    )
```

**Expected behavior**
`curl localhost:8123 -d "select * from queue"` returns `1 2 test`

**Error message and/or stacktrace**
```
# curl localhost:8123 -d "select * from queue"
Code: 27, e.displayText() = DB::Exception: Cannot parse input: expected '{' before: '.0, "data": "a"}': (at row 1)
: While executing SourceFromInputStream (version 20.12.3.3 (official build))
```

**Comment by kssenii** [comment]
@paul-nameless I checked your example and it works fine...

**Comment by paul-nameless** [comment]
Sorry for your spended time, there was my mistake.
