### ISSUE TITLE
Unexpected SHOW TABLES behaviour without where clause

### ISSUE THREAD

**Issue by fastio** [ClickHouse/ClickHouse#18139]
**Describe the unexpected behaviour**

When `use_antlr_parser = 1`, 
```SHOW TABLES``` query returns unexpected result.

**How to reproduce**

Execute the SQL: ``` SHOW TABLES```

**Expected behavior**

It should return the table list of current database.

**Error message and/or stacktrace**

```
Received exception from server (version 20.13.1):
Code: 35. DB::Exception: Received from localhost:9000. DB::Exception: Number of arguments for function "and" should be at least 2: passed 1: While processing and(1).
```

**Additional context**
version: 20.13.1.1
os: macos

**Comment by fastio** [comment]
Please assigned it to me.

**Comment by spongedu** [comment]
`ParseTreeVisitor` set where clause even if there isn't any in the statement. Add a condition check before `setWhereClause` in `ParseTreeVisitor::visitShowTablesStmt` should solve this.

**Comment by fastio** [comment]
> setWhereClause

Thanks.
