### ISSUE TITLE
20.12.3.3 Less amount of data is returned if "read backoff" is in effect.

### ISSUE THREAD

**Issue by mrAndersen** [ClickHouse/ClickHouse#18137]
Consider following: 

1 master server with Distributed table (```tracking_distributed```), 2 shards, previously was 4 shards, but during chat discussion i've reduced them to 2 for easier debugging (including master server each having 1 replica with 1 MergeTree table ```tracking_shard```). Also a ```tracking``` table - which is an old table that i want to re-distribute and aggregate while doing inserts from it into ```tracking_distributed``` which is connected to MV on the same server, by doing following insert:

```
insert into tracking_distributed (date, datetime, col1, col2, col3, col4, col5,
                                  col6, col7, col8, col9,
                                  col10, col11, col12, col13, col14, col15, col16,
                                  col17, col18, col19,
                                  col20, col21, col22, col23,
                                  col24, col25,
                                  col26, col27, col28, col29, col30, col31)
select date,
          datetime,
          1     as raw1,
          0     as raw2,
          col3,
             col4,
             col5,
             col6,
             col7,
             col8,
             col9,
             col10,
             col11,
             col12,
             col13,
             col14,
             col15,
             col16,
             col17,
             col18,
             col19,
             col20,
             col21,
             col22,
             col23,
             col24,
             col25,
             [[]]  as raw3,
             0     as raw4,
             'RUB' as raw5,
             []    as raw6,
             0     as raw7,
             []    as raw8
      from tracking
      where date > '2010-01-01'
        and date <= '2019-07-01'
```

Data inside ```tracking``` are starting from 2019-01-08. After this insert i am checking that all rows are inserted correctly by doing following two queries:

```
select count(), concat(toString(toMonth(date)), '.', toString(toYear(date))) as dt
from tracking_distributed
where (date >= '2000-02-01')
  AND (date < '2019-07-01')
group by dt
order by dt;

select count(), concat(toString(toMonth(date)), '.', toString(toYear(date))) as dt
from tracking
where (date >= '2000-02-01')
  AND (date < '2019-07-01')
group by dt
order by dt;
```

And getting very strange results:

tracking_distributed:
```
78238,1.2019
8406510,2.2019
7700480,3.2019
47273866,4.2019
86705743,5.2019
69612803,6.2019
```

tracking:
```
78238,1.2019
8406510,2.2019
21402619,3.2019
47759435,4.2019
89318991,5.2019
76633611,6.2019
```

```tracking``` (csv, no column names) - [schema](https://pastebin.com/G5m6taU7) 
```tracking_dsitributed``` (csv, no column names) - [schema](https://pastebin.com/RPXXn4w2)

0) Before inserting on every shard is executed ```truncate table tracking_shard``` and additionally executed ```truncate table tracking_distributed``` 
1) Logs does not have any errors on shards and on master
2) If i am doing 6 separate queries for 6 month - i am getting CORRECT data inside ```tracking_distributed``` e.g. ```where date >= 2019-01-01 and date < 2019-02-01``` ```where date >= 2019-02-01 and date < 2019-03-01```
3) I've tried stop distributed flushes, do insert then flush in one operation - same result
4) Tried using insert_distributed_sync=1, same result but slower
5) Tried wraping initial select with subselect e.g. select * from (select date, datetime ...), same results
6) Servers and clickhouse-server on every shard have UTC datetime
7) ```/var/lib/clickhouse/data/<db>/<distributed_table>``` location empty after insert is finished
8) Trace log - https://pastebin.com/UThwL0XV
9) Also tried removing default toDate(datetime) in distributed table - but no luck

**Comment by mrAndersen** [comment]
UP:

Problem also occurs when doing inserts like ```insert into tracking_shard select ... from remote(server,'tracking') where cityHash64(date) % 2 == 1``` + local query on server1 like ```insert into tracking_shard select ... from tracking where cityHash64(date) % 2 == 0```

**Comment by mrAndersen** [comment]
UP:

Problem FOUND! If i set max_threads=1 (from default 8) everything is working! All data are in place!
Also there are some strange messages in logs:

```
<Debug> MergeTreeReadPool: Slow read, event №1: read 1048576 bytes in 1.104 sec
<Debug> MergeTreeReadPool: Will lower number of threads to 7
```

I assume after this some data are lost silently without any errors

**Comment by mrAndersen** [comment]
UP:

Setting this:

read_backoff_min_latency_ms=100000 (so number of threads never lowers)
max_threads=5
max_insert_threads=5

Works PERFECTLY. So this is data loss every time when number of threads for MergeTreeReadPool lowers due to backoff mechanics...

**Comment by alexey-milovidov** [comment]
@den-crane What versions are affected?
Could you please make a draft PR with failing test?

**Comment by KochetovNicolai** [comment]
Repro:
```
create table t (x UInt64, s String) engine = MergeTree order by x;
INSERT INTO t SELECT
    number,
    if(number < (8129 * 1024), arrayStringConcat(arrayMap(x -> toString(x), range(number % 128)), ' '), '')
FROM numbers((8129 * 1024) * 3);

select count(), sum(length(s)) from t settings max_threads = 3, read_backoff_min_latency_ms = 1, read_backoff_max_throughput = 1000000000, read_backoff_min_interval_between_events_ms = 1, read_backoff_min_events = 1, read_backoff_min_concurrency = 1;
```

```
:) select count(), sum(length(s)) from t settings max_threads = 3, read_backoff_min_latency_ms = 1, read_backoff_max_throughput = 1000000000, read_backoff_min_interval_between_events_ms = 1, read_backoff_min_events = 1, read_backoff_min_concurrency = 1

SELECT
    count(),
    sum(length(s))
FROM t
SETTINGS max_threads = 3, read_backoff_min_latency_ms = 1, read_backoff_max_throughput = 1000000000, read_backoff_min_interval_between_events_ms = 1, read_backoff_min_events = 1, read_backoff_min_concurrency = 1

Query id: 5605ae8e-3ce4-4b06-92eb-e314d4f81bba

┌──count()─┬─sum(length(s))─┐
│ 20000116 │      983073009 │
└──────────┴────────────────┘

1 rows in set. Elapsed: 0.169 sec. Processed 20.00 million rows, 1.16 GB (118.51 million rows/s., 6.89 GB/s.) 

:) select count(), sum(length(s)) from t settings max_threads = 3, read_backoff_min_latency_ms = 1, read_backoff_max_throughput = 1000000000, read_backoff_min_interval_between_events_ms = 1, read_backoff_min_events = 1, read_backoff_min_concurrency = 1

SELECT
    count(),
    sum(length(s))
FROM t
SETTINGS max_threads = 3, read_backoff_min_latency_ms = 1, read_backoff_max_throughput = 1000000000, read_backoff_min_interval_between_events_ms = 1, read_backoff_min_events = 1, read_backoff_min_concurrency = 1

Query id: c0f5f964-3db0-4bf1-ae9c-3f50d4af558f

┌──count()─┬─sum(length(s))─┐
│ 18607290 │     1510185631 │
└──────────┴────────────────┘

1 rows in set. Elapsed: 0.416 sec. Processed 18.61 million rows, 1.68 GB (44.72 million rows/s., 4.03 GB/s.) 

```

**Comment by KochetovNicolai** [comment]
Bug was added in #16423
