### ISSUE TITLE
untuple expand fields can not be accessed again

### ISSUE THREAD

**Issue by melin** [ClickHouse/ClickHouse#18133]
untuple expand fields can not be accessed again

```sql
select ACTIVITY_RAW, parseDateTime64BestEffort(toString(S_D_EVENTOCCURTIME)) from (
  SELECT JSONExtractRaw(activity_json, 'activity') as ACTIVITY_RAW,
    untuple(JSONExtract(ACTIVITY_RAW, 'Tuple(S_S_PARTNERCODE String, S_S_EVENTTYPE String, S_S_EVENTID String, 
    S_E_INVOKETYPE String, S_D_EVENTOCCURTIME Int64')) activity
  FROM activity_result
);
```
![image](https://user-images.githubusercontent.com/1145830/102325747-7c7f8480-3fbe-11eb-999d-03a04d0367cd.png)

**Comment by hexiaoting** [comment]
Can you give us a minimal info that can reproduce this error? including how to create this table and some data

**Comment by melin** [comment]
> Can you give us a minimal info that can reproduce this error? including how to create this table and some data

select _ut_1 from (select untuple(tuple(1, 2)))

**Comment by alexey-milovidov** [comment]
CC @amosbird @KochetovNicolai

**Comment by larry-cdn77** [comment]
I can indeed see this in version 21.8 LTS (was fine in previous 21.3 LTS)

**Comment by alexey-milovidov** [comment]
The behavior of `untuple` function has been deliberately made worse as the previous implementation was not memory-safe.
Now it's only possible to access them with the following syntax:

```
SELECT `tupleElement((1, 2), 1)` FROM (select untuple(tuple(1, 2)))
```

It is inconvenient. But I'd rather recommend not using the `untuple` function at all.
