### ISSUE TITLE
Inf to UInt64 is 0

### ISSUE THREAD

**Issue by simPod** [ClickHouse/ClickHouse#18143]
_Disclosure: I'm not a mathematician_ 😄 

To start, I'd start with this example

```sql
select toDateTime('hi');
```

ClickHouse throws exception because it does not know how to make a datetime from `'hi'`.

```sql
select toUInt64(Inf);
```

Gives 0 though. I know there's no representation for ∞ in UInt range but I'd either expect error thrown, same as above, or something closest to the infinity -> max uint. 0 seems kind of unexpected to me.

Is there any reasoning for that? Thanks!

**Comment by alexey-milovidov** [comment]
It's implementation specific behaviour that should be documented.

For efficiency, we use the same CPU instructions for conversion as for any other float values, there is no special case. And we return whatever result these CPU instructions will produce. Occasionally it is zero but it's not guaranteed.
