### ISSUE TITLE
Direct conversion to IPv6 from string

### ISSUE THREAD

**Issue by ifoo** [ClickHouse/ClickHouse#18152]
Currently there are the `toIPv4()` and `toIPv6()` functions to parse an IP address from a `String` type.
In order to be able to store both v4 and v6 addresses in a column, it needs to be IPv6, obviously.
Alternatively, they could be stored as `String` as well, but that would imply loosing CIDR matching.

Now, v4 addresses need to be "mapped" to v6 address in order to work correctly (e.g. `::ffff:192.168.1.1`).
With the current version of `toIPv6()` it is not possible to directly parse an IPv4 address.
Workarounds do exist (e.g. `if(toIPv6(src_ip) != defaultValueOfTypeName('IPv6'), toIPv6(src_ip), toIPv6(concat('::ffff:', src_ip)))`), but they are quite cumbersome to use.

It would be nice to either:

- Have `toIPv6()` also parse IPv4 strings, and automatically do the v6 mapping
- Have a new function (e.g. something like `parseIPv6()`) that implements this behavior, so `toIPv6()` stays backwards compatible.

**Comment by alexey-milovidov** [comment]
+1

Let's allow `toIPv6` and `IPv6StringToNum` to parse IPv4 addresses into IPv6-mapped addresses.

**Comment by bharatnc** [comment]
@alexey-milovidov I think I can take a stab at it if I can have this assigned.

**Comment by alexey-milovidov** [comment]
@bharatnc Perfect.

**Comment by bharatnc** [comment]
I wasn't able to get to this issue so far. Just thought it would only be fair to leave a note so that others can pick this up in the meantime if I still don't get to this by next week.
