### ISSUE TITLE
[MaterializeMySQL] DB::Exception :cannot read all data.Bytes read: 0. Bytes expected 4.

### ISSUE THREAD

**Issue by mingjia1** [ClickHouse/ClickHouse#18151]
i use to clickhouse20.12.3 ,this MaterializeMySQLSyncThread to sync 2 mysql schema, one schema is ok,but other  error message is "cannot read all data.Bytes read: 0. Bytes expected 4."
<img width="766" alt="20201217010228" src="https://user-images.githubusercontent.com/20858449/102381074-bb83f900-4003-11eb-80f4-fcebc250b346.png">

**Comment by zhang2014** [comment]
I will try to fixes it.

**Comment by Doslin** [comment]
> I will try to fixes it.

解决了吗

**Comment by alexey-milovidov** [comment]
@zhang2014 Your help will be really appreciated.
