### ISSUE TITLE
Debug assertion: Arguments of 'modulo' have incorrect data types

### ISSUE THREAD

**Issue by abyss7** [ClickHouse/ClickHouse#18189]
Excerpt from server log:

> 2020.12.17 05:35:47.589320 [ 66 ] {0aafa923-375a-4d36-94ad-b63780de159f} <Fatal> : Logical error: 'Arguments of 'modulo' have incorrect data types: 'x' of type 'UInt64', '' of type 'Nullable(Nothing)''.
> 2020.12.17 05:35:47.589858 [ 63 ] {} <Trace> BaseDaemon: Received signal 6
> 2020.12.17 05:35:47.590246 [ 148 ] {} <Fatal> BaseDaemon: ########################################
> 2020.12.17 05:35:47.590593 [ 148 ] {} <Fatal> BaseDaemon: (version 20.13.1.5439, build id: 260C17DE928A2720) (from thread 66) (query_id: 0aafa923-375a-4d36-94ad-b63780de159f) Received signal Aborted (6)
> 2020.12.17 05:35:47.590850 [ 148 ] {} <Fatal> BaseDaemon: 
> 2020.12.17 05:35:47.591174 [ 148 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f8882736fb7 0x7f8882738921 0x112c4eac 0x112c4f51 0x13dfcc3f 0x14953a38 0x14952261 0x131f596e 0x131fbc93 0x131fcc35 0x13210392 0x1afe6bde 0x1afe1b07 0x1afe192a 0x1afe2852 0x1afe6dc4 0x1afe1041 0x1afe0e5f 0x1afe3190 0x1b23335a 0x1ad0015b 0x1a44305d 0x1a43fc6f 0x1a43f156 0x1a748ef9 0x1a74947d 0x1a96e109 0x1a96cb7a
> 2020.12.17 05:35:47.591691 [ 148 ] {} <Fatal> BaseDaemon: 4. /build/glibc-S7xCS9/glibc-2.27/signal/../sysdeps/unix/sysv/linux/raise.c:51: raise @ 0x3efb7 in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.27.so
> 2020.12.17 05:35:47.591933 [ 148 ] {} <Fatal> BaseDaemon: 5. /build/glibc-S7xCS9/glibc-2.27/stdlib/abort.c:81: abort @ 0x40921 in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.27.so
> 2020.12.17 05:35:47.592452 [ 148 ] {} <Fatal> BaseDaemon: 6. /build/obj-x86_64-linux-gnu/../src/Common/Exception.cpp:50: DB::handle_error_code(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x112c4eac in /workspace/clickhouse
> 2020.12.17 05:35:47.592877 [ 148 ] {} <Fatal> BaseDaemon: 7. /build/obj-x86_64-linux-gnu/../src/Common/Exception.cpp:56: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x112c4f51 in /workspace/clickhouse
> 2020.12.17 05:35:47.608131 [ 148 ] {} <Fatal> BaseDaemon: 8. /build/obj-x86_64-linux-gnu/../src/Common/Exception.h:37: DB::Exception::Exception<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&) @ 0x13dfcc3f in /workspace/clickhouse
> 2020.12.17 05:35:47.621111 [ 148 ] {} <Fatal> BaseDaemon: 9. /build/obj-x86_64-linux-gnu/../src/Functions/FunctionBinaryArithmetic.h:1095: DB::FunctionBinaryArithmetic<DB::ModuloImpl, DB::NameModulo, false>::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x14953a38 in /workspace/clickhouse
> 2020.12.17 05:35:47.633717 [ 148 ] {} <Fatal> BaseDaemon: 10. /build/obj-x86_64-linux-gnu/../src/Functions/FunctionBinaryArithmetic.h:1200: DB::FunctionBinaryArithmeticWithConstants<DB::ModuloImpl, DB::NameModulo, false>::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x14952261 in /workspace/clickhouse
> 2020.12.17 05:35:47.641176 [ 148 ] {} <Fatal> BaseDaemon: 11. /build/obj-x86_64-linux-gnu/../src/Functions/IFunctionAdaptors.h:152: DB::DefaultExecutable::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x131f596e in /workspace/clickhouse
> 2020.12.17 05:35:47.648432 [ 148 ] {} <Fatal> BaseDaemon: 12. /build/obj-x86_64-linux-gnu/../src/Functions/IFunction.cpp:293: DB::ExecutableFunctionAdaptor::executeWithoutLowCardinalityColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x131fbc93 in /workspace/clickhouse
> 2020.12.17 05:35:47.655723 [ 148 ] {} <Fatal> BaseDaemon: 13. /build/obj-x86_64-linux-gnu/../src/Functions/IFunction.cpp:448: DB::ExecutableFunctionAdaptor::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x131fcc35 in /workspace/clickhouse
> 2020.12.17 05:35:47.664096 [ 148 ] {} <Fatal> BaseDaemon: 14. /build/obj-x86_64-linux-gnu/../src/Functions/IFunction.h:78: DB::IFunctionBase::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x13210392 in /workspace/clickhouse
> 2020.12.17 05:35:47.713021 [ 148 ] {} <Fatal> BaseDaemon: 15. /build/obj-x86_64-linux-gnu/../src/Storages/MergeTree/KeyCondition.cpp:485: DB::applyFunctionForField(std::__1::shared_ptr<DB::IFunctionBase> const&, std::__1::shared_ptr<DB::IDataType const> const&, DB::Field const&) @ 0x1afe6bde in /workspace/clickhouse
> 2020.12.17 05:35:47.762725 [ 148 ] {} <Fatal> BaseDaemon: 16. /build/obj-x86_64-linux-gnu/../src/Storages/MergeTree/KeyCondition.cpp:536: DB::applyFunction(std::__1::shared_ptr<DB::IFunctionBase> const&, std::__1::shared_ptr<DB::IDataType const> const&, DB::FieldRef const&) @ 0x1afe1b07 in /workspace/clickhouse
> 2020.12.17 05:35:47.812018 [ 148 ] {} <Fatal> BaseDaemon: 17. /build/obj-x86_64-linux-gnu/../src/Storages/MergeTree/KeyCondition.cpp:1423: DB::KeyCondition::applyMonotonicFunctionsChainToRange(DB::Range, std::__1::vector<std::__1::shared_ptr<DB::IFunctionBase>, std::__1::allocator<std::__1::shared_ptr<DB::IFunctionBase> > > const&, std::__1::shared_ptr<DB::IDataType const>, bool) @ 0x1afe192a in /workspace/clickhouse
> 2020.12.17 05:35:47.861217 [ 148 ] {} <Fatal> BaseDaemon: 18. /build/obj-x86_64-linux-gnu/../src/Storages/MergeTree/KeyCondition.cpp:1538: DB::KeyCondition::checkInHyperrectangle(std::__1::vector<DB::Range, std::__1::allocator<DB::Range> > const&, std::__1::vector<std::__1::shared_ptr<DB::IDataType const>, std::__1::allocator<std::__1::shared_ptr<DB::IDataType const> > > const&) const @ 0x1afe2852 in /workspace/clickhouse
> 2020.12.17 05:35:47.910579 [ 148 ] {} <Fatal> BaseDaemon: 19. /build/obj-x86_64-linux-gnu/../src/Storages/MergeTree/KeyCondition.cpp:1387: DB::KeyCondition::checkInRange(unsigned long, DB::FieldRef const*, DB::FieldRef const*, std::__1::vector<std::__1::shared_ptr<DB::IDataType const>, std::__1::allocator<std::__1::shared_ptr<DB::IDataType const> > > const&, bool, BoolMask) const::$_17::operator()(std::__1::vector<DB::Range, std::__1::allocator<DB::Range> > const&) const @ 0x1afe6dc4 in /workspace/clickhouse
> 2020.12.17 05:35:47.959804 [ 148 ] {} <Fatal> BaseDaemon: 20. /build/obj-x86_64-linux-gnu/../src/Storages/MergeTree/KeyCondition.cpp:1299: BoolMask DB::forAnyHyperrectangle<DB::KeyCondition::checkInRange(unsigned long, DB::FieldRef const*, DB::FieldRef const*, std::__1::vector<std::__1::shared_ptr<DB::IDataType const>, std::__1::allocator<std::__1::shared_ptr<DB::IDataType const> > > const&, bool, BoolMask) const::$_17>(unsigned long, DB::FieldRef const*, DB::FieldRef const*, bool, bool, std::__1::vector<DB::Range, std::__1::allocator<DB::Range> >&, unsigned long, BoolMask, DB::KeyCondition::checkInRange(unsigned long, DB::FieldRef const*, DB::FieldRef const*, std::__1::vector<std::__1::shared_ptr<DB::IDataType const>, std::__1::allocator<std::__1::shared_ptr<DB::IDataType const> > > const&, bool, BoolMask) const::$_17&&) @ 0x1afe1041 in /workspace/clickhouse
> 2020.12.17 05:35:48.009215 [ 148 ] {} <Fatal> BaseDaemon: 21. /build/obj-x86_64-linux-gnu/../src/Storages/MergeTree/KeyCondition.cpp:1384: DB::KeyCondition::checkInRange(unsigned long, DB::FieldRef const*, DB::FieldRef const*, std::__1::vector<std::__1::shared_ptr<DB::IDataType const>, std::__1::allocator<std::__1::shared_ptr<DB::IDataType const> > > const&, bool, BoolMask) const @ 0x1afe0e5f in /workspace/clickhouse
> 2020.12.17 05:35:48.058632 [ 148 ] {} <Fatal> BaseDaemon: 22. /build/obj-x86_64-linux-gnu/../src/Storages/MergeTree/KeyCondition.cpp:1632: DB::KeyCondition::mayBeTrueInRange(unsigned long, DB::FieldRef const*, DB::FieldRef const*, std::__1::vector<std::__1::shared_ptr<DB::IDataType const>, std::__1::allocator<std::__1::shared_ptr<DB::IDataType const> > > const&) const @ 0x1afe3190 in /workspace/clickhouse
> 2020.12.17 05:35:48.109672 [ 148 ] {} <Fatal> BaseDaemon: 23. /build/obj-x86_64-linux-gnu/../src/Storages/MergeTree/PartitionPruner.cpp:18: DB::PartitionPruner::canBePruned(std::__1::shared_ptr<DB::IMergeTreeDataPart const> const&) @ 0x1b23335a in /workspace/clickhouse
> 2020.12.17 05:35:48.156897 [ 148 ] {} <Fatal> BaseDaemon: 24. /build/obj-x86_64-linux-gnu/../src/Storages/StorageMergeTree.cpp:220: DB::StorageMergeTree::totalRowsByPartitionPredicate(DB::SelectQueryInfo const&, DB::Context const&) const @ 0x1ad0015b in /workspace/clickhouse
> 2020.12.17 05:35:48.198767 [ 148 ] {} <Fatal> BaseDaemon: 25. /build/obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectQuery.cpp:1189: DB::InterpreterSelectQuery::executeFetchColumns(DB::QueryProcessingStage::Enum, DB::QueryPlan&, std::__1::shared_ptr<DB::PrewhereDAGInfo> const&, std::__1::unordered_set<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x1a44305d in /workspace/clickhouse
> 2020.12.17 05:35:48.241186 [ 148 ] {} <Fatal> BaseDaemon: 26. /build/obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectQuery.cpp:819: DB::InterpreterSelectQuery::executeImpl(DB::QueryPlan&, std::__1::shared_ptr<DB::IBlockInputStream> const&, std::__1::optional<DB::Pipe>) @ 0x1a43fc6f in /workspace/clickhouse
> 2020.12.17 05:35:48.283175 [ 148 ] {} <Fatal> BaseDaemon: 27. /build/obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectQuery.cpp:471: DB::InterpreterSelectQuery::buildQueryPlan(DB::QueryPlan&) @ 0x1a43f156 in /workspace/clickhouse
> 2020.12.17 05:35:48.325808 [ 148 ] {} <Fatal> BaseDaemon: 28. /build/obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectWithUnionQuery.cpp:301: DB::InterpreterSelectWithUnionQuery::buildQueryPlan(DB::QueryPlan&) @ 0x1a748ef9 in /workspace/clickhouse
> 2020.12.17 05:35:48.368715 [ 148 ] {} <Fatal> BaseDaemon: 29. /build/obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectWithUnionQuery.cpp:338: DB::InterpreterSelectWithUnionQuery::execute() @ 0x1a74947d in /workspace/clickhouse
> 2020.12.17 05:35:48.413417 [ 148 ] {} <Fatal> BaseDaemon: 30. /build/obj-x86_64-linux-gnu/../src/Interpreters/executeQuery.cpp:507: DB::executeQueryImpl(char const*, char const*, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool, DB::ReadBuffer*) @ 0x1a96e109 in /workspace/clickhouse
> 2020.12.17 05:35:48.458460 [ 148 ] {} <Fatal> BaseDaemon: 31. /build/obj-x86_64-linux-gnu/../src/Interpreters/executeQuery.cpp:839: DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool) @ 0x1a96cb7a in /workspace/clickhouse

**Comment by alexey-milovidov** [comment]
You did not provide the query.

**Comment by nikitamikhaylov** [comment]
This is a bit strange, because this query doesn't contain function module. 
```
2020.12.17 05:35:47.576023 [ 66 ] {0aafa923-375a-4d36-94ad-b63780de159f} <Debug> executeQuery: (from [::1]:42244, using old parser) SELECT toDateTime(toDateTime(NULL), 10.000100135803223, NULL, NULL), count(-2) FROM test1 WHERE (toDate(p) = '2020-09-01') AND ((sipHash64(toString(toDate(p))) % NULL) = 9223372036854775807)
2020.12.17 05:35:47.585011 [ 66 ] {0aafa923-375a-4d36-94ad-b63780de159f} <Trace> ContextAccess (default): Access granted: SELECT(p) ON default.test1
2020.12.17 05:35:47.589320 [ 66 ] {0aafa923-375a-4d36-94ad-b63780de159f} <Fatal> : Logical error: 'Arguments of 'modulo' have incorrect data types: 'x' of type 'UInt64', '' of type 'Nullable(Nothing)''.
2020.12.17 05:35:47.589858 [ 63 ] {} <Trace> BaseDaemon: Received signal 6
2020.12.17 05:35:47.590246 [ 148 ] {} <Fatal> BaseDaemon: ########################################
2020.12.17 05:35:47.590593 [ 148 ] {} <Fatal> BaseDaemon: (version 20.13.1.5439, build id: 260C17DE928A2720) (from thread 66) (query_id: 0aafa923-375a-4d36-94ad-b63780de159f) Received signal Aborted (6)
```

**Comment by alexey-milovidov** [comment]
`((sipHash64(toString(toDate(p))) % NULL)`

**Comment by alexey-milovidov** [comment]
@nikitamikhaylov You did not provide the table definition.

**Comment by alexey-milovidov** [comment]
Not enough info. Reopen when it will be reproduced next time.
