### ISSUE TITLE
about fill all row

### ISSUE THREAD

**Issue by vegastar002** [ClickHouse/ClickHouse#18184]
select * from
(WITH [10, 12, 23] AS coast , ['a', 'b', 'c'] AS t1 select t1,coast ) array join t1,coast;

┌─t1─┬─coast─┐
│ a  │    10 │
│ b  │    12 │
│ c  │    23 │
└────┴───────┘

I want add d,0 e,0 f,0  at the end, like :
┌─t1─┬─coast─┐
│ a  │    10 │
│ b  │    12 │
│ c  │    23 │
│ d  │    0  │
│ e  │    0  │
│ f  │    0  │
└────┴───────┘

in short, the result must include [a,b,c,d,e,f] in t1 , how to write sql ?

**Comment by alexey-milovidov** [comment]
@vegastar002 I can take your question verbatim and propose to add records with UNION ALL:

```
SELECT *
FROM 
(
    WITH
        [10, 12, 23] AS coast,
        ['a', 'b', 'c'] AS t1
    SELECT
        t1,
        coast
)
ARRAY JOIN
    t1,
    coast
UNION ALL
SELECT *
FROM VALUES('t1 String, coast UInt64', ('d', 0), ('e', 0))

Query id: a7922c64-699e-4529-9c09-999c5fb614c4

┌─t1─┬─coast─┐
│ a  │    10 │
│ b  │    12 │
│ c  │    23 │
└────┴───────┘
┌─t1─┬─coast─┐
│ d  │     0 │
│ e  │     0 │
└────┴───────┘

5 rows in set. Elapsed: 0.003 sec.
```

**Comment by vegastar002** [comment]
left join
