### ISSUE TITLE
MaterializeMySQL: Allow replication of table without primary key if it has secondary one

### ISSUE THREAD

**Issue by imysm** [ClickHouse/ClickHouse#18193]
更新到最新版 20.12.3.3 后 ，我创建一个materializedMySQL库 ，表在同步的过程中 ，可以用count 进行统计。当同步完成后 ，执行 select count(1) 报错 。cannot be materialized, because there is no primary keys

```

2020.12.17 19:37:51.444448 [ 4138 ] {198fccfc-c4b8-4167-9e4c-23bbc66daa4a} <Error> executeQuery: Code: 48, e.displayText() = DB::Exception: The ac.pp_wechatinfo cannot be materialized, because there is no primary keys. (version 20.12.3.3 (official build)) (from [::1]:46280) (in query: select count(1) from wec
hat_event_record;), Stack trace (when copying this message, always include the lines below):

0. DB::MySQLInterpreter::InterpreterCreateImpl::getRewrittenQueries(DB::MySQLParser::ASTCreateQuery const&, DB::Context const&, std::__1::basic_string<char, std::__1
::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xdf10a6d in
 /usr/bin/clickhouse
1. DB::MySQLInterpreter::InterpreterMySQLDDLQuery<DB::MySQLInterpreter::InterpreterCreateImpl>::execute() @ 0xdba14bc in /usr/bin/clickhouse
2. DB::InterpreterExternalDDLQuery::execute() @ 0xdba0507 in /usr/bin/clickhouse
3. ? @ 0xdeec307 in /usr/bin/clickhouse
4. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum,
 bool) @ 0xdeeaedd in /usr/bin/clickhouse
5. ? @ 0xdb4d8c4 in /usr/bin/clickhouse
6. ? @ 0xdb654d8 in /usr/bin/clickhouse
7. DB::commitMetadata(std::__1::function<void ()> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::bas
ic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xdb6bf5e in /usr/bin/clickhouse
8. DB::MaterializeMetadata::transaction(DB::MySQLReplication::Position const&, std::__1::function<void ()> const&) @ 0xdb6c451 in /usr/bin/clickhouse
9. DB::MaterializeMySQLSyncThread::prepareSynchronized(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xdb46939 in /
usr/bin/clickhouse
10. DB::MaterializeMySQLSyncThread::synchronization(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xdb45fba in /usr
/bin/clickhouse
11. ? @ 0xdb64b7a in /usr/bin/clickhouse
12. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x7d1baad in /usr/bin/clickhouse
13. ? @ 0x7d1f5d3 in /usr/bin/clickhouse
14. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
15. __clone @ 0xfe8dd in /usr/lib64/libc-2.17.so

```

**Comment by imysm** [comment]
但是在源Mysql里面，是有主键的 
PRIMARY KEY (`W_ID`)

**Comment by tavplubix** [comment]
Could you please provide output of the following:
```
$ grep -Fa "MaterializeMySQLSyncThread: " /var/log/clickhouse-server/clickhouse-server.log
```
and
```
mysql> show create table ac.pp_wechatinfo;
```

**Comment by imysm** [comment]
Excuese me for so late reply 

> Could you please provide output of the following:
> 
> ```
> $ grep -Fa "MaterializeMySQLSyncThread: " /var/log/clickhouse-server/clickhouse-server.log
> ```
`
2020.12.17 18:33:23.296486 [ 4086 ] {} <Error> MaterializeMySQLSyncThread: Code: 48, e.displayText() = DB::Exception: The ac.pp_wechatinfo cannot be materialized, because there is no primary keys., Stack trace (when copying this message, always include the lines below):
2020.12.17 18:33:23.297867 [ 4086 ] {} <Error> MaterializeMySQLSyncThread: Code: 48, e.displayText() = DB::Exception: The ac.pp_wechatinfo cannot be materialized, because there is no primary keys., Stack trace (when copying this message, always include the lines below):
`
> and
> 
> ```
> mysql> show create table ac.pp_wechatinfo;
> ```


`
CREATE TABLE `pp_wechatinfo` (
  `id` bigint(20) DEFAULT NULL,
  `aid` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `uid` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL ,
  `oid` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL ,
  `fid` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `type` tinyint(1) DEFAULT NULL ,
  `e_time` timestamp NULL DEFAULT NULL ,
  `cate` tinyint(1) DEFAULT NULL ,
  `can` tinyint(1) DEFAULT NULL ,
  `create_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `template_id` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  KEY `job_idx` (`e_time`,`aid`,`uid`) USING BTREE,
  KEY `del_idx` (`aid`,`ud`,`fid`,`template_id`,`create_date`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci 
`

**Comment by tavplubix** [comment]
>> `mysql> show create table ac.pp_wechatinfo;`
> ```
> CREATE TABLE pp_wechatinfo 
> (
>   id bigint(20) DEFAULT NULL,
>   aid varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
>   uid varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
>   oid varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
>   fid varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
>   typetiny int(1) DEFAULT NULL,
>   e_time timestamp NULL DEFAULT NULL, 
>   catetiny int(1) DEFAULT NULL, 
>   cantiny int(1) DEFAULT NULL, 
>   create_date timestamp NULL DEFAULT CURRENT_TIMESTAMP, 
>   template_id varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL, 
>   KEY job_idx (e_time, aid, uid) USING BTREE, 
>   KEY del_idx (aid, uid, fid, template_id, create_date) USING BTREE 
> ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
> ```

As we can see from the CREATE query, table `pp_wechatinfo` does not have **primary** key. That's why it cannot be replicated to ClickHouse. 

However, I've checked the sources of `MaterializeMySQL` and it looks like we can allow replication of table without primary key if it has some secondary key and we can use it as ORDER BY key. It should not break something, but I'm not completely sure about it.
