### ISSUE TITLE
Lowering the default for maximum of parts to be merged at once, or make it configurable

### ISSUE THREAD

**Issue by dqminh** [ClickHouse/ClickHouse#1820]
We have this case recently

```
:) select num_parts, formatReadableSize(total_size_bytes_compressed) from system.merges where num_parts > 100;

SELECT
    num_parts,
    formatReadableSize(total_size_bytes_compressed)
FROM system.merges
WHERE num_parts > 100

┌─num_parts─┬─formatReadableSize(total_size_bytes_compressed)─┐
│      1001 │ 49.31 GiB                                       │
└───────────┴─────────────────────────────────────────────────┘
```

where we hits the hard-coded limit of number of parts being merged at once. Merging 1000 parts at once is rarely a good idea though. Can we lower this, or make it configurable somehow ?

**Comment by bobrik** [comment]
Memory usage of merges on 3 machines that decided to do this:

![image](https://user-images.githubusercontent.com/89186/35348446-f3499344-00ec-11e8-98e5-7070be0887f1.png)

**Comment by bobrik** [comment]
This may be related to #1821, as it happened not long after.

**Comment by alexey-milovidov** [comment]
Just add to `MergeTreeSettings` and pass into `SimpleMergeSelector`.
