### ISSUE TITLE
clickhouse provide centos arm64 rpm download?

### ISSUE THREAD

**Issue by melin** [ClickHouse/ClickHouse#18220]
clickhouse provide centos arm64 rpm download?

**Comment by den-crane** [comment]
No arm64 packages.

**Comment by alexey-milovidov** [comment]
@melin You can install ClickHouse without rpm packages (from binary download):
https://clickhouse.tech/docs/en/getting-started/install/#from-binaries-non-linux

Run
```
sudo ./clickhouse install
```
