### ISSUE TITLE
Tables with DateTime64 don't have min/max_time set?

### ISSUE THREAD

**Issue by mzealey** [ClickHouse/ClickHouse#18244]
**Describe the bug**

I have a table like:

```
CREATE TABLE test (
    time DateTime64(3)
    ...
) ENGINE = MergeTree()
PARTITION BY toStartOfInterval(time, INTERVAL 1 HOUR)
...
```

But when I search in `system.parts` it does not appear to have the `min/max` columns appropriately set?

```
partition:                             2020-06-01 01:00:00
min_date:                              1970-01-01
max_date:                              1970-01-01
min_time:                              1970-01-01 00:00:00
max_time:                              1970-01-01 00:00:00
```

I assume that if these were correctly set, doing a `select toStartOfInterval(time, interval 1 day), count()` type query would be pretty instant rather than trying to scan everything? I am guessing this is due to the `DateTime64` type in use?

Clickhouse 20.11.3.3

**Comment by den-crane** [comment]
They are just informational columns.
It does not related to partition pruning/elimination.

**Comment by alexey-milovidov** [comment]
@Enmk why not?
