### ISSUE TITLE
Logs in `checkSource` not consistent with code

### ISSUE THREAD

**Issue by taiyang-li** [ClickHouse/ClickHouse#18240]
**Describe the bug**
See the code in `Pipe.cpp`. The logic of `if` not consistent with the logs below.  Can `checkSource` be passed when `source.getOutputs().size() == 2` ? 
```
static void checkSource(const IProcessor & source)
{
    ......
    if (source.getOutputs().size() > 1)
        throw Exception("Source for pipe should have single or two outputs, but " + source.getName() + " has " +
                        toString(source.getOutputs().size()) + " outputs.", ErrorCodes::LOGICAL_ERROR);
}
```

**Comment by filimonov** [comment]
Condition is correct, exception message is wrong. See https://github.com/ClickHouse/ClickHouse/commit/458c7f516deb834bcb6775cdec732b404e793ce0
