### ISSUE TITLE
ON CLUSTER query gives: DB::Exception: Cannot provide query execution status

### ISSUE THREAD

**Issue by milonas115** [ClickHouse/ClickHouse#18247]
I'm getting the following error very randomly about a dozen times a day:

Code: 341, e.displayText() = DB::Exception: Cannot provide query execution status. The query's node /clickhouse/task_queue/ddl/query-0000269928 has been deleted by the cleaner since it was finished (or its lifetime is expired) (version 20.10.3.30 (official build))

The error occurs on the following two query types: Truncate / ALTER TABLE

I can't 100% repoduce as it happens randomly, but last time I had it happen, I was running about a dozen ALTER TABLE UPDATE queries (in series), and it would fail sometimes on query 1, sometimes on query 8 etc. 100% random.

Is there some sort of setting that the cleaner uses to delete the queries node that can be adjusted or is this a bug?

**Comment by SaltTan** [comment]
The default DDL cleaner parameters are:
```
<yandex>
<distributed_ddl>
    <max_tasks_in_queue>1000</max_tasks_in_queue>
    <task_max_lifetime>604800</task_max_lifetime>
    <cleanup_delay_period>60</cleanup_delay_period>
</distributed_ddl>
</yandex>
```

**Comment by ghuname** [comment]
ClickHouse client version 21.1.2.15 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 21.1.2 revision 54443.

I have the same problem. I have just created a ReplicatedCollapsingMergeTree on cluster command. Than I created distributed table on cluster.
Now I dropped distributed table on cluster.
And finally I dropped ReplicatedCollapsingMergeTree on cluster that resulted in error:
```
:) drop table default.cm_upstream_quality_shard on cluster grabber;

DROP TABLE default.cm_upstream_quality_shard ON CLUSTER grabber

Query id: f41d799d-34d3-4a37-8722-4610d59cee54


Received exception from server (version 21.1.2):
Code: 341. DB::Exception: Received from localhost:9000. DB::Exception: Cannot provide query execution status. The query's node /clickhouse/task_queue/ddl/query-0000000813 has been deleted by the cleaner since it was finished (or its lifetime is expired).

0 rows in set. Elapsed: 0.023 sec.
```

End result is, all tables are dropped, but I would like to know why this error is happening at the first place, because we are experiencing such on cluster errors in different situations, like https://github.com/ClickHouse/ClickHouse/issues/19319#issue-790045094.

**Comment by SaltTan** [comment]
@ghuname How many DDL tasks are stored in ZooKeeper?
```
SELECT count()
FROM system.zookeeper
WHERE path = '/clickhouse/task_queue/ddl/'

SELECT
    ctime,
    name,
    value
FROM system.zookeeper
WHERE path = '/clickhouse/task_queue/ddl/'
ORDER BY ctime ASC
LIMIT 3

SELECT
    ctime,
    name,
    value
FROM system.zookeeper
WHERE path = '/clickhouse/task_queue/ddl/'
ORDER BY ctime DESC
LIMIT 3
```

**Comment by ghuname** [comment]
SELECT count()
FROM system.zookeeper
WHERE path = '/clickhouse/task_queue/ddl/'

Node 1 and 2 (shard1) 124, node 3 and 4 (shard2) 1

SELECT
    ctime,
    name,
    value
FROM system.zookeeper
WHERE path = '/clickhouse/task_queue/ddl/'
ORDER BY ctime ASC
LIMIT 3

ctime              |name            |value                                                                                                                                                                                                                                                          |
-------------------|----------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
2021-01-21 02:08:22|query-0000000692|version: 1¶query: DROP TABLE IF EXISTS IPDR.UsChIfName_join ON CLUSTER grabber¶hosts: ['10%2E241%2E129%2E170:9000','10%2E241%2E129%2E171:9000','10%2E241%2E129%2E172:9000','10%2E241%2E129%2E173:9000']¶initiator: node3:9000¶       |
2021-01-22 02:08:51|query-0000000694|version: 1¶query: DROP TABLE IF EXISTS IPDR.UsChIfName_join ON CLUSTER grabber¶hosts: ['10%2E241%2E129%2E170:9000','10%2E241%2E129%2E171:9000','10%2E241%2E129%2E172:9000','10%2E241%2E129%2E173:9000']¶initiator: node3:9000¶       |
2021-01-22 09:28:26|query-0000000697|version: 1¶query: CREATE TABLE Analytics.tmp_ap_test UUID 'c6be9db9-23e6-452a-9cea-0d26cf6de66a' ON CLUSTER grabber (`crm_cmMacAddress` String) ENGINE = Log¶hosts: ['10%2E241%2E129%2E170:9000','10%2E241%2E129%2E171:9000','10%2E241%2E129%2E172:9000','10%2E|

SELECT
    ctime,
    name,
    value
FROM system.zookeeper
WHERE path = '/clickhouse/task_queue/ddl/'
ORDER BY ctime DESC
LIMIT 3


ctime              |name            |value                                                                                                                                                                                                                                                          |
-------------------|----------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
2021-01-28 02:07:31|query-0000000838|version: 1¶query: DROP TABLE IF EXISTS ref_tables.CmtsCmUsChIfName_join ON CLUSTER grabber¶hosts: ['10%2E241%2E129%2E170:9000','10%2E241%2E129%2E171:9000','10%2E241%2E129%2E172:9000','10%2E241%2E129%2E173:9000']¶initiator: node3:|
2021-01-28 02:07:31|query-0000000837|version: 1¶query: CREATE TABLE ref_tables.CmtsCmUsChIfIndex_join UUID '15567a6b-16ed-4a9b-8818-65e0ad8c56e7' ON CLUSTER grabber ENGINE = Join(ANY, LEFT, CmtsCmUsChIfIndex) AS SELECT DISTINCT concat(CmtsHostName, '/', toString(CmtsCmUsChIfIndex)) AS CmtsCm|
2021-01-28 02:07:31|query-0000000839|version: 1¶query: CREATE TABLE ref_tables.CmtsCmUsChIfName_join UUID '23392819-9e1f-4e42-a06b-2527baf63bee' ON CLUSTER grabber ENGINE = Join(ANY, LEFT, UsChIfName) AS SELECT DISTINCT concat(CmtsHostName, '/', UsChIfName) AS UsChIfName, toString(CmtsCmUsCh|

**Comment by ghuname** [comment]
@SaltTan Can you please check my answer above?

**Comment by SaltTan** [comment]
> SELECT count()
> FROM system.zookeeper
> WHERE path = '/clickhouse/task_queue/ddl/'
> 
> Node 1 and 2 (shard1) 124, node 3 and 4 (shard2) 1

I don't understand this.
I would expect all nodes to look at the same znode and see the same number of the tasks.
Can you see your DROP TABLE in the list?

**Comment by ghuname** [comment]
@SaltTan This is situation right now:

![image](https://user-images.githubusercontent.com/15207713/106427663-08af1380-6468-11eb-94ae-e6649d18331d.png)


Now all 4 number are the same = 113. They used to be (left to right, top to bottom) 124, 124, 1, 1 (not the same), when I reported the istuation last time.
The first row on the picture are two nodes that form shard1, bottom row are nodes that form shard2.
Zookeeper is installed on each of the four nodes.


```
SELECT count()
FROM system.zookeeper
WHERE (path = '/clickhouse/task_queue/ddl/') AND (value LIKE '%DROP%')

Query id: fa2b75df-9282-44f4-91e9-8fb80d83f5e3

┌─count()─┐
│      58 │
└─────────┘

```

```
SELECT
    min(ctime),
    max(ctime)
FROM system.zookeeper
WHERE (path = '/clickhouse/task_queue/ddl/') AND (value LIKE '%DROP%')

Query id: 2b0ea5f2-a741-4fdb-9ac2-84717cd3359b

┌──────────min(ctime)─┬──────────max(ctime)─┐
│ 2021-01-25 02:07:19 │ 2021-02-01 02:07:38 │
└─────────────────────┴─────────────────────┘

```

**Comment by SaltTan** [comment]
Can you reproduce the issue?

**Comment by millin** [comment]
Looks like this issue happened for me only with db engine Atomic

**Comment by ghuname** [comment]
> Can you reproduce the issue?

I tried to reproduce it by creation of the table with ReplicatedCollapsingMergeTree engine, insert some rows and drop it, all the time using on cluster commands.
After repeating the process for dozen times,  I had no success to produce the error.

@SaltTan What was your idea in order to trace this type of error?

**Comment by SaltTan** [comment]
I would check the logs on all nodes to see what DDLWorker threads were doing.

**Comment by meilin-shi** [comment]
> The default DDL cleaner parameters are:
> 
> ```
> <yandex>
> <distributed_ddl>
>     <max_tasks_in_queue>1000</max_tasks_in_queue>
>     <task_max_lifetime>604800</task_max_lifetime>
>     <cleanup_delay_period>60</cleanup_delay_period>
> </distributed_ddl>
> </yandex>
> ```

I face the same problem and after add the parameters above, DDL statement works fine.

**Comment by cainiaodidi** [comment]
Does this problem be solved? If yes, how to solve it?

**Comment by tavplubix** [comment]
> Does this problem be solved? If yes, how to solve it?

@cainiaodidi, can you reproduce the issue? What version of ClickHouse do you use? How many ON CLUSTER queries do you run?

**Comment by cainiaodidi** [comment]
> > Does this problem be solved? If yes, how to solve it?
> 
> @cainiaodidi, can you reproduce the issue? What version of ClickHouse do you use? How many ON CLUSTER queries do you run?

```shell
Received exception from server (version 21.11.5):
Code: 159. DB::Exception: Received from beidouuseranalysisclickhouse.proxy.ck.qiyi.database:9068. DB::Exception: Watching task /clickhouse/task_queue/ddl/query-0000000004 is executing longer than distributed_ddl_task_timeout (=180) seconds. There are 40 unfinished hosts (0 of them are currently active), they are going to execute the query in background. (TIMEOUT_EXCEEDED)
```
60 queries

**Comment by tavplubix** [comment]
> 60 queries

60 queries per second? per hour? per day? 60 queries at all? How to reproduce the issue?

**Comment by cainiaodidi** [comment]
> > 60 queries
> 
> 60 queries per second? per hour? per day? 60 queries at all? How to reproduce the issue?

I just submit a create table query using `on cluster xxx` on client, and then it raises an error as above.

**Comment by tavplubix** [comment]
> and then it raises an error as above

Which one? `Watching task ... is executing longer than distributed_ddl_task_timeout` from your comment or `Cannot provide query execution status` from issue description?

**Comment by cainiaodidi** [comment]
> > and then it raises an error as above
> 
> Which one? `Watching task ... is executing longer than distributed_ddl_task_timeout` from your comment or `Cannot provide query execution status` from issue description?

It's `Watching task ... is executing longer than distributed_ddl_task_timeout`. Sorry, are these two problems different errors?

**Comment by tavplubix** [comment]
Yes, these errors are completely different. `Watching task ... is executing longer than distributed_ddl_task_timeout` means that `distributed_ddl_task_timeout` exceeded, but query is not finished on some hosts (maybe because some hosts are unavailable or busy with previous `ON CLUSTER` queries) and query will be executed asynchronously. 

In your case (`query-0000000004 ... There are 40 unfinished hosts (0 of them are currently active)`) it probably caused by some misconfiguration. Check your cluster config, server logs and `system.distributed_ddl_queue` table.

**Comment by solon-liu** [comment]
Is this a bug?
In which version was it repaired?

I have encountered this error many times in version 20.12.8.
I tried to adjust the parameters, but I still couldn't avoid the error.
After I upgraded the version to 21.12.4, this error did not appear again.
