### ISSUE TITLE
Fetch key from dictionary

### ISSUE THREAD

**Issue by mzealey** [ClickHouse/ClickHouse#18241]
**Use case**
I'm using `ip_trie` on maxmind geoip databases. Given an IP address I want to find out what key was used (ie what network the IP comes under). But it seems it is not possible to look up the key field when using `dictGet`?

```
        <layout>
            <ip_trie/>
        </layout>
        <structure>
            <key>
                <attribute>
                    <name>network</name>
                    <type>String</type>
                </attribute>
            </key>
            <attribute>
                <name>geoname_id</name>
                <type>UInt32</type>
                <null_value>0</null_value>
            </attribute>
...
```

```
clickhouse :) select dictGet('geoip_city_blocks_ipv4', 'geoname_id', tuple(toUInt32(toIPv4('1.1.1.1')))) ;

┌─dictGet('geoip_city_blocks_ipv4', 'geoname_id', tuple(toUInt32(toIPv4('1.1.1.1'))))─┐
│                                                                             2077456 │
└─────────────────────────────────────────────────────────────────────────────────────┘

clickhouse :) select dictGet('geoip_city_blocks_ipv4', 'network', tuple(toUInt32(toIPv4('1.1.1.1')))) ;

Received exception from server (version 20.11.3):
Code: 36. DB::Exception: Received from localhost:9000. DB::Exception: No such attribute 'network': While processing dictGet('geoip_city_blocks_ipv4', 'network', tuple(toUInt32(toIPv4('1.1.1.1')))). 
```

**Comment by alexey-milovidov** [comment]
Workaround: duplicate network in another attribute.

I'm not sure if it's possible to implement this feature for free, because networks may be split in parts in internal data structure.

**Comment by mzealey** [comment]
Yeah I figured we could duplicate. I don't know the code, but one way to work around easily may be allow the `<key>` attributes to also be specified as `<attribute>` so effectively the same as the duplicating workaround but without having to do it in the base data?

**Comment by alexey-milovidov** [comment]
That's a good idea!

**Comment by filimonov** [comment]
`dictHas` doesn't help?

**Comment by mzealey** [comment]
no because it would say that `a.b.c.d` existed in the dict (which i already know) but not what subnet matched eg `a.b.c.0/24`

**Comment by SaltTan** [comment]
You don't have to duplicate in the base data if you use `expression`
```
        <structure>
            <key>
                <attribute>
                    <name>network</name>
                    <type>String</type>
                </attribute>
            </key>
            <attribute>
                <name>network_desc</name>
                <expression>network</expression>
                <type>String</type>
                <null_value></null_value>
            </attribute>
```

**Comment by vdimir** [comment]
> You don't have to duplicate in the base data if you use `expression`

Seems now it doesn't work with `file` source (one of common usecase)
https://github.com/ClickHouse/ClickHouse/blob/51481c9c5fa5235d2afcfdc98470dfc3fdb86cae/src/Dictionaries/FileDictionarySource.cpp#L85

But it works with `clickhouse` source.

**Comment by mzealey** [comment]
(also a note; i don't believe there is any documentation around `<expression>`)

**Comment by SaltTan** [comment]
> (also a note; i don't believe there is any documentation around <expression>)

There is https://clickhouse.tech/docs/en/sql-reference/dictionaries/external-dictionaries/external-dicts-dict-structure/#ext_dict_structure-attributes
