### ISSUE TITLE
Docs: `SHOW PROCESSLIST` not actually identical to `SELECT * FROM system.processes`

### ISSUE THREAD

**Issue by cincodenada** [ClickHouse/ClickHouse#1825]
According to the docs:

>This query is identical to: `SELECT * FROM system.processes [INTO OUTFILE filename] [FORMAT format]`.

This is inaccurate, as `SELECT * FROM system.processes` will include itself as an entry in the processlist, so you will always get at least one process (`SELECT * FROM system.processes` itself). This is reflected at the top ("other than SHOW PROCESSLIST queries"), but the difference should be noted here, perhaps something like:

>This query is nearly identical to: `SELECT * FROM system.processes [INTO OUTFILE filename] [FORMAT format]`, except that as noted above it will not show itself, which the `SELECT` form does.

I discovered this when switching from parsing `SHOW PROCESSLIST` to `SELECT memory_usage FROM system.processes`, and found an extra 0 in the list, which turned out to be the `SELECT memory_usage FROM system.processes` query itself, and I had to account for that.

**Comment by blinkov** [comment]
@BayoNet I don't see this in your internal backlog

**Comment by BayoNet** [comment]
Is this documentation correct?
https://clickhouse.yandex/docs/en/query_language/show/#show-processlist

**Comment by alexey-milovidov** [comment]
Now Ok:

> Outputs the content of the system.processes table, that contains a list of queries that is being processed at the moment, **excepting SHOW PROCESSLIST queries**.
