### ISSUE TITLE
what's means this error

### ISSUE THREAD

**Issue by intfish123** [ClickHouse/ClickHouse#18252]
<Error> system.query_log: Cannot quickly remove directory /data1/clickhouse/data_default/clickhouse/data/system/query_log/delete_tmp_202007_117486_117872_7 by removing files; fallback to recursive removal. Reason: Code: 458, e.displayText() = DB::ErrnoException: Cannot unlink file /data1/clickhouse/data_default/clickhouse/data/system/query_log/delete_tmp_202007_117486_117872_7/checksums.txt, errno: 2, strerror: No such file or directory (version 20.3.4.10 (official build))
2020.12.20 11:10:11.148234 [ 32676 ] {} <Error> void DB::BackgroundProcessingPool::threadFunction(): Code: 87, e.displayText() = DB::ErrnoException: Cannot seek through file /data1/clickhouse/data_default/clickhouse/data/system/query_log/202007_117489_117489_0/query_start_time.bin, errno: 22, strerror: Invalid argument: (while reading column query_start_time): (while reading from part /data1/clickhouse/data_default/clickhouse/data/system/query_log/202007_117489_117489_0/ from mark 0 with max_rows_to_read = 1024), Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x102e0d8c in ?
1. DB::ErrnoException::ErrnoException(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int, std::__1::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > const&) @ 0x8f31b77 in ?
2. DB::throwFromErrnoWithPath(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int) @ 0x8f2fac6 in ?
3. DB::ReadBufferFromFileDescriptor::seek(long, int) @ 0x8f5c998 in ?
4. DB::CompressedReadBufferFromFile::seek(unsigned long, unsigned long) @ 0xccf67ae in ?
5. DB::MergeTreeReaderStream::seekToMark(unsigned long) @ 0xd88cd48 in ?
6. ? @ 0xd88e177 in ?
7. DB::IDataType::deserializeBinaryBulkWithMultipleStreams(DB::IColumn&, unsigned long, DB::IDataType::DeserializeBinaryBulkSettings&, std::__1::shared_ptr<DB::IDataType::DeserializeBinaryBulkState>&) const @ 0x9156a29 in ?
8. DB::MergeTreeReaderWide::readData(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::IDataType const&, DB::IColumn&, unsigned long, bool, unsigned long, bool) @ 0xd88e426 in ?
9. DB::MergeTreeReaderWide::readRows(unsigned long, bool, unsigned long, std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >&) @ 0xd88f601 in ?
10. DB::MergeTreeSequentialBlockInputStream::readImpl() @ 0xd8b7b11 in ?
11. DB::IBlockInputStream::read() @ 0xccd503f in ?
12. DB::ExpressionBlockInputStream::readImpl() @ 0xd0ec4f6 in ?
13. DB::IBlockInputStream::read() @ 0xccd503f in ?
14. DB::MaterializingBlockInputStream::readImpl() @ 0xcf4a2a3 in ?
15. DB::IBlockInputStream::read() @ 0xccd503f in ?
16. DB::MergingSortedBlockInputStream::init(std::__1::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn> > >&) @ 0xd12f350 in ?
17. DB::MergingSortedBlockInputStream::readImpl() @ 0xd1300fe in ?
18. DB::IBlockInputStream::read() @ 0xccd503f in ?
19. DB::MergeTreeDataMergerMutator::mergePartsToTemporaryPart(DB::FutureMergedMutatedPart const&, DB::MergeListEntry&, DB::TableStructureReadLockHolder&, long, std::__1::unique_ptr<DB::IReservation, std::__1::default_delete<DB::IReservation> > const&, bool, bool) @ 0xd77c32c in ?
20. DB::StorageMergeTree::merge(bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) @ 0xd587ebc in ?
21. DB::StorageMergeTree::mergeMutateTask() @ 0xd58ecfc in ?
22. DB::BackgroundProcessingPool::threadFunction() @ 0xd6f72cb in ?
23. ? @ 0xd6f7c90 in ?
24. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x8f50b4b in ?
25. ? @ 0x8f4f00f in ?
26. start_thread @ 0x7e25 in /usr/lib64/libpthread-2.17.so
27. clone @ 0xf834d in /usr/lib64/libc-2.17.so
 (version 20.3.4.10 (official build))

**Comment by den-crane** [comment]
You should upgrade CH to 20.3.21.2
