### ISSUE TITLE
test.clickhouse.tech contains outdated documentation

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#18283]
Figure out how to remove it.

**Comment by splichy** [comment]
at least we can access older documentation here:
https://test.clickhouse.tech/docs/v19.16/en/

Anyway listBox for switching to older documentation is missing on https://clickhouse.tech/docs/ e.g. https://clickhouse.tech/docs/v20.8/en/ will redirect you back to https://clickhouse.tech/docs/en/

**Comment by alexey-milovidov** [comment]
@splichy Version switcher has been broken long time ago and it's not easy to make it work again.

**Comment by splichy** [comment]
PS: listBox is available on some pages, like: https://clickhouse.tech/docs/en/interfaces/
but when you click it will redirect you to https://clickhouse.tech/docs/en/

**Comment by splichy** [comment]
OK, that's pitty :/
