### ISSUE TITLE
Error when selecting profile in http requests

### ISSUE THREAD

**Issue by chbuescher** [ClickHouse/ClickHouse#18305]
I have defined a settings profile "web".
Up to clickhouse version 20.6 i could reference it in http queries:

curl 'http://localhost:8123/?query=SELECT%201'
1

In version 20.8 and later this doesn't work any more:

curl 'http://localhost:8123/?query=SELECT%201&profile=web'
Code: 115, e.displayText() = DB::Exception: Unknown setting profile (version 20.8.9.6 (official build))

According to the recent HTTP Interface documentation the "old" behaviour is still valid:
"You can also use the URL parameters to specify any settings for processing a single query or entire profiles of settings. Example:http://localhost:8123/?profile=web&max_rows_to_read=1000000000&query=SELECT+1"

**Comment by akuzm** [comment]
Duplicate https://github.com/ClickHouse/ClickHouse/issues/18300
