### ISSUE TITLE
Can't use settings profile in http request

### ISSUE THREAD

**Issue by chbuescher** [ClickHouse/ClickHouse#18300]
I defined a web profile in users.xml as described here: https://clickhouse.tech/docs/en/operations/settings/settings-profiles/
Up to version 20.6 i could use this profile in http requests:
curl 'http://localhost:8123/?query=SELECT%201&profile=web'
1

In version 20.8 an later this doesn't work any more:
curl 'http://localhost:8123/?query=SELECT%201&profile=web'
Code: 115, e.displayText() = DB::Exception: Unknown setting profile (version 20.8.9.6 (official build))

The recent documentation still references the "old" behaviour:
https://clickhouse.tech/docs/en/interfaces/http/
"You can also use the URL parameters to specify any settings for processing a single query or entire profiles of settings. Example:http://localhost:8123/?profile=web&max_rows_to_read=1000000000&query=SELECT+1"

**Comment by akuzm** [comment]
Fixed here https://github.com/ClickHouse/ClickHouse/pull/18167
