### ISSUE TITLE
Json data from mysql have space, how can I do?

### ISSUE THREAD

**Issue by cifaz** [ClickHouse/ClickHouse#18316]
Json data from mysql have space, how can I do?

The step:
`
CREATE TABLE training_org_manage
ENGINE = MergeTree
ORDER BY id AS
SELECT *
FROM mysql('192.168.18.21:6033   ', 'tb_manager_test', 'training_org_manage', 'root', '');
`

The table have json data type; and data like 
`
{"areaList": [{"cityId": "125104", "districtId": "125104107", "provinceId": "125"}]}
`

How can I handle the space in clickhouse. thanks!

**Comment by den-crane** [comment]
using JSONExtract functionns?

https://clickhouse.tech/docs/en/sql-reference/functions/json-functions/#jsonextractkeysandvaluesjson-indices-or-keys-value-type

SELECT JSONExtractKeysAndValues(JSONExtractArrayRaw(j, 'areaList')[1], 'String') AS r
FROM
(
    SELECT '{"areaList": [{"cityId": "125104", "districtId": "125104107", "provinceId": "125"}]}' AS j
)

┌─r─────────────────────────────────────────────────────────────────────┐
│ [('cityId','125104'),('districtId','125104107'),('provinceId','125')] │
└───────────────────────────────────────────────────────────────────────┘

**Comment by cifaz** [comment]
> using JSONExtract functionns?
> 
> https://clickhouse.tech/docs/en/sql-reference/functions/json-functions/#jsonextractkeysandvaluesjson-indices-or-keys-value-type
> 
> ```sql
> SELECT JSONExtractKeysAndValues(JSONExtractArrayRaw(j, 'areaList')[1], 'String') AS r
> FROM
> (
>     SELECT '{"areaList": [{"cityId": "125104", "districtId": "125104107", "provinceId": "125"}]}' AS j
> )
> 
> ┌─r─────────────────────────────────────────────────────────────────────┐
> │ [('cityId','125104'),('districtId','125104107'),('provinceId','125')] │
> └───────────────────────────────────────────────────────────────────────┘
> ```

Thank you!

But can not relove essential issues! 
The whole josn data is: 
`
{"areaList": [{"cityId": "125104", "districtId": "125104107", "provinceId": "125"}], "subjectList": [{"subjectCode": "T03T01"}, {"subjectCode": "T03T01"}, {"subjectCode": "T03T01"}], "industryList": [{"industryCode": "100100100104"}, {"industryCode": "100100100109"}]}
`
or more data

I want to resolve muti level json data and resolve the json data when sync mysql to clickhouse;

**Comment by cifaz** [comment]
I want to query data by sql: 
`
SELECT
	id,
	org_name,
	visitParamExtractString(ext_json, 'cityId')
FROM
	training_org_manage manage 
WHERE
	is_delete = 0 
	and visitParamExtractString(ext_json, 'cityId') = '125104'
`

**Comment by den-crane** [comment]
```sql

SELECT visitParamExtractString(j, 'cityId') AS x
FROM
(
    SELECT replace(j, ': ', ':') AS j
    FROM
    (
        SELECT '{"areaList": [{"cityId": "125104", "districtId": "125104107", "provinceId": "125"}], "subjectList": [{"subjectCode": "T03T01"}, {"subjectCode": "T03T01"}, {"subjectCode": "T03T01"}], "industryList": [{"industryCode": "100100100104"}, {"industryCode": "100100100109"}]}' AS j
    )
)

Query id: 56e94300-0a44-424f-b241-26471ebd494e

┌─x──────┐
│ 125104 │
└────────┘

```

**Comment by cifaz** [comment]
> ```sql
> SELECT visitParamExtractString(j, 'cityId') AS x
> FROM
> (
>     SELECT replace(j, ': ', ':') AS j
>     FROM
>     (
>         SELECT '{"areaList": [{"cityId": "125104", "districtId": "125104107", "provinceId": "125"}], "subjectList": [{"subjectCode": "T03T01"}, {"subjectCode": "T03T01"}, {"subjectCode": "T03T01"}], "industryList": [{"industryCode": "100100100104"}, {"industryCode": "100100100109"}]}' AS j
>     )
> )
> 
> Query id: 56e94300-0a44-424f-b241-26471ebd494e
> 
> ┌─x──────┐
> │ 125104 │
> └────────┘
> ```

Thank you a lot;
I replace space when import data from mysql:
`
CREATE TABLE training_org_manage
ENGINE = MergeTree
ORDER BY id AS
SELECT 
id,org_id,org_name, `other_fields...`, replaceRegexpAll(ext_json,' ','') as ext_json
FROM mysql('127.0.0.1:6033', 'tb_manager_test', 'training_org_manage', 'root', '11');
`
