### ISSUE TITLE
DDL are not working and hanging: There is no a local address in host list

### ISSUE THREAD

**Issue by yonj1e** [ClickHouse/ClickHouse#18341]
ClickHouse server version 20.8.9.6 (official build)

```
CREATE TABLE IF NOT EXISTS t_local ON CLUSTER cluster_2_replica
(
    `ID` String,
    `CreateTime` DateTime DEFAULT now()
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{layer}-{shard}/t_local', '{replica}')
PARTITION BY toYYYYMMDD(CreateTime)
ORDER BY CreateTime


Received exception from server (version 20.8.9):
Code: 159. DB::Exception: Received from localhost:9000. DB::Exception: Watching task /clickhouse/task_queue/ddl/query-0000000000 is executing longer than distributed_ddl_task_timeout (=180) seconds. There are 4 unfinished hosts (0 of them are currently active), they are going to execute the query in background. 

0 rows in set. Elapsed: 180.192 sec.
```
```
[zk: localhost:2181(CONNECTED) 8] get /clickhouse/task_queue/ddl/query-0000000000
version: 1
query: CREATE TABLE IF NOT EXISTS default.t_local ON CLUSTER cluster_2_replica (`ID` String, `CreateTime` DateTime DEFAULT now()) ENGINE = ReplicatedMergeTree(\'/clickhouse/tables/{layer}-{shard}/t_local\', \'{replica}\') PARTITION BY toYYYYMMDD(CreateTime) ORDER BY CreateTime
hosts: ['10%2E111%2E99%2E78:19001','10%2E111%2E99%2E78:19004','10%2E111%2E99%2E78:19007','10%2E111%2E99%2E78:19010']
initiator: clickhouse1:9000

[zk: localhost:2181(CONNECTED) 9] ls /clickhouse/task_queue/ddl/query-0000000000/active 
[]
[zk: localhost:2181(CONNECTED) 10] ls /clickhouse/task_queue/ddl/query-0000000000/finished 
[]
```
Neither Active nor finished had records
And then I tested ReplicatedMergeTree
```
replica1
CREATE TABLE IF NOT EXISTS t_local
(
    `ID` String,
    `CreateTime` DateTime DEFAULT now()
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{layer}-{shard}/t_local', '{replica}')
PARTITION BY toYYYYMMDD(CreateTime)
ORDER BY CreateTime

Ok.

0 rows in set. Elapsed: 0.218 sec.

replica2
CREATE TABLE IF NOT EXISTS t_local
(
    `ID` String,
    `CreateTime` DateTime DEFAULT now()
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{layer}-{shard}/t_local', '{replica}')
PARTITION BY toYYYYMMDD(CreateTime)
ORDER BY CreateTime

Ok.

0 rows in set. Elapsed: 0.366 sec. 

clickhouse1_replica :) insert into t_local values('a000', now());

INSERT INTO t_local VALUES

Ok.

1 rows in set. Elapsed: 0.049 sec. 

clickhouse1_replica :) select * from t_local;

SELECT *
FROM t_local

┌─ID───┬──────────CreateTime─┐
│ a000 │ 2020-12-22 03:22:21 │
└──────┴─────────────────────┘

1 rows in set. Elapsed: 0.006 sec.

replica1
SELECT *
FROM t_local

┌─ID───┬──────────CreateTime─┐
│ a000 │ 2020-12-22 03:22:21 │
└──────┴─────────────────────┘

1 rows in set. Elapsed: 0.006 sec. 
```
The data can be synchronized properly
How can I troubleshoot this problem

**Comment by yonj1e** [comment]
DDLQueryStatusInputStream
2020.12.22 06:28:41.496324 [ 36 ] {} <Debug> DDLWorker: Will not execute task query-0000000003: There is no a local address in host list
2020.12.22 06:28:41.496392 [ 36 ] {} <Debug> DDLWorker: Waiting a watch

**Comment by filimonov** [comment]
I guess it's hostname as configured on node (check `hostname --fqdn`) vs hostnames as configured in clickhouse configuration (`<remote_servers>`). 

Were you able to fix the issue? If you do - please add a commend of what was wrong / what fix was applied, and kindly close the issue

**Comment by yonj1e** [comment]
> I guess it's hostname as configured on node (check `hostname --fqdn`) vs hostnames as configured in clickhouse configuration (`<remote_servers>`).
> 
> Were you able to fix the issue? If you do - please add a commend of what was wrong / what fix was applied, and kindly close the issue

You are right, the node host name(/etc/hosts) does not match the ClickHouse configuration(remote_servers) host name

**Comment by 1212mohamedtaha** [comment]
I have the same issue. and I checked that hostname --fqdn is the same as the host name specified in <remote_servers>.
The same issue (There is no a local address in host list) exists

**Comment by LeftoversTodayAppAdmin** [comment]
Im running into the same issue now. I have /etc/hosts on each machine with IPs and FQDNs, I am seeing that the server is connecting to the keeper but it does not execute the query.

DDLWorker: Will not execute task query-0000000005: There is no a local address in host list

**Comment by LeftoversTodayAppAdmin** [comment]
Hey @1212mohamedtaha I figured out the issue, here is a ticket with instructions and update to the guide doc:
https://github.com/ClickHouse/ClickHouse/issues/63313
