### ISSUE TITLE
Add hit_column_statistic system table to guide the design of materialized views

### ISSUE THREAD

**Issue by Qsimple** [ClickHouse/ClickHouse#18347]
**Use case**
As we all known, choosing the primary key is the most important thing while design an materialized views with AggregatingMergeTree engine. Commonly, using the most frequently query columns as the primary key will match the most of query scene. So, how to know which columns is the most frequently query?  

**Describe the solution you'd like**
May be we can create an hit_column_statistic(or other name) system table to log the column query frequency. Like query_log, we can log into hit_column_statistic use `SystemLog` when run in `InterpreterSelectQuery:executeFetchColumns`.     

Then, we can use hit_column_statistic system table to guide the design of materialized views. Or degin the materialized views automaticly in the future.

**Describe alternatives you've considered**
noop

**Additional context**
noop

h

tks and hope the response from community.

**Comment by alexey-milovidov** [comment]
@amosbird has recently added information about column usage in system.query_log.
It is done in this PR: #17726

**Comment by Qsimple** [comment]
I think it is enough, tks
