### ISSUE TITLE
Storages can receive incorrectly rewritten queries in 'read' method.

### ISSUE THREAD

**Issue by DimasKovas** [ClickHouse/ClickHouse#18371]
(you don't have to strictly follow this form)

**Describe the bug**
Storages receive incorrectly rewritten query in 'read' method in some cases.
For instance, the initial query is

> with test as (select number as a from numbers(10)) select * from log_t0 full join test using a

But  Storage::read receives this query in query_info.query:

> WITH test AS (SELECT number AS a FROM numbers(10)) AS _subquery1
SELECT a FROM log_t0
ALL FULL OUTER JOIN
(SELECT number AS a FROM numbers(10)) AS test
USING (a)

Where the construction 'with test as (...) as _subquery1' is not correct and AST can not be parsed from this string.

This behavior was found by reading logs. I did not find any queries affected by this, but it can break something in the future.

**How to reproduce**
First of all add debug log at the beginning of read method in storage (e.g. [here](https://github.com/ClickHouse/ClickHouse/blob/3b2f8c1a97cd80164e5f3eeb1ed570dc2bee6bbe/src/Storages/StorageTinyLog.cpp#L436)). I used a StorageTinyLog in the example but it also works for other storages.

> LOG_DEBUG(log, "XXX Reading from tiny log (Query: {})", DB::serializeAST(*query_info.query));

Do not forget to include <Parsers/formatAST.h>

* Which ClickHouse server version to use

I used the latest ClickHouse version from Arcadia.

* `CREATE TABLE` statements for all tables involved
create table 

> create table log_t0 (a UInt64) engine=TinyLog()

* Queries to run that lead to unexpected result

> with test as (select number as a from numbers(10)) select * from log_t0 full join test using a

**Error message and/or stacktrace**
The following line can be found in the log:

> XXX Reading from tiny log (Query: WITH test AS (SELECT number AS a FROM numbers(10)) AS _subquery1 SELECT a FROM log_t0 ALL FULL OUTER JOIN (SELECT number AS a FROM numbers(10)) AS test USING (a))

**Additional context**

**Comment by filimonov** [comment]
I guess the AST is correct, but serialization of AST to string is wrong.

**Comment by alexey-milovidov** [comment]
Fixed: https://pastila.nl/?0056d001/dadfcd679eee97147c21b62b196e313e#iqdM7Vt8gcyCDCTHfBYTvg==
