### ISSUE TITLE
Apply optimize_aggregation_in_order even if group by matches the sort key partially 

### ISSUE THREAD

**Issue by cyberhuman** [ClickHouse/ClickHouse#18384]
**Use case**

Given some table with a sort key (k1, k2, k3):
```
CREATE TABLE test (k1 Int32, k2 Int32, k3 Int32)
ENGINE = MergeTree()
ORDER BY (k1, k2, k3);
```
It's possible to use the group by optimization when querying it:
```
SELECT k1, k2, k3
FROM test
GROUP BY k1, k2, k3
SETTINGS optimize_aggregation_in_order = 1;
```
This helps when the cardinality of k1 is very high.
However, if one wants to group by k1 and k3 (assuming the number of different k3 for each k1 is small), the optimization is turned off completely:
```
SELECT k1, sum(k2), k3
FROM test
GROUP BY k1, k3
SETTINGS optimize_aggregation_in_order = 1; -- <= doesn't have any effect
```

**Describe the solution you'd like**
It would be nice if optimization still worked for grouping by k1, and the query was processed in RAM inside of each bucket.

**Describe alternatives you've considered**
In some cases, a workaround is possible using `array*` functions. However, it's hard to both write and read:
```
SELECT
  t.k1 AS k1,
  (
    arrayJoin(
      arrayMap(x -> ((x.1)[1], arraySum(x.2)),
      arraySplit(
        (x, y) -> y != 0,
        arraySort(
          x -> x.1,
          groupArray((t.k3, t.k2))
        ) AS row,
        arrayDifference(x -> x.1, row)
      )
    ) AS out
  ).2 AS k2,
  out.1 AS k3
FROM test AS t
GROUP BY k1
SETTINGS optimize_aggregation_in_order = 1;
```

**Additional context**

**Comment by azat** [comment]
This should be fixed by #35111
