### ISSUE TITLE
How to access the result of explain query through JDBC ?

### ISSUE THREAD

**Issue by fuwhu** [ClickHouse/ClickHouse#18397]
**Problem description**
We use JDBC to connect to ClickHouse, and we want to get the execution plan of specific SQL query using explain.
However, it seems we can not get the result of the explain query through JDBC.

Is there any mechanism that we can get the explain result or we need to add this feature somehow ?

**Comment by den-crane** [comment]
The issue is JDBC 
Open an issue where https://github.com/ClickHouse/clickhouse-jdbc

```
curl 'localhost:8123?query=explain+select+1+format+TabSeparatedWithNamesAndTypes'
explain
String
Expression (Projection)
  Expression (Before ORDER BY and SELECT)
    SettingQuotaAndLimits (Set limits and quota after reading from storage)
      ReadFromStorage (SystemOne)

```

**Comment by den-crane** [comment]
ClickHouse/clickhouse-jdbc#529

<img width="578" alt="Screen Shot 2020-12-23 at 12 09 26 PM" src="https://user-images.githubusercontent.com/19737682/103016049-d086ed80-4517-11eb-9610-5d45e205d585.png">

**Comment by fuwhu** [comment]
> The issue is in JDBC
> Open an issue where https://github.com/ClickHouse/clickhouse-jdbc
> 
> ```
> curl 'localhost:8123?query=explain+select+1+format+TabSeparatedWithNamesAndTypes'
> explain
> String
> Expression (Projection)
>   Expression (Before ORDER BY and SELECT)
>     SettingQuotaAndLimits (Set limits and quota after reading from storage)
>       ReadFromStorage (SystemOne)
> ```

is this also after ClickHouse/clickhouse-jdbc#529 ?

**Comment by den-crane** [comment]
@fuwhu The issue is not related to CH server.
Use my fix for JDBC-driver ClickHouse/clickhouse-jdbc#529

**Comment by fuwhu** [comment]
@den-crane 
Got it, thanks a lot Denny.
Just created a new issue https://github.com/ClickHouse/clickhouse-jdbc/issues/530
Let me close this one.
