### ISSUE TITLE
JSONEachRow can not parse +Inf to float64

### ISSUE THREAD

**Issue by korservick** [ClickHouse/ClickHouse#1839]
CH version: 1.1.54342
log:
2018.01.30 17:12:40.931768 [ 30 ] <Error> executeQuery: Code: 72, e.displayText() = DB::Exception: Cannot read floating point value: (at row 121867)
, e.what() = DB::Exception (from 172.21.0.3:49692) (in query: select count() from kafka_json), Stack trace:

0. /usr/bin/clickhouse-server(StackTrace::StackTrace()+0x15) [0x73178b5]
1. /usr/bin/clickhouse-server(DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)+0x1e) [0x19ca19e]
2. /usr/bin/clickhouse-server(void DB::readFloatTextFast<double>(double&, DB::ReadBuffer&)+0x10e4) [0x7347d24]
3. /usr/bin/clickhouse-server(DB::DataTypeNumberBase<double>::deserializeTextJSON(DB::IColumn&, DB::ReadBuffer&) const+0x4a) [0x6036c8a]
4. /usr/bin/clickhouse-server(DB::JSONEachRowRowInputStream::read(std::vector<COWPtr<DB::IColumn>::mutable_ptr<DB::IColumn>, std::allocator<COWPtr<DB::IColumn>::mutable_ptr<DB::IColumn> > >&)+0x510) [0x69a5540]
5. /usr/bin/clickhouse-server(DB::BlockInputStreamFromRowInputStream::readImpl()+0x97) [0x6b780e7]
6. /usr/bin/clickhouse-server(DB::IProfilingBlockInputStream::read()+0x26f) [0x5fe84cf]
7. /usr/bin/clickhouse-server(DB::KafkaBlockInputStream::readImpl()+0x8b) [0x6b3713b]
8. /usr/bin/clickhouse-server(DB::IProfilingBlockInputStream::read()+0x26f) [0x5fe84cf]
9. /usr/bin/clickhouse-server(DB::ExpressionBlockInputStream::readImpl()+0x2c) [0x698f40c]
10. /usr/bin/clickhouse-server(DB::IProfilingBlockInputStream::read()+0x26f) [0x5fe84cf]
11. /usr/bin/clickhouse-server(DB::ConcatBlockInputStream::readImpl()+0xbb) [0x66d4f0b]
12. /usr/bin/clickhouse-server(DB::IProfilingBlockInputStream::read()+0x26f) [0x5fe84cf]
13. /usr/bin/clickhouse-server(DB::Aggregator::execute(std::shared_ptr<DB::IBlockInputStream> const&, DB::AggregatedDataVariants&)+0x269) [0x6a5ed99]
14. /usr/bin/clickhouse-server(DB::AggregatingBlockInputStream::readImpl()+0x5e7) [0x69553b7]
15. /usr/bin/clickhouse-server(DB::IProfilingBlockInputStream::read()+0x26f) [0x5fe84cf]
16. /usr/bin/clickhouse-server(DB::ExpressionBlockInputStream::readImpl()+0x2c) [0x698f40c]
17. /usr/bin/clickhouse-server(DB::IProfilingBlockInputStream::read()+0x26f) [0x5fe84cf]
18. /usr/bin/clickhouse-server(DB::ExpressionBlockInputStream::readImpl()+0x2c) [0x698f40c]
19. /usr/bin/clickhouse-server(DB::IProfilingBlockInputStream::read()+0x26f) [0x5fe84cf]
20. /usr/bin/clickhouse-server(DB::AsynchronousBlockInputStream::calculate(MemoryTracker*)+0x54) [0x19dc544]
21. /usr/bin/clickhouse-server(ThreadPool::worker()+0x16d) [0x7361b9d]
22. /usr/bin/clickhouse-server() [0x76fcfae]
23. /lib/x86_64-linux-gnu/libpthread.so.0(+0x76b9) [0x7f6c87b3c6b9]
24. /lib/x86_64-linux-gnu/libc.so.6(clone+0x6c) [0x7f6c875693dc]

2018.01.30 17:12:40.974737 [ 30 ] <Trace> StorageKafka (kafka_json): KafkaBlockInputStream did not finish successfully, unsubscribing from assignments and rejoining

**Comment by filimonov** [comment]
Just inf/Inf (without plus sign) is supported, but may be signed +Inf can also be supported.

testcase: 
```
CREATE TABLE float_inf_problem ( x Float64 ) ENGINE = Memory;
insert into float_inf_problem format JSONEachRow {"x":"+inf"};

# those - work:
insert into float_inf_problem format JSONEachRow {"x":"-inf"};
insert into float_inf_problem format JSONEachRow {"x":"inf"};

insert into float_inf_problem format Values (+inf);
insert into float_inf_problem format Values (+Inf);
```

**Comment by alexey-milovidov** [comment]
JSON in its specification has no support for `inf`, `nan`.
But we have some support, and I think we should also add support for +inf.

**Comment by alexey-milovidov** [comment]
`+inf` is not supported in all test formats including TSV, CSV, JSONEachRow.

**Comment by korservick** [comment]
2 years ago... :) Just remember that I catch this `+inf` from Node.js code.
