### ISSUE TITLE
<Error> TCPHandler: Code: 32, e.displayText() = DB::Exception: Attempt to read after eof, Stack trace

### ISSUE THREAD

**Issue by tobberguo** [ClickHouse/ClickHouse#18403]
2020.12.23 18:13:43.123646 [ 23419 ] {} <Debug> MaterializeMySQLSyncThread: Skip MySQL event: 
 
=== TableMapEvent ===
Timestamp: 1608718423
Event Type: TableMapEvent
Server ID: 88803665
Event Size: 75
Log Pos: 111225
Flags: 0
Table ID: 4042981
Flags: 1
Schema Len: 10
Schema: bidme_test
Table Len: 21
Table: sf_resume_update_logs
Column Count: 4
Column Type [0]: 3, Meta: 0
Column Type [1]: 8, Meta: 0
Column Type [2]: 8, Meta: 0
Column Type [3]: 15, Meta: 60
Null Bitmap: 00000000

2020.12.23 18:13:43.124002 [ 23419 ] {} <Error> MaterializeMySQLSyncThread: Code: 32, e.displayText() = DB::Exception: Attempt to read after eof, Stack trace (when copying this message, always include the lines below):

0. DB::ReadBuffer::throwReadAfterEOF() @ 0x7d359ed in /usr/bin/clickhouse
1. ? @ 0xdb2edf3 in /usr/bin/clickhouse
2. DB::MySQLReplication::MySQLFlavor::readPayloadImpl(DB::ReadBuffer&) @ 0xdb33353 in /usr/bin/clickhouse
3. DB::MySQLProtocol::IMySQLReadPacket::readPayload(DB::ReadBuffer&, unsigned char&) @ 0xdb1b902 in /usr/bin/clickhouse
4. DB::MySQLProtocol::PacketEndpoint::tryReceivePacket(DB::MySQLProtocol::IMySQLReadPacket&, unsigned long) @ 0xdb1c3f3 in /usr/bin/clickhouse
5. DB::MaterializeMySQLSyncThread::synchronization(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xdb46206 in /usr/bin/clickhouse
6. ? @ 0xdb64b7a in /usr/bin/clickhouse
7. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x7d1baad in /usr/bin/clickhouse
8. ? @ 0x7d1f5d3 in /usr/bin/clickhouse
9. start_thread @ 0x7dd5 in /usr/lib64/libpthread-2.17.so
10. __clone @ 0xfe02d in /usr/lib64/libc-2.17.so
 (version 20.12.3.3 (official build))

**Comment by tobberguo** [comment]
MaterializeMySQL同步msyql数据，第一次全量同步完后，我在mysql中随意修改一个内容，同步拉取的时候报错。clickhouse版本：20.12.3.3

**Comment by tobberguo** [comment]
@BohuTANG @zhang2014

**Comment by tavplubix** [comment]
Could you please provide more information, how to reproduce the issue?
