### ISSUE TITLE
Memory cannot be freed

### ISSUE THREAD

**Issue by chenkaiyin1201** [ClickHouse/ClickHouse#18400]
version: 20.9.2.20
problem: After a SQL from Clickhouse caused a memory burst, the node memory cannot be automatically freed.

![image](https://user-images.githubusercontent.com/43174388/102980257-430cc300-4542-11eb-96e0-afdab8fccb65.png)

**Comment by den-crane** [comment]
It's the expected behavior. CH does not deallocate memory immediately to save CPU on allocations.
