### ISSUE TITLE
Map datatype

### ISSUE THREAD

**Issue by arctica** [ClickHouse/ClickHouse#1841]
There is already limited support for a Map datatype via the Nested type and *Map aggregate functions. This means people have a need for keys->value data structures.

It would be useful to have a dedicated Map datatype which can work with at least integers and strings as the keys and any other datatype as the value. Syntactic sugar should allow accessing values of the Map via the index operator and an easy way to create Maps.

E.g. creation via Map('foo', 1, 'bar', 3) and access via map['foo']

One can eachieve the required data storage via a Nested(k String, v Int64) column but access is rather clunky: nst.v[indexOf(nst.k, 'foo')]

**Comment by shwangdev** [comment]
Really need this feature.  Any update yet?

**Comment by Tasselmi** [comment]
hey guys, any progress on this topic?
It really helpful to use map type to store key-values.
When I dump hive data into clickhouse, this made me mad.    `Arrya/Map/Struct` THEY ARE SO fundamental ~

**Comment by alexey-milovidov** [comment]
Initial implementation has been done in #15806.
