### ISSUE TITLE
Bug: тип date через ODBC из PostgreSQL в ClickHouse

### ISSUE THREAD

**Issue by hhhackkk** [ClickHouse/ClickHouse#18420]
PostgreSQL подключён к ClickHouse через ODBC.
В PostgreSQL есть таблица где имеется поле типа date.
Создаём внешний словарь в clickhouse на эту таблицу и делаем select.
Bug: дату показывает не такую какая в PostgreSQL 

ver. ClickHouse 20.12.3.3

Воспроизводим: 
1. Создаём таблицу в PostgreSQL и вставляем парочку записей

```
CREATE TABLE public.test_date
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    date date,
    PRIMARY KEY (id)
);
```

2. Создаём внешний словарь в clickhouse

```
CREATE DICTIONARY db.test_date (`id` UInt64, `date` Date) PRIMARY KEY id SOURCE(
  ODBC(
    TABLE 'public.test_date' CONNECTION_STRING 'DSN=connection;UID=user;PWD=pass'
  )
) LAYOUT(DIRECT())
```

Делаем select в PostgreSQL видим что все даты верные
https://ibb.co/5BmfKqR
Делаем запрос в ClickHouse и видим что все даты это начало отсчёта unix time
https://ibb.co/sHxTTZ7

Если меняем в PostgreSQL тип поля date на timestamp причём не важно с тайм зоной или нет и делаем select в ClickHouse, то результат верный.

дополнение: 
https://github.com/ClickHouse/ClickHouse/issues/3700

**Comment by kssenii** [comment]
Fixed in #17301. Fixed since 21.1 version.
