### ISSUE TITLE
Documentation markup is ugly.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#18432]
1. Light-orange on gray is inhumane:

![Screenshot_20201223_172100](https://user-images.githubusercontent.com/18581488/103006821-64ba7a00-4543-11eb-81a6-dbc278bbe706.png)

2. Copy button is not sticky, it looks weird:

![Screenshot_20201223_172113](https://user-images.githubusercontent.com/18581488/103006889-7d2a9480-4543-11eb-9e76-2aac4902b68d.png)

3. Idiotic highlighling by default (no highlighting is better):

![Screenshot_20201223_172136](https://user-images.githubusercontent.com/18581488/103006928-8ca9dd80-4543-11eb-9e91-e2bc875cc8b6.png)

**Comment by alexey-milovidov** [comment]
![Screenshot_20210116_181354](https://user-images.githubusercontent.com/18581488/104815648-e5108a00-5826-11eb-911f-845bc75ee648.png)

**Comment by rfraposa** [comment]
Not relevant anymore
