### ISSUE TITLE
is it support roaringbitmap64?if not,have future plan ?

### ISSUE THREAD

**Issue by zhou-binbin** [ClickHouse/ClickHouse#18457]
Make sure to check documentation https://clickhouse.yandex/docs/en/ first. If the question is concise and probably has a short answer, asking it in Telegram chat https://telegram.me/clickhouse_en is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

If you still prefer GitHub issues, remove all this text and ask your question here.

**Comment by amosbird** [comment]
https://github.com/ClickHouse/ClickHouse/pull/17858

**Comment by zhou-binbin** [comment]
> #1First of all,thank you for your answer.My CK version is 20.8,I use bitmap64,I find a question. the question as follows:
the answer of groupbitmap(uid)  and count (distinct uid) not the same, the type of uid is UInt64,What is the reason?

**Comment by amosbird** [comment]
It's not merged yet (ETA this week)

**Comment by zhou-binbin** [comment]
> ETA

That will be wonderful.This problem will be fixed in the near future，Will it be merged into the latest version?

**Comment by amosbird** [comment]
It's merged.

**Comment by zhou-binbin** [comment]
> It's merged.

OK,what is the version ? is it the latest release version v20.8.11.17-lts or other ? can you tell me the version ? Thank you !

**Comment by zhou-binbin** [comment]
@amosbird

**Comment by amosbird** [comment]
It's in current master. I'm not sure when it will be released. You can get the CI build from here https://clickhouse-builds.s3.yandex.net/0/7b23b866a231cb399ada061e7e378d2d3ac625c7/clickhouse_build_check/report.html  . Or you can build it manually.

**Comment by alexey-milovidov** [comment]
Testing build has been released: https://repo.yandex.ru/clickhouse/deb/testing/main/
