### ISSUE TITLE
Performing C SOURCE FILE Test CMAKE_HAVE_LIBC_PTHREAD failed

### ISSUE THREAD

**Issue by herbertluo** [ClickHouse/ClickHouse#18451]
**Operating system**
Linux VM_116_204_centos 3.10.107

**Cmake version**
cmake version 3.19.2

**Ninja version**
1.9.0

**Compiler name and version**
gcc version 9.3.0 (GCC) 
gcc version 9.3.0 (GCC)

**Full cmake and/or ninja output**
-- Using custom linker by name: gold
-- CMAKE_BUILD_TYPE is not set, set to default = RelWithDebInfo
-- CMAKE_BUILD_TYPE: RelWithDebInfo
-- Using objcopy: /usr/bin/objcopy.
-- Default libraries: -nodefaultlibs -lgcc  -lc -lm -lrt -lpthread -ldl
-- Some symbols from glibc will be replaced for compatibility
-- Using libunwind: unwind
-- Using exception handler: unwind
-- Using libcxx: cxx
-- Using libcxxfs: 
-- Using libcxxabi: cxxabi
-- Unit tests are enabled
-- Building for: Linux-3.10.107-1-tlinux2_kvm_guest-0049 x86_64  ;
    USE_STATIC_LIBRARIES=ON
    MAKE_STATIC_LIBRARIES=ON
    SPLIT_SHARED=
    UNBUNDLED=OFF
    CCACHE=CCACHE_FOUND-NOTFOUND 
-- Using double-conversion:  : double-conversion
-- Using ssl=1: /root/dev/ClickHouse/contrib/boringssl/include : ssl;crypto
-- Using ldap=1: /root/dev/ClickHouse/contrib/openldap-cmake/linux_x86_64/include;/root/dev/ClickHouse/contrib/openldap/include : ldap_r;lber
-- Using icu=1:  : icui18n;icuuc;icudata
-- Using zlib-ng: /root/dev/ClickHouse/contrib/zlib-ng;/root/dev/ClickHouse/build/contrib/zlib-ng : zlib
-- Using zstd: /root/dev/ClickHouse/contrib/zstd/lib : zstd
-- Using sparsehash: /root/dev/ClickHouse/contrib/sparsehash-c11
-- Using re2: /root/dev/ClickHouse/contrib/re2 : re2;  : re2_st
-- Using krb5=1: /root/dev/ClickHouse/contrib/krb5/src/include;/root/dev/ClickHouse/build/contrib/krb5-cmake/include : krb5
-- Using libgsasl=1: /root/dev/ClickHouse/contrib/libgsasl/src;/root/dev/ClickHouse/contrib/libgsasl/linux_x86_64/include : libgsasl
-- Using cyrus-sasl: krb5=1: /root/dev/ClickHouse/contrib/cyrus-sasl/include : sasl2
-- Using librdkafka=1: /root/dev/ClickHouse/contrib/librdkafka/src : rdkafka cppkafka
-- Using AMQP-CPP=1: /root/dev/ClickHouse/contrib/AMQP-CPP/include;/root/dev/ClickHouse/contrib/AMQP-CPP/include;/root/dev/ClickHouse/contrib/AMQP-CPP : AMQP-CPP
-- Using capnp=1: capnpc
-- LLVM include Directory: /root/dev/ClickHouse/contrib/llvm/llvm/include;/root/dev/ClickHouse/build/contrib/llvm/llvm/include
-- LLVM library Directory: /root/dev/ClickHouse/build/contrib/llvm/llvm
-- LLVM C++ compiler flags: 
-- Using h3=1: /root/dev/ClickHouse/contrib/h3/src/h3lib/include : h3
-- Using libxml2: /root/dev/ClickHouse/contrib/libxml2/include;/root/dev/ClickHouse/contrib/libxml2-cmake/linux_x86_64/include : libxml2
-- Using brotli=1: /root/dev/ClickHouse/contrib/brotli/c/include : brotli
-- Using protobuf=1: /root/dev/ClickHouse/contrib/protobuf/src : libprotobuf : $<TARGET_FILE:protoc> : libprotoc
-- Using gRPC=1: /root/dev/ClickHouse/contrib/grpc/include : grpc;grpc++ : $<TARGET_FILE:grpc_cpp_plugin>
-- Using pdqsort: /root/dev/ClickHouse/contrib/pdqsort
-- Using miniselect: /root/dev/ClickHouse/contrib/miniselect/include
-- Using hdfs3=1: /root/dev/ClickHouse/contrib/libhdfs3/include : hdfs3
-- Using curl: /root/dev/ClickHouse/contrib/curl/include : curl
-- Using aws_s3=1: /root/dev/ClickHouse/contrib/aws/aws-cpp-sdk-s3/include : aws_s3
-- Using snappy: snappy
-- Using Parquet: arrow=arrow_static: ; parquet=parquet_static: ; thrift=thrift_static ; flatbuffers=flatbuffers
-- Using simdjson=ON
-- Using rapidjson=1: /root/dev/ClickHouse/contrib/rapidjson/include
-- Using fastops=1: /root/dev/ClickHouse/contrib/fastops/ : fastops
-- Using unixodbc
-- Using ROCKSDB=1: /root/dev/ClickHouse/contrib/rocksdb/include : rocksdb
-- Using snappy: snappy
-- Using internal=1 orc=1: /root/dev/ClickHouse/contrib/orc/c++/include : orc
-- Using snappy: snappy
-- Using avro=1: /root/dev/ClickHouse/contrib/avro/lang/c++/include : avrocpp
-- Using msgpack=1: /root/dev/ClickHouse/contrib/msgpack-c/include
-- Using cassandra=1: /root/dev/ClickHouse/contrib/cassandra/include/ : cassandra_static
-- Using libuv: /root/dev/ClickHouse/contrib/libuv : uv_a
-- Using sentry=ON: sentry
-- Using stats=1 : /root/dev/ClickHouse/contrib/stats/include
-- Using gcem=1: /root/dev/ClickHouse/contrib/gcem/include
-- Using cityhash:  : cityhash
-- Using farmhash:  : farmhash
-- Using gtest=1: /root/dev/ClickHouse/contrib/googletest/googletest : gtest_main;gtest : 
-- Using mysqlclient=1:  : mariadbclient; staticlib=
-- compiler C   = /usr/local/bin/gcc  -fdiagnostics-color=always  -pipe -msse4.1 -msse4.2 -mpopcnt  -Wall  -Werror -O2 -g -DNDEBUG -O3  -fno-pie
-- compiler CXX = /usr/local/bin/g++  -fdiagnostics-color=always -std=gnu++2a -fsized-deallocation  -pipe -msse4.1 -msse4.2 -mpopcnt   -Wall  -Werror -O2 -g -DNDEBUG -O3  -fno-pie
-- LINKER_FLAGS =  -fuse-ld=gold -rdynamic -Wl,--no-undefined -Wl,-no-pie 
-- Packaging with tzdata version: 2020d
-- Using cctz
-- Using FastMemcpy
-- Using hyperscan
-- jemalloc malloc_conf: percpu_arena:percpu,oversize_threshold:0,muzzy_decay_ms:10000
-- Using jemalloc
-- Using cpuid
-- Using replxx
-- Using Poco::Crypto
-- Using Poco::Data::ODBC
-- ZSTD VERSION 1.4.0
-- Using CMake version 3.19.2
-- ZLIB_HEADER_VERSION: 1.2.11
-- ZLIBNG_HEADER_VERSION: 1.9.9
-- Arch detected: 'x86_64'
-- Basearch of 'x86_64' has been detected as: 'x86'
-- Architecture-specific source files: arch/x86/x86.c;arch/x86/insert_string_sse.c;arch/x86/deflate_quick.c;arch/x86/fill_window_sse.c;arch/x86/slide_sse.c;arch/x86/crc_folding.c
-- The following features have been enabled:

 * CMAKE_BUILD_TYPE, Build type: RelWithDebInfo (selected)
 * ZLIB_COMPAT, Provide a zlib-compatible API
 * WITH_OPTIM, Build with optimisation
 * WITH_NEW_STRATEGIES, Use new strategies
 * SSE42_CRC, Support CRC hash generation using the SSE4.2 instruction set, using "-msse4"
 * SSE42_DEFLATE_QUICK, Support SSE4.2-accelerated quick compression
 * PCLMUL_CRC, Support CRC hash generation using PCLMULQDQ, using "-mpclmul"

-- The following REQUIRED packages have been found:

 * Threads

-- The following features have been disabled:

 * WITH_GZFILEOP, Compile with support for gzFile-related functions
 * WITH_SANITIZERS, Build with address sanitizer and all supported sanitizers other than memory sanitizer
 * WITH_MSAN, Build with memory sanitizer
 * WITH_FUZZERS, Build test/fuzz
 * MAINTAINER, Build with maintainer warnings and tests enabled

CMake Deprecation Warning at contrib/mariadb-connector-c/CMakeLists.txt:5 (CMAKE_MINIMUM_REQUIRED):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- librdkafka with SASL support
-- FLATBUFFERS_LIBRARY: flatbuffers
CMake Deprecation Warning at contrib/googletest/googletest/CMakeLists.txt:56 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- Native target architecture is X86
-- Threads enabled.
-- Doxygen disabled.
stat /root/dev/ClickHouse/contrib/llvm/llvm/bindings/go/conftest.go: no such file or directory
-- Go bindings disabled, need at least Go 1.2.
-- Ninja version: 1.9.0
-- Could NOT find OCaml (missing: OCAMLFIND OCAML_VERSION OCAML_STDLIB_PATH) 
-- Could NOT find OCaml (missing: OCAMLFIND OCAML_VERSION OCAML_STDLIB_PATH) 
-- OCaml bindings disabled.
-- LLVM host triple: x86_64-unknown-linux-gnu
-- LLVM default target triple: x86_64-unknown-linux-gnu
-- Constructing LLVMBuild project information
-- Linker detection: GNU Gold
-- LLVMHello ignored -- Loadable modules not supported on this platform.
-- Targeting X86
-- Targeting AArch64
CMake Deprecation Warning at contrib/libgsasl/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- 
-- 3.13.0.0
-- checking compiler: GCC (9.3.)
-- Checking whether strerror_r returns an int
-- Checking whether strerror_r returns an int -- no
-- No CMAKE_CXX_STANDARD set, assuming 11
CMake Error at contrib/grpc/cmake/cares.cmake:25 (add_subdirectory):
  The source directory

    /root/dev/ClickHouse/contrib/grpc/third_party/cares/cares

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  contrib/grpc/CMakeLists.txt:253 (include)

CMake Deprecation Warning at contrib/cassandra/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

CMake Deprecation Warning at contrib/cassandra/cmake/modules/CppDriver.cmake:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
Call Stack (most recent call first):
  contrib/cassandra/CMakeLists.txt:10 (include)

-- PROJECT version: 2.11.0
-- libuv version: v1.34.1
-- OpenSSL version: v
-- Using std::atomic implementation for atomic operations
CMake Deprecation Warning at contrib/cassandra/src/third_party/sparsehash/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- Using hash header <functional> and namespace "std"
-- SENTRY_TRANSPORT=curl
-- SENTRY_BACKEND=none
-- GCE-Math version 1.13.0
-- Performing Test SUPPORTS_CXXFLAG_frame_larger_than=65536
-- Performing Test SUPPORTS_CXXFLAG_frame_larger_than=65536 - Success
-- Performing Test SUPPORTS_CFLAG_frame_larger_than=65536
-- Performing Test SUPPORTS_CFLAG_frame_larger_than=65536 - Success
-- /root/dev/ClickHouse/src: Have 8858 megabytes of memory.
        Limiting concurrent linkers jobs to 2 and compiler jobs to 3
-- Will build ClickHouse 20.13.1.1 revision 54444 
CMake Warning at src/Functions/CMakeLists.txt:53 (message):
  Not generating debugger info for ClickHouse functions

-- ClickHouse modes:
-- Server mode: ON
-- Client mode: ON
-- Local mode: ON
-- Benchmark mode: ON
-- Extract from config mode: ON
-- Compressor mode: ON
-- Copier mode: ON
-- Format mode: ON
-- Obfuscator mode: ON
-- ODBC bridge mode: ON
-- ClickHouse install: ON
-- ClickHouse git-import: ON
-- Target check already exists
-- /root/dev/ClickHouse/utils: Have 8830 megabytes of memory.
        Limiting concurrent linkers jobs to 2 and compiler jobs to OFF
-- Configuring incomplete, errors occurred!
See also "/root/dev/ClickHouse/build/CMakeFiles/CMakeOutput.log".
See also "/root/dev/ClickHouse/build/CMakeFiles/CMakeError.log".

**CMakeError.log top 100**
Performing C SOURCE FILE Test CMAKE_HAVE_LIBC_PTHREAD failed with the following output:
Change Dir: /root/dev/ClickHouse/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/local/bin/ninja cmTC_670d3 && [1/2] Building C object CMakeFiles/cmTC_670d3.dir/src.c.o
[2/2] Linking C executable cmTC_670d3
FAILED: cmTC_670d3 
: && /usr/local/bin/gcc -fdiagnostics-color=always  -pipe -msse4.1 -msse4.2 -mpopcnt  -Wall  -Werror -fuse-ld=gold -rdynamic -Wl,--no-undefined   -rdynamic CMakeFiles/cmTC_670d3.dir/src.c.o -o cmTC_670d3   && :
CMakeFiles/cmTC_670d3.dir/src.c.o:src.c:function main: error: undefined reference to 'pthread_create'
CMakeFiles/cmTC_670d3.dir/src.c.o:src.c:function main: error: undefined reference to 'pthread_detach'
CMakeFiles/cmTC_670d3.dir/src.c.o:src.c:function main: error: undefined reference to 'pthread_cancel'
CMakeFiles/cmTC_670d3.dir/src.c.o:src.c:function main: error: undefined reference to 'pthread_join'
CMakeFiles/cmTC_670d3.dir/src.c.o:src.c:function main: error: undefined reference to 'pthread_atfork'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

Source file was:
#include <pthread.h>

static void* test_func(void* data)
{
  return data;
}

int main(void)
{
  pthread_t thread;
  pthread_create(&thread, NULL, test_func, NULL);
  pthread_detach(thread);
  pthread_cancel(thread);
  pthread_join(thread, NULL);
  pthread_atfork(NULL, NULL, NULL);
  pthread_exit(NULL);

  return 0;
}

Determining if the include file sys/random.h exists failed with the following output:
Change Dir: /root/dev/ClickHouse/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/local/bin/ninja cmTC_af9ae && [1/2] Building C object CMakeFiles/cmTC_af9ae.dir/CheckIncludeFile.c.o
FAILED: CMakeFiles/cmTC_af9ae.dir/CheckIncludeFile.c.o 
/usr/local/bin/gcc   -fdiagnostics-color=always  -pipe -msse4.1 -msse4.2 -mpopcnt  -Wall  -Werror -o CMakeFiles/cmTC_af9ae.dir/CheckIncludeFile.c.o -c CheckIncludeFile.c
CheckIncludeFile.c:1:10: fatal error: sys/random.h: No such file or directory
    1 | #include <sys/random.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.

Performing C SOURCE FILE Test TUKLIB_PHYSMEM_SPECIAL failed with the following output:
Change Dir: /root/dev/ClickHouse/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/local/bin/ninja cmTC_8eb0c && [1/2] Building C object CMakeFiles/cmTC_8eb0c.dir/src.c.o
FAILED: CMakeFiles/cmTC_8eb0c.dir/src.c.o 
/usr/local/bin/gcc -DTUKLIB_PHYSMEM_SPECIAL -D_ALL_SOURCE -D_GNU_SOURCE -D_POSIX_PTHREAD_SEMANTICS -D_TANDEM_SOURCE -D__EXTENSIONS__  -fdiagnostics-color=always  -pipe -msse4.1 -msse4.2 -mpopcnt  -Wall  -Werror -w -o CMakeFiles/cmTC_8eb0c.dir/src.c.o -c src.c
src.c:5:13: error: unknown type name ‘compile’
    5 |             compile error
      |             ^~~~~~~
src.c:5:13: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ at end of input
ninja: build stopped: subcommand failed.

Source file was:

            #if defined(_WIN32) || defined(__CYGWIN__) || defined(__OS2__)                 || defined(__DJGPP__) || defined(__VMS)                 || defined(AMIGA) || defined(__AROS__) || defined(__QNX__)
            int main(void) { return 0; }
            #else
            compile error
            #endif
        
Performing C SOURCE FILE Test TUKLIB_PHYSMEM_AIX failed with the following output:
Change Dir: /root/dev/ClickHouse/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/local/bin/ninja cmTC_38f9a && [1/2] Building C object CMakeFiles/cmTC_38f9a.dir/src.c.o
FAILED: CMakeFiles/cmTC_38f9a.dir/src.c.o 
/usr/local/bin/gcc -DTUKLIB_PHYSMEM_AIX -D_ALL_SOURCE -D_GNU_SOURCE -D_POSIX_PTHREAD_SEMANTICS -D_TANDEM_SOURCE -D__EXTENSIONS__  -fdiagnostics-color=always  -pipe -msse4.1 -msse4.2 -mpopcnt  -Wall  -Werror -w -o CMakeFiles/cmTC_38f9a.dir/src.c.o -c src.c
src.c:2:22: fatal error: sys/systemcfg.h: No such file or directory
    2 |             #include <sys/systemcfg.h>
      |                      ^~~~~~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.

Source file was:

            #include <sys/systemcfg.h>
            int main(void)
            {
                (void)_system_configuration.physmem;
                return 0;
            }
        
Determining if the optreset exist failed with the following output:
Change Dir: /root/dev/ClickHouse/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/local/bin/ninja cmTC_c6c35 && [1/2] Building C object CMakeFiles/cmTC_c6c35.dir/CheckSymbolExists.c.o
FAILED: CMakeFiles/cmTC_c6c35.dir/CheckSymbolExists.c.o 
/usr/local/bin/gcc -D_ALL_SOURCE -D_GNU_SOURCE -D_POSIX_PTHREAD_SEMANTICS -D_TANDEM_SOURCE -D__EXTENSIONS__  -fdiagnostics-color=always  -pipe -msse4.1 -msse4.2 -mpopcnt  -Wall  -Werror -w -o CMakeFiles/cmTC_c6c35.dir/CheckSymbolExists.c.o -c CheckSymbolExists.c

**Comment by zhangjingwei-gwi** [comment]
I got through this by set `set(CMAKE_HAVE_LIBC_PTHREAD 1)` at the top of cmakelist.txt. hope to help.

**Comment by alexey-milovidov** [comment]
> CMake Error at contrib/grpc/cmake/cares.cmake:25 (add_subdirectory):
The source directory
/root/dev/ClickHouse/contrib/grpc/third_party/cares/cares
does not contain a CMakeLists.txt file.

You should checkout all submodules recursively.
