### ISSUE TITLE
A function to extract text from HTML and XML

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#18454]
**Use case**

We have web crawl database with HTML content in a column.
Need to extract text content to do some analysis.

**Describe the solution you'd like**

It can be not 100% correct but must be fast.

For HTML and XHTML:
- remove `script` and `style` elements (and maybe `meta`) with all their content (assuming `</script>` is properly escaped in JS string literals as expected, counterexample: `<script>var x = "</script>"</script>`);
- unwrap CDATA;
- remove tags (assuming entities are properly escaped in attributes, counterexample: `<test test=">">`);
- collapse whitespaces;

For XML:
- unwrap CDATA;
- remove tags (assuming entities are properly escaped in attributes, counterexample: `<test test=">">`);
- collapse whitespaces;

(everything should be done in single pass but the logical order matters)

We will not support custom XML entities. We will not decode HTML and XML entities (there will be a separate function for it). We will not process meta charset declaration... It's in question should we involve processing of comments.

**Describe alternatives you've considered**

[Parse HTML with regular expressions](https://i.redd.it/k6sded6b9mkz.png):
```
replaceRegexpAll(replaceRegexpAll(content, '(?s)<(script|style)[^>]*>.*?</(script|style)>', ''), '<[^>]+>', '')
```

**Comment by zlx19950903** [comment]
What slows down the speed of regular expression? It should be quite fast.

**Comment by alexey-milovidov** [comment]
@zlx19950903 

1. There are two invocations of regular expressions, it means two passes over memory instead of one.
2. The implementation with regular expressions is not quite correct.
3. Performance of regular expressions depends on the engine. ClickHouse has support for two engines: `re2` and `hyperscan`. Both are quite fast. AFAIR, hyperscan does not support replacements, so only re2 remains. AFAIK, re2 does not have shortcuts to quickly find next symbols with SIMD. It is reasonably fast but carefully optimized custom code can achieve better performance.

**Comment by zlx19950903** [comment]
I have finished a version based on HyperScan. The methods are follow:

1. Use **hs_compile_multi** to compile "(?s)<script[^>]\*>.\*?</script>", "(?s)<style[^>]\*>.\*?</style>", "<[^>]+>", "(?s)\<![CDATA[.\*?]]>";
2. Keep the order of match and remove elements above and their contents. Specially for **CADTA**，we reserve its content;

Everything will be done in a single pass and get a SIMD support. But there are some problems:
1. Is it enough that we just handle <style></style>,<script></script> and <other tags>?
2. If CDATA occurs in the area of script's content, is it should be reserved? For example:
      "<script>\<![CDATA[some codes here]]></script>"
   What do we get from the examples above? "some codes here" or just nothing?

**Comment by alexey-milovidov** [comment]
> Is it enough that we just handle <style></style>,<script></script> and ?

Looks like it's enough.

> If CDATA occurs in the area of script's content, is it should be reserved?

All content of the script tag should be removed (including CDATA).

> What do we get from the examples above? "some codes here" or just nothing?

nothing.

**Comment by alexey-milovidov** [comment]
A test case:

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<![CDATA[  <script type="text/javascript">Hello, world</script> ]]><hello />world<![CDATA[ <style> ]]> hello</style>
<script><![CDATA[</script>]]>hello</script>
</html>
```

Should return:

```  <script type="text/javascript">Hello, world</script> world <style> hello```

If you manage to achieve correct result with regexp, you are hero!

**Comment by zlx19950903** [comment]
Thanks. I will handle this question, assign to me.

**Comment by zlx19950903** [comment]
> A test case:
> 
> ```
> <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
>   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
> <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
> <![CDATA[  <script type="text/javascript">Hello, world</script> ]]><hello />world<![CDATA[ <style> ]]> hello</style>
> <script><![CDATA[</script>]]>hello</script>
> </html>
> ```
> 
> Should return:
> 
> ` <script type="text/javascript">Hello, world</script> world <style> hello`
> 
> If you manage to achieve correct result with regexp, you are hero!

The last two sentences of example above is  "<script><![CDATA[</script>]]>hello</script>", and "<script><![CDATA[</script>" will be checked as "<script></script>" label firstly. So the answer will be "]]hello". Am i right?

**Comment by zlx19950903** [comment]
> A test case:
> 
> ```
> <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
>   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
> <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
> <![CDATA[  <script type="text/javascript">Hello, world</script> ]]><hello />world<![CDATA[ <style> ]]> hello</style>
> <script><![CDATA[</script>]]>hello</script>
> </html>
> ```
> 
> Should return:
> 
> ` <script type="text/javascript">Hello, world</script> world <style> hello`
> 
> If you manage to achieve correct result with regexp, you are hero!

The last two sentences of example above is `<script><![CDATA[</script>]]>hello</script>`. And as described, it is a counter example and `<script><![CDATA[</script>` will be checked as `script` label. So the right answer will be `]]hello`. Am I right?

**Comment by zlx19950903** [comment]
> A test case:
> 
> ```
> <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
>   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
> <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
> <![CDATA[  <script type="text/javascript">Hello, world</script> ]]><hello />world<![CDATA[ <style> ]]> hello</style>
> <script><![CDATA[</script>]]>hello</script>
> </html>
> ```
> 
> Should return:
> 
> ` <script type="text/javascript">Hello, world</script> world <style> hello`
> 
> If you manage to achieve correct result with regexp, you are hero!

The last two sentences of example above is `<script><![CDATA[</script>]]>hello</script>`. And as described, it is a counter example and `<script><![CDATA[</script>` will be checked as `script` label. So the right answer will be `]]>hello`. Am I right? The complete answer should be `<script type="text/javascript">Hello, world</script> world <style> hello]]>hello`

**Comment by zlx19950903** [comment]
And another question is that what 's the law of collapsing whitespaces? If whitespace occurs in an element, it is easy to remove; But if it occurs in the content, should it be removed?For example, `<tag1>\n<tag2>`, should we remove this new line character?

**Comment by alexey-milovidov** [comment]
> The last two sentences of example above is <script><![CDATA[</script>]]>hello</script>. And as described, it is a counter example and <script><![CDATA[</script> will be checked as script label.

Not quite. The logic is the following:

`<script>` - skip everything until script is closed.
`<![CDATA[` - process everything as plain character data unless CDATA is closed.
`</script>` - processed as plain characters inside CDATA, does not mean that the script is closed.
`]]>` - CDATA is closed.
`hello` - skipped as inside the script tag.
`</script>` - finally, script is closed.

More info:

1. There is a difference between XML (including XHTML) and HTML (including HTML5).
XML does not allow mismatched tags (the document is considered incorrect as a whole and rejected).
HTML does not support CDATA, and does not interpret it as XML.
XML has different semantics of comments than HTML.

2. HTML recommends to escape `/` in string literals in JavaScript as `\/`. But it is not always the case, and unescaped `</script>` sequence can be found in JavaScript.

But we don't rely on anything of this behaviour and will implement some kind of "best effort" approach that is neither 100% correct in the sense of HTML or XML, and supports both: - mismatched tags, - CDATA, - unescaped `/` in JavaScript and CSS.

I suggest to implement all the logic in single loop with one-pass over characters.

**Comment by alexey-milovidov** [comment]
![Screenshot_20210110_015540](https://user-images.githubusercontent.com/18581488/104110250-fc132180-52e6-11eb-89b3-95090dd5a54c.png)

**Comment by zlx19950903** [comment]
> Whitespaces:
> 
> ![Screenshot_20210110_015540](https://user-images.githubusercontent.com/18581488/104110250-fc132180-52e6-11eb-89b3-95090dd5a54c.png)

I conclude the picture as follow:
1. Continous whitespaces will be collapsed into one blank. 
      1. `content\n\n  \n  content` will be `content content`
      2. `content  content` will be `content content`
2. Single white space will be subtituted by one blank.
      1. `content\ncontent` will be `content content`
      2. `\ncontent` will be ` content`
That is to say, outcome will never contain a newline character and continous blanks. It loos like more complicated than I thought. So many questions to bother you!
