### ISSUE TITLE
Any solution or plan for supporting read-write separation ?

### ISSUE THREAD

**Issue by liuyonghengheng** [ClickHouse/ClickHouse#18452]
### Background  

At present, when users insert a large amount of records into the mergetree distributed table, the insertion task will take up a large amount of computing resources, which leads to the **performance decline** or even failure of the query. As a DBA, I want to ensure that clickhouse's performance is good and stable.

As far as I know, some clickhouse users/developers leverage clickhouse mergetree engine's library and external compute engine(such as spark) to generate mergetree files, and move them directly to all local table path corresponding to the specific distributed table. However, this way depends on extra development to reinvent the wheel (also need good understanding to the internal of Clickhouse) and it is not user friendly.  

### Question  

If clickhouse can support the built-in read-write separation function, all insertion operations will be carried out on the write node, and the write node will compact/merge input records, and then the merged files will be distributed to the corresponding read nodes according to shard, so that the impact of insert operation on query node can be reduced, thus ensuring the stability of query performance. So my question is, do community have a plan to support the **built-in read-write separation** function ?

**Comment by hit-lacus** [comment]
+1

**Comment by den-crane** [comment]
You can insert into dedicated replica. And enable `always_fetch_merged_part`

_Add setting always_fetch_merged_part which restrict replica to merge parts by itself and always prefer dowloading from other replicas. #10379 (alesapin)_

**Comment by liuyonghengheng** [comment]
Thank you for your reply @den-crane .

From my understanding, using dedicated replica to implement the separation/splitting of read and write do works, but this approach is **not flexible** and may lead to **waste of resources**. For example, if I create a clickhouse cluster with 10 shards and 2 replica for each shard (in 20 physical nodes), then I will have 10 clickhouse nodes for write operation. Doing so may cause waste of resources, in the real scenario, maybe only two machines is enough to accept all write operation (write node is not responsible for answering query).  

My idea is to introducing **r/w splitting distributed table engine** and **new role** to clickhouse cluster : read node and write node. Each clickhouse node can be designated as read or write node when creating a r/w splitting table. Users can insert records into any write nodes, the write nodes are responsible for dividing the records by shard and inserting it into the local directory temporarily. After all the records are merged into merged-tree files, merged-tree files will be distributed to the read nodes (so compact/merge in read node side will be reduced).  

![image](https://user-images.githubusercontent.com/56812134/103153388-1ae3c500-47cb-11eb-971f-5c9fba4f91ce.png)


Here is some **detail/concerns** of this design(some point are complex so I didn't explain them fully at the moment):

- Only merge tree table engines will be supported .
- Whether to support atomic write .
- For the scenario of continuous/real-time insertion, there should be some parameters (such as max_wait_count, max_wait_druation) that can control the frequency of synchronization to the read node; of course, this will also cause the data delay to increase .
- If users send a large amount of records(which belongs to many shards) to single write node, the write node need to reduce the number of small files and improve the merge speed. 

Do you agree with my proposal or do you have any suggestions?

**Comment by den-crane** [comment]
**JFYI: My opinion is not relevant. I have no relation to CH development.**

But anyway you have described over-complicated schema. And I think you overrate the ingestion performance impact.
I am happy with a current design that all nodes ingest data and merge parts and do not use the network for fetches.

**Comment by liuyonghengheng** [comment]
Hi, @den-crane, thank you for your reply.

As far as I know, some Clickhouse users leverage merge tree engine's library or temporary Clickhouse cluster(in k8s) to generate merge-tree files, and move them directly to all local table path corresponding to the specific distributed table. But it is not the build-in function. For example, [QQ Music use case](https://cloud.tencent.com/developer/article/1637840) is a proven use case (unlucky, the article is wrote in Chinese).  Following is chart of architecture (use temporary Clickhouse cluster in k8s).

![image](https://user-images.githubusercontent.com/56812134/103168341-33a4b700-486d-11eb-87c7-8bae22832a39.png) 

I have raise a discussion in [2021 roadmap discussion]( https://github.com/ClickHouse/ClickHouse/issues/17623) .

**Comment by meshpaul** [comment]
Hmm, I think this is best to be controlled via CH Proxy and extra infrastrucure.  Where one can separate `insert` from `select` and mix of K8 operator to be merged as part of same persisted/replicated storage.  I am not so sure one can split read vs write effectively but with use of replication and separating cluster into read and write plus CH Proxy can direct resources.  

I asked this ? to Altinity on  [k8](https://github.com/Altinity/clickhouse-operator) If using over K8 operator one can set CPU limits to scale things dynamically this is the most effective way to achieve this other-way this will lead to extra infrastructure

**Comment by filimonov** [comment]
> Do you agree with my proposal or do you have any suggestions?

The separation of reads and writes is used ALREADY successfully in quite a few places (I know 3 quite big installations when it's happening). I don't exactly understand the additional requirements. 

OK, you have insert-only nodes - just name 2 of your nodes as 'insert node' and use it only for inserts. 
You can have read-only node - just name 8 nodes as 'read nodes' and use it only for reads. 
You can scale them easily - i.e. start / stop additional read/insert nodes when needed.

So it's possible already (while require some scripting). 

What kind of changes needed from ClickHouse side? 

The main problem here is how to move big amount of data between the nodes efficiently, and one of the possible answers - don't do it at all by separating storage and computation - that work is happening (S3).

**Comment by liukairong** [comment]
As far as I know, when writing data in the ClickHouse distributed table, if the local table is written, only one node will write the data, and the data will be distributed to other nodes. In the distributed architecture, why can’t it be used to multiple The local node writes data, eg: Spark df is written to CK, df has the same partition data as the local node of ck, and the data of a partition of df is written to a local node of CK, which can greatly improve the writing of CK. Entry speed, is this idea achievable?

**Comment by liukairong** [comment]
> Hi, @den-crane, thank you for your reply.
> 
> As far as I know, some Clickhouse users leverage merge tree engine's library or temporary Clickhouse cluster(in k8s) to generate merge-tree files, and move them directly to all local table path corresponding to the specific distributed table. But it is not the build-in function. For example, [QQ Music use case](https://cloud.tencent.com/developer/article/1637840) is a proven use case (unlucky, the article is wrote in Chinese). Following is chart of architecture (use temporary Clickhouse cluster in k8s).
> 
> ![image](https://user-images.githubusercontent.com/56812134/103168341-33a4b700-486d-11eb-87c7-8bae22832a39.png)
> 
> I have raise a discussion in [2021 roadmap discussion](https://github.com/ClickHouse/ClickHouse/issues/17623) .



> Hmm, I think this is best to be controlled via CH Proxy and extra infrastrucure. Where one can separate `insert` from `select` and mix of K8 operator to be merged as part of same persisted/replicated storage. I am not so sure one can split read vs write effectively but with use of replication and separating cluster into read and write plus CH Proxy can direct resources to appropriate R/W clusters.
> 
> I asked this ? to Altinity on [k8](https://github.com/Altinity/clickhouse-operator) If using over K8 operator to split between read/write. Their answer was very efficient IMHO one can set CPU limits to scale things dynamically this is the most effective way to achieve this other-way this will lead to extra infrastructure



> Hi, @den-crane, thank you for your reply.
> 
> As far as I know, some Clickhouse users leverage merge tree engine's library or temporary Clickhouse cluster(in k8s) to generate merge-tree files, and move them directly to all local table path corresponding to the specific distributed table. But it is not the build-in function. For example, [QQ Music use case](https://cloud.tencent.com/developer/article/1637840) is a proven use case (unlucky, the article is wrote in Chinese). Following is chart of architecture (use temporary Clickhouse cluster in k8s).
> 
> ![image](https://user-images.githubusercontent.com/56812134/103168341-33a4b700-486d-11eb-87c7-8bae22832a39.png)
> 
> I have raise a discussion in [2021 roadmap discussion](https://github.com/ClickHouse/ClickHouse/issues/17623) .

As far as I know, when writing data in the ClickHouse distributed table, if the local table is written, only one node will write the data, and the data will be distributed to other nodes. In the distributed architecture, why can’t it be used to multiple The local node writes data, eg: Spark df is written to CK, df has the same partition data as the local node of ck, and the data of a partition of df is written to a local node of CK, which can greatly improve the writing of CK. Entry speed, is this idea achievable?

**Comment by azat** [comment]
@liukairong not sure that I understood the question, but

> As far as I know, when writing data in the ClickHouse distributed table, if the local table is written, only one node will write the data, and the data will be distributed to other nodes.

When you INSERT data into Distributed query, the node that you was used to INSERT into will split data by sharding_key and send data to other shards by itself.
It will do this in background by default (see `insert_distributed_sync`), but you can change this.

>why can’t it be used to multiple

Did not understand, but you can insert into any node, you just need to create the same Distributed table on each of them, then any node can be used as an entry point for INSERT, and will do the splitting and sending between the nodes of the cluster.

>Spark df is written to CK, df has the same partition data as the local node of ck, and the data of a partition of df is written to a local node of CK, which can greatly improve the writing of CK. Entry speed, is this idea achievable?

*(I assume that CK is ClickHouse)*

Did not understand, but if partitioning in spark is the same as in ClickHouse you can insert into local node.
Also note, that if you don't need to rely on the distribution of data by sharding key, then you can INSERT Into any local node (but you need to balance things, to avoid uneven cluster load).

**Comment by lingo-xp** [comment]
As @liukairong mentioned, we can balance the data by sharding key in spark , and directly write them into local nodes. It is very efficient(In our scenarios, hundred billions of data can be inserted within a few hours ), but it may cost a lot of machine resource(high cpu and high IO) and impact the reading operation. So we want a way to directly generate mergetree files in spark/flink to meet the need for read-write separation, it's just like bulkloader in hbase or rocksdb.  As far as I know, clickhouse-local may have similar ability, but it's hard to be embedded in spark/flink/mapreduce program. Leveraging merge tree engine's library with JNI may be the only choice for us. Is there any better solution to generate mergetree files in spark/flink/mapreduce?

**Comment by alexey-milovidov** [comment]
It's trivial to have separate read and write nodes using shared storage (ClickHouse over s3).

**Comment by tchaton** [comment]
> It's trivial to have separate read and write nodes using shared storage (ClickHouse over s3).

Hey @alexey-milovidov How do you do that ?
