### ISSUE TITLE
A setting `log_comment`

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#18494]
**Describe the solution you'd like**
Add a setting `log_comment`. It can be set to arbitrary string no longer than `max_query_size`.
If this setting is set, it will be logged along with query in a form `comment: ...`.
It will be also written to the `system.query_log` table to a separate column `comment String` (thought it's slightly redundant as we already write all settings to the `Settings Nested(Names String, Values String)`).

**Use case**
Use it in `clickhouse-test`. Quickly select queries from `system.query_log` related to the test. Server logs will be also more easy readable.

**Comment by TszKitLo40** [comment]
I am new here and want to try this issue, but I have some questions.
1. Do we just need to add the setting `log_comment`?
2. Have been the implementation of logging to the `system.query_log` and `comment: ...` already implemented?

**Comment by alexey-milovidov** [comment]
@TszKitLo40 

> Do we just need to add the setting log_comment?

Yes. And implement the corresponding behaviour.

> Have been the implementation of logging to the system.query_log and comment: ... already implemented?

No, we need to add it. See `executeQuery.h/cpp` for `static void logQuery` and `QueryLog.h`.

**Comment by TszKitLo40** [comment]
So we need to do the follow things:
1. Add the setting `log_comment` and implement the corresponding behavior.
2. The corresponding behavior should be implemented in `executeQuery.h/cpp` and `QueryLog.h`.
Do you think I have understood clearly?

**Comment by alexey-milovidov** [comment]
Yes, absolutely.

**Comment by TszKitLo40** [comment]
I want to have a try. (btw, which file about the setting `log_comment` can I refer to?)

**Comment by alexey-milovidov** [comment]
Ok.

`Interpreters/Settings.h`

**Comment by ucasFL** [comment]
> Ok.
> 
> `Interpreters/Settings.h`

BTW, it's `Core/Settings.h`
