### ISSUE TITLE
High level test coverage with factories.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#18495]
**Describe the solution you'd like**

All Factories (e.g. FunctionFactory, StorageFactory...) will add names of created objects into query context.
These names will be written into `system.query_log` table, so we will be able to determine:

- what functions query has been used;
- what storage engines query has been used;
- what data types query has been used;
- etc...

**Use case**

For development: find entities that are not covered by tests.
For documentation: for every entity add a link to existing tests, sorted by something like TF*IDF metric (more specific tests first).

**Additional info**

We already have similar information in query_log for settings and for databases/tables/columns.

**Alternatives**

Low level (source code) test coverage on per-test basis. It will be implemented in a separate task.

**Comment by kssenii** [comment]
Taking this task.
