### ISSUE TITLE
Debug assertion in Map datatype

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#18492]
```
SELECT
    CAST(([2, 1, 1023], ['', '']), 'Map(UInt8, String)') AS map,
    map[10]
```

Triggers `Assertion 'n < size()' failed` in `DB::ColumnString::operator[](unsigned long)`
https://clickhouse-test-reports.s3.yandex.net/18481/64c4ade5b0e0c9a13d6c2475431daf431fc97554/fuzzer/fuzzer.log

Introduced here: #17829
First found here: #18481

**Comment by hexiaoting** [comment]
The error was different when I run this SQL:
```
ClickHouse client version 20.13.1.1.
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 20.13.1 revision 54443.

dell123 :) SELECT　    CAST(([2, 1, 1023], ['', '']), 'Map(UInt8, String)') AS map,　    map[10];

Received exception from server (version 20.13.1):
Code: 1001. DB::Exception: Received from localhost:9000. DB::Exception: std::length_error: basic_string.

0 rows in set. Elapsed: 0.004 sec.

dell123 :) SELECT　    CAST(([2, 1, 1023], ['', '']), 'Map(UInt8, String)') AS map,　    map[10];

Received exception from server (version 20.13.1):
Code: 241. DB::Exception: Received from localhost:9000. DB::Exception: Memory limit (for query) exceeded: would use 128.00 TiB (attempt to allocate chunk of 140737490507006 bytes), maximum: 93.13 GiB.

0 rows in set. Elapsed: 0.003 sec.

dell123 :)
```

In addition, when cast a tuple to map type, in the current version, we assume tuple has two elements and these two elements  have the same size.

Of course we can add the default value when the second element's value are not all specified.

**Comment by alexey-milovidov** [comment]
It because you are running release build - it has no assertions and you get errors that are much worse.

**Comment by alexey-milovidov** [comment]
> Of course we can add the default value when the second element's value are not all specified.

No, just need to throw exceptions that arrays are not of the same size.
