### ISSUE TITLE
Virtual Memory Usage Difference by Versions

### ISSUE THREAD

**Issue by tkionshao** [ClickHouse/ClickHouse#18500]
Hi Clickhouse Team,

This is a DBA team which is using Clickhouse with huge throughput(4.6 Billions per day) for worldwide Telekom companies with a good performance for a long time. Recently, we want to use newer version of Clickhouse for kind of good feature. But we found that when we monitor performance and compare by project, there is a different in Virtual Memory, I want to ask how to explain the usage of them, thanks.

![20201225_095523](https://user-images.githubusercontent.com/35727603/103114479-b4ab5500-4699-11eb-9829-72fd8ce564ea.jpg)

![20201225_095510](https://user-images.githubusercontent.com/35727603/103114490-bd9c2680-4699-11eb-9b0b-12079d74a2ca.jpg)

#4394

**Comment by alexey-milovidov** [comment]
The difference in virtual memory usage does not matter, only physical memory usage matters.
(possible reasons: we allocate memory in a different way, probably more efficiently, by reserving more virtual memory pages)

Another possible reason: #11139

If the difference in physical memory usage is in range of megabytes, not gigabytes, it is not worth investigating.

Recently we have checked the difference in physical memory usage between 20.3 and 20.8 on some user scenario and have found that it was even lowered. We also check for the difference in memory usage (RSS) in per-commit performance tests.
