### ISSUE TITLE
4GB ram, clickhouse distributed table insert select syntax encounter OOM

### ISSUE THREAD

**Issue by wu-johnson** [ClickHouse/ClickHouse#18506]
I have a clickhouse cluster with 3 docker nodes, each docker has 4GB RAM, when using `insert select `  query to handle clickhouse cluster table, it throws OOM. the following is the detail. how can i fix this for just 4GB RAM?

**local table(has 260 tag columns(tag_001 ~ tag_260):**
CREATE TABLE default.t_local
(
    ds UInt32,
    user_id String,
    tag_001 SimpleAggregateFunction(anyLast, Nullable(String)),
    tag_002 SimpleAggregateFunction(anyLast, Nullable(String)),
    tag_003 SimpleAggregateFunction(anyLast, Nullable(String)),
    tag_004 SimpleAggregateFunction(anyLast, Nullable(String)),
    tag_005 SimpleAggregateFunction(anyLast, Nullable(String)),
    tag_006 SimpleAggregateFunction(anyLast, Nullable(String)),
    tag_007 SimpleAggregateFunction(anyLast, Nullable(String)),
    tag_008 SimpleAggregateFunction(anyLast, Nullable(String)),
    tag_009 SimpleAggregateFunction(anyLast, Nullable(String)),
    ...,
    tag_260 SimpleAggregateFunction(anyLast, Nullable(String)),
)
ENGINE = ReplicatedAggregatingMergeTree('/clickhouse/tables/{shard}/t_local', '{replica}')
PARTITION BY ds
ORDER BY (ds, user_id)
SETTINGS index_granularity = 8192

**cluster table(has 260 tag columns(tag_001 ~ tag_260):**
CREATE TABLE default.t_cluster 
(
ds UInt32,
user_id String,
tag_001 SimpleAggregateFunction(anyLast, Nullable(String)),
tag_002 SimpleAggregateFunction(anyLast, Nullable(String)),
tag_003 SimpleAggregateFunction(anyLast, Nullable(String)),
tag_004 SimpleAggregateFunction(anyLast, Nullable(String)),
tag_005 SimpleAggregateFunction(anyLast, Nullable(String)),
tag_006 SimpleAggregateFunction(anyLast, Nullable(String)),
tag_007 SimpleAggregateFunction(anyLast, Nullable(String)),
tag_008 SimpleAggregateFunction(anyLast, Nullable(String)),
tag_009 SimpleAggregateFunction(anyLast, Nullable(String)),
...,
tag_260 SimpleAggregateFunction(anyLast, Nullable(String))
)
ENGINE = Distributed('cluster', 'default', 't_local', sipHash64(user_id))

**table t_profile has 23,000,000 records**
execute sql:

set aggregation_memory_efficient_merge_threads=2;
set max_distributed_connections=4;
set max_insert_threads=0;
set max_bytes_before_external_group_by=500000000;
set max_bytes_before_external_sort=500000000;
set max_memory_usage=2000000000;
set min_insert_block_size_rows = 200000;
insert into t_cluster
SELECT 
    ds,
    user_id,
    tag_001
FROM 
(
    SELECT 
        '20201222' AS ds,
        user_id,
        'male' AS tag_001
    FROM 
    (
        SELECT user_id
        FROM t_profile
        WHERE (ds = 20201221) AND (sex = '1761')
    )
    UNION ALL
    SELECT 
        '20201222' AS ds,
        user_id,
        'female' AS tag_001
    FROM 
    (
        SELECT user_id
        FROM t_profile
        WHERE (ds = 20201221) AND (sex = '1762')
    )
    UNION ALL
    SELECT 
        '20201222' AS ds,
        user_id,
        'unknown' AS tag_001
    FROM 
    (
        SELECT user_id
        FROM t_profile
        WHERE (ds = 20201221) AND (sex = '0')
    )
)

**Comment by den-crane** [comment]
```
* Add 16GB swap.
* set <mark_cache_size> to 500MB (config.xml)
* set <mlock_executable> to false (config.xml)
* set max_block_size=16000 (users.xml)
* set min_compress_block_size / max_compress_block_size = 256 kb (users.xml)
* set max_threads=1

```

**Comment by filimonov** [comment]
cross-reference older discussion: https://github.com/ClickHouse/ClickHouse/issues/1531

**Comment by filimonov** [comment]
For lot of columns https://github.com/ClickHouse/ClickHouse/issues/6943
