### ISSUE TITLE
Avro Confluent format_avro_schema_registry_url multiple values

### ISSUE THREAD

**Issue by ccellado** [ClickHouse/ClickHouse#18517]
**Use case**
With Apache Flink we fetch avro schema using a list of urls, as there are several in our projects.

**Describe the solution you'd like**
allow format_avro_schema_registry_url to parse multiple urls

**Describe alternatives you've considered**
Right now you have to now of find which node in your system holds which schema.

**Comment by filimonov** [comment]
It's just for HA? I.e. all registries are the same? 

Can you share some official docs / samples of how it was implemented in Flink (didn't find, sorry).

**Comment by ccellado** [comment]
I'm sorry, Flink indeed does not "smart select" from a list - you have pick one manually.

Closing the request.
