### ISSUE TITLE
Is it appropriate to deal with the sql ?

### ISSUE THREAD

**Issue by coderlongren** [ClickHouse/ClickHouse#18534]
My scenario is to analyze the data 
the sql is :
```sql
select material_id, sum(cost) as sum_cost from table where material_id in (id1, id2.....id100000) 
and time > time1 group by material_id order by sum_cost;
```
the material_id is Wide range.
I wonder if this is appropriate？

**Comment by coderlongren** [comment]
Data order of magnitude 20 million rows，

**Comment by alexey-milovidov** [comment]
Yes, having 100 000 elements in right hand side of IN is totally Ok. You only have to increase `max_query_size` setting.

As an alternative you can also write ids to a temporary table and use `IN (SELECT ...)` or use external data for query.

20 million records is nothing for ClickHouse, queries will be processed instantly.
