### ISSUE TITLE
intersects next part

### ISSUE THREAD

**Issue by Sallery-X** [ClickHouse/ClickHouse#18559]
(you don't have to strictly follow this form)

**Describe the bug**
2020.12.28 10:29:03.486666 [ 62 ] {} <Error> bc_online.ck_content_basic_info_pvuv: DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Code: 49, e.displayText() = DB::Exception: Part fd14b7e6c0c6610e8422d56580fb952a_1_10_2 intersects next part fd14b7e6c0c6610e8422d56580fb952a_6_30_3 (state Committed). It is a bug., Stack trace (when copying this message, always include the lines below)
**How to reproduce**
* Which ClickHouse server version to use
20.8.2.3

**Error message and/or stacktrace**
2020.12.28 10:29:03.486666 [ 62 ] {} <Error> bc_online.ck_content_basic_info_pvuv: DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Code: 49, e.displayText() = DB::Exception: Part fd14b7e6c0c6610e8422d56580fb952a_1_10_2 intersects next part fd14b7e6c0c6610e8422d56580fb952a_6_30_3 (state Committed). It is a bug., Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x1a80ae30 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xff9e75d in /usr/bin/clickhouse
2. ? @ 0x17bf5b92 in /usr/bin/clickhouse
3. DB::MergeTreeData::renameTempPartAndReplace(std::__1::shared_ptr<DB::IMergeTreeDataPart>&, SimpleIncrement*, DB::MergeTreeData::Transaction*, std::__1::unique_lock<std::__1::mutex>&, std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeDataPart const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeDataPart const> > >*) @ 0x17bea1cf in /usr/bin/clickhouse
4. DB::MergeTreeData::renameTempPartAndReplace(std::__1::shared_ptr<DB::IMergeTreeDataPart>&, SimpleIncrement*, DB::MergeTreeData::Transaction*) @ 0x17beabec in /usr/bin/clickhouse
5. DB::StorageReplicatedMergeTree::fetchPart(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, unsigned long, std::__1::shared_ptr<zkutil::ZooKeeper>) @ 0x17a494c6 in /usr/bin/clickhouse
6. DB::StorageReplicatedMergeTree::executeFetch(DB::ReplicatedMergeTreeLogEntry&) @ 0x17a4b7bd in /usr/bin/clickhouse
7. DB::StorageReplicatedMergeTree::executeLogEntry(DB::ReplicatedMergeTreeLogEntry&) @ 0x17a4ddb1 in /usr/bin/clickhouse
8. ? @ 0x17a4e1ad in /usr/bin/clickhouse
9. DB::ReplicatedMergeTreeQueue::processEntry(std::__1::function<std::__1::shared_ptr<zkutil::ZooKeeper> ()>, std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&, std::__1::function<bool (std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&)>) @ 0x17daafa2 in /usr/bin/clickhouse
10. DB::StorageReplicatedMergeTree::queueTask() @ 0x17a011ce in /usr/bin/clickhouse
11. DB::BackgroundProcessingPool::workLoopFunc() @ 0x17b7efd3 in /usr/bin/clickhouse
12. ? @ 0x17b7f902 in /usr/bin/clickhouse
13. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xffce517 in /usr/bin/clickhouse
14. ? @ 0xffccb53 in /usr/bin/clickhouse
15. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
16. __clone @ 0x122103 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
 (version 20.8.2.3 (official build))

**Additional context**

**Comment by den-crane** [comment]
You  should upgrade to 20.8.11.17.

Please show the output of 
`zgrep -E 'fd14b7e6c0c6610e8422d56580fb952a_1_10_2|fd14b7e6c0c6610e8422d56580fb952a_6_30_3' /var/log/clickhouse-server/clickhouse-server.log*`

**Comment by Sallery-X** [comment]
2020.12.28 11:41:11.482630 [ 65 ] {} <Error> bc_online.ck_content_basic_info_pvuv: DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Code: 49, e.displayText() = DB::Exception: Part fd14b7e6c0c6610e8422d56580fb952a_1_10_2 intersects next part fd14b7e6c0c6610e8422d56580fb952a_6_30_3 (state Committed). It is a bug., Stack trace (when copying this message, always include the lines below):
2020.12.28 11:51:12.080920 [ 70 ] {} <Warning> bc_online.ck_content_basic_info_pvuv: Part fd14b7e6c0c6610e8422d56580fb952a_6_6_1 is covered by fd14b7e6c0c6610e8422d56580fb952a_6_30_3 but should be merged into fd14b7e6c0c6610e8422d56580fb952a_1_10_2. This shouldn't happen often.
2020.12.28 11:51:26.938902 [ 70 ] {} <Error> bc_online.ck_content_basic_info_pvuv: DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Code: 49, e.displayText() = DB::Exception: Part fd14b7e6c0c6610e8422d56580fb952a_1_10_2 intersects next part fd14b7e6c0c6610e8422d56580fb952a_6_30_3 (state Committed). It is a bug., Stack trace (when copying this message, always include the lines below):
2020.12.28 11:51:27.039962 [ 57 ] {} <Warning> bc_online.ck_content_basic_info_pvuv: Part fd14b7e6c0c6610e8422d56580fb952a_6_6_1 is covered by fd14b7e6c0c6610e8422d56580fb952a_6_30_3 but should be merged into fd14b7e6c0c6610e8422d56580fb952a_1_10_2. This shouldn't happen often.
2020.12.28 11:51:41.205911 [ 57 ] {} <Error> bc_online.ck_content_basic_info_pvuv: DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Code: 49, e.displayText() = DB::Exception: Part fd14b7e6c0c6610e8422d56580fb952a_1_10_2 intersects next part fd14b7e6c0c6610e8422d56580fb952a_6_30_3 (state Committed). It is a bug., Stack trace (when copying this message, always include the lines below):
2020.12.28 12:01:41.962020 [ 82 ] {} <Warning> bc_online.ck_content_basic_info_pvuv: Part fd14b7e6c0c6610e8422d56580fb952a_6_6_1 is covered by fd14b7e6c0c6610e8422d56580fb952a_6_30_3 but should be merged into fd14b7e6c0c6610e8422d56580fb952a_1_10_2. This shouldn't happen often.
2020.12.28 12:01:57.150886 [ 82 ] {} <Error> bc_online.ck_content_basic_info_pvuv: DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Code: 49, e.displayText() = DB::Exception: Part fd14b7e6c0c6610e8422d56580fb952a_1_10_2 intersects next part fd14b7e6c0c6610e8422d56580fb952a_6_30_3 (state Committed). It is a bug., Stack trace (when copying this message, always include the lines below):

**Comment by Sallery-X** [comment]
> You should upgrade to 20.8.11.17.
> 
> Please show the output of
> `zgrep -E 'fd14b7e6c0c6610e8422d56580fb952a_1_10_2|fd14b7e6c0c6610e8422d56580fb952a_6_30_3' /var/log/clickhouse-server/clickhouse-server.log*`

it doesn't work

**Comment by den-crane** [comment]
@Sallery-X Do you have logs with messages about "fd14b7e6c0c6610e8422d56580fb952a_1_10_2|fd14b7e6c0c6610e8422d56580fb952a_6_30_3" before time 2020.12.28 10:29:03.486666

**Comment by Sallery-X** [comment]
> @Sallery-X Do you have logs with messages about "fd14b7e6c0c6610e8422d56580fb952a_1_10_2|fd14b7e6c0c6610e8422d56580fb952a_6_30_3" before time 2020.12.28 10:29:03.486666 ?

2020.12.28 11:41:11.482630 [ 65 ] {} bc_online.ck_content_basic_info_pvuv: DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Code: 49, e.displayText() = DB::Exception: Part fd14b7e6c0c6610e8422d56580fb952a_1_10_2 intersects next part fd14b7e6c0c6610e8422d56580fb952a_6_30_3 (state Committed). It is a bug., Stack trace (when copying this message, always include the lines below):
2020.12.28 11:51:12.080920 [ 70 ] {} bc_online.ck_content_basic_info_pvuv: Part fd14b7e6c0c6610e8422d56580fb952a_6_6_1 is covered by fd14b7e6c0c6610e8422d56580fb952a_6_30_3 but should be merged into fd14b7e6c0c6610e8422d56580fb952a_1_10_2. This shouldn't happen often.
2020.12.28 11:51:26.938902 [ 70 ] {} bc_online.ck_content_basic_info_pvuv: DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Code: 49, e.displayText() = DB::Exception: Part fd14b7e6c0c6610e8422d56580fb952a_1_10_2 intersects next part fd14b7e6c0c6610e8422d56580fb952a_6_30_3 (state Committed). It is a bug., Stack trace (when copying this message, always include the lines below):
2020.12.28 11:51:27.039962 [ 57 ] {} bc_online.ck_content_basic_info_pvuv: Part fd14b7e6c0c6610e8422d56580fb952a_6_6_1 is covered by fd14b7e6c0c6610e8422d56580fb952a_6_30_3 but should be merged into fd14b7e6c0c6610e8422d56580fb952a_1_10_2. This shouldn't happen often.
2020.12.28 11:51:41.205911 [ 57 ] {} bc_online.ck_content_basic_info_pvuv: DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Code: 49, e.displayText() = DB::Exception: Part fd14b7e6c0c6610e8422d56580fb952a_1_10_2 intersects next part fd14b7e6c0c6610e8422d56580fb952a_6_30_3 (state Committed). It is a bug., Stack trace (when copying this message, always include the lines below):
2020.12.28 12:01:41.962020 [ 82 ] {} bc_online.ck_content_basic_info_pvuv: Part fd14b7e6c0c6610e8422d56580fb952a_6_6_1 is covered by fd14b7e6c0c6610e8422d56580fb952a_6_30_3 but should be merged into fd14b7e6c0c6610e8422d56580fb952a_1_10_2. This shouldn't happen often.
2020.12.28 12:01:57.150886 [ 82 ] {} bc_online.ck_content_basic_info_pvuv: DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Code: 49, e.displayText() = DB::Exception: Part fd14b7e6c0c6610e8422d56580fb952a_1_10_2 intersects next part fd14b7e6c0c6610e8422d56580fb952a_6_30_3 (state Committed). It is a bug., Stack trace (when copying this message, always include the lines below):

**Comment by tnaumova-ebay** [comment]
Hi, we're using: 
`version 20.9.3.45 (official build).`
And having similar issue:

`2021.01.26 10:48:12.315374 [ 23422 ] {} <Error> XXXX.XXXX: DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Code: 49, e.displayText() = DB::Exception: Part 202101-32_338783_338792_1_401976 intersects previous part 202101-32_338745_338791_2_401976 (state Committed). It is a bug., Stack trace (when copying this message, always include the lines below):`
and then
`2021.01.26 10:48:10.827570 [ 23428 ] {} <Error> XXXX.XXXX: DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Code: 49, e.displayText() = DB::Exception: Part 202101-32_338783_338792_1_401976 intersects previous part 202101-32_338745_338791_2_401976 (state Committed). It is a bug., Stack trace (when copying this message, always include the lines below):`

Please advise.

**Comment by Sallery-X** [comment]
> `2021.01.26 10:48:10.827570 [ 23428 ] {} <Error> XXXX.XXXX: DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Code: 49, e.displayText() = DB::Exception: Part 202101-32_338783_338792_1_401976 intersects previous part 202101-32_338745_338791_2_401976 (state Committed). It is a bug., Stack trace (when copying this message, always include the lines below):`

try to rewrite the table

**Comment by alexey-milovidov** [comment]
This can be fixed by a sequence of

ALTER TABLE ... DETACH PARTITION ...
ALTER TABLE ... ATTACH PARTITION ...

commands for the affected table.

**Comment by karthik-thiyagarajan** [comment]
> This can be fixed by a sequence of
> 
> ALTER TABLE ... DETACH PARTITION ... ALTER TABLE ... ATTACH PARTITION ...
> 
> commands for the affected table.

Can you help me how to do this attach table / detach table when the clickhouse server itself is not starting as it crashes in 23.12 version with the same error as "Part 20240908_241972_241980_1 intersects previous part 20240908_241970_241985_1. It is a bug or a result of manual intervention in the server or ZooKeeper data: Cannot attach table"). Also, if there are multiple parts having this problem, how to identify such issues through some commands when the server is not starting up. Please help.
