### ISSUE TITLE
[Guidance] Table Migration (due to changing primary key)

### ISSUE THREAD

**Issue by arpowers** [ClickHouse/ClickHouse#18551]
Working with Clickhouse and all is going well, but today I ran into the problem of needing to a change the name of a primary key on a table. 

After some research, it appears that currently a migration of data to a new table is needed to do this. It would be helpful to have some basic syntax and guidelines for how a table migration should happen with Clickhouse. 

- What is the preferred approach for a non-zookeeper managed server?

**Comment by den-crane** [comment]
Create a new table.` insert into new select * from old`

**Comment by arpowers** [comment]
@den-crane simple enough! thanks
