### ISSUE TITLE
There are so many versions, are all the versions forward compatible, and what is the difference between the different versions?

### ISSUE THREAD

**Issue by Sallery-X** [ClickHouse/ClickHouse#18558]

**Comment by den-crane** [comment]
The last 3 versions are supported: 20.12.4.5 , 20.11.6.6, 20.10.7.4, plus two LTS: 20.8.11.17, 20.3.21.2
The first number - 20 -- year, the second major release, all other bugfix releases.

If you just start to use CH, then use the latest stable release **20.12.4.5.**

Changelog: https://github.com/ClickHouse/ClickHouse/blob/master/CHANGELOG.md
