### ISSUE TITLE
poco cmake error

### ISSUE THREAD

**Issue by herbertluo** [ClickHouse/ClickHouse#18569]
`contrib/poco/build_cmake.sh`

**Operating system**
Linux VM_116_204_centos 3.10.107-1

**Cmake version**
3.19

**Ninja version**
1.9.0

**Compiler name and version**
gcc 10.2.0
g++ 10.2.0

**Full cmake and/or ninja output**
-- The C compiler identification is GNU 10.2.0
-- The CXX compiler identification is GNU 10.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/local/bin/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/local/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Poco package version: 1.9.3
-- Setting Poco build type - RelWithDebInfo
-- Building dynamic libraries
-- Building without tests & samples
-- Using internal sqlite, zlib, pcre, expat, ...
-- Looking for pthread_setaffinity_np in pthread
-- Looking for pthread_setaffinity_np in pthread - found
-- Performing Test HAVE_THREE_PARAM_SCHED_SETAFFINITY
-- Performing Test HAVE_THREE_PARAM_SCHED_SETAFFINITY - Success
-- Platform has THREE PARAM at PTHREAD_SETAFFINITY_NP
-- Found OpenSSL: /usr/lib64/libcrypto.so (found version "1.0.2k")  
-- Found MySQL Include directory: /usr/include/mysql  library directory: /usr/lib64/mysql
-- MySQL Support Enabled
-- Could NOT find ODBC (missing: ODBC_INCLUDE_DIRECTORIES ODBC_LIBRARIES) 
-- ODBC Support Disabled - no ODBC runtime
-- CMake 3.19.2 successfully configured Poco using Unix Makefiles generator
-- Installation target path: /usr/local
-- C_FLAGS:  = -Wno-sign-compare -fno-strict-aliasing -Wno-unknown-pragmas
-- CMAKE_C_FLAGS_DEBUG:=-g   -D_DEBUG
-- CMAKE_C_FLAGS_RELEASE:=-O3 -DNDEBUG
-- CMAKE_C_FLAGS_MINSIZEREL:=-Os -DNDEBUG
-- CMAKE_C_FLAGS_RELWITHDEBINFO:=-O2 -g -DNDEBUG
-- 
-- 
-- CXX_FLAGS:= -Wno-sign-compare  -fno-strict-aliasing -Wno-unknown-pragmas -Wno-non-virtual-dtor
-- CMAKE_CXX_FLAGS_DEBUG:=-g -D_DEBUG
-- CMAKE_CXX_FLAGS_RELEASE:=-O3 -DNDEBUG
-- CMAKE_CXX_FLAGS_MINSIZEREL:=-Os -DNDEBUG
-- CMAKE_CXX_FLAGS_RELWITHDEBINFO:=-O2 -g -DNDEBUG
-- Building: Encodings
-- Building: XML
-- Building: JSON
-- Building: Util
-- Building: Net
-- Building: MongoDB
-- Building: Redis
-- Building: NetSSL_OpenSSL
-- Building: Crypto
-- Building: Data
-- Building: Zip
-- Building: PageCompiler
-- Building: File2Page
-- Configuring done
CMake Error at Foundation/CMakeLists.txt:166 (add_library):
  Cannot find source file:

    include/Poco/zconf.h

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .ispc

CMake Error at Foundation/CMakeLists.txt:166 (add_library):
  No SOURCES given to target: Foundation

CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by alexey-milovidov** [comment]
`contrib` libraries are not meant to be built separately. They are build with ClickHouse.
