### ISSUE TITLE
Data lost when using Kafka engine

### ISSUE THREAD

**Issue by MaryamJFard** [ClickHouse/ClickHouse#18563]
**Describe the unexpected behaviour**
I consumed one Kafka topic with 2 Kafka engine tables and 2 consumer MVs and finally 2 MergeTree() tables in Clickhouse, everything was fine for a couple of days but one day, at just one minute, we observed a difference in the amount of records in 2 tables; it seemed that unlike that everything was the same for the 2 pipelines, one of them experienced data lost. In order to find the cause of this data lost, clickhouse-server.log and clickhouse-server.err.log files were checked there were no errors for that special minute. Also resource utilizations was checked, CPU busy, load and RAM memory were normal. 

**How to reproduce**
* CH version: 20.6.3.28
* There is no aggregation in MVs creation, a simple select.
* The enginge used to create final tables: MergeTree() (instead of using replacing engines that may lead to data being missed)

**Expected behavior**
The amount of records in both tables should always be the same.

**Error message and/or stacktrace**
No errors were raised in any stage of the pipelines. 

**Help me if you know**
What is the next step in order to figure out the cause of this problem? or can one say because of similar issues Kafka engines are not reliable?

**Comment by filimonov** [comment]
> I consumed one Kafka topic with 2 Kafka engine tables and 2 consumer MVs and finally 2 MergeTree() tables in Clickhouse, 

Can you share the fragment of your schema? (I don't care about real column/table names)

>  or can one say because of similar issues Kafka engines are not reliable?

We expect to have at-least-once. So duplicates may happen, but missing data - not. 

If you can share the logs (clickhouse-server.log trace log level, which is the default) in a problematic minute (+ few minutes around) I can try to look for anomalies.

Also please update to one of the supported versions, for example, update to 20.8.11 will be straight-forward.

**Comment by MaryamJFard** [comment]
**The table**

CREATE TABLE db.mytable
(
    `clmn_1` UInt64,
    `clmn_2` UInt64,
    `clmn_3` Int8,
    `clmn_4` Nullable(String),
    `clmn_5` DateTime,
    `clmn_6` Date,
    `clmn_7` DateTime,
    `clmn_8` DateTime,
    `clmn_9` DateTime
)
ENGINE = MergeTree()
ORDER BY clmn_1
SETTINGS index_granularity = 8192

**And the errors from clickhouse-server.log:**


<Error> executeQuery: Code: 24, e.displayText() = DB::Exception: Cannot write to ostream at offset: While executing ODBCDriver2BlockOutputFormat (version 20.6.3.28 (official build)) (in query:  SELECT **** ), Stack trace (when copying this message, always include the lines below):
<Error> DynamicQueryHandler: Code: 24, e.displayText() = DB::Exception: Cannot write to ostream at offset : While executing ODBCDriver2BlockOutputFormat, Stack trace (when copying this message, always include the lines below):
<Error> DynamicQueryHandler: Cannot send exception to client: Code: 24, e.displayText() = DB::Exception: Cannot write to ostream at offset , Stack trace (when copying this message, always include the lines below):
<Warning> TCPHandler: Client has not sent any data.

@filimonov 
As far as I know, this error is caused by client side disconnect on http protocol, for example due to read timeout on client side. So server can't write any more to the socket after client close that; which means it is not relevant to my issue.

**Comment by filimonov** [comment]
> ENGINE = MergeTree()

I guess you have 2 Engine=Kafka tables, 2 MV and 2 target tables... I need schema of all 6. Especially interested in SETTINGS of engine=kafka. 

> And the errors from clickhouse-server.log

Nothing related to Kafka. I need not only errors but trace logs. 


> As far as I know, this error is caused by client side disconnect on http protocol, for example due to read timeout on client side. So server can't write any more to the socket after client close that; which means it is not relevant to my issue.

Flushing from engine=Kafka to MergeTree has does not depend in any way to http or client connections.

**Comment by MaryamJFard** [comment]
Yes you are right there are 6 tables; both of the target tables are the same as the one I pasted here to my previous comment, so in this one, the following is 2 Engine=Kafka tables and 2 MV:

CREATE TABLE db.kafka_1
(
    `clmn_1` UInt64,
    `clmn_2` UInt64,
    `clmn_3` Int8,
    `clmn_4` Nullable(String),
    `clmn_5` String,
    `clmn_7` String
)
ENGINE = Kafka('host:port', 'topic1', 'group_name_0', 'AvroConfluent')

CREATE TABLE db.kafka_2
(
    `clmn_1` UInt64,
    `clmn_2` UInt64,
    `clmn_3` Int8,
    `clmn_4` Nullable(String),
    `clmn_5` String,
    `clmn_7` String
)
ENGINE = Kafka('host:port', 'topic1', 'group_name_1', 'AvroConfluent')


CREATE MATERIALIZED VIEW db.consumer_1 TO db.mytable_1
(
    `clmn_1` UInt64,
    `clmn_2` UInt64,
    `clmn_3` Int8,
    `clmn_4` Nullable(String),
    `clmn_5` DateTime,
    `clmn_6` Date,
    `clmn_7` DateTime,
    `clmn_8` DateTime,
    `clmn_9` DateTime
) AS
SELECT 
    clmn_1,
    clmn_2,
    clmn_3,
    clmn_4,
    toDateTime(clmn_5) AS clmn_5,
    toDate(clmn_5) AS clmn_6,
    toDateTime(clmn_7) AS clmn_7,
    now() AS clmn_8,
    ***** AS clmn_9
FROM db.kafka_1

CREATE MATERIALIZED VIEW db.consumer_2 TO db.mytable_2
(
    `clmn_1` UInt64,
    `clmn_2` UInt64,
    `clmn_3` Int8,
    `clmn_4` Nullable(String),
    `clmn_5` DateTime,
    `clmn_6` Date,
    `clmn_7` DateTime,
    `clmn_8` DateTime,
    `clmn_9` DateTime
) AS
SELECT 
    clmn_1,
    clmn_2,
    clmn_3,
    clmn_4,
    toDateTime(clmn_5) AS clmn_5,
    toDate(clmn_5) AS clmn_6,
    toDateTime(clmn_7) AS clmn_7,
    now() AS clmn_8,
    ***** AS clmn_9
FROM db.kafka_2

@filimonov 
I sent you all the logs for that special minute not only the errors.

**Comment by filimonov** [comment]
> I sent you all the logs for that special minute not only the errors.

It seems you decreased log level from default trace to error.

Please enable trace  logging and try to reproduce the problem.

**Comment by filimonov** [comment]
@MaryamJFard

If you just compare the numbers from 2 tables consuming the same topic - why do you think one of table misses some data?
I would suspect first the other have some duplicates (duplicates are expected in some cornet cases). 

Without trace logs, I can't do anything with that issue.
