### ISSUE TITLE
Write Roaring Bitmap data from Spark to CH

### ISSUE THREAD

**Issue by zhou-binbin** [ClickHouse/ClickHouse#18589]
I want to write roaringbitmap data(java) into CK by Spark,I try it but failed,have CK support it ,if not ,have future plan?

**Comment by abyss7** [comment]
Please, provide more information on how exactly you are trying to store the data into CH. Also provide CH version.

**Comment by zhou-binbin** [comment]
> Please, provide more information on how exactly you are trying to store the data into CH. Also provide CH version.

First of all,Thank you for your answer,The more information of the question as follows:

1. the CK table :
CREATE TABLE app_userid_bit_ch
(
    `appname` String,
    `uidbit` AggregateFunction(groupBitmap, UInt64)
)
ENGINE = AggregatingMergeTree()
ORDER BY appname
SETTINGS index_granularity = 128
2. the Spark main program statements：
    `val prop=new Properties()
    val ckDriver="ru.yandex.clickhouse.ClickHouseDriver"
    prop.put("driver",ckDriver)
    prop.put("user",user)
    prop.put("password",password)
    import spark.implicits._
    val ckdata = sc.textFile(args(0)).map(x=>{
      val y = x.split(",")
      val appname = y(0)
      val uidbitmap = new RoaringBitmap()
      y(1).split(":").foreach(k=>uidbitmap.add(k.toInt))
      (appname,uidbitmap)
    }).toDF()
    ckdata.write.mode(saveMode="append")
      .option("batchsize", "200")
      .option("isolationLevel", "NONE") 
      .option("numPartitions", "1") 
      .jdbc(url, table,prop)`

3. the CH version is 20.8.3.18

I want to write Roaring Bitmap data into CK by spark,use java org.roaringbitmap.RoaringBitmap but failed. have CK support it ,if not ,have future plan?At present, we can only import the original ID data  into CK,and then build RBM structure by creating materialized view. But the amount of original ID data is often very large.

**Comment by den-crane** [comment]
@zhou-binbin you should open a ticket against https://github.com/ClickHouse/clickhouse-jdbc
your question is not related to CH server.
