### ISSUE TITLE
Evaluate another implementation of `memcpy`

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#18583]
https://github.com/jart/cosmopolitan/blob/de09bec215675e9b0beb722df89c6f794da74f3f/libc/nexgen32e/memcpy.S#L49

Note: it has some dependencies and requires initialization (to check for AVX2).

**Comment by jart** [comment]
I'm the author of the fast memcpy function. Let me know if there's anything I can do to support you.

**Comment by alexey-milovidov** [comment]
We may want to add
`.cfi_startproc`
`.cfi_endproc`
directives, so the function will be visible in profiler.

**Comment by alexey-milovidov** [comment]
@jart 

It's unclear where to plug in initialization code like calls to `_init_kHalfCache3`, `_init_kHalfCache3` and `memjmpinit` if we are using glibc (and not using startup code of cosmopolitan).

**Comment by alexey-milovidov** [comment]
Do I understand correctly that the asm code assumes specific kind of relocations: `kCpuids(%rip)` and have to be build or linked with specific options?

**Comment by alexey-milovidov** [comment]
Maybe if only thing that I want is memcpy, it will be simpler to rewrite the code instead of trying to plug it as is?

**Comment by jart** [comment]
You need `KEEP(*(SORT_BY_NAME(.init.*)))` in your linker script. If you're not using linker scripts, then you're probably better off defining a `.ctor` or `.init_array` function since those are defined by the standard GNU linker scripts.

**Comment by alexey-milovidov** [comment]
@jart I see that these sections are in the binary, but they are not called.
I tried to call them directly but the first attempt failed:

```
extern "C" void _init_kHalfCache3();
extern "C" void _init_kCpuids();

__attribute__((__constructor__)) void memcpy_init()
{
    _init_kHalfCache3();
    _init_kCpuids();
}
```

**Comment by alexey-milovidov** [comment]
@jart I'm trying to read the code of memcpy.

```
/// 8 remaining bytes
.L4:
    /// We will use rbx, so save the previous value on stack.
    push	%rbx

    /// The current four bytes
	mov	(%rsi),%ecx
	/// The latest four bytes
	mov	-4(%rsi,%rdx),%ebx
	mov	%ecx,(%rdi)
	mov	%ebx,-4(%rdi,%rdx)

	/// Restore the value of rbx and return
	jmp	1b

/// 4 remaining bytes
.L3:
    /// We will use rbx, so save the previous value on stack.
    push	%rbx

    /// The current two bytes
	mov	(%rsi),%cx
    /// The latest two bytes
	mov	-2(%rsi,%rdx),%bx
	mov	%cx,(%rdi)
	mov	%bx,-2(%rdi,%rdx)

	/// Restore the value of rbx and return
	jmp	1b
```

Do I understand that we copy by two halves only to support overlapping memory regions?
So, if I only need standard conforming memcpy, I can simplify this code?

**Comment by alexey-milovidov** [comment]
```
    pxor %xmm4,%xmm4
    pxor %xmm3,%xmm3
```

```
    vxorps %ymm4,%ymm4,%ymm4
    vxorps %ymm3,%ymm3,%ymm3
```

Why do we zeroing these registers before return? Is it required by ABI?

**Comment by alexey-milovidov** [comment]
@jart 

I see that there are AVX non-temporal stores: https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=stream_si256&expand=5673,5672,5673
but we don't use them.

Are they beneficial?

**Comment by alexey-milovidov** [comment]
@jart

I have managed to create standalone version of memcpy:
https://gist.github.com/alexey-milovidov/2c3b4e532b11bfb1708c89bccc7d6576

I tried to understand your code and write comments but I'm not sure if I get everthing right.
Could you please take a look at the comments in code?

Also I don't understand how it get managed for initialization functions like `_init_memcpy` to get called with correct arguments during startup. In my example I call it manually.

**Comment by jart** [comment]
Try this https://gist.github.com/jart/badea20bfc8fdbae3e9d2f662df64d35

**Comment by alexey-milovidov** [comment]
Thank you!

Do I understand correctly that the header file with macro is needed to use the fact that less number of registers are clobbered in memcpy than it's usually expected?

Sadly this macro is incompatible with libc++ code:
```
/home/milovidov/work/ClickHouse/contrib/libcxx/include/utility:973:12: error: expected unqualified-id
    _VSTD::memcpy(&__r, __p, sizeof(__r));
```

I will first try to use it without this header, as usual `memcpy` function call...

**Comment by alexey-milovidov** [comment]
If someone will try to write `std::memcpy` it will also fail.

**Comment by alexey-milovidov** [comment]
BTW, is there significant benefit of using AVX for memcpy?
We still use SSE4.2 in default build and we can use AVX and further only via dynamic dispatch.

(so, the initialization function can be still needed)

**Comment by jart** [comment]
The macro is optional and it has trickle-down benefits explained here: https://justine.lol/cosmopolitan/index.html

AVX is optional too. There's no consensus on whether or not it helps. It improves benchmark scores. However if you rarely use AVX in your program then you might incur penalties in the thousands of cycles when the CPU turns the AVX die space on and off to save power.

**Comment by alexey-milovidov** [comment]
Thanks. 

Btw, is it true that loop unrolling (I mean main loops with SSE/AVX copy) does not make sense?

**Comment by alexey-milovidov** [comment]
@jart First try either did not show performance improvement or we cannot observe it.
Maybe it because I have disabled AVX.

We can try better by the following way:
- make jump table not readonly;
- allow to rewrite it in runtime by simple function call (to avoid dealing with init mechanics);
- maybe add AVX non-temporary stores?

**Comment by jart** [comment]
My goal with providing assistance was to get you up and running quickly. You're the one who knows best how to correctly handle things like cpuid dispatching for your codebase. Enjoy Cosmopolitan MemCpy!

**Comment by alexey-milovidov** [comment]
AMD Ryzen does not have `erms` and in fact `rep movsb` is working up to 3 times slower than unrolled aligned SSE2 mov operations if copying within L1 or L2 cache using 16 threads.

**Comment by jart** [comment]
The implementation of this function in the Cosmopolitan codebase checks for ERMS via CPUID. You can implement that same check here too.

**Comment by alexey-milovidov** [comment]
@jart

I'm trying to evaluate various implementations of memcpy and found that the performance tests are not good enough.
We can test them just slightly better:

1. Test on various CPUs: at least several generations of Intel and latest generation of AMD.
2. Don't run a loop with identical size to copy, use randomized sizes from some distribution. When testing for small sizes, we should include a case when sizes are unpredictable.
3. Touch memory after copying, otherwise the test is unrealistic.
4. Test with doing copying from various number of threads.

There are cases when your memcpy is significantly slower (and there are other cases when it is faster) with the difference more than 1.5x in comparison to glibc's memcpy (even from glibc 2.2.5).

Maybe I will try to implement self-tuning algorithm with Bayesian Bandits as described here: https://habr.com/en/company/yandex/blog/457612/

**Comment by alexey-milovidov** [comment]
Raw data for memcpy benchmark:

[result_c5metal.txt](https://github.com/ClickHouse/ClickHouse/files/6142203/result_c5metal.txt) - baremetal, some modern Intel
[result_e5_2650v2.txt](https://github.com/ClickHouse/ClickHouse/files/6142205/result_e5_2650v2.txt) - baremetal, very old Intel
[result_yandex_cascade_lake.txt](https://github.com/ClickHouse/ClickHouse/files/6142208/result_yandex_cascade_lake.txt) - cloud, Intel Cascade Lake
[result_c5a_24xlarge.txt](https://github.com/ClickHouse/ClickHouse/files/6144918/result_c5a_24xlarge.txt) - cloud, AMD EPYC

**Comment by alexey-milovidov** [comment]
```
CREATE TABLE memcpy_benchmark
(
    `machine` LowCardinality(String),
    `name` LowCardinality(String),
    `size` UInt64,
    `iterations` UInt64,
    `threads` UInt16,
    `generator` UInt8,
    `memcpy` UInt8,
    `elapsed` UInt64
)
ENGINE = MergeTree
ORDER BY (machine, size, threads, generator, memcpy)
```

```
$ clickhouse-client --query "INSERT INTO memcpy_benchmark SELECT 'c5metal', * FROM input('name String, size UInt64, iterations UInt64, threads UInt16, generator UInt8, memcpy UInt8, elapsed UInt64') FORMAT TSV" < result_c5metal.txt 
$ clickhouse-client --query "INSERT INTO memcpy_benchmark SELECT 'e5_2650v2', * FROM input('name String, size UInt64, iterations UInt64, threads UInt16, generator UInt8, memcpy UInt8, elapsed UInt64') FORMAT TSV" < result_e5_2650v2.txt 
$ clickhouse-client --query "INSERT INTO memcpy_benchmark SELECT 'yandex_cascade_lake', * FROM input('name String, size UInt64, iterations UInt64, threads UInt16, generator UInt8, memcpy UInt8, elapsed UInt64') FORMAT TSV" < result_yandex_cascade_lake.txt 
$ clickhouse-client --query "INSERT INTO memcpy_benchmark SELECT 'c5a_24xlarge', * FROM input('name String, size UInt64, iterations UInt64, threads UInt16, generator UInt8, memcpy UInt8, elapsed UInt64') FORMAT TSV" < result_c5a_24xlarge.txt 
```
