### ISSUE TITLE
Best way to do data rebalancing in Clickhouse

### ISSUE THREAD

**Issue by clasnake** [ClickHouse/ClickHouse#18588]
As of now, there's no native support for auto-rebalancing for Clickhouse. Say we need to add new nodes to the Clickhouse cluster and need to do a rebalance to make sure all the data still distributes evenly across all the nodes. What is the recommended way to do this?

**Comment by den-crane** [comment]
There is no easy tricks.

You can use clickhouse-copier -- it will re-insert everything.
