### ISSUE TITLE
Cannot do rolling cluster upgrade from 20.9 to 20.12

### ISSUE THREAD

**Issue by simPod** [ClickHouse/ClickHouse#18609]
We wanted to do rolling cluster upgrade from 20.9 to 20.12.

Upgraded one replica to 20.12 and suddenly started seeing messages on second replica

> DB::Exception: Cannot parse input: expected 'quorum: ' before: 'merge_type: 2\n'

Same issue as in https://github.com/ClickHouse/ClickHouse/issues/17183

Does it mean rolling upgrade is not possible as all replicas must be on the same version?

**Comment by alexey-milovidov** [comment]
You can do rolling update, but replication will stop during update; while SELECT queries will continue to work and INSERT queries continue to write data that will be replicated later after upgrade is finished.

Recommendations:
- do not keep different versions of replicas for a long time;
- use your testing environment to check the update first.

**Comment by filimonov** [comment]
Caused by https://github.com/ClickHouse/ClickHouse/pull/14490/
