### ISSUE TITLE
Aggregate function `any` is slower than expected

### ISSUE THREAD

**Issue by OmarBazaraa** [ClickHouse/ClickHouse#18613]
### Description
When I run the following query, it finishes in less than a second.

```sql
SELECT
    ProjectId,
    COUNT() AS PageCount
FROM clarity.page_data_all
GROUP BY ProjectId
ORDER BY PageCount DESC
LIMIT 50

Elapsed: 0.873 sec. Processed 11.34 billion rows, 90.72 GB (13.00 billion rows/s., 103.97 GB/s.)
```

But when I slight change the query as follows, it takes much longer time (~10 seconds).

```sql
SELECT
    ProjectId,
    any(domain(Url)) AS Domain,
    COUNT() AS PageCount
FROM clarity.page_data_all
GROUP BY ProjectId
ORDER BY PageCount DESC
LIMIT 50

Elapsed: 10.107 sec. Processed 11.34 billion rows, 1.29 TB (1.12 billion rows/s., 127.14 GB/s.)
```

Even if I change the query to `any(Ur)l` instead of `any(domain(Url))`, it is still taking around 10 seconds.

### Expected Performance
I didn't expect such difference in performance. I thought ClickHouse would extract the domains for only 50 URLs.

### Additional Context
**Server Version:** 20.10.2

**Comment by den-crane** [comment]
> 11.34 billion rows, 90.72 GB
> 11.34 billion rows, 1.29 TB

AFAIK The cause is in Url column size. CH needs to read and uncompress files. 

Try to materialize domain as a real column. 
Try to use LowCardinality.

**Comment by alexey-milovidov** [comment]
> I thought ClickHouse would extract the domains for only 50 URLs.

There is no such optimization. It is possible to implement but it will require more complex query pipeline with two passes of the data. See https://github.com/ClickHouse/ClickHouse/issues/5329

**Comment by OmarBazaraa** [comment]
> > I thought ClickHouse would extract the domains for only 50 URLs.
> 
> There is no such optimization. It is possible to implement but it will require more complex query pipeline with two passes of the data. See #5329

Does the same apply for using `any(Url)` instead of `any(domain(Url))` or `domain(any(Url))`?
As it's taking too long as well.
