### ISSUE TITLE
Add support for TIMEDIFF function in MySQL Wire protocol (Mysql.Data .NET driver)

### ISSUE THREAD

**Issue by siradjev** [ClickHouse/ClickHouse#18612]
**Use case**
Mysql.Data is the default way to connect to mysql DB in .NET. 
https://dev.mysql.com/doc/connector-net/en/connector-net-versions.html
Currently it's not possible to connect due to driver trying to call TIMEDIFF after connection. 

Error returned
```
MySql.Data.MySqlClient.MySqlException: 'Code: 46, e.displayText() = DB::Exception: Unknown function TIMEDIFF. Maybe you meant: ['dateDiff'] (version 20.8.9.6 (official build))'
```
Example snippet to check. 
```
            using (MySqlConnection conn = new MySqlConnection("Database=db;Data Source=server; Port=9004;User Id=mtest;Password=mtest"))
            {
                conn.Open(); // throws exception
            }

```

**Describe the solution you'd like**
Add TIMEDIFF meta-function support to mysql wire protocol in Clickhouse as a part of overall effort to improve MySQL compatibility #9336.

**Describe alternatives you've considered**
No other real alternative is available.

**Comment by filimonov** [comment]
https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_timediff

It returns TIME type which does not exists in clickhouse :\

**Comment by den-crane** [comment]
https://dev.mysql.com/doc/internals/en/date-and-time-data-type-representation.html
```
TIME: A three-byte integer packed as DD×24×3600 + HH×3600 + MM×60 + SS 

 1 bit sign    (1= non-negative, 0= negative)
 1 bit unused  (reserved for future extensions)
10 bits hour   (0-838)
 6 bits minute (0-59) 
 6 bits second (0-59) 
---------------------
24 bits = 3 bytes
```

**Comment by siradjev** [comment]
Probably would also need UTC_TIMESTAMP() implemented as per #17177

**Comment by SpringHgui** [comment]
+1

**Comment by alexey-milovidov** [comment]
It works: `TIMEDIFF(NOW(), UTC_TIMESTAMP())`
