### ISSUE TITLE
Structure of replication_queue table changed

### ISSUE THREAD

**Issue by simPod** [ClickHouse/ClickHouse#18610]
We have checked backward incompatible changes in changelog to avoid issues while upgrading from 20.9 to 20.12

Though upgrading one replica changed structure of `system.replication_queue` table which caused replicas with different versions to be incompatible.

![image](https://user-images.githubusercontent.com/327717/103294062-624b9a80-49f1-11eb-8e6c-67dd73d9a55a.png)
![image](https://user-images.githubusercontent.com/327717/103294072-65df2180-49f1-11eb-9d39-bbddbce75439.png)

---------------

I believe that this (source https://github.com/ClickHouse/ClickHouse/issues/18609) is not mentioned in documentation but is critical to know for upgrading ClickHouse

> do not keep different versions of replicas for a long time;

https://clickhouse.tech/docs/en/operations/update/ states 

> Do not update all the servers on a cluster simultaneously, or the cluster will be unavailable for some time.

but this is kinda what should have been done this time.

Did we do something wrong or the BC change was not mentioned in the changelog while it should have

_As a side note: I'm not complaining, just trying to see what could have been done better to avoid it in the future._

~We have reverted replica from 20.12 to 20.9 and now seeing these errors in logs~

> ~Too many parts (300). Merges are processing significantly slower than inserts~

~However replication queue is empty and mutations are also all done. Is there a way to check status of those unmerged parts?~

~Might be because there's not way back from 20.12? (https://github.com/ClickHouse/ClickHouse/issues/18609)~

> ~(ReplicatedMergeTreeRestartingThread): void DB::ReplicatedMergeTreeRestartingThread::run(): Code: 27, e.displayText() = DB::Exception: Cannot parse input: expected 'quorum: ' before: 'merge_type: 2\n', Stack trace (when copying this message, always include the lines below):~

**Comment by simPod** [comment]
Might be because there's not way back from 20.12?

> (ReplicatedMergeTreeRestartingThread): void DB::ReplicatedMergeTreeRestartingThread::run(): Code: 27, e.displayText() = DB::Exception: Cannot parse input: expected 'quorum: ' before: 'merge_type: 2\n', Stack trace (when copying this message, always include the lines below):

**Comment by den-crane** [comment]
replication_queue is a virtual table. It exists for users. CH itself does not use this table.

**Comment by simPod** [comment]
Ah, right. Though something was the reason of

> DB::Exception: Cannot parse input: expected 'quorum: ' before: 'merge_type: 2\n'

some structure somewhere must have changed so those versions were incompatible.

The cluster is now on 20.12 and everything is running though there was some BC change that was not mentioned. Any idea what?

**Comment by filimonov** [comment]
Do you use insert_quorum?

**Comment by simPod** [comment]
It's set to 0 in `system.settings`

```
name	value
insert_quorum	0
insert_quorum_parallel	0
```

**Comment by alexey-milovidov** [comment]
> Do not update all the servers on a cluster simultaneously, or the cluster will be unavailable for some time.
but this is kinda what should have been done this time.

Install new version. Restart half of the replicas. After they are up, restart other replicas.

**Comment by filimonov** [comment]
> Ah, right. Though something was the reason of
> 
> > DB::Exception: Cannot parse input: expected 'quorum: ' before: 'merge_type: 2\n'
> 
> some structure somewhere must have changed so those versions were incompatible.

Caused by https://github.com/ClickHouse/ClickHouse/pull/14490/
