### ISSUE TITLE
wrong result in window function without ORDER BY section

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#18618]
```
SELECT
   gr,
   str,
   count(*) OVER (PARTITION BY gr) a,
   sum(1)   OVER (PARTITION BY gr) b,
   count(*) OVER (PARTITION BY gr ORDER BY str DESC) c,   
   sum(1)   OVER (PARTITION BY gr ORDER BY str DESC) d
from  (select number %3 gr,  'numb'||toString(number) str from numbers(9))
order by gr, str;

┌─gr─┬─str───┬─a─┬─b─┬─c─┬─d─┐
│  0 │ numb0 │ 3 │ 3 │ 3 │ 3 │
│  0 │ numb3 │ 2 │ 2 │ 2 │ 2 │
│  0 │ numb6 │ 1 │ 1 │ 1 │ 1 │
│  1 │ numb1 │ 3 │ 3 │ 3 │ 3 │
│  1 │ numb4 │ 2 │ 2 │ 2 │ 2 │
│  1 │ numb7 │ 1 │ 1 │ 1 │ 1 │
│  2 │ numb2 │ 3 │ 3 │ 3 │ 3 │
│  2 │ numb5 │ 2 │ 2 │ 2 │ 2 │
│  2 │ numb8 │ 1 │ 1 │ 1 │ 1 │
└────┴───────┴───┴───┴───┴───┘


expected (PG):

SELECT
   gr,
   str,
   count(*) OVER (PARTITION BY gr) a,
   sum(1)   OVER (PARTITION BY gr) b,
   count(*) OVER (PARTITION BY gr ORDER BY str DESC) c,   
   sum(1)   OVER (PARTITION BY gr ORDER BY str DESC) d
FROM
(SELECT generate_series%3 gr, 'numb'||generate_series str FROM generate_series(0,8)) t
order by gr, str

 gr |  str  | a | b | c | d
----+-------+---+---+---+---
  0 | numb0 | 3 | 3 | 3 | 3
  0 | numb3 | 3 | 3 | 2 | 2
  0 | numb6 | 3 | 3 | 1 | 1
  1 | numb1 | 3 | 3 | 3 | 3
  1 | numb4 | 3 | 3 | 2 | 2
  1 | numb7 | 3 | 3 | 1 | 1
  2 | numb2 | 3 | 3 | 3 | 3
  2 | numb5 | 3 | 3 | 2 | 2
  2 | numb8 | 3 | 3 | 1 | 1
(9 rows)
```

**Comment by l1t1** [comment]
in which version can I test the window functions?

**Comment by den-crane** [comment]
> in which version can I test the window functions?

20.13.1.5547

**Comment by l1t1** [comment]
thanks

**Comment by l1t1** [comment]
i try to install them on a  debian 10.7 on virtualbox, and receive following err msg, how to expand the / size?
![2020-12-30_091223](https://user-images.githubusercontent.com/23301704/103323814-6de5a280-4a7f-11eb-9143-17f0782f1a4d.png)

**Comment by l1t1** [comment]
i use 
```
C:\Program Files\Oracle\VirtualBox>VBoxManage modifyhd "E:\vdisk\debian\debian.vdi" --resize 20480
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
```
to expand the vdisk, it shows 20GB in vitrulbox, in debian, fdisk shows 20GB too, but df still shows / used 100%.
![2020-12-30_093327](https://user-images.githubusercontent.com/23301704/103324664-78a23680-4a83-11eb-9b86-fd122e630e38.png)
![2020-12-30_094121](https://user-images.githubusercontent.com/23301704/103324669-7cce5400-4a83-11eb-8202-0a7d9d4c6243.png)

**Comment by l1t1** [comment]
ref https://blog.csdn.net/qq_20679687/article/details/97858854 and sloved expand problem, ch is installed, but  windows function doesn't work
![2020-12-30_105334](https://user-images.githubusercontent.com/23301704/103326901-63caa080-4a8d-11eb-8563-bc658938a8f3.png)

**Comment by l1t1** [comment]
found the setting papameter, it works
![2020-12-30_111915](https://user-images.githubusercontent.com/23301704/103327770-f0c32900-4a90-11eb-8491-f8e0d952538d.png)

**Comment by l1t1** [comment]
what functions is ready now? 
row_number() is unkown.

**Comment by l1t1** [comment]
other install formats at https://clickhouse-builds.s3.yandex.net/0/14a8b5e5ade79e820ff6b0cfe2982a861f717670/clickhouse_build_check/report.html

**Comment by akuzm** [comment]
@l1t1 these screenshots are not related to this issue. If you have questions, please open a separate issue for them.

> what functions is ready now?
row_number() is unkown.

Only aggregate functions work for now. This feature is "work in progress", we will add documentation and make an announcement when it is ready for general testing.

**Comment by l1t1** [comment]
> @l1t1 these screenshots are not related to this issue. If you have questions, please open a separate issue for them.
> 
> > what functions is ready now?
> > row_number() is unkown.
> 
> Only aggregate functions work for now. This feature is "work in progress", we will add documentation and make an announcement when it is ready for general testing.

thanks, i hide the screenshots

**Comment by akuzm** [comment]
Looks like it is the effect of frame. We support only `rows between unbounded preceding and current row`. Postgres has different defaults:
>The default framing option is RANGE UNBOUNDED PRECEDING, which is the same as RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW. With ORDER BY, this sets the frame to be all rows from the partition start up through the current row's last ORDER BY peer. Without ORDER BY, this means all rows of the partition are included in the window frame, since all rows become peers of the current row.

This explains the difference.

```
postgres=# SELECT
   gr,
   str,
   count(*) OVER (PARTITION BY gr ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) a,
   sum(1)   OVER (PARTITION BY gr ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) b,
   count(*) OVER (PARTITION BY gr ORDER BY str DESC) c,   
   sum(1)   OVER (PARTITION BY gr ORDER BY str DESC) d
FROM
(SELECT generate_series%3 gr, 'numb'||generate_series str FROM generate_series(0,8)) t
order by gr, str
;
 gr |  str  | a | b | c | d 
----+-------+---+---+---+---
  0 | numb0 | 3 | 3 | 3 | 3
  0 | numb3 | 2 | 2 | 2 | 2
  0 | numb6 | 1 | 1 | 1 | 1
  1 | numb1 | 3 | 3 | 3 | 3
  1 | numb4 | 2 | 2 | 2 | 2
  1 | numb7 | 1 | 1 | 1 | 1
  2 | numb2 | 3 | 3 | 3 | 3
  2 | numb5 | 2 | 2 | 2 | 2
  2 | numb8 | 1 | 1 | 1 | 1
```

**Comment by l1t1** [comment]
will ch support  ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROWS etc clauses?

**Comment by den-crane** [comment]
> will ch support ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROWS etc clauses?

If it's god's will it will happen

**Comment by akuzm** [comment]
`RANGE` frame is the default now.
