### ISSUE TITLE
write clickhosue DB::Exception: Too many simultaneous queries. Maximum: 16

### ISSUE THREAD

**Issue by ningyanhui** [ClickHouse/ClickHouse#18620]
config

<background_schedule_pool_size>80</background_schedule_pool_size>
<background_pool_size>80</background_pool_size>
<max_final_threads>80</max_final_threads>
<background_buffer_flush_schedule_pool_size>80</background_buffer_flush_schedule_pool_size>
<background_distributed_schedule_pool_size>80</background_distributed_schedule_pool_size>

<max_memory_usage>64000000000</max_memory_usage>
<max_insert_threads>80</max_insert_threads>

Other descriptions
I want to known the '16' belong to ?

**Comment by alexey-milovidov** [comment]
@ningyanhui 

It's `max_concurrent_queries` in config.xml.
