### ISSUE TITLE
the window function with over(order by) is much slower than that without it

### ISSUE THREAD

**Issue by l1t1** [ClickHouse/ClickHouse#18622]
with order by ---12s
without order by  --1.8s
sorry for paste the picture, as i cannot copy text from my virtualbox
![2020-12-30_152501](https://user-images.githubusercontent.com/23301704/103336618-b7e87b80-4ab3-11eb-9911-80b43b833b26.png)

**Comment by l1t1** [comment]
oder by two columns --6s , half time of order by 1 col.
![2020-12-30_155146](https://user-images.githubusercontent.com/23301704/103337705-1b27dd00-4ab7-11eb-8f9f-f125d5599512.png)

**Comment by l1t1** [comment]
the time is not stable, order by 1 col --9s
![2020-12-30_155529](https://user-images.githubusercontent.com/23301704/103337888-98535200-4ab7-11eb-9f7f-7c8a3d1fa8d9.png)

**Comment by l1t1** [comment]
and the result of sum is not the same if order by different columns
![VirtualBox_debian_30_12_2020_16_37_27](https://user-images.githubusercontent.com/23301704/103339921-b58b1f00-4abd-11eb-87e3-c0f8ced1ad80.png)

**Comment by alexey-milovidov** [comment]
This performance difference is expected due to sorting.
