### ISSUE TITLE
SQL syntax checker mistake dictGet parameters as column names 

### ISSUE THREAD

**Issue by zhangguiyu** [ClickHouse/ClickHouse#18623]
in SQL syntax checker, if the column name shares the same name as a dictionary, it will be considered appearing more than once if a dictionary method is called, e.g.,

SELECT dictGet('qmesh', 'QualifierName', qid) AS qmesh FROM TABLE

will result in execption:

DB::Exception: Column qmesh specified more than once. 

* Which ClickHouse server version to use
clickhouse-server 20.11.4

* Which interface to use, if matters

clickhouse-client

* Non-default settings, if any

create a dictionary based on clickhouse, called 'qmesh'

* Queries to run that lead to unexpected result

SELECT dictGet('qmesh', 'QualifierName', qid) AS qmesh FROM TABLE

**Expected behavior**

Clickhouse should differentiate the text within a method from text in the SQL column names

**Error message and/or stacktrace**

DB::Exception: Column qmesh specified more than once. 

**Additional context**
None

**Comment by amosbird** [comment]
Cannot reproduce in 20.13.1.1. Please share your dict config.

**Comment by zhangguiyu** [comment]
Thanks amosbird, here are additional info:

dict config:

guiyu@mi:~/mia/src/docker/clickhouse-server/etc/config.d$ more dmesh_dictionary.xml 
<yandex>
    <dictionary>
        <name>dmesh</name>
        <source>
            <clickhouse>
                <host>localhost</host>
                <port>9000</port>
                <user>default</user>
                <password></password>
                <db>dev</db>
                <table>mesh_d</table>
                <where></where>
            </clickhouse>
        </source>
        <lifetime>
            <min>300</min>
            <max>360</max>
        </lifetime>
        <layout>
            <flat/>
        </layout>
        <structure>
            <id>
                <name>did</name>
            </id>
            <attribute>
                <name>DescriptorName</name>
                <type>String</type>
                <null_value></null_value>
            </attribute>
        </structure>
    </dictionary>
</yandex>

The exact SQL that failed is:

CREATE MATERIALIZED VIEW IF NOT EXISTS date_pmid_mesh_mv                  
ENGINE = MergeTree                                                        
ORDER BY pmid                                                             
POPULATE AS                                                               
--     INSERT INTO date_pmid_mesh_mv                                      
SELECT                                                                    
    a.date,                                                               
    a.pmid,                                                               
    b.id,                                                                 
    b.did, b.dmajor, b.meshd,                                             
    b.qid, b.qmajor, b.meshq                                              
FROM                                                                      
    (                                                                     
    /*                                                                    
    WITH [       0, 10000000] AS prange                                   
    WITH [10000000, 20000000] AS prange                                   
    WITH [20000000, 30000000] AS prange                                   
    WITH [30000000, 35000000] AS prange                                   
    */                                                                    
    WITH [30000000, 35000000] AS prange                                   
    SELECT date, pmid                                                     
    FROM papers_mv                                                        
    WHERE pmid >= prange[1] AND pmid < prange[2]                          
    ) AS a                                                                
LEFT JOIN                                                                 
    (                                                                     
    /*                                                                    
    WITH [       0, 10000000] AS prange                                   
    WITH [10000000, 20000000] AS prange                                   
    WITH [20000000, 30000000] AS prange                                   
    WITH [30000000, 35000000] AS prange                                   
    */                                                                    
    WITH [30000000, 35000000] AS prange                                   
    SELECT                                                                
        concat( toString(pmid),'.',toString(did),'.',toString(dmajor),'.',
        toString(qid),'.',toString(qmajor) ) AS id, pmid,                 
        did, dmajor, dictGet('dmesh','DescriptorName', toUInt64(did)) AS dmesh,
        qid, qmajor, dictGet('qmesh','QualifierName', toUInt64(qid)) AS qmesh
    FROM pmid_mesh_mv                                                     
    WHERE pmid >= prange[1] AND pmid < prange[2]                          
    ) AS b                                                                
ON                                                                        
    a.pmid = b.pmid  

and I had to change qmesh to meshq, dmesh to meshd, in order for the query  to work. The following is the query that worked after the above change:

CREATE MATERIALIZED VIEW IF NOT EXISTS date_pmid_mesh_mv                  
ENGINE = MergeTree                                                        
ORDER BY pmid                                                             
POPULATE AS                                                               
--     INSERT INTO date_pmid_mesh_mv                                      
SELECT                                                                    
    a.date,                                                               
    a.pmid,                                                               
    b.id,                                                                 
    b.did, b.dmajor, b.meshd,                                             
    b.qid, b.qmajor, b.meshq                                              
FROM                                                                      
    (                                                                     
    /*                                                                    
    WITH [       0, 10000000] AS prange                                   
    WITH [10000000, 20000000] AS prange                                   
    WITH [20000000, 30000000] AS prange                                   
    WITH [30000000, 35000000] AS prange                                   
    */                                                                    
    WITH [30000000, 35000000] AS prange                                   
    SELECT date, pmid                                                     
    FROM papers_mv                                                        
    WHERE pmid >= prange[1] AND pmid < prange[2]                          
    ) AS a                                                                
LEFT JOIN                                                                 
    (                                                                     
    /*                                                                    
    WITH [       0, 10000000] AS prange                                   
    WITH [10000000, 20000000] AS prange                                   
    WITH [20000000, 30000000] AS prange                                   
    WITH [30000000, 35000000] AS prange                                   
    */                                                                    
    WITH [30000000, 35000000] AS prange                                   
    SELECT                                                                
        concat( toString(pmid),'.',toString(did),'.',toString(dmajor),'.',
        toString(qid),'.',toString(qmajor) ) AS id, pmid,                 
        did, dmajor, dictGet('dmesh','DescriptorName', toUInt64(did)) AS meshd,
        qid, qmajor, dictGet('qmesh','QualifierName', toUInt64(qid)) AS meshq
    FROM pmid_mesh_mv                                                     
    WHERE pmid >= prange[1] AND pmid < prange[2]                          
    ) AS b                                                                
ON                                                                        
    a.pmid = b.pmid

**Comment by zhangguiyu** [comment]
Sorry, I can't seem to replicate this bug in clickhouse-server 20.11.4 anymore:

e.g., the following now works:

```
CREATE MATERIALIZED VIEW IF NOT EXISTS bug_mv                                                                   
ENGINE = MergeTree   
ORDER BY pmid        
POPULATE AS          
-- INSERT INTO bug_mv
SELECT                
    a.date,           
    a.pmid,                                                               
    b.id,             
    b.did, b.dmajor, b.dmesh,
    b.qid, b.qmajor, b.qmesh
FROM                                                                      
    (                 
 WITH [0, 10] AS prange
    SELECT date, pmid 
    FROM papers_mv                                                        
    WHERE pmid >= prange[1] AND pmid < prange[2]
    ) AS a            
LEFT JOIN             
    (                                                                     
   WITH [0, 10] AS prange
    SELECT            
        concat( toString(pmid),'.',toString(did),'.',toString(dmajor),'.',
        toString(qid),'.',toString(qmajor) ) AS id, pmid,                 
        did, dmajor, dictGet('dmesh','DescriptorName', toUInt64(did)) AS dmesh,
        qid, qmajor, dictGet('qmesh','QualifierName', toUInt64(qid)) AS qmesh
    FROM pmid_mesh_mv 
    WHERE pmid >= prange[1] AND pmid < prange[2]                          
    ) AS b            
ON                    
    a.pmid = b.pmid  
```
Closing issue. aplogies for the erraneous submission.
