### ISSUE TITLE
Run "service clickhouse-server start" failed and print "

### ISSUE THREAD

**Issue by costaxu** [ClickHouse/ClickHouse#18664]
(you don't have to strictly follow this form)

When I start clickhouse-server, run "service clickhouse-server start" but it failed and comes out  "Init script is already running".

My version is  20.12.4.5.
My OS is Linux devcloud113 3.10.107-1-tlinux2_kvm_guest-0049 #1 SMP Tue Jul 30 23:46:29 CST 2019 x86_64 x86_64 x86_64 GNU/Linux

I tried to fix it and I found the "service_or_func" function may not suite my Linux distributed release, So I just run "$1" and it works.
service_or_func()
{
    $1
    #if [ -x "/bin/systemctl" ] && [ -f /etc/systemd/system/clickhouse-server.service ] && [ -d /run/systemd/system ]; then
    #    #echo "service again?"
    #    service $PROGRAM $1
    #else
    #    $1
    #fi
}

**Comment by alexey-milovidov** [comment]
You can also start ClickHouse with the following command:

`sudo clickhouse start`

**Comment by l1t1** [comment]
`nohup. /clickhouse server &`
are suitable for tgz version

**Comment by den-crane** [comment]
> My OS is Linux devcloud113 3.10.107-1-tlinux2_kvm_guest-0049 #1 SMP Tue Jul 30 23:46:29 CST 2019 x86_64 x86_64 x86_64 GNU/Linux

What Linux distro do you use?

cat /etc/*rel*

**Comment by l1t1** [comment]
systemctl start clickhouse ?

**Comment by costaxu** [comment]
I think my linux is CentOS Linux release 7.2

**Comment by l1t1** [comment]
> I think my linux is CentOS Linux release 7.2

systemctl start clickhouse
