### ISSUE TITLE
will ch release binary files for other platforms

### ISSUE THREAD

**Issue by l1t1** [ClickHouse/ClickHouse#18661]
such as windows, android, linux on arm?

**Comment by alexey-milovidov** [comment]
We already release binaries for Linux on ARM, see https://clickhouse.tech/docs/en/getting-started/install/#from-binaries-non-linux

There are no special binaries for Windows as ClickHouse works on WSL2.

We don't release binaries for Android although it can be built easily: https://clickhouse.tech/blog/en/2020/pixel-benchmark/

**Comment by l1t1** [comment]
thanks.  and one more question
why https://builds.clickhouse.tech/master/aarch64/clickhouse
is so big size?  it's about 2GB.

**Comment by alexey-milovidov** [comment]
It contains debug info.

**Comment by l1t1** [comment]
can you also supply a non debug version?

**Comment by alexey-milovidov** [comment]
If you run `strip clickhouse` you will get it automatically.

**Comment by l1t1** [comment]
> If you run `strip clickhouse` you will get it automatically.

I see.  but supply such an file will save network traffic, since many people just want to use it, not test it.

**Comment by l1t1** [comment]
c program compiled in debug version is slower than release version in windows, is that also true in linux?

**Comment by alexey-milovidov** [comment]
No. Debug info has absolutely zero impact on performance.
It is contained in a separate section of the binary that is not even loaded.
The machine code does not depend on the presence of the debug info.

> debug version is slower than release version in windows

You a mixed up a little. You mean "debug" build.
But what we distribute is "release build with debug info".

**Comment by l1t1** [comment]
could you release a grip version arm binary?

**Comment by l1t1** [comment]
https://github.com/ClickHouse/ClickHouse/releases/download/v20.13.1.5584-testing/clickhouse-common-static-dbg-20.13.1.5584.tgz 550 MB
https://github.com/ClickHouse/ClickHouse/releases/download/v20.8.11.17-lts/clickhouse-common-static-dbg-20.8.11.17.tgz 1.47GB
why the 20.13 file is smaller?

**Comment by alexey-milovidov** [comment]
It is using Link Time Optimization (LTO).
