### ISSUE TITLE
MaterializeMySQL query is very slow

### ISSUE THREAD

**Issue by awesomeleo** [ClickHouse/ClickHouse#18662]
(you don't have to strictly follow this form)

**Describe the situation**
I do a query select count（*）by using MaterializeMySQL engine， and it will use almost 1000 seconds.
I suspect it may be caused by  the 'FINAL' operation.
So I do a test, selecting the data from MaterializeMySQL and inseting it to a ReplacingMergeTree table. It's 1400 times faster than the query  using 'FINAL'.

localhost :) select count(*) from replmgt where _sign = 1;

SELECT count(*)
FROM replmgt
WHERE _sign = 1

┌────count()─┐
│ 8534664000 │
└────────────┘

1 rows in set. Elapsed: 0.682 sec. Processed 8.53 billion rows, 8.53 GB (12.51 billion rows/s., 12.51 GB/s.) 

localhost :) select count(*) from replmgt final where _sign = 1;

SELECT count(*)
FROM replmgt
FINAL
WHERE _sign = 1

┌────count()─┐
│ 8534664000 │
└────────────┘

1 rows in set. Elapsed: 1015.328 sec. Processed 8.53 billion rows, 1.04 TB (8.41 million rows/s., 1.03 GB/s.) 

**How to reproduce**
* Which ClickHouse server version to use
 20.10.6.27

* `CREATE TABLE` statements for all tables involved

CREATE TABLE `test` (
  `id` int NOT NULL AUTO_INCREMENT,
  `create_time` datetime DEFAULT NULL,
  `num` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB AUTO_INCREMENT=31814646 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

insert some data
DROP PROCEDURE IF EXISTS test_insert;
DELIMITER $$
CREATE PROCEDURE test_insert()
BEGIN
    DECLARE i INT DEFAULT 1;
    WHILE i <= 83240000 DO
        insert into test ( create_time, num ) values (  now(), i ); 
	SET i=i+1;
    END WHILE;
END $$
DELIMITER ;
CALL test_insert()

then replicat data to clickhouse

**Expected performance**
select count（*） is fast， but now is too slow.

**Additional context**

So I do a test, selecting the data from MaterializeMySQL and inseting it to a ReplacingMergeTree table. It's 1400 times faster than the query  using 'FINAL'.

**Comment by alexey-milovidov** [comment]
@zhang2014 @BohuTANG

**Comment by den-crane** [comment]
@awesomeleo but if you delete some rows `select count（*）` without FINAL will be incorrect.

**Comment by BohuTANG** [comment]
MaterializeMySQL underlying engine is ReplacingMergeTree, this case looks not make sense. Can you insert data to ReplacingMergeTree directly and do the test?

**Comment by awesomeleo** [comment]
> @awesomeleo but if you delete some rows `select count（*）` without FINAL will be incorrect.

Yes, I know. So we need to optimzie the FINAL performace. It's 1400 times slower than the query without FINAL. It's not acceptable.

**Comment by awesomeleo** [comment]
> MaterializeMySQL underlying engine is ReplacingMergeTree, this case looks not make sense. Can you insert data to ReplacingMergeTree directly and do the test?

@BohuTANG  Yes. I have done the test. It's an issue with ReplacingMergeTree.

MaterializeMergeTree with final:
localhost :) select count(*) from mmgt;
SELECT count(*)
FROM mmgt
┌────count()─┐
│ 8534664000 │
└────────────┘
1 rows in set. Elapsed: 1100.927 sec. Processed 8.53 billion rows, 1.13 TB (7.75 million rows/s., 1.02 GB/s.) 
---------------------------------------------------
Modify MaterializeMySQL , remove FINAL
localhost :) select count(*) from mmgt;
SELECT count(*)
FROM mmgt
┌────count()─┐
│ 8534664000 │
└────────────┘
1 rows in set. Elapsed: 2.812 sec. Processed 8.53 billion rows, 93.88 GB (3.04 billion rows/s., 33.39 GB/s.) 

----------------------------------------
ReplacingMergeTree without final:
localhost :) select count(*) from replmgt where _sign=1;
SELECT count(*)
FROM replmgt
WHERE _sign = 1
┌────count()─┐
│ 8534664000 │
└────────────┘
1 rows in set. Elapsed: 0.653 sec. Processed 8.53 billion rows, 8.53 GB (13.07 billion rows/s., 13.07 GB/s.)
------------------------------------------------------
ReplacingMergeTree with final:
localhost :) select count(*) from replmgt final where _sign = 1;
SELECT count(*)
FROM replmgt
FINAL
WHERE _sign = 1
┌────count()─┐
│ 8534664000 │
└────────────┘
1 rows in set. Elapsed: 1015.328 sec. Processed 8.53 billion rows, 1.04 TB (8.41 million rows/s., 1.03 GB/s.)

**Comment by awesomeleo** [comment]
perf top：
Overhead  Shared Object            Symbol                                                                                                                                   
  13.00%  clickhouse               [.] memcpy
  12.38%  clickhouse               [.] _ZN2DB16filterArraysImplIDuEEvRKNS_8PODArrayIT_Lm4096E9AllocatorILb0ELb0EELm15ELm16EEERKNS1_ImLm4096ES4_Lm15ELm16EEERS5_RS8_RKNS1_IDu
  11.30%  clickhouse               [.] DB::ColumnString::insertFrom
  10.09%  clickhouse               [.] DB::ColumnVector<long>::filter
   7.25%  clickhouse               [.] _ZNK2DB12ColumnVectorIDuE6filterERKNS_8PODArrayIDuLm4096E9AllocatorILb0ELb0EELm15ELm16EEEl
   6.72%  clickhouse               [.] DB::ReplacingSortedAlgorithm::merge
   4.93%  clickhouse               [.] DB::ColumnVector<short>::filter
   3.18%  clickhouse               [.] DB::ColumnVector<unsigned long>::filter
   3.00%  clickhouse               [.] DB::ColumnNullable::insertFrom
   2.97%  clickhouse               [.] DB::ReplacingSortedAlgorithm::insertRow
   2.81%  clickhouse               [.] DB::filterChunk
   2.26%  clickhouse               [.] DB::ColumnVector<long>::insertFrom
   1.67%  clickhouse               [.] DB::deserializeBinarySSE2<1>
   1.40%  clickhouse               [.] LZ4::(anonymous namespace)::decompressImpl<16ul, true>
   1.12%  clickhouse               [.] DB::ColumnString::updateWeakHash32
   1.08%  clickhouse               [.] DB::deserializeBinarySSE2<2>
   0.89%  clickhouse               [.] DB::ColumnVector<short>::insertFrom
   0.71%  clickhouse               [.] DB::ColumnVector<long>::compareAt
   0.49%  clickhouse               [.] DB::ColumnVector<unsigned long>::insertFrom
  
the filter use too many cpu cycles, could we opzimize this?

**Comment by awesomeleo** [comment]
same issue https://github.com/ClickHouse/ClickHouse/issues/18083

**Comment by Lomixlm** [comment]
> > MaterializeMySQL underlying engine is ReplacingMergeTree, this case looks not make sense. Can you insert data to ReplacingMergeTree directly and do the test?
> 
> @BohuTANG Yes. I have done the test. It's an issue with ReplacingMergeTree.
> 
> ## MaterializeMySQL with final:
> localhost :) select count(_) from mmgt; SELECT count(_)
> FROM mmgt
> ┌────count()─┐
> │ 8534664000 │
> └────────────┘
> 1 rows in set. Elapsed: 1100.927 sec. Processed 8.53 billion rows, 1.13 TB (7.75 million rows/s., 1.02 GB/s.)
> Modify MaterializeMySQL , remove FINAL
> localhost :) select count(_) from mmgt; SELECT count(_)
> FROM mmgt
> ┌────count()─┐
> │ 8534664000 │
> └────────────┘
> 1 rows in set. Elapsed: 2.812 sec. Processed 8.53 billion rows, 93.88 GB (3.04 billion rows/s., 33.39 GB/s.)
> 
> ## ReplacingMergeTree without final:
> localhost :) select count(_) from replmgt where _sign=1; SELECT count(_)
> FROM replmgt
> WHERE _sign = 1
> ┌────count()─┐
> │ 8534664000 │
> └────────────┘
> 1 rows in set. Elapsed: 0.653 sec. Processed 8.53 billion rows, 8.53 GB (13.07 billion rows/s., 13.07 GB/s.)
> ReplacingMergeTree with final:
> localhost :) select count(_) from replmgt final where _sign = 1; SELECT count(_)
> FROM replmgt
> FINAL
> WHERE _sign = 1
> ┌────count()─┐
> │ 8534664000 │
> └────────────┘
> 1 rows in set. Elapsed: 1015.328 sec. Processed 8.53 billion rows, 1.04 TB (8.41 million rows/s., 1.03 GB/s.)



> > MaterializeMySQL underlying engine is ReplacingMergeTree, this case looks not make sense. Can you insert data to ReplacingMergeTree directly and do the test?
> 
> @BohuTANG Yes. I have done the test. It's an issue with ReplacingMergeTree.
> 
> ## MaterializeMySQL with final:
> localhost :) select count(_) from mmgt; SELECT count(_)
> FROM mmgt
> ┌────count()─┐
> │ 8534664000 │
> └────────────┘
> 1 rows in set. Elapsed: 1100.927 sec. Processed 8.53 billion rows, 1.13 TB (7.75 million rows/s., 1.02 GB/s.)
> Modify MaterializeMySQL , remove FINAL
> localhost :) select count(_) from mmgt; SELECT count(_)
> FROM mmgt
> ┌────count()─┐
> │ 8534664000 │
> └────────────┘
> 1 rows in set. Elapsed: 2.812 sec. Processed 8.53 billion rows, 93.88 GB (3.04 billion rows/s., 33.39 GB/s.)
> 
> ## ReplacingMergeTree without final:
> localhost :) select count(_) from replmgt where _sign=1; SELECT count(_)
> FROM replmgt
> WHERE _sign = 1
> ┌────count()─┐
> │ 8534664000 │
> └────────────┘
> 1 rows in set. Elapsed: 0.653 sec. Processed 8.53 billion rows, 8.53 GB (13.07 billion rows/s., 13.07 GB/s.)
> ReplacingMergeTree with final:
> localhost :) select count(_) from replmgt final where _sign = 1; SELECT count(_)
> FROM replmgt
> FINAL
> WHERE _sign = 1
> ┌────count()─┐
> │ 8534664000 │
> └────────────┘
> 1 rows in set. Elapsed: 1015.328 sec. Processed 8.53 billion rows, 1.04 TB (8.41 million rows/s., 1.03 GB/s.)

please, How to solve the problem of slow query in MaterializeSQL? "Modify MaterializeMySQL , remove FINAL" how?

**Comment by BohuTANG** [comment]
@zhang2014 ping for help

**Comment by awesomeleo** [comment]
> > > MaterializeMySQL underlying engine is ReplacingMergeTree, this case looks not make sense. Can you insert data to ReplacingMergeTree directly and do the test?
> > 
> > 
> > @BohuTANG Yes. I have done the test. It's an issue with ReplacingMergeTree.
> > ## MaterializeMySQL with final:
> > localhost :) select count(_) from mmgt; SELECT count(_)
> > FROM mmgt
> > ┌────count()─┐
> > │ 8534664000 │
> > └────────────┘
> > 1 rows in set. Elapsed: 1100.927 sec. Processed 8.53 billion rows, 1.13 TB (7.75 million rows/s., 1.02 GB/s.)
> > Modify MaterializeMySQL , remove FINAL
> > localhost :) select count(_) from mmgt; SELECT count(_)
> > FROM mmgt
> > ┌────count()─┐
> > │ 8534664000 │
> > └────────────┘
> > 1 rows in set. Elapsed: 2.812 sec. Processed 8.53 billion rows, 93.88 GB (3.04 billion rows/s., 33.39 GB/s.)
> > ## ReplacingMergeTree without final:
> > localhost :) select count(_) from replmgt where _sign=1; SELECT count(_)
> > FROM replmgt
> > WHERE _sign = 1
> > ┌────count()─┐
> > │ 8534664000 │
> > └────────────┘
> > 1 rows in set. Elapsed: 0.653 sec. Processed 8.53 billion rows, 8.53 GB (13.07 billion rows/s., 13.07 GB/s.)
> > ReplacingMergeTree with final:
> > localhost :) select count(_) from replmgt final where _sign = 1; SELECT count(_)
> > FROM replmgt
> > FINAL
> > WHERE _sign = 1
> > ┌────count()─┐
> > │ 8534664000 │
> > └────────────┘
> > 1 rows in set. Elapsed: 1015.328 sec. Processed 8.53 billion rows, 1.04 TB (8.41 million rows/s., 1.03 GB/s.)
> 
> > > MaterializeMySQL underlying engine is ReplacingMergeTree, this case looks not make sense. Can you insert data to ReplacingMergeTree directly and do the test?
> > 
> > 
> > @BohuTANG Yes. I have done the test. It's an issue with ReplacingMergeTree.
> > ## MaterializeMySQL with final:
> > localhost :) select count(_) from mmgt; SELECT count(_)
> > FROM mmgt
> > ┌────count()─┐
> > │ 8534664000 │
> > └────────────┘
> > 1 rows in set. Elapsed: 1100.927 sec. Processed 8.53 billion rows, 1.13 TB (7.75 million rows/s., 1.02 GB/s.)
> > Modify MaterializeMySQL , remove FINAL
> > localhost :) select count(_) from mmgt; SELECT count(_)
> > FROM mmgt
> > ┌────count()─┐
> > │ 8534664000 │
> > └────────────┘
> > 1 rows in set. Elapsed: 2.812 sec. Processed 8.53 billion rows, 93.88 GB (3.04 billion rows/s., 33.39 GB/s.)
> > ## ReplacingMergeTree without final:
> > localhost :) select count(_) from replmgt where _sign=1; SELECT count(_)
> > FROM replmgt
> > WHERE _sign = 1
> > ┌────count()─┐
> > │ 8534664000 │
> > └────────────┘
> > 1 rows in set. Elapsed: 0.653 sec. Processed 8.53 billion rows, 8.53 GB (13.07 billion rows/s., 13.07 GB/s.)
> > ReplacingMergeTree with final:
> > localhost :) select count(_) from replmgt final where _sign = 1; SELECT count(_)
> > FROM replmgt
> > FINAL
> > WHERE _sign = 1
> > ┌────count()─┐
> > │ 8534664000 │
> > └────────────┘
> > 1 rows in set. Elapsed: 1015.328 sec. Processed 8.53 billion rows, 1.04 TB (8.41 million rows/s., 1.03 GB/s.)
> 
> please, How to solve the problem of slow query in MaterializeSQL? "Modify MaterializeMySQL , remove FINAL" how?

You can pass the _version condition (e.g.  _version > 0) or change the code.
