### ISSUE TITLE
Division by zero question

### ISSUE THREAD

**Issue by xiaobao3315** [ClickHouse/ClickHouse#18663]
clickhouse version is 20.5.4.40

create sql is:
 CREATE TABLE local.mbi_sale_analysis_by_brand_daily
(
    `sale_amount_d` Decimal(17, 2),
    `sale_amount_d_ly` Decimal(17, 2) 
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/local/mbi_sale_analysis_by_brand_daily', '1')
ORDER BY (sale_amount_d, sale_amount_d_ly)
SETTINGS index_granularity = 8192

table is empty,no data in table

when execute sql : 
select multiIf(sum(sale_amount_d_ly) = 0 , 0, sum(sale_amount_d) / sum(sale_amount_d_ly)) from local.mbi_sale_analysis_by_brand_daily
error is "Division by zero"

anyway, execute sql:
select case when sum(sale_amount_d_ly)= 0 then 0
           else sum(sale_amount_d) / sum(sale_amount_d_ly)end as saleReach
 from local.mbi_sale_analysis_by_brand_daily
also error "Division by zero"

**Comment by l1t1** [comment]
use Int64

**Comment by alexey-milovidov** [comment]
Workaround:

```
toFloat64(sum(sale_amount_d)) / toFloat64(sum(sale_amount_d_ly))
```

**Comment by alexey-milovidov** [comment]
#18663

**Comment by PHaroZ** [comment]
You can keep your decimal type and use [`intDivOrZero`](https://clickhouse.tech/docs/en/sql-reference/functions/arithmetic-functions/#intdivorzeroa-b) to divite your decimal with a 0 denominator
