### ISSUE TITLE
Upgrade librdkafka to 1.5.3 or greater to fix duplicate writes with exactly once semantics and compressed messages

### ISSUE THREAD

**Issue by shayrybak** [ClickHouse/ClickHouse#18668]
We are experiencing duplicates writes when consuming from Kafka using the Kafka connector while using exactly once semantics with compressed messages. We were able to locate the bug in librdkakfa, the issue https://github.com/edenhill/librdkafka/issues/3020 was resolved in https://github.com/edenhill/librdkafka/releases/tag/v1.5.3 of librdkafka.

Can we change the librdkafka version in Clickhouse?
I couldn't find any way to build Clickhouse with a different librdkafka version and would rather use an official release.

**Comment by sundy-li** [comment]
Take a look at the  `.gitmodules` file and the `contrib/librdkafka`

**Comment by shayrybak** [comment]
Thanks for the tip, I'll try to do a build myself, I think it will still be good to have the newer version in the official build at some point if possible.

**Comment by filimonov** [comment]
I'll help you....

**Comment by filimonov** [comment]
BTW - while EOS semantics will guarantee you that no duplicates will happen on the Kafka side (i.e. even if you produce the same messages few times it will be consumed once), but ClickHouse as a kafka client can guarantee only at-least-once. And in some corner cases (connection lost etc) you can get duplicates.

We need to have something like transactions on clickhouse side to be able to avoid that.

**Comment by shayrybak** [comment]
Thank you @filimonov, I'm still trying to get a build running locally. 

We are aware of that, but at this time we only see the duplicates as a result of the issue resolved in 1.5.3 so hopefully, that will do the job for us.

**Comment by filimonov** [comment]
You can pull my branch, or wait for CI build in #18671

**Comment by shayrybak** [comment]
Hi @filimonov ,

We completed testing and this indeed solved our issue. thank you for your help.
