### ISSUE TITLE
clickhouse insert too slow, more than 10s, and tcp recv-q has a lot of data

### ISSUE THREAD

**Issue by gj-zhang** [ClickHouse/ClickHouse#18667]
version 20.9.3.45 (official build)
I have 10 Clickhouse nodes, four of which have this problem and the remaining six have no problem. 
the node that has problem, cpu idle more than 99% and disk not busy
```
sudo netstat -antp | grep port
tcp        0      0 0.0.0.0:port           0.0.0.0:*               LISTEN      3367617/clickhouse- 
tcp        0      0 10.10.10.10:port     10.10.71.22:30242      TIME_WAIT   -                   
tcp        0      0 10.10.10.10:port     10.10.81.139:56536     ESTABLISHED 3367617/clickhouse- 
tcp      371      0 10.10.10.10:port     10.10.81.162:55584     ESTABLISHED 3367617/clickhouse- 
tcp      371      0 10.10.10.10:port     10.10.81.3:60558       ESTABLISHED 3367617/clickhouse- 
tcp      371      0 10.10.10.10:port     10.10.80.89:38060      ESTABLISHED 3367617/clickhouse- 
tcp      371      0 10.10.10.10:port     10.10.71.72:46240      ESTABLISHED 3367617/clickhouse- 
tcp        0      0 10.10.10.10:port     10.10.81.62:23656      ESTABLISHED 3367617/clickhouse- 
tcp        0      0 10.10.10.10:port     10.10.71.138:65074     ESTABLISHED 3367617/clickhouse- 
tcp   257121      0 10.10.10.10:port     10.10.182.225:16370    ESTABLISHED 3367617/clickhouse- 
tcp        0      0 10.10.10.10:port     10.10.182.104:39817    ESTABLISHED 3367617/clickhouse- 
tcp    51929      0 10.10.10.10:port     10.10.182.191:16798    ESTABLISHED 3367617/clickhouse- 
tcp        0      0 10.10.10.10:port     10.10.71.38:48184      ESTABLISHED 3367617/clickhouse-
```
```xml
<max_threads>56</max_threads> 
<background_pool_size>28</background_pool_size>
```
I tried to restart one of them and set max_threads to 200 and background_pool_size to 50. The restarted node does not have this problem

how to resolve it ?

**Comment by den-crane** [comment]
Can you provide:
* `create table` 
* insert query
* excerpt from the /var/log/clickhouse-server/clickhouse-server.log about the time of issue

**Comment by gj-zhang** [comment]
> Can you provide:
> 
> * `create table`
> * insert query
> * excerpt from the /var/log/clickhouse-server/clickhouse-server.log about the time of issue

Sorry for taking so long to reply.
1. We have a lot of tables, and I don't know how to provide them, and all table engine is ReplicatedMergeTree
2. Same as the first
3. the log  like the picture
![image](https://user-images.githubusercontent.com/21170229/103533060-6717bf00-4ec7-11eb-897d-83afd4779c97.png)
and i restart all the node, this problem goes away.

Could you give me some ideas or suggestions to find out the problem if it comes up again

**Comment by den-crane** [comment]
No info. No repro.
