### ISSUE TITLE
index analysis for system.numbers

### ISSUE THREAD

**Issue by ocmajortom** [ClickHouse/ClickHouse#1866]
Query gets correct results but never finishes:

```
SELECT *
FROM system.numbers
WHERE number < 10
```
```
┌─number─┐
│      0 │
│      1 │
│      2 │
│      3 │
│      4 │
│      5 │
│      6 │
│      7 │
│      8 │
│      9 │
└────────┘
↘ Progress: 7.99 billion rows, 63.92 GB (789.84 million rows/s., 6.32 GB/s.)
```
keeps running

ClickHouse client version 1.1.54342.
Connected to ClickHouse server version 1.1.54342.

Use case is getting all entries from a dictionary like:

```
select number id,
       dictGetString('currency', 'name', toUInt64(id)) name
  from system.numbers where number<1000000;
```
cheers!

**Comment by alexey-milovidov** [comment]
Yes, system.numbers table doesn't have "index", and the query will perform "full scan".

You can overcome by using:
- LIMIT: `SELECT * FROM system.numbers LIMIT 10`;
- table function numbers: `SELECT * FROM numbers(10)`;

PS. It's Ok if someone will also add an index (analysis of WHERE for simple conditions on number).

**Comment by ocmajortom** [comment]
thx!
