### ISSUE TITLE
Double format output when settings in ASTSelectQuery is a format setting.

### ISSUE THREAD

**Issue by ucasfl** [ClickHouse/ClickHouse#18680]
```sql
select * from action format CSV SETTINGS format_csv_delimiter=' '

SELECT *
FROM action
SETTINGS format_csv_delimiter = ' '
FORMAT CSV
SETTINGS format_csv_delimiter = ' '
```

**Comment by sundy-li** [comment]
Hmm, it's by design. 
Maybe we should remove settings after format if we already push down to the query?

https://github.com/ClickHouse/ClickHouse/blob/ac989f3a8fe8e2135e25ac7d6e340b048092e906/src/Parsers/QueryWithOutputSettingsPushDownVisitor.h#L13-L20

**Comment by alexey-milovidov** [comment]
Fixed.
