### ISSUE TITLE
Support for EXCEPT(COLUMNS('expression'))

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#18685]
**Use case**
```
SELECT  * EXCEPT(COLUMNS('bytes')), COLUMNS('bytes') APPLY (formatReadableSize) FROM system.parts
```

**Describe the solution you'd like**
Instead of passing a comma separated list of columns gives the ability to use COLUMNS function for EXCEPT.

**Describe alternatives you've considered**
Pass all column names by hand.

**Additional context**
Just like as ```SELECT [COLUMNS('bytes')] FROM system.parts``` works.

**Comment by amosbird** [comment]
Nice idea. Actually we can just let `except` accept a string and treat it as regex.

**Comment by alexey-milovidov** [comment]
Yes, it will be more consistent.
