### ISSUE TITLE
Deadlock with TinyLog engine (20.8)

### ISSUE THREAD

**Issue by astudnev** [ClickHouse/ClickHouse#18691]
After migrating 19.9 -> 20.8 the query like:

```
INSERT INTO tinylog 
SELECT FROM tab WHERE ( x IN (SELECT FROM tinylog))
```

Locked ( read- write operating in sub-select )

**Comment by UnamedRus** [comment]
Related https://github.com/ClickHouse/ClickHouse/issues/15997
