### ISSUE TITLE
SQL compatibility: support SELECT ALL syntax

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#18706]
**Use case**
For #15112

**Describe the solution you'd like**

SELECT ALL is identical to SELECT without DISTINCT.

If ALL is specified - ignore it.
If both ALL and DISTINCT are specified - syntax error or exception.

ALL can also be specified inside aggregate function:

SELECT sum(ALL x)

with the same effect (noop).

**Comment by zhangjmruc** [comment]
#18779
