### ISSUE TITLE
MySQL compatibility: DIV and MOD operators

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#18707]
https://dev.mysql.com/doc/refman/8.0/en/arithmetic-functions.html

**Use case**
`a DIV b` - the same as `intDiv(a, b)`
`a MOD b` - the same as `modulo(a, b)`

**Comment by spongedu** [comment]
I'd like to try this if it's ok :)

**Comment by alexey-milovidov** [comment]
@spongedu That will be awesome!
