### ISSUE TITLE
ActionsDAG::Index::remove maybe wrong

### ISSUE THREAD

**Issue by taiyang-li** [ClickHouse/ClickHouse#18714]
**Describe the bug**
In `ActionsDAG::Index::remove`, implementation as below.
In the first `remove` method, return ahead if `node->result_name` is contained in map. If not, then erase node from map and list. This is rather strange.  Maybe return ahead if `node->result_name` is not contained in map is the right way ? 
``` c++
        void remove(Node * node)
        {
            auto it = map.find(node->result_name);
            if (it != map.end())
                return;

            list.erase(it->second);
            map.erase(it);
        }

        void remove(std::list<Node *>::iterator it)
        {
            auto map_it = map.find((*it)->result_name);
            if (map_it != map.end() && map_it->second == it)
                map.erase(map_it);

            list.erase(it);
        }
```

**Comment by sundy-li** [comment]
@taiyang-li  you can paste the code like this.

https://github.com/ClickHouse/ClickHouse/blob/5b0b3b455177931b92121cf47590b3053b0cab52/src/Interpreters/ActionsDAG.h#L136-L144

**Comment by KochetovNicolai** [comment]
`Index` is a structure which contains a list of columns and hash table `name -> list::iterator`.
It is expected that list may contain columns with the same names, e.g. `('x', 'x', 'y', 'y')`. Hash table may contain reference to the part of the list, e.g. `{'x' : list.begin(), 'y' : list.begin() + 2}`

The second `remove` method by iterator is more common, cause it can remove nodes from list which are not in map. `remove(list.begin())` gives `('x', 'y', 'y'), {'y' : list.begin() + 1}`, but `remove(list.begin() + 1)` gives  `('x', 'y', 'y'), {'x' : list.begin(), 'y' : list.begin() + 1}`.

The first `remove` removes by name (probably, I should change it's arg to string) only if hash table contains this name. Now it is only used in one place, in case hash table contains a name.

**Comment by taiyang-li** [comment]
I think the operations in the first `remove` code is just opposite to:  
`The first remove removes by name (probably, I should change it's arg to string) only if hash table contains this name.`

**Comment by KochetovNicolai** [comment]
Hm, indeed.
Maybe we just don't need this code at all. I will check.
Thank you!

**Comment by KochetovNicolai** [comment]
The first version of `ActionsDAG::Index::remove` was removed.
