### ISSUE TITLE
Fatal error: Uncaught ClickHouseDB\Exception\QueryException: Empty reply from server

### ISSUE THREAD

**Issue by sagarsumit** [ClickHouse/ClickHouse#18716]
Hi Team,

I am getting an issue while fetching 5 months data from ClickHouse and I have already set execution time as 0 and memory usage as 0 for infinite time and memory respectively in the configuration settings.

I tried on some lesser date range and then I was getting rows but it was taking more time like 2.5 min and I have a data set in billions rows.

How can I get rid of it or there is any other information required please let me know?

And I also get following one when I add more columns-
`Fatal error: Uncaught ClickHouseDB\Exception\QueryException: HttpCode:500 ; ;Code: 173, e.displayText() = DB::ErrnoException: Allocator: Cannot mmap 64.00 MiB., errno: 12, strerror: Cannot allocate memory: While executing ConvertingAggregatedToChunksTransform (version 20.3.12.112)`

**Comment by alexey-milovidov** [comment]
Check the amount of RAM on the server.

**Comment by mitzsu** [comment]
> Check the amount of RAM on the server.

It is 32GB.

**Comment by mitzsu** [comment]
@alexey-milovidov Any other thing, you need to know?

**Comment by catapricop** [comment]
Hi mitzsu, I'm having a similar problem when running a high cardinality "insert into select" using the PHP client. Did you get to the bottom of it?
Uncaught ClickHouseDB\Exception\QueryException: Empty reply from server

**Comment by mitzsu** [comment]
You can use Python for **insert into select**. I used this SQL statement using Python.

**Comment by alexey-milovidov** [comment]
The problem can be avoided by enabling external aggregation.
