### ISSUE TITLE
How to query data on AWS S3 using ClickHouse S3 table engine and table function in a secure way?

### ISSUE THREAD

**Issue by davidshtian** [ClickHouse/ClickHouse#18721]
I'm using ClickHouse 20.12.5, and I would like to query the data on Amazon S3. The storage is supported with table engine and table function, but it needs AWS Access Key and Secret Key for authentication in [parameters](https://clickhouse.tech/docs/en/sql-reference/table-functions/s3/), which is a security concern, using AWS IAM role is more secure. 

Before that, I'm still using AK and SK for auth, and I've set the config file /etc/clickhouse-server/config.d/s3.xml as below:
```
<yandex>
    <s3>
       <my_endpoint>
           <endpoint>https://s3.us-east-1.amazonaws.com:443</endpoint>
           <access_key_id>***</access_key_id>
           <secret_access_key>***</secret_access_key>
       </my_endpoint>
   </s3>
</yandex>
```
But still select * s3(path, format, structure) failed due to "AccessDenied" error, and with select * s3(path, AK, SK, format, structure) the query executed successfully. 

The example error logs as below:
```
2021.01.04 13:25:14.484949 [ 4187 ] {690a989e-d328-4f29-a28a-2108536427a8} <Error> TCPHandler: Code: 499, e.displayText() = DB::Exception: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>3E1F6D8111348A1A</RequestId><HostId>F1AvI482zxcwaYzDfmCwZKaABbo1sVqNZ5Ngb49nw8cjwoMKK8ylrC5+DjLokC8w9PMuru/IdEk=</HostId></Error>: While executing S3, Stack trace:

0. DB::ReadBufferFromS3::initialize() @ 0xd9bdd5d in /usr/bin/clickhouse
1. DB::ReadBufferFromS3::nextImpl() @ 0xd9bd311 in /usr/bin/clickhouse
2. DB::TabSeparatedRowInputFormat::readPrefix() @ 0xe87f33b in /usr/bin/clickhouse
3. DB::IRowInputFormat::generate() @ 0xe7f24cb in /usr/bin/clickhouse
4. DB::ISource::work() @ 0xe77e93a in /usr/bin/clickhouse
5. DB::InputStreamFromInputFormat::readImpl() @ 0xe748b7f in /usr/bin/clickhouse
6. DB::IBlockInputStream::read() @ 0xd8a0715 in /usr/bin/clickhouse
7. ? @ 0xe366146 in /usr/bin/clickhouse
8. DB::ISource::work() @ 0xe77e93a in /usr/bin/clickhouse
9. DB::SourceWithProgress::work() @ 0xe8dbeba in /usr/bin/clickhouse
10. ? @ 0xe7b747c in /usr/bin/clickhouse
11. DB::PipelineExecutor::executeStepImpl(unsigned long, unsigned long, std::__1::atomic<bool>*) @ 0xe7b45a7 in /usr/bin/clickhouse
12. DB::PipelineExecutor::executeImpl(unsigned long) @ 0xe7b2d99 in /usr/bin/clickhouse
13. DB::PipelineExecutor::execute(unsigned long) @ 0xe7b291d in /usr/bin/clickhouse
14. ? @ 0xe7bed1d in /usr/bin/clickhouse
15. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x7dc5b3d in /usr/bin/clickhouse
16. ? @ 0x7dc96f3 in /usr/bin/clickhouse
17. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
18. clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
```

Wondering any misconfiguration or is there any additional configuration needed for S3 query? And what is the secure way to query data on AWS S3 using ClickHouse S3 table engine and table function?

Kindly looking forward to your reply. Thanks~

**Comment by UnamedRus** [comment]
Hi David,

> ClickHouse 20.12.5

IAM and other methods of auth for s3 were introduced in 20.13.
select * s3(path, format, structure) 
https://github.com/ClickHouse/ClickHouse/commit/39d867e56d4a36c45d2600d694857a5786bfc0ea

**Comment by davidshtian** [comment]
Also tried with 20.13.1.5584, and it still failed.

```
# clickhouse-client 
ClickHouse client version 20.13.1.5584 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 20.13.1 revision 54443.

ip-172-31-63-242.ec2.internal :) SELECT * FROM s3('https://s3.us-east-1.amazonaws.com/score-st/score/score', 'TSV', '`id` UInt32,`num` UInt32,`value` UInt32')

SELECT *
FROM s3('https://s3.us-east-1.amazonaws.com/score-st/score/score', 'TSV', '`id` UInt32,`num` UInt32,`value` UInt32')

Query id: 8189c33a-b916-4bb1-9b2b-5531f48cca25


Received exception from server (version 20.13.1):
Code: 499. DB::Exception: Received from localhost:9000. DB::Exception: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>9F65AA4D002CDA83</RequestId><HostId>ODtu9N/Dc37ujTKxk4bzKzywvu7xBln1XDx7Of0nSiMNlKxlw9iYtbTYjkQPqm4AFnTWEoNPGAg=</HostId></Error>: While executing S3. 

0 rows in set. Elapsed: 25.969 sec.
```

And the config file shown as below:
```
    <s3>
       <endpoint>
           <endpoint>https://s3.us-east-1.amazonaws.com/</endpoint>
           <access_key_id>AK</access_key_id>
           <secret_access_key>SK</secret_access_key>
           <use_environment_credentials>true</use_environment_credentials>
       </endpoint>
   </s3>
```

**Comment by davidshtian** [comment]
> Hi David,
> 
> > ClickHouse 20.12.5
> 
> IAM and other methods of auth for s3 were introduced in 20.13.
> [39d867e](https://github.com/ClickHouse/ClickHouse/commit/39d867e56d4a36c45d2600d694857a5786bfc0ea)
> 
> Can you confirm that you are using my_endpoint as domain in path?

@UnamedRus Do you have any example configurations to refer? Or any demo that ClickHouse on S3 works with table engine and table function? Thanks a lot~

**Comment by UnamedRus** [comment]
I just tested, and defining creds in xml is working for me.

```
<yandex>
    <s3>
       <my_endpoint>
           <endpoint>https://s3.us-east-1.amazonaws.com</endpoint>
           <access_key_id>AK</access_key_id>
           <secret_access_key>SK</secret_access_key>
           <use_environment_credentials>false</use_environment_credentials>
       </my_endpoint>
   </s3>
</yandex>


SELECT *
FROM s3('https://s3.us-east-1.amazonaws.com/bucket/dir/test.csv.gz', LineAsString, 'test String', gz)
LIMIT 1

1 rows in set. Elapsed: 2.079 sec.

SELECT version()

Query id: 818b4280-ab6f-4e3d-b620-39c6d0620b44

┌─version()────┐
│ 20.13.1.5517 │
└──────────────┘
```

Can you remove trailing slash from endpoint in config.
If it doesn't work, set  use_environment_credentials to false.
And check again?
You would need to restart the server after changes.

**Comment by davidshtian** [comment]
@UnamedRus Thanks~ I would take a try~

**Comment by davidshtian** [comment]
> I just tested, and defining creds in xml is working for me.
> 
> ```
> <yandex>
>     <s3>
>        <my_endpoint>
>            <endpoint>https://s3.us-east-1.amazonaws.com</endpoint>
>            <access_key_id>AK</access_key_id>
>            <secret_access_key>SK</secret_access_key>
>            <use_environment_credentials>false</use_environment_credentials>
>        </my_endpoint>
>    </s3>
> </yandex>
> 
> 
> SELECT *
> FROM s3('https://s3.us-east-1.amazonaws.com/bucket/dir/test.csv.gz', LineAsString, 'test String', gz)
> LIMIT 1
> 
> 1 rows in set. Elapsed: 2.079 sec.
> 
> SELECT version()
> 
> Query id: 818b4280-ab6f-4e3d-b620-39c6d0620b44
> 
> ┌─version()────┐
> │ 20.13.1.5517 │
> └──────────────┘
> ```
> 
> Can you remove trailing slash from endpoint in config.
> If it doesn't work, set  use_environment_credentials to false. (if it set to true, clickhouse would try to first use them instead of creds from config)
> And check again?
> You would need to restart the server after changes.

I've removed trailing slash from endpoint in config and it worked!

Based on the test, for endpoint config in S3, trailing slash, port (e.g. 443) and virtual host style (e.g. https://score-st.s3.us-east-1.amazonaws.com) are not supported.

**Comment by davidshtian** [comment]
@UnamedRus Hi~ I've tested this feature in AWS global regions, and all worked well. However, when I tested in AWS China region(Beijing and Ningxia), it throws errors as below:
```
Error message: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = SSL Exception: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED (version 20.13.1.5591 (official build))
```

It seems a certificate issue, and the host of S3 in China regions is different from global regions, for example, it's 'https://s3.cn-north-1.amazonaws.com.cn'. 

Though replace with 'http' would be a workaround and tested, I would like to know is this a known issue or need a fix on this? Thanks~

**Comment by UnamedRus** [comment]
> It seems a certificate issue, and the host of S3 in China regions is different from global regions, for example, it's 'https://s3.cn-north-1.amazonaws.com.cn'.

Yes, it looks like.

> I would like to know is this a known issue or need a fix on this? 

I don't think that is a known issue, one of the possible reasons is clickhouse is using a statically linked ssl library and it's only checking subset (Ubuntu~) of possible ssl cert location.

related pr https://github.com/ClickHouse/ClickHouse/issues/17803

**Comment by wahani** [comment]
It seems I have a related Problem. With Version '21.3.12.2' I get an Access Denied error message while executing

```sql
select count(*)
from s3('https://s3.eu-central-1.amazonaws.com/bucket/tmp.csv', 'CSV', 'id String');
```

however adding the credentials resolves this issue:

```sql
select count(*)
from s3('https://s3.eu-central-1.amazonaws.com/bucket/tmp.csv', '...', '...', 'CSV', 'id String');
```

The configuration block for this looks like:

**Comment by davidshtian** [comment]
> documentation

**Comment by davidshtian** [comment]
Try to set `<endpoint>https://s3.eu-central-1.amazonaws.com</endpoint>`?

**Comment by wahani** [comment]
Thanks for providing feedback. Unfortunately it does not change the behavior. I tested this in the aforementioned versions.

**Comment by lingcuv** [comment]
Hi @davidshtian I have the similar certificate issue and tested on multiple versions including the latest one. But all failed.
I wonder if there is any issue with my s3 bucket configuration. Could help share some information on your s3 bucket config? Does it have to be a public bucket? 
Kindly looking forward to your reply. Thanks

**Comment by davidshtian** [comment]
> Hi @davidshtian I have the similar certificate issue and tested on multiple versions including the latest one. But all failed.
> I wonder if there is any issue with my s3 bucket configuration. Could help share some information on your s3 bucket config? Does it have to be a public bucket?
> Kindly looking forward to your reply. Thanks

No need to set s3 bucket public, what's the error message? And what's the OS?

**Comment by davidshtian** [comment]
> Thanks for providing feedback. Unfortunately it does not change the behavior. I tested this in the aforementioned versions.

The older version still got the same error?

**Comment by lingcuv** [comment]
> > Hi @davidshtian I have the similar certificate issue and tested on multiple versions including the latest one. But all failed.
> > I wonder if there is any issue with my s3 bucket configuration. Could help share some information on your s3 bucket config? Does it have to be a public bucket?
> > Kindly looking forward to your reply. Thanks
> 
> No need to set s3 bucket public, what's the error message? And what's the OS?
Thanks for your reply.
I got 'The AWS Access Key Id you provided does not exist in our records' if set use_environment_credentials to false.
And got 'Access Denied' if use the IAM role and set use_environment_credentials to true.
I used the yandex/clickhouse-server image on the eks cluster on aws.

**Comment by davidshtian** [comment]
> > > Hi @davidshtian I have the similar certificate issue and tested on multiple versions including the latest one. But all failed.
> > > I wonder if there is any issue with my s3 bucket configuration. Could help share some information on your s3 bucket config? Does it have to be a public bucket?
> > > Kindly looking forward to your reply. Thanks
> > 
> > 
> > No need to set s3 bucket public, what's the error message? And what's the OS?
> > Thanks for your reply.
> > I got 'The AWS Access Key Id you provided does not exist in our records' if set use_environment_credentials to false.
> > And got 'Access Denied' if use the IAM role and set use_environment_credentials to true.
> > I used the yandex/clickhouse-server image on the eks cluster on aws.

It looks like a permission issue, especially 'The AWS Access Key Id you provided does not exist in our records', it seems using China regions with Global AK/SK or the opposite, and 'Access Denied' might be role used in IRSA cannot access S3.

**Comment by lingcuv** [comment]
> > > > Hi @davidshtian I have the similar certificate issue and tested on multiple versions including the latest one. But all failed.
> > > > I wonder if there is any issue with my s3 bucket configuration. Could help share some information on your s3 bucket config? Does it have to be a public bucket?
> > > > Kindly looking forward to your reply. Thanks
> > > 
> > > 
> > > No need to set s3 bucket public, what's the error message? And what's the OS?
> > > Thanks for your reply.
> > > I got 'The AWS Access Key Id you provided does not exist in our records' if set use_environment_credentials to false.
> > > And got 'Access Denied' if use the IAM role and set use_environment_credentials to true.
> > > I used the yandex/clickhouse-server image on the eks cluster on aws.
> 
> It looks like a permission issue, especially 'The AWS Access Key Id you provided does not exist in our records', it seems using China regions with Global AK/SK or the opposite, and 'Access Denied' might be role used in IRSA cannot access S3.

Thanks for your help. But it seems that either of the cases you mentioned wasn't what I ran into.

**Comment by Zhile** [comment]
Hi @davidshtian, I use IAM role to access the files in S3. 
When I use `aws s3 cp s3://my-bucket/1.csv .`, I can get the file I want. But when I use ClickHouse, there's always error like 

```
Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = SSL Exception: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED,
```
The config I use is like 
```
<yandex>
    <s3>
       <my_endpoint>
           <endpoint>https://s3.us-east-1.amazonaws.com</endpoint>
           <region>us-east-1</region>
           <use_environment_credentials>true</use_environment_credentials>
       </my_endpoint>
   </s3>
</yandex>
```
The bucket is private and we don't want to make it public. Is there any error in the config?

**Comment by UnamedRus** [comment]
@Zhile 

Which operation system do you use?

If it's something other than ubuntu based, look here: https://github.com/ClickHouse/ClickHouse/issues/18869#issuecomment-757111029

**Comment by Zhile** [comment]
Thanks,  @UnamedRus. I think you're right. It's working now.

**Comment by Zhile** [comment]
If you use **use_environment_credentials**, another thing may be useful: 
* if your s3 path is prefixed by HTTP, you should have an endpoint with HTTP.  
* if your s3 path is prefixed by HTTPS, you should have an endpoint with HTTPS. You can put them in the config together. 
* This configuration doesn't need to restart the server. 
```
<s3>
  <my_endpoint_https>
    <endpoint>https://s3.us-east-1.amazonaws.com</endpoint>
    <region>us-east-1</region>
    <use_environment_credentials>true</use_environment_credentials>
  </my_endpoint_https>
  <my_endpoint_http>
    <endpoint>http://s3.us-east-1.amazonaws.com</endpoint>
    <region>us-east-1</region>
    <use_environment_credentials>true</use_environment_credentials>
  </my_endpoint_http>
</s3>
```
Then you can query HTTP s3 
```
select count() from s3('http://s3.us-east-1.amazonaws.com/test/tests1.txt','CSV','da date, name String')
```
or HTTPS s3
```
select count() from s3('https://s3.us-east-1.amazonaws.com/test/tests1.txt','CSV','da date, name String')
```

If you only put HTTPs endpoint in config.xml, and query data on http://s3.us-east-1.amazonaws.com, there will be `Access Denied` error.

**Comment by partamonov** [comment]
I am having same issue. ClickHouse server version 21.8.10 revision 54449

If I have credentials in query params I can access fine, if I am using IAM role from the node (aws cli can do any required actions) or if I am putting credentials to 'config.d' directory then I am getting Access Denied.

```
Could not list objects in bucket '....' with prefix 'blah', S3 exception: `AccessDenied`, message: 'Access Denied'.
``` 

config file
```
<yandex>
            <s3>
               <my_endpoint>
                   <endpoint>https://s3.eu-west-1.amazonaws.com</endpoint>
                   <region>eu-west-1</region>
                   <access_key_id>...</access_key_id>
                   <secret_access_key>....</secret_access_key>
                   <use_environment_credentials>false</use_environment_credentials>
               </my_endpoint>
           </s3>
</yandex>
```

query is
```
select count(*) from s3('https://s3.eu-west-1.amazonaws.com/xxx/arrival_date*/*.orc', 'ORC', '`arrival_date` ...')
```

**Comment by UnamedRus** [comment]
```
                   <use_environment_credentials>false</use_environment_credentials>
```

Change this to true
