### ISSUE TITLE
Catboost model reload

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#18722]
Provide a way to reload / add / remove catboost models w/o server restart.

**Comment by oleg-savko** [comment]
It would be great if in catboost configuration file we can specify for example s3 bucket, and clickhouse load models from it periodically.

**Comment by filimonov** [comment]
@kitaisreal those catboost models are almost the same as dictionaries :) So maybe you can pick it?

**Comment by filimonov** [comment]
Great! BTW it was also reported that touching config file with model doesn't trigger the model reload (but maybe it is not so important since we have system reload....)

**Comment by alexey-milovidov** [comment]
Not important at all.

**Comment by Avogar** [comment]
> Great! BTW it was also reported that touching config file with model doesn't trigger the model reload (but maybe it is not so important since we have system reload....)

Check https://github.com/ClickHouse/ClickHouse/pull/22434
