### ISSUE TITLE
ClickHouse testing version is asking some questions about Kerberos.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#18734]
It's clearly a bug. I don't need Kerberos.

**Comment by alexey-milovidov** [comment]
@traceon It happens when I install ClickHouse on AWS.

**Comment by traceon** [comment]
None of my changes relevant to Kerberos (#14995) have been merged yet.

Here are the most probable candidates: #16621 and #12771.

@alexey-milovidov What does ClickHouse testing version ask about Kerberos exactly though?

**Comment by alexey-milovidov** [comment]
After asking password for default user (with pink dialog) it asks about Kerberos realm in the same way.

**Comment by traceon** [comment]
@ilejn can this be caused by your #16621?

**Comment by alexey-milovidov** [comment]
Most likely caused by https://github.com/ClickHouse/ClickHouse/pull/16621/files#diff-2a13f1344504379e877324d3a0375adcbcb4cb27d7e575ad8f4618a52d6a00e0R43

I will remove it.

**Comment by ilejn** [comment]
It seems that Alexey is right and the issue is caused by "Recommends: krb5-user" in debian control file. 
Looking into it.
