### ISSUE TITLE
Group-by query keep changing results when enable distributed_aggregation_memory_efficient

### ISSUE THREAD

**Issue by sundy-li** [ClickHouse/ClickHouse#18756]
(you don't have to strictly follow this form)

**Describe the bug**

Group-by query keep changing results when enable distributed_aggregation_memory_efficient

** version

v20.3.8.53

**How to reproduce**

 Hard to reproduce locally
 
**Additional context**
```
cat ~/a.sql
 
SELECT uid
    FROM
    (
        SELECT uid
        FROM app.app_user_info_day_all
        WHERE ((day >= '2020-10-01') AND (day <= '2020-10-01')) AND (charge_countrycode IN ('FR', 'BE'))
        GROUP BY uid
    )
    GROUP BY uid
 settings max_threads = 32, skip_unavailable_shards = 0
```

```
for i in `seq 1 30`;do cat ~/a.sql | clickhouse-client --distributed_aggregation_memory_efficient 1  | wc -l
done

522139
522139
499914
499914
499914
522139
522139
522139
522139
```

```
for i in `seq 1 30`;do cat ~/a.sql | clickhouse-client --distributed_aggregation_memory_efficient 0  | wc -l
done
522139
522139
522139
522139
522139
522139
522139
```

```
> grep -Eo 'Total aggregated. [0-9]+' 499914_trace.log | sort > a.log
> grep -Eo 'Total aggregated. [0-9]+' 522139_trace.log | sort > b.log
> diff a.log b.log


```

Total aggregated value are the same , no differs …

If I use settings max_threads = 1, it's a stable result too.

cc @filimonov

**Comment by filimonov** [comment]
Maybe https://github.com/ClickHouse/ClickHouse/pull/10063 ?

Update at least to latest patch-release of 20.3 (better - to some newer version).

**Comment by sundy-li** [comment]
> Maybe #10063 ?
> 
> Update at least to latest patch-release of 20.3 (better - to some newer version).

No, we already have this commit in production.

**Comment by sundy-li** [comment]
Can't reproduce it with the latest code `20.12.1.1`, I use it to query the online data by distributed table.

Maybe it's already fixed in master.
