### ISSUE TITLE
ClickHouseProfileEvents_ZooKeeperWaitMicroseconds very big

### ISSUE THREAD

**Issue by gj-zhang** [ClickHouse/ClickHouse#18759]
ClickHouseProfileEvents_ZooKeeperWaitMicroseconds 6564505184722
after 1min
ClickHouseProfileEvents_ZooKeeperWaitMicroseconds 6567706573267

About 3000 seconds

please help.

**Comment by alexey-milovidov** [comment]
3000 seconds spent for one minute means that you have at least 50 concurrent requests to ZooKeeper which is normal if you have at least a few 10s of Replicated tables.

**Comment by gj-zhang** [comment]
> 3000 seconds spent for one minute means that you have at least 50 concurrent requests to ZooKeeper which is normal if you have at least a few 10s of Replicated tables.

ok thank you

**Comment by zhoupengbo** [comment]
What does this indicator mean?  ClickHouseProfileEvents_ZooKeeperWaitMicroseconds 
@alexey-milovidov my nums is about 10 hours, and increacing...

**Comment by alexey-milovidov** [comment]
It means that 10 hours has been spent in waiting for responses from ZooKeeper since server startup.
The waiting is done asynchronously and in parallel, so you'd better not to care.
