### ISSUE TITLE
Clickhouse Nested issue

### ISSUE THREAD

**Issue by vladomelchenko** [ClickHouse/ClickHouse#18765]
After you create table with fields with dots and after alter table clickhouse throw exception about bad cast
version 20.12.3

How to reproduce

```
CREATE TABLE test_nested
(
    `id` String,
    `with_dot.str` String,
    `with_dot.array` Array(Int32)
)
ENGINE = MergeTree()
ORDER BY id


Insert Into test_nested (id,`with_dot.str`, `with_dot.array`) VALUES('123','asd',[1,2])

select * FROM test_nested


SELECT *
FROM test_nested

Query id: 42f26a6e-7573-4169-a4a1-9fe7022ba656

┌─id──┬─with_dot.str─┬─with_dot.array─┐
│ 123 │ asd          │ [1,2]          │
└─────┴──────────────┴────────────────┘

alter table test_nested ADD COLUMN `with_dot.bool` UInt8


SELECT *
FROM test_nested

Query id: 3ea8ae6b-1e0a-4ae5-b4d0-dcdcb6b7b8f8


Received exception from server (version 20.12.3):
Code: 49. DB::Exception: Received from localhost:9000. DB::Exception: Bad cast from type DB::DataTypeNumber<char8_t> to DB::DataTypeArray: (while reading from part /var/lib/clickhouse/store...
```

I think that happend because clickhouse after altert think that field `with_dot.bool` is nested and trying to cast to array, but i'm not creating nested field, i'm only use field name with `.`

**Comment by den-crane** [comment]
Dot in column names has a special/reserved meaning. CH expects that columns with dot is Arrays.
Do not use dot.

**Comment by vladomelchenko** [comment]
> Dot in column names has a special/reserved meaning. CH expects that columns with dot is Arrays.
> Do not use dot.

But why that works without alter?

**Comment by vladomelchenko** [comment]
and i think you need specify that rule here https://clickhouse.tech/docs/en/sql-reference/syntax/#syntax-identifiers

**Comment by vladomelchenko** [comment]
and if field names with dot not contains array all works fine even after alter

**Comment by alexey-milovidov** [comment]
Still relevant in 20.8 (master).

**Comment by shabashev-ivan** [comment]
Все еще не исправлено
