### ISSUE TITLE
MaterializeMySQL引擎同步mysql5.7增量数据就会提示错误

### ISSUE THREAD

**Issue by xinge-1** [ClickHouse/ClickHouse#18761]
2021.01.05 17:29:28.806968 [ 13966 ] {a941b042-b637-42ca-ae42-5d6b765233a3} <Error> TCPHandler: Code: 32, e.displayText() = DB::Exception: Attempt to read after eof, Stack trace:

0. DB::ReadBuffer::throwReadAfterEOF() @ 0x7d3f9ed in /usr/bin/clickhouse
1. ? @ 0xdb3d0a3 in /usr/bin/clickhouse
2. DB::MySQLReplication::MySQLFlavor::readPayloadImpl(DB::ReadBuffer&) @ 0xdb41983 in /usr/bin/clickhouse
3. DB::MySQLProtocol::IMySQLReadPacket::readPayload(DB::ReadBuffer&, unsigned char&) @ 0xdb29bb2 in /usr/bin/clickhouse
4. DB::MySQLProtocol::PacketEndpoint::tryReceivePacket(DB::MySQLProtocol::IMySQLReadPacket&, unsigned long) @ 0xdb2a6a3 in /usr/bin/clickhouse
5. DB::MaterializeMySQLSyncThread::synchronization(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xdb544b6 in /usr/bin/clickhouse
6. ? @ 0xdb72e2a in /usr/bin/clickhouse
7. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x7d25aad in /usr/bin/clickhouse
8. ? @ 0x7d295d3 in /usr/bin/clickhouse
9. start_thread @ 0x7e65 in /usr/lib64/libpthread-2.17.so
10. __clone @ 0xfe88d in /usr/lib64/libc-2.17.so

**Comment by xinge-1** [comment]
binlog_checksum  = CRC32

**Comment by xinge-1** [comment]
![image](https://user-images.githubusercontent.com/76768331/103633075-2def5580-4f80-11eb-80a4-e10b121d228d.png)

**Comment by xinge-1** [comment]
binlog_gtid_simple_recovery	ON
enforce_gtid_consistency	ON
gtid_executed_compression_period	1000
gtid_mode	ON
gtid_next	AUTOMATIC
gtid_owned	
gtid_purged	6434c3f1-e69c-11ea-a8f5-fa163ed60b44:1-11586025,
66397238-e692-11ea-a178-fa163eaa7f61:1-13235043
session_track_gtids	OFF

**Comment by xinge-1** [comment]
binlog_format	ROW

**Comment by xinge-1** [comment]
全量同步没有问题，但是当源数据库MySQL有增量数据写入，错误日志就会出现上面错误。

**Comment by zhang2014** [comment]
ClickHouse使用的版本是?

**Comment by xinge-1** [comment]
> ClickHouse使用的版本是吗？

ClickHouse client version 20.12.4.5 (official build).
Connecting to 172.21.128.5:9000 as user default.
Connected to ClickHouse server version 20.12.4 revision 54442.

ecs-ghubnew-uat-db5.ghub :) select version();

SELECT version()

Query id: c7afab8c-570e-44ab-9558-22a5c1a06383

┌─version()─┐
│ 20.12.4.5 │
└───────────┘

1 rows in set. Elapsed: 0.001 sec.

**Comment by xinge-1** [comment]
> ClickHouse使用的版本是?

找到原因了 是MaterializeMySQL同步不支持V1版本的binlog

**Comment by linshuchang** [comment]
mysql和clickhouse在两台服务器上，MaterializeMySQL引擎同步MySQL数据时,当mysql所在服务器重启后，mysql再新增数据或者其他操作时，clickhouse数据没有任何变化。必须要重启clickhouse数据库才行，这个如何解决？
