### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by xiaobao3315** [ClickHouse/ClickHouse#18778]
clickhouse version is 20.5.4.40

1、create table sql is :
_CREATE TABLE local.ods_log_ecm_event_kafka
(
    `user` String,
    `os_type` String,
    `app_name` String,
    `app_version` String,
    `network_type` String,
    `event_id` String,
    `event_duration` UInt16,
    `event_type` String,
    `event_data` String,
    `device_id` String,
    `up_date` String,
    `cre_date` Date DEFAULT toDate(now())
)
ENGINE = MergeTree
PARTITION BY toDate(cre_date)
ORDER BY tuple()
SETTINGS index_granularity = 8192_

2、then insert datas:

_INSERT INTO local.ods_log_ecm_event_kafka (user, os_type, app_name, app_version, network_type, event_id, event_duration, event_type, event_data, device_id, up_date, cre_date) VALUES
('F051901', 'Android 10', '员圈', '3.16.1.1', 'wifi', '2c809641-7440-49e7-8ac9-a1475c0d1441', 0, 'login', '{"time":1600256013706,"params":""}', 'f8bb176ab9465e9d', '1600256013707', '2020-09-16'),
('A161160', 'iOS 11.2.1', '圈立方', '1.23.0', 'cellular', 'c69f5d5e-d55e-426f-8604-ac24240bc51f', 0, 'ProductDetailPageStay', '{"skuName":"物生物（RELEA）焖烧杯便携小型保温桶闷烧罐女学生便当盒餐盒上班族316不锈钢饭盒550ML 糖豆桂花黄","skuCode":"000000000000550045","stayTime":"6.937","userName":"庞军","uid":"A161160"}', 'F887037D-CFB0-43B2-AA3A-70449583ED8D', '1600256016440', '2020-9-16'),                                                                                                                                                                                 ('S0011078', 'Android 9', '员圈', '3.16.1.1', 'wifi', 'b607d131-fb21-458d-a6d3-aa511c8f7848', 0, 'login', '{"time":1600255998198,"params":""}', '519416da98f812ed', '1600255998200', '2020-09-16'),
('s0010200', 'Android 10', '员圈', '3.16.1.1', 'cellular', '0ed24618-c1c1-4f40-b601-ee370555340a', 0, 'click_productDetails', '{"time":1600255999350,"params":{"router":"productDetails","routeName":"商品详情","skuCode":"000000000000315003","maiDianId":"s0010200_1600255999347"}}', '1b558feab5dbb5e2', '1600255999350', '2020-09-16'),
('f201762', 'iOS 13.6', '员圈', '3.16.1.1', 'cellular', 'c86da51e-e504-4abd-b0bb-3037d494ea94', 0, 'click_productDetails', '{"time":1600256001876,"params":{"router":"productDetails","routeName":"商品详情","skuCode":"000000000000558152","maiDianId":"f201762_1600256001876"}}', '82C2CA3B-185D-4E7E-8C69-26A2C5F750B6', '1600256001876', '2020-09-16');_

3 then execute sql server crash

_select *from local.ods_log_ecm_event_kafka WHERE up_date = toString(toUnixTimestamp64Milli(toDateTime64('2019-09-16 00:00:00', 0)))_

what problem with the sql?

**Comment by den-crane** [comment]
Works fine against 20.13.1.5579

20.5.4.40 is out support. 
Check with stable or LTS releases. 20.8.11.17 / 20.10.6.27 / 20.11.7.4 /  20.12.5.14

**Comment by alexey-milovidov** [comment]
@den-crane We can create a test with these queries pasted verbatim.

**Comment by den-crane** [comment]
@xiaobao3315 can you clarify. What do you exactly mean by "server crash"? Empty query result or CH server crash?

**Comment by xiaobao3315** [comment]
@den-crane  CH server crash

**Comment by den-crane** [comment]
@xiaobao3315 can you provide logs with crash messages?

**Comment by alexey-milovidov** [comment]
No answer...
