### ISSUE TITLE
How to deal with the setting of primary key and index in new business table creation

### ISSUE THREAD

**Issue by shadowDy** [ClickHouse/ClickHouse#18784]
When creating a new business table, we don't know the query latitude, query scenario, query mode and other information. However, the setting, order and index configuration of primary key and sorting construction have a great impact on the query performance of Clickhouse. At present, the cluster does not support the change of primary key and sorting construction order. How to guarantee the query performance in this scenario? Or do you have any good suggestions for new business, sorting and primary key setting when creating tables?

**Comment by den-crane** [comment]
>Or do you have any good suggestions

No. We still unable predict the future. Just test on a daily data, choose some suitable table structure. Re-work / reload data later if needed.

**Comment by shadowDy** [comment]
> Re-work / reload data later if needed.

In this mode, when adding columns to the table that need high-frequency query, you need to adjust the order of the sort key, and you need to replay all the data. It's too troublesome

**Comment by den-crane** [comment]
> > Re-work / reload data later if needed.
> 
> In this mode, when adding columns to the table that need high-frequency query, you need to adjust the order of the sort key, and you need to replay all the data. It's too troublesome

The problem that you don't not have options with CH. 
There is no magic. Terra-bytes of data cannot be reordered for free. It needs to read/uncompress/sort/compress/write.
