### ISSUE TITLE
how to fill result set with missed rows

### ISSUE THREAD

**Issue by mbtolou** [ClickHouse/ClickHouse#18786]
how to fill result set with missed rows ?

main result is 

|A|B|
|---|---|
|saterday|100|
|sunday|250|
|monday|450|

desired result 

|A|B|
|---|---|
|saterday|100|
|sunday|250|
|monday|450|
|tuesday|NULL|
|wednesday|NULL|
|thursday|NULL|
|friday|NULL|

Tuesday

what is the easiest way to fill missed rows in result set ?

**Comment by stigsb** [comment]
Maybe LEFT JOIN is what you are looking for?

**Comment by mbtolou** [comment]
something like

WITH FILL arrayJoin(['a','b'])

**Comment by vegastar002** [comment]
用右联(right join)
