### ISSUE TITLE
Problem with View Create Query

### ISSUE THREAD

**Issue by BhavyaRajSharma** [ClickHouse/ClickHouse#18783]
**Problem Statement:**
I was trying to create a view using the following query :
`CREATE OR REPLACE VIEW dbpolaris1.visit_sp_view10 on cluster API AS SELECT sp.imsi,sp.staypointstartdate,sp.staypointenddate,sp.lat,sp.lon,sp.unc,sp.spid,sp.ccn,sp.locationCCN,sp.operator,v.msisdn,v.imei,v.visitstartdate,v.visitenddate FROM dbpolaris1.visit AS v FINAL INNER JOIN (SELECT sp.imsi,sp.staypointstartdate,sp.staypointenddate,sp.lat,sp.lon,sp.unc,sp.spid,sp.ccn,sp.locationCCN,sp.operator from dbpolaris1.staypoint AS sp FINAL WHERE sp.isactive = 1) AS sp USING (imsi,spid)
`
after running the query I got an exception saying default.staypoint_local doesn't exit. In the query, I am using staypoint table which is a distributed table that points to the staypoint_local table. Both the tables are in a database "dbpolaris1", but somehow view creation query trying to find the local table in the default database.

**Query Error:**

> Received exception from server (version 20.8.9):
> Code: 60. DB::Exception: Received from localhost:9100. DB::Exception: There was an error on [10.49.3.106:9100]: Code: 60, e.displayText() = DB::Exception: Table default.staypoint_local doesn't exist. (version 20.8.9.6 (official build)). 
> 

### Note: I am using <distributed_product_mode>local</distributed_product_mode> in user.xml

**STAYPOINT CREATE COMMAND:**

> 		CREATE TABLE dbpolaris1.staypoint
> 		(
> 			`imsi` Int64 CODEC(Delta(8), Default),
> 			`staypointstartdate` DateTime CODEC(Delta(4), Default),
> 			`staypointenddate` DateTime CODEC(Delta(4), Default),
> 			`lat` Float64 CODEC(Gorilla, Default),
> 			`lon` Float64 CODEC(Gorilla, Default),
> 			`unc` Float64 CODEC(Gorilla, Default),
> 			`spid` Int64 CODEC(T64, Default),
> 			`ccn` LowCardinality(String),
> 			`locationCCN` LowCardinality(String),
> 			`operator` LowCardinality(String),
> 			`ver` DateTime CODEC(Delta(4), Default),
> 			`isactive` Int8 CODEC(T64, Default)
> 		)
> 		ENGINE = Distributed('API', '', 'staypoint_local', imsi % 2)
> 

**STAYPOINT_LOCAL CREATE COMMAND:**

> 		CREATE TABLE dbpolaris1.staypoint_local
> 		(
> 			`imsi` Int64 CODEC(Delta(8), Default),
> 			`staypointstartdate` DateTime CODEC(Delta(4), Default),
> 			`staypointenddate` DateTime CODEC(Delta(4), Default),
> 			`lat` Float64 CODEC(Gorilla, Default),
> 			`lon` Float64 CODEC(Gorilla, Default),
> 			`unc` Float64 CODEC(Gorilla, Default),
> 			`spid` Int64 CODEC(T64, Default),
> 			`ccn` LowCardinality(String),
> 			`locationCCN` LowCardinality(String),
> 			`operator` LowCardinality(String),
> 			`ver` DateTime CODEC(Delta(4), Default),
> 			`isactive` Int8 CODEC(T64, Default),
> 			INDEX imsi_index1 imsi TYPE minmax GRANULARITY 3,
> 			INDEX spid_index2 spid TYPE minmax GRANULARITY 1,
> 			INDEX locationCCN_index3 locationCCN TYPE set(0) GRANULARITY 4,
> 			INDEX operator_index4 operator TYPE set(0) GRANULARITY 4
> 		)
> 		ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{shard1}/staypoint', '{replica1}', ver)
> 		PARTITION BY toYYYYMMDD(staypointstartdate)
> 		ORDER BY (imsi, spid)
> 

		
**VISIT CREATE COMMAND:**

> 		CREATE TABLE dbpolaris1.visit
> 		(
> 			`imsi` Int64 CODEC(Delta(8), Default),
> 			`msisdn` Nullable(String),
> 			`imei` Nullable(String),
> 			`visitstartdate` DateTime CODEC(Delta(4), Default),
> 			`visitenddate` DateTime CODEC(Delta(4), Default),
> 			`spid` Int64 CODEC(T64, Default),
> 			`ver` DateTime CODEC(Delta(4), Default)
> 		)
> 		ENGINE = Distributed('API', '', 'visit_local', imsi % 2)
> 

**VISIT_LOCAL CREATE COMMAND:**

> 		CREATE TABLE dbpolaris1.visit_local
> 		(
> 			`imsi` Int64 CODEC(Delta(8), Default),
> 			`msisdn` Nullable(String),
> 			`imei` Nullable(String),
> 			`visitstartdate` DateTime CODEC(Delta(4), Default),
> 			`visitenddate` DateTime CODEC(Delta(4), Default),
> 			`spid` Int64 CODEC(T64, Default),
> 			`ver` DateTime CODEC(Delta(4), Default),
> 			INDEX imsi_index1 imsi TYPE minmax GRANULARITY 3,
> 			INDEX visitstartdate_index2 visitstartdate TYPE minmax GRANULARITY 1,
> 			INDEX visitenddate_index3 visitenddate TYPE minmax GRANULARITY 1,
> 			INDEX spid_index4 spid TYPE minmax GRANULARITY 1
> 		)
> 		ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{shard1}/visit', '{replica1}', ver)
> 		PARTITION BY toYYYYMMDD(visitstartdate)
> 		ORDER BY (imsi, visitstartdate)
> 

**API CLUSTER:**

> 		<API>
>                 <shard>
>                 <internal_replication>true</internal_replication>
>                         <replica>
>                                 <default_database>dbpolaris1</default_database>
>                                 <host>10.49.3.106</host>
>                                 <port>9100</port>
>                         </replica>
>                         <replica>
>                                 <default_database>dbpolaris1_replica</default_database>
>                                 <host>10.49.3.104</host>
>                                 <port>9100</port>
>                         </replica>
>                 </shard>
>                 <shard>
>                 <internal_replication>true</internal_replication>
>                         <replica>
>                                 <default_database>dbpolaris1</default_database>
>                                 <host>10.49.3.104</host>
>                                 <port>9100</port>
>                         </replica>
>                         <replica>
>                                 <default_database>dbpolaris1_replica</default_database>
>                                 <host>10.49.3.106</host>
>                                 <port>9100</port>
>                         </replica>
>                 </shard>
>         </API>
> 

**ClickHouse Version Used**
ClickHouse client version 20.8.9.6 (official build).
Connected to ClickHouse server version 20.8.9 revision 54438.

**Comment by den-crane** [comment]
Does this `SELECT sp.imsi,sp.staypointstartdate,...` from VIEW work (without create view) ?

**Comment by BhavyaRajSharma** [comment]
@den-crane,
No. It is giving the same thing with select query only.

> DEV-BDSP-Worker-06 :) SELECT sp.imsi,sp.staypointstartdate,sp.staypointenddate,sp.lat,sp.lon,sp.unc,sp.spid,sp.ccn,sp.locationCCN,sp.operator,v.msisdn,v.imei,v.visitstartdate,v.visitenddate FROM dbpolaris1.visit AS v FINAL INNER JOIN (SELECT sp.imsi,sp.staypointstartdate,sp.staypointenddate,sp.lat,sp.lon,sp.unc,sp.spid,sp.ccn,sp.locationCCN,sp.operator from dbpolaris1.staypoint AS sp FINAL WHERE sp.isactive = 1) AS sp USING (imsi,spid)
> 
> SELECT 
>     sp.imsi,
>     sp.staypointstartdate,
>     sp.staypointenddate,
>     sp.lat,
>     sp.lon,
>     sp.unc,
>     sp.spid,
>     sp.ccn,
>     sp.locationCCN,
>     sp.operator,
>     v.msisdn,
>     v.imei,
>     v.visitstartdate,
>     v.visitenddate
> FROM dbpolaris1.visit AS v
> FINAL
> INNER JOIN 
> (
>     SELECT 
>         sp.imsi,
>         sp.staypointstartdate,
>         sp.staypointenddate,
>         sp.lat,
>         sp.lon,
>         sp.unc,
>         sp.spid,
>         sp.ccn,
>         sp.locationCCN,
>         sp.operator
>     FROM dbpolaris1.staypoint AS sp
>     FINAL
>     WHERE sp.isactive = 1
> ) AS sp USING (imsi, spid)
> 
> 
> Received exception from server (version 20.8.9):
> Code: 60. DB::Exception: Received from localhost:9100. DB::Exception: Table default.staypoint_local doesn't exist.. 
> 
> 0 rows in set. Elapsed: 0.004 sec. 
> 
> DEV-BDSP-Worker-06 :) 
>

**Comment by den-crane** [comment]
ah, OK. 

CH does not support JOINs for distributed tables in circle-replication. 

https://github.com/ClickHouse/ClickHouse/issues/6571
https://github.com/ClickHouse/ClickHouse/issues/3196

The best option for you to do not use  circle-replication.

**Comment by BhavyaRajSharma** [comment]
hi @den-crane, I have changed the CH topology as described below but still facing the same problem as mentioned above : 

```
<API>
            <shard>
            <internal_replication>true</internal_replication>
                    <replica>
                            <default_database>dbpolaris1</default_database>
                            <host>10.49.3.103</host>
                            <port>9100</port>
                    </replica>
                    <replica>
                            <default_database>dbpolaris1</default_database>
                            <host>10.49.3.108</host>
                            <port>9100</port>
                    </replica>
            </shard>
            <shard>
            <internal_replication>true</internal_replication>
                    <replica>
                            <default_database>dbpolaris1</default_database>
                            <host>10.49.3.105</host>
                            <port>9100</port>
                    </replica>
                    <replica>
                            <default_database>dbpolaris1</default_database>
                            <host>10.49.3.111</host>
                            <port>9100</port>
                    </replica>
            </shard>
    </API>
```
