### ISSUE TITLE
how to select >0 column

### ISSUE THREAD

**Issue by vegastar002** [ClickHouse/ClickHouse#18807]
select * from
(select * from
(WITH [0, 0, 0] AS d1, [0, 1, 0] AS t1, [3, 0, 0] AS t2
select d1, t1, t2 ) array join d1, t1, t2
);

┌─d1─┬─t1─┬─t2─┐
│  0 │  0 │  3 │
│  0 │  1 │  0 │
│  0 │  0 │  0 │
└────┴────┴────┘

the d1 column total is 0, finally want : 

┬─t1─┬─t2─┐
│ 0  │ 3  │
│ 1  │ 0  │
│ 0  │ 0  │
┴────┴────┘
because sum(d1) is 0 , don't show .

how to write sql ?

**Comment by alexey-milovidov** [comment]
I don't understand your question quite well.

**Comment by hexiaoting** [comment]
@vegastar002 
you want to skip column b (because sum(b) == 0) to get the following result?
```
┌─t1─┬─t2─┐
│  0 │  3 │
│  1 │  0 │
│  0 │  0 │
└────┴────┘
```

**Comment by vegastar002** [comment]
> @vegastar002
> you want to skip column b (because sum(b) == 0) to get the following result?
> 
> ```
> ┌─t1─┬─t2─┐
> │  0 │  3 │
> │  1 │  0 │
> │  0 │  0 │
> └────┴────┘
> ```

Yes !!!

**Comment by hexiaoting** [comment]
@vegastar002 
As I know, it is difficult to write the sql when we don't know the select schema.
maybe column transformer can help, like `select * except xxx from ....`

But in this case, I'm afraid whether it can be written in sql or not.
Waiting for others to give you the sql you want.

**Comment by den-crane** [comment]
```sql
select (arrayJoin(g) as ag).1 d1, ag.2 t1, ag.3 t2 from 
(select sum(d1) s, groupArray( (d1, t1, t2) ) g from
         (WITH [0, 0, 0] AS d1, [0, 1, 0] AS t1, [3, 0, 0] AS t2 select d1, t1, t2 ) array join d1, t1, t2
having s = 0       ---------<------
)

┌─d1─┬─t1─┬─t2─┐
│  0 │  0 │  3 │
│  0 │  1 │  0 │
│  0 │  0 │  0 │
└────┴────┴────┘
```

**Comment by hexiaoting** [comment]
> ```sql
> select (arrayJoin(g) as ag).1 d1, ag.2 t1, ag.3 t2 from 
>      (select sum(d1) s, groupArray( (d1, t1, t2) ) g from
>          (WITH [0, 0, 0] AS d1, [0, 1, 0] AS t1, [3, 0, 0] AS t2 select d1, t1, t2 ) array join d1, t1, t2
>        having s = 0       ---------<------
>      )
> ```

I'm afraid this is not what the author want. @vegastar002  Do you mean this?
how to remove the columns whose sum() equals 0. If we do not know these column names at first?
