### ISSUE TITLE
fetch partition does not support macro in ZK path

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#18805]
CREATE TABLE test (i Int64, s String)
ENGINE = ReplicatedMergeTree ('/clickhouse/{cluster}/tables/test','{replica}') ORDER BY i;

insert into test select 1, '';

CREATE TABLE restore (i Int64, s String)
ENGINE = ReplicatedMergeTree ('/clickhouse/{cluster}/tables/restore','{replica}') ORDER BY i;

alter table restore fetch partition tuple() from '/clickhouse/{cluster}/tables/test';

DB::Exception: No node, path: /clickhouse/**{cluster}**/tables/test/replicas.

Expected: macro {cluster} to be substituted the same way as with CREATE TABLE

**Comment by fastio** [comment]
Hi, Please assign it to me.
