### ISSUE TITLE
 Can I add new columns without stopping inserting data

### ISSUE THREAD

**Issue by intfish123** [ClickHouse/ClickHouse#18819]
Make sure to check documentation https://clickhouse.yandex/docs/en/ first. If the question is concise and probably has a short answer, asking it in Telegram chat https://telegram.me/clickhouse_en is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

If you still prefer GitHub issues, remove all this text and ask your question here.

Can I add new columns without stopping inserting data

**Comment by den-crane** [comment]
Yes you can.

1. add columns to MergeTree tables at ALL nodes.
2. add columns to Distributed tables at ALL nodes.
3. add columns to Buffer_ingene tables at ALL nodes.
