### ISSUE TITLE
Which kind of Merge Engines are supported in Materialized View?

### ISSUE THREAD

**Issue by wallace-clickhouse** [ClickHouse/ClickHouse#18825]
Which kind of engines are supported in Materialized View?
I tried  the MergeTree()  in  creating a materialized view and it didn't work(when data is inserted into original left table,no data found by select from materialized view).
Such as
_CREATE MATERIALIZED VIEW test_mv ENGINE = MergeTree() ORDER BY tuple() AS SELECT aaa.value, bbb.name FROM table_test as aaa INNER JOIN dimension as bbb ON aaa.value = bbb.value;_

**Comment by den-crane** [comment]
Any engine is supported.

```sql
CREATE MATERIALIZED VIEW test_mv 
ENGINE = MergeTree() ORDER BY tuple() AS 
SELECT table_test.value, dimension.name 
FROM table_test 
  INNER JOIN dimension
    ON table_test.value = dimension.value;


create table table_test (value Int64) Engine = MergeTree() order by value;  

create table dimension (value Int64, name String) Engine = MergeTree() order by value;  

insert  into dimension values (1, 'test'), (2, 'xxx');

insert  into table_test values (1), (2);

select * from test_mv;

┌─value─┬─name─┐
│     1 │ test │
│     2 │ xxx  │
└───────┴──────┘

```

https://den-crane.github.io/Everything_you_should_know_about_materialized_views_commented.pdf

https://youtu.be/ckChUkC3Pns?t=9326
