### ISSUE TITLE
clickhouse server start failed

### ISSUE THREAD

**Issue by JunjianS** [ClickHouse/ClickHouse#18822]
Version: clickhouse 20.10.tgz
OS: centos7
cluster have 3 nodes

use command  systemctl start clickhouse-server,  then check status , but get below error and no log file

systemctl status clickhouse-server
● clickhouse-server.service - ClickHouse Server (analytic DBMS for big data)
   Loaded: loaded (/etc/systemd/system/clickhouse-server.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Thu 2021-01-07 16:53:56 CST; 3s ago
  Process: 3281 ExecStart=/usr/bin/clickhouse-server --config=/etc/clickhouse-server/config.xml --pid-file=/run/clickhouse-server/clickhouse-server.pid (code=exited, status=232/ADDRESS_FAMILIES)
 Main PID: 3281 (code=exited, status=232/ADDRESS_FAMILIES)

**Comment by den-crane** [comment]
>clickhouse 20.10.tgz

it seems you did not install clickhouse binary.
Why did you use tgz instead of recommended way with yum/rpm ?

**Comment by alexey-milovidov** [comment]
@den-crane `tgz` is valid installation option, the same as `deb` or `rpm`.

**Comment by den-crane** [comment]
@alexey-milovidov I know. But  @JunjianS have installed clickhouse-server.tgz without clickhouse-common-static.tgz
and now unable to start CH without /usr/bin/clickhouse

**Comment by JunjianS** [comment]
> > clickhouse 20.10.tgz
> 
> it seems you did not install clickhouse binary.
> Why did you use tgz instead of recommended way with yum/rpm ?

thanks ,i have to use tgz, because the server cannot access the Internet,  i reinstall it and no problem now,
