### ISSUE TITLE
I don't get expect improvement when I use sample. How does it work?

### ISSUE THREAD

**Issue by tangxueming** [ClickHouse/ClickHouse#18824]
I check in issues list, but I don't find useful info. So I post this issue.
And there is  little info about sample in document.
**1.Why I need sample?**
    My dataset is huge, one day  5 billions rows. When I query more than 3 days data, the query execute timeout. I guess sample feature may help me.

**2. Schema** 
CREATE TABLE  mydatabase.apm_zipkin_sample_shard on cluster mycluster
(
    `timestamp` UInt64,
    `id` String,
    `kind` LowCardinality(String),
    `name` LowCardinality(String),
    `traceId` String,
    `duration` UInt64,
    `time_date` Date,
    `time_date_8hour` DateTime
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/mydatabase.apm_zipkin_sample_shard/{shard}', '{replica}')
PARTITION BY (time_date, time_date_8hour)
ORDER BY (timestamp, duration, xxHash32(traceId))
SAMPLE BY xxHash32(traceId)
TTL time_date + toIntervalDay(30)
SETTINGS index_granularity = 8192;
I have simplify the schema.

**3.Query  and Log**
There are 1 billion rows in test dataset.
***(1) with sample***
``` sql
SELECT count() FROM apm_zipkin_sample_distributed  sample 0.1 WHERE ( (time_date between '2021-01-04' and '2021-01-06' ) and timestamp between '1609689600000000' and '1609945200000000' ) and (localEndpoint.serviceName =  'client' )  LIMIT 500;
```

[clickhouse1-1] 2021.01.07 18:49:01.858437 [ 198 ] {40259ecc-af13-4ec3-b5dd-ab0132b55732} <Debug> executeQuery: (from [::ffff:192.168.0.6]:63924, user: root) SELECT count() FROM apm_zipkin_sample_distributed sample 0.1 WHERE ( (time_date between '2021-01-04' and '2021-01-06' ) and timestamp between '1609689600000000' and '1609945200000000' ) and (localEndpoint.serviceName = 'client' ) LIMIT 500
[clickhouse1-1] 2021.01.07 18:49:01.860036 [ 198 ] {40259ecc-af13-4ec3-b5dd-ab0132b55732} <Debug> InterpreterSelectQuery: MergeTreeWhereOptimizer: condition "(time_date >= '2021-01-04') AND (time_date <= '2021-01-06')" moved to PREWHERE
[clickhouse1-1] 2021.01.07 18:49:01.861182 [ 198 ] {40259ecc-af13-4ec3-b5dd-ab0132b55732} <Debug> pupu_monitor.apm_zipkin_sample_shard (SelectExecutor): Key condition: unknown, unknown, and, (column 0 in [1609689600000000, +inf)), (column 0 in (-inf, 1609945200000000]), and, unknown, and, and, unknown, unknown, and, and, (column 2 in (-inf, 429496728]), and
[clickhouse1-1] 2021.01.07 18:49:01.861205 [ 198 ] {40259ecc-af13-4ec3-b5dd-ab0132b55732} <Debug> pupu_monitor.apm_zipkin_sample_shard (SelectExecutor): MinMax index condition: (column 0 in [18631, +inf)), (column 0 in (-inf, 18633]), and, unknown, unknown, and, unknown, and, and, (column 0 in [18631, +inf)), (column 0 in (-inf, 18633]), and, and
[clickhouse1-1] 2021.01.07 18:49:01.886597 [ 198 ] {40259ecc-af13-4ec3-b5dd-ab0132b55732} <Debug> pupu_monitor.apm_zipkin_sample_shard (SelectExecutor): Selected 34 parts by partition key, 34 parts by primary key, 46564 marks by primary key, 46564 marks to read from 35 ranges
[clickhouse2-1] 2021.01.07 18:49:01.889025 [ 270 ] {08986616-11dc-4ed7-825a-b84d8bd63959} <Debug> executeQuery: (from [::ffff:192.168.3.190]:57287, user: root, initial_query_id: 40259ecc-af13-4ec3-b5dd-ab0132b55732) SELECT count() FROM pupu_monitor.apm_zipkin_sample_shard SAMPLE 1 / 10 WHERE (((time_date >= '2021-01-04') AND (time_date <= '2021-01-06')) AND ((timestamp >= '1609689600000000') AND (timestamp <= '1609945200000000'))) AND (localEndpoint.serviceName = 'client') LIMIT 500
[clickhouse3-1] 2021.01.07 18:49:01.889595 [ 350 ] {3acc067b-4fbe-422b-bb86-bc39b6bbbadf} <Debug> executeQuery: (from [::ffff:192.168.3.190]:30560, user: root, initial_query_id: 40259ecc-af13-4ec3-b5dd-ab0132b55732) SELECT count() FROM pupu_monitor.apm_zipkin_sample_shard SAMPLE 1 / 10 WHERE (((time_date >= '2021-01-04') AND (time_date <= '2021-01-06')) AND ((timestamp >= '1609689600000000') AND (timestamp <= '1609945200000000'))) AND (localEndpoint.serviceName = 'client') LIMIT 500
[clickhouse2-1] 2021.01.07 18:49:01.889555 [ 270 ] {08986616-11dc-4ed7-825a-b84d8bd63959} <Debug> InterpreterSelectQuery: MergeTreeWhereOptimizer: condition "(time_date >= '2021-01-04') AND (time_date <= '2021-01-06')" moved to PREWHERE
[clickhouse2-1] 2021.01.07 18:49:01.890820 [ 270 ] {08986616-11dc-4ed7-825a-b84d8bd63959} <Debug> pupu_monitor.apm_zipkin_sample_shard (SelectExecutor): Key condition: unknown, unknown, and, (column 0 in [1609689600000000, +inf)), (column 0 in (-inf, 1609945200000000]), and, unknown, and, and, unknown, unknown, and, and, (column 2 in (-inf, 429496728]), and
[clickhouse2-1] 2021.01.07 18:49:01.890852 [ 270 ] {08986616-11dc-4ed7-825a-b84d8bd63959} <Debug> pupu_monitor.apm_zipkin_sample_shard (SelectExecutor): MinMax index condition: (column 0 in [18631, +inf)), (column 0 in (-inf, 18633]), and, unknown, unknown, and, unknown, and, and, (column 0 in [18631, +inf)), (column 0 in (-inf, 18633]), and, and
[clickhouse2-1] 2021.01.07 18:49:01.914676 [ 270 ] {08986616-11dc-4ed7-825a-b84d8bd63959} <Debug> pupu_monitor.apm_zipkin_sample_shard (SelectExecutor): Selected 32 parts by partition key, 32 parts by primary key, 46662 marks by primary key, 46662 marks to read from 33 ranges
[clickhouse3-1] 2021.01.07 18:49:01.890134 [ 350 ] {3acc067b-4fbe-422b-bb86-bc39b6bbbadf} <Debug> InterpreterSelectQuery: MergeTreeWhereOptimizer: condition "(time_date >= '2021-01-04') AND (time_date <= '2021-01-06')" moved to PREWHERE
[clickhouse3-1] 2021.01.07 18:49:01.891506 [ 350 ] {3acc067b-4fbe-422b-bb86-bc39b6bbbadf} <Debug> pupu_monitor.apm_zipkin_sample_shard (SelectExecutor): Key condition: unknown, unknown, and, (column 0 in [1609689600000000, +inf)), (column 0 in (-inf, 1609945200000000]), and, unknown, and, and, unknown, unknown, and, and, (column 2 in (-inf, 429496728]), and
[clickhouse3-1] 2021.01.07 18:49:01.891526 [ 350 ] {3acc067b-4fbe-422b-bb86-bc39b6bbbadf} <Debug> pupu_monitor.apm_zipkin_sample_shard (SelectExecutor): MinMax index condition: (column 0 in [18631, +inf)), (column 0 in (-inf, 18633]), and, unknown, unknown, and, unknown, and, and, (column 0 in [18631, +inf)), (column 0 in (-inf, 18633]), and, and
[clickhouse3-1] 2021.01.07 18:49:01.920625 [ 350 ] {3acc067b-4fbe-422b-bb86-bc39b6bbbadf} <Debug> pupu_monitor.apm_zipkin_sample_shard (SelectExecutor): Selected 34 parts by partition key, 34 parts by primary key, 46663 marks by primary key, 46663 marks to read from 36 ranges
[clickhouse3-1] 2021.01.07 18:49:10.458101 [ 350 ] {3acc067b-4fbe-422b-bb86-bc39b6bbbadf} <Information> executeQuery: Read 378437523 rows, 12.71 GiB in 8.568455139 sec., 44166365 rows/sec., 1.48 GiB/sec.
[clickhouse3-1] 2021.01.07 18:49:10.458122 [ 350 ] {3acc067b-4fbe-422b-bb86-bc39b6bbbadf} <Debug> MemoryTracker: Peak memory usage (for query): 8.22 MiB.
[clickhouse2-1] 2021.01.07 18:49:10.612048 [ 270 ] {08986616-11dc-4ed7-825a-b84d8bd63959} <Information> executeQuery: Read 378438410 rows, 12.71 GiB in 8.722966009 sec., 43384143 rows/sec., 1.46 GiB/sec.
[clickhouse2-1] 2021.01.07 18:49:10.612070 [ 270 ] {08986616-11dc-4ed7-825a-b84d8bd63959} <Debug> MemoryTracker: Peak memory usage (for query): 8.18 MiB.
┌─count()─┐
│ 1654706 │
└─────────┘
[clickhouse1-1] 2021.01.07 18:49:11.669930 [ 198 ] {40259ecc-af13-4ec3-b5dd-ab0132b55732} <Information> executeQuery: Read 1135399455 rows, 38.14 GiB in 9.81145631 sec., 115721807 rows/sec., 3.89 GiB/sec.
[clickhouse1-1] 2021.01.07 18:49:11.669953 [ 198 ] {40259ecc-af13-4ec3-b5dd-ab0132b55732} <Debug> MemoryTracker: Peak memory usage (for query): 12.12 MiB.

1 rows in set. Elapsed: 10.243 sec. Processed 1.14 billion rows, 40.96 GB (110.85 million rows/s., 4.00 GB/s.)

***(2) without sample***
``` sql
SELECT count() FROM apm_zipkin_sample_distributed  WHERE ( (time_date between '2021-01-04' and '2021-01-06' ) and timestamp between '1609689600000000' and '1609945200000000' ) and (localEndpoint.serviceName =  'client' )  LIMIT 500
```
[clickhouse1-1] 2021.01.07 18:47:57.729884 [ 198 ] {94b783c8-3e0e-45ad-8286-23c89faeb179} <Debug> executeQuery: (from [::ffff:192.168.0.6]:63924, user: root) SELECT count() FROM apm_zipkin_sample_distributed WHERE ( (time_date between '2021-01-04' and '2021-01-06' ) and timestamp between '1609689600000000' and '1609945200000000' ) and (localEndpoint.serviceName = 'client' ) LIMIT 500
[clickhouse1-1] 2021.01.07 18:47:57.732246 [ 198 ] {94b783c8-3e0e-45ad-8286-23c89faeb179} <Debug> InterpreterSelectQuery: MergeTreeWhereOptimizer: condition "(time_date >= '2021-01-04') AND (time_date <= '2021-01-06')" moved to PREWHERE
[clickhouse1-1] 2021.01.07 18:47:57.734379 [ 198 ] {94b783c8-3e0e-45ad-8286-23c89faeb179} <Debug> pupu_monitor.apm_zipkin_sample_shard (SelectExecutor): Key condition: unknown, unknown, and, (column 0 in [1609689600000000, +inf)), (column 0 in (-inf, 1609945200000000]), and, unknown, and, and, unknown, unknown, and, and
[clickhouse1-1] 2021.01.07 18:47:57.734412 [ 198 ] {94b783c8-3e0e-45ad-8286-23c89faeb179} <Debug> pupu_monitor.apm_zipkin_sample_shard (SelectExecutor): MinMax index condition: (column 0 in [18631, +inf)), (column 0 in (-inf, 18633]), and, unknown, unknown, and, unknown, and, and, (column 0 in [18631, +inf)), (column 0 in (-inf, 18633]), and, and
[clickhouse1-1] 2021.01.07 18:47:57.736470 [ 198 ] {94b783c8-3e0e-45ad-8286-23c89faeb179} <Debug> pupu_monitor.apm_zipkin_sample_shard (SelectExecutor): Selected 34 parts by partition key, 34 parts by primary key, 46566 marks by primary key, 46566 marks to read from 34 ranges
[clickhouse3-1] 2021.01.07 18:47:57.739307 [ 350 ] {d6121963-86ec-47d1-ad44-a402ae0f6b8d} <Debug> executeQuery: (from [::ffff:192.168.3.190]:30560, user: root, initial_query_id: 94b783c8-3e0e-45ad-8286-23c89faeb179) SELECT count() FROM pupu_monitor.apm_zipkin_sample_shard WHERE (((time_date >= '2021-01-04') AND (time_date <= '2021-01-06')) AND ((timestamp >= '1609689600000000') AND (timestamp <= '1609945200000000'))) AND (localEndpoint.serviceName = 'client') LIMIT 500
[clickhouse2-1] 2021.01.07 18:47:57.739422 [ 270 ] {59df79c3-5af7-4df2-9dbc-3713d1453d79} <Debug> executeQuery: (from [::ffff:192.168.3.190]:57287, user: root, initial_query_id: 94b783c8-3e0e-45ad-8286-23c89faeb179) SELECT count() FROM pupu_monitor.apm_zipkin_sample_shard WHERE (((time_date >= '2021-01-04') AND (time_date <= '2021-01-06')) AND ((timestamp >= '1609689600000000') AND (timestamp <= '1609945200000000'))) AND (localEndpoint.serviceName = 'client') LIMIT 500
[clickhouse3-1] 2021.01.07 18:47:57.739819 [ 350 ] {d6121963-86ec-47d1-ad44-a402ae0f6b8d} <Debug> InterpreterSelectQuery: MergeTreeWhereOptimizer: condition "(time_date >= '2021-01-04') AND (time_date <= '2021-01-06')" moved to PREWHERE
[clickhouse3-1] 2021.01.07 18:47:57.741325 [ 350 ] {d6121963-86ec-47d1-ad44-a402ae0f6b8d} <Debug> pupu_monitor.apm_zipkin_sample_shard (SelectExecutor): Key condition: unknown, unknown, and, (column 0 in [1609689600000000, +inf)), (column 0 in (-inf, 1609945200000000]), and, unknown, and, and, unknown, unknown, and, and
[clickhouse3-1] 2021.01.07 18:47:57.741345 [ 350 ] {d6121963-86ec-47d1-ad44-a402ae0f6b8d} <Debug> pupu_monitor.apm_zipkin_sample_shard (SelectExecutor): MinMax index condition: (column 0 in [18631, +inf)), (column 0 in (-inf, 18633]), and, unknown, unknown, and, unknown, and, and, (column 0 in [18631, +inf)), (column 0 in (-inf, 18633]), and, and
[clickhouse3-1] 2021.01.07 18:47:57.742949 [ 350 ] {d6121963-86ec-47d1-ad44-a402ae0f6b8d} <Debug> pupu_monitor.apm_zipkin_sample_shard (SelectExecutor): Selected 34 parts by partition key, 34 parts by primary key, 46665 marks by primary key, 46665 marks to read from 34 ranges
[clickhouse2-1] 2021.01.07 18:47:57.739979 [ 270 ] {59df79c3-5af7-4df2-9dbc-3713d1453d79} <Debug> InterpreterSelectQuery: MergeTreeWhereOptimizer: condition "(time_date >= '2021-01-04') AND (time_date <= '2021-01-06')" moved to PREWHERE
[clickhouse2-1] 2021.01.07 18:47:57.741225 [ 270 ] {59df79c3-5af7-4df2-9dbc-3713d1453d79} <Debug> pupu_monitor.apm_zipkin_sample_shard (SelectExecutor): Key condition: unknown, unknown, and, (column 0 in [1609689600000000, +inf)), (column 0 in (-inf, 1609945200000000]), and, unknown, and, and, unknown, unknown, and, and
[clickhouse2-1] 2021.01.07 18:47:57.741245 [ 270 ] {59df79c3-5af7-4df2-9dbc-3713d1453d79} <Debug> pupu_monitor.apm_zipkin_sample_shard (SelectExecutor): MinMax index condition: (column 0 in [18631, +inf)), (column 0 in (-inf, 18633]), and, unknown, unknown, and, unknown, and, and, (column 0 in [18631, +inf)), (column 0 in (-inf, 18633]), and, and
[clickhouse2-1] 2021.01.07 18:47:57.742822 [ 270 ] {59df79c3-5af7-4df2-9dbc-3713d1453d79} <Debug> pupu_monitor.apm_zipkin_sample_shard (SelectExecutor): Selected 32 parts by partition key, 32 parts by primary key, 46663 marks by primary key, 46663 marks to read from 32 ranges
[clickhouse2-1] 2021.01.07 18:48:00.484860 [ 270 ] {59df79c3-5af7-4df2-9dbc-3713d1453d79} <Information> executeQuery: Read 378438411 rows, 3.89 GiB in 2.745376254 sec., 137845736 rows/sec., 1.42 GiB/sec.
[clickhouse2-1] 2021.01.07 18:48:00.484884 [ 270 ] {59df79c3-5af7-4df2-9dbc-3713d1453d79} <Debug> MemoryTracker: Peak memory usage (for query): 8.69 MiB.
[clickhouse3-1] 2021.01.07 18:48:01.125161 [ 350 ] {d6121963-86ec-47d1-ad44-a402ae0f6b8d} <Information> executeQuery: Read 378437525 rows, 3.89 GiB in 3.385797021 sec., 111772065 rows/sec., 1.15 GiB/sec.
[clickhouse3-1] 2021.01.07 18:48:01.125186 [ 350 ] {d6121963-86ec-47d1-ad44-a402ae0f6b8d} <Debug> MemoryTracker: Peak memory usage (for query): 8.62 MiB.
┌──count()─┐
│ 16501929 │
└──────────┘
[clickhouse1-1] 2021.01.07 18:48:01.125963 [ 198 ] {94b783c8-3e0e-45ad-8286-23c89faeb179} <Information> executeQuery: Read 1135399460 rows, 11.67 GiB in 3.396016108 sec., 334332766 rows/sec., 3.44 GiB/sec.
[clickhouse1-1] 2021.01.07 18:48:01.125986 [ 198 ] {94b783c8-3e0e-45ad-8286-23c89faeb179} <Debug> MemoryTracker: Peak memory usage (for query): 9.19 MiB.

1 rows in set. Elapsed: 3.659 sec. Processed 1.14 billion rows, 12.53 GB (310.26 million rows/s., 3.42 GB/s.)

**4.My question**
I found
1. read rows is equals.
2.  sample query time >  no_sample query time 
So how does sample feature work. Or do I use in wrong way?

**Comment by den-crane** [comment]
because `ORDER BY (timestamp, duration, ` timestamp & duration are high cardinality columns.

Check this example https://gist.github.com/den-crane/42bf77285b53762f11d88d73a46179de
https://stackoverflow.com/questions/64369622/using-sample-in-clickhouse-seems-to-read-all-rows-and-more-bytes-is-this-expect

**Comment by tangxueming** [comment]
> because `ORDER BY (timestamp, duration, ` timestamp & duration are high cardinality columns.
> 
> Check this example https://gist.github.com/den-crane/42bf77285b53762f11d88d73a46179de
> https://stackoverflow.com/questions/64369622/using-sample-in-clickhouse-seems-to-read-all-rows-and-more-bytes-is-this-expect
> 
> Try
> 
> ```
> ORDER BY (serviceName, intDiv(timestamp, 3600000), xxHash32(traceId))
> SAMPLE BY xxHash32(traceId)
> ```

Thank you for your help and suggestions. Let me have a try.

**Comment by tangxueming** [comment]
I need set primary key with timestamp.
sample  :10%
First test:  There is   1.2 billions+ rows in 3 days. Timestamp_30second  is 24*60*2=2880  
 different value in  one day .  The result is good, only read 32 millions rows.
` Order by (timestamp_30second ,hash(traceId))`

Second test: There is   2 billions+ rows in 5 days, timestamp_second is    24*60*60 =86400  in one day.  The result is bad, only drop 16 million rows.
`Order by (timestamp_second ,hash(traceId))`
In second test, I think the dataset is too small. Sample query nearly read all granularity, because the rows is less than 8192 every second.
In my prod env, there is 55k rows every second. It avoid reading all granularity. It is acceptable for me that a slowly query run time between 10 and 20 seconds.
Next week, I will do some test on my prod env,.Then I will share the result.

**Comment by den-crane** [comment]
Check my advice. Reduce granularity in index to hour.` Order by (toStartOfHour(timestamp), hash(traceId))`

**Comment by tangxueming** [comment]
> Check my advice. Reduce granularity in index to hour.` Order by (toStartOfHour(timestamp), hash(traceId))`

I failed with timestamp.  I need list  record order by timestamp desc, so I set primary key with timestamp.
Now I think it is satisfying in my case. 
When query one day data, I use query without sample.
When query more than one day day,  I cam use sampled query with hour granularity.
And record list is still order by timestamp.
I will check your advice next week. Thanks!

**Comment by tangxueming** [comment]
It works well when I set timestamp_hour as primary key . Thanks!
But it's slowly  when I execute ' select xxx from tableA order by timestamp_hour, timestamp desc limit 10' . It is so slowly that I don't think I will use this method.
In my case, I will execute two queries, one is ' select xxx from tableA order by timestamp', another is ' select count(), quantile(0.95)(duration), max(duration), sum(errorCount), avg(duration) from tableA group by  intDiv(timestamp, 3600)*3600'.
 'group by intDiv(timestamp, 3600)*3600'   is similar to 'group by hour'.  Number 3600 is not fixed, sometimes the number is 1800.
Recently, I use two table. One table  is order by timestamp_second to execute first query. Another use Aggregate Engine to execute second query.
They work well, except querying quantileMerge(percent95). 
The value is inaccurate.
