### ISSUE TITLE
Choose Decimal/Float interpretation from literal values 

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#18841]
In certain cases, clickhouse can determine the resulting type of values interpretation without explicit conversion declaration.
And we can have settings which would control that kind of behavior.

**Use case**
```
SELECT toDecimal64(1.4,10) UNION ALL SELECT 1.5 ;

Code: 386. DB::Exception: Received from localhost:9000. DB::Exception: There is no supertype for types Decimal(18, 10), Float64 because some of them have no lossless conversion to Decimal.

CREATE TABLE test_float(`id` UInt64,`decimal_column` Decimal64(10)) ENGINE = MergeTree ORDER BY id

INSERT INTO test_float (decimal_column) SELECT 1.5

Query id: f1e03fab-e6a4-4b0a-8264-94fa715b1e8f

Ok.

INSERT INTO test_float (decimal_column) SELECT 1.5
FROM view_test_float
UNION ALL
SELECT decimal_column
FROM view_test_float

Query id: 8e0761af-44e8-4389-b942-2cc0789a7e44


Received exception from server (version 20.13.1):
Code: 386. DB::Exception: Received from localhost:9000. DB::Exception: There is no supertype for types Float64, Decimal(18, 10) because some of them have no lossless conversion to Decimal.

```

**Describe the solution you'd like**
Clickhouse would automatically interpret 1.5 as decimal when other values are decimal.

**Describe alternatives you've considered**
Use toDecimal() functions.

**Additional context**
https://github.com/ClickHouse/ClickHouse/issues/9881#issuecomment-657261973

**Comment by alexey-milovidov** [comment]
> In certain cases, clickhouse can determine the resulting type of values interpretation without explicit conversion declaration.

But it will make expressions context-sensitive, which is recognized as an anti-pattern in programming languages.
