### ISSUE TITLE
Alias in AggregatingMergeTree

### ISSUE THREAD

**Issue by igorbb** [ClickHouse/ClickHouse#18849]
Can we have a way to use aliases with AggregatingMergeTree? 

**Use case**
Example:
Have the following AggregatingMergeTree table: 
```
drop table  if exists test_alias;
create table test_alias (
  timestamp UInt64,
  updates_count_state AggregateFunction(count),
  name String,
  up_count ALIAS countMerge(updates_count_state)
) Engine = AggregatingMergeTree
ORDER BY
  timestamp;
```

Then, after inserting data into the table we could query with:
```
select name, up_count from test_alias GROUP BY name
```

**Describe alternatives you've considered**

An alternative (which works) is to write a query without aliases.
And query with:
```
SELECT
  countMerge(updates_count_state),
  name
FROM
  test_alias
GROUP BY
  name
  ```
  
  Nevertheless, it would be much nicer to query directly using pre-defined aliases.

**Comment by den-crane** [comment]
BTW, You can use SimpleAggregateFunction here.

```sql
create table test_alias (
  timestamp UInt64,
  up_count SimpleAggregateFunction(sum, UInt64) CODEC(T64, LZ4), 
  name String
) Engine = AggregatingMergeTree
ORDER BY
  timestamp;
```

**Comment by den-crane** [comment]
>up_count ALIAS countMerge(updates_count_state)

select without group by will fail in case.

**Comment by igorbb** [comment]
Thanks den-crane.

I think the example I posted, might have been too simple.
I know it will fail, would be great to have an alias to be computed only if included on the query. Like in the sample query.

In our case, we depend on other conditions, so I think SimpleAggregateFunction would not be enough for us.
Unless it also works with the `If` modifier or some other aggregation functions ?


Example :
```
create table test_alias (
  timestamp UInt64,
  up_count SimpleAggregateFunction(sum, UInt64) CODEC(T64, LZ4), 
  -- this_variable_wont_work SimpleAggregateFunction(argMin, UInt64, UInt64 ) ,
  -- this_count_if_wont_work AggregateFunction(count,UInt8),
  name String
) Engine = AggregatingMergeTree
ORDER BY
  timestamp;
  ````
