### ISSUE TITLE
why select count(*) from numbers(10000000) cannot run in readonly mode?

### ISSUE THREAD

**Issue by l1t1** [ClickHouse/ClickHouse#18854]
Code: 164, e.displayText() = DB::Exception: play: Cannot execute query in readonly mode (version 20.13.1.5552 (official build))

**Comment by den-crane** [comment]
All table functions require RW privileges.
You can use `select count(*) from system.numbers where number <= 10000000` instead.

**Comment by l1t1** [comment]
thanks
