### ISSUE TITLE
A function to read file as a String.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#18851]
```
SELECT file(path)
```

Restrictions on file path must apply (server can only read files from the `user_files` directory)

**Use case**

```
clickhouse-client --query "INSERT INTO table SELECT file('a.txt'), file('b.txt')"
```

```
clickhouse-local --query "SELECT file('a.txt'), file('b.txt')" | clickhouse-client --query "INSERT INTO table FORMAT TSV"
```

In this example, the whole content of the `a.txt` and `b.txt` file is inserted as a single String values.

**Notes**

We get used to the fact that storing large BLOBs in ClickHouse is discouraged.
But after enabling adaptive index granularity it becomes more ok.

**Comment by keen-wolf** [comment]
Hi~ I'd like to take this one

**Comment by alexey-milovidov** [comment]
That will be awesome!
