### ISSUE TITLE
rename operator on local and Distributed table

### ISSUE THREAD

**Issue by shadowDy** [ClickHouse/ClickHouse#18856]
the local table：new_test_local with in megreTree 
the distributed table: new_test distributed on new_test_local

when i executed `select count(*) from new_test ` return 10；

then i executed `rename table new_test_local to test_local` return ok

when i executed `select count(*) from test_local ` return 10；
when i executed `select count(*) from new_test_local ` return failed，table not found;

but ~~~

when i executed `select count(*) from new_test ` return 10；

execute `show create table new_test` 
the local table is new_test_local ;

i can not understand.....

**Comment by amosbird** [comment]
It should be related to DatabaseAtomic. Tables are identified by UUID and stays unmodified during rename.

**Comment by shadowDy** [comment]
> It should be related to DatabaseAtomic. Tables are identified by UUID and stays unmodified during rename.

In this case, do I need to change the table creation statement of the distributed table

**Comment by shadowDy** [comment]
@amosbird 我发现重命名本地表后，通过分布式表的写入不能写到对应的本地表了。

**Comment by shadowDy** [comment]
@amosbird I found that after renaming the local table, the corresponding local table cannot be written through the writing of the distributed table.

**Comment by tavplubix** [comment]
I cannot reproduce the issue, could you please provide a full list of queries (including `CREATE`s and `INSERT`s) to reproduce it and output of `select * from system.clusters format TSV` (or cluster description from config.xml)?

**Comment by alexey-milovidov** [comment]
No info provided.
