### ISSUE TITLE
Array function logical incorrectness.

### ISSUE THREAD

**Issue by ClownfishYang** [ClickHouse/ClickHouse#18855]
I'm testing a starting index from an array that is above a certain threshold and then monotonically increases in value.
But the same judgment logic gives two different results, which is a violation of consistency: A && B == B && A.
```
SELECT 
    uuid, 
    arrayFirstIndex((a, b) -> ((a >= 5) AND (arraySum(arrayMap(a -> if(a >= 5, 0, 1), arraySlice(data_f, b + 1, 4))) = 0))
        , arraySlice(data_f, 1, length(data_f) - 3), range(toUInt64(length(data_f) - 3))) AS freq_idx
FROM 
(
    SELECT 
        'id1' AS uuid, 
        'p1' AS param, 
        [1, 2, 3, 4, 5, 4, 7, 8, 9, 3, 2, 1, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1] AS data_f
    FROM system.one
)
┌─uuid─┬─freq_idx─┐
│ id1  │        5 │
└──────┴──────────┘

SELECT 
    uuid, 
    arrayFirstIndex((a, b) -> ((arraySum(arrayMap(a -> if(a >= 5, 0, 1), arraySlice(data_f, b + 1, 4))) = 0) AND (a >= 5))
        , arraySlice(data_f, 1, length(data_f) - 3), range(toUInt64(length(data_f) - 3))) AS freq_idx
FROM 
(
    SELECT 
        'id1' AS uuid, 
        'p1' AS param, 
        [1, 2, 3, 4, 5, 4, 7, 8, 9, 3, 2, 1, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1] AS data_f
    FROM system.one
)
┌─uuid─┬─freq_idx─┐
│ id1  │       13 │
└──────┴──────────┘

```

**Comment by UnamedRus** [comment]
If we would replace arrayMap(a...) with arrayMap(x...) the result would be consistent.

```

SELECT
    uuid,
    arrayFirstIndex((a, b) -> ((arraySum(arrayMap(x -> if(x >= 5, 0, 1), arraySlice(data_f, b + 1, 4))) = 0) AND (a >= 5)), arraySlice(data_f, 1, length(data_f) - 3), range(toUInt64(length(data_f) - 3))) AS freq_idx
FROM
(
    SELECT
        'id1' AS uuid,
        'p1' AS param,
        [1, 2, 3, 4, 5, 4, 7, 8, 9, 3, 2, 1, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1] AS data_f
    FROM system.one
)

Query id: c05a651e-473f-4961-9a35-f6eec3b8fccf

┌─uuid─┬─freq_idx─┐
│ id1  │       13 │
└──────┴──────────┘

SELECT
    uuid,
    arrayFirstIndex((a, b) -> ((a >= 5) AND (arraySum(arrayMap(x -> if(x >= 5, 0, 1), arraySlice(data_f, b + 1, 4))) = 0)), arraySlice(data_f, 1, length(data_f) - 3), range(toUInt64(length(data_f) - 3))) AS freq_idx
FROM
(
    SELECT
        'id1' AS uuid,
        'p1' AS param,
        [1, 2, 3, 4, 5, 4, 7, 8, 9, 3, 2, 1, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1] AS data_f
    FROM system.one
)

Query id: 1f655d1a-e121-46e1-8abf-e68fcb811268

┌─uuid─┬─freq_idx─┐
│ id1  │       13 │
└──────┴──────────┘

```

Simpler Example 

```
WITH [0, 1] AS arr
SELECT arrayExists(x -> (x AND (arrayExists(x -> (NOT x), arr) > 0)), arr) AS x

┌─x─┐
│ 1 │
└───┘

WITH [0, 1] AS arr
SELECT arrayExists(x -> ((x = 1) AND (arrayExists(x -> (NOT (x = 1)), arr) > 0)), arr) AS x

┌─x─┐
│ 0 │
└───┘

WITH [0, 1] AS arr
SELECT arrayExists(x -> ((arrayExists(x -> (NOT (x = 1)), arr) > 0) AND (x = 1)), arr) AS x

┌─x─┐
│ 1 │
└───┘
```

Issue happens when clickhouse tries to reuse the result of the first expression (x = 1) the second lambda.

**Comment by ClownfishYang** [comment]
> If we would replace arrayMap(a...) with arrayMap(x...) the result would be consistent.
> 
> ```
> 
> SELECT
>     uuid,
>     arrayFirstIndex((a, b) -> ((arraySum(arrayMap(x -> if(x >= 5, 0, 1), arraySlice(data_f, b + 1, 4))) = 0) AND (a >= 5)), arraySlice(data_f, 1, length(data_f) - 3), range(toUInt64(length(data_f) - 3))) AS freq_idx
> FROM
> (
>     SELECT
>         'id1' AS uuid,
>         'p1' AS param,
>         [1, 2, 3, 4, 5, 4, 7, 8, 9, 3, 2, 1, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1] AS data_f
>     FROM system.one
> )
> 
> Query id: c05a651e-473f-4961-9a35-f6eec3b8fccf
> 
> ┌─uuid─┬─freq_idx─┐
> │ id1  │       13 │
> └──────┴──────────┘
> 
> SELECT
>     uuid,
>     arrayFirstIndex((a, b) -> ((a >= 5) AND (arraySum(arrayMap(x -> if(x >= 5, 0, 1), arraySlice(data_f, b + 1, 4))) = 0)), arraySlice(data_f, 1, length(data_f) - 3), range(toUInt64(length(data_f) - 3))) AS freq_idx
> FROM
> (
>     SELECT
>         'id1' AS uuid,
>         'p1' AS param,
>         [1, 2, 3, 4, 5, 4, 7, 8, 9, 3, 2, 1, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1] AS data_f
>     FROM system.one
> )
> 
> Query id: 1f655d1a-e121-46e1-8abf-e68fcb811268
> 
> ┌─uuid─┬─freq_idx─┐
> │ id1  │       13 │
> └──────┴──────────┘
> ```
> 
> Simpler Example
> 
> ```
> WITH [0, 1] AS arr
> SELECT arrayExists(x -> (x AND (arrayExists(x -> (NOT x), arr) > 0)), arr) AS x
> 
> ┌─x─┐
> │ 1 │
> └───┘
> 
> WITH [0, 1] AS arr
> SELECT arrayExists(x -> ((x = 1) AND (arrayExists(x -> (NOT (x = 1)), arr) > 0)), arr) AS x
> 
> ┌─x─┐
> │ 0 │
> └───┘
> 
> WITH [0, 1] AS arr
> SELECT arrayExists(x -> ((arrayExists(x -> (NOT (x = 1)), arr) > 0) AND (x = 1)), arr) AS x
> 
> ┌─x─┐
> │ 1 │
> └───┘
> ```
> 
> Issue happens when clickhouse tries to reuse the result of the first expression (x = 1) the second lambda.

Yeah, that's right, like you said.Please forgive me for not looking carefully, this is a great design, I will correct it.
Now I happen to have a new problem, can you help me take a look at it?
I need to query for the same starting value in both Arrays and how many times a value will appear after that.
```
SELECT 
t1.uuid AS uuid,
arrayFirstIndex(c -> t1.data_i[c+1] == 0 AND t2.data_i[c+1] == 0
        AND countEqual(arraySlice(t1.data_i, c+1,40),1) == 1
        AND countEqual(arraySlice(t2.data_i, c+1,40),1) == 1
        ,range(length(t1.data_i))) AS lr_freq_idx

 FROM (
SELECT 
    'id1' AS uuid, 
    'p1' AS param, 
    range(10000) AS data_i
FROM system.one
) t1
LEFT JOIN (
SELECT 
    'id1' AS uuid, 
    'p2' AS param, 
    range(10000) AS data_i
FROM system.one
) t2
ON t1.uuid = t2.uuid

┌─uuid─┬─lr_freq_idx─┐
│ id1  │           1 │
└──────┴─────────────┘
```
If range(10000), the execution is fine, but if range(100000), the execution is wrong.
```
Progress: 0.00 rows, 0.00 B (0.00 rows/s., 0.00 B/s.) Received exception from server (version 20.2.1):
Code: 241. DB::Exception: Received from localhost:9000. DB::Exception: Memory limit (for query) exceeded: would use 32.00 GiB (attempt to allocate chunk of 34362893096 bytes), maximum: 9.31 GiB:
```
I don't understand why such a simple query consumes so much memory.Is there any way to avoid the use problem, this is just the data I use for testing, development may use more data.

**Comment by den-crane** [comment]
>I need to query for the same starting value in both Arrays and how many times a value will appear after that.

This is unclear. Can you make for clear example?

>Memory limit (for query) exceeded
The issue is that you pass arrays into lambda function. In this case CH makes a copy of passed arrays.

```sql
set send_logs_level='debug'

SELECT arrayFilter(i -> arr1[i]/arr2[i] = arr2[i] * arr2[i], range(length(arr1))) 
from (select materialize(range(1000000)) arr1, materialize(range(1000000)) arr2)

Memory limit (for query) exceeded: would use 4.00 TiB

--the same query without arrays in lamda
SELECT arrayFilter((i, j) -> (i/j = j * j), arr1, arr2) 
from (select materialize(range(1000000)) arr1, materialize(range(1000000)) arr2)

Peak memory usage (for query): 20.01 MiB
```

**Comment by ClownfishYang** [comment]
For example, if I have two Arrays, I want to find that both Arrays are greater than or equal to some value the first time (for example, 60) and then many times in a row (for example, 5 times).
```
SELECT 
t1.uuid AS uuid,
arrayFirstIndex(i -> t1.data_i[i] >= 60 and t2.data_i[i] >= 60
	and arraySum(arrayMap(x -> if (x >= 60, 0, 1), arraySlice(t1.data_i, i + 1, 4))) == 0
	and arraySum(arrayMap(x -> if (x >= 60, 0, 1), arraySlice(t2.data_i, i + 1, 4))) == 0
        ,arrayEnumerate(t1.data_i)) AS lr_freq_idx

 FROM (
SELECT 
    'id1' AS uuid, 
    'p1' AS param, 
    range(10000) AS data_i
FROM system.one
) t1
LEFT JOIN (
SELECT 
    'id1' AS uuid, 
    'p2' AS param, 
    range(10000) AS data_i
FROM system.one
) t2
ON t1.uuid = t2.uuid
```
I'm simplifying here, but in fact these arrays may not have the same length, so we need to convert the index value, and there's no quick way to do that (I mean when the array is really long),
