### ISSUE TITLE
where条件位置不同会产生明显的性能差异,如果做到自动条件下推

### ISSUE THREAD

**Issue by yanchaoguo** [ClickHouse/ClickHouse#18867]
如何更好的解决下面的问题
查询一：
SELECT  t1.`biz_type` AS `biz_type`, count() AS `count`
FROM  `scene_model` as t1
LEFT JOIN (select id from `app`.`user_model` where  `user_scene_pv` > 5000 ) as `User Model` ON  t1.`create_user` = `User Model`.`id`
GROUP BY t1.`biz_type`
ORDER BY t1.`biz_type` ASC

查询二：
SELECT  t1.`biz_type` AS `biz_type`, count() AS `count`
FROM  `scene_model` as t1
LEFT JOIN (select id,user_scene_pv from `app`.`user_model`  ) as `User Model` ON  t1.`create_user` = `User Model`.`id`
where  `user_scene_pv` > 5000
GROUP BY t1.`biz_type`
ORDER BY t1.`biz_type` ASC 

仅仅因为 “where  `user_scene_pv` > 5000” 条件的位置不同 查询一可2秒出结果 ，查询二 1分钟后time out

scene_model 数据量1个亿  ，user_model数据量5000万  加了过滤条件后剩余50万

**Comment by lizhichao** [comment]
排查不符合条件的数据，再关联。
先关联 再排除。
第一个肯定快很多啊 ，第二个做了很多无用功。多简单的问题……

**Comment by yanchaoguo** [comment]
> 排除不符合条件的数据，再关联。
> 先关联，再排除不符合条件的数据。
> 第一个肯定快很多啊 ，第二个做了很多无用功。多简单的问题……

你可能没理解我的意思 我是说这种方式怎么不是自动条件下推 还需要人来优化呢

**Comment by lizhichao** [comment]
> > 排除不符合条件的数据，再关联。
> > 先关联，再排除不符合条件的数据。
> > 第一个肯定快很多啊 ，第二个做了很多无用功。多简单的问题……
> 
> 你可能没理解我的意思 我是说这种方式怎么不是自动条件下推 还需要人来优化呢

这就是初级工程师和高级工程师的区别了，初级工程师就会写很多低效率代码

**Comment by yanchaoguo** [comment]
> > > 排除不符合条件的数据，再关联。
> > > 先关联，再排除不符合条件的数据。
> > > 第一个肯定快很多啊 ，第二个做了很多无用功。多简单的问题……
> > 
> > 
> > 你可能没理解我的意思 我是说这种方式怎么不是自动条件下推 还需要人来优化呢
> 
> 这就是初级工程师和高级工程师的区别了，初级工程师就会写很多低效率代码

那么如何在数据库层改善这种情况 让这种操作变的更加友好呢？我记得clickhouse嵌套查询是支持下推操作的

**Comment by zhang2014** [comment]
/// NOTE: the syntactic way of pushdown has limitations and should be partially disabled in case of JOINs.
        ///       Let's take a look at the query:
        ///
        ///           SELECT a, b FROM (SELECT 1 AS a) ANY LEFT JOIN (SELECT 1 AS a, 1 AS b) USING (a) WHERE b = 0
        ///
        ///       The result is empty - without pushdown. But the pushdown tends to modify it in this way:
        ///
        ///           SELECT a, b FROM (SELECT 1 AS a) ANY LEFT JOIN (SELECT 1 AS a, 1 AS b WHERE b = 0) USING (a) WHERE b = 0
        ///
        ///       That leads to the empty result in the right subquery and changes the whole outcome to (1, 0) or (1, NULL).
        ///       It happens because the not-matching columns are replaced with a global default values on JOIN.
        ///       Same is true for RIGHT JOIN and FULL JOIN.

reference : https://github.com/ClickHouse/ClickHouse/blob/master/src/Interpreters/PredicateExpressionsOptimizer.cpp#L127

**Comment by yanchaoguo** [comment]
> /// NOTE: the syntactic way of pushdown has limitations and should be partially disabled in case of JOINs.
> /// Let's take a look at the query:
> ///
> /// SELECT a, b FROM (SELECT 1 AS a) ANY LEFT JOIN (SELECT 1 AS a, 1 AS b) USING (a) WHERE b = 0
> ///
> /// The result is empty - without pushdown. But the pushdown tends to modify it in this way:
> ///
> /// SELECT a, b FROM (SELECT 1 AS a) ANY LEFT JOIN (SELECT 1 AS a, 1 AS b WHERE b = 0) USING (a) WHERE b = 0
> ///
> /// That leads to the empty result in the right subquery and changes the whole outcome to (1, 0) or (1, NULL).
> /// It happens because the not-matching columns are replaced with a global default values on JOIN.
> /// Same is true for RIGHT JOIN and FULL JOIN.
> 
> reference : https://github.com/ClickHouse/ClickHouse/blob/master/src/Interpreters/PredicateExpressionsOptimizer.cpp#L127
没错，下推后 外层的where条件继续保留 这样在保证结果不变的情况下 提升了查询性能
该特性在哪个版本会发布呢

**Comment by zhang2014** [comment]
> 没错，下推后 外层的where条件继续保留 这样在保证结果不变的情况下 提升了查询性能
该特性在哪个版本会发布呢

此优化会引入JOIN的功能性问题(语法优化层无法解决, 需要将谓词优化改写到执行层时才可能解决。目前执行层的改写正在进行中)。

**Comment by yanchaoguo** [comment]
> > 没错，下推后 外层的where条件继续保留 这样在保证结果不变的情况下 提升了查询性能
> > 该特性在哪个版本会发布呢
> 
> 此优化会引入JOIN的功能性问题(语法优化层无法解决, 需要将谓词优化改写到执行层时才可能解决。目前执行层的改写正在进行中)。

👍 @zhang2014 该优化很有用 关注中…

**Comment by yanchaoguo** [comment]
@den-crane @zhang2014 为什么关掉 该问题已经优化掉了吗

**Comment by helifu** [comment]
> > 没错，下推后 外层的where条件继续保留 这样在保证结果不变的情况下 提升了查询性能
> > 该特性在哪个版本会发布呢
> 
> 此优化会引入JOIN的功能性问题(语法优化层无法解决, 需要将谓词优化改写到执行层时才可能解决。目前执行层的改写正在进行中)。

Hi @zhang2014, could you please share that PR which is in WIP state?
