### ISSUE TITLE
OpenSSL certificate issue when using S3 https endpoint in AWS China Region

### ISSUE THREAD

**Issue by davidshtian** [ClickHouse/ClickHouse#18869]
**Describe the bug**
When using S3 https endpoint in AWS China Region (Beijing and Ningxia), there is a openssl certificate issue reported.

**How to reproduce**
* Which ClickHouse server version to use: 20.13.1.5591
* Default settings + S3 settings shown as below:
```
<yandex>
    <s3>
        <endpoint>
        <endpoint>https://s3.cn-north-1.amazonaws.com.cn</endpoint>
           <use_environment_credentials>true</use_environment_credentials>
        </endpoint>
   </s3>
</yandex>
```
* Workaround: replace with 'http' would be a workaround and tested, but it's not secure.

**Error message and/or stacktrace**
```
2021.01.08 11:40:45.152230 [ 2541 ] {a696e605-ef1f-4ff2-948a-45b7a50ef487} <Error> TCPHandler: Code: 499, e.displayText() = DB::Exception: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = SSL Exception: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED (version 20.13.1.5591 (official build)): While executing S3, Stack trace:

0. DB::ReadBufferFromS3::initialize() @ 0xeac4dcd in /usr/bin/clickhouse
1. DB::ReadBufferFromS3::nextImpl() @ 0xeac4381 in /usr/bin/clickhouse
2. DB::CSVRowInputFormat::readPrefix() @ 0xf988646 in /usr/bin/clickhouse
3. DB::IRowInputFormat::generate() @ 0xf964c4f in /usr/bin/clickhouse
4. DB::ISource::tryGenerate() @ 0xf8eef95 in /usr/bin/clickhouse
5. DB::ISource::work() @ 0xf8eecba in /usr/bin/clickhouse
6. DB::InputStreamFromInputFormat::readImpl() @ 0xd442acf in /usr/bin/clickhouse
7. DB::IBlockInputStream::read() @ 0xe9a2545 in /usr/bin/clickhouse
8. ? @ 0xf495f26 in /usr/bin/clickhouse
9. DB::ISource::tryGenerate() @ 0xf8eef95 in /usr/bin/clickhouse
10. DB::ISource::work() @ 0xf8eecba in /usr/bin/clickhouse
11. DB::SourceWithProgress::work() @ 0xfa5639a in /usr/bin/clickhouse
12. ? @ 0xf928b5c in /usr/bin/clickhouse
13. DB::PipelineExecutor::executeStepImpl(unsigned long, unsigned long, std::__1::atomic<bool>*) @ 0xf925906 in /usr/bin/clickhouse
14. DB::PipelineExecutor::executeImpl(unsigned long) @ 0xf923a89 in /usr/bin/clickhouse
15. DB::PipelineExecutor::execute(unsigned long) @ 0xf9234fd in /usr/bin/clickhouse
16. ? @ 0xf9313be in /usr/bin/clickhouse
17. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x86454ad in /usr/bin/clickhouse
18. ? @ 0x8649063 in /usr/bin/clickhouse
19. start_thread @ 0x740b in /usr/lib64/libpthread-2.26.so
20. __clone @ 0xecf9f in /usr/lib64/libc-2.26.so
```

**Expected behavior**
There will be right certificate for S3 https endpoint in AWS China Region.

**Comment by filimonov** [comment]
1) did you install correct root ca certificates? (curl request work?)
2) which OS do you use (on some OS you need to adjust the path to CA in  ssl client configuration of ClickHouse)?

**Comment by davidshtian** [comment]
> 1. did you install correct root ca certificates? (curl request work?)
> 2. which OS do you use (on some OS you need to adjust the path to CA in  ssl client configuration of ClickHouse)?

1. Yes, when using AWS CLI or API on the same server, the request works and the default endpoint is https://.
2. OS version used is Amazon Linux 2.

The host is different in China regions (https://s3.cn-north-1.amazonaws.com.cn) from global regions (https://s3.us-east-1.amazonaws.com). It works well in AWS global regions.

Thanks~

**Comment by davidshtian** [comment]
> 1. did you install correct root ca certificates? (curl request work?)
> 2. which OS do you use (on some OS you need to adjust the path to CA in ssl client configuration of ClickHouse)?

It seems it's the 2nd issue and update test results below:

- China Region + Amazon Linux 2: Not Work
- China Region + Ubuntu 18.04: Work
- Global Region + Amazon Linux 2: Not Work
- Global Region + Ubuntu 20.04: Work

Which folder should I copy certificate to? And which certificate do I need to copy?

Thanks~

**Comment by davidshtian** [comment]
> > 1. did you install correct root ca certificates? (curl request work?)
> > 2. which OS do you use (on some OS you need to adjust the path to CA in ssl client configuration of ClickHouse)?
> 
> It seems it's the 2nd issue and update test results below:
> 
> * China Region + Amazon Linux 2: Not Work
> * China Region + Ubuntu 18.04: Work
> * Global Region + Amazon Linux 2: Not Work
> * Global Region + Ubuntu 20.04: Work
> 
> Which folder should I copy certificate to? And which certificate do I need to copy?
> 
> Thanks~


Works for setting openssl <caConfig> to /etc/pki/tls/certs/ca-bundle.crt for Amazon Linux 2:

```
        <client> <!-- Used for connecting to https dictionary source and secured Zookeeper communication -->
            <loadDefaultCAFile>true</loadDefaultCAFile>
            <caConfig>/etc/pki/tls/certs/ca-bundle.crt</caConfig>
            <cacheSessions>true</cacheSessions>
            <disableProtocols>sslv2,sslv3</disableProtocols>
            <preferServerCiphers>true</preferServerCiphers>
            <!-- Use for self-signed: <verificationMode>none</verificationMode> -->
            <invalidCertificateHandler>
                <!-- Use for self-signed: <name>AcceptCertificateHandler</name> -->
                <name>RejectCertificateHandler</name>
            </invalidCertificateHandler>
        </client>
    </openSSL>
```

Thanks for the help~

**Comment by filimonov** [comment]
More universal solution #17803
