### ISSUE TITLE
Can I convert the query result to an array?

### ISSUE THREAD

**Issue by qinglok** [ClickHouse/ClickHouse#18865]
Like this:
`select array( select col_1 from table )`

But this function doesn't support this.

**Comment by IVitamin-C** [comment]
![image](https://user-images.githubusercontent.com/35019926/104000459-3abab600-51d9-11eb-8d09-d322c8bdd52a.png)

**Comment by IVitamin-C** [comment]
with (select 1 as t from system.one) as a 
select array(a)

**Comment by qinglok** [comment]
> with (select 1 as t from system.one) as a
> select array(a)

Thanks, but got an error:
 DB::Exception: Scalar subquery returned more than one row (version 20.9.5.5 (official build))

**Comment by IVitamin-C** [comment]
![image](https://user-images.githubusercontent.com/35019926/104002939-b702c880-51dc-11eb-9d10-8e0078591391.png)
with (select 1 as t,2 as t2,3 as t3 from system.one) as t
select t
tuple,not array

**Comment by IVitamin-C** [comment]
select groupArray(t)
from (
select number as t from numbers(20)
)

**Comment by qinglok** [comment]
> select groupArray(t)
> from (
> select number as t from numbers(20)
> )


It's my description that's wrong.

┌─c1─┬─c2─┐
│ a1 │ a2 │
│ b1 │ b2 │
└────┴────┘

I want to get a result like array [a1, b1].

**Comment by qinglok** [comment]
> select groupArray(t)
> from (
> select number as t from numbers(20)
> )

Thank you. It solves my big problem.
