### ISSUE TITLE
Failed to build on OSX BigSur with error 'Darwin build is supported only for Clang'

### ISSUE THREAD

**Issue by fastio** [ClickHouse/ClickHouse#18863]
**Branch**

Current master , commit: 56f3a3b6c71b3d9af95652d9125cb5ffeaea9d6e

**Operating system**

MacOS 11.1

**Cmake version**

3.16.4

**Ninja version**

1.10.0

**Compiler name and version**

gcc 10.2

**Full cmake and/or ninja output**

cmake .. -DENABLE_CLICKHOUSE_ALL=0 -DENABLE_CLICKHOUSE_CLIENT=1 -DENABLE_MYSQL=0 -DCMAKE_CXX_COMPILER=`which g++-10.2` -DCMAKE_C_COMPILER=`which gcc-10.2`
-- The C compiler identification is GNU 10.2.0
-- The CXX compiler identification is GNU 10.2.0
-- Checking whether C compiler has -isysroot
-- Checking whether C compiler has -isysroot - yes
-- Checking whether C compiler supports OSX deployment target flag
-- Checking whether C compiler supports OSX deployment target flag - yes
-- Check for working C compiler: /usr/local/gcc-10.2.0/bin/gcc-10.2
-- Check for working C compiler: /usr/local/gcc-10.2.0/bin/gcc-10.2 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Checking whether CXX compiler has -isysroot
-- Checking whether CXX compiler has -isysroot - yes
-- Checking whether CXX compiler supports OSX deployment target flag
-- Checking whether CXX compiler supports OSX deployment target flag - yes
-- Check for working CXX compiler: /usr/local/gcc-10.2.0/bin/g++-10.2
-- Check for working CXX compiler: /usr/local/gcc-10.2.0/bin/g++-10.2 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning at cmake/find/ccache.cmake:17 (message):
  CCache is not found.  We recommend setting it up if you build ClickHouse
  from source often.  Setting it up will significantly reduce compilation
  time for 2nd and consequent builds
Call Stack (most recent call first):
  CMakeLists.txt:67 (include)

-- CMAKE_BUILD_TYPE is not set, set to default = RelWithDebInfo
-- CMAKE_BUILD_TYPE: RelWithDebInfo
-- Disabling compiler -pipe option (have only 1718 mb of memory)
-- Performing Test HAVE_SSE41
-- Performing Test HAVE_SSE41 - Success
-- Performing Test HAVE_SSE42
-- Performing Test HAVE_SSE42 - Success
-- Performing Test HAVE_SSSE3
-- Performing Test HAVE_SSSE3 - Success
-- Performing Test HAVE_AVX
-- Performing Test HAVE_AVX - Success
-- Performing Test HAVE_AVX2
-- Performing Test HAVE_AVX2 - Success
-- Performing Test HAVE_PCLMULQDQ
-- Performing Test HAVE_PCLMULQDQ - Success
-- Performing Test HAVE_POPCNT
-- Performing Test HAVE_POPCNT - Success
-- Performing Test SUPPORTS_CXXFLAG_error
-- Performing Test SUPPORTS_CXXFLAG_error - Success
-- Performing Test SUPPORTS_CFLAG_error
-- Performing Test SUPPORTS_CFLAG_error - Success
CMake Error at cmake/darwin/default_libs.cmake:4 (message):
  Darwin build is supported only for Clang
Call Stack (most recent call first):
  CMakeLists.txt:380 (include)

-- Configuring incomplete, errors occurred!

**Comment by filimonov** [comment]
Well, may be you should try clang? There is an instruction for that: https://clickhouse.tech/docs/en/development/build-osx/ 

BTW afaik clang from xcode is also supported now.

**Comment by fastio** [comment]
> probably

Thanks for your reply.

**Comment by fastio** [comment]
> Well, may be you should try clang instead of gcc?
> There is an instruction for that: https://clickhouse.tech/docs/en/development/build-osx/
> 
> BTW afaik clang from xcode is also supported now.
> 
> P.S. If you are a developer who want to improve portability of ClickHouse - you can remove that check and try to compile with gcc, most probably you will need to do some adjustements in code here and there.

Thanks for your reply :)
