### ISSUE TITLE
Build ClickHouse failed with "std" symbol issue in CLion on Mac OS X

### ISSUE THREAD

**Issue by TisonKun** [ClickHouse/ClickHouse#18877]
**Operating system**

macOS Catalina 10.15.7

**Cmake version**

3.19.2

**Ninja version**

1.10.2

**Compiler name and version**

```
clang version 11.0.0
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /usr/local/opt/llvm/bin
```

**Full cmake and/or ninja output** CLion output

[output.txt](https://github.com/ClickHouse/ClickHouse/files/5790164/output.txt)

**Comment by TisonKun** [comment]
I can build with cmake & ninja successfully. But it seems CLion uses make and gives different result.

**Comment by alexey-milovidov** [comment]
@TisonKun Most likely CLion is using different compiler.

**Comment by TisonKun** [comment]
@alexey-milovidov is this config wrong? "-isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk"

How can I resolve it? I don't find an entry config it.

**Comment by TisonKun** [comment]
![image](https://user-images.githubusercontent.com/18818196/104084643-f20c0700-5283-11eb-87f6-b34e269444cc.png)

**Comment by TisonKun** [comment]
Using ninja as generator didn't fix the issue. The progress is different

From command-line

```
mkdir build
cd build 
cmake .. -DCMAKE_CXX_COMPILER=`which clang++` -DCMAKE_C_COMPILER=`which clang`
ninja
```

From CLion

```
cmake --build /Users/tison/Documents/GitHub/ClickHouse/cmake-build-debug --target clean -j 4
cmake --build /Users/tison/Documents/GitHub/ClickHouse/cmake-build-debug --target all -j 8  
```

Running CLion command in command-line give the same failure but I don't know the difference as well as how to solve it.

**Comment by TisonKun** [comment]
After generating with ninja several times it completed build without known reason.
