### ISSUE TITLE
apply max_execution_time but without using an estimate?

### ISSUE THREAD

**Issue by mzealey** [ClickHouse/ClickHouse#18872]
**Describe the bug**

I have been using `max_execution_time` to limit query complexity. Normally this works great but there are some situations where very complex queries (1 page of sql so won't include below) are estimated at 1800s but actually complete in 4s. Because the estimate was 1800s I get the error message "Estimated query execution time (1807.380046338318 seconds) is too long. Maximum: 60. Estimated rows to process: 2871497: While executing MergeTreeThread (version 20.11.3.3 (official build))".

As there will always be issues around estimating query execution time, my request is to have an option alongside max_execution_time which will say whether to rely on estimates or whether to just run it and abort after the specified time.

**Comment by den-crane** [comment]
you need to set `timeout_before_checking_execution_speed=0`

**Comment by mzealey** [comment]
ok thank you. i saw some comments around this but assumed it was only applicable for the `min_execution_speed` type options
