### ISSUE TITLE
String trim weird behavior

### ISSUE THREAD

**Issue by wutchzone** [ClickHouse/ClickHouse#18883]
Hello,
When working with string I have found weird behavior. The use case was to extract the IPv4 address from a string. The string has the following format `name-123-321-123-123.domain123.com`.

given `name-123-321-123-123.domain123.com`
```
select arrayStringConcat(arraySlice(splitByChar('-',trim(trailing '.domain123.com' from 'name-123-321-123-123.domain123.com')), -4, 4), '.')
```
returns `123.321.123.` expected  `123.321.123.123` that does not match

given `name-123-321-123-100.domain123.com`
```
select arrayStringConcat(arraySlice(splitByChar('-',trim(trailing '.domain123.com' from 'name-123-321-123-100.domain123.com')), -4, 4), '.')
```
returns `123.321.123.100` expected `123.321.123.100` that does match.

It only does not work when the number in trailing (`.domain123.com`) matches the last octet (`123`). I have look through the documentation and I could not find if this is the default behavior.

ClickHouse server version 20.12.4 revision 54442

**Comment by den-crane** [comment]
Incorrect regex is in `trim(trailing`

SELECT replaceRegexpOne('123-321-123-123.domain123.com', '[\.domain123\.com]*$', '')
--
123-321-123-

**Comment by alexey-milovidov** [comment]
http://sqlfiddle.com/#!17/0a28f/358
http://sqlfiddle.com/#!9/0a28f18/562
http://sqlfiddle.com/#!4/82b7d/1
http://sqlfiddle.com/#!18/82b7d/1

**Comment by alexey-milovidov** [comment]
The function `trim` treats the argument as a set of characters (octets) to be removed and removes all the specified characters from beginning/end of the string.

**Comment by den-crane** [comment]
ops. right

```
PG: select trim(trailing '.domain123.com' from 'name-123-321-123-123.domain123.com');
       rtrim
-------------------
 name-123-321-123-

```
