### ISSUE TITLE
Logical error: Task was not found in task queue

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#18887]
https://clickhouse-test-reports.s3.yandex.net/0/fe1c153c6f5e598044007d6fce36b322e71b700b/fuzzer/report.html#fail1

**Comment by alexey-milovidov** [comment]
@KochetovNicolai Second case: https://clickhouse-test-reports.s3.yandex.net/18853/56475774d32b45cb49b509c92d9fb47fe2e96385/fuzzer/report.html#fail1

It started to be annoying.

**Comment by KochetovNicolai** [comment]
Attempt to add more debug info: #18922

**Comment by KochetovNicolai** [comment]
Probably fixed by #18964
