### ISSUE TITLE
Will DateTime64 have negative effect compared with DateTime?

### ISSUE THREAD

**Issue by fzyzcjy** [ClickHouse/ClickHouse#18889]
Hi thanks for the lib! I need millisecond precision, so I wonder whether DateTime64 has negative effect compared with DateTime?

From what I know, I guess it will suffer from a bit of performance drop, and a bit of extra storage. But I do not know whether it will have more problems, especially big problems?

**Comment by alexey-milovidov** [comment]
I'm unaware of any significant issues with DateTime64.
