### ISSUE TITLE
GROUP BY selects not all rows since version 20.11.2.1

### ISSUE THREAD

**Issue by PaulKhripkov** [ClickHouse/ClickHouse#18921]
**Describe the bug**
Hello, guys.
When I use GROUP BY on big tables (e.g. 10M rows on VM with 8G of RAM with default CH docker image setting or 5B rows on VM with max_memory_usage=193273528320 and max_memory_usage_for_all_queries=214748364800) on CH v. 20.11.2.1 or higher I get wrong answer from CH, it does not select all distinct rows. And in system.query_log I see wrong value in read_rows field. In version 20.10.7.4 and earlier (I checked about 15-20 different versions) this problem does not appear.

**How to reproduce**
Start docker with yandex/clickhouse-server:20.11.2.1 or higher.

docker run -d -p 8123:8123 --name clickhouse-server --ulimit nofile=262144:262144 --volume=$HOME/some_clickhouse_database:/var/lib/clickhouse yandex/clickhouse-server:20.11.2.1

I tried yandex/clickhouse-client and DBeaver with the same result.
It does't matter whether connected host directory to the container for storing data or not.
Default CH settings from docker image.
Also I checked version of CH installed from repo.

Create table:

CREATE TABLE default.xxx (
	field1 String,
	field2 String,
	field3 String,
	field4 String,
	field5 String,
	field6 String,
	field7 String,
	field8 String,
	field9 String,
	field10 String,
	field11 String,
	field12 String,
	field13 String,
	field14 String,
	field15 String,
	field16 String,
	field17 Date,
	field18 Date,
	field19 String,
	field20 String,
	field21 Int8,
	field22 String
) 
ENGINE = MergeTree()
ORDER BY field1

Create GenerateRandom table to populate our test one:

CREATE TABLE generate_engine_table (
field1 String,
field2 String,
field3 String,
field4 String,
field5 String,
field6 String,
field7 String,
field8 String,
field9 String,
field10 String,
field11 String,
field12 String,
field13 String,
field14 String,
field15 String,
field16 String,
field17 Date,
field18 Date,
field19 String,
field20 String,
field21 Int8,
field22 String
) 
ENGINE = GenerateRandom(1, 50, 3)

Populating test table:

insert into default.xxx
select * from generate_engine_table
limit 10000000

And involving GROUP BY in simple test query:

select count() from (
select
	field1,
	field2,
	field3,
	field4,
	field5,
	field6,
	field7,
	field8,
	field9,
	field10,
	field11,
	field12,
	field13,
	field14,
	field15,
	field16,
	field17,
	field18,
	field19,
	field20,
	field21,
	field22,
	count()
from default.xxx
group by 
	field1,
	field2,
	field3,
	field4,
	field5,
	field6,
	field7,
	field8,
	field9,
	field10,
	field11,
	field12,
	field13,
	field14,
	field15,
	field16,
	field17,
	field18,
	field19,
	field20,
	field21,
	field22
)

**Expected behavior**
I expect to see value 10M in system.query_log field read_rows. But I see values about 8M and these values different every time I involving the test query. Also I expect that CH selects all distinct rows but it does not. 

**Error message and/or stacktrace**
No error or warning messages in console or log files.

**Comment by amosbird** [comment]
> No error or warning messages in console or log files.

Check if there is any `Will lower number of threads to` message in the log.

**Comment by den-crane** [comment]
try `set read_backoff_min_latency_ms=0`

duplicate for https://github.com/ClickHouse/ClickHouse/issues/18137 ?

**Comment by PaulKhripkov** [comment]
Yes, there are messages about lowering threads and read_backoff_min_latency_ms=0 helped. Thank you, guys.
