### ISSUE TITLE
Cannot select non-english column name when using multiple join in a single query.

### ISSUE THREAD

**Issue by kilik52** [ClickHouse/ClickHouse#18937]
**Describe the bug**
Cannot select non-english column name when using multiple join in a single query.

**How to reproduce**

 ClickHouse server version 20.11.4 revision 54442.

* `CREATE TABLE` statements for all tables involved

````
CREATE TABLE store (id UInt32, "名称" String, "状态" String) ENGINE=MergeTree() Order by id;
CREATE TABLE location (id UInt32, name String) ENGINE=MergeTree() Order by id;
CREATE TABLE sales ("日期" Date, "店铺" UInt32, "地址" UInt32, "销售额" Float32) ENGINE=MergeTree() Order by "日期";
````

* Sample data for all these tables

````
INSERT INTO store VALUES (1,'店铺1','启用'),(2,'店铺2','停用');
INSERT INTO location VALUES (1,'上海市'),(2,'北京市');
INSERT INTO sales VALUES ('2021-01-01',1,1,10),('2021-01-02',2,2,20);
````

**Query which cause error**

````
SELECT
    `日期`,
    location.name,
    store.`状态`
FROM sales
LEFT JOIN store ON store.id = `店铺`
LEFT JOIN location ON location.id = `地址`
````

**Error message and/or stacktrace**

Code: 47. DB::Exception: Received from localhost:9000. DB::Exception: Missing columns: '状态' while processing query: 'SELECT `地址`, `店铺`, `日期`, `状态`, id AS `--store.id` FROM sales ALL LEFT JOIN (SELECT * FROM store) AS store ON `--store.id` = `店铺`', required columns: '地址' '店铺' '日期' 'id' '状态', source columns: '销售额' '地址' '店铺' '日期', joined columns: 'id' 'store.名称' 'store.状态'. 

**Additional context**

I can select `english column name` when using multiple left join: 

````
SELECT
    `日期`,
    location.name,
    store.id
FROM sales
LEFT JOIN store ON store.id = `店铺`
LEFT JOIN location ON location.id = `地址`
````

Result: 

````
Query id: f352f76b-575c-4f2d-873f-63aae289a61d

┌───────日期─┬─location.name─┬─store.id─┐
│ 2021-01-01 │ 上海市        │        1 │
│ 2021-01-02 │ 北京市        │        2 │
└────────────┴───────────────┴──────────┘

2 rows in set. Elapsed: 0.016 sec. 
````

I can select `non-english column name` when using **single** left join: 

````
SELECT store.`状态`
FROM sales
LEFT JOIN store ON store.id = `店铺`
````

Result: 

````
Query id: f70f9b1e-ff0f-43a4-a9e0-9bbf31c93333

┌─store.状态─┐
│ 启用       │
│ 停用       │
└────────────┘

2 rows in set. Elapsed: 0.014 sec. 
````

**Comment by mathfool** [comment]
![image](https://user-images.githubusercontent.com/1754669/104617056-f55d2380-56c5-11eb-998b-8f18f2c6ced2.png)
looks like somehow the required columns set stores only short name and the key used here is the long column name. Not sure if this is only for non-english.

**Comment by arjenzhou** [comment]
HI, is there any progress about this?
@alexey-milovidov @mathfool

**Comment by alexey-milovidov** [comment]
Looks like it is solved.
