### ISSUE TITLE
Aggregate functions SUM/COUNT don't work in combination on sub-select / PowerBI direct query 

### ISSUE THREAD

**Issue by gersmann** [ClickHouse/ClickHouse#18956]
**Describe the bug**
Aggregate functions are not working under certain circumstances.
**How to reproduce**
Clickhouse 20.12.4.5

```
select sum(C1) as C1,
    count(C1) as C2
from 
(
    select value as C1
    from system.asynchronous_metric_log
) as ITBL;
```

**Expected behavior**
Aggregate function SUM and COUNT return valid results.

**Error message and/or stacktrace**
SQL Error [184]: ClickHouse exception, code: 184, host: xxx port: 8123; Code: 184, e.displayText() = DB::Exception: Aggregate function sum(C1) is found inside another aggregate function in query: While processing sum(C1) AS C1 (version 20.12.4.5 (official build))

**Additional context**
The query is auto-generated by a BI tool, it looks a bit strange but should be valid SQL. This type of SQL is generated by PowerBI direct query, which i just managed to get running using a custom connector. PowerBI basically generates all SQL that uses aggregate functions like this. It would be very unfortunate if this was a barrier to use it in conjunction with Clickhouse.

**Comment by den-crane** [comment]
It's how aliases work in CH.

Use table specifier -- ITBL.C1: 
```sql
select sum(C1) as C1,
    count(ITBL.C1) as C2
from 
(
    select value as C1
    from system.asynchronous_metric_log
) as ITBL;

```

**Comment by gersmann** [comment]
@den-crane so there is zero chance that this is going to work in the mid-term future, if I understand correctly? Unfortunately this rules CH out in scenarios where there is no control over the generated SQL (this SQL works for 50+ datasources including all major databases).

**Comment by UnamedRus** [comment]
https://github.com/ClickHouse/ClickHouse/issues/9715
Related Feature request.

**Comment by UnamedRus** [comment]
@gersmann 
https://github.com/ClickHouse/ClickHouse/pull/22044

```
21.5.1.6436
set prefer_column_name_to_alias=1;

SELECT
    sum(C1) AS C1,
    count(C1) AS C2
FROM
(
    SELECT value AS C1
    FROM system.asynchronous_metric_log
) AS ITBL

Query id: ef243910-c3c7-49d5-993c-f0072b8da5ac

┌────────────────C1─┬──────C2─┐
│ 11755715575942096 │ 5643383 │
└───────────────────┴─────────┘

```

**Comment by gersmann** [comment]
@UnamedRus very nice, great update!
