### ISSUE TITLE
Insert into Distributed table partially done when NetException Timeout: connect timed out occurs

### ISSUE THREAD

**Issue by kymtwyf** [ClickHouse/ClickHouse#18965]
**Describe the unexpected behaviour**
I am trying to insert into a distributed table via http endpoint using parquet format. However, one of the host went unavailable during the insertion. The http request was not successful (with `wait_end_of_query=1`)

The distributed table has 6 shards with only **ONE** replica.

**How to reproduce**
* Which ClickHouse server version to use
20.6.5.8
* Which interface to use, if matters
HTTP
* Non-default settings, if any
wait_end_of_query=1
* `CREATE TABLE` statements for all tables involved
N/A
* Sample data for all these tables, use [clickhouse-obfuscator]
N/A
* Queries to run that lead to unexpected result
INSERT INTO DISTRIBUTED_TABLE

**Expected behavior**
Distributed table insertion only success when all hosts are inserted successfully. Otherwise, no data is inserted in this API call. 

**Error message and/or stacktrace**
```
Code: 209, e.displayText() = DB::NetException: Timeout: connect timed out: 10.159.49.136:9000 (clickhouse-server-1:9000): Insertion status:
Wrote 1 blocks and 1340784 rows on shard 0 replica 0, clickhouse-server-0:9000 (average 343 ms per block)
Wrote 0 blocks and 0 rows on shard 1 replica 0, clickhouse-server-1:9000 (average 287 ms per block)
Wrote 1 blocks and 1341412 rows on shard 2 replica 0, clickhouse-server-2:9000 (average 398 ms per block)
Wrote 1 blocks and 1339375 rows on shard 3 replica 0, clickhouse-server-3:9000 (average 337 ms per block)
Wrote 1 blocks and 1339216 rows on shard 4 replica 0, clickhouse-server-4:9000 (average 336 ms per block)
Wrote 1 blocks and 1338525 rows on shard 5 replica 0, clickhouse-server-5:9000 (average 349 ms per block)
(version 20.6.5.8)
```

**Additional context**
N/A

**Comment by den-crane** [comment]
No transactions right now. No 2FC.

**Comment by kymtwyf** [comment]
@den-crane  in such case, how can I handle the failure ? 

And do we have plan to support transactions ?

**Comment by den-crane** [comment]
>how can I handle the failure ?

Make inserts are idempotent. Repeat until success. Using Replicated tables and insert deduplication.
https://clickhouse.tech/docs/en/engines/table-engines/mergetree-family/replication/


>And do we have plan to support transactions ?

If it's god's will it will happen.
