### ISSUE TITLE
Non-deterministic function being removed from where clause (SelectQueryInfo)

### ISSUE THREAD

**Issue by filipecaixeta** [ClickHouse/ClickHouse#18975]
[QUESTION]
I'm creating a storage that needs to get all the where clauses. 
If I do a `SELECT * FROM table WHERE funct()` this funct is removed from the SelectQueryInfo
This happens even when the function is set to isDeterministic=false
The only function that is not removed is rand()
Even functions that take a table column as argument are being removed

**Comment by KochetovNicolai** [comment]
Hi, @filipecaixeta .
Could you please show an example where you want to find those functions?

`SelectQueryInfo` contains different information that may be helpful to execute query. E.g. `SelectQueryInfo::query` is a query AST, which should contain unchanged query with `WHERE` clause. It is used by `MergeTree` in PK analysis:
https://github.com/ClickHouse/ClickHouse/blob/44758935dfcd018e704ad51a7b1793b8321c2def/src/Storages/MergeTree/KeyCondition.cpp#L409-L410

**Comment by filipecaixeta** [comment]
Solved
My function was returning `return DataTypeUInt8().createColumnConst(elem.column->size(), 1u);`
When I added `return DataTypeUInt8().createColumnConst(elem.column->size(), 1u)->convertToFullColumnIfConst();` it appeared in the `WHERE` clause.
It looks like there is an optimization step running before this `query_info` is generated
