### ISSUE TITLE
`optimize_move_functions_out_of_any` is questionable

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#18973]
**Describe the situation**
There is a setting `optimize_move_functions_out_of_any` that is turn on by default.
It moves functions out of `any` aggregate function.
But it's not always beneficial.

Example:
```
any(substring(large_string, 1, 10))
```
is better than
```
substring(any(large_string), 1, 10)
```

**Comment by den-crane** [comment]
I would disable it by default because of https://github.com/ClickHouse/ClickHouse/issues/18051
