### ISSUE TITLE
Inaccurate result when casting to Float64

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#18999]
```
SELECT cast('1.5008753E7', 'Float64')

┌─cast('1.5008753E7', 'Float64')─┐
│             15008753.000000002 │
└────────────────────────────────┘

SELECT toFloat64('1.5008753E7')

┌─toFloat64('1.5008753E7')─┐
│       15008753.000000002 │
└──────────────────────────┘
```

But: 
```
select 1.5008753E7;

┌─15008753.─┐
│  15008753 │
└───────────┘

SELECT * FROM values('x Float64', (1.5008753E7))

┌────────x─┐
│ 15008753 │
└──────────┘
```

So for example `SELECT toFloat64('1.5008753E7') = 1.5008753E7;` returns zero. 

Also type casting don't support hex floats:

```
SELECT toFloat64('0x1.f7ced916872b0p-4')

--- DB::Exception: Cannot parse string '0x1.f7ced916872b0p-4' as Float64:
```

While hex literals in queries supported:
```
SELECT 0x1.f7ced916872b0p-4;

┌─0.123─┐
│ 0.123 │
└───────┘
```

Context: jdbc driver pass floats as strings with casting. It leads to loosing of precision.

**Comment by filimonov** [comment]
Same as https://github.com/ClickHouse/ClickHouse/issues/17933

**Comment by KochetovNicolai** [comment]
`cast` uses fast and not very precise parser from string:
https://github.com/ClickHouse/ClickHouse/blob/d88d3de0d18f4879c8994b03ef7c4b957b6a83cf/src/IO/readFloatText.h#L317

Maybe add setting for using more precise parser?

**Comment by filimonov** [comment]
Yes, let's do it. There are cases when precision iw more important than speed.
