### ISSUE TITLE
getMacro function didn't return correct value

### ISSUE THREAD

**Issue by chenk818** [ClickHouse/ClickHouse#18996]
**Describe the bug**
in my config file defined macro like below
![image](https://user-images.githubusercontent.com/1886495/104429136-3c60f100-55c0-11eb-8e0e-99b2b219eefd.png)

when i create a ReplicatedMergeTree with macro {shard} and {replica}，I found uncorrect node in Zookeeper with RSHARD and RREPLICA. meanwhile getMacro return uncorrect value。
![image](https://user-images.githubusercontent.com/1886495/104427320-0fabda00-55be-11eb-9d4b-57b7703c9654.png)
After reboot clickhouse server, this problem disappear

timeline  information:
the ck server started at 2020-12-15;
At 2020-12-29，i created a replicated table using macro and  hadn't problem(via zookeeper node)。
At 2021-1-8 this problem happend。

* ClickHouse server version 20.10.6

**Comment by KochetovNicolai** [comment]
Macros are initialized on server start. Change of macros in config file does not apply until server restart. Function `getMacro` has probably used old value.

**Comment by den-crane** [comment]
Verify results getMacro results with `select * from system.macros`

**Comment by chenk818** [comment]
> Verify results getMacro results with `select * from system.macros`
system.macros returns the same value

**Comment by chenk818** [comment]
> Macros are initialized on server start. Change of macros in config file does not apply until server restart. Function `getMacro` has probably used old value.

Change of macros in config file will be updated  by ConfigReloader,i checked it 
 otherwise,no one set thats wrong values(RSHARD,RREPLICA)
