### ISSUE TITLE
it's very slowly when I dropping clumns

### ISSUE THREAD

**Issue by intfish123** [ClickHouse/ClickHouse#19066]
(you don't have to strictly follow this form)

**Describe the bug**
It's very slowly when I dropping clumns. It has elapsed 166100 seconds.

**How to reproduce**
* Which ClickHouse server version to use
my clickhouse version is "20.5.2.7-2"
* Which interface to use, if matters
I execute this sql: alter table log.xx drop column if exists studentname
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

**Expected behavior**

**Error message and/or stacktrace**

**Additional context**

**Comment by den-crane** [comment]
1. 20.5.2.7 is out of support.
2. Check system.merges -- long merge can block `drop column`
3. use `system stop merges tablename; drop column; system start merges tablename;` if you need to drop column immediately.

**Comment by alexey-milovidov** [comment]
The issue should not exist on newer versions, as ALTER query has been made completely lock-free.
