### ISSUE TITLE
multiIf expression as first parameter of dictGet()

### ISSUE THREAD

**Issue by pic-Nick** [ClickHouse/ClickHouse#19079]
This query works fine:
```
with 'dict1' as param
select dictGet(if(param = 'dict1', 'dictName1', 'dictName2'), 'datestart', toUInt64(202018))
```
but this query produces an error:
```
with 'dict1' as param
select dictGet(multiIf(param = 'dict1', 'dictName1', 'dictName2'), 'datestart', toUInt64(202018))

Code: 43, e.displayText() = DB::Exception: Illegal type String of first argument of function dictGet, expected a const string. (version 20.7.4.11 (official build))
```
The same with dictGetDate(), but with different error message:
`Code: 44, e.displayText() = DB::Exception: Argument at index 0 for function dictGetDate must be constant (version 20.7.4.11 (official build))`

Structures of the dictionaries is the same.
Why `multiIf()` is so different and is it possible to make it behave like `if()`?

**Comment by alexey-milovidov** [comment]
Culprit: `SELECT isConstant(multiIf('dict1' = 'dict1', 'dictName1', 'dictName2'))`
It is the implementation detail of `multiIf`.
Yes, it's possible to make it return constant expression in this case.

**Comment by kitaisreal** [comment]
Fixed in https://github.com/ClickHouse/ClickHouse/pull/19533.
