### ISSUE TITLE
"ALTER TABLE … DELETE Statement" does not work because "Mutations are not supported by storage Distributed"

### ISSUE THREAD

**Issue by etc-crontab** [ClickHouse/ClickHouse#19089]
Hello,

**Describe the unexpected behaviour**
When trying to perform this kind of statement 
```sql
ALTER TABLE company_db.events_distr ON CLUSTER 'company_cluster' DELETE WHERE uid = 100;
```
the following error message is returned:
Mutations are not supported by storage Distributed

**How to reproduce**
I've used the clickhouse cluster dockerfile from this repo: https://github.com/tetafro/clickhouse-cluster.git, updating the docker-compose.yml file to load the version 20.8.11.17. This will create a cluster with 2 shards and 2 replicas.
* ClickHouse server version used: 20.8.11.17 (official build)
* Interface: command line client
* No specific settings
* Statements executed:
```sql
CREATE DATABASE company_db ON CLUSTER company_cluster;
 
CREATE TABLE company_db.events ON CLUSTER 'company_cluster' (
    time DateTime,
    uid  Int64,
    type LowCardinality(String)
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{cluster}/{shard}/table', '{replica}')
PARTITION BY toDate(time)
ORDER BY (uid);

CREATE TABLE company_db.events_distr ON CLUSTER 'company_cluster' AS company_db.events
ENGINE = Distributed('company_cluster', company_db, events, uid);
```
* Sample data:
```sql
INSERT INTO company_db.events_distr VALUES ('2020-01-01 10:00:00', 100, 'view'), ('2020-01-01 10:05:00', 101, 'view'), ('2020-01-01 11:00:00', 100, 'contact'), ('2020-01-01 12:10:00', 101, 'view'), ('2020-01-02 08:10:00', 100, 'view'), ('2020-01-03 13:00:00', 103, 'view');
```
* Queries to run that lead to unexpected result:
```sql
ALTER TABLE company_db.events_distr ON CLUSTER 'company_cluster' DELETE WHERE uid = 100;
```

**Expected behavior**
The 3 entries with a uid of 100 should be removed from the different tables. If this behavior is expected, the page https://clickhouse.tech/docs/en/sql-reference/statements/alter/delete/ and the first "Note" on this page https://clickhouse.tech/docs/en/sql-reference/statements/alter/#query_language_queries_alter should probably be modified to say that this is not supported.

**Error message and/or stacktrace**
Code: 48, e.displayText() = DB::Exception: Mutations are not supported by storage Distributed (version 20.8.11.17 (official build))

**Additional context**
If this is expected, is it possible to put it in the documentation and a way to achieve this? It probably means that we have to connect to the different shards and launch the 'ALTER' query there.

Thanks in advance for your help.

**Comment by den-crane** [comment]
Mutations are only supported by *MergeTree.



use mutations directly against  company_db.events `ALTER TABLE company_db.events ON CLUSTER 'company_cluster' DELETE WHERE uid = 100;`

**Comment by etc-crontab** [comment]
Thanks a lot @den-crane for the fast answer and the provided query.
