### ISSUE TITLE
Import from ORC doesn't finish

### ISSUE THREAD

**Issue by glader** [ClickHouse/ClickHouse#19095]
I have an ORC file with 10 mln rows. I created a table with the same structure and executed `insert into <table> select * from file('<filename>', ORC, '<fields>')` . Rows were inserted, and `select count(1) from <table>` gave me 10 mln. But query didn't stop, and still is running. `select query, written_rows from system.processes` shows 700 mln inserted rows and counting.

`CREATE TABLE t (a lot of ordinary fields) ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{shard}/t', '{replica}') PARTITION BY toYYYYMM(calday) ORDER BY (calday) SETTINGS index_granularity = 8192`
clickhouse version 20.8.2.3.

**Expected behavior**
Query is finished.

**Comment by alexey-milovidov** [comment]
Could you please share the file to reproduce the issue?
You can obfuscate data or send it privately to clickhouse-feedback@yandex-team.com

**Comment by glader** [comment]
Sent to  clickhouse-feedback@yandex-team.com

**Comment by KochetovNicolai** [comment]
Repro:

```sql
create table t (number UInt64) engine = MergeTree order by number;
select number from numbers(10) into outfile 'out.orc' format ORC settings max_block_size = 5;
```
This query cause infinite loop:

```sh
$ clickhouse client -q "insert into t format ORC" < ~/out.orc
```
Data is inserted all the time:
```
:) select count() from t

SELECT count()
FROM t

Query id: ac95b92c-2307-4c2c-97ef-2d436b71521b

┌─count()─┐
│ 3145650 │
└─────────┘

1 rows in set. Elapsed: 0.002 sec. 

 :) select count() from t

SELECT count()
FROM t

Query id: 57bb9beb-8aa3-4132-8175-9242c74de50f

┌─count()─┐
│ 4194200 │
└─────────┘
```
