### ISSUE TITLE
Race condition in HashJoin::setTotals.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#19129]
**Describe the bug**
https://clickhouse-test-reports.s3.yandex.net/19017/489d9d186ab9f0844cc55421739070f46796732c/stress_test_(thread)/stderr.log

**Comment by qoega** [comment]
https://clickhouse-test-reports.s3.yandex.net/19884/2459777f57a265378e949d7ab9926c29fc7b4de6/stress_test_(thread).html#fail1

**Comment by alexey-milovidov** [comment]
No longer relevant. Fixed.
