### ISSUE TITLE
Data race near Context::addQueryAccessInfo.

### ISSUE THREAD

**Issue by alesapin** [ClickHouse/ClickHouse#19130]
Report https://clickhouse-test-reports.s3.yandex.net/19009/63b5f8b8dabca200f95b35a54bff15f0543051b9/functional_stateless_tests_(thread).html#fail1

cc @vitlibar

**Comment by amosbird** [comment]
This was a known race and was fixed by adding a guard: `internal` query flag https://github.com/ClickHouse/ClickHouse/blob/d2366b5c6c16f6c0b478b8332010968b09b12bf3/src/Interpreters/InterpreterSelectQuery.cpp#L1605

It seems still broken...

**Comment by alexey-milovidov** [comment]
Fixed in #19313
