### ISSUE TITLE
how to get middle-state value from an AggregatingMergeTree table

### ISSUE THREAD

**Issue by Tasselmi** [ClickHouse/ClickHouse#19135]
I follow the instruct of AggregatingMergeTree engine:
```
CREATE MATERIALIZED VIEW test.basic
ENGINE = AggregatingMergeTree() PARTITION BY toYYYYMM(StartDate) ORDER BY (CounterID, StartDate)
AS SELECT
    CounterID,
    StartDate,
    groupBitmapState(UserID) AS user_bitmap_obj  
FROM test.visits
GROUP BY CounterID, StartDate;
```

how can I get a bitmap object, for example `StartDate = '2021-01-15' and CounterID = xxx`
then I can do some bitmapAnd operation with other bitmap object.  As groupBitmapMerge returns `bitmapCardinality` which is not I want.

I can not use user_bitmap_obj directly either, because clickhouse supports only Scalar subquery, an  AggregatingMergeTree table may returns more than one row with one pair of sorting key.

I got another example from some page :
```
DROP TABLE IF EXISTS bitmap_column_expr_test2;
CREATE TABLE bitmap_column_expr_test2
(
    tag_id String,
    z AggregateFunction(groupBitmap, UInt32)
)
ENGINE = MergeTree
ORDER BY tag_id;

INSERT INTO bitmap_column_expr_test2 VALUES ('tag1', bitmapBuild(cast([1,2,3,4,5,6,7,8,9,10] as Array(UInt32))));
INSERT INTO bitmap_column_expr_test2 VALUES ('tag2', bitmapBuild(cast([6,7,8,9,10,11,12,13,14,15] as Array(UInt32))));
INSERT INTO bitmap_column_expr_test2 VALUES ('tag3', bitmapBuild(cast([2,4,6,8,10,12] as Array(UInt32))));

SELECT groupBitmapOr(z) FROM bitmap_column_expr_test2 WHERE like(tag_id, 'tag%');
┌─groupBitmapOr(z)─┐
│             15   │
└──────────────────┘

SELECT arraySort(bitmapToArray(groupBitmapOrState(z))) FROM bitmap_column_expr_test2 WHERE like(tag_id, 'tag%');
┌─arraySort(bitmapToArray(groupBitmapOrState(z)))─┐
│ [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]           │
└─────────────────────────────────────────────────┘
```

but when I run `select bitmapCardinality(groupBitmapOrState(user_bitmap_obj))`, it failed.
```
The type AggregateFunction(groupBitmap, UInt32) of argument for aggregate function groupBitmap is illegal, because it cannot be used in Bitmap operations
```

IT IS OK WITH MergeTree ENGINE, BUT NOT OK WITH AggregatingMergeTree ENGINE, WHICH MAKES ME CONFUSED.

**Comment by den-crane** [comment]
may be:
finalizeAggregation https://clickhouse.tech/docs/en/sql-reference/functions/other-functions/#function-finalizeaggregation
-MergeState https://clickhouse.tech/docs/en/sql-reference/aggregate-functions/combinators/#aggregate_functions_combinators-mergestate

**Comment by Tasselmi** [comment]
> may be:
> finalizeAggregation https://clickhouse.tech/docs/en/sql-reference/functions/other-functions/#function-finalizeaggregation
> -MergeState https://clickhouse.tech/docs/en/sql-reference/aggregate-functions/combinators/#aggregate_functions_combinators-mergestate

`groupBitmapMergeState` works fine for me. Thanks a lot.
