### ISSUE TITLE
RabbitMQ topic name as column data?

### ISSUE THREAD

**Issue by alexeykulakov** [ClickHouse/ClickHouse#19151]
Inspired by the article https://clickhouse.tech/docs/en/engines/table-engines/integrations/rabbitmq/

It's clear how to get message payloads from RabbitMQ, but how to get topic names as column data?

**Comment by UnamedRus** [comment]
It looks like it possible to [get](https://clickhouse.tech/docs/en/engines/table-engines/integrations/rabbitmq/#virtual-columns) _exchange_name, but not topic.

When you define your MATERIALIZED VIEW on top of rabbit table you can include it in SELECT query like this:

```
SELECT _exchange_name, * FROM rabbit_table
```

**Comment by alexeykulakov** [comment]
But exchanxge name is not evough for me. I have some kind of IOT network, where each device send to the broker it's indicators.
For example:
Topic: Mac_address/location_id/stats_ind
Payload: {settings: {...}}

So I need to get topic string to save mac and location as separate columns.
It seems that this should be like a standart issue.

**Comment by filimonov** [comment]
@kssenii maybe you can add it?

**Comment by kssenii** [comment]
@alexeykulakov probably by topic you mean routing keys? (In rabbitmq topics mean pattern-based routing via `topic exchange`, so seems like you are referring to `routing keys`). They are not saved in message metadata and are dropped after exchange passing. But you can just add  `Mac_address/location_id/stats_ind` into optional publishing parameter  `messageID`  (a string) and it is available as `_message_id` (string column) in virtual columns.

**Comment by filimonov** [comment]
@alexeykulakov ?

**Comment by alexey-milovidov** [comment]
No info provided.
