### ISSUE TITLE
Clickhouse failed to start, permission denied

### ISSUE THREAD

**Issue by Goolen** [ClickHouse/ClickHouse#19223]
Hello：
CentOS Linux release 7.9
ClickHouse server version 20.12.5.14 (official build).
yum installed.

when I use command "systemctl start clickhouse-server"   to start clickhouse , and Failed to start , 
clickhouse-server.err.log and clickhouse-server.log is empty .

in /var/log/message，is：
clickhouse-server: Processing configuration file '/etc/clickhouse-server/config.xml'.
clickhouse-server: std::exception. Code: 1001, type: std::__1::__fs::filesystem::filesystem_error, e.what() = filesystem error: in posix_stat:  failed to determine attributes for the specified path: Permission denied [/etc/clickhouse-server/config.xml], Stack trace (when copying this message, always include the   
lines below):
clickhouse-server: 0. std::__1::system_error::system_error(std::__1::error_code, std::__1::basic_string<char, std::__1::char_traits<char>, std::    
__1::allocator<char> > const&) @ 0x123f8d83 in ?

I checked the directory and file permissions，is OK
-rw-rw---- 1 clickhouse clickhouse 33809 Jan 18 09:06 config.xml

drwxr-x---  2 clickhouse clickhouse 4096 Jan 18 09:25 access
drwxr-x--- 10 clickhouse clickhouse 4096 Jan 18 09:30 data
drwxr-x---  2 clickhouse clickhouse 4096 Jan 18 09:25 format_schemas
drwxr-x---  2 clickhouse clickhouse 4096 Jan 18 09:30 log
drwxr-x---  2 clickhouse clickhouse 4096 Jan 18 09:25 tmp
drwxr-x---  2 clickhouse clickhouse 4096 Jan 18 09:25 user_files

But when I use command “/usr/bin/clickhouse-server --config=/etc/clickhouse-server/config.xml” to start ，is OK

Can you take a look for me? Thank you very much.

**Comment by zhangjmruc** [comment]
Would you please show us how you use command “/usr/bin/clickhouse-server --config=/etc/clickhouse-server/config.xml” to start?
Normally, you should only use clickhouse user to manually start clickhouse server. 
sudo -u clickhouse /usr/bin/clickhouse-server --config=/etc/clickhouse-server/config.xml

**Comment by hexiaoting** [comment]
check `/etc` and `/etc/clickhouse-server` directories's permission(mode and owner)

**Comment by Goolen** [comment]
> check `/etc` and `/etc/clickhouse-server` directories's permission(mode and owner)

# ll -d /etc/
drwxr-xr-x. 110 root root 8192 Jan 15 15:13 /etc/

# ll -d /etc/clickhouse-server
drw-rw---- 4 clickhouse clickhouse 183 Jan 18 09:06 /etc/clickhouse-server

**Comment by Goolen** [comment]
> Would you please show us how you use command “/usr/bin/clickhouse-server --config=/etc/clickhouse-server/config.xml” to start?
> Normally, you should only use clickhouse user to manually start clickhouse server.
> sudo -u clickhouse /usr/bin/clickhouse-server --config=/etc/clickhouse-server/config.xml

# ps aux | grep click
root     15751  0.0  0.0 112828  2292 pts/0    S+   13:30   0:00 grep --color=auto click
# /usr/bin/clickhouse-server --config=/etc/clickhouse-server/config.xml --daemon
# ps aux | grep click
root     15803  6.0  0.4 804000 133620 ?       DLsl 13:30   0:00 /usr/bin/clickhouse-server --config=/etc/clickhouse-server/config.xml --daemon

**Comment by Goolen** [comment]
[root@db1074 ~]# ps aux | grep click
root     15984  0.0  0.0 112828  2196 pts/0    S+   13:32   0:00 grep --color=auto click
[root@db1074 ~]# 
[root@db1074 ~]# systemctl start clickhouse-server
[root@db1074 ~]# 
[root@db1074 ~]# ps aux | grep click              
root     16021  0.0  0.0 112828  2244 pts/0    S+   13:32   0:00 grep --color=auto click

**Comment by Goolen** [comment]
[root@db1074 ~]# ps aux | grep click
root     15751  0.0  0.0 112828  2292 pts/0    S+   13:30   0:00 grep --color=auto click
[root@db1074 ~]# 
[root@db1074 ~]# /usr/bin/clickhouse-server --config=/etc/clickhouse-server/config.xml --daemon
[root@db1074 ~]# 
[root@db1074 ~]# ps aux | grep click
root     15803  6.0  0.4 804000 133620 ?       DLsl 13:30   0:00 /usr/bin/clickhouse-server --config=/etc/clickhouse-server/config.xml --daemon
root     15809  0.0  0.0 112828  2240 pts/0    S+   13:30   0:00 grep --color=auto click
[root@db1074 ~]#

**Comment by hexiaoting** [comment]
> > check `/etc` and `/etc/clickhouse-server` directories's permission(mode and owner)
> 
> # ll -d /etc/
> drwxr-xr-x. 110 root root 8192 Jan 15 15:13 /etc/
> 
> # ll -d /etc/clickhouse-server
> drw-rw---- 4 clickhouse clickhouse 183 Jan 18 09:06 /etc/clickhouse-server

chmod /etc to owner clickhouse, and use clickhouse users to start server

**Comment by zhangjmruc** [comment]
change the permission for /etc/clickhouse-server to drwxr-xr-x, as blow:
drwxr-xr-x   4 root                   root                     4096 Oct 26 10:15 clickhouse-server/

chmod 644 /etc/clickhouse-server

**Comment by Goolen** [comment]
> /etc/clickhouse-serv

thank you first
After changing the permissions to 755 , start is OK.

There is no permission to change this directory after installation，I don't know why it became 660.

**Comment by Goolen** [comment]
> > > check `/etc` and `/etc/clickhouse-server` directories's permission(mode and owner)
> > 
> > 
> > # ll -d /etc/
> > drwxr-xr-x. 110 root root 8192 Jan 15 15:13 /etc/
> > # ll -d /etc/clickhouse-server
> > drw-rw---- 4 clickhouse clickhouse 183 Jan 18 09:06 /etc/clickhouse-server
> 
> chown /etc to owner clickhouse, and use clickhouse users to start server

Thank you.
The problem has been solved，reference @zhangjmruc

**Comment by krafter** [comment]
setting WorkingDirectory=/<config_file_dir>/<owned_by_clickhouse_user>/ in systemctl service helped me

**Comment by amolsr** [comment]
what is the password for clickhouse ubuntu user.?
