### ISSUE TITLE
Template engine for materialized views

### ISSUE THREAD

**Issue by thyn** [ClickHouse/ClickHouse#19227]
Materialized views are very great. But fields count are growing very fast. We also need to have multiple materialized views with different  detailing levels (session ,pages,users,scenes and etc.) of the practically the same fields lists (200+ fields) from multiple raw tables (from different sources).

Does anyone sql template engines for clickhouse? Can you share your experience?

**Comment by den-crane** [comment]
It's unclear what are you going to count? number of ?

You can different tools, for example https://clickhouse.tech/docs/en/engines/table-engines/mergetree-family/summingmergetree/#nested-structures
Or do pivot and store rows instead of columns.
