### ISSUE TITLE
inconsistency on inserted rows value on ReplicatedSummingMergeTree

### ISSUE THREAD

**Issue by m7shapan** [ClickHouse/ClickHouse#19249]
Hi,
I'm facing an inconsistency issue on rows value when I trying to insert the same data on ReplicatedSummingMergeTree

 to reproduce the issue I need to create a ReplicatedSummingMergeTree table
```sql
CREATE TABLE IF NOT EXISTS default.test_table ON CLUSTER analytics
(
    date    Date,
    hour    UInt8,
    value   Float64,
    device  String,
    country String
) ENGINE = ReplicatedSummingMergeTree(
           '/clickhouse_test_table_cluster/tables/{shard}/hits',
           '{replica}',
           value
    )
      ORDER BY (date, hour, device, country)
      PARTITION BY toYYYYMM(date);
```

then try to insert the same data multiple times, example
```sql
INSERT INTO default.test_table (date, hour, value, device, country)
VALUES ('2021-01-18', 1, 5, 'android', 'EG');

INSERT INTO default.test_table (date, hour, value, device, country)
VALUES ('2021-01-18', 1, 5, 'android', 'EG');

INSERT INTO default.test_table (date, hour, value, device, country)
VALUES ('2021-01-18', 1, 5, 'android', 'EG');
```

then try to get the sum of the table rows
```sql
select * from test_table
```
i expected `15` but the actual was `5`
```
┌───────date─┬─hour─┬─value─┬─device──┬─country─┐
│ 2021-01-18 │    1 │     5 │ android │ EG      │
└────────────┴──────┴───────┴─────────┴─────────┘
```

**Comment by UnamedRus** [comment]
It's because of [insert-deduplicate](https://clickhouse.tech/docs/en/operations/settings/settings/#settings-insert-deduplicate)

```
Data blocks are deduplicated. For multiple writes of the same data block (data blocks of the same size containing the same rows in the same order), the block is only written once. The reason for this is in case of network failures when the client application doesn’t know if the data was written to the DB, so the INSERT query can simply be repeated. It doesn’t matter which replica INSERTs were sent to with identical data. INSERTs are idempotent. Deduplication parameters are controlled by merge_tree server settings.
```

**Comment by den-crane** [comment]
https://clickhouse.tech/docs/en/engines/table-engines/mergetree-family/replication/

Data blocks are deduplicated. For multiple writes of the same data block (data blocks of the same size containing the same rows in the same order), the block is only written once. The reason for this is in case of network failures when the client application doesn’t know if the data was written to the DB, so the INSERT query can simply be repeated. It doesn’t matter which replica INSERTs were sent to with identical data. INSERTs are idempotent. Deduplication parameters are controlled by merge_tree server settings.
