### ISSUE TITLE
Any query results in a strange 404 error.

### ISSUE THREAD

**Issue by zarkones** [ClickHouse/ClickHouse#19247]
**Bug that happens**
I'm using Node's clickhouse module, every time I try to do a query I'm welcomed with the fallowing in the console.

```
Error: 404: �9?%�J��PG!U/%�� '�2$��DCS�V����ʵ"9��$3?�J�%�$1)�8U!5'5��(391'� �(1�8��H!%?�8O�D!�"��DA�,��83?O��@��H�D�TA#?--3931G!�43'ES�
                                         ����2|


1 getErrorObj
  /home/REDACTED/Desktop/programming/REDACTED/node_modules/clickhouse/index.js:225

2 Request._callback
  /home/REDACTED/Desktop/programming/REDACTED/node_modules/clickhouse/index.js:557

3 Request.self.callback
  /home/REDACTED/Desktop/programming/REDACTED/node_modules/request/request.js:185

4 anonymous
  /home/REDACTED/Desktop/programming/REDACTED/node_modules/request/request.js:1161

5 anonymous
  /home/REDACTED/Desktop/programming/REDACTED/node_modules/request/request.js:1083

```

**Environment setup**
ClickHouse server version 20.12.4 revision 54442 running on Debian 10 based Linux distribution inside of Docker.

**Things to note**
Executing queries via ClickHouse client from inside of the image via CLI works. Also, from outside of Docker I'm able to execute queries via DBeaver.
It seems that the error appears only through Node.

**Comment by alexey-milovidov** [comment]
You should create an issue in GitHub of the Node.js driver.

**Comment by alexey-milovidov** [comment]
https://github.com/apla/node-clickhouse/issues

**Comment by zarkones** [comment]
@alexey-milovidov Thank you for your help. Cheers.
