### ISSUE TITLE
Filter pushdown into S3 (using S3 SELECT API)

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#19275]
https://docs.aws.amazon.com/AmazonS3/latest/dev/s3-glacier-select-sql-reference-select.html
https://docs.min.io/docs/minio-select-api-quickstart-guide.html

**Use case**
The user queries data from S3. We take subset of expressions from ClickHouse query and send them to S3 using its API.

**Implementation**
Similar to `transformQueryForExternalDatabase`.

**Additional context**
The settings
```
InputSerialization={
        'CSV': {
            "FileHeaderInfo": "USE",
        },
        'CompressionType': 'GZIP',
    },
    OutputSerialization={'CSV': {}},
```
will be inferred automatically.

S3 is using slow query engine internally (every query engine is slow comparing to ClickHouse) and in some cases queries with filters may process slower than fetching all data into ClickHouse and processing it, despite the network cost.

**Comment by alexey-milovidov** [comment]
I expect S3 SELECT is either too slow (slower than reading and filtering by ClickHouse) or does not have enough compatible semantics, so better to avoid implementing this feature.

**Comment by alexey-milovidov** [comment]
Also, 1.5 years have passed and there were no comments or thumb-ups on this feature.

**Comment by ovidiubuligan** [comment]
@alexey-milovidov more than 2 years have passed since the case was opened . Do you know if the S3 query engine has improved ?

**Comment by alexey-milovidov** [comment]
@ovidiubuligan, no, we didn't check it.
