### ISSUE TITLE
Materialized View data discrepancy 

### ISSUE THREAD

**Issue by dmftaras** [ClickHouse/ClickHouse#19282]
**Describe the unexpected behaviour**
So basically initial INSERT query will fill the `orders_log.product_sales_by_day` table properly, and MV will continue doing so til some point, but after a few days, part of the data is going to be missing in the `orders_log.product_sales_by_day` table. 

I'm not sure what exactly is causing this. Let me know if you have any ideas. Thanks!

**How to reproduce**
* Which ClickHouse server version to use
ClickHouse server version 20.10.3.30 (official build).

* `CREATE TABLE` statements for all tables involved
```
CREATE TABLE orders_log.product_sales_by_day
(
    `store_id` UInt32,
    `product_id` UInt32,
    `total` Float64,
    `order_date` Date
)
ENGINE = AggregatingMergeTree
PARTITION BY toYYYYMM(order_date)
ORDER BY (store_id, product_id, order_date)
SETTINGS index_granularity = 8192

CREATE MATERIALIZED VIEW orders_log.product_sales_by_day_mv TO orders_log.product_sales_by_day
(
    `store_id` UInt32,
    `product_id` UInt32,
    `total` Float64,
    `order_date` Date
) AS
SELECT
    orders.store_id,
    items.product_id,
    SUM(items.product_price * items.status_quantity) AS total,
    toDate(orders.order_date, 'America/Vancouver') AS order_date
FROM orders_log.orders
INNER JOIN orders_log.items ON orders.uuid = items.order_uuid
GROUP BY
    store_id,
    product_id,
    order_date


INSERT INTO orders_log.product_sales_by_day_mv SELECT 
  store_id, 
  items.product_id AS product_id, 
  SUM(items.product_price * items.status_quantity) AS total, 
  toDate(orders.order_date, 'America/Vancouver') AS order_date 
FROM orders_log.items  
INNER JOIN orders_log.orders ON orders.uuid = items.order_uuid 
GROUP BY store_id, product_id, order_date
```

**Comment by den-crane** [comment]
1. AggregatingMergeTree require some AggregateFunction or SimpleAggregateFunction. You need to use sumState / mergeState https://gist.github.com/den-crane/6eff375752a236a456e1b3dc2ca7db62  or https://gist.github.com/den-crane/e326eef3b6ee6ccd5ca0df1dc1849a05
  in your case `total` is calculated by ANY()
2. Or you can use SummingMergeTree. SummingMergeTree calculates sums automatically for all columns not included in `ORDER BY (store_id, product_id, order_date)`. `total` -- in you case.
3. `orders_log.orders INNER JOIN orders_log.items` try to avoid joins in MATERIALIZED VIEW, it's bad for performance.
https://den-crane.github.io/Everything_you_should_know_about_materialized_views_commented.pdf
https://youtu.be/ckChUkC3Pns?t=9326

**Comment by dmftaras** [comment]
@den-crane thanks!
