### ISSUE TITLE
clickhouse连接mycat

### ISSUE THREAD

**Issue by SDUERLLei** [ClickHouse/ClickHouse#19295]
clickhouse中连接mycat查询提示table doesn`t exist

**Comment by mathfool** [comment]
请提供些详细信息。please provide more details.

**Comment by SDUERLLei** [comment]
我用的是mycat的分库分表，然后想要测试同步mycat的数据到clickhouse，使用的命令是：insert into table select * from mysql('ip:8066','db','table','user','password'),其中8066为mycat端口，然后同一条命令有时可以查出结果，有时则报表不存在

**Comment by alexey-milovidov** [comment]
It may be related to the incomplete implementation of INFORMATION_SCHEMA database.
If `mycat` does not work with ClickHouse, I recommend using another tool.
