### ISSUE TITLE
The problem of result returned by Clickhouse JDBC

### ISSUE THREAD

**Issue by github24518** [ClickHouse/ClickHouse#19294]
BUG:  clickhouse-jdbc
In multi table relational query, the fields returned by Clickhouse JDBC are t1.xx1, t1.xx2, t2.xx1, t2.xxx2 with table alias, which is not convenient for entity object mapping!

**Comment by alexey-milovidov** [comment]
You should create an issue in the https://github.com/ClickHouse/clickhouse-jdbc repository.

**Comment by alexey-milovidov** [comment]
CC @zhicwu

**Comment by zhicwu** [comment]
@alexey-milovidov, I tent to agree that this is inconvenient. I think it's not limited to JDBC driver as I got same results using clickhouse-client. If there's no plan to change the behavior from server-side, I'll consider a new setting in JDBC driver to optionally remove the prefix.

```sql
select * from (select 1 as a, 2 as b) t1 inner join (select 1 as a, 2 as b) t2 on t1.a = t2.a inner join (select 1 as a, 2 as b) t3 on t2.a = t3.a
```

Results:
```
┌─t1.a─┬─t1.b─┬─t2.a─┬─t2.b─┬─t3.a─┬─t3.b─┐
│    1 │    2 │    1 │    2 │    1 │    2 │
└──────┴──────┴──────┴──────┴──────┴──────┘
```

**Comment by den-crane** [comment]
@zhicwu it's users responsibility to name columns. `select t1.b as t1_b  from`

> I'll consider a new setting in JDBC driver to optionally remove the prefix.

Please don't. You will break the current behavior. You cannot distinguish nested columns names and user-named columns `select x as "x.a"`

**Comment by zhicwu** [comment]
> it's users responsibility to name columns.

Right but the default behavior is sort of "unexpected"(compare to MySQL/PostgreSQL etc.), and it's tedious to create alias for each of the column just for removing the prefix...

> Please don't. You will break the current behavior. You cannot distinguish nested columns names and user-named columns `select x as "x.a"`

I see your point. By default, prefix will not be removed until we explicitly set `removeAlias=true` in connection setting or query parameter.

**Comment by den-crane** [comment]
>Right but the default behavior is sort of "unexpected"(compare to MySQL/PostgreSQL etc.)

Right, but this clickhouse-JDBC behavior is compatible with clickhouse-client / clickhouse-cpp / clickhouse-go / clickhouse-python / clickhouse-odbc.

**Comment by keu** [comment]
> > Right but the default behavior is sort of "unexpected"(compare to MySQL/PostgreSQL etc.)
> 
> Right, but this clickhouse-JDBC behavior is compatible with clickhouse-client / clickhouse-cpp / clickhouse-go / clickhouse-python / clickhouse-odbc.

which is again super inconvenient, and not compatible with previous version of clickhouse-client / clickhouse-cpp / clickhouse-go / clickhouse-python / clickhouse-odbc.

Consider the following usage:
```sql
create table `tmp`.`table`
engine = MergeTree
order by (st.field)  -- has to use st now
as (
 select st.* from some_table as st
);

select * from tmp.table where st.field = 0;
```

**Comment by github24518** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by keu** [comment]
Even more, this behavior breaks dbt integration in my case.
The following
```sql
{{
    config(
      order_by='(someid)', engine='MergeTree()', materialized='table'
    )
}}
with data as (
  select m.profile as someid,
  li.awards,
  li.certifications
  from {{ ref('data_source') }} li
  where li.profile != ''
)
select * from data

```
gives this error:
```
Elements 'li.awards' and 'li.certifications' of Nested data structure 'li' (Array columns) have different array sizes. (SIZES_OF_ARRAYS_DONT_MATCH)
```
when this one doesn't
```sql
{{
    config(
      order_by='(someid)', engine='MergeTree()', materialized='table'
    )
}}
with data as (
  select m.profile as someid,
  li.awards as awards,
  li.certifications as certifications
  from {{ ref('data_source') }} li
  where li.profile != ''
)
select * from data
```
