### ISSUE TITLE
ReplicatedMergeTree: Clean inactive parts code is fragile

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#19306]
See `clearOldPartsAndRemoveFromZK`:

https://github.com/ClickHouse/ClickHouse/blob/636049f4657f0943875199cb983eee6d168aaaf8/src/Storages/StorageReplicatedMergeTree.cpp#L5301-L5323

It collects the list of all inactive parts and try to remove all of them at once - first from zookeeper, then from filesystem. 

Some scenarios (most typical example - mutations on tables with lot of parts) can create enormous number of inactive parts, which are removed slowly. And while they are removed a lot of bad things can happen:
1) hard restart - if data were already removed from zookeeper but not from filesystem:
- it can prevent clickhouse from restarting (local set of parts is too diffent from zookeeper)
- even in clickhouse will start all those parts will be moved to detached as 'unexpected' and may take a lot of disk space. 
2) new mutations creating even more inactive parts - may end up with situations when millions of inactive parts were collected, making the system unusable. 

Proposal:
1) change clearOldPartsAndRemoveFromZK to process old parts in bulks (bulk size can be configured via mergetree settings, i guess nice default is about 1000 parts). Every bulk shoud be first removed from zookeeper then from filesystem (as now, but it will not hang for lot of time on filesystem or zookeeper operation and zookeeper and filesystem will mostly be in sync). Maybe introduce and option do process every individual bulk in parallel by several threads simultaniously.
2) Introduce 'too many inactive parts' exception (configurable via merge_tree_setttings similar to parts_to_throw_insert  or to max_parts_in_total), to prevent collecting too many inactive parts (i think that smth about 50K inactive parts in system is something you should worry).

**Comment by alexey-milovidov** [comment]
The setting `inactive_parts_to_throw_insert` has been added.
