### ISSUE TITLE
how to get json string

### ISSUE THREAD

**Issue by vegastar002** [ClickHouse/ClickHouse#19304]
SELECT *
FROM 
(
    WITH
        [1, 2, 3] AS d1,
        ['a', 'e', 'f'] AS t1,
        ['x', 'y', 'z'] AS t2
    SELECT
        d1,
        t1,
        t2
)
ARRAY JOIN
    d1,
    t1,
    t2
FORMAT JSON

Query id: 0077ae25-56b7-49da-b787-66a2b4ffdfdc

{
	"meta":
	[
		{
			"name": "d1",
			"type": "UInt8"
		},
		{
			"name": "t1",
			"type": "String"
		},
		{
			"name": "t2",
			"type": "String"
		}
	],
	"data":
	[
		{
			"d1": 1,
			"t1": "a",
			"t2": "x"
		},
		{
			"d1": 2,
			"t1": "e",
			"t2": "y"
		},
		{
			"d1": 3,
			"t1": "f",
			"t2": "z"
		}                                                                                                                                      
	],
	"rows": 3,
	"statistics":
	{
		"elapsed": 0.000619288,
		"rows_read": 1,
		"bytes_read": 1
	}
}

3 rows in set. Elapsed: 0.002 sec. 

I only want get the string :

	"data":
	[
		{
			"d1": 1,
			"t1": "a",
			"t2": "x"
		},
		{
			"d1": 2,
			"t1": "e",
			"t2": "y"
		},
		{
			"d1": 3,
			"t1": "f",
			"t2": "z"
		}                                                                                                                                      
	]

how to do ?

**Comment by e-mars** [comment]
hi @vegastar002 ,

if you need the field and data names you can do something like this:
```
clickhouse-client --host chnode21.marsnet.local --user ch_admin --password password --database db1 --query "Select * from table1 format JSONEachRow"
```
output:
```
{"id":"1","column1":"abc"}
{"id":"2","column1":"def"}
{"id":"3","column1":"ghi"}
```
if all you need are the values, then you can use something like this:
```
clickhouse-client --host chnode21.marsnet.local --user ch_admin --password password --database db1 --query "Select * from table1 format JSONCompactEachRow"
["1", "abc"]
["2", "def"]
["3", "ghi"]
```

see the following for additional data return formats:
https://clickhouse.com/docs/en/interfaces/formats/#json

thanks.
