### ISSUE TITLE
Azure Blob table function and storage engine

### ISSUE THREAD

**Issue by baibaichen** [ClickHouse/ClickHouse#19307]
To allow import and export to Azure Blob  compatible storage.

**Use case**
Use case and implementation is mostly like file table function and `File` storage:
https://clickhouse.yandex/docs/en/query_language/table_functions/file/

**Describe the solution you'd like**
Similar with S3, use https://github.com/Azure/azure-storage-cpp to access files on blob

**Describe alternatives you've considered**
Currently, we use URL engine to get data from blob, but it failed to use [MKI authenticate](https://techcommunity.microsoft.com/t5/azure-database-support-blog/using-managed-service-identity-msi-to-authenticate-on-azure-sql/ba-p/1288248) which is used by [Azure Marketplace ](https://azure.microsoft.com/en-us/marketplace/)

**Additional context**
No

**Comment by shaofengshi** [comment]
+1 This is a nice feature for running Clickhouse on Azure.

**Comment by ucasfl** [comment]
Implemented in #50604.
