### ISSUE TITLE
support "case x when a then b" express

### ISSUE THREAD

**Issue by l1t1** [ClickHouse/ClickHouse#19308]
translate

case x when a then b when c then d end

to

case when x=a then b when x=c then d end

now the 1st express always return null
eg.
```sql
select number n,case n when 0 then 0 when 1 then 6 when 2 then 30 end lo ,
case n when 0 then 5 when 1 then 29 when 2 then 99 end hi from system.numbers limit 3
n	lo	hi
0	ᴺᵁᴸᴸ	ᴺᵁᴸᴸ
1	ᴺᵁᴸᴸ	ᴺᵁᴸᴸ
2	ᴺᵁᴸᴸ	ᴺᵁᴸᴸ
```

**Comment by alexey-milovidov** [comment]
Duplicate https://github.com/ClickHouse/ClickHouse/issues/9596.

**Comment by alexey-milovidov** [comment]
Duplicate https://github.com/ClickHouse/ClickHouse/issues/11085.
