### ISSUE TITLE
Typo in replication documentation

### ISSUE THREAD

**Issue by fsergii** [ClickHouse/ClickHouse#19321]
On page
https://clickhouse.tech/docs/ru/engines/table-engines/mergetree-family/replication/

there is example:
<default_replica_path>/clickhouse/tables/{shard}/{database}/{table}</default_replica_path>
<default_replica_name>{replica}</default_replica_path>

Closing tag different from the opening tag

I think there should be:
<default_replica_path>/clickhouse/tables/{shard}/{database}/{table}</default_replica_path>
<default_replica_name>{replica}</default_replica_name>

**Comment by bharatnc** [comment]
Fixed via https://github.com/ClickHouse/ClickHouse/pull/19090. Looks correct now.
