### ISSUE TITLE
Block structure mismatch in PipelineExecuting stream: different values of constants, actual: '1610284101.175', expected: '1610284101.174''.

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#19327]
**Describe the bug**
Found by sql_fuzzy
https://clickhouse-test-reports.s3.yandex.net/0/80c937b64c8e0caaf9da353d83920ae9450c02e6/functional_stateless_tests_(debug).html

**Comment by KochetovNicolai** [comment]
Cannot reproduce this error for query from fuzz tests.
I expect this will be fixed by #19316
