### ISSUE TITLE
Why is de-duplication faster than reading data directly?

### ISSUE THREAD

**Issue by nnsgmsone** [ClickHouse/ClickHouse#19349]
I  created a table with the following command:
```
CREATE TABLE default.people
(
    `orderId` String,
    `uid` String,
    `price` Float32,
    `city` String
)
ENGINE = ReplacingMergeTree()
ORDER BY orderId
SETTINGS index_granularity = 8192 │
```
then i run two sql:

```
select city from people; 0.98s
select distinct(city) from people; 0.342s
```
My understanding is that de-duplication should read the data first and then de-duplicate it by sorting or hashing, which in theory should be slower than reading the data directly. But the phenomenon is the opposite, is this using indexes?

**Comment by qoega** [comment]
Have you tried to run your queries several times? It can be explained for example with data placed in memory by fs after first data read. 
And what is the size of your table? Deduplicated result can be much smaller than complete result.

**Comment by nnsgmsone** [comment]
I have executed the sql after clearing the page cache and restarting the service。Data volume of 100 million rows (3GB)

**Comment by nnsgmsone** [comment]
Also I use the client to execute the sql, my understanding client will automatically add the limit, so the output should not be the reason for the performance gap.

**Comment by qoega** [comment]
> Also I use the client to execute the sql, my understanding client will automatically add the limit, so the output should not be the reason for the performance gap.

You can add limit manually and check that this is not an issue.

Additionaly there is additional information in query log. 
https://clickhouse.tech/docs/en/operations/system-tables/query_log/
You can check PerfEvents for your query where you can check what is different in your query.
https://clickhouse.tech/docs/en/operations/system-tables/events/#system_tables-events

@akuzm It is a nice example for OpenTelemetry to see what happens in ClickHouse without reading logs etc.

**Comment by yingfeng** [comment]
This is not an issue, it's a question on why such queries have different performance: 

`
select city from people; 0.98s

select avg(price) from people group by city; 0.34s

select distinct(city) from people; 0.34s
`

According to the general understanding, the column `city` should be read at first, then inserted into hashtable to provide `group by` or `distinct` operation. The first SQL does nothing more than reading the content of that column, while the latter two have extra opeartions of inserting into the hashtable. 

Perhaps the implementation of the hashtable could automatically increase the IO parallelism? The mechanism here is interesting...

**Comment by nnsgmsone** [comment]
[server.log](https://github.com/ClickHouse/ClickHouse/files/5854141/server.log)
this is the log。

**Comment by nnsgmsone** [comment]
The time gap can be obtained from the logs and the client has no relationship.

**Comment by nnsgmsone** [comment]
@alexey-milovidov Can you help me solve my confusion?

**Comment by alexey-milovidov** [comment]
Hypothesis: the query without deduplication returns more records and it takes more time to transfer the result.

**Comment by nnsgmsone** [comment]
```
executeQuery: Read 100000000 rows, 1.40 GiB in 0.235573548 sec., 424495877 rows/sec., 5.93 GiB/sec.
executeQuery: Read 100000000 rows, 1.40 GiB in 0.887121595 sec., 112724118 rows/sec., 1.57 GiB/sec.
```
Do you mean that this time also includes the transmission time, if so, it is fine.
@alexey-milovidov

**Comment by nnsgmsone** [comment]
Thanks, I understand

**Comment by alexey-milovidov** [comment]
> Do you mean that this time also includes the transmission time, if so, it is fine.

Yes.
