### ISSUE TITLE
Why clickhouse does not support transaction?

### ISSUE THREAD

**Issue by godliness** [ClickHouse/ClickHouse#19352]
Clickhouse does not support transaction will lead to duplicated data when we using spark to load data into clickhouse(spark task failed and retry will lead to this).

As i know, the reason includes:
1. Clickhouse is a kind of OLAP database which is just for analysis and query
2. Clickhouse delete and update operation will takes a lot of time and expensive

Except above reasons, do we have any other reasons in technically, if we support transaction which would be a very helpful feature for loading data into clickhouse.

Is clickhouse using LSM-Tree which is only support append operation or something else data structures is the key reason?
And do we have any roadmap to support transaction?

@alexey-milovidov

**Comment by alexey-milovidov** [comment]
There is no technical reasons to not support transactions for single large INSERT into ReplicatedMergeTree table. It is in our roadmap and @tavplubix will implement it.

We have plans to do the following:
- large INSERT in single transaction;
- transactional INSERT into table and all dependent materialized views;
- allow to acquire a snaphot (begin transaction) and use it for multiple SELECT queries.

Step 1 is to allow it for ReplicatedMergeTree.
Transactional semantics for Distributed tables (with multiple shards) is more hard.
Full featured semantics of ANSI SQL transactions is not even in roadmap.

**Comment by godliness** [comment]
@alexey-milovidov very appreciate for your detail response!

@tavplubix do you have any proposal document about this plan or anything else useful doc to understand this feature deeply? thanks in advance!

**Comment by godliness** [comment]
found the roadmap list: https://github.com/ClickHouse/ClickHouse/issues/17623
