### ISSUE TITLE
groupArrayArray | DB::Exception: Too large array size: while receiving packet

### ISSUE THREAD

**Issue by hatrena** [ClickHouse/ClickHouse#19370]
Hi,

I have a table that has `arr` as `Array(LowCardinality(String))`. Now I am using syntax in my query to result in aggregated info for `arr` like:

`arrayReduce('sumMap', [groupArrayArray(arr) AS flat_arr], [arrayResize(CAST([], 'Array(UInt64)'), length(flat_arr), toUInt64(1))]) AS arr_stats` 

So the expected result would be something like:
`A,B,1,3`

This query will result in `DB::Exception: Too large array size: while receiving packet` error if I have much data as `groupArrayArray` is flatting the `arr`

Is there any other way to get the result I need?

**Comment by hatrena** [comment]
Hi, 

I wanted to know if you could have any updates on this?

**Comment by alexey-milovidov** [comment]
This is an internal safety threshold that is protecting from excessive memory usage.
You can rewrite the query in a way that will return multiple smaller arrays instead of one larger array.
