### ISSUE TITLE
UBSan report in lcm/gcd.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#19398]
**Describe the bug**
https://clickhouse-test-reports.s3.yandex.net/19385/117708abc616a777014566cca6f1a00a3dae4109/fuzzer_ubsan/server.log

**Comment by ucasFL** [comment]
related #19276, #19329, #19302

**Comment by alexey-milovidov** [comment]
Fixed in #19532.
