### ISSUE TITLE
MaterializeMySQL synchronization problem

### ISSUE THREAD

**Issue by leoones** [ClickHouse/ClickHouse#19399]
MySQL5.7    to   Clickhouse 20.12 
 
Clickhouse Sync configuration:

1， CREATE DATABASE db_product ENGINE = MaterializeMySQL('192.168.5.168:3306', 'db_product', 'user', 'user123');

2 ，Data synchronization completed；

3， Execute in MySQL SQL：
          create table   test.order_bak  like  test.order;

clickhouse error :
      DB::Exception: Cannot convert create like statement to ClickHouse SQL (version 20.12.5.14 (official build))

problem:
     Why does the execution under the test database affect the synchronization of the db_product database? 
     Doesn't Clickhouse filter synchronously at the database level? 
     How can I solve this problem?

**Comment by alexey-milovidov** [comment]
MaterializeMySQL is not under active development and remains as experimental, mostly abandoned feature.
