### ISSUE TITLE
Best way to select last/first n rows for each group

### ISSUE THREAD

**Issue by alex-klepa** [ClickHouse/ClickHouse#19392]
Hi,

First I want to say thank you to all developers and contributors for this killer product, I start evaluating it for my project and I love it!

I have a query optimization question, let's say I have following table:

```sql
CREATE TABLE items (
  time DateTime,
  group_id UInt16,
  value UInt32()
) ENGINE = MergeTree()
PARTITION BY toYYYYMM(time)
ORDER BY (group_id, time)
```

And I need to select last n rows for each group, the first most obvious query is this(using CH **LIMIT n BY**), but it's not optimal and can be slow on large data sets:

```sql
SELECT
  group_id,
  groupArray(time)[1] as time,
  groupArray(value), -- << Here I can calculate moving avergaes, rolling sums, etc.
FROM ( 
  SELECT * FROM items ORDER BY time desc LIMIT 100 BY group_id
)
GROUP BY group_id;
```

Is there a way to optimize this query or different way to do it (different table(s) structure)?

**Comment by den-crane** [comment]
You can pre-aggregate and find the first 1 and the last 1.


Connected to ClickHouse server version 21.1.1 revision 54443.

```
CREATE TABLE items (
  time DateTime,
  group_id UInt16,
  value UInt32()
) ENGINE = MergeTree()
PARTITION BY toYYYYMM(time)
ORDER BY (group_id, time);

insert into items select toDateTime('2020-01-01 00:00:00') + number/100, number%111111, 0 
from numbers(1000000000);

SELECT
  group_id,
  groupArray(time)[1] as time,
  groupArray(value)
FROM ( 
  SELECT * FROM items ORDER BY time desc LIMIT 100 BY group_id
)
GROUP BY group_id format Null; 

0 rows in set. Elapsed: 47.944 sec. Processed 1.00 billion rows, 10.00 GB (20.86 million rows/s., 208.58 MB/s.)


SELECT
  group_id,
  groupArray(time)[1] as time,
  groupArray(value)
FROM ( 
  SELECT * FROM items ORDER BY group_id desc, time desc LIMIT 100 BY group_id
)
GROUP BY group_id format Null

0 rows in set. Elapsed: 30.140 sec. Processed 1.99 billion rows, 19.94 GB (66.14 million rows/s., 661.41 MB/s.)


set optimize_aggregators_of_group_by_keys=1;

SELECT　  group_id,　  ((arrayReverseSort( x-> x.1, groupArray((time,value))) as x).1)[1],　  x.2　
FROM items　GROUP BY group_id　limit 100;

100 rows in set. Elapsed: 27.759 sec. Processed 1.00 billion rows, 10.00 GB (36.02 million rows/s., 360.24 MB/s.)

```

**Comment by alex-klepa** [comment]
Cool, I can reference  values within SELECT clause in CH. 

But still this part `SELECT * FROM items ORDER BY group_id desc, time desc LIMIT 100 BY group_id` will scan whole table regardless the LIMIT, the bigger dataset the slower it will be.

**Comment by alexey-milovidov** [comment]
It is the most optimal way so far, no better way is known.

**Comment by sweihub** [comment]
Same issue, select last N records will cause whole table scanning...

![image](https://github.com/ClickHouse/ClickHouse/assets/5334841/a290aa24-09cb-4f03-adaf-eb46cf8ccd7a)
