### ISSUE TITLE
uniqExact works unexpectedly

### ISSUE THREAD

**Issue by Mengde-Cao** [ClickHouse/ClickHouse#19402]
there is a query like:
```
select uniqExact(id) from log;
```
when the query is executed in clickhouse-client for the first time，it returns:
```
┌─uniqExact(id)─┐
 │ 670515                     │
└────────┘

1 rows in set. Elapsed: 13.837 sec. Processed 61.61 million rows, 5.78 GB (4.45 million rows/s., 418.00 MB/s.)
```
and then execute query again, it returns:
```
┌─uniqExact(id)─┐
│               696935      │
└────────┘

1 rows in set. Elapsed: 1.764 sec. Processed 64.08 million rows, 6.02 GB (36.33 million rows/s., 3.41 GB/s.)
```

my table is:
```
CREATE TABLE log(
   request_time DateTime,
   id String
) ENGINE = MergeTree()
ORDER BY request_time
PARTITION BY formatDateTime(request_time, '%Y%m%d_%H');
```

there is no merging or inserting on the table ```log```，i have no idea why the first query ```Processed 61.61 million rows, 5.78 GB``` and the second ```Processed 64.08 million rows, 6.02 GB```

**Comment by taiyang-li** [comment]
Maybe data is written into your table `log` in realtime?

**Comment by Mengde-Cao** [comment]
> Maybe data is written into your table `log` in realtime?

I'm sure the data is static and all inserting and merging works are complete. If I change the ```uniqExact``` to ```count```, the result will keep same. It appears like that query return in advance since a limitation, but I have no idea what limitation is triggered.

**Comment by den-crane** [comment]
What CH version do you use?

try set read_backoff_min_latency_ms=0

duplicate for #18137 ?

**Comment by Mengde-Cao** [comment]
> What CH version do you use?
> 
> try set read_backoff_min_latency_ms=0
> 
> duplicate for #18137 ?

thx!  it seems to be fixed.
