### ISSUE TITLE
Exception: Memory limit (for query) exceeded

### ISSUE THREAD

**Issue by JunjianS** [ClickHouse/ClickHouse#19403]
ClickHouse server version : 20.10.2.20
cluster with 4 node, 2master and 2 replica, 
there are about 400 million recordes in 4 tables.

I'm testing ClickHouse to see if it's a fit for our data.

I found that performing a GROUP BY with query on local table,result is ok, but put the same query on distributed table(records is same),  results in Memory limit (for query) exceeded, even though max_bytes_before_external_group_by  is set.

set max_memory_usage=30000000000
set max_bytes_before_external_group_by=15000000000

could you please give me some advice ？ thank you very much.

**Comment by taiyang-li** [comment]
Query distributed table consumes more memory then query local table. You can also try `max_bytes_before_external_sort` if your query contains `order by`.

**Comment by den-crane** [comment]
How much memory do you have?

Try to set `set max_bytes_before_external_group_by=10000000000`

**Comment by den-crane** [comment]
20.10.2 is obsolete. Upgrade to 20.10.7.4

**Comment by JunjianS** [comment]
> How much memory do you have?
> 
> Try to set `set max_bytes_before_external_group_by=10000000000`

thanks, each node have 32G memory, i will try upgrade it

**Comment by JunjianS** [comment]
> Query distributed table consumes more memory then query local table. You can also try `max_bytes_before_external_sort` if your query contains `order by`.

thanks, no order statement

**Comment by den-crane** [comment]
try `set aggregation_memory_efficient_merge_threads=2`

**Comment by alexey-milovidov** [comment]
Also need to enable `distributed_aggregation_memory_efficient` first. It's not enabled by default.

**Comment by JunjianS** [comment]
> aggregation_memory_efficient_merge_threads

> Also need to enable `distributed_aggregation_memory_efficient` first. It's not enabled by default.

thanks ，i set below settings,
 
set distributed_aggregation_memory_efficient = 1;
set aggregation_memory_efficient_merge_threads=2;
            
query result in exception unfortunately, but the rows processed has increased
↑ Progress: 406.23 million rows, 29.07 GB (4.55 million rows/s., 325.78 MB/s.) ███████████████████████████████████████████████████████████████████████████████████████▎       91%
Received exception from server (version 20.10.2):
Code: 241. DB::Exception: Received from localhost:9000. DB::Exception: Memory limit (total) exceeded: would use 29.98 GiB (attempt to allocate chunk of 6440289048 bytes), maximum: 28.13 GiB: While executing CreatingSetsTransform.

**Comment by JunjianS** [comment]
i updated below settings, the query result came out.@_@
set max_memory_usage=300000000000
set max_bytes_before_external_group_by=15000000000 #(this value is max_memory_usage/2 before, is max_memory_usage/20 now )
set distributed_aggregation_memory_efficient = 1;
