### ISSUE TITLE
S3 - Allow setting x-amz-server-side-encryption-customer-(key/md5)

### ISSUE THREAD

**Issue by joshuataylor** [ClickHouse/ClickHouse#19428]
**Use case**
With S3, you have to send the header `x-amz-server-side-encryption-customer-key` and `x-amz-server-side-encryption-customer-key-md5` if the resource is server side encrypted.

https://docs.aws.amazon.com/AmazonS3/latest/dev/ServerSideEncryptionCustomerKeysSSEUsingRESTAPI.html
https://docs.aws.amazon.com/AmazonS3/latest/dev/ServerSideEncryptionCustomerKeys.html

**Describe the solution you'd like**
Ability to set this in the query.

**Comment by alex-zaitsev** [comment]
@excitoon ^

**Comment by joshuataylor** [comment]
This is awesome!

I'm going to look into adding it as a table function, would be awesome to pass this through to the s3 table function (https://clickhouse.tech/docs/en/sql-reference/table-functions/s3/).

My usecase: I get a list of S3 URLs that have a presigned key and I use clickhouse to convert these. It works great when I download them then process them, but I want to skip this step and just use Clickhouse.
