### ISSUE TITLE
GROUPING aggregate function

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#19426]
**Use case**
Have ability to distinguish rows being produced by GROUP BY and ROLLUP / CUBE.

**Describe the solution you'd like**
Just like in oracle or other databases.
https://oracle-base.com/articles/misc/rollup-cube-grouping-functions-and-grouping-sets

**Describe alternatives you've considered**
Using nulls as suggested in https://github.com/ClickHouse/ClickHouse/issues/8091#issuecomment-563725443, but it's not always applicable.

**Additional context**
https://github.com/ClickHouse/ClickHouse/issues/8091

**Comment by l1t1** [comment]
GROUP BY GROUPING SETS also needed

**Comment by alexey-milovidov** [comment]
It's being implemented by @MaxTheHuman (just started).

**Comment by filimonov** [comment]
wip pr https://github.com/ClickHouse/ClickHouse/pull/24172
