### ISSUE TITLE
AddressSanitizer: heap-buffer-overflow on address in DateLUT

### ISSUE THREAD

**Issue by alesapin** [ClickHouse/ClickHouse#19441]
query, report https://gist.github.com/alesapin/c91d9ffd65471c4d8b595219a26a601a.
Full report
https://clickhouse-test-reports.s3.yandex.net/19412/cc2788af881c96701076b366259bc99525d926b1/fuzzer_asan/report.html#fail1

**Comment by alexey-milovidov** [comment]
True bug, it may cause crash.
