### ISSUE TITLE
Performance Issue with UNION ALL in View

### ISSUE THREAD

**Issue by bytecodedan** [ClickHouse/ClickHouse#1946]
My team has been experiencing an issue with Clickhouse (ver 1.1.54236-4) views where we have several queries joined by UNION ALL's to the point where the system locks up and needs to be restarted manually.  We have tried protecting the system by setting the limit of concurrent queries to 30 and yet it still comes to a halt and we notice the following exception.

"DB::Exception: Too much simultaneous queries."

In addition, some of our views query other views simultaneously with UNION ALL as well.

System specs: 

- CPU: Intel Xeon CPU E5-2697 v2 @ 2.70GHz (x4)
- Memory: 32GB

**Comment by blinkov** [comment]
@bytecodedan could you provide a way to reproduce this?

**Comment by filimonov** [comment]
Very old issue, a lot of changes happened in the meantime.

If you will face it on newer clickhouse versions - please feel free to open a new one.
