### ISSUE TITLE
Destructor warnings in the new code lead to the build failures

### ISSUE THREAD

**Issue by leshikus** [ClickHouse/ClickHouse#19494]
**Operating system**
Debian-like linux (Astra Linux 2.12.41)

**Cmake version**
3.16.3-1~bpo9+1

**Ninja version**
1.7.2-1

**Compiler name and version**
clang 1:9.0.1-14 + a few patches, recompiled to support gold plugins

**Full cmake and/or ninja output**
src/Parsers/New/AST/INode.h:19:17: error: definition of implicit copy constructor for 'INode' is deprecated because it has a user-declared destructor [-Werror,-Wdeprecated]
        virtual ~INode() = default;
                ^

I also get delete-non-abstract-non-virtual-dtor fatal warnings at the same module.

**Workaround**
Adding the following to cmake/warnings.cmake helped:
no_warning(deprecated)
no_warning(delete-non-abstract-non-virtual-dtor)

**Comment by alexey-milovidov** [comment]
Possible reason is the usage of old clang version (9.0). We are using clang 11 in CI and for releases.
Nevertheless, you can disable the problematic code inside `src/Parsers/New/` (it is optional) as a workaround.

**Comment by alexey-milovidov** [comment]
@abyss7 Nothing was done, I will close this.

**Comment by alexey-milovidov** [comment]
At the meantime, clang-9 becomes even more obsolete.
