### ISSUE TITLE
ZLIB_INCLUDE_DIRS is missed for cassandra_static target

### ISSUE THREAD

**Issue by leshikus** [ClickHouse/ClickHouse#19511]
**Operating system**
Debian-like linux (Astra Linux 2.12.41)

**Cmake version**
3.16.3-1~bpo9+1

**Ninja version**
1.7.2-1

**Compiler name and version**
clang 1:9.0.1-14 + a few patches, recompiled to support gold plugins

**Full cmake and/or ninja output**
minizip sources are used instead of a static library

FAILED: contrib/cassandra/src/CMakeFiles/cassandra_static.dir/cloud_secure_connection_config.cpp.o 
/usr/lib/llvm-9/bin/clang++  -DCASS_STATIC -DSTD_EXCEPTION_HAS_STACK_TRACE=1 -I../contrib/sentry-native/include -I../contrib/cassandra/src/third_party/curl -I../contrib/cassandra/src/third_party/hdr_histogram -I../contrib/cassandra/src/third_party/http-parser -I../contrib/cassandra/src/third_party/minizip -I../contrib/cassandra/src/third_party/mt19937_64 -I../contrib/cassandra/src/third_party/rapidjson/rapidjson -I../contrib/cassandra/src/third_party/sparsehash/src -I../contrib/cassandra/include -I../contrib/cassandra/src -I../contrib/libuv/include -isystem ../contrib/boringssl/include -isystem ../contrib/libcxx/include -isystem ../contrib/libcxxabi/include -isystem ../contrib/libunwind/include -isystem ../contrib/libc-headers/x86_64-linux-gnu -isystem ../contrib/libc-headers -g -O2 -fdebug-prefix-map=/opt/build/clickhouse-21.1.2.1=. -specs=/usr/share/dpkg/no-pie-compile.specs -Wdate-time -fdiagnostics-color=always -std=gnu++2a -fsized-deallocation  -gdwarf-aranges -pipe -msse4.1 -msse4.2 -mpopcnt   -Wall -Wno-unused-command-line-argument  -fdiagnostics-absolute-paths -fexperimental-new-pass-manager -Werror -w -pthread -std=c++11 -Wall -pedantic -Wextra -Wno-long-long -Wno-unused-parameter -Wno-variadic-macros -Wno-zero-length-array -Wno-unused-local-typedef -Wno-unknown-warning-option -Wconversion -Wno-sign-conversion -Wno-shorten-64-to-32 -Wno-undefined-var-template -Werror -O2 -g -DNDEBUG -O3  -flto=thin -fno-pie   -D OS_LINUX -nostdinc++ -MD -MT contrib/cassandra/src/CMakeFiles/cassandra_static.dir/cloud_secure_connection_config.cpp.o -MF contrib/cassandra/src/CMakeFiles/cassandra_static.dir/cloud_secure_connection_config.cpp.o.d -o contrib/cassandra/src/CMakeFiles/cassandra_static.dir/cloud_secure_connection_config.cpp.o -c ../contrib/cassandra/src/cloud_secure_connection_config.cpp
In file included from ../contrib/cassandra/src/cloud_secure_connection_config.cpp:43:
/opt/build/clickhouse-21.1.2.1/contrib/cassandra/src/third_party/minizip/unzip.h:51:10: fatal error: 'zlib.h' file not found
#include "zlib.h"
         ^~~~~~~~
1 error generated.
ninja: build stopped: subcommand failed.
debian/rules:91: recipe for target 'override_dh_auto_build' failed

**Workaround**
in contrib/cassandra/src/CMakeLists.txt replace
target_include_directories(cassandra_static PRIVATE ${INCLUDE_DIRS} ${CASS_INCLUDES})
with
target_include_directories(cassandra_static PRIVATE ${INCLUDE_DIRS} ${CASS_INCLUDES} ${ZLIB_INCLUDE_DIRS})

**Comment by alexey-milovidov** [comment]
I will submit your patch.

**Comment by leshikus** [comment]
Thanks!
