### ISSUE TITLE
Data stored in store directory in version 21?

### ISSUE THREAD

**Issue by winoenix** [ClickHouse/ClickHouse#19531]
Recently I have installed a clickhouse of version 21.1.2.15. I found that the data is stored in the store directory(CLICKHOUSEPATH/store) with the name of random string, but not in the data directory as before. 

Instead, in the data directory there are some symbolic links to the data directory in the store directory. 
Is it a new feature of the new version?

When I tried to freeze the table, I found the directory with random name in the shadow directory(same as the one in store directory) but not like "/database/tablename" as before. 
It seems make the restore from the freeze file more complicated and makes no benefits.

Is there any suggestion with the backup/restore work in the new version? Thanks!

**Comment by winoenix** [comment]
It seems that the default database comes to Atomic from Ordinary?

**Comment by alexey-milovidov** [comment]
That's true. Atomic database is default from version 20.10.

It gives the following benefits: lock-free table CREATE/DROP/RENAME, allows EXCHANGE and REPLACE queries.

Drawbacks: some external tools may not be ready for data layout on filesystem.

You can also create database with ENGINE specified explicitly, e.g. `CREATE DATABASE db ENGINE = Ordinary` or change the default in users profile with `default_database_engine` setting.

**Comment by winoenix** [comment]
> That's true. Atomic database is default from version 20.10.
> 
> It gives the following benefits: lock-free table CREATE/DROP/RENAME, allows EXCHANGE and REPLACE queries.
> 
> Drawbacks: some external tools may not be ready for data layout on filesystem.
> 
> You can also create database with ENGINE specified explicitly, e.g. `CREATE DATABASE db ENGINE = Ordinary` or change the default in users profile with `default_database_engine` setting.

thank very much
