### ISSUE TITLE
 Does not take effect after modifying the configuration file

### ISSUE THREAD

**Issue by yangzan66** [ClickHouse/ClickHouse#19545]
modify the configuration file:
 vim /etc/clickhouse-server/config.xml
    <merge_tree>
        <parts_to_throw_insert>600</parts_to_throw_insert>
    </merge_tree>

but the new configuration doesn't effect:
db-clickhouse11 :) select * from system.merge_tree_settings where name like 'parts_to_throw_insert' format Vertical;

SELECT *
FROM system.merge_tree_settings
WHERE name LIKE 'parts_to_throw_insert'
FORMAT Vertical

Row 1:
──────
name:        parts_to_throw_insert
value:       300
changed:     0
description: If more than this number active parts in single partition, throw 'Too many parts ...' exception.

according to the docs: https://clickhouse.tech/docs/en/operations/configuration-files/#configuration_files 
 The server tracks changes in config files, as well as files and ZooKeeper nodes that were used when performing substitutions and overrides, and reloads the settings for users and clusters on the fly. This means that you can modify the cluster, users, and their settings without restarting the server.

but in fact, it doesn't,  why?

thank you!

**Comment by alexey-milovidov** [comment]
It does not update without server restart as most of the configuration chenges.
Only a few config changes can update without restart.

**Comment by alexey-milovidov** [comment]
Moreover, the default settings specified in config.xml are applied and saved in created tables.
Chaning defaults then will not change table settings - you have to do ALTER TABLE ... MODIFY SETTING.

**Comment by yangzan66** [comment]
> Moreover, the default settings specified in config.xml are applied and saved in created tables.
> Chaning defaults then will not change table settings - you have to do ALTER TABLE ... MODIFY SETTING.


thanks for your reply

how can i find one table default settings value? 
I can only find the 'Show statement settings ' by show create table command or system.tables,but cann't find the default value for one table.

**Comment by den-crane** [comment]
system.merge_tree_settings -- mergeTree tables def. settings <merge_tree> config.xml's section
https://clickhouse.tech/docs/en/operations/settings/merge-tree-settings/#merge-tree-settings

https://clickhouse.tech/docs/en/operations/settings/
system.settings -- user's session settings <profile> users.xml's section

**Comment by yangzan66** [comment]
> system.merge_tree_settings -- mergeTree tables def. settings <merge_tree> config.xml's section
> https://clickhouse.tech/docs/en/operations/settings/merge-tree-settings/#merge-tree-settings
> 
> system.settings -- user's session settings users.xml's section
> https://clickhouse.tech/docs/en/operations/settings/


how can I know which configurations in xml files will take effect without restart clickhouse , and which configuratinos must restart clickhouse to make it effect ？  I didn't find the description in the manual .  if restart the the clickhouse, it will affect the application.
thank you !

**Comment by spff** [comment]
Same question as above, I would  appreciate it if there's any doc mentioning the config reload process (without zookeeper)
