### ISSUE TITLE
how to create mergetree table by selecting from a log table?

### ISSUE THREAD

**Issue by tooptoop4** [ClickHouse/ClickHouse#19543]
step 1.
CREATE TABLE trips ( pickup_datetime DateTime, dropoff_datetime Nullable(DateTime), pulocationid Nullable(UInt8), dolocationid Nullable(UInt8), sr_flag Nullable(FixedString(1)), dispatching_base_number Nullable(String), dispatching_base_num Nullable(String) ) ENGINE = Log;

step 2.
INSERT INTO trips FORMAT CSV

step 3
**how to create new MergeTree engine table with same data as trips table? I tried below but shows syntax error related to a static create table definition with all data types listed, not a create table as select:**
CREATE TABLE trips_mergetree ENGINE = MergeTree() as select * from trips order by dropoff_datetime;

**Comment by den-crane** [comment]
MergeTree() -- requires table `order by ` section, all rows in MergeTree.
You can use a dummy order -- tuple() function.

```sql
CREATE TABLE trips_mergetree ENGINE = 
MergeTree() 
order by tuple() <<<<----
as select * from trips order by dropoff_datetime;
```

But better to use proper partitioning and proper order.

```sql
CREATE TABLE trips_mergetree ENGINE = 
MergeTree() 
partition by toYYYYMM(pickup_datetime)
order by pickup_datetime
as select * from trips order by dropoff_datetime;
```

https://clickhouse.tech/docs/en/engines/table-engines/mergetree-family/mergetree/
https://clickhouse.tech/docs/en/engines/table-engines/mergetree-family/mergetree/#selecting-the-primary-key
https://clickhouse.tech/docs/en/engines/table-engines/mergetree-family/custom-partitioning-key/
