### ISSUE TITLE
 DB::Exception: Missing columns: 'i.i_category' while processing query

### ISSUE THREAD

**Issue by Arvinzhu** [ClickHouse/ClickHouse#19546]
**ClickHouse server version ** 
ClickHouse client version 20.11.3.3 (official build).

**Describe the bug**
 DB::Exception: Missing columns: 'i.i_category' while processing query

**Expected behavior**
```
SELECT
    i.i_item_sk AS item_sk,
    i.i_category,
    i.i_current_price AS current_price
FROM item AS i
WHERE i.i_current_price > 
(
    SELECT avg(j.i_current_price)
    FROM item AS j
    WHERE j.i_category = i.i_category
)
LIMIT 100
```

**Error message and/or stacktrace** 
Received exception from server (version 20.11.3):
Code: 47. DB::Exception: Received from 172.16.200.6:9000. DB::Exception: Missing columns: 'i.i_category' while processing query: 'SELECT avg(i_current_price) FROM item AS j WHERE i_category = i.i_category', required columns: 'i_category' 'i.i_category' 'i_current_price', source columns: 'i_product_name' 'i_manager_id' 'i_container' 'i_manufact' 'i_units' 'i_manufact_id' 'i_category_id' 'i_class' 'i_formulation' 'i_class_id' 'i_brand_id' 'i_color' 'i_size' 'i_current_price' 'i_rec_start_date' 'i_item_desc' 'i_rec_end_date' 'i_item_id' 'i_wholesale_cost' 'i_category' 'i_brand' 'i_item_sk': While processing (SELECT avg(j.i_current_price) FROM item AS j WHERE j.i_category = i.i_category) AS _subquery73: While processing i_current_price > ((SELECT avg(j.i_current_price) FROM item AS j WHERE j.i_category = i.i_category) AS _subquery73).

**Additional context** 
This statement  can  run normally on mysql  server.

**Comment by tavplubix** [comment]
ClickHouse does not support correlated subqueries

**Comment by alexey-milovidov** [comment]
Duplicate #6697.
