### ISSUE TITLE
ClickHouse GROUP BY DAY(timestamp), MONTH(timestamp) or YEAR(timestamp)!?

### ISSUE THREAD

**Issue by sv3t0sl4v** [ClickHouse/ClickHouse#19557]
Greetings!

Is there a way in ClickHouse to do a GROUP BY DAY/MONTH/YEAR() with a timestamp value? Having hard time figuring it out while rewriting MySQL queries to ClickHouse. My MySQL queries looks like so...

SELECT COUNT(this), COUNT(that) FROM table WHERE something = x AND stamp BETWEEN startdate AND enddate
SELECT COUNT(this), COUNT(that) FROM table WHERE something = x AND stamp BETWEEN startdate AND enddate GROUP BY DAY(stamp)
SELECT COUNT(this), COUNT(that) FROM table WHERE something = x AND stamp BETWEEN startdate AND enddate GROUP BY MONTH(stamp)
SELECT COUNT(this), COUNT(that) FROM table WHERE something = x AND stamp BETWEEN startdate AND enddate GROUP BY YEAR(stamp)

Quite simple AND SLOW in MySQL, but I do not know how to do the aggregates in ClickHouse.

Thanks!

**Comment by filimonov** [comment]
Use: toDate(stamp) / toMonth(stamp) / toYear(stamp) 

Compatibility layer for MySQL will be added in https://github.com/ClickHouse/ClickHouse/pull/19387

**Comment by sv3t0sl4v** [comment]
Will try! Thanks!

**Comment by sv3t0sl4v** [comment]
Does not show rows with values of 0 when grouping.
