### ISSUE TITLE
DROP TABLE default.test_repl ON CLUSTER 'default' SYNC failed for Atomic

### ISSUE THREAD

**Issue by Slach** [ClickHouse/ClickHouse#19568]
**Describe the bug**
For DATABASE ENGINE Atomic (used by Default for all databases from 20.10) 
when try to `DROP TALBE replicatedmergetree table ON CLUSTER ... SYNC`, query failed after `distributed_ddl_task_timeout` seconds
`decrease `database_atomic_delay_before_drop_table_sec=1` and setup `database_atomic_wait_for_drop_and_detach_synchronously=1` for default user profile didn't help

**How to reproduce**
just look to https://gist.github.com/Slach/a7f2946a108883f6b1d5585b1b5b6b0d
```
bash -x ./reproduce.sh
```

* Which ClickHouse server version to use
Latest official docker build

* Non-default settings, if any
```
<yandex>
    <database_atomic_delay_before_drop_table_sec>1</database_atomic_delay_before_drop_table_sec>
    <profile>
        <default>
            <database_atomic_wait_for_drop_and_detach_synchronously>1</database_atomic_wait_for_drop_and_detach_synchronously>
            <distributed_ddl_task_timeout>20</distributed_ddl_task_timeout>
        </default>
    </profile>
</yandex>

```

**Expected behavior**
Successfull DROP TABLE on cluster

**Error message and/or stacktrace**
Code: 159. DB::Exception: Received from localhost:9000. DB::Exception: Watching task /clickhouse/task_queue/ddl/query-0000000001 is executing longer than distributed_ddl_task_timeout (=20) seconds. There are 2 unfinished hosts (0 of them are currently active), they are going to execute the query in background.

**Additional context**
table physically deleted, but Atomic engine doesn't return "finished" flag to Zookeeper `distributed_ddl` queue

```
docker-compose exec clickhouse-0-0-0 clickhouse-client -q "SELECT * FROM system.zookeeper WHERE path='/clickhouse/task_queue/ddl/query-0000000001/finished' FORMAT
Vertical"
```

returns empty result

**Comment by Slach** [comment]
@tavplubix thanks a lot

**Comment by WesleyBatista** [comment]
If you drop and recreate a replicated table too fast, changing it's ORDER BY, you may get:
```
code: 342, message: Existing table metadata in ZooKeeper differs in primary key. Stored in ZooKeeper: col1, col2, col3, local: col1)
```

For the record, this was working fine on version `20.9.2.20` and started failing after upgrading to `21.1.9.41`.

I could workaround it by appending **SYNC** to the drop query:
```
DROP TABLE default.my_table SYNC;
```

FYI @tavplubix

**Comment by tavplubix** [comment]
@WesleyBatista It's exactly the reason why `SYNC` modifier and `database_atomic_wait_for_drop_and_detach_synchronously` settings were added. But it's recommended to use some unique paths in ZooKeeper for each `CREATE` query, so `SYNC` will not be required.

See also #12135
