### ISSUE TITLE
Batch insertion fails when a integer column has one row starts with 0, and a following row with empty

### ISSUE THREAD

**Issue by zhangjmruc** [ClickHouse/ClickHouse#19567]
**Describe the unexpected behaviour**
When I insert the two rows separately, both can be inserted succesfully. But when I insert both together, clickhouse fails to parse.
Is this behavior expected? Or CH has any logic error in batch insertion?

create table t(a int, b String) engine=Memory();
-- batch insertion fails
insert into t values(**01**,'a'),**(,**'b');

Exception on client:
Code: 62. DB::Exception: Cannot parse expression of type Int32 here: ,'b');: data for INSERT was parsed from query

Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 21.2.1 revision 54447.

-- When inserted separately, successful.
ubuntu :) insert into t values(01,'a');

Ok.

1 rows in set. Elapsed: 0.002 sec. 

ubuntu :) insert into t values(,'b');

Ok.

1 rows in set. Elapsed: 0.002 sec. 

ubuntu :) select * from t;

┌─a─┬─b─┐
│ 1 │ a │
└───┴───┘
┌─a─┬─b─┐
│ 0 │ b │
└───┴───┘

**Comment by alexey-milovidov** [comment]
Missing value is not supported in VALUES.
Both queries are invalid.

The query `insert into t values(,'b');` succeeded despite being incorrect due to implementation specific behaviour.
