### ISSUE TITLE
Ability to control the level for different log channels separately

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#19569]
Want to have the following configuration:
1) trace log are written to file (as default)
2) error log is disabled
3) console log is enabled with NOTICE level (replaces of p.2) - the output collected by docker. 

Also I get once the request to set up error log to collect only logs with ERROR level (no WARNINGS). 

BTW: there is no documented way to send logs to stderr.

**Comment by alexey-milovidov** [comment]
> Also I get once the request to set up error log to collect only logs with ERROR level (no WARNINGS).

You should convince the client that this feature is unneeded.

**Comment by alexey-milovidov** [comment]
Warnings are as crucial as errors, and the intention to avoid writing it into log file is definitely wrong.

**Comment by filimonov** [comment]
> > Also I get once the request to set up error log to collect only logs with ERROR level (no WARNINGS).
> 
> You should convince the client that this feature is unneeded.

Our err logs are often very noisy, and polluted by some silly things like
https://github.com/ClickHouse/ClickHouse/issues/10935

That makes users who processes the logs by some commercial tools for ways to limit the amount of logs / silent them a bit. 

And that was just a side note. What is needed in that task - is the ability to stop writing err log (many people set main log level to warning and they have 2 exactly the same logs, which is silly), and ability to control the level of stdout logger.

**Comment by alexey-milovidov** [comment]
> What is needed in that task - is the ability to stop writing err log

We already have this option.

**Comment by alexey-milovidov** [comment]
> ability to control the level of stdout logger

We also have this.

**Comment by alexey-milovidov** [comment]
We also have support to set different levels for different loggers (MergeTree, DDLWorker, etc.)

**Comment by filimonov** [comment]
> > ability to control the level of stdout logger
> 
> We also have this.

You are wrong. It uses the same logging level as main log. 

https://github.com/ClickHouse/ClickHouse/blob/9f5cd35a6963cc556a51218b46b0754dcac7306a/base/loggers/Loggers.cpp#L146

**Comment by filimonov** [comment]
Actually it's one line fix needed...

**Comment by filimonov** [comment]
> > What is needed in that task - is the ability to stop writing err log
> 
> We already have this option.

Yes. And since we can disable writing err log at all - why do you think it is better to write errors only (or fatal only) there?

**Comment by alexey-milovidov** [comment]
> Actually it's one line fix needed...

Ok, do it.

**Comment by alexey-milovidov** [comment]
> And since we can disable writing err log at all - why do you think it is better than giving the user a choice - not write at all, to write errors only, or fatal only?

It is questionable feature. We can just drop and forget about it and concentrate on other features.
