### ISSUE TITLE
Failed to use MaterializeMySQL engine

### ISSUE THREAD

**Issue by sliontc** [ClickHouse/ClickHouse#19573]
When I created the MaterializeMySQL database engine, the database was not synced with below error:
![image](https://user-images.githubusercontent.com/6959147/105709501-c27e1f80-5f50-11eb-8752-460b627dc40d.png)

What error could be found in the create query?

**Comment by tavplubix** [comment]
Could you please post the CREATE query as a text, not as screenshot?

**Comment by sliontc** [comment]
CREATE TABLE `t_log` (
  `id` bigint DEFAULT NULL,
  `resource` varchar(255) DEFAULT NULL,
  `operateTime` datetime DEFAULT NULL,
  `isCheck` bit(1) DEFAULT b'0',
  `uni_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `operate` int DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

**Comment by sliontc** [comment]
I found the bit data type is not supported in CK, so I change it to tinyint, and the error disappeared. But another issue occurred, when I select data from the synced table, it always said: "table xxxx cannot be materialized, because there is no primary keys.".
Actually I'v added the primary key in MySQL.


2021.01.26 22:25:25.879522 [ 23186 ] {585fc753-f242-4367-8fe2-5fc6ef9a49c4} <Error> DynamicQueryHandler: Code: 48, e.displayText() = DB::Exception: The uni_center.c_organization cannot be materialized, because there is no primary keys., Stack trace (when copying this message, always include the lines below):

**Comment by stigsb** [comment]
See also #14735 for BIT support.

As for primary keys, you really want to have one. MaterializeMySQL could perhaps treat a unique index for a non-null column  (or concatenated non-null columns) as a primary key, if there's only one such index, but IMHO that would be putting even more hardcoded assumptions into MaterializeMySQL (there are enough of those already).
