### ISSUE TITLE
Insert from mysql with datetime as partition not work

### ISSUE THREAD

**Issue by RangerWolf** [ClickHouse/ClickHouse#19577]
Please help to DELETE this issue, I found I misunderstanding to output ` 0 rows in set. ` 
It works OK.

**Describe the bug**

1. `Select from mysql`  could get 6K+ records
2. But  `insert into (xxxx) select ... from mysql where create_time ... ` no data insert

Sample select sql:
```SQL
select
	`id`, `name`,  `md5`, `create_time`, `update_time`
from mysql('host:3306', 'db_name', 'table_name', 'user_name', 'password_value') 
where create_time >= '2021-01-24 00:00:00' and create_time < '2021-01-25 00:00:00';

-- Outut: Ok. 6693 rows in set. Elapsed: 0.165 sec
```

Insert  sql
```SQL
insert into target_table (
	`id`, `name`,  `md5`, `create_time`, `update_time`
) select
	`id`, `name`,  `md5`, `create_time`, `update_time`
from mysql('host:3306', 'db_name', 'table_name', 'user_name', 'password_value') 
where create_time >= '2021-01-24 00:00:00' and create_time < '2021-01-25 00:00:00';

--Output: Ok. 0 rows in set. Elapsed: 0.162 sec. Processed: 0 rows, 0.0B (0 rows/s, 0.0B/s)
```

**How to reproduce**
* Which ClickHouse server version to use
```SQL
select version()                                                           
┌─version()─┐
│ 20.8.9.6  │
└───────────┘
```

* `CREATE TABLE` statements for all tables involved
```SQL
CREATE TABLE target_table
(
    `id` Int32,
    `name` Nullable(String),
    `create_time` DateTime,
    `md5` String,
    `update_time` DateTime
)
ENGINE = MergeTree
PARTITION BY toDate(create_time)
ORDER BY md5
SETTINGS index_granularity = 8192
```

* Queries to run that lead to unexpected result
insert into sql described abover

**Expected behavior**
expect 6k+ records are inserted into clickhouse table from mysql

**Error message and/or stacktrace**
no any error messages

**Additional context**
No

**Comment by qoega** [comment]
> Please help to DELETE this issue, I found I misunderstanding to output 0 rows in set.
> It works OK.

closed
