### ISSUE TITLE
WITH doesn't work with UNION ALL

### ISSUE THREAD

**Issue by O1O1O1O** [ClickHouse/ClickHouse#19585]
**Describe the unexpected behaviour**

Using a CTE named in a WITH fails if a UNION ALL is used

**How to reproduce**

This CTE example returns `1`
```
WITH data AS (
  SELECT 1,2,3
)
SELECT COUNT(*) 
FROM (SELECT * FROM data);
```

but if I use a UNION ALL the CTE is not recognized:
```
WITH data AS (
  SELECT 1,2,3
)
SELECT COUNT(*) 
FROM (SELECT * FROM data)
UNION ALL (SELECT * FROM data);
```
Causing this error: `DB::Exception: Table default.data doesn't exist (version 21.1.2.15 (official build))`

Using CH version `21.1.2.15` and driver `clickhouse-jdbc 0.2.4`

**Comment by alexey-milovidov** [comment]
There is a setting `enable_global_with_statement`. Enabling this setting will turn on the desired behaviour.

Also we plan to enable it by default, see #18684.
