### ISSUE TITLE
Code: 198, DB::Exception: Cannot getnameinfo(): Name or service not known

### ISSUE THREAD

**Issue by ben-efiz** [ClickHouse/ClickHouse#19586]
**Describe the bug**
The ClickHouse setup (more details below) works as expected, including replication, but the error log at `/var/log/clickhouse-server/clickhouse-server.err.log` contains a big amount of unexpected stacktraces, always the same (see below). It seems it can not [resolve the host name](https://github.com/ClickHouse/ClickHouse/blob/80ae2b5138d98c01399c10543c11b69f7b2bad83/src/Common/DNSResolver.cpp#L120).

**Does it reproduce on recent release?**
21.1.2.15 (official build)

**How to reproduce**
* its not triggered by a specific query but happens just by running the clickhouse server

**Expected behavior**
No error logged if everything works as expected.

**Error message and/or stacktrace**
```
2021.01.25 19:12:50.043078 [ 59 ] {} <Error> bool DB::DNSResolver::updateCacheImpl(UpdateF &&, ElemsT &&, const DB::String &) [UpdateF = bool (DB::DNSResolver::*)(const Poco::Net::IPAddress &), ElemsT = std::__1::unordered_set<Poco::Net::IPAddress, std::__1::hash<Poco::Net::IPAddress>, std::__1::equal_to<Poco::Net::IPAddress>, std::__1::allocator<Poco::Net::IPAddress>> &]: Code: 198, e.displayText() = DB::Exception: Cannot getnameinfo(::ffff:<IP address redacted>): Name or service not known, Stack trace (when copying this message, always include the lines below):

0. ? @ 0x869e50d in /usr/bin/clickhouse
1. ? @ 0x869fa83 in /usr/bin/clickhouse
2. DB::DNSResolver::updateAddress(Poco::Net::IPAddress const&) @ 0x86a2308 in /usr/bin/clickhouse
3. bool DB::DNSResolver::updateCacheImpl<bool (DB::DNSResolver::*)(Poco::Net::IPAddress const&), std::__1::unordered_set<Poco::Net::IPAddress, std::__1::hash<Poco::Net::IPAddress>, std::__1::equal_to<Poco::Net::IPAddress>, std::__1::allocator<Poco::Net::IPAddress> >&>(bool (DB::DNSResolver::*&&)(Poco::Net::IPAddress const&), std::__1::unordered_set<Poco::Net::IPAddress, std::__1::hash<Poco::Net::IPAddress>, std::__1::equal_to<Poco::Net::IPAddress>, std::__1::allocator<Poco::Net::IPAddress> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x86a1d60 in /usr/bin/clickhouse
4. DB::DNSResolver::updateCache() @ 0x86a0d31 in /usr/bin/clickhouse
5. DB::DNSCacheUpdater::run() @ 0xeb6957a in /usr/bin/clickhouse
6. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0xeb39ae2 in /usr/bin/clickhouse
7. DB::BackgroundSchedulePool::threadFunction() @ 0xeb3bf17 in /usr/bin/clickhouse
8. ? @ 0xeb3d191 in /usr/bin/clickhouse
9. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x86415ed in /usr/bin/clickhouse
10. ? @ 0x86451a3 in /usr/bin/clickhouse
11. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
12. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
 (version 21.1.2.15 (official build))
```

**Additional context**

The IP address of the host in the above mentioned stacktrace was redacted but it showed correctly as 10.11.12.13 (as an example).

The ClickHouse instance is running using [ClickHouse Operator](https://github.com/Altinity/clickhouse-operator) on Kubernetes cluster using 1 shard, 2 replicas and 3 ZooKeeper instances.

```
uname -a
Linux chi-ugcluster-production-0-0-0 3.10.0-1062.18.1.el7.x86_64 #1 SMP Tue Mar 17 23:49:17 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

cat /proc/version                                                                                                                              126 ↵
Linux version 3.10.0-1062.18.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC) ) #1 SMP Tue Mar 17 23:49:17 UTC 2020
```

**Comment by den-crane** [comment]
As I understand after POD (server with CH restarted) it gets a new hostname.
After that other CH nodes alert this message because they try to update DNS cache for already non-existent (outdated) hostname. 
Everything else works as expected except this false error message.

**Comment by ben-efiz** [comment]
@den-crane i can confirm i had to restart the pods several times while keeping the persistant volume claim (aka storage including DB). Only remark i have is that the IP address i redacted is actually from the current host the pod is running on. Just before the first appearance of the above mentioned stacktrace, i see
```
[ 47 ] {} <Warning> AddressPatterns: Failed to check if the allowed client hosts contain address <IP address redacted>. DB::Exception: Cannot getnameinfo(::ffff:<IP address redacted>): Name or service not known, code = 198
```
with the same (and current host's) IP address.

**Comment by ben-efiz** [comment]
I can confirm the errors disappear after some time (possibly after pod restarts). @den-crane i leave it to you to keep ticket open as possible usability improvement.

**Comment by hdhoang** [comment]
since #35956 we have new option to stop retrying for each name after a few failures fwiw
