### ISSUE TITLE
Official  Online-Document (ch)  Writing errors

### ISSUE THREAD

**Issue by woshiyifadaguangtou** [ClickHouse/ClickHouse#19596]
https://clickhouse.tech/docs/zh/sql-reference/functions/date-time-functions/

![image](https://user-images.githubusercontent.com/8001533/105798293-d4050d00-5fcc-11eb-9f32-88630088e773.png)
Missing A 'Y' in function 'toYYYYMM' and 'toYYYYMMDD'

**Comment by kitaisreal** [comment]
Thanks for the information. Fixed in https://github.com/ClickHouse/ClickHouse/pull/19601.
