### ISSUE TITLE
The computation is limited by the memory of the client node

### ISSUE THREAD

**Issue by loovia** [ClickHouse/ClickHouse#19595]
I have 20 billion rows data to compute, and not enough memory to support computation.
Does any parameters can control put data on disk to compute? Or support shuffle to exchange data like MapReduce?
What I mean by that is to execute `Select`, the memory of the node that is limited

**Comment by den-crane** [comment]
max_bytes_before_external_group_by
max_bytes_before_external_sort

https://clickhouse.tech/docs/en/operations/settings/query-complexity/#settings-max_bytes_before_external_group_by

https://clickhouse.tech/docs/en/sql-reference/statements/select/order-by/#implementation-details

**Comment by loovia** [comment]
@den-crane thanks!
I add an extra parameter `SET distributed_aggregation_memory_efficient=1`, and it seems to be working.
My cluster consists of three hosts with two shard each, and I found that one clickhouse-server node not increase the memory. The memory usage of the other two nodes was expected. 
Ideally, all three hosts use about the same amount of memory. Why does this happen?

**Comment by den-crane** [comment]
>My cluster consists of three hosts with two shard each

What do you mean by that?

**Comment by loovia** [comment]
My clickhouse consists of 3 shards and 1 replica.

**Comment by den-crane** [comment]
> My clickhouse consists of 3 shards and 1 replica.

you mean circle-replication?

or you have
host1: shard1replica1
host2: shard2replica1
host3: shard3replica1
?

**Comment by loovia** [comment]
> host1: shard1replica1
host2: shard2replica1
host3: shard3replica1

it is.

**Comment by alexey-milovidov** [comment]
BTW, we want to enable `distributed_aggregation_memory_efficient` by default.
@den-crane Do you remember any issues from your experience?

PS. It is already enabled in Yandex Metrica clusters for years.

**Comment by loovia** [comment]
My current problem is:
when I execute `insert into ... select ... ` , one of the hosts in my cluster did not seem to be working because memory usage had not changed

**Comment by den-crane** [comment]
> BTW, we want to enable `distributed_aggregation_memory_efficient` by default.
> @den-crane Do you remember any issues from your experience?
> 
> PS. It is already enabled in Yandex Metrica clusters for years.

It's a good idea. We also have it enabled for years. 
I think all issues about distributed_aggregation_memory_efficient are solved right now.

**Comment by den-crane** [comment]
@loovia please show the result of 

```
SELECT
    cluster,
    shard_num,
    replica_num,
    host_name
FROM system.clusters
WHERE cluster NOT LIKE 'test_%'
```

**Comment by loovia** [comment]
┌─cluster──────────────────────────────┬─shard_num─┬─replica_num─┬─host_name─────┐
│ clickhouse_cluster_3shards_2replicas │         1 │           1 │ node1         │
│ clickhouse_cluster_3shards_2replicas │         1 │           2 │ node2         │
│ clickhouse_cluster_3shards_2replicas │         2 │           1 │ node2         │
│ clickhouse_cluster_3shards_2replicas │         2 │           2 │ node3         │
│ clickhouse_cluster_3shards_2replicas │         3 │           1 │ node3         │
│ clickhouse_cluster_3shards_2replicas │         3 │           2 │ node1         │
└──────────────────────────────────────┴───────────┴─────────────┴───────────────┘

**Comment by den-crane** [comment]
@loovia So it's a circle-replication. 

Probably you need to create proper remote_servers order for each host. And set **load_balancing = in_order** !!!
Because right now CH can query only 2 hosts and get all data from it.

All 3 hosts have to have **different**!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! remote_servers order:

example for host1 !!!!! ONLY:
```
   <shard>
        <replica>node1
        <replica>node2
<shard>
        <replica>node2
        <replica>node3
<shard>
        <replica>node3
        <replica>node1
```
So with **load_balancing = in_order**  node1 as node initiator will get data from all 3 servers, because they are the first in replica's list.

**Comment by loovia** [comment]
@den-crane thank you very much !!
