### ISSUE TITLE
GraphiteMergeTree documentation

### ISSUE THREAD

**Issue by ei-grad** [ClickHouse/ClickHouse#1960]
GraphiteMergeTree documentation lacks the description of its configuration parameters:
- `path_column_name`
- `time_column_name`
- `value_column_name`
- `version_column_name`

Also, the default value for `version_column_name` is `Timestamp`, but the documentation mentions the `Version` column.

**Comment by AlekSi** [comment]
Documentation also states that "Graphite stores full data in ClickHouse" and make it sound like roll-ups are just read feature, the data on disk stays the same. It does not mention the fact that `OPTIMIZE` roll-ups data on disk.

**Comment by alexey-milovidov** [comment]
Fixed.
