### ISSUE TITLE
ALTER TABLE performance issue

### ISSUE THREAD

**Issue by allen12921** [ClickHouse/ClickHouse#19616]
We are using below clickhouse and  encountered performance  issue when  ALTER TABLE:
ClickHouse client version 20.3.8.53 (official build).

Below is  the query_log, Please advice

select  * from  query_log;

type:                 QueryFinish
event_date:           2021-01-26
event_time:           2021-01-26 07:48:16
query_start_time:     2021-01-26 07:46:01
query_duration_ms:    135179
read_rows:            0
read_bytes:           0
written_rows:         0
written_bytes:        0
result_rows:          0
result_bytes:         0
memory_usage:         76246397
  ALTER TABLE mytables update flag = modulo(plus(flag, 2), 3) where prod_id IN (‘5e06eec2d1ec2a5a8a5cbbb2',....,'5e06eec2d1ec2a5a8a5cbbb2'）
exception_code:       0
exception:            
stack_trace:          
is_initial_query:     1
user:                 admin
query_id:             84f0c96e-893e-4663-9095-a8a5e8a7864b
address:              ::ffff:172.27.253.89
port:                 52404
initial_user:         admin
initial_query_id:     84f0c96e-893e-4663-9095-a8a5e8a7864b
initial_address:      ::ffff:172.27.253.89
initial_port:         52404
interface:            2
os_user:              
client_hostname:      
client_name:          
client_revision:      0
client_version_major: 0
client_version_minor: 0
client_version_patch: 0
http_method:          2
http_user_agent:      
quota_key:            
revision:             54433
thread_ids:           [2057]
ProfileEvents.Names:  ['Query','FileOpen','WriteBufferFromFileDescriptorWrite','WriteBufferFromFileDescriptorWriteBytes','IOBufferAllocs','IOBufferAllocBytes','ArenaAllocChunks','ArenaAllocBytes','FunctionExecute','CreatedWriteBufferOrdinary','DiskWriteElapsedMicroseconds','ContextLock','RWLockAcquiredReadLocks','RealTimeMicroseconds','UserTimeMicroseconds','SystemTimeMicroseconds','SoftPageFaults','OSIOWaitMicroseconds','OSCPUWaitMicroseconds','OSCPUVirtualTimeMicroseconds','OSWriteBytes','OSWriteChars']
ProfileEvents.Values: [1,1,1,478736,9,4194599,2,8192,8,1,257,26,2,135204034,85915,32415,19230,233,123,118329,577536,605184]
Settings.Names:       ['max_threads','max_alter_threads','max_query_size','use_uncompressed_cache','background_pool_size','load_balancing','max_streams_multiplier_for_merge_tables','log_queries','max_ast_elements','max_expanded_ast_elements','max_memory_usage','max_memory_usage_for_user','log_query_threads']
Settings.Values:      ['72','72','100000000','1','72','random','10','1','1000000','1000000','32212254720','0','0']

**Comment by filimonov** [comment]
And what is the issue? ALTER UPDATE can take significant time if you have a significant amount of data. It really iterates through parts unpack them, check conditions, apply the update if there are matching rows, and pack the modified columns back. 

In some cases ALTER UPDATE may be locked by replication queue / merges and other things. 

It's better to check the status of ALTER UPDATE inside system.mutations / system.merges / system.replication_queue.

**Comment by filimonov** [comment]
Or you mean that async ALTER is waiting for something? Most probably some concurrent operation was holding the lock. Consider update to 20.8 or newer ClickHouse versions, most of the locks related to alters were removed in 20.6.
