### ISSUE TITLE
How to get map type all keys or values or do count aggregation?

### ISSUE THREAD

**Issue by ahutsunshine** [ClickHouse/ClickHouse#19611]
For the implementation of map type https://github.com/ClickHouse/ClickHouse/pull/15806 and the document https://github.com/ClickHouse/ClickHouse/pull/19592, I dont see how I can iterate the map type and  get all map keys or values? Also, I  want to calculate the map value count  group by the map value, how can I do this? Thanks.

**Comment by ahutsunshine** [comment]
For  example, if the table `table_map` has the following data where the  keys are `name`, `age` and `gender` and  the values are  `20` , `lisi`  and `female`, how can I get them? And  how to  do  count aggregation group by `name` key  or `lisi` value?
```
select * from table_map  
┌─a─────────────────────────────────┐
│ {'name':'lisi','age':'20'}        │
│ {'name':'lisi','gender':'female'} │
└───────────────────────────────────┘
```

**Comment by sundy-li** [comment]
You can try #18788  #9273

**Comment by ahutsunshine** [comment]
@sundy-li Can you share me the clickhouse version where I can use mapKeys or mapValues? I use the latest clickhouse version https://github.com/ClickHouse/ClickHouse/releases/tag/v21.1.2.15-stable to build the clickhouse server, but got `Unknown function mapKeys: While processing mapKeys(a)` when using it.

**Comment by sundy-li** [comment]
it's only in master, you can download from ci builds

**Comment by ahutsunshine** [comment]
Sure, but it doesnt solve the problem. In prod, we need to a stable version rather than it we build by ourselves where there may have bugs and not be used in prod.

**Comment by sundy-li** [comment]
@ahutsunshine  Map is an experimental feature currently.
