### ISSUE TITLE
what's the meaning of the string following in clickhouse-server.err.log

### ISSUE THREAD

**Issue by wallace-clickhouse** [ClickHouse/ClickHouse#19626]
In clickhouse-server.err.log,I find the following record such as
"_DB::TCPHandler::runImpl() @ 0x4f24ce7 in /opt/clickhouse/programs/clickhouse_"
So what's the meaning of _@ 0x4f24ce7_?
how does it be generated? Thank you!

**Comment by filimonov** [comment]
It's the address in an executable. If you have debug symbols installed it can be mapped into a position of source code, for example like that:

```
apt-get update 
apt-get install clickhouse-common-static-dbg=$(clickhouse-client --version-clean) 
apt-get install binutils
addr2line -afiCe /path/to/clickhouse 0x4f24ce7
```
