### ISSUE TITLE
Why do join and filters get errors？

### ISSUE THREAD

**Issue by JonasBollack** [ClickHouse/ClickHouse#19645]
table A:
![image](https://user-images.githubusercontent.com/17606375/105842341-f9b40580-6010-11eb-8507-6ea46fe814c8.png)
table B:
![image](https://user-images.githubusercontent.com/17606375/105842364-0173aa00-6011-11eb-94a3-47c162dd40fd.png)

select 
  "T_8FB5CF"."id1" "__fcol_0", 
  "T_8FB5CF"."id2" "__fcol_1", 
  "T_8FB5CF"."id3" "__fcol_2", 
  "T_8FB5CF"."id4" "__fcol_3", 
  "T_8FB5CF"."id5" "__fcol_4", 
  "T_8FB5CF"."date" "__fcol_5", 
  "T_8FB5CF"."shuzhi" "__fcol_6", 
  "T_8FB5CF"."数值2" "__fcol_7"
from "A1"."B" "T_8FB5CF"
  left outer join "A1"."A" "T_8C7546"
  on "T_8FB5CF"."id2" = "T_8C7546"."id2"
where (
  "T_8C7546"."id2" = ''
  or "T_8C7546"."id2" is null
)
limit 5000
ClickHouse exception, code: 47, host: 192.168.5.67, port: 8123; Code: 47, e.displayText() = DB::Exception: Missing columns: 'T_8C7546.id2' while processing query: '(T_8C7546.id2 = '') OR isNull(T_8C7546.id2)', required columns: 'T_8C7546.id2', source columns: '数值2' 'shuzhi' 'date' 'id5' 'id3' 'id2' 'id4' 'id1' (version 20.5.4.40)

**Comment by den-crane** [comment]
20.5.4.40 is obsolete.

Please check against 21.1.2.15

Please provide `show create table "A1"."B"` and `show create table "A1"."A" `

**Comment by JonasBollack** [comment]
please help me! thanks
CREATE TABLE A1.B
(
    `id1` Nullable(String),
    `id2` Nullable(String),
    `id3` Nullable(String),
    `id4` Nullable(String),
    `id5` Nullable(String),
    `date` Nullable(Date),
    `shuzhi` Nullable(Int32),
    `数值2` Nullable(Int32)
)
ENGINE = MySQL('192.168.5.57:3306', 'pearl', 'B', 'root', 'root')

CREATE TABLE A1.A
(
    `id123` Nullable(String),
    `id2` Nullable(String),
    `id 3` Nullable(String),
    `date` Nullable(Date),
    `shuzhi` Nullable(Int32),
    `数值2` Nullable(Int32)
)
ENGINE = MySQL('192.168.5.57:3306', 'pearl', 'A', 'root', 'root')

**Comment by JonasBollack** [comment]
> 20.5.4.40 is obsolete.
> 
> Please check against 21.1.2.15
> 
> Please provide `show create table "A1"."B"` and `show create table "A1"."A" `



> 20.5.4.40 is obsolete.
> 
> Please check against 21.1.2.15
> 
> Please provide `show create table "A1"."B"` and `show create table "A1"."A" `

please help me! thanks
CREATE TABLE A1.B
(
id1 Nullable(String),
id2 Nullable(String),
id3 Nullable(String),
id4 Nullable(String),
id5 Nullable(String),
date Nullable(Date),
shuzhi Nullable(Int32),
数值2 Nullable(Int32)
)
ENGINE = MySQL('192.168.5.57:3306', 'pearl', 'B', 'root', 'root')

CREATE TABLE A1.A
(
id123 Nullable(String),
id2 Nullable(String),
id 3 Nullable(String),
date Nullable(Date),
shuzhi Nullable(Int32),
数值2 Nullable(Int32)
)
ENGINE = MySQL('192.168.5.57:3306', 'pearl', 'A', 'root', 'root')

**Comment by alexey-milovidov** [comment]
```
CREATE DATABASE A1;

CREATE TABLE A1.B
(
    `id1` Nullable(String),
    `id2` Nullable(String),
    `id3` Nullable(String),
    `id4` Nullable(String),
    `id5` Nullable(String),
    `date` Nullable(Date),
    `shuzhi` Nullable(Int32),
    `数值2` Nullable(Int32)
)
ENGINE = Memory;

CREATE TABLE A1.A
(
    `id123` Nullable(String),
    `id2` Nullable(String),
    `id3` Nullable(String),
    `date` Nullable(Date),
    `shuzhi` Nullable(Int32),
    `数值2` Nullable(Int32)
)
ENGINE = Memory;

SELECT
    T_8FB5CF.id1 AS __fcol_0,
    T_8FB5CF.id2 AS __fcol_1,
    T_8FB5CF.id3 AS __fcol_2,
    T_8FB5CF.id4 AS __fcol_3,
    T_8FB5CF.id5 AS __fcol_4,
    T_8FB5CF.date AS __fcol_5,
    T_8FB5CF.shuzhi AS __fcol_6,
    T_8FB5CF.`数值2` AS __fcol_7
FROM A1.B AS T_8FB5CF
LEFT JOIN A1.A AS T_8C7546 ON T_8FB5CF.id2 = T_8C7546.id2
WHERE (T_8C7546.id2 = '') OR isNull(T_8C7546.id2)
LIMIT 5000;

Received exception from server (version 21.3.1):
Code: 47. DB::Exception: Received from localhost:9000. DB::Exception: Missing columns: 'T_8C7546.id2' while processing query: '(T_8C7546.id2 = '') OR isNull(T_8C7546.id2)', required columns: 'T_8C7546.id2' 'T_8C7546.id2'.
```

**Comment by UnamedRus** [comment]
Related https://github.com/ClickHouse/ClickHouse/issues/19288
