### ISSUE TITLE
how to remove a shard? And move the data to another shard

### ISSUE THREAD

**Issue by gj-zhang** [ClickHouse/ClickHouse#19646]
how to remove a shard? And move the data to another shard

**Comment by den-crane** [comment]
Is your table Replicated ?

**Comment by gj-zhang** [comment]
> Is your table Replicated ?
> What CH version?

yes

20.9.3.45

**Comment by den-crane** [comment]
Then you can execute fetch partition for all partitions ( copy them from old shard to another into detached folder of table ).

https://clickhouse.tech/docs/en/sql-reference/statements/alter/partition/#alter_fetch-partition

```
ALTER TABLE users FETCH PARTITION 201902 FROM '/clickhouse/tables/01-01/visits';
```

For example at old server generate SQL script:
```
select concat('alter table `',table, '` fetch partition id \'', partition_id, '\'FROM \'/clickhouse/tables/01-01/visits\';')
from system.parts 
where active = 1 and table like 'visits' 
group by database,table,partition_id
order by database,table,partition_id 
```
execute this SQL script at another server.


Then at another server

```
select concat('alter table `',table, '` attach part id '||partition_id||';')
from system.detached_parts
where database = 'xxx' and table = 'visits'

```
execute this SQL script at another server.

drop the table visits at old shard on all replicas

**Comment by frankwg** [comment]
Hi @den-crane Is it possible to use FETCH PART / ATTACH PART instead of FETCH PARTITION / ATTACH PARTITION for data movement?
