### ISSUE TITLE
SSE4 and AVX512 acceleration for LZ4 decompression

### ISSUE THREAD

**Issue by yingfeng** [ClickHouse/ClickHouse#19647]
Within the codes of `LZ4_decompress_faster.h|cpp`, I've found that SIMD acceleration is used for LZ4 decompression.  However, I could only see optimization code for SSE2|SSE2|NEON, currently, state of the art SIMD could be based on SSE4 or AVX512, why not provide corresponding optimizations for these two suite of SIMD instructions?

**Comment by alexey-milovidov** [comment]
Yes, we can try to use AVX-512 there.

Details:

There are two components where SIMD is used:
- copy;
- shuffle.

For shuffle it is using specific "shuffle" intruction from SSSE3. There is no such instruction in AVX2.
As far as I remember, there is only shuffle separately inside two halves of the AVX register.
If there is full shuffle instruction in AVX-512, we can use it.

For copy, what matters is register size. We already using SSE2 (16 bytes).
AVX (32 bytes) is not used to avoid switching between SSE and AVX registers when doing shuffle.
We can use AVX-512 there.

**Comment by yingfeng** [comment]
Thank you,  there seems not to be suitable shuffle instructions within AVX..

**Comment by nnsgmsone** [comment]
I think _mm512_shuffle_epi8 is working, could it be that there is some problem with the function? @alexey-milovidov

**Comment by alexey-milovidov** [comment]
@nnsgmsone Looks like it should work with two instructions: https://twitter.com/pshufb/status/1099684103207698433

**Comment by nnsgmsone** [comment]
yes

**Comment by guowangy** [comment]
@alexey-milovidov 
Is this issue still help wanted?
Icelake Server has VBMI features which allows shuffle across 32 & 64 bytes data.
I can help to add a shuffle version of `copyOverlay32` based on this.

**Comment by alexey-milovidov** [comment]
@guowangy Yes, still wanted!

**Comment by guowangy** [comment]
Thanks. I will work on it.

**Comment by guowangy** [comment]
Implemented: https://github.com/ClickHouse/ClickHouse/pull/37891
