### ISSUE TITLE
Execute Clickhouse compressor -- decompress to return xshell

### ISSUE THREAD

**Issue by xiedeyantu** [ClickHouse/ClickHouse#19658]
SELECT *
FROM mt2

┌─a─┬──b─┬──c─┐
│ 3 │  4 │ 10 │
│ 3 │  5 │  9 │
│ 3 │  6 │  8 │
│ 3 │  7 │  7 │
│ 3 │  8 │  6 │
│ 3 │  9 │  5 │
│ 3 │ 10 │  4 │
└───┴────┴────┘

The data directory is as follows

[root@ck mt2]# tree
.
├── 3_1_1_0
│   ├── a.bin
│   ├── a.mrk
│   ├── b.bin
│   ├── b.mrk
│   ├── c.bin
│   ├── checksums.txt
│   ├── c.mrk
│   ├── columns.txt
│   ├── count.txt
│   ├── minmax_a.idx
│   ├── partition.dat
│   ├── primary.idx
│   ├── skp_idx_idx_c.idx
│   └── skp_idx_idx_c.mrk
├── detached
└── format_version.txt

Execute clickhouse-compressor like this

[root@ck mt2]# clickhouse-compressor --decompress < 3_1_1_0/b.bin2                                                                                                                	
[root@ck mt2]# Xshell

**Comment by xiedeyantu** [comment]
[root@ck mt2]# clickhouse-compressor --decompress < 3_1_1_0/b.bin
[root@ck mt2]# Xshell

not b.bin2

**Comment by alexey-milovidov** [comment]
That is correct and you just read some binary data from your table into your terminal.

**Comment by xiedeyantu** [comment]
Why show Xshell instead of data？I want to see the structure of the bin file

**Comment by alexey-milovidov** [comment]
Binary data can be interpreted by terminal.

**Comment by xiedeyantu** [comment]
Can you give me a shell command? How to operate?

**Comment by alexey-milovidov** [comment]
Could you please tell me how to reproduce this result?

E.g. CREATE TABLE statement, INSERT...

**Comment by alexey-milovidov** [comment]
To display binary data I also recommend `xxd` tool:

`clickhouse-compressor --decompress < 3_1_1_0/b.bin | xxd`

**Comment by xiedeyantu** [comment]
This shell command is easy to use. Thank you very much
