### ISSUE TITLE
SELECT * doesn't include ALIAS columns

### ISSUE THREAD

**Issue by db0rg** [ClickHouse/ClickHouse#19659]
**Describe the unexpected behaviour**
When using `SELECT * FROM table` it doesn't include any columns defined using `ALIAS` expressions. This affects both queries and views made using `SELECT *`.

**How to reproduce**
Encountered and verified on 20.11.3 (current docker image for `yandex/clickhouse-server:20.3`)

```
:) create table foo (x UInt8, y UInt8, z UInt8 ALIAS x + y) Engine=Memory()

CREATE TABLE foo
(
    `x` UInt8,
    `y` UInt8,
    `z` UInt8 ALIAS x + y
)
ENGINE = Memory()

Ok.

:) insert into table foo (x, y) VALUES (1, 2)

INSERT INTO foo (x, y) VALUES

Ok.

:) select * from foo

SELECT *
FROM foo

┌─x─┬─y─┐
│ 1 │ 2 │
└───┴───┘

:) select z from foo

SELECT z
FROM foo

┌─z─┐
│ 3 │
└───┘

:) create view bar as select * from foo

CREATE VIEW bar AS
SELECT *
FROM foo

Ok.

:) select * from bar

SELECT *
FROM bar

┌─x─┬─y─┐
│ 1 │ 2 │
└───┴───┘

 :) select z from bar

SELECT z
FROM bar


Received exception from server (version 20.11.3):
Code: 47. DB::Exception: Received from host.docker.internal:9000. DB::Exception: Missing columns: 'z' while processing query: 'SELECT z FROM (SELECT * FROM default.foo) AS bar', required columns: 'z', source columns: 'y' 'x'.
```

**Expected behavior**
I expect `SELECT * from table` to include all the columns present in the `SHOW CREATE table` expression. In particular I expect a view created as `CREATE VIEW table_view AS SELECT * from table` to be able to access the same columns as the original table.

**Additional context**
Creating views via by selecting everything from another table is a useful pattern to switch between several tables that contain different versions of "the same" data. The present behaviour means that it's not compatible with `ALIAS` columns limiting their usefulness. I realize there might be some subtleties involving materialized views in which case one wouldn't want to increase the materialized size, but it seems avoidable by inheriting the aliasing or restricting the behaviour in that case.

**Comment by alexey-milovidov** [comment]
This behaviour is motivated by the following use cases:
- create table dump with `SELECT * FROM table` and be able to load it back;
- create another table and insert all data with `INSERT INTO table SELECT * FROM another table`;
- use as many alias columns with various expressions as the user wants without considerations about data listing with `SELECT * FROM table`.

We cannot change this behaviour without breaking backwards compatibility.

**Comment by alexey-milovidov** [comment]
Two settings were added recently:

`asterisk_include_materialized_columns`
`asterisk_include_alias_columns`

**Comment by alexey-milovidov** [comment]
AFAIK, these settings affect query analysis at query time.
So, if you already created a view with `SELECT *`, the meaning of the `*` can be changed on per-query basis.

**Comment by alexey-milovidov** [comment]
These settings should address your use case.
