### ISSUE TITLE
ColumnVector may segfault

### ISSUE THREAD

**Issue by yuzhichang** [ClickHouse/ClickHouse#19667]
I leaved a comment at https://github.com/clickhouse/clickhouse/pull/13097:
src/Columns/ColumnVector.h L115:
```
    using Container = std::conditional_t<is_POD,
                                         PaddedPODArray<ValueType>,
                                         std::vector<ValueType>>;
```
ColumnArray::sizeAt(n) may pass -1. It's safe for PaddedPODArray since it always allocate some unused bytes at the begin and end of the array. However it's dangerous for std::vector.

**Comment by alexey-milovidov** [comment]
That's true, std::vector should not be used there.

**Comment by alexey-milovidov** [comment]
Big integers were rewritten to use the memory layout that corresponds to native integers
(contiguous memory with exactly the corresponding number of bits, little endian, most significant sign bit...)

The special case in code becomes irrelevant and I will remove them.
