### ISSUE TITLE
недостаточная документация по clickhouse-local

### ISSUE THREAD

**Issue by chipitsine** [ClickHouse/ClickHouse#1966]
добрый день!

к примеру, есть такой файл

```
ilia@localhost:~$ head example.csv 
"column1","column2","column3"
1,2,3
1,1,1
2,1,1
```

команда фейлится по непонятной причине. подозреваю, что не описан явно формат. но ведь он, согласно спецификации, описан в первой строке ?
```
ilia@localhost:~$ clickhouse-local -N example --file example.csv --input-format CSV --query "select column1 from example"
Code: 60. DB::Exception: Table _local.example doesn't exist.

ilia@localhost:~$ 
```

действительно, добавляем явно формат, запрос проходит. но что это ? зачем оно включило первую служебную строку ?

```
ilia@localhost:~$ clickhouse-local -N example --structure "column1 String, column2 String, column3 String" --file example.csv --input-format CSV --query "select column1 from example"
Read 4 rows, 138.00 B in 0.001 sec., 5748 rows/sec., 193.68 KiB/sec.
column1
1
1
2
ilia@localhost:~$ 
```

кажется, тут есть серьезные недоработки с поддержкой CSV (и с документацией)

**Comment by filimonov** [comment]
> зачем оно включило первую служебную строку ?

А Вы зачем включили первую служебную строку в файл CSV? :) 
Если серьезно: просто замените формат на CSVWithNames

Про документацию - да, не всё идеально. Возможные форматы описаны тут: https://clickhouse.yandex/docs/en/formats/

**Comment by chipitsine** [comment]
не работает

```
ilia@localhost:~$ clickhouse-local -N example --file example.csv --input-format CSVWithNames --query "select column1 from example"
Code: 60. DB::Exception: Table _local.example doesn't exist.

ilia@localhost:~$ 

```

**Comment by filimonov** [comment]
Ok, теперь видимо не хватает параметра --structure, который описывал бы то, какие поля должны быть в таблице.  См. https://clickhouse.yandex/docs/ru/table_engines/external_data/

**Comment by chipitsine** [comment]
если не хватает параметра --structure, очевидно, об этом стоит написать явно. из ```Table _local.example doesn't exist.``` трудно об этом предположить (учитывая, что я указал CSVWithNames)

**Comment by filimonov** [comment]
посмотрел на исходники clickhouse-local по-другому обрабатывает внешние таблицы (думал что так же как external_data). 

Проблема кажется в этом return: 
https://github.com/yandex/ClickHouse/blob/d64f2beaf84123ee6c69c482b5c40029a8ed1194/dbms/src/Server/LocalServer.cpp#L364

Может быть было бы лучше сделать так же как в external_data для clickhouse-client? Тогда можно было бы использовать несколько таблиц в clickhouse-local.

**Comment by chipitsine** [comment]
если там можно сделать так, чтобы имена столбцов брались из CSV - это то, что нужно.

если нет, но скажет явно, что нужен аргумент --structure - тоже нормально

**Comment by chipitsine** [comment]
я ориентировался на вот такую штуку ttps://habrahabr.ru/post/85758/ (к сожалению, под линукс ее нет). мне почему-то казалось, что это естественно - брать названия столбцов прямо из CSV

**Comment by filimonov** [comment]
В ClickHouse используются строгие типы данных. Конечно можно просто все столбцы записать как строки, но тогда это будет работать менее эффективно, чем если заранее для числовых стобцов указать подходящий тип: https://clickhouse.yandex/docs/ru/data_types/int_uint/  , указать в каких столбцах хранятся даты и т.д. Сделать это автоматически только на основании заголовков CSV - невозможно.

**Comment by chipitsine** [comment]
по умолчанию как строки - вполне норм. если я хочу явно, я ведь смогу переопределить ?

**Comment by filimonov** [comment]
Угу. Кстати, почему clickhouse-local? мне кажется обычный clickhouse-server удобнее почти всегда, и вовсе не так уж тяжеловесен, его в любой момент можно остановить, если не нужен. clickhouse-local в основном используется чтоб какие-то простые вещи в command line делать без запуска сервера.

**Comment by chipitsine** [comment]
одноразовая обработка CSV, с аггрегацией.

**Comment by chipitsine** [comment]
"clickhouse-local в основном используется чтоб какие-то простые вещи в command line делать без запуска сервера" - задача вполне попадала под это условие.

если вы с какой-то целью включаете clickhouse-local в дистрибутив, то его могут запускать. если вы не хотите, чтобы его запускали - не включайте в дистрибутив

**Comment by faucct** [comment]
> В ClickHouse используются строгие типы данных. Конечно можно просто все столбцы записать как строки, но тогда это будет работать менее эффективно, чем если заранее для числовых стобцов указать подходящий тип: https://clickhouse.yandex/docs/ru/data_types/int_uint/ , указать в каких столбцах хранятся даты и т.д. Сделать это автоматически только на основании заголовков CSV - невозможно.

Как я понимаю, речь идет только о том, чтобы учитывать порядок колонок в заголовке CSV. Сейчас заголовок просто [пропускается](https://github.com/yandex/ClickHouse/blob/6b74ab870822d8487c7c710c0f9a0d53b45d1000/dbms/src/Formats/CSVRowInputStream.cpp#L110). Возможно ли это поправить?

**Comment by alexey-milovidov** [comment]
> Как я понимаю, речь идет только о том, чтобы учитывать порядок колонок в заголовке CSV. Сейчас заголовок просто пропускается. Возможно ли это поправить?

Да, совсем несложно добавить возможность учёта столбцов в заголовке.

**Comment by alexey-milovidov** [comment]
> Да, совсем несложно добавить возможность учёта столбцов в заголовке.

Добавлено, настройка `input_format_with_names_use_header`.

**Comment by filimonov** [comment]
Эта статья частично решает проблему недостаточной документации:

https://www.altinity.com/blog/2019/6/11/clickhouse-local-the-power-of-clickhouse-sql-in-a-single-command

**Comment by alexey-milovidov** [comment]
@filimonov В таком случае надо просто поместить ссылку в документацию?
