### ISSUE TITLE
Reading performance for big binary data

### ISSUE THREAD

**Issue by mayankkandari** [ClickHouse/ClickHouse#19671]
Hi,
We  migrated our  timeseries database from MySQL database to Clickhouse DB. We write our database into two tables

1. timeseries_table (time(INT), report_id(INT), report_element_id(INT), value(INT))
2. snapshot_report(time(INT),  report_id(INT), VALUE (BINARY  STRING DATA).

First table contains timeseries point for every element of a report.

In second table we write 1000 tuples (report_element_id, value) in single row using binary string 

We are using ClickHouse server version 20.1.8.41.

While reading data from second table ( snapshot_report), reading operation is slow compare to Mysql or Postgres database whereas reading operation from first (timeseries_table) table is 50 time faster  compare to Mysql/Postgres.  Any suggestion here to achieve  high reading performance from second table. Max length of data is (62000 Bytes) for value in snapshot_report. 

ENGINE Table type used is MERGE TREE.

**Comment by mayankkandari** [comment]
snapshot_report (`created` Date DEFAULT toDate(start_time), `recno` UInt32 DEFAULT CAST(1, 'UInt32'), `report_id` UInt32, `start_time` UInt32, `data` String, `metadata` String) ENGINE = MergeTree() PARTITION BY toStartOfWeek(created) PRIMARY KEY (report_id, start_time) ORDER BY (report_id, start_time) SETTINGS index_granularity = 8192 

This is exact schema of table.

**Comment by alexey-milovidov** [comment]
@mayankkandari You should recreate the table without `SETTINGS index_granularity = 8192`.

**Comment by mayankkandari** [comment]
> @mayankkandari You should recreate the table without `SETTINGS index_granularity = 8192`.

Hi @alexey-milovidov ,
Thanks your your speedy response. I don't specify SETTINGS index_granularity = 8192 in "CREATE TABLE statement" but when I execute "SHOW CREATE TABLE",  I see SETTINGS index_granularity = 8192 .

**Comment by alexey-milovidov** [comment]
@mayankkandari 

Ok. Could you please recreate the snapshot table with `SETTINGS index_granularity_bytes` = '1M'?
It may help by reducing the data amount that is read for point queries.

**Comment by alexey-milovidov** [comment]
Also, if the first table works fast enough for all types of queries you may not need to duplicate data in the second table.
