### ISSUE TITLE
Clickhouse-Copier: Is inserting in destination tables parts not in intended destination table

### ISSUE THREAD

**Issue by RO-29** [ClickHouse/ClickHouse#19688]
Hello I have a question about clickhouse-copier, I am using the latest 21.2.1

I was able to do the required configurations and able to run the script as well

```
on the source cluster, I have two nodes (replicated, single shard)
And on destination cluster, I have 4 nodes (replicated and 2 shard)

I declared table pre-hand on destination cluster with ReplicatedMergeTree type manually while defining sharding key in description.xml

After running clickhouse-copier, I see many local tables being made by clickhouse copier but it was not inserted in the destination table.

instead it was inserting in {destination_cluster}.{table_name}_part_{x}  whose engine type was MergeTree (not the one I declared, ReplicatedMergeTree)

I stopped the copier after running for few minutes as my intended destination table was still empty
My source table is around 200GBi
```

Is it a known behavior? will the parts table merge automatically to the source table?

My custom script is not able to scale well to copy big tables and hence I would really like the clickhouse-copier to work

Otherwise I would be forced to use Insert into .. Select From .. which is very slow

**Comment by SaltTan** [comment]
clickhouse-copier creates intermediate tables in order to handle exceptions better.
Just wait a little longer.
You can also read copier's logs to find out what it is doing.
Or at least check system.processes.
There is some information in this discussion: https://github.com/ClickHouse/ClickHouse/pull/9075
