### ISSUE TITLE
how to convert FixedString(16) to UInt256 in CH?

### ISSUE THREAD

**Issue by chenk818** [ClickHouse/ClickHouse#19691]

**Comment by kitaisreal** [comment]
Hello, @chenk818 

```SQL
CREATE TABLE test_fixed_string(value FixedString(16)) ENGINE=TinyLog;
INSERT INTO test_fixed_string VALUES ('1'), ('2'), ('3');
SELECT value, toInt256(value), cast(value, 'Int256') FROM test_fixed_string
```
Result:
```
┌─value─┬─toInt256(value)─┬─cast(value, 'Int256')─┐
│ 1     │               1 │                     1 │
│ 2     │               2 │                     2 │
│ 3     │               3 │                     3 │
└───────┴─────────────────┴───────────────────────┘
```

For additional reference:
Information about type conversions: https://clickhouse.tech/docs/en/sql-reference/functions/type-conversion-functions/#toint8163264128256
Link to our test ClickHouse setup where you can experiment with queries: https://gh-api.clickhouse.tech/play.

**Comment by chenk818** [comment]
> Hello, @chenk818
> 
> ```sql
> CREATE TABLE test_fixed_string(value FixedString(16)) ENGINE=TinyLog;
> INSERT INTO test_fixed_string VALUES ('1'), ('2'), ('3');
> SELECT value, toInt256(value), cast(value, 'Int256') FROM test_fixed_string
> ```
> 
> Result:
> 
> ```
> ┌─value─┬─toInt256(value)─┬─cast(value, 'Int256')─┐
> │ 1     │               1 │                     1 │
> │ 2     │               2 │                     2 │
> │ 3     │               3 │                     3 │
> └───────┴─────────────────┴───────────────────────┘
> ```
> 
> For additional reference:
> Information about type conversions: https://clickhouse.tech/docs/en/sql-reference/functions/type-conversion-functions/#toint8163264128256
> Link to our test ClickHouse setup where you can experiment with queries: https://gh-api.clickhouse.tech/play.

@kitaisreal  thanks,but my question is not like this.
I have a cloumn with String type,and want to convert it to UInt type。So i used sipHash128 function to convert the String colunn into FixedString(16).Just like below:

SELECT sipHash128('hello') AS a

┌─a──────┐
│ T3"X!

Then how to convert a to UInt256?

**Comment by kitaisreal** [comment]
Hello, @chenk818, I checked that we did not have support for `reinterpretAsUInt256`, `reinterpretAsInt128`, `reinterpretAsInt256`. So I added it in scope of https://github.com/ClickHouse/ClickHouse/pull/19858.
When it will be merged, this functions can be used for this task.

```
SELECT reinterpretAsUInt256(hash), sipHash128('test') as hash
```

```
┌─reinterpretAsUInt256(sipHash128('test'))─┬─hash──────┐
│  131866609359808026049277560554463445382 │ �A��	�e^�Ѐ?͕4c │
└──────────────────────────────────────────┴───────────┘
```

**Comment by chenk818** [comment]
> Hello, @chenk818, I checked that we did not have support for `reinterpretAsUInt256`, `reinterpretAsInt128`, `reinterpretAsInt256`. So I added it in scope of #19858.
> When it will be merged, this functions can be used for this task.
> 
> ```
> SELECT reinterpretAsUInt256(hash), sipHash128('test') as hash
> ```
> 
> ```
> ┌─reinterpretAsUInt256(sipHash128('test'))─┬─hash──────┐
> │  131866609359808026049277560554463445382 │ �A��	�e^�Ѐ?͕4c │
> └──────────────────────────────────────────┴───────────┘
> ```

thx
