### ISSUE TITLE
What action caused code 24 and code 226 errors?

### ISSUE THREAD

**Issue by playcode001** [ClickHouse/ClickHouse#19705]
What action caused code 24 and code 226 errors?

2021.01.27 13:21:59.718256 [ 26522 ] {0a71f8b0-00e2-4c7a-9efd-430a2ca873f4} <Error> DynamicQueryHandler: Code: 24, e.displayText() = DB::Exception: Cannot write to ostream at offset 8388608: While executing TabSeparatedRowOutputFormat, Stack trace (when copying this message, always include the lines below):

DB::MergeTreeData::loadDataParts(bool)::(anonymous class)::operator()() const: Code: 226, e.displayText() = DB::Exception: Marks file '/var/lib/clickhouse/store/ef5/ef5c0a8e-fa7c-44f8-b6fc-f969e1197808/202012_702       1_7902_35/written_bytes.mrk2' doesn't exist, Stack trace (when copying this message, always include the lines below):

**Comment by qoega** [comment]
>when copying this message, always include the lines below

**Comment by playcode001** [comment]
@qoega  sorry!
2021.01.27 13:21:59.718256 [ 26522 ] {0a71f8b0-00e2-4c7a-9efd-430a2ca873f4} <Error> DynamicQueryHandler: Code: 24, e.displayText() = DB::Exception: Cannot write to ostream at offset 8388608: While executing TabSeparatedRowOutputFormat, Stack trace (when copying this message, always include the lines below):

0. DB::WriteBufferFromOStream::nextImpl() @ 0x9a8e4d0 in /usr/bin/clickhouse
1. DB::WriteBufferFromHTTPServerResponse::nextImpl() @ 0xe2d9e77 in /usr/bin/clickhouse
2. DB::WriteBuffer::write(char const*, unsigned long) @ 0x7b4d3ce in /usr/bin/clickhouse
3. DB::CompressedWriteBuffer::nextImpl() @ 0xd429369 in /usr/bin/clickhouse
4. DB::IOutputFormat::flush() @ 0xe3a8d75 in /usr/bin/clickhouse
5. DB::IOutputFormat::work() @ 0xe3a8cca in /usr/bin/clickhouse
6. ? @ 0xe39d37c in /usr/bin/clickhouse
7. DB::PipelineExecutor::executeStepImpl(unsigned long, unsigned long, std::__1::atomic<bool>*) @ 0xe39a4a7 in /usr/bin/clickhouse
8. ? @ 0xe39f455 in /usr/bin/clickhouse
9. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x7b7293d in /usr/bin/clickhouse
10. ? @ 0x7b76463 in /usr/bin/clickhouse
11. start_thread @ 0x7dc5 in /usr/lib64/libpthread-2.17.so
12. __clone @ 0xf776d in /usr/lib64/libc-2.17.so
 (version 20.11.4.13 (official build))
2021.01.27 13:21:59.718426 [ 26522 ] {0a71f8b0-00e2-4c7a-9efd-430a2ca873f4} <Error> DynamicQueryHandler: Cannot send exception to client: Code: 24, e.displayText() = DB::Exception: Cannot write to ostream at offset 7340422, Stack trace (when copying this message, always include the lines below):

0. DB::WriteBufferFromOStream::nextImpl() @ 0x9a8e4d0 in /usr/bin/clickhouse
1. DB::WriteBufferFromHTTPServerResponse::nextImpl() @ 0xe2d9e77 in /usr/bin/clickhouse
2. DB::HTTPHandler::trySendExceptionToClient(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&, DB::HTTPHandler::Output&) @ 0xe2ca334 in /usr/bin/clickhouse
3. DB::HTTPHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&) @ 0xe2cb347 in /usr/bin/clickhouse
4. Poco::Net::HTTPServerConnection::run() @ 0x10a76365 in /usr/bin/clickhouse
5. Poco::Net::TCPServerConnection::start() @ 0x10aac89f in /usr/bin/clickhouse
6. Poco::Net::TCPServerDispatcher::run() @ 0x10aae2ae in /usr/bin/clickhouse
7. Poco::PooledThread::run() @ 0x10bdb499 in /usr/bin/clickhouse
8. Poco::ThreadImpl::runnableEntry(void*) @ 0x10bd742a in /usr/bin/clickhouse
9. start_thread @ 0x7dc5 in /usr/lib64/libpthread-2.17.so
10. __clone @ 0xf776d in /usr/lib64/libc-2.17.so
 (version 20.11.4.13 (official build))

**Comment by playcode001** [comment]
2021.01.27 10:44:16.109244 [ 23564 ] {} <Warning> Access(local directory): File /mnt/ch/clickhouse/access/users.list doesn't exist
2021.01.27 10:44:16.109268 [ 23564 ] {} <Warning> Access(local directory): Recovering lists in directory /mnt/ch/clickhouse/access/
2021.01.27 10:44:16.165005 [ 23635 ] {} <Warning> system.query_thread_log (ef5c0a8e-fa7c-44f8-b6fc-f969e1197808): Checksums for part 202012_93_5827_42 not found. Will calculate them from data on disk.
2021.01.27 10:44:16.165136 [ 23632 ] {} <Warning> system.query_thread_log (ef5c0a8e-fa7c-44f8-b6fc-f969e1197808): Checksums for part 202012_8158_8223_10 not found. Will calculate them from data on disk.
2021.01.27 10:44:16.165664 [ 23633 ] {} <Warning> system.query_thread_log (ef5c0a8e-fa7c-44f8-b6fc-f969e1197808): Checksums for part 202012_5828_7020_242 not found. Will calculate them from data on disk.
2021.01.27 10:44:16.167455 [ 23630 ] {} <Warning> system.query_thread_log (ef5c0a8e-fa7c-44f8-b6fc-f969e1197808): Checksums for part 202012_7021_7902_35 not found. Will calculate them from data on disk.
2021.01.27 10:44:16.174013 [ 23636 ] {} <Error> auto DB::MergeTreeData::loadDataParts(bool)::(anonymous class)::operator()() const: Code: 226, e.displayText() = DB::Exception: No columns.txt in part 202011_92_92_0, Stack trace (when copying this message, always include the lines below):

0. DB::IMergeTreeDataPart::loadColumns(bool) @ 0xe078fc0 in /usr/bin/clickhouse
1. ? @ 0xe0e20a3 in /usr/bin/clickhouse
2. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0x7b7547d in /usr/bin/clickhouse
3. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()&&...)::'lambda'()::operator()() @ 0x7b779df in /usr/bin/clickhouse
4. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x7b7293d in /usr/bin/clickhouse
5. ? @ 0x7b76463 in /usr/bin/clickhouse
6. start_thread @ 0x7dc5 in /usr/lib64/libpthread-2.17.so
7. __clone @ 0xf776d in /usr/lib64/libc-2.17.so
 (version 20.11.4.13 (official build))
2021.01.27 10:44:16.174083 [ 23636 ] {} <Error> system.query_thread_log (ef5c0a8e-fa7c-44f8-b6fc-f969e1197808): Considering to remove broken part /var/lib/clickhouse/store/ef5/ef5c0a8e-fa7c-44f8-b6fc-f969e1197808/202011_92_92_0 because it's impossible to repair.
2021.01.27 10:44:16.182677 [ 23633 ] {} <Error> auto DB::MergeTreeData::loadDataParts(bool)::(anonymous class)::operator()() const: Code: 226, e.displayText() = DB::Exception: Marks file '/var/lib/clickhouse/store/ef5/ef5c0a8e-fa7c-44f8-b6fc-f969e1197808/202012_5828_7020_242/client_version_minor.mrk2' doesn't exist, Stack trace (when copying this message, always include the lines below):

0. DB::MergeTreeDataPartWide::loadIndexGranularity() @ 0xe131ee3 in /usr/bin/clickhouse
1. ? @ 0xe0e20b7 in /usr/bin/clickhouse
2. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0x7b7547d in /usr/bin/clickhouse
3. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()&&...)::'lambda'()::operator()() @ 0x7b779df in /usr/bin/clickhouse
4. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x7b7293d in /usr/bin/clickhouse
5. ? @ 0x7b76463 in /usr/bin/clickhouse
6. start_thread @ 0x7dc5 in /usr/lib64/libpthread-2.17.so
7. __clone @ 0xf776d in /usr/lib64/libc-2.17.so
 (version 20.11.4.13 (official build))

**Comment by playcode001** [comment]
2021.01.27 10:44:16.109244 [ 23564 ] {} <Warning> Access(local directory): File /mnt/ch/clickhouse/access/users.list doesn't exist
2021.01.27 10:44:16.109268 [ 23564 ] {} <Warning> Access(local directory): Recovering lists in directory /mnt/ch/clickhouse/access/
2021.01.27 10:44:16.165005 [ 23635 ] {} <Warning> system.query_thread_log (ef5c0a8e-fa7c-44f8-b6fc-f969e1197808): Checksums for part 202012_93_5827_42 not found. Will calculate them from data on disk.
2021.01.27 10:44:16.165136 [ 23632 ] {} <Warning> system.query_thread_log (ef5c0a8e-fa7c-44f8-b6fc-f969e1197808): Checksums for part 202012_8158_8223_10 not found. Will calculate them from data on disk.
2021.01.27 10:44:16.165664 [ 23633 ] {} <Warning> system.query_thread_log (ef5c0a8e-fa7c-44f8-b6fc-f969e1197808): Checksums for part 202012_5828_7020_242 not found. Will calculate them from data on disk.
2021.01.27 10:44:16.167455 [ 23630 ] {} <Warning> system.query_thread_log (ef5c0a8e-fa7c-44f8-b6fc-f969e1197808): Checksums for part 202012_7021_7902_35 not found. Will calculate them from data on disk.
2021.01.27 10:44:16.174013 [ 23636 ] {} <Error> auto DB::MergeTreeData::loadDataParts(bool)::(anonymous class)::operator()() const: Code: 226, e.displayText() = DB::Exception: No columns.txt in part 202011_92_92_0, Stack trace (when copying this message, always include the lines below):

0. DB::IMergeTreeDataPart::loadColumns(bool) @ 0xe078fc0 in /usr/bin/clickhouse
1. ? @ 0xe0e20a3 in /usr/bin/clickhouse
2. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0x7b7547d in /usr/bin/clickhouse
3. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()&&...)::'lambda'()::operator()() @ 0x7b779df in /usr/bin/clickhouse
4. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x7b7293d in /usr/bin/clickhouse
5. ? @ 0x7b76463 in /usr/bin/clickhouse
6. start_thread @ 0x7dc5 in /usr/lib64/libpthread-2.17.so
7. __clone @ 0xf776d in /usr/lib64/libc-2.17.so
 (version 20.11.4.13 (official build))
2021.01.27 10:44:16.174083 [ 23636 ] {} <Error> system.query_thread_log (ef5c0a8e-fa7c-44f8-b6fc-f969e1197808): Considering to remove broken part /var/lib/clickhouse/store/ef5/ef5c0a8e-fa7c-44f8-b6fc-f969e1197808/202011_92_92_0 because it's impossible to repair.
2021.01.27 10:44:16.182677 [ 23633 ] {} <Error> auto DB::MergeTreeData::loadDataParts(bool)::(anonymous class)::operator()() const: Code: 226, e.displayText() = DB::Exception: Marks file '/var/lib/clickhouse/store/ef5/ef5c0a8e-fa7c-44f8-b6fc-f969e1197808/202012_5828_7020_242/client_version_minor.mrk2' doesn't exist, Stack trace (when copying this message, always include the lines below):

0. DB::MergeTreeDataPartWide::loadIndexGranularity() @ 0xe131ee3 in /usr/bin/clickhouse
1. ? @ 0xe0e20b7 in /usr/bin/clickhouse
2. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0x7b7547d in /usr/bin/clickhouse
3. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()&&...)::'lambda'()::operator()() @ 0x7b779df in /usr/bin/clickhouse
4. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x7b7293d in /usr/bin/clickhouse
5. ? @ 0x7b76463 in /usr/bin/clickhouse
6. start_thread @ 0x7dc5 in /usr/lib64/libpthread-2.17.so
7. __clone @ 0xf776d in /usr/lib64/libc-2.17.so
 (version 20.11.4.13 (official build))

**Comment by alexey-milovidov** [comment]
> 2021.01.27 13:21:59.718256 [ 26522 ] {0a71f8b0-00e2-4c7a-9efd-430a2ca873f4} DynamicQueryHandler: Code: 24, e.displayText() = DB::Exception: Cannot write to ostream at offset 8388608: While executing TabSeparatedRowOutputFormat

Cannot send query result to the client. When sending data, client disconnected.

**Comment by alexey-milovidov** [comment]
> DB::MergeTreeData::loadDataParts(bool)::(anonymous class)::operator()() const: Code: 226, e.displayText() = DB::Exception: Marks file '/var/lib/clickhouse/store/ef5/ef5c0a8e-fa7c-44f8-b6fc-f969e1197808/202012_702 1_7902_35/written_bytes.mrk2' doesn't exist

Non-replicated MergeTree table (system.query_log) was restored after restart, broken data parts were found.
