### ISSUE TITLE
About GROUP BY, time and RAM

### ISSUE THREAD

**Issue by kuraga** [ClickHouse/ClickHouse#19709]
Good day!

I have a question about ClickHouse's GROUP BY, time and RAM.

My triplet-index-`GROUP BY`-to-`Memory`-table query on 150 GB (original CSV size), 2 billion rows takes 3 minutes and eats 300GB RAM.

Changing this query to to-`MergeTree`table and applying `max_bytes_before_external_group_by` I could decrease RAM usage to 120 GB. But not less as it becomes a failure.

As for the time it varies from 3 minutes up to 2 hours because
1) I can vary input table structure;
2) I can vary output table structure;
3) (maybe) I can omtimize the query.

BTW, exporting to CSV is fast: 20 minutes!
And I see that there are many combination of that two structures. And I can't guess **right** which combination will be faster.

So I have two questions:
1. Can I decrease memory usage significantly?
2. Which is a right way for `GROUP BY` pipeline?
Could time vary so significantly? Because I thought:
`time of GROUP BY for random-structure table = time to convert table to the correct structure + time of GROUP BY for correct-structure table`. But I don't see it...

Thanks very much!

**Comment by alexey-milovidov** [comment]
> Can I decrease memory usage significantly?

Yes, just enable `max_bytes_before_external_group_by`, see https://clickhouse.tech/docs/en/sql-reference/statements/select/group-by/#select-group-by-in-external-memory

**Comment by alexey-milovidov** [comment]
> Could time vary so significantly?

As you told, you have different queries on tables with different table structure - the answer is yes.

**Comment by alexey-milovidov** [comment]
Also worth to note that Memory tables not always improve performance over MergeTree tables - the best option is to start with MergeTree tables.

**Comment by kuraga** [comment]
> > Can I decrease memory usage significantly?
> 
> Yes, just enable `max_bytes_before_external_group_by`, see https://clickhouse.tech/docs/en/sql-reference/statements/select/group-by/#select-group-by-in-external-memory

Hm, as I already wrote above I've tried it.

**Comment by alexey-milovidov** [comment]
Also you can lower the `aggregation_memory_efficient_merge_threads` - it will give a tradeoff between speed and memory usage.

**Comment by kuraga** [comment]
> Also you can lower the `aggregation_memory_efficient_merge_threads` - it will give a tradeoff between speed and memory usage.

Yes, it works! Thanks.

**Comment by kuraga** [comment]
@alexey-milovidov ,

> Maybe you can provide more details?

```sql
CREATE TABLE InputTable
(
  ts DateTime('Europe/Moscow'),
  zid1 UInt32,
  zid2 UInt32,
  i1 UInt32,
  i2 UInt32,
  ...
)
ENGINE = AggregatingMergeTree()
ORDER BY (ts, zid1, zid2)
SAMPLE BY (ts, zid1, zid2);
```

```sql
CREATE TABLE Aggregated
(
  ts DateTime('Europe/Moscow'),
  zid1 UInt32,
  zid2 UInt32,
  i1Sum UInt32,
  i2Sum UInt32,
  ...
)
ENGINE = MergeTree()
ORDER BY (ts, zid1, zid2)
SAMPLE BY (ts, zid1, zid2);
```

```sql
INSERT INTO Aggregated
  SELECT ts, zid, home_zid,
      sum(i1) AS i1Sum, sum(i2) AS i2Sum, ...
  FROM InputTable
  GROUP BY ts, zid1, zid2;
```

`(ts, zid1)` pairs set is dense. `(zid1, zid2)` pairs set is more sparse.

Say, please:
1. Are table structures correct for this query? Could they differ?
2. I see that `SELECT ... INTO OUTFILE` query is significantly quicker. Why? Is it because `MergeTree` indexes/orders rows?

Thanks very much!

**Comment by den-crane** [comment]
>ENGINE = AggregatingMergeTree()
>ORDER BY (ts, zid1, zid2)
>SAMPLE BY (ts, zid1, zid2);


1. ENGINE = AggregatingMergeTree() -- AggregatingMergeTree must used only with AggregateFunctions or SimpleAggregateFunctions.

2. ORDER BY (ts, zid1, zid2) -- mostly you should never place high-cardinality column (ts) as leading in the Primary-Key index.
   probably it should be ORDER BY (zid1, zid2, ts) 

3. SAMPLE BY (ts, zid1, zid2) -- completely wrong. Sample must cover all space of possible values. Usually you can user some hash function like cityHash64( ts, zid1, zid2 ), but in your case SAMPLING is unusable because you have high-cardinality columns in the Primary-Key index.
I would recommend to remove SAMPLE BY section.

4.  ` sum(i1) AS i1Sum` , I think you need to use SummingMergeTree instead of AggregatingMergeTree. SummingMergeTree sums automatically all numeric columns which are not the members of ORDER_BY section.


>I see that SELECT ... INTO OUTFILE query is significantly quicker. Why? Is it because MergeTree indexes/orders rows?

Clickhouse spends a lot of resources on the insert, + mixed reading & writing on the same storage messes with each other.

**Comment by kuraga** [comment]
> 2. ORDER BY (ts, zid1, zid2) -- mostly you should never place high-cardinality column (ts) as leading in the Primary-Key index.
>    probably it should be ORDER BY (zid1, zid2, ts)

@den-crane , where could I read about it?

1 - Thanks!
4 - Ahh... Sure.
3 - Thanks, will re-read in documentation.
