### ISSUE TITLE
How do array fields merge

### ISSUE THREAD

**Issue by loovia** [ClickHouse/ClickHouse#19737]
desc table:
```
┌─name───┬─type─────┬
│ labelname  │ String              │
│ labelvalue  │ String              │
│ uv               │ Array(UInt64) │
└───────┴──────────
```
data example:
```
dc-ch-34 :) select labelname,labelvalue,uv from rp_gene_user_array;

SELECT 
    labelname,
    labelvalue,
    uv
FROM rp_gene_user_array

┌─labelname──┬─labelvalue─┬─uv──────┐
│ active_tag │ value      │ [4,5,6] │
└────────────┴────────────┴─────────┘
┌─labelname──┬─labelvalue─┬─uv──────┐
│ active_tag │ value      │ [1,2,3] │
└────────────┴────────────┴─────────┘
```
I want to get `active_tag | value | [1,2,3,4,5,6]` and use `select labelname, labelvalue, groupArray(arrayJoin(uv)) as uv from rp_gene_user_array group by labelname, labelvalue;` can merge `uv` field and it's what i want. 
However, when computing large amounts of data(about 1 billion), the memory limit will be exceeded. I set `distributed_aggregation_memory_efficient = 1`.

Is there a better function or optimization parameter that can be used?

**Comment by den-crane** [comment]
groupArrayArray
``` sql
select a,b, groupArrayArray(arr) from
(
select 'active_tag' a , 'value' b , [4,5,6]  arr
union all
select 'active_tag' a , 'value' b , [1,2,3]  arr
) x
group by a,b

┌─a──────────┬─b─────┬─groupArrayArray(arr)─┐
│ active_tag │ value │ [4,5,6,1,2,3]        │
└────────────┴───────┴──────────────────────┘
```

**Comment by loovia** [comment]
@den-crane thanks.
maybe my data length is too large and return error: `DB::Exception: Too large array size: While executing SourceFromNativeStream. 
`. 
What parameter settings can be change max length of the array

**Comment by alexey-milovidov** [comment]
It is the hard limit on Array size (one billion if I recall correctly). If you face dealing with arrays of this size *in a single value* you have to split them.
