### ISSUE TITLE
Ability to specify which tables to be replicated in MaterializeMySQL engine

### ISSUE THREAD

**Issue by sliontc** [ClickHouse/ClickHouse#19745]
A new feature is requested.

**Use case**
When using MaterializeMySQL engine to sync MySQL database, it always occured that new tables were added which didn't have primary key or some unsupported data type were defined. All these will stop MaterializeMySQL working.

**Describe the solution you'd like**
Maybe a new feature could be considered that we could include or exclude the specified tables when create MaterializeMySQL.
Something like this:
CREATE DATABASE [IF NOT EXISTS] db_name [ON CLUSTER cluster]
ENGINE = MaterializeMySQL('host:port', database('table1','table3'), 'user', 'password') [SETTINGS ...]

**Comment by stigsb** [comment]
I think a good solution would be to mirror the table replication filters in mysql as MaterializeMySQL database settings, for example:

```
SETTINGS
    replicate_do_table = 'tbl list',
    replicate_ignore_table = 'tbl list',
    replicate_wild_do_table = 'wild tbl list',
    replicate_wild_ignore_table = 'wild tbl list'
```

These settings would be immutable, you can not change them once the database is created.

Any thoughts @zhang2014 ?

**Comment by zhang2014** [comment]
Maybe consider the following DDL:
```
ALTER DATABASE `db_name` STOP REPLICATE;
ALTER DATABASE `db_name` START REPLICATE; 
ALTER DATABASE `db_name` RESTART REPLICATE; 
ALTER DATABASE `db_name` ADD IGNORE TABLES `table_name` | (`table_name_1`, `table_name_2`);
```

**Comment by sliontc** [comment]
Did you guys mean it's already available or future plan?

**Comment by poweroftrue** [comment]
So, there's a quick and hacky workaround to this, simply revoke the read all privileges:
```
# Please make sure this is a different user than your app's main user 
# This will stop the user from reading any table
REVOKE SELECT ON *.* FROM clickhouse@'%'
```

Then give Clickhouse MySQL select privilege on the table you want to replicate:
```
GRANT SELECT ON db.table1 TO 'clickhouse'@'%';
GRANT SELECT ON db.table2 TO 'clickhouse'@'%';
```

This way on the initial dump Clickhouse will only see the tables you selected.

If you have a long list of tables (like my case) you can use this query to generate the command for you, selecting all tables except a few:
```
# table1 and table2 will be ignored
SELECT 
    CONCAT('GRANT SELECT ON ',
            table_name,
            ' to 
                clickhouse@\'%\';') AS commands
FROM
    information_schema.tables
WHERE
    table_schema = 'database_name'
        AND table_name NOT IN ('table1' , 'table2');
```
Then: 
```
FLUSH PRIVILEGES;
```

Now you can run the MaterializeMySQL create database statement. 


After testing, this will sadly only help you get the data from custom tables into Clickhouse, reading bin logs will break the replication and throw table not found errors.

I thought `detach database` and then `attach database` will help resume the replication but it did not. So, this is only helpful to load data once and then you have to drop the database and do it all over again until the feature to select custom tables is out.

**Comment by poweroftrue** [comment]
Oh, I just found `materialized_postgresql_tables_list` in MaterializedPostgreSQL, I think for consistency we can implement something like it?
