### ISSUE TITLE
Whether the parts of the same partition is a concurrent merge? 

### ISSUE THREAD

**Issue by Sallery-X** [ClickHouse/ClickHouse#19744]

**Comment by alexey-milovidov** [comment]
Non overlapping ranges of data parts in the same partition can be merged concurrently.

**Comment by Sallery-X** [comment]
> Non overlapping ranges of data parts in the same partition can be merged concurrently.


Which function is the specific code of concurrent merge? 

right here？

void BackgroundProcessingPool::startTask(const TaskHandle & task, bool allow_execute_in_parallel)
{
    Poco::Timestamp current_time;

    task->allow_execute_in_parallel = allow_execute_in_parallel;

    {
        std::unique_lock lock(tasks_mutex);
        task->iterator = tasks.emplace(current_time, task);

        wake_event.notify_all();
    }

}

**Comment by alexey-milovidov** [comment]
Yes, also search for `background_pool_size` and its usages.
