### ISSUE TITLE
 Concurrently write to different replicas of the same shard, how to prevent the newly generated part file from conflicting with each other

### ISSUE THREAD

**Issue by Sallery-X** [ClickHouse/ClickHouse#19747]

**Comment by Sallery-X** [comment]
include the part name，metadata and part cache

**Comment by alexey-milovidov** [comment]
Part name includes the block number that is synchronized with ZooKeeper.

**Comment by Sallery-X** [comment]
> Part name includes the block number that is synchronized with ZooKeeper and guaranteed to be distinct for distinct parts.

Concurrently write to different replicas of the same shard，The tmp directory is likely to be duplicated？

**Comment by alexey-milovidov** [comment]
tmp directory is local on each replica.
