### ISSUE TITLE
MATERIALIZED VIEW inconsistency of data

### ISSUE THREAD

**Issue by ClownfishYang** [ClickHouse/ClickHouse#19749]
This is the table I used for testing.
```
CREATE TABLE test_1
(
	`UUID` String,
	`v1` String,
	`v2` Float32
)
ENGINE = MergeTree()
ORDER BY (UUID)
SETTINGS index_granularity = 8192;

CREATE MATERIALIZED VIEW test_2
ENGINE = AggregatingMergeTree() ORDER BY (UUID) AS 
SELECT UUID, toFloat32(v1) / v2 AS v3 FROM test_1
```

Now I'm going to start inserting data.
```
set send_logs_level='debug';
INSERT INTO test_1 VALUES('id1', '1', 2);
-- error
INSERT INTO test_1 VALUES('id2', '1A', 2);
-- error
INSERT INTO test_1 VALUES('id3', '1B', 2);
INSERT INTO test_1 VALUES('id4', '2', 2);
-- error
INSERT INTO test_1 VALUES('id5', '2a', 2);

SELECT * FROM test_1;
┌─UUID─┬─v1─┬─v2─┐
│ id1  │ 1  │  2 │
│ id2  │ 1A │  2 │
│ id3  │ 1B │  2 │
│ id4  │ 2  │  2 │
│ id5  │ 2a │  2 │
└──────┴────┴────┘

SELECT * FROM test_2;
┌─UUID─┬──v3─┐
│ id1  │ 0.5 │
└──────┴─────┘
┌─UUID─┬─v3─┐
│ id4  │  1 │
└──────┴────┘
```
The insert statement returns' parse string error 'when inserting data from id2, id3, and id5, but in fact the data has been successfully inserted into table' test_1 'and is reported to me due to the failure of table' test_2 '.
I don't understand how the time 'test_2' works. If the time is synchronous, then the table 'test_1' should not succeed. If the time is asynchronous, this error report should not be reported to me.

PS:I need to use materialized views to aggregate the data, but some of the data will fail due to excessive memory usage. This logic is now done with `Spark`, but it will cause a lot of extra tasks.

**Comment by den-crane** [comment]
MATERIALIZED VIEW is an insert trigger.
But CH does not have transactions / atomicity in Table -> Materialized View.

1. client sends `INSERT INTO test_1 VALUES('id2', '1A', 2);`
2. INSERT handler gets inserted buffer
3. **INSERT handler ** triggers MATERIALIZED VIEW test_2 
4. table test_1 writes inserted buffer
5. MATERIALIZED VIEW fails to parse inserted buffer
6. INSERT handler reports the error to the client.

**Comment by ClownfishYang** [comment]
> MATERIALIZED VIEW is an insert trigger.
> But CH does not have transactions / atomicity in Table -> Materialized View.
> 
> 1. client sends `INSERT INTO test_1 VALUES('id2', '1A', 2);`
> 2. INSERT handler gets an inserted buffer
> 3. INSERT handler writes the inserted buffer into table test_1
> 4. **INSERT handler** triggers MATERIALIZED VIEW test_2
> 5. MATERIALIZED VIEW fails to parse inserted buffer
> 6. INSERT handler reports the error to the client.

Thank you for your reply, which is exactly what I expected.
For my initial purpose is materialized views to the use of the decoupling, in does not affect I ` t1 ` insert, can automatically generate ` t2 ` data again at the same time, this should be an asynchronous process, in the concept of similar ` Oracle ` also is such, now this way seems only a small portion of the program logic to CH, but my application still need to wait for its completion, influenced me write speed, then all done by the program to be better than this, what do you think?

**Comment by den-crane** [comment]
Do not really understand what is the problem
Just do not use MV? Insert into both tables from a client ?
