### ISSUE TITLE
Suspected bug in ColumnArray::updatePermutation method

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#19756]
**Describe the bug**
https://clickhouse-test-reports.s3.yandex.net/19702/c74631c650b42e4d107254a03bd82c2c2913039b/fuzzer_msan/server.log

Most likely introduced here: #11006

**Comment by CurtizJ** [comment]
Minimal repro:

```sql
SELECT
    number
    FROM numbers(256)
    ORDER BY
        arrayFilter(x -> materialize(255), ['257']) ASC
    LIMIT 10
```
