### ISSUE TITLE
Multiple issues in JOIN with dictionary.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#19754]
Found by fuzzer:

1. https://clickhouse-test-reports.s3.yandex.net/19588/065d22cf2b8b259e157a72ccc9da56a0a8c7f5c1/fuzzer_msan/server.log
2. https://clickhouse-test-reports.s3.yandex.net/19588/065d22cf2b8b259e157a72ccc9da56a0a8c7f5c1/fuzzer_asan/server.log
3. https://clickhouse-test-reports.s3.yandex.net/20047/c59f22d7b4823875a4d5f021329b05be81a1fd69/fuzzer_ubsan/server.log
4. https://clickhouse-test-reports.s3.yandex.net/20472/5bdc57004682a5e0236ec630546d20ad752c2fde/fuzzer_asan/server.log

Most likely caused by block structure mismatch.

**Comment by alexey-milovidov** [comment]
https://clickhouse-test-reports.s3.yandex.net/20472/5bdc57004682a5e0236ec630546d20ad752c2fde/fuzzer_asan/server.log

**Comment by alexey-milovidov** [comment]
See also https://github.com/ClickHouse/ClickHouse/issues/23002

**Comment by vdimir** [comment]
Related https://github.com/ClickHouse/ClickHouse/issues/21619
