### ISSUE TITLE
SUM(col) / SUM(SUM(col)) OVER (PARTITION BY col2) aggregate function over WINDOW is not supported.

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#19857]
**How to reproduce**

```
SELECT sum(number) / sum(sum(number)) OVER (PARTITION BY (number % 10))
FROM numbers(10000)
GROUP BY number % 10

Query id: 76ed1093-b378-45c2-b644-1de44783734a


0 rows in set. Elapsed: 0.003 sec.

Received exception from server (version 21.2.1):
Code: 47. DB::Exception: Received from localhost:9000. DB::Exception: Unknown identifier: sum(sum(number)) OVER (PARTITION BY number % 10) there are columns: modulo(number, 10), sum(number): While processing sum(number) / sum(sum(number)) OVER (PARTITION BY (number % 10)).



postgres=# SELECT sum(generate_series) / sum(sum(generate_series))  OVER (PARTITION BY (generate_series % 10)) FROM generate_series(0,10000) GROUP BY generate_series % 10;
        ?column?
------------------------
 1.00000000000000000000
 1.00000000000000000000
 1.00000000000000000000
 1.00000000000000000000
 1.00000000000000000000
 1.00000000000000000000
 1.00000000000000000000
 1.00000000000000000000
 1.00000000000000000000
 1.00000000000000000000
(10 rows)

**Expected behavior**
Query works

**Comment by akuzm** [comment]
This is expected for now -- the window functions are processed at the latest stage of the query execution, so we can't calculate any expressions with them, and have to use a subselect.
Proper support for this will be complicated: we'll have to account for window functions in `ActionsDAG`, then split it into alternating `WindowStep` and `ExpressionStep` instances.

**Comment by akuzm** [comment]
Not actively working on this ATM.

**Comment by akuzm** [comment]
By the way, it is going to be simpler to implement than I tought. Window functions can't be inside other window functions, so we can always topo-sort the execution graph into three parts:

1. Base expressions w/o window functions
2. Window functions that reference the base expressions
3. Expressions that reference window functions

This means we'll need at most ExpressionStep + WindowStep + ExpressionStep.

**Comment by alexey-milovidov** [comment]
I need this :wink:

**Comment by jahilliard** [comment]
I want this too! 🤤 We used this pattern all the time at FB.

**Comment by Alpha-su** [comment]
So where is the hard part, I am very eager to use this new feature Otherwise I need to parse out the subquery

**Comment by SharonCastel** [comment]
Thanks @den-crane.
@novikd can you please update when this fix is going to be fixed? 
most of our queries use window function on a complex way on postgres and if this fix is not going to happen maybe I need to postpone the migration to CH.

**Comment by kilik52** [comment]
Is there a work-around for now?
I saw someone mentioned subquery, but what's the subquery version of this one👇?

```sql
SELECT sum(number) / sum(sum(number)) OVER (PARTITION BY (number % 10))
FROM numbers(10000)
GROUP BY number % 10
```

**Comment by andrea-s** [comment]
Once done, this should also enable some interesting performance boosts, I would expect, based on the availability of short circuit function evaluation. Am I right on this?

Imagine that we have a table containing two harmonized sources, a big one (let's call it web_traffic) and a small one (transactions).

Thanks to short circuiting, will this sample query perform more efficiently once it's syntactically doable in ClickHouse?

```
select
customer_id,
case
        when source = 'web_traffic' then toDate('1970-01-01')
        when source = 'transactions' then max(date) over (partition by customer_id)
        else toDate('1970-01-01')
end as last_transaction_date
from mytdb.mytable
```
Currently, one could do the following:

```
select
customer_id,
maxIf(date, source = 'transactions') over (partition by customer_id) as last_transaction_date
from mytdb.mytable
```

which is reading all rows despite the -If suffix.
