### ISSUE TITLE
(negligible) demonstration of memory growth due to infinite regexp cache.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#19869]
ClickHouse is using infinite cache for compiled regular expressions.
Hyperscan can use several megabytes per compiled regexp.
It makes infinite memory growth possible:

```
clickhouse-benchmark --query "SELECT multiFuzzyMatchAny('Hello, world', 5, ['(' || (SELECT toString(rand(1))) || '|' || (SELECT toString(rand(2))) || ')+(' || (SELECT toString(rand(3))) || '|' || (SELECT toString(rand(4))) || ')+(' || (SELECT toString(rand(5))) || ')+'])"
```

Possible solutions:
- simply drop cache if its size is 1000 entries;
- replace to LRU cache with 1000 entries.

**Comment by rschu1ze** [comment]
In PR #37544, I replaced the space-unbounded global cache for re2 regexps with a space-limited local cache. The cache for hyper/vectorscan regexps may still grow unlimited ... will fix that.
