### ISSUE TITLE
Altering Enum in ordering key doesn't work on ReplicatedMergeTree

### ISSUE THREAD

**Issue by Blackmorse** [ClickHouse/ClickHouse#19878]
**Describe the bug**
Reproduces at 20.8.12.2 Clickhouse version.

```
CREATE TABLE t ON CLUSTER replicated
(
    `a` UInt64,
    `b` Enum8('a' = 1, 'b' = 2)
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/default/{shard}/t', '{replica}')
ORDER BY (b, a)

INSERT INTO t VALUES (1,1),(2,2)

ALTER TABLE t ON CLUSTER replicated MODIFY COLUMN b Enum8('a' = 1)
```
The last statement falls into error: `Cannot execute replicated DDL query, maximum retires exceeded`

In case of local alter: 
`ALTER TABLE t ON CLUSTER replicated MODIFY COLUMN b Enum8('a' = 1)`

the error is next:
```
Received exception from server (version 20.8.12):
Code: 524. DB::Exception: Received from localhost:9100. DB::Exception: ALTER of key column b from type Enum8('a' = 1, 'b' = 2) to type Enum8('a' = 1) must be metadata-only.
```

**Expected behavior**
The same as on non-Replicated MergeTree

**Comment by alesapin** [comment]
Hi!

Alter of the key columns in ClickHouse is quite limited. You can alter enums but only add new values. Removing old values can change the representation of the primary key. 
```
:) ALTER TABLE t
    MODIFY COLUMN `b` Enum8('a' = 1)

Received exception from server (version 21.2.1):
Code: 524. DB::Exception: Received from localhost:9000. DB::Exception: ALTER of key column b from type Enum8('a' = 1, 'b' = 2) to type Enum8('a' = 1) is not safe because it can change the representation of primary key. 
```
but the extension is allowed:
```

ALTER TABLE t
    MODIFY COLUMN `b` Enum8('a' = 1, 'b' = 2, 'c' = 3)

Ok.

```

**Comment by alexey-milovidov** [comment]
> The same as on non-Replicated MergeTree

But how it's related to Replicated / non-Replicated MergeTree?

**Comment by Blackmorse** [comment]
@alesapin , 

>  You can alter enums but only add new values

But documentation says:

> The Enum type can be changed without cost using ALTER, if only the set of values is changed. It is possible to both add and remove members of the Enum using ALTER (removing is safe only if the removed value has never been used in the table)

**Comment by Blackmorse** [comment]
@alexey-milovidov 

> But how it's related to Replicated / non-Replicated MergeTree?

Sorry, I was sure that the same operation works on simple MergeTree(). My bad

**Comment by alesapin** [comment]
> @alesapin ,
> 
> > You can alter enums but only add new values
> 
> But documentation says:
> 
> > The Enum type can be changed without cost using ALTER, if only the set of values is changed. It is possible to both add and remove members of the Enum using ALTER (removing is safe only if the removed value has never been used in the table)

As the documentation says:
`> removing is safe only if the removed value has never been used in the table`

We restrict unsafe operations for the primary key columns because it can lead not only to the single-column corruption but to the whole table became broken.

**Comment by Blackmorse** [comment]
@alesapin , So , It is correct behaviour, right?

**Comment by alesapin** [comment]
> @alesapin , So , It is correct behaviour, right?

Yes, it's expected.

**Comment by Blackmorse** [comment]
Thanks
