### ISSUE TITLE
> Part name includes the block number that is synchronized with ZooKeeper and guaranteed to be distinct for distinct parts.

### ISSUE THREAD

**Issue by Sallery-X** [ClickHouse/ClickHouse#19895]
> Part name includes the block number that is synchronized with ZooKeeper and guaranteed to be distinct for distinct parts.

Concurrently write to different replicas of the same shard，The tmp directory is likely to be duplicated？

_Originally posted by @Sallery-X in https://github.com/ClickHouse/ClickHouse/issues/19747#issuecomment-770534761_

**Comment by alexey-milovidov** [comment]
One number is used for tmp directory and another - when directory is renamed.
Only final block number is synchronized between replicas.

Temporary data parts are local and does not necessarily have distinct names on distinct replicas.
