### ISSUE TITLE
Order by on array join column failing

### ISSUE THREAD

**Issue by hlinowes** [ClickHouse/ClickHouse#19945]
**Describe the bug**
When attempting to apply a nested function (`AVG(ABS(...))`) on an `ARRAY JOIN` column with an `ORDER BY` the query fails. When removing the `ORDER BY` or adding aliasing to the `ARRAY JOIN` the query succeeds.

**How to reproduce**
* Clickhouse version: `21.1.2.15`
* Image: `docker.io/yandex/clickhouse-server:21.1.2.15`
```
CREATE TABLE temp_table
(
    category Array(String),
    score Array(Float32)
)
ENGINE = Memory();

insert into temp_table
select array('red', 'green', 'blue', 'orange'),
       array(1.2, -2.5, 1.9, 3.3)
from (select number from system.numbers limit 10);
```

Query that fails:
```
select avg(abs(t.`score`)) as `sc`, t.`category`
from temp_table as t
ARRAY JOIN t.`score`, t.`category`
GROUP BY t.`category`
ORDER BY `sc`
LIMIT 500;
```

Using aliasing in query allows it to succeed.
```
select avg(abs(array_join_alias)) as `sc`, t.`category`
from temp_table_2 as t
ARRAY JOIN t.`score` as array_join_alias, t.`category`, t.`origin`, t.`name`
GROUP BY t.`category`
ORDER BY `sc`
LIMIT 500;
```

**Expected behavior**
Expect the query to succeed listing the average of absolute values of the score column grouped by category and ordered by the avg(abs(score)).

**Error message and/or stacktrace**
When the query fails the following message is displayed:
`Exception: Illegal type Array(Float32) of argument of function abs: While processing abs(score) (version 21.1.2.15 (official build))`

**Additional context**
The issue does not seem to occur on Clickhouse version `20.6.5.8`. Not sure about other older versions but have only tested on the two mentioned in this post.

**Comment by den-crane** [comment]
You have to use aliases in this case.  `ARRAY JOIN t.`score` as array_join_alias`
Original array column is also available in select section by original `t.score` name

https://clickhouse.tech/docs/ru/sql-reference/statements/select/array-join/

**Comment by hlinowes** [comment]
It makes sense to me why the alias is useful/needed here, but I am confused why the query seems to succeed without aliasing but when the `ORDER BY` is removed. The following query succeeds:
```
select avg(abs(t.`score`)) as `sc`, t.`category`
from temp_table as t
ARRAY JOIN t.`score`, t.`category`
GROUP BY t.`category`
LIMIT 500;
```

**Comment by alexey-milovidov** [comment]
Most likely it's a bug in name resolution. We will address it in this task: #23194
