### ISSUE TITLE
[RFC] Different representation of columns. Sparse columns.

### ISSUE THREAD

**Issue by CurtizJ** [ClickHouse/ClickHouse#19953]
**Use case**
This issue describes the details of refactoring, which moves `ser/de` of columns from `IDataType` and allows to choose dynamically different representations of columns in every data part. Also it describes implementation of sparse representation on disk.
It is the prerequisite for other bigger task: to choose dynamically optimal representation (`LowCardinality`, `Sparse` or `Dense`) and codec of columns.

**Describe the solution you'd like**
The plan:

Introduce interface `ISerialization`  which will be responsible to how serialize and deserialize columns. 
Move `enumerateStreams`, `getFileNameForStream` and `serialize*/deserialize*` method to it from `IDataType` as is.
Implement them for every data type. 

Introduce methods:
- `SerializationPtr IDataType::getSerialization(const IColumn & column)`
  It will determine to which representation (sparse/dense) write column according to its content and will return appropriate `Serialization`. Can be used at inserts, when we write full column from memory.
- `SerializationPtr IDataType::getSerialization(const SerializationSettings & settings)`
 The same as above, but can be used when we don't have column in memory and know statistics about its content (number of rows, number of non-default values, etc..). Can be used for merges.
- `SeserializationPtr IDataType::getSerialization(cosnt NameAndTypePair & name_and_type, ExistenceCallback callback)`
  Used for deserialization, when we need to deterimine which serialization to use from files, written on disk. It will ask by callback existence of some files and according to this information will return appropriate `Seserialization`.

For now there will be 3 types of Serialization:
 - Default.
 - Sparse. It will write only non zero values from column using default serialization and will write separate stream with offsets for them.
 - Subcolumns. The same logic as in `DataTypeOneElementTupleStreams` now. Wraps default deserializations, but some substreams will have names like in named tuples to proper reading of subcolumns. It will be used only for deserialization. Getting it will have the same logic as `IDataType::tryGetSubcolumnType` now.

For getting all types of `Serializations` there will be the corresponding methods.

**Details of sparse serialization**

Every column in part will be written in Default or Sparse serizalition. Serialization will be chosen before reading/writing column.
Parts will store number of non-empty values for every column. During merges serializations will be chosen according to summary number of non-empty values in column among all merged parts.
For loading data parts we can store this metadata in separate file.

For first iteration in-memory column representation will be always dense. But, when some kind of `ColumnSparse` will be implemented, not much changes in code are expected.

**Comment by CurtizJ** [comment]
Maybe one `ISerialization` interface with all `serialiaze*/deserialize*` methods will be better than separate interfaces.

**Comment by filimonov** [comment]
1. The relation of compression / LowCardinality / CODEC / column representation  become more cumbersome. Would be great to have clear explanation for those. 
2. I think i don't really understand how marks for sparse column will work.
3. One more obvious option for column serialization is RLE (run length encoding) - but again not clear if the fact that is exists on compression level is enough, or it should be codec or column representation

**Comment by CurtizJ** [comment]
1. Compressions are the subset of codecs. Some of codecs do compression, but others just prepare data to achive better compression ratio by other algorithm. The difference between codec and representation is that representation has representation of column in memory, that allows to do efficiently common operations with columns (getting of single elements, sorting, permuting, etc.) and in some queries gives some advantages in RAM consumption and time of execution. So, representation has its own `IColumn` implementation.
Also It's in plans to move `LowCardinality` and `Const` to column representations.
2. It's not mentioned in this issue, but every granule will have at least one offset. If granule has only default values, this offset will be equal to granule size. So, marks will work the same as now.
3. RLE can have column implementation and be one of representations.

**Comment by UnamedRus** [comment]
About ColumnSparse

> It can reduce usage of disk space and improve performance of some queries for columns, which contain a lot of default (zero) values. 

What about Nullable columns, will default value be Null instead of zero?

**Comment by CurtizJ** [comment]
Yes, default of Nullable column is `NULL`. BTW, it's better to implement special case for sparse nullable column, because in that case null map is unneded, but it's not done yet.

**Comment by UnamedRus** [comment]
Another question about DEFAULT value.

What if user would use as default value some specific number/string/whatever.
And what will happen if user will change it to another value via ALTER TABLE MODIFY COLUMN
If it work only for zero/Null values right now, probably it can be extended in future with automatically guessing default (most occurred) value for each part / compression block.

**Comment by CurtizJ** [comment]
Defaults of old parts are materialized and during `ALTER` they won't be modified. So, if user modify default from zero/null to custom, in old parts columns, that were written in sparse serialization, will remain sparse, but new columns unlikely will be written in sparse serialization.

It's possible to support custom defaults in sparse columns and it will give some more performance improvement (e.g. in functions, that change default value), but it requires more complicated implementation, and currently it's not done yet.

**Comment by UnamedRus** [comment]
> will give some more performance improvement

Some custom aggregation/condition pipeline for default values?

```
sum(default_value*count_of_default) (+ sum(other_values))
```

Or add them for uniq functions only once.

Anyway, thank you for answers.

**Comment by CurtizJ** [comment]
Implemented in #22535.
