### ISSUE TITLE
How to decrease the number of ClickHouse operations on ZooKeeper?

### ISSUE THREAD

**Issue by gj-zhang** [ClickHouse/ClickHouse#19955]
```
java.lang.Exception: shutdown Leader! reason: zxid lower 32 bits have rolled over, forcing re-election, and therefore new epoch start
```

Is there any other way to restart ZooKeeper on a regular basis?

**Comment by alexey-milovidov** [comment]
Group INSERTs to larger batches to lower the amount of INSERT queries.

**Comment by alexey-milovidov** [comment]
Other caveats:
- useless partitioning that leads to large number of partitions;
- large number of tables with identical structure.

**Comment by gj-zhang** [comment]
> Other caveats:
> 
> * useless partitioning that leads to large number of partitions;
> * large number of tables with identical structure.
thanks
