### ISSUE TITLE
Evaluate Coverity again

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#19964]
We already did that 3 years ago: https://habr.com/en/company/yandex/blog/342018/
Also we are already using PVS-Studio and clang-tidy with Clang static analyzer in CI.

**Comment by alexey-milovidov** [comment]
```
mkdir build_coverity
cd build_coverity
CC=clang CXX=clang++ cmake -D ENABLE_CCACHE=0 ..
COVERITY_UNSUPPORTED_COMPILER_INVOCATION=1 cov-build --dir cov-int ninja clickhouse
```

**Comment by alexey-milovidov** [comment]
```
2021-02-02T06:58:25.017239Z|cov-build|2553417|info|> Build time (cov-build overall): 01:00:04.595690
2021-02-02T06:58:25.017239Z|cov-build|2553417|info|> 
2021-02-02T06:58:25.055563Z|cov-build|2553417|info|> Build time (C/C++ emits total): 16:43:25.440091
2021-02-02T06:58:25.055563Z|cov-build|2553417|info|> 
2021-02-02T06:58:25.055563Z|cov-build|2553417|info|> 
2021-02-02T06:58:25.055591Z|cov-build|2553417|info|> Emitted 8012 C/C++ compilation units (96%) successfully
2021-02-02T06:58:25.055591Z|cov-build|2553417|info|> 
2021-02-02T06:58:25.055591Z|cov-build|2553417|info|> 8089 C/C++ compilation units (96%) are ready for analysis
2021-02-02T06:58:25.055591Z|cov-build|2553417|info|> The cov-build utility completed successfully.
```

**Comment by alexey-milovidov** [comment]
```
$ du -hc cov-int
5,7G    cov-int

$ tar czvf clickhouse.tgz cov-int
```

**Comment by alexey-milovidov** [comment]
`Build successfully submitted.`

**Comment by alexey-milovidov** [comment]
#20010

**Comment by alexey-milovidov** [comment]
Analysis takes half a day.

**Comment by alexey-milovidov** [comment]
It makes sense even as the third static analyzer.

**Comment by Felixoid** [comment]
I'll see if we can use a schedule to run it once a day on `master` branch

**Comment by bkuschel** [comment]
@Felixoid Submitted a build last night, it's still analyzing this morning (8hrs so far). Incremental analysis will speed things up I suspect but requires storing the intermediate files somewhere (about 3.5G). Once done, i'll do an intermediate build to see how much it speeds up.

**Comment by Felixoid** [comment]
> requires storing the intermediate files somewhere (about 3.5G).

We can store it in S3, no problem with it

**Comment by bkuschel** [comment]
After doing a few uploads, It seems that keeping the cov analysis around doesn't give much performance benefit (if any). However one thing I did notice is the build wrapper 'cov-build' seems to slow the build down a lot, when possible an incremental build may help.

**Comment by Felixoid** [comment]
The task is done around a month ago, although it's broken because of our code

> Boris Kuschel, [05/05/2022 21:19]
> i think i found the culprit... just need to udnerstand why now.. https://github.com/ClickHouse/ClickHouse/blob/7380a713335e849f92a941e3ec1a9f46961a1176/programs/main.cpp#L358

**Comment by alexey-milovidov** [comment]
Done.
