### ISSUE TITLE
Cannot start clickhouse-server! Permission denied?

### ISSUE THREAD

**Issue by sv3t0sl4v** [ClickHouse/ClickHouse#19968]
Hi! Can't start clickhouse-server today after MySQL update. Errors I get from **sudo journalctl -u clickhouse-server** are... 

Couldn't save preprocessed config to /var/lib/clickhouse/preprocessed_configs/config.xml: Access to file denied: /var/lib/clickho
Logging trace to /var/log/clickhouse-server/clickhouse-server.log
Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
systemd[1]: clickhouse-server.service: Main process exited, code=exited, status=70/n/a
systemd[1]: clickhouse-server.service: Failed with result 'exit-code'.

/var/log/clickhouse-server/clickhouse-server.err.log says

{} <Error> Application: DB::ErrnoException: Cannot open file /var/lib/clickhouse/status, errno: 13, strerror: Permission denied

The /var/lib/clickhouse dir is symlink to /var/lib/mysql/clickhouse user clickhouse group clickhouse owns the folders. It says it is permission problem, while it is not. Trued chowning just in case with

**chown -R clickhouse:clickhouse /var/lib/clickhouse
chown -R clickhouse:clickhouse /var/lib/mysql/clickhouse**

Issue persists.

Any ideas? ClickHouse server still claims it is a permission issue, but it is not.  ClickHouse 21.1.2.15 with revision 54445,

**Comment by zhangjmruc** [comment]
You need to double check the access rights for current directory and all parent directores too.
Would you please show the output for blow commands? I suspect that issue related to mysql directories as you mentioned issue happens after MySQL update.
ll -d /var/lib
ll -d /var/lib/clickhouse
ll -d /var/lib/mysql
ll -d /var/lib/mysql/clickhouse

**Comment by sv3t0sl4v** [comment]
Thank you for your reply! Doing it even now and I am still puzzled. 

**ll -d /var/lib**
drwxr-xr-x 50 root root 4096 Jan 16 09:51 /var/lib/

**ll -d /var/lib/clickhouse**
lrwxrwxrwx 1 clickhouse clickhouse 25 Apr 11  2020 /var/lib/clickhouse -> /var/lib/mysql/clickhouse/

**ll -d /var/lib/mysql**
drwx------ 12 mysql mysql 4096 Feb  2 08:25 /var/lib/mysql/

**ll -d /var/lib/mysql/clickhouse**
drwxr-xr-x 14 clickhouse clickhouse 4096 Jan 20 18:47 /var/lib/mysql/clickhouse/

**Comment by sv3t0sl4v** [comment]
Playing with modes and access rights now. Could it be because of the symlink?

**Comment by den-crane** [comment]
You need to add read priv to all on /var/lib/mysql/

`chmod a+r /var/lib/mysql/`
