### ISSUE TITLE
Query error

### ISSUE THREAD

**Issue by always-waiting** [ClickHouse/ClickHouse#19966]
![截图_2021-02-02_14-59-22](https://user-images.githubusercontent.com/8566918/106564300-07651000-6568-11eb-96b8-c5fec20b1079.png)

When i query with that sql, err occured. But it only appeared for dt='2021-02-01' and ht from '00' to '15'. I don't know how to fix it.

Could anyone help me, please?

**Comment by zhangjmruc** [comment]
Would you please provide the create table stmt of the table rud_department_minute?

**Comment by den-crane** [comment]
First of all upgrade CH to 20.10.7.4
