### ISSUE TITLE
'ATTACH PART' after 'FREEZE' throws 'Cannot parse input'

### ISSUE THREAD

**Issue by ibradwan** [ClickHouse/ClickHouse#19982]
**Describe the bug**

***Overview***
I'm trying to take backups using disk snapshotting (provided by Azure managed disks). I first freeze the tables, then take the snapshot, then delete the `shadow` folder.

When I restore on the new machine, most of the parts are attached normally, but some of them throw this exception: 

`DB::Exception: Cannot parse input: expected 'columns format version: 1\n' at end of stream.`

When I check the those parts files, I find them empty. It makes sense to me that the above exception is thrown, given that `columns.txt` is empty.

***Logs***
The logs show that the parts that had this problem, were actually being merged into other parts while the disk snapshotting process was taking place.

The snapshotting happened around: **2/1/2021 18:26:50**.
The logs for the corrupted parts on the original machine during this time:
1. **202102_44840_44845_1**
```
2021.02.01 18:26:24.441555 [ 3592 ] {} <Trace> db.tbl_local: Created log entry /clickhouse/tables/db/tbl_local/1-2/log/log-0014128833 for merge 202102_44840_44845_1
2021.02.01 18:26:24.450236 [ 3581 ] {} <Trace> db.tbl_local: Executing log entry to merge parts 202102_44840_44840_0, 202102_44841_44841_0, 202102_44842_44842_0, 202102_44843_44843_0, 202102_44844_44844_0, 202102_44845_44845_0 to 202102_44840_44845_1
2021.02.01 18:26:24.568142 [ 3581 ] {} <Trace> db.tbl_local: Renaming temporary part tmp_merge_202102_44840_44845_1 to 202102_44840_44845_1.
2021.02.01 18:26:26.319651 [ 17413 ] {5915ab08-e1f1-4c2a-a717-019b91c05581} <Trace> db.tbl_local (SelectExecutor): Not using primary index on part 202102_44840_44845_1
2021.02.01 18:26:26.323552 [ 17413 ] {5915ab08-e1f1-4c2a-a717-019b91c05581} <Trace> MergeTreeSelectProcessor: Reading 1 ranges from part 202102_44840_44845_1, approx. 7173 rows starting from 0
2021.02.01 18:26:26.348964 [ 20087 ] {54085b6f-bd8f-4fdf-acd6-8d123c44c602} <Debug> db.tbl_local: Freezing part 202102_44840_44845_1 snapshot will be placed at shadow/backup/
2021.02.01 18:26:28.424710 [ 17413 ] {633d8d3f-0092-4d41-b9e4-09bb6b56f79e} <Trace> db.tbl_local (SelectExecutor): Not using primary index on part 202102_44840_44845_1
2021.02.01 18:26:28.428688 [ 17413 ] {633d8d3f-0092-4d41-b9e4-09bb6b56f79e} <Trace> MergeTreeSelectProcessor: Reading 1 ranges from part 202102_44840_44845_1, approx. 7173 rows starting from 0
2021.02.01 18:26:30.554802 [ 17413 ] {7afe16d6-cce3-498a-86b9-6127c7ce9971} <Trace> db.tbl_local (SelectExecutor): Not using primary index on part 202102_44840_44845_1
2021.02.01 18:26:30.558277 [ 17413 ] {7afe16d6-cce3-498a-86b9-6127c7ce9971} <Trace> MergeTreeSelectProcessor: Reading 1 ranges from part 202102_44840_44845_1, approx. 7173 rows starting from 0
2021.02.01 18:26:32.695378 [ 17413 ] {47b6ed79-73b1-4f78-af35-d35e57f17787} <Trace> db.tbl_local (SelectExecutor): Not using primary index on part 202102_44840_44845_1
2021.02.01 18:26:32.699297 [ 17413 ] {47b6ed79-73b1-4f78-af35-d35e57f17787} <Trace> MergeTreeSelectProcessor: Reading 1 ranges from part 202102_44840_44845_1, approx. 7173 rows starting from 0
2021.02.01 18:26:32.838306 [ 27778 ] {} <Trace> db.tbl_local: Executing log entry to merge parts 202102_44830_44839_2, 202102_44840_44845_1, 202102_44846_44846_0, 202102_44847_44847_0, 202102_44848_44848_0, 202102_44849_44849_0, 202102_44850_44850_0, 202102_44851_44851_0 to 202102_44830_44851_3
2021.02.01 18:26:32.842236 [ 27778 ] {} <Trace> MergeTreeSequentialSource: Reading 2 marks from part 202102_44840_44845_1, total 7173 rows starting from the beginning of the part
```

2. **202102_44830_44839_2**
```
2021.02.01 18:26:15.829780 [ 3570 ] {} <Trace> db.tbl_local: Created log entry /clickhouse/tables/db/tbl_local/1-2/log/log-0014128826 for merge 202102_44830_44839_2
2021.02.01 18:26:15.840304 [ 16326 ] {} <Trace> db.tbl_local: Executing log entry to merge parts 202102_44830_44834_1, 202102_44835_44835_0, 202102_44836_44836_0, 202102_44837_44837_0, 202102_44838_44838_0, 202102_44839_44839_0 to 202102_44830_44839_2
2021.02.01 18:26:16.007008 [ 16326 ] {} <Trace> db.tbl_local: Renaming temporary part tmp_merge_202102_44830_44839_2 to 202102_44830_44839_2.
2021.02.01 18:26:18.095087 [ 20613 ] {e6e82e12-cf40-41d8-b724-35dfc63d51f1} <Trace> db.tbl_local (SelectExecutor): Not using primary index on part 202102_44830_44839_2
2021.02.01 18:26:18.099127 [ 20613 ] {e6e82e12-cf40-41d8-b724-35dfc63d51f1} <Trace> MergeTreeSelectProcessor: Reading 1 ranges from part 202102_44830_44839_2, approx. 9594 rows starting from 0
2021.02.01 18:26:26.319638 [ 17413 ] {5915ab08-e1f1-4c2a-a717-019b91c05581} <Trace> db.tbl_local (SelectExecutor): Not using primary index on part 202102_44830_44839_2
2021.02.01 18:26:26.323443 [ 17413 ] {5915ab08-e1f1-4c2a-a717-019b91c05581} <Trace> MergeTreeSelectProcessor: Reading 1 ranges from part 202102_44830_44839_2, approx. 9594 rows starting from 0
2021.02.01 18:26:26.345225 [ 20087 ] {54085b6f-bd8f-4fdf-acd6-8d123c44c602} <Debug> db.tbl_local: Freezing part 202102_44830_44839_2 snapshot will be placed at shadow/backup/
2021.02.01 18:26:28.424694 [ 17413 ] {633d8d3f-0092-4d41-b9e4-09bb6b56f79e} <Trace> db.tbl_local (SelectExecutor): Not using primary index on part 202102_44830_44839_2
2021.02.01 18:26:28.428581 [ 17413 ] {633d8d3f-0092-4d41-b9e4-09bb6b56f79e} <Trace> MergeTreeSelectProcessor: Reading 1 ranges from part 202102_44830_44839_2, approx. 9594 rows starting from 0
2021.02.01 18:26:30.554791 [ 17413 ] {7afe16d6-cce3-498a-86b9-6127c7ce9971} <Trace> db.tbl_local (SelectExecutor): Not using primary index on part 202102_44830_44839_2
2021.02.01 18:26:30.558186 [ 17413 ] {7afe16d6-cce3-498a-86b9-6127c7ce9971} <Trace> MergeTreeSelectProcessor: Reading 1 ranges from part 202102_44830_44839_2, approx. 9594 rows starting from 0
2021.02.01 18:26:32.695363 [ 17413 ] {47b6ed79-73b1-4f78-af35-d35e57f17787} <Trace> db.tbl_local (SelectExecutor): Not using primary index on part 202102_44830_44839_2
2021.02.01 18:26:32.699207 [ 17413 ] {47b6ed79-73b1-4f78-af35-d35e57f17787} <Trace> MergeTreeSelectProcessor: Reading 1 ranges from part 202102_44830_44839_2, approx. 9594 rows starting from 0
2021.02.01 18:26:32.838306 [ 27778 ] {} <Trace> db.tbl_local: Executing log entry to merge parts 202102_44830_44839_2, 202102_44840_44845_1, 202102_44846_44846_0, 202102_44847_44847_0, 202102_44848_44848_0, 202102_44849_44849_0, 202102_44850_44850_0, 202102_44851_44851_0 to 202102_44830_44851_3
2021.02.01 18:26:32.838439 [ 27778 ] {} <Debug> db.tbl_local (MergerMutator): Merging 8 parts: from 202102_44830_44839_2 to 202102_44851_44851_0 into Wide
2021.02.01 18:26:32.838728 [ 27778 ] {} <Trace> MergeTreeSequentialSource: Reading 4 marks from part 202102_44830_44839_2, total 9594 rows starting from the beginning of the part
2021.02.01 18:26:33.193019 [ 27778 ] {} <Trace> db.tbl_local (MergerMutator): Merged 8 parts: from 202102_44830_44839_2 to 202102_44851_44851_0
```

The logs on the new machine:
```
2021.02.02 10:22:23.220915 [ 14130 ] {834cc4d3-66af-40dc-a07d-6c183031b68e} <Error> executeQuery: Code: 27, e.displayText() = DB::ParsingException: Cannot parse input: expected 'columns format version: 1\n' at end of stream. (version 21.1.2.15 (official build)) (from [::ffff:127.0.0.1]:45842) (in query: ALTER TABLE db.tbl_local ATTACH PART '202102_44830_44839_2'; ), Stack trace (when copying this message, always include the lines below):

0. DB::ParsingException::ParsingException(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x8609f13 in /usr/bin/clickhouse
1. DB::throwAtAssertionFailed(char const*, DB::ReadBuffer&) @ 0x865587f in /usr/bin/clickhouse
2. DB::NamesAndTypesList::readText(DB::ReadBuffer&) @ 0xe8054a1 in /usr/bin/clickhouse
3. DB::IMergeTreeDataPart::loadColumns(bool) @ 0xf59ea85 in /usr/bin/clickhouse
4. DB::IMergeTreeDataPart::loadColumnsChecksumsIndexes(bool, bool) @ 0xf59e3a9 in /usr/bin/clickhouse
5. DB::MergeTreeData::tryLoadPartsToAttach(std::__1::shared_ptr<DB::IAST> const&, bool, DB::Context const&, DB::MergeTreeData::PartsTemporaryRename&) @ 0xf5fdd2d in /usr/bin/clickhouse
6. DB::StorageReplicatedMergeTree::attachPartition(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, bool, DB::Context const&) @ 0xf446e9a in /usr/bin/clickhouse
7. DB::MergeTreeData::alterPartition(std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::vector<DB::PartitionCommand, std::__1::allocator<DB::PartitionCommand> > const&, DB::Context const&) @ 0xf5f6e3c in /usr/bin/clickhouse
8. DB::InterpreterAlterQuery::execute() @ 0xee0729a in /usr/bin/clickhouse
9. ? @ 0xf17d029 in /usr/bin/clickhouse
10. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool) @ 0xf17b99d in /usr/bin/clickhouse
11. DB::TCPHandler::runImpl() @ 0xf8844d6 in /usr/bin/clickhouse
12. DB::TCPHandler::run() @ 0xf8932e7 in /usr/bin/clickhouse
13. Poco::Net::TCPServerConnection::start() @ 0x11dd646f in /usr/bin/clickhouse
14. Poco::Net::TCPServerDispatcher::run() @ 0x11dd7e81 in /usr/bin/clickhouse
15. Poco::PooledThread::run() @ 0x11f03809 in /usr/bin/clickhouse
16. Poco::ThreadImpl::runnableEntry(void*) @ 0x11eff79a in /usr/bin/clickhouse
17. start_thread @ 0x76db in /lib/x86_64-linux-gnu/libpthread-2.27.so
18. clone @ 0x12171f in /lib/x86_64-linux-gnu/libc-2.27.so
```

The part that should have been generated by merging those parts (i.e. 202102_44830_44851_3) did not make it to the `shadow` folder.

***Count check***
Before and right freezing the table, it had `5455985681` rows on the original machine. But on the new machine it only had `5455968914`, the difference (i.e. **16767**) is basically the sum of the `count.txt` value for the above two parts in the `shadow` folder.

**Does it reproduce on recent release?**
Yes, I'm using this version `21.1.2.15` on both machines.

**How to reproduce**
***Backup***
1. Run `ALTER TABLE db.tbl_local FREEZE WITH NAME 'backup';`.
2. Take disk snapshot.
3. Clear shadow folder: `sudo rm -rf /drives/ssd1/clickhouse/shadow`

***Restore***
1. Restore a disk from the snapshot and attach to the machine.
2. Copy hardlinks: `sudo cp -rl /drives/ssd1/clickhouse/shadow/backup/data/db/* /drives/ssd1/clickhouse/data/db/tbl_local/detached`
3. Attach parts by running `ALTER TABLE db.tbl_local ATTACH PART '$part';` for each part.

**Expected behavior**
All the parts get attached normally and the count on the old machine should be equal to the count on the new machine.

**Comment by alexey-milovidov** [comment]
If you do disk snapshotting on running server, the data on filesystem is not necessarily already being written to disk.
It may reside in dirty pages in OS page cache.

**Comment by ibradwan** [comment]
Thanks Alexey for the explanation,

I expected that freezing the parts will produce a clean disk written state, but given what you said, I'm not sure if even stopping the clickhouse-server on a single replica before snapshotting its disk would work. Do you think there's another way to handle this (preferably without shutting down a replica)?

Also based on what I understand, this can happen with any parts that are being merged during the backup process, which means that this approach may not be applicable to do backups because it could lose large parts in the process not just small/recent parts.

BTW, [here](https://altinity.com/blog/introduction-to-clickhouse-backups-and-clickhouse-backup) is the tutorial that I have been following to do this exercise.

**Comment by den-crane** [comment]
`sync` before (2 - Take disk snapshot. ) is probably enough.
 
>BTW, here is the tutorial that I have been following to do this exercise.

No. I don't see it. 
When you read a file from the inside OS you read it from OS cache (+disk). 
When you did (2) from the outside you lost OS cache.

**Comment by ibradwan** [comment]
Makes sense... Anyway I think `sync` will only reduce the probability of this happening but won't eliminate it.

**Comment by den-crane** [comment]
@ibradwan seems you misunderstood something.

> I will have to stop the ClickHouse server

No, I do NOT see any sense to stop CH.
It's unclear how you do snapshots and what is your setup. 
In some cases `sync` is not enough, because env. can have more caches / raid cache / disk-drive cache.

**Comment by ibradwan** [comment]
Thanks Denny for pointing this out.

>  No, I do NOT see any sense to stop CH.

Sorry I was confused, but yes given that the parts are immutable and the `FREEZE` operation uses hard-links, syncing the pages after the `FREEZE` operation should be enough.

I had to dig a bit deeper into the Azure disks story to understand if a `sync` call would be enough to write the data to the persistent storage or not. Here's what I found in case someone else looks this up in the future:
Azure disks are basically backed up by Azure blobs, the way the snapshots work depends on the data currently written to thoes blobs. Check [this](https://azure.microsoft.com/en-us/blog/announcing-general-availability-of-incremental-snapshots-of-managed-disks/) for more details (esp. about the incremental snapshots).

So in order to guarantee that our backup is consistent, we have to `sync` any dirty pages to the disk (i.e. blobs). But for some cases, Azure provides what is called BlobCache as a caching layer on the host machine, which should virtually increase the VM disk IO capabilities. But the BlobCache is enabled only under certain circumstances (e.g. less than 4 TB disks), for our use case we have large drives (> 4 TB), so the BlobCache is not enabled for our ClickHouse cluster. Therefore I'm not sure if calling `sync` only would be enough if we had BlobCache enabled. At least I did not run experiments on that setup.

Anyway here is some references that could be useful if someone needs more data:
[How VictoriaMetrics makes instant snapshots for multi-terabyte time series data](https://valyala.medium.com/how-victoriametrics-makes-instant-snapshots-for-multi-terabyte-time-series-data-e1f3fb0e0282#:~:text=VictoriaMetrics%20uses%20hard%20links%20to,safe%2C%20since%20parts%20never%20change).
[Azure VM backup](https://docs.microsoft.com/en-us/azure/backup/backup-azure-vms-introduction)
[Azure disk backup (preview)](https://docs.microsoft.com/en-us/azure/backup/disk-backup-overview)
[Azure premium storage caching](https://docs.microsoft.com/en-us/azure/virtual-machines/premium-storage-performance#disk-caching)
[Azure BlobCache](https://azure.microsoft.com/en-us/blog/azure-premium-storage-now-generally-available-2/)
