### ISSUE TITLE
JSON DataType (RFC)

### ISSUE THREAD

**Issue by hexiaoting** [ClickHouse/ClickHouse#19981]
In our production environment, we have many semi-structure datasets in json format to analysis.
Our data's features include:
1. have key name
2. value type is multiply, include Number, String, Array and so on, But the value type of the same key name is the same.
3. the schema (the info of keys) is dynamic.

For example:
```
{a:1, b:"xyz"}
{a:1, b:"zzz", c:100}
{a:100, c:200, d:[0,1,2]}
```
And our queries are most related to a few columns, So I want to implement a JSON dataType to save every key's values in columnar storage to support this situation.

# JSON Type Grammars:
## create table
`create table test (data json) Engine = MergeTree() order by tuple()`
```
dell123 :) desc test
┌─name─┬─type─────────┬─default_type─┬─default_expression─┬─comment─┬─codec_expression─┬─ttl_expression─┐
│ data │ JSON         │              │                    │         │                  │                │
└──────┴──────────────┴──────────────┴────────────────────┴─────────┴──────────────────┴────────────────┘

## desc table
dell123 :) desc test setting json_schema_expand=1
shows  below 4 columns:
data:a
data:b
data:c
data:d
```

## insert table
`insert into test select parse_json(' { "key1": "value1", "key2": "value2" } ')`
**Storage for json**
{a:1, b:"xyz", c: [1,2,3], d:[{d1: 100, d2: "zzz"}, {d1:200, d3:0}]}
it will stored in 6 columns:
| column name |type  |value  |
| --- | --- | --- |
| data:a | UInt32 | 1 |
| data:b | String | "xyz" |
| data:c | Array(UInt32) |[1,2,3]  |
| data:d.d1 |Array(UInt32)  |[100,200]  |
| data:d.d2 |Array(String)  |["zzz", NULL]  |
| data:d.d3 |Array(UInt32)  |[NULL, 0] |

## select 
the syntax is learned from snowflake，we can access json's data using `.` or `[]`：
`<column>:<level1_element>.<level2_element>.<level3_element>` or
`<column>['<level1_element>']['<level2_element>']`
Note: `data:salesperson.name` equals `data['salesperson']['name']`

example:
`select data:key1 from test`  returns value1

# Implementation
For the implementation I think we can reference JSONEachRow format(not sure, need discussions)

# Questions:
1. Is this grammar OK?
2. the restriction for json type is accepted?
    * must have key name
    * the value type of the key name must be the same

**Comment by alexey-milovidov** [comment]
@CurtizJ is doing this task: dynamic columns in tables with support to import shema-less JSON.

**Comment by filimonov** [comment]
Also https://github.com/ClickHouse/ClickHouse/pull/7426

**Comment by hexiaoting** [comment]
This feature will be discussed in https://github.com/ClickHouse/ClickHouse/issues/23516 with a new datatype `Object`.
