### ISSUE TITLE
 Now it is very difficult to rebalance data after adding shards. Are there any plans to optimize this?  

### ISSUE THREAD

**Issue by Sallery-X** [ClickHouse/ClickHouse#19994]

**Comment by den-crane** [comment]
Yes, it's planned. It will implemented in the next 5 years.

**Comment by wzb5212** [comment]
> Yes, it's planned. It will implemented in the next 5 years.



> Yes, it's planned. It will implemented in the next 5 years.

are you kidding??

**Comment by wzb5212** [comment]
> Yes, it's planned. It will implemented in the next 5 years.

are you kidding ????
