### ISSUE TITLE
How to query the latest specified number of data without using order by?

### ISSUE THREAD

**Issue by MrSsunlight** [ClickHouse/ClickHouse#19992]
Near real-time data flows into the table, the table structure **uses time partitioned by day**, and **time is the primary key**；If I want to query the 20 latest data generated during the day, and currently clickhouse does not pass the `order by time desc` operation, how can I achieve the same effect without traversing all the data of the day？

Somewhat similar to this question [1582](https://github.com/ClickHouse/ClickHouse/issues/1582) but only query the latest specified number of items for the day or a whole time range, instead of narrowing the retrieval time range to achieve fast query results

**Comment by den-crane** [comment]
It was in 2017 https://github.com/ClickHouse/ClickHouse/issues/1582 
Now Ch has an optimization for order by and it does NOT traversing all the data.

--optimize_read_in_order Enable ORDER BY optimization for reading data in corresponding order in MergeTree tables.

Optimization is enabled by  default.

Example: 

```sql
create table XT(t DateTime, X String) engine=MergeTree Partition by toYYYYMM(t) order by t;
insert into XT select toDateTime('2020-01-01') + number/1000, toString(number) from numbers(100000000);

select * from XT where toDate(t) = '2020-01-01' order by t desc limit 10;
┌───────────────────t─┬─X────────┐
│ 2020-01-01 23:59:59 │ 86399999 │
│ 2020-01-01 23:59:59 │ 86399998 │
│ 2020-01-01 23:59:59 │ 86399997 │
│ 2020-01-01 23:59:59 │ 86399996 │
│ 2020-01-01 23:59:59 │ 86399995 │
│ 2020-01-01 23:59:59 │ 86399994 │
│ 2020-01-01 23:59:59 │ 86399993 │
│ 2020-01-01 23:59:59 │ 86399992 │
│ 2020-01-01 23:59:59 │ 86399991 │
│ 2020-01-01 23:59:59 │ 86399990 │
└─────────────────────┴──────────┘

10 rows in set. Elapsed: 0.009 sec. Processed 243.31 thousand rows,     <<<<<<<<<<<<<-------------

-------- DISABLE OPTIMIZATION ---------------------------------

set optimize_read_in_order=0;
select * from XT where toDate(t) = '2020-01-01' order by t desc limit 10;

10 rows in set. Elapsed: 0.297 sec. Processed 86.41 million rows,       <<<<<<<<<<<<<-------------

```
