### ISSUE TITLE
build failed on  v20.8.7.15-lts

### ISSUE THREAD

**Issue by leosunli** [ClickHouse/ClickHouse#19995]
Make sure that `git diff` result is empty and you've just pulled fresh master. Try cleaning up cmake cache. Just in case, official build instructions are published here: https://clickhouse.yandex/docs/en/development/build/

**Operating system**
OS kind or distribution, specific version/release, non-standard kernel if any. If you are trying to build inside virtual machine, please mention it too.
Linux version 3.10.0-957.21.3.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org)) #1 SMP Tue Jun 18 16:35:19 UTC 2019

**gcc version **
[root@emr-dev-support011158132038 build]# gcc -v
使用内建 specs。
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/x86_64-pc-linux-gnu/10.2.0/lto-wrapper
目标：x86_64-pc-linux-gnu
配置为：../configure --enable-checking=release --enable-languages=c,c++ --disable-multilib
线程模型：posix
Supported LTO compression algorithms: zlib
gcc 版本 10.2.0 (GCC)
[root@emr-dev-support011158132038 build]#

**Cmake version**
cmake version 3.15.7

**Ninja version**
Ninja version 1.8.2
**Compiler name and version**

**Full cmake and/or ninja output**
[root@emr-dev-support011158132038 build]# cmake ..
-- Using custom linker by name: gold
-- IPO/LTO not enabled.
-- CMAKE_BUILD_TYPE is not set, set to default = RelWithDebInfo
-- CMAKE_BUILD_TYPE: RelWithDebInfo
-- Using objcopy: /usr/bin/objcopy.
-- Default libraries: -nodefaultlibs -lgcc  -lc -lm -lrt -lpthread -ldl
-- Some symbols from glibc will be replaced for compatibility
-- Using libunwind: unwind
-- Using exception handler: unwind
-- Using libcxx: cxx
-- Using libcxxfs:
-- Using libcxxabi: cxxabi
-- Tests are enabled
-- Building for: Linux-3.10.0-957.21.3.el7.x86_64 x86_64  ; USE_STATIC_LIBRARIES=ON MAKE_STATIC_LIBRARIES=ON SPLIT_SHARED= UNBUNDLED=OFF CCACHE=CCACHE_FOUND-NOTFOUND
-- Using double-conversion:  : double-conversion
-- Using ssl=1: /root/shengjun/source/ck/ClickHouse/contrib/openssl/include;/root/shengjun/source/ck/ClickHouse/contrib/openssl-cmake/linux_x86_64/include : ssl;crypto
-- Using ldap=1: /root/shengjun/source/ck/ClickHouse/contrib/openldap-cmake/linux_x86_64/include;/root/shengjun/source/ck/ClickHouse/contrib/openldap/include : ldap_r;lber
-- Using icu=1:  : icui18n;icuuc;icudata
-- Using zlib-ng: /root/shengjun/source/ck/ClickHouse/contrib/zlib-ng;/root/shengjun/source/ck/ClickHouse/build/contrib/zlib-ng : zlib
-- Using zstd: /root/shengjun/source/ck/ClickHouse/contrib/zstd/lib : zstd
-- Using sparsehash: /root/shengjun/source/ck/ClickHouse/contrib/sparsehash-c11
-- Using re2: /root/shengjun/source/ck/ClickHouse/contrib/re2 : re2;  : re2_st
-- Using krb5=1: /root/shengjun/source/ck/ClickHouse/contrib/krb5/src/include;/root/shengjun/source/ck/ClickHouse/build/contrib/krb5-cmake/include : krb5
-- Using libgsasl=1: /root/shengjun/source/ck/ClickHouse/contrib/libgsasl/src;/root/shengjun/source/ck/ClickHouse/contrib/libgsasl/linux_x86_64/include : libgsasl
-- Using cyrus-sasl: krb5=1: /root/shengjun/source/ck/ClickHouse/contrib/cyrus-sasl/include : sasl2
-- Using librdkafka=1: /root/shengjun/source/ck/ClickHouse/contrib/librdkafka/src : rdkafka cppkafka
-- Using AMQP-CPP=1: /root/shengjun/source/ck/ClickHouse/contrib/AMQP-CPP/include;/root/shengjun/source/ck/ClickHouse/contrib/AMQP-CPP/include;/root/shengjun/source/ck/ClickHouse/contrib/AMQP-CPP : AMQP-CPP
-- Using capnp=1: capnpc
-- LLVM include Directory: /root/shengjun/source/ck/ClickHouse/contrib/llvm/llvm/include;/root/shengjun/source/ck/ClickHouse/build/contrib/llvm/llvm/include
-- LLVM library Directory: /root/shengjun/source/ck/ClickHouse/build/contrib/llvm/llvm
-- LLVM C++ compiler flags:
-- Using h3=1: /root/shengjun/source/ck/ClickHouse/contrib/h3/src/h3lib/include : h3
-- Using libxml2: /root/shengjun/source/ck/ClickHouse/contrib/libxml2/include;/root/shengjun/source/ck/ClickHouse/contrib/libxml2-cmake/linux_x86_64/include : libxml2
-- Using brotli=1: /root/shengjun/source/ck/ClickHouse/contrib/brotli/c/include : brotli
-- Using protobuf=1: /root/shengjun/source/ck/ClickHouse/contrib/protobuf/src : libprotobuf : $<TARGET_FILE:protoc>
-- Using gRPC=ON: /root/shengjun/source/ck/ClickHouse/contrib/grpc/include : libgrpc++
-- Using pdqsort: /root/shengjun/source/ck/ClickHouse/contrib/pdqsort
-- Using hdfs3=1: /root/shengjun/source/ck/ClickHouse/contrib/libhdfs3/include : hdfs3
-- Using curl: /root/shengjun/source/ck/ClickHouse/contrib/curl/include : curl
-- Using aws_s3=1: /root/shengjun/source/ck/ClickHouse/contrib/aws/aws-cpp-sdk-s3/include : aws_s3
-- Using snappy: snappy
-- Using Parquet: arrow=arrow_static: ; parquet=parquet_static: ; thrift=thrift_static ; flatbuffers=flatbuffers
-- Using simdjson=ON
-- Using rapidjson=1: /root/shengjun/source/ck/ClickHouse/contrib/rapidjson/include
-- Using fastops=1: /root/shengjun/source/ck/ClickHouse/contrib/fastops/ : fastops
-- Using unixodbc
-- Using snappy: snappy
-- Using internal=1 orc=1: /root/shengjun/source/ck/ClickHouse/contrib/orc/c++/include : orc
-- Using snappy: snappy
-- Using avro=1: /root/shengjun/source/ck/ClickHouse/contrib/avro/lang/c++/include : avrocpp
CMake Warning at cmake/find/msgpack.cmake:14 (message):
  Submodule contrib/msgpack-c is missing.  To fix try run:

   git submodule update --init --recursive
Call Stack (most recent call first):
  CMakeLists.txt:431 (include)

CMake Error at cmake/find/msgpack.cmake:15 (message):
  Cannot use internal msgpack
Call Stack (most recent call first):
  CMakeLists.txt:431 (include)

-- Configuring incomplete, errors occurred

**CMakeError.log**
Performing C SOURCE FILE Test CMAKE_HAVE_LIBC_PTHREAD failed with the following output:
Change Dir: /root/shengjun/source/ck/ClickHouse/build/CMakeFiles/CMakeTmp

Run Build Command(s):/root/shengjun/ninja-1.8.2/ninja cmTC_0470d && [1/2] Building C object CMakeFiles/cmTC_0470d.dir/src.c.o
[2/2] Linking C executable cmTC_0470d
FAILED: cmTC_0470d 
: && /usr/local/bin/gcc -fdiagnostics-color=always  -pipe -msse4.1 -msse4.2 -mpopcnt  -Wall  -Werror -DCMAKE_HAVE_LIBC_PTHREAD  -fuse-ld=gold -rdynamic -Wl,--no-undefined   -rdynamic CMakeFiles/cmTC_0470d.dir/src.c.o  -o cmTC_0470d   && :
CMakeFiles/cmTC_0470d.dir/src.c.o:src.c:function main: 错误: 对‘pthread_create’未定义的引用
CMakeFiles/cmTC_0470d.dir/src.c.o:src.c:function main: 错误: 对‘pthread_detach’未定义的引用
CMakeFiles/cmTC_0470d.dir/src.c.o:src.c:function main: 错误: 对‘pthread_join’未定义的引用
CMakeFiles/cmTC_0470d.dir/src.c.o:src.c:function main: 错误: 对‘pthread_atfork’未定义的引用
collect2: 错误：ld 返回 1
ninja: build stopped: subcommand failed.

Source file was:
#include <pthread.h>

void* test_func(void* data)
{
  return data;
}

int main(void)
{
  pthread_t thread;
  pthread_create(&thread, NULL, test_func, NULL);
  pthread_detach(thread);
  pthread_join(thread, NULL);
  pthread_atfork(NULL, NULL, NULL);
  pthread_exit(NULL);

  return 0;
}

Determining if the include file sys/random.h exists failed with the following output:
Change Dir: /root/shengjun/source/ck/ClickHouse/build/CMakeFiles/CMakeTmp

Run Build Command(s):/root/shengjun/ninja-1.8.2/ninja cmTC_41c1a && [1/2] Building C object CMakeFiles/cmTC_41c1a.dir/CheckIncludeFile.c.o
FAILED: CMakeFiles/cmTC_41c1a.dir/CheckIncludeFile.c.o 
/usr/local/bin/gcc   -fdiagnostics-color=always  -pipe -msse4.1 -msse4.2 -mpopcnt  -Wall  -Werror -o CMakeFiles/cmTC_41c1a.dir/CheckIncludeFile.c.o   -c CheckIncludeFile.c
CheckIncludeFile.c:1:10: 致命错误：sys/random.h：没有那个文件或目录
    1 | #include <sys/random.h>
      |          ^~~~~~~~~~~~~~
编译中断。
ninja: build stopped: subcommand failed.

**Comment by filimonov** [comment]
I see in the error log you attached:

```
Submodule contrib/msgpack-c is missing. To fix try run:

git submodule update --init --recursive
```

Please follow that recommendation

**Comment by leosunli** [comment]
@filimonov  i have run git submodule update --init --recursive
 it stilll does not work.

**Comment by alexey-milovidov** [comment]
@leosunli But there are much more files in the `msgpack-c` directory, you can see it on GitHub.

**Comment by leosunli** [comment]
hi @filimonov 
there are error on https://github.com/msgpack/msgpack-c/tree/master as follow:
![image](https://user-images.githubusercontent.com/3837921/106732375-98f97e00-664b-11eb-81b6-b96ce0706916.png)

**Comment by leosunli** [comment]
the error message as follow when I call ninja.
[10/3427] Linking CXX executable contrib/protobuf/protoc-3.13.0.0
FAILED: contrib/protobuf/protoc-3.13.0.0
: && /usr/local/bin/g++ -fdiagnostics-color=always -std=c++2a -fsized-deallocation  -pipe -msse4.1 -msse4.2 -mpopcnt   -Wall  -Werror -w -O2 -g -DNDEBUG -O3  -fno-pie -fuse-ld=gold -rdynamic -Wl,--no-undefined -Wl,-no-pie   -rdynamic contrib/protobuf/CMakeFiles/protoc.dir/__/src/google/protobuf/compiler/main.cc.o -o contrib/protobuf/protoc-3.13.0.0  contrib/protobuf/libprotoc.a  contrib/protobuf/libprotobuf.a  -lpthread  -Wl,--start-group  base/glibc-compatibility/libglibc-compatibility.a  contrib/libcxx-cmake/libcxx.a  contrib/libcxxabi-cmake/libcxxabi.a  contrib/libunwind-cmake/libunwind.a  -Wl,--end-group  -pthread  -nodefaultlibs -lgcc  -lc -lm -lrt -lpthread -ldl && :
../contrib/libcxx/include/ostream:1005: 错误: 对‘std::__1::basic_ostream<char, std::__1::char_traits<char> >::put(char)’未定义的引用
../contrib/libcxx/include/ostream:1005: 错误: 对‘std::__1::basic_ostream<char, std::__1::char_traits<char> >::put(char)’未定义的引用
../contrib/libcxx/include/ostream:1006: 错误: 对‘std::__1::basic_ostream<char, std::__1::char_traits<char> >::flush()’未定义的引用
../contrib/libcxx/include/ostream:1005: 错误: 对‘std::__1::basic_ostream<char, std::__1::char_traits<char> >::put(char)’未定义的引用
../contrib/libcxx/include/ostream:1006: 错误: 对‘std::__1::basic_ostream<char, std::__1::char_traits<char> >::flush()’未定义的引用
../contrib/libcxx/include/ostream:1005: 错误: 对‘std::__1::basic_ostream<char, std::__1::char_traits<char> >::put(char)’未定义的引用
../contrib/libcxx/include/ostream:1006: 错误: 对‘std::__1::basic_ostream<char, std::__1::char_traits<char> >::flush()’未定义的引用
../contrib/libcxx/include/ostream:1006: 错误: 对‘std::__1::basic_ostream<char, std::__1::char_traits<char> >::flush()’未定义的引用
../contrib/libcxx/include/istream:190: 错误: 对‘VTT for std::__1::basic_ifstream<char, std::__1::char_traits<char> >’未定义的引用
../contrib/libcxx/include/istream:190: 错误: 对‘VTT for std::__1::basic_ifstream<char, std::__1::char_traits<char> >’未定义的引用
../contrib/libcxx/include/ios:675: 错误: 对‘vtable for std::__1::basic_ios<char, std::__1::char_traits<char> >’未定义的引用
/usr/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function
../contrib/libcxx/include/fstream:1209: 错误: 对‘vtable for std::__1::basic_ifstream<char, std::__1::char_traits<char> >’未定义的引用
/usr/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function
../contrib/libcxx/include/fstream:1209: 错误: 对‘vtable for std::__1::basic_ifstream<char, std::__1::char_traits<char> >’未定义的引用
/usr/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function
../contrib/libcxx/include/fstream:1209: 错误: 对‘std::__1::basic_filebuf<char, std::__1::char_traits<char> >::basic_filebuf()’未定义的引用
../contrib/libcxx/include/fstream:1211: 错误: 对‘std::__1::basic_filebuf<char, std::__1::char_traits<char> >::open(char const*, unsigned int)’未定义的引用
../contrib/libcxx/include/fstream:1133: 错误: 对‘vtable for std::__1::basic_ifstream<char, std::__1::char_traits<char> >’未定义的引用
/usr/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function
../contrib/libcxx/include/fstream:1133: 错误: 对‘vtable for std::__1::basic_ifstream<char, std::__1::char_traits<char> >’未定义的引用
/usr/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function
../contrib/libcxx/include/fstream:1133: 错误: 对‘std::__1::basic_filebuf<char, std::__1::char_traits<char> >::~basic_filebuf()’未定义的引用
../contrib/libcxx/include/fstream:1133: 错误: 对‘VTT for std::__1::basic_ifstream<char, std::__1::char_traits<char> >’未定义的引用
../contrib/libcxx/include/fstream:1133: 错误: 对‘std::__1::basic_istream<char, std::__1::char_traits<char> >::~basic_istream()’未定义的引用
../contrib/libcxx/include/fstream:1133: 错误: 对‘std::__1::basic_ios<char, std::__1::char_traits<char> >::~basic_ios()’未定义的引用
../contrib/libcxx/include/fstream:1133: 错误: 对‘std::__1::basic_filebuf<char, std::__1::char_traits<char> >::~basic_filebuf()’未定义的引用
../contrib/libcxx/include/fstream:1133: 错误: 对‘VTT for std::__1::basic_ifstream<char, std::__1::char_traits<char> >’未定义的引用
../contrib/libcxx/include/fstream:1133: 错误: 对‘std::__1::basic_istream<char, std::__1::char_traits<char> >::~basic_istream()’未定义的引用
../contrib/libcxx/include/fstream:1133: 错误: 对‘std::__1::basic_ios<char, std::__1::char_traits<char> >::~basic_ios()’未定义的引用
../contrib/libcxx/include/fstream:1209: 错误: 对‘std::__1::basic_filebuf<char, std::__1::char_traits<char> >::~basic_filebuf()’未定义的引用
../contrib/libcxx/include/fstream:1209: 错误: 对‘std::__1::basic_istream<char, std::__1::char_traits<char> >::~basic_istream()’未定义的引用
../contrib/libcxx/include/fstream:1209: 错误: 对‘std::__1::basic_ios<char, std::__1::char_traits<char> >::~basic_ios()’未定义的引用
../contrib/libcxx/include/ostream:725: 错误: 对‘std::__1::basic_ostream<char, std::__1::char_traits<char> >::sentry::sentry(std::__1::basic_ostream<char, std::__1::char_traits<char> >&)’未定义的引用
../contrib/libcxx/include/ostream:725: 错误: 对‘std::__1::basic_ostream<char, std::__1::char_traits<char> >::sentry::~sentry()’未定义的引用
../contrib/libcxx/include/ostream:725: 错误: 对‘std::__1::basic_ostream<char, std::__1::char_traits<char> >::sentry::~sentry()’未定义的引用
../contrib/protobuf/src/google/protobuf/compiler/command_line_interface.cc:344: 错误: 对‘std::__1::basic_ostream<char, std::__1::char_traits<char> >::operator<<(int)’未定义的引用
../contrib/protobuf/src/google/protobuf/compiler/command_line_interface.cc:344: 错误: 对‘std::__1::basic_ostream<char, std::__1::char_traits<char> >::operator<<(int)’未定义的引用
../contrib/protobuf/src/google/protobuf/compiler/command_line_interface.cc:340: 错误: 对‘std::__1::basic_ostream<char, std::__1::char_traits<char> >::operator<<(int)’未定义的引用
../contrib/protobuf/src/google/protobuf/compiler/command_line_interface.cc:344: 错误: 对‘std::__1::basic_ostream<char, std::__1::char_traits<char> >::operator<<(int)’未定义的引用
../contrib/libcxx/include/istream:1521: 错误: 对‘std::__1::basic_istream<char, std::__1::char_traits<char> >::sentry::sentry(std::__1::basic_istream<char, std::__1::char_traits<char> >&, bool)’未定义的引用
../contrib/libcxx/include/ostream:165: 错误: 对‘VTT for std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >’未定义的引用
../contrib/libcxx/include/ios:675: 错误: 对‘vtable for std::__1::basic_ios<char, std::__1::char_traits<char> >’未定义的引用
/usr/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function
../contrib/libcxx/include/ostream:165: 错误: 对‘VTT for std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >’未定义的引用
../contrib/libcxx/include/sstream:706: 错误: 对‘vtable for std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >’未定义的引用
/usr/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function
../contrib/libcxx/include/sstream:706: 错误: 对‘vtable for std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >’未定义的引用
/usr/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function
../contrib/libcxx/include/sstream:213: 错误: 对‘std::__1::basic_streambuf<char, std::__1::char_traits<char> >::basic_streambuf()’未定义的引用
../contrib/libcxx/include/sstream:213: 错误: 对‘vtable for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> >’未定义的引用
/usr/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function
../contrib/libcxx/include/sstream:744: 错误: 对‘std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> >::str() const’未定义的引用
../contrib/libcxx/include/sstream:685: 错误: 对‘vtable for std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >’未定义的引用
/usr/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function
../contrib/libcxx/include/sstream:685: 错误: 对‘vtable for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> >’未定义的引用
/usr/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function
../contrib/libcxx/include/sstream:685: 错误: 对‘vtable for std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >’未定义的引用
/usr/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function
../contrib/libcxx/include/sstream:190: 错误: 对‘std::__1::basic_streambuf<char, std::__1::char_traits<char> >::~basic_streambuf()’未定义的引用
../contrib/libcxx/include/sstream:685: 错误: 对‘VTT for std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >’未定义的引用
../contrib/libcxx/include/sstream:685: 错误: 对‘std::__1::basic_ostream<char, std::__1::char_traits<char> >::~basic_ostream()’未定义的引用
../contrib/libcxx/include/sstream:685: 错误: 对‘std::__1::basic_ios<char, std::__1::char_traits<char> >::~basic_ios()’未定义的引用
../contrib/libcxx/include/sstream:706: 错误: 对‘VTT for std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >’未定义的引用
../contrib/libcxx/include/sstream:706: 错误: 对‘std::__1::basic_ostream<char, std::__1::char_traits<char> >::~basic_ostream()’未定义的引用
../contrib/libcxx/include/sstream:685: 错误: 对‘vtable for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> >’未定义的引用
/usr/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function
../contrib/libcxx/include/sstream:190: 错误: 对‘std::__1::basic_streambuf<char, std::__1::char_traits<char> >::~basic_streambuf()’未定义的引用
../contrib/libcxx/include/sstream:685: 错误: 对‘std::__1::basic_ostream<char, std::__1::char_traits<char> >::~basic_ostream()’未定义的引用
../contrib/libcxx/include/ios:675: 错误: 对‘vtable for std::__1::basic_ios<char, std::__1::char_traits<char> >’未定义的引用
/usr/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function
../contrib/libcxx/include/sstream:213: 错误: 对‘std::__1::basic_streambuf<char, std::__1::char_traits<char> >::basic_streambuf()’未定义的引用
../contrib/libcxx/include/sstream:213: 错误: 对‘vtable for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> >’未定义的引用
/usr/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function
../contrib/libcxx/include/sstream:744: 错误: 对‘std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> >::str() const’未定义的引用
../contrib/libcxx/include/sstream:190: 错误: 对‘std::__1::basic_streambuf<char, std::__1::char_traits<char> >::~basic_streambuf()’未定义的引用
../contrib/libcxx/include/sstream:685: 错误: 对‘std::__1::basic_ostream<char, std::__1::char_traits<char> >::~basic_ostream()’未定义的引用
../contrib/libcxx/include/sstream:190: 错误: 对‘std::__1::basic_streambuf<char, std::__1::char_traits<char> >::~basic_streambuf()’未定义的引用
../contrib/libcxx/include/ios:675: 错误: 对‘vtable for std::__1::basic_ios<char, std::__1::char_traits<char> >’未定义的引用
/usr/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function
../contrib/libcxx/include/sstream:213: 错误: 对‘std::__1::basic_streambuf<char, std::__1::char_traits<char> >::basic_streambuf()’未定义的引用
../contrib/libcxx/include/sstream:744: 错误: 对‘std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> >::str() const’未定义的引用
../contrib/protobuf/src/google/protobuf/compiler/ruby/ruby_generator.cc:161: 错误: 对‘std::__1::basic_ostream<char, std::__1::char_traits<char> >::operator<<(unsigned short)’未定义的引用
../contrib/libcxx/include/sstream:213: 错误: 对‘std::__1::basic_streambuf<char, std::__1::char_traits<char> >::basic_streambuf()’未定义的引用
../contrib/protobuf/src/google/protobuf/compiler/ruby/ruby_generator.cc:66: 错误: 对‘std::__1::basic_ostream<char, std::__1::char_traits<char> >::operator<<(long)’未定义的引用
../contrib/libcxx/include/sstream:744: 错误: 对‘std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> >::str() const’未定义的引用
../contrib/protobuf/src/google/protobuf/compiler/ruby/ruby_generator.cc:66: 错误: 对‘std::__1::basic_ostream<char, std::__1::char_traits<char> >::operator<<(unsigned int)’未定义的引用
../contrib/protobuf/src/google/protobuf/compiler/ruby/ruby_generator.cc:66: 错误: 对‘std::__1::basic_ostream<char, std::__1::char_traits<char> >::operator<<(unsigned long)’未定义的引用
../contrib/protobuf/src/google/protobuf/compiler/ruby/ruby_generator.cc:66: 错误: 对‘std::__1::basic_ostream<char, std::__1::char_traits<char> >::operator<<(float)’未定义的引用
../contrib/protobuf/src/google/protobuf/compiler/ruby/ruby_generator.cc:66: 错误: 对‘std::__1::basic_ostream<char, std::__1::char_traits<char> >::operator<<(double)’未定义的引用
../contrib/protobuf/src/google/protobuf/io/zero_copy_stream_impl.cc:275: 错误: 对‘std::__1::basic_istream<char, std::__1::char_traits<char> >::read(char*, long)’未定义的引用
../contrib/protobuf/src/google/protobuf/io/zero_copy_stream_impl.cc:307: 错误: 对‘std::__1::basic_ostream<char, std::__1::char_traits<char> >::write(char const*, long)’未定义的引用
../contrib/protobuf/src/google/protobuf/stubs/int128.cc:173: 错误: 对‘std::__1::basic_ostream<char, std::__1::char_traits<char> >::operator<<(unsigned long)’未定义的引用
../contrib/protobuf/src/google/protobuf/stubs/int128.cc:170: 错误: 对‘std::__1::basic_ostream<char, std::__1::char_traits<char> >::operator<<(unsigned long)’未定义的引用
../contrib/protobuf/src/google/protobuf/stubs/int128.cc:165: 错误: 对‘std::__1::basic_ostream<char, std::__1::char_traits<char> >::operator<<(unsigned long)’未定义的引用
../contrib/libcxx/include/ostream:725: 错误: 对‘std::__1::basic_ostream<char, std::__1::char_traits<char> >::sentry::sentry(std::__1::basic_ostream<char, std::__1::char_traits<char> >&)’未定义的引用
../contrib/libcxx/include/ostream:725: 错误: 对‘std::__1::basic_ostream<char, std::__1::char_traits<char> >::sentry::~sentry()’未定义的引用
../contrib/libcxx/include/ostream:725: 错误: 对‘std::__1::basic_ostream<char, std::__1::char_traits<char> >::sentry::~sentry()’未定义的引用
../contrib/protobuf/src/google/protobuf/stubs/stringpiece.cc:43: 错误: 对‘std::__1::basic_ostream<char, std::__1::char_traits<char> >::write(char const*, long)’未定义的引用
../contrib/libcxx/src/iostream.cpp:141: 错误: 对‘std::__1::basic_ostream<wchar_t, std::__1::char_traits<wchar_t> >::flush()’未定义的引用
../contrib/libcxx/src/iostream.cpp:147: 错误: 对‘std::__1::basic_ostream<wchar_t, std::__1::char_traits<wchar_t> >::flush()’未定义的引用
../contrib/libcxx/include/istream:190: 错误: 对‘vtable for std::__1::basic_istream<char, std::__1::char_traits<char> >’未定义的引用
/usr/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function
../contrib/libcxx/include/istream:190: 错误: 对‘vtable for std::__1::basic_istream<char, std::__1::char_traits<char> >’未定义的引用
/usr/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function
../contrib/libcxx/include/__std_stream:74: 错误: 对‘std::__1::basic_streambuf<wchar_t, std::__1::char_traits<wchar_t> >::basic_streambuf()’未定义的引用
../contrib/libcxx/include/istream:190: 错误: 对‘vtable for std::__1::basic_istream<wchar_t, std::__1::char_traits<wchar_t> >’未定义的引用
/usr/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function
../contrib/libcxx/include/istream:190: 错误: 对‘vtable for std::__1::basic_istream<wchar_t, std::__1::char_traits<wchar_t> >’未定义的引用
/usr/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function
../contrib/libcxx/include/__locale:252: 错误: 对‘vtable for std::__1::basic_ostream<char, std::__1::char_traits<char> >’未定义的引用
/usr/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function
../contrib/libcxx/include/__locale:252: 错误: 对‘vtable for std::__1::basic_ostream<char, std::__1::char_traits<char> >’未定义的引用
/usr/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function
../contrib/libcxx/include/__std_stream:256: 错误: 对‘std::__1::basic_streambuf<wchar_t, std::__1::char_traits<wchar_t> >::basic_streambuf()’未定义的引用
../contrib/libcxx/include/__locale:252: 错误: 对‘vtable for std::__1::basic_ostream<wchar_t, std::__1::char_traits<wchar_t> >’未定义的引用
/usr/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function
../contrib/libcxx/include/__locale:252: 错误: 对‘vtable for std::__1::basic_ostream<wchar_t, std::__1::char_traits<wchar_t> >’未定义的引用
/usr/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function
../contrib/libcxx/include/__std_stream:256: 错误: 对‘std::__1::basic_streambuf<wchar_t, std::__1::char_traits<wchar_t> >::basic_streambuf()’未定义的引用

**Comment by filimonov** [comment]
It seems you are doing something wrong with submodules. Submodule points to the concrete commit, not to a master

![](https://i.imgur.com/BJIGHwO.png)

https://github.com/msgpack/msgpack-c/tree/46684265d50b5d1b062d4c5c428ba08462844b1d

**Comment by leosunli** [comment]
Hi @filimonov 
I  don't understand that you say Submodule points to the concrete commit.
Could you help me explain in more detail？
Thanks
