### ISSUE TITLE
Unable to startup clickhouse

### ISSUE THREAD

**Issue by songjh513** [ClickHouse/ClickHouse#20031]
i try to restart clickhouse-server
here is all log :
[root@ch1 clickhouse-server]# ll
total 4
-rw-r-----. 1 clickhouse clickhouse      0 Feb   3 04:32 clickhouse-server.err.log
-rw-r-----. 1 clickhouse clickhouse      0 Feb   3 04:32 clickhouse-server.log
-rw-r-----. 1 clickhouse clickhouse 994 Feb   3 04:32 stderr.log
-rw-r-----. 1 clickhouse clickhouse      0 Feb   3 04:32 stdout.log

stderr.log is:
`Logging trace to /var/log/clickhouse-server/clickhouse-server.log
Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = Exception: Cannot change directory to /var/lib/clickhouse/cores, Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x1257bcfc in /usr/bin/clickhouse
1. ? @ 0x898ff9a in /usr/bin/clickhouse
2. DB::Server::initialize(Poco::Util::Application&) @ 0x8e93041 in /usr/bin/clickhouse
3. Poco::Util::Application::run() @ 0x124c9bb5 in /usr/bin/clickhouse
4. DB::Server::run() @ 0x8e927d2 in /usr/bin/clickhouse
5. mainEntryClickHouseServer(int, char**) @ 0x8e89e0c in /usr/bin/clickhouse
6. main @ 0x8dc8791 in /usr/bin/clickhouse
7. __libc_start_main @ 0x22555 in /usr/lib64/libc-2.17.so
8. ? @ 0x8e2db5f in /usr/bin/clickhouse
 (version 20.8.4.11)
Logging trace to /var/log/clickhouse-server/clickhouse-server.log
Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = Exception: Cannot change directory to /var/lib/clickhouse/cores, Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x1257bcfc in /usr/bin/clickhouse
1. ? @ 0x898ff9a in /usr/bin/clickhouse
2. DB::Server::initialize(Poco::Util::Application&) @ 0x8e93041 in /usr/bin/clickhouse
3. Poco::Util::Application::run() @ 0x124c9bb5 in /usr/bin/clickhouse
4. DB::Server::run() @ 0x8e927d2 in /usr/bin/clickhouse
5. mainEntryClickHouseServer(int, char**) @ 0x8e89e0c in /usr/bin/clickhouse
6. main @ 0x8dc8791 in /usr/bin/clickhouse
7. __libc_start_main @ 0x22555 in /usr/lib64/libc-2.17.so
8. ? @ 0x8e2db5f in /usr/bin/clickhouse
 (version `20.8.4.11)``

sudo -u clickhouse /usr/bin/clickhouse-server --config-file /etc/clickhouse-server/config.xml
output:
`Processing configuration file '/etc/clickhouse-server/config.xml'.
Include not found: clickhouse_remote_servers
Include not found: clickhouse_compression
Couldn't save preprocessed config to /var/lib/clickhouse//preprocessed_configs/config.xml: Access to file denied: /var/lib/clickhouse//preprocessed_configs/config.xml
Logging trace to /var/log/clickhouse-server/clickhouse-server.log
Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
Logging trace to console
2021.02.03 05:04:56.846065 [ 17796 ] {} <Information> SentryWriter: Sending crash reports is disabled
2021.02.03 05:04:56.851238 [ 17796 ] {} <Trace> Pipe: Pipe capacity is 1.00 MiB
2021.02.03 05:04:56.928238 [ 17796 ] {} <Information> : Starting ClickHouse 20.8.4.11 with revision 54438, no build id, PID 17796
2021.02.03 05:04:56.928373 [ 17796 ] {} <Information> Application: starting up
2021.02.03 05:04:56.934623 [ 17796 ] {} <Trace> Application: Will mlockall to prevent executable memory from being paged out. It may take a few seconds.
2021.02.03 05:04:57.176691 [ 17796 ] {} <Trace> Application: The memory map of clickhouse executable has been mlock'ed
2021.02.03 05:04:57.177159 [ 17796 ] {} <Information> StatusFile: Status file /var/lib/clickhouse/status already exists - unclean restart. Contents:
PID: 14701
Started at: 2021-02-03 05:02:31
Revision: 54438

2021.02.03 05:04:57.177314 [ 17796 ] {} <Debug> Application: rlimit on number of file descriptors is 262144
2021.02.03 05:04:57.177343 [ 17796 ] {} <Debug> Application: Initializing DateLUT.
2021.02.03 05:04:57.177359 [ 17796 ] {} <Trace> Application: Initialized DateLUT with time zone 'America/New_York'.
2021.02.03 05:04:57.177394 [ 17796 ] {} <Debug> Application: Setting up /var/lib/clickhouse/tmp/ to store temporary data in it
2021.02.03 05:04:57.178605 [ 17796 ] {} <Debug> Application: Configuration parameter 'interserver_http_host' doesn't exist or exists and empty. Will use 'ch1.pinghang.com' as replica host.
2021.02.03 05:04:57.180159 [ 17796 ] {} <Debug> ConfigReloader: Loading config '/etc/clickhouse-server/users.xml'
Processing configuration file '/etc/clickhouse-server/users.xml'.
Include not found: networks
Include not found: networks
Include not found: networks
Couldn't save preprocessed config to /var/lib/clickhouse//preprocessed_configs/users.xml: Access to file denied: /var/lib/clickhouse//preprocessed_configs/users.xml
2021.02.03 05:04:57.180558 [ 17796 ] {} <Debug> ConfigReloader: Loaded config '/etc/clickhouse-server/users.xml', performing update on configuration
2021.02.03 05:04:57.181128 [ 17796 ] {} <Debug> ConfigReloader: Loaded config '/etc/clickhouse-server/users.xml', performed update on configuration
2021.02.03 05:04:57.181606 [ 17796 ] {} <Information> Application: Setting max_server_memory_usage was set to 113.22 GiB (125.80 GiB available * 0.90 max_server_memory_usage_to_ram_ratio)
2021.02.03 05:04:57.181637 [ 17796 ] {} <Information> Application: Loading metadata from /var/lib/clickhouse/
2021.02.03 05:04:57.185796 [ 17796 ] {} <Information> DatabaseAtomic (system): Total 6 tables and 0 dictionaries.`

how to solve it ?

**Comment by bobliugq** [comment]
I got same error

**Comment by JohnTeslaa** [comment]
i got same error too

**Comment by tangtaocode** [comment]
I got same error

**Comment by alexey-milovidov** [comment]
It may happen if `clickhouse` user cannot create directories in `/var/lib/clickhouse`
Check the access rights and the path in configuration file.
