### ISSUE TITLE
Concurrently write to different replicas of the same shard, are there any performance issues or other problem？

### ISSUE THREAD

**Issue by Sallery-X** [ClickHouse/ClickHouse#20038]

**Comment by nvartolomei** [comment]
We do that successfully for small and large workloads. There are some tradeoffs, mostly specific to how big the batches are, normal mergetree tables vs. aggregation* merge tree tables and so on.

**Comment by alexey-milovidov** [comment]
No issues. Total throughput will be better with concurrent writes to different replicas.
