### ISSUE TITLE
How to pass "time" function data in clickhouse

### ISSUE THREAD

**Issue by RohanJ24** [ClickHouse/ClickHouse#20040]
I have mysql table which consist fields `(from_time, to_time)` having `time` data type. Here is below my table description and some data from that table.
![Screenshot from 2021-02-03 19-44-23](https://user-images.githubusercontent.com/47451568/106762509-e8e04100-665b-11eb-9f49-18250f66440c.png)
![Screenshot from 2021-02-03 19-45-17](https://user-images.githubusercontent.com/47451568/106762548-f269a900-665b-11eb-95b3-01dae217813b.png)
I want to migrate mysql data to clickhouse. Clickhouse accepts the `time` data type field as a `string` in schema. But when I try to dump data from mysql to clickhouse it shows me following error :
`CRITICAL:ex='datetime.timedelta' object has no attribute 'encode'
`
Is there any solution ?

**Comment by den-crane** [comment]
>But when I try to dump data from mysql to clickhouse it shows me following error :

Dump how?

>CRITICAL:ex='datetime.timedelta' object has no attribute 'encode' 

It does not look like CH error.

**Comment by RohanJ24** [comment]
> It does not look like CH error.

Then what will be the data type of clickhouse which accepts only "time" data.
Example : 20:00:00

**Comment by RohanJ24** [comment]
> Dump how?

By using following command 
`clickhouse-mysql --src-host={mysql_host} --src-user={mysql_user} --src-password={mysql_password} --dst-host={ch_host} --dst-user={ch_user} --dst-password={ch_password} --migrate-table --src-tables={db}.{table_name}  --dst-schema {db} --dst-table {table_name}`

**Comment by alexey-milovidov** [comment]
`clickhouse-mysql` is a third-party tool. You can ask questions in their repository.
