### ISSUE TITLE
Missing logs for ZooKeeperUserExceptions

### ISSUE THREAD

**Issue by ben-efiz** [ClickHouse/ClickHouse#20048]
**Describe the issue**
I have `ReplicatedReplacingMergeTree` on one shard and two replicas managed by ZooKeeper all running on a Kubernetes cluster managed by [clickhouse-operator](https://github.com/Altinity/clickhouse-operator). The setup works fine, data is being replicated correctly but the Prometheus metrics report several `ZooKeeperUserExceptions`. ClickHouse is not logging those exception, not even on trace level so i have no chance on seeing what the issues are about.

**How to reproduce**
* ClickHouse server version 21.1.2
* ZooKeeper 3.6.1
* `CREATE TABLE` with `ReplicatedReplacingMergeTree` as engine
* Set logger level to `Trace`
```
<logger>
    <level>trace</level>
    <log>/var/log/clickhouse-server/clickhouse-server.log</log>
    <errorlog>/var/log/clickhouse-server/clickhouse-server.err.log</errorlog>
    <size>1000M</size>
    <count>10</count>
</logger>
```
* Grep logs for anything which might be related to the [error messages](https://github.com/ClickHouse/ClickHouse/blob/ac989f3a8fe8e2135e25ac7d6e340b048092e906/src/Common/ZooKeeper/IKeeper.cpp#L85), e.g.
```
 grep -i -E "No node|Bad version|No children for ephemerals|Node exists|Not empty" -r /var/log/clickhouse-server/
```
* No information on how to reproduce as i can't see the root cause in the missing logs.

**Expected behavior**
If Prometheus metrics are reporting `ZooKeeperUserExceptions` i want to see them also in the logs. It seems they are not fatal errors, but normally i would expect them to see on logger level `Error` already, otherwise `Debug` at least `Trace`.

**Error message and/or stacktrace**
No stacktrace as i can't see the exceptions in the missing logs.

**Additional context**
I first thought its related to the ClickHouse Kubernetes [operator](https://github.com/Altinity/clickhouse-operator) so i opened a ticket [there](https://github.com/Altinity/clickhouse-operator/issues/642) with additional details but we found out its rather a ClickHouse logger issue.

When looking at the implementation you can find the profile events increment here https://github.com/ClickHouse/ClickHouse/blob/ac989f3a8fe8e2135e25ac7d6e340b048092e906/src/Common/ZooKeeper/IKeeper.cpp#L28

The places using [`Coordination::isUserError(Error code)`](https://github.com/ClickHouse/ClickHouse/blob/ac989f3a8fe8e2135e25ac7d6e340b048092e906/src/Common/ZooKeeper/IKeeper.h#L102) are not really logging anything beside one `LOG_INFO` in a specific condition https://github.com/ClickHouse/ClickHouse/blob/d601faa6695f2f1748afd508a33295fefca53f90/src/Storages/MergeTree/ReplicatedMergeTreeBlockOutputStream.cpp#L419

I would expect more logs in that context or the correctly thrown Exceptions being logged where catched.

**Comment by alexey-milovidov** [comment]
`ZooKeeperUserExceptions` does not indicate errors. They are part of the logic of distributed coordination.
They can appear due to multiple various reasons.

Example:
```
    else if (code == Coordination::Error::ZBADVERSION)
    {
        ProfileEvents::increment(ProfileEvents::NotCreatedLogEntryForMerge);
        LOG_TRACE(log, "Log entry is not created for merge {} because log was updated", merged_name);
        return CreateMergeEntryResult::LogUpdated;
    }
```

- retrying of multi-transaction.

**Comment by ben-efiz** [comment]
@alexey-milovidov thx for the follow up. While your example shows a `LOG_TRACE` quite a few of the others ZooKeeper exceptions don't have **any** log. So in my case i have ~20k `ZooKeeperUserExceptions` being reported by Prometheus but no idea what's the reason behind. Even not with logger level set to `Trace`.

Looking at https://github.com/ClickHouse/ClickHouse/blob/d601faa6695f2f1748afd508a33295fefca53f90/src/Storages/MergeTree/ReplicatedMergeTreeBlockOutputStream.cpp#L412

i can see that there is only one `LOG_INFO` but nothing in case
`else if (multi_code == Coordination::Error::ZNODEEXISTS && failed_op_path == quorum_info.status_path)`
or in the final else. So i would expect something like (just as an example)

```
            else if (multi_code == Coordination::Error::ZNODEEXISTS && failed_op_path == quorum_info.status_path)
            {
                LOG_TRACE(log, "Transaction rollback: Another quorum insert has been already started."); // added
                transaction.rollback();
                throw Exception("Another quorum insert has been already started", ErrorCodes::UNSATISFIED_QUORUM_FOR_PREVIOUS_WRITE);
            }
            else
            {
                LOG_TRACE(log, "Transaction rollback: {}", Coordination::errorMessage(multi_code)); // added
                /// NOTE: We could be here if the node with the quorum existed, but was quickly removed.
                transaction.rollback();
                throw Exception("Unexpected logical error while adding block " + toString(block_number) + " with ID '" + block_id + "': "
                                + Coordination::errorMessage(multi_code) + ", path " + failed_op_path,
                                ErrorCodes::UNEXPECTED_ZOOKEEPER_ERROR);
            }
```

Or maybe better at one place
https://github.com/ClickHouse/ClickHouse/blob/ac989f3a8fe8e2135e25ac7d6e340b048092e906/src/Common/ZooKeeper/IKeeper.cpp#L28
```
Exception::Exception(const std::string & msg, const Error code_, int)
    : DB::Exception(msg, DB::ErrorCodes::KEEPER_EXCEPTION), code(code_)
{
    if (Coordination::isUserError(code))
    {
        ProfileEvents::increment(ProfileEvents::ZooKeeperUserExceptions);
        LOG_TRACE(log, "Error code: {} {}", code, msg)
    }
    else if (Coordination::isHardwareError(code))
        ProfileEvents::increment(ProfileEvents::ZooKeeperHardwareExceptions);
    else
        ProfileEvents::increment(ProfileEvents::ZooKeeperOtherExceptions);
}

```

**Comment by alexey-milovidov** [comment]
I think these are just too low-level to be logged. Maybe better to simply remove `ZooKeeperUserExceptions` from your monitoring? It's like some technical low-level event and there are no much insight to get from it.

Also we are using `Trace` level by default and on our production servers. We don't want to make it too verbose.

Though maybe we can add these logs and it's going to be fine...

Also we have intention to add `system.zookeeper_log` table that will log all interaction with ZooKeeper. Looks like the solution for this task?

**Comment by ben-efiz** [comment]
@alexey-milovidov ok understood. I think `system.zookeeper_log` makes sense then. Maybe also naming it different then error/exceptions? Because this is also what i see when querying `system.errors`

```
SELECT *
FROM system.errors
ORDER BY value DESC

┌─name───────────────────┬─code─┬─value─┐
│ KEEPER_EXCEPTION       │  999 │ 19920 │
│ UNKNOWN_IDENTIFIER     │   47 │     1 │
│ SYNTAX_ERROR           │   62 │     1 │
│ CANNOT_OPEN_FILE       │   76 │     1 │
│ NO_ELEMENTS_IN_CONFIG  │  139 │     1 │
│ TOO_MANY_ROWS_OR_BYTES │  396 │     1 │
└────────────────────────┴──────┴───────┘
```

And of course i would like to know about those ~20k `KEEPER_EXCEPTION`s which are all `ZooKeeperUserExceptions` reported by the Prometheus metrics.

**Comment by alexey-milovidov** [comment]
https://github.com/ClickHouse/ClickHouse/issues/25449
