### ISSUE TITLE
New datatype -- RawBinary(n) based on FixedString

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#20042]
RawBinary(3) stored as 3 bytes. But allows to insert and select this as hex() unhex() automagically.

```sql
create table rb_store( rb_col RawBinary(3) ) engine = Memory;

insert into rb_store( rb_col ) values ('000000'),  ('121212'), ('ffffff')

select  rb_col from rb_store;

000000
121212
ffffff
```

@akuzm : _probably,  you can do by analogy with IPv6  (DataTypeCustomIPv6Serialization)_

**Comment by UnamedRus** [comment]
Probably it would make sense to have something like RawBinaryWithCharSet(size, '0-9A-Za-z') too.

It would help when we have bigger possible charset than just hex. (base64)

**Comment by alexey-milovidov** [comment]
I would not like if it will be implemented before user defined types.

**Comment by filimonov** [comment]
#18568 #4420
