### ISSUE TITLE
Max elements in the array

### ISSUE THREAD

**Issue by cnkang** [ClickHouse/ClickHouse#20059]
The document https://clickhouse.tech/docs/en/sql-reference/functions/array-functions/#rangeend-rangestart-end-step
says 
"an exception is thrown if arrays with a total length of more than 100,000,000 elements are created in a data block."
According to the document, the total elements can be 100 million

but when I run "select has(range(1,100000000),1) as res", the server gives me an error:
ClickHouse exception, code: 128, host: 127.0.0.1, port: 37872; Code: 128, e.displayText() = DB::Exception: Array of size 99999999 is too large to be manipulated as single field, maximum size 1000000: While processing has(range(1, 100000000), 1) AS res (version 20.12.2.1 (official build))

The error message says, the max size can only be 1 million
is it something wrong in the document or any setting on the server can be adjusted?  Thanks.

**Comment by den-crane** [comment]
Nothing wrong here. It's another limit.

Single array max size = 1mil 
https://github.com/ClickHouse/ClickHouse/blob/486418d112b8d97eccbed1bf9317e5b5870da381/src/Columns/ColumnArray.cpp#L44

Range function = 100 mil per block.

With range per block you'll get **A call to function range would produce 100016599 array elements, which is greater than the allowed maximum of 100000000**

https://github.com/ClickHouse/ClickHouse/blob/master/src/Functions/array/range.cpp#L29
