### ISSUE TITLE
ch start failed: Caught exception while loading metadata:

### ISSUE THREAD

**Issue by peaksnail** [ClickHouse/ClickHouse#20055]
2021.02.04 10:53:13.119713 [ 27702 ] {} <Error> Application: Caught exception while loading metadata: Poco::Exception. Code: 1000, e.code() = 111, e.displayText() = Connection refused: 47.106.193.101:7017, Stack trace (when copying this message, always include the lines below):

0. Poco::IOException::IOException(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x13cda46c in /usr/bin/clickhouse
1. Poco::Net::ConnectionRefusedException::ConnectionRefusedException(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x13bf7299 in /usr/bin/clickhouse
2. ? @ 0xa1a7374 in /usr/bin/clickhouse
3. Poco::Net::SocketImpl::connect(Poco::Net::SocketAddress const&) @ 0x13c0ccb9 in /usr/bin/clickhouse
4. Poco::MongoDB::Connection::Connection(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x11b5f404 in /usr/bin/clickhouse
5. DB::StorageMongoDB::StorageMongoDB(DB::StorageID const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned short, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, DB::Context const&) @ 0x1177c4d5 in /usr/bin/clickhouse
6. ? @ 0x1177d5af in /usr/bin/clickhouse
7. DB::StorageFactory::get(DB::ASTCreateQuery const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, DB::Context&, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, bool) const @ 0x10f1fbc6 in /usr/bin/clickhouse
8. DB::createTableFromAST(DB::ASTCreateQuery, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool) @ 0x11516e5f in /usr/bin/clickhouse
9. ? @ 0x1151e6e1 in /usr/bin/clickhouse
10. ? @ 0x1151f02d in /usr/bin/clickhouse
11. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0xa43d6ad in /usr/bin/clickhouse
12. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()&&...)::'lambda'()::operator()() const @ 0xa43dd93 in /usr/bin/clickhouse
13. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa43cc4d in /usr/bin/clickhouse
14. ? @ 0xa43b3ff in /usr/bin/clickhouse
15. start_thread @ 0x7dd5 in /usr/lib64/libpthread-2.17.so
16. __clone @ 0xfdead in /usr/lib64/libc-2.17.so
 (version 20.8.3.18)
2021.02.04 10:53:13.119847 [ 27702 ] {} <Information> Application: Shutting down storages.
2021.02.04 10:53:13.119863 [ 27702 ] {} <Information> Context: Shutdown disk default
2021.02.04 10:53:13.119941 [ 27729 ] {} <Trace> SystemLog (system.query_log): Terminating
2021.02.04 10:53:13.122805 [ 27702 ] {} <Debug> Application: Shut down storages.
2021.02.04 10:53:13.123002 [ 27702 ] {} <Debug> Application: Destroyed global context.
2021.02.04 10:53:13.124306 [ 27702 ] {} <Error> Application: Connection refused: 47.106.193.101:7017
2021.02.04 10:53:13.124362 [ 27702 ] {} <Information> Application: shutting down
2021.02.04 10:53:13.124374 [ 27702 ] {} <Debug> Application: Uninitializing subsystem: Logging Subsystem
2021.02.04 10:53:13.124544 [ 27710 ] {} <Trace> BaseDaemon: Received signal -2
2021.02.04 10:53:13.124595 [ 27710 ] {} <Information> BaseDaemon: Stop SignalListener thread

hi team

how to resolve the problem? 

I find clickhouse-server try to connect port 7017 but I can't find any configuration about the port 

ch works before I restart the server, and I don't change the configuration

**Comment by zhangjmruc** [comment]
From the backtrace, we can see there is a table defined in ch with engine MongoDB(StorageMongoDB) with host_port as 47.106.193.101:7017.
To resolve this problem:
1. Check the status of MongoDB to make sure it can be connected.
2. If you have no idea of the problem table, you can choose to delete the metadata for it.  /var/lib/clickhouse/metadata/
