### ISSUE TITLE
a interest clickhouse bug

### ISSUE THREAD

**Issue by xjtuzxh** [ClickHouse/ClickHouse#20056]
![image](https://user-images.githubusercontent.com/24972760/106839237-c50f1080-66d8-11eb-9e8b-4235f8cfdc79.png)

```
select toDateTime(serverTime) from edw.ubt_30nodes_all
where serverTime BETWEEN '2020-10-31 99:59:00' and  '2020-10-31 99:99:99'
limit 10
```

the range of hour\minute\second is [0,100)

**Comment by alexey-milovidov** [comment]
ClickHouse is using implementation specific behaviour when hour/minute/second is out of range.
It may overflow to the next time period.

This is made for performance reasons - to avoid extra checks, and we have no plans to change it.
