### ISSUE TITLE
When I search something and use format CSVWithNames ,the result while lose one row 

### ISSUE THREAD

**Issue by 545593069** [ClickHouse/ClickHouse#20054]
When I search something and use format CSVWithNames ，the result was 94 row
![image](https://user-images.githubusercontent.com/41407474/106834393-56c65000-66d0-11eb-9810-3a7be97966c1.png)
I replace  “ format CSVWithNames” by "format CSV"，the data was 93 row and title also one line data
![image](https://user-images.githubusercontent.com/41407474/106834570-ad338e80-66d0-11eb-8686-89c60c1cebe5.png)
I remove  “ format ” condition，the data was 95 row and title was no data
![image](https://user-images.githubusercontent.com/41407474/106834712-e8ce5880-66d0-11eb-94fd-9eb292b6b2e9.png)
Repeated many times，I think this is a bug.
                                                      look forward to your reply.

**Comment by den-crane** [comment]
JDBC driver does not support SQL queries with Format.
In case of CSVWithNames JDBC takes the first line of the result as NamesAndTypes rows.
https://github.com/ClickHouse/clickhouse-jdbc/issues/555
