### ISSUE TITLE
[Question] Equivalent Hash Function in ClickHouse and Apache Spark

### ISSUE THREAD

**Issue by pan3793** [ClickHouse/ClickHouse#20076]
I found ClickHouse and Spark both support hash function `murmurHash3_32` and `xxHash64` , and from clickhouse source code, got `murmurHash3_32 seed=1361930890` and `xxHash64 seed=0`, but the sad thing is I got a total different result by using the same seed in these two engine.

Spark `FunctionRegistry`
```
expression[Murmur3Hash]("hash"),
expression[XxHash64]("xxhash64"),
```

clickhouse side: `select murmurHash3_32(1) => 3831157163`
spark side: `select hash(1, 1361930890) => -450058676`

Can anyone give me some suggestions?

**Comment by filimonov** [comment]
The hashing functions are the same.
Binary represenataion of number `1` may differ significantly. Number of bits (8/16/32/64/...), endlianless etc. 

Try using it on some byte sequence with fixed / platform independent representation.

**Comment by den-crane** [comment]
```sql

select murmurHash3_32((1));
┌─murmurHash3_32(1)─┐
│        3831157163 │
└───────────────────┘

select murmurHash3_32(toUInt16(1));
┌─murmurHash3_32(toUInt16(1))─┐
│                  2511813514 │
└─────────────────────────────┘

select murmurHash3_32(toUInt32(1));
┌─murmurHash3_32(toUInt32(1))─┐
│                  4226891818 │
└─────────────────────────────┘

select murmurHash3_32(toUInt64(1));
┌─murmurHash3_32(toUInt64(1))─┐
│                  1392991556 │
└─────────────────────────────┘
```

**Comment by pan3793** [comment]
Thanks for @filimonov @den-crane explanation, and I do did some tries with data type conversion before open the issue, but didn't got a expected equivalent result.

For example:
```
SELECT murmurHash3_32(toInt32(2))

┌─murmurHash3_32(toInt32(2))─┐
│                 1085422463 │
└────────────────────────────┘
```
```
scala> spark.sql("""select hash(2, 1361930890)""").show
+-------------------+
|hash(2, 1361930890)|
+-------------------+
|          110778980|
+-------------------+
```

And let's make  the question specific on some types and functions.

How can write the SQL for ClickHouse and Spark using hash function `murmurHash3_32` to get a same result for one `String`/`Int32`?

Would you please show a demo for this specific case? It would be greatly appreciated.

**Comment by den-crane** [comment]
@pan3793 check the string first 'abc'

```
SELECT murmurHash3_32('abc')

┌─murmurHash3_32('abc')─┐
│            3017643002 │
└───────────────────────┘
```

Need to verify that algo & seed are consistent

**Comment by filimonov** [comment]
Big endian (java) vs little endian (x86)?

**Comment by pan3793** [comment]
Still not got expected result with `murmurHash3_32`, but succeed with `xxHash64`

```
SELECT toInt32(murmurHash3_32('abc'))

┌─toInt32(murmurHash3_32('abc'))─┐
│                    -1277324294 │
└────────────────────────────────┘

SELECT toInt64(xxHash64('a'))

┌─toInt64(xxHash64('a'))─┐
│   -3292477735350538661 │
└────────────────────────┘

SELECT toInt64(xxHash64('abc'))

┌─toInt64(xxHash64('abc'))─┐
│      4952883123889572249 │
└──────────────────────────┘
```

```
spark.udf.register("murmurHash3_32", udf { str: String => Murmur3HashFunction.hash(UTF8String.fromString(str), StringType, hash=1361930890).toInt})

scala> spark.sql(""" select murmurHash3_32('abc') """).show
+---------+
| UDF(abc)|
+---------+
|659263176|
+---------+

spark.udf.register("xxHash64", udf { str: String => XxHash64Function.hash(UTF8String.fromString(str), StringType, hash=0L)})

scala> spark.sql(""" select xxHash64('a') """).show
+--------------------+
|              UDF(a)|
+--------------------+
|-3292477735350538661|
+--------------------+

scala> spark.sql(""" select xxHash64('abc') """).show
+-------------------+
|           UDF(abc)|
+-------------------+
|4952883123889572249|
+-------------------+
```

**Comment by den-crane** [comment]
I wonder , why do you  think that `murmurHash3_32 seed=1361930890` ?
I see 0 ?

void MurmurHash3_x86_32 ( const void * key, int len, uint32_t seed, void * out
MurmurHash3_x86_32(data, size, 0, bytes);

https://github.com/ClickHouse/ClickHouse/blob/bd81f43ecb33dfd160f54b97cebf533156d9565e/src/Functions/FunctionsHashing.h#L303


though, c++ is a gibberish for me.

**Comment by pan3793** [comment]
> I wonder , why do you think that murmurHash3_32 seed=1361930890 ?
I see 0 ?

Oops!  You are right, my fault, the search result actually in arrow submodule ...
