### ISSUE TITLE
Unable to delete/update data for one table 

### ISSUE THREAD

**Issue by kilik52** [ClickHouse/ClickHouse#20075]
At some point, i cannot delete data from one specific table. It's a single node server. And it's a simple deletion:

ALTER TABLE xx DELETE WHERE xxx=xxx

and the query engine returned me an id.  But i found the deletion is failed.

There is no any log in error log or log file. 

I can still query things, I can insert data. I can create another table and delete data from that. But I  cannot delete data from one specific table. 

Any idea how to find the reason?

ClickHouse server version 20.11.4 revision 54442.

**Comment by filimonov** [comment]
```
SELECT * FROM system.mutations WHERE ... 
SELECT * FROM system.replication_queue WHERE ... 
SELECT * FROM system.merges WHERE ... 
SELECT * FROM system.replicas WHERE ... 
```

**Comment by kilik52** [comment]
```` 
SELECT * FROM system.mutations WHERE is_done = 0
````

Mutations get blocked since i called this:

````SQL
UPDATE `取消原因` = joinGet('order_join', 'r1', `第三方订单ID`), `取消原因二级分类` = joinGet('order_join', 'r2', `第三方订单ID`) WHERE `日期` >= '2021-01-01 00:00:00' 
````

After that all mutaions such as:

````SQL
UPDATE `取消原因` = '1' WHERE `订单号` = '210131232428901285'       
DELETE WHERE `日期` >= '2021-01-01 00:00:00'  
````

are all blocked.

nothing in replication_queue, merges, replicas.

and i've already removed Join Table: order_join
