### ISSUE TITLE
Is there a way to capture state of aggregations?

### ISSUE THREAD

**Issue by alex-klepa** [ClickHouse/ClickHouse#20084]
I tried following MV:
```sql
CREATE TABLE trades (
  time        DateTime64(3),
  stock_id    UInt16,
  price       Decimal64(4),
  size        UInt32
) ENGINE = MergeTree()
PARTITION BY toYYYYMM(time)
ORDER BY (stock_id, time)


CREATE MATERIALIZED VIEW ohlc
ENGINE = AggregatingMergeTree
PARTITION BY toDate(bucket)
ORDER BY (stock_id, bucket, slice)
POPULATE AS
SELECT
    stock_id,
    fromUnixTimestamp64Milli(toInt64(round((toUnixTimestamp64Milli(now64(3)) + 50) / 100) * 100)) slice, -- Timestamp rounded to 100ms
    bucket,
    count() AS trades,
    argMax(time, time) last_trade,
    argMin(price, time) AS open,
    max(price) AS high,
    min(price) AS low,
    argMax(price, time) AS close,
    sum(size) volume
FROM trades
GROUP BY stock_id, toStartOfMinute(time) as bucket;
```

I want to capture states of aggregation(1m) every 100 milliseconds, is that possible? I tried MV above - for existing data it will create just final "state", for real-time data 100ms aggregation not 1m.

**Comment by den-crane** [comment]
You have to use AggregateFunctions / States / Merge

```
CREATE MATERIALIZED VIEW ohlc
ENGINE = AggregatingMergeTree
PARTITION BY toDate(bucket)
ORDER BY (stock_id, bucket, slice)
POPULATE AS
SELECT
    stock_id,
    fromUnixTimestamp64Milli(toInt64(round((toUnixTimestamp64Milli(now64(3)) + 50) / 100) * 100)) slice
    bucket,
    countState() AS trades,
    argMaxState(time, time) last_trade,
    argMinState(price, time) AS open,
    maxState(price) AS high,
    minState(price) AS low,
    argMaxState(price, time) AS close,
    sumState(size) volume
FROM trades
GROUP BY stock_id, bucket, slice;

```

https://gist.github.com/den-crane/d03524eadbbce0bafa528101afa8f794
https://gist.github.com/den-crane/49ce2ae3a688651b9c2dd85ee592cb15
For max/count you can use SimpleAggregateFunction https://gist.github.com/den-crane/e326eef3b6ee6ccd5ca0df1dc1849a05

**Comment by den-crane** [comment]
MV is an insert trigger it never reads original table 

Check this:
https://den-crane.github.io/Everything_you_should_know_about_materialized_views_commented.pdf
https://youtu.be/ckChUkC3Pns?list=PLO3lfQbpDVI-hyw4MyqxEk3rDHw95SzxJ&t=9371

**Comment by alex-klepa** [comment]
Yes, I'm using AggregateFunctions / States / Merge, just edited it manually and forgot to add -State.
Thank you, that what I thought.
