### ISSUE TITLE
Cascade view prevents kafka from committing

### ISSUE THREAD

**Issue by simpl1g** [ClickHouse/ClickHouse#20086]
ClickHouse server version 20.8.9 revision 54438

Imagine we have the following structure of tables

kafka_queue ->  mv1 -> mergetree1 -> mv2 -> mergetree2

If we push to kafka message which cannot be processed by mv2(for example wrong data type) message will be inserted to mergetree1, but CH will not commit to kafka that message was processed. So in the end message will be inserted to mergetree1 infinite amount of times

How to reproduce

Create all tables
```SQL
CREATE TABLE dummy_queue (
  app_id String
) ENGINE = Kafka('{kafka_brokers_stage}', 'dummy_queue', 'stage-dummy_ch_queue', 'JSONEachRow');

CREATE MATERIALIZED VIEW dummy_mv TO dummy (
  app_id String
) AS SELECT app_id FROM dummy_queue;

CREATE TABLE dummy (
  app_id String
) ENGINE = MergeTree ORDER BY (app_id);

CREATE TABLE dummy_cascade (
  app_id UInt32
) ENGINE = MergeTree ORDER BY (app_id);

CREATE MATERIALIZED VIEW dummy_cascade_mv TO dummy_cascade
AS SELECT toUInt32(app_id) * 2 AS app_id FROM dummy;
```
Insert record that can be parsed
```
kafkacat -b kafka -t dummy_queue -P
{"app_id":"2"}
```
Watch that dummy_cascade table filled
```SQL
SELECT *
FROM dummy_cascade

┌─app_id─┐
│      4 │
└────────┘
```
Insert record that cannot be parsed
```
kafkacat -b kafka -t dummy_queue -P
{"app_id":"test"}
```
dummy_cascade table don't have new records, because of parsing error `DB::Exception: Cannot parse string 'test' as UInt32: syntax error at begin of string`
```SQL
SELECT *
FROM dummy_cascade

┌─app_id─┐
│      4 │
└────────┘
```

However in intermediate table dummy will be a lot of duplicate records, and the number of records will be growing and growing

```SQL
SELECT *
FROM dummy

┌─app_id─┐
│ 2      │
│ test   │
│ test   │
│ test   │
│ test   │
│ test   │
└────────┘
┌─app_id─┐
│ test   │
└────────┘
┌─app_id─┐
│ test   │
└────────┘

**Comment by den-crane** [comment]
By design.

Insert is successful only all inserts into dependent materialized views succeeded.
Then commit into kafka happen.

**Comment by simpl1g** [comment]
It's a strange design, I would expect such behavior if mv2 was connected to kafka_queue directly. However in this case mv2 doesn't care how data is written to mergetree1, why should queue fail. Also in case of problem it is easier to write data from mergetree1 to mergetree2 from scratch, than to think how to deduplicate it in mergetree1.

I expect that data is written to mergetree1 and committed if all mv connected to queue directly worked

**Comment by filimonov** [comment]
Kafka don't know if the first level table is real MergeTree, or for example engine=Null (when only second level MVs matter).
