### ISSUE TITLE
SELECT * LIMIT 1 FROM S3 table function reads all the data

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#20090]
``` sql
SELECT *
FROM default.hits_100m_obfuscated_s3_csv
LIMIT 1


Received exception from server (version 21.1.3):
Code: 241. DB::Exception: Received from localhost:9000. DB::Exception: Memory limit (for query) exceeded: would use 9.32 GiB (attempt to allocate chunk of 4198304 bytes), maximum: 9.31 GiB: While executing S3.

0 rows in set. Elapsed: 7.278 sec.
```

**Comment by daledude** [comment]
ClickHouse server version 21.2.3 revision 54447.

I run into this as well. Is it expected that Clickhouse will read all the data from S3 into memory before a query occurs? Is there a spill over to disk feature?

**Comment by daledude** [comment]
```set input_format_parallel_parsing=0;``` seems to "fix" running out of memory. I'm not clear exactly what this setting does.

**Comment by alexey-milovidov** [comment]
Shouldn't be the case anymore.
