### ISSUE TITLE
Perform algebraic optimizations of arithmetic expressions inside aggregate functions.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#20092]
Some aggregate functions are commutative with some arithmetic expressions.

```
avg(x + const) = avg(x) + const
```

This is applicable for aggregate functions: `sum`, `avg`, `min`, `max` and operations: `+`, `-`, `*`, `/` (but not for `intDiv` and `modulo`).

In case of integer overflow it either works correctly (for `sum`) or we may assume that integer overflow is implementation specific behaviour and apply optimization under this assumption.

**Possible implementation**

AST rewrite with InDepthNodeVisitor.
Should not rewrite if expression has alias.

**Comment by ucasFL** [comment]
I want to do this.

**Comment by alexey-milovidov** [comment]
That will be awesome!

**Comment by ucasFL** [comment]
In fact, for `sum`, `sum(x * const)  = sum(x) * const` and `sum(x / const) = sum(x) / const`, but `sum(x +/- const)` doesn't equal `sum(x) +/- const`. @alexey-milovidov

**Comment by ucasFL** [comment]
And in fact, this has been done in #18919. @alexey-milovidov

**Comment by alexey-milovidov** [comment]
@ucasFL I corrected the description.
Do we have optimization for `avg(x + const)`?

**Comment by alexey-milovidov** [comment]
```
milovidov-desktop :) EXPLAIN SYNTAX SELECT sum(number * 2) FROM system.numbers

EXPLAIN SYNTAX
SELECT sum(number * 2)
FROM system.numbers

Query id: f2a66469-d3a4-4548-813b-042798d334dd

┌─explain────────────────┐
│ SELECT sum(number) * 2 │
│ FROM system.numbers    │
└────────────────────────┘

2 rows in set. Elapsed: 0.001 sec. 

milovidov-desktop :) EXPLAIN SYNTAX SELECT avg(number * 2) FROM system.numbers

EXPLAIN SYNTAX
SELECT avg(number * 2)
FROM system.numbers

Query id: a95c3d45-4247-4535-9c61-7339e107b2ef

┌─explain────────────────┐
│ SELECT avg(number * 2) │
│ FROM system.numbers    │
└────────────────────────┘

2 rows in set. Elapsed: 0.001 sec. 

milovidov-desktop :) EXPLAIN SYNTAX SELECT avg(number + 2) FROM system.numbers

EXPLAIN SYNTAX
SELECT avg(number + 2)
FROM system.numbers

Query id: 106bebda-cfc6-4ef4-9d43-3a0703f5228e

┌─explain────────────────┐
│ SELECT avg(number + 2) │
│ FROM system.numbers    │
└────────────────────────┘

2 rows in set. Elapsed: 0.002 sec. 

milovidov-desktop :) EXPLAIN SYNTAX SELECT max(number + 2) FROM system.numbers

EXPLAIN SYNTAX
SELECT max(number + 2)
FROM system.numbers

Query id: 7bc442fd-f109-437c-94cf-20b16e8aa1e9

┌─explain────────────────┐
│ SELECT max(number) + 2 │
│ FROM system.numbers    │
└────────────────────────┘

2 rows in set. Elapsed: 0.001 sec. 
```

**Comment by alexey-milovidov** [comment]
Only first query is rewritten by default.

**Comment by ucasFL** [comment]
> Only first query is rewritten by default.

Yes, I checked that we have optimization for `sum`, `min` and `max` except `avg`.
