### ISSUE TITLE
Fuse some aggregate functions

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#20091]
Add aggregate function `sumCount`. This function returns a tuple of two fields: sum and count.

Add a setting `optimize_fuse_sum_count_avg`.
If it is enabled and query contains at least two aggregate functions from `sum`, `count`, `avg` of identical arguments, rewrite them to `sumCount(x).1`, `sumCount(x).2`, `sumCount(x).1 / sumCount(x).2`.

This setting should not be enabled by default to avoid incompatibilities in clusters where new and old server versions may work at the same time.

**Further directions**

Multiple `quantile` functions can be fused to single `quantiles`.

**Alternatives**

Compiled aggregator that we already had years ago but removed.

**Comment by hexiaoting** [comment]
I want to try it.

**Comment by alexey-milovidov** [comment]
Great, it will be wonderful!
