### ISSUE TITLE
runtime error: 3.09016e+09 is outside the range of representable values of type 'int'

### ISSUE THREAD

**Issue by nvartolomei** [ClickHouse/ClickHouse#20101]
**Describe the bug**
https://clickhouse-test-reports.s3.yandex.net/20088/d65f8ffb5189f43acae76c18f0b79d842e6ed59d/fuzzer_ubsan/report.html#fail1

**How to reproduce**
Try to reproduce the report and copy the tables and queries involved.

**Comment by alexey-milovidov** [comment]
Fixed.
