### ISSUE TITLE
Cannot remove input 0 because it has dependent nodes in ActionsDAG

### ISSUE THREAD

**Issue by nvartolomei** [ClickHouse/ClickHouse#20100]
**Describe the bug**
https://clickhouse-test-reports.s3.yandex.net/20088/d65f8ffb5189f43acae76c18f0b79d842e6ed59d/fuzzer_debug/report.html#fail1

**How to reproduce**
Try to reproduce the report and copy the tables and queries involved.

**Comment by KochetovNicolai** [comment]
#20073

**Comment by alexey-milovidov** [comment]
Duplicate #19914
