### ISSUE TITLE
Non-homogeneous behaviour of an index

### ISSUE THREAD

**Issue by nflorentin** [ClickHouse/ClickHouse#20104]
Hi, 

I'm seeing a behaviour which seems strange to me.

I've the following table:
```SQL
CREATE TABLE results(
  word_id UInt32,
  name String,
  day Date,
  yearWeek UInt32
) ENGINE = MergeTree()
PARTITION BY yearWeek
ORDER BY (day,name,word_id)
SETTINGS index_granularity = 8192;
```

My table is filled in an homogeneous way: for each yearWeek, I have 52 million distinct word_id and around 50 rows for each word_id so the number of rows for one yearWeek is 50 million * 50 = 2.5 billion rows.
In total there are 52 yearWeek so 52 * 2.5 billion = 130 billion rows in total in the **results** table.

I notice that very similar queries run in very different execution times:
```SQL
SELECT * FROM results WHERE results.word_id = 545 AND yearWeek = '202014';
```
=> 47 rows in results, run in 480ms (processed 1.85 billions rows at 3.72 billion rows/s)
```SQL
SELECT * FROM results WHERE results.word_id = 1 AND yearWeek = '202014';
```
=> 46 rows in results, run in 9.5 seconds (processed 1.85 billion rows at 193 million rows/s)

So my questions are:
- Is this normal ? Is there anything I can do to have more homogeneous result ?
- Does the order of the columns in the ORDER BY clause of my table creation code has an impact on it ? 
- Could the reason be that **name** in the index is non-monotonic ? 

Thanks in advance for your insights

Configuration:
Clickhouse 21.1.2.15 on ubuntu 20.04
32 cpu
128go ram
5to SSD disk

**Comment by amosbird** [comment]
> Is this normal ? Is there anything I can do to have more homogeneous result ?

Yes

> Does the order of the columns in the ORDER BY clause of my table creation code has an impact on it ?

Yes

> Could the reason be that name in the index is non-monotonic ?

No

Most likely you `word_id = 545` is clusterd in some range of `(day, name)` while `word_id = 1` is scattered around. If you have ORDER BY (word_id, day, name), the issue will be gone, however it might have other negative impacts for other queries.

**Comment by nflorentin** [comment]
@amosbird thanks a lot for your quick answer and for your work.
If there is any resource or document which go deeper into the subject of indexes, I would be more than interested ! 
Have a nice day.

**Comment by amosbird** [comment]
> If there is any resource or document which go deeper into the subject of indexes, I would be more than interested !

I'd recommend browsing through https://github.com/ClickHouse/clickhouse-presentations . It takes time but the journey will be fruitful.

**Comment by nflorentin** [comment]
@amosbird thank you for taking time to answer my questions
