### ISSUE TITLE
Lossy/Fuzzy codec compression algorithm?

### ISSUE THREAD

**Issue by mzealey** [ClickHouse/ClickHouse#20119]
**Use case**

Let's say we have a table of queries and add a column called `response_time` which is uncorrelated to any of the columns we are ordering by. We were doing this a `Float32` and it didn't compress much - perhaps 3.5 bytes used per row rather than 4. We could also try storing it as a `Int64` in microseconds, but it varies so much (may be 1us or 10s), again it doesn't seem like there is a good way to compress it well.

But actually in this case we don't need the retrieved value to be 100% accurate. So I suspect there should be some way to significantly improve compression ratios if you could say "We need the original value preserved, with an accuracy of X digits" or "within Y% of the original number" or something like this? So we could easily store 123 microseconds or 5.78 +- 0.02 seconds as we don't need to know it took 5.7912345 seconds exactly.

I'm guessing a more general feature of a lossy compression algorithm (within some guaranteed bounds) would probably find many other uses than this. So rather than `ZSTD()` you could do `LOSSY(some config params)` as the codec on column types that would support this. I guess even for some bit array types this may be useful.

**Alternatives**

I doubt that doing a simple truncate+store would actually improve compression very much at the moment with `Float32` types but I did not try this. And for the example above because of the wide range of possible values we'd have to use an `Int64` type if we were storing it all as microseconds, which also doesn't compress so well.

I guess an alternative could be a new type like `Float8` or some way to specify `Float(exponent, mantissa)` but even then would probably not have such good compression or flexibility as a lossy codec.

**Comment by alexey-milovidov** [comment]
You can round Float32 to BFloat16 this way:
```
SELECT 5.7912345::Float32 AS x, reinterpretAsFloat32(bitAnd(reinterpretAsUInt32(x), 0xFFFF0000))
```

After you do it, they will be compressed by ZSTD almost twice, and you'll get a lossy compression.

**Comment by alexey-milovidov** [comment]
`EPHEMERAL` column can be used:
https://clickhouse.com/docs/en/sql-reference/statements/create/table/#ephemeral
to let you insert a Float32 value but round it on the fly.
