### ISSUE TITLE
RBAC: add support to LOCK and UNLOCK user accounts using SQL commands

### ISSUE THREAD

**Issue by vzakaznikov** [ClickHouse/ClickHouse#20126]
Currently there is no way to LOCK or UNLOCK user accounts using RBAC SQL commands.

**Use case**
Locking an account is needed in various cases to temporarily block user from login without
completely dropping the user. 

**Describe the solution you'd like**
```sql
ALTER USER [ACCOUNT] LOCK/UNLOCK 
```

The `SHOW CREATE USER` should list user account and indicate if the account is locked.

The `SHOW USERS` command should not list locked users.

But we can add support to list all currently locked users.

```sql
SHOW LOCKED USERS
```

Locked accounts should not be allowed to login.

**Bonus feature**

 Add support for account locking policy. For example, lock account after 5 invalid login attempts or just lock account for some period of time.

**Comment by alexey-milovidov** [comment]
This would be a nice feature, but apparently, no one is willing to implement it.
