### ISSUE TITLE
InputFormat should allow to read subset of columns.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#20129]
**Use case**

`File`-like table engine with column oriented format (Native, Parquet, Arrow) under the hood.
For more quick data import and for serverless data processing.

**Comment by keen-wolf** [comment]
I'd like to take this one~

**Comment by alexey-milovidov** [comment]
Thank you, let's do it!

**Comment by nikitamikhaylov** [comment]
Done here #22299
