### ISSUE TITLE
Make format of clickhouse-server.log & clickhouse-server.err.log configurable

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#20130]
I would like to have a setting to log logfiles in JSONEachRow format (i.e.)
It allows to ingest LOGs using 3d-party tools , or by ClickHouse itself.

```
    <logger>
        <level>trace</level>
        <log>/var/log/clickhouse-server/clickhouse-server.log</log>
        <format>JSONEachRow</format>
...
```

possible formats JSONEachRow, TSV, CSV ...

**Comment by nvartolomei** [comment]
#12300

**Comment by SadiHassan** [comment]
@den-crane please check my comments [here at 35366](https://github.com/ClickHouse/ClickHouse/issues/35366).

**Comment by den-crane** [comment]
my current way is to parse logs with regex https://kb.altinity.com/altinity-kb-setup-and-maintenance/ch-logs-2-json-vectordev/

**Comment by nvartolomei** [comment]
#39277
