### ISSUE TITLE
Cascading materialized view querying upstream materialized view gets unexpected aggregations

### ISSUE THREAD

**Issue by jak2030** [ClickHouse/ClickHouse#20138]
I am confused by the behavior of one materialized view querying a second materialized view.

- create table A
- create TO materialized view B from A
- create TO materialized view C from B
- insert records to A

If C is:

```
select id, sum(amount) from B group by id
```

The results I see:

```
select sum(amount) from A group by id
```

**How to reproduce**

I'm using ClickHouse server v21.1.3. (current latest Docker image)

A full demo:

```
-- "warehouse" is allowed to contain duplicate "collection_id" records
CREATE TABLE warehouse
(
    `collection_id` String CODEC(LZ4),
    `rollup_id` String CODEC(LZ4),
    `version_timestamp` DateTime CODEC(LZ4),
    `timestamp` DateTime CODEC(LZ4),
    `amount` Float64 CODEC(Gorilla, LZ4)
)
ENGINE = MergeTree
ORDER BY (collection_id);

-- "latest" will dedupe "collection_id" by latest version_timestamp.
CREATE TABLE latest
(
    `collection_id` String CODEC(LZ4),
    `rollup_id` String CODEC(LZ4),
    `version_timestamp` DateTime CODEC(LZ4),
    `timestamp` DateTime CODEC(LZ4),
    `amount` Float64 CODEC(Gorilla, LZ4)
)
ENGINE = ReplacingMergeTree(version_timestamp)
ORDER BY collection_id;

-- Generate "latest" via a materialized view TO statement
CREATE MATERIALIZED VIEW latest_mv 
TO latest AS SELECT * from warehouse;

-- "rollup" aggregates by a "rollup_id"
-- note that the unexpected behavior outlined below occurs even if
-- using AggregateFunction types and State/Merge suffixes
CREATE TABLE rollup
(
    `rollup_id` String CODEC(LZ4),
    `timestamp` DateTime CODEC(LZ4),
    `amount` Float64 CODEC(Gorilla, LZ4)
)
ENGINE = AggregatingMergeTree()
ORDER BY rollup_id;

-- Generate "rollup" via a materialized view TO statement.
-- This should sums amounts and gets max timestamp from "latest"
CREATE MATERIALIZED VIEW rollup_mv 
TO rollup AS (
	SELECT
		rollup_id,
		max(timestamp) as timestamp,
		sum(amount) as amount
	FROM
		latest
	GROUP BY
		rollup_id
	ORDER BY
		rollup_id
);

-- Insert two records with expected behavior:
-- both records will appear in "warehouse" (true)
-- only latest by version_timestamp (second record) in "latest" (true)
-- aggregation only applied to records in latest (so a sum amount of 10 is expected) (false)
INSERT INTO warehouse FORMAT Values
	('A1', 'A', '2021-01-01 00:00:00', '2021-02-02 00:00:00', 10.0),
	('A1', 'A', '2021-02-01 00:00:00', '2021-02-02 00:00:00', 11.0);


-- querying the rollup table has the unexpected result of summing both records (10 + 11 == 21):
--
-- ┌─rollup_id─┬───────────timestamp─┬─amount─┐
-- │ A         │ 2021-02-02 00:00:00 │     21 │
-- └───────────┴─────────────────────┴────────┘
-- 
SELECT
	rollup_id,
	timestamp,
	amount
FROM
	rollup;
```

**Expected behavior**
I expect to see a sum amount of 10.0, as this is what is in the "latest" table. Instead, we see a sum amount of 21.0, which is what you get by summing the amounts in the original "warehouse" table.

**Comment by den-crane** [comment]
1. MV is an insert trigger. It gets data from insert. IT NEVER READS THE SOURCE TABLE. 
ENGINE OF THE SOURCE TABLE DOES NOT MATTER.

2. AggregatingMergeTree MUST BE USED with AggregateFunctions OR SimpleAggregateFunction
Now it simply corrupts `max(timestamp)` , sum(amount) DURING merges.

Check this:
https://den-crane.github.io/Everything_you_should_know_about_materialized_views_commented.pdf
https://youtu.be/ckChUkC3Pns?list=PLO3lfQbpDVI-hyw4MyqxEk3rDHw95SzxJ&t=9371

https://gist.github.com/den-crane/e326eef3b6ee6ccd5ca0df1dc1849a05
https://gist.github.com/den-crane/49ce2ae3a688651b9c2dd85ee592cb15
https://gist.github.com/den-crane/d03524eadbbce0bafa528101afa8f794

**Comment by jak2030** [comment]
Thank you for the fast reply! Really appreciate it. Will read through the links now.

>  IT NEVER READS THE SOURCE TABLE.

In this context, is "source" table A or B for:

- create table A
- create TO materialized view B
- create TO materialized view C
- insert into A

> AggregatingMergeTree MUST BE USED with AggregateFunctions OR SimpleAggregateFunction
> Now it simply corrupts max(timestamp) , sum(amount) DURING merges.

It's the same result if I use AggregateFunctions, so I guess my misunderstanding still arises around what the source table is. (https://gist.github.com/jak2030/afdce4e7b82aec6ed40db10dab40a5d8)

Again, thanks so much for the prompt response!

**Comment by den-crane** [comment]
Source table is the table is used in MV from section.

**Comment by karthikvt26** [comment]
I think a fairly similar use case of not being able to cascade the aggregated data further is the missing piece if I am not missing something here. There is another similar issue in this regard which is to coalesce information [here](https://github.com/ClickHouse/ClickHouse/issues/57240#issuecomment-2100860326)
