### ISSUE TITLE
would like AvgWeighted, var*Weighted, and stddev*Weighted functions

### ISSUE THREAD

**Issue by bubaflub** [ClickHouse/ClickHouse#2014]
Hi,

I'd like to request some new functions.  There are `quantile*Weighted` functions but no Weighted functions for simple statistics like average, variance, and the standard deviation.  I can do the weighting calculation in the query but I think functions would be easier to use, read, and understand.

Thanks!

**Comment by bubaflub** [comment]
If folks think it is a good idea I can put a PR up that implements what I'm suggesting.

**Comment by alexey-milovidov** [comment]
I think, it is good idea!
Looking forward for PR.

**Comment by bubaflub** [comment]
Great.  I'm thinking about implementing:

- CountWeighted
- SumWeighted
- AvgWeighted
- varSampleWeighted
- varPopWeighted
- stddevSampleWeighted
- stddevPopWeighted

I can add tests and documentation in English as well.

**Comment by alexey-milovidov** [comment]
Ok. 

Please be careful with naming. As we have function `sum`, the weighted should be named `sumWeighted`, and as we have `varSamp`, the weighted should be named `varSampWeighted`.

**Comment by Slind14** [comment]
At this point one could also consider adding a function for a T-Test (mean, std. dev., count) as well as T-Test(x)

**Comment by leif-larsen** [comment]
Has this been implemented yet?

**Comment by alexey-milovidov** [comment]
No.
