### ISSUE TITLE
Store data-skipping indexes on separate partition?

### ISSUE THREAD

**Issue by mzealey** [ClickHouse/ClickHouse#20157]
**Use case**

We have some very large tables that are infrequently accessed stored on hdd storage. We have added some data-skipping indexes (bloom filters) to speed up common search queries. It works well. However when doing the initial query it has to load the entire index. Testing on nvme shows we can easily process this at 2-3GB/sec, much higher than our hdd speed. Would it be possible to store the skipping indexes on separate volume/partition to speed this up?

**Comment by alexey-milovidov** [comment]
Maybe the `cache` disk will help.
