### ISSUE TITLE
Do we need to still use GROUP BY in MATERIALIZED VIEWS?

### ISSUE THREAD

**Issue by mzealey** [ClickHouse/ClickHouse#20162]
Following on from #16954, does it still make sense to write:

```
CREATE TABLE agg (
) ENGINE = AggregatingMergeTree()

CREATE MATERIALIZED VIEW mv TO agg AS SELECT ... FROM src GROUP BY ...
```

is it basically identical performance-wise to write it without the `GROUP BY` without any overheads or other costs (and probably making it much easier to insert bulk data without having to go via a Null table per #17239) ?

**Comment by alexey-milovidov** [comment]
Yes, after `optimize_on_insert` is enabled there is no reason to write GROUP BY in mat.view definition.

**Comment by alexey-milovidov** [comment]
Maybe it is still good for illustrative purposes.

Also maybe there are cases when GROUP BY in mat.view differs to the ORDER BY key of AggregatingMergeTree but I cannot imagine if they are useful.

**Comment by mzealey** [comment]
Seems to work perfectly in my testing - no need for Null engines or GROUP BY's any more. Great work!

**Comment by mzealey** [comment]
Hm actually I just came across a case where this is not working so well. I'm using cloudflare goflow and have an agg table like:

```
CREATE TABLE netflow_sum_proto_port (
    Time DateTime CODEC(DoubleDelta, LZ4),
    SamplerAddress IPv4 CODEC(ZSTD),
    ProtoName Enum8('ICMP'=1,'TCP'=6, 'UDP'=17,'other'=0),
    Port Int32,
    Flows SimpleAggregateFunction(sum, Float64),
    Packets SimpleAggregateFunction(sum, Float64),
    Bytes SimpleAggregateFunction(sum, Float64)
)
ENGINE = AggregatingMergeTree()
PARTITION BY toDate(Time)
ORDER BY (Time, SamplerAddress, ProtoName, Port);

drop view if exists netflow_sum_proto_port_mv;
CREATE MATERIALIZED VIEW netflow_sum_proto_port_mv TO netflow_sum_proto_port
AS SELECT
    toStartOfInterval(time, INTERVAL 30 SECOND) AS Time,
    reinterpretAsUInt32(reverse(SamplerAddress)) AS SamplerAddress,
    ProtoName,
    IF(Port in (443,80,0,445,993,143,2003,1443,3306,110,3389,22,21,23,995,25,53,19,587,2083,7000,1194,5060,4001,1198,389,123,1900,161,623,11211,131,132,133,134,135,136,137,138,139), Port, -1) Port,
    sum(Flows) AS Flows,
    sum(Packets) AS Packets,
    sum(Bytes) AS Bytes
FROM (
    SELECT
        toUInt32(TimeFlowEnd-TimeFlowStart+1) AS duration
        , arrayJoin(timeSlots(TimeFlowStart, duration, 1)) AS time
        , SamplerAddress
        , IF( Proto in (1,6,17), Proto, 0 ) AS ProtoName
        , arrayJoin([SrcPort, DstPort]) AS Port
        , 1.0 / 2 / duration AS Flows
        , toFloat32(Packets) / 2 / duration AS Packets
        , toFloat32(Bytes) / 2 / duration AS Bytes
    FROM netflow_flows
    WHERE Type = 'Netflow_9'
) t;
```

This is working fine, but if I truncate + insert historic data it goes very slow without the group by - if I add `GROUP BY Time, SamplerAddress, ProtoName, Port` on the end it goes about 20* faster inserting. I'm only using `max_insert_threads=1` so perhaps that is the difference as when doing the GROUP BY it seems to use quite a bit more CPU.

**Comment by alexey-milovidov** [comment]
Yes, it is expected: GROUP BY implementation (it's the same as used for SELECT queries) is faster than merging.

**Comment by alexey-milovidov** [comment]
So, the answer is: it still makes sense :)
