### ISSUE TITLE
 Cannot create MySQL database, because Code: 69, e.displayText() = DB::Exception: FixedString size must be positive,

### ISSUE THREAD

**Issue by imysm** [ClickHouse/ClickHouse#20172]
Clickhouse Version:ClickHouse client version 21.1.2.15 (official build).
MySQL.  Version:Server version: 8.0.21 MySQL Community Server - GPL
Action:
create database on Clickhouse with MySQL Engine.
`create DATABASE mysql_dcdb_13　ENGINE = MySQL('10.2.1.3:8809', 'dcdb', 'dc', 'Dc%A0dc1234');`
Error:
`Received exception from server (version 21.1.2):
Code: 501. DB::Exception: Received from localhost:9000. DB::Exception: Cannot create MySQL database, because Code: 69, e.displayText() = DB::Exception: FixedString size must be positive,`

**Comment by beeflyme** [comment]
also have this problem 
at : ClickHouse client version 21.1.1.5643 (official build).

**Comment by UprightNeether** [comment]
I meet the same problem. FixedString need a positive length,since there is no length<0 in mysql,find the column which length is 0

**Comment by tekeri** [comment]
Same problem.
I had issued `CREATE VIEW malformed AS SELECT NULL as bad_column;`  to trigger this. The inferred type is `binary(0)` and thus zero sized.
Workaround: use `CAST(NULL as EXPECTED_TYPE) AS good_column,` instead.

**Comment by wanglishuai** [comment]
use this sql to check which table's columns has the length < 1 
select * from information_schema.`COLUMNS` WHERE character_maximum_length < 1
i meet the same problem with this table has unormal attributes **binary(0)**
CREATE TABLE `testtable` (
  `obj_name` binary(0) DEFAULT NULL,
  `obj_id` binary(0) DEFAULT NULL,
  `zone_id` int(11) NOT NULL DEFAULT '0',
  `zone_name` varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8

**Comment by tbragin** [comment]
It appears that the problem is that ClickHouse automatically infers type for zero length columns as `binary(0)` which is not supported in MySQL. Users have suggested workarounds (see above), but the real solution probably should be change in behavior so that a different type is inferred, correct? 

Btw, I'm curious if folks are still experiencing these issues on the [most recent & supported versions](https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md#scope-and-supported-versions). I did not see any PRs aimed to fix this, so I would assume so.

**Comment by melvynator** [comment]
Does not seem to reproduce:

```
MySQL [test2]> CREATE TABLE testtable (
    -> obj_name binary(0) DEFAULT NULL,
    -> obj_id binary(0) DEFAULT NULL,
    -> zone_id int(11) NOT NULL DEFAULT '0',
    -> zone_name varchar(100) DEFAULT NULL
    -> ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
Query OK, 0 rows affected, 2 warnings (0.028 sec)
MySQL [test2]> INSERT INTO testtable (zone_id) VALUES (1);
Query OK, 1 row affected (0.005 sec)

MySQL [test2]> SELECT * FROM testtable;
+----------+--------+---------+-----------+
| obj_name | obj_id | zone_id | zone_name |
+----------+--------+---------+-----------+
| NULL     | NULL   |       1 | NULL      |
+----------+--------+---------+-----------+
1 row in set (0.003 sec)
```

ClickHouse:

```
CREATE DATABASE mysql_db2
ENGINE = MySQL('database-1.civz4ysn80n2.us-west-2.rds.amazonaws.com', 'test2', 'admin', 'mypassword')
SETTINGS read_write_timeout = 10000, connect_timeout = 100

Query id: a8975aef-3dcf-4862-a3e7-53f5e3a9e3e5

Ok.

0 rows in set. Elapsed: 0.025 sec.

SELECT *
FROM mysql_db2.testtable

Query id: 12a28904-101b-4c4a-9e59-596a4b87aa3e

   ┌─obj_name─┬─obj_id─┬─zone_id─┬─zone_name─┐
1. │ ᴺᵁᴸᴸ     │ ᴺᵁᴸᴸ   │       1 │ ᴺᵁᴸᴸ      │
   └──────────┴────────┴─────────┴───────────┘

1 row in set. Elapsed: 0.016 sec.
```
