### ISSUE TITLE
Create table with CTE not working in new version 21.2.2.8

### ISSUE THREAD

**Issue by stas-sl** [ClickHouse/ClickHouse#20187]
Just have updated CH to a new version 21.2.2.8 and suddenly the following statement stopped working

```sql
create table t engine = Memory as
with cte as (select * from numbers(10))
select * from cte
```
> DB::Exception: Table default.cte doesn't exist.

Could you kindly revert the old behavior - I liked it.

**Comment by alexey-milovidov** [comment]
@amosbird Could you please take a look?

**Comment by stas-sl** [comment]
That was fast, thanks!

**Comment by DipalPrajapati** [comment]
Hi  , I still face the issue in 4 node cluster. Please help. It was working earlier with 20.x.
