### ISSUE TITLE
Not equi-join ON expression: name = 'a'. No columns in one of equality side.: While processing name = 'a'. 

### ISSUE THREAD

**Issue by imysm** [ClickHouse/ClickHouse#20193]
Clichouse Version: ClickHouse client version 21.1.2.15 (official build).

Procedure:
`
cnsha175 :) select * from test;

SELECT *
FROM test

Query id: ebb5dc1a-4b97-4fd9-a12e-f44c71c5461a

┌─id─┐
│  6 │
└────┘
┌─id─┐
│  1 │
│  2 │
│  3 │
│  4 │
│  5 │
└────┘

6 rows in set. Elapsed: 0.002 sec. 

cnsha175 :) select * from test1;

SELECT *
FROM test1

Query id: 8f131091-9aad-4918-a143-aa968bff0a8e

┌─id─┬─name─┐
│  1 │ a    │
└────┴──────┘

1 rows in set. Elapsed: 0.001 sec. 

cnsha175 :)  select * from test inner join test1 on test.id=test1.id and test1.name='a';

SELECT *
FROM test
INNER JOIN test1 ON (test.id = test1.id) AND (test1.name = 'a')

Query id: 2d4a2a5a-56c1-4ec9-85b3-14a21e45ee40

Received exception from server (version 21.1.2):
Code: 403. DB::Exception: Received from localhost:9000. DB::Exception: Not equi-join ON expression: name = 'a'. No columns in one of equality side.: While processing name = 'a'. 

0 rows in set. Elapsed: 0.001 sec. 

cnsha175 :) 
`

**But I can use it like this in previous versions。**

**Comment by Zhile** [comment]
Has this been fixed? I think it's a bug.  This can be still reproduced in 21.2 version. 
@alexey-milovidov  Can you help to take a look?

**Comment by hexiaoting** [comment]
This query can run in version : 21.4.1.1
```
dell123 :) create table test (id Int) Engine=Memory;;

CREATE TABLE test
(
    `id` Int
)
ENGINE = Memory

Query id: bea26518-a41a-4441-b4c2-e5cd01299810

Ok.

0 rows in set. Elapsed: 0.030 sec.

dell123 :) create table test1 (id Int,name String) Engine=Memory;;

CREATE TABLE test1
(
    `id` Int,
    `name` String
)
ENGINE = Memory

Query id: b7a693ed-2a66-4782-8cc9-c011e76e20c6

Ok.

0 rows in set. Elapsed: 0.039 sec.

dell123 :) select * from test inner join test1 on test.id=test1.id and test1.name='a';

SELECT *
FROM test
INNER JOIN test1 ON (test.id = test1.id) AND (test1.name = 'a')

Query id: a479ec34-0238-4a21-b439-3ae63708cb5b

Ok.

0 rows in set. Elapsed: 0.030 sec.

dell123 :) select version();

SELECT version()

Query id: 7c4043e3-7329-4704-862b-a3b2099b590b

┌─version()─┐
│ 21.4.1.1  │
└───────────┘

1 rows in set. Elapsed: 0.012 sec.

```


But below query can not run in this version:
```
dell123 :) select * from test inner join test1 on test1.name='a';

SELECT *
FROM test
INNER JOIN test1 ON test1.name = 'a'

Query id: 185b98f9-4c60-4644-b3b4-6b81573336a1


0 rows in set. Elapsed: 0.014 sec.

Received exception from server (version 21.4.1):
Code: 403. DB::Exception: Received from localhost:9000. DB::Exception: Cannot get JOIN keys from JOIN ON section: name = 'a'.

```

**Comment by cnkang** [comment]
I tried with 21.7.6.36, same error:

ClickHouse exception, code: 403, host: 127.0.0.1, port: 42918; Code: 403, e.displayText() = DB::Exception: Not equi-join ON expression: name = 'a'. No columns in one of equality side.: While processing name = 'a' (version 21.7.6.39 (official build))

**Comment by vdimir** [comment]
> I tried with 21.7.6.36, same error:
> 
> ClickHouse exception, code: 403, host: 127.0.0.1, port: 42918; Code: 403, e.displayText() = DB::Exception: Not equi-join ON expression: name = 'a'. No columns in one of equality side.: While processing name = 'a' (version 21.7.6.39 (official build))

@cnkang 

What's query?

* `select * from test inner join test1 on test.id=test1.id and test1.name='a'` works fine in master.
* `select * from test inner join test1 on test1.name='a'` doesn't work but it's doesn't contain expression to join by, so it shouldn't

**Comment by vdimir** [comment]
Original comment is the same as https://github.com/ClickHouse/ClickHouse/issues/21868

**Comment by cnkang** [comment]
I see, I tested with` select * from test inner join test1 on test1.name='a'`

**Comment by vdimir** [comment]
> I see, I tested with` select * from test inner join test1 on test1.name='a'`

Thanks. Such query not supported yet. What behavior do you expect, could you come up with examples?

**Comment by AnatolySnegovskiy** [comment]
in version 21.8.3.44, it doesn't work again

**Comment by vdimir** [comment]
> in version 21.8.3.44, it doesn't work again

@AnatolySnegovskiy

Could you please provide what query (with schema and data) that are you trying to run?

**Comment by siradjev** [comment]
> Hi @vdimir, I want to clarify that we are talking about same case which is `select * from test inner join test1 on test.id=test1.id and test1.name='a' ` right? I'm not refering to `select * from test inner join test1 on test1.name='a'` case. I noticed that @hexiaoting mentioned that it worked fine in version `21.4.1.1`, so I was wondering if it should be working in version `21.8.8.29`.

I opened separate ticket for the problem. I agree with you that it should be working fine since it worked in two previous LTS releases.
