### ISSUE TITLE
MergeTree ORDER BY and Arrays

### ISSUE THREAD

**Issue by amirvaza** [ClickHouse/ClickHouse#20191]
Hi All,

Im trying to achieve a good scalable form of a nested model where a user can add any property to the data point
I have the following table:
```
CREATE TABLE nested_test
(
    `EventTime` DateTime64(3),
    `EventName` String,
    `EventProperties` Nested (
        `EventPropertyName` String,
        `EventPropertyValue` Nullable(String)
    )
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(EventTime)
ORDER BY (EventProperties.EventPropertyName)
SETTINGS index_granularity = 8192
```

Now I want to query by an EventPropertyName, for example:
```
SELECT COUNT(*) AS c
FROM nested_test
WHERE arrayExists(x -> (x = 'EProp1'), EventProperties.EventPropertyName)
```
For an unknown reason, at least not known to me, clickhouse reads the entire table instead of just the granules that it needs, even after optimizing.

**How to reproduce**
ClickHouse version: 21.1.2.15

1. Create the table above
2. `INSERT INTO nested_test SELECT 1, 'EName', ['EProp1'], ['EPValue1'] FROM system.numbers LIMIT 8192`
3. `INSERT INTO nested_test SELECT 1, 'EName', ['EProp2'], ['EPValue1'] FROM system.numbers LIMIT 8192`
4. Query:
```
SELECT COUNT(*) AS c
FROM nested_test
WHERE arrayExists(x -> (x = 'EProp1'), EventProperties.EventPropertyName)

Query id: 02518b68-d6d3-4cc1-b1a6-532a7f8d1d56

┌────c─┐
│ 8192 │
└──────┘

1 rows in set. Elapsed: 0.003 sec. Processed 16.38 thousand rows, 376.83 KB (5.05 million rows/s., 116.07 MB/s.)
                                             ^^^^^
```

**Expected behavior**
Processing 8192 rows (one graunle) instead of 16.38k (2 granules)

What am I doing wrong?
My first guess it ordering by array values isnt supported

Thanks.

**Comment by filimonov** [comment]
Clickhouse uses space index. Ordering by arrays is very bad idea

**Comment by alexey-milovidov** [comment]
ORDER BY array does not allows to locate individual entries in arrays.
https://en.wikipedia.org/wiki/Lexicographic_order
