### ISSUE TITLE
ClickHouse server congfiguration suggession 

### ISSUE THREAD

**Issue by Crazylearner30** [ClickHouse/ClickHouse#20197]
Hi Team,

Currently, we are on an **r5.4xlarge** machine with 16CPU's and 128 GB RAM and each table size is approximately 10TB.

Futureuse: We are planning to upgrade our database from 10TB to 20TB soon.

Note: each table is stored under a different server and works in a random load balancing env. 

Kindly suggest to us what will be the next best server configuration to handle 20TB of data on each server. 

Thank you.

**Comment by filimonov** [comment]
See 
https://clickhouse.tech/docs/en/operations/requirements/
https://blog.cloudflare.com/clickhouse-capacity-estimation-framework/
