### ISSUE TITLE
How to improve query perfermance on system.parts

### ISSUE THREAD

**Issue by Qsimple** [ClickHouse/ClickHouse#20209]
Hi dear dev team:
  We are developing some Table parts monitor by "SELECT xxx FROM system.parts". As time goes on, the stored data gets bigger and bigger, and parts directory gets more and more. The query on system.parts gets slower and slower.   
 we consume 6s to process 58k rows with sql "SELECT COUNT(1) FROM system.parts"

  I think the reason is the parts fetch the parts info from OS file system when ingest an query rather then store some data independent.  
  In those scenes, any suggestion to improve the query perfermance on system.parts?
                                                                                                                                               Tks, :)

**Comment by den-crane** [comment]
>We are developing some Table parts monitor

Can you clarify ? What for do you need `SELECT xxx FROM system.parts` ?

```
SELECT COUNT(active)
FROM system.parts

┌─COUNT(active)─┐
│         11155 │
└───────────────┘

1 rows in set. Elapsed: 0.827 sec. Processed 11.15 thousand rows
```

**Comment by filimonov** [comment]
See also https://github.com/ClickHouse/ClickHouse/issues/19570

To extract some info about part clickhouse need to do `stat` system call. Lot of calls = slow.

**Comment by Qsimple** [comment]
> > We are developing some Table parts monitor
> 
> Can you clarify ? What for do you need `SELECT xxx FROM system.parts` ?
> 
> ```
> SELECT COUNT(active)
> FROM system.parts
> 
> ┌─COUNT(active)─┐
> │         11155 │
> └───────────────┘
> 
> 1 rows in set. Elapsed: 0.827 sec. Processed 11.15 thousand rows
> ```
Like 

```sql
SELECT SUM(bytes_on_disk), SUM(rows) FROM system.parts GROUP BY database, table
```  

@filimonov  I think ClickHouse still need to call lots of `stat` to calc the sum bytes. tks

**Comment by Algunenano** [comment]
System.parts now shouldn't require extra syscalls for unrequired columns.

Summing numbers that are already in memory does not require syscalls.
