### ISSUE TITLE
Data Corruption // Invalid number of rows in Chunk (21.2.2.8)

### ISSUE THREAD

**Issue by gersmann** [ClickHouse/ClickHouse#20218]
I am having reproducible data corruption issues. Even deleted the clickhouse data directory and set up everything from scratch. 

I have a materialized view on top of a raw data table, which gets filled in chunks and has a JSON column, which the MV extracts data from.

After a couple of inserts (parquet files, about 10k records), the count(1) query starts to fail. 

```
DB::Exception: Invalid number of rows in Chunk column UInt8 position 0: expected 14840, got 6648: While executing MergeTreeThread (version 21.2.2.8 (official build))
```

Query: 
```
SELECT count(1) FROM trackings;
```

Error Log:

```
2021.02.08 21:56:29.077827 [ 49700 ] {d7af1139-0a83-442b-8ccd-de064b250ba8} <Warning> AWSClient: ClientConfiguration: Retry Strategy will use the default max attempts.
2021.02.08 21:56:30.257540 [ 49701 ] {d0a589b5-54cb-43f6-8fb7-700747bc55d0} <Error> executeQuery: Code: 49, e.displayText() = DB::Exception: Invalid number of rows in Chunk column UInt8 position 0: expected 14611, got 6419: While executing MergeTreeThread (version 21.2.2.8 (official build)) (from 127.0.0.1:55572) (in query: SELECT count(1) FROM trackings WHERE courier IS NOT null FORMAT TabSeparatedWithNamesAndTypes;), Stack trace (when copying this message, always include the lines below):

0. DB::Chunk::checkNumRowsIsConsistent() @ 0xf613833 in /usr/bin/clickhouse
1. DB::MergeTreeBaseSelectProcessor::readFromPartImpl() @ 0xf44a2d0 in /usr/bin/clickhouse
2. DB::MergeTreeBaseSelectProcessor::readFromPart() @ 0xf44aa5d in /usr/bin/clickhouse
3. DB::MergeTreeBaseSelectProcessor::generate() @ 0xf44927b in /usr/bin/clickhouse
4. DB::ISource::tryGenerate() @ 0xf61e8f5 in /usr/bin/clickhouse
5. DB::ISource::work() @ 0xf61e60a in /usr/bin/clickhouse
6. DB::SourceWithProgress::work() @ 0xf77977a in /usr/bin/clickhouse
7. ? @ 0xf65920d in /usr/bin/clickhouse
8. DB::PipelineExecutor::executeStepImpl(unsigned long, unsigned long, std::__1::atomic<bool>*) @ 0xf656001 in /usr/bin/clickhouse
9. ? @ 0xf65aa06 in /usr/bin/clickhouse
10. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x851158f in /usr/bin/clickhouse
11. ? @ 0x8515023 in /usr/bin/clickhouse
12. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
13. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
```

Table Defintion: 
``` 
CREATE MATERIALIZED VIEW trackings
ENGINE = ReplacingMergeTree(update_ts)
ORDER BY (created, user_id, oid)
PARTITION BY (toYYYYMM(created))
AS
SELECT 
    FROM_UNIXTIME(toInt32(JSONExtractInt(anyLast(_doc), 'created', '$date')/1000)) as created,
    anyLast(user_id) AS user_id,
    _id AS oid,
    JSONExtractString(anyLast(_doc), 'tracking_number') as tracking_number,
```

**Comment by alexey-milovidov** [comment]
Is it possible to share the files needed for reproducible scenario (maybe privately)?

**Comment by alexey-milovidov** [comment]
How does it relate to:
- parquet files: if you use files in different format, does the issue present?
- materialized view: if you insert data directly to the trackings table, does the issue present?
- s3 import/export (I see "AWSClient" message in log, how is it related)?
- usage of JSON functions: if you replace `JSONExtractInt` to something else, how does it change?

Is it possible to also check the issue on versions 21.1, 20.12 and 20.8?

**Comment by gersmann** [comment]
@alexey-milovidov I am currently testing 20.8.11.17 and don't have this issue. Maybe related to https://github.com/ClickHouse/ClickHouse/issues/10683?

**Comment by alesapin** [comment]
> @alexey-milovidov I am currently testing 20.8.11.17 and don't have this issue. Maybe related to #10683?

Hi! Maybe it's related to #10683, maybe not. It's very hard to guess without data/steps for error repro.

**Comment by gersmann** [comment]
I cannot share the data unfortunately, due to privacy concerns. I can close the issues, since I could resolve this via downgrading.

**Comment by alesapin** [comment]
> I cannot share the data unfortunately, due to privacy concerns. I can close the issues, since I could resolve this via downgrading.

You can use `clickhouse-obfuscator` to sample/obfuscate your private data. See instructions in `clickhouse-obfuscator --help` and in [link](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80)

**Comment by alesapin** [comment]
Also maybe it can be reproduced with some random data?

**Comment by gersmann** [comment]
The underlying data is in a string column as JSON. What I could do is to obfuscate the data after it has been extracted from JSON, not sure if that helps, but I'll try.

**Comment by alexey-milovidov** [comment]
@gersmann You can try set `optimize_on_insert` to 0 on version 21.2 to check the hypothesis.

> I can close the issues, since I could resolve this via downgrading.

We cannot close this issue until it's resolved.

**Comment by alesapin** [comment]
Hi @gersmann! Do you have any success with obfuscation or `optimize_on_insert`? It's really important, we will be glad if you provide any additional details for this issue.

**Comment by gersmann** [comment]
> Hi @gersmann! Do you have any success with obfuscation or `optimize_on_insert`? It's really important, we will be glad if you provide any additional details for this issue.

Hi @alesapin, how can we get in touch? PN?

**Comment by filimonov** [comment]
@gersmann any news here?

**Comment by alexey-milovidov** [comment]
No info was provided.
There were no similar reports.

**Comment by gersmann** [comment]
Hi @alexey-milovidov, sorry for not getting back earlier. I did anonymize the data, but there was still critical information in the data. Since we have moved on to use a different analytical DBMS I could not invest more time in this unfortunately.
