### ISSUE TITLE
is there a comparison of clickhouse vs kdb+

### ISSUE THREAD

**Issue by l1t1** [ClickHouse/ClickHouse#20210]
Kdb+Transitive Comparisons
https://kx.com/wp-content/uploads/2020 /11/KdbTransitive- Comparisons-1. pdf

**Comment by den-crane** [comment]
https://tech.marksblogg.com/benchmarks.html

**Comment by alexey-milovidov** [comment]
@l1t1 There is no version of kdb+ freely available for testing.
The only version that is possible to download is 32bit build with 4 GB data limit.
It makes all comparisons and benchmarks not reproducible and not trustworthy.

**Comment by l1t1** [comment]
https://ondemand.kx.com  64bits kdb+ for test

**Comment by l1t1** [comment]
https://anaconda.org/kx/kdb/files contains the binary files
