### ISSUE TITLE
User Friendly Cloud Table Design (RFC)

### ISSUE THREAD

**Issue by yiguolei** [ClickHouse/ClickHouse#20219]
# Problem
Current distributed table has the following problems:

- Each table can only have one shard on each node, so the number of shard in a table is bound to the number of nodes, but when number of node is expanded, the number of shards has been determined when the table is created, so the system could not move one shard to other node to rebalance data. Currently, the existing solution is to add an empty shard to the newly added node, and then write the incremental data to the new node. This method has the following disadvantages:
	- It is okay for the general merge tree table, but for some replacing merge tree tables, there is nothing you can do;
	- Historical data cannot be migrated, many users stop writing and then copy historical data to the new shard, which is very unfriendly to business;
- The replication relationship between replicas is actually the data replication relationship between nodes, because a table has only one shard on a node, and when there are 3 nodes in the system, there is no way to make 2 shards and 2 replicas. , 4 nodes are required; in addition, since the replica is defined at the cluster level, there is no way to create multiple tables in a cluster with different number of replicas;
- The definition of the shard and the definition of the replica are all in the configuration file, which needs to be manually modified by the user. The configuration file needs to be manually modified when the node expands and shrinks, and the maintenance cost is relatively high.
- Each local table needs the user to specify the path on ZK, and the user needs to ensure that no multiple tables point to the same ZK path. In fact, it is difficult for users to understand why ZK  is needed because zk is actually a module inside the system.

# New Cloud Table 

## Create table

```
CREATE TABLE [IF NOT EXISTS] [db.]table_name [ON CLUSTER cluster]
(
    name1 [type1] [NULL|NOT NULL] [DEFAULT|MATERIALIZED|ALIAS expr1] [compression_codec] [TTL expr1],
    name2 [type2] [NULL|NOT NULL] [DEFAULT|MATERIALIZED|ALIAS expr2] [compression_codec] [TTL expr2],
    ...
) ENGINE = MergeTree()
 
[Distributed by sharding key]
Settings vshard_num = 3, replica_num = 2，assign_vshard_policy='random'；
```

- vshard_num: indicates how many vshards are created
- replica_num: number of replcias for every vshard
- assign_vshard_policy is a distribution strategy from vshard to node. At the initial stage, you can consider assigning it randomly.
- sharding key definition

Both related local table and distributed table is called during create table. vshard is a local table actually. But it is different from current shard, because vshard num is not related with node num and a distributed table could have more than one vshard on a single node.

replica_num is related with node num, for example, if there are only 2 nodes, you can not create a vshard with 3 replicas.

## Insert 

```
INSERT INTO [db.]table [(c1, c2, c3)] VALUES (v11, v12, v13), (v21, v22, v23), ...
Settings vshard_id = 2
```

User does not need a local table here, just specify the distributed table name and vshard id, and the system automatically routes the data to specific vshard;
If shard_id is not specified, then the data will be allocated according to the sharding strategy in the table's sharding definition.

## Query

- Case 1: Just use distributed table

```
SELECT * FROM table_name
```

- Case 2: Sometimes, a query has to use local table to do colocated join, it has to use local table name in the query. In this case user could use distributed_table_name[v_shardid] instead of local table name.

```
SELECT * FROM cluster(`cluster_name`, view(SELECT a, b, c FROM table_name[v_shardid]))
```

## Rebalance Data

```
ALTER TABLE table_name
RELOCATE shard_id to node_ip:port
```

If a new node is added to the cluster, the administrator could use migrate function to move some vshards to the new node.

Later, you can consider introducing a coordinator node to maintain the load of each node in the cluster, and dynamically call the relocate command to complete the rebalance work.

# Solutions
![image](https://user-images.githubusercontent.com/9208457/107309084-c23f6180-6ac4-11eb-9eee-de0ff67af1ce.png)

In order to achieve the above functions, and to minimize the changes to the current CK code and maintain compatibility, the rough design scheme is as follows:

- When the user creates a distributed table, a distributed table is created on each machine in the cluster;
- When creating a distributed table, the user can specify the number of vshards, and the system directly distributes the vshards to multiple machines according to a certain distribution algorithm;
- Each vshard corresponds to a local table. Since user could not access vshard using the vshard name directly, so it can be directly idized, its name is a uuid. So that multiple local tables belonging to the same distributed table can be stored on one node.
- Store the following metadata information on zk:
	- Mapping from distributed table to vshard;
	- Mapping from vshard to replicas;
	- Mapping from replicas to nodes;
	- zk path for each replica;
- When reading data, directly rewrite the vshard query on a certain node into a merge table function; when the merge table function is executed, it calculates the list of vshards to be read locally based on the metadata in ZK.
- When inserting data, insert directly into vshard;

**Comment by filimonov** [comment]
See also 
https://github.com/ClickHouse/ClickHouse/issues/6772
https://clickhouse.yandex/blog/en/concept-cloud-mergetree-tables
https://github.com/ClickHouse/ClickHouse/issues/6357
https://github.com/ClickHouse/ClickHouse/issues/13574

**Comment by yiguolei** [comment]
@filimonov  I have read all three proposals. 
It has to modify the writing process and implement an internal queue in #6772. And "converhouse" implement an agent using GO which could not be integrated with current CK. And it dose not have any progress any more.

The proposal in #13574 is Moving Parts between shards. It is also currently used in Tencent Cloud ^-^. But it could not deal with ReplacingMergeTree Engine.  Since part is moved between shards, the sharding key is useless during query. So that could not do shard pruning during query.

Yandex's cloud merge table is the ideal proposal. But it is very difficult to implement the range partition and split procedure. 

My current proposal is similar to the vshard method in Yandex's cloud table proposal  but without vshard split. And it is very easy to implement.

**Comment by mdianjun** [comment]
@yiguolei 
> But it could not deal with ReplacingMergeTree Engine.
Could you explain this reason more detailed? 3Q.

**Comment by godliness** [comment]
@yiguolei  What if when insert date into the vshard which is relocating to another node?

**Comment by yiguolei** [comment]
> @yiguolei
> 
> > But it could not deal with ReplacingMergeTree Engine.
> 
> Could you explain this reason more detailed? 3Q.

In ReplacingMergeTree table engine, data is distributed among all nodes according to the sharding key, the sharding key is part of "**primary key**". And Merging process will merge the records with same primary to to one record. So that all records with same primary key has to be on the same node. For example, there are 4 nodes at the beiginning, then all data is distributed according to hash(sharding key) % 4, If one node is added to the cluster, then all records should be redistributed according to the new sharding map hash(sharding key) % 5.  All data must be redistributed instead of just relocating a few parts.

**Comment by yiguolei** [comment]
> @yiguolei What if when we insert data into the vshard which is relocating to another node?

During relocating, one replica is added to the replica group. It is just like add a new replica in current **Shard**. And all data insert into the vshard will replicated to all replicas in the replica group. And the newly added replica is also fetch the old parts from other replicas. If the process is done, then the old replica is dropped.

**Comment by qoega** [comment]
IMHO I see several downsides of the proposal:
1) vshard key can be misused by a user and data will be distributed with misbalance. Some shards can be overloaded and other can be almost empty. There can appear a new problem to autobalance vshards.
2) if user defines vshard key manually it can lead to data duplicates if he has incorrect code. vshards will make it harder to operate ClickHouse correctly.
3) There is no procedure how to change number of vshards in RFC. If we used incorrect vshard number or bad sharding key we may want to change number of partitions.

For me it is highly preferable if we find an automatic way to define number of vshards and sharding policy. And allow to split large shard to several smaller shards. If we do so we can allow not to create another level of storage like vshards at least on user level.

**Comment by yiguolei** [comment]
@qoega  

> * vshard key can be misused by a user and data will be distributed with misbalance. Some shards can be overloaded and other can be almost empty. There can appear a new problem to autobalance vshards.
> * if user defines vshard key manually it can lead to data duplicates if he has incorrect code. vshards will make it harder to operate ClickHouse correctly.

vshard key is the same as current shard key. Currently, if user using a sharding key in distributed table, he has to concern about the shard key to assure that data is balanced among all shards. And he has to make sure the code is right to avoid data duplicates between shards. Because the only difference between shard and vshard is that there could be 2 or more vshard in a single node. I think vshard is the same as shard in this scenario.

> 3\. There is no procedure how to change number of vshards in RFC. If we used incorrect vshard number or bad sharding key we may want to change number of partitions.

Yes, it is. User could not change the vshard number because it has to re-distribute data during this process. It is also the same as current shard. But user could create more vshards during create table process. For example, if there are 4 nodes in the cluster, he could create 40 vshards and about 10 vshards on a single node and move some vshards to new added node during cluster expansion.

vshard is similar to shard in elasticsearch and slice in amazon redshift. In general, vshard is a litter better than current shard, but it could not solve all problems.

**Comment by alexey-milovidov** [comment]
Looks abandoned.
