### ISSUE TITLE
Add tables parts/size/rows metrics

### ISSUE THREAD

**Issue by dmmarkov** [ClickHouse/ClickHouse#20222]
**Use case**
I'd like to see size of tables, number of parts and number of rows in tables. But I don't want to use extra exporter which can extract this information from system.parts.

**Describe the solution you'd like**
It maybe some kind of async metrics which can be captured by prometheus. 

**Additional context**
I know that exists https://github.com/ClickHouse/clickhouse_exporter which can scrape this values but it will be better if clickhouse can also export this part of values via metrics

**Comment by filimonov** [comment]
See #20200 

Can be addressed by (more general) https://github.com/ClickHouse/ClickHouse/issues/10043

**Comment by dmmarkov** [comment]
Issue https://github.com/ClickHouse/ClickHouse/issues/10043 more general. How to vote for this feature?

**Comment by Algunenano** [comment]
Prometheus output format -> https://github.com/ClickHouse/ClickHouse/pull/36206
