### ISSUE TITLE
darwin-aarch64 build in CI

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#20245]
**Use case**
Allow people to download pre-build ClickHouse for Apple M1. #20237

**Describe the solution you'd like**
Add a toolchain. See `cmake/darwin` directory.

**Comment by abyss7** [comment]
Qemu support: https://blogs.blackberry.com/en/2021/05/strong-arming-with-macos-adventures-in-cross-platform-emulation

**Comment by alexey-milovidov** [comment]
Ok, it works!
