### ISSUE TITLE
Use service account for LDAP

### ISSUE THREAD

**Issue by fuCtor** [ClickHouse/ClickHouse#20253]
**Use case**
In some organisations are using AD with hierarchical structure (nested organisation unit) and DN follow this structure. As result we can not  use permanent build_dn for users with different OU.

**Describe the solution you'd like**
Solution can be look like:
1) bind as service account
2) set dn for user_name by some filter string to user_dn
3) bind as user_dn with password
3) use user_dn with filter for group/roles fetching

This approach is implemented in Metabase.

**Comment by traceon** [comment]
Are users defined in `ou`s or referenced there? They should be referenced there but defined somewhere else, as I understand. And that place should serve as a `bind_dn`. Otherwise, nothing prevents you from defining multiple ldap servers with different `bind_dn`'s for users in different `ou`s.

**Comment by fuCtor** [comment]
As I can understand they are defined there.

Do you mean define in `user_directories` multiple `ldap` section  with different `server`. But this do not solve second problem. For example.

We have such users
```
CN=Иванов Иван Иванович,OU=users_l0.1.1.2,OU=users_l0.1.1,OU=users_l0.1,OU=users_l0,DC=domain,DC=tld + sAMAccountName=i.i.ivanov

CN=Петров Сергей Владимирович,OU=users_l0.2,OU=users_l0,DC=domain,DC=tld + sAMAccountName=s.v.petrov
```
With ldap_server configured as:
```
<my_ldap_server>
  <host>ldap.domain.tld</host>
  <port>389</port>
  <bind_dn>DOMAIN\{user_name}</bind_dn>
  <verification_cooldown>300</verification_cooldown>
  <enable_tls>no</enable_tls>
</my_ldap_server>
```
We can successful bind user and login to clickhouse with `i.i.ivanov` or `s.v.petrov`. 
For get the groups we should build filter strings:
```
(&(objectClass=group)(member=CN=Иванов Иван Иванович,OU=users_l0.1.1,OU=users_l0.1.1,OU=users_l0.1,OU=users_l0,DC=domain,DC=tld))

(&(objectClass=group)(member=CN=Петров Сергей Владимирович,OU=users_l0.2,OU=users_l0,DC=domain,DC=tld))
```
But I don’t know how to do it.

**Comment by traceon** [comment]
How does the content of `OU=users_l0.2,OU=users_l0,DC=domain,DC=tld` look like?

**Comment by fuCtor** [comment]
```
CN=Петров Сергей Владимирович,OU=users_l0.2,OU=users_l0,DC=domain,DC=tld  objectClass=person,top,user
CN=Смирнов Дмитрий Витальевич,OU=users_l0.2,OU=users_l0,DC=domain,DC=tld objectClass=person,top,user
OU=users_l0.2.1,OU=users_l0.2,OU=users_l0,DC=domain,DC=tld objectClass=top,organizationalUnit
OU=users_l0.2.2,OU=users_l0.2,OU=users_l0,DC=domain,DC=tld objectClass=top,organizationalUnit
...
```

**Comment by traceon** [comment]
> We can successful bind user and login to clickhouse with i.i.ivanov or s.v.petrov.

Where is this specified? How do the records associate to these user names?

**Comment by fuCtor** [comment]
> > We can successful bind user and login to clickhouse with i.i.ivanov or s.v.petrov.
> 
> Where is this specified? How do the records above associate to these user names?

In config:
```
<bind_dn>DOMAIN\{user_name}</bind_dn>
```
It's allow bind user. AD support this DN string and if I'm made request from console:
```
ldapwhoami -H "ldap://ldap.domain.tld" -D 'CN=Петров Сергей Владимирович,OU=users_l0.2,OU=users_l0,DC=domain,DC=tld'  -W
ldapwhoami -H "ldap://ldap.domain.tld" -D 'DOMAIN\s.v.petrov'  -W
```
I get the same result: `DOMAIN\s.v.petrov`

**Comment by traceon** [comment]
OU is a "group", you usually put references there (the `member=CN=Петров Сергей Владимирович` attribute), to the actual DN with user definition. So I am asking, where that user definition is located?

**Comment by traceon** [comment]
What is the output of

```sh
dsquery user -name s.v.petrov
```

and

```sh 
dsquery group -name users_l0.2
```
?

**Comment by traceon** [comment]
After discussing this in chat, the missing part was identified to be a `{user_dn}` substitution in `<search_filter>` section specifically, which would store the real DN of the user. By default, it could be equal to `bind_dn` itself, but for cases like this issue, a separate LDAP search should be performed to retrieve that `user_dn`. So another search filter must be configured for that: `<user_dn_search_filter>`.

**Comment by paf91** [comment]
@traceon
could you please show your solution in this example format:

```
<ldap_servers>
    <test_ldap_server>
    <host>ldap.forumsys.com</host>
    <port>389</port>
    <bind_dn>uid={user_name},dc=example,dc=com</bind_dn>
    <enable_tls>no</enable_tls>
    <tls_require_cert>never</tls_require_cert>
    </test_ldap_server>
</ldap_servers>
```
