### ISSUE TITLE
how to kill long query?

### ISSUE THREAD

**Issue by Fanduzi** [ClickHouse/ClickHouse#20273]
KILL QUERY WHERE query_id='xxx' doesn't work, it just return waiting. 

Is it true that a sql cannot be killed unless it is executed? But what is the point of killing if all executions are completed? The CPU is full, and the purpose of kill query is to immediately stop the executing sql and reduce the CPU usage

**Comment by den-crane** [comment]
Unfortunately not all queries can be killed.
KILL QUERY only sets a flag that must be checked by the query.
A query pipeline is checking this flag  before a switching to next block. If the pipeline has stuck somewhere in the middle it cannot be killed.
If a query does not stop, the only way to get rid of it is to restart ClickHouse.

**Comment by Fanduzi** [comment]
> Unfortunately not all queries can be killed.
> KILL QUERY only sets a flag that must be checked by the query.
> A query pipeline is checking this flag before a switching to next block. If the pipeline has stuck somewhere in the middle it cannot be killed.
> If a query does not stop, the only way to get rid of it is to restart ClickHouse.

Thank you @den-crane , I understand, I will restart after waiting, you guys response time is too fast!  Happy Chinese New Year :)

**Comment by amosbird** [comment]
I feel like we can extend the `KILL` query so that it can kill
1. long queries
2. queries of given table, database
3. queries of given function
etc..

**Comment by SaltTan** [comment]
Any column from system.processes can be used in the WHERE section of KILL QUERY

**Comment by den-crane** [comment]
yeah, like

KILL QUERY WHERE elapsed > 600
