### ISSUE TITLE
Start pushing alpine images to dockerhub

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#20276]
```
VERSION=21.1.2.15 DOCKER_IMAGE="filimonovq/clickhouse-server"  ./alpine-build.sh
docker push filimonovq/clickhouse-server:21.1.2.15-alpine
```

See also:
* https://github.com/ClickHouse/ClickHouse/blob/master/docker/server/alpine-build.sh
* https://github.com/ClickHouse/ClickHouse/pull/16479

**Comment by alesapin** [comment]
Done https://clickhouse-test-reports.s3.yandex.net/19912/0979308e68ac9a1ad0d49df019955dca3cd8cf50/push_to_dockerhub.html. Will check during next release.

**Comment by filimonov** [comment]
Works perfectly!
