### ISSUE TITLE
wrong toDecimalX minus result

### ISSUE THREAD

**Issue by chenbo1989** [ClickHouse/ClickHouse#20283]
I've been studying basic usage and I found wrong minus result on DecimalXX type.

**Example Query**
`
select toDecimal64(4,4) - toDecimal32(2,2)
`

**Expected output**
2.0000

**Actual output**
3.9800

Is there anything wrong or maybe my misunderstanding of toDecimal ?

![image](https://user-images.githubusercontent.com/8475371/107513855-cdd57a00-6be3-11eb-841d-d425a198d172.png)

**How to reproduce**
1. OS: macOS Catalina 10.15.5
2. server: clickhouse-server, built from source, version 21.3.1.1
3. client:  clickhouse-client,  built from source, version 21.3.1.1

**Comment by filimonov** [comment]
Confirmed. It's a bug.

**Comment by filimonov** [comment]
20.12 and before are not affected. Thanks for the report!

**Comment by alexey-milovidov** [comment]
Broken in #18145.
