### ISSUE TITLE
Can I set the linux user "clickhouse"  to "/bin/bash" in passwd?

### ISSUE THREAD

**Issue by winoenix** [ClickHouse/ClickHouse#20280]
I wants to run some 3rd party tools like clickhouse-backup, but don't want to use the root user.

Can I set the user "clickhouse" from "/bin/false" to "/bin/bash" so that I can use those tools under the clickhouse user? (Just like we use the oracle user when using an Oracle)?

Is there any negative effect to the clickhouse system?

Thanks very much!

**Comment by alexey-milovidov** [comment]
As far as I remember, shell is set to `/bin/false` for security reasons to avoid the possibility that you accidentially allow someone to login as clickhouse. We also set home directory to `/nonexistent`.

If you set shell to `/bin/bash` but no one from outside can log in to your server as clickhouse, it is still secure.

**Comment by filimonov** [comment]
```
sudo -u clickhouse HOME=/tmp bash
sudo su clickhouse -s /usr/bin/bash
etc.
```
