### ISSUE TITLE
How does a Materialized View with a replication engine work?

### ISSUE THREAD

**Issue by ilugid** [ClickHouse/ClickHouse#20288]
I am curious about how a Materialized View with a replication engine work?

We have a 2 node cluster with a Table with replication engine (single shard).
We have created a Materialized view on the first node with a replication engine (single shard) with select query from the above table.
We now created a Materialized View on the second node similar to first node.

The question is how will this really work. Will it be populated with Inserts on local table specified in the Select query or will it be populated with replication from other replica?

**Comment by den-crane** [comment]
https://youtu.be/ckChUkC3Pns?t=10715

https://den-crane.github.io/Everything_you_should_know_about_materialized_views_commented.pdf

**Comment by ilugid** [comment]
Thanks!! That helped.
