### ISSUE TITLE
str_to_date function

### ISSUE THREAD

**Issue by rlazimi-dev** [ClickHouse/ClickHouse#20452]
**Use case**
Convert a string to a Date object.

**Describe the solution you'd like**
The solution should have the same prototype as MYSQL's str_to_date function.

An example of the str_to_date function:
```
str_to_date('19/May/1999', '%d/%m/%Y')
str_to_date('02/21/1986', '%m/%d/%Y')
```
returns
```
(Date) 1999-05-19
(Date) 1986-02-21
```

**Describe alternatives you've considered**
String parsing. It is possible, however it adds a lot of complexity and degrades performance.

**Comment by UnamedRus** [comment]
There is a parseDateTimeBestEffort function, which covers multiple date string formats.

```
SELECT
    toDate(parseDateTimeBestEffort('02/21/1986')),
    toDate(parseDateTimeBestEffort('19/May/1999'))

Query id: 384372ae-5318-4eeb-bf49-97bb09b9a8c9

┌─toDate(parseDateTimeBestEffort('02/21/1986'))─┬─toDate(parseDateTimeBestEffort('19/May/1999'))─┐
│                                    1986-02-21 │                                     1999-05-19 │
└───────────────────────────────────────────────┴────────────────────────────────────────────────┘
```

**Comment by den-crane** [comment]
also parseDateTimeBestEffortUS https://clickhouse.tech/docs/en/sql-reference/functions/type-conversion-functions/

**Comment by rlazimi-dev** [comment]
thank you for the help, this solved my problem!
