### ISSUE TITLE
min(date), max(date) returning 1970-01-01 if no rows matched

### ISSUE THREAD

**Issue by ramazanpolat** [ClickHouse/ClickHouse#20467]
**Describe the bug**
If there is no row corresponding to where condition (or even if there the table is empty) then `min` and `max` functions return `1970-01-01`.

**Does it reproduce on recent release?**
Yes, it is reproducible on 21.2.2.8.

**How to reproduce**
```
create table minmaxdate2(
	x Int64,
	d Date DEFAULT toDate(now())
) Engine=MergeTree order by x;

insert into minmaxdate2 select number, toDate(now()) from numbers(10);

SELECT
    min(d),
    max(d)
FROM minmaxdate2
WHERE x > 5

Query id: 03b9a36d-65ea-44e0-907c-16ee86fe811f

┌─────min(d)─┬─────max(d)─┐
│ 2021-02-13 │ 2021-02-13 │
└────────────┴────────────┘

SELECT
    min(d),
    max(d)
FROM minmaxdate2
WHERE x > 10

Query id: 8f18bb01-c8de-4337-bf45-f7f8ae5aeb9a

┌─────min(d)─┬─────max(d)─┐
│ 1970-01-01 │ 1970-01-01 │
└────────────┴────────────┘
```

Although there is no date like `1970-01-01` in the table, the second query returns `1970-01-01` for `min` as well as `max`.

* Which ClickHouse server version to use
v21.2.2.8
* Which interface to use, if matters
clickhouse-client

**Expected behavior**
It is expected to get `NULL` if there are no corresponding rows.

**Comment by alexey-milovidov** [comment]
The desired behaviour is available under `aggregate_functions_null_for_empty` setting.
