### ISSUE TITLE
MacOSX 10.14.6 编译 ClickHouse 失败

### ISSUE THREAD

**Issue by Smelly-calf** [ClickHouse/ClickHouse#20491]
[0/2] Re-checking globbed directories...
[4641/5458] Building CXX object src/Parsers/New/CMakeFiles/clickhouse_parsers_new.dir/AST/Identifier.cpp.o
FAILED: src/Parsers/New/CMakeFiles/clickhouse_parsers_new.dir/AST/Identifier.cpp.o 
/usr/local/opt/llvm/bin/clang++ -DPOCO_ENABLE_CPP11 -DPOCO_HAVE_FD_POLL -DPOCO_OS_FAMILY_UNIX -DUNALIGNED_OK -DUSE_FASTMEMCPY=0 -DUSE_REPLXX=1 -DWITH_COVERAGE=0 -DWITH_GZFILEOP -DX86_64 -DZLIB_COMPAT -Iincludes/configs -I../src -Isrc -Isrc/Core/include -I../base/common/.. -Ibase/common/.. -I../contrib/cityhash102/include -I../contrib/cctz/include -Icontrib/zlib-ng -I../contrib/zlib-ng -I../base/pcg-random/. -isystem ../contrib/libcxx/include -isystem ../contrib/libcxxabi/include -isystem ../contrib/antlr4-runtime -isystem ../contrib/fast_float/include -isystem ../contrib/msgpack-c/include -isystem ../contrib/xz/src/liblzma/api -isystem ../contrib/zstd/lib -isystem ../contrib/re2 -isystem ../contrib/boost -isystem ../contrib/poco/Net/include -isystem ../contrib/poco/Foundation/include -isystem ../contrib/poco/NetSSL_OpenSSL/include -isystem ../contrib/poco/Crypto/include -isystem ../contrib/boringssl/include -isystem ../contrib/poco/Util/include -isystem ../contrib/poco/JSON/include -isystem ../contrib/poco/XML/include -isystem ../contrib/replxx/include -isystem ../contrib/fmtlib-cmake/../fmtlib/include -isystem ../contrib/double-conversion -isystem ../contrib/dragonbox/include -isystem contrib/re2_st -isystem ../contrib/croaring/include -fdiagnostics-color=always -std=gnu++2a -fsized-deallocation  -gdwarf-aranges -msse4.1 -msse4.2 -mpopcnt   -Wall -Wno-unused-command-line-argument  -stdlib=libc++ -fdiagnostics-absolute-paths -fexperimental-new-pass-manager -Werror -Wextra -Wpedantic -Wno-vla-extension -Wno-zero-length-array -Wno-c11-extensions -Wcomma -Wconditional-uninitialized -Wcovered-switch-default -Wdeprecated -Wembedded-directive -Wempty-init-stmt -Wextra-semi-stmt -Wextra-semi -Wgnu-case-range -Winconsistent-missing-destructor-override -Wnewline-eof -Wold-style-cast -Wrange-loop-analysis -Wredundant-parens -Wreserved-id-macro -Wshadow-field -Wshadow-uncaptured-local -Wshadow -Wstring-plus-int -Wundef -Wunreachable-code-return -Wunreachable-code -Wunused-exception-parameter -Wunused-macros -Wunused-member-function -Wzero-as-null-pointer-constant -Weverything -Wno-c++98-compat-pedantic -Wno-c++98-compat -Wno-c99-extensions -Wno-conversion -Wno-ctad-maybe-unsupported -Wno-deprecated-dynamic-exception-spec -Wno-disabled-macro-expansion -Wno-documentation-unknown-command -Wno-double-promotion -Wno-exit-time-destructors -Wno-float-equal -Wno-global-constructors -Wno-missing-prototypes -Wno-missing-variable-declarations -Wno-nested-anon-types -Wno-packed -Wno-padded -Wno-return-std-move-in-c++11 -Wno-shift-sign-overflow -Wno-sign-conversion -Wno-switch-enum -Wno-undefined-func-template -Wno-unused-template -Wno-vla -Wno-weak-template-vtables -Wno-weak-vtables -g -O0 -g3 -ggdb3 -fno-inline  -D_LIBCPP_DEBUG=0 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.15   -D OS_DARWIN -Wno-c++2a-compat -Wno-deprecated-this-capture -Wno-documentation-html -Wno-documentation -Wno-documentation-deprecated-sync -Wno-shadow-field -Wno-unused-parameter -Wno-extra-semi -Wno-inconsistent-missing-destructor-override -Wno-shadow -nostdinc++ -MD -MT src/Parsers/New/CMakeFiles/clickhouse_parsers_new.dir/AST/Identifier.cpp.o -MF src/Parsers/New/CMakeFiles/clickhouse_parsers_new.dir/AST/Identifier.cpp.o.d -o src/Parsers/New/CMakeFiles/clickhouse_parsers_new.dir/AST/Identifier.cpp.o -c ../src/Parsers/New/AST/Identifier.cpp
In file included from ../src/Parsers/New/AST/Identifier.cpp:1:
In file included from ../src/Parsers/New/AST/Identifier.h:3:
/Users/wangqian/CLionProjects/ClickHouse/src/Parsers/New/AST/INode.h:19:17: error: definition of implicit copy constructor for 'INode' is deprecated because it has a user-declared destructor [-Werror,-Wdeprecated]
        virtual ~INode() = default;
                ^
/Users/wangqian/CLionProjects/ClickHouse/src/Parsers/New/AST/Identifier.h:9:7: note: in implicit copy constructor for 'DB::AST::INode' first required here
class Identifier : public INode
      ^
/Users/wangqian/CLionProjects/ClickHouse/src/Parsers/New/AST/Identifier.cpp:42:66: note: in implicit copy constructor for 'DB::AST::Identifier' first required here
DatabaseIdentifier::DatabaseIdentifier(PtrTo<Identifier> name) : Identifier(*name)
                                                                 ^
1 error generated.
ninja: build stopped: subcommand failed.

**Comment by filimonov** [comment]
Please follow the documentation, step-by-step: https://clickhouse.tech/docs/en/development/build-osx/

If it will not help - we will need clang version, cmake output, clickhouse revision you trying to build etc.

**Comment by knoguchi** [comment]
FWIW CH compiles fine on my Mac (big sur with latest build tools).  If someone wants to know the compilers and configurations I can paste CMake log.
