### ISSUE TITLE
list of companies using clickhouse

### ISSUE THREAD

**Issue by allyraza** [ClickHouse/ClickHouse#205]
it would be really nice if we could add a list of companies on the site that are using clickhouse in production.

**Comment by blinkov** [comment]
Unfortunately, it's not that easy from legal standpoint. Though if company you work for is ok about stating publicly that's it's using ClickHouse in production  — feel free to do so.

**Comment by alexey-milovidov** [comment]
@blinkov We can collect the links to public statements about ClickHouse usage in production.
There are plenty of them. But we just not collecting.

**Comment by blinkov** [comment]
I'd still not put it anywhere near official website without their written approval. Just collecting the list of what's already out there is possible of course.

**Comment by blinkov** [comment]
https://clickhouse.tech/docs/en/introduction/adopters/
