### ISSUE TITLE
count() function returns null when used with group by clause

### ISSUE THREAD

**Issue by sarave** [ClickHouse/ClickHouse#20536]
ClickHouse Version: 20.8.12.2

count() function returns 0 when there are no matching rows
sample query: 

> SELECT count() FROM table_name WHERE 0=1

But the same query returns null when group by clause is added
sample query:

> SELECT count() FROM table_name WHERE 0=1 group by column_name

Is this expected behavior?
Any way to get 0 as the result when using group by clause?

**Comment by den-crane** [comment]
? What are you talking about? What Null?

ClickHHouse 20.8.11
```sql
 select count(*) from (select 1 a) t where 1=0 group by a;
0 rows in set. Elapsed: 0.001 sec.
```

postgresql:
```sql
select count(*) from (select 1 a) t where 1=0 group by a;
 count
-------
(0 rows)
```

vertica:
```sql
select count(*) from (select 1 a) t where 1=0 group by a;
 count
-------
(0 rows)

```
