### ISSUE TITLE
drop source column of materialized column 

### ISSUE THREAD

**Issue by asafcombo** [ClickHouse/ClickHouse#20552]
Hi. Is there any functionality to drop a source column at the time of insert. an example:

```
CREATE TABLE test
(
    `timestamp`             DateTime Codec (DoubleDelta, LZ4),
    `source`                   NULL,
    `destination`            Int64 MATERIALIZED  source * 2

) ENGINE = MergeTree() PARTITION BY toYYYYMM(timestamp)
...
...
```

The idea is to only save the materialized column.

I know I can use a NULL table and build a materialized view on top, but if what I asked could work the DDL is simpler

**Comment by den-crane** [comment]
No such feature. 
You can use input function, but insert will be more complicated. https://clickhouse.tech/docs/en/sql-reference/table-functions/input/

**Comment by asafcombo** [comment]
thanks @den-crane
