### ISSUE TITLE
Exception: Nested type Array(String) cannot be inside Nullable type (version 20.9.2.20 (official build))

### ISSUE THREAD

**Issue by zav379** [ClickHouse/ClickHouse#20612]
i was created table:
CREATE TABLE compare.test1
(
	event Nullable(String)
) 
ENGINE = MergeTree ORDER BY tuple();

when i have construction as 
SELECT
	JSONExtractString(event, 'event_time') as s
	,event
	,splitByChar('T', JSONExtractString(event, 'event_time'))[1]
from compare.test1

i have error:
Exception: Nested type Array(String) cannot be inside Nullable type (version 20.9.2.20 (official build))

When in table i implement event String insted of Nullable(String) it's ok, i don't have any error

**Comment by vdimir** [comment]
Now `Nullabe(String)` not supported by function `splitByChar`. Workaround is to covert `Nullable(String)` into `String` e.g. with `COALESCE` and (maybe you also want to add `WHERE event is not NULL`) :
```
SELECT
    JSONExtractString(event, 'event_time') AS s,
    event,
    splitByChar('T', JSONExtractString(COALESCE(event, ''), 'event_time'))[1]
FROM test1
WHERE event is not NULL
```

**Comment by den-crane** [comment]
splitByChar('T', assumeNotNull( ... ) )

**Comment by zav379** [comment]
thanks

**Comment by BlackSinny** [comment]
when i run 

```sql
ALTER table ${databaseName} ON CLUSTER ${tmp } ADD COLUMN asset_get_id_list Nullable(Array(String)) DEFAULT NULL;
```

receive
```sql
Code: 43. DB::Exception: Nested type Array(String) cannot be inside Nullable type. (ILLEGAL_TYPE_OF_ARGUMENT
```

can you  help me....

**Comment by CristianNogueiras** [comment]
Hi everyone! 

I´m trying to launch without success the next query: 

CREATE TABLE parquet_landing_allrep.erab_release_masorange ON CLUSTER `all-replicated`
(
    `edr_id` String,
    `connection_id` String,
    `tech_id` Int32,
    `edr_type_name` String,
    `timestamp` DateTime,
    `utc_offset` Int32,
    `process_date` DateTime,
    `connection_mode` String,
    `guami_gummei` Int64,
    `cgi_tech` String,
    `amfuengap_mmes1ap_id` Int64,
    `ranuengap_enbs1ap_id` Int64,
    `imsi` String,
    `imei` String,
    `tac` String,
    `masked_imei_sv` Int64,
    `sp_cell_rsrp` Float32,
    `sp_cell_rsrq` Float32,
    `sp_cell_sinr` Float32,
    `timing_advance` Int64,
    `transmission_mode` String,
    `lat` Float32,
    `lon` Float32,
    `location_accuracy` Float32,
    `geolocation_origin` String,
    `veryhigh_res_token` String,
    `high_res_token` String,
    `medium_res_token` String,
    `low_res_token` String,
    `veryhigh_s2_id` String,
    `high_s2_id` String,
    `medium_s2_id` String,
    `low_s2_id` String,
    `neighbours_count` Int32,
    `neighbour_cells` String,
    `secondary_cells_count` Int32,
    `secondary_cells` String,
    `nsa_cgi_tech` String,
    `nsa_rsrp` Float32,
    `nsa_rsrq` Float32,
    `nsa_secondary_cells_count` Int32,
    `nsa_secondary_cells` String,
    `release_start_timestamp` DateTime,
    `release_end_timestamp` DateTime,
    `release_detailed_list_count` Int32,
    `release_detailed_list` String,
    `release_result` String,
    `pdu_session_release_cause_per_pdu` String,
    `erab_qci_track_list_count` Int32,
    `erab_qci_track_list` String,
    `release_origin` String,
    `message_flow` Array(String),
    `task_id` String,
    `task_name` String,
    `path_to_ct` Array(String)
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/oss_ct_resource_release_v1', '{replica}')
ORDER BY edr_id;

Elapsed: 0.001 sec.
 
Received exception from server (version 24.8.14):
Code: 43. DB::Exception: Received from localhost:9000. DB::Exception: Nested type Array(String) cannot be inside Nullable type. (ILLEGAL_TYPE_OF_ARGUMENT)

Does someone know a solution  to skip this error? 

THX IN ADVANCE
