### ISSUE TITLE
ALTER TABLE ADD COLUMN и RENAME не работает для таблиц с Engine=Dictionary.

### ISSUE THREAD

**Issue by aCLr** [ClickHouse/ClickHouse#2069]
Добавил атрибуты в конфиг словаря. Подумывал сделать ALTER TABLE ADD COLUMN, но не тут-то было:
```
Received exception from server (version 1.1.54343):
Code: 48. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Method alter is not supported by storage Dictionary.
```
Хак с созданием новой таблички с доп. колонками с последующим RENAME (чтобы не попасть на исчезающе малый период, когда таблички нет в бд) тоже не прокатил:
```
:) rename table offers to old_offers, new_offers to offers;

RENAME TABLE offers TO old_offers, new_offers TO offers

Received exception from server (version 1.1.54343):
Code: 48. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Method rename is not supported by storage Dictionary. 

0 rows in set. Elapsed: 0.033 sec.
```

Пришлось делать DROP TABLE, затем CREATE. 
Некритично, но всё же.

**Comment by alexey-milovidov** [comment]
После добавления запросов CREATE DICTIONARY, теперь не требуется отдельно создавать таблицы с ENGINE = Dictionary, и актуальность задачи отсутствует.
