### ISSUE TITLE
Better Hyperloglog cardinality estimation algorithm

### ISSUE THREAD

**Issue by bocharov** [ClickHouse/ClickHouse#2073]
Otmar Ertl (@oertl) did a great job on HyperLogLog improvements in his article "New cardinality estimation algorithms for HyperLogLog sketches" https://arxiv.org/abs/1702.01284. Later he proposed to change Redis implementation of HyperLogLog (https://github.com/antirez/redis/pull/4749) and @antirez found that the new implementation is around 20% faster, simpler and has lower theoretical error.

We could improve ClickHouse `uniqHLL12`, `uniqCombined` aggregate functions and maybe introduce new function `uniqHLL(q, p)(x)` using same algorithm.

**Comment by alexey-milovidov** [comment]
We have added parameter to the `uniqCombined` function to tune the HLL quality/space in #3406.
But we still have to:
- dig into links you shared;
- change the hash function and introduce new aggregate function like `uniqEnhanced`.

**Comment by alexey-milovidov** [comment]
Is there any evidence that the proposed implementations going to be better than the `uniqCombined` function?
