### ISSUE TITLE
ReplacingMergeTree - some improvements to standarize row deletion?

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#2074]
Idea of ReplacingMergeTree is quite simple and allows to use ClickHouse in some scenarios where data is not immutable. The only problem with it - you can't delete rows from there, and can't change the value of columns which is inside PK. And because in ClickHouse it's always better to add to PK columns according to most common SELECT pattern (not like in traditional SQL), it's sometimes necessary to make PK of the row mutable too.

Of course the only way to 'update' the PK of the row during merge process - remove the old row and insert new row.

There are some approaches to make that possible:
1) The simplest: just to have extra 'deleted' column to filter out rows from resulting set.
2) Or using version column only:
    - allow version field to be negative
    - while merging - instead of taking the row with max(version) - take the row with max(abs(version))
    - and  filter out resulting rows which have version below 0.

May be one of approaches should be standardized, and supported by engine itself?

**Comment by avalon12** [comment]
A problem you are not regarding here is that merging only happens when OPTIMIZE TABLE is being executed... until that point you still have 2 rows, 1 marked with deleted and the other not.

To comply with GDPR your data doesnt just have to be marked as deleted, it really has to be gone, you can never "delete" your primary key, so not all data is deleted. Do you still comply to GDPR if the user ID points to a number of rows in your database with blanked data?

The preferred solution is a TRUE deletion of the entire row, so that we do not have to involve GDPR consequences in choosing our primary keys....

**Comment by filimonov** [comment]
Just to clarify: that issue is not connected with GDPR.

About GDPR: as far as i know some special syntax of real data deletion is planned. Hope that it will be delivered till may of 2018. For now the only  way to delete some rows from clickhouse is full rewrite of one partition.

So create the table with the same structure, copy one partition without certain rows. Later you need to drop original partition and copy back the copy. Not very atomic, not very fast, but doable. 

As I understand the first implementation of delete if ClickHouse will work in a similar way (but atomically), and will have some special syntax like: `ALTER TABLE ... DELETE ... `

**Comment by avalon12** [comment]
Depending on the way you store your data you can remove data with the following strategy:

Use primary key that cannot be used for singling out any personal data after deletion, use ReplacingMergeTree, replace the existing row with one that contains only blanked or default values. Execute (or wait for) optimize table.

Another solution wich is more thorough is to set up your clickhouse partitions per “entity to be deleted”, for example client id. Then one can detach and delete one or more partitions from disk. This ofcourse has impact on performance and whatnot, but if you only have few entities this might be a viable solution.

**Comment by filimonov** [comment]
About GDPR: actually as far as i know at that point 'right to be forgotten' doesn't enforce to remove that data instantly, you need to have protocol describing that procedure, and up to 1 month to really remove the data. So i don't think that running OPTIMIZE FINAL will be a big issue during that month.

**Comment by rpfennin** [comment]
optimize final does not appear to delete all pairs of rows that it should.  in my tests, it leaves about half of the rows that should get purged.

**Comment by alexey-milovidov** [comment]
This issue has been rendered irrelevant.
