### ISSUE TITLE
How to remove replica from clickhouse cluster?

### ISSUE THREAD

**Issue by anto-sr** [ClickHouse/ClickHouse#20868]
We are using 3 replica node clickhouse cluster with node names of ch111,ch112,ch113 and we are using tables with engine Replicated merge tree, I would like to remove ch113 from the clickhouse cluster without any issues on data availability on other replica nodes.

Our config file in three replica nodes contains:
```
       <cluster_live>
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                     <host>ch111</host>
                    <port>9000</port>
                </replica>
            </shard>
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                    <host>ch112</host>
                    <port>9000</port>
                </replica>
            </shard>
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                    <host>ch113</host>
                    <port>9000</port>
                </replica>
            </shard>
                </cluster_live>
```

**Comment by den-crane** [comment]
Your cluster_live configuration has 3 shards. Each shard has only 1 replica.
Can you show `show create table  mytable` ?


In general to remove replica you should:
1. edit remote_servers and remove replica
2. execute `drop database ...` for all databases at this replica.
