### ISSUE TITLE
ReplicatedReplacingMergeTree replaces only when the new value is bigger

### ISSUE THREAD

**Issue by iameugenejo** [ClickHouse/ClickHouse#20867]
Hello, I'm seeing a bug with `ReplicatedReplacingMergeTree` that's not replacing the entry when the new entry has smaller values in the fields that are not primary keys.

Please note that this does not happen with `ReplacingMergeTree`.

clickhouse version is 20.8.11.17

please see below:

### create table:
```sql
create table tmp.rep_repl
(
    `timestamp` DateTime,
    `account_number` UInt64,
    `account_name` String
) Engine = ReplicatedReplacingMergeTree('/clickhouse/tables/{layer}-{shard}/tmp.rep_repl', '{replica}', timestamp)
PARTITION BY formatDateTime(timestamp, '%Y%m%d')
ORDER BY (account_number, timestamp)
TTL timestamp + toIntervalDay(1);
```

### test - insert (correct)
```sql
insert into tmp.rep_repl select toStartOfDay(now()), 1, 'test';
select * from tmp.rep_repl;

┌───────────timestamp─┬─account_number─┬─account_name─┐
│ 2021-02-18 00:00:00 │              1 │ test         │
└─────────────────────┴────────────────┴──────────────┘
```

### test - insert bigger value (correct)
```sql

insert into tmp.rep_repl select toStartOfDay(now()), 1, 'test2';
select * from tmp.rep_repl;


┌───────────timestamp─┬─account_number─┬─account_name─┐
│ 2021-02-18 00:00:00 │              1 │ test         │
└─────────────────────┴────────────────┴──────────────┘
┌───────────timestamp─┬─account_number─┬─account_name─┐
│ 2021-02-18 00:00:00 │              1 │ test2        │
└─────────────────────┴────────────────┴──────────────┘

optimize table tmp.rep_repl final;
select * from tmp.rep_repl;

┌───────────timestamp─┬─account_number─┬─account_name─┐
│ 2021-02-18 00:00:00 │              1 │ test2        │
└─────────────────────┴────────────────┴──────────────┘
```

### test - insert smaller value (**incorrect**)
```sql

insert into tmp.rep_repl select toStartOfDay(now()), 1, 'test';
select * from tmp.rep_repl;


┌───────────timestamp─┬─account_number─┬─account_name─┐
│ 2021-02-18 00:00:00 │              1 │ test2        │
└─────────────────────┴────────────────┴──────────────┘

optimize table tmp.rep_repl final;
select * from tmp.rep_repl;

┌───────────timestamp─┬─account_number─┬─account_name─┐
│ 2021-02-18 00:00:00 │              1 │ test2        │
└─────────────────────┴────────────────┴──────────────┘
```

### test - insert bigger value (correct)
```sql
insert into tmp.rep_repl select toStartOfDay(now()), 1, 'test3';
select * from tmp.rep_repl;

┌───────────timestamp─┬─account_number─┬─account_name─┐
│ 2021-02-18 00:00:00 │              1 │ test2        │
└─────────────────────┴────────────────┴──────────────┘
┌───────────timestamp─┬─account_number─┬─account_name─┐
│ 2021-02-18 00:00:00 │              1 │ test3        │
└─────────────────────┴────────────────┴──────────────┘

optimize table tmp.rep_repl final;
select * from tmp.rep_repl;

┌───────────timestamp─┬─account_number─┬─account_name─┐
│ 2021-02-18 00:00:00 │              1 │ test3        │
└─────────────────────┴────────────────┴──────────────┘
```

### test - insert smaller value (**incorrect**)
```sql
insert into tmp.rep_repl select toStartOfDay(now()), 1, 'test2';
select * from tmp.rep_repl;

┌───────────timestamp─┬─account_number─┬─account_name─┐
│ 2021-02-18 00:00:00 │              1 │ test3        │
└─────────────────────┴────────────────┴──────────────┘
```

**Comment by den-crane** [comment]
You defined table as

```
ReplicatedReplacingMergeTree('/clickhouse/tables/{layer}-{shard}/tmp.rep_repl', '{replica}', timestamp)
```
This means that `timestamp` column will be used as VER column. It will be compared during replacing to make decision with row to remain.

```
ORDER BY (account_number, timestamp)
```
This means that these set of columns `account_number, timestamp` will be used as a collapsing KEY. Each unique set of these column should stay in the table. 

These defines are contradict each other SO Replacing removes random / any row for duplicated set of  `account_number, timestamp`

**Comment by iameugenejo** [comment]
I see, I should remove `timestamp` from the engine declaration.

@den-crane thank you for the clarification.

**Comment by iameugenejo** [comment]
@den-crane I just tested with out `timestamp`, and it's behaving the same

**Comment by den-crane** [comment]
Can you provide a new example?
Try without `TTL timestamp + toIntervalDay(1)`. It could be that the recent rows has date older than 1 day and are deleted by TTL.

**Comment by iameugenejo** [comment]
@den-crane Here is the new test without the TTL:

```sql
create table tmp.rep_repl
(
    `timestamp` DateTime,
    `account_number` UInt64,
    `account_name` String
) Engine = ReplicatedReplacingMergeTree('/clickhouse/tables/{layer}-{shard}/tmp.rep_repl', '{replica}')
PARTITION BY formatDateTime(timestamp, '%Y%m%d')
ORDER BY (account_number, timestamp);


insert into tmp.rep_repl select toStartOfDay(now()), 1, 'test';
select * from tmp.rep_repl;
┌───────────timestamp─┬─account_number─┬─account_name─┐
│ 2021-02-18 00:00:00 │              1 │ test         │
└─────────────────────┴────────────────┴──────────────┘

insert into tmp.rep_repl select toStartOfDay(now()), 1, 'test2';
select * from tmp.rep_repl;
┌───────────timestamp─┬─account_number─┬─account_name─┐
│ 2021-02-18 00:00:00 │              1 │ test         │
└─────────────────────┴────────────────┴──────────────┘
┌───────────timestamp─┬─account_number─┬─account_name─┐
│ 2021-02-18 00:00:00 │              1 │ test2        │
└─────────────────────┴────────────────┴──────────────┘

optimize table tmp.rep_repl final;
select * from tmp.rep_repl;
┌───────────timestamp─┬─account_number─┬─account_name─┐
│ 2021-02-18 00:00:00 │              1 │ test2        │
└─────────────────────┴────────────────┴──────────────┘

insert into tmp.rep_repl select toStartOfDay(now()), 1, 'test';
select * from tmp.rep_repl;
┌───────────timestamp─┬─account_number─┬─account_name─┐
│ 2021-02-18 00:00:00 │              1 │ test2        │
└─────────────────────┴────────────────┴──────────────┘

optimize table tmp.rep_repl final;
select * from tmp.rep_repl;
┌───────────timestamp─┬─account_number─┬─account_name─┐
│ 2021-02-18 00:00:00 │              1 │ test2        │
└─────────────────────┴────────────────┴──────────────┘

insert into tmp.rep_repl select toStartOfDay(now()), 1, 'test3';
select * from tmp.rep_repl;
┌───────────timestamp─┬─account_number─┬─account_name─┐
│ 2021-02-18 00:00:00 │              1 │ test2        │
└─────────────────────┴────────────────┴──────────────┘
┌───────────timestamp─┬─account_number─┬─account_name─┐
│ 2021-02-18 00:00:00 │              1 │ test3        │
└─────────────────────┴────────────────┴──────────────┘

optimize table tmp.rep_repl final;
select * from tmp.rep_repl;
┌───────────timestamp─┬─account_number─┬─account_name─┐
│ 2021-02-18 00:00:00 │              1 │ test3        │
└─────────────────────┴────────────────┴──────────────┘

insert into tmp.rep_repl select toStartOfDay(now()), 1, 'test2';
select * from tmp.rep_repl;
┌───────────timestamp─┬─account_number─┬─account_name─┐
│ 2021-02-18 00:00:00 │              1 │ test3        │
└─────────────────────┴────────────────┴──────────────┘

```

**Comment by iameugenejo** [comment]
Here is the same test with `ReplacingMergeTree` - https://gist.github.com/iameugenejo/c3e3af1bdf11d9fe1c0112817864d8a0 (not posting the snippet here directly to keep the irrelevant info from polluting the discussion)

**Comment by den-crane** [comment]
```
insert into tmp.rep_repl select toStartOfDay(now()), 1, 'test';
insert into tmp.rep_repl select toStartOfDay(now()), 1, 'test';
insert into tmp.rep_repl select toStartOfDay(now()), 1, 'test';
```

try ` set insert_deduplicate=0`

https://clickhouse.tech/docs/en/engines/table-engines/mergetree-family/replication/

_Data blocks are deduplicated. For multiple writes of the same data block (data blocks of the same size containing the same rows in the same order), the block is only written once. The reason for this is in case of network failures when the client application doesn’t know if the data was written to the DB, so the INSERT query can simply be repeated. It doesn’t matter which replica INSERTs were sent to with identical data. INSERTs are idempotent. Deduplication parameters are controlled by merge_tree server settings._

**Comment by iameugenejo** [comment]
@den-crane `set insert_deduplicate=0` worked.

I'll make sure to use this flag for insert to any `ReplicatedReplacingMergeTree`.

Thank you.

(Maybe `insert_deduplicate=0` should be default for `ReplicatedReplacingMergeTree` since the engine itself has its own deduplication logic? Otherwise, I'd appreciate if there's a note added to the documentation saying insert_deduplicate=0 may be required for the engine to work properly)

**Comment by den-crane** [comment]
>I'll make sure to use this flag for insert to any ReplicatedReplacingMergeTree.

You should not do this. 
In real life in a production system `insert_deduplicate` does not intervene because REAL inserts do not repeat naturally.


> (Maybe `insert_deduplicate=0` should be default for `ReplicatedReplacingMergeTree` since the engine itself has its 
>own deduplication logic? Otherwise, I'd appreciate if there's a note added to the documentation saying 
>insert_deduplicate=0 may be required for the engine to work properly)

No. It should not. Insert deduplication is not related to the "deduplication" of Replacing engine.
You probably misunderstood what is  "Insert deduplication".

**Comment by iameugenejo** [comment]
The use case for `ReplicatedReplacingMergeTree` I have is that I need to keep track of changes to this account information daily. 

We have a separate source database that's not clickhouse for the account information,

and I will have a cron task that would insert the entire set of accounts a few times a day, mostly at the end of the day from multiple servers, to this table.

We're only interested in the state of the information daily bases not per-event base, so this engine serves the purpose.

So, regarding `In real life in a production system insert_deduplicate does not intervene because REAL inserts do not repeat naturally`, that's our real life production situation we have that real inserts do repeat naturally.

**Comment by iameugenejo** [comment]
And I do understand what insert deduplication means for the replicating engines. I understand why it's needed, but I think ReplacingMergeTree engine itself performs the deduplication that serves the purpose of that as well, and it has an additional characteristic of keeping the last inserted row. But not only the additional characteristic gets ignored when the "insert deduplicate" logic kicks in first.

**Comment by den-crane** [comment]
Do you realize that it's about **insert** (all rows in the same order) not about **rows** in insert? Deduplication skips repeated inserts not rows.

>that's our real life production situation we have that real inserts do repeat naturally.

Then you should add unique insert identifier generated at the source (additional column). 
created_at -> nanoseconds, or insert_id UUID.

>And I do understand what insert deduplication means for the replicating engines.

Eventually  insert deduplication will be implemented for non Replicated engines as well.

>but I think ReplacingMergeTree engine itself performs the deduplication

I think you don't understand.

**Comment by iameugenejo** [comment]
@den-crane Great, that's the exact information I needed. Thanks for clarifying it.

Revised the table to have the timestamp as is for the uniqueness of the insert, and it's working fine without setting off the flag.

```sql
create table tmp.rep_repl
(
    `timestamp` DateTime,
    `date` Date,
    `account_number` UInt64,
    `account_name` String
) Engine = ReplicatedReplacingMergeTree('/clickhouse/tables/{layer}-{shard}/tmp.rep_repl', '{replica}')
PARTITION BY date
ORDER BY (account_number, date);


insert into tmp.rep_repl select now(), toDate(now()), 1, 'test';
select * from tmp.rep_repl;
┌───────────timestamp─┬───────date─┬─account_number─┬─account_name─┐
│ 2021-02-18 19:54:20 │ 2021-02-18 │              1 │ test         │
└─────────────────────┴────────────┴────────────────┴──────────────┘

insert into tmp.rep_repl select now(), toDate(now()), 1, 'test2';
select * from tmp.rep_repl;
┌───────────timestamp─┬───────date─┬─account_number─┬─account_name─┐
│ 2021-02-18 19:54:20 │ 2021-02-18 │              1 │ test         │
└─────────────────────┴────────────┴────────────────┴──────────────┘
┌───────────timestamp─┬───────date─┬─account_number─┬─account_name─┐
│ 2021-02-18 19:54:31 │ 2021-02-18 │              1 │ test2        │
└─────────────────────┴────────────┴────────────────┴──────────────┘

optimize table tmp.rep_repl final;
select * from tmp.rep_repl;
┌───────────timestamp─┬───────date─┬─account_number─┬─account_name─┐
│ 2021-02-18 19:54:31 │ 2021-02-18 │              1 │ test2        │
└─────────────────────┴────────────┴────────────────┴──────────────┘

insert into tmp.rep_repl select now(), toDate(now()), 1, 'test';
select * from tmp.rep_repl;
┌───────────timestamp─┬───────date─┬─account_number─┬─account_name─┐
│ 2021-02-18 19:54:31 │ 2021-02-18 │              1 │ test2        │
└─────────────────────┴────────────┴────────────────┴──────────────┘
┌───────────timestamp─┬───────date─┬─account_number─┬─account_name─┐
│ 2021-02-18 19:54:46 │ 2021-02-18 │              1 │ test         │
└─────────────────────┴────────────┴────────────────┴──────────────┘

optimize table tmp.rep_repl final;
select * from tmp.rep_repl;
┌───────────timestamp─┬───────date─┬─account_number─┬─account_name─┐
│ 2021-02-18 19:54:46 │ 2021-02-18 │              1 │ test         │
└─────────────────────┴────────────┴────────────────┴──────────────┘

insert into tmp.rep_repl select now(), toDate(now()), 1, 'test3';
select * from tmp.rep_repl;
┌───────────timestamp─┬───────date─┬─account_number─┬─account_name─┐
│ 2021-02-18 19:55:01 │ 2021-02-18 │              1 │ test3        │
└─────────────────────┴────────────┴────────────────┴──────────────┘
┌───────────timestamp─┬───────date─┬─account_number─┬─account_name─┐
│ 2021-02-18 19:54:46 │ 2021-02-18 │              1 │ test         │
└─────────────────────┴────────────┴────────────────┴──────────────┘

optimize table tmp.rep_repl final;
select * from tmp.rep_repl;
┌───────────timestamp─┬───────date─┬─account_number─┬─account_name─┐
│ 2021-02-18 19:55:01 │ 2021-02-18 │              1 │ test3        │
└─────────────────────┴────────────┴────────────────┴──────────────┘

insert into tmp.rep_repl select now(), toDate(now()), 1, 'test2';
select * from tmp.rep_repl;
┌───────────timestamp─┬─account_number─┬─account_name─┐
│ 2021-02-18 00:00:00 │              1 │ test3        │
└─────────────────────┴────────────────┴──────────────┘

optimize table tmp.rep_repl final;
select * from tmp.rep_repl;
┌───────────timestamp─┬───────date─┬─account_number─┬─account_name─┐
│ 2021-02-18 19:55:17 │ 2021-02-18 │              1 │ test2        │
└─────────────────────┴────────────┴────────────────┴──────────────┘
```

**Comment by gaurav-750** [comment]
This has been very helpful @den-crane . Thanks for posting this doubt @iameugenejo.
