### ISSUE TITLE
insert into table tutorial.visits_v1 for many times,but got count(*) result error.

### ISSUE THREAD

**Issue by xx0227** [ClickHouse/ClickHouse#20871]
I tried execute " clickhouse-client --query "INSERT INTO tutorial.visits_v1 FORMAT TSV" --max_insert_block_size=100000 < visits_v1.tsv " for many times following the [instructions](https://clickhouse.tech/docs/en/single/#import-data)
,  and i executed "select count(*) from tutorial.visits_v1" after each insert. For the first three times, the count(*) result is correct and its multiple growth , but then the count result decreased.  I got confused. Why it happends like that?
Follow is the execute simple execute records.

question2:
After I executed 'insert into ...' , in several seconds, the result changed with the time I execute 'count(*)' , the later, the lower.

Thank you in advance!

--------------------first execute --------------------------
SELECT count(*)
FROM visits_v1

Query id: a465fd70-7e99-4872-b448-04c7c8815a4d

┌─count()─┐
│ 1680609 │
└─────────┘
--------------------second execute ------------------------
┌─count()─┐
│ 3359868 │
└─────────┘
--------------------third execute--------------------------
┌─count()─┐
│ 5038397 │
└─────────┘
--------------------fourth execute--------------------------
┌─count()─┐
│ 3185468 │
└─────────┘

**Comment by den-crane** [comment]
>visits_v1.tsv " for many times following the instructions

Why? Can you clarify what instructions did you follow?

tutorial.visits_v1 has the  ENGINE = CollapsingMergeTree(Sign)

This engine removes duplicates https://clickhouse.tech/docs/en/engines/table-engines/mergetree-family/collapsingmergetree/ automatically.
