### ISSUE TITLE
summingMergeTree vs aggregatingMergeTree

### ISSUE THREAD

**Issue by sundarv85** [ClickHouse/ClickHouse#20873]
Hello,
We have the following table

```
CREATE TABLE visits 
(
	`eventDateTime` DateTime,
	`accountId` String, 
	`appName` String, 
	`url` String, 
	`count` UInt32,
	`total` UInt64, 
	`min` Float32, 
	`max` Float32
) ENGINE = MergeTree(accountId, (accountId, appName, eventDateTime), 8192)
```

For this, we are planning to write a `material view`, so that we can group all the entries on a hourly basis (by default we write on a minute basis).  We tried the following `summingMergeTree` method

```
CREATE MATERIALIZED VIEW visitsSummingMergeTreePerHourMaterialView
ENGINE = summingMergeTree()
PARTITION BY eventDateTime
ORDER BY (eventDateTime)
POPULATE
AS SELECT
    toStartOfHour(eventDateTime) AS eventDateTime,
    accountId,
    appName,
    url,
    sum(count) AS counts,
    sum(total) AS totals,
    min(min) as min,
    max(max) as max,
FROM visits
GROUP BY accountId, appName, eventDateTime
ORDER BY accountId, appName, eventDateTime
```

This works correctly for the count, total time etc.. but the min/max are not working. The advantage of this table though is
 - the data we already have is immediately applied and grouped
 - the query is the same between the main table and the summing material veiw table (no change in our backend except for the table name)

We have the other method `aggregatingMergeTree` for getting min, max also to work

```
CREATE TABLE visitsAggregationMergeTreePerHour 
(
	`eventDateTime` DateTime, 
	`accountId` String, 
	`appName` String, 
	`url` String, 
	`count` AggregateFunction(sum, UInt32), 
	`total` AggregateFunction(sum, UInt64),
	`min` AggregateFunction(min, UInt64), 
	`max` AggregateFunction(max, UInt64)
) ENGINE = AggregatingMergeTree(accountId, (accountId, appName, eventDateTime), 8192)


CREATE MATERIALIZED VIEW visitsAggreatedMergeTreePerHourMaterialView
TO visitsAggregationMergeTreePerHour
AS SELECT
    toStartOfHour(eventDateTime) AS eventDateTime,
    accountId,
    appName,
    url,
    sumState(count) AS count,
    sumState(total) AS total,
    minState(min) as min,
    maxState(max) as max
FROM visits
GROUP BY accountId, appName, eventDateTime
ORDER BY accountId, appName, eventDateTime
```

But using this method, we have to apply the query with the `sumMerge`, `minMerge`

```
SELECT sumMerge(count), sumMerge(total), minMerge(min), maxMerge(max) FROM visitsPerHour group by accountId, appName, eventDateTime
```

Questions are

 - Is this aggregation only applied when we call the query - or is it already applied and aggregated before itself
 - We are creating another table visitsPerHour - so does that mean using this method, we will increase the size (as we now have an additional table)
 - What are the advantages/disadvantages of this table compared to the Summing Tree table
 
The issues with have with this table are

 - This is applied only starting from this time and the data before this is not grouped correctly
 - All queries have to be changed when using this table to use the merge functions
 
What is the better approach and is it possible to get the `summingMergeTree` method itself to get the min/max also working (which will avoid the intermediate table)?

**Comment by den-crane** [comment]
You need to use one of aggregateFunction (SimpleAggregateFunction or AggregateFunction)
Database engine in Materialized view table knows nothing about select in materialized view.
SummingMergeTree sums automatically. In your case it does not know that it should calc min/max.

https://den-crane.github.io/Everything_you_should_know_about_materialized_views_commented.pdf
https://youtu.be/ckChUkC3Pns?list=PLO3lfQbpDVI-hyw4MyqxEk3rDHw95SzxJ&t=9371

SimpleAggregateFunction min/max/sum could be used with SummingMergeTree and AggregatingMergeTree
In this case you don't need to use -Merge
https://gist.github.com/den-crane/e326eef3b6ee6ccd5ca0df1dc1849a05

It better always use TO table notation. It's not intermediate table. In this case MATERIALIZED VIEW stores it's data in this table instead of .inner table.

**Comment by sundarv85** [comment]
Thanks @den-crane  This really helped. Especially the PDF really helped us understand how MV works...

**Comment by llwdd** [comment]
You can try 'SimpleAggregateFunction'..
