### ISSUE TITLE
Cannot attach system's table when restart clickhouser-server 

### ISSUE THREAD

**Issue by talent2333** [ClickHouse/ClickHouse#20954]
I just change the storage configuraiton in **multiple disks policy** and apply it to some tables.
Then restart my clickhouse-server,but fail.
I encounter the error that i can not attach these tables from metadata files.
refer to my clickhouse-server.err.log
![image](https://user-images.githubusercontent.com/25974296/108454331-1e656b00-72a7-11eb-86f5-7591c01080fe.png)

Then I try to add default disk under storage_configuraiton->disks in config.xml
refer to my config.xml
![image](https://user-images.githubusercontent.com/25974296/108453830-3688ba80-72a6-11eb-97aa-557daa61d3c2.png)

But still fail.
refer to my clickhouse-server.err.log
![image](https://user-images.githubusercontent.com/25974296/108453557-ac405680-72a5-11eb-8e44-cd8a0d230d39.png)
I hope you can tell me how to fix this error,thx

**Comment by filimonov** [comment]
There is data for that table on default disk. And default disk is not a part of used policy.

You need either to move that data (manually) to one of disks which are the part of that policy, either add the default disk to that policy.

**Comment by talent2333** [comment]
> There is data for that table on default disk. And default disk is not a part of used policy.
> 
> You need either to move that data (manually) to one of disks which are the part of that policy, either add the default disk to that policy.

Thanks your reply.But the path of default disk is same to the path of disk_data_02 under xml label <disks>
![image](https://user-images.githubusercontent.com/25974296/108579252-094d1280-7361-11eb-9c9b-38b84aabe24e.png)
Do you mean disk_data_02 is not same to default under <disks> label 
and i need to add default as a new disk under volume_name_0 of my custom policy in your solution 2.

**Comment by alexey-milovidov** [comment]
@filimonov Could you please help?
