### ISSUE TITLE
clickhouse-copier usablitity: progress + final stats/report

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#20955]
1) clickhouse-copier does not provide good feedback to understand what is the status of table copy, how many partitions / pieces was already copied and how many are still to do - it can be for example printed in log from time to time, and accessible via some shell-command like ```clikchouse-client --config ... --get-progress``` and / or via some zookeeper node which we can observe.

2) there is a lot of confusing messages during the process which meaning are not clear without reading the sources (and user don't understand if particular issue mentioned in logs were important/self-healed). Just one example: "But not moved to original destination table".

Just add a final status message at the end summarizing the result of copier execution. I.e. 
```
Table XXX successfully copied from SRC_CLUSTER to DST_CLUSTER  (10 partitions out of 10 are ok) in 10 sec (100Mb/s).
Issue during copying table YYY: ... 
```
or something similar. Final stats can be also provided in machine-readable (json?) format. (May be in the same zookeeper node as for progress like above)

**Comment by filimonov** [comment]
Also those 2 issues are often lead to confusions.
* https://github.com/ClickHouse/ClickHouse/issues/20957
* https://github.com/ClickHouse/ClickHouse/issues/17966

And in general - refreshing docs about copier is needed, to describe how it work.

**Comment by filimonov** [comment]
Also - maybe a possibility to cross-check the source and target at the end (by rows number and some checksums?).

**Comment by nikitamikhaylov** [comment]
1) Now the status is written in Zookeeper node (`task_path` + `/status`) in JSON format. Here is an example 
```json
{"hits":{"all_partitions_count":5,"processed_partitions_count":5}}
```
where hits is a table task name from config. And `processed_partitions_count` is updated during the process of copying.
Final stats is not written there. 

2) Logs are very useful for me to debug copier. I don't want to get rid all of them. I will delete some confusing ones and all logs will be written with `info` priority to skip useless messages from Distributed tables etc (they are written with Debug or Trace priority).
