### ISSUE TITLE
Allow replicas in MySQL engine

### ISSUE THREAD

**Issue by ekonkov** [ClickHouse/ClickHouse#20969]
It is a good idea to allow several replicas in MySQL table engine.

**Comment by alexey-milovidov** [comment]
Let's generate the addresses with `parseRemoteDescription` function.
The user should specify replicas with `|` character, example: `host{1|2|3}`.

Multiple shards cannot be specified.
(actually it can be reasonable to allow shards and create StorageDistributed on top of StorageMySQL)

This also makes sense for `postgres` table function.
