### ISSUE TITLE
Considering to remove broken part ... because it's impossible to repair.

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#20971]
Scenario: 
create a table, edit columns.txt file, detach table,  attach table  back

Result:
The part removed completely.

Expected:
part moved to detached.

**Comment by alexey-milovidov** [comment]
Part is removed if its level is zero.

**Comment by alexey-milovidov** [comment]
Users are not supposed to manually edit columns.txt file.

**Comment by filimonov** [comment]
File can be damaged other way (w/o manual interventions).

Don't it brake documented invariant? 

> If the system detects broken data parts (with the wrong size of files) or unrecognized parts (parts written to the file system but not recorded in ZooKeeper), it moves them to the `detached` subdirectory (they are not deleted).

**Comment by alexey-milovidov** [comment]
@filimonov Let's submit a patch.

**Comment by alexey-milovidov** [comment]
> File can be damaged other way (w/o manual interventions).

If table is replicated - the part will be repaired from replica.
If table is not replicated - the damaged part cannot be repaired automatically and it's in doubt you can do anything.

**Comment by filimonov** [comment]
> it's in doubt you can do anything.

The same is true for parts with level > 1, which we just detach w/o removing. Imho it's better to have the same behaviour in similar use cases.
