### ISSUE TITLE
Can't start service  after updade to 21.2.3 

### ISSUE THREAD

**Issue by onine007** [ClickHouse/ClickHouse#20994]
Error message :

2021.02.20 10:01:59.700389 [ 21866 ] {} <Error> Application: Caught exception while loading metadata: std::exception. Code: 1001, type: std::runtime_error, e.what() = failed alloc while reading, Stack trace (when copying this message, always include the lines below):

0. roaring::Roaring64Map::read(char const*, bool) @ 0x9dc8aba in /usr/bin/clickhouse
1. _ZN2DB25RoaringBitmapWithSmallSetImLDu32EE4readERNS_10ReadBufferE @ 0x9dc83cc in /usr/bin/clickhouse
2. DB::DataTypeAggregateFunction::deserializeBinaryBulk(DB::IColumn&, DB::ReadBuffer&, unsigned long, double) const @ 0xe6c058e in /usr/bin/clickhouse
3. DB::IDataType::deserializeBinaryBulkWithMultipleStreams(COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, DB::IDataType::DeserializeBinaryBulkSettings&, std::__1::shared_ptr<DB::IDataType::DeserializeBinaryBulkState>&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, COW<DB::IColumn>::immutable_ptr<DB::IColumn> > > >*) const @ 0xe77dacc in /usr/bin/clickhouse
4. DB::NativeBlockInputStream::readData(DB::IDataType const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, DB::ReadBuffer&, unsigned long, double) @ 0xed839ed in /usr/bin/clickhouse
5. DB::NativeBlockInputStream::readImpl() @ 0xed84506 in /usr/bin/clickhouse
6. DB::IBlockInputStream::read() @ 0xe69a135 in /usr/bin/clickhouse
7. DB::MergeTreeWriteAheadLog::restore(std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&) @ 0xf46601e in /usr/bin/clickhouse
8. DB::MergeTreeData::loadDataParts(bool) @ 0xf30b84d in /usr/bin/clickhouse
9. DB::StorageMergeTree::StorageMergeTree(DB::StorageID const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::StorageInMemoryMetadata const&, bool, DB::Context&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::MergeTreeData::MergingParams const&, std::__1::unique_ptr<DB::MergeTreeSettings, std::__1::default_delete<DB::MergeTreeSettings> >, bool) @ 0xf0f1948 in /usr/bin/clickhouse
10. ? @ 0xf4f6394 in /usr/bin/clickhouse
11. DB::StorageFactory::get(DB::ASTCreateQuery const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, DB::Context&, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, bool) const @ 0xf06fd49 in /usr/bin/clickhouse
12. DB::createTableFromAST(DB::ASTCreateQuery, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool) @ 0xe90bb76 in /usr/bin/clickhouse
13. ? @ 0xe8fff31 in /usr/bin/clickhouse
14. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0x8502338 in /usr/bin/clickhouse
15. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()&&...)::'lambda'()::operator()() @ 0x85042ef in /usr/bin/clickhouse
16. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x84ff90f in /usr/bin/clickhouse
17. ? @ 0x85033a3 in /usr/bin/clickhouse
18. start_thread @ 0x7e65 in /usr/lib64/libpthread-2.17.so
19. clone @ 0xfe88d in /usr/lib64/libc-2.17.so
 (version 21.2.3.15 (official build))
2021.02.20 10:01:59.702023 [ 21866 ] {} <Error> Application: failed alloc while reading

**Comment by onine007** [comment]
CREATE TABLE my_sdap.crowd_bitmap_result_replicated
(
    `instance_id` UInt32,
    `crowd_id` UInt32,
    `status` UInt8 DEFAULT 1,
    `dt` UInt32,
    `measure` AggregateFunction(groupBitmap, UInt32),
    `created_at` DateTime DEFAULT now(),
    `crowd_cardinality` UInt32 MATERIALIZED ifNull(bitmapCardinality(measure), toUInt32(0))
)
ENGINE = MergeTree()
PARTITION BY dt
ORDER BY (dt, crowd_id)
SETTINGS index_granularity = 8192

how to cast measure  to AggregateFunction(groupBitmap, UInt64) ?

**Comment by alexey-milovidov** [comment]
This is related to roaring bitmaps feature. Need help from @yuzhichang.

By the way, from what version do you upgrade?

**Comment by onine007** [comment]
> This is related to roaring bitmaps feature. Need help from @yuzhichang.
> 
> By the way, from what version do you upgrade?

from version  20.8.12

**Comment by taylor12805** [comment]
We had ran into that situation, you can try to delete all the data stored in the table my_sdap.crowd_bitmap_result_replicated and upgrade to version 21.2.3 and write data to it again. The error message won't appear.
The reason behind this is in old version ClickHouse AggregateFunction(groupBitmap, UInt32) encoded as roaring32, but in newer version ClickHouse this datatype is encoded as roaring64, which leads to a decode error.

**Comment by onine007** [comment]
> We had ran into that situation, you can try to delete all the data stored in the table my_sdap.crowd_bitmap_result_replicated and upgrade to version 21.2.3 and write data to it again. The error message won't appear.
> The reason for this error is in old version ClickHouse AggregateFunction(groupBitmap, UInt32) encoded as roaring32, but in newer version ClickHouse this datatype is encoded as roaring64, which leads to a decode error.

Can AggregateFunction(groupBitmap, UInt32)  convert to AggregateFunction(groupBitmap, UInt64) in 21.3.8 version?

**Comment by onine007** [comment]
bitmapAndnot(bitmapBuild(arrayConcat([1111111111111],bitmapToArray(measure))),bitmapBuild([1111111111111]))  can  convert AggregateFunction(groupBitmap, UInt32)  to AggregateFunction(groupBitmap, UInt64)
