### ISSUE TITLE
WATCH query hangs if source table was detached

### ISSUE THREAD

**Issue by tavplubix** [ClickHouse/ClickHouse#21004]
https://clickhouse-test-reports.s3.yandex.net/20946/f5fc082ed0e4b3d9f412f6ecfb5db0ce49469d3e/stress_test_(address).html#fail1

```
SET allow_experimental_live_view = 1;
CREATE TABLE mt (a Int32) Engine=MergeTree order by tuple();
CREATE LIVE VIEW lv AS SELECT sum(a) FROM mt;
DETACH TABLE mt [PERMANENTLY];
WATCH lv;
```

cc: @vzakaznikov

**Comment by vzakaznikov** [comment]
That is currently the expected behavior as `WATCH` query will not get any updates. If you re-create a table again and do a new insert then you will see that you do get the updates. 

@alexey-milovidov, is there a way to get a notification when a table is dropped?

**Comment by alexey-milovidov** [comment]
LIVE VIEW is not being officially supported by ClickHouse team.
