### ISSUE TITLE
design table for customer

### ISSUE THREAD

**Issue by peaksnail** [ClickHouse/ClickHouse#21008]
hi team
I have a customer table like
```sql
create table customer (
storeId  String,
customerId String,
createDate UInt64,
updateDate UInt64,
type UInt8,
status UInt8,
birthDay UInt64,
date Date default toDate(createDate/1000)
) engine = MergeTree ...
```
I have more than 10000 stores and much more customers, I will query the customer with storeId or type but not createDate or some other date.

I'm confused how to design partition key for the table. I don't use date to query and the number of stores is to much.
And I can't use a single partition because of much data

Have any suggestions? thanks

**Comment by den-crane** [comment]
> I don't use date to query and the number of stores is to much.

It does not matter. Just use `partition by toYYYYMM(toDate(createDate/1000))`
First of all partitioning is about insert --> create minimum parts during inserting and about data retention.
Partitioning can speed up queries but it's not mandatory.

**Comment by peaksnail** [comment]
It will read all partition if using partition by toYYYYMM(toDate(createDate/1000)),
Is there any way to speed up queries using storeId to query like 
```
select ... from customer where storeId='xxx'
```
otherwise it will be slow when the data is big

**Comment by den-crane** [comment]
partition by toYYYYMM(toDate(createDate/1000))
order by (storeId, toDate(createDate/1000))
