### ISSUE TITLE
Error Bad cast from type DB::ColumnVector

### ISSUE THREAD

**Issue by zav379** [ClickHouse/ClickHouse#21057]
I can't drop or modify column p_DlgTime in table

CREATE TABLE test.p_DlgTime
(
	.........
	p_DlgTime UInt16
       ..........
) 
ENGINE = MergeTree ORDER BY tuple();

ALTER TABLE test.p_DlgTime  MODIFY COLUMN p_DlgTime Float32
return error:
SQL Error [368]: ClickHouse exception, code: 368, host: 192.168.0.23, port: 8123; Code: 368, e.displayText() = DB::Exception: Bad cast from type DB::ColumnVector<unsigned int> to DB::ColumnVector<int> (version 20.3.7.46 (official build))

  ClickHouse exception, code: 368, host: 192.168.0.23, port: 8123; Code: 368, e.displayText() = DB::Exception: Bad cast from type DB::ColumnVector<unsigned int> to DB::ColumnVector<int> (version 20.3.7.46 (official build))

    java.lang.Throwable: Code: 368, e.displayText() = DB::Exception: Bad cast from type DB::ColumnVector<unsigned int> to DB::ColumnVector<int> (version 20.3.7.46 (official build))

ALTER TABLE test.p_DlgTime Drop COLUMN p_DlgTime;
return:
SQL Error [368]: ClickHouse exception, code: 368, host: 192.168.0.23, port: 8123; Code: 368, e.displayText() = DB::Exception: Bad cast from type DB::ColumnVector<unsigned int> to DB::ColumnVector<int> (version 20.3.7.46 (official build))

  ClickHouse exception, code: 368, host: 192.168.0.23, port: 8123; Code: 368, e.displayText() = DB::Exception: Bad cast from type DB::ColumnVector<unsigned int> to DB::ColumnVector<int> (version 20.3.7.46 (official build))

    java.lang.Throwable: Code: 368, e.displayText() = DB::Exception: Bad cast from type DB::ColumnVector<unsigned int> to DB::ColumnVector<int> (version 20.3.7.46 (official build))

I don't now, what does it mean?

**Comment by taylor12805** [comment]
you can only modify column datatype to compatible datatype, for instance
`ALTER TABLE default.p_DlgTime MODIFY COLUMN p_DlgTime UInt32`
or
`ALTER TABLE default.p_DlgTime MODIFY COLUMN p_DlgTime Int32`
The error is thrown because UInt16 and Float32 is not compatible, so it can't convert to Float32 datatype.

**Comment by alexey-milovidov** [comment]
The query works fine on recent ClickHouse versions.
