### ISSUE TITLE
ld: unknown option: -platform_version

### ISSUE THREAD

**Issue by windylcx** [ClickHouse/ClickHouse#21058]
when i try to build ch from source in my Mac OS ,it failed at the step with the following msgs:

```
cmake .. -DCMAKE_C_COMPILER=`brew --prefix llvm`/bin/clang -DCMAKE_CXX_COMPILER=`brew --prefix llvm`/bin/clang++ -DCMAKE_PREFIX_PATH=`brew --prefix llvm`
-- The C compiler identification is Clang 11.1.0
-- The CXX compiler identification is Clang 11.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: /usr/local/opt/llvm/bin/clang
-- Check for working C compiler: /usr/local/opt/llvm/bin/clang - broken

CMake Error at /usr/local/Cellar/cmake/3.19.5/share/cmake/Modules/CMakeTestCCompiler.cmake:66 (message):
  The C compiler

    "/usr/local/opt/llvm/bin/clang"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: ~/ClickHouse/build/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/local/bin/ninja cmTC_b81f1 && [1/2] Building C object CMakeFiles/cmTC_b81f1.dir/testCCompiler.c.o
    [2/2] Linking C executable cmTC_b81f1
    FAILED: cmTC_b81f1 
    : && /usr/local/opt/llvm/bin/clang -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names -L/usr/local/opt/llvm/lib CMakeFiles/cmTC_b81f1.dir/testCCompiler.c.o -o cmTC_b81f1   && :
    ld: unknown option: -platform_version
    clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
    ninja: build stopped: subcommand failed.
```

**Comment by wangzhen11aaa** [comment]
Use command
`ld -v` 
show the linker version.

**Comment by windylcx** [comment]
> Use command
> `ld -v`
> show the linker version.

@(#)PROGRAM:ld  PROJECT:ld64-450.3
BUILD 18:16:53 Apr  5 2019
configured to support archs: armv6 armv7 armv7s arm64 arm64e arm64_32 i386 x86_64 x86_64h armv6m armv7k armv7m armv7em
LTO support using: LLVM version 10.0.1, (clang-1001.0.46.4) (static support for 22, runtime is 22)
TAPI support using: Apple TAPI version 10.0.1 (tapi-1001.0.4.1)

**Comment by windylcx** [comment]
I follow   the [docs] (https://clickhouse.tech/docs/en/development/build-osx/)

**Comment by kitaisreal** [comment]
@windylcx try to reinstall llvm and clang in homebrew.

**Comment by nikitamikhaylov** [comment]
Try to add `/usr/local/opt/llvm/bin/` into your PATH

**Comment by feidaodalian** [comment]
@windylcx hi,I have also  this question  #21867 ，Excuse me, did you solve the problem

**Comment by windylcx** [comment]
> @windylcx hi,I have also this question #21867 ，Excuse me, did you solve the problem

sorry,not yet

**Comment by windylcx** [comment]
> Try to add `/usr/local/opt/llvm/bin/` into your PATH

i try this,doesn't work

**Comment by alexey-milovidov** [comment]
Duplicate #21904
