### ISSUE TITLE
create table not use non-deterministic functions

### ISSUE THREAD

**Issue by maimaip** [ClickHouse/ClickHouse#21055]
Partition key cannot contain non-deterministic functions:

old clickhouse 20.10 stable
`create table app.user_test(id Int32,day Date,s_t Nullable(DateTime))ENGINE = MergeTree() PARTITION BY ifNull(day,today()) ORDER BY ifNull(s_t,now()) TTL day + toIntervalDay(7)`
create table is ok 
new clickhouse version 21.2 stable
`create table app.user_test(id Int32,day Date,s_t Nullable(DateTime))ENGINE = MergeTree() PARTITION BY ifNull(day,today()) ORDER BY ifNull(s_t,now()) TTL day + toIntervalDay(7)` 
create error 
DB::Exception:Partition key cannot contain non-deterministic functions, but contains function today. 
the same create sql but not use in new version clickhouse.

**Comment by alexey-milovidov** [comment]
This behaviour is correct - it protects you from mistakes in table definition.
`PARTITION BY today()` can lead to surprising results - some queries won't be able to find records in table.

Instead you should create `insert_date DEFAULT today()` field in table and `PARTITION BY ifNull(day,insert_date)`
