### ISSUE TITLE
joinGet can not get column when it in join keys

### ISSUE THREAD

**Issue by liubo0127** [ClickHouse/ClickHouse#21061]
When I want to extract column(`id`) in join keys, it report error "StorageJoin doesn't contain column id".

<img width="1382" alt="image" src="https://user-images.githubusercontent.com/28344969/108700997-5c31f000-7542-11eb-9b6e-884b734d2404.png">

**Comment by amosbird** [comment]
Same as dictionary. But the motivation is unclear. Is it to check whether Join table contains a given key? In that case, perhaps we need to provide `joinHas` similar to `dictHas`.

**Comment by filimonov** [comment]
There was a PR for dics recently...

**Comment by liubo0127** [comment]
The MySQL example:
Here are two tables `one` and `two`, with the following requirements
```
DELETE
FROM one
LEFT JOIN two ON one.id=two.id
AND one.name=two.name
AND one.address=two.address
WHERE one.address IS NULL
```

How do I do it with ClickHouse

**Comment by filimonov** [comment]
Not sure if i understand it good. How `joinGet('join','id',id)` will help you?

**Comment by liubo0127** [comment]
> Not sure if i understand it good. How `joinGet('join','id',id)` will help you?
> Or you mean smth like `joinGet('join','id',(id,name,address))`?
> 
> The second definitely make sence.

Thanks

**Comment by amosbird** [comment]
>  but how to create table with `joinGet('join','id',(id,name,address))`

It's possible to use multiple keys after https://github.com/ClickHouse/ClickHouse/pull/13015 

In order to lookup key columns, you have to make a duplicate column, for example:

```
CREATE TABLE test_joinGet(id String, name String, address String, id_value default id) ENGINE = Join(any, left, id, name, address);

INSERT INTO test_joinGet (id, name, address) VALUES ('ab', '1', 'x'), ('ab', '2', 'y'), ('cd', '3', 'z');

SELECT joinGet(test_joinGet, 'id_value', 'ab', '1', 'x');
```
