### ISSUE TITLE
Slow data replication

### ISSUE THREAD

**Issue by cw9** [ClickHouse/ClickHouse#21089]
I'm recently seeing 5X longer data replication time for node replaces.

the system.replication_queue table is showing a lot of entries with postpone_reason
`Not executing fetch of part 448335_0_0_0 because 3 fetches already executing, max 3.`

Is this causing the slow node replace? If so is there anything I can do to fix this?

**Comment by cw9** [comment]
Ah I see, there is a new field `background_fetches_pool_size` that I didn't config, I had `background_schedule_pool_size = 16`.

Can someone share some insights on why the new config?

**Comment by den-crane** [comment]
It seems Yandex internally has a small number of Replicated tables and very fast and reliable network. 
3 is enough for them and not for everybody else.

**Comment by cw9** [comment]
so background_fetches_pool_size is related to number of tables?

**Comment by den-crane** [comment]
related to a number of simultaneous fetches.

if you make 1 insert per second into 1 table you need to fetch 1 part.
if you make 1 insert per second into 100 tables you need to fetch 100 parts.

**Comment by cw9** [comment]
hmm, despite I have more tables recently than before, the inserts per second across all tables didn't change much, is there anything else that can impact data replication speed? Also is there anything else I should check other than system.replication_queue table?

**Comment by den-crane** [comment]
So you did not upgrade your CH ?

**Comment by cw9** [comment]
I did upgrade to 20.12.4 recently

**Comment by cw9** [comment]
Why do I sometimes see no replicated fetches 
```
SELECT count()
FROM system.replicated_fetches

Query id: 403d71a7-06e8-430a-a152-a94ce1843321

┌─count()─┐
│       0 │
└─────────┘
```

When there are tables data still to be replicated?
```
SELECT count()
FROM system.replicas
WHERE queue_size > 20

Query id: 16843d56-f5f8-4757-8828-e27912fe50d9

┌─count()─┐
│       4 │
└─────────┘
```

**Comment by den-crane** [comment]
probably because postpone is logarithmic. Check  system.replicated_queue

**Comment by cw9** [comment]
There are a lot of entries in system.replicated_queue, is there any way to config the retry behavior?

**Comment by cw9** [comment]
Gentle ping on this, I'm still seeing idle periods where no data replication is happening after hours of replication, I have to restart the new node to get the data replication to run in full speed again.
![image](https://user-images.githubusercontent.com/6710599/110488701-b42d3280-80bc-11eb-8f78-04e30c63c6bc.png)

**Comment by alexey-milovidov** [comment]
21.8 should be better.
