### ISSUE TITLE
Parquet support List datatype

### ISSUE THREAD

**Issue by taylor12805** [ClickHouse/ClickHouse#21080]
**Use case**
Support reading from parquet list datatype to ClickHouse Array and vice versa.

**Describe the solution you'd like**
since ClickHouse use arrow to transfer data between ClickHouse and Parquet, i think it is possible to extend [CHColumnToArrowColumn](https://github.com/ClickHouse/ClickHouse/blob/master/src/Processors/Formats/Impl/CHColumnToArrowColumn.cpp) to support reading from ClickHouse Array datatype to Parquet and extend [ArrowColumnToCHColumn](https://github.com/ClickHouse/ClickHouse/blob/master/src/Processors/Formats/Impl/ArrowColumnToCHColumn.cpp) to support reading from Parquet List datatype to ClickHouse Array.

I am working on it now

**Comment by filimonov** [comment]
Great news! Nobody is currently working on the task so it's yours. 

See also: https://github.com/ClickHouse/ClickHouse/issues/7704

Please let us know if you will need any help / support with that.

**Comment by filimonov** [comment]
You need to map arrow arrays to clickhouse arrays of corresponding subtypes, and create tests for that.

It should be smth like type detection / mapping + smth like 'fillColumnWithArrayData' template(?) function (maybe with some specialization will be needed for particular subtypes) + at least one test for every array subtype.

And similar stuff should happen for writer.

After that part will be done there is also an extended scope of that task - for an array of structs, that can be also taken after the first part will be ready.

**Comment by den-crane** [comment]
ORC & Parquet (not sure) allows Null instead of list.
Let's implement these


from ORC(list) | Clickhouse | back to ORC(list)
-- | -- | --
[] | [] | []
[null] | [null] | [null]
null | [] | []



```pyhton
with open("./test4.orc", "wb") as data:
    with pyorc.Writer(data, "struct<col0:array<int>,col1:array<string>>") as writer:
        writer.write(([0], ["Test 0"]))
        writer.write(([None], [None]))
        writer.write((None, None))
```

**Comment by taylor12805** [comment]
> ORC & Parquet (not sure) allows Null instead of list.
> Let's implement these
> 
> from ORC(list)	Clickhouse	back to ORC(list)
> []	[]	[]
> [null]	[null]	[null]
> null	[]	[]
> ```python
> with open("./test4.orc", "wb") as data:
>     with pyorc.Writer(data, "struct<col0:array<int>,col1:array<string>>") as writer:
>         writer.write(([0], ["Test 0"]))
>         writer.write(([None], [None]))
>         writer.write((None, None))
> ```

Sure, I will pay attention to this situation

**Comment by taylor12805** [comment]
> ORC & Parquet (not sure) allows Null instead of list.
> Let's implement these
> 
> from ORC(list)	Clickhouse	back to ORC(list)
> []	[]	[]
> [null]	[null]	[null]
> null	[]	[]
> ```python
> with open("./test4.orc", "wb") as data:
>     with pyorc.Writer(data, "struct<col0:array<int>,col1:array<string>>") as writer:
>         writer.write(([0], ["Test 0"]))
>         writer.write(([None], [None]))
>         writer.write((None, None))
> ```

Hi, den-crane
is ClickHouse support null array as you mentioned 
Clickhouse |
--|
[null] |

because when I created a table:
`CREATE TABLE default.event_table
(
    `id` String,
    `extended_field` Array(String)
) ENGINE = MergeTree()
ORDER BY tuple()`
and insert null data
`
insert into event_table (id, extended_field) values ('123', [null])
`

it appears that ClickHouse doesn't store null value

id | extended_field |
--|:--
123 |  [] |

**Comment by filimonov** [comment]
```
CREATE TABLE default.event_table
(
    `id` String,
    `extended_field` Array(Nullable(String))
) ENGINE = MergeTree()
ORDER BY tuple()
```

**Comment by taylor12805** [comment]
> Try:
> 
> ```
> CREATE TABLE default.event_table
> (
>     `id` String,
>     `extended_field` Array(Nullable(String))
> ) ENGINE = MergeTree()
> ORDER BY tuple()
> ```
> 
> How the task is going? Any progress? Do you need any help?

I think i missed this scenario in the implementation, i will try to fix it.

**Comment by faisalhasnain** [comment]
@taylor12805 any idea when it will get merged? we need to import large volume of data  from parquet files into clickhouse and the data contains columns as array of strings and array of objects.

**Comment by Avogar** [comment]
The PR was merged.
