### ISSUE TITLE
REMOVE TTL doesn't work

### ISSUE THREAD

**Issue by windylcx** [ClickHouse/ClickHouse#21103]
![image](https://user-images.githubusercontent.com/917238/108838315-6f11f680-760e-11eb-8470-d7947e53f59b.png)

my version:

ClickHouse client version 20.9.3.45 (official build).

https://clickhouse.tech/docs/en/sql-reference/statements/alter/ttl/

![image](https://user-images.githubusercontent.com/917238/108838552-bef0bd80-760e-11eb-874a-2b64618fca39.png)

**Comment by filimonov** [comment]
It was added in 20.10.

See #14742. Check also: https://github.com/ClickHouse/ClickHouse/pull/18130

Please update to one of the latest versions

**Comment by ypg521** [comment]
How remove TTL in table ?
in 20.8

**Comment by alexey-milovidov** [comment]
Q: How to remove TTL in ClickHouse version 20.8?
A: It takes two steps. Step 1: Upgrade to ClickHouse version 20.2. Step 2. Remove TTL.

**Comment by ypg521** [comment]
> Q: How to remove TTL in ClickHouse version 20.8?
> A: It takes two steps. Step 1: Upgrade to ClickHouse version 21.2 or newer. Step 2: Remove TTL with ALTER TABLE ... REMOVE TTL query.

Thanks , and sorry for my bad English
