### ISSUE TITLE
RabbitMQ ENGINE randomly re publishing messages

### ISSUE THREAD

**Issue by khlystov** [ClickHouse/ClickHouse#21112]
**Describe the bug**
I have a table based on RabbitMQ ENGINE, I do inserts in that table and it works as expected and I am able to see incoming messages in rabbitmq. BUT from time to time I am getting this log message in the error log and exactly after that one of my previously posted messages becomes republished.

2021.02.23 17:43:16.443563 [ 21028 ] {} <Error> StorageRabbitMQ (test): Producer's channel 20 error: connection lost
2021.02.23 17:43:16.443671 [ 21028 ] {} <Error> StorageRabbitMQ (test): Library error report: connection lost

**Does it reproduce on recent release?**
 ClickHouse server version 21.2.4 revision 54447

**How to reproduce**
* Which ClickHouse server version to use
ClickHouse server version 21.2.4 revision 54447
* Queries to run that lead to unexpected result
`drop table if exists clickhouse.test;
drop table if exists clickhouse.input;
drop table if exists clickhouse.clickhouse_mv;
drop table if exists clickhouse.clickhouse_mv;

CREATE TABLE clickhouse.test ( 
	key UInt64,
	value UInt64,
	date DateTime
) ENGINE = RabbitMQ SETTINGS rabbitmq_host_port = ' ',
	rabbitmq_exchange_name = 'test',
	rabbitmq_format = 'JSONEachRow',
	rabbitmq_persistent = 1,
	rabbitmq_num_consumers = 1;

CREATE TABLE clickhouse.input ( 
	key UInt64,
	value UInt64,
	date DateTime 
) Engine = MergeTree ORDER BY (date);

CREATE MATERIALIZED VIEW clickhouse.clickhouse_mv TO clickhouse.test AS 
SELECT * FROM clickhouse.input;

INSERT INTO clickhouse.`input` (`key`, value) VALUES(52, 5221);
`

**Expected behavior**
I think once a message is published it should not be published again. 

**Error message and/or stacktrace**
![image](https://user-images.githubusercontent.com/1534096/108886124-a3d77b00-7619-11eb-9782-a2b37c1eb150.png)

2021.02.23 17:43:16.443563 [ 21028 ] {} <Error> StorageRabbitMQ (test): Producer's channel 20 error: connection lost
2021.02.23 17:43:16.443671 [ 21028 ] {} <Error> StorageRabbitMQ (test): Library error report: connection lost

**Comment by kssenii** [comment]
@khlystov, what is the average time period between two `connection lost` logs? And much data was approximately inserted between them?

**Comment by khlystov** [comment]
> @khlystov, what is the average time period between two `connection lost` logs? And much data was approximately inserted between them?
from 1 to 3 minutes. just one row

**Comment by khlystov** [comment]
@kssenii from 1 to 3 minutes. just one row

**Comment by kssenii** [comment]
@khlystov, how often these single row inserts are made?

**Comment by khlystov** [comment]
@kssenii actually it happens exactly every 3 minutes

2021.02.23 18:31:29.387849 [ 21028 ] {} <Error> StorageRabbitMQ (test): Producer's channel 216 error: connection lost
2021.02.23 18:31:29.387996 [ 21028 ] {} <Error> StorageRabbitMQ (test): Library error report: connection lost

2021.02.23 18:34:30.193880 [ 21028 ] {} <Error> StorageRabbitMQ (test): Producer's channel 217 error: connection lost
2021.02.23 18:34:30.193962 [ 21028 ] {} <Error> StorageRabbitMQ (test): Library error report: connection lost

**Comment by khlystov** [comment]
@kssenii just once. I am prototyping right now and do such  single row inserts for tests

**Comment by kssenii** [comment]
@khlystov, now it should be ok. If the problem is still present, please, write again.

**Comment by panterkta** [comment]
gh pr checkout 21138

**Comment by khlystov** [comment]
@kssenii still the same 

2021.03.08 08:57:35.928839 [ 3215 ] {} <Error> StorageRabbitMQ (sbgi_input1): Producer's channel 1_0 error: connection lost
2021.03.08 08:57:35.928964 [ 3215 ] {} <Error> StorageRabbitMQ (sbgi_input1): Library error report: connection lost
2021.03.08 08:58:20.541654 [ 3223 ] {} <Error> StorageRabbitMQ (sbgi_input1): Producer's channel 2_0 error: connection lost
2021.03.08 08:58:20.541784 [ 3223 ] {} <Error> StorageRabbitMQ (sbgi_input1): Library error report: connection lost
2021.03.08 09:00:37.072549 [ 3215 ] {} <Error> StorageRabbitMQ (sbgi_input1): Producer's channel 1_1 error: connection lost
2021.03.08 09:00:37.072654 [ 3215 ] {} <Error> StorageRabbitMQ (sbgi_input1): Library error report: connection lost
2021.03.08 09:01:03.917943 [ 3209 ] {} <Error> StorageRabbitMQ (sbgi_input1): Producer's channel 3_0 error: connection lost
2021.03.08 09:01:03.918054 [ 3209 ] {} <Error> StorageRabbitMQ (sbgi_input1): Library error report: connection lost
2021.03.08 09:01:21.684470 [ 3223 ] {} <Error> StorageRabbitMQ (sbgi_input1): Producer's channel 2_1 error: connection lost
2021.03.08 09:01:21.684560 [ 3223 ] {} <Error> StorageRabbitMQ (sbgi_input1): Library error report: connection lost

**Comment by khlystov** [comment]
@kssenii  also new error during data inserts 

2021.03.08 09:08:31.734606 [ 3465 ] {b5cbe893-ec57-4d6c-92cd-1d565974a680} <Error> DynamicQueryHandler: Code: 530, e.displayText() = DB::Exception: Cannot connect to RabbitMQ host: 134.209.105.54, port: 5672: while write prefix to view rabbitmq.sbgi_input_mv (3c38740e-19f6-4f46-9d46-086209876f97), Stack trace (when copying this message, always include the lines below):

**Comment by kssenii** [comment]
BTW, I just noticed, you are using the same table for mv and inserts?
> CREATE MATERIALIZED VIEW clickhouse.clickhouse_mv TO clickhouse.test AS
SELECT * FROM clickhouse.input;
INSERT INTO clickhouse.input (key, value) VALUES(52, 5221);

It is written in doc that it is not allowed, and in this case there should be more error messages.

**Comment by khlystov** [comment]
> BTW, I just noticed, you are using the same table for mv and inserts?
> 
> > CREATE MATERIALIZED VIEW clickhouse.clickhouse_mv TO clickhouse.test AS
> > SELECT * FROM clickhouse.input;
> > INSERT INTO clickhouse.input (key, value) VALUES(52, 5221);
> 
> It is written in doc (probably not easy to notice though) that it is not allowed, and in this case there should be more error messages.

My current setup is:

 
CREATE TABLE rabbitmq.sbgi_input (
objectId String DEFAULT '',
objectType String DEFAULT '',
sourceId String DEFAULT '',
target String DEFAULT '',
instance String DEFAULT '',
placeRaw String DEFAULT '',
regionRaw String DEFAULT '',
countyRaw String DEFAULT '',
countryRaw String DEFAULT '',
ladRaw String DEFAULT '',
locationRaw String DEFAULT '',
locationStringRaw String DEFAULT '',
jobTitleRaw String DEFAULT '',
companyRaw String DEFAULT '',
skillsRaw String DEFAULT '',
experienceRaw String DEFAULT '',
schoolRaw String DEFAULT '',
schoolUrlRaw String DEFAULT '',
fullnameRaw  String DEFAULT ''
) ENGINE = RabbitMQ SETTINGS rabbitmq_host_port = ' 4:5672',
rabbitmq_exchange_name = 'sbgi.input',
rabbitmq_format = 'JSONEachRow',
rabbitmq_persistent = 1,
rabbitmq_num_consumers = 1;

CREATE MATERIALIZED VIEW rabbitmq.sbgi_input_mv TO rabbitmq.sbgi_input AS
select 
	version as objectId, 
	'employee' as objectType,
	location as locationStringRaw
from lkdn_profiles.employees;

**Comment by kssenii** [comment]
But MV in regard to RabbitMQ table are used not in this way:

> CREATE MATERIALIZED VIEW rabbitmq.sbgi_input_mv TO **rabbitmq.sbgi_input** AS
select
version as objectId,
'employee' as objectType,
location as locationStringRaw
from **lkdn_profiles.employees**;

But it should be:

> CREATE MATERIALIZED VIEW rabbitmq.sbgi_input_mv TO  **lkdn_profiles.employees** AS
select
version as objectId,
'employee' as objectType,
location as locationStringRaw
from **rabbitmq.sbgi_input**;

And if you want to insert into table, you use `INSERT INTO rabbitmq.sbgi_input`

**Comment by khlystov** [comment]
> But MV in regard to RabbitMQ table are used not in this way:
> 
> > CREATE MATERIALIZED VIEW rabbitmq.sbgi_input_mv TO **rabbitmq.sbgi_input** AS
> > select
> > version as objectId,
> > 'employee' as objectType,
> > location as locationStringRaw
> > from **lkdn_profiles.employees**;
> 
> But it should be:
> 
> > CREATE MATERIALIZED VIEW rabbitmq.sbgi_input_mv TO  **lkdn_profiles.employees** AS
> > select
> > version as objectId,
> > 'employee' as objectType,
> > location as locationStringRaw
> > from **rabbitmq.sbgi_input**;
> 
> And if you want to insert into table, you use `INSERT INTO rabbitmq.sbgi_input`

but I need to write data into rabbitmq.sbgi_input based on new data from lkdn_profiles.employees

**Comment by kssenii** [comment]
MV `into` rabbitmq table is not implemented, you can only make MV `from` rabbitmq table. 

So current setup is:
If you wan't to channel data `into` ClickHouse via RabbitMQ table engine, you use materialised view like `as select * from rabbitmq_table`. If you want to channel data `out of` ClickHouse into RabbitMQ, you use `insert into rabbitmq_table`.

**Comment by kssenii** [comment]
Though I think there are a few small changes needed to make MV `into` rabbitmq table work. For now it does not work properly, because connection is supposed to be closed once current outputStream is finished. And there are errors like yours, because no measures are taken to sustain this connection object while it becomes idle (because it was supposed to used only with `insert` queries).
