### ISSUE TITLE
Row Policy - confusing documentation for Restrictive and Permissive.

### ISSUE THREAD

**Issue by MyroTk** [ClickHouse/ClickHouse#21110]
**Describe the issue**
The documentation says `Permissive policy grants access to rows` and `Restrictive policy restricts access to rows` but that's a bit misleading because they do the same thing in terms of permitting access to rows that meet their condition. The rest of the `AS Clause` explains the difference well, but these initial statements are unnecessary.

**Comment by alexey-milovidov** [comment]
Fixed.
