### ISSUE TITLE
Merge is not performed after batch data insert

### ISSUE THREAD

**Issue by SE2AI** [ClickHouse/ClickHouse#21115]
Dear authors, 

I am testing `partition by` feature with `MergeTree` engine. But after inserting batch number of data, I found that `system.parts` shows the partitons are **never** merged (but the active=1). Then I tried `optimze` command assigned to specific partition key, after a while, the partition fragments are merged successfully. 

Could you please explain why the merge behavior doesn't conducted unless with the `optimize`? If the partitions are not merged, will the performance of clickhouse be effected?

The result in `system.parts` are attached below:
The first two are manually merged by `optimize`, the rest partitions are fragments which are never merged.
I think partitions of ('20\0\0\0','00\0\0\0') should be merged into datablock a1ce303e292f_4_1194_3_1224, but it's not.
```sql
┌─partition───────────────┬─name──────────────────────────┬─active─┐
│ ('40\0\0\0','5000\0')   │ 54d2d42178080f8_7_1192_3_1224 │      1 │
│ ('50\0\0\0','10000')    │ 88781210a425d7_17_1150_3_1224 │      1 │
│ ('20\0\0\0','00\0\0\0') │ a1ce303e292f_4_367_2_1224     │      1 │
│ ('20\0\0\0','00\0\0\0') │ a1ce303e292f_391_758_2_1224   │      1 │
│ ('20\0\0\0','00\0\0\0') │ a1ce303e292f_785_1120_2_1224  │      1 │
│ ('20\0\0\0','00\0\0\0') │ a1ce303e292f_1146_1146_0_1224 │      1 │
│ ('20\0\0\0','00\0\0\0') │ a1ce303e292f_1166_1166_0_1224 │      1 │
│ ('20\0\0\0','00\0\0\0') │ a1ce303e292f_1180_1180_0_1224 │      1 │
│ ('20\0\0\0','00\0\0\0') │ a1ce303e292f_1194_1194_0_1224 │      1 │
└─────────────────────────┴───────────────────────────────┴────────┘
```

many thanks!

**Comment by den-crane** [comment]
CH does not merge parts by time. 
Merge scheduler selects parts by own algorithm based on the current node workload / number of parts / size of parts.
https://github.com/ClickHouse/ClickHouse/issues/8322#issuecomment-567990939

>If the partitions are not merged, will the performance of clickhouse be effected?

No, CH merge scheduler balance between big number of parts and wasting resources on merges. 
Merges are CPU/DISK IO expensive. If CH will merge every new part then all resources will be spend on merges and will no resources remain on queries (selects ).

**Comment by SE2AI** [comment]
Thanks Denny! I check #8322 (comment) detailedly, it really helps a lot. 
So If `active` equals to 1 for some partitions, it means I need not to care about how many partitions there are, right? Even there are some single partitions?
If merge is resource expensive, what is `OPTIMIZE` designed for and what are the most appropriate application scenarios for using it?

**Comment by den-crane** [comment]
>So If active equals to 1 for some partitions, it means I need not to care 
>about how many partitions there are, right? Even there are some single partitions?

right.

>If merge is resource expensive, what is OPTIMIZE designed for and
> what are the most appropriate application scenarios for using it?

1. debug purposes. OPTIMIZE is used in CH tests extensively because tests need to verify from the SQL layer that after the FINAL merge data is merged correctly.
2. there is GraphiteMergeTree -- it is designed to reduce/resample data during merges. You can set a rule -- "rollup to 1hour after 1 week, and then rollup to 1day after 2 months". The merge scheduler is not aware about GraphiteMergeTree rollup feature. Merge scheduler will not merge the data older 2 months because it thinks that data is merged. The only way to execute this "rollup to 1day after 2 months" is to run "OPTIMIZE FINAL" against the old partitions.
3...
4...

**Comment by SE2AI** [comment]
Thank you very much, I understand how it works now: )
