### ISSUE TITLE
Materialized View: argMax does not return the argument corresponding to the FIRST occurence of the maximum value

### ISSUE THREAD

**Issue by cyber-moon** [ClickHouse/ClickHouse#21139]
Say I have the following table:
| timestamp | type | selectivity |
| --- | --- | --- |
| 139 | a | 3 |
| 143 | f | 1 |
| 298 | a | 4 |
| 197 | a | 4 |
| ... | ... | ... |

Timestamp is a unique number, selectivity is a non-unique number. The table contains many dublicate type-selectivity combinations (such as row 3 and 4 in the above example).

For each type, I need the maximum selectivity and the corresponding timestamp. If several entries reach the maximum selectivity, I want the latest (i.e. highest) timestamp. In the above example, this would be:
| timestamp | type | selectivity |
| --- | --- | --- |
| 143 | f | 1 |
| 298 | a | 4 |

The most efficient way to achieve this, as far as I am aware, is to use the GROUP BY clause together with max and argMax. By first sorting the timestamps in _descending_ order, I make use of the fact that argMax(timestamp, selectivity) returns the timestamp corresponding to the _first_ occurence of the maximum selectivity (see [here](https://clickhouse.tech/docs/en/sql-reference/aggregate-functions/reference/argmax/)). Thus the highest timestamp is returned.
```sql
SELECT argMax(timestamp, selectivity) as time_at_max_selectivity,
       type,
       max(selectivity) as max_selectivity
FROM (SELECT *
      FROM my_data
      ORDER BY timestamp DESC)
GROUP BY type
ORDER BY type;
```
This works as expected and returns correct values.

When introducing Materialized Views to speed up the query, Clickhouse doesn't return the correct values anymore. I assume that my table is somehow resorted and thus argMax does not return the _first_ occurence.

Here a minimal working example creating the materialized view and fetching the result.
```sql
CREATE MATERIALIZED VIEW my_data_materialized
ENGINE = AggregatingMergeTree() ORDER BY type
AS SELECT argMaxState(timestamp, selectivity) AS timestamp_state,
          type,
          maxState(selectivity) AS selectivity_state
FROM (SELECT *
      FROM my_data
      ORDER BY timestamp DESC)
GROUP BY type;
```
```sql
SELECT argMaxMerge(timestamp_state) as time_at_max_selectivity,
       type,
       maxMerge(selectivity_state) as max_selectivity
FROM my_data_materialized
GROUP BY type
ORDER BY type;
```

Help is very much appreciated - is there anything wrong with how I use the materialized view, or is there a better option to reach the same result? Or is this a misbehavior of Clickhouse?

**Comment by den-crane** [comment]
MV is an insert trigger. It gets data from insert. **IT NEVER READS THE SOURCE TABLE.**
    ENGINE OF THE SOURCE TABLE DOES NOT MATTER.

Check this:
https://den-crane.github.io/Everything_you_should_know_about_materialized_views_commented.pdf
https://youtu.be/ckChUkC3Pns?list=PLO3lfQbpDVI-hyw4MyqxEk3rDHw95SzxJ&t=9371

**Comment by den-crane** [comment]
Try tuple comparison  (selectivity, timestamp)

```
SELECT argMax(timestamp, (selectivity, timestamp) ) as time_at_max_selectivity,
       type,
       max(selectivity) as max_selectivity
FROM my_data
GROUP BY type
ORDER BY type;```


```
argMaxState(timestamp, (selectivity, timestamp) ) 
```

**Comment by cyber-moon** [comment]
Hey @den-crane 
Thanks for the fast answer! I wasn't aware that we can maximize over tuples, this definitely solves the problem and is way nicer than my approach. Thanks a lot!
