### ISSUE TITLE
Segfault in FULL JOIN

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#21137]
https://clickhouse-test-reports.s3.yandex.net/21020/2ced21c837006053542b9f04c338faebf504f413/fuzzer_asan/server.log

**Comment by alexey-milovidov** [comment]
https://clickhouse-test-reports.s3.yandex.net/20393/f8f475e83fc5a08a113417ff385eaacd1292ec2b/fuzzer_msan/report.html#fail1

**Comment by vdimir** [comment]
Same bug as issue #19362, closed via PR #21248
