### ISSUE TITLE
column bin file 

### ISSUE THREAD

**Issue by ac3225020** [ClickHouse/ClickHouse#21141]
i am new to clickhouse, i want to figure out how column store works. Now i use mergetree engine to create table, but i find that  all the column data store in one file named data.bin, how can i create a table for store different column data in individual file.
the create table ddl:
 CREATE TABLE test.order
(
    `orderid` String COMMENT '订单号',
    `orderstatus` Nullable(String) COMMENT '订单状态',
    `incomeconfirmtime` Nullable(String) COMMENT '收入确认时间',
    `d` Date
)
ENGINE = MergeTree
PARTITION BY d
ORDER BY orderid
SETTINGS index_granularity = 8192 

the data file path:
![image](https://user-images.githubusercontent.com/10062515/108999261-06457f80-76dd-11eb-926f-1285278f500c.png)

**Comment by UnamedRus** [comment]
You need to disable compact format

```
ALTER TABLE  test.order MODIFY SETTING min_bytes_for_wide_part=0,min_rows_for_wide_part=0
```

**Comment by alexey-milovidov** [comment]
Compact format is also column-oriented but with columns placed in one file.
