### ISSUE TITLE
Insert a record with too many columns leads an exception when using clickhouse-jdbc

### ISSUE THREAD

**Issue by mdianjun** [ClickHouse/ClickHouse#21187]
**Describe the bug**
Insert a record with too many columns leads an exception.

**How to reproduce**
* ClickHouse server version：20.8.10.13
* Interface：clickhouse-jdbc
* Insert one record with 2019 columns，and an Unknown Exception is thrown. Analyze the http packet between the jdbc and clickhouse-server， jdbc send a request "POST /?query=insert+into+... (many columns)"，but the request has not been finished, the server send a response:
```
HTTP/1.1 400 Bad Request
Connection: Close
```
And then jbdc continue to send the remaining request packet.

I think, maybe the server side has a max size of received http packet, but the http request is beyond the size limit.

**Comment by den-crane** [comment]
it's https://github.com/ClickHouse/clickhouse-jdbc issue. Open ticket in https://github.com/ClickHouse/clickhouse-jdbc/issues
