### ISSUE TITLE
What data types are supported in external dictionaries

### ISSUE THREAD

**Issue by cyberhuman** [ClickHouse/ClickHouse#21209]
The [documentation](https://clickhouse.tech/docs/en/sql-reference/dictionaries/external-dictionaries/external-dicts-dict-structure/#ext_dict_structure-attributes) mentions Nullable is not supported, but it appears Enum is not supported, too. Or is it a bug?

```
CREATE DATABASE test

CREATE TABLE test.tbl
(
    `key` String,
    `value` Enum('Foo' = 0, 'Bar' = 1)
)
ENGINE = MergeTree
ORDER BY (key, value)

CREATE DICTIONARY test.dict
(
    `key` String,
    `value` Enum('Foo' = 0, 'Bar' = 1)
)
PRIMARY KEY key
SOURCE(CLICKHOUSE(DATABASE 'test' TABLE 'tbl'))
LIFETIME(MIN 0 MAX 0)
LAYOUT(HASHED)

Received exception from server (version 21.1.3):
Code: 50. DB::Exception: Received from 10.100.0.76:9001. DB::Exception: Unknown type Enum('Foo' = 0, 'Bar' = 1).
```

**Comment by cyberhuman** [comment]
any news here?

**Comment by kitaisreal** [comment]
Hello, @cyberhuman.

Currently we support:
1. UInt8, UInt16, UInt32, UInt64, UInt128
2. Int8, Int16, Int32, Int64
3. Float32, Float64, Decimal32, Decimal64, Decimal128
4. String
5. Nullable types are supported not in all dictionaries, flat dictionary, hashed, complex key hashed, direct, complex key direct, supports nullable
6. PolygonDictionary support Array

Related to your question enums are not yet supported.
From our dictionaries roadmap next types to support is nullable and array.
After that we can add Enum support, Decimal256, Int128, Int256.

**Comment by cyberhuman** [comment]
@kitaisreal thank you very much for your answer!
I'm really looking forward to see Nullable, arrays and enums being supported!
