### ISSUE TITLE
Memory limit (total) exceeded: would use 64.00 GiB (attempt to allocate chunk of 4217828 bytes), maximum: 64.00 GiB, Stack trace (when copying this message, always include the lines below):

### ISSUE THREAD

**Issue by Sallery-X** [ClickHouse/ClickHouse#21218]
2021.02.26 00:42:41.734859 [ 14500 ] {161ad650-be23-4a05-a205-ac18f746702b} <Error> DynamicQueryHandler: Code: 241, e.displayText() = DB::Exception: Memory limit (total) exceeded: would use 64.00 GiB (attempt to allocate chunk of 4217828 bytes), maximum: 64.00 GiB, Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x18cd2050 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xe63232d in /usr/bin/clickhouse
2. ? @ 0xe61fdcf in /usr/bin/clickhouse
3. MemoryTracker::alloc(long) @ 0xe61e736 in /usr/bin/clickhouse
4. MemoryTracker::alloc(long) @ 0xe61e736 in /usr/bin/clickhouse
5. MemoryTracker::alloc(long) @ 0xe61e736 in /usr/bin/clickhouse
6. DB::CompressedWriteBuffer::CompressedWriteBuffer(DB::WriteBuffer&, std::__1::shared_ptr<DB::ICompressionCodec>, unsigned long) @ 0x1550caf4 in /usr/bin/clickhouse
7. DB::MergeTreeDataPartWriterOnDisk::Stream::Stream(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::IDisk>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::ICompressionCodec> const&, unsigned long, unsigned long, unsigned long) @ 0x161806be in /usr/bin/clickhouse
8. ? @ 0x161856ed in /usr/bin/clickhouse
9. DB::MergeTreeDataPartWriterWide::MergeTreeDataPartWriterWide(std::__1::shared_ptr<DB::IMergeTreeDataPart const> const&, DB::NamesAndTypesList const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeIndex const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeIndex const> > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::ICompressionCodec> const&, DB::MergeTreeWriterSettings const&, DB::MergeTreeIndexGranularity const&) @ 0x161861e2 in /usr/bin/clickhouse
10. DB::MergeTreeDataPartWide::getWriter(DB::NamesAndTypesList const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeIndex const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeIndex const> > > const&, std::__1::shared_ptr<DB::ICompressionCodec> const&, DB::MergeTreeWriterSettings const&, DB::MergeTreeIndexGranularity const&) const @ 0x16174f40 in /usr/bin/clickhouse

**Comment by den-crane** [comment]
Clickhouse version?
Query?

It's not bug. It's normal behavior. CH checks memory required for a query execution and available memory. 
This check is implemented to prevent OOM.

you can configure `<max_server_memory_usage_to_ram_ratio>5</max_server_memory_usage_to_ram_ratio>`

```
config.xml
    <!-- Maximum memory usage (resident set size) for server process.
         Zero value or unset means default. Default is "max_server_memory_usage_to_ram_ratio" of available physical RAM.
         If the value is larger than "max_server_memory_usage_to_ram_ratio" of available physical RAM, it will be cut down.

         The constraint is checked on query execution time.
         If a query tries to allocate memory and the current memory usage plus allocation is greater
          than specified threshold, exception will be thrown.

         It is not practical to set this constraint to small values like just a few gigabytes,
          because memory allocator will keep this amount of memory in caches and the server will deny service of queries.
      -->
    <max_server_memory_usage>0</max_server_memory_usage>

    <!-- On memory constrained environments you may have to set this to value larger than 1.
      -->
    <max_server_memory_usage_to_ram_ratio>0.9</max_server_memory_usage_to_ram_ratio>

```
