### ISSUE TITLE
Cannot write to ostream at offset 56864

### ISSUE THREAD

**Issue by Sallery-X** [ClickHouse/ClickHouse#21219]
2021.02.26 12:02:26.515511 [ 28814 ] {bd6be0c4-9a3e-4347-bfbe-8900dbeef61c} <Error> DynamicQueryHandler: Cannot send exception to client: Code: 24, e.displayText() = DB::Exception: Cannot write to ostream at offset 56864, Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x18cd2050 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xe63232d in /usr/bin/clickhouse
2. ? @ 0x1033d62a in /usr/bin/clickhouse
3. DB::WriteBufferFromHTTPServerResponse::nextImpl() @ 0x163500a2 in /usr/bin/clickhouse
4. DB::HTTPHandler::trySendExceptionToClient(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&, DB::HTTPHandler::Output&) @ 0x16347d04 in /usr/bin/clickhouse
5. ? @ 0x1634b3ca in /usr/bin/clickhouse
6. Poco::Net::HTTPServerConnection::run() @ 0x18bb1df3 in /usr/bin/clickhouse
7. Poco::Net::TCPServerConnection::start() @ 0x18bf000b in /usr/bin/clickhouse
8. Poco::Net::TCPServerDispatcher::run() @ 0x18bf0728 in /usr/bin/clickhouse
9. Poco::PooledThread::run() @ 0x18d6ee36 in /usr/bin/clickhouse
10. Poco::ThreadImpl::runnableEntry(void*) @ 0x18d6a230 in /usr/bin/clickhouse
11. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
12. clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
 (version 20.8.11.17 (official build))

**Comment by den-crane** [comment]
It's not a bug.

What error happened at a client?

>DB::Exception: Cannot write to ostream at offset 56864

In general this error signals that HTTP client has gone and Clickhouse was unable to send a response.
