### ISSUE TITLE
Clickhouse process crashed during concurrent queries

### ISSUE THREAD

**Issue by yiguolei** [ClickHouse/ClickHouse#21236]
(you don't have to strictly follow this form)

**Describe the bug**
During perf test, clickhouse process crashed!!

**Does it reproduce on recent release?**
NO
**How to reproduce**
* version 21.1.2.15

**Error message and/or stacktrace**
2021.02.26 17:27:57.749852 [ 13775 ] {} <Fatal> BaseDaemon: ########################################
2021.02.26 17:27:57.749894 [ 13775 ] {} <Fatal> BaseDaemon: (version 21.1.2.15, no build id) (from thread 12439) (query_id: e86b3337-016a-43f1-918e-e77790c05dda) Received signal Aborted (6)
2021.02.26 17:27:57.749909 [ 13775 ] {} <Fatal> BaseDaemon:
2021.02.26 17:27:57.749936 [ 13775 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f4c3f366387 0x7f4c3f367a78 0xc6cd7f0 0x8b9ef2d 0x8b9ef5a
2021.02.26 17:27:57.761948 [ 13775 ] {} <Fatal> BaseDaemon: 3. gsignal @ 0x36387 in /usr/lib64/libc-2.17.so
2021.02.26 17:27:57.762364 [ 13775 ] {} <Fatal> BaseDaemon: 4. abort @ 0x37a78 in /usr/lib64/libc-2.17.so
2021.02.26 17:27:57.769644 [ 13775 ] {} <Fatal> BaseDaemon: 5. _Unwind_Resume @ 0xc6cd7f0 in /data/c_log/repository/clickhouse-server-21.1.2.15-v1/server/bin/clickhouse
2021.02.26 17:27:57.769714 [ 13775 ] {} <Fatal> BaseDaemon: 6. ? @ 0x8b9ef2d in /data/c_log/repository/clickhouse-server-21.1.2.15-v1/server/bin/clickhouse
2021.02.26 17:27:57.770349 [ 13775 ] {} <Fatal> BaseDaemon: 7. void boost::context::detail::fiber_entry<boost::context::detail::fiber_record<boost::context::fiber, FiberStack&, DB::RemoteQueryExecutorRoutine> >(boost::context::detail::transfer_t) @ 0x8b9ef5a in /data/c_log/repository/clickhouse-server-21.1.2.15-v1/server/bin/clickhouse

**Comment by den-crane** [comment]
Can you share a query and DDLs?

zgrep e86b3337-016a-43f1-918e-e77790c05dda /var/log/clickhouse/*

>(version 21.1.2.15, no build id)

It seems it's not an official build. How did you build it? What OS/arch?

**Comment by alexey-milovidov** [comment]
> Does it reproduce on recent release?
NO

So the solution is to install the recent release.

**Comment by ditgittube** [comment]
How did you solve this problem? @yiguolei

**Comment by yej2021** [comment]
How did this problem end up being solved? @yiguolei

**Comment by alexey-milovidov** [comment]
Installing new version fixes the problem:
```
curl https://clickhouse.com/ | sh
```

**Comment by yej2021** [comment]
> Installing new version fixes the problem:
> 
> ```
> curl https://clickhouse.com/ | sh
> ```

Due to various complex reasons, our current production environment cannot be upgraded or installed with a new version. We need to solve the crash problem of this instance on the ClickHouse 21.3.4.25-lts version. We hope to find the root cause of the problem and patch this version to solve this problem.

Do you know the exact reason or in which version this problem is fixed?

**Comment by helifu** [comment]
As @den-crane said above, capture the query according to the **query_id** and then reproduce in the local env. Hope it helps.

**Comment by yej2021** [comment]
> 



> @yej2021 As den-crane said above, capture the query according to the **query_id** and then reproduce in the local environment. Hope it helps.

We also created a table in the test environment and queried the SQL statement (query_id when the instance is suspended) to reproduce the problem. However, an error is reported during the query, which will not cause the database instance to crash. Are there any other ideas?
