### ISSUE TITLE
DB-wise LowCardinality dictionaries

### ISSUE THREAD

**Issue by Teeeto** [ClickHouse/ClickHouse#21239]
**Use case**
There is a database  where phone number is used as a key in many tables. Each individual table does not justify storing phone number as LowCardinality due to uniques/count ratio. However this could be justified considering all the rows from all the dozens of tables which contain the phone number.

**Describe the solution you'd like**
Utilize one string dictionary for multiple tables. 
One of the possible approaches is to add optional dictionary name in LowCardinality declaration.
Then the columns would look like Phone LowCardinality(String,'MyPhoneNumDict')

**Comment by filimonov** [comment]
Did you consider using external dictionaries for that?

**Comment by Teeeto** [comment]
Maintaining an external dictionary is extra code one needs to have at  the ETL process populating the DB. Additionally as I understand a select query would have to utilize the dictionary explicitly or a view would be required (not sure about efficiency).
Sharing a LowCardinality dictionary is much more elegant and seamless from user prospective since it is maintained and looked up automatically.

**Comment by alexey-milovidov** [comment]
It's not trivial to support global dictionary for Replicated tables since data can appear on servers in different order - it means that dictionary ids will be also selected in different way on replicas and replicated data will be not byte-identical.

**Comment by Teeeto** [comment]
It might require shipping new dictionary entries together with insert data to replicas then?
Or making dictionary itself sort of a replicated table.

**Comment by Teeeto** [comment]
So a possible flow would be.
1) Trivial. 
XXX is inserted on replica 0 and gets a key (bit) 0000.....0001 where first two bits are replica id (00)
Insert is propagated to replica  1 together with mapping XXX : 0000.....001.
All subsequent inserts to both replicas use this mapping
2) Duplicate
XXX is inserted on replica 0 and 1 simultaneously.
So synchronization of  replica 0 -> replica 1 goes with XXX:0000.....00A mapping
And replica 1 -> replica 0 goes with XXX:0100.....00B mapping

Each dictionary entry for XXX becomes a key-tuple on both replicas.
So during lookup XXX would resolve to 2 values and matching would become "belong to set" instead of "equals" for XXX

There can be a background deduplication process which would try to reduce the tuple to single value (picking the one with the lowest replica ID).

For some cases (I believe a lower percentage of them) this would introduce a tradeoff between performance and storage efficiency (if tuple matching is considerable slower than equality and deduplication is a costly process) but for most cases it would be pure storage efficiency since the case of introducing new id at the same moment on different replicas looks to be rare one in the real world.

**Comment by filimonov** [comment]
There are too many different cases there, and quite a lot of invariants would be broken. 
 
Clickhouse is the guy from big data world. 
Imagine you need to sync the dictionary between 1000 or 10000 nodes, and the dictionary size tends to grow to gigabytes. Some old data need to be cleaned, etc. Some replicas may go offline suddenly (together with their dicts) etc. 

It's not trivial, just as Alexey told. 

The feature maybe useful in some scenarios. 

Maybe we can also think about  creating  special kind of dictionary filled in a streaming manner. Like dictPut(name, String) -> id. (which can be used in insert statements)
