### ISSUE TITLE
timezone cannot be omitted when converting Date/Datetime to DateTime64

### ISSUE THREAD

**Issue by winoenix** [ClickHouse/ClickHouse#21247]
when I was trying to convert date/datetime to datetime64, I found timezone cannot be omitted when converting Date/Datetime to DateTime64.
For example:
WITH toDate('2019-09-16') AS dt　SELECT toDateTime64(dt, 6, timezone())
WITH toDateTime('2019-09-16 19:20:12') AS dt　SELECT toDateTime64(dt, 6, timezone())
can be done. But
WITH toDate('2019-09-16') AS dt　SELECT toDateTime64(dt, 6)
WITH toDateTime('2019-09-16 19:20:12') AS dt　SELECT toDateTime64(dt, 6)

raises exception:
 Illegal column Const(UInt8) of time zone argument of function, must be constant string: While processing toDateTime64(toDateTime('2019-09-16 19:20:12') AS dt, 6)

BTW, how can I get the Timezone from a Date/DateTime parameter?

Thanks.

**Comment by den-crane** [comment]
fixed long time ago

```
WITH toDateTime('2019-09-16 19:20:12') AS dt
SELECT toDateTime64(dt, 6)

Query id: 575c938a-72c8-45ef-9bda-6dba6de05bb0

┌────────toDateTime64(dt, 6)─┐
│ 2019-09-16 19:20:12.000000 │
└────────────────────────────┘

```

**Comment by den-crane** [comment]
```
SELECT toTypeName(now('Europe/Paris'))

Query id: 1a47e804-d8d8-4996-8a3f-66d2f95a89e5

┌─toTypeName(now('Europe/Paris'))─┐
│ DateTime('Europe/Paris')        │
└─────────────────────────────────┘

```
