### ISSUE TITLE
MongoDB as external dictionary

### ISSUE THREAD

**Issue by SVGitHub** [ClickHouse/ClickHouse#2125]
I have created a dictionary configuration for a simple MongoDB collection.  

Mongo Document - 
{
    "_id" : 1,
    "num" : 1234,
    "name" : "Test"
}

Please find the config below (Ignore the underscore after the tag. It was not allowing to add some tags. So I have added underscore)
<lifetime_></lifetime_>
 <layout_><hashed_/></layout_>
 <structure_>
<id_>
<name_>num</name_>
</id_>
 <attribute_>
                   <name_>name</name_>
                                <type_>String</type_>
 <null_value></null_value>
                        </attribute_>
        </structure_>

But, I am getting the below error when the dictionary is getting loaded -
<Error> ExternalDictionaries: Cannot create external dictionary 'TempClickHouse' from config path /etc/clickhouse-server/dictionary.xml: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = Syntax error: Not a valid unsigned integer, e.what() = Syntax error

There is no mention of which field it is referring to. No description of the error. How can I identify what has to be changed?

Actually the error was in the lifetime tag. I hadnt mentioned the 'min' and 'max' tag.

The description in the error should be appropriate and this applies to any other tag or configuration

**Comment by Jaxvk** [comment]
set `null_value`  0
```
<null_value>0</null_value>
```
