### ISSUE TITLE
Why the decimal  incorrect?

### ISSUE THREAD

**Issue by vegastar002** [ClickHouse/ClickHouse#21269]
localhost :) select round( (1027-949) /949,4)  *   100;

┌─multiply(round(divide(minus(1027, 949), 949), 4), 100)─┐
│                                      8.219999999999999 │
└──────────────────────────────────

localhost :) select round( (1027-949) /949,4)  *  1;

┌─multiply(round(divide(minus(1027, 949), 949), 4), 1)─┐
│                                               0.0822 │
└──────────────────────────────────────────────────────┘

version: 20.11

why not show the correct result :
8.22 ??

**Comment by hohaftf** [comment]
It is float data type. And it's OK because the size of structure in memory is limited.
see https://en.wikipedia.org/wiki/Floating-point_arithmetic#Accuracy_problems

**Comment by alexey-milovidov** [comment]
You have to explicitly cast to Decimal:

`SELECT round(CAST(1027 - 949, 'Decimal(10, 5)') / CAST(949, 'Decimal(10, 5)'), 4) * 100`
