### ISSUE TITLE
Old MySQL, missing column `DATETIME_PRECISION` in INFORMATION_SCHEMA

### ISSUE THREAD

**Issue by anonymous-shy** [ClickHouse/ClickHouse#21335]
Hi, all:
Clickhouse Version:ClickHouse client version 21.2.4.6 (official build).
MySQL. Version:Server version: 5.6.35 MySQL Community Server - GPL
Action:
create database on Clickhouse with MySQL Engine.
create DATABASE Tab1　ENGINE = MySQL('Ip:Host', 'DB', 'user', 'passwd');
Error:
Received exception from server (version 21.2.4):
Code: 501. DB::Exception: Received from bjxg-bd-slave67:19000. DB::Exception: Cannot create MySQL database, because Poco::Exception. Code: 1000, e.code() = 1054, e.displayText() = mysqlxx::BadQuery: Unknown column 'DATETIME_PRECISION' in 'field list' 
How can I fix it?

**Comment by windylcx** [comment]
i met the  same problem

**Comment by zhenruyan** [comment]
i met the same problem

+1。mysql 5.5

**Comment by zongyaoou** [comment]
+1

**Comment by alexey-milovidov** [comment]
![Screenshot_20221020_003643](https://user-images.githubusercontent.com/18581488/196817577-aa17c377-9df8-4be0-888d-842dd6486974.png)

**Comment by qoega** [comment]
As a workaround people propose to disable feature by setting `DisableDatetimePrecision` in mysql config.
https://github.com/go-gorm/mysql/issues/13#issuecomment-717282983
