### ISSUE TITLE
I am facing issue while using the same database name even after dropping the database from CH and clearing ZK path. 

### ISSUE THREAD

**Issue by DipalPrajapati** [ClickHouse/ClickHouse#21332]
Hello there , 
I am facing issue while using the same database name even after dropping the database from CH and clearing ZK path. 

PFA logs. 
`2021.03.01 08:25:05.747578 [ 27626 ] {} <Error> h1_dma.dmaRawDumpLocal (c3e02226-4bcc-43d6-a7c5-e3e0755876d5): void DB::StorageReplicatedMergeTree::queueUpdatingTask(): Code: 999, e.displayText() = Coordination::Exception: Can't get data for node /clickhouse/two_shards_distributed_replicated/h1_dma/table/dmaRawDumpLocal/01/replicas/01/log_pointer: node doesn't exist (No node), Stack trace (when copying this message, always include the lines below):

0. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error, int) @ 0xe9d7e93 in /usr/bin/clickhouse
1. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error) @ 0xe9d8112 in /usr/bin/clickhouse
2. zkutil::ZooKeeper::get(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Stat*, std::__1::shared_ptr<Poco::Event> const&) @ 0xe9de5d2 in /usr/bin/clickhouse
3. DB::ReplicatedMergeTreeQueue::pullLogsToQueue(std::__1::shared_ptr<zkutil::ZooKeeper>, std::__1::function<void (Coordination::WatchResponse const&)>) @ 0xe644b78 in /usr/bin/clickhouse
4. DB::StorageReplicatedMergeTree::queueUpdatingTask() @ 0xe312111 in /usr/bin/clickhouse
5. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0xda48492 in /usr/bin/clickhouse
6. DB::BackgroundSchedulePool::threadFunction() @ 0xda4a8c2 in /usr/bin/clickhouse
7. ? @ 0xda4bb41 in /usr/bin/clickhouse
8. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x7dc5b3d in /usr/bin/clickhouse
9. ? @ 0x7dc96f3 in /usr/bin/clickhouse
10. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
11. clone @ 0xfe9fd in /usr/lib64/libc-2.17.so
 (version 20.12.5.14 (official build))`

Can anybody helps ? basically I drop database and delete ZK path by following commands.

`DROP DATABASE h1_dma ON CLUSTER replicated`
` deleteall /clickhouse/replicated/h1_dma
deleteall /clickhouse/two_shards_distributed_replicated/h1_dma`
I have 2 clusters.

**Comment by den-crane** [comment]
Database Atomic?

https://github.com/ClickHouse/ClickHouse/issues/12135

**Comment by DipalPrajapati** [comment]
Yes thank you I found it. You can close it. I keep 10 minutes wait in between delete  and create the same DB , or i can change  the property database_atomic_delay_before_drop_table_sec to 0 right?

**Comment by den-crane** [comment]
yes, right
