### ISSUE TITLE
 CheckSortedBlockInputStream unit tests failing

### ISSUE THREAD

**Issue by stigsb** [ClickHouse/ClickHouse#21349]
**Describe the bug**
`src/unit_tests_dbms` fails in master

**Does it reproduce on recent release?**
At least 21.2 branch and master.

**How to reproduce**
Compile master with -DENABLE_TESTS=ON

```
./src/unit_tests_dbms --gtest_filter==CheckSortedBlockInputStream.CheckBadLastRow
```

**Expected behavior**
Tests passing

**Error message and/or stacktrace**
```
 $ ./src/unit_tests_dbms --gtest_filter=CheckSortedBlockInputStream.CheckBadLastRow
Running main() from ../contrib/googletest/googletest/src/gtest_main.cc
Note: Google Test filter = CheckSortedBlockInputStream.CheckBadLastRow
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from CheckSortedBlockInputStream
[ RUN      ] CheckSortedBlockInputStream.CheckBadLastRow
Aborted
```

**Additional context**

cmake command:

```
cmake .. \
    -DCMAKE_C_COMPILER=/usr/bin/gcc-10 \
    -DCMAKE_CXX_COMPILER=/usr/bin/g++-10 \
    -DCMAKE_BUILD_TYPE=Debug \
    -DENABLE_CLICKHOUSE_ALL=OFF \
    -DENABLE_CLICKHOUSE_SERVER=ON \
    -DENABLE_CLICKHOUSE_CLIENT=ON \
    -DUSE_STATIC_LIBRARIES=OFF \
    -DSPLIT_SHARED_LIBRARIES=ON \
    -DUSE_UNWIND=ON \
    -DENABLE_UTILS=OFF \
    -DENABLE_LIBRARIES=OFF \
    -DENABLE_MYSQL=ON
```

It happens on every test in `src/DataStreams/tests/gtest_check_sorted_stream.cpp` that uses `EXPECT_THROW`, possible more.

**Comment by alexey-milovidov** [comment]
We ensure that it does not fail in our CI:
![Screenshot_20210301_200627](https://user-images.githubusercontent.com/18581488/109532004-aa5a6c80-7ac9-11eb-9905-1d1c30aba421.png)

**Comment by alexey-milovidov** [comment]
Maybe you are using modified source code? Or do you run tests on non x86_64 Linux?

**Comment by stigsb** [comment]
This was built on x86_64 Ubuntu 20.04 with a fresh master checkout. I'll try with a fresh clone and nuked ccache.
