### ISSUE TITLE
Clickhouse block sizes for dictionaries

### ISSUE THREAD

**Issue by MaxJPowers** [ClickHouse/ClickHouse#21348]
In `system.dictionaries` there's a row called `hit-rate` which for cache dictionaries is recommended to be higher than 99%. However when I load a 10th of a dictionary into the cache, I still get 99%+ hit rate even thought I'm randomly taking values from the dictionary. This leads me to believe its the average of the ratio of the blocks that have been hit/cached not the individual rows. If so is there a way of seeing the block size so I can optimise the number of cached entries accordingly.

**Comment by kitaisreal** [comment]
Hello, @MaxJPowers, could you please provide some example. Hit rate is calculated for rows in cache dictionaries.

**Comment by kitaisreal** [comment]
Answered in scope of https://github.com/ClickHouse/ClickHouse/issues/22239.
