### ISSUE TITLE
Broken links to presentations.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#21356]
**Describe the bug**
The links like https://clickhouse.tech/presentations/yatalks_2019 stopped to work.

We should fix these links and ensure that it will never happen again. CC @blinkov

**Comment by alexey-milovidov** [comment]
https://support.cloudflare.com/hc/en-us/articles/200172286-Configuring-URL-forwarding-or-redirects-with-Cloudflare-Page-Rules

Let's try:
![Screenshot_20210301_210905](https://user-images.githubusercontent.com/18581488/109539555-7fc0e180-7ad2-11eb-84a5-6c90c4ee0b9d.png)

**Comment by alexey-milovidov** [comment]
The new rule does not work either.

**Comment by alexey-milovidov** [comment]
It because of "workers" (Run JavaScript on the edge) being configured.
Need to untangle it...

**Comment by blinkov** [comment]
As far as I remember they have always been on a separate subdomain like https://presentations.clickhouse.tech/yatalks_2019/ and it's still working

**Comment by alexey-milovidov** [comment]
@blinkov What you say is simply untrue.

**Comment by alexey-milovidov** [comment]
I'm trying to fix Website workers right now.

**Comment by alexey-milovidov** [comment]
People complained that the link on https://www.youtube.com/watch?v=ltg8vstuHUU does not work.

**Comment by alexey-milovidov** [comment]
I've fixed it.
