### ISSUE TITLE
Int128 max/min misbehavior

### ISSUE THREAD

**Issue by smagellan** [ClickHouse/ClickHouse#21384]
(you don't have to strictly follow this form)

**Describe the unexpected behaviour**
A clear and concise description of what works not as it is supposed to.

**How to reproduce**
* Which ClickHouse server version to use: 21.2.5 revision 54447
* Which interface to use, if matters: clickhouse-client 21.2.5.5 (official build)
* Queries to run that lead to unexpected result: SELECT CAST(-170141183460469231731687303715884105728, 'Int128') as min_val, CAST(170141183460469231731687303715884105727, 'Int128') as max_val;
* Queries to run that lead to unexpected result: SELECT CAST('-170141183460469231731687303715884105728', 'Nullable(Int128)') as min_val, CAST('170141183460469231731687303715884105727', 'Nullable(Int128)') as max_val;

**Expected behavior**
First query gives min_val = -170141183460469231731687303715884105728, max_val = -170141183460469231731687303715884105728 (-170141183460469231731687303715884105728 and 170141183460469231731687303715884105727 expected). (Compare with this (sane) query: SELECT CAST('-170141183460469231731687303715884105728', 'Int128') as min_val, CAST('170141183460469231731687303715884105727', 'Int128') as max_val;)
Second query(with Nullable(Int128)) ) gives min_val = NULL and max_val = 170141183460469231731687303715884105727 (-170141183460469231731687303715884105728 and 170141183460469231731687303715884105727 expected)

**Comment by alexey-milovidov** [comment]
In the first query numbers are parsed as Float64 before being casted to Int128.
The right way is to put it in quotes as in the second query.

We will check what's wrong with the second query.

PS. Big integers is experimental feature (in development).

**Comment by smagellan** [comment]
Thank you!
