### ISSUE TITLE
SELECT asterisk behaviour

### ISSUE THREAD

**Issue by mzealey** [ClickHouse/ClickHouse#21386]
In postgres and many other databases, with tables `t1(a,b)` and `t2(y,z)`, `select * from t1, t2` or `select t1.*, t2.* from t1, t2` would produce results `(a,b,y,z)`. `select t1.*, y from t1,t2` would produce results `(a,b,y)`. In clickhouse currently there is only the option of `select * from t1,t2` which produces `(t1.a,t1.b,t2.y,t2.z)`, or `select a,b,y,z from t1,t2` which produces `(a,b,y,z)` but is really bad to type if you have lots of columns in tables. (I know you shouldn't really do this from normal tables, but in the case where you have a number of CTEs that you want to join together in the final statement it is really userful). For some design reason that I don't really understand, in clickhouse `select t1.*` only works if you have 1 column it won't allow you to select 2 of them.

So I'd really like it if `select t1.*, t2.* from t1,t2` produce column name output of `(a,b,y,z)` (ie without the table names prefixed, because they have been explicitly selected by the user from the tables, and allowing asterisk expansion in similarity with other SQL dialects.

**Comment by UnamedRus** [comment]
```
22.6

SELECT
    t1.*,
    c
FROM
(
    SELECT
        1 AS a,
        2 AS b
) AS t1,
(
    SELECT
        3 AS c,
        4 AS d
) AS t2

Query id: 10104ae2-0374-42d7-b351-bf6fdfac3476

┌─a─┬─b─┬─c─┐
│ 1 │ 2 │ 3 │
└───┴───┴───┘

SELECT
    t1.*,
    t2.*
FROM
(
    SELECT
        1 AS a,
        2 AS b
) AS t1,
(
    SELECT
        3 AS c,
        4 AS d
) AS t2

Query id: c40301e4-7779-4180-9b70-78c34f78c595

┌─a─┬─b─┬─c─┬─d─┐
│ 1 │ 2 │ 3 │ 4 │
└───┴───┴───┴───┘
```

**Comment by mzealey** [comment]
nice
