### ISSUE TITLE
If the replica is not a leader, I can not find the code that the follower send optimize operation to the leader！

### ISSUE THREAD

**Issue by Sallery-X** [ClickHouse/ClickHouse#21395]
`bool StorageReplicatedMergeTree::optimize(
    const ASTPtr &,
    const StorageMetadataPtr &,
    const ASTPtr & partition,
    bool final,
    bool deduplicate,
    const Context & query_context)
{
    assertNotReadonly();

    if (!is_leader)
        throw Exception("OPTIMIZE cannot be done on this replica because it is not a leader", ErrorCodes::NOT_A_LEADER);`

**Comment by filimonov** [comment]
Why do you thing you need it? Since 20.5 all replicas are leaders (unless you explicitly forbid them to be a leader)

**Comment by Sallery-X** [comment]
> Why do you think you need it? Since 20.5 all replicas are leaders (unless you explicitly forbid them to be a leader).
> 
> If you're using an older version there was a code for that (but it was quite fragile)

If  all replicas are leaders，every replica could excute merge plan,  the parts that will be merged maybe conflict, such as the replica merge part_1_1_0  part_2_2_0 to part_1_2_1, but another merge part 1_1_0、part_2_2_0 and part_3_3_0 to part_1_3_1

**Comment by filimonov** [comment]
> conflict

Everything will be ok. See: https://github.com/ClickHouse/ClickHouse/pull/11637

You can explain it like that: leader now do an attempt to put the merge task in the queue. If in meanwhile queue changed he will remove the task, will reread the queue, and will do another attempt with respect to the changed queue state.

**Comment by Sallery-X** [comment]
> > conflict
> 
> Everything will be ok. See: #11637
> 
> You can explain it like that: leader now do an attempt to put the merge task in the queue. If in meanwhile queue changed he will remove the task, will reread the queue, and will do another attempt with respect to the changed queue state.

the code follows should be remove？ 
 if (!is_leader)
        return;

**Comment by filimonov** [comment]
> if (!is_leader) return;

It can happen if you use special setting which forbids for some replicas to be leaders.

**Comment by Sallery-X** [comment]
> > if (!is_leader) return;
> 
> It can happen if you use special setting which forbids for some replicas to be leaders.

But I check the zookeeper log found that almost only one replica put the merge task! my cluster is 1 shard 15 replicas
