### ISSUE TITLE
Use spring boot +clickhouse to query big data

### ISSUE THREAD

**Issue by 279zlj** [ClickHouse/ClickHouse#21404]
Spring boot query clickhouse returns a large amount of data and appears oom, but the flow query of mybatis does not return results, or do I have to paging? Is there a good solution

**Comment by smagellan** [comment]
max_block_size option maybe + take a look at jdbc driver docs: https://github.com/ClickHouse/clickhouse-jdbc. I know nothing about  mybatis, though

**Comment by den-crane** [comment]
OOM in JAVA on in Clickhouse-server?

**Comment by alexey-milovidov** [comment]
It is the issue of your application, not of ClickHouse.
