### ISSUE TITLE
The clickhouse server is powered off, causing the clickhouse service process to start, and port 8123 and port 9000 are absent

### ISSUE THREAD

**Issue by mjh568412187** [ClickHouse/ClickHouse#21402]
Make sure to check documentation https://clickhouse.yandex/docs/en/ first. If the question is concise and probably has a short answer, asking it in Telegram chat https://telegram.me/clickhouse_en is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

If you still prefer GitHub issues, remove all this text and ask your question here.

----------
Hello everyone
The version of clickhouse is: clickhouse-server-19.13.2.19-1.el7.x86_64

There was a production accident
Description of the accident:
Due to the server, the clickhouse server was restarted
After restarting, the clickhouse service starts normally, but the port cannot be started, that is, the port 8123 9000 is missing.
The clickhouse-server background log is refreshed as follows:
'''''
2021.02.23 21:04:34.743534 [ 46 ] {} <Error> default.just_test_on_cluster (ReplicatedMergeTreeRestartingThread): Couldn't
 start replication: Replica /clickhouse/ycdata_1shards_3replicas/default/just_test/shared01/replicas/yhyc-clickhouse-05 a
ppears to be already active. If you're sure it's not, try again in a minute or remove znode /clickhouse/ycdata_1shards_3r
eplicas/default/just_test/shared01/replicas/yhyc-clickhouse-05/is_active manually, DB::Exception: Replica /clickhouse/ycd
ata_1shards_3replicas/default/just_test/shared01/replicas/yhyc-clickhouse-05 appears to be already active. If you're sure
 it's not, try again in a minute or remove znode /clickhouse/ycdata_1shards_3replicas/default/just_test/shared01/replicas
/yhyc-clickhouse-05/is_active manually, stack trace:
0. clickhouse-server(StackTrace::StackTrace()+0x30) [0x6f28600]
1. clickhouse-server(DB::Exception::Exception(std::string const&, int)+0x1f) [0x316365f]
2. clickhouse-server(DB::ReplicatedMergeTreeRestartingThread::activateReplica()+0x8f1) [0x613e951]
3. clickhouse-server(DB::ReplicatedMergeTreeRestartingThread::tryStartup()+0x24) [0x613ead4]
4. clickhouse-server(DB::ReplicatedMergeTreeRestartingThread::run()+0x768) [0x613fc08]
5. clickhouse-server(DB::BackgroundSchedulePoolTaskInfo::execute()+0xd8) [0x633a108]
6. clickhouse-server(DB::BackgroundSchedulePool::threadFunction()+0xaa) [0x633ab5a]
7. clickhouse-server() [0x633ad04]
8. clickhouse-server(ThreadPoolImpl<std::thread>::worker(std::_List_iterator<std::thread>)+0x1b8) [0x3191a08]
9. clickhouse-server() [0x76cb73f]
10. /lib64/libpthread.so.0(+0x7dd5) [0x7f08fa6f5dd5]
11. /lib64/libc.so.6(clone+0x6d) [0x7f08fa11cead]

---
3_32119_32119_0 to ignored_20210223_32119_32119_0
2021.02.23 20:44:55.390726 [ 77 ] {} <Error> local_ods.ods_order_db__t_trade_order_item: Renaming unexpected part 2021022
3_32121_32121_0 to ignored_20210223_32121_32121_0
2021.02.23 20:44:55.390777 [ 77 ] {} <Error> local_ods.ods_order_db__t_trade_order_item: Renaming unexpected part 2021022
3_32122_32122_0 to ignored_20210223_32122_32122_0
2021.02.23 20:44:55.390854 [ 77 ] {} <Error> local_ods.ods_order_db__t_trade_order_item: Renaming unexpected part 2021022
3_32123_32123_0 to ignored_20210223_32123_32123_0
2021.02.23 20:44:55.390914 [ 77 ] {} <Error> local_ods.ods_order_db__t_trade_order_item: Renaming unexpected part 2021022
3_32124_32124_0 to ignored_20210223_32124_32124_0
2021.02.23 20:44:55.390963 [ 77 ] {} <Error> local_ods.ods_order_db__t_trade_order_item: Renaming unexpected part 2021022
3_32126_32126_0 to ignored_20210223_32126_32126_0
2021.02.23 20:44:55.391015 [ 77 ] {} <Error> local_ods.ods_order_db__t_trade_order_item: Renaming unexpected part 2021022
3_32127_32127_0 to ignored_20210223_32127_32127_0
2021.02.23 20:44:55.391075 [ 77 ] {} <Error> local_ods.ods_order_db__t_trade_order_item: Renaming unexpected part 2021022
3_32128_32128_0 to ignored_20210223_32128_32128_0
2021.02.23 20:44:55.391152 [ 77 ] {} <Error> local_ods.ods_order_db__t_trade_order_item: Renaming unexpected part 2021022
3_32129_32129_0 to ignored_20210223_32129_32129_0
2021.02.23 20:44:55.391214 [ 77 ] {} <Error> local_ods.ods_order_db__t_trade_order_item: Renaming unexpected part 2021022
3_32131_32131_0 to ignored_20210223_32131_32131_0
2021.02.23 20:44:55.391285 [ 77 ] {} <Error> local_ods.ods_order_db__t_trade_order_item: Renaming unexpected part 2021022
3_32132_32132_0 to ignored_20210223_32132_32132_0
2021.02.23 20:44:55.391337 [ 77 ] {} <Error> local_ods.ods_order_db__t_trade_order_item: Renaming unexpected part 2021022
3_32133_32133_0 to ignored_20210223_32133_32133_0
2021.02.23 20:44:55.391390 [ 77 ] {} <Error> local_ods.ods_order_db__t_trade_order_item: Renaming unexpected part 2021022
3_32134_32134_0 to ignored_20210223_32134_32134_0

2021.02.23 20:44:55.388079 [ 77 ] {} <Error> local_ods.ods_order_db__t_trade_order_item: Renaming unexpected part 2021022
3_32080_32100_4 to ignored_20210223_32080_32100_4
2021.02.23 20:44:55.388142 [ 77 ] {} <Error> local_ods.ods_order_db__t_trade_order_item: The set of parts restored in pla
ce of 20210223_32080_32100_4 looks incomplete. There might or might not be a data loss. Suspicious parts: 20210223_31024_
32079_262 (state Committed)
2021.02.23 20:44:55.388158 [ 77 ] {} <Error> local_ods.ods_order_db__t_trade_order_item: Renaming unexpected part 2021022
3_32080_32105_5 to ignored_20210223_32080_32105_5
2021.02.23 20:44:55.388226 [ 77 ] {} <Error> local_ods.ods_order_db__t_trade_order_item: The set of parts restored in pla
ce of 20210223_32080_32105_5 looks incomplete. There might or might not be a data loss. Suspicious parts: 20210223_31024_
32079_262 (state Committed)
2021.02.23 20:44:55.388241 [ 77 ] {} <Error> local_ods.ods_order_db__t_trade_order_item: Renaming unexpected part 2021022
3_32080_32110
""""""

At that time, I waited for a while, and I saw that the port was not restored, and the background log was not refreshed.

guess:
At that time, the data written on clickhouse was relatively large, and data recovery may take a certain amount of time. At that time, the server was powered off and restarted. After the restart, clickhouse needs a certain process to restore data.

I don't know if you have encountered such a problem, what kind of data recovery mechanism of clickhouse looks like, please be confused.

**Comment by den-crane** [comment]
>local_ods.ods_order_db__t_trade_order_item: Renaming unexpected part  .... to ignored_....

This is normal behavior.

>The set of parts restored in place of  ... looks incomplete. There might or might not be a data loss. Suspicious parts

This is data loss because of power outage (linux cache was not written to disk).

> please be confused.

Yeah, we are.


>The clickhouse server is powered off, causing the clickhouse 
>service process to start, and port 8123 and port 9000 are absent

Clickhouse may start for very long time. Start time depends on a number of parts in your tables.

Please provide: `select count() from system.parts`.

**Comment by alexey-milovidov** [comment]
> The set of parts restored in place of ... looks incomplete. There might or might not be a data loss. Suspicious parts
This is data loss because of power outage (linux cache was not written to disk).

If you have replicas unaffected by power outage, the missing data parts will be restored from them.

**Comment by mjh568412187** [comment]
hello

yhyc-clickhouse-05 :) select count(*) from system.parts;

SELECT count(*)
FROM system.parts

┌─count()─┐
│   136622 │
└─────────┘

1 rows in set. Elapsed: 4.690 sec. Processed 68.31 thousand rows, 35.01 MB (14.57 thousand rows/s., 7.47 MB/s.)

At that time, the log of clickhouse-server.log_bak20210223 reported the renaming situation

[root@yhyc-clickhouse-05 clickhouse-server]# cat clickhouse-server.log_bak20210223 | grep "2021.02.23" | grep "Renaming" |wc -l
245

However, Houyang’s log is not refreshed anymore

If the number of partitions is 136622, how long does it take to recover from a power failure based on your experience?

Is it because I just have to wait for enough time, the clickhouse service will automatically restore the data

**Comment by mjh568412187** [comment]
> > The set of parts restored in place of ... looks incomplete. There might or might not be a data loss. Suspicious parts
> > This is data loss because of power outage (linux cache was not written to disk).
> 
> If you have replicas unaffected by power outage, the missing data parts will be restored from them.

Hello there,
Glad your answers and insights

After waiting for a period of time, the port of clickhouse was not restored, and the data was not restored. I also used ReplicatedMergeTree to restore data from other servers.

**Comment by withTheHidden** [comment]
> > local_ods.ods_order_db__t_trade_order_item: Renaming unexpected part  .... to ignored_....
> 
> This is normal behavior.
> 
> > The set of parts restored in place of  ... looks incomplete. There might or might not be a data loss. Suspicious parts
> 
> This is data loss because of power outage (linux cache was not written to disk).
> 
> > please be confused.
> 
> Yeah, we are.
> 
> > The clickhouse server is powered off, causing the clickhouse
> > service process to start, and port 8123 and port 9000 are absent
> 
> Clickhouse may start for very long time. Start time depends on a number of parts in your tables.
> 
> Please provide: `select count() from system.parts`.

we meet this problem too,  clickhouse start for 2 days ,but port 8123 and port 9000 are absent always.. what should we do now ... thank~

**Comment by alexey-milovidov** [comment]
@withTheHidden You need to check server logs.
They are located at `/var/lib/clickhouse-server/clickhouse-server.log`
