### ISSUE TITLE
WITH FILL with interpolation

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#21412]
```
SELECT *
FROM values('pos UInt16, val UInt16', (1, 10), (13, 130), (15, 150), (20, 200))
ORDER BY pos ASC WITH FILL

Query id: 78385df6-a0cf-49e1-bf3b-440ae0b4c626

┌─pos─┬─val─┐
│   1 │  10 │
│   2 │   0 │
│   3 │   0 │
│   4 │   0 │
│   5 │   0 │
│   6 │   0 │
│   7 │   0 │
│   8 │   0 │
│   9 │   0 │
│  10 │   0 │
│  11 │   0 │
│  12 │   0 │
│  13 │ 130 │
│  14 │   0 │
│  15 │ 150 │
│  16 │   0 │
│  17 │   0 │
│  18 │   0 │
│  19 │   0 │
│  20 │ 200 │
└─────┴─────┘

20 rows in set. Elapsed: 0.001 sec. 
```

I want interpolated numbers instead of zeros in val column.

**Comment by amosbird** [comment]
I also need similar features. Perhaps we can provide `WITH FILL` with a lambda function with arguments: begin_value, previous_value, next_value, end_value.

**Comment by rhuddleston** [comment]
previous_value would be very helpful

**Comment by alexey-milovidov** [comment]
Filling with previous value is easy to implement.
Interpolation is not easy.

**Comment by alexey-milovidov** [comment]
It is easy to implement, but we need to figure out how to define the rules.
Especially if we want different rules for different columns, e.g. linear interpolation for numeric columns and filling with previous value for strings.

**Comment by den-crane** [comment]
implemented https://github.com/ClickHouse/ClickHouse/pull/35349 22.4
