### ISSUE TITLE
Ldap login authorization problem

### ISSUE THREAD

**Issue by e-era** [ClickHouse/ClickHouse#21443]
Clickhouse use this Verify:
dn: cn={uid},ou=People,dc=xxx,dc=com
pass: 123456

Generally search for dn according to uid, and then verify dn by pass.

Python like this(first ldap_con.search dn by uid, then ldap_con.simple_bind_s(dn, password)):

```python
def ldapVerify(uid = '', password = ''):
    APP_LDAP_URL = 'ldap://192.168.6.200:389'
    APP_LDAP_BASE_DN = 'dc=xxx,dc=com'

    ldap_con = ldap.initialize(APP_LDAP_URL)
    ldap_con.protocol_version = ldap.VERSION3
    ldap_con.set_option(ldap.OPT_REFERRALS, 0)
    ldap_con.simple_bind("", "")
    ldap_ret_id = ldap_con.search(APP_LDAP_BASE_DN, ldap.SCOPE_SUBTREE, "uid=" + uid)
    
    ret_type, ret_data = ldap_con.result(ldap_ret_id, 0)
    
    if ret_type == ldap.RES_SEARCH_ENTRY:
        dn = ret_data[0][0]
        mail = ret_data[0][1]['mail']
        realname = dn.split(',')[0].split('=')[1].replace(' ','')
    
        try:
            res = ldap_con.simple_bind_s(dn, password)
            return(True, realname, mail)
        except Exception as e:
            logging.error(uid+' '+str(e))
            return(False, realname, mail)
    else:
        return(None, None, None)
```

**Comment by traceon** [comment]
Not sure, I understand what's the problem, and what is you trying to achieve.

**Comment by e-era** [comment]
![image](https://user-images.githubusercontent.com/10257435/110058358-29d38e80-7d9d-11eb-8980-f48d597a42f5.png)

Thank you for your reply！I think uid and cn are different。

**Comment by traceon** [comment]
If the ClickHouse user name matched `uid` you should put it (`uid=...`) in the `bind_dn` string. Otherwise, you can put `cn=...`. Is that the problem?

**Comment by traceon** [comment]
Could you please post you LDAP config in ClickHouse here?

**Comment by e-era** [comment]
CREATE USER xxx IDENTIFIED WITH ldap_server BY 'my_ldap_server';

![image](https://user-images.githubusercontent.com/10257435/110192617-1b9f7400-7e6a-11eb-869d-b37f967cc69d.png)

![image](https://user-images.githubusercontent.com/10257435/110192558-c2374500-7e69-11eb-953e-697993cf47b5.png)

If I change uid={user_name} to cn={user_name}(Jackie Chan) login is ok，but use Jackie.Chan is not ok，i usually use gitlab、jenkins、openvpn configue ldap without this problem

**Comment by traceon** [comment]
I see. What is the user name in the ClickHouse (the `xxx` placeholder)?
ClickHouse user name will be placed in `{user_name}` so they must match for bind to succeed.
