### ISSUE TITLE
Unexpected performance difference between MySQL and ClickHouse with INNER JOIN

### ISSUE THREAD

**Issue by nflorentin** [ClickHouse/ClickHouse#21440]
Hi,

I have two tables (results and words) in both ClickHouse and MySQL:
- **results** has 2.5 billion rows
- **words** has 50 million rows

In MySQL (version 5.7, engine MyISAM):
- **results**  is partitioned by column **domain**, has no index
- **words** is in RAM memory, has a primary key **id**

In CH (version 21.1.2.15):
- **results** has **ORDER BY (domain, word_id)**, ENGINE is **MergeTree**
- **words** has **ORDER BY (id)**, ENGINE is **MergeTree**

I'm benchmarking both solutions on a specific query:
```SQL
SELECT * FROM results INNER JOIN words ON results.word_id = words.id 
WHERE results.domain = crc32('www.abc.fr') LIMIT 50000;
-- takes 0.36s in MySQL
-- takes 10.5 secondes in ClickHouse
```

I tried to put the table **words** in RAM in Clickhouse with no improvement.
Reading the doc of ClickHouse, I think I understood that the LIMIT does take effect after the join, so it seems to be the reason why CH is slow on that query.

I rewrote the query in ClickHouse like this:
```SQL
WITH 
  sub AS (SELECT * FROM results WHERE results.domain = crc32('www.abc.fr') LIMIT 50000),
  sub2 AS (SELECT * FROM words WHERE words.id IN (SELECT word_id FROM sub))　
SELECT * FROM sub INNER JOIN sub2 ON sub.word_id = sub2.id;
-- now takes 1.6s
```

I wonder if there is another angle to attack the problem. I see a 10 fold increase in performance in others queries in ClickHouse comparing with MySQL and I'm a bit disappointed that on that query (which is the more important of my application), ClickHouse seems to be 5 times slower that MySQL.

I must have missed something important.

Thanks in advance for your insights and your amazing work on CH.

**Comment by vdimir** [comment]
If it's suitable for you to store `words` in memory you can try [Join table engine](https://clickhouse.tech/docs/en/engines/table-engines/special/join/)

`CREATE TABLE words (id UInt64)  ENGINE = Join(ALL, INNER, id);`

You will be able to perform usual select queries from `words` also it will be reloaded after server restart.
But type of join fixed and other ones (`LEFT`, `FULL` etc) cannot be performed with such table.

**Comment by nflorentin** [comment]
I just tested it and the following query now runs in **50ms** ! I can't believe how fast it is!
```SQL
SELECT * FROM results
INNER JOIN words ON results.word_id = words.id 
WHERE results.domain = crc32('www.abc.fr') 
LIMIT 50000;
```

@vdimir thank you for your reactivity and for the pertinence of your answer.
