### ISSUE TITLE
Found parts with the same min block and with the same max block as the missing part

### ISSUE THREAD

**Issue by BhavyaRajSharma** [ClickHouse/ClickHouse#21451]
**Problem Statement:**
I was trying to ingest data into clickhouse and getting following warning

```
_1. Hoping that it will eventually appear as a result of a merge.
2021.03.04 15:29:14.323625 [ 28764 ] {} <Warning> dbpolaris1.visit_local (ReplicatedMergeTreePartCheckThread): Checking part 20180922_70_75_1
2021.03.04 15:29:14.323956 [ 28764 ] {} <Warning> dbpolaris1.visit_local (ReplicatedMergeTreePartCheckThread): Checking if anyone has a part covering 20180922_70_75_1.
2021.03.04 15:29:14.324997 [ 28764 ] {} <Warning> dbpolaris1.visit_local (ReplicatedMergeTreePartCheckThread): Found parts with the same min block and with the same max block as the missing part 20180922_70_75_1. Hoping that it will eventually appear as a result of a merge.

```

		
**VISIT CREATE COMMAND:**

> 		CREATE TABLE dbpolaris1.visit
> 		(
> 			`imsi` Int64 CODEC(Delta(8), Default),
> 			`msisdn` Nullable(String),
> 			`imei` Nullable(String),
> 			`visitstartdate` DateTime CODEC(Delta(4), Default),
> 			`visitenddate` DateTime CODEC(Delta(4), Default),
> 			`spid` Int64 CODEC(T64, Default),
> 			`ver` DateTime CODEC(Delta(4), Default)
> 		)
> 		ENGINE = Distributed('API', '', 'visit_local', imsi % 2)
> 

**VISIT_LOCAL CREATE COMMAND:**

> 		CREATE TABLE dbpolaris1.visit_local
> 		(
> 			`imsi` Int64 CODEC(Delta(8), Default),
> 			`msisdn` Nullable(String),
> 			`imei` Nullable(String),
> 			`visitstartdate` DateTime CODEC(Delta(4), Default),
> 			`visitenddate` DateTime CODEC(Delta(4), Default),
> 			`spid` Int64 CODEC(T64, Default),
> 			`ver` DateTime CODEC(Delta(4), Default),
> 			INDEX imsi_index1 imsi TYPE minmax GRANULARITY 3,
> 			INDEX visitstartdate_index2 visitstartdate TYPE minmax GRANULARITY 1,
> 			INDEX visitenddate_index3 visitenddate TYPE minmax GRANULARITY 1,
> 			INDEX spid_index4 spid TYPE minmax GRANULARITY 1
> 		)
> 		ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{shard1}/visit', '{replica1}', ver)
> 		PARTITION BY toYYYYMMDD(visitstartdate)
> 		ORDER BY (imsi, visitstartdate)
> 

**API CLUSTER:**

```
<API>
            <shard>
            <internal_replication>true</internal_replication>
                    <replica>
                            <default_database>dbpolaris1</default_database>
                            <host>10.49.3.109</host>
                            <port>9100</port>
                    </replica>
                    <replica>
                            <default_database>dbpolaris1</default_database>
                            <host>10.49.3.111</host>
                            <port>9100</port>
                    </replica>
            </shard>
    </API>
```

**ClickHouse Version Used**
ClickHouse client version 20.12.5.14 (official build).

**Comment by den-crane** [comment]
>getting following exception

What exception? 

 <Warning> -- it's not an exception.

**Comment by mezhekov** [comment]
I have a similar problem, the point is that replication does not work, it grows delay

**Comment by den-crane** [comment]
outdated
