### ISSUE TITLE
Syntax error trying to create an index

### ISSUE THREAD

**Issue by ianmaddox** [ClickHouse/ClickHouse#21460]
Here's a table I'm trying to create:
```
Syntax error: failed at position 203 (line 10, col 29):
CREATE TABLE example_table
(
    `id` UUID,
    `date_added` DateTime,
    `name` String,
    `stype` String,
    `ntype` UInt32,
    `rank` Int32,
    `description` String,
   INDEX idx1 (stype,ntype) TYPE bloom_filter GRANULARITY 4
)
ENGINE = MergeTree ()
ORDER BY rank;

Expected one of: token, ClosingRoundBracket, Comma, DEFAULT, MATERIALIZED, ALIAS, COMMENT
```
When I run this, it highlights the T in TYPE and shows the above error.

If I create the table without the index line and then alter it, I get the following:
```
Syntax error: failed at position 31:
ALTER TABLE example_table ADD INDEX idx2 (stype,ntype) TYPE bloom_filter GRANULARITY 4 AFTER description;

Expected COLUMN
```
It complains that it expects COLUMN instead of INDEX.

As a side note, I get a similar error about bad syntax when I attempt to delete a index as well.

*Versions in use*
ClickHouse client version 18.16.1.
ClickHouse server version 21.2.5 revision 54447.
Running official docker container version

* Which interface to use, if matters
CLI

**Expected behavior**
Indexes are created either during create or alter operations.

**Comment by den-crane** [comment]
>ClickHouse client version 18.16.1.

Client parses SQL. 18.16 does not support skip indexes.
You should upgrade ClickHouse client to 21.2.5
