### ISSUE TITLE
> > if (!is_leader) return;

### ISSUE THREAD

**Issue by Sallery-X** [ClickHouse/ClickHouse#21462]
> > if (!is_leader) return;
> 
> It can happen if you use special setting which forbids for some replicas to be leaders.

But I check the zookeeper log found that almost only one replica put the merge task! my cluster is 1 shard 15 replicas

_Originally posted by @Sallery-X in https://github.com/ClickHouse/ClickHouse/issues/21395#issuecomment-790256726_

**Comment by den-crane** [comment]
It because this one replica is closer to ZK / faster / more lucky. It does not matter who was the first
