### ISSUE TITLE
Cpu not to be used when process multiple insert

### ISSUE THREAD

**Issue by lcwxz1989** [ClickHouse/ClickHouse#21464]
(you don't have to strictly follow this form)

**Describe the situation**
I have a clickhouse cluseter with 4 nodes, 2 shard and 2 replica. Each of node is configured 30cpu and 30 mem
When I insert into rows to it, the latency is around 500 milli seconds to 15 seconds. And the cpu is 97% idle.

**What I want**
How to speed up insert statement

I know some optimization. Such as batch insert by sorted rows, and maybe at least 1000 rows will have better performance.
But I want to konw if there is some system configuration to speed up insert, such as max_insert_thread(this is for insert...select, so is not what I want) and so on.

** Scenario**

*DDL*

```sql
#_local table_

CREATE TABLE IF NOT EXISTS db.table_remote ON CLUSTER 'test' 
( user_id UInt32,  
company_id UInt32,  
create_at DateTime )  
ENGINE = ReplicatedMergeTree('/test/{cluster}', '{shard}-{replica}') 
PARTITION BY toYYYYMM(create_at) 
ORDER BY ( create_at, intHash32(company_id), user_id) 
SAMPLE BY intHash32(company_id) 
SETTINGS index_granularity=8192;"

#_distribute table_

CREATE TABLE IF NOT EXISTS db.table ON CLUSTER 'test' AS db.table_remote 
ENGINE = Distributed('test', db, table_remote, rand());" 
```

_insert query_

lib: github.com/ClickHouse/clickhouse-go
code:			

```go
tx, _ := connect.Begin()
stmt, _ := tx.Prepare(insertSQL)// insert into `table` which is distribute table
for i := 0; i <  1000; i++ {
    select {
        case p := <-insertChan:
            if _, err :=  stmt.Exec(p.UserID, p.CompanyID,p.CreateAt ); err != nil {
                log.Fatal(err)
            }
        case <-ticker:
            log.Infof("batch insert batch number is %s ", i)
            break
    }
}
tx.Commit()
```

**Comment by filimonov** [comment]
Maybe your bottleneck is not a cpu? And we need exact insert scenario (there are hundreds of options)

**Comment by den-crane** [comment]
Please provide table DDL.
Insert performance depends on many factors.

**Comment by lcwxz1989** [comment]
@filimonov @den-crane  hi, I have updated scenario and DDL info, thanks a lot

**Comment by lcwxz1989** [comment]
I have some confused about insert performance:
There is some suggestion In the [clickhouse doc](https://clickhouse.tech/docs/en/introduction/performance/#performance-when-inserting-data)
A: `To improve performance, you can make multiple INSERT queries in parallel, which scales linearly`. I suppose if I have scale the machine horizontal, I can query more multiple INSERT statement.
B:  `If the inserted rows are around 1 KB in size, the speed will be from 50,000 to 200,000 rows per second`. I suppose this is for one machine, and this can be 2 times if I use distribute table with two machine.
But in fact now, I have 2 machine, but I only can get insert speed as one machine.
