### ISSUE TITLE
table size increased clickhouse optimize table deduplicate take much time

### ISSUE THREAD

**Issue by sanjaypocket52** [ClickHouse/ClickHouse#21467]
Hi Team,

I am using replacemergeTree engine remove deduplication and after insertion ran following command
OPTIMIZE TABLE table name FINAL DEDUPLICATE

In start it is fast but once data is growing it is very slow. Please suggest any changes.

**Comment by sanjaypocket52** [comment]
Please suggest any solutions

**Comment by den-crane** [comment]
* You can implement deduplication in ETL (before loading into Clickhouse).
* You can query data with selects witch deduplicate data on the fly. And then run optimize once a day.

**Comment by alexey-milovidov** [comment]
Deduplication has to process and rewrite all the data in the table. It takes a time and it's inevitable.
