### ISSUE TITLE
v21.2.5.5 in arm64  start error

### ISSUE THREAD

**Issue by wuzedewuze** [ClickHouse/ClickHouse#21476]
2021.03.05 20:09:56.208451 [ 201590 ] {} <Fatal> BaseDaemon: (version 21.2.5.5, no build id) (from thread 201557) (no query) Received signal Aborted (6)
2021.03.05 20:09:56.208461 [ 201590 ] {} <Fatal> BaseDaemon: 
2021.03.05 20:09:56.208473 [ 201590 ] {} <Fatal> BaseDaemon: Stack trace: 0xfffe8b4966e0
2021.03.05 20:09:56.208497 [ 201590 ] {} <Fatal> BaseDaemon: 0. gsignal @ 0x366e0 in /usr/lib64/libc-2.28.so
2021.03.05 20:09:56.211624 [ 201588 ] {} <Trace> ZooKeeper: Initialized, hosts: 192.168.0.209:2181,192.168.0.249:2181,192.168.0.225:2181
2021.03.05 20:09:56.217448 [ 201588 ] {} <Debug> DDLWorker: Scheduling tasks
2021.03.05 20:09:56.217456 [ 201589 ] {} <Debug> DDLWorker: Cleaning queue
2021.03.05 20:09:56.217863 [ 201588 ] {} <Debug> DDLWorker: Waiting a watch
2021.03.05 20:09:56.379746 [ 201590 ] {} <Fatal> BaseDaemon: Calculated checksum of the binary: 34B52F8F7BC6DB128D516E9B3985B1CB. There is no information about the reference checksum.
2021.03.05 20:09:56.379815 [ 201590 ] {} <Information> SentryWriter: Not sending crash report
2021.03.05 20:09:57.156306 [ 201585 ] {} <Trace> SystemLog (system.crash_log): Flushing system log, 1 entries to flush
2021.03.05 20:09:57.156371 [ 201585 ] {} <Debug> SystemLog (system.crash_log): Will use existing table system.crash_log for CrashLog
2021.03.05 20:09:57.156611 [ 201585 ] {} <Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 165.84 GiB.
2021.03.05 20:09:57.157113 [ 201585 ] {} <Trace> system.crash_log (c8eac1dc-425e-4959-8a32-1fd2b301c83c): Renaming temporary part tmp_insert_all_1_1_0 to all_21_21_0.
2021.03.05 20:09:57.157204 [ 201585 ] {} <Trace> SystemLog (system.crash_log): Flushed system log
2021.03.05 20:10:03.656266 [ 201573 ] {} <Trace> SystemLog (system.metric_log): Flushing system log, 8 entries to flush
2021.03.05 20:10:03.656758 [ 201573 ] {} <Debug> SystemLog (system.metric_log): Will use existing table system.metric_log for MetricLog
2021.03.05 20:10:03.659625 [ 201573 ] {} <Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 165.84 GiB.
2021.03.05 20:10:03.662217 [ 201573 ] {} <Trace> system.metric_log (bb2e6664-3e5b-4272-9c68-59d7d2b81931): Renaming temporary part tmp_insert_202103_1_1_0 to 202103_21_21_0.
2021.03.05 20:10:03.662791 [ 201573 ] {} <Trace> SystemLog (system.metric_log): Flushed system log
2021.03.05 20:10:07.108142 [ 201556 ] {} <Fatal> Application: Child process was terminated by signal 6.

**Comment by wuzedewuze** [comment]
2021.03.05 20:09:56.139329 [ 201557 ] {} <Warning> Application: Calculated checksum of the binary: 34B52F8F7BC6DB128D516E9B3985B1CB. There is no information about the reference checksum.
2021.03.05 20:09:56.208425 [ 201590 ] {} <Fatal> BaseDaemon: ########################################
2021.03.05 20:09:56.208451 [ 201590 ] {} <Fatal> BaseDaemon: (version 21.2.5.5, no build id) (from thread 201557) (no query) Received signal Aborted (6)
2021.03.05 20:09:56.208461 [ 201590 ] {} <Fatal> BaseDaemon: 
2021.03.05 20:09:56.208473 [ 201590 ] {} <Fatal> BaseDaemon: Stack trace: 0xfffe8b4966e0
2021.03.05 20:09:56.208497 [ 201590 ] {} <Fatal> BaseDaemon: 0. gsignal @ 0x366e0 in /usr/lib64/libc-2.28.so
2021.03.05 20:09:56.379746 [ 201590 ] {} <Fatal> BaseDaemon: Calculated checksum of the binary: 34B52F8F7BC6DB128D516E9B3985B1CB. There is no information about the reference checksum.
2021.03.05 20:10:07.108142 [ 201556 ] {} <Fatal> Application: Child process was terminated by signal 6.

**Comment by filimonov** [comment]
will check it...

**Comment by filimonov** [comment]
checked latest (21.3.1.6179) - just works.

**Comment by filimonov** [comment]
Where did you get the build? 

Try that:
```
curl -O 'https://builds.clickhouse.tech/master/aarch64/clickhouse' && chmod a+x ./clickhouse 
sudo ./clickhouse install
sudo clickhouse start 
clickhouse-client 
```

**Comment by filimonov** [comment]
If it still happens on your side - try to run it in gdb

**Comment by wuzedewuze** [comment]
thanks
Maybe  I needs try to build clickhouse without libunwind     follow #20221

**Comment by mastertheknife** [comment]
> Maybe I needs try to build clickhouse without libunwind follow #20221
> I‘m not faminiar with c++ , how to build clickhouse without libunwind ?

Most likely.
You need to add -DUSE_UNWIND=OFF to cmake

**Comment by wuzedewuze** [comment]
> > Maybe I needs try to build clickhouse without libunwind follow #20221
> > I‘m not faminiar with c++ , how to build clickhouse without libunwind ?
> 
> Most likely.
> You need to add -DUSE_UNWIND=OFF to cmake
