### ISSUE TITLE
Dictionaries dictGetHierarchy, dictIsIn complex keys support

### ISSUE THREAD

**Issue by kitaisreal** [ClickHouse/ClickHouse#21471]
Currently dictionary hierarchy methods `dictGetHierarchy`, `dictIsIn ` supported only for dictionaries with simple key. But there can be use cases where this features can be necessary for complex keys, for example complex key that contains only 1 String attribute.

**Comment by alexey-milovidov** [comment]
@kitaisreal Maybe drop this feature request?

**Comment by alexey-milovidov** [comment]
Let's drop it.
