### ISSUE TITLE
This is the sql generated by tableau, clickhouse reports an error

### ISSUE THREAD

**Issue by qazqaz44944** [ClickHouse/ClickHouse#21491]
**### This is the sql generated by tableau, clickhouse reports an error**  
Code: 47, e.displayText() = DB::Exception: Unknown identifier: X_measure__0 there are columns: MEMBERID, ACTIONTIME, 'DATE', cast(ACTIONTIME, 'DATE'): While processing multiIf(cast(ACTIONTIME, 'DATE') > X_measure__0, cast(ACTIONTIME, 'DATE'), NOT (cast(ACTIONTIME, 'DATE') > X_measure__0), NULL, NULL) (version 21.2.5.5 (official build))

SELECT `FGL`.`MEMBERID` AS `MEMBERID`,
    MIN(CAST(`FGL`.`ACTIONTIME` AS DATE)) AS `X_measure__0`,
    MIN((CASE WHEN (CAST(`FGL`.`ACTIONTIME` AS DATE) > `t0`.`X_measure__0`)
        THEN CAST(`FGL`.`ACTIONTIME` AS DATE)
        WHEN NOT (CAST(`FGL`.`ACTIONTIME` AS DATE) > `t0`.`X_measure__0`) THEN NULL ELSE NULL END)) AS `X_measure__2`
  FROM `FGL`
    INNER JOIN (
    SELECT `FGL`.`MEMBERID` AS `MEMBERID`,
      MIN(CAST(`FGL`.`ACTIONTIME` AS DATE)) AS `X_measure__0`
    FROM `FGL`
    GROUP BY `MEMBERID`
  ) `t0` ON (`FGL`.`MEMBERID` = `t0`.`MEMBERID`)
  GROUP BY `MEMBERID`

**### I can modify one to run**  Can it be optimized

  SELECT `FGL`.`MEMBERID` AS `MEMBERID`,
    MIN(CAST(`FGL`.`ACTIONTIME` AS DATE)) AS `X_measure__1`,
    MIN((CASE WHEN (CAST(`FGL`.`ACTIONTIME` AS DATE) > `t0`.`X_measure__0`)
        THEN CAST(`FGL`.`ACTIONTIME` AS DATE)
        WHEN NOT (CAST(`FGL`.`ACTIONTIME` AS DATE) > `t0`.`X_measure__0`) THEN NULL ELSE NULL END)) AS `X_measure__2`
  FROM `FGL`
    INNER JOIN (
    SELECT `FGL`.`MEMBERID` AS `MEMBERID`,
      MIN(CAST(`FGL`.`ACTIONTIME` AS DATE)) AS `X_measure__0`
    FROM `FGL`
    GROUP BY `MEMBERID`
  ) `t0` ON (`FGL`.`MEMBERID` = `t0`.`MEMBERID`)
  GROUP BY `MEMBERID`

**Comment by den-crane** [comment]
Yes, this is the known issue. Tableau does not support Clickhouse SQL.
