### ISSUE TITLE
Using the bloomfilter index for big table

### ISSUE THREAD

**Issue by phamtai97** [ClickHouse/ClickHouse#21502]
I read the document: https://clickhouse.tech/docs/en/engines/table-engines/mergetree-family/mergetree/. 
I created table with schema:

```sql
CREATE TABLE test(
 `field1` Int64,
 `field2` Int32,
 `field3` String,
 `field4` String,
 `field5` String,
 `field6` Int32,
 `field7` Int64,
 `field8` String,
 `time` Int64,
 `field9` Int64,
 `field10` Int64,
 `field11` Int32,
 `field12` String,
 `field13` Int32,
 `field14` Int32,
 `field15` Int64,
 `field16` Int64,
 `field17` Int64,
 `field18` Int64,
 `field19` String,
 `field20` String,
 `field21` Int64,
 `field22` Int32,
 `field23` String,
 `field24` Int32,
 `field25` Int32,
 `field26` Int64,
 `field27` Int64,
 `field28` Int64,
 `field29` Int64,
 `field30` String,
 `field31` String,
 `date_time` DateTime64
) ENGINE =  ReplicatedMergeTree('/data/clickhouse/replicated/test_repl', 'replica_1')
PARTITION BY toYYYYMM(date_time)
ORDER BY (time, field1, field2) SETTINGS index_granularity = 8192;
```
Note: I use model 2 replicate and 3 shards by field1.

Then, I created the bloomfilter index:
```sql
ALTER TABLE test ON CLUSTER cluster_two_shards ADD INDEX index_field1 (field1) TYPE bloom_filter(0.01) GRANULARITY 4
ALTER TABLE test ON CLUSTER cluster_two_shards ADD INDEX index_field3 (field3) TYPE bloom_filter(0.01) GRANULARITY 4
ALTER TABLE test ON CLUSTER cluster_two_shards ADD INDEX index_field4 (field4) TYPE bloom_filter(0.01) GRANULARITY 4
```

I insert about 300 million rows into this table. And I perform select SQL:

```sql
select * from test where toYYYYMM(data_time) BETWEEN '202102' AND '202102' AND field1='123456789'
```

So, This SQL runs very slow: ~40s. I think that it is very fast because I use a query statement that has partition (date_time) and index key (field1) and the table sorted by field1. 

Before I do not use the index for the table, the performance is good. Or I perform SQL:
```sql
SELECT identity(123456789) from test;

-- Action Time: ~2s
```

@den-crane can help me.

**Comment by den-crane** [comment]
>toYYYYMM(data_time)

I don't see **data_time** column.
Why do you have 2 different time column  date_time  and time ?

**Comment by phamtai97** [comment]
I am sory, data_time is date_time field. Time is int64 type, date_time is
DateTime type and date_time = time/1000

Vào CN, 7 thg 3, 2021 lúc 22:21 Denny Crane <notifications@github.com> đã
viết:

**Comment by phamtai97** [comment]
I am sory, data_time is date_time field. 
Time is int64 type, date_time is
DateTime type and date_time = time/1000

**Comment by den-crane** [comment]
You don't need ' `date_time` DateTime64' column

And you can use 
```
PARTITION BY toYYYYMM(fromUnixTimestamp64Milli(time))
ORDER BY (toDate(fromUnixTimestamp64Milli(time)),  field1, field2) 
```

And remove bloom_filter skip indexes.

**Comment by phamtai97** [comment]
But, i need query field 1 or other fields such as field 3 or field 4 that is String type. Do I need to use the index for fields 3 and 4 ?

**Comment by den-crane** [comment]
Skip indexes are not inverted indexes like you used from other databases. They can make queries slower , because skip index processing is hard task and it requires a lot of CPU. 

Try different settings bloom_filter(0.01) (0.3) (0.5) GRANULARITY 4 - GRANULARITY 10.
But do not expect much. Skip indexes help in limit number of cases. 
You'd better focus on PK index because you wasted it by placing high-cardinality column time to a leading position.

**Comment by phamtai97** [comment]
> You'd better focus on PK index because you wasted it by placing high-cardinality column time to a leading position.
I do not understand your idea

**Comment by den-crane** [comment]
>ORDER BY (time, field1, field2)

This looks completely wrong for me.

The order of columns in PK and set of columns is the most important thing.
To develop the best PK need to understand the nature of the columns, and need to know the queries you are going to run.
Try `ORDER BY (field1, field2, time) ` `ORDER BY (field2, field1, time)`

**Comment by phamtai97** [comment]
Ok, I agree with your idea.

So, I have many SQL queries that use different conditions (field1, field2, field3, ....), the above SQL statement is just one of them. But, most of my queries use the `time` field. I cannot leave all of those fields as primary keys. And I use PK in three fields: time, field1, field2 to perform SQL `Select DISTINCT(field1, field2)`, because my data has duplicate records.

In your opinion, how should I create a table with large data and need to query in many different fields?

**Comment by phamtai97** [comment]
After I remove the bloom filter index, should I run analyze SQL?

**Comment by den-crane** [comment]
>But, most of my queries use the time field

Then try to use my first suggestion `ORDER BY (toDate(fromUnixTimestamp64Milli(time)),  field1, field2) `
Place time into leading position but reduce cardinality (of index column) to one day.

>I cannot leave all of those fields as primary keys.

Why?

>And I use PK in three fields: time, field1, field2 to perform SQL Select DISTINCT(field1, field2), because my data has duplicate records.

And? PrimaryKeyIndex has nothing in common with `DISTINCT(field1, field2)`.

>In your opinion, how should I create a table with large data and need to query in many different fields?

There is no silver bullet, there is no magic. 
You can only satisfy part of queries. Try to satisfy the most frequent / important queries.
Some users duplicate / triplicate all data, and create 2, 3 tables with different ORDER_BY and the same data.
Some users create additional tables to emulate inverted indexes.

>Note: date_time field is DateTime type not DateTime64 type.

I suggested to remove this excessive column, and use only time column in your queries

```
PARTITION BY toYYYYMM(fromUnixTimestamp64Milli(time))
ORDER BY (toDate(fromUnixTimestamp64Milli(time)),  field1, field2) 
```

>After I remove the bloom filter index, should I run analyze SQL?

No.

**Comment by phamtai97** [comment]
Thank you for your answer.

> but reduce cardinality (of index column) to one day.

The mean this idea?

**Comment by den-crane** [comment]
>but reduce cardinality (of index column) to one day.

In this case Clickhouse will be able to use PKindex for queries without `time = ` predicate.

**Comment by phamtai97** [comment]
Thank you for your answers.
