### ISSUE TITLE
 Bring more results of distributed table query on different machines

### ISSUE THREAD

**Issue by 15537261738** [ClickHouse/ClickHouse#21504]
query: select count(1) from tablename where event_day='2021-03-06'
The following are the query results of count(1) on different machines
cluster-1: 10494720
cluster-2:10493949 
cluster-3:10502865
Local table engine for distributed tables is ReplicatedReplacingMergeTree.
The local table is a materialized view of Kafka.
Is this structure reasonable?
I want to know the reason for this difference
thanks

**Comment by den-crane** [comment]
1. Can you show 'show create table yourReplicatedReplacingMergeTree'
2. Can you show 'select * from system.macros'
3. Can you show 'select * from system.clusters'

**Comment by 15537261738** [comment]
CREATE TABLE kafka_queue
(
    `message` String
)
ENGINE = Kafka
SETTINGS kafka_broker_list = 'kafka-1:9092,kafka-2:9092,kafka-3:9092', kafka_topic_list = 'topic', kafka_group_name = 'clickhouse', kafka_format = 'TSVRaw'


CREATE MATERIALIZED VIEW kafka_consumer TO local
AS
SELECT
    replace(replace(splitByString(' ', message)[3], 'T', ' '), '+08:00', '') AS occur_time,
    splitByString(' ', message)[8] AS user_id,
    splitByString(' ', message)[10] AS action_json,
    visitParamExtractString(splitByString(' ', message)[10], 'region') AS region,
    toDate(replace(replace(splitByString(' ', message)[3], 'T', ' '), '+08:00', '')) AS event_day
FROM kafka_queue


CREATE TABLE local
(
    `occur_time` String,
    `user_id` UInt32,
    `action_json` String,
    `region` String,
    `event_day` Date
)
ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{shard}/local', '{replica}')
PARTITION BY (region, toYYYYMMDD(event_day))
ORDER BY (occur_time, user_id, action_json)
SETTINGS index_granularity = 8192

The Kafka consumer of each machine on the cluster is the same


┌─macro───┬─substitution─────┐
│ replica │ 01               │
│ shard   │ cluster-2 │
└─────────┴──────────────────┘
┌─macro───┬─substitution─────┐
│ replica │ 01               │
│ shard   │ cluster-3 │
└─────────┴──────────────────┘
┌─macro───┬─substitution─────┐
│ replica │ 01               │
│ shard   │ cluster-4 │
└─────────┴──────────────────┘


┌─cluster──────────────────────────────────────┬─shard_num─┬─shard_weight─┬─replica_num─┬─host_name────────┬─host_address─┬─port─┬─is_local─┬─user────┬─default_database─┬─errors_count─┬─estimated_recovery_time─┐
│ xxx                                          │         1 │            1 │           1 │ cluster-2 │ 172.24.163.7 │ 9000 │        1 │ default │                  │            0 │                       0 │
│ xxx                                          │         1 │            1 │           2 │ cluster-3 │ 172.24.163.8 │ 9000 │        0 │ default │                  │            0 │                       0 │
│ xxx                                          │         2 │            1 │           1 │ cluster-3 │ 172.24.163.8 │ 9000 │        0 │ default │                  │            0 │                       0 │
│ xxx                                          │         2 │            1 │           2 │ cluster-4 │ 172.24.163.9 │ 9000 │        0 │ default │                  │            0 │                       0 │
│ xxx                                          │         3 │            1 │           1 │ cluster-4 │ 172.24.163.9 │ 9000 │        0 │ default │                  │            0 │                       0 │
│ xxx                                          │         3 │            1 │           2 │ cluster-2 │ 172.24.163.7 │ 9000 │        1 │ default │                  │            0 │                       0 │
└──────────────────────────────────────────────┴───────────┴──────────────┴─────────────┴──────────────────┴──────────────┴──────┴──────────┴─────────┴──────────────────┴──────────────┴─────────────────────────┘


In addition, I set <internal_replication>true</internal_replication>

**Comment by den-crane** [comment]
But your cluster description **remote_servers** is completely wrong.

You have one-shard one-replica at each CH node.

Here I see each server twice:
```
┌─clu─┬─shard_num─┬─shard_weight─┬─replica_num─┬─host_name────────┬─host_address─┬─port─┬─is_local─┬─user────┬─default_database─┬─errors_count─┬─estimated_recovery_time─┐
│ xxx │ 1         │ 1            │ 1           │ cluster-2        │ 172.24.163.7 │ 9000 │ 1        │ default │                  │ 0 │ 0 │
│ xxx │ 1         │ 1            │ 2           │ cluster-3        │ 172.24.163.8 │ 9000 │ 0        │ default │                  │ 0 │ 0 │
│ xxx │ 2         │ 1            │ 1           │ cluster-3        │ 172.24.163.8 │ 9000 │ 0        │ default │                  │ 0 │ 0 │
│ xxx │ 2         │ 1            │ 2           │ cluster-4        │ 172.24.163.9 │ 9000 │ 0        │ default │                  │ 0 │ 0 │
│ xxx │ 3         │ 1            │ 1           │ cluster-4        │ 172.24.163.9 │ 9000 │ 0        │ default │                  │ 0 │ 0 │
│ xxx │ 3         │ 1            │ 2           │ cluster-2        │ 172.24.163.7 │ 9000 │ 1        │ default │                  │ 0 │ 0 │
└───  ┴───────────┴──────────────┴─────────────┴──────────────────┴──────────────┴──────┴──────────┴─────────┴──────────────────┴──────────────┴─────────────────────────┘
```

**Comment by 15537261738** [comment]
In order to configure dual replicas, my cluster is configured with 3 units, two by two for redundancy. 
This is really a stupid idea.
When I modify it to a single copy, the data remains consistent.
After modifying it into a double copy, I will observe whether it can be reproduced.
Thank you very much for your answer.

**Comment by 15537261738** [comment]
In addition, I would also like to ask whether two machines that are copies of each other can consume Kafka.

**Comment by pmusa** [comment]
Yes, they can. [This doc](https://clickhouse.com/docs/en/integrations/kafka/kafka-table-engine#clusters-and-performance) explains how it works.
