### ISSUE TITLE
Date value is inconsistency between format

### ISSUE THREAD

**Issue by phamtai97** [ClickHouse/ClickHouse#21503]
I have a schema:
```sql
CREATE TABLE test(
 `field1` Int64,
 `field2` Int32,
 `field3` String,
 `field4` String,
 `field5` String,
 `field6` Int32,
 `field7` Int64,
 `field8` String,
 `time` Int64,
 `field9` Int64,
 `field10` Int64,
 `field11` Int32,
 `field12` String,
 `field13` Int32,
 `field14` Int32,
 `field15` Int64,
 `field16` Int64,
 `field17` Int64,
 `field18` Int64,
 `field19` String,
 `field20` String,
 `field21` Int64,
 `field22` Int32,
 `field23` String,
 `field24` Int32,
 `field25` Int32,
 `field26` Int64,
 `field27` Int64,
 `field28` Int64,
 `field29` Int64,
 `field30` String,
 `field31` String,
 `date_time` DateTime64
) ENGINE =  ReplicatedMergeTree('/data/clickhouse/replicated/test_repl', 'replica_1')
PARTITION BY toYYYYMM(date_time)
ORDER BY (time, field1, field2) SETTINGS index_granularity = **8192**
```
I perform SQL:

```sql
SELECT toDate(date_time), toYYYYMM(date_time), date_time FROM test
WHERE toYYYYMM(date_time) BETWEEN 202101 AND 202102
AND voucher_id=123456789;
```
The result:
| toDate      | toYYYYMM | date_time
| ----------- | ----------- | ----------- |
| 2021-02-01      | 202102       | 2021-01-31T17:00:00+00:00

I confused about this result. Why toDate and toYYYYMM different  date_time? 
I expected toDate: 2021-31-01 and toYYYYMM: 202001.

**Comment by den-crane** [comment]
This result is from JDBC application? Right?

Can you show the result of
```
select timezone(), now(), toString(now());
```

**Comment by phamtai97** [comment]
The result of your SQL:

|timezone()| now() |toString(now())|
| ----------- | ----------- | ----------- |
|Asia/Ho_Chi_Minh   | 2021-03-07T14:08:03+00:00       | 2021-03-07 21:08:03

**Comment by phamtai97** [comment]
I use lib:

```pom
<dependency>
    <groupId>ru.yandex.clickhouse</groupId>
    <artifactId>clickhouse-jdbc</artifactId>
</dependency>
```

**Comment by den-crane** [comment]
What tool do use to query data using JDBC ? DataGrip?
What timezone at you local computer ? Windows/MACos -- Asia/Ho_Chi_Minh ?

**Comment by phamtai97** [comment]
I develop aplication by Java anh use lib Clickhouse JDBC. Then, I deploy on Linux server.

**Comment by phamtai97** [comment]
I try query this SQL on superset tool on Mac PC, the result is not change.

**Comment by phamtai97** [comment]
So how the data is actually stored? Is it because lib JDBC has converted the time to the correct local time?
What SQL do I have to use to compare the date_time properly?

**Comment by den-crane** [comment]
>So how the data is actually stored? 

it depends on how you insert data.

>Is it because lib JDBC has converted the time to the correct local time?

yes. JDBC converts datetime to the local TZ. It should work OK if you run JAVA app at the server with Asia/Ho_Chi_Minh.

>What SQL do I have to use to compare the date_time properly?

WHERE date_time >= toDateTime('2021-01-01 00:00:00', 'Asia/Ho_Chi_Minh') 
       AND date_time < toDateTime('2021-01-03 00:00:00', 'Asia/Ho_Chi_Minh')

**Comment by phamtai97** [comment]
Thank you, I understanded this issue.
