### ISSUE TITLE
A signed integer is being converted to an unisigned integer in `MsgPackRowInputFormat`

### ISSUE THREAD

**Issue by anmolarora** [ClickHouse/ClickHouse#21505]
In the msgpack visitor of [`MsgPackRowInputFormat`](https://github.com/ClickHouse/ClickHouse/blob/master/src/Processors/Formats/Impl/MsgPackRowInputFormat.cpp#L53), 
`visit_positive_integer` https://github.com/ClickHouse/ClickHouse/blob/47d684a5c35410201d4dd4f63f3287bf25cdabb7/src/Processors/Formats/Impl/MsgPackRowInputFormat.cpp#L110-L114 and `visit_negative_integer `https://github.com/ClickHouse/ClickHouse/blob/47d684a5c35410201d4dd4f63f3287bf25cdabb7/src/Processors/Formats/Impl/MsgPackRowInputFormat.cpp#L116-L120 both call `insert_integer` https://github.com/ClickHouse/ClickHouse/blob/47d684a5c35410201d4dd4f63f3287bf25cdabb7/src/Processors/Formats/Impl/MsgPackRowInputFormat.cpp#L53 which takes `UInt64` - unsigned integer as the argument thereby loosing the sign of a signed integer passed to it.

Because of this `MsgPackRowInputFormat` will not parse negative integers correctly.

**Comment by Avogar** [comment]
@anmolarora can you give an example when parsing negative integer is incorrect?
Here we have a chain of casting: `Int64 -> UInt64 -> Int8/Int16/Int32/Int64/UInt8/UInt16/UInt32/UInt64` (the last cast appears in calling `insertValue` in the needed column. And such chain is valid, we don't loose sign, because we cast `UInt64` to the needed type.

**Comment by anmolarora** [comment]
@Avogar The chain `insert_integer` -> `insertValue` might make the value loose sign.
`value` (which is passed to `insert_integer`) is not being typecasted when calling `insertValue` on the appropriate column.
https://github.com/ClickHouse/ClickHouse/blob/4125a78be697abbc54638319b6e62459e7a022d2/src/Columns/ColumnVector.h#L183
Won't the above function take the value type as `UInt64` even in case of an `Int64` type column? Or am I missing something here?

**Comment by Avogar** [comment]
@anmolarora Template typename T in `insertValue(const T value) ` is template of the whole class ColumnVector, not the specific method:
https://github.com/ClickHouse/ClickHouse/blob/4125a78be697abbc54638319b6e62459e7a022d2/src/Columns/ColumnVector.h#L95-L96

In `insert_integer` we firstly cast column to the needed and then call `insertValue`, for example:
https://github.com/ClickHouse/ClickHouse/blob/47d684a5c35410201d4dd4f63f3287bf25cdabb7/src/Processors/Formats/Impl/MsgPackRowInputFormat.cpp#L92

If you look at the definition of `ColumnInt32` you can make sure that `T = Int32`:
https://github.com/ClickHouse/ClickHouse/blob/4125a78be697abbc54638319b6e62459e7a022d2/src/Columns/ColumnsNumber.h#L21
So, in case of `Int32` we will call method `void insertValue(const T value) ` with `T = Int32` and our value of type `UInt64` will be casted to `Int32`.

**Comment by anmolarora** [comment]
@Avogar Appreciate the detailed ellaboration. I understand that there's not bug.
Closing the issue.
