### ISSUE TITLE
Failed to insert data with columns

### ISSUE THREAD

**Issue by Sammion** [ClickHouse/ClickHouse#21515]
I want migrate data from a MergeTree table to a disturibute table. But I got an error here:

    Code: 20. DB::Exception: Received from localhost:9000. DB::Exception: Number of columns doesn't match.

my Clickhouse version is 21.1.2

Here is my tables' structre and sql:
```sql
 CREATE TABLE tables.PI_TRAFFIC_ALL
(
    `raw_session_id` String,
    `session_id` String,
    `ga_vstr_id` String,
    `user_login_flag` Int32,
    `new_vstr_flag` Int32,
    `pltfrm_id` Int32,
    `dvic_id` Int32,
    `sum_dt` Date
)
ENGINE = Distributed('real_3shards_1replicas', 'tables', 'CLSFD_PI_TRAFFIC', rand())
;
CREATE TABLE tables.PI_TRAFFIC_SRC
(
    `raw_session_id` String,
    `session_id` String,
    `ga_vstr_id` String,
    `user_login_flag` Int32,
    `new_vstr_flag` Int32,
    `pltfrm_id` Int32,
    `dvic_id` Int32,
    `sum_dt` Date
)
ENGINE = MergeTree
PARTITION BY sum_dt
ORDER BY sum_dt
SETTINGS index_granularity = 8192;
-- Return error DB::Exception: Number of columns doesn't match.

insert into tables.PI_TRAFFIC_ALL select 
raw_session_id,session_id,ga_vstr_id,user_login_flag,new_vstr_flag,pltfrm_id,dvic_id,sum_dt
from tables.PI_TRAFFIC_SRC;

-- But successfully with thi sql
insert into tables.PI_TRAFFIC_ALL select * from tables.PI_TRAFFIC_SRC;

```

**Comment by den-crane** [comment]
Please share the result of

```
select FQDN() h, length(g) col_num, groupArray(name) g 
from clusterAllReplicas('real_3shards_1replicas', system.columns) where table = 'PI_TRAFFIC_SRC'
group by h
```

**Comment by den-crane** [comment]
And you have different tables CLSFD_PI_TRAFFIC VS PI_TRAFFIC_SRC

```
ENGINE = Distributed('real_3shards_1replicas', 'tables', 'CLSFD_PI_TRAFFIC', rand())
;
CREATE TABLE tables.PI_TRAFFIC_SRC
```

**Comment by bakey** [comment]
I try your case on version 21.3,but it didn't  replay。May be just upgrade the clickhosue-server?

**Comment by Sammion** [comment]
> Please share the result of
> 
> ```
> select FQDN() h, length(g) col_num, groupArray(name) g 
> from clusterAllReplicas('real_3shards_1replicas', system.columns) where table = 'CLSFD_PI_TRAFFIC'
> group by h
> ```

┌─h────────────┬─col_num─┬─g──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ 0be97fd088ac │      27 │ ['raw_clsfd_session_id','clsfd_session_id','ga_vstr_id','clsfd_is_user_login_flag','clsfd_is_new_vstr_flag','clsfd_pltfrm_id','clsfd_dvic_id','clsfd_trffc_chnl_name','geo_cntry_name','geo_region_name','geo_city_name','app_id','page_type_txt','home_page_txt','clsfd_categ_ref_id','clsfd_geo_ref_id','clsfd_event_categ','clsfd_event_action','clsfd_total_event','clsfd_pv_cnt','clsfd_bnc_cnt','clsfd_vst_drtn_num','CRE_DATE','CRE_USER','upd_date','UPD_USER','clsfd_sum_dt'] │
│ 3d54764f7598 │      80 │ ['raw_clsfd_session_id','clsfd_session_id','ga_vstr_id','clsfd_is_user_login_flag','clsfd_is_new_vstr_flag','clsfd_pltfrm_id','clsfd_dvic_id','clsfd_trffc_chnl_name','geo_cntry_name','geo_region_name','geo_city_name','app_id','page_type_txt','home_page_txt','clsfd_categ_ref_id','clsfd_geo_ref_id','clsfd_event_categ','clsfd_event_action','clsfd_total_event','clsfd_pv_cnt','clsfd_bnc_cnt','clsfd_vst_drtn_num','CRE_DATE','CRE_USER','upd_date','UPD_USER','clsfd_sum_dt','raw_clsfd_session_id','clsfd_session_id','ga_vstr_id','clsfd_is_user_login_flag','clsfd_is_new_vstr_flag','clsfd_pltfrm_id','clsfd_dvic_id','clsfd_sum_dt'] │
└──────────────┴─────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

**Comment by Sammion** [comment]
Sorry, to avoid some data security issue, I remove some columns in the tables' structure. And I failed to recurring this issue.
When I try, another error happened.
Here is my testing steps:

```
3d54764f7598 :) insert into tables.PI_TRAFFIC_ALL select
:-] raw_session_id,session_id,ga_vstr_id,user_login_flag,new_vstr_flag,pltfrm_id,dvic_id,sum_dt
:-] from tables.PI_TRAFFIC_SRC;

INSERT INTO tables.PI_TRAFFIC_ALL SELECT
    raw_session_id,
    session_id,
    ga_vstr_id,
    user_login_flag,
    new_vstr_flag,
    pltfrm_id,
    dvic_id,
    sum_dt
FROM tables.PI_TRAFFIC_SRC

Query id: f54e83b5-92cc-40f2-9a29-8cc32403d1cf

**Ok.**

**0 rows in set. Elapsed: 0.018 sec. Processed 10.00 thousand rows, 1.51 MB (550.79 thousand rows/s., 83.00 MB/s.)**

3d54764f7598 :) select * from tables.PI_TRAFFIC_ALL limit 10;

SELECT *
FROM tables.PI_TRAFFIC_ALL
LIMIT 10

Query id: 56f21d32-ccc9-43eb-98cc-b2bba63e1603


Received exception from server (version 21.1.2):
Code: 279. DB::Exception: Received from localhost:9000. DB::Exception: All connection tries failed. Log:

There is no table `tables`.`CLSFD_PI_TRAFFIC` on server: 10.41.83.252:9000

: While executing Remote.

0 rows in set. Elapsed: 0.110 sec.

3d54764f7598 :) select count(*) from tables.PI_TRAFFIC_ALL

SELECT count(*)
FROM tables.PI_TRAFFIC_ALL

Query id: 1ed490e4-3b66-487d-8923-61cb636ca786


Received exception from server (version 21.1.2):
Code: 279. DB::Exception: Received from localhost:9000. DB::Exception: All connection tries failed. Log:

There is no table `tables`.`CLSFD_PI_TRAFFIC` on server: 10.41.83.252:9000

: While executing Remote.

0 rows in set. Elapsed: 0.107 sec.

3d54764f7598 :) select count(*) from tables.PI_TRAFFIC_SRC

SELECT count(*)
FROM tables.PI_TRAFFIC_SRC

Query id: 3211fcf9-15d5-48d8-875a-366c68a20e6c

┌─count()─┐
│   10000 │
└─────────┘

1 rows in set. Elapsed: 0.006 sec.

3d54764f7598 :) select count(*) from tables.PI_TRAFFIC

SELECT count(*)
FROM tables.PI_TRAFFIC

Query id: 1d0e4bb0-30ae-4aaa-ad03-c24322816c53

┌─count()─┐
│       0 │
└─────────┘

1 rows in set. Elapsed: 0.008 sec.

3d54764f7598 :) select count(*) from tables.PI_TRAFFIC_ALL

SELECT count(*)
FROM tables.PI_TRAFFIC_ALL

Query id: 5744412f-1840-4cf4-9c4b-829289a8091d


Received exception from server (version 21.1.2):
Code: 279. DB::Exception: Received from localhost:9000. DB::Exception: All connection tries failed. Log:

There is no table `tables`.`CLSFD_PI_TRAFFIC` on server: 10.41.83.252:9000

: While executing Remote.

0 rows in set. Elapsed: 0.105 sec.

```
