### ISSUE TITLE
clarification

### ISSUE THREAD

**Issue by Rebiss** [ClickHouse/ClickHouse#21528]
Hello!
We use as a log analyzer elasticsearch ․
In 1 day we have 1+ TB data log,  30+ k message/second end very slow queries(5-20 min).
To what extent will these issues be resolved if we switch to ClickHouse?
Thanks in advance!!!

**Comment by den-crane** [comment]
You should try.
Clichouse is not a full substitute for elasticsearch.  In many use-cases it is impossible to replace elasticsearch with Clickhouse.

**Comment by genzgd** [comment]
This very much depends on your use case.

At Comcast we use ClickHouse for processing several million log events per second with very fast queries.  ClickHouse has replaced Splunk and ElasticSearch for most of these logs.  However, it is definitely NOT simply a drop in replacement.  A lot of additional work has gone into building applications which transform the logs and insert them into ClickHouse tables, as well as new Grafana dashboards and other query tools.

**Comment by Rebiss** [comment]
Ok. Thanks!!
