### ISSUE TITLE
"No free connections in pool. Waiting " when using DiskS3

### ISSUE THREAD

**Issue by yiguolei** [ClickHouse/ClickHouse#21525]
(you don't have to strictly follow this form)

**Describe the bug**
Use disks3 to do star schema benchmark, the query is blocked and there are many "No free connections in pool. Waiting" in logs. 

**Does it reproduce on recent release?**
21.2.4.6 (official build).

**How to reproduce**
1. Follow the star schema bench mark guide https://clickhouse.tech/docs/en/getting-started/example-datasets/star-schema/
2. Use -s 1000 to generates 6 billion rows.
3. Execute query 1.1 
4. query will be blocked.

**Comment by ucasFL** [comment]
Related #21376.

**Comment by alexey-milovidov** [comment]
Fixed in master.
