### ISSUE TITLE
When i use the storage of replicatedReplicaingMergeTree, i found the parts haven't merge parts for too long

### ISSUE THREAD

**Issue by Sallery-X** [ClickHouse/ClickHouse#21524]

**Comment by den-crane** [comment]
Clickhouse merge scheduler does not have the goal to merge everything. 
Merge scheduler balance number of parts in a partition with an amount of resources needed to merge them and plans merges if there are free resources available. 


Merges are eventual and may never happen. It depends on the number of inserts that happened after, the number of parts in the partition, size of parts.
If the total size of input parts bigger than the maximum part size then they are never will be merged.

**Comment by Sallery-X** [comment]
> Clickhouse merge scheduler does not have the goal to merge everything.
> Merge scheduler balance number of parts in a partition with an amount of resources needed to merge them and plans merges if there are free resources available.
> 
> Merges are eventual and may never happen. It depends on the number of inserts that happened after, the number of parts in the partition, size of parts.
> If the total size of input parts bigger than the maximum part size then they are never will be merged.

But when I excute optimize table, it could be merged

**Comment by den-crane** [comment]
Clickhouse merge scheduler does not have the goal to merge everything.
