### ISSUE TITLE
MaterializeMySQL not support data type 'time'

### ISSUE THREAD

**Issue by mchcz** [ClickHouse/ClickHouse#21536]
when I create table in MySQL like below:
create table test1(a time PRIMARY key);

Code: 50. DB::Exception: Received from 172.17.6.55:9100. DB::Exception: Unknown data type family: time: While executing MYSQL_QUERY_EVENT. The query: create table test1(a time PRIMARY key). 

We need to synchronize data from Mysql to Clickhouse in real time，many field types are involved in the source DB, including data type 'time', so I wonder if this type will be supported in the future？
@zhang2014 

MySQL Version：5.7.25
Clickhouse Version：21.2.5.5

**Comment by filimonov** [comment]
https://github.com/ClickHouse/ClickHouse/issues/18091

**Comment by filimonov** [comment]
https://github.com/ClickHouse/ClickHouse/issues/14735
