### ISSUE TITLE
How to use Kafka-engine to consumer Kafka with kerbores 

### ISSUE THREAD

**Issue by Lipeng522** [ClickHouse/ClickHouse#21538]
when I use clickhouse kafka-engine, one question I have.
My company's kafka cluster have kerbores, and in the clickhouse web, no guides teach me how to setting kerbores when I use kafka-engine.

So when using kafka-engine, how to consumer kafka topic with kerbores??

**Comment by ngsiolei** [comment]
Please have a look on `Kafka / Configuration / Kerberos support` in ClickHouse docs, https://clickhouse.tech/docs/en/engines/table-engines/integrations/kafka/#kafka-kerberos-support

**Comment by Lipeng522** [comment]
OK,Thank you very much
But if I use this way, the clickhouse config will be changed, The cluster is not only for me, Maybe the owner of the cluster wouldn't like to change. is there anyone method that can be solved by set parameters when using kafka-engine. 
Thank you, waiting for your reply.

**Comment by ngsiolei** [comment]
For Kafka engine authentication, server-level settings in ClickHouse config file is the way to go now.

**Comment by Lipeng522** [comment]
OK，I know，thank you

**Comment by mjh568412187** [comment]
> For Kafka engine authentication, server-level settings in ClickHouse config file is the way to go now.

https://github.com/ClickHouse/ClickHouse/issues/23933
Thank you, waiting for your reply.
