### ISSUE TITLE
cluster work normally, but log of one node prints many error logs

### ISSUE THREAD

**Issue by victortony** [ClickHouse/ClickHouse#21545]
Hello.
I install a clickhouse cluster which have two nodes. The cluster works normally. 
1. But the log of one node prints many error; The detail of error list below. 
2. The "Address: 10.115.xxx.x:62543" is not in my cluster. Where does the ip from, why my cluster read the ip so frequently?

2021.03.09 18:00:38.897646 [ 50 ] {} <Trace> TCPHandlerFactory: TCP Request. **Address: 10.115.xxx.x:62543**
2021.03.09 18:00:38.897790 [ 50 ] {} <Error> ServerErrorHandler: Poco::Exception. Code: 1000, e.code() = 107, e.displayText() = Net Exception: Socket is not connected (version 19.16.3.6
2021.03.09 18:00:39.014314 [ 49 ] {} <Trace> TCPHandlerFactory: TCP Request. Address: **10.115.xxx.x:20469**
2021.03.09 18:00:39.015025 [ 49 ] {} <Error> ServerErrorHandler: Code: 210, e.displayText() = DB::NetException: Connection reset by peer, while reading from socket **(10.115.xxx.x:20469**), Stack trace:

0. 0x34fcf10 StackTrace::StackTrace() /usr/bin/clickhouse
1. 0x350715f DB::Exception::Exception(std::string const&, int) /usr/bin/clickhouse
2. 0x33f2658 ? /usr/bin/clickhouse
3. 0x357c52c DB::TCPHandler::runImpl() /usr/bin/clickhouse
4. 0x357cb6c DB::TCPHandler::run() /usr/bin/clickhouse
5. 0x6d4bb6f Poco::Net::TCPServerConnection::start() /usr/bin/clickhouse
6. 0x6d4c265 Poco::Net::TCPServerDispatcher::run() /usr/bin/clickhouse
7. 0x71d1771 Poco::PooledThread::run() /usr/bin/clickhouse
8. 0x71cd4f8 Poco::ThreadImpl::runnableEntry(void*) /usr/bin/clickhouse
9. 0x78ac0ff ? /usr/bin/clickhouse
10. 0x7fac442b1dc5 start_thread /usr/lib64/libpthread-2.17.so
11. 0x7fac43ddc73d __clone /usr/lib64/libc-2.17.so
 (version 19.16.3.6)

**Comment by alexey-milovidov** [comment]
It may be related to network scanners operating in your network.
