### ISSUE TITLE
Will the merging be executed regularly？

### ISSUE THREAD

**Issue by Sallery-X** [ClickHouse/ClickHouse#21541]
Clickhouse merge scheduler does not have the goal to merge everything.

_Originally posted by @den-crane in https://github.com/ClickHouse/ClickHouse/issues/21524#issuecomment-793346722_

**Comment by Sallery-X** [comment]
I think the merge operation will be excute when i  insert、alter or optimize, Besides   will the merging be executed regularly when the storage start up？And How often？

**Comment by tavplubix** [comment]
Duplicate of #21554
