### ISSUE TITLE
can't insert CSV array into Clickhouse using Apache Nifi

### ISSUE THREAD

**Issue by aol-59** [ClickHouse/ClickHouse#21552]
Hi,
I am using Apache Nifi and Clickhouse Database.
I have a table with 3 columns :
c1 Array(UInt32),
c2 Array(Float32),
c3 Array(String)

I used PutDatabaseRecord Processor to insert CSV record.
[1,2,3],[1.1,2.2,3.3],['a','b','c']

Code 26 : Exception: Cannot parse quoted string : expected opening quote At row 1 
Row 1:
column 0 : name c1 , type Array(UInt32), parsed text "[1]"
column 1 : name c2 , type Array(Float32), parsed text "[2]"
column 2 : name c3 , type Array(String), parsed text "["ERROR
Code 26 : Exception: Cannot parse quoted string : expected opening quote At row 1 

i tried to put a backslash before quotations \"[1,2,3]\" but didn't work.

Thanks.

**Comment by nikitamikhaylov** [comment]
What will be if you disable `input_format_parallel_parsing` setting?

**Comment by aol-59** [comment]
> What will be if you disable `input_format_parallel_parsing` setting?

same error :(

**Comment by den-crane** [comment]
```
select [1,2,3],[1.1,2.2,3.3],['a','b','c'] format CSV
"[1,2,3]","[1.1,2.2,3.3]","['a','b','c']"
```

You sent:  `"[1]","[2]","[a,b,c]"` instead of `"[1,2,3]","[1.1,2.2,3.3]","['a','b','c']"`
