### ISSUE TITLE
FreeBSD Stable Version Build

### ISSUE THREAD

**Issue by janantos** [ClickHouse/ClickHouse#21561]
Are there stable versions freebsd builds available? I can see only latest master build. 
also have tried build using /utils/build/build_freebsd.sh but failing on pthread library during cmake configure.

is it please possible to provide build setup you are using for master builds?

Thanks Jan

**Comment by filimonov** [comment]
Open commit in the ClickHouse master branch which does some changes in code with a green mark near it.
Click on the green mark, open 'Special build check' it has a binary and a build log.

For example:
https://clickhouse-builds.s3.yandex.net/0/5a6cc876e4947f4b883faab9c15a1645ef413242/clickhouse_special_build_check/build_log_915339475_1615318107.txt 

It's actually a cross-build executed on Linux, but we expect direct build should work on BSD too.

**Comment by janantos** [comment]
Thanks for hints @filimonov, after little bit digging I can confirm I can build ClickHouse in FreeBSD pot jail. (clang11, freebsd 12.2)

```
cmake --debug-trycompile --verbose=1 -DCMAKE_VERBOSE_MAKEFILE=1 -LA -DCMAKE_BUILD_TYPE=release -DENABLE_CHECK_HEAVY_BUILDS=0 -DCMAKE_TOOLCHAIN_FILE=../cmake/freebsd/toolchain-x86_64.cmake -DCMAKE_C_COMPILER=clang11 -DCMAKE_CXX_COMPILER=clang++11 ..
ninja clickhouse-bundle
```
