### ISSUE TITLE
"max_concurrent_queries" setting change is not reflected in error message

### ISSUE THREAD

**Issue by yakout** [ClickHouse/ClickHouse#21567]
I changed the `max_concurrent_queries` server settings in config.xml to 200 and restarted the Server, but I still get this error
```
DB::Exception: Too many simultaneous queries. Maximum: 100 (version 21.1.2.15 (official build))
```

I noticed an increased load on the machine so I am assuming the setting took effect but the number didn't change in the error message, any idea why the number didn't change?

**Comment by ngsiolei** [comment]
Please have a look on preprocessed config `/var/lib/clickhouse/preprocessed_configs/config.xml`, which was generated by all config files, see if `max_concurrent_queries` was overridden.

Ref: [How to check whether Clickhouse server-settings is really applied?](https://stackoverflow.com/questions/65950979/how-to-check-whether-clickhouse-server-settings-is-really-applied)

**Comment by yakout** [comment]
Thanks Issue resolved.
when I run 
`sudo service clickhouse-server status`
I found the correct path of the config file (I was editing the wrong one)
```
└─274033 /usr/bin/clickhouse-server --config=/etc/clickhouse-server/config.xml --pid-file=/run/clickhouse-server/clickhouse-server.pid
```
