### ISSUE TITLE
FR: Table function dictionary

### ISSUE THREAD

**Issue by amosbird** [ClickHouse/ClickHouse#21560]
### Table function: dictionary

motivation: Provide an easy way to inspect dictionaries.

use case:  `select * from dictionary(dict)`.

It shall behave similar to the following:
```
create table xxx (<dictionary_column_definition>) engine Dictionary(dict);
select * from xxx;
drop table xxx;
```

**Comment by alexey-milovidov** [comment]
Actually it's useful only for dictionaries created from XML and only if you did not create the Dictionary database:
```
CREATE DATABASE dictionaries ENGINE = Dictionary
```

But may be still worth doing.
