### ISSUE TITLE
If one replica shut down, the ddl operation on cluster will never succeed. Are there any optimization plans? 

### ISSUE THREAD

**Issue by Sallery-X** [ClickHouse/ClickHouse#21574]

**Comment by filimonov** [comment]
I guess we need to introduce smth like 'maintenance' (maybe also 'failover') mode for a node.

**Comment by marising** [comment]
hi @filimonov, 

I implemented a node management feature. The node is stateful. If one replica node fails, the node can be paused by admin, and the user DDL operation can skip the paused node. When the node is restored, the node can be restarted by admin,  and the DDL can continue to execute. 

I don’t know if this is useful to everyone, can it be submitted to the community?

hi @Sallery-X , Is the scenario I described above what you need?

**Comment by Sallery-X** [comment]
> hi @filimonov,
> 
> I implemented a node management feature. The node is stateful. If one replica node fails, the node can be paused by admin, and the user DDL operation can skip the paused node. When the node is restored, the node can be restarted by admin, and the DDL can continue to execute.
> 
> I don’t know if this is useful to everyone, can it be submitted to the community?
> 
> hi @Sallery-X , Is the scenario I described above what you need?

yes！  could you share me？

**Comment by marising** [comment]
@Sallery-X 
Okay, I will sort out the code and test cases, and then submit a PR.
