### ISSUE TITLE
MaterializeMySQL: Does the database need to be recreated when replication is interrupted?

### ISSUE THREAD

**Issue by hssrs** [ClickHouse/ClickHouse#21576]
Hi, I am very interested in the new feature in MaterializeMySQL engine，It‘s awesome.

Recently I ran into a problem. When I used MaterializeMySQL to synchronize data from MySQL , the MySQL service was interrupted unexpectly, and when I restarted MySQL , the replication did not seem to continue until I restart the ClickHouse service.

My questions is 
- Can I assume that when this happens, the current solution is either to restart the service or drop and then recreate the database on the ClickHouse side?
- If my guess is correct, has the community included this question in the scope of optimization?  For example，re-connecting and continue the previous session when a similar exception occurs instead of restarting server.
- If we want MaterializeMySQL to support reconnection and can continue to synchronize data **from the interrupted position**, what issues need to be paid special attention to?

Thank in advance :D

**Comment by stigsb** [comment]
FWIW, you do not have to restart ClickHouse, `DETACH DATABASE foo; ATTACH DATABASE foo;` should do the trick.

Anyway, #20961 should fix this, so I believe this issue can be closed @filimonov
