### ISSUE TITLE
How to import csv file with  delimiter character ascll 

### ISSUE THREAD

**Issue by joakapp** [ClickHouse/ClickHouse#21575]
How to import csv file with ascll delimiter character, example:

LOOG_NFO110OU0702014-03-21-01.57.30.000000
LNOG_NFO110OU070502014-03-21-01.57.30.000000
ANOG_NFO110OU07502014-03-21-01.57.30.000000
LNOG_FO110OU00502014-03-21-01.57.30.000000

delimiter character "" is "0X03",

**Comment by den-crane** [comment]
--format_csv_delimiter=$'\x03'

**Comment by joakapp** [comment]
Thanks a lot
