### ISSUE TITLE
Is there any way to support the Bit DataType of Mysql  ？

### ISSUE THREAD

**Issue by zhaohaoren** [ClickHouse/ClickHouse#21578]
I have a mysql table with a bit column:
![image](https://user-images.githubusercontent.com/48273170/110580416-9c7ca980-81a3-11eb-9c4a-67b6a4168547.png)

and create a mysql engine table in clickhouse:

CREATE TABLE t_xxxx(
    is_deleted       UInt8
) ENGINE = MySQL

when query the table, reponse the follow error:
**`[2021-03-10 13:24:11] Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = mysqlxx::CannotParseValue: Cannot parse unsigned integer: , query: SELECT `is_deleted` FROM `table` (version 20.10.3.30 (official build))`**

I try to use Int8 and String to map this column, but it doesn‘t work very well，is there any other solutions to deal with this problem?

**Comment by filimonov** [comment]
https://github.com/ClickHouse/ClickHouse/issues/14735

**Comment by holadepo** [comment]
This workaround should work:
- Create the table using the `String` data type for the MySQL `bit` column
```
CREATE TABLE t_xxxx(
  is_deleted String
) ENGINE = MySQL
```

- Then use the `reinterpretAsUInt8` function to map the column to `UInt8` in your select statement.
`SELECT reinterpretAsUInt8(is_deleted) FROM t_xxxx`

**Comment by tavplubix** [comment]
#32900
