### ISSUE TITLE
How to improve ClickHouse Cluster performance when upgrade to 20.12.7.3 from 20.4.4.18

### ISSUE THREAD

**Issue by ggchangan** [ClickHouse/ClickHouse#21577]
Currently, we want upgrade ClickHouse version from 20.4.4.18 to 20.12.7.3 to use atomic database and do performance contrast between two version. 
The test environment is as the following:
ClickHouse: 4shards with 1 replica, C5.9xlarge, gp3 with 10000 IOPS and 1000 MB/s throughput.
The data is about 2T each shard and the case number is round 4000.
The version is the only different when do performance contrast.
Here is the basic conclusion:
1. The performance of ClickHouse cluster with 20.12.7.3 is worse then cluster with 20.4.4.18 in heavy pressure situation 
![image](https://user-images.githubusercontent.com/6263801/110580107-ee70ff80-81a2-11eb-9ae6-13f4235b9a29.png)
Each picture for one case set which is pulled from corresponding ClickHouse user in production environment. The x axis is query serial number, and y axis is query run time. And the red line is for 20.4.4.18, the green line is for 20.12.7.3.
And from the above picture, for example Case_troubleshoot_109.png, the green line is worse than red line for most cases.

It'll be very appreciated for any suggestions to improve the performance of cluster 20.12.7.3.

**Comment by filimonov** [comment]
Please share samples of problematic queries & schema.

**Comment by ggchangan** [comment]
From the above picture, you can see that the performance of afoptimizer, audience, datafeed_p3, mkpl, troubleshoot in 20.12.7.3 is worse than 20.4.4.18. Let make troubleshoot as an example, the <2000.ms ratio of 20.12.7.3 is worse than 20.4.4.18:
- 20.4.4.18

catalog | round | <=100.0ms | <=100.0ms ratio | >100.0ms <=500.0ms | <500.0ms ratio | >500.0ms <=1000.0ms | <1000.0ms ratio | >1000.0ms <=2000.0ms | <2000.0ms ratio | >2000.0ms <=3000.0ms | <3000.0ms ratio | >3000.0ms <=4000.0ms | <4000.0ms ratio | >4000.0ms <=5000.0ms | <5000.0ms ratio | >5000.0ms <=6000.0ms | <6000.0ms ratio | >6000.0ms <=7000.0ms | <7000.0ms ratio | >7000.0ms <=8000.0ms | <8000.0ms ratio | >8000.0ms <=20000.0ms | <20000.0ms ratio | >20000.0ms <=40000.0ms | <40000.0ms ratio | >40000.0ms <=60000.0ms | <60000.0ms ratio | >60000.0ms <=100000.0ms | <100000.0ms ratio | >100000.0ms <=200000.0ms | <200000.0ms ratio | >200000.0ms <=300000.0ms | <300000.0ms ratio | >300000.0ms <=400000.0ms | <400000.0ms ratio | >400000.0ms <=500000.0ms | <500000.0ms ratio | >500000.0ms <=600000.0ms | <600000.0ms ratio | >600000.0ms <=800000.0ms | <800000.0ms ratio | total
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
troubleshoot | 9 | 66 | 0.7857 | 15 | 0.9643 | 0 | 0.9643 | 3 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 84
troubleshoot | 8 | 48 | 0.5714 | 22 | 0.8333 | 7 | 0.9167 | 7 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 84
troubleshoot | 7 | 59 | 0.7024 | 18 | 0.9167 | 5 | 0.9762 | 2 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 84
troubleshoot | 6 | 51 | 0.6071 | 22 | 0.8690 | 6 | 0.9405 | 5 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 84
troubleshoot | 5 | 63 | 0.7500 | 18 | 0.9643 | 2 | 0.9881 | 1 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 84
troubleshoot | 4 | 57 | 0.6786 | 24 | 0.9643 | 3 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 84
troubleshoot | 3 | 35 | 0.4167 | 42 | 0.9167 | 6 | 0.9881 | 1 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 84
troubleshoot | 2 | 9 | 0.1071 | 22 | 0.3690 | 18 | 0.5833 | 13 | 0.7381 | 12 | 0.8810 | 2 | 0.9048 | 1 | 0.9167 | 1 | 0.9286 | 0 | 0.9286 | 1 | 0.9405 | 4 | 0.9881 | 1 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 84
troubleshoot | 1 | 0 | 0.0000 | 2 | 0.0238 | 6 | 0.0952 | 31 | 0.4643 | 17 | 0.6667 | 9 | 0.7738 | 4 | 0.8214 | 4 | 0.8690 | 0 | 0.8690 | 0 | 0.8690 | 5 | 0.9286 | 6 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 84
troubleshoot | 0 | 12 | 0.1429 | 18 | 0.3571 | 8 | 0.4524 | 24 | 0.7381 | 8 | 0.8333 | 2 | 0.8571 | 2 | 0.8810 | 0 | 0.8810 | 0 | 0.8810 | 0 | 0.8810 | 0 | 0.8810 | 10 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 84


- 20.12.7.3


catalog | round | <=100.0ms | <=100.0ms ratio | >100.0ms <=500.0ms | <500.0ms ratio | >500.0ms <=1000.0ms | <1000.0ms ratio | >1000.0ms <=2000.0ms | <2000.0ms ratio | >2000.0ms <=3000.0ms | <3000.0ms ratio | >3000.0ms <=4000.0ms | <4000.0ms ratio | >4000.0ms <=5000.0ms | <5000.0ms ratio | >5000.0ms <=6000.0ms | <6000.0ms ratio | >6000.0ms <=7000.0ms | <7000.0ms ratio | >7000.0ms <=8000.0ms | <8000.0ms ratio | >8000.0ms <=20000.0ms | <20000.0ms ratio | >20000.0ms <=40000.0ms | <40000.0ms ratio | >40000.0ms <=60000.0ms | <60000.0ms ratio | >60000.0ms <=100000.0ms | <100000.0ms ratio | >100000.0ms <=200000.0ms | <200000.0ms ratio | >200000.0ms <=300000.0ms | <300000.0ms ratio | >300000.0ms <=400000.0ms | <400000.0ms ratio | >400000.0ms <=500000.0ms | <500000.0ms ratio | >500000.0ms <=600000.0ms | <600000.0ms ratio | >600000.0ms <=800000.0ms | <800000.0ms ratio | total
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
troubleshoot | 9 | 3 | 0.0357 | 15 | 0.2143 | 12 | 0.3571 | 18 | 0.5714 | 12 | 0.7143 | 7 | 0.7976 | 3 | 0.8333 | 2 | 0.8571 | 2 | 0.8810 | 0 | 0.8810 | 10 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 84
troubleshoot | 8 | 5 | 0.0595 | 21 | 0.3095 | 16 | 0.5000 | 21 | 0.7500 | 7 | 0.8333 | 2 | 0.8571 | 2 | 0.8810 | 0 | 0.8810 | 0 | 0.8810 | 0 | 0.8810 | 7 | 0.9643 | 3 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 84
troubleshoot | 7 | 3 | 0.0357 | 18 | 0.2500 | 8 | 0.3452 | 12 | 0.4881 | 16 | 0.6786 | 10 | 0.7976 | 4 | 0.8452 | 2 | 0.8690 | 1 | 0.8810 | 0 | 0.8810 | 9 | 0.9881 | 1 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 84
troubleshoot | 6 | 2 | 0.0238 | 13 | 0.1786 | 9 | 0.2857 | 19 | 0.5119 | 14 | 0.6786 | 9 | 0.7857 | 6 | 0.8571 | 1 | 0.8690 | 0 | 0.8690 | 1 | 0.8810 | 9 | 0.9881 | 1 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 84
troubleshoot | 5 | 5 | 0.0595 | 17 | 0.2619 | 8 | 0.3571 | 9 | 0.4643 | 8 | 0.5595 | 11 | 0.6905 | 4 | 0.7381 | 7 | 0.8214 | 4 | 0.8690 | 0 | 0.8690 | 11 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 84
troubleshoot | 4 | 5 | 0.0595 | 12 | 0.2024 | 17 | 0.4048 | 21 | 0.6548 | 8 | 0.7500 | 7 | 0.8333 | 4 | 0.8810 | 0 | 0.8810 | 0 | 0.8810 | 0 | 0.8810 | 10 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 84
troubleshoot | 3 | 4 | 0.0476 | 22 | 0.3095 | 11 | 0.4405 | 21 | 0.6905 | 8 | 0.7857 | 6 | 0.8571 | 2 | 0.8810 | 0 | 0.8810 | 0 | 0.8810 | 0 | 0.8810 | 10 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 84
troubleshoot | 2 | 3 | 0.0357 | 17 | 0.2381 | 11 | 0.3690 | 23 | 0.6429 | 10 | 0.7619 | 7 | 0.8452 | 1 | 0.8571 | 2 | 0.8810 | 0 | 0.8810 | 0 | 0.8810 | 10 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 84
troubleshoot | 1 | 5 | 0.0595 | 29 | 0.4048 | 20 | 0.6429 | 9 | 0.7500 | 4 | 0.7976 | 5 | 0.8571 | 0 | 0.8571 | 2 | 0.8810 | 0 | 0.8810 | 0 | 0.8810 | 10 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 84
troubleshoot | 0 | 10 | 0.1190 | 28 | 0.4524 | 11 | 0.5833 | 21 | 0.8333 | 4 | 0.8810 | 0 | 0.8810 | 0 | 0.8810 | 0 | 0.8810 | 0 | 0.8810 | 0 | 0.8810 | 10 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 0 | 1.0000 | 84


- 20.4.4.18 datadog
![image](https://user-images.githubusercontent.com/6263801/110584205-cfc23700-81a9-11eb-92ff-997338ec9bb3.png)
- 20.12.7.3 datadog
![image](https://user-images.githubusercontent.com/6263801/110584236-d94b9f00-81a9-11eb-9803-dbdcfbb43885.png)

And from datadog picture of first 5 minutes, the average throughput of 20.4.4.18 is about 600k, however the average throughput of 20.12.7.3 is only about 300k.

**Comment by ggchangan** [comment]
@filimonov the performance test is based on case set and there're so many query and schema. Is there any setting changes from 20.4.4.18 to 20.12.7.3 which lead throughput of ClickHouse 20.12.7.3 is lower than ClickHouse 20.4.4.18?

**Comment by filimonov** [comment]
>  Is there any setting changes from 20.4.4.18 to 20.12.7.3 which lead throughput of ClickHouse 20.12.7.3 is lower than ClickHouse 20.4.4.18?

ClickHouse development pace is very high. There are thousands of changes in between. 

Here is the (not comprehensive) list of new settings / settings which change there default between 20.4.4.18 and 20.12.7.3:
https://gist.github.com/filimonov/bb4d58dbb0a91a5a64853bcc12e907bc#settings-and-merge_tree_settings

We don't expect that any of those changes should lead to a visible performance downgrade. If you see some - we need reproducible examples to be able to help you. 

BTW: i would recommend you to go to 21.1 instead. 20.12 is close to it's EOL.

**Comment by alexey-milovidov** [comment]
@ggchangan You should isolate the minumal subset of queries where the difference in performance is observable.

It's possible that your two clusters are different not only in version. For example, if you upload the data to a fresh cluster, the performance can be worse than on a cluster where data was uploaded a while ago.
