### ISSUE TITLE
select result from a view seems not right

### ISSUE THREAD

**Issue by thomasdba** [ClickHouse/ClickHouse#21585]
**Describe the bug**
Here log_full_v is a view to join two tables, column resp.time should be larger than time , but the fourth query is not as expected ,if i create a new table with the  data of view ,the fourth query looks as expected .

iZuf6hdfuwnixieohn4urrZ :) select sum(resp.time > time) from log_full_v ;

SELECT sum(resp.time > time)
FROM log_full_v

Query id: 19487f3f-93bd-4670-9fb5-df1a1f8f4fd8

┌─sum(greater(resp.time, time))─┐
│                          6057 │
└───────────────────────────────┘

1 rows in set. Elapsed: 0.014 sec. Processed 11.92 thousand rows, 631.81 KB (843.22 thousand rows/s., 44.69 MB/s.)

iZuf6hdfuwnixieohn4urrZ :) select count() from log_full_v;

SELECT count()
FROM log_full_v

Query id: 5ead0645-6ed9-4751-b80b-2a009bab3a8b

┌─count()─┐
│    6168 │
└─────────┘

1 rows in set. Elapsed: 0.008 sec. Processed 11.92 thousand rows, 559.69 KB (1.46 million rows/s., 68.41 MB/s.)

iZuf6hdfuwnixieohn4urrZ :) select sum(resp.time < time) from log_full_v ;

SELECT sum(resp.time < time)
FROM log_full_v

Query id: 1cd4367f-218b-4277-97d5-5d63a44321b6

┌─sum(less(resp.time, time))─┐
│                        111 │
└────────────────────────────┘

1 rows in set. Elapsed: 0.009 sec. Processed 11.92 thousand rows, 631.81 KB (1.36 million rows/s., 71.95 MB/s.)

**iZuf6hdfuwnixieohn4urrZ :) select count() from log_full_v where resp.time > time ;

SELECT count()
FROM log_full_v
WHERE resp.time > time

Query id: b25e1868-46ee-43c1-a8a3-cd9559e6de9a

┌─count()─┐
│       0 │
└─────────┘

1 rows in set. Elapsed: 0.007 sec. Processed 6.11 thousand rows, 323.83 KB (829.49 thousand rows/s., 43.96 MB/s.)**

iZuf6hdfuwnixieohn4urrZ :) select count() from log_full_v where resp.time < time+1000 ;

SELECT count()
FROM log_full_v
WHERE resp.time < (time + 1000)

Query id: 650543a3-76e8-4ebc-8399-82085a7ec922

┌─count()─┐
│     111 │
└─────────┘

1 rows in set. Elapsed: 0.015 sec. Processed 11.92 thousand rows, 631.81 KB (798.12 thousand rows/s., 42.30 MB/s.)

**Does it reproduce on recent release?**
[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

**How to reproduce**
* Which ClickHouse server version to use
* Which interface to use, if matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

**Expected behavior**

**Error message and/or stacktrace**

**Additional context**

**Comment by alexey-milovidov** [comment]
Does it reproduce on recent release?
