### ISSUE TITLE
DNS error: EAI: Address family for hostname not supported

### ISSUE THREAD

**Issue by dubin555** [ClickHouse/ClickHouse#21591]
**DNS error: EAI: Address family for hostname not supported**
the server with Ipv6 disable, when command 'clickhouse-server --config-file=/etc/clickhouse-server/config.xml'
the clickhouse server fail to start

here is the log
2021.03.10 13:11:57.843688 [ 8800 ] {} <Error> Application: DB::Exception: Listen [::]:8123 failed: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = DNS error: EAI: Address family for hostname not supported (version 21.2.5.5 (official build))

I try to modify the 'listen_host' in the config file with following setting
1. local ip 
2. ::
3. ::1
4. 0.0.0.0
5. 127.0.0.1
all attempts failed.

**How to reproduce**
* Which ClickHouse server version to use:  21.2.5.5 (official build)

Thanks in advance

**Comment by filimonov** [comment]
Or use `<listen_try>1</listen_try>` to ignore it.

**Comment by dubin555** [comment]
Solved. if anyone had the same issue, please try to modify the listen.xml(full path:/etc/clickhouse-server/config.d/listen.xml), do not modify the listen_host in the config.xml.

**Comment by kokizzu** [comment]
start getting this on docker today -_-"
