### ISSUE TITLE
Segmentation fault in libunwind when stopping v20.12.8.5

### ISSUE THREAD

**Issue by chbuescher** [ClickHouse/ClickHouse#21595]
We get a core file each time we restart clickhouse server running **on RHEL6** / x86

Failed to read a valid object file image from memory.
Core was generated by `clickhouse-server --daemon --pid-file=/var/run/clickhouse-server/clickhouse-ser'.
Program terminated with signal 11, Segmentation fault.
#0  0x00000000123e360c in _Unwind_GetCFA () at ../contrib/libunwind/src/libunwind.cpp:83
83      ../contrib/libunwind/src/libunwind.cpp: No such file or directory.
        in ../contrib/libunwind/src/libunwind.cpp
Missing separate debuginfos, use: debuginfo-install clickhouse-common-static-20.12.8.5-2.x86_64
(gdb) bt
#0  0x00000000123e360c in _Unwind_GetCFA () at ../contrib/libunwind/src/libunwind.cpp:83
#1  0x0000000000000000 in ?? ()
(gdb)

**Comment by alexey-milovidov** [comment]
Fixed in #17046.

**Comment by alexey-milovidov** [comment]
Version 20.12 is no longer supported. Update to version 21.3 is recommended.
