### ISSUE TITLE
Timeout exceeded while receiving data from server. Waited for 18446744073 seconds, timeout is 2100000000 seconds.

### ISSUE THREAD

**Issue by Derek-BMW** [ClickHouse/ClickHouse#21615]
caught this error when I tried to load data from mysql engine with 'insert into clickhouse.xxx select * from mysql_db.xxx'

the duration is obvious wrong, it just passed less than 5min

**Comment by Derek-BMW** [comment]
how can i solve this?

**Comment by abyss7** [comment]
Which version do you use?
