### ISSUE TITLE
Memory Usage / Leak Troubleshooting

### ISSUE THREAD

**Issue by chenziliang** [ClickHouse/ClickHouse#21611]
Hi,

May I ask if there are any steps we can execute to troubleshoot memory usage issues in ClickHouse ? Sometimes we found memory grows too much and OOM during data ingestion. We have tried Valgrind (in a black box way),  but look like it is not quite accurate and reported lots of `possible memory leak` which may not be the case. We also tried Google perftools in a white box way, but run into some challenges in launching the private build binary with perftools. I have seen some memory tracker / simple profiler / jemalloc metrics embedded in ClickHouse, may i ask if these tracker / profiler help and if there are docs on how to use them ?

Thanks !

**Comment by chenziliang** [comment]
One example of the fatal log is 

```
2021.03.10 21:39:19.745189 [ 200054 ] {} <Error> auto DB::IBackgroundJobExecutor::jobExecutingTask()::(anonymous class)::operator()() const: Code: 241, e.displayText() = DB::Exception: Memory limit (total) exceeded: would use 56.59 GiB (attempt to allocate chunk of 4412234 bytes), maximum: 56.59 GiB: (while reading column original_log): While executing MergeTreeSequentialSource, Stack trace (when copying this message, always include the lines below):  
```

**Comment by den-crane** [comment]
Clickhouse version?
Why do you think that you are experiencing a mem. leak? 
Do you have some graph to see memory usage in time?

If CH uses 56GB or 560GB it does not mean that it's a memory leak.

**Comment by chenziliang** [comment]
CH 20.11.1.

We are not sure if there are mem leak actually. Since we are only doing ingestion, it seems not quite making sense CH runs out of memory and crash (more reasonable way may be rejecting the ingest request instead?).

I will try to collect the usage graph.  

Thanks a lot !

**Comment by den-crane** [comment]
You provided zero information. No logs. No graphs. No queries. No table DDLs.
Clickhouse usually does not crash. And has memory tracker to prevent OOM. CH sets memory limit for itself as 0.9*RAM and fails queries with an error " Memory limit (total) exceeded: would use ... GiB".


You can change .9. /etc/clickhouse-server/config.xml

```
   <!-- On memory constrained environments you may have to set this to value larger than 1.
      -->
    <max_server_memory_usage_to_ram_ratio>0.9</max_server_memory_usage_to_ram_ratio>
```

**Comment by chenziliang** [comment]
> You provided zero information. No logs. No graphs. No queries. No table DDLs.
> Clickhouse usually does not crash. And has memory tracker to prevent OOM. CH sets memory limit for itself as 0.9*RAM and fails queries with an error " Memory limit (total) exceeded: would use ... GiB".
> 
> You can change .9. /etc/clickhouse-server/config.xml
> 
> ```
>    
>     <max_server_memory_usage_to_ram_ratio>0.9</max_server_memory_usage_to_ram_ratio>
> ```

Thanks. I will keep trying to see if it can be reproduced. And come back when i have more details.

**Comment by chenziliang** [comment]
Close it as we can't reproduce this issue. Will report back if it arises again.
