### ISSUE TITLE
arrayProduct

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#21613]
for the last year I replied 3 times with a silly snippet:
```
SELECT
    [2, 3, 4] AS x,
    pow(2, arraySum(i -> log2(i), x)) AS arrayProduct
┌─x───────┬─arrayProduct─┐
│ [2,3,4] │           24 │
└─────────┴──────────────┘
```

I think we need a function to multiply elements of an array.

**Comment by hexiaoting** [comment]
assign to me

**Comment by UnamedRus** [comment]
> assign to me, should I use pow(2, arraySum(i -> log2(i), x)) the algorithm to implement arrayProduct?

I don't think so, it would produce Float value from multiplying integers.


```
SELECT
    [2, 3, 40] AS x,
    pow(2, arraySum(i -> log2(i), x)) AS arrayProduct

Query id: 1fcc62b2-fd29-4cff-b9ed-f4e434c9043a

[LAPTOP-319G0GMQ] 2021.03.12 04:55:33.309638 [ 10268 ] {1fcc62b2-fd29-4cff-b9ed-f4e434c9043a} <Debug> executeQuery: (from 127.0.0.1:38504, using production parser) SELECT [2, 3, 40] AS x, pow(2, arraySum(i -> log2(i), x)) AS arrayProduct;
┌─x────────┬───────arrayProduct─┐
│ [2,3,40] │ 240.00000000000003 │
└──────────┴────────────────────┘
```

There is actually arrayFold function in development, which is generalized version of arrayProduct i guess.

https://github.com/ClickHouse/ClickHouse/pull/21589

**Comment by den-crane** [comment]
It should calculate 2*3*4

arrayProduct([2,3,4]) -> 2*3*4 = 24

**Comment by pp641** [comment]
It should be 
accumulate(v.begin(), v.end(), 1, multiplies<int>())
 This function in c++ multiplies all the element of the array in c++
arr[] = {1,2,3,4};
int ans =  accumulate(arr.begin(), arr.end(), 1, multiplies<int>())
ans = 24

**Comment by dmalkr** [comment]
Yes, you can implement product of elements via `arrayFold`: `SELECT arrayFold(x,acc -> x*acc, [1,2,3,4,5], toInt64(1));`
PR #21589 (`arrayFold` function) on review now.

**Comment by hexiaoting** [comment]
@den-crane 
When I process Array(Decimal(P, s)) , which kind of type should  I return ?  Decimal(P,S) or enlarge scale by multiply the array size?

I find the type of operator  `*` result's  scale enlarged by add all the operators `8 = 4+4`: 
```
select toDecimal32(0.111, 4) as a,  toDecimal32(0.112, 4) as b, a *b　as k , toTypeName(k) ,toTypeName(a), toTypeName(b);

┌──────a─┬──────b─┬──────────k─┬─toTypeName(multiply(toDecimal32(0.111, 4), toDecimal32(0.112, 4)))─┬─toTy│
peName(toDecimal32(0.111, 4))─┬─toTypeName(toDecimal32(0.112, 4))─┐                                       │
│ 0.1110 │ 0.1120 │ 0.01243200 │ Decimal(9, 8)                                                      │ Deci│
mal(9, 4)                     │ Decimal(9, 4)                     │                                       │
└────────┴────────┴────────────┴────────────────────────────────────────────────────────────────────┴─────│
──────────────────────────────┴───────────────────────────────────┘
```

**Comment by hexiaoting** [comment]
@den-crane Can you give me some advice？

**Comment by den-crane** [comment]
>When I process Array(Decimal(P, S)) , which kind of type should I return ?

The same time as the input type (Decimal(P, S)) and use float64 for calculations
