### ISSUE TITLE
Metric ZooKeeperSession is more than 1 in 20.12.7

### ISSUE THREAD

**Issue by Zhile** [ClickHouse/ClickHouse#21621]
Hi, 
I'm using ClickHouse 20.12.7.3 and I have 3 zookeeper nodes. I found the metric ZooKeeperSession is more than 1. 

Every time I select ZooKeeperSession from system.metrics, it's always more than 1. But its description is 
`Number of sessions (connections) to ZooKeeper. Should be no more than one, because using more than one connection to ZooKeeper may lead to bugs due to lack of linearizability (stale reads) that ZooKeeper consistency model allows.
`
I also select the rows from system.metric_log. The value CurrentMetric_ZooKeeperSession is like
total: 246237, 
3 (12988 rows, 5%), 2 (210838 rows, 86%), 1 (22488 rows, 9%)
It seems most time this value is not 1.

However, I didn't see any problems if this value is more than 1. 

What is the meaning of this value? Are there any methods I can do or check to make this value be 1? Are there any consequences if this value remains 1 all the time? 

We're very serious about the zookeeper status because it's so critical for the cluster that we need to pay a lot of attention on it.

**Comment by filimonov** [comment]
Don't you use multiple zookeepers in clickhouse?

**Comment by alesapin** [comment]
This bug is quite rare but was introduced in 20.10 and fixed here https://github.com/ClickHouse/ClickHouse/pull/21264.

**Comment by Zhile** [comment]
Thanks @alesapin. This is really timely for us to know that. I think we have to use a new version for this.
BTW, we use three zookeeper nodes for ClickHouse cluster. These nodes are in same cluster.

**Comment by winter7** [comment]
@alesapin Is there a released version for this fix please？

**Comment by ys-zhaoyh** [comment]
ClickHouse release v21.3, 2021-03-12  @winter7
