### ISSUE TITLE
when i upgrade version 20.8.11.17 to 20.6.6.7

### ISSUE THREAD

**Issue by Sallery-X** [ClickHouse/ClickHouse#21622]
Logging information to /var/lib/clickhouse/clickhouse-server-log/clickhouse-server.log
Logging errors to /var/lib/clickhouse/clickhouse-server-log/clickhouse-server.err.log
Logging information to console
2021.03.11 17:58:16.029409 [ 1 ] {} <Information> SentryWriter: Sending crash reports is disabled
2021.03.11 17:58:16.068013 [ 1 ] {} <Information> : Starting ClickHouse 20.6.6.7 with revision 54436, build id: EFED6F232CE6FE56, PID 1
2021.03.11 17:58:16.068097 [ 1 ] {} <Information> Application: starting up
2021.03.11 17:58:16.072172 [ 1 ] {} <Information> Application: It looks like the process has no CAP_IPC_LOCK capability, binary mlock will be disabled. It could happen due to incorrect ClickHouse package installation. You could resolve the problem manually with 'sudo setcap cap_ipc_lock=+ep /usr/bin/clickhouse'. Note that it will not work on 'nosuid' mounted filesystems.
2021.03.11 17:58:16.072479 [ 1 ] {} <Error> Application: The <users>, <profiles> and <quotas> elements should be located in users config file: /etc/clickhouse-server/users.xml not in main config /etc/clickhouse-server/config.xml. Also note that you should place configuration changes to the appropriate *.d directory like 'users.d'.
Include not found: networks
2021.03.11 17:58:16.074768 [ 1 ] {} <Information> Application: Loading metadata from /var/lib/clickhouse/
2021.03.11 17:58:16.075400 [ 1 ] {} <Error> Application: Caught exception while loading metadata: Code: 62, e.displayText() = DB::Exception: Syntax error (in file /var/lib/clickhouse/metadata/system.sql): failed at position 19 (line 1, col 19): UUID 'f1e0cff7-f187-4e10-bdd4-37f18bd5b42a'
ENGINE = Atomic
. Expected one of: storage definition, ENGINE, ON, Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x123fea60 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xa23e3fd in /usr/bin/clickhouse
2. ? @ 0x100c5a8e in /usr/bin/clickhouse
3. ? @ 0xf4f7c2c in /usr/bin/clickhouse
4. DB::loadMetadataSystem(DB::Context&) @ 0xf4fa8ce in /usr/bin/clickhouse
5. DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0xa2dce1e in /usr/bin/clickhouse
6. Poco::Util::Application::run() @ 0x1232dab7 in /usr/bin/clickhouse
7. DB::Server::run() @ 0xa2a2869 in /usr/bin/clickhouse
8. mainEntryClickHouseServer(int, char**) @ 0xa294513 in /usr/bin/clickhouse
9. main @ 0xa239919 in /usr/bin/clickhouse
10. __libc_start_main @ 0x270b3 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
11. _start @ 0xa23902e in /usr/bin/clickhouse
 (version 20.6.6.7 (official build))
2021.03.11 17:58:16.075464 [ 1 ] {} <Information> Application: Shutting down storages.
2021.03.11 17:58:16.076658 [ 1 ] {} <Error> Application: DB::Exception: Syntax error (in file /var/lib/clickhouse/metadata/system.sql): failed at position 19 (line 1, col 19): UUID 'f1e0cff7-f187-4e10-bdd4-37f18bd5b42a'
ENGINE = Atomic
. Expected one of: storage definition, ENGINE, ON
2021.03.11 17:58:16.076722 [ 1 ] {} <Information> Application: shutting down
2021.03.11 17:58:16.076903 [ 45 ] {} <Information> BaseDaemon: Stop SignalListener thread

**Comment by abyss7** [comment]
Do you mean "downgrade to version" instead? We don't support downgrading by any means - the metadata, binary formats, etc may change without backward compatibility.

**Comment by filimonov** [comment]
Just remove system database from metadata/data/store folder. It will be recreated.

And Yes, just like @abyss7  said, sometimes newer versions use some  newer features, which can prevent the possibility to downgrade. 

But in most of cases it's possible to disable new functionality if you need to keep a possibility of downgrading.

**Comment by baofengzhouyu** [comment]
Did you solved this problem ？ I had  the same problem !
