### ISSUE TITLE
create UpdatingMergeTree table engine

### ISSUE THREAD

**Issue by mbtolou** [ClickHouse/ClickHouse#21638]
hi.

can you create UpdatingMergeTree for update old value of record.
like this :

```sql
CREATE TABLE test.updating (d Date, k UInt64, s String, v0 Nullable(UInt16),v1  Nullable(UInt16), v2  Nullable(UInt16),v3  Nullable(UInt16)) ENGINE = UpdatingMergeTree (d, k, 8192);

INSERT INTO test.updating (d,k,s,v0) VALUES ('2000-01-01', 1, 'Hello', 0);

select *
from test.updating
```
result :
'2000-01-01'      1         'Hello'        0         null           null          null

```sql
INSERT INTO test.updating (d,k,s,v1) VALUES ('2000-01-01', 1, 'Hello', 10);
```

result :
'2000-01-01'      1         'Hello'        0         10             null          null

**Comment by den-crane** [comment]
>can you create UpdatingMergeTree for update old value of record.

We cannot.

try this: https://gist.github.com/den-crane/d03524eadbbce0bafa528101afa8f794

**Comment by mbtolou** [comment]
Your opinion about this :

```sql
select *
from test.updating
SETTINGS keep_last_value_by_order_keys;
```

and 

```sql
optimize test.updating final
SETTINGS keep_last_value_by_order_keys;
```

**Comment by mbtolou** [comment]
https://github.com/ClickHouse/ClickHouse/issues/3852#issuecomment-465646350
