### ISSUE TITLE
If table mismatch Kafka Engine drops messages

### ISSUE THREAD

**Issue by tobad357** [ClickHouse/ClickHouse#2163]
Steps to reproduce

1. Create a Kafka Topic and send some CapnProto messages to it including and enum with two values
```
enum Test {
  col1 @1;
  col2 @2;
}
```
2. Create a Kafka Table
3. Create a materialized view on top of the Kafka table but with and enum that has three values

Now Clickhouse will log 
<Error> void DB::StorageKafka::streamThread(): Code: 53, e.displayText() = DB::Exception: Type mismatch for column enum_test. Column has type Enum16(...)

But the batch still gets committed and the message is lost

This causes problems in case the enums are updated in the wrong order.
What would be expected is that the batch wouldn't be committed if the error happens

Steps to update an enum

1. Detach kafka tables
2. Delete materialized views
3. Delete kafka tables
4. Recreate kafka tables with new enum def
5. Recreate mat views

**Comment by tobad357** [comment]
@vavrusa FYI, in case you are using this in production

**Comment by vavrusa** [comment]
@tobad357 any chance you could try investigate? It seems to be throwing an error, but maybe something needs to be checked in the readSuffix() before committing. https://github.com/yandex/ClickHouse/blob/master/dbms/src/Storages/StorageKafka.cpp#L185

**Comment by tobad357** [comment]
Will try to investigate.
My C++ chops isn't the greatest, as haven't used it in 18 years

**Comment by filimonov** [comment]
Fixed long ago. Now Kafka engine do commits only if able to parse all the messages and flush the data to destination tables.
