### ISSUE TITLE
What capped the throughput of one consumer

### ISSUE THREAD

**Issue by winter7** [ClickHouse/ClickHouse#21648]
My question is about upper limit of parameter `kafka_max_block_size`.
I once created one Kafka table to consume a queue with huge messages. Since my version was 20.4, I wasn't using `kafka_num_consumers` to add threads. 
My `kafka_max_block_size` was set as `1048576`. Configs `min_insert_block_size` and `min_insert_block_size` are both `1048576`.
I can monitor consumer group lags were increasing while the IOPS or throughput of ClickHouse instances were very low. So I was wondering what capped the throughput of one consumer.
I tried to modify `kafka_max_block_size` as `10485760` and only to find that flushing size seemed to be still 1M instead of 10M and lags showed no tendency to slow down. 
As far as I know, there are only 2 ways to improve consuming performance, adding consumer('s threads) or increasing the value of `kafka_max_block_size`. But it didn't work as expected when I modified the parameter from 1M to 10M. Do you have any idea about it?
If you need more information I’d be more than happy to provide it.

**Comment by filimonov** [comment]
> there are only 2 ways to improve consuming performance, adding consumer('s threads) or increasing the value of

There are more:
1) update clickhouse version
2) adjust [librdkafka settings](https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md) namely  queued.min.messages and queued.max.messages.kbytes and few others.
To do that - create kafka section in /etc/clickhouse-server/config.xml, like follows:
```
<kafka>
 <queued_min_messages>10000000</queued_min_messages>
</kafka>
```

**Comment by winter7** [comment]
@filimonov Thanks for the help!
I'm wondering whether parameter `kafka_max_block_size` has an upper limit value?

**Comment by filimonov** [comment]
> I'm wondering whether parameter kafka_max_block_size has an upper limit value?

There is no sense (usually) to set it to more than few millions.
