### ISSUE TITLE
The same SQL on the same node gets different results

### ISSUE THREAD

**Issue by sileiH** [ClickHouse/ClickHouse#21651]
When I run the same SQL on the same node, I get different results and find that they scan different rows. I then split the SQL and found that the split results add up correctly. 
So I have a question, is it possible that when a SQL consumes a large amount of resources, its results may produce errors?

**CREATE SQL：**
CREATE TABLE test.testTable_local on cluster report_shards_replicas (
  `id1` String, `id2` String , `arrayList` Array(String)
) ENGINE = ReplicatedMergeTree('/clickhouse/tables/{layer}-{shard}/testTable_local', '{replica}')

**EXCUTE SQL：**
select count(1) from test.testTable_local where  has(arrayList, 'xxx');

**RESULT：**

┌─count(1)─┐
│ 95308188 │
└──────────┘

1 rows in set. Elapsed: 38.917 sec. Processed 187.10 million rows, 463.72 GB (4.81 million rows/s., 11.92 GB/s.) 

┌─count(1)─┐
│ 94000772 │
└──────────┘

1 rows in set. Elapsed: 53.800 sec. Processed 184.52 million rows, 457.35 GB (3.43 million rows/s., 8.50 GB/s.) 

**CLICKHOUSE VERSION：**
20.12.3

**Comment by UnamedRus** [comment]
https://github.com/ClickHouse/ClickHouse/issues/18137

try `set read_backoff_min_latency_ms=0`

**Comment by filimonov** [comment]
Or just update clickhouse version.
