### ISSUE TITLE
Wrong Partition selected/deleted

### ISSUE THREAD

**Issue by JaitlyD** [ClickHouse/ClickHouse#21650]
For end of month, if a date doesn't exist, its selecting the next available date.
When I ran: ALTER TABLE DbName.TableName DROP PARTITION '2020-09-31', this statement deleted data for October-1st as September has only 30 days
* Which ClickHouse server version to use 21.2.2.8
* Which interface to use, if matters: Dbeaver, ClickHouse client
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

**Expected behavior**

ALTER TABLE DbName.TableName DROP PARTITION '2020-09-31' would have thrown date exception, instead it deleted next available date()ct-1st-2020) partition. Also, this issue exist for Select statement as well.
**Error message and/or stacktrace**

**Additional context**

**Comment by den-crane** [comment]
The behavior of parsing incorrect dates is implementation specific. ClickHouse may return zero date, throw an exception or do “natural” overflow.

```
SELECT toDate('2020-09-31')

┌─toDate('2020-09-31')─┐
│           2020-10-01 │
└──────────────────────┘
```
