### ISSUE TITLE
multiple query occur error

### ISSUE THREAD

**Issue by lcwxz1989** [ClickHouse/ClickHouse#21657]
When I benchmark clickhouse, get this error ' could not load time location: too many open files'. The concurrency is 10

**Comment by den-crane** [comment]
What Clickhouse version do you use?
How we can reproduce this? Do you have SQL to run? Create table? Data sample?
Can you share `cat /etc/security/limits.d/clickhouse.conf`

**Comment by lcwxz1989** [comment]
I have make a mistake, I do not close the connection. Thx a lot
