### ISSUE TITLE
【Timing trigger】How to routinely delay statistics 3min before specifying the mean value and quantile value of the aggregated latitude

### ISSUE THREAD

**Issue by shadowDy** [ClickHouse/ClickHouse#21660]
sql demo：
select a，avg(b)，avg(c),quantile(0.900000)(b)/avg(d) bd,quantile(0.900000)(c)/avg(e) ce from xxxx where time='xxx' group by a
for example:
when 10：56，i want execute a sql with time param = 10:53
when 10：57，i want execute a sql with time param = 10:54

The results of each minute will be written into the new table y to provide queries, and each time the data of the past 3 hours in the y table will be queried

Does clickhouse have a timing trigger？
or How Materialized Views Support Timing Calculation of Quantile

thanks

**Comment by amosbird** [comment]
Cron job is in current roadmap. You can use external tools like crontab for now, with sql predicate :  `time = toStartOfMinute(now()) - 180`

**Comment by shadowDy** [comment]
@amosbird Can materialized views be used to solve the pre aggregation of 99 percentile values？

**Comment by amosbird** [comment]
The sql demo doesn't look like pre-aggregation. It aggregates per minute data and generates a new table. In these case, MV will suffice.

If you need pre-aggregation by minute, this https://github.com/ClickHouse/ClickHouse/pull/20202 will help.

**Comment by shadowDy** [comment]
@amosbird 
Thank you for your reply
In fact, the basic table is a table with tens of billions of data, which can be written in real time, query the data of the past three hours every minute, and aggregate the data by column a + minute granularity. Calculate the mean value, quantile value and other operations.

In my understanding, pre aggregation can reduce duplicate data of 2 hours and 58 minutes per scan.

Is this the category of materialized view processing?

Can materialized views be used to solve the pre aggregation of 99 percentile values？

I'm not sure I understand the pre aggregation and materialized views correctly.

**Comment by melvynator** [comment]
> Does clickhouse have a timing trigger？

We now have refreshable materialized view: https://clickhouse.com/docs/en/sql-reference/statements/create/view#refreshable-materialized-view
