### ISSUE TITLE
Clickhouse materialized views using differential dataflow

### ISSUE THREAD

**Issue by silashansen** [ClickHouse/ClickHouse#21669]
Seeing how [Materialize](https://materialize.com/) is innovating on the performance of materialized views using [Differential Dataflow](https://github.com/TimelyDataflow/differential-dataflow), I'm wondering if Clickhouse is using or considering implementing something similar, since there is so much focus on Materialized views already.

I am not an expert on the internals of differential dataflow, although it sounds like a novel approach that is worth looking into.
I'm evaluating our next analytics for real-time analytics right now, that's why I'm wondring.

**Comment by abyss7** [comment]
I'm not expert either in DD, but seems like the Differential Dataflow is a whole another different engine, which is hardly related to our concept of materialized views.

If you point out specific peformance or architectural differences between CH and DD approaches, we can try to discuss them in details.
