### ISSUE TITLE
`regexp_tree` dictionary type

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#21694]
**Use case**

User-Agent parsing: #157.
But the implementation should be flexible enough to solve more string parsing/extraction tasks.

**Describe the solution you'd like**

The dictionary data is represented by a tree of regular expressions.
(actually not a tree but multiple trees - there can be multiple root nodes)

Every node of the tree can have:
1. Regular expression. If it is matched, then children (if any) will be processed and setting the result attribute (if any, see 2) will be done. Regexp can have subpatterns that can be referenced later.
2. Setting an attribute(s) to some value. Can contain references to previously matched subpatterns. Attribute is processed as a string and then casted to its type (in dictionary spec).
3. Arbitrary number of children nodes of the same type.

When attributes are requested from the dictionary, the tree will be traversed until every attribute is set. If there are multiple matching regexps that have branches setting the same attribute, the first (last?) wins. If the tree has been traversed but attribute was not set, the default value for attribute is assigned.

The data can be loaded from table (using any available dictionary source) with the following structure:

id UInt64,
parent_id UInt64,
regexp String,
*attr_1* String,
...
*attr_n* String

`id` and `parent_id` only exists to make a tree structure.
`attr_n` is the column for the corresponding attribute - its value is how to set the attribute if regexp matched, examples: `Internet Explorer` (just a string) or `Windows \1` (string with referenced subpattern) or `\2` (just a referenced subpattern, for example, if subpattern contains digits - it can be used to set numeric attribute).

Alternatively, the tree can be specified in YAML file (config) in local filesystem - we should create `YAMLDictionarySource` for this purpose. In this case, `id` and `parent_id` are not specified (implicit).

The tree can have multiple children (alternative branches) with different regular expressions. We should combine these regular expressions to match in a single pass and select what branches are applicable. This is possible with Hyperscan. Maybe we should match all the regexps from all tree nodes at once and then traverse the tree just checking the bool flags.

**Details**

Maybe we can also allow to set a temporary (scratch) variables to reference it later in a tree.

The dictionary should support `LowCardinality(String)` types.

**Comment by alexey-milovidov** [comment]
Example:
(sorry, I don't know YAML, but I hope you will get the idea)

```
match: 'MSIE (\\d+)'
    set:
        version: '\\1'
    match: 'Windows'
        set:
            os: 1
match: 'Mozilla'
...
```

**Comment by alexey-milovidov** [comment]
Real world example is here: https://github.com/highpower/uatraits/blob/master/data/browser.xml

**Comment by filimonov** [comment]
I'm afraid that tree may be not enough.

UA parsing is often state machine than tree traversal - it can have negative regular expressions which can reset the state and switch to another branch.

**Comment by alexey-milovidov** [comment]
It should work on this database: https://github.com/matomo-org/device-detector/tree/master/regexes

**Comment by alexey-milovidov** [comment]
@filimonov 

> I'm afraid that tree may be not enough.

Our experience in [Yandex.Metrica](https://metrica.yandex.com/) shows that tree is enough.

**Comment by filimonov** [comment]
BTW most tfaffic is created by few hundreds of different useragents, lru cache on hashed user agent string allows not to apply any regexp most of the time.

**Comment by alexey-milovidov** [comment]
Yes, this technique was implemented in our internal library (the number of unique user-agents was about several millions).

**Comment by ivoleg** [comment]
I'm working on it

**Comment by alexey-milovidov** [comment]
The task has been abandoned.

**Comment by alexey-milovidov** [comment]
This feature makes sense and worth doing.

**Comment by nooblose** [comment]
I'm working on it

**Comment by alexey-milovidov** [comment]
Continued in #40878.

**Comment by hanfei1991** [comment]
update: the following work will be donw in https://github.com/ClickHouse/ClickHouse/pull/43858

I aim to support ua parse libs  https://github.com/ua-parser/uap-core and https://github.com/matomo-org/device-detector/tree/master/regexes but still have some problems. Check the pr to follow the progress

**Comment by hanfei1991** [comment]
after this pr https://github.com/ClickHouse/ClickHouse/pull/45631 regexp tree dictionary will be a better ua-parser which is compatible with https://github.com/ua-parser/uap-core

See the test to know how to use it.
