### ISSUE TITLE
Parsing google.protobuf.Timestamp

### ISSUE THREAD

**Issue by lddlww** [ClickHouse/ClickHouse#21725]
i use kafka engine for parse the protobuf message，which like follow：
```
message Mth{
    repeated Sth ts = 1;
    google.protobuf.Timestamp create_time=11;
}
```
clickhouse table :
```
CREATE TABLE metrics.proto
(
    `ts.labels` Array(Nested(name String, value String)),
    `ts.samples` Array(Nested(ts Int64, value Float64)),
    `create_time` DateTime64(3)
)
ENGINE = TinyLog
```

when i exec  the follow cmd，it throws error
```
cat proto_msg.bin |clickhouse-client --query "insert into metrics.proto format Protobuf settings format_schema='msg:Mth'"

Code: 570. DB::Exception: The field 'opsac.spider.v1.Mth.create_time' has an incompatible type message for serialization of the data type 'DateTime64': data for INSERT was parsed from stdin
```

how can i define column type to map  ```google.protobuf.Timestamp```  format ?

**Comment by filimonov** [comment]
It's not rfc3339 
It's https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#google.protobuf.Timestamp

So submessage with 2 fields.

**Comment by lddlww** [comment]
thanks for reply

i use ```Tuple(seconds Int64, nanos Int32)``` to map ```google.protobuf.Timestamp```, it's work now
