### ISSUE TITLE
Build failed on  branch v21.3.2.5-lts

### ISSUE THREAD

**Issue by Sallery-X** [ClickHouse/ClickHouse#21731]
CPoject/ClickHouse/contrib/libcxx/include/cstdlib:158:9: error: no member named 'aligned_alloc' in the global namespace

**Comment by Sallery-X** [comment]
macos   llvm 11.1.0

**Comment by fastio** [comment]
Hi, modify the file contrib/libcxx/include/cstdlib:157, from ```if _LIBCPP_STD_VER > 14 && defined(_LIBCPP_HAS_ALIGNED_ALLOC)``` to ```if _LIBCPP_STD_VER > 17 && defined(_LIBCPP_HAS_ALIGNED_ALLOC)```

**Comment by jindal-git** [comment]
Can I use this thread to confirm how the official images are built for this version? Should I use gcc-10 on linux:

./packager --output-dir deb/out/ --package-type deb --compiler=gcc-10

**Comment by alexey-milovidov** [comment]
clang-11 should be used.

Here is how the official binaries are built: https://clickhouse-builds.s3.yandex.net/0/d7c43291b14092c7a393b5d3bfc2f9c8dd636c0b/clickhouse_build_check/build_log_919871481_1615825131.txt

1. Open the "commits" page:
https://github.com/ClickHouse/ClickHouse/commits/master

2. Find a commit with successful "ClickHouse build check":
![Screenshot_20210315_215745](https://user-images.githubusercontent.com/18581488/111206572-98082480-85d9-11eb-99df-fbf74f5f1ce8.png)

3. Click on the "Details" link.

4. Open the build logs.

**Comment by alexey-milovidov** [comment]
In "ClickHouse special build check" you will also find build for Mac OS (they are named "darwin").
