### ISSUE TITLE
CLA Questions 

### ISSUE THREAD

**Issue by JasonKeirstead** [ClickHouse/ClickHouse#21738]
Hi all. I was looking at this project and trying to get a handle on the contribution process. 

The CLA (https://yandex.ru/legal/cla/?lang=en) has three clauses in it that are somewhat strange, and I am hoping I can get some additional clarification.

Clause 4 states: 

"_4. Use of Contributes by Contributor. Once Contributes are provided to Yandex and this Agreement is signed, Contributor reserves the right to use Contributes by any legal means **provided such use causes no damage to Yandex’s business reputation**_." (emphasis added by me) 

Putting aside that "business reputation" is extremely broad, this clause seems incompatible with the Apache 2 license that this project is under.... ? 

Clause 5 states: 

"_6. Market Value. Contributor confirms that the market value of the ordinary (non-exclusive) license for the right to use each particular Contribute granted by Contributor to Yandex makes RUR 100 (one hundred)._" 

I do not understand what this clause is or why it is there, it does not read that "the market value makes R100". Is it trying to say that the market value of the code *is* R100? How is one to know what the current market value of a snippet of their code is?

Clause 9 states:

"_9. Liability. If any claims or legal actions are filed against Yandex for its use of Contributes, Contributor undertakes to compensate all property losses of the Customer resulted from such claims provided Yandex used Contributes in accordance with the terms hereof._"

I believe this also violates the Apache 2 license. It is also opening the contributor up to a huge legal risk.
 
**EDIT**: At the bottom of CONTRIBUTING.md it also gives the option of using a totally different DCO? This is a bit confusing.

**Comment by alexey-milovidov** [comment]
You don't have to sign a CLA to contribute code.

> As an alternative, you can provide DCO instead of CLA. You can find the text of DCO here: https://developercertificate.org/ It is enough to read and copy it verbatim to your pull request.

> If you don't agree with the CLA and don't want to provide DCO, you still can open a pull request to provide your contributions.

**Comment by JasonKeirstead** [comment]
If the CLA provisions are obsolete, can I suggest it be removed to eliminate confusion?

**Comment by alexey-milovidov** [comment]
They are not obsolete - if you ok with CLA, you can agree with the terms.
