### ISSUE TITLE
Discussion: cluster-shared session 

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#21748]
A lot of BI tools rely on using temporary tables. 

When clickhouse works in the cluster, later queries (which rely on the existence of temporary tables created before) can be sent by the load balancer to some other clickhouse node, which knows nothing about the session.

So the lack of session consistency cluster-wide may be a limiting factor for using ClickHouse with different BI tools.

Maybe we need to look for some ways to share the session somehow inside the cluster, or redirect the user transparently to the node hosting his session (it's HTTP and named sessions used).

Alternative options/ideas are welcomed.

**Comment by alexey-milovidov** [comment]
This is interesting... In our use cases we allocate additional two nodes that look on cluster and analysts connect to either one or another and create their temporary tables there.

**Comment by alexey-milovidov** [comment]
Also there was a use case in Yandex.Metrica when we pass some hint (arbitrary random string) to the API that will allow to prefer specific API server (sticky balancing) and then `load_balancing = 'nearest_hostname'` is used to implement sticky balancing on ClickHouse side.

This is to get consistent results on subsequent queries in presence of lagging replicas.

**Comment by alexey-milovidov** [comment]
So, the issue should be technically solvable by load balancer.
