### ISSUE TITLE
RabbitMQ engine works incorrectly with queue which contains messages

### ISSUE THREAD

**Issue by AlexeySadkovich** [ClickHouse/ClickHouse#21757]
Hi!
I made a table with RabbitMQ engine which connects to an existing queue and saves messages from it to table through materialized view. If the queue was empty before connecting then every new message is stored in table successfully, but if there were messages in the queue then only the last one is stored and others just disappear.

```SQL
CREATE TABLE queue (
	log String
) ENGINE = RabbitMQ SETTINGS ..., rabbitmq_exchange_type = 'topic', rabbitmq_format = 'JSONAsString';


CREATE MATERIALIZED VIEW consumer TO general AS
SELECT
   ...
FROM queue;
```

Do you have any idea what this can be about? It seems to me that this is  a bug in engine or view. 

Thanks!

ClickHouse 21.2.5.5

**Comment by kssenii** [comment]
@AlexeySadkovich, can you show all settings of the table? You use `rabbitmq_queue_base` setting?

**Comment by AlexeySadkovich** [comment]
@kssenii,
Yes, I'm using name of exisiting queue for  ```rabbitmq_queue_base``` setting.

All settings:
```SQL
rabbitmq_host_port = '...',
rabbitmq_exchange_name = '...',
rabbitmq_queue_base = 'logs-clickhouse',
rabbitmq_exchange_type = 'topic',
rabbitmq_routing_key_list = 'logs',
rabbitmq_format = 'JSONAsString';
```

**Comment by kssenii** [comment]
Actually, in the list of usages of `rabbitmq_queue_base` settings it is `not` written that it can be used as a queue defined by user, from which to receive messages. It was anyway supposed that publishing is done only  to `exchange`, not to queue.

But I can take a look at this case. Anyway, it not optimal. You may better publish to exchange, which allows to use `num_queues` and `num_consumers` settings together which makes everything much much faster.

So you start publishing and then create a table? Also you declare same exchnage, queue and bind queue to exchange yourself?

**Comment by AlexeySadkovich** [comment]
@kssenii,
Yep, publishing starts before table creation.
I have two similar queues binded to general exchange. One for clickhouse service and another for different service. The point is I'd like to avoid data inconsistency between both services if something goes wrong with clickhouse and I restart it. So i need to read and store all accumulated messages.
Exchange is already declared. It seems to me that it doesn't matter how queue and binding were created because queued messages don't get to table anyway.
