### ISSUE TITLE
parseDateTimeBestEffortOrZero('') returns 2000-01-01 00:00:00

### ISSUE THREAD

**Issue by aopetrov86** [ClickHouse/ClickHouse#21765]
**Describe the unexpected behaviour**
Query:
```sql
select 
    toDate(0),
    toDateTime(0),
    parseDateTimeBestEffortOrZero(''),
    parseDateTimeBestEffortOrZero('dfg')
```
Returns strange result:
| toDate\(0\) | toDateTime\(0\) | parseDateTimeBestEffortOrZero\(''\) | parseDateTimeBestEffortOrZero\('dfg'\) |
| :--- | :--- | :--- | :--- |
| 1970-01-01 | 1970-01-01 00:00:00 | 2000-01-01 00:00:00 | 1970-01-01 00:00:00 |

**How to reproduce**
* Which ClickHouse server version to use 20.8.14.4

**Expected behavior**
parseDateTimeBestEffortOrZero('') == 1970-01-01 00:00:00

**Comment by filimonov** [comment]
Most probably fixed in https://github.com/ClickHouse/ClickHouse/pull/16541 (20.11+)

**Comment by aopetrov86** [comment]
@filimonov, thanks. Not reproduced in version 20.11.6
