### ISSUE TITLE
Could you offer me a link

### ISSUE THREAD

**Issue by Sallery-X** [ClickHouse/ClickHouse#21767]
clang-11 should be used.

Here is how the official binaries are built: https://clickhouse-builds.s3.yandex.net/0/d7c43291b14092c7a393b5d3bfc2f9c8dd636c0b/clickhouse_build_check/build_log_919871481_1615825131.txt

1. Open the "commits" page:
https://github.com/ClickHouse/ClickHouse/commits/master

2. Find a commit with successful "ClickHouse build check":
![Screenshot_20210315_215745](https://user-images.githubusercontent.com/18581488/111206572-98082480-85d9-11eb-99df-fbf74f5f1ce8.png)

3. Click on the "Details" link.

4. Open the build logs.

_Originally posted by @alexey-milovidov in https://github.com/ClickHouse/ClickHouse/issues/21731#issuecomment-799672993_

**Comment by den-crane** [comment]
here 21.3  https://clickhouse-builds.s3.yandex.net/21495/f0c97a2b9643fda8cf32dec46248a8d098fb4af6/clickhouse_build_check/report.html

**Comment by godliness** [comment]
@Sallery-X On macos i did not find clang++-11, only clang-11 in **/usr/local/opt/llvm/bin/clang-11**.

  LLVM (http://llvm.org/):
  LLVM version 11.0.1
  Optimized build.
  Default target: x86_64-apple-darwin19.6.0
  Host CPU: haswell

clang version 11.0.1
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /usr/local/opt/llvm/bin

which clang++-11
clang++-11 not found

In the report, i found they use the clang++-11

Did you find the clang++-11 on MacOs (10.15.7 (19H114))?
