### ISSUE TITLE
Ephemeral Credentials/GRANTS

### ISSUE THREAD

**Issue by WesleyBatista** [ClickHouse/ClickHouse#21763]
**Use case**

Considering the [Playground example](https://clickhouse.tech/docs/en/getting-started/playground/#examples) presented on the official docs, I wish it was possible to execute queries trough HTTP API/Native Client by providing a temporary user credentials, that would be vanished with its privileges after some specified time.

**Describe the solution you'd like**

Implement a **`TTL`** option/setting for the [`CREATE USER`](https://clickhouse.tech/docs/en/sql-reference/statements/create/user/) statement, so it is possible to create users that will be automatically removed on the background after a certain time. For example:
```sql
CREATE USER mira WITH TTL 1800
```

**Describe alternatives you've considered**

Perhaps could also be implemented on the [`GRANT`](https://clickhouse.tech/docs/en/sql-reference/statements/grant/) statement:
```sql
GRANT SELECT ON my_test_database.* TO mira WITH TTL 1800
```

```sql
GRANT role_containing_grants TO mira WITH TTL 1800
```

**Comment by filimonov** [comment]
Sound a bit strange. From RBAC you usually expect dererminism w/o too many 'automatic' changes. 

Can you explain why exactly is it needed? Playground currently uses single user.

**Comment by WesleyBatista** [comment]
> _From RBAC you usually expect dererminism w/o too many 'automatic' changes_

Thanks for bringing this up. I didn't have this perspective.

Unfortunately, I have no strong background on security to contribute more on the topic.

> _Can you explain why exactly is it needed? Playground currently uses single user._

I wouldn't say it is needed, it is more like a rough idea that popped up.

Elaborating a bit more and leaving Playground aside, please consider the following scenario:

- We need to allow access/actions to specific tables/databases for new users in an ad-hoc manner.
- We also want to have fine grain permissions, for security reasons.

Today, we would need to manually create these users and set the permissions/roles.
The users are ad-hoc, so they might need access just for some hours or days, and whoever takes care of the database _ideally_ would remove the user as soon as there's no need for it anymore.

An user could be easily forgotten if we depend on manual processes or communication to happen. Leaving credentials behind could potentially compromise database's integrity and give chances for data breaches. 

It would be nice if the database itself did the job of removing the user after **`TTL`** expires.

This was the idea I had before your input. I am not sure anymore how valuable and feasible it really is.

**Comment by alexey-milovidov** [comment]
This is implemented with temporary passwords.
