### ISSUE TITLE
Memory Spike: System Hang

### ISSUE THREAD

**Issue by nshah14285** [ClickHouse/ClickHouse#21772]
OS: Ubuntu 18.04
Clickhouse Version: 21.2.5.5 (upgraded from version 20.12.5.14)
Memory: 8GB
Swap Memory: 4GB
Processor: 4 core

I am using Oracle Virtual Box and have installed Ubuntu 18.04 and Clickhouse 21.2.5.5 on that. Earlier version of clickhouse was working fine. Problem occured after upgrading to clickhouse to 21.2.5.5

**Issues**
Memory spikes and system get hang when I connect clickhouse from terminal using clickhouse-client command and run queries like `show databases` or `show tables` etc..

I tried to limit the values from configuration file but it has no effect.
Please find attached configuration file.

It works perfectly when I access clickhouse from
`UI: Tabix`
`clickhouse-client  -q 'Show databases;'`
`clickhouse-client -q 'SELECT count(*) FROM test.user;'`

Please help to resolve this issue.

[config.txt](https://github.com/ClickHouse/ClickHouse/files/6146935/config.txt)
[users.txt](https://github.com/ClickHouse/ClickHouse/files/6146936/users.txt)

**Comment by filimonov** [comment]
Please ensure it's really hang (other queries are not working, while clickhouse-process is active) ensure your VM have enough ram, ensure that the process was not killed by oomkiller (see `dmesg`). 

We need fragment of log just before the issue:
```
sudo tail -n 1000 /var/log/clickhouse-server/clickhouse-server.log | tee logtail.txt
```

stacktraces at the moment of hang:

```
sudo apt-get update 
sudo apt-get install gdb clickhouse-common-static-dbg=$(clickhouse-client --version-clean)

sudo gdb -p $(pidof -s clickhouse-server) -batch -ex 'set pagination off' -ex 'thread apply all backtrace' -ex 'detach' -ex 'quit' | tee trace.txt
```

Please provide requested info and attach both files to continue.

**Comment by alexey-milovidov** [comment]
No info provided.

**Comment by nshah14285** [comment]
@alexey-milovidov 
I'll provide the details once I run the above mentioned command provided by you.
