### ISSUE TITLE
Would use 1.00 EiB ... while executing ConvertingAggregatedToChunksTransform

### ISSUE THREAD

**Issue by Teeeto** [ClickHouse/ClickHouse#21773]
Abnormal memory requirements for a query with string filter

Appeared fresh after upgrade to 21.3.2.5 

The table is not big - 480 mb compressed

Getting an error
```
SQL Error [241]: ClickHouse exception, code: 241, host: localhost, port: 8123; Code: 241, e.displayText() = DB::Exception: Memory limit (for query) exceeded: would use 1.00 EiB (attempt to allocate chunk of 1152921504606554384 bytes), maximum: 101.47 GiB: While executing ConvertingAggregatedToChunksTransform (version 21.3.2.5 (official build))

The query is quite plain
SELECT 
       FirstScreen,
       "SessionResult" AS "SessionResult",
       count(*) AS count
FROM
  (SELECT FirstScreen,
          SessionResult,
          LastResponse,
          toDate(LastResponseDateTime),
          WasEligible,
          WasSessionSuccessfull,
          COUNT (*)
   FROM MPTUSSDSESSIONS
   GROUP by FirstScreen,
            SessionResult,
            LastResponse,
            toDate(LastResponseDateTime),
            WasEligible,
            WasSessionSuccessfull) AS expr_qry
WHERE  "SessionResult" NOT IN ('unknown result')
  AND "WasSessionSuccessfull" ='Y'
GROUP BY FirstScreen,  "SessionResult"
ORDER BY count DESC
LIMIT 10000;
```

Most interesting - when line  `AND "WasSessionSuccessfull" ='Y' ` is removed from the query it completes ok.

**Comment by Teeeto** [comment]
The table DDL is 
CREATE TABLE XXX
(

    `SessionId` Int64 CODEC(Delta(8),
 LZ4HC(0)),

    `SUBSCRIBERID` String CODEC(ZSTD(22)),

    `LastResponse` Nullable(String) CODEC(ZSTD(22)),

    `LastResponseDateTime` Nullable(DateTime64(3)) CODEC(Delta(8),
 LZ4HC(0)),

    `LastRequest` Nullable(String) CODEC(LZ4HC(0)),

    `FirstScreen` Nullable(String) CODEC(LZ4HC(0)),

    `ActionCount` Nullable(Int64) CODEC(T64,
 LZ4HC(0)),

    `IsLastValid` Nullable(UInt8) CODEC(LZ4HC(0)),

    `SessionResult` Nullable(String) CODEC(ZSTD(22)),

    `WasEligible` String CODEC(ZSTD(22)),

    `WasSessionSuccessfull` String CODEC(ZSTD(22))
)
ENGINE = MergeTree
PRIMARY KEY (SessionId,
 SUBSCRIBERID)
ORDER BY (SessionId,
 SUBSCRIBERID)
SETTINGS index_granularity = 8192;

**Comment by filimonov** [comment]
Please provide the whole stacktrace of the exception (should be in logs).

**Comment by Teeeto** [comment]
This run memory requirement changed but still huge. If I use string filters on different columns at the same place error still comes up with different memory requirements (was testing data corruption hypothesis)

2021.03.17 10:15:04.376890 [ 202508 ] {72d64fae-d654-4cc2-aaca-b1e5cdcdd99a} <Error> executeQuery: Code: 241, e.displayText() = DB::Exception: Memory limit (for query) exceeded: would use 32.00 PiB (attempt to allocate chunk of 36028797016894038 bytes), maximum: 101.47 GiB: While executing ConvertingAggregatedToChunksTransform (version 21.3.2.5 (official build)) (from 127.0.0.1:49806) (in query: SELECT FirstScreen, "SessionResult" AS "SessionResult", count(*) AS count FROM (SELECT FirstScreen, SessionResult, LastResponse, toDate(LastResponseDateTime), WasEligible, WasSessionSuccessfull, COUNT (*) FROM MPTUSSDSESSIONS GROUP by FirstScreen, SessionResult, LastResponse, toDate(LastResponseDateTime), WasEligible, WasSessionSuccessfull) AS expr_qry WHERE "SessionResult" NOT IN ('unknown result') AND "WasSessionSuccessfull" ='Y' GROUP BY FirstScreen, "SessionResult" ORDER BY count DESC FORMAT TabSeparatedWithNamesAndTypes;), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception<char const*, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, long&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const*&&, char const*&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, long&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&) @ 0x8624525 in /usr/bin/clickhouse
1. MemoryTracker::alloc(long) @ 0x8623e7d in /usr/bin/clickhouse
2. MemoryTracker::alloc(long) @ 0x8623be4 in /usr/bin/clickhouse
3. void DB::PODArrayBase<1ul, 4096ul, Allocator<false, false>, 15ul, 16ul>::resize<>(unsigned long) @ 0x8661737 in /usr/bin/clickhouse
4. DB::ColumnString::deserializeAndInsertFromArena(char const*) @ 0xf1ffc0e in /usr/bin/clickhouse
5. void HashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash<StringRef, void>, HashTableNoState>, DefaultHash<StringRef, void>, HashTableGrower<8ul>, Allocator<true, true> >::forEachValue<void DB::Aggregator::convertToBlockImplFinal<DB::AggregationMethodSerialized<HashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash<StringRef, void>, HashTableNoState>, DefaultHash<StringRef, void>, HashTableGrower<8ul>, Allocator<true, true> > >, HashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash<StringRef, void>, HashTableNoState>, DefaultHash<StringRef, void>, HashTableGrower<8ul>, Allocator<true, true> > >(DB::AggregationMethodSerialized<HashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash<StringRef, void>, HashTableNoState>, DefaultHash<StringRef, void>, HashTableGrower<8ul>, Allocator<true, true> > >&, HashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash<StringRef, void>, HashTableNoState>, DefaultHash<StringRef, void>, HashTableGrower<8ul>, Allocator<true, true> >&, std::__1::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn> > >&, std::__1::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn> > >&, DB::Arena*) const::'lambda'(DB::AggregationMethodSerialized<HashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash<StringRef, void>, HashTableNoState>, DefaultHash<StringRef, void>, HashTableGrower<8ul>, Allocator<true, true> > > const&, HashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash<StringRef, void>, HashTableNoState>, DefaultHash<StringRef, void>, HashTableGrower<8ul>, Allocator<true, true> >&)>(DB::AggregationMethodSerialized<HashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash<StringRef, void>, HashTableNoState>, DefaultHash<StringRef, void>, HashTableGrower<8ul>, Allocator<true, true> > >&&) @ 0xef4ff10 in /usr/bin/clickhouse
6. void DB::Aggregator::convertToBlockImplFinal<DB::AggregationMethodSerialized<HashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash<StringRef, void>, HashTableNoState>, DefaultHash<StringRef, void>, HashTableGrower<8ul>, Allocator<true, true> > >, HashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash<StringRef, void>, HashTableNoState>, DefaultHash<StringRef, void>, HashTableGrower<8ul>, Allocator<true, true> > >(DB::AggregationMethodSerialized<HashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash<StringRef, void>, HashTableNoState>, DefaultHash<StringRef, void>, HashTableGrower<8ul>, Allocator<true, true> > >&, HashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash<StringRef, void>, HashTableNoState>, DefaultHash<StringRef, void>, HashTableGrower<8ul>, Allocator<true, true> >&, std::__1::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn> > >&, std::__1::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn> > >&, DB::Arena*) const @ 0xef4fe04 in /usr/bin/clickhouse
7. void DB::Aggregator::convertToBlockImpl<DB::AggregationMethodSerialized<HashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash<StringRef, void>, HashTableNoState>, DefaultHash<StringRef, void>, HashTableGrower<8ul>, Allocator<true, true> > >, HashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash<StringRef, void>, HashTableNoState>, DefaultHash<StringRef, void>, HashTableGrower<8ul>, Allocator<true, true> > >(DB::AggregationMethodSerialized<HashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash<StringRef, void>, HashTableNoState>, DefaultHash<StringRef, void>, HashTableGrower<8ul>, Allocator<true, true> > >&, HashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash<StringRef, void>, HashTableNoState>, DefaultHash<StringRef, void>, HashTableGrower<8ul>, Allocator<true, true> >&, std::__1::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn> > >&, std::__1::vector<DB::PODArray<char*, 4096ul, Allocator<false, false>, 15ul, 16ul>*, std::__1::allocator<DB::PODArray<char*, 4096ul, Allocator<false, false>, 15ul, 16ul>*> >&, std::__1::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn> > >&, DB::Arena*, bool) const @ 0xef49256 in /usr/bin/clickhouse
8. DB::Aggregator::prepareBlockAndFillSingleLevel(DB::AggregatedDataVariants&, bool) const @ 0xeebcf65 in /usr/bin/clickhouse
9. DB::ConvertingAggregatedToChunksTransform::mergeSingleLevel() @ 0xfae0854 in /usr/bin/clickhouse
10. ? @ 0xf931ddd in /usr/bin/clickhouse
11. DB::PipelineExecutor::executeStepImpl(unsigned long, unsigned long, std::__1::atomic<bool>*) @ 0xf92ea01 in /usr/bin/clickhouse
12. ? @ 0xf9335d6 in /usr/bin/clickhouse
13. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x864f9df in /usr/bin/clickhouse
14. ? @ 0x8653473 in /usr/bin/clickhouse
15. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
16. __clone @ 0x122103 in /usr/lib/x86_64-linux-gnu/libc-2.31.so

2021.03.17 10:15:04.377716 [ 202508 ] {72d64fae-d654-4cc2-aaca-b1e5cdcdd99a} <Error> DynamicQueryHandler: Code: 241, e.displayText() = DB::Exception: Memory limit (for query) exceeded: would use 32.00 PiB (attempt to allocate chunk of 36028797016894038 bytes), maximum: 101.47 GiB: While executing ConvertingAggregatedToChunksTransform, Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception<char const*, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, long&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const*&&, char const*&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, long&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&) @ 0x8624525 in /usr/bin/clickhouse
1. MemoryTracker::alloc(long) @ 0x8623e7d in /usr/bin/clickhouse
2. MemoryTracker::alloc(long) @ 0x8623be4 in /usr/bin/clickhouse
3. void DB::PODArrayBase<1ul, 4096ul, Allocator<false, false>, 15ul, 16ul>::resize<>(unsigned long) @ 0x8661737 in /usr/bin/clickhouse
4. DB::ColumnString::deserializeAndInsertFromArena(char const*) @ 0xf1ffc0e in /usr/bin/clickhouse
5. void HashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash<StringRef, void>, HashTableNoState>, DefaultHash<StringRef, void>, HashTableGrower<8ul>, Allocator<true, true> >::forEachValue<void DB::Aggregator::convertToBlockImplFinal<DB::AggregationMethodSerialized<HashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash<StringRef, void>, HashTableNoState>, DefaultHash<StringRef, void>, HashTableGrower<8ul>, Allocator<true, true> > >, HashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash<StringRef, void>, HashTableNoState>, DefaultHash<StringRef, void>, HashTableGrower<8ul>, Allocator<true, true> > >(DB::AggregationMethodSerialized<HashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash<StringRef, void>, HashTableNoState>, DefaultHash<StringRef, void>, HashTableGrower<8ul>, Allocator<true, true> > >&, HashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash<StringRef, void>, HashTableNoState>, DefaultHash<StringRef, void>, HashTableGrower<8ul>, Allocator<true, true> >&, std::__1::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn> > >&, std::__1::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn> > >&, DB::Arena*) const::'lambda'(DB::AggregationMethodSerialized<HashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash<StringRef, void>, HashTableNoState>, DefaultHash<StringRef, void>, HashTableGrower<8ul>, Allocator<true, true> > > const&, HashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash<StringRef, void>, HashTableNoState>, DefaultHash<StringRef, void>, HashTableGrower<8ul>, Allocator<true, true> >&)>(DB::AggregationMethodSerialized<HashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash<StringRef, void>, HashTableNoState>, DefaultHash<StringRef, void>, HashTableGrower<8ul>, Allocator<true, true> > >&&) @ 0xef4ff10 in /usr/bin/clickhouse
6. void DB::Aggregator::convertToBlockImplFinal<DB::AggregationMethodSerialized<HashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash<StringRef, void>, HashTableNoState>, DefaultHash<StringRef, void>, HashTableGrower<8ul>, Allocator<true, true> > >, HashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash<StringRef, void>, HashTableNoState>, DefaultHash<StringRef, void>, HashTableGrower<8ul>, Allocator<true, true> > >(DB::AggregationMethodSerialized<HashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash<StringRef, void>, HashTableNoState>, DefaultHash<StringRef, void>, HashTableGrower<8ul>, Allocator<true, true> > >&, HashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash<StringRef, void>, HashTableNoState>, DefaultHash<StringRef, void>, HashTableGrower<8ul>, Allocator<true, true> >&, std::__1::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn> > >&, std::__1::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn> > >&, DB::Arena*) const @ 0xef4fe04 in /usr/bin/clickhouse
7. void DB::Aggregator::convertToBlockImpl<DB::AggregationMethodSerialized<HashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash<StringRef, void>, HashTableNoState>, DefaultHash<StringRef, void>, HashTableGrower<8ul>, Allocator<true, true> > >, HashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash<StringRef, void>, HashTableNoState>, DefaultHash<StringRef, void>, HashTableGrower<8ul>, Allocator<true, true> > >(DB::AggregationMethodSerialized<HashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash<StringRef, void>, HashTableNoState>, DefaultHash<StringRef, void>, HashTableGrower<8ul>, Allocator<true, true> > >&, HashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash<StringRef, void>, HashTableNoState>, DefaultHash<StringRef, void>, HashTableGrower<8ul>, Allocator<true, true> >&, std::__1::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn> > >&, std::__1::vector<DB::PODArray<char*, 4096ul, Allocator<false, false>, 15ul, 16ul>*, std::__1::allocator<DB::PODArray<char*, 4096ul, Allocator<false, false>, 15ul, 16ul>*> >&, std::__1::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn> > >&, DB::Arena*, bool) const @ 0xef49256 in /usr/bin/clickhouse
8. DB::Aggregator::prepareBlockAndFillSingleLevel(DB::AggregatedDataVariants&, bool) const @ 0xeebcf65 in /usr/bin/clickhouse
9. DB::ConvertingAggregatedToChunksTransform::mergeSingleLevel() @ 0xfae0854 in /usr/bin/clickhouse
10. ? @ 0xf931ddd in /usr/bin/clickhouse
11. DB::PipelineExecutor::executeStepImpl(unsigned long, unsigned long, std::__1::atomic<bool>*) @ 0xf92ea01 in /usr/bin/clickhouse
12. ? @ 0xf9335d6 in /usr/bin/clickhouse
13. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x864f9df in /usr/bin/clickhouse
14. ? @ 0x8653473 in /usr/bin/clickhouse
15. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
16. __clone @ 0x122103 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
 (version 21.3.2.5 (official build))

**Comment by Teeeto** [comment]
I was trying to build a test dataset to reproduce the issue and encountered a strange behavior which may or may not be related to the issue.

Generate test data:
CREATE TABLE Test
(
String1 String codec(LZ4HC(0)),
String2 String codec(LZ4HC(0)),
String3 String codec(LZ4HC(0)),
String4 String codec (LZ4HC(0))
)
ENGINE = MergeTree()
PRIMARY KEY (String1,String2)
ORDER BY (String1,String2)
SETTINGS index_granularity = 8192;




INSERT INTO Test 
SELECT BS1,randomString(2),BS2, randomString(1)
FROM (select bitShiftRight(rand32(),28)+1 Rand16 FROM numbers(50*1000*1000)) n join 
(SELECT row_number() over () as RN, randomString(100) BS1, randomString(50) BS2 from numbers(16)) bigStrings
on n.Rand16=bigStrings.RN

Now, two selects with their results:

SELECT *
FROM
  (SELECT String1,
          String2,
          String3,
          String4,
          COUNT (*)
   FROM Test
   GROUP by String1,
            String2,
            String3,
            String4
) AS expr_qry

![WithoutFilter](https://user-images.githubusercontent.com/56020245/111434565-1fa87d00-8719-11eb-8983-f7ca5ada5ac0.png)

Its ok, now we add a filter

SELECT *
FROM
  (SELECT String1,
          String2,
          String3,
          String4,
          COUNT (*)
   FROM Test
   GROUP by String1,
            String2,
            String3,
            String4
) AS expr_qry
WHERE  String4 ='B'

![WithFilter](https://user-images.githubusercontent.com/56020245/111434633-33ec7a00-8719-11eb-86ab-ff47f0b11a70.png)

Please note how the first column became equal to the filter looks like 1st and 4th columns swapped essentially.

**Comment by filimonov** [comment]
Confirmed:
```
DROP TABLE IF EXISTS Test;

CREATE TABLE Test
ENGINE = MergeTree()
PRIMARY KEY (String1,String2)
ORDER BY (String1,String2)
AS 
SELECT
   'String1_' || toString(number) as String1,
   'String2_' || toString(number) as String2,
   'String3_' || toString(number) as String3,
   'String4_' || toString(number%4) as String4
FROM numbers(1);

SELECT *
FROM
  (
   SELECT String1,String2,String3,String4,COUNT(*)
   FROM Test
   GROUP by String1,String2,String3,String4
  ) AS expr_qry
FORMAT Vertical;

SELECT *
FROM
  (
    SELECT String1,String2,String3,String4,COUNT(*)
    FROM Test
    GROUP by String1,String2,String3,String4
  ) AS expr_qry
WHERE  String4 ='String4_0'
FORMAT Vertical;
```

**Comment by alexey-milovidov** [comment]
The fix will ship in the next patch release tomorrow.
