### ISSUE TITLE
Nearly 6000 lines of construction sentences are executed multiple times to report different error messages

### ISSUE THREAD

**Issue by yangyongyongyong** [ClickHouse/ClickHouse#21774]
Make sure to check documentation https://clickhouse.yandex/docs/en/ first. If the question is concise and probably has a short answer, asking it in Telegram chat https://telegram.me/clickhouse_en is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

If you still prefer GitHub issues, remove all this text and ask your question here.

[mycreateTableScripts.txt](https://github.com/ClickHouse/ClickHouse/files/6148071/mycreateTableScripts.txt)

启动服务
docker run -d --name some-clickhouse-server --ulimit nofile=262144:262144 yandex/clickhouse-server

客户端连接
docker run -it --rm --link some-clickhouse-server:clickhouse-server yandex/clickhouse-client  --multiline --host clickhouse-server

when i run create table scripts (which in mycreateTableScripts.txt).  it return "Unmatched parentheses: ("  or  "Expected one of: CODEC, NULL, ALIAS, TTL, ClosingRoundBracket, Comma, DEFAULT, NOT, MATERIALIZED, COMMENT, token"  . 

The two return strings always appear at random.

Shouldn't reporting errors be the same?

**Comment by yangyongyongyong** [comment]
when i install clickhouse on docker, show this error; but when i install clickhouse in centos,than The constructional sentences pass. so it is docker issue.

**Comment by filimonov** [comment]
Do you copy & paste your long query in clickhouse-client interactive session? It may be for example some issue with tabs.

Workarounds:
- you can pipe in the file 
- use queries-file command line argument. 
- remove newlines and tabs from the query before pasting it into interactive session

**Comment by yangyongyongyong** [comment]
> Do you copy & paste your long query in clickhouse-client interactive session? It may be for example some issue with tabs.
> 
> Workarounds:
> 
> * you can pipe in the file
> * use queries-file command line argument.
> * remove newlines and tabs from the query before pasting it into interactive session

error

**Comment by alexey-milovidov** [comment]
Increase the `max_query_size` setting. You can pass `--max_query_size` to clickhouse-client in command line.
