### ISSUE TITLE
How to best way manage a ClickHouse Cluster

### ISSUE THREAD

**Issue by jonatasfreitasv** [ClickHouse/ClickHouse#2178]
Hi guy's, I'm again :).

How Yandex manage her cluster ?

Manual manage is very hard.

Let's imagine a scenario where I have 100 machines, 50-50 shard / replica.

When I have to create a replicated/shard table, it would have to enter the 100 servers and manually create one by one, this is unfeasible.

Or for example, I want to delete a table, same scenario.

How do you solve this type of situation on the +300 Yandex Metrica servers.

**Comment by alex-zaitsev** [comment]
Look at 'ON CLUSTER' syntax.
https://clickhouse.yandex/docs/en/single/index.html#distributed-ddl-queries-on-cluster-clause

**Comment by jonatasfreitasv** [comment]
Yes, but when i try this:

`DROP TABLE rt_analytics.activations ON CLUSTER cluster`

I receive this message:

`Code: 49, e.displayText() = DB::Exception: Query id cannot be empty, e.what() = DB::Exception`

**Comment by lamber-ken** [comment]
hi，it needs the version of server and client are same

**Comment by jonatasfreitasv** [comment]
Is the same version in all:

# Shard 1
ClickHouse client version 1.1.54362.
Connected to ClickHouse server version 1.1.54362.

# Replica 1
ClickHouse client version 1.1.54362.
Connected to ClickHouse server version 1.1.54362.

Shard 2
ClickHouse client version 1.1.54362.
Connected to ClickHouse server version 1.1.54362.

**Comment by lamber-ken** [comment]
try version 1.1.54370.
I met the same error, I use 1.1.54376, it's ok

**Comment by jonatasfreitasv** [comment]
The last version for YUM is 1.1.54362 =/

**Comment by lamber-ken** [comment]
@jonatasfreitasv, you can use docker https://hub.docker.com/r/yandex/clickhouse-server/

**Comment by NanoBjorn** [comment]
I had an issue with docker — you have yo use `--network=host` to make it work and it is not save. This happens because you place actual server ip in `config.yml` file but by default docker iptables config container could not connect to the host itself so replicating does not work properly.

It seems that there is no easy way of managing cluster and every devops writes his own salt scripts or more complex system to make manageable.
