### ISSUE TITLE
toDate(string) function successfully parses some inputs, which should not be parsed, while not parsing other similar inputs.

### ISSUE THREAD

**Issue by hrissan** [ClickHouse/ClickHouse#21782]
(you don't have to strictly follow this form)

**Describe the bug**
toDate function successfully parses some inputs, which should not be parsed, while not parsing other similar inputs.

**Does it reproduce on recent release?**
Yes

$ clickhouse-client
ClickHouse client version 21.3.2.5 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 21.3.2 revision 54447.

**How to reproduce**
boot3879 :) select toDate('3021-06-10')
│           1970-01-01 │
boot3879 :) select toDate('2021-16-10')
│           1970-01-01 │
boot3879 :) select toDate('2021-06-40')
│           1970-01-01 │
boot3879 :) select toDate('nice-06-10')
│           1970-01-01 │

**Expected behavior**
boot3879 :) select toDate('3021-06-10')
Code: 6. DB::Exception: 
boot3879 :) select toDate('2021-16-10')
Code: 6. DB::Exception: 
boot3879 :) select toDate('2021-06-40')
Code: 6. DB::Exception: 
boot3879 :) select toDate('nice-06-10')
Code: 6. DB::Exception: 

**Additional context**

If we try letters instead of digits for month or day, exception is correctly raised.

boot3879 :) select toDate('2021-hi-10')
Code: 6. DB::Exception: Received from localhost:9000. DB::Exception: Cannot parse string '2021-hi-10' as Date: syntax error at position 9 (parsed just '2021-hi-1'): While processing toDate('2021-hi-10'). 
SELECT toDate('2021-06-hi')
Code: 6. DB::Exception: Received from localhost:9000. DB::Exception: Cannot parse string '2021-06-hi' as Date: syntax error at position 9 (parsed just '2021-06-h'): While processing toDate('2021-06-hi'). 

Why specifying "nice" or other letters as year part or specifying month/day as incorrect digits are allowed and map to year 1970, while specifying "hi" or other letters as month/day raises exception?

BTW this behavior also happens in toDateTime

**Comment by den-crane** [comment]
The behavior of parsing incorrect dates is implementation specific. ClickHouse may return zero date, throw an exception or do “natural” overflow.

**Comment by flyingmutant** [comment]
How can you determine if the date is correct or not? Isn't it the job of `toDate`?

**Comment by den-crane** [comment]
I am not a CH developer. I am a member of CH community and I am doing triage.

My opinion: CH developers decided that it's a responsibility of a client for the sake of performance.
Nothing to discuss here. I closed tons of issues like your.

**Comment by proggga** [comment]
Thanks for the help, but you said:
> My opinion: CH developers decided that it's a responsibility of a client for the sake of performance.

this is your opinion, not theirs, not either is community opinion
if you sure, that CHdev decided that, please send a link to the official documentation

**Comment by den-crane** [comment]
my quote is a copy/paste from the documentation.

I can add the same sentence to the documentation for toDate function if you like.

**Comment by proggga** [comment]
> my quote is a copy/paste from the documentation.
> 
> I can add the same sentence to the documentation for toDate function if you like.

Your quote is copy/paste from documentation, but that sentence not in the documentation and you can add this to docs?
Am I right?

**Comment by den-crane** [comment]
@proggga I took it from https://clickhouse.tech/docs/en/sql-reference/functions/date-time-functions/#tostartofmonth

And yes, I think I will add the same snippet to toDate / toDateTime .... functions.
```
Attention

The behavior of parsing incorrect dates is implementation specific. ClickHouse may return zero date, throw an exception or do “natural” overflow.
```

**Comment by hrissan** [comment]
Can clickhouse at least do it consistently?

When using toDate in selects, it is very hard to notice errors, when garbage is accepted as valid dates.

Behavior is implemenation-specific, true, but implementation should strive to make it as useful as possible.

Parsing "nice-06-10" as "1970-01-01", but throwing error on "2021-hi-10" is very strange. I doubt very much developers intended it to behave in this way.

**Comment by den-crane** [comment]
блин, вы думаете никто не в курсе что-ли? 
388-й раз никто это не будет обсуждать.
