### ISSUE TITLE
lastMap, firstMap/anyMap, mergeMap/mapMerge for aggregating/merging arrays (like maxMap but for strings and etc)

### ISSUE THREAD

**Issue by morozovsk** [ClickHouse/ClickHouse#21805]
I'm working on [simple backend](https://github.com/amplihouse/amplihouse) for [amplitude sdk](https://github.com/amplitude).
My backend can get events from clients, put it in clickhouse and I can view data in [metabase](https://github.com/metabase/metabase).

**Use case**

I have:

- table events (MergeTree, os, device_id, ...other user properties)
- aggregating materialized view raw_users (AggregatingMergeTree, SimpleAggregateFunction, GROUP BY os, device_id)
- and final aggregating view users (view, SELECT ... GROUP BY os, device_id)

For calculating last users properties I use anyLast, SimpleAggregateFunction(anyLast, String) in mat view and anyLast in final view.

Everything works fine. But ... for each new custom user property I need add new column.

**The solution I'd like**

I woud like to create one new column in table events:
```
customUserPropertiesMap Nested (name String, value String)
```
and one new column in table users:
```
SimpleAggregateFunction(anyLastMap, String, String)
```
and use function:
```
anyLastMap
```
**for example:**
![screenshot_2021-03-17_01:30:36](https://user-images.githubusercontent.com/1822063/111393044-877ea980-86c0-11eb-8ac7-c85f22dc42ea.png)

**Alternatives I'd considered**
I used maxMap but it works only for increased integers.

**Additional context**
```sql
CREATE TABLE amplihouse.events (
	os String,
	device_id String,
	t DateTime,
	event_type String,
	session_start DateTime,
	version String, 
	os_version String, 
	device_manufacturer String, 
	device_model String,
	carrier String,
	language String,
	country String,
	country_code String,
	region String,
	city String,
	ip String
) 
Engine MergeTree PARTITION BY (os, toYYYYMMDD(t)) ORDER BY (device_id);

CREATE MATERIALIZED VIEW amplihouse.raw_users (os String,
	device_id String,
	start SimpleAggregateFunction(min, DateTime),
	end SimpleAggregateFunction(max, DateTime),
	events SimpleAggregateFunction(sum, UInt64),
	sessions SimpleAggregateFunction(groupUniqArrayArray, Array(DateTime)),
	days SimpleAggregateFunction(groupUniqArrayArray, Array(Date)), 
	version SimpleAggregateFunction(anyLast, String),
	start_version SimpleAggregateFunction(any, String),
	os_version SimpleAggregateFunction(anyLast, String),
	device_manufacturer SimpleAggregateFunction(anyLast, String),
	device_model SimpleAggregateFunction(anyLast, String),
	carrier SimpleAggregateFunction(anyLast, String),
	language SimpleAggregateFunction(anyLast, String),
	country SimpleAggregateFunction(anyLast, String),
	country_code SimpleAggregateFunction(anyLast, String),
	region SimpleAggregateFunction(anyLast, String),
	city SimpleAggregateFunction(anyLast, String),
	ip SimpleAggregateFunction(anyLast, String)
) AS SELECT
       os,
       device_id,
       min(t),
       max(t),
       count(),
       groupUniqArray(session_start),
       groupUniqArray(toDate(t)),
       min(version),
       anyLast(device_manufacturer),
       anyLast(device_model),
       anyLast(version),
       anyLast(os_version),
       anyLast(carrier),
       anyLast(language),
       anyLast(country),
       anyLast(country_code),
       anyLast(region),
       anyLast(city),
       anyLast(ip)
FROM amplihouse.events
GROUP BY os, device_id;
ENGINE = AggregatingMergeTree PARTITION BY os ORDER BY device_id;
```

**Comment by UnamedRus** [comment]
-Map aggregation function combinator as more general solution.

https://github.com/ClickHouse/ClickHouse/issues/11721

**Comment by UnamedRus** [comment]
Implemented by https://github.com/ClickHouse/ClickHouse/pull/24539, starting from 21.12

**Comment by alexey-milovidov** [comment]
@UnamedRus But the quality of implementation is in question.
