### ISSUE TITLE
Parse exception for Dictionary with JSONEachRow

### ISSUE THREAD

**Issue by kfirdado** [ClickHouse/ClickHouse#21804]
(you don't have to strictly follow this form)

**Describe the bug**
There is a parsing exception when reading a dictionary from json file formatted as JSONEachRow:
`Code: 27. DB::Exception: Received from localhost:9000. DB::Exception: Cannot parse input: expected '"' before: 'abc", "foo": "1" }\n{ "id": "def", "foo": "2" }\n': (while reading the value of key id).`

**Does it reproduce on recent release?**
Reproduced on version 21.3.2

**How to reproduce**
Create file test.json:
```
{ "id": "abc", "foo": "1" }
{ "id": "def", "foo": "2" }

```

Create dictionary:
```
clickhouse-client --query "
CREATE DICTIONARY test
(
    id String,
    foo String
)
PRIMARY KEY id
SOURCE(FILE(path '/var/lib/clickhouse/user_files/test.json' format 'JSONEachRow'))
LAYOUT(HASHED())
LIFETIME(MIN 5 MAX 15);
"
```

Run test query:
`clickhouse-client --query "SELECT id from test"`

Output:
`Code: 27. DB::Exception: Received from localhost:9000. DB::Exception: Cannot parse input: expected '"' before: 'abc", "foo": "1" }\n{ "id": "def", "foo": "2" }\n': (while reading the value of key id).`

For sanity check, the following query works as expected:
```
clickhouse-client --query "SELECT id FROM file('/var/lib/clickhouse/user_files/test.json', 'JSONEachRow', 'id String, foo String')"
abc
def
```

**Expected behavior**
Parsing of JSONEachRow should work for dictionary the same as it is for table.

**Comment by den-crane** [comment]
(HASHED()) -- layout supports only UInt64 as PRIMARY KEY

You need to use -- COMPLEX_KEY_HASHED
```sql
 CREATE DICTIONARY test
 (
     id String,
     foo String
 )
 PRIMARY KEY id
 SOURCE(FILE(path '/var/lib/clickhouse/user_files/test.json' format 'JSONEachRow'))
 LAYOUT(COMPLEX_KEY_HASHED())
 LIFETIME(MIN 5 MAX 15);

SELECT * FROM test;

┌─id──┬─foo─┐
│ abc │ 1   │
│ def │ 2   │
└─────┴─────┘
SELECT dictGet('dw.test', 'foo', tuple('abc')) AS r

┌─r─┐
│ 1 │
└───┘
```
