### ISSUE TITLE
ninja clickhouse install - error: no matching constructor for initialization of 'DB::MySQLReplication::UpdateRowsEvent' 

### ISSUE THREAD

**Issue by ravil-iskinin** [ClickHouse/ClickHouse#21806]
Make sure that `git diff` result is empty and you've just pulled fresh master. Try cleaning up cmake cache. Just in case, official build instructions are published here: https://clickhouse.yandex/docs/en/development/build/

**Operating system**
OS kind or distribution, specific version/release, non-standard kernel if any. If you are trying to build inside virtual machine, please mention it too.
docker images : yandex/clickhouse-deb-builder:latest 

**Cmake version**
3.16.3

**Ninja version**
1.10.0

**Compiler name and version**
CC=clang-11
CXX=clang++-11

**Full cmake and/or ninja output**
FAILED: utils/check-mysql-binlog/CMakeFiles/check-mysql-binlog.dir/main.cpp.o 
/usr/bin/ccache /usr/bin/clang++-11  -DAWS_SDK_VERSION_MAJOR=1 -DAWS_SDK_VERSION_MINOR=7 -DAWS_SDK_VERSION_PATCH=231 -DBOOST_ASIO_STANDALONE=1 -DCARES_STATICLIB -DENABLE_OPENSSL_ENCRYPTION -DPOCO_ENABLE_CPP11 -DPOCO_HAVE_FD_EPOLL -DPOCO_OS_FAMILY_UNIX -DSTD_EXCEPTION_HAS_STACK_TRACE=1 -DUNALIGNED_OK -DUSE_FASTMEMCPY=1 -DUSE_REPLXX=1 -DWITH_COVERAGE=0 -DWITH_GZFILEOP -DX86_64 -DZLIB_COMPAT -D__CLANG_SUPPORT_DYN_ANNOTATION__ -I../contrib/sentry-native/include -Iincludes/configs -I../src -Isrc -Isrc/Core/include -I../base/mysqlxx/.. -I../contrib/mariadb-connector-c/include -Icontrib/mariadb-connector-c/include -I../base/common/.. -Ibase/common/.. -I../contrib/cityhash102/include -I../contrib/FastMemcpy -I../contrib/cctz/include -Icontrib/zlib-ng -I../contrib/zlib-ng -I../base/pcg-random/. -I../contrib/aws-c-common/include -I../contrib/aws-c-event-stream/include -Icontrib/aws-s3-cmake/include -Icontrib/grpc/third_party/cares/cares -I../contrib/grpc/third_party/cares/cares -I../contrib/abseil-cpp -I../contrib/libuv/include -I../contrib/libpq -I../contrib/libpq/include -isystem ../contrib/libcxx/include -isystem ../contrib/libcxxabi/include -isystem ../contrib/libunwind/include -isystem ../contrib/libpqxx/include -isystem ../contrib/rocksdb/include -isystem ../contrib/orc/c++/include -isystem contrib/orc/c++/include -isystem ../contrib/libhdfs3/include -isystem ../contrib/miniselect/include -isystem ../contrib/pdqsort -isystem ../contrib/llvm/llvm/include -isystem contrib/llvm/llvm/include -isystem ../contrib/AMQP-CPP/include -isystem ../contrib/boringssl/include -isystem ../contrib/boost -isystem ../contrib/poco/Net/include -isystem ../contrib/poco/Foundation/include -isystem ../contrib/poco/NetSSL_OpenSSL/include -isystem ../contrib/poco/Crypto/include -isystem ../contrib/poco/Util/include -isystem ../contrib/poco/JSON/include -isystem ../contrib/poco/XML/include -isystem ../contrib/replxx/include -isystem ../contrib/fmtlib-cmake/../fmtlib/include -isystem ../contrib/fast_float/include -isystem ../contrib/msgpack-c/include -isystem ../contrib/aws/aws-cpp-sdk-s3/include -isystem ../contrib/aws/aws-cpp-sdk-core/include -isystem ../contrib/xz/src/liblzma/api -isystem ../contrib/zstd/lib -isystem ../contrib/re2 -isystem ../contrib/double-conversion -isystem ../contrib/dragonbox/include -isystem contrib/re2_st -isystem ../contrib/croaring/cpp -isystem ../contrib/croaring/include -isystem ../contrib/grpc/include -isystem ../contrib/protobuf/src -isystem src/Server/grpc_protos -isystem ../contrib/libc-headers/x86_64-linux-gnu -isystem ../contrib/libc-headers -fdiagnostics-color=always -std=gnu++2a -fsized-deallocation  -pipe -msse4.1 -msse4.2 -mpopcnt   -Wall -Wno-unused-command-line-argument  -fdiagnostics-absolute-paths -fexperimental-new-pass-manager -Werror -Wextra -Wframe-larger-than=65536 -Wpedantic -Wno-vla-extension -Wno-zero-length-array -Wno-c11-extensions -Wcomma -Wconditional-uninitialized -Wcovered-switch-default -Wdeprecated -Wembedded-directive -Wempty-init-stmt -Wextra-semi-stmt -Wextra-semi -Wgnu-case-range -Winconsistent-missing-destructor-override -Wnewline-eof -Wold-style-cast -Wrange-loop-analysis -Wredundant-parens -Wreserved-id-macro -Wshadow-field -Wshadow-uncaptured-local -Wshadow -Wstring-plus-int -Wundef -Wunreachable-code-return -Wunreachable-code -Wunused-exception-parameter -Wunused-macros -Wunused-member-function -Wzero-as-null-pointer-constant -Weverything -Wno-c++98-compat-pedantic -Wno-c++98-compat -Wno-c99-extensions -Wno-conversion -Wno-ctad-maybe-unsupported -Wno-deprecated-dynamic-exception-spec -Wno-disabled-macro-expansion -Wno-documentation-unknown-command -Wno-double-promotion -Wno-exit-time-destructors -Wno-float-equal -Wno-global-constructors -Wno-missing-prototypes -Wno-missing-variable-declarations -Wno-nested-anon-types -Wno-packed -Wno-padded -Wno-return-std-move-in-c++11 -Wno-shift-sign-overflow -Wno-sign-conversion -Wno-switch-enum -Wno-undefined-func-template -Wno-unused-template -Wno-vla -Wno-weak-template-vtables -Wno-weak-vtables -O3 -DNDEBUG   -D OS_LINUX -nostdinc++ -pthread -MD -MT utils/check-mysql-binlog/CMakeFiles/check-mysql-binlog.dir/main.cpp.o -MF utils/check-mysql-binlog/CMakeFiles/check-mysql-binlog.dir/main.cpp.o.d -o utils/check-mysql-binlog/CMakeFiles/check-mysql-binlog.dir/main.cpp.o -c ../utils/check-mysql-binlog/main.cpp
In file included from ../utils/check-mysql-binlog/main.cpp:1:
In file included from ../contrib/libcxx/include/iostream:37:
In file included from ../contrib/libcxx/include/ios:215:
In file included from ../contrib/libcxx/include/__locale:15:
In file included from ../contrib/libcxx/include/string:507:
In file included from ../contrib/libcxx/include/string_view:175:
In file included from ../contrib/libcxx/include/__string:57:
In file included from ../contrib/libcxx/include/algorithm:643:
/opt/cache/tass/sources/ClickHouse/contrib/libcxx/include/memory:886:28: error: no matching constructor for initialization of 'DB::MySQLReplication::WriteRowsEvent'
        ::new ((void*)__p) _Up(_VSTD::forward<_Args>(__args)...);
                           ^   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/cache/tass/sources/ClickHouse/contrib/libcxx/include/__memory/allocator_traits.h:519:21: note: in instantiation of function template specialization 'std::__1::allocator<DB::MySQLReplication::WriteRowsEvent>::construct<DB::MySQLReplication::WriteRowsEvent, std::__1::shared_ptr<DB::MySQLReplication::TableMapEvent> &, DB::MySQLReplication::EventHeader>' requested here
                __a.construct(__p, _VSTD::forward<_Args>(__args)...);
                    ^
/opt/cache/tass/sources/ClickHouse/contrib/libcxx/include/memory:3360:55: note: in instantiation of function template specialization 'std::__1::__shared_ptr_emplace<DB::MySQLReplication::WriteRowsEvent, std::__1::allocator<DB::MySQLReplication::WriteRowsEvent>>::__shared_ptr_emplace<std::__1::shared_ptr<DB::MySQLReplication::TableMapEvent> &, DB::MySQLReplication::EventHeader>' requested here
    ::new ((void*)_VSTD::addressof(*__guard.__get())) _ControlBlock(__a, _VSTD::forward<_Args>(__args)...);
                                                      ^
/opt/cache/tass/sources/ClickHouse/contrib/libcxx/include/memory:3369:19: note: in instantiation of function template specialization 'std::__1::allocate_shared<DB::MySQLReplication::WriteRowsEvent, std::__1::allocator<DB::MySQLReplication::WriteRowsEvent>, std::__1::shared_ptr<DB::MySQLReplication::TableMapEvent> &, DB::MySQLReplication::EventHeader, void>' requested here
    return _VSTD::allocate_shared<_Tp>(allocator<_Tp>(), _VSTD::forward<_Args>(__args)...);
                  ^
/opt/cache/tass/sources/ClickHouse/utils/check-mysql-binlog/main.cpp:72:26: note: in instantiation of function template specialization 'std::__1::make_shared<DB::MySQLReplication::WriteRowsEvent, std::__1::shared_ptr<DB::MySQLReplication::TableMapEvent> &, DB::MySQLReplication::EventHeader, void>' requested here
            event = std::make_shared<DB::MySQLReplication::WriteRowsEvent>(last_table_map_event, std::move(header));
                         ^
/opt/cache/tass/sources/ClickHouse/src/Core/MySQL/MySQLReplication.h:481:11: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
    class WriteRowsEvent : public RowsEvent
          ^
/opt/cache/tass/sources/ClickHouse/src/Core/MySQL/MySQLReplication.h:481:11: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 2 were provided
/opt/cache/tass/sources/ClickHouse/src/Core/MySQL/MySQLReplication.h:484:9: note: candidate constructor not viable: requires 3 arguments, but 2 were provided
        WriteRowsEvent(std::shared_ptr<TableMapEvent> table_map_, EventHeader && header_, const RowsEventHeader & rows_header)
        ^
In file included from ../utils/check-mysql-binlog/main.cpp:1:
In file included from ../contrib/libcxx/include/iostream:37:
In file included from ../contrib/libcxx/include/ios:215:
In file included from ../contrib/libcxx/include/__locale:15:
In file included from ../contrib/libcxx/include/string:507:
In file included from ../contrib/libcxx/include/string_view:175:
In file included from ../contrib/libcxx/include/__string:57:
In file included from ../contrib/libcxx/include/algorithm:643:
/opt/cache/tass/sources/ClickHouse/contrib/libcxx/include/memory:886:28: error: no matching constructor for initialization of 'DB::MySQLReplication::DeleteRowsEvent'
        ::new ((void*)__p) _Up(_VSTD::forward<_Args>(__args)...);
                           ^   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/cache/tass/sources/ClickHouse/contrib/libcxx/include/__memory/allocator_traits.h:519:21: note: in instantiation of function template specialization 'std::__1::allocator<DB::MySQLReplication::DeleteRowsEvent>::construct<DB::MySQLReplication::DeleteRowsEvent, std::__1::shared_ptr<DB::MySQLReplication::TableMapEvent> &, DB::MySQLReplication::EventHeader>' requested here
                __a.construct(__p, _VSTD::forward<_Args>(__args)...);
                    ^
/opt/cache/tass/sources/ClickHouse/contrib/libcxx/include/memory:3360:55: note: in instantiation of function template specialization 'std::__1::__shared_ptr_emplace<DB::MySQLReplication::DeleteRowsEvent, std::__1::allocator<DB::MySQLReplication::DeleteRowsEvent>>::__shared_ptr_emplace<std::__1::shared_ptr<DB::MySQLReplication::TableMapEvent> &, DB::MySQLReplication::EventHeader>' requested here
    ::new ((void*)_VSTD::addressof(*__guard.__get())) _ControlBlock(__a, _VSTD::forward<_Args>(__args)...);
                                                      ^
/opt/cache/tass/sources/ClickHouse/contrib/libcxx/include/memory:3369:19: note: in instantiation of function template specialization 'std::__1::allocate_shared<DB::MySQLReplication::DeleteRowsEvent, std::__1::allocator<DB::MySQLReplication::DeleteRowsEvent>, std::__1::shared_ptr<DB::MySQLReplication::TableMapEvent> &, DB::MySQLReplication::EventHeader, void>' requested here
    return _VSTD::allocate_shared<_Tp>(allocator<_Tp>(), _VSTD::forward<_Args>(__args)...);
                  ^
/opt/cache/tass/sources/ClickHouse/utils/check-mysql-binlog/main.cpp:79:26: note: in instantiation of function template specialization 'std::__1::make_shared<DB::MySQLReplication::DeleteRowsEvent, std::__1::shared_ptr<DB::MySQLReplication::TableMapEvent> &, DB::MySQLReplication::EventHeader, void>' requested here
            event = std::make_shared<DB::MySQLReplication::DeleteRowsEvent>(last_table_map_event, std::move(header));
                         ^
/opt/cache/tass/sources/ClickHouse/src/Core/MySQL/MySQLReplication.h:489:11: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
    class DeleteRowsEvent : public RowsEvent
          ^
/opt/cache/tass/sources/ClickHouse/src/Core/MySQL/MySQLReplication.h:489:11: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 2 were provided
/opt/cache/tass/sources/ClickHouse/src/Core/MySQL/MySQLReplication.h:492:9: note: candidate constructor not viable: requires 3 arguments, but 2 were provided
        DeleteRowsEvent(std::shared_ptr<TableMapEvent> table_map_, EventHeader && header_, const RowsEventHeader & rows_header)
        ^
In file included from ../utils/check-mysql-binlog/main.cpp:1:
In file included from ../contrib/libcxx/include/iostream:37:
In file included from ../contrib/libcxx/include/ios:215:
In file included from ../contrib/libcxx/include/__locale:15:
In file included from ../contrib/libcxx/include/string:507:
In file included from ../contrib/libcxx/include/string_view:175:
In file included from ../contrib/libcxx/include/__string:57:
In file included from ../contrib/libcxx/include/algorithm:643:
/opt/cache/tass/sources/ClickHouse/contrib/libcxx/include/memory:886:28: error: no matching constructor for initialization of 'DB::MySQLReplication::UpdateRowsEvent'
        ::new ((void*)__p) _Up(_VSTD::forward<_Args>(__args)...);
                           ^   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/cache/tass/sources/ClickHouse/contrib/libcxx/include/__memory/allocator_traits.h:519:21: note: in instantiation of function template specialization 'std::__1::allocator<DB::MySQLReplication::UpdateRowsEvent>::construct<DB::MySQLReplication::UpdateRowsEvent, std::__1::shared_ptr<DB::MySQLReplication::TableMapEvent> &, DB::MySQLReplication::EventHeader>' requested here
                __a.construct(__p, _VSTD::forward<_Args>(__args)...);
                    ^
/opt/cache/tass/sources/ClickHouse/contrib/libcxx/include/memory:3360:55: note: in instantiation of function template specialization 'std::__1::__shared_ptr_emplace<DB::MySQLReplication::UpdateRowsEvent, std::__1::allocator<DB::MySQLReplication::UpdateRowsEvent>>::__shared_ptr_emplace<std::__1::shared_ptr<DB::MySQLReplication::TableMapEvent> &, DB::MySQLReplication::EventHeader>' requested here
    ::new ((void*)_VSTD::addressof(*__guard.__get())) _ControlBlock(__a, _VSTD::forward<_Args>(__args)...);
                                                      ^
/opt/cache/tass/sources/ClickHouse/contrib/libcxx/include/memory:3369:19: note: in instantiation of function template specialization 'std::__1::allocate_shared<DB::MySQLReplication::UpdateRowsEvent, std::__1::allocator<DB::MySQLReplication::UpdateRowsEvent>, std::__1::shared_ptr<DB::MySQLReplication::TableMapEvent> &, DB::MySQLReplication::EventHeader, void>' requested here
    return _VSTD::allocate_shared<_Tp>(allocator<_Tp>(), _VSTD::forward<_Args>(__args)...);
                  ^
/opt/cache/tass/sources/ClickHouse/utils/check-mysql-binlog/main.cpp:86:26: note: in instantiation of function template specialization 'std::__1::make_shared<DB::MySQLReplication::UpdateRowsEvent, std::__1::shared_ptr<DB::MySQLReplication::TableMapEvent> &, DB::MySQLReplication::EventHeader, void>' requested here
            event = std::make_shared<DB::MySQLReplication::UpdateRowsEvent>(last_table_map_event, std::move(header));
                         ^
/opt/cache/tass/sources/ClickHouse/src/Core/MySQL/MySQLReplication.h:497:11: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
    class UpdateRowsEvent : public RowsEvent
          ^
/opt/cache/tass/sources/ClickHouse/src/Core/MySQL/MySQLReplication.h:497:11: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 2 were provided
/opt/cache/tass/sources/ClickHouse/src/Core/MySQL/MySQLReplication.h:500:9: note: candidate constructor not viable: requires 3 arguments, but 2 were provided
        UpdateRowsEvent(std::shared_ptr<TableMapEvent> table_map_, EventHeader && header_, const RowsEventHeader & rows_header)
        ^
3 errors generated.

**Comment by filimonov** [comment]
What version are you trying to build? Do you have submodules updated?

https://github.com/ClickHouse/ClickHouse/commit/ab55556c5e3600528ba8f5e3d54638990b5b3a5b

**Comment by ravil-iskinin** [comment]
I'm trying to build СH tag v21.2.6.1-stable.
Yes, I've updated submodules.
Ок, I will compile and install v21.4.1.6251-testing, also I want to get a stable version with this fix. :))

**Comment by alexey-milovidov** [comment]
You don't have to build all targets (utils), just type
```
ninja clickhouse
```

Then if you want to install ClickHouse, run

```
sudo build/programs/clickhouse install
```

**Comment by ravil-iskinin** [comment]
@alexey-milovidov, Thank  you
