### ISSUE TITLE
Z-Ordering Index

### ISSUE THREAD

**Issue by bakey** [ClickHouse/ClickHouse#21813]
**Use case**
A Z-ordering Index defines an ordering on multi-dimensional data. Data sorted that way can be efficiently filtered by min/max statistics regarding to the columns participating in the ordering.
ClickHouse currently only supports lexicographic ordering or numeric ordering via the order BY clause when create table. This strongly prefers the first column, i.e. given the "ORDER BY (col1, col2, col3)" clause => col1 will be totally ordered (hence filtering on col1 will be very efficient), but values belonging to col2 and col3 will be scattered throughout the data set (hence filtering on col2 or col3 will barely do any good).

**Describe the solution you'd like**
We could extend the syntax of create statement,  e.g. support "ZORDER BY" clause to imply the sorting type.
"ZORDER BY (col1, col2, col3)" would cluster the rows in a way that filtering on col1, col2, or col3 would be equally efficient.

If this looks good.I will participate in this task and submit a pull request.Thanks for review

Reference:
        https://en.wikipedia.org/wiki/Z-order_curve

**Comment by filimonov** [comment]
Please see https://github.com/ClickHouse/ClickHouse/pull/6286

I guess the work is paused there again, right @alexey-milovidov ?

You can definitely collaborate.

**Comment by akuzm** [comment]
It probably doesn't require non-standard grammar. The first step is to create a function `zOrder(lat, lon)`, that takes several numeric values and returns the Z-order value for them. We can index on this function, e.g. `ORDER BY zOrder(lat, lon)`. Then we will teach the query optimizer to deduce restrictions on Z-order range from a test for equality -- e.g. if we have `WHERE lat = <constant> and lon = <constant>`, and the table is `ORDER BY zOrder(lat, lon)`, the query optimizer will deduce the primary key range we have to read. Then we can move to more complex conditions such as inequalities.

**Comment by akuzm** [comment]
A pull request with just the `zOrder` function will be appreciated -- it is relatively easy to do, and I think we already have an implementation somewhere in the old pull requests... We will merge it soon and at least have some progress, which is good because this task is stuck for too long already.
The query optimizer part is more complicated, it will be the next step.

**Comment by alexey-milovidov** [comment]
Yes, the `zOrder` function is fully implemented in #6286
The only remaining part is to finish KeyCondition analysis, that is about 50% implemented.

**Comment by bakey** [comment]
> It probably doesn't require non-standard grammar. The first step is to create a function `zOrder(lat, lon)`, that takes several numeric values and returns the Z-order value for them. We can index on this function, e.g. `ORDER BY zOrder(lat, lon)`. Then we will teach the query optimizer to deduce restrictions on Z-order range from a test for equality -- e.g. if we have `WHERE lat = <constant> and lon = <constant>`, and the table is `ORDER BY zOrder(lat, lon)`, the query optimizer will deduce the primary key range we have to read. Then we can move to more complex conditions such as inequalities.

That make sense.I will follow this method to complete.
So when will the zOrder function of pr #6286 be merged? @alexey-milovidov 
or should I complete the fully function base on this PR ?

**Comment by alexey-milovidov** [comment]
You can extract the existing code from #6286 into a new PR.

**Comment by alexey-milovidov** [comment]
@bakey Are you still working on this?

**Comment by bakey** [comment]
> @bakey Are you still working on this?

Yes, I am still working on this.Something interrupt the development processs last couple of weeks.
I will be dedicated to this issue from now on.Hope can submit MR in a few days

**Comment by alexey-milovidov** [comment]
@hustnn 

You just use `CREATE TABLE ... ORDER BY zCurve(x, y, ...)`
and you need to support these type of functions in KeyCondition.

It is not so hard, and 99% implemented in #4538 by @achulkov2 
Currently, no one is working on this task and it remains open for contributions.

**Comment by alexey-milovidov** [comment]
Closing due to lack of progress.

**Comment by alexey-milovidov** [comment]
#41195
