### ISSUE TITLE
Long-running OPTIMIZE: Timeout exceeded while reading from socket

### ISSUE THREAD

**Issue by lxswbr** [ClickHouse/ClickHouse#21814]
Use Python to connect clickhouse, after each node performs optimize table operation, a single node returns the following exception: Code: 209. DB::NetException. DB::NetException: Timeout exceeded while reading from socket (10.162.89.88:9000): while receiving packet from ck05.jinrong.lycc.qihoo.net:9000, how to solve this

**Comment by filimonov** [comment]
Optimize will be finished anyway (you can see it running in `show processlist`).

Just reconnect or use bigger timeouts.

**Comment by lxswbr** [comment]
The execution is indeed completed. How do I use a longer timeout period, set it during the Python connection or configure it in the clickhouse configuration file? What is the name of the parameter? I set some parameters before and it didn't work.

**Comment by den-crane** [comment]
It depends on python driver. Each driver has own unique timeout settings. Check with a driver's vendor.
