### ISSUE TITLE
ServerException: Code: 241 - DB::Exception: Memory limit (total) exceeded

### ISSUE THREAD

**Issue by SE2AI** [ClickHouse/ClickHouse#21817]
dear authors,

I tried to insert batch number of record (500 records/thread x 6 threads) into clickhouse table, and got the runtime error below:

> clickhouse_driver.errors.ServerException: Code: 241.
> DB::Exception: Memory limit (total) exceeded: would use 56.02 GiB (attempt to allocate chunk of 4219316 bytes), maximum: 56.02 GiB. Stack trace:

This error does not always appear, it means the `insert` could somtimes be performed successfully, sometimes not. I can't figure out why it happened. clickhouse version is 21.1.2.15. moreover, I didn't meet this problem before. Weeks ago, the same insert could be just performed successfully.

By refering to some online QA, I tried to change clickhouse user.xml file, the <_max_memory_usage_> to 50G, but it didn't work.

What does the `chunk of 4219316 bytes` mean? Could you please tell me the reason, and any suggestions to solve this problem? thanks a lot:)

**Comment by filimonov** [comment]
How many columns do the table have? Can you share the schema? Do you have any non-standard settings? 

Do you have some concurrent queries running? Can you check queries memory usage in system.query_log? 

> What does the chunk of 4219316 bytes mean? 

It literały means that during the insert execution clickhouse made an attempt to allocate 4mb of data, getting to the limit.

**Comment by SE2AI** [comment]
The target table has 680 columns, it's a kind of wide-sparse table, and the settings of user.xml and config.xml are same as default. I just curious about that the same test DML could be performed normally before, the test code are the same. Maybe there are some differences of the OS, I run three docker process, only this one difference.

No, there are no concurrent queries, but concurrent insert. The query_log shows:
```
┌─memory_usage─┐
│            0 │
│      4590390 │
│            0 │
│            0 │
│            0 │
│            0 │
│            0 │
│            0 │
│            0 │
│            0 │
│            0 │
│      4529893 │
│            0 │
│            0 │
│            0 │
│            0 │
│            0 │
│            0 │
│            0 │
│            0 │
│            0 │
│            0 │
│            0 │
│            0 │
│            0 │
│            0 │
│            0 │
│            0 │
│            0 │
│            0 │
│   3017264637 │
│   3017275325 │
│   3017271741 │
│   3017267357 │
│   3017263005 │
│   3017263101 │
│            0 │

```

You mean that when allocating 4MB data, it reaches the limit? The memory info is:
```
              total        used        free      shared  buff/cache   available
Mem:            62G        7.0G         46G        2.0G        8.7G         52G
Swap:          4.0G        2.4G        1.6G
```

**Comment by SE2AI** [comment]
Another small question is when I run `clickhouse stop`, the server will start automatically. It seems there is a daemon process. So how to stop the server completely?
btw, this problem appears to CH instance, but it's ok for CH cluster :)

**Comment by filimonov** [comment]
> You mean that when allocating 4MB data, it reaches the limit? 

Yes.
It was "the straw that broke the camel’s back" :) 

So if successfully allocated 50Gb before for other tasks/queries, and when it requested 4Mb more it reached the limit.

**Comment by filimonov** [comment]
```Memory limit (total) exceeded: would use 56.02 GiB```

It does not correspond to 'free 46G'. 

You need to check the memory usage and check query log when issue was happening. 

> No, there are no concurrent queries, but concurrent insert. 

From what i see your single insert requires about 3Gb of RAM. So if you will try to start 19 such inserts simultaneously - you will hit the limit. In practice some amount of RAM is always used by clickhouse itself.

**Comment by SE2AI** [comment]
but I tracked the memory usage, and found it only cost a part of memory, after setting max_memory_usage to 10G，I got the same exception message, even the number are the same **`56.02 GiB (attempt to allocate chunk of 4219316 bytes)`**

**Comment by filimonov** [comment]
> and what do you think about it could run normally before

Have no idea.

> will the docker processes affact it?

If you run 3 docker containers - obviously they will use more RAM altogether, comparing to a single instance.
