### ISSUE TITLE
In MySQL engine, timestamp (6) is converted to DateTime, not DateTime64.

### ISSUE THREAD

**Issue by songgylyx** [ClickHouse/ClickHouse#21820]
See title.

**Comment by filimonov** [comment]
See https://github.com/ClickHouse/ClickHouse/pull/11512#discussion_r450226856

**Comment by kitaisreal** [comment]
Check if `mysql_datatypes_support_level` = `datetime64`. Timestamp(6) is converted to DateTime64(6).
