### ISSUE TITLE
Broken command line suggestions

### ISSUE THREAD

**Issue by tetafro** [ClickHouse/ClickHouse#21829]
**Describe the bug**

Command line suggestions don't work in the latest client version with older server:

```
$ clickhouse-client -h mycluster.com -d mydb -u app --ask-password

ClickHouse client version 21.3.2.5 (official build).
Connecting to database mydb at mycluster.com:9000 as user app.
Connected to ClickHouse server version 20.8.5 revision 54438.

ClickHouse server version is older than ClickHouse client. It may indicate that the server is out of date and can
be upgraded.

mycluster.com :) Cannot load data for command line suggestions: Code: 60, e.displayText() = DB::Exception:
Received from mycluster.com:9000. DB::Exception: Table system.errors doesn't exist..
(version 21.3.2.5 (official build))
```
Though it works well with client 21.2.6.1 (server is the same).

**Does it reproduce on recent release?**

It doesn't reproduce on 20.12 server.

**Comment by alexey-milovidov** [comment]
Yes, it will happen if you connect with newer client to older server.

Workarounds:
- install new server version;
- ignore this message;
- run client without suggestions (`-A` command line argument).

**Comment by alexey-milovidov** [comment]
@azat I thought about this issue when we've added suggestions for system.errors but it does not look important.

**Comment by azat** [comment]
@alexey-milovidov let's try #21943
