### ISSUE TITLE
sequenceMatch: add time window for event chain

### ISSUE THREAD

**Issue by jinghancc** [ClickHouse/ClickHouse#21833]
(you don't have to strictly follow this form)

**Use case**
I want to do funnel analysis based on event data that are stored in ClickHouse. Let's define a few elements for funnel analysis:

- event chain: A (event_id = 1) -> B (event_id = 2) -> C (event_id = 3)

- time period: 0 (event_ms) ~ 500 (event_ms)

- time window: 100 (event_ms)

I want to know, for each user, if there is an event chain (A->B->C) happened within the time period, and intervals between A and C is within the time window.

**Describe the solution you'd like**
`sequenceMatch` seems like a promising candidate for my use case, but currently it can only add time window for two consecutive events, like A -> B, and B -> C, but not for A -> C. I would like to define time window for the whole event chain, it would be nice if you could add this feature.
```sql
SELECT 
  uid, 
  sequenceMatch(t<100)('(?1)(?2)(?3)')(event_ms, event_id = 1, event_id = 2, event_id = 3) funnel
FROM (
  /* emulate test dataset */
  SELECT data.1 event_id, data.2  event_ms, data.3 uid
  FROM (
    SELECT arrayJoin(
      [(1, 100, 123), 
      (1, 120, 123), 
      (1, 130, 123), 
      (1, 150, 345), 
      (1, 180, 345), 
      (2, 150, 123), 
      (2, 200, 234), 
      (2, 140, 345),
      (2, 210, 345),
      (2, 300, 345),
      (3, 180, 123),
      (3, 250, 123),
      (3, 290, 234),
      (3, 270, 345)]) data)
  )
WHERE event_ms >= 0 AND event_ms <= 500 
GROUP BY uid;

Results:
123     1  (100 -> 150 -> 180, 120 -> 150 -> 180, 130 -> 150 -> 180)
234     0
345     1 (180 -> 210 -> 270)
```

**Describe alternatives you've considered**
Currently I use `join` to find all qualified patterns, but it's pretty slow, especially when the dataset is large.
```sql
SELECT
    t1.event_ms, t2.event_ms, t3.event_ms, t4.event_ms,
    t1.uid, t2.uid, t3.uid, t4.uid
FROM
(SELECT 
    uid, event_ms 
FROM funnel_join_test_1
WHERE
    event_id = 1 AND event_ms >= 0 AND event_ms <= 500) as t1
ASOF left join
(SELECT 
    uid, event_ms 
FROM funnel_join_test_1
WHERE
    event_id = 2 AND event_ms >= 0 AND event_ms <= 500) as t2
ON t1.uid = t2.uid AND t1.event_ms  < t2.event_ms
ASOF left join
(SELECT 
    uid, event_ms 
FROM funnel_join_test_1
WHERE
    event_id = 3 AND event_ms >= 0 and event_ms <= 500) as t3
ON t2.uid = t3.uid and t2.event_ms < t3.event_ms
ASOF left join
(SELECT 
    uid, event_ms 
FROM funnel_join_test_1
WHERE
    event_id = 3 AND event_ms >= 0 and event_ms <= 500) as t4
ON t3.uid = t4.uid and t4.event_ms < t1.event_ms + 100
WHERE t4.event_ms > 0;
```

**Additional context**

**Comment by filimonov** [comment]
Did you check windowFunnel function?

**Comment by jinghancc** [comment]
> Did you check windowFunnel function?

@filimonov thanks for the suggestion! I just double checked that function, and that is the one I need! However, the official documentation about `window` parameter is kind of misleading, so I propose a [fix](https://github.com/ClickHouse/ClickHouse/issues/21849) for that, do you think we could make the change?

**Comment by filimonov** [comment]
> > Did you check windowFunnel function?
> 
> @filimonov thanks for the suggestion! I just double checked that function, and that is the one I need! However, the official documentation about `window` parameter is kind of misleading, so I propose a [fix](https://github.com/ClickHouse/ClickHouse/issues/21849) for that, do you think we could make the change?

Sure, it would be simpler/faster if you will just send pull request with proposed change.

**Comment by jinghancc** [comment]
> > > Did you check windowFunnel function?
> > 
> > 
> > @filimonov thanks for the suggestion! I just double checked that function, and that is the one I need! However, the official documentation about `window` parameter is kind of misleading, so I propose a [fix](https://github.com/ClickHouse/ClickHouse/issues/21849) for that, do you think we could make the change?
> 
> Sure, it would be simpler/faster if you will just send pull request with proposed change.

Thanks! Will do!

**Comment by kotik** [comment]
@jinghancc @alexey-milovidov can we close this ticket? `windowFunnel` worked, didn't it?
