### ISSUE TITLE
windowFunnel: same event gets counted twice

### ISSUE THREAD

**Issue by jinghancc** [ClickHouse/ClickHouse#21835]
(you don't have to strictly follow this form)

**Describe the unexpected behaviour**
Test 1: running `windowFunnel` on different events without duplicate timestamp, it works well:
```sql
SELECT
    uid,
    windowFunnel(50)(toUInt32(event_ms), event_id = 1, event_id = 2) AS level
FROM
    (
    /* emulate test dataset */
    SELECT data.1 event_id, data.2  event_ms, data.3 uid
    FROM (
        SELECT arrayJoin(
        [(1, 100, 123),
        (1, 200, 345),
        (1, 210, 345),
        (2, 99, 123),
        (2, 250, 234),
        (2, 230, 345),
        (2, 240, 345)]) data)
    )
WHERE
    event_ms >= 0
    AND event_ms <= 300
GROUP BY
    uid;

Results:
┌─uid─┬─level─┐
│ 123 │     1 │
│ 234 │     0 │
│ 345 │     2 │
└─────┴───────┘
```

Test 2: running `windowFunnel` on different events with duplicate timestamp, it count unexpected event into result.
In this case, user 123 has event 1 and event 2 both happened at 100(event_ms), theoretically, it should not count this match because timestamp of event 2 is not greater than event 1.
```sql
SELECT
    uid,
    windowFunnel(50)(toUInt32(event_ms), event_id = 1, event_id = 2) AS level
FROM
    (
    /* emulate test dataset */
    SELECT data.1 event_id, data.2  event_ms, data.3 uid
    FROM (
        SELECT arrayJoin(
        [(1, 100, 123),
        (1, 200, 345),
        (1, 210, 345),
        (2, 100, 123),
        (2, 250, 234),
        (2, 230, 345),
        (2, 240, 345)]) data)
    )
WHERE
    event_ms >= 0
    AND event_ms <= 300
GROUP BY
    uid;

Results:
┌─uid─┬─level─┐
│ 123 │     2 │
│ 234 │     0 │
│ 345 │     2 │
└─────┴───────┘
```

Test 3: running `windowFunnel` on two same event count all events twice:
```sql
SELECT
    uid,
    windowFunnel(50)(toUInt32(event_ms), event_id = 1, event_id = 1) AS level
FROM
    (
    /* emulate test dataset */
    SELECT data.1 event_id, data.2  event_ms, data.3 uid
    FROM (
        SELECT arrayJoin(
        [(1, 100, 123),
        (1, 200, 345)]) data)
    )
WHERE
    event_ms >= 0
    AND event_ms <= 300
GROUP BY
    uid;

Results:
┌─uid─┬─level─┐
│ 123 │     2 │
│ 345 │     2 │
└─────┴───────┘
```

**How to reproduce**: run SQL query pasted above
* Which ClickHouse server version to use: 21.2.3.15
* Which interface to use, if matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

**Expected behavior**
When searching for qualified event chain, it should satisfy: 
**timestamp of first event < timestamp of second event <= timestamp of first event + window**

I guess currently it follows:
timestamp of first event <= timestamp of second event <= timestamp of first event + window

With that, Test 2 will generate results:
```
┌─uid─┬─level─┐
│ 123 │     1 │
│ 234 │     0 │
│ 345 │     2 │
└─────┴───────┘
```

Test 3 will generate results:
```
┌─uid─┬─level─┐
│ 123 │     1 │
│ 345 │     1 │
└─────┴───────┘

```

**Error message and/or stacktrace**

**Additional context**

**Comment by ucasFL** [comment]
Maybe introduced in #18884.

**Comment by jinghancc** [comment]
> Maybe introduced in #18884.

Hi @ucasFL , thanks for finding the related PR! But I guess this issue existed before this PR because duplicate events cannot be avoided by changing sorting method. 

I wonder if we should change logic [here](https://github.com/ClickHouse/ClickHouse/blob/master/src/AggregateFunctions/AggregateFunctionWindowFunnel.h#L199)
from 
```
else if (events_timestamp[event_idx - 1] >= 0 && timestamp <= events_timestamp[event_idx - 1] + window)
```
to
```
else if (events_timestamp[event_idx - 1] >= 0 && timestamp > events_timestamp[event_idx - 1] && timestamp <= events_timestamp[event_idx - 1] + window)
```
so that only when timestamp of current event strictly greater than previous event, can we update the events_timestamp.

**Comment by jinghancc** [comment]
Proposal: we could add a new mode called `strictly increasing` to avoid duplicate timestamps, so that we change the matching pattern from
```
timestamp of cond1 <= timestamp of cond2 <= ... <= timestamp of condN <= timestamp of cond1 + window.
```
to
```
timestamp of cond1 < timestamp of cond2 < ... < timestamp of condN <= timestamp of cond1 + window.
```
@sundy-li @filimonov does that sound like a valid way to you?

**Comment by sundy-li** [comment]
I think the test 2 case is reasonable. It's using stable sort, so    (1, 100, 123) ->  (2, 100, 123) results to level 2.
       
I test these 3 cases in 20.3, and it works well, I did not catch the latest options like `strict` and `strict_order`.  Maybe some changes broker this function.

**Comment by jinghancc** [comment]
> I think the test 2 case is reasonable. It's using stable sort, we can accept some timestamp by default (not in strict mode), so (1, 100, 123) -> (2, 100, 123) results to level 2.
> 
> I test these 3 cases in 20.3, and it works well, I did not catch the latest options like `strict` and `strict_order`. Maybe some changes broker this function.

Hi @sundy-li , thanks for looking into this issue! My ClickHouse version is 21.2.3.15, so it's possible that new changes introduced this unexpected behavior. 
Do you think it's reasonable to introduce a new mode to make the timestamp `strictly increasing` to avoid counting duplicate timestamps into result?

**Comment by vdimir** [comment]
> Do you think it's reasonable to introduce a new mode to make the timestamp `strictly increasing` to avoid counting duplicate timestamps into result?

I think adding such option may be possible, but it seems that function will do some additional work (filtering), for which it is not responsible. Why filtering rows with non-unique timestamp before applying this function is not possible? For example with `GROUP BY`

**Comment by LukeHarrimanHQ** [comment]
Agreed - I am trying to do number 3 as well.

**Comment by BrandesEric** [comment]
We are still seeing this problem too (number 3).  This is a pretty significant issue to make windowFunnel actually work intuitively.

**Comment by DerekChia** [comment]
Number 2 and 3 work as expected in the latest LTS 24.8 after adding the option 'strict_increase'. 

Number 2 - https://fiddle.clickhouse.com/54c452a5-52fc-4f83-984f-2eba56eef3e4
Number 3 - https://fiddle.clickhouse.com/edf516d6-195d-47e7-b09a-de6aa48d1c40

I suggest we close this?
