### ISSUE TITLE
Distributed does not see existing MergeTree table from another shard

### ISSUE THREAD

**Issue by uriyger** [ClickHouse/ClickHouse#2184]
We have 4 nodes: 2 shard and 2 replicas in our cluster
Right after creating 4 new MergeTree tables and 4 Distributed tables - all is ok
But  in period from 2 hours to 12 hours distributed table on the 1st node  starts to show an error, sometimes it appears on another node:

We have up to 10 tables without this problem, except recent 3 tables 

Our Structure:
shard 1:  db1, db3
shard 2: db2, db4

Error message:
```
SELECT count(*) FROM distributed_table 

Received exception from server (version 1.1.54370):
Code: 279. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::NetException. DB::NetException: All connection tries failed. Log: 

There is no table .merge_tree_table on server: db2_host:9000
There is no table .merge_tree_table on server: db4_host:9000
```
Database is selected before query or can be specified directly in query it's doesn't matter. Error message is the same.  "There is no table .merge_tree_table ..."

I can successfully send query to mergeTree table on every node

After dropping distributed table and creating again, error is gone for a while but then appears again.

We use this structure on production for 1 year

UPD: We found workaround, the problem occurs only in case when Distributed table was created  using currentDatabase() in create statement

Since We specified explicit DB name in create statement, the error is gone

**Comment by uriyger** [comment]
I updated description, the problem is actual only for tables created using currentDatabase()

**Comment by filimonov** [comment]
Related #6104

**Comment by filimonov** [comment]
Closing in advance to #6104
