### ISSUE TITLE
mac build 21.3.2.5-lts faild

### ISSUE THREAD

**Issue by feidaodalian** [ClickHouse/ClickHouse#21867]
$ cmake .. -DCMAKE_C_COMPILER=`brew --prefix llvm`/bin/clang -DCMAKE_CXX_COMPILER=`brew --prefix llvm`/bin/clang++ -DCMAKE_PREFIX_PATH=`brew --prefix llvm`
I want to use clang 11.
but return question :
`CMake Error at /usr/local/Cellar/cmake/3.19.7/share/cmake/Modules/CMakeTestCCompiler.cmake:66 (message):
  The C compiler

    "/usr/local/opt/llvm/bin/clang"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /Users/xufei3/cworkspace/JacDB/build/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/local/bin/ninja cmTC_9b6e6 && [1/2] Building C object CMakeFiles/cmTC_9b6e6.dir/testCCompiler.c.o
    [2/2] Linking C executable cmTC_9b6e6
    FAILED: cmTC_9b6e6 
    : && /usr/local/opt/llvm/bin/clang -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/cmTC_9b6e6.dir/testCCompiler.c.o -o cmTC_9b6e6   && :
    ld: unknown option: -platform_version
    clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
    ninja: build stopped: subcommand failed.`

my install llvm 
`ZBMAC-2VX14CHTD:build xufei3$ /usr/local/opt/llvm/bin/clang --version
clang version 11.1.0
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /usr/local/opt/llvm/bin`
but it mybe use /usr/bin 
I can use cmake.. success.
`ZBMAC-2VX14CHTD:build xufei3$ /usr/bin/clang --version
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin`

**Comment by abyss7** [comment]
What is your `ld` version is?

**Comment by alexey-milovidov** [comment]
Duplicate #21904
