### ISSUE TITLE
Can't insert row into table with Decimal column using JSONEachRow format

### ISSUE THREAD

**Issue by iassasin** [ClickHouse/ClickHouse#21875]
**Describe the bug**
When trying to insert into table with decimal from json clickhouse produces unexpected and non-clear error.

**Does it reproduce on recent release?**
Yes. Reproduced at v21.3.2.5. And v20.6.x+ reproduces too.

**How to reproduce**
Clickhouse version v21.3.2.5
Client doesn't matter. I use CLI.
```
CREATE TABLE test2(id Decimal(18, 4)) ENGINE = MergeTree() ORDER BY id
INSERT INTO test2 FORMAT JSONEachRow {"id":"0.00"}

DB::ParsingException: Cannot parse input: expected ',' before: '"0.00"}': (at row 1)
```

**Expected behavior**
Row inserted to table

**Error message and/or stacktrace**
```
Code: 27, e.displayText() = DB::ParsingException: Cannot parse input: expected ',' before: '"0.00"}': (at row 1)
, Stack trace (when copying this message, always include the lines below):

0. DB::throwAtAssertionFailed(char const*, DB::ReadBuffer&) @ 0x86660a5 in /usr/bin/clickhouse
1. DB::JSONEachRowRowInputFormat::advanceToNextKey(unsigned long) @ 0xf9a5b54 in /usr/bin/clickhouse
2. DB::JSONEachRowRowInputFormat::readJSONObject(std::__1::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn> > >&) @ 0xf9a5718 in /usr/bin/clickhouse
3. DB::JSONEachRowRowInputFormat::readRow(std::__1::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn> > >&, DB::RowReadExtension&) @ 0xf9a6476 in /usr/bin/clickhouse
4. DB::IRowInputFormat::generate() @ 0xf969358 in /usr/bin/clickhouse
5. DB::ISource::tryGenerate() @ 0xf8f7df5 in /usr/bin/clickhouse
6. DB::ISource::work() @ 0xf8f79ea in /usr/bin/clickhouse
7. DB::ParallelParsingInputFormat::InternalParser::getChunk() @ 0xf9bff9e in /usr/bin/clickhouse
8. DB::ParallelParsingInputFormat::parserThreadFunction(std::__1::shared_ptr<DB::ThreadGroupStatus>, unsigned long) @ 0xf9bf5fe in /usr/bin/clickhouse
9. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0x8652408 in /usr/bin/clickhouse
10. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()&&...)::'lambda'()::operator()() @ 0x86543bf in /usr/bin/clickhouse
11. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x864f9df in /usr/bin/clickhouse
12. ? @ 0x8653473 in /usr/bin/clickhouse
13. start_thread @ 0x76ba in /lib/x86_64-linux-gnu/libpthread-2.23.so
14. __clone @ 0x1074dd in /lib/x86_64-linux-gnu/libc-2.23.so
 (version 21.3.2.5 (official build))
Code: 27, e.displayText() = DB::ParsingException: Cannot parse input: expected ',' before: '"0.00"}': (at row 1)
, Stack trace (when copying this message, always include the lines below):

0. DB::throwAtAssertionFailed(char const*, DB::ReadBuffer&) @ 0x86660a5 in /usr/bin/clickhouse
1. DB::JSONEachRowRowInputFormat::advanceToNextKey(unsigned long) @ 0xf9a5b54 in /usr/bin/clickhouse
2. DB::JSONEachRowRowInputFormat::readJSONObject(std::__1::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn> > >&) @ 0xf9a5718 in /usr/bin/clickhouse
3. DB::JSONEachRowRowInputFormat::readRow(std::__1::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn> > >&, DB::RowReadExtension&) @ 0xf9a6476 in /usr/bin/clickhouse
4. DB::IRowInputFormat::generate() @ 0xf969358 in /usr/bin/clickhouse
5. DB::ISource::tryGenerate() @ 0xf8f7df5 in /usr/bin/clickhouse
6. DB::ISource::work() @ 0xf8f79ea in /usr/bin/clickhouse
7. DB::ParallelParsingInputFormat::InternalParser::getChunk() @ 0xf9bff9e in /usr/bin/clickhouse
8. DB::ParallelParsingInputFormat::parserThreadFunction(std::__1::shared_ptr<DB::ThreadGroupStatus>, unsigned long) @ 0xf9bf5fe in /usr/bin/clickhouse
9. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0x8652408 in /usr/bin/clickhouse
10. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()&&...)::'lambda'()::operator()() @ 0x86543bf in /usr/bin/clickhouse
11. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x864f9df in /usr/bin/clickhouse
12. ? @ 0x8653473 in /usr/bin/clickhouse
13. start_thread @ 0x76ba in /lib/x86_64-linux-gnu/libpthread-2.23.so
14. __clone @ 0x1074dd in /lib/x86_64-linux-gnu/libc-2.23.so
 (version 21.3.2.5 (official build))
```

**Comment by den-crane** [comment]
JSONEachRow is not JSON. 

JSONEachRow expects `{"id":0.00}`

**Comment by iassasin** [comment]
@den-crane but why? At least error message seems incorrect in this case. It says that can't parse json and expecting comma, but json is valid. Also in documentation nothing about this.
Last and important point - if it will stringified or parsed from float value, for decimal it can be precision-loss, so transfer it as string value looks like best choice.

**Comment by den-crane** [comment]
JSONEachRow is a text format. 
0.00 - string representation, it's parsed as Decimal.

**Comment by iassasin** [comment]
For example in NodeJS to achieve this string representation of decimal in json-string I'll need to use custom json stringification function instead of built-in `JSON.stringify`. Also in JSON specification it is not actually string, it is number (see section "Numbers" [here](https://www.ecma-international.org/wp-content/uploads/ECMA-404_2nd_edition_december_2017.pdf)). And number when parsed can loss precision in most json libraries.
You really say that precision loss for Decimal is expected behavior while importing/exporting data in clickhouse?

**Comment by den-crane** [comment]
>You really say that precision loss for Decimal is expected behavior while importing/exporting data in clickhouse?

the opposite.

```sql
CREATE TABLE test2(id Decimal(38, 18), id1 Float64) ENGINE = MergeTree() ORDER BY id　;
INSERT INTO test2 FORMAT JSONEachRow {"id":111111.111111111111111111, "id1":111111.111111111111111111}　;

SELECT * FROM test2
┌────────────────────────id─┬────────────────id1─┐
│ 111111.111111111111111111 │ 111111.11111111111 │
└───────────────────────────┴────────────────────┘
```

You can use input function and cast data
```sql
INSERT INTO test2 SELECT cast(id as Decimal(38, 18)), cast(id1 as Float64) from input('id String, id1 String') FORMAT JSONEachRow {"id":"111111.111111111111111111", "id1":"111111.111111111111111111"}　;

SELECT * FROM test2
┌────────────────────────id─┬────────────────id1─┐
│ 111111.111111111111111111 │ 111111.11111111111 │
│ 111111.111111111111111111 │ 111111.11111111111 │
└───────────────────────────┴────────────────────┘
```

**Comment by iassasin** [comment]
May be I something misunderstand, but this cast `cast(id1 as Float64)` is precision lossy in general case. But now I can't provide an example of value wich show this loss. Thanks for answers.

**Comment by den-crane** [comment]
@iassasin 

еще раз JSONEachRow это не JSON. Забудьте на секунду про существование JSON. Чем вы там генерите текстовый файл и какие там проблемы вне скоупа Кликхауз.

JSONEachRow это особый текстовый формат, который издалека напоминает JSON.

И вот у нас есть текст "id":111111.111111111111111111, 
тут не может быть потери точности -- это текст.
Когда КХ внутри парсит текст 111111.111111111111111111 для  Decimal(18, 4) он парсит это как текст. КХ не ожидает тут кавычек, потому что JSONEachRow.

**Comment by den-crane** [comment]
cast(id1 as Float64) был приведен как пример потери точности в доказательство что Decimal при парсинге как раз наоборот ничего не теряет

**Comment by iassasin** [comment]
> JSONEachRow это не JSON
Ок, теперь я понял свою ошибку, сначала я подумал, что вы про форматы КХ JSON и JSONEachRow, а тут речь именно про сам формат JSON. Правда из документации этот тонкий момент совсем не очевиден :(
Теперь я понял и пример с потерей точности, это, конечно, рабочий вариант, но в моем случае придется из-за двух колонок все 20 в запросе так явно прописывать, не очень удобно.

В целом я вижу тут два момента:
1. Изменить сообщение об ошибке для кейса из моего примера. Ну совсем не очевидно, что никакая запятая тут не при чем.
2. Или все-таки добавить в JSONEachRow поддержку парсинга числа в том числе из кавычек. Если это работает с явным кастом из строки в Decimal, то было бы здорово облегчить задачу и парсить сразу в кавычках, как в первом посте.

Эти моменты не могут являться основанием для создания issue?

**Comment by den-crane** [comment]
Делать вы можете любые тикеты, только не bug, а feature request.

Подозреваю все эти проблемы из-за супербыстрого парсинга.
Да можно выводить нормальную ошибку, но тогда надо больше cpu тратить на if else if, это деньги на лишние сервера и электричество (я не шучу).

**Comment by iassasin** [comment]
> но тогда надо больше cpu тратить на if else if, это деньги на лишние сервера и электричество

Согласен, платить больше никому не хочется. Еще раз спасибо за ответы.
