### ISSUE TITLE
ALTER TABLE foo MATERIALIZE COLUMN bar

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#21885]
More natural way to init column values for the past data (instead of ugly `ALTER TABLE foo UPDATE bar=bar WHERE 1`) 

Should work for parts where column does not exists, also should work with MATERIALIZED columns.

Supersedes https://github.com/ClickHouse/ClickHouse/issues/19785

**Comment by macobo** [comment]
It would be ideal if this could only materialize data in certain parts as with `OPTIMIZE`.

See also https://github.com/ClickHouse/ClickHouse/issues/21885 (sorry, discovered this issue after creating my own)

**Comment by UnamedRus** [comment]
PR https://github.com/ClickHouse/ClickHouse/pull/27038
