### ISSUE TITLE
Cannot use LDAP authentication for users that are not bind users

### ISSUE THREAD

**Issue by rlazimi-dev** [ClickHouse/ClickHouse#21893]
**Describe the bug**
I am trying to use LDAP as an external authenticator. I am expecting to be able to authenticate with a user that is not a bind user.

**How to reproduce**
ClickHouse version: 21.3.2.5

given configuration:
```
<yandex>

    <!-- ... -->
    <ldap_servers>

        <ldap_test>
            <host>ldap.test.co</host>
            <port>636</port>
            <bind_dn>uid=bind_user,cn=users,cn=accounts,dc=test,dc=com</bind_dn>
            <verification_cooldown>300</verification_cooldown>
            <enable_tls>yes</enable_tls>
            <tls_require_cert>never</tls_require_cert>
        </ldap_test>

    </ldap_servers>


    <user_directories>

        <ldap>
            <server>ldap_test</server>
            <roles>
                 <test_admin />
            </roles>
            <role_mapping>
                <base_dn>cn=users,cn=accounts,dc=test,dc=com</base_dn>
                <scope>subtree</scope>
                <search_filter>(uid={0})</search_filter>
                <attribute>uid</attribute>
            </role_mapping>
        </ldap>

      <!-- ... -->
    </user_directories>

</yandex>
```

and given command:
```
clickhouse-client --user 'rlazimi-dev' --password <password> --query "select 1"
```

and suppose `rlazimi-dev` is a user in LDAP (and does not appear anywhere in clickhouse), that is not a bind user

and suppose anonymous binding in my LDAP server is not allowed.

**Expected behavior**
I expect that the query will run without giving me an authentication error.

**Comment by traceon** [comment]
Your configuration doesn't look correct.

Firts, the ldap server should be configured like this:
```xml
    <ldap_servers>

        <ldap_test>
            <host>ldap.test.co</host>
            <port>636</port>
            <bind_dn>uid={user_name},cn=users,cn=accounts,dc=test,dc=com</bind_dn>
            <verification_cooldown>300</verification_cooldown>
            <enable_tls>yes</enable_tls>
            <tls_require_cert>never</tls_require_cert>
        </ldap_test>

    </ldap_servers>
```

Here, `{user_name}` will be replaced with the actual user name.

Then, you need a filter that returns entries that contain group name in one of the attributes, for role mapping. What you do doesn't look correct. Why you extract `uid` here? `{0}` is not a recognized placeholder either.
```xml
            <role_mapping>
                <base_dn>cn=users,cn=accounts,dc=test,dc=com</base_dn>
                <scope>subtree</scope>
                <search_filter>(uid={0})</search_filter>
                <attribute>uid</attribute>
            </role_mapping>
```

**Comment by traceon** [comment]
> and suppose rlazimi-dev is a user in LDAP (and does not appear anywhere in clickhouse), that is not a bind user
> and suppose anonymous binding in my LDAP server is not allowed.

The bind will be performed on behalf of  `rlazimi-dev`, and group search will be done while bound as `rlazimi-dev`. "Admin" user is not required, nor supported.

**Comment by rlazimi-dev** [comment]
Thanks for the insight.

```<bind_dn>uid=bind_user,cn=users,cn=accounts,dc=test,dc=com</bind_dn>```

I deliberately hardcoded the username here because I want a specific account to perform binding (my LDAP does not allow anonymous binding)

> Then, you need a filter that returns entries that contain group name in one of the attributes, for role mapping. What you do doesn't look correct. Why you extract uid here? {0} is not a recognized placeholder either.

What exactly do you mean by "group name in one of the attributes, for role mapping"? Can you show me an exact example, I don't have too much experience with LDAP, so it will help if you can make a quick LDAP example entry as well.

**Comment by traceon** [comment]
> I deliberately hardcoded the username here because I want a specific account to perform binding (my LDAP does not allow anonymous binding). I want other users, that are not allowed to bind, to still log in however.

The config I suggested doesn't rely on anonymous binding. The Bind DN will be constructed for each user by replacing `{user_name}` with user name. When `rlazimi-dev` is trying to authenticate, the following BindDN will be constructed: `uid=rlazimi-dev,cn=users,cn=accounts,dc=test,dc=com`.

> What exactly do you mean by "group name in one of the attributes, for role mapping"? Can you show me an exact example, I don't have too much experience with LDAP, so it will help if you can make a quick LDAP example entry as well.

Here is a working example, for cases when users are grouped in `groupOfNames` entries and referenced by `member` attributes in them. The value of `cn` attribute from such groups will be used as a role name (after `clickhouse_` prefix is removed.)

https://github.com/ClickHouse/ClickHouse/blob/95c87d4dedf2c33ba09fe0f8c36971875de03d99/programs/server/config.xml#L432-L438

See the comments/documentation and examples in this `config.xml` file, both, for ldap user directory and ldap server sections.

Also, see the documentation draft [External authentication mechanism support in ClickHouse ](https://gist.github.com/traceon/d922c8452e8065b86667168578dc5c12).

**Comment by rlazimi-dev** [comment]
Hi @traceon, I'd like to come back to this issue.

> ... The Bind DN will be constructed for each user by replacing {user_name} with user name. When rlazimi-dev is trying to authenticate, the following BindDN will be constructed: uid=rlazimi-dev,cn=users,cn=accounts,dc=test,dc=com.

My issue is that in my case, `rlazimi-dev` is not allowed to be a bind user in ldap. I have another bind user that I'd instead like to use for binding, and only after binding I'd like to access `rlazimi-dev`'s permissions for the query.

For example:
1. given the following command: `clickhouse-client --user 'rlazimi-dev' --password <password> --query "select 1"`
2. I'd like my bind dn to be: `uid=bind_user,cn=users,cn=accounts,dc=test,dc=com`
3. and my permissions to be those of: `rlazimi-dev`

in step 2, bind_user's password would be stored encrypted somewhere in configuration for example

**Comment by traceon** [comment]
This is problematic, as a different configuration will be required, with a stored bind user password in plain text, a separate search filter for locating login user DN, and then an ability to manually encode and match passwords to hashes stored in LDAP. This is overly complicated, unsafe, and overall not very viable setup to have a configuration support for. At the time of implementing LDAP support, this was one of the potential cases, and we decided against adding support for this.

**Comment by rlazimi-dev** [comment]
You bring up a good point. However, I do think it will be a good feature, as I am unable to change my ldap server to allow for anonymous binding.

Although I mentioned keeping the password in the configuration in the example, I think a more secure way to implement this is to ask for bind credentials alongside the normal credentials then to handle the bind credentials in the CH server – this means they're treated with the same security.

For example:
```
clickhouse-client \
  --user 'rlazimi-dev' \
  --password <password> \
  --bind-user 'bind-user' \
  --bind-password <password1> \
  --query "select 1"
```

**Comment by traceon** [comment]
> I am unable to change my ldap server to allow for anonymous binding

You don't have to allow anonymous binding (you need to actually forbid it). Instead, you should configure the LDAP server in a way it actually able to authenticate the registered users by allowing them to bind using their credentials.

**Comment by rlazimi-dev** [comment]
Hi @traceon, I am able to authenticate with my LDAP user, with anonymous binding forbidden, using the configuration tips you provided - thanks!
