### ISSUE TITLE
How to accelerate update querys

### ISSUE THREAD

**Issue by SE2AI** [ClickHouse/ClickHouse#21898]
In my case, I build a table with 12M data and 600 partitions，and test the performance of single-record update per second.

I try both situations:

1. 100 concurrent single-update in one partition, only one column value changed for each update.
2. 100 concurrent single-update in 100 partition(1 update for 1 partition), only one column value changed for each update.

In both situations, the 100 update could be completed after about 3~4min, which means update efficiency is about ~0.3 record per second. 

So, how to improve update performance? actually 100 single-record-update per second would be ok for me. Are there any important configurations or best practice guide?

**Comment by den-crane** [comment]
You do understand that Clickhouse does not support updates as daily-basis operations?
Alter update / delete are designed for rare admin operations like GDPR.
Try ReplacingMergeTree / CollapsingMErgeTree / external dictionaries instead of alter.
