### ISSUE TITLE
Recent ClickHouse versions seem to be having problems with `remote_servers` substitution

### ISSUE THREAD

**Issue by mic4ael** [ClickHouse/ClickHouse#21905]
**Describe the unexpected behaviour**
`remote_servers` substition doesn't seem to be respected.

**How to reproduce**
Problematic ClickHouse version: 21.2
The last good version: 20.x
Tested this on two docker containers: `yandex/clickhouse-server:21.2` (bad), `yandex/clickhouse-server:20.8.9.6` (good)

`/etc/clickhouse-server/config.d/config.xml`
```xml
<yandex>
    <path>/var/lib/clickhouse/</path>
    <tmp_path>/var/lib/clickhouse/tmp/</tmp_path>
    <user_files_path>/var/lib/clickhouse/user_files/</user_files_path>
    <format_schema_path>/var/lib/clickhouse/format_schemas/</format_schema_path>

    <include_from>/etc/clickhouse-server/metrica.d/metrica.xml</include_from>

    <users_config>users.xml</users_config>

    <display_name>RELEASE-NAME-clickhouse</display_name>
    <listen_host>0.0.0.0</listen_host>
    <http_port>8123</http_port>
    <tcp_port>9000</tcp_port>
    <interserver_http_port>9009</interserver_http_port>
    <max_connections>4096</max_connections>
    <keep_alive_timeout>3</keep_alive_timeout>
    <max_concurrent_queries>100</max_concurrent_queries>
    <uncompressed_cache_size>8589934592</uncompressed_cache_size>
    <mark_cache_size>5368709120</mark_cache_size>
    <timezone>UTC</timezone>
    <umask>022</umask>
    <mlock_executable>false</mlock_executable>
    <remote_servers incl="clickhouse_remote_servers" optional="true" />
    <zookeeper incl="zookeeper-servers" optional="true" />
    <macros incl="macros" optional="true" />
    <builtin_dictionaries_reload_interval>3600</builtin_dictionaries_reload_interval>
    <max_session_timeout>3600</max_session_timeout>
    <default_session_timeout>60</default_session_timeout>
    <disable_internal_dns_cache>1</disable_internal_dns_cache>

    <query_log>
        <database>system</database>
        <table>query_log</table>
        <partition_by>toYYYYMM(event_date)</partition_by>
        <flush_interval_milliseconds>7500</flush_interval_milliseconds>
    </query_log>

    <query_thread_log>
        <database>system</database>
        <table>query_thread_log</table>
        <partition_by>toYYYYMM(event_date)</partition_by>
        <flush_interval_milliseconds>7500</flush_interval_milliseconds>
    </query_thread_log>

    <distributed_ddl>
        <path>/clickhouse/task_queue/ddl</path>
    </distributed_ddl>
    <logger>
        <level>trace</level>
        <log>/var/log/clickhouse-server/clickhouse-server.log</log>
        <errorlog>/var/log/clickhouse-server/clickhouse-server.err.log</errorlog>
        <size>1000M</size>
        <count>10</count>
    </logger>
</yandex>
```

`/etc/clickhouse-server/metrica.d/metrica.xml`

```xml
<?xml version="1.0"?>
<yandex>
    <clickhouse_remote_servers>
        <RELEASE-NAME-clickhouse>
            <shard>
                <replica>
                    <internal_replication>true</internal_replication>
                    <host>RELEASE-NAME-clickhouse-0.RELEASE-NAME-clickhouse-headless.sentry.svc.cluster.local</host>
                    <port>9000</port>
                    <user>default</user>
                    <compression>true</compression>
                </replica>
            </shard>
            <shard>
                <replica>
                    <internal_replication>true</internal_replication>
                    <host>RELEASE-NAME-clickhouse-1.RELEASE-NAME-clickhouse-headless.sentry.svc.cluster.local</host>
                    <port>9000</port>
                    <user>default</user>
                    <compression>true</compression>
                </replica>
            </shard>
            <shard>
                <replica>
                    <internal_replication>true</internal_replication>
                    <host>RELEASE-NAME-clickhouse-2.RELEASE-NAME-clickhouse-headless.sentry.svc.cluster.local</host>
                    <port>9000</port>
                    <user>default</user>
                    <compression>true</compression>
                </replica>
            </shard>
        </RELEASE-NAME-clickhouse>
    </clickhouse_remote_servers>
</yandex>
```

I noticed that there are some changes in `/etc/clickhouse-server/config.xml` between these versions that might have something to do with this issue. Namely:

(good)
```xml
<remote_servers incl="clickhouse_remote_servers" >
```

(bad)
```xml
<remote_servers>
```

**Expected behavior**
`cluster` is created. On a good version of `Clickhouse` `RELEASE-NAME-clickhouse` cluster is available (`select * from system.clusters`) and its definition is available in the `preprocessed_configs`. On a bad version for some reason the cluster is missing.

**Error message and/or stacktrace**
None.

**Comment by den-crane** [comment]
It was intentional https://github.com/ClickHouse/ClickHouse/pull/18740 ?

So you saying that even implicit incl does not work anymore?

```
/etc/clickhouse-server/config.d/config.xml
    <remote_servers incl="clickhouse_remote_servers" optional="true" />
```

You don't need metrica.xml or incl for remote_servers (incl useful for repeating settings like passwords for dictionaries)
Just place rs.xml into config.d

```
cat /etc/clickhouse-server/config.d/clusters.xml


<?xml version="1.0" ?>
<yandex>
    <remote_servers>
        <RELEASE-NAME-clickhouse>
            <shard>
                <replica>
                    <internal_replication>true</internal_replication>
                    <host>RELEASE-NAME-clickhouse-0.RELEASE-NAME-clickhouse-head...

```

**Comment by mic4ael** [comment]
> It was intentional #18740 ?
> 
> So you saying that even implicit incl does not work anymore?
> 
> ```
> /etc/clickhouse-server/config.d/config.xml
>     <remote_servers incl="clickhouse_remote_servers" optional="true" />
> ```
> 
> BTW, You don't need metrica.xml or incl for remote_servers (incl useful for repeating settings like passwords for dictionaries)
> Just place rs.xml into config.d
> 
> ```
> cat /etc/clickhouse-server/config.d/clusters.xml
> 
> 
> <?xml version="1.0" ?>
> <yandex>
>     <remote_servers>
>         <RELEASE-NAME-clickhouse>
>             <shard>
>                 <replica>
>                     <internal_replication>true</internal_replication>
>                     <host>RELEASE-NAME-clickhouse-0.RELEASE-NAME-clickhouse-head...
> ```

Hey, yeah. That is what i basically did. But I am curious whether `incl` is still supported. Did the behaviour change between major releases?

**Comment by alexey-milovidov** [comment]
`incl` is still supported.
We only removed it from the default configuration.

**Comment by mic4ael** [comment]
But this still doesn't explain why my configuration was not respected. I don't think this should be closed since for some reason I am still experiencing the problem on the versions 21.x

**Comment by mic4ael** [comment]
The configuration which works on 20.8.x should also work on 21.2.x, right? For some reason it doesn't

**Comment by den-crane** [comment]
I'll check incl

**Comment by den-crane** [comment]
@alexey-milovidov it seems incl works only for the first section occurrence ?

config.xml has remote_servers with test clusters.

If I add to `/etc/clickhouse-server/config.d/config.xml` this `<remote_servers incl="clickhouse_remote_servers" />`
then inclusion does not work.

If add the same but with replace="true"  (or with replace="false" ?) like this `<remote_servers incl="clickhouse_remote_servers" replace="true" />` then everything works (but of course test clusters replaced).
