### ISSUE TITLE
JDBC driver / specific HTTP clients: Chunk size is too large error when executing an "INSERT INTO" with HTTP client compression

### ISSUE THREAD

**Issue by edonin** [ClickHouse/ClickHouse#21907]
I recently doing some tests for updating from clickhouse 20.3 to 21.3.2.5.

With this new build, when I am executing  large insertion over the HTTP connection, with compression activated on the client side
Like this query
POST /?query=INSERT+INTO+%60avc%60.%60topconversationdetails%60+FORMAT+RowBinary&database=avc&compress=1&decompress=1 HTTP/1.1
Where data are inside the content on the HTTP request in compressed row binary format

I sometimes see this errors/stack trace in the clickhouse log file :

```
2021.03.19 11:54:42.764099 [ 41063 ] {eba46f57-0491-4ffb-b571-ed9d1618da75} <Error> DynamicQueryHandler: Code: 307, e.displayText() = DB::Exception: Chunk size is too large, Stack trace (when copying this message, always include the lines below):

0. DB::HTTPChunkedReadBuffer::readChunkHeader() @ 0xf8d5e5b in /opt/InfoVista/5ViewSDM/bin/clickhouse
1. DB::HTTPChunkedReadBuffer::nextImpl() @ 0xf8d616b in /opt/InfoVista/5ViewSDM/bin/clickhouse
2. DB::wrapReadBufferReference(DB::ReadBuffer&)::ReadBufferWrapper::nextImpl() @ 0xe7183fc in /opt/InfoVista/5ViewSDM/bin/clickhouse
3. DB::CompressedReadBufferBase::readCompressedData(unsigned long&, unsigned long&, bool) @ 0xe7d88cc in /opt/InfoVista/5ViewSDM/bin/clickhouse
4. DB::CompressedReadBuffer::nextImpl() @ 0xe7d83e7 in /opt/InfoVista/5ViewSDM/bin/clickhouse
5. DB::ConcatReadBuffer::nextImpl() @ 0xe966e1e in /opt/InfoVista/5ViewSDM/bin/clickhouse
6. DB::LimitReadBuffer::nextImpl() @ 0x86a7fcc in /opt/InfoVista/5ViewSDM/bin/clickhouse
7. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, DB::Context&, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>) @ 0xf1306cb in /opt/InfoVista/5ViewSDM/bin/clickhouse
8. DB::HTTPHandler::processQuery(DB::Context&, DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::__1::optional<DB::CurrentThread::QueryScope>&) @ 0xf84675a in /opt/InfoVista/5ViewSDM/bin/clickhouse
9. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0xf84a8ee in /opt/InfoVista/5ViewSDM/bin/clickhouse
10. DB::HTTPServerConnection::run() @ 0xf8d35ff in /opt/InfoVista/5ViewSDM/bin/clickhouse
11. Poco::Net::TCPServerConnection::start() @ 0x11f7ccbf in /opt/InfoVista/5ViewSDM/bin/clickhouse
12. Poco::Net::TCPServerDispatcher::run() @ 0x11f7e6d1 in /opt/InfoVista/5ViewSDM/bin/clickhouse
13. Poco::PooledThread::run() @ 0x120b4df9 in /opt/InfoVista/5ViewSDM/bin/clickhouse
14. Poco::ThreadImpl::runnableEntry(void*) @ 0x120b0c5a in /opt/InfoVista/5ViewSDM/bin/clickhouse
15. start_thread @ 0x7dd5 in /usr/lib64/libpthread-2.17.so
16. __clone @ 0xfdead in /usr/lib64/libc-2.17.so
 (version 21.3.2.5 (official build))
2021.03.19 11:54:42.764302 [ 41063 ] {eba46f57-0491-4ffb-b571-ed9d1618da75} <Error> DynamicQueryHandler: Cannot send exception to client: Code: 246, e.displayText() = DB::Exception: Unexpected data instead of HTTP chunk header, Stack trace (when copying this message, always include the lines below):

0. DB::HTTPChunkedReadBuffer::readChunkHeader() @ 0xf8d5e02 in /opt/InfoVista/5ViewSDM/bin/clickhouse
1. DB::HTTPChunkedReadBuffer::nextImpl() @ 0xf8d616b in /opt/InfoVista/5ViewSDM/bin/clickhouse
2. DB::HTTPHandler::trySendExceptionToClient(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, DB::HTTPServerRequest&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&) @ 0xf849ca2 in /opt/InfoVista/5ViewSDM/bin/clickhouse
3. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0xf84b015 in /opt/InfoVista/5ViewSDM/bin/clickhouse
4. DB::HTTPServerConnection::run() @ 0xf8d35ff in /opt/InfoVista/5ViewSDM/bin/clickhouse
5. Poco::Net::TCPServerConnection::start() @ 0x11f7ccbf in /opt/InfoVista/5ViewSDM/bin/clickhouse
6. Poco::Net::TCPServerDispatcher::run() @ 0x11f7e6d1 in /opt/InfoVista/5ViewSDM/bin/clickhouse
7. Poco::PooledThread::run() @ 0x120b4df9 in /opt/InfoVista/5ViewSDM/bin/clickhouse
8. Poco::ThreadImpl::runnableEntry(void*) @ 0x120b0c5a in /opt/InfoVista/5ViewSDM/bin/clickhouse
9. start_thread @ 0x7dd5 in /usr/lib64/libpthread-2.17.so
10. __clone @ 0xfdead in /usr/lib64/libc-2.17.so
 (version 21.3.2.5 (official build))

```

It does not seems to happen if I disable the client compression (but my requests are larger)

**Comment by den-crane** [comment]
Can you  show `create table topconversationdetails`

**Comment by den-crane** [comment]
Could not reproduce

```
21.4.1.6248

clickhouse-client -q "select arrayStringConcat(arrayMap(x->toString (cityHash64(x)) , range(1000)),' ') from numbers(100000) Format RowBinary" |gzip >test.bin.gz

clickhouse-client -q "CREATE TABLE log (row String) ENGINE = Null"

for i in `seq 1 50`; do curl -s -w 'Total: %{time_total}s HTTP: %{http_code}\n' -H 'Content-Encoding: gzip'  "http://localhost:8123/?compress=1&query=INSERT%20INTO%20log%20format%20RowBinary" --data-binary @test.bin.gz ; done;
Total: 2.770964s HTTP: 200
Total: 2.765195s HTTP: 200
Total: 2.835844s HTTP: 200
Total: 2.766895s HTTP: 200
Total: 2.607872s HTTP: 200
Total: 2.635509s HTTP: 200
Total: 2.533113s HTTP: 200
Total: 2.619424s HTTP: 200
Total: 2.670999s HTTP: 200
Total: 2.696852s HTTP: 200
Total: 2.804179s HTTP: 200
Total: 2.750693s HTTP: 200
Total: 2.739884s HTTP: 200
Total: 2.724064s HTTP: 200
...
```

**Comment by edonin** [comment]
Hi,

In your test case, you are trying to use the standard http compression.
Here, I got issue with the internal data compression algorithm.
You have to specify decompress=1 if the data sent by the client is compressed, and compress=1 if you want that the server compresses the data:
https://github.com/ClickHouse/ClickHouse/blob/21.3/src/Server/HTTPHandler.cpp#L467
https://clickhouse.tech/docs/en/interfaces/http/#compression

I am trying to find a reproducible test case.

**Comment by edonin** [comment]
Ok, it seems to happens when you use Transfert-Encoding: chunked, and the Content-Length is not specified.

It is difficult to reproduce with curl (I am still working on it), but it is what happens with the clickhouse-jdbc driver from java code.

**Comment by den-crane** [comment]
https://github.com/ClickHouse/ClickHouse/issues/17073
https://github.com/ClickHouse/ClickHouse/issues/17446

**Comment by edonin** [comment]
Thanks for the links.
After digging inside several network traces, it seems that the jdbc driver, when sending a rowbinary format, with decompress=1, is generating only one Data chunk split over several TCP packets.
It used to be accepted by the clickhouse server, but it is no more the case (I doubt that this way to do that is valid from the HTTP specs.)

I will dig more in the jdbc driver.

**Comment by edonin** [comment]
Ok, so I troubleshooted at more deeper level:

When the clickhouse-jdbc driver is used with decompress=1 and with native or rowbinary format for insertion, the apache http library (a quite standard library for using http) is generating a Tranfer-Encoding: chunked communication where chunks are bigger than a TCP packets. (so we receive the chunk size on the first tcp packet and some part of the chunk, and then, the remaining content of the chunk is split into several tcp packets).

A cannot reproduce with curl or wget, but it should be possible to write a java test case.

This mode seems to be called by apache team "large chunk", it is not forbidden by the RFC: https://tools.ietf.org/html/rfc7230#section-4.1
And was previously supported by clickhouse server.

So finally, it seems to be a clickhouse server bug. What do you think ?

**Comment by alexey-milovidov** [comment]
I confirm - the code around limiting the chunk size is incorrect.

HTTPServerRequest.cpp:40
> stream = std::make_unique<HTTPChunkedReadBuffer>(std::move(in), max_query_size);

`max_query_size` should not apply to the size of INSERTed data.

**Comment by alexey-milovidov** [comment]
@abyss7 Better not to limit at all or limit with some large value (will be implicitly limited by max_memory_usage).

BTW, why do we need
```
/// Chunk is not completely in buffer, copy it to scratch space.
memory.resize(chunk_size);
```

Maybe it's possible to read data by parts that will fit in buffer and count the number of bytes remaining to the end of chunk?

**Comment by alexey-milovidov** [comment]
Let's also make the error message more descriptive. It should say about the chunk of HTTP Transfer-Encoding: chunked.

**Comment by gj-zhang** [comment]
> Let's also make the error message more descriptive. It should say about the chunk of HTTP Transfer-Encoding: chunked.

Can this be resolved only by upgrading the Server version? If so, which version do I need to upgrade to? My current version is 21.3.3.14 and this error is also reported

**Comment by liujingmao** [comment]
In our company's dev enviroment , I also encountered the Error, But I do not know how to solve it

**Comment by alexey-milovidov** [comment]
@gj-zhang @liujingmao Upgrade to version 22.7.
