### ISSUE TITLE
DB::Exception: Cancelled merging parts in DB::MergeTreeDataMergerMutator::mergePartsToTemporaryPart

### ISSUE THREAD

**Issue by wo31415927** [ClickHouse/ClickHouse#21902]
Error log:

2021.03.19 14:17:39.282115 [ 398126 ] {2dc89ca3-c79e-45cf-a101-94718db3d02e} <Error> executeQuery: Code: 236, e.displayText() = DB::Exception: Cancelled merging parts (version 20.10.3.30 (official build)) (from [::ffff:192.168.53.228]:60536) (in query: optimize table `tag_user_dsfe_cust_demo` partition ('2019-12-31','test_52de62e81f3b4fcc816612066747f905') final), Stack trace (when copying this message, always include the lines below):

0. DB::MergeTreeDataMergerMutator::mergePartsToTemporaryPart(DB::FutureMergedMutatedPart const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::MergeListEntry&, std::__1::shared_ptr<DB::RWLockImpl::LockHolderImpl>&, long, DB::Context const&, std::__1::unique_ptr<DB::IReservation, std::__1::default_delete<DB::IReservation> > const&, bool) @ 0xe33c4e2 in /usr/bin/clickhouse
1. DB::StorageMergeTree::merge(bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) @ 0xe0d6169 in /usr/bin/clickhouse
2. DB::StorageMergeTree::optimize(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::IAST> const&, bool, bool, DB::Context const&) @ 0xe0daf48 in /usr/bin/clickhouse
3. DB::InterpreterOptimizeQuery::execute() @ 0xdbc0124 in /usr/bin/clickhouse
4. ? @ 0xdec8f18 in /usr/bin/clickhouse
5. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool) @ 0xdec7dbd in /usr/bin/clickhouse
6. DB::TCPHandler::runImpl() @ 0xe568ea6 in /usr/bin/clickhouse
7. DB::TCPHandler::run() @ 0xe575ca7 in /usr/bin/clickhouse
8. Poco::Net::TCPServerConnection::start() @ 0x10d4dd6f in /usr/bin/clickhouse
9. Poco::Net::TCPServerDispatcher::run() @ 0x10d4f77e in /usr/bin/clickhouse
10. Poco::PooledThread::run() @ 0x10e80a39 in /usr/bin/clickhouse
11. Poco::ThreadImpl::runnableEntry(void*) @ 0x10e7c96a in /usr/bin/clickhouse
12. start_thread @ 0x7e25 in /usr/lib64/libpthread-2.17.so
13. __clone @ 0xf834d in /usr/lib64/libc-2.17.so

2021.03.19 14:17:39.282239 [ 398126 ] {2dc89ca3-c79e-45cf-a101-94718db3d02e} <Error> TCPHandler: Code: 236, e.displayText() = DB::Exception: Cancelled merging parts, Stack trace:

0. DB::MergeTreeDataMergerMutator::mergePartsToTemporaryPart(DB::FutureMergedMutatedPart const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::MergeListEntry&, std::__1::shared_ptr<DB::RWLockImpl::LockHolderImpl>&, long, DB::Context const&, std::__1::unique_ptr<DB::IReservation, std::__1::default_delete<DB::IReservation> > const&, bool) @ 0xe33c4e2 in /usr/bin/clickhouse
1. DB::StorageMergeTree::merge(bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) @ 0xe0d6169 in /usr/bin/clickhouse
2. DB::StorageMergeTree::optimize(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::IAST> const&, bool, bool, DB::Context const&) @ 0xe0daf48 in /usr/bin/clickhouse
3. DB::InterpreterOptimizeQuery::execute() @ 0xdbc0124 in /usr/bin/clickhouse
4. ? @ 0xdec8f18 in /usr/bin/clickhouse
5. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool) @ 0xdec7dbd in /usr/bin/clickhouse
6. DB::TCPHandler::runImpl() @ 0xe568ea6 in /usr/bin/clickhouse
7. DB::TCPHandler::run() @ 0xe575ca7 in /usr/bin/clickhouse
8. Poco::Net::TCPServerConnection::start() @ 0x10d4dd6f in /usr/bin/clickhouse
9. Poco::Net::TCPServerDispatcher::run() @ 0x10d4f77e in /usr/bin/clickhouse
10. Poco::PooledThread::run() @ 0x10e80a39 in /usr/bin/clickhouse
11. Poco::ThreadImpl::runnableEntry(void*) @ 0x10e7c96a in /usr/bin/clickhouse
12. start_thread @ 0x7e25 in /usr/lib64/libpthread-2.17.so
13. __clone @ 0xf834d in /usr/lib64/libc-2.17.so

---

clickhouse:
version 20.10.3.30

lsb_release -a:
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: RedHatEnterpriseServer
Description:    Red Hat Enterprise Linux Server release 7.4 (Maipo)
Release:        7.4
Codename:       Maipo

CREATE TABLE tag_user_dsfe_cust_demo
(
    `_uid` UInt64 COMMENT '',
    `tag_code` String COMMENT '',
    `dt` String COMMENT '',
    `create_time` DateTime DEFAULT now() COMMENT ''
)
ENGINE = MergeTree
PARTITION BY (dt, tag_code)
ORDER BY _uid
SETTINGS index_granularity = 8192
;

---

there is some concurrent batch write operation from spark to table tag_user_dsfe_cust_demo,every batch size is 10000,
every write operation just "insert into" their own partition which is guaranteed by "dt, tag_code" column content in the write row.
after write operation,I use "optimize table `tag_user_dsfe_cust_demo` partition ('2019-12-31','test_52de62e81f3b4fcc816612066747f905') final" to merge the parts and the error happend.
I tried 100 concurrent write and optimize operation,5~6 optimize throw the error,other successed.
that's why?

**Comment by alexey-milovidov** [comment]
This is neither an error nor a bug.

Merges are cancelled in the following cases:
- table is being dropped or detached;
- server shutdown;
- SYSTEM STOP MERGES query is issued;
- (in older versions) when ALTER TABLE is being processed.

**Comment by alexey-milovidov** [comment]
PS. Version 20.10 is no longer supported and you should upgrade to 21.3.
