### ISSUE TITLE
Materialized view has incorrect data from `ReplacingMergeTree` table when rows are collapsing.

### ISSUE THREAD

**Issue by vorillaz** [ClickHouse/ClickHouse#21909]
Hey there, first things first thanks a lot for the wonderful project.
I am trying to create a "data sync" table with hourly aggregated data from a `ReplacingMergeTree` table.

I've created the table and the `MATERIALIZED VIEW` for syncing as:
```sql
CREATE TABLE summs (
  timestamp Datetime DEFAULT now(),
  id UInt32,
  sign Int8 DEFAULT 1,
  value Float32,
  projectId Int8,
  page String
) ENGINE = ReplacingMergeTree(sign) PARTITION BY tuple()
order by (id, projectId, page);

CREATE TABLE summs_hourly (
  id UInt32,
  hour DateTime,
  page String,
  projectId Int8,
  -- 
  pageviews AggregateFunction(count),
  valueavg AggregateFunction(avg, Float32)
) ENGINE = AggregatingMergeTree() Partition by toYYYYMM(hour)
ORDER BY (hour, id, page, projectId);

CREATE MATERIALIZED VIEW summs_hourly_mv TO summs_hourly AS
SELECT toStartOfHour(timestamp) as hour,
  id,
  page,
  projectId,
  countState() pageviews,
  avgState(value) valueavg
FROM summs
GROUP BY hour,
  id,
  page,
  projectId;
```

Afterwards I am adding some data and everything seems to work as expected:
```sql
INSERT INTO summs (id, sign, value, projectId, page)
VALUES (2, 1, 200, 1, '/page2'),
  (2, 1, 100, 1, '/page3'),
  (2, 1, 300, 1, '/page3'),
  (2, 1, 200, 1, '/page3');
```

And retrieving the data gives me the proper results:
```
SELECT hour,
  id,
  page,
  projectId,
  countMerge(pageviews) pageviews_final,
  avgMerge(valueavg) avgState_final
FROM summs_hourly FINAL
GROUP BY hour,
  id,
  page,
  projectId;
  
┌────────────────hour─┬─id─┬─page───┬─projectId─┬─pageviews_final─┬─avgState_final─┐
│ 2021-03-19 12:00:00 │  2 │ /page3 │         1 │               3 │            200 │
│ 2021-03-19 12:00:00 │  2 │ /page2 │         1 │               1 │            200 │
└─────────────────────┴────┴────────┴───────────┴─────────────────┴────────────────┘
```

**But** as I am trying to collapse the data for the `summs` table the results are incorrect, the data in the original table are properly collapsing but the `summs_hourly` table does not correspond with the collapsed data:
```sql
-- collapse
INSERT INTO summs (id, sign, value, projectId, page)
VALUES (2, -1, 200, 1, '/page2'), (2, 1, 333, 1, '/page2');

SELECT *
FROM summs
FINAL;

┌───────────timestamp─┬─id─┬─sign─┬─value─┬─projectId─┬─page───┐
│ 2021-03-19 12:43:45 │  2 │    1 │   333 │         1 │ /page2 │
└─────────────────────┴────┴──────┴───────┴───────────┴────────┘
┌───────────timestamp─┬─id─┬─sign─┬─value─┬─projectId─┬─page───┐
│ 2021-03-19 12:43:20 │  2 │    1 │   200 │         1 │ /page3 │
└─────────────────────┴────┴──────┴───────┴───────────┴────────┘

SELECT hour,
  id,
  page,
  projectId,
  countMerge(pageviews) pageviews_final,
  avgMerge(valueavg) avgState_final
FROM summs_hourly FINAL
GROUP BY hour,
  id,
  page,
  projectId;

┌────────────────hour─┬─id─┬─page───┬─projectId─┬─pageviews_final─┬─────avgState_final─┐
│ 2021-03-19 12:00:00 │  2 │ /page3 │         1 │               3 │                200 │
│ 2021-03-19 12:00:00 │  2 │ /page2 │         1 │               3 │ 244.33333333333334 │
└─────────────────────┴────┴────────┴───────────┴─────────────────┴────────────────────┘

```

`pageviews` and `avgState_final` are also aggregating the rows with `sign:-1`.
I am not quite sure if that's a bug or maybe I need to tune the the aggregated view.
Any help will be highly appreciated.

**Comment by den-crane** [comment]
Materialized view is an insert trigger. It knows nothing about an engine of the base table. 

https://den-crane.github.io/Everything_you_should_know_about_materialized_views_commented.pdf
https://youtu.be/ckChUkC3Pns?t=9326

**Comment by vorillaz** [comment]
Hey @den-crane, thanks for the response.
Is there any chance I could use aggregated materialized views along with collapsing rows without manually data syncing with a cron Job?

**Comment by den-crane** [comment]
To be honest I did not read you issue. I don't have time to read/think.

I just replied with my snippet.
I see you have some sign column, can you mutliple ` sign * value as value`  in Materialized view?

**Comment by vorillaz** [comment]
@den-crane I appreciate your time and efforts. I don't get your point about the sign values and aggregating the count for pageviews, can you elaborate a bit more?

**Comment by den-crane** [comment]
```
ReplacingMergeTree(sign)

VALUES (2, 1, 200, 1, '/page2'),
VALUES (2, -1, 200, 1, '/page2'), (2, 1, 333, 1, '/page2');
```
You have confused CollapsingMT and ReplacingMergeTree? Because ReplacingMergeTree use the version policy, not the sign.


But anyway. You a inserting values into SummingMT, if you negate value by *-1 then you get the matching result:
MV value = value*sign === 1*1 +  1*(-1) + 1*1 = 1

```sql
CREATE MATERIALIZED VIEW summs_hourly_mv TO summs_hourly AS
SELECT toStartOfHour(timestamp) as hour,
  id,
  page,
  projectId,
  sumState(1*sign) pageviews,          ----<------
  avgState(value*sign) valueavg        ----<------
FROM summs
GROUP BY hour,
  id,
  page,
  projectId;
```
