### ISSUE TITLE
Increased hashed dictionary RAM x4 usage after upgrade CH to 21.3

### ISSUE THREAD

**Issue by NikitaZakharov** [ClickHouse/ClickHouse#21935]
After upgrade CH from 20.8 to 21.3 I noticed RAM used by dictionary with `hashed` layout was increased exactly in **4** times.

OS: Ubuntu 20.04
Processor: AMD EPYC 7502P 32-Core Processor
RAM: 252 GB

`<dictionaries_lazy_load>false</dictionaries_lazy_load>
`

In 20.8 release CH was using less memory for dictionaries with `hashed` layout.
The problem was not detected for dictionaries with `ComplexKeyHashed` layout. But they have a small amount of data (up to 500 MB).
After server restart with 20.8 version memory usage is increasing up to 30 GB (all dictionaries RAM usage) step by step during dictionaries loading.
After server restart with 21.3 version memory usage is increasing up to 112 GB almost immediately and then decreasing to 91 GB.

Maybe it's a consequence after #18236

20.8 version dictionary
```
┌─status─┬─type───┬─key────┬─attribute.types─┬─element_count─┬─formatReadableSize(bytes_allocated)─┐
│ LOADED │ Hashed │ UInt64 │ ['Float64']     │     428492347 │ 16.00 GiB                           │
└────────┴────────┴────────┴─────────────────┴───────────────┴─────────────────────────────────────┘
```

21.3 version dictionary
```
┌─status─┬─type───┬─key────┬─attribute.types─┬─element_count─┬─formatReadableSize(bytes_allocated)─┐
│ LOADED │ Hashed │ UInt64 │ ['Float64']     │     428492347 │ 64.00 GiB                           │
└────────┴────────┴────────┴─────────────────┴───────────────┴─────────────────────────────────────┘
```

Dictionaries with the same scheme but another amount of data also have this problem.

**Comment by kitaisreal** [comment]
@NikitaZakharov as I understand dictionary has 1 key UInt64 and 1 attribute Float64 ?

**Comment by NikitaZakharov** [comment]
@kitaisreal yes, exactly

Dictionary definition in XML config:

```
<dictionary>
    <name>NAME</name>
    <source>
        <clickhouse>
            <host>host</host>
            <port>port</port>
            <user>user</user>
            <password>password</password>
            <db>database</db>
            <table>table</table>
        </clickhouse>
    </source>
    <lifetime>0</lifetime>
    <layout>
        <hashed></hashed>
    </layout>
    <structure>
        <id>
            <name>key_column</name>
        </id>
        <attribute>
            <name>attribute_column</name>
            <type>Float64</type>
            <expression>toFloat64(attribute_column)</expression>
            <null_value>0.0</null_value>
        </attribute>
    </structure>
</dictionary>
```

`attribute_column` in `table` table has Decimal(20, 4) type

**Comment by kitaisreal** [comment]
@NikitaZakharov after small investigation, we see that only change in new versions is resize call during block insert.
Do you have any reproducible example to try ?

**Comment by kitaisreal** [comment]
@NikitaZakharov can you check how many elements you have in source ? Maybe some keys are not unique ?

**Comment by kitaisreal** [comment]
Let me show my example configuration to reproduce ticket:
Dictionary configuration
```xml
<dictionary>
    <name>float_dictionary_xml</name>
    <structure>
        <id>
            <name>id</name>
        </id>

        <attribute>
            <name>value</name>
            <type>UInt64</type>
            <null_value>0</null_value>
        </attribute>
    </structure>

    <layout>
        <hashed/>
    </layout>

    <source>
        <clickhouse>
            <host>localhost</host>
            <port>9000</port>
            <user>default</user>
            <password></password>
            <table>float_dictionary_source</table>
        </clickhouse>
    </source>

    <lifetime>0</lifetime>

</dictionary>
```
```
CREATE TABLE default.float_dictionary_source (id UInt64, value Float64) ENGINE=MergeTree ORDER BY id;
INSERT INTO default.float_dictionary_source SELECT number, toFloat64(number) FROM system.numbers LIMIT 428492347
```

```
SELECT dictGet('float_dictionary_xml', 'value', number) FROM system.numbers LIMIT 10
SELECT name, bytes_allocated, element_count FROM system.dictionaries
```

21.3
```
float_dictionary_xml                   │     17179869376 │     428492347
```
20.8
```
float_dictionary_xml │     17179869344 │     428492347 │
```

17179869376 / (1024 * 1024 * 1024) = ~16 GB

**Comment by alexey-milovidov** [comment]
#15454

**Comment by NikitaZakharov** [comment]
@kitaisreal in your example I see `UInt64` type for attribute in dictionary and `Float64` type for attribute in source table. 
In my case, attribute column is `Decimal(20, 4)` type in source table and for dictionary it should be converted to `Float64` based on `<expression>toFloat64(attribute_column)</expression>` setting. Maybe dictionary allocates memory for decimal type instead of float?

Also, my source has duplicates by key column but it should not be the issue because hash table overrides value for specific key to the last random value in selection if it's not unique.

**Comment by kitaisreal** [comment]
@NikitaZakharov already created pull request for problem https://github.com/ClickHouse/ClickHouse/pull/15454.
