### ISSUE TITLE
The default database is default if the replica table does not specify the database

### ISSUE THREAD

**Issue by melin** [ClickHouse/ClickHouse#21947]
The default database is default if the replica table does not specify the database
Also sql single machine can execute

```sql
create table etl_test_csv_1
ENGINE = ReplicatedMergeTree
ORDER BY name
AS
select * from dd1_import_csv
```

Caused by: java.lang.Throwable: Code: 60, e.displayText() = DB::Exception: There was an error on [datainsight-d-006052.te.td:9110]: Code: 60, e.displayText() = DB::Exception: Table default.dd1_import_csv doesn't exist (version 21.3.2.5 (official build)) (version 21.3.2.5 (official build))

```
ClickHouseProperties properties = new ClickHouseProperties();
properties.setCompress(true);
properties.setPassword(clickhousePassword);
properties.setConnectionTimeout(clickHouseConnectionTimeout * 1000);
properties.setSocketTimeout(clickHouseSocketTimeout * 1000);
properties.setDataTransferTimeout(clickHouseDataTransferTimeout * 1000);
properties.setKeepAliveTimeout(clickHouseKeepAliveTimeout * 1000);

BalancedClickhouseDataSource dataSource = new BalancedClickhouseDataSource("jdbc:clickhouse://192.168.6.53:8124/datainsight", properties);
```

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/8340
