### ISSUE TITLE
Is there any news about the plan to support shared (or remote) file system?

### ISSUE THREAD

**Issue by xiaogaozi** [ClickHouse/ClickHouse#21952]
Hi folks, according to #17623 the community has a plan to support shared (or remote) file system in this year. Is there any news (like RFC, design document)? We ([JuiceFS](https://github.com/juicedata/juicefs)) are very happy to participate in relevant discussions. Thanks.

**Comment by alexey-milovidov** [comment]
Yes, we have plans to allow multiple compute nodes to share the same data in MergeTree table.

**Comment by xiaogaozi** [comment]
@alexey-milovidov Is there any more details? Thanks.

**Comment by alexey-milovidov** [comment]
ClickHouse over s3 is production ready since at least 22.3.
https://clickhouse.com/docs/en/guides/sre/configuring-s3-for-clickhouse-use
