### ISSUE TITLE
Can we have another release for 20.12? 

### ISSUE THREAD

**Issue by Zhile** [ClickHouse/ClickHouse#21956]
Hi, 
Can we have another release for 20.12? I see it's been about 18 days since the last release on dockerhub. 
How's the frequency of one release? Based on what kinds of standards will we build a release version for ClickHouse server? 
If I build the binary on my local machine, is there any difference (performance, configs, size etc.) with the official release? 

Thanks.

**Comment by filimonov** [comment]
> How's the frequency of one release?

If we talk about 'bugfix' release (i.e. incrementing the last partition of the version to fix some bugs, w/o changing the functionality) - it depends on:
1) the number of 'queued' fixes and their importance
2) CI status (tests should be green)
3) how busy Yandex teammates are with other tasks.

Normally it's from few days to few weeks. 
 
>  If I build the binary on my local machine, is there any difference (performance, configs, size etc.) with the official release?

If you will use the same packager script to create a build as used in clickhouse CI you should get build 'as good as the official', see https://github.com/ClickHouse/ClickHouse/tree/master/docker/packager

**Comment by Zhile** [comment]
Thanks @filimonov for the explanation. So can we have a manual trigger for the release? I'm waiting for this release to do some tests.

**Comment by alexey-milovidov** [comment]
20.12 is out of support. If you need bugfixes, better to upgrade to release 21.3.

**Comment by Zhile** [comment]
@alexey-milovidov  Can you help to build another release for 20.12? I tried 21.1, 21.2, 21.3 and there're still critical bugs which block our upgrade. 

https://github.com/ClickHouse/ClickHouse/issues/22399
https://github.com/ClickHouse/ClickHouse/issues/20193

**Comment by alexey-milovidov** [comment]
We already stopped backporting changes to version 20.12, it will be more easy to ship fixed to 21.3 than to revive 20.12.

**Comment by Zhile** [comment]
We don't need to backport anything to 20.12. We just need to build a release for 20.12. If this is not possible, please help to fix 21.3. Many thanks.
