### ISSUE TITLE
Weird result when summing floats.

### ISSUE THREAD

**Issue by YordanPavlov** [ClickHouse/ClickHouse#21973]
(you don't have to strictly follow this form)

We noticed some weird computations in our queries, then narrowed down the problem to the following query:

```sql
SELECT
sum(value)
FROM
(
SELECT arrayJoin([
   115792089237316200000000000000000000000000000000000000000000000000,
   115792089237316200000000000000000000000000000000000000000000000000,
   115792089237316200000000000000000000000000000000000000000000000000,
  -115792089237316200000000000000000000000000000000000000000000000000,
  -115792089237316200000000000000000000000000000000000000000000000000,
  -115792089237316200000000000000000000000000000000000000000000000000] ) as value
)
```
This outputs: 4.6768052394588893e49, when we would expect it to output 0.

It does reproduce on both an older version which we have, ClickHouse server version 20.4.6 revision 54434 and on the latest version I installed locally from Deb package, ClickHouse server version 21.3.3 revision 54447.

Playing with the values in the query I added .0 at the end so to make CH consider them as Float64, also wrapping the numbers with toFloat64 did not help. I presume the problem is around floating point arithmetics, but the values are still small compared to the maximum value to be stored in Float64.

**Comment by den-crane** [comment]
try to use sumKahan instead of sum

It's how summation works in CPU.

```
result: **Schema (SQLite v3.26)**

    

---

**Query #1**

    select sum(a) from 
    (select 115792089237316200000000000000000000000000000000000000000000000000 a union all
    select  115792089237316200000000000000000000000000000000000000000000000000  union all
    select   115792089237316200000000000000000000000000000000000000000000000000  union all
    select   -115792089237316200000000000000000000000000000000000000000000000000  union all
    select  -115792089237316200000000000000000000000000000000000000000000000000  union all
    select  -115792089237316200000000000000000000000000000000000000000000000000) t;

| sum(a)                 |
| ---------------------- |
| 4.6768052394588893e+49 |

---

[View on DB Fiddle](https://www.db-fiddle.com/) 
```
