### ISSUE TITLE
AggregatingMergeTree table is not merging records. 

### ISSUE THREAD

**Issue by DipalPrajapati** [ClickHouse/ClickHouse#21985]
I have one AggregatingMergeTree  table , in one day data(batch) I am inserting 99M records , in which only 10000 subscribers are new,others are repeated with same rest of fields except time. 
But it is not merging the records. 

**select count(*) from dmaData;**

SELECT count(*)
FROM myTable

Query id: 2fb5005e-d96f-4b91-b673-c16e673ea936

┌───count()─┐
│ 379692631 │
└───────────┘
I have inserted 4 days data which is roughly  like  99M*4. 

What could be the reason, due to this my other jobs are failing saying Memory exceeded (60GB).

**Comment by den-crane** [comment]
Clickhouse merge scheduler does not have the goal to merge everything.
Merge scheduler balance number of parts in a partition with an amount of resources needed to merge them and plans merges if there are free resources available.

Merges are eventual and may never happen. It depends on the number of inserts that happened after, the number of parts in the partition, size of parts.
If the total size of input parts bigger than the maximum part size then they are never will be merged.

**Comment by DipalPrajapati** [comment]
OK .How can i check maximum part size? 
Do you mean I should break up my input data in different chunk and insert?  Would that work?

**Comment by den-crane** [comment]
I mean that you should not relay on the merging.
Write your queries to work with not merged data. All queries should use aggregate functions and groupby.

**Comment by den-crane** [comment]
>What could be the reason, due to this my other jobs are failing saying Memory exceeded (60GB).

set max_bytes_before_external_group_by to spill aggregation to disk
https://clickhouse.tech/docs/en/operations/settings/query-complexity/#settings-max_bytes_before_external_group_by

**Comment by DipalPrajapati** [comment]
@den-crane  
Hi again ,
I checked the part sizes. 
They are hardly in 1-2 GB. 
I have 2 nodes. 

**First node :** 
┌─partition_id─┬─formatReadableSize(bytes)─┐
│ all          │ 2.35 GiB                  │
│ all          │ 2.35 GiB                  │
│ all          │ 1.25 GiB                  │
│ all          │ 1.16 GiB                  │
│ all          │ 1.16 GiB                  │
│ all          │ 857.35 MiB                │
└──────────────┴───────────────────────────┘

**Second node :** 
┌─partition_id─┬─formatReadableSize(bytes)─┐
│ all          │ 2.36 GiB                  │
│ all          │ 2.32 GiB                  │
│ all          │ 2.30 GiB                  │
│ all          │ 287.87 MiB                │
│ all          │ 352.35 MiB                │
│ all          │ 314.55 MiB                │
│ all          │ 343.20 MiB                │
│ all          │ 335.06 MiB                │
│ all          │ 69.27 MiB                 │
│ all          │ 309.50 MiB                │
│ all          │ 63.11 MiB                 │
└──────────────┴───────────────────────────┘

Why merge is not happening? 
default part size is 150GB as it is.

**Comment by den-crane** [comment]
@DipalPrajapati it's expected. 

Merge scheduler balance number of parts in a partition with an amount of resources needed to merge them and plans merges if there are free resources available.

I observe around 22 parts for the hot partitions in my production. 

>Is there any other way to check the reason of it ?

Nothing to check. It's expected normal behavior.

> enabling partitioning for this aggregatingMergeTree will help ? Currently I am partitioning by tuple()?

NO? You have partitioning. You simply have only one partition.

**Comment by DipalPrajapati** [comment]
The only issue I am trying to solve here is that aggregation of data is not happening. 
Against the table keys I am getting more than single records.

**Comment by den-crane** [comment]
>Which should not happen. 

It **MUST** happen. Data in ALL Engine ALWAYS not full aggregated / merged. 
You **MUST** always query your table using queries with GROUP BY.


>And by enabling partitioning , I meant , increasing num of partitions will help in this case?

Obviously not.
