### ISSUE TITLE
Delete the distributed table and the node on the zookeeper is not deleted?

### ISSUE THREAD

**Issue by melin** [ClickHouse/ClickHouse#22014]
Delete the distributed table and the node on the zookeeper is not deleted? Rebuild the same name table, indicating that the node already exists

**Comment by den-crane** [comment]
Replicated? Atomic database?

https://github.com/ClickHouse/ClickHouse/issues/12135#issuecomment-653932557

**Comment by melin** [comment]
> Replicated? Atomic database?
> 
> [#12135 (comment)](https://github.com/ClickHouse/ClickHouse/issues/12135#issuecomment-653932557)

Yes, the same problem

**Comment by den-crane** [comment]
So you can use UUID as ZK path.

Or configure

```
$ cat /etc/clickhouse-server/config.d/database_atomic_delay_before_drop_table.xml
<yandex>
    <database_atomic_delay_before_drop_table_sec>1</database_atomic_delay_before_drop_table_sec>
</yandex>


$ cat /etc/clickhouse-server/users.d/atomic.xml
<?xml version="1.0" ?>
<yandex>
  <users>
    <default>
      <database_atomic_wait_for_drop_and_detach_synchronously>1</database_atomic_wait_for_drop_and_detach_synchronously>
    </default>
  </users>
</yandex>

```
