### ISSUE TITLE
How to use Kafka-engine to parse nestedJson 

### ISSUE THREAD

**Issue by Lipeng522** [ClickHouse/ClickHouse#22019]
Make sure to check documentation https://clickhouse.yandex/docs/en/ first. If the question is concise and probably has a short answer, asking it in Telegram chat https://telegram.me/clickhouse_en is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

If you still prefer GitHub issues, remove all this text and ask your question here.

**Comment by Lipeng522** [comment]
The dataType of kafka is cannal-json, as follow:
{
  "data": [
    {
      "id": "8169d862ca741b9cfc54d5f273e21ccb",
      "trans_number": "1201140550027043",
      "cust_id": "983394828429862540",
      "cust_phone": "",
      "cust_clubcard_id": "",
      "cust_ship_add": "",
      "comment": "",
      "create_time": "2021-01-04 15:23:30",
      "update_time": "2021-01-04 15:23:30"
    }
  ],
  "database": "yh_rme_soc_stream_prod",
  "es": 1609745010000,
  "id": 46271193,
  "isDdl": false,
  "mysqlType": {
    "id": "varchar(32)",
    "trans_number": "varchar(30)",
    "cust_id": "varchar(50)",
    "cust_phone": "varchar(20)",
    "cust_clubcard_id": "varchar(30)",
    "cust_ship_add": "varchar(200)",
    "comment": "varchar(100)",
    "create_time": "datetime",
    "update_time": "datetime"
  },
  "old": null,
  "pkNames": null,
  "sql": "",
  "sqlType": {
    "id": 12,
    "trans_number": 12,
    "cust_id": 12,
    "cust_phone": 12,
    "cust_clubcard_id": 12,
    "cust_ship_add": 12,
    "comment": 12,
    "create_time": 93,
    "update_time": 93
  },
  "table": "tlog_custinfo_20210104",
  "ts": 1609745010150,
  "type": "INSERT"
}



if I want to use kafka-engine to consumer this topic and get the infomation of `data`, when create queue_table,how to define the `data`'s dataType?

**Comment by melin** [comment]
select '{"data":[{"id":"8169d862ca741b9cfc54d5f273e21ccb","trans_number":"1201140550027043","cust_id":"983394828429862540","cust_phone":"","cust_clubcard_id":"","cust_ship_add":"","comment":"","create_time":"2021-01-04 15:23:30","update_time":"2021-01-04 15:23:30"}],"database":"yh_rme_soc_stream_prod","es":1609745010000,"id":46271193,"isDdl":false,"mysqlType":{"id":"varchar(32)","trans_number":"varchar(30)","cust_id":"varchar(50)","cust_phone":"varchar(20)","cust_clubcard_id":"varchar(30)","cust_ship_add":"varchar(200)","comment":"varchar(100)","create_time":"datetime","update_time":"datetime"},"old":null,"pkNames":null,"sql":"","sqlType":{"id":12,"trans_number":12,"cust_id":12,"cust_phone":12,"cust_clubcard_id":12,"cust_ship_add":12,"comment":12,"create_time":93,"update_time":93},"table":"tlog_custinfo_20210104","ts":1609745010150,"type":"INSERT"}' as data_json,
       JSONExtractArrayRaw(data_json, 'data') AS data_raw,
       arrayJoin(data_raw) AS data_array_raw,
       untuple(JSONExtract(data_array_raw, 'Tuple(id String, trans_number String, cust_id String, cust_phone String, cust_clubcard_id String, cust_ship_add String)'))

**Comment by den-crane** [comment]
```
create table entrypoint(J String) Engine=Null;
create table datastore(a String, i Int64, f Float64) Engine=MergeTree order by a;

create materialized view jsonConverter to datastore
as select (JSONExtract(J, 'Tuple(String,Tuple(Int64,Float64))') as x),
        x.1 as a,
        x.2.1 as i,
        x.2.2 as f
from entrypoint;

$ echo '{"s": "val1", "b2": {"i": 42, "f": 0.1}}' | \
    clickhouse-client -q "insert into entrypoint format JSONAsString"

$ echo '{"s": "val1","b2": {"i": 33, "f": 0.2}},{"s": "val1","b2": {"i": 34, "f": 0.2}}' | \
   clickhouse-client -q "insert into entrypoint format JSONAsString"

SELECT * FROM datastore;
┌─a────┬──i─┬───f─┐
│ val1 │ 42 │ 0.1 │
└──────┴────┴─────┘
┌─a────┬──i─┬───f─┐
│ val1 │ 33 │ 0.2 │
│ val1 │ 34 │ 0.2 │
└──────┴────┴─────┘
```
