### ISSUE TITLE
Значение null заменяется на 1970-01-01 во внешнем словаре range_hashed через odbc к postgres

### ISSUE THREAD

**Issue by magvan** [ClickHouse/ClickHouse#22022]
Создал таблицу в Postgres.
![image](https://user-images.githubusercontent.com/8927781/112126897-f171e400-8bd5-11eb-939a-58250468369e.png)

Сделал по ней словарь в clickhouse, в словаре видим это
![image](https://user-images.githubusercontent.com/8927781/112129545-91c90800-8bd8-11eb-85f0-ed43f1bedfbf.png)

**date_end в источнике данных (postgres) имеет значение null, но в словаре в кликхаусе имеет значение 1970-01-01**

Как увидеть эту ошибку:

Создал таблицу в PG.
```
create table pay.rate (
    id bigserial not null primary key,
    currencies varchar(6) not null,
    rate numeric(16,8) not null,
    date_start timestamp not null default now(),
    date_end timestamp default null
);

insert into pay.rate (currencies, rate) values ('USDRUB', 72);
insert into pay.rate (currencies, rate) values ('RUBUSD', 0.014);
```

Настроил odbc в /etc/odbc.ini
```
[DEFAULT]
Driver = postgres_db

[postgres_db]
Description         = PostgreSQL connection to postgres_db
Driver              = /usr/lib/x86_64-linux-gnu/odbc/psqlodbcw.so
Database            = postgres_db
ServerName          = 127.0.0.1
UserName            = postgres
Password            = postgres
Port                = 5432
Protocol            = 9.3
ReadOnly            = No
RowVersioning       = No
ShowSystemTables    = No
ConnSettings        =
```

Создал словарь в xml
```
<dictionary>
    <name>rate</name>
    <source>
        <odbc>
            <connection_string>DSN=postgres_db</connection_string>
            <table>pay.rate</table>
        </odbc>
    </source>
    <lifetime>
        <min>300</min>
        <max>360</max>
    </lifetime>
    <layout>
        <range_hashed/>
    </layout>
    <structure>
        <id>
            <name>id</name>
            <type>UInt64</type>:
        </id>
        <range_min>
            <name>date_start</name>
            <type>Date</type>
        </range_min>
        <range_max>
            <name>date_end</name>
            <type>Date</type>
        </range_max>
        <attribute>
            <name>rate</name>
            <type>Float64</type>
            <null_value>0</null_value>
        </attribute>
    </structure>
</dictionary>
```
Создал базу что бы видеть словарь
```
CREATE DATABASE rate_t ENGINE = Dictionary;
SELECT * FROM dictionaries.rate;
```
Теперь можно посмотреть словарь
```
SELECT t.* FROM rate_t.rate t
```

**Comment by filimonov** [comment]
```
<name>date_end</name>
<type>Date</type>
```
В  типе данных Date невозможно записать Null поэтому используется значение по умолчанию (1 января 1970).

Для хранения null в КХ нужно использовать Nullable(...)

Впрочем, поддержка null для словарей появилась совсем недавно и это может не работать корректно для  range_hashed.

При этом 'нулевая дата', т.е. 1 января 1970 года для range_hashed должна служить как маркер открытого диапазона и dictget запросы должны работать корректно.

**Comment by alexey-milovidov** [comment]
@kitaisreal Наверное Nullable уже работает корректно для `range_hashed` и задачу можно закрывать?

**Comment by magvan** [comment]
> @kitaisreal Наверное Nullable уже работает корректно для `range_hashed` и задачу можно закрывать?

Nullable нет в range_hashed.

Настраиваю словарь:
```
            <range_min>
		    <name>date_start</name>
		    <type>Date</type>
	    </range_min>
	    <range_max>
		    <name>date_end</name>
		    <type>Date</type>
	    </range_max>
```

range_min и range_max, поддерживает следующие типы: (текст из документации)
```
Чтобы использовать выборку по диапазонам дат, необходимо в structure определить элементы range_min, range_max. В этих элементах должны присутствовать элементы name и type (если type не указан, будет использован тип по умолчанию – Date). type может быть любым численным типом (Date/DateTime/UInt64/Int32/др.).
```

Если указать тип Nullable(Date) то словарь просто не загрузится с ошибкой
```
Code: 36, e.displayText() = DB::Exception: Code: 36, e.displayText() = DB::Exception: Dictionary structure type of 'range_min' and 'range_max' should be an integer, Date, DateTime, or Enum. Actual 'range_min' and 'range_max' type is Nullable(Date) (version 21.3.3.14 (official build)) (version 21.3.3.14 (official build))
```

**Атрибуты поддерживают Nullable(...), но не range_min, ragne_max.**

**Comment by magvan** [comment]
> ```
> <name>date_end</name>
> <type>Date</type>
> ```
> 
> В типе данных Date невозможно записать Null поэтому используется значение по умолчанию (1 января 1970).
> 
> Для хранения null в КХ нужно использовать Nullable(...)
> 
> Впрочем, поддержка null для словарей появилась совсем недавно и это может не работать корректно для range_hashed.
> 
> При этом 'нулевая дата', т.е. 1 января 1970 года для range_hashed должна служить как маркер открытого диапазона и dictget запросы должны работать корректно.

**Comment by magvan** [comment]
> @filimonov В типе данных Date невозможно записать Null поэтому используется значение по умолчанию (1 января 1970).
> Для хранения null в КХ нужно использовать Nullable(...)

Nullable можно использовать в атрибутах. При конфигурировании словаря испльзощвать nullable для полей range_min/range_max нельзя.

Понимаю что Date не может быть Null.
Судя по документации открытая дата считается:
```
Если граница диапазона NULL или некорректная дата (1900-01-01), то диапазон считается открытым. Диапазон может быть открытым с обеих сторон.
```
Получается что null надо приводить к 1900-01-01 и делать это через вьюху в PG. Какой то костыль получается.

**Comment by magvan** [comment]
Если бы можно было бы использовать **\<expression /\>** в range_min/range_max. Думаю в нем можно было бы заменить null на 1900-01-01.

**Comment by magvan** [comment]
> @magvan
> Получается что null надо приводить к 1900-01-01 и делать это через вьюху в PG. Какой то костыль получается.

С вьюхой тоже не получилось. Создал вьюху, теперь она отдает такие данные:
![image](https://user-images.githubusercontent.com/8927781/112274122-2c841e00-8c8f-11eb-8a74-aec9ef315c21.png)
Попробовал сделать не закрытые даты date_end.
1900-01-01 как в доках написанно
```
Если граница диапазона NULL или некорректная дата (1900-01-01), то диапазон считается открытым. Диапазон может быть открытым с обеих сторон.
```
Смотрю в словарь, а там опять 1970-01-01.
![image](https://user-images.githubusercontent.com/8927781/112274469-91d80f00-8c8f-11eb-966e-b341dd3b7bfb.png)
В итоге получается что дата не открытая, а не правильная. Дата начала 2021-03-24, а дата окончания 1970-01-01

**Comment by filimonov** [comment]
>  Получается что null надо приводить к 1900-01-01 и делать это через вьюху в PG. Какой то костыль получается.

Не надо. 1900-01-01 это ошибка в документации, такая дата сейчкас для КХ невозможна. Там семерка потерялась. Должно быть как раз 1970-01-01

>  Я ожидал что вернет 72.

Да, если вы всё верно сделали то должен вернуть 72. 

Перепроверил - у меня всё работает как ожидается несмотря на 1970-01-01:

```
DROP TABLE IF EXISTS rates;

DROP DICTIONARY IF EXISTS rates_dict;

CREATE TABLE rates (
  id UInt64,
  date_start Nullable(Date),
  date_end Nullable(Date),
  rate Decimal64(4)
) engine=Log;


INSERT INTO rates VALUES (1, Null, '2021-03-13',99), (1, '2021-03-14','2021-03-16',100), (1, '2021-03-17', Null, 101), (2, '2021-03-14', Null, 200), (3, Null, '2021-03-14', 300), (4, '2021-03-14', '2021-03-14', 400);

CREATE DICTIONARY rates_dict
(
  id UInt64,
  date_start Date,
  date_end Date,
  rate Decimal64(4)
)
PRIMARY KEY id
SOURCE(CLICKHOUSE(HOST 'localhost' PORT 9000 USER 'default' TABLE 'rates'))
LIFETIME(MIN 1 MAX 1000)
LAYOUT(RANGE_HASHED())
RANGE(MIN date_start MAX date_end);

SELECT * FROM rates_dict order by id, date_start;

┌─id─┬─date_start─┬───date_end─┬─────rate─┐
│  1 │ 1970-01-01 │ 2021-03-13 │  99.0000 │
│  1 │ 2021-03-14 │ 2021-03-16 │ 100.0000 │
│  1 │ 2021-03-17 │ 1970-01-01 │ 101.0000 │
│  2 │ 2021-03-14 │ 1970-01-01 │ 200.0000 │
│  3 │ 1970-01-01 │ 2021-03-14 │ 300.0000 │
│  4 │ 2021-03-14 │ 2021-03-14 │ 400.0000 │
└────┴────────────┴────────────┴──────────┘

WITH 
  toDate('2021-03-10') + INTERVAL number DAY as date
select 
  date,
  dictGet(currentDatabase() || '.rates_dict', 'rate', toUInt64(1), date) as rate1,
  dictGet(currentDatabase() || '.rates_dict', 'rate', toUInt64(2), date) as rate2,
  dictGet(currentDatabase() || '.rates_dict', 'rate', toUInt64(3), date) as rate3,
  dictGet(currentDatabase() || '.rates_dict', 'rate', toUInt64(4), date) as rate4
FROM numbers(10);

┌───────date─┬────rate1─┬────rate2─┬────rate3─┬────rate4─┐
│ 2021-03-10 │  99.0000 │   0.0000 │ 300.0000 │   0.0000 │
│ 2021-03-11 │  99.0000 │   0.0000 │ 300.0000 │   0.0000 │
│ 2021-03-12 │  99.0000 │   0.0000 │ 300.0000 │   0.0000 │
│ 2021-03-13 │  99.0000 │   0.0000 │ 300.0000 │   0.0000 │
│ 2021-03-14 │ 100.0000 │ 200.0000 │ 300.0000 │ 400.0000 │
│ 2021-03-15 │ 100.0000 │ 200.0000 │   0.0000 │   0.0000 │
│ 2021-03-16 │ 100.0000 │ 200.0000 │   0.0000 │   0.0000 │
│ 2021-03-17 │ 101.0000 │ 200.0000 │   0.0000 │   0.0000 │
│ 2021-03-18 │ 101.0000 │ 200.0000 │   0.0000 │   0.0000 │
│ 2021-03-19 │ 101.0000 │ 200.0000 │   0.0000 │   0.0000 │
└────────────┴──────────┴──────────┴──────────┴──────────┘
```

**Comment by filimonov** [comment]
> Code: 36, e.displayText() = DB::Exception: Code: 36, e.displayText() = DB::Exception: Dictionary structure type of 'range_min' and 'range_max' should be an integer, Date, DateTime, or Enum. Actual 'range_min' and 'range_max' type is Nullable(Date) (version 21.3.3.14 (official build)) (version 21.3.3.14 (official build)) 

@kitaisreal - наверное можно это поддержать.

**Comment by magvan** [comment]
@filimonov 
еще раз все проверил и запустил, заработало. Результат 72. Спасибо большое!

**Comment by den-crane** [comment]
https://github.com/ClickHouse/ClickHouse/issues/21647
