### ISSUE TITLE
В атрибут словаря range_hashed всегда проставляется дефолтное значение, odbc к postgres

### ISSUE THREAD

**Issue by magvan** [ClickHouse/ClickHouse#22021]
Создал таблицу в Postgres.
![image](https://user-images.githubusercontent.com/8927781/112126897-f171e400-8bd5-11eb-939a-58250468369e.png)

Сделал по ней словарь в clickhouse, в словаре видим это
![image](https://user-images.githubusercontent.com/8927781/112127326-5fb6a680-8bd6-11eb-9b83-660b4d0c66e9.png)

**rate есть на самом деле, но заменился на ноль. Это происходит если в описание словаря в xml в range_min/range_max поставить тип UInt64. А если оставить тип Date или DateTime, то поле rate правильно заполняется.** Не понятно как это связано.

Как увидеть эту ошибку:

Создал таблицу в PG.
```
create table pay.rate (
    id bigserial not null primary key,
    currencies varchar(6) not null,
    rate numeric(16,8) not null,
    date_start timestamp not null default now(),
    date_end timestamp default null
);

insert into pay.rate (currencies, rate) values ('USDRUB', 72);
insert into pay.rate (currencies, rate) values ('RUBUSD', 0.014);
```

Настроил odbc в /etc/odbc.ini
```
[DEFAULT]
Driver = postgres_db

[postgres_db]
Description         = PostgreSQL connection to postgres_db
Driver              = /usr/lib/x86_64-linux-gnu/odbc/psqlodbcw.so
Database            = postgres_db
ServerName          = 127.0.0.1
UserName            = postgres
Password            = postgres
Port                = 5432
Protocol            = 9.3
ReadOnly            = No
RowVersioning       = No
ShowSystemTables    = No
ConnSettings        =
```

Создал словарь в xml
```
<dictionary>
    <name>rate</name>
    <source>
        <odbc>
            <connection_string>DSN=postgres_db</connection_string>
            <table>pay.rate</table>
        </odbc>
    </source>
    <lifetime>
        <min>300</min>
        <max>360</max>
    </lifetime>
    <layout>
        <range_hashed/>
    </layout>
    <structure>
        <id>
            <name>id</name>
            <type>UInt64</type>:
        </id>
        <range_min>
            <name>date_start</name>
            <type>UInt64</type>
        </range_min>
        <range_max>
            <name>date_end</name>
            <type>UInt64</type>
        </range_max>
        <attribute>
            <name>rate</name>
            <type>Float64</type>
            <null_value>0</null_value>
        </attribute>
    </structure>
</dictionary>
```
Создал базу что бы видеть словарь
```
CREATE DATABASE rate_t ENGINE = Dictionary;
SELECT * FROM dictionaries.rate;
```
Теперь можно посмотреть словарь
```
SELECT t.* FROM rate_t.rate t
```

**Comment by den-crane** [comment]
>Это происходит если в описание словаря в xml в range_min/range_max поставить тип UInt64. 

так а в PG это (date_start/date_end) числовые типы?

**Comment by magvan** [comment]
> > Это происходит если в описание словаря в xml в range_min/range_max поставить тип UInt64.
> 
> так а в PG это (date_start/date_end) числовые типы?

timestamp

**Comment by den-crane** [comment]
ээээ, ну так и почему вы ожидаете что должно работать?
каким образом timestamp в PG сконвертируется в числовой тип в КХ?

**Comment by magvan** [comment]
> ээээ, ну так и почему вы ожидаете что это должно работать?
> каким образом timestamp в PG сконвертируется в числовой тип в КХ?

судя по словарю в clickhouse он правильно сконвертировал
![image](https://user-images.githubusercontent.com/8927781/112264007-44ed3c00-8c81-11eb-9dc5-ef2aece739fd.png)

Дата из PG  соответствует UInt64 в хаусе 1616406649884000

Вопрос не в этом, почему rate не заполняется?

**Comment by magvan** [comment]
> @den-crane 
> ээээ, ну так и почему вы ожидаете что это должно работать?
> каким образом timestamp в PG сконвертируется в числовой тип в КХ?

Сделал вьюху в PG
```
CREATE VIEW pay.v_rate AS
select
    id,
    currencies,
    rate,
    extract(epoch from date_start)::integer as date_start,
    extract(epoch from date_end)::integer as date_end
from pay.rate;
```
Отдает integer
![image](https://user-images.githubusercontent.com/8927781/112277760-2132f180-8c93-11eb-88c8-16a592f95528.png)

Смотрю что видит словарь в clickhouse
![image](https://user-images.githubusercontent.com/8927781/112277944-593a3480-8c93-11eb-8996-323b8e97cb3a.png)

rate все так же пустой

**Comment by den-crane** [comment]
скорее всего 0 не работает как открытый диапазон, что вообще-то логично, с чего бы.
