### ISSUE TITLE
insert from file for temporary tables

### ISSUE THREAD

**Issue by ospv** [ClickHouse/ClickHouse#22054]
It is possible to insert data from file using clickhouse-client:
`clickhouse-client ... --query 'insert into mytable format CSV < data.csv`

But for temporary tables it is not working because temporary tables are not visible in other sessions.

I suggest to allow 'insert' from file within clickhouse-client session, like select does (select into outfile '...').
For example:
`insert into mytable format CSV fromfile 'data.csv'`

**Comment by den-crane** [comment]
https://clickhouse.tech/docs/en/sql-reference/table-functions/file/ ?

**Comment by ospv** [comment]
> https://clickhouse.tech/docs/en/sql-reference/table-functions/file/ ?
Only works for files on server side.

**Comment by alexey-milovidov** [comment]
Yes, it will be nice to have this feature in client.

**Comment by alexey-milovidov** [comment]
There are some caveats:
\- everything after `FORMAT` section is parsed as table data.

**Comment by amosbird** [comment]
> There are some caveats:
> - everything after `FORMAT` section is parsed as table data.

`LOAD FILE <filename> INTO <table> [FORMAT ...] `

This statement will be rewritten as  `INSERT INTO <table> ...` and have input stream attached to the local file.
