### ISSUE TITLE
ClickHouse SELECT Queries Performance Degraded Significantly When ZooKeeper Cluster Is Shutdown

### ISSUE THREAD

**Issue by jlazdw** [ClickHouse/ClickHouse#22068]
According to the ClickHouse architecture  document, https://clickhouse.tech/docs/en/engines/table-engines/mergetree-family/replication/, "ZooKeeper is not used in SELECT queries because replication does not affect the performance of SELECT and queries run just as fast as they do for non-replicated tables.". I just did the experiment to temporarily shutdown the ZooKeeper cluster used in the ClickHouse cluster. As a result,  in the ClickHouse cluster, each replica showed session time-out and then turned into read-only mode. The real-time queries can still go through and I did not observe any failure on the query path. However, in my experimental set up, the latency of the queries went up, from 100 ms to about 120 ms, in terms of 50%-tile. The 95%-tile latency got even worse, from 200 ms to 350 ms.

I do see that in the Clickhouse server log, the error message on failure to connect to the ZooKeeper Cluster. But other than such ZK connection failure, I do not see any failures reported in the log file. 

All my tables are constructed with Replicated Merge Tree. And I am using ClickHouse 20.7.3.7 release from last year.

Is there an explanation on why the query performance gets worse for Replicated Merge Tree Tables when the ZooKeeper is shutdown.

**Comment by filimonov** [comment]
Do you use any non-standard configuration for the table? select_sequential_consistency? insert_quorum?

How the queries you benchmark look like? How do you benchmark? (do you use clickhouse-benchmark?)

Does it reproduces always (so when you start zookeeper back the problem disappear?)

**Comment by jlazdw** [comment]
We have select_sequential_consistency = 0  and insert_quorum =2.  Before I shut down the ZK cluster for the experiment, I already shutdown the data injection path, so insert_quorum should not matter.

I used clickhouse-benchmark against the Distributed Table node, on a small cluster (8 shards).   For query latency < 40 ms, I do see the 50%-tile latency increased very clearly after the ZK cluster is shutdown. The 95%-tile reported by clickhouse-benchmark varied from run to run and it is hard to make a conclusive answer on whether the latency is increased or not. 

In terms of re-producibility, for a small cluster, once I brought back the ZK cluster, the latency immediately recovered. For the cluster that I reported the earlier result, the cluster is much bigger (250 shards). I can see the clients from one datacenter have the latency recover to normal after the ZK cluster was  brought back.  But the clients from the other datacenter, the latency even did not return back to normal.

**Comment by filimonov** [comment]
Can you compare stacktraces (or perf top / perf record) of your benchmark with and without zookeeper?

**Comment by filimonov** [comment]
> against the Distributed Table node,

what is the type of query? Isn't it a `select count()` query? 

> I am using ClickHouse 20.7.3.7

Can you check one of the latest releases?

**Comment by jlazdw** [comment]
One particular query type is about count. But it is not to count every row in the table. One count example is: 

SELECT COUNT(ID) FROM <some table> PREWHERE CREATION_DATE BETWEEN '2021-03-22 22:48:15' AND '2021-03-22 23:18:15'

I will run the same test on the latest stable release along with the perf tool installed.

**Comment by alexey-milovidov** [comment]
No info provided.
