### ISSUE TITLE
stop service command does not complete

### ISSUE THREAD

**Issue by badvir** [ClickHouse/ClickHouse#2206]
Hello.

The Stop Service command does not complete often.
Occurs often when running for a long time.
SIGTERM seems not to be handled properly.

```
[root@localhost ~]# service clickhouse-server stop
Stop clickhouse-server service: 
```

```
[root@localhost ~]# ps -ef|grep click
clickho+  8277     1  0 Mar26 ?        00:14:15 clickhouse-server --daemon --pid-file=/var/run/clickhouse-server/clickhouse-server.pid --config-file=/etc/clickhouse-server/config.xml
root     14854 14824  0 09:45 pts/0    00:00:00 /bin/sh /usr/sbin/service clickhouse-server stop
root     14861 14854  0 09:45 pts/0    00:00:00 /bin/sh /etc/init.d/clickhouse-server stop
root     14865 14861  0 09:45 pts/0    00:00:02 /bin/sh /etc/init.d/clickhouse-server stop
root     21347 15392  0 10:19 pts/1    00:00:00 grep --color=auto click
```

**<Information>**

**OS : Fedora27**

┌─name──────────────────────┬─value──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ VERSION_FULL              │ ClickHouse 1.1.54370                                                                                                                       │
│ VERSION_DESCRIBE          │ v1.1.54370-stable                                                                                                                          │
│ BUILD_DATE                │ 2018-03-26                                                                                                                                 │
│ BUILD_TYPE                │ Release                                                                                                                                    │
│ SYSTEM                    │ Linux-3.10.0-327.el7.x86_64                                                                                                                │
│ SYSTEM_PROCESSOR          │ x86_64                                                                                                                                     │
│ LIBRARY_ARCHITECTURE      │                                                                                                                                            │
│ CMAKE_VERSION             │ 3.9.6                                                                                                                                      │
│ C_COMPILER                │ /usr/lib64/ccache/gcc                                                                                                                      │
│ C_COMPILER_VERSION        │ 7.2.1                                                                                                                                      │
│ CXX_COMPILER              │ /usr/lib64/ccache/g++                                                                                                                      │
│ CXX_COMPILER_VERSION      │ 7.2.1                                                                                                                                      │
│ C_FLAGS                   │   -D_GLIBCXX_USE_CXX11_ABI=1 -pipe -msse4.1 -msse4.2 -mpopcnt -fno-omit-frame-pointer  -Wall   -O2 -DNDEBUG                                │
│ CXX_FLAGS                 │  -std=c++17  -D_GLIBCXX_USE_CXX11_ABI=1 -pipe -msse4.1 -msse4.2 -mpopcnt  -fno-omit-frame-pointer  -Wall  -Wnon-virtual-dtor  -O2 -DNDEBUG │
│ LINK_FLAGS                │  -static-libgcc -static-libstdc++                                                                                                          │
│ BUILD_COMPILE_DEFINITIONS │                                                                                                                                            │
│ BUILD_INCLUDE_DIRECTORIES │                                                                                                                                            │
│ STATIC                    │ FALSE                                                                                                                                      │
│ USE_EMBEDDED_COMPILER     │                                                                                                                                            │
│ USE_INTERNAL_MEMCPY       │                                                                                                                                            │
│ USE_GLIBC_COMPATIBILITY   │                                                                                                                                            │
│ USE_JEMALLOC              │                                                                                                                                            │
│ USE_TCMALLOC              │ 1                                                                                                                                          │
│ USE_UNWIND                │ 1                                                                                                                                          │
│ USE_ICU                   │ 1                                                                                                                                          │
│ USE_MYSQL                 │ 1                                                                                                                                          │
│ USE_RE2_ST                │ 1                                                                                                                                          │
│ USE_VECTORCLASS           │                                                                                                                                            │
│ USE_RDKAFKA               │ 1                                                                                                                                          │
│ USE_CAPNP                 │ 1                                                                                                                                          │
│ USE_Poco_DataODBC         │ 1                                                                                                                                          │
│ USE_Poco_MongoDB          │ 1                                                                                                                                          │
│ USE_Poco_NetSSL           │ 1                                                                                                                                          │
└───────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

**Comment by den-crane** [comment]
I experience the same issue. 50/50 need to kill -9 because stop works too long (I waited 1 hour and gave up). 
It seems related to long merges (some of merges take 10 - 12 hours on my env.). So I am checking system.merges before stop initiating.

**Comment by badvir** [comment]
Unfortunately, there were no merge tasks and no queries in my case.

**Comment by alexey-milovidov** [comment]
It shouldn't be related to long merges or any other background operations as we are calcelling them on shutdown.

Could you please provide a stack trace of your server when it hangs on shutdown?
Just type `sudo gdb -batch -ex 't apply all bt' -p $(pidof clickhouse-server)`

**Comment by alexey-milovidov** [comment]
This issue was fixed in recent releases.
