### ISSUE TITLE
runningDifference() across blocks

### ISSUE THREAD

**Issue by simPod** [ClickHouse/ClickHouse#22098]
So currently `runningDifference()` computes delta only inside single block.

This FR is about making it work across multiple blocks.

I understand that it is not suited to be run on continuous data. Actually, I can't really imagine the use case in production env where I'd like to compute eg. running difference for 2 days of data which I suppose would be across multiple blocks.

Or, I might also be wrong and understand the limitation poorly 🤔

**Comment by alexey-milovidov** [comment]
This will be addressed with lag/lead functions from this PR: #21895

**Comment by den-crane** [comment]
Now runningDifference works in multi-threading with unordered blocks. If it will been fixed then it became the same as window function.

```
set max_block_size=3

select number - x from (
SELECT number , any(number) over (rows between 1 preceding and current row)  x
FROM numbers(10))

┌─minus(number, x)─┐
│                0 │
│                1 │
│                1 │
└──────────────────┘
┌─minus(number, x)─┐
│                1 │
│                1 │
│                1 │
└──────────────────┘
┌─minus(number, x)─┐
│                1 │
│                1 │
│                1 │
└──────────────────┘
┌─minus(number, x)─┐
│                1 │
└──────────────────┘
```

**Comment by alexey-milovidov** [comment]
@den-crane Never thought about this usage of window functions. Thank you!

**Comment by den-crane** [comment]
oops,

it should be  between 1 preceding and 1 preceding

```
select number - x from (
SELECT number , any(number) over (rows between 1 preceding and 1 preceding)  x
FROM numbers(10))
```

**Comment by alexey-milovidov** [comment]
The functions `runningDifference`, `runningAccumulate`, `neighbor` will not be improved
because their implementation is not well aligned with query execution pipeline and more like a hack.

This is in favor of window functions.

**Comment by alexey-milovidov** [comment]
#16484
