### ISSUE TITLE
DB::Exception: Inserting field of type String into ColumnAggregateFunction. Expected AggregateFunctionState: While executing MergingAggregatedTransform

### ISSUE THREAD

**Issue by moon03432** [ClickHouse/ClickHouse#22108]
(you don't have to strictly follow this form)

**Describe the bug**
In a distributed (and unbalanced) table, querying argMax(bitmap, xxx) reports bug on nodes with almost no data.

**Does it reproduce on recent release?**
Yes. Reproduced on version 21.1.2 and 20.4.8.99 
[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

**How to reproduce**
* Which ClickHouse server version to use
20.4.8.99

* Which interface to use, if matters
clickhouse-client

* Non-default settings, if any
No

* `CREATE TABLE` statements for all tables involved
`CREATE TABLE default.dist_cdp_segments
(
    `seg_id` String,
    `mid_seqs` AggregateFunction(groupBitmap, UInt32) CODEC(NONE),
    `cardinality` UInt32,
    `is_manual` UInt8,
    `create_time` DateTime DEFAULT now()
)
ENGINE = Distributed('cdpck', 'default', 'cdp_segments') 

CREATE TABLE default.cdp_segments
(
    `seg_id` String,
    `mid_seqs` AggregateFunction(groupBitmap, UInt32) CODEC(NONE),
    `cardinality` UInt32,
    `is_manual` UInt8,
    `create_time` DateTime DEFAULT now()
)
ENGINE = ReplacingMergeTree()
ORDER BY seg_id
SETTINGS index_granularity = 1 
`

* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
data is unbalanced. error occured on nodes with almost no data. it works on nodes with enough data.

* Queries to run that lead to unexpected result
`SELECT bitmapMax(argMax(mid_seqs, create_time)) FROM dist_cdp_segments WHERE seg_id = '29ffb173a754403d8f5ed801ca7d6f87'`

**Expected behavior**

return results without error.
![image](https://user-images.githubusercontent.com/11847340/112423776-3c266400-8d6e-11eb-8388-6a0aab3e97d6.png)

**Error message and/or stacktrace**

![image](https://user-images.githubusercontent.com/11847340/112423889-6d9f2f80-8d6e-11eb-85e2-778eb7923cd9.png)

**Additional context**

**Comment by alexey-milovidov** [comment]
The issue is fixed.

20.9:
```
SELECT bitmapMax(argMax(x, y))
FROM remote('127.0.0.{2,3}', view(
    SELECT
        groupBitmapState(toUInt32(number)) AS x,
        number AS y
    FROM numbers(10)
    GROUP BY number
))

Query id: 3271c235-c0d8-42c5-ba59-1922786c7f34

Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 20.9.7 revision 54439.

ClickHouse server version is older than ClickHouse client. It may indicate that the server is out of date and can be upgraded.

↑ Progress: 20.00 rows, 160.00 B (183.50 rows/s., 1.47 KB/s.)  99%
0 rows in set. Elapsed: 0.110 sec. 

Received exception from server (version 20.9.7):
Code: 49. DB::Exception: Received from localhost:9000. DB::Exception: Inserting field of type String into ColumnAggregateFunction. Expected AggregateFunctionState: While executing MergingAggregatedTransform.
```

21.7:
```
milovidov-desktop :) SELECT bitmapMax(argMax(x, y)) FROM remote('127.0.0.{2,3}', view(SELECT groupBitmapState(toUInt32(number)) AS x, number AS y FROM numbers(10) GROUP BY number))

SELECT bitmapMax(argMax(x, y))
FROM remote('127.0.0.{2,3}', view(
    SELECT
        groupBitmapState(toUInt32(number)) AS x,
        number AS y
    FROM numbers(10)
    GROUP BY number
))

Query id: f243af78-e08e-44f6-8c30-216908f5abdd

┌─bitmapMax(argMax(x, y))─┐
│                       9 │
└─────────────────────────┘
```
