### ISSUE TITLE
INNER ANY JOIN bug (version 21.4.1.1) missing rows in result.

### ISSUE THREAD

**Issue by wangzhen11aaa** [ClickHouse/ClickHouse#22106]
(you don't have to strictly follow this form)

**Describe the bug**
A clear and concise description of what works not as it is supposed to.
INNER ANY join missing rows.

**Does it reproduce on recent release?**
[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

**How to reproduce**

* Which ClickHouse server version to use
* 21.4.1.1
* 
Table Schema
sy-buffer-10-12-3-12.m6v.idc.sprucetec.com :) show create table TableA;

SHOW CREATE TABLE TableA

Query id: 3875b532-aad7-4c0a-b42f-06e1119f62b8

┌─statement───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ CREATE TABLE default.TableA
(
    `id` Int32,
    `c1` Int32,
    `c2` Int32
)
ENGINE = MergeTree
ORDER BY id
SETTINGS index_granularity = 8192 │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

1 rows in set. Elapsed: 0.001 sec.

sy-buffer-10-12-3-12.m6v.idc.sprucetec.com :) show create table TableB;

SHOW CREATE TABLE TableB

Query id: b392d01c-493d-4f08-86fe-57bc42730296

┌─statement─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ CREATE TABLE default.TableB
(
    `id1` Int32,
    `c3` Int32,
    `c4` Int32
)
ENGINE = MergeTree
ORDER BY id1
SETTINGS index_granularity = 8192 │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

Data in table
sy-buffer-10-12-3-12.m6v.idc.sprucetec.com :) select * from TableB;

SELECT *
FROM TableB

Query id: 5e216cbc-7e0d-4d46-9bd9-d10cfb9f48dd

┌─id1─┬──c3─┬──c4─┐
│   1 │ 300 │ 401 │
└─────┴─────┴─────┘
┌─id1─┬──c3─┬──c4─┐
│   1 │ 300 │ 400 │
└─────┴─────┴─────┘

2 rows in set. Elapsed: 0.002 sec.

sy-buffer-10-12-3-12.m6v.idc.sprucetec.com :) select * from TableA;

SELECT *
FROM TableA

Query id: 751c2d84-0748-463d-9ea9-30815bbdf663

┌─id─┬──c1─┬──c2─┐
│  1 │ 100 │ 202 │
└────┴─────┴─────┘
┌─id─┬──c1─┬──c2─┐
│  1 │ 100 │ 201 │
└────┴─────┴─────┘
┌─id─┬──c1─┬──c2─┐
│  1 │ 100 │ 200 │
└────┴─────┴─────┘

3 rows in set. Elapsed: 0.002 sec.
* Queries to run that lead to unexpected result

**Expected behavior**

sy-buffer-10-12-3-12.m6v.idc.sprucetec.com :) select * from (SELECT * from TableA) as A ANY INNER JOIN (SELECT * from TableB) as B on A.id = B.id1;

SELECT *
FROM
(
    SELECT *
    FROM TableA
) AS A
ANY INNER JOIN
(
    SELECT *
    FROM TableB
) AS B ON A.id = B.id1

Query id: 2478dece-11d6-4352-94fc-e19b181e9f30

┌─id─┬──c1─┬──c2─┬─id1─┬──c3─┬──c4─┐
│  1 │ 100 │ 200 │   1 │ 300 │ 401 │
└────┴─────┴─────┴─────┴─────┴─────┘

1 rows in set. Elapsed: 0.004 sec.

Expected Answer:

SELECT *
FROM
(
    SELECT *
    FROM TableA
) AS A
ANY INNER JOIN
(
    SELECT *
    FROM TableB
) AS B ON A.id = B.id1

┌─id─┬──c1─┬──c2─┬─id1─┬──c3─┬──c4─┐
│  1 │ 100 │ 200 │   1 │ 300 │ 400 │
│  1 │ 100 │ 201 │   1 │ 300 │ 400 │
│  1 │ 100 │ 202 │   1 │ 300 │ 400 │
└────┴─────┴─────┴─────┴─────┴─────┘

3 rows in set. Elapsed: 0.003 sec.

**Error message and/or stacktrace**

**Additional context**

**Comment by wangzhen11aaa** [comment]
May be LEFT ANY JOIN is the right solution.

**Comment by den-crane** [comment]
Starting from CH 20...  INNER ANY JOIN make distinct rows for both tables left and right.

```
--any_join_distinct_right_table_keys arg                         Enable old ANY JOIN logic with many-to-one left-to-right table keys mapping for all ANY JOINs. It leads to confusing not equal
                                                                   results for 't1 ANY LEFT JOIN t2' and 't2 ANY RIGHT JOIN t1'. ANY RIGHT JOIN needs one-to-many keys mapping to be consistent
                                                                   enabled, the query will be performed anyway, otherwise the error will be reported.

```

```
# cat etc/clickhouse-server/users.d/z_user_substitutes.xml
<?xml version="1.0"?>
<yandex>
    <profiles>
        <default>
                <joined_subquery_requires_alias>0</joined_subquery_requires_alias>
                <any_join_distinct_right_table_keys>1</any_join_distinct_right_table_keys>
        </default>
    </profiles>
```
</yandex>
