### ISSUE TITLE
Crash when querying HDFS table

### ISSUE THREAD

**Issue by Lishengchao** [ClickHouse/ClickHouse#22115]
problem ：When I execute a query with clikchouse, the clickhouse service crashes.

Hadoop version: 3.0.0+cdh6.3.2
clickhouse version: 20.8.5.45

Situation description:
1. Data is stored in HDFS
2. HDFS engine used by clickhouse
3. Data flow in real time: log->kafka->flume->hdfs->clickhouse read

Table building statement:
CREATE TABLE event.ods_triggerChargeEquInfo_tmp
(
    `batteryNo` String,
    `dcChargerHVSwitchStatus` Int64,
    `chargerShelvesEnableStatus` Int64,
    `chargeNo` String,
    `version` String,
    `smartDCElectricMeterNo` String,
    `chagerDeviceNo` String,
    `platformKey` String,
    `chargerShelvesWorkStatus` Int64,
    `eventKey` String,
    `dcChagerOperateStatus` Int64,
    `singleChargeTotalkwh` Float64,
    `singleSpikeTotalkwh` Float64,
    `singlePeakTotalkwh` Float64,
    `singleAverageTotalkwh` Float64,
    `singleValleyTotalkwh` Float64,
    `chargerShelvesNo` String,
    `energyofSmartDCElectricMeter` String,
    `allDCChargerEmergencyShutdown` Int64,
    `batteryInShelvesStatus` Int64,
    `timestamp` String,
    `chargerStartChargeTime` String,
    `chargerEndChargeTime` String,
    `orderId` String
)
ENGINE = HDFS('hdfs://xxx/user/flume/data/triggerChargeEquInfo_tmp/*',
 'JSONEachRow')

Query statement executed：
SELECT `timestamp`
,chargerShelvesNo
,formatDateTime(toDate(toDateTime((toInt64(`timestamp` )/1000))),'%Y-%m') as day_month
,chargerShelvesWorkStatus
,platformKey
,smartDCElectricMeterNo
,singleChargeTotalkwh
from event.ods_triggerChargeEquInfo_tmp
where batteryNo != '0'
and singleChargeTotalkwh > 0
and chargerShelvesWorkStatus in ('2','3','4','5')
LIMIT 10

Crash log：
2021.03.25 13:09:51.283474 [ 24631 ] {} <Fatal> BaseDaemon: ########################################
2021.03.25 13:09:51.283514 [ 24631 ] {} <Fatal> BaseDaemon: (version 20.8.5.45 (official build), no build id) (from thread 1618) (query_id: 30b7f991-31cc-4fec-9d83-b59d903904c4) Received signal Segmentation fault (11)
2021.03.25 13:09:51.283534 [ 24631 ] {} <Fatal> BaseDaemon: Address: 0x18 Access: read. Address not mapped to object.
2021.03.25 13:09:51.283553 [ 24631 ] {} <Fatal> BaseDaemon: Stack trace: 0x15d8492b 0xe64d87d 0x163a2b9e 0x16293c55 0x16295ae4 0xe639b47 0xe638093 0x7f54c3603ea5 0x7f54c2f208dd
2021.03.25 13:09:51.284055 [ 24631 ] {} <Fatal> BaseDaemon: 3. /build/obj-x86_64-linux-gnu/../src/IO/ReadBufferFromHDFS.cpp:41: DB::ReadBufferFromHDFS::nextImpl() @ 0x15d8492b in /usr/lib/debug/usr/bin/clickhouse
2021.03.25 13:09:51.284364 [ 24631 ] {} <Fatal> BaseDaemon: 4. /build/obj-x86_64-linux-gnu/../src/IO/ReadBuffer.h:60: DB::loadAtPosition(DB::ReadBuffer&, DB::Memory<Allocator<false, false> >&, char*&) @ 0xe64d87d in /usr/lib/debug/usr/bin/clickhouse
2021.03.25 13:09:51.284855 [ 24631 ] {} <Fatal> BaseDaemon: 5. /build/obj-x86_64-linux-gnu/../src/Formats/JSONEachRowUtils.cpp:15: DB::fileSegmentationEngineJSONEachRowImpl(DB::ReadBuffer&, DB::Memory<Allocator<false, false> >&, unsigned long) @ 0x163a2b9e in /usr/lib/debug/usr/bin/clickhouse
2021.03.25 13:09:51.285395 [ 24631 ] {} <Fatal> BaseDaemon: 6. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:1867: DB::ParallelParsingBlockInputStream::segmentatorThreadFunction(std::__1::shared_ptr<DB::ThreadGroupStatus>) @ 0x16293c55 in /usr/lib/debug/usr/bin/clickhouse
2021.03.25 13:09:51.286068 [ 24631 ] {} <Fatal> BaseDaemon: 7. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:4206: ThreadFromGlobalPool::ThreadFromGlobalPool<void (DB::ParallelParsingBlockInputStream::*)(std::__1::shared_ptr<DB::ThreadGroupStatus>), DB::ParallelParsingBlockInputStream*, std::__1::shared_ptr<DB::ThreadGroupStatus> >(void (DB::ParallelParsingBlockInputStream::*&&)(std::__1::shared_ptr<DB::ThreadGroupStatus>), DB::ParallelParsingBlockInputStream*&&, std::__1::shared_ptr<DB::ThreadGroupStatus>&&)::'lambda'()::operator()() const @ 0x16295ae4 in /usr/lib/debug/usr/bin/clickhouse
2021.03.25 13:09:51.286214 [ 24631 ] {} <Fatal> BaseDaemon: 8. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/atomic:856: ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xe639b47 in /usr/lib/debug/usr/bin/clickhouse
2021.03.25 13:09:51.286255 [ 24631 ] {} <Fatal> BaseDaemon: 9. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2615: void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()> >(void*) @ 0xe638093 in /usr/lib/debug/usr/bin/clickhouse
2021.03.25 13:09:51.286271 [ 24631 ] {} <Fatal> BaseDaemon: 10. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
2021.03.25 13:09:51.286285 [ 24631 ] {} <Fatal> BaseDaemon: 11. __clone @ 0xfe8dd in /usr/lib64/libc-2.17.so

**Comment by alexey-milovidov** [comment]
Looks similar to #13406.

**Comment by Lishengchao** [comment]
> Looks similar to #13406.

During this period of time, I have been observing, and I found that clikchouse would crash from time to time when reading HDFS.
The first case: too many queries;
The second case: the time of the crash is uncertain, sometimes one or two hours, sometimes three or four days.

The above crash logs are similar.
Today clikhouse crashed again, the log is as follows (similar to the last crash log):
2021.03.31 16:44:12.345165 [ 23720 ] {} <Fatal> BaseDaemon: ########################################
2021.03.31 16:44:12.345200 [ 23720 ] {} <Fatal> BaseDaemon: (version 20.8.5.45 (official build), no build id) (from thread 21945) (query_id: b40529c3-c1cc-401e-98e4-85dfa91930c3) Received signal Segmentation fault (11)
2021.03.31 16:44:12.345218 [ 23720 ] {} <Fatal> BaseDaemon: Address: 0x18 Access: read. Address not mapped to object.
2021.03.31 16:44:12.345228 [ 23720 ] {} <Fatal> BaseDaemon: Stack trace: 0x15d8492b 0xe64d87d 0x163a2b9e 0x16293c55 0x16295ae4 0xe639b47 0xe638093 0x7f97b9742ea5 0x7f97b905f8dd
2021.03.31 16:44:12.345750 [ 23720 ] {} <Fatal> BaseDaemon: 3. /build/obj-x86_64-linux-gnu/../src/IO/ReadBufferFromHDFS.cpp:41: DB::ReadBufferFromHDFS::nextImpl() @ 0x15d8492b in /usr/lib/debug/usr/bin/clickhouse
2021.03.31 16:44:12.346060 [ 23720 ] {} <Fatal> BaseDaemon: 4. /build/obj-x86_64-linux-gnu/../src/IO/ReadBuffer.h:60: DB::loadAtPosition(DB::ReadBuffer&, DB::Memory<Allocator<false, false> >&, char*&) @ 0xe64d87d in /usr/lib/debug/usr/bin/clickhouse
2021.03.31 16:44:12.346567 [ 23720 ] {} <Fatal> BaseDaemon: 5. /build/obj-x86_64-linux-gnu/../src/Formats/JSONEachRowUtils.cpp:15: DB::fileSegmentationEngineJSONEachRowImpl(DB::ReadBuffer&, DB::Memory<Allocator<false, false> >&, unsigned long) @ 0x163a2b9e in /usr/lib/debug/usr/bin/clickhouse
2021.03.31 16:44:12.347083 [ 23720 ] {} <Fatal> BaseDaemon: 6. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:1867: DB::ParallelParsingBlockInputStream::segmentatorThreadFunction(std::__1::shared_ptr<DB::ThreadGroupStatus>) @ 0x16293c55 in /usr/lib/debug/usr/bin/clickhouse
2021.03.31 16:44:12.347769 [ 23720 ] {} <Fatal> BaseDaemon: 7. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:4206: ThreadFromGlobalPool::ThreadFromGlobalPool<void (DB::ParallelParsingBlockInputStream::*)(std::__1::shared_ptr<DB::ThreadGroupStatus>), DB::ParallelParsingBlockInputStream*, std::__1::shared_ptr<DB::ThreadGroupStatus> >(void (DB::ParallelParsingBlockInputStream::*&&)(std::__1::shared_ptr<DB::ThreadGroupStatus>), DB::ParallelParsingBlockInputStream*&&, std::__1::shared_ptr<DB::ThreadGroupStatus>&&)::'lambda'()::operator()() const @ 0x16295ae4 in /usr/lib/debug/usr/bin/clickhouse
2021.03.31 16:44:12.347904 [ 23720 ] {} <Fatal> BaseDaemon: 8. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/atomic:856: ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xe639b47 in /usr/lib/debug/usr/bin/clickhouse
2021.03.31 16:44:12.347945 [ 23720 ] {} <Fatal> BaseDaemon: 9. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2615: void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()> >(void*) @ 0xe638093 in /usr/lib/debug/usr/bin/clickhouse
2021.03.31 16:44:12.347966 [ 23720 ] {} <Fatal> BaseDaemon: 10. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
2021.03.31 16:44:12.347979 [ 23720 ] {} <Fatal> BaseDaemon: 11. __clone @ 0xfe8dd in /usr/lib64/libc-2.17.so
~

How can I completely solve my problem, #13406 Can this solve my problem? what should I do？

**Comment by alexey-milovidov** [comment]
@kssenii are trying to reproduce this issue with HDFS Docker image but are not being able to reproduce it yet.
Any help with reproducing example is appreciated.

**Comment by alexey-milovidov** [comment]
Duplicate #13406.
