### ISSUE TITLE
orc file uses zlib to compress data, not support import?

### ISSUE THREAD

**Issue by melin** [ClickHouse/ClickHouse#22111]
orc file uses zlib to compress data, not support import?

**Comment by filimonov** [comment]
I expect it to work. Did you try that?

**Comment by melin** [comment]
> I expect it to work. Did you try that?

execution failure

**Comment by alexey-milovidov** [comment]
How excatly did it fail? Could you please provide an example to reproduce?

**Comment by melin** [comment]
> How excatly did it fail? Could you please provide an example to reproduce?

Not related to zlib compression, orc record field name is uppercase letter, table field name is lowercase letter, inconsistent result
