### ISSUE TITLE
Allow writes into system.zookeeper table

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#22130]
**Use case**
Manually modify the contents of ZooKeeper.
Not for normal usage scenarios... mostly for operations engineers.

**Describe the solution you'd like**

Allow INSERT. It should contain only subset of the columns, because some of the columns in `system.zookeeper` table (like numChildren, ctime, etc...) cannot be specified explicitly.

INSERT will perform multiple create operations.

Add a setting to perform set operations (update existing nodes) instead of creating new nodes.

**Additional context**

Also it will be nice to allow "full scan" queries to `system.zookeeper` table to quickly creating dumps.
It can be filtered by condition on prefix of path.

**Comment by KochetovNicolai** [comment]
1. Probably you can't change version as well, but we indeed can check it in zk transaction. Version should be optional (it's also ok if user is not allowed to specify it). I think it would be also logical to recursively create all parents for a node.
2. I think we can ignore returning any value (but should throw an exception if needed).
3. Yes.
4. Yes.
5. I think we need to create a transaction for multiple rows.
