### ISSUE TITLE
Top N of unique string

### ISSUE THREAD

**Issue by hatrena** [ClickHouse/ClickHouse#22141]
Hi,

In the main table, there is a string column for `ip` which is unique (mostly) per document. I want to return the top 10 IPs for this table (few billions of documents). Is there any performant way to do so?

**Comment by den-crane** [comment]
What do you mean top10 if they are uniq?

**Comment by hatrena** [comment]
to return something like:

```
┌───count()─┬─click_ip──────┐
│ 10024205 │ 47.253.44.xxx │
│  9929538 │ 47.253.32.xxx │
│  9927342 │ 47.253.32.xxx │
│  9886397 │ 47.90.248.xxx │
│  9876835 │ 47.253.33.xxx │
│  9866026 │ 47.253.40.xxx │
│  9850891 │ 47.253.44.xxx │
│  9832420 │ 47.89.183.xxx │
│  9830460 │ 47.253.47.xxx │
│  9763984 │ 47.252.11.xxx │
└──────────┴───────────────┘
```

**Comment by hatrena** [comment]
something similar to `topK(N)` with count as well but performant.

**Comment by alexey-milovidov** [comment]
Naive solution is:

```
SELECT click_ip, count() AS c FROM table GROUP BY click_ip ORDER BY c DESC LIMIT 10
```

It may not fit in memory, but you can raise `max_memory_usage` and enable `max_bytes_before_external_group_by`.
Then the query will be able to proceed even with multiple billion records. But it can be slow.

Optimized variant is:

```
SELECT click_ip, count() AS c FROM table
WHERE click_ip IN
(
    SELECT click_ip FROM table ORDER BY rand() LIMIT 1000000
)
GROUP BY click_ip ORDER BY c DESC LIMIT 10
```

It relies on assumption that top 10 IP addresses most likely will be present in random sample of a million records from a table. It's not guaranteed to be true but it is almost always true.

This query can be slightly more optimal:

```
SELECT click_ip, count() AS c FROM table
WHERE click_ip IN
(
    SELECT click_ip FROM table WHERE rand() % 10000 = 123
)
GROUP BY click_ip ORDER BY c DESC LIMIT 10
```

And if data in your table is uniformly distributed, you can also use this trick:
```
SET max_rows_to_group_by = 1000000, group_by_overflow_mode = 'any';
SELECT click_ip, count() AS c FROM table GROUP BY click_ip ORDER BY c DESC LIMIT 10;
```

**Comment by hatrena** [comment]
The average response from the naive solution is `10 rows in set. Elapsed: 15.929 sec. Processed 204.23 million rows, 20.28 GB (12.82 million rows/s., 1.27 GB/s.)` which is much better than the other solutions somehow. those take minutes.

**Comment by alexey-milovidov** [comment]
Great!

By tuning the constants of the optimized variants (with subqueries) you can get better response time.
