### ISSUE TITLE
ORDER BY GROUP BY number

### ISSUE THREAD

**Issue by kokizzu** [ClickHouse/ClickHouse#22154]
**Use case**
Simpler query, especially when multiple column group by
``` 
SELECT some_long_column, COUNT(*)
FROM bla
GROUP BY 1
ORDER BY 1
```

**Describe the solution you'd like**
it's better if it can ORDER/GROUP BY number, where number indicating the position of selected column (this supported in most databases: PostgreSQL/MySQL/MSSQL).

**Additional context**

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/2592
