### ISSUE TITLE
Performance comparison with MySql HeatWave

### ISSUE THREAD

**Issue by yahorsi** [ClickHouse/ClickHouse#22169]
Hu Guys,

Recently Oracle has developed a columnar engine called Heat Wave - https://www.oracle.com/mysql/heatwave/.
It is available only in the Oracle Cloud, works as a "transparent" engine, which means, the query can still be executed on the MySql server with no changes, but if the table is loaded in the HeatWave cluster, then it can be executed on the new columnar engine.

This is very fresh, new, vectorized, columnar, distributed, low price (cluster with 3 servers and 1.5 TB of memory costs less than 1k month). So, would be really cool to have a perf comparison, like ClickHouse on 2 nodes with 1TB memory vs ClickHouse cluster of 3 nodes (minimal configuration, where 1 node is just MySql node and 2 nodes are used as Heat Wave). 

Additionally, would be great to have a similar comparison to the Microsoft SQL server that has support for the clustered column store index and, especially, to the **Sql Server Analysis Services**. With the last one, it's not sort of the apples to apples, but it still the columnar engine that **they claim** is the fastest (well, we know who's really the fastest but...)

Thanks

PS:
Guys under the ClickHouse, I love you :)

**Comment by melvynator** [comment]
Thank you for your interest in ClickHouse and for your love of ClickHouse. Currently we don't provide any benchmark against HeatWave. There is multiple reasons to it.

1. We don't see this product being used a lot on the field. The time invested in doing a benchmark against HeatWave is not going to benefit our broader community. A benchmark should be done very scientifically, it's not a trivial process and it takes a long time. 

2. HeatWave is not remotely open, it's not open source, not open code, there is nothing open about it, making the whole process even more complex.

3. The term of service of Oracle cloud forbid us to run any benchmark against them as stated below:

> You may not, and may not cause or permit others to: (a) ... (b) perform or disclose any benchmarking or availability testing of the Services; (c) perform or disclose any performance or vulnerability testing of the Services without Oracle’s prior written approval, or perform or disclose network discovery, port and service identification, vulnerability scanning, password cracking or remote access testing of the Services; or (d) use the Services to perform cyber currency or crypto currency mining ((a) through (d) ...

I hope this answer your question. If you want to see our available benchmark, you can go here: https://clickhouse.com/benchmark/dbms/#[100000000,[%22ClickHouse%22,%22Vertica%22,%22Greenplum%22],[%221%22,%222%22 

I'm closing as I feel like this answer the topic but feel free to reopen if you have any follow up questions.

**Comment by alexey-milovidov** [comment]
@yahorsi It will be interesting to see the results of HeatWave.
We have prepared a benchmark suite ClickBench: https://benchmark.clickhouse.com/
that allows to quickly submit and validate the results independently.

Now we need your help adding HeatWave.

**Comment by yahorsi** [comment]
@alexey-milovidov I can sure do it. Do you guys have any instructions on how to perform the benchmark? HW is built on top of the MySql, it will require small changes in the DDL to enable HW acceleration. Also, Heatwave supports a cluster of servers with a minimum of 1 server which is 16 cores * 512GB of memory + some storage, so how many servers should be in the cluster? Should I make several tests on the different cluster sizes?

**Comment by alexey-milovidov** [comment]
Here is the methodology of the benchmark: https://github.com/ClickHouse/ClickBench/
You can collect many results on different configurations.
