### ISSUE TITLE
clickhouse's permission issue

### ISSUE THREAD

**Issue by geekboood** [ClickHouse/ClickHouse#22184]
I encounter a permission issue when I try to use clickhouse on ubuntu and data dir in another volume. Here is what I have done. 
`sudo ln -s /media/8t/clickhouse /var/lib/clickhouse`
and the permission info about /media/8t/clickhouse folder looks like this:
```user@machine:/media/8t$ ll
total 12
drwx------ 3 user       user       4096 3月  27 01:44 ./
drwxr-xr-x 9 root       root       4096 3月  21 15:17 ../
drwxr-x--- 4 clickhouse clickhouse 4096 3月  27 01:45 clickhouse/
```
when I try to use `sudo -u clickhouse /usr/bin/clickhouse-server --config-file /etc/clickhouse-server/config.xml` command to start clickhouse, I always get this error: ` <Error> Application: DB::ErrnoException: Cannot open file /var/lib/clickhouse/status, errno: 13, strerror: Permission denied`. Do you guys have any idea about how to solve this? My clickhouse version is `Starting ClickHouse 21.3.3.14 with revision 54448, build id: 7C39F44C9AD4D3BA36D74775616894F60A552276`, and it is installed from clickhouse's ubuntu repo.

**Comment by filimonov** [comment]
```
sudo chown -R clickhouse:clickhouse /var/lib/clickhouse/
```
