### ISSUE TITLE
what is the recommended config to use both replicaMergeTree and replication of server level 

### ISSUE THREAD

**Issue by xinchen0104** [ClickHouse/ClickHouse#2220]
What is the origin purpose to design replicaMergeTree since there is already replication in cluster config? Should I create replicaMergeTree in nodes that are also replications of one shard?

**Comment by xinchen0104** [comment]
My config:

`        <rrc_ck_cluster>
            <shard>
                <internal_replication>false</internal_replication>
                <replica>
                    <host>ch-00a</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>ch-00b</host>
                    <port>9000</port>
                </replica>
            </shard>

            <shard>
                <internal_replication>false</internal_replication>
                <replica>
                    <host>ch-01a</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>ch-01b</host>
                    <port>9000</port>
                </replica>
            </shard>
        </rrc_ck_cluster>`

My create sql:

host:ch-00a
`CREATE TABLE default.zk_local ( id Int64,  name String,  age Int64,  created_at Date) ENGINE = ReplicatedMergeTree('/clickhouse/tables/00/zk_cluster', 'a', created_at, id, id, 8192);`
host:ch-00b
`CREATE TABLE default.zk_local ( id Int64,  name String,  age Int64,  created_at Date) ENGINE = ReplicatedMergeTree('/clickhouse/tables/00/zk_cluster', 'b', created_at, id, id, 8192);`
host:ch-01a
`CREATE TABLE default.zk_local ( id Int64,  name String,  age Int64,  created_at Date) ENGINE = ReplicatedMergeTree('/clickhouse/tables/01/zk_cluster', 'a', created_at, id, id, 8192);`
host:ch-01b
`CREATE TABLE default.zk_local ( id Int64,  name String,  age Int64,  created_at Date) ENGINE = ReplicatedMergeTree('/clickhouse/tables/01/zk_cluster', 'b', created_at, id, id, 8192);`
host:all
CREATE TABLE default.zk_cluster ( id Int64,  name String,  age Int64,  created_at Date) ENGINE = Distributed(rrc_ck_cluster, default, zk_local, id);

**Comment by meolu** [comment]
there are two way to create distributed table. 
# 1、Without Zookeeper
refer to [this test script](https://github.com/yandex/ClickHouse/blob/0114b69f6180740848b5d3acef4804fa5ac87134/dbms/tests/integration/test_distributed_ddl/test.py#L267)
## config.xml
```xml
        <rrc_ck_cluster_without_zookeeper>
            <shard>
                <!-- the most important params internal_replication = false-->
                <internal_replication>false</internal_replication>
                <replica>
                    <host>ch-00a</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>ch-00b</host>
                    <port>9000</port>
                </replica>
            </shard>

            <shard>
                <internal_replication>false</internal_replication>
                <replica>
                    <host>ch-01a</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>ch-01b</host>
                    <port>9000</port>
                </replica>
            </shard>
        </rrc_ck_cluster_without_zookeeper>
```

## DDL
```sql
CREATE TABLE default.zk_local ( id Int64,  name String,  age Int64,  created_at Date) 
ENGINE = MergeTree(created_at, id, id, 8192);

CREATE TABLE default.zk_cluster ( id Int64,  name String,  age Int64,  created_at Date) 
ENGINE = Distributed(rrc_ck_cluster_without_zookeeper, default, zk_local, id)
```

# With Zookeeper
## config.xml
refer to [config.xml](https://github.com/yandex/ClickHouse/blob/0114b69f6180740848b5d3acef4804fa5ac87134/dbms/tests/integration/test_distributed_ddl/configs/config.d/clusters.xml#L7)
```xml
        <rrc_ck_cluster_with_zookeeper>
            <shard>
                <!-- the most important params internal_replication = true-->
                <internal_replication>true</internal_replication>
                <replica>
                    <host>ch-00a</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>ch-00b</host>
                    <port>9000</port>
                </replica>
            </shard>

            <shard>
                <internal_replication>false</internal_replication>
                <replica>
                    <host>ch-01a</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>ch-01b</host>
                    <port>9000</port>
                </replica>
            </shard>
        </rrc_ck_cluster_with_zookeeper>
```

## DDL
refer to [test](https://github.com/yandex/ClickHouse/blob/0114b69f6180740848b5d3acef4804fa5ac87134/dbms/tests/integration/test_distributed_ddl/test.py#L211)
```sql
CREATE TABLE default.zk_local ( id Int64,  name String,  age Int64,  created_at Date) ENGINE = ReplicatedMergeTree('/clickhouse/tables/00/zk_cluster', 'b', created_at, id, id, 8192);

CREATE TABLE default.zk_cluster ( id Int64,  name String,  age Int64,  created_at Date) ENGINE = Distributed(rrc_ck_cluster_with_zookeeper, default, zk_local, id);
```

#  summary
now, you can understand what's the difference of with-zookeeper and without-zookeeper.  `<internal_replication>false</internal_replication>`, clickhouse will sync the data to other nodes while the value is set to false, then the DDL should be writed without zookeeper.

@alexey-milovidov @proller is that right ?

# 联系我
如果是中国的同学，可以加微信讨论 `wu-shuiyong`（请附上名字和公司，谢谢）

**Comment by alexey-milovidov** [comment]
The difference is that internal replication will repair data automatically after failures. It keeps data 100% consistent and byte-identical.

While the "replication" through Distributed table just duplicates INSERTs and does not guarantee consistency and repair.
We can call it "poor" replication as opposed to the full featured replication.

"Poor" replication can be used in the following scenarios:
- you cannot tolerate ZooKeeper in your infrastructure;
- you want to duplicate data in totally different clusters (e.g. production and staging);
- you want to duplicate data across tables of different structure;
- one time insertion of identical data into massive amount of servers.
