### ISSUE TITLE
Consuming Kafka too slowly

### ISSUE THREAD

**Issue by winter7** [ClickHouse/ClickHouse#22215]
**Describe the unexpected behaviour**
I had these 2 similar Kafka topics, say `topic_a` and `topic_b`. And I have 1 ClickHouse server. I created 2 Kafka engine tables named `table_a` and `table_b` to consume each topic.
the 2 topics both had similar throughput of `50k offsets/s` and `5M bytes/s`.
`table_a` and `table_b` were all configured with `kafka_max_block_size=1M`.

Firstly, both `table_a` and `table_b` didn't have enough speed to catch up their lags. 
So I created `table_a_2`, `table_a_3` and `table_a_4` with same consumer group as `table_a`, and `topic_a` seemed to be caught up.
However, when I tried to create `table_b_2`, `table_b_3` and `table_b_4` to speed up the consuming of `topic_b`, I started to get exceptions like `All commit attempts failed. Last block was already written to target table(s), but was not commited to Kafka`. And I observed that the `CPU IO Await` was high. And both topics' consumer group's throughput was affected and decreased.
The `CPU IO Await` remained high until I dropped `table_b` and all `table_b_*`.
And when I modified `kafka_max_block_size` from `1M` to `0.5M`, 4 `table_a` and 4 `table_b` seemed to consume harmoniously. But after a few hours, exceptions were thrown again and both topics' consumer group's lags increased again.
Now I have no idea about how to create appropriate number and the correct configuration of Kafka engine tables for each topic.

**How to reproduce**
* ClickHouse version = 20.4.4.18.
* You can refer to the throughput of messages I mentioned above.

**Expected behavior**
I expect a right way to create Kafka tables under this message throughput. I wonder how CPU IO Await is affected and if I should turn `kafka_max_block_size` up or down.

**Error message and/or stacktrace**
```
2021.03.27 10:50:00.762714 [ 119 ] {} <Error> StorageKafka (table_a_4): Exception during commit attempt: Broker: Unknown member
2021.03.27 10:50:00.763741 [ 119 ] {} <Error> StorageKafka (table_a_4): Exception during commit attempt: Broker: Unknown member
2021.03.27 10:50:00.764718 [ 119 ] {} <Error> StorageKafka (table_a_4): Exception during commit attempt: Broker: Unknown member
2021.03.27 10:50:00.765695 [ 119 ] {} <Error> StorageKafka (table_a_4): Exception during commit attempt: Broker: Unknown member
2021.03.27 10:50:00.766693 [ 119 ] {} <Error> StorageKafka (table_a_4): Exception during commit attempt: Broker: Unknown member
2021.03.27 10:50:00.916783 [ 119 ] {} <Error> void DB::StorageKafka::threadFunc(): Code: 518, e.displayText() = DB::Exception: All commit attempts failed. Last block was already written to target table(s), but was not commited to Kafka., Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x104191d0 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x8fff8ad in /usr/bin/clickhouse
2. ? @ 0xd80ad07 in /usr/bin/clickhouse
3. DB::KafkaBlockInputStream::commit() @ 0xd7fd3d9 in /usr/bin/clickhouse
4. DB::StorageKafka::streamToViews() @ 0xd7f0358 in /usr/bin/clickhouse
5. DB::StorageKafka::threadFunc() @ 0xd7f0da8 in /usr/bin/clickhouse
6. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0xcfe9619 in /usr/bin/clickhouse
7. DB::BackgroundSchedulePool::threadFunction() @ 0xcfe9c42 in /usr/bin/clickhouse
8. ? @ 0xcfe9d72 in /usr/bin/clickhouse
9. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x902526b in /usr/bin/clickhouse
10. ? @ 0x9023753 in /usr/bin/clickhouse
11. start_thread @ 0x76db in /lib/x86_64-linux-gnu/libpthread-2.27.so
12. __clone @ 0x12188f in /lib/x86_64-linux-gnu/libc-2.27.so
 (version 20.4.4.18 (official build))
```

**Additional context**
Please tell me if you need more detailed message. I'm really troubled by this issue.

**Comment by UnamedRus** [comment]
> I had these 2 similar Kafka topics

Did you tried to create one kafka table with both topics attached to it?

With `kafka_max_block_size` set to 1 mil.
Which throughput it would have? (Which throughput you have with 2 tables?)

If you have 50k/s, clickhouse would wait up to 7.5 sec in order to collect 1 mil messages. (`stream_flush_interval_ms` setting)

**Comment by winter7** [comment]
@UnamedRus Thanks for helping!

> Did you tried to create one kafka table with both topics attached to it?

I didn't. Could you please help to explain what the advantages of this are?

> With `kafka_max_block_size` set to 1 mil. Which throughput it would have?

In fact, say `topic_a`, the throughput of consumer group would be up to 50k offsets/s if I create 4 consumers. But if I have 4 consumers for `topic_a` and 4 consumers for `topic_b` they will affect others' throughput and get exceptions occasionally and cpu await goes high. I believe it has something with the number of consumers.

>If you have 50k/s, clickhouse would wait up to 7.5 sec in order to collect 1 mil messages. (`stream_flush_interval_ms` setting)

Do you mean that if I set a lower value for setting `kafka_max_block_size ` , my CPU IO await will be smoother?

**Comment by UnamedRus** [comment]
> I didn't. Could you please help to explain what the advantages of this are?

Kafka table share background pool with other tasks.(they now have separate pool for streaming engines but it's only in newest versions of clickhouse). It's better to have less consumers than more, if you not exceed limit of single kafka table ~ 300k/sec.

> Do you mean that if I set a lower value for setting kafka_max_block_size , my CPU IO await will be smoother?

Kafka table would commit messages faster. It's not clear from your issue, for how long did you watched for kafka table lag.

**Comment by filimonov** [comment]
Start from upgrade to 20.8 or newer. There was a lot of improvements in perf.

Since 20.9 you can use setting thread per consumer
