### ISSUE TITLE
Distributed table Sharding not working properly

### ISSUE THREAD

**Issue by samanway1996** [ClickHouse/ClickHouse#22227]
I am creating a distributed table over three underlying tables (or, shards created with engine ReplacingMergeTree). While inserting data into the distributed table, two of the shards getting filled appropriately, but one shard is having data records which should have been stored to the other ones.   

**More about the Issue:**
I am inserting duplicate data on different batch, so while querying I need my data to be deduplicated. And that's the reason I am using ReplacingMergeTree and OPTIMIZE statement. But to get the data deduplicated while querying, I need same records to be inserted to same shard (as OPTIMIZE does not work over distributed table). I am using an hashed Id (which is a String of 10 characters). But after investigating more I realised while inserting to the distributed table, the data is not going to proper shard where it should be. 

**How to reproduce**
Clickhouse version I am using: 21.2.5

**Table schema**
```
CREATE TABLE db_name.shard_name
(
  `some_id` String,
  `date_created` DateTime DEFAULT now() CODEC(T64, LZ4),
  `some_column` Datatype
)
ENGINE = ReplacingMergeTree()
PARTITION BY toYYYYMMDD(date_created)
ORDER BY some_id
SETTINGS index_granularity = 8192
```

```
CREATE TABLE db_name.distributed_table_name ON CLUSTER `cluster-name` AS db_name.shard_name
ENGINE = Distributed(cluster-name, db_name, shard_name, xxHash32(some_id))
```

```
#!/bin/bash
clickhouse-client -h CLICKHOUSE_HOSTNAME -u CLICKHOUSE_USERNAME --password CLICKHOUSE_PASSWORD -d db_name --multiquery --query \
    "SET max_memory_usage=60000000000;
    INSERT INTO db_name.distributed_table_name FORMAT JSONEachRow" --input_format_skip_unknown_fields=1  < filename.json
```

**Error message and/or stacktrace**
Surprisingly when insertion was done in multiple batches, I issued the following query to each shard.
```
SELECT some_id, xxHash32(some_id ) AS hashed_id, xxHash32(some_id )%3  AS modulo
FROM db_name.shard_name 
WHERE date_created >= '2021-03-29 00:00:00'
```
I am getting the following result.
<img width="297" alt="Screenshot 2021-03-29 at 2 39 58 AM" src="https://user-images.githubusercontent.com/10659497/112768180-5abf8000-9038-11eb-904c-f62c1b8b05bb.png">
<img width="299" alt="Screenshot 2021-03-29 at 2 36 52 AM" src="https://user-images.githubusercontent.com/10659497/112768185-601cca80-9038-11eb-8309-de0f535ffa22.png">
<img width="299" alt="Screenshot 2021-03-29 at 2 37 03 AM" src="https://user-images.githubusercontent.com/10659497/112768191-63b05180-9038-11eb-9c4d-191ed4af8a1e.png">

**Expected behavior**
Clearly the third shard should store the records having `xxHash32(some_id )%3 = 0`. The record with ID as _2903312331_ should be stored in first shard. 

**Other workarounds tried**
I have read that ReplacingMergeTree can suffer from race conditions if SELECT query is issued in between OPTIMIZE is processing, and data can be invalidated. But I made sure, I query from the table once OPTIMIZE is finished. Also have tried with other hash like `murmurHash3_64`.

**More context**
The shard tables were created long ago, and first data was being inserted to individual shards randomly. Later the distributed table was created in purpose to deduplicate the data (by directing same records to be inserted to same shard, so that OPTIMIZE can deduplicate the whole data).

**Comment by den-crane** [comment]
Please share 
```sql
select shard_num, shard_weight, replica_num, is_local 
from system.clusters;
where cluster = 'cluster-name'
```

**Comment by den-crane** [comment]
>The shard tables were created long ago, and first data was being inserted to individual shards randomly.

But CH does not do re-sharding.
It's you responsibility to re-shard data if you are adding more shards.

**Comment by samanway1996** [comment]
> > The shard tables were created long ago, and first data was being inserted to individual shards randomly.
> 
> But CH does not do re-sharding.
> It's your responsibility to re-shard data if you are adding more shards.

Yes, that is why, I am checking data inserted only after the Sharding key has been introduced. 
`WHERE date_created >= '2021-03-29 00:00:00'`

```
SELECT some_id, xxHash32(some_id ) AS hashed_id, xxHash32(some_id )%3  AS modulo
FROM db_name.shard_name 
WHERE date_created >= '2021-03-29 00:00:00'
```

**Comment by samanway1996** [comment]
> Please share
> 
> ```sql
> select shard_num, shard_weight, replica_num, is_local 
> from system.clusters;
> where cluster = 'cluster-name'
> ```

<img width="407" alt="Screenshot 2021-03-29 at 11 22 11 AM" src="https://user-images.githubusercontent.com/10659497/112792440-173d3400-9081-11eb-879c-6f043950aa7f.png">

**Comment by den-crane** [comment]
Check that all 3 servers have the same configuration

```
select shard_num, shard_weight, replica_num, is_local 
from system.clusters;
where cluster = 'cluster-name'
```

**Comment by azat** [comment]
No reply for 2 years, let's close?
