### ISSUE TITLE
HDFS Storage support hadoop.rpc.protection=PRIVACY

### ISSUE THREAD

**Issue by Qsimple** [ClickHouse/ClickHouse#22236]
Some context can be found in https://github.com/ClickHouse/ClickHouse/pull/16621#issuecomment-808635139      

Hope to discuss the future plan about the intergration with HDFS.  

tks

**Comment by michael1589** [comment]
I'm asking @bdrosen96's willing to merge his code to libhdfs3, not sure if he agrees.  The solution is just in his repo(https://github.com/bdrosen96/libhdfs3). Can the community accept the plan including 3 steps(the change looks not small): 1. update clickhouse's libgsasl as @bdrosen96's; 2.cherry pick @bdrosen96's PR into libhdfs3 of clickhouse. 3. modify clickhouse's cmake. 
@alexey-milovidov @filimonov it's a pleasure to hear your opinions.

**Comment by michael1589** [comment]
@bdrosen96 You're absolutely correct! It's not so easy. I tried to merge over 100 files to clickhouse/libhdfs3 but run failed. Seems that the merge was not successful. BTW,  would I still have to replace clickhouse/libgsasl with bdrosen96/libgsasl even if my merge is OK?  clickhouse/libgsasl  is v1.8.0, and bdrosen96/libgsasl  is v1.8.1.  I just want to use your PR about secure rpc call and secure Data Transfer, without KMS related.

**Comment by bdrosen96** [comment]
Yes, the SASL stuff is needed for secure RPC to support both privacy and integrity.

**Comment by michael1589** [comment]
Hi all, I've commit three PRs to fix this problem. Refer: https://github.com/ClickHouse/ClickHouse/pull/37852. Since the two third-party libraries are still blocked, the main PR wouldn't be merged util the third-party libraries merged in.

**Comment by yj7778826** [comment]
> Hi all, I've commit three PRs to fix this problem. Refer: #37852. Since the two third-party libraries are still blocked, the main PR wouldn't be merged util the third-party libraries merged in.

I am using version 22.7.7.24，it seems to work well with config 'hadoop.rpc.protection=authentication,privacy'. I suppose libhdfs3 in this version include this PR

**Comment by yusiwen123** [comment]
> > Hi all, I've commit three PRs to fix this problem. Refer: #37852. Since the two third-party libraries are still blocked, the main PR wouldn't be merged util the third-party libraries merged in.
> 
> I am using version 22.7.7.24，it seems to work well with config 'hadoop.rpc.protection=authentication,privacy'. I suppose libhdfs3 in this version include this PR

 I am using version 22.10.2.11，it still can't work with config 'hadoop.rpc.protection=authentication,privacy'. can you help me ?

**Comment by DenisGee** [comment]
> > > Hi all, I've commit three PRs to fix this problem. Refer: #37852. Since the two third-party libraries are still blocked, the main PR wouldn't be merged util the third-party libraries merged in.
> > 
> > 
> > I am using version 22.7.7.24，it seems to work well with config 'hadoop.rpc.protection=authentication,privacy'. I suppose libhdfs3 in this version include this PR
> 
> I am using version 22.10.2.11，it still can't work with config 'hadoop.rpc.protection=authentication,privacy'. can you help me ?

Same problem with 23.4.5.22

**Comment by yj7778826** [comment]
> > > > Hi all, I've commit three PRs to fix this problem. Refer: #37852. Since the two third-party libraries are still blocked, the main PR wouldn't be merged util the third-party libraries merged in.
> > > 
> > > 
> > > I am using version 22.7.7.24，it seems to work well with config 'hadoop.rpc.protection=authentication,privacy'. I suppose libhdfs3 in this version include this PR
> > 
> > 
> > I am using version 22.10.2.11，it still can't work with config 'hadoop.rpc.protection=authentication,privacy'. can you help me ?
> 
> Same problem with 23.4.5.22

only 22.7.7.24 support this feature, after that this PR has been roll-back

**Comment by alexey-milovidov** [comment]
We don't support HDFS.
