### ISSUE TITLE
when will clickhouse materialized view update the data? 

### ISSUE THREAD

**Issue by melin** [ClickHouse/ClickHouse#22250]
when will clickhouse materialized view update the data? How long source table update the materialized view table data

**Comment by KochetovNicolai** [comment]
Hi.
Data insertion into MV table happens at the same time you insert data into source table.
If insertion into source table returns `ok`, new data is inserted in both source and MV table. This insert is not transnational, however. It means, there could be a moment when `select` can get not consistent data while reading from source table and MV (e.g. it can see MV before insertion, but source table after).
