### ISSUE TITLE
 clickhouse-client --format_csv_delimiter='@@@' or --format_csv_delimiter=$'\@\@\@' got Exception

### ISSUE THREAD

**Issue by DreamUFO** [ClickHouse/ClickHouse#22267]
(you don't have to strictly follow this form)

import csv data into database ,like this
clickhouse-client --format_csv_delimiter='@@@' --query="insert into default.tb_name select col1,col2,col3 from file('csv_file_name.csv','CSVWithNames','col1 String,col2 String,col3 String')"

got 
Code: 19. DB::Exception: A setting's value string has to be an exactly one character long

how to translate Symbol @ ,I try \@ not working too.

**Comment by filimonov** [comment]
Just like exception says: CSV supports only single character separators (i.e. single `@` could be ok, but 3 of them - not). 

You can try to use `format Template`, `format  Regexp` or just preprocess your input with smth like `sed`

**Comment by DreamUFO** [comment]
ok,thanks.I got.
I'll deal with multi Symbol delimiter befor import.
