### ISSUE TITLE
Query failed when column name is number

### ISSUE THREAD

**Issue by liuneng1994** [ClickHouse/ClickHouse#22268]
**Describe the bug**
A table has number column names, query will fail when the where condition has number literal that same with column name.

**Does it reproduce on recent release?**
It reproduces on 21.1.2.15, and also reproduce on master branch

**How to reproduce**
DROP TABLE IF EXISTS ttt01778;
CREATE TABLE ttt01778 (\`1\` String, \`2\` INT) ENGINE = MergeTree() ORDER BY tuple();
INSERT INTO ttt01778 values('1',1),('2',2),('3',3);
select * from ttt01778 where 1=2;

query will fail

**Expected behavior**
query success with empty result

**Error message and/or stacktrace**
Code: 386, e.displayText() = DB::Exception: There is no supertype for types String, Int32 because some of them are String/FixedString and some of them are not: while executing 'FUNCTION equals(1 : 0, 2 : 1) -> equals(1, 2) UInt8 : 2

**Comment by liuneng1994** [comment]
I'm working on this issue

**Comment by liuneng1994** [comment]
pr https://github.com/ClickHouse/ClickHouse/pull/22270

**Comment by den-crane** [comment]
Not a bug . You should use ` or " for database objects with names started with digit.

```
SELECT *
FROM ttt01778
WHERE `1` = toString(`2`)

Query id: aa37a978-75e4-4931-a58b-40cbca197e6a

┌─1─┬─2─┐
│ 1 │ 1 │
│ 2 │ 2 │
│ 3 │ 3 │
└───┴───┘

```

**Comment by liuneng1994** [comment]
@den-crane I just want to send a query with condition number(1) equals numbers(2), I can get metadata from jdbc driver without any data scan. But clickhouse recognizes numbers as columns.  You test SQL `SELECT * from ttt01778 where 2=3`, it worked. The two SQL has Inconsistent behavior. So I think this is a bug

**Comment by den-crane** [comment]
OK. Strange that 

```
21.4.1.6364

select * from ttt01778 where 1=2;
Ok.

0 rows in set. Elapsed: 0.002 sec.
