### ISSUE TITLE
kafka engine can't consume messages

### ISSUE THREAD

**Issue by shiyhuan** [ClickHouse/ClickHouse#22272]
this is my kafka message:
{"app_name":"com.emoji.coolkeyboard","country":"US","api_level":23,"app_key":"4e5ab3a6d2140457e0423a28a094b1fd","duid":"17d2b544411e4fdfbb3c7a1686b6158f","system":"android","app_version":2914,"create_time":1617007678646,"extra":"1213","event_name":"123","language":"en","commit_time":1632396153000}
{"app_name":"com.emoji.coolkeyboard","country":"US","api_level":23,"app_key":"4e5ab3a6d2140457e0423a28a094b1fd","duid":"17d2b544411e4fdfbb3c7a1686b6158f","system":"android","app_version":2914,"create_time":1617007678646,"extra":"1213","event_name":"123","language":"en","commit_time":1632396153000}

and this is my dml

create table t_event_kafka
(
    duid String,
    event_name String,
    commit_time Int32,
    extra String,
    app_name String,
    app_version String,
    app_key String,
    country String,
    language String,
    system String,
    api_lever Int32,
    create_time Int32
) engine=Kafka SETTINGS kafka_broker_list = 'host.docker.internal:9092',
                            kafka_topic_list = 'flow_event',
                            kafka_group_name = 'test-consumer-group',
                            kafka_format = 'JSONEachRow',
                            kafka_num_consumers = 1;

create table t_event
(
    duid String,
    event_name String,
    commit_time Int32,
    extra String,
    app_name String,
    app_version String,
    app_key String,
    country String,
    language String,
    system String,
    api_lever Int32,
    create_time Int32
) engine=MergeTree()
order by (commit_time,duid);

create materialized view mv_event to t_event
as select duid,event_name,commit_time,extra,app_name,app_version,app_key,country,language,system,api_lever,create_time
from t_event_kafka order by (commit_time,duid) ;

**Comment by den-crane** [comment]
JSON: api_level
Table: api_lever

--input_format_skip_unknown_fields arg    Skip columns with unknown names from input data (it works for JSONEachRow, CSVWithNames, TSVWithNames and TSKV formats).

**Comment by shiyhuan** [comment]
> JSON：api_level
> 表：api_lever
> 
> --input_format_skip_unknown_fields arg跳过输入数据中具有未知名称的列（适用于JSONEachRow，CSVWithNames，TSVWithNames和TSKV格式）。
> 
> JSONEachRow期望类型相同。
> app_version**字符串**JSONEachRow预期`"app_version":"2914"`不会`"app_version":2914`

thanks

**Comment by shiyhuan** [comment]
> JSON: api_level
> Table: api_lever
> 
> --input_format_skip_unknown_fields arg Skip columns with unknown names from input data (it works for JSONEachRow, CSVWithNames, TSVWithNames and TSKV formats).
> 
> JSONEachRow expects that types are the same.
> app_version **String** JSONEachRow expects `"app_version":"2914"` not `"app_version":2914`

after I modified,it can't still run.
this is my kafka message:
{"app_name":"com.emoji.coolkeyboard","country":"US","api_level":23,"app_key":"4e5ab3a6d2140457e0423a28a094b1fd","duid":"17d2b544411e4fdfbb3c7a1686b6158f","system":"android","app_version":2914,"create_time":1617108725973,"extra":"{\"feeling\":\"Not good\"}","event_name":"feeling_choose","language":"en","commit_time":1617089132000}


and my dml:

create table t_event_kafka
(
    duid String,
    event_name String,
    commit_time datetime,
    extra String,
    app_name String,
    app_version Int32,
    app_key String,
    country String,
    language String,
    system String,
    api_level Int32,
    create_time datetime
) engine=Kafka SETTINGS kafka_broker_list = 'host.docker.internal:9092',
                            kafka_topic_list = 'flow_event',
                            kafka_group_name = 'test-consumer-group',
                            kafka_format = 'JSONEachRow',
                            kafka_num_consumers = 1;

create table t_event1
(
    duid String,
    event_name String,
    commit_time datetime,
    extra String,
    app_name String,
    app_version Int32,
    app_key String,
    country String,
    language String,
    system String,
    api_level Int32,
    create_time datetime
) engine=MergeTree()
partition by toYYYYMM(commit_time)
order by (commit_time,duid)

create materialized view mv_event to t_event1
as select duid,event_name,commit_time,extra,app_name,app_version,app_key,country,language,system,api_level,create_time
from t_event_kafka order by (commit_time,duid)

**Comment by alexey-milovidov** [comment]
@shiyhuan What exception do you get?
