### ISSUE TITLE
Not all parts be applied TTL after execute `ALTER ON CLUSTER MODIFY TTL`

### ISSUE THREAD

**Issue by xiaogaozi** [ClickHouse/ClickHouse#22273]
**Describe the unexpected behaviour**
After I executed `ALTER ON CLUSTER MODIFY TTL` query, I found not all parts by applied TTL. For example:

```sql
:) SELECT name, active, rows, move_ttl_info.expression, move_ttl_info.min, move_ttl_info.max, data_version FROM system.parts WHERE table = 'xxx';

┌─name───────────────────────┬─active─┬────rows─┬─move_ttl_info.expression─────────────────┬─move_ttl_info.min───────┬─move_ttl_info.max───────┬─data_version─┐
│ 20201031_0_648_20          │      1 │ 2716886 │ []                                       │ []                      │ []                      │            0 │
│ 20201031_649_682_3         │      1 │  109043 │ []                                       │ []                      │ []                      │          649 │
│ 20201101_0_1098_25         │      1 │ 3201636 │ []                                       │ []                      │ []                      │            0 │
│ 20201102_0_60_3_6          │      1 │  271675 │ ['plus(event_date, toIntervalMonth(6))'] │ ['2021-05-02 00:00:00'] │ ['2021-05-02 00:00:00'] │            6 │
│ 20201102_61_153_5          │      1 │  197994 │ []                                       │ []                      │ []                      │           61 │
│ 20201102_154_165_3         │      1 │   21855 │ []                                       │ []                      │ []                      │          154 │
│ 20201103_0_43_3_44         │      1 │  202097 │ ['plus(event_date, toIntervalMonth(6))'] │ ['2021-05-03 00:00:00'] │ ['2021-05-03 00:00:00'] │           44 │
│ 20201104_0_139_4_353       │      1 │  660266 │ ['plus(event_date, toIntervalMonth(6))'] │ ['2021-05-04 00:00:00'] │ ['2021-05-04 00:00:00'] │          353 │
│ 20201104_140_352_6_353     │      1 │  648538 │ ['plus(event_date, toIntervalMonth(6))'] │ ['2021-05-04 00:00:00'] │ ['2021-05-04 00:00:00'] │          353 │
└────────────────────────────┴────────┴─────────┴──────────────────────────────────────────┴─────────────────────────┴─────────────────────────┴──────────────┘
```

As you can see, only those parts which don't have `data_version` (or `MergeTreePartInfo.mutation`) have this problem.

**How to reproduce**
* Which ClickHouse server version to use: 20.9.2.20
* Which interface to use, if matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result: `ALTER ON CLUSTER MODIFY TTL`

**Expected behavior**
All parts be applied TTL

**Error message and/or stacktrace**
N/A

**Additional context**
This is a distributed DDL query, and table engine is `ReplicatedMergeTree`.

**Comment by den-crane** [comment]
20.9.2.20 is out of support. Does it reproduce with 21.* ?

**Comment by xiaogaozi** [comment]
@vzakaznikov May I ask, do you have any clue about this issue?

**Comment by filimonov** [comment]
Mutation was still running / in progress when you was checking? (check system.muatations)

**Comment by xiaogaozi** [comment]
> Mutation was still running / in progress when you was checking? (check system.mutations)

@filimonov No, all mutations have already done. Actually, I've waited several days after execute `MODIFY TTL` query.

```sql
SELECT count(*)
FROM system.mutations
WHERE (table = 'xxx') AND (command = 'MATERIALIZE TTL') AND (is_done = 0)

┌─count()─┐
│       0 │
└─────────┘
```

**Comment by vzakaznikov** [comment]
> @vzakaznikov May I ask, do you have any clue about this issue?

That version is "quite old". Do you have ability to try the same action on a newer release as mentioned above?

**Comment by xiaogaozi** [comment]
> > @vzakaznikov May I ask, do you have any clue about this issue?
> 
> That version is "quite old". Do you have ability to try the same action on a newer release as mentioned above?

@vzakaznikov Thanks for your reply, we may be try to verify this behavior with newer CH in the future. BTW, as a workaround, we have use `ALTER TABLE MOVE PART` command to migrate these "problematic" data parts.
