### ISSUE TITLE
How to troubleshoot kerberos

### ISSUE THREAD

**Issue by baibaichen** [ClickHouse/ClickHouse#22276]
Hi all

I am using 21.3.3.14 on suse 11.4 to access secure HDFS, but failed to read data on HDFS.  I get the following error:
```
Failed to evaluate challenge:  GSSAPI error in client while negotiating security context in
gss_init_sec_context() in SASL library. This is most likely due insufficient credentials or
malicious interactions.
```

here are my configuration

```properties
[libdefaults]
 default_realm = $REALM
 dns_lookup_realm = false
 dns_lookup_kdc = false
 ticket_lifetime = 24h
 renew_lifetime = 7d
 forwardable = true
 renewable = true
 rdns = false
 default_tkt_enctypes = acfour-hamc-md5 des-cbc-crc des-cbc-md5 des3-hmac-sha1 acfour-hamc des-hmac-sha1
 default_tgs_enctypes = acfour-hamc-md5 des-cbc-crc des-cbc-md5 des3-hmac-sha1 acfour-hamc des-hmac-sha1
```
**Any help would be appreciated**!

By reading codes,  it would be failed at calling `gss_init_sec_context()`, even i set KRB5_TRACE as described at [here](https://web.mit.edu/kerberos/krb5-1.12/doc/admin/troubleshoot.html), but i did't see any log.

**Comment by filimonov** [comment]
@baibaichen check is DNS is resolved properly both ways (reverse dns too), and ensure clocks are in sync.

@ilejn do you have some ideas on how to debug it?

**Comment by ilejn** [comment]
@baibaichen 
The issue can be caused by many reasons. 
Most likely it should be investigated with the help of kdc logs, client is usually not informed of what exactly went wrong.

Use 'klist' to examine tickets as a sanity check.

**Comment by baibaichen** [comment]
> @baibaichen check is DNS is resolved properly both ways (reverse dns too), and ensure clocks are in sync.
> 
I disabled dns lookup as well as rdns

what make me confused is `hdfs` itself work correctly, which means sanity check is passed
