### ISSUE TITLE
Metabase with ClickHouse Driver

### ISSUE THREAD

**Issue by jonatasfreitasv** [ClickHouse/ClickHouse#2229]
Hi guys!!

Please all mark in this issue for speed this feature https://github.com/metabase/metabase/issues/3332.

**Comment by alexey-milovidov** [comment]
https://clickhouse.com/learn/lessons/connect-metabase-to-clickhouse/

**Comment by alexey-milovidov** [comment]
Here is the tutorial to connect ClickHouse to Metabase: https://clickhouse.com/docs/en/connect-a-ui/metabase-and-clickhouse/
