### ISSUE TITLE
"ZooKeeper session has been expired" exception when inserting data to the Replicated table

### ISSUE THREAD

**Issue by maskshell** [ClickHouse/ClickHouse#22304]
**Describe the bug**

System throws "ZooKeeper session has been expired" exception when inserting data to the replicated table.

I took a little look at the source code. There are some guesses:

When the background resources are free, CH will regularly check if the connection with ZK has expired.
This detection should be done in a loop by table, and if it expires a new connection session will be started.

However, we have more than 1500 replicated tables.
I calculated that it takes nearly 3 seconds just to finish detecting these tables.
If there is an INSERT in the meantime, I guess there is something wrong with the logic at this time.

The following functions will all execute `assertSessionIsNotExpired()`:
```
ReplicatedMergeTreeBlockOutputStream::commitPart()
ReplicatedMergeTreeBlockOutputStream::write()
ReplicatedMergeTreeBlockOutputStream::writeExistingPart()
```

When ZK session expired, it is just simply throw the exception ...
 
```
/// Allow to verify that the session in ZooKeeper is still alive.
static void assertSessionIsNotExpired(zkutil::ZooKeeperPtr & zookeeper)
{
    if (!zookeeper)
        throw Exception("No ZooKeeper session.", ErrorCodes::NO_ZOOKEEPER);

    if (zookeeper->expired())
        throw Exception("ZooKeeper session has been expired.", ErrorCodes::NO_ZOOKEEPER);
}
```

Temporary solution:

Increase the value of `<session_timeout_ms>` in the `<zookeeper-servers>` section to a large enough size,
and make sure it is not larger than the `maxSessionTimeout` value of the ZooKeeper server.

btw: the `<session_timeout_ms>` value defaults to 30000, and this is not clearly expressed in the documentation.

**Comment by maskshell** [comment]
After testing, the maximum allowed value for `session_timeout_ms` is 10737418.

10737418000 Bytes = 10.000 Gigabytes

Does this mean anything exactly? Or is it just a limitation in the algorithm?

**Comment by maskshell** [comment]
After testing, the maximum allowed value for `session_timeout_ms` is looks like 10737418.

10737418000 Bytes = 10.000 Gigabytes

Does this mean anything exactly? Or is it just a limitation in the algorithm?

and, strange things
* `<session_timeout_ms>3600000</session_timeout_ms>`
* `<session_timeout_ms>7200000</session_timeout_ms>`
cannot work,

and these worked:
* `<session_timeout_ms>5368709</session_timeout_ms>`
* `<session_timeout_ms>10737418</session_timeout_ms>`

**Comment by filimonov** [comment]
It's not neccessary that the reason of
`ZooKeeper session has been expired`
is expiration by timeout.

It may become 'expired' after some failures too, check if you see some other zookeeper related exceptions (also in ZooKeeper logs) around the time you see the 'expired' exception. 

Maybe we should change the exception text to
"ZooKeeper session is lost (due to expiration or failure)"

**Comment by maskshell** [comment]
@filimonov, but this 'expired' behavior are not concurrent happend in all replicas.

```
下午2点38:43.363分	WARN	NIOServerCnxn	
caught end of stream exception
EndOfStreamException: Unable to read additional data from client sessionid 0xd785ff49ff41d99, likely client has closed socket
	at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:240)
	at org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:203)
	at java.lang.Thread.run(Thread.java:748)

下午2点38:43.365分	INFO	NIOServerCnxn	
Closed socket connection for client /10.9.15.70:38120 which had sessionid 0xd785ff49ff41d99

下午2点38:43.367分	INFO	NIOServerCnxnFactory	
Accepted socket connection from /10.9.15.70:56418

下午2点38:43.368分	WARN	ZooKeeperServer	
Connection request from old client /10.9.15.70:56418; will be dropped if server is in r-o mode

下午2点38:43.368分	INFO	ZooKeeperServer	
Client attempting to establish new session at /10.9.15.70:56418

下午2点38:43.368分	INFO	ZooKeeperServer	
Established session 0xd785ff49ff41ebd with negotiated timeout 30000 for client /10.9.15.70:56418
```

**Comment by maskshell** [comment]
> It's not neccessary that the reason of
> `ZooKeeper session has been expired`
> is expiration by timeout.
> 
> It may become 'expired' after some failures too, check if you see some other zookeeper related exceptions (also in ZooKeeper logs) around the time you see the 'expired' exception.
> 
> Maybe we should change the exception text to
> "ZooKeeper session is lost (due to expiration or failure)"

Indeed, I observed that this is indeed a separate case, not a disconnection caused by the timeout mechanism.

**Comment by alexey-milovidov** [comment]
The logic is correct. Single ZooKeeper session must live for whole duration of INSERT query.
INSERT query cannot be done if ZooKeeper session is expired.

An expiration of ZooKeeper session (e.g. connection loss between ClickHouse and ZooKeeper) is normal if happens from time to time and it is inevitable.

But if it happens too frequently it indicates a misconfiguration - e.g. overloaded ZooKeeper server or bad network connection.
