### ISSUE TITLE
intDiv is 25% slower than divide 

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#22314]
```
SELECT intDiv(rand64(), 1000000000) FROM numbers(10000000000) FORMAT Null

0 rows in set. Elapsed: 20.442 sec. Processed 10.00 billion rows, 80.00 GB (489.19 million rows/s., 3.91 GB/s.) 

SELECT divide(rand64(), 1000000000) FROM numbers(10000000000) FORMAT Null

0 rows in set. Elapsed: 14.496 sec. Processed 10.00 billion rows, 80.00 GB (689.86 million rows/s., 5.52 GB/s.) 
```

**Comment by alexey-milovidov** [comment]
What version do you use?
Does it reproduce on 21.4-testing?

**Comment by alexey-milovidov** [comment]
This https://github.com/ClickHouse/ClickHouse/pull/21307 ?

**Comment by filimonov** [comment]
It reproduces on yesterdays testing build
```

SELECT *
FROM system.build_options

Query id: 8e5742bc-b38e-4f36-9e8f-53b72045b9c7

┌─name──────────────────────┬─value──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ VERSION_FULL              │ ClickHouse 21.4.1.6378                                                                                                                                                                                                                                     │
│ VERSION_DESCRIBE          │ v21.4.1.6378-testing                                                                                                                                                                                                                                       │
│ VERSION_INTEGER           │ 21004001                                                                                                                                                                                                                                                   │
│ VERSION_GITHASH           │ 6fb444f732b6c6315e5d511690949175ca21d6c8                                                                                                                                                                                                                   │
│ VERSION_REVISION          │ 54449                                                                                                                                                                                                                                                      │
│ BUILD_DATE                │ 2021-03-29                                             
```

**Comment by filimonov** [comment]
Actually, the performance of intDiv now is as good as before 

20.8 Elapsed: 22.984 sec. 
21.1.7.1 Elapsed: 77.718 sec.
21.4 Elapsed: 20.768 sec.

But the performance of divide was significantly improved in 20.10:

20.8 Elapsed: 51.875 sec.
20.9 Elapsed: 60.792 sec
20.10 Elapsed: 15.765 sec. 

It's counter-intuitive to have intDiv slower than div :)

**Comment by alexey-milovidov** [comment]
The performance of floating point division has been improved due to migration to clang-11:
https://github.com/ClickHouse/ClickHouse/blob/master/docs/en/whats-new/changelog/2020.md#buildtestingpackaging-improvement-4

**Comment by alexey-milovidov** [comment]
To compare intDiv with floating point division, we also need to add truncation after floating point division.

Example:
```
SELECT toUInt32(divide(rand64(), 1000000000)) FROM numbers(10000000000) FORMAT Null
```

**Comment by alexey-milovidov** [comment]
`SELECT intDiv(rand64(), 1000000000) FROM numbers(10000000000) FORMAT Null`
- 681 million rows/sec.

`SELECT divide(rand64(), 1000000000) FROM numbers(10000000000) FORMAT Null`
- 750 million rows/sec.

`SELECT toUInt32(divide(rand64(), 1000000000)) FROM numbers(10000000000) FORMAT Null`
- 506 million rows/sec.

**Comment by alexey-milovidov** [comment]
@filimonov Your testing method is quite wrong...

`SELECT count() FROM system.numbers WHERE NOT ignore(intDiv(number, 1000000000))`
- 960.49 million rows/s.

`SELECT count() FROM system.numbers WHERE NOT ignore(divide(number, 1000000000))`
- 1.20 billion rows/s.

`SELECT count() FROM system.numbers WHERE NOT ignore(toUInt32(divide(number, 1000000000)))`
- 682.00 million rows/s.
