### ISSUE TITLE
incorrect frame in window func

### ISSUE THREAD

**Issue by ceedok** [ClickHouse/ClickHouse#22321]
hello

i use uniqExact(uid) for count cumulative uniqs, and use window frame as UNBOUNDED PRECEDING AND CURRENT ROW

if i use in window parameter PARTITION BY field with correct values, then everything works good

but if i remove PARTITION BY, and want the table to be a single partition with window frame UNBOUNDED PRECEDING AND CURRENT ROW

then the behavior of the window frame changes as if i set it from the beginning to the end of the section (UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)

**Comment by akuzm** [comment]
Please add some example of a query and data where we can see the problem.

I can imagine that you have `over (range between unbounded preceding and current row)`, which is equivalent to `over (range between unbounded preceding and unbounded following)`, because there are no `ORDER BY` columns and all rows are peers.

**Comment by ceedok** [comment]
This is h

ow i count cumulative LTV with help of window function. And do PARTITION BY source_id (source of traffic) - it works fine.

SELECT
cohort,
month,
CAST(sum(revenue) AS Float64) AS total_revenue,
uniqExact(uid) AS total_users,
total_revenue / total_users AS ltv,
CAST(MAX(cum_revenue) AS Float64) AS cum_revenue,
MAX(cum_users) AS cum_users,
CAST((cum_revenue / cum_users) AS Float64) AS cum_ltv
FROM
(
SELECT
uid,
device,
distance_month,
revenue,
source_id,
sum(revenue) OVER w AS cum_revenue,
uniqExact(uid) OVER w AS cum_users
FROM test.yandex_data_final
WINDOW w AS
(
PARTITION BY source_id
ORDER BY distance_month ASC
ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
)
)
GROUP BY
source_id AS cohort,
distance_month AS month
ORDER BY
cohort ASC,
month ASC

Here I'm trying to count cumulative LTV of all the service in total, and remove PARTITION BY source_id. In the result table I see that field cum_users was counted wrong. It ignored the frame of the window, which means it counted everything from beginning to the end of the section. And I wanted it to count everything from the beginning of the section till current line.

SELECT
--    cohort,
month,
CAST(sum(revenue) AS Float64) AS total_revenue,
uniqExact(uid) AS total_users,
total_revenue / total_users AS ltv,
CAST(MAX(cum_revenue) AS Float64) AS cum_revenue,
MAX(cum_users) AS cum_users,
CAST((cum_revenue / cum_users) AS Float64) AS cum_ltv
FROM
(
SELECT
uid,
device,
distance_month,
revenue,
source_id,
sum(revenue) OVER w AS cum_revenue,
uniqExact(uid) OVER w AS cum_users
FROM test.yandex_data_final
WINDOW w AS
(
--    PARTITION BY source_id
ORDER BY distance_month ASC
ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
)
)
GROUP BY
--    source_id AS cohort,
distance_month AS month
ORDER BY
--    cohort ASC,
month ASC

This is what 'SHOW CREATE TABLE' shows on my data:
CREATE TABLE test.yandex_data_final ( uid UInt64, device String, source_id UInt64, start_dt Date, start_ts DateTime, end_ts DateTime, revenue Decimal(38, 2), birthday Date, distance_month Int64 ) ENGINE = MergeTree ORDER BY (start_ts, uid) SETTINGS index_granularity = 8192

Here is my data, except for i casted revenue field to Float64 because of the features of export through Pandas. 
https://drive.google.com/file/d/1oxSdluoZasRRFbWIO3wsYHxWkm6yAPgJ/view?usp=sharing

**Comment by akuzm** [comment]
You have the maximum number of users in month 0, so it might be correct that the cumulative number of users doesn't change:
```
$clickhouse-local --structure "uid UInt64, device String, source_id UInt64, start_dt DateTime, start_ts DateTime, end_ts DateTime, revenue Decimal(38, 2), birthday DateTime, distance_month Int64" --file ~/Downloads/yandex_data_final.csv --input-format "CSVWithNames" --input_format_skip_unknown_fields=1 --query "select distance_month, uniqExact(uid) users from table group by distance_month format PrettyCompact"
┌─distance_month─┬──users─┐
│              0 │ 380121 │
│              4 │  12959 │
│              3 │  15481 │
│              2 │  19305 │
│              5 │  10631 │
│              1 │  30391 │
│              6 │   8394 │
│              7 │   6325 │
│              9 │   3191 │
│              8 │   4519 │
│             11 │   1370 │
│             10 │   2196 │
└────────────────┴────────┘
```

If you try the same query in Postgres, is the result different? I tried to run it in SQLite but it doesn't support `count(distinct uid)` as a window function.

**Comment by akuzm** [comment]
A more precise proof that all users are seen in the month 0:
```
SELECT
    distance_month,
    length(users_cumulative) AS cumulative_users,
    length(arrayIntersect(users_cumulative, users_prev)) AS already_seen_users
FROM 
(
    SELECT
        distance_month,
        users_cumulative,
        lagInFrame(users_cumulative) OVER (ORDER BY distance_month ASC) AS users_prev
    FROM 
    (
        SELECT
            distance_month,
            groupUniqArrayArray(groupUniqArray(uid)) OVER (ORDER BY distance_month ASC) AS users_cumulative
        FROM table
        GROUP BY distance_month
    )
)

┌─distance_month─┬─cumulative_users─┬─already_seen_users─┐
│              0 │           380121 │                  0 │
│              1 │           380121 │             380121 │
│              2 │           380121 │             380121 │
│              3 │           380121 │             380121 │
│              4 │           380121 │             380121 │
│              5 │           380121 │             380121 │
│              6 │           380121 │             380121 │
│              7 │           380121 │             380121 │
│              8 │           380121 │             380121 │
│              9 │           380121 │             380121 │
│             10 │           380121 │             380121 │
│             11 │           380121 │             380121 │
└────────────────┴──────────────────┴────────────────────┘
```

**Comment by akuzm** [comment]
Or even simper:
```
SELECT
    first_month,
    count(*) AS users
FROM 
(
    SELECT min(distance_month) AS first_month
    FROM table
    GROUP BY uid
)
GROUP BY first_month
ORDER BY users DESC


┌─first_month─┬──users─┐
│           0 │ 380121 │
└─────────────┴────────┘
```

**Comment by ceedok** [comment]
This would be correct if there was no GROUP BY section at all, but there is one, and in it I group by month_distance, and I want to find the maximum for each month_distance

**Comment by akuzm** [comment]
The cumulative number of users doesn't change with growing months, because all users are encountered in the first month. The result is correct given the data.
