### ISSUE TITLE
Can ClickHouse MaterializeMySQL ENGINE hide the MySQL password ?

### ISSUE THREAD

**Issue by yuuch** [ClickHouse/ClickHouse#22339]
(you don't have to strictly follow this form)

**Use case**
I use the `default` user to create a MaterializeMySQL databse. 

```SQL
CREATE DATABASE mysql ENGINE = MaterializeMySQL('localhost:3306', 'db', 'mysql_user', 'mysql_pwd');
```
And I grant this database to `user1`.
When I log in ClickHouse as `user1`, I run the SQL:

```sql
SHOW CREATE DATABASE mysql
```
It returns:

```
┌─statement───────────────────────────────────────────────────────────────────────────────────┐
│ CREATE DATABASE chdb
ENGINE = MaterializeMySQL('127.0.0.1:3306', 'chdb', 'mysql_user', 'mysql_pwd') │
└─────────────────────────────────────────────────────────────────────────────────────────────┘
```
Now, user1 get the mysql password.
 I don't want `user1` know my MySQL password.

**Describe the solution you'd like**

 I don't want `user1` know my MySQL password.
Can CH hide the password ?
```
┌─statement───────────────────────────────────────────────────────────────────────────────────┐
│ CREATE DATABASE chdb
ENGINE = MaterializeMySQL('127.0.0.1:3306', 'chdb', 'mysql_user', '****') │
└─────────────────────────────────────────────────────────────────────────────────────────────┘
```
@zhang2014  @BohuTANG

**Comment by BohuTANG** [comment]
This should be a generic requirement, [MySQl engine](https://clickhouse.tech/docs/en/engines/table-engines/integrations/mysql/) also has this problem, it would be better to call a function, such as Mask.
