### ISSUE TITLE
one question about system.enent.InsertedRows

### ISSUE THREAD

**Issue by Yanbuc** [ClickHouse/ClickHouse#22342]
I create a table  and then i select the value of system.enent.InsertedRows . Then i insert into a row into the table  and i select the 
value of system.enent.InsertedRows . Make me conflused , the value of system.enent.InsertedRows  not only increase one,but increase much.
Before:
![image](https://user-images.githubusercontent.com/28927682/112951100-960f9b00-916d-11eb-814c-9857f30ce17a.png)
After
![image](https://user-images.githubusercontent.com/28927682/112951208-afb0e280-916d-11eb-86a7-ebfe8df69e77.png)
Why the value increases so much?

**Comment by KochetovNicolai** [comment]
Hi.
If you have some activity on server, it is very likely that ClickHouse writes some new rose into system tables (e.g. `system.query_log` for selects, `system.part_log` for merges and fetches, `system.trace_log` periodically, if enabled).

For my test server, the values has increased just between two selects (nobody insert into my server):
```
:) select event, value from system.events where event like 'Insert%'

SELECT
    event,
    value
FROM system.events
WHERE event LIKE 'Insert%'

Query id: 88aba8cf-6eff-48b8-85fa-f4128ac0e05b

┌─event───────────────────────┬───value─┐
│ InsertQuery                 │       4 │
│ InsertQueryTimeMicroseconds │    7666 │
│ InsertedRows                │   30646 │
│ InsertedBytes               │ 1342932 │
└─────────────────────────────┴─────────┘

4 rows in set. Elapsed: 0.003 sec. 

:) select event, value from system.events where event like 'Insert%'

SELECT
    event,
    value
FROM system.events
WHERE event LIKE 'Insert%'

Query id: dab23ebc-870d-45d0-b2c9-ded3b7a9eaca

┌─event───────────────────────┬───value─┐
│ InsertQuery                 │       4 │
│ InsertQueryTimeMicroseconds │    7666 │
│ InsertedRows                │   30670 │
│ InsertedBytes               │ 1367816 │
└─────────────────────────────┴─────────┘

4 rows in set. Elapsed: 0.002 sec. 
```

**Comment by Yanbuc** [comment]
I see . thanks

**Comment by Yanbuc** [comment]
> Hi.
> If you have some activity on server, it is very likely that ClickHouse writes some new rose into system tables (e.g. `system.query_log` for selects, `system.part_log` for merges and fetches, `system.trace_log` periodically, if enabled).
> 
> For my test server, the values has increased just between two selects (nobody insert into my server):
> 
> ```
> :) select event, value from system.events where event like 'Insert%'
> 
> SELECT
>     event,
>     value
> FROM system.events
> WHERE event LIKE 'Insert%'
> 
> Query id: 88aba8cf-6eff-48b8-85fa-f4128ac0e05b
> 
> ┌─event───────────────────────┬───value─┐
> │ InsertQuery                 │       4 │
> │ InsertQueryTimeMicroseconds │    7666 │
> │ InsertedRows                │   30646 │
> │ InsertedBytes               │ 1342932 │
> └─────────────────────────────┴─────────┘
> 
> 4 rows in set. Elapsed: 0.003 sec. 
> 
> :) select event, value from system.events where event like 'Insert%'
> 
> SELECT
>     event,
>     value
> FROM system.events
> WHERE event LIKE 'Insert%'
> 
> Query id: dab23ebc-870d-45d0-b2c9-ded3b7a9eaca
> 
> ┌─event───────────────────────┬───value─┐
> │ InsertQuery                 │       4 │
> │ InsertQueryTimeMicroseconds │    7666 │
> │ InsertedRows                │   30670 │
> │ InsertedBytes               │ 1367816 │
> └─────────────────────────────┴─────────┘
> 
> 4 rows in set. Elapsed: 0.002 sec. 
> ```
thanks. I see.

**Comment by Yanbuc** [comment]
thanks. I see .
