### ISSUE TITLE
Window Function row_number failed to return globally unique row numbers

### ISSUE THREAD

**Issue by kokomal** [ClickHouse/ClickHouse#22351]
Version 21.3.2.5
We have 3 shards of ***MergeTree, each has data for different days. There is a ###_all distributed table standing out for those 3 shards. 
When we execute :

```
SELECT
  row_number() OVER (PARTITION BY customer_no ORDER BY day) AS id_rank
FROM ###_all
```

The id_rank showed multiple '1's for the same customer_no, in another word, it seems that CK failed to globally de-duplicate and re-sort the row_numbers from different shards and thus did not return the unique arrays in distributed cases.

**Comment by kokomal** [comment]
DDL&DMLs are below:
```
-- DDL
-- local table
-- dadb is our database name
-- clus is our cluster name
CREATE TABLE dadb.`demo_loan` ON CLUSTER clus(
`id` Int64 COMMENT 'id',
`date_stat` Date COMMENT 'date of stat',
`customer_no` String COMMENT 'customer no',
`loan_principal` Float64 COMMENT 'loan principal'
) ENGINE=ReplicatedReplacingMergeTree() ORDER BY id PARTITION BY toYYYYMM(date_stat);

-- distributed table
CREATE TABLE dadb.`demo_loan_all` ON CLUSTER clus(
`id` Int64 COMMENT 'id',
`date_stat` Date COMMENT 'date of stat',
`customer_no` String COMMENT 'customer no',
`loan_principal` Float64 COMMENT 'loan principal'
) ENGINE=Distributed(clus, dadb, demo_loan, cityHash64(id));

-- DML
INSERT INTO dadb.`demo_loan_all` (id, date_stat, customer_no, loan_principal) VALUES (10001, toDate('2023-10-28'), 'USER_A', 10000);
INSERT INTO dadb.`demo_loan_all` (id, date_stat, customer_no, loan_principal) VALUES (10002, toDate('2023-10-28'), 'USER_A', 20000);
INSERT INTO dadb.`demo_loan_all` (id, date_stat, customer_no, loan_principal) VALUES (10003, toDate('2023-10-28'), 'USER_A', 30000);
INSERT INTO dadb.`demo_loan_all` (id, date_stat, customer_no, loan_principal) VALUES (10004, toDate('2023-10-28'), 'USER_A', 40000);
INSERT INTO dadb.`demo_loan_all` (id, date_stat, customer_no, loan_principal) VALUES (10005, toDate('2023-10-28'), 'USER_A', 50000);
INSERT INTO dadb.`demo_loan_all` (id, date_stat, customer_no, loan_principal) VALUES (10006, toDate('2023-10-28'), 'USER_A', 60000);
INSERT INTO dadb.`demo_loan_all` (id, date_stat, customer_no, loan_principal) VALUES (10007, toDate('2023-10-28'), 'USER_A', 70000);
INSERT INTO dadb.`demo_loan_all` (id, date_stat, customer_no, loan_principal) VALUES (10008, toDate('2023-10-28'), 'USER_A', 80000);
```

Wrongful answers will be shown if the following sql is executed:
```
-- NO CORRECT, RETURN SPORATIC id_rank
SELECT date_stat,
	customer_no,
	loan_principal,
	row_number() OVER (PARTITION BY ax.customer_no ORDER BY ax.date_stat ) AS id_rank   
FROM  dadb.demo_loan_all ax  
WHERE ax.date_stat >= toDate('2021-02-20')
SETTINGS allow_experimental_window_functions = 1;
```
You may get
------------------------------------------------------------
"date_stat","customer_no","loan_principal","id_rank"
2023-10-28,USER_A,70000.0,1
2023-10-28,USER_A,60000.0,2
2023-10-28,USER_A,40000.0,1
2023-10-28,USER_A,80000.0,2
2023-10-28,USER_A,50000.0,3
2023-10-28,USER_A,30000.0,4
2023-10-28,USER_A,20000.0,1
2023-10-28,USER_A,10000.0,2
---------------------------------------------------------------

Correct answers shall be shown if forcibly push the data into one shards's memory:
```
SELECT ax.*,
	row_number() OVER (PARTITION BY ax.customer_no ORDER BY ax.date_stat ) AS id_rank 
FROM (
	SELECT date_stat,
		customer_no,
		loan_principal
	FROM dadb.demo_loan_all ax  
WHERE ax.date_stat >=toDate('2021-02-20')
) ax
SETTINGS allow_experimental_window_functions = 1;
```
You may get
------------------------------------------------------------
"date_stat","customer_no","loan_principal","id_rank"
2023-10-28,USER_A,70000.0,1
2023-10-28,USER_A,60000.0,2
2023-10-28,USER_A,10000.0,3
2023-10-28,USER_A,20000.0,4
2023-10-28,USER_A,50000.0,5
2023-10-28,USER_A,40000.0,6
2023-10-28,USER_A,80000.0,7
2023-10-28,USER_A,30000.0,8
---------------------------------------------------------------

**Comment by akuzm** [comment]
The window functions are broken for distributed tables, see this one as well: https://github.com/ClickHouse/ClickHouse/issues/22121

**Comment by akuzm** [comment]
I'll close this one as a duplicate and will continue in #22121
