### ISSUE TITLE
arrayFill description in Russian

### ISSUE THREAD

**Issue by kolsys** [ClickHouse/ClickHouse#22377]
**Describe the issue**
`arrayFill`, `arrayReverseFill`, `arraySplit`, `arrayReverseSplit` descriptions are not exists in Russian documentation.

**Comment by filimonov** [comment]
Btw: you can translate it and send PR ;)

**Comment by kitaisreal** [comment]
Fixed in scope of https://github.com/ClickHouse/ClickHouse/pull/22493.
