### ISSUE TITLE
Allow arbitrary number of merges to process concurrently according to their priorities.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#22381]
**Current behaviour**

Merge operation occupies a slot in background pool.
If merge operation is started we can either continue to process it util finished or cancel it.
For this reason, we have a logic to limit the size of merge operation:
\- if half of pool is occupied and big merge is already processed, then only smaller merges (by specific ratio) can be processed.

This logic is needed to avoid stalls in smaller merges: big merges should not occupy the pool for a long time and small merges should be able to proceed.

**Describe the solution you'd like**

Allow more merges to start. Every merge has the inner loop where a block of data is processed. Wrap the iteration of this inner loop (a unit of work) to std::function. These units of work will be pushed to another pool for processing (a container under a mutex). A separate thread pool will select these units of work to process according to their priorities. The logic for priorities can be as simple: the total size to merge is smaller - the higher priority.

The size of thread pool can be smaller and it will be configured by user. For example, on extremely slow cloud instances with network disks it can be just 2. 

Big merges will be effectively paused when smaller merges needed to process. There is no concern if multiple big merges will be assigned.

**Comment by filimonov** [comment]
Is it possible both for vertical and horizontal merges? Does it guarantee that long merge will still be getting some cpu time even if new tiny merges are pushed with high frequency?

Now heuristics which picks the parts to merge rely on pool size and how busy it is. Does it stay the same?

**Comment by alexey-milovidov** [comment]
> Is it possible both for vertical and horizontal merges?

Yes.

> Does it guarantee that long merge will still be getting some cpu time even if new tiny merges are pushed with high frequency?

No and this is as expected. When there are too many small merges, large merges will not be processed.

> Now heuristics which picks the parts to merge rely on pool size and how busy it is. Does it stay the same?

The heuristic may require changes but not necessarily. Will check how it will work.

> If number of merges will go high - won't it lead to higher number of opened files and higher ram usage?

Yes, this is a concern, we can stop (cancel and postpone) large merges if they are not being scheduled.

**Comment by amosbird** [comment]
Is it possible that huge merges get starving to death?

**Comment by alexey-milovidov** [comment]
> Is it possible that huge merges get starving to death?

It can be possible, need to experiment.

**Comment by filimonov** [comment]
> I observe that in most production scenarios the number of concurrently executed merges is less than the pool size (it's around 1 on Yandex.Metrica servers)

That just means your system is well designed and servers are not overloaded.

Imagine the system with 1000 tables and realtime inserts in all of them. Or just system with very slow disks.

**Comment by filimonov** [comment]
>  it means that too many merges are not scheduled even in presense of free pool

I can conclude from that that it works quite good now - do we really need to touch it?

**Comment by alexey-milovidov** [comment]
Solved.

**Comment by filimonov** [comment]
https://github.com/ClickHouse/ClickHouse/pull/29140
