### ISSUE TITLE
NULL point out random value 

### ISSUE THREAD

**Issue by cicihou** [ClickHouse/ClickHouse#22397]
When I calculate one column, the NULL value will point out 0 or 1 in a random way.
Thus it will cause the strange result under the COUNT/SUM or some other function.

![image](https://user-images.githubusercontent.com/41445818/113086124-a1b59d00-9213-11eb-9ed9-7dec22b58eae.png)

I've simplify the SQL as followings
`        SELECT nlp_id, 
         nlp_lvl_pol,
         if(nlp_lvl_pol=5, 1, 0) as pos_score_origin,
         multiIf(nlp_lvl_pol=5, 1, nlp_lvl_pol is null, 0,  0) as pos_score_new
        FROM libyvocv110_nlp_wide
       	WHERE nlp_lvl_pol is NULL`

our clickhouse version is 20.5.2.7

I've read the document and understand the NULL will cause some other problem. But I don't find similar explanation in my situation.

It can be reproduced in many other tables with similar DDL in our DB.

Any feedback would be appreciated, If you've work on this issue, plz let me know.

Finally, many thanks for your brilliant works related to Clickhouse :)

**Comment by filimonov** [comment]
Please update to the latest 20.8 or newer and retry. Most probably fixed in  https://github.com/ClickHouse/ClickHouse/pull/11807

**Comment by alexey-milovidov** [comment]
I recommend to use version 21.3, not older.
