### ISSUE TITLE
How to use kafka enginer with avro format

### ISSUE THREAD

**Issue by tangxueming** [ClickHouse/ClickHouse#22409]
error : Code: 1001. DB::Exception: Received from xxx. DB::Exception: avro::Exception: EOF reached. 
version : 21.2.2
Accroding to test file [/test_storage_kafka/test.py](https://github.com/ClickHouse/ClickHouse/blob/master/tests/integration/test_storage_kafka/test.py#L410), I create a queue table and  a MATERIALIZED VIEW.
``` sql
CREATE TABLE office_env.kafka_avro (
                app_id String
) ENGINE = Kafka()
SETTINGS kafka_broker_list = '192.168.1.20:9092',
        kafka_topic_list = 'user_behavior_sink_avro_test',
        kafka_group_name = 'user_behavior_sink_avro_test_group',
        kafka_format = 'Avro',
        kafka_flush_interval_ms = 1000 ;
CREATE MATERIALIZED VIEW office_env.kafka_avro_mv Engine=Log AS
    SELECT *, _topic, _partition, _offset FROM office_env.kafka_avro;
```
1. Do  I set format_avro_schema_registry_url? In test file only AvroConfluent set format_avro_schema_registry_url.

**Comment by ilejn** [comment]
@tangxueming  
What you are doing is correct, registry_url is needed for AvroConfluent, not for Avro.

The issue you faced should be fixed by https://github.com/ClickHouse/ClickHouse/issues/21437 
Please, repeat your test against a version it is backported to and let me know if it works for you.
