### ISSUE TITLE
How to kill slow query process

### ISSUE THREAD

**Issue by lxswbr** [ClickHouse/ClickHouse#22404]
Why use the kill query statement to kill the slow query sql progress does not take effect

**Comment by KochetovNicolai** [comment]
Hi!
Not all stages of query are easily cancellable. But, also, it may be a bug.
If you have slow query, which cannot be killed, you may dump trace of query threads using query:
```sql
SELECT arrayStringConcat(arrayMap(x -> demangle(addressToSymbol(x)), trace), '\n')
FROM system.stack_trace
WHERE query_id = '24cf2c5b-f0e7-4916-87b1-0eadff5da86d'
SETTINGS allow_introspection_functions = 1
FORMAT Vertical
```
(replace `query_id` string with your query id, from `system.processes`)
and send result here.

**Comment by filimonov** [comment]
Also: provide a sample of the query which can not be killed.

**Comment by lxswbr** [comment]
@KochetovNicolai 
Hi! 
According to your method, all the following information can be found. Can you help me interpret what it means? Thanks

Row 600:
────────
arrayStringConcat(arrayMap(lambda(tuple(x), demangle(addressToSymbol(x))), trace), '
'): __lll_lock_wait
_L_lock_883
__GI___pthread_mutex_lock
std::__1::mutex::lock()
DB::PipelineExecutor::tryAddProcessorToStackIfUpdated(DB::ExecutingGraph::Edge&, std::__1::queue<DB::ExecutingGraph::Node*, std::__1::deque<DB::ExecutingGraph::Node*, std::__1::allocator<DB::ExecutingGraph::Node*> > >&, unsigned long)
DB::PipelineExecutor::prepareProcessor(unsigned long, unsigned long, std::__1::queue<DB::ExecutingGraph::Node*, std::__1::deque<DB::ExecutingGraph::Node*, std::__1::allocator<DB::ExecutingGraph::Node*> > >&, std::__1::unique_lock<std::__1::mutex>)
DB::PipelineExecutor::executeStepImpl(unsigned long, unsigned long, std::__1::atomic<bool>*)

ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>)

start_thread
clone

Row 601:
────────
arrayStringConcat(arrayMap(lambda(tuple(x), demangle(addressToSymbol(x))), trace), '
'): __lll_lock_wait
_L_lock_883
__GI___pthread_mutex_lock
std::__1::mutex::lock()
DB::PipelineExecutor::tryAddProcessorToStackIfUpdated(DB::ExecutingGraph::Edge&, std::__1::queue<DB::ExecutingGraph::Node*, std::__1::deque<DB::ExecutingGraph::Node*, std::__1::allocator<DB::ExecutingGraph::Node*> > >&, unsigned long)
DB::PipelineExecutor::prepareProcessor(unsigned long, unsigned long, std::__1::queue<DB::ExecutingGraph::Node*, std::__1::deque<DB::ExecutingGraph::Node*, std::__1::allocator<DB::ExecutingGraph::Node*> > >&, std::__1::unique_lock<std::__1::mutex>)
DB::PipelineExecutor::executeStepImpl(unsigned long, unsigned long, std::__1::atomic<bool>*)

ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>)

start_thread
clone

**Comment by KochetovNicolai** [comment]
As I see, there should be at lease 601 rows. Can I see them all? :)
Those two just wait on mutex, which is ok.
Also it would be interesting to see the query indeed.

**Comment by lxswbr** [comment]
@KochetovNicolai 
More than 600 lines are all the same information

**Comment by alexey-milovidov** [comment]
@lxswbr We need all 600+ lines of the result.
