### ISSUE TITLE
Understanding LTS releases

### ISSUE THREAD

**Issue by jindal-git** [ClickHouse/ClickHouse#22419]
I see that 21.3 is an LTS release, but there are 3 versions so far (21.3.2.5, 21.3.3.14, 21.3.4.25) and the documentation below doesn't refer to the specific version. Is the LTS still being validated? Which version will become the real LTS that is supported long term?

https://clickhouse.tech/docs/en/whats-new/changelog/

**Comment by alexey-milovidov** [comment]
Version 21.3 is the LTS version which means that it comes with one year support.

Whenever an issue is found and fixed, the patch is released.
These patches are numbered sequentially: 21.3.2, 21.3.3, 21.3.4, etc...

You should prefer the version with latest patches in production.
When a new patch comes, there are two options:
- simply upgrade - this is safe as the patch version comes with bugfixes and nothing more (but you still have to test the upgrade on testing environment if you have one - it is your own responsibility);
- check if the list of bugfixes contains anything relevant for you and make a decision, do you need to upgrage.

The patches are usually contain fixes for rare corner cases that you may have never face in production. But upgrade is recommended nevertheless.

The list of patches is located in the release pull request: https://github.com/ClickHouse/ClickHouse/pull/21495
