### ISSUE TITLE
Use Avro string for ClickHouse string

### ISSUE THREAD

**Issue by ilejn** [ClickHouse/ClickHouse#22414]
Selecting data from a String column to Avro format we get _bytes_ . 
For the sake of integration flexibility it is nice to be able to retrieve ClickHouse String as Avro _string_.

Current behavior must be preserved of course. 
_avro_type_for_string_ seems to be a good name for a new parameter to switch between bytes and string. Allowed values 'bytes' and 'string' with default 'bytes'.

Another option. We can introduce optional explicit Avro schema (similar to what we do for protobuf) as alternative of generating schema based on a query structure. This approach looks fine to me, but our customers prefer parameter.

**Comment by ilejn** [comment]
Plan to handle it.

**Comment by ilejn** [comment]
Does it make sense?
Feedback is appreciated.

**Comment by oandrew** [comment]
I think it would be useful to be able to specify which fields should be exported as avro string. Maybe wildcard/regex pattern? Then you could use something like avro_string_column_pattern=* to set it for all fields if needed. 
It was originally avro string when I implemented it but as @alexey-milovidov noted we have no guarantees Clickhouse String is a UTF8 string which is what avro string requires.

**Comment by ilejn** [comment]
I like the idea. 
Although this way seems slightly less elegant than _avro_type_for_string_, it is more useful from practical standpoint.
