### ISSUE TITLE
mysql client lost connect when query with format  TabSeparated

### ISSUE THREAD

**Issue by l1t1** [ClickHouse/ClickHouse#22416]
i connect clickhouse with the MySQL client,

mysql> select * from hu limit 2 format  TabSeparated;
ERROR 2013 (HY000): Lost connection to MySQL server during query
mysql> select * from hu limit 2;
ERROR 2006 (HY000): MySQL server has gone away
No connection. Trying to reconnect...
Connection id:    1
Current database: pop

normal result

**Comment by filimonov** [comment]
Mysql protocol don't support custom formats.

**Comment by l1t1** [comment]
thanks
