### ISSUE TITLE
SYSTEM STOP MERGES does not work

### ISSUE THREAD

**Issue by lingnancfy** [ClickHouse/ClickHouse#22420]
I want to use "SYSTEM STOP MERGES TABLE" to stop merge and then migrate some parts to another shard. My operation as follow: 
1： clickhouse-client -q "insert into DTDB.lineorder_demo FORMAT CSV" < lineorder.tbl； 
2： I execute "SYSTEM STOP MERGES DTDB.lineorder_demo" immediately after the import is complete But within 15 minutes, the parts will still merge and decrease.

**Comment by KochetovNicolai** [comment]
Could you try to run `SYSTEM STOP MERGES` before `insert`? Also, if table is replicated, you should run this query for every replica.

**Comment by den-crane** [comment]
lineorder_demo -- Distributed?

Because stop merges is not applicable to Distributed Engine

**Comment by lingnancfy** [comment]
> lineorder_demo -- Distributed?
> 
> Because stop merges is not applicable to Distributed Engine

I have understand it, stop merges is ok, This question is relevant to the old_part_time.

**Comment by den-crane** [comment]
SYSTEM STOP MERGES is not related to inactive parts

**Comment by FishermanZzhang** [comment]
@den-crane 

when test `Part movement between shards` https://github.com/ClickHouse/ClickHouse/pull/17871
I found the same problem.


`DB::Exception: Part is busy, reason: Part all_0_0_0 has already been assigned a merge into all_0_4_1. Stack trace: `

my code is :



```
import time
from clickhouse_driver import Client

"""
<ck01>                                                                                                                                                      
    <shard>                                                                                                                                                 
        <internal_replication>true</internal_replication>                                                                                                   
        <replica>                                                                                                                                           
            <host>centos01</host>                                                                                                                       
            <port>9000</port>                                                                                                                               
        </replica>                                                                                                                                          
        <replica>                                                                                                                                           
            <host>centos02</host>                                                                                                                       
            <port>9000</port>                                                                                                                               
        </replica>                                                                                                                                          
    </shard>                                                                                                                                                
    <shard>                                                                                                                                                 
        <internal_replication>true</internal_replication>                                                                                                   
        <replica>                                                                                                                                           
            <host>centos03</host>                                                                                                                       
            <port>9000</port>                                                                                                                               
        </replica>                                                                                                                                          
        <replica>                                                                                                                                           
            <host>centos04</host>                                                                                                                       
            <port>9000</port>                                                                                                                               
        </replica>                                                                                                                                          
    </shard>                                                                                                                                                
</ck01>   

"""

# shard 1
client_01 = Client('centos01')
client_02 = Client('centos02')
# shard 2
client_03 = Client('centos03')
client_04 = Client('centos04')


cluster = 'ck01'
database = 'tutorial'
table = 'test_move'


client_01.execute("drop table if exists {database}.{table} on cluster {cluster} no delay".format(database=database, table=table, cluster=cluster))

sql = '''CREATE TABLE if not exists {database}.{table}  on cluster {cluster} 
            (v UInt64)
            ENGINE=ReplicatedMergeTree
            ORDER BY tuple()'''.format(database=database, table=table, cluster=cluster)

print(sql)
r = client_01.execute(sql)

print("run ....")
time.sleep(5)

client_01.execute("SYSTEM STOP MERGES {database}.{table}".format(database=database, table=table))
client_02.execute("SYSTEM STOP MERGES {database}.{table}".format(database=database, table=table))

cnt = 10 
repeat = 3

for i in range(1, cnt + 1):
    sql = "INSERT INTO {database}.{table} VALUES ({value}), ({value}), ({value})".format(database=database, table=table, value=i)
    client_01.execute(sql)


r = client_01.execute("select count() from {database}.{table}".format(database=database, table=table))
assert cnt * repeat == r[0][0]

r = client_03.execute("select count() from {database}.{table}".format(database=database, table=table))
assert 0 == r[0][0]

sql = "ALTER TABLE {database}.{table} MOVE PART 'all_0_0_0' TO SHARD '/clickhouse/tables/ck_cluster/2/{database}/{table}'".format(database=database, table=table)
client_01.execute(sql)

client_01.execute("SYSTEM START MERGES {database}.{table}".format(database=database, table=table))
client_02.execute("SYSTEM START MERGES {database}.{table}".format(database=database, table=table))
client_01.execute("OPTIMIZE TABLE  {database}.{table} FINAL".format(database=database, table=table))

while True:
    if "DONE" == client_01.execute("SELECT state FROM system.part_moves_between_shards WHERE table = '{table}'".format(table=table))[0][0].strip():
        break
    print("move ..., wait for complete")
    time.sleep(1
```

**Comment by nvartolomei** [comment]
@FishermanZzhang what you are seeing is expected behaviour. There are 2 independent jobs running, one assigning merges for the whole shard and second running merges on replicas. System stop merges stops the second one but not the first one. Today I'm not aware of any mechanisms to stop the first one.

Re part movement, the idea is to let merges happen and at the same time try to move parts. It should work correctly. If you see an email exception like the one above then you wait until merge is done and try moving the resulting part.

Ps. The part movement is know to contain bugs. Do not use it in production if you care about your data at least until #24585

**Comment by sunny19930321** [comment]
I have the same problem，

**Comment by sunny19930321** [comment]
> @den-crane @KochetovNicolai @nvartolomei
> 
> when test `Part movement between shards` #17871 I found the same problem.
> 
> `DB::Exception: Part is busy, reason: Part all_0_0_0 has already been assigned a merge into all_0_4_1. Stack trace: `
> 
> my code is :
> 
> ```
> import time
> from clickhouse_driver import Client
> 
> """
> <ck01>                                                                                                                                                      
>     <shard>                                                                                                                                                 
>         <internal_replication>true</internal_replication>                                                                                                   
>         <replica>                                                                                                                                           
>             <host>centos01</host>                                                                                                                       
>             <port>9000</port>                                                                                                                               
>         </replica>                                                                                                                                          
>         <replica>                                                                                                                                           
>             <host>centos02</host>                                                                                                                       
>             <port>9000</port>                                                                                                                               
>         </replica>                                                                                                                                          
>     </shard>                                                                                                                                                
>     <shard>                                                                                                                                                 
>         <internal_replication>true</internal_replication>                                                                                                   
>         <replica>                                                                                                                                           
>             <host>centos03</host>                                                                                                                       
>             <port>9000</port>                                                                                                                               
>         </replica>                                                                                                                                          
>         <replica>                                                                                                                                           
>             <host>centos04</host>                                                                                                                       
>             <port>9000</port>                                                                                                                               
>         </replica>                                                                                                                                          
>     </shard>                                                                                                                                                
> </ck01>   
> 
> """
> 
> # shard 1
> client_01 = Client('centos01')
> client_02 = Client('centos02')
> # shard 2
> client_03 = Client('centos03')
> client_04 = Client('centos04')
> 
> 
> cluster = 'ck01'
> database = 'tutorial'
> table = 'test_move'
> 
> 
> client_01.execute("drop table if exists {database}.{table} on cluster {cluster} no delay".format(database=database, table=table, cluster=cluster))
> 
> sql = '''CREATE TABLE if not exists {database}.{table}  on cluster {cluster} 
>             (v UInt64)
>             ENGINE=ReplicatedMergeTree
>             ORDER BY tuple()'''.format(database=database, table=table, cluster=cluster)
> 
> print(sql)
> r = client_01.execute(sql)
> 
> print("run ....")
> time.sleep(5)
> 
> client_01.execute("SYSTEM STOP MERGES {database}.{table}".format(database=database, table=table))
> client_02.execute("SYSTEM STOP MERGES {database}.{table}".format(database=database, table=table))
> 
> cnt = 10 
> repeat = 3
> 
> for i in range(1, cnt + 1):
>     sql = "INSERT INTO {database}.{table} VALUES ({value}), ({value}), ({value})".format(database=database, table=table, value=i)
>     client_01.execute(sql)
> 
> 
> r = client_01.execute("select count() from {database}.{table}".format(database=database, table=table))
> assert cnt * repeat == r[0][0]
> 
> r = client_03.execute("select count() from {database}.{table}".format(database=database, table=table))
> assert 0 == r[0][0]
> 
> sql = "ALTER TABLE {database}.{table} MOVE PART 'all_0_0_0' TO SHARD '/clickhouse/tables/ck_cluster/2/{database}/{table}'".format(database=database, table=table)
> client_01.execute(sql)
> 
> client_01.execute("SYSTEM START MERGES {database}.{table}".format(database=database, table=table))
> client_02.execute("SYSTEM START MERGES {database}.{table}".format(database=database, table=table))
> client_01.execute("OPTIMIZE TABLE  {database}.{table} FINAL".format(database=database, table=table))
> 
> while True:
>     if "DONE" == client_01.execute("SELECT state FROM system.part_moves_between_shards WHERE table = '{table}'".format(table=table))[0][0].strip():
>         break
>     print("move ..., wait for complete")
>     time.sleep(1
> ```
Is there a good solution？cannot move because part is will to merge
