### ISSUE TITLE
General compression methods: support for bz2.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#22428]
**Use case**
Import and export of `bz2` files directly.

**Additional context**
It's extremely slow. But the use case is when there is already files in bz2 format and you have to deal with it.

**Comment by ucasFL** [comment]
Which library should use to implement this?

**Comment by alexey-milovidov** [comment]
The original library is ok: https://gitlab.com/federicomenaquintero/bzip2
