### ISSUE TITLE
How to build a release clickhouse-server

### ISSUE THREAD

**Issue by Zhile** [ClickHouse/ClickHouse#22435]
Hi, 
I'm trying to build a clickhouse-server docker image locally. 

I'm using this https://github.com/ClickHouse/ClickHouse/tree/master/docker/packager to build the binary, the command I use is like 
```
./packager --output-dir=/home/ubuntu/github/ClickHouse/docker/packager/output --package-type binary --compiler=clang-11  
```
But the generated binary `clickhouse` is too big, about 2.0GB in total. However I found the binary in yandex/clickhouser-server docker image is only about 291MB. Maybe my build process include some debug information or some kinds of lib? 

Q1: What commands (or options) should I use to build a binary like the one in docker image? 

I tried to use `./release` command, but there's some error like 
```
E: /var/cache/pbuilder/bionic-amd64/aptcache/: No such directory
E: debootstrap failed
E: debootstrap.log not present
```

```
W: /home/ubuntu/.pbuilderrc does not exist
using bionic-amd64 ubuntu bionic amd64 root http://mirror.yandex.ru/ubuntu/
I: pbuilder: network access will be disabled during build
I: Current time: Thu Apr  1 10:25:58 UTC 2021
I: pbuilder-time-stamp: 1617272758
I: Building the build Environment
I: extracting base tarball [/var/cache/pbuilder/bionic-amd64-base.tgz]
E: failed to find /var/cache/pbuilder/bionic-amd64-base.tgz, have you done <pbuilder create> to create your base tarball yet?
```

Q2: How to resolve these two errors? 

Thanks.

**Comment by zeekling** [comment]
The article maybe can help you : https://www.bookstack.cn/read/clickhouse-20.10-en/d91b58242743006c.md

I add `-DCMAKE_BUILD_TYPE="Release"` after `cmake .. `

The clickhouser will be about 400MB.
