### ISSUE TITLE
Live view vs interval query efficiency 

### ISSUE THREAD

**Issue by alex-klepa** [ClickHouse/ClickHouse#22436]
Hi @vzakaznikov,

I have a question, hope you can help me.
Let assume I have some query (`SELECT * FROM table WHERE updated_at > NOW64()- INTERVAL 1 second`) that select data updated within last second. I don't need every update, just snapshot every second.
What's going to be more efficient LIVE VIEW or just direct query every second?

Thank you

**Comment by vzakaznikov** [comment]
Hi @alex-klepa, efficiency will depend on how fast it takes to execute the query itself and the overall insert rate. If the result can be calculated fast you can use polling method and resend the query every second. Now, if you have 100's of clients sending the exact same query then a LIVE VIEW might be much more efficient as it will store the cached result in memory but might be more inefficient if you have many updates going into the source table as LIVE VIEW will try to be in sync with the source table and calculates new result for each insert block. In this case it really depends on your INSERT rate. The best way to find out what works for your specific case is to prototype both solutions. You also have to keep in mind that LIVE VIEW tables are still an experimental feature. Hope this helps.

**Comment by alex-klepa** [comment]
Thank you for detail explanation!

**Comment by vzakaznikov** [comment]
If don't need real-time updates then you can also try a solution using LIVE VIEW table but not using WATCH query. Instead you can use plain select on the LIVE VIEW. In this case what will happened is that you will still use polling method and resend your query to the LIVE VIEW every second. Now if the insert rate is not high and many clients send the same query to this LIVE VIEW at this very same second then they will all get an instant result as the result will be in the cache of the LIVE VIEW.

**Comment by alex-klepa** [comment]
Got it, I think I read your article regarding this, using LIVE VIEW as caching layer.

**Comment by vzakaznikov** [comment]
You are most welcome!
