### ISSUE TITLE
how to let clickhouse fill the new add columns to database files without modifying other columns

### ISSUE THREAD

**Issue by l1t1** [ClickHouse/ClickHouse#22439]
-> alter table ren add column agg UInt8 default 
    -> ( case 
    -> when age=0 then 0
    -> when age> 0 and age <100 then toUInt8(age/5)+1
    -> when age>=100 then 21
    -> end )
    -> ;

I used optimize table. it fast but didnot fill all rows. 
query system.parts_columns
optimze final command  filled all rows but modified other columns and slow

**Comment by UnamedRus** [comment]
```
ALTER TABLE ren UPDATE agg=agg WHERE 1;
```
