### ISSUE TITLE
Operator IN works incorrectly with NULL values.

### ISSUE THREAD

**Issue by StarWix** [ClickHouse/ClickHouse#2245]
In common case I want to do next queries:
```
SELECT * FROM table1
WHERE (x1, x2, ..., xn) IN (
   SELECT DISTINCT (y1, y2, ..., yn) FROM table2
)
```
where `x1`, ..., `xn`, `y1`, ..., `yn` can be null.

But now `null IN null == null` and rows with nulls are missing in results.

I expect that `null in null` should return `1` as it works with `nan` values.

```
CREATE TABLE test
(
    x Nullable(Float64)
)
ENGINE = Log;

INSERT INTO test VALUES(1, NaN, null);

SELECT x
FROM test 
WHERE x IN nan;

┌───x─┐
│ nan │
└─────┘

SELECT x
FROM test 
WHERE x IN NULL;

Ok.

SELECT 
    x, 
    x IN NULL, 
    x = NULL, 
    x IN nan, 
    x = nan
FROM test;

┌───x─┬─in(x, NULL)─┬─equals(x, NULL)─┬─in(x, nan)─┬─equals(x, nan)─┐
│   1 │           0 │ \N              │          0 │              0 │
│ nan │           0 │ \N              │          1 │              0 │
│  \N │          \N │ \N              │         \N │             \N │
└─────┴─────────────┴─────────────────┴────────────┴────────────────┘
```

**Comment by atris** [comment]
Is this issue relevant? I would like to fix this if it makes sense

**Comment by atris** [comment]
@alexey-milovidov Please let me know

**Comment by alexey-milovidov** [comment]
The behaviour is correct.

It is compatible to SQL standard and to MySQL, Postgres, SQLite, MS SQL:
http://sqlfiddle.com/#!9/0a28f18/105
http://sqlfiddle.com/#!17/0a28f/82
http://sqlfiddle.com/#!5/0a28f18/1
http://sqlfiddle.com/#!18/9eecb/16802

In contrast, NaNs are not exist in standard SQL and we do whatever we like for them: for the purpose of GROUP BY, DISTINCT, IN, JOIN, we compare bit representations of NaNs. Note that there are many NaNs with different bit representations.

It's possible to implement a setting to allow NULLs to be found in sets and to be JOINed.
This is almost straightforward but few complications exist: for example, data structures for Set and Join table engines will become incompatible and changing this hypothetical setting may lead to segfaults.

**Comment by StarWix** [comment]
@alexey-milovidov it would be nice to have this setting.

**Comment by blinkov** [comment]
@StarWix, do you have any further questions?

**Comment by masm22** [comment]
@blinkov am I right saying that the suggested way to select records where attribute value equals NULL is using `isNull()` function?

**Comment by blinkov** [comment]
> @blinkov am I right saying that the suggested way to select records where attribute value equals NULL is using `isNull()` function?

Yes, you can also use more common `foo IS NULL` syntax.

**Comment by masm22** [comment]
@blinkov thanks. I believe you could close the issue.
