### ISSUE TITLE
HDFS table engine triggers crash

### ISSUE THREAD

**Issue by likang-github** [ClickHouse/ClickHouse#22460]
![image](https://user-images.githubusercontent.com/43307989/113323506-9f089400-9348-11eb-9460-3325d48d9f9e.png)

**Comment by filimonov** [comment]
Normally that should not happen. Core file is created when the process segfault. 

It is alway a sign of some bug. 

To invistigate it we need clickhouse version and fragment of clickhouse logs (see /var/log/clickhouse-server/clickhouse-server.log) - lines around '####'.

Optionally the coredump files can also be used to debug the issue.

**Comment by likang-github** [comment]
how can i  specify the core.* file generation path through the config.xml

**Comment by alexey-milovidov** [comment]
Do you use the official ClickHouse release binaries?

**Comment by likang-github** [comment]
yes version 20.12.3.3

**Comment by filimonov** [comment]
Please do

```
grep '####' -C50 /var/log/clickhouse-server/clickhouse-server.log
```

**Comment by likang-github** [comment]
![image](https://user-images.githubusercontent.com/43307989/113386373-b5e8ce00-93bc-11eb-94e0-da40db6e862d.png)

**Comment by likang-github** [comment]
[users.txt](https://github.com/ClickHouse/ClickHouse/files/6248005/users.txt)
[config.txt](https://github.com/ClickHouse/ClickHouse/files/6248006/config.txt)

**Comment by likang-github** [comment]
![image](https://user-images.githubusercontent.com/43307989/113387563-1ed14580-93bf-11eb-8ff8-59d059157fb6.png)

**Comment by likang-github** [comment]
[clickhouse-server.zip](https://github.com/ClickHouse/ClickHouse/files/6248084/clickhouse-server.zip)

**Comment by alexey-milovidov** [comment]
It's related to HDFS, the issue is duplicate of:

#22115
#13406

**Comment by likang-github** [comment]
change table engine？ use  MergeTree？

**Comment by alexey-milovidov** [comment]
@likang-github 

@kssenii are trying to reproduce this issue with HDFS Docker image but is not being able to reproduce it yet.
Any help with reproducing example is appreciated.

**Comment by alexey-milovidov** [comment]
Duplicate #13406.
