### ISSUE TITLE
Modify ttl does not affects old parts.

### ISSUE THREAD

**Issue by vsop-479** [ClickHouse/ClickHouse#22483]
To my invesigation, ClickHouse uses old parts' ttl as a new part's ttl when merging, so it would not delete old parts desipte modifying table's ttl.
Maybe clickhouse can use modified table's ttl as new part's ttl when merging to delete old parts‘ data.

**Comment by den-crane** [comment]
What Clickhouse version do you use?
Modern Clickhouse recalculate TTL when alter table modify ttl applied.

Also use `ALTER TABLE ... MATERIALIZE TTL` to materialize ttl.

**Comment by vsop-479** [comment]
My Clickhouse version is 20.6.
I will test it on a new version.

**Comment by vsop-479** [comment]
20.10.6.27 can delete old parts.
