### ISSUE TITLE
Improve data skip index usability add `system.data_skip_indexes` table

### ISSUE THREAD

**Issue by Slach** [ClickHouse/ClickHouse#22485]
**Use case**
I need to know which secondary index presents and which column it used without parsing `create_table_query` from `system.tables` 
And maybe statistic about efficiency (how much granules / bytes checked and how many granules \ bytes skipped), 
skip index disk size etc.

**Describe the solution you'd like**
Add `system.data_skip_indexes`

**Comment by filimonov** [comment]
https://github.com/ClickHouse/ClickHouse/issues/7659

**Comment by Slach** [comment]
oops
