### ISSUE TITLE
If leader excute a merge task but leader is down, other replicas only fetch the part, what about this merge task?

### ISSUE THREAD

**Issue by Sallery-X** [ClickHouse/ClickHouse#22490]

**Comment by filimonov** [comment]
> other replicas only fetch the part

Why? Normally all replicas do merges, not only leader. Also since 20.5 there are no leaders.

**Comment by Sallery-X** [comment]
> > other replicas only fetch the part
> 
> Why? Normally all replicas do merges, not only leader. Also since 20.5 there are no leaders.

I know the feature, If i use the old version, what about the merge task?

**Comment by filimonov** [comment]
Normally all replicas do merges

**Comment by Sallery-X** [comment]
> Normally all replicas do merges

I know that!  that's not my question

**Comment by filimonov** [comment]
If you explicitly forbid to some replicas to do merges - they will not do it, and task will stay in queue. It is not related to leaders etc.

**Comment by Sallery-X** [comment]
> If you explicitly forbid to some replicas to do merges - they will not do it, and task will stay in queue. It is not related to leaders etc.
some replicas not do merges, but they will fetch, I mean the replica is down that is doing merge

**Comment by Sallery-X** [comment]
> > If you explicitly forbid to some replicas to do merges - they will not do it, and task will stay in queue. It is not related to leaders etc.
> > some replicas not do merges, but they will fetch, I mean the replica is down that is doing merge

Please read my question

**Comment by Sallery-X** [comment]
> If you explicitly forbid to some replicas to do merges - they will not do it, and task will stay in queue. It is not related to leaders etc.


Please read my question carefully

**Comment by filimonov** [comment]
I've read it. I've answered that

If you fill my answer not satisfy you - please introduce more details / context.

Asking me to reread the question is not constructive. If you think it can help with something - please reread my answer above. 10 times :p

**Comment by filimonov** [comment]
BTW maybe your English / translate is just too poor. Execute vs 'have executed'?
