### ISSUE TITLE
Query with JOIN ON does not support OR

### ISSUE THREAD

**Issue by piatto-evision** [ClickHouse/ClickHouse#22509]
I need to run this query:

SELECT `t0`.`nazione` AS `nazione`,
  `t0`.`segmento` AS `segmento`,
  `t1`.`X_measure__0` AS `sum_Calculation_570831280438702082_ok`,
  `t0`.`sum_vendita_ok` AS `sum_vendita_ok`
FROM (
  SELECT `supermercato`.`nazione` AS `nazione`,
    `supermercato`.`segmento` AS `segmento`,
    SUM(`supermercato`.`vendita`) AS `sum_vendita_ok`
  FROM `supermercato`
  GROUP BY `nazione`,
    `segmento`
) `t0`
  INNER JOIN (
  SELECT SUM(`supermercato`.`vendita`) AS `X_measure__0`,
    `supermercato`.`segmento` AS `segmento`
  FROM `supermercato`
  GROUP BY `segmento`
) `t1` ON ((`t0`.`segmento` = `t1`.`segmento`) OR ((`t0`.`segmento` IS NULL) AND (`t1`.`segmento` IS NULL)))

But clickhouse version 21.3.3.14 (official build) server gives me the following error:

Code: 48, e.displayText() = DB::Exception: JOIN ON does not support OR. Unexpected '(segmento = t1.segmento) OR (isNull(segmento) AND isNull(t1.segmento))': While processing (segmento = t1.segmento) OR (isNull(segmento) AND isNull(t1.segmento)) 

Is there a compatible different syntax to run the query?

Is there a possibility that 'INNER JOIN ON' with 'OR 'syntax will be supported in the future ??

**Comment by den-crane** [comment]
JOIN ON OR not supported yet.  Use 2 queries and union all

Work in progress https://github.com/ClickHouse/ClickHouse/pull/21320

**Comment by piatto-evision** [comment]
> JOIN ON OR not supported yet. Use 2 queries and union all. Or convert Nulls to some values in subqueries.
> 
> Work in progress #21320

Thanks so much for the reply Denny Crane.
I hope this feature will be implemented soon.

**Comment by griguolcomerranas** [comment]
This issue was closed some time ago, however it is still not working, even with the recent merge of [#21320](https://github.com/ClickHouse/ClickHouse/pull/21320). The JOIN ON with OR conditions is probably not an issue anymore however the problem might be somehow related with the  **JOIN ON "NULL"** condition.
Would it be possible to fix it at some point in the future? Or it does not even make sense?
Thanks for the help!

**Comment by griguolcomerranas** [comment]
Hello again.
Everything seems to be working fine with the  [new v1.0.0 stable release of the Altinity connector](https://github.com/Altinity/clickhouse-tableau-connector-odbc/releases/tag/v1.0.0).
So, probably no need or big rush  to fix the JOIN ON with OR and NULL conditions anymore
Thanks a lot for your help!
