### ISSUE TITLE
delete table cause error in clickhouse 1.1.54378 (stable)

### ISSUE THREAD

**Issue by pdeva** [ClickHouse/ClickHouse#2250]
just upgraded to `1.1.54378`.

i did a delete table. however it seems for some reason clickhouse didnt properly clean up the table.
now i see this error msg everytime i try to execute any query:

```
SELECT *
FROM system.tables

Received exception from server (version 1.1.54378):
Code: 60. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Table ds.metastore2 doesn't exist..

0 rows in set. Elapsed: 0.062 sec.
```

here is a stacktrace from logs:

```
2018.04.20 03:45:39.267401 [ 28 ] <Error> executeQuery: Code: 60, e.displayText() = DB::Exception: Table ds.metastore2 doesn't exist., e.what() = DB::Exception (from 98.210.189.103:62472) (in query: SELECT database,name,engine FROM system.tables   FoRmAt JSON), Stack trace:
0. /usr/bin/clickhouse-server(StackTrace::StackTrace()+0x15) [0x84e2995]
1. /usr/bin/clickhouse-server(DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)+0x21) [0x2cc9d61]
2. /usr/bin/clickhouse-server(DB::Context::getTableImpl(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, DB::Exception*) const+0x371) [0x7cab251]
3. /usr/bin/clickhouse-server(DB::Context::getTable(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const+0x72) [0x7cab5a2]
4. /usr/bin/clickhouse-server(DB::StorageMaterializedView::getDataPath[abi:cxx11]() const+0x38) [0x81c91b8]
5. /usr/bin/clickhouse-server(DB::StorageSystemTables::read(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, DB::SelectQueryInfo const&, DB::Context const&, DB::QueryProcessingStage::Enum&, unsigned long, unsigned int)+0xeb4) [0x5f61304]
6. /usr/bin/clickhouse-server(DB::InterpreterSelectQuery::executeFetchColumns(DB::InterpreterSelectQuery::Pipeline&, bool)+0x16d9) [0x7d00839]
7. /usr/bin/clickhouse-server(DB::InterpreterSelectQuery::executeImpl(DB::InterpreterSelectQuery::Pipeline&, std::shared_ptr<DB::IBlockInputStream> const&, bool)+0x4b) [0x7d02b7b]
8. /usr/bin/clickhouse-server(DB::InterpreterSelectQuery::executeWithMultipleStreams()+0x48) [0x7d03be8]
9. /usr/bin/clickhouse-server(DB::InterpreterSelectWithUnionQuery::executeWithMultipleStreams()+0x6b) [0x7d0d77b]
10. /usr/bin/clickhouse-server(DB::InterpreterSelectWithUnionQuery::execute()+0x37) [0x7d0da47]
11. /usr/bin/clickhouse-server() [0x7d68691]
12. /usr/bin/clickhouse-server(DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, DB::Context&, std::function<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>)+0x115) [0x7d69a75]
13. /usr/bin/clickhouse-server(DB::HTTPHandler::processQuery(Poco::Net::HTTPServerRequest&, HTMLForm&, Poco::Net::HTTPServerResponse&, DB::HTTPHandler::Output&)+0x2d56) [0x2ce65d6]
14. /usr/bin/clickhouse-server(DB::HTTPHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&)+0x24b) [0x2ce895b]
15. /usr/bin/clickhouse-server(Poco::Net::HTTPServerConnection::run()+0x331) [0x86d4461]
16. /usr/bin/clickhouse-server(Poco::Net::TCPServerConnection::start()+0xe) [0x86ccd0e]
17. /usr/bin/clickhouse-server(Poco::Net::TCPServerDispatcher::run()+0x169) [0x86cd0e9]
18. /usr/bin/clickhouse-server(Poco::PooledThread::run()+0x76) [0x876eec6]
19. /usr/bin/clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0x37) [0x876b0d7]
20. /usr/bin/clickhouse-server() [0x8dcbe7e]
21. /lib/x86_64-linux-gnu/libpthread.so.0(+0x76b9) [0x7f56b6c206b9]
22. /lib/x86_64-linux-gnu/libc.so.6(clone+0x6c) [0x7f56b644941c]
```

it seems for some reason the entry was not removed from `system.tables`

**Comment by zhang2014** [comment]
How recover:
```
CREATE TABLE `.inner.${materialized_view_name}`(${materialized_view_columns_list}) Engine = ${materialized_view_engine};
DROP TABLE ${materialized_view_name};
```
After that, the materialized view and the inner table are deleted.

**Comment by zhang2014** [comment]
It is weird to delete a materialized view when the inner table is deleted. Because their dependencies can't do that And There will be compatibility problem. : )

**Comment by pdeva** [comment]
ok i got the database recovered.

either way if a `drop table` statement is going to result in a corrupt database, clickhouse needs to throw an error and stop the user from executing it. otherwise eventually someone is going to run into this problem again.

**Comment by zhang2014** [comment]
How do we stop this type of problem? @alexey-milovidov

**Comment by pdeva** [comment]
may i know what an 'inner table' refers to here?

**Comment by zhang2014** [comment]
The materialized view links the dependency table to the inner table, and the data is calculated and stored in the inner table.

**Comment by pdeva** [comment]
cant you just check when doing a `drop table` if any materialized views reference the table being dropped as an inner table? seems like a fairly simple (and necessary) check to me.

**Comment by andrea-s** [comment]
Hey,

this happens also by dropping a database that contains any materialized view. I think this is a fairly severe regression...

**Comment by andrea-s** [comment]
`83b6f0483a5c :) create database some_tests

CREATE DATABASE some_tests

Ok.

0 rows in set. Elapsed: 0.032 sec.

83b6f0483a5c :) create table some_tests.my_table ENGINE = MergeTree(day, (day), 8192) as select today() as day, 'mystring' as str;

CREATE TABLE some_tests.my_table
ENGINE = MergeTree(day, day, 8192) AS
SELECT
    today() AS day,
    'mystring' AS str

Ok.

0 rows in set. Elapsed: 0.049 sec.

83b6f0483a5c :) show tables from some_tests;

SHOW TABLES FROM some_tests

┌─name─────┐
│ my_table │
└──────────┘

1 rows in set. Elapsed: 0.025 sec.

83b6f0483a5c :) create materialized view some_tests.my_materialized_view ENGINE = MergeTree(day, (day), 8192) as select * from some_tests.my_table;

CREATE MATERIALIZED VIEW some_tests.my_materialized_view
ENGINE = MergeTree(day, day, 8192) AS
SELECT *
FROM some_tests.my_table

Ok.

0 rows in set. Elapsed: 0.035 sec.

83b6f0483a5c :) show tables from some_tests;

SHOW TABLES FROM some_tests

┌─name────────────────────────┐
│ .inner.my_materialized_view │
│ my_materialized_view        │
│ my_table                    │
└─────────────────────────────┘

3 rows in set. Elapsed: 0.005 sec.

83b6f0483a5c :) select * from some_tests.my_materialized_view;

SELECT *
FROM some_tests.my_materialized_view

Ok.

0 rows in set. Elapsed: 0.004 sec.

83b6f0483a5c :) drop database some_tests;

DROP DATABASE some_tests

Received exception from server (version 1.1.54380):
Code: 60. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Table some_tests.`.inner.my_materialized_view` doesn't exist..

0 rows in set. Elapsed: 0.300 sec.`

**Comment by andrea-s** [comment]
Tagging @alexey-milovidov for visibility (since this issue is not on the front page anymore)

**Comment by alexey-milovidov** [comment]
Not relevant anymore.
Added a test just in case: 966f46cfab
