### ISSUE TITLE
Data duplication with ALTER commands, using ReplicatedMergeTree with S3 storage

### ISSUE THREAD

**Issue by taiwhite** [ClickHouse/ClickHouse#22516]
**Describe the bug**
When a ReplicatedMergeTree table on S3 storage with multiple replicas is modified using ALTER commands, the data on S3 is duplicated every time ALTER is used.

**Does it reproduce on recent release?**
[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)
* 21.2.2.8 revision 54447
* 21.4.1 revision 54447

**How to reproduce**
* Version: 21.4.1 revision 54447 or 21.2.2.8 revision 54447
* Storage configuration:
```
<storage_configuration>
    <disks>
      <external>
        <type>s3</type>
        <endpoint>[AWS S3 endpoint]</endpoint>
        <access_key_id>[access_key_id]</access_key_id>
        <secret_access_key>[secret_access_key]</secret_access_key>
      </external>
    </disks>
    <policies>
      <external>
        <volumes>
          <external>
            <disk>external</disk>
          </external>
        </volumes>
      </external>
    </policies>
  </storage_configuration>
```
* Statements to reproduce error:
Create replicated table on two instances of ClickHouse:
```
CREATE TABLE zero_copy_replication ( d UInt64, sign Int8 ) ENGINE = ReplicatedMergeTree('/clickhouse/zero_copy_replication', '1') ORDER BY d 
SETTINGS storage_policy='external';
CREATE TABLE zero_copy_replication ( d UInt64, sign Int8 ) ENGINE = ReplicatedMergeTree('/clickhouse/zero_copy_replication', '2') ORDER BY d 
SETTINGS storage_policy='external';
```
Insert data into the table, then alter the table on either instance using a command similar to this:
`ALTER TABLE zero_copy_replication UPDATE sign = 1 WHERE 1;`
Then SYNC on both instances:
`SYSTEM SYNC REPLICA zero_copy_replication;`
Each time the table is altered using similar commands, data will be duplicated in the AWS S3 bucket.

**Expected behavior**
No increase in the amount of data in the S3 bucket when the replicated table is altered.

**Comment by Jokser** [comment]
@taiwhite 
Have you tried zero-copy option for 21.4 version?
```
    <merge_tree>
        <allow_s3_zero_copy_replication>1</allow_s3_zero_copy_replication>
    </merge_tree>
```

**Comment by taiwhite** [comment]
@Jokser 
I did try this option. The bug is present in both 21.2 and 21.4, when zero-copy is enabled and disabled.

**Comment by PolyProgrammist** [comment]
Checked 21.2.2.8 version, it also removes data after some time. So everything is ok.

@taiwhite
