### ISSUE TITLE
CSV parsing setting: format_csv_not_trim_spaces

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#22574]
**Use case**
CSV file with unquoted strings and spaces at start and end of strings which needs to be preserved.

>  In violation of the RFC, when parsing rows without quotes, the leading and trailing spaces and tabs are ignored. 

```
echo "aa ,2" | clickhouse-local -S "a String, b int" --input-format="CustomSeparated" --format_custom_escaping_rule=CSV --format_custom_field_delimiter=',' --format_csv_delimiter=',' -q "select * from table FORMAT CSV"
"aa",2
```

**Describe the solution you'd like**
Setting

https://github.com/ClickHouse/ClickHouse/issues/6742#issuecomment-526567265

**Comment by Alex-Cheng** [comment]
Is there any workaround except upgrading clickhouse.
