### ISSUE TITLE
Clickhouse doesn't respect cgroup limits

### ISSUE THREAD

**Issue by tobad357** [ClickHouse/ClickHouse#2261]
Currently getNumberOfPhysicalCPUCores doesn't respect if CK is run inside of a docker container / cgroup. It will return the actual amount of cores on the host instead of the limited amount
Which I'm guessing means CK sizes thread pools etc to use all CPUs instead of the allocated amount

Suggested would be to read ```/sys/fs/cgroup/cpu/cpu.cfs_quota_us``` if > -1 and divide by 1000 and round up to closest integer

For memory CK could read ```/sys/fs/cgroup/memory/memory.limit_in_bytes``` if available

**Comment by atris** [comment]
I have raised a PR for the same. https://github.com/yandex/ClickHouse/pull/2325

**Comment by reflection** [comment]
Clickhouse still doesn't respect cgroup limits, unfortunately.  The merged pull request incorrectly calculates physical cpus and doesn't address memory limits (docker image below modified to log to console at debug level):

```
# Start with memory limited to 1gb and cpus limited to 1 core
# https://docs.docker.com/v17.09/engine/admin/resource_constraints/#limit-a-containers-access-to-memory
$ docker run -d --name ch --ulimit nofile=262144:262144 -p 8123:8123 -p 9000:9000 -m 1g --cpus="1.0" -v /tmp/ch-data:/var/lib/clickhouse clickhouse

# Clickhouse incorrectly sees 100 (!!!) cores and full system RAM
$ docker logs ch
2018.08.23 23:35:17.405633 [ 1 ] <Information> : Starting ClickHouse 18.10.3 with revision 54405
...
2018.08.23 23:35:17.419872 [ 1 ] <Information> Application: Available RAM = 15.61 GiB; physical cores = 100; threads = 4.
```

**Comment by alexey-milovidov** [comment]
The calculation in the PR looks incorrect:

```
$ docker run -m 1g --cpus="1.0" ubuntu:trusty cat /sys/fs/cgroup/cpu/cpu.cfs_quota_us
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
100000
```

But I have no idea, why it is using the value "cpu.cfs_quota_us". Looks totally irrelevant.
Should I simply revert this PR or some trivial fix is possible?

**Comment by reflection** [comment]
Thanks for reverting.  In the #2325 pull request @bobrik linked to [openjdk's cgroup work](http://hg.openjdk.java.net/jdk/jdk/rev/7f22774a5f42).

For cpu: `int OSContainer::active_processor_count()`
For memory: `long OSContainer::memory_limit_in_bytes()`

**Comment by bobrik** [comment]
I'll take this chance to also mention that if you're using CFS quotas, there's a high chance you're throttling when you shouldn't: https://github.com/kubernetes/kubernetes/issues/67577.

**Comment by sushiMix** [comment]
is cgroup supported ? It seems some code has been merged from #2325 but it is not clear for me.

**Comment by alexey-milovidov** [comment]
It is implemented for memory but not implemented for CPU.

This task remains super easy, free for grabs :)

**Comment by JaySon-Huang** [comment]
I create a PR for this issue: https://github.com/ClickHouse/ClickHouse/pull/33342
