### ISSUE TITLE
Documentation for system's tables.

### ISSUE THREAD

**Issue by webmaks** [ClickHouse/ClickHouse#2264]
There is no documentation for system's tables. Because we do not have exaclty description such paramenters like these (all parameters into database "system"):  

Query                                   
SelectQuery                             
InsertQuery                             
FileOpen                                
Seek                                    
ReadBufferFromFileDescriptorRead        
ReadBufferFromFileDescriptorReadBytes   
WriteBufferFromFileDescriptorWrite      
WriteBufferFromFileDescriptorWriteBytes 
ReadCompressedBytes                     
CompressedReadBufferBlocks              
CompressedReadBufferBytes               
IOBufferAllocs                          
IOBufferAllocBytes                      
ArenaAllocChunks                        
ArenaAllocBytes                         
FunctionExecute                         
MarkCacheHits                           
MarkCacheMisses                         
CreatedReadBufferOrdinary               
CreatedWriteBufferOrdinary              
ReplicatedPartMerges                    
InsertedRows                            
InsertedBytes                           
ZooKeeperInit                           
ZooKeeperTransactions                   
ZooKeeperGetChildren                    
ZooKeeperCreate                         
ZooKeeperRemove                         
ZooKeeperExists                         
ZooKeeperGet                            
ZooKeeperSet                            
ZooKeeperMulti                          
SelectedParts                           
SelectedRanges                          
SelectedMarks                           
MergedRows                              
MergedUncompressedBytes                 
MergesTimeMilliseconds                  
MergeTreeDataWriterRows                 
MergeTreeDataWriterUncompressedBytes    
MergeTreeDataWriterCompressedBytes      
MergeTreeDataWriterBlocks               
MergeTreeDataWriterBlocksAlreadySorted  
LeaderElectionAcquiredLeadership        
RegexpCreated                           
ContextLock                             
RWLockAcquiredReadLocks                 
RWLockReadersWaitMilliseconds           

 we can't monitoring  it properly. We would like to add it to zabbix monitoring system in order to monitoring clickhouse. And it would be very helped for better understanding clickhouse.

**Comment by ThomasBarach** [comment]
+1

**Comment by alexey-milovidov** [comment]
Now `system.events` and `system.metrics` tables have `description` column and the metrics are documented straight there.
