### ISSUE TITLE
Flaky tests after enabling parallel execution

### ISSUE THREAD

**Issue by CurtizJ** [ClickHouse/ClickHouse#22661]

**Comment by CurtizJ** [comment]
At 13:00 05.04

| test_name | c | last_time | first_seen | last_seen | comment | 
|:-:|-:|:-:|:-|:-|:-|
| 01666_merge_tree_max_query_limit | 10 | 2021-04-03 20:40:03 | 19e4a33f9d2dfa5293d74c195d916ba3ddff3a0e | 89db2b1ffc49aed82efcabffed1ccb594d6d550c |  |
| 01149_zookeeper_mutation_stuck_after_replace_partition | 5 | 2021-04-03 20:36:28 | f76846b7c5c7804c10d22616593f54ae09641e77 | 89db2b1ffc49aed82efcabffed1ccb594d6d550c |  |
| 01526_initial_query_id | 4 | 2021-04-05 02:43:36 | 3446870c2500a13955e397255ce52d268b422178 | a9eb7a7c7e9592c0a62be0b54fbcc6298e46d50e |  |
| 01107_atomic_db_detach_attach | 4 | 2021-04-04 14:18:00 | 35d62b73a7f766b7e9447e5e9a32e32baf2cf907 | 44e160596ef81aa9428da31b11201d6ce7763ba8 |  |
| 01502_long_log_tinylog_deadlock_race | 3 | 2021-04-02 18:56:23 | 121c5c96053ca07cdc9eca1f9458022400df3e22 | d0037329cfb8cefed50b4e88d04d90dac165d2e4 |  |
| 01670_log_comment | 2 | 2021-04-03 20:39:16 | 67fdfd4b894b817bb9cc5532ae300c524e5e373c | 89db2b1ffc49aed82efcabffed1ccb594d6d550c |  |
| 01730_distributed_group_by_no_merge_order_by_long | 2 | 2021-04-03 14:22:49 | c3a9cbe01c1c07d21cd1f89b31291a194fc21b25 | 6d9852344f510d58ebcf71a79b96cde036952aa7 |  |
| 01263_type_conversion_nvartolomei | 2 | 2021-04-03 11:24:27 | d0037329cfb8cefed50b4e88d04d90dac165d2e4 | 143f4b59a00747415931b9eef64f51b17740914b |  |
| 01039_row_policy_dcl | 1 | 2021-04-05 06:01:13 | a16a09eb2f81eb929998907b34512e1211eeb62f | a16a09eb2f81eb929998907b34512e1211eeb62f |  |
| 01383_log_broken_table | 1 | 2021-04-05 02:44:00 | 3df84d5b480889c9d78339e732bab84672a8028f | 3df84d5b480889c9d78339e732bab84672a8028f |  |
| 01360_materialized_view_with_join_on_query_log | 1 | 2021-04-04 22:44:41 | c0a13bb5d2ba55446c2167f2e0e4805acea70c87 | c0a13bb5d2ba55446c2167f2e0e4805acea70c87 |  |
| 01605_adaptive_granularity_block_borders | 1 | 2021-04-05 03:54:03 | f78c846bdf9b02ffff2fbc9c5f49571c7b01eff3 | f78c846bdf9b02ffff2fbc9c5f49571c7b01eff3 |  |
| 01455_opentelemetry_distributed | 1 | 2021-04-04 17:18:05 | 0d03b8c0c4e10de8599fa1787c0580a0238d7c84 | 0d03b8c0c4e10de8599fa1787c0580a0238d7c84 |  |
| 01622_defaults_for_url_engine | 1 | 2021-04-02 09:06:00 | 61d47947268d56f4e6af3022f02af5f697faab22 | 61d47947268d56f4e6af3022f02af5f697faab22 |  |
| 01702_system_query_log | 1 | 2021-04-02 09:07:06 | eec4ac75b0fdfb9a141fe35a0bcbc2112e5710b1 | eec4ac75b0fdfb9a141fe35a0bcbc2112e5710b1 |  |
| 01461_query_start_time_microseconds | 1 | 2021-04-02 20:27:39 | 18cb1bad253970bbea6734a4a2b62001b5ceaee5 | 18cb1bad253970bbea6734a4a2b62001b5ceaee5 |  |
| 01531_query_log_query_comment | 1 | 2021-04-03 22:43:09 | cb4e119c3d819f17d00f2815a9b3a42f1054ae1e | cb4e119c3d819f17d00f2815a9b3a42f1054ae1e |  |
| 01526_client_start_and_exit | 1 | 2021-04-04 14:41:03 | 44e160596ef81aa9428da31b11201d6ce7763ba8 | 44e160596ef81aa9428da31b11201d6ce7763ba8 |  |
| 01632_tinylog_read_write | 1 | 2021-04-03 11:24:27 | 143f4b59a00747415931b9eef64f51b17740914b | 143f4b59a00747415931b9eef64f51b17740914b |  |
| 01641_memory_tracking_insert_optimize_long | 1 | 2021-04-04 15:20:11 | 72cf7b01e88a4c69fddd687a933d3cc075a52c98 | 72cf7b01e88a4c69fddd687a933d3cc075a52c98 |  |

**Comment by CurtizJ** [comment]
`01526_initial_query_id` - probably bug in `SYSTEM FLUSH LOGS`

**Comment by CurtizJ** [comment]
`01383_log_broken_table` - Setting max_memory_usage shouldn't be greater than 6000000. Constraint is setting in `01294_create_settings_profile`.

**Comment by CurtizJ** [comment]
`01360_materialized_view_with_join_on_query_log`:  `DB::Exception: Timeout exceeded (60 s) while flushing system log 'DB::QueryLog'. ... (in query: SYSTEM FLUSH LOGS)`

**Comment by alesapin** [comment]
nasty tests https://github.com/ClickHouse/ClickHouse/pull/22670/files

**Comment by CurtizJ** [comment]
Functional tests are stable now.
