### ISSUE TITLE
Replicated tables with TTL moves or delete do not work when <allow_s3_zero_copy_replication> is set to 1

### ISSUE THREAD

**Issue by taiwhite** [ClickHouse/ClickHouse#22679]
**Describe the bug**
When <allow_s3_zero_copy_replication> is set to 1 in the <merge_tree> configuration, replicated tables with TTL moves or delete are broken. SELECT from replicated tables with TTL moves or delete causes errors.

**Does it reproduce on recent release?**
[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

* 21.4.1 revision 54447

**How to reproduce**
* Version: 21.4.1 revision 54447
* Storage configuration: 
```
<yandex>
  <storage_configuration>
    <disks>
      <external>
        <type>s3</type>
        <endpoint>[AWS S3 endpoint]</endpoint>
        <access_key_id>[access_key_id]</access_key_id>
        <secret_access_key>[secret_access_key]</secret_access_key>
      </external>
      <external_tiered>
        <type>s3</type>
        <endpoint>[AWS S3 endpoint]</endpoint>
        <access_key_id>[access_key_id]</access_key_id>
        <secret_access_key>[secret_access_key]</secret_access_key>
      </external_tiered>
    </disks>
    <policies>
      <external>
        <volumes>
          <external>
            <disk>external</disk>
          </external>
        </volumes>
      </external>
      <tiered>
        <volumes>
          <default>
            <disk>external</disk>
          </default>
          <external>
            <disk>external_tiered</disk>
          </external>
        </volumes>
      </tiered>
    </policies>
  </storage_configuration>
</yandex>
```
* Merge tree configuration:
```
<yandex>
  <merge_tree>
    <allow_s3_zero_copy_replication>1</allow_s3_zero_copy_replication>
  </merge_tree>
</yandex>
```
* Statements to reproduce error: 
Note: either of the two following create statements could be used -- the error occurs with both TTL move and TTL delete.

Create replicated table with TTL move on two instances of ClickHouse:
```
CREATE TABLE zero_copy_replication ( d UInt64, d1 DateTime ) ENGINE = ReplicatedMergeTree('/clickhouse/zero_copy_replication_ttl', '1') ORDER BY d 
TTL d1 + interval 2 day to volume 'external'
SETTINGS storage_policy='tiered';
CREATE TABLE zero_copy_replication ( d UInt64, d1 DateTime ) ENGINE = ReplicatedMergeTree('/clickhouse/zero_copy_replication_ttl', '2') ORDER BY d 
TTL d1 + interval 2 day to volume 'external'
SETTINGS storage_policy='tiered';
```
Alternate create statement, replicated table with TTL delete on two instances of ClickHouse:
```
CREATE TABLE zero_copy_replication ( d UInt64, d1 DateTime ) ENGINE = ReplicatedMergeTree('/clickhouse/zero_copy_replication_ttl', '1') ORDER BY d 
TTL d1 + interval 2 day
SETTINGS storage_policy='tiered';
CREATE TABLE zero_copy_replication ( d UInt64, d1 DateTime ) ENGINE = ReplicatedMergeTree('/clickhouse/zero_copy_replication_ttl', '2') ORDER BY d 
TTL d1 + interval 2 day
SETTINGS storage_policy='tiered';
```
Insert data into the table, with some rows before the 2 day TTL, and some rows after the 2 day TTL.
Then, SELECT using a command similar to the following:
```
SELECT COUNT() FROM zero_copy_replication
```

**Expected behavior**
Expect to be able to SELECT from a replicated table with TTL with <allow_s3_zero_copy_replication> set to 1.

**Error message and/or stacktrace**
Error message:
```
Code: 499. DB::Exception: Received from localhost:9000. 
DB::Exception: <?xml version="1.0" encoding="UTF-8"?><Error><Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>data/zero-copy-replication/xqzqytlaumwdavygqraanbwlllelhijs</Key>
<RequestId>0W01GFT6FX2J4VDF</RequestId>
<HostId>FGeqq3GokrJx9qHMxu9TeFgmWrm/2nH0c6xMLTAGxcWXBeZgnapkwOfJixZZN9JXjjjd6Ei6CKY=</HostId>
</Error>: (while reading column d): (while reading from part 
/var/lib/clickhouse/disks/external/store/83b/83b6fb95-f932-417a-aaaf-c709d864e7a5/all_2_2_0/ 
from mark 23 with max_rows_to_read = 8192): While executing MergeTreeReverse.
```

**Comment by ianton-ru** [comment]
I hope this PR fixes the bug.
https://github.com/ClickHouse/ClickHouse/pull/22864

**Comment by taiwhite** [comment]
@ianton-ru I am still receiving the same error. 

The tables I am using are the same as before. Note: This error occurs when there are two S3 buckets (the bucket urls are different).

Query: `SELECT d FROM zero_copy_replication ORDER BY d DESC LIMIT 1`
Error: ```Received exception from server (version 21.5.1):
                                 Code: 499. DB::Exception: Received from localhost:9000. DB::Exception: <?xml version="1.0" encoding="UTF-8"?>
                                 <Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>data/zero-copy-replication/yxgvblyphtcqefyfbopccojormhshpsl</Key><BucketName>root</BucketName><Resource>/root/data/zero-copy-replication/yxgvblyphtcqefyfbopccojormhshpsl</Resource><RequestId>1675210639F9C58A</RequestId><HostId>2b32c6b5-0aba-4acc-952c-7080ad9280db</HostId></Error>: (while reading column d): (while reading from part /var/lib/clickhouse/disks/external/store/3f5/3f5917b5-defe-477a-8303-90cd6ad2c89a/all_2_2_0/ from mark 23 with max_rows_to_read = 8192): While executing MergeTreeReverse.```

**Comment by ianton-ru** [comment]
> @ianton-ru I am still receiving the same error from [#22864](https://github.com/ClickHouse/ClickHouse/pull/22864).
> 
> The tables I am using are the same as before. Note: This error occurs when there are two S3 buckets (the bucket urls are different).
I can't reproduce it.
Could you please help me?
I can't see difference between your bug description and test code except names.
https://github.com/ClickHouse/ClickHouse/pull/22864/files#diff-0681639d33adaeb66aef8293c9fea215e340cafaca8fbefc284def4f43d1c45eR142
Does this test produce this error on your system, or I've lost something?

**Comment by taiwhite** [comment]
This test does not produce any errors for me, but I'm not sure why because everything seems very similar. Here are the functions I am using to insert values in a python script:

> Insert integers into table with specified time value for ttl moves
```python3
    def insert_data_time(node, number_of_mb, time, start=0):
        values = ','.join(f"({x},{time})" for x in range(start, int((1024 * 1024 * number_of_mb) / 8) + start + 1))
        node.query(f"INSERT INTO zero_copy_replication VALUES {values}")
```

```python3
tm = time.mktime((datetime.date.today() - datetime.timedelta(days=7)).timetuple())
insert_data_time(nodes[0], 1, tm, 0)
tm = time.mktime((datetime.date.today() - datetime.timedelta(days=3)).timetuple())
insert_data_time(nodes[0], 1, tm, 1024*1024)
tm = time.mktime(datetime.date.today().timetuple())
insert_data_time(nodes[0], 10, tm, 1024*1024*2)
```

Query to produce error:
```
SELECT COUNT() FROM zero_copy_replication
```

**Comment by ianton-ru** [comment]
I still can't reproduce.

**Comment by ianton-ru** [comment]
I can.
My mistake was that I set setting `min_bytes_for_wide_part` to 0 in tests. Default part type was detected incorrectly but this setting hide it.
Thanks to @Jokser
