### ISSUE TITLE
Error DB::Exception: There is no query: While processing Select 

### ISSUE THREAD

**Issue by aubweb9** [ClickHouse/ClickHouse#22688]
Hi, 

When I do an alter table delete using a specific query condition it makes clickhouse-server.log grow forever.
The only way to stop it is to manually kill the mutation.

The error is :
`2021.04.06 09:17:22.188417 [ 6001 ] {} <Error> auto DB::IBackgroundJobExecutor::jobExecutingTask()::(anonymous class)::operator()() const: Code: 393, e.displayText() = DB::Exception: There is no query: While processing (SELECT import_done FROM data.view_last_import WHERE id = 136) AS _subquery145131: While processing 0 = ((SELECT import_done FROM data.view_last_import WHERE id = 136) AS _subquery145131): While processing (id = 136) AND (0 = ((SELECT import_done FROM data.view_last_import WHERE id = 136) AS _subquery145131)),
`

Sample of the log : 
[ch_log.txt](https://github.com/ClickHouse/ClickHouse/files/6262885/ch_log.txt)

It's happening on current version and 20.12.3.3 as well.

The query  is : 
`ALTER TABLE data.smr_overview
DELETE WHERE id = xxx AND 0 = (select import_done from data.view_last_import where id = xxx);`

The data.smr_overview table is a simple MergeTree table.
The view_last_import DDL is (it's a CH view based on a mysql view):

`CREATE VIEW data.view_last_import
(
    `id` UInt32,
    `date_end_tz` Nullable(Date),
    `date_end_utc` Nullable(Date),
    `import_done` UInt8
) AS
SELECT
    id,
    date_end_tz,
    date_end_utc,
    import_done
FROM mysql('xxx.xxx.xx.xx:3306',
 'datas',
 'view_last_import',
 'xxxxxxxxxxxxxxx',
 'xxxxxxxxxxxxxxx');`

The view works perfectly and the import_done return always 1 or 0.
And if I remove the "AND 0 = (select import_done from data.view_last_import where id = xxx)" the delete works just fine.

I would expect that the mutation completes successfully and not to see an infinite loop on the logs.

Thanks,
Aub.

**Comment by hexiaoting** [comment]
In version 21.5.1.1, I try it, it seems run OK. 
Can you run it on the fresh master, or give us a minimal example that we can reproduce this error.
