### ISSUE TITLE
support alter table fetch part from zkshardpath

### ISSUE THREAD

**Issue by songenjie** [ClickHouse/ClickHouse#22705]
(you don't have to strictly follow this form)

**Use case**
fect part from zkshard pathh 

**Describe the solution you'd like**
contain in alter fetch partition like attach partition

**Comment by nvartolomei** [comment]
Already exists https://clickhouse.tech/docs/en/sql-reference/statements/alter/partition/#alter_fetch-partition?

**Comment by songenjie** [comment]
> Already exists https://clickhouse.tech/docs/en/sql-reference/statements/alter/partition/#alter_fetch-partition?

it just support fetch partition ,not support fetch part
