### ISSUE TITLE
dictGetOrDefault('dict','col',Null,0.0) returns Null

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#22727]
**Describe the unexpected behaviour**
If Null being passed as dictionary key, dictGetOrDefault returns null instead of default value.

**How to reproduce**
Clickhouse version 21.5, 21.1, 20.8

```

CREATE VIEW dict_null_source AS SELECT 1 as key, 1 as val;
CREATE DICTIONARY dict_null (key UInt64, val UInt32) PRIMARY KEY key SOURCE(CLICKHOUSE(host 'localhost' user 'default' table 'dict_null_source' ))LAYOUT(FLAT)LIFETIME(300)


SELECT dictGetOrDefault('default.dict_null', 'val', CAST(NULL, 'Nullable(UInt64)'), 0) AS val

Query id: 79518a8e-b439-4d08-a0b2-85e4b3ef99eb

┌──val─┐
│ ᴺᵁᴸᴸ │
└──────┘
```

**Additional context**
```

SELECT dictGetOrDefault('default.dict_null', 'val', CAST(1, 'UInt64'))

Query id: 71ec76a1-fb61-4641-9145-79c6bfffd490


0 rows in set. Elapsed: 0.001 sec.

Received exception from server (version 21.5.1):
Code: 42. DB::Exception: Received from localhost:9000. DB::Exception: Wrong argument count for function dictGetOrDefault: While processing dictGetOrDefault('default.dict_null', 'val', CAST(1, 'UInt64')).

```

Error message in 21.1 was better:  `Number of arguments for function dictGetOrDefault doesn't match: passed 3, should be 4:`

**Comment by kitaisreal** [comment]
Related to first issue, this is expected behaviour because dictionaries does not support nullable keys, and when nullable keys are passed into function we use default implementation.
Default implementation return null values if value in input column was null.
Related to second issues, I updated exceptions in scope of pull request https://github.com/ClickHouse/ClickHouse/pull/22821.

**Comment by UnamedRus** [comment]
>  Default implementation return null values if value in input column was null.

For me it's would be more convenient and expected if dictionary would return Default value in this case. (And dictGetOrNull would return Null) 
Our client face this behavior while running mutations and they stuck because of Null to non-null conversion.
But it looks like it's default behavior for a lot of functions:
```
SELECT toUInt32OrZero(NULL)

Query id: 14d28bcd-1f26-42c1-a9b5-8f57f879f8ca

┌─toUInt32OrZero(NULL)─┐
│ ᴺᵁᴸᴸ                 │
└──────────────────────┘

SELECT transform(NULL, [1, 2], [2, 3], 0)

Query id: 91d00c44-cf8a-4a58-918d-026eac35c489

┌─transform(NULL, [1, 2], [2, 3], 0)─┐
│ ᴺᵁᴸᴸ                               │
└────────────────────────────────────┘
```

> I updated exceptions in scope of pull request #22821.

Thank you.
