### ISSUE TITLE
Why does the clickhouse source code release package not contain the submodules source code?

### ISSUE THREAD

**Issue by wallace-clickhouse** [ClickHouse/ClickHouse#22730]
When I download the ClickHouse source code for compilation, I need to add the --recursive parameter to the git command to download the source code containing submodules.In addition, the release package of the clickhouse source code does not contain the submodules source code, this seems to be different from other open source communities.So I wonder why?

**Comment by alexey-milovidov** [comment]
Source code tarballs are generated automatically by GitHub:
https://github.com/ClickHouse/ClickHouse/releases/tag/v21.5.1.6463-testing
and GitHub does not include submodules for some reason.

Nevertheless, we don't pay any attention to these tarballs and don't use them.

I have found a ton of feature requests for GitHub about it:
https://github.com/dear-github/dear-github/issues/214
https://github.community/t/create-release-that-contains-submodule/1329

Also I don't know how to remove the links to these tarballs. (If I know, I will remove them).
And also it should be possible to publish custom source code tarball on GitHub Releases page.

**Comment by filimonov** [comment]
> And also it should be possible to publish custom source code tarball on GitHub Releases page

That is a nice practice and requirement for reproducable builds.
