### ISSUE TITLE
unexpected behaviour with data filtering

### ISSUE THREAD

**Issue by zav379** [ClickHouse/ClickHouse#22754]
i have table with field  i_action
& i have different results in queries:

ClickHouse client version 20.9.2.20 (official build).
ClickHouse server version 20.9.2 revision 54439.

query:
select i_action, count(*) as kol
from coem.events_month
group by i_action

Results:
DownloadComplete	44669
DownloadFail	2913
DownloadStart	47683

select i_action, count(*) as kol
from coem.events_month
where  i_action='DownloadStart'
group by i_action

Results:
DownloadStart	47677

filtr does not work correctly

**Comment by den-crane** [comment]
Check result of
```
select i_action, count(*) as kol
from coem.events_month
where identity(i_action)='DownloadStart'
group by i_action
```

Can you share `show create table  coem.events_month` ?

**Comment by zav379** [comment]
CREATE TABLE coem.events_month
(
    `hash_ud` UInt64,
    `i_device` UInt64,
    `i_platform` String,
    `i_user_guid` UInt64,
    `i_os_version` String,
    `i_time` DateTime,
    `i_time_zone` Int8,
    `i_insert_date` DateTime,
    `i_patch_group_id` String,
    `i_id` UInt32,
    `i_fb_id` UInt64,
    `i_event_guid` String,
    `i_data` String TTL dump_date + toIntervalYear(10),
    `i_version` String,
    `i_action` String,
    `dump_date` Date,
    `platform` String,
    ...fields...
)
ENGINE = MergeTree
PARTITION BY (platform, toYYYYMM(dump_date))
ORDER BY (toDate(i_time), i_action, i_version, i_user_guid)
SAMPLE BY i_user_guid
SETTINGS index_granularity = 8192

**Comment by den-crane** [comment]
What about the result with ` identity(i_action)`?

```
Check result of

select i_action, count(*) as kol
from coem.events_month
where identity(i_action)='DownloadStart'
group by i_action

``

**Comment by zav379** [comment]
with  identity it's ok
result:
DownloadStart	47683
what's reason?

**Comment by den-crane** [comment]
Upgrade at least to 20.9.7.11

**Comment by zav379** [comment]
thanks
