### ISSUE TITLE
Startup does not use all available compute power

### ISSUE THREAD

**Issue by bobrik** [ClickHouse/ClickHouse#2278]
This is a typical picture in htop of a starting ClickHouse:

![image](https://user-images.githubusercontent.com/89186/39209315-5f7aa652-47ba-11e8-9a0a-fc5b91efb225.png)

One or two CPUs are saturated, but the rest sits idle. We 48T of data across ~240 tables on this machine and it takes ~18 minutes until ClickHouse is able to accept connections. We see around 35GB RSS at that point.

Not all stages are that bad, we also see this:

![image](https://user-images.githubusercontent.com/89186/39209622-1bf71d38-47bb-11e8-8d41-cd17d9f670c8.png)

But it doesn't go anywhere near saturating either disks or CPU.

It feels like there's a room for more aggressive parallel startup.

**Comment by silviucpp** [comment]
I created around 6k tables with one row in each table and seems is taking 5 minutes to start. From my tests clickhouse performances is degrading directly proportional to the increase in the number of tables.

The following changes: https://github.com/yandex/ClickHouse/pull/1722 helps a bit but not enough, still more work to be done. Once a zookeper session expires or there is a spike in zookeper seems everything blows when you have lot of tables.

**Comment by alexey-milovidov** [comment]
Server startup time is proportional to the number of files and data parts.
Time is spent in `stat` syscalls to obtain file size on disk (This is needed to perform repair after hard reset.)

It is IO bound, but when single thread is used to load tables, it is bounded by sum latency and disk is not utilized by 100%.

To load tables, we use multiple threads up to number of physical CPU cores. Loading process is parallelized (1) by databases and (2) by tables inside a database.

But it was indended for use cases when we have very large number (~100 000) of tiny tables, and it is not parallelized when the number of tables less than few hundreds. I will fix it to allow parallelize even for medium number of tables.

**Comment by alexey-milovidov** [comment]
After this change, it still can be parallelized not by 100% if the number of files in tables are non-uniform (for example, if there is one table with huge number of data parts and/or columns).

**Comment by bobrik** [comment]
We were definitely not seeing IO utilization reach anywhere near 100%.

It should be possible to give you a timeline with CPU% and IO%, with `open()` and `stat()` from our cluster. Would that help?

cc @dqminh

**Comment by alexey-milovidov** [comment]
Now it loads in 54 seconds with flushed page cache
and in 4 seconds with page cache
on a server with 8 SATA HDD in RAID-5 and 16 core CPU,
with 151 tables (96 of them are from MergeTree family) 
and 466033 files in ClickHouse data directory,
4040 data parts and 9577 columns.

**Comment by alexey-milovidov** [comment]
> It should be possible to give you a timeline with CPU% and IO%, with open() and stat() from our cluster. Would that help?

This is not needed, because the changes that I am working on right now are not committed to master.

**Comment by alexey-milovidov** [comment]
TODO:
- it is possible to load data parts in parallel for a single table;

**Comment by alexey-milovidov** [comment]
Now data parts are loaded in parallel.

**Comment by winter7** [comment]
> Now data parts are loaded in parallel.

can you tell me which version starts to support parallel loading?

**Comment by alexey-milovidov** [comment]
19.14

https://github.com/ClickHouse/ClickHouse/blob/master/CHANGELOG.md#clickhouse-release-191433-2019-09-10
> Allow to use multiple threads during parts loading and removal.

**Comment by filimonov** [comment]
PRs
https://github.com/ClickHouse/ClickHouse/issues/6074
https://github.com/ClickHouse/ClickHouse/pull/6438

Setting `max_part_loading_threads`

**Comment by winter7** [comment]
do you have any recommanded number about `max_part_loading_threads` in `merge_tree`? @filimonov

**Comment by alexey-milovidov** [comment]
@winter7 Default value (autodetect) should be ok for all use cases.

**Comment by winter7** [comment]
@alexey-milovidov I don't think I can find default value in `config.xml` `<merge_tree>` nor `system.settings`. Is it related with version?

**Comment by den-crane** [comment]
@winter7 The default value max_part_loading_threads = auto (=== cpu cores) 
https://github.com/ClickHouse/ClickHouse/issues/10087#issuecomment-610966025
