### ISSUE TITLE
Use clickhouse with Dart

### ISSUE THREAD

**Issue by andrelec1** [ClickHouse/ClickHouse#22806]
I have a plan to use a clickhouse dbm with DART ( https://dart.dev/ ) 

I didn't find any "official' driver... 

do you know a lib that i can use ?

**Comment by alexey-milovidov** [comment]
As soon as there are no drivers for Dart, you can use ClickHouse GRPC interface.

Here is an example of the usage from Python (hope it will help):
https://github.com/ClickHouse/ClickHouse/tree/master/utils/grpc-client
