### ISSUE TITLE
Select table(with order by id) using limit offset clause return different result

### ISSUE THREAD

**Issue by hexiaoting** [ClickHouse/ClickHouse#22828]
(you don't have to strictly follow this form)

**Describe the bug**
A table with `order by id`. when select it with a large offset, the result returned is different every time.

**Does it reproduce on recent release?**
Yes

**How to reproduce**
```
create table mul_thread_offset (id Int32, name String) Engine=MergeTree order by id;
insert into mul_thread_offset select number, randomPrintableASCII(10) from numbers(100000000);

dell123 :) select id from mul_thread_offset limit 1300000, 1

┌───────id─┐
│ 91869140 │
└──────────┘

dell123 :) select id from mul_thread_offset limit 1300000, 1　;

┌───────id─┐
│ 33739762 │
└──────────┘

dell123 :) select id from mul_thread_offset limit 1300000, 1　;
┌──────id─┐
│ 3684368 │
└─────────┘
```
* Which ClickHouse server version to use
`21.5.1.1`

* Non-default settings, if any
max_threads=20

**Expected behavior**
` select id from mul_thread_offset limit 1300000, 1` return the same result every time, because table has `order by id`.

**Additional message**
If I set max_threads=1, then the result is correct. It seems that when merge all the result from multi threads, we do not reorder by id.

**Comment by ucasFL** [comment]
It's not a bug, because the order of returning blocks is uncentain.  Only if with `order by id` in sql, it will always return same result.

**Comment by hexiaoting** [comment]
So create table with `order by id` is only used for storage , for index, right?
