### ISSUE TITLE
Why insert into by ORC input formats cost too much memory in clickhouse-server?

### ISSUE THREAD

**Issue by godliness** [ClickHouse/ClickHouse#22831]
Use clickhouse-jdbc(0.3.0) to read an ORC file and insert it into clickhouse(version 21.3.2.5)table.

sql&code:
```
sth.write()
                .sql("insert into student select **297 columns**, '20200311' from input('**297 columns**')")
                .data(createHadoopInputStream(args), ClickHouseFormat.ORC) // read orc file as input stream
                .dataCompression(ClickHouseCompression.none)
                .send();
```

ORC file size: ~300MB
ORC file rows: 9442205
ORC file columns: 297

When clickhouse-server received this request the server memory usage peak to 55GB+
And from the query_log SelectedRow and SelectedBytes are double to InsertedRows and InsertedBytes which is so wired.
### **Information from system.query_log for the insert select query**:
````
memory_usage: 53448377329
ProfileEvents as below:
'Query' 1
'InsertQuery' 1
'FileOpen' 1191
'WriteBufferFromFileDescriptorWrite' 12269
'WriteBufferFromFileDescriptorWriteBytes'  2026533857
'IOBufferAllocs' 3564
'IOBufferAllocBytes' 1250865364
'FunctionExecute' 2
'TableFunctionExecute' 1
'DiskWriteElapsedMicroseconds' 1794720
'NetworkReceiveElapsedMicroseconds'  1661417
'InsertedRows' 9442205
'InsertedBytes' 29681129929
'ZooKeeperTransactions' 3
'ZooKeeperCreate' 1
'ZooKeeperMulti' 2
'SelectedRows' 18884410
'SelectedBytes' 59078993708
'MergeTreeDataWriterRows' 9442205
'MergeTreeDataWriterUncompressedBytes' 29681129929
'MergeTreeDataWriterCompressedBytes' 2026490841
'MergeTreeDataWriterBlocks' 1
'ContextLock' 2692
'RWLockAcquiredReadLocks' 3
'RealTimeMicroseconds' 217074049
'UserTimeMicroseconds' 164903563
'SystemTimeMicroseconds' 49723245
'SoftPageFaults' 22400251
````

Question1: Why SelectedRows and SelectedBytes are double to InsertedRows and InsertedBytes?

Question2: Why ~300MB ORC file expand to 55GB in clickhouse memory? That very cost memory when we import hive data into clickhouse.

Question3: Any parameters optimize or ways could improve this situation？Cause we have too many big orc files need to be load every day.

Question4: After data imported, from Hive table (941GB orc file by zlib compression) change to clickhouse table (2120GB lz4 file), why the data size expand so much?

Our orc file has many same column values, example: 297 columns has 200 columns are null in total rows and column values has fixed 20 kinds, is this the key reason lead to memory expand?

Any response will be appreciated.

**Comment by godliness** [comment]
Seem like we had a optimize about this, but it is for regular file not stdin: https://github.com/ClickHouse/ClickHouse/pull/10580/files#diff-99d522ea02f81cbff9c5c1490075962f0f695f866e4b6b30e55373f5f66a662fR90

**Comment by godliness** [comment]
@alexey-milovidov @filimonov

Any help will be appreciated.

**Comment by filimonov** [comment]
https://github.com/ClickHouse/ClickHouse/issues/10461#issuecomment-623006030

**Comment by filimonov** [comment]
See also https://github.com/ClickHouse/ClickHouse/pull/22673
