### ISSUE TITLE
Add a setting `insert_select_null_as_default`

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#22832]
**Use case**
```
CREATE TABLE default_test (s String DEFAULT 'Hello') ENGINE = Memory;

-- works, see the `input_format_null_as_default` setting.
INSERT INTO default_test VALUES ('World'), (NULL);

-- does not work but I want it to work:
INSERT INTO default_test SELECT 'World' UNION ALL SELECT NULL;
```

**Comment by fastio** [comment]
@alexey-milovidov Please assign it to me. Thanks.

**Comment by alexey-milovidov** [comment]
@fastio It is strange, I see your message in notifications but not here.
Maybe @kssenii already started doing this task. If not and you want to do it, it's yours.

**Comment by fastio** [comment]
> @fastio It is strange, I see your message in notifications but not here.

Sorry, I deleted the message by mistake. 

> Maybe @kssenii already started doing this task. If not and you want to do it, it's yours.

Let's wait for him to finish this work. If not, I'm happy to work on it.

**Comment by kssenii** [comment]
@fastio, I haven't started yet, I was going to start today. But if you want this task, it's yours.

**Comment by fastio** [comment]
> @fastio, I haven't started yet, I was going to start today. But if you want this task, it's yours.

It's up to you to deal with it. I choose another issue :)
