### ISSUE TITLE
Clickhouse will close other ports automatically

### ISSUE THREAD

**Issue by yiguolei** [ClickHouse/ClickHouse#22842]
I am intergrating  clickhouse as a storage engine in our own DB. I bind port 8000 in thrift server. But when I call mainEntryClickHouseServer(argc, argv); to start clickhouse the 8000 port will be closed. My code is like this:

main(int argc, char* argv) {
    start_thrift();  // bind to 8000
    sleep(100);
    mainEntryClickHouseServer(argc, argv);  // start clickhouse service.
}

port 8000 is active during sleep, but will be closed after clickhouse  service is started.

Any ideas?

**Comment by alexey-milovidov** [comment]
No, we don't close ports on startup.
