### ISSUE TITLE
THP & memory consumption on aarch64

### ISSUE THREAD

**Issue by mastertheknife** [ClickHouse/ClickHouse#22841]
Hi,

**Describe the issue**
Just sharing some experience today with RAM usage and THP in its default state (enabled), and brand new empty ClickHouse.
In the documentation it says to disable THP because of performance reasons. But i think maybe its worth adding that it should be disabled because it can cause excessive RAM usage, at least on aarch64.

~P.S: It seems that the watchdog process has a typo in its name.~

**Additional context**
THP enabled:
```
[root@removed ~]# echo always > /sys/kernel/mm/transparent_hugepage/enabled 
[root@removed ~]# systemctl restart clickhouse-server
[root@removed ~]# top -b -n1 | egrep '(RES|clickhouse|clck)'
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
   8201 clickho+  20   0 2145.1m   1.2g 156.8m S   0.0  20.6   0:00.65 clickhouse-serv
   8199 clickho+  20   0 1511.8m   1.0g  40.6m S   0.0  18.6   0:00.16 clckhouse-watch
```

THP disabled \ opt-in:
```
[root@removed ~]# echo madvise > /sys/kernel/mm/transparent_hugepage/enabled 
[root@removed ~]# systemctl restart clickhouse-server
[root@removed ~]# top -b -n1 | egrep '(RES|clickhouse|clck)'
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
   8062 clickho+  20   0 2137.0m 201.4m 158.9m S   0.0   3.5   0:00.53 clickhouse-serv
   8060 clickho+  20   0 1511.8m  63.0m  42.2m S   0.0   1.1   0:00.02 clckhouse-watch
```

Version: 21.3.5.42
Distro: Oracle Linux 8.3
Kernel: 5.4.17-2102.200.13.el8uek.aarch64
Build: unofficial

**Comment by alexey-milovidov** [comment]
> P.S: It seems that the watchdog process has a typo in its name.

It's intentional.
```
setThreadName("clckhouse-watch");   /// 15 characters
```
As alternative, we can change to `clickhouse-wtch` if you like.

**Comment by alexey-milovidov** [comment]
Ok. The usage of transparent huge pages is controversial.
- on old Linux kernel it leads to significant performance drop, but only after some runtime under load;
- in newer Linux kernel user reports that it improves performance without drawbacks;
- and you have added another consideration...

Let's edit the docs.

**Comment by mastertheknife** [comment]
About THP it does have some benefits, especially on x86_64 which doesn't handle high rate of TLB flushes as efficiently as aarch64 (from a personal experience with a VOIP server application).

I believe the issue here is that it tried to use 1GB pages. If it would have been 2MB pages it would probably be more acceptable.
From what i have seen, in /proc/<pid>/smaps, its just a 1 GB page, probably used by jemalloc as the main arena.

Unfortunately i wasn't able to find a way to disable 1 GB THP, so setting to 'madvise' (opt-in) is probably a good solution.

**Comment by alexey-milovidov** [comment]
https://github.com/ClickHouse/ClickHouse/commit/133443bd144de6bec11894099871fa8ec64112c7

**Comment by timurkhisamov** [comment]
> Ok. The usage of transparent huge pages is controversial.
> 
> * on old Linux kernel it leads to significant performance drop, but only after some runtime under load;
> * in newer Linux kernel user reports that it improves performance without drawbacks;
> * and you have added another consideration...
> 
> Let's edit the docs.

@alexey-milovidov, could you tell me please "on old Linux kernel" -from which version it will be the old?
