### ISSUE TITLE
Zookeeper slow due to replica down

### ISSUE THREAD

**Issue by tobad357** [ClickHouse/ClickHouse#2284]
We had a scenario where one replica was down for many hours in a 4 way (2 shards, 2 replicas per shard) setup
During this time we noticed slowdowns in Zookeeper for other usage.
Looking through Zookeeper stats we could see what looked like that the replica that was up on it's own was generating significantly more traffic to Zookeeper than the two replicas which were in sync

This in turn caused ZK slow down.

This is not fully confirmed, but ZK was slow before we shutdown CK and then became fast again once CK was down

**Comment by tobad357** [comment]
From stat command
``` /10.230.190.171:59768[1](queued=4,recved=413813,sent=430799)```

**Comment by alexey-milovidov** [comment]
Improved in https://github.com/ClickHouse/ClickHouse/pull/2758
