### ISSUE TITLE
Can't build memcpy-bench with lld and shared libraries

### ISSUE THREAD

**Issue by Algunenano** [ClickHouse/ClickHouse#22862]
Using a clean tree with current master (dc7a2b7f8853b00ee85872d4c32b1ea421f7651f).

**Operating system**
Archlinux

**Cmake version**
cmake version 3.20.0

**Ninja version**
1.10.2

**Compiler name and version**
clang version 11.1.0 (Using ccache via PATH)
ccache version 4.2

**Full cmake and/or ninja output**

Configuration:
```
CFLAGS="-march=native -mtune=native -O3 -pipe -fno-plt -Wall -Wextra -Wno-unused-parameter -g3 -gdwarf -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer"
CXXFLAGS="-march=native -mtune=native -O3 -pipe -fno-plt -Wall -Wextra -Wno-unused-parameter -g3 -gdwarf -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer"
CC=clang
CXX=clang++
cmake -DCMAKE_C_FLAGS="${CFLAGS} -fuse-ld=lld -Wno-error" -DCMAKE_CXX_FLAGS="${CXXFLAGS} -fuse-ld=lld -Wno-error" -DWERROR=0 -DUSE_STATIC_LIBRARIES=0 -DSPLIT_SHARED_LIBRARIES=1 -DCLICKHOUSE_SPLIT_BINARY=1 ..
```

Ninja (final) call:
```
$ ninja utils/memcpy-bench/memcpy-bench
[...]
ld.lld: error: can't create dynamic relocation R_X86_64_32S against local symbol in readonly segment; recompile object files with -fPIC or pass '-Wl,-z,notext' to allow text relocations in the output
>>> defined in utils/memcpy-bench/CMakeFiles/memcpy-bench.dir/memcpy_jart.S.o
>>> referenced by memcpy_jart.S:47 (../utils/memcpy-bench/memcpy_jart.S:47)
>>>               utils/memcpy-bench/CMakeFiles/memcpy-bench.dir/memcpy_jart.S.o:(MemCpy)

ld.lld: error: can't create dynamic relocation R_X86_64_64 against local symbol in readonly segment; recompile object files with -fPIC or pass '-Wl,-z,notext' to allow text relocations in the output
>>> defined in utils/memcpy-bench/CMakeFiles/memcpy-bench.dir/memcpy_jart.S.o
>>> referenced by utils/memcpy-bench/CMakeFiles/memcpy-bench.dir/memcpy_jart.S.o:(.rodata+0x0)
```

As far as I can see, using dynamic libraries enables `CMAKE_POSITION_INDEPENDENT_CODE` so all files are built using `fPIE` but `memcpy_jart.S` contains position dependent calls so the linker can't do anything with it. I've tried adding and removing fPIC and fPIE to this directory but since the assembly code already contains these calls it doesn't make a difference.

I think there are several solutions:
* Dont' build `memcpy-bench` if `dbms` was built with position independent code.
* Regenerate `memcpy_jart.S` with -fPIC so that it doesn't contain position dependent code. I hope the resulting file would work in both situations (with and without pic).
* Generate a `memcpy_jart_pic.S` file and choose dinamically between the 2 assembly files depending on the options.

**Comment by alexey-milovidov** [comment]
The simplest is just to disable `memcpy-bench` when shared linking is used.

**Comment by alexey-milovidov** [comment]
PS. The usage of `memcpy-bench` is non-obvious, and it's very easy to drive misleading conclusions. Maybe I have to write a blog post about it, it's really complicated.
