### ISSUE TITLE
Query failed when use set index: "DB::Exception: ColumnUInt8 expected as Set index condition result"

### ISSUE THREAD

**Issue by heneyin** [ClickHouse/ClickHouse#22893]
Clickhouse version: 20.3.21
---
When I add an set  index to the MergeTree table, query with `1=1` exec failed:
在 MergeTree 表里面添加一个 set 类型的跳数索引之后，如果执行的查询包含 `1=1`，就会失败.
Query:
```
ALTER TABLE table_with_set_index ADD INDEX a_index (a) TYPE set(1000) GRANULARITY 5;
select a from table_with_set_index where 1=1 and a ='hello';
```
Exception message:
```
DB::Exception: ColumnUInt8 expected as Set index condition result..
```

**Comment by alexey-milovidov** [comment]
Upgrade to version 21.3 is recommended.

**Comment by heneyin** [comment]
> Upgrade to version 21.3 is recommended.

The current version is the latest version of 20.3,  20.3.21

**Comment by alexey-milovidov** [comment]
We no longer provide support for version 20.3.
The support period for version 20.3 was one year and it has ended.

Upgrading is the only option.
