### ISSUE TITLE
Update Sign Field in CollapsingMeregTree Engine in Clickhouse

### ISSUE THREAD

**Issue by IVRAMA** [ClickHouse/ClickHouse#22949]
Hi All, 
I am new to the **CollapsingMergeTree** Engine. 

I have a scenario where the data is ingested into a table for eg: Table named Events with fields 
Eventid (PRimary KEy), 
Updated_At (Date Field) 
Sign (sign field for engine).

The first record could be inserted into Events with values(1,'2021-04-09 09:09:15', 1) 

After Soemtime a new record is inserted with values (1,'2021-04-09 16:22:23', 1)

I would now like to change the sign as -1 for the first record but getting an error message cannot update key field (sign).

Can someone help me in this usecase where i need to keep only the latest records and previous records need to be deleted. 
Similar to **ReplacingMergeTree**. 
Clickhouse documentation tells that we cannto garuntee **_Complete Deduplication of records_** in ReplacingMergeTree Engine.

**Comment by tom-clickhouse** [comment]
Hello IVRAMA, 
You don't need to update the sign field. 
Instead, after you already had inserted 
r1: (1,'2021-04-09 09:09:15', 1), 
you now insert two new rows:
r2: (1,'2021-04-09 09:09:15', -1)
r3: (1,'2021-04-09 16:22:23', 1)

r2 cancels r1  and so both r1 and r2 get deleted.

Hope that helps, please let me know if you need more help.
