### ISSUE TITLE
toYearWeek wrong value

### ISSUE THREAD

**Issue by zvonand** [ClickHouse/ClickHouse#22948]
According to [CH docs](https://clickhouse.tech/docs/en/sql-reference/functions/date-time-functions/#toweekdatemode), `toYearWeek` mode `0` has return years range 0 - 53, but instead of returning `*year*00` for the corresponding queries, it returns `*year-1*52`:

```
SELECT toYearWeek(toDateTime64('1930-01-01 00:00:00', 0, 'UTC'))

┌─toYearWeek(toDateTime64('1930-01-01 00:00:00', 0, 'UTC'))─┐
│                                                    192952 │
└───────────────────────────────────────────────────────────┘


SELECT toYearWeek(toDateTime64('1942-01-01 00:00:00', 0, 'UTC'))

┌─toYearWeek(toDateTime64('1942-01-01 00:00:00', 0, 'UTC'))─┐
│                                                    194152 │
└───────────────────────────────────────────────────────────┘


```

**Comment by alexey-milovidov** [comment]
@Enmk nothing was done, will reassign.

**Comment by anmolarora** [comment]
I think this is happening because we're always adding `WeekModeFlag::YEAR` to the `week_mode` in case of `toYearWeek` here-
https://github.com/ClickHouse/ClickHouse/blob/master/src/Functions/CustomWeekTransforms.h#L52
