### ISSUE TITLE
Build debian packages manually without the help of `dh-*`, `dpkg-*`, `debuild`, `deb-*` tools.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#22963]
There is too much infrastructure in Debian tools.
For example, they set many build flags that require significant efforts from us to remove.
We already have portable single binary build without dependencies and we don't need debian tools at all.

To build Debian package we only need to place some files accordingly, run `tar`, `gzip` and `ar`.

**Comment by filimonov** [comment]
> To build Debian package we only need to place some files accordingly, run tar, gzip and ar.

👎 

We just need cmake / cpack.
So cmake itself will produce debs & rpms

**Comment by filimonov** [comment]
See https://gitlab.kitware.com/cmake/community/-/wikis/doc/cpack/Packaging-With-CPack

@traceon have some experience with that.

**Comment by alexey-milovidov** [comment]
If we will use CPack it will prevent switching to Bazel.

**Comment by filimonov** [comment]
> If we will use CPack it will prevent switching to Bazel.

Why? I think it's possible to use them together.

**Comment by FedericoCeratto** [comment]
Users would benefit from having Clickhouse packaged and maintained in Linux distributions.
Currently the packaging is attempted by few distributions (see https://repology.org/project/clickhouse/versions ) due the difficulty of the task.
Could you kindly consider making Clickhouse more distribution-friendly and taking feedback from package maintainers?

**Comment by filimonov** [comment]
> Users would benefit from having Clickhouse packaged and maintained in Linux distributions.

There are few issues:
1) most of the distros require dynamic linking, we prefer static (need to have a full control on the versions of dependencies, some time patches versions used because dependecy maintainers can't fix their issues fast enough)
2) high development pace - we have around one feature release in a month. And much more bug-fix releases. Following that, and keeping that pace is a huge challenge for package maintainers
3) we already provide packaging for main distros (rpm/deb/tgz). Do you have any issues with them? It's much simpler just to add one more repo for users. There is instruction in the docs for that.

**Comment by FedericoCeratto** [comment]
Replying to your question: Clickhouse is currently packaged in Debian but maintaining the package requires considerable efforts due to its build configuration and requirements. 
For many users it is very time consuming to update production databases on monthly basis and creates significant availability risks. Updating every 6 months (tracking LTS) or few years can be preferred.
Furthermore, a popular Linux distribution can guarantee that a given build of a product has been tested with a given version of kernel, libc and other libraries by a large userbase, for months or years. 
If long-term support is not possible, Debian can provide faster updates using the Debian Backports archive.
If you think cooperating with distribution can increase user adoption, here are some suggestions: https://drewdevault.com/2021/09/27/Let-distros-do-their-job.html

**Comment by alexey-milovidov** [comment]
(from @Felixoid) nFPM looks good: https://nfpm.goreleaser.com/configuration/

**Comment by Felixoid** [comment]
This is done in #33664

The only thing here is cleaning out the stuff

**Comment by alexey-milovidov** [comment]
Solved.

**Comment by alexey-milovidov** [comment]
@FedericoCeratto The main reason is that there are too many different packaging systems.
Every packaging system has it's own view of how to do something "the right way".

It is much more easy to solve the problem of packaging in one, single, not so right way - to build one binary for every Linux and to simply wrap it into .deb, .rpm and everything else.

About Linux distributions - we don't care at all, most of the server side software from OS distributions is unusable, it is always the right thing to install from the software maintainer, not from the OS maintainer.

**Comment by alexey-milovidov** [comment]
> We just need cmake / cpack.
So cmake itself will produce debs & rpms

I'm not an enthusiast of CMake. It does the job, but better to use as less features of CMake as possible.

**Comment by alexey-milovidov** [comment]
@bzed, @FedericoCeratto we have implemented this task and we don't regret it.

dh-scripts is a nightmare. It is nightmare for a reason - they accumulated a lot of complexity through history, and all this complexity is probably well-motivated.

But it is very refreshing to drop all the complexity altogether! Sometimes it is good to be ignorant and don't respect the rules.

**Comment by Felixoid** [comment]
https://github.com/jordansissel/fpm and https://github.com/goreleaser/nfpm exist for reasons. And it's definitely the way to go.

We only care about the delivery of static binaries to users. Having one system packaging all together in different formats is an order of magnitude more convenient than maintaining a fleet of build scripts.

**Comment by Felixoid** [comment]
Next time somebody will argue about upstream packages I'll post this link https://bugs.launchpad.net/ubuntu/+source/poetry/+bug/1958227

**Comment by bzed** [comment]
@Felixoid thats like looking at mysql and blaming clickhouse for using some kind of sql. The generated dependency in that package comes from the weird dependency in the metadata of the upstream source.

The version in unstable is actaully correct:

```Depends: python3-lockfile (>= 1:0.12.2), python3-cachecontrol (>= 0.12.6), python3-cachy (>= 0.3.0), python3-cleo (>= 0.8.1), python3-crashtest (>= 0.3.1), python3-dulwich, python3-html5lib (>= 0.3.1), python3-importlib-metadata | python3 (>> 3.10), python3-jsonschema (>= 3.2.0), python3-keyring (>= 22.0.1), python3-packaging, python3-pexpect (>= 4.8.0), python3-pkginfo (>= 1.7.0), python3-platformdirs (>= 2.5.2), python3-platformdirs (<< 3.0.0), python3-poetry-core (>= 1.0.7), python3-requests (>= 2.25.1), python3-requests-toolbelt (>= 0.9.1), python3-shellingham (>= 1.3.2), python3-tomlkit, python3-urllib3, python3-virtualenv (>= 20.4.0), python3:any
```

The generated dependency is enough to make the automatic tests happy as only the first alternative is beeing looked at for reproducibility reason.

You would have exactly the same issue with your fpm stuff if you would fail to specify the dependencies properly.
Distributions might have some issues, but this is clearly an upstream issue for large parts.

**Comment by bzed** [comment]
@Felixoid for a good example on how packaging a database is done properly, have a look at postgresql.

**Comment by Felixoid** [comment]
> The version in unstable is actaully correct:

The version in LTS is broken for more than half of the year. It just shows that either it's hard to fix/backport or nobody cares.

> You would have exactly the same issue with your fpm stuff if you would fail to specify the dependencies properly.

That's the point. Once the software is put to release, we are unable to fix something in a foreign distro. And no doubts, no upgrades. 

------

We are heavily dependent on custom patched 3d party dependencies and compile a big static binary. No one distro likes it and requires dynamic linking. It's a dead end.

And each package manager is a world. To learn a proper way of maintaining the simplest go package a couple of years ago I've spent months playing around salsa and git/debian.

One who knows and uses the toolsets is a hero. No doubts.

I rather prefer maintaining the repositories on https://packages.clickhouse.com

**Comment by FedericoCeratto** [comment]
There is need for upstream developers to learn how to do packaging when distribution maintainers are willing do all work.
The only thing we ask for is basic cooperation around things like having a sane build environment, documenting quirks or uncommon requirement, addressing security concerns.

(@bzed just a nitpick: Debian is volunteer-driven and Debian Developers are usually not paid by Debian itself)
