### ISSUE TITLE
About data and database manipulation, trivial operations, maintenance ops, metrics... on ClickHouse ecosystem

### ISSUE THREAD

**Issue by jonatasfreitasv** [ClickHouse/ClickHouse#2297]
Hi guys!

I would like to understand what needs you would like to have within the ClickHouse ecosystem.

Features that make sense inside an Ops UI, like the MemSQL Ops. (Http://blog.memsql.com/wp-content/uploads/2015/08/memsql-ops-new-1024.jpg)
(https://docs.memsql.com/memsql-ops/v5.8/memsql-ops-overview/)

What features make sense to you?

Functionalities related to general operations such as monitoring and metrics of tables and server, query execution and data manipulantion, etc..

Please, open Issues in this repo and post your ideas -> https://github.com/jonatasfreitasv/HouseOps

With this prefix [Features].

:+1: in this issue if HouseOps idea make sense.

Thx a lot guys!

**Comment by alexey-milovidov** [comment]
We need a UI for cluster operations with the following levels:
1. Clusters overview: the list of clusters with their nodes and some health info of the nodes.
2. Server metrics: graphs for available metrics of single server or a group of servers.
3. Logs navigation and search: display query_log, text_log with filtering capabilities.
4. Profiling and comparison of a single query or a group of queries: metrics comparison, flame graphs (see "Speedscope").
