### ISSUE TITLE
Conflicts and unexpected result of CAST in where condition

### ISSUE THREAD

**Issue by SE2AI** [ClickHouse/ClickHouse#22985]
Dear authors,

In my case, values of colomn _note_ is always **NULL**, but got unexpected query result:

query: `select record_id, note from demo where CAST(note AS DECIMAL(18,0)) is not null limit 3;`
result is:
```
┌─record_id───────┬────note──────┐
│ 2_120000_120000 │ ᴺᵁᴸᴸ          │
│ 2_120000_120001 │ ᴺᵁᴸᴸ          │
│ 2_120000_120002 │ ᴺᵁᴸᴸ          │
└─────────────────┴───────────────┘
```
I think the result should be 0 rows, but got 3? Obviously, it is different from Mysql.

And then I try to find out the value of cast by:
query: `select CAST(note AS DECIMAL(18,0)), record_id from demo where CAST(note AS DECIMAL(18,0)) is not null limit 3;`
but got: `DB::Exception: Cannot convert NULL value to non-Nullable type`

So if the convertion would fail, why it is not blocked by cast condition in advance?
and vise versa, If where-cast condition tells it is not null, why the convertion failed, it should assign certain value to results.

If it's not a bug, I think there must be some reasons for the design of this feature.

**Comment by SE2AI** [comment]
I try with Nullable type, it solves the problem

`select record_id, note from demo where CAST(note AS **Nullable**(DECIMAL(18,0))) is not null limit 3;`

**Comment by UnamedRus** [comment]
There is setting for that:

```
set cast_keep_nullable=1;
```

**Comment by SE2AI** [comment]
@UnamedRus Thanks, it's more convenient, and really a flexible way.
