### ISSUE TITLE
Memory limit may not work as expected if query has very large number of UNION ALL

### ISSUE THREAD

**Issue by gituser** [ClickHouse/ClickHouse#22980]
**Describe the bug**
I was using clickhouse `v20.5.2.7` on VM with 4GB memory without any issues on dataset approximately ~5.2 GB (total) and decided to upgrade it to the latest version which is  `v21.3.5.42`.

I'm using default configuration supplied with debian packages, only slightly adjusting default user in `users.d/default.xml` and listen port in `config.d/my.xml` all other values are default set by clickhouse.

So after upgrade I noticed lots of OOMs happening, so I've played around with the versions and noticed that the last stable version I can use is:
`v20.6.11.1`

If I update to any version after the `v20.6.11.1` clickhouse-server starts to OOM, e.g. to:  ` v20.7.2.30` 

**Does it reproduce on recent release?**
Yes

**How to reproduce**
I'm not quite sure how to reproduce the issue, most likely OOM happens due to big query I have with lots of UNIONs.

Try this on version: `v20.7.2.30` or on more recent one `v21.3.5.42`. For me reproduces on all version after the `v20.6.11.1`

The table itself is about 134M rows:

```
┌───count()─┐
│ 134659659 │
└───────────┘
```

* CREATE TABLE:
```
CREATE TABLE rates_clickhouse_prod.good_rates
(
    `event_date` Date DEFAULT toDate(event_time),
    `event_time` DateTime,
    `from` String,
    `to` String,
    `amount` String,
    `source` String
)
ENGINE = MergeTree(event_date, (event_time, event_date), 8192)
```

* Sample data for all these tables:
```
┌─event_date─┬──────────event_time─┬─from─┬─to──┬─amount───┬─source────────────────────┐
│ 2021-04-12 │ 2021-04-12 00:06:13 │ USD  │ EUR │ 0.840904 │ openexchangerates@USD/EUR │
│ 2021-04-12 │ 2021-04-12 00:12:15 │ USD  │ EUR │ 0.840904 │ openexchangerates@USD/EUR │
│ 2021-04-12 │ 2021-04-12 00:02:12 │ USD  │ EUR │ 0.840904 │ openexchangerates@USD/EUR │
│ 2021-04-12 │ 2021-04-12 00:16:13 │ USD  │ EUR │ 0.840904 │ openexchangerates@USD/EUR │
│ 2021-04-12 │ 2021-04-12 00:04:12 │ USD  │ EUR │ 0.840904 │ openexchangerates@USD/EUR │
└────────────┴─────────────────────┴──────┴─────┴──────────┴───────────────────────────┘
```

* Queries to run that lead to unexpected result
The query looks like this:

```
 SELECT `from`, `to`, `amount`, `event_time`, toUnixTimestamp(good_rates.event_time, 'Europe/London') as unix_timestamp FROM 
`good_rates` LIMIT 0 UNION ALL SELECT `from`, `to`, `amount`, `event_time`, toUnixTimestamp(good_rates.event_time, 'Europe/London') as 
unix_timestamp FROM `good_rates` WHERE `from` = 'YYY' AND `to` = 'XXX' AND `event_time` <= '2021-04-11 06:23:07' AND `event_time` >= 
'2021-04-11 06:19:07' LIMIT 1 UNION ALL SELECT `from`, `to`, `amount`, `event_time`, toUnixTimestamp(good_rates.event_time, 
'Europe/London') as unix_timestamp FROM `good_rates` WHERE `from` = 'YYY' AND `to` = 'XXX' AND `event_time` <= '2021-04-11 07:23:07' 
AND `event_time` >= '2021-04-11 07:19:07' LIMIT 1 UNION ALL SELECT `from`, `to`, `amount`, `event_time`, 
toUnixTimestamp(good_rates.event_time, 'Europe/London') as unix_timestamp FROM `good_rates` WHERE `from` = 'YYY' AND `to` = 'XXX' AND 
`event_time` <= '2021-04-11 08:23:07' AND `event_time` >= '2021-04-11 08:19:07' LIMIT 1 UNION ALL SELECT `from`, `to`, `amount`, 
`event_time`, toUnixTimestamp(good_rates.event_time, 'Europe/London') as unix_timestamp FROM `good_rates` WHERE `from` = 'YYY' AND `to` 
= 'XXX' AND `event_time` <= '2021-04-11 09:23:07' AND `event_time` >= '2021-04-11 09:19:07' LIMIT 1 UNION ALL SELECT `from`, `to`, 
`amount`, `event_time`, toUnixTimestamp(good_rates.event_time, 'Europe/London') as unix_timestamp FROM `good_rates` WHERE `from` = 
'YYY' AND `to` = 'XXX' AND `event_time` <= '2021-04-11 10:23:07' AND `event_time` >= '2021-04-11 10:19:07' LIMIT 1 UNION ALL SELECT 
`from`, `to`, `amount`, `event_time`, toUnixTimestamp(good_rates.event_time, 'Europe/London') as unix_timestamp FROM `good_rates` WHERE 
`from` = 'YYY' AND `to` = 'XXX' AND `event_time` <= '2021-04-11 11:23:07' AND `event_time` >= '2021-04-11 11:19:07' LIMIT 1 UNION ALL 
SELECT `from`, `to`, `amount`, `event_time`, toUnixTimestamp(good_rates.event_time, 'Europe/London') as unix_timestamp FROM 
`good_rates` WHERE `from` = 'YYY' AND `to` = 'XXX' AND `event_time` <= '2021-04-11 12:23:07' AND `event_time` >= '2021-04-11 12:19:07' 
LIMIT 1 UNION ALL SELECT `from`, `to`, `amount`, `event_time`, toUnixTimestamp(good_rates.event_time, 'Europe/London') as 
unix_timestamp FROM `good_rates` WHERE `from` = 'YYY' AND `to` = 'XXX' AND `event_time` <= '2021-04-11 13:23:07' AND `event_time` >= 
'2021-04-11 13:19:07' LIMIT 1 UNION ALL SELECT `from`, `to`, `amount`, `event_time`, toUnixTimestamp(good_rates.event_time, 
'Europe/London') as unix_timestamp FROM `good_rates` WHERE `from` = 'YYY' AND `to` = 'XXX' AND `event_time` <= '2021-04-11 14:23:07' 
AND `event_time` >= '2021-04-11 14:19:07' LIMIT 1 UNION ALL SELECT `from`, `to`, `amount`, `event_time`, 
toUnixTimestamp(good_rates.event_time, 'Europe/London') as unix_timestamp FROM `good_rates` WHERE `from` = 'YYY' AND `to` = 'XXX' AND 
`event_time` <= '2021-04-11 15:23:07' AND `event_time` >= '2021-04-11 15:19:07' LIMIT 1 UNION ALL SELECT `from`, `to`, `amount`, 
`event_time`, toUnixTimestamp(good_rates.event_time, 'Europe/London') as unix_timestamp FROM `good_rates` WHERE `from` = 'YYY' AND `to` 
= 'XXX' AND `event_time` <= '2021-04-11 16:23:07' AND `event_time` >= '2021-04-11 16:19:07' LIMIT 1 UNION ALL SELECT `from`, `to`, 
`amount`, `event_time`, toUnixTimestamp(good_rates.event_time, 'Europe/London') as unix_timestamp FROM `good_rates` WHERE `from` = 
'YYY' AND `to` = 'XXX' AND `event_time` <= '2021-04-11 17:23:07' AND `event_time` >= '2021-04-11 17:19:07' LIMIT 1 UNION ALL SELECT 
`from`, `to`, `amount`, `event_time`, toUnixTimestamp(good_rates.event_time, 'Europe/London') as unix_timestamp FROM `good_rates` WHERE 
`from` = 'YYY' AND `to` = 'XXX' AND `event_time` <= '2021-04-11 18:23:07' AND `event_time` >= '2021-04-11 18:19:07' LIMIT 1 UNION ALL 
SELECT `from`, `to`, `amount`, `event_time`, toUnixTimestamp(good_rates.event_time, 'Europe/London') as unix_timestamp FROM 
`good_rates` WHERE `from` = 'YYY' AND `to` = 'ZZZ' AND `event_time` <= '2021-04-11 06:23:07' AND `event_time` >= '2021-04-11 06:19:07' 
LIMIT 1 UNION ALL SELECT `from`, `to`, `amount`, `event_time`, toUnixTimestamp(good_rates.event_time, 'Europe/London') as 
unix_timestamp FROM `good_rates` WHERE `from` = 'YYY' AND `to` = 'ZZZ' AND `event_time` <= '2021-04-11 07:23:07' AND ...
```
I know it's a bad query but the thing is on `v20.6.11.1` it works fine whilst on `v20.7.2.30` and above clickhouse-server OOMs.

**Expected behavior**
clickhouse-server shouldn't OOM.

**Comment by den-crane** [comment]
Change  `<mlock_executable>false</mlock_executable>` in /etc/clickhouse-server/config.xml

**Comment by gituser** [comment]
@den-crane, just tired this, didn't help the issue is still there.

**Comment by alexey-milovidov** [comment]
Lower the value of 
```
<mark_cache_size>5368709120</mark_cache_size>
```
to `1000000000`

**Comment by alexey-milovidov** [comment]
Also try to lower the value of `max_threads` setting.

**Comment by gituser** [comment]
@alexey-milovidov, I don't think this setting has anything to do with the issue, as the issue is reproduce-able only on versions after `v20.6.11.1` and in both `v20.6.11.1` and `v20.7.2.30` this setting has same value.

Even if I increase to 8GB memory clickhouse still OOMs on the newer version after `v20.6.11.1`, so I don't think the issue is that I have 4GB memory in a VM.

**Comment by alexey-milovidov** [comment]
It may be related due to more efficient (more parallel) processing of queries with multiple UNION ALL.
Does lowering the number of threads helps?

**Comment by alexey-milovidov** [comment]
If you will share the dataset (maybe obfuscated) we will be able to investigate the memory usage.

**Comment by gituser** [comment]
@alexey-milovidov 

how do I obfuscate the dataset?

**Comment by gituser** [comment]
> Also try to lower the value of `max_threads` setting.

did you mean `<max_thread_pool_size>10000</max_thread_pool_size>` this setting, because I don't see `max_threads` in config.xml.

**Comment by alexey-milovidov** [comment]
`SELECT * FROM system.settings WHERE name = 'max_threads'`
\- to show the current value of `max_threads`

`SET max_threads = ...`
\- to set it to a new value for session before executing the query.

`users.xml`, put it into profiles/default to change the default.

**Comment by gituser** [comment]
@alexey-milovidov 

Setting `max_threads = 1` for default profile settings seems to prevent OOM on  `v20.7.2.30` (although there is much higher mem usage still comparing to `v20.6.11.1` 20% vs 50% of all available memory and it grows if I hit the page with that query multiple times), but what this option is actually doing?

And why on `v20.6.11.1` it works just fine with the default (auto = 6) and in case of version `v20.7.2.30` clickhouse-server OOMs if you don't set it?

It seems to me there is a memory leak somewhere after  `v20.6.11.1`.

**Comment by alexey-milovidov** [comment]
There are no known memory leaks in ClickHouse.

Also the query is quite simple, it contains just the following components with UNION ALL:
```
SELECT
    from,
    to,
    amount,
    event_time,
    toUnixTimestamp(good_rates.event_time, 'Europe/London') AS unix_timestamp
FROM good_rates
WHERE (from = 'YYY') AND (to = 'XXX') AND (event_time <= '2021-04-11 06:23:07') AND (event_time >= '2021-04-11 06:19:07')
LIMIT 1
```

These types of queries cannot have memory leaks.

**Comment by alexey-milovidov** [comment]
How many `UNION ALL` do you have in your query?

**Comment by gituser** [comment]
@alexey-milovidov query contains quite a lot of `UNION ALL`

clickhouse profiler is not showing me full query, it truncates it for some reason (showing with `...` at the end), any idea how to get the full query in `system.query_log` ?

**Comment by alexey-milovidov** [comment]
`SET log_queries_cut_to_length = 1000000000`

**Comment by gituser** [comment]
@alexey-milovidov 

> `SET log_queries_cut_to_length = 1000000000`


Thanks, I've set it, but I still get truncated query in the `query_log` for some reason.

I've tried to set it for my user as well this way:
`alter user <username> settings log_queries_cut_to_length=1000000000;`

but still no luck.

**Comment by azat** [comment]
@gituser is this still relevant? can you try reproduce it with 22.3? Also maybe you can provide a reproducer? Or maybe this can be closed?

BTW it is interesting that you got OOM, while this should not be possible (if the only major memory consumer is clickhouse on that node), because since 20.4 clickhouse syncs internal memory tracker with rss (#10362)

Or maybe you've adjusted max memory usage for server to some value that the server don't have? (i.e. overcommit)

FWIW maybe 20.11 can improve memory accounting for you (it includes #16121), but note, that even after it there was some fixes, so it is better to try the most recent version.

**Comment by gituser** [comment]
@azat I didn't get back to this issue since the last comment.

I think I've decided to get back to that old version.

Need to test the newest release, I'll update my server and get back to you.

Most likely the issue was with the long query and how it was handled in newer versions of clickhouse.
