### ISSUE TITLE
Which version of clickhouse supports openldap? Which version of clickhouse supports kerberos?

### ISSUE THREAD

**Issue by mjh568412187** [ClickHouse/ClickHouse#23037]
Make sure to check documentation https://clickhouse.yandex/docs/en/ first. If the question is concise and probably has a short answer, asking it in Telegram chat https://telegram.me/clickhouse_en is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

If you still prefer GitHub issues, remove all this text and ask your question here.

Question 1: The online clickhouse version I currently use is 20.3.12.112-1.el7.x86_64
Do you support openldap? Are there relevant supporting documents?
Question 2: Clickhouse will support ldap and kerberos in the future version

**Comment by alexey-milovidov** [comment]
LDAP is supported since version 20.11 for authentication of users and since version 21.2 for mapping of user roles.
Kerberos is supported since version 21.4.

The version 20.3 that you are using is more than one year old and is not supported anymore.

**Comment by mjh568412187** [comment]
> LDAP is supported since version 20.11 for authentication of users and since version 21.2 for mapping of user roles.
> Kerberos is supported since version 21.4.
> 
> The version 20.3 that you are using is more than one year old and is not supported anymore.

First of all thanks for your reply:
Is there any relevant detailed documentation?

**Comment by alexey-milovidov** [comment]
LDAP: https://clickhouse.tech/docs/en/operations/external-authenticators/ldap/

**Comment by alexey-milovidov** [comment]
Kerberos: https://clickhouse.tech/docs/en/operations/external-authenticators/kerberos/

**Comment by mjh568412187** [comment]
> Kerberos: https://clickhouse.tech/docs/en/operations/external-authenticators/kerberos/

Thank you very much, I understand in general
Ask again
What version of clickhouse are you currently using online?
Is it useful to ldap and kerberos?
Also, can the clickhouse versions of ldap and kerberos that are currently supported be available for production? Or the test environment?

**Comment by alexey-milovidov** [comment]
The version 21.4 with Kerberos support was released yesterday. It is ready for production.
You'd better to install it to your testing environment first, and only after testing for your own scenarios, deploy it on production.

At Yandex we are using multiple different versions of ClickHouse (there are more than 60 clusters inside Yandex + even more in Yandex.Cloud), mostly 21.3 and 20.8.

**Comment by mjh568412187** [comment]
> The version 21.4 with Kerberos support was released yesterday. It is ready for production.
> You'd better to install it to your testing environment first, and only after testing for your own scenarios, deploy it on production.
> 
> At Yandex we are using multiple different versions of ClickHouse (there are more than 60 clusters inside Yandex + even more in Yandex.Cloud), mostly 21.3 and 20.8.

Very happy to communicate with you for a long time
Is it useful to integrate clickhouse with ldap in a production cluster?
My email is mjh568412187@163.com, I am from China, do you use WeChat here?

**Comment by alexey-milovidov** [comment]
> Is it useful to integrate clickhouse with ldap in a production cluster?

https://altinity.com/blog/integrating-clickhouse-with-ldap-part-one
https://zhuanlan.zhihu.com/p/355554683

I do have WeChat but did not use it for over a year - most likely it's frozen.

**Comment by mjh568412187** [comment]
> > Is it useful to integrate clickhouse with ldap in a production cluster?
> 
> https://altinity.com/blog/integrating-clickhouse-with-ldap-part-one
> https://zhuanlan.zhihu.com/p/355554683
> 
> I do have WeChat but did not use it for over a year - most likely it's frozen.

The version of clickhouse in the latest yum source does not have a version of clickhouse21.3

https://packagecloud.io/Altinity/clickhouse

github： https://github.com/ClickHouse/ClickHouse/releases/tag/v21.3.7.62-stable
Do you use the rpm to install and produce?

I now want to clickhouse to integrate ldap and must go to clickhouse21.3

**Comment by alexey-milovidov** [comment]
> https://packagecloud.io/Altinity/clickhouse

packagecloud/Altinity is unofficial ClickHouse project, it may lag behind on the latest patches and stable releases.
I recommend to install as on the website https://clickhouse.tech/#quick-start (CentOS or RedHat tab)

**Comment by mjh568412187** [comment]
> > https://packagecloud.io/Altinity/clickhouse
> 
> packagecloud/Altinity is unofficial ClickHouse project, it may lag behind on the latest patches and stable releases.
> I recommend to install as on the website https://clickhouse.tech/#quick-start (CentOS or RedHat tab)

I installed your suggestion and installed the 21.3.7.62 version of clickhouse to integrate ldap, but the integration failed, please take a look at the following link

https://github.com/ClickHouse/ClickHouse/issues/23414

**Comment by mjh568412187** [comment]
> > https://packagecloud.io/Altinity/clickhouse
> 
> packagecloud/Altinity is unofficial ClickHouse project, it may lag behind on the latest patches and stable releases.
> I recommend to install as on the website https://clickhouse.tech/#quick-start (CentOS or RedHat tab)

I need your help   https://github.com/ClickHouse/ClickHouse/issues/23414
