### ISSUE TITLE
"Net Exception: Socket is not connected" after upgrade CH from 19.11.11.57 to 21.3.4.25

### ISSUE THREAD

**Issue by sinmaker** [ClickHouse/ClickHouse#23059]
After upgrading clickhouse, I see in the error log many messages like blow.
I run clickhouse on Ubuntu 18.04.
It seems to be functioning ok. 
Should I be worried? What's the root cause?

`2021.04.13 09:31:08.897973 [ 20117 ] {} <Error> ServerErrorHandler: Poco::Exception. Code: 1000, e.code() = 107, e.displayText() = Net Exception: Socket is not connected, Stack trace (when copying this message, always include the lines below):

0. Poco::Net::SocketImpl::error(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x11f7dc4e in /usr/bin/clickhouse
1. Poco::Net::SocketImpl::peerAddress() @ 0x11f7fec6 in /usr/bin/clickhouse
2. DB::HTTPServerRequest::HTTPServerRequest(DB::Context const&, DB::HTTPServerResponse&, Poco::Net::HTTPServerSession&) @ 0xf8db914 in /usr/bin/clickhouse
3. DB::HTTPServerConnection::run() @ 0xf8da784 in /usr/bin/clickhouse
4. Poco::Net::TCPServerConnection::start() @ 0x11f84caf in /usr/bin/clickhouse
5. Poco::Net::TCPServerDispatcher::run() @ 0x11f866c1 in /usr/bin/clickhouse
6. Poco::PooledThread::run() @ 0x120bcde9 in /usr/bin/clickhouse
7. Poco::ThreadImpl::runnableEntry(void*) @ 0x120b8c4a in /usr/bin/clickhouse
8. start_thread @ 0x76db in /lib/x86_64-linux-gnu/libpthread-2.27.so
9. __clone @ 0x12171f in /lib/x86_64-linux-gnu/libc-2.27.so
 (version 21.3.4.25 (official build))`

**Comment by millin** [comment]
The same issue with 21.3.6.55

**Comment by alexey-milovidov** [comment]
@sinmaker No, you should not be worried about this exception message.
It happens when a client connects to ClickHouse and closes connection immediately.

It may possibly indicate some minor issues with your infrastructure, but it is not an issue of ClickHouse itself.

**Comment by filimonov** [comment]
Then log spamming is the issue https://github.com/ClickHouse/ClickHouse/issues/10935#issuecomment-797360292

**Comment by abyss7** [comment]
I.e. I've encountered the same situation recently when client specified an unknown setting.

**Comment by andvary** [comment]
I encountered this message because of a bug in my HTTP client (in go you must read the entire response body in order to persist connections, otherwise your client sets "RST" flag, the connection drops and has to be re-established every time a new request is being made). So I'm actually grateful to the ClickHouse developers for this useful warning.

**Comment by liubo-it** [comment]
me too
