### ISSUE TITLE
Вопрос по работе windowFunnel в режиме mode='strict'|'strict_order'

### ISSUE THREAD

**Issue by cadet354** [ClickHouse/ClickHouse#23057]
Здравствуйте,
вопрос по работе windowFunnel в режиме mode='strict'|'strict_order'.
У меня по тестам получается, что если встречается повторно **промежуточный** шаг, то подсчет воронки останавливается.
Например ищем воронку Start->Anketa->Finish

Есть следующая последовательность
Start->Anketa->Product->Start->Anketa->Finish вернет 2 (хотя воронка сформировалась в конце, и должно быть 3)
при этом
Start->Anketa->Product->Start->Finish вернет 3 ( убрал Anketa второй раз)

Не понятна логика, почему и зачем такое поведение?
Без указания mode отрабатывает корректно.

Версия clickhouse: 21.3.5.42
Код для воспроизведения:
````
CREATE TABLE IF NOT EXISTS trace_manual
(
	IP String,
	Time DateTime,
	Event String
)
ENGINE = MergeTree PARTITION BY toYYYYMMDD(Time)
ORDER BY (IP, Time)
SETTINGS index_granularity = 8192;

INSERT INTO trace_manual(IP, Time, Event)
VALUES ('127.0.0.1', '2021-01-01', 'Start');

INSERT INTO trace_manual(IP, Time, Event)
VALUES ('127.0.0.1', '2021-01-01 02:00:00', 'Anketa');

INSERT INTO trace_manual(IP, Time, Event)
VALUES ('127.0.0.1', '2021-01-01 04:30:00', 'Product');

INSERT INTO trace_manual(IP, Time, Event)
VALUES ('127.0.0.1', '2021-01-01 04:40:00', 'Start');

--если эту вставку убрать, то вернет 3
INSERT INTO trace_manual(IP, Time, Event)
VALUES ('127.0.0.1', '2021-01-01 04:40:00', 'Anketa');

INSERT INTO trace_manual(IP, Time, Event)
VALUES ('127.0.0.1', '2021-01-01 05:00:00', 'Finish');

select IP, windowFunnel(6048000000000000, 'strict' )(Time, Event = 'Start', Event = 'Anketa', Event = 'Finish') as level
from devim.trace_manual
group by IP; --result=2
```

**Comment by akuzm** [comment]
@vdimir might know

**Comment by vdimir** [comment]
Поведение режимов действительно довольно специальное, кроме того, они могу использоваться совместно.

В режиме `strict` цепочка считается начиная с первого вхождения первого события в цепочке (`Start`) и прерывается любым не ожидаемым событием из цепочки (второе вхождение `Anketa` в примере). События, которых нет в искомой цепочке, игнорируются (`Product` в примере). Особым образом рассматривается первое событие, его повторные вхождения игнорируются в режиме `strict` (возможно, это баг и стоит исправить такое поведение).

Режим `strict_order` позволяет учитывать события, которые не перечислены в цепочке, процесс поиска останавливается, если они встречаются.

Попробуем обновить документацию, правильно и более подробно описать работу данных режимов.

Также можете посмотреть комментарий в PR, где эти опции были добавлены:
https://github.com/ClickHouse/ClickHouse/pull/6548
https://github.com/ClickHouse/ClickHouse/pull/9773

Если вам подходит поведение без включения режимов, нужно найти цепочку как подпоследовательность, то рекомендуется так и использовать `windowFunnel` без дополнительных параметров.

**Comment by cadet354** [comment]
Спасибо за ответ,
я посмотрел комментарии, но там нигде не встречается мой случай, в моем случае всегда есть нужная цепочка (последние 3 шага), но алгоритм прохода раньше просто прерывается и не пытается дальнейшую реализацию.

По подсчету в просто windowFunnel тоже есть вопрос, т.к. число промежуточных шагов получаются не по убывающей последовательности,  на наших тестовых данных

count       level
863427    ;0 <-- первый
96238      ;1
681690    ;2
878383    ;3 <-- последний шаг
при этом решение основанное на подсчете через массивы 
```
select
       sum(step1_time>'1970-01-01 00:00:00') as start, --1 656 311
       sum(step2_time>'1970-01-01 00:00:00') as anketa, --1 560 073
       sum(step3_time>'1970-01-01 00:00:00') as finish --878 383
from (
    select groupArray(Event) as events,
           groupArray(Time) as times,
           arrayFilter(time, name -> (name = 'Start'), times, events)[1] as step1_time,
           arrayFilter(time, name -> (name = 'Anketa') and (time > step1_time) and (step1_time > '1970-01-01 00:00:00'), times, events)[1] as step2_time,
           arrayFilter(time, name -> (name = 'Finish') and (time > step2_time) and (step2_time > '1970-01-01 00:00:00'), times, events)[1] as step3_time
    from (select Event, Time, IP from trace where Event in ('Start', 'Anketa', 'Finish') order by Time)
    group by IP);
```
дает корректные результаты по убывающей, но хоть финальные результаты совпадают,
постараюсь локализировать и прислать пример.
