### ISSUE TITLE
dictGetOrNull: missing feature from release v21.4.3.21-stable

### ISSUE THREAD

**Issue by kozlek** [ClickHouse/ClickHouse#23054]
Hello 🙂
After reading the v21.4 changelog, my team and I decided to upgrade to v21.4.3.21-stable using the official APT repository to enjoy the new `dictGetOrNull` function.
However, the function is absent from the release, despite being advertised on the changelog. Same using the official Docker image 😕 
Shouldn't we remove it from the changelog ?
Keep up the good work 👏

**Comment by alexey-milovidov** [comment]
Yes, the feature should be present in 21.4 but it does not. We are checking our release scripts for possible errors.

Don't worry, we will ship this feature as advertised :)

**Comment by alexey-milovidov** [comment]
We have found an issue in our release script.

The corrections are made in release 21.4.4.

**Comment by kozlek** [comment]
Just updated, it's working perfectly 👌
Thanks a lot 🙏
