### ISSUE TITLE
clickhouse link mysql,mysql decimal(9,2) type, clickhouse mapped to string

### ISSUE THREAD

**Issue by melin** [ClickHouse/ClickHouse#23068]
![image](https://user-images.githubusercontent.com/1145830/114714690-eb9a9900-9d64-11eb-9243-0d804d2c19eb.png)

![image](https://user-images.githubusercontent.com/1145830/114714984-32888e80-9d65-11eb-913b-d48621493bba.png)

**Comment by alexey-milovidov** [comment]
Duplicate https://github.com/ClickHouse/ClickHouse/issues/4954
