### ISSUE TITLE
Is it the best way to create a Clickhouse table and place the columns with low cardinality on the left in order by primary key order？？

### ISSUE THREAD

**Issue by shadowDy** [ClickHouse/ClickHouse#23109]
For example, there are year, month, day, hour and time stamp in order by. The year should be on the far left and the hour should be on the far right.

**Comment by den-crane** [comment]
In the most cases it's correct. 
In some cases it's not. For example you have a multi-tenant system and you have 10 000 tenants. You need to divide tenants because all queries have `where tenant = ... `  then you put tenant_id to first position in order_by.

**Comment by filimonov** [comment]
Good ORDER BY typically contains 3 to 5 columns. 
The most important for filtering (and/or the lowest cardinal) on the left-most position. 
Later importance is getting lower, and column cardinality - higher.  

Ideally, if you can organize the data in the natural hierarchy order, for ex. `(continent, country, region, city, street)`
