### ISSUE TITLE
Supporting IN, LIKE and LIMIT in MySQL engine

### ISSUE THREAD

**Issue by kocherovf** [ClickHouse/ClickHouse#2310]
Hello.

Firstly, I want to say big thanks for your great work with the ClickHouse. It's really the best open source analytics database (maybe just the best).

As far as I understand from the official docs (from Russian version) for now MySQL engine doesn't support execution of IN, LIKE and LIMIT conditions on MySQL side. So, my question is do you plan to improve MySQL engine and especially implement passing mentioned conditions to MySQL.

Thanks in advance.

**Comment by alexey-milovidov** [comment]
Sure. We have an intent to complete it.
But for now there is no time schedule for this feature - we will try to do it "in between" of another features.

**Comment by alexey-milovidov** [comment]
IN and LIKE are implemented.

And we don't implement LIMIT becase it is applicable only in trivial cases.
