### ISSUE TITLE
clickhouse-server-19.13.3.26-2  Password required for user XXXX

### ISSUE THREAD

**Issue by zfno111** [ClickHouse/ClickHouse#23107]
we use chproxy to connet clickhouse

Our cluster is single copy and multiple shards
version 19.13.3.26-2
however  There are many errors in chproxy like 
"
ERROR: 2021/04/15 04:38:10 proxy.go:201: [ Id: 163F694DCAA486F4; User "distributed-read"(14) proxying as "default"(14) to "10.8.66.12:8123"(4); RemoteAddr: "10.8.104.237:35910"; LocalAddr: "10.8.56.10:9095"; Duration: 30028689 μs]: cannot kill query: unexpected status code returned from query "KILL QUERY WHERE query_id = '163F694DCAA486F4'" at "http://10.8.66.12:8123": 401. Response body: "Code: 194, e.displayText() = DB::Exception: Password required for user default (version 19.13.3.26 (official build))\n"; query: "select\n store_code\n ,area_code as parentOrgCode\n ,2 as parentOrgType\n ,sale_amt_rank\n ,stat_dt\n from click.sma_store_area_rank_all\n where\n sync_time GLOBAL in (SELECT MAX(sync_time) FROM click.sma_store_area_rank_all WHERE cycle_type = 0 and stat_dt = '2021-04-15' )\n and stat_dt = '2021-04-15'\n and cycle_type = 0\n\n\n\n\n\n\n\n\n\n\n\n\n and store_code in\n ( \n '803114'\n )\nFORMAT TabSeparatedWithNamesAndTypes;"
"
I am sure that our cluster has the correct password and can connect
and Most of the time, the cluster works normally
So can someone tell me what the reason is???

my chproxy config is 
"
server:
  http:
      listen_addr: ":9095"
      allowed_networks: ["192.168.0.0/8","10.8.0.0/8"]
  metrics:
      allowed_networks: ["10.8.0.0/8"]

users:
  - name: "distributed-write"
    to_cluster: "distributed-write"
    to_user: "default"

  - name: "replica-write"
    to_cluster: "replica-write"
    to_user: "default"

  - name: "distributed-read"
    to_cluster: "distributed-read"
    to_user: "default"
    max_concurrent_queries: 300
    max_execution_time: 1m

clusters:
  - name: "replica-write"
    replicas:
      - name: "replica1"
        nodes: ["10.8.56.5:8123","10.8.56.6:8123","10.8.56.8:8123","10.8.66.12:8123"]
    users:
      - name: "default"
        password: "XXXXXX"

  - name: "distributed-write"
    nodes: ["10.8.56.5:8123","10.8.56.6:8123","10.8.56.8:8123","10.8.66.12:8123"]
    users:
      - name: "default"
        password: "XXXXX"

  - name: "distributed-read"
    nodes: ["10.8.56.5:8123","10.8.56.6:8123","10.8.56.8:8123","10.8.66.12:8123"]
    users:
    - name: "default"
      password: "XXXXXX"

caches:
  - name: "shortterm"
    dir: "/data/chproxy95/cache/shortterm"
    max_size: 150Mb
    expire: 130s
"

**Comment by alexey-milovidov** [comment]
Please upgrade to version 21.4.
