### ISSUE TITLE
clickhouse large query in system.progress

### ISSUE THREAD

**Issue by trollhe** [ClickHouse/ClickHouse#23115]
hi,
 
   my exec signle sql to clickhouse,about time is 20seconds,but auto schedule exec to clickhouse,save large query progress:
```
select `user` ,address ,client_hostname ,is_cancelled ,current_database,SUBSTRING(trim(query),1,100) query1,count(*) cnt from system.processes group by `user` ,address ,client_hostname ,is_cancelled ,current_database,SUBSTRING(trim(query),1,100)  order by cnt desc ;
```

![image](https://user-images.githubusercontent.com/41068725/114857721-2d861680-9e1b-11eb-948d-bdf8348c09ef.png)

      how to Troubleshooting clickhouse?

**Comment by filimonov** [comment]
Number of concurrent inserts looks big. That can happen if you start many inserts in parallel at the same time, or you send data to clickhouse slowly, or clickhouse write data to target table slow. Or some combination of those. 

Not enough information to provide a better answer. You should provide at least information from system.query log for few such queries, and information/schema of the table you insert to, and provide information how exactly do you insert data into clickhouse
