### ISSUE TITLE
if move_factor is set to large，the data from the first volume will be mostly moved to the next volume

### ISSUE THREAD

**Issue by FoolishWall** [ClickHouse/ClickHouse#23110]
the storage.xml is as follows
```
<yandex>
  <storage_configuration>
    <disks>
      <default>
         <!--
             You can reserve some amount of free space
             on any disk (including default) by adding
             keep_free_space_bytes tag
         -->
         <keep_free_space_bytes>1024</keep_free_space_bytes>
      </default>
      <default1>
        <path>/data2/clickhouse/</path>
        <keep_free_space_bytes>1024</keep_free_space_bytes>
      </default1>
    </disks>
    <policies>
      <default> <!-- name for new storage policy -->
        <volumes>
          <default> <!-- name of volume -->
            <disk>default</disk>
          </default>
          <default1_vol>
            <disk>default1</disk>
          </default1_vol>
        </volumes>
        <move_factor>0.8</move_factor>
      </default>
    </policies>
  </storage_configuration>
</yandex>
```

before data migration，the storage space information is as follows
disk | size | used | use%
-- | -- | -- | --
/data1 | 1T | 250G | 27%
/data2 | 1T | 3.2G | 1%

after data migration，the storage space information is as follows
disk | size | used | use%
-- | -- | -- | --
/data1 | 1T | 1.9G | 1%
/data2 | 1T | 221G | 24%

**And, what is the max_data_part_size_bytes default value?**

if move_factor is set to small，the data from the first volume will be little moved to the next volume
the storage.xml is as follows
```
<yandex>
  <storage_configuration>
    <disks>
      <default>
         <!--
             You can reserve some amount of free space
             on any disk (including default) by adding
             keep_free_space_bytes tag
         -->
         <keep_free_space_bytes>1024</keep_free_space_bytes>
      </default>
      <default1>
        <path>/data2/clickhouse/</path>
        <keep_free_space_bytes>1024</keep_free_space_bytes>
      </default1>
    </disks>
    <policies>
      <default> <!-- name for new storage policy -->
        <volumes>
          <default1_vol>
            <disk>default1</disk>
          </default1_vol>
          <default> <!-- name of volume -->
            <disk>default</disk>
          </default>
        </volumes>
        <move_factor>0.2</move_factor>
      </default>
    </policies>
  </storage_configuration>
</yandex>
```

before data migration，the storage space information is as follows
disk | size | used | use%
-- | -- | -- | --
/data1 | 1T | 132M | 27%
/data2 | 1T | 214G | 1%

after data migration，the storage space information is as follows
disk | size | used | use%
-- | -- | -- | --
/data1 | 1T | 419M | 1%
/data2 | 1T | 214G | 24%

**Comment by filimonov** [comment]
`move_factor=0.8` means if there are less than 80% of free disk space on the first volume - move *the largest* part to the next volume. So i guess you have some large parts there which makes that difference. 

See also 
https://altinity.com/blog/2019/11/29/amplifying-clickhouse-capacity-with-multi-volume-storage-part-2 (section "Moving Parts Manually" and around)

**Comment by filimonov** [comment]
> And, what is the max_data_part_size_bytes default value?

Zero, which means "no limit".

**Comment by FoolishWall** [comment]
> `move_factor=0.8` means if there are less than 80% of free disk space on the first volume - move **the largest** part to the next volume. So i guess you have some large parts there which makes that difference.
> 
> See also
> https://altinity.com/blog/2019/11/29/amplifying-clickhouse-capacity-with-multi-volume-storage-part-2 (section "Moving Parts Manually" and around)

Thank you very much for your answer, while I still have some doubts. When i set 'move_factor' to 0.8, the data under the 'data1' directory mostly moved to 'data2' directory. 

disk | size | used | use%
-- | -- | -- | --
/data1 | 1T | 250G | 27%
/data2 | 1T | 3.2G | 1%


disk | size | used | use%
-- | -- | -- | --
/data1 | 1T | 1.9G | 1%
/data2 | 1T | 221G | 24%


When the data migration is complete, i set 'move_factor' to 0.2 by modifying storage.xml, but the data under the 'data2' directory moved to 'data1' directory little. So，i think the parts size is same. And i do't set 'max_data_part_size_bytes' vaule, So

**Comment by alexey-milovidov** [comment]
@filimonov Do you have a followup?

**Comment by filimonov** [comment]
> but the data under the 'data2' directory moved to 'data1' directory little.

Not clear what are you trying to archive. 

Why do you think something should be moved back? You already forced clickhouse to push the data to the next volume, it does not work in opposite direction. Move_factor only helps to free some disk space on hot volume by pushing it to cold & slow volume.
