### ISSUE TITLE
GROUP/ORDER BY Clause support using the ordinal position of the output column

### ISSUE THREAD

**Issue by melin** [ClickHouse/ClickHouse#23113]
The following queries are equivalent. They both group the output by the nationkey input column with the first query using the ordinal position of the output column and the second query using the input column name:

```sql
SELECT count(*), nationkey FROM customer GROUP BY 2;
SELECT count(*), nationkey FROM customer GROUP BY nationkey;
```

**Comment by nvartolomei** [comment]
#2592

**Comment by alexey-milovidov** [comment]
@nvartolomei This is very easy task, why don't do it?
