### ISSUE TITLE
Views with subqueries don't rewrite simple table names

### ISSUE THREAD

**Issue by tobia** [ClickHouse/ClickHouse#2312]
If you create a view with a sub-query that uses a simple table name, it is not rewritten with the database name.

So it works when the current database is the same it was created in:

    :) create database test
    :) use test
    :) create view whoami as select 1 as n
    :) create view tellme as select * from whoami
    :) create view tellme_nested as select * from (select * from whoami)
    :) select * from tellme

    ┌─n─┐
    │ 1 │
    └───┘

    :) select * from tellme_nested

    ┌─n─┐
    │ 1 │
    └───┘

But not in another database:

    :) use default
    :) select * from test.tellme

    ┌─n─┐
    │ 1 │
    └───┘

    :) select * from test.tellme_nested

    Received exception from server (version 1.1.54370):
    Code: 60. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Table default.whoami doesn't exist..

**Comment by alexey-milovidov** [comment]
Now it is failed at all when setting `enable_optimize_predicate_expression` is enabled.
@zhang2014

**Comment by filimonov** [comment]
Is it fixed now?

**Comment by alexey-milovidov** [comment]
133363e8e36b83e6ee7450a44d90b05b43dd8f62
