### ISSUE TITLE
Data processing with external tools in streaming fashion

### ISSUE THREAD

**Issue by kitaisreal** [ClickHouse/ClickHouse#23151]
(excerpt from #15065)

The user may write a program that will accept streams of serialized data to stdin (or multiple streams at several file descriptors), process the data and provide serialized result to stdout. We can allow to use these programs as table function. Table function may accept several SQL queries as arguments, prepare file descriptors, connect them with the program and pipe serialized data into them. This is similar to "map" in "mapreduce" model. It is intented for complex calculations that cannot be expressed in SQL.

There are various options how these programs can run: preinstalled programs available on server (easy part); third-party programs on blob-storage (s3, HDFS) that must be run in constrained environment (Linux namespaces, seccomp...)

**Comment by ruct** [comment]
Hi, this feature is currently in development and booked by me

**Comment by alexey-milovidov** [comment]
> There are various options how these programs can run: preinstalled programs available on server (easy part)

It has been implemented.
