### ISSUE TITLE
Inconsistent query translation with filters on _table and rand()

### ISSUE THREAD

**Issue by cw9** [ClickHouse/ClickHouse#23163]
**Describe the bug**
Sometimes the query translation behaves incorrectly and inconsistently on queries with _table and rand() in Where clause

**Does it reproduce on recent release?**
ClickHouse server version 20.12.4 revision 54442

**How to reproduce*
```
CREATE TABLE abc
(
    `f1` String,
    `f2` String
)
ENGINE = MergeTree()
ORDER BY f1
```

The query below could result in different results:
```
SELECT f2 FROM merge('default', '^abc$') PREWHERE _table = 'abc' AND f1 = 'a' AND rand()%100 < 20
```

Result 1:
```
Received exception from server (version 20.12.4):
Code: 47. DB::Exception: Received from hostname:1234. DB::Exception: Missing columns: 'f1' while processing query: 'WITH '' AS _table SELECT f2 FROM merge('default', '^abc$') PREWHERE (_table = 'abc') AND (f1 = 'a') AND ((rand() % 100) < 20)', required columns: 'f2' 'f1', source columns: 'f2'.
```
Note that there is a `WITH '' AS _table` added to the beginning of the query

Result 2:
```
Ok.

0 rows in set. Elapsed: 0.009 sec.
```

Meanwhile the following query without the rand() works consistently:
```
SELECT f2 FROM merge('default', '^abc$') PREWHERE (_table = 'abc') AND (f1 = 'a')
```

**Comment by alexey-milovidov** [comment]
I've reproduced the issue on version 20.12 and verified that it does not reproduce on master.
The issue is fixed.
