### ISSUE TITLE
TTL information in system.tables

### ISSUE THREAD

**Issue by iameugenejo** [ClickHouse/ClickHouse#23169]
**Use case**
I have a back-up script that freezes partitions that any of their parts are modified after the last backup, then uploads the parts. clickhouse is updating the `modification_time` of the parts that are being purged when their TTL expires, so the script is picking up those empty parts and overwriting them in the remote backup storage.

To prevent the script to not operate on the partitions that their TTL is expired, I am going to use the TTL information from the part's table, but there's no easy way to parse that information programmatically from what's available.

**Describe the solution you'd like**
It will be great if the TTL information is available in system.table.

For example,

```
SELECT ttl
FROM system.tables
WHERE database = 'test'
AND table = 'logs'

┌──────ttl──────┐
│         86400 │
└───────────────┘

```

**Describe alternatives you've considered**
The only way right now is to use a regex or grep to capture the information from the create table statement, and interpret the interval expression.

```
# cat metadata/test/logs.sql | grep TTL | awk '{ print $4 }'
toIntervalDay(8)
```

**Comment by alexey-milovidov** [comment]
It is unclear - what exact number do we need? TTL can be arbitrarily complex expression depending on table's columns.

**Comment by iameugenejo** [comment]
When I first needed it, I didn't realize the TTL duration could change depending on the month or the year the information is parsed.
I ended up using this query to determine the absolute threshold date/time - 
```
SELECT database, 
              name,
              extractAllGroupsHorizontal(create_table_query, 'toInterval([^(]+)[(]([0-9]+)') ttl,
              addHours(multiIf(ttl[1][1] == 'Second', subtractSeconds(now(), toUInt64(ttl[2][1])),
                                            ttl[1][1] == 'Minute', subtractMinutes(now(), toUInt64(ttl[2][1])),
                                            ttl[1][1] == 'Hour', subtractHours(now(), toUInt64(ttl[2][1])),
                                            ttl[1][1] == 'Day', subtractDays(now(), toUInt64(ttl[2][1])),
                                            ttl[1][1] == 'Week', subtractWeeks(now(), toUInt64(ttl[2][1])),
                                            ttl[1][1] == 'Month', subtractMonths(now(), toUInt64(ttl[2][1])),
                                            ttl[1][1] == 'Quarter', subtractQuarters(now(), toUInt64(ttl[2][1])),
                                            ttl[1][1] == 'Year', subtractYears(now(), toUInt64(ttl[2][1])),
                                            toDateTime('1970-01-01 00:00:00')), 1) expires_at
   FROM system.tables
 WHERE ttl != [[],[]]
 GROUP BY database, name, create_table_query
```
