### ISSUE TITLE
REPLACE TABLE replaces table even in case the insertion fails

### ISSUE THREAD

**Issue by cyberhuman** [ClickHouse/ClickHouse#23175]
**Describe the unexpected behaviour**
1. `CREATE TABLE t1 (...) ENGINE ReplicatedReplacingMergeTree(...) ...`
2. insert data into t1.
3. `CREATE TABLE t2 (...) ENGINE Join(ANY, LEFT, ...)`.
4. `REPLACE TABLE t2 ENGINE Join(ANY, LEFT, ...) AS SELECT ... FROM t1`
5. the insertion fails with `exception: Code: 241, e.displayText() = DB::Exception: Memory limit (total) exceeded: would use 704.69 GiB (attempt to allocate chunk of 132317568 bytes), maximum: 704.68 GiB: While executing CreatingSetsTransform (version 21.3.2.5)`
6. `t2` is replaced with a subset of data from `t1`.

**How to reproduce**
* Which ClickHouse server version to use
21.3.2.5

* Which interface to use, if matters
clickhouse-client

**Expected behavior**
If the query fails, the replacement should not happen.

**Comment by alexey-milovidov** [comment]
@tavplubix 

That's a good idea.
We can also make `CREATE TABLE ... AS SELECT` atomic if database is `Atomic`.
(table won't be created in case of insertion error)
