### ISSUE TITLE
Documentation for REPLACE TABLE ... SELECT does not match reality

### ISSUE THREAD

**Issue by cyberhuman** [ClickHouse/ClickHouse#23176]
**Describe the issue**
The documentation at https://clickhouse.tech/docs/en/sql-reference/statements/create/table/#replace-table-query says:
> Instead of above, you can use the following:
>
> ```
> REPLACE TABLE myOldTable SELECT * FROM myOldTable WHERE CounterID <12345;
> ```

However, when trying to use this syntax, a syntax error is reported:
```
Syntax error: failed at position 26 ('SELECT'):

REPLACE TABLE myOldTable SELECT * FROM myOldTable WHERE CounterID <12345;

Expected one of: storage definition, ENGINE, AS, UUID, OpeningRoundBracket, ON, Dot, token
```

A working syntax:
```
REPLACE TABLE myOldTable ENGINE ... AS SELECT * FROM myOldTable WHERE CounterID <12345;
```

**Comment by DanRoscigno** [comment]
closed by https://github.com/ClickHouse/ClickHouse/blob/master/docs/en/sql-reference/statements/create/table.md
