### ISSUE TITLE
Would mutations_sync=0 cause UPDATE inconsistency?

### ISSUE THREAD

**Issue by SE2AI** [ClickHouse/ClickHouse#23180]
Dear Authors,

By default, mutations_sync is set to 0, all mutations execute asynchronously.

If there are two UPDATE operations which update the same field, e.g. first set value to A and then to B in sequence.

In this case, the filed should be B finally, but will mutations_sync=0 cause B executed prior to A?

The other question is in which scope mutations_sync would take effect? In connection scope (only executions in one connection are synchronous) or db scope (executions from all clients are asynchronous)?

Thanks.

**Comment by SE2AI** [comment]
could anyone help to answer the question?

**Comment by hexiaoting** [comment]
If you run updates in sequence in the same connection, then B is the final result.
If you run `set mutations_sync = 1;`, then this will take effect on this connection.
If you run `alter .... update .... settings mutations_sync=1;` this will take effect only in this SQL.

**Comment by SE2AI** [comment]
@hexiaoting many thanks wenting,

according to your answer, it seems A will never be the final result.
so considering sequence , what is the side effects of **mutation_sync=0** for one connection (and the replicated table)?

In our scenario, we have to keep execution sequences and we use distributed table with one replication, so what's the suggestion? mutation_sync=2?

May I add your Wechat:)

**Comment by hexiaoting** [comment]
please give me your account on wechat.

**Comment by SE2AI** [comment]
@hexiaoting Z_Q_Young, thanks a lot:)

**Comment by hexiaoting** [comment]
> @hexiaoting Z_Q_Young, thanks a lot:)

Added.
