### ISSUE TITLE
no build clickhouse-odbc-bridge aarch64

### ISSUE THREAD

**Issue by roygbip** [ClickHouse/ClickHouse#23186]
There is no build clickhouse-odbc-bridge for aarch64 in ci.

How do I build it myself ?

```shell
./packager --output-dir=$HOME/clickhouse --package-type binary --compiler=clang-11-aarch64  --version=21.1.2.15  --official
```

no clickhouse-odbc-bridge output.

**Comment by alexey-milovidov** [comment]
Yes, we don't (yet) package clickhouse-odbc-bridge for AArch64.
The library `unixodbc` is configured only for x86_64, see the `contrib/unixodbc/linux_x86_64`.

To enable it for AArch64, we need to add the corresponding configuration near in `linux_aarch64`.
