### ISSUE TITLE
[aarch64] Uncaught exception in clickhouse-client

### ISSUE THREAD

**Issue by roygbip** [ClickHouse/ClickHouse#23183]
i download the ci build output binary

```shell
 wget https://clickhouse-builds.s3.yandex.net/0/9110a76d00807baf9dc368cd613512298188269b/clickhouse_special_build_check/clang-11-aarch64_relwithdebuginfo_none_bundled_unsplitted_disable_False_binary/clickhouse
```

and run command:

```shell
root@ubuntu-8658944997-7vjh6:/# ./clickhouse client -h
libc++abi: terminating with uncaught exception of type boost::wrapexcept<boost::program_options::invalid_command_line_syntax>: the required argument for option is missing
Aborted (core dumped)
root@ubuntu-8658944997-7vjh6:/# uname -a
Linux ubuntu-8658944997-7vjh6 4.19.90-17.ky10.aarch64 #1 SMP Sun Jun 28 14:27:40 CST 2020 aarch64 aarch64 aarch64 GNU/Linux
root@ubuntu-8658944997-7vjh6:/# ./clickhouse client --version
ClickHouse client version 21.5.1.6580 (official build).
```

but our old clickhouse version 20.3.18.186 runing correct:
```shell
[root@Malluma ch]# uname -a
Linux Malluma 4.19.90-17.ky10.aarch64 #1 SMP Sun Jun 28 14:27:40 CST 2020 aarch64 aarch64 aarch64 GNU/Linux
[root@Malluma ch]# ./clickhouse-aarch64-20.3.18.186 client --v
Bad arguments: option '--v' is ambiguous and matches '--version', '--version-clean', and '--vertical'
[root@Malluma ch]# ./clickhouse-aarch64-20.3.18.186 client ---version
Bad arguments: unrecognised option '---version'
[root@Malluma ch]# ./clickhouse-aarch64-20.3.18.186 client -h
Bad arguments: the required argument for option '--host' is missing
```
It seems that the new version brings new bugs?

both new and old version running under QEMU is correctly.

**Comment by alexey-milovidov** [comment]
What servers do you use to test these versions?

**Comment by alexey-milovidov** [comment]
The issue does not reproduce on Amazon Linux (AArch64, Graviton2):
```

       __|  __|_  )
       _|  (     /   Amazon Linux 2 AMI
      ___|\___|___|

https://aws.amazon.com/amazon-linux-2/
No packages needed for security; 2 packages available
Run "sudo yum update" to apply all updates.
[ec2-user@ip-172-31-25-65 ~]$ wget https://clickhouse-builds.s3.yandex.net/0/9110a76d00807baf9dc368cd613512298188269b/clickhouse_special_build_check/clang-11-aarch64_relwithdebuginfo_none_bundled_unsplitted_disable_False_binary/clickhouse
--2021-04-16 22:07:55--  https://clickhouse-builds.s3.yandex.net/0/9110a76d00807baf9dc368cd613512298188269b/clickhouse_special_build_check/clang-11-aarch64_relwithdebuginfo_none_bundled_unsplitted_disable_False_binary/clickhouse
Resolving clickhouse-builds.s3.yandex.net (clickhouse-builds.s3.yandex.net)... 93.158.134.158, 2a02:6b8::2:158
Connecting to clickhouse-builds.s3.yandex.net (clickhouse-builds.s3.yandex.net)|93.158.134.158|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2000574808 (1.9G) [application/octet-stream]
Saving to: ‘clickhouse’

100%[==========================================================================================================================================================================================================>] 2,000,574,808 12.8MB/s   in 2m 32s 

2021-04-16 22:10:29 (12.5 MB/s) - ‘clickhouse’ saved [2000574808/2000574808]

[ec2-user@ip-172-31-25-65 ~]$ chmod a+x clickhouse 
[ec2-user@ip-172-31-25-65 ~]$ ./clickhouse client -h
Bad arguments: the required argument for option '--host' is missing
[ec2-user@ip-172-31-25-65 ~]$
```

**Comment by alexey-milovidov** [comment]
Duplicate #19028.

**Comment by alexey-milovidov** [comment]
@roygbip Could you help me debugging this issue. It happens on specific cloud instance and on specific OS where I cannot obtain access. Maybe you can create a small temporary VM, temporary ssh keypair and send the address along with keypair to clickhouse-feedback@yandex-team.ru? Then we will need a few days to experiment with it...

**Comment by roygbip** [comment]
> What servers do you use to test these versions?

Huawei server (aarch64)

```shell
[root@Malluma ~]# cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c
    128  HUAWEI,Kunpeng 920

[root@Malluma ~]# dmidecode | grep "Product Name"
	Product Name: TaiShan 200 (Model 2280)
	Product Name: BC82AMDD

[root@Malluma ~]# uname -a
Linux Malluma 4.19.90-17.ky10.aarch64 #1 SMP Sun Jun 28 14:27:40 CST 2020 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by roygbip** [comment]
> The issue does not reproduce on Amazon Linux (AArch64, Graviton2):
> 
> ```
> 
>        __|  __|_  )
>        _|  (     /   Amazon Linux 2 AMI
>       ___|\___|___|
> 
> https://aws.amazon.com/amazon-linux-2/
> No packages needed for security; 2 packages available
> Run "sudo yum update" to apply all updates.
> [ec2-user@ip-172-31-25-65 ~]$ wget https://clickhouse-builds.s3.yandex.net/0/9110a76d00807baf9dc368cd613512298188269b/clickhouse_special_build_check/clang-11-aarch64_relwithdebuginfo_none_bundled_unsplitted_disable_False_binary/clickhouse
> --2021-04-16 22:07:55--  https://clickhouse-builds.s3.yandex.net/0/9110a76d00807baf9dc368cd613512298188269b/clickhouse_special_build_check/clang-11-aarch64_relwithdebuginfo_none_bundled_unsplitted_disable_False_binary/clickhouse
> Resolving clickhouse-builds.s3.yandex.net (clickhouse-builds.s3.yandex.net)... 93.158.134.158, 2a02:6b8::2:158
> Connecting to clickhouse-builds.s3.yandex.net (clickhouse-builds.s3.yandex.net)|93.158.134.158|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 2000574808 (1.9G) [application/octet-stream]
> Saving to: ‘clickhouse’
> 
> 100%[==========================================================================================================================================================================================================>] 2,000,574,808 12.8MB/s   in 2m 32s 
> 
> 2021-04-16 22:10:29 (12.5 MB/s) - ‘clickhouse’ saved [2000574808/2000574808]
> 
> [ec2-user@ip-172-31-25-65 ~]$ chmod a+x clickhouse 
> [ec2-user@ip-172-31-25-65 ~]$ ./clickhouse client -h
> Bad arguments: the required argument for option '--host' is missing
> [ec2-user@ip-172-31-25-65 ~]$
> ```

yes, no problem testing in QEMU + docker(aarch64)

**Comment by roygbip** [comment]
> @roygbip Could you help me debugging this issue? It happens on specific cloud instance and on specific OS where I cannot obtain access. Maybe you can create a small temporary VM, temporary ssh keypair and send the address along with keypair to [clickhouse-feedback@yandex-team.ru](mailto:clickhouse-feedback@yandex-team.ru)? Then we will need a few days to experiment with it...

**Comment by roygbip** [comment]
> @roygbip Could you help me debugging this issue? It happens on specific cloud instance and on specific OS where I cannot obtain access. Maybe you can create a small temporary VM, temporary ssh keypair and send the address along with keypair to [clickhouse-feedback@yandex-team.ru](mailto:clickhouse-feedback@yandex-team.ru)? Then we will need a few days to experiment with it...

I'm sorry, this is not our machine, and we have a security protocol. Is there anything else I can help you with？

**Comment by alexey-milovidov** [comment]
It may be related to the contents of the shared libraries on the system.
ClickHouse depends on only one shared library - `libc` that is represented by the following files:

```
/lib/aarch64-linux-gnu/libc.so.6
/lib/aarch64-linux-gnu/libdl.so.2
/lib/aarch64-linux-gnu/libm.so.6
/lib/aarch64-linux-gnu/libpthread.so.0
/lib/aarch64-linux-gnu/librt.so.1
/lib/aarch64-linux-gnu/libnss_dns.so.2
/lib/aarch64-linux-gnu/libnss_files.so.2
/lib/aarch64-linux-gnu/libresolv.so.2
/lib/ld-linux-aarch64.so.1
```

If you send me these files from "Malluma Linux", maybe I will be able to reproduce this issue.

**Comment by alexey-milovidov** [comment]
> I'm sorry, this is not our machine, and we have a security protocol. Is there anything else I can help you with？

You can create empty VM on the same cloud service.

**Comment by roygbip** [comment]
> It may be related to the contents of the shared libraries on the system.
> ClickHouse depends on only one shared library - `libc` that is represented by the following files:
> 
> ```
> /lib/aarch64-linux-gnu/libc.so.6
> /lib/aarch64-linux-gnu/libdl.so.2
> /lib/aarch64-linux-gnu/libm.so.6
> /lib/aarch64-linux-gnu/libpthread.so.0
> /lib/aarch64-linux-gnu/librt.so.1
> /lib/aarch64-linux-gnu/libnss_dns.so.2
> /lib/aarch64-linux-gnu/libnss_files.so.2
> /lib/aarch64-linux-gnu/libresolv.so.2
> /lib/ld-linux-aarch64.so.1
> ```
> 
> If you send me these files from "Malluma Linux", maybe I will be able to reproduce this issue.

container environment in "Malluma Linux":

```shell
root@ubuntu-584d458fcc-9d758:/# ls -l /lib/ld-linux-aarch64.so.1
lrwxrwxrwx 1 root root 28 Dec 16 11:04 /lib/ld-linux-aarch64.so.1 -> aarch64-linux-gnu/ld-2.31.so
```

It seems that all libraries are at `/lib/aarch64-linux-gnu`, I've packed all the files in this directory(use: `tar -czf aarch64-linux-gnu.tar.gz /lib/aarch64-linux-gnu`).  you can download from http://pub1-bjyt.s3.360.cn/g-lib/public/aarch64-linux-gnu.tar.gz

**Comment by alexey-milovidov** [comment]
> I'm sorry, this is not our machine, and we have a security protocol. Is there anything else I can help you with？

Maybe you can create a fresh VM of the same type on the cloud?

**Comment by ElapsedSoul** [comment]
> but our old clickhouse version 20.3.18.186 runing correct:
@roygbip This version run on kylin v10 too?
I'am afraid, It's the OS's case.

**Comment by ElapsedSoul** [comment]
> @roygbip Could you help me debugging this issue? It happens on specific cloud instance and on specific OS where I cannot obtain access. Maybe you can create a small temporary VM, temporary ssh keypair and send the address along with keypair to [clickhouse-feedback@yandex-team.ru](mailto:clickhouse-feedback@yandex-team.ru)? Then we will need a few days to experiment with it...

Hi,buddy,
It seems not the machine platform case, I think it's the OS case, Maybe you could debug this by install the OS,

Kylin-Server-10-SP1-Release-Build19-20210319-aarch64.iso
https://pan.baidu.com/s/1GOLao-6WmGqUkCXf1CA6qg
提取码：1vt8
I find a download url by using pan.baidu.com.

**Comment by ElapsedSoul** [comment]
@roygbip @alexey-milovidov 

My servers cpu arch is  Phytium,
I build from x86 cross is ok for UOS but not for Kylin v10 sp1,
[my issuse](crashed on kylin os with arm #19028)
