### ISSUE TITLE
How to efficiently integrate offline + real-time data to de-compute?

### ISSUE THREAD

**Issue by lxswbr** [ClickHouse/ClickHouse#23193]
Now there is the following scenario: it is necessary to integrate the offline table and the real-time table into a full data calculation, then there is a problem, how to get the latest record of id? The current method is to use the ReplicatedReplacingMergeTree engine table, first perform offline and real-time union all initialization data, and then insert the last two hours of real-time data into the table every hour, and then execute the optimize operation on each node to trigger deduplication, so This leads to a lot of pressure on the cluster. Is there any other good way?

**Comment by tom-clickhouse** [comment]
Can there be a new record occurring for a specific id at any time? 
Or is there a fixed time window in which a new record for a specific id can occur?
