### ISSUE TITLE
Very long runtime for ignore(*) queries on S3 tables

### ISSUE THREAD

**Issue by taiwhite** [ClickHouse/ClickHouse#23199]
**Describe the bug**

`SELECT count() FROM s3 WHERE NOT ignore(*)`

This query runs in 1.7 seconds on a table containing 10,000 rows from the ontime dataset, but it takes 300+ seconds to run on tables with 20,000 or more rows from the ontime dataset.

**Does it reproduce on recent release?**
[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

* 21.2.2 revision 54447
* 21.4.1 revision 54447

**How to reproduce**
* ClickHouse server version 21.2.2 or 21.4.1
* Storage configuration:
```
<storage_configuration>
    <disks>
      <external>
        <type>s3</type>
        <endpoint>[AWS S3 endpoint]</endpoint>
        <access_key_id>[access_key_id]</access_key_id>
        <secret_access_key>[secret_access_key]</secret_access_key>
      </external>
    </disks>
    <policies>
      <external>
        <volumes>
          <external>
            <disk>external</disk>
          </external>
        </volumes>
      </external>
    </policies>
  </storage_configuration>
```
* `CREATE TABLE` statement:
```
CREATE TABLE s3 (
                  Year UInt16,
                  Quarter UInt8,
                  Month UInt8,
                  DayofMonth UInt8,
                  DayOfWeek UInt8,
                  FlightDate Date,
                  UniqueCarrier FixedString(7),
                  AirlineID Int32,
                  Carrier FixedString(2),
                  TailNum String,
                  FlightNum String,
                  OriginAirportID Int32,
                  OriginAirportSeqID Int32,
                  OriginCityMarketID Int32,
                  Origin FixedString(5),
                  OriginCityName String,
                  OriginState FixedString(2),
                  OriginStateFips String,
                  OriginStateName String,
                  OriginWac Int32,
                  DestAirportID Int32,
                  DestAirportSeqID Int32,
                  DestCityMarketID Int32,
                  Dest FixedString(5),
                  DestCityName String,
                  DestState FixedString(2),
                  DestStateFips String,
                  DestStateName String,
                  DestWac Int32,
                  CRSDepTime Int32,
                  DepTime Int32,
                  DepDelay Int32,
                  DepDelayMinutes Int32,
                  DepDel15 Int32,
                  DepartureDelayGroups String,
                  DepTimeBlk String,
                  TaxiOut Int32,
                  WheelsOff Int32,
                  WheelsOn Int32,
                  TaxiIn Int32,
                  CRSArrTime Int32,
                  ArrTime Int32,
                  ArrDelay Int32,
                  ArrDelayMinutes Int32,
                  ArrDel15 Int32,
                  ArrivalDelayGroups Int32,
                  ArrTimeBlk String,
                  Cancelled UInt8,
                  CancellationCode FixedString(1),
                  Diverted UInt8,
                  CRSElapsedTime Int32,
                  ActualElapsedTime Int32,
                  AirTime Int32,
                  Flights Int32,
                  Distance Int32,
                  DistanceGroup UInt8,
                  CarrierDelay Int32,
                  WeatherDelay Int32,
                  NASDelay Int32,
                  SecurityDelay Int32,
                  LateAircraftDelay Int32,
                  FirstDepTime String,
                  TotalAddGTime String,
                  LongestAddGTime String,
                  DivAirportLandings String,
                  DivReachedDest String,
                  DivActualElapsedTime String,
                  DivArrDelay String,
                  DivDistance String,
                  Div1Airport String,
                  Div1AirportID Int32,
                  Div1AirportSeqID Int32,
                  Div1WheelsOn String,
                  Div1TotalGTime String,
                  Div1LongestGTime String,
                  Div1WheelsOff String,
                  Div1TailNum String,
                  Div2Airport String,
                  Div2AirportID Int32,
                  Div2AirportSeqID Int32,
                  Div2WheelsOn String,
                  Div2TotalGTime String,
                  Div2LongestGTime String,
                  Div2WheelsOff String,
                  Div2TailNum String,
                  Div3Airport String,
                  Div3AirportID Int32,
                  Div3AirportSeqID Int32,
                  Div3WheelsOn String,
                  Div3TotalGTime String,
                  Div3LongestGTime String,
                  Div3WheelsOff String,
                  Div3TailNum String,
                  Div4Airport String,
                  Div4AirportID Int32,
                  Div4AirportSeqID Int32,
                  Div4WheelsOn String,
                  Div4TotalGTime String,
                  Div4LongestGTime String,
                  Div4WheelsOff String,
                  Div4TailNum String,
                  Div5Airport String,
                  Div5AirportID Int32,
                  Div5AirportSeqID Int32,
                  Div5WheelsOn String,
                  Div5TotalGTime String,
                  Div5LongestGTime String,
                  Div5WheelsOff String,
                  Div5TailNum String
                ) ENGINE = MergeTree()
                PARTITION BY Year
                ORDER BY (Carrier, FlightDate)
                SETTINGS index_granularity = 8192, storage_policy='external';
```
* Data used: ontime dataset, 20,000 rows
* Query to add data from ontime dataset:
```INSERT INTO s3 SELECT * FROM datasets.ontime LIMIT 20000```
* Queries to run that lead to unexpected result
```SELECT count() FROM s3 WHERE NOT ignore(*)```

**Expected behavior**
Runtime comparable to the runtime of this query on a dataset with only 10,000 rows.

**Comment by Jokser** [comment]
@taiwhite 
Could you please provide, how many parts / partitions are allocated for `s3` table in the case of 10k and 20k rows?
Am I right that the query with `NOT ignore(*)` technically is equal to `SELECT count(*) FROM (SELECT * from s3)` ?

**Comment by taiwhite** [comment]
@Jokser 
There is only 1 part allocated for the `s3` table in both cases. That is correct, `NOT ignore(*)` should simply evaluate to 1 for all rows.

**Comment by Jokser** [comment]
@taiwhite 
Thank you.
Could you please also attach CH logs of this benchmark execution for 20k rows?

**Comment by alexey-milovidov** [comment]
@Jokser 

> Am I right that the query with NOT ignore(*) technically is equal to SELECT count(*) FROM (SELECT * from s3) ?

No, this is wrong. The query `SELECT count(*) FROM (SELECT * from s3)` will read only one column.

**Comment by alexey-milovidov** [comment]
@Jokser 

> I think such a result for 10k rows may be caused by in-memory parts optimization.

In-memory parts are not enabled by default.

**Comment by alexey-milovidov** [comment]
But if you mean "compact parts", it might be the reason.

**Comment by taiwhite** [comment]
[bug.zip](https://github.com/ClickHouse/ClickHouse/files/6366387/bug.zip)

I ran my tests again and it seems like this is not only a problem with S3 tables, I had very long time with a local table as well. The zip file contains logs for running the query with 10k rows on local and s3 tables, and logs for running the query with 20k rows on local and s3 tables separately.

**Comment by Jokser** [comment]
@taiwhite 
Thank you for logs. I've checked it and found that for 10k rows compact part form is used, while for 20k rows - wide.
It means that we need to sequentially read O(column) files for wide case and only 1 file for compact.
That's why you see such big difference in results.
This is known issue and it can be improved using parallel reads.

@alexey-milovidov 
Could you please explain, why CH have used only 1 thread for `SELECT count() FROM s3 WHERE NOT ignore(*)` query? Can it process such queries using more threads?

**Comment by alexey-milovidov** [comment]
> Could you please explain, why CH have used only 1 thread for

Due to very low amount of records in a table (just 20 000 records is about nothing).

> Can it process such queries using more threads?

It will make the query processing time even worse. As it will do two times more requests.

**Comment by alexey-milovidov** [comment]
What do you need is requesting more than one column at once from single thread to mitigate obnoxiously high s3 latency.

**Comment by alexey-milovidov** [comment]
`MergeTreeReaderWide::readRows` - make a loop over columns to request reading more than one column at once.

**Comment by alexey-milovidov** [comment]
Wow, it's fixed! :rocket:
