### ISSUE TITLE
Precision loss when using exponential literals

### ISSUE THREAD

**Issue by hyst329** [ClickHouse/ClickHouse#2321]
Steps to reproduce (at least for build 54362):
```sql
CREATE TEMPORARY TABLE t (i Float64);
INSERT INTO t VALUES (123456789);
INSERT INTO t VALUES (1.23456789e8);
```
and then
```sql
SELECT * FROM t;
```
returns
```
123456789
123456789.00000001
```
(Note that 123456789 is an integer which can be represented exactly in 64-bit floating point type according to IEEE 754. In comparison, `123456789 == 1.23456789e8` is true in programming languages like C++, Java, and Python.)

**Comment by KochetovNicolai** [comment]
ClickHouse has fast but not very precise parser in case you insert data. It works similar to:
```
SELECT 1.23456789 * 100000000.

┌─multiply(1.23456789, 100000000.)─┐
│               123456788.99999999 │
└──────────────────────────────────┘
```

**Comment by hyst329** [comment]
@KochetovNicolai it still can be a concern, since JDBC driver (for example) uses simple `Double.toString()` ([see here](https://github.com/yandex/clickhouse-jdbc/blob/24f1a40fb85a29c5d86b8567b7dda0666163e94f/src/main/java/ru/yandex/clickhouse/ClickHousePreparedStatementImpl.java#L240)) on batch insertion, so it can lead to potential data corruption (i.e. actually equal values inserted from different sources (JDBC and non-JDBC for example) may not be treated as equal).
