### ISSUE TITLE
Huawei OBS: s3 SignatureDoesNotMatch when path has '='

### ISSUE THREAD

**Issue by Zhiqisc** [ClickHouse/ClickHouse#23283]
`CREATE TABLE default.ods_test_user
(    `mobile_number` String
)
ENGINE = S3('https://***.com/${bucket}/test/user/etl_date=*/*', '***', '***', 'CSV')`
`
<Debug> AWSClient: Make request to: https://***.com/${bucket}/test/user/etl_date=20210415/user-0.csv
<Trace> AWSClient: Receiving response...
<Debug> AWSClient: Response status: 403, Forbidden
Resolved remote host IP address: 
Request ID: 
Exception name: 
Error message: <?xml version="1.0" encoding="UTF-8" standalone="yes"?><Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><RequestId>***</RequestId><HostId>***</HostId><AWSAccessKeyId>***</AWSAccessKeyId><CanonicalRequest>GET
/${bucket}/test/user/etl_date=20210415/
`
The data can be read when there is no '=' in the path

**Comment by bun4uk** [comment]
I have a similar issue with `+` symbol. 
My object name is `s_user_name+0+0001188763.json.gz`
In the exception, I see mention of `s_user_name%200%200001188763.json.gz` which decodes as `s_user_name 0 0001188763.json.gz`. So probably `+` somehow decodes as `space`

**Comment by excitoon** [comment]
Problem here is that we use AWS C++ SDK and Poco together, but these products encode/decode URI's in different manner.

**Comment by excitoon** [comment]
@Zhiqisc which version of ClickHouse have you used?

**Comment by alexey-milovidov** [comment]
See #29511
