### ISSUE TITLE
High CPU load with high number of tables, even in idle mode

### ISSUE THREAD

**Issue by Maximus43** [ClickHouse/ClickHouse#23293]
**Describe the situation**
A lot of tables (current number 42444) in Clickhouse makes database almost non-operational, even if there are no any selects. CPU load in idle mode correlates with number of tables.

**How to reproduce**
Create a lot of tables and check CPU load.

* Which ClickHouse server version to use
* 21.3.3.14 (official build)

* Which interface to use, if matters
clickhouse-driver for Python

* Non-default settings, if any
No

* `CREATE TABLE` statements for all tables involved

```
create table test_table
(
	amnt_subunits_in_package Nullable(Float32),
	base_product_id Nullable(Int64),
	base_url String,
	category Nullable(String),
	category_id Nullable(String),
	competitor Nullable(String),
	competitor_url Nullable(String),
	dt DateTime,
	gtin Nullable(String),
	in_stock Nullable(UInt8),
	in_stock_amount Nullable(Float32),
	kamp_price Nullable(Float32),
	kamp_tom Nullable(DateTime),
	list_price Nullable(Float32),
	local_path Nullable(String),
	nobbnr Nullable(Int64),
	picture_url Nullable(String),
	price Float32,
	price_per_subunit Nullable(Float32),
	product_brand Nullable(String),
	product_description Nullable(String),
	product_details Nullable(String),
	product_id String,
	product_manufactor_sn Nullable(String),
	product_meta Nullable(String),
	product_name String,
	product_short_dsc Nullable(String),
	product_supplier_sn Nullable(String),
	store_id Int64,
	store_name Nullable(String),
	sub_level Nullable(Int64),
	subunit Nullable(String),
	unit Nullable(String),
	url String,
	veil_price Nullable(Float32)
)
engine = MergeTree;
```

* Queries to run that lead to slow performance
Even idle database (no INSERTs, no SELECTs) consumes 30-40% of CPU.

**Expected performance**
Postgres consumes 1-2% of CPU in the same scenario. I expect same or better performance.

**Additional context**
Clickhouse server is installed on KVM instance.
Here is graph of CPU load for last month:

<img width="1352" alt="image" src="https://user-images.githubusercontent.com/2333901/115204773-2734ba80-a0f9-11eb-88f5-ec4497b59305.png">

**Comment by UnamedRus** [comment]
BTW there is 
Lazy database engine, which can be used for storing a lot of Log tables.

https://clickhouse.tech/docs/en/engines/table-engines/log-family/
https://clickhouse.tech/docs/en/engines/database-engines/lazy/

**Comment by Maximus43** [comment]
@UnamedRus, thank you!
Switching to Lazy database with Log tables helped a lot! Now CPU usage is about 1-5%.

**Comment by UnamedRus** [comment]
>  Switching to Lazy database with Log tables helped a lot! Now CPU usage is about 1-5%.

Log table engine have some drawbacks, so it should be used only for unimportant temporary tables.
