### ISSUE TITLE
group by по таблице CollapsingMergeTree с модификатором FINAL требует неадекватно много памяти

### ISSUE THREAD

**Issue by yuragr76** [ClickHouse/ClickHouse#2329]
2018.05.08 16:23:21.936649 [ 59833 ] <Error> executeQuery: Code: 241, e.displayText() = DB::Exception: Memory limit (for query) exceeded: would use 18.16 GiB (attempt to allocate chunk of 1048576 bytes), maximum: 18.16 GiB, e.what() = DB:
:Exception (from [::ffff:10.176.1.126]:62082) (in query: select sum(count_opers), viol_code from checks.tr_opers final group by viol_code FORMAT TabSeparatedWithNamesAndTypes), Stack trace:

0. /usr/bin/clickhouse-server(StackTrace::StackTrace()+0x15) [0x84eb065]
1. /usr/bin/clickhouse-server(MemoryTracker::alloc(long)+0x547) [0x84e6a07]
2. /usr/bin/clickhouse-server(Allocator<false>::alloc(unsigned long, unsigned long)+0x30) [0x84cf110]
3. /usr/bin/clickhouse-server(DB::ReadBufferFromFileBase::ReadBufferFromFileBase(unsigned long, char*, unsigned long)+0x108) [0x84ff3c8]
4. /usr/bin/clickhouse-server(DB::ReadBufferFromFile::ReadBufferFromFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, int, char*, unsigned long)+0x3d) [0x84fe35d]
5. /usr/bin/clickhouse-server(DB::AggregatingBlockInputStream::TemporaryFileStream::TemporaryFileStream(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x2f) [0x7f9debf]
6. /usr/bin/clickhouse-server(DB::AggregatingBlockInputStream::readImpl()+0x515) [0x7f9e545]
7. /usr/bin/clickhouse-server(DB::IProfilingBlockInputStream::read()+0x259) [0x75f5c49]
8. /usr/bin/clickhouse-server(DB::ExpressionBlockInputStream::readImpl()+0x2d) [0x7fd534d]
9. /usr/bin/clickhouse-server(DB::IProfilingBlockInputStream::read()+0x259) [0x75f5c49]
10. /usr/bin/clickhouse-server(DB::ExpressionBlockInputStream::readImpl()+0x2d) [0x7fd534d]
11. /usr/bin/clickhouse-server(DB::IProfilingBlockInputStream::read()+0x259) [0x75f5c49]
12. /usr/bin/clickhouse-server(DB::copyData(DB::IBlockInputStream&, DB::IBlockOutputStream&, std::atomic<bool>*)+0x80) [0x760b590]
13. /usr/bin/clickhouse-server(DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, DB::Context&, std::function<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>)+0x562) [0x7d6f662]
14. /usr/bin/clickhouse-server(DB::HTTPHandler::processQuery(Poco::Net::HTTPServerRequest&, HTMLForm&, Poco::Net::HTTPServerResponse&, DB::HTTPHandler::Output&)+0x2d66) [0x2ce8686]
15. /usr/bin/clickhouse-server(DB::HTTPHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&)+0x24b) [0x2ceaa0b]
16. /usr/bin/clickhouse-server(Poco::Net::HTTPServerConnection::run()+0x331) [0x86dcb31]
17. /usr/bin/clickhouse-server(Poco::Net::TCPServerConnection::start()+0xe) [0x86d53de]
18. /usr/bin/clickhouse-server(Poco::Net::TCPServerDispatcher::run()+0x169) [0x86d57b9]
19. /usr/bin/clickhouse-server(Poco::PooledThread::run()+0x76) [0x8776976]
20. /usr/bin/clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0x37) [0x8772b87]
21. /usr/bin/clickhouse-server() [0x8dd397e]
22. /lib/x86_64-linux-gnu/libpthread.so.0(+0x76b9) [0x7f361a7a16b9]
23. /lib/x86_64-linux-gnu/libc.so.6(clone+0x6c) [0x7f3619fca41c]

Настройки в users.xml
            <max_memory_usage>19500000000</max_memory_usage>
            <max_bytes_before_external_group_by>500000000</max_bytes_before_external_group_by>
            <distributed_aggregation_memory_efficient>1</distributed_aggregation_memory_efficient>
            <max_bytes_before_external_sort>500000000</max_bytes_before_external_sort>

версия 1.1.54380

размер таблицы ~ 400 млн.

**Comment by alexey-milovidov** [comment]
How to fix:
1. Install ClickHouse version 20.10 or newer.
2. Set up `max_bytes_before_external_group_by` to the appropriate value.
