### ISSUE TITLE
Part X intersects next part Y. It is a bug.

### ISSUE THREAD

**Issue by Blackmorse** [ClickHouse/ClickHouse#23296]
**Describe the bug**
At some point of time next error appears at log. (After that this error spams the log endlessly..)

`
Apr 17 17:45:30 click-inst-1.com clickhouse-server[43]: 2021.04.17 17:45:30.287957 [ 780 ] {} <Error> db.table(d577b766-e1b9-4a33-be19-6ac5f968ad41): auto DB::StorageReplicatedMergeTree::processQueueEntry(ReplicatedMergeTreeQueue::SelectedEntryPtr)::(anonymous class)::operator()(DB::StorageReplicatedMergeTree::LogEntryPtr &) const: Code: 49, e.displayText() = DB::Exception: Part d23fba2922c1a8f3adafceb40a86c34c_45540_46193_7_46162 intersects next part d23fba2922c1a8f3adafceb40a86c34c_46190_46194_1 (state Committed). It is a bug.,
`
Table with ReplicatedMergeTree engine.

**Does it reproduce on recent release?**
Reproduces at version 21.3.5.42 

**How to reproduce**
I didn't find any specific requests around this time: only inserts and several alter deletes ( in 1-hour time range around 17:45)

**Error message and/or stacktrace**
`
Apr 17 17:45:30 click-inst-1.com clickhouse-server[43]: 2021.04.17 17:45:30.287957 [ 780 ] {} <Error> db.table (d577b766-e1b9-4a33-be19-6ac5f968ad41): auto DB::StorageReplicatedMergeTree::processQueueEntry(ReplicatedMergeTreeQueue::SelectedEntryPtr)::(anonymous class)::operator()(DB::StorageReplicatedMergeTree::LogEntryPtr &) const: Code: 49, e.displayText() = DB::Exception: Part d23fba2922c1a8f3adafceb40a86c34c_45540_46193_7_46162 intersects next part d23fba2922c1a8f3adafceb40a86c34c_46190_46194_1 (state Committed). It is a bug., Stack trace (when copying this message, always include the lines below):
Apr 17 17:45:30 click-inst-1.com clickhouse-server[43]: 0. DB::MergeTreeData::getActivePartsToReplace(DB::MergeTreePartInfo const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::IMergeTreeDataPart const>&, std::__1::unique_lock<std::__1::mutex>&) const @ 0xf5e6ed0 in /usr/bin/clickhouse
Apr 17 17:45:30 click-inst-1.com clickhouse-server[43]: 1. DB::MergeTreeData::renameTempPartAndReplace(std::__1::shared_ptr<DB::IMergeTreeDataPart>&, SimpleIncrement*, DB::MergeTreeData::Transaction*, std::__1::unique_lock<std::__1::mutex>&, std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeDataPart const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeDataPart const> > >*) @ 0xf5e8484 in /usr/bin/clickhouse
Apr 17 17:45:30 click-inst-1.com clickhouse-server[43]: 2. DB::MergeTreeData::renameTempPartAndReplace(std::__1::shared_ptr<DB::IMergeTreeDataPart>&, SimpleIncrement*, DB::MergeTreeData::Transaction*) @ 0xf5eaabd in /usr/bin/clickhouse
Apr 17 17:45:30 click-inst-1.com clickhouse-server[43]: 3. DB::MergeTreeDataMergerMutator::renameMergedTemporaryPart(std::__1::shared_ptr<DB::IMergeTreeDataPart>&, std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeDataPart const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeDataPart const> > > const&, DB::MergeTreeData::Transaction*) @ 0xf6389f2 in /usr/bin/clickhouse
Apr 17 17:45:30 click-inst-1.com clickhouse-server[43]: 4. DB::StorageReplicatedMergeTree::tryExecuteMerge(DB::ReplicatedMergeTreeLogEntry const&) @ 0xf3eb027 in /usr/bin/clickhouse
Apr 17 17:45:30 click-inst-1.com clickhouse-server[43]: 5. DB::StorageReplicatedMergeTree::executeLogEntry(DB::ReplicatedMergeTreeLogEntry&) @ 0xf3dfef2 in /usr/bin/clickhouse
Apr 17 17:45:30 click-inst-1.com clickhouse-server[43]: 6. ? @ 0xf451b7f in /usr/bin/clickhouse   Apr 17 17:45:30 click-inst-1.com clickhouse-server[43]: 7. DB::ReplicatedMergeTreeQueue::processEntry(std::__1::function<std::__1::shared_ptr<zkutil::ZooKeeper> ()>, std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&, std::__1::function<bool (std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&)>) @ 0xf787d98 in /usr/bin/clickhouse                                                                                                                       Apr 17 17:45:30click-inst-1.com clickhouse-server[43]: 8. DB::StorageReplicatedMergeTree::processQueueEntry(std::__1::shared_ptr<DB::ReplicatedMergeTreeQueue::SelectedEntry>) @ 0xf409f3d in /usr/bin/clickhouse        Apr 17 17:45:30 click-inst-1.com clickhouse-server[43]: 9. ? @ 0xf5789a7 in /usr/bin/clickhouse   Apr 17 17:45:30 click-inst-1.com clickhouse-server[43]: 10. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0x86502c8 in /usr/bin/clickhouse                       Apr 17 17:45:30 click-inst-1.com clickhouse-server[43]: 11. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()&&...)::'lambda'()::operator()() @ 0x865227f in /usr/bin/clickhouse                                                                                                                Apr 17 17:45:30 click-inst-1.com clickhouse-server[43]: 12. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x864d89f in /usr/bin/clickhouse                               Apr 17 17:45:30 click-inst-1.comu clickhouse-server[43]: 13. ? @ 0x8651333 in /usr/bin/clickhouse
Apr 17 17:45:30 click-inst-1.com clickhouse-server[43]: 14. start_thread @ 0x7dd5 in /usr/lib64/libpthread-2.17.so
Apr 17 17:45:30 click-inst-1.com clickhouse-server[43]: 15. clone @ 0xfdead in /usr/lib64/libc-2.17.so
Apr 17 17:45:30 click-inst-1.com clickhouse-server[43]: (version 21.3.5.42 (official build)) `

**Comment by tavplubix** [comment]
Could you please share output of the following query?
```
WITH
    'd23fba2922c1a8f3adafceb40a86c34c_45540_46193_7_46162' AS p1,
    'd23fba2922c1a8f3adafceb40a86c34c_46190_46194_1' AS p2
SELECT
    materialize(hostName()) AS host,
    *
FROM remote('replica1,replica2,replica3', 'system.part_log')
WHERE (database = 'db') AND (table = 'table') AND ((part_name IN (p1, p2)) OR has(merged_from, p1) OR has(merged_from, p2))
FORMAT Vertical
```
`'replica1,replica2,replica3'` is a comma-separated list of hostnames (or ip addresses) of all replicas

@gj-zhang, could you please do the same? (query is a bit different, because all replicas are on a single server, as I can suppose from your logs)
```
WITH
    '20210320_89_102_2' AS p1,
    '20210320_98_169_4' AS p2
SELECT
    *
FROM system.part_log
WHERE (database = 'mydatabase') AND (table LIKE 'mytable%') AND ((part_name IN (p1, p2)) OR has(merged_from, p1) OR has(merged_from, p2))
FORMAT Vertical
```

**Comment by Blackmorse** [comment]
I have no system.part_log turned on..
Also this problem was gone after I deattached/attached part

**Comment by tavplubix** [comment]
Hm, similar issue was reported for 20.8.2.3 (#18559) and 1.1.54394.3 ( #4833). Seems like the bug has always existed.

**Comment by crazyproger** [comment]
We meet this problem almost every day( Currently fix it by detach/attach.
We have cluster with 4 shards, 2 mirrors in each shard. All CH version 20.8.14.4.
However table on which we meet this problems is bit different: it is ReplicatedMergeTree table which is mirrored on each instance(so 8 mirrors, `{shard}` in zk path is same for all insances).
Every day our ETL system starts to insert lots of data by lots of threads on 4 of 8 CH nodes(insert select). After some time replication_queue ends with such errors on each node(however parts with problems are different on each node).

By the lifetime of our cluster we've met such problems in other tables too, but very rare(maybe 3-4 times in a year), but every day in this table.
Attached here replication queue from one server. 
Also I can upload logs from all servers to some place for CH team(sorry, can't make it public, sensitive data might be) for CH team to analyze.

[clickhouse-server-db-3_rq.log](https://github.com/ClickHouse/ClickHouse/files/6404653/clickhouse-server-db-3_rq.log)

**Comment by crazyproger** [comment]
Attached output of query:
```
WITH
    '202103_37087_37167_7' AS p1,
    '202103_37167_37350_11' AS p2
SELECT materialize(hostName()) AS host,
       *
FROM remote(
        <all_hosts>,
        'system.part_log')
WHERE (database = 'db')
  AND (table = 'table')
  AND ((part_name IN (p1, p2)) OR has(merged_from, p1) OR has(merged_from, p2))
```
(Problem parts from previous log)
[out.tar.gz](https://github.com/ClickHouse/ClickHouse/files/6404808/out.tar.gz)

and with `and event_type!='DownloadPart'` - merges only
[Result_5.csv](https://github.com/ClickHouse/ClickHouse/files/6404813/Result_5.csv)

**Comment by utkarsh2811** [comment]
Hi guys,

this issue still exists:
any idea how i can fix this issue i get in my ch pod logs? below are logs from /var/log/clickhouse-server/clickhouse-server.err.log :
```
2023.09.13 11:39:49.582729 [ 161 ] {} <Error> time_series.video_stat (ReplicatedMergeTreeRestartingThread): Failed to restart the table. Will try again: Code: 49. DB::Exception: Part 202308_0_147_3 intersects part 202308_84_231_3. It is a bug or a result of manual intervention in the ZooKeeper data. (LOGICAL_ERROR), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0xe2322d5 in /usr/bin/clickhouse
1. ? @ 0x95929fe in /usr/bin/clickhouse
2. DB::ActiveDataPartSet::add(DB::MergeTreePartInfo const&, String const&, std::vector<String, std::allocator<String>>*) @ 0x144fd96c in /usr/bin/clickhouse
3. DB::ReplicatedMergeTreeQueue::initialize(std::shared_ptr<zkutil::ZooKeeper>) @ 0x14888998 in /usr/bin/clickhouse
4. DB::ReplicatedMergeTreeRestartingThread::tryStartup() @ 0x148c8d64 in /usr/bin/clickhouse
5. DB::ReplicatedMergeTreeRestartingThread::runImpl() @ 0x148c7d82 in /usr/bin/clickhouse
6. DB::ReplicatedMergeTreeRestartingThread::run() @ 0x148c6e5a in /usr/bin/clickhouse
7. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x12890fc6 in /usr/bin/clickhouse
8. DB::BackgroundSchedulePool::threadFunction() @ 0x12893eaa in /usr/bin/clickhouse
9. ? @ 0x12894cee in /usr/bin/clickhouse
10. ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0xe301613 in /usr/bin/clickhouse
11. ? @ 0xe307281 in /usr/bin/clickhouse
12. ? @ 0x7f7a56e14609 in ?
13. __clone @ 0x7f7a56d39133 in ?
 (version 23.3.8.22.altinitystable (altinity build))
```

**Comment by tavplubix** [comment]
> version 23.3.8.22.altinitystable (altinity build)

@utkarsh2811 , you are using an alternative build that does not contain important bugfixes. It's highly not recommended. We only support official ClickHouse builds.

Also, as you can see from the error message: "It is a bug **or a result of manual intervention in the ZooKeeper data**".

And you already were reporting other issues that may indicate manual intervention in the ZooKeeper data: https://github.com/ClickHouse/ClickHouse/issues/47879

If you
 - can reproduce it with the official ClickHouse build
 - and did not manually modify data in ZooKeeper
 - and can reproduce it without third-party scripts (like clickhouse-operator) that can modify data in ZooKeeper

then please create a new issue with a bug report and provide detailed diagnostics (the list of actions that lead to the error; all logs from all replicas containing the names of the intersecting parts)
