### ISSUE TITLE
The performance diff between Map and Array

### ISSUE THREAD

**Issue by ruanwenjun** [ClickHouse/ClickHouse#23299]
Hi, I want to know the query performance between `Map` and `Array`. If I want to store multiple-value in one column, I can choose `Array` or `Map`, and use `has()` or `mapContains()` to filter the data in query. Which one will be faster, I found no obvious difference during the test.

**Comment by l1t1** [comment]
please post your test

**Comment by ruanwenjun** [comment]
```sql
CREATE TABLE test_map
(
      `itemId` Int64,
       `userId` Map[Int64,Int32],
       `ts` DateTime('America/Phoenix')
)
ENGINE = SummingMergeTree
PARTITION BY toYYYYMMDD(ts)
ORDER BY (itemId, userId, ts)
SETTINGS index_granularity = 8192;

CREATE TABLE test_array
(
      `itemId` Int64,
       `userId` Array(Int64),
       `ts` DateTime('America/Phoenix')
)
ENGINE = SummingMergeTree
PARTITION BY toYYYYMMDD(ts)
ORDER BY (itemId, userId, ts)
SETTINGS index_granularity = 8192
```

Import 1000w rows of data, and query sql is 
```sql
Select * from test_map where mapContains(userId, 123233)
Select * from test_array where has(userId, 123233)
```

**Comment by l1t1** [comment]
`userId` Map[Int64,Int32], should be `userId` Map(Int64,Int32),

and the insert sql?

**Comment by alexey-milovidov** [comment]
`Map` data type is implemented with linear array. There is no advantage in performance over `Array`.

**Comment by ruanwenjun** [comment]
> `Map` data type is implemented with linear array. There is no advantage in performance over `Array`.

Thank you.
