### ISSUE TITLE
question about execute_merges_on_single_replica_time_threshold feature 

### ISSUE THREAD

**Issue by Sallery-X** [ClickHouse/ClickHouse#23300]
Why does it happen？ when some replicas are added / removed,  execute some merges on more than one replica.

**Comment by filimonov** [comment]
clickhouse decides which replica SHOULD do the merge (and which one we should wait for) based on the number of currently active replicas.
```
replica_which_should_do_the_merges = active_replicas[ hash(part_name) % number_of_active_replicas  ] 
```

If you the number of replicas changes different replicas can decide to wait for different replicas. No strong guarantees there.

**Comment by Sallery-X** [comment]
> P.S. That is a feature for some VERY specific use cases and can make sense only if you see CPU is used heavily by merges, and network is fast / underloaded. For 'normal' usage patterns (one/few huge tables with batch inserts) we don't recommend using it.

I want to use nfs, all replicas use one  file system. So i need make sure only one replica excute merge 、mutation  and other  log entry type operation.

**Comment by filimonov** [comment]
It will not work. Other replicas do fetch instead of merge

**Comment by Sallery-X** [comment]
> It will not work. Other replicas do fetch instead of merge

I known that. And I think It works. Other replicas will fetch instead of merge, and ensure that the cache is consistent among the replicas.

**Comment by tavplubix** [comment]
> I want to use nfs, all replicas use one file system

Do you mean that you want multiple replicas to share the same data in NFS? There is no way it can work, `execute_merges_on_single_replica_time_threshold` and other settings will not help.

**Comment by Sallery-X** [comment]
> Do you mean that you want multiple replicas to share the same data in NFS? There is no way it can work, `execute_merges_on_single_replica_time_threshold` and other settings will not help.

I try to modify some code to make it work

**Comment by filimonov** [comment]
See also https://github.com/ClickHouse/ClickHouse/pull/16240
