### ISSUE TITLE
How to auto accept yes when install server

### ISSUE THREAD

**Issue by zhengyangyong** [ClickHouse/ClickHouse#23346]
Hi:
 when I am installing clickhouse-server from tgz use `install/doinst.sh`, the choice need be selected :
```
Allow server to accept connections from the network (default is localhost only), [y/N]
```
can any way make it silent installation like `install/doinst.sh -y` ?

Version : 21.1.9.41

**Comment by alexey-milovidov** [comment]
`yes | install/doinst.sh`
