### ISSUE TITLE
A "versioned" version of AggregatingMergeTree

### ISSUE THREAD

**Issue by esbenkolsbjerg** [ClickHouse/ClickHouse#23356]
We have a very specific criteria for storing data which we cannot find a very good solution for. We would like to do something like a versioned AggregatingMergeTree but it doesn't exist so is there maybe a different solution?

We have a setup that looks like this:
```
create table if not exists test.test
(
    country        LowCardinality(String),
    text           String CODEC (ZSTD(3)),
    number         SimpleAggregateFunction( max, UInt32),
    related_number Float32,
    first_seen     SimpleAggregateFunction( min, Date)
)
    engine = AggregatingMergeTree()
        PARTITION BY country
        ORDER BY (country, text)
        SETTINGS index_granularity = 256;

insert into test
values ('us', 'foo', 1, 30, '2020-01-01'),
       ('us', 'foo', 2, 20, '2021-01-02'),
       ('us', 'foo', 3, 10, '2021-01-03');
```
If we do select all data with final (`select * from test final`) we get:

| country | text | number | related_number | first_seen |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| us | foo  | 3  | 30 | 2020-01-01  |

which is what one would expect. 

But we would like "save" the `related_number` that correspond to max `number` while maintaining the lowest `first_seen` date as shown in the table below (with the _**bold italic records highligthed**_).

(`select * from test`)
| country | text | number | related_number | first_seen |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| us | foo  | 1  | 30 | **_2020-01-01_**  |
| us | foo  | 2  | 20 | 2020-01-02  |
| **_us_** | **_foo_**  | **_3_**  | **_10_** | 2020-01-03  |
| us | foo  | 1  | 30 | 2020-01-04  |

So essentially we are looking for the behavior of the combination of a ReplacingMergeTree (with `number` as the version column) and a AggregatingMergeTree -> a VersionedAggregatingMergeTree.

Any idea how we could solve this?

edit: changed the last table to better show what we want

**Comment by inakivb** [comment]
related_number SimpleAggregateFunction(anyLast,Float32) should work

**Comment by esbenkolsbjerg** [comment]
Sadly both `number` and `related_number` are not ascending or (increasing for that matter). The idea is that `related_number` fits together with `number`, hence we want them as a pair but we only wanna keep the record of the highest `number` as it is the important one. I know we can do this if we split the logic into two tables but we would prefer if it was just all in one.

**Comment by den-crane** [comment]
But you should simply use `SimpleAggregateFunction` Or `AggregateFunction` ?

What CH version do you use?


```sql
create table if not exists test
(    country        LowCardinality(String),
    text           String CODEC (ZSTD(3)),
    number         SimpleAggregateFunction( max, UInt32),
    related_number SimpleAggregateFunction(argMax, Tuple(Float32, Tuple(UInt32, Int16))),
    first_seen     SimpleAggregateFunction( min, Date)
)
    engine = AggregatingMergeTree()
        PARTITION BY country
        ORDER BY (country, text)
        SETTINGS index_granularity = 256;

create table if not exists test_ingestor
(   country        LowCardinality(String),
    text           String,
    number         UInt32,
    related_number Float32,
    first_seen     Date)
engine = Null;    

create materialized view test_ingestor_mv to test
as 
select country, text, number, (related_number,(number,-toInt16(first_seen))) as related_number, first_seen
from test_ingestor

insert into test_ingestor values ('us', 'foo', 1, 30, '2020-01-01'), ('us', 'foo', 2, 20, '2021-01-02'), ('us', 'foo', 3, 10, '2021-01-03');

select * from test final　;
┌─country─┬─text─┬─number─┬─related_number──┬─first_seen─┐
│ us      │ foo  │      3 │ (10,(3,-18630)) │ 2020-01-01 │
└─────────┴──────┴────────┴─────────────────┴────────────┘

select country, text, number, related_number.1 as related_number, first_seen from test final　;
┌─country─┬─text─┬─number─┬─related_number─┬─first_seen─┐
│ us      │ foo  │      3 │             10 │ 2020-01-01 │
└─────────┴──────┴────────┴────────────────┴────────────┘

```

**Comment by esbenkolsbjerg** [comment]
Thanks for the answer
