### ISSUE TITLE
when i edit listen_port,i can't  restart

### ISSUE THREAD

**Issue by tomuGo** [ClickHouse/ClickHouse#23354]
version:  ClickHouse server version 21.4.3 revision 54447.
system:   ubuntu18.04
![image](https://user-images.githubusercontent.com/24789356/115369340-947c4480-a1fa-11eb-9dfb-66cb803393dc.png)

![image](https://user-images.githubusercontent.com/24789356/115370089-4ddb1a00-a1fb-11eb-86b7-9749a6a4896b.png)

**Comment by tavplubix** [comment]
Is there any errors in server log?
Please, attach server log as text or link to pastebin/gist, not as image.

**Comment by alexey-milovidov** [comment]
No info provided.

**Comment by alexey-milovidov** [comment]
PS. I enjoyed the screenshots.
