### ISSUE TITLE
Lingering TTL expired parts 

### ISSUE THREAD

**Issue by iameugenejo** [ClickHouse/ClickHouse#23398]
Parts with 0 rows because of TTL expiration are not getting cleaned up.

clickhouse version: 20.8.14.4

```
SELECT DISTINCT count(partition)
FROM system.parts
WHERE (database = 'logs_5m') AND (table = '.inner.logs') AND (rows = 0)

┌─count(partition)─┐
│              113 │
└──────────────────┘
```

```
SELECT DISTINCT partition
FROM system.parts
WHERE (database = 'logs_5m') AND (table = '.inner.logs') AND (rows = 0)
ORDER BY partition ASC
LIMIT 10

┌─partition─┐
│ 20201104  │
│ 20201115  │
│ 20201221  │
│ 20201222  │
│ 20201223  │
│ 20201224  │
│ 20201225  │
│ 20201226  │
│ 20201227  │
│ 20201228  │
└───────────┘
```

The table has TTL of 8 days, and the time of queries above is 04/20/2021.

I see empty partitions as old as 5 months (the modification_time is 1 month and 3 days old)

I checked the disk and the part folders for those are still there as well with 0 bytes for `*.mrk2` and `*.bin` files.

I wonder if these parts will be eventually cleaned up, or if I need to clean them up manually with some commands.

**Comment by den-crane** [comment]
This feature has been implemented in 
ClickHouse release v20.12.3.3-stable, 2020-12-13 
Remove empty parts after they were pruned by TTL, mutation, or collapsing merge algorithm. #16895 (Anton Popov).
