### ISSUE TITLE
Clickhouse version 21.3.7.62 failed to integrate ldap

### ISSUE THREAD

**Issue by mjh568412187** [ClickHouse/ClickHouse#23414]
Make sure to check documentation https://clickhouse.yandex/docs/en/ first. If the question is concise and probably has a short answer, asking it in Telegram chat https://telegram.me/clickhouse_en is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

If you still prefer GitHub issues, remove all this text and ask your question here.

----
Clickhouse version 21.3.7.62 failed to integrate ldap

hello
The link I refer to is as follows:
https://bbs.huaweicloud.com/blogs/239870
https://clickhouse.tech/docs/en/operations/external-authenticators/ldap/

My configuration file is as follows /etc/clickhouse-server/config.xml
```
    <ldap_servers>
         <ldap_server_name>
             <host>10.1.53.66</host>
             <port>389</port>
             <auth_dn_prefix>uid=</auth_dn_prefix>
          <auth_dn_suffix>,cn=users,cn=accounts,dc=yonghui,dc=cn</auth_dn_suffix>
             <enable_tls>no</enable_tls>
             <tls_require_cert>never</tls_require_cert>
         </ldap_server_name>
    </ldap_servers>
```

/etc/clickhouse-server/users.xml
```
    <users>
        <username>
             <ldap>
                 <server>ldap_server_name</server>
             </ldap>
             <networks incl="networks" replace="replace">
                  <ip>::/0</ip>
             </networks>
            <profile>default</profile>
            <quota>default</quota>
        </username>
    </users>
```

My account is 80913188. The account and password can be seen on ldap, and they have been confirmed to be correct, but an error was reported when logging in to clickhouse

<img width="1455" alt="image" src="https://user-images.githubusercontent.com/26197792/115493515-782de580-a296-11eb-9764-4d178d245740.png">

**Comment by traceon** [comment]
The error that is printed at `clickhouse-client` side is a generic one.
The `clickhouse-server` should have more informative log (right before a similar `Authentication failed: ...` message.)
Please, post that log message here.

Also, try binding to that LDAP server from the same terminal session, using OpenLDAP's `ldapwhoami` utility:
```sh
ldapwhoami -H 'ldap://10.1.53.66:389' -D 'uid=username,cn=users,cn=accounts,dc=yonghui,dc=cn' -w password
```
...and post the output here.

**Comment by mjh568412187** [comment]
> The error that is printed at `clickhouse-client` side is a generic one.
> The `clickhouse-server` should have more informative log (right before a similar `Authentication failed: ...` message.)
> Please, post that log message here.
> 
> Also, try binding to that LDAP server from the same terminal session, using OpenLDAP's `ldapwhoami` utility:
> 
> ```shell
> ldapwhoami -H 'ldap://10.1.53.66:389' -D 'uid=username,cn=users,cn=accounts,dc=yonghui,dc=cn' -w password
> ```
> 
> ...and post the output here.

<img width="1458" alt="image" src="https://user-images.githubusercontent.com/26197792/115561101-d20acb80-a2e7-11eb-95b7-1388f44cb20d.png">

Now I have configured clickhouse according to the above configuration,
by
ldapwhoami -x -D "uid=80913188,cn=users,cn=accounts,dc=yonghui,dc=cn" -W -H ldap://10.1.53.66:389
The data that can be accessed, I personally think there is no problem with the communication between the clickhouse server itself and ldap, but when the ldap configuration is configured in clickhouse, the execution of clickhouse-client will not work

clickhouse background log：
<img width="1428" alt="image" src="https://user-images.githubusercontent.com/26197792/115561703-6a08b500-a2e8-11eb-9cd8-2f708fc96258.png">

**Comment by mjh568412187** [comment]
> The error that is printed at `clickhouse-client` side is a generic one.
> The `clickhouse-server` should have more informative log (right before a similar `Authentication failed: ...` message.)
> Please, post that log message here.
> 
> Also, try binding to that LDAP server from the same terminal session, using OpenLDAP's `ldapwhoami` utility:
> 
> ```shell
> ldapwhoami -H 'ldap://10.1.53.66:389' -D 'uid=username,cn=users,cn=accounts,dc=yonghui,dc=cn' -w password
> ```
> 
> ...and post the output here.

Does your clickhouse configuration integrate ldap? Can I send out the configuration to see? Thank you

**Comment by traceon** [comment]
Is `80913188` your user name as also specified in `users.xml` config file? Like:
```xml
    <users>
        <80913188>
             <ldap>
                 <server>ldap_server_name</server>
             </ldap>
             <networks incl="networks" replace="replace">
                  <ip>::/0</ip>
             </networks>
            <profile>default</profile>
            <quota>default</quota>
        </username>
    </users>```

**Comment by mjh568412187** [comment]
> Is your `80913188` user name also specified in `users.xml` config file?
> 
> Like this:
> 
> ```
>     <users>
>         <80913188>
>              <ldap>
>                  <server>ldap_server_name</server>
>              </ldap>
>              <networks incl="networks" replace="replace">
>                   <ip>::/0</ip>
>              </networks>
>             <profile>default</profile>
>             <quota>default</quota>
>         </80913188>
>     </users>
> ```

-----
ok
Thank you for following your method, the complete configuration file is as follows:
/etc/clickhouse-server/config.xml

`    <ldap_servers>
         <ldap_server_name>
             <host>10.1.53.66</host>
             <port>389</port>
             
             <bind_dn>uid={user_name},cn=users,cn=accounts,dc=yonghui,dc=cn</bind_dn>
             <enable_tls>no</enable_tls>
             <tls_require_cert>never</tls_require_cert>
         </ldap_server_name>
    </ldap_servers>
`

/etc/clickhouse-server/user.xml

`    <users>
        <80913188>
             <ldap>
                 <server>ldap_server_name</server>
             </ldap>
             <networks incl="networks" replace="replace">
                  <ip>::/0</ip>
             </networks>
            <profile>default</profile>
            <quota>default</quota>
        </80913188>
    </users>
`

Restarting clickhouse in this way will fail. The error message is as follows:
<img width="1463" alt="image" src="https://user-images.githubusercontent.com/26197792/115649156-5f3a3880-a359-11eb-8499-3943e4a7ca5a.png">

This error is that the xml configuration file does not support numbers

----
/etc/clickhouse-server/user.xml

`
    <users>
       <ycd_mjh>
             <ldap>
                 <server>ldap_server_name</server>
             </ldap>
             <networks incl="networks" replace="replace">
                  <ip>::/0</ip>
             </networks>
            <profile>default</profile>
            <quota>default</quota>
      </ycd_mjh>
    </users>
`

The above configuration can get through

<img width="1465" alt="image" src="https://user-images.githubusercontent.com/26197792/115649353-b9d39480-a359-11eb-9dbd-db3324369345.png">

doubt:
If this is the case, first of all, the username cannot be a pure number
Second, do I need to configure all users in ldap one by one in users.xml?

This is obviously unreasonable, is there any other way?

**Comment by traceon** [comment]
>  the username cannot be a pure number

Yes, looks like, this is a limitation of XML config format.

> do I need to configure all users in ldap one by one in users.xml?

No, you can use LDAP as a user directory, see: https://clickhouse.tech/docs/en/operations/external-authenticators/ldap/#ldap-external-user-directory

**Comment by mjh568412187** [comment]
> > the username cannot be a pure number
> 
> Yes, looks like, this is a limitation of XML config format.
> 
> > do I need to configure all users in ldap one by one in users.xml?
> 
> No, you can use LDAP as a user directory, see: https://clickhouse.tech/docs/en/operations/external-authenticators/ldap/#ldap-external-user-directory

ok, i have solved the problem, thank you

**Comment by traceon** [comment]
@mjh568412187 if all problems mentioned here are solved/not relevant anymore, please feel free to close this issue.
