### ISSUE TITLE
Whenever I delete a table and rebuild it again with the same name, it reports an error

### ISSUE THREAD

**Issue by GeraltXLi** [ClickHouse/ClickHouse#23425]
**Describe the unexpected behaviour**
Whenever I delete a table and rebuild it again with the same name, it reports an error
```
e.displayText() = DB::ErrnoException: Cannot unlink file  XXXXXXX
```

**How to reproduce**
* Which ClickHouse server version to use
21.2.4.6 

* `CREATE TABLE` statements for all tables involved
I changed some sensitive information
```
CREATE TABLE test_info_local (
collect_time DateTime64(3),
t String,
s String,
sst DateTime64(3),
pss UInt64
)ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/test/test_info_local','{replica}')
PARTITION BY toYYYYMMDD(collect_time)
ORDER BY (collect_time)
TTL toDateTime(collect_time) + INTERVAL 6 MONTH
SETTINGS storage_policy = 'moving_from_ssd_to_hdd';
```

**Expected behavior**
The expectation is that the table should be created directly with success

**Comment by tavplubix** [comment]
Which file it cannot unlink? Is there stacktrace for the exception in server log?

**Comment by FakerGit** [comment]
> Which file it cannot unlink? Is there stacktrace for the exception in server log?

Just like this.
![image](https://user-images.githubusercontent.com/13702295/115548278-e21bae80-a2d9-11eb-8079-cee8c617dad6.png)

**Comment by tavplubix** [comment]
Hm, there is `dropIfEmpty()` in the stacktrace. It means that some error (probably related to ZooKeeper) occurred on table creation, than ClickHouse tried to cancel table creation by removing some files from disk, but another error (`Cannot unlink file`) happened and information about the first error was lost. 

Seems like `Cannot unlink file` may happen in multidisk configuration only. As a workaround you can try to create similar table with one-disk configuration to see the original error message.

Related: #23433

**Comment by FakerGit** [comment]
Thank you very much for your reply!
I will try it later.
