### ISSUE TITLE
Can I create Materialized view from another Materialized view?

### ISSUE THREAD

**Issue by FakerGit** [ClickHouse/ClickHouse#23423]
I actually have a raw data table that probably records the data for each scene of the game. Then I want to pre-aggregate the memory max for each scene, and then finally pre-aggregate the data for each scene for each hour. 

I tried it and it seems that the second materialized view does not generate data.

**Comment by tavplubix** [comment]
It should work, recursive materialized views are supported

**Comment by FakerGit** [comment]
The Materialized view, which select from another Materialized view, does not have data. 

```sql
/*source table*/
CREATE TABLE test_scene_info_local (
collect_time DateTime64(3),
scene String,
scene_start_time DateTime64(3),
pss UInt64
)ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/test/test_scene_info_local','{replica}')
PARTITION BY toYYYYMMDD(collect_time)
ORDER BY (collect_time)
TTL toDateTime(collect_time) + INTERVAL 6 MONTH
SETTINGS storage_policy = 'moving_from_ssd_to_hdd';

/*first materialized view*/
CREATE MATERIALIZED VIEW test_scene_mv (
	scene_start_time DateTime64(3),
	scene String,
	max_pss UInt64
)ENGINE = ReplicatedSummingMergeTree('/clickhouse/tables/{shard}/test/test_scene_mv','{replica}')
PARTITION BY toYYYYMMDD(scene_start_time)
ORDER BY (scene_start_time,scene)
TTL toDateTime(scene_start_time) + INTERVAL 6 MONTH
SETTINGS storage_policy = 'moving_from_ssd_to_hdd'
AS SELECT 
scene ,
scene_start_time,
max(pss) as max_pss
FROM test_scene_info_local
group by (scene_start_time,scene)
order by (scene_start_time,scene);

/*second materialized view*/
CREATE MATERIALIZED VIEW test_scene_hour_mv (
	hour DateTime,
	scene String,
	avg_pss_peak Float64
)ENGINE = ReplicatedSummingMergeTree('/clickhouse/tables/{shard}/test/test_scene_hour_mv','{replica}')
PARTITION BY toYYYYMMDD(hour)
ORDER BY (hour,scene)
TTL hour + INTERVAL 6 MONTH
SETTINGS storage_policy = 'moving_from_ssd_to_hdd' AS
SELECT 
toStartOfHour(scene_start_time) as hour,
scene,
avg(max_pss) as avg_pss_peak
FROM test_scene_mv
group by (hour,scene)
order by (hour,scene);

/*insert*/
insert into test_scene_info_local (collect_time,transid,scene,scene_start_time,pss) VALUES
('2021-04-21 16:27:01.291','PLAY','2021-04-21 16:27:01.001',10),
('2021-04-21 16:27:02.291','PLAY','2021-04-21 16:27:01.001',8),
('2021-04-21 16:27:03.291','PLAY','2021-04-21 16:27:01.001',6),
('2021-04-21 16:27:10.222','ROOM','2021-04-21 16:27:10.222',50),
('2021-04-21 16:27:11.222','ROOM','2021-04-21 16:27:10.222',80),
('2021-04-21 17:27:20.300','PLAY','2021-04-21 16:27:20.280',80),
('2021-04-21 17:27:20.300','PLAY','2021-04-21 16:27:20.280',80);
```

**Comment by den-crane** [comment]
https://den-crane.github.io/Everything_you_should_know_about_materialized_views_commented.pdf (page 18)

You should use:
```sql
FROM `.inner.test_scene_mv`
```
But only if database is not Atomic.

**Comment by FakerGit** [comment]
Thank you very much for your reply! Especially this document.
I have created the second mv from the source table of first mv  and it worked.

**Comment by FakerGit** [comment]
@den-crane

**Comment by FakerGit** [comment]
I first pre-aggregate the max memory values for each scenario as view 1, and then aggregate the average of the max memory values for each scenario within an hour based on view 1. The group by of view 1 and view 2 is not the same.

Like the problem mentioned on page 13 of your document, if the two parts of the data are written at different times, it will result in two records for the max of view 1 (at this time, view 1 itself has no problem with the maxMerge query because of group by), but view 2 will also produce the corresponding two data, and avgMerge will have a problem.

@den-crane Is there a solution for this?

**Comment by FakerGit** [comment]
> I first pre-aggregate the max memory values for each scenario as view 1, and then aggregate the average of the max memory values for each scenario within an hour based on view 1. The group by of view 1 and view 2 is not the same.
> 
> Like the problem mentioned on page 13 of your document, if the two parts of the data are written at different times, it will result in two records for the max of view 1 (at this time, view 1 itself has no problem with the maxMerge query because of group by), but view 2 will also produce the corresponding two data, and avgMerge will have a problem.
> 
> ```sql
> view_1:
> ts    scene max_memory
> 16:01 room  10
> 16:01 room  20
> 
> select ts, scene, max(max_memory) from view_1 group by (ts, scene);  /*result is 20, which is exactly what we expected*/
> 
> 
> view_2:
> hour  scene env avg_memory
> 16:00 room  dev xx
> 16:00 room  dev xx
> 
> select hour, scene,env, avgMerge(avg_memory)  from view_2 group by(hour,scene,env)
> /*result is 15 instead of 20. But the max memory is 20 and the count of scene is 1. It should be 20 (20/1).*/
> ```
> 
> @den-crane Is there a solution for this?

I will try use replacingTree.

**Comment by den-crane** [comment]
ttl group by 
https://github.com/ClickHouse/ClickHouse/issues/14345#issue-690219122
