### ISSUE TITLE
After the Kafka engine table is deleted, the materialized view cannot consume the Kafka data and submit the offset according to the original construction model. The offset will only be submitted when the Kafka table is queried by select

### ISSUE THREAD

**Issue by qianmoQ** [ClickHouse/ClickHouse#23430]
(you don't have to strictly follow this form)

**Describe the bug**
After the Kafka engine table is deleted, the materialized view cannot consume the Kafka data and submit the offset according to the original construction model. The offset will only be submitted when the Kafka table is queried by select

**Does it reproduce on recent release?**
20.11.3.3

**How to reproduce**
* Clickhouse 20.11.3.3

**Step**
1. Create Kafka Table

```sql
CREATE TABLE IF NOT EXISTS olap_kafka_transform_local ON CLUSTER ck_cluster_1
(
    `id` String,
    `dt` String,
    `cc_level1` String,
    `cc_level2` String,
    `cc_level3` String,
    `app_id` UInt32
) ENGINE = Kafka
    SETTINGS
    kafka_broker_list = 'xxxxxxx',
    kafka_topic_list = 'olap_consume_offline',
    kafka_group_name = 'olap_consume_offline_ck_cluster_1',
    kafka_format = 'JSONEachRow',
    kafka_num_consumers = 6,
    kafka_max_block_size = 20000,
    kafka_skip_broken_messages = 1048577;;
```

2. delete kafka engine table

```sql
drop table olap_kafka_transform_local ON CLUSTER ck_cluster_1;
```

3. Recreate Kafka table
4. Problems recur

**Expected behavior**

**Error message and/or stacktrace**

**Additional context**

**Comment by filimonov** [comment]
1. Can you clarify what means "submit the offset according to the original construction model" ? 
2. Can you share the fragment of `/var/log/clickhouse-server/clickhouse-server.log` after table was recreated? I'm interested in log lines with trace log level containing Kafka. Do the data from Kafka topic is coming to MV?

**Comment by filimonov** [comment]
Can not reproduce, see #24941
