### ISSUE TITLE
Major slowdown on queries with multiple subquery levels

### ISSUE THREAD

**Issue by vpanfilov** [ClickHouse/ClickHouse#23444]
Hello. We use fairly complicated dynamically-generated nested queries in our project and discovered strange performance issues on queries with multiple levels of filtering.

**How to reproduce**
* Tested on version 21.3.6.55
* Minimal reproducible example that leads to terrible performance:
```sql
WITH
  initial_query AS (
    SELECT 1 AS number
  ),
  query1 AS (
    SELECT *, number1 AS number FROM (
      SELECT *, number AS number1
      FROM initial_query
      WHERE number IN (SELECT number FROM initial_query)
    )
  ),
  query2 AS (
    SELECT *, number2 AS number FROM (
      SELECT *, number AS number2
      FROM query1
      WHERE number IN (SELECT number FROM query1)
    )
  ),
  query3 AS (
    SELECT *, number3 AS number FROM (
      SELECT *, number AS number3
      FROM query2
      WHERE number IN (SELECT number FROM query2)
    )
  ),
  query4 AS (
    SELECT *, number4 AS number FROM (
      SELECT *, number AS number4 FROM query3
      WHERE number IN (SELECT number FROM query3)
    )
  )
SELECT * FROM query4
```
```
1 rows in set. Elapsed: 78.911 sec.
```

The more nesting levels are used, the slower is the performance: 

- query1 ~ 0.005 sec.
- query2 ~ 0.05 sec.
- query3 ~ 1.5 sec.
- query4 ~ 80 sec.

**Expected performance**
The query should execute almost immediately

**Comment by amosbird** [comment]
Expanded query looks as expected http://oracle.wentropy.com/b4327614776a9633 as we don't cache CTE results.

@KochetovNicolai Why do we have two CreatingSetsTransform for a query with only one `IN` clause http://oracle.wentropy.com/6e9d21bf52888211

**Comment by vpanfilov** [comment]
Seems to be connected with https://github.com/ClickHouse/ClickHouse/issues/21992

**Comment by vpanfilov** [comment]
Interestigly, this query:
[see on gh-api.clickhouse.tech](https://gh-api.clickhouse.tech/play?user=play#V0lUSAogIGluaXRpYWxfcXVlcnkgQVMgKAogICAgU0VMRUNUIDEgQVMgbnVtYmVyCiAgKSwKICBxdWVyeTEgQVMgKAogICAgU0VMRUNUICosIG51bWJlcjEgQVMgbnVtYmVyIEZST00gKAogICAgICBTRUxFQ1QgKiwgbnVtYmVyIEFTIG51bWJlcjEKICAgICAgRlJPTSBpbml0aWFsX3F1ZXJ5CiAgICAgIFdIRVJFIG51bWJlciBJTiAoU0VMRUNUIG51bWJlciBGUk9NIGluaXRpYWxfcXVlcnkpCiAgICApCiAgKSwKICBxdWVyeTIgQVMgKAogICAgU0VMRUNUICosIG51bWJlcjIgQVMgbnVtYmVyIEZST00gKAogICAgICBTRUxFQ1QgKiwgbnVtYmVyIEFTIG51bWJlcjIKICAgICAgRlJPTSBxdWVyeTEKICAgICAgV0hFUkUgbnVtYmVyIElOIChTRUxFQ1QgbnVtYmVyIEZST00gcXVlcnkxKQogICAgKQogICksCiAgcXVlcnkzIEFTICgKICAgIFNFTEVDVCAqLCBudW1iZXIzIEFTIG51bWJlciBGUk9NICgKICAgICAgU0VMRUNUICosIG51bWJlciBBUyBudW1iZXIzCiAgICAgIEZST00gcXVlcnkyCiAgICAgIFdIRVJFIG51bWJlciBJTiAoU0VMRUNUIG51bWJlciBGUk9NIHF1ZXJ5MikKICAgICkKICApLAogIHF1ZXJ5NCBBUyAoCiAgICBTRUxFQ1QgKiwgbnVtYmVyNCBBUyBudW1iZXIgRlJPTSAoCiAgICAgIFNFTEVDVCAqLCBudW1iZXIgQVMgbnVtYmVyNCBGUk9NIHF1ZXJ5MwogICAgICBXSEVSRSBudW1iZXIgSU4gKFNFTEVDVCBudW1iZXIgRlJPTSBxdWVyeTMpCiAgICApCiAgKQpTRUxFQ1QgKiBGUk9NIHF1ZXJ5NA==)
shows only 0.1 second as elapsed time in web interface though it is being calculated for around a minute. Does it mean that the majority of time is being spent on query parsing and AST optimising stage?

**Comment by vpanfilov** [comment]
It seems that default setting `enable_optimize_predicate_expression = 1` is the root cause of the problem:

For example:
```sql
WITH
  initial_query AS (
    SELECT 1 AS number
  ),
  query1 AS (
    SELECT *, number1 AS number FROM (
      SELECT *, number AS number1
      FROM initial_query
      WHERE number IN (SELECT number FROM initial_query)
    )
  ),
  query2 AS (
    SELECT *, number2 AS number FROM (
      SELECT *, number AS number2
      FROM query1
      WHERE number IN (SELECT number FROM query1)
    )
  ),
  query3 AS (
    SELECT *, number3 AS number FROM (
      SELECT *, number AS number3
      FROM query2
      WHERE number IN (SELECT number FROM query2)
    )
  ),
  query4 AS (
    SELECT *, number4 AS number FROM (
      SELECT *, number AS number4 FROM query3
      WHERE number IN (SELECT number FROM query3)
    )
  )
SELECT * FROM query4
SETTINGS enable_optimize_predicate_expression = 1
```
```
1 rows in set. Elapsed: 81.958 sec. (read 945 rows)
```
But after disabling this optimization, the number of rows in reduced dramatically and query exetutes immediately:
```sql
WITH
  initial_query AS (
    SELECT 1 AS number
  ),
  query1 AS (
    SELECT *, number1 AS number FROM (
      SELECT *, number AS number1
      FROM initial_query
      WHERE number IN (SELECT number FROM initial_query)
    )
  ),
  query2 AS (
    SELECT *, number2 AS number FROM (
      SELECT *, number AS number2
      FROM query1
      WHERE number IN (SELECT number FROM query1)
    )
  ),
  query3 AS (
    SELECT *, number3 AS number FROM (
      SELECT *, number AS number3
      FROM query2
      WHERE number IN (SELECT number FROM query2)
    )
  ),
  query4 AS (
    SELECT *, number4 AS number FROM (
      SELECT *, number AS number4 FROM query3
      WHERE number IN (SELECT number FROM query3)
    )
  )
SELECT * FROM query4
SETTINGS enable_optimize_predicate_expression = 0
```
```
1 rows in set. Elapsed: 0.144 sec. (read 16 rows)
```
Elapsed time is from clickhouse-client and number of rows read is from Clickhouse web UI

EXPLAIN PIPELINE of the query with `enable_optimize_predicate_expression = 1`:
```
10347 rows in set.
```

EXPLAIN PIPELINE of the query with `enable_optimize_predicate_expression = 0`:
```
186 rows in set
```

**Comment by alexey-milovidov** [comment]
Hold before #31796.

**Comment by fm4v** [comment]
Must be fixed in the new analyzer `SET allow_experimental_analyzer=1;`

5 subquery levels:
<table>
<tr>
 <td>rows in EXPLAIN PIPELINE
 <td>allow_experimental_analyzer=0
 <td>allow_experimental_analyzer=1
<tr>
 <td>enable_optimize_predicate_expression=1
 <td>103450
 <td>346
<tr>
 <td>enable_optimize_predicate_expression=0
 <td>346
 <td>346
</table>
