### ISSUE TITLE
Support quantile(level, expr)

### ISSUE THREAD

**Issue by cw9** [ClickHouse/ClickHouse#23448]
The [quantile functions](https://clickhouse.tech/docs/en/sql-reference/aggregate-functions/reference/quantile/) in ClickHouse supports `quantile(level)(expr)`, is it possible to support `quantile(level, expr)`? 
The latter format is much easier to use with standard SQL libraries.

**Comment by alexey-milovidov** [comment]
It is possible but requires moderate changes in query engine.

In current implementation, constant arguments of aggregate functions are processed in the same way as non-constant arguments. But the constant parameters may alter the implementation of aggregate function - in fact, different aggregate functions can be run depending on the values of constant parameters.

**Comment by alexey-milovidov** [comment]
This task cannot be implemented earlier than #12552.

**Comment by alexey-milovidov** [comment]
It will be better to avoid implementing this task.
