### ISSUE TITLE
Syncronous Insert into Distributed table via http with insert_distributed_sync=1 returns success response before all data inserted, which leads to incomplete data in select after

### ISSUE THREAD

**Issue by lazydream** [ClickHouse/ClickHouse#23454]
**Describe the bug**
I'm trying to insert some data into distributed table on clickhouse cluster with two shards via http interface. I'm using  insert_distributed_sync=1 so I expect to get success response only after all data is saved on shards, but when I'm trying to select data from table immediately after insert success response, it's possible to get incomplete data. When add some sleep time between insert and select, select returns complete data

**How to reproduce**
Run script which executes queries listed below on clickhouse cluster via http interface, (with insert_distributed_sync=1 parameter for insert query) one after another. Expected count after insert - 31, got 0 or something different than 31

* Which ClickHouse server version to use
ClickHouse server version 20.8.3 revision 54438.

* Which interface to use, if matters
http

* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved

┌─statement──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ CREATE TABLE tableau.count_click__part
(
    `dt` Date,
    `updated_dt` Date,
    `countClick` UInt32
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/count_click__part ', '{replica}')
PARTITION BY toYYYYMMDD(updated_dt)
ORDER BY tuple()
SETTINGS index_granularity = 8192 │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

┌─statement──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ CREATE TABLE tableau.count_click
(
    `dt` Date,
    `updated_dt` Date,
    `countClick` UInt32
)
ENGINE = Distributed('tableau', 'tableau', 'count_click__part', rand()) │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

* Queries to run that lead to unexpected result
INSERT INTO tableau.count_click FORMAT JSONEachRow {"dt": "2021-03-21", "countClick": 1, "updated_dt": "2021-04-21"} {"dt": "2021-03-22", "countClick": 1, "updated_dt": "2021-04-21"} {"dt": "2021-03-23", "countClick": 1, "updated_dt": "2021-04-21"} {"dt": "2021-03-24", "countClick": 1, "updated_dt": "2021-04-21"} {"dt": "2021-03-25", "countClick": 1, "updated_dt": "2021-04-21"} {"dt": "2021-03-26", "countClick": 1, "updated_dt": "2021-04-21"} {"dt": "2021-03-27", "countClick": 1, "updated_dt": "2021-04-21"} {"dt": "2021-03-28", "countClick": 1, "updated_dt": "2021-04-21"} {"dt": "2021-03-29", "countClick": 1, "updated_dt": "2021-04-21"} {"dt": "2021-03-30", "countClick": 1, "updated_dt": "2021-04-21"} {"dt": "2021-03-31", "countClick": 1, "updated_dt": "2021-04-21"} {"dt": "2021-04-01", "countClick": 1, "updated_dt": "2021-04-21"} {"dt": "2021-04-02", "countClick": 1, "updated_dt": "2021-04-21"} {"dt": "2021-04-03", "countClick": 1, "updated_dt": "2021-04-21"} {"dt": "2021-04-04", "countClick": 1, "updated_dt": "2021-04-21"} {"dt": "2021-04-05", "countClick": 1, "updated_dt": "2021-04-21"} {"dt": "2021-04-06", "countClick": 1, "updated_dt": "2021-04-21"} {"dt": "2021-04-07", "countClick": 1, "updated_dt": "2021-04-21"} {"dt": "2021-04-08", "countClick": 1, "updated_dt": "2021-04-21"} {"dt": "2021-04-09", "countClick": 1, "updated_dt": "2021-04-21"} {"dt": "2021-04-10", "countClick": 1, "updated_dt": "2021-04-21"} {"dt": "2021-04-11", "countClick": 1, "updated_dt": "2021-04-21"} {"dt": "2021-04-12", "countClick": 1, "updated_dt": "2021-04-21"} {"dt": "2021-04-13", "countClick": 1, "updated_dt": "2021-04-21"} {"dt": "2021-04-14", "countClick": 1, "updated_dt": "2021-04-21"} {"dt": "2021-04-15", "countClick": 1, "updated_dt": "2021-04-21"} {"dt": "2021-04-16", "countClick": 1, "updated_dt": "2021-04-21"} {"dt": "2021-04-17", "countClick": 1, "updated_dt": "2021-04-21"} {"dt": "2021-04-18", "countClick": 1, "updated_dt": "2021-04-21"} {"dt": "2021-04-19", "countClick": 1, "updated_dt": "2021-04-21"} {"dt": "2021-04-20", "countClick": 1, "updated_dt": "2021-04-21"}

 SELECT count(*) from tableau.count_click

**Expected behavior**
I expected to always get all records from Distributed table after get success response from insert request with insert_distributed_sync = 1 set. But its possible to get incomplete data in that case

**Comment by kitaisreal** [comment]
@azat can you take a look at it ?

**Comment by azat** [comment]
>Run script which executes queries listed below on clickhouse cluster via http interface, (with insert_distributed_sync=1 parameter for insert query) one after another. Expected count after insert - 31, got 0 or something different than 31

Can you share steps to reproduce? Since I cannot reproduce it.

```sql
create table data (key Int) engine=Memory();
```

```sh
{ echo "INSERT INTO FUNCTION remote('127.2', currentDatabase(), data) FORMAT TabSeparated"; yes 1 | head -n100; } | curl 127.1:8123/? --data-binary @- && curl 127.1:8123/ --data-binary @- <<<'SELECT count() FR
OM data'
# note that insert into function remote() is always synchronous, so I don't pass insert_distributed_sync=1
```

I see that you have ReplicatedMergeTree, with default `load_balancing=random` you may query different replicas and this can be the reason.
Take a look at `insert_quorum` and `select_sequential_consistency` settings.

>ClickHouse server version 20.8.3 revision 54438.

Can you try newer version? Does only http affected in your case?

**Comment by lazydream** [comment]
@azat yes, 

we have 2 replicas for each shard, so with `insert_distributed_sync=1` clickhouse returns success response after insert finished on 1 replica (not all replicas), and select query straight after insert query may lead to getting data from other replicas with incomplete data at the moment

In case of more than 1 (n) replica setting `insert_quorum=n` solves the problem of getting inconsistent results right after insert in a replicated table
