### ISSUE TITLE
Support of dynamic subcolumns in tables.

### ISSUE THREAD

**Issue by CurtizJ** [ClickHouse/ClickHouse#23516]
Inroduce new data type `Object(<schema format>)`, which will get the name of format for semi-structured data (`JSON`, `XML`, etc.).
Initially it will work only with `MergeTree` tables. Maybe later will add some other storages.

Values will be inserted as strings to columns of that type. Then separate subcolumns will be parsed according to schema format and written in columnar format.

Subcolumns of type `Object` will be stored in the lowest common type in which all values of subcolumn can be represented.

Columns of type `Object` will support reading of subcolumns and slices at arbitrary level of nesting.

For example if we will write in the column with name `user` and type `Object` the following `JSON`:
```json
{
    "name" : "John",
    "age" : 42,
    "location" : {
        "country" : "USA",
        "city" : "New York"
    }
}
```

There will be 4 columns, available for reading: `user.name`, `user.age`, `user.location.country`, `user.location.city`. Also slice `user.location.*`.

Preferred type of subcolumn in query should be specified with operator `::`, e.g. `user.age::UInt8`. If it will be omitted, subcolumn will be converted to `String`.

### Implementation details

Introduce `DataTypeObject`, `SerializationObject` and `ColumnObject`.

Metadata of storage will store `DataTypeObject` for column. It will know nothing about its subcolumns. There will be concrete data types (named tuples) in data parts, which will be deduced from data. For queries there are 2 approaches:

- Don't get any information about all subcolumns from table. In inserts always allow to insert new subcolumns. In selects it's not a problem for query analysis, because type will be specified in query (or will be `String`). If it will be absent in some parts (possibly all) column will be filled by defaults.
Caveats: in inserts we won't be able to return error in case, when new type of subcolumn is totally incompatible with old type, (f.e. `String` and `Array(UInt32)`). However we always can write data as string, but any small mistake will lead to writing garbage to the table. In selects we won't be able to read slices (`user.location.*` from example above).

- Before execution of query get types of all subcolumns. We can deduce common type from parts.
Caveats: may be too slow due to large number of parts and subcolumns. Also some races are possible and maybe additional synchronisation will be required.

For now I am not sure which one is better.

`ColumnObject` will store map from keys to regular columns.

Insertion will be supported from row-based input formats. Structure (JSON and similar) will be parsed for every row, then all paths will be extracted and added to `ColumnObject` as strings. When new key will appear, new subcolumn with all defaults will be added to `ColumnObject`. After all rows will be parsed, types of every subcolumns will be optimized to lowest common for all values. And finally `DataTypeObject` will be converted to named `Tuple`, which will be written in part metadata. It's ok to use path as keys, because serialization of such flat tuple will be the same as complex structure of tuple, f.e. for types ```Tuple(a String, b Tuple(c UInt32, d UInt32))``` and ```Tuple(a String, `b.c` UInt32 `b.d` UInt32)```.

Caveats: it will be harder to read intermediate structure as tuple, but anyway you can't do very much with tuples in ClickHouse. Some problems may exist with `Nested` type with multiple levels.

Before merge for every subcolumn of type `Object` will be deduced the least common type among all parts and in new part it will be written in that type.

**Comment by filimonov** [comment]
> When new key will appear, new subcolumn with all defaults will be added to ColumnObject. After all rows will be parsed, types of every subcolumns will be optimized to lowest common for all values.

Please check also whitepapers of the Dremel (it's used by Google BigQuery): https://storage.googleapis.com/pub-tools-public-publication-data/pdf/36632.pdf

**Comment by UnamedRus** [comment]
What if JSON files which  are going to be inserted in table would have quite a lot of uniq keys? (It could be up to millions per partition)
It would be great if such uniq and non frequent keys could be handled in another way. (eg not create separate files for each subcolumn) One of possible solution is: create multiple bucket arrays/maps.

Sometimes it's would be possible to do by hand, but it would be pretty convenient if we would have single syntax for accessing all element's of JSON type.

**Comment by CurtizJ** [comment]
It's planned to write all subcolumns in columnar format, but if their amount will be to large, to merge some of them to one file. It will looks like some intermediate format of part between wide and compact. It's almost the last task, that remains to make PR ready for review.

**Comment by UnamedRus** [comment]
> It will looks like some intermediate format of part between wide and compact.
That's cool.

But would it be efficient with really huge amount of keys.
eg you would need to store marks offset for each "key", arrays/map like could be more compact, but it's only my thoughts.

**Comment by alexey-milovidov** [comment]
@UnamedRus We have three almost independent features that are in development:
1. Sparse serialization and dynamic choice of serialization format for columns.
2. Dynamic subcolumns.
3. Combining large number of columns together.

**Comment by UnamedRus** [comment]
First two is obvious. 

But 
> Combining large number of columns together.

Can you link to pr/rfc?

Would it work like wide column store?

**Comment by alexey-milovidov** [comment]
It is almost identical to compact parts but the columns will be combined based on their hash.
As simple as hash % 64 -> column group.

**Comment by xuanyue202** [comment]
@alexey-milovidov is there are issue/pr/rfc that is linked to the mechanism you mentioned? this is very crucial for us.

**Comment by alexey-milovidov** [comment]
@xuanyue202 This: #23932

**Comment by yiguolei** [comment]
@alexey-milovidov  When will this feature be completed? It is very crucial for us too

**Comment by alexey-milovidov** [comment]
Today we have working prototype, it is being tested on various datasets and already can be used for some demos.
Making it production-ready may take at least several months.
And it will appear in stable release not earlier than in November (most likely later).

**Comment by sundarv85** [comment]
Hi @alexey-milovidov, We are very much interested in using this feature. Is there a test build/branch which we can use for our initial development - so that we will be able to move faster when the final release happens by end of this year/early next year..

**Comment by UnamedRus** [comment]
Go to pr https://github.com/ClickHouse/ClickHouse/pull/23932

Navigate to the end of page:

Find check:  **ClickHouse build check — 9/13 builds are OK**
Click on **Details**.
Use files from here.

**Comment by sundarv85** [comment]
One question is: since these are dynamic sub-columns - would there be a command to fetch all the new distinct dynamic sub-column names available (instead of the values, just the name of the columns)

If we get that, we can then show this in our UI for easy filtering option..

**Comment by CurtizJ** [comment]
> What about type conflicts? E.g. when fields with same keys have different types. Fallback to raw JSON?

Types will be promoted to the least common type and columns from old parts will be converted to the new type while reading. E.g. this conversion is possible: `Int8 -> Int64 -> Float64 -> String`.

**Comment by CurtizJ** [comment]
> Would there be a command to fetch all the new distinct dynamic sub-column names available?

Yes, names and types of subcolumns will be available in `DESCRIBE` query with options `describe_extend_object_types` and `describe_include_subcolumns`.

**Comment by ernado** [comment]
Can we have an option to disable conversion during read to keep type of old parts?

Probably we can even split parts by type conflicts to preserve types (at least without losing information, e.g. we can merge `Int`-s safely to maximum type).

**Comment by CurtizJ** [comment]
No, it's not implemented now. And it's not clear how to deal with columns that are written in different types, because we won't be able to read the whole column. Probably we could handle this cases by forcing user to specify type in `::` operator and apply `castOrDefault` function, which will do nothing if type of column is already the same as requested, but our query analyzer is not ready for this currently. Or we can just skip parts in which types are mismatched, which seems bad to me.

Also, I didn't mention that columns are converted to the least common type during merges too.

**Comment by ernado** [comment]
Got it, thank you!

So, my concern is following situation.

What if we insert such rows:
``` json
{ "event": "GotArray",  "data": [1, 2, 3, 4, 5] }
{ "event": "GotStr",    "data": "foo" }
{ "event": "GotBool",   "data": true }
```

Can we read them back as json without losing types (or insert at all)?

**Comment by ernado** [comment]
One possible solution is to create a new type `RawJSON` which is `String` that must be valid json value, e.g. `true`, `false`, `[1, 2, 3]` and use it as least common type in situations when types are not from the same kind (e.g. not uint8 vs int8).


This will allow us to read back any object we write to `JSON` with same merge logic.

Also, part merge can calculate benefit from merge in some way and refuse to merge some parts.
For example, we have single value of `RawJSON` and 99.9% values of `uint8`, so it can very wasteful.

Sorry, I'm not very familiar with ClickHouse internals and some of this can be nonsense, but I'm building a log storage on top of ClickHouse and very interested in this feature, so trying to address most of domain-specific concenrs.

For reference:
* [OTEL Log model](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md#log-data-model)
* [UBER Logging](https://eng.uber.com/logging/), they use arrays of keys and values for each type.

**Comment by vmihailenco** [comment]
I use OpenTelemetry for a similar purpose and wonder why do you care so much about the type? As a user, I don't care at all whether `true` is a string, a boolean, or a number. I want rich and fast query language, i.e. check if `data` from you example contains/equals `true`. The underlying type does not matter much - it will look the same in UI.

**Comment by ernado** [comment]
@vmihailenco

The `"true"` and `true` are different json values and can look different in UI. I care about types because json have them, column type name is `JSON`, not some kind of `WeakTypedStructure`. I want to read back from database same `json` that I'm writing to column, I think it is appropriate assumption. 

Also it is not clear how to represent json field with contains values such as `[1, 2]` and `1`, there is no common type for them except raw json.

Fuzzy type coercion can be implemented on top of it and fully supporting `json` values does not conflict with "rich and fast query language", just adds expected correctness and least surprise.

**Comment by ernado** [comment]
Also another point is to look into storing such values (with conflicting types!) as some kind of `jsonb` like PostgreSQL does.

**Comment by vmihailenco** [comment]
Thanks for the answer.

>Also it is not clear how to represent json field with contains values such as [1, 2] and 1, there is no common type for them except raw json.

Yes, if you look at the problem through the "what type" prism. But you can filter such different values just fine (equals for scalars, `has` for arrays). `p50(some.json.column)` would probably require using `toFloat64OrDefault` on all values. Would be nice if CH can help with it.

>fully supporting json values does not conflict with "rich and fast query language", just adds expected correctness and least surprise.

True, if we can have it all, let's have it. My point is that it is more important what I can do with all these types, not how it works/typed internally...

**Comment by marwan-nwh** [comment]
I spent a few days thinking about Uber's solution and this solution, and I think there are some benefits for Uber's solution over the proposed solution (at this stage), but I could be wrong.  

I will try to summarize it in a few points:
- The point mentioned by @ernado (when a new type is totally incompatible with the old type) is not a problem at all in Uber's solution. Except, that solution reduces the types to String (for text), Float64 (for numbers), and UInt8 (for booleans), also Array(String) and Array(Float64)
- The proposed solution seems to save more space by using the lowest common type, while Uber's solution uses Float64 for all numbers. But, this solution will keep abandoned columns as columns, while Uber's solution just keeps them as values, which could waste some of the space we gained by using the lowest possible type. You also still could do this `Array(Int8) -> Array(Int16) -> Array(Int32) -> Array(Int64) -> Array(Float64)` using arrays.
- You don't need to run any alterations in Uber's solution. (Except if you did the last part in the previous point)

Some unexpected behavior of other databases:
- Druid doesn't complain if you pushed incompatible types to the same column but complain at querying.
- Rockset makes a better job but returns inaccurate data, so if you inserted the following
```
{ "price": "30"}
{ "price": 50 }
{ "price": 40}
```
then you query `SELECT price FROM mytable where price > 30`, it could return 50 only or 40 only, not sure why.

Concerns with Uber's solution: Performance of the query on a large amount of data, because everything works with the arrays, not sure how good ClickHouse at this, will try to test it.

Sorry if this is negative feedback.

**Comment by UnamedRus** [comment]
> But, this solution will keep abandoned columns as columns

If this column have at least 1 non-default value in part, it will be written to disk.
And if it have low amount of non default values in part, it will use sparse serialization.
https://github.com/ClickHouse/ClickHouse/issues/19953

> Performance of the query on a large amount of data, because everything works with the arrays, not sure how good ClickHouse at this, will try to test it.

We can assume that arrays would be at least couple of times slower than separate columns.
And read much more data from disk.

**Comment by marwan-nwh** [comment]
> We can assume that arrays would be at least couple of times slower than separate columns.
And read much more data from disk.

This could be solved using Materialized Views, right?

I would love to not deal with arrays, and implement something like this or use it as a native solution of course, but I don't want to face problems later.

And what about alterations? And in Uber's article, they mentioned that after a while, they had too many columns, which made CH unresponsive.

**Comment by marwan-nwh** [comment]
I wish I were able to provide a PR, but I am not that good :) 
But if we can have it all natively, please let's do that.

**Comment by marwan-nwh** [comment]
Can I suggest an addition to this feature? 
If ClickHouse could keep some info about the frequency of using the columns it will be perfect. It would be even more perfect if we could have a configuration somewhere to delete the columns that have not been used in the last number of days.

**Comment by UnamedRus** [comment]
@marwan-nwh 

You can find this info in system.query_log table, with even better granularity. 

```
databases:                             ['system']
tables:                                ['system.warnings']
columns:                               ['system.warnings.message']



DESC system.query_log;
│ databases                             │ Array(LowCardinality(String))                                                                          │              │                          │         │                  │                │
│ tables                                │ Array(LowCardinality(String))                                                                          │              │                          │         │                  │                │
│ columns                               │ Array(LowCardinality(String))                                                                          │              │                          │         │                  │                │
│ projections                           │ Array(LowCardinality(String))                                                                          │              │                          │         │                  │                │
│ views                                 │ Array(LowCardinality(String))
```

**Comment by marwan-nwh** [comment]
Wow, perfect 👌

**Comment by xiaokang** [comment]
Hi @CurtizJ, it's a really useful feature!

What's the final choice of the 2 approaches?

> There will be concrete data types (named tuples) in data parts, which will be deduced from data. For queries there are 2 approaches:

**Comment by marwan-nwh** [comment]
Will CH suffer if a lot of distinct columns have been inserted using this feature?

**Comment by CurtizJ** [comment]
@xiaokang
The second approach has been chosen. The types are deduced from parts before analysis of query. For better performance common types can be cached and recalculate only when new part is added (after insert or fetch).

**Comment by CurtizJ** [comment]
@marwan-nwh

The performance of queries may suffer if number of distinct columns will exceed several thousands. The analysis of query may take long time in that case (up to several seconds). But in case, when there are selected not many columns in one query, the performance should be good and shouldn't differ a lot from case, when there are only selected columns in table.

Also to solve this problem, there will be implemented hybrid wide/compact data part format, in which some columns will be grouped to one file to avoid huge number of files.

**Comment by UnamedRus** [comment]
> Also to solve this problem, there will be implemented hybrid wide/compact data part format, in which some columns will be grouped to one file to avoid huge number of files.

I think, it make sense to be able to control how columns being grouped in such files manually.

For example, in telecom, it's possible to have logic groups of columns which related to ~one metric, but for different percentile or frequency.

**Comment by CurtizJ** [comment]
> I think, it make sense to be able to control how columns being grouped in such files manually.

I agree, we are thinking now about how it's better to implement grouping. Also, it makes sense to have some statistics about usage of columns and group first of all rarely used columns.

**Comment by UnamedRus** [comment]
> group first of all rarely used columns.

That's sounds good.
But it also brings another topic.

What if you have millions of uniq keys (at some level of json), having separate columns for them will be a big overhead even with sparse serialization. 

May be they can be collected in maps with full path as key. `map['json.key1.key2.keyc']`

**Comment by sundarv85** [comment]
Hello, Is there any timeline for this feature to be shipped in a particular release..

**Comment by alexey-milovidov** [comment]
@sundarv85 See the answer here: https://github.com/ClickHouse/ClickHouse/pull/23932

**Comment by taiyang-li** [comment]
That's a wonderful feature!!!  Thank you @CurtizJ

**Comment by arun11299** [comment]
Thanks for this feature. It looks like an important step for clickhouse. Any examples on how to aggregate the data in JSON type using an MV and Summing/Aggregated Merge tree ? Would the target table need explicit rows or can we use JSON type there as well ?

**Comment by alexey-milovidov** [comment]
@arun11299 You can have flexible schema in the source table (where you SELECT) but the aggregated table will have strict schema and the SELECT query should the explicit list of aggregate functions.

**Comment by nityanandagohain** [comment]
Is there a limit on the number of uniue keys that a JSON column can store ?
