### ISSUE TITLE
Add thread name to logger message

### ISSUE THREAD

**Issue by JackyWoo** [ClickHouse/ClickHouse#23537]
This idea is modified by:

1. log will be more readable
2. many systems of other language log thread name
3. Many thread name setted in CH code

**Comment by filimonov** [comment]
Actually the task is very easy, but it's a bit questionable - it will pollute logs with more data, but the extra value of that is not 100% clear -  normally certain types of messages can happen in certain types of threads anyway. 

Also - did you try system.text_log?

**Comment by JackyWoo** [comment]
got it, thanks
