### ISSUE TITLE
MaterializeMySQL in Amazon RDS error

### ISSUE THREAD

**Issue by ziFieYu** [ClickHouse/ClickHouse#23541]
When using MaterializeMySQL to synchronize mysql, Clickhouse will execute [flush tables with read lock] in the master. This SQL is not supported in Amazon RDS, resulting in synchronization failure

**Comment by tavplubix** [comment]
Is there any other way to consistently dump all data from MySQL without using `FLUSH TABLES WITH READ LOCK`?
