### ISSUE TITLE
How many tables per database?

### ISSUE THREAD

**Issue by ramazanpolat** [ClickHouse/ClickHouse#23551]
Checking from the `store` directory, I can see that tables are assigned a 3 letter hex like those:

```
drwxr-x---  3 clickhouse clickhouse 4096 Apr 23 10:24 253/
drwxr-x---  3 clickhouse clickhouse 4096 Apr 21 13:31 35d/
drwxr-x---  3 clickhouse clickhouse 4096 Apr 23 11:03 39f/
drwxr-x---  3 clickhouse clickhouse 4096 Apr 21 13:31 41b/
```

Does that mean we can only have 2^12 =4096 tables for each database?

**Comment by den-crane** [comment]
Any number of tables.
`store` is not a database. 
3 letters folder is  just  the part of table's uuid 
```
3a9/3a9b4e1a-0135-4592-9397-00f4a79a0228/
f2e/f2ef9537-060a-4612-b54b-a446fd33ee5a/
```
