### ISSUE TITLE
Copying CollapsingMergeTree to another table results different row count

### ISSUE THREAD

**Issue by ramazanpolat** [ClickHouse/ClickHouse#23558]
I have a table `keyword` with `CollapsingMergeTree` engine which I want to duplicate.

Duplicating table:
```
create table keyword_NEW as keyword;
insert into keyword_NEW select * from keyword;
select count() from keyword = 25M rows
select count() from keyword_NEW = 21M rows
```
4M rows missing.

There were no inserts happening while duplicating the table and all external write operations were stopped (clickhouse server listens for only localhost connection).

I thought CollapsingMergeTree would actually *delete* rows based on `sign`.

But it seems like although they are deleted, count() still shows deleted rows.

Is this duplication safe? Does that mean my data is intact in `keyword_NEW` table?

**Comment by UnamedRus** [comment]
You need to compare:

select count() from keyword FINAL;
select count() from keyword_NEW FINAL;


de duplication is eventually, it's possible that you have some duplicated rows in main table, which are being deduplicated in new.
