### ISSUE TITLE
How to model a 1:N relationship with aggregation?

### ISSUE THREAD

**Issue by mauidude** [ClickHouse/ClickHouse#23560]
So I posted this on stackoverflow but it didn't seem to get any responses. Maybe someone here can help me.... Maybe nested types can help me here but I am not sure how those would aggregate...

Original stackoverflow question:

I have a series of events that I want to put into Clickhouse and they tie back to a single entity via an `id` field. Each event type has a different part of the entity and most of the event types occur once, but some occur multiple times. I am trying to figure out how to model this so that the table has one row (after an `OPTIMIZE`) to represent that entity (even though there are multiple events per entity).

My data is something like this, where event D is the one that can occur multiple times:
```
Event type A:
{
  "id": <string identifier>,
  "a": <data for field a>
  "aa": <data for field aa>
}

Event type B:
{
  "id": <string identifier>,
  "b": <data for field b>,
  "bb": <data for field bb>
}

Event type C:
{
  "id": <string identifier>,
  "c": <data for field c>,
  "cc": <data for field cc>
}

Event type D:
{
  "id": <string identifier>,
  "d": <data for field d>,
  "dd": <data for field dd>
}
```

What I want a table in Clickhouse to look like is something like this:

```
CREATE TABLE events
(
  id String,
  a Nullable(String),
  aa Nullable(String),
  b Nullable(String),
  bb Nullable(String),
  c Nullable(String),
  cc Nullable(String),
  d Nullable(Array(String)),
  dd Nullable(Array(String))
)
```
where the elements of column `d` and `dd` are ordered the same, e.g. `d[1]` and `dd[1]` should be from the same instance of event D.

What I am having trouble with is coming up with the correct engine that would give me this. I naturally went to the `AggregatingMergeTree` for this and using `id` as the sort key, but I don't know how to aggregate the fields from event D. I think it might be because of the apparent lack of an aggregate function that would aggregate values into an array of that type (e.g. aggregating `Nullable(String)` into `Array(String)`). 

Is there such a function or table engine that would accomplish what I'm trying to do or am I even thinking about this correctly? I realize I could write the D events to a separate table but I want to avoid a join if possible.

**Comment by l1t1** [comment]
groupArray()

**Comment by mauidude** [comment]
I did see that but the first line in the docs says `Values can be added to the array in any (indeterminate) order.` which I need the columns from event D to match in order. Is there away to use Nested types with groupArray? It was kind of confusing to me because from what I understand, Nested types are arrays themselves?

**Comment by l1t1** [comment]
groupArray 
Syntax: groupArray(x) or groupArray(max_size)(x)

Creates an array of argument values.
Values can be added to the array in any (indeterminate) order.

The second version (with the max_size parameter) limits the size of the resulting array to max_size elements. For example, groupArray(1)(x) is equivalent to [any (x)].
**In some cases, you can still rely on the order of execution. This applies to cases when SELECT comes from a subquery that uses ORDER BY.**

**Comment by l1t1** [comment]
eg.

with t as (select number n from system.numbers limit 100000),
t1 as (select n%20 x,count(*)c from t group by x),
t2 as (select toUInt8(x/4)x1,groupArray(c)ac from t1 group by x1)
--select t2.*,2 from t2
--union all
select x1% 3 x2,groupArray(ac) ac,3 from t2 group by x2
;

**Comment by melvynator** [comment]
Thank you @l1t1
