### ISSUE TITLE
Client: Cannot load data for command line suggestions

### ISSUE THREAD

**Issue by TheRoSS** [ClickHouse/ClickHouse#23577]
**Describe the bug** 
Когда сервер CH стоит на продакшн, обычно политика его обновления задаётся отделом поддержки. Обновление же локального клиента зачастую происходит автоматически из репозитория. В результате после одного обновления вылезла несовместимость клиента с сервером

```
$ clickhouse-client -h clickh-node.a                                                                                                                                                                                      07:11:
ClickHouse client version 21.4.4.30 (official build).
Connecting to clickh-node.a:9000 as user xxxx.
Connected to ClickHouse server version 19.14.6 revision 54425.

ClickHouse server version is older than ClickHouse client. It may indicate that the server is out of date and can be upgraded.

clickh-n5.a :) Cannot load data for command line suggestions: Code: 60, e.displayText() = DB::Exception: Received from clickh-node.a:9000. DB::Exception: Table system.storage_policies doesn't exist.. (version 21.4.4.30 (official build))
```

OS: Ubuntu 18.04

Кроме этой ошибки и не  работающей авто подстановки по табуляции, запросы на сервер работают нормально. До обновления хорошо работало всё. Проблема вылезла не при последнем обновлении, а несколько обновлений назад. Просто баг-репорт написал не сразу

**Expected behavior**
Клиент совместим с любыми версиями сервера

**Comment by alexey-milovidov** [comment]
Client is still usable with the server version 19.14 but suggestions won't work.
Server version 19.14 is not supported anymore and should be upgraded as soon as possible.

**Comment by alexey-milovidov** [comment]
If you don't want to see the error message about suggestions, run clickhouse-client with `-A` flag.
