### ISSUE TITLE
Bitwise operators

### ISSUE THREAD

**Issue by aCLr** [ClickHouse/ClickHouse#2358]
Очень хочется иметь возможность использовать битовые операторы (`&`, `|`), не только функции (`bidAnd`, `bitOr`). Сами в плюсы, к сожалению, не умеем,  :(

**Comment by alexey-milovidov** [comment]
Жалко символов. Хотя для совместимости с MySQL можно сделать.

**Comment by alexey-milovidov** [comment]
Implementing bitwise operators is risky, here's why:

- if we'd have bitwise operators `|` and `&`, the users may think (for a moment), we also have logical operators `||` and `&&`;
- but we have the string concatenation operator `||`, so it may lead to confusion.

Although MySQL and MS SQL Server have them, maybe it's worth doing.
Let's put this task on hold.
