### ISSUE TITLE
Integration with S2 Geometry library.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#23619]
https://s2geometry.io/

@Slach @UnamedRus what functions from this library you need the most?

**Comment by Slach** [comment]
I think
first of all function related to search Neighbors, Intersection, Union, Rectangles is required 

a good source for test cases is here
https://github.com/google/s2geometry/blob/master/src/python/pywraps2_test.py

**Comment by Slach** [comment]
Maybe data skip index with S2PointIndex type also will good idea

**Comment by filimonov** [comment]
convert lat/lng data to s2 Cell ID
  s2.CellIDFromLatLng 
  s2.LatLngFromDegrees
 
converting the area into s2 region - polygons converted to s2 using
s2.PointFromLatLng, s2.LatLngFromDegrees, s2.LoopFromPoints

circles are converted to s2 Cap using 
s2 PointFromLatLng, s2 LatLngFromDegrees  s1.ChordAngleFromSquaredLength s2.CapFromCenterChordAngle(point,radius))

**Comment by alexey-milovidov** [comment]
Available in 21.9.
