### ISSUE TITLE
Connection reset by peer, while writing to socket

### ISSUE THREAD

**Issue by chenchaocauc** [ClickHouse/ClickHouse#23625]
My Clickhouse cluster often has error logs，The content is as follows：
1、<Error> TCPHandler: Code: 210, e.displayText() = DB::Exception: Connection reset by peer, while writing to socket
2、I/O error: Broken pipe, while writing to socket
3、Unknown packet 0 from server 101.3.120.45:9000
I learned about some of the parameters set，like connect_timeout_with_failover_ms,  But it didn't work. 
Help me！！！

**Comment by filimonov** [comment]
If the client just drops the connection w/o waition for getting the whole responce you will can that effect. Check client side timeouts, and client code.
