### ISSUE TITLE
nullif function bug in version 20.6.9.1

### ISSUE THREAD

**Issue by phhcer** [ClickHouse/ClickHouse#23630]
```sql
-- ok
select toFloat32(null)

-- ok
select nullif('', '') is null

-- failed
select toFloat32(nullif('', '') 
```

err msg:
> Code: 72, e.displayText() = DB::Exception: Cannot read floating point value: Cannot parse Float32 from String (version 20.6.9.1 (official build))

**Comment by alexey-milovidov** [comment]
There is no such issue in recent versions: https://gh-api.clickhouse.tech/play?user=play#c2VsZWN0IHRvRmxvYXQzMihudWxsaWYoJycsICcnKSk=

**Comment by phhcer** [comment]
> There is no such issue in recent versions: https://gh-api.clickhouse.tech/play?user=play#c2VsZWN0IHRvRmxvYXQzMihudWxsaWYoJycsICcnKSk=

Yep! It seems like the reason of this issue is that the datatype from `toFloat32` is `Float32` but not `Nullable(FLoat32)`.
