### ISSUE TITLE
Different data between table and materialized view

### ISSUE THREAD

**Issue by orangeScorp** [ClickHouse/ClickHouse#23632]
The materialized view was created using the **POPULATE** keyword.
Engine of materialized view for distributed tables is **ReplicatedSummingMergeTree**.
Local table engine for distributed tables is **ReplicatedMergeTree**.
The aggregate field in the materialized view after creation contained larger (twice) value than the count of rows in the table.
The new data in the materialized view was calculated correctly.

DDL example:
------------------------------
**Table:**

CREATE TABLE test_db.test_table_local ON CLUSTER "test_cluster" (
`id` UInt64,
`date` UInt32,
`a1` String,
`a2` String
) ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/test_db/test_table_local', '{replica}')
PARTITION BY date
PRIMARY KEY (date, a1, a2)
ORDER BY (date, a1, a2)
SETTINGS index_granularity = 8192;

CREATE TABLE test_db.test_table  ON CLUSTER "test_cluster" (
`id` UInt64,
`date` UInt32,
`a1` String,
`a2` String
) ENGINE = Distributed(test_cluster, test_db, test_table_local, rand());

**Materialized view:**

CREATE MATERIALIZED VIEW test_db.test_view_local ON CLUSTER "test_cluster" (
`agg_count` UInt64,
`date` UInt32,
`a1` String,
`a2` String
) ENGINE = ReplicatedSummingMergeTree('/clickhouse/tables/{shard}/test_db/test_view_local', '{replica}')
PARTITION BY date
PRIMARY KEY (date, a1, a2)
ORDER BY (date, a1, a2)
SETTINGS index_granularity = 8192 POPULATE AS
SELECT
count() AS agg_count,
date,
a1,
a2
FROM test_db.test_table_local
GROUP BY a1, a2, date;

CREATE TABLE test_db.test_view on cluster "test_cluster" (
`agg_count` UInt64,
`date` UInt32,
`a1` String,
`a2` String
) ENGINE = Distributed('test_cluster', 'test_db', 'test_view_local', toInt64(date));

**Comment by ilejn** [comment]
I would start from making sure that cluster is defined properly, e.g. no shard/replica mess.
It might be reasonable to calculate records in test_db.test_table_local directly, not via distributed table.

**Comment by den-crane** [comment]
If you  execute  `CREATE MATERIALIZED VIEW t ON CLUSTER "test_cluster"  populate`  you execute populate TWICE.

I suggest to do not use **POPULATE** and use **TO** syntax.
https://den-crane.github.io/Everything_you_should_know_about_materialized_views_commented.pdf
