### ISSUE TITLE
Unable to run distributed alter on ReplicatedMergeTrees - 1.1.54380

### ISSUE THREAD

**Issue by jpiper** [ClickHouse/ClickHouse#2364]
It looks like there is an issue parsing the query as it thinks the database is "testtable" when it is "mydb"

```
ALTER TABLE mydb.testtable ON CLUSTER prod
ADD COLUMN 
frontend UInt8 AFTER servertype
```

```
Received exception from server (version 1.1.54380):
Code: 291. DB::Exception: Received from localhost:9000, 127.0.0.1
DB::Exception: Access denied to database testtable. 
```

**Comment by alesapin** [comment]
I have added a test exactly for this case https://github.com/ClickHouse/ClickHouse/pull/10404. Seems like this bug was fixed, but I don't know when :( I think we can close this issue.
