### ISSUE TITLE
Modifying clickhouse configuration parameter not working!

### ISSUE THREAD

**Issue by qianmoQ** [ClickHouse/ClickHouse#23674]
ClickHouse(`users.xml`) does not execute the set parameter logic after modifying the ClickHouse configuration parameter, but the configuration queried in the system table is valid and will only work if the service is restarted.

**Comment by alexey-milovidov** [comment]
What exactly do you modify? How to reproduce the issue?

**Comment by qianmoQ** [comment]
> What exactly do you modify? How to reproduce the issue?

Modify the 'max_partitions_per_insert_block' parameter and insert partitions greater than this value to reproduce

**Comment by filimonov** [comment]
Most probably you are doing something wrong. It is a user-level setting, you need to put it into users.xml inside the default profile. 
If it does not help - please show what exactly did you do, and how the file looks like. 

P.S. Relaxing that limitation (`max_partitions_per_insert_block`) is typically a very bad idea. Or not: it's VERY-VERY bad idea :) Rethink your partitioning schema instead - you want to do inserts in one or a few partitions at a time.
