### ISSUE TITLE
Document recommended procedure to take down nodes for maintenance

### ISSUE THREAD

**Issue by dqminh** [ClickHouse/ClickHouse#2368]
Currently we have a cluster consists of many shards, each shards contains 3 replicas. Would be nice to have some recommendations in official documentation on how to perform node maintenance in the cluster  ( upgrade / restart / etc. ) that causes the least disruptions in the cluster to distributed queries, inserts etc.

For example sometimes we observed that when a node comes up from maintenance and trying to catch up on replication and merges, queries sent to it can be slowed down significantly, causing max_concurrent_query limits to be exceeded.

**Comment by valyala** [comment]
@dqminh, we successfully use `chproxy` during maintenance / upgrade procedure as a workaround for the described issue.

[Chproxy](https://github.com/Vertamedia/chproxy/blob/master/README.md) automatically routes each query to the least loaded healthy replica. `Least loaded` means the replica with the minimum number of concurrently running queries at the moment. So, if a replica contains slow shard(s), then `chproxy` will automatically route more queries to faster replicas until slow shard(s) return to normal operation.

Just enumerate per-replica distributed table's addresses in the `clusters -> replicas` config section. See https://github.com/Vertamedia/chproxy/blob/master/README.md#clusters for details.

**Comment by DanRoscigno** [comment]
hold for new architecture docs so that we have a  concrete example

**Comment by alexey-milovidov** [comment]
The current recommendation is to not do anything special, just let the cluster handle it.
