### ISSUE TITLE
The question about removing "pie" in this MR: https://github.com/ClickHouse/ClickHouse/pull/8483

### ISSUE THREAD

**Issue by wangfeng2012** [ClickHouse/ClickHouse#23691]
Background: The product requires secure compilation options. "-pie" is used to generate position-independent executable programs to reduce memory usage. and in this case, it is difficult for attackers to use executable codes in the system to launch attacks.

Analysis: In MR (https://github.com/ClickHouse/ClickHouse/pull/8483), the "-pie" compilation option is added by default after the GCC version is upgraded. As a result, the addressing efficiency of the global constant table decreases. Therefore, the "pie" parameter is deleted. And this modification is not available in the ARM version.

Question: For security and performance impact analysis, please help evaluate whether the modification can be reverted. Thank you.

**Comment by alexey-milovidov** [comment]
`-pie` decreases performance 1% in average; in some functions performance decrease can be in order of 10%.
It also makes introspection and debugging harder.
It's not planned to add back `-pie` but you can create unofficial build of ClickHouse by yourself.
