### ISSUE TITLE
Functions not implemented with Int128, Int256, UInt256, and Decimal256.

### ISSUE THREAD

**Issue by MyroTk** [ClickHouse/ClickHouse#23703]
**Describe the unexpected behaviour**
A list of functions that do not support Int128, Int256, UInt256, or Decimal256.

**How to reproduce**
* Which ClickHouse server version to use
ClickHouse server version 21.5.1 revision 54447

* Functions and the types which they do not support.

gcd - Int256, UInt256, Decimal256
lcm - Int256, UInt256, Decimal256
modulo - Decimal256
moduloOrZero - Decimal256

arrayDifference - Int128, Int256, UInt256, Decimal256
arrayCumSum - Int128, Int256, UInt256, Decimal256
arrayCumSumNonNegative - Int128, Int256, UInt256, Decimal256

mapAdd - Int128, Int256, UInt256, Decimal256
mapSubtract - Int128, Int256, UInt256, Decimal256
mapPopulateSeries - Int128, Int256, UInt256, Decimal256

and - Int128, Int256, UInt256, Decimal256
or - Int128, Int256, UInt256, Decimal256
not - Int128, Int256, UInt256, Decimal256
xor - Int128, Int256, UInt256, Decimal256

pow - Int128, Int256, UInt256, Decimal256
power - Int128, Int256, UInt256, Decimal256
atan2 - Int128, Int256, UInt256, Decimal256
hypot - Int128, Int256, UInt256, Decimal256
intExp2 - Int256, UInt256, Decimal256
intExp10 - Int256, UInt256, Decimal256

roundDown - Int128, Int256, UInt256, Decimal256
roundToExp2 - Int256, UInt256, Decimal256
roundAge - Decimal256
roundDuration - Decimal256

bitTestAll - Int128, Int256, UInt256
bitTestAny - Int128, Int256, UInt256
bitRotateLeft - Int256, UInt256
bitRotateRight - Int256, UInt256
bitTest - Int256, UInt256
all bit functions do not support Decimal256

**Comment by alexey-milovidov** [comment]
Big integers is a feature under development.

**Comment by alexey-milovidov** [comment]
@MyroTk These functions are not supposed to be implemented.

**Comment by vzakaznikov** [comment]
@alexey-milovidov, are we going to document this?

**Comment by alexey-milovidov** [comment]
Better skip it.
