### ISSUE TITLE
Another case encountered "DB::Exception: Not found column xxx in block..."  (MaterializeMySQL) 

### ISSUE THREAD

**Issue by nickbaba2012** [ClickHouse/ClickHouse#23708]
I reported the issue #23470 a few days ago, now it is fine after upgrade to the latest stable version (version 21.4.5.46).
But encountered same error message "`Code: 10. DB::Exception: Received from localhost:9000. DB::Exception: Not found column type in block: while executing 'INPUT : 1 -> type Nullable(Int8) : 1'`" for another case...

Refer to below two screenshots, it's fine if the column **type** exits in both 'select' and 'where' clause.
![image](https://user-images.githubusercontent.com/44794448/116338305-1af1e100-a80e-11eb-83b4-ecf5e6201e33.png)
![image](https://user-images.githubusercontent.com/44794448/116338498-660bf400-a80e-11eb-95c9-eed301352a1b.png)

but encountered the exception if the column **type** only exists in 'where' clause:
![image](https://user-images.githubusercontent.com/44794448/116338467-5c828c00-a80e-11eb-9f81-20a551020f65.png)

**Comment by tavplubix** [comment]
Could you please provide `CREATE TABLE` statement of this table?

**Comment by nickbaba2012** [comment]
> Could you please provide `CREATE TABLE` statement of this table?

### MySQL statement:
CREATE TABLE `balance_change_record` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `type` tinyint(4) DEFAULT NULL,
  `value` decimal(10,4) DEFAULT NULL,
  `time` timestamp NULL DEFAULT NULL,
  `initiative_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `passivity_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `person_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `tenant_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `created_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `value_snapshot` decimal(10,4) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `balance_change_record_initiative_id` (`person_id`) USING BTREE,
  KEY `type` (`type`) USING BTREE,
  KEY `balance_change_record_type` (`time`) USING BTREE,
  KEY `initiative_id` (`initiative_id`) USING BTREE,
  KEY `balance_change_record_tenant_code` (`passivity_id`) USING BTREE,
  KEY `tenant_code` (`tenant_code`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1691049 DEFAULT CHARSET=utf8

### Clickhouse statement:
CREATE TABLE gaia_acc_ajidou.balance_change_record
(
    `id` Int64,
    `type` Nullable(Int8),
    `value` Nullable(Decimal(10, 4)),
    `time` Nullable(DateTime),
    `initiative_id` Nullable(String),
    `passivity_id` Nullable(String),
    `person_id` Nullable(String),
    `tenant_code` Nullable(String),
    `created_time` Nullable(DateTime),
    `updated_time` Nullable(DateTime),
    `value_snapshot` Nullable(Decimal(10, 4)),
    `_sign` Int8 MATERIALIZED 1,
    `_version` UInt64 MATERIALIZED 1,
    INDEX _version _version TYPE minmax GRANULARITY 1
)
ENGINE = ReplacingMergeTree(_version)
PARTITION BY intDiv(id, 18446744073709551)
ORDER BY (assumeNotNull(type), assumeNotNull(time), assumeNotNull(initiative_id), assumeNotNull(passivity_id), assumeNotNull(person_id), assumeNotNull(tenant_code), id)
SETTINGS index_granularity = 8192

**Comment by nickbaba2012** [comment]
I copied the table to another database, no issue was found.
Seems the exception only for MaterializeMySQL database
