### ISSUE TITLE
create table  engine=HDFS() failed  version 21.4.5.46 

### ISSUE THREAD

**Issue by zxsciro** [ClickHouse/ClickHouse#23715]
An error occurred on the server when create table engine = HDFS(),
could you give me an  example  of config.xml  which can support hadoop kerberos  authentication . thanks 

CH version 21.4.5.46 

CREATE TABLE hdfs_engine_table
(
    `name` String,
    `value` UInt32
)
ENGINE = HDFS('hdfs://xxx.xxx.xxx.xxx:8020/user/admin/data/hdfs_engine_table', 'CSV')

Code: 491. DB::Exception: Received from 127.0.0.1:9000. DB::Exception: URL "hdfs://xxxx.xxx.xxx.xxx:8020/user/admin/data/hdfs_engine_table" is not allowed in config.xml.

**Comment by alexey-milovidov** [comment]
Remove the section `<remote_url_allow_hosts>` from config.xml.
