### ISSUE TITLE
Fuzzer does not reinitialize connection after exception in client.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#23713]
https://clickhouse-test-reports.s3.yandex.net/23650/6ae4cc6ca779bc3c6cea243a79f73e46f9912438/fuzzer_ubsan/fuzzer.log

It leads to false positive reports.

**Comment by alexey-milovidov** [comment]
```
SELECT uniqStateForEachState([NULL])
```
cannot be deserialized by client.

**Comment by akuzm** [comment]
Added reinitialization here https://github.com/ClickHouse/ClickHouse/pull/23726
