### ISSUE TITLE
After alter table delete on a replicated table, the old deleted data cannot insert, but this is fixed in ck21.4.5.46.

### ISSUE THREAD

**Issue by zhangjmruc** [ClickHouse/ClickHouse#23728]
Would you please help to explain or point out which pull request fixed this issue?

The symptom is that, I cannot insert the old deleted data into the replicated table when I use alter... delete. However I can insert via truncate table or alter... drop partition. It looks like the issue is fixed in ck42.4.5.46.

---- how to reproduce:
-- 1. create table and insert on row.
create table t_rep(a int, b int, d Date) engine=ReplicatedMergeTree('/clickhouse/tables/test/t_rep/1','1') order by a partition by d;
insert into t_rep values(1,1,'2020-04-28');
select * from t_rep;

--2. use alter... delete
alter table t_rep delete where a=1;

--3. insert the same row again.
insert into t_rep values(1,1,'2020-04-28');

--4 There is still 0 rows in problematic version, like ck21.3. Expected 1 rows.
select * from t_rep;

#### wrong result
node231 :) insert into t_rep values(1,1,'2020-04-28');

Ok.

1 rows in set. Elapsed: 0.062 sec.

node231 :) select * from t_rep;

Ok.

**0 rows in set**. Elapsed: 0.101 sec.

### Correct result on ck21.4.5.46
node153 :) insert into t_rep values(1,1,'2020-04-28');

Ok.

1 rows in set. Elapsed: 0.067 sec.

node153 :) select * from t_rep;

┌─a─┬─b─┬──────────d─┐
│ 1 │ 1 │ 2020-04-28 │
└───┴───┴────────────┘

**1 rows in set.** Elapsed: 0.002 sec.

**Comment by den-crane** [comment]
Expected behavior. Insert deduplication.
https://clickhouse.tech/docs/en/development/architecture/#replication

https://clickhouse.tech/docs/en/operations/settings/settings/#settings-insert-deduplicate

**Comment by zhangjmruc** [comment]
@den-crane I already deleted the duplicated rows, actually I tried to delete all the row using "where 1". Then for the empty repliacted table, I can only insert new rows, but not work for exactly same old rows.

**Comment by zhangjmruc** [comment]
@den-crane I checked with the setting "insert-deduplicate", the problem issue works when value is 0 (Disabled). Thanks very much for your help!
