### ISSUE TITLE
Memory Limit (total) exceeded: would use 113.08 GiB 

### ISSUE THREAD

**Issue by IgorLelyakov** [ClickHouse/ClickHouse#23724]
Добрый день!
При выполнении операций Select и Select+Insert система выдает сообщение – «Memory Limit (total) exceeded: would use 113.08 GiB (attempt to allocate chunk of 11665622 bytes), maximum: 113.08 GiB (version 21.4.5.46)». 
В результате запроса получается одна таблица количество записей (строк) 116 000 000, количество столбцов (атрибутов) 375 (запрос во вложении). 
В запросе выполняется 205 операций SELECT, 179 операций JOIN, 36 операций UNION, 5 операций GROUP BY.
Есть ли какие-либо параметры, которые позволят выполнять операции Select и Select+Insert не увеличивая оперативную память и желательно без существенного замедления выполнения операций.  
Эти же действия ранее выполнялись на СУБД PostgreSQL, все операции выполнялись без ошибки по лимиту памяти, но очень медленно, после перехода на Click House все стало работать очень быстро (в 100 раз быстрее - замерял), но потребовало последовательного увеличения оперативной памяти начинали с 25ГБ оперативной памяти и довели до 120 ГБ оперативной памяти. Возможно ли как то управлять потреблением оперативной памяти. Хотелось бы увеличивать сложность и объем запроса, но что бы не выпадало сообщение об ошибке по лимиту памяти.
[SELECT - limit memory.docx](https://github.com/ClickHouse/ClickHouse/files/6390950/SELECT.-.limit.memory.docx)

**Comment by den-crane** [comment]
Версия КХ? Примеры запросов? DDL таблицы?

>SELECT - limit memory.docx

Да щаз, мы все побежали ворд покупать, ага.

**Comment by IgorLelyakov** [comment]
КХ версия 21.4.5..46
Пример запроса в формате тхт прилагаю,
формирую представление по результатам запроса и пытаюсь сохранить в виде таблицы, то-есть последовательно выбираю данные из разных таблиц соединяя их в итоге в одну большую таблицу
[SELECT - limit memory v3.txt](https://github.com/ClickHouse/ClickHouse/files/6392309/SELECT.-.limit.memory.v3.txt)

**Comment by IgorLelyakov** [comment]
[DDL.txt](https://github.com/ClickHouse/ClickHouse/files/6392403/DDL.txt)

DDL таблицы куда пытаюсь сохранить результат запроса

**Comment by den-crane** [comment]
Надо упрощать запрос, это слишком сложный запрос для КХ. КХ неоптимально выполняет такие JOIN

**Comment by IgorLelyakov** [comment]
спасибо
