### ISSUE TITLE
 Does ClickHouse rebalance the connection to zookeeper after zookeeper restarted

### ISSUE THREAD

**Issue by Zhile** [ClickHouse/ClickHouse#23725]
Suppose we have a ClickHouse cluster and a zookeeper cluster (with 3 nodes) . 
If one zookeeper node is restarted, the connections will be moved to the other two nodes. 
Do you know any ways to rebalance the connections to zookeeper without restart the whole ClickHouse cluster? 
zookeeper does have a method to let all the clients rebalancing their connections, seems ClickHouse doesn't have this? 
https://zookeeper.apache.org/doc/r3.5.4-beta/zookeeperReconfig.html#ch_reconfig_rebalancing

**Comment by den-crane** [comment]
Expected behavior. You don't need such rebalance. 
All ZK nodes do the same amount of work. It does not matter if all clients connected to only one ZK node or to 3 ZK nodes.

**Comment by IVitamin-C** [comment]
I modify zookeeper config in config.xml ,zk client reconnect.
<img width="1629" alt="image" src="https://user-images.githubusercontent.com/35019926/186566001-a2c02c83-7f36-40ed-8114-cda3ad93a292.png">
Metrics ZKUserExceptions,ObsoleteReplicatedParts and average write time  is lower than before the modification.
ZKUserExceptions:
<img width="743" alt="image" src="https://user-images.githubusercontent.com/35019926/186571067-189c9c43-16b4-46e3-a71c-ee8b7c83d9bc.png">
ObsoleteReplicatedParts:
<img width="742" alt="image" src="https://user-images.githubusercontent.com/35019926/186571132-c52ab5c5-fb7d-45ab-b695-85d015d7d7d9.png">
average write time:
<img width="754" alt="image" src="https://user-images.githubusercontent.com/35019926/186571251-2d46bffa-0507-4ce4-94fc-3bee178ff246.png">

I think clickhouse zk client need rebalance when the connection is uneven.

**Comment by IVitamin-C** [comment]
@den-crane

**Comment by azat** [comment]
> Expected behavior. You don't need such rebalance.
> All ZK nodes do the same amount of work. It does not matter if all clients connected to only one ZK node or to 3 ZK nodes.

Well, zookeeper should be scaled for reads, so this does make sense in some workloads actually.

There is an idea of implementing this but using manual commands - #41207
