### ISSUE TITLE
rabbitmq - how to change x-max-length for queues created by CH ?

### ISSUE THREAD

**Issue by khlystov** [ClickHouse/ClickHouse#23737]
rabbitmq - how to change x-max-length for queues created by CH ?
 
by default it looks like this: 
![image](https://user-images.githubusercontent.com/1534096/116422718-aee09e80-a848-11eb-9a98-0ce74f229ae0.png)

thank you!

**Comment by kssenii** [comment]
Now It is taken as `max(max_block_size, 100K)`. I will make a PR soon to allow user to configure any available setting for queues or exchanges.
For now you can modify `max_block_size` setting to make queue size less.
