### ISSUE TITLE
ALTER DELETE doesn't delete all data

### ISSUE THREAD

**Issue by Alekky09** [ClickHouse/ClickHouse#23734]
Hello,
I have a replicated MergeTree table across a few nodes.
I ran the following query:
```
ALTER TABLE table_name 
ON CLUSTER cluster 
DELETE WHERE condition=condition 
SETTINGS mutations_sync=2
```
The mutation appears as finished in the mutations table, but the data is still there. More over, whenever I do a SELECT query now, I get a different amount of rows back (either 150k rows or about 2.4mil rows).

If I run the DELETE again, it will only delete the rows created *after the first mutation*.

**Comment by den-crane** [comment]
select version();

select * from system.mutation where not is_done;

**Comment by Alekky09** [comment]
Heya,

`select version();` yields `21.3.5.42`

`select * from system.mutations where not is_done;` yields 0 rows

**Comment by den-crane** [comment]
Can you check `select * from system.mutations where not is_done;` at all replicas?

**Comment by Alekky09** [comment]
Looks like 2 of them are stalling the mutations... I did those DELETE queries a few days ago

**Comment by den-crane** [comment]
Share `select * from system.mutations where not is_done;`

**Comment by den-crane** [comment]
Did you ever restore your table? Did you use attach partition?

https://github.com/ClickHouse/ClickHouse/issues/18804

**Comment by Alekky09** [comment]
Rebooting the replicas fixed it!
