### ISSUE TITLE
max_concurrent_queries_for_user change requires restart

### ISSUE THREAD

**Issue by vsop-479** [ClickHouse/ClickHouse#23730]
I modified max_concurrent_queries_for_user in users.xml, and it changed in system.settings.
But users suffered  too many simultaneous queries with old max_concurrent_queries_for_user value, I had to restart the server to make new value effect.

**Comment by alexey-milovidov** [comment]
@vsop-479 

I checked the source code... the settings should apply but only when client reconnects.
Please check if it is the case.

BTW, what driver and interface the clients use?

**Comment by vsop-479** [comment]
I think we had restarted clients before restarted servers. I will check it again.
The driver is ClickHouse official jdbc.

**Comment by vsop-479** [comment]
@alexey-milovidov 
we restart the clients, but max_concurrent_queries_for_user does not applys immdiately, but applys after many hours passed.
The client is clickhouse-jdbc.

**Comment by vsop-479** [comment]
@alexey-milovidov 
We got "Too many simultaneous queries for user default" in stale setting, its a subquery requested by other clickhouse server with default user.
Maybe the connections between clickhouse servers should be rebuild to apply default settings？

**Comment by alexey-milovidov** [comment]
That's true - connections between servers in a cluster are long living.

**Comment by vsop-479** [comment]
> That's true - connections between servers in a cluster are long living.

Why do not ClickHouse uses new settings for every new query, and keeps settings just in the query context. But in every connection.
