### ISSUE TITLE
<Error> TCPHandler: Code: 432, e.displayText() = DB::Exception: Unknown codec family code: 226, Stack trace:

### ISSUE THREAD

**Issue by asipincasp** [ClickHouse/ClickHouse#23736]
Hello. After upgrade from version 12 to 21.4.5.46 i have a problem:

2021.04.27 08:54:10.365371 [ 30078 ] {3df4f238-9e17-44e6-8a70-804673e2430d} <Error> executeQuery: Code: 432, e.displayText() = DB::Exception: Unknown codec family code: 226 (version 21.2.5.5 (official build)) (from 10.89.70.138:34222) (in query: INSERT INTO pcs_stats.clicks (event_uuid, group_id, platform, os_name, os_version, device, browser, browser_version, country, city, event_date, event_time, url, is_bot, category, stream_type, audience_uuid, contact_uuid, send_time) VALUES ), Stack trace (when copying this message, always include the lines below):

0. DB::CompressionCodecFactory::get(unsigned char) const @ 0xe5cd729 in /usr/bin/clickhouse
1. DB::CompressedReadBufferBase::readCompressedData(unsigned long&, unsigned long&, bool) @ 0xe5bec5e in /usr/bin/clickhouse
2. DB::CompressedReadBuffer::readBig(char*, unsigned long) @ 0xe5be7f2 in /usr/bin/clickhouse
3. DB::DataTypeNumberBase<unsigned int>::deserializeBinaryBulk(DB::IColumn&, DB::ReadBuffer&, unsigned long, double) const @ 0xe74d7b3 in /usr/bin/clickhouse
4. DB::IDataType::deserializeBinaryBulkWithMultipleStreams(COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, DB::IDataType::DeserializeBinaryBulkSettings&, std::__1::shared_ptr<DB::IDataType::DeserializeBinaryBulkState>&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, COW<DB::IColumn>::immutable_ptr<DB::IColumn> > > >*) const @ 0xe77508c in /usr/bin/clickhouse
5. DB::NativeBlockInputStream::readData(DB::IDataType const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, DB::ReadBuffer&, unsigned long, double) @ 0xed7abed in /usr/bin/clickhouse
6. DB::NativeBlockInputStream::readImpl() @ 0xed7b706 in /usr/bin/clickhouse
7. DB::IBlockInputStream::read() @ 0xe691795 in /usr/bin/clickhouse
8. DB::TCPHandler::receiveData(bool) @ 0xf5c1562 in /usr/bin/clickhouse
9. DB::TCPHandler::receivePacket() @ 0xf5b97fc in /usr/bin/clickhouse
10. DB::TCPHandler::readDataNext(unsigned long const&, int const&) @ 0xf5bb68f in /usr/bin/clickhouse
11. DB::TCPHandler::processInsertQuery(DB::Settings const&) @ 0xf5b9d4e in /usr/bin/clickhouse
12. DB::TCPHandler::runImpl() @ 0xf5b2989 in /usr/bin/clickhouse
13. DB::TCPHandler::run() @ 0xf5c2409 in /usr/bin/clickhouse
14. Poco::Net::TCPServerConnection::start() @ 0x11b5fe2f in /usr/bin/clickhouse
15. Poco::Net::TCPServerDispatcher::run() @ 0x11b61841 in /usr/bin/clickhouse
16. Poco::PooledThread::run() @ 0x11c988e9 in /usr/bin/clickhouse
17. Poco::ThreadImpl::runnableEntry(void*) @ 0x11c9474a in /usr/bin/clickhouse
18. start_thread @ 0x7e25 in /usr/lib64/libpthread-2.17.so
19. __clone @ 0xf834d in /usr/lib64/libc-2.17.so

2021.04.27 08:54:10.365433 [ 30078 ] {3df4f238-9e17-44e6-8a70-804673e2430d} <Error> TCPHandler: Code: 432, e.displayText() = DB::Exception: Unknown codec family code: 226, Stack trace:

0. DB::CompressionCodecFactory::get(unsigned char) const @ 0xe5cd729 in /usr/bin/clickhouse
1. DB::CompressedReadBufferBase::readCompressedData(unsigned long&, unsigned long&, bool) @ 0xe5bec5e in /usr/bin/clickhouse
2. DB::CompressedReadBuffer::readBig(char*, unsigned long) @ 0xe5be7f2 in /usr/bin/clickhouse
3. DB::DataTypeNumberBase<unsigned int>::deserializeBinaryBulk(DB::IColumn&, DB::ReadBuffer&, unsigned long, double) const @ 0xe74d7b3 in /usr/bin/clickhouse
4. DB::IDataType::deserializeBinaryBulkWithMultipleStreams(COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, DB::IDataType::DeserializeBinaryBulkSettings&, std::__1::shared_ptr<DB::IDataType::DeserializeBinaryBulkState>&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, COW<DB::IColumn>::immutable_ptr<DB::IColumn> > > >*) const @ 0xe77508c in /usr/bin/clickhouse
5. DB::NativeBlockInputStream::readData(DB::IDataType const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, DB::ReadBuffer&, unsigned long, double) @ 0xed7abed in /usr/bin/clickhouse
6. DB::NativeBlockInputStream::readImpl() @ 0xed7b706 in /usr/bin/clickhouse
7. DB::IBlockInputStream::read() @ 0xe691795 in /usr/bin/clickhouse
8. DB::TCPHandler::receiveData(bool) @ 0xf5c1562 in /usr/bin/clickhouse
9. DB::TCPHandler::receivePacket() @ 0xf5b97fc in /usr/bin/clickhouse
10. DB::TCPHandler::readDataNext(unsigned long const&, int const&) @ 0xf5bb68f in /usr/bin/clickhouse
11. DB::TCPHandler::processInsertQuery(DB::Settings const&) @ 0xf5b9d4e in /usr/bin/clickhouse
12. DB::TCPHandler::runImpl() @ 0xf5b2989 in /usr/bin/clickhouse
13. DB::TCPHandler::run() @ 0xf5c2409 in /usr/bin/clickhouse
14. Poco::Net::TCPServerConnection::start() @ 0x11b5fe2f in /usr/bin/clickhouse
15. Poco::Net::TCPServerDispatcher::run() @ 0x11b61841 in /usr/bin/clickhouse
16. Poco::PooledThread::run() @ 0x11c988e9 in /usr/bin/clickhouse
17. Poco::ThreadImpl::runnableEntry(void*) @ 0x11c9474a in /usr/bin/clickhouse
18. start_thread @ 0x7e25 in /usr/lib64/libpthread-2.17.so
19. __clone @ 0xf834d in /usr/lib64/libc-2.17.so

**Comment by CurtizJ** [comment]
Please, can you show your table schema and specify what client do you use for inserts. Also, please, clarify versions: what is version 12 and you said, that you had upgrade to 21.4.5.46, but in log you have `version 21.2.5.5`

**Comment by asipincasp** [comment]
Andrey, we are update from |21.2.5.5 to |
|21.4.5.46 an monday.|

|schema|

|SHOW CREATE TABLE clicks

Query id: df0329f7-4272-4d5d-8cce-e5864f22aeaa
CREATE TABLE pcs_stats.clicks
(
`event_uuid` FixedString(60),
`group_id` UInt32,
`platform` String,
`os_name` String,
`os_version` UInt8,
`device` String,
`browser` String,
`browser_version` UInt8,
`country` String,
`city` String,
`event_date` Date,
`event_time` DateTime,
`url` String,
`is_bot` UInt8,
`cnt` UInt8 DEFAULT 1,
`category` String,
`stream_type` String,
`audience_uuid` FixedString(36),
`contact_uuid` FixedString(36),
`send_time` DateTime
)
ENGINE = SummingMergeTree(cnt)
PARTITION BY (stream_type, toYYYYMM(event_date))
ORDER BY (group_id, event_date, event_uuid, platform, os_name, 
os_version, device, browser, browser_version, country, city, url)
SETTINGS index_granularity = 8192
|

|
|

|We are using old version of this library 
https://github.com/kshvakov/clickhouse-client in old version of our service.
|

|
|

29.04.2021 04:24, Anton Popov пишет:

**Comment by asipincasp** [comment]
We are turned on log on our appliation and we can see, this error on 
commit transaction with many insert.

29.04.2021 04:24, Anton Popov пишет:

**Comment by CurtizJ** [comment]
But https://github.com/kshvakov/clickhouse-client is an empty repository.

**Comment by asipincasp** [comment]
with latest driver
https://github.com/ClickHouse/clickhouse-go/releases/tag/v1.4.3
same error

29.04.2021 20:20, Anton Popov пишет:

**Comment by alexey-milovidov** [comment]
Looks like the Go driver is sending incorrect data.
You have to create an issue in their repository.
