### ISSUE TITLE
cmake3 failed on branch v21.3.8.76 and centos7

### ISSUE THREAD

**Issue by playprogram111** [ClickHouse/ClickHouse#23748]
Make sure that `git diff` result is empty and you've just pulled fresh master. Try cleaning up cmake cache. Just in case, official build instructions are published here: https://clickhouse.yandex/docs/en/development/build/

**Operating system**
centos7
**Cmake version**
cmake3.13.1

**Ninja version**

**Compiler name and version**
gcc9 or gcc10

** clickhouse branch
v21.3.8.76 / v21.4

**Full cmake and/or ninja output**

Determining if the pthread_create exist failed with the following output:
Change Dir: /data1/dev/ch/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/gmake" "cmTC_57784/fast"
/usr/bin/gmake -f CMakeFiles/cmTC_57784.dir/build.make CMakeFiles/cmTC_57784.dir/build
gmake[1]: Entering directory `/data1/dev/ch/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_57784.dir/CheckSymbolExists.c.o
/usr/local/gcc/bin/gcc   -pipe -msse4.1 -msse4.2 -mpopcnt  -Wall     -o CMakeFiles/cmTC_57784.dir/CheckSymbolExists.c.o   -c /data1/dev/ch/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_57784
/usr/bin/cmake3 -E cmake_link_script CMakeFiles/cmTC_57784.dir/link.txt --verbose=1
/usr/local/gcc/bin/gcc   -pipe -msse4.1 -msse4.2 -mpopcnt  -Wall     -fuse-ld=gold -rdynamic -Wl,--no-undefined  -rdynamic CMakeFiles/cmTC_57784.dir/CheckSymbolExists.c.o  -o cmTC_57784 
CMakeFiles/cmTC_57784.dir/CheckSymbolExists.c.o:CheckSymbolExists.c:function main: error: undefined reference to 'pthread_create'
collect2: error: ld returned 1 exit status
gmake[1]: *** [cmTC_57784] Error 1
gmake[1]: Leaving directory `/data1/dev/ch/build/CMakeFiles/CMakeTmp'
gmake: *** [cmTC_57784/fast] Error 2

File /data1/dev/ch/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Performing C SOURCE FILE Test TUKLIB_PHYSMEM_SPECIAL failed with the following output:
Change Dir: /data1/dev/ch/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/gmake" "cmTC_b5885/fast"
/usr/bin/gmake -f CMakeFiles/cmTC_b5885.dir/build.make CMakeFiles/cmTC_b5885.dir/build
gmake[1]: Entering directory `/data1/dev/ch/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_b5885.dir/src.c.o
/usr/local/gcc/bin/gcc -D_ALL_SOURCE -D_GNU_SOURCE -D_POSIX_PTHREAD_SEMANTICS -D_TANDEM_SOURCE -D__EXTENSIONS__  -pipe -msse4.1 -msse4.2 -mpopcnt  -Wall  -w -DTUKLIB_PHYSMEM_SPECIAL   -o CMakeFiles/cmTC_b5885.dir/src.c.o   -c /data1/dev/ch/build/CMakeFiles/CMakeTmp/src.c
/data1/dev/ch/build/CMakeFiles/CMakeTmp/src.c:5:13: error: unknown type name ‘compile’
    5 |             compile error
      |             ^~~~~~~
/data1/dev/ch/build/CMakeFiles/CMakeTmp/src.c:5:13: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ at end of input
gmake[1]: *** [CMakeFiles/cmTC_b5885.dir/src.c.o] Error 1
gmake[1]: Leaving directory `/data1/dev/ch/build/CMakeFiles/CMakeTmp'
gmake: *** [cmTC_b5885/fast] Error 2

Source file was:

            #if defined(_WIN32) || defined(__CYGWIN__) || defined(__OS2__)                 || defined(__DJGPP__) || defined(__VMS)                 || defined(AMIGA) || defined(__AROS__) || defined(__QNX__)
            int main(void) { return 0; }
            #else
            compile error
            #endif
        
Performing C SOURCE FILE Test TUKLIB_PHYSMEM_AIX failed with the following output:
Change Dir: /data1/dev/ch/build/CMakeFiles/CMakeTmp

[CMakeError.log](https://github.com/ClickHouse/ClickHouse/files/6396152/CMakeError.log)

**Comment by alexey-milovidov** [comment]
Create a fresh system (use Docker if appropriate) and follow the instructions: https://github.com/ClickHouse/ClickHouse/blob/master/docs/en/development/build.md#how-to-build-clickhouse-on-any-linux-how-to-build-clickhouse-on-any-linux

**Comment by playprogram111** [comment]
Hi, I find the reason: The error is thorwed here, if comment this SEND_ERROR, cmake3 will passed

vim contrib/xz/CMakeLists.txt
if(NOT TUKLIB_CPUCORES_FOUND OR NOT TUKLIB_PHYSMEM_FOUND)
    # Use SEND_ERROR instead of FATAL_ERROR. If someone reports a bug,
    # seeing the results of the remaining checks can be useful too.
    #        message(SEND_ERROR
    #        "tuklib_cpucores() or tuklib_physmem() failed. "
    #        "Unless you really are building for a system where these "
    #        "modules are not supported (unlikely), this is a bug in the "
    #        "included cmake/tuklib_*.cmake files that should be fixed. "
    #        "To build anyway, edit this CMakeLists.txt to ignore this error.")
endif()

**Comment by playprogram111** [comment]
https://git.sailfishos.org/mirror/xz/commit/474320e9908786ba2021035f9013191e16cde08a

**Comment by playprogram111** [comment]
> Hi, I find the reason: The error is thorwed here, if comment this SEND_ERROR, cmake3 will passed
> 
> vim contrib/xz/CMakeLists.txt
> if(NOT TUKLIB_CPUCORES_FOUND OR NOT TUKLIB_PHYSMEM_FOUND)
> # Use SEND_ERROR instead of FATAL_ERROR. If someone reports a bug,
> # seeing the results of the remaining checks can be useful too.
> # message(SEND_ERROR
> # "tuklib_cpucores() or tuklib_physmem() failed. "
> # "Unless you really are building for a system where these "
> # "modules are not supported (unlikely), this is a bug in the "
> # "included cmake/tuklib_*.cmake files that should be fixed. "
> # "To build anyway, edit this CMakeLists.txt to ignore this error.")
> endif()

update submodule contrib/xz, then everything is ok
the reason is, contrib/xz is older than cmake3.13, they are uncompatible
