### ISSUE TITLE
output_format_json_array_of_rows server setting ignored

### ISSUE THREAD

**Issue by roignpar** [ClickHouse/ClickHouse#23741]
**Describe the bug**
Similar to #3489, the `output_format_json_array_of_rows` setting is ignored when set in `users.xml` settings. When set in config.xml, the server doesn't even start.
Setting through `clickhouse-client` works as expected.

**Does it reproduce on recent release?**
Yes, as described below.

**How to reproduce**
* ClickHouse server version 21.4.5 revision 54447 from docker image `yandex/clickhouse-server:21 (1c73a207247b)`
* HTTP interface as well as command line `ClickHouse client version 21.4.5.46 (official build)`
* Non-default settings:

additional `config.xml`:
```xml
<yandex>                                                
    <logger>                                            
        <level>none</level>                             
    </logger>                                           
                                                        
    <max_concurrent_queries>300</max_concurrent_queries>
                             
    <keep_alive_timeout>3600</keep_alive_timeout>       
</yandex>                                               
```
additional `users.xml`:
```xml
<yandex>                                                                          
    <profiles>                                                                    
        <default>                                                             
            <output_format_json_array_of_rows>1</output_format_json_array_of_rows>
        </default>                                                                
    </profiles>                                                                   
</yandex>                                                                         
```
* Queries to run that lead to unexpected result:
```sql
SELECT * FROM table_name
FORMAT JSONEachRow
```

**Expected behavior**
Would expect to get back a JSON array containing each result row as an object, as described in [documentation]:
```
[
  {...},
  {...},
  {...}
]
```
Instead, Clickhouse returns NDJSON:
```
{...}
{...}
{...}
```

[documentation]: https://clickhouse.tech/docs/en/operations/settings/settings/#output-format-json-array-of-rows

**Comment by alexey-milovidov** [comment]
Duplicate #3489.

**Comment by roignpar** [comment]
@alexey-milovidov thanks for looking into it!

As far as I can tell, although it is similar to #3489, it is not an exact duplicate as this refers to a different configuration parameter and it's reproducible through the HTTP Interface as well. You mentioned in #3489 that it was related to client not receiving settings from the server, but this shouldn't affect the HTTP interface, should it?

**Comment by alexey-milovidov** [comment]
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/56976.

**Comment by alexey-milovidov** [comment]
@roignpar, sorry for missing your comment.

I've tested it with the HTTP interface and found that everything works perfectly as of today:

```
$ echo "{profiles: {default: {output_format_json_array_of_rows: 1}}}" > users.d/test-23741.yaml
```

```
$ curl http://localhost:8123/ -d "SELECT * FROM numbers(10) FORMAT JSONEachRow"
[
{"number":"0"},
{"number":"1"},
{"number":"2"},
{"number":"3"},
{"number":"4"},
{"number":"5"},
{"number":"6"},
{"number":"7"},
{"number":"8"},
{"number":"9"}
]
```
