### ISSUE TITLE
How to properly investigate ClickHouse init process failed and Loading data parts error?

### ISSUE THREAD

**Issue by keshy7** [ClickHouse/ClickHouse#23756]
I am using ClickHouse (v.21.4.5.46) in Kubernetes with persistent volume on '/var/lib/clickhouse/' path. Whenever I have changes in my project and the pods are restarted (including ClickHouse), ClickHouse would not start and we encounter the error `ClickHouse init process failed.` If I delete the persistent volume files, the server starts successfully. 😕

I have enabled console logging and we were able to pull the logs:
[ClickHouse init process failed.txt](https://github.com/ClickHouse/ClickHouse/files/6397879/ClickHouse.init.process.failed.txt)

The last traces indicate that the data parts are being loaded. However, it suddenly stops loading and I cannot identify what causes the error and whether there are other reasons the server doesn't start.

May I ask for guidance how I should investigate further?

Thank you so much for your help!

**Comment by filimonov** [comment]
It cames from https://github.com/ClickHouse/ClickHouse/blob/c7bd69cc92b41ab6ab61b67956276baca0af1cbd/docker/server/entrypoint.sh#L117

That means you have some init DB script. And to run it docker entrypoint starts clickhouse, and wait up to configured timeout (default is 12 sec) to run those scripts.

Far from perfect... 

Options are: don't use init DB at all, or adjust the timeout variable.

Proper option: avoid running init scripts with every container start.

**Comment by keshy7** [comment]
This is very helpful! Thank you so much @filimonov!

**Comment by jastabile** [comment]
> It cames from
> 
> [ClickHouse/docker/server/entrypoint.sh](https://github.com/ClickHouse/ClickHouse/blob/c7bd69cc92b41ab6ab61b67956276baca0af1cbd/docker/server/entrypoint.sh#L117)
> 
> Line 117 in [c7bd69c](/ClickHouse/ClickHouse/commit/c7bd69cc92b41ab6ab61b67956276baca0af1cbd)
> 
>  tries=${CLICKHOUSE_INIT_TIMEOUT:-12} 
> That means you have some init DB script. And to run it docker entrypoint starts clickhouse, and wait up to configured timeout (default is 12 sec) to run those scripts.
> 
> Far from perfect...
> 
> Options are: don't use init DB at all, or adjust the timeout variable.
> 
> Proper option: avoid running init scripts with every container start.

Hey, I'm reviving this issue because I'm having the same issue everytime I want to redeploy or scale out clickouse-server on ECS. 
How can I avoid running init scripts with every container start? 

Because I'm not being able to scale
