### ISSUE TITLE
count  distinct on ordered field consumes more memory than needed

### ISSUE THREAD

**Issue by qingping209** [ClickHouse/ClickHouse#23765]
It seems that distinct count(x)  does not take ordering into account event if data is ordered by x, because I observe huge memory usage which is not necessary when counting ordered fields.

**Comment by filimonov** [comment]
Aggregate functions are not aware of ordering (and i doubt they will be in close future), you can try smth like:
```
Select count() from (select distrinct x from table)
```

Or
```
SET optimize_aggregation_in_order=1
Select count() from (select 1 from table group by x)
```

**Comment by qingping209** [comment]
> Select count() from (select distinct x from table)

why this can save memory?  It does not work for my case.

**Comment by qingping209** [comment]
> Select count() from (select distinct x from table)
this does not work in my case, neither local or distributed table;

> SET optimize_aggregation_in_order=1
> Select count() from (select 1 from table group by x)
this works for local table but not for distributed table

**Comment by filimonov** [comment]
> this does not work in my case

what exactly do you mean?

> this works for local table but not for distributed table

What exactly do you mean?

Does it say 'i will not work in that case?' :)
