### ISSUE TITLE
Bug in FLOAT comparator

### ISSUE THREAD

**Issue by 1Ridav** [ClickHouse/ClickHouse#23768]
**Describe the bug**
WHERE clause does not filter data as expected. I'm trying to filter by some FLOAT number, but keep getting wrong results

**Does it reproduce on recent release?**
Have not tested on recent releases

**How to reproduce**
Run this query
```sql
SELECT
  any(uuid) AS id,
  any(start_ts) AS start_ts,
FROM journal AS j
WHERE j.start_ts >= 1619675611
GROUP BY uuid
ORDER BY j.start_ts desc
LIMIT 0, 50
```
* Which ClickHouse server version to use
  ClickHouse server version 20.11.4 revision 54442
* Which interface to use, if matters
CLI
* Non-default settings
```sql
CREATE TABLE IF NOT EXISTS journal (
    start_ts FLOAT,
    uuid String,
) ENGINE = MergeTree()
ORDER BY uuid
TTL toDate(start_ts) + INTERVAL 180 DAY DELETE
```

Sample record in database, just one record.
I write my data to CH as floating number, but for some reason it is getting rounded(or floored) to integer
uuid | start_ts
 9adb4aeb-cc1b-4d33-94cb-418a517ed1fe │ 1619675600

* Queries to run that lead to unexpected result
```sql
SELECT
  any(uuid) AS id,
  any(start_ts) AS start_ts,
FROM journal AS j
WHERE j.start_ts >= 1619675611
GROUP BY uuid
ORDER BY j.start_ts desc
LIMIT 0, 50
```
I get this record even if it should not be returned
 9adb4aeb-cc1b-4d33-94cb-418a517ed1fe │ 1619675600
this record keep returning even if I try  WHERE j.start_ts >= 1619675620 or any other number in this range 1619675601-1619675640 (I'm not sure about precise boundaries)

**Expected behavior**
Query returned records which start_ts is bigger or equal to 1619675611
**Error message and/or stacktrace**
There is no error message or stacktrace

**Additional context**
I changed FLOAT to UInt32, this solved my current issue, but it seems to me like there is a bug in FLOAT comparator

**Comment by den-crane** [comment]
not a bug.

```
SELECT toFloat32('1619675611')

┌─toFloat32('1619675611')─┐
│              1619675600 │
└─────────────────────────┘
```
