### ISSUE TITLE
Same query, different result

### ISSUE THREAD

**Issue by ronhuizer** [ClickHouse/ClickHouse#23785]
Hi,

I'm pretty new to OLAP databases so I feel a bit like a lost lamb in an abattoir, but here goes...

I'm trying to get my first database to work. I got 1 server, 1 cluster, 1 database, 2 tables. The 2 tables are virtually the same, only the sorting (and primary) key differs.
In order to test the performance of both table configurations I loaded up both table with the same data, 1 year of vessel AIS data, 7.8 billion records in each table. Both tables contain the same amount of data and same amount of rows.

When I perform a bounding-box-like query on both tables, the answer from table 1 differs from table 2. When I perform the same query multiple times all the answers from table1 are the same, same goes for table2, so the differences between the 2 are consistent as well.

I don't get any warnings or error messages, just different results.
query: select * from AIS.dynamics where mmsi = 235089333 and lon > -45 and lat > -3

table one:
CREATE TABLE AIS.dynamics
(
    `message_type` Int8,
    `channel` FixedString(1),
    `cog` Nullable(Float32),
    `commstate` Int8,
    `heading` Nullable(Int16),
    `position_accuracy` Nullable(Int8),
    `lat` Float32,
    `lon` Float32,
    `point` String,
    `message_id` Int8,
    `mmsi` Int32,
    `nav_status` Int8,
    `raimflag` Int8,
    `rot` Nullable(Float32),
    `sog` Nullable(Float32),
    `source_type` Int8,
    `timestamp` DateTime
)
ENGINE = MergeTree
PRIMARY KEY (mmsi, timestamp)
ORDER BY (mmsi, timestamp)
SETTINGS index_granularity = 8192

table2:
CREATE TABLE AIS.dynamics3
(
    `message_type` Int8,
    `channel` FixedString(1),
    `cog` Nullable(Float32),
    `commstate` Int8,
    `heading` Nullable(Int16),
    `position_accuracy` Nullable(Int8),
    `lat` Float32,
    `lon` Float32,
    `point` String,
    `message_id` Int8,
    `mmsi` Int32,
    `nav_status` Int8,
    `raimflag` Int8,
    `rot` Nullable(Float32),
    `sog` Nullable(Float32),
    `source_type` Int8,
    `timestamp` DateTime
)
ENGINE = MergeTree
PRIMARY KEY (mmsi, lat, lon, timestamp)
ORDER BY (mmsi, lat, lon, timestamp)
SETTINGS index_granularity = 8192

**Comment by filimonov** [comment]
> just different results.
> query: select * from AIS.dynamics where mmsi = 235089333 and lon > -45 and lat > -3

What exactly do you mean by different results? Number or returned rows differ? Their order? Something else?

**Comment by alexey-milovidov** [comment]
No info was provided.
