### ISSUE TITLE
bitTest, bitTestAll, bitTestAny not utilizing multiple threads.

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#23791]
**Describe the situation**
bitTest, bitTestAll, bitTestAny doesn't use more than 1 thread.

**How to reproduce**

```
SET max_threads = 1;

SELECT bitTest(materialize(1000), 4)
FROM numbers_mt(1000000000)
FORMAT Null;

0 rows in set. Elapsed: 1.008 sec. Processed 1.00 billion rows, 8.00 GB (991.70 million rows/s., 7.93 GB/s.)

SET max_threads = 32;

SELECT bitTest(materialize(1000), 4)
FROM numbers_mt(1000000000)
FORMAT Null

0 rows in set. Elapsed: 1.003 sec. Processed 1.00 billion rows, 8.00 GB (997.04 million rows/s., 7.98 GB/s.)

set max_threads=1;

SELECT bitTestAll(materialize(1000), 4, 10)
FROM numbers_mt(1000000000)
FORMAT Null

0 rows in set. Elapsed: 1.007 sec. Processed 1.00 billion rows, 8.00 GB (992.99 million rows/s., 7.94 GB/s.)

 set max_threads=32;
 
SELECT bitTestAll(materialize(1000), 4, 10)
FROM numbers_mt(1000000000)
FORMAT Null

0 rows in set. Elapsed: 0.998 sec. Processed 1.00 billion rows, 8.00 GB (1.00 billion rows/s., 8.02 GB/s.)
```

**Comment by alexey-milovidov** [comment]
https://github.com/ClickHouse/ClickHouse/issues/19229#issuecomment-789350287

**Comment by alexey-milovidov** [comment]
Don't use FORMAT Null to test the performance.

**Comment by alexey-milovidov** [comment]
```
milovidov-desktop :) SELECT count() FROM numbers_mt(1000000000) WHERE NOT ignore(bitTest(materialize(1000), 4))

SELECT count()
FROM numbers_mt(1000000000)
WHERE NOT ignore(bitTest(materialize(1000), 4))

Query id: 807ed776-a304-4283-887b-a56f511b79ac

┌────count()─┐
│ 1000000000 │
└────────────┘

1 rows in set. Elapsed: 0.377 sec. Processed 1.00 billion rows, 8.00 GB (2.65 billion rows/s., 21.23 GB/s.)
```

**Comment by alexey-milovidov** [comment]
@UnamedRus All issues where you test performance that way will be closed immediately.

**Comment by akuzm** [comment]
> Don't use FORMAT Null to test the performance on synthetic benchmarks.

Why? It is used in a lot of performance tests. We have special tweak that doesn't send the result blocks to client in case of `format Null`, why is it different from calculating the same column for `WHERE` and discarding it?

**Comment by alexey-milovidov** [comment]
AFAIK, the pipeline with output is build,
there is single output processor,
and then there is an overhead in moving chunks between ports.

**Comment by alexey-milovidov** [comment]
If query performance is slower than around 10 GB/sec you can use queries with FORMAT Null safely.
But here we have 177.92 GB/s. for processing inside CPU cache and different effects matter.

**Comment by UnamedRus** [comment]
>  there is single output processor.
> But here we have 177.92 GB/s. for processing inside CPU cache and different effects matter (atomic ops in query pipeline).

Ok thank you. didn't know that.
