### ISSUE TITLE
row_number and system.number limit makes big result

### ISSUE THREAD

**Issue by l1t1** [ClickHouse/ClickHouse#23794]
with t1 as (select number id ,row_number()over(order by id) rn from system.numbers limit 3),
t2 as (select number+1 id ,row_number()over(order by id) rn from system.numbers limit 4),
t3 as (select number+2 id ,row_number()over(order by id) rn from system.numbers limit 4)
select *
from t1
left join t3 on t1.id = t3.id
left join t2 on t1.id = t2.id

Code: 158, e.displayText() = DB::Exception: Limit for rows or bytes to read exceeded, max rows: 10.00 billion, current rows: 10.00 billion: While executing Numbers (version 21.5.1.6541)

**Comment by l1t1** [comment]
this sql can run. 
with t1 as (select number id ,row_number()over(order by id) rn from (select * from system.numbers limit 3)),
t2 as (select number+1 id ,row_number()over(order by id) rn from (select * from system.numbers limit 4)),
t3 as (select number+2 id ,row_number()over(order by id) rn from (select * from system.numbers limit 4))
select *
from t1
left join t3 on t1.id = t3.id
left join t2 on t1.id = t2.id

**Comment by akuzm** [comment]
`ORDER BY` has to read the entire input, and `system.numbers` is endless. This is the expected behavior.
