### ISSUE TITLE
Basic Auth for http/url functions 

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#23803]
```
select * FROM url('https://guest:guest@jigsaw.w3.org/HTTP/Basic/','RawBLOB', 'a String');
```

That should work

**Comment by filimonov** [comment]
The same is needed for `format_avro_schema_registry_url`

```
2021.04.30 14:00:04.277754 [ 21 ] {} <Error> void DB::StorageKafka::threadFunc(size_t): Code: 86, e.displayText() = DB::Exception: Received error from remote server /schemas/ids/1. HTTP status code: 401 Unauthorized, body: {"error_code": 40101, "message": "Unauthorized"}
: while fetching schema id = 1, Stack trace (when copying this message, always include the lines below):

0. DB::assertResponseIsOk(Poco::Net::HTTPRequest const&, Poco::Net::HTTPResponse&, std::__1::basic_istream<char, std::__1::char_traits<char> >&, bool) @ 0xd418764 in /usr/bin/clickhouse
1. DB::AvroConfluentRowInputFormat::SchemaRegistry::fetchSchema(unsigned int) @ 0xf939a8f in /usr/bin/clickhouse
2. std::__1::pair<std::__1::shared_ptr<avro::ValidSchema>, bool> DB::LRUCache<unsigned int, avro::ValidSchema, std::__1::hash<unsigned int>, DB::TrivialWeightFunction<avro::ValidSchema> >::getOrSet<DB::AvroConfluentRowInputFormat::SchemaRegistry::getSchema(unsigned int)::'lambda'()>(unsigned int const&, DB::AvroConfluentRowInputFormat::SchemaRegistry::getSchema(unsigned int)::'lambda'()&&) @ 0xf938102 in /usr/bin/clickhouse
3. DB::AvroConfluentRowInputFormat::getOrCreateDeserializer(unsigned int) @ 0xf92bda3 in /usr/bin/clickhouse
4. DB::AvroConfluentRowInputFormat::readRow(std::__1::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn> > >&, DB::RowReadExtension&) @ 0xf92b4ef in /usr/bin/clickhouse
5. DB::IRowInputFormat::generate() @ 0xf944b36 in /usr/bin/clickhouse
6. DB::ISource::tryGenerate() @ 0xf8ceb05 in /usr/bin/clickhouse
7. DB::ISource::work() @ 0xf8ce82a in /usr/bin/clickhouse
8. DB::KafkaBlockInputStream::readImpl() @ 0xf4eb4be in /usr/bin/clickhouse
9. DB::IBlockInputStream::read() @ 0xe977305 in /usr/bin/clickhouse
10. DB::copyData(DB::IBlockInputStream&, DB::IBlockOutputStream&, std::__1::atomic<bool>*) @ 0xe995b0f in /usr/bin/clickhouse
11. DB::StorageKafka::streamToViews() @ 0xf4e1ebd in /usr/bin/clickhouse
12. DB::StorageKafka::threadFunc(unsigned long) @ 0xf4e0cbe in /usr/bin/clickhouse
13. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0xeb26232 in /usr/bin/clickhouse
14. DB::BackgroundSchedulePool::threadFunction() @ 0xeb28667 in /usr/bin/clickhouse
15. ? @ 0xeb298e1 in /usr/bin/clickhouse
16. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x862e3fd in /usr/bin/clickhouse
17. ? @ 0x8631fb3 in /usr/bin/clickhouse
18. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
19. clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
 (version 21.1.9.41 (official build))
```

**Comment by Swastyy** [comment]
@filimonov @alexey-milovidov Can I work on this? Pl assign it to me.

**Comment by filimonov** [comment]
Yes, sure. Please let us know if you will need some help or will stuck somewhere.

**Comment by Swastyy** [comment]
Hi @filimonov , My system showed "SSE 4.2 not supported" after running `$ grep -q sse4_2 /proc/cpuinfo && echo "SSE 4.2 supported" || echo "SSE 4.2 not supported"`. I have a WSL system in windows machine. Is it possible to install it anyways?

**Comment by filimonov** [comment]
I know some people run the ClickHouse executable on WSL, but i doubt you will be able to build it there. You should use VM with linux or better linux as main OS to be able to build ClickHouse. 

About sse4.2 - maybe it's again some issue with WSL. If you really don't have SSE 4.2 in cpu then build is possible, but if you have some old procesor compilation may take lot of time.

**Comment by michael1589** [comment]
I'm working on this issue. Can you pls let me try?

**Comment by michael1589** [comment]
Hi, I've fixed out. It's a bug maybe. Here's my CH response:
peng-liudemacbook-pro.local :) select * FROM url('https://guest:guest@jigsaw.w3.org/HTTP/Basic/','RawBLOB', 'a String');

SELECT *
FROM url('https://guest:guest@jigsaw.w3.org/HTTP/Basic/', 'RawBLOB', 'a String')

Query id: 4ed6de2c-ed2b-4945-bbe4-777554adbb1b

┌─a──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML//EN">
<html>
  <head>
    <title>Basic Authentication test page</title>

  </head>

<BODY BGCOLOR="white">
<P>
      <A HREF=".."><IMG SRC="/icons/jigsaw" ALT="Jigsaw" BORDER="0" WIDTH="212"
	  HEIGHT="49"></A><IMG SRC="/icons/jigpower.gif" WIDTH="94" HEIGHT="52" ALT="Jigsaw Powered !"
	BORDER="0" ALIGN="Right">

<P>
<HR>
<P>Your browser made it!
  </body>
</html>
 │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

1 rows in set. Elapsed: 1.114 sec.

**Comment by cwurm** [comment]
> The same is needed for `format_avro_schema_registry_url`

Basic Auth is not yet implemented for Confluent Schema Registry. Should there be a separate issue for this? It is especially relevant when using Confluent Cloud where the registry is always protected.

**Comment by filimonov** [comment]
> > The same is needed for `format_avro_schema_registry_url`
> 
> Basic Auth is not yet implemented for Confluent Schema Registry. Should there be a separate issue for this? It is especially relevant when using Confluent Cloud where the registry is always protected.

It is implemented but don't work when the user name or password have some special characters. Will be fixed soon, see the progress in https://github.com/ClickHouse/ClickHouse/pull/33299

**Comment by cwurm** [comment]
@filimonov I haven't tested it myself but I've been told it doesn't work and looking at the code making the HTTP request it does not look like it's using any credentials? https://github.com/ClickHouse/ClickHouse/blob/5dbf4eae36fa3e3e4edef4e638815afd4021efed/src/Processors/Formats/Impl/AvroRowInputFormat.cpp#L667-L674

**Comment by michael1589** [comment]
Case that user name or password have some special characters is PR pending. See https://github.com/ClickHouse/ClickHouse/pull/33299
