### ISSUE TITLE
Soft deletion

### ISSUE THREAD

**Issue by hagen1778** [ClickHouse/ClickHouse#23806]
I know that CH supports [ALTER DELETE](https://clickhouse.tech/docs/en/faq/operations/delete-old-data/#alter-delete) statement which is very helpful and cool! However, sometimes it could be quite impactful in terms of resources used to perform a mutation of data on disk. Especially, if rows selected for deletion are present in all stored data parts. 

Is it possible to just mark data "as deleted" instead of performing the actual mutation? I'd imagine data marked as deleted will be still present on disk but never returned by SELECT queries. Is it possible to implement such a "soft deletion" procedure in CH? Will CH accept external contribution if that is possible?

**Comment by UnamedRus** [comment]
https://github.com/ClickHouse/ClickHouse/issues/19627

**Comment by hagen1778** [comment]
Ah! Thank you, @UnamedRus! My finding skills failed me. Closing as duplicate.
