### ISSUE TITLE
cannot parse json kafka

### ISSUE THREAD

**Issue by yctn** [ClickHouse/ClickHouse#2381]
im sending json over kafka into clickhouse. but clickhouse give an cannot parse error. i manualy validated json on kafka and json seems to be valid. so i dont understand why i get this error.

2018.05.17 09:31:02.453233 [ 4 ] <Debug> StorageKafka (syslog): Started streaming to 1 attached views
2018.05.17 09:31:02.453294 [ 4 ] <Trace> StorageKafka (syslog): Creating formatted reader
2018.05.17 09:31:02.602382 [ 4 ] <Trace> UnionBlockInputStream: Waiting for threads to finish
2018.05.17 09:31:02.602425 [ 4 ] <Trace> UnionBlockInputStream: Waited for threads to finish
2018.05.17 09:31:02.602459 [ 4 ] <Trace> StorageKafka (syslog): KafkaBlockInputStream did not finish successfully, unsubscribing from assignments and rejoining
2018.05.17 09:31:02.643003 [ 4 ] <Error> void DB::StorageKafka::streamThread(): Code: 27, e.displayText() = DB::Exception: Cannot parse input: expected , before: time": "2018-05-17 09:24:58", "server_addr": "2001:1aa8:185::212:100", "hostname": "nl1-web213-40", "remote_addr": "2001:1aa8:185::212:100", "request_time": "0.: (at row 57291)
, e.what() = DB::Exception, Stack trace:

0. /usr/bin/clickhouse-server(StackTrace::StackTrace()+0x15) [0x82e3db5]
1. /usr/bin/clickhouse-server(DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)+0x21) [0x2cc1371]
2. /usr/bin/clickhouse-server() [0x8300a3b]
3. /usr/bin/clickhouse-server(DB::assertChar(char, DB::ReadBuffer&)+0x93) [0x8300c73]
4. /usr/bin/clickhouse-server(DB::JSONEachRowRowInputStream::read(std::vector<COWPtr<DB::IColumn>::mutable_ptr<DB::IColumn>, std::allocator<COWPtr<DB::IColumn>::mutable_ptr<DB::IColumn> > >&)+0xaac) [0x7fbe4ac]
5. /usr/bin/clickhouse-server(DB::BlockInputStreamFromRowInputStream::readImpl()+0xa3) [0x81d49f3]
6. /usr/bin/clickhouse-server(DB::IProfilingBlockInputStream::read()+0x2a9) [0x75d7c39]
7. /usr/bin/clickhouse-server(DB::KafkaBlockInputStream::readImpl()+0x9c) [0x819270c]
8. /usr/bin/clickhouse-server(DB::IProfilingBlockInputStream::read()+0x2a9) [0x75d7c39]
9. /usr/bin/clickhouse-server(DB::ParallelInputsProcessor<DB::UnionBlockInputStream<(DB::StreamUnionMode)0>::Handler, (DB::StreamUnionMode)0>::loop(unsigned long)+0x153) [0x7cf7ac3]
10. /usr/bin/clickhouse-server(DB::ParallelInputsProcessor<DB::UnionBlockInputStream<(DB::StreamUnionMode)0>::Handler, (DB::StreamUnionMode)0>::thread(MemoryTracker*, unsigned long)+0x218) [0x7cf8398]
11. /usr/bin/clickhouse-server() [0x8d9675e]
12. /lib/x86_64-linux-gnu/libpthread.so.0(+0x8063) [0x7f4dc05ca063]
13. /lib/x86_64-linux-gnu/libc.so.6(clone+0x6c) [0x7f4dbfffe62c]

**Comment by filimonov** [comment]
Can you find and provide that problematic row?

**Comment by filimonov** [comment]
I bet something wrong with quotes or backslashes in your data. 

There is only one case when that error can happen 
https://github.com/yandex/ClickHouse/blob/adfc743e060dca26d6fa0bcb7fd93320de0655c5/dbms/src/DataStreams/JSONEachRowRowInputStream.cpp#L104

And it can means that clickhouse thinks that it succesfully finished reading of some value of json property and expect next property to start i.e. for example something like that can produce such an error

Check for example what values have a field before which goes before `"time": "2018-05-17 09:24:58"`, and if the quotes and slashes are properly escaped. 

Minimal sample - backslash at the end of x is not escaped:
```
➜ echo '{"x":"a\","y":"b"}' | clickhouse-client --query='insert into abc format JSONEachRow'
Code: 27. DB::Exception: Cannot parse input: expected , before: y":"b"}\n: (at row 1)
```

**Comment by yctn** [comment]
Nothing goes before time. Time is the first thing i start a line with. which means the previous line was not closed proberly. but there are a few issues going on. when i juse a kafka consume and pipe it into jq i do not get any json errors. but still clickhouse-kafka gives me an error. would it be possible to print the bogus row? cause now i dont have information on what to debug exacly?

**Comment by millin** [comment]
I had the same error and I spent a lot of time searching for its causes.
Finally I discovered that this happens when getting empty message from Kafka :man_facepalming:
