### ISSUE TITLE
Make the subcolumn separator character for Nested and Array types configurable

### ISSUE THREAD

**Issue by gyfis** [ClickHouse/ClickHouse#23827]
**Use case**
We'd like to use dots `.` in column names and not have functionality issues with the internal usage of dots in `Nested` and `Array` types.

**Describe the solution you'd like**
If we extracted the dot `.` usage to a configuration with the same default, any ClickHouse user could modify this behavior based on their preferences, e.g. by setting `subcolumn_separator_character = '#'`.

**Describe alternatives you've considered**
An alternative is to simply use a different naming scheme for columns.

**Additional context**
I found these places where the dot is specifically used (but there are surely more of them)
https://github.com/ClickHouse/ClickHouse/blob/9f5cd35a6963cc556a51218b46b0754dcac7306a/src/Core/NamesAndTypes.cpp#L19-L27
https://github.com/ClickHouse/ClickHouse/blob/9f5cd35a6963cc556a51218b46b0754dcac7306a/src/DataTypes/Serializations/ISerialization.cpp#L126-L135

**Comment by alexey-milovidov** [comment]
Most likely this feature will not be implemented (due to increase of internal complexity).

It's expected that you should be able to refer to columns with dots if the name is wrapped in quotes:
```
"abc.def"
or
`abc.def`
```
But it is likely to break in some places in code.

**Comment by gyfis** [comment]
@alexey-milovidov Thank you for the swift response! I thought this could get implemented, because the dots are a specific-enough feature (only used by Nested and Array types), but I can see the argument against adding this flexibility to ClickHouse.

**Comment by alexey-milovidov** [comment]
The problem is that we plan to extend dots usage to support semistructured data.
E.g. you insert arbitrary JSON into a column, the data is transparently split by subcolumns and then you can query it like `a.b.c::String`.

**Comment by gyfis** [comment]
Gotcha! I think we can close this now, thanks for your time!
