### ISSUE TITLE
Optimize only changed partition on AggregatingMergeTree table engine

### ISSUE THREAD

**Issue by mbtolou** [ClickHouse/ClickHouse#23826]
Optimize only changed partition on AggregatingMergeTree table engine

Execution of the above command takes 30 minutes:

`
optimize table TABLE_NAME final;
`

but if only optimize changed partition :
onlye take 10 seconds : 

`
optimize table TABLE_NAME   PARTITION  201901 final
`

if ignore unchanged partition , optimize table is very fast.
thanks

**Comment by den-crane** [comment]
already implemented
https://github.com/ClickHouse/ClickHouse/issues/12759
https://github.com/ClickHouse/ClickHouse/pull/15939

**Comment by den-crane** [comment]
use setting 
  --optimize_skip_merged_partitions arg                            Skip partitions with one part with level > 0 in optimize final
