### ISSUE TITLE
add a procedure language

### ISSUE THREAD

**Issue by l1t1** [ClickHouse/ClickHouse#23834]
like oracle pl/sql
so we can do something like

declare 
   l_depnam varchar2(20) := 'testing'; 
   l_loc     varchar2(10) := 'Dubai'; 
   begin 
   execute immediate 'insert into dept values   (:1, :2, :3)' 
     using 50, l_depnam, l_loc; 
   commit; 
end;

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/11 https://github.com/ClickHouse/ClickHouse/issues/32

**Comment by jeongyoungbeom** [comment]
Hello
I don't know how to use it because I've never used it before.
Could you tell me an example of using this method?
