### ISSUE TITLE
assumeNotNull returns non-default value in case of there were some calculations over Null

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#23859]
**Describe the bug**
assumeNotNull returns non-default value in case of there were some calculations over Null

**Does it reproduce on recent release?**
Yes

**How to reproduce**
Clickhouse 21.6

```
WITH CAST(NULL, 'Nullable(UInt8)') AS column
SELECT
    column,
    assumeNotNull(column + 999) AS x


┌─column─┬─x─┐
│   ᴺᵁᴸᴸ │ 0 │
└────────┴───┘

WITH CAST(NULL, 'Nullable(UInt8)') AS column
SELECT
    column,
    assumeNotNull(materialize(column) + 999) AS x

┌─column─┬───x─┐
│   ᴺᵁᴸᴸ │ 999 │
└────────┴─────┘
```

**Comment by alexey-milovidov** [comment]
But it is how it supposed to work.

**Comment by alexey-milovidov** [comment]
`coalesce(x, 0)` or `ifNull(x, 0)` should be used instead.

`assumeNotNull` is for the case when it's assumed that the value is not NULL.
If assumption does not hold, the function returns implementation specific result.

In other words: `assumeNotNull` is an optimized function for rare special usages.

**Comment by UnamedRus** [comment]
Ok.

In that case docs looks a bit misleading:

```
Returned values

    The original value from the non-Nullable type, if it is not NULL.
    The default value for the non-Nullable type if the original value was NULL.
```

**Comment by alexey-milovidov** [comment]
I have corrected the docs: https://github.com/ClickHouse/ClickHouse/commit/41a6fd677e633124a2341b22d518307ed9e596e2

**Comment by UnamedRus** [comment]
Thank you
