### ISSUE TITLE
MATERIALIZED VIEW and AggregateFunction, count does not match

### ISSUE THREAD

**Issue by blanchonvincent** [ClickHouse/ClickHouse#23854]
Here is my table with a date and an ID along with the view that count the number of unique ID per day:

```
CREATE TABLE test_local on cluster abc(req_time DateTime, req_id UUID)
    ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/test_local', '{replica}')
        PARTITION BY toYYYYMM(req_time)
        ORDER BY (toYYYYMM(req_time));

CREATE TABLE test on cluster abc as test_local ENGINE = Distributed(abc, default, test_local, rand());
```

Then the materialized view:

```
CREATE MATERIALIZED VIEW test_mv_local
            on cluster abc (day Date, c AggregateFunction(uniq,UUID))
            ENGINE = ReplicatedAggregatingMergeTree('/clickhouse/tables/{shard}/test_mv_local', '{replica}')
                PARTITION BY toYYYYMM(day) ORDER BY (day)
AS
SELECT toDate(req_time) AS day, uniqState(req_id) AS c
FROM test_local
GROUP BY day;

CREATE TABLE test_mv on cluster abc as test_mv_local ENGINE = Distributed(abc, default, test_mv_local);
```

I inserted some millions of rows in the `test_local` table and run two queries:

* `SELECT day, uniqMerge(c) from test_mv group by day order by day desc limit 10;`:

```
┌────────day─┬─uniqMerge(c)─┐
│ 2021-05-02 │        45780 │
│ 2021-05-01 │        52677 │
│ 2021-04-30 │        58322 │
│ 2021-04-29 │        86853 │
│ 2021-04-28 │        64323 │
│ 2021-04-27 │        66857 │
│ 2021-04-26 │        61222 │
│ 2021-04-25 │        61674 │
│ 2021-04-24 │        63013 │
│ 2021-04-23 │        58919 │
└────────────┴──────────────┘
```

* `SELECT toDate(req_time), count(distinct req_id) from test group by toDate(req_time) order by toDate(req_time) desc limit 10;`:

```
┌─toDate(req_time)─┬─uniqExact(req_id)─┐
│       2021-05-02 │             45780 │
│       2021-05-01 │             52678 │
│       2021-04-30 │             58322 │
│       2021-04-29 │             86746 │
│       2021-04-28 │             64323 │
│       2021-04-27 │             66800 │
│       2021-04-26 │             61222 │
│       2021-04-25 │             61674 │
│       2021-04-24 │             63013 │
│       2021-04-23 │             58919 │
└──────────────────┴───────────────────┘
```

They give close results but not similar results and do not get why.

I have checked [this issue](https://github.com/ClickHouse/ClickHouse/issues/10326#issuecomment-616284409) by @den-crane that have great explanation about ReplicatedAggregatingMergeTree and why they needs AggregateFunctions. I also cannot use SimpleAggregatingFunctions since [there is no support for `uniq`](https://clickhouse.tech/docs/en/sql-reference/data-types/simpleaggregatefunction/).

I also noticed the poor performance: `0.896s` for the `test` table vs `0.410s` for the materialized view, confirming I do something wrong.

**Comment by itzikiusa** [comment]
I think it should be uniqExact and not uniq
This is what distinct does

**Comment by blanchonvincent** [comment]
@itzikiusa thank you for pointing this mistake out, that works now!
I'm using now `uniqExact`, `uniqExactState` and `uniqExactMerge`. However, the query on the view is now barely faster than the query on the table `0.827s` vs `0.746s`, probably because the [function looks more complex](https://clickhouse.tech/docs/en/sql-reference/aggregate-functions/reference/uniqexact/#agg_function-uniqexact) than `uniq`.

**Comment by den-crane** [comment]
There is no any sense to use uniqExact & AggregatingMergeTree. 
Try the opposite : hll12State / hll12Merge (or uniqCombine). hyperloglog structures bring % of errors, because they probabilities, but they use 1000 times less space and 1000 times faster.
