### ISSUE TITLE
RFC: LZ4 compressed clickhouse logs

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#23860]
I really love clickhouse logs. They helped me a lot of times, they 'tell stories' :) 

But on limited env (like tiny cloud instances) people often set the main log level from trace to information, or just disable it at all, keeping err log only - and motivation is very simple - logs are quite big, they take disk space & part of disk bandwidth - and that effect is very visible on tiny instances.

Maybe if we would compress them with LZ4 (streaming) it will be fewer reasons to disable them? 

What do you think of that? (I'm not totally convinced if it's good, because logs usually are expected to be straight and simple).

**Comment by alexey-milovidov** [comment]
That's a good feature. It can be beneficial to enable streaming lz4 compression and disable gz compression of rotated files.

Just to confirm, it it true that:
- lz4 framing format allows streaming compression with appends and it can decompress the data at any point of time?
- the integration in OS (at least Ubuntu), e.g. `less`, viewing inside `mc`, `grep` works with this format?

**Comment by filimonov** [comment]
```
apt-get update 
apt-get install lz4

# yes, it is appendable:
$ echo 1 |  lz4c  >> log.lz4 
$ echo 2 |  lz4c  >> log.lz4 
$ echo 3 |  lz4c  >> log.lz4

$ lz4cat log.lz4
1
2
3

# yes, there are nice command line wrappers: 

$ lz4cat log.lz4 | grep 2
2

$ lz4cat log.lz4 | less 

# rip grep support it out of the box (with -z flag)
apt-get install ripgrep

$ rg -z 2 log.lz4 
2:2

# midnight commander view supports lz4 files natively
```

See also manpages: http://manpages.ubuntu.com/manpages/bionic/man1/lz4.1.html

**Comment by filimonov** [comment]
But there is a question - how well it will be able to compress in streaming mode (i guess it will compress each line individually the compression will be poor).
