### ISSUE TITLE
materialized view clickhouse with optimize table

### ISSUE THREAD

**Issue by sanjaypocket52** [ClickHouse/ClickHouse#23872]
Insertion only tables works fine for the materialised view.
But once we do optimize table (multiple insertion same PK OPTIMIZE TABLE {} FINAL DEDUPLICATE ) materialised view is show wrong result.

is it not possible materialised view for optimize table or any idea how to proceed.

USE CASE -

insert into table2(id,user_id,amount,created_at) values(1,23,333,'2021-08-08 00:00:00')

CREATE MATERIALIZED VIEW table1
ENGINE = AggregatingMergeTree
PARTITION BY (YM) ORDER BY (YM)
POPULATE
AS SELECT
  toYYYYMM(created_at) AS YM,
  user_id,
  sum(amount) AS rake_amount
FROM table2
GROUP BY user_id,YM

insert into table2(id,user_id,amount,created_at) values(1,23,33,'2021-08-08 00:00:00')
OPTIMIZE TABLE table2 FINAL DEDUPLICATE

YM.          user_id.   rake
202105	103350	1000.0
202105	103350	500.0
202103	103350	16.64
202105	103350	1886.0

there should be only one row for fifth month but after OPTIMIZE table we have multiple entry into table 1.

**Comment by den-crane** [comment]
Works as expected.
MATERIALIZED VIEW is an insert trigger. It does not read the source table.

https://den-crane.github.io/Everything_you_should_know_about_materialized_views_commented.pdf

**Comment by sanjaypocket52** [comment]
Den, Any solution to aggregation solution perform for tables who got update / insertion.
