### ISSUE TITLE
Won't start on Mac OS X 10.15.7

### ISSUE THREAD

**Issue by ice1x** [ClickHouse/ClickHouse#23875]
You have to provide the following information whenever possible.

**Describe the bug**
Won't start on Mac OS X 10.15.7

**Does it reproduce on recent release?**
latest from git as discribed inside the instructions https://clickhouse.tech/docs/ru/development/build-osx/

**How to reproduce**
* ClickHouse server version to use 21.6.1.1
* Install using this instructions on Mac OS X 10.15.7 https://clickhouse.tech/docs/ru/development/build-osx/

**Expected behavior**
Possible to start service

**Error message and/or stacktrace**
 % ~/ClickHouse/build/programs/clickhouse-server       
Processing configuration file 'config.xml'.
Code: 107, e.displayText() = DB::Exception: Configuration file config.xml doesn't exist and there is no embedded config, Stack trace (when copying this message, always include the lines below):

<Empty trace>
 (version 21.6.1.1)

**Additional context**
No any info about config necessary content for start in https://clickhouse.tech/docs/ru/development/build-osx/

**Comment by alexey-milovidov** [comment]
You need to provide the config file in arguments:
`~/ClickHouse/build/programs/clickhouse-server --config-file ~/ClickHouse/programs/server/config.xml`

**Comment by ice1x** [comment]
Submitted this works fine.
May be it should be also inside the guide?

**Comment by alexey-milovidov** [comment]
You can edit the docs - press on the pencil icon at the top right corner.

**Comment by ice1x** [comment]
@alexey-milovidov pulled request: https://github.com/ClickHouse/ClickHouse/pull/23898/files
