### ISSUE TITLE
ionice for background moves between disks

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#23880]
Normally it's low priority io-only operation. See also https://github.com/ClickHouse/ClickHouse/pull/12076

**Comment by alexey-milovidov** [comment]
I thought `ionice` does not help. Do you have experiments proving the opposite?

**Comment by filimonov** [comment]
> Do you have experiments proving the opposite?

I think you meaned "compared to just setting niceness, on CFQ sheduler".

It's quite hard to model that scenario, and the priority of that is low.

But here the situation is a bit different - we don't support setting niceness for separate pool, so it will be comparison of 'non setting anything' vs. 'setting ionice'.

Option for setting thread niceness for the pool cal also be considered as option (it also adjusts ionice automatically, while can not set idle priority).

On cqf it should work for all reads and for synchronious writes (for async writes flushing happens outside of the program context)

**Comment by alexey-milovidov** [comment]
Ok.

I'm afraid of adding more settings without good reasons.
Many clients tend to adjust some settings for the reasons of fear, uncertainty and doubt.

**Comment by alexey-milovidov** [comment]
I also don't like when users have to tune ClickHouse instead of using default settings.

**Comment by filimonov** [comment]
Btw: this is not a my idea (and i have no plans to work on that in near future).

That subject popped up during some discussions (some users were asking about that) and i decided it's worth to have it in the backlog (even if it will not be implemented in the close future).

**Comment by alexey-milovidov** [comment]
Another idea is to add IO throttling for merges and moves. E.g. merges and moves occupy not more than 50% IO bandwidth.

**Comment by filimonov** [comment]
> Another idea is to add IO throttling for merges and moves. E.g. merges and moves occupy not more than 50% IO bandwidth.

Static throttling is not very nice: if clickhouse has nothing more important to do (no running queries) - why should we make merges / moves slower. Because of that something like priorities (or more granular resource control) sounds more interesting.

In general, normally foreground tasks (queries) are more important (well maybe unless it's delayed insert - then the priority of that can be lower than background merge).
