### ISSUE TITLE
OPTIMIZE TABLE <table> PARTITION <part> moves data to another disk

### ISSUE THREAD

**Issue by mindrb** [ClickHouse/ClickHouse#23892]
**Describe the bug**
When running command `optimize table table1 on cluster ourcluster partition 20210504` some partitions from this table and even from other tables are moved from ssd to hdd disks (storage configuration is below).
Fast disk has plenty of empty space. It is less than 70% used.

table1 is 
```
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/dbname/table1', '{replica}')
PARTITION BY toYYYYMMDD(time_stamp)
SETTINGS storage_policy = 'ssd_hdd';
```

**Does it reproduce on recent release?**
Almost the latest release - 21.4.5.46

**How to reproduce**
Run OPTIMIZE command. The problem is that behaviour is not 100% reproducible. Sometimes OPTIMIZE command runs as expected. Sometimes it moves only partitions on the same table. Sometimes moves partitions even from another table.

**Expected behavior**
I expect that OPTIMIZE TABLE command would not move data from one disk to another when there is enough space on the fast disk.

**Additional context**
```
    <storage_configuration>

        <disks>
            <ssd> <!-- disk name -->
                <path>/ch/fast/data/</path>
            </ssd>
            <hdd>
                <path>/ch/slow/data/</path>
            </hdd>
        </disks>

        <policies>
            <ssd_hdd>
                <volumes>
                    <hot>
                        <disk>ssd</disk>
                    </hot>
                    <cold>
                        <disk>hdd</disk>
                    </cold>
                </volumes>
                <move_factor>0.2</move_factor>
            </ssd_hdd>
        </policies>

    </storage_configuration>
```
```
SELECT * FROM storage_policies
┌─policy_name─┬─volume_name─┬─volume_priority─┬─disks───────┬─volume_type─┬─max_data_part_size─┬─move_factor─┬─prefer_not_to_merge─┐
│ default     │ default     │               1 │ ['default'] │ JBOD        │                  0 │           0 │                   0 │
│ ssd_hdd     │ hot         │               1 │ ['ssd']     │ JBOD        │                  0 │         0.2 │                   0 │
│ ssd_hdd     │ cold        │               2 │ ['hdd']     │ JBOD        │                  0 │         0.2 │                   0 │
└─────────────┴─────────────┴─────────────────┴─────────────┴─────────────┴────────────────────┴─────────────┴─────────────────────┘

```

**Comment by den-crane** [comment]
Check CH log for "having unreserved " messages around that merges.

This is expected behaviour. Because merges book twice space on a disk, probably it was 0 free space available in MERGE POOL at hot disk.

>It is less than 70% used.

probably it was 0% in the MERGE POOL

**Comment by mindrb** [comment]
Thank you for the clarification.

No such messages in CH log. But that is maybe because I reduced logging to `<level>information</level>`.

Where could I read about this MERGE POOL and it's settings?

So if my partition is ~20GB in total I need additional ~40GB on the fast disk for the OPTIMIZE to succeed without moving data to slow disk? Or ~20GB?

**Comment by den-crane** [comment]
You need number of simultaneous merges *  20*2 + move_factor 0.2

**Comment by mindrb** [comment]
Thank you. Clear now. Also did some tests.

I suggest to improve [OPTIMIZE documentation](https://clickhouse.tech/docs/en/sql-reference/statements/optimize/). Important nuance is that to optimize one 20GB partition I need up to 40GB of empty space. But out of those 40GB 20GB will be released into OS after operation but other 20GB will be freed only in ~8 minutes. So if I decide to optimize 5 partitions 20GB each I need not 40GB but 120GB of free space. Which will be freed only after few minutes.
