### ISSUE TITLE
Kafka engine producer dynamic query

### ISSUE THREAD

**Issue by kullanici0606** [ClickHouse/ClickHouse#23895]
I am trying Kafka engine producer (i.e insert data to clickhouse, consume from kafka). 
In my case, I need clickhouse to produce events based on some dynamic condition.
So I followed [this tutorial](https://altinity.com/blog/2020/5/21/clickhouse-kafka-engine-tutorial) but changed the materialized view like this:

```
CREATE MATERIALIZED VIEW readings_high_queue_mv_2 TO readings_high_queue2 AS　
    SELECT readings_id, time, temperature, _key 
       FROM readings 　
       WHERE toFloat32(temperature) <= (select toFloat32(MAX(temperature)) from my_readings);
```

readings_high_queue2 table (kafka engine):
```
CREATE TABLE readings_high_queue2 ( 
    readings_id Int32, 
    time DateTime, 
    temperature Decimal(5,2)
   ) ENGINE = Kafka SETTINGS 
       kafka_broker_list = 'localhost:9092',  
       kafka_topic_list = 'readings_high2',
       kafka_group_name = 'readings_high_consumer_group2',
       kafka_format = 'CSV',
       kafka_max_block_size = 1048576;
```

my_readings table:
```
CREATE TABLE my_readings (
     readings_id Int32, 
     temperature Decimal(5,2),
     _key String) 
     ENGINE MergeTree ORDER BY temperature;
```

Is this kind of usage supported by Clickhouse? Because when I insert a new value to my_readings table (i.e change max value) previously inserted rows which satisfy current but not previous max condition are not produced as Kafka events.

Example:
```
INSERT INTO my_readings(readings_id, temperature) VALUES(1, 25); -- max value is 25

INSERT INTO readings(readings_id, time, temperature, _key) VALUES(1, '2020-05-16 23:55:44', 24.20, '0');
INSERT INTO readings(readings_id, time, temperature, _key) VALUES(1, '2020-05-16 23:55:45', 30.15, '0');
```

First insert is produced as event since it is less than max value and can be consumed:
```
$ bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic readings_high2
1,"2020-05-16 23:55:44",23.20
```
Second one is not produced since it is greater than current max value (i.e 25) and therefore no event is producted.

Now I update the max value:
```
INSERT INTO my_readings(readings_id, temperature) VALUES(1, 35); -- max value is now 35
```
I expect the following event:
`1, '2020-05-16 23:55:45', 30.15`
but no event is produced.

Is this kind of use case supported or does Clickhouse only support producing events on insert?

Clickhouse version: 21.4.4.30
Kafka version: 2.13-2.8.0

**Comment by den-crane** [comment]
it's expected behaviour. Mat.View watches inserts only into the left table (readings in your case).

https://den-crane.github.io/Everything_you_should_know_about_materialized_views_commented.pdf

**Comment by kullanici0606** [comment]
Thanks a lot for both answer and the document.
