### ISSUE TITLE
clickhouse-client error

### ISSUE THREAD

**Issue by miladstar77** [ClickHouse/ClickHouse#23891]
Hello Dears

when I want to use clickhouse-client in interactive mode it shows killed and its very slow
like this :
clickhouse.:~# clickhouse-client
ClickHouse client version 21.4.6.55 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 21.4.6 revision 54447.

clickhouse:) select 1
Killed
could you please tell me what can i do ?

**Comment by den-crane** [comment]
Do you use WindowsForLinux?

**Comment by miladstar77** [comment]
no ,
