### ISSUE TITLE
HTTP request with an empty header value results in bad request response

### ISSUE THREAD

**Issue by marekbecka** [ClickHouse/ClickHouse#23901]
Clicktail installed from provided .deb package (version 1.0.20180402) generates HTTP requests like:

`POST /?query=INSERT+INTO+clicktail.apache_log+FORMAT+JSONEachRow HTTP/1.1`
`Host: XXX:8123`
`User-Agent: libclick-go/1.4.0 clicktail/dev (regex)`
`Content-Length: 2425`
`Authorization: Basic XXX`
`Content-Encoding: gzip`
`Content-Type: application/json`
`X-Honeycomb-Team: `
`Accept-Encoding: gzip`

Header X-Honeycomb-Team contains only space before terminal characters:
`58 2d 48 6f 6e 65 79 63 6f 6d 62 2d 54 65 61 6d 3a 20 0d 0a`

Clickhouse server 21.4.5.46 doesn't accept those requests and returns: 
`HTTP/1.1 400 Bad Request`

There is no requirement in RFC 7230 https://tools.ietf.org/html/rfc7230#section-3.2 for field-value to contains any data. Shouldn't be those requests accepted?

**Comment by alexey-milovidov** [comment]
Yes, I think we should accept it.

**Comment by alexey-milovidov** [comment]
If we simply remove these two lines it will work as expected:
https://github.com/ClickHouse/ClickHouse/blob/master/src/Server/HTTP/ReadHeaders.cpp#L71

**Comment by abyss7** [comment]
Yes, it looks like the code is non-conformant without a reason.

**Comment by kubantsev** [comment]
> @alexey-milovidov 
> If we simply remove these two lines it will work as expected:
> https://github.com/ClickHouse/ClickHouse/blob/master/src/Server/HTTP/ReadHeaders.cpp#L71

Nope, it will fails further on `ch == '\n'` as `skipWhitespaceIfAny(in, true);` skips `\r` too

**Comment by clowdrgn** [comment]
Same question in #24268 , hope to fix it soon
