### ISSUE TITLE
"Unsupported aggregate function argMax" error when using it with SimpleAggregateFunction

### ISSUE THREAD

**Issue by nkolotov** [ClickHouse/ClickHouse#23907]
**Describe the bug**
[Documentation for function `argMax`](https://clickhouse.tech/docs/ru/sql-reference/aggregate-functions/reference/argmax/) suggest that is it helpful when used with `SimpleAggregateFunction`:
>Удобно использовать для работы с SimpleAggregateFunction.

However an attempt to do so causes an error that `argMax` is an unsupported aggregate function.

**Does it reproduce on recent release?**
should be reproducible with 21.4.6.55
[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

**How to reproduce**
run docker container using fresh ClickHouse image:
```
docker run --rm -t -i --name=ch --ulimit nofile=262144:262144 yandex/clickhouse-server
```
execute query using ClickHouse client:
```
docker run -it --rm --link ch:clickhouse-server yandex/clickhouse-client --host clickhouse-server
ClickHouse client version 21.4.6.55 (official build).
Connecting to clickhouse-server:9000 as user default.
Connected to ClickHouse server version 21.4.6 revision 54447.

434de4405058 :) CREATE TABLE test ( a SimpleAggregateFunction(argMax, UInt8, UInt64) ) ENGINE = AggregatingMergeTree PARTITION BY a ORDER BY a

CREATE TABLE test
(
    `a` SimpleAggregateFunction(argMax, UInt8, UInt64)
)
ENGINE = AggregatingMergeTree
PARTITION BY a
ORDER BY a

Query id: 66663518-96f6-4a8c-989b-29d92ff360d3


0 rows in set. Elapsed: 0.003 sec. 

Received exception from server (version 21.4.6):
Code: 36. DB::Exception: Received from clickhouse-server:9000. DB::Exception: Unsupported aggregate function argMax, supported functions are any,anyLast,min,max,sum,sumWithOverflow,groupBitAnd,groupBitOr,groupBitXor,sumMap,minMap,maxMap,groupArrayArray,groupUniqArrayArray.
```

**Expected behavior**
I was expecting table to be successfully created or at least not complain about `argMax` being unsupported.

**Additional context**
I thought that maybe i'm missing something (which won't be surprising since documentation doesn't provide an example of `argMax` use along with `SimpleAggregateFunction`), however quick search reviled that [neither `argMax` or `argMin` are listed among supported aggregate functions for DataTypeCustomSimpleAggregateFunction](https://github.com/ClickHouse/ClickHouse/blob/7ae8938b6948507ad211265ae0a0600e4d214fe0/src/DataTypes/DataTypeCustomSimpleAggregateFunction.cpp#L30) so either documentation is misleading or `checkSupportedFunctions` implementation is incorrect.

**Comment by den-crane** [comment]
Try Tuple

```
CREATE TABLE test
(
    `a` SimpleAggregateFunction(argMax, Tuple(UInt8, UInt64))
)
ENGINE = AggregatingMergeTree
PARTITION BY a
ORDER BY a
```

**Comment by den-crane** [comment]
You should never use `PARTITION BY a ORDER BY a`  SimpleAggregate in PARTITION/ORDER By

**Comment by nkolotov** [comment]
> Try Tuple
> 
> ```
> CREATE TABLE test
> (
>     `a` SimpleAggregateFunction(argMax, Tuple(UInt8, UInt64))
> )
> ENGINE = AggregatingMergeTree
> PARTITION BY a
> ORDER BY a
> ```

This returns `DB::Exception: Aggregate function argMax requires two arguments.`

**Comment by UnamedRus** [comment]
Support for argMax in SimpleAggregateFunction was removed here: https://github.com/ClickHouse/ClickHouse/pull/23393

Because it has crash: https://github.com/ClickHouse/ClickHouse/issues/22384

**Comment by oxygenkun** [comment]
For those who want to use `argMax` with -SimpleState, change `argMaxState(arg, val)` to `maxSimpleState(Tuple(val, arg))` (Logically, they are not equivalent, but the results are the same).

**Comment by UnamedRus** [comment]
```
maxSimpleState(Tuple(val, arg))
```

Sorting by tuple with 2 values is much slower.

**Comment by oxygenkun** [comment]
> Sorting by a tuple with 2 values is much slower.

Yup. But considering using it with Materialized View, the doc says `SimpleAggregateFunction(name, types_of_arguments…) data type stores the current value of the aggregate function, and does not store its full state as AggregateFunction dose`, which means `SimpleAggregateFunction` will process less data than `AggregateFunction`. Which one is faster cannot be accurately predicted.

Test in a usage scenario where I use a lot of `argMax` results and the base table will update every day. The processing data size with the `AggregateFunction`  table is much larger than only using the `SimpleAggregateFunction` columns table, and the former computing elapsed is slightly slower than the latter.
