### ISSUE TITLE
kuberentes health check gets 502 error on http 8123 port

### ISSUE THREAD

**Issue by electrical** [ClickHouse/ClickHouse#23904]
**Describe the unexpected behaviour**
In kubernetes we run a health check on port 8123 to verify the service is up.
We often receive a 502 error back from Clickhouse which is unexpected.

**How to reproduce**
More details: https://github.com/Altinity/clickhouse-operator/issues/654
Versions tried: 20.8.12.2 & 21.3.6.55

**Expected behavior**
Expect it to give back a 200 code and 'Ok.' message

**Error message and/or stacktrace**
No errors have been found so far. If further debugging is possible i'm happy to follow up.

**Comment by alexey-milovidov** [comment]
Do you use any proxy servers in front of ClickHouse?
What do you see in ClickHouse logs?

**Comment by alexey-milovidov** [comment]
ClickHouse never responds with HTTP 502.

**Comment by electrical** [comment]
Hi, The livecheck connects directly to the docker container. I haven't seen anything in the clickhouse server logs so far.
I had it running on debug level but had to lower it to informational as the logs were getting to big.

**Comment by alexey-milovidov** [comment]
If you don't see these requests in ClickHouse logs, it must be not ClickHouse, who responses with 502 code.

**Comment by electrical** [comment]
I've tried to check what I can. In the meantime the error actually disappeared which is super confusing since it's been around for quite a long time.
Going to close this for now. If it happens again I'll try to do more digging and open a new issue.
Thank you for the assistance.
