### ISSUE TITLE
Empty `TE` HTTP 1.1 request header results to `400 Bad Request`

### ISSUE THREAD

**Issue by kubantsev** [ClickHouse/ClickHouse#23915]
Affects: **v21.3.9.83-lts**

I'm using http-client library which sends empty TE header value by default. It's allowed by [RFC](https://tools.ietf.org/html/rfc2616#section-14.39):
> If the TE field-value is empty or if no TE field is present, the only
> transfer-coding  is "chunked". A message with no transfer-coding is
> always acceptable.

After upgrade to _v21.3.9.83-lts_ I've got `400 Bad Request` response:
```
telnet localhost 9123
Trying ::1...
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
GET /ping HTTP/1.1
TE: 

HTTP/1.1 400 Bad Request
Connection: Close

Connection closed by foreign host.
```

with any non-whitespace TE header value it's ok:
```telnet localhost 9123
Trying ::1...
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
GET /ping HTTP/1.1
TE: chunked

HTTP/1.1 200 OK
Date: Thu, 06 May 2021 06:33:49 GMT
Connection: Keep-Alive
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Keep-Alive: timeout=125
X-ClickHouse-Summary: {"read_rows":"0","read_bytes":"0","written_rows":"0","written_bytes":"0","total_rows_to_read":"0"}

4
Ok.

0

```
Empty TE header works fine with at least _v20.8.14.4-lts_

**Comment by alexey-milovidov** [comment]
Duplicate #23901.
