### ISSUE TITLE
Rabbitmq quorum queue support 

### ISSUE THREAD

**Issue by ismailakpolat** [ClickHouse/ClickHouse#23918]
Tables using rabbitmq engine are created as classic queues. With rabbitmq 3.8  quorum type queues are implemented. Seems clickhouse not support it yet. I tried to create queue before creating clickhouse table but it did not work either. Below is the error message. 

> DB::Exception: Failed to declare queue. Probably queue settings are conflicting: max_block_size, deadletter_exchange. Attempt                 specifying differently those settings or use a different queue_base or manually delete previously declared queues,                 which  were declared with the same names. ERROR reason: PRECONDITION_FAILED - inequivalent arg 'x-queue-type' for queue 'history.queue' in vhost '/': received none but current is the value 'quorum' of type 'longstr' (version 21.2.4.6 (official build)) 

**Suggestion:**
Add parameter option as queue type to create table ddl.

**Hardness:**
Seems easy just few code for queue definition will be added. Client library may need to be upgraded.

**Comment by kssenii** [comment]
Already done in https://github.com/ClickHouse/ClickHouse/pull/23887. It is not yet merged though.

**Comment by ismailakpolat** [comment]
Oh thank you. Hope to be released soon.
