### ISSUE TITLE
all_part merge without insert or alter

### ISSUE THREAD

**Issue by sileiH** [ClickHouse/ClickHouse#23914]
I did not perform any INSERT and ALTER operations. Today, I monitored several background parts to perform a merge operation. Why is this merge performed? Does this operation have any effect? Is there any way to avoid this operation, because when you merge the disk space will suddenly surge and then fall?

I hope someone can help me solve this problem, thank you very much

**Comment by den-crane** [comment]
MergeScheduler wakes up every second and computes does it need to merge parts or not, and if it does need, then scheduler a new merge and merge parts.

**Comment by sileiH** [comment]
Sometimes I don't need this merge, and it causes the disks to explode and crash. Will he merge the part from different disks? My each disk capacity is relatively small, is there any way to avoid this?

**Comment by den-crane** [comment]
>Sometimes I don't need this merge, and it causes the disks to explode and crash. 

CH MergeScheduler is hardcoded and does not have such parameters. Try to reduce background_pool_size (users / default profile), and set it to 8
```
background_pool_size arg                                       Number of threads performing background work for tables (for example, merging in merge tree). Only has meaning at server
```

>Will he merge the part from different disks? 

It depends on how you configured storage policy.

>My each disk capacity is relatively small, is there any way to avoid this?

No

**Comment by sileiH** [comment]
Thank you
