### ISSUE TITLE
lagInFrame The function 'lagInFrame can only be used as a window function, not as an aggregate function

### ISSUE THREAD

**Issue by kolykhalov** [ClickHouse/ClickHouse#23931]
Hi guys, looks like I am terrible at documents understanding, can you please point what am I doing wrong here with lagInFrame function so I get this error?

I have a postgresql query in which I calculate difference in warehouse stock over window to get the orders:

`select date, ABS(sum(increase)) as orders 
from (
select date_trunc('day',lastupdated) as date
       qty - lag(qty) over (PARTITION BY product_id, date_trunc('day',lastupdated) order by date_trunc('day',lastupdated)) as increase
from goods) t
group by product_id
order by date desc`

It works fine

If I transpile this query to Clickhouse while replacing 'qty - lag(qty)' to 'lagInFrame(qty,1)' I get the error in subject.

What am I doing wrong here? Please advise.

**Comment by UnamedRus** [comment]
Probably the same issue as here:

https://github.com/ClickHouse/ClickHouse/issues/19857

You can't calculate expression over window functions for now, you need to use separate subquery for this.

**Comment by kolykhalov** [comment]
> You can't calculate expression over window functions for now, you need to use separate subquery for this.

@UnamedRus thanks for brief answer! :) Can you point in the direction how to subquery it? I do not quite follow what is the logic of subquery. I have several groups over time and product that have diminishing number (as products stock) and I need to calculate difference by date in each product stock. Postgresql does it the way I wrote in question. Much appreciated!

**Comment by UnamedRus** [comment]
```
select date, ABS(sum(qty - lag_qty)) as orders from ( select date_trunc('day',lastupdated) as date, lag(qty) over (PARTITION BY product_id, date_trunc('day',lastupdated) order by date_trunc('day',lastupdated)) as lag_qty from goods) t group by product_id order by date desc
```

Can you check this?

**Comment by kolykhalov** [comment]
> Can you check this?
Sure! :)

` DB::Exception: Unknown aggregate function lag (version 21.4.6.55 (official build))`

Had to modify it to lagInFrame like this and group by date:

```
select date
, ABS(sum(qty - lag_qty)) as orders 
from (select id,date_trunc('day',lastupdated) as date, qty, 
lagInFrame(qty) over (PARTITION BY product_id, date_trunc('day',lastupdated) order by date_trunc('day',lastupdated)) as lag_qty 
from goods ))t

group by product_id, date order by date desc
```

And again 
`The function 'lagInFrame can only be used as a window function, not as an aggregate function`

**Comment by UnamedRus** [comment]
```
SELECT
    date,
    ABS(sum(qty - lag_qty)) AS orders
FROM
(
    SELECT
        product_id,
        date_trunc('day', lastupdated) AS date,
        qty,
        lagInFrame(qty) OVER (PARTITION BY product_id, date_trunc('day', lastupdated) ORDER BY date_trunc('day', lastupdated) ASC) AS lag_qty
    FROM
    (
        SELECT
            rand() % 4 AS product_id,
            now() AS lastupdated,
            number AS qty
        FROM numbers(100)
    )
) AS t
GROUP BY
    product_id,
    date
ORDER BY date DESC

Query id: 86f52d0a-cb68-40ea-be1d-7d3ce32fc901

┌────────────────date─┬─orders─┐
│ 2021-05-07 00:00:00 │      0 │
│ 2021-05-07 00:00:00 │     20 │
│ 2021-05-07 00:00:00 │     14 │
│ 2021-05-07 00:00:00 │     56 │
└─────────────────────┴────────┘
```

**Comment by UnamedRus** [comment]
```
SELECT
    product_id,
    date,
    ABS(sum(qty - lag_qty)) AS orders,
    count()
FROM
(
    SELECT
        product_id,
        date_trunc('day', lastupdated) AS date,
        qty,
        lagInFrame(qty) OVER (PARTITION BY product_id, date_trunc('day', lastupdated) ORDER BY date_trunc('day', lastupdated) ASC) AS lag_qty
    FROM
    (
        SELECT
            rand() % 4 AS product_id,
            now() + toIntervalHour(number) AS lastupdated,
            number AS qty
        FROM numbers(100)
    )
) AS t
GROUP BY
    product_id,
    date
ORDER BY date DESC


┌─product_id─┬────────────────date─┬─orders─┬─count()─┐
│          2 │ 2021-05-11 00:00:00 │     88 │       8 │
│          1 │ 2021-05-11 00:00:00 │     83 │       4 │
│          0 │ 2021-05-11 00:00:00 │     91 │       8 │
│          3 │ 2021-05-11 00:00:00 │     76 │       4 │
│          2 │ 2021-05-10 00:00:00 │     60 │       8 │
│          1 │ 2021-05-10 00:00:00 │     57 │       5 │
│          0 │ 2021-05-10 00:00:00 │     61 │       3 │
│          3 │ 2021-05-10 00:00:00 │     67 │       8 │
│          1 │ 2021-05-09 00:00:00 │     42 │       5 │
│          2 │ 2021-05-09 00:00:00 │     34 │       3 │
│          3 │ 2021-05-09 00:00:00 │     28 │      12 │
│          0 │ 2021-05-09 00:00:00 │     47 │       4 │
│          0 │ 2021-05-08 00:00:00 │     26 │       6 │
│          3 │ 2021-05-08 00:00:00 │     22 │       6 │
│          2 │ 2021-05-08 00:00:00 │     23 │       6 │
│          1 │ 2021-05-08 00:00:00 │     16 │       6 │
│          3 │ 2021-05-07 00:00:00 │      3 │       1 │
│          0 │ 2021-05-07 00:00:00 │      0 │       1 │
│          1 │ 2021-05-07 00:00:00 │      1 │       1 │
│          2 │ 2021-05-07 00:00:00 │      2 │       1 │
└────────────┴─────────────────────┴────────┴─────────┘

```

**Comment by UnamedRus** [comment]
It produces some result with multiple qty per day also.

**Comment by UnamedRus** [comment]
Can you make some example which is failing in clickhouse?

**Comment by kolykhalov** [comment]
Sure, thanks a lot for your engaging! 👍 

The query looks like this (according to your example):

````sql
select date,lag from (
  select product_id,date,qty
  ,lagInFrame(qty) over (PARTITION by product_id,date order by date) as lag
  from (
		select product_id, date_trunc('day',lastupdated) as date, min(qty) as qty
                  from goods
		  group by product_id, date_trunc('day',lastupdated)
		  order by date_trunc('day',lastupdated)
		  ) 
  )t
  group by date,lag 
  order by date desc
````

The result of the subquery is:

id | date | qty
------------ | ------------- | ---------------
4482707	| 2021-05-03 00:00:00 | 1
9871092	| 2021-05-03 00:00:00	|0
9870995	|2021-05-03 00:00:00	|1
8474083	|2021-05-03 00:00:00	|12
4482707	|2021-05-04 00:00:00	|104
9871092	|2021-05-04 00:00:00	|0
9870995	|2021-05-04 00:00:00	|1
8474083	|2021-05-04 00:00:00	|11
4482707	|2021-05-05 00:00:00	|100
9871092	|2021-05-05 00:00:00	|0
8474083	|2021-05-05 00:00:00	|7
9870995	|2021-05-05 00:00:00	|1
4482707	|2021-05-06 00:00:00	|89
9871092	|2021-05-06 00:00:00	|0
8474083	|2021-05-06 00:00:00	|7
9870995	|2021-05-06 00:00:00	|1

result:
````
The function 'lagInFrame' can only be used as a window function, not as an aggregate function (version 21.4.6.55 (official build))
````

In the end I just copy-pasted your query replacing with my subquery like this:

````sql
SELECT
    date,
    ABS(sum(qty - lag_qty)) AS orders
FROM
(
    SELECT
        product_id,
        date,
        qty,
        lagInFrame(qty) OVER (PARTITION BY product_id, date ORDER BY date ASC) AS lag_qty
    FROM
    (
        select product_id, date_trunc('day',lastupdated) as date, min(qty) as qty
         from goods
		  group by product_id,date_trunc('day',lastupdated)
		  order by date_trunc('day',lastupdated)
    )
) AS t
GROUP BY
   product_id,
    date
ORDER BY date DESC
````

whadda ya know, exactly the same result:
````
The function 'lagInFrame' can only be used as a window function, not as an aggregate function (version 21.4.6.55 (official build))
````

**Comment by UnamedRus** [comment]
```
CREATE TABLE goods
ENGINE = Memory AS
SELECT
    rand() % 4 AS product_id,
    now() + toIntervalHour(number) AS lastupdated,
    number AS qty
FROM numbers(100)

SELECT
    date,
    ABS(sum(qty - lag_qty)) AS orders
FROM
(
    SELECT
        product_id,
        date,
        qty,
        lagInFrame(qty) OVER (PARTITION BY product_id, date ORDER BY date ASC) AS lag_qty
    FROM
    (
        SELECT
            product_id,
            date_trunc('day', lastupdated) AS date,
            min(qty) AS qty
        FROM goods
        GROUP BY
            product_id,
            date_trunc('day', lastupdated)
        ORDER BY date_trunc('day', lastupdated) ASC
    )
) AS t
GROUP BY
    product_id,
    date
ORDER BY date DESC

Query id: dc732d5e-5d15-457c-9ae6-3e79e9891ca1

┌────────────────date─┬─orders─┐
│ 2021-05-12 00:00:00 │     88 │
│ 2021-05-12 00:00:00 │     94 │
│ 2021-05-12 00:00:00 │     86 │
│ 2021-05-12 00:00:00 │     92 │
│ 2021-05-11 00:00:00 │     69 │
│ 2021-05-11 00:00:00 │     64 │
│ 2021-05-11 00:00:00 │     62 │
│ 2021-05-11 00:00:00 │     67 │
│ 2021-05-10 00:00:00 │     38 │
│ 2021-05-10 00:00:00 │     41 │
│ 2021-05-10 00:00:00 │     39 │
│ 2021-05-10 00:00:00 │     43 │
│ 2021-05-09 00:00:00 │     18 │
│ 2021-05-09 00:00:00 │     20 │
│ 2021-05-09 00:00:00 │     14 │
│ 2021-05-09 00:00:00 │     16 │
│ 2021-05-08 00:00:00 │      2 │
│ 2021-05-08 00:00:00 │      0 │
│ 2021-05-08 00:00:00 │      3 │
│ 2021-05-08 00:00:00 │     13 │
└─────────────────────┴────────┘

select date,lag from (
  select product_id,date,qty
  ,lagInFrame(qty) over (PARTITION by product_id,date order by date) as lag
  from (
		select product_id, date_trunc('day',lastupdated) as date, min(qty) as qty
                  from goods
		  group by product_id, date_trunc('day',lastupdated)
		  order by date_trunc('day',lastupdated)
		  ) 
  )t
  group by date,lag 
  order by date desc


┌────────────────date─┬─lag─┐
│ 2021-05-12 00:00:00 │   0 │
│ 2021-05-11 00:00:00 │   0 │
│ 2021-05-10 00:00:00 │   0 │
│ 2021-05-09 00:00:00 │   0 │
│ 2021-05-08 00:00:00 │   0 │
└─────────────────────┴─────┘
```



Can you run `SHOW CREATE TABLE goods;`

**Comment by kolykhalov** [comment]
There you go

CREATE TABLE seller.goods
(
    `product_id` String,
    `name` Nullable(String),
    `currentprice` Nullable(Float32),
    `oldprice` Nullable(Float32),
    `discount` Nullable(Int32),
    `promo` Nullable(Int32),
    `item_size` Nullable(String),
    `warehouse` Nullable(String),
    `qty` Nullable(Int32),
    `lastupdated` DateTime,
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(lastupdated)
ORDER BY (id, lastupdated)
SETTINGS index_granularity = 8192

**Comment by kolykhalov** [comment]
Here is my last subquery result which is identical to yours first subquery, which is 

`SELECT
            product_id,
            date_trunc('day', lastupdated) AS date,
            min(qty) AS qty
        FROM goods
        GROUP BY
            product_id,
            date_trunc('day', lastupdated)
        ORDER BY date_trunc('day', lastupdated) ASC`

|product_id|lastupdated|qty
|--|--|--|
6128185	|2021-05-22 00:00:00	|116
9870995	|2021-05-22 00:00:00	|1
6265052	|2021-05-22 00:00:00	|90
8974919	|2021-05-22 00:00:00	|169
4482707	|2021-05-22 00:00:00	|279
4482707	|2021-05-23 00:00:00	|274
6128185	|2021-05-23 00:00:00	|114
6265052	|2021-05-23 00:00:00	|89
8974919	|2021-05-23 00:00:00	|165
8474083	|2021-05-24 00:00:00	|1
6265052	|2021-05-24 00:00:00	|87
6128185	|2021-05-24 00:00:00	|109
8974919	|2021-05-24 00:00:00	|162
4482707	|2021-05-24 00:00:00	|267
4482707	|2021-05-25 00:00:00	|264
6128185	|2021-05-25 00:00:00	|109
8974919	|2021-05-25 00:00:00	|158
8474083	|2021-05-25 00:00:00	|1
6265052	|2021-05-25 00:00:00	|87

result of the full query which is 
`SELECT
    date,
    ABS(sum(qty - lag_qty)) AS orders
FROM
(
    SELECT
        product_id,
        date,
        qty,
        lagInFrame(qty) OVER (PARTITION BY product_id, date ORDER BY date ASC) AS lag_qty
    FROM
    (
        SELECT
            product_id,
            date_trunc('day', lastupdated) AS date,
            min(qty) AS qty
        FROM goods
        GROUP BY
            product_id,
            date_trunc('day', lastupdated)
        ORDER BY date_trunc('day', lastupdated) ASC
    )
) AS t
GROUP BY
    product_id,
    date
ORDER BY date DESC`

As before: ` DB::Exception: The function 'lagInFrame' can only be used as a window function, not as an aggregate function (version 21.4.6.55 (official build))`

**Comment by akuzm** [comment]
```
CREATE TABLE goods
(
    `id` String,
    `name` Nullable(String),
    `currentprice` Nullable(Float32),
    `oldprice` Nullable(Float32),
    `discount` Nullable(Int32),
    `promo` Nullable(Int32),
    `item_size` Nullable(String),
    `warehouse` Nullable(String),
    `qty` Nullable(Int32),
    `lastupdated` DateTime
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(lastupdated)
ORDER BY (id, lastupdated)
SETTINGS index_granularity = 8192
;

SELECT
    date,
    ABS(sum(qty - lag_qty)) AS orders
FROM
(
    SELECT
        id,
        date,
        qty,
SELECT
    date,
    ABS(sum(qty - lag_qty)) AS orders
FROM
(
    SELECT
        id,
        date,
        qty,
        lagInFrame(qty) OVER (PARTITION BY id, date ORDER BY date ASC) AS lag_qty
    FROM
    (
        SELECT
            id,
            date_trunc('day', lastupdated) AS date,
            min(qty) AS qty
        FROM goods
        GROUP BY
            id,
            date_trunc('day', lastupdated)
        ORDER BY date_trunc('day', lastupdated) ASC
    )
) AS t
GROUP BY
    id,
    date
ORDER BY date DESC;

Received exception from server (version 21.7.1):
Code: 36. DB::Exception: Received from localhost:9000. DB::Exception: The function 'lagInFrame' can only be used as a window function, not as an aggregate function. Stack trace:
```

Looks like some problem with alias substitution, i.e. lag_qty is substituted to the upper subquery.

**Comment by akuzm** [comment]
```
:) select lagInFrame(toNullable(1)) over ();

Received exception from server (version 21.7.1):
Code: 36. DB::Exception: Received from localhost:9000. DB::Exception: The function 'lagInFrame' can only be used as a window function, not as an aggregate function. Stack trace:
```

The problem is in auto-application of `-OrNull` combinator for aggregate functions of nullable arguments.
