### ISSUE TITLE
clickhouse 21.4.5.46 How to use kafka engine table to consume data of kafka with kerberos

### ISSUE THREAD

**Issue by mjh568412187** [ClickHouse/ClickHouse#23933]
Make sure to check documentation https://clickhouse.yandex/docs/en/ first. If the question is concise and probably has a short answer, asking it in Telegram chat https://telegram.me/clickhouse_en is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

If you still prefer GitHub issues, remove all this text and ask your question here.

clickhouse version：21.4.5.46
kafka with kerberos

confing.xml

```
<!-- Kerberos-aware Kafka -->
<kafka>
  <security_protocol>SASL_PLAINTEXT</security_protocol>
  <sasl_kerberos_keytab>/opt/kerberos_conf/ucloud_bi.keytab</sasl_kerberos_keytab>
  <sasl_kerberos_principal>ucloud_bi@YONGHUI.CN</sasl_kerberos_principal>
</kafka>
```

systemctl restart clickhouse-server

Create the kafka engine table

The error is as follows
<img width="1346" alt="image" src="https://user-images.githubusercontent.com/26197792/117407457-2ac1a180-af41-11eb-85d8-811a140a379c.png">

参考链接：https://clickhouse.tech/docs/en/engines/table-engines/integrations/kafka/#kafka-kerberos-support

**Comment by filimonov** [comment]
See
https://github.com/ClickHouse/ClickHouse/blob/master/tests/integration/test_storage_kerberized_kafka/configs/kafka.xml

and
https://github.com/edenhill/librdkafka/wiki/Using-SASL-with-librdkafka

Try to connect with kafkacat. After success - use same parameters in kafka config in clickhouse
