### ISSUE TITLE
Subquery became slow after upgrading

### ISSUE THREAD

**Issue by AlexMAS** [ClickHouse/ClickHouse#23935]
Hello!

I've upgraded ClickHouse from `20.1.9.54` to `21.3.4.25` and noticed that CPU consumption dramatically increased.

After long investigation seems I found out the reason or something near to it.

Firstly, I have several databases (`77` to be precise) with same schema. Each database has next `MergeTree` table:

```sql
CREATE TABLE IF NOT EXISTS history (
  param_id String,
  date Date DEFAULT toDate(time),
  time DateTime,
  value Float64
)
ENGINE = MergeTree()
PARTITION BY toYYYYMM(date)
ORDER BY (param_id, date, time)
```

Periodically I need to determine the latest timestamp of the `history` table. Due to the table has lots of data I made [a small optimization](https://github.com/ClickHouse/ClickHouse/issues/1582) which promised must minimize the number of parts needed to perform the query. And it has worked fine in `20.1.9.54`.

```sql
SELECT max(time) AS lastTimestamp
FROM history
WHERE date >=
(
  SELECT max(max_date)
  FROM system.parts
  WHERE (database = 'db1') AND (table = 'history') AND (active = 1) AND (rows > 0)
)
```

After upgrade this query became very slow especially if I performing it for several database simultaneously. At this moment CPU consumption is increased and seems that ClickHouse makes full scan.

My first thoughts were about some kind of locking the `system.parts` table so to check I replaced the subquery with a constant.

```sql
SELECT max(time) AS lastTimestamp
FROM history
WHERE date >= '2021-05-07'
```

And the query started to work as fast as before.

Strangely, at the same moment if I perform the subquery separately it works fast.

```sql
SELECT max(max_date)
FROM system.parts
WHERE (database = 'db1') AND (table = 'history') AND (active = 1) AND (rows > 0)

Query id: bdb29e5c-acd1-4efb-a315-4ba3aa06db8a

┌─max(max_date)─┐
│    2021-05-07 │
└───────────────┘

1 rows in set. Elapsed: 0.269 sec.
```

I've been confused. Both the query (with a constant in `WHERE` clause) and the subquery work fast separately but slow together.

Finally I've replaced the subquery with `today()` function and got the same slow query!

```sql
:) SELECT max(time) AS lastTimestamp　FROM history　WHERE date >= (SELECT today())

SELECT max(time) AS lastTimestamp
FROM history
WHERE date >=
(
    SELECT today()
)

Query id: cf0dd788-9030-47a3-bdc4-ab540f3f7bb2

┌─lastTimestamp─┐
│    1620377322 │
└───────────────┘

1 rows in set. Elapsed: 10.305 sec. Processed 671.30 million rows, 1.35 GB (65.14 million rows/s., 130.79 MB/s.)
```

So I decided that **the reason does not relate with the `system.parts` table but with how subqueries are processed** in `21.3.4.25`.

At the moment I see next behavior. Increasing number of above mentioned queries to different databases increases CPU consumption and degrate the query performance. All queries are executed concurrently. Performing of the query looks like full scan and the optimization is not applied. 

Probably I missed some important changes between `20.1.9.54` and `21.3.4.25`. Anyway I need your help or ideas how to fix the problem.

**Comment by amosbird** [comment]
It's most likely related to https://github.com/ClickHouse/ClickHouse/pull/21766

**Comment by AlexMAS** [comment]
@amosbird Thank you for replying. Could you tell which version will include the fix?

**Comment by amosbird** [comment]
Good question. I don't know how to find the exact releases. Maybe you can try checking some latest versions and see if the ChangeLog contains this fix.

**Comment by AlexMAS** [comment]
Seems [v21.4](https://clickhouse.tech/docs/en/whats-new/changelog/#clickhouse-release-21-4) should include the fix. I'll check it, thanks.

**Comment by filimonov** [comment]
21.3.9 should also have it backported

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/21717

Why did you  use 21.3.4.25 instead of 21.3.9.83
