### ISSUE TITLE
command: show views

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#23937]
select database, name from system.tables where engine = 'View'

https://stackoverflow.com/questions/67434764/how-to-list-all-available-views-in-clickhouse-db

**Comment by alexey-milovidov** [comment]
Also consider materialized views and live views.
But materialized views are not very different to tables, so the scope of SHOW VIEWS remains unclear.

**Comment by alexey-milovidov** [comment]
If we will implement SHOW VIEWs straight as proposed, people will always wonder if materialized and live views are included.
