### ISSUE TITLE
I find that the query execution time increases linearly when the number of columns returned by the query increases

### ISSUE THREAD

**Issue by wallace-clickhouse** [ClickHouse/ClickHouse#23954]
I find that the query execution time increases linearly when the number of columns returned by the query increases. 
So how can I optimize the query or database parameters to reduce query duration ?

**Comment by alexey-milovidov** [comment]
There are multiple ways how queries can be optimized.

Give me your query, the definition of your tables, your cluster configuration and the settings, the configuration of your hardware, the version of ClickHouse you are using; your domain area and load scenario, the name of your company... and maybe we will find a way to optimize some queries.

**Comment by wallace-clickhouse** [comment]
Can you give me some general optimization instructions?For the situation of returning many columns(about 100) in one query,under which I find the query is slower than less columns.
Thanks a lot！
