### ISSUE TITLE
Caused by: org.apache.http.TruncatedChunkException: Truncated chunk ( expected size: 4096; actual size: 4088)

### ISSUE THREAD

**Issue by a394023466** [ClickHouse/ClickHouse#23955]
Caused by: org.apache.http.TruncatedChunkException: Truncated chunk ( expected size: 4096; actual size: 4088)

**Comment by a394023466** [comment]
![image](https://user-images.githubusercontent.com/39642052/117537149-c4687c00-b031-11eb-8942-28e19d00bd52.png)

**Comment by den-crane** [comment]
Check clickhouse server err.log.

It does not look like CH error. This error is in java / jdbc.

**Comment by GarveyZuo** [comment]
I meet the same problem and it appear every time when I use jdbc to read data。

**Comment by GarveyZuo** [comment]
even after update the clickhouse jdbc version to 0.7.2
