### ISSUE TITLE
Clickhouse live view refresh not working

### ISSUE THREAD

**Issue by mxzhong** [ClickHouse/ClickHouse#23977]
Hello, Now I use clickHouse server version 21.1.2 revision 54443

I get a question about live view refresh,
when I use the "CREATE LIVE VIEW lv WITH TIMEOUT 15 AND REFRESH 5 AS SELECT now();" like the example
https://clickhouse.tech/docs/en/sql-reference/statements/create/view/#live-view-alter-refresh

I got a exception :
Syntax error: failed at position 37 ('AND'):
CREATE LIVE VIEW lv WITH TIMEOUT 15 AND REFRESH 5 AS SELECT now();
Expected one of: AS, OpeningRoundBracket, ON, TO, token

Just remove  "AND REFRESH 5" it works, But I need use refresh function, how to write?

**Comment by vzakaznikov** [comment]
I don't remember which in version it was added. Bu the latest stable version of ClickHouse supports it.

```
