### ISSUE TITLE
Are there any plans for the table engine EmbeddedRocksDB? will consider implementing distributed storage of key-value data?

### ISSUE THREAD

**Issue by blueChild** [ClickHouse/ClickHouse#23989]
Currently, the table engine `EmbeddedRocksDB` supported by clickhouse supports key-value operations on data, which I think is a great implementation. Unfortunately, we find that this feature is only an experimental feature. During the use of this feature, we think that this feature lacks the following functions:

- Multi-disk policy configuration
- Support delete operation
- Delete expired key-value data
- Distributed data storage

We want to use clickhouse to replace Redis to implement a similar distributed key-value system to reduce the memory requirements of the system. The delete operation and key-value data deletion functions are supplemented in our local version. To implement the `distributed data storage` feature, we want to use [pinterest/rocksplicator](https://github.com/pinterest/rocksplicator)  to generate and manage data copies and route queries. Do you have any better suggestions from the community about the implementation of distributed storage? Also, for `EmbeddedRocksDB`, is there a plan behind the community? I look forward to hearing from you. Thank you.

**Comment by alexey-milovidov** [comment]
There are some plans around or related to EmbeddedRocksDB:

1. Proper use of key-value tables in JOIN: #33582
2. Key-value interface for ClickHouse: #33581
3. Support composite key for EmbeddedRocksDB tables: #32819

There are no current plans around storage and replication of EmbeddedRocksDB, this is up to community (if there will be work, we will help with merging).
