### ISSUE TITLE
Clickhouse process crash while inserting data.

### ISSUE THREAD

**Issue by kindred77** [ClickHouse/ClickHouse#23986]
CH version: 20.8.3.18
We import a table with 300+ columns and 500 million rows into CH everyday using spark.
There are 4 nodes with 64cpu cores, 250G mem, 10 SSD disks in the CH cluster.
We use the official JDBC driver and set the batch size to be 100000.
It will be stateful when concurrent running task is about 500.
But the CH process cash frequently when we set the batch size to be 300000+ and concurrent running task is 800+.
We got a "core.120788" file in the CH home dir and some message in server log below when the process crashed:

2021.05.04 08:45:27.420282 [ 120812 ] {} <Trace> MergeTreeSequentialSource: Reading 14 marks from part all_9741_9741_0, total 27642 rows starting from the beginning of the part, column login_30d_days
2021.05.04 08:45:27.420463 [ 120812 ] {} <Trace> MergeTreeSequentialSource: Reading 11 marks from part all_9742_9742_0, total 19469 rows starting from the beginning of the part, column login_30d_days
2021.05.04 08:45:27.420643 [ 120812 ] {} <Trace> MergeTreeSequentialSource: Reading 16 marks from part all_9743_9743_0, total 28949 rows starting from the beginning of the part, column login_30d_days
2021.05.04 08:45:27.420836 [ 120812 ] {} <Trace> MergeTreeSequentialSource: Reading 15 marks from part all_9744_9744_0, total 27998 rows starting from the beginning of the part, column login_30d_days
2021.05.04 08:45:27.421025 [ 120812 ] {} <Trace> MergeTreeSequentialSource: Reading 15 marks from part all_9745_9745_0, total 26506 rows starting from the beginning of the part, column login_30d_days
2021.05.04 08:45:27.422587 [ 120812 ] {} <Trace> MergeTreeSequentialSource: Reading 15 marks from part all_9739_9739_0, total 28255 rows starting from the beginning of the part, column month_favour_amt
2021.05.04 08:45:27.422792 [ 120812 ] {} <Trace> MergeTreeSequentialSource: Reading 10 marks from part all_9740_9740_0, total 17199 rows starting from the beginning of the part, column month_favour_amt
2021.05.04 08:45:27.422988 [ 120812 ] {} <Trace> MergeTreeSequentialSource: Reading 14 marks from part all_9741_9741_0, total 27642 rows starting from the beginning of the part, column month_favour_amt
2021.05.04 08:45:27.423172 [ 120812 ] {} <Trace> MergeTreeSequentialSource: Reading 11 marks from part all_9742_9742_0, total 19469 rows starting from the beginning of the part, column month_favour_amt
2021.05.04 08:45:27.423365 [ 120812 ] {} <Trace> MergeTreeSequentialSource: Reading 16 marks from part all_9743_9743_0, total 28949 rows starting from the beginning of the part, column month_favour_amt
2021.05.04 08:45:27.423553 [ 120812 ] {} <Trace> MergeTreeSequentialSource: Reading 15 marks from part all_9744_9744_0, total 27998 rows starting from the beginning of the part, column month_favour_amt
2021.05.04 08:45:27.423757 [ 120812 ] {} <Trace> MergeTreeSequentialSource: Reading 15 marks from part all_9745_9745_0, total 26506 rows starting from the beginning of the part, column month_favour_amt
2021.05.04 08:45:27.425124 [ 120812 ] {} <Trace> MergeTreeSequentialSource: Reading 15 marks from part all_9739_9739_0, total 28255 rows starting from the beginning of the part, column no_disturb_user_type
2021.05.04 08:45:27.425329 [ 120812 ] {} <Trace> MergeTreeSequentialSource: Reading 10 marks from part all_9740_9740_0, total 17199 rows starting from the beginning of the part, column no_disturb_user_type
2021.05.04 08:45:27.425516 [ 120812 ] {} <Trace> MergeTreeSequentialSource: Reading 14 marks from part all_9741_9741_0, total 27642 rows starting from the beginning of the part, column no_disturb_user_type
2021.05.04 08:45:27.425700 [ 120812 ] {} <Trace> MergeTreeSequentialSource: Reading 11 marks from part all_9742_9742_0, total 19469 rows starting from the beginning of the part, column no_disturb_user_type
2021.05.04 08:45:27.425888 [ 120812 ] {} <Trace> MergeTreeSequentialSource: Reading 16 marks from part all_9743_9743_0, total 28949 rows starting from the beginning of the part, column no_disturb_user_type
2021.05.04 08:45:27.426084 [ 120812 ] {} <Trace> MergeTreeSequentialSource: Reading 15 marks from part all_9744_9744_0, total 27998 rows starting from the beginning of the part, column no_disturb_user_type
2021.05.04 08:45:27.426277 [ 120812 ] {} <Trace> MergeTreeSequentialSource: Reading 15 marks from part all_9745_9745_0, total 26506 rows starting from the beginning of the part, column no_disturb_user_type
2021.05.04 08:45:27.429370 [ 120812 ] {} <Trace> MergeTreeSequentialSource: Reading 15 marks from part all_9739_9739_0, total 28255 rows starting from the beginning of the part, column xffq_avail_vou_cnt
2021.05.04 08:45:27.429574 [ 120812 ] {} <Trace> MergeTreeSequentialSource: Reading 10 marks from part all_9740_9740_0, total 17199 rows starting from the beginning of the part, column xffq_avail_vou_cnt
2021.05.04 08:45:27.429760 [ 120812 ] {} <Trace> MergeTreeSequentialSource: Reading 14 marks from part all_9741_9741_0, total 27642 rows starting from the beginning of the part, column xffq_avail_vou_cnt
2021.05.04 08:45:27.429940 [ 120812 ] {} <Trace> MergeTreeSequentialSource: Reading 11 marks from part all_9742_9742_0, total 19469 rows starting from the beginning of the part, column xffq_avail_vou_cnt
2021.05.04 08:45:27.430128 [ 120812 ] {} <Trace> MergeTreeSequentialSource: Reading 16 marks from part all_9743_9743_0, total 28949 rows starting from the beginning of the part, column xffq_avail_vou_cnt
2021.05.04 08:45:27.430319 [ 120812 ] {} <Trace> MergeTreeSequentialSource: Reading 15 marks from part all_9744_9744_0, total 27998 rows starting from the beginning of the part, column xffq_avail_vou_cnt
2021.05.04 08:45:27.430503 [ 120812 ] {} <Trace> MergeTreeSequentialSource: Reading 15 marks from part all_9745_9745_0, total 26506 rows starting from the beginning of the part, column xffq_avail_vou_cnt
2021.05.04 08:45:27.431869 [ 120812 ] {} <Trace> MergeTreeSequentialSource: Reading 15 marks from part all_9739_9739_0, total 28255 rows starting from the beginning of the part, column xffq_avail_vou_max_val
2021.05.04 08:45:27.432077 [ 120812 ] {} <Trace> MergeTreeSequentialSource: Reading 10 marks from part all_9740_9740_0, total 17199 rows starting from the beginning of the part, column xffq_avail_vou_max_val
2021.05.04 08:45:27.432273 [ 120812 ] {} <Trace> MergeTreeSequentialSource: Reading 14 marks from part all_9741_9741_0, total 27642 rows starting from the beginning of the part, column xffq_avail_vou_max_val
2021.05.04 08:45:27.432453 [ 120812 ] {} <Trace> MergeTreeSequentialSource: Reading 11 marks from part all_9742_9742_0, total 19469 rows starting from the beginning of the part, column xffq_avail_vou_max_val
2021.05.04 08:45:27.432634 [ 120812 ] {} <Trace> MergeTreeSequentialSource: Reading 16 marks from part all_9743_9743_0, total 28949 rows starting from the beginning of the part, column xffq_avail_vou_max_val
2021.05.04 08:45:27.432822 [ 120812 ] {} <Trace> MergeTreeSequentialSource: Reading 15 marks from part all_9744_9744_0, total 27998 rows starting from the beginning of the part, column xffq_avail_vou_max_val
2021.05.04 08:45:27.433009 [ 120812 ] {} <Trace> MergeTreeSequentialSource: Reading 15 marks from part all_9745_9745_0, total 26506 rows starting from the beginning of the part, column xffq_avail_vou_max_val
2021.05.04 08:45:27.434350 [ 120812 ] {} <Trace> MergeTreeSequentialSource: Reading 15 marks from part all_9739_9739_0, total 28255 rows starting from the beginning of the part, column xffq_vou_min_expiry_tm
2021.05.04 08:45:27.434549 [ 120812 ] {} <Trace> MergeTreeSequentialSource: Reading 10 marks from part all_9740_9740_0, total 17199 rows starting from the beginning of the part, column xffq_vou_min_expiry_tm
2021.05.04 08:45:27.434734 [ 120812 ] {} <Trace> MergeTreeSequentialSource: Reading 14 marks from part all_9741_9741_0, total 27642 rows starting from the beginning of the part, column xffq_vou_min_expiry_tm
2021.05.04 08:45:27.434911 [ 120812 ] {} <Trace> MergeTreeSequentialSource: Reading 11 marks from part all_9742_9742_0, total 19469 rows starting from the beginning of the part, column xffq_vou_min_expiry_tm
2021.05.04 08:45:27.435098 [ 120812 ] {} <Trace> MergeTreeSequentialSource: Reading 16 marks from part all_9743_9743_0, total 28949 rows starting from the beginning of the part, column xffq_vou_min_expiry_tm
2021.05.04 08:45:27.435284 [ 120812 ] {} <Trace> MergeTreeSequentialSource: Reading 15 marks from part all_9744_9744_0, total 27998 rows starting from the beginning of the part, column xffq_vou_min_expiry_tm
2021.05.04 08:45:27.435468 [ 120812 ] {} <Trace> MergeTreeSequentialSource: Reading 15 marks from part all_9745_9745_0, total 26506 rows starting from the beginning of the part, column xffq_vou_min_expiry_tm
2021.05.04 08:50:01.866283 [ 143444 ] {} <Information> SentryWriter: Sending crash reports is disabled
2021.05.04 08:50:01.868017 [ 143444 ] {} <Trace> Pipe: Pipe capacity is 1.00 MiB
2021.05.04 08:50:01.918275 [ 143444 ] {} <Information> : Starting ClickHouse 20.8.3.18 with revision 54438, no build id, PID 143444
2021.05.04 08:50:01.918332 [ 143444 ] {} <Information> Application: starting up
2021.05.04 08:50:01.922632 [ 143444 ] {} <Information> StatusFile: Status file /data/clickhouse/newclickhouse/data/status already exists - unclean restart. Contents:
PID: 120788
Started at: 2021-05-04 07:05:01
Revision: 54438

2021.05.04 08:50:01.922715 [ 143444 ] {} <Debug> Application: rlimit on number of file descriptors is 102400
2021.05.04 08:50:01.922723 [ 143444 ] {} <Debug> Application: Initializing DateLUT.
2021.05.04 08:50:01.922726 [ 143444 ] {} <Trace> Application: Initialized DateLUT with time zone 'Asia/Shanghai'.
2021.05.04 08:50:01.922743 [ 143444 ] {} <Debug> Application: Setting up /data/clickhouse/newclickhouse/data/tmp/ to store temporary data in it
2021.05.04 08:50:01.922914 [ 143444 ] {} <Debug> Application: Configuration parameter 'interserver_http_host' doesn't exist or exists and empty. Will use 'd20809u28-72-144' as replica host.
2021.05.04 08:50:01.923647 [ 143444 ] {} <Debug> ConfigReloader: Loading config '/data/clickhouse/newclickhouse/etc/clickhouse-server/users.xml'
2021.05.04 08:50:01.924072 [ 143444 ] {} <Debug> ConfigReloader: Loaded config '/data/clickhouse/newclickhouse/etc/clickhouse-server/users.xml', performing update on configuration
2021.05.04 08:50:01.924495 [ 143444 ] {} <Debug> ConfigReloader: Loaded config '/data/clickhouse/newclickhouse/etc/clickhouse-server/users.xml', performed update on configuration
2021.05.04 08:50:01.925063 [ 143444 ] {} <Information> Application: Setting max_server_memory_usage was set to 226.25 GiB (251.39 GiB available * 0.90 max_server_memory_usage_to_ram_ratio)
2021.05.04 08:50:01.925071 [ 143444 ] {} <Information> Application: Loading metadata from /data/clickhouse/newclickhouse/data/
2021.05.04 08:50:01.926139 [ 143444 ] {} <Information> DatabaseAtomic (system): Total 3 tables and 0 dictionaries.
2021.05.04 08:50:01.929147 [ 143452 ] {} <Information> StoragePolicySelector: Storage policy `policies1` loaded
2021.05.04 08:50:01.929246 [ 143450 ] {} <Information> BackgroundProcessingPool: Create BackgroundProcessingPool with 16 threads

**Comment by alexey-milovidov** [comment]
Does the issue reproduce on recent ClickHouse release?

**Comment by kindred77** [comment]
Did not crash since we change to 21.3.9 lts.
This could be closed, thanks for supportment.
