### ISSUE TITLE
 Too  many partitions for single INSERT block (more than 500)

### ISSUE THREAD

**Issue by gelezayka** [ClickHouse/ClickHouse#24006]
I will insert a lot of data through carbonapi into the clickhouse and get this error.
First I saw the error "more than 100"
I set In config file max_partitions_per_insert_block to 1000
This led to the error "more than 500"
After it i change 1000 to 0 and saw the same error

I don't understand what to do?
Thank you for helping me.

Error trace from log:
2021.05.11 01:16:23.624415 [ 30175 ] {3e6c70e3-9ff3-47c3-aaa3-3521f613eaaf} <Error> executeQuery: Code: 252, e.displayText() = DB::Exception: 
Too many partitions for single INSERT block (more than 500). The limit is controlled by 'max_partitions_per_insert_block' setting. Large number of partitions is a common misconception. It will lead to severe negative performance impact, including slow server startup, slow INSERT queries and slow SELECT queries. Recommended total number of partitions for a table is under 1000..10000. Please note, that partitioning is not intended to speed up SELECT queries (ORDER BY key is sufficient to make range queries fast). Partitions are intended for data manipulation (DROP PARTITION, etc). (version 21.4.6.55 (official build)) (from x.x.x.x:59114) (in query: INSERT INTO graphite.data_sharded (Path, Value, Time, Date, Timestamp) VALUES), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x87f71
4a in /usr/bin/clickhouse
1. DB::MergeTreeDataWriter::splitBlockIntoParts(DB::Block const&, unsigned long, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const
&) @ 0xfccc43f in /usr/bin/clickhouse
2. DB::ReplicatedMergeTreeBlockOutputStream::write(DB::Block const&) @ 0xfd72559 in /usr/bin/clickhouse
3. DB::PushingToViewsBlockOutputStream::write(DB::Block const&) @ 0xf24a7b4 in /usr/bin/clickhouse
4. DB::AddingDefaultBlockOutputStream::write(DB::Block const&) @ 0xf25476b in /usr/bin/clickhouse
5. DB::SquashingBlockOutputStream::finalize() @ 0xf254d8c in /usr/bin/clickhouse
6. DB::SquashingBlockOutputStream::writeSuffix() @ 0xf254e09 in /usr/bin/clickhouse
7. DB::TCPHandler::processInsertQuery(DB::Settings const&) @ 0xfef3710 in /usr/bin/clickhouse
8. DB::TCPHandler::runImpl() @ 0xfeebfd9 in /usr/bin/clickhouse
9. DB::TCPHandler::run() @ 0xfefe399 in /usr/bin/clickhouse
10. Poco::Net::TCPServerConnection::start() @ 0x125b865f in /usr/bin/clickhouse
11. Poco::Net::TCPServerDispatcher::run() @ 0x125ba071 in /usr/bin/clickhouse
12. Poco::PooledThread::run() @ 0x126f0799 in /usr/bin/clickhouse
13. Poco::ThreadImpl::runnableEntry(void*) @ 0x126ec5fa in /usr/bin/clickhouse
14. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
15. __clone @ 0xfe9fd in /usr/lib64/libc-2.17.so

**Comment by alexey-milovidov** [comment]
Remove partition key from your table (it is totally fine to not having partition key at all) or make it less granular (e.g. partitions by months, not by days).

**Comment by alexey-milovidov** [comment]
About the setting - you probably put it in a wrong place (it is the query level setting, set up for a user profile, see users.xml).

**Comment by gelezayka** [comment]
i create  new table like this: 
	 CREATE TABLE graphite.data_sharded on cluster tss
	(
	    `Path` String,
	    `Value` Float64,
	    `Time` UInt32,
	    `Date` Date,
	    `Timestamp` UInt32
	)
ENGINE = ReplicatedGraphiteMergeTree('/clickhouse/tables/{layer}-{shard}/graphite.data_sharded', '{replica}', 'graphite_rollup')
PARTITION BY toYYYYMM(Date)
ORDER BY (Path, Time)
SETTINGS index_granularity = 8192;


SELECT partition　   FROM system.parts　   WHERE database = 'graphite' and table = 'data_sharded' and active = 1　   GROUP BY partition;


┌─partition─┐
│ 202105    │
└───────────┘

and saw same error:

2021.05.11 11:42:46.472110 [ 29474 ] {22ab8284-3ac1-4b40-9553-1ae8a665e1c0} <Error> executeQuery: Code: 252, e.displayText() = DB::Exception: Too many partitions for single INSERT block (more than 500). The limit is controlled by 'max_partitions_per_insert_block' setting. Large number of partitions is a common misconception. It will lead to severe negative performance impact, including slow server startup, slow INSERT queries and slow SELECT queries. Recommended total number of partitions for a table is under 1000..10000. Please note, that partitioning is not intended to speed up SELECT queries (ORDER BY key is sufficient to make range queries fast). Partitions are intended for data manipulation (DROP PARTITION, etc). (version 21.4.6.55 (official build)) (from x.x.x.x:50852) (in query: INSERT INTO graphite.data_sharded (Path, Value, Time, Date, Timestamp) VALUES), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x87f714a in /usr/bin/clickhouse
1. DB::MergeTreeDataWriter::splitBlockIntoParts(DB::Block const&, unsigned long, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&) @ 0xfccc43f in /usr/bin/clickhouse
2. DB::ReplicatedMergeTreeBlockOutputStream::write(DB::Block const&) @ 0xfd72559 in /usr/bin/clickhouse
3. DB::PushingToViewsBlockOutputStream::write(DB::Block const&) @ 0xf24a7b4 in /usr/bin/clickhouse
4. DB::AddingDefaultBlockOutputStream::write(DB::Block const&) @ 0xf25476b in /usr/bin/clickhouse
5. DB::SquashingBlockOutputStream::finalize() @ 0xf254d8c in /usr/bin/clickhouse
6. DB::SquashingBlockOutputStream::writeSuffix() @ 0xf254e09 in /usr/bin/clickhouse
7. DB::TCPHandler::processInsertQuery(DB::Settings const&) @ 0xfef3710 in /usr/bin/clickhouse
8. DB::TCPHandler::runImpl() @ 0xfeebfd9 in /usr/bin/clickhouse
9. DB::TCPHandler::run() @ 0xfefe399 in /usr/bin/clickhouse
10. Poco::Net::TCPServerConnection::start() @ 0x125b865f in /usr/bin/clickhouse
11. Poco::Net::TCPServerDispatcher::run() @ 0x125ba071 in /usr/bin/clickhouse
12. Poco::PooledThread::run() @ 0x126f0799 in /usr/bin/clickhouse
13. Poco::ThreadImpl::runnableEntry(void*) @ 0x126ec5fa in /usr/bin/clickhouse
14. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
15. __clone @ 0xfe9fd in /usr/lib64/libc-2.17.so

**Comment by alexey-milovidov** [comment]
@gelezayka It must be an error in inserted data - more than 500 distinct months don't look realistic.

**Comment by zdyj3170101136** [comment]
is there any update? same problem
