### ISSUE TITLE
How to append an element after each array in a 2-D Array

### ISSUE THREAD

**Issue by JIANCHUJUN** [ClickHouse/ClickHouse#24014]
Suppose we have two arrays with the same length.  
A = [[1,2],[3,4]].  
B = [5,6].  
Is there a easy way to get a new array C = [[1,2,5],[3,4,6]]?    
     
Generally,   
if A is with a shape of (n,a) and B is with a shape of (n,b),    
can we get a new array C with a shape of (n,a+b)?

**Comment by l1t1** [comment]
arrayMap(x,y->arrayConcat(x,[y])), [[1,2],[3,4]],[5,6])

**Comment by l1t1** [comment]
select arrayMap(x,y->arrayPushBack(x,y), [[1,2],[3,4]],[5,6])

**Comment by JIANCHUJUN** [comment]
Thanks! It solves the prolem.
