### ISSUE TITLE
Compilation of correlated subquery failed

### ISSUE THREAD

**Issue by dgzdot** [ClickHouse/ClickHouse#24039]
A query with correlated subquery failed at compile time.

clickhouse version: 21.4.3.21

repro steps：
The table schame comes from TPCH.
CREATE TABLE tpch.customer
(
    `c_custkey` Int32,
    `c_name` String,
    `c_address` String,
    `c_nationkey` Int32,
    `c_phone` String,
    `c_acctbal` Decimal(15, 2),
    `c_mktsegment` String,
    `c_comment` String
)
ENGINE = MergeTree
ORDER BY c_custkey
SETTINGS index_granularity = 8192;

CREATE TABLE tpch.orders
(
    `o_orderkey` Int32,
    `o_custkey` Int32,
    `o_orderstatus` String,
    `o_totalprice` Decimal(15, 2),
    `o_orderdate` Date,
    `o_orderpriority` String,
    `o_clerk` String,
    `o_shippriority` Int32,
    `o_comment` String
)
ENGINE = MergeTree
ORDER BY o_orderkey
SETTINGS index_granularity = 8192;

Query: 
SELECT c_custkey
FROM customer
WHERE 1000000 < (
    SELECT SUM(o_totalprice)
    FROM orders
    WHERE o_custkey = c_custkey 
);

Exception: 
DB::Exception: Missing columns: 'c_custkey' while processing query: 'SELECT sum(o_totalprice) FROM orders WHERE o_custkey = c_custkey', required columns: 'o_custkey' 'o_totalprice' 'c_custkey', maybe you meant: ['o_custkey','o_totalprice','o_custkey']: While processing (SELECT sum(o_totalprice) FROM orders WHERE o_custkey = c_custkey) AS _subquery9: While processing 1000000 < ((SELECT sum(o_totalprice) FROM orders WHERE o_custkey = c_custkey) AS _subquery9).

**Comment by dgzdot** [comment]
@alexey-milovidov Hi, Sorry to interrupt you. Is there something wrong with my SQL or does it not support this feature

**Comment by alexey-milovidov** [comment]
ClickHouse does not support correlated subqueries.

**Comment by alexey-milovidov** [comment]
#6697
