### ISSUE TITLE
how to pass client settings such like max_memory_useage for  http query

### ISSUE THREAD

**Issue by windylcx** [ClickHouse/ClickHouse#24034]
in some cases,i can only run select  query via http interface ,like curl or wget,but some times it will out of memory limit

how to set these client settings just like in the clickhouse-client when using http interface? 

by setting  a small value in settings at the end of  select  query,it shows Memory limit (for query) exceeded

SELECT
    CAST('2021-05-10', 'date') AS log_date,
    countDistinct(map_uid) AS uid_cnt
FROM
(
    SELECT
        map_uid,
        countDistinct(type) AS type_cnt
    FROM
    (
        SELECT
            map_uid,
            if(os_type = 'Mobile', 'mobile', 'desktop') AS type
        FROM login
        WHERE (toDate(log_time) >= subtractDays(CAST('2021-05-10', 'date'), 28)) AND (toDate(log_time) <= subtractDays(CAST('2021-05-10', 'date'), 1))
        GROUP BY
            map_uid,
            type
    )
    GROUP BY map_uid
)
WHERE type_cnt = 2
GROUP BY log_date
SETTINGS max_memory_usage = 20

↓ Progress: 12.01 million rows, 156.14 MB (37.41 million rows/s., 486.35 MB/s.)  0%
Received exception from server (version 20.9.3):
Code: 241. DB::Exception: Received from  DB::Exception: Received from clickhouse_node4_4_1:9000. DB::Exception: Memory limit (for query) exceeded: would use 4.22 MiB (attempt to allocate chunk of 4421564 bytes), maximum: 20.00 B.

but i change the  max_memory_usage value to a very big value such as 10000000000000000, it doesn't work.

finaly it show the errors:
memory limit Received exception from server (version 20.9.3):
Code: 241. DB::Exception: Received from 1 DB::Exception: Memory limit (for query) exceeded: would use 9.38 GiB (attempt to allocate chunk of 133939184 bytes), maximum: 9.31 GiB: While executing AggregatingTransform.

and i use set max_memory_usage=10000000000000;  then run the query it works.

so ,how to set the client settings via http interface ,pls help thx.

**Comment by alexey-milovidov** [comment]
In URL parameter:

`...&max_memory_usage=10000000000000`

**Comment by windylcx** [comment]
> In URL parameter:
> 
> `...&max_memory_usage=10000000000000`

it works, thank you !
