### ISSUE TITLE
DB::Exception: Bad get: has UInt64, requested String (version 21.4.6.55 (official build))

### ISSUE THREAD

**Issue by HuaWorld** [ClickHouse/ClickHouse#24044]
Hi, everyone
I now want to create a ClickHouse table whose engine is MySQL, but there is a problem with the title when I create the table fields
Here is my DDL:
```
create table mysql_engine_tbl01_hive_tbls(
TBL_ID             Int32                 ,
CREATE_TIME        Int32                      ,
DB_ID              Int8                ,
LAST_ACCESS_TIME      Int8                   ,
OWNER              String                 ,
RETENTION          Int8                       ,
SD_ID              Int32               ,
TBL_NAME           String              ,
TBL_TYPE           String                ,
VIEW_EXPANDED_TEXT String                   ,
VIEW_ORIGINAL_TEXT String                   
)
ENGINE = MySQL('host'='192.xxx.xxx.201:3306','hive','tbls','xx','xx')
```

The error message：
2021.05.12 08:25:33.386479 [ 49 ] {a5195733-a362-4e4e-ad7e-838664ba436c} <Trace> ContextAccess (default): Access granted: CREATE TABLE ON xiaohu.mysql_engine_tbl01_hive_tbls
2021.05.12 08:25:33.386512 [ 49 ] {a5195733-a362-4e4e-ad7e-838664ba436c} <Trace> ContextAccess (default): Access granted: MYSQL ON *.*
2021.05.12 08:25:33.387191 [ 49 ] {a5195733-a362-4e4e-ad7e-838664ba436c} <Error> executeQuery: Code: 170, e.displayText() = DB::Exception: Bad get: has UInt64, requested String (version 21.4.6.55 (official build)) (from 10.32.0.1:19735) (in query: create table mysql_engine_tbl01_hive_tbls( TBL_ID String, CREATE_TIME String, DB_ID String, LAST_ACCESS_TIME String, OWNER String, RETENTION String, SD_ID String, TBL_NAME String, TBL_TYPE String, VIEW_EXPANDED_TEXT String, VIEW_ORIGINAL_TEXT String, IS_REWRITE_ENABLED String ) ENGINE = MySQL('host'='xxxx:3306','hive','tbls','xxx','xx')), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x87f714a in /usr/bin/clickhouse
1. auto& DB::Field::safeGet<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >() @ 0x88ddf56 in /usr/bin/clickhouse
2. ? @ 0xf9c3617 in /usr/bin/clickhouse
3. DB::StorageFactory::get(DB::ASTCreateQuery const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, DB::Context&, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, bool) const @ 0xf917e09 in /usr/bin/clickhouse
4. DB::InterpreterCreateQuery::doCreateTable(DB::ASTCreateQuery&, DB::InterpreterCreateQuery::TableProperties const&) @ 0xf1d56f8 in /usr/bin/clickhouse
5. DB::InterpreterCreateQuery::createTable(DB::ASTCreateQuery&) @ 0xf1d252f in /usr/bin/clickhouse
6. DB::InterpreterCreateQuery::execute() @ 0xf1d7b90 in /usr/bin/clickhouse
7. ? @ 0xf7356e2 in /usr/bin/clickhouse
8. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, DB::Context&, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>) @ 0xf738d95 in /usr/bin/clickhouse
9. DB::HTTPHandler::processQuery(DB::Context&, DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::__1::optional<DB::CurrentThread::QueryScope>&) @ 0xfe7da52 in /usr/bin/clickhouse
10. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0xfe810bd in /usr/bin/clickhouse
11. DB::HTTPServerConnection::run() @ 0xff077af in /usr/bin/clickhouse
12. Poco::Net::TCPServerConnection::start() @ 0x125b865f in /usr/bin/clickhouse
13. Poco::Net::TCPServerDispatcher::run() @ 0x125ba071 in /usr/bin/clickhouse
14. Poco::PooledThread::run() @ 0x126f0799 in /usr/bin/clickhouse
15. Poco::ThreadImpl::runnableEntry(void*) @ 0x126ec5fa in /usr/bin/clickhouse
16. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
17. clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so

**Comment by alexey-milovidov** [comment]
Duplicate #11154.

**Comment by alexey-milovidov** [comment]
This is incorrect:
`MySQL('host'='192.xxx.xxx.201:3306','hive','tbls','xx','xx')`
Replace to:
MySQL('192.xxx.xxx.201:3306','hive','tbls','xx','xx')
