### ISSUE TITLE
function arrayProduct doesn't exsit

### ISSUE THREAD

**Issue by l1t1** [ClickHouse/ClickHouse#24041]
SELECT arrayProduct([1,2,3,4,5,6]) as res

DB::Exception: Unknown function arrayProduct. Maybe you meant: ['arrayReduce','arrayCount']: While processing arrayProduct([1, 2, 3, 4, 5, 6]) AS res (version 21.5.1.6541)

**Comment by den-crane** [comment]
arrayProduct has been merged into 21.6 branch only.

**Comment by l1t1** [comment]
it returns a value with type float64 and overflow when running
select arrayProduct(range(1,22)) a, toTypeName(a)

14197454024290337000 | Float64
-- | --

the right answer should be
51090942171709440000

**Comment by den-crane** [comment]
right answer 1.1240007277776077e21

https://www.wolframalpha.com/input/?i=factorial+22
1124000727777607680000

**Comment by l1t1** [comment]
range(1,22) is an array from 1 to 21
