### ISSUE TITLE
Using row policy in combination with LIMIT an result in an endless loop.

### ISSUE THREAD

**Issue by dstruck** [ClickHouse/ClickHouse#24057]
When using a row policy like `CREATE ROW POLICY pol1 ON CLUSTER cluster1 ON test USING toDate(timestamp) >= date_sub(YEAR, 1, today()) TO user1;` running queries as the role **user1** with **LIMIT** (example: `SELECT id FROM test LIMIT 10`) do not finish and the progress bar endlessly jumps back to the left. Other queries like `SELECT count() FROM test;` still run as expected.

This has been tested on version **21.4.6.55**.

Unfortunately we cannot replicate this behavior in a test setup with a subset of the production data. Neither did we find entries in the error log file.

**Comment by alexey-milovidov** [comment]
Could you please share some subset of ClickHouse logs during execution of the problematic query?

**Comment by dstruck** [comment]
Sorry for the late response. Issue still persists in the latest 22.4.5 release.

What kind of logs would you need?
