### ISSUE TITLE
NaN compare error

### ISSUE THREAD

**Issue by maliangzhu** [ClickHouse/ClickHouse#24078]
```sql
create table t1 ( a float) engine=Log;
insert into t1 values('NaN');
select * from t1 where a = a+1;
```
```
expect : 1 row
real: 0 row
```

commit 32c263aa9f2cbf0982426ea53625ad33fde6f479 seems fixed NaN compare in hashtab

but scan operator seems still error

Does modify `bool_if_safe_conversion`  can fix the problem?

**Comment by MaceWindu** [comment]
another case

```sql
-- doesn't work
select * from t1 where a = toFloat32(NaN)
-- works
select * from t1 where toFloat32(NaN) = toFloat32(NaN)

```

**Comment by den-crane** [comment]
isNaN https://clickhouse.com/docs/en/sql-reference/functions/other-functions/#isnanx

```
SELECT
    nan = (nan + 1),
    isNaN(nan) = isNaN(nan + 1)

Query id: b874a0e6-64eb-415b-9213-43f8fb324d5b

┌─equals(nan, plus(nan, 1))─┬─equals(isNaN(nan), isNaN(plus(nan, 1)))─┐
│                         0 │                                       1 │
└───────────────────────────┴─────────────────────────────────────────┘

```

**Comment by den-crane** [comment]
Use isNaN and isInfinite if you need to check float for NaN of Infinite

**Comment by MaceWindu** [comment]
While I can agree that nan/infinity values should be detected using isnan/isinfinity functions, it does not answer why `nan = nan`  or `inf = inf`r eturns `true` for literals, but not for table lookups
