### ISSUE TITLE
Should uniq or uniqCombined be used for sharded, aggregated uniques?

### ISSUE THREAD

**Issue by genzgd** [ClickHouse/ClickHouse#24072]
the documentation for uniqCombined says:

```
Compared to the uniq function, the uniqCombined:
Consumes several times less memory.
Calculates with several times higher accuracy.
Usually has slightly lower performance. In some scenarios, uniqCombined can perform better than uniq, for example, with distributed queries that transmit a large number of aggregation states over the network.
```

The documentation for uniq says:

```
We recommend using this function in almost all scenarios.
```

We have "distributed queries that transmit a large number of aggregation states" -- so should we be using uniqCombined?  If so should the "uniq" recommendation be updated to reflect that?  Or is the uniqCombined documentation out of date?

(On a side note, I don't suppose there's a way to convert uniqState to uniqCombinedState for existing data?)

**Comment by den-crane** [comment]
>If so should the "uniq" recommendation be updated to reflect that? 
>Or is the uniqCombined documentation out of date?

Milovidov: 
uniqCombined with default values is somewhat more accurate than uniq.
uniqCombined is more accurate and takes up less memory and disk space. But usually slower.


I (Denis) suggest to try `uniqCombined64(15)` -- it boosts queries up to 10 times for my distributed queries (1Gbit network).
And the error is <2% in comparison with uniqExact.

Also about states:
```
disk space for example
2.2M    uniqHLL12State
58M   uniqCombinedState(20)
15M   uniqCombinedState(15)
140M    uniqState

Speed
SELECT uniqMerge(us) AS unique FROM mvz WHERE z = '555' GROUP BY d
┌─unique─┐
│ 297580 │
└────────┘
1 rows in set. Elapsed: 0.031 sec.

SELECT uniqHLL12Merge(uh) AS unique FROM mvz WHERE z = '555' GROUP BY d
┌─unique─┐
│ 297323 │
└────────┘
1 rows in set. Elapsed: 0.002 sec.

SELECT uniqCombinedMerge15(uc) AS unique FROM mvz WHERE z = '555' GROUP BY d
┌─unique─┐
│ 298636 │
└────────┘
1 rows in set. Elapsed: 0.003 sec.
```


>(On a side note, I don't suppose there's a way to convert uniqState to uniqCombinedState for existing data?)

No way. 
AMilovidov thinks that it's possible in theory, he can do it :) (select states into application / recalculate / insert into another table).

**Comment by genzgd** [comment]
I'll give uniqCombined(64) a shot.  Thanks for the detailed response!
