### ISSUE TITLE
various time values from now()

### ISSUE THREAD

**Issue by aich1983** [ClickHouse/ClickHouse#24070]
This query returns various values of time (screenshot attached)
{code:sql}
select now(), toStartOfHour(now()), toHour(now()), toString(now()), toDateTime(now())
{code}
Why is the difference between toHour(now()) and toStartOfHour(now())?
Also attached local settings.
version DBMS: ClickHouse (ver. 20.5.3.27)
Case sensitivity: plain=exact, delimited=exact
Driver: ru.yandex.clickhouse-jdbc (ver. 0.1, JDBC0.1)
Utility for querying is Datagrip
Workstation is MacBook Pro
![изображение_2021-05-12_214345](https://user-images.githubusercontent.com/84098198/118027915-20e9d500-b36b-11eb-84bf-14ad3ca6c72a.png)
![изображение_2021-05-12_214428](https://user-images.githubusercontent.com/84098198/118027988-3a8b1c80-b36b-11eb-8847-121ac4b72cff.png)

**Comment by den-crane** [comment]
It's not unexpected. Everything here is expected.

JDBC driver converts time to client's timezone. But does not convert Strings. Strings are converted to TZned strings by a clickhouse server which have different timezone. The same for toHour.

JDBC/Datagrip related question https://github.com/ClickHouse/clickhouse-jdbc/issues/202
