### ISSUE TITLE
GRANT SELECT if column not in restricted tuple

### ISSUE THREAD

**Issue by bralbral** [ClickHouse/ClickHouse#24071]
According documentation : 

```
GRANT SELECT(x,y) ON db.table TO john WITH GRANT OPTION
It means that john has the permission to execute:

SELECT x,y FROM db.table.
SELECT x FROM db.table.
SELECT y FROM db.table.
john can’t execute SELECT z FROM db.table. The SELECT * FROM db.table also is not available. Processing this query, ClickHouse doesn’t return any data, even x and y. The only exception is if a table contains only x and y columns. In this case ClickHouse returns all the data.
```

Is there a way to return column z empty, filled with null, or not return during processing? 
`SELECT x,y,z FROM db.table` now returns exception. 
This behavior is incomprehensible

**Comment by e-mars** [comment]
Hi @bralbral,

The current behavior is to return an error when columns selected are not included in the `GRANT SELECT`:
i believe this is the exception you are referencing:
```
Code: 497. DB::Exception: user_xy: Not enough privileges. To execute this query it's necessary to have grant SELECT(id, x, y, z) ON db1.table4. (ACCESS_DENIED) (version 22.1.3.7 (official build))
```
this is produced when using something like `SELECT * FROM db1.table4` is used.

The behavior is designed to be similar to what is implemented in other database systems.
**Examples**
PostgreSQL behavior:
```
db1=> select * from table4;
ERROR:  permission denied for relation table4
db1=> select x,y from table4;
  x  |  y
-----+-----
 abc | def
(1 row)
```

MySQL behavior:
```
mysql> select * from db1.table4;
ERROR 1143 (42000): SELECT command denied to user 'user_xy'@'localhost' for column 'id' in table 'table4'
mysql> select x,y from db1.table4;
+------+------+
| x    | y    |
+------+------+
| abc  | def  |
+------+------+
1 row in set (0.00 sec)
```

if you would like to suggest a different behavior, please submit an enhancement request using the template "Feature Request" when creating a new issue.

thanks.
