### ISSUE TITLE
Innerworking of force_restore_data 

### ISSUE THREAD

**Issue by ghuname** [ClickHouse/ClickHouse#24086]
Lets say that I have a cluster with two replicated nodes: node1 and node2.
Lets say that after stopping clickhouse-server on node1 I have delete everything in the /var/lib/clickhouse/data folder,  and with sudo -u clickhouse touch /var/lib/clickhouse/flags/force_restore_data created a restore flag.

Now with starting a clickhouse-server on node1, can I expect that all data will be replicated from node2 to node1?

**Comment by den-crane** [comment]
Yes.

**Comment by ghuname** [comment]
@den-crane  

Dan, thank you for an answer.

We can see that force_restore_data file is deleted. 
How to check weather restore is still in progress or it is completed?
At the moment, some tables are replicated but some aren't.
Do we have an indicator that both replicas are in sync?
How to check that?

Best regards.

**Comment by den-crane** [comment]
>We can see that force_restore_data file is deleted.

That's is expected.

>Do we have an indicator that both replicas are in sync?
>How to check that?

select * from system.replication_queue

chhost:8123/replicas_status

select absolute_delete from system.replicas

**Comment by ghuname** [comment]
@den-crane 
SELECT * FROM system.replication_queue, returns 14923 rows.

This number goes few up and few down, but basically it is stucked.
How to treat this rows? How to force replication?

curl localhost:8123/replicas_status returns something like this:
database.kpi:     Absolute delay: 0. Relative delay: 0.
database.boot:       Absolute delay: 1620994060. Relative delay: 0.
database.server:        Absolute delay: 1620994061. Relative delay: 1620270045.

What to do with these delays?

**Comment by den-crane** [comment]
can you provide the output of https://kb.altinity.com/altinity-kb-setup-and-maintenance/altinity-kb-replication-queue

and `select version()`

**Comment by ghuname** [comment]
@den-crane 
I would have send the output of the query to you, but as both nodes in the shard were unstable, we had to recover everything, and during recovering parts are up to 500 per table now.

Anyway, we are a bit disappointed with the clickhouse and the way it handles database parts.
These servers were under have load caused by huge number of selects.
At one moment when I summed threads from system.processes I come to the 4.5k for 100 queries.
If database relays on merging, than merging should be prioritized.
In this case, with parts growth due to heavy load, it was a highway to hell.

Regarding version:
ClickHouse client version 19.16.3.6.
Connected to ClickHouse server version 19.16.3 revision 54427.

Anyway, both nodes are stable now. Thank you Den for  all information you have provided..

**Comment by ghuname** [comment]
Is there a way to turn of replica for serving distributed queries, and to stop consuming kafka table, in order to give to the database a chance to merge parts, and afterwards to continue digesting kafka topics and serving as replica.

**Comment by den-crane** [comment]
> Anyway, we are a bit disappointed with the clickhouse and the way it handles database parts.
> These servers were under have load caused by huge number of selects.
> At one moment when I summed threads from system.processes I come to the 4.5k for 100 queries.
> If database relays on merging, than merging should be prioritized.
> In this case, with parts growth due to heavy load, it was a highway to hell.

What are you talking about? What merges? Your original question was about restoring a replica.

**Comment by ghuname** [comment]
It is indirectly related, and basically a long and complicated story.
We had to restore nodes, and during restoration, we found problems with huge number of parts in old clickhouse data directory.
After restoration, parts are under control, but looks like clickhouse wasn't good enough to keep them under control before restoration.

**Comment by den-crane** [comment]
https://kb.altinity.com/altinity-kb-useful-queries/altinity-kb-number-of-active-parts-in-a-partition
