### ISSUE TITLE
Use MaterializeMySQL synchronization problem: mysqlxx::UseQueryResult must be contain theCreate Table, Table columns.

### ISSUE THREAD

**Issue by zengxc8384** [ClickHouse/ClickHouse#24081]
When I used ClickHouse's MaterializeMySQL feature to synchronize data from MySQL to ClickHouse, I had some problems. The Click House version I'm using is 20.10.3.30, and the MySQL version I'm using is 5.7.20-log.

The SQL statement I executed is as follows:

SET allow_experimental_database_materialize_mysql=1; 
CREATE DATABASE if not exists test ENGINE = MaterializeMySQL('x.x.x.x:3306', 'test', 'user', 'test');

After I executed the SQL statement, I saw the following information from the error log /var/log/clickhouse-server/clickhouse-server.err. Log:

2021.05.13 15:15:45.426319 [ 14049 ] {} <Error> MaterializeMySQLSyncThread: Code: 20, e.displayText() = DB::Exception: mysqlxx::UseQueryResult must be contain theCreate Table, Table columns., Stack trace (when copying this message, always include the lines below):

0. DB::MySQLBlockInputStream::initPositionMappingFromQueryResultStructure() @ 0xf688d5b in /usr/bin/clickhouse
1. DB::MySQLBlockInputStream::MySQLBlockInputStream(mysqlxx::Pool::Entry const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Block const&, unsigned long, bool, bool) @ 0xf68842d in /usr/bin/clickhouse
2. DB::MaterializeMetadata::MaterializeMetadata(mysqlxx::Pool::Entry&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool&) @ 0xe910f2e in /usr/bin/clickhouse
3. DB::MaterializeMySQLSyncThread::prepareSynchronized() @ 0xe8b20c4 in /usr/bin/clickhouse
4. DB::MaterializeMySQLSyncThread::synchronization() @ 0xe8b1824 in /usr/bin/clickhouse
5. ? @ 0xe8d0e32 in /usr/bin/clickhouse
6. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x85349bf in /usr/bin/clickhouse
7. ? @ 0x85384e3 in /usr/bin/clickhouse
8. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
9. __clone @ 0xfe96d in /usr/lib64/libc-2.17.so
 (version 21.3.10.1 (official build))

**Comment by weiyongyuan** [comment]
I also faced this probloem .The ClickHouse'version is 21.3.3.14.

**Comment by kasnet** [comment]
I also faced this problem.I find that the reason is view in mysql.
