### ISSUE TITLE
Stream transfer data

### ISSUE THREAD

**Issue by vixa2012** [ClickHouse/ClickHouse#2408]
Hello dier support. I am working with Clickhouse on nodejs and using special driver recommended on your site.
https://github.com/apla/node-clickhouse

As I can see, the stream transmits only one row per time. Transmit of 1,5 million of rows takes 25 sec.
It would be very good if Stream could receive a bulk of rows per time.

Could you tell me, maybe it is a clickhouse configuration problem, or bad driver?

**Comment by SkeLLLa** [comment]
I don't know if it still relevant to you, but as far as I can see both those clients for node.js that listed on official site have very poor quality. Also they use http interface that's not very fast. So as a result all performance that clickhouse has is lost in client libraries.
