### ISSUE TITLE
Can you make postgres interface?

### ISSUE THREAD

**Issue by javawin** [ClickHouse/ClickHouse#24083]
Can you make postgres interface?

**Comment by alexey-milovidov** [comment]
We already have, see `config.xml`:

```
    <!-- Compatibility with PostgreSQL protocol.
         ClickHouse will pretend to be PostgreSQL for applications connecting to this port.
    -->
    <postgresql_port>9005</postgresql_port>
```

**Comment by javawin** [comment]
> We already have, see `config.xml`:
> 
> ```
>     
>     <postgresql_port>9005</postgresql_port>
> ```

Огромное спасибо за оперативный ответ, и главное, за проделанную работу.
