### ISSUE TITLE
I can not connect via postgres interface

### ISSUE THREAD

**Issue by javawin** [ClickHouse/ClickHouse#24094]
I can not connect via postgres interface
message
SSL error: Remote host terminated the handshake
  Remote host terminated the handshake
  Remote host terminated the handshake
    SSL peer shut down incorrectly
    SSL peer shut down incorrectly

ch and mariadb connection work without problem
may be you have advice to connect to ch as postgres

**Comment by alexey-milovidov** [comment]
How do you connect?

**Comment by javawin** [comment]
> How do you connect?

datagrip and dbeaver with same result. From another host.
I have ordinary standart postgres in ch host.

**Comment by den-crane** [comment]
JDBC driver is not supported by postgresql wire protocol.

**Comment by javawin** [comment]
>JDBC driver is not supported by postgresql wire protocol.
Native postgres use anothe protocol? Its work. 
How i can use you postgres version? What kind drivers i can use?

**Comment by javawin** [comment]
PHP work with ch as postgres.

**Comment by javawin** [comment]
Php work.

**Comment by javawin** [comment]
that won't work, am I getting it right? Have you only implemented the "Select" syntakisis?
https://prnt.sc/12wtinu

**Comment by zhicwu** [comment]
@javawin, you can use connection string like below:
``` text
jdbc:postgresql://<host>:<port>/<db>?user=<user>&password=<password>&ssl=false&sslmode=disable&preferQueryMode=simple
```

[This](https://github.com/ClickHouse/clickhouse-jdbc/blob/d3db68c73bb1e81c54e3ff030856998069b2aee4/clickhouse-benchmark/src/main/java/tech/clickhouse/benchmark/JdbcDriver.java#L31) works for me.

**Comment by Le6688** [comment]
我也碰到这个问题了，你是最后是怎么解决的啊？
