### ISSUE TITLE
Load data table inmemory and increase response time

### ISSUE THREAD

**Issue by mbtolou** [ClickHouse/ClickHouse#24099]
hi.
I test scenario that load 1 billion record in mongodb and test query performance.
like this :

query 1 : 
```
select *
from test_table
limit 10000
```

query 2:
```
select server_id,sum(use_a)
from test_table
group by server_id
```

result of mongodb and clickhouse : 

|            | Q1    | Q2    |
|------------|-------|-------|
| Clickhouse | 600ms | 1.7s  |
| MongoDB    | 10ms  | 400ms |

I search and found mongodb load data in RAM and increase performance .
question:
how can load data inmemory for increase performance ?

**Comment by den-crane** [comment]
What engine do you use for Clickhouse  table ?

**Comment by mbtolou** [comment]
MergeTree

**Comment by den-crane** [comment]
Can you show the output of

```
set send_logs_level='trace';

select server_id,sum(use_a)
from test_table
group by server_id format Null;

```
