### ISSUE TITLE
How many memory will ClickHouse server use?

### ISSUE THREAD

**Issue by awesomeleo** [ClickHouse/ClickHouse#24115]
There are 4 configurations about memory usage in ClickHouse server?  But I am not very clear about the relationship among them.

There are max_server_memory_usage, uncompressed_cache_size and mark_cache_size in config.xml , and max_memory_usage in users.xml. Does the max_server_memory_usage include all other three memory usage? Is max_server_memory_usage the total memory limits in ClickHouse Server? Is the max_memory_usage  also included in  max_server_memory_usage?

If I have a sever wiht 32GB memory, how should I config the memory usage？

I run a benchmark and sometimes i get oom currently.
The ClickHouse version is 21.2.3.15-stable

**Comment by filimonov** [comment]
check https://kb.altinity.com/altinity-kb-setup-and-maintenance/altinity-kb-memory-configuration-settings

**Comment by awesomeleo** [comment]
Thanks a lot.
