### ISSUE TITLE
MemoryTracker should be used in operator new in a light way

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#24110]
**Use case**
Very rare deadlock is possible.

**Describe the solution you'd like**
If MemoryTracker is called from operator new, don't:
- log anything (1);
- throw (2).

(1) is strictly necessarily to avoid deadlock;
(2) is almost necessarily to avoid tons of peculiarities in destructors.

**Comment by alexey-milovidov** [comment]
CC @azat

**Comment by azat** [comment]
> If MemoryTracker is called from operator new, don't log anything

Right now the only log message that is done from this context is memory usage (when it grows above the threshold), or I missed something?

>If MemoryTracker is called from operator new, don't throw - is almost necessarily to avoid tons of peculiarities in destructors.

But how do you suggest implementing MEMORY_LIMIT_EXCEEDED error?

Also note, that MemoryTracker already does not throw if unwind is in progress, and this should cover lots of corner cases.
Do you have examples of other "peculiarities in destructors"?
