### ISSUE TITLE
When I run one big sql (over 1.3M)  on clickhouse,the problem 'Max query size exceeded' happened

### ISSUE THREAD

**Issue by cwh2008** [ClickHouse/ClickHouse#24114]
Hi,
When I run one big sql (over 1.3M)  on clickhouse using JDBC and client,the problem 'Max query size exceeded' both  happened.
  I don't find the parameter to set to resove this question.
ClickHouse exception, code: 62, host: 9.23.28.116, port: 8123; Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 262145 (',') (line 1099, col 63): ,. Max query size exceeded: ',' (version 21.4.6.55 (official build))
       I'm pleasure if u have a solution .
                Best Regard.
                              Eward

**Comment by den-crane** [comment]
https://clickhouse.tech/docs/en/operations/settings/settings/#settings-max_query_size

**Comment by den-crane** [comment]
```
cat /etc/clickhouse-server/users.d/m.xml
<?xml version="1.0"?>
<yandex>
    <profiles>
        <default>
            <max_query_size>10000000</max_query_size>
        </default>
    </profiles>
</yandex>
```

**Comment by cwh2008** [comment]
Based on your advice,I solved this problem,Thanks a Lot.

Other，the problem above is solved,but the other problem happended.,and I get the solution:
Q:
ClickHouse exception, code: 168, host: , port: 8123; Code: 168, e.displayText() = DB::Exception:
 AST is too big. Maximum: 50000 (version 21.4.6.55 (official build))

A:Maximum number of elements in a query syntactic tree. If exceeded, an exception is thrown. In the same way as the previous setting, it is checked only after parsing the query. By default, 10,000.
Add to user.xml  or users.d :
<max_ast_elements>10000000</max_ast_elements>
<max_expanded_ast_elements>10000000</max_expanded_ast_elements>
