### ISSUE TITLE
Insert query does not support PostgreSQL non-default schemas

### ISSUE THREAD

**Issue by nshah14285** [ClickHouse/ClickHouse#24149]
Hello,

On clickhouse side, I try to insert a query like

```
Insert INTO TABLE FUNCTION postgresql('192.168.0.1:5432', 'test', 'user', 'user1', 'password', 'tsweb') (id, email) values (5,'5@n.com');
```

**and get the error below**

> Received exception from server (version 21.4.6):
Code: 1001. DB::Exception: Received from localhost:9000. DB::Exception: pqxx::undefined_table: ERROR:  relation "user" does not exist

If I remove the schema 'tsweb' from table function then it throws error like

> Received exception from server (version 21.4.6):
Code: 60. DB::Exception: Received from localhost:9000. DB::Exception: PostgreSQL table test."user" does not exist.

Even [documentation](https://clickhouse.tech/docs/en/sql-reference/table-functions/postgresql/) does not mentioned about the schema in the Insert query.

Thanks

**Comment by nshah14285** [comment]
@kssenii 
Any update on this?

Thanks in Advance.

**Comment by kssenii** [comment]
@nshah14285 I'll do in the next few days, it just requires more changes than it seems.

**Comment by nshah14285** [comment]
@kssenii 
OK.
