### ISSUE TITLE
How to get seconds from a datetime?

### ISSUE THREAD

**Issue by alniks** [ClickHouse/ClickHouse#24145]
toRelativeSecondNum is no different from toUnixTimestamp, it ignores the second parameter (btw what's the meaning of it?) and depends only on the time zone of the server. The following query returns 4 equal numbers and they will be different from server to server depending on the server's time zone

```sql
select toRelativeSecondNum(toDateTime('2015-07-02 06:00:13')) as rs, toUnixTimestamp(toDateTime('2015-07-02 06:00:13')) as ux, toRelativeSecondNum(toDateTime('2015-07-02 06:00:13'), 'Europe/Minsk') as rsMinsk, toRelativeSecondNum(toDateTime('2015-07-02 06:00:13'), 'UTC') as rsUTC
```

The only reliable way to get seconds I see is to get years multiply by seconds in a year add months multiplied by seconds in a month, etc.

**Comment by filimonov** [comment]
Fix

```
SELECT
    toRelativeSecondNum(toDateTime('2015-07-02 06:00:13')) AS rs,
    toUnixTimestamp(toDateTime('2015-07-02 06:00:13')) AS ux,
    toRelativeSecondNum(toDateTime('2015-07-02 06:00:13', 'Europe/Minsk')) AS rsMinsk,
    toRelativeSecondNum(toDateTime('2015-07-02 06:00:13', 'UTC')) AS rsUTC

Query id: 7a004b5b-4ce8-43f5-af2d-1bf6e1fc2a6e

┌─────────rs─┬─────────ux─┬────rsMinsk─┬──────rsUTC─┐
│ 1435809613 │ 1435809613 │ 1435806013 │ 1435816813 │
└────────────┴────────────┴────────────┴────────────┘

1 rows in set. Elapsed: 0.001 sec. 
```

You need to pass timezone when you convert the string to timestamp, i.e. inside toDateTime function. Otherwise, the conversion of human-readable time to the unix timestamp will happen according to server default rules.

**Comment by filimonov** [comment]
BTW: the name of the issue is misleading a bit. Number of seconds since what?

**Comment by alniks** [comment]
The real problem is not to get seconds from the time returned by toDateTime, but from times stored in DB. Suppose we have a DateTime column 'created', toRelativeSecondNum(created, 'Europe/Moscow') will be same as toRelativeSecondNum(created, 'UTC'), so the meaning of the second parameter is unclear. 

The second problem is that toRelativeSecondNum(created) will give different values for the same datetime on different servers depending on a server's timezone. And it's not clear why. 

I've found a reliable way to get seconds from a date, but this requires to convert a date to a string, which looks weird.

And you are right - the naming of the function and description in the docs are confusing.

**Comment by alexey-milovidov** [comment]
`toRelativeSecondNum` is returning the number of seconds from the fixed but unspecified point in time.
To obtain the number of seconds from specified point in time, simply subtract two DateTime values:

`SELECT now() - toDateTime('2000-01-01 00:00:00')`

https://gh-api.clickhouse.tech/play?user=play#U0VMRUNUIG5vdygpIC0gdG9EYXRlVGltZSgnMjAwMC0wMS0wMSAwMDowMDowMCcp
