### ISSUE TITLE
MaterializeMySQL engine decimal overflow

### ISSUE THREAD

**Issue by gefire** [ClickHouse/ClickHouse#24143]
clickhouse version :  21.4.6.55 
SELECT version()

Query id: f5f49ca2-9eae-48a2-848d-c973bdc25428

┌─version()─┐
│ 21.4.6.55 │
└───────────┘

1 rows in set. Elapsed: 0.005 sec. 

mysql version:  5.7.33-36-57-log

data in mysql : 
SELECT id,amount FROM agent_account_info aai WHERE id=198111479
+-----------+--------+
| id        | amount |
+-----------+--------+
| 198111479 |  0.090 |
+-----------+--------+
1 row in set (0.00 sec)

replication to clickhouse the data like ：

SELECT
    id,
    amount
FROM agent_account_info AS aai
WHERE id = 198111479

Query id: a1db3521-d5cb-4203-9c52-5378bca32368

┌────────id─┬──────────amount─┐
│ 198111479 │ -2147483712.445 │
└───────────┴─────────────────┘

1 rows in set. Elapsed: 0.018 sec. Processed 32.16 thousand rows, 1.69 MB (1.82 million rows/s., 95.48 MB/s.) 

amount type is decimal, looks like overflow.

but it not every records overflow。few records from replication sync like this.

what can i do get more detail info for this ？

can i get the MaterializeMySQL sql log in clickhouse ?

**Comment by RexIsMe** [comment]
I get the same problem, and have no idea about that. if someone can solve, attention me plz

**Comment by abyss7** [comment]
Please, provide CREATE TABLE statements in both DBs.

**Comment by alexey-milovidov** [comment]
No info provided.
