### ISSUE TITLE
[Question] Improving read query throughput

### ISSUE THREAD

**Issue by agaurav** [ClickHouse/ClickHouse#2414]
Read query throughput for small `select` queries seems to be too low (`max 30 qps`) for such a superb database. Comparing this to influxdb or prometheus, they are able to go upto 1500 for same query on same setup. Indeed for complex query involving million+ rows, clickhouse execution time is usually 100x better. 

Going through the architecture doc, only relevant part I can find was below:

> Internally, it is just a basic multithreaded server without coroutines, fibers, etc. Since the server is not designed to process a high rate of simple queries but is intended to process a relatively low rate of complex queries, each of them can process a vast amount of data for analytics.

Is there a config or "quick patch & compile" to increase the qps for simple select queries?

Or a more permanent solution, where a few threads can process large number of simple queries and rest reserved for complex queries.

 Will very much love to contribute in any way possible as it will immensely improve its potential as backend for live dashboards (with large number of graphs) with lots of simultaneous user sessions.

**Comment by meshpaul** [comment]
What are you using for dashboard grafana?

**Comment by meshpaul** [comment]
Also what are you using as metric collector to store in data in DB?

**Comment by meshpaul** [comment]
Also what ClickHouse user profile  are you using? ex https://github.com/yandex/ClickHouse/edit/master/docs/en/operations/settings/settings_profiles.md. 

In addition can you share the details on how you came up with such numbers? and mention things like hardware/vm and whole app stack for each use case?  How many concurrent queries etc?

**Comment by agaurav** [comment]
@meshpaul Both dashboard and metric collector are our own implementation at [archsaber](https://archsaber.io). Metric collector is in golang & dashboard in React+[dygraphs](https://github.com/danvk/dygraphs)+[crossfilter](http://crossfilter.github.io/crossfilter/)+d3

The given number are for [flowlog](https://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/flow-logs.html) analysis involving  
- ~4 million rows
- `Debian 9` vm 
- `2 logical cores`
- `8 GB RAM` .
-  Data on `NVMe-SSD` capable of `680,000` Read IOPS, `650 GB/s` read throughput

**Comment by agaurav** [comment]
@alexey-milovidov any thoughts on this ? 

Some insights on what might be the throttling the small read queries.

**Comment by ztlpn** [comment]
It is rather difficult to predict what the bottleneck is because we haven't spent much time optimizing for the case of many small queries. For example last time someone checked this case the bottleneck was surprisingly in generating `query_id` strings.

This means you need to profile. Try applying the load and determining if the server is CPU-bound or IO-bound. If it is CPU-bound, then what do tools like `perf top` say?

**Comment by agaurav** [comment]
@ztlpn It seems to be cpu bound as IO hardly crossed 4%  (both cpu & disk IO) while cpu was 100% on all cores and load avg also peaked to 125. 
I will try to profile the execution and come up with some code level insights.

**Comment by silviucpp** [comment]
I personally have different results than yours:

I created the following tables on 3 nodes (VM with 2 cores, 8 GB ram, no SSD):

```sql
CREATE DATABASE test;
CREATE TABLE test.collection_src (timestamp DateTime, username Nullable(String))
	   ENGINE = MergeTree
	   PARTITION BY toYYYYMM(timestamp)
	   ORDER BY timestamp
	   SETTINGS index_granularity = 8192;

CREATE TABLE test.collection AS test.collection_src ENGINE = Distributed(cluster_test_no_replica, test, collection_src ,rand());
```

In each node I inserted 1 raw (In the local MergeTree table):

```sql
INSERT INTO test.collection_src(timestamp, username) VALUES(toDateTime('2001-01-01 00:00:00'), 'jon');
```

Then I tested by sending to one of the ClickHouse nodes from a different machine the following queries over HTTP:

1. SELECT COUNT(*) FROM test.collection_src - got around 1440 q/s
2. SELECT COUNT(*) FROM test.collection - got around 643 q/s
3. SELECT COUNT(*) FROM remote('172.17.33.123,172.17.33.124,172.17.33.125', test, collection_src) - got around 530 q/s

Test one hits the local MergeTree, second one the distributed table (which will send the query to all 3 nodes in ck cluster) and third one is using the remote function.

Results seems logic as time hitting the local node only it's the fastest thing and also Distributed table is faster than remote as you can find also in documentation.

Silviu

**Comment by qoega** [comment]
If you still have questions about small query performance you can try to reproduce problem with actual version of ClickHouse and reopen this issue or create new one.
