### ISSUE TITLE
Documentation for arrayReduce function

### ISSUE THREAD

**Issue by harlinb** [ClickHouse/ClickHouse#2415]
It took me quite some time to figure out how to flatten nested arrays using the arrayReduce function.

eg.:

```
SELECT 
    [['query1'], ['query2']] AS queries, 
    [['hit1', 'hit2'], ['hit1']] AS hits, 
    arrayReduce('groupArrayArray', queries) AS queries_flat, 
    arrayReduce('groupArrayArray', hits) AS hits_flat, 
    arrayMap(x -> length(x), hits) AS hitCount

┌─queries─────────────────┬─hits───────────────────────┬─queries_flat────────┬─hits_flat──────────────┬─hitCount─┐
│ [['query1'],['query2']] │ [['hit1','hit2'],['hit1']] │ ['query1','query2'] │ ['hit1','hit2','hit1'] │ [2,1]    │
└─────────────────────────┴────────────────────────────┴─────────────────────┴────────────────────────┴──────────┘
```

arrayReduce is only mention once in passing here:
https://clickhouse.yandex/docs/en/functions/array_functions/#arrayuniqarr

the arrayReduce('groupArrayArray', x) syntax for flattening arrays is also mentioned here:
https://yandex.github.io/clickhouse-presentations/meetup11/not_in_the_docs.pdf

**Comment by salisbury-espinosa** [comment]
extra info on the subject of issue
```sql
select arrayReduce(x -> x, [1, 2, 3])
```
> DB::Exception: Function arrayReduce can't have lambda-expressions as arguments.

**Comment by viktortnk** [comment]
In case it will be useful for someone, there is `arrayFlatten` function, so for above query it would be:
```sql
SELECT
    [['query1'], ['query2']] AS queries,
    [['hit1', 'hit2'], ['hit1']] AS hits,
    arrayFlatten(queries) AS queries_flat,
    arrayFlatten(hits) AS hits_flat,
    arrayMap(x -> length(x), hits) AS hitCount;
```
