### ISSUE TITLE
date_time_input_format and date_time_output_format in users.xml don't work 

### ISSUE THREAD

**Issue by yuzhichang** [ClickHouse/ClickHouse#24164]
* clickhouse version: 21.3.8.76

Add following piece to users.xml and restart clickhouse-server:

```
            <date_time_input_format>best_effort</date_time_input_format>
            <date_time_output_format>iso</date_time_output_format>
```

```
$ clickhouse-client -m
ClickHouse client version 21.3.8.76 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 21.3.8 revision 54447.

DROP TABLE IF EXISTS test_datetime;

CREATE TABLE test_datetime(timestamp DateTime('Europe/Moscow')) ENGINE=Log;

SELECT name, value, changed FROM system.settings WHERE name LIKE 'date_time%';
┌─name────────────────────┬─value───────┬─changed─┐
│ date_time_input_format  │ best_effort │       1 │
│ date_time_output_format │ iso         │       1 │
└─────────────────────────┴─────────────┴─────────┘

INSERT INTO test_datetime VALUES ('2009-07-13T09:07:13+08:00');
Exception on client:
Code: 6. DB::Exception: Cannot parse string '2009-07-13T09:07:13+08:00' as DateTime('Europe/Moscow'): syntax error at position 19 (parsed just '2009-07-13T09:07:13'): while executing 'FUNCTION CAST(assumeNotNull(_dummy_0) :: 2, 'DateTime(\'Europe/Moscow\')' :: 1) -> CAST(assumeNotNull(_dummy_0), 'DateTime(\'Europe/Moscow\')') DateTime('Europe/Moscow') : 4': data for INSERT was parsed from query


SET date_time_input_format = 'best_effort';

INSERT INTO test_datetime VALUES ('2009-07-13T09:07:13+08:00');
1 rows in set. Elapsed: 0.023 sec. 

SELECT timestamp FROM test_datetime;
┌───────────timestamp─┐
│ 2009-07-13 05:07:13 │
└─────────────────────┘

SET date_time_output_format = 'iso';

SELECT timestamp FROM test_datetime;
┌────────────timestamp─┐
│ 2009-07-13T01:07:13Z │
└──────────────────────┘

```

**Comment by yuzhichang** [comment]
Looks like clickhouse-client doesn't use server side settings of `date_time_input_format` and `date_time_output_format`.

**Comment by den-crane** [comment]
It's incorrect query in case of curl. 
CH uses date_time_input_format setting only for inserts.

Both date_time_input_format & date_time_output_format work as expected with curl if they set using a user profile.

**Comment by charlie-wasp** [comment]
> Looks like clickhouse-client doesn't use server side settings of date_time_input_format and date_time_output_format

Is it expected behaviour? I stumble upon it just now with version 22.2.2.1. For some reason adding `SETTINGS date_time_output_format = 'iso'` to my `SELECT`-queries don't help neither

**Comment by sweihub** [comment]
What a pity that ClickHouse dose not support select with ISO time, is it really hard to implement? It's really weird of modern database. I hope to have it at next version. `set date_time_input_format = 'best_effort'`on works for insert!
```sql
select * from future where time >= '2023-11-15T23:08:00+08:00';
ERROR:  Query execution failed.
DB::Exception: Cannot convert string 2023-11-15T23:08:00+08:00 to type DateTime64(0, 'Asia/Shanghai'): while executing 'FUNCTION greaterOrEquals(time : 2, '2023-11-15T23:08:00+08:00' : 10) -> greaterOrEquals(time, '2023-11-15T23:08:00+08:00') UInt8 : 11'
```

**Comment by den-crane** [comment]
@sweihub it does support 

https://fiddle.clickhouse.com/1d6eab01-16b9-4f14-9103-334809e91240
```
select now() format Pretty;
+---------------------+
|               now() |
+---------------------+
| 2023-11-15 15:30:52 |
+---------------------+

set date_time_output_format='iso';

select now() format Pretty;
+----------------------+
|                now() |
+----------------------+
| 2023-11-15T15:30:52Z |
+----------------------+
```

`date_time_output_format` -- Method to write DateTime to text output. Possible values: 'simple', 'iso', 'unix_timestamp'.

**Comment by den-crane** [comment]
@sweihub you can use parseDateTimeBestEffort  https://fiddle.clickhouse.com/12e5157a-9aae-4043-9f9b-ab5cd3bf5ca9

**Comment by sweihub** [comment]
> @sweihub you can use parseDateTimeBestEffort https://fiddle.clickhouse.com/12e5157a-9aae-4043-9f9b-ab5cd3bf5ca9

Thanks for pointing out this, Yes, I have to use the `very-long-name-convertion-function` for the ISO datetime already. Why dosen't ClickHouse learn from PostgreSQL, the ISO input datetime should be default and convenient for users. And it dose not break any of existing conventions.

Do you accept a PR for this once `date_time_input_format = 'best_effort'` was set?

**Comment by GabrielMusatMestre** [comment]
Also struggling with this, specially because based on the [official docs](https://clickhouse.com/docs/en/operations/settings/formats#date_time_input_format)  there is no mention that the `best_effort` parser is only applied for INSERTs. Would love to see this functionality for SELECT statements also.
