### ISSUE TITLE
memory usage Increase continuously

### ISSUE THREAD

**Issue by jiakai908** [ClickHouse/ClickHouse#24174]
in version 21.3.5.42.

i have a question that ck memory usage Increase continuously in the last month. how can i to fix this problem and in the `clickhouse-server.err.log` it only occurs warn message. 
[ 15572 ] {d500d22d-bb04-4c77-96d3-cf4d56677fe4} <Warning> StorageKafka (xzzflabel_queue): [rdk:CONFWARN] [thrd:app]: Configuration property group.id is a consumer property and will be ignored by this producer instance.
the picture of memory usage like this:
![image](https://user-images.githubusercontent.com/32918492/118429210-bab2d880-b703-11eb-9d1e-31ca3b1e686e.png)

**Comment by filimonov** [comment]
> [ 15572 ] {d500d22d-bb04-4c77-96d3-cf4d56677fe4} StorageKafka (xzzflabel_queue): [rdk:CONFWARN] [thrd:app]: Configuration property group.id is a consumer property and will be ignored by this producer instance. 

doesn't look related. 

Maybe some caches just grow together with data? 
Check
https://kb.altinity.com/altinity-kb-setup-and-maintenance/altinity-kb-who-ate-my-memory

and try 
```
SYSTEM DROP MARK CACHE
SYSTEM DROP UNCOMPRESSED CACHE,
SYSTEM DROP MMAP CACHE;
```

**Comment by jiakai908** [comment]
thanks, i will try it and observe a period of time.

**Comment by jiakai908** [comment]
@filimonov `SYSTEM DROP MMAP CACHE` is not recogonized by ck. I execute other command and it's memeory usage only decrease 3% and it still using 34% when my ck in the low usage period.

**Comment by filimonov** [comment]
Does the situation normalizes after restart? How much RAM do you have at all? Also Kafka can prefetch messages - check if the detaching Kafka table(s) helps (but memory may be released with some delay).

**Comment by jiakai908** [comment]
I restart ck in the test env ,then it's memory usage decrease to 20%.
