### ISSUE TITLE
Предел памяти (общий) превышен: будет использовано 113,08 ГиБ (попытка выделить блок размером 4198368 байт), максимум: 113,08

### ISSUE THREAD

**Issue by IgorLelyakov** [ClickHouse/ClickHouse#24175]
Добрый день!

Выполняю простой запрос - соединяю (join) 2 таблицы по одному общему атрибуту
•	EAIST.LC77777 - таблица с большим кол-вом атрибутов = 365, записей = 10 000 000,
•	EAIST.P1 - таблица с большим кол-вом атрибутов = 392, записей = 13 000 000

В результате сообщение об ошибке по памяти
cc.blynk.clickhouse.except.ClickHouseException: исключение ClickHouse, код: 241, хост: null, порт: 0; Код: 241, e.displayText () = DB :: Exception: предел памяти (общий) превышен: будет использовано 113,08 ГиБ (попытка выделить блок размером 4198368 байт), максимум: 113,08 ГиБ: (при чтении столбца SPGZ_KPGZId): (в то время как чтение из part / var / lib / clickhouse / store / 28e / 28e1d1bd-6fce-4047-9ecb-7c50564693ea / 20210511_20210511_172_172_0 / с отметки 0 с max_rows_to_read = 2883): при выполнении MergeTreeThread (официальная сборка 21.4.5)

Возможно ли что-либо сделать - Есть ли какие-либо параметры, которые позволят выполнить операцию не увеличивая оперативную память или надо увеличивать оперативную память?
Файлы запроса и DDL таблиц во вложении

С уважением,
Игорь Леляков

[CREATE TABLE EAIST.P1.txt](https://github.com/ClickHouse/ClickHouse/files/6491384/CREATE.TABLE.EAIST.P1.txt)
[CREATE TABLE EAIST.LC77777.txt](https://github.com/ClickHouse/ClickHouse/files/6491385/CREATE.TABLE.EAIST.LC77777.txt)
[SELECT v2.txt](https://github.com/ClickHouse/ClickHouse/files/6491386/SELECT.v2.txt)

**Comment by vdimir** [comment]
Для выполнения JOIN правая таблица должна помещаяться в память (в случае использования hash join,  по умолчанию) https://clickhouse.tech/docs/en/sql-reference/statements/select/join/#memory-limitations 

Можно попробовать воспользоваться алгоритмом `partial_merge`:
```
SET join_algorithm = 'partial_merge';
```
(или `auto` + `max_bytes_in_join`, тогда переключение будет выполняться автоматически)

Алгоритм `partial_merge` сбрасывает промежуточные данные на диск и работает медленее, но позволяет обрабатывать большие таблицы справа.

**Comment by IgorLelyakov** [comment]
Владимир огромное спасибо! 
Установил SET join_algorithm = 'partial_merge';
Все прошло успешно!

С уважением,
Игорь
