### ISSUE TITLE
CatBoost models require numerical columns first to use in CH?

### ISSUE THREAD

**Issue by IanCal** [ClickHouse/ClickHouse#2418]
I've put a very simple training example here along with a trained model: https://github.com/IanCal/catboost_train_minimal_issue

The format is simple, there's a label then a categorical feature then a numeric one. I think the column description format is as required and the model trains just fine.

However, loading it into clickhouse and trying to use it:

```
ian-desktop :) select modelEvaluate('minimal', 'test', 0.1)

SELECT modelEvaluate('minimal', 'test', 0.1)

Received exception from server (version 1.1.54383):
Code: 36. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Column 0should be numeric to make float feature..

0 rows in set. Elapsed: 0.116 sec.
```

I think this may be related to this section of code:
https://github.com/yandex/ClickHouse/blob/adfc743e060dca26d6fa0bcb7fd93320de0655c5/dbms/src/Dictionaries/CatBoostModel.cpp#L118

It appears to be going through the columns in order and requiring that the first ones are all the numeric columns, then checks the remaining ones are categorical.

Perhaps there's something I've done wrong in the setup though. Is there a working example with numerical and categorical data mixed?

Version info:

```
ClickHouse client version 1.1.54383.
Connecting to localhost:9000.
Connected to ClickHouse server version 1.1.54383.
```
```
ian@ian-desktop:/media/storage/catboost_models/minimal$ catboost --version
git info:
    Commit: eb57c882a844d06eca4cd75aff81667725e7becc
    Author: Aleksandr Gorbunov <neksard@yandex-team.ru>
    Summary: add __divti3 implementation for the compiler_rt library

Other info:
    Build by: ian
    Top src dir: /home/ian/projects/catboost
    Top build dir: /home/ian/.ya/build/build_root/3cw4/000d72
    Hostname: ian-desktop
    Host information:
        Linux ian-desktop 4.4.0-127-generic #153-Ubuntu SMP Sat May 19 10:58:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by KochetovNicolai** [comment]
> It appears to be going through the columns in order and requiring that the first ones are all the numeric columns, then checks the remaining ones are categorical.

You're right. When you call `modelEvaluate` function for CatBoost model, you should firstly specify numeric features, than categorical (even if you used different order while training). Order between numeric and between categorical should remain the same as was in training.

I have example with mixed features in tests:
https://github.com/yandex/ClickHouse/blob/adfc743e060dca26d6fa0bcb7fd93320de0655c5/dbms/tests/external_models/catboost/test_apply_catboost_model/test.py#L80
Hope, it will help.
