### ISSUE TITLE
A Dumb Question on C++ std_move

### ISSUE THREAD

**Issue by mathfool** [ClickHouse/ClickHouse#24185]
I have a dumb question about the use of std_move. In 
BlockIO InterpreterInsertQuery::execute(): ln 312

https://github.com/ClickHouse/ClickHouse/blob/8ede5c736a6744f8daa6301d63697b8d4864725d/src/Interpreters/InterpreterInsertQuery.cpp#L310-L313

can this code block just written as 

```cpp
out_wrapper->setProcessListElement(context.getProcessListElement());
out_streams.emplace_back(std::move(out_wrapper););
```
or any specific reason?

**Comment by kitaisreal** [comment]
@mathfool thanks for question, yes it can be rewritten.

**Comment by mathfool** [comment]
Thanks!
