### ISSUE TITLE
Set encodings NLS_LANG for Oracle ODBC driver does not work

### ISSUE THREAD

**Issue by alexwang58** [ClickHouse/ClickHouse#24198]
* ClickHouse server version:  21.1.2.15 (official build)
* Linux Server: Centos7

Using Oracle as a source of ClickHouse external dictionaries via Oracle ODBC driver , and set NLS_LANG environment variable both in `/etc/default/clickhouse`  and `/etc/bashrc`, but still got encoding problem.
After environment variable had been setted,  I restarted the terminal, and then restarted both of  `clickhouse-server` and `clickhouse-odbc-bridge`.  But this does`t work for encoding problem.

Environment variable setting:
1. /etc/default/clickhouse
```
export NLS_LANG="SIMPLIFIED CHINESE_CHINA.AL32UTF8"
```

2. /etc/bashrc
```
export NLS_LANG="SIMPLIFIED CHINESE_CHINA.AL32UTF8"
```

Other software information：
oracle-instantclient-odbc-21.1.0.0.0-1.x86_64
oracle-instantclient-basic-21.1.0.0.0-1.x86_64

After NLS_LANG was setted  in /etc/bashrc , both isql and sqlplus can display the chinese character correctly.

Any type of guidance or advice will be greatly appreciated.

**Comment by filimonov** [comment]
Check the process environment:
```
sudo xargs -0 -L1 -a /proc/$(pidof clickhouse-server)/environ
sudo xargs -0 -L1 -a /proc/$(pidof clickhouse-odbc-bridge)/environ
```

**Comment by alexwang58** [comment]
> Check the process environment:
> 
> ```
> sudo xargs -0 -L1 -a /proc/$(pidof clickhouse-server)/environ
> sudo xargs -0 -L1 -a /proc/$(pidof clickhouse-odbc-bridge)/environ
> ```
> 
> If you use systems service - check https://serverfault.com/questions/413397/how-to-set-environment-variable-in-systemd-service

It works :) 
Thanks for your solution @filimonov , it`s really helpful. Actually I`m using systems service to manage clickhouse-server. Follow your suggestion to set environment variable in systemd system, the problem was fixed.

* What I did to fix it ：

1.  Add `Environment` variable into /etc/systemd/system/clickhouse-server.service
```ini
[Service]
Environment="NLS_LANG=SIMPLIFIED CHINESE_CHINA.AL32UTF8"
```

2.  reload and restart the clickhouse system service
```shell
 sudo systemctl daemon-reload && sudo systemctl start clickhouse-server
```

* Other suggestions may be helpful for someone else who was stucked in such problem
1.  `/etc/default/clickhouse`  works for SysVInit, not for SystemD. ` /etc/init.d/clickhouse-server` will call the shell script, to set your local environment variable. 
```shell
test -f /etc/default/clickhouse && . /etc/default/clickhouse
```
and you should start clickhouse-server use this command:
``` shell
service start clickhouse-server
```

2.  if use SystemD to manage your clickhouse-server. you should set environment variable in `/etc/systemd/system/clickhouse-server.service`
```ini
[Service]
Environment="NLS_LANG=YOUR_ORACLE_ENCODING"
```
if you got such error `Init script is already running`,  may be you  start clickhouse with SysVInit or others. You can try to stop than fist, such as `sudo clickhouse stop` or `service stop clickhouse-server`

3.  check your process environment:
```
sudo xargs -0 -L1 -a /proc/$(pidof clickhouse-server)/environ
sudo xargs -0 -L1 -a /proc/$(pidof clickhouse-odbc-bridge)/environ
```

4.  how to make sure the encoding of your oracle? send this query to your oracle server
```
SELECT USERENV ('language') FROM DUAL; 
```
