### ISSUE TITLE
New data type: Sign

### ISSUE THREAD

**Issue by ramazanpolat** [ClickHouse/ClickHouse#24195]
**Use case**

CollapsingMergeTree engine uses a `sign` column to delete pairs of rows if all of the fields in a sorting key (ORDER BY) are equivalent. The problem is if somehow someone accidentally inserts a value other than -1 or +1 then the merging operations stuck. 

We have faced this in one of the production systems and it is virtually impossible to get rid of those rows.

**Describe the solution you'd like**
Introducing a new data type called `Sign` which only accepts +1 or -1 will solve this problem.

**Additional context**
If it is unacceptable to insert a value different than -1 or +1 then forbidding to insert an unacceptable value would solve this problem. I know the client **must not** insert unacceptable values in the first place, but for a production system if somehow a row with Sign=2 is accidentally inserted then it is really hard to get rid of those rows unless we move the whole table to another one. Also, this problem will fill logs with the same error message that will shadow all other error messages and this is another side effect of the same problem.

To prevent this happen, we can use a table with Null engine and have a materialized view to filter unacceptable values but it is too much work to do for each CollapsingMergeTree.

**Comment by nvartolomei** [comment]
Have you tried `CONSTRAINT c_sign CHECK sign IN (-1, +1)`? https://presentations.clickhouse.tech/meetup30/new_features/#3

**Comment by ramazanpolat** [comment]
> Side note: Have you tried `CONSTRAINT c_sign CHECK sign IN (-1, +1)`? https://presentations.clickhouse.tech/meetup30/new_features/#3

That's a feature I've completely forgotten. It is a nice way to enforce it.

**Comment by tavplubix** [comment]
Also there are `optimize_on_insert` setting (enabled by default). If the setting enabled ClickHouse will merge new data before inserting and will throw exception if sign has unexpected value.
