### ISSUE TITLE
Improving sending metrics from clickhouse to graphite - set hostname

### ISSUE THREAD

**Issue by unix196** [ClickHouse/ClickHouse#2419]
Good day. We send metric from clickhouse to graphite with same config:
```
cat /etc/clickhouse-server/conf.d/graphite.xml 
<?xml version="1.0"?>
<yandex>
    <graphite>
        <host>graphite_server.local</host>
        <port>2003</port>
        <root_path>stats</root_path>
    </graphite>
</yandex>
```
All metric we ussually send with  short hostname of the server: test1, test2 =>  graphite server creates directories with short name:
```
graphite/whisper/stats/test1
graphite/whisper/stats/test2
```
But clickhouse for sending metric to graphite use fqdn of the server (through command "hostname -f"). In our case fqdn give from /etc/hosts:
```
192.168.1.100  test1.home.local test1
```
and on graphite we receive series with directory path:
```
graphite/whisper/stats/test1_home_local/Clickhouse
```
From documentation, in integration clickhouse  and graphite doesn't exist variable like "hostname" for adjusting hostname. In documentation for config.xml I find variable "<interserver_http_host>", I try set it to short hostname, but nothing changed.
Is there some way adjusting hostname for sending metrics from Clickhouse to graphite?
For example, collectd has variable in config file, which set hostname:
```
/etc/collectd/collectd.conf:
...
Hostname "test1"
...
```

**Comment by alexey-milovidov** [comment]
Replace 

```
    <graphite>
        <host>graphite_server.local</host>
        <port>2003</port>
        <root_path>stats</root_path>
    </graphite>
```

with

```
    <graphite>
        <host>graphite_server.local</host>
        <port>2003</port>
        <hostname_in_path>false</hostname_in_path>
        <root_path>your_host_name.stats</root_path>
    </graphite>
```
