### ISSUE TITLE
domain('http://abc/') = ''

### ISSUE THREAD

**Issue by mzealey** [ClickHouse/ClickHouse#24199]
Clickhouse 21.4.3.21

```
SELECT domain('http://abc/')

Query id: e9f15840-4d27-4563-b4ca-6351fd37092e

┌─domain('http://abc/')─┐
│                       │
└───────────────────────┘

```

I would have expected this to produce 'abc' as the result. `abc.com` etc work correctly.

**Comment by filimonov** [comment]
Related

https://github.com/ClickHouse/ClickHouse/issues/17673

See description of #11120

**Comment by fm4v** [comment]
`abc` is not valid domain name

**Comment by mzealey** [comment]
On a local network it is a valid name either because defined directly or because of DNS search options.

**Comment by fm4v** [comment]
Please use `netloc` function for this. Function `domain` is used by a certain number of users and will not be changed
```
SELECT netloc('https://abc/')

   ┌─netloc('https://abc/')─┐
1. │ abc                    │
   └────────────────────────┘
```
