### ISSUE TITLE
KafkaEngine-> MV1 & MV2 and from one of the MVs to Aggregating Merge Tree not working. 

### ISSUE THREAD

**Issue by DipalPrajapati** [ClickHouse/ClickHouse#24202]
I have one kafka Engine and 2 different MVs on it , One MV feed to one ReplicatedMergeTree table (Which is working) where as another MV to ReplicatedAggregatingMergeTree , which is not working.

**Comment by filimonov** [comment]
That should work. Probably you did something wrong. 
Try to attach same materialized view to the regular table instead of Kafka and try to insert the data into that table.

**Comment by DipalPrajapati** [comment]
Hi , I tried, that works , when I get data from regular table instead of Kafka. But MV is not working with Kafka.

**Comment by filimonov** [comment]
1) Check logs in /var/log/clickhouse-server/
2) share your schema

**Comment by DipalPrajapati** [comment]
Hi, you are right, The issue was i had 2 different database having same kafka engine reading from same kafka topic. Hence closing it, thank you.
