### ISSUE TITLE
When I set the value of max_server_memory_usage, the instance also  happened OOM

### ISSUE THREAD

**Issue by Sallery-X** [ClickHouse/ClickHouse#24216]

**Comment by abyss7** [comment]
Please, provide more information.

Which version are you using?
What was the limit set?
How much physical memory available?
What was a size of free memory at the moment of OOM?

**Comment by Sallery-X** [comment]
> Please, provide more information.
> 
> Which version are you using?
> What was the limit set?
> How much physical memory available?
> What was a size of free memory at the moment of OOM?

clickhouse version: 19.17.4.11
limit set 128G
physical memory available 128G
I dont know, like this
![image](https://user-images.githubusercontent.com/45587738/118628901-a05e2500-b7ff-11eb-852f-b228c6c94f24.png)

**Comment by abyss7** [comment]
19.17 is a very old and currently unsupported version - a lot of improvements have been made since then. If you can reproduce the same behavior on the more recent version, then please try it.
