### ISSUE TITLE
ReplacingMergeTree: FINAL + PREWHERE behaves differently than FINAL + WHERE

### ISSUE THREAD

**Issue by Sallery-X** [ClickHouse/ClickHouse#24217]
create table test (id int, version int) engine = ReplacingMergeTree order by id;

insert into test values (1, 1);
insert into test values (1, 2);

select * from test final where id = 1 and version = 1;  -- empty result
select * from test final prewhere id = 1 and version = 1;  -- returns (1, 1)

**Comment by Sallery-X** [comment]
version:20.8.11.17

**Comment by den-crane** [comment]
PREWHERE runs before FINAL

**Comment by den-crane** [comment]
I added to the documentation:

!!! note "Attention"
     The `PREWHERE` section is executed before` FINAL`, so the results of `FROM FINAL` queries may be skewed when using` PREWHERE` with fields not in the `ORDER BY` section of a table.
