### ISSUE TITLE
Code: 491, e.displayText() = DB::Exception: URL "IP:9000" is not allowed in config.xml (version 21.5.1.6601 (official build))

### ISSUE THREAD

**Issue by zhbdesign** [ClickHouse/ClickHouse#24218]
2021.05.18 10:21:02.848829 [ 11049 ] {a86df5fe-abba-4619-90c9-8e6c9e3b0e9e} <Debug> executeQuery: (from [::ffff:192.168.31.181]:43904, user: zhb, using production parser) SELECT DISTINCT database AS name, concat('CREATE DATABASE IF NOT EXISTS "', name, '"') AS create_db_query FROM remote('IP', system, tables) WHERE database != 'system' SETTINGS skip_unavailable_shards = 1
2021.05.18 10:21:02.850963 [ 11049 ] {a86df5fe-abba-4619-90c9-8e6c9e3b0e9e} <Error> executeQuery: Code: 491, e.displayText() = DB::Exception: URL "IP:9000" is not allowed in config.xml (version 21.5.1.6601 (official build)) (from [::ffff:192.168.31.181]:43904) (in query: SELECT DISTINCT database AS name, concat('CREATE DATABASE IF NOT EXISTS "', name, '"') AS create_db_query FROM remote('192.168.31.181', system, tables) WHERE database != 'system' SETTINGS skip_unavailable_shards = 1), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x88b553a in /usr/bin/clickhouse
1. DB::RemoteHostFilter::checkHostAndPort(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const @ 0xd822e89 in /usr/bin/clickhouse
2. DB::TableFunctionRemote::parseArguments(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>) @ 0xea84273 in /usr/bin/clickhouse
3. DB::TableFunctionFactory::get(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>) const @ 0xec3908a in /usr/bin/clickhouse
4. DB::Context::executeTableFunction(std::__1::shared_ptr<DB::IAST> const&) @ 0xf13be73 in /usr/bin/clickhouse
5. DB::JoinedTables::getLeftTableStorage() @ 0xf68b2d7 in /usr/bin/clickhouse
6. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>, std::__1::shared_ptr<DB::IBlockInputStream> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&) @ 0xf329efa in /usr/bin/clickhouse
7. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0xf32951e in /usr/bin/clickhouse
8. DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0xf6502a7 in /usr/bin/clickhouse
9. ? @ 0xf2e45f1 in /usr/bin/clickhouse
10. DB::InterpreterFactory::get(std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&) @ 0xf2e3c62 in /usr/bin/clickhouse
11. ? @ 0xf80ff87 in /usr/bin/clickhouse
12. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, bool) @ 0xf80e8a3 in /usr/bin/clickhouse
13. DB::TCPHandler::runImpl() @ 0xfff75cb in /usr/bin/clickhouse
14. DB::TCPHandler::run() @ 0x1000a299 in /usr/bin/clickhouse
15. Poco::Net::TCPServerConnection::start() @ 0x1268798f in /usr/bin/clickhouse
16. Poco::Net::TCPServerDispatcher::run() @ 0x12689401 in /usr/bin/clickhouse
17. Poco::PooledThread::run() @ 0x127c31d9 in /usr/bin/clickhouse
18. Poco::ThreadImpl::runnableEntry(void*) @ 0x127bf1ca in /usr/bin/clickhouse
19. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
20. __clone @ 0xfe96d in /usr/lib64/libc-2.17.so

**Comment by abyss7** [comment]
Please, show the exact entry in your config.xml file.

**Comment by zhbdesign** [comment]
> Please, show the exact entry in your config.xml file.

![image](https://user-images.githubusercontent.com/50901800/118746161-45254480-b88a-11eb-90fe-c03145325b82.png)

**Comment by zhbdesign** [comment]
> Please, show the exact entry in your config.xml file.

Is the change made in 21.4.1? Is the previous version the default < remote_ url_ allow_ hosts></remote_ url_ allow_ Hosts > means all allowed

**Comment by alexey-milovidov** [comment]
Yes, it was changed in 21.4, see https://github.com/ClickHouse/ClickHouse/pull/20058
