### ISSUE TITLE
Security vulnerability notifications

### ISSUE THREAD

**Issue by lubo** [ClickHouse/ClickHouse#24257]
**Use case**

Users should be able to subscribe to a feed, which will notify them whenever a new security vulnerability is published.

**Describe the solution you'd like**

Atom/RSS feed equivalent to https://clickhouse.tech/docs/en/whats-new/security-changelog/.

**Describe alternatives you've considered**

A mailing list, perhaps hosted on Google Groups, where security announcements would be posted.

**Additional context**

Currently, if a user wants to keep up with the security with the security vulnerabilities, there seems to be no other way but to manually check https://clickhouse.tech/docs/en/whats-new/security-changelog/ whenever a new version is released. Since your release cadence is pretty high, this very impractical and perhaps even discouraging.

**Comment by alexey-milovidov** [comment]
Maybe CVE list has subscription capabilities?
https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=ClickHouse

**Comment by lubo** [comment]
Nope, the page doesn't contain any Atom/RSS link.

**Comment by nvartolomei** [comment]
https://www.cvedetails.com/product/58175/Yandex-Clickhouse.html?vendor_id=6851

from https://security.stackexchange.com/questions/25557/how-to-subscribe-to-information-about-new-vulnerabilities-in-selected-products

**Comment by lubo** [comment]
A couple of downsides to the cvedetials.com approach:

* There are some concerning [limitations](https://www.cvedetails.com/how-does-it-work.php).
* The site requires registration to create feeds.
* Is this project actually committed to obtaining a CVE number for each vulnerability? What about pre-disclosure announcements, when even the CVE numbers might not be issued yet?

**Comment by alexey-milovidov** [comment]
Yes, currently not every potential vulnerability get its CVE number. We are doing it but not systematically.
