### ISSUE TITLE
 DB::Exception: Aggregate function sum(postition) is found inside another aggregate function in query: While processing sum(postition) AS postition

### ISSUE THREAD

**Issue by cwh2008** [ClickHouse/ClickHouse#24251]
Hi，
    When I execute this query sql :
SELECT
    avg(postition) AS avg,
    sum(postition) AS postition
FROM system.columns;
and the exception happened,which was:
Received exception from server (version 21.4.4):
Code: 184. DB::Exception: Received from localhost:9000. DB::Exception: Aggregate function sum(postition) is found inside another aggregate function in query: While processing sum(postition) AS postition. 

But this sql can run correctly in MySQL. This is Clickhouse's  special syntax ? 
        Thanks.
                     Best Regards.
                             Eward

**Comment by amosbird** [comment]
You can set  `prefer_column_name_to_alias = 1`.

**Comment by cwh2008** [comment]
Hi，amosbird. Thanks a lot.
Your solution is the key to this quetion.
