### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by MrSsunlight** [ClickHouse/ClickHouse#24269]
uname -a: Linux Malluma 4.19.90-17.ky10.aarch64 #1 SMP Sun Jun 28 14:27:40 CST 2020 aarch64 aarch64 aarch64 GNU/Linux
clickhouse version:  20.3.19.4
Deploy using kubernetes；

Symptom: No data is read or written, the memory gradually grows without releasing
Detailed description：
    First write part of the data, wait for a period of automatic merging and then restart the service. After restarting, no independent data request will be made (verification from system.query_log does not show any requests). Only part of the dictionary data is manually loaded, and the initial memory is observed Occupancy.  Through continuous observation of memory reuse, it is found that the clickhouse service memory is gradually increasing and not released. This observation lasted for a day, and finally reached the memory limit.
    It is generated by source code compilation. I don't know how to locate the specific reason? I want to try to use tools such as valgrind to see if it is feasible!

**Comment by alesapin** [comment]
First of all, this version is out of support, so I recommend updating to the latest stable or LTS version. If you want to check your version for memory leaks you can build it with address sanitizer. Use CMake option `-DSANITIZE=address`.
