### ISSUE TITLE
allow for extremes to be calculated based on all data — beyond the specified LIMIT

### ISSUE THREAD

**Issue by buyology** [ClickHouse/ClickHouse#24263]
**Use case**

For some paginated data requests it is very helpful to know the `min` and `max` of *all* of the data, even outside of the current row set.

Presently

> Extreme values are calculated for rows before LIMIT

**Describe the solution you'd like**

A way for `extremes = 1` to look beyond the currently specified `LIMIT` — at all data.

**Describe alternatives you've considered**

* Issue a second query and assemble home made "global extremes". 

For example,

```sql
SELECT MIN(x) min_x, MAX(x) MAX_x, MIN(y) min_y, … FROM ( SELECT a, SUM(x), SUM(y) FROM t GROUP BY a )
```

The con is that a second query has to be issued (performance) and a second query has to be constructed — whereas the `extremes` are very developer friendly.

* Fetch all data and calculate with all data at hand.

This leads to overfetching when pagination is feasible.

**Comment by alexey-milovidov** [comment]
The implementation can be similar to #6613.

**Comment by buyology** [comment]
It was simple enough to just go with a window function as suggested by @den-crane + deprecate all our uses of the extremes-feature.

Closing.
