### ISSUE TITLE
I find the query duration is mainly consumed in the phase of "_<Debug> MemoryTracker: Current memory usage:_". 

### ISSUE THREAD

**Issue by wallace-clickhouse** [ClickHouse/ClickHouse#24276]
The query duration is mainly consumed in the phase of "_<Debug> MemoryTracker: Current memory usage:_". 
What is ClickHouse doing in this phase? Why is it so slow?

**Comment by alexey-milovidov** [comment]
@wallace-clickhouse The "Current memory usage" is a status message and does not indicate any particular query processing stage.

You can check where the time spent by using query metrics from query_log:
https://presentations.clickhouse.com/meetup58/building_for_fast/#12 (slide 12)
