### ISSUE TITLE
Build deb packages on Apple M1 

### ISSUE THREAD

**Issue by kolsys** [ClickHouse/ClickHouse#24277]
I'm trying to build Debian packages for aarch64 docker image with packager.

**Operating system**
OSX 10.3.1

TAG: v21.3.10.1-lts

After some fixes of packager and docker/packager/deb/Dockerfile (I was comment:
```
RUN  curl -O https://clickhouse-builds.s3.yandex.net/utils/1/dpkg-deb \
    && chmod +x dpkg-deb \
    && cp dpkg-deb /usr/bin
```
Because it's doesn't work on aarch64) try to build:

`./docker/packager/packager --output-dir=$HOME/Source/Clickhouse/output --clickhouse-repo-path=$HOME/Source/Clickhouse --package-type=deb --compiler=clang-11 --force-build-image`

But get strange errors. See build.log.
[build.log](https://github.com/ClickHouse/ClickHouse/files/6507901/build.log)

Any suggestions?

I have success with this script but its build only binaries not deb packages.

```
#!/usr/bin/env bash


cd /ClickHouse
export DEBIAN_FRONTEND=noninteractive
LLVM_VERSION=11

export LDFLAGS='-L/lib/gcc/aarch64-linux-gnu/9 -L/usr/lib/aarch64-linux-gnu -B/lib/gcc/aarch64-linux-gnu/9 -B/usr/lib/aarch64-linux-gnu'
export CFLAGS='-Wno-incomplete-setjmp-declaration -Wno-nonportable-include-path -I/usr/include/aarch64-linux-gnu -I/usr/include'
export CXXFLAGS=$CFLAGS

CMAKE_FLAGS='-D CMAKE_SYSTEM_INCLUDE_PATH=/usr/include/aarch64-linux-gnu;/usr/include ' \
  '-D ENABLE_CAPNP=0 -D ENABLE_RDKAFKA=0 -D ENABLE_POCO_MONGODB=0 -D ENABLE_POCO_REDIS=0 ' \
  '-D ENABLE_ODBC=0 -D ENABLE_SSL=0 -D ENABLE_CASSANDRA=0 -D ENABLE_LDAP=0 ' \
  '-D ARCH_ARM=1 ' \
  '-D CMAKE_JOB_POOLS:STRING=compile=2;link=1'


touch /etc/apt/apt.conf.d/99verify-peer.conf \
&& echo >>/etc/apt/apt.conf.d/99verify-peer.conf 'Acquire { https::Verify-Peer false }'

echo 'deb [trusted=yes] http://apt.llvm.org/focal/ llvm-toolchain-focal-'$LLVM_VERSION' main' | tee /etc/apt/sources.list.d/llvm.list
apt-get update && env DEBIAN_FRONTEND=noninteractive apt-get install -y cmake ninja-build wget \
  libc-dev devscripts debhelper \
  libicu-dev libreadline-dev gperf \
  mysql-client clang-$LLVM_VERSION lld-$LLVM_VERSION

ln -s /usr/bin/lld-${LLVM_VERSION} /usr/bin/ld.lld

# ./release --no-pbuilder

export CMAKE_FLAGS=$CMAKE_FLAGS

# debuild --preserve-env -e PATH \
#   -e DEB_CC=clang-$LLVM_VERSION -e DEB_CXX=clang++-$LLVM_VERSION -e CMAKE_FLAGS="$CMAKE_FLAGS" \
#   -b ${DEBUILD_NOSIGN_OPTIONS} ${DEBUILD_NODEPS_OPTIONS}
# exit

CC=clang-$LLVM_VERSION CXX=clang++-$LLVM_VERSION cmake -j 2 . -Bbuild-arm64 -DCMAKE_TOOLCHAIN_FILE=cmake/linux/toolchain-aarch64.cmake $CMAKE_FLAGS \
  && ninja -C build-arm64
```

**Comment by filimonov** [comment]
Build of packages for platforms other than amd64 is not supported.

**Comment by kolsys** [comment]
I know, but I need at least one arm64 docker image with mysql support for local development. I see that build is possible, but don't understand why deb package builds without success.

**Comment by filimonov** [comment]
You don't need debs to create docker image.

See 
https://github.com/ClickHouse/ClickHouse/blob/9982f05e4deb23d923f4f17ace5cef9d53146b67/docker/server/Dockerfile#L15-L17

You can try the image build this way here: altinity/clickhouse-server:21.6.1.6734-testing-arm 

See also https://github.com/ClickHouse/ClickHouse/issues/22152

**Comment by kolsys** [comment]
I was built LTS ARM version with MySQL dictionary support after some patches. If someone needed: 
https://hub.docker.com/r/kolsys/clickhouse-server
