### ISSUE TITLE
failed to insert data with warning “Block with ID  already exists as part  ignoring it. ”

### ISSUE THREAD

**Issue by rogerlzp** [ClickHouse/ClickHouse#24272]
You have to provide the following information whenever possible.

**Describe the bug**
failed to insert data with warning “Block with ID  already exists as part  ignoring it. ”

**Does it reproduce on recent release?**
v21.3.3.14-stable

**How to reproduce**
create table script:
CREATE TABLE dm.fact_tx_conf_sum_local
(
    `fund_hcode` Nullable(String) COMMENT '产品全局编码',
    `fund_code` Nullable(String) COMMENT '产品代码',
    `prod_type` Nullable(String) COMMENT '产品类型',
    `conf_name` Nullable(String) COMMENT '确认名称',
    `agent_code` Nullable(String) COMMENT '销售商代码',
    `conf_date` String COMMENT '确认日期',
    `cust_type` Nullable(String) COMMENT '客户类型',
    `org_wtype` Nullable(String) COMMENT '机构类型1',
    `org_mtype` Nullable(String) COMMENT '机构类型2',
    `cisp_type` Nullable(String) COMMENT '证监会分类',
    `pbc_type` Nullable(String) COMMENT '人行分类',
    `identi_type` Nullable(String) COMMENT '证件类型',
    `ta_insidehcode` Nullable(String) COMMENT 'TA业务代码',
    `conf_code` Nullable(String) COMMENT '确认业务代码',
    `exchange_flag` Nullable(String) COMMENT '交易所标识',
    `apply_amt` Nullable(Decimal(38, 2)) COMMENT '申请金额',
    `apply_share` Nullable(Decimal(38, 2)) COMMENT '申请份额',
    `conf_amt` Nullable(Decimal(38, 2)) COMMENT '确认金额',
    `conf_share` Nullable(Decimal(38, 2)) COMMENT '确认份额',
    `bonus_type` Nullable(String) COMMENT '分红方式',
    `ttl_fee` Nullable(Decimal(38, 2)) COMMENT '总费用',
    `comm_fee` Nullable(Decimal(38, 2)) COMMENT '手续费',
    `transfee` Nullable(Decimal(38, 2)) COMMENT '过户费',
    `consign_fee` Nullable(Decimal(38, 2)) COMMENT '代销费',
    `register_fee` Nullable(Decimal(38, 2)) COMMENT '注册登记人费',
    `fund_asset_fee` Nullable(Decimal(38, 2)) COMMENT '归基金资产费',
    `finalsettle_comss` Nullable(Decimal(38, 2)) COMMENT '后收费用',
    `finalsettle_sale_orgfee` Nullable(Decimal(38, 2)) COMMENT '后收费归销售机构',
    `finalsettle_fund_assetfee` Nullable(Decimal(38, 2)) COMMENT '后收费归基金资产',
    `oth_fee1` Nullable(Decimal(38, 2)) COMMENT '其他费用1',
    `interest` Nullable(Decimal(38, 2)) COMMENT '利息',
    `int_amt_share` Nullable(Decimal(38, 2)) COMMENT '认购期利息转份额',
    `perfpay` Nullable(Decimal(38, 4)) COMMENT '业绩报酬',
    `breach_amt` Nullable(Decimal(38, 2)) COMMENT '违约金',
    `conf_ttnop` Nullable(Decimal(38, 0)) COMMENT '确认成功总笔数',
    `hdatasign` Nullable(String) COMMENT '数据标识',
    `hloadtime` Nullable(String) COMMENT '数据时间',
    `hbatchdate` Nullable(String) COMMENT '批次日期',
    `hdatasrc` Nullable(String) COMMENT '数据源',
    `par_month` String COMMENT '确认日期'
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/fact_tx_conf_sum_local_20210301084834', '{replica}')
PARTITION BY par_month
ORDER BY conf_date
SETTINGS index_granularity = 8192

we have fix nodes, 3 shard and 2 backup.

The error happened in the incremental insert.
First delete two partition, and then upload data.
The delete sql： 
ALTER TABLE  dm.fact_tx_conf_sum_local delete where par_month >= toString(toYYYYMM(today()-30)) ,
which is executed on each node.
And then insert data to local table on each node.
batch insert data to each node, the batch size is 1000.

**Expected behavior**
It is about 100000 records.
if ALTER TABLE  dm.fact_tx_conf_sum_local delete where par_month >= toString(toYYYYMM(today()-30)) , then some node will have the warning "Block with ID  already exists as part  ignoring it.", and the data is not inserted.
if ALTER TABLE  dm.fact_tx_conf_sum_local delete drop partition ('202104'), then insert data will GOOD, without any error.

 
**Error message and/or stacktrace**
2021.05.19 10:54:51.055770 [ 38083 ] {fb62ecde-4f6d-4139-b085-550b678c60e8} <Information> dm.fact_tx_conf_sum_local (Replicated OutputStream): Block with ID 70c9bfa6aaf65ba94db6f381c786f3bf_17452529178871705725_4169674670341443998 already exists locally as part 70c9bfa6aaf65ba94db6f381c786f3bf_124_124_0; ignoring it.

**Additional context**
Probably it is caused by " ALTER TABLE  dm.fact_tx_conf_sum_local delete where par_month " doesn't remove all the data that should be removed. and then failed  when insert again.

**Comment by rogerlzp** [comment]
after another try, using the exact value ('202104')  instead of expression ( toString(toYYYYMM(today()-30)) ), then the data is good.

**Comment by alesapin** [comment]
Yes, it's known unexpected behavior. Delete mutations don't affect deduplication blocks. Maybe we have to implement such logic under the setting.

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/3526 


clickhouse-client --insert_deduplicate 0

https://clickhouse.yandex/docs/en/operations/table_engines/replication/

Data blocks are deduplicated. For multiple writes of the same data block (data blocks of the same size containing the same rows in the same order), the block is only written once. The reason for this is in case of network failures when the client application doesn't know if the data was written to the DB, so the INSERT query can simply be repeated. It doesn't matter which replica INSERTs were sent to with identical data. INSERTs are idempotent. Deduplication parameters are controlled by merge_tree server settings.
