### ISSUE TITLE
Support HuaweiCloud OBS as a table storage 

### ISSUE THREAD

**Issue by isae** [ClickHouse/ClickHouse#24294]
For now, only AWS S3 and Tencent Cloud Object Storage are supported, see https://github.com/ClickHouse/ClickHouse/blob/218f534a6f5a4389c8c3b47f0a3fe3acd6ac3aee/src/IO/S3Common.cpp#L605

Actually, maybe any S3-compatible storage could be supported (by just relaxing URL regex constraint).

ClickHouse version: 21.4.6.55

**Comment by isae** [comment]
I am sorry for "unfinished code" label, "feature request" is more suitable, I guess.

**Comment by filimonov** [comment]
It is used to distinguish 2 possible forms of addresses - when the bucket is a part of hostname, and when it's a part of the path. 

How URLs for HuaweiCloud OBS typically look like?

**Comment by isae** [comment]
In my case it is `https://some-bucket.obs.ru-moscow-1.hc.sbercloud.ru/some/path/file.txt` - we're using SberCloud.Advanced. It uses virtual-hosted style URLs. 

I think, it would be better to specify 4 config properties for S3 engine:
- endpoint: i.e.`obs.ru-moscow-1.hc.sbercloud.ru` or `s3.us-east-2.amazonaws.com`.
- bucket 
- path
- url_style: virtual_hosted/path, defaulting to virtual_hosted.

This approach looks more robust than regex matching in terms of supporting different S3-like services.

**Comment by filimonov** [comment]
@excitoon what do you think about it?
