### ISSUE TITLE
If using Array of Tuple column in MergeTree table, the data cannot be read after restart

### ISSUE THREAD

**Issue by alexwl** [ClickHouse/ClickHouse#24293]
**Describe the bug**

I have a table created from `SELECT` query. The table has two columns: `UInt64` primary key and an array of tuples `Array(Tuple(String, UInt64))`. After restart of the ClickHouse server the data in the second column is lost (`SELECT` query returns only empty strings and zeros).

**Does it reproduce on recent release?**

Yes

**How to reproduce**

1. Create a table
```
CREATE TABLE Test ENGINE = MergeTree()
ORDER BY number AS
SELECT number,[('string',number)] as array from numbers(1,1000000)
```
2. Select the data
```
SELECT * FROM Test LIMIT 5
```

```
┌─number─┬─array──────────┐
│      1 │ [('string',1)] │
│      2 │ [('string',2)] │
│      3 │ [('string',3)] │
│      4 │ [('string',4)] │
│      5 │ [('string',5)] │
└────────┴────────────────┘
```
(everything is fine)

3. Restart ClickHouse server (`sudo systemctl restart clickhouse-server`)

4. Select the data again
```
SELECT * FROM Test LIMIT 5
```

```
┌─number─┬─array────┐
│      1 │ [('',0)] │
│      2 │ [('',0)] │
│      3 │ [('',0)] │
│      4 │ [('',0)] │
│      5 │ [('',0)] │
└────────┴──────────┘
```
The data in the `array` column is lost.

**Additional context**

In order to reproduce this behavior, the number of rows in the `Test` table should be sufficiently large (> 300000 rows on my machine).

**Comment by filimonov** [comment]
20.10 - last good version.

**Comment by mathfool** [comment]
data written by new version:
`-rw-r-----  1 lqin  staff    30008 May 22 00:07 array%2E%27string%27.bin
-rw-r-----  1 lqin  staff     2976 May 22 00:07 array%2E%27string%27.mrk2
-rw-r-----  1 lqin  staff  4005014 May 22 00:07 array%2Enumber.bin
-rw-r-----  1 lqin  staff     2976 May 22 00:07 array%2Enumber.mrk2
-rw-r-----  1 lqin  staff    36169 May 22 00:07 array.size0.bin
-rw-r-----  1 lqin  staff     2976 May 22 00:07 array.size0.mrk2`

data written by correct version
`
-rw-r-----  1 lqin  staff    30008 May 21 23:09 array%2E1.bin
-rw-r-----  1 lqin  staff     2976 May 21 23:09 array%2E1.mrk2
-rw-r-----  1 lqin  staff  4005014 May 21 23:09 array%2E2.bin
-rw-r-----  1 lqin  staff     2976 May 21 23:09 array%2E2.mrk2
-rw-r-----  1 lqin  staff    36169 May 21 23:09 array.size0.bin
-rw-r-----  1 lqin  staff     2976 May 21 23:09 array.size0.mrk2
`
