### ISSUE TITLE
Parameters do not work on DESCRIBE

### ISSUE THREAD

**Issue by grundrauschen** [ClickHouse/ClickHouse#24301]
**Describe the bug**
I am working with parameterized queries and they work fine for me so far for updates and selects.
The behaviour does though seem to break, when `DESCRIBE` is involved.

**Does it reproduce on recent release?**
Version used: 21.4.6.55 (server) -- yes

 
**How to reproduce**
* Which ClickHouse server version to use
  * Version used: 21.4.6.55 (server)
* Which interface to use, if matters
  * CLI and HTTP
* Non-default settings, if any
  * no

When using the CLI on a simple `SELECT` example, the parameter work fine:

```sh
$ clickhouse client --param_p0="2" -q "SELECT {p0:String}"
2
```

When using it in a `DESCRIBE` part it does break though:

```sh
$ clickhouse client --param_p0="2" -q "DESCRIBE TABLE (SELECT {p0:String})"
Received exception from server (version 21.4.6):
Code: 456. DB::Exception: Received from localhost:9000. DB::Exception: Query parameter `p0` was not set.
```

**Expected behavior**
It would be expected to return to correct types like:

```sh
$ clickhouse client -q "DESCRIBE TABLE (SELECT '2')"
\'2\'   String
```

**Error message and/or stacktrace**

As written above the following message appears:

```
Received exception from server (version 21.4.6):
Code: 456. DB::Exception: Received from localhost:9000. DB::Exception: Query parameter `p0` was not set.
```

**Additional context**
Possibly related to #10976

**Comment by grundrauschen** [comment]
Hello @den-crane,
I have a question concerning the change or `bug` to `feature`.
Is it not expected, that parameters work in every kind of queries or did I get the wrong impression from the docs?

The software I use Clickhouse with, creates queries dynamically but with certain values from the users.
To mitigate possible SQL injection attacks, we would like to use parameters for all user input, for example in `WHERE` clauses.
To check the datatypes, we run `DESCRIBE` on certain queries.
The current behaviour prevents though to move completely to parameterized queries and would have us to change some query generation.

**Comment by den-crane** [comment]
>Is it not expected, that parameters work in every kind of queries or did I get the wrong impression from the docs?

It's expected, initially parameters were implemented for SELECTs only. 
Not a bug , because it never worked before.

**Comment by grundrauschen** [comment]
Thank you for that clarification.
