### ISSUE TITLE
Predict size of hash table for GROUP BY

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#24317]
**Describe the situation**

For simple queries sometimes around 10% of query execution time can be spent in hash table resizes. We have already optimized resizes but we can do better avoiding resizes whenever possible.

**Proposed solution**

Add a statistics (cache) for observed hash table sizes during GROUP BY. It can be keyed by hash of database and table names, GROUP BY and WHERE expressions.

When aggregation is finished, observed size is collected. If observed size is bigger than some threshold (e.g. 10 million items, controlled by query setting), it will not be used in statistics - it is needed to avoid memory overallocation. If observed size is greater than previously collected value, the previously collected value is replaced by the observed value (statistics is collecting the maximum observed size unless it is too large). If observed size is more than two times less than predicted value, the previously collected value is replaced by the observed value (the statistics is dropped on misprediction).

Two-level aggregation method can be selected from the start if predicted size is large enough.

The size of the cache should be controlled by server setting. Proposed size is 10 000 items. The cache can use LRU strategy. The usage of the cache (update of statistics and the usage of collected data) should be controlled by dedicated query-level setting (on/off).

**Comment by alexey-milovidov** [comment]
Yes, but we want to avoid some heavyweight statistics that will require storage and bookkeeping.
Let's start with something lightweight as in this PR.

**Comment by nickitat** [comment]
may I take this task?

**Comment by alexey-milovidov** [comment]
@nickitat Sure, let's try!

**Comment by nickitat** [comment]
@alexey-milovidov I get to the point where there is something concrete to discuss. Please take a look at the pr.
