### ISSUE TITLE
For production environment，should I use LTS or stable?

### ISSUE THREAD

**Issue by Sallery-X** [ClickHouse/ClickHouse#24315]
Make sure to check documentation https://clickhouse.yandex/docs/en/ first. If the question is concise and probably has a short answer, asking it in Telegram chat https://telegram.me/clickhouse_en is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

If you still prefer GitHub issues, remove all this text and ask your question here.

**Comment by alexey-milovidov** [comment]
The latest *stable* version (e.g. 21.4) is recommended to use in production. In our experience the most recent stable version contains less amount of issues.

You can prefer *LTS* version (e.g. 21.3) in rare cases when you cannot install newer versions while still being able to install patches. We release patches for LTS versions in six months after release and for stable versions in two months after release. Installing patches is always required, both for stable and for LTS.
