### ISSUE TITLE
What is moving path?

### ISSUE THREAD

**Issue by onine007** [ClickHouse/ClickHouse#24314]
version: 21.3.10

![image](https://user-images.githubusercontent.com/24770345/118905829-191fc700-b94f-11eb-9929-c4b9b381effb.png)

What is moving path ?
Can i remove it ?

**Comment by mathfool** [comment]
Maybe you can wait and see if it will disappear later. It looks like a temp state when data is moving between volumn/disks(you configured multiple disk/volumn?).

**Comment by onine007** [comment]
> Maybe you can wait and see if it will disappear later. It looks like a temp state when data is moving between volumn/disks(you configured multiple disk/volumn?).

yes i configured multiple disk , and it  disappeared .
