### ISSUE TITLE
Configuration for secured/TLS zookeeper connection is not included in current documentation

### ISSUE THREAD

**Issue by genzgd** [ClickHouse/ClickHouse#24312]
The content from the PR https://github.com/ClickHouse/ClickHouse/pull/10184, including the <secure> option for the zookeeper configuration, and the explanation of the <client> option for mutual TLS, does not seem to be any place in the official ClickHouse documentation.

**Comment by genzgd** [comment]
We only got this working using TLS 1.3 on both zookeeper and ClickHouse, and the TLS_AES_128_GCM_SHA256 cipher suite explicitly configured in zookeeper

**Comment by alexey-milovidov** [comment]
As long as ClickHouse Keeper usage is preferred, we don't have to document the details of ZooKeeper anymore.
