### ISSUE TITLE
maintained. A configuration list

### ISSUE THREAD

**Issue by zhbdesign** [ClickHouse/ClickHouse#24322]
Now, Clickhouse has many configuration parameters that can be maintained. A configuration list can be maintained on the official website, because many configurations are not placed in the configuration file by default, and many configurations do not understand the specific meaning. I hope this suggestion can be adopted

**Comment by alexey-milovidov** [comment]
If the default configuration file does not have description and example for some configuration parameter,
it means that parameter is being "expert level" - not recommended to be changed in normal scenarios.

**Comment by zhbdesign** [comment]
> If the default configuration file does not have description and example for some configuration parameter,
> it means that parameter is being "expert level" - not recommended to be changed in normal scenarios.

In case of problems in the production environment, it may be necessary to modify these configurations. I think such a list is needed, because it takes time for us to find configurations in use. Expert level configurations can be specially explained. In special cases, expert level configurations need to be modified. For automatic operation and maintenance, these configurations are also needed to develop more convenient operation and maintenance tools
