### ISSUE TITLE
Parts that reached the max part size: will they still be merged?

### ISSUE THREAD

**Issue by heyciao** [ClickHouse/ClickHouse#24360]
Hi
I read [here](https://clickhouse.tech/docs/en/operations/settings/merge-tree-settings/#max-bytes-to-merge-at-max-space-in-pool) this about the parameter "max_bytes_to_merge_at_max_space_in_pool":

> The maximum total parts size (in bytes) to be merged into one part, if there are enough resources available.
max_bytes_to_merge_at_max_space_in_pool -- roughly corresponds to the maximum possible part size created by an automatic background merge.

From that I primarily understand that no single "part" will ever become bigger than that limit (current default 150GB), which is ok for me.

**Question:**
If that's correct, what will happen later to those big parts when more and more data is added to the table?
Will they...
1) be left untouched forever on their respective (low) levels
...or...
2) will they still be split&merged into higher levels (therefore still creating parts which are still limited to that max size, but with their values merged&sorted&split between the higher-level parts)?

Example:
A: table definition:
`create table test_tbl (col1 string codec(ZSTD(1)) engine=MergeTree() order by (col1)`
B1: a specific part of 150GBs on level e.g. 3 contains the following rows:
`...`
`hello`
`there`
`user`
`xenon`
`...`
B2: another specific part of 150GBs on level e.g. 5 contains as well the following rows:
`...`
`hello`
`there`
`user`
`xenon`
`...`

After adding more and more data to the table, can I expect that those parts will get merged, creating on a higher level at least 2 parts of ~150GB each, but this time with the merged rows sorted that will contain the following:
C1: (of less than 150GB as e.g. compression will become more effective) containing following rows:
`...`
`hello`
`hello`
`there`
`there`
`...`
C2: (of less than 150GB as e.g. compression will become more effective) containing following rows:
`...`
`user`
`user`
`xenon`
`xenon`
`...`

My understanding of this sentence of the documentation...

> Merges occur until the total size of the source parts is less than max_bytes_to_merge_at_max_space_in_pool.

...is that those source parts (sized each 150GB) will be left untouched forever :(

**Main reasons why I'm asking this:**

- I'm using (as well) the engine "ReplacingMergeTree", and I'm hoping that duplicate records/rows get deduplicated as well when those duplicate records are present in 2 or more parts which have already reached the limit of "max_bytes_to_merge_at_max_space_in_pool".
- in general, I'm relying a lot on the the merge operation to sort all rows to then get a better compression ratio (and less CPU consumption) as more and more similar rows would become physically sequential.

**I guess that the super-summarized question would be:**
does "max_bytes_to_merge_at_max_space_in_pool" limit only the final size of the generated parts by the merge-operations (therefore all parts will still be merged to higher levels independently from the size of the source parts or of the final result), or does it really exclude beforehand from all merge-operations all parts that, when merged, would exceed the target of "max_bytes_to_merge_at_max_space_in_pool"?

Thanks a lot!

**Comment by den-crane** [comment]
>be left untouched forever on their respective (low) levels

Yes. No splits.
BTW, forced merge `optimize table ... final` can merge parts to any size (it does not limited by max_bytes_to_merge_at_max_space_in_pool).

* You can increase max_bytes_to_merge_at_max_space_in_pool to 1TB.

* You  partition by hash ( from ReplacingMergeTree key ) 
   Partition by (key%10, toYYYYMM(time)) 
   In this case you will have 10 buckets (sub-partition).

**Comment by heyciao** [comment]
Thank you
