### ISSUE TITLE
[QUESTION] About supported ClickHouse SQL commands

### ISSUE THREAD

**Issue by jonatasfreitasv** [ClickHouse/ClickHouse#2437]
Hi guys,

I'm owner of this project (https://github.com/HouseOps/HouseOps).

I need to implement autocomplete querys in editor.

My question is, exist in any location a list of supported commands in ClickHouse syntax ?

All terms not supported by standard SQL.

Thx a lot.

**Comment by jonatasfreitasv** [comment]
Not have in a simple text list ? hehe

Thx a lot!

**Comment by alexey-milovidov** [comment]
You can find the grammar in ANTLR format here:
https://github.com/ClickHouse/ClickHouse/blob/abcb3bcbe2c6f4c28caf6840b7482d83477e6bf4/src/Parsers/New/ClickHouseParser.g4

It's not directly used by ClickHouse but *roughly* corresponds to its syntax.
