### ISSUE TITLE
clickhouse client command display error

### ISSUE THREAD

**Issue by trollhe** [ClickHouse/ClickHouse#24380]
hi,team:

   i install new clickhouse by rpm package,but clickhouse-client input commands,display repear command,what i do?

soft envs
```
os: centos 7.6
clickhouse: 21.5.5.12 (official build).
install type: rpm and offline
```

error detail:
![image](https://user-images.githubusercontent.com/41068725/119086992-ef42cf00-ba38-11eb-9275-b57cc93e9ac2.png)

**Comment by alexey-milovidov** [comment]
You have VT-100 incompatible terminal.
Try different terminal emulator, e.g. Konsole, Gnome-terminal, XTerm, iTerm, Kitty...

**Comment by trollhe** [comment]
> You have VT-100 incompatible terminal.
> Try different terminal emulator, e.g. Konsole, Gnome-terminal, XTerm, iTerm, Kitty...

Solved,can use xterm , thans.
