### ISSUE TITLE
MaterializeMySQLSyncThread: Code: 1002,  DB::Exception: ParseMetaData: Unhandled data type:16

### ISSUE THREAD

**Issue by BillVolz** [ClickHouse/ClickHouse#24407]
Hello,

I added a MySql(8.0.23) database using MaterializeMySQL.  The database gets created and works for a short period of time, roughly for the first 5 million rows.  Commands then start returning 1002 DB::Exception: ParseMetaData: Unhandled data type:16.  It looks like 16 is a BIT type but the database doesn’t have a BIT field.  

I tried click house version 21.3.4.25 and 21.5.5

Received exception from the server (version 21.5.5):
Code: 1002. DB::Exception: Received from localhost:9000. DB::Exception: ParseMetaData: Unhandled data type:16. 

Created the database using 
CREATE DATABASE messages ENGINE = MaterializeMySQL('sg-int:3306', 'messages', 'clickhouse', '****');

The database gets created, the table gets created, there is only 1 table in the database, it replicates several million rows where selects are working, then commands start failing.

2021.05.21 19:12:18.262645 [ 91 ] {} <Error> MaterializeMySQLSyncThread: Code: 1002, e.displayText() = DB::Exception: ParseMetaData: Unhandled data type:16, Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x879d83a in /usr/bin/clickhouse
1. DB::MySQLReplication::TableMapEvent::parseMeta(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) @ 0xef92ccb in /usr/bin/clickhouse
2. DB::MySQLReplication::TableMapEvent::parseImpl(DB::ReadBuffer&) @ 0xef92623 in /usr/bin/clickhouse
3. DB::MySQLReplication::MySQLFlavor::readPayloadImpl(DB::ReadBuffer&) @ 0xef99fb7 in /usr/bin/clickhouse
4. DB::MySQLProtocol::IMySQLReadPacket::readPayload(DB::ReadBuffer&, unsigned char&) @ 0xef7e867 in /usr/bin/clickhouse
5. DB::MySQLProtocol::PacketEndpoint::tryReceivePacket(DB::MySQLProtocol::IMySQLReadPacket&, unsigned long) @ 0xef7f393 in /usr/bin/clickhouse
6. DB::MaterializeMySQLSyncThread::synchronization() @ 0xef49f1d in /usr/bin/clickhouse
7. ? @ 0xef6ad12 in /usr/bin/clickhouse
8. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x87ddabf in /usr/bin/clickhouse
9. ? @ 0x87e16c3 in /usr/bin/clickhouse
10. start_thread @ 0x9609 in /lib/libpthread.so.0
11. clone @ 0x122293 in /lib/libc.so.6
 (version 21.5.5.12 (official build))

MySql Create.

CREATE TABLE `details` (
  `a` bigint NOT NULL,
  `b` datetime DEFAULT NULL,
  `c` datetime DEFAULT NULL,
  `d` datetime DEFAULT NULL,
  `e` int NOT NULL,
  `f` int DEFAULT NULL,
  `g` varchar(255) NOT NULL,
  `g` varchar(255) DEFAULT NULL,
  `i` varchar(255) DEFAULT NULL,
  `j` varchar(255) DEFAULT NULL,
  `k` varchar(255) DEFAULT NULL,
  `l` varchar(75) DEFAULT NULL,
  `m` varchar(75) DEFAULT NULL,
  `n` varchar(2000) DEFAULT NULL,
  `o` double DEFAULT NULL,
  `p` datetime DEFAULT NULL,
  `q` datetime DEFAULT NULL,
  `r` datetime DEFAULT NULL,
  `s` datetime DEFAULT NULL,
  `t` int DEFAULT NULL,
  `u` int DEFAULT NULL,
  `v` datetime DEFAULT NULL,
  `w` datetime DEFAULT NULL,
  `x` varchar(30) DEFAULT NULL,
  `y` varchar(30) DEFAULT NULL,
  `z` varchar(1024) DEFAULT NULL,
  `aa` varchar(1024) DEFAULT NULL,
  `bb` varchar(1024) DEFAULT NULL,
  `cc` int DEFAULT NULL,
  `dd` int DEFAULT NULL,
  `ee` int DEFAULT NULL,
  `ff` int DEFAULT NULL,
  `gg` int DEFAULT NULL,
  PRIMARY KEY (`a`,`e`,`g`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

**Comment by wen2013a** [comment]
I have the same problem

**Comment by BillVolz** [comment]
After recreating the MySQL table and starting over the error went away.  It could be that at some point the MySQL database had a field that was a bit and it was changed to an integer.  I am not sure what MySql does to the bin log when this happens. Is it possible the bin log still contained something referencing a bit even know that bit field was changed?

My problem is resolved but I wanted to add this in case it helps to debug this.
