### ISSUE TITLE
formatDateTime return empty on with fill query !

### ISSUE THREAD

**Issue by mbtolou** [ClickHouse/ClickHouse#24414]
formatDateTime return empty on with fill query !

```
select addDays(today(),`number`) profile_date,formatDateTime(profile_date,'%m-%d') profile_str
from numbers(5)
order by profile_date with fill from addDays(today(),-7) to addDays(today(),1)
```

result :

![image](https://user-images.githubusercontent.com/6413705/119221737-ed930d00-bb05-11eb-81d7-f24c47716e46.png)

**Comment by alexey-milovidov** [comment]
This is expected behaviour.
When filling string value, it is filled with empty strings.
Filling is performed after order by and after functions are calculated.

What you need is:
```
SELECT
    profile_date,
    formatDateTime(profile_date, '%m-%d') AS profile_str
FROM
(
    SELECT addDays(today(), number) AS profile_date
    FROM numbers(5)
    ORDER BY profile_date ASC WITH FILL FROM addDays(today(), -7) TO addDays(today(), 1)
)
```

**Comment by alexey-milovidov** [comment]
@olgarev Please add clarification in docs about WITH FILL.

**Comment by olgarev** [comment]
Internal documentation ticket DOCSUP-9735
