### ISSUE TITLE
Bad link to external disctionary functions (russian edition)

### ISSUE THREAD

**Issue by ukolovda** [ClickHouse/ClickHouse#24418]
**Describe the issue**
On page https://clickhouse.tech/docs/ru/sql-reference/dictionaries/
link to dictionary functions ("Подключаемые (внешние) словари с **набором функций**.")
Link "набором функций" is https://clickhouse.tech/docs/ru/sql-reference/dictionaries/external-dictionaries/
But should be https://clickhouse.tech/docs/ru/sql-reference/functions/ext-dict-functions/

**Comment by alexey-milovidov** [comment]
Could you please press on :pencil2: at the top right corner in the docs and edit the link?
