### ISSUE TITLE
How can I immediately determine whether the detach statement Is successfully executed?

### ISSUE THREAD

**Issue by lingnancfy** [ClickHouse/ClickHouse#24425]
After detach part, I immediately queried the query_log table to find the “QueryFinish” record，but return nothing.

I put two sqls in a shell script：
$CLICKHOUSE_HOME/clickhouse client --host **** --port 9000 -q "alter table DTDB.lineorder_1 detach part '1996_0_0_0'"

$CLICKHOUSE_HOME/clickhouse client --host **** --port 9000 -q "select * from system.query_log where query like 'alter table DTDB.lineorder_1 detach part \'1996_0_0_0\'%'"

But I'll find it later.

**Comment by alexey-milovidov** [comment]
Query log is flushed every 7.5 seconds by default, see `config.xml`.
