### ISSUE TITLE
EXCHANGE TABLES not working on latest docker image

### ISSUE THREAD

**Issue by amirvaza** [ClickHouse/ClickHouse#24439]
Using latest image in docker `yandex/clickhouse-server:latest`

Creating 2 identical tables Atomic db is default but also tried recreating but it isn't related because its an OS issue

```
CREATE TABLE IF NOT EXISTS t1
(
    a DateTime64(3),
    b UInt8
) ENGINE = MergeTree()
ORDER BY (a)
```
```
CREATE TABLE IF NOT EXISTS t2
(
    a DateTime64(3),
    b UInt8
) ENGINE = MergeTree()
ORDER BY (a)
```

Command `EXCHANGE TABLES t1 AND t2` returns:
```
Code: 1. DB::Exception: Received from localhost:9000. DB::Exception: System call renameat2() is not supported.
```

Suggestions?

**Comment by vdimir** [comment]
Couldn't reproduce.

@amirvaza Is it solved? What was the problem?

**Comment by amirvaza** [comment]
If anyone experience the same, it was due to using mapped volume to `/var/lib/clickhouse/` and a mac host

**Comment by Slach** [comment]
@vdimir when we use non-Linux host OS for docker, volumes have different implementation and could not support renameat2 syscall

**Comment by myLouisJava** [comment]
> @myLouisJava according to source code
> 
> https://github.com/ClickHouse/ClickHouse/blob/7383bdd5fa6bbab3a3f7b7cec64c4592f7463834/src/Databases/DatabaseAtomic.cpp#L163-L164
> 
> your kernel should support `renameat2` which file system do you use in `/var/lib/clickhouse`?
> 
> could run `uname -a` on Host OS?

Linux 3.10.0-1160.31.1.el7.x86_64
the kernel does not support `renameat2`
ok, thanks
