### ISSUE TITLE
IBackgroundJobExecutor::jobExecutingTask error occurs repeatly when I upgraded to version 21.4.5.46 (official build)

### ISSUE THREAD

**Issue by dengc367** [ClickHouse/ClickHouse#24438]
You have to provide the following information whenever possible.

**Describe the bug**
In the clickhouse-server.log, I found one error repeatly reported:

IBackgroundJobExecutor::jobExecutingTask error occurs repeatly when I upgraded to version 21.4.5.46 (official build)

**Does it reproduce on recent release?**
version 21.5.5.12 (official build)
version 21.4.5.46 (official build)

**How to reproduce**
*  version 21.4.5.46 (official build)
* all is default clickhouse settings

**Expected behavior**
The error cannot happened.

**Error message and/or stacktrace**
{} <Error> auto DB::IBackgroundJobExecutor::jobExecutingTask()::(anonymous class)::operator()() const: Code: 53, e.displayText() = DB::Exception: Types of column 1 in section IN don't match: Int32 on the left, UInt8 on the right, Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x87f4c4a in /usr/bin/clickhouse
1. DB::Set::checkTypesEqual(unsigned long, std::__1::shared_ptr<DB::IDataType const> const&) const @ 0xf62388c in /usr/bin/clickhouse
2. DB::KeyCondition::tryPrepareSetIndex(std::__1::vector<std::__1::shared_ptr<DB::IAST>, std::__1::allocator<std::__1::shared_ptr<DB::IAST> > > const&, DB::Context const&, DB::KeyCondition::RPNElement&, unsigned long&) @ 0xfbcf375 in /usr/bin/clickhouse
3. DB::KeyCondition::tryParseAtomFromAST(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, DB::Block&, DB::KeyCondition::RPNElement&) @ 0xfbcb154 in /usr/bin/clickhouse
4. DB::KeyCondition::traverseAST(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, DB::Block&) @ 0xfbca65e in /usr/bin/clickhouse
5. DB::KeyCondition::traverseAST(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, DB::Block&) @ 0xfbca5e3 in /usr/bin/clickhouse
6. DB::KeyCondition::KeyCondition(DB::SelectQueryInfo const&, DB::Context const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::ExpressionActions> const&, bool, bool) @ 0xfbc9acd in /usr/bin/clickhouse
7. DB::MergeTreeDataSelectExecutor::readFromParts(std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeDataPart const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeDataPart const> > >, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryInfo const&, DB::Context const&, unsigned long, unsigned int, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, long, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, long> > > const*) const @ 0xfca565e in /usr/bin/clickhouse
8. DB::StorageFromMergeTreeDataPart::read(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryInfo&, DB::Context const&, DB::QueryProcessingStage::Enum, unsigned long, unsigned int) @ 0xfc6656b in /usr/bin/clickhouse
9. DB::IStorage::read(DB::QueryPlan&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryInfo&, DB::Context const&, DB::QueryProcessingStage::Enum, unsigned long, unsigned int) @ 0xf8dd89f in /usr/bin/clickhouse
10. DB::InterpreterSelectQuery::executeFetchColumns(DB::QueryProcessingStage::Enum, DB::QueryPlan&) @ 0xf27503e in /usr/bin/clickhouse
11. DB::InterpreterSelectQuery::executeImpl(DB::QueryPlan&, std::__1::shared_ptr<DB::IBlockInputStream> const&, std::__1::optional<DB::Pipe>) @ 0xf26a791 in /usr/bin/clickhouse
12. DB::InterpreterSelectQuery::buildQueryPlan(DB::QueryPlan&) @ 0xf2695ab in /usr/bin/clickhouse
13. DB::InterpreterSelectQuery::execute() @ 0xf26d2d7 in /usr/bin/clickhouse
14. DB::isStorageTouchedByMutations(std::__1::shared_ptr<DB::IStorage> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::vector<DB::MutationCommand, std::__1::allocator<DB::MutationCommand> > const&, DB::Context) @ 0xf5df3d6 in /usr/bin/clickhouse
15. DB::MergeTreeDataMergerMutator::mutatePartToTemporaryPart(DB::FutureMergedMutatedPart const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::MutationCommands const&, DB::BackgroundProcessListEntry<DB::MergeListElement, DB::MergeInfo>&, long, DB::Context const&, std::__1::unique_ptr<DB::IReservation, std::__1::default_delete<DB::IReservation> > const&, std::__1::shared_ptr<DB::RWLockImpl::LockHolderImpl>&) @ 0xfc539c7 in /usr/bin/clickhouse
16. DB::StorageMergeTree::mutateSelectedPart(std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::StorageMergeTree::MergeMutateSelectedEntry&, std::__1::shared_ptr<DB::RWLockImpl::LockHolderImpl>&) @ 0xf9ac91e in /usr/bin/clickhouse
17. ? @ 0xf9bbca8 in /usr/bin/clickhouse
18. ? @ 0xfb8e817 in /usr/bin/clickhouse
19. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0x8837758 in /usr/bin/clickhouse
20. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()&&...)::'lambda'()::operator()() @ 0x883971f in /usr/bin/clickhouse
21. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x8834d2f in /usr/bin/clickhouse
22. ? @ 0x88387c3 in /usr/bin/clickhouse
23. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
24. __clone @ 0xfe8dd in /usr/lib64/libc-2.17.so
 (version 21.4.5.46 (official build))

**Additional context**
No another context error occurs.

**Comment by alesapin** [comment]
Hi! Seems like you are using alters or mutations. Can you provide output from `system.mutations` table?

**Comment by dengc367** [comment]
That's awesome! Thanks very much. @alesapin  The problem have been solved.
I run the [`kill mutation`](https://clickhouse.tech/docs/zh/sql-reference/statements/misc/#kill-mutation) query, and then the clickhouse log does't report the error log any more.

![image](https://user-images.githubusercontent.com/1353036/119317115-54512b80-bcaa-11eb-92ac-065e3c5a206d.png)
