### ISSUE TITLE
String with number converted to scientific notation

### ISSUE THREAD

**Issue by lroman242** [ClickHouse/ClickHouse#24440]
**ClickHouse server version 20.10.3 revision 54441**

Table:
`CREATE TABLE events (
....
custom_id String,
....
)
    engine = ReplicatedReplacingMergeTree('/clickhouse/tables/{layer}-{shard}/database.events', '{replica}',
             updated_at)
        PARTITION BY toYYYYMM(created_at)
        PRIMARY KEY id
        ORDER BY id
`

Data:
`INSERT INTO events VALUES (..., '12312312312312312312', ....)`

Result:
`SELECT * FROM events WHERE custom_id = '12312312312312312312' `  -> no results
I've found that record by another ID and custom_id = '1.2312312312312312e+19'

How to prevent such behavior (converting large number into scientific notation) ?

**Comment by vdimir** [comment]
What client do you use to connect to server, is it some driver?
Can it be reproduced with non replicated table?

I tried to reproduce it locally with `clickhouse-client` it works as expected both on 20.10 and current version.

**Comment by lroman242** [comment]
@vdimir Yea, looks like problem in client. Thank you for note
