### ISSUE TITLE
Graceful server shutdown

### ISSUE THREAD

**Issue by nvartolomei** [ClickHouse/ClickHouse#24451]
Currently, running queries are cancelled and server waits for clients to close connections for `shutdown_wait_unfinished`.

Proposal: Do not cancel running queries and let them run for some timeout before trying to shut down storages.

This should be useful for large clusters with long-running distributed queries and high release cadence.

**Comment by alexey-milovidov** [comment]
I would better not implement this feature.

It will introduce complications on server side while clients still should always support retries (with exponential backoff and limits) and be ready to return error for user. This is required for high availability.

But this feature is very easy to implement (just add a flag to disable query cancellation on shutdown).
If you want to implement it, please send a PR.
