### ISSUE TITLE
Does ReplicatedMergeTree has data copy  limit in service recovery

### ISSUE THREAD

**Issue by chengbinghan** [ClickHouse/ClickHouse#24453]
hi
    in our company,we use clickhouse for a long time. (thanks clickhouse dev group!)
in our situation, we use  ReplicatedMergeTree engine。but we has some problem. for example.
 We running two clickhouse instance  on host 10.0.0.1 and 10.0.0.2 .because we use ReplicatedMergeTree。 the data in 10.0.0.1 and 10.0.0.2 is same. 
![image](https://user-images.githubusercontent.com/37525039/119366115-348a2980-bce3-11eb-871e-aa969f4b8d16.png)
  
**step1:** When something wrong on 10.0.0.1 , We can also use clickhouse on 10.0.0.2.
![image](https://user-images.githubusercontent.com/37525039/119367472-926b4100-bce4-11eb-8a0f-890d27c748a0.png)
**step2:**After some time, 10.0.0.2 data is 1000G
![image](https://user-images.githubusercontent.com/37525039/119367755-dcecbd80-bce4-11eb-9ccb-927d923a0038.png)
**step3:** After some time,We recovery clickhouse which on 10.0.0.1.   There are 500G data need send to 10.0.0.1 from 10.0.0.2。
![image](https://user-images.githubusercontent.com/37525039/119368188-4c62ad00-bce5-11eb-9268-c40fc523e127.png)

The problem is, when 500G data from 10.0.0.2 to 10.0.0.1 clickhouse. the 10.0.0.1 io utils is high,and load on the linux server is too high. so in this situation. server 10.0.0.1 will be busy, especialy io utils. so other service on 10.0.0.1 can't work.

is there some way to limit the speed of  data copy . so well can let 10.0.0.1 work well. we can use one night to copy data from 
10.0.0.2 to 10.0.0.1

**Comment by den-crane** [comment]
Check this https://github.com/ClickHouse/ClickHouse/issues/22742

**Comment by chengbinghan** [comment]
> Check this #22742

666
