### ISSUE TITLE
Support query parameters in create table/drop table/insert into

### ISSUE THREAD

**Issue by DimasKovas** [ClickHouse/ClickHouse#24456]
**Use case**
CH supports query parameters ([docs](https://clickhouse.tech/docs/en/interfaces/cli/#cli-queries-with-parameters)).
They can be used in query templates. E.g. analysts use it to run the same query over different tables. But now parameters are recognized only in **select** part of the query. In **create table**/**drop table**/**insert into** CH throw an error (DB::Exception: Syntax error: failed at position 13 ('{'): {xxx:Identifier}...)

**Describe the solution you'd like**
Tables in **create table**/**drop table**/**insert into**   queries can be parametrize

**Comment by alexey-milovidov** [comment]
Duplicate https://github.com/ClickHouse/ClickHouse/issues/27226.
