### ISSUE TITLE
Запрос Insert Select выполняется очень долго – уходит в бесконечность, не выдает сообщения об ошибке и не вставляет ни одной записи

### ISSUE THREAD

**Issue by IgorLelyakov** [ClickHouse/ClickHouse#24479]
Добрый день!
Версия 21.4.5
120ГБ ОП
настройки SET join_algorithm = 'auto', max_bytes_in_join = 64 424 509 440 (то-есть 60 ГБ)

Запрос Insert Select выполняется очень долго – уходит в бесконечность, не выдает сообщения об ошибке и не вставляет ни одной записи,
Но если выполнить этот же запрос без операции "Insert", только "Select" то запрос успешно выполняется примерно за 1 минуту.

Запрос большой, в нем последовательно соединяются много таблиц через операции JOIN, в результате получается представление с количеством атрибутов = "687" и ориентировочно более 100 000 000 записей 

Скажите есть ли какие-либо настройки для того, чтобы запрос Insert Select выполнился успешно без ошибки по оперативной памяти и в разумные сроки? 

Запрос Insert Select и DDL таблицы в которую пытаюсь вставить записи во вложении.

С уважением,
Игорь Леляков

[CREATE TABLE EAIST.KLPSPl.txt](https://github.com/ClickHouse/ClickHouse/files/6537927/CREATE.TABLE.EAIST.KLPSPl.txt)
[INSERT SELECT.txt](https://github.com/ClickHouse/ClickHouse/files/6537999/INSERT.SELECT.txt)

**Comment by den-crane** [comment]
>"Select" то запрос успешно выполняется примерно за 1 минуту.

Я подозреваю выдает первые строки. Что если добавить в конце select ... format Null , сколько тогда время выполнения?

**Comment by alexey-milovidov** [comment]
No info provided.
