### ISSUE TITLE
 Occasionally authentication failed occurs

### ISSUE THREAD

**Issue by Sallery-X** [ClickHouse/ClickHouse#24474]
You have to provide the following information whenever possible.

**Describe the bug**
A clear and concise description of what works not as it is supposed to.
same user and password， Occasionally authentication failed occurs， I am confused 

**How to reproduce**
* Which ClickHouse server version to use
  21.3.5.42

the error like this
![image](https://user-images.githubusercontent.com/45587738/119430241-01778280-bd43-11eb-92fd-c67025d61cb9.png)

![image](https://user-images.githubusercontent.com/45587738/119430301-1a803380-bd43-11eb-9b32-7bb89860488d.png)

**Comment by filimonov** [comment]
You have some domain whitelist which user allowed to connect from. And there are some issues during reverse dns lookup.

**Comment by Sallery-X** [comment]
> You have some domain whitelist which user allowed to connect from. And there are some issues during reverse dns lookup.

I cant figure out, 
How should I troubleshoot the problem

**Comment by filimonov** [comment]
Always connect from the same ip, ensure that the ip you use can always be resolved by DNS server correctly.

Or just remove host / or host_regexp from user config - i mean that 
https://clickhouse.tech/docs/en/operations/settings/settings-users/#user-namenetworks
OR
https://clickhouse.tech/docs/en/sql-reference/statements/create/user/#user-host

**Comment by alexey-milovidov** [comment]
Does it reproduce on the recent release?

I see that you are using version **21.3.5**.
Versions **21.5.5** and **21.3.11** are available. These versions may contain fixes.
I've added "obsolete-version" label.
