### ISSUE TITLE
MATERIALIZED VIEW and AggregateFunction, error results

### ISSUE THREAD

**Issue by shadowDy** [ClickHouse/ClickHouse#24482]
source table schema:
CREATE TABLE test_local
(
    `app` String,
    `count` UInt32
)
ENGINE = MergeTree()
ORDER BY app
SETTINGS index_granularity = 8192

 MV table schema：
CREATE MATERIALIZED VIEW test_view_new_local
(
    `count_80` AggregateFunction(quantileExact(0.8), UInt32),
    `app` String
)
ENGINE = AggregatingMergeTree()
ORDER BY app
SETTINGS index_granularity = 8192 AS
SELECT
    app,
    quantileExactState(0.8)(count) AS count_80
FROM test_local
GROUP BY app

then i will insert 6 rows records into source table test_local:

insert into test_local values('app',79)
insert into test_local values('app',70)
insert into test_local values('app',67)
insert into test_local values('app',86)
insert into test_local values('app',67)
insert into test_local values('app',72)

show result:
 select * from test_local;
┌─app─┬─count─┐
│ app │    72 │
└─────┴───────┘
┌─app─┬─count─┐
│ app │    79 │
│ app │    70 │
│ app │    67 │
│ app │    86 │
│ app │    67 │
└─────┴───────┘

when i execute the sql：
select app,quantileExact(0.8)(count) from test_local group by app
return:
┌─app─┬─quantileExact(0.8)(count)─┐
│ app │                        79 │
└─────┴───────────────────────────┘
result is right.

but when i use MV : 
select app,quantileExactMerge(count_80) from test_view_new_local group by app;
then return : 
┌─app─┬─quantileExactMerge(count_80)─┐
│ app │                           72 │
└─────┴──────────────────────────────┘

Obviously, materialized view result is wrong! Why is the result of materialized view inconsistent with the original table.

thanks~

**Comment by shadowDy** [comment]
When I merge six inserts into one insert query,
insert into test_local values('app3',79),('app3',70),('app3',67),('app3',86),('app3',67),('app3',72)

 the result doesn't change.

**Comment by den-crane** [comment]
quantileExactMerge also needs the same parameter (0.8). It does not stored in the value.

```
select app,quantileExactMerge(0.8)(count_80) from test_view_new_local group by app;
┌─app─┬─quantileExactMerge(0.8)(count_80)─┐
│ app │                                79 │
└─────┴───────────────────────────────────┘
```
