### ISSUE TITLE
PCG serialization is slow in 20.8-lts

### ISSUE THREAD

**Issue by johnskopis** [ClickHouse/ClickHouse#24481]
Will you please backport a06be511df8ebd0a963470026d8460257b891dc7 to 20.8-lts to fix performance issues when using ReservoirSampler?

I haven't had a chance to test but it seems the commit will fix the apparent performance issues.

Thanks

**Comment by alexey-milovidov** [comment]
We don't backport performance improvements.
To get performance improvement, upgrade to version 21.5.

**Comment by johnskopis** [comment]
good to know. thanks
