### ISSUE TITLE
Exception: There is no profile 'default' in configuration file.

### ISSUE THREAD

**Issue by hydgladiator** [ClickHouse/ClickHouse#24484]
Make sure to check documentation https://clickhouse.yandex/docs/en/ first. If the question is concise and probably has a short answer, asking it in Telegram chat https://telegram.me/clickhouse_en is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

If you still prefer GitHub issues, remove all this text and ask your question here.

Run entrypoint.sh , then Error and can not start clickhouse-server

bash-4.2# sh /entrypoint.sh
Processing configuration file '/etc/clickhouse-server/config.xml'.
Logging trace to /var/log/clickhouse-server/clickhouse-server.log
Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
Logging trace to console
2021.05.25 18:24:19.453013 [ 660 ] {} <Trace> Pipe: Pipe capacity is 1.00 MiB
2021.05.25 18:24:19.456212 [ 660 ] {} <Information> : Starting ClickHouse 20.3.10.75 with revision 54433
2021.05.25 18:24:19.456285 [ 660 ] {} <Information> Application: starting up
2021.05.25 18:24:19.631903 [ 660 ] {} <Information> Application: It looks like the process has no CAP_IPC_LOCK capability, binary mlock will be disabled. It could happen due to incorrect ClickHouse package installation. You could resolve the problem manually with 'sudo setcap cap_ipc_lock=+ep /usr/bin/clickhouse'. Note that it will not work on 'nosuid' mounted filesystems.
2021.05.25 18:24:19.632839 [ 660 ] {} <Debug> Application: rlimit on number of file descriptors is 1024000
2021.05.25 18:24:19.632865 [ 660 ] {} <Debug> Application: Initializing DateLUT.
2021.05.25 18:24:19.632877 [ 660 ] {} <Trace> Application: Initialized DateLUT with time zone 'Asia/Shanghai'.
2021.05.25 18:24:19.632915 [ 660 ] {} <Debug> Application: Setting up /var/lib/clickhouse/tmp/ to store temporary data in it
2021.05.25 18:24:19.634358 [ 660 ] {} <Debug> Application: Configuration parameter 'interserver_http_host' doesn't exist or exists and empty. Will use 'a5f851d5face' as replica host.
2021.05.25 18:24:19.634571 [ 660 ] {} <Information> SensitiveDataMaskerConfigRead: 1 query masking rules loaded.
2021.05.25 18:24:19.637688 [ 660 ] {} <Debug> ConfigReloader: Loading config '/etc/clickhouse-server/config.xml'
Processing configuration file '/etc/clickhouse-server/config.xml'.
Saved preprocessed configuration to '/var/lib/clickhouse//preprocessed_configs/config.xml'.
2021.05.25 18:24:19.640691 [ 660 ] {} <Information> Application: Uncompressed cache size was lowered to 3.82 GiB because the system has low amount of memory
2021.05.25 18:24:19.737336 [ 660 ] {} <Information> Application: Shutting down storages.
2021.05.25 18:24:19.737378 [ 660 ] {} <Debug> Application: Shut down storages.
2021.05.25 18:24:19.738611 [ 660 ] {} <Debug> Application: Destroyed global context.
2021.05.25 18:24:19.739256 [ 660 ] {} <Error> Application: DB::Exception: There is no profile 'default' in configuration file.
2021.05.25 18:24:19.739597 [ 660 ] {} <Information> Application: shutting down
2021.05.25 18:24:19.739609 [ 660 ] {} <Debug> Application: Uninitializing subsystem: Logging Subsystem
2021.05.25 18:24:19.739761 [ 699 ] {} <Information> BaseDaemon: Stop SignalListener thread

![ck-issue](https://user-images.githubusercontent.com/13326206/119483017-1e35a980-bd87-11eb-9ac2-a219628591b2.jpg)

**Comment by filimonov** [comment]
That is your error:
```
DB::Exception: There is no profile 'default' in configuration file.
```

Please fix the users.xml & return back default profile (or just use default configuration)

**Comment by hydgladiator** [comment]
Follow said that  'default' in users.xml  , is <profiles> or <users> or <quotas> sections ? 
I only modify or add username & password_sha256_hex kv into the users.xml

The configuration File equals to using at another enviroment's same file.


sudo cat /etc/clickhouse-server/users.xml


<?xml version="1.0"?>
<yandex>
    
    <profiles>
        
        <default>
            
            <max_memory_usage>10000000000</max_memory_usage>

            
            <load_balancing>random</load_balancing>
        </default>

        
        <readonly>
            <readonly>1</readonly>
        </readonly>
    </profiles>

    
    <users>
	<default>
	<password_sha256_hex>699040f6cfe3afbc4316c01950228a6980b1ae778ca7dd12a764cc03b9c9318f</password_sha256_hex>
	<networks incl="networks" replace="replace">
	<ip>::/0</ip>
	</networks>
	<profile>default</profile>
	<quota>default</quota>
	</default>

	<ck>
	<password_sha256_hex>6d48a457e035233bb0cd930ecf831dc55ae265f6c94c30127ccd92b67a10bec6</password_sha256_hex>
	<networks incl="networks" replace="replace">
	<ip>::/0</ip>
	</networks>
	<profile>readonly</profile>
	<quota>default</quota>
	</ck>

	<uniondrug>
	<password_sha256_hex>386ffd7fcaac48f20aae9dafcfcca695045742f213acfb39dedea16e74349cf1</password_sha256_hex>
	<networks incl="networks" replace="replace">
	<ip>::/0</ip>
	</networks>
	<profile>default</profile>
	<quota>default</quota>
	</uniondrug>

	<deploy>
	<password_sha256_hex>14d2f91818dd0f96a743e1f1084a4db2c7ec27b00c7022e279d0231de607e277</password_sha256_hex>
	<networks incl="networks" replace="replace">
	<ip>::/0</ip>
	</networks>
	<profile>default</profile>
	<quota>default</quota>
	</deploy>

        
        <default>
            
            <password></password>

            
            <networks>
                <ip>::/0</ip>
            </networks>

            
            <profile>default</profile>

            
            <quota>default</quota>

            
            
        </default>
    </users>

    
    <quotas>
        
        <default>
            
            <interval>
                
                <duration>3600</duration>

                
                <queries>0</queries>
                <errors>0</errors>
                <result_rows>0</result_rows>
                <read_rows>0</read_rows>
                <execution_time>0</execution_time>
            </interval>
        </default>
    </quotas>
</yandex>
