### ISSUE TITLE
Metadata storage path for Atomic database engine

### ISSUE THREAD

**Issue by Blackmorse** [ClickHouse/ClickHouse#24491]
After migrating from _Ordinary_ database engine to _Atomic_ Clickhouse no longer stores metadata at _**metadata/**_ folder. Instead of this there are symlinks from _**metadata/<database>**_ to corresponding locations at _**store/**_ folder.

Previously , our set up had separate disk (RAID) mounted at _**metadata/**_ to provide more robust metadata storage.
Are there any setting or possibility to store Clickhouse's metadata physically at specified location?

**Comment by den-crane** [comment]
I guess `<path>/var/lib/clickhouse/</path>` in config.xml

**Comment by Blackmorse** [comment]
I'm looking only for **metadata** storage, not the full clickhouse data...

**Comment by alexey-milovidov** [comment]
It's not possible to use a separate disk for metadata with the Atomic database.
I recommend setting up replication because RAID (including RAID-1) does not provide good guarantees if only a single server is used.
