### ISSUE TITLE
OPTIMIZE DEDUPLICATE not removing oldest row

### ISSUE THREAD

**Issue by jretanax** [ClickHouse/ClickHouse#24502]
**Describe the unexpected behaviour**
I have 2 rows with same id and event_date, one row was inserted 2 weeks ago and one row was inserted today.
When running 
`OPTIMIZE TABLE mytable_local ON CLUSTER '{cluster}' PARTITION 20210525 FINAL DEDUPLICATE BY event_date, id;`
the command is removing the row that was inserted today. 
That new row has other values updated and that's why I'm trying to deduplicate by removing the oldest one.

**How to reproduce**
*ClickHouse 21.5.5.12
*ReplicatedMergeTree table

**Expected behavior**
As for the ReplacingMergeTree table engine, I would expect the following for the MergeTree table when using OPTIMIZE:

When merging, ReplacingMergeTree from all the rows with the same sorting key leaves only one:
- The last in the selection, if ver not set. A selection is a set of rows in a set of parts participating in the merge. The most recently created part (the last insert) will be the last one in the selection. Thus, after deduplication, the very last row from the most recent insert will remain for each unique sorting key.
- With the maximum version, if ver specified.

As the MergeTree table has no version handling one useful addition would be:
`OPTIMIZE ... FINAL DEDUPLICATE BY xxx, yyy VERSIONED BY zzz`

**Comment by den-crane** [comment]
DEDUPLICATE BY has no relation to ReplacingMergeTree logic. Currently it leaves random row.

**Comment by jretanax** [comment]
Is there a way to not make it random? or somehow using a column having the version number?

**Comment by alexey-milovidov** [comment]
No, DEDUPLICATE BY is intended to leave any single row from the group.
