### ISSUE TITLE
[Enhancement Request] Method to restrict user access to system database information

### ISSUE THREAD

**Issue by ryn9** [ClickHouse/ClickHouse#2451]
Would it be possible for an enhancement that would restrict user access to system database information?

User restrictions appear to be limited to the 'allow_databases' heuristic and application of a profile with the 'readonly' heuristic applied. Seen here: [https://clickhouse.yandex/docs/en/operations/access_rights/](url)

With those applied, though, a user still has read access to the system database. There are tables there that contain information that contain information that would be beneficial to restrict. 

Some examples:

Allow restrictions on system.query_log. This table appears to show all the queries made to the system, and some requester information. We likely don't want one user to see what other users are querying.

Allow restrictions on system.databases, system.tables, system.columns, etc.. when the user does not have access those entries. We likely don't want one user to gain information on resources that are not supposed to have access to.

Allow restrictions on system.build_options, system.clusters, system.metrics, system.parts, system.parts_columns, system.processes, system.replicas, system.replication_queue, system.settings, etc.  These contain system information we likely do not want regular users to have access to.

If granular access is not possible, perhaps a profile heuristic (similar to the 'readonly' heuristic) could at least be created that would provide only least-privileged style access to these resources?

Many thanks

**Comment by ryn9** [comment]
Any better way to get developers attention on this matter?

**Comment by sushiMix** [comment]
in 20.5 I have seen some new improvements on user management but system tables can still be requested by any user. I canpotentially use the ROW policy on each table to filter the SELECT result for system tables but need to do it for each table (and need to track new tables on each upgrade).

**Comment by alexey-milovidov** [comment]
> The REVOKE SELECT on system.* does not work (maybe some tables are required to be visible).

@vitlibar Why not?

**Comment by vitlibar** [comment]
There are privileges `SHOW_COLUMNS`, `SHOW_TABLES`, `SHOW_DATABASES` which control visibility of columns, tables, and databases to user. For example, if you don't have `SHOW_COLUMNS` privilege for some column that column isn't displayed in the `system.columns` table for you.

The SHOW_COLUMNS privilege is special: it's granted implictly with any other "column" grant. And the privilege "SHOW COLUMNS" implicitly grants "SHOW TABLES" for the correspondent table, and so on. For example,

```
GRANT SELECT(x,y) ON db.table TO user1
```

implicitly grants

```
GRANT SHOW COLUMNS(x,y) ON db.table TO user1
GRANT SHOW TABLES ON db.table TO user1
GRANT SHOW DATABASES ON db.* TO user1
```

**Comment by vitlibar** [comment]
Also there is privilege "SHOW_USERS" which controls visibility of user names and grants to other users.

**Comment by vitlibar** [comment]
> > The REVOKE SELECT on system.* does not work (maybe some tables are required to be visible).
> 
> @vitlibar Why not?

The `REVOKE SELECT on system.*` command does not work because it's granted implictly. And it's granted implicitly in order to use those "SHOW *" commands to control access.

**Comment by vitlibar** [comment]
I think we should provide implicit access only to few system tables, not all of them. Or maybe we should implement more `SHOW <something>` privileges.

**Comment by alexey-milovidov** [comment]
This can be solved with row policies.
