### ISSUE TITLE
CREATE OR REPLACE TABLE on a DISTRIBUTED table while performing writes

### ISSUE THREAD

**Issue by amirvaza** [ClickHouse/ClickHouse#24566]
Hi everyone, 

ClickHouse server version 21.5.5.12 (official build). (docker image)

**Some notes:**
Have 2 servers `ch1`, `ch2`, each has 2 tables `t1` and `t2` and another table `distributed_t1`

I tried to use `CREATE OR REPLACE TABLE` on table `distributed_t1` while performing writes+read from that table

While performing writes, RECREATed distributed_t1 and pointed it to t2 instead of t1

But some of the data was missing from t1, how do i know?
I have used insert bulks of 100 inserts, and after recreating, count() returned a number that doesn't divide by 100, meaning some of it was missing.

To be precise, the data that should have been on the _other_ server is missing.

**Example:**
```
CREATE TABLE t1 ON CLUSTER my_cluster (a UInt64, b UInt64) ENGINE=MergeTree()
CREATE TABLE t2 ON CLUSTER my_cluster (a UInt64, b UInt64) ENGINE=MergeTree()
CREATE TABLE IF NOT EXISTS distributed_t1 ON CLUSTER my_cluster ( a UInt64, b UInt64 ) ENGINE = Distributed('my_cluster', 'default', 't1', b) SETTINGS fsync_after_insert = 0, fsync_directories = 0
```
Recreate:
```
CREATE OR REPLACE TABLE distributed_t1 ON CLUSTER my_cluster ( a UInt64, b UInt64 ) ENGINE = Distributed('my_cluster', 'default', 't2', b) SETTINGS fsync_after_insert = 0, fsync_directories = 0
```
Writes are sequential number of column `b`, all writes are written to `ch1`, when recreating, sometimes half (because there are 2 servers) of the data is missing from `t1` and `t2` on both server servers

Not sure if related, but same things can also happen while reading from Merge() engine and recreating it

My question is, how far ATOMIC are those commands over an atomic database?
I was expecting the server to flush writes to a certain point, do the command, and then continue with the same pointer to the same table in that point of time

What am I missing? Am I missing something?

Thanks.

**Comment by tavplubix** [comment]
`REPLACE TABLE t ...` query is a kind of syntax sugar, it works the following queries:
 ```
CREATE TABLE tmp_replace_xxxxxx ...
EXCHANGE TABLES t AND tmp_replace_xxxxxx -- it's atomic
DROP TABLE tmp_replace_xxxxxx
```

If table engine is `Distributed` and `insert_distributed_sync=0` then it's possible that some data were inserted into Distributed table before `EXCHANGE`, but it were not flushed into destination tables before `DROP`.

Probably we can fix it on ClickHouse side by forcefully flushing Distributed table after `EXCHANGE`

**Comment by amirvaza** [comment]
Awesome.
It will make things much easier for us, we don't mind which table it will be flushed into, but we do mind to not lose the data of course.
