### ISSUE TITLE
Question about shared_ptr_helper

### ISSUE THREAD

**Issue by wangzhen11aaa** [ClickHouse/ClickHouse#24575]
I have a question about this template class.
```c++
/** Allows to make std::shared_ptr from T with protected constructor.
  *
  * Derive your T class from shared_ptr_helper<T> and add shared_ptr_helper<T> as a friend
  *  and you will have static 'create' method in your class.
  */
template <typename T>
struct shared_ptr_helper
{
    template <typename... TArgs>
    static std::shared_ptr<T> create(TArgs &&... args)
    {
        return std::shared_ptr<T>(new T(std::forward<TArgs>(args)...));
    }
};

Many places use this pattern
class StorageReplicatedMergeTree final : public ext::shared_ptr_helper<StorageReplicatedMergeTree>, public MergeTreeData
{
    friend struct ext::shared_ptr_helper<StorageReplicatedMergeTree>;
..
};

But I think the friend class is redundant.

For example

#include <iostream>
#include <memory>

using namespace std;
template <typename T>
struct shared_ptr_helper
{
    template <typename... TArgs>
    static std::shared_ptr<T> create(TArgs &&... args)
    {
        return std::shared_ptr<T>(new T(std::forward<TArgs>(args)...));
    }
};
class A:public shared_ptr_helper<A>{
    public:
    int a;
};

int main(){
    std::shared_ptr<A> aObj = A::create();
    cout << aObj->a << endl;
}
```

This code also can use the create method. Here is the question, what does the friend class do in this pattern. 
Thanks.

**Comment by kitaisreal** [comment]
@wangzhen11aaa we make ext::shared_ptr_helper friend because we want to create protected or private constructors, but force clients to use shared_ptr_helper create method for object construction.

**Comment by wangzhen11aaa** [comment]
#include <iostream>
#include <memory>

using namespace std;
template <typename T>
struct shared_ptr_helper
{
    template <typename... TArgs>
    static std::shared_ptr<T> create(TArgs &&... args)
    {
        return std::shared_ptr<T>(new T(std::forward<TArgs>(args)...));
    }
};
class A:public shared_ptr_helper<A>{
    friend shared_ptr_helper<A>;
    public:
    int a;
    protected:
        A()=default;
};

int main(){
    std::shared_ptr<A> aObj = A::create();
    cout << aObj->a << endl;
}
OK
