### ISSUE TITLE
Quadkey support

### ISSUE THREAD

**Issue by ethlo** [ClickHouse/ClickHouse#2458]
As several other tickets mention in passing, it would be very nice to be able to use quadkey indexing for proximity searches. A work-around has been explored in the following blog posts, however, it requires that the lat/lon coordinate is still present for doing the final sorting by distance.  

```
SELECT 
    lat,
    lon, 
    user_id, 
    greatCircleDistance(lon, lat, -73.985195, 40.75896) AS dist, 
    bar(dist, 0, 10000) AS bar
FROM events 
WHERE ((quadkey >= 1013670044871163904) AND (quadkey <= 1013670049166131200)) AND (dist < 10000)
ORDER BY dist ASC
LIMIT 5
```

Wanted functions:
`coordinateToQuadkey(float64 lon, float64 lat)` - gives the quadkey (int64) for the given coordinates
`quadkeyToCoordinate(int64 quadkey)` - Gives the coordinates (lon/lat) for the quadkey

This would be great if this also would allow us to do 
`greatCircleDistanceQuadkey(quadkey, -73.985195, 40.75896) AS dist`
Or even better, make Clickhouse use Quadkey behind the scenes for improving lookup time :).

References
* https://github.com/CartoDB/python-quadkey/
 * "Geospatial processing with Clickhouse" - https://carto.com/blog/inside/geospatial-processing-with-clickhouse/
*"Geospatial processing with Clickhouse, take 2 - https://carto.com/blog/inside/geospatial-processing-with-clickhouse-take-2/
* https://github.com/yandex/ClickHouse/issues/2008
* https://github.com/yandex/ClickHouse/pull/1908

PS: I have only just started exploring ClickHouse in the last few days, and I love it so far. Keep up the good work!

**Comment by alexey-milovidov** [comment]
Also geohash support will be useful:
https://github.com/yinqiwen/geohash-int/blob/master/geohash.c

**Comment by alexey-milovidov** [comment]
Now we have `geohash` functions and in addition `geoToH3` function.
```
milovidov-Pro-P30 :) SELECT geo
geoToH3         geohashDecode   geohashEncode   geohashesInBox
```
