### ISSUE TITLE
Different query result between 20.3LTS and 20.8LTS 

### ISSUE THREAD

**Issue by taiyang-li** [ClickHouse/ClickHouse#24602]
**Describe the unexpected behaviour**
When I excute query: `select match('sss','^[\D]*$') a` in https://play.clickhouse.tech
It returns different result bettwen 20.3LTS and 20.8LTS 

Using 20.3 LTS,  this query returns 0
Using 20.8 LTS,  this query returns 1.

**Comment by alexey-milovidov** [comment]
It's described in the changelog.

**Comment by alexey-milovidov** [comment]
https://github.com/ClickHouse/ClickHouse/blob/master/docs/en/whats-new/changelog/2020.md#improvement-15

**Comment by taiyang-li** [comment]
Thanks @alexey-milovidov
