### ISSUE TITLE
background thread keep selecting the same parts but never be able to finish the compact.

### ISSUE THREAD

**Issue by qingping209** [ClickHouse/ClickHouse#24603]
When I observed "too many parts " in the log, I tried to check the exact part number, but failed.  select count(*) from system.parts blocked?

**Comment by qingping209** [comment]
and mean while, the system ouput logs as follows insanely:

![Uploading image.png…]()

**Comment by qingping209** [comment]
and I dig into the code(v21.4.4.30)  a bit.  SelectePartsToMerge was called according to the log, and a non-null MergeMutateSelectedEntry ptr is returned; by what's weird is, mergeSelectedParts is not called since no log "Merging {} parts: from {} to {} into {}" appeared.

**Comment by alesapin** [comment]
Hi! The logs look quite weird. Which version do you use? Also, please show the output of `select * from system.settings where changed=1` and `select * from system.merge_tree_settings where changed=1`. If you will be able to reproduce the case then gdb-traces or output of `SELECT arrayStringConcat(arrayMap(x, y -> concat(x, ': ', y), arrayMap(x -> addressToLine(x), trace), arrayMap(x -> demangle(addressToSymbol(x)), trace)), '\n') as trace FROM system.stack_trace format Vertical` will be useful.

**Comment by qingping209** [comment]
> Hi! The logs look quite weird. Which version do you use? Also, please show the output of `select * from system.settings where changed=1` and `select * from system.merge_tree_settings where changed=1`. If you will be able to reproduce the case then gdb-traces or output of `SELECT arrayStringConcat(arrayMap(x, y -> concat(x, ': ', y), arrayMap(x -> addressToLine(x), trace), arrayMap(x -> demangle(addressToSymbol(x)), trace)), '\n') as trace FROM system.stack_trace format Vertical` will be useful.

thx for you reply. I restarted the process to resume our service.  I can not reproduce it for now.  Do you have any comment on the bold words:

> And I dig into the code(v21.4.4.30) a bit. SelectePartsToMerge was called according to the log, and a non-null MergeMutateSelectedEntry ptr is returned; **_but what's weird is, mergeSelectedParts is not called since no log "Merging {} parts: from {} to {} into {}" appeared._**

**Comment by wangzhen11aaa** [comment]
How to close these stuff. CK only selects and does not do any merge.


2021.06.01 17:16:48.350993 [ 1263789 ] {} <Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 2.97 TiB.
2021.06.01 17:16:48.446263 [ 1263776 ] {} <Debug> system.metric_log (8a648132-f1ff-4e97-b40a-76b0e5b510ca) (MergerMutator): Selected 8 parts from 202106_1_22_2 to 202106_29_29_0
2021.06.01 17:16:48.446512 [ 1263776 ] {} <Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 2.97 TiB.
2021.06.01 17:16:48.452455 [ 1263791 ] {} <Debug> system.text_log (a92acfd8-e49a-4b80-b354-7fe8441bd495) (MergerMutator): Selected 8 parts from 202106_1_22_2 to 202106_29_29_0
2021.06.01 17:16:48.452652 [ 1263791 ] {} <Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 2.97 TiB.
2021.06.01 17:16:48.550762 [ 1263792 ] {} <Debug> system.metric_log (8a648132-f1ff-4e97-b40a-76b0e5b510ca) (MergerMutator): Selected 8 parts from 202106_1_22_2 to 202106_29_29_0
2021.06.01 17:16:48.551019 [ 1263792 ] {} <Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 2.97 TiB.
2021.06.01 17:16:48.553257 [ 1263787 ] {} <Debug> system.text_log (a92acfd8-e49a-4b80-b354-7fe8441bd495) (MergerMutator): Selected 8 parts from 202106_1_22_2 to 202106_29_29_0
2021.06.01 17:16:48.553612 [ 1263787 ] {} <Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 2.97 TiB.
^C2021.06.01 17:16:48.626461 [ 1263765 ] {} <Trace> BaseDaemon: Received signal 2
2021.06.01 17:16:48.626621 [ 1263765 ] {} <Information> Application: Received termination signal (Interrupt: 2)
2021.06.01 17:16:48.626783 [ 1263753 ] {} <Debug> Application: Received termination signal.
2021.06.01 17:16:48.626855 [ 1263753 ] {} <Debug> Application: Waiting for current connections to close.
2021.06.01 17:16:48.655355 [ 1263779 ] {} <Debug> system.text_log (a92acfd8-e49a-4b80-b354-7fe8441bd495) (MergerMutator): Selected 8 parts from 202106_1_22_2 to 202106_29_29_0
2021.06.01 17:16:48.655366 [ 1263774 ] {} <Debug> system.metric_log (8a648132-f1ff-4e97-b40a-76b0e5b510ca) (MergerMutator): Selected 8 parts from 202106_1_22_2 to 202106_29_29_0
2021.06.01 17:16:48.655548 [ 1263779 ] {} <Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 2.97 TiB.
2021.06.01 17:16:48.655789 [ 1263774 ] {} <Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 2.97 TiB.
2021.06.01 17:16:48.756407 [ 1263777 ] {} <Debug> system.text_log (a92acfd8-e49a-4b80-b354-7fe8441bd495) (MergerMutator): Selected 8 parts from 202106_1_22_2 to 202106_29_29_0
2021.06.01 17:16:48.756422 [ 1263790 ] {} <Debug> system.metric_log (8a648132-f1ff-4e97-b40a-76b0e5b510ca) (MergerMutator): Selected 8 parts from 202106_1_22_2 to 202106_29_29_0
2021.06.01 17:16:48.756619 [ 1263777 ] {} <Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 2.97 TiB.
2021.06.01 17:16:48.756754 [ 1263790 ] {} <Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 2.97 TiB.
2021.06.01 17:16:48.860736 [ 1263773 ] {} <Debug> system.metric_log (8a648132-f1ff-4e97-b40a-76b0e5b510ca) (MergerMutator): Selected 8 parts from 202106_1_22_2 to 202106_29_29_0
2021.06.01 17:16:48.860736 [ 1263786 ] {} <Debug> system.text_log (a92acfd8-e49a-4b80-b354-7fe8441bd495) (MergerMutator): Selected 8 parts from 202106_1_22_2 to 202106_29_29_0

**Comment by qingping209** [comment]
> 2021.06.01 17:16:48.860736 [ 1263773 ] {} system.metric_log (8a648132-f1ff-4e97-b40a-76b0e5b510ca) (MergerMutator): Selected 8 parts from 202106_1_22_2 to 202106_29_29_0

 I believe it's the same issue. you can follow the instruction in the source issue to check some internal states of clickhouse process.

**Comment by qingping209** [comment]
> Hi! The logs look quite weird. Which version do you use? Also, please show the output of `select * from system.settings where changed=1` and `select * from system.merge_tree_settings where changed=1`. If you will be able to reproduce the case then gdb-traces or output of `SELECT arrayStringConcat(arrayMap(x, y -> concat(x, ': ', y), arrayMap(x -> addressToLine(x), trace), arrayMap(x -> demangle(addressToSymbol(x)), trace)), '\n') as trace FROM system.stack_trace format Vertical` will be useful.

`
SELECT *
FROM system.settings
WHERE changed = 1

Query id: 50c36e26-8469-4ea2-8d84-7499b3ffd7b9

Row 1:
──────
name:        use_uncompressed_cache
value:       0
changed:     1
description: Whether to use the cache of uncompressed blocks.
min:         ᴺᵁᴸᴸ
max:         ᴺᵁᴸᴸ
readonly:    0
type:        Bool

Row 2:
──────
name:        background_pool_size
value:       32
changed:     1
description: Number of threads performing background work for tables (for example, merging in merge tree). Only has meaning at server startup.
min:         ᴺᵁᴸᴸ
max:         ᴺᵁᴸᴸ
readonly:    0
type:        UInt64

Row 3:
──────
name:        load_balancing
value:       random
changed:     1
description: Which replicas (among healthy replicas) to preferably send a query to (on the first attempt) for distributed processing.
min:         ᴺᵁᴸᴸ
max:         ᴺᵁᴸᴸ
readonly:    0
type:        LoadBalancing

Row 4:
──────
name:        max_memory_usage
value:       10000000000
changed:     1
description: Maximum memory usage for processing of single query. Zero means unlimited.
min:         ᴺᵁᴸᴸ
max:         ᴺᵁᴸᴸ
readonly:    0
type:        UInt64

Row 5:
──────
name:        allow_introspection_functions
value:       0
changed:     1
description: Allow functions for introspection of ELF and DWARF for query profiling. These functions are slow and may impose security considerations.
min:         ᴺᵁᴸᴸ
max:         ᴺᵁᴸᴸ
readonly:    0
type:        Bool
`

`
SELECT *
FROM system.merge_tree_settings
WHERE changed = 1

Query id: 9a28d081-a911-43cd-8506-755af95bdf9e

Row 1:
──────
name:        old_parts_lifetime
value:       0
changed:     1
description: How many seconds to keep obsolete parts.
type:        Seconds

Row 2:
──────
name:        parts_to_delay_insert
value:       2000
changed:     1
description: If table contains at least that many active parts in single partition, artificially slow down insert into table.
type:        UInt64

Row 3:
──────
name:        parts_to_throw_insert
value:       2000
changed:     1
description: If more than this number active parts in single partition, throw 'Too many parts ...' exception.
type:        UInt64

Row 4:
──────
name:        max_parts_in_total
value:       1000000
changed:     1
description: If more than this number active parts in all partitions in total, throw 'Too many parts ...' exception.
type:        UInt64

4 rows in set. Elapsed: 0.002 sec. 
`

**Comment by qingping209** [comment]
> @qingping209 Are there any `Memory limit exceeded` errors in logs before the merges stop execution?

![image](https://user-images.githubusercontent.com/11344292/120456754-7ba1aa00-c3c8-11eb-9e54-fd52c8cd8eb5.png)

yes. It seems that merge stopping execution happened immediately after the system hit memory limit.

**Comment by alesapin** [comment]
Good. Actually, we have multiple fixes for this problem recently. I just added one non-significant fix. Probably with the newer versions the error will be fixed.

**Comment by qingping209** [comment]
> Good. Actually, we have multiple fixes for this problem recently. I just added one non-significant fix. Probably with the newer versions the error will be fixed.

![image](https://user-images.githubusercontent.com/11344292/120460810-08019c00-c3cc-11eb-9d42-8b4489ac57ac.png)

Can you explain a bit who throw the exception  ?

**Comment by alesapin** [comment]
`tryLogCurrentException` itself can throw an exception. `scheduleOrThrowOnError` throws an exception when it was not able to allocate a thread or there was an exception in previous jobs https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ThreadPool.h#L41-L43.

**Comment by qingping209** [comment]
> `tryLogCurrentException` itself can throw an exception. `scheduleOrThrowOnError` throws an exception when it was not able to allocate a thread or there was an exception in previous jobs https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ThreadPool.h#L41-L43.

thx
