### ISSUE TITLE
Existance condition for alter query

### ISSUE THREAD

**Issue by crakjie** [ClickHouse/ClickHouse#2469]
Is that possible to see in future the altering language enhanced with column existence conditions?

`ALTER TABLE [db].name [ON CLUSTER cluster] ADD [IF NOT EXISTS]|DROP [IF EXISTS]|MODIFY COLUMN [IF EXISTS]`

**Comment by alexey-milovidov** [comment]
https://github.com/ClickHouse/ClickHouse/pull/3900
