### ISSUE TITLE
Why do select * from table use  a lot of memory like 10G when we use BufferBase whoes default size is 1MB and it is used recycled. 

### ISSUE THREAD

**Issue by wangzhen11aaa** [ClickHouse/ClickHouse#24749]
Why do select * from table use  a lot of memory like 10G when we use BufferBase whoes default size is 1MB and it is used recycled. 
Whether does it do the right thing, or may be something wrong with it.

**Comment by den-crane** [comment]
Clickhouse version? 
What is BufferBase?

**Comment by wangzhen11aaa** [comment]
21.4.1.1

**Comment by wangzhen11aaa** [comment]
I read the code, from Client.app, through IStreamBlock/ Block/ Buffer/BufferBase class. Just not figure out why do select cost so much memory.

**Comment by den-crane** [comment]
try this

```
cat /etc/clickhouse-server/users.d/min_bytes_to_use_mmap_io.xml
<?xml version="1.0"?>
<yandex>
    <profiles>
        <default>
            <min_bytes_to_use_mmap_io>0</min_bytes_to_use_mmap_io>
       </default>
    </profiles>
</yandex>
```

>21.4.1.1

Are you sure? Such version is not stable.
Upgrade to 21.4.7.3

**Comment by wangzhen11aaa** [comment]
> try this
> 
> ```
> cat /etc/clickhouse-server/users.d/min_bytes_to_use_mmap_io.xml
> <?xml version="1.0"?>
> <yandex>
>     <profiles>
>         <default>
>             <min_bytes_to_use_mmap_io>0</min_bytes_to_use_mmap_io>
>        </default>
>     </profiles>
> </yandex>
> ```
> 
> > 21.4.1.1
> 
> Are you sure? Such version is not stable.
> Upgrade to 21.4.7.3

Ok, I will try this configuration first.Thank you.

**Comment by wangzhen11aaa** [comment]
This configuration is disabled by default.

**Comment by wangzhen11aaa** [comment]
> try this
> 
> ```
> cat /etc/clickhouse-server/users.d/min_bytes_to_use_mmap_io.xml
> <?xml version="1.0"?>
> <yandex>
>     <profiles>
>         <default>
>             <min_bytes_to_use_mmap_io>0</min_bytes_to_use_mmap_io>
>        </default>
>     </profiles>
> </yandex>
> ```
> 
> > 21.4.1.1
> 
> Are you sure? Such version is not stable.
> Upgrade to 21.4.7.3
This configuration is 0 by default. I just use it by default.

**Comment by alexey-milovidov** [comment]
The behaviour is correct.
See the `max_block_size` and `max_threads` parameters.
