### ISSUE TITLE
Can multi ClickHouse share same S3 storage path, one rw, others ro

### ISSUE THREAD

**Issue by pan3793** [ClickHouse/ClickHouse#24752]
Hi community,

I see that ClickHouse support S3 Storage now, as S3 is a distribute storage, if there possible to use S3 storage as an alternation of `Replicated*MergeTree` for small or medium dataset(million ~ billion records) but wants HA and high query concurrency(over 10k/s)?

Suppose multi ClickHouse instances create MergeTree family table share the same S3 storage and the same path, only one ClickHouse node write data, and all ClickHouse nodes can read data.

Does it technically feasible? Will or will not ClickHouse consider to suppose it in future?

**Comment by UnamedRus** [comment]
You can look at s3 zero copy replication https://github.com/ClickHouse/ClickHouse/pull/16240

**Comment by pan3793** [comment]
Thanks for answer, it's an amazing feature.
