### ISSUE TITLE
agg in Distributed table error

### ISSUE THREAD

**Issue by ljwps** [ClickHouse/ClickHouse#24783]
My sql is :

select webid, nation, city, sum(pv), SUM(timelong)
from juba_sessioncount
where cdate between '2020-01-31' and '2021-06-30'
  and webid = 36
GROUP BY webid, nation, city;

juba_sessioncount  is a Distributed table

this sql run error：
java.sql.SQLException: ClickHouse exception, code: 70, host: 192.168.5.44, port: 8123; Code: 70, e.displayText() = DB::Exception: Conversion from AggregateFunction(sum, Int32) to AggregateFunction(sum, Nullable(Int32)) is not supported: while converting source column `sum(timelong)` to destination column `sum(timelong)` (version 21.4.6.55 (official build))
 Query: select webid, nation, city, sum(pv), SUM(timelong) from juba_sessioncount where cdate between '2020-01-31' and '2021-06-30' and webid = 36 GROUP BY webid, nation, city Parameters: []

CH driver is   clickhouse-jdbc  0.3.1

BUT
this sql works well under clickhouse-client
AND
this sql works well under local table with jdbc

**Comment by den-crane** [comment]
please share:
```
show create table juba_sessioncount;
show create table ...local..;
```

**Comment by ljwps** [comment]
> please share:
> 
> ```
> show create table juba_sessioncount;
> show create table ...local..;
> ```
Thank you for your reply.

I found that if this SQL "**CREATE TABLE IF NOT EXISTS juba_sessioncount ON CLUSTER perftest_3shards_1replicas AS juba_sessioncount_replica ENGINE = Distributed(perftest_3shards_1replicas,juba,juba_sessioncount_replica,rand())**" is used to build a distributed table **(without defining any fields)**,  it will establish **nullable fields** in the distributed table, so the SQL statement above will report an error

**juba_sessioncount:**
CREATE TABLE IF NOT EXISTS juba_sessioncount ON CLUSTER perftest_3shards_1replicas AS juba_sessioncount_replica ENGINE = Distributed(perftest_3shards_1replicas,juba,juba_sessioncount_replica,rand())

**show create table ...local**
CREATE TABLE juba_sessioncount_replica on CLUSTER 'perftest_3shards_1replicas'
(
	"_id" String,
	"resourcedomain" String,
	"date_year" Int32,
	"keywords" String,
	"nation" String,
	"city" String,
	"pv" Int32,
	"firsturl" String,
	"_timestamp_long_" DateTime64(3, 'Asia/Shanghai'),
	"language" String,
	"sessionid" String,
	"resolution" String,
	"webid" Int32,
	"istagcount" Int32,
	"province" String,
	"engine" String,
	"browser" String,
	"cookieid" String,
	"colordepth" String,
	"createtime" DateTime64(3, 'Asia/Shanghai'),
	"date_month" Int32,
	"iseventcount" Int32,
	"ip" String,
	"systemname" String,
	"usertype" Int32,
	"terminal" String,
	"date_day" Int32,
	"useruuid" String,
	"resourcetype" Int32,
	"timelong" Int32,
	"cdate" DateTime64(3, 'Asia/Shanghai'),
	"visitortype" Int32,
	"resourceurl" String,
	"date_hh" Int32,
	"district" String,
	"region" String,
	"flash" String
)ENGINE=ReplicatedMergeTree('/clickhouse/tables/{shard}/juba/juba_sessioncount_replica','{replica}')
PRIMARY KEY (cdate,webid,sessionid)
ORDER BY (cdate,webid,sessionid,nation,city)
PARTITION BY toYYYYMM(cdate)

**Comment by den-crane** [comment]
> it will establish nullable fields in the distributed table, so the SQL statement above will report an error

Please show the example.
Steps to reproduce.

I cannot repro this

```
CREATE TABLE juba_sessioncount_replica
(
    `_id` String,
    `resourcedomain` String,
    `date_year` Int32,
    `keywords` String,
    `nation` String,
    `city` String,
    `pv` Int32,
    `firsturl` String,
    `timestamp_long` DateTime64(3, 'Asia/Shanghai'),
    `language` String,
    `sessionid` String,
    `resolution` String,
    `webid` Int32,
    `istagcount` Int32,
    `province` String,
    `engine` String,
    `browser` String,
    `cookieid` String,
    `colordepth` String,
    `createtime` DateTime64(3, 'Asia/Shanghai'),
    `date_month` Int32,
    `iseventcount` Int32,
    `ip` String,
    `systemname` String,
    `usertype` Int32,
    `terminal` String,
    `date_day` Int32,
    `useruuid` String,
    `resourcetype` Int32,
    `timelong` Int32,
    `cdate` DateTime64(3, 'Asia/Shanghai'),
    `visitortype` Int32,
    `resourceurl` String,
    `date_hh` Int32,
    `district` String,
    `region` String,
    `flash` String
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(cdate)
PRIMARY KEY (cdate, webid, sessionid)
ORDER BY (cdate, webid, sessionid, nation, city);

CREATE TABLE IF NOT EXISTS juba_sessioncount AS juba_sessioncount_replica
ENGINE = Distributed(test_shard_localhost, currentDatabase(), juba_sessioncount_replica, rand());

SHOW CREATE TABLE juba_sessioncount

Query id: 3c73b15a-9211-4b95-9360-e5ffcaec0cbc

┌─statement──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ CREATE TABLE dw.juba_sessioncount
(
    `_id` String,
    `resourcedomain` String,
    `date_year` Int32,
    `keywords` String,
    `nation` String,
    `city` String,
    `pv` Int32,
    `firsturl` String,
    `timestamp_long` DateTime64(3, 'Asia/Shanghai'),
    `language` String,
    `sessionid` String,
    `resolution` String,
    `webid` Int32,
    `istagcount` Int32,
    `province` String,
    `engine` String,
    `browser` String,
    `cookieid` String,
    `colordepth` String,
    `createtime` DateTime64(3, 'Asia/Shanghai'),
    `date_month` Int32,
    `iseventcount` Int32,
    `ip` String,
    `systemname` String,
    `usertype` Int32,
    `terminal` String,
    `date_day` Int32,
    `useruuid` String,
    `resourcetype` Int32,
    `timelong` Int32,
    `cdate` DateTime64(3, 'Asia/Shanghai'),
    `visitortype` Int32,
    `resourceurl` String,
    `date_hh` Int32,
    `district` String,
    `region` String,
    `flash` String
)
ENGINE = Distributed('test_shard_localhost', 'dw', 'juba_sessioncount_replica', rand()) │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

**Comment by ljwps** [comment]
> > it will establish nullable fields in the distributed table, so the SQL statement above will report an error
> 
> Please show the example.
> Steps to reproduce.
> 
> I cannot repro this
> 
> ```
> CREATE TABLE juba_sessioncount_replica
> (
>     `_id` String,
>     `resourcedomain` String,
>     `date_year` Int32,
>     `keywords` String,
>     `nation` String,
>     `city` String,
>     `pv` Int32,
>     `firsturl` String,
>     `timestamp_long` DateTime64(3, 'Asia/Shanghai'),
>     `language` String,
>     `sessionid` String,
>     `resolution` String,
>     `webid` Int32,
>     `istagcount` Int32,
>     `province` String,
>     `engine` String,
>     `browser` String,
>     `cookieid` String,
>     `colordepth` String,
>     `createtime` DateTime64(3, 'Asia/Shanghai'),
>     `date_month` Int32,
>     `iseventcount` Int32,
>     `ip` String,
>     `systemname` String,
>     `usertype` Int32,
>     `terminal` String,
>     `date_day` Int32,
>     `useruuid` String,
>     `resourcetype` Int32,
>     `timelong` Int32,
>     `cdate` DateTime64(3, 'Asia/Shanghai'),
>     `visitortype` Int32,
>     `resourceurl` String,
>     `date_hh` Int32,
>     `district` String,
>     `region` String,
>     `flash` String
> )
> ENGINE = MergeTree
> PARTITION BY toYYYYMM(cdate)
> PRIMARY KEY (cdate, webid, sessionid)
> ORDER BY (cdate, webid, sessionid, nation, city);
> 
> CREATE TABLE IF NOT EXISTS juba_sessioncount AS juba_sessioncount_replica
> ENGINE = Distributed(test_shard_localhost, currentDatabase(), juba_sessioncount_replica, rand());
> 
> SHOW CREATE TABLE juba_sessioncount
> 
> ┌─statement──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
> │ CREATE TABLE dw.juba_sessioncount
> (
>     `_id` String,
>     `resourcedomain` String,
>     `date_year` Int32,
>     `keywords` String,
>     `nation` String,
>     `city` String,
>     `pv` Int32,
>     `firsturl` String,
>     `timestamp_long` DateTime64(3, 'Asia/Shanghai'),
>     `language` String,
>     `sessionid` String,
>     `resolution` String,
>     `webid` Int32,
>     `istagcount` Int32,
>     `province` String,
>     `engine` String,
>     `browser` String,
>     `cookieid` String,
>     `colordepth` String,
>     `createtime` DateTime64(3, 'Asia/Shanghai'),
>     `date_month` Int32,
>     `iseventcount` Int32,
>     `ip` String,
>     `systemname` String,
>     `usertype` Int32,
>     `terminal` String,
>     `date_day` Int32,
>     `useruuid` String,
>     `resourcetype` Int32,
>     `timelong` Int32,
>     `cdate` DateTime64(3, 'Asia/Shanghai'),
>     `visitortype` Int32,
>     `resourceurl` String,
>     `date_hh` Int32,
>     `district` String,
>     `region` String,
>     `flash` String
> )
> ENGINE = Distributed('test_shard_localhost', 'dw', 'juba_sessioncount_replica', rand()) │
> └────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
> ```
Thank you for your reply.

My mistake !

Using this SQL is right:
CREATE TABLE IF NOT EXISTS juba_sessioncount ON CLUSTER perftest_3shards_1replicas
AS **juba.**juba_sessioncount_replica
ENGINE = Distributed(perftest_3shards_1replicas,juba,juba_sessioncount_replica,rand());

In database **default**, the fields of table juba_sessioncount_replica  are all nullable
In database **juba**, the fields of table juba_sessioncount_replica  are all default

so ,this sql
**CREATE TABLE IF NOT EXISTS juba_sessioncount ON CLUSTER perftest_3shards_1replicas
AS juba_sessioncount_replica
ENGINE = Distributed(perftest_3shards_1replicas,juba,juba_sessioncount_replica,rand());**
uses the **default database**
