### ISSUE TITLE
Projections: combine resultset from main table and projection.

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#24810]
**Use case**
Allow to combine output from projection and non aggregated main table.

Allow to use less precise functions in GROUP BY keys.

**Describe the solution you'd like**
```

DROP TABLE IF EXISTS tp;

CREATE TABLE tp
(
    `type` Int32,
    `ts` DateTime,
    `eventcnt` UInt64,
    PROJECTION p
    (
        SELECT
            type,
            toStartOfHour(ts),
            sum(eventcnt)
        GROUP BY
            type,
            toStartOfHour(ts)
    )
)
ENGINE = MergeTree
ORDER BY (type, ts)

INSERT INTO tp SELECT
    number % 3,
    toDateTime('2021-04-05 00:00:00') + toIntervalMinute(number * 35),
    1
FROM numbers(1000)

set allow_experimental_projection_optimization = 1, force_optimize_projection = 1;

SELECT
    type,
    sum(eventcnt)
FROM tp
WHERE ts > '2021-04-05 00:00:55'
GROUP BY type

Query id: b79de24a-44e1-4956-b79f-17544b1456e7


0 rows in set. Elapsed: 0.002 sec.

Received exception from server (version 21.6.1):
Code: 584. DB::Exception: Received from localhost:9000. DB::Exception: No projection is used when allow_experimental_projection_optimization = 1.


But clickhouse should be able to optimize it it something like that:

SELECT
    type,
    sum(x)
FROM
(
    SELECT
        type,
        sum(eventcnt) AS x
    FROM tp
    WHERE (ts > '2021-04-05 00:00:55') AND (ts < toStartOfHour(toDateTime('2021-04-05 00:00:55')))
    GROUP BY type
    UNION ALL
    SELECT
        type,
        sum(eventcnt) AS x
    FROM tp
    WHERE toStartOfHour(ts) > '2021-04-05 00:00:55'
    GROUP BY type
)
GROUP BY type

Query id: d15dcef3-8b15-4046-8bc8-840dfeaba2df

┌─type─┬─sum(x)─┐
│    0 │    333 │
│    2 │    333 │
│    1 │    332 │
└──────┴────────┘


select type, sum(eventcnt)　from tp GROUP BY type, toStartOfDay(ts);

SELECT
    type,
    sum(eventcnt)
FROM tp
GROUP BY
    type,
    toStartOfDay(ts)

Query id: deec4c69-c841-4102-94c4-d52ab75b30a1


0 rows in set. Elapsed: 0.004 sec.

Received exception from server (version 21.6.1):
Code: 584. DB::Exception: Received from localhost:9000. DB::Exception: No projection is used when allow_experimental_projection_optimization = 1.

SELECT
    type,
    sum(eventcnt)
FROM tp
GROUP BY
    type,
    toStartOfDay(toStartOfHour(ts))
FORMAT Null

Query id: 1066c944-adad-4a7a-97be-eb342de1196c

Ok.

0 rows in set. Elapsed: 0.004 sec. Processed 1.00 thousand rows, 28.29 KB (263.60 thousand rows/s., 7.46 MB/s.)

```

**Comment by amosbird** [comment]
> Allow to combine output from projection and non aggregated main table.

I've got this feature request multiple times, however, I still cannot find a general way to solve it. I think we should provide a dedicated MergeTree engine that's made for time series data, with implicit date time column. Then we can provide sophisticate partition/index/projection rules over the time column, simiar to Druid.

> Allow to use less precise functions in GROUP BY keys.

I did something like this for index analysis. It requires hardcoded rules which I don't like.

**Comment by UnamedRus** [comment]
> I still cannot find a general way to solve it. 
> One possible solution would be providing a dedicated MergeTree engine that's made for time series data, with implicit date time column. 

So it wouldn't be general solution, right? 
For me having dedicated MergeTree engine looks like an over kill for this situation.

>  It requires hardcoded rules which I don't like.

Hardcoded rules for conversion between specific functions? 

It does looks like that those issues share the same problem like this one https://github.com/ClickHouse/ClickHouse/issues/15257
We need some way to manipulate and convert conditions with time points and ranges in other set of conditions.

**Comment by UnamedRus** [comment]
What if we we have pretty usual table with monthly partitioning:

```
CREATE TABLE tp
(
    `type` Int32,
    `ts` DateTime,
    `eventcnt` UInt64,
    PROJECTION p
    (
        SELECT
            type,
            toStartOfHour(ts),
            sum(eventcnt)
        GROUP BY
            type,
            toStartOfHour(ts)
    )
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(ts)
ORDER BY (type, ts)
```

And usual query as well:

```
SELECT type, sum(eventcnt) FROM tp WHERE ts > '2017-01-10' AND ts < '2022-01-10'   GROUP BY type
```

So on part level (because of min-max index) ClickHouse can understand, that it either read part as whole either skip completely. (for all months between 201702 to 202112 that's true in our query)
And if ClickHouse read this part as whole, it can use projection for that.

If we will have some other conditions with ts column: 

```
SELECT type, sumIf(eventcnt, ts > '2019-01-10'), sumIf(eventcnt, ts > '2018-01-10')  FROM tp WHERE ts > '2017-01-10' AND ts < '2022-01-10'   GROUP BY type
```

In that case, ClickHouse will read 2 additional partitions (201901, 201801) from source table.

**Comment by UnamedRus** [comment]
https://kb.altinity.com/altinity-kb-queries-and-syntax/partial-projection-optimization/

**Comment by alexey-milovidov** [comment]
This task has an extremely low chance to be implemented.
