### ISSUE TITLE
Improve documentation about <remote_url_allow_hosts> in config.xml

### ISSUE THREAD

**Issue by cn-ds** [ClickHouse/ClickHouse#24836]
**Describe the issue**

I was trying to update the ``<remote_url_allow_hosts>`` and the documentation was a bit light and since it is obviously the best pratice to configure this section we could maybe add a bit of documentation.

Maybe we should add in the comment related to the **remote_url_allow_hosts** tag that you should use the following format to specify allowed hosts:
````
<host>yandex.ru</host>
````
We could also add an example using a regex.

**Additionnal info**

Since this change https://github.com/ClickHouse/ClickHouse/pull/20058 people will maybe need more info on the **remote_url_allow_hosts** tag

**Comment by filimonov** [comment]
Can you try to make desired improvement by your own? (there is a pen icon on the top right side on every doc page - which allow to edit docs & send PR)

**Comment by cn-ds** [comment]
Okay, I will close the issue when it's done.

**Comment by cn-ds** [comment]
@filimonov I made a PR here : https://github.com/ClickHouse/ClickHouse/pull/24918

Sorry if I'm not following the conventions.

**Comment by roman-vynar** [comment]
`remote_url_allow_hosts` is still missing from the docs https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings
