### ISSUE TITLE
How to realize data synchronization when adding a new replica to a Clickhouse

### ISSUE THREAD

**Issue by shadowDy** [ClickHouse/ClickHouse#24831]
Cluster status:

Currently, ZK is not introduced into the cluster, and reading and writing are realized through distributed tables; The configuration mode of multi slice and double copy is adopted.

The data quality of each replica is about 800g, using HDD storage

Problems encountered:

How to quickly synchronize historical data to a new replica instance when a single replica is down, an instance is migrated, or a new replica is added; How to ensure the consistency of historical data and delta data on the new replica with other replicas.

Does Clickhouse have any good suggestions on data consistency?

thanks~

**Comment by den-crane** [comment]
You can

1. stop ingestion
2. alter table freeze (make snapshot)
3. add a new server into cluster
4. start ingestion (new data will be added on both nodes)
5. copy / rsync snapshot , attach parts from the snapshot at the new replica.

Of course it's not possible for Replacing / Collapsing.

>How to ensure the consistency of historical data and delta data on the new replica with other replicas.

No good ways. Use replication (Zookeeper)

>Does Clickhouse have any good suggestions on data consistency?

Of course not. There is no easy way to compare 800g of data in two tables.
