### ISSUE TITLE
Why is kafka engine not connecting to the broker?

### ISSUE THREAD

**Issue by shaon-chowdhury** [ClickHouse/ClickHouse#24844]
I've setup a table using the kafka engine (defined below). However, I don't see any data in the `data_kafka` table when I query it even though the kafka topic is being populated by the producer.

```
CREATE TABLE data_kafka (
    test_col String, 
    value Nullable(Float32),
) ENGINE = Kafka('host:port','grp','grp','CSV')
```

I have added the following to `clickhouse-server/config.xml` so that the kafka cluster can be read from.

```
<kafka>
    <security_protocol>sasl_plaintext</security_protocol>
    <sasl_mechanism>PLAIN</sasl_mechanism>
    <sasl_username>username</sasl_username>
    <sasl_password>pwd</sasl_password>
    <debug>all</debug>
    <auto_offset_reset>latest</auto_offset_reset>
    <compression_type>snappy</compression_type>
</kafka>
```

In the logs, I see the following. It seems like there is an issue with validating SASL credentials but the `username` and `pwd` match the across the kafka producer and clickhouse configs.

```
[rdk:ERROR] [thrd:app]: data_kafka#consumer-2: sasl_plaintext:host:port/bootstrap: Disconnected while requesting ApiVersion: might be caused by incorrect security.protocol configuration (connecting to a SSL listener?) or broker version is < 0.10 (see api.version.request) (after 3ms in state APIVERSION_QUERY, 3 identical error(s) suppressed)
```

What could be going on here?

**Comment by filimonov** [comment]
Just as exception says - the most probable reason is wrong sasl_mechanism / security_protocol 

Also, keep in mind that config.xml changes require a clickhouse-server restart.

**Comment by filimonov** [comment]
See also: https://kb.altinity.com/altinity-kb-integrations/altinity-kb-kafka/altinity-kb-adjusting-librdkafka-settings
