### ISSUE TITLE
Incorrect partition drop when using insert_quorum

### ISSUE THREAD

**Issue by vasyaabr** [ClickHouse/ClickHouse#2485]
When dropping last (current) partition, with insert_quorum enabled, Clickhouse didn't refresh Zookeper node `/clickhouse/tables/cluster/table/quorum/last_part`. May be, this node didn't refreshed at all when any partition dropped.

When using `select_sequential_consistency`=1, this leads to exeption in all SELECT's.

Issue can be fixed by manual Zookeeper node update:
`set /clickhouse/tables/funprodwh/Turnovers/quorum/last_part last_partition_name`

**Comment by nikitamikhaylov** [comment]
Fixed here #10188.
