### ISSUE TITLE
Sanitizer assert in Stress test(memory)

### ISSUE THREAD

**Issue by nikitamikhaylov** [ClickHouse/ClickHouse#24856]
**Describe the bug**
https://clickhouse-test-reports.s3.yandex.net/24691/f3c81f4c9bd0574f621af7a3efd11871044b09a4/stress_test_(memory).html#fail1

**Error message and/or stacktrace**
```bash
↳ $ grep --text 'Fatal' ./clickhouse-server.log
2021.05.31 19:26:38.021586 [ 62297 ] {} <Fatal> BaseDaemon: ########################################
2021.05.31 19:26:38.057692 [ 62297 ] {} <Fatal> BaseDaemon: (version 21.7.1.7004, build id: C59B50A3C8ED7B340218186F119CFE1C9B441144) (from thread 25808) (query_id: c9c1cc3c-995d-40ca-996e-63d51e2f05a9) Received signal Unknown signal (-3)
2021.05.31 19:26:38.100854 [ 62297 ] {} <Fatal> BaseDaemon: Sanitizer trap.
2021.05.31 19:26:38.118115 [ 62297 ] {} <Fatal> BaseDaemon: Stack trace: 0x9721219 0x2e3325fc 0x961b116 0x95b253c 0x31e0eda2 0x2e62ad97 0x2e62bfbe 0x2e62da83 0x2f92dc46 0x301a7ea8 0x301bc63a 0x301a9d33 0x301cbd94 0x301aa0bd 0x3014ce20 0x300f8e25 0x30122726 0x30137f22 0x30bf2e09 0x30bce9e7 0x30bbb607 0x30bb5865 0x3143283c 0x3142db4d 0x300a723e 0x300a15d2 0x31bcd210 0x31bc7704 0x3400af2d 0x3404d729 0x40a643eb 0x40a65ab9
2021.05.31 19:26:38.870681 [ 62297 ] {} <Fatal> BaseDaemon: 0.1. inlined from ./obj-x86_64-linux-gnu/../src/Common/StackTrace.cpp:304: StackTrace::tryCapture()
2021.05.31 19:26:38.897601 [ 62297 ] {} <Fatal> BaseDaemon: 0. ../src/Common/StackTrace.cpp:265: StackTrace::StackTrace() @ 0x9721219 in /usr/bin/clickhouse
2021.05.31 19:26:40.120750 [ 62297 ] {} <Fatal> BaseDaemon: 1.1. inlined from ./obj-x86_64-linux-gnu/../src/Common/CurrentThread.h:78: DB::CurrentThread::getQueryId()
2021.05.31 19:26:40.132996 [ 62297 ] {} <Fatal> BaseDaemon: 1. ../base/daemon/BaseDaemon.cpp:381: sanitizerDeathCallback() @ 0x2e3325fc in /usr/bin/clickhouse
2021.05.31 19:27:22.980527 [ 62580 ] {} <Fatal> BaseDaemon: ########################################
2021.05.31 19:27:23.185067 [ 62580 ] {} <Fatal> BaseDaemon: (version 21.7.1.7004, build id: C59B50A3C8ED7B340218186F119CFE1C9B441144) (from thread 25808) (query_id: c9c1cc3c-995d-40ca-996e-63d51e2f05a9) Received signal Aborted (6)
2021.05.31 19:27:23.188597 [ 62580 ] {} <Fatal> BaseDaemon:
2021.05.31 19:27:23.189906 [ 62580 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f584a7ec18b 0x7f584a7cb859 0x961c7f7 0x961b171 0x95b253c 0x31e0eda2 0x2e62ad97 0x2e62bfbe 0x2e62da83 0x2f92dc46 0x301a7ea8 0x301bc63a 0x301a9d33 0x301cbd94 0x301aa0bd 0x3014ce20 0x300f8e25 0x30122726 0x30137f22 0x30bf2e09 0x30bce9e7 0x30bbb607 0x30bb5865 0x3143283c 0x3142db4d 0x300a723e 0x300a15d2 0x31bcd210
2021.05.31 19:27:23.195694 [ 62580 ] {} <Fatal> BaseDaemon: 4. raise @ 0x4618b in /usr/lib/x86_64-linux-gnu/libc-2.31.so
2021.05.31 19:27:23.196033 [ 62580 ] {} <Fatal> BaseDaemon: 5. abort @ 0x25859 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
2021.05.31 19:27:47.179640 [ 292 ] {} <Fatal> Application: Child process was terminated by signal 6.
```

```bash
↳ $ addr2line -afiCe ./clickhouse 0x9721219 0x2e3325fc 0x961b116 0x95b253c 0x31e0eda2 0x2e62ad97 0x2e62bfbe 0x2e62da83 0x2f92dc46 0x301a7ea8 0x301bc63a 0x301a9d33 0x301cbd94 0x301aa0bd 0x3014ce20 0x300f8e25 0x30122726 0x30137f22 0x30bf2e09 0x30bce9e7 0x30bbb607 0x30bb5865 0x3143283c 0x3142db4d 0x300a723e 0x300a15d2 0x31bcd210 0x31bc7704 0x3400af2d 0x3404d729 0x40a643eb 0x40a65ab9
0x0000000009721219
StackTrace::StackTrace()
./obj-x86_64-linux-gnu/../src/Common/StackTrace.cpp:304
StackTrace
./obj-x86_64-linux-gnu/../src/Common/StackTrace.cpp:265
0x000000002e3325fc
sanitizerDeathCallback()
./obj-x86_64-linux-gnu/../src/Common/CurrentThread.h:78
sanitizerDeathCallback()
./obj-x86_64-linux-gnu/../base/daemon/BaseDaemon.cpp:381
0x000000000961b116
__sanitizer::Die()
crtstuff.c:?
0x00000000095b253c
__msan_check_mem_is_initialized
??:?
0x0000000031e0eda2
ColumnConst
./obj-x86_64-linux-gnu/../src/Columns/ColumnConst.cpp:44
0x000000002e62ad97
boost::intrusive_ptr<DB::ColumnConst>::intrusive_ptr(DB::ColumnConst*, bool)
./obj-x86_64-linux-gnu/../contrib/boost/boost/smart_ptr/intrusive_ptr.hpp:67
COW<DB::IColumn>::mutable_ptr<DB::ColumnConst>::mutable_ptr(DB::ColumnConst*)
./obj-x86_64-linux-gnu/../src/Common/COW.h:92
??
./obj-x86_64-linux-gnu/../src/Common/COW.h:285
DB::IExecutableFunction::defaultImplementationForConstantArguments(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const
./obj-x86_64-linux-gnu/../src/Functions/IFunction.cpp:168
0x000000002e62bfbe
DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const
??:?
0x000000002e62da83
DB::IExecutableFunction::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const
??:?
0x000000002f92dc46
DB::ActionsDAG::addFunction(std::__1::shared_ptr<DB::IFunctionOverloadResolver> const&, std::__1::vector<DB::ActionsDAG::Node const*, std::__1::allocator<DB::ActionsDAG::Node const*> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)
??:?
0x00000000301a7ea8
DB::ScopeStack::addFunction(std::__1::shared_ptr<DB::IFunctionOverloadResolver> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)
??:?
0x00000000301bc63a
DB::ActionsMatcher::visit(DB::ASTFunction const&, std::__1::shared_ptr<DB::IAST> const&, DB::ActionsMatcher::Data&)
./obj-x86_64-linux-gnu/../contrib/libcxx/include/string:1444
std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()
./obj-x86_64-linux-gnu/../contrib/libcxx/include/string:2218
??
./obj-x86_64-linux-gnu/../src/Interpreters/ActionsVisitor.h:169
DB::ActionsMatcher::visit(DB::ASTFunction const&, std::__1::shared_ptr<DB::IAST> const&, DB::ActionsMatcher::Data&)
./obj-x86_64-linux-gnu/../src/Interpreters/ActionsVisitor.cpp:1057
0x00000000301a9d33
DB::ActionsMatcher::visit(std::__1::shared_ptr<DB::IAST> const&, DB::ActionsMatcher::Data&)
??:?
0x00000000301cbd94
DB::ActionsMatcher::visit(DB::ASTExpressionList&, std::__1::shared_ptr<DB::IAST> const&, DB::ActionsMatcher::Data&)
??:?
0x00000000301aa0bd
DB::ActionsMatcher::visit(std::__1::shared_ptr<DB::IAST> const&, DB::ActionsMatcher::Data&)
./obj-x86_64-linux-gnu/../src/Interpreters/ActionsVisitor.cpp:635
0x000000003014ce20
DB::InDepthNodeVisitor<DB::ActionsMatcher, true, std::__1::shared_ptr<DB::IAST> const>::visit(std::__1::shared_ptr<DB::IAST> const&)
./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2844
??
./obj-x86_64-linux-gnu/../src/Interpreters/InDepthNodeVisitor.h:53
DB::InDepthNodeVisitor<DB::ActionsMatcher, true, std::__1::shared_ptr<DB::IAST> const>::visit(std::__1::shared_ptr<DB::IAST> const&)
./obj-x86_64-linux-gnu/../src/Interpreters/InDepthNodeVisitor.h:43
0x00000000300f8e25
DB::ExpressionAnalyzer::getRootActions(std::__1::shared_ptr<DB::IAST> const&, bool, std::__1::shared_ptr<DB::ActionsDAG>&, bool)
??:?
0x0000000030122726
std::__1::shared_ptr<DB::IAST>::~shared_ptr()
./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:3211
DB::SelectQueryExpressionAnalyzer::appendSelect(DB::ExpressionActionsChain&, bool)
./obj-x86_64-linux-gnu/../src/Interpreters/ExpressionAnalyzer.cpp:1184
0x0000000030137f22
ExpressionAnalysisResult
./obj-x86_64-linux-gnu/../src/Interpreters/ExpressionAnalyzer.cpp:1592
0x0000000030bf2e09
DB::InterpreterSelectQuery::getSampleBlockImpl()
./obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectQuery.cpp:625
0x0000000030bce9e7
operator()
./obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectQuery.cpp:492
0x0000000030bbb607
DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>, std::__1::shared_ptr<DB::IBlockInputStream> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&)
??:?
0x0000000030bb5865
InterpreterSelectQuery
./obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectQuery.cpp:160
0x000000003143283c
DB::InterpreterSelectWithUnionQuery::buildCurrentChildInterpreter(std::__1::shared_ptr<DB::IAST> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&)
./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:1656
std::__1::unique_ptr<DB::InterpreterSelectQuery, std::__1::default_delete<DB::InterpreterSelectQuery> >::~unique_ptr()
./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:1612
DB::InterpreterSelectWithUnionQuery::buildCurrentChildInterpreter(std::__1::shared_ptr<DB::IAST> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&)
./obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectWithUnionQuery.cpp:212
0x000000003142db4d
InterpreterSelectWithUnionQuery
./obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectWithUnionQuery.cpp:134
0x00000000300a723e
std::__1::__vector_base<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >::~__vector_base()
./obj-x86_64-linux-gnu/../contrib/libcxx/include/vector:463
std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >::~vector()
./obj-x86_64-linux-gnu/../contrib/libcxx/include/vector:557
std::__1::__unique_if<DB::InterpreterSelectWithUnionQuery>::__unique_single std::__1::make_unique<DB::InterpreterSelectWithUnionQuery, std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context>&, DB::SelectQueryOptions const&>(std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context>&, DB::SelectQueryOptions const&)
./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2068
0x00000000300a15d2
DB::InterpreterFactory::get(std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&)
??:?
0x0000000031bcd210
DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, bool, DB::ReadBuffer*)
./obj-x86_64-linux-gnu/../src/Interpreters/executeQuery.cpp:531
0x0000000031bc7704
DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, bool)
./obj-x86_64-linux-gnu/../src/Interpreters/executeQuery.cpp:920
0x000000003400af2d
DB::TCPHandler::runImpl()
./obj-x86_64-linux-gnu/../src/Server/TCPHandler.cpp:312
0x000000003404d729
DB::TCPHandler::run()
??:?
0x0000000040a643eb
Poco::Net::TCPServerConnection::start()
./obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServerConnection.cpp:57
0x0000000040a65ab9
Poco::Net::TCPServerDispatcher::run()
./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:1655
std::__1::unique_ptr<Poco::Net::TCPServerConnection, std::__1::default_delete<Poco::Net::TCPServerConnection> >::~unique_ptr()
./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:1612
Poco::Net::TCPServerDispatcher::run()
./obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServerDispatcher.cpp:116
```

**Comment by alexey-milovidov** [comment]
Duplicate #25447.

**Comment by smmsmm1988** [comment]
> **Describe the bug** https://clickhouse-test-reports.s3.yandex.net/24691/f3c81f4c9bd0574f621af7a3efd11871044b09a4/stress_test_(memory).html#fail1
> 
> **Error message and/or stacktrace**
> 
> ```shell
> ↳ $ grep --text 'Fatal' ./clickhouse-server.log
> 2021.05.31 19:26:38.021586 [ 62297 ] {} <Fatal> BaseDaemon: ########################################
> 2021.05.31 19:26:38.057692 [ 62297 ] {} <Fatal> BaseDaemon: (version 21.7.1.7004, build id: C59B50A3C8ED7B340218186F119CFE1C9B441144) (from thread 25808) (query_id: c9c1cc3c-995d-40ca-996e-63d51e2f05a9) Received signal Unknown signal (-3)
> 2021.05.31 19:26:38.100854 [ 62297 ] {} <Fatal> BaseDaemon: Sanitizer trap.
> 2021.05.31 19:26:38.118115 [ 62297 ] {} <Fatal> BaseDaemon: Stack trace: 0x9721219 0x2e3325fc 0x961b116 0x95b253c 0x31e0eda2 0x2e62ad97 0x2e62bfbe 0x2e62da83 0x2f92dc46 0x301a7ea8 0x301bc63a 0x301a9d33 0x301cbd94 0x301aa0bd 0x3014ce20 0x300f8e25 0x30122726 0x30137f22 0x30bf2e09 0x30bce9e7 0x30bbb607 0x30bb5865 0x3143283c 0x3142db4d 0x300a723e 0x300a15d2 0x31bcd210 0x31bc7704 0x3400af2d 0x3404d729 0x40a643eb 0x40a65ab9
> 2021.05.31 19:26:38.870681 [ 62297 ] {} <Fatal> BaseDaemon: 0.1. inlined from ./obj-x86_64-linux-gnu/../src/Common/StackTrace.cpp:304: StackTrace::tryCapture()
> 2021.05.31 19:26:38.897601 [ 62297 ] {} <Fatal> BaseDaemon: 0. ../src/Common/StackTrace.cpp:265: StackTrace::StackTrace() @ 0x9721219 in /usr/bin/clickhouse
> 2021.05.31 19:26:40.120750 [ 62297 ] {} <Fatal> BaseDaemon: 1.1. inlined from ./obj-x86_64-linux-gnu/../src/Common/CurrentThread.h:78: DB::CurrentThread::getQueryId()
> 2021.05.31 19:26:40.132996 [ 62297 ] {} <Fatal> BaseDaemon: 1. ../base/daemon/BaseDaemon.cpp:381: sanitizerDeathCallback() @ 0x2e3325fc in /usr/bin/clickhouse
> 2021.05.31 19:27:22.980527 [ 62580 ] {} <Fatal> BaseDaemon: ########################################
> 2021.05.31 19:27:23.185067 [ 62580 ] {} <Fatal> BaseDaemon: (version 21.7.1.7004, build id: C59B50A3C8ED7B340218186F119CFE1C9B441144) (from thread 25808) (query_id: c9c1cc3c-995d-40ca-996e-63d51e2f05a9) Received signal Aborted (6)
> 2021.05.31 19:27:23.188597 [ 62580 ] {} <Fatal> BaseDaemon:
> 2021.05.31 19:27:23.189906 [ 62580 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f584a7ec18b 0x7f584a7cb859 0x961c7f7 0x961b171 0x95b253c 0x31e0eda2 0x2e62ad97 0x2e62bfbe 0x2e62da83 0x2f92dc46 0x301a7ea8 0x301bc63a 0x301a9d33 0x301cbd94 0x301aa0bd 0x3014ce20 0x300f8e25 0x30122726 0x30137f22 0x30bf2e09 0x30bce9e7 0x30bbb607 0x30bb5865 0x3143283c 0x3142db4d 0x300a723e 0x300a15d2 0x31bcd210
> 2021.05.31 19:27:23.195694 [ 62580 ] {} <Fatal> BaseDaemon: 4. raise @ 0x4618b in /usr/lib/x86_64-linux-gnu/libc-2.31.so
> 2021.05.31 19:27:23.196033 [ 62580 ] {} <Fatal> BaseDaemon: 5. abort @ 0x25859 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
> 2021.05.31 19:27:47.179640 [ 292 ] {} <Fatal> Application: Child process was terminated by signal 6.
> ```
> 
> ```shell
> ↳ $ addr2line -afiCe ./clickhouse 0x9721219 0x2e3325fc 0x961b116 0x95b253c 0x31e0eda2 0x2e62ad97 0x2e62bfbe 0x2e62da83 0x2f92dc46 0x301a7ea8 0x301bc63a 0x301a9d33 0x301cbd94 0x301aa0bd 0x3014ce20 0x300f8e25 0x30122726 0x30137f22 0x30bf2e09 0x30bce9e7 0x30bbb607 0x30bb5865 0x3143283c 0x3142db4d 0x300a723e 0x300a15d2 0x31bcd210 0x31bc7704 0x3400af2d 0x3404d729 0x40a643eb 0x40a65ab9
> 0x0000000009721219
> StackTrace::StackTrace()
> ./obj-x86_64-linux-gnu/../src/Common/StackTrace.cpp:304
> StackTrace
> ./obj-x86_64-linux-gnu/../src/Common/StackTrace.cpp:265
> 0x000000002e3325fc
> sanitizerDeathCallback()
> ./obj-x86_64-linux-gnu/../src/Common/CurrentThread.h:78
> sanitizerDeathCallback()
> ./obj-x86_64-linux-gnu/../base/daemon/BaseDaemon.cpp:381
> 0x000000000961b116
> __sanitizer::Die()
> crtstuff.c:?
> 0x00000000095b253c
> __msan_check_mem_is_initialized
> ??:?
> 0x0000000031e0eda2
> ColumnConst
> ./obj-x86_64-linux-gnu/../src/Columns/ColumnConst.cpp:44
> 0x000000002e62ad97
> boost::intrusive_ptr<DB::ColumnConst>::intrusive_ptr(DB::ColumnConst*, bool)
> ./obj-x86_64-linux-gnu/../contrib/boost/boost/smart_ptr/intrusive_ptr.hpp:67
> COW<DB::IColumn>::mutable_ptr<DB::ColumnConst>::mutable_ptr(DB::ColumnConst*)
> ./obj-x86_64-linux-gnu/../src/Common/COW.h:92
> ??
> ./obj-x86_64-linux-gnu/../src/Common/COW.h:285
> DB::IExecutableFunction::defaultImplementationForConstantArguments(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const
> ./obj-x86_64-linux-gnu/../src/Functions/IFunction.cpp:168
> 0x000000002e62bfbe
> DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const
> ??:?
> 0x000000002e62da83
> DB::IExecutableFunction::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const
> ??:?
> 0x000000002f92dc46
> DB::ActionsDAG::addFunction(std::__1::shared_ptr<DB::IFunctionOverloadResolver> const&, std::__1::vector<DB::ActionsDAG::Node const*, std::__1::allocator<DB::ActionsDAG::Node const*> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)
> ??:?
> 0x00000000301a7ea8
> DB::ScopeStack::addFunction(std::__1::shared_ptr<DB::IFunctionOverloadResolver> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)
> ??:?
> 0x00000000301bc63a
> DB::ActionsMatcher::visit(DB::ASTFunction const&, std::__1::shared_ptr<DB::IAST> const&, DB::ActionsMatcher::Data&)
> ./obj-x86_64-linux-gnu/../contrib/libcxx/include/string:1444
> std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()
> ./obj-x86_64-linux-gnu/../contrib/libcxx/include/string:2218
> ??
> ./obj-x86_64-linux-gnu/../src/Interpreters/ActionsVisitor.h:169
> DB::ActionsMatcher::visit(DB::ASTFunction const&, std::__1::shared_ptr<DB::IAST> const&, DB::ActionsMatcher::Data&)
> ./obj-x86_64-linux-gnu/../src/Interpreters/ActionsVisitor.cpp:1057
> 0x00000000301a9d33
> DB::ActionsMatcher::visit(std::__1::shared_ptr<DB::IAST> const&, DB::ActionsMatcher::Data&)
> ??:?
> 0x00000000301cbd94
> DB::ActionsMatcher::visit(DB::ASTExpressionList&, std::__1::shared_ptr<DB::IAST> const&, DB::ActionsMatcher::Data&)
> ??:?
> 0x00000000301aa0bd
> DB::ActionsMatcher::visit(std::__1::shared_ptr<DB::IAST> const&, DB::ActionsMatcher::Data&)
> ./obj-x86_64-linux-gnu/../src/Interpreters/ActionsVisitor.cpp:635
> 0x000000003014ce20
> DB::InDepthNodeVisitor<DB::ActionsMatcher, true, std::__1::shared_ptr<DB::IAST> const>::visit(std::__1::shared_ptr<DB::IAST> const&)
> ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2844
> ??
> ./obj-x86_64-linux-gnu/../src/Interpreters/InDepthNodeVisitor.h:53
> DB::InDepthNodeVisitor<DB::ActionsMatcher, true, std::__1::shared_ptr<DB::IAST> const>::visit(std::__1::shared_ptr<DB::IAST> const&)
> ./obj-x86_64-linux-gnu/../src/Interpreters/InDepthNodeVisitor.h:43
> 0x00000000300f8e25
> DB::ExpressionAnalyzer::getRootActions(std::__1::shared_ptr<DB::IAST> const&, bool, std::__1::shared_ptr<DB::ActionsDAG>&, bool)
> ??:?
> 0x0000000030122726
> std::__1::shared_ptr<DB::IAST>::~shared_ptr()
> ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:3211
> DB::SelectQueryExpressionAnalyzer::appendSelect(DB::ExpressionActionsChain&, bool)
> ./obj-x86_64-linux-gnu/../src/Interpreters/ExpressionAnalyzer.cpp:1184
> 0x0000000030137f22
> ExpressionAnalysisResult
> ./obj-x86_64-linux-gnu/../src/Interpreters/ExpressionAnalyzer.cpp:1592
> 0x0000000030bf2e09
> DB::InterpreterSelectQuery::getSampleBlockImpl()
> ./obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectQuery.cpp:625
> 0x0000000030bce9e7
> operator()
> ./obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectQuery.cpp:492
> 0x0000000030bbb607
> DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>, std::__1::shared_ptr<DB::IBlockInputStream> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&)
> ??:?
> 0x0000000030bb5865
> InterpreterSelectQuery
> ./obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectQuery.cpp:160
> 0x000000003143283c
> DB::InterpreterSelectWithUnionQuery::buildCurrentChildInterpreter(std::__1::shared_ptr<DB::IAST> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&)
> ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:1656
> std::__1::unique_ptr<DB::InterpreterSelectQuery, std::__1::default_delete<DB::InterpreterSelectQuery> >::~unique_ptr()
> ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:1612
> DB::InterpreterSelectWithUnionQuery::buildCurrentChildInterpreter(std::__1::shared_ptr<DB::IAST> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&)
> ./obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectWithUnionQuery.cpp:212
> 0x000000003142db4d
> InterpreterSelectWithUnionQuery
> ./obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectWithUnionQuery.cpp:134
> 0x00000000300a723e
> std::__1::__vector_base<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >::~__vector_base()
> ./obj-x86_64-linux-gnu/../contrib/libcxx/include/vector:463
> std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >::~vector()
> ./obj-x86_64-linux-gnu/../contrib/libcxx/include/vector:557
> std::__1::__unique_if<DB::InterpreterSelectWithUnionQuery>::__unique_single std::__1::make_unique<DB::InterpreterSelectWithUnionQuery, std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context>&, DB::SelectQueryOptions const&>(std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context>&, DB::SelectQueryOptions const&)
> ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2068
> 0x00000000300a15d2
> DB::InterpreterFactory::get(std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&)
> ??:?
> 0x0000000031bcd210
> DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, bool, DB::ReadBuffer*)
> ./obj-x86_64-linux-gnu/../src/Interpreters/executeQuery.cpp:531
> 0x0000000031bc7704
> DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, bool)
> ./obj-x86_64-linux-gnu/../src/Interpreters/executeQuery.cpp:920
> 0x000000003400af2d
> DB::TCPHandler::runImpl()
> ./obj-x86_64-linux-gnu/../src/Server/TCPHandler.cpp:312
> 0x000000003404d729
> DB::TCPHandler::run()
> ??:?
> 0x0000000040a643eb
> Poco::Net::TCPServerConnection::start()
> ./obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServerConnection.cpp:57
> 0x0000000040a65ab9
> Poco::Net::TCPServerDispatcher::run()
> ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:1655
> std::__1::unique_ptr<Poco::Net::TCPServerConnection, std::__1::default_delete<Poco::Net::TCPServerConnection> >::~unique_ptr()
> ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:1612
> Poco::Net::TCPServerDispatcher::run()
> ./obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServerDispatcher.cpp:116
> ```

hello, I also encountered such issue (Received signal Unknown signal (-3)) yesterday. What's the reason for this issue? Is it the bug in the kernel?
