### ISSUE TITLE
Decimal overflow

### ISSUE THREAD

**Issue by skytian** [ClickHouse/ClickHouse#24868]
You have to provide the following information whenever possible.

When query a decimal like this:

`SELECT toDecimal32(-8388609.54, 2);`

the result is as below :
`-8388609.53`

![image](https://user-images.githubusercontent.com/6102578/120444067-d97ac580-c3b9-11eb-9be2-06747adc6a1d.png)

----

![image](https://user-images.githubusercontent.com/6102578/120444102-e4cdf100-c3b9-11eb-8285-5f8b7d09efd1.png)
----
![image](https://user-images.githubusercontent.com/6102578/120444505-43936a80-c3ba-11eb-9919-fcbb293358e1.png)

**Comment by alexey-milovidov** [comment]
In your query
`SELECT toDecimal32(-8388609.54, 2);`
you are writing floating point number `-8388609.54` that have type Float64, then converting it to Decimal.

Correct way to create Decimal number is:
`SELECT toDecimal32('-8388609.54', 2);`
