### ISSUE TITLE
ReplicatedReplacingMergeTree ERROR，after ck restart

### ISSUE THREAD

**Issue by mythmoon** [ClickHouse/ClickHouse#24864]
ReplicatedReplacingMergeTree ERROR  after  ck restart;

Application: Shut down storages.
2021.06.02 03:26:37.072609 [ 56 ] {} <Debug> Application: Destroyed global context.
2021.06.02 03:26:37.105394 [ 56 ] {} <Error> Application: DB::Exception: The local set of parts of table RTDC.history_replace doesn't look like the set of parts in ZooKeeper: 18.10 million rows of 34.31 million total rows in filesystem are suspicious. There are 1603 unexpected parts with 18096541 rows (234 of them is not just-written with 14646822 rows), 0 missing parts (with 0 blocks).: Cannot attach table `RTDC`.`history_replace` from metadata file /var/lib/clickhouse/metadata/RTDC/history_replace.sql from queryATTACH TABLE RTDC.history_replace (`itemid` UInt64, `clock` UInt64, `ns` UInt64, `clockns` UInt64, `count` String, `value` String, `type` UInt8) ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{shard}/RTDC/history_replace', '{replica}', clockns) PARTITION BY toYYYYMMDD(FROM_UNIXTIME(clock)) PRIMARY KEY itemid ORDER BY itemid SETTINGS index_granularity = 8192, merge_with_ttl_timeout = 5: while loading database `RTDC` from path /var/lib/clickhouse/metadata/RTDC
2021.06.02 03:26:37.105524 [ 56 ] {} <Information> Application: shutting down
2021.06.02 03:26:37.105559 [ 56 ] {} <Debug> Application: Uninitializing subsystem: Logging Subsystem
2021.06.02 03:26:37.105859 [ 57 ] {} <Information> BaseDaemon: Stop SignalListener thread
2021.06.02 03:26:37.170576 [ 55 ] {} <Information> Application: Child process exited normally with cod

**Comment by mythmoon** [comment]
then mv history_replace.sql  and data  ,restart OK .
then  create history_replace, ERROR again!!!

**Comment by mythmoon** [comment]
then mv history_replace.sql  and data  ,restart OK .
then  create history_replace, ERROR again!!!

**Comment by den-crane** [comment]
>then create history_replace, ERROR again!!!

How you managed to create history_replace? Because this path already  exists `'/clickhouse/tables/{shard}/RTDC/history_replace', ` ?
