### ISSUE TITLE
How to avoid duplicate data into diff shards when shards changed?

### ISSUE THREAD

**Issue by maskshell** [ClickHouse/ClickHouse#24876]
I am using `ReplicatedReplacingMergeTree` engine and would like to insert data through `Distributed` table.
At a later stage, shards may be added from time to time.
I want to prevent inserting duplicate data in different shard - as this would not be automatically de-duplicated.

Well, the [documentation](https://clickhouse.tech/docs/en/engines/table-engines/special/distributed/) mentions that:
> To select the shard that a row of data is sent to, the sharding expression is analyzed, and its remainder is taken from dividing it by the total weight of the shards. The row is sent to the shard that corresponds to the half-interval of the remainders from prev_weight to prev_weights + weight, where prev_weights is the total weight of the shards with the smallest number, and weight is the weight of this shard.

So, that means that if I change the weight of the shards, or add shards, then when I need to insert duplicate data later, they are likely to be distributed among different shards.

So my question is:
How do I design the sharding key for distributed tables to avoid inserting duplicate data into different shards?
Or, how to use clickhouse to prevent that?

**Comment by den-crane** [comment]
>How do I design the sharding key for distributed tables to avoid inserting duplicate data into different shards?

It's impossible. You can mitigate the issue using consistent hash functions in the sharding key like `jumpConsistentHash`

https://clickhouse.tech/docs/en/sql-reference/functions/hash-functions/#jumpconsistenthash

https://en.wikipedia.org/wiki/Consistent_hashing

**Comment by den-crane** [comment]
>So, how is this problem generally handled now?

No solution. Only the reinsertion all data using clickhouse-copier or other tools.

**Comment by maskshell** [comment]
I was just looking through the CHANGELOG and found an interesting new feature.

One of the new features in 21.3 (LTS), "[Add setting insert_shard_id to support insert data into specific shard from distributed table.](https://github.com/ClickHouse/ClickHouse/pull/19961)"

For example.
`INSERT INTO dist_table .... settings insert_shard_id = 1`

But currently it only supports numeric values and not expressions.
If expressions are supported, does this basically solve the problem? 

For example:
`INSERT INTO dist_table .... settings insert_shard_id = (jumpConsistentHash(intHash64(id), 8) + 1)`

**Comment by maskshell** [comment]
> It would be better to do it via virtual column instead of a setting. Currently, _shard_num virtual column is returned in SELECTs from distributed tables, so the natural extension is to use it in INSERTs in order to write to a specific shard.

> But we don't have support for INSERTing of virtual columns.
