### ISSUE TITLE
Optimize bitmap SQL

### ISSUE THREAD

**Issue by onine007** [ClickHouse/ClickHouse#24873]
How to optimize this SQL:
```sql
SELECT
    toString(event_dt) AS dt,
    '' AS by_field,
    toFloat64OrZero(toString(groupBitmap(events_user_id))) AS measure
FROM 
(
    SELECT
        event_dt,
        events.user_id AS events_user_id
    FROM 
    (
        SELECT
            event_dt,
            user_id
        FROM events
        WHERE ((events.event_dt >= 20210416) AND (events.event_dt <= 20210515) AND (events.client_id = 1) AND (events.event_id = 45)) AND (toInt32OrNull(events.event_attr1) IN (53))
    ) AS events
    INNER JOIN 
    (
        SELECT
            dt AS event_dt,
            arrayJoin(bitmapToArray(measure)) AS user_id
        FROM crowd_bitmap_result
        PREWHERE (crowd_id = 2564) AND (status = 1) AND (dt >= 20210416) AND (dt <= 20210515)
    ) AS crowds USING (user_id, event_dt)
)
GROUP BY event_dt
ORDER BY
    event_dt ASC,
    measure DESC
LIMIT 200 BY dt;
```
when bitmap:measure Cardinality is  large  , it takes more memory  then , oom 

if any way to optimize it ?

**Comment by Nicemo** [comment]
Is events_user_id range from zero? In my case , 500 million ids split to 500 shards to reduce the taken memory。

**Comment by RashidSh1980** [comment]
Dear onine007,
Could you check pls this one and give your response

SELECT
    toString(event_dt) AS dt,
    '' AS by_field,
    toFloat64OrZero(toString(groupBitmap(events_user_id))) AS measure
FROM 
(
    SELECT
        event_dt,
        events.user_id AS events_user_id
    FROM 
    (
        SELECT
            event_dt,
            user_id
        FROM events
        WHERE ((events.event_dt >= 20210416) AND (events.event_dt <= 20210515) AND (events.client_id = 1) AND (events.event_id = 45)) AND (toInt32OrNull(events.event_attr1) IN (53))
         AND (event_dt, user_id) in (
                                      SELECT
                                           dt AS event_dt,
                                           arrayJoin(bitmapToArray(measure)) AS user_id
                                      FROM crowd_bitmap_result
                                      PREWHERE (crowd_id = 2564) AND (status = 1) AND (dt >= 20210416) AND (dt <= 20210515)
                                     )
    ) AS events
 
)
GROUP BY event_dt
ORDER BY
    event_dt ASC,
    measure DESC
LIMIT 200 BY dt;
