### ISSUE TITLE
Confusion about arithmetic

### ISSUE THREAD

**Issue by spihiker** [ClickHouse/ClickHouse#24871]
SELECT
    version(),
    -0.34 * 100 AS num1,
    -0.56 * 100 AS num2

Query id: 052ba8bf-2b0b-47c8-841b-de0fb352f553

Row 1:
──────
version(): 21.3.12.2
num1:      -34
num2:      -56.00000000000001

Why is num2 not 56? 
Thans for your help.

**Comment by alexey-milovidov** [comment]
https://stackoverflow.com/questions/588004/is-floating-point-math-broken

**Comment by spihiker** [comment]
Thank you very much.
