### ISSUE TITLE
Replicated database: check metadata consistency on server startup

### ISSUE THREAD

**Issue by Blackmorse** [ClickHouse/ClickHouse#24880]
**The problem**
Suppose we have a database (e.g. _db_) with Engine = Replicated  on the cluster. Let's make manually delete on one of the hosts
`rm -R /var/lib/clickhouse/store/<db_uuid_prefix>/<db_uuid>/*`
(or even better)
`rm -R /var/lib/clickhouse/store`
After restarting this host there are no tables restored at _db_

**Feature**
Comparing to existing replication mechanizm of ReplicatedMergeTrees:
_ReplicatedMergeTree_ has data, and this data represented as a _parts_. When manually deleting parts 
`rm -r -R /var/lib/clickhouse/<table_uuid_prefix>/<table_uuid>/*`
after a while Clickhouse will detect missing parts and restore them from the replica.

In case of Replicated database, table's sql-files can be treated as database data, and similar replication mechanizm expected

This makes process of restoring the lost data/metadata on the replicas almost fully-automated

**Use case**
We are mounting _metadata_ folder to separate disk (something very reliable, like RAIDs). E.g. when disk with _store/_ is corrupted, we have to manually copy metadata from replica and restore symlinks at _metadata/_ folder,  (for _Atomic_ databases). 
In case of using _Replicated_ Database with improvements described above, when disk with  _store/_  is corrupted, data and metadata will be restored automatically without manual intervention

**Comment by tavplubix** [comment]
`Replicated` engine restores tables automatically if replica is staled. New replicas create all tables automatically too. If metadata were removed from disk for some reason, you can drop database and create it again to restore tables.

But we should check metadata consistency on server startup.

**Comment by Blackmorse** [comment]
@tavplubix 

Steps to reproduce:
1. Create **Replicated** database on cluster, create tables inside it
2. Stop one instance 
3. remove contents of the _store/_ folder
4. Start the instance again
5. Recreate **Replicated** database (`drop database` ... and then `create database`)
Result: no tables restored on this instance
Checked on 21.5.6.6 version

_________________

Also my point was about _automatic_ recovery.
Again, in case of loosing parts for Replicated table, you do not need to recreate table, Clickhouse will restore them automatically from the replicas.
Would be great to have the same behaviour for the **Replicated** database, and do not recreate it in case of loosing tables metadata.
