### ISSUE TITLE
Least privileges for `GRANT POSTGRES ON ...`

### ISSUE THREAD

**Issue by serpa-dystematic** [ClickHouse/ClickHouse#24884]
I have a user that needs to create tables with `postgres` engine in a database.

That user is not an admin, so I want to give him the least privileges possible, but I could only do it with this command:
```
GRANT POSTGRES on *.* to <USER>
```

If I tried to limit the database, it would throw an error:
```
Exception on client:
Code: 509. DB::Exception: POSTGRES cannot be granted on the database level
```

What's the best approach for this?

**Comment by vitlibar** [comment]
`GRANT POSTGRES` allows to call the table function `postgresql()` and also it allows to create tables with the `POSTGRES` engine. However to create a table it's also necessary to have the `CREATE TABLE` privilege granted. So to create a user which is allowed to create tables in a specific database and also to use the POSTGRES engine the following commands can be used:

```
GRANT POSTGRES ON *.* TO username;
GRANT CREATE TABLE ON dbname.* TO username;
```
