### ISSUE TITLE
Delete the clickhouse ReplicatedMergeTree engine table, and rebuild the table with zk bug

### ISSUE THREAD

**Issue by mjh568412187** [ClickHouse/ClickHouse#24883]
You have to provide the following information whenever possible.

**Describe the bug**

A clear and concise description of what works not as it is supposed to.

**Does it reproduce on recent release?**

[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

**Enable crash reporting**

If possible, change "enabled" to true in "send_crash_reports" section in `config.xml`:

```
<send_crash_reports>
        <!-- Changing <enabled> to true allows sending crash reports to -->
        <!-- the ClickHouse core developers team via Sentry https://sentry.io -->
        <enabled>false</enabled>
```

**How to reproduce**

* Which ClickHouse server version to use
* Which interface to use, if matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

**Expected behavior**

**Error message and/or stacktrace**

**Additional context**

---
first step
<img width="1349" alt="image" src="https://user-images.githubusercontent.com/26197792/120497337-e4048180-c3f0-11eb-94a7-02a8edc7a0d8.png">

Second step
Recreate the same table
<img width="1499" alt="image" src="https://user-images.githubusercontent.com/26197792/120497527-10200280-c3f1-11eb-81c8-74e470c02498.png">

third step
<img width="1451" alt="image" src="https://user-images.githubusercontent.com/26197792/120497730-3cd41a00-c3f1-11eb-8a20-6cf0b3a2294d.png">

The path of zk is not deleted

**Comment by filimonov** [comment]
That is related to Atomic database behaviour.

See https://kb.altinity.com/engines/altinity-kb-atomic-database-engine#q-i-cannot-reuse-zookeeper-path-after-dropping-the-table
