### ISSUE TITLE
how to join ip range?

### ISSUE THREAD

**Issue by trollhe** [ClickHouse/ClickHouse#24895]
hi,team

   i want join two table on iprange,but not support this sql,how can do it?

```

CREATE TABLE if not exists default.tb2
(
    `ip` String,
    `country` String
)
ENGINE = MergeTree()
order by ip
partition by country
SETTINGS index_granularity = 25;

CREATE TABLE if not exists  default.tb1
(
    `ip` String
)
ENGINE = MergeTree()
order by ip
SETTINGS index_granularity = 3000;


insert into default.tb1(ip)
select '102.0.1.5';


insert into default.tb2(ip,country)
select '102.0.1.0/24','KEN';

``

`select ip from default.tb1;`

```
ip       |
---------+
102.0.1.5|
```

`select ip,country from default.tb2;`

```
ip          |country|
------------+-------+
102.0.1.0/24|KEN    |
```

  i want  join tb1 and tb2 on ip,by `select tb1.ip,tb2.country from tb1 join tb2 on isIPAddressInRange(tb1.ip, tb2.ip)=1;`,but throwing error:

```
[403]: ClickHouse exception, code: 403, host: 192.168.5.212, port: 8123; Code: 403, e.displayText() = DB::Exception: Invalid columns in JOIN ON section. Columns ip and tb2.ip are from different tables.: While processing isIPAddressInRange(ip, tb2.ip) = 1 (version 21.4.6.55 (official build))¶
```

how can to join by data range , e.g.  func(tb1.ip,tb2.iprange) ,or on  tb1.ip between tb2.ip_start and  tb2.ip_end?

**Comment by UnamedRus** [comment]
You can look into ip_trie dictionary

https://clickhouse.tech/docs/en/sql-reference/dictionaries/external-dictionaries/external-dicts-dict-layout/#ip-trie

**Comment by trollhe** [comment]
> You can look into ip_trie dictionary
> 
> https://clickhouse.tech/docs/en/sql-reference/dictionaries/external-dictionaries/external-dicts-dict-layout/#ip-trie

tks
