### ISSUE TITLE
aiohttp client causes `Socket is not connected` spam in error log after update to clichouse-server LTS 21.3

### ISSUE THREAD

**Issue by niya3** [ClickHouse/ClickHouse#24899]
**Describe the bug**

Clickhouse-server error log contains too many stacktraces with the `Net Exception: Socket is not connected` message (at lease 1 per each 5 requests, SELECT or INSERT - doesn't matter) when using Python aiohttp client. It makes impossible to find real important error messages in the log file even on low-traffic installation.

**Does it reproduce on recent release?**

Yes, with debian package for 21.3.12.2 LTS version

**How to reproduce**

1. Install the LTS version 21.3.12.2 of `clickhouse-server` debian package to VM with Debian 10 Buster and run it with default config:
```bash
echo "deb http://repo.yandex.ru/clickhouse/deb/stable/ main/" > /etc/apt/sources.list.d/clickhouse.list
apt update -q
apt install clickhouse-server=21.3.12.2 clickhouse-common-static=21.3.12.2
systemctl start clickhouse-server
tail -f /var/log/clickhouse-server/clickhouse-server.err.log
```

2. Create a tiny python client and run in:
```bash
apt update -q
apt install python3 python3-pip
pip3 install aiohttp==3.7.4.post0 asyncio==3.4.3 # the latest versions

cat << EOF > ./get.py
import asyncio
import aiohttp

async def main():
    async with aiohttp.ClientSession() as s:
        async with s.get('http://localhost:8123') as r:
            pass

asyncio.run(main())
EOF

watch python3 ./get.py
```

**Expected behavior**

No new messages in `/var/log/clickhouse-server/clickhouse-server.err.log` file

**Current behavior**

At lease 1 of each 5 request causes a new error message in  `/var/log/clickhouse-server/clickhouse-server.err.log` file

```c++
2021.06.03 10:08:11.259984 [ 110107 ] {} <Error> ServerErrorHandler: Poco::Exception. Code: 1000, e.code() = 107, e.displayText() = Net Exception: Socket is not connected, Stack trace (when copying this message, always include the lines below):

0. Poco::Net::SocketImpl::error(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x11d0c84e in /usr/bin/clickhouse
1. Poco::Net::SocketImpl::peerAddress() @ 0x11d0eac6 in /usr/bin/clickhouse
2. DB::HTTPServerRequest::HTTPServerRequest(DB::Context const&, DB::HTTPServerResponse&, Poco::Net::HTTPServerSession&) @ 0xf669c64 in /usr/bin/clickhouse
3. DB::HTTPServerConnection::run() @ 0xf668ad4 in /usr/bin/clickhouse
4. Poco::Net::TCPServerConnection::start() @ 0x11d138af in /usr/bin/clickhouse
5. Poco::Net::TCPServerDispatcher::run() @ 0x11d152c1 in /usr/bin/clickhouse
6. Poco::PooledThread::run() @ 0x11e4b9e9 in /usr/bin/clickhouse
7. Poco::ThreadImpl::runnableEntry(void*) @ 0x11e4784a in /usr/bin/clickhouse
8. start_thread @ 0x7fa3 in /usr/lib/x86_64-linux-gnu/libpthread-2.28.so
9. clone @ 0xf94cf in /usr/lib/x86_64-linux-gnu/libc-2.28.so
 (version 21.3.12.2 (official build))
```

**Additional context**

1. can't reproduce this bug at clickhouse-server LTS version **19.14.8.9** at all
1. can't reproduce bug using **docker**
```bash
docker run --rm -d -p 8123:8123 -name ch yandex/clickhouse-server:21.3
docker exec -ti ch tail -f /var/log/clickhouse-server/clickhouse-server.err.log
# no error messages in log file
```
3. error messages dissappear after switching to `httpx` client:

```bash
pip install httpx==0.18.1 #the latest version
cat << EOF > ./get_httpx.py
import asyncio
import httpx

async def main():
    async with httpx.AsyncClient() as s:
        r = await s.get('http://localhost:8123')

asyncio.run(main())
EOF

watch python3 ./get_httpx.py
# no error messages in log file
```
4. in clickhouse-server LTS version **20.8.18.32** aiohttp client requests cause `Connection reset by peer` messages:

```c++
2021.06.03 10:41:08.653341 [ 111869 ] {} <Error> ServerErrorHandler: Poco::Exception. Code: 1000, e.code() = 104, e.displayText() = Connection reset by peer, Stack trace (when copying this message, always include the lines below):

0. Poco::IOException::IOException(int) @ 0x18ce275f in /usr/bin/clickhouse
1. Poco::Net::ConnectionResetException::ConnectionResetException(int) @ 0x18bd39bd in /usr/bin/clickhouse
2. ? @ 0x18bf07ca in /usr/bin/clickhouse
3. Poco::Net::SocketImpl::receiveBytes(void*, int, int) @ 0x18beee60 in /usr/bin/clickhouse
4. Poco::Net::HTTPSession::receive(char*, int) @ 0x18bbd1d8 in /usr/bin/clickhouse
5. Poco::Net::HTTPSession::get() @ 0x18bbd243 in /usr/bin/clickhouse
6. Poco::Net::HTTPHeaderStreamBuf::readFromDevice(char*, long) @ 0x18bb1dfa in /usr/bin/clickhouse
7. Poco::BasicBufferedStreamBuf<char, std::__1::char_traits<char>, Poco::Net::HTTPBufferAllocator>::underflow() @ 0x18bae758 in /usr/bin/clickhouse
8. std::__1::basic_streambuf<char, std::__1::char_traits<char> >::uflow() @ 0x19c5af0e in ?
9. std::__1::basic_istream<char, std::__1::char_traits<char> >::get() @ 0x19c62506 in ?
10. Poco::Net::HTTPRequest::read(std::__1::basic_istream<char, std::__1::char_traits<char> >&) @ 0x18bb4ed7 in /usr/bin/clickhouse
11. Poco::Net::HTTPServerRequestImpl::HTTPServerRequestImpl(Poco::Net::HTTPServerResponseImpl&, Poco::Net::HTTPServerSession&, Poco::Net::HTTPServerParams*) @ 0x18bbb305 in /usr/bin/clickhouse
12. Poco::Net::HTTPServerConnection::run() @ 0x18bb9ccc in /usr/bin/clickhouse
13. Poco::Net::TCPServerConnection::start() @ 0x18bf7e5b in /usr/bin/clickhouse
14. Poco::Net::TCPServerDispatcher::run() @ 0x18bf83e8 in /usr/bin/clickhouse
15. Poco::PooledThread::run() @ 0x18d76ed6 in /usr/bin/clickhouse
16. Poco::ThreadImpl::runnableEntry(void*) @ 0x18d722d0 in /usr/bin/clickhouse
17. start_thread @ 0x7fa3 in /usr/lib/x86_64-linux-gnu/libpthread-2.28.so
18. __clone @ 0xf94cf in /usr/lib/x86_64-linux-gnu/libc-2.28.so
 (version 20.8.18.32 (official build))
```

**Comment by filimonov** [comment]
Reproduces, 21.5.6.6.

**Comment by alexey-milovidov** [comment]
The message looks correct.
We can adjust it by changing to warning or removing stack trace.

**Comment by niya3** [comment]
@alexey-milovidov yep, the message itself may seem correct, but there is so many questions that it may indicate some subtle bug :)

1. What is the reason of this message?
2. How should I change the code using an `aiohttp` client to get rid of messages?
3. Why doesn't it reproduce with the similar code using an `httpx` client?
4. Why doesn't it reproduce with docker images?
5. Why doesn't it reproduce with 19.14 LTS? Why message has changed from 20.8 LTS to 21.3 LTS?

**Comment by filimonov** [comment]
'Problematic' stream - finishes with tcp RST:
![Screenshot from 2021-06-07 14-39-30](https://user-images.githubusercontent.com/1549571/121018070-49b08f00-c79e-11eb-9dee-158b33e32243.png)

'Good' stream - finishes with tcp FIN
![Screenshot from 2021-06-07 14-39-39](https://user-images.githubusercontent.com/1549571/121018111-5cc35f00-c79e-11eb-9955-73278d9568c7.png)

**Comment by filimonov** [comment]
So I think the python app is closed before you get the response from the server, and OS kills the connection with RST. 

The workaround is to wait for a server response :) Like `await resp.text()` or `await session.close()` or similar.

P.S. Why do you ask clickhouse questions if you are not interested in answers? :)

**Comment by niya3** [comment]
@filimonov thanks a lot! It was my fault, I didn't check the code hard enough!

My code uses https://github.com/maximdanilchenko/aiochclient async-client and when I added `await resp.text()` call to [connection health check code](https://github.com/maximdanilchenko/aiochclient/blob/5954094aecc63870f276fbcec429e1d8efd869c3/aiochclient/client.py#L115) it became mostly (but not quite) OK. However, it works for me now.

And the answer to your last question: sometimes we don't care about the response's body, but we interested in its status.

**Comment by filimonov** [comment]
Relates to https://github.com/ClickHouse/ClickHouse/issues/23858
