### ISSUE TITLE
import avro file from S3 into ClickHouse

### ISSUE THREAD

**Issue by stasDomb** [ClickHouse/ClickHouse#24903]
Hello. I  try to get the info from avro file, located on S3. But I couldn't.
I created table with s3 integration engine

> │ CREATE TABLE s3_facts
> (
>     `column1` UUID,
>     `column2` UInt32,
>     `column3` UInt16
>     
> )
> ENGINE = S3('https://s3...../click-house-input-test/*', 'AVRO', 'gz') │

And I couldn't get any data from it. 

> SELECT *
> FROM s3_facts
> LIMIT 10
> 
> Query id: 182ef5ac-d4eb-4eea-a913-56df6930a65f
> 
> 
> 0 rows in set. Elapsed: 0.047 sec.
> 
> Received exception from server (version 21.3.3):
> Code: 73. DB::Exception: Received from localhost:9000. DB::Exception: Unknown format AVRO.

When I try to get the info from csv or txt file, it is successful.
CH version - 21.3.3
OS - Ubuntu

**Comment by qoega** [comment]
It is trivially 'Avro' and case sensitive.
https://clickhouse.tech/docs/en/interfaces/formats/#data-format-avro

**Comment by stasDomb** [comment]
> It is trivially 'Avro' and case sensitive.
> https://clickhouse.tech/docs/en/interfaces/formats/#data-format-avro

Yes, it was easy. Thanks a lot!
