### ISSUE TITLE
No sync in data on both the nodes

### ISSUE THREAD

**Issue by DipalPrajapati** [ClickHouse/ClickHouse#24912]
Hi , 
I have 2 nodes in CH, have one ReplicatedReplacingMergeTree table , which does have different data on both the node . 
What could be the reason.
The insert only happens on Distributed table.

` CREATE TABLE offsetTable
(
    `tableName` LowCardinality(String),
    `lastUpdatedTime` SimpleAggregateFunction(max, DateTime)
)
ENGINE = ReplicatedReplacingMergeTree('/clickhouse/{clusterC2}/dbname/table/offsetTableLocal/{shardC2}', '{replicaC2}')
ORDER BY tableName
SETTINGS index_granularity = 8192`

data on node 1: 
`select * from  offsetTable FINAL;

SELECT *
FROM offsetTable
FINAL

Query id: e178dedf-a3ef-4b34-a0a7-bee99cf3e3bd

┌─tableName─┬─────lastUpdatedTime─┐
│ table1  │ 2020-05-24 00:00:00 │
└───────────┴─────────────────────┘
┌─tableName────┬─────lastUpdatedTime─┐
│ table2 │ 2020-05-28 00:00:00 │
└──────────────┴─────────────────────┘
`
node 2: 
`select * from  offsetTable FINAL;

SELECT *
FROM offsetTable
FINAL

Query id: 7990781e-4d52-4b72-86aa-be98859c407b

┌─tableName─────┬─────lastUpdatedTime─┐
│ table1 │ 2020-05-24 00:00:00│
└───────────────┴─────────────────────┘
┌─tableName─┬─────lastUpdatedTime─┐
│ table2  │  2020-05-27 00:00:00  │
└───────────┴─────────────────────┘
`
Why both does show different offset?

**Comment by den-crane** [comment]
Please share from BOTH SERVERS:

```
select absolute_delay , zookeeper_path, cityHash64(zookeeper_path) h, replica_path, log_pointer, zookeeper_exception 
from system.replicas  where table = 'offsetTable'

select * from system.macros

```

**Comment by DipalPrajapati** [comment]
`select absolute_delay , zookeeper_path, cityHash64(zookeeper_path) h, replica_path, log_pointer, zookeeper_exception
:-] from system.replicas  where table = 'offsetTableLocal'
:-] ;

SELECT
    absolute_delay,
    zookeeper_path,
    cityHash64(zookeeper_path) AS h,
    replica_path,
    log_pointer,
    zookeeper_exception
FROM system.replicas
WHERE table = 'offsetTableLocal'

Query id: d9859821-a0ce-4447-a0f4-742a003242ec

┌─absolute_delay─┬─zookeeper_path─────────────────────────────────────────────┬────────────────────h─┬─replica_path───────────────────────────────────────────────────────────┬─log_pointer─┬─zookeeper_exception─┐
│              0 │ /clickhouse/replicated/mydb/table/offsetTableLocal/01 │ 16794368672708443997 │ /clickhouse/replicated/mydb/table/offsetTableLocal/01/replicas/01 │         228 │                     │
└────────────────┴────────────────────────────────────────────────────────────┴──────────────────────┴────────────────────────────────────────────────────────────────────────┴─────────────┴─────────────────────┘
 select absolute_delay , zookeeper_path, cityHash64(zookeeper_path) h, replica_path, log_pointer, zookeeper_exception　 from system.replicas  where table = 'offsetTableLocal'　;

SELECT
    absolute_delay,
    zookeeper_path,
    cityHash64(zookeeper_path) AS h,
    replica_path,
    log_pointer,
    zookeeper_exception
FROM system.replicas
WHERE table = 'offsetTableLocal'

Query id: 845cfa39-1410-408e-b228-141fafc66c28

┌─absolute_delay─┬─zookeeper_path─────────────────────────────────────────────┬────────────────────h─┬─replica_path───────────────────────────────────────────────────────────┬─log_pointer─┬─zookeeper_exception─┐
│              0 │ /clickhouse/replicated/mydb/table/offsetTableLocal/02 │ 12082944535567172082 │ /clickhouse/replicated/mydb/table/offsetTableLocal/02/replicas/02 │         301 │                     │
└────────────────┴────────────────────────────────────────────────────────────┴──────────────────────┴────────────────────────────────────────────────────────────────────────┴─────────────┴─────────────────────┘


`

1 rows in set. Elapsed: 0.039 sec.


**select * from system.macros**
`
SELECT *
FROM system.macros

Query id: 5d4ea63f-0b3f-4711-b436-b80ecb50cf3a

┌─macro─────┬─substitution──────────────────────┐
│ clusterC1 │ two_shards_distributed_replicated │
│ clusterC2 │ replicated                        │
│ replicaC1 │ 01                                │
│ replicaC2 │ 01                                │
│ shardC1   │ 01                                │
│ shardC2   │ 01                                │
└───────────┴───────────────────────────────────┘

SELECT *
FROM system.macros

Query id: c4be68fe-634a-43f3-8a0e-d2494b0b25a6

┌─macro─────┬─substitution──────────────────────┐
│ clusterC1 │ two_shards_distributed_replicated │
│ clusterC2 │ replicated                        │
│ replicaC1 │ 02                                │
│ replicaC2 │ 02                                │
│ shardC1   │ 02                                │
│ shardC2   │ 02                                │
└───────────┴───────────────────────────────────┘
`

**Comment by den-crane** [comment]
You have 2 shards , NO REPLICATION!!!!!

/clickhouse/replicated/mydb/table/offsetTableLocal/02
/clickhouse/replicated/mydb/table/offsetTableLocal/01

│ shardC2 │ 01 │
│ shardC2 │ 02 │

You macros shard should be have the same value.

node1: │ shardC2 │ 01 │
node2: │ shardC2 │ 01 │

**Comment by DipalPrajapati** [comment]
Did not understand it .  Please check the cluster definitions. I have 2 kind of clusters in my db.  This particular table  is on `replicated` cluster. 
It is not HA cluster. 

clickhouse_shards:
  two_shards_distributed_replicated:
    shard01:
      - host: host1
        port: 9000
    shard02:
      - host: host2
        port: 9000
  replicated:
    shard01:
      - host: host1
        port: 9000
      - host: host2
        port: 9000

clickhouse_macros:
  macro_01:
   host1:
      clusterC1: two_shards_distributed_replicated
      clusterC2: replicated
      shardC1: "01"
      replicaC1: "01"
      shardC2: "01"
      replicaC2: "01"
    host2:
      clusterC1: two_shards_distributed_replicated
      clusterC2: replicated
      shardC1: "02"
      replicaC1: "02"
      shardC2: "02"
      replicaC2: "02"
      
      Please suggest how the value should be.
      
      For replicated should it be all 01 ?
