### ISSUE TITLE
Is it possible to have sharding with multiple disks but same node

### ISSUE THREAD

**Issue by shawel** [ClickHouse/ClickHouse#24931]
I have a single clickhouse instance with multiple volumes attached to i. I wanted to distribute data by sharding key in to different volumes! is this possible? is there a workaround if not?  

thanks

**Comment by filimonov** [comment]
Short answer - no. 

Long answer - clickhouse has a lot of building blocks which can be combined in different ways (while not all of the possible combination were tested, and can be considered as 'recommended'). For example you can try something like that: create 2 tables with same name in 2 different databases, and with different storage policies (each pointing to the single disk). Create a 'cluster' definition listing the same node (localhost) as 2 shards (but use  different <default_database>).  Create a Distributed table on top of that cluster.  

P.S. Why do you need it?

**Comment by shawel** [comment]
Thank you @filimonov! The main motivation is to increase throughput since i/o is the big bottleneck on our AWS EBS volume. It is about 3 TB worth of data and does full scans most of the time. The data has about 10 partitions atm on a single disk.

**Comment by den-crane** [comment]
The best and easiest way is to make raid0 using mdraid

**Comment by filimonov** [comment]
> motivation is to increase throughput 

That does not explain why do you need that sharding key. 

> The best and easiest way is to make raid0 using mdraid

+1.


You can also just use JBOD config on cluckhouse side. See https://altinity.com/blog/2019/11/27/amplifying-clickhouse-capacity-with-multi-volume-storage-part-1

**Comment by shawel** [comment]
Thanks @filimonov and @den-crane 
I will experiment with it.

@filimonov yes I considered Jbod and we have several tables using it. but the reason for shard key was distributed evenly. From the article 
'''
Background merges will tend to create bigger and bigger parts with time, moving each resulting part to one of the disks. As a result our storage policy does not give any guarantee that data will be evenly distributed across disks.  It also does not guarantee that I/O throughput will be better on JBOD than on the slowest disk. To get such guarantees you should use RAID instead.
'''

it seems like this will not work on on optimize. Perhaps there are settings to control

**Comment by alexey-milovidov** [comment]
You will still have multiple data parts and these parts will be distributed across disks in JBOD almost uniformly.
