### ISSUE TITLE
docker run: Configuration file '' isn't readable by user with id '101'

### ISSUE THREAD

**Issue by kasnet** [ClickHouse/ClickHouse#24953]
`
docker run -d --name clickhouse-server --ulimit nofile=262144:262144 -p 9100:9000 -p 8123:8123 -p 9009:9009 yandex/clickhouse-server:21.3.11.5
`
docker logs:
`
Configuration file '' isn't readable by user with id '101'
`

**Comment by filimonov** [comment]
Can't reproduce the problem with your example. 

Most probably you mount in the file /etc/clickhouse-server/config.xml which have no access for 101 user.
