### ISSUE TITLE
Can I submit pull requests on other language's document?

### ISSUE THREAD

**Issue by Tiaonmmn** [ClickHouse/ClickHouse#25014]
**Describe the issue**
When I read the Clickhouse document, I found that there are several inconsistencies with the English document. Can I submit pull  requests on it? 

**Additional context**
Such as [formats.md](https://github.com/ClickHouse/ClickHouse/blob/master/docs/zh/interfaces/formats.md),on line 71

> `TabSeparated`格式支持输出total值(与TOTALS一起使用时)和extreme值(当`extreme`被设置为1时)。在这种情况下，total值和extreme值会在主数据后输出。主要结果、总值和极值之间用空行分隔。示例:

The corresponding English document on line 74 is :

> The `TabSeparated` format supports outputting total values (when using WITH TOTALS) and extreme values (when ‘extremes’ is set to 1). In these cases, the total values and extremes are output after the main data. The main result, total values, and extremes are separated from each other by an empty line. Example:

The `extreme`  word is untranslated.That may make people confused when reading doc.

**Comment by ucasFL** [comment]
It's welcome to submit documents related pull requests.
