### ISSUE TITLE
Run Unit test with command make merge_selector. Error

### ISSUE THREAD

**Issue by wangzhen11aaa** [ClickHouse/ClickHouse#25013]
Hi, every one.
➜ tests git:(comment_code) ✗ make merge_selector
CMake Error: Error processing file: /Users/wen/ClionProjects/ClickHouse/CMakeFiles/VerifyGlobs.cmake
make[1]: *** [cmake_check_build_system] Error 1
make: *** [src/Storages/tests/CMakeFiles/merge_selector.dir/rule] Error 2
➜ tests git:(comment_code) ✗ tail -n 10 Makefile

Special targets to cleanup operation of make.
Special rule to run CMake to check the build system integrity.
No rule that depends on this can have commands that come from listfiles
because they might be regenerated.
cmake_check_build_system:
cd /Users/wen/ClionProjects/ClickHouse && $(CMAKE_COMMAND) -P /Users/wen/ClionProjects/ClickHouse/CMakeFiles/VerifyGlobs.cmake
cd /Users/wen/ClionProjects/ClickHouse && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

➜ tests git:(comment_code) ✗ ls /Users/wen/ClionProjects/ClickHouse/CMakeFiles/VerifyGlobs.cmake
ls: /Users/wen/ClionProjects/ClickHouse/CMakeFiles/VerifyGlobs.cmake: No such file or directory

I did not have this file in this directory.

Please help.

**Comment by alexey-milovidov** [comment]
Your environment can be messed up with CLion or something else.
I recommend to try with the clean working copy and using `ninja` instead of `make`.

**Comment by wangzhen11aaa** [comment]
> Your environment might be messed up with CLion or something else.
> I recommend to try with a clean working copy and using `ninja` instead of `make`.

My local environment is VScode in Mac. Usually, I use the extension installed in Vscode, cmake-ui to compile this object.

My ninja comes with these errors:

➜  tests git:(comment_code) ✗ ninja --version
1.10.2
➜  tests git:(comment_code) ✗ ninja merge_selector
ninja: error: loading 'build.ninja': No such file or directory

**Comment by wangzhen11aaa** [comment]
> Your environment might be messed up with CLion or something else.
> I recommend to try with a clean working copy and using `ninja` instead of `make`.

Hi, You mean I need a complete clean code or environment? or both.

**Comment by wangzhen11aaa** [comment]
Hi, I have tried cmake which is a extension installed in VSCode.

[build] CMake Error:
[build]   The detected version of Ninja (GNU Make 3.81
[build] 
[build]   Copyright (C) 2006 Free Software Foundation, Inc.
[build] 
[build]   This is free software; see the source for copying conditions.
[build] 
[build]   There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
[build] 
[build]   PARTICULAR PURPOSE.
[build] 
[build]   
[build] 
[build]   This program built for i386-apple-darwin11.3.0) is less than the version of
[build]   Ninja required by CMake (1.3).
[build] 
[build] 
[build] CMake Error at contrib/zlib-ng/cmake/archdetect.cmake:22 (try_run):
[build]   Failed to generate test project build system.
[build] Call Stack (most recent call first):
[build]   contrib/zlib-ng/CMakeLists.txt:56 (include)

But, the ninja version is the newest one. 
➜  ClionProjects ninja --version
1.10.2

**Comment by alexey-milovidov** [comment]
> This program built for i386-apple-darwin11.3.0)

It means you are using 32bit version of Ninja.

**Comment by wangzhen11aaa** [comment]
> > This program built for i386-apple-darwin11.3.0)
> 
> It means you are using 32bit version of Ninja.

Hi,  I just install ninja with the following command in Mac.
brew install ninja 
Thanks for your reply.

**Comment by wangzhen11aaa** [comment]
Thanks, the VerifyGlobs.cmake file locates in 
.//debug/CMakeFiles/VerifyGlobs.cmake.
I use the cmake tools installed in VScode, it is ok now. 
alexey-milovidov

**Comment by wangzhen11aaa** [comment]
/usr/local/bin/cmake --build /Users/wen/ClionProjects/ClickHouse/debug --config Debug --target merge_selector -j 10
It seems we can set the --build configuration to make the ninja to get this VerifyGlobs.cmake file.

**Comment by wangzhen11aaa** [comment]
Let make a conclusion:
CMake Error: Error processing file: /Users/wen/ClionProjects/ClickHouse/CMakeFiles/VerifyGlobs.cmake
make[1]: *** [cmake_check_build_system] Error 1
make: *** [src/Storages/tests/CMakeFiles/merge_selector.dir/rule] Error 2
This error prompted by cmake is right, It can not find this file.
----------------------------------- Beautiful split line ---------------------------
build] The detected version of Ninja (GNU Make 3.81
[build]
[build] Copyright (C) 2006 Free Software Foundation, Inc.
[build]
[build] This is free software; see the source for copying conditions.
[build]
[build] There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
[build]
[build] PARTICULAR PURPOSE.
This promption is not cool.
