### ISSUE TITLE
A DoS attack issue with wrong user&password

### ISSUE THREAD

**Issue by IvyWei** [ClickHouse/ClickHouse#25035]
Hi,  on v21.3.4.25-lts we found a DoS attack issue.

> for i in {1..5000}
do
    clickhouse client --host xx.xx.xx.xx --port 9000 -u ckuser --password 'wrong_password' --query "select 1" >/dev/null 2>&1 &
done 

After above testcase being executed, new connection with correct user&password  may get  a timeout or some others error
> Code: 209. DB::NetException: Timeout exceeded while reading from socket (xx.xx.xx.xx:9000)

Are we aware of this problem or Do we have any plans about this?

**Comment by alexey-milovidov** [comment]
What version of ClickHouse do you use?

**Comment by IvyWei** [comment]
v21.3



发自我的小米手机
在 alexey-milovidov ***@***.***>，2021年6月7日 下午7:00写道：

What version of ClickHouse do you use?

**Comment by IvyWei** [comment]
> What version of ClickHouse do you use?

v21.3.4.25-lts

**Comment by alexey-milovidov** [comment]
Do you connect to ClickHouse directly or it is behind a proxy like Cloudflare?
Cloudflare has DoS protection that will detect these connection attempts and disable access.

**Comment by alexey-milovidov** [comment]
And do you use the unmodified version of ClickHouse?

I checked it on master with 
```
for i in {1..5000}; do clickhouse-client --password abc; done
```
in one terminal window
and 
```
for i in {1..5000}; do clickhouse-client --query "SELECT 1"; done
```
in another terminal window.

No such issue, it works flawlessly.

So, we need to differentiate the possible causes of this issue.

By the way, what is your server configuration?

**Comment by IvyWei** [comment]
> Do you connect to ClickHouse directly or it is behind a proxy like Cloudflare?

Directly,  server and client both in one host.


> And do you use the unmodified version of ClickHouse?

Actually not, i have some changed in it. Maybe it's a self-introduced problem, will update here later if any clue.
