### ISSUE TITLE
Are there  plans to  provide  arm64 installation package ?

### ISSUE THREAD

**Issue by juyonychen** [ClickHouse/ClickHouse#25032]
Dear,
     Now，we have to Running Clickhouse on the CPU of Kunpeng 920，it's arm64 architecture。So, are there  plans to 
provide  arm64 installation package ?
    thinks.

**Comment by filimonov** [comment]
See https://github.com/ClickHouse/ClickHouse/issues/25030#issuecomment-855928636

**Comment by juyonychen** [comment]
thanks！
