### ISSUE TITLE
While executing AggregatingTransform, Memory limit (for query) exceeded

### ISSUE THREAD

**Issue by zcw5116** [ClickHouse/ClickHouse#25058]
Server RAM:  64GB
CPU: 16 Core
CH Version： 21.6.2.7

When using default settings，excuting the following statement，  everything is OK :

> select country, sum(in_flow) as sum_in_flow, sum(out_flow) sum_out_flow from　accesslog a group by country;

However, when I setting max_bytes_before_external_group_by=100000000, (100MB)， then excuting the above statement， but an error throw， the following：

> → Progress: 591.76 million rows, 19.06 GB (31.80 million rows/s., 1.02 GB/s.) ██████████████████████████████████████████████████████████████████ 99%
0 rows in set. Elapsed: 18.835 sec. Processed 591.76 million rows, 19.06 GB (31.42 million rows/s., 1.01 GB/s.)

Received exception from server (version 21.6.2):
Code: 241. DB::Exception: Received from ch001:9000. DB::Exception: Memory limit (for query) exceeded: would use 9.31 GiB (attempt to allocate chunk of 4204636 bytes), maximum: 9.31 GiB: While executing AggregatingTransform. 

disk space is enough large，what's wrong ?
thank you.

**Comment by MrSsunlight** [comment]
set max_memory_usage

**Comment by zcw5116** [comment]
> set max_memory_usage

Setting this parameter is useless.
Note:
1. The default max_memory_usage parameter value is 10g. When I don't set max_bytes_before_external_group_by, everything is normal.
2. When I set the value of the max_bytes_before_external_group_by parameter to 2g, everything is normal.
3. When I set the value of the max_bytes_before_external_group_by parameter to 100M, the memory overflowed.
4. When I set the value of the max_bytes_before_external_group_by parameter to 100M and increase the max_memory_usage to 50G, the query hangs.

**Comment by alexey-milovidov** [comment]
If you set `max_bytes_before_external_group_by` to a very low value, large number of temporary files will be generated, and (paradoxically) the amount of memory needed to merge these temporary files and finish the query will be even higher.

**Comment by alexey-milovidov** [comment]
if max_memory_usage is 10 GB, I recommend to set max_bytes_before_external_group_by to 5 GB.

**Comment by sherrychenzhang** [comment]
meet this problem，too. seems the group by need a lot of memory. 1 G data 90G memory, hard to think.

**Comment by alexey-milovidov** [comment]
@sherrychenzhang There is nothing surprising if 1 GB of compressed data requires 90 GB of in memory data structures for aggregation.

**Comment by sherrychenzhang** [comment]
> @sherrychenzhang There is nothing surprising if 1 GB of compressed data requires 90 GB of in memory data structures for aggregation.

but we are using like 1GB of uncompressed data.

**Comment by zcw5116** [comment]
> If you set `max_bytes_before_external_group_by` to a very low value, large number of temporary files will be generated, and (paradoxically) the amount of memory needed to merge these temporary files and finish the query will be even higher.

Good reply, thank you very much.

**Comment by sherrychenzhang** [comment]
set  max_bytes_before_external_group_by      10000000000     1

still error? not big enough?

Received exception from server (version 19.5.3):
Code: 241. DB::Exception: Received from 127.0.0.1:8326. DB::Exception: Received from 127.0.0.1:7327. DB::Exception: Memory limit (for query) exceeded: would use 99.03 GiB (attempt to allocate
chunk of 8589934592 bytes), maximum: 93.13 GiB.
18.097
12,18150,241

**Comment by zcw5116** [comment]
> set max_bytes_before_external_group_by 10000000000 1
> 
> still error? not big enough?
> 
> Received exception from server (version 19.5.3):
> DB::Exception: Memory limit (for query) exceeded: would use 99.03 GiB (attempt to allocate
> chunk of 8589934592 bytes), maximum: 93.13 GiB.

what's your sql statement ?

**Comment by alexey-milovidov** [comment]
I can check if the memory usage is normal if you provide some datasets to test.

**Comment by alexey-milovidov** [comment]
@sherrychenzhang Are there any other memory heavy operations:
ORDER BY, DISTINCT, IN subquery, JOIN, etc...

**Comment by zcw5116** [comment]
> @sherrychenzhang Are there any other memory heavy operations?:
> ORDER BY, DISTINCT, IN subquery, JOIN, etc...

Received exception from server (version 19.5.3):
DB::Exception: Memory limit (for query) exceeded: would use 99.03 GiB (attempt to allocate
chunk of 8589934592 bytes), maximum: 93.13 GiB.

His error information does not contain Any AggregatingTransform infromation, Maybe not group-by statement.

**Comment by ChuhC** [comment]
meet the same problem on  version 20.7.1.1

**Comment by ChuhC** [comment]
`max_bytes_before_external_group_by` setting not work

**Comment by ChuhC** [comment]
sql: 

  `SELECT serial, addr_src_int, addr_dst_int, proto, port_dst, sum(cnt) as count FROM TrafficSumming   WHERE  (  serial = '315fe87034d0c7e498c704dd09196739dbe52dfc'  ) AND  ( date >= '2021-06-22 09:02:32' AND date < '2021-06-22 10:02:32' )  GROUP BY serial, addr_src_int, addr_dst_int, proto, port_dst, cnt  LIMIT 180000, 20000`
