### ISSUE TITLE
Ubuntu graphical installation / upgrade hungs on asking default password for clickhouse-server

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#25054]
configuring :(

![Screenshot from 2021-06-07 16-36-01](https://user-images.githubusercontent.com/1549571/121035985-addb4f00-c7ae-11eb-8327-00d25d87119c.png)

And if we will open 'details':

![Screenshot from 2021-06-07 16-36-051](https://user-images.githubusercontent.com/1549571/121036223-e2e7a180-c7ae-11eb-800d-81b20c7eff49.png)

See https://github.com/ClickHouse/ClickHouse/pull/22976#issuecomment-820910439

**Comment by alexey-milovidov** [comment]
How to detect the Ubuntu graphical installation from the script?

**Comment by alexey-milovidov** [comment]
This issue required help, but no help was provided.
