### ISSUE TITLE
unexpected data packet crash process ? 

### ISSUE THREAD

**Issue by qingping209** [ClickHouse/ClickHouse#25068]
our production clickhouse process crashed with the following stack:

![image](https://user-images.githubusercontent.com/11344292/121142855-fce8b900-c86e-11eb-897e-b9059e6adabb.png)

it seems like cause by unexpected data packet  ?  

After I restarted the process, I run the query, and everything is OK. So I believe the crash is not caused by the query.

the corefile is up to 130GB, way too big to do any meaningful analysis.

**Comment by den-crane** [comment]
21.4 is out of support. 
It's not the official build? Did you build Clickhouse yourself?

**Comment by alexey-milovidov** [comment]
@qingping209 This is your own alternative build of ClickHouse.
The official build does not have this issue.

**Comment by qingping209** [comment]
> 21.4 is out of support.
> It's not the official build? Did you build Clickhouse yourself?

Yes. I built Clickhouse myself.

**Comment by qingping209** [comment]
> @qingping209 This is your own alternative build of ClickHouse.
> The official build does not have this issue.

I followed the build instruction. So which version do you recommend to use. And what's the difference of the official build from the build instruction  ? anything need special attention ?
