### ISSUE TITLE
DiskS3::restoreFiles may misorder objects of a file

### ISSUE THREAD

**Issue by yuzhichang** [ClickHouse/ClickHouse#25069]
At DiskS3.cpp, line 232:
DiskS3::writeFile(const String & path, size_t buf_size, WriteMode mode) 
if path exist, and mode=Append, then create a randomly named object and append to the meta. This object name(S3 key) may precede previous object names in dictionary order.

DiskS3::restoreFiles iterates S3 keys in dictionary order to restore the meta.

Version: 21.7.1.7029
@GrigoryPervakov , @Jokser

**Comment by Jokser** [comment]
@yuzhichang Agree, it can be. But it affects only Log* engines. At the moment there is no backup mechanism for them.
This issue can be solved with introducing an order field in S3 object metadata which determines order of S3 object in corresponding metadata file.

**Comment by alexey-milovidov** [comment]
Maybe introduce this field just in case?
BTW does s3 metadata have versioning?

**Comment by Jokser** [comment]
S3 object metadata is just a `map<string, string>`. We can add any new field to it.

**Comment by alexey-milovidov** [comment]
"Zero-copy" replication is a non-production feature.
The server issues a warning if it is trying to be used.
Its status is also stated in the documentation.

The "restore" feature in this issue has no relation to the officially supported BACKUP/RESTORE commands.
