### ISSUE TITLE
Build for Intel(R) Core(TM)2 Duo CPU     E8400  @ 3.00GHz failed

### ISSUE THREAD

**Issue by hbk-ronak** [ClickHouse/ClickHouse#25086]
Hi. I'm a graduate student and I'm trying to setup a database for a research project that I'm working on with my professor. I've been trying to install clickhouse from source on the server allocated to me but I've been unsuccessful. Can someone look into the build error and help me fix it? Any help will be greatly appreciated.

The command that I used to install ClickHouse are as follows:
git clone --recursive https://github.com/ClickHouse/ClickHouse.git
git submodule sync --recursive && git submodule update --init --recursive && git submodule foreach git submodule foreach git reset --hard && git submodule foreach git submodule foreach git clean -xfd
CC=gcc-11
CXX=g++-11
mkdir ~/packages/ClickHouse/build
cd ~/packages/ClickHouse/build
cmake -DHAVE_SSE41=0 -DHAVE_SSE42=0 -DHAVE_POPCNT=0 DHAVE_PCLMULQDQ_INTRIN=0 -DPCLMULFLAG=' ' ..
ninja

**Operating system**
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
OS kind or distribution, specific version/release, non-standard kernel if any. If you are trying to build inside virtual machine, please mention it too.

**Cmake version**
cmake version 3.16.3

**Ninja version**
1.10.0

**Compiler name and version**
gcc (Ubuntu 11.1.0-1ubuntu1:20.04) 11.1.0
g++ (Ubuntu 11.1.0-1ubuntu1:20.04) 11.1.0

**Full cmake and/or ninja output**
The full Cmake and ninja output is in the link
[log.txt](https://github.com/ClickHouse/ClickHouse/files/6618764/log.txt)

**Comment by alexey-milovidov** [comment]
Let's build with clang-11 or clang-12.

**Comment by hbk-ronak** [comment]
Hi,

As suggested I built with clang-12 and the build was successful. But when I tried to run 

```ls -l programs/clickhouse```
I get the following message (when run from $HOME or from $HOME/packages/ClickHouse (the path where repo was cloned))

```
ls: cannot access 'programs/clickhouse': No such file or directory
```
I used the following sequence of commands to build the clickhouse

git clone --recursive https://github.com/ClickHouse/ClickHouse.git
echo "Repository Cloned"
cd ~/packages/ClickHouse
git submodule sync --recursive && git submodule update --init --recursive && git submodule foreach git submodule foreach git reset --hard && git submodule foreach git submodule foreach git clean -xfd
echo "Submodules updates"
export CC=clang-12
export CXX=clang++-12
echo "Creating a build directory"
mkdir ~/packages/ClickHouse/build
echo "cd into build directory"
cd ~/packages/ClickHouse/build
echo "calling cmake"
cmake -DHAVE_SSE41=0 -DHAVE_SSE42=0 -DHAVE_POPCNT=0 -DHAVE_PCLMULQDQ_INTRIN=0 -DPCLMULFLAG=' ' ..
echo "building"
ninja clickhouse

The log for the build is attached [here](https://github.com/ClickHouse/ClickHouse/files/6626464/log.txt)

**Comment by alexey-milovidov** [comment]
It is in your build directory, usually `build/programs/clickhouse`.
Nevertheless, you can find it:
`find . -name clickhouse -type f -executable`

**Comment by hbk-ronak** [comment]
Thanks this works. I'm now able to run clickhouse client and clickhouse server.
