### ISSUE TITLE
2021.06.09 11:19:20.803174 [ 21807 ] {e7d3a563-caf9-4ad2-b45c-f94dc072dcc0} <Error> TCPHandler: Code: 10, e.displayText() = DB::Exception: Not found column createTime in block, Stack trace:

### ISSUE THREAD

**Issue by AKMCC-hub** [ClickHouse/ClickHouse#25108]
2021.06.09 11:19:20.803174 [ 21807 ] {e7d3a563-caf9-4ad2-b45c-f94dc072dcc0} <Error> TCPHandler: Code: 10, e.displayText() = DB::Exception: Not found column createTime in block, Stack trace:

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x8b5b17a in /usr/bin/clickhouse
1. DB::Exception::Exception<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x8bf9e63 in /usr/bin/clickhouse
2. DB::ActionsDAG::updateHeader(DB::Block) const @ 0xf49c047 in /usr/bin/clickhouse
3. DB::ExpressionStep::ExpressionStep(DB::DataStream const&, std::__1::shared_ptr<DB::ActionsDAG>) @ 0x1061e8ca in /usr/bin/clickhouse
4. DB::MergeTreeDataSelectExecutor::spreadMarkRangesAmongStreamsFinal(std::__1::vector<DB::RangesInDataPart, std::__1::allocator<DB::RangesInDataPart> >&&, std::__1::unique_ptr<std::__1::vector<DB::ReadFromMergeTree::IndexStat, std::__1::allocator<DB::ReadFromMergeTree::IndexStat> >, std::__1::default_delete<std::__1::vector<DB::ReadFromMergeTree::IndexStat, std::__1::allocator<DB::ReadFromMergeTree::IndexStat> > > >, unsigned long, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, unsigned long, bool, DB::SelectQueryInfo const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, DB::Settings const&, DB::MergeTreeReaderSettings const&, std::__1::shared_ptr<DB::ActionsDAG>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const @ 0x101b4eca in /usr/bin/clickhouse
5. DB::MergeTreeDataSelectExecutor::readFromParts(std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeDataPart const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeDataPart const> > >, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context>, unsigned long, unsigned int, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, long, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, long> > > const*, DB::MergeTreeDataSelectCache*) const @ 0x101ac5cf in /usr/bin/clickhouse
6. DB::MergeTreeDataSelectExecutor::read(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context>, unsigned long, unsigned int, DB::QueryProcessingStage::Enum, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, long, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, long> > > const*) const @ 0x1019ea0b in /usr/bin/clickhouse
7. DB::StorageMergeTree::read(DB::QueryPlan&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryInfo&, std::__1::shared_ptr<DB::Context>, DB::QueryProcessingStage::Enum, unsigned long, unsigned int) @ 0xfe5714d in /usr/bin/clickhouse
8. DB::StorageMergeTree::read(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryInfo&, std::__1::shared_ptr<DB::Context>, DB::QueryProcessingStage::Enum, unsigned long, unsigned int) @ 0xfe57279 in /usr/bin/clickhouse
9. DB::StorageMaterializeMySQL::read(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryInfo&, std::__1::shared_ptr<DB::Context>, DB::QueryProcessingStage::Enum, unsigned long, unsigned int) @ 0xfe32c69 in /usr/bin/clickhouse
10. DB::IStorage::read(DB::QueryPlan&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryInfo&, std::__1::shared_ptr<DB::Context>, DB::QueryProcessingStage::Enum, unsigned long, unsigned int) @ 0xfd81cb7 in /usr/bin/clickhouse
11. DB::InterpreterSelectQuery::executeFetchColumns(DB::QueryProcessingStage::Enum, DB::QueryPlan&) @ 0xf89eccf in /usr/bin/clickhouse
12. DB::InterpreterSelectQuery::executeImpl(DB::QueryPlan&, std::__1::shared_ptr<DB::IBlockInputStream> const&, std::__1::optional<DB::Pipe>) @ 0xf896a23 in /usr/bin/clickhouse
13. DB::InterpreterSelectQuery::buildQueryPlan(DB::QueryPlan&) @ 0xf895ae0 in /usr/bin/clickhouse
14. DB::InterpreterSelectWithUnionQuery::buildQueryPlan(DB::QueryPlan&) @ 0xfa0553e in /usr/bin/clickhouse
15. DB::InterpreterSelectWithUnionQuery::execute() @ 0xfa06611 in /usr/bin/clickhouse
16. ? @ 0xfbc0da1 in /usr/bin/clickhouse
17. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, bool) @ 0xfbbf423 in /usr/bin/clickhouse
18. DB::TCPHandler::runImpl() @ 0x103e5eb2 in /usr/bin/clickhouse
19. DB::TCPHandler::run() @ 0x103f8db9 in /usr/bin/clickhouse
20. Poco::Net::TCPServerConnection::start() @ 0x129f64af in /usr/bin/clickhouse
21. Poco::Net::TCPServerDispatcher::run() @ 0x129f7f3a in /usr/bin/clickhouse
22. Poco::PooledThread::run() @ 0x12b31f39 in /usr/bin/clickhouse
23. Poco::ThreadImpl::runnableEntry(void*) @ 0x12b2df2a in /usr/bin/clickhouse
24. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
25. clone @ 0xfe96d in /usr/lib64/libc-2.17.so

**Comment by filimonov** [comment]
> Not found column createTime in block

If the column is there - please share table schema and query you run.

Otherwise we can't help you and ticket will be closed.

**Comment by menglshuai** [comment]
> > 在块中找不到列 createTime
> 
> 如果该列在那里 - 请共享表架构并运行查询。
> 
> 否则我们无法帮助您，票将被关闭。

db :) desc student_login_log

DESCRIBE TABLE student_login_log

Query id: 1aa306f4-234b-4164-adeb-117ded8dd02f

┌─name────────┬─type─────────────┬─default_type─┬─default_expression─┬─comment─┬─codec_expression─┬─ttl_expression─┐
│ id          │ UInt32           │              │                    │         │                  │                │
│ uid         │ Int32            │              │                    │         │                  │                │
│ login_time  │ DateTime         │              │                    │         │                  │                │
│ school_id   │ Nullable(Int32)  │              │                    │         │                  │                │
│ ip_addr     │ Nullable(String) │              │                    │         │                  │                │
│ device_uuid │ String           │              │                    │         │                  │                │
│ http_header │ String           │              │                    │         │                  │                │
│ utoken      │ String           │              │                    │         │                  │                │
│ update_at   │ DateTime         │              │                    │         │                  │                │
│ _sign       │ Int8             │ MATERIALIZED │ 1                  │         │                  │                │
│ _version    │ UInt64           │ MATERIALIZED │ 1                  │         │                  │                │
└─────────────┴──────────────────┴──────────────┴────────────────────┴─────────┴──────────────────┴────────────────┘

11 rows in set. Elapsed: 0.001 sec.

db :) select device_uuid from student_login_log where uid = 324142\G

SELECT device_uuid
FROM student_login_log
WHERE uid = 324142

Query id: e76829b0-3b53-411e-98ee-b3cd395ff42d


0 rows in set. Elapsed: 0.005 sec.

Received exception from server (version 21.6.3):
Code: 47. DB::Exception: Received from localhost:9000. DB::Exception: Missing columns: 'uid' while processing query: '_sign = 1, uid, device_uuid', required columns: '_sign' 'uid' 'device_uuid' '_sign' 'uid' 'device_uuid'.

db :) select * from student_login_log where uid = 324142\G

SELECT *
FROM student_login_log
WHERE uid = 324142

Query id: 6e460a7a-0147-4512-9ed2-41ac609daa53

Row 1:
──────
id:          3454309
uid:         324142
login_time:  2021-01-07 19:32:28






2021.06.09 13:55:21.172475 [ 21807 ] {e76829b0-3b53-411e-98ee-b3cd395ff42d} <Error> TCPHandler: Code: 47, e.displayText() = DB::Exception: Missing columns: 'uid' while processing query: '_sign = 1, uid, device_uuid', required columns: '_sign' 'uid' 'device_uuid' '_sign' 'uid' 'device_uuid', Stack trace:

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x8b5b17a in /usr/bin/clickhouse
1. DB::TreeRewriterResult::collectUsedColumns(std::__1::shared_ptr<DB::IAST> const&, bool) @ 0xfb540d0 in /usr/bin/clickhouse
2. DB::TreeRewriter::analyze(std::__1::shared_ptr<DB::IAST>&, DB::NamesAndTypesList const&, std::__1::shared_ptr<DB::IStorage const>, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, bool) const @ 0xfb5d20c in /usr/bin/clickhouse
3. DB::StorageMaterializeMySQL::read(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryInfo&, std::__1::shared_ptr<DB::Context>, DB::QueryProcessingStage::Enum, unsigned long, unsigned int) @ 0xfe32f15 in /usr/bin/clickhouse
4. DB::IStorage::read(DB::QueryPlan&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryInfo&, std::__1::shared_ptr<DB::Context>, DB::QueryProcessingStage::Enum, unsigned long, unsigned int) @ 0xfd81cb7 in /usr/bin/clickhouse
5. DB::InterpreterSelectQuery::executeFetchColumns(DB::QueryProcessingStage::Enum, DB::QueryPlan&) @ 0xf89eccf in /usr/bin/clickhouse
6. DB::InterpreterSelectQuery::executeImpl(DB::QueryPlan&, std::__1::shared_ptr<DB::IBlockInputStream> const&, std::__1::optional<DB::Pipe>) @ 0xf896a23 in /usr/bin/clickhouse
7. DB::InterpreterSelectQuery::buildQueryPlan(DB::QueryPlan&) @ 0xf895ae0 in /usr/bin/clickhouse
8. DB::InterpreterSelectWithUnionQuery::buildQueryPlan(DB::QueryPlan&) @ 0xfa0553e in /usr/bin/clickhouse
9. DB::InterpreterSelectWithUnionQuery::execute() @ 0xfa06611 in /usr/bin/clickhouse
10. ? @ 0xfbc0da1 in /usr/bin/clickhouse
11. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, bool) @ 0xfbbf423 in /usr/bin/clickhouse
12. DB::TCPHandler::runImpl() @ 0x103e5eb2 in /usr/bin/clickhouse
13. DB::TCPHandler::run() @ 0x103f8db9 in /usr/bin/clickhouse
14. Poco::Net::TCPServerConnection::start() @ 0x129f64af in /usr/bin/clickhouse
15. Poco::Net::TCPServerDispatcher::run() @ 0x129f7f3a in /usr/bin/clickhouse
16. Poco::PooledThread::run() @ 0x12b31f39 in /usr/bin/clickhouse
17. Poco::ThreadImpl::runnableEntry(void*) @ 0x12b2df2a in /usr/bin/clickhouse
18. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
19. clone @ 0xfe96d in /usr/lib64/libc-2.17.so
