### ISSUE TITLE
'Different expressions with the same alias' error on single select query with CTE

### ISSUE THREAD

**Issue by ahmeturun** [ClickHouse/ClickHouse#25118]
executing a query that doesn't have any union statements gives 'Different expressions with the same alias _subquery365786:' error when 'enable_global_with_statement' setting is enabled.

```
create table cnumbers (`number` UInt64, `letter` LowCardinality(String) CODEC(ZSTD(1))) ENGINE = MergeTree() 
ORDER BY number
PRIMARY KEY number;

insert into cnumbers select number, toString(number) from system.numbers limit 5;

with 5 as s
SELECT number, letter FROM cnumbers
prewhere (number,letter) in (SELECT number, letter FROM cnumbers)
where 
	number < 100;
```

reproduced on 
21.3.12.2

error message details
SQL Error [179]: ClickHouse exception, code: 179, host: 10.10.5.41, port: 8123; Code: 179, e.displayText() = DB::Exception: Different expressions with the same alias _subquery365788:
(WITH 5 AS s SELECT number, letter FROM cnumbers) AS _subquery365788
and
(WITH 5 AS s SELECT number, letter FROM cnumbers) AS _subquery365788
: While processing (WITH 5 AS s SELECT number, letter FROM cnumbers) AS _subquery365788 (version 21.3.12.2 (official build))

**Comment by siradjev** [comment]
Additional info. 
problem won't happen if GLobal WITH is not used (enable_global_with_statement=0). Backward incompatible change not mentioned in documentation/changelog #18705.
Problem won't happen if explicit prewhere or implicit move to prewhere is not used.

**Comment by alexey-milovidov** [comment]
I will close this issue in favor of #23194.
