### ISSUE TITLE
Is there any way to get resultset in the order of arguments in IN query . I am asking this in regards with clickhouse

### ISSUE THREAD

**Issue by deepprakash345** [ClickHouse/ClickHouse#25120]
Is there any way to get resultset in the order of arguments in IN query . I am asking this in regards with clickhouse. 
For ex :-
select * from table where name in ('AAA','BBB','CCC');
Can we get result in the order such that records are sorted by name .

**Comment by shacuros** [comment]
You can try like this:

```
select *
from table
where name in ('AAA','BBB','CCC')
ORDER BY indexOf(['AAA','BBB','CCC'], name)
```

**Comment by filimonov** [comment]
> You can try like this:
> 
```
select *
from table
where name in ('AAA','BBB','CCC')
ORDER BY name
```

**Comment by deepprakash345** [comment]
@shacuros , This worked, thank you so much

**Comment by deepprakash345** [comment]
@shacuros , can you please give me some input on https://github.com/ClickHouse/ClickHouse/issues/25121.
