### ISSUE TITLE
Backup Technique for clickhouse .

### ISSUE THREAD

**Issue by deepprakash345** [ClickHouse/ClickHouse#25121]
As far as we have checked. clickhouse changes all the parts even if one row is updated in the table. In this case taking remote backup becomes very costly due to transfer of huge amount of data.Can anyone suggest me any better way to this

**Comment by den-crane** [comment]
There is a feature for Replicated tables  update-in-partition https://clickhouse.tech/docs/en/sql-reference/statements/alter/partition/#update-in-partition

Also CH changes only names of the parts, so you can deduce using part name and checksums.txt that part is unchanged, just renamed.
