### ISSUE TITLE
HTML Form Exception: Field value too long 

### ISSUE THREAD

**Issue by lopn** [ClickHouse/ClickHouse#25139]
Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = HTML Form Exception: Field value too long (version 21.3.6.55 (official build)

how can i do it？

**Comment by lopn** [comment]
@abyss7 can you help me?

**Comment by abyss7** [comment]
Can you please provide any data about your HTTP request? Especially the field values in your POST headers.

**Comment by lopn** [comment]
https://github.com/ClickHouse/ClickHouse/blob/3e63b033e87d7b183a4024fcf8d4dadbeb471d4b/src/Server/HTTP/HTMLForm.cpp#L253

**Comment by abyss7** [comment]
If you are sure that the problem is exacly with this limitation, then I will just a server setting for it.

**Comment by lopn** [comment]
POST /?wait_end_of_query=1&database=default&user=xxxx&password=xxxxx HTTP/1.1
Host: 172.31.32.7:8123
Content-Length: 372086
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="query"

with ps as (SELECT
	rp.chan_pub_id as chan_pub_id,rp.publisher_id as publisher_id,sum(pub_impression) as pub_impression,sum(pub_cost) as pub_cost,sum(pub_click) as pub_click,max(channel_id) as channel_id
FROM xxxxxx

**Comment by lopn** [comment]
POST /?wait_end_of_query=1&database=default&user=xxxx&password=xxxx HTTP/1.1
Host: 172.31.32.7:8123
Content-Length: 185809
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="query"

with ps as (SELECT
	rp.chan_pub_id as chan_pub_id,rp.publisher_id as publisher_id,sum(pub_impression) as pub_impression,sum(pub_cost) as pub_cost,sum(pub_click) as pub_click,max(channel_id) as channel_id
FROM
	xxxxxx

**Comment by lopn** [comment]
DFL_MAX_VALUE_LENGTH = 256 * 1024
        https://github.com/ClickHouse/ClickHouse/blob/3e63b033e87d7b183a4024fcf8d4dadbeb471d4b/src/Server/HTTP/HTMLForm.h#L132
        
        this default is 256KB， how can config it

**Comment by lopn** [comment]
@abyss7

**Comment by lopn** [comment]
@abyss7

**Comment by lopn** [comment]
@abyss7 what time can you add configure?   i want to use it
