### ISSUE TITLE
RunningDifference(x) for multiple Grouping values

### ISSUE THREAD

**Issue by ervivekmehta** [ClickHouse/ClickHouse#2515]
My Table tbl_data(event_time, monitor_id,type,event_date,status)

select status,sum(runningDifference(event_time)) as delta from (SELECT status,event_date,event_time FROM tbl_data WHERE event_date >= '2018-05-01' AND monitor_id =3 ORDER BY event_time ASC) group by status

Result will be

status delta
1 4665465
2 965

This query result give me right answer for single monitor_id, Now I required it for multiple monitor_id,

How can I achieve it in single/same query??

I have tried by grouping but it also run calculation based on monitor grouping, so monitor grouping will not solve problem as I think.

please revert if you have any solution for me.

**Comment by filimonov** [comment]
Related #8326

**Comment by alexey-milovidov** [comment]
The feature was implemented in the following PR: https://github.com/ClickHouse/ClickHouse/pull/8326

**Comment by forkwhilefork** [comment]
I think this was incorrectly closed. It doesn't look like this was implemented in #8326.

**Comment by tanchik-curly** [comment]
@alexey-milovidov @filimonov @den-crane Do we have this implemented, because I have the same issue in a new version?

**Comment by den-crane** [comment]
@tanchik-curly RunningDifference is abomination, use window functions.

**Comment by tanchik-curly** [comment]
@den-crane thanks for your answer!
Could you provide an optimized example for getting the delta between two consecutive rows and I have a couple of different ids in a filter?

```select * from (
SELECT
    -- *,
    t._id AS _id,
    t.time AS time,
    t.kpiEac as kpiEac,
    case when t.eacT != 0 then t.eacT else null end as EAC_T,
    runningDifference(EAC_T) as delta,
    m.tReset as tReset
  FROM MSS02_DATA.SIGNALS AS t
  INNER JOIN (SELECT * FROM MSS02_DATA.V_METADATA WHERE _id_portfolio = '6540e52a48334fb975f87f7d' and _id IN ('65450f0bab44b1356f7b39dc', '65450f0ba9d5091aa07b3e9d')) AS m ON t._id = m._id
  WHERE
    _id_portfolio = '6540e52a48334fb975f87f7d'
    and _id IN ('65450f0ba9d5091aa07b3e9d', '65450f0bab44b1356f7b39dc')
    and time >= toDateTime(1713823200)
    and time <= toDateTime(1713956400)
  ORDER BY time ASC
  WITH FILL
    from toDateTime(1713823200)
    to toDateTime(1713956400)
  STEP 300
  ) order by _id DESC, time ```

**Comment by den-crane** [comment]
@tanchik-curly Please open a separate issue. Don't spoil the old closed unrelated issue. https://kb.altinity.com/altinity-kb-queries-and-syntax/lag-lead/#using-laginframeleadinframe-starting-from-clickhouse-214
Thank you in advance.
