### ISSUE TITLE
how to let one instance only accept insert queries ?

### ISSUE THREAD

**Issue by haiertashu** [ClickHouse/ClickHouse#25160]
hi all,
  Is there a way to make one instance only accept the insert queries without the select queries?

```xml
 <shard>
     <replica>
         <role>0</role>
         <host>node1</host>
         <port>9000</port>
     </replica>
     <replica>
         <role>1</role>
         <host>node2</host>
         <port>9000</port>
     </replica>
 </shard>
```
for example, 'role' field to config the replica accept insert_only(role=1) / select_only(role=2) / both(role=0)

**Comment by alexey-milovidov** [comment]
Create two clusters.
One contains single replica and is used for SELECTs and another contains both replicas and is used for INSERTs.
