### ISSUE TITLE
[RFC] Detached parts cleanup

### ISSUE THREAD

**Issue by tavplubix** [ClickHouse/ClickHouse#25195]
Automatically remove parts that where detached long time ago (one month by default) and have some prefix in name (such as `broken`, `broken_on_start`, `inactive`, `clone`, etc). It should not affect parts that were detached manually by `ALTER DETACH` query.

**Comment by filimonov** [comment]
Some types of inactive parts are almost useless (_tmp),  automatic cleaning for them after some retention period should be good. 

Users almost never check them and sometimes a lot of disk space is wasted by them. 

Extra thoughts:
May be we can add a warning at server start about the size occupied by detached parts and expose their count / size at async metric.

May be we can apply same ttl rules to detached parts (w/o merge, similar to ddl_only_drop_parts).
