### ISSUE TITLE
clickhouse server start fatal.

### ISSUE THREAD

**Issue by shadowDy** [ClickHouse/ClickHouse#25202]
2021.06.11 18:57:22.349719 [ 25903 ] {} <Trace> BaseDaemon: Received signal 11
2021.06.11 18:57:22.349894 [ 26078 ] {} <Fatal> BaseDaemon: ########################################
2021.06.11 18:57:22.349945 [ 26078 ] {} <Fatal> BaseDaemon: (version 20.12.3.3 (official build), no build id) (from thread 25912) (no query) Received signal Segmentation fault (11)
2021.06.11 18:57:22.349964 [ 26078 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
2021.06.11 18:57:22.349981 [ 26078 ] {} <Fatal> BaseDaemon: Stack trace: 0xe2d6a01 0xe072832 0xe070224 0xe06e0b4 0xd930e4c 0x7d1e5ed 0x7d20b4f 0x7d1baad 0x7d1f5d3 0x318b207851 0x318aee767d
2021.06.11 18:57:22.350066 [ 26078 ] {} <Fatal> BaseDaemon: 2. DB::StorageDistributedDirectoryMonitor::createPool(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>
 > const&, DB::StorageDistributed const&) @ 0xe2d6a01 in ?
2021.06.11 18:57:22.350086 [ 26078 ] {} <Fatal> BaseDaemon: 3. DB::StorageDistributed::requireDirectoryMonitor(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >
const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xe072832 in ?
2021.06.11 18:57:22.350112 [ 26078 ] {} <Fatal> BaseDaemon: 4. DB::StorageDistributed::createDirectoryMonitors(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >
const&) @ 0xe070224 in ?
2021.06.11 18:57:22.350125 [ 26078 ] {} <Fatal> BaseDaemon: 5. DB::StorageDistributed::startup() @ 0xe06e0b4 in ?
2021.06.11 18:57:22.350156 [ 26078 ] {} <Fatal> BaseDaemon: 6. ? @ 0xd930e4c in ?
2021.06.11 18:57:22.350178 [ 26078 ] {} <Fatal> BaseDaemon: 7. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0x7d1e5ed in ?
2021.06.11 18:57:22.350232 [ 26078 ] {} <Fatal> BaseDaemon: 8. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>,
int, std::__1::optional<unsigned long>)::'lambda1'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()&&...)::'lambda'()::operator()() @ 0x7d20b4f in ?
2021.06.11 18:57:22.350259 [ 26078 ] {} <Fatal> BaseDaemon: 9. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x7d1baad in ?
2021.06.11 18:57:22.350267 [ 26078 ] {} <Fatal> BaseDaemon: 10. ? @ 0x7d1f5d3 in ?
2021.06.11 18:57:22.350274 [ 26078 ] {} <Fatal> BaseDaemon: 11. start_thread @ 0x318b207851 in ?
2021.06.11 18:57:22.350300 [ 26078 ] {} <Fatal> BaseDaemon: 12. __clone @ 0x318aee767d in ?
2021.06.11 18:57:22.350315 [ 26078 ] {} <Information> SentryWriter: Not sending crash report

**Comment by KochetovNicolai** [comment]
Version 20.12.3.3 is not supported already. Could you try 21.3 at least?
