### ISSUE TITLE
MaterializeMySQL:DB::Exception: ParseQueryEvent: Unsupported query event:SAVEPOINT `trans2`

### ISSUE THREAD

**Issue by kasnet** [ClickHouse/ClickHouse#25211]
**myql:5.7  my.conf:**

log-bin=/data/logs/mysql/mysql-bin.log 
binlog_format=ROW 
server-id=1
sync_binlog=1

gtid-mode=on
enforce-gtid-consistency=1
log-slave-updates=1 

**report error:**
{38b4d524-03bc-4781-96e4-9351330b25be} <Error> DynamicQueryHandler: Code: 49, e.displayText() =
DB::Exception: ParseQueryEvent: Unsupported query event:SAVEPOINT `trans2`, Stack trace (when copying this message, always inclu
de the lines below):

0. DB::MySQLReplication::QueryEvent::parseImpl(DB::ReadBuffer&) @ 0xe8f2d5e in /usr/bin/clickhouse
1. DB::MySQLReplication::MySQLFlavor::readPayloadImpl(DB::ReadBuffer&) @ 0xe8faee2 in /usr/bin/clickhouse
2. DB::MySQLProtocol::IMySQLReadPacket::readPayload(DB::ReadBuffer&, unsigned char&) @ 0xe8e0bf7 in /usr/bin/clickhouse
3. DB::MySQLProtocol::PacketEndpoint::tryReceivePacket(DB::MySQLProtocol::IMySQLReadPacket&, unsigned long) @ 0xe8e1693 in /usr/b
in/clickhouse
4. DB::MaterializeMySQLSyncThread::synchronization() @ 0xe8aeea8 in /usr/bin/clickhouse
5. ? @ 0xe8ce272 in /usr/bin/clickhouse
6. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x8531a3f in /usr/bin/clickhous
e
7. ? @ 0x8535563 in /usr/bin/clickhouse
8. start_thread @ 0x9609 in /lib/libpthread.so.0
9. __clone @ 0x122293 in /lib/libc.so.6
 (version 21.3.11.5 (official build))

**Comment by kasnet** [comment]
Hi，which version solved this problem？ @alexey-milovidov

**Comment by Lonsss** [comment]
UP!  faced the same problem
`  File "/usr/local/lib/python3.6/dist-packages/clickhouse_driver/client.py", line 290, in execute
    columnar=columnar
  File "/usr/local/lib/python3.6/dist-packages/clickhouse_driver/client.py", line 480, in process_ordinary_query
    columnar=columnar)
  File "/usr/local/lib/python3.6/dist-packages/clickhouse_driver/client.py", line 136, in receive_result
    return result.get_result()
  File "/usr/local/lib/python3.6/dist-packages/clickhouse_driver/result.py", line 50, in get_result
    for packet in self.packet_generator:
  File "/usr/local/lib/python3.6/dist-packages/clickhouse_driver/client.py", line 152, in packet_generator
    packet = self.receive_packet()
  File "/usr/local/lib/python3.6/dist-packages/clickhouse_driver/client.py", line 169, in receive_packet
    raise packet.exception
clickhouse_driver.errors.ServerException: Code: 49.
DB::Exception: ParseQueryEvent: Unsupported query event:SAVEPOINT `s2fd2b5b243c04dbe966bb2a009b9ad18`. Stack trace:

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x9b722d4 in /usr/bin/clickhouse
1. DB::MySQLReplication::QueryEvent::parseImpl(DB::ReadBuffer&) @ 0x11f7ddd7 in /usr/bin/clickhouse
2. DB::MySQLReplication::MySQLFlavor::readPayloadImpl(DB::ReadBuffer&) @ 0x11f843e0 in /usr/bin/clickhouse
3. DB::MySQLProtocol::IMySQLReadPacket::readPayload(DB::ReadBuffer&, unsigned char&) @ 0x11f6e887 in /usr/bin/clickhouse
4. DB::MaterializedMySQLSyncThread::synchronization() @ 0x11f5565d in /usr/bin/clickhouse
5. ? @ 0x11f63cb3 in /usr/bin/clickhouse
6. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x9bb4397 in /usr/bin/clickhouse
7. ? @ 0x9bb7d9d in /usr/bin/clickhouse
8. start_thread @ 0x9450 in /usr/lib/x86_64-linux-gnu/libpthread-2.33.so
9. clone @ 0x117d53 in /usr/lib/x86_64-linux-gnu/libc-2.33.so
`

**Comment by jeeinn** [comment]
Save Problem  /(ㄒoㄒ)/~~
version 21.12.3.32
```
<Error> DynamicQueryHandler: Code: 49. DB::Exception: ParseQueryEvent: Unsupported query event:SAVEPOINT `trans2`. (LOGICAL_ERROR), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa21959a in /usr/bin/clickhouse
1. DB::MySQLReplication::QueryEvent::parseImpl(DB::ReadBuffer&) @ 0x12d697f7 in /usr/bin/clickhouse
2. DB::MySQLReplication::MySQLFlavor::readPayloadImpl(DB::ReadBuffer&) @ 0x12d6ff37 in /usr/bin/clickhouse
3. DB::MySQLProtocol::IMySQLReadPacket::readPayload(DB::ReadBuffer&, unsigned char&) @ 0x12d5be4b in /usr/bin/clickhouse
4. DB::MySQLProtocol::PacketEndpoint::tryReceivePacket(DB::MySQLProtocol::IMySQLReadPacket&, unsigned long) @ 0x12d5c9ad in /usr/bin/clickhouse
5. DB::MaterializedMySQLSyncThread::synchronization() @ 0x12d43afe in /usr/bin/clickhouse
6. ? @ 0x12d51430 in /usr/bin/clickhouse
7. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa25a3b7 in /usr/bin/clickhouse
8. ? @ 0xa25ddbd in /usr/bin/clickhouse
9. start_thread @ 0x817a in /usr/lib64/libpthread-2.28.so
10. __clone @ 0xfcdc3 in /usr/lib64/libc-2.28.so
 (version 21.12.3.32 (official build))
```

**Comment by jeeinn** [comment]
>Maybe because of use `SET allow_experimental_database_materialized_mysql = 1;` in session
>add tag to `users.xml` -> profiles -> default can solved
>`<allow_experimental_database_materialized_mysql>1</allow_experimental_database_materialized_mysql>`

**Comment by MahmoudElhalwany** [comment]
@jeeinn @Lonsss  @kasnet 

any news?

**Comment by windylcx** [comment]
same problem ,any solutions?
