### ISSUE TITLE
Limitations on amount of query parameters

### ISSUE THREAD

**Issue by grundrauschen** [ClickHouse/ClickHouse#25216]
**Describe the unexpected behaviour**
I try to use parameterized queries for our software to prevent SQL injections over user variable fields.
The implementation worked so far.

As our software can create quite large or complicated queries,
we ran into a first limitation.

We have a query with ~800 parameters and get back an error when using `curl` (for debugging).

**How to reproduce**
* Which ClickHouse server version to use
  * 21.5.6.6
* Which interface to use, if matters
  * HTTP
* Non-default settings, if any
* Query
  * As the parameters were not cleaned from confidential data, I can sadly not provide example tables and queries.
  * If needed for further investigation, I would try to create a query, which uses enough parameters to trigger the error.

**Expected behavior**
There should not be a limit to the amount of query fields.

**Error message and/or stacktrace**

```
$ curl -v `cat url.txt` --data-binary @query.sql
> Host: clickhouse:8123
> User-Agent: curl/7.64.0
> Accept: */*
> Content-Length: 49780
> Content-Type: application/x-www-form-urlencoded
> Expect: 100-continue
>
* Expire in 1000 ms for 0 (transfer 0x558051040fb0)
< HTTP/1.1 100 Continue
* We are completely uploaded and fine
< HTTP/1.1 500 Internal Server Error
< Date: Fri, 11 Jun 2021 14:02:47 GMT
< Connection: Keep-Alive
< Content-Type: text/plain; charset=UTF-8
< X-ClickHouse-Server-Display-Name: 60601d5e39b6
< Transfer-Encoding: chunked
< X-ClickHouse-Exception-Code: 1000
<
Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = HTML Form Exception: Too many form fields (version 20.10.3.30 (official build))
* Connection #0 to host clickhouse left intact
```

How large is the limit on the query parameters and would there be a technical solution to not have an upper limit on the parameter count?

Thank you in advance.

**Comment by alexey-milovidov** [comment]
@abyss7 Let's make all these thresholds customizeable and also raise them to some large enough value by default, e.g. one million of fields.
