### ISSUE TITLE
Had to re-create LDAP users after upgrading from 21.3 to 21.6

### ISSUE THREAD

**Issue by zhicwu** [ClickHouse/ClickHouse#25226]
After upgrading server from 21.3 to 21.6, all ldap users disappeared. None of them appears in `SHOW USERS` output, although relevant SQL scripts still exist under `/var/lib/clickhouse-server/user_files`.

I wasn't able to re-create ldap user due to below error, so I had to drop and then re-create each user.
``` text
Received exception from server (version 21.6.3):
Code: 493. DB::Exception: Received from localhost:9000. DB::Exception: user `xxx`: cannot insert because user `xxx` already exists in local directory: Couldn't insert user `derekw`. Successfully inserted: none.
```

Is it because the SQL script using incorrect SQL(should replace `ldap_server BY` to `LDAP SERVER`)?
``` sql
ATTACH USER xxx IDENTIFIED WITH ldap_server BY 'window_ad';
```

**Comment by traceon** [comment]
Are those users only authenticated through LDAP or there is an LDAP users directory configured? Users, that are learned about from LDAP are ephemeral, you shouldn't add them permanently and the list of such users will be cleared after each clickhouse server restart.

**Comment by zhicwu** [comment]
Authenticated through LDAP, windows active directory to be more specific.

I use below statement to create them:
``` sql
-- 'window_ad' is an ldap server defined in config.xml
CREATE USER xxx IDENTIFIED WITH LDAP SERVER BY 'window_ad';
```

**Comment by traceon** [comment]
OK, then the right way to recreate them would be:
```sql
CREATE USER xxx IDENTIFIED WITH ldap SERVER 'window_ad';
```

The syntax was changed before the final release of the feature.

**Comment by zhicwu** [comment]
Thanks @traceon. Yes, I did that on both 21.3 and 21.6 without issue. The problem happened after upgrading from 21.3 to 21.6. I noticed the SQL script under /var/lib/clickhouse-server/user_files still uses incorrect syntax, but I'm not sure if it's the root cause or not.

**Comment by traceon** [comment]
So you get
```
cannot insert because user `xxx` already exists in local directory
```
but the user is not listed in the output of `SHOW USERS`?

**Comment by zhicwu** [comment]
Yes.

**Comment by alexey-milovidov** [comment]
@traceon Said that the syntax has been changed since first experimental versions.

> Is it because the SQL script using incorrect SQL(should replace ldap_server BY to LDAP SERVER)?

Yes, the queries have to be adjusted.
