### ISSUE TITLE
How to set "storage policy" for Materialize MySQL engine

### ISSUE THREAD

**Issue by taotaizhu-pw** [ClickHouse/ClickHouse#25239]
We need to set "storage policy" for  Materialize MySQL engine. This engin create the table automaticly, I cannot add "settings storage_policy" command. How can we modify the policy for Materialize MySQL engine? Can we change the default policy setting? 

Thanks

**Comment by den-crane** [comment]
You can set another value for `  <path>/var/lib/clickhouse/</path>` /etc/clickhouse-server/config.xml
Or you can change default policy.

```
cat /etc/clickhouse-server/config.d/storage.xml
<?xml version="1.0" ?>
<yandex>
    <storage_configuration>
            <disks>
                <disk1>
                    <path>/mnt/disk1/</path>
                </disk1>
            </disks>
        <policies>
            <default>
                <volumes>
                    <default>
                        <disk>default</disk>
                        <disk>disk1</disk>
                    </default>
                </volumes>
            </default>
        </policies>
     </storage_configuration>
 </yandex>
```

**Comment by DipalPrajapati** [comment]
@den-crane Is it okay to change the default policy like this for encrypted storage configuration? 
` 
<storage_configuration>
	<disks>
		<disk1>
			<type>local</type>
			<path>/var/lib/clickhouse/</path>
		</disk1>
		<disk2>
			<type>encrypted</type>
			<disk>disk1</disk>
			<path>encrypted_one/</path>
			
			<algorithm>AES_128_CTR</algorithm>
			<key_hex id="0">00112233445566778899aabbccddeeff</key_hex>
			<key_hex id="1">ffeeddccbbaa99887766554433221100</key_hex>
			<current_key_id>1</current_key_id>
		</disk2>
	</disks>
	<policies>
		<default>
			<volumes>
				<default>
					<disk>disk2</disk>
				</default>
			</volumes>
		</default>
	</policies>
</storage_configuration>
`
Let me know , thanks. May i name it differently then default and still keep it default  ? if yes how?
