### ISSUE TITLE
I have a question about this comment. 

### ISSUE THREAD

**Issue by wangzhen11aaa** [ClickHouse/ClickHouse#25230]
Thanks advance.
 
explicit ThreadFromGlobalPool(Function && func, Args &&... args)
        : state(std::make_shared<Poco::Event>())
    {
        /// NOTE: If this will throw an exception, the destructor won't be called.
        GlobalThreadPool::instance().scheduleOrThrow([
            state = state,
            func = std::forward<Function>(func),
            args = std::make_tuple(std::forward<Args>(args)...)]() mutable
      ....
    }

The comment followed the Note says that the destructor won't be called. 
I mean, all the resources are controlled by smart_pointers,
state controlled by shared_ptr,
func, and args are  right value 
all of them are on the stack of schedule(), to be more precise, they are used to construct a temporary lambda object functioned like lambda. I personally think that all of them can be freed when the exception occurs.
Where am i wrong?

**Comment by alexey-milovidov** [comment]
The comment just warns that the destructor of ThreadFromGlobalPool won't be called in case of exception.
Although it does not have any significant logic, only an assertion:

```
        if (joinable())
            abort();
```
