### ISSUE TITLE
build.ninja and gnutls

### ISSUE THREAD

**Issue by sheerluck** [ClickHouse/ClickHouse#2524]
Gentoo Linux: clickhouse-1.1.54385 fails to compile
But when I added -lgnutls to LINK_LIBRARIES in file clickhouse-1.1.54385_build/build.ninja
(three times, right after -lrdkafka) it compiles just fine

**Comment by proller** [comment]
please show how you run cmake and cmake console output
you can try redefine rdkafka libs:
```cmake .. -DRDKAFKA_LIB=/path/to/rdkafka;/path/to/libgnutls.a```
