### ISSUE TITLE
Ability to define a default database using a user profile.

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#25268]
I have 3 users A, B, C. Each user has own private DB: A, B, C. 
I need an ability to set for each user their private DB as default for their queries.

**Comment by MaxWk** [comment]
Hi den-crane,I have some question about that issue. Currently we already have a default_database config in config.xml. 
If we implement this feature，is it necessary to keep it?

**Comment by alexey-milovidov** [comment]
@MaxWk 

> If we implement this feature，is it necessary to keep it?

Yes, it will act as "default default". So, if `default_database` is specified for user in `users.xml` or with `CREATE USER`, it will be used; if not - the `default_database` from `config.xml` will be used.

**Comment by MaxWk** [comment]
> @MaxWk
> 
> > If we implement this feature，is it necessary to keep it?
> 
> Yes, it will act as "default default". So, if `default_database` is specified for user in `users.xml` or with `CREATE USER`, it will be used; if not - the `default_database` from `config.xml` will be used.

ok,please assign it to me

**Comment by MaxWk** [comment]
@den-crane this feature already merged
