### ISSUE TITLE
Inquiries about processing ALTER DELETE

### ISSUE THREAD

**Issue by parkbaesun** [ClickHouse/ClickHouse#25261]
Hello,

I am currently using the clickhouse 20.6.6.7 version.

I'd like to inquire about ALTER DELETE syntax.

I checked that all ALTER DELETE data that I have used so far were entered into system.mutations

So i'd like to ask you a question regarding this part.

1. I think the data will continue to be entered in system.mutations, so wouldn't this be a problem?

2. Is there any part of clickhouse that automatically deletes system.mutations data?
  (for example, old system.mutations data)

3. Is there a way for the user to delete system.mutations data?

4. If I delete the data in system.mutations, would there be any problem with the data deleted in ALTER DELETE syntax?

**Comment by den-crane** [comment]
1,2. CH keeps only  recent mutations
   Merge_tree setting 
   ```finished_mutations_to_keep                         │ 100   │       0 │ How many records about mutations that are done to keep. If zero, then keep all of them.```
   https://clickhouse.tech/docs/en/operations/settings/merge-tree-settings/#merge-tree-settings
   `select * from system.merge_tree_settings where name like '%muta%';`

3. No.
4. It's impossible. `system.mutations` is a virtual table it does not support mutations
