### ISSUE TITLE
Support for non-constant regular expressions and LIKE conditions.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#25271]
**Use case**
```
SELECT count()
FROM test.hits
WHERE URL LIKE concat('%', Referer, '%')

0 rows in set. Elapsed: 0.042 sec. 

Received exception from server (version 21.7.1):
Code: 44. DB::Exception: Received from localhost:9000. DB::Exception: Argument at index 1 for function like must be constant: while executing 'FUNCTION like(URL : 0, concat('%', Referer, '%') : 3) -> like(URL, concat('%', Referer, '%')) UInt8 : 4'.
```

**Describe the solution you'd like**
Construct them dynamically.

**Additional context**
The cache for regular expressions is unlimited in memory.
Now we have to make it limited somehow.

The most simple solution is to simply drop the cache when its size is at some threshold (e.g. 10 000 items).
(or just reuse LRUCache)

**Comment by rschu1ze** [comment]
Will look into this as a warmup task.

**Comment by alexey-milovidov** [comment]
@rschu1ze is

> The cache for regular expressions is unlimited in memory.
Now we have to make it limited somehow.

> The most simple solution is to simply drop the cache when its size is at some threshold (e.g. 10 000 items).

addressed?

**Comment by rschu1ze** [comment]
Caching is useful if there are few patterns. I am thinking about alternatives with different tradeoffs right now (we don't want to impact "normal" LIKEs with const-patterns too much where caching is *always* useful.) Will push something in a follow-up PR.
