### ISSUE TITLE
Allow different primary key and group by in  Summing/Aggregating engines

### ISSUE THREAD

**Issue by ipostelnik** [ClickHouse/ClickHouse#2528]
Today, Summing/Aggregating engines will group by primary key when updating aggregated values. Since primary keys have to be kept in memory this sometimes forces painful choices if key values are large. It would be nice to be able to aggregate by longer list of fields, but only include a subset of them in the primary key. 

Another variant is aggregating by a long string key (say User-Agent header value), but using a hash of the value as primary key. This is probably more difficult to support since it requires different storage order from aggregation.

**Comment by alexey-milovidov** [comment]
Now you can specify ORDER BY clause and PRIMARY KEY with subset of columns from ORDER BY.
