### ISSUE TITLE
[RFC] Materialization improvements

### ISSUE THREAD

**Issue by Algunenano** [ClickHouse/ClickHouse#25291]
We want to improve status visibility and error handling of materialize views in ClickHouse. For that we have several feature requests / proposals and we wanted to share them with the community before we start any development. 

This is an early plan subject to change. I would rather have a good solution that fits ClickHouse spirit rathen than the perfect solution for our use cases, so feel free to share any ideas or share any concerns. Thanks a lot in advance. 

These are the 4 features proposed (detailed bellow):
* A new log for materializations
* Be able to modify (with some contraints) the SQL of a materialized view.
* Optional quarantine partitions for failures during materialization.
* Syntax to replay a quarantined partition.

My plan is to start working on those features in order as they are independent (1, 2, then 3 and 4 together).

## Logging

We want to improve the visibility of materializations as there isn't a straightforward way to know how much time is spent in each materialization when inserting data, nor which materializations have been executed and which haven't when a failure happens in one of them (especially if using parallel view processing).

To address this we want to add a new system log (system.query_materialization_log) with the result of each materialization. A single query could potentially insert [0..N] rows in this table.

### Settings

Setting: `log_materialization`. When enabled adds the result of materialized views into the `system.query_materialization_log` log. You can change the name of the table in the table parameter (see below).

Use the following parameters to configure logging (same as query_thread_log):

`database` – Name of the database.
`table` – Name of the system table the queries will be logged in.
`partition_by` — Custom partitioning key for a system table. Can't be used if engine defined.
`engine` - MergeTree Engine Definition for a system table. Can't be used if partition_by defined.
`flush_interval_milliseconds` – Interval for flushing data from the buffer in memory to the table.
`log_level` - The minimum status to log

If the table does not exist, ClickHouse will create it. If the structure of the query materialization log changed when the ClickHouse server was updated, the table with the old structure is renamed and a new table is created automatically.

Example
```
<query_materialization_log>
    <database>system</database>
    <table>query_materialization_log</table>
    <partition_by>toMonday(event_date)</partition_by>
    <flush_interval_milliseconds>7500</flush_interval_milliseconds>
</query_materialization_log>
```

### Fields

The materialization log table would contain the following fields:

Duration fields:

* event_date:           2021-04-08
* event_time:           2021-04-08 13:14:12
* materialization_start_time:     2021-04-08 13:14:12
* materialization_duration_ms: 981

Query identification:

* user:                 default
* query_id:             9458bbe0-a4dd-45fd-93fe-5968916f8ef4
* materialization_name: matview_a
* materialization_uuid: 00000000-0000-0000-0000-000000000000
* materialization_query: ATTACH MATERIALIZED VIEW matview_a TO default.table_b (`key` Float64,`count` Int64) AS SELECT toFloat64(a) AS key, b AS count FROM default.table_a

Runtime data (information that affects only by this materialization, not the whole query):

* read_rows:            0
* read_bytes:           0
* written_rows:         4
* written_bytes:        72
* memory_usage:         4201086
* ProfileEvents.Names:  ['Query','IOBufferAllocs','IOBufferAllocBytes','ContextLock','RWLockAcquiredReadLocks','RealTimeMicroseconds','UserTimeMicroseconds','SystemTimeMicroseconds','SoftPageFaults','HardPageFaults','OSIOWaitMicroseconds','OSCPUVirtualTimeMicroseconds','OSReadBytes','OSWriteBytes','OSWriteChars']
* ProfileEvents.Values: [1,3,2101293,18,1,981473,17385,11996,530,16,952011,29381,15065088,4096,2048]

Status:

* status: MaterializationFinished, MaterializationError, MaterializationCancelled
  * MaterializationFinished: The materialization finished correctly. Data was written into the target table.
  * MaterializationError: There was an error when running this materialization. Data wasn't written into the target table.
  * MaterializationCancelled: The materialization was cancelled and wasn't executed (for example if a previous materialization with the same source table failed). Data wasn't written into the target table.
* exception_code: Error core
* exception: Error message
* stack_trace: Error stack trace
* quarantine_part: If quarantined (See other proposals), the name of the part

## ALTER MATERIALIZE VIEW

A large number of errors that happen in materialized views are due to corner cases in the input, things such as not handling NULL values, invalid JSON inputs (that could be avoid with isValidJSON) or failed casts (toInt32 vs COALESCE(toInt32OrNull(value), -1)).

The problem we have is that currently to fix the materialize view you need to drop it and create it. This has 2 possibilities:
* If the view dumps into a different table (`[TO[db.]name]`) then you can do it without losing data, but there is an interval of time during which the view doesn't exist and an insert won't be materialized.
* If the view stores the data into an inner table, then you have the same issue as above (interval without materialization) but you will also lose any data that was already generated.

### SYNTAX

The proposal is to be able to modify the SQL of MATERIALIZE VIEWS:

```
ALTER TABLE [db].name [ON CLUSTER cluster] QUERY AS SELECT ...
```

This would allow transforming only the view query as long as it keeps the same structure, for example replacing

```
SELECT toInt32(JSONExtractRaw(record,'size')) as size FROM default.landing
```

with
```
SELECT coalesce(toInt32OrNull(JSONExtractRaw(record,'size')), -1) as size FROM default.landing
```

It would throw an error if the table isn't a materialized view or if you try changing either source or target tables or columns.

## QUARANTINE ON ERROR

When an insertion on a materialized view fails there might not be an easy way to recover the lost data, as the block that failed might not be identifiable in the source table, or it might have a small TTL or ENGINE = NULL.

Related to this, if the data has already been inserted in other materialized views dependendent on the same source table, retrying the insertion in the landing table will duplicate data there. You can only improve this with good design (batch id, deduplication... and praying).

To improve the situation we want to propose a new keyword set at materialization view creation (`QUARANTINE`) which changes its behaviour on error. Instead of throwing an exception the error will be logged (in the query_materialization_log), the blocks will be saved a quarantined part and the process will continue normally (other views on the same source table would be executed).

Errors also include timeouts during view execution and cancellations where the source table has already written it's data.

Note that in order for this to be effective and be reused later `log_materialization` should be enabled and logging >= ERROR.

### SYNTAX

During creation:
```sql
CREATE MATERIALIZED VIEW [IF NOT EXISTS] [db.]matview_name [ON CLUSTER] [TO[db.]name] [ENGINE = engine] [POPULATE] [QUARANTINE] AS SELECT ...
```

Alternatively, we could add a way to enable or disable it after creation:
```sql
ALTER TABLE [db].name [ON CLUSTER cluster] MODIFY QUARANTINE [TRUE|FALSE]
```

### QUARANTINE PARTS

When an error happens in a materialization view with `QUARANTINE`, the log_materialization will include the error and the name of a quarantine part that includes the input of the original query.

Quarantined parts are stored under the **target_table** path:

```
$(CH_PATH)/data/$(DATABASE)/$(TARGET_TABLE)/quarantine_$(MATVIEW)_${id}
```

These parts:

* Aren't replicated
* Are removed automatically if applied successfully (see REPLAY)
* Are removed automatically if the matview is deleted (both for inner and external tables)
* Are removed automatically if the quarantine is disabled for the view
* Can't be attached/detached since they have a different structure.
* Should contain any necessary information to re-read them and reprocess them again (see REPLAY).

## QUARANTINE REPLAY

To make it easier to reproduce an issue or relaunch the process once the view has been altered to accept the input, we propose to have a new `ALTER` query that allows you to replay a quarantined part. This query would read the quarantine part (partition_expr), the **current definition** of the materialization view and process it again doing an insert over the target table.

If applied correctly, this will automatically delete the quarantine part.

### SYNTAX

```sql
ALTER TABLE [db.]matview_name REPLAY PARTITION partition_expr;
```

**Comment by UnamedRus** [comment]
For 2 part

There is `allow_experimental_alter_materialized_view_structure ` support for this already but it's in experimental state.

https://github.com/ClickHouse/ClickHouse/issues/15206

**Comment by den-crane** [comment]
Atomic/Transactional  insertion into TABLE <-> MV will be addressed https://github.com/ClickHouse/ClickHouse/issues/22086

**Comment by UnamedRus** [comment]
But concept of quarantine parts could be interesting.

Related https://github.com/ClickHouse/ClickHouse/issues/21721

**Comment by Algunenano** [comment]
> For 2 part
> There is allow_experimental_alter_materialized_view_structure support for this already but it's in experimental state.

Thanks. I'll have a look to see how it works and whether I can help test it and getting it into a stable status.

> Atomic/Transactional insertion into TABLE <-> MV will be addressed #22086

Atomic inserts with materialized views would also solve our issues. We are already quarantining data at the application level when an insert fails, so I don't see any issue on replaying everything vs quaratining and replaying only the affected materialized view.

**Comment by amosbird** [comment]
Quarantine parts look similar to what https://github.com/ClickHouse/ClickHouse/pull/14860 tried to offer.

**Comment by azat** [comment]
>A new log for materializations

To me, materialized views should be logged as a separate queries. So instead of introducing separate system tables for them they should be just appeared in system.processes and system.query_log as a separate queries.

I started this in #20477, but there are some conceptual comments from @akuzm 

>QUARANTINE PARTS

One of concerns here is too many files. Using one big file for storing all failures (i.e. some log) may be too slow, from the other side there should not be too much such parts, and using one file replay will be much simpler (i.e. `ALTER TABLE mv REPLAY`), what do you think about this?

*Plus the syntax `ALTER TABLE mv REPLAY PARTITION ...` may confuse user (since PARTITION is in MergeTree only)*

**Comment by Algunenano** [comment]
> To me, materialized views should be logged as a separate queries. So instead of introducing separate system tables for them they should be just appeared in system.processes and system.query_log as a separate queries.

I see two possible issues there:
- Whether project wise, CH want's to consider dependent queries as different processes or not. What warrants being considered a full query (query_log) vs thread (query_thread_log)?
- By adding everything to system.query_log you either will be missing important columns or will have many columns that won't be used by other types of queries. For example, views might want to log the view name / uuid and target table, remote queries will want to store information about the remote server, client requests save information about the client, etc.

> I started this in #20477, but there are some conceptual comments from @akuzm

I like the idea of having a QueryProcess/QueryProcessHolder class from the PR that you can use to keep control of the processes / queries. To implement the view_logs in #25714 I've had to manually switch between ThreadStatus' as you might multiple queries/views being executed interleaved in the same thread. Anything that makes that simpler would be great.

> One of concerns here is too many files. Using one big file for storing all failures (i.e. some log) may be too slow, from the other side there should not be too much such parts, and using one file replay will be much simpler (i.e. ALTER TABLE mv REPLAY), what do you think about this?

The problem with that is that you lose granularity. For example, if you have a failure from last week and a failure from today, having a single file would force you to replay both, even though you are probably only want to keep the recent one as it's the one that made you look into it. No strong feelings, though.

> Plus the syntax ALTER TABLE mv REPLAY PARTITION ... may confuse user (since PARTITION is in MergeTree only)

You could call it `BATCH` instead and avoid naming PARTITION.

That being said, I would rather have atomic inserts (including views) first as they might make having a quarantine system less necessary. It might still be useful, but then I would consider it for all tables and not only materialized views.

**Comment by azat** [comment]
>Whether project wise, CH want's to consider dependent queries as different processes or not. What warrants being considered a full query (query_log) vs thread (query_thread_log)?

Sorry don't get this.

>By adding everything to system.query_log you either will be missing important columns or will have many columns that won't be used by other types of queries.

Maybe you are right (to me separate table for MV logging looks a little bit too much, but if everything from this issue will be done I guess this will make MV special anyway, and separate logging is okay then).

> For example, views might want to log the view name / uuid and target table

There is `tables` and `databases`, this is enough to log all the tables that are used in the query (the same can be done for UUID)

**Comment by Algunenano** [comment]
Closing this old ticket:
* The log was implemented.
* Changing the materialized view query was already supported.
* The quarantine idea can be handled externally with transactions (experimental)

I'd rather open other specific tickets (or PRs) if there are future ideas to improve materialization and close this
