### ISSUE TITLE
Performance Difference b/n Local and distributed query

### ISSUE THREAD

**Issue by shawel** [ClickHouse/ClickHouse#25308]
I have the following table on Node1  called Node1Local (Contains all data)
```
CREATE TABLE default.Node1Local
(
    `A` UInt64,
    `B` Array(UInt32)
)
ENGINE = MergeTree
PRIMARY KEY A
ORDER BY A
SETTINGS index_granularity = 8192

insert into Node1Local select number, arrayDistinct(arraySlice(arrayMap(x -> rand(x)%6000, range(1000)),1, rand()%1000)) from numbers(100000000);
```
Node2 has table Node1LocalDistributed that accessed Node1Local on Node1. (All data is on Node1) 
```
CREATE TABLE default.Node1LocalDistributed
(
    `A` UInt64,
    `B` Array(UInt32)
)
ENGINE = Distributed('audience', 'default', 'Node1Local')
```

However queries on Node1 (Node1Local) and Node2  (Node1LocalDistributed) differ in performance by as much as 5x.  for example

Node1Local
```

SELECT
    arrayJoin(B) AS level1,
    uniq(A)
FROM 
(
    SELECT
        B,
        A
    FROM Node1Local
    WHERE (A < 1000000) AND hasAny(B, [11, 12, 13, 14, 15, 16, 17, 18, 19])
)
GROUP BY level1
FORMAT Null

Query id: 19e583db-c68d-430f-a925-add81dd7e7a7

Ok.

0 rows in set. Elapsed: 7.386 sec. Processed 1.00 million rows, 1.91 GB (135.50 thousand rows/s., 258.56 MB/s.)
```

Node1LocalDistributed 
```
SELECT
    arrayJoin(B) AS level1,
    uniq(A)
FROM 
(
    SELECT
        B,
        A
    FROM Node1LocalDistributed
    WHERE (A < 1000000) AND hasAny(B, [11, 12, 13, 14, 15, 16, 17, 18, 19])
)
GROUP BY level1
FORMAT Null

Query id: a193883c-7cfc-467b-90b0-274814604405

Ok.

0 rows in set. Elapsed: 33.781 sec. Processed 1.00 million rows, 1.91 GB (29.63 thousand rows/s., 56.53 MB/s.)

```

I am using v 21.6. On real data which this eg. is based on but with more columns, performance is slow as much as 10x

**Comment by alexey-milovidov** [comment]
Remove subquery:

```
    SELECT
        arrayJoin(B) AS level1,
        uniq(A)
    FROM Node1LocalDistributed
    WHERE (A < 1000000) AND hasAny(B, [11, 12, 13, 14, 15, 16, 17, 18, 19])
    GROUP BY level1
    FORMAT Null
```

**Comment by shawel** [comment]
Thanks @alexey-milovidov I noticed it works if I remove sub-query. But this is a contrived example where removing it as a sub-query is not an option for us for the time being. Is there a reason why it is slower? Thank you

**Comment by amosbird** [comment]
> Thanks @alexey-milovidov I noticed it works if I remove sub-query. But this is a contrived example where removing it as a sub-query is not an option for us for the time being. Is there a reason why it is slower? Thank you

It's the limitation of how ClickHouse handles subqueries and distributed queries. Subqueries are treated as an local table and the aggregation will only be executed on the initiator instead of distributed GROUP BY.

It's better to always place some distributed table on the leftmost side. Alternatively, you can rewrite the query like this:

```

SELECT
    arrayJoin(B) AS level1,
    uniq(A)
FROM 
cluster(
  your_fancy_cluster_name,
  view(
    SELECT
        B,
        A
    FROM Node1Local
    WHERE (A < 1000000) AND hasAny(B, [11, 12, 13, 14, 15, 16, 17, 18, 19])
  )
)
GROUP BY level1
FORMAT Null

```

**Comment by shawel** [comment]
Ok great thanks! i will try it..
