### ISSUE TITLE
Bug report: Strange "Missing columns" while processing SELECT query

### ISSUE THREAD

**Issue by JZuming** [ClickHouse/ClickHouse#25319]
**Describe the bug**

I used my fuzzing tool to test ClickHouse (v21.5.6.6-stable), and found that it returned stange error message when processing a sql.

**Does it reproduce on recent release?**

v21.5.6.6-stable

**How to reproduce**

* ClickHouse server version: v21.5.6.6-stable
* Installation: 
1. mkdir build; cd build
2. cmake ..  \
        -DCMAKE_BUILD_TYPE=Debug     \
        -DENABLE_CLICKHOUSE_ALL=OFF     \
        -DENABLE_CLICKHOUSE_SERVER=ON     \
        -DENABLE_CLICKHOUSE_CLIENT=ON     \
        -DENABLE_LIBRARIES=OFF     \
        -DUSE_UNWIND=ON     \
        -DENABLE_UTILS=OFF     \
        -DENABLE_TESTS=OFF -DSANITIZE=address
3. sudo make install
* Test command: 
```
1. clickhouse-server &

2. clickhouse-client --query '
create table t_dc ( 
c_nm7 INTEGER NOT NULL,
c_wmsuhiiaw INTEGER ,
c_ncc INTEGER ,
c_x4 INTEGER ,
c_d TEXT ,
c_dlhkvu TEXT NOT NULL,
c_h54cg87j INTEGER ,
c_bi_88h TEXT ,
c_je8pz6rn TEXT NOT NULL,
primary key(c_nm7)
) engine = MergeTree();'

3. clickhouse-client --query '
select  max(
  ref_0.c_x4 < (
      select
            58 as c0
          from
            t_dc as ref_13
          where (ref_13.c_x4 > ref_13.c_wmsuhiiaw)
            or (ref_13.c_ncc < ref_0.c_x4)
          )
    ) as c1
from
  t_dc as ref_0;'
```

**Expected behavior**

Normally run without any error message

**Error message and/or stacktrace**

```
Received exception from server (version 21.5.6):
Code: 47. DB::Exception: Received from localhost:9000. DB::Exception: Missing columns: 'ref_0.c_x4' while processing query: 'SELECT 58 AS c0 FROM t_dc AS ref_13 WHERE (c_x4 > c_wmsuhiiaw) OR (c_ncc < ref_0.c_x4)', required columns: 'c_x4' 'c_wmsuhiiaw' 'c_ncc' 'ref_0.c_x4', maybe you meant: ['c_axh']: While processing (SELECT 58 AS c0 FROM t_dc AS ref_13 WHERE (ref_13.c_x4 > ref_13.c_wmsuhiiaw) OR (ref_13.c_ncc < ref_0.c_x4)) AS _subquery1342: While processing c_x4 < ((SELECT 58 AS c0 FROM t_dc AS ref_13 WHERE (ref_13.c_x4 > ref_13.c_wmsuhiiaw) OR (ref_13.c_ncc < ref_0.c_x4)) AS _subquery1342): While processing max(c_x4 < ((SELECT 58 AS c0 FROM t_dc AS ref_13 WHERE (ref_13.c_x4 > ref_13.c_wmsuhiiaw) OR (ref_13.c_ncc < ref_0.c_x4)) AS _subquery1342)) AS c1.
```

**Additional context**

It seems to be a bug since ref_0.c_x4 truly exists.

**Comment by hexiaoting** [comment]
No, it's not a bug.
```
        SELECT 58 AS c0
        FROM t_dc AS ref_13
        WHERE (ref_13.c_x4 > ref_13.c_wmsuhiiaw) OR (ref_13.c_ncc < ref_0.c_x4)
```
This subquery references to `ref_0` but subquery's `from` clause doesn't have it.

**Comment by JZuming** [comment]
@hexiaoting 
Thanks for your reply.  It seems that ClickHouse is different, because other DBMSs (such as sqlite, mysql, mariadb) support that subquery can reference the table used in the parent query.

> ```
>         SELECT 58 AS c0
>         FROM t_dc AS ref_13
>         WHERE (ref_13.c_x4 > ref_13.c_wmsuhiiaw) OR (ref_13.c_ncc < ref_0.c_x4)
> ```
> 
> This subquery references to `ref_0` but subquery's `from` clause doesn't have it.

**Comment by amosbird** [comment]
I think it's worth doing by extending `global with` a little bit.

**Comment by amosbird** [comment]
I was wrong. This is correlated subqueries and it's not supported yet. https://github.com/ClickHouse/ClickHouse/issues/6697

**Comment by alexey-milovidov** [comment]
@JZuming So, it's not a bug but a missing feature.

We found your fuzzer very useful, because it also can find real issues in code like #25411
So, if you can filter out this type of issues (unsupported correlated subqueries) and continue searching others, it will be very appreciated.
