### ISSUE TITLE
Kafka _timestamp / _timestamp_ms not working?

### ISSUE THREAD

**Issue by mzealey** [ClickHouse/ClickHouse#25322]
**Describe the bug**

Appears that _timestamp and _timestamp_ms virtual columns are returning 0 for kafka. Perhaps it is somehow due to JSONEachRow format?

Issue is in docker 21.6.4.26 and 21.2.2.8 at least.

I'm using amazon MSK 2.6.1

**How to reproduce**

```
create table kafka ( name String ) ENGINE=Kafka() SETTINGS kafka_broker_list = '...', kafka_topic_list = 'test-events', kafka_group_name='test', kafka_format='JSONEachRow';
create table t (time DateTime64(3), name String) ENGINE=MergeTree() ORDER BY tuple();
create materialized view kafka_mv to t AS select _timestamp_ms, name FROM kafka;
```

```
echo '{"name":"test"}' | bin/kafka-console-producer.sh ...
```

Clickhouse table just looks like:

```
┌────────────────────time─┬─name─┐
│ 1970-01-01 00:00:00.000 │ test │
...
└─────────────────────────┴──────┘
```

If checking with kafka consumer:

```
bin/kafka-console-consumer.sh ... --from-beginning --property print.timestamp=true
CreateTime:1623839664050        {"name":"test"}
CreateTime:1623839989619        {"name":"test"}
CreateTime:1623840562909        {"name":"test"}
CreateTime:1623840285113        {"name":"test"}
```

I see the same with _timestamp col

**Comment by filimonov** [comment]
Mapping of columns in mv happens by names, not by positions.

So that should help:
```
create materialized view kafka_mv to t AS select _timestamp_ms as time, name FROM kafka;
```

**Comment by mzealey** [comment]
Gah yes that fixed it. Normally I thought there were errors when creating a mv or inserting into it like this, but I did not see anything on console or in the logs :-/
