### ISSUE TITLE
Stress test: Segfault without stacktrace

### ISSUE THREAD

**Issue by tavplubix** [ClickHouse/ClickHouse#25320]
https://clickhouse-test-reports.s3.yandex.net/25305/c873714698724001296c78f3db7b0b3dd6d1572b/stress_test_(thread).html#fail1

```
2021.06.16 02:00:13.450333 [ 404 ] {} <Fatal> Application: Child process was terminated by signal 11.
```
Without stacktrace or any other `Fatal` messages.

Probably related to libunwind: https://gist.github.com/nvartolomei/f6035732911a4ea74e5edf72a9da207e

**Comment by alexey-milovidov** [comment]
@kitaisreal has fixed libunwind and we don't have this issue anymore.
