### ISSUE TITLE
Does COLUMNS function work on materialized columns ?

### ISSUE THREAD

**Issue by shawel** [ClickHouse/ClickHouse#25337]
Is this expected behaviour?

**Comment by alexey-milovidov** [comment]
Yes, see the setting `asterisk_include_materialized_columns`.

**Comment by shawel** [comment]
Ok thank you @alexey-milovidov

**Comment by Oberonhive** [comment]
> Yes, see the setting `asterisk_include_materialized_columns`.

Seems it works only for asterisk but not with COLUMNS function.
```
create table tbl(
	a String,
	b String MATERIALIZED a
)ENGINE = MergeTree
PRIMARY KEY tuple();
```


This returns both columns:
```
select * 
  from tbl
settings asterisk_include_materialized_columns=1;
```


But this throws an error:
```
select COLUMNS('b')
  from tbl
settings asterisk_include_materialized_columns=1;
```
`Empty list of columns in SELECT query. (EMPTY_LIST_OF_COLUMNS_QUERIED) (version 22.6.1.1985 (official build))`


@alexey-milovidov maybe i'm doing something wrong?
