### ISSUE TITLE
[BUG] Return format on execute ON CLUSTER query.

### ISSUE THREAD

**Issue by jonatasfreitasv** [ClickHouse/ClickHouse#2538]
When run this query for example:
`CREATE TABLE default.table_name ON CLUSTER '{cluster_name}'`

The return is not `JSON`, is `text/plain`.

Like:
```
xyz_1.com	9000	0		1	0
xyz_2.com	9000	0		0	0
```

**Comment by alexey-milovidov** [comment]
If you specify FORMAT JSON in a query, it will return the result in specified format:

```
CREATE TABLE default.table_name ON CLUSTER 'test_shard_localhost' (x UInt32) ENGINE = Memory FORMAT JSON
```
