### ISSUE TITLE
Support `grant replace` SQL statement

### ISSUE THREAD

**Issue by godliness** [ClickHouse/ClickHouse#25395]
**Use case**

Try think we need develop a web portal to manage privileges of clickhouse cluster which has thounsands nodes，everyone has its own privileges，so we need a master just like the web portal to push the final state privileges to every node，web portal need store the cluster privileges data into database，so we have to generate the delta privileges sql after admin change the privileges and run them on every node，that's easy lead to data inconsistent when some nodes privileges are differently，if we support grant replace，we just get the final state from database and replace all privileges
for every node.

We can not easily to revoke all and grant privileges, because the incoming and processing requests would has no all privileges for a moment.

grant replace need calculate the differential set and do add or remove privileges on resource for user.

**Describe the solution you'd like**
Just add  `grant replace` and do not need to restart `clickhouse-server` it will be effected

**SYNTAX**

`grant replace select on db.table to user,role`
`grant replace role1 to user,role`

**Comment by Cas-pian** [comment]
This is a useful feature

**Comment by vitlibar** [comment]
It seems a bit unclear to me. Could you explain for example what the following statement

```
GRANT REPLACE SELECT ON mydb.mytable TO john
```

is going to do?

**Comment by Cas-pian** [comment]
> It seems a bit unclear to me. Could you explain for example what the following statement
> 
> ```
> GRANT REPLACE SELECT ON mydb.mytable TO john
> ```
> 
> is going to do?

It's a bit like `CREATE OR REPLACE TABLE`, it drop old privileges and replace it by new privileges, cause there might be two much privilges that need to be revoked, and is too long for the sql.

**Comment by vitlibar** [comment]
`CREATE OR REPLACE TABLE` is like two commands `DROP TABLE IF EXISTS` and then `CREATE TABLE` but in one command. Do you mean `GRANT REPLACE` should work as `REVOKE <something>` and after that `GRANT <something>`?

So

```
GRANT REPLACE SELECT ON mydb.mytable TO john
```

should work like

```
REVOKE SELECT ON mydb.mytable FROM john;
GRANT SELECT ON mydb.mytable TO john;
```

Is that what you mean?

**Comment by Cas-pian** [comment]
Yes, correct. Thus we don't need to revoke old privileges one by one, just drop them and grant with new privileges.

**Comment by vitlibar** [comment]
You can revoke everything with one command

```
REVOKE ALL ON *.* FROM john;
```

and then you can grant what you need.

**Comment by Cas-pian** [comment]
@vitlibar Yes, but this might affect the sql which is current using some privileges, if grant replace is supported, we can do these things in one sql (since there's no transaction in ck)
cc @godliness

**Comment by vitlibar** [comment]
If I understand your idea correctly after implementing this feature you will have to write all privileges in a single command, like this

```
GRANT REPLACE SELECT(x,y) ON mydb1.mytable1, INSERT(z) ON mydb2.mytable2, CREATE, DROP ON mydb3.* TO john;
```

And if you write that sequentially:
```
GRANT REPLACE SELECT(x,y) ON mydb1.mytable1 TO john;
GRANT REPLACE INSERT(z) ON mydb2.mytable2 TO john;
GRANT REPLACE CREATE ON mydb3.* TO john;
GRANT REPLACE DROP ON mydb3.* TO john;
```
you'll get a completely wrong result (`john will be left with only `CREATE, DROP ON mydb3.*` access rights).

**Comment by Cas-pian** [comment]
It seems CH has already support grant multi db privileges to user in a single command.
`GRANT select on db1*, insert on db2.* to john`.
  
The point is that if current privilege is `select, insert on db1.tb1`, and execute `grant replace select on db1.tb1`, the `select` should never be revoked at any time, cause it might be using by an incoming request.

**Comment by vitlibar** [comment]
> The point is that if current privilege is select, insert on db1.tb1, and execute grant replace select on db1.tb1, the select should never be revoked at any time, cause it might be using by an incoming request.

Ok, I understood. This should be a useful feature.

**Comment by vitlibar** [comment]
> It seems CH has already support grant multi db privileges to user in a single command.
GRANT select on db1*, insert on db2.* to john

That's right, so implementing of this feature seems to be not very difficult.

**Comment by godliness** [comment]
@vitlibar thanks for your attention.
@Cas-pian thanks for your explain.
try think we need develop a web portal to manage privileges of clickhouse cluster which has thounsands nodes，everyone has its own privileges，so we need a master just like the web portal to push the final state privileges to every node，web portal need store the cluster privileges data into database，so we have to generate the delta privileges sql after admin change the privileges and run them on every node，that's easy lead to data inconsistent when some nodes privileges are differently，if we support grant replace，we just get the final state from database and replace all privileges
for every node. 

We can not easily to revoke all and grant, cause incoming and processing request would has no privileges.

grant replace need calculate the differential set and do add or remove privileges on resource for user

**Comment by Cas-pian** [comment]
@vitlibar Bingo.
@godliness similar use case, very clear explaination 👍

**Comment by Cas-pian** [comment]
@vilibar, I have finished this feature [here](https://github.com/ClickHouse/ClickHouse/issues/25395), PTAL
