### ISSUE TITLE
Support for DISTINCT ON (columns)

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#25404]
For people who get used to Postgres.

**Describe the solution you'd like**
`SELECT DISTINCT ON (a, b, ...) a, b, c, ...`
is equivalent to
`SELECT a, b, c... LIMIT 1 BY a, b, ...`

**Comment by TszKitLo40** [comment]
Can you give me some advice for solving this issue?

**Comment by alexey-milovidov** [comment]
It can be solved completely within parser (see `ParserSelectQuery.h/cpp`).

If `DISTINCT ON (...)` is parsed in a query, create an AST similarly to `LIMIT BY`.
If both `DISTINCT ON (...)` and `LIMIT BY` are present, the query should not be parsed.

**Comment by TszKitLo40** [comment]
> It can be solved completely within parser (see `ParserSelectQuery.h/cpp`).
> 
> If `DISTINCT ON (...)` is parsed in a query, create an AST similarly to `LIMIT BY`.
> If both `DISTINCT ON (...)` and `LIMIT BY` are present, the query should not be parsed.

Should `DISTINCT ON (...)` be parsed like https://github.com/ClickHouse/ClickHouse/blob/master/src/Parsers/ParserSelectQuery.cpp#L259? It seems that this part is for `LIMIT BY`.

**Comment by alexey-milovidov** [comment]
I can be parsed similarly, the contents in parens should be parsed as expression list:

```
if (!exp_list.parse(pos, limit_by_expression_list, expected))
    return false;
```

**Comment by TszKitLo40** [comment]
OK, I will try to solve this issue. After finishing the parser, can I filed the PR first and let you have a look? And I am not sure where should the tests be added?

**Comment by alexey-milovidov** [comment]
Sure, let's do it!

**Comment by alexey-milovidov** [comment]
Tests can be added in `tests/queries/0_stateless`

**Comment by TszKitLo40** [comment]
I am compiling ClickHouse on Mac. But `no member named 'aligned_alloc' in the global namespace` error is thrown, and I have run the following command `cmake -DCMAKE_C_COMPILER=$(brew --prefix llvm)/bin/clang -DCMAKE_CXX_COMPILER=$(brew --prefix llvm)/bin/clang++ -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
cmake --build . --config RelWithDebInfo`, how can I fix it?

**Comment by TszKitLo40** [comment]
I think it should be parsed like this `if (s_distinct_on.ignore(pos, expected)) {
            if (!exp_list.parse(pos, limit_by_expression_list, expected))
                return false;
        }` but how can we parse `limit_by_lenth`, it seems that there is no keyword about `limit by ` in `SELECT a, b, c... LIMIT 1 BY a, b, ...`, so we can't parse limit by like 'Limit By'.

**Comment by alexey-milovidov** [comment]
DISTINCT ON ... is equivalent to LIMIT 1 BY ...
So, the limit_length will be simply set to 1.

**Comment by TszKitLo40** [comment]
> DISTINCT ON ... is equivalent to LIMIT 1 BY ...
> So, the limit_length will be simply set to 1.
Yes, I think so. But `limit_by_length` is an ASTPtr which points to IAST, it seems that it can't be directly set to 1.

**Comment by TszKitLo40** [comment]
@alexey-milovidov Can you give me some advice how to set the limit_length to 1? I can't find out the function which can be used to.

**Comment by alexey-milovidov** [comment]
`std::make_shared<ASTLiteral>` should be created with value 1.
