### ISSUE TITLE
A common way to send and store prometeus metrics

### ISSUE THREAD

**Issue by antonyc** [ClickHouse/ClickHouse#25401]
Hi! Is there a common way to store and retrieve prometeus metrics in clickhouse via remote_write, remote_read? I see a bunch of abandoned projects in github and no good docs for brining up a custom installation to satisfy my needs.
Thank you in advance!

**Comment by MaxWk** [comment]
Clickhouse has integrated prometheus, only need to configure to open it, there is another way is through clickhouse-exporter。

**Comment by Farfaday** [comment]
https://clickhouse.tech/docs/en/operations/server-configuration-parameters/settings/#server_configuration_parameters-prometheus

**Comment by antonyc** [comment]
@MaxWk this is about exporting internal CH metrics to some prometeus, write? Same as exporter.

What I mean, is using CH as a Storage for Prometeus, which a called [remote write](https://prometheus.io/docs/operating/configuration/#remote_write) and [remote read](https://prometheus.io/docs/operating/configuration/#remote_read). So as prometeus itself (and internal TSDB) is not good for using as a long-term storage, it seems find using CH with GraphiteMergeTree. But to do that, one should be able to configure prometeus to use CH as a storage through remote read/write options.

**Comment by Slach** [comment]
@antonyc unfortunately only https://github.com/Percona-Lab/PromHouse, but it's a not maintained project right now

**Comment by MaxWk** [comment]
> @MaxWk this is about exporting internal CH metrics to some prometeus, right? Same as exporter.
> 
> What I mean, is using CH as a Storage for Prometeus, which a called [remote write](https://prometheus.io/docs/operating/configuration/#remote_write) and [remote read](https://prometheus.io/docs/operating/configuration/#remote_read). So as prometeus itself (and internal TSDB) is not good for using as a long-term storage, it seems find using CH with GraphiteMergeTree. But to do that, one should be able to configure prometeus to use CH as a storage through remote read/write options.



> What I mean, is using CH as a Storage for Prometeus, which a called [remote write](https://prometheus.io/docs/operating/configuration/#remote_write) and [remote read](https://prometheus.io/docs/operating/configuration/#remote_read). So as prometeus itself (and internal TSDB) is not good for using as a long-term storage, it seems find using CH with GraphiteMergeTree. But to do that, one should be able to configure prometeus to use CH as a storage through remote read/write options.

Sorry, I got it wrong. Your needs seem very reasonable, and it seems that time series data is indeed suitable for storage in clickhouse.

**Comment by antonyc** [comment]
@den-crane but are there any plans for support? What is the common way of requesting a feature in CH?

**Comment by den-crane** [comment]
>What is the common way of requesting a feature in CH?

Create an issue as Feature Request ? 
https://github.com/ClickHouse/ClickHouse/issues/new/choose  Feature request / Suggest an idea for ClickHouse

>but are there any plans for support?

not sure, I think it was in extended roadmap before, current roadmap https://github.com/ClickHouse/ClickHouse/issues/17623

Did you try https://github.com/VictoriaMetrics/VictoriaMetrics instead of Clickhouse ?

**Comment by antonyc** [comment]
No, I didn't try victoria metrics :) ok, thanks.
