### ISSUE TITLE
JSONExtract - RawString type for parsing

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#25414]
I parse a lot of fields using a single call of JSONExtact. 

But some of the fields have some 'custom' / 'unstructured' json data, which I just want to extract in a 'json' field - very similar to JSONExtractRaw but in the same/single parsing pass.

i.e. smth like 
```
JSONExtact(json, 'Tuple(id String, score Float32, details RawString)')
```

**Comment by amosbird** [comment]
I've done a slightly different implementation:

If json node is of string type, extract it as string, or else as raw string.

**Comment by alexey-milovidov** [comment]
@amosbird It makes sense. Let's do it.

**Comment by amosbird** [comment]
。。
