### ISSUE TITLE
view optimisation

### ISSUE THREAD

**Issue by morozovsk** [ClickHouse/ClickHouse#25418]
**Describe the situation**
`CREATE VIEW v1 AS SELECT * FROM t1 FINAL`
`SELECT * FROM v1 WHERE date = today()` is too slow.

**Expected performance**
If a column in view and in table is the same - it needs to do optimisation for passing condition from out of view inside view. like:
`SELECT * FROM (SELECT * FROM t1 WHERE date = today())`

**Comment by skirpichenok** [comment]
FYI When I defined ORDER BY inside a View definition it works ok and use index. But If I definied a View without OREDR BY and then I query that View like "select * from MY_VIEW OREDR BY id" then it works slower and does not use index [sometimes memory can be over. probably it depends on amount of data I operate]

probably it is similar optimization that needs to be added - for passing ORDER BY from out of view inside view
