### ISSUE TITLE
Increase flush speed to kafka table

### ISSUE THREAD

**Issue by shaon-chowdhury** [ClickHouse/ClickHouse#25416]
What setting is used to adjust the flush latency for kafka tables? I have noticed that my kafka tables requires 7500ms to flush even after changing all the default flush properties in config.xml

**Comment by UnamedRus** [comment]
https://kb.altinity.com/altinity-kb-integrations/altinity-kb-kafka/altinity-kb-kafka-main-parsing-loop

You need to change: kafka_flush_interval_ms setting
You can do it on Kafka table level.

**Comment by shaon-chowdhury** [comment]
@UnamedRus thank you! Added these at the kafka table level
