### ISSUE TITLE
auto FINAL for select from ReplacingMergeTree/AggregatingMergeTree

### ISSUE THREAD

**Issue by morozovsk** [ClickHouse/ClickHouse#25415]
**Use case**
I use metabase and another software for visualizing data from clickhouse for end users. Now I need create VIEW like `select from t FINAL` for all ReplacingMergeTree/AggregatingMergeTree tables. It works but sometime it is slow and always it is uneffective. I cant add FINAL to select query because metabase/e.t.c. generate sql by own. 

**Describe the solution you'd like**
Please add option for server or for table like "auto final".

**Describe alternatives you've considered**
I can create proxy and change sql query on the fly by adding FINAL to all queries but it is not convenient.

**Additional context**
ENGINE MaterializeMySQL works with FINAL by default and it is expected behavior but ReplacingMergeTree returns old duplicates and it is unexpected. Moreover, I can't even change the behavior to the expected.

**Comment by alexey-milovidov** [comment]
#40945

**Comment by Algunenano** [comment]
It was implemented
