### ISSUE TITLE
Add functions `bin` and `unbin`

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#25422]
**Use case**

Viewing binary data such as bitmasks, hashes, internal representation of IEEE-754 numbers, etc.
Mostly for debugging.

**Describe the solution you'd like**

Similar to `hex`/`unhex`.

`bin` - returns a string with `0` and `1`. Bits are in "human" order, most significant first. Most significant zero bits are not printed (except the case with single zero).

**Describe alternatives you've considered**

Now I have to run interactive `python` from command line, but I will be more happy using ClickHouse.

**Caveats**

The name `bin` may suggest that the function will "split data into bins" but it is completely unrelated.

**Comment by TszKitLo40** [comment]
Should `bin` and `unbin` only accepts `int` or `long`?

**Comment by alexey-milovidov** [comment]
Similarly to `hex`, they also accept String, FixedString, Float...

`bin` from String and FixedString returns bits starting from the most significant bit of the first byte to the least significant bit of the last byte. In contrast to integers, leading zero bits are included. Floats are treated as their byte representation in memory.

`unbin` from FixedString returns FixedString and for other types - always returns String.

PS. It should work similarly to `hex`/`unhex`.

**Comment by TszKitLo40** [comment]
In `hex.h`, which functions can be used in the sql directly?

**Comment by alexey-milovidov** [comment]
See `FunctionsCoding.h/cpp`, `FunctionHex`, `FunctionUnhex`

**Comment by alexey-milovidov** [comment]
Tests:

```
bin(0) = '0'
bin(1) = '1'
bin(10) = '1010'
bin(127) = '1111111'
bin(255) = '11111111'
bin('0') = '00110000'
bin('10') = '0011000100110000'
```

**Comment by TszKitLo40** [comment]
But the implementation in `FunctionHex` and `FunctionUnhex` is a little complicated and I can't understand it clearly.
