### ISSUE TITLE
Improve logging for "Not executing log entry ... is greater than the current maximum" errors

### ISSUE THREAD

**Issue by siradjev** [ClickHouse/ClickHouse#25445]
(you don't have to strictly follow this form)

**Use case**
There are many scenarios when clickhouse goes into infinite error saying: 
```
Not executing log entry MUTATE_PART for part xxxx-421_0_36_2_111 because source parts size (324.06 MiB) is greater than the current maximum (0.00 B)

Not executing log entry MERGE_PART for part xxxx-421_0_36_2_111 because source parts size (324.06 MiB) is greater than the current maximum (0.00 B)
```

In both of those cases this error is typically caused not by disk space, but by number of available threads in background pool, and it is misleading and not providing clear picture of what is problematic, unless there is configured metrics monitoring for clickhouse. 

**Describe the solution you'd like**
Improve the error to include variables used to calculate maximum size, something like below:
```
Not executing log entry MUTATE_PART for part xxxx-421_0_36_2_111 because source parts size (324.06 MiB) is greater than the current maximum (0.00 B). background_pool_size=16; busy_threads_in_pool=9; number_of_free_entries_in_pool_to_execute_mutation=10; disk_space=43TiB; 

Not executing log entry MERGE_PART for part xxxx-421_0_36_2_111 because source parts size (324.06 MiB) is greater than the current maximum (0.00 B).  background_pool_size=16; busy_threads_in_pool=9; max_bytes_to_merge_at_min_space_in_pool=16; max_bytes_to_merge_at_max_space_in_pool=1; number_of_free_entries_in_pool_to_lower_max_size_of_merge=8; disk_space=22TiB.
```

**Describe alternatives you've considered**
No alternatives, and any troubleshooting takes forever and leads to many assumptions. 

**Additional context**

**Comment by alexey-milovidov** [comment]
Maybe #22381 and #25165 will help.

**Comment by siradjev** [comment]
> Maybe #22381 and #25165 will help.

Yes, they would reduce amount of problem, this FR is to simply provide better troubleshooting means for admins.

**Comment by alexey-milovidov** [comment]
#22381 has been implemented and the issue should not be relevant anymore.
