### ISSUE TITLE
php mysqli client Authentication for user default failed

### ISSUE THREAD

**Issue by 1995hzczjut** [ClickHouse/ClickHouse#25451]
1. When I use the MySQL command line(mysql -h10.188.41.8 -udefault -psftcwl -P9004 default), it's OK.
2021.06.18 01:19:15.618760 [ 5042 ] {} <Trace> MySQLHandlerFactory: MySQL connection. Id: 25. Address: [::ffff:10.188.41.8]:49866
2021.06.18 01:19:15.619694 [ 5042 ] {} <Trace> MySQLHandler: Sent handshake
2021.06.18 01:19:15.619854 [ 5042 ] {} <Trace> MySQLHandler: payload size: 91
2021.06.18 01:19:15.619906 [ 5042 ] {} <Trace> MySQLHandler: Capabilities: 33531533, max_packet_size: 16777216, character_set: 33, user: default, auth_response length: 20, database: default, **auth_plugin_name: mysql_native_password**
2021.06.18 01:19:15.620532 [ 5042 ] {} <Trace> ContextAccess (default): Settings: readonly=0, allow_ddl=true, allow_introspection_functions=false
2021.06.18 01:19:15.620604 [ 5042 ] {} <Trace> ContextAccess (default): List of all grants: GRANT ALL ON *.* WITH GRANT OPTION
2021.06.18 01:19:15.620615 [ 5042 ] {} <Trace> ContextAccess (default): List of all grants including implicit: GRANT ALL ON *.* WITH GRANT OPTION
2021.06.18 01:19:15.620682 [ 5042 ] {} <Debug> MySQLHandler: Authentication for user default succeeded.

2. Then use PHP MySQL extension, authorization failed(all parameters are the **same** as the above command line), the difference between logs is empty auth_ plugin_ name
2021.06.18 01:38:07.660049 [ 5042 ] {} <Trace> MySQLHandlerFactory: MySQL connection. Id: 26. Address: [::ffff:10.188.41.8]:49888
2021.06.18 01:38:07.660486 [ 5042 ] {} <Trace> MySQLHandler: Sent handshake
2021.06.18 01:38:07.661697 [ 5042 ] {} <Trace> MySQLHandler: payload size: 68
2021.06.18 01:38:07.661759 [ 5042 ] {} <Trace> MySQLHandler: Capabilities: 172557, max_packet_size: 1073741824, character_set: 33, user: hzchzc, auth_response length: 20, database: default, **auth_plugin_name:** 
2021.06.18 01:38:07.668111 [ 5042 ] {} <Error> MySQLHandler: Authentication for user hzchzc failed.
2021.06.18 01:38:07.668323 [ 5042 ] {} <Error> MySQLHandler: DB::Exception: Received packet with wrong sequence-id: 0. Expected: 3.

**Comment by 1995hzczjut** [comment]
Which ClickHouse server version to use
v21.6.3.14-stable

**Comment by morozovsk** [comment]
mysqli is deprecated in php 8. try to use pdo instead.

**Comment by alexey-milovidov** [comment]
Most likely we support the `mysql_native_password` authentication but not some other authentication that PHP is using.
