### ISSUE TITLE
Questions about using populate in materialized view

### ISSUE THREAD

**Issue by shadowDy** [ClickHouse/ClickHouse#25457]
Why is it that the official document does not recommend using the explode parameter, just because the new data cannot be added to the view during import? Besides, are there any other questions?

Can I use this parameter for offline scheduled data import?

For loading stock data to new materialized view, is there any suggested solution;

**Comment by morozovsk** [comment]
>just because the new data cannot be added to the view during import?

yes
>Besides, are there any other questions?

no
>Can I use this parameter for offline scheduled data import?

yes
>For loading stock data to new materialized view, is there any suggested solution;

What do you mean?

**Comment by shadowDy** [comment]
@morozovsk It should be a high-frequency demand scenario to build materialized view for the stored data. In the cluster of real-time import, how to gracefully solve the problem of materialized view for the stored data

**Comment by morozovsk** [comment]
when you create/recreate materialized view just use TO to existing table. so when you need to recreate materialized view (for example if you need to add new column) you can just drop materialized view and create new one instead and your data will be saved at existing table.

**Comment by shadowDy** [comment]
> when you create/recreate materialized view just use TO to existing table. so when you need to recreate materialized view (for example if you need to add new column) you can just drop materialized view and create new one instead and your data will be saved at existing table.

Does this mean that when I create materialized views with to exists table syntax, I will automatically select materialized views and import new views? Is there a performance problem with this one? Is it suitable for clusters imported in real time?

**Comment by morozovsk** [comment]
you need to select data only from existted table not from mat view. mat view is just a insert trigger. so when you create/recreate materialized view you just create/recreate insert trigger.

**Comment by den-crane** [comment]
Check this https://den-crane.github.io/Everything_you_should_know_about_materialized_views_commented.pdf 
slides 9, 34-38
