### ISSUE TITLE
Drop Table hang on forever

### ISSUE THREAD

**Issue by feihengye** [ClickHouse/ClickHouse#25450]
**description**
![image](https://user-images.githubusercontent.com/77636494/122496363-38794500-d01e-11eb-892f-a23b3aab575a.png)

As the pic, when exec the DROP table DDL, will hang on  DB::StorageMergeTree::shutdown() .

DDL: DROP TABLE db.local ON CLUSTER clickhouse_base_platform_1_replica

**How to reproduce**
Sorry，I don't know, so far.

**Which ClickHouse server version to use**
21.3.3.14

**Which interface to use, if matters**
Mysql connector

**Comment by alexey-milovidov** [comment]
The version 21.3.3 does not contain all the patches. Should be updated to 21.3.12 or 21.6.3.

**Comment by nikitamikhaylov** [comment]
This issue is already fixed and will be available in next patch release (21.3.13)

**Comment by feihengye** [comment]
@nikitamikhaylov 
I did not find the 21.3.13, the 21.3 max version is v21.3.9.83-lts.
![image](https://user-images.githubusercontent.com/77636494/122713364-286c9a00-d298-11eb-91a3-dde929f181ba.png)

**Comment by feihengye** [comment]
link bug: https://github.com/ClickHouse/ClickHouse/issues/25523
