### ISSUE TITLE
ninja failed:

### ISSUE THREAD

**Issue by powerpistn** [ClickHouse/ClickHouse#25461]
i use **docker run -it ubuntu:20.04 /bin/bash** to create a container,enter the container,my steps are as follow:

    ` apt-get update
    apt-get -y  install git cmake python ninja-build wget nano sudo gnupg
    nano  /etc/apt/sources.list \

    #### add sources into /etc/apt/sources.list
    deb http://apt.llvm.org/focal/ llvm-toolchain-focal main
    deb-src http://apt.llvm.org/focal/ llvm-toolchain-focal main
    # 11
    deb http://apt.llvm.org/focal/ llvm-toolchain-focal-11 main
    deb-src http://apt.llvm.org/focal/ llvm-toolchain-focal-11 main
    # 12
    deb http://apt.llvm.org/focal/ llvm-toolchain-focal-12 main
    deb-src http://apt.llvm.org/focal/ llvm-toolchain-focal-12 main
######
    wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
    apt-get update
    apt-get upgrade -y
    apt-get -y install clang-11
    export CC=clang-11
    export CXX=clang++-11
    git clone --recursive https://github.com/ClickHouse/ClickHouse.git
    cd ClickHouse 
    mkdir build 
    cd build
    cmake .. 
    ninja`

In the last step, I encountered the following error

`root@925eb7dc117f:/ClickHouse/build# ninja
[0/2] Re-checking globbed directories...
[1233/9765] Building CXX object contrib/hyperscan-cmake/CMakeFiles/hyperscan.dir/__/hyperscan/src/nfagraph/ng_repeat.cpp.o
FAILED: contrib/hyperscan-cmake/CMakeFiles/hyperscan.dir/__/hyperscan/src/nfagraph/ng_repeat.cpp.o 
/usr/bin/clang++-11  -DBOOST_ASIO_STANDALONE=1 -DSTD_EXCEPTION_HAS_STACK_TRACE=1 -DUSE_HYPERSCAN=1 -I../contrib/sentry-native/include -I../contrib/hyperscan-cmake/common -I../contrib/hyperscan/include -I../contrib/hyperscan-cmake/x86_64 -I../base/glibc-compatibility/memcpy -isystem ../contrib/hyperscan/src -isystem ../contrib/libcxx/include -isystem ../contrib/libcxxabi/include -isystem ../contrib/libunwind/include -isystem ../contrib/boost -isystem ../contrib/libc-headers/x86_64-linux-gnu -isystem ../contrib/libc-headers -fdiagnostics-color=always -fsized-deallocation  -gdwarf-aranges -msse4.1 -msse4.2 -mpopcnt -fasynchronous-unwind-tables -falign-functions=32   -Wall -Wno-unused-command-line-argument  -fdiagnostics-absolute-paths -fexperimental-new-pass-manager -Werror -w -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -g -O0 -g3 -ggdb3 -fno-inline  -D_LIBCPP_DEBUG=0   -D OS_LINUX -g0 -mno-avx -mno-avx2 -march=corei7 -O2 -fno-strict-aliasing -fno-omit-frame-pointer -fvisibility=hidden -fno-sanitize=undefined -nostdinc++ -std=gnu++2a -MD -MT contrib/hyperscan-cmake/CMakeFiles/hyperscan.dir/__/hyperscan/src/nfagraph/ng_repeat.cpp.o -MF contrib/hyperscan-cmake/CMakeFiles/hyperscan.dir/__/hyperscan/src/nfagraph/ng_repeat.cpp.o.d -o contrib/hyperscan-cmake/CMakeFiles/hyperscan.dir/__/hyperscan/src/nfagraph/ng_repeat.cpp.o -c ../contrib/hyperscan/src/nfagraph/ng_repeat.cpp
Killed
[1240/9765] Building CXX object contrib/hyperscan-cmake/CMakeFiles/hyperscan.dir/__/hyperscan/src/nfagraph/ng_som.cpp.o`

I want to know which step I did wrong? How can i solve this problem

**Comment by alexey-milovidov** [comment]
> I encountered the following error

`Killed [1240/9765]`

You don't have enough memory to perform multithreaded build.
Lower the number of threads by running `ninja -j1`
