### ISSUE TITLE
use MaterializeMySQL, a few days suddenly quit

### ISSUE THREAD

**Issue by y-nian** [ClickHouse/ClickHouse#25475]
clickhouse version :21.3.3.14
when i use MaterializeMySQL, a few days later, clickhouse suddenly quit, error log show :
2021.06.16 00:12:31.128449 [ 45422 ] {} <Error> Application: DB::Exception: Mapping for table with UUID=492485cd-a9ea-47d2-b695-ced3cb918c10 already exists. It happened due to UUID collision, most likely because some not random UUIDs were manually specified in CREATE queries.

if i would use MaterializeMySQL engine , how can i deal with it? thanks

all error log as follow:

0. DB::MergeTreeDataMergerMutator::mergePartsToTemporaryPart(DB::FutureMergedMutatedPart const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::BackgroundProcessListEntry<DB::MergeListElement, DB::MergeInfo>&, std::__1::shared_ptr<DB::RWLockImpl::LockHolderImpl>&, long, DB::Context const&, std::__1::unique_ptr<DB::IReservation, std::__1::default_delete<DB::IReservation> > const&, bool, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0xf6285a4 in /usr/bin/clickhouse
1. DB::StorageMergeTree::mergeSelectedParts(std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, bool, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, DB::StorageMergeTree::MergeMutateSelectedEntry&, std::__1::shared_ptr<DB::RWLockImpl::LockHolderImpl>&) @ 0xf3a11e8 in /usr/bin/clickhouse
2. ? @ 0xf3b363c in /usr/bin/clickhouse
3. ? @ 0xf574f37 in /usr/bin/clickhouse
4. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0x8651748 in /usr/bin/clickhouse
5. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()&&...)::'lambda'()::operator()() @ 0x86536ff in /usr/bin/clickhouse
6. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x864ed1f in /usr/bin/clickhouse
7. ? @ 0x86527b3 in /usr/bin/clickhouse
8. start_thread @ 0x7e25 in /usr/lib64/libpthread-2.17.so
9. __clone @ 0xf834d in /usr/lib64/libc-2.17.so
 (version 21.3.3.14 (official build))
2021.06.16 00:12:31.128449 [ 45422 ] {} <Error> Application: DB::Exception: Mapping for table with UUID=492485cd-a9ea-47d2-b695-ced3cb918c10 already exists. It happened due to UUID collision, most likely because some not random UUIDs were manually specified in CREATE queries.

**Comment by pepole** [comment]
I also disturbed by this question. When I create a few Mysql table in my clickhouse, I restart the clickhouse-server and it will success.
Then I added in  more ,almost 48 MySQL Databases in , I restart failed with  the message of "Application: DB::Exception: Mapping for table with UUID=1abe8612-e71a-4d6c-9abe-8612e71add6c already exists. It happened due to UUID collision, most likely because some not random UUIDs were manually specified in CREATE queries." Any God could help ?
