### ISSUE TITLE
При выполнении операции ORDER BY сообщение об ошибке – Превышен лимит памяти 120 ГБ

### ISSUE THREAD

**Issue by IgorLelyakov** [ClickHouse/ClickHouse#25529]
Добрый день!
Версия 21.4.5
120ГБ оперативной памяти
настройки SET join_algorithm = 'auto', max_bytes_in_join = 64 424 509 440 (то-есть 60 ГБ)

Таблица LCP2 содержит 48 млн. записей и 467 атрибутов

При выборе данных из таблицы «LCP2» выдается сообщение об ошибке «Превышен лимит памяти 120 ГБ».

В запросе осуществляется выбор 35 атрибутов и 7,5 млн. записей, выполняется одна операция GROUP BY по полю «P2_PurchaseDetailedSpecifications_PurchaseDetailedSpecificationId» и одна операция ORDER BY по полю "Стоимость ДОЗ".

Если убрать операцию ORDER BY по полю "Стоимость ДОЗ" то запрос выполняется без ошибки. Таким образом ошибка по лимиту памяти возникает при выполнении операции ORDER BY.

Скажите есть ли какие-либо настройки для того, чтобы запрос с операцией ORDER BY выполнился успешно без ошибки по оперативной памяти?

Файл запроса и DDL таблицы LCP2 прилагаются.

С уважением,
Леляков Игорь
[CREATE TABLE LCP2.txt](https://github.com/ClickHouse/ClickHouse/files/6685259/CREATE.TABLE.LCP2.txt)
[SELECT+ORDER BY.txt](https://github.com/ClickHouse/ClickHouse/files/6685260/SELECT%2BORDER.BY.txt)

**Comment by vdimir** [comment]
С настройкой `SET join_algorithm = 'partial_merge';` поведение такое же?

**Comment by alexey-milovidov** [comment]
`max_bytes_before_external_sort`
https://clickhouse.tech/docs/en/sql-reference/statements/select/order-by/#implementation-details

**Comment by IgorLelyakov** [comment]
спасибо, попробую

**Comment by IgorLelyakov** [comment]
Добрый день!
Выставил max_bytes_before_external_sort= 85 899 345 92 - тоже самое сообщение об ошибке,
уменьшил выставил max_bytes_before_external_sort= 42 949 672 960 - то же самое сообщение об ошибке о превышении лимита памяти, что порекомендуете еще уменьшить или наоборот увеличить?
max_memory_usage=128 849 018 880 
Ошибку пишет 
SQL Error [241]: ClickHouse exception, code: 241, host: 10.42.8.116, port: 8123; Code: 241, e.displayText() = DB::Exception: Memory limit (total) exceeded: would use 113.08 GiB (attempt to allocate chunk of 4587520 bytes), maximum: 113.08 GiB: While executing ConvertingAggregatedToChunksSource (version 21.4.5.46 (official build))

Файл с настройками прилагаю
[settings_202106221831.txt](https://github.com/ClickHouse/ClickHouse/files/6695654/settings_202106221831.txt)

**Comment by alexey-milovidov** [comment]
`SET max_bytes_before_external_sort = '50G', max_bytes_before_external_group_by = '50G', distributed_aggregation_memory_efficient = 1;`

**Comment by IgorLelyakov** [comment]
спасибо, попробую

**Comment by IgorLelyakov** [comment]
Алексей, большое спасибо, запрос отработал без ошибки!

Выставил 
max_bytes_before_external_sort= 53687091200
max_bytes_before_external_group_by = 53687091200

Не выставлял
distributed_aggregation_memory_efficient = 1
 так как я понял он нужен только если используется кластер
