### ISSUE TITLE
Quick QA: Which facet does the recommend insertion rate apply?

### ISSUE THREAD

**Issue by leiless** [ClickHouse/ClickHouse#25587]
Hi @alexey-milovidov, @alesapin, @KochetovNicolai, @akuzm, @blinkov, as the ClickHouse Performance docs says:

> ...
> We recommend inserting data in packets of at least 1000 rows, or no more than a single request per second.
> ...
> https://clickhouse.tech/docs/en/introduction/performance/#performance-when-inserting-data

Which facet does this limit apply? per ClickHouse cluster? or per database? or per table?

My use case is that we have multiple apps to share the same ClickHouse instance, so I need to know which facet does the limit applies.

**Comment by den-crane** [comment]
Per node. 

But it's very average recommendation.  Probably if you have 4CPU/16GB RAM/1 HDD server this sentence is true.
If you have NVME disks and 64 CPU and do more inserts per second per server.
