### ISSUE TITLE
Missing data after merge from Buffer table

### ISSUE THREAD

**Issue by SargtLa** [ClickHouse/ClickHouse#25585]
Hello!

Faced the issue, when my data, that I've inserted into a buffer table, disappeared after merge to main table.
I have a few instances, that are collecting data and inserting it to buffer table. Each instance has its own buffer and performs insert query after buffer reaches some limit (currently 1000 rows).

I use http interface with format JSONCompactEachRow.
I am also writing a log with query data and clickhouse response. I have got no errors and every time response is 200.
I have also made some SELECT queries from buffer table, and get all my inserted info, but after merge SELECT from main table did not show newly inserted rows.

I faced the issue on the version 21.1
After update to 21.6.5.37 nothing changed, data continues to disappear.

**How to reproduce**

Version:  21.6.5.37
Tables:

create table myDB.TestTable
(
    Timestamp      DateTime64(6),
    Name              LowCardinality(String),
    Quantity          UInt32,
    Price          Decimal(14, 7),
    City             LowCardinality(String),
    Code          UInt64,
    Source       LowCardinality(String)
)
    engine = MergeTree PARTITION BY (Name, toYYYYMM(Timestamp))
        PRIMARY KEY (Name, Timestamp)
        ORDER BY (Name, Timestamp)
        SETTINGS index_granularity = 8192;

create table myDB.TestTable_buffer
(
    Timestamp      DateTime64(6),
    Name           LowCardinality(String),
    Quantity       UInt32,
    Price          Decimal(14, 7),
    City           LowCardinality(String),
    Code           UInt64,
    Source         LowCardinality(String)
)
    engine = Buffer('myDb', 'TestTable', 16, 10, 120, 10000, 1000000, 10000000, 100000000);

Insert query example:

INSERT INTO myDb.TestTable_buffer (Timestamp, Name, Quantity, Price, City, Code) FORMAT JSONCompactEachRow  ["2021-06-21 09:42:05.066", "Banana", 15, 28.940000, "Kyiv", 72057594037936208] ;

**Comment by alexey-milovidov** [comment]
You have `myDB` for `myDB.TestTable` and `myDB.TestTable_buffer`
but for the destination table you have `myDb`.

Database names are case sensitive.

**Comment by alexey-milovidov** [comment]
```
milovidov-desktop :) CREATE DATABASE myDB

CREATE DATABASE myDB

Query id: 67a97de9-79d3-459c-87d6-65e6fd0f2c17

Ok.

0 rows in set. Elapsed: 0.002 sec. 

milovidov-desktop :) create table myDB.TestTable　(　Timestamp DateTime64(6),　Name LowCardinality(String),　Quantity UInt32,　Price Decimal(14, 7),　City LowCardinality(String),　Code UInt64,　Source LowCardinality(String)　)　engine = MergeTree PARTITION BY (Name, toYYYYMM(Timestamp))　PRIMARY KEY (Name, Timestamp)　ORDER BY (Name, Timestamp)　SETTINGS index_granularity = 8192;

CREATE TABLE myDB.TestTable
(
    `Timestamp` DateTime64(6),
    `Name` LowCardinality(String),
    `Quantity` UInt32,
    `Price` Decimal(14, 7),
    `City` LowCardinality(String),
    `Code` UInt64,
    `Source` LowCardinality(String)
)
ENGINE = MergeTree
PARTITION BY (Name, toYYYYMM(Timestamp))
PRIMARY KEY (Name, Timestamp)
ORDER BY (Name, Timestamp)
SETTINGS index_granularity = 8192

Query id: 838012b3-41dd-453e-aee7-4f5fb4ce620d

Ok.

0 rows in set. Elapsed: 0.003 sec. 

milovidov-desktop :) create table myDB.TestTable_buffer
:-] (
:-] Timestamp DateTime64(6),
:-] Name LowCardinality(String),
:-] Quantity UInt32,
:-] Price Decimal(14, 7),
:-] City LowCardinality(String),
:-] Code UInt64,
:-] Source LowCardinality(String)
:-] )
:-] engine = Buffer('myDb', 'TestTable', 16, 10, 120, 10000, 1000000, 10000000, 100000000);

CREATE TABLE myDB.TestTable_buffer
(
    `Timestamp` DateTime64(6),
    `Name` LowCardinality(String),
    `Quantity` UInt32,
    `Price` Decimal(14, 7),
    `City` LowCardinality(String),
    `Code` UInt64,
    `Source` LowCardinality(String)
)
ENGINE = Buffer('myDb', 'TestTable', 16, 10, 120, 10000, 1000000, 10000000, 100000000)

Query id: c3647b1f-6955-4e6b-9b61-d6e03e5bb874

Ok.

0 rows in set. Elapsed: 0.001 sec. 

milovidov-desktop :) INSERT INTO myDb.TestTable_buffer (Timestamp, Name, Quantity, Price, City, Code) FORMAT JSONCompactEachRow ["2021-06-21 09:42:05.066", "Banana", 15, 28.940000, "Kyiv", 72057594037936208] ;

INSERT INTO myDb.TestTable_buffer (Timestamp, Name, Quantity, Price, City, Code) FORMAT JSONCompactEachRow

Query id: bae1b81f-4d26-4a3d-b64b-3cd03d14ec2b


0 rows in set. Elapsed: 0.010 sec. 

Received exception from server (version 21.8.1):
Code: 81. DB::Exception: Received from localhost:9000. DB::Exception: Database myDb doesn't exist.
```

**Comment by SargtLa** [comment]
Hello! Sorry, renamed tables for this issue, because real name does not matter here. I have no problem with inserting the data and get no errors about naming. The insert queries are all the same and the name of the table does not matter. The issue is that some data were flushed to the main table from buffer and some data were lost, despite being inserted in buffer.
