### ISSUE TITLE
drop table on cluster问题

### ISSUE THREAD

**Issue by sunzaizhi11** [ClickHouse/ClickHouse#25588]
clickhouse版本：21.4.4.30

我以drop table testck on cluster clustername 能成功删除
但是接下来再以create table testck on cluster clustername的方式创建同一张表的时候，每次都会出现如下错误：
`Code: 458. DB::Exception: Received from localhost:9000. DB::Exception: There was an error on [clickhouse009187.ppdgdsl.com:9000]: Code: 458, e.displayText() = DB::ErrnoException: Cannot unlink file /data3/clickhouse/store/c52/c52fef43-0862-4a1e-8596-00b983254830/format_version.txt, errno: 2, strerror: No such file or directory (version 21.4.4.30 (official build)). `

神奇的是过几分钟左右再执行上述create语句就成功了，
网上也没找到资料，想了解是什么原因造成的，谢谢。

**Comment by tavplubix** [comment]
Fixed in #23433
Version 21.4.4.30 is outdated, please consider upgrading

**Comment by sunzaizhi11** [comment]
This problem does not exist in newest versions?
