### ISSUE TITLE
set default_roles_all to 0 for all ldap users

### ISSUE THREAD

**Issue by rlazimi-dev** [ClickHouse/ClickHouse#25591]
I would like to know how to modify the `default_roles_all` setting so that users logging in from ldap are not automatically granted a custom admin role that I've created.

For users that have already logged in, I can simply modify the column, but with LDAP, new users are always logging in. If there is a way to do this, I suggest it is documented. I will check the source in the meantime.

**Comment by Blackmorse** [comment]
@rlazimi-dev , Does this mean that any ldap user can log in into ClickHouse, and there is no way to restrict that behaviour?

**Comment by rlazimi-dev** [comment]
Ignore this thread, I made it based off a misunderstanding of how LDAP in ClickHouse works.

See #25686 .
