### ISSUE TITLE
UNION with JOIN + WHERE query fails in 21.5+

### ISSUE THREAD

**Issue by Schmak** [ClickHouse/ClickHouse#25611]
**Describe the bug**
The following query fails in 21.5 and 21.6 releases.
It worked fine in 21.4.

**Does it reproduce on recent release?**
Yes

**How to reproduce**
```
SELECT * FROM (
    SELECT 1 AS a, 2 AS b FROM system.one
    JOIN system.one USING dummy
      UNION ALL
    SELECT 3 AS a, 4 AS b FROM system.one
)
WHERE a != 10
```

**Expected behavior**
Query should run without errors

**Error message and/or stacktrace**
```
Code: 49, e.displayText() = DB::Exception: Block structure mismatch in Pipe::unitePipes stream: different number of columns:
a UInt8 UInt8(size = 0), b UInt8 UInt8(size = 0), dummy UInt8 UInt8(size = 0)
a UInt8 UInt8(size = 0), b UInt8 UInt8(size = 0) (version 21.6.5.37 (official build))
```

**Comment by SaltTan** [comment]
Duplicate https://github.com/ClickHouse/ClickHouse/issues/24024?
Does it work on 21.5.7?
You can disable `query_plan_filter_push_down` as a workaround.

**Comment by alexey-milovidov** [comment]
Works perfect on 21.8.
