### ISSUE TITLE
The clickhouse always restart,  when update many data

### ISSUE THREAD

**Issue by Sallery-X** [ClickHouse/ClickHouse#25617]
You have to provide the following information whenever possible.

**Describe the bug**

A clear and concise description of what works not as it is supposed to.

![image](https://user-images.githubusercontent.com/45587738/123066061-5097fc80-d442-11eb-8de5-f5ae221e6e93.png)

version: 20.8.11.17

**Comment by alesapin** [comment]
Hi, there is no information about restarts on the screenshot. The issue is unclear. Also, you are using not the latest patch to 20.8. Try to update.

**Comment by Sallery-X** [comment]
> Hi, there is no information about restarts on the screenshot. The issue is unclear. Also, you are using not the latest patch to 20.8. Try to update.

about 5w+ mutations， the log just just exit 137

**Comment by Sallery-X** [comment]
> Hi, there is no information about restarts on the screenshot. The issue is unclear. Also, you are using not the latest patch to 20.8. Try to update.

no error log，log the mutations log until  the container restart suddenly
