### ISSUE TITLE
`a small table A inner join a big table B;` is slower than `a big table B inner join a small table A;`

### ISSUE THREAD

**Issue by yanhuqing666** [ClickHouse/ClickHouse#25613]
**Describe the situation**
What exactly works slower than expected?
`a small table A inner join a big table B;`
works slower than
`a big table B inner join a small table A;`

**How to reproduce**

 ***1.CREATE TABLE***
`CREATE TABLE warehouse
(
    `w_warehouse_sk` Int32,
    `w_warehouse_id` String,
    `w_warehouse_name` String,
    `w_warehouse_sq_ft` Int32,
    `w_street_number` String,
    `w_street_name` String,
    `w_street_type` String,
    `w_suite_number` String,
    `w_city` String,
    `w_county` String,
    `w_state` String,
    `w_zip` String,
    `w_country` String,
    `w_gmt_offset` Float32
)
ENGINE = MergeTree
ORDER BY w_warehouse_sk`

`CREATE TABLE inventory
(
    `inv_date_sk` Int32,
    `inv_item_sk` Int32,
    `inv_warehouse_sk` Int32,
    `inv_quantity_on_hand` Int32
)
ENGINE = MergeTree
ORDER BY (inv_date_sk, inv_item_sk, inv_warehouse_sk)
`
 ***2.  init data***
`warehouse` has 5 rows
and `inventory` has 11,745,000 rows
or use these [test data](https://github.com/yanhuqing666/testdata/tree/main/ck_test1). use `cat x* > file.zip` and unzip

 ***3.query***
`select distinct(w_warehouse_name) from warehouse join (select distinct(inv_warehouse_sk) from inventory where inv_quantity_on_hand > 900) b on inv_warehouse_sk = w_warehouse_sk;`
slower than 
`select distinct(w_warehouse_name) from (select distinct(inv_warehouse_sk) from inventory where inv_quantity_on_hand > 900) b  join warehouse on inv_warehouse_sk = w_warehouse_sk;
`

* Which ClickHouse server version to use
21.6.3.14 
* Which interface to use, if matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to slow performance

**Expected performance**
What are your performance expectation, why do you think they are realistic? Has it been working faster in older ClickHouse releases? Is it working faster in some specific other systems?

I think the two queries should be the same 

**Additional context**

**Comment by vdimir** [comment]
It's expected with HashJoin algorithm, because it build hashmap for right table before performing join, so it's preferable to have smaller table at right side of join.

See `Performance` and `Memory Limitations` sections: https://clickhouse.tech/docs/en/sql-reference/statements/select/join/#performance

**Comment by yanhuqing666** [comment]
I found the reason for the query time in my case, which is not build hashmap, but reading time from many parts by thread pool or by a single thread

If you really need to read lots of data from the big table. The big table's single-thread reading will become a little slow.

**Comment by den-crane** [comment]
@yanhuqing666 What CH version do you use? I believe it's  multi-threaded now.

**Comment by yanhuqing666** [comment]
> @yanhuqing666 What CH version do you use? I believe it's multi-threaded now.

21.6.3.14 ， I open a pr https://github.com/ClickHouse/ClickHouse/pull/25614 
maybe there are other better ways to resolve

**Comment by yanhuqing666** [comment]
It is fixed by #26052
