### ISSUE TITLE
error: another log entry for the same part is being processed

### ISSUE THREAD

**Issue by derekperkins** [ClickHouse/ClickHouse#2562]
> (ReplicatedMergeTreeQueue): Not executing log entry for part 20180501_20180531_6_11_1 because another log entry for the same part is being processed. This shouldn't happen often.

I'm seeing hundreds of these log lines per second and replication isn't progressing. Any idea what could be causing this?

ClickHouse version: 1.1.54385
Using Docker

**Comment by alexey-milovidov** [comment]
This is normal and does not indicate any errors itself.
