### ISSUE TITLE
skip_unavailable_shards have the preference over fallback_to_stale_replicas

### ISSUE THREAD

**Issue by alex-zaitsev** [ClickHouse/ClickHouse#2564]
When 
1) both skip_unavailable_shards and fallback_to_stale_replicas are set to 1, 
2) one replica is down (partially)
3) other replicas are latent (stale)

In this case CH returns incomplete data skipping latent shards

The problem is in:
https://github.com/yandex/ClickHouse/blob/096fec65048aefd665651ba7f7ff5ddd4f684aea/dbms/src/Common/PoolWithFailoverBase.h

PoolWithFailoverBase<TNestedPool>::getMany(...)

```
    if (up_to_date_count >= min_entries)
    {
        /// There is enough up-to-date entries.
        try_results.resize(up_to_date_count);
    }
    else if (fallback_to_stale_replicas)
    {
        /// There is not enough up-to-date entries but we are allowed to return stale entries.
        /// Gather all up-to-date ones and least-bad stale ones.

        size_t size = std::min(try_results.size(), max_entries);
        try_results.resize(size);
    }
```
When skip_unavaialble_shards=1 then min_entries=0 in this code. So once up_to_date_count is also 0, shard is skipped.

Those two conditions should be switched.

**Comment by alexey-milovidov** [comment]
@azat FYI

**Comment by azat** [comment]
>Those two conditions should be switched.

Indeed and looks pretty damn easy to fix
