### ISSUE TITLE
Insert data bug

### ISSUE THREAD

**Issue by zhanghaicheng1** [ClickHouse/ClickHouse#25659]
1、create table
```
CREATE TABLE insert_select_testtable
(
    `a` Int8,
    `b` String,
    `c` Int8
)
ENGINE = MergeTree()
ORDER BY a
```
2、insert date
【Dbeaver Tools】
plan 1 ：success
```
INSERT INTO insert_select_testtable (a,b,c) VALUES (1, 'a', 1),(2,'b',1) ;
```
  _Updated Rows	0
  Query	INSERT INTO insert_select_testtable (a,b,c) VALUES (1, 'a', 1),(2,'b',1) 
  Finish time	Thu Jun 24 10:28:31 CST 2021_
plan2：failed
```
INSERT INTO insert_select_testtable (*) VALUES (3, '', 3) ;
```
_SQL Error [62]: ClickHouse exception, code: 62, host: ****, port: 8123; Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 38 ('*'): *) VALUES (3, '', 3) . Expected one of: identifier, compound identifier, list of elements (version 20.8.3.18)_

【Clickhouse Client】
Consistent with the above error
![image](https://user-images.githubusercontent.com/46189785/123193737-e5990500-d4d7-11eb-970e-8672f5c046d2.png)
Check the official website, it is supported, the screenshot is proof
![image](https://user-images.githubusercontent.com/46189785/123193901-209b3880-d4d8-11eb-85b5-28c3419bfa55.png)

**Comment by zhanghaicheng1** [comment]
Looking forward to reply, thank you！

**Comment by zhanghaicheng1** [comment]
```
INSERT INTO insert_select_testtable  Values (2,'d', 2); 
```
is ok!

**Comment by jptx1234** [comment]
![image](https://user-images.githubusercontent.com/8757243/123209194-da9f9e00-d4f2-11eb-8697-aa2c7c7e4622.png)

试了下新版本 21.6.5.37 没问题，你用的是20.8.3.18，要不升级下版本试试看

English version:
It's OK in version 21.6.5.37. You are using 20.8.3.18. Maybe you can try the latest version.

**Comment by alesapin** [comment]
Yes, this is quite a new type of query, just update to the latest stable.

**Comment by zhanghaicheng1** [comment]
Thanks！
