### ISSUE TITLE
ALTER TABLE ... FREEZE documentation: WITH NAME is not documented

### ISSUE THREAD

**Issue by aferreira** [ClickHouse/ClickHouse#25650]
The documentation of `ALTER TABLE ... FREEZE` ([here](https://clickhouse.tech/docs/en/sql-reference/statements/alter/partition/#alter_freeze-partition)) does not mention `WITH NAME`.

With the recent addition of `UNFREEZE` – implemented by https://github.com/ClickHouse/ClickHouse/pull/21142 and documented at https://github.com/ClickHouse/ClickHouse/pull/24765 – the [documentation](https://clickhouse.tech/docs/en/sql-reference/statements/alter/partition/#alter_unfreeze-partition) gets inconsistent since `UNFREEZE` mentions a backup name without a correspondence at freeze time.

According to the Git commits, the `WITH NAME` part of `FREEZE` has been there for a long time.

**Comment by DanRoscigno** [comment]
closed by https://clickhouse.com/docs/en/sql-reference/statements/alter/partition/#freeze-partition
