### ISSUE TITLE
Does hdfs engine support viewfs?

### ISSUE THREAD

**Issue by mdianjun** [ClickHouse/ClickHouse#25656]
It seems that libhdfs3 doesn't support viewfs，look at this: https://issues.apache.org/jira/browse/HAWQ-1626 ，so does hdfs table engine?

hdfs viewfs: https://hadoop.apache.org/docs/stable/hadoop-project-dist/hadoop-hdfs/ViewFs.html

**Comment by kssenii** [comment]
@mdianjun yes, it is not supported as libhdfs3 does not have this support.
