### ISSUE TITLE
Is it possible to download a specific version of macOS binary build?

### ISSUE THREAD

**Issue by DevcodeHenrik** [ClickHouse/ClickHouse#25664]
Hello!
Is it possible do download a specific precompiled version of macOS clickhouse binary? Not always getting the latest?
(curl -O 'https://builds.clickhouse.tech/master/macos/clickhouse')
Thanks,
/Henrik

**Comment by l1t1** [comment]
from https://github.com/ClickHouse/ClickHouse/commits/master
get build link such as

https://clickhouse-builds.s3.yandex.net/0/3e238c1767b9ff7a989428c691886886536f2a5e/clickhouse_special_build_check/report.html

it has some builds. but don't include macos

**Comment by l1t1** [comment]
from https://github.com/ClickHouse/ClickHouse/commits/master
get build link such as

https://clickhouse-builds.s3.yandex.net/0/3e238c1767b9ff7a989428c691886886536f2a5e/clickhouse_special_build_check/report.html

it has some builds. but don't include macos

**Comment by den-crane** [comment]
Short answer: No.
