### ISSUE TITLE
When there are duplicate nodes in different clusters, insert a piece of data based on the distributed table of the replicated table, and query two pieces of data

### ISSUE THREAD

**Issue by HavAnIdea** [ClickHouse/ClickHouse#25661]
I tested a distributed table with replicated table as local table.

Now there are 4 CK servers A, B, C, D, 
where A, B, C are a cluster (3shards_1replicas), and A, B, C, D are the second cluster (2shards_2replicas: s1{A,B}, s2{C,D})

When I use the following sql to build a table

create table t on cluster 3shards_1replicas (...) engine = ReplicatedMergeTree(...) ...
create table t_all on cluster 3shards_1replicas as t engine = Distributed(.., rand())

Insert 1 piece of data into t_all, query t_all to find 2 pieces of data

When the cluster of the above table creation statement is changed to 2shards_2replicas,  same insert, the query is normal;
The local table engine of the table creation statement is changed to MergeTree, same insert, and the query is normal.

So, when there are duplicate nodes in different clusters, does the replicated table engine not work properly?

**Comment by den-crane** [comment]
Replication depends on ZK path and macros (ReplicatedMergeTree(zk_path)).
You need to have 2 sets of macros shard.

Please provide EXACT command `create table t on cluster 3shards_1replicas (...) engine = ReplicatedMergeTree(...) `
and `select * from system.macros` from all 4 nodes.

**Comment by HavAnIdea** [comment]
local table DDL like ' create table t on 3shards_1replicas (columns) engine = ReplicatedMergeTree('clickhouse/table/{shard}/default/t', {replica}) '
A,B,C,D four nodes have the same macros (shard and replica), but different value

A shard = 01, replica = 01
B shard = 01, replica = 02
C shard = 02, replica = 01
D shard = 02, replica = 02

only 2shards_2replicas's macros , no 3shards_1replicas's macros

so, even if I specify the cluster name as 3shards_1replicas，
when doing macro replacement，ClickHouse cannot tell whether the replaced macro belongs to this cluster

It is undeniable that the configuration of multiple clusters is very flexible，but does it bring additional learning costs, because not everyone knows the cluster configuration (such as macros and node belongs to which cluster), and these people cannot use it correctly

**Comment by den-crane** [comment]
forget about `on cluster`. `on cluster` is a simple helper to execute queries on each node. It has no relation to replication.

remote_servers section -- aka cluster description has 0 ZERO relation to replication.

You need to define one more macro and name it for example myshardXXX.

A shard = 01, replica = 01, myshardXXX=01
B shard = 01, replica = 02, myshardXXX=02
C shard = 02, replica = 01, myshardXXX=03
D shard = 02, replica = 02

After that create a table using that new macro

`ReplicatedMergeTree('clickhouse/table/{myshardXXX}/default/t', {replica}) '`
