### ISSUE TITLE
Detect that server is running under cgroup control, get cpu/memory info with limitations

### ISSUE THREAD

**Issue by piotr-szybicki** [ClickHouse/ClickHouse#25662]
Hi, we are planning to run our CH instances in kubernetes and I was wondering if the `max_server_memory_usage_to_ram_ratio` will check if we are running under a cgroup control and read the value from /sys/fs/cgroup/memory. I suspect that it doesn't but wanted to confirm (found this: https://github.com/flant/loghouse/issues/110).

**Comment by vdimir** [comment]
PR https://github.com/ClickHouse/ClickHouse/pull/18448 related but offers some straightforward approach to control it using env variables

**Comment by vdimir** [comment]
@piotr-szybicki so, what do you think on setting hardware info from env? Does it solve your task? I suppose that PR requires some changes, because we still haven't decided how it should looks like.

**Comment by piotr-szybicki** [comment]
So I think at the moment we can set the value in helm chart  `max_memory_usage` to the limit that this container is allowed to use. And that will be good enough? I think also I will create PR to address this (if they are welcomed). The Java Virtual Machine does this this way http://hg.openjdk.java.net/jdk/jdk/file/03f2bfdcb636/src/hotspot/os/linux/osContainer_linux.cpp#l233 I though similar approach could work for ClickHouse?

**Comment by vdimir** [comment]
> I think also I will create PR to address this (if they are welcomed).

It will be really appreciated.

Solution with getting cpu/memory info from `/proc` if it's available seems good.

**Comment by thyn** [comment]
Any updates here?  Does it included in any roadmap?

**Comment by alexey-milovidov** [comment]
What is the most easy way to get this info without the use of any libraries?
Maybe `/sys/fs/cgroup/...`? Where exactly to read this info?

PS. It's not included in any roadmap.

**Comment by alexey-milovidov** [comment]
Memory: `/sys/fs/cgroup/memory/memory.limit_in_bytes`?

**Comment by thyn** [comment]
May be it's possible to setup cpu and memory limits  in config. It would be the great point to start.  We sometimes use clickhouse in k8s with other containers and we can't limit it normally.

**Comment by thyn** [comment]
Any updates here?

**Comment by JaySon-Huang** [comment]
@thyn I think this issue is duplicated with https://github.com/ClickHouse/ClickHouse/issues/2261 and will be closed by  #30574 and #33342
