### ISSUE TITLE
timeZoneOffset should be renamed to timezoneOffset

### ISSUE THREAD

**Issue by finnan444** [ClickHouse/ClickHouse#25668]
**timeZoneOffset** function [description and example](https://github.com/ClickHouse/ClickHouse/blob/master/docs/ru/sql-reference/functions/date-time-functions.md#timezoneoffset-timezoneoffset) raises error - `Unknown function timeZoneOffset. Maybe you meant: ['timezoneOffset','timezoneOf']`
Correct function name - **timezoneOffset**

**Comment by alexey-milovidov** [comment]
Aliases were added in recent ClickHouse release.
