### ISSUE TITLE
Clickhouse21.4.5.46 version failed to connect to superset clickhouse19.9.2.4 is possible

### ISSUE THREAD

**Issue by mjh568412187** [ClickHouse/ClickHouse#25685]
Make sure to check documentation https://clickhouse.yandex/docs/en/ first. If the question is concise and probably has a short answer, asking it in Telegram chat https://telegram.me/clickhouse_en is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

If you still prefer GitHub issues, remove all this text and ask your question here.

![image](https://user-images.githubusercontent.com/26197792/123294206-3ac02f80-d547-11eb-8156-e76e6c262f51.png)

**Comment by mjh568412187** [comment]
> Make sure to check documentation https://clickhouse.yandex/docs/en/ first. If the question is concise and probably has a short answer, asking it in Telegram chat https://telegram.me/clickhouse_en is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse
> 
> If you still prefer GitHub issues, remove all this text and ask your question here.
> 
> ![image](https://user-images.githubusercontent.com/26197792/123294206-3ac02f80-d547-11eb-8156-e76e6c262f51.png)

2021.06.25 01:22:57.181363 [ 76025 ] {} <Error> Access(user directories): default: Authentication failed: Code: 192, e.displayText() = DB::Exception: There is no user `default` in user directories, Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x87f4c4a in /usr/lib/debug/.build-id/9a/14d4a10dca592b9770271f208e8f7a390418e3.debug
1. DB::IAccessStorage::throwNotFound(DB::IAccessEntity::Type, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const @ 0xec5ab22 in /usr/lib/debug/.build-id/9a/14d4a10dca592b9770271f208e8f7a390418e3.debug
2. DB::MultipleAccessStorage::loginImpl(DB::Credentials const&, Poco::Net::IPAddress const&, DB::ExternalAuthenticators const&) const @ 0xec819e8 in /usr/lib/debug/.build-id/9a/14d4a10dca592b9770271f208e8f7a390418e3.debug
3. DB::IAccessStorage::login(DB::Credentials const&, Poco::Net::IPAddress const&, DB::ExternalAuthenticators const&, bool) const @ 0xec5d19c in /usr/lib/debug/.build-id/9a/14d4a10dca592b9770271f208e8f7a390418e3.debug
4. DB::Context::setUser(DB::Credentials const&, Poco::Net::SocketAddress const&) @ 0xf08b807 in /usr/lib/debug/.build-id/9a/14d4a10dca592b9770271f208e8f7a390418e3.debug
5. DB::HTTPHandler::authenticateUser(DB::Context&, DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&) @ 0xfe73ccd in /usr/lib/debug/.build-id/9a/14d4a10dca592b9770271f208e8f7a390418e3.debug
6. DB::HTTPHandler::processQuery(DB::Context&, DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::__1::optional<DB::CurrentThread::QueryScope>&) @ 0xfe76b04 in /usr/lib/debug/.build-id/9a/14d4a10dca592b9770271f208e8f7a390418e3.debug
7. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0xfe7e58d in /usr/lib/debug/.build-id/9a/14d4a10dca592b9770271f208e8f7a390418e3.debug
8. DB::HTTPServerConnection::run() @ 0xff04c7f in /usr/lib/debug/.build-id/9a/14d4a10dca592b9770271f208e8f7a390418e3.debug
9. Poco::Net::TCPServerConnection::start() @ 0x125b5b0f in /usr/lib/debug/.build-id/9a/14d4a10dca592b9770271f208e8f7a390418e3.debug
10. Poco::Net::TCPServerDispatcher::run() @ 0x125b7521 in /usr/lib/debug/.build-id/9a/14d4a10dca592b9770271f208e8f7a390418e3.debug
11. Poco::PooledThread::run() @ 0x126edc49 in /usr/lib/debug/.build-id/9a/14d4a10dca592b9770271f208e8f7a390418e3.debug
12. Poco::ThreadImpl::runnableEntry(void*) @ 0x126e9aaa in /usr/lib/debug/.build-id/9a/14d4a10dca592b9770271f208e8f7a390418e3.debug
13. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
14. clone @ 0xfe96d in /usr/lib64/libc-2.17.so
 (version 21.4.5.46 (official build))
2021.06.25 01:22:57.181643 [ 76025 ] {} <Error> DynamicQueryHandler: Code: 516, e.displayText() = DB::Exception: default: Authentication failed: password is incorrect or there is no user with such name, Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x87f4c4a in /usr/lib/debug/.build-id/9a/14d4a10dca592b9770271f208e8f7a390418e3.debug
1. DB::IAccessStorage::throwCannotAuthenticate(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xec5d3df in /usr/lib/debug/.build-id/9a/14d4a10dca592b9770271f208e8f7a390418e3.debug
2. DB::IAccessStorage::login(DB::Credentials const&, Poco::Net::IPAddress const&, DB::ExternalAuthenticators const&, bool) const @ 0xec5d222 in /usr/lib/debug/.build-id/9a/14d4a10dca592b9770271f208e8f7a390418e3.debug
3. DB::Context::setUser(DB::Credentials const&, Poco::Net::SocketAddress const&) @ 0xf08b807 in /usr/lib/debug/.build-id/9a/14d4a10dca592b9770271f208e8f7a390418e3.debug
4. DB::HTTPHandler::authenticateUser(DB::Context&, DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&) @ 0xfe73ccd in /usr/lib/debug/.build-id/9a/14d4a10dca592b9770271f208e8f7a390418e3.debug
5. DB::HTTPHandler::processQuery(DB::Context&, DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::__1::optional<DB::CurrentThread::QueryScope>&) @ 0xfe76b04 in /usr/lib/debug/.build-id/9a/14d4a10dca592b9770271f208e8f7a390418e3.debug
6. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0xfe7e58d in /usr/lib/debug/.build-id/9a/14d4a10dca592b9770271f208e8f7a390418e3.debug
7. DB::HTTPServerConnection::run() @ 0xff04c7f in /usr/lib/debug/.build-id/9a/14d4a10dca592b9770271f208e8f7a390418e3.debug
8. Poco::Net::TCPServerConnection::start() @ 0x125b5b0f in /usr/lib/debug/.build-id/9a/14d4a10dca592b9770271f208e8f7a390418e3.debug
9. Poco::Net::TCPServerDispatcher::run() @ 0x125b7521 in /usr/lib/debug/.build-id/9a/14d4a10dca592b9770271f208e8f7a390418e3.debug
10. Poco::PooledThread::run() @ 0x126edc49 in /usr/lib/debug/.build-

**Comment by alexey-milovidov** [comment]
Looks like this is a configuration issue.
Check `/etc/clickhouse-server/users.xml` and `/etc/clickhouse-server/users.d/*`

**Comment by mjh568412187** [comment]
> Looks like this is a configuration issue.
> Check `/etc/clickhouse-server/users.xml` and `/etc/clickhouse-server/users.d/*`

You must configure a default user for clickhouse to use superset. I don’t know if it’s ck or superset. Now this problem has been solved, thank you
