### ISSUE TITLE
Got Checksum doesn't match Exception when query table

### ISSUE THREAD

**Issue by meetjunsu** [ClickHouse/ClickHouse#25699]
**clickhouse version**: 21.5.5.12
**full log:**
`
ru.yandex.clickhouse.except.ClickHouseException: ClickHouse exception, code: 40, host: 10.70.132.5, port: 8123; Code: 40, e.displayText()= DB::Exception: Checksum doesn't match: corrupted data. Reference: 6a4b4815ba651f5753b6d668681ca677. Actual: bc6fa98d8a294985b2743e3bf133a5ce. Size of compressed block: 165475. The mismatch is caused by single bit flip in data block at byte 160785, bit 0. This is most likely due to hardware failure. If you receive broken data over network and the error does not repeat every time, this can be caused by badRAM on network interface controller or bad controller itself or bad RAM on network switches or bad CPU on network switches (look at the logs on related network switches; note that TCP checksums don't help) or bad RAM on host (look at dmesg or kern.log for enormous amount ofEDAC errors, ECC-related reports, Machine Check Exceptions, mcelog; note that ECC memory can fail if the number of errors is huge) or bad CPU on host. If you read data from disk, this can be caused by disk bit rott. This exception protects ClickHouse from data corruption due to hardware failures.: (while reading column command_line__hist.item): While executing MergeTreeThread (version 21.5.5.12 (official build))
`

**Disk check result:**
```
badblocks -b 5120 -s -v -o badblocks.log /dev/sdc1
Pass completed, 0 bad blocks found. (0/0/0 errors)
```

**What causes this problem and how to restore the database？**

**Comment by alexey-milovidov** [comment]
You have faulty hardware.

Please read the exception message entirely. The message describe your issue in exhaustive way.
