### ISSUE TITLE
Output type of intDiv function is somehow constrained by the type of first argument

### ISSUE THREAD

**Issue by vpanfilov** [ClickHouse/ClickHouse#25703]
**Bug description**

If **Int8** value is provided as first argument of **intDiv()** function, the output type is limited to **Int8** as well. So, this query:

```sql
SELECT intDiv(1, 0.001)

Received exception from server (version 21.6.5):
Code: 153. DB::Exception: Received from localhost:9000. DB::Exception: Cannot perform integer division, because it will produce infinite or too large number: While processing intDiv(1, 0.001).
```
gives rather counter-intuitive error message.

But this query works, as the result value fits in Int8 type:
```sql
SELECT
    intDiv(1, 0.01) AS res,
    toTypeName(res)

┌─res─┬─toTypeName(intDiv(1, 0.01))─┐
│ 100 │ Int8                        │
└─────┴─────────────────────────────┘
```

**Does it reproduce on recent release?**

Yes, tested on 21.6.5.37 and 21.3.6.55

**Expected behavior**

**intDiv** output type shouldn't be limited by **Int8** type.

**Current workaround**

Casting first argument to **Float64** or **Int64** or similar types:
```sql
SELECT
    intDiv(toFloat64(1), 0.001) AS res,
    toTypeName(res)

┌──res─┬─toTypeName(intDiv(toFloat64(1), 0.001))─┐
│ 1000 │ Int64                                   │
└──────┴─────────────────────────────────────────┘
```

**Comment by alexey-milovidov** [comment]
This is how it is supposed to work, but the error message and documentation can be improved.
