### ISSUE TITLE
severe performance issue when SELECT create_table_query field from system.tables

### ISSUE THREAD

**Issue by Nicholaswang** [ClickHouse/ClickHouse#25700]
![image](https://user-images.githubusercontent.com/3916488/123388741-bd8ace00-d5cb-11eb-8243-6d5124262c14.png)
there are 1.4k rows in system.tables, when select create_table_query(fetch from metadata SQL), it can only process 20 rows per second. 

**How to reproduce**
can't reproduce with new ClickHouse instances of the same version, weird!

* Which ClickHouse server version to use
20.3.10

No abnormal fluctuation of cpu、memory and IO。

Can you guys provide some instructions debugging this issue, have tested 'pstack', 'strace', 'perf', can't use bcc(ebpf) due to environment restrictions.

**Comment by Nicholaswang** [comment]
SQL:
select database, name, engine, hex(MD5(create_table_query)), if(empty(partition_key), 'null', partition_key) from system.tables where engine in ('ReplicaedMergeTree', 'MergeTree') and database not in ('system')

**Comment by alexey-milovidov** [comment]
You can try Query Profiler: https://clickhouse.tech/docs/en/operations/optimizing-performance/sampling-query-profiler/
It should be already enabled by default, just replace the query id in the [example](https://clickhouse.tech/docs/en/operations/optimizing-performance/sampling-query-profiler/#example)

**Comment by alexey-milovidov** [comment]
If you have any difficulties, upgrade ClickHouse to version 21.6 (latest) and check again.

**Comment by alexey-milovidov** [comment]
`create_table_query` requires opening and reading .sql metadata files. It's expected to be slow if you have slow or overloaded IO. 
20 rows per second does not look normal anyhow but it is possible with slow HDD or EBS.
