### ISSUE TITLE
Conditional function 'if' works inconsistently with constant condition argument

### ISSUE THREAD

**Issue by vpanfilov** [ClickHouse/ClickHouse#25784]
**Describe the unexpected behaviour**
In most cases Clickhouse always evaluates both expressions `then` and `else` and throws error if their types don't match each other. But if the condition is constant Clickhouse can calculate only one branch. For example:

```sql
SELECT if(1, 'it works', throwIf(1, 'it doesn\'t work'))

Query id: b9f7968c-75d4-4758-b621-8fdaa5822b38

┌─'it works'─┐
│ it works   │
└────────────┘
```

This optimisation comes in very handy in cases when I need to use different date interval units for grouping:

```sql
SELECT
    if(1, toIntervalSecond(5), toIntervalHour(2)) AS interval,
    toTypeName(interval)

┌─interval─┬─toTypeName(toIntervalSecond(5))─┐
│        5 │ IntervalSecond                  │
└──────────┴─────────────────────────────────┘
```

But if I use simple expression in condition argument, this optimisation doesn't work as expected:

```sql
SELECT if(1 == 1, 'it works', throwIf(1, 'it doesn\'t work'))

Received exception from server (version 21.6.5):
Code: 395. DB::Exception: Received from localhost:9000. DB::Exception: it doesn't work: While processing if(1 = 1, 'it works', throwIf(1, 'it doesn\'t work')).
```
```sql
SELECT if(1 = 1, toIntervalSecond(5), toIntervalHour(2)) AS interval

Received exception from server (version 21.6.5):
Code: 386. DB::Exception: Received from localhost:9000. DB::Exception: There is no supertype for types IntervalSecond, IntervalHour: While processing if(1 = 1, toIntervalSecond(5), toIntervalHour(2)) AS interval.
```

Clickhouse knows exactly that `1 == 1`  is a constant:

```sql
SELECT
    1 = 1 AS cond,
    isConstant(cond) AS is_const

Query id: b642e8cf-4b3f-4da4-9109-83785f4a6c20

┌─cond─┬─is_const─┐
│    1 │        1 │
└──────┴──────────┘
```

**Expected behavior**
Branch calculation optimisation should work in all cases when condition argument is a constant in all conditional functions (**if**, **multiIf**) and operators.

**Comment by alexey-milovidov** [comment]
> it doesn't work: While processing if(1 = 1, 'it works', throwIf(1, 'it doesn\'t work')).

Exception is thrown, because the arguments of `throwIf` are constants.
Constant expressions are evaluated for constant folding.

If the arguments are not constant, it works as expected:

```
SELECT if(1 = 1, 123, throwIf(number > 0, 'it doesn\'t work'))
FROM numbers(1)

Query id: 15dd033a-c044-46f0-ae64-ae50310e9d63

┌─if(equals(1, 1), 123, throwIf(greater(number, 0), 'it doesn\'t work'))─┐
│                                                                    123 │
└────────────────────────────────────────────────────────────────────────┘
```

> SELECT if(1 = 1, toIntervalSecond(5), toIntervalHour(2)) AS interval

Type inference may not depend on the values of constants.
