### ISSUE TITLE
Restrict authentication of LDAP users

### ISSUE THREAD

**Issue by Blackmorse** [ClickHouse/ClickHouse#25800]
According to the documentation: 

> roles — section with a list of locally defined roles that will be assigned to each user retrieved from the LDAP server. If no roles are specified, user will not be able to perform any actions after authentication

Does this mean that ANY LDAP user can log in ClickHouse? Sure, if he has no matching LDAP role, he can do nothing, but still..

What can I do to restrict access for the users that have no matched roles?

**Comment by traceon** [comment]
> Does this mean that ANY LDAP user can log in ClickHouse?

If bind succeeds - yes.

**Comment by Blackmorse** [comment]
> Just block anyone who doesn't have a valid assigned role at the time of login attempt, or a separate filter to filter out users that shouldn't be able to login at all?

The first one. May it be some additional setting - don't allow users to log in if he has no valid assigned role?

**Comment by traceon** [comment]
Sounds reasonable.

**Comment by Scorcher** [comment]
Setting like

`clickhouse.user_directories.ldap.role_mapping.allow_connection_without_mapped_roles=1|0` - Allow connection if no roles mapped - 1 (default, current behaviour), refuse connection if no roles mapped - 0

will be good option to avoid useless connections.

**Comment by andrey-mikhailov** [comment]
You can do it via the option select_from_system_db_requires_grant
See https://github.com/ClickHouse/ClickHouse/pull/38970
