### ISSUE TITLE
Encountering lots detached parts when using `ALTER .. DELETE`

### ISSUE THREAD

**Issue by OmarBazaraa** [ClickHouse/ClickHouse#25818]
After we start deleting data manually from ClickHouse using `ALTER .. DELETE` command, we start facing lots of detached parts with very large sizes that almost fill our storage.

The table we delete from is a `ReplicatedMergeTree` table, and we execute mutation command on a single replica only.

Those are the logs I was able to grab related to one of the detached parts:
```
2021.06.28 15:34:33.855780 [ 6301 ] {} <Trace> MergeTreePartsMover: Part 202106_100086_145233_7_213218 was cloned to /drives/hdd1/clickhouse/data/my_database/my_local_table/detached/202106_100086_145233_7_213218/
2021.06.28 15:34:34.151152 [ 6301 ] {} <Information> MergeTreePartsMover: Failed to swap 202106_100086_145233_7_213218. Active part doesn't exist. Possible it was merged or mutated. Will remove copy on path '/drives/hdd1/clickhouse/data/my_database/my_local_table/detached/202106_100086_145233_7_213218/'.
```

We are using `clickhouse-server` version `20.10.2.20`. Can anyone help us why this is happening and how to avoid it?

**Comment by den-crane** [comment]
20.10 is out support. Supported versions are 21.3, 21.5, 21.6.
You need to upgrade at least to the latest bugfix release 20.10.7.4

**Comment by OmarBazaraa** [comment]
Well, indeed upgrading to the latest bugfix release solved the problem. Thanks!
