### ISSUE TITLE
DATE_SUB(date, INTERVAL xxx unit) - works, but is not documented

### ISSUE THREAD

**Issue by pakud** [ClickHouse/ClickHouse#25815]
**Describe the issue**
ClickHouse seems to handle correctly this type of expressions:

- DATE_SUB(NOW(), INTERVAL 1 DAY)
- DATE_ADD(NOW(), INTERVAL 1 WEEK)

handling of this format is in https://github.com/ClickHouse/ClickHouse/blob/a52bba91b776034654a96f88b2b3f81bc6170a83/src/Parsers/ExpressionElementParsers.cpp#L1369 but is not documented in https://clickhouse.tech/docs/en/sql-reference/functions/date-time-functions/#date_sub

**Additional context**
above is based on ClickHouse 21.3.5. maybe the documentation can be updated to match behavior of the code?

looks like DATE_SUB, DATE_ADD can behave just like https://clickhouse.tech/docs/en/sql-reference/functions/date-time-functions/#timestamp_add

thank you!

**Comment by DanRoscigno** [comment]
It looks like these were added to the page, but the issue was not closed.
