### ISSUE TITLE
Aggregation functions behave differently when handling 0 rows

### ISSUE THREAD

**Issue by ygnuss** [ClickHouse/ClickHouse#25811]
I would expect all aggregation functions to behave the same way when handling 0 rows. Here you have an example to reproduce it. The following query returns `nan` because the inner query returns no rows.

```
SELECT quantiles(0.95)(number)
FROM 
(
    SELECT number
    FROM numbers(10)
    WHERE number > 10
)

Query id: 2b09da72-e170-4e5f-b083-9fc236639221

┌─quantiles(0.95)(number)─┐
│ [nan]                   │
└─────────────────────────┘

1 rows in set. Elapsed: 0.009 sec. 

```

If you use `sum` function instead of `quantiles` you will get a different result. If you have 0 rows from the inner query you'll get 0:

```
SELECT sum(number)
FROM 
(
    SELECT number
    FROM numbers(10)
    WHERE number > 10
)

Query id: 54227ddc-9e65-4ce3-80b2-b42b5cf48b1e

┌─sum(number)─┐
│           0 │
└─────────────┘

1 rows in set. Elapsed: 0.117 sec. 
```

It is weird the same kind of operation (sum | quantiles) returns different things when they receive the same result (no rows). I'd expect both of them behaves the same way returning `nan` or 0.

It is weird too that if you format the output as JSON you won't get nan but null:

```
SELECT coalesce(quantiles(0.95)(number), 0)
FROM 
(
    SELECT number
    FROM numbers(10)
    WHERE number > 10
)
FORMAT JSON

Query id: be48ef2f-1cc0-4491-80c1-2e8eb40929fe

{
	"meta":
	[
		{
			"name": "coalesce(quantiles(0.95)(number), 0)",
			"type": "Array(Float64)"
		}
	],

	"data":
	[
		{
			"coalesce(quantiles(0.95)(number), 0)": [null]
		}                                                                                                                                                                            
	],

	"rows": 1,

	"rows_before_limit_at_least": 10,

	"statistics":
	{
		"elapsed": 0.003954347,
		"rows_read": 10,
		"bytes_read": 80
	}
}

1 rows in set. Elapsed: 0.010 sec. 

```

I'm using **version 21.6.5.37**.

**Comment by den-crane** [comment]
Result is different because functions are different. 

sum = 0, avg = nan, because avg = sum(0)/count 0 = nan.

you can enable ANSI behavior, it disabled by performance reasons.
--aggregate_functions_null_for_empty arg                         Rewrite all aggregate functions in a query, adding -OrNull suffix to them

```
set aggregate_functions_null_for_empty=1;

SELECT avg(number)　FROM　(　    SELECT number　    FROM numbers(10)　    WHERE number > 10　);
ᴺᵁᴸᴸ

SELECT sum(number)　FROM　(　    SELECT number　    FROM numbers(10)　    WHERE number > 10　);
ᴺᵁᴸᴸ
```

unfortunately it does not work for quantiles

```
set aggregate_functions_null_for_empty=1;
SELECT quantiles(0.95)(number)　FROM　(　    SELECT number　    FROM numbers(10)　    WHERE number > 10　);

 DB::Exception: Nested type Array(Float64) cannot be inside Nullable type.
```

**Comment by ygnuss** [comment]
Ok, thanks for your explanation @den-crane!!

One question. You've said `aggregate_functions_null_for_empty` is disabled by default due to performance reasons. The performance hit is due to having to rewrite the query or due to using -OrNull suffix? 

Thanks!!

**Comment by den-crane** [comment]
>One question. You've said aggregate_functions_null_for_empty is disabled by default due to performance reasons. 
>The performance hit is due to having to rewrite the query or due to using -OrNull suffix?

Nullable types are slower than not Nullable.
`aggregate_functions_null_for_empty` produces Nullable types.

**Comment by den-crane** [comment]
quantiles has been fixed https://github.com/ClickHouse/ClickHouse/pull/25919
