### ISSUE TITLE
There is NPE in MergeTreeData::renameTempPartAndReplace on branch master

### ISSUE THREAD

**Issue by leosunli** [ClickHouse/ClickHouse#25812]
**Describe the bug**
There is NPE in MergeTreeData::renameTempPartAndReplace  as follow
When MergeTreeData::getAnyPartInPartition may return nullptr, 
existing_part_in_partition->partition.value throw NullPointException.

`bool MergeTreeData::renameTempPartAndReplace(
    MutableDataPartPtr & part, SimpleIncrement * increment, Transaction * out_transaction,
    std::unique_lock<std::mutex> & lock, DataPartsVector * out_covered_parts, MergeTreeDeduplicationLog * deduplication_log)
{
 .....
    if (out_transaction && &out_transaction->data != this)
        throw Exception("MergeTreeData::Transaction for one table cannot be used with another. It is a bug.",
            ErrorCodes::LOGICAL_ERROR);

    part->assertState({DataPartState::Temporary});

    MergeTreePartInfo part_info = part->info;
    String part_name;

    if (DataPartPtr existing_part_in_partition = getAnyPartInPartition(part->info.partition_id, lock))
    {
        if (part->partition.value != existing_part_in_partition->partition.value)
            throw Exception(
                "Partition value mismatch between two parts with the same partition ID. Existing part: "
                + existing_part_in_partition->name + ", newly added part: " + part->name,
                ErrorCodes::CORRUPTED_DATA);
    }

....
}
`

**Comment by CurtizJ** [comment]
If `getAnyPartInPartition` will return `nullptr` we won't fall to the `if ` and there won't be null pointer dereference.
