### ISSUE TITLE
Unknown table engine / table function s3 when using clickhouse-local

### ISSUE THREAD

**Issue by chrisgoddard** [ClickHouse/ClickHouse#25825]
I'm trying to use clickhouse-local to pull some data from an S3 bucket. The query works fine on Clickhouse Server, but when I run in clickhouse-local I get an error "Unknown table function s3"

```
./clickhouse local --query "select * FROM s3('https://bucket.s3.amazonaws.com/other/file*.csv', 'xxx', 'yyy', 'CSVWithNames', 'ID Int64, SecondID Int64, ResponseCodeID	Int64, DataSourceId	Int64, CreatedOn Timestamp, mappedResponseCodeId Int64')"
```

I also tried defining as a table engine and then querying:

```
./clickhouse local --query "CREATE TABLE s3_engine_table (ID Int64, SecondID Int64, ResponseCodeID	Int64, DataSourceId	Int64, CreatedOn Timestamp, mappedResponseCodeId Int64)
ENGINE = s3('https://bucket.s3.amazonaws.com/other/file*.csv', 'xxx', 'yyy/ze3hC', 'CSVWithNames');
select *
from s3_engine_table"
```

Here I got "Unknown table engine s3".

I'm using version 21.7.1.7136 (official build)

Is s3 not supported at all through clickhouse-local or is there some configuration I'm missing?

**Comment by alexey-milovidov** [comment]
I've got:

```
Unknown table engine s3. Maybe you meant: ['S3']
```

Which answers the question.

**Comment by alexey-milovidov** [comment]
Table engine with Capital letter: S3.
Table function with lowercase letter: s3.

**Comment by alexey-milovidov** [comment]
I also have one thought... maybe you are using clickhouse-local built for non-Linux, where integration with s3 may be disabled.

**Comment by chrisgoddard** [comment]
Ah that must be it - I'm using it on OSX. I tried both upper and lower case for both.

Just out of interest, why is that disabled in the MacOSx binary?

**Comment by alexey-milovidov** [comment]
Most likely it is just not configured for build, but can be added easily.
