### ISSUE TITLE
Use JDBC to insert a distributed table, and the local engine is a replicatedMergeTree, and the number of data items is always inconsistent.

### ISSUE THREAD

**Issue by HavAnIdea** [ClickHouse/ClickHouse#25843]
Now there are 4 CK servers A, B, C, D  the cluster's configuration like (2shards_2replicas: s1{A,B}, s2{C,D})

local table DDL :
create table t on 3shards_1replicas (columns) engine = ReplicatedMergeTree('clickhouse/table/{shard}/default/t', {replica})

I used JDBC to insert a distributed table, and the local engine is a replicatedMergeTree.

First, 
```java

            ClickHouseProperties properties = new ClickHouseProperties();
            properties.setUser(prop.getProperty("user"));
            properties.setPassword(prop.getProperty("password"));
            ClickHouseDataSource clickHouseDataSource = new ClickHouseDataSource(url, properties);
            Connection connection = clickHouseDataSource.getConnection();

            connection.setAutoCommit(false);
            preparedStatement = connection.prepareStatement(this.writeRecordSql);

            for (Record record : buffer) {
                preparedStatement = fillPreparedStatement(preparedStatement, record);
                preparedStatement.addBatch();
            }
            preparedStatement.executeBatch();
            connection.commit();
```
When `buffer` has more than 4096 identical records, query the distributed table and found that n*2048 pieces of data are missing.
When I check the information and find that there are duplicate data blocks, the duplicate data blocks will be deleted by default.

Second,
I added a configuration to connection，`insert_deduplicate = 1`, it exists in ClickHouse/src/Core/Settings.h
```java
            ClickHouseProperties properties = new ClickHouseProperties();
            properties.setUser(prop.getProperty("user"));
            properties.setPassword(prop.getProperty("password"));
            // add this
            properties.setInsertDeduplicate(false);
            ClickHouseDataSource clickHouseDataSource = new ClickHouseDataSource(url, properties);
            Connection connection = clickHouseDataSource.getConnection();

            connection.setAutoCommit(false);
            preparedStatement = connection.prepareStatement(this.writeRecordSql);

            for (Record record : buffer) {
                preparedStatement = fillPreparedStatement(preparedStatement, record);
                preparedStatement.addBatch();
            }
            preparedStatement.executeBatch();
            connection.commit();
```

This time I insert a piece of data and query two pieces of the same data.

So, What should I do to insert it normally？

**Comment by den-crane** [comment]
> connection.setAutoCommit(false);
>  connection.commit();

CH does not support transaction. This two line do nothing. 
Insert deduplication is a feature https://clickhouse.tech/docs/en/engines/table-engines/mergetree-family/replication/

_Data blocks are deduplicated. For multiple writes of the same data block (data blocks of the same size containing the same rows in the same order), the block is only written once. The reason for this is in case of network failures when the client application does not know if the data was written to the DB, so the INSERT query can simply be repeated. It does not matter which replica INSERTs were sent to with identical data. INSERTs are idempotent._

It's your responsibility to make blocks are not identical by adding some uniq info (i.e. column with uniq insert_id) or disable  insert_deduplicate = 0

**Comment by inertance** [comment]
i do it also , but a error occur : Method write is not supported by storage Distributed with more than one shard and no sharding key provided (version 20.8.18.32 (official build))
