### ISSUE TITLE
Max vs Order by desc limit 1

### ISSUE THREAD

**Issue by kullanici0606** [ClickHouse/ClickHouse#25848]
I have a table where I need to query current maximum value constantly. Therefore I tried to use `max` aggregate function and even though it runs on a sorting key column, it looks like it is scanning all the rows. However, when I change the query to `order by column desc limit 1`, it returns a lot faster. Is it the expected behaviour or am I doing something wrong?

Clickhouse version: 21.4.6.55-2

**Table definition:**

    CREATE TABLE testing.stats
    (
        `stat_date` DateTime('UTC') CODEC(DoubleDelta),
        `tag` String,
        `area` String,
        `description` String
    )
    ENGINE = MergeTree
    PARTITION BY toYYYYMMDD(stat_date)
    ORDER BY (stat_date, tag)
    SETTINGS storage_policy = 'moving_from_ssd_to_hdd', index_granularity = 8192

**Queries**:
`select max(stat_date) from testing.stats`
`1 rows in set. Elapsed: 4.677 sec. Processed 30.61 billion rows, 122.44 GB (6.54 billion rows/s., 26.18 GB/s.) `

vs
`select stat_date from testing.stats order by stat_date desc limit 1`
`1 rows in set. Elapsed: 0.146 sec. Processed 8.89 million rows, 35.58 MB (61.04 million rows/s., 244.16 MB/s.)`

**Explaing for max query:**

    EXPLAIN
    SELECT max(stat_date)
    FROM testing.stats
    
    Query id: 1554e1aa-09d8-4d5d-b67d-7eb44f32359f
    
    ┌─explain───────────────────────────────────────────────────────────────────────┐
    │ Expression ((Projection + Before ORDER BY))                                   │
    │   Aggregating                                                                 │
    │     Expression (Before GROUP BY)                                              │
    │       SettingQuotaAndLimits (Set limits and quota after reading from storage) │
    │         ReadFromStorage (MergeTree)                                           │
    └───────────────────────────────────────────────────────────────────────────────┘

**Explain for order by query**

    EXPLAIN
    SELECT stat_date
    FROM testing.stats
    ORDER BY stat_date DESC
    LIMIT 1
    
    Query id: a426bb3f-fdf3-47cd-a81c-e3f45639283f
    
    ┌─explain─────────────────────────────────────────────────────────────────────────┐
    │ Expression (Projection)                                                         │
    │   Limit (preliminary LIMIT)                                                     │
    │     FinishSorting                                                               │
    │       Expression (Before ORDER BY)                                              │
    │         SettingQuotaAndLimits (Set limits and quota after reading from storage) │
    │           Expression (Remove unused columns after reading from storage)         │
    │             Union                                                               │
    │               MergingSorted (Merge sorting mark ranges)                         │
    │                 Expression (Calculate sorting key prefix)                       │
    │                   ReverseRows                                                   │
    │                     ReadFromStorage (MergeTree with order)                      │
    │               MergingSorted (Merge sorting mark ranges)                         │
    │                 Expression (Calculate sorting key prefix)                       │
    │                   ReverseRows                                                   │
    │                     ReadFromStorage (MergeTree with order)                      │
    │               MergingSorted (Merge sorting mark ranges)                         │
    │                 Expression (Calculate sorting key prefix)                       │
    │                   ReverseRows                                                   │
    │                     ReadFromStorage (MergeTree with order)                      │
    │               MergingSorted (Merge sorting mark ranges)                         │
    │                 Expression (Calculate sorting key prefix)                       │
    │                   ReverseRows                                                   │
    │                     ReadFromStorage (MergeTree with order)                      │
    │               MergingSorted (Merge sorting mark ranges)                         │
    │                 Expression (Calculate sorting key prefix)                       │
    │                   ReverseRows                                                   │
    │                     ReadFromStorage (MergeTree with order)                      │
    │               MergingSorted (Merge sorting mark ranges)                         │
    │                 Expression (Calculate sorting key prefix)                       │
    │                   ReverseRows                                                   │
    │                     ReadFromStorage (MergeTree with order)                      │
    │               MergingSorted (Merge sorting mark ranges)                         │
    │                 Expression (Calculate sorting key prefix)                       │
    │                   ReverseRows                                                   │
    │                     ReadFromStorage (MergeTree with order)                      │
    │               MergingSorted (Merge sorting mark ranges)                         │
    │                 Expression (Calculate sorting key prefix)                       │
    │                   ReverseRows                                                   │
    │                     ReadFromStorage (MergeTree with order)                      │
    │               MergingSorted (Merge sorting mark ranges)                         │
    │                 Expression (Calculate sorting key prefix)                       │
    │                   ReverseRows                                                   │
    │                     ReadFromStorage (MergeTree with order)                      │
    │               MergingSorted (Merge sorting mark ranges)                         │
    │                 Expression (Calculate sorting key prefix)                       │
    │                   ReverseRows                                                   │
    │                     ReadFromStorage (MergeTree with order)                      │
    │               MergingSorted (Merge sorting mark ranges)                         │
    │                 Expression (Calculate sorting key prefix)                       │
    │                   ReverseRows                                                   │
    │                     ReadFromStorage (MergeTree with order)                      │
    │               MergingSorted (Merge sorting mark ranges)                         │
    │                 Expression (Calculate sorting key prefix)                       │
    │                   ReverseRows                                                   │
    │                     ReadFromStorage (MergeTree with order)                      │
    │               MergingSorted (Merge sorting mark ranges)                         │
    │                 Expression (Calculate sorting key prefix)                       │
    │                   ReverseRows                                                   │
    │                     ReadFromStorage (MergeTree with order)                      │
    │               MergingSorted (Merge sorting mark ranges)                         │
    │                 Expression (Calculate sorting key prefix)                       │
    │                   ReverseRows                                                   │
    │                     ReadFromStorage (MergeTree with order)                      │
    │               MergingSorted (Merge sorting mark ranges)                         │
    │                 Expression (Calculate sorting key prefix)                       │
    │                   ReverseRows                                                   │
    │                     ReadFromStorage (MergeTree with order)                      │
    │               MergingSorted (Merge sorting mark ranges)                         │
    │                 Expression (Calculate sorting key prefix)                       │
    │                   ReverseRows                                                   │
    │                     ReadFromStorage (MergeTree with order)                      │
    │               MergingSorted (Merge sorting mark ranges)                         │
    │                 Expression (Calculate sorting key prefix)                       │
    │                   ReverseRows                                                   │
    │                     ReadFromStorage (MergeTree with order)                      │
    │               MergingSorted (Merge sorting mark ranges)                         │
    │                 Expression (Calculate sorting key prefix)                       │
    │                   ReverseRows                                                   │
    │                     ReadFromStorage (MergeTree with order)                      │
    │               MergingSorted (Merge sorting mark ranges)                         │
    │                 Expression (Calculate sorting key prefix)                       │
    │                   ReverseRows                                                   │
    │                     ReadFromStorage (MergeTree with order)                      │
    │               MergingSorted (Merge sorting mark ranges)                         │
    │                 Expression (Calculate sorting key prefix)                       │
    │                   ReverseRows                                                   │
    │                     ReadFromStorage (MergeTree with order)                      │
    │               MergingSorted (Merge sorting mark ranges)                         │
    │                 Expression (Calculate sorting key prefix)                       │
    │                   ReverseRows                                                   │
    │                     ReadFromStorage (MergeTree with order)                      │
    │               MergingSorted (Merge sorting mark ranges)                         │
    │                 Expression (Calculate sorting key prefix)                       │
    │                   ReverseRows                                                   │
    │                     ReadFromStorage (MergeTree with order)                      │
    │               MergingSorted (Merge sorting mark ranges)                         │
    │                 Expression (Calculate sorting key prefix)                       │
    │                   ReverseRows                                                   │
    │                     ReadFromStorage (MergeTree with order)                      │
    │               MergingSorted (Merge sorting mark ranges)                         │
    │                 Expression (Calculate sorting key prefix)                       │
    │                   ReverseRows                                                   │
    │                     ReadFromStorage (MergeTree with order)                      │
    │               MergingSorted (Merge sorting mark ranges)                         │
    │                 Expression (Calculate sorting key prefix)                       │
    │                   ReverseRows                                                   │
    │                     ReadFromStorage (MergeTree with order)                      │
    │               MergingSorted (Merge sorting mark ranges)                         │
    │                 Expression (Calculate sorting key prefix)                       │
    │                   ReverseRows                                                   │
    │                     ReadFromStorage (MergeTree with order)                      │
    │               MergingSorted (Merge sorting mark ranges)                         │
    │                 Expression (Calculate sorting key prefix)                       │
    │                   ReverseRows                                                   │
    │                     ReadFromStorage (MergeTree with order)                      │
    │               MergingSorted (Merge sorting mark ranges)                         │
    │                 Expression (Calculate sorting key prefix)                       │
    │                   ReverseRows                                                   │
    │                     ReadFromStorage (MergeTree with order)                      │
    │               MergingSorted (Merge sorting mark ranges)                         │
    │                 Expression (Calculate sorting key prefix)                       │
    │                   ReverseRows                                                   │
    │                     ReadFromStorage (MergeTree with order)                      │
    │               MergingSorted (Merge sorting mark ranges)                         │
    │                 Expression (Calculate sorting key prefix)                       │
    │                   ReverseRows                                                   │
    │                     ReadFromStorage (MergeTree with order)                      │
    │               MergingSorted (Merge sorting mark ranges)                         │
    │                 Expression (Calculate sorting key prefix)                       │
    │                   ReverseRows                                                   │
    │                     ReadFromStorage (MergeTree with order)                      │
    │               MergingSorted (Merge sorting mark ranges)                         │
    │                 Expression (Calculate sorting key prefix)                       │
    │                   ReverseRows                                                   │
    │                     ReadFromStorage (MergeTree with order)                      │
    │               MergingSorted (Merge sorting mark ranges)                         │
    │                 Expression (Calculate sorting key prefix)                       │
    │                   ReverseRows                                                   │
    │                     ReadFromStorage (MergeTree with order)                      │
    │               MergingSorted (Merge sorting mark ranges)                         │
    │                 Expression (Calculate sorting key prefix)                       │
    │                   ReverseRows                                                   │
    │                     ReadFromStorage (MergeTree with order)                      │
    │               MergingSorted (Merge sorting mark ranges)                         │
    │                 Expression (Calculate sorting key prefix)                       │
    │                   ReverseRows                                                   │
    │                     ReadFromStorage (MergeTree with order)                      │
    │               MergingSorted (Merge sorting mark ranges)                         │
    │                 Expression (Calculate sorting key prefix)                       │
    │                   ReverseRows                                                   │
    │                     ReadFromStorage (MergeTree with order)                      │
    │               MergingSorted (Merge sorting mark ranges)                         │
    │                 Expression (Calculate sorting key prefix)                       │
    │                   ReverseRows                                                   │
    │                     ReadFromStorage (MergeTree with order)                      │
    │               MergingSorted (Merge sorting mark ranges)                         │
    │                 Expression (Calculate sorting key prefix)                       │
    │                   ReverseRows                                                   │
    │                     ReadFromStorage (MergeTree with order)                      │
    │               MergingSorted (Merge sorting mark ranges)                         │
    │                 Expression (Calculate sorting key prefix)                       │
    │                   ReverseRows                                                   │
    │                     ReadFromStorage (MergeTree with order)                      │
    │               MergingSorted (Merge sorting mark ranges)                         │
    │                 Expression (Calculate sorting key prefix)                       │
    │                   ReverseRows                                                   │
    │                     ReadFromStorage (MergeTree with order)                      │
    └─────────────────────────────────────────────────────────────────────────────────┘

**Comment by den-crane** [comment]
it is the expected behaviour.

ORDER BY is optimized to use matching index / table order. MAX is not optimized.

**Comment by kullanici0606** [comment]
Thanks for the answer Denny.

**Comment by alexey-milovidov** [comment]
Duplicate https://github.com/ClickHouse/ClickHouse/issues/329

**Comment by chinarjf** [comment]
@den-crane 
I noticed that in version 22.238.14.6, the query using `MAX` is faster than the one using `ORDER BY DESC LIMIT 1`. Has the `MAX` function been optimized?
