### ISSUE TITLE
ANTLR parser: Missing column when casting with Postgresql style cast

### ISSUE THREAD

**Issue by Algunenano** [ClickHouse/ClickHouse#25855]
**Describe the bug**

When using the antrl parser, using CAST on a column works:

```
SELECT CAST(type, 'String')
:-] FROM system.query_log
:-] ORDER BY event_time_microseconds DESC
:-] LIMIT 1

SELECT CAST(type, 'String')
FROM system.query_log
ORDER BY event_time_microseconds DESC
LIMIT 1

Query id: 2248ed6f-15b0-40b5-800d-5e49b7043c6a

┌─CAST(type, 'String')─┐
│ ExceptionBeforeStart │
└──────────────────────┘

1 rows in set. Elapsed: 0.041 sec. Processed 2.54 thousand rows, 22.83 KB (61.54 thousand rows/s., 553.90 KB/s.)
```

But using `::` doesn't:

```
SELECT type::String
:-] FROM system.query_log
:-] ORDER BY event_time_microseconds DESC LIMIT 1;

SELECT CAST(type, 'String')
FROM system.query_log
ORDER BY event_time_microseconds DESC
LIMIT 1

Query id: ecbf836d-7e3d-4694-8e2f-9eb56ea839ec


0 rows in set. Elapsed: 0.007 sec. 

Received exception from server (version 21.8.1):
Code: 47. DB::Exception: Received from localhost:9000. DB::Exception: Missing columns: 'type' while processing query: 'SELECT type', required columns: 'type'.
```

Although the queries reported back by the backend are the same, the second one throws an exception.

**Does it reproduce on recent release?**

* master/HEAD: KO
* v21.7.1.7020-testing: KO
* v21.6.5.37-stable: KO

**Expected behavior**

Both queries should work the same way (same as the production parser).

**Additional context**

The production parser works fine in all tested releases (21.6, 21.7 and master).

**Comment by alexey-milovidov** [comment]
@Algunenano I'm wondering why do you use ANTLR parser? What are the benefits?

**Comment by Algunenano** [comment]
I don't use it. I only discovered this because the CI complained about this while working on other things (https://github.com/ClickHouse/ClickHouse/pull/25714). To be honest I did try the Antrl parser + conversion from new to old for a different project and saw that it was ~10x slower so I wouldn't mind if it was removed tomorrow.
