### ISSUE TITLE
Command-line client: Show actual database name in shell prompt

### ISSUE THREAD

**Issue by jirisamek** [ClickHouse/ClickHouse#25887]
**Use case**
I am using ClickHouse command line client to connect to ClickHouse cluster  with multiple databases. When executing SQL commands I would like to easily see in which database they are being executed.

**Describe the solution you'd like**
I would like to have database name shown in the prefix of the command prompt.

**Comment by den-crane** [comment]
it's already implemented

check /etc/clickhouse-client/config.xml

```
 <prompt_by_server_display_name>
        <default>{display_name} {database} {user} :) </default>
```

**Comment by den-crane** [comment]
Though it has a bug. If default database is not names default.

```
xxxxxxxxxxxx default default :) select currentDatabase();

SELECT currentDatabase()

┌─currentDatabase()─┐
│ dw                │
└───────────────────┘
```

**Comment by jirisamek** [comment]
I see, perfect. Thank you for the quick reply.
