### ISSUE TITLE
ARRAY JOIN in Materialized View yields empty values

### ISSUE THREAD

**Issue by stergiotis** [ClickHouse/ClickHouse#25885]
**Describe the bug**

A materialized view similiar to the one below does insert rows with all columns populated from array values filled with the default values (empty string, 0 uint64).
```sql
CREATE MATERIALIZED VIEW blub TO foo AS SELECT col1,col2,arycol1,arycol2 FROM
    (SELECT col1,col2,arycol1,arycol2 FROM my_table WHERE length(arycol1) > 0) 
ARRAY JOINT arycol1,arycol2
````

**Does it reproduce on recent release?**

Yes (Version 21.6)

**How to reproduce**

Version 21.6.1.6689 on Linux amd64 (official build)

**Expected behavior**

I could not find any mentioned limitation of using ARRAY JOIN in a materialized view and therefore assumed that it works similiar as when used in 
```sql
INSERT INTO foo AS SELECT ....
```

**Comment by den-crane** [comment]
cannot reproduce. Can you provide repro?

```
21.6.5.37

create table S (col1 String, col2 String, arycol1 Array(String), arycol2 Array(String)) Engine=MergeTree order by col1;
create table D (col1 String, col2 String, arycol1 String , arycol2 String) Engine=MergeTree order by col1;

CREATE MATERIALIZED VIEW blub TO D AS SELECT col1, col2, arycol1, arycol2 FROM
    (SELECT col1, col2, arycol1, arycol2 FROM S WHERE length(arycol1) > 0) 
ARRAY JOIN arycol1 , arycol2

insert into S values( '1', '2', ['a','b'], ['a','b']) ( '3', '4', ['c','d'], ['c','d']) 

select * from D;
┌─col1─┬─col2─┬─arycol1─┬─arycol2─┐
│ 1    │ 2    │ a       │ a       │
│ 1    │ 2    │ b       │ b       │
│ 3    │ 4    │ c       │ c       │
│ 3    │ 4    │ d       │ d       │
└──────┴──────┴─────────┴─────────┘
```

**Comment by den-crane** [comment]
21.6.1 is obsolete. use 21.6.5.37

**Comment by stergiotis** [comment]
I am terribly sorry, haven't been able to reproduce on dev machine so far. I am speculating that it might be an edge case when bloom-filter indices and LowCardinality is involved.

Will upgrade the production system and re-open a fresh bug if still relevant.

Many thanks for your support and the great DB, love it!
