### ISSUE TITLE
Datetime64 invalid range specified

### ISSUE THREAD

**Issue by TemaSpb** [ClickHouse/ClickHouse#25901]
https://clickhouse.tech/docs/en/sql-reference/data-types/datetime64/

On this page stated that:
> Supported range from January 1, 1925 till December 31, 2283.

but DateTime64 has the same supported range as Datetime type ([1970-01-01 00:00:00, 2105-12-31 23:59:59]).
Is it a bug or incorrect documentation?

**Comment by den-crane** [comment]
ClickHouse release 21.4.1 2021-04-12
New Feature
    Extended range of DateTime64 to support dates from year 1925 to 2283.

```sql

SELECT
    toDateTime64('1927-01-01 01:01:01.434', 3) AS t,
    toInt64(t)

Query id: dce56106-0583-457a-88a0-716d0774ffa7

┌───────────────────────t─┬─toInt64(toDateTime64('1927-01-01 01:01:01.434', 3))─┐
│ 1927-01-01 01:01:01.434 │                                         -1356994739 │
└─────────────────────────┴─────────────────────────────────────────────────────┘
```
