### ISSUE TITLE
Code: 33. DB::Exception: Cannot read all data. : data for INSERT was parsed from stdin

### ISSUE THREAD

**Issue by Jack012a** [ClickHouse/ClickHouse#25905]
Hello all,

We have a process that is used to import data of RowBinary into ClickHouseDB.

For example,

`$ cat abc.rowbinary | clickhouse-client --query="insert into default.test FORMAT RowBinary"`

It has been working fine without issues. However, this morning, it crashed and reported the following errors:

> Code: 33. DB::Exception: Cannot read all data. Bytes read: 377261643. Bytes expected: 16812728239.: (at row 4)
> : data for INSERT was parsed from stdin

I manually checked the abc.rowbinary with clickhouse-local and the file looks fine. After I rerun the process, the file was imported correctly.

Question> What might cause this issues early this morning since I cannot reproduce the same error?

Thank you

**Comment by den-crane** [comment]
Bit-rot? https://en.wikipedia.org/wiki/Data_degradation Does your server have ECC memory?

Clickhouse version?

**Comment by q0987** [comment]
$ clickhouse-client --version
ClickHouse client version 21.4.6.55 (official build).

$ clickhouse-server --version
ClickHouse server version 21.4.6.55 (official build).

**Comment by den-crane** [comment]
1 Can you show column types `desc default.test` ?
2 What is the average size of  abc.rowbinary files?
3 How many files for you load per day in average?
4 Do you load several files in parallel?

**Comment by q0987** [comment]
1> Sorry, I cannot.

2> Each file is around 400MB

3> ~4000 files
But the issue happened on the first file of the day and the server at the time is idle.

4> we only insert one file at a time.

5> 250GB memory

I only got the following:
thread(MemoryTracker*, unsigned long)+0x1fa) [0x4190dfa]
thread(MemoryTracker*, unsigned long)+0x1fa) [0x4190dfa]
thread(MemoryTracker*, unsigned long)+0x1fa) [0x4190dfa]
thread(MemoryTracker*, unsigned long)+0x1fa) [0x4190dfa]

Thank you

**Comment by den-crane** [comment]
1 column types? Even without names?

**Comment by q0987** [comment]
Date, DateTime, String, UInt64, String, String, String, Float64, Float64, UInt8, UInt8, UInt8, Float64, ..., UInt8

ENGINE = MergeTree PARTITION BY date

Thank you

**Comment by den-crane** [comment]
I've realized that the error happened in clickhouse-client and is not related to server.

**Comment by georgemarsroberts** [comment]
So,how to fix this?final

**Comment by den-crane** [comment]
>cat abc.rowbinary | clickhouse-client --query="insert into default.test FORMAT RowBinary"

@georgemarsroberts In this particular case the issue is in `abc.rowbinary` probably it was corrupted / truncated.
