### ISSUE TITLE
Histograms & group by would be useful together

### ISSUE THREAD

**Issue by AllanLeanderRostockHansen** [ClickHouse/ClickHouse#25916]
**Use case**
[Histograms](https://clickhouse.tech/docs/en/sql-reference/aggregate-functions/parametric-functions/#histogram) are useful for  examining the distribution of a variable, but it's often interesting to compare several the distributions of a variable filtered by some other variable, which groupby is really useful for.
Combining the `histogram`-function with `group by` could be immensely useful for analytics.

(And if this is possible today, and example in the documentation would be useful!)

**Describe the solution you'd like**
That Clickhouse can combine the `histogram`-function with a `group by`, and an accompanying example in the docs.

**Additional context**
This kind of exploratory analysis is so common, that plotting-packages like [Seaborn have it build right in](https://seaborn.pydata.org/examples/faceted_histogram.html) – but plotting tools like these are usually require you to load the entire dataset in memory.

![image](https://user-images.githubusercontent.com/64133386/124284544-60ec5d80-db4d-11eb-94e8-b391aaf43f75.png)

**Comment by UnamedRus** [comment]
```
SELECT
    species,
    sex,
    histogram(10)(flipper_lenght_mm)
FROM
(
    SELECT
        CAST(rand64() % 3, 'Enum8(\'Adelie\' = 0, \'Chinstrap\' = 1, \'Gentoo\' = 2)') AS species,
        CAST(rand() % 2, 'Enum8(\'Male\' = 0, \'Female\' = 1)') AS sex,
        rand() % 300 AS flipper_lenght_mm
    FROM numbers(1000)
)
GROUP BY
    species,
    sex
    
SELECT
    species,
    sex,
    x,
    bar(arrayJoin(histogram(10)(flipper_lenght_mm).3) AS x, 0, 40)
FROM
(
    SELECT
        CAST(rand64() % 3, 'Enum8(\'Adelie\' = 0, \'Chinstrap\' = 1, \'Gentoo\' = 2)') AS species,
        CAST(rand() % 2, 'Enum8(\'Male\' = 0, \'Female\' = 1)') AS sex,
        rand() % 300 AS flipper_lenght_mm
    FROM numbers(1000)
)
GROUP BY
    species,
    sex
```

What is your problem?

**Comment by AllanLeanderRostockHansen** [comment]
Hmm, I think the query that I couldn't get to work had another problem, but thanks for the example of how to do this.

Would you mind if I submit a PR to the docs using the example code that you provided above? I could have used that myself :)
I will of course credit you with the code in the text accompanying text.

**Comment by UnamedRus** [comment]
> Would you mind if I submit a PR to the docs using the example code that you provided above? 

That would be appreciated. 

> I will of course credit you with the code in the text accompanying text.

Not needed at all. (Let's keep docs clear)
