### ISSUE TITLE
about bloom_filter

### ISSUE THREAD

**Issue by ys-zhaoyh** [ClickHouse/ClickHouse#25911]
May I ask, who can briefly introduce the realization principle of bloom_filter,not Bloom filter.

**Comment by alexey-milovidov** [comment]
The `bloom_filter` index is implemented using the Bloom Filter data structure.

**Comment by alexey-milovidov** [comment]
See the docs https://clickhouse.com/docs/en/guides/improving-query-performance/skipping-indexes/#bloom-filter-types for additional details.
