### ISSUE TITLE
Fuse some aggregate functions, part 2.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#25961]
Continuation of #20091

If query has multiple `quantile` aggregate functions with the same arguments but different level parameter:
```
SELECT quantile(0.5)(x), quantile(0.9)(x), quantile(0.95)(x) FROM ...
```

Rewrite it to
```
SELECT quantiles(0.5, 0.9, 0.95)(x)[1], quantiles(0.5, 0.9, 0.95)(x)[2], quantiles(0.5, 0.9, 0.95)(x)[3] FROM ...
```

So the aggregation will share the state.
This should be applied to every type of quantile calculation algorithm (quantile, quantileDeterministic, quantileTiming, quantileTDigest, quantileTDigestWeighted, quantileExact, quantileExactWeighted, quantileBFloat16).

**Comment by vmihailenco** [comment]
Could you also add `quantileBFloat16Weighted`?

**Comment by vdimir** [comment]
> Could you also add `quantileBFloat16Weighted`?

@vmihailenco 

Done with https://github.com/ClickHouse/ClickHouse/pull/29258

**Comment by vmihailenco** [comment]
Thank you :+1:
