### ISSUE TITLE
What's the max precision of datetime64

### ISSUE THREAD

**Issue by wangqinghuan1993** [ClickHouse/ClickHouse#25967]
Hi
 I do not get the decription of max precision datetime64 supports in [Datetime64](https://clickhouse.tech/docs/en/sql-reference/data-types/datetime64/) . Could you tell me or enrich [Datetime64](https://clickhouse.tech/docs/en/sql-reference/data-types/datetime64/) doc about max precision support?

**Comment by alexey-milovidov** [comment]
Nanoseconds (9 digits after decimal point).
