### ISSUE TITLE
CHANGELOG.md wasnt updated. Why?

### ISSUE THREAD

**Issue by awslabspl** [ClickHouse/ClickHouse#25971]
The file `CHANGELOG.md` hadnt been updated with whats been changed in new release and so on. Why?

**Comment by den-crane** [comment]
Chanelog is updated with some delay.
Currently the latest stable is 21.6. And changelog has info about 21.6 https://github.com/ClickHouse/ClickHouse/blob/master/CHANGELOG.md#clickhouse-release-216-2021-06-05

**Comment by awslabspl** [comment]
> Chanelog is updated with some delay.
> Currently the latest stable is 21.6. And changelog has info about 21.6 https://github.com/ClickHouse/ClickHouse/blob/master/CHANGELOG.md#clickhouse-release-216-2021-06-05

There was an release today. Its marked as `stable`. Why there is not mentioned in `Changelog`?

**Comment by den-crane** [comment]
Chanelog is updated with some delay.

**Comment by alexey-milovidov** [comment]
We don't update changelog for "patch" releases.
