### ISSUE TITLE
Why is the result of the Clickhouse query unstable

### ISSUE THREAD

**Issue by shadowDy** [ClickHouse/ClickHouse#25983]
Clickhouse version: 20.12.3

When I execute this SQL query on the distributed table:

41 results are returned.

When I executed it again, I found that 43 results were returned.

After comparison, I found the two missing data and confirmed that the missing data were not inserted during this period; And the two data are on the same slice;

Log in to the corresponding partition to view the log_ ID finds the query log of the partition. It is found that the query is returned successfully and there is no exception in the log; Comparing the two SQL logs, the missing query logs have the following doubts:

1: There are multiple slow read logs
2: Peak memory usage (for query): 0.00 B.

Why does this happen？
thanks.
![image](https://user-images.githubusercontent.com/18388143/124412312-cc6a4100-dd80-11eb-9fc5-e1d4c209a525.png)

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/18137
Fixed a long time ago.
You need to upgrade to at least 20.12.8.5 or set `read_backoff_min_latency_ms=0`

**Comment by shadowDy** [comment]
> read_backoff_min_latency_m
How to add or set this parameter, I didn't find this parameter in the document.
thanks~

**Comment by shadowDy** [comment]
> duplicate #18137
> Fixed a long time ago.
> You need to upgrade to at least to 20.12.8.5 or set `read_backoff_min_latency_ms=0`

How to add or set this parameter, I didn't find this parameter in the document.

**Comment by den-crane** [comment]
```
cat /etc/clickhouse-server/users.d/read_backoff_min_latency_ms.xml
<?xml version="1.0"?>
<yandex>
    <profiles>
        <default>
            <read_backoff_min_latency_ms>0</read_backoff_min_latency_ms>
        </default>
    </profiles>
</yandex>
```

**Comment by shadowDy** [comment]
> ```
> cat /etc/clickhouse-server/users.d/read_backoff_min_latency_ms.xml
> <?xml version="1.0"?>
> <yandex>
>     <profiles>
>         <default>
>             <read_backoff_min_latency_ms>0</read_backoff_min_latency_ms>
>         </default>
>     </profiles>
> </yandex>
> ```

thanks，This configuration seems to solve the problem
