### ISSUE TITLE
Force remote execution of function in postgressql funtion

### ISSUE THREAD

**Issue by Bornegio** [ClickHouse/ClickHouse#25987]
**Use case**
External databases uses custom functions or extension, so receiving data from that db is impossible (e.g postgis geo types).  

**Describe the solution you'd like**
Adding function like literal, that takes string with function and expected response data type as arguments. It sends function and force to execute it on remote db side.

**Comment by UnamedRus** [comment]
Related to https://github.com/ClickHouse/ClickHouse/issues/19320
