### ISSUE TITLE
Dictionary Updates with updateField not working (Postgres) 

### ISSUE THREAD

**Issue by tobiaslins** [ClickHouse/ClickHouse#25988]
**Describe the bug**

I've created an external dictionary with a Postgres source. The table has a `updateAt` column. When Clickhouse tries to refetch the updated columns, Postgres throws an error because the timestamp provided is not valid.

I see following error in clickhouse:
```
std::exception. Code: 1001, type: pqxx::data_exception, e.what() = ERROR:  date/time field value out of range: "1625475272"
LINE 1: ...tes" FROM "my_dictionary" WHERE "updatedAt" >= '162547527...
                                                             ^
HINT:  Perhaps you need a different "datestyle" setting.
 (version 21.3.9.83 (official build))
```

Is there a way to set a custom date format? it should be either a valid Unix timestamp or Iso timstamp

**How to reproduce**

* Which ClickHouse server version to use
ClickHouse 21.3.9.83

**Schema** 
Postgres:
```sql
CREATE TABLE my_dictionary (
    "userId" character varying,
    "projectId" character varying,
    notes character varying NOT NULL DEFAULT ''::character varying,
    "updatedAt" timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);
```

Clickhouse:
```sql
CREATE DICTIONARY my_dictionary (
  `userId` String,
  `projectId` String,
  `notes` String
) 
PRIMARY KEY projectId,userId 
SOURCE(
  POSTGRESQL(
    PORT 5432 HOST 'db' USER 'postgres' PASSWORD 'postgres' DB 'mydb' TABLE 'my_dictionary' UPDATE_FIELD '"updatedAt"'
  )
) LIFETIME(MIN 5 MAX 15) 
LAYOUT(COMPLEX_KEY_HASHED())
```

**Expected behavior**
There `where updatedAt` query should be using a valid timestamp depending on the source. postgres doesn't accept the format

**Error message and/or stacktrace**
```
std::exception. Code: 1001, type: pqxx::data_exception, e.what() = ERROR:  date/time field value out of range: "1625475272"
LINE 1: ...tes" FROM "my_dictionary" WHERE "updatedAt" >= '162547527...
                                                             ^
HINT:  Perhaps you need a different "datestyle" setting.
 (version 21.3.9.83 (official build))
```

**Comment by kitaisreal** [comment]
@tobiaslins please provide part of your dictionary and postgres table configuration for reproducible example.

**Comment by tobiaslins** [comment]
Hey @kitaisreal , just added it sorry!

**Comment by kitaisreal** [comment]
@tobiaslins checked on version 21.6.
Dictionary configuration
```xml
<dictionaries>
<dictionary>
    <name>postgres_test</name>
    <structure>
        <id>
            <name>id</name>
        </id>

        <attribute>
            <name>value</name>
            <type>String</type>
            <null_value></null_value>
        </attribute>
    </structure>

    <layout>
        <hashed/>
    </layout>

    <source>
        <postgresql>
            <host>127.0.0.1</host>
            <port>5432</port>
            <user>yetti</user>
            <password>asd2221</password>
            <db>test_db</db>
            <table>test_dictionary</table>
            <update_field>updated_at</update_field>
       </postgresql>
    </source>

    <lifetime>3</lifetime>
</dictionary>
</dictionaries>
```
PostgresTable
```sql
CREATE TABLE test_dictionary (id Integer, value Text, updated_at timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP);
```
ClickHouse send queries to Postgres like :
```sql
SELECT "id", "value" FROM "test_dictionary" WHERE updated_at >= '2021-07-05 13:50:26';
```

Could you please check on version 21.6 if your case will work ? I will check now on 21.3.

**Comment by kitaisreal** [comment]
@tobiaslins issue exists in 21.3 I successfully reproduced it.

**Comment by kitaisreal** [comment]
@tobiaslins it was fixed here https://github.com/ClickHouse/ClickHouse/commit/671395e8c81e79f079334650112737eca6e3f6c7#diff-c44c88fa71cecc689a30191d0379be5caa9391ad9718c763f35efbbdcb5901f8R131.
This commit goes into 21.4. Please check if it will fix your issue.

**Comment by tobiaslins** [comment]
@kitaisreal amazing! thank you for the fast responses and solution. I just upgraded to 21.6 and it seems to work fine now :)
