### ISSUE TITLE
The CH progress was killed by OOM killer

### ISSUE THREAD

**Issue by HyaZz** [ClickHouse/ClickHouse#25985]
Recently,our team meets a problem!The length of user's queries is big,even bigger than max_query_size sometime.In addition,some of them are RAM high-consumed including group by,join and so on.Our servers‘ RAM are 256G.The CH version is 20.8.5.45.The cluster have 45 nodes(15 shards & 3 replicas)

The correlative config settings at beginning are as follow:
1.max_query_size (default:256K)
2.max_memory_usage_for_user 230G
3.max_bytes_before_external_group_by 100G
4.max_bytes_before_external_sort 100G

The CH progress was killed by OOM killer now and then，just like this:
`[16944749.606371] Out of memory: Kill process 223459 (clickhouse-serv) score 958 or sacrifice child
[16944749.606463] Killed process 223459 (clickhouse-serv) total-vm:605840272kB, anon-rss:251523284kB, file-rss:0kB, shmem-rss:0kB`

We made an effort to solve this sutiation:
1.set max_query_size 512K
2.max_memory_usage 160G
3.max_memory_usage_for_user 180G
4.max_bytes_before_external_group_by 80G
5.max_bytes_before_external_sort 80G

But there is nothing to be change.The problem still exists.The memory limit exception didn't be thrown,so that can free the memory allocated to aviod to be killed by OOM killer.

So,we raise this issue for help.did anyone meet this problem too?and how to solve?and perhaps some untracked memory?Thanks!

**Comment by tom-clickhouse** [comment]
Can you please install the latest release if possible, and see if the issue still exists? There have been some improvements and bug fixes for OOM issues in the meantime.

**Comment by den-crane** [comment]
20.8 is out of support. Upgrade.
