### ISSUE TITLE
SELECT row of data is too slow

### ISSUE THREAD

**Issue by EgorKurito** [ClickHouse/ClickHouse#25990]
The following problem occurred in our project, which we cannot solve.
We have a huge data of our logs, and we go to ClickHouse from MongoDB.

Our table is created like this:
    
```SQL
CREATE TABLE IF NOT EXISTS logs ON CLUSTER default (
	raw         String,
	ts          DateTime64(6) MATERIALIZED toDateTime64(JSONExtractString(raw, 'date_time'), 6),
	device_id   String        MATERIALIZED JSONExtractString(raw, 'device_id'),
	level       Int8          MATERIALIZED JSONExtractInt(raw, 'level'),
	context     String        MATERIALIZED JSONExtractString(raw, 'context'),
	event       String        MATERIALIZED JSONExtractString(raw, 'event'),
	event_code  String        MATERIALIZED JSONExtractInt(raw, 'event_code'),
	data        String        MATERIALIZED JSONExtractRaw(raw, 'data'),
	date        Date          DEFAULT toDate(ts),
	week        Date          DEFAULT toMonday(ts)
)
ENGINE ReplicatedReplacingMergeTree()
ORDER BY (device_id, ts)
PARTITION BY week
```

and I'm running a query like so

```SQL
SELECT device_id,toDateTime(ts),context,level,event,data 
FROM logs 
WHERE device_id = 'some_uuid'
ORDER BY ts DESC 
LIMIT 10 
OFFSET 0;
```
this is the result 10 rows in set. **Elapsed: 6.23 sec.**

And second without order, limit and offset:
```SQL
SELECT device_id,toDateTime(ts),context,level,event,data 
FROM logs 
WHERE device_id = 'some_uuid'
```
this is the result **Elapsed: 7.994 sec.** for each 500 rows of 130000+

Is too slow. 

Seems that CH process all the rows in the table. What is wrong and what need to improve the speed of CH?

**Comment by kitaisreal** [comment]
Hello, @EgorKurito. Such table possibly can show some performance decrease during insert, but selects should be fast.
Can you provide some minimum reproducible syntetic example to check ?
Which version of ClickHouse do you use ? Thanks

**Comment by EgorKurito** [comment]
@kitaisreal Unfortunately, we will not be able to provide data from tables for privacy reasons (
We have about 2 billion records;
CH version is 21.6.5.37;

**Comment by den-crane** [comment]
@EgorKurito can you share result and statistics of `select uniq(_part) from logs`

**Comment by EgorKurito** [comment]
@den-crane 
```

SELECT uniq(_part)
FROM logs

Query id: cf7b75f9-56f2-43ec-a23c-6c4a9a5e53d7

┌─uniq(_part)─┐
│         628 │
└─────────────┘

1 rows in set. Elapsed: 364.509 sec. Processed 1.86 billion rows, 1.86 GB (5.10 million rows/s., 5.10 MB/s.)

chi-staging-default-0-0-0.chi-staging-default-0-0.staging-services.svc.cluster.local :) select uniq(week) from logs

SELECT uniq(week)
FROM logs

Query id: 89ef63c2-2229-4540-8386-a3a65c880ca8

┌─uniq(week)─┐
│        167 │
└────────────┘

1 rows in set. Elapsed: 174.511 sec. Processed 1.86 billion rows, 3.72 GB (10.64 million rows/s., 21.29 MB/s.)

```

One of the decision tools to search by week partitioning

**Comment by kitaisreal** [comment]
@EgorKurito is there any change that these MATERIALIZED columns where added with ALTER command ?
Can you please provide server characteristics ?
How many records are in table 2 billions ?
Maybe query is not slow.

**Comment by kitaisreal** [comment]
@EgorKurito could you please provide query_log data and query_thread_log data for queries that we try to optimise ?

**Comment by den-crane** [comment]
@EgorKurito 

>1 rows in set. Elapsed: 174.511 sec. Processed 1.86 billion rows, 3.72 GB (10.64 million rows/s., 21.29 MB/s.)

Your disk random i/o is very slow, what do you use as disks?  s3 ?

**Comment by EgorKurito** [comment]
**Update**
Sorry for slow answer, 
If I search by partition, like this:
```SQL
SELECT ts, raw
FROM logs
WHERE device_id = '0e38b9b9-df38-4560-8886-8645a32616a7'
  AND ts <= toDateTime64('2021-06-10T14:23:57.912', 6)
  AND week = toMonday(toDate('2021-06-10'))
ORDER BY ts DESC
LIMIT 10;
```
This is faster: 200-600ms
But if I just need to get the last 10,100, 1000 logs, this method will be inconvenient. 
@den-crane, @kitaisreal
