### ISSUE TITLE
timestamp clause not working properly

### ISSUE THREAD

**Issue by Kev1ntan** [ClickHouse/ClickHouse#26000]
**Describe the unexpected behaviour**
The following problem occurred in our project, which we cannot solve.
Our table is created like this: 

```sql
    CREATE TABLE if not exists replicated_aixp_combined_user_events (
      id String DEFAULT '',
      type String DEFAULT '',
      original_timestamp DateTime64(3) DEFAULT parseDateTimeBestEffort('0001-1-1 23:00:00') Codec(DoubleDelta, LZ4),
      Sign Int8 DEFAULT 1,
      Version UInt64 DEFAULT 1
    ) engine = ReplicatedVersionedCollapsingMergeTree(path, replica, Sign, Version)
    PARTITION BY toWeek(original_timestamp)
    ORDER BY (id, original_timestamp)
    SETTINGS index_granularity = 8192;
```

and i'm running a query like:
```sql
select original_timestamp from replicated_aixp_combined_user_events
where type='identify'
and original_timestamp >= parseDateTimeBestEffortOrNull('2020-05-09T17:00:00.000Z')
order by original_timestamp asc
limit 100
```
the results is(order ascending):
original_timestamp 
2021-05-02 00:00:00
2021-05-02 00:00:00
2021-05-02 00:00:02
2021-05-02 00:00:02
...

there are millions rows with original_timestamp before 2021-May, but the query results only rows after 2021-May. 

another case if i run a query like(change 2020-05 to 2020-03):
```sql
select original_timestamp from replicated_aixp_combined_user_events
where type='identify'
and original_timestamp >= parseDateTimeBestEffortOrNull('2020-03-09T17:00:00.000Z')
order by original_timestamp asc
limit 100
```
the results is(order ascending):
2021-03-07 00:00:04
2021-03-07 00:00:08
2021-03-07 00:00:28
2021-03-07 00:00:52
2021-03-07 00:01:09
...

thats the proof that before 2021-May we have more rows to show, but why the result only start after 2021-05(for the first case) and 2021-03(for the second case). anyone can help with this issue?

clickhouse version "20.12.3"

**Comment by den-crane** [comment]
20.12.3 is obsolete, check with 21.5 or 21.6
and check result with parseDateTime64BestEffortOrNull

```
>= parseDateTime64BestEffortOrNull('2020-05-09T17:00:00.000Z')
```

**Comment by Kev1ntan** [comment]
@den-crane thanks, working properly with 21.6
