### ISSUE TITLE
The Performance of Join Fact Tables with Large Dimension Tables Is Poor

### ISSUE THREAD

**Issue by wallace-clickhouse** [ClickHouse/ClickHouse#26019]
I find the performance of join fact tables with large dimension tables in ClickHouse is poor，is there any plan to optimize this performance weakness in future versions?

Thank you!

**Comment by den-crane** [comment]
Yes, there are plans to implement grace-join and merge-join in the future.

**Comment by helifu** [comment]
hi @den-crane , is there any issue or link about grace-join/merge-join ? thanks in advance : )
