### ISSUE TITLE
Mixed versions in a cluster: Backwards compatibility broken when using aggregate functions w/ aliases over distributed tables

### ISSUE THREAD

**Issue by nvartolomei** [ClickHouse/ClickHouse#26027]
I'm trying to test upgrade path from 20.8 to the latest version and found that queries that involve aliases fail.

I have built a test case and submitted it as a PR as well 26028.
node1 is master
node2 is v19.16

```python
    node1.query("create table tab (x UInt64, x_alias UInt64 ALIAS x) engine = Memory")
    node2.query("create table tab (x UInt64, x_alias UInt64 ALIAS x) engine = Memory")
    node1.query('insert into tab values (1)')
    node2.query('insert into tab values (1)')

    node1.query("select sum(x_alias) from remote('node{1,2}', default, tab)")
    node2.query("select sum(x_alias) from remote('node{1,2}', default, tab)")
```

Last query fails w/ `Code: 10. DB::Exception: Received from 172.16.1.3:9000. DB::Exception: Not found column sum(x_alias) in block. There are only columns: sum(x)`

**Comment by alexey-milovidov** [comment]
The best option is to simply continue and upgrade the rest of the nodes in a cluster. The chance this incompatibility will be addressed is low.
