### ISSUE TITLE
why force_data_skipping_indices , indexHint 

### ISSUE THREAD

**Issue by Data-bytes305** [ClickHouse/ClickHouse#26029]
clickhouse version: 21.7.1.7029

Table ddl:
CREATE TABLE dw.xxxxxx
(
    `stk_day` Date,
    `shopid` String,
    `goodsid` String,
    `qty` Decimal(18, 4),
    `cost` Decimal(18, 4),
    `costvalue` Decimal(18, 4),
    `bu` UInt16,
    `key_goodsid` UInt64 DEFAULT cityHash64(concat(toString(bu), '-', goodsid)),
    `key_shop_goodsid` UInt64 DEFAULT cityHash64(concat(shopid, '-', goodsid)),
    `venderid` String,
    INDEX ind_goodsid goodsid TYPE bloom_filter(0.025) GRANULARITY 4
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(stk_day)
ORDER BY (stk_day, shopid)
SETTINGS index_granularity = 8192

rows: 6327264813

count(distinct goodsid): 357092

query_1:
        select shopid, sum(qty), sum(qty)
        from xxxxxx
        where goodsid = '23576'
        group by shopid;

1371 rows in set. Elapsed: 173.955 sec. Processed 6.33 billion rows, 151.07 GB (36.37 million rows/s., 868.45 MB/s.)

query_2:
    select shopid, sum(qty), sum(qty)
    from xxxxxx
    where indexHint(goodsid = '23576')
    group by shopid;

2077 rows in set. Elapsed: 11.371 sec. Processed 6.33 billion rows, 137.26 GB (556.46 million rows/s., 12.07 GB/s.)

query_3:
        select shopid, sum(qty), sum(qty)
        from xxxxxx
        where goodsid = '23576'
        group by shopid
        settings force_data_skipping_indices='ind_goodsid';

1371 rows in set. Elapsed: 99.897 sec. Processed 6.33 billion rows, 151.07 GB (63.34 million rows/s., 1.51 GB/s.)

question_1: 
        Why are the results of query_1 and query_2 different and the performance difference is so big ?

question_2: 
        Why query_1 does not use the index ?

question_3:
        Is there any other way to make it faster？

**Comment by den-crane** [comment]
Can you show the same for

```
select shopid, sum(qty), sum(qty)
from xxxxxx
where identity(goodsid) = '23576'
group by shopid
```

I think indexHint disables ind_goodsid bloom_filter index. Because in this case this index is bad.
