### ISSUE TITLE
clickhouse subtracts hours on insert

### ISSUE THREAD

**Issue by depyronick** [ClickHouse/ClickHouse#26024]
While inserting exact same data with exact method and exact time, all of a sudden clickhouse starts to subtract two hours. Also the table DDLs are exactly same too.

![image](https://user-images.githubusercontent.com/13220891/124594003-f64a6300-de67-11eb-9b5a-d5f9096b2b34.png)

The terminal on right side shows what it should be.

On right CH version: 21.3.2.5
On left CH version: 21.6.5.37

**Comment by den-crane** [comment]
can you share `select timezone()` from both servers?

**Comment by depyronick** [comment]
> can you share `select timezone()` from both servers?

Server on left has timezone config set to UTC on config.xml but the server on the right uses default configurations.

Server on left shows `UTC` and `Europe/Berlin` on right.

I've made a few more tests, it seems like the issue is that if I use `remote` function, like `INSERT INTO table SELECT * FROM remote()`, it inserts by converting the time. 

But if I insert new data with HTTP interface, it inserts as is.

**Comment by depyronick** [comment]
So, i've tried using `--use_client_time_zone` setting with `clickhouse-client` it seems it now inserts what it reads. 

Is this the correct way to do that? I am trying to insert from one server with Berlin timezone to another with UTC, without changing any value...

**Comment by den-crane** [comment]
>I am trying to insert from one server with Berlin timezone to another with UTC, without changing any value...

It seems you insert datetime incorrectly using HTTP.

CH stores datetime in UTC only, no matter what.
TZ are applied when string are rendered or parsed.

`INSERT INTO table SELECT * FROM remote()` -- does nothing with TZ. Just copies data as is.

When you query data using clickhouse-client you get data in server TZ by default.

When you insert data using HTTP TZ can be applied if you insert use string format but not than timestamp.

**Comment by depyronick** [comment]
Imagine two servers

**Server #1** with OS timezone set to _Europe/Berlin_ and clickhouse server timezone set to _Europe/Berlin_ and with clickhouse version of _21.3.2.5_.

**Server #2** with OS timezone set to _Europe/Berlin_ and clickhouse server timezone set to _UTC_ and with clickhouse version of _21.6.5.37_

And now imagine a data with datetime value on Server #1, and is inserted via HTTP interface.

```
┌─dt_value─┐
2021-01-01 00:00:00
```

Now, if you do this on Server #2 via clickhouse-client: `INSERT INTO tableOnServerTwo SELECT * FROM remote('serverone' ...)`

This is what you get on Server #2

```
┌─dt_value─┐
2020-12-31 22:00:00
```

On both servers table column:

`dt_value` DateTime CODEC(DoubleDelta, LZ4),`

So... It does converts.

**Comment by den-crane** [comment]
When you insert into server1 using HTTP 2021-01-01 00:00:00 -- CH thinks that '2021-01-01 00:00:00' (BERLIN TZ) and stores in a table value 1609455600 -- 2020-12-31 23:00:00 UTC

When you insert into server2 using HTTP 2021-01-01 00:00:00 -- CH thinks that '2021-01-01 00:00:00' (UTC) and stores in a table value 1609459200 -- '2021-01-01 00:00:00 UTC

When you load from server2 into server1 value 1609459200, it stored in server1 as 1609459200

Because CH stores data only as UTC timestamps.

I'm closing this. Let's continue in Alitinity zendesk. Because everything works as expected.

**Comment by depyronick** [comment]
Alright got it. I've inserted values using `date_add(HOUR, 2, dt_value) as dt_value` and it's all ok.
