### ISSUE TITLE
What is the meaning of the commands in clickhouse 21.4.5.46 version?

### ISSUE THREAD

**Issue by mjh568412187** [ClickHouse/ClickHouse#26035]
You have to provide the following information whenever possible.

**Describe the bug**

A clear and concise description of what works not as it is supposed to.

**Does it reproduce on recent release?**

[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

**Enable crash reporting**

If possible, change "enabled" to true in "send_crash_reports" section in `config.xml`:

```
<send_crash_reports>
        <!-- Changing <enabled> to true allows sending crash reports to -->
        <!-- the ClickHouse core developers team via Sentry https://sentry.io -->
        <enabled>false</enabled>
```

**How to reproduce**

* Which ClickHouse server version to use
* Which interface to use, if matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

**Expected behavior**

**Error message and/or stacktrace**

**Additional context**

---
`[root@xxxx ~]# /etc/init.d/clickhouse-server status
/var/run/clickhouse-server/clickhouse-server.pid file exists and contains pid = 99176.
The process with pid = 99176 is running.
Usage: /etc/init.d/clickhouse-server {start|stop|status|restart|forcestop|forcerestart|reload|condstart|condstop|condrestart|condreload|initdb}`

My friend clearly help explain

For example, I modified the configuration file of clickhouse, how can it be hot-loaded without restarting the clickhouse service?

For example, nginx, you can use nginx reload

I tested it in the current version of clickhouse
[root@ckshard12 ~]# /etc/init.d/clickhouse-server reload
Init script is already running

service clickhouse-server start
service clickhouse-server stop
service clickhouse-server restart
service clickhouse-server forcestop
service clickhouse-server forcerestart
service clickhouse-server reload
service clickhouse-server condstart
service clickhouse-server condstop
service clickhouse-server condrestart
service clickhouse-server condreload
service clickhouse-server initdb

Not sure if it is feasible

I am not sure what does |forcestop|forcerestart|reload|condstart|condstop|condrestart|condreload|initdb mean?

**Comment by den-crane** [comment]
>For example, I modified the configuration file of clickhouse, how can it be hot-loaded without restarting the clickhouse service?

Some parameters are applied automatically, no actions required other parameters require full restart  `service clickhouse-server restart` . 

```
Settings & restart

All users settings don’t need server restart but applied on connect. User need to reconnect to Clickhouse server.

Most of server settings applied only on a server start, except sections:

    <remote_servers> (cluster config)

    <dictionaries> (ext.dictionaries)

    <max_table_size_to_drop> & <max_partition_size_to_drop>

```

https://kb.altinity.com/altinity-kb-setup-and-maintenance/altinity-kb-server-config-files#Serverconfigfiles-Settings&restart
