### ISSUE TITLE
complex_key_range_hashed

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#26037]
range_hashed dictionary supports only UInt64 as a key right now.
I need more complex key  i.e (banner_id UInt64, event_state String)

**Comment by alexey-milovidov** [comment]
Ok.

Workaround: hash both keys into single UInt64 key if the number of keys is small (e.g millions) and you can tolerate 1 / 2^64 potential collision probability for every key.

**Comment by vpanfilov** [comment]
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/22029
