### ISSUE TITLE
Mixed versions in a cluster: Backwards compatibility broken when using aggregate functions w/ aliases over distributed tablesBroken backwards compatibility when using CTEs, nested queries and aggregations

### ISSUE THREAD

**Issue by nvartolomei** [ClickHouse/ClickHouse#26030]
This used to work fine but is failing on recent releases (21.7+ and latest master commit). When the following query is executed from 21.7 build it fails with: `Code: 184. DB::Exception: Received from 172.16.1.2:9000. DB::Exception: Received from node2:9000. DB::Exception: Aggregate function count() is found inside another aggregate function in query.`

Test case #26031

```sql
WITH
    quantile(0.05)(cnt) as p05,
    quantile(0.95)(cnt) as p95,
    p95 - p05 as inter_percentile_range
SELECT 
    sum(cnt) as total_requests,
    count() as data_points,
    inter_percentile_range
FROM (
    SELECT
        count() as cnt
    FROM remote('node{1,2}', numbers(10))
    GROUP BY number
)
```

Worked perfectly before. It seems that CTEs are pushed too deep now, is this expected and the query is actually incorrect?

explain syntax on latest master

```sql
WITH
    quantile(0.05)(cnt) AS p05,
    quantile(0.95)(cnt) AS p95,
    p95 - p05 AS inter_percentile_range
SELECT
    sum(cnt) AS total_requests,
    count() AS data_points,
    inter_percentile_range
FROM
(
    WITH
        (quantile(0.95)(count() AS cnt) AS p95) - (quantile(0.05)(cnt) AS p05) AS inter_percentile_range,
        p05,
        p95
    SELECT cnt
    FROM ...
    GROUP BY number
)
```

**Comment by alexey-milovidov** [comment]
See the `enable_global_with_statement` setting.

**Comment by alexey-milovidov** [comment]
See the comment: https://github.com/ClickHouse/ClickHouse/pull/26031#issuecomment-880402901
