### ISSUE TITLE
Memory leak when upgrading ClickHouse from 21.4.5.46 -> 21.6.6.51

### ISSUE THREAD

**Issue by reflection** [ClickHouse/ClickHouse#26042]
** Describe the bug**
ClickHouse nodes consistently restart with OOMKilled error after upgrade.  Reverting fixed this.

**Does it reproduce on recent release?**
Yes

**How to reproduce**

* Which ClickHouse server version to use - 21.6.6.51
* Queries to run that lead to unexpected result
* Only thing running were standard summarization queries (summarizing raw -> summary tables).  Didn't see any long-running queries in monitoring/logs.

**Expected behavior**
No memory leak

**Error message and/or stacktrace**
Attached logs from 3 nodes before OOMKilled
[ch-2.log.gz](https://github.com/ClickHouse/ClickHouse/files/6773254/ch-2.log.gz)
[ch-3.log.gz](https://github.com/ClickHouse/ClickHouse/files/6773255/ch-3.log.gz)
[ch-4.log.gz](https://github.com/ClickHouse/ClickHouse/files/6773256/ch-4.log.gz)

**Additional context**
Perhaps the memory leak is related to S3 tiered storage, as we use this on 3 of our raw tables with the following TTLs:
TTL
toStartOfDay(<datetime field>) + INTERVAL 91 DAY to VOLUME 's3',
toStartOfDay(<datetime field>) + INTERVAL 5 YEAR DELETE

**Comment by alexey-milovidov** [comment]
Yes, it is possible that the excessive memory usage is related to S3 tiered storage, that is currently in development and is not ready for production.

**Comment by alexey-milovidov** [comment]
Run the following query to check from where the memory is allocated:

```
SELECT
    count(),
    sum(size) AS bytes,
    arrayStringConcat(arrayMap(x -> concat(demangle(addressToSymbol(x)), '\n    ', addressToLine(x)), trace), '\n') AS sym
FROM system.trace_log
WHERE event_date >= today() - 5 AND trace_type = 'Memory'
GROUP BY trace
ORDER BY bytes DESC
LIMIT 10
```

**Comment by kitaisreal** [comment]
@nikitamikhaylov can you take a look at it ?

**Comment by Jokser** [comment]
@reflection 
I see the following line in your logs:
`2021.07.06 22:27:31.457135 [ 107 ] {} <Debug> WriteBufferFromS3: Writing part. Bucket: cuda-datalake-waf-archive, Key: ch/mhpuybehncrrginjuguicdfxnplasjua, Upload_id: x6WYfXqPTyya1NmNv6n4nlWJwJgHIQF8OWI.3mOdig_odDl3hqvsIDvM80aw4UP_bBuDQ0xk3Ieq3CKfxCKansndulFggqvOOcQXVEQD67Nm9VyBlImKCug8NcLFTGQ_, Size: 537919488
`

It means that each opened WriteBufferFromS3 consumes 512Mb memory.
As workaround you can decrease setting `s3_min_upload_part_size` to `64Mb` (default is `512Mb`).
This setting may be set in s3 disk configuration if you use 21.6+ versions.
If memory leak appears even after this change it should be investigated deeper.

**Comment by alexey-milovidov** [comment]
@Jokser it should work with default settings.
Also, OOM should not occur regardless to the settings.

@reflection I suggest not using the "S3 virtual filesystem" feature while it is under development.

**Comment by SaltTan** [comment]
I noticed increased memory usage in 21.6 as well, and I don't use S3.
I didn't get any OOMs though, just a few of 'Memory limit (total) exceeded'.
It seems to have gotten back to normal in 21.7 (the other nodes of the cluster run 21.5):
![image](https://user-images.githubusercontent.com/20357526/126371360-2d09f586-d14b-4782-a24e-3af778d6f79f.png)

**Comment by alexey-milovidov** [comment]
The issue with excessive size of the default upload buffer for s3 has been fixed.
