### ISSUE TITLE
Add memory tracker with memory limit to clickhouse-client.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#26043]
Prevent excessive memory usage on client side.
Should be controlled by `max_memory_usage` in client's config file.

By default it should not be sent to the server (when the setting is unchanged).

But if the user specified the setting explicitly, either in client's config file, in command line or with SET query, it should affect both client and server side limits.

**Use case**
#26033

**Comment by FArthur-cmd** [comment]
Solved in #27191.
