### ISSUE TITLE
recreate user with xml  cause EXC_BAD_ACCESS 

### ISSUE THREAD

**Issue by MaxWk** [ClickHouse/ClickHouse#26073]
You have to provide the following information whenever possible.

**Describe the bug**

recreate user with xml ,sometimes server will throw exception with EXC_BAD_ACCESS

**How to reproduce**
1.start server
2. create user by xml
```sh
cat > $USER_CONFIG_PATH/test.xml << EOF
<?xml version="1.0"?>
<yandex>
    <users>
        <test>
            <password></password>
            <networks incl="networks" replace="replace">
                <ip>::1</ip>
                <ip>127.0.0.1</ip>
            </networks>
            <profile>readonly</profile>
            <quota>default</quota>
        </test>
    </users>
</yandex>
EOF
```
3.make sure user success loaded
`clickhouse-client --query "show users"`

4. delete the xml
`rm $USER_CONFIG_PATH/test.xml`

5. repeat 2

6. connect with user
`clickhouse-client --user test --query "select 1"`

if not exception ,repeat 4,5,6

* Which ClickHouse server version to use
master branch

**Comment by MaxWk** [comment]
it look like AccessControlManager cache the ContextAccess in memory ,when user recreate quickly,it will read some old data。

**Comment by vitlibar** [comment]
ClickHouse reads users xml configuration files at start, keeps their contents in memory, and after that each two seconds it checks the modification time of those configuration files and rereads those files which have been changed.

**Comment by MaxWk** [comment]
@vitlibar  I think the design of caching is okay, but the reason I posted this issue is because the  has crashed. Is it possible to prevent it here?

**Comment by vitlibar** [comment]
> @vitlibar I think the design of caching is okay, but the reason I posted this issue is because the has crashed. Is it possible to prevent it here?
Yes, now I see, I'll try to fix it soon.

**Comment by vitlibar** [comment]
The bug has been fixed.
