### ISSUE TITLE
When will 21.6 release it's first LTS version？[projection feature related]

### ISSUE THREAD

**Issue by mo-avatar** [ClickHouse/ClickHouse#26070]
Projection has been merged as an experimental feature in 21.6, and 21.6 has just released an stable version "v21.6.6.51-stable", When will 21.6 release it's first LTS version?
Best Regards!

**Comment by den-crane** [comment]
21.6 will not be LTS. 
LTS will be 21.8 or 21.9.
The experimental mark will be removed from Projections someday in the future, nobody know when.

**Comment by mo-avatar** [comment]
> 21.6 will not be LTS.
> LTS will be 21.8 or 21.9.
> The experimental mark will be removed from Projections someday in the future, nobody know when.

Thanks!  If 21.8 or 21.9 will be LTS， when can we expect the LTS version be released(do not need to be guaranteed)?  Say, September or October?
Cause we want to use the feature some how, but we can't introduce an non-LTS version due to certain rules.

**Comment by alexey-milovidov** [comment]
21.8 will be released in August.

**Comment by mo-avatar** [comment]
> 21.8 will be released in August.
Roger that, thanks!
