### ISSUE TITLE
Distributed Join() tables?

### ISSUE THREAD

**Issue by Alekky09** [ClickHouse/ClickHouse#26098]
Hello,
I have created a table with engine Join() on my cluster of nodes, however I can't access the data from all of the nodes, just the one from which I did INSERT. Is there a Distributed version of this table?

It seems like it would fit my needs as I do large JOINs frequently, and I'd avoid the speed slowdown with this Join() table engine.

**Comment by den-crane** [comment]
You can use this Join table locally where you did the insert.

**Comment by Alekky09** [comment]
> You can use this Join table locally where you did the insert.

But I can't use it globally?

**Comment by gj-zhang** [comment]
> > You can use this Join table locally where you did the insert.
> 
> But I can't use it globally?

hi, do you resolve?

**Comment by alexey-milovidov** [comment]
There are no distributed Join tables.

But you can use Distributed table on top of Join tables, so when you insert into the Distributed table, the data will be inserted into Join table on every shard.

Then you use these Join tables locally.
