### ISSUE TITLE
sequenceMatch fails often even for trivial amounts of data (hardcoded limit)

### ISSUE THREAD

**Issue by andrea-s** [ClickHouse/ClickHouse#26095]
```
root@18575791bbaa:/# clickhouse-client -m
ClickHouse client version 21.6.6.51 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 21.6.6 revision 54448.

18575791bbaa :) SELECT sequenceMatch('(?1)(?t>1)(?2)')(timestamp, number <= 1000, number > 1000) AS seq
:-] FROM
:-] (
:-]     SELECT
:-]         number,
:-]         toDateTime('2021-01-01 00:00:00') + number AS timestamp
:-]     FROM system.numbers
:-]     LIMIT 1000
:-] );

SELECT sequenceMatch('(?1)(?t>1)(?2)')(timestamp, number <= 1000, number > 1000) AS seq
FROM
(
    SELECT
        number,
        toDateTime('2021-01-01 00:00:00') + number AS timestamp
    FROM system.numbers
    LIMIT 1000
)

Query id: 4a8058c7-24e8-409d-8cdf-efa05a45e430


0 rows in set. Elapsed: 0.007 sec.

Received exception from server (version 21.6.6):
Code: 160. DB::Exception: Received from localhost:9000. DB::Exception: Pattern application proves too difficult, exceeding max iterations (1000000): While executing ConvertingAggregatedToChunksTransform.
```

The limit seems to be hardcoded (https://github.com/ClickHouse/ClickHouse/blob/7a56ab8b1dc833d40e2140a35b95c65f383e4132/src/AggregateFunctions/AggregateFunctionSequenceMatch.h#L138), is there a way that we could expose this in settings at least? Unfortunately situations like the above happen quite a bit with "real life" datasets and it makes it hard to use sequenceMatch in production.

The above query could be rewritten like this of course:

```
SELECT coalesce(maxIfOrNull(timestamp, number > 1000) - minIfOrNull(timestamp, number <= 1000), 0) > 1 AS seq
FROM
(
    SELECT
        number,
        toDateTime('2021-01-01 00:00:00') + number AS timestamp
    FROM system.numbers
    LIMIT 1000
)
```

but it's not always practical.

**Comment by filimonov** [comment]
Without time condition different algorithm is used.

**Comment by filimonov** [comment]
https://github.com/ClickHouse/ClickHouse/pull/4004

**Comment by andrea-s** [comment]
Thank you for the pointer @filimonov.

Digging a bit more into it, it looks like even for sequenceMatch, too many paths are checked/kept in memory - so customer journeys that involve large matches in the first stage and few matches in the second stage have a probability to fail. E.g.:

```
-- errors out
SELECT sequenceMatch('(?1)(?t<=1000)(?2)')(timestamp, number <= 1000, number > 1000) AS seq
FROM
(
    SELECT
        number,
        toDateTime('2021-01-01 00:00:00') + number AS timestamp
    FROM system.numbers
    LIMIT 1000
)

-- works
SELECT sequenceMatch('(?1)(?t<=1000)(?2)')(timestamp, number <= 10, number > 1000) AS seq
FROM
(
    SELECT
        number,
        toDateTime('2021-01-01 00:00:00') + number AS timestamp
    FROM system.numbers
    LIMIT 1000
)
```

Am I right in saying that the sequenceMatch algorithm could work in a greedier way? Like in the example above, there would be no need to keep track of 1000 initial matches for the first query, but just to keep a reference to the last one. What do you think? I would be happy to tackle this in the source code but I would like to understand if I'm missing something obvious first...

**Comment by UnamedRus** [comment]
> Am I right in saying that the sequenceMatch algorithm could work in a greedier way? Like in the example above, there would be no need to keep track of 1000 initial matches for the first query, but just to keep a reference to the last one. What do you think? I would be happy to tackle this in the source code but I would like to understand if I'm missing something obvious first...

It's needed for AggregatingMergeTree tables and -State -Merge combinators.
You need to have full state in case of new data appear.

**Comment by filimonov** [comment]
> Thank you for the pointer @filimonov.
> 
> Digging a bit more into it, it looks like even for sequenceMatch, too many paths are checked/kept in memory - so customer journeys that involve large matches in the first stage and few matches in the second stage have a probability to fail. E.g.:
> 
> ```
> -- errors out
> SELECT sequenceMatch('(?1)(?t<=1000)(?2)')(timestamp, number <= 1000, number > 1000) AS seq
> FROM
> (
>     SELECT
>         number,
>         toDateTime('2021-01-01 00:00:00') + number AS timestamp
>     FROM system.numbers
>     LIMIT 1000
> )
> 
> -- works
> SELECT sequenceMatch('(?1)(?t<=1000)(?2)')(timestamp, number <= 10, number > 1000) AS seq
> FROM
> (
>     SELECT
>         number,
>         toDateTime('2021-01-01 00:00:00') + number AS timestamp
>     FROM system.numbers
>     LIMIT 1000
> )
> ```
> 
> Am I right in saying that the sequenceMatch algorithm could work in a greedier way? Like in the example above, there would be no need to keep track of 1000 initial matches for the first query, but just to keep a reference to the last one. What do you think? I would be happy to tackle this in the source code but I would like to understand if I'm missing something obvious first...

See https://github.com/ClickHouse/ClickHouse/pull/4004#issuecomment-454349525

P. S. Maybe windowFunnel will work for you? Or combining sequenceMatch (w/o time condition) with window functions?

**Comment by andrea-s** [comment]
Thank you! For the moment we are just rewriting our queries so that only users which match all the sequence conditions are included in the analysis. This helps quite a bit as it excludes impossible paths from the funnel by itself.

Regardless, do you think there would be room in a future version to make the sequence_match_max_iterations parameter user-settable? I understand the reasoning for its existence, but in many cases it would be acceptable to have a "slower" computation performed as long as it completes (for instance in our case we are computing this asynchronously in the background and making it available to users after materialization, so it would be perfectly fine for it to be more intensive).
