### ISSUE TITLE
GLOBAL IN don't return results from all nodes

### ISSUE THREAD

**Issue by MaxSkarzhinets** [ClickHouse/ClickHouse#2610]
Why when I use "GLOBAL IN", I do not get results from all nodes?
Example 1:
```
SELECT *
FROM tbl
PREWHERE EntityID GLOBAL IN (        
 SELECT EntityID
 FROM tbl
 PREWHERE EntityID = 'value'
)
```
Example 2:
```
SELECT *
FROM tbl
preWHERE EntityID  = 'value'
```
Count of rows Example 1 less then Example 2.

ClickHouse is deployed on 2 nodes: 1, 2. Each nodes have table with some data and view with aggregated data from all nodes. I connected to node 1 and execute query to view and not see data from node 1. When I connected to node 2 and execute query to view and not see data from node 2.

Why it occurs?

**Comment by azat** [comment]
I cannot reproduce this using usptream/master (98c603eaae):

```sql
create table data (key Int) Engine=MergeTree() order by key
insert into data select * from numbers(10)
select * from remote('127.1', currentDatabase(), data) prewhere key global in (select key from data prewhere key = 2)
select * from cluster('test_cluster_two_shards', currentDatabase(), data) prewhere key global in (select key from data prewhere key = 2)
```

That said that maybe it has been fixed already (but you do not provide any version)

FWIW You can check using temporary tables instead (and they will use indexes unlike global in):

```sql
create temporary table payload as select key from data prewhere key = 2
select * from remote('127.1', currentDatabase(), data) prewhere key in payload
```

**Comment by alexey-milovidov** [comment]
I don't remember whether this specific issue was fixed, but there were multiple issues with subqueries and PREWHERE and the code was rewritten multiple times.

**Comment by alexey-milovidov** [comment]
@azat Maybe it's worth to commit this test?

**Comment by azat** [comment]
Ok (Actually I came to this issues while looking into this [issue](https://github.com/ClickHouse/ClickHouse/blob/master/tests/queries/bugs/01224_dist_on_dist_global_in.sql) with distributed and global in, so let's see if I can fix this and then I will add the test from this issue to then)
