### ISSUE TITLE
lagInFrame and leadInFrame does not return NULL for calculated target rows which are out of frame.

### ISSUE THREAD

**Issue by ryzuo** [ClickHouse/ClickHouse#26115]
**Describe the unexpected behaviour**
When we use lagInFrame/leadInFrame window function, the returned value of rows that to be out of the frame is 0 or an empty string(depends on the type of the original column). However, like most other DBMSs' implementation, the returned value is null instead of 0 or empty string. Semantically, 0 or empty string can be computed while null cannot. Consequently, 0 or "" leads to incorrect behavior in subsequent procedures if this kind of returned values are accepted, 0 and empty strings really means something semantically in many cases.

I looked into the document, don't quite understand the term "**respect the frame**", not sure if it means 0 and empty string must be the default value it should use, when the target row to calculate is out of frame.

**How to reproduce**
* Which ClickHouse server version to use
Any version since window function lagInFrame/leadInFrame are introduced. 
For example, in the query below:
```
SELECT
    number,
    lagInFrame(number, 1) OVER w AS prevOne,
    lagInFrame(number, 2) OVER w AS prevTwo
FROM numbers(10)
WINDOW w AS (ORDER BY number ASC)

Query id: 1027831f-0764-4a08-bc6a-70fd2752a4dc

┌─number─┬─prevOne─┬─prevTwo─┐
│      0 │       0 │       0 │
│      1 │       0 │       0 │
│      2 │       1 │       0 │
│      3 │       2 │       1 │
│      4 │       3 │       2 │
│      5 │       4 │       3 │
│      6 │       5 │       4 │
│      7 │       6 │       5 │
│      8 │       7 │       6 │
│      9 │       8 │       7 │
└────────┴─────────┴─────────┘
```
In the row 1, I'm expecting prevOne and prevTwo to be NULL, and in row 2, expecting prevTwo to be NULL, but obviously they are 0 instead.

**Expected behavior**
For rows that the function runs on target row is out of frame, expected returned value must be null as query below:
```
SELECT
    number,
    lagInFrame(number, 1) OVER w AS prevOne,
    lagInFrame(number, 2) OVER w AS prevTwo
FROM numbers(10)
WINDOW w AS (ORDER BY number ASC)

Query id: ad65c077-90ef-4821-9376-c9567be203ff

┌─number─┬─prevOne─┬─prevTwo─┐
│      0 │    ᴺᵁᴸᴸ │    ᴺᵁᴸᴸ │
│      1 │       0 │    ᴺᵁᴸᴸ │
│      2 │       1 │       0 │
│      3 │       2 │       1 │
│      4 │       3 │       2 │
│      5 │       4 │       3 │
│      6 │       5 │       4 │
│      7 │       6 │       5 │
│      8 │       7 │       6 │
│      9 │       8 │       7 │
└────────┴─────────┴─────────┘
```

A simple fix of this I can think of is making the return type of the function to be ColumnNullable():
```
DataTypePtr getReturnType() const override
    { return std::make_shared<DataTypeNullable>(argument_types[0]); }
```

**Comment by kitaisreal** [comment]
@akuzm can you take a look at it ?

**Comment by akuzm** [comment]
```
:) SELECT　    number,　    lagInFrame(toNullable(number), 1) OVER w AS prevOne,　    lagInFrame(toNullable(number), 2) OVER w AS prevTwo　FROM numbers(10)　WINDOW w AS (ORDER BY number ASC)

[akuzm-nix] 2021.07.09 20:06:30.768610 [ 67080 ] {43a7a385-fb4b-4bf8-8f1d-291f1f0e2b13} <Fatal> : Logical error: 'Bad cast from type DB::ColumnNullable to DB::ColumnVector<unsigned long>'.
[akuzm-nix] 2021.07.09 20:06:30.770316 [ 67734 ] <Fatal> BaseDaemon: ########################################
[akuzm-nix] 2021.07.09 20:06:30.770795 [ 67734 ] <Fatal> BaseDaemon: (version 21.8.1.1, build id: 1B15653DE347AAD3) (from thread 67080) (query_id: 43a7a385-fb4b-4bf8-8f1d-291f1f0e2b13) Received signal Aborted (6)
[akuzm-nix] 2021.07.09 20:06:30.771189 [ 67734 ] <Fatal> BaseDaemon: 
[akuzm-nix] 2021.07.09 20:06:30.771722 [ 67734 ] <Fatal> BaseDaemon: Stack trace: 0x7f531068c18b 0x7f531066b859 0x7f53128a6ee5 0x7f53128a6ff9 0x7f530d6738cc 0x7f52f874282b 0x7f52f4c1b417 0x7f52f4bd1e4c 0x7f52f4bd26ff 0x7f52f4bd73cf 0x7f52f5345b5c 0x7f52f5345abf 0x7f52f5345a5d 0x7f52f5345a1d 0x7f52f53459f5 0x7f52f53459bd 0x7f5312959fa9 0x7f5312950895 0x7f52f53443b6 0x7f52f5344d99 0x7f52f5342c46 0x7f52f5341f36 0x7f52f536c9f9 0x7f52f536c926 0x7f52f536c89d 0x7f52f536c841 0x7f52f536c752 0x7f52f536c64c 0x7f52f536c55d 0x7f52f536c51d 0x7f52f536c4f5 0x7f52f536c4c0 0x7f5312959fa9 0x7f5312950895 0x7f53129502d4 0x7f5312956da4 0x7f5312956cfd 0x7f5312956c25 0x7f5312956542 0x7f5310a2b609 0x7f5310768293
[akuzm-nix] 2021.07.09 20:06:30.775794 [ 67734 ] <Fatal> BaseDaemon: 4. /build/glibc-eX1tMB/glibc-2.31/signal/../sysdeps/unix/sysv/linux/raise.c:51: __GI_raise @ 0x4618b in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.31.so
[akuzm-nix] 2021.07.09 20:06:30.783894 [ 67734 ] <Fatal> BaseDaemon: 5. /build/glibc-eX1tMB/glibc-2.31/stdlib/abort.c:81: abort @ 0x25859 in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.31.so
[akuzm-nix] 2021.07.09 20:06:31.168000 [ 67734 ] <Fatal> BaseDaemon: 6. /home/akuzm/ch1/ch/src/Common/Exception.cpp:53: DB::handle_error_code(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool, std::__1::vector<void*, std::__1::allocator<void*> > const&) @ 0x290ee5 in /home/akuzm/ch1/build-clang11/src/libclickhouse_common_iod.so
[akuzm-nix] 2021.07.09 20:06:31.484758 [ 67734 ] <Fatal> BaseDaemon: 7. /home/akuzm/ch1/ch/src/Common/Exception.cpp:60: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x290ff9 in /home/akuzm/ch1/build-clang11/src/libclickhouse_common_iod.so
[akuzm-nix] 2021.07.09 20:06:31.767326 [ 67734 ] <Fatal> BaseDaemon: 8. /home/akuzm/ch1/ch/src/Common/assert_cast.h:47: DB::ColumnVector<unsigned long> const& assert_cast<DB::ColumnVector<unsigned long> const&, DB::IColumn const&>(DB::IColumn const&) @ 0x449f8cc in /home/akuzm/ch1/build-clang11/src/AggregateFunctions/libclickhouse_aggregate_functionsd.so
[akuzm-nix] 2021.07.09 20:06:32.086567 [ 67734 ] <Fatal> BaseDaemon: 9. /home/akuzm/ch1/ch/src/Columns/ColumnVector.h:137: DB::ColumnVector<unsigned long>::insertFrom(DB::IColumn const&, unsigned long) @ 0x34682b in /home/akuzm/ch1/build-clang11/src/libclickhouse_columnsd.so
[akuzm-nix] 2021.07.09 20:06:32.506433 [ 67734 ] <Fatal> BaseDaemon: 10. /home/akuzm/ch1/ch/src/Processors/Transforms/WindowTransform.cpp:1553: DB::WindowFunctionLagLeadInFrame<false>::windowInsertResultInto(DB::WindowTransform const*, unsigned long) @ 0x2dc417 in /home/akuzm/ch1/build-clang11/src/libclickhouse_processors_transformsd.so
[akuzm-nix] 2021.07.09 20:06:32.812601 [ 67734 ] <Fatal> BaseDaemon: 11. /home/akuzm/ch1/ch/src/Processors/Transforms/WindowTransform.cpp:955: DB::WindowTransform::writeOutCurrentRow() @ 0x292e4c in /home/akuzm/ch1/build-clang11/src/libclickhouse_processors_transformsd.so
[akuzm-nix] 2021.07.09 20:06:33.121521 [ 67734 ] <Fatal> BaseDaemon: 12. /home/akuzm/ch1/ch/src/Processors/Transforms/WindowTransform.cpp:1093: DB::WindowTransform::appendChunk(DB::Chunk&) @ 0x2936ff in /home/akuzm/ch1/build-clang11/src/libclickhouse_processors_transformsd.so
[akuzm-nix] 2021.07.09 20:06:33.432126 [ 67734 ] <Fatal> BaseDaemon: 13. /home/akuzm/ch1/ch/src/Processors/Transforms/WindowTransform.cpp:1306: DB::WindowTransform::work() @ 0x2983cf in /home/akuzm/ch1/build-clang11/src/libclickhouse_processors_transformsd.so
```

Nice.

This one is also broken:
```
:) SELECT　    number,　    lagInFrame(number, 1, null) OVER w AS prevOne,　    lagInFrame(number, 2, null) OVER w AS prevTwo　FROM numbers(10)　WINDOW w AS (ORDER BY number ASC)

┌─number─┬─prevOne─┬─prevTwo─┐
│      0 │ ᴺᵁᴸᴸ    │ ᴺᵁᴸᴸ    │
│      1 │ ᴺᵁᴸᴸ    │ ᴺᵁᴸᴸ    │
│      2 │ ᴺᵁᴸᴸ    │ ᴺᵁᴸᴸ    │
│      3 │ ᴺᵁᴸᴸ    │ ᴺᵁᴸᴸ    │
│      4 │ ᴺᵁᴸᴸ    │ ᴺᵁᴸᴸ    │
│      5 │ ᴺᵁᴸᴸ    │ ᴺᵁᴸᴸ    │
│      6 │ ᴺᵁᴸᴸ    │ ᴺᵁᴸᴸ    │
│      7 │ ᴺᵁᴸᴸ    │ ᴺᵁᴸᴸ    │
│      8 │ ᴺᵁᴸᴸ    │ ᴺᵁᴸᴸ    │
│      9 │ ᴺᵁᴸᴸ    │ ᴺᵁᴸᴸ    │
└────────┴─────────┴─────────┘
```

**Comment by ryzuo** [comment]
Right, forgot to mention this does not work either, and I also tried table with the type of column is Nullable(Float32), and run the functions on the column, the value overflows... I've got no time to look into the cause yet.
The change of getReturnType() I mentioned above can fix the "no-null returned value" problem, but it clearly does not solve the rest of the problem

> ```
> :) SELECT　    number,　    lagInFrame(toNullable(number), 1) OVER w AS prevOne,　    lagInFrame(toNullable(number), 2) OVER w AS prevTwo　FROM numbers(10)　WINDOW w AS (ORDER BY number ASC)
> 
> [akuzm-nix] 2021.07.09 20:06:30.768610 [ 67080 ] {43a7a385-fb4b-4bf8-8f1d-291f1f0e2b13} <Fatal> : Logical error: 'Bad cast from type DB::ColumnNullable to DB::ColumnVector<unsigned long>'.
> [akuzm-nix] 2021.07.09 20:06:30.770316 [ 67734 ] <Fatal> BaseDaemon: ########################################
> [akuzm-nix] 2021.07.09 20:06:30.770795 [ 67734 ] <Fatal> BaseDaemon: (version 21.8.1.1, build id: 1B15653DE347AAD3) (from thread 67080) (query_id: 43a7a385-fb4b-4bf8-8f1d-291f1f0e2b13) Received signal Aborted (6)
> [akuzm-nix] 2021.07.09 20:06:30.771189 [ 67734 ] <Fatal> BaseDaemon: 
> [akuzm-nix] 2021.07.09 20:06:30.771722 [ 67734 ] <Fatal> BaseDaemon: Stack trace: 0x7f531068c18b 0x7f531066b859 0x7f53128a6ee5 0x7f53128a6ff9 0x7f530d6738cc 0x7f52f874282b 0x7f52f4c1b417 0x7f52f4bd1e4c 0x7f52f4bd26ff 0x7f52f4bd73cf 0x7f52f5345b5c 0x7f52f5345abf 0x7f52f5345a5d 0x7f52f5345a1d 0x7f52f53459f5 0x7f52f53459bd 0x7f5312959fa9 0x7f5312950895 0x7f52f53443b6 0x7f52f5344d99 0x7f52f5342c46 0x7f52f5341f36 0x7f52f536c9f9 0x7f52f536c926 0x7f52f536c89d 0x7f52f536c841 0x7f52f536c752 0x7f52f536c64c 0x7f52f536c55d 0x7f52f536c51d 0x7f52f536c4f5 0x7f52f536c4c0 0x7f5312959fa9 0x7f5312950895 0x7f53129502d4 0x7f5312956da4 0x7f5312956cfd 0x7f5312956c25 0x7f5312956542 0x7f5310a2b609 0x7f5310768293
> [akuzm-nix] 2021.07.09 20:06:30.775794 [ 67734 ] <Fatal> BaseDaemon: 4. /build/glibc-eX1tMB/glibc-2.31/signal/../sysdeps/unix/sysv/linux/raise.c:51: __GI_raise @ 0x4618b in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.31.so
> [akuzm-nix] 2021.07.09 20:06:30.783894 [ 67734 ] <Fatal> BaseDaemon: 5. /build/glibc-eX1tMB/glibc-2.31/stdlib/abort.c:81: abort @ 0x25859 in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.31.so
> [akuzm-nix] 2021.07.09 20:06:31.168000 [ 67734 ] <Fatal> BaseDaemon: 6. /home/akuzm/ch1/ch/src/Common/Exception.cpp:53: DB::handle_error_code(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool, std::__1::vector<void*, std::__1::allocator<void*> > const&) @ 0x290ee5 in /home/akuzm/ch1/build-clang11/src/libclickhouse_common_iod.so
> [akuzm-nix] 2021.07.09 20:06:31.484758 [ 67734 ] <Fatal> BaseDaemon: 7. /home/akuzm/ch1/ch/src/Common/Exception.cpp:60: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x290ff9 in /home/akuzm/ch1/build-clang11/src/libclickhouse_common_iod.so
> [akuzm-nix] 2021.07.09 20:06:31.767326 [ 67734 ] <Fatal> BaseDaemon: 8. /home/akuzm/ch1/ch/src/Common/assert_cast.h:47: DB::ColumnVector<unsigned long> const& assert_cast<DB::ColumnVector<unsigned long> const&, DB::IColumn const&>(DB::IColumn const&) @ 0x449f8cc in /home/akuzm/ch1/build-clang11/src/AggregateFunctions/libclickhouse_aggregate_functionsd.so
> [akuzm-nix] 2021.07.09 20:06:32.086567 [ 67734 ] <Fatal> BaseDaemon: 9. /home/akuzm/ch1/ch/src/Columns/ColumnVector.h:137: DB::ColumnVector<unsigned long>::insertFrom(DB::IColumn const&, unsigned long) @ 0x34682b in /home/akuzm/ch1/build-clang11/src/libclickhouse_columnsd.so
> [akuzm-nix] 2021.07.09 20:06:32.506433 [ 67734 ] <Fatal> BaseDaemon: 10. /home/akuzm/ch1/ch/src/Processors/Transforms/WindowTransform.cpp:1553: DB::WindowFunctionLagLeadInFrame<false>::windowInsertResultInto(DB::WindowTransform const*, unsigned long) @ 0x2dc417 in /home/akuzm/ch1/build-clang11/src/libclickhouse_processors_transformsd.so
> [akuzm-nix] 2021.07.09 20:06:32.812601 [ 67734 ] <Fatal> BaseDaemon: 11. /home/akuzm/ch1/ch/src/Processors/Transforms/WindowTransform.cpp:955: DB::WindowTransform::writeOutCurrentRow() @ 0x292e4c in /home/akuzm/ch1/build-clang11/src/libclickhouse_processors_transformsd.so
> [akuzm-nix] 2021.07.09 20:06:33.121521 [ 67734 ] <Fatal> BaseDaemon: 12. /home/akuzm/ch1/ch/src/Processors/Transforms/WindowTransform.cpp:1093: DB::WindowTransform::appendChunk(DB::Chunk&) @ 0x2936ff in /home/akuzm/ch1/build-clang11/src/libclickhouse_processors_transformsd.so
> [akuzm-nix] 2021.07.09 20:06:33.432126 [ 67734 ] <Fatal> BaseDaemon: 13. /home/akuzm/ch1/ch/src/Processors/Transforms/WindowTransform.cpp:1306: DB::WindowTransform::work() @ 0x2983cf in /home/akuzm/ch1/build-clang11/src/libclickhouse_processors_transformsd.so
> ```
> 
> Nice.
> 
> This one is also broken:
> 
> ```
> :) SELECT　    number,　    lagInFrame(number, 1, null) OVER w AS prevOne,　    lagInFrame(number, 2, null) OVER w AS prevTwo　FROM numbers(10)　WINDOW w AS (ORDER BY number ASC)
> 
> ┌─number─┬─prevOne─┬─prevTwo─┐
> │      0 │ ᴺᵁᴸᴸ    │ ᴺᵁᴸᴸ    │
> │      1 │ ᴺᵁᴸᴸ    │ ᴺᵁᴸᴸ    │
> │      2 │ ᴺᵁᴸᴸ    │ ᴺᵁᴸᴸ    │
> │      3 │ ᴺᵁᴸᴸ    │ ᴺᵁᴸᴸ    │
> │      4 │ ᴺᵁᴸᴸ    │ ᴺᵁᴸᴸ    │
> │      5 │ ᴺᵁᴸᴸ    │ ᴺᵁᴸᴸ    │
> │      6 │ ᴺᵁᴸᴸ    │ ᴺᵁᴸᴸ    │
> │      7 │ ᴺᵁᴸᴸ    │ ᴺᵁᴸᴸ    │
> │      8 │ ᴺᵁᴸᴸ    │ ᴺᵁᴸᴸ    │
> │      9 │ ᴺᵁᴸᴸ    │ ᴺᵁᴸᴸ    │
> └────────┴─────────┴─────────┘
> ```
