### ISSUE TITLE
Do you have any documentation on how to use Clickhouse keeper

### ISSUE THREAD

**Issue by zhbdesign** [ClickHouse/ClickHouse#26117]
Do you have any documentation on how to use Clickhouse keeper

**Comment by alexey-milovidov** [comment]
This documentation is going to be written.

**Comment by alesapin** [comment]
You can look at draft here: https://github.com/ClickHouse/ClickHouse/pull/26150

**Comment by alexey-milovidov** [comment]
Merged.

**Comment by alexey-milovidov** [comment]
https://clickhouse.tech/docs/en/operations/clickhouse-keeper/
