### ISSUE TITLE
The distributed table IN specifies that all table data is faster than some of its data

### ISSUE THREAD

**Issue by sileiH** [ClickHouse/ClickHouse#26121]
CREATE TABLE test.test_local
(
    `fid` String,
    `imei` String,
    `app` String
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{layer}-{shard}/test_local', '{replica}')
ORDER BY app
SETTINGS storage_policy = 'hdd_in_order', index_granularity = 8192 

 CREATE TABLE test.test
(
    `fid` String,
    `imei` String,
    `app` String
)
ENGINE = Distributed('report_shards_replicas', 'test', 'test_local', rand())

 CREATE TABLE test.mysql_test
(
    `task_id` String,
    `import_day` Date,
    `data` String
)
ENGINE = MySQL('xxxx', 'xxx', 'xxx', 'xxx', 'xxx')

-- query_1

SELECT count(1)
FROM test.test
WHERE imei IN 
(
    SELECT data
    FROM test.mysql_test
    WHERE task_id = '72c4fa9efadb4230ba92831631796037'
)
GROUP BY app
<img width="813" alt="WeChatcbd23e466845058830990e9ad9558620" src="https://user-images.githubusercontent.com/34700762/125058816-36fee200-e0dd-11eb-9123-25aca21e79ef.png">

-- query_2

SELECT count(1)
FROM test.test
WHERE imei IN 
(
    SELECT data
    FROM test.mysql_test
)
GROUP BY app
<img width="795" alt="WeChat13e73ac0108a3aafce327ff447457f6e" src="https://user-images.githubusercontent.com/34700762/125058797-32d2c480-e0dd-11eb-8f6b-ea4614f3f8d0.png">

The distributed table is about 7 billion, The mysql external table value is 2000W, and the task_id value is 200W, Query2 is dozens of times faster than Query1,What is the cause of this

**Comment by den-crane** [comment]
Check performance of 

```
SELECT count()
   (select * FROM test.test)
WHERE imei IN
           (SELECT data FROM test.mysql_test WHERE task_id = '72c4fa9efadb4230ba92831631796037')
GROUP BY app
```

**Comment by sileiH** [comment]
The performance of this SQL is still very poor。
![image](https://user-images.githubusercontent.com/34700762/125718276-34506f81-51af-42f5-97a8-a77eded1af1f.png)

But when I removed the WHERE condition from the IN subquery, the performance improved
<img width="869" alt="WeChatc814860947bc987facf6cca8f50721c4" src="https://user-images.githubusercontent.com/34700762/125718828-4ce578cb-ffa9-4992-8749-329e2fdec90d.png">

**Comment by alexey-milovidov** [comment]
@sileiH Filtering by WHERE requires reading one additional column, and when the column is heavy, it will slow-down the query.
