### ISSUE TITLE
Unknown function dateName

### ISSUE THREAD

**Issue by fedoranvar** [ClickHouse/ClickHouse#26124]
You have to provide the following information whenever possible.

**Describe the bug**

receive 'Unknown function' error by running query with dateName function

**Does it reproduce on recent release?**

On clickhouse server version of 21.6.5 (latest)

**How to reproduce**

* Which ClickHouse server version to use
    21.6.5
* Which interface to use, if matters
    grafana or official docker container-client
* Queries to run that lead to unexpected result
    select dateName('month', '2020-01-01')

**Expected behavior**

showing 'January'

**Additional context**

![image](https://user-images.githubusercontent.com/52028706/125079107-ab855100-e0dc-11eb-9178-e15c8fcf61dc.png)

**Comment by den-crane** [comment]
It will be available from 21.7
