### ISSUE TITLE
'auto' not allowed in function prototype

### ISSUE THREAD

**Issue by zhengshengjun** [ClickHouse/ClickHouse#26146]
Hi, I just checked out from master branch and met the following build error. Should ClickHouse avoid using 'auto' in function prototype ?

**Operating system**
macOS Catalina 10.15.7 

**Cmake version**
3.19.2

**Ninja version**

**Compiler name and version**
Apple clang version 12.0.0 (clang-1200.0.32.29)

**Full cmake and/or ninja output**

/Users/workspace/clion/opensource/ClickHouse/src/Common/Config/configReadClient.cpp:14:25: error: 'auto' not allowed in function prototype
bool safeFsExists(const auto & path)
                        ^~~~
1 error generated.

**Comment by alexey-milovidov** [comment]
The code is valid and conforms C++20 standard.
The issue is with *Apple* clang. 
clang should be used instead. You can install clang with brew.
