### ISSUE TITLE
hasAll() filter condition not relying on bloom filter; re-writing as has() AND has()... does use bloom_filter 

### ISSUE THREAD

**Issue by isheu** [ClickHouse/ClickHouse#26151]
**Describe the situation**
hasAll() filter condition not relying on bloom filter, but re-writing as series of has() AND has()... (or series of indexOf conditions) does use bloom filter 

**How to reproduce**
* ClickHouse server version: 21.2.7.2

Test Table: 
- 33M records, 10 columns
- MergeTree() engine, has a sort order specified
- Has a field STRING_ARRAY that is a Array(String) column. It has a bloom filter data-skipping index (`TYPE bloom_filter(0.01) GRANULARITY 1`)

The following query takes 1.5 seconds: 
```
SELECT * FROM db_name.table_name
WHERE hasAll(STRING_ARRAY, ['value_1', 'value_2', 'value_3']
```
Running `EXPLAIN indexes = 1`, only the primary key is picked up. The bloom filter isn't used. 

The following query takes 0.45 seconds: 
```
SELECT * FROM db_name.table_name
WHERE has(STRING_ARRAY, 'value_1') AND has(STRING_ARRAY, 'value_2') AND has(STRING_ARRAY, 'value_3')
```
Running `EXPLAIN indexes = 1`, the bloom filter is used. 

**Expected performance**
Expecting the hasAll() filter condition to also get performance improvement from the bloom filter on STRING_ARRAY.

**Comment by akuzm** [comment]
This feature would be nice to have.

**Comment by alexey-milovidov** [comment]
Related to #24900 (hasAny is already supported).
CC @Enmk

**Comment by BraulioVM** [comment]
Hi, may I get assigned to this issue? I would like to contribute the fix

**Comment by BraulioVM** [comment]
I'm making my way through the RPN calculations and the bloom filters, but if anyone needs this feature **right now**  I don't mind another person contributing it.
