### ISSUE TITLE
[Question] What's the difference between replicated_deduplication_window and insert_deduplicate

### ISSUE THREAD

**Issue by lamber-ken** [ClickHouse/ClickHouse#2620]
Hi, What's the difference between `replicated_deduplication_window` and `insert_deduplicate`
Thank you very match.

**Comment by wawanawna** [comment]
No answer @alexey-milovidov @ztlpn ?

**Comment by filimonov** [comment]
replicated_deduplication_window & replicated_deduplication_window_seconds are merge_tree settings, you can adjust them per table using SETTINGS statement, or globally - in <merge_tree> section of config.xml.

insert_deduplicate is session setting, so you can bypass that deduplication logic for one particular insert.
