### ISSUE TITLE
The function `clearOldTemporaryDirectories` is run every second.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#26212]
It is too much. It is very heavy function as it iterates over potentially large directories.
Even on my machine it leads to about 8% CPU usage in background which is non-tolerable.

**Comment by alexey-milovidov** [comment]
Decrease to at least once a few minutes.

**Comment by fastio** [comment]
@alexey-milovidov  The execution period of this function can be controlled by parameter with default value. I can fix it.

**Comment by alexey-milovidov** [comment]
@fastio Thank you! Let's do it.
It should not affect `clearOldParts` that will continue to run frequently.
