### ISSUE TITLE
Add `addressToLineWithInlines` function.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#26211]
**Use case**
Similar to `addressToLine` but outputs an array with inlined places in code.

**Comment by GinGin3203** [comment]
Hi! I'm a first-timer contributor. Could you assign the task to me?

**Comment by alexey-milovidov** [comment]
Ok.

Look at the implementation of `addressToLine` in `src/Functions/addressToLine.cpp`
Also look how inlined stack frames are found at `src/Common/StackTrace.cpp`, near `static void toStringEveryLineImpl`.

**Comment by alexey-milovidov** [comment]
@fuzzERot It should return an array with main stack frame and all the inlined functions if any.
So, if there are no inlined function, the array will have one element.

**Comment by alexey-milovidov** [comment]
Currently no one is working on this feature. I will be happy it you will help! :+1:
