### ISSUE TITLE
[MV] неполные данные

### ISSUE THREAD

**Issue by urykhy** [ClickHouse/ClickHouse#2621]
версия: 1.1.54385
ZK: 3.5.2

после обновления - появилось расхождение между таблицей и MV:
проверочный запрос:
```sql
SELECT date, h, shows1, shows2
FROM
  (SELECT date, toHour(timestamp) as h, sum(ev_type = 0) AS shows1
   FROM events_local
   WHERE date BETWEEN '2018-07-09' AND '2018-07-10'
   GROUP BY date, h) 
ANY LEFT JOIN
  (SELECT date, toHour(timestamp) as h, sumIf(count, event_type = 0) AS shows2
   FROM hour_banner_events_local
   WHERE date BETWEEN '2018-07-09' AND '2018-07-10'
   GROUP BY date, h)
USING date, h
WHERE shows1 != shows2
order by date, h asc
```
date |h|shows1|shows2
-------|--|------|------
10/07/18 | 8 | 19,603,645 | 19,481,276 |
* в основной таблице (events_local/ReplicatedMergeTree) - данные корректны
* в MV (hour_banner_events_local/ReplicatedSummingMergeTree) - отсутствует часть данных
* расхождения есть не каждый час
* программа заливающая данные периодически получает 500, после чего повторяет попытку загрузки данных.
* в CH есть ошибки вида _2018.07.10 08:22:35: ZooKeeper session has been expired.: while pushing to view hour_banner_events_local_.
* в графите сильно выросли ZooKeeperExceptions: ![image](https://user-images.githubusercontent.com/1411834/42498724-a25749b4-8435-11e8-96de-d863b06e5b6c.png)

**Comment by urykhy** [comment]
сделали стенд (к сожалению он использует внутренние компоненты, но думаю повторить не сложно) для выявления бага:

1. КХ (19.15.3.6) + ZK
2. 1 шард. реплицируемая таблица (куда заливаем данные) + реплицируемая MV.
3. запускаем заливку данных, заливатор должен понимать ошибку 500 и делать повторную попытку отправить данные.
4. в цикле останавливаем и запускаем контейнер ZK: 
```
for i in `seq 1 10`; do
     docker stop stand_zookeeper
     docker start stand_zookeeper
     sleep 20
done
```
5. запускаем проверку консистентности MV/таблицы. есть расхождение.

**Comment by den-crane** [comment]
@urykhy не атомарность таблицы и MV общеизвестны и документированы. Легко воспроизводится throwIf

```

create table testX ( A Int64) engine=MergeTree order by tuple();
create MATERIALIZED view testXA engine=MergeTree order by tuple() as select * from testX;
create MATERIALIZED view testXB engine=MergeTree order by tuple() as select throwIf(A=20000000) from testX;
create MATERIALIZED view testXC engine=MergeTree order by tuple() as select * from testX;
insert into testX select number from numbers(100000000) settings max_block_size=10000;
 DB::Exception: Value passed to 'throwIf' function is non zero: while pushing to view dw.testXB

select count() from testX
21000000

select count() from testXA
21000000

select count() from testXB
19950000

select count() from testXC
19950000
```

**Comment by urykhy** [comment]
@den-crane, в вашем случае пользователь получил ошибку ?
у меня заливатор получает "200 OK" и не может определить что операция не выполнилась.

**Comment by den-crane** [comment]
> @den-crane, в вашем случае пользователь получил ошибку ?
> у меня заливатор получает "200 OK" и не может определить что операция не выполнилась.

ОК. Это интересно. 
Непонятно `заливатор должен понимать ошибку 500 и делать повторную попытку отправить данные.`. 

Т.е. заливатор получает 500 и при повторе 200 и данные не согласуются
или заливатор получает 200 и данные не согласуются

**Comment by urykhy** [comment]
заливатор периодически получает 500 и повторяет заливку блока до получения "200 OK".

**Comment by den-crane** [comment]
Заливка в один поток? Может такое быть что между 500й и 200й влезает другой заливатор и заисывает больше 100 инсертов?

**Comment by urykhy** [comment]
> Заливка в один поток? 
в 4

> Может такое быть что между 500й и 200й влезает другой заливатор и записывает больше 100 инсертов?
нет.

> Где данные правильные в таблице или MV ?
а таблице. в MV данных меньше. 

более того, если сделать другой тест(назовём его B, в отличие от описанного выше - A)
* посмотреть по логам на ошибки ZK, 
* найти что заливалось во время ошибок
* залить эти данные в чистую таблицу/MV в БД B
то данные влитые в B.MV полностью сходятся с тем чего не хватает в A.MV после теста A.

**Comment by den-crane** [comment]
@alexey-milovidov 
Действительно дыра в дизайне.
Если блок есть в таблице, то из-за дедупликации insert в MV не случается.

```
CREATE TABLE test12345 (A Int64)
ENGINE = ReplicatedMergeTree ('/clickhouse/{cluster}/tables/test','{replica}')
ORDER BY tuple();

CREATE MATERIALIZED VIEW test12345mv Engine=ReplicatedMergeTree ('/clickhouse/{cluster}/tables/testmv','{replica}') order by tuple()
AS SELECT count(), randConstant() r FROM test12345;

insert into test12345 values(1),(2),(3);

insert into test12345 values(1),(2),(3);

select * from test12345mv;

┌─count()─┬─────────r─┐
│       3 │ 634339350 │
└─────────┴───────────┘
```

https://github.com/ClickHouse/ClickHouse/issues/5274

**Comment by urykhy** [comment]
по мотивам a0d06c5ee0a7f4fd37a0bea43fff973c16ad80b0 получилось сделать такой патч:

```diff
diff --git a/dbms/src/DataStreams/PushingToViewsBlockOutputStream.cpp b/dbms/src/DataStreams/PushingToViewsBlockOutputStream.cpp
index 195c5edcb0..52105202c2 100644
--- a/dbms/src/DataStreams/PushingToViewsBlockOutputStream.cpp
+++ b/dbms/src/DataStreams/PushingToViewsBlockOutputStream.cpp
@@ -25,6 +25,7 @@ PushingToViewsBlockOutputStream::PushingToViewsBlockOutputStream(
     /// If the "root" table deduplactes blocks, there are no need to make deduplication for children
     /// Moreover, deduplication for AggregatingMergeTree children could produce false positives due to low size of inserting blocks
     bool disable_deduplication_for_children = !no_destination && storage->supportsDeduplication();
+    disable_deduplication_for_children = false;
 
     if (!table.empty())
     {
@@ -76,8 +77,8 @@ void PushingToViewsBlockOutputStream::write(const Block & block)
         output->write(block);
 
     /// Don't process materialized views if this block is duplicate
-    if (replicated_output && replicated_output->lastBlockIsDuplicate())
-        return;
+    //if (replicated_output && replicated_output->lastBlockIsDuplicate())
+    //    return;
 
     // Insert data into materialized views only after successful insert into main table
     const Settings & settings = context.getSettingsRef();
{code}

в тестах на стенде стало хорошо, потерь нет.
но может быть так ломается что-то другое ? ;)

**Comment by den-crane** [comment]
https://t.me/c/1425947904/4246

> Denny Crane (I don't work at Yandex (never did)), [Jan 21, 2020 at 5:00:12 PM]:
> А что написано в CLICKHOUSE-3381 ? 
> Зачем оно (Don't deduplicate a block inserted from MV if the source block is Ok) ?
> Что пытались починить?

> Alexey Milovidov, [Jan 21, 2020 at 5:09:42 PM]:
> Когда при вставке в mv из-за агрегации, пачки становятся маленькими и начинают совпадать для разных входных данных.
 
> Denny Crane (I don't work at Yandex (never did)), [Jan 21, 2020 at 5:56:04 PM]:
> эммм. Что-то я не понимаю, во первых это не работает https://github.com/ClickHouse/ClickHouse/issues/5274
 > во вторых это сломало идемпотентность insert-в (ретраи) https://github.com/ClickHouse/ClickHouse/issues/2621#issuecomment-558668325
 > хотя возможно это не рабоает потому что у меня ENGINE = Null;  в https://github.com/ClickHouse/ClickHouse/issues/5274
 
> Alexey Milovidov, [Jan 21, 2020 at 6:00:34 PM]:
> Копирую текст из задачи:
> 
> Смысл задачи был в исправлении проблемы: избыточная дедупликация данных в materialized view из-за того, что данные более агрегированные, по сравнению с исходной таблицей, и могут совпадать, даже если в исходную таблицу вставлялись не дубликаты.
> 
> Если движок исходной таблицы Null, то получается, что вовсе нет никакой дедупликации.

> Denny Crane (I don't work at Yandex (never did)), [Jan 21, 2020 at 6:04:07 PM]:
> Ясно. ОК. Да действительно, если движек у таблицы replicated то все по другому.
> 
> Но получается, что если в Replicated таблицу вставка успешная, а в MV упала например too many parts
> insert возвращается с ошибкой, повторяем инсерт. В таблицу ничего не вставится из-за дедупликации, и MV тоже из-за фичи CLICKHOUSE-3381 ? Инсерт будет успешным.
> 
> И получится что в MV не хватает.

> Alexey Milovidov, [Jan 21, 2020 at 6:07:19 PM]:
> Тут не припоминаю. Возможно так и есть.

**Comment by urykhy** [comment]
посмотрел на другие причины расхождений (какие всё ещё есть после патча выше)
кроме ситуации "данные есть в основной таблице но их нет в MV" бывает и наоборот:

лог выглядит примерно так 
```
2020.01.23 14:21:56.665364 [ 19 ] <Debug> executeQuery: (from 172.19.0.5:52236, query_id: 8d1a617d-d242-45c5-9833-018032a476ae) INSERT INTO data.events_local /* file_id: 264 */
2020.01.23 14:21:57.390199 [ 19 ] <Debug> data.events_local (Replicated OutputStream): Wrote block with ID '202001_283832432587100632_12784886461397706606', 213125 rows
2020.01.23 14:21:57.558111 [ 19 ] <Trace> data.events_local (Data): Renaming temporary part tmp_insert_202001_272_272_0 to 202001_263_263_0.
2020.01.23 14:21:58.141548 [ 19 ] <Debug> data.events_local (Data): Undoing transaction. Removing parts: 202001_263_263_0.
2020.01.23 14:21:58.356074 [ 19 ] <Debug> data.events_local (Replicated OutputStream): Fail to commit block with ID '202001_283832432587100632_12784886461397706606', 213125 rows
2020.01.23 14:21:59.176709 [ 19 ] <Error> executeQuery: Code: 244, e.displayText() = DB::Exception: Unrecoverable network error while adding block 263 with ID '202001_283832432587100632_12784886461397706606': Session expired

.....

2020.01.23 14:22:59.703980 [ 19 ] <Debug> executeQuery: (from 172.19.0.5:52574, query_id: 7605b3d6-a5a7-48a4-b54a-dcb45b64617b) INSERT INTO data.events_local /* file_id: 264 */
2020.01.23 14:23:00.460886 [ 19 ] <Debug> data.events_local (Replicated OutputStream): Wrote block with ID '202001_283832432587100632_12784886461397706606', 213125 rows
2020.01.23 14:23:00.471811 [ 19 ] <Information> data.events_local (Replicated OutputStream): Block with ID 202001_283832432587100632_12784886461397706606 ignored since !block_number_lock 202001_273_273_0
2020.01.23 14:23:00.471855 [ 19 ] <Debug> data.events_local (Replicated OutputStream): Commited block with ID '202001_283832432587100632_12784886461397706606', 213125 rows
```
* добавлено немного логгирования о жизни блока
* выглядит что после `Undoing transaction` блок не вставляется.
* data.events_local - ReplicatedMergeTree таблица.
