### ISSUE TITLE
LDAP: use special account to perform search in the directory

### ISSUE THREAD

**Issue by amoskaliov** [ClickHouse/ClickHouse#26220]
**Problem**
Currently Clickhouse offers the following scenario of LDAP login:
1. Directly bind with the user's login and password.
2. While bound find the user's groups.

I have 2 problems with this scenario:
1. Users use `uid` attribute to login (it looks like `j.doe`), while the user's DN in LDAP looks like `cn=John Doe,ou=People,dc=***,dc=ru`. So I can't set appropriate `bind_dn` parameter.
2. Due to security reasons users are not allowed to perform search in the directory. 

**Describe the solution you'd like**
These problems can be solved if Clickhouse uses special LDAP account to find the DN and groups of the user. So the scenario will look like:
1. The user enters uid and password.
2. Clickhouse binds with its own special account and performs search with filter `(&amp;(objectClass=posixAccount)(uid={user_name}))` to get the DN of the user (string like `cn=John Doe,ou=People,dc=***,dc=ru`).
3. Using the found DN and entered password Clickhouse binds to the LDAP to check the password.
4. Then unbinds and with its own account finds user's groups (user's account is not allowed to search, while Clickhouses's account is).

This scenario looks complicated but it's actually widespread. It's supported in many applications we use (actually Clickhouse is the only exception). It's supported in PostgreSQL: https://www.postgresql.org/docs/13/auth-ldap.html (it's called `the search+bind mode`).

**Comment by traceon** [comment]
Makes sense. Will be implemented eventually... probably.
