### ISSUE TITLE
how to write the sql using clickhouse, if i want to get the aggregate results fo each items select from table?

### ISSUE THREAD

**Issue by aohan237** [ClickHouse/ClickHouse#26242]
search all the ways from google to sf, no same questions.

say i have a table，which is about 1T large:

user_id|  pay_time | pay_info
-|-|-
1 | 1232323 | {'num':10, "total":100}
1  |1232324 | {'num':11, "total":110}
1  |1232325  |{'num':12, "total":120}
2  |1232326 | {'num':13, "total":130}
2  |1232327 | {'num':14, "total":140}
2  |1232328 | {'num':15, "total":150}
2  |1232329 | {'num':16, "total":160}

how i get each user' sum total or sum num when he make payments,   he has already spent, which is pay_time less than this current payment's paytime. results as follows:

user_id | pay_time | sum_num| sum_total
-|-|-|-
1 | 1232323  |0 |0
1|  12323234 |10| 100
1 | 12323234 |21 |210
2 | 1232326  |0 |0 
2| 1232327   |13 |130
2  |1232328  |27 |270
2 | 1232329  |42 |420

i have read the docs, but it seems no results.  

and allow_experimental_window_functions seems not working, dont know why.

thanks in advance

**Comment by den-crane** [comment]
>and allow_experimental_window_functions seems not working, dont know why.

Clickhouse version?  `select version()`

**Comment by aohan237** [comment]
> > and allow_experimental_window_functions seems not working, dont know why.
> 
> Clickhouse version? `select version()`

ch-server-11 :) SET allow_experimental_window_functions = 1

SET allow_experimental_window_functions = 1

Query id: 3f2de759-f552-49c5-835f-beb395c2e913

Ok.

0 rows in set. Elapsed: 0.002 sec.

ch-server-11 :) select number, avg(number) over (order by number rows unbounded preceding) from numbers(10);

Syntax error: failed at position 33 ('('):

select number, avg(number) over (order by number rows unbounded preceding) from numbers(10);

Expected one of: LIMIT, WHERE, HAVING, GROUP BY, INTO OUTFILE, OFFSET, PREWHERE, Comma, ORDER BY, SETTINGS, UNION ALL, FROM, FORMAT, WITH, token

ch-server-11 :) select version()

SELECT version()

Query id: 8d308534-db64-4b84-bc43-0703b5f8ed5a

┌─version()─┐
│ 21.7.2.7  │
└───────────┘

1 rows in set. Elapsed: 0.003 sec.

**Comment by aohan237** [comment]
> > and allow_experimental_window_functions seems not working, dont know why.
> 
> Clickhouse version? `select version()`

version is 21.7.2.7

i cant use allow_experimental_window_functions in sql query,  but i config it in user.xml in profile, it works

**Comment by aohan237** [comment]
now that i can use window function to fulfill this.
but what should i do if i want exclude the current row?

it seems that exclude is still unsupported,  is there any alternative ways?

**Comment by akuzm** [comment]
`EXCLUDE CURRENT ROW` is not currently supported and we don't have a timeline for this, but for frames that don't go over current row, you can emulate it by switching from e.g. `ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW` to `ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING`.

**Comment by aohan237** [comment]
> `EXCLUDE CURRENT ROW` is not currently supported and we don't have a timeline for this, but for frames that don't go over current row, you can emulate it by switching from e.g. `ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW` to `ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING`.

thanks

what if i want condition sum, i only want to sum pay_time less than start time,  as follows: how do i fulfill this

user_id |start_time| pay_time | pay_info
-- | --|-- | --
1 | 2|5 | {'num':10, "total":100}
1 | 2|2 | {'num':11, "total":110}
1 | 3|3 | {'num':12, "total":120}
1 | 3|3 | {'num':13, "total":130}

results like this

user_id |start_time| pay_time | sum_num | sum_total
-- | --|-- | -- | --
1 | 2|5 | 0|0
1 | 2|2 |0|0
1 | 3|3 |11|100
1 | 4|4 |23|230

**Comment by alexey-milovidov** [comment]
@akuzm Could you please help with this question?

**Comment by akuzm** [comment]
> @akuzm Could you please help with this question?

This needs a `FILTER` clause which CH doesn't have, but it does have `-If` combinator that has a similar effect.  So `sumIf(payInfo['total'], pay_time < start_time)`.

**Comment by alexey-milovidov** [comment]
@akuzm We have added the FILTER clause:

```
milovidov-desktop :) SELECT sum(number) FILTER(WHERE number % 2 = 0) FROM numbers(10)

SELECT sumIf(number, (number % 2) = 0)
FROM numbers(10)

Query id: 94a0a8ac-1a93-4ff1-b9b9-f043959893c0

┌─sumIf(number, equals(modulo(number, 2), 0))─┐
│                                          20 │
└─────────────────────────────────────────────┘
```
