### ISSUE TITLE
SELECT COUNT(1) super slow, COUNT(*) super fast

### ISSUE THREAD

**Issue by kokizzu** [ClickHouse/ClickHouse#26244]
isn't it should be exactly the same if there's no null?

`COUNT(1)` took more than a minute (unfinished) and 13GB RAM for 160k-ish rows, but `COUNT(*)` took less than 10 ms.

**Comment by amosbird** [comment]
If your clickhouse server has a setting named : `optimize_normalize_count_variants`, it should work as expected.

**Comment by den-crane** [comment]
Clickhouse version?

```sql
create table x ( A String, F Float64) Engine=MergeTree order by A;
insert into x select toString(number), 0 from numbers(100000000)　;

select count(1) from x;
Elapsed: 0.001 sec.


select count() from x;
Elapsed: 0.001 sec


select count(F) from x;
Elapsed: 0.031 sec


select count(A) from x;
Elapsed: 0.272 sec

**Comment by kokizzu** [comment]
2.1.6.5 revision 54448

**Comment by kokizzu** [comment]
hmm.. today it doesn't happened anymore '__') weird (no changes on the server or the queries tho)
