### ISSUE TITLE
not working (or outdated) official build instructions

### ISSUE THREAD

**Issue by alekon** [ClickHouse/ClickHouse#26254]
I'm trying to follow "Faster builds for development " section of build instructions https://clickhouse.tech/docs/en/development/build/#faster-builds-for-development
Did git clone for github repository, then installed clang-11(mentioned as recommended) and build tools from repository:
```
apt install clang-11 cmake ninja-build lld
cd ClickHouse
mkdir build
cd build
```
and then run command:
```
cmake .. -DCMAKE_C_FLAGS="--ld-path=lld" -DCMAKE_CXX_FLAGS="--ld-path=lld" -DUSE_STATIC_LIBRARIES=0 -DSPLIT_SHARED_LIBRARIES=1 -DCLICKHOUSE_SPLIT_BINARY=1
```
With this flags cmake complain about broken C compiler. After googling bit i found that issue may be in incompatible change in clang parameters between v11 and v12 https://github.com/ClickHouse/ClickHouse/issues/17917
After altering flags for clang 11 build works
```
cmake -DCMAKE_C_FLAGS="-fuse-ld=lld" -DCMAKE_CXX_FLAGS="-fuse-ld=lld" -DUSE_STATIC_LIBRARIES=0 -DSPLIT_SHARED_LIBRARIES=1 -DCLICKHOUSE_SPLIT_BINARY=1 ..
```
So it would be nice to note about this issue in build instructions

**Operating system**
OS kind or distribution, specific version/release, non-standard kernel if any. If you are trying to build inside virtual machine, please mention it too.
ubuntu 20.04.2

**Cmake version**
3.16.3

**Ninja version**
1.10.0

**Compiler name and version**
clang 11.0.0-2~ubuntu20.04.1

**Full cmake and/or ninja output**
-- The C compiler identification is Clang 11.0.0
-- The CXX compiler identification is Clang 11.0.0
-- Check for working C compiler: /usr/bin/clang-11
-- Check for working C compiler: /usr/bin/clang-11 -- broken
CMake Error at /usr/share/cmake-3.16/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "/usr/bin/clang-11"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/user/ch/ClickHouse/build/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/ninja cmTC_3a0bc && [1/2] Building C object CMakeFiles/cmTC_3a0bc.dir/testCCompiler.c.o
    FAILED: CMakeFiles/cmTC_3a0bc.dir/testCCompiler.c.o 
    /usr/bin/clang-11   --ld-path=lld -o CMakeFiles/cmTC_3a0bc.dir/testCCompiler.c.o   -c testCCompiler.c
    clang: error: unsupported option '--ld-path=lld'
    ninja: build stopped: subcommand failed.
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:29 (project)

-- Configuring incomplete, errors occurred!
See also "/home/user/ch/ClickHouse/build/CMakeFiles/CMakeOutput.log".
See also "/home/user/ch/ClickHouse/build/CMakeFiles/CMakeError.log".

**Comment by alexey-milovidov** [comment]
I've updated the docs: https://github.com/ClickHouse/ClickHouse/commit/f30e614165183a5dca7276e532f7ff482960463a

`lld` is used by default.
