### ISSUE TITLE
Unfold all macros when creating ReplicatedMergeTree

### ISSUE THREAD

**Issue by siradjev** [ClickHouse/ClickHouse#26251]
**Use case**
Currently on creation of replicated merge tree, metadata SQL files are kept as-is (except for {database}, {table}) macros. 
As every replicated merge tree relies heavily on zookeeper path, and zookeeper path is assumed to be constant and never changing, it makes more sense to resolve all of the macros, not just {database} and {table}. 
With current behavior clickhouse won't load existing table correctly in case macro is updated (e.g. replica name is modified, or shard numbering strategy is decided to be changed). 
Because zookeeper does not allow renaming, it does not make much sense to keep placeholders, except for manual moving sql files to new cluster. 

**Describe the solution you'd like**
When creating Replicated Merge tree, all of macros to be unfolded / resolved. 
Original macros string may remain in metadata.sql or creation script as commented line for simplicity. 
it has already been fixed for {database} and {table} macros before, since it was leading to problems like #25953. 

there is another thought by @alexey-milovidov in https://github.com/ClickHouse/ClickHouse/issues/6917#issuecomment-531702719

```
We can unfold these macros at the table creation
but we should not unfold all other macros (shard, layer, etc.)
because there is typical scenario when table metadata (.sql) is copied between shards.

And the proposed logic of unfolding some macros and not unfolding other macros looks questionable.
```

However, it's not clear about potential issues. "ON CLUSTER" syntax is more correct way of creating table across shards. 

**Describe alternatives you've considered**
Currently the only alternative is to manually create script that bulk traverses through all metadata and makes necessary replacements.

**Comment by alexey-milovidov** [comment]
This task has to be closed because its priority is vanishingly low and it does not even make sense to keep it in the backlog.

**Comment by ilejn** [comment]
@alexey-milovidov , are there any advantages of current behavior?
If no, do you mind if we (Arenadata) handle this issue?
BTW, have a look https://t.me/clickhouse_ru/295820
