### ISSUE TITLE
exception rows in system.replication_queue 

### ISSUE THREAD

**Issue by onine007** [ClickHouse/ClickHouse#26259]
There are some "Code: 49, e.displayText() = DB::Exception: Unexpected merged part 14_3559_3680_1_3694 intersecting drop range 14_3651_3651_999999999_3656 (version 21.3.14.1 (official build))"  error  rows in   table   system.replication_queue ;

last_exception:         Code: 49, e.displayText() = DB::Exception: Unexpected merged part 14_3559_3680_1_3694 intersecting drop range 14_3651_3651_999999999_3656 (version 21.3.14.1 (official build))

postpone_reason:        Not executing log entry queue-0000325368 of type DROP_RANGE for part 14_3651_3651_999999999_3656 because another DROP_RANGE or REPLACE_RANGE entry are currently executing.

Restart  clickhouse-server is not disappear

**Comment by tavplubix** [comment]
Fixed in #25549
