### ISSUE TITLE
clickhouse connect HDFS, I want to modify the user who logs in to HDFS.

### ISSUE THREAD

**Issue by yuwoliang** [ClickHouse/ClickHouse#26264]
When I log in to other use in Clickhouse, I want to log in to HDFS with different users, how can I do? The hadoop security authentication is simple.

**Comment by kssenii** [comment]
It can be implemented by adding `hdfsBuilderSetUserName`. You want to be able specify a specific user for each hdfs table? I can add a new engine argument for this.

**Comment by yuwoliang** [comment]
Thank you very much for your quick reply. Yes, In our hdfs, each hdfs path has its own owner. We cannot use hive (super user) to access, so when reading data, we need to switch the user name. 
How to configure the hdfsBuilderSetUserName you mentioned? The version I use is 20.8.7.

**Comment by kssenii** [comment]
> How to configure

It is not configuration I mentioned, but a change in code. I can add this change and then adding a user will require to add one more hdfs engine argument.

> The version I use is 20.8.7.

But new abilities are not backported to old versions. If implemented, it will be available only in last versions.

**Comment by yuwoliang** [comment]
OK, Thank you.

**Comment by yanghong** [comment]
Do you use clickhouse HDFS engine?

**Comment by kssenii** [comment]
> Yes, In our hdfs, each hdfs path has its own owner. We cannot use hive (super user) to access, so when reading data, we need to switch the user name.

@yuwoliang, actually use can already specify a username in url, it will be set if present.
