### ISSUE TITLE
MongoDB engine can't connect to mongo without auth

### ISSUE THREAD

**Issue by ST-eugenekrivdyuk** [ClickHouse/ClickHouse#26267]
**Describe the unexpected behaviour**
`MongoDB` engine is failing to fetch data from collection when Mongo server doesn't have auth enabled.

**How to reproduce**
* Which ClickHouse server version to use
21.3.14.1
* `CREATE TABLE` statements for all tables involved

``` sql
CREATE TABLE IF NOT EXISTS mongo_table
(
    ...
)
ENGINE = MongoDB('<HOST>:<PORT>', '<DB_NAME>', '<COLLECTION_NAME>', '', '')
```
Note that I left user and password empty because Mongo doesn't have auth configured.

* Queries to run that lead to unexpected result

```
SELECT *
FROM mongo_table
LIMIT 1

Query id: 36aac235-e93c-493e-a1e3-346b5397dad9

0 rows in set. Elapsed: 0.004 sec.

Received exception from server (version 21.3.14):
Code: 1000. DB::Exception: Received from localhost:9000. DB::Exception: Invalid argument: empty username.
```

**Expected behavior**
If user and password are empty Clickhouse should connect to MongoDB without auth.

**Comment by akuzm** [comment]
This is a limitation of the Poco library we use to work with Mongo. We could support it.
