### ISSUE TITLE
Optimization Union/Join at query filtration

### ISSUE THREAD

**Issue by fantom0005** [ClickHouse/ClickHouse#26268]
**Use case**
We join/union several tables with billions of rows of ad campaigns data, filtered by time range. For the most of the cases we need only recent months of data. But now it spends a lot of memory because the external filter doesn't apply on table which we join/union. 
So all data in the joined table is loaded into RAM.

Someone in Clickhouse support chat (telegram) has recommended a workaround with the suggestion to join sub queries parametrized via custom settings. But it isn't convenient as we want to create views with joins/unions and use them for directly connected BI tools (different filters applied on fly).

**Describe the solution you'd like**
We have 2 tables and we write join sql.
```sql
create table ads_report
(
    date Date,
    ad_id String,
    clicks Float64
)
engine = MergeTree PARTITION BY toYYYYMM(date)
ORDER BY date;

create table ads_report_2
(
    date Date,
    ad_id String,
    impression Float64
)
engine = MergeTree PARTITION BY toYYYYMM(date)
ORDER BY date;
```
```sql
# query with join
select * from ads_report ar
join ads_report_2 ar2 on ar.ad_id=ar2.ad_id and ar.date = ar2.date
where ar.date >= '2021-01-01';

# current plan
EXPLAIN
SELECT *
FROM ads_report AS ar
INNER JOIN ads_report_2 AS ar2 ON ar.ad_id = ar2.ad_id
WHERE ar.date >= '2021-01-01'

┌─explain─────────────────────────────────────────────────────────────────────────────┐
│ Expression (Projection)                                                             │
│   CreatingSets (Create sets before main query execution)                            │
│     Expression (Before ORDER BY)                                                    │
│       Filter (WHERE)                                                                │
│         Join (JOIN)                                                                 │
│           Expression (Before JOIN)                                                  │
│             SettingQuotaAndLimits (Set limits and quota after reading from storage) │
│               ReadFromPreparedSource (Read from NullSource)                         │
│     CreatingSet (Create set for JOIN)                                               │
│       Expression (Projection + Before ORDER BY)                                     │
│         SettingQuotaAndLimits (Set limits and quota after reading from storage)     │
│           ReadFromPreparedSource (Read from NullSource)                             │
└─────────────────────────────────────────────────────────────────────────────────────┘

# --------------------------------------
# desired plan. It's like use subquery


EXPLAIN
SELECT *
FROM ads_report AS ar
INNER JOIN 
(
    SELECT *
    FROM ads_report_2
    WHERE date >= '2021-01-01'
) AS ar2 ON (ar.ad_id = ar2.ad_id) AND (ar.date = ar2.date)
WHERE ar.date >= '2021-01-01'


┌─explain─────────────────────────────────────────────────────────────────────────────┐
│ Expression (Projection)                                                             │
│   CreatingSets (Create sets before main query execution)                            │
│     Expression (Before ORDER BY)                                                    │
│       Filter (WHERE)                                                                │
│         Join (JOIN)                                                                 │
│           Expression (Before JOIN)                                                  │
│             SettingQuotaAndLimits (Set limits and quota after reading from storage) │
│               ReadFromPreparedSource (Read from NullSource)                         │
│     CreatingSet (Create set for JOIN)                                               │
│       Expression (Projection + Before ORDER BY)                                     │
│         Filter (WHERE)   # need to this filter                                      │
│           SettingQuotaAndLimits (Set limits and quota after reading from storage)   │
│             ReadFromPreparedSource (Read from NullSource)                           │
└─────────────────────────────────────────────────────────────────────────────────────┘
```

***High level solution***
Guys, I know that the steps are naive and not so simple. But I imagine it this way:
* receive fields which tables joined
* get external filters by this fields
* apply filters on SQL for the query which loaded data from joined table 
* ... do standard algorithm

**PS**
Possibly we can develop this feature ourselves. But we don't have experience with clickhouse.
Can you say how difficult it is?
How long can implantation take?

**Comment by akuzm** [comment]
This is a straightforward optimization we would want to have. When we have an inner equi-join, we should create an "equivalence class" (in pg terms) that records the fact that `ad_id` on both sides is the same. Then we should move this inequality condition to the equivalence class. Then we should re-generate the inequality clause for both tables from this equivalence class.

I guess you shouldn't try to implement it yourself now, because the topic is tricky and we have several efforts underway around this area, that would involve a significant refactoring. E.g. this PR is relevant https://github.com/ClickHouse/ClickHouse/pull/18787

@vdimir FYI

**Comment by fantom0005** [comment]
@akuzm Thank you.
Yes, solution with  "equivalence class" sounds difficult. We won't try to implement it ourselves, but this feature is critical for our solution, and we’re ready to help with the implementation (if we can). Could you please share the estimated time of its availability and any options how we can help?

**Comment by vdimir** [comment]
By the way, there's WIP PR https://github.com/ClickHouse/ClickHouse/pull/24420, that I suppose allows to apply optimization of used memory with filters. If we'll change condition to `ar2.date >= '2021-01-01'` (use column for right table explicitly) and place this condition to JOIN ON section then hash table for join will contain filtered values. 
I'll check if it actually works like this. If it is, implementing optimization that will push down conditions from `WHERE` may be next step

**Comment by akuzm** [comment]
An older similar issue: https://github.com/ClickHouse/ClickHouse/issues/10913

**Comment by aovlexus** [comment]
@akuzm any updates here. 

This PR  https://github.com/ClickHouse/ClickHouse/pull/24420 (Support conditions in JOIN ON section). But https://github.com/ClickHouse/ClickHouse/pull/18787 has many conflicts and looks like will be never joined. We  extremely need this feature.

How we can push this issue forward?

**Comment by vdimir** [comment]
@aovlexus I'm going to implement kind of push down for filters for right table in JOIN. Actually it's close to #24420 , but need to analyze `WHERE` section.
I suppose I'll just start only after https://github.com/ClickHouse/ClickHouse/pull/21320 will be merged, because now it may cause conflicts difficult to resolve. 

So, no estimation yet, but it's in the plans.

**Comment by kitaisreal** [comment]
Closed by https://github.com/ClickHouse/ClickHouse/pull/61216.
