### ISSUE TITLE
After 'no space' error and cleaned up disk, 'create table' throws exception

### ISSUE THREAD

**Issue by innerr** [ClickHouse/ClickHouse#2628]
What I did: executed query "create table mytable ..." from clickhouse-client
What I got: a error about 'no space on disk'

Then I cleaned up my disk, made some space, and reran the query.
What I got: a error about 'file exists: <data-path>/db/metadata/<database>/mytable.sql.tmp'

I can't processed until I deleted this tmp file.

**Comment by alexey-milovidov** [comment]
Server will clean old tmp files on startup. So, the issue will be solved by server restart.

Why we don't remove tmp file if it is already exist before creating new file? This is left as an additional protection against concurrent creates (we open file with O_EXCL; though it is concurrent creates are already protected by `DDLGuard`).

We still can remove tmp file in case of exception. Look at `DatabaseOrdinary.cpp`, method `DatabaseOrdinary::createTable`. This is easy to implement.

**Comment by alexey-milovidov** [comment]
@nikitamikhaylov 
Is it fixed?

**Comment by nikitamikhaylov** [comment]
It is not fixed. No Exception is being catched now. https://github.com/ClickHouse/ClickHouse/blob/458f596e187c75c4e77669bfc0831cfe20b3b986/dbms/src/Databases/DatabaseOnDisk.cpp#L145-L155
Will send PR.

**Comment by alexey-milovidov** [comment]
It is fixed.
