### ISSUE TITLE
Unsupported value when reading Array from dictionary with MySQL as source

### ISSUE THREAD

**Issue by quoc-t-le** [ClickHouse/ClickHouse#26299]
Just wanted to test out this item in change log:

Added support for Array type in dictionaries. #25119 

I created a view in MySQL 5.7 for the dictionary to read from, I mimic an array column like so:

1. null as test_array_column
2. '[]' as test_array_column
3. '[1337,7331]' as test_array_column
4. JSON_ARRAYAGG(...) as test_array_column

When I reload the dictionary that uses that as source only # 1 did not give an error listed below.  Not sure if it supports MySQL as source or I am not correctly defining the column.  Looking at the tests (https://github.com/kitaisreal/ClickHouse/blob/b1e72163ec393636be23db155c9e5694dfd73e03/tests/queries/0_stateless/01902_dictionary_array_type.sql) I only see clickhouse as the source.

` <dictionary>
        ...
        <layout>
            <hashed />
        </layout>

        <source>
            <mysql>
                ...
                <table>v_array_test</table>
            </mysql>
        </source>

        <structure>
            ... 
            <attribute>
                <name>test_array_column</name>
                <type>Array(UInt32)</type>
                <null_value>[]</null_value>
            </attribute>
        </structure>
</dictionary>`

**Error message and/or stacktrace**

2021.07.13 20:48:42.397517 [ 55 ] {96fd76a8-9115-425a-8753-176d15dd5408} <Error> executeQuery: Code: 48, e.displayText() = DB::Exception: Unsupported value type (version 21.7.2.7 (official build)) (from 127.0.0.1:54496) (in query: -- Setup and reload dictionaries
system reload dictionary array_dict_test;), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x8d35c1a in /usr/bin/clickhouse
1. ? @ 0x106d9e67 in /usr/bin/clickhouse
2. DB::MySQLBlockInputStream::readImpl() @ 0x106d9002 in /usr/bin/clickhouse
3. DB::IBlockInputStream::read() @ 0xf51faa4 in /usr/bin/clickhouse
4. DB::HashedDictionary<(DB::DictionaryKeyType)0, false>::loadData() @ 0xdd282ec in /usr/bin/clickhouse
5. DB::HashedDictionary<(DB::DictionaryKeyType)0, false>::HashedDictionary(DB::StorageID const&, DB::DictionaryStructure const&, std::__1::unique_ptr<DB::IDictionarySource, std::__1::default_delete<DB::IDictionarySource> >, DB::HashedDictionaryStorageConfiguration const&, std::__1::shared_ptr<DB::Block>) @ 0xdd27f49 in /usr/bin/clickhouse
6. ? @ 0xdeb34bd in /usr/bin/clickhouse
7. ? @ 0xdeb305b in /usr/bin/clickhouse
8. DB::DictionaryFactory::create(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Poco::Util::AbstractConfiguration const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context const>, bool) const @ 0xf21ca32 in /usr/bin/clickhouse
9. DB::ExternalDictionariesLoader::create(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Poco::Util::AbstractConfiguration const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const @ 0xf83c7e4 in /usr/bin/clickhouse
10. DB::ExternalLoader::LoadingDispatcher::loadSingleObject(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::ExternalLoader::ObjectConfig const&, std::__1::shared_ptr<DB::IExternalLoadable const>) @ 0xf848f37 in /usr/bin/clickhouse
11. DB::ExternalLoader::LoadingDispatcher::doLoading(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, bool, unsigned long, bool, std::__1::shared_ptr<DB::ThreadGroupStatus>) @ 0xf846252 in /usr/bin/clickhouse
12. ThreadFromGlobalPool::ThreadFromGlobalPool<void (DB::ExternalLoader::LoadingDispatcher::*)(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, bool, unsigned long, bool, std::__1::shared_ptr<DB::ThreadGroupStatus>), DB::ExternalLoader::LoadingDispatcher*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, unsigned long&, bool&, unsigned long&, bool, std::__1::shared_ptr<DB::ThreadGroupStatus> >(void (DB::ExternalLoader::LoadingDispatcher::*&&)(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, bool, unsigned long, bool, std::__1::shared_ptr<DB::ThreadGroupStatus>), DB::ExternalLoader::LoadingDispatcher*&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, unsigned long&, bool&, unsigned long&, bool&&, std::__1::shared_ptr<DB::ThreadGroupStatus>&&)::'lambda'()::operator()() @ 0xf84d033 in /usr/bin/clickhouse
13. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x8d76adf in /usr/bin/clickhouse
14. ? @ 0x8d7a3c3 in /usr/bin/clickhouse
15. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
16. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so

**Additional context**
Clickhouse 21.7.2.7
MySQL 5.7

**Comment by kssenii** [comment]
Array type is not supported for MySQL dictionary source. The exception message `DB::Exception: Unsupported value type` is correct.

**Comment by quoc-t-le** [comment]
If you click the item in change log:
Added support for Array type in dictionaries. #25119

The feature claims to close #2135.

and not you say its not supported for MySQL?

**Comment by kssenii** [comment]
Yes, not supported. 
Here is a list of what types are supported: https://github.com/ClickHouse/ClickHouse/blob/master/src/Formats/MySQLBlockInputStream.cpp#L119-L208.

As for  #2135 - it means that array types now can be supported for external dictionaries in case of there is a defined convertion via client library. For example, it is implemented for PostgreSQL dictionary source so array types are supported for it. For MySQL they are not, because there is no defined conversion in the link above.
