### ISSUE TITLE
Access rights intersection got wrong result

### ISSUE THREAD

**Issue by Cas-pian** [ClickHouse/ClickHouse#26293]
**Describe the bug**

A clear and concise description of what works not as it is supposed to.

Privileges intersect operation has a bug,  @vitlibar 

**How to reproduce**

ck: 21.4.4.30
```sql
create user if not exists test;

grant show on db1.tb1 to a;

grant select on db2.* to a;
```

**Expected behavior**

The intersection of the two previous access rights `should be empty`, but the method `AccessRights`.`makeIntersection()` produces `show on db1.tb1` as the result, which should be wrong.

**Comment by vitlibar** [comment]
`AccessRights.makeIntersection()` is an internal function, it's used currently only to find out if the current user have enough access rights granted with grant option to execute the `REVOKE` command. I don't quite understand the connection to your example. In your example the user named `test` will get access rights on `db1.tb1` and at the same time on each table in the database `db2`. `AccessRights.makeIntersection()` must not be even called while executing your example.

**Comment by Cas-pian** [comment]
@vitlibar Thanks for your response.  
Yes, it's a internal function, and I found the result of intersection is werid when I develop a new feature which uses this function. And I'll show my feature in minutes. Thanks.

**Comment by Cas-pian** [comment]
@vitlibar This is my [code](https://github.com/Cas-pian/ClickHouse/commit/4c0456650a3558be0483d4d666cbc402396920d3) to add [grant replace](https://github.com/ClickHouse/ClickHouse/issues/25395) feature support. And I'm trying to test the case and got the wrong result.  
   
So I've got a little debuging and found `AccessRights.makeIntersection()` remains false access rights, [this](7dc5b6bdc06a970a46537558ae80cae9138c6d5d) is my trying for fix this, and I'm a little confused of the flags. PTAL

**Comment by vitlibar** [comment]
I've fixed the issue with `makeIntersection()`. By the way, it seems `grant replace` can be implemented by adding about four lines to the beginning of `updateFromQueryTemplate()`:

```
if (query.replace_access)
    grantee.access = {};
if (query.replace_roles
    grantee.granted_roles = {};
```

**Comment by Cas-pian** [comment]
> I've fixed the issue with `makeIntersection()`. 

Nice work. Thanks for you quick fix.

And let's discuss the implment detail [here](https://github.com/ClickHouse/ClickHouse/pull/26384), thanks
