### ISSUE TITLE
Occasionally authentication failed occurs (hostname_pattern is used, `getaddrinfo` does not work)

### ISSUE THREAD

**Issue by Sallery-X** [ClickHouse/ClickHouse#26333]
You have to provide the following information whenever possible.

Which ClickHouse server version to use
21.3.5.42
the error like this
![image](https://user-images.githubusercontent.com/45587738/125724907-6e8f4aaa-7ba4-46ce-b81f-cc71022967d4.png)

**Comment by alexey-milovidov** [comment]
Your DNS server cannot perform requests in some cases.
