### ISSUE TITLE
How to Configm Who Uses the Memory of the Clickhouse Process?

### ISSUE THREAD

**Issue by wallace-clickhouse** [ClickHouse/ClickHouse#26355]
I found that clickhouse server memory usage is always around 22% while no merge task or query is being executed,it's very strange.So how can I check and analyze the memory usage of clickhouse server to find who is occupying the memory.

**Comment by UnamedRus** [comment]
https://kb.altinity.com/altinity-kb-setup-and-maintenance/altinity-kb-who-ate-my-memory
