### ISSUE TITLE
Clickhouse failed to start due to suspicious parts

### ISSUE THREAD

**Issue by kymtwyf** [ClickHouse/ClickHouse#26370]
my clickhouse server failed to start due to below error messages:
```
2021.07.15 21:30:12.251401 [ 1 ] {} <Error> Application: DB::Exception: The local set of parts of table db.table doesn't look like the set of parts in ZooKeeper: 34.00 rows of 34.00 total rows in filesystem are suspicious. There are 1 unexpected parts with 34 rows (0 of them is not just-written with 34 rows), 0 missing parts (with 0 blocks).: Cannot attach table `db`.`table` from metadata file /var/lib/clickhouse/metadata/db/table.sql from query ATTACH TABLE table (`exp_id` UInt64, `phase_id` UInt32, `start_dt` Nullable(Date), `end_dt` Nullable(Date)) ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/{database}/table', '{replica}') ORDER BY tuple() SETTINGS index_granularity = 8192
```

How can I fix this to start the server?

**Comment by akuzm** [comment]
This means that the local data is not consistent with metadata in Zookeeper.
First of all, check that the Zookeeper path is correct.
If it is correct, follow this manual to restore the data on this replica from other replicas: https://clickhouse.tech/docs/en/engines/table-engines/mergetree-family/replication/#recovery-after-failures

**Comment by kymtwyf** [comment]
@akuzm thank you for your quick response! It is helpful !!!
