### ISSUE TITLE
Read and Write separation implementation. 

### ISSUE THREAD

**Issue by moweonlee** [ClickHouse/ClickHouse#26395]
I have been looking for some documents to implement Read/Write separation in distributed table.

And I found an issue that read-write separation can be archived by using "always_fetch_merged_parts" in following [link].(https://github.com/ClickHouse/ClickHouse/issues/18452) 

But I can't find any detail instruction to do that.

So can I get any detail instruction to do read-write separation ? 

But anyway I think I could do that like this .

 I have thought there should be some nodes to ingest write and merge them to deliver merged data to read only cluster and also exactly same number of nodes are necessary in read only cluster because we can't divide or merge data parts.
So this is a constraint that I think. I just want to say this to confirm that my understanding right or wrong. 

 The basic ideas that I have thought are each ReplicatedMergeTree should be defined with a extra remote replica in read only node.
And a distributed table is also required to connect every ReplicatedMergeTree to read them at once in read cluster.
 
 But I'm not sure how it can explicitly define the master node and secondary node to read only merged-data in read only cluster. 

Any examples or guides are welcome . 

Thanks in advance.

**Comment by den-crane** [comment]
always_fetch_merged_part is a merge tree setting. https://clickhouse.tech/docs/en/operations/settings/merge-tree-settings/#merge-tree-settings

```
# cat /etc/clickhouse-server/config.d/always_fetch_merged_part.xml
<?xml version="1.0"?>
<yandex>
    <merge_tree>
        <always_fetch_merged_part>1</always_fetch_merged_part>
    </merge_tree>
</yandex>
```

**Comment by moweonlee** [comment]
Thank you for your information.

So I have configured a distributed table which have 2 nodes (1,2 ) as write role and other nodes  (3,4 ) as fetch role.

Then does this distributed table **write** data into Node 3,4 ( fetch_only) when Node 1,2 failed?

```
CREATE TABLE default.dtest_table ENGINE=Distributed( 'test_cluster', default, test_table, rand() )

# Node 1 
CREATE TABLE test_table(
    key UInt64,
    value String
) ENGINE = ReplicatedMergeTree('/clickhouse/tables/test_table/shard1_replicated', '1')
ORDER BY tuple()

# Node 2 
CREATE TABLE test_table(
    key UInt64,
    value String
) ENGINE = ReplicatedMergeTree('/clickhouse/tables/test_table/shard2_replicated', '2')
ORDER BY tuple()


# Node 3 ( Fetch data from Node 1 ) 
CREATE TABLE test_table(
    key UInt64,
    value String
) ENGINE = ReplicatedMergeTree('/clickhouse/tables/test_table/shard1_replicated', '1')
ORDER BY tuple()
SETTINGS always_fetch_merged_part=1

# Node 4 ( Fetch data from Node 2  ) 
CREATE TABLE test_table(
    key UInt64,
    value String
) ENGINE = ReplicatedMergeTree('/clickhouse/tables/test_table/shard2_replicated', '2')
ORDER BY tuple()
SETTINGS always_fetch_merged_part=1
```

**Comment by alexey-milovidov** [comment]
You should configure two clusters in the `<remote_servers>`, one to be used for readers and another to be used for writers. They can span across a different subset of replicas.
