### ISSUE TITLE
Slicing rows by previous rows

### ISSUE THREAD

**Issue by dolbyzerr** [ClickHouse/ClickHouse#2641]
Hello, I have a question regarding tables design and/or querying.

I have two tables `Sessions` and `Orders`. I need to have sessions of each order joined by visitor.

Each user journey is represented by this sequence (session1, session2, session3, order1, sessions4, sessions5, order2)

So each session before order and after the previous order belongs to that order, at the end of the day I need this set of data:

```
(order1 <= session1, session2, session3)
(order2 <= sessions4, sessions5)
```

__My sample tables:__

## Sessions

| dateTime   | visitorId | sessionId |
| ---------- | --------- | --------- |
| 2018-01-01 | v1        | s1        |
| 2018-01-02 | v1        | s2        |
| 2018-01-03 | v2        | s3        |
| 2018-01-04 | v1        | s4        |
| 2018-01-05 | v2        | s5        |
| 2018-01-06 | v3        | s6        |

## Orders

| dateTime   | visitorId | orderId |
| ---------- | --------- | ------- |
| 2018-01-03 | v1        | o1      |
| 2018-01-05 | v1        | o2      |
| 2018-01-06 | v2        | o3      |

__Resulting table that I am loogin for:__

## OrdersWithSessions

| dateTime   | visitorId | orderId | sessions |
| ---------- | --------- | ------- | -------- |
| 2018-01-03 | v1        | o1      | [s1,s2]  |
| 2018-01-05 | v1        | o2      | [s4]     |
| 2018-01-06 | v2        | o3      | [s3,s5]  | 

or

## OrdersWithSessions

| dateTime   | visitorId | orderId | sessionId |
| ---------- | --------- | ------- | --------- |
| 2018-01-03 | v1        | o1      | s1        |
| 2018-01-03 | v1        | o1      | s2        |
| 2018-01-05 | v1        | o2      | s4        |
| 2018-01-06 | v2        | o3      | s3        |
| 2018-01-06 | v2        | o3      | s5        |

I am not sure how to do that without a dependent subquery.

Maybe I should change something is schema design slightly?

**Comment by alexey-milovidov** [comment]
This should be the case for ASOF JOIN.
Let's check if it's applicable...

**Comment by alexey-milovidov** [comment]
Yes, it's doable with ASOF JOIN:

```
CREATE TEMPORARY TABLE sessions (date DateTime, visitorId String, sessionId String);
CREATE TEMPORARY TABLE orders (date DateTime, visitorId String, orderId String);

INSERT INTO sessions VALUES
('2018-01-01 00:00:00', 'v1', 's1'),
('2018-01-02 00:00:00', 'v1', 's2'),
('2018-01-03 00:00:00', 'v2', 's3'),
('2018-01-04 00:00:00', 'v1', 's4'),
('2018-01-05 00:00:00', 'v2', 's5'),
('2018-01-06 00:00:00', 'v3', 's6');

INSERT INTO orders VALUES
('2018-01-03 00:00:00', 'v1', 'o1'),
('2018-01-05 00:00:00', 'v1', 'o2'),
('2018-01-06 00:00:00', 'v2', 'o3');

SELECT 
    visitorId, 
    orderId, 
    groupUniqArray(sessionId)
FROM sessions
ASOF INNER JOIN orders ON (sessions.visitorId = orders.visitorId) AND (sessions.date <= orders.date)
GROUP BY 
    visitorId, 
    orderId
ORDER BY 
    visitorId ASC, 
    orderId ASC;
```
