### ISSUE TITLE
Nested columns with dot in their name are not unnested by ARRAY JOIN close

### ISSUE THREAD

**Issue by cyrilou242** [ClickHouse/ClickHouse#26427]
**Description**
When using nested arrays, nested columns that have a dot in their name are not unnested by an ARRAY JOIN close. 
This is unexpected because it's written in the [ARRAY JOIN Clause doc](https://clickhouse.tech/docs/en/sql-reference/statements/select/array-join/#array-join-with-nested-data-structure):

> When specifying names of nested data structures in ARRAY JOIN, the meaning is the same as ARRAY JOIN with all the array elements that it consists of

 

**How to reproduce**
Reproduced on ClickHouse server version 21.6.5 revision 54448. Should also be true for newer versions.

```
CREATE TABLE mini_session_dot (
id String, 
hits Nested(number Int64, `info.Info11` String, `info.Info22` String)
) Engine = MergeTree() ORDER BY id
```

```
DESCRIBE TABLE mini_session_dot
|─name─────────────┬─type──────────┬
│ id               │ String        │
│ hits.number      │ Array(Int64)  │
│ hits.info.Info11 │ Array(String) │
│ hits.info.Info22 │ Array(String) │
└──────────────────┴───────────────┴
```
* Queries to run that lead to unexpected result: 
```
DESCRIBE TABLE (select * from mini_session_dot array join hits)
|─name─────────────┬─type──────────┬
│ id               │ String        │
│ hits.number      │ Int64         │
│ hits.info.Info11 │ Array(String) │
│ hits.info.Info22 │ Array(String) │
└──────────────────┴───────────────┴
```
Array join is not performed on `hits.info.Info11` and `hits.info.Info22`.

**Expected behavior**
According to the [documentation](https://clickhouse.tech/docs/en/sql-reference/statements/select/array-join/#array-join-with-nested-data-structure), statement above should return: 
```
|─name─────────────┬─type──────────┬
│ id               │ String        │
│ hits.number      │ Int64         │
│ hits.info.Info11 │ String        │
│ hits.info.Info22 │ String        │
└──────────────────┴───────────────┴
```

**Current possible workarounds are:**
- explicit array join for columns that contains dots
```
DESCRIBE TABLE (select * from mini_session_dot array join hits, hits.info.Info11, hits.info.Info22)
┌─name─────────────┬─type───┬
│ id               │ String │
│ hits.number      │ Int64  │
│ hits.info.Info11 │ String │
│ hits.info.Info22 │ String │
└──────────────────┴────────┴
```
This works fine, but this means we lose the syntactic sugar of the `Nested` field.
- use a COLUMNS statement: 
```
DESCRIBE TABLE (select * from mini_session_dot array join COLUMNS('^hits'))
┌─name─────────────┬─type───┬
│ id               │ String │
│ hits.number      │ Int64  │
│ hits.info.Info11 │ String │
│ hits.info.Info22 │ String │
└──────────────────┴────────┴
```

This works fine, but feels a bit hacky. 
Also, it may be impossible to do with bad column naming. (but it would not happen in real life I think). Eg: if `id` is renamed `hitsAAAAA` it matches the regex.

**Comment by den-crane** [comment]
dot characters is reserved and cannot be used in column names

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/18765
