### ISSUE TITLE
Add settings to disable merges for a replica

### ISSUE THREAD

**Issue by alex-zaitsev** [ClickHouse/ClickHouse#2642]
We would like to implement a scenario when merges are running on a leader replica only, and other replicas fetch merged parts from the leader one. That allows to have complete separation of data insertion/merging from queries. Currently, there is no way to do that. 

Please add settings similar to prefer_fetch_merged_part_*. E.g.

force_fetch_merged_part
force_fetch_merged_part_size_threshold

**Comment by filimonov** [comment]
Does it have sence? What are advantages of that scenario?

I.e. currently merge process time = read data from disk time + write data to disk time. Bottleneck is disk io, not CPU, as merge sort in case if source parts are already sorted (they are) should be executed in linear time.

After change it would be:
merge process time = read part from network time + write data to disk time. Bottleneck is netword io + disk io, not CPU again (if your network card can send data to disk without CPU help).

10Gbps network can be faster that disks, but if the network channel to your server will be 100% busy, the server will not be responsible, so you need to limit the bandwidth or have multiple network cards. The volumes of data to be send will be really huge. The server which will do merges will need to send parts to all the replicas, without multicasting it will overuse network on that server (i.e. to send 100 Gb part to 5 replicas it will need to send 500 Gb).

**Comment by alex-zaitsev** [comment]
Currently: read-merge-write. Don't forget that merge has to decompress and compress the data that is CPU intensive.
With fetch only: network-write

Less CPU and I/O.

**Comment by alexey-milovidov** [comment]
Do the following MergeTree settings work for you?
```
/** After specified amount of time passed after replication log entry creation                            \
     *  and sum size of parts is greater than threshold,                                                      \
     *  prefer fetching merged part from replica instead of doing merge locally.                              \
     *  To speed up very long merges. */                                                                      \
    M(SettingSeconds, prefer_fetch_merged_part_time_threshold, 3600)                                          \
    M(SettingUInt64, prefer_fetch_merged_part_size_threshold, 10ULL * 1024 * 1024 * 1024)                     \
```

Write them down in config.xml in `merge_tree` section.

**Comment by alexey-milovidov** [comment]
> Do the following MergeTree settings work for you?

These setting should work for this task.
