### ISSUE TITLE
Add a setting `allow_suspicious_indices`.

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#26467]
Not sure is UB or expected B.

```sql
CREATE TABLE test
(
    `a` Int64
)
ENGINE = MergeTree
PRIMARY KEY a
ORDER BY (a, a);

ALTER TABLE test
    ADD COLUMN `b` Int64,     MODIFY ORDER BY (a, a, b, b, b);

SHOW CREATE TABLE test;

CREATE TABLE test
(
    `a` Int64,
    `b` Int64
)
ENGINE = MergeTree
PRIMARY KEY a
ORDER BY (a, a, b, b, b)
SETTINGS index_granularity = 8192
```

**Comment by alexey-milovidov** [comment]
Add a setting `allow_suspicious_indices`.
The index is considered suspicious if it contains identical expressions.
This applies to: ORDER BY, PRIMARY KEY, and secondary indices.

The setting is checked on CREATE and ALTER queries but not on ATTACH query.

It should be 0 by default if `compatibility` is at least 22.10.

**Comment by lingtaolf** [comment]
May I have a try ?

**Comment by alexey-milovidov** [comment]
@lingtaolf Thank you, this will be very helpful!

**Comment by alexey-milovidov** [comment]
This task is available.
