### ISSUE TITLE
Lots of empty tmp_merge_... directories under $TMP_PATH leading to significant time to chown on startup

### ISSUE THREAD

**Issue by jacobrandall** [ClickHouse/ClickHouse#26471]
**Describe the issue**
After running a cluster for ~6 months, I've noticed the chown on startup take ~30 minutes. On a new cluster the chown time is barely noticeable, probably 1 minute or so. Running `df -i` shows inode usage of ~2.1M inodes on `/var/lib/clickhouse` and digging in shows that 1.97M of that is under `/var/lib/clickhouse/tmp/data/default/$TABLE_NAME_REDACTED`, which has only 5 files, and the rest of the 1.97M are empty directories named `tmp_merge_...`. I believe the speed of the chown of ~2M inodes is relative to the read / write IOPs available on the volume.

**How to reproduce**
* Which ClickHouse server version to use
  * `20.11.3.3`

**Expected behavior**
Either on startup or as part of normal background processes, cleanup of these tmp directories after merges complete.

**Error message and/or stacktrace**
N/A

**Additional context**
N/A

One possible solution I'm considering, but would like to confirm if it's safe is perhaps removing everything (or at least empty dirs) under `/var/lib/clickhouse/tmp` before startup / chown.

Please let me know if you need any other information. I searched the current / previous issues on github, and the changelog, but didn't find anything related, apologies if I missed something.

**Comment by den-crane** [comment]
Not sure is it helpful or not but you can disable `chown` by setting env var CLICKHOUSE_DO_NOT_CHOWN=1

**Comment by jacobrandall** [comment]
> Not sure is it helpful or not but you can disable `chown` by setting env var CLICKHOUSE_DO_NOT_CHOWN=1

Thanks @den-crane, I have considered setting that but for bootstrapping new clusters still would want that to chown the new volumes. So I'd probably end up doing an initContainer (this is running in Kubernetes) to duplicate what the chown is doing, but perhaps check for a `chown.done` file before the chown that is touched after the very first time a chown is done (perhaps even per directory) but prefer to keep things as simple and straight from the base ClickHouse docker image if possible. Whenever we upgrade versions we'd need to be very careful comparing the `/entrypoint.sh` script to confirm what changed and push updates if needed to the script run by the initContainer.

There's still the issue that eventually I'll run out of inodes (yes it will be a while before that happens) and curious what action should be taken in that situation.

**Comment by alexey-milovidov** [comment]
Yes, we see giant number of empty directories in our production servers.
@den-crane found that it is related to https://github.com/ClickHouse/ClickHouse/pull/15639

**Comment by den-crane** [comment]
@amosbird I don't understand did you solve it in https://github.com/ClickHouse/ClickHouse/pull/28299 or not ?

**Comment by amosbird** [comment]
> @amosbird I don't understand did you solve it in #28299 or not ?

It's solved.

**Comment by alexey-milovidov** [comment]
Ok, we will backport change.

**Comment by filimonov** [comment]
Should we also run some cleanup (lot of tmp folders may be there from older versions)

**Comment by alexey-milovidov** [comment]
I'd better not doing it automatically.
