### ISSUE TITLE
Is it possible to search by ALL columns? 

### ISSUE THREAD

**Issue by alter** [ClickHouse/ClickHouse#26478]
Hello,

I have data in millions of columns(I hope I will be able to create so many columns in clickhouse).
And these data will contain only specific strings: 'true', 'false', 'none'.
How it is possible to find all rows with 'true' and 'false' values in all columns?

**Comment by alexey-milovidov** [comment]
No, you cannot create a table with million columns.

**Comment by UnamedRus** [comment]
You could look into roaringBitMap data type.

```
┌─res─┬─toTypeName(bitmapBuild([1, 2, 3, 4, 5]))─────┐
│     │ AggregateFunction(groupBitmap, UInt8)        │
└─────┴──────────────────────────────────────────────┘
```
https://clickhouse.tech/docs/en/sql-reference/functions/bitmap-functions/
