### ISSUE TITLE
Your DNS server cannot perform requests in some cases.

### ISSUE THREAD

**Issue by Sallery-X** [ClickHouse/ClickHouse#26489]
Your DNS server cannot perform requests in some cases.

_Originally posted by @alexey-milovidov in https://github.com/ClickHouse/ClickHouse/issues/26333#issuecomment-880388637_

**Comment by Sallery-X** [comment]
Manual resolution is normal
![009DDFBF82C4B6FDE41980BB6E0BF30A](https://user-images.githubusercontent.com/45587738/126113535-95fabd12-f4a9-4a2e-b703-04e4a9fcbc20.png)
But sometime fail,i am confuzed
![image](https://user-images.githubusercontent.com/45587738/126113741-b6ebaad2-7f32-4f1f-9c62-360c857e1109.png)

**Comment by filimonov** [comment]
"Temporary failure in name resolution". 

The word **temporary** means that the problem may go away in the next retry (also when you do manual retry). 

https://stackoverflow.com/questions/56188537/getaddrinfo-temporary-failure-in-name-resolution-kubernetes-coredns
https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/

etc.

**Comment by xuxianzhang** [comment]
> "Temporary failure in name resolution".
> 
> The word **temporary** means that the problem may go away in the next retry (also when you do manual retry).
> 
> https://stackoverflow.com/questions/56188537/getaddrinfo-temporary-failure-in-name-resolution-kubernetes-coredns
> https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/
> 
> etc.

i think you misunderstand. this problem not occur searching address by hostname but searching hostname by address when calls DNSResolver::reverseResolve in kubernetes. It's not clear why,and there is no packet on the container's virtual network interface. so i suggest him enable internal dns cache
