### ISSUE TITLE
Clickhouse performs poorly when doing group by queries on high cardinality columns.

### ISSUE THREAD

**Issue by wallace-clickhouse** [ClickHouse/ClickHouse#26495]
**Describe the situation**
When I submit a query ,for example "select person,sum(salary) from popularity group by person",as person is a high cardinality column,the query runs very slow during "<Trace> Aggregator: Merging aggregated data" processing which comes from the query plan.

**How to reproduce**
I use ClickHouse-20.3,2,1_stable
CREATE TABLE statement is as follows:
create table popularity (person String,salary Float32) ENGINE MergeTree() ORDER BY person  SETTINGS index_granularity=8192;
the amount of data in my table is about 100 million.

**Expected performance**
I think clickhouse should be very good at single-table queries, especially for aggregate queries that can take milliseconds of query time, but to my surprise, clickhouse's query performance is clearly unsatisfactory in scenarios where grouping conditions contain high cardinality columns.

**Additional context**
Can you give me some advise to optimize the performance under such scenarios,or any optimization planned in futural versions?

**Comment by alexey-milovidov** [comment]
> I use ClickHouse-20.3,2,1_stable

Update to the latest version 21.7.

**Comment by den-crane** [comment]
@wallace-clickhouse 
>the amount of data in my table is about 100 million.

Do you mean 100 million uniq person? It's not that easy task. Especially for String type, because CH uses 128 bit hashes.
Please share `select uniq(person) from popularity`


Test with numeric 64bit 
```sql
create table popularity (person String,salary Float32) 
ENGINE MergeTree() ORDER BY person;

insert into popularity select toString(number), 0 from numbers(100000000);

select person,sum(salary) from popularity group by person format Null;
Elapsed: 5.092 sec. Processed 100.00 million rows

set optimize_aggregation_in_order=1;
select person,sum(salary) from popularity group by person format Null;
Elapsed: 13.957 sec. Processed 100.00 million rows
```

**Comment by wallace-clickhouse** [comment]
@alexey-milovidov 
ok,I will try,and can you give me some further infomation about the optimization in version 21.7 for the scenario I mentioned above?
Thank you!

**Comment by wallace-clickhouse** [comment]
@den-crane
Yes,_select uniq(person) from popularity_ is 100 million，I find that the query time continues to increase as the grouping column cardinality increases.
_optimize_aggregation_in_order_  from which version this parameter is supported?It seems that the parameter is not supported in 20.3.2.1. Is there any other parameters or ways to optimize the query performance under this situation.
Thank you very much!

**Comment by den-crane** [comment]
@wallace-clickhouse why do you expect that 100 mil aggregation will finish instantly? 
What execution time do you observe? 
Why do you use outdated CH?

**Comment by wallace-clickhouse** [comment]
@den-crane I think clickhouse is very good at querying single table,especially under aggregating scenario.So I think maybe clickhouse can process such query in 1~2 seconds.I observe the elapsed time during query execution.I have already planned to upgrade CH version to the latest.
Thank you!

**Comment by l1t1** [comment]
similar as
https://github.com/ClickHouse/ClickHouse/issues/26666

**Comment by den-crane** [comment]
> @den-crane I think clickhouse is very good at querying single table,especially under aggregating scenario.So I think maybe clickhouse can process such query in 1~2 seconds.I observe the elapsed time during query execution.I have already planned to upgrade CH version to the latest.
> Thank you!

All of this is not true.

**Comment by den-crane** [comment]
Even to return 100 millions as a result takes 2 seconds. I don't see how it's possible to make group by 100 mil. rows in milliseconds. Show another tool / database which can do it faster on a single machine.
