### ISSUE TITLE
MongoDB engine can return null value when  some record lack of property in mongo collection?

### ISSUE THREAD

**Issue by etdick** [ClickHouse/ClickHouse#26490]
How to reproduce：
1.docker image : clickhouse-server : 21.6.8.62
2.CREATE TABLE statements for all tables involved
CREATE TABLE IF NOT EXISTS mongo_table
(
_id UInt64,
updated_time DateTime,
account Nullable(String)
)
ENGINE = MongoDB(':', '<DB_NAME>', '<COLLECTION_NAME>', '', '')

3.Queries to run that lead to unexpected result

select * from mongo_table
Received exception from server (version 21.6.8):
Code: 10. DB::Exception: Received from localhost:9000. DB::Exception: Column account is absent in MongoDB collection: While executing SourceFromInputStream.

i found some record have no "account " in mongodb collection . i epxect null value when some record have no "account "

**Comment by alexey-milovidov** [comment]
Yes, it will be good to have this behaviour.
