### ISSUE TITLE
[PART AND PARTITION] Would all the parts of one partition be merged into a single part finally? 

### ISSUE THREAD

**Issue by mo-avatar** [ClickHouse/ClickHouse#26493]
We are trying to use  clickhouse-local to do pre-computing of part。 

As we all know，one partition has many parts， but will all the parts in one partition be merged into one part finally？

If they will  be merged into one part some how,  will single execution of  "OPTIMIZE TABLE [db.]name [ON CLUSTER cluster] [PARTITION partition | PARTITION ID 'partition_id'] [FINAL]" command give the final result ?

Thx!

**Comment by den-crane** [comment]
Merges are eventual and may never happen. 
It depends on the number of inserts that happened after, the number of parts in the partition, size of parts.
If the total size of input parts are greater than the maximum part size then they will never be merged.

OPTIMIZE ... FINAL tries to merge all part into a single part if it has enough resources in a merge pool (free disk space) without noting maximum part size limit.

**Comment by mo-avatar** [comment]
@den-crane Thanks a lot，after reading your reply，I re-read the related code, and find function like this:
UInt64 MergeTreeDataMergerMutator::getMaxSourcePartsSizeForMerge(size_t pool_size, size_t pool_used) const
{
    if (pool_used > pool_size)
        throw Exception("Logical error: invalid arguments passed to getMaxSourcePartsSize: pool_used > pool_size", ErrorCodes::LOGICAL_ERROR);

    size_t free_entries = pool_size - pool_used;
    const auto data_settings = data.getSettings();

    /// Always allow maximum size if one or less pool entries is busy.
    /// One entry is probably the entry where this function is executed.
    /// This will protect from bad settings.
    UInt64 max_size = 0;
    if (pool_used <= 1 || free_entries >= data_settings->number_of_free_entries_in_pool_to_lower_max_size_of_merge)
        max_size = data_settings->max_bytes_to_merge_at_max_space_in_pool;
    else
        max_size = interpolateExponential(
            data_settings->max_bytes_to_merge_at_min_space_in_pool,
            data_settings->max_bytes_to_merge_at_max_space_in_pool,
            static_cast<double>(free_entries) / data_settings->number_of_free_entries_in_pool_to_lower_max_size_of_merge);

    return std::min(max_size, static_cast<UInt64>(data.getStoragePolicy()->getMaxUnreservedFreeSpace() / DISK_USAGE_COEFFICIENT_TO_SELECT));
}
Again, thanks for your help!
