### ISSUE TITLE
Single quotes in CSV files are being treated like double quote enclosures

### ISSUE THREAD

**Issue by marklit** [ClickHouse/ClickHouse#26507]
According to https://www.ietf.org/rfc/rfc4180.txt double quotes should be used for field enclosing. ClickHouse appears to treat single quotes the same way. Below will import into MySQL and PostgreSQL but it fails with ClickHouse. The following was tested against 21.7.3.14 (official build).

```bash
$ cat test.csv
```

```
a,b,c
AA123,'Testing this' Ltd,EN
```

```bash
$ clickhouse-client
```

```sql
CREATE TABLE details (
    a String,
    b String,
    c String
) ENGINE = Log;
```

```bash
$ cat test.csv | clickhouse-client --query="INSERT INTO details FORMAT CSVWithNames"
```

```
Code: 27. DB::ParsingException: Cannot parse input: expected ',' before: 'Ltd,EN\n': 
Row 1:
Column 0,   name: a, type: String, parsed text: "AA123"
Column 1,   name: b, type: String, parsed text: "<SINGLE QUOTE>Testing this<SINGLE QUOTE>"
ERROR: There is no delimiter (,). "L" found instead.

: data for INSERT was parsed from stdin: (at row 1)
```

**Comment by den-crane** [comment]
By default CH uses automatic deduce using the first character.

There is a parameters
 --format_csv_allow_single_quotes arg                             If it is set to true, allow strings in single quotes.
--format_csv_allow_double_quotes arg                             If it is set to true, allow strings in double quotes.

So you should use

```
cat test.csv | clickhouse-client --format_csv_allow_single_quotes=0 --query="INSERT INTO details FORMAT CSVWithNames"
```
