### ISSUE TITLE
Remove 'delete_tmp_' directories on server start-up

### ISSUE THREAD

**Issue by abyss7** [ClickHouse/ClickHouse#26503]
For some reasons when we delete a MergeTree Part in atomic way something may go wrong - and leave the `delete_tmp_*` folder or it's part on disk. This may lead to a disk space consumption over time.

It's suggested to delete this folders at least at server start-up. Current solution with `clearOldTemporaryDirectories()` doesn't work because this method is called periodically from a thread without any locks or advisory on folders - it may cause the race conditions.

**Comment by alesapin** [comment]
Fixed long time ago.
