### ISSUE TITLE
Is it possible to change the database engine?

### ISSUE THREAD

**Issue by Alekky09** [ClickHouse/ClickHouse#26519]
I can't find anything about this in the docs. Is it possible to change the database engine after the database was already created?

**Comment by alexey-milovidov** [comment]
No, it's not possible.

It is possible to move (RENAME) tables between databases with Ordinary and Atomic engines.

**Comment by den-crane** [comment]
https://kb.altinity.com/engines/altinity-kb-atomic-database-engine/altinity-kb-how-to-convert-atomic-to-ordinary
