### ISSUE TITLE
difference between truncate table default.SampleTable vs delete /var/lib/clickhouse/data/default/SampleTable

### ISSUE THREAD

**Issue by q0987** [ClickHouse/ClickHouse#26528]
Hello all,

To remove all data from a table(i.e.  default.SampleTable),

```
truncate table default.SampleTable;

rm -fr /var/lib/clickhouse/data/default/SampleTable/*
```

Is there any difference between the above two operations?

Thank you

**Comment by alexey-milovidov** [comment]
Second operation is illegal - server will be unaware that the files are gone.
It works only for very basic table engines: Log, TinyLog, StripeLog.
If you do this for MergeTree, server will throw exception on next query and you will have to restart server to apply changes.
If you do this for ReplicatedMergeTree, server will notice that the data is gone and repair itself from replica.

**Comment by q0987** [comment]
I only do the second operation while I turn off the clickhouse-server. The main reason I need to do this is to transfer some data from one machine to another machine so I don't have to import all data again.

Thank you

**Comment by alexey-milovidov** [comment]
Yes, you can manually move data between offline servers - it is legal :)
And to online server as well (with moving to detached directory and ATTACH PART queries).
