### ISSUE TITLE
Assertion failure writing to kafka

### ISSUE THREAD

**Issue by ilejn** [ClickHouse/ClickHouse#26547]
You have to provide the following information whenever possible.

**Describe the bug**

Any attempt to insert into a table with engine Kafka (e.g. test_kafka_insert from integration test) causes assertion failure.

**Does it reproduce on recent release?**

I am playing with recent master c255f152aa4e50933bf

**Error message and/or stacktrace**

2021.07.19 23:31:48.695409 [ 1592186 ] {2d87e4e5-4795-4c31-ac04-2ec059dbabc5} <Debug> MemoryTracker: Peak memory usage (for query): 0.00 B.
clickhouse: /home/ilejn/projects/ClickHouse/src/Storages/Kafka/WriteBufferToKafkaProducer.cpp:51: virtual DB::WriteBufferToKafkaProducer::~WriteBufferToKafkaProducer(): Assertion `rows == 0 && chunks.empty()' failed.
2021.07.19 23:31:48.696445 [ 1592136 ] {} <Trace> BaseDaemon: Received signal 6
2021.07.19 23:31:48.697249 [ 1592463 ] {} <Fatal> BaseDaemon: ########################################
2021.07.19 23:31:48.697505 [ 1592463 ] {} <Fatal> BaseDaemon: (version 21.7.1.1, no build id) (from thread 1592186) (query_id: 2d87e4e5-4795-4c31-ac04-2ec059dbabc5) Received signal Aborted (6)
2021.07.19 23:31:48.697648 [ 1592463 ] {} <Fatal> BaseDaemon: 
2021.07.19 23:31:48.697802 [ 1592463 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f8266f12fbb 0x7f8266ef8864 0x7f8266ef8749 0x7f8266f0a3d6 0x146dd808 0x146d89f9 0x146d89bd 0x146d897d 0x146d862e 0x9980c71 0x9980c19 0x146d8b0c 0x1523639b 0x146d4f7a 0x146d4f3d 0x146d4efd 0x146d4cae 0x9980c71 0x9980c19 0x9a9b8ec 0x1478a648 0x1389f75a 0x1389f71d 0x1389f6dd 0x1389f48e 0x9980c71 0x9980c19 0x9a9b8ec 0x147b1588 0x138a03ba 0x138a037d 0x138a033d 0x138a008e 0x9980c71 0x9980c19 0x9a9b8ec 0x1478f85b 0x138a0e7a 0x138a0e3d 0x138a0dfd 0x138a0bce
2021.07.19 23:31:48.698029 [ 1592463 ] {} <Fatal> BaseDaemon: 4. gsignal @ 0x40fbb in /usr/lib/x86_64-linux-gnu/libc-2.33.so
2021.07.19 23:31:48.698113 [ 1592463 ] {} <Fatal> BaseDaemon: 5. abort @ 0x26864 in /usr/lib/x86_64-linux-gnu/libc-2.33.so
2021.07.19 23:31:48.698188 [ 1592463 ] {} <Fatal> BaseDaemon: 6. ? @ 0x26749 in /usr/lib/x86_64-linux-gnu/libc-2.33.so
2021.07.19 23:31:48.698263 [ 1592463 ] {} <Fatal> BaseDaemon: 7. ? @ 0x383d6 in /usr/lib/x86_64-linux-gnu/libc-2.33.so
2021.07.19 23:31:48.824976 [ 1592463 ] {} <Fatal> BaseDaemon: 8. /home/ilejn/projects/ClickHouse/src/Storages/Kafka/WriteBufferToKafkaProducer.cpp:0: DB::WriteBufferToKafkaProducer::~WriteBufferToKafkaProducer() @ 0x146dd808 in /home/ilejn/projects/ClickHouse/build/programs/clickhouse
2021.07.19 23:31:49.466935 [ 1592463 ] {} <Fatal> BaseDaemon: 9. /home/ilejn/projects/ClickHouse/contrib/libcxx/include/memory:892: std::__1::allocator<DB::WriteBufferToKafkaProducer>::destroy(DB::WriteBufferToKafkaProducer*) @ 0x146d89f9 in /home/ilejn/projects/ClickHouse/build/programs/clickhouse
2021.07.19 23:31:50.229230 [ 1592463 ] {} <Fatal> BaseDaemon: 10. /home/ilejn/projects/ClickHouse/contrib/libcxx/include/__memory/allocator_traits.h:541: void std::__1::allocator_traits<std::__1::allocator<DB::WriteBufferToKafkaProducer> >::__destroy<DB::WriteBufferToKafkaProducer>(std::__1::integral_constant<bool, true>, std::__1::allocator<DB::WriteBufferToKafkaProducer>&, DB::WriteBufferToKafkaProducer*) @ 0x146d89bd in /home/ilejn/projects/ClickHouse/build/programs/clickhouse
2021.07.19 23:31:50.877117 [ 1592463 ] {} <Fatal> BaseDaemon: 11. /home/ilejn/projects/ClickHouse/contrib/libcxx/include/__memory/allocator_traits.h:487: void std::__1::allocator_traits<std::__1::allocator<DB::WriteBufferToKafkaProducer> >::destroy<DB::WriteBufferToKafkaProducer>(std::__1::allocator<DB::WriteBufferToKafkaProducer>&, DB::WriteBufferToKafkaProducer*) @ 0x146d897d in /home/ilejn/projects/ClickHouse/build/programs/clickhouse
2021.07.19 23:31:51.536775 [ 1592463 ] {} <Fatal> BaseDaemon: 12. /home/ilejn/projects/ClickHouse/contrib/libcxx/include/memory:2611: std::__1::__shared_ptr_emplace<DB::WriteBufferToKafkaProducer, std::__1::allocator<DB::WriteBufferToKafkaProducer> >::__on_zero_shared() @ 0x146d862e in /home/ilejn/projects/ClickHouse/build/programs/clickhouse
2021.07.19 23:31:51.731367 [ 1592463 ] {} <Fatal> BaseDaemon: 13. /home/ilejn/projects/ClickHouse/contrib/libcxx/include/memory:2476: std::__1::__shared_count::__release_shared() @ 0x9980c71 in /home/ilejn/projects/ClickHouse/build/programs/clickhouse
2021.07.19 23:31:51.909613 [ 1592463 ] {} <Fatal> BaseDaemon: 14. /home/ilejn/projects/ClickHouse/contrib/libcxx/include/memory:2517: std::__1::__shared_weak_count::__release_shared() @ 0x9980c19 in /home/ilejn/projects/ClickHouse/build/programs/clickhouse
2021.07.19 23:31:52.532413 [ 1592463 ] {} <Fatal> BaseDaemon: 15. /home/ilejn/projects/ClickHouse/contrib/libcxx/include/memory:3213: std::__1::shared_ptr<DB::WriteBufferToKafkaProducer>::~shared_ptr() @ 0x146d8b0c in /home/ilejn/projects/ClickHouse/build/programs/clickhouse
2021.07.19 23:31:52.739467 [ 1592463 ] {} <Fatal> BaseDaemon: 16. /home/ilejn/projects/ClickHouse/src/Storages/Kafka/KafkaBlockOutputStream.h:9: DB::KafkaBlockOutputStream::~KafkaBlockOutputStream() @ 0x1523639b in /home/ilejn/projects/ClickHouse/build/programs/clickhouse

**Comment by ilejn** [comment]
I am about to look into some kafka/avro improvement anyway and probably will fix it.
I've created the ticket mainly as a sanity check, to ensure it is not a local issue and I am not doing something stupid.
Attn @filimonov

**Comment by ilejn** [comment]
The left part is true (rows == 0) while chunks is not empty. I've saw that it had size 4 while I do not know if it depends on data or not.

**Comment by ilejn** [comment]
Data is written to kafka Ok, so it is quite possible that integration test is ok for release build.

**Comment by filimonov** [comment]
I never analyzed/tested deeply writing to Kafka. The assert look valid, some unflushed data in the destructor - some race?

**Comment by ilejn** [comment]
I appreciate if someone reproduce it.

**Comment by filimonov** [comment]
Something like writing to kafka table by many threads and simultaneously detach / attach table?

**Comment by ilejn** [comment]
In my case any insert produces this error.
That is why I would like to exclude possibility of a local issue.

**Comment by filimonov** [comment]
> In my case any insert produces this error.
> That is why I would like to exclude possibility of a local issue.

Oh, ok I've misunderstood you. There are some tests for Kafka inserts, and if it would happen always - they would catch it for sure already.

Check that countRow stuff - while the name of the function doesn't seem like something important, while it actually do flushes:
https://github.com/ClickHouse/ClickHouse/blob/47c1bb34163d496a9fe97d1aa4dd73894c4ad5d5/src/Storages/Kafka/WriteBufferToKafkaProducer.cpp#L54

**Comment by ilejn** [comment]
@filimonov  Yes, that is right, integration tests would fail if they run against debug build (or a build with enabled asserts).
Do we do this?
Thanks, I've already looked into countRow while haven't noticed anything suspicious.

**Comment by alexey-milovidov** [comment]
```
Mikhail Filimonov, [11.08.21 20:34]
[In reply to Alexey Milovidov]
А это что-то непонятное. Я надеялся что Илья с этим сам разберётся...
```

**Comment by ilejn** [comment]
I cannot reproduce the issue in fresh Ubuntu 20.04. In this environment kafka integration test runs smoothly against debug build. 
Trying to optimize writing data to kafka anyway, so it might be that I'll sort this issue out.
I suggest closing the ticket.

**Comment by qoega** [comment]
assert:
```
clickhouse: ../src/Storages/Kafka/WriteBufferToKafkaProducer.cpp:51: virtual DB::WriteBufferToKafkaProducer::~WriteBufferToKafkaProducer(): Assertion `rows == 0 && chunks.empty()' failed.
```

```
2021.08.17 11:28:17.929547 [ 416 ] {} <Fatal> BaseDaemon: ########################################
2021.08.17 11:28:17.929684 [ 416 ] {} <Fatal> BaseDaemon: (version 21.9.1.7770, build id: 5E67AC29E8CD1631D48C72C12BF9DB5D97D5807B) (from thread 11) (query_id: a2fb5031-5c4d-4156-b245-c768bc00ea3f) Received signal Aborted (6)
2021.08.17 11:28:17.929781 [ 416 ] {} <Fatal> BaseDaemon:
2021.08.17 11:28:17.929941 [ 416 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f02fedb518b 0x7f02fed94859 0x7f02fed94729 0x7f02feda5f36 0x1f2333ad 0x1f1dde3c 0x1f1dddfd 0x1f1dddbd 0x1f1dda35 0x1348c8bd 0x1348c85f 0x1f1ddf8c 0x1f23634a 0x1f1d9fbd 0x1f1d9f7d 0x1f1d9f3d 0x1f1d9cf5 0x1348c8bd 0x1348c85f 0x1db2dc2c 0x1e62a76a 0x1e62a9bd 0x1e62a97d 0x1e62a93d 0x1e628f75 0x1348c8bd 0x1348c85f 0x135e7eac 0x1e63101c 0x1e62d15d 0x1e62d11d 0x1e62d0dd 0x1e62ce55 0x1348c8bd 0x1348c85f 0x135e7eac 0x1e63091c 0x1e62de5d 0x1e62de1d 0x1e62dddd 0x1e62db15
2021.08.17 11:28:17.930208 [ 416 ] {} <Fatal> BaseDaemon: 4. gsignal @ 0x4618b in /usr/lib/x86_64-linux-gnu/libc-2.31.so
2021.08.17 11:28:17.930293 [ 416 ] {} <Fatal> BaseDaemon: 5. abort @ 0x25859 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
2021.08.17 11:28:17.930359 [ 416 ] {} <Fatal> BaseDaemon: 6. ? @ 0x25729 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
2021.08.17 11:28:17.930425 [ 416 ] {} <Fatal> BaseDaemon: 7. ? @ 0x36f36 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
2021.08.17 11:28:18.025499 [ 416 ] {} <Fatal> BaseDaemon: 8. ./obj-x86_64-linux-gnu/../src/Storages/Kafka/WriteBufferToKafkaProducer.cpp:0: DB::WriteBufferToKafkaProducer::~WriteBufferToKafkaProducer() @ 0x1f2333ad in /usr/bin/clickhouse
2021.08.17 11:28:18.629941 [ 416 ] {} <Fatal> BaseDaemon: 9. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:892: std::__1::allocator<DB::WriteBufferToKafkaProducer>::destroy(DB::WriteBufferToKafkaProducer*) @ 0x1f1dde3c in /usr/bin/clickhouse
2021.08.17 11:28:19.228353 [ 416 ] {} <Fatal> BaseDaemon: 10. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/__memory/allocator_traits.h:541: void std::__1::allocator_traits<std::__1::allocator<DB::WriteBufferToKafkaProducer> >::__destroy<DB::WriteBufferToKafkaProducer>(std::__1::integral_constant<bool, true>, std::__1::allocator<DB::WriteBufferToKafkaProducer>&, DB::WriteBufferToKafkaProducer*) @ 0x1f1dddfd in /usr/bin/clickhouse
2021.08.17 11:28:19.851241 [ 416 ] {} <Fatal> BaseDaemon: 11. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/__memory/allocator_traits.h:487: void std::__1::allocator_traits<std::__1::allocator<DB::WriteBufferToKafkaProducer> >::destroy<DB::WriteBufferToKafkaProducer>(std::__1::allocator<DB::WriteBufferToKafkaProducer>&, DB::WriteBufferToKafkaProducer*) @ 0x1f1dddbd in /usr/bin/clickhouse
2021.08.17 11:28:20.504452 [ 416 ] {} <Fatal> BaseDaemon: 12. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2611: std::__1::__shared_ptr_emplace<DB::WriteBufferToKafkaProducer, std::__1::allocator<DB::WriteBufferToKafkaProducer> >::__on_zero_shared() @ 0x1f1dda35 in /usr/bin/clickhouse
2021.08.17 11:28:20.662621 [ 416 ] {} <Fatal> BaseDaemon: 13. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2476: std::__1::__shared_count::__release_shared() @ 0x1348c8bd in /usr/bin/clickhouse
2021.08.17 11:28:20.819109 [ 416 ] {} <Fatal> BaseDaemon: 14. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2517: std::__1::__shared_weak_count::__release_shared() @ 0x1348c85f in /usr/bin/clickhouse
2021.08.17 11:28:21.423917 [ 416 ] {} <Fatal> BaseDaemon: 15. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:3213: std::__1::shared_ptr<DB::WriteBufferToKafkaProducer>::~shared_ptr() @ 0x1f1ddf8c in /usr/bin/clickhouse
2021.08.17 11:28:21.630927 [ 416 ] {} <Fatal> BaseDaemon: 16. ./obj-x86_64-linux-gnu/../src/Storages/Kafka/KafkaBlockOutputStream.h:9: DB::KafkaSink::~KafkaSink() @ 0x1f23634a in /usr/bin/clickhouse
2021.08.17 11:28:22.221898 [ 416 ] {} <Fatal> BaseDaemon: 17. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:892: std::__1::allocator<DB::KafkaSink>::destroy(DB::KafkaSink*) @ 0x1f1d9fbd in /usr/bin/clickhouse
2021.08.17 11:28:22.826278 [ 416 ] {} <Fatal> BaseDaemon: 18. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/__memory/allocator_traits.h:541: void std::__1::allocator_traits<std::__1::allocator<DB::KafkaSink> >::__destroy<DB::KafkaSink>(std::__1::integral_constant<bool, true>, std::__1::allocator<DB::KafkaSink>&, DB::KafkaSink*) @ 0x1f1d9f7d in /usr/bin/clickhouse
2021.08.17 11:28:23.442636 [ 416 ] {} <Fatal> BaseDaemon: 19. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/__memory/allocator_traits.h:487: void std::__1::allocator_traits<std::__1::allocator<DB::KafkaSink> >::destroy<DB::KafkaSink>(std::__1::allocator<DB::KafkaSink>&, DB::KafkaSink*) @ 0x1f1d9f3d in /usr/bin/clickhouse
2021.08.17 11:28:24.050635 [ 416 ] {} <Fatal> BaseDaemon: 20. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2611: std::__1::__shared_ptr_emplace<DB::KafkaSink, std::__1::allocator<DB::KafkaSink> >::__on_zero_shared() @ 0x1f1d9cf5 in /usr/bin/clickhouse
2021.08.17 11:28:24.207407 [ 416 ] {} <Fatal> BaseDaemon: 21. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2476: std::__1::__shared_count::__release_shared() @ 0x1348c8bd in /usr/bin/clickhouse
2021.08.17 11:28:24.362245 [ 416 ] {} <Fatal> BaseDaemon: 22. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2517: std::__1::__shared_weak_count::__release_shared() @ 0x1348c85f in /usr/bin/clickhouse
2021.08.17 11:28:24.730954 [ 416 ] {} <Fatal> BaseDaemon: 23. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:3213: std::__1::shared_ptr<DB::SinkToStorage>::~shared_ptr() @ 0x1db2dc2c in /usr/bin/clickhouse
2021.08.17 11:28:25.300617 [ 416 ] {} <Fatal> BaseDaemon: 24. ./obj-x86_64-linux-gnu/../src/DataStreams/PushingToSinkBlockOutputStream.h:13: DB::PushingToSinkBlockOutputStream::~PushingToSinkBlockOutputStream() @ 0x1e62a76a in /usr/bin/clickhouse
2021.08.17 11:28:25.872628 [ 416 ] {} <Fatal> BaseDaemon: 25. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:892: std::__1::allocator<DB::PushingToSinkBlockOutputStream>::destroy(DB::PushingToSinkBlockOutputStream*) @ 0x1e62a9bd in /usr/bin/clickhouse
2021.08.17 11:28:26.438413 [ 416 ] {} <Fatal> BaseDaemon: 26. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/__memory/allocator_traits.h:541: void std::__1::allocator_traits<std::__1::allocator<DB::PushingToSinkBlockOutputStream> >::__destroy<DB::PushingToSinkBlockOutputStream>(std::__1::integral_constant<bool, true>, std::__1::allocator<DB::PushingToSinkBlockOutputStream>&, DB::PushingToSinkBlockOutputStream*) @ 0x1e62a97d in /usr/bin/clickhouse
2021.08.17 11:28:27.015948 [ 416 ] {} <Fatal> BaseDaemon: 27. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/__memory/allocator_traits.h:487: void std::__1::allocator_traits<std::__1::allocator<DB::PushingToSinkBlockOutputStream> >::destroy<DB::PushingToSinkBlockOutputStream>(std::__1::allocator<DB::PushingToSinkBlockOutputStream>&, DB::PushingToSinkBlockOutputStream*) @ 0x1e62a93d in /usr/bin/clickhouse
2021.08.17 11:28:27.675700 [ 416 ] {} <Fatal> BaseDaemon: 28. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2611: std::__1::__shared_ptr_emplace<DB::PushingToSinkBlockOutputStream, std::__1::allocator<DB::PushingToSinkBlockOutputStream> >::__on_zero_shared() @ 0x1e628f75 in /usr/bin/clickhouse
2021.08.17 11:28:27.828301 [ 416 ] {} <Fatal> BaseDaemon: 29. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2476: std::__1::__shared_count::__release_shared() @ 0x1348c8bd in /usr/bin/clickhouse
2021.08.17 11:28:27.979724 [ 416 ] {} <Fatal> BaseDaemon: 30. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2517: std::__1::__shared_weak_count::__release_shared() @ 0x1348c85f in /usr/bin/clickhouse
2021.08.17 11:28:28.477687 [ 416 ] {} <Fatal> BaseDaemon: 31. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:3213: std::__1::shared_ptr<DB::IBlockOutputStream>::~shared_ptr() @ 0x135e7eac in /usr/bin/clickhouse
2021.08.17 11:28:28.627734 [ 416 ] {} <Fatal> BaseDaemon: 32. ./obj-x86_64-linux-gnu/../src/DataStreams/AddingDefaultBlockOutputStream.h:23: DB::AddingDefaultBlockOutputStream::~AddingDefaultBlockOutputStream() @ 0x1e63101c in /usr/bin/clickhouse
2021.08.17 11:28:29.200986 [ 416 ] {} <Fatal> BaseDaemon: 33. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:892: std::__1::allocator<DB::AddingDefaultBlockOutputStream>::destroy(DB::AddingDefaultBlockOutputStream*) @ 0x1e62d15d in /usr/bin/clickhouse
2021.08.17 11:28:29.781333 [ 416 ] {} <Fatal> BaseDaemon: 34. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/__memory/allocator_traits.h:541: void std::__1::allocator_traits<std::__1::allocator<DB::AddingDefaultBlockOutputStream> >::__destroy<DB::AddingDefaultBlockOutputStream>(std::__1::integral_constant<bool, true>, std::__1::allocator<DB::AddingDefaultBlockOutputStream>&, DB::AddingDefaultBlockOutputStream*) @ 0x1e62d11d in /usr/bin/clickhouse
2021.08.17 11:28:30.372169 [ 416 ] {} <Fatal> BaseDaemon: 35. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/__memory/allocator_traits.h:487: void std::__1::allocator_traits<std::__1::allocator<DB::AddingDefaultBlockOutputStream> >::destroy<DB::AddingDefaultBlockOutputStream>(std::__1::allocator<DB::AddingDefaultBlockOutputStream>&, DB::AddingDefaultBlockOutputStream*) @ 0x1e62d0dd in /usr/bin/clickhouse
2021.08.17 11:28:30.946100 [ 416 ] {} <Fatal> BaseDaemon: 36. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2611: std::__1::__shared_ptr_emplace<DB::AddingDefaultBlockOutputStream, std::__1::allocator<DB::AddingDefaultBlockOutputStream> >::__on_zero_shared() @ 0x1e62ce55 in /usr/bin/clickhouse
2021.08.17 11:28:31.101233 [ 416 ] {} <Fatal> BaseDaemon: 37. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2476: std::__1::__shared_count::__release_shared() @ 0x1348c8bd in /usr/bin/clickhouse
2021.08.17 11:28:31.252475 [ 416 ] {} <Fatal> BaseDaemon: 38. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2517: std::__1::__shared_weak_count::__release_shared() @ 0x1348c85f in /usr/bin/clickhouse
2021.08.17 11:28:31.754575 [ 416 ] {} <Fatal> BaseDaemon: 39. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:3213: std::__1::shared_ptr<DB::IBlockOutputStream>::~shared_ptr() @ 0x135e7eac in /usr/bin/clickhouse
2021.08.17 11:28:31.833033 [ 416 ] {} <Fatal> BaseDaemon: 40. ./obj-x86_64-linux-gnu/../src/DataStreams/SquashingBlockOutputStream.h:12: DB::SquashingBlockOutputStream::~SquashingBlockOutputStream() @ 0x1e63091c in /usr/bin/clickhouse
2021.08.17 11:28:32.413012 [ 416 ] {} <Fatal> BaseDaemon: 41. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:892: std::__1::allocator<DB::SquashingBlockOutputStream>::destroy(DB::SquashingBlockOutputStream*) @ 0x1e62de5d in /usr/bin/clickhouse
2021.08.17 11:28:32.979225 [ 416 ] {} <Fatal> BaseDaemon: 42. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/__memory/allocator_traits.h:541: void std::__1::allocator_traits<std::__1::allocator<DB::SquashingBlockOutputStream> >::__destroy<DB::SquashingBlockOutputStream>(std::__1::integral_constant<bool, true>, std::__1::allocator<DB::SquashingBlockOutputStream>&, DB::SquashingBlockOutputStream*) @ 0x1e62de1d in /usr/bin/clickhouse
2021.08.17 11:28:33.556477 [ 416 ] {} <Fatal> BaseDaemon: 43. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/__memory/allocator_traits.h:487: void std::__1::allocator_traits<std::__1::allocator<DB::SquashingBlockOutputStream> >::destroy<DB::SquashingBlockOutputStream>(std::__1::allocator<DB::SquashingBlockOutputStream>&, DB::SquashingBlockOutputStream*) @ 0x1e62dddd in /usr/bin/clickhouse
2021.08.17 11:28:34.129907 [ 416 ] {} <Fatal> BaseDaemon: 44. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2611: std::__1::__shared_ptr_emplace<DB::SquashingBlockOutputStream, std::__1::allocator<DB::SquashingBlockOutputStream> >::__on_zero_shared() @ 0x1e62db15 in /usr/bin/clickhouse
2021.08.17 11:28:35.147729 [ 416 ] {} <Fatal> BaseDaemon: Calculated checksum of the binary: 2C15539E15A8F987B1C8673B7346AA05. There is no information about the reference checksum.
2021.08.17 11:28:42.061401 [ 1 ] {} <Fatal> Application: Child process was terminated by signal 6.
```

I reproduce it with build from master 2818f79326c0cb65c9985f7fc9b1de8daa5fb417 
In my case this is sufficient to trigger an assert
``` sh
~/clickhouse/docker/packager/packager --compiler clang-11 --package-type deb --output-dir ~/debug-ch/output/ --clickhouse-repo-path /home/qoega/clickhouse --ccache_dir ~/docker-ch/local_ccache/ --cache ccache --build-type debug --with-binaries programs | tee ~/packager.log
./runner -n 10 --src-dir /home/qoega/clickhouse/src --binary /home/qoega/debug-ch/output/binary/clickhouse --odbc-bridge-binary /home/qoega/debug-ch/output/binary/clickhouse-odbc-bridge --library-bridge-binary /home/qoega/debug-ch/output/binary/clickhouse-library-bridge --cleanup-containers --command bash
pytest -x -k kafka
```

**Comment by ilejn** [comment]
@qoega is there anything special about your environment?
In my case problem appeared in ubuntu 21.04, but not in 20.04.

**Comment by qoega** [comment]
I use docker environment and it should be completely reproducible. I guess my local environment is not related(it is also Ubuntu 20.04 if I remember correctly).

**Comment by qoega** [comment]
I was able to reproduce it using a single test scenario also inside docker:
```
pytest -x test_storage_kafka --count 100 -k test_kafka_protobuf_no_delimiter
```

**Comment by filimonov** [comment]
Hm. Actually, I don't understand how that assertion may NOT trigger...

It seems like after https://github.com/ClickHouse/ClickHouse/pull/19886 condition `chunks.empty()` is always false. 

@azat ?
