### ISSUE TITLE
> "Temporary failure in name resolution".

### ISSUE THREAD

**Issue by Sallery-X** [ClickHouse/ClickHouse#26546]
> "Temporary failure in name resolution".
> 
> The word **temporary** means that the problem may go away in the next retry (also when you do manual retry).
> 
> https://stackoverflow.com/questions/56188537/getaddrinfo-temporary-failure-in-name-resolution-kubernetes-coredns
> https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/
> 
> etc.

i think you misunderstand. this problem not occur searching address by hostname but searching hostname by address when calls DNSResolver::reverseResolve in kubernetes. It's not clear why,and there is no packet on the container's virtual network interface. so i suggest him enable internal dns cache

_Originally posted by @xuxianzhang in https://github.com/ClickHouse/ClickHouse/issues/26489#issuecomment-882526250_

**Comment by filimonov** [comment]
It's not clear to me how we can help you. What are your expectations from ClickHouse when `getnameinfo` (OS call) returns "Temporary failure in name resolution"?

**Comment by abyss7** [comment]
Please, fill out the task description properly - so everyone can understand an issue.

**Comment by Sallery-X** [comment]
> It's not clear to me how we can help you. What are your expectations from ClickHouse when `getnameinfo` (OS call) returns "Temporary failure in name resolution"?

Just retry about 3 times?
