### ISSUE TITLE
Newly inserted rows are not reflected in the table.

### ISSUE THREAD

**Issue by moweonlee** [ClickHouse/ClickHouse#26542]
- Symptom

Writing rows into the clickhouse at rate 15,901/seconds

1.  In the middle of writing rows into CH ( usually when insert rate is increased ) , a counting query which is "SELECT count(1) from table"  doesn't show newly added rows 

```
SELECT
    hour,
    count(1)
FROM dnclicks_stms_array_basic_20210720
WHERE date = '2021-07-20'
GROUP BY hour
ORDER BY hour ASC

Query id: 07e66508-16b6-4580-aae3-3484e790052b

┌─hour─┬─count(1)─┐
│    0 │ 57244602 │
│    1 │ 46961453 │
│    2 │ 36522543 │
│    3 │ 28088084 │
│    4 │ 24206314 │
│    5 │ 27615161 │
│    6 │ 40149078 │
│    7 │ 41273176 │
│    8 │ 24156579 │
│    9 │  8926306 │
└──────┴──────────┘

```

2.  we stopped Flink to stop insert. 

3. A number of rows in table are still keep changing even Insertion is totally stopped. ( increasing, decreasing  ) 

4. After couple of hours, rows begin to appear little by little. ( they are rows which are inserted before Flink killed ). 

- Clickhouse version 
```
Connected to ClickHouse server version 21.2.5 revision 54447.
```
- Clickhouse cluster setup 
  - Flink is writing data into clickhouse ( Time window fired in every 10 seconds )
  - Using Flink-to-clickhouse sink : https://github.com/ivi-ru/flink-clickhouse-sink
  - Using 8 nodes for ring topology replicated mergeTree and its distributed table
  - Intel(R) Xeon(R) Silver 4214 CPU @ 2.20GHz
  - 64GBytes RAM

**Comment by den-crane** [comment]
>dnclicks_stms_array_basic_20210720

is it distributed table?

**Comment by moweonlee** [comment]
@den-crane 

Yes dnclicks_stms_array_basic_20210720 is distributed table .

**Comment by moweonlee** [comment]
What I have figured out is that the main reason of this delayed write came from frequent writing in Flink output. 

No delay has been reproduced after changing clickhouse.sink.time-sec 5->10 seconds.

As I know "clickhouse.sink.time-sec" define how long data which is to be written can stay in the buffer waiting to be bulk writing.

But several times I have done some practical tests to find out which values are suitable for my volume.

So I guess if clickhouse have some features or plans to support buffered write which is designed to convert frequent and small writes into big bulk mode.

@den-crane 

Thank you Den.

--- 

Reference : https://github.com/ivi-ru/flink-clickhouse-sink
```
clickhouse.sink.timeout-sec - timeout for loading data,
```

**Comment by alexey-milovidov** [comment]
> So I guess if clickhouse have some features or plans to support buffered write which is designed to convert frequent and small writes into big bulk mode.

Yes, https://github.com/ClickHouse/ClickHouse/issues/18282
