### ISSUE TITLE
Failed to use mysql engine when creating database with mysql engine

### ISSUE THREAD

**Issue by prudens** [ClickHouse/ClickHouse#26544]
clickhouse's version: 20.8.3.
when i type the sql statment:
**_create database  test ENGINE = MYSQL('172.16.0.55:3306','test','root','passw0rd');_**
but response message:
_**Received exception from server (version 20.8.3):
Code: 36. DB::Exception: Received from 127.0.0.1:9000. DB::Exception: Database engine MYSQL cannot have arguments. 
0 rows in set. Elapsed: 0.006 sec.**_ 

so what happened about this?

**Comment by abyss7** [comment]
The engine name is case-sensitive: we have engine `MySQL`, but not `MYSQL`. The error message is misleading in this way. Try and report, if it helps.

**Comment by prudens** [comment]
> The engine name is case-sensitive: we have engine `MySQL`, but not `MYSQL`. The error message is misleading in this way. Try and report, if it helps.

yes，rename the engine name as MySQL，it work well！thank you.
