### ISSUE TITLE
Memory tracking issue in groupBitmapState ?

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#26555]
That query uses about 10Gb of RAM, should fail with that setting.
In practice it can go OOM, and clickhouse memory tracker doesn't know about that:

```
SET max_threads = 8, max_memory_usage = '3G';
CREATE TABLE oom_issue ENGINE = AggregatingMergeTree ORDER BY n AS　SELECT cityHash64(rand() % 1000) as n, groupBitmapState(number) FROM numbers_mt(2000000000) GROUP BY n;
```

```
[laptop-5591] 2021.07.20 13:22:45.739115 [ 272424 ] {cda8ab45-5c7c-47de-83eb-14ec6d0fdb4c} <Debug> MemoryTracker: Peak memory usage (for query): 6.53 MiB.
```

**Comment by amosbird** [comment]
It's likely because CRoaring is a C library. Perhaps we need to do memory tracking over malloc.

**Comment by alexey-milovidov** [comment]
We can add a setting `allow_roaring_bitmap` to prevent usage of these functions if memory consumption for arbitrary queries has to be enforced. Not the best solution, though.
