### ISSUE TITLE
UInt64 bitmap operations performance decreased dramatically

### ISSUE THREAD

**Issue by maehrlae** [ClickHouse/ClickHouse#26553]
**Describe the situation**
Coming from version 20.8.11.17 the performance of operations using bitmaps with datatype UInt64 decreased  after we upgraded to the current LTS version 21.3.14.1. The problem is also included in the current stable version.

Example times from our applicataion:

Clickhouse 20.8.11.17 

```sql
CREATE TABLE vv1
ENGINE = Memory AS
SELECT groupBitmapState(cityHash64(POSITION_ID)) AS r
FROM POSITION_I
WHERE (FIELDNAME = 'PTY001') AND (VALUE = 1)

Ok.

0 rows in set. Elapsed: 2.986 sec. Processed 40.63 million rows, 2.41 GB (13.61 million rows/s., 805.86 MB/s.)
```
compared to Clickhouse 21.3.14.1 
```sql
CREATE TABLE vv1
ENGINE = Memory AS
SELECT groupBitmapState(cityHash64(POSITION_ID)) AS r
FROM POSITION_I
WHERE (FIELDNAME = 'PTY001') AND (VALUE = 1)

Query id: 80de41ae-339f-41c9-a8b7-2dde5faf4e22

Ok.

0 rows in set. Elapsed: 70.690 sec. Processed 40.63 million rows, 2.41 GB (574.74 thousand rows/s., 34.03 MB/s.)
```

Those are 3 seconds versus 70 seconds for the same operation on the same data on the same machine.

**How to reproduce**
* Which ClickHouse server version to use
Clickhouse 20.8.11.17 versus Clickhouse 21.3.14.1 (or newer)

* Queries to run that lead to slow performance

```sql
CREATE TABLE t1
ENGINE = Memory AS
SELECT groupBitmapState(rand64()) AS r
FROM numbers(30000000)


SELECT bitmapCardinality(r)
FROM t1
```

**Expected performance**
Expected performance is similar to 20.8.11.17. That is

CREATE TABLE t1 ....  -> around 12s
SELECT bitmapCardinality(r) ... -> less than 0.01s

actually it is with 21.3.14.1

CREATE TABLE t1 ....  -> around 65s
SELECT bitmapCardinality(r) ... -> 19s

Especially the difference for the SELECT bitmapCardinality(r) is dramatic. From 0.003s to 19s.

**Comment by filimonov** [comment]
```
SELECT count()
FROM numbers_mt(100000000)
HAVING NOT ignore(groupBitmapState(cityHash64(rand() % 100000)))
```

20.11 (last good) Elapsed: 2.843 sec. 

21.1 (first bad) Elapsed: 11.783 sec.

**Comment by filimonov** [comment]
Related to https://github.com/ClickHouse/ClickHouse/issues/7962 and https://github.com/ClickHouse/ClickHouse/pull/17858 

If UInt32 is enough for you you can just cast the argument to UInt32.

**Comment by amosbird** [comment]
> 20.11 (last good) Elapsed: 2.843 sec.

IIRC, it uses UInt32 and produces inaccurate results.

**Comment by congwen** [comment]
why bitmap64 is so slowly？

**Comment by hylllllll** [comment]
It's too slowly. Can it be optimized?

**Comment by maxjustus** [comment]
I am seeing this as well. int64 bitmap operations are shockingly slow

**Comment by desperado1992** [comment]
bitmap64 is very very slow ?  when  optimized ?
