### ISSUE TITLE
When one of zk nodes goes down, tasks will fail

### ISSUE THREAD

**Issue by wzisheng** [ClickHouse/ClickHouse#26558]
I'm working on v21.3.4.25-lts

When one of zk server goes down (for any reasons), the clickhouse server who's connecting to it will report some exceptions . 
At the same time tasks executing on this clickhouse server will fail.
In fact, clickhouse will try to connect to other zk server from the zk cluster automatically from this:
https://github.com/ClickHouse/ClickHouse/blob/47c1bb34163d496a9fe97d1aa4dd73894c4ad5d5/src/Common/ZooKeeper/ZooKeeperImpl.cpp#L354
Once it builds a new connection with zookeeper(maybe another zk server) it returns.

Can we maintanence multi connections with all zookeeper servers at the same time.  In this case if a zookeeper server goes down , clickhouse can switch to another connection without failing the tasks.

Or do we have any other plans for this scenario ?
thanks

**Comment by den-crane** [comment]
>At the same time tasks executing on this clickhouse server will fail.

At the same time CH expect that your client app re-try failed operation, because an operation can fail by many reasons for example because network glitch in between CH server and your client app.

**Comment by wzisheng** [comment]
> > At the same time tasks executing on this clickhouse server will fail.
> 
> At the same time CH expects that your client app re-tries failed operation, because an operation can fail by many reasons. For example because of a network glitch in between CH server and your client app.

Seems reasonable for what you said. Actually i think it's better if CH can select available ZK. Fail the client task only if there's no available ZK can retry.  In this case exceptions between ZK and CH are unperceived for client.

**Comment by wzisheng** [comment]
@alesapin  @tavplubix  hi, I've a doubt here can you help to check:

**Comment by tavplubix** [comment]
> Can we maintanence multi connections with all zookeeper servers at the same time.

It cannot work for fundamental reasons. You will get obscure consistency issues if you send requests to multiple ZooKeeper servers during processing of one "task". The only correct way to process ZooKeeper session expiration is to fail task, reconnect, reinitialize in-memory state and try to execute task from the beginning.

> After first operation timout it will calling finalize(false, false) to set expired to true...

Yes, but we throw "Operation timeout" and set "expired" flag not atomically (because there is no reason to do it atomically). Other threads may throw "Operation timeout" in-between.

**Comment by wzisheng** [comment]
> Yes, but we throw "Operation timeout" and set "expired" flag not atomically (because there is no reason to do it atomically). Other threads may throw "Operation timeout" in-between.
Yes i can see that's not atomically, i just cant' find out why it takes so long time (in my case it's 50s to set expired flag). 
From the code i can see there's only one possibility: finialize() can't get acquire `push_request_mutex ` in 5 consecutive times...
https://github.com/ClickHouse/ClickHouse/blob/0e83fff90d8170a93125191bb928cc33400110a4/src/Common/ZooKeeper/ZooKeeperImpl.cpp#L823

**Comment by tavplubix** [comment]
See #28195

**Comment by wzisheng** [comment]
> See #28195
Great , will it be backported to v21.3 ?

**Comment by den-crane** [comment]
> > See #28195
> > Great , will it be backported to v21.3 ?

no
