### ISSUE TITLE
Backwards compatibility broken when nesting Nullable inside LowCardinality data type

### ISSUE THREAD

**Issue by nvartolomei** [ClickHouse/ClickHouse#26556]
This change #21562 breaks backwards compatibility w/ anything prior to it when nesting Nullable within LowCardinality.

Test case:

Run ClickHouse 21.7

```
CREATE TABLE default.test
(
    `a` UInt64,
    `b` Array(LowCardinality(Nullable(String)))
)
ENGINE = ReplicatedMergeTree('/click/test/', 'r')
ORDER BY a
SETTINGS index_granularity = 8192, min_bytes_for_wide_part = 0;

INSERT INTO test VALUES (0, []);


INSERT INTO test VALUES (1, [null]);
```

Now downgrade to eg ClickHouse 20.8 and the part will be thrown away with one of the following error messages:

```
DB::Exception: No b.dict.null.mrk2 file checksum for column b in part /var/lib/clickhouse/data/default/test/...
```

Newer versions don't write null mask anymore, and old versions require them.

---

What's the purpose of enumerate streams? Can we fix the incompatibility by just changing (backporting to older versions)

`dictionary_type->enumerateStreams(callback, path);` to `removeNullable(dictionary_type)->enumerateStreams(callback, path);` in enumerateStreams or it is more complicated than that?

cc @CurtizJ

**Comment by nvartolomei** [comment]
My naive suggestion is wrong. It would break compatibility even more. Eg when you run 20.8 together w/ 20.8 with the patch.

**Comment by nvartolomei** [comment]
The easiest fix is to probably continue to write empty null mask file.

**Comment by nvartolomei** [comment]
One widely used open source project is using this data type combination btw, Sentry.

**Comment by alexey-milovidov** [comment]
We discussed this issue internally.

It appears that `.null` files for null masks for `LowCardinality` are unneeded and were written in previous versions by mistake.
It is pointless to continue writing unneeded empty files, so the change will remain.

But if you upgrade to newer version and are using `Array(LowCardinality(Nullable(T)))`, then downgrading back to some old version will be impossible. We will add a note about it to the changelog.

Also we may introduce a patch to that old versions to add compatibility. But this has lower priority. It will be done "on request" basis.

**Comment by nvartolomei** [comment]
If I'm not mistaken the same problem will get triggered  when an older replica crashes/is restarted. To keep in mind.

**Comment by filimonov** [comment]
Also during rolling upgrade data coming into updated replicas (if it has `LowCardinality(Nullable(String))`) will not be able to replicate on older replicas, it will be redownloaded several times & detached as broken.
