### ISSUE TITLE
Scale issue of ReplicatedMergeTree caused by zookeeper

### ISSUE THREAD

**Issue by chenxing-xc** [ClickHouse/ClickHouse#2666]
Currently, every part in ReplicatedMergeTree will be registered into zookeeper, this will caused huge znodes in zookeeper. and if there are multiple replicas, the number of znodes is disaster while we deploy a cluster with hundred nodes. 
e.g. we have 2000 parts right now( partition by date and product id), and this number is growing per day. the cluster is composed of  400 nodes.  and this setting create about 6 million znodes and about to reach the limitation of zookeeper. :--(

Rethinking the usage of zookeeper in ClickHouse, it behavior as coordinate service + message queue. Too many (per part) information is registered. and zookeeper (lack of scale ability) could be the bottleneck if part number is high. How could we resolve this problem? is there any plan in ClickHouse roadmap?

**Comment by alexey-milovidov** [comment]
Recently we have introduced an option to lower the size of znodes.
(This doesn't change amount of different znodes but total size of ZK memory and snapshot is much lower.)

To enable, add
```
<merge_tree>
    <use_minimalistic_checksums_in_zookeeper>1</use_minimalistic_checksums_in_zookeeper>
</merge_tree>
```

to `config.xml` or to a separate file in `config.d` directory.

This option was introduced in release: https://github.com/yandex/ClickHouse/blob/master/CHANGELOG.md#clickhouse-release-1154378-2018-04-16

We have already enabled it on all of our clusters and now we are going to enable it by default.
The only caveat: if you enable this option, you cannot rollback to versions prior to 1.1.54378.

**Comment by alexey-milovidov** [comment]
We also have in order of 10..20 million of znodes in our ZK cluster. This still work Ok.
At this moment `use_minimalistic_checksums_in_zookeeper` helps for our case.

**Comment by chenxing-xc** [comment]
Question: if we enable this setting, is it compatible with residual data in zk and local host? and is there any command to refresh the checksum, which already exists in zk, using this minimal format ?

**Comment by alexey-milovidov** [comment]
> Question: if we enable this setting, is it compatible with residual data in zk and local host?

Yes.

> is there any command to refresh the checksum, which already exists in zk, using this minimal format ?

No. Old checksums will be replaced during background merges.

**Comment by qietingfengling** [comment]
Set the use_minimalistic_checksums_in_zookeeper parameter. During the grayscale period, there will be a parameter inconsistency in the cluster for a certain period of time. Will it affect?

**Comment by blinkov** [comment]
@chenxing-xc, do you have any further questions?

**Comment by chenxing-xc** [comment]
Thanks Ivan, no more question from my side. @qietingfengling is not from my
team. maybe he or she still need your help.

Ivan Blinkov <notifications@github.com> 于2020年4月2日周四 上午12:46写道：
