### ISSUE TITLE
Some union all sql makes the clickhouse server  crash

### ISSUE THREAD

**Issue by wangzhen11aaa** [ClickHouse/ClickHouse#26661]
You have to provide the following information whenever possible.

Sql has union all sometimes makes the server crash.

A clear and concise description of what works not as it is supposed to.

On v21.3.3.14-lts
[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

No, inner network.

**How to reproduce**

* Which ClickHouse server version to use
 v21.3.3.14-lts

* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

**Expected behavior**

In the clickhouse-server.log, 
we can see the sql
"SELECT    100000000                                                      AS area_code,
          32                                                             AS area_category_id,
          'Nation'                                                       AS area_name,
          100000000                                                      AS class_code,
          32                                                             AS class_category_id,
          'allClass'                                                    AS class_name,
          sum(IF (class_line_id > 0, order_money, 0)) / sum(order_money)    protein_ratio
FROM      (
                 SELECT order_datekey,
                        sku_id,
                        company_id,
                        sale_area_id,
                        order_status,
                        order_money,
                        sale_type
                 FROM   etl_dwd_ord_order_detail_rt final
                 WHERE  order_datekey = 20210719
                 AND    c_t<=1626684005
                 AND    order_status > 0
                 AND    promotion_type NOT IN (1,
                                               2,
                                               99)
                 AND    IF(sale_type IS NULL,3,sale_type) =1
                 AND    city_flag=2 ) oi
JOIN
          (
                 SELECT sku_id,
                        class2_id,
                        class2_name
                 FROM   etl_membi_product_pms_class_sku_map_realtime final ) sku
ON        oi.sku_id = sku.sku_id
LEFT JOIN
          (
                 SELECT class_l2_id,
                        class_line_id
                 FROM   etl_dim_custom_class
                 WHERE  class_line_id = 33 ) cus
ON        sku.class2_id = cus.class_l2_id
UNION ALL
SELECT    sa.big_area_id                                                 area_code,
          7                                                              AS area_category_id,
          sa.big_area_name                                                  area_name,
          100000000                                                      AS class_code,
          32                                                             AS class_category_id,
          'allClass'                                                    AS class_name,
          sum(IF (class_line_id > 0, order_money, 0)) / sum(order_money)    protein_ratio
FROM      (
                 SELECT order_datekey,
                        sku_id,
                        company_id,
                        sale_area_id,
                        order_status,
                        order_money,
                        sale_type
                 FROM   etl_dwd_ord_order_detail_rt final
                 WHERE  order_datekey = 20210719
                 AND    c_t<=1626684005
                 AND    order_status > 0
                 AND    promotion_type NOT IN (1,
                                               2,
                                               99)
                 AND    IF(sale_type IS NULL,3,sale_type) =1
                 AND    city_flag=2 ) oi
JOIN
          (
                 SELECT sale_area_id,
                        big_area_id,
                        big_area_name
                 FROM   etl_membi_dim_city_manage_type final ) sa
ON        sa.sale_area_id = oi.sale_area_id
JOIN
          (
                 SELECT sku_id,
                        class2_id,
                        class2_name
                 FROM   etl_membi_product_pms_class_sku_map_realtime final ) sku
ON        oi.sku_id = sku.sku_id
LEFT JOIN
          (
                 SELECT class_l2_id,
                        class_line_id
                 FROM   etl_dim_custom_class
                 WHERE  class_line_id = 33 ) cus
ON        sku.class2_id = cus.class_l2_id
GROUP BY  area_code,
          area_name
UNION ALL
SELECT    sa.zhucheng_id                                                 area_code,
          34                                                             AS area_category_id,
          sa.zhucheng_name                                                  area_name,
          100000000                                                      AS class_code,
          32                                                             AS class_category_id,
          'allClass'                                                    AS class_name,
          sum(IF (class_line_id > 0, order_money, 0)) / sum(order_money)    protein_ratio
FROM      (
                 SELECT order_datekey,
                        sku_id,
                        company_id,
                        sale_area_id,
                        order_status,
                        order_money,
                        sale_type
                 FROM   etl_dwd_ord_order_detail_rt final
                 WHERE  order_datekey = 20210719
                 AND    c_t<=1626684005
                 AND    order_status > 0
                 AND    promotion_type NOT IN (1,
                                               2,
                                               99)
                 AND    IF(sale_type IS NULL,3,sale_type) =1
                 AND    city_flag=2 ) oi
JOIN
          (
                 SELECT sale_area_id,
                        zhucheng_id,
                        zhucheng_name
                 FROM   etl_membi_dim_city_manage_type final ) sa
ON        sa.sale_area_id = oi.sale_area_id
JOIN
          (
                 SELECT sku_id,
                        class2_id,
                        class2_name
                 FROM   etl_membi_product_pms_class_sku_map_realtime final ) sku
ON        oi.sku_id = sku.sku_id
LEFT JOIN
          (
                 SELECT class_l2_id,
                        class_line_id
                 FROM   etl_dim_custom_class
                 WHERE  class_line_id = 33 ) cus
ON        sku.class2_id = cus.class_l2_id
GROUP BY  area_code,
          area_name format tabseparatedwithnamesandtypes;"

Log information in system.crash_log;
		{
			"event_date": "2021-07-19",
			"event_time": "2021-07-19 16:40:08",
			"timestamp_ns": "1626684008813485010",
			"signal": 6,
			"thread_id": "74408",
			"query_id": "16790BA66BBE6A06",
			"trace": ["139754534883847","139754534889720","201165456","161909058","161909114"],
			"trace_full": ["3. gsignal @ 0x36207 in \/usr\/lib64\/libc-2.17.so","4. abort @ 0x378f8 in \/usr\/lib64\/libc-2.17.so","5. _Unwind_Resume @ 0xbfd8a90 in \/usr\/bin\/clickhouse","6. ? @ 0x9a68942 in \/usr\/bin\/clickhouse","7. void boost::context::detail::fiber_entry<boost::context::detail::fiber_record<boost::context::fiber, FiberStack&, DB::PacketReceiver::Routine> >(boost::context::detail::transfer_t) @ 0x9a6897a in \/usr\/bin\/clickhouse"],
			"version": "ClickHouse 21.4.1.1",
			"revision": 54449,
			"build_id": "F99DA3EA2E80949BC71FC7F746D770608481D2B4"
		},

I have searched that, the boost::context is used to simulate the coroutine and signal 6 (abort) is usually a memory problem,
and does these information results in the parallel execution of the sql?

**Comment by abyss7** [comment]
Can you try and provide some data to reproduce an issue? Or at least provide `CREATE TABLE` statements?

**Comment by den-crane** [comment]
Log indicates 
"version": "ClickHouse 21.4.1.1",
"revision": 54449,
"build_id": "F99DA3EA2E80949BC71FC7F746D770608481D2B4"

 There is no such version. This is unofficial build. It's unsupported.

**Comment by alexey-milovidov** [comment]
Update to the latest release.
