### ISSUE TITLE
how to speed up count distinct query

### ISSUE THREAD

**Issue by l1t1** [ClickHouse/ClickHouse#26666]
with t as (select number n from system.numbers limit 123456789)
select count(distinct case when n%10 =1 then n else null end) from t 
took 2.7s
if i omit  distinct, it took 1.4s
I try to rewrite it with group by case when as follows, it's slower. 

 with t as (select number n from system.numbers limit 123456789)
,t2 as (select case when n%10 =1 then n else null end a from t group by a)
select count(a) from t2
took 6.6s

**Comment by den-crane** [comment]
```
with t as (select number n from system.numbers limit 123456789)
select uniqIf(n,n%10) from t

┌─uniqIf(n, modulo(n, 10))─┐
│                110875347 │
└──────────────────────────┘
```

**Comment by l1t1** [comment]
https://clickhouse.tech/docs/en/sql-reference/aggregate-functions/reference/uniq/
says
uniq 
Calculates the approximate number of different values of the argument.
uniqExact
Calculates the exact number of different argument values.

the later is slow

**Comment by den-crane** [comment]
And what? Magic does not exists. 
You cannot have both (speed and accuracy).
