### ISSUE TITLE
untuple() function does not return field names

### ISSUE THREAD

**Issue by huzinagi** [ClickHouse/ClickHouse#26670]
ClickHouse version 21.7.4.18:
`SELECT untuple((a, b))
FROM
(
    SELECT
        1 AS a,
        2 AS b
)

Query id: 29253bb4-efb1-401e-94c0-d6351ec3b50d

┌─tupleElement(tuple(a, b), 1)─┬─tupleElement(tuple(a, b), 2)─┐
│                                              1 │                                              2 │
└───────  ───────────┴───────────────────┘
`

ClickHouse vrsion 21.5.6.6 :
`SELECT untuple((a, b))
FROM
(
    SELECT
        1 AS a,
        2 AS b
)

Query id: c7eb6f97-a89a-4d9c-8415-2f1fcfd4edcd

┌─a─┬─b─┐
│     1 │    2 │
└───┴──┘
`
In this case, the request was executed as written in the documentation

**Comment by alexey-milovidov** [comment]
See https://github.com/ClickHouse/ClickHouse/pull/26179

**Comment by rchadin** [comment]
It turns out that this will be fixed in version 21.9, which instead of the column names "tupleElement(tuple(a, b), 1)" and "tupleElement(tuple(a, b), 2)"  will be as before "a" and "b"?

**Comment by alexey-milovidov** [comment]
No, it's not fixed in 21.9.

**Comment by mafiore** [comment]
this is sad. it would be nice to have pretty names .
