### ISSUE TITLE
What'll happen if set prefer_not_to_merge on all storage volumes  with MergeTree engine？

### ISSUE THREAD

**Issue by allen12921** [ClickHouse/ClickHouse#26685]
Just curious what will happen if CH server with below settings when the table was created in  MergeTree engine?

<storage_configuration>
  <disks>
        <disk_name_1> 
            <path>/mnt/fast_ssd/clickhouse/</path>
        </disk_name_1>
    </disks>
    <policies>
        <policy_name_1>
            <volumes>
                <volume_name_1>
                    <disk>disk_name_1</disk>
                    <prefer_not_to_merge>true</prefer_not_to_merge>
                </volume_name_1>
            </volumes>
            <move_factor>0.1</move_factor>
        </policy_name_1>
    </storage_configuration>

**Comment by alexey-milovidov** [comment]
Nothing good will happen.
