### ISSUE TITLE
ReplacingMergeTree Query with FINAL Modifier and LIMIT Modifier unexpect result

### ISSUE THREAD

**Issue by zhaixun** [ClickHouse/ClickHouse#26686]
**Describe the bug**
ClickHouse client version 21.3.3.14 (official build).

When i use  FINAL Modifier and LIMIT Modifier  on ReplacingMergeTree Engine, the returned result is not the final status

**How to reproduce**

Step 1:
CREATE TABLE test
(
    `uid` String,
	`status` String,
    `finalDate` DateTime DEFAULT now()
)
ENGINE = ReplacingMergeTree(finalDate)
PARTITION BY javaHash(uid) % 10
ORDER BY uid SETTINGS index_granularity = 8192

Step2:
insert into table test(uid,status) values ('id1','0')
insert into table test(uid,status) values ('id1','1')

Step3:
select * from test final
┌─uid─┬─status─┬───────────finalDate─┐
│ id1 │ 1      │ 2021-07-22 14:44:01 │
└─────┴────────┴─────────────────────┘

Step4:
select * from test final  limit 1
┌─uid─┬─status─┬───────────finalDate─┐
│ id1 │ 0      │ 2021-07-22 14:43:58 │
└─────┴────────┴─────────────────────┘

expected result is id1,1,2021-07-22 14:44:01

**Comment by alexey-milovidov** [comment]
Does not reproduce in version 22.2.

**Comment by den-crane** [comment]
it does not reproduce after 21.7
