### ISSUE TITLE
request fails without a field from WHERE

### ISSUE THREAD

**Issue by evakorne** [ClickHouse/ClickHouse#26689]
I am getting the following error on request like this

> Code: 47, e.displayText() = DB::Exception: Missing columns: 'name' while processing query: '_sign = 1, id, name, type', required columns: '_sign' 'id' 'name' 'type' '_sign' 'id' 'name' 'type' (version 21.7.4.18 (official build))

```
SELECT　id　  
FROM lender　  
WHERE name = 'q'
```

however this request works

```
SELECT　id, name　  
FROM lender　  
WHERE name = 'q'
```

I can't use a subquery, how can I get around this?

```
SELECT id
  FROM (SELECT id, name
  FROM lender  
  WHERE name = 'q') d
```

DESCRIBE lender
![image](https://user-images.githubusercontent.com/87803630/126610615-38a6c21a-a17d-43ca-a5cf-43330541e20f.png)

**Comment by den-crane** [comment]
Can you share `show create table lender` `show create database ....` ?
Do you use myterializeMysql?

Possibly duplicate for https://github.com/ClickHouse/ClickHouse/issues/24830

**Comment by evakorne** [comment]
> Can you share `show create table lender` `show create database ....` ?
> Do you use myterializeMysql?
> 
> Possibly duplicate for #24830

yes

```
┌─statement──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ CREATE TABLE ****.lender
(
    `id` Int32,
    `product_type_id` Nullable(UInt32),
    `code` String,
    `name` String,
    `country_code` Nullable(String),
    `type` Nullable(String),
    `url` Nullable(String),
    `is_active` Int8,
    `real_time_tracking` Nullable(Int8),
    `tracking_description` Nullable(String),
    `_sign` Int8 MATERIALIZED 1,
    `_version` UInt64 MATERIALIZED 1,
    INDEX _version _version TYPE minmax GRANULARITY 1
)
ENGINE = ReplacingMergeTree(_version)
PARTITION BY intDiv(id, 4294967)
ORDER BY (assumeNotNull(product_type_id), assumeNotNull(type), code, id)
SETTINGS index_granularity = 8192 │


CREATE DATABASE ****
ENGINE = MaterializeMySQL(******) 
```

**Comment by den-crane** [comment]
It's already fixed. Will be available in the next release.
