### ISSUE TITLE
system.tables has only 7907 rows and this query takes a very longtime to execute, SELECT * FROM system.tables WHERE is_temporary = 0 SETTINGS show_table_uuid_in_table_create_query_if_not_nil=1. Any idea why does this take such a long time ?  

### ISSUE THREAD

**Issue by ljinde** [ClickHouse/ClickHouse#26693]
Make sure to check documentation https://clickhouse.yandex/docs/en/ first. If the question is concise and probably has a short answer, asking it in Telegram chat https://telegram.me/clickhouse_en is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

If you still prefer GitHub issues, remove all this text and ask your question here.

**Comment by den-crane** [comment]
clarify long? 1 second? 1 hour?

Please share statistics for `select name, database from system.tables WHERE is_temporary = 0`

Ch reads .sql files from metadata folder for the column `create_table_query` it tabes time read 7907 files

**Comment by alexey-milovidov** [comment]
Specify only needed columns instead of `SELECT *`.
Some columns in this table are calculated on the fly and are quite heavy.
