### ISSUE TITLE
How to measure disk operations caused by max_bytes_before_external_group_by or max_bytes_before_external_sort

### ISSUE THREAD

**Issue by browcio** [ClickHouse/ClickHouse#26692]
I wonder if there is a way to visualize how much data is written to disk when max_bytes_before_external_group_by or max_bytes_before_external_sort is in use. From what i searched, there are no matching column in a system.query_log or in system metrics.

**Comment by thealexjo** [comment]
`select written_bytes from query_log where has(Settings.Names, 'max_bytes_before_external_sort')`

But does this make sense? Those settings are in-memory settings and affect only `SELECT` statements.
