### ISSUE TITLE
build  failed!  out of memory

### ISSUE THREAD

**Issue by zqchinaone** [ClickHouse/ClickHouse#26728]
Hello！everyone

I am getting this error:

ninja
[0/2] Re-checking globbed directories...
[2/225] Linking CXX static library src/libdbms.a
FAILED: src/libdbms.a

/opt/rh/devtoolset-10/root/usr/bin/ranlib: out of memory allocating 6873453400573489713 bytes after a total of 16908288 bytes
ninja: build stopped: subcommand failed.
=====
ClickHouse v21.7.4.18-stable
=====
 gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/opt/rh/devtoolset-10/root/usr --mandir=/opt/rh/devtoolset-10/root/usr/share/man --infodir=/opt/rh/devtoolset-10/root/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --with-default-libstdcxx-abi=gcc4-compatible --enable-plugin --enable-initfini-array --with-isl=/builddir/build/BUILD/gcc-10.2.1-20210130/obj-x86_64-redhat-linux/isl-install --disable-libmpx --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 10.2.1 20210130 (Red Hat 10.2.1-11) (GCC)
====
free -m
              total        used        free      shared  buff/cache   available
Mem:          15866        5482        1969          24        8414       10029
Swap:          6047           1        6046

====
ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 63334
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 63334
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
===
cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)
===

**Comment by abyss7** [comment]
It's a problem with your local build tools - we neither can debug this issue, nor do support custom builds.
