### ISSUE TITLE
How to open the map feature on cluster

### ISSUE THREAD

**Issue by lightClouds917** [ClickHouse/ClickHouse#26729]
i can set allow_experimental_map_type = 1 on simple node . it is ok to set and to use map.
but when i deploy cluster with 4 shards and 2 replicas, i can not set this params.
how can i use map feature when cluster deployment?
version:21.5.6.6.
thanks!

**Comment by den-crane** [comment]
users profile

```
# cat /etc/clickhouse-server/users.d/allow_experimental_map_type.xml

<?xml version="1.0"?>
<yandex>
    <profiles>
        <default>
           <allow_experimental_map_type>1</allow_experimental_map_type>
        </default>
    </profiles>
</yandex>
```
Restart is not needed.
