### ISSUE TITLE
A time-consuming problem of Clickhouse driver node

### ISSUE THREAD

**Issue by shadowDy** [ClickHouse/ClickHouse#26737]
In the Clickhouse cluster (300 instances), connect a single instance on a node through the Clickhouse client method, and then initiate the select count() from XXXX operation;

In many tests, it is found that there are occasional time-consuming and long tail problems;

Then, through query_ After the ID pulls the execution time on each instance; It is found that the long tail often appears in the dirver node (the node that initiates the SQL request connection), and the time consumption of this node is several times longer than that of other nodes;

For example, the maximum time for other nodes is 2S, the time for dirver nodes is 10 + s, and the total time is 10 + s; 

What will lead to this problem and how to avoid it?

**Comment by den-crane** [comment]
It's expected behavior. Node initator takes time to combine results from shards.
You can check is it true or not by setting `set distributed_group_by_no_merge=1`

 --distributed_group_by_no_merge arg                              If 1, Do not merge aggregation states from different servers for distributed queries (shards will process query up to the

**Comment by shadowDy** [comment]
> It's expected behavior. Node initator takes time to combine results from shards.
> You can check is it true or not by setting `set distributed_group_by_no_merge=1`
> 
> --distributed_group_by_no_merge arg If 1, Do not merge aggregation states from different servers for distributed queries (shards will process query up to the

@den-crane 
The SQL I initiated is only select count() from XXX. There are no other aggregation operations. The data returned from each node to dirver is summed. Normally, it will not take so much time.

**Comment by den-crane** [comment]
Please share statistics for 
`set distributed_group_by_no_merge=0; select....`
`set distributed_group_by_no_merge=1; select....`

And trace
```
set send_logs_level='trace';
select.... format Null
```

**Comment by shadowDy** [comment]
> set send_logs_level='trace';
> select.... format Null
> ```
 2021.07.27 10:53:31.968736 [ 30637 ] {40c14a84-24e6-486b-ac5e-c04f9c37eb94} <Trace> InterpreterSelectQuery: WithMergeableState -> WithMergeableState
 2021.07.27 10:53:32.017057 [ 30637 ] {40c14a84-24e6-486b-ac5e-c04f9c37eb94} <Information> executeQuery: Read 1 rows, 4.01 KiB in 0.881749787 sec., 1 rows/sec., 4.55 KiB/sec.
 2021.07.27 10:53:32.017163 [ 30637 ] {40c14a84-24e6-486b-ac5e-c04f9c37eb94} <Debug> MemoryTracker: Peak memory usage (for query): 0.00 B.
 2021.07.27 10:53:31.746844 [ 24571 ] {8efca6e0-880a-4388-a5bc-8ef6508152b5} <Debug> executeQuery: (from 10.141.226.164:53306, initial_query_id: 3a960287-163f-4e8e-94f3-7df0b6c6a0e3, using production parser) SELECT count() FROM sessiondb.ug_dws_bhv_bd_dau_1d_local
 2021.07.27 10:53:32.072983 [ 114800 ] {bc0a8d32-7387-4a64-800d-262c9fc07c7a} <Trace> ContextAccess (default): Access granted: SELECT(cuid) ON sessiondb.ug_dws_bhv_bd_dau_1d_local
 2021.07.27 10:53:32.514148 [ 114800 ] {bc0a8d32-7387-4a64-800d-262c9fc07c7a} <Trace> InterpreterSelectQuery: WithMergeableState -> WithMergeableState
 2021.07.27 10:53:32.533677 [ 114800 ] {bc0a8d32-7387-4a64-800d-262c9fc07c7a} <Information> executeQuery: Read 1 rows, 4.01 KiB in 0.772485908 sec., 1 rows/sec., 5.19 KiB/sec.
 2021.07.27 10:53:32.533872 [ 114800 ] {bc0a8d32-7387-4a64-800d-262c9fc07c7a} <Debug> MemoryTracker: Peak memory usage (for query): 0.00 B.
 2021.07.27 10:53:32.418777 [ 24571 ] {8efca6e0-880a-4388-a5bc-8ef6508152b5} <Trace> ContextAccess (default): Access granted: SELECT(cuid) ON sessiondb.ug_dws_bhv_bd_dau_1d_local
 2021.07.27 10:53:32.549235 [ 24571 ] {8efca6e0-880a-4388-a5bc-8ef6508152b5} <Trace> InterpreterSelectQuery: WithMergeableState -> WithMergeableState
 2021.07.27 10:53:32.560853 [ 24571 ] {8efca6e0-880a-4388-a5bc-8ef6508152b5} <Information> executeQuery: Read 1 rows, 4.01 KiB in 0.473697524 sec., 2 rows/sec., 8.46 KiB/sec.
 2021.07.27 10:53:32.562133 [ 24571 ] {8efca6e0-880a-4388-a5bc-8ef6508152b5} <Debug> MemoryTracker: Peak memory usage (for query): 0.00 B.
 2021.07.27 10:54:03.150866 [ 69117 ] {26f26c92-ad3c-4d64-adb6-f35142c59c14} <Debug> executeQuery: (from 10.141.226.164:55834, initial_query_id: 3a960287-163f-4e8e-94f3-7df0b6c6a0e3, using production parser) SELECT count() FROM sessiondb.ug_dws_bhv_bd_dau_1d_local
 2021.07.27 10:54:03.150794 [ 95217 ] {59160b74-cf97-4fcd-bcb8-8c2372302e80} <Debug> executeQuery: (from 10.141.226.164:62281, initial_query_id: 3a960287-163f-4e8e-94f3-7df0b6c6a0e3, using production parser) SELECT count() FROM sessiondb.ug_dws_bhv_bd_dau_1d_local
 2021.07.27 10:54:04.974346 [ 69117 ] {26f26c92-ad3c-4d64-adb6-f35142c59c14} <Trace> ContextAccess (default): Access granted: SELECT(cuid) ON sessiondb.ug_dws_bhv_bd_dau_1d_local
 2021.07.27 10:54:06.171025 [ 69117 ] {26f26c92-ad3c-4d64-adb6-f35142c59c14} <Trace> InterpreterSelectQuery: WithMergeableState -> WithMergeableState
 2021.07.27 10:54:04.974390 [ 95217 ] {59160b74-cf97-4fcd-bcb8-8c2372302e80} <Trace> ContextAccess (default): Access granted: SELECT(cuid) ON sessiondb.ug_dws_bhv_bd_dau_1d_local
 2021.07.27 10:54:06.170943 [ 95217 ] {59160b74-cf97-4fcd-bcb8-8c2372302e80} <Trace> InterpreterSelectQuery: WithMergeableState -> WithMergeableState
 2021.07.27 10:54:06.666414 [ 95217 ] {59160b74-cf97-4fcd-bcb8-8c2372302e80} <Information> executeQuery: Read 1 rows, 4.01 KiB in 3.253392704 sec., 0 rows/sec., 1.23 KiB/sec.
 2021.07.27 10:54:06.666484 [ 95217 ] {59160b74-cf97-4fcd-bcb8-8c2372302e80} <Debug> MemoryTracker: Peak memory usage (for query): 0.00 B.
 2021.07.27 10:54:06.666505 [ 69117 ] {26f26c92-ad3c-4d64-adb6-f35142c59c14} <Information> executeQuery: Read 1 rows, 4.01 KiB in 3.256510595 sec., 0 rows/sec., 1.23 KiB/sec.
 2021.07.27 10:54:06.666587 [ 69117 ] {26f26c92-ad3c-4d64-adb6-f35142c59c14} <Debug> MemoryTracker: Peak memory usage (for query): 0.00 B.
 2021.07.27 10:54:06.746683 [ 134 ] {3a960287-163f-4e8e-94f3-7df0b6c6a0e3} <Trace> Aggregator: Merging partially aggregated blocks (bucket = -1).
 2021.07.27 10:54:06.754556 [ 134 ] {3a960287-163f-4e8e-94f3-7df0b6c6a0e3} <Trace> Aggregator: Merged partially aggregated blocks. 1 rows, 8.00 B. in 0.007745992 sec. (129.09902308187253 rows/sec., 1.01 KiB/sec.)
 2021.07.27 10:54:06.759025 [ 32761 ] {3a960287-163f-4e8e-94f3-7df0b6c6a0e3} <Information> executeQuery: Read 100 rows, 400.78 KiB in 36.645041528 sec., 2 rows/sec., 10.94 KiB/sec.

Some tracing logs are as above.

It is found from the log that the execution time on each node is not long, but there is no log for a period of time, which takes 30 + S. in terms of time-consuming statistics, the time-consuming driver is high and the time-consuming node is low.

**Comment by shadowDy** [comment]
`2021.07.27 10:53:31.968736 [ 30637 ] {40c14a84-24e6-486b-ac5e-c04f9c37eb94} InterpreterSelectQuery: WithMergeableState -> WithMergeableState
2021.07.27 10:53:32.017057 [ 30637 ] {40c14a84-24e6-486b-ac5e-c04f9c37eb94} executeQuery: Read 1 rows, 4.01 KiB in 0.881749787 sec., 1 rows/sec., 4.55 KiB/sec.
2021.07.27 10:53:32.017163 [ 30637 ] {40c14a84-24e6-486b-ac5e-c04f9c37eb94} MemoryTracker: Peak memory usage (for query): 0.00 B.
2021.07.27 10:53:31.746844 [ 24571 ] {8efca6e0-880a-4388-a5bc-8ef6508152b5} executeQuery: (from 10.141.226.164:53306, initial_query_id: 3a960287-163f-4e8e-94f3-7df0b6c6a0e3, using production parser) SELECT count() FROM sessiondb.ug_dws_bhv_bd_dau_1d_local
2021.07.27 10:53:32.072983 [ 114800 ] {bc0a8d32-7387-4a64-800d-262c9fc07c7a} ContextAccess (default): Access granted: SELECT(cuid) ON sessiondb.ug_dws_bhv_bd_dau_1d_local
2021.07.27 10:53:32.514148 [ 114800 ] {bc0a8d32-7387-4a64-800d-262c9fc07c7a} InterpreterSelectQuery: WithMergeableState -> WithMergeableState
2021.07.27 10:53:32.533677 [ 114800 ] {bc0a8d32-7387-4a64-800d-262c9fc07c7a} executeQuery: Read 1 rows, 4.01 KiB in 0.772485908 sec., 1 rows/sec., 5.19 KiB/sec.
2021.07.27 10:53:32.533872 [ 114800 ] {bc0a8d32-7387-4a64-800d-262c9fc07c7a} MemoryTracker: Peak memory usage (for query): 0.00 B.
2021.07.27 10:53:32.418777 [ 24571 ] {8efca6e0-880a-4388-a5bc-8ef6508152b5} ContextAccess (default): Access granted: SELECT(cuid) ON sessiondb.ug_dws_bhv_bd_dau_1d_local
2021.07.27 10:53:32.549235 [ 24571 ] {8efca6e0-880a-4388-a5bc-8ef6508152b5} InterpreterSelectQuery: WithMergeableState -> WithMergeableState
2021.07.27 10:53:32.560853 [ 24571 ] {8efca6e0-880a-4388-a5bc-8ef6508152b5} executeQuery: Read 1 rows, 4.01 KiB in 0.473697524 sec., 2 rows/sec., 8.46 KiB/sec.
2021.07.27 10:53:32.562133 [ 24571 ] {8efca6e0-880a-4388-a5bc-8ef6508152b5} MemoryTracker: Peak memory usage (for query): 0.00 B.
2021.07.27 10:54:03.150866 [ 69117 ] {26f26c92-ad3c-4d64-adb6-f35142c59c14} executeQuery: (from 10.141.226.164:55834, initial_query_id: 3a960287-163f-4e8e-94f3-7df0b6c6a0e3, using production parser) SELECT count() FROM sessiondb.ug_dws_bhv_bd_dau_1d_local
2021.07.27 10:54:03.150794 [ 95217 ] {59160b74-cf97-4fcd-bcb8-8c2372302e80} executeQuery: (from 10.141.226.164:62281, initial_query_id: 3a960287-163f-4e8e-94f3-7df0b6c6a0e3, using production parser) SELECT count() FROM sessiondb.ug_dws_bhv_bd_dau_1d_local
2021.07.27 10:54:04.974346 [ 69117 ] {26f26c92-ad3c-4d64-adb6-f35142c59c14} ContextAccess (default): Access granted: SELECT(cuid) ON sessiondb.ug_dws_bhv_bd_dau_1d_local
2021.07.27 10:54:06.171025 [ 69117 ] {26f26c92-ad3c-4d64-adb6-f35142c59c14} InterpreterSelectQuery: WithMergeableState -> WithMergeableState
2021.07.27 10:54:04.974390 [ 95217 ] {59160b74-cf97-4fcd-bcb8-8c2372302e80} ContextAccess (default): Access granted: SELECT(cuid) ON sessiondb.ug_dws_bhv_bd_dau_1d_local
2021.07.27 10:54:06.170943 [ 95217 ] {59160b74-cf97-4fcd-bcb8-8c2372302e80} InterpreterSelectQuery: WithMergeableState -> WithMergeableState
2021.07.27 10:54:06.666414 [ 95217 ] {59160b74-cf97-4fcd-bcb8-8c2372302e80} executeQuery: Read 1 rows, 4.01 KiB in 3.253392704 sec., 0 rows/sec., 1.23 KiB/sec.
2021.07.27 10:54:06.666484 [ 95217 ] {59160b74-cf97-4fcd-bcb8-8c2372302e80} MemoryTracker: Peak memory usage (for query): 0.00 B.
2021.07.27 10:54:06.666505 [ 69117 ] {26f26c92-ad3c-4d64-adb6-f35142c59c14} executeQuery: Read 1 rows, 4.01 KiB in 3.256510595 sec., 0 rows/sec., 1.23 KiB/sec.
2021.07.27 10:54:06.666587 [ 69117 ] {26f26c92-ad3c-4d64-adb6-f35142c59c14} MemoryTracker: Peak memory usage (for query): 0.00 B.
2021.07.27 10:54:06.746683 [ 134 ] {3a960287-163f-4e8e-94f3-7df0b6c6a0e3} Aggregator: Merging partially aggregated blocks (bucket = -1).
2021.07.27 10:54:06.754556 [ 134 ] {3a960287-163f-4e8e-94f3-7df0b6c6a0e3} Aggregator: Merged partially aggregated blocks. 1 rows, 8.00 B. in 0.007745992 sec. (129.09902308187253 rows/sec., 1.01 KiB/sec.)
2021.07.27 10:54:06.759025 [ 32761 ] {3a960287-163f-4e8e-94f3-7df0b6c6a0e3} executeQuery: Read 100 rows, 400.78 KiB in 36.645041528 sec., 2 rows/sec., 10.94 KiB/sec.`

**Comment by shadowDy** [comment]
> 2021.07.27 10:53:31.968736 [ 30637 ] {40c14a84-24e6-486b-ac5e-c04f9c37eb94} InterpreterSelectQuery: WithMergeableState -> WithMergeableState
2021.07.27 10:53:32.017057 [ 30637 ] {40c14a84-24e6-486b-ac5e-c04f9c37eb94} executeQuery: Read 1 rows, 4.01 KiB in 0.881749787 sec., 1 rows/sec., 4.55 KiB/sec.
2021.07.27 10:53:32.017163 [ 30637 ] {40c14a84-24e6-486b-ac5e-c04f9c37eb94} MemoryTracker: Peak memory usage (for query): 0.00 B.
2021.07.27 10:53:31.746844 [ 24571 ] {8efca6e0-880a-4388-a5bc-8ef6508152b5} executeQuery: (from 10.141.226.164:53306, initial_query_id: 3a960287-163f-4e8e-94f3-7df0b6c6a0e3, using production parser) SELECT count() FROM sessiondb.ug_dws_bhv_bd_dau_1d_local
2021.07.27 10:53:32.072983 [ 114800 ] {bc0a8d32-7387-4a64-800d-262c9fc07c7a} ContextAccess (default): Access granted: SELECT(cuid) ON sessiondb.ug_dws_bhv_bd_dau_1d_local
2021.07.27 10:53:32.514148 [ 114800 ] {bc0a8d32-7387-4a64-800d-262c9fc07c7a} InterpreterSelectQuery: WithMergeableState -> WithMergeableState
2021.07.27 10:53:32.533677 [ 114800 ] {bc0a8d32-7387-4a64-800d-262c9fc07c7a} executeQuery: Read 1 rows, 4.01 KiB in 0.772485908 sec., 1 rows/sec., 5.19 KiB/sec.
2021.07.27 10:53:32.533872 [ 114800 ] {bc0a8d32-7387-4a64-800d-262c9fc07c7a} MemoryTracker: Peak memory usage (for query): 0.00 B.
2021.07.27 10:53:32.418777 [ 24571 ] {8efca6e0-880a-4388-a5bc-8ef6508152b5} ContextAccess (default): Access granted: SELECT(cuid) ON sessiondb.ug_dws_bhv_bd_dau_1d_local
2021.07.27 10:53:32.549235 [ 24571 ] {8efca6e0-880a-4388-a5bc-8ef6508152b5} InterpreterSelectQuery: WithMergeableState -> WithMergeableState
2021.07.27 10:53:32.560853 [ 24571 ] {8efca6e0-880a-4388-a5bc-8ef6508152b5} executeQuery: Read 1 rows, 4.01 KiB in 0.473697524 sec., 2 rows/sec., 8.46 KiB/sec.
2021.07.27 10:53:32.562133 [ 24571 ] {8efca6e0-880a-4388-a5bc-8ef6508152b5} MemoryTracker: Peak memory usage (for query): 0.00 B.
2021.07.27 10:54:03.150866 [ 69117 ] {26f26c92-ad3c-4d64-adb6-f35142c59c14} executeQuery: (from 10.141.226.164:55834, initial_query_id: 3a960287-163f-4e8e-94f3-7df0b6c6a0e3, using production parser) SELECT count() FROM sessiondb.ug_dws_bhv_bd_dau_1d_local
2021.07.27 10:54:03.150794 [ 95217 ] {59160b74-cf97-4fcd-bcb8-8c2372302e80} executeQuery: (from 10.141.226.164:62281, initial_query_id: 3a960287-163f-4e8e-94f3-7df0b6c6a0e3, using production parser) SELECT count() FROM sessiondb.ug_dws_bhv_bd_dau_1d_local
2021.07.27 10:54:04.974346 [ 69117 ] {26f26c92-ad3c-4d64-adb6-f35142c59c14} ContextAccess (default): Access granted: SELECT(cuid) ON sessiondb.ug_dws_bhv_bd_dau_1d_local
2021.07.27 10:54:06.171025 [ 69117 ] {26f26c92-ad3c-4d64-adb6-f35142c59c14} InterpreterSelectQuery: WithMergeableState -> WithMergeableState
2021.07.27 10:54:04.974390 [ 95217 ] {59160b74-cf97-4fcd-bcb8-8c2372302e80} ContextAccess (default): Access granted: SELECT(cuid) ON sessiondb.ug_dws_bhv_bd_dau_1d_local
2021.07.27 10:54:06.170943 [ 95217 ] {59160b74-cf97-4fcd-bcb8-8c2372302e80} InterpreterSelectQuery: WithMergeableState -> WithMergeableState
2021.07.27 10:54:06.666414 [ 95217 ] {59160b74-cf97-4fcd-bcb8-8c2372302e80} executeQuery: Read 1 rows, 4.01 KiB in 3.253392704 sec., 0 rows/sec., 1.23 KiB/sec.
2021.07.27 10:54:06.666484 [ 95217 ] {59160b74-cf97-4fcd-bcb8-8c2372302e80} MemoryTracker: Peak memory usage (for query): 0.00 B.
2021.07.27 10:54:06.666505 [ 69117 ] {26f26c92-ad3c-4d64-adb6-f35142c59c14} executeQuery: Read 1 rows, 4.01 KiB in 3.256510595 sec., 0 rows/sec., 1.23 KiB/sec.
2021.07.27 10:54:06.666587 [ 69117 ] {26f26c92-ad3c-4d64-adb6-f35142c59c14} MemoryTracker: Peak memory usage (for query): 0.00 B.
2021.07.27 10:54:06.746683 [ 134 ] {3a960287-163f-4e8e-94f3-7df0b6c6a0e3} Aggregator: Merging partially aggregated blocks (bucket = -1).
2021.07.27 10:54:06.754556 [ 134 ] {3a960287-163f-4e8e-94f3-7df0b6c6a0e3} Aggregator: Merged partially aggregated blocks. 1 rows, 8.00 B. in 0.007745992 sec. (129.09902308187253 rows/sec., 1.01 KiB/sec.)
2021.07.27 10:54:06.759025 [ 32761 ] {3a960287-163f-4e8e-94f3-7df0b6c6a0e3} executeQuery: Read 100 rows, 400.78 KiB in 36.645041528 sec., 2 rows/sec., 10.94 KiB/sec.

**Comment by shadowDy** [comment]
**2021.07.27 10:53:31.968736 [ 30637 ] {40c14a84-24e6-486b-ac5e-c04f9c37eb94} InterpreterSelectQuery: WithMergeableState -> WithMergeableState
2021.07.27 10:53:32.017057 [ 30637 ] {40c14a84-24e6-486b-ac5e-c04f9c37eb94} executeQuery: Read 1 rows, 4.01 KiB in 0.881749787 sec., 1 rows/sec., 4.55 KiB/sec.
2021.07.27 10:53:32.017163 [ 30637 ] {40c14a84-24e6-486b-ac5e-c04f9c37eb94} MemoryTracker: Peak memory usage (for query): 0.00 B.
2021.07.27 10:53:31.746844 [ 24571 ] {8efca6e0-880a-4388-a5bc-8ef6508152b5} executeQuery: (from 10.141.226.164:53306, initial_query_id: 3a960287-163f-4e8e-94f3-7df0b6c6a0e3, using production parser) SELECT count() FROM sessiondb.ug_dws_bhv_bd_dau_1d_local
2021.07.27 10:53:32.072983 [ 114800 ] {bc0a8d32-7387-4a64-800d-262c9fc07c7a} ContextAccess (default): Access granted: SELECT(cuid) ON sessiondb.ug_dws_bhv_bd_dau_1d_local
2021.07.27 10:53:32.514148 [ 114800 ] {bc0a8d32-7387-4a64-800d-262c9fc07c7a} InterpreterSelectQuery: WithMergeableState -> WithMergeableState
2021.07.27 10:53:32.533677 [ 114800 ] {bc0a8d32-7387-4a64-800d-262c9fc07c7a} executeQuery: Read 1 rows, 4.01 KiB in 0.772485908 sec., 1 rows/sec., 5.19 KiB/sec.
2021.07.27 10:53:32.533872 [ 114800 ] {bc0a8d32-7387-4a64-800d-262c9fc07c7a} MemoryTracker: Peak memory usage (for query): 0.00 B.
2021.07.27 10:53:32.418777 [ 24571 ] {8efca6e0-880a-4388-a5bc-8ef6508152b5} ContextAccess (default): Access granted: SELECT(cuid) ON sessiondb.ug_dws_bhv_bd_dau_1d_local
2021.07.27 10:53:32.549235 [ 24571 ] {8efca6e0-880a-4388-a5bc-8ef6508152b5} InterpreterSelectQuery: WithMergeableState -> WithMergeableState
2021.07.27 10:53:32.560853 [ 24571 ] {8efca6e0-880a-4388-a5bc-8ef6508152b5} executeQuery: Read 1 rows, 4.01 KiB in 0.473697524 sec., 2 rows/sec., 8.46 KiB/sec.
2021.07.27 10:53:32.562133 [ 24571 ] {8efca6e0-880a-4388-a5bc-8ef6508152b5} MemoryTracker: Peak memory usage (for query): 0.00 B.
2021.07.27 10:54:03.150866 [ 69117 ] {26f26c92-ad3c-4d64-adb6-f35142c59c14} executeQuery: (from 10.141.226.164:55834, initial_query_id: 3a960287-163f-4e8e-94f3-7df0b6c6a0e3, using production parser) SELECT count() FROM sessiondb.ug_dws_bhv_bd_dau_1d_local
2021.07.27 10:54:03.150794 [ 95217 ] {59160b74-cf97-4fcd-bcb8-8c2372302e80} executeQuery: (from 10.141.226.164:62281, initial_query_id: 3a960287-163f-4e8e-94f3-7df0b6c6a0e3, using production parser) SELECT count() FROM sessiondb.ug_dws_bhv_bd_dau_1d_local
2021.07.27 10:54:04.974346 [ 69117 ] {26f26c92-ad3c-4d64-adb6-f35142c59c14} ContextAccess (default): Access granted: SELECT(cuid) ON sessiondb.ug_dws_bhv_bd_dau_1d_local
2021.07.27 10:54:06.171025 [ 69117 ] {26f26c92-ad3c-4d64-adb6-f35142c59c14} InterpreterSelectQuery: WithMergeableState -> WithMergeableState
2021.07.27 10:54:04.974390 [ 95217 ] {59160b74-cf97-4fcd-bcb8-8c2372302e80} ContextAccess (default): Access granted: SELECT(cuid) ON sessiondb.ug_dws_bhv_bd_dau_1d_local
2021.07.27 10:54:06.170943 [ 95217 ] {59160b74-cf97-4fcd-bcb8-8c2372302e80} InterpreterSelectQuery: WithMergeableState -> WithMergeableState
2021.07.27 10:54:06.666414 [ 95217 ] {59160b74-cf97-4fcd-bcb8-8c2372302e80} executeQuery: Read 1 rows, 4.01 KiB in 3.253392704 sec., 0 rows/sec., 1.23 KiB/sec.
2021.07.27 10:54:06.666484 [ 95217 ] {59160b74-cf97-4fcd-bcb8-8c2372302e80} MemoryTracker: Peak memory usage (for query): 0.00 B.
2021.07.27 10:54:06.666505 [ 69117 ] {26f26c92-ad3c-4d64-adb6-f35142c59c14} executeQuery: Read 1 rows, 4.01 KiB in 3.256510595 sec., 0 rows/sec., 1.23 KiB/sec.
2021.07.27 10:54:06.666587 [ 69117 ] {26f26c92-ad3c-4d64-adb6-f35142c59c14} MemoryTracker: Peak memory usage (for query): 0.00 B.
2021.07.27 10:54:06.746683 [ 134 ] {3a960287-163f-4e8e-94f3-7df0b6c6a0e3} Aggregator: Merging partially aggregated blocks (bucket = -1).
2021.07.27 10:54:06.754556 [ 134 ] {3a960287-163f-4e8e-94f3-7df0b6c6a0e3} Aggregator: Merged partially aggregated blocks. 1 rows, 8.00 B. in 0.007745992 sec. (129.09902308187253 rows/sec., 1.01 KiB/sec.)
2021.07.27 10:54:06.759025 [ 32761 ] {3a960287-163f-4e8e-94f3-7df0b6c6a0e3} executeQuery: Read 100 rows, 400.78 KiB in 36.645041528 sec., 2 rows/sec., 10.94 KiB/sec.**

**Comment by den-crane** [comment]
Check logs `select * from clusterAllReplicas('.clustername...', system.query_log) where initial_query_id = '{8efca6e0-880a-438.....'`
then you will see when shards got that request

**Comment by shadowDy** [comment]
@den-crane 
Do you mean to suspect that the network between driver and node has stopped for 30s.

**Comment by den-crane** [comment]
Do you mean you have found a slow shard?
Issue solved?

**Comment by shadowDy** [comment]
I've found the slow node. But I don't understand why it takes so long to wait from receiving SQL to executing

**Comment by shadowDy** [comment]
newi issue:
https://github.com/ClickHouse/ClickHouse/issues/27003
