### ISSUE TITLE
When flink write to distributed table, the disk space decrease slowly

### ISSUE THREAD

**Issue by tangxueming** [ClickHouse/ClickHouse#26734]
Flink write to distributed table(4 nodes), these nodes only received data and then send data to others (20 nodes).
 I find the disk space decrease slowly.
![image](https://user-images.githubusercontent.com/15307808/126760798-f1a728df-a04b-44fd-aa14-247d1c14f4cd.png)

 Then  I stopped flink job as 10:26 The system become unstable. 
The orange disk space is 100 gb,  others are 50 gb。
 today
![image](https://user-images.githubusercontent.com/15307808/126760857-d372d53f-41cd-4f32-ae90-d23d73f0be76.png)

yesterday
![image](https://user-images.githubusercontent.com/15307808/126760913-ce9a97da-ca51-47a1-b24d-3743a08d2698.png)
My version is 21.7. 
I find "too many parts" error on  one of storage nodes.
What should I do?

**Comment by den-crane** [comment]
Distributed table works async by default. 
You can see delayed inserts `select sum(data_files) delayed_inserts, table from clusterAllReplicas({cluster}, system.distribution_queue) group by table`

>I find "too many parts" error on one of storage nodes.

read this https://github.com/ClickHouse/ClickHouse/issues/3174#issuecomment-423435071

**Comment by tangxueming** [comment]
@den-crane  Thanks !

**Comment by tangxueming** [comment]
@den-crane 
Flink write data to distributed table in 5 nodes and then send data to shard tables in other 20 nodes.
![image](https://user-images.githubusercontent.com/15307808/130165036-8ab52cb6-2ec5-4697-889d-5342d14324fa.png)
The mostly delayed_inserts are belong to one table.
I wonder whether the value  of delayed_inserts is acceptable.
How do I find the max acceptable  delayed_inserts in my cluster?

**Comment by den-crane** [comment]
check the table `system.distribution_queue`

**Comment by tangxueming** [comment]
Thank you for your reply!
I maybe did not  describe my problem clearly.
I get delayed number  from system.distribution_queue, but I don't know whether the number is appropriate.
