### ISSUE TITLE
Some views with avg function may stop working properly after upgrade to >=21.1

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#26732]
Imagine a view was created on versions before 21.1:
```sql
CREATE VIEW foo AS SELECT avgIf(toDecimal64(1, 3),0) as x;

SHOW CREATE TABLE foo;

Row 1:
──────
statement: CREATE VIEW default.foo
(
    `x` Decimal(18, 3)
) AS
SELECT avgIf(toDecimal64(1, 3), 0) AS x

SELECT * FROM foo;
┌─────x─┐
│ 0.000 │
└───────┘
```

Now upgrade to 21.1 or newer:

```sql
SELECT * FROM foo

Received exception from server (version 21.7.4):
Code: 407. DB::Exception: Received from localhost:9000. DB::Exception: Decimal convert overflow. Cannot convert infinity or NaN to decimal: while converting source column x to destination column x: while executing 'FUNCTION CAST(x :: 2, Decimal(18, 3) :: 1) -> CAST(x, Decimal(18, 3)) Decimal(18, 3) : 0'. 
```

The reason is that after #15419 the result of `avg` changed
```sql
SELECT  version(),   toTypeName(avg(toDecimal64(1, 3)));

┌─version()─┬─toTypeName(avg(toDecimal64(1, 3)))─┐
│ 20.12.8.5 │ Decimal(18, 3)                     │
│ 21.1.9.41 │ Float64                            │
└───────────┴────────────────────────────────────┘
```

And for empty dataset it now return NaN instead of zero, and NaN can not be casted to decimal. 

One of the options to fix it - is just to recreate the view, or adjust the SELECT section replacing `avgIf` to `avgOrDefaultIf`

**Comment by filimonov** [comment]
@alexey-milovidov do you think we need to do something with that (may be we can relax casting rules for that case?), or just keep it as 'known issue with known workaround'?

**Comment by filimonov** [comment]
BTW - that looks a bit silly (we use accurate decimal division and later casting the result to Float64):
https://github.com/myrrc/ClickHouse/blob/394b81ac46c2eb9fb5e14ae8c382f90d98316ecb/src/AggregateFunctions/AggregateFunctionAvg.h#L45

**Comment by myrrc** [comment]
> BTW - that looks a bit silly (we use accurate decimal division and later casting the result to Float64):
> https://github.com/myrrc/ClickHouse/blob/394b81ac46c2eb9fb5e14ae8c382f90d98316ecb/src/AggregateFunctions/AggregateFunctionAvg.h#L45

Results would be too shifted otherwise (converting each to float and dividing them).

**Comment by den-crane** [comment]
I vote for a rolling back https://github.com/ClickHouse/ClickHouse/pull/15419 and a fixing the documentation.

**Comment by filimonov** [comment]
> I vote for a rolling back #15419 and a fixing the documentation.

Questionable

**Comment by filimonov** [comment]
Corner case when casting to floats lead to errors / losing the precision:

```sql

select version(), avg(x) from ( with 100000000000000000 as a select if(number=0, toDecimal128(a, 1) * 10000000000000, toDecimal128(a, 1) * 10000000000000 + 1000000000000) as x  from numbers(2))　;

┌─version()───┬─avg(x)─┐
│ 21.9.1.7503 │   1e30 │
└─────────────┴────────┘

┌─version()─┬────────────────────────────avg(x)─┐
│ 20.11.6.6 │ 1000000000000000000500000000000.0 │
└───────────┴───────────────────────────────────┘
```

```
select version(), avg(toDecimal64(5, 18)/10000000000000000 + 5) as x;

┌─version()───┬─x─┐
│ 21.9.1.7503 │ 5 │
└─────────────┴───┘

┌─version()─┬────────────────────x─┐
│ 20.11.6.6 │ 5.000000000000000500 │
└───────────┴──────────────────────┘
```
