### ISSUE TITLE
build clickhouse and /programs/clickhouse has generated, but I can not execute it. there has some error, include/jemalloc/internal/tsd_generic.h:145: Failed assertion: "tsd_booted" Abort trap: 6, so i don't known how to process it

### ISSUE THREAD

**Issue by LBGandREN** [ClickHouse/ClickHouse#26741]
Make sure to check documentation https://clickhouse.yandex/docs/en/ first. If the question is concise and probably has a short answer, asking it in Telegram chat https://telegram.me/clickhouse_en is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

If you still prefer GitHub issues, remove all this text and ask your question here.

**Comment by alexey-milovidov** [comment]
What kind of build do you perform?

**Comment by LBGandREN** [comment]
I used macOS bigsur 11.5;  the build command I used is 'cmake .. -DCMAKE_CXX_COMPILER=`which clang++` -DCMAKE_C_COMPILER=`which clang` -DCMAKE_BUILD_TYPE=Debug' and then used 'ninja'.

**Comment by francisoliverlee** [comment]
> I used macOS bigsur 11.5; the build command I used is 'cmake .. -DCMAKE_CXX_COMPILER=`which clang++` -DCMAKE_C_COMPILER=`which clang` -DCMAKE_BUILD_TYPE=Debug' and then used 'ninja'.

same problem build DEBUG.  i success runing: 
```
cmake .. -DCMAKE_CXX_COMPILER=which clang++ -DCMAKE_C_COMPILER=which clang
```

**Comment by alexey-milovidov** [comment]
Two options:
1. If you are ClickHouse user, don't build it by yourself, download pre-built binary (from https://clickhouse.tech/) instead.
2. If you are ClickHouse developer, you have to dig into this issue on your own.

**Comment by LBGandREN** [comment]
@francisoliverlee  
I used 'cmake .. -DCMAKE_CXX_COMPILER=which clang++ -DCMAKE_C_COMPILER=which clang'
also not success, also has the problem: 
    include/jemalloc/internal/tsd_generic.h:145: Failed assertion: "tsd_booted" Abort trap: 6
