### ISSUE TITLE
Join Table Engine with persistent=1, how to prevent running out of inodes?

### ISSUE THREAD

**Issue by pavel-naumenko** [ClickHouse/ClickHouse#26756]
## Description
Using Join table for value lookup.  
If using updates of join table (inserting new keys) - running out of inodes soon, as with each data block insert, new storage files created, however those aren't merged / cleaned like with Merge Tree tables.  
Thus even for small size table with frequent updates, can quite soon get FS limit reached. E.g. can have single record in table, while thousands of files in storage.
## Question
- Is there any option for Join table to perform cleanup of old persistence or merge storage by join key?
- Or can Dictionary engine, as alternative for such lookup, be updated to allow new key entry via INSERT not just per time reload (i.e on event basis not just via lifetime interval configuration)

## Use case
- Source data: events 
  - event_id, device_id - uniq identifiers
  - ts - timestamp  
- For each event need to store it's initial ts as ts of first event with same device_id.

- Join table 
```
        CREATE TABLE IF NOT EXISTS default.devices
        (  
            device_id String,
            ts_init DateTime
        ) ENGINE = Join(ANY, LEFT, device_id)
        SETTINGS persistent=1;
```
- Processing:
  - each time event arrives 
      - join table updated via MV with insert of device_id, ts
      - if device was already present - old record kept with init ts (join strictness=ANY, thus duplicates ignored)
      - target event table populated via another MV as event data (event_id, device_id, ts) + joined data (ts_init)
- Results [ClickHouse Version: 21.7.4.18]:
    - functionality wise everything works ok
    - however to avoid loosing device data on db restarts enabling persistence option -  then getting FS issue
    - current workaround: use for devices simple MTree table and join it; however in this case it's more suboptimal as with each data block insert from MV each time join created

### ddl
    CREATE TABLE IF NOT EXISTS default.events_source
    (  
        device_id String,
        event_id String,
        ts DateTime
    ) ENGINE = MergeTree()
    PARTITION BY toYYYYMM(ts)
    ORDER BY (ts);

    CREATE TABLE IF NOT EXISTS default.events_target
    (  
        device_id String,
        event_id String,
        ts DateTime,
        ts_init DateTime
    ) ENGINE = MergeTree()
    PARTITION BY toYYYYMM(ts)
    ORDER BY (ts);

    CREATE TABLE IF NOT EXISTS default.devices
    (  
        device_id String,
        ts_init DateTime
    ) ENGINE = Join(ANY, LEFT, device_id)
    SETTINGS persistent=1;

    CREATE MATERIALIZED VIEW IF NOT EXISTS default.devices_mv TO default.devices
    AS
    SELECT
        device_id,
        min(ts) ts_init
    FROM default.events_source
    GROUP BY device_id;

    CREATE MATERIALIZED VIEW IF NOT EXISTS default.events_mv TO default.events_target
    AS
    SELECT
        e.device_id,
        e.event_id,
        e.ts,
        if(d.ts_init > 0,  d.ts_init, e.ts) ts_init
    FROM default.events_source e
        ANY LEFT JOIN default.devices d on d.device_id = e.device_id;
###  emulate multiple inserts  
```
 for i in $(seq 10); do clickhouse-client -u default -q "INSERT INTO default.devices(device_id, ts_init) VALUES ('test-device', now())"; done
```
### verify storage keeps growing  with each entry
  ```
  DATA_PATH=$(clickhouse-client -u default -q "SELECT data_paths[1] FROM system.tables where database = 'default' AND name = 'devices'")    
  ls /var/lib/clickhouse/$DATA_PATH/*.bin | wc -l
  ```

**Comment by UnamedRus** [comment]
It's happening due each insert creates additional .bin file on disk, and those files not being merged together.

> Is there any option for Join table to perform cleanup of old persistence or merge storage by join key?

Not yet, but it could be point for feature request.

> Or can Dictionary engine, as alternative for such lookup, be updated to allow new key entry via INSERT not just per time reload (i.e on event basis not just via lifetime interval configuration)

Probably cache dictionaries could work for you.

https://clickhouse.tech/docs/en/sql-reference/dictionaries/external-dictionaries/external-dicts-dict-layout/#cache

**Comment by pavel-naumenko** [comment]
Thanks for reply.

Will have to stick with workaround then and use single joins for now. 
Hopefully some day either Join or Dict Table would be enhanced.

Cache dictionary proposal unfortunately didn't help.
By description it's ok, however during testing I've found that it doesn't work as I would expect:
- when item is found in cache - it returns cached result = OK
- when item is not in cache - it executes some sql and adds it to cache = OK
- however if item is not in cache and not found by sql - it also added to cache - thus wrong empty value returned for sequential calls (after adding real item) = NOK

### sample
- create view that would be source for dict updates
  ```  
    CREATE VIEW IF NOT EXISTS default.events_devices AS
    SELECT device_id, min(ts) as ts_init
    FROM default.events_target
    GROUP BY device_id;
  ```

- create dictionary (used complex_key_cache instead of cache as have non integer key, i.e. composite)
  ```
    CREATE DICTIONARY IF NOT EXISTS  default.devices
    (
        device_id String,
        ts_init DateTime
    )
    PRIMARY KEY device_id
    SOURCE(CLICKHOUSE(DB 'default' TABLE 'events_devices'))
    LAYOUT(complex_key_cache(SIZE_IN_CELLS 100000))
    LIFETIME(0);
  ```

- if pre-register device, dict cache is ok
  ```
    INSERT INTO default.events_target(device_id, event_id, ts)
    VALUES ('device-2', 'event-2', toDateTime('2020-01-01 01:01:01'));
    
    SELECT dictGet('default.devices', 'ts_init', tuple('device-2'));
  ```
    
- if using real case (initially device not yet in cache (new event arrives) and only for sequential events it should be added and used)
```
    - emulate non existing device call (wrong value cached)
    SELECT dictGet('default.devices', 'ts_init', tuple('device-3'));
    
    - insert real value
    INSERT INTO default.events_target(device_id, event_id, ts)
    VALUES ('device-3', 'event-3', toDateTime('2020-01-01 01:01:01'));
    
    - get devices from cache (instead of real value as from events_devices, dummy zero date returned
    SELECT dictGet('default.devices', 'ts_init', tuple('device-3'));
```

So in MV if trying to switch to dict this results that init date never populates (always current date set)
```
  CREATE MATERIALIZED VIEW IF NOT EXISTS default.events_mv TO default.events_target
    AS
    SELECT
        e.device_id,
        e.event_id,
        e.ts,
		dictGetDateTimeOrDefault('default.devices', 'ts_init', tuple(e.device_id), e.ts) ts_init
FROM default.events_source e;
```


> It's happening due each insert creates additional .bin file on disk, and those files not being merged together.
> 
> > Is there any option for Join table to perform cleanup of old persistence or merge storage by join key?
> 
> Not yet, but it could be point for feature request.
> 
> > Or can Dictionary engine, as alternative for such lookup, be updated to allow new key entry via INSERT not just per time reload (i.e on event basis not just via lifetime interval configuration)
> 
> Probably cache dictionaries could work for you.
> 
> https://clickhouse.tech/docs/en/sql-reference/dictionaries/external-dictionaries/external-dicts-dict-layout/#cache
