### ISSUE TITLE
There's no way to stop MaterializeMySQL while dumping a table 

### ISSUE THREAD

**Issue by poweroftrue** [ClickHouse/ClickHouse#26774]
There's no way to stop MaterializeMySQL while dumping a table 

**Does it reproduce on recent release?**

Yes, latest.

**How to reproduce**

* Start MaterializeMySQL on a big table.
* Try to `drop database` or `detach database` it will just freeze until the table is finished initial dump.
* Restarting Clickhouse won't work.

**Expected behavior**

To be able to stop the replication or drop the database

**Workaround**

After some testing, the only way to stop it is to kill the `FLUSH TABLES WITH READ LOCK`  query

**Comment by alexey-milovidov** [comment]
There is no workaround and MaterializeMySQL is not under active development.
