### ISSUE TITLE
FILTER clause for aggregate functions

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#26776]
See https://modern-sql.com/feature/filter
Can be implemented entirely on syntax level.

`agg(args) FILTER (WHERE expr)`
is equivalent to
`aggIf(args, expr)`

**Additional context**
If aggregate function already contains `If` modifier, exception will be thrown.

**Comment by nickitat** [comment]
@alexey-milovidov Hi, may I take this task?

**Comment by alexey-milovidov** [comment]
@nickitat Yes, it will be wonderful!

**Comment by vkingnew** [comment]
From which version support this feature?

**Comment by nickitat** [comment]
> From which version support this feature?

21.10

you could use https://fiddle.clickhouse.com/ to learn smth about different CH versions
