### ISSUE TITLE
MaterializeMySQL ENGINE  doesn't support  ON CLUSTER perftest_3shards_1replicas  grammar

### ISSUE THREAD

**Issue by hcymysql** [ClickHouse/ClickHouse#26781]
set allow_experimental_database_materialize_mysql = 1;

CREATE DATABASE test ON CLUSTER perftest_3shards_1replicas ENGINE = MaterializeMySQL('172.19.136.32:3306', 'test', 'admin','123456');

The error message is：
Received exception from server (version 21.7.4):
Code: 336. DB::Exception: Received from localhost:9000. DB::Exception: There was an error on [ck1:9000]: Code: 336, e.displayText() = DB::Exception: MaterializeMySQL is an experimental database engine. Enable allow_experimental_database_materialize_mysql to use it. (version 21.7.4.18 (official build)).

**Comment by den-crane** [comment]
MaterializeMySQL does not support sharding and replication. MaterializeMySQL is supported only on a single host.

**Comment by tavplubix** [comment]
See also #19030 and #6107
