### ISSUE TITLE
There is a problem when I use the new version to set the default password through debconf-set-Selections to automate the installation

### ISSUE THREAD

**Issue by haozz1** [ClickHouse/ClickHouse#26799]
I want to install Clickhouse automatically.
So I wrote a script to skip the input of default password (press Enter)
`
apt-get install -o Dpkg::Options::=--force-yes -y debonf-utils
`
`debconf-set-selections ./InstallClickHouse.seed`
`apt-get install -o Dpkg::Options::="-force-confold" --force-yes -y clickhouse-server=xxx clickhouse-client=xxx clickhouse-common-static=xxx
`
This works when using version 21.4.6.55 or earlier.But the script doesn't work when I use the newer version,It must manually press Enter to set the password.
Did the new version of ClickHouse change any Settings？or is there a better way to solve this problem？
Thanks a lot.

**Comment by den-crane** [comment]
You should set `DEBIAN_FRONTEND=noninteractive` 

https://askubuntu.com/a/972528

**Comment by haozz1** [comment]
> You should set `DEBIAN_FRONTEND=noninteractive`
> 
> https://askubuntu.com/a/972528

It doesn't work for me, I set `sudo DEBIAN_FRONTEND=noninteractive` but when I run the script to install ClickHouse it still stops at `Enter Password for default User:` and waits for me to press Enter manually

**Comment by haozz1** [comment]
> You should set `DEBIAN_FRONTEND=noninteractive`
> 
> https://askubuntu.com/a/972528

Thank you very much for your answer, I have solved my problem
