### ISSUE TITLE
Does clickhouse support stored procedures?

### ISSUE THREAD

**Issue by peterZhiFate** [ClickHouse/ClickHouse#26802]
In sql server, I can create a stored procedure through the following sql statement
USE AdventureWorks2012;
GO
CREATE PROCEDURE HumanResources.uspGetEmployeesTest2
     @LastName nvarchar(50),
     @FirstName nvarchar(50)
AS

     SET NOCOUNT ON;
     SELECT FirstName, LastName, Department
     FROM HumanResources.vEmployeeDepartmentHistory
     WHERE FirstName = @FirstName AND LastName = @LastName
     AND EndDate IS NULL;
GO
I tried to create a stored procedure with the same statement format but failed.

**Comment by den-crane** [comment]
Not yet. May be the next year

**Comment by peterZhiFate** [comment]
Thanks!
