### ISSUE TITLE
when exec distributed ddl， got error： can not write to ostream at offet 14

### ISSUE THREAD

**Issue by miaojianxin** [ClickHouse/ClickHouse#26825]
sometimes， I run sql like this，use the client：CREATE TABLE replicaTest on cluster distable ( label_id UInt32,  label_name String,  insert_time Date) ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard_name}/replicaTest','{replica_name}',insert_time, (label_id, insert_time), 8192);

got error, the stacktrace is as follows, the ck version is  20.8.6,   thank you
the stack is not the same as  https://github.com/ClickHouse/ClickHouse/issues/3981,  I didn't use http client.

Received exception from server (version 20.8.6):
Code: 24. DB::Exception: Received from localhost:7901. DB::Exception: Cannot write to ostream at offset 22. Stack trace:

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x1a13f46f in /data2/clickhouse_ha_test/ha_1/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xea77199 in /data2/clickhouse_ha_test/ha_1/clickhouse
2. DB::WriteBufferFromOStream::nextImpl() (.cold) @ 0x10688eea in /data2/clickhouse_ha_test/ha_1/clickhouse
3. DB::IAST::FormatSettings::writeIdentifier(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const @ 0x17cbb26e in /data2/clickhouse_ha_test/ha_1/clickhouse
4. DB::ASTIdentifier::formatImplWithoutAlias(DB::IAST::FormatSettings const&, DB::IAST::FormatState&, DB::IAST::FormatStateStacked) const @ 0x17c090cd in /data2/clickhouse_ha_test/ha_1/clickhouse
5. DB::ASTWithAlias::formatImpl(DB::IAST::FormatSettings const&, DB::IAST::FormatState&, DB::IAST::FormatStateStacked) const @ 0x17c9bd47 in /data2/clickhouse_ha_test/ha_1/clickhouse
6. DB::ASTFunction::formatImplWithoutAlias(DB::IAST::FormatSettings const&, DB::IAST::FormatState&, DB::IAST::FormatStateStacked) const @ 0x17c01899 in /data2/clickhouse_ha_test/ha_1/clickhouse
7. DB::ASTWithAlias::formatImpl(DB::IAST::FormatSettings const&, DB::IAST::FormatState&, DB::IAST::FormatStateStacked) const @ 0x17c9bd47 in /data2/clickhouse_ha_test/ha_1/clickhouse
8. DB::ASTStorage::formatImpl(DB::IAST::FormatSettings const&, DB::IAST::FormatState&, DB::IAST::FormatStateStacked) const @ 0x17bdc936 in /data2/clickhouse_ha_test/ha_1/clickhouse
9. DB::ASTCreateQuery::formatQueryImpl(DB::IAST::FormatSettings const&, DB::IAST::FormatState&, DB::IAST::FormatStateStacked) const @ 0x17bdddce in /data2/clickhouse_ha_test/ha_1/clickhouse
10. DB::ASTQueryWithOutput::formatImpl(DB::IAST::FormatSettings const&, DB::IAST::FormatState&, DB::IAST::FormatStateStacked) const @ 0x17c43363 in /data2/clickhouse_ha_test/ha_1/clickhouse
11. DB::formatAST(DB::IAST const&, std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool, bool) @ 0x17d3f37b in /data2/clickhouse_ha_test/ha_1/clickhouse
12. DB::executeDDLQueryOnCluster(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, DB::AccessRightsElements&&, bool) @ 0x16ae5163 in /data2/clickhouse_ha_test/ha_1/clickhouse
13. DB::InterpreterCreateQuery::execute() @ 0x16c50aa2 in /data2/clickhouse_ha_test/ha_1/clickhouse
14. DB::executeQueryImpl(char const*, char const*, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool, DB::ReadBuffer*) @ 0x17093ced in /data2/clickhouse_ha_test/ha_1/clickhouse
15. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool) @ 0x1709573a in /data2/clickhouse_ha_test/ha_1/clickhouse
16. DB::TCPHandler::runImpl() @ 0x177405d2 in /data2/clickhouse_ha_test/ha_1/clickhouse
17. DB::TCPHandler::run() @ 0x177412ac in /data2/clickhouse_ha_test/ha_1/clickhouse
18. Poco::Net::TCPServerConnection::start() @ 0x1a05d4a7 in /data2/clickhouse_ha_test/ha_1/clickhouse
19. Poco::Net::TCPServerDispatcher::run() @ 0x1a05d91f in /data2/clickhouse_ha_test/ha_1/clickhouse
20. Poco::PooledThread::run() @ 0x1a1dad4e in /data2/clickhouse_ha_test/ha_1/clickhouse
21. Poco::ThreadImpl::runnableEntry(void*) @ 0x1a1d6257 in /data2/clickhouse_ha_test/ha_1/clickhouse
22. start_thread @ 0x8347 in /data2/mjx/gentoo/lib64/libpthread-2.30.so
23. __clone @ 0x107fdf in /data2/mjx/gentoo/lib64/libc-2.30.so

**Comment by miaojianxin** [comment]
when this happened， the ck server run ok ，can insert data，select data ok。

**Comment by filimonov** [comment]
That looks like a timeout on the client or other disconnect visible from the server (i.e. server wants to write some data but the stream is closed).

**Comment by miaojianxin** [comment]
I open a new client， the error is there too， when restart the server， that is ok， the distributed ddl  exec ok

**Comment by miaojianxin** [comment]
the stack is here


I open a new client， the error is there too， when restart the server， that is ok， the distributed ddl executed ok.
after sevreal hours, got the same error too, when&nbsp;the distributed ddl executed.







Received exception from server (version 20.8.6):
Code: 24. DB::Exception: Received from localhost:7901. DB::Exception: Cannot write to ostream at offset 22. Stack trace:

Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator &gt; const&amp;, int) @ 0x1a13f46f in /data2/clickhouse_ha_test/ha_1/clickhouse

DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator &gt; const&amp;, int) @ 0xea77199 in /data2/clickhouse_ha_test/ha_1/clickhouse

DB::WriteBufferFromOStream::nextImpl() (.cold) @ 0x10688eea in /data2/clickhouse_ha_test/ha_1/clickhouse

DB::IAST::FormatSettings::writeIdentifier(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator &gt; const&amp;) const @ 0x17cbb26e in /data2/clickhouse_ha_test/ha_1/clickhouse

DB::ASTIdentifier::formatImplWithoutAlias(DB::IAST::FormatSettings const&amp;, DB::IAST::FormatState&amp;, DB::IAST::FormatStateStacked) const @ 0x17c090cd in /data2/clickhouse_ha_test/ha_1/clickhouse

DB::ASTWithAlias::formatImpl(DB::IAST::FormatSettings const&amp;, DB::IAST::FormatState&amp;, DB::IAST::FormatStateStacked) const @ 0x17c9bd47 in /data2/clickhouse_ha_test/ha_1/clickhouse

DB::ASTFunction::formatImplWithoutAlias(DB::IAST::FormatSettings const&amp;, DB::IAST::FormatState&amp;, DB::IAST::FormatStateStacked) const @ 0x17c01899 in /data2/clickhouse_ha_test/ha_1/clickhouse

DB::ASTWithAlias::formatImpl(DB::IAST::FormatSettings const&amp;, DB::IAST::FormatState&amp;, DB::IAST::FormatStateStacked) const @ 0x17c9bd47 in /data2/clickhouse_ha_test/ha_1/clickhouse

DB::ASTStorage::formatImpl(DB::IAST::FormatSettings const&amp;, DB::IAST::FormatState&amp;, DB::IAST::FormatStateStacked) const @ 0x17bdc936 in /data2/clickhouse_ha_test/ha_1/clickhouse

DB::ASTCreateQuery::formatQueryImpl(DB::IAST::FormatSettings const&amp;, DB::IAST::FormatState&amp;, DB::IAST::FormatStateStacked) const @ 0x17bdddce in /data2/clickhouse_ha_test/ha_1/clickhouse

DB::ASTQueryWithOutput::formatImpl(DB::IAST::FormatSettings const&amp;, DB::IAST::FormatState&amp;, DB::IAST::FormatStateStacked) const @ 0x17c43363 in /data2/clickhouse_ha_test/ha_1/clickhouse

DB::formatAST(DB::IAST const&amp;, std::__1::basic_ostream<char, std::__1::char_traits &gt;&amp;, bool, bool) @ 0x17d3f37b in /data2/clickhouse_ha_test/ha_1/clickhouse

DB::executeDDLQueryOnCluster(std::__1::shared_ptrDB::IAST const&amp;, DB::Context const&amp;, DB::AccessRightsElements&amp;&amp;, bool) @ 0x16ae5163 in /data2/clickhouse_ha_test/ha_1/clickhouse

DB::InterpreterCreateQuery::execute() @ 0x16c50aa2 in /data2/clickhouse_ha_test/ha_1/clickhouse

DB::executeQueryImpl(char const*, char const*, DB::Context&amp;, bool, DB::QueryProcessingStage::Enum, bool, DB::ReadBuffer*) @ 0x17093ced in /data2/clickhouse_ha_test/ha_1/clickhouse

DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator &gt; const&amp;, DB::Context&amp;, bool, DB::QueryProcessingStage::Enum, bool) @ 0x1709573a in /data2/clickhouse_ha_test/ha_1/clickhouse

DB::TCPHandler::runImpl() @ 0x177405d2 in /data2/clickhouse_ha_test/ha_1/clickhouse

DB::TCPHandler::run() @ 0x177412ac in /data2/clickhouse_ha_test/ha_1/clickhouse

Poco::Net::TCPServerConnection::start() @ 0x1a05d4a7 in /data2/clickhouse_ha_test/ha_1/clickhouse

Poco::Net::TCPServerDispatcher::run() @ 0x1a05d91f in /data2/clickhouse_ha_test/ha_1/clickhouse

Poco::PooledThread::run() @ 0x1a1dad4e in /data2/clickhouse_ha_test/ha_1/clickhouse

Poco::ThreadImpl::runnableEntry(void*) @ 0x1a1d6257 in /data2/clickhouse_ha_test/ha_1/clickhouse

start_thread @ 0x8347 in /data2/mjx/gentoo/lib64/libpthread-2.30.so

__clone @ 0x107fdf in /data2/mjx/gentoo/lib64/libc-2.30.so



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ClickHouse/ClickHouse"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月27日(星期二) 晚上11:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ClickHouse/ClickHouse] when exec distributed ddl， got error： can not write to ostream at offet 14 (#26825)





 
That looks like a timeout on the client or other disconnect visible from the server (i.e. server wants to write some data but the stream is closed).

**Comment by alexey-milovidov** [comment]
You are using a modified ClickHouse version.
We only support the official, unmodified versions.
