### ISSUE TITLE
HAProxy health check make clickhouse-server print 'Code:1000' error log

### ISSUE THREAD

**Issue by clowdrgn** [ClickHouse/ClickHouse#26824]
You have to provide the following information whenever possible.

**Describe the bug**

HAProxy health check make clickhouse-server print 'Code:1000' error log, but everything looks good.
![image](https://user-images.githubusercontent.com/9083547/127091542-600f4aad-6493-4d4a-a668-a085dc6834d2.png)

**Does it reproduce on recent release?**

[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)
https://github.com/ClickHouse/ClickHouse/issues/1851

**How to reproduce**

* Which ClickHouse server version to use
21.3.3.14

* Which interface to use, if matters
use haproxy health check clickhouse server status

**Expected behavior**

**Error message and/or stacktrace**

![image](https://user-images.githubusercontent.com/9083547/127091771-138ce3bc-895f-46ca-ba8a-d6fdc754fba8.png)

**Additional context**

**Comment by filimonov** [comment]
Duplicate https://github.com/ClickHouse/ClickHouse/issues/24879

**Comment by filimonov** [comment]
It's not a bug actually (everything works properly), but a usability issue (excessive logging, lot of noise in logs)

**Comment by filimonov** [comment]
Duplicate https://github.com/ClickHouse/ClickHouse/issues/23858
