### ISSUE TITLE
Code: 999. DB::Exception: Received from localhost:9000. DB::Exception: Connection loss.

### ISSUE THREAD

**Issue by AngelLittleChaochao** [ClickHouse/ClickHouse#26832]
Recently when we did ingestion to ClickHouse, we often encountered 'Connection loss' error or 'Session expired' error. Since the connection to Zookeeper is lost, the table to read only state. Now the error is very often.  It has relationship with two many znodes in Zookeeper since it was running normally before.  (I got many connection loss error, the call stack maybe different for connection loss exception.)
I only have one machine to do ingestion, other 99 machines' ingestion task has been stopped.
Here is my zookeeper environment config:
1. 11 machines in zookeeper cluster.
2. For Zookeeper each machine, 38 cores, 113GB memory.
3. Snapshot size: 3.2GB
4. Snapshot and Txnlog dumpped to SSD disk.
5. The znode count is about **11 million** 

2021.07.27 03:40:34.366333 [ 62894 ] {} <Error> prod.test: void DB::StorageReplicatedMergeTree::mergeSelectingTask(): Code: 999, e.displayText() = Coordination::Exception: /test/shard_6/block_numbers/20200711-20200711-20200711-0-0 (Connection loss), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x87f714a in /usr/bin/clickhouse
1. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error, int) @ 0x1022f905 in /usr/bin/clickhouse
2. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error) @ 0x1022fb72 in /usr/bin/clickhouse
3. ? @ 0x1024781a in /usr/bin/clickhouse
4. Coordination::ZooKeeper::finalize(bool, bool) @ 0x1026db25 in /usr/bin/clickhouse
5. Coordination::ZooKeeper::receiveThread() @ 0x10273516 in /usr/bin/clickhouse
6. ? @ 0x10278602 in /usr/bin/clickhouse
7. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x88372bf in /usr/bin/clickhouse
8. ? @ 0x883ade3 in /usr/bin/clickhouse
9. start_thread @ 0x76db in /lib/x86_64-linux-gnu/libpthread-2.27.so
10. __clone @ 0x12188f in /lib/x86_64-linux-gnu/libc-2.27.so
 (version 21.4.6.55 (official build))

**Comment by den-crane** [comment]
>11 machines in zookeeper cluster.

Suggested value is 3 node of ZK. Bigger number of ZK nodes -- worse performance.

**Comment by filimonov** [comment]
> > 11 machines in zookeeper cluster.
> 
> Suggested value is 3 node of ZK. Bigger number of ZK nodes -- worse performance.

Sometimes you may go 5 (if you want to be ready to die of 2 nodes in the ensemble simultaneously). But having more nodes is rather harmful. 

> Snapshot and Txnlog dumpped to SSD disk. 

ensure the disk is fast and not used by smth else. 
You can also try to tune JVM / garbage collector a bit. https://kb.altinity.com/altinity-kb-setup-and-maintenance/altinity-kb-zookeeper/jvm-sizes-and-garbage-collector-settings

See also https://kb.altinity.com/altinity-kb-setup-and-maintenance/altinity-kb-zookeeper/altinity-kb-proper-setup 

> The znode count is about 11 million

Sometimes it can be a sign of suboptimal schema / usage patter (especially too granular partitioning, too fast & tiny insert)
