### ISSUE TITLE
In-memory part can be written only at INSERT ?

### ISSUE THREAD

**Issue by etah000** [ClickHouse/ClickHouse#26833]
Now CH supports memory part. but strangely, those parts cannot be merged in memory.  

If users have a lot of small inserts in parallel, those small data parts could be saved and merged in memory  until the merged part's size meets "min_rows_for_compact_part". Then it is written to disks.

Actually, it throws exception "DataPartWriterInMemory supports only one write". Is there any special consideration to forbid those operations?

**Comment by amosbird** [comment]
> Actually, it throws exception "DataPartWriterInMemory supports only one write".

It's an LOGICAL_ERROR which indicates a bug. Which version do you use? Could you provide a minimal reproduceable case for us to test?

**Comment by etah000** [comment]
I used branch 21.3.  Because the default "SimpleMergeSelector" always selects  "InMemory" parts with other disk parts and the resulted part is written to disk, I changed the selector to "LevelMergeSelector“， Then CH failed to start with the above exception.  

I also found the comment "  /// You can write only one block. In-memory part can be written only at INSERT." in "MergeTreeDataDataPartWriterInMemory.h".  If I removed the `statements:`

```
void MergeTreeDataPartWriterInMemory::write(
    const Block & block, const IColumn::Permutation * permutation)
{
//    if (part_in_memory->block)
//        throw Exception("DataPartWriterInMemory supports only one write", ErrorCodes::LOGICAL_ERROR);

```
It works.

**Comment by etah000** [comment]
@amosbird  I created a pull request: https://github.com/ClickHouse/ClickHouse/pull/26954. I am still working on the integration test.

**Comment by reedycreek** [comment]
After setting min_rows_for_compact_part to 10000, the memory usage increased from 16G to 44 G in 6 hours.

![image](https://user-images.githubusercontent.com/349046/142162531-7d14d563-39d4-4b63-8485-560529de1deb.png)

**Comment by azat** [comment]
>After setting min_rows_for_compact_part to 10000, the memory usage increased from 16G to 44 G in 6 hours.

@reedycreek Looks like you have tons of InMemory parts.

Basically if there are zero changes in other parts the delta should be equal to output of this query `select formatReadableSize(sum(data_uncompressed_bytes)) from system.parts where part_type = 'InMemory'`

And is this still an issue? Or this can be closed?
