### ISSUE TITLE
Want to know why  Clickhouse/programs/server/Server.h file can use header file in src directory

### ISSUE THREAD

**Issue by Yanbuc** [ClickHouse/ClickHouse#26831]
I can't understand the code in  Clickhouse/programs/server/Server.h. 
![image](https://user-images.githubusercontent.com/28927682/127138480-fd32c87e-954c-4431-bd59-be61f51ddecd.png)

daemon/BaseDaemon.h is in src direcory, but Server.h can use it by #include<>. I search in CMakeLists.txt, but I can't find code like  "target_include_directories(clickhouse-server-lib". I want to know why Server.h can use the header file in src directory.

**Comment by alexey-milovidov** [comment]
The `src` directory is included in the header search path:

$ rg '/Server.cpp' build/compile_commands.json | grep -o -P -- '-I ?\S+'
-I/home/milovidov/work/ClickHouse/build/includes/configs
-I/home/milovidov/work/ClickHouse/base/glibc-compatibility/memcpy
**-I/home/milovidov/work/ClickHouse/src**
-I/home/milovidov/work/ClickHouse/build/src
-I/home/milovidov/work/ClickHouse/build/src/Core/include
-I/home/milovidov/work/ClickHouse/base/base/..
-I/home/milovidov/work/ClickHouse/build/base/base/..
-I/home/milovidov/work/ClickHouse/rust/skim/include
-I/home/milovidov/work/ClickHouse/contrib/cctz/include
-I/home/milovidov/work/ClickHouse/base/pcg-random/.
-I/home/milovidov/work/ClickHouse/contrib/miniselect/include
-I/home/milovidov/work/ClickHouse/contrib/zstd/lib
-I/home/milovidov/work/ClickHouse/contrib/libfarmhash
-I/home/milovidov/work/ClickHouse/src/Common/mysqlxx/.
-I/home/milovidov/work/ClickHouse/contrib/libmetrohash/src
-I/home/milovidov/work/ClickHouse/contrib/murmurhash/include
-I/home/milovidov/work/ClickHouse/rust/BLAKE3/include
