### ISSUE TITLE
Website markup is unbearable.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#26846]
1.
![Screenshot_20210719_183057](https://user-images.githubusercontent.com/18581488/127196887-ec8bd3ca-b260-4964-b205-6a060ef40426.png)

2.
![Screenshot_20210630_024744](https://user-images.githubusercontent.com/18581488/127196964-afdf352d-e8a3-433e-a196-618cdae83ea3.png)

**Comment by qoega** [comment]
Your browser version is crucial. Otherwise it will be like "can't reproduce" on another browsers.

**Comment by alexey-milovidov** [comment]
Yes, it should work in all modern browsers: Chrome, Firefox, Safari, Edge...

**Comment by alexey-milovidov** [comment]
@rfraposa this task is fixed.
