### ISSUE TITLE
(russian description) LagInFrame bug

### ISSUE THREAD

**Issue by NursultanKariev** [ClickHouse/ClickHouse#26868]
You have to provide the following information whenever possible.

**Describe the bug**

При использовании lagInFrame на таблицу, получаю странный результат

select  
   a.subscription_id, msisdn,  
   lagInFrame(deactivation_date) over (partition by subscription_id order by deactivation_date rows between unbounded preceding and unbounded following) as eff_dt,  
   deactivation_date as exp_dt  
 from test.test_msisdn a 
 where subscription_id in (3410475)

![image](https://user-images.githubusercontent.com/39010462/127263119-44b9b129-128e-4b49-b837-fe775aa38ab6.png)

Однако при использовании LagInFrame на данные, прописанные через select, результат правильный:

 select  
   id, num,  
   lagInFrame(test_dt) over (partition by id order by test_dt ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) as eff_dt,  
   test_dt as  exp_dt   from
(  select 343123 as id, 1234567 as num, '2020-02-24 17:08:59' as test_dt
 union all
 select 343123 as id, 7654321 as num, '2020-02-24 17:20:12' as test_dt); 

![image](https://user-images.githubusercontent.com/39010462/127263349-a4f13dba-95dc-4213-b0dc-c3765eee550a.png)

**Does it reproduce on recent release?**

ClickHouse server version 21.7.4.18 (official build)

**Comment by akuzm** [comment]
Есть ещё одно отличие поведения `lagInFrame` от стандартного `lag` -- вместо null возвращается значение типа данных по умолчанию. В таблице у вас тип колонки Date, значение по умолчанию 1970-01-01. C union у вас тип колонки String, значение по умолчанию -- пустая строка. В обоих случаях результат работы функции ожидаемый.

Если нужно null, с версии 21.9 можно будет писать lagInFrame(toNullable(test_dt)). Недавно исправили здесь https://github.com/ClickHouse/ClickHouse/issues/26115

**Comment by NursultanKariev** [comment]
> Есть ещё одно отличие поведения `lagInFrame` от стандартного `lag` -- вместо null возвращается значение типа данных по умолчанию. В таблице у вас тип колонки Date, значение по умолчанию 1970-01-01. C union у вас тип колонки String, значение по умолчанию -- пустая строка. В обоих случаях результат работы функции ожидаемый.
> 
> Если нужно null, с версии 21.9 можно будет писать lagInFrame(toNullable(test_dt)). Недавно исправили здесь #26115

Это понятно, но почему у второй строки eff_dt 1973-05-04, а не 2021-02-24?

**Comment by akuzm** [comment]
> Это понятно, но почему у второй строки eff_dt 1973-05-04, а не 2021-02-24?

Пришлите мне `SHOW CREATE TABLE test.test_msisdn`, попробую воспроизвести локально и разобраться.

**Comment by NursultanKariev** [comment]
> test_msisdn

 CREATE TABLE test.test_msisdn
(
    `file_dt` String,
    `file_name` String,
    `id` UInt64,
    `msisdn` Nullable(UInt64),
    `deactivation_date` Nullable(DateTime),
    `subscription_id` Nullable(UInt64),
    `last_modified` Nullable(DateTime),
    `eff_dt` Date MATERIALIZED toDate(parseDateTimeBestEffort(file_dt)),
    `load_dt` DateTime MATERIALIZED CAST(now(), 'DateTime')
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{cluster}/test/test_msisdn/{shard}', '{replica}')
PARTITION BY eff_dt
ORDER BY id
SETTINGS index_granularity = 8192

**Comment by akuzm** [comment]
```
CREATE TABLE test.test_msisdn
(
    `file_dt` String,
    `file_name` String,
    `id` UInt64,
    `msisdn` Nullable(UInt64),
    `deactivation_date` Nullable(DateTime),
    `subscription_id` Nullable(UInt64),
    `last_modified` Nullable(DateTime),
    `eff_dt` Date MATERIALIZED toDate(parseDateTimeBestEffort(file_dt)),
    `load_dt` DateTime MATERIALIZED CAST(now(), 'DateTime')
)
ENGINE = MergeTree
PARTITION BY eff_dt
ORDER BY id
SETTINGS index_granularity = 8192
;


insert into test.test_msisdn values ('2020-02-24 17:20:12', '', 343123, null, '2020-02-24 17:20:12', null, null);
insert into test.test_msisdn values ('2020-02-24 17:08:59', '', 343123, null, '2020-02-24 17:08:59', null, null);

 
 SELECT
    a.subscription_id,
    msisdn,
    lagInFrame(deactivation_date) OVER (PARTITION BY subscription_id ORDER BY deactivation_date ASC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS eff_dt,
    deactivation_date AS exp_dt
FROM test.test_msisdn AS a
;

┌─subscription_id─┬─msisdn─┬─eff_dt─┬──────────────exp_dt─┐
│            ᴺᵁᴸᴸ │   ᴺᵁᴸᴸ │   ᴺᵁᴸᴸ │ 2020-02-24 17:08:59 │
└─────────────────┴────────┴────────┴─────────────────────┘
┌─subscription_id─┬─msisdn─┬──────────────eff_dt─┬──────────────exp_dt─┐
│            ᴺᵁᴸᴸ │   ᴺᵁᴸᴸ │ 2020-02-24 17:08:59 │ 2020-02-24 17:20:12 │
└─────────────────┴────────┴─────────────────────┴─────────────────────┘
```
Что-то не получилось, вторая строка нормальная. Может данные другие нужны? Попробуйте ещё на последнем testing-релизе, возможно это поправилось вместе с исправлениями в lagInFrame для Nullable типов.

**Comment by NursultanKariev** [comment]
Исходные данные для этой выборки выглядят так:

20210225	crm#cont20210225-0001.csv	99442	996772124356	2021-02-24 17:08:59	3410475	2021-02-24 17:08:59
20210225	crm#cont20210225-0001.csv	99460	996778432123	2021-02-24 17:20:12	3410475	2021-02-24 17:20:12.

Я, конечно, попробую, просто мы вообще не используем Nullable типы для  lagInFrame, так как вылетает ошибка "too large size"

**Comment by akuzm** [comment]
С полными данными то же самое:
```
SELECT *
FROM test.test_msisdn

┌─file_dt──┬─file_name─────────────────┬────id─┬───────msisdn─┬───deactivation_date─┬─subscription_id─┬───────last_modified─┐
│ 20210225 │ crm#cont20210225-0001.csv │ 99460 │ 996778432123 │ 2021-02-24 17:20:12 │         3410475 │ 2021-02-24 17:20:12 │
└──────────┴───────────────────────────┴───────┴──────────────┴─────────────────────┴─────────────────┴─────────────────────┘
┌─file_dt──┬─file_name─────────────────┬────id─┬───────msisdn─┬───deactivation_date─┬─subscription_id─┬───────last_modified─┐
│ 20210225 │ crm#cont20210225-0001.csv │ 99442 │ 996772124356 │ 2021-02-24 17:08:59 │         3410475 │ 2021-02-24 17:08:59 │
└──────────┴───────────────────────────┴───────┴──────────────┴─────────────────────┴─────────────────┴─────────────────────┘


SELECT
    a.subscription_id,
    msisdn,
    lagInFrame(deactivation_date) OVER (PARTITION BY subscription_id ORDER BY deactivation_date ASC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS eff_dt,
    deactivation_date AS exp_dt
FROM test.test_msisdn AS a

┌─subscription_id─┬───────msisdn─┬─eff_dt─┬──────────────exp_dt─┐
│         3410475 │ 996772124356 │   ᴺᵁᴸᴸ │ 2021-02-24 17:08:59 │
└─────────────────┴──────────────┴────────┴─────────────────────┘
┌─subscription_id─┬───────msisdn─┬──────────────eff_dt─┬──────────────exp_dt─┐
│         3410475 │ 996778432123 │ 2021-02-24 17:08:59 │ 2021-02-24 17:20:12 │
└─────────────────┴──────────────┴─────────────────────┴─────────────────────┘
```

Колонка deactivation_date, от которой считаете lag, имеет тип Nullable(UInt64), так что эти изменения могли повлиять.

**Comment by NursultanKariev** [comment]
```
CREATE TABLE test.test_msisdn
(
    `file_dt` String,
    `file_name` String,
    `id` UInt64,
    `msisdn` UInt64,
    `deactivation_date` DateTime,
    `subscription_id` UInt64,
    `last_modified` DateTime,
    `eff_dt` Date MATERIALIZED toDate(parseDateTimeBestEffort(file_dt)),
    `load_dt` DateTime MATERIALIZED CAST(now(), 'DateTime')
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{cluster}/test/test_msisdn/{shard}', '{replica}')
PARTITION BY eff_dt
ORDER BY id
SETTINGS index_granularity = 8192;




select  
   a.subscription_id, msisdn,  
   lagInFrame(deactivation_date) over (partition by subscription_id order by deactivation_date) as eff_dt,  
   deactivation_date as exp_dt  
 from test.test_msisdn a 
 where subscription_id in (3410475)
```

![image](https://user-images.githubusercontent.com/39010462/127487652-afcec388-0240-4c18-80ae-5953bf1cef0a.png)


Убрал все Nullable поля, результат тот же. Наверное, мне нужно будет подождать обновления
