### ISSUE TITLE
function normalizedQueryHash question

### ISSUE THREAD

**Issue by tangxueming** [ClickHouse/ClickHouse#26877]
**Describe my question**
The function normalizedQueryHash  return different values when queries with in condition.

**Does it reproduce on recent release?**
My version is 21.7.4

**How to reproduce**
1.select normalizedQueryHash('select * from numbers(10) where number in (9)')  6037532643196110503
2.select normalizedQueryHash('select * from numbers(10) where number in (8,9,10)') 1083722354938531863
3.select normalizedQueryHash('select * from numbers(10) where number in (8,10)') 1083722354938531863
4.select normalizedQueryHash('select * from numbers(10) where number in (8,10);') 17752078657236047151

I guest that the bug also happens in system.query_log column normalized_query_hash.

**Comment by amosbird** [comment]
1.  (9)  is numeric literal instead of tuple
4. Maybe we should get rid of trailing colons.

**Comment by tangxueming** [comment]
> 1. (9)  is numeric literal instead of tuple
what's the type of (8,9,10)？
In general，sql 1，2，3 are similar， because their parameterized sqls  all are 'select * from numbers(10) where number in (?)'

**Comment by alexey-milovidov** [comment]
Tuples with single element and with multiple elements are normalized differently. That's as it is intended.
If it is not stated in the documentation - documentation should be corrected.

> Maybe we should get rid of trailing colons.

Semicolons. Yes, it will be easy to do, but also not very important. Let's do it...
