### ISSUE TITLE
COPY table1 TO table2

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#26872]
Copying tables is a very common use case. 

That command should be:
- deterministic (in terms of order of inserts, and block sizes) 
- IO optimal (not read too many files from a lot of source table partitions at once). 
- have retries (if one block fails it first retry it several times) - if target table support retries, 
- both table1 and table2 can be table functions (s3 / file / url etc).
- (maybe) can be restarted from the middle in case of failures (may require storing the state in zookeeper)
- (maybe) when both tables are distributed - do the work on shards.
- (maybe) when tables are replicated - split the work for all replica

Alternatives:
- attach all partitions https://github.com/ClickHouse/ClickHouse/issues/25223 nice if both sides share the same schema (that can be a mode of copy table) 
- `insert ... select ... ` - may require some extra efforts to do retries, to preserve the deterministic order, also without WHERE select tends to collect data from many different partitions at once. See also #26870
- clickhouse-copier - hard to set up, works only between clickhouse tables/clusters.

**Comment by alexey-milovidov** [comment]
You can do it with BACKUP and RESTORE commands.
