### ISSUE TITLE
Non-deterministic order of data flushing in INSERT ... SELECT

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#26870]
When doing idempotent retries of INSERT ... SELECT statement, then the SELECT part can return data in a different order, and duplication will happen. 

Workarounds are either setting max_threads to 1, either adding ORDER BY into the SELECT part of the query. 

Note: Not sure if we can / should do something with that in common case, the issue is opened to highlight that the issue exists and has workarounds. It's ok to close it.

**Comment by alexey-milovidov** [comment]
Please add the docs.
