### ISSUE TITLE
DB directory not mount in docker

### ISSUE THREAD

**Issue by ejaysss** [ClickHouse/ClickHouse#2690]
I need mount database folder from host, start conteiner by this command:

sudo docker run -d --name clickhouse-server1 --restart always --ulimit nofile=262144:262144 -v /data/:/var/lib/clickhouse/data yandex/clickhouse-server

After this conteiner write Restarting....

sudo docker ps
CONTAINER ID        IMAGE                                                     COMMAND                  CREATED             STATUS                          PORTS               NAMES
6ddf42d537c5        yandex/clickhouse-server   "/bin/sh -c 'exec ..."   7 seconds ago       **Restarting (70) 2** seconds ago                       clickhouse-server1

How I can mount host folder as database folder inside docker conteiner?

**Comment by ejaysss** [comment]
[username@clickhouse-server-node1 clickhouse-server]$ sudo docker run -d --name clickhouse-server1 --restart always --ulimit nofile=262144:262144 -v /data/clickhouse-server/config.xml:/etc/clickhouse-server/config.xml -v /data/clickhouse-server/data:/var/lib/clickhouse/data -v /data/clickhouse-server/log:/var/log/clickhouse-server yandex/clickhouse-server
fc855855567adf08b868463290cda60fa96999176287be38db292ea4c63ef670
[username@clickhouse-server-node1 clickhouse-server]$ sudo docker ps -as
CONTAINER ID        IMAGE                                                     COMMAND                  CREATED             STATUS                                    PORTS               NAMES                SIZE
fc855855567a        yandex/clickhouse-server   "/bin/sh -c 'exec ..."   4 seconds ago       Restarting (232) Less than a second ago                       clickhouse-server1   16.2 kB (virtual 373 MB)
[username@clickhouse-server-node1 clickhouse-server]$ sudo docker run -i --rm=true -v /data/clickhouse-server/data:/var/lib/clickhouse/data --user root --entrypoint /bin/sh yandex/clickhouse-server -c "chown -R clickhouse:clickhouse /var/lib/clickhouse /var/log/clickhouse-server"
[username@clickhouse-server-node1 clickhouse-server]$ sudo docker ps -as
CONTAINER ID        IMAGE                                                     COMMAND                  CREATED             STATUS                           PORTS               NAMES                SIZE
fc855855567a        yandex/clickhouse-server   "/bin/sh -c 'exec ..."   33 seconds ago      Restarting (232) 4 seconds ago                       clickhouse-server1   16.2 kB (virtual 373 MB)
[username@clickhouse-server-node1 clickhouse-server]$ sudo docker stop fc855855567a
fc855855567a
[username@clickhouse-server-node1 clickhouse-server]$ sudo docker stop fc855855567a
fc855855567a
[username@clickhouse-server-node1 clickhouse-server]$ sudo docker ps -as
CONTAINER ID        IMAGE                                                     COMMAND                  CREATED             STATUS                       PORTS               NAMES                SIZE
fc855855567a        yandex/clickhouse-server   "/bin/sh -c 'exec ..."   53 seconds ago      Exited (232) 6 seconds ago                       clickhouse-server1   16.2 kB (virtual 373 MB)
[username@clickhouse-server-node1 clickhouse-server]$ sudo docker start fc855855567a
fc855855567a
[username@clickhouse-server-node1 clickhouse-server]$ sudo docker ps -as
CONTAINER ID        IMAGE                                                     COMMAND                  CREATED              STATUS                                    PORTS               NAMES                SIZE
fc855855567a        yandex/clickhouse-server   "/bin/sh -c 'exec ..."   About a minute ago   Restarting (232) Less than a second ago                       clickhouse-server1   16.2 kB (virtual 373 MB)
[username@clickhouse-server-node1 clickhouse-server]$

**Comment by tuedelue** [comment]
There is an issue with your rights management. The docker container uses its internal clickhouse user and group (id 105 and id 106).
You need to make sure that the id-corresponding user/group has rw access to the folder on the host (they are most probably *not* the same).

A workaround is to create a your own docker image that aligns the clickhouse user ids to one of the host system -- in case you want to do it this way. I have once used the following Dockerfile:
```
FROM ubuntu:16.04

ARG repository="deb http://repo.yandex.ru/clickhouse/deb/stable main/"
ARG version=\*
ARG MAX_MEMORY="120000000000"

RUN grep -q sse4_2 /proc/cpuinfo && echo "SSE 4.2 supported" || echo "SSE 4.2 NOT! supported"

RUN useradd -M --system clickhouse

RUN apt-key adv --keyserver keyserver.ubuntu.com --recv E0C56BD4 && \
    mkdir -p /etc/apt/sources.list.d && \
    echo $repository | tee /etc/apt/sources.list.d/clickhouse.list && \
    apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y apt-transport-https tzdata && \
    apt-get install -y clickhouse-server-common=$version clickhouse-server-base=$version && \
    rm -rf /var/lib/apt/lists/* /var/cache/debconf && \
    apt-get clean

RUN sed -i 's,<listen_host>127.0.0.1</listen_host>,<listen_host>0.0.0.0</listen_host>,' /etc/clickhouse-server/config.xml && \
    sed -i 's,<listen_host>::1</listen_host>,,' /etc/clickhouse-server/config.xml && \
    sed -i 's,<max_memory_usage>\d+<\/max_memory_usage>,<max_memory_usage>${MAX_MEMORY}<\/max_memory_usage>,' /etc/clickhouse-server/users.xml

RUN chown -R clickhouse /etc/clickhouse-server/
ENV CLICKHOUSE_CONFIG /etc/clickhouse-server/config.xml

ENTRYPOINT exec /usr/bin/clickhouse-server --config=${CLICKHOUSE_CONFIG}

USER clickhouse

RUN id

EXPOSE 9000
```

**Comment by ntfs32** [comment]
Show your docker logs ，Check your configuration file, host selinux ，and host folder permissions，because this container run as clickhouse user
