### ISSUE TITLE
Insert error

### ISSUE THREAD

**Issue by Sallery-X** [ClickHouse/ClickHouse#26902]
You have to provide the following information whenever possible.

![image](https://user-images.githubusercontent.com/45587738/127321165-6757934a-ce49-41f9-b1e6-4052c1c2df64.png)

version: 21.3.5.42-lts

**Comment by den-crane** [comment]
21.3.5.42-lts is obsolete, there are 21.3.15.4

table DDL?
query?
clickhouse-server.log?

**Comment by Sallery-X** [comment]
> 21.3.5.42-lts is obsolete, there are 21.3.15.4
> 
> table DDL?
> query?
> clickhouse-server.log?
> API? do you use clichouse-client? or curl?
> Format? CSV ?

![image](https://user-images.githubusercontent.com/45587738/127324245-8afe8f8f-9cd9-4107-8615-24746e810df3.png)
just api insert，it's clickhouse-server.log

**Comment by den-crane** [comment]
No info. Bye.
