### ISSUE TITLE
unit test zstd_buffers, I do not get which code updates the pos in BufferBase.

### ISSUE THREAD

**Issue by wangzhen11aaa** [ClickHouse/ClickHouse#26911]
In zstd_buffers.cpp 
line 28 - 31

      for (size_t i = 0; i < n; ++i)
        {
            DB::writeIntText(i, zstd_buf); // I do not find the code which updates the pos in BufferBase, That is weird.
            DB::writeChar('\t', zstd_buf);
        }
The template function is

```
template <typename T>
void writeIntText(T x, WriteBuffer & buf)
{
    if (likely(reinterpret_cast<intptr_t>(buf.position()) + WRITE_HELPERS_MAX_INT_WIDTH < reinterpret_cast<intptr_t>(buf.buffer().end())))
        buf.position() = itoa(x, buf.position()); // After this assignment, the pos changed. Why?
    else
        detail::writeUIntTextFallback(x, buf);
}
```

I debug the code, find nothing about the updation code. Please give an advice.

**Comment by genzgd** [comment]
This appears to be just an example file in `/src/IO/examples`, it's not an actual unit test.  You appear to be correct that it fails to properly update the buffer position.   Feel free to submit a pull request if you want to update this example, which appears to be oriented toward performance.
