### ISSUE TITLE
I want to delay the materialized view of clickhouse to take effect

### ISSUE THREAD

**Issue by sangensong** [ClickHouse/ClickHouse#26942]
First, I'm insert into CH use CSV file.
 
Clickhouse's insert speed will become slower if I use materialized view. However, if I drop the materialized view, the query speed will become slowly. In my scenario, real-time requirements are not high, But can't tolerate csv file accumulation

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/3685
