### ISSUE TITLE
Implement four letter commands for `clickhouse-keeper`.

### ISSUE THREAD

**Issue by alesapin** [ClickHouse/ClickHouse#26976]
We need to implement similar commands in `clickhouse-keeper`: https://zookeeper.apache.org/doc/r3.4.8/zookeeperAdmin.html#sc_zkCommands. Not the best interface for system monitoring, but will be compatible with existing monitoring tools.

**Comment by JackyWoo** [comment]
I‘d like work on it.  Details #28649

**Comment by alexey-milovidov** [comment]
@JackyWoo It will be awesome!
