### ISSUE TITLE
"Not found column ... in block" error, when join on alias column

### ISSUE THREAD

**Issue by keepflooding** [ClickHouse/ClickHouse#26980]
**Describe the bug**

"Not found column ... in block" error, when join on alias column.

**How to reproduce**

```sql
CREATE TABLE a (
    id UInt32,
    value UInt32,
    id_alias UInt32 ALIAS id    
) ENGINE = MergeTree() ORDER BY id;

CREATE TABLE b (
    id UInt32,
    value UInt32
) ENGINE = MergeTree() ORDER BY id;

INSERT INTO a VALUES (1, 1), (2, 2), (3, 3);
INSERT INTO b VALUES (1, 4), (2, 5), (3, 6);

SELECT * FROM a JOIN b ON a.id_alias = b.id;
```

**Expected behavior**

In version 21.5.9.4 result is:

id | value | b.id | b.value
-- | -------- | ----- | ----------
1 |  1 | 1 | 4 
2 | 2 | 2 | 5 
3 | 3 | 3 | 6 

**Error message and/or stacktrace**

In version 21.7.5.29 result is:
```
SQL Error [10]: ClickHouse exception, code: 10, host: 127.0.0.1, port: 14343; Code: 10, e.displayText() = DB::Exception: Not found column id_alias in block. There are only columns: id, value (version 21.7.5.29 (official build))
```

**Comment by den-crane** [comment]
(version 21.9.1):
Code: 352. DB::Exception: Received from localhost:9000. 
DB::Exception: Column 'id' is ambiguous: While processing (id AS id_alias) = b.id. (AMBIGUOUS_COLUMN_NAME)
