### ISSUE TITLE
Как корректно добавить новый диск ?

### ISSUE THREAD

**Issue by NikolayPraydkin** [ClickHouse/ClickHouse#26994]
Начало заканчиваться место на диске, добавил второй диск(оба ssd), создал папку clickhouse внутри папки data , shadow
Далее прописал
sudo chown -R clickhouse:clickhouse clickhouse/
sudo  chmod -R 755 clickhouse/

config
....
<path>/var/lib/clickhouse/</path>

    <storage_configuration>
    	<disks>
     
		<default>
		   <keep_free_space_bytes>50387208960</keep_free_space_bytes>
		</default>

        	<dop>
            	   <path>/media/nikolai/tom870/clickhouse/</path>
        	</dop>
       
    	</disks>
    
 	<policies>
 			<default>
 			  <volumes>
 			     <default>
 	  		       <disk>default</disk>
 	  		       <disk>dop</disk>
 			     </default>
 			   </volumes>
 			  <move_factor>0.2</move_factor>
 	
 			</default>
 	
        </policies>
    </storage_configuration> 
   ...
Вроде бы заработало, но после перестарта системы кликхаус не стартует

clickhouse-server.error.log

2021.07.29 23:25:29.513906 [ 10801 ] {} <Error> Application: Caught exception while loading metadata: Code: 481, e.displayText() = DB::ErrnoException: Cannot check read access to file: /media/nikolai/tom870/clickhouse/, errno: 2, strerror: No such file or directory: Cannot attach table `system`.`asynchronous_metric_log_0` from metadata file /var/lib/clickhouse/store/d85/d85d46fc-ed0a-40bb-8666-21acf539f260/asynchronous_metric_log_0.sql from query ATTACH TABLE system.asynchronous_metric_log_0 UUID 'f8ef437e-baf8-4708-884c-f2eeb14c3c3c' (`event_date` Date, `event_time` DateTime, `event_time_microseconds` DateTime64(6), `name` String, `value` Float64) ENGINE = MergeTree PARTITION BY toYYYYMM(event_date) ORDER BY (event_date, event_time) SETTINGS index_granularity = 8192: while loading database `system` from path /var/lib/clickhouse/metadata/system, Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x8d2aa5a in /usr/bin/clickhouse
1. DB::throwFromErrnoWithPath(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int) @ 0x8d2ba49 in /usr/bin/clickhouse
2. FS::canRead(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x8d73cd4 in /usr/bin/clickhouse
3. ? @ 0xf6717bb in /usr/bin/clickhouse
4. DB::DiskFactory::create(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Poco::Util::AbstractConfiguration const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context const>) const @ 0xf6673a9 in /usr/bin/clickhouse
5. DB::DiskSelector::DiskSelector(Poco::Util::AbstractConfiguration const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context const>) @ 0xf6634bf in /usr/bin/clickhouse
6. void std::__1::allocator<DB::DiskSelector>::construct<DB::DiskSelector, Poco::Util::AbstractConfiguration const&, char const* const&, std::__1::shared_ptr<DB::Context const> >(DB::DiskSelector*, Poco::Util::AbstractConfiguration const&, char const* const&, std::__1::shared_ptr<DB::Context const>&&) @ 0xf75965f in /usr/bin/clickhouse
7. DB::Context::getDiskSelector(std::__1::lock_guard<std::__1::mutex>&) const @ 0xf7356cb in /usr/bin/clickhouse
8. DB::Context::getStoragePolicySelector(std::__1::lock_guard<std::__1::mutex>&) const @ 0xf7222dd in /usr/bin/clickhouse
9. DB::Context::getStoragePolicy(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const @ 0xf735829 in /usr/bin/clickhouse
10. DB::MergeTreeData::getStoragePolicy() const @ 0x10375735 in /usr/bin/clickhouse
11. DB::MergeTreeData::getRelativeDataPathsWithDisks() const @ 0x1037506e in /usr/bin/clickhouse
12. DB::MergeTreeData::MergeTreeData(DB::StorageID const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::StorageInMemoryMetadata const&, std::__1::shared_ptr<DB::Context>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::MergeTreeData::MergingParams const&, std::__1::unique_ptr<DB::MergeTreeSettings, std::__1::default_delete<DB::MergeTreeSettings> >, bool, bool, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>) @ 0x1036b61e in /usr/bin/clickhouse
13. DB::StorageMergeTree::StorageMergeTree(DB::StorageID const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::StorageInMemoryMetadata const&, bool, std::__1::shared_ptr<DB::Context>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::MergeTreeData::MergingParams const&, std::__1::unique_ptr<DB::MergeTreeSettings, std::__1::default_delete<DB::MergeTreeSettings> >, bool) @ 0x100b4bc0 in /usr/bin/clickhouse
14. ? @ 0x1059c818 in /usr/bin/clickhouse
15. DB::StorageFactory::get(DB::ASTCreateQuery const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, std::__1::shared_ptr<DB::Context>, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, bool) const @ 0x1002d481 in /usr/bin/clickhouse
16. DB::createTableFromAST(DB::ASTCreateQuery, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool) @ 0xf63f05c in /usr/bin/clickhouse
17. ? @ 0xf63d6f3 in /usr/bin/clickhouse
18. ? @ 0xf63e77f in /usr/bin/clickhouse
19. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0x8d6e638 in /usr/bin/clickhouse
20. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()&&...)::'lambda'()::operator()() @ 0x8d701df in /usr/bin/clickhouse
21. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x8d6b91f in /usr/bin/clickhouse
22. ? @ 0x8d6f203 in /usr/bin/clickhouse
23. start_thread @ 0x9609 in /lib/x86_64-linux-gnu/libpthread-2.31.so
24. /build/glibc-eX1tMB/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:97: __GI___clone @ 0x122293 in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.31.so
 (version 21.7.4.18 (official build))
2021.07.29 23:25:29.515548 [ 10801 ] {} <Error> Application: DB::ErrnoException: Cannot check read access to file: /media/nikolai/tom870/clickhouse/, errno: 2, strerror: No such file or directory: Cannot attach table `system`.`asynchronous_metric_log_0` from metadata file /var/lib/clickhouse/store/d85/d85d46fc-ed0a-40bb-8666-21acf539f260/asynchronous_metric_log_0.sql from query ATTACH TABLE system.asynchronous_metric_log_0 UUID 'f8ef437e-baf8-4708-884c-f2eeb14c3c3c' (`event_date` Date, `event_time` DateTime, `event_time_microseconds` DateTime64(6), `name` String, `value` Float64) ENGINE = MergeTree PARTITION BY toYYYYMM(event_date) ORDER BY (event_date, event_time) SETTINGS index_granularity = 8192: while loading database `system` from path /var/lib/clickhouse/metadata/system
2021.07.29 23:26:00.003484 [ 10871 ] {} <Error> Application: Caught exception while loading metadata: Code: 481, e.displayText() = DB::ErrnoException: Cannot check read access to file: /media/nikolai/tom870/clickhouse/, errno: 2, strerror: No such file or directory: Cannot attach table `system`.`asynchronous_metric_log_0` from metadata file /var/lib/clickhouse/store/d85/d85d46fc-ed0a-40bb-8666-21acf539f260/asynchronous_metric_log_0.sql from query ATTACH TABLE system.asynchronous_metric_log_0 UUID 'f8ef437e-baf8-4708-884c-f2eeb14c3c3c' (`event_date` Date, `event_time` DateTime, `event_time_microseconds` DateTime64(6), `name` String, `value` Float64) ENGINE = MergeTree PARTITION BY toYYYYMM(event_date) ORDER BY (event_date, event_time) SETTINGS index_granularity = 8192: while loading database `system` from path /var/lib/clickhouse/metadata/system, Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x8d2aa5a in /usr/bin/clickhouse
1. DB::throwFromErrnoWithPath(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int) @ 0x8d2ba49 in /usr/bin/clickhouse
2. FS::canRead(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x8d73cd4 in /usr/bin/clickhouse
3. ? @ 0xf6717bb in /usr/bin/clickhouse
4. DB::DiskFactory::create(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Poco::Util::AbstractConfiguration const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context const>) const @ 0xf6673a9 in /usr/bin/clickhouse
5. DB::DiskSelector::DiskSelector(Poco::Util::AbstractConfiguration const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context const>) @ 0xf6634bf in /usr/bin/clickhouse
6. void std::__1::allocator<DB::DiskSelector>::construct<DB::DiskSelector, Poco::Util::AbstractConfiguration const&, char const* const&, std::__1::shared_ptr<DB::Context const> >(DB::DiskSelector*, Poco::Util::AbstractConfiguration const&, char const* const&, std::__1::shared_ptr<DB::Context const>&&) @ 0xf75965f in /usr/bin/clickhouse
7. DB::Context::getDiskSelector(std::__1::lock_guard<std::__1::mutex>&) const @ 0xf7356cb in /usr/bin/clickhouse
8. DB::Context::getStoragePolicySelector(std::__1::lock_guard<std::__1::mutex>&) const @ 0xf7222dd in /usr/bin/clickhouse
9. DB::Context::getStoragePolicy(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const @ 0xf735829 in /usr/bin/clickhouse
10. DB::MergeTreeData::getStoragePolicy() const @ 0x10375735 in /usr/bin/clickhouse
11. DB::MergeTreeData::getRelativeDataPathsWithDisks() const @ 0x1037506e in /usr/bin/clickhouse
12. DB::MergeTreeData::MergeTreeData(DB::StorageID const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::StorageInMemoryMetadata const&, std::__1::shared_ptr<DB::Context>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::MergeTreeData::MergingParams const&, std::__1::unique_ptr<DB::MergeTreeSettings, std::__1::default_delete<DB::MergeTreeSettings> >, bool, bool, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>) @ 0x1036b61e in /usr/bin/clickhouse
13. DB::StorageMergeTree::StorageMergeTree(DB::StorageID const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::StorageInMemoryMetadata const&, bool, std::__1::shared_ptr<DB::Context>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::MergeTreeData::MergingParams const&, std::__1::unique_ptr<DB::MergeTreeSettings, std::__1::default_delete<DB::MergeTreeSettings> >, bool) @ 0x100b4bc0 in /usr/bin/clickhouse
14. ? @ 0x1059c818 in /usr/bin/clickhouse
15. DB::StorageFactory::get(DB::ASTCreateQuery const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, std::__1::shared_ptr<DB::Context>, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, bool) const @ 0x1002d481 in /usr/bin/clickhouse
16. DB::createTableFromAST(DB::ASTCreateQuery, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool) @ 0xf63f05c in /usr/bin/clickhouse
17. ? @ 0xf63d6f3 in /usr/bin/clickhouse
18. ? @ 0xf63e77f in /usr/bin/clickhouse
19. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0x8d6e638 in /usr/bin/clickhouse
20. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()&&...)::'lambda'()::operator()() @ 0x8d701df in /usr/bin/clickhouse
21. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x8d6b91f in /usr/bin/clickhouse
22. ? @ 0x8d6f203 in /usr/bin/clickhouse
23. start_thread @ 0x9609 in /lib/x86_64-linux-gnu/libpthread-2.31.so
24. /build/glibc-eX1tMB/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:97: __GI___clone @ 0x122293 in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.31.so
 (version 21.7.4.18 (official build))

**Comment by den-crane** [comment]
что если удалить из конфига кусок `<default> <keep_free_space_bytes>50387208960</keep_free_space_bytes> </default>`

**Comment by NikolayPraydkin** [comment]
тоже самое 
2021.07.30 23:51:01.531058 [ 22942 ] {} <Error> Application: Caught exception while loading metadata: Code: 481, e.displayText() = DB::ErrnoException: Cannot check read access to file: /media/nikolai/tom870/clickhouse/, errno: 2, strerror: No such file or directory: Cannot attach table `system`.`asynchronous_metric_log` from metadata file /var/lib/clickhouse/store/d85/d85d46fc-ed0a-40bb-8666-21acf539f260/asynchronous_metric_log.sql from query ATTACH TABLE system.asynchronous_metric_log UUID '3a0f3030-bfa2-4ebe-ba0f-3030bfa27ebe' (`event_date` Date, `event_time` DateTime, `event_time_microseconds` DateTime64(6), `name` LowCardinality(String), `value` Float64) ENGINE = MergeTree PARTITION BY toYYYYMM(event_date) ORDER BY (event_date, event_time) SETTINGS index_granularity = 8192: while loading database `system` from path /var/lib/clickhouse/metadata/system, Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x8d2aa5a in /usr/bin/clickhouse
1. DB::throwFromErrnoWithPath(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int) @ 0x8d2ba49 in /usr/bin/clickhouse
2. FS::canRead(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x8d73cd4 in /usr/bin/clickhouse
3. ? @ 0xf6717bb in /usr/bin/clickhouse
4. DB::DiskFactory::create(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Poco::Util::AbstractConfiguration const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context const>) const @ 0xf6673a9 in /usr/bin/clickhouse
5. DB::DiskSelector::DiskSelector(Poco::Util::AbstractConfiguration const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context const>) @ 0xf6634bf in /usr/bin/clickhouse
6. void std::__1::allocator<DB::DiskSelector>::construct<DB::DiskSelector, Poco::Util::AbstractConfiguration const&, char const* const&, std::__1::shared_ptr<DB::Context const> >(DB::DiskSelector*, Poco::Util::AbstractConfiguration const&, char const* const&, std::__1::shared_ptr<DB::Context const>&&) @ 0xf75965f in /usr/bin/clickhouse
7. DB::Context::getDiskSelector(std::__1::lock_guard<std::__1::mutex>&) const @ 0xf7356cb in /usr/bin/clickhouse
8. DB::Context::getStoragePolicySelector(std::__1::lock_guard<std::__1::mutex>&) const @ 0xf7222dd in /usr/bin/clickhouse
9. DB::Context::getStoragePolicy(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const @ 0xf735829 in /usr/bin/clickhouse
10. DB::MergeTreeData::getStoragePolicy() const @ 0x10375735 in /usr/bin/clickhouse

**Comment by NikolayPraydkin** [comment]
похоже проблема не в кликхаусе, а в том что  после перезапуска диск оказывался отмонтированным.
