### ISSUE TITLE
Node time-consuming long tail problem

### ISSUE THREAD

**Issue by shadowDy** [ClickHouse/ClickHouse#27003]
View system.query_log information:
`Query id: f31110f6-123a-4b98-8cb8-0534789f1546

Row 1:
──────
type:                          QueryStart
event_date:                    2021-07-30
event_time:                    2021-07-30 14:29:14
event_time_microseconds:       2021-07-30 14:29:14.278350
query_start_time:              2021-07-30 14:29:14
query_start_time_microseconds: 2021-07-30 14:29:14.278350`

`Row 2:
──────
type:                          QueryFinish
event_date:                    2021-07-30
event_time:                    2021-07-30 14:29:27
event_time_microseconds:       2021-07-30 14:29:27.228829
query_start_time:              2021-07-30 14:29:14
query_start_time_microseconds: 2021-07-30 14:29:14.278350
query_duration_ms:             3867
read_rows:                     1
read_bytes:                    4104`

Although query_ duration_ The MS value is not very high (actually it is also a long tail), but what is more prominent is the time-consuming from receiving SQL to starting execution, and there is no clue in the log. How to fix this problem.

**Comment by den-crane** [comment]
```
Row 1:
──────
type: QueryStart
event_time_microseconds:       2021-07-30 14:29:14.278350


Row 2: 
────── 
type: QueryFinish 
event_time_microseconds:       2021-07-30 14:29:27.228829
query_start_time_microseconds: 2021-07-30 14:29:14.278350 
query_duration_ms: 3867 
read_rows: 1 read_bytes: 4104

```

Is it from node-initiator? or node-executor?
Can you share normal query_log from several nodes? node-initiator and the long tale executor?

**Comment by shadowDy** [comment]
> ```
> Row 1:
> ──────
> type: QueryStart
> event_time_microseconds:       2021-07-30 14:29:14.278350
> 
> 
> Row 2: 
> ────── 
> type: QueryFinish 
> event_time_microseconds:       2021-07-30 14:29:27.228829
> query_start_time_microseconds: 2021-07-30 14:29:14.278350 
> query_duration_ms: 3867 
> read_rows: 1 read_bytes: 4104
> ```
> 
> Is it from node-initiator? or node-executor?
node executor.

> Can you share normal query_log from several nodes? node-initiator and the long tale executor at least?
I can share another similar case log：
After adding the tracing log：（set send_logs_level='trace';）
the nodes that take the longest time (return the latest) are linked to the completed log as follows:

2021.07.30 16:54:10.872338 [ 354 ] {571e2634-e992-454e-8b4d-9daaae31b256} <Trace> Connection (10.141.238.225:7270): Connecting. Database: (not specified). User: default
2021.07.30 16:54:15.371469 [ 354 ] {571e2634-e992-454e-8b4d-9daaae31b256} <Trace> Connection (10.141.238.225:7270): Connected to ClickHouse server version 21.1.2.
2021.07.30 16:54:33.192186 [ 5376 ] {ef33a41d-8f2c-4884-8eb6-656e1a2bd773} <Debug> executeQuery: (from 10.141.238.226:59874, initial_query_id: 571e2634-e992-454e-8b4d-9daaae31b256, using production parser) SELECT count() FROM sessiondb.ug_dws_bhv_bd_dau_1retain_1d_local
2021.07.30 16:54:34.406999 [ 5376 ] {ef33a41d-8f2c-4884-8eb6-656e1a2bd773} <Trace> ContextAccess (default): Access granted: SELECT(cuid) ON sessiondb.ug_dws_bhv_bd_dau_1retain_1d_local
 2021.07.30 16:54:35.096166 [ 5376 ] {ef33a41d-8f2c-4884-8eb6-656e1a2bd773} <Trace> InterpreterSelectQuery: WithMergeableState -> WithMergeableState
2021.07.30 16:54:35.464486 [ 5376 ] {ef33a41d-8f2c-4884-8eb6-656e1a2bd773} <Information> executeQuery: Read 1 rows, 4.01 KiB in 1.810029764 sec., 0 rows/sec., 2.21 KiB/sec.
2021.07.30 16:54:35.464539 [ 5376 ] {ef33a41d-8f2c-4884-8eb6-656e1a2bd773} <Debug> MemoryTracker: Peak memory usage (for query): 0.00 B.
2021.07.30 16:54:35.536558 [ 354 ] {571e2634-e992-454e-8b4d-9daaae31b256} <Trace> Aggregator: Merging partially aggregated blocks (bucket = -1).
2021.07.30 16:54:35.681053 [ 354 ] {571e2634-e992-454e-8b4d-9daaae31b256} <Trace> Aggregator: Merged partially aggregated blocks. 1 rows, 8.00 B. in 0.134060687 sec. (7.459308335485406 rows/sec., 59.67 B/sec.)
┌─────count()─┐
│ 44203894789 │
└─────────────┘
2021.07.30 16:54:35.684267 [ 68796 ] {571e2634-e992-454e-8b4d-9daaae31b256} <Information> executeQuery: Read 100 rows, 400.78 KiB in 25.104337986 sec., 3 rows/sec., 15.96 KiB/sec.
2021.07.30 16:54:35.684371 [ 68796 ] {571e2634-e992-454e-8b4d-9daaae31b256} <Debug> MemoryTracker: Peak memory usage (for query): 4.26 MiB.

It takes 5S from initiating connecting to connected.
It takes 18S from connected to node executeQuery.
It takes 1.810029764s from executeQuery to finish;

**Comment by shadowDy** [comment]
> Can you share normal query_log from several nodes? node-initiator and the long tale executor at least?

executor query_log：
`
Row 1:
──────
type:                          QueryStart
event_date:                    2021-07-30
event_time:                    2021-07-30 16:54:33
event_time_microseconds:       2021-07-30 16:54:33.006769
query_start_time:              2021-07-30 16:54:33
query_start_time_microseconds: 2021-07-30 16:54:33.006769
`
`
Row 2:
──────
type:                          QueryFinish
event_date:                    2021-07-30
event_time:                    2021-07-30 16:54:35
event_time_microseconds:       2021-07-30 16:54:35.464453
query_start_time:              2021-07-30 16:54:33
query_start_time_microseconds: 2021-07-30 16:54:33.006769
query_duration_ms:             1810
read_rows:                     1
read_bytes:                    4104
written_rows:                  0
written_bytes:                 0
result_rows:                   1
result_bytes:                  8192
memory_usage:                  0
current_database:              default
query:                         SELECT count() FROM sessiondb.ug_dws_bhv_1retain_1d_local
normalized_query_hash:         15410111270351225339
query_kind:                    Select
databases:                     []
tables:                        []
columns:                       []
exception_code:                0
exception:
stack_trace:
is_initial_query:              0
user:                          default
query_id:                      ef33a41d-8f2c-4884-8eb6-656e1a2bd773
initial_user:                  ck_writer
initial_query_id:              571e2634-e992-454e-8b4d-9daaae31b256
`

driver query_log：

`
Row 1:
──────
type:                          QueryStart
event_date:                    2021-07-30
event_time:                    2021-07-30 16:54:10
event_time_microseconds:       2021-07-30 16:54:10.431850
query_start_time:              2021-07-30 16:54:10
query_start_time_microseconds: 2021-07-30 16:54:10.431850
query_duration_ms:             0
read_rows:                     0
`

`
Row 2:
──────
type:                          QueryFinish
event_date:                    2021-07-30
event_time:                    2021-07-30 16:54:35
event_time_microseconds:       2021-07-30 16:54:35.684222
query_start_time:              2021-07-30 16:54:10
query_start_time_microseconds: 2021-07-30 16:54:10.431850
query_duration_ms:             25104
read_rows:                     100
read_bytes:                    410400
written_rows:                  0
written_bytes:                 0
result_rows:                   1
result_bytes:                  64
memory_usage:                  4471333
current_database:              default
query:                         select count() from ug_dws_bhv_1retain_1d;
normalized_query_hash:         687913349225529823
query_kind:                    Select
databases:                     ['default']
tables:                        ['default.ug_dws_bhv_1retain_1d']
columns:                       ['default.ug_dws_bhv_1retain_1d.is_matrix_new']
exception_code:                0
exception:
stack_trace:
is_initial_query:              1
query_id:                      571e2634-e992-454e-8b4d-9daaae31b256
initial_query_id:              571e2634-e992-454e-8b4d-9daaae31b256
`

**Comment by shadowDy** [comment]
> > ```
> > Row 1:
> > ──────
> > type: QueryStart
> > event_time_microseconds:       2021-07-30 14:29:14.278350
> > 
> > 
> > Row 2: 
> > ────── 
> > type: QueryFinish 
> > event_time_microseconds:       2021-07-30 14:29:27.228829
> > query_start_time_microseconds: 2021-07-30 14:29:14.278350 
> > query_duration_ms: 3867 
> > read_rows: 1 read_bytes: 4104
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Is it from node-initiator? or node-executor?
> 
> node executor.
> 
> > Can you share normal query_log from several nodes? node-initiator and the long tale executor at least?
> 
> executor query_log:
> `Row 2: ────── type: QueryFinish event_date: 2021-07-30 event_time: 2021-07-30 14:29:27 event_time_microseconds: 2021-07-30 14:29:27.228829 query_start_time: 2021-07-30 14:29:14 query_start_time_microseconds: 2021-07-30 14:29:14.278350 query_duration_ms: 3867 read_rows: 1 read_bytes: 4104 written_rows: 0 written_bytes: 0 result_rows: 1 result_bytes: 8192 memory_usage: 0 current_database: default query: SELECT count() FROM sessiondb.ug_dws_bhv_1retain_1d_local normalized_query_hash: 15410111270351225339 query_kind: Select databases: [] tables: [] columns: [] exception_code: 0 exception: stack_trace: is_initial_query: 0 query_id: faf06fd2-208a-43be-9018-06c96ef8caa6 initial_query_id: b91d6610-3458-443a-80cf-85d2f8d2ad21`
> 
> driver query_log:
> `Row 2: ────── type: QueryFinish event_date: 2021-07-30 event_time: 2021-07-30 14:29:27 event_time_microseconds: 2021-07-30 14:29:27.273753 query_start_time: 2021-07-30 14:29:10 query_start_time_microseconds: 2021-07-30 14:29:10.808896 query_duration_ms: 16423 read_rows: 100 read_bytes: 410400 written_rows: 0 written_bytes: 0 result_rows: 1 result_bytes: 64 memory_usage: 31070389 current_database: default query: select count() from ug_dws_bhv_1retain_1d; normalized_query_hash: 687913349225529823 query_kind: Select databases: ['default'] tables: ['default.ug_dws_bhv_1retain_1d'] columns: ['default.ug_dws_bhv_1retain_1d.is_matrix_new'] exception_code: 0 exception: stack_trace: is_initial_query: 1 query_id: b91d6610-3458-443a-80cf-85d2f8d2ad21 initial_query_id: b91d6610-3458-443a-80cf-85d2f8d2ad21`
> 
> by the way
> I can share another similar case log：
> After adding the tracing log：（set send_logs_level='trace';）
> the nodes that take the longest time (return the latest) are linked to the completed log as follows:
> 
> `2021.07.30 16:54:10.872338 [ 354 ] {571e2634-e992-454e-8b4d-9daaae31b256} <Trace> Connection (10.141.238.225:7270): Connecting. Database: (not specified). User: default 2021.07.30 16:54:15.371469 [ 354 ] {571e2634-e992-454e-8b4d-9daaae31b256} <Trace> Connection (10.141.238.225:7270): Connected to ClickHouse server version 21.1.2. 2021.07.30 16:54:33.192186 [ 5376 ] {ef33a41d-8f2c-4884-8eb6-656e1a2bd773} <Debug> executeQuery: (from 10.141.238.226:59874, initial_query_id: 571e2634-e992-454e-8b4d-9daaae31b256, using production parser) SELECT count() FROM sessiondb.ug_dws_bhv_1retain_1d_local 2021.07.30 16:54:34.406999 [ 5376 ] {ef33a41d-8f2c-4884-8eb6-656e1a2bd773} <Trace> ContextAccess (default): Access granted: SELECT(cuid) ON sessiondb.ug_dws_bhv_1retain_1d_local 2021.07.30 16:54:35.096166 [ 5376 ] {ef33a41d-8f2c-4884-8eb6-656e1a2bd773} <Trace> InterpreterSelectQuery: WithMergeableState -> WithMergeableState 2021.07.30 16:54:35.464486 [ 5376 ] {ef33a41d-8f2c-4884-8eb6-656e1a2bd773} <Information> executeQuery: Read 1 rows, 4.01 KiB in 1.810029764 sec., 0 rows/sec., 2.21 KiB/sec. 2021.07.30 16:54:35.464539 [ 5376 ] {ef33a41d-8f2c-4884-8eb6-656e1a2bd773} <Debug> MemoryTracker: Peak memory usage (for query): 0.00 B. 2021.07.30 16:54:35.536558 [ 354 ] {571e2634-e992-454e-8b4d-9daaae31b256} <Trace> Aggregator: Merging partially aggregated blocks (bucket = -1). 2021.07.30 16:54:35.681053 [ 354 ] {571e2634-e992-454e-8b4d-9daaae31b256} <Trace> Aggregator: Merged partially aggregated blocks. 1 rows, 8.00 B. in 0.134060687 sec. (7.459308335485406 rows/sec., 59.67 B/sec.) 2021.07.30 16:54:35.684267 [ 68796 ] {571e2634-e992-454e-8b4d-9daaae31b256} <Information> executeQuery: Read 100 rows, 400.78 KiB in 25.104337986 sec., 3 rows/sec., 15.96 KiB/sec. 2021.07.30 16:54:35.684371 [ 68796 ] {571e2634-e992-454e-8b4d-9daaae31b256} <Debug> MemoryTracker: Peak memory usage (for query): 4.26 MiB.`
> 
> It takes 5S from initiating connecting to connected.
> It takes 18S from connected to node executeQuery.
> It takes 1.810029764s from executeQuery to finish;
> 
> executor query_log：
> `Row 1: ────── type: QueryStart event_date: 2021-07-30 event_time: 2021-07-30 16:54:33 event_time_microseconds: 2021-07-30 16:54:33.006769 query_start_time: 2021-07-30 16:54:33 query_start_time_microseconds: 2021-07-30 16:54:33.006769`
> `Row 2: ────── type: QueryFinish event_date: 2021-07-30 event_time: 2021-07-30 16:54:35 event_time_microseconds: 2021-07-30 16:54:35.464453 query_start_time: 2021-07-30 16:54:33 query_start_time_microseconds: 2021-07-30 16:54:33.006769 query_duration_ms: 1810 read_rows: 1 read_bytes: 4104 written_rows: 0 written_bytes: 0 result_rows: 1 result_bytes: 8192 memory_usage: 0 current_database: default query: SELECT count() FROM sessiondb.ug_dws_bhv_1retain_1d_local normalized_query_hash: 15410111270351225339 query_kind: Select databases: [] tables: [] columns: [] exception_code: 0 exception: stack_trace: is_initial_query: 0 user: default query_id: ef33a41d-8f2c-4884-8eb6-656e1a2bd773 initial_user: ck_writer initial_query_id: 571e2634-e992-454e-8b4d-9daaae31b256`
> 
> driver query_log：
> 
> `Row 1: ────── type: QueryStart event_date: 2021-07-30 event_time: 2021-07-30 16:54:10 event_time_microseconds: 2021-07-30 16:54:10.431850 query_start_time: 2021-07-30 16:54:10 query_start_time_microseconds: 2021-07-30 16:54:10.431850 query_duration_ms: 0 read_rows: 0`
> 
> `
> Row 2:
> ──────
> type: QueryFinish
> event_date: 2021-07-30
> event_time: 2021-07-30 16:54:35
> event_time_microseconds: 2021-07-30 16:54:35.684222
> query_start_time: 2021-07-30 16:54:10
> query_start_time_microseconds: 2021-07-30 16:54:10.431850
> query_duration_ms: 25104
> read_rows: 100
> read_bytes: 410400
> written_rows: 0
> written_bytes: 0
> result_rows: 1
> result_bytes: 64
> memory_usage: 4471333
> current_database: default
> query: select count() from ug_dws_bhv_1retain_1d;
> normalized_query_hash: 687913349225529823
> query_kind: Select
> databases: ['default']
> tables: ['default.ug_dws_bhv_1retain_1d']
> columns: ['default.ug_dws_bhv_1retain_1d.is_matrix_new']
> exception_code: 0
> exception:
> stack_trace:
> is_initial_query: 1
> query_id: 571e2634-e992-454e-8b4d-9daaae31b256
> initial_query_id: 571e2634-e992-454e-8b4d-9daaae31b256

**Comment by Algunenano** [comment]
Not possible to debug with the information and it's a really old release. It's possible that the remote query was created after analysis but not executed until the pipeline reached that point. Well, in this case we didn't have pipelines yet and it was datastreams, so another reason to verify in a more recent release.
