### ISSUE TITLE
Select with DateTime64 scan all table without partitioning

### ISSUE THREAD

**Issue by ADovgalyuk** [ClickHouse/ClickHouse#27005]
I've got a table with DateTime64 column:
```
`date_time` DateTime64(3)
```
and following params:
```
ENGINE = ReplacingMergeTree
PARTITION BY toDate(date_time)
ORDER BY (date_time,  host, session_id)
```
When I'm using toDateTime in where clause only partitions whith appropriate date are being scanned
```
SELECT count()
FROM grameen_http_cdr
WHERE toDateTime(date_time) >= toDateTime(1627279320)

Query id: 2029a447-b8a9-4dd2-bd8e-b967ff3ec71b

┌───count()─┐
│ 603959607 │
└───────────┘

1 rows in set. Elapsed: 2.090 sec. Processed 603.96 million rows, 4.83 GB (288.97 million rows/s., 2.31 GB/s.) 
```
But when toDateTime64 filter is used, all table is scanned, not respecting toDate(date_time)  partitioning.
```
SELECT count()
FROM http_cdr
WHERE toDateTime64(date_time, 3) >= toDateTime64(1627279320, 3)

Query id: 2514d7ca-3679-47bc-87a8-6ff82f5b8278

┌───count()─┐
│ 603880825 │
└───────────┘

1 rows in set. Elapsed: 7.834 sec. Processed 2.40 billion rows, 19.20 GB (306.38 million rows/s., 2.45 GB/s.) 
```
Why toDateTime64 filter doesn't respect partitioning?

**CH version** 21.4.6 revision 54447

**Comment by den-crane** [comment]
You do understand that you can omit `toDateTime64(..., 3)` and simply use `date_time >= toDateTime64(1627279320, 3)`?

repro
```
create table testdt64pp(date_time DateTime64(3), x String) 
Engine=MergeTree 
  partition by toDate(date_time) 
   order by date_time;

insert into testdt64pp select toDateTime64('2020-01-01 00:00:00.000',3)+number , '' from numbers(1000000);

SELECT count()　FROM testdt64pp WHERE toDateTime64(date_time,3) >= toDateTime64('2020-01-10 00:00:00.000',3);
Processed 1.00 million rows

SELECT count()　FROM testdt64pp WHERE date_time >= toDateTime64('2020-01-10 00:00:00.000',3);
Processed 222.40 thousand rows
```

**Comment by ADovgalyuk** [comment]
Yes, i do understand that I have some workaround ways. The main thing initially was about clickhouse plugin for grafana which transform:
```
WHERE
    $timeFilter
```
to 
```
 toDateTime64(date_time, 3) >= toDateTime64(1627648197, 3)
```
Using Column:DateTime64. But i can't state that as an issue, since CH still should work as usual in my opinion. At least it's not an obvious behavior for me.

**Comment by UnamedRus** [comment]
Can you check as workaround

```
WHERE
    $timeFilter
```

Can be replaced with

```
WHERE
    $dateTimeCol BETWEEN toDateTime64($from,3) AND toDateTime64($to,3) 
```

**Comment by filimonov** [comment]
https://github.com/ClickHouse/ClickHouse/pull/32240 ?

**Comment by zvonand** [comment]
The partitioning is not respected due to unknown monotonicity -- it cannot be specified for `toDateTime64()` function, as it is basicaly a `toDecimal64()`, and `toDecimal...()` have unknown monotonicity and have more than one argument, so monotonicity cannot be specified.


I.e. we have the same behavior for `Decimal64`:

Create and populate a table similar to above example:
```sql
CREATE TABLE testdt64pp2
(
    `dec` Decimal64(3),
    `x` String
)
ENGINE = MergeTree
PARTITION BY dec > 500000
ORDER BY dec

Ok.


INSERT INTO testdt64pp2 SELECT
    toDecimal64(0, 3) + number,
    ''
FROM numbers(1000000)

Ok.

0 rows in set. Elapsed: 0.106 sec. Processed 1.00 million rows, 8.00 MB (9.40 million rows/s., 75.20 MB/s.)
```


We have the same thing with no respect to partitioning when using `toDecimal64()`:
```sql
tietokone :) SELECT count() FROM testdt64pp2 WHERE dec >= toDecimal64(490000, 3)

┌─count()─┐
│  510000 │
└─────────┘

1 row in set. Elapsed: 0.026 sec. Processed 516.67 thousand rows, 4.13 MB (19.73 million rows/s., 157.85 MB/s.)
```

```sql
tietokone :) SELECT count() FROM testdt64pp2 WHERE toDecimal64(dec, 3) >= toDecimal64(490000, 3)

┌─count()─┐
│  510000 │
└─────────┘

1 row in set. Elapsed: 0.035 sec. Processed 1.00 million rows, 8.00 MB (28.40 million rows/s., 227.23 MB/s.)
```

So I guess it is not a bug, it has to be the way it is.

**Comment by UnamedRus** [comment]
May be it can be fixed, if ClickHouse will remove all CAST's to the same data type?

IE: in table it's `DateTime64(3)`, in query `toDateTime64(date_time, 3)`, so it shouldn't change column value and can be safely removed.

**Comment by filimonov** [comment]
> toDecimal...() have unknown monotonicity and have more than one argument

Second arg is constant in 100% cases. So monotonnicity can be defined.

**Comment by filimonov** [comment]
I think it can be improved.

**Comment by den-crane** [comment]
solved https://github.com/ClickHouse/ClickHouse/pull/40219 ( https://github.com/ClickHouse/ClickHouse/pull/39864 )
