### ISSUE TITLE
Server crash on v21.3.2.5 when catch DB::TCPHandler::~TCPHandler() fatal exception

### ISSUE THREAD

**Issue by Fatpa** [ClickHouse/ClickHouse#27010]
Our clickhouse-server crashes sometime after getting fatal, the fatal message detail from clickhouse-server.err.log is as below:

`2021.07.30 14:18:11.997402 [ 5548 ] {} <Fatal> BaseDaemon: ########################################
2021.07.30 14:18:11.997446 [ 5548 ] {} <Fatal> BaseDaemon: (version 21.3.2.5 (official build), build id: 179BDBBF228667883DFCD900B8CD498272FC044F) (from thread 22949) (no query) Received signal Segmentation fault (11)
2021.07.30 14:18:11.997734 [ 5548 ] {} <Fatal> BaseDaemon: Address: 0x8 Access: read. Address not mapped to object.
2021.07.30 14:18:11.997812 [ 5548 ] {} <Fatal> BaseDaemon: Stack trace: 0xf8b3749 0xf8b6ef9 0x11f7e6e6 0x120b4df9 0x120b0c5a 0x7f1205c42ea5 0x7f120596b8dd
2021.07.30 14:18:11.997869 [ 5548 ] {} <Fatal> BaseDaemon: 1. DB::TCPHandler::~TCPHandler() @ 0xf8b3749 in /usr/bin/clickhouse
2021.07.30 14:18:11.997886 [ 5548 ] {} <Fatal> BaseDaemon: 2. DB::TCPHandler::~TCPHandler() @ 0xf8b6ef9 in /usr/bin/clickhouse`

The server runs on CentOS 7.6 with 3.10.0-1127.el7.x86_64 kernel.

But sorry for that, I have no idea about reproducing this crash. I thought it may be due to the no query connection.

**Comment by alexey-milovidov** [comment]
Update to the latest release.
