### ISSUE TITLE
Config to specify arrow columns to be output as strings

### ISSUE THREAD

**Issue by lejtmany** [ClickHouse/ClickHouse#27035]
Currently `String` columns are typed as `Binary` when output in `Arrow` format. It would be great if the was an analog to the `output_format_avro_string_column_pattern` setting for avro called `output_format_arrow_string_column_pattern` that would allow the user to specify which columns should be output as Strings

Thank you!

**Comment by enjoylife** [comment]
Given the arrow type, its related to this issue #27094 which is still occurring.

**Comment by Avogar** [comment]
There are new settings `output_format_arrow_string_as_string`, `output_format_parquet_string_as_string`, `output_format_orc_string_as_string` that allow to output all String columns as String type in corresponding format (https://github.com/ClickHouse/ClickHouse/pull/37327). If you really need to specify only some of columns for using String type, reopen this issue.
