### ISSUE TITLE
Add a technique similar to GWP-ASan

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#27039]
**Describe the solution you'd like**
Small random subset of memory allocations should be protected by guard pages.

GWP-ASan (is in fact almost unrelated to ASan) is not a specific tool but a technique that requires a small change in memory allocator. https://llvm.org/docs/GwpAsan.html

The only point is to enable it by default in production.

**Comment by alexey-milovidov** [comment]
@azat Maybe you will find it interesting?
I see you as an expert in allocators :)

**Comment by azat** [comment]
@alexey-milovidov I was thinking about this when I was trying new tcmalloc (in #11590 there was an item `GWP-ASan for debug builds?` in the `pre-upstream checklist` checklist), but at that time I was thinking about just enabling this functionality in tcmalloc, not implementing it.

But it looks pretty easy to implement, I will take a look.

*FWIW here is a future request in jemalloc - https://github.com/jemalloc/jemalloc/issues/2020*
