### ISSUE TITLE
Shell client hangs due to query

### ISSUE THREAD

**Issue by nskforward** [ClickHouse/ClickHouse#27034]
Centos 8
Installed on pure system clickhouse-server and clickhouse-client from rpm according to manual: https://clickhouse.tech/docs/en/getting-started/install/
Open client:
```
clickhouse-client -h 127.0.0.1
```
I see welcome clickhouse-client cmd interface
Execute the following request:
```
:) CREATE DATABASE md
```
Result
```
CREATE DATABASE md

Query id: 72d2b12c-bc67-4e88-9d6c-3ee4609f6361

Timeout exceeded while receiving data from server. Waited for 300 seconds, timeout is 300 seconds.
Cancelling query.
```

Why I see such error?

**Comment by den-crane** [comment]
>I see welcome clickhouse-client cmd interface

Can you share this `welcome` lines?

Can you share `/var/log/clickhouse-server/clickhouse-server.log` ?
