### ISSUE TITLE
snowflake id (not to confuse with Snowflake service) time extract and convert functions

### ISSUE THREAD

**Issue by jasine** [ClickHouse/ClickHouse#27058]
**Use case**
[snowflake id](https://en.wikipedia.org/wiki/Snowflake_ID) is a form of unique identifier used in distributed computing. The format was created by Twitter and it is widely used in many products such as discord api and etc. 

snowflake is a int64 number and generated based on timestamp, so it is comparable between two ids and it is sorting friendly,   therefore it is a good replacement to uuid  to be used as primary key in many occasions 

when it comes to clickhouse merge key engine,
- we can use snowflake to be the order key or primary key and extract time from it to be the partitioning key at the same time
- some time based queries can be applied on snowflack primary keys after converting time to snowflake and speed up the queries 

**Describe the solution you'd like**

I'd like to add a group of snowflake time extract and convert  functions to solve above questions, and I wonder whether the community will accept this feature.

**Comment by alexey-milovidov** [comment]
Yes, it is rather easy to implement (just do bit shifts accordingly).

You can already do it with `bitShiftRight(snowflake_id, 41)::DateTime64(3)`.
Maybe a separate function(s) will be more convenient.
If there will be a pull request, it will be accepted.

Proposed names:
`snowflakeToDateTime`
`snowflakeToDateTime64`

**Comment by jasine** [comment]
> Yes, it is rather easy to implement (just do bit shifts accordingly).
> 
> You can already do it with `bitShiftRight(snowflake_id, 41)::DateTime64(3)`.
> Maybe a separate function(s) will be more convenient.
> If there will be a pull request, most likely it will be accepted.
> 
> Proposed names:
> `snowflakeToDateTime`
> `snowflakeToDateTime64`

@alexey-milovidov  thanks, it is a long formula,   and snowflake time base on an epoch (default `1288834974657` which is Nov 04 2010 01:42:54 UTC), currently I use 

```fromUnixTimestamp64Milli(((bitShiftRight(snowflake_id, 22)+1288834974657))::Int64)```

 so a function is more convenient and I will create a pull request later. 

by the way, as you suggested, I tried to use `::DateTime64(3)` to replace `fromUnixTimestamp64Milli`, and it seems that converting from number to DateTime64(3) has wrong result, and from string to  DateTime64(3) is correct, is it a bug ? 

for example  

`select 1627807940674::DateTime64(3);`  has correct result: `2021-08-01 08:52:20.476` but `select 1627807940674::Int64::DateTime64(3)` result `2282-12-31 00:00:00.000`

**Comment by UnamedRus** [comment]
Correct way of data casting.

```
SELECT
    fromUnixTimestamp64Milli(CAST('1627807940674', 'Int64')),
    CAST(1627807940674 / 1000, 'DateTime64(3)')

┌─fromUnixTimestamp64Milli(CAST('1627807940674', 'Int64'))─┬─CAST(divide(1627807940674, 1000), 'DateTime64(3)')─┐
│                                  2021-08-01 11:52:20.674 │                            2021-08-01 11:52:20.674 │
└──────────────────────────────────────────────────────────┴────────────────────────────────────────────────────┘
```

**Comment by jasine** [comment]
@UnamedRus got it, thanks

**Comment by filimonov** [comment]
Similar https://github.com/sony/sonyflake
