### ISSUE TITLE
How could ClickHouse maintain cached query results?

### ISSUE THREAD

**Issue by davidshtian** [ClickHouse/ClickHouse#27062]
To reduce query execution time and improve system performance, I would like to cache the results of certain types of queries in memory. 

The ideal situation would be **"When I submit a query,  ClickHouse checks the results cache for a valid, cached copy of the query results. If a match is found in the result cache and the table in the query hasn't been modified, ClickHouse will use the cached results and doesn't actually execute the query again."**

Here, the results doesn't refer to the data cached in the page cache, but to the cached SQL query result. Has ClickHouse already implement this feature? If so, is there any configuration guide on how to achieve this?

[chproxy](https://github.com/Vertamedia/chproxy) might be an optional caching solution, but as far as I know it just cached the result based on TTL but not check whether the table has been modified or not. 

Thanks~

**Comment by den-crane** [comment]
In roadmap
https://github.com/ClickHouse/ClickHouse/issues/17623

https://github.com/ClickHouse/ClickHouse/pull/23706#issuecomment-855306375

**Comment by davidshtian** [comment]
> In roadmap
> #17623
> 
> [#23706 (comment)](https://github.com/ClickHouse/ClickHouse/pull/23706#issuecomment-855306375)

Got it~ Thanks.
