### ISSUE TITLE
how to drop a materialized view ?

### ISSUE THREAD

**Issue by petermenglei** [ClickHouse/ClickHouse#27070]
DB::Exception: Syntax error: failed at position 6 ('MATERIALIZED'): MATERIALIZED VIEW themis.mv_test_idreverse. Expected one of: VIEW, DATABASE, TEMPORARY, TABLE, DICTIONARY, USER, ROLE, SETTINGS PROFILE, PROFILE, ROW POLICY, POLICY, QUOTA (version 21.3.14.1 (official build))

**Comment by tavplubix** [comment]
`DROP TABLE themis.mv_test_idreverse` or `DROP VIEW themis.mv_test_idreverse`
