### ISSUE TITLE
Why does memory keep increasing, 10 percent one day and 50 percent a few days later

### ISSUE THREAD

**Issue by slrem** [ClickHouse/ClickHouse#27077]
Why does memory keep increasing, 10 percent one day and 50 percent a few days later

**Comment by den-crane** [comment]
You need to provide more data. 
How big the grow in GB? How much data you have? 
If you run `system drop mark cache` is it drops memory usage?

**Comment by slrem** [comment]
Machine configuration:

ClickHouse version: 21.4.6.55

System: ubuntu16.04.12

Memory: 16 g

CPU: 8 cores

Description: Data entry is about 10G per hour, every hour is about more than 10,000 tables created and deleted more than 10,000 expired tables, the total number of tables is maintained at about 20,000

**Comment by slrem** [comment]
> 您需要提供更多数据。
> GB 的增长有多大？你有多少数据？
> 如果你运行`system drop mark cache`它会降低内存使用量吗？

Machine configuration:
ClickHouse version: 21.4.6.55
System: ubuntu16.04.12
Memory: 16 g
CPU: 8 cores

Description: Data entry is about 10G per hour, Every hour is about more than 10,000 tables created and deleted more than 10,000 expired tables, The total number of tables is maintained at about 20,000

system drop mark cache is invalid

**Comment by filimonov** [comment]
Please share results of the queries from https://kb.altinity.com/altinity-kb-setup-and-maintenance/altinity-kb-who-ate-my-memory 

> system drop mark cache is invalid

What do you mean? Can you share the output?

**Comment by slrem** [comment]
> Please share results of the queries from https://kb.altinity.com/altinity-kb-setup-and-maintenance/altinity-kb-who-ate-my-memory
> 
> > system drop mark cache is invalid
> 
> What do you mean? Can you share the output?

I mean, it worked, but memory didn't drop

**Comment by den-crane** [comment]
>every hour is about more than 10,000 tables 

Wowwwww!!!!!!!!! What table engine do you use for these tables? What is the usecase?

**Comment by slrem** [comment]
> > every hour is about more than 10,000 tables
> 
> Wowwwww!!!!!!!!! What table engine do you use for these tables? What is the usecase?

The vast majority (99%) are MergeTree engines, a small number (1%) of ReplacingMergeTree engines,

Usage:

There are now two hosts (A and B) with ClickHouse installed.

A host is responsible for data entry, each hour to create A table, B is responsible for the host data sheet by SCP copy on each hour from/var/lib/clickhouse/data, and/var/lib/clickhouse/metadata in the file to host B, Then attach the table to the clickhouse of host B and delete the copied table from host A.

Host B needs to merge the hourly table synchronized from host A into the hourly table and delete the hourly table. Then, at dawn, host B uses the hourly table for data calculation and caches the calculated data to the cache table. Then, host B merges the hourly table into A monthly table and deletes the hourly table

**Comment by den-crane** [comment]
It's kinda expected for `Memory: 16 g` and `10,000 MergeTree`
16g is super-tiny and not usable in production.

**Comment by slrem** [comment]
> It's kinda expected for `Memory: 16 g` and `10,000 MergeTree`
> 16g is super-tiny and not usable in production.

It's not directly related to the continued growth of content, is it?
