### ISSUE TITLE
Invalid sumIf behavior with nullable arguments

### ISSUE THREAD

**Issue by DimasKovas** [ClickHouse/ClickHouse#27073]
**Describe the bug**

`sumIf` returns incorrect results in some cases with Nullable arguments.

**How to reproduce**

* Which ClickHouse server version to use
Latest master/arcadia version

* Queries to run that lead to unexpected result
```sql
:) select sumIf(toFloat64OrZero(b), a = 0) as r1, sumIf(cast(b as Float), a = 0) as r2, sum(if(a = 0, toFloat64OrZero(b), 0)) as r3 from (select arrayJoin([1, 2, 3, NULL]) as a, toNullable('10.0') as b)

SELECT
    sumIf(toFloat64OrZero(b), a = 0) AS r1,
    sumIf(CAST(b, 'Float'), a = 0) AS r2,
    sum(if(a = 0, toFloat64OrZero(b), 0)) AS r3
FROM
(
    SELECT
        arrayJoin([1, 2, 3, NULL]) AS a,
        toNullable('10.0') AS b
)

Query id: 2e4e320d-e52a-4514-bc6f-118485558191

┌─r1─┬─r2─┬─r3─┐
│ 10 │  0 │  0 │
└────┴────┴────┘
```
**Expected behavior**

All results are 0.

**Additional context**

It breaks when null values in Nullable column are compared with `assumeNotNull` from this column.
It also only breaks when first argument is Nullable too.

**Comment by kitaisreal** [comment]
@DimasKovas which clickhouse server version do you use ?

**Comment by DimasKovas** [comment]
> @DimasKovas which clickhouse server version do you use ?

@kitaisreal I reproduced it on latest master version (1f1795a305c3b170f6137309ccfa169efe4aa8f5), but originally it was found on master version which is ~ half a year old, so the bug exists for quite a while.

**Comment by Algunenano** [comment]
Some tests:
* 20.7.4.11: │  0 │  0 │  0 │
* 20.8.2.3: │ 10 │ 10 │  0 │
* 20.8.19.4: │ 10 │  0 │  0 │
* 21.3.17.2: │ 10 │  0 │  0 │
* 21.8.7.22: │ 10 │  0 │  0 │
* 21.9.4.35: │ 10 │  0 │  0 │
* Master/HEAD: │ 10 │  0 │  0 │

So it is indeed an old issue. Something changed in 20.8 and it was partially "reverted" but not fully fixed.

**Comment by alexey-milovidov** [comment]
Minimal reproducing example:
`SELECT anyIf(toNullable('Hello'), arrayJoin([1, NULL]) = 0)`

**Comment by alexey-milovidov** [comment]
Broken here: #13964
