### ISSUE TITLE
populate and MATERIALIZED VIEW ... TO ... 

### ISSUE THREAD

**Issue by TimonKK** [ClickHouse/ClickHouse#2707]
Есть такой запрос создания мат вью
CREATE MATERIALIZED VIEW loadstat_agg_view TO loadstat_agg
ENGINE = AggregatingMergeTree(date, (host, date), 8192) POPULATE AS
SELECT
  host,
  date,
  countState() AS hitCount,
  countState(if(load = 0, host, NULL)) AS badCount,
  uniqState(ip) AS hostCount,
  uniqState(host) AS siteCount,
  uniqState(userAgent) AS uniqCount,
  avgState(
    if(
      ((resolved - opened) > 0)
      AND ((resolved - opened) <= 60000),
      resolved - opened,
      NULL
    ) / 1000
  ) AS avgLoadTime
FROM
  loadstat
GROUP BY
  host,
  date

Ругается:
Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 99 (line 2, col 1): ENGINE = AggregatingMergeTree(date, (host, date), 8192) POPULATE AS
SELECT
  host,
  date,
  countState() AS hitCount,
  countState(if(load = 0, host, NULL)) AS. Expected one of: token, OpeningRoundBracket, AS, e.what() = DB::Exception

Что не так?

Если убрать "ENGINE = AggregatingMergeTree(date, (host, date), 8192) POPULATE" запрос отрабатывает

**Comment by filimonov** [comment]
Если используется синтаксис с опцией TO, тогда предполагается что целевая таблица уже существует. А если таблица уже существует, то и параметры движка этой таблицы указывать не нужно.

**Comment by TimonKK** [comment]
Убрал ENGINE, ругается теперь так:
Syntax error: failed at position 213 (line 3, col 70): POPULATE AS

**Comment by filimonov** [comment]
Хм. POPULATE не работает с TO. См. 

https://github.com/yandex/ClickHouse/blob/7bae3506c41be971ec6ec031c139f596e026a5f0/dbms/src/Parsers/ParserCreateQuery.cpp#L367

Легко обойти - можно просто INSERT ... SELECT сделать перед созданием матвью

Но действительно наверное несколько нелогично, по крайней мере должно быть какое-то внятное сообщение об ошибке.

**Comment by RouR** [comment]
Нужно выкинуть конструкцию `TO loadstat_agg`

**Comment by MrBuddyCasino** [comment]
I just this issue, too: `MATERIALIZED VIEW ... TO <target> POPULATE` throws an error. This is a migration, and the underlying table already contains a lot of data. Is there a way to trigger a `POPULATE` in a separate query without having to re-insert data in some table?
