### ISSUE TITLE
how to delete wal.bin file ?

### ISSUE THREAD

**Issue by onine007** [ClickHouse/ClickHouse#27075]
![image](https://user-images.githubusercontent.com/24770345/127837814-bc2d7ac2-cfb7-4448-872b-44b0b01e44ba.png)
Can delete these files?  How to delete ?  

Make sure to check documentation https://clickhouse.yandex/docs/en/ first. If the question is concise and probably has a short answer, asking it in Telegram chat https://telegram.me/clickhouse_en is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

If you still prefer GitHub issues, remove all this text and ask your question here.

**Comment by tavplubix** [comment]
You should not delete these files

**Comment by den-crane** [comment]
wal.bin -- is a Write Ahead Log for in-memory parts. Inserted data is stored in this file.
You can disable ` in-memory parts`. See merge tree settings.

**Comment by onine007** [comment]
can't  delete wal_***_***.bin  ?

**Comment by filimonov** [comment]
You should not delete these files if you used in-memory parts and write-ahead log.

See mergetree settings:
```
in_memory_parts_enable_wal
min_bytes_for_compact_part
min_rows_for_compact_part
```
