### ISSUE TITLE
Create Table with projection feature failed using clickhouse-local

### ISSUE THREAD

**Issue by taylor12805** [ClickHouse/ClickHouse#27124]
**Describe the bug**

create MergeTree Table with projections feature using clickhouse-local, program exits with exception.

**Does it reproduce on recent release?**

Yes, on ClickHouse Server Version: 21.7.5.29

**How to reproduce**

ClickHouse server version: 21.7.5

`
clickhouse local --logger.console --logger.level information --query "CREATE TABLE test_projections (mid UInt64, join_time String, turn_time String, fans Int64, friends Int64, last_order_time String, PROJECTION test_proj (SELECT max(mid) as max_mid)) ENGINE = MergeTree() ORDER BY mid SETTINGS index_granularity = 8192" -- --path /data/clickhouse-data/2952608b-8fad-47ee-b9b2-37d50cd6cabe
`

**Expected behavior**

Program exit with a table created on the path.

**Error message and/or stacktrace**

2021.08.03 16:58:42.708359 [ 7125 ] {a81d210a-4070-4cae-bfd9-523cb4cef25e} <Error> executeQuery: Code: 81, e.displayText() = DB::Exception: Database _temporary_and_external_tables doesn't exist (version 21.7.5.29 (official build)) (from 0.0.0.0:0) (in query: CREATE TABLE test_projections (mid UInt64, join_time String, turn_time String, fans Int64, friends Int64, last_order_time String, PROJECTION test_proj (SELECT max(mid) as max_mid)) ENGINE = MergeTree() ORDER BY mid SETTINGS index_granularity = 8192), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x8d30bda in /mnt/storage01/clickhouse-spark/clickhouse-server/clickhouse
1. DB::DatabaseCatalog::assertDatabaseExistsUnlocked(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const @ 0xf79111c in /mnt/storage01/clickhouse-spark/clickhouse-server/clickhouse
2. DB::DatabaseCatalog::getDatabaseForTemporaryTables() const @ 0xf78d63b in /mnt/storage01/clickhouse-spark/clickhouse-server/clickhouse
3. DB::TemporaryTableHolder::TemporaryTableHolder(std::__1::shared_ptr<DB::Context const>, std::__1::function<std::__1::shared_ptr<DB::IStorage> (DB::StorageID const&)> const&, std::__1::shared_ptr<DB::IAST> const&) @ 0xf78cb0c in /mnt/storage01/clickhouse-spark/clickhouse-server/clickhouse
4. DB::TemporaryTableHolder::TemporaryTableHolder(std::__1::shared_ptr<DB::Context const>, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, std::__1::shared_ptr<DB::IAST> const&, bool) @ 0xf78d830 in /mnt/storage01/clickhouse-spark/clickhouse-server/clickhouse
5. DB::ProjectionDescription::getProjectionFromAST(std::__1::shared_ptr<DB::IAST> const&, DB::ColumnsDescription const&, std::__1::shared_ptr<DB::Context const>) @ 0xffed2d4 in /mnt/storage01/clickhouse-spark/clickhouse-server/clickhouse
6. DB::InterpreterCreateQuery::setProperties(DB::ASTCreateQuery&) const @ 0xf85f38e in /mnt/storage01/clickhouse-spark/clickhouse-server/clickhouse
7. DB::InterpreterCreateQuery::createTable(DB::ASTCreateQuery&) @ 0xf8657f3 in /mnt/storage01/clickhouse-spark/clickhouse-server/clickhouse
8. DB::InterpreterCreateQuery::execute() @ 0xf86bbdc in /mnt/storage01/clickhouse-spark/clickhouse-server/clickhouse
9. ? @ 0xfe16b53 in /mnt/storage01/clickhouse-spark/clickhouse-server/clickhouse
10. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::__1::shared_ptr<DB::Context>, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>, std::__1::optional<DB::FormatSettings> const&) @ 0xfe1a61d in /mnt/storage01/clickhouse-spark/clickhouse-server/clickhouse
11. DB::LocalServer::processQueries() @ 0x8e4be46 in /mnt/storage01/clickhouse-spark/clickhouse-server/clickhouse
12. DB::LocalServer::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x8e4975e in /mnt/storage01/clickhouse-spark/clickhouse-server/clickhouse
13. Poco::Util::Application::run() @ 0x13394743 in /mnt/storage01/clickhouse-spark/clickhouse-server/clickhouse
14. mainEntryClickHouseLocal(int, char**) @ 0x8e510d4 in /mnt/storage01/clickhouse-spark/clickhouse-server/clickhouse
15. main @ 0x8d2b95e in /mnt/storage01/clickhouse-spark/clickhouse-server/clickhouse
16. __libc_start_main @ 0x202e1 in /lib/x86_64-linux-gnu/libc-2.24.so
17. _start @ 0x8cf6c6e in /mnt/storage01/clickhouse-spark/clickhouse-server/clickhouse

**Comment by amosbird** [comment]
Addressed in https://github.com/ClickHouse/ClickHouse/pull/26286
