### ISSUE TITLE
Nullable field not accepted in multi-value insertion

### ISSUE THREAD

**Issue by schien-dong** [ClickHouse/ClickHouse#27120]
version 21.7.5.29 (official build) revision 54449

create table test(
logid UUID default generateUUIDv4(),
extid UInt64 default 0
) engine=MergeTree()
primary key logid
order by logid;

The issue can be reproduced with an empty table.

The following insert statements work:

insert into test (extid) values (1);
insert into test (extid) values (NULL);
insert into test (extid) values ('0');

When the values are batched in a single query, this works:

insert into test (extid) values (1), (0);

This mixed case also works:

insert into test (extid) values (NULL), ('0');

The following query is expected work but it fails:

insert into test (extid) values ('0'), (NULL);

**Error message and/or stacktrace**

Code: 32. DB::Exception: Attempt to read after eof: Cannot parse UInt64 from String, because value is too short: while executing 'FUNCTION CAST(assumeNotNull(_dummy_0) :: 2, 'UInt64' :: 1) -> CAST(assumeNotNull(_dummy_0), 'UInt64') UInt64 : 4': data for INSERT was parsed from query

Error reproduced with:

- clickhouse-client
- mysql-client (protocol=TCP on Port 9004)
- HTTP API

**Comment by alexey-milovidov** [comment]
@tavplubix It is definitely related to expression templates and should be easy to fix.

**Comment by tiantiantian808** [comment]
I'm working on fix the problem

**Comment by sunny19930321** [comment]
@schien-dong fix https://github.com/ClickHouse/ClickHouse/pull/28413
