### ISSUE TITLE
GLIBC 2.32 / 2.33 / 2.34 compatibility

### ISSUE THREAD

**Issue by Algunenano** [ClickHouse/ClickHouse#27133]
It would be nice if Clickhouse supported building in an enviornment with GLIBC 2.32+ like it supports older releases (pinning symbols).

My usecase is that I'm building in a new machine (Archlinux with GLIBC 2.33) and that works great until I want to run the integration tests, which run under an old Ubuntu (20.04) with 2.31-0ubuntu9.2 and that will fail when using the binary:

```
E               Exception: Timed out while waiting for instance `node1' with ip address 172.16.0.4 to start. Container status: running, logs: clickhouse: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by clickhouse)
E               clickhouse: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by clickhouse)
```

I see that @amosbird started working on it but ended up discarding the PR (https://github.com/ClickHouse/ClickHouse/pull/24015). I've tested it and it doesn't work for 2.33.

Are there any plans to support this or should I look for a better way to run those tests locally?

**Comment by amosbird** [comment]
Starting from 2.34 we will require a new __libc_main_start which is basically impossible. So we either need to ship a libc blob in submodule, or do static linking.

**Comment by alexey-milovidov** [comment]
Yes, we need to provide full environment during build, similar to what we do with cross-compilation.

The option with static linking is also *possible* but quite hard, because we need to open and load .so for CatBoost dynamically.
