### ISSUE TITLE
dynamically setting mutations_sync without a session context

### ISSUE THREAD

**Issue by schien-dong** [ClickHouse/ClickHouse#27148]
Currently the mutations_sync flag can be set either in the config xml or in the client console.

When using the HTTP API, due to the stateless nature of HTTP, there is no concept of a "session". Therefore, when mutations_sync is set to 2, before sending a second Update query, the Update is not blocking as expected.

Multiple queries are also not allowed for a good reason, so this leaves just a few options to express the intent:

- allow an X-ClickHouse-Mutations-Sync header
- read from the query parameter. eg. /?set_mutations_sync=2&param_id=...&query=...
- use a SQL modifier, e.g. "alter table cars update... at mutation_sync=2"

The more trivial (least disruptive) methods are listed first.

**Comment by tavplubix** [comment]
> When using the HTTP API, due to the stateless nature of HTTP, there is no concept of a "session".

You can add `session_id` parameter to HTTP request, so ClickHouse will maintain session context for each `session_id`:
```
$ curl "http://localhost:8123/?query=select+value+from+system.settings+where+name='mutations_sync'"
0
$ curl "http://localhost:8123/?session_id=42&query=set+mutations_sync=1"
$ curl "http://localhost:8123/?session_id=42&query=select+value+from+system.settings+where+name='mutations_sync'"
1
```

> Currently the mutations_sync flag can be set either in the config xml or in the client console.

It also can be set in HTTP request (even without session):
```
$ curl "http://localhost:8123/?mutations_sync=2&query=select+value+from+system.settings+where+name='mutations_sync'"
2
```

See https://clickhouse.tech/docs/en/interfaces/http/ for details.
