### ISSUE TITLE
Sign aws specific headers `x-amz` 

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#27140]
In https://github.com/ClickHouse/ClickHouse/pull/11134 support for custom headers in s3 functions was added, but it's not working if you would try to pass some aws specific headers like `x-amz-request-payer` in it.

```
<header>x-amz-request-payer: requester</header>
```
Error message:

```
`AccessDenied`, message: 'There were headers present in the request which were not signed'.
```

https://docs.aws.amazon.com/AmazonS3/latest/userguide/ObjectsinRequesterPaysBuckets.html

Because clickhouse doesn't sign them properly

**Expected behavior**

custom_headers working fine with aws s3.

**Comment by aderouineau** [comment]
@UnamedRus Isn't this more a bug than a feature?

**Comment by UnamedRus** [comment]
Because it was added for a different purpose and never worked like that, it's being considered as feature by clickhouse core team standarts.

**Comment by aderouineau** [comment]
It looks like moving `AWSAuthV4Signer::SignRequest` and `AWSAuthV4Signer::PresignRequest` after the `SetHeaderValue()` loops in `src/IO/S3Common.cpp` should fix this issue. It worked for me. Unfortunately for legal reasons I am currently unable to issue a pull request.

**Comment by aderouineau** [comment]
@UnamedRus Any update on this?

**Comment by antonio2368** [comment]
@UnamedRus do you think it makes sense to simply sign all headers or just have a list of headers that need to be signed?

**Comment by UnamedRus** [comment]
>  just have a list of headers that need to be signed?

I think we need to follow AWS documentation

https://github.com/ClickHouse/ClickHouse/pull/34585#issuecomment-1046137807

https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-header-based-auth.html

The CanonicalHeaders list must include the following:

HTTP host header.

If the Content-Type header is present in the request, you must add it to the CanonicalHeaders list.

Any x-amz-* headers that you plan to include in your request must also be added. For example, if you are using temporary security credentials, you need to include x-amz-security-token in your request. You must add this header in the list of CanonicalHeaders.
