### ISSUE TITLE
TLS connection to zookeeper does not appear to work

### ISSUE THREAD

**Issue by genzgd** [ClickHouse/ClickHouse#27151]
ClickHouse versions 21.4.4, 21.7.5.

We have tried to create a TLS connection between ClickHouse and Zookeeper.  Zookeeper apparently does not support TLS 1.3 (see https://issues.apache.org/jira/browse/ZOOKEEPER-3622).  From what we can tell, ClickHouse tries to connect to zookeeper with TLS 1.3, and the handshake fails:

```
2021.08.03 17:10:13.609414 [ 2835628 ] {} <Error> Application: Coordination::Exception: All connection tries failed while connecting to ZooKeeper. nodes: secure://[2001:558:fee0:47:9a03:9bff:fe67:fc76]:2281, secure://[2001:558:fee0:47:9a03:9bff:fe67:fd6e]:2281, secure://[2001:558:fee0:47:9a03:9bff:fe67:fcf6]:2281
Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = SSL Exception: error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE (version 21.7.5.29 (official build)), [2001:558:fee0:47:9a03:9bff:fe67:fc76]:2281
```

We tried forcing TLS 1.2 with the following configuration, but the setting seems to be ignored:

```
<openSSL>
  <server>
    ....
  </server>
  <client>
        <certificateFile>/etc/clickhouse-server/certs/zookeeper_client.crt</certificateFile>
        <privateKeyFile>/etc/clickhouse-server/certs/zookeeper_client.key</privateKeyFile>
	<!-- <loadDefaultCAFile>true</loadDefaultCAFile> -->
        <caConfig>/etc/clickhouse-server/certs/cacert</caConfig>
        <cacheSessions>true</cacheSessions>
	<requireTLSv1_2>true</requireTLSv1_2>
	<disableProtocols>sslv2,sslv3,tlsv1,tlsv1_1</disableProtocols>
        <preferServerCiphers>true</preferServerCiphers>
        <verificationMode>none</verificationMode>
        <invalidCertificateHandler>
            <name>RejectCertificateHandler</name>
        </invalidCertificateHandler>
    </client>
<openSSL>
```

In fact, the entire client sections seems to be ignored for the zookeeper TLS connection, as the behavior is the same even without the <client> element entirely.

Does anyone have a working configuration of ClickHouse to Zookeeper TLS using client certificates/mutual auth?

**Comment by alexey-milovidov** [comment]
We are successfully using TLS connections to ZooKeeper in Yandex.Cloud, but without client certificates authentication.

**Comment by genzgd** [comment]
We eventually got this working with client certificate authentication.  The only combination that worked for us was TLS 1.3 on both zookeeper and ClickHouse, using `TLS_AES_128_GCM_SHA256` as the zookeeper cipher suite.  Strongly suggest that documentation be updated as per #24312
