### ISSUE TITLE
Can't use tag <include_from> in config.xml

### ISSUE THREAD

**Issue by qiancijun** [ClickHouse/ClickHouse#27167]
i want to config remote_servers and zookeeper in metrika.xml, but i can't use tag include_from to quote the external file
i make sure my metrika.xml is correct
version 21.7.4.18
``` xml
<?xml version="1.0"?>
<yandex>
   <zookeeper>
        <node index="1">
            <host>Node101</host>
            <port>2181</port>
        </node>
        <node index="2">
            <host>Node102</host>
            <port>2181</port>
        </node>
        <node index="3">
            <host>Node103</host>
            <port>2181</port>
        </node>
    </zookeeper>
    <macros>
        <shard>01</shard>
        <replica>rep_1_1</replica>
    </macros>
</yandex>
```

**Comment by lingnancfy** [comment]
May be some error info in the clickhouse-server.log

**Comment by qiancijun** [comment]
i have already check it, it only point that mismatch tag

**Comment by den-crane** [comment]
>i want to config remote_servers and zookeeper in metrika.xml

? WHY ?

You don't need to use /etc/metrica.xml https://kb.altinity.com/altinity-kb-setup-and-maintenance/altinity-kb-server-config-files
Just copy these xml files into /etc/clickhouse-server/config.d/

https://github.com/ClickHouse/ClickHouse/pull/18740
https://github.com/ClickHouse/ClickHouse/issues/21905
https://github.com/ClickHouse/ClickHouse/issues/26025
