### ISSUE TITLE
 AVG function in GraphiteMergeTree is deceptive

### ISSUE THREAD

**Issue by praisethejack** [ClickHouse/ClickHouse#27162]
I created a GraphiteMergeTree use the Rollup Configuration as follow:
```
    <metric_avg_all>
        <default>
            <function>avg</function>
            <retention>
                <age>0</age>
                <precision>10</precision>
            </retention>
            <retention>
                <age>60</age>
                <precision>60</precision>
            </retention>
            <retention>
                <age>300</age>
                <precision>300</precision>
            </retention>
            <retention>
                <age>3600</age>
                <precision>3600</precision>
            </retention>
        </default>
    </metric_avg_all>
```
For test it, I insert every 5s, in age 0, it actually use anyLast, that OK.
But, in all of the last age, I found that, it avg a number of records one by one like this:
```
if it should avg 5 record(1,2,3,4,5)
(1+2)/2 = 1.5
(1.5+3)/2 = 2.25
(3.125+4)/2 = 3.125
(3.125+5)/2 = 4.0625 != 3
```
Obviously, this is not true from the user's perspective.
Now, I can just add extra retention to make sure that each one only works on two records, like age 0 pre 10, age 20 pre 20.
Unforunately, this can still lead to errors where miss a record. And the age doesn't fit what I need.

Is there any other way to do that?

**Comment by den-crane** [comment]
Yes, it's expected. Probably must be documented. It's impossible to fix in GraphiteMergeTree.
You can use TTL GroupBY and AggregateFunction(avg) or sum/count.

**Comment by praisethejack** [comment]
Thanks.
Additionally, I try to use groupArrayMovingAvg. But got a error when create table:
```
Aggregate function groupArrayMovingAvg isn't supported in GraphiteMergeTree.
```
I don't know if the other specific aggregate functions are work. It should better specifically list support function.

**Comment by praisethejack** [comment]
Thanks.
Additionally, I try to use groupArrayMovingAvg. But got a error when create table:
```
Aggregate function groupArrayMovingAvg isn't supported in GraphiteMergeTree.
```
I don't know if the other specific aggregate functions are work. It should better specifically list support function.

**Comment by praisethejack** [comment]
@den-crane I fail to create a megreTree table with TTL Where GrouBy
```
CREATE TABLE demo8.table_agg_v3(d DateTime32, k1 Int, k2 Int, x Int, y Int, lv UInt8 DEFAULT 10) ENGINE = MergeTree ORDER BY (k1, k2) TTL d + INTERVAL 60 SECOND WHERE lv=10 GROUP BY k1, k2 SET lv = 20, x = max(x), y = min(y) SETTINGS merge_with_ttl_timeout=60

got error:
Syntax error: failed at position 176 ('GROUP'):
Expected one of: LIKE, GLOBAL NOT IN, PRIMARY KEY, end of query, AS, DIV, IS, INTO OUTFILE, OR, QuestionMark, BETWEEN, NOT LIKE, MOD, AND, Comma, SETTINGS, PARTITION BY, IN, SAMPLE BY, ILIKE, FORMAT, NOT ILIKE, NOT, token, NOT IN, GLOBAL IN
```
Is Where can not use in TTL GroupBy

**Comment by den-crane** [comment]
@praisethejack https://kb.altinity.com/altinity-kb-queries-and-syntax/ttl/ttl-group-by-examples
