### ISSUE TITLE
How can I specify schema on PostgreSQL engine?

### ISSUE THREAD

**Issue by chu1070y** [ClickHouse/ClickHouse#27166]
Hello,

I read PostgreSQL Engine on CH Document.
https://clickhouse.tech/docs/en/engines/database-engines/postgresql/

Where can I specify the schema name on PostgreSQL engine?

When I tested, It didn't get all of table from all schemas.
It seems CH can get only `public` schema which is default schema.

Is there any way that I can access other schema?

**Comment by kssenii** [comment]
Yes, for database engine using non default schema was not implemented, but easy to add.. I'll do.

**Comment by chu1070y** [comment]
Thank you!
