### ISSUE TITLE
output_format_avro_string_column_pattern not recognized

### ISSUE THREAD

**Issue by lejtmany** [ClickHouse/ClickHouse#27192]
> A clear and concise description of what works not as it is supposed to.

when using `output_format_avro_string_column_pattern` get an error that setting is not recognized

**Does it reproduce on recent release?**

yes  21.7.5

**How to reproduce**
```sql
CREATE TABLE test1 (colA String) Engine MergeTree ORDER BY colA
SELECT * FROM test1 FORMAT Avro SETTINGS output_format_avro_string_column_pattern='colA'
```

Returns 
```
0 rows in set. Elapsed: 0.010 sec.

Received exception from server (version 21.7.5):
Code: 115. DB::Exception: Received from localhost:9000. DB::Exception: Unknown setting output_format_avro_string_column_pattern.
```

**Expected behavior**
It outputs specified columns as strings in avro format

**Comment by alexey-milovidov** [comment]
The feature is not released yet.
#26245

**Comment by lejtmany** [comment]
Apologies. Just saw the setting in the docs and assumed it was out
https://clickhouse.tech/docs/en/operations/settings/settings/#output_format_avro_string_column_pattern
