### ISSUE TITLE
Materialized View generating too slow

### ISSUE THREAD

**Issue by Hast** [ClickHouse/ClickHouse#27209]
We collect raw events into a ClickHouse table. Table structure:

```
CREATE TABLE IF NOT EXISTS raw_events
(
    owner_id                  UInt32,
    user_id                   UInt32,
    event_datetime            DateTime,
    event_type_id             UInt8,
    unique_id                 FixedString(18),
    data                      String,
    attr_1                    UInt32,
    attr_2                    UInt32
)
    engine = MergeTree PARTITION BY toYYYYMMDD(event_datetime)
    ORDER BY (owner_id, user_id, event_type_id, event_datetime);
```

At the moment *raw_events* table contains **120000000 (120M) rows**.

We aim to show our users some aggregate statistics for those events, thus we created a materialized view:

```
CREATE MATERIALIZED VIEW test
ENGINE = AggregatingMergeTree() PARTITION BY (date)
ORDER BY (owner_id, user_id, date)
AS SELECT
       toYYYYMMDD(event_datetime) as date,
       owner_id,
       user_id,
       multiIf(
                   event_type_id == 1, 10,
                   event_type_id == 2, 20,
                   event_type_id == 3, 30,
                   event_type_id == 4, 40,
                   event_type_id == 32, 50,
                   event_type_id >= 64, 60,
                   0
           ) as status,
       attr_1,
       attr_2,
       COUNT() as count,
       COUNT(DISTINCT unique_id) as unique_count
   FROM raw_events
   GROUP BY owner_id, user_id, date, status, attr_1, attr_2
   ORDER BY owner_id, user_id, date;
```

If we run the select query separately, it takes around 1 second to generate a response for a single owner_id. But creating a materialized view for the same select takes too much time. After executing *create materialized view* query it generated just **200 records** and it took it **~10 minutes**. So it looks like it will take days to completely build a view for the current 120M records table.

What am I missing? Maybe there are some tricks for order/group clauses to make it run faster? At the moment it's much easier for me to just run select+group query instead of using a materialized view.

Additional question: is there a way to check the progress for materialized view building for an existing table?

**Comment by den-crane** [comment]
AggregatingMergeTree -- uses `ORDER BY ` as collapsing rule.
AggregatingMergeTree -- have to be used with AggregateFunctions + -State + -Merge combinators
ORDER BY -- is excessive


```
CREATE MATERIALIZED VIEW test
ENGINE = AggregatingMergeTree() PARTITION BY (date)
ORDER BY (owner_id, user_id, date, status, attr_1, attr_2)         ---<<<<<<<<<<<<<<<<<<<<-----------
AS SELECT
       toYYYYMMDD(event_datetime) as date,
       owner_id,
       user_id,
       multiIf(
                   event_type_id == 1, 10,
                   event_type_id == 2, 20,
                   event_type_id == 3, 30,
                   event_type_id == 4, 40,
                   event_type_id == 32, 50,
                   event_type_id >= 64, 60,
                   0
           ) as status,
       attr_1,
       attr_2,
       countState() as count,                                  ---<<<<<<<<<<<<<<<<<<<<-----------
       uniqState(unique_id) as unique_count        ---<<<<<<<<<<<<<<<<<<<<-----------
   FROM raw_events
   GROUP BY owner_id, user_id, date, status, attr_1, attr_2

```

https://gist.github.com/den-crane/a72614fbe6d23eb9c2f1bce40c66893f
https://gist.github.com/den-crane/49ce2ae3a688651b9c2dd85ee592cb15
https://den-crane.github.io/Everything_you_should_know_about_materialized_views_commented.pdf
