### ISSUE TITLE
clickhouse-cpp

### ISSUE THREAD

**Issue by goutaiping** [ClickHouse/ClickHouse#27210]
HI clickhouse:
     I'm happy to use clickhouse-cpp, and I successfully compiled the library under Qt Creator5.9.8 software, but when I run the test program I have a problem, and I need your help. It always reports an error: "exception : fail to connect: Operation completed successfully",  Looking forward to your reply, Thank you very much

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/clickhouse-cpp/issues/98
