### ISSUE TITLE
Inquiries about timezone

### ISSUE THREAD

**Issue by parkbaesun** [ClickHouse/ClickHouse#27215]
Hello,

I'm going to use the timezone.

I checked the contents in the document, but I am inquiring because there is something confusing.
( checked document :  https://clickhouse.tech/docs/en/sql-reference/data-types/datetime/ )

I checked the list supported by clickhouse in the link below.
https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

So, should it be used in the form of a country/region name?

I wonder if there is a way to do plus or minus time based on UTC.

for example, 
  - SELECT toDateTime(now(), 'UTC+5')
  - SELECT toDateTime(now(), 'UTC+05:00')

**Comment by den-crane** [comment]
>So, should it be used in the form of a country/region name?

Yes, you should.

>I wonder if there is a way to do plus or minus time based on UTC.

Clickhouse does not support it.

But parseDateTimeBestEffort function supports `Z-0344` form:

```
SELECT parseDateTimeBestEffort('2021-01-01T00:00:00Z-0344')

Query id: f2cb5dfb-13d3-49b9-8d10-cf20f4e1f647

┌─parseDateTimeBestEffort('2021-01-01T00:00:00Z-0344')─┐
│                                  2021-01-01 03:44:00 │
└──────────────────────────────────────────────────────┘
```
