### ISSUE TITLE
Unexpected LIKE behavior after upgrade to 21.6.6.51 version

### ISSUE THREAD

**Issue by vitalek84** [ClickHouse/ClickHouse#27213]
Hello all. Have upgraded from 21.3.4.25 to 21.6.6.51 and suddenly queries like: 
select str from (select 'https://www.etsy.com/de/search?q=kawaii%20clothing&ref=auto-1' as str) where str LIKE '%etsy.com%\?q=%';   stopped to work; 

I tried query via native clickhouse client and via http interface. 
via clickhouse client I noticed one difference here is query output:
Click house behavior 21.3.4: 

 select str from (select 'https://www.etsy.com/de/search?q=kawaii%20clothing&ref=auto-1' as str) where str LIKE '%etsy.com%\?q=%';

SELECT str
FROM 
(
    SELECT 'https://www.etsy.com/de/search?q=kawaii%20clothing&ref=auto-1' AS str
)
WHERE str LIKE **'%etsy.com%\\?q=%'**

Query id: a613805b-45dc-4853-8daa-1155f687a71a

┌─str───────────────────────────────────────────────────────────┐
│ https://www.etsy.com/de/search?q=kawaii%20clothing&ref=auto-1 │
└───────────────────────────────────────────────────────────────┘
1 rows in set. Elapsed: 0.002 sec. 

Click house behavior 21.6.6: 

select str from (select 'https://www.etsy.com/de/search?q=kawaii%20clothing&ref=auto-1' as str) where str LIKE '%etsy.com%\?q=%';

SELECT str
FROM 
(
    SELECT 'https://www.etsy.com/de/search?q=kawaii%20clothing&ref=auto-1' AS str
) 
WHERE str LIKE **'%etsy.com%?q=%'**

↘ Progress: 0.00 rows, 0.00 B (0.00 rows/s., 0.00 B/s.) Ok.

0 rows in set. Elapsed: 0.058 sec. 

There are different string in LIKE section.  Is this a bug or a feature? 
To reproduce this behavior you can run this query on 21.3.4.25 and 21.6.6.51 without and database and tables creation.

**Comment by den-crane** [comment]
The old behaviour was incorrect, fixed https://github.com/ClickHouse/ClickHouse/pull/23610

https://github.com/ClickHouse/ClickHouse/blob/master/CHANGELOG.md
ClickHouse release 21.5, 2021-05-20
Fixed misinterpretation of some LIKE expressions with escape sequences. #23610 (alexey-milovidov).

**Comment by den-crane** [comment]
You don't need to escape `?` , because it means nothing for `LIKE`. Wild single character for like is `_`.

**Comment by vitalek84** [comment]
Thank you very much for your response!
