### ISSUE TITLE
Compare queries with normalized formatting

### ISSUE THREAD

**Issue by Nyoroon** [ClickHouse/ClickHouse#27229]
**Use case**
I want to compare two queries with same semantics, but different format.

**Describe the solution you'd like**
Function to normalize query format (like in `SHOW CREATE` statement) or get query hash after re-formatting.
Or function to compare two queries.

**Describe alternatives you've considered**
`normalizeQuery` and `normalizedQueryHash`, but they don't "fix" formatting and can't be used to compare two queries with same semantics, but different formatting:
```
SELECT normalizedQueryHash('select 1') = normalizedQueryHash('SELECT 1')

┌─equals(normalizedQueryHash('select 1'), normalizedQueryHash('SELECT 1'))─┐
│                                                                        0 │
└──────────────────────────────────────────────────────────────────────────┘
```

**Comment by amosbird** [comment]
It will also help remove trailing semicolons.
