### ISSUE TITLE
Wrong documention about MaterializeMySQL

### ISSUE THREAD

**Issue by wzisheng** [ClickHouse/ClickHouse#27268]
I'm working in v21.3.4.25-lts.

Find there's a mistake in the documention : [https://clickhouse.tech/docs/en/engines/database-engines/materialized-mysql/#creating-a-database](url)

Should there be`CREATE DATABASE [IF NOT EXISTS] db_name [ON CLUSTER cluster]
ENGINE = MaterializeMySQL('host:port', ['database' | database], 'user', 'password') [SETTINGS ...]`

MaterializeMySQL  ≠   MaterializedMySQL
With MaterializedMySQL you may get `Code: 36, e.displayText() = DB::Exception: Database engine MaterializedMySQL cannot have arguments (version 21.3.4.25) (version 21.3.4.25)`

Please check, thanks

**Comment by den-crane** [comment]
It was renamed recently. Starting from 21.9 it will be  MaterializedMySQL. 
Documentation reflects this renaming.

https://github.com/ClickHouse/ClickHouse/pull/26822 Rename MaterializeMySQL to MaterializedMySQL

**Comment by wzisheng** [comment]
#26822
