### ISSUE TITLE
the aarch64 version Unknown table engine Hdfs.

### ISSUE THREAD

**Issue by weijiasheng** [ClickHouse/ClickHouse#27267]
Hi:
      I try install the  aarch64 version , use the follow commond,
     
curl -O 'https://builds.clickhouse.tech/master/aarch64/clickhouse' && chmod a+x ./clickhouse

create table test(id Int)ENGINE = Hdfs('hdfs://hdfsCluster/tmp/new_test/books.csv')
CREATE TABLE test
(
    `id` Int
)
ENGINE = Hdfs('hdfs://hdfsCluster/tmp/new_test/books.csv')

0 rows in set. Elapsed: 0.013 sec. 

Received exception from server (version 21.9.1):
Code: 56. DB::Exception: Received from localhost:9000. DB::Exception: Unknown table engine Hdfs.
UNKNOWN_STORAGE)

**Comment by den-crane** [comment]
aarch64 built without HDFS.
If you need HDFS you should fix make file and build by yourself.

**Comment by weijiasheng** [comment]
hi,I was success build at version 21.3.4.25,But I still not use the HDFS engine?
Is the some file I need modify? and how to modify? Thanks!

**Comment by weijiasheng** [comment]
> aarch64 built without HDFS.
> If you need HDFS you should fix make file and build by yourself.
hi,I was success build at version 21.3.4.25,But I still not use the HDFS engine?
Is the some file I need modify? and how to modify? Thanks!
