### ISSUE TITLE
How can we monitoring all unmerged parts(files)

### ISSUE THREAD

**Issue by imiskolee** [ClickHouse/ClickHouse#27276]
hi:
  
 In ReplacingMergeTree, I know duplicated rows can not automatically trigger merge when the part is not active, and we can focus trigger merge on SQL `optimize table ..... final deduplicated`.

update small records to old partition often happen(maybe just 1 or 2 records update), and it's always can not merge, based on 
performance reason I also can not use` FINAL` when querying data.

So, I am asking how to monitoring all unmerged parts, because we can set scheduled jobs to trigger the focus merge process.

**Comment by imiskolee** [comment]
or any configuration  to control the background merge thread to  trigger merge again when any data needs merge?

**Comment by den-crane** [comment]
https://stackoverflow.com/a/60436253/11644308
