### ISSUE TITLE
How does MATERIALIZED VIEW work when several tables involved?

### ISSUE THREAD

**Issue by NiDHanWang** [ClickHouse/ClickHouse#27274]
The documentation mentioned that:

**`When inserting data to the table specified in SELECT, part of the inserted data is converted by this SELECT query, and the result is inserted in the view.`**.

But if there're several tables involved in one SQL statement, how exactly would the MATERIALIZED VIEW be triggered?

The MATERIALIZED VIEW would be triggered when **any** table involved has some data being inserted into or **all** tables have?

**Comment by tavplubix** [comment]
Materialized view is triggered on insertion into the first table of SELECT query.
