### ISSUE TITLE
Documentation: incoming data (web analytics & sessioning) tutorial

### ISSUE THREAD

**Issue by xmariachi** [ClickHouse/ClickHouse#2728]
I think it would be beneficial to provide a simple yet illustrative tutorial on web sessioning to show the potential of ClickHouse on incoming data, to show examples of the deeper ideas behind ClickHouse. It is mentioned also in many points of the docs that the initial usage is Metrika, so it would be good to create a mini-Metrika that illustrates more important engines usage, where they shine and how to work with them, main integrations (Kafka, external sources as Dictionaries), hints on best practices, etc.

It would help onboarding and understanding ClickHouse for incoming data scenarios.

**Comment by blinkov** [comment]
Yep, it would be nice, though such tutorial will go well beyond just ClickHouse and will hardly be applicable "as is" to most companies. Tutorial on setting up small ClickHouse cluster lives here https://clickhouse.yandex/tutorial.html , but how to integrate it properly into existing company ecosystem is extremely individual.

**Comment by xmariachi** [comment]
> will hardly be applicable "as is" to most companies": Definitely! Not "as is", but as a starting point to get the concepts and understand the _dos_ and _don'ts_. 

Integrations may be well be totally separated - it's just additions I thought of that are pretty common on incoming data scenario, esp. Kafka).

**Comment by blinkov** [comment]
It's not that straightforward even if we talk just about Kafka. There's Kafka table engine https://clickhouse.yandex/docs/en/operations/table_engines/kafka/ which allows to SELECT from topic and INSERT INTO persistent table in ClickHouse. It sounds like a good way to go, but in practice companies tend to have some applications that read from persistent queue and do arbitrary non-declarative business logic before inserting data into storage like ClickHouse.

**Comment by xmariachi** [comment]
Indeed, and I have met some of these myself. We are using it and so far it's OK, apart from JSON parsing limitations.

However, the way I see it, I think the main benefit is in shedding light on CH for the incoming data scenario, especially using the Collapsing or other *MergeTree engines "in action" for event handling, event aggregation, windowing, etc.
