### ISSUE TITLE
MaterializeMySQL with AWS RDS failed

### ISSUE THREAD

**Issue by wangsoft** [ClickHouse/ClickHouse#27302]
**try to make ClickHouse as the slave of AWA RDS mysql , but failed**

Error Message:

2021.08.05 06:53:59.129906 [ 12603 ] {} <Error> MaterializeMySQLSyncThread: Poco::Exception. Code: 1000, e.code() = 1045, e.displayText() = mysqlxx::BadQuery: Access denied for user '*******'@'%' (using password: YES) (***********.amazonaws.com.cn:3306), Stack trace (when copying this message, always include the lines below):
 
0. mysqlxx::Query::executeImpl() @ 0x13307dc0 in /usr/lib/debug/.build-id/69/7a9902dce7a291c0e5ca723b17481126142a81.debug
1. DB::MaterializeMetadata::startReplication(mysqlxx::Pool::Entry&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > >&) @ 0xf808d3b in /usr/lib/debug/.build-id/69/7a9902dce7a291c0e5ca723b17481126142a81.debug
2. DB::MaterializeMySQLSyncThread::prepareSynchronized(DB::MaterializeMetadata&) @ 0xf7a9ee0 in /usr/lib/debug/.build-id/69/7a9902dce7a291c0e5ca723b17481126142a81.debug
3. DB::MaterializeMySQLSyncThread::synchronization() @ 0xf7a941c in /usr/lib/debug/.build-id/69/7a9902dce7a291c0e5ca723b17481126142a81.debug
4. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::MaterializeMySQLSyncThread::startSynchronization()::$_0>(DB::MaterializeMySQLSyncThread::startSynchronization()::$_0&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) @ 0xf7cbdf4 in /usr/lib/debug/.build-id/69/7a9902dce7a291c0e5ca723b17481126142a81.debug
5. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x8d6b91f in /usr/lib/debug/.build-id/69/7a9902dce7a291c0e5ca723b17481126142a81.debug
6. void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) @ 0x8d6f203 in /usr/lib/debug/.build-id/69/7a9902dce7a291c0e5ca723b17481126142a81.debug
7. start_thread @ 0x7dd5 in /usr/lib64/libpthread-2.17.so
8. __clone @ 0xfdead in /usr/lib64/libc-2.17.so
 (version 21.7.4.18 (official build))

**Comment by den-crane** [comment]
MaterializeMySQL supports only ORACLE mysql. 
 AWS RDS is not supported.

**Comment by wangsoft** [comment]
AWS RDS mysql is not  a mysql ？
