### ISSUE TITLE
FR: Data resharing without zookeeper

### ISSUE THREAD

**Issue by zhang2014** [ClickHouse/ClickHouse#2733]
This  is just a discussion. cc @sundy-li 

### Use ClusterCopier
 - Configure a complex
 - Heavy dependence on zookeeper
 - No good progress notification

### Use INSERT INTO SELECT
  - Very slow
  - Need to be offline

## Some of our ideas

> Support `ALTER TABLE table_name SEND PART part_name TO TABLE_FUNCTION(eg.remote)`

- Lock the part to prevent it merge
- execute ALTER TABLE migrate_to_table_name BEGIN SESSION TRANSACTION;
- INSERT INTO migrate_to_table_name 
- DETACH PART part_name
- execute ALTER TABLE migrate_to_table_name COMMIT SESSION TRANSACTION;
- DELETE DETACH PART part_name
 
### The problem of our ideas

- In rare cases the data is inconsistent

**Comment by alexey-milovidov** [comment]
> SEND PART part_name TO TABLE_FUNCTION

Table function remote is just a temporary Distributed table (a StorageDistributed object). How are you going to send data into it? The only possibility is to do the same as `INSERT INTO TABLE FUNCTION remote(...)`.

**Comment by blinkov** [comment]
Strategically it'd be better to fix the weak spots of current `clickhouse-copier` implementation instead of making yet another alternative to choose from.

**Comment by alexey-milovidov** [comment]
clickhouse-copier:
- coordination by ZooKeeper is by design;
- configuration complexity is unavoidable.

For progress, we look at system.parts on destination servers and at task nodes in ZK.

**Comment by blinkov** [comment]
Why unavoidable? For example, someone could make a GUI that sets it up via step-by-step wizard or something, and then displays running tasks with progress bars.

I think ZooKeeper by itself will hardly be a problem if you don't have to interact with it directly.

**Comment by zhang2014** [comment]
> Table function remote is just a temporary Distributed table (a StorageDistributed object). How are you going to send data into it? The only possibility is to do the same as INSERT INTO TABLE FUNCTION remote(...).

Yes, but it's transactional. 

## About transaction

> Support `ALTER TABLE table_name BEGIN TRANSACTION`

### Description about transaction implementation
1. Based on table and connection session
2. If a transaction is started, it will not be renameTempPartAndAdd. see: https://github.com/yandex/ClickHouse/blob/master/dbms/src/Storages/MergeTree/MergeTreeBlockOutputStream.cpp#L24
3. Distributed tables push transaction operations down

**Comment by zhang2014** [comment]
> Why unavoidable? For example, someone could make a GUI that sets it up via step-by-step wizard or something, and then displays running tasks with progress bars.
I think ZooKeeper by itself will hardly be a problem if you don't have to interact with it directly.

This is great, but we have some case is no zookeeper.

# About configuration complexity with ClusterCopier
https://clickhouse.yandex/docs/en/operations/utils/clickhouse-copier/#configuration-of-copying-tasks

It requires too much configuration that is actually easily accessible at the SQL layer. eg.
- Engine description
- source_cluster And destination_cluster
- sharding_key

**Comment by zhang2014** [comment]
Any questions about that ?
If not, I will complete a preliminary implementation as soon as possible. 
The code may be more conducive to discussion :)
