### ISSUE TITLE
Sorting rows within GROUP BY groups

### ISSUE THREAD

**Issue by vpanfilov** [ClickHouse/ClickHouse#2739]
Hi, I want to calculate some metrics, which are dependent on previous events with the given **session_id**, so I want to get correctly sorted arrays with `groupArray()` function. 

But Clickhouse documentation for `groupArray()` function says:
> Values can be added to the array in any (indeterminate) order.
> In some cases, you can still rely on the order of execution. This applies to cases when SELECT comes from a subquery that uses ORDER BY.

So I have only two options:
1. Use a subquery with `ORDER BY` clause;
2. Try to manually sort all rows with `arraySort` function.

Let's consider a following example. Create the following table;
```sql
CREATE TABLE test_group_by_sort
(
    id String,
    order Int32,
    data1 Int32,
    data2 Int32
)
ENGINE = TinyLog
```
And insert some data with random order:
```sql
INSERT INTO test_group_by_sort VALUES
('a', 3, 1, 2),
('b', 2, 4, 5),
('c', 1, 6, 3),
('a', 1, 2, 9),
('b', 1, 3, 4),
('a', 2, 5, 3),
('c', 2, 1, 2);
```

Imagine that we want to calculate running differences for columns **data1** and **data2** with grouping by **id** columns.

**1. Subquery with `ORDER BY` clause:**

I have not found a way to use `runningDifference` functions with `GROUP BY` clause, so I used higher-order functions to achieve the desired result:
```sql
SELECT * FROM 
(WITH
	groupArray(order) AS order,
	groupArray(data1) AS data1,
	groupArray(data2) AS data2,
	arrayEnumerate(order) AS index,
	arrayMap((x, i) -> 
		if(i != 1, x - data1[i-1], 0),
		data1, index) AS data1_diff,
	arrayMap((x, i) -> 
		if(i != 1, x - data2[i-1], 0),
		data2, index) AS data2_diff
SELECT
	id, order,
	data1, data1_diff,
	data2, data2_diff
FROM
(SELECT *
FROM test_group_by_sort
ORDER BY id, order)
GROUP BY id
ORDER BY id)
ARRAY JOIN order, data1, data1_diff, data2, data2_diff

┌─id─┬─order─┬─data1─┬─data1_diff─┬─data2─┬─data2_diff─┐
│ a  │     1 │     2 │          0 │     9 │          0 │
│ a  │     2 │     5 │          3 │     3 │         -6 │
│ a  │     3 │     1 │         -4 │     2 │         -1 │
│ b  │     1 │     3 │          0 │     4 │          0 │
│ b  │     2 │     4 │          1 │     5 │          1 │
│ c  │     1 │     6 │          0 │     3 │          0 │
│ c  │     2 │     1 │         -5 │     2 │         -1 │
└────┴───────┴───────┴────────────┴───────┴────────────┘
```

**2. Manually sort all rows with `arraySort` function:**

Here I need to create an array of tuples to sort all columns at once by `order` column:
```sql
WITH
	groupArray(tuple(order, data1, data2)) AS data,
	arrayEnumerate(data) AS index,
	arraySort(x -> x.1, data) AS sorted_data,
	arrayMap((x, i) -> tuple(
		x.1, x.2,
		if(i != 1, x.2 - sorted_data[i-1].2, 0),
		x.3,
		if(i != 1, x.3 - sorted_data[i-1].3, 0)
	), sorted_data, index) AS result_array,
	arrayJoin(result_array) AS result
SELECT
	id,
	result.1 AS sorted_order,
	result.2 AS sorted_data1,
	result.3 AS sorted_data1_diff,
	result.4 AS sorted_data2,
	result.5 AS sorted_data2_diff
FROM test_group_by_sort
GROUP BY id
ORDER BY id

┌─id─┬─sorted_order─┬─sorted_data1─┬─sorted_data1_diff─┬─sorted_data2─┬─sorted_data2_diff─┐
│ a  │            1 │            2 │                 0 │            9 │                 0 │
│ a  │            2 │            5 │                 3 │            3 │                -6 │
│ a  │            3 │            1 │                -4 │            2 │                -1 │
│ b  │            1 │            3 │                 0 │            4 │                 0 │
│ b  │            2 │            4 │                 1 │            5 │                 1 │
│ c  │            1 │            6 │                 0 │            3 │                 0 │
│ c  │            2 │            1 │                -5 │            2 │                -1 │
└────┴──────────────┴──────────────┴───────────────────┴──────────────┴───────────────────┘
```

As you can see, the results are the same. But which solution is preferrable from the performance point of view? Will there be any surprises with distributed tables? Are there any other approaches to calculate metrics depending on row ordering within groups?

**Comment by blinkov** [comment]
@vpanfilov, is this question still relevant?

**Comment by filimonov** [comment]
Related: https://github.com/ClickHouse/ClickHouse/issues/2739

**Comment by alexey-milovidov** [comment]
Related: #3708

**Comment by alexey-milovidov** [comment]
@vpanfilov Variant 2 is more preferrable, it should work better for distributed queries.
