### ISSUE TITLE
Session is locked by a concurrent client

### ISSUE THREAD

**Issue by liangxianjin** [ClickHouse/ClickHouse#27425]
Caused by: ru.yandex.clickhouse.except.ClickHouseException: ClickHouse exception, code: 373, host: xxx.xxx.xx.xx, port: 8123; Code: 373, e.displayText() = DB::Exception: Session is locked by a concurrent client. (version 20.2.1.2183 (official build))
hello!  give me a hand. 
![image](https://user-images.githubusercontent.com/45254883/128630131-87ffaba8-4937-4f9d-bfa7-bed856d68ced.png)
I wrote a set of JDBC connection pool myself. In case of concurrency, the exceptions on the package will be

**Comment by den-crane** [comment]
Show how you create / setup your `this.dataSource`.
It seems you reuse `session_id` which is incorrect. Each connection must have different  `session_id`.

**Comment by liangxianjin** [comment]
![image](https://user-images.githubusercontent.com/45254883/128652029-6e0f4dda-cbb0-4ea8-863f-c19462e87c06.png)
OK, I  need to try

**Comment by liangxianjin** [comment]
Thank you. It has been solved

**Comment by TechGeorgii** [comment]
Started getting this error frequently, DBeaver, JDBC driver 0.9.4. Not sure if is the reason, but driver was recently updated from 0.8.something. Is there anyone experiencing this?

**Comment by iamtalhaasghar** [comment]
> Started getting this error frequently, DBeaver, JDBC driver 0.9.4. Not sure if is the reason, but driver was recently updated from 0.8.something. Is there anyone experiencing this?

To be exact it broke down in v0.9.1. read more here. https://github.com/ClickHouse/clickhouse-java/issues/2690#issuecomment-3782693004.

Thank you for sharing your observation @TechGeorgii  it really helped me with pin pointing exactly where the problem is.
