### ISSUE TITLE
Do we have plan to support data rebalance when new node join into cluster?

### ISSUE THREAD

**Issue by godliness** [ClickHouse/ClickHouse#27453]
If ClickHouse use S3 as storage level, we need rebalance metadata when new shard node join in cluster, if ClickHouse use local disk as storage level, we need rebalance parts files between shards when new shard node join in cluster.

Do we have plan to support above feature? If we have, how to plan to implement it, do we need implement a new coordinator component system to do this? just like **hbase** that **hmaster**(coordinator) responsible for rebalancing regions?

Any answer will be appreciated!

**Comment by den-crane** [comment]
Yes, it's the wanted feature. But it's not planned for the near future. Maybe 2023.
