### ISSUE TITLE
different query duration time

### ISSUE THREAD

**Issue by onine007** [ClickHouse/ClickHouse#27451]
version: 21.3.14 
users is a Distributed table 

![微信截图_20210809145826_11](https://user-images.githubusercontent.com/24770345/128669992-7709aae6-505a-4bdf-97a1-ffb3d41693ca.png)
![微信截图_20210809145907_22](https://user-images.githubusercontent.com/24770345/128669996-b89f24fe-8a69-4000-8cdd-7e93b93ec31a.png)
why these two queries  take different query duration time  ? 
is it any settings can auto  convert query1 to query2 ?

**Comment by amosbird** [comment]
> why these two queries take different query duration time ?

ClickHouse doesn't do distributed processing over subqueries.

> is it any settings can auto convert query1 to query2 ?

Not yet.
