### ISSUE TITLE
toDatetime64() function truncates millisecond.

### ISSUE THREAD

**Issue by deltacat** [ClickHouse/ClickHouse#27468]
**Describe the bug**

toDatetime64() function truncates millisecond.

The clickhouse [document for DateTime64](https://clickhouse.tech/docs/en/sql-reference/data-types/datetime64/): 

- `Tick size (precision): 10-precision seconds`
- `DateTime64(precision, [timezone])`

As my understood, precision 3 means milliseconds, so, toDateTime64(1628499775912，3) should be today "2021-08-09 09:02:55.912". 
But it works incorrect, the number was converted as a "unix timestamp in second" and overflow, result to "2282-12-31 00:00:00.000".

**Does it reproduce on recent release?**

yes, could be reproduce on v21.7.5.29 and v21.7.4.??

**How to reproduce**

* Which ClickHouse server version to use: v21.7.5.29 (official docker image)
* Which interface to use, if matters: all of these interface/client:
  * official clickhouse-client
  * offical jdbc driver
  * DBeaver
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved: with no need for such case

then, it's easy to produce:

case 1: expect today, but not.

```
SELECT toDateTime64(1628499775912, 3)

Query id: 6d0bb7a2-0cd1-4424-a197-4ef320bd1337

┌─toDateTime64(1628499775912, 3)─┐
│        2282-12-31 00:00:00.000 │
└────────────────────────────────┘
```

case 2: T2 should be 1628499775912 but got 1628499775

```
SELECT
    toDateTime64('2021-08-09 09:02:55.912', 3) AS t1,
    toUInt64(toDateTime64('2021-08-09 09:02:55.912', 3)) AS t2

Query id: 7e07190a-ecbf-444d-be6a-48a04568c33a

┌──────────────────────t1─┬─────────t2─┐
│ 2021-08-09 09:02:55.912 │ 1628499775 │
└─────────────────────────┴────────────┘
```

case 2: t1 should be same as T2, but T2 lost milliseconds.

```plain
SELECT
    toDateTime64('2021-08-09 09:02:55.912', 3) AS t1,
    toDateTime64(toUInt64(toDateTime64('2021-08-09 09:02:55.912', 3)), 3) AS t2

Query id: 3d5add57-84ff-46a1-b3cf-f5a04ba3284b

┌──────────────────────t1─┬──────────────────────t2─┐
│ 2021-08-09 09:02:55.912 │ 2021-08-09 09:02:55.000 │
└─────────────────────────┴─────────────────────────┘
```

**Expected behavior**

toDateTime64() function should keep millisecond.

**Comment by den-crane** [comment]
toDateTime64 expects millisecond separated by . dot.  1628499775.912

```
SELECT toDateTime64(1628499775.912, 3)
┌─toDateTime64(1628499775.912, 3)─┐
│         2021-08-09 09:02:55.912 │
└─────────────────────────────────┘
```

You are looking for fromUnixTimestamp64Milli

```
SELECT fromUnixTimestamp64Milli(toInt64(1628499775912))

┌─fromUnixTimestamp64Milli(toInt64(1628499775912))─┐
│                          2021-08-09 09:02:55.912 │
└──────────────────────────────────────────────────┘
```

Or 

```
SELECT reinterpret(1628499775912, 'DateTime64(3)')
┌─reinterpret(1628499775912, 'DateTime64(3)')─┐
│                     2021-08-09 09:02:55.912 │
└─────────────────────────────────────────────┘
```

**Comment by deltacat** [comment]
@den-crane thx a lot. It's my fault.
