### ISSUE TITLE
RIGHT(x, n) does not work over distributed table

### ISSUE THREAD

**Issue by knoguchi** [ClickHouse/ClickHouse#27504]
**Describe the bug**

SELECT RIGHT(x, n) does not work over Distributed engine table.

RIGHT(x, n) is translated to substring(x, negate(n)).  
It appears negate(n) does not work over distributed table.

**Does it reproduce on recent release?**

I do not have test environment with recent release.

**How to reproduce**

* Which ClickHouse server version to use
21.3.4

* `CREATE TABLE` statements for all tables involved
In a cluster environment "mycluster", create a table "tbl" on each shard, and create a distributed table "dtbl".
```
create table default.tbl on cluster mycluster (name String) engine=Memory;
create table default.dtbl (name String) ENGINE=Distributed('mycluster', 'default', 'tbl', rand());
```
* Sample data for all these tables
On one of the shards
```
insert into default.tbl (name) values ('hello.usa');
```
* Queries to run that lead to unexpected result
```
select RIGHT(name, 3) from default.dtbl;
```

**Expected behavior**

It should return `usa`

**Error message and/or stacktrace**

```
Received exception from server (version 21.3.4):
Code: 10. DB::Exception: Received from localhost:9000. DB::Exception: Not found column substring(name, negate(3)) in block. There are only columns: substring(name, -3): While executing Remote.
```

**Additional context**
```
select substring(name, negate(3)) from default.dtbl;
``` 
got the same error.

```
select substring(name, -3) from default.dtbl;
```
works fine.

**Comment by den-crane** [comment]
It seems you have 2 different versions of CH in the cluster.

Please share `select materialize(version()) from clusterAllReplicas(mycluster, system.one);`

**Comment by knoguchi** [comment]
All 21.3.4.25
```
SELECT materialize(version())
FROM clusterAllReplicas(mycluster, system.one)
FORMAT CSV

Query id: 1dd7c6c1-fb70-462a-9fb3-35c23ab1436f

"21.3.4.25"
"21.3.4.25"
"21.3.4.25"
"21.3.4.25"
"21.3.4.25"
"21.3.4.25"
"21.3.4.25"
"21.3.4.25"
"21.3.4.25"
"21.3.4.25"
"21.3.4.25"
"21.3.4.25"
"21.3.4.25"
"21.3.4.25"
"21.3.4.25"
"21.3.4.25"

16 rows in set. Elapsed: 0.009 sec.
```

**Comment by knoguchi** [comment]
I upgraded all of my ClickHouse nodes to 21.7.3.14.   I used the same test method, and confirmed RIGHT() works fine.

Though the version was consistently 21.3.4.25, your comment is interesting.  It sounds like queries could fail during rolling upgrade if two different versions are in CH cluster.

**Comment by den-crane** [comment]
then it strange that I cannot reproduce the issue

```
21.3.4.25

select  RIGHT(toString(dummy), 3)  from remote(test_cluster_two_shards_localhost, system.one);
┌─substring(toString(dummy), negate(3))─┐
│ 0                                     │
└───────────────────────────────────────┘
┌─substring(toString(dummy), negate(3))─┐
│ 0                                     │
└───────────────────────────────────────┘
```

**Comment by den-crane** [comment]
> It sounds like queries could fail during rolling upgrade if two different versions are in a CH cluster?

Yes, it could.

**Comment by knoguchi** [comment]
Thanks for checking.   Though the root cause is still unknown I will close this ticket.   I will report back if I hit the same problem again.
