### ISSUE TITLE
isNull(toDateOrNull(<invalidate date>)) has a bug

### ISSUE THREAD

**Issue by leitelyaya** [ClickHouse/ClickHouse#27515]
**Describe the bug**

> I need filter invalidate date. I've tried to use the function isNull(toDateOrNull(date))=1, but got the unexcept result when the date string contains any special character like '|' or ';'.

**Does it reproduce on recent release?**
> yes, I've tested the lastet version.

**How to reproduce**

* Which ClickHouse server version to use
> 21.7.6.39; 19.9.5.36
* Queries to run that lead to unexpected result
`select isNull(toDateOrNull(null)), toDateOrNull('20210810'), isNull(toDateOrNull('20210810')), toDateOrNull('210804|0'), isNull(toDateOrNull('210804|0'))`

**Expected behavior**

> I want to get 'true' if different format of invalidate date like "210804|0"

**Comment by vdimir** [comment]
It returns `true` in provided case. What result do you expect?

```
SELECT
    isNull(toDateOrNull('2021-08-10')),
    isNull(toDateOrNull(NULL)),
    toDateOrNull('20210810'),
    isNull(toDateOrNull('20210810')),
    toDateOrNull('210804|0'),
    isNull(toDateOrNull('210804|0'))

Query id: 1913bee9-9396-4173-9280-0942d0a59dc9

┌─isNull(toDateOrNull('2021-08-10'))─┬─isNull(toDateOrNull(NULL))─┬─toDateOrNull('20210810')─┬─isNull(toDateOrNull('20210810'))─┬─toDateOrNull('210804|0')─┬─isNull(toDateOrNull('210804|0'))─┐
│                                  0 │                          1 │                     ᴺᵁᴸᴸ │                                1 │                     ᴺᵁᴸᴸ │                                1 │
└────────────────────────────────────┴────────────────────────────┴──────────────────────────┴──────────────────────────────────┴──────────────────────────┴──────────────────────────────────┘
```

**Comment by leitelyaya** [comment]
@vdimir I got different results.

from version 21.7.6.39:
`
SELECT
    isNull(toDateOrNull(NULL)),
    toDateOrNull('20210810'),
    isNull(toDateOrNull('20210810')),
    toDateOrNull('210804|0'),
    isNull(toDateOrNull('210804|0'))
FORMAT Vertical

Query id: 4bfcd591-f419-4dd9-bb5d-a3b2b69a80c4

Row 1:
──────
isNull(toDateOrNull(NULL)):       1
toDateOrNull('20210810'):         ᴺᵁᴸᴸ
isNull(toDateOrNull('20210810')): 1
toDateOrNull('210804|0'):         1970-01-01
isNull(toDateOrNull('210804|0')): 0
`

from version 19.9.5.36:
`
SELECT 
    isNull(toDateOrNull(NULL)), 
    toDateOrNull('20210810'), 
    isNull(toDateOrNull('20210810')), 
    toDateOrNull('210804|0'), 
    isNull(toDateOrNull('210804|0'))
FORMAT Vertical

Row 1:
──────
isNull(toDateOrNull(NULL)):       1
toDateOrNull('20210810'):         ᴺᵁᴸᴸ
isNull(toDateOrNull('20210810')): 1
toDateOrNull('210804|0'):         0000-00-00
isNull(toDateOrNull('210804|0')): 0
`

**Comment by alexey-milovidov** [comment]
Upgrade to version 21.8.

21.7:
```
┌─toDateOrNull('210804|0')─┐
│               1970-01-01 │
└──────────────────────────┘
```

21.8:
```
┌─toDateOrNull('210804|0')─┐
│                     ᴺᵁᴸᴸ │
└──────────────────────────┘
```
