### ISSUE TITLE
multiSearchAny function with subquery

### ISSUE THREAD

**Issue by matterumirai** [ClickHouse/ClickHouse#27517]
Hello,

i want to search whole column values in a subquery like query below:

`select * from myTable where multiSearchAny(column,(select col from table)) `   is not working for subquery

is there any way or function to achieve this?

Thanks in advance.

**Comment by vdimir** [comment]
You can use [WITH](https://clickhouse.tech/docs/en/sql-reference/statements/select/with/) statement
```
CREATE TABLE t1 (col String) ENGINE = Memory;
INSERT INTO t1 VALUES ('aaaa'),('bbbb'),('xxxx'),('uuuuu');

CREATE TABLE t2 (key String) ENGINE = Memory;
INSERT INTO t2 VALUES ('a'),('b'),('c');
```

```
WITH (select groupArray(key) from t2) as keys SELECT * from t1 WHERE multiSearchAny(col, keys);

┌─col──┐
│ aaaa │
│ bbbb │
└──────┘
```

**Comment by matterumirai** [comment]
@vdimir Thanks for the answer it works properly.

In multiSearchAny function  the number of keys should be at most 255 because of implementation specification.

Do you have any idea how can i use all keys (more than 255) in the function without any script just with query?

**Comment by vdimir** [comment]
> Do you have any idea how can i use all keys (more than 255) in the function without any script just with query?

If you know upper bound for the number of keys you can make several keys array with `OFFSET` and `LIMIT` if sub-queries. For arbitrary number of keys there should be other solution, maybe using `position` (single version, no `multi-`) and some kind of JOIN.
