### ISSUE TITLE
DB::Exception: Memory limit (total) exceeded

### ISSUE THREAD

**Issue by TheAlexCH** [ClickHouse/ClickHouse#27522]
Hi,

After getting some first help on stackexchange and reading hours through all other issues, I am not able to find any solution to the RAM consumtion problem and the fact that Clickhouse seems never happy with the RAM settings. 

Code: 241, e.displayText() = DB::Exception: Memory limit (total) exceeded: would use 55.85 GiB (attempt to allocate chunk of 135926032 bytes), maximum: 55.83 GiB: While executing AggregatingTransform (version 21.4.6.55 (official build))

First I had 12 GB ram and now 62 of wich I allocate 54 GB to CH and it is still not happy.

**Settings:**
<max_memory_usage>54000000000</max_memory_usage>
<max_threads>3</max_threads>
<max_block_size>65536</max_block_size>
<max_bytes_before_external_group_by>15000000000</max_bytes_before_external_group_by>
<aggregation_memory_efficient_merge_threads>1</aggregation_memory_efficient_merge_threads>

**Query I am running:** 
CREATE MATERIALIZED VIEW testDB.view2
ENGINE=SummingMergeTree () 
ORDER BY groupingId
POPULATE
AS 
SELECT 	
	groupingId,
	count(distinct id) as idCount,
	sum(amount) / 100000000 as amtBalance
from testDB.`testTable` tt
group by groupingId

The setting max_bytes_before_external_group_by helped to prolong the moment my query is failing. 

If this is not a bug, please ellaborate on how I can resolve this issue.

Table is 200 GB in CH with around 3 billion rows (not many columns, mainly int64).

**NOTE**
I have been watching HTOP on ubuntu the entire time and at no point I saw the ram surpassing the 15 GB of consumption which I believe are the limits by my settings (external group by). I have tried with max threads 1,2,3,4 and many other combinations of those settigs above. None worked. Eventually, ram runs out.

**Comment by den-crane** [comment]
Does it fail if you run this

```
SELECT
groupingId,
count(distinct id) as idCount,
sum(amount) / 100000000 as amtBalance
from testDB.testTable tt
group by groupingId
format Null
```

**Comment by den-crane** [comment]
You can do back-population using Null table https://gist.github.com/den-crane/f7382cd4f1f859ff6ac46afe7dc9925a

https://den-crane.github.io/Everything_you_should_know_about_materialized_views_commented.pdf
