### ISSUE TITLE
ClickHouse release v20.9.3.45 - Alter table freeze fails with "directory already exists and is not empty" error

### ISSUE THREAD

**Issue by sushraju** [ClickHouse/ClickHouse#27532]
As part of backing up a table, the ```ALTER TABLE `db`.`table_name` FREEZE WITH NAME '<name>'``` command fails with 

```
"error can't freeze table: code: 84, message: Directory /var/lib/clickhouse/shadow/d57f9386bfb34faeae1a2d275cf051ea/data/<db>/<table_name>/20201105_0_9627_12 already exists and is not empty."
```

**Does it reproduce on recent release?**

This is a production cluster running on v20.9.3.45.  This issue hasn't been seen on other clusters where we have enabled backups. 

We haven't upgraded to a release later than v20.9.3.45.

**Comment by den-crane** [comment]
20.9.3.45 is out of support.

>This issue hasn't been seen on other clusters where we have enabled backups.

You have Atomic database in this setup and Ordinary in others.
Compare `show create database db`.
And 20.9 misses '<name>' in the folders name in case of Atomic.

It seems has been fixed in later versions.

```
create database test Engine=Atomic;
create table test.test(a Int64) Engine=MergeTree order by a;
insert into test.test select number from numbers(10000000);
alter table test.test freeze with name 'test';

alter table test.test freeze with name 'test';
DB::Exception: Directory /var/lib/clickhouse/shadow/    test    /store/5e3/5e3687c9-4150-4efe-9e36-87c941500efe/all_1_6_1 already exists and is not empty.. (DIRECTORY_ALREADY_EXISTS)
```

**Comment by sushraju** [comment]
Thanks for the quick response.  Here's the output:

```
show create database default;

CREATE DATABASE default\nENGINE = Ordinary
```

Can you point me to a bug that was specifically fixed?

**Comment by den-crane** [comment]
ENGINE = Ordinary cannot produce this path `d57f9386bfb34faeae1a2d275cf051ea/data/<db>/<table_name>` -- it's impossible. 

Can you share trace of `ALTER TABLE db.table_name FREEZE WITH NAME '<name>'` from clickhouse-server.log ?

**Comment by sushraju** [comment]
@den-crane Thanks for your support on this.  I don't think this is an issue with the Clickhouse cluster.  This is more of an issue with the backup tool that is running the freeze query. The db connect read timeout needs to be higher for large clusters.

I will close this issue.
