### ISSUE TITLE
unable restart upgrade 21.3 from 20.6

### ISSUE THREAD

**Issue by tiantiantian808** [ClickHouse/ClickHouse#27543]
> upgrade clickhouse 21.3 from 20.6，clickhouse server unable restart，the service is in deadlock state

![image](https://user-images.githubusercontent.com/20608540/128961949-e0bffb93-57cd-4fd0-8a46-a698ac8b6572.png)

![image](https://user-images.githubusercontent.com/20608540/128962139-0932fab3-bc6e-4c02-ab9f-0f405f178c56.png)

**Comment by den-crane** [comment]
Your message is very unclear. Share all logs as text (attach file if text is long). 
Do not post pictures, nobody like pictures, you will never get a reply.

**Comment by tiantiantian808** [comment]
We use the upgrade step 20.6 -> 20.10 -> 21.3, can get up, but delete the partition appeared the following exception
021.08.12 08:03:18.274452 [ 30164 ] {d02856e8-80bb-4ff8-a220-8b1ac452218c} <Error> executeQuery: Code: 529, e.displayText() = DB::Exception: DROP PART|PARTITION cannot be done on this replica because it is not a leader (version 21.3.13.9 (official build)) (from [::ffff:172.21.70.166]:59028) (in query: alter table xstore_group_data.selectsite_all_date_local drop partition '20210811'), Stack trace (when copying this message, always include the lines below):

0. DB::StorageReplicatedMergeTree::dropPartition(std::__1::shared_ptr<DB::IAST> const&, bool, bool, DB::Context const&, bool) @ 0xf1ef94e in /data0/jdolap/clickhouse/lib/clickhouse
1. DB::MergeTreeData::alterPartition(std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::vector<DB::PartitionCommand, std::__1::allocator<DB::PartitionCommand> > const&, DB::Context const&) @ 0xf3c053f in /data0/jdolap/clickhouse/lib/clickhouse
2. DB::InterpreterAlterQuery::execute() @ 0xe9d86fe in /data0/jdolap/clickhouse/lib/clickhouse
3. ? @ 0xeef43b2 in /data0/jdolap/clickhouse/lib/clickhouse
4. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, DB::Context&, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>) @ 0xeef7a85 in /data0/jdolap/clickhouse/lib/clickhouse
5. DB::HTTPHandler::processQuery(DB::Context&, DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::__1::optional<DB::CurrentThread::QueryScope>&) @ 0xf6156fa in /data0/jdolap/clickhouse/lib/clickhouse
6. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0xf61988e in /data0/jdolap/clickhouse/lib/clickhouse
7. DB::HTTPServerConnection::run() @ 0xf69fb2f in /data0/jdolap/clickhouse/lib/clickhouse
8. Poco::Net::TCPServerConnection::start() @ 0x11d4bb0f in /data0/jdolap/clickhouse/lib/clickhouse
9. Poco::Net::TCPServerDispatcher::run() @ 0x11d4d521 in /data0/jdolap/clickhouse/lib/clickhouse
10. Poco::PooledThread::run() @ 0x11e83c49 in /data0/jdolap/clickhouse/lib/clickhouse
11. Poco::ThreadImpl::runnableEntry(void*) @ 0x11e7faaa in /data0/jdolap/clickhouse/lib/clickhouse
12. start_thread @ 0x7dc5 in /usr/lib64/libpthread-2.17.so
13. clone @ 0xf621d in /usr/lib64/libc-2.17.so

**Comment by tiantiantian808** [comment]
The cause has been found，The default BackgroundSchedulePool is used up. The default is 16

**Comment by tiantiantian808** [comment]
> Your message is very unclear. Share all logs as text (attach file if text is long).
> Do not post pictures, nobody like pictures, you will never get a reply.

The cause has been found，The default BackgroundSchedulePool is used up. The default is 16

**Comment by alexey-milovidov** [comment]
Ok. It can be related to a huge amount of Distributed or Buffer tables.
I will close this issue as it is resolved.

**Comment by sunny19930321** [comment]
> Ok. It can be related to a huge amount of Distributed or Buffer tables.
> I will close this issue as it is resolved.

ok
