### ISSUE TITLE
Is there any effective solution for ClickHouse to support GDPR?

### ISSUE THREAD

**Issue by fsgdgsdfgsgd** [ClickHouse/ClickHouse#27559]
In order to meet GDPR requirements, we want to enable users to choose whether to delete their personal data. We have tried several solutions and I will share them below.

Solution 1: Use CollapsingMergeTree engine
We normally use ReplicatedMergeTree as our table engine. When we switched the table engine to CollapsingMergeTree, we noticed that some of our query performance dropped very severely. And because the deletion process of CollapsingMergeTree is asynchronous, users will see inconsistent data.

Solution 2: Use external dictionary
In this solution, we store user's personal data in another database. And we use dictionary to query personal data from another database.
The advantages of this solution is that if we do not need to query the columns related to the user's personal data, it will not affect the query performance. And it's easy to delete data from other databases.

We tested two data sources: Redis and ClickHouse. The layout of the dictionary is complex_key_direct.
1) ClickHouse
Because ClickHouse is not good at deleting data, we use other tools to delete the data and then import it again. Because user's personal data is not large, this method is acceptable.
But ClickHouse has poor performance as a dictionary source in our case. Queries are very easy to time out.

2) Redis
The performance of Redis can meet the requirements, but because the Redis cluster cannot be used as the dictionary source now (maybe because of some bugs, I raised another [issue](https://github.com/ClickHouse/ClickHouse/issues/27123) to discuss it), so this solution has also been abandoned. 

Solution 3: Use ALTER TABLE … DELETE Statement
This deletion is also asynchronous and we found that when we want to delete a large amount of data, the performance of ClickHouse will drop drastically.

Solution 4: Use JOIN clause
In this solution, we store the user's personal data in another table and use JOIN clause to query personal data if needed.
The performance of this solution is barely possible. We may try some optimizations to see if we can improve performance.

Forgot to mention. We have terabytes of data. And our analysis system is interactive, so the query cannot execute too long.

Does anyone have any good suggestions? It would be really helpful.

**Comment by den-crane** [comment]
>Solution 3: Use ALTER TABLE … DELETE Statement

`ALTER TABLE … DELETE` was implemented exactly to solve this problem. BUT you should run a small number of mutations during day / or better week. 
I suggest to accumulate IDs of users which should be deleted somewhere in backend (mysql) or CH table (user_ids_to_delete) and once a week run 1 mutation `ALTER TABLE … DELETE where id in ( {list from user_ids_to_delete} )` or `ALTER TABLE … DELETE where id in (select id from user_ids_to_delete)`.

Also you can tune merge tree settings

```
max_replicated_mutations_in_queue ( 8 )  
How many tasks of mutating parts are allowed simultaneously in ReplicatedMergeTree queue.                                                                                    

number_of_free_entries_in_pool_to_execute_mutation ( 10 ) 
When there is less than specified number of free entries in pool, do not execute part mutations. 
This is to leave free threads for regular merges and avoid "Too many parts"
```

**Comment by lz19970205** [comment]
> > Solution 3: Use ALTER TABLE … DELETE Statement
> 
> `ALTER TABLE … DELETE` was implemented exactly to solve this problem. BUT you should run a small number of mutations during day / or better week.
> I suggest to accumulate IDs of users which should be deleted somewhere in backend (mysql) or CH table (user_ids_to_delete) and once a week run 1 mutation `ALTER TABLE … DELETE where id in ( {list from user_ids_to_delete} )` or `ALTER TABLE … DELETE where id in (select id from user_ids_to_delete)`.
> 
> Also you can tune merge tree settings
> 
> ```
> max_replicated_mutations_in_queue ( 8 )  
> How many tasks of mutating parts are allowed simultaneously in ReplicatedMergeTree queue.                                                                                    
> 
> number_of_free_entries_in_pool_to_execute_mutation ( 10 ) 
> When there is less than specified number of free entries in pool, do not execute part mutations. 
> This is to leave free threads for regular merges and avoid "Too many parts"
> ```

Thanks for reply! I understand what you mean, but I have some questions.
1. If the ClickHouse is very busy, then the data may not be deleted for a long time, right?
2. If a mutation has already started execution, will its execution be interrupted when a client request comes? If not, I think a too heavy mutation may affect the performance of CH?
3. I under that the 'max_replicated_mutations_in_queue' will only affect the memory consumption? Does this parameter have other effects?

**Comment by den-crane** [comment]
1. Yes. Mutations can run for very long time. This is expected. It's not an issue for GDPR. GDPR does not require immediate actions.
2. No it will not be interrupted. Mutations may affect performance. BUT there is no difference between mutation and merges.  Mutation is a special type of Merge and merges are running all time and they also affect SELECTs performance.
3. It affects MEMORY/CPU/DISK IO.

**Comment by lz19970205** [comment]
> 1. Yes. Mutations can run for very long time. This is expected. It's not an issue for GDPR. GDPR does not require immediate actions.
> 2. No it will not be interrupted. Mutations may affect performance. BUT there is no difference between mutation and merges.  Mutation is a special type of Merge and merges are running all time and they also affect SELECTs performance.
> 3. It affects MEMORY/CPU/DISK IO.

Thanks! This is really helpful! We will make some optimizations based on your suggestions, and then see how the performance is.
