### ISSUE TITLE
why did ch merge only one part?

### ISSUE THREAD

**Issue by chenk818** [ClickHouse/ClickHouse#27565]
ClickHouse server version 21.3.4 revision 54447
select table,elapsed,source_part_names,result_part_name from system.merges;

the result is like below:
![image](https://user-images.githubusercontent.com/1886495/129027298-d744ca5d-328e-421e-b1ff-ae19c6922614.png)

and these merges looks like hanged(elpaed more than 16 hours)

**Comment by den-crane** [comment]
Check `is_mutation` column.
And share `select * from system.mutation where not is_done`.

**Comment by den-crane** [comment]
So it's a mutations. Healthy and running. 
Mutations can run for very long, because they re-write all data in related parts. Basically Mutation reads all data in the parts and writes it back without deleted rows.
