### ISSUE TITLE
install of latest version 20.2.1.2183 is not successful

### ISSUE THREAD

**Issue by sigirisetti** [ClickHouse/ClickHouse#27560]
Hi all,

I tried to install latest version , 20.2.1.2183, by manually downloading tgz as suggested in install page but hitting below error

Can you please suggest whats going wrong?

tried 

sudo /etc/init.d/clickhouse-server start

as well as

sudo -u clickhouse clickhouse-server --config-file=/etc/clickhouse-server/config.xml

Thanks
Surya

$ sudo -u clickhouse clickhouse-server --config-file=/etc/clickhouse-server/config.xml
Include not found: clickhouse_remote_servers
Include not found: clickhouse_compression
Logging trace to /var/log/clickhouse-server/clickhouse-server.log
Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
Logging trace to console
2021.08.11 19:29:18.212085 [ 1 ] {} <Trace> Pipe: Pipe capacity is 1.00 MiB
2021.08.11 19:29:18.214780 [ 1 ] {} <Information> : Starting ClickHouse 20.2.1.2183 with revision 54432
2021.08.11 19:29:18.214828 [ 1 ] {} <Information> Application: starting up
2021.08.11 19:29:18.217890 [ 1 ] {} <Debug> Application: Set max number of file descriptors to 4096 (was 1024).
2021.08.11 19:29:18.217909 [ 1 ] {} <Debug> Application: Initializing DateLUT.
2021.08.11 19:29:18.217922 [ 1 ] {} <Trace> Application: Initialized DateLUT with time zone 'Asia/Singapore'.
2021.08.11 19:29:18.218084 [ 1 ] {} <Debug> Application: Configuration parameter 'interserver_http_host' doesn't exist or exists and empty. Will use 'appuprakhya-ThinkPad-T470p' as replica host.
2021.08.11 19:29:18.220040 [ 1 ] {} <Debug> ConfigReloader: Loading config '/etc/clickhouse-server/users.xml'
Include not found: networks
2021.08.11 19:29:18.220728 [ 1 ] {} <Information> Application: Loading metadata from /var/lib/clickhouse/
2021.08.11 19:29:18.299031 [ 1 ] {} <Error> Application: Caught exception while loading metadata: Code: 62, e.displayText() = DB::Exception: Syntax error (in file /var/lib/clickhouse/metadata/system.sql): failed at position 19 (line 1, col 19): UUID '61258d5c-6949-4e2d-9ad8-28c243b86fde'
ENGINE = Atomic
. Expected one of: ON, ENGINE, storage definition, Stack trace (when copying this message, always include the lines below):

0. 0xbc6e05c Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) /build/obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/Exception.cpp:27 in /usr/lib/debug/usr/bin/clickhouse
1. 0x4f8d739 DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) /build/obj-x86_64-linux-gnu/../dbms/src/Common/Exception.cpp:35 in /usr/lib/debug/usr/bin/clickhouse
2. 0x4cfa23c DB::parseQuery(DB::IParser&, char const*, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, unsigned long) (.cold) /build/obj-x86_64-linux-gnu/../dbms/src/Parsers/parseQuery.cpp:310 in /usr/lib/debug/usr/bin/clickhouse
3. 0x8de2989 DB::loadDatabase(DB::Context&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool) /build/obj-x86_64-linux-gnu/../dbms/src/Interpreters/loadMetadata.cpp:39 in /usr/lib/debug/usr/bin/clickhouse
4. 0x8de4f80 DB::loadMetadataSystem(DB::Context&) /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/string:2133 in /usr/lib/debug/usr/bin/clickhouse
5. 0x4ed313b DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) /build/obj-x86_64-linux-gnu/../dbms/programs/server/Server.cpp:532 in /usr/lib/debug/usr/bin/clickhouse
6. 0x9d5a193 Poco::Util::Application::run() /build/obj-x86_64-linux-gnu/../contrib/poco/Util/src/Application.cpp:335 in /usr/lib/debug/usr/bin/clickhouse
7. 0x4fd15b1 DB::Server::run() /build/obj-x86_64-linux-gnu/../dbms/programs/server/Server.cpp:152 in /usr/lib/debug/usr/bin/clickhouse
8. 0x4fc95af mainEntryClickHouseServer(int, char**) /build/obj-x86_64-linux-gnu/../dbms/programs/server/Server.cpp:989 in /usr/lib/debug/usr/bin/clickhouse
9. 0x4ecfe19 main /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/vector:461 in /usr/lib/debug/usr/bin/clickhouse
10. 0x21bf7 __libc_start_main /build/glibc-S9d2JN/glibc-2.27/csu/../csu/libc-start.c:344 in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.27.so
11. 0x4f334ca _start  in /usr/lib/debug/usr/bin/clickhouse
 (version 20.2.1.2183 (official build))
2021.08.11 19:29:18.299162 [ 1 ] {} <Information> Application: Shutting down storages.
2021.08.11 19:29:18.299191 [ 1 ] {} <Debug> Application: Shut down storages.
2021.08.11 19:29:18.299592 [ 1 ] {} <Debug> Application: Destroyed global context.
2021.08.11 19:29:18.299751 [ 1 ] {} <Error> Application: DB::Exception: Syntax error (in file /var/lib/clickhouse/metadata/system.sql): failed at position 19 (line 1, col 19): UUID '61258d5c-6949-4e2d-9ad8-28c243b86fde'
ENGINE = Atomic
. Expected one of: ON, ENGINE, storage definition
2021.08.11 19:29:18.299782 [ 1 ] {} <Information> Application: shutting down
2021.08.11 19:29:18.299806 [ 1 ] {} <Debug> Application: Uninitializing subsystem: Logging Subsystem
2021.08.11 19:29:18.299964 [ 2 ] {} <Information> BaseDaemon: Stop SignalListener thread

**Comment by den-crane** [comment]
20.2.1.2183  is testing release and very old.

here is the latest release https://github.com/ClickHouse/ClickHouse/releases/tag/v21.7.7.47-stable

**Comment by sigirisetti** [comment]
Hi, thanks for your response. I want to try different column databases. My objective is try to install/upgrade clickhouse on redhat/ubuntu flavor of linux without internet. I will try to download use rpm/deb for install. Will post my response here again. Thank you

**Comment by sigirisetti** [comment]
Nice. your version of software worked well.. https://github.com/ClickHouse/ClickHouse/releases/tag/v21.7.7.47-stable

Installed debs offline and able to follow your tutorial page

Thanks a lot

**Comment by sigirisetti** [comment]
Hi, 

Thanks for your time. I'm pasting server install log here. clickhouse is installed on ubuntu 18 in laptop which has internet access. If I download deb/rpm files and try to install on a linux server without internet connection will it be successful as well

Below log show

- dependent lib install
- There is a https call - Get:1 https://repo.clickhouse.tech/deb/stable main/ clickhouse-server 21.7.7.47 [90.5 kB]

will these steps be successful on linux server without internet connectivity?

Thank you


**Install LOG:**

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'clickhouse-server' instead of './clickhouse-server_21.7.7.47_all.deb'
The following packages were automatically installed and are no longer required:
  cuda-command-line-tools-11-0 cuda-command-line-tools-11-1 cuda-compiler-11-0 cuda-compiler-11-1 cuda-cudart-11-0
  cuda-cudart-11-1 cuda-cudart-dev-11-0 cuda-cudart-dev-11-1 cuda-cuobjdump-11-0 cuda-cuobjdump-11-1
  cuda-cupti-11-0 cuda-cupti-11-1 cuda-cupti-dev-11-0 cuda-cupti-dev-11-1 cuda-documentation-11-0
  cuda-documentation-11-1 cuda-driver-dev-11-0 cuda-driver-dev-11-1 cuda-gdb-11-0 cuda-gdb-11-1
  cuda-libraries-11-0 cuda-libraries-11-1 cuda-libraries-dev-11-0 cuda-libraries-dev-11-1 cuda-memcheck-11-0
  cuda-memcheck-11-1 cuda-nsight-11-0 cuda-nsight-11-1 cuda-nsight-compute-11-0 cuda-nsight-compute-11-1
  cuda-nsight-systems-11-0 cuda-nsight-systems-11-1 cuda-nvcc-11-0 cuda-nvcc-11-1 cuda-nvdisasm-11-0
  cuda-nvdisasm-11-1 cuda-nvml-dev-11-0 cuda-nvml-dev-11-1 cuda-nvprof-11-0 cuda-nvprof-11-1 cuda-nvprune-11-0
  cuda-nvprune-11-1 cuda-nvrtc-11-0 cuda-nvrtc-11-1 cuda-nvrtc-dev-11-0 cuda-nvrtc-dev-11-1 cuda-nvtx-11-0
  cuda-nvtx-11-1 cuda-nvvp-11-0 cuda-nvvp-11-1 cuda-samples-11-0 cuda-samples-11-1 cuda-sanitizer-11-0
  cuda-sanitizer-11-1 cuda-toolkit-11-0 cuda-toolkit-11-1 cuda-tools-11-0 cuda-tools-11-1 cuda-visual-tools-11-0
  cuda-visual-tools-11-1 gir1.2-geocodeglib-1.0 gyp libcublas-11-0 libcublas-11-1 libcublas-dev-11-0
  libcublas-dev-11-1 libcufft-11-0 libcufft-11-1 libcufft-dev-11-0 libcufft-dev-11-1 libcurand-11-0 libcurand-11-1
  libcurand-dev-11-0 libcurand-dev-11-1 libcusolver-11-0 libcusolver-11-1 libcusolver-dev-11-0
  libcusolver-dev-11-1 libcusparse-11-0 libcusparse-11-1 libcusparse-dev-11-0 libcusparse-dev-11-1 libfwup1
  libglade2-0 libheif1 libjs-async libjs-inherits libjs-node-uuid libjs-underscore libllvm7 libllvm8 libllvm9
  libnpp-11-0 libnpp-11-1 libnpp-dev-11-0 libnpp-dev-11-1 libnvidia-common-450 libnvidia-common-455 libnvjpeg-11-0
  libnvjpeg-11-1 libnvjpeg-dev-11-0 libnvjpeg-dev-11-1 libuv1-dev libvte-common libvte9 node-abbrev node-ansi
  node-ansi-color-table node-archy node-async node-balanced-match node-block-stream node-brace-expansion
  node-combined-stream node-concat-map node-cookie-jar node-delayed-stream node-forever-agent node-form-data
  node-fs.realpath node-fstream node-fstream-ignore node-github-url-from-git node-glob node-graceful-fs
  node-hosted-git-info node-inflight node-inherits node-ini node-isexe node-json-stringify-safe node-lockfile
  node-lru-cache node-mime node-minimatch node-mkdirp node-mute-stream node-node-uuid node-nopt node-npmlog
  node-once node-osenv node-path-is-absolute node-pseudomap node-qs node-read node-request node-retry node-rimraf
  node-semver node-sha node-slide node-spdx-correct node-spdx-expression-parse node-spdx-license-ids node-tar
  node-tunnel-agent node-underscore node-validate-npm-package-license node-which node-wrappy node-yallist par2
  python-glade2 python-vte ubuntu-web-launchers
Use 'sudo apt autoremove' to remove them.
The following NEW packages will be installed:
  clickhouse-server
0 upgraded, 1 newly installed, 0 to remove and 38 not upgraded.
Need to get 90.5 kB of archives.
After this operation, 177 kB of additional disk space will be used.
Get:1 https://repo.clickhouse.tech/deb/stable main/ clickhouse-server 21.7.7.47 [90.5 kB]
Fetched 90.5 kB in 1s (76.0 kB/s)      
Selecting previously unselected package clickhouse-server.
(Reading database ... 453866 files and directories currently installed.)
Preparing to unpack .../clickhouse-server_21.7.7.47_all.deb ...
Unpacking clickhouse-server (21.7.7.47) ...
Setting up clickhouse-server (21.7.7.47) ...
ClickHouse binary is already located at /usr/bin/clickhouse
Symlink /usr/bin/clickhouse-server already exists but it points to /clickhouse. Will replace the old symlink to /usr/bin/clickhouse.
Creating symlink /usr/bin/clickhouse-server to /usr/bin/clickhouse.
Symlink /usr/bin/clickhouse-client already exists but it points to /clickhouse. Will replace the old symlink to /usr/bin/clickhouse.
Creating symlink /usr/bin/clickhouse-client to /usr/bin/clickhouse.
Symlink /usr/bin/clickhouse-local already exists but it points to /clickhouse. Will replace the old symlink to /usr/bin/clickhouse.
Creating symlink /usr/bin/clickhouse-local to /usr/bin/clickhouse.
Symlink /usr/bin/clickhouse-benchmark already exists but it points to /clickhouse. Will replace the old symlink to /usr/bin/clickhouse.
Creating symlink /usr/bin/clickhouse-benchmark to /usr/bin/clickhouse.
Symlink /usr/bin/clickhouse-copier already exists but it points to /clickhouse. Will replace the old symlink to /usr/bin/clickhouse.
Creating symlink /usr/bin/clickhouse-copier to /usr/bin/clickhouse.
Symlink /usr/bin/clickhouse-obfuscator already exists but it points to /clickhouse. Will replace the old symlink to /usr/bin/clickhouse.
Creating symlink /usr/bin/clickhouse-obfuscator to /usr/bin/clickhouse.
Symlink /usr/bin/clickhouse-compressor already exists but it points to /clickhouse. Will replace the old symlink to /usr/bin/clickhouse.
Creating symlink /usr/bin/clickhouse-compressor to /usr/bin/clickhouse.
Symlink /usr/bin/clickhouse-format already exists but it points to /clickhouse. Will replace the old symlink to /usr/bin/clickhouse.
Creating symlink /usr/bin/clickhouse-format to /usr/bin/clickhouse.
Symlink /usr/bin/clickhouse-extract-from-config already exists but it points to /clickhouse. Will replace the old symlink to /usr/bin/clickhouse.
Creating symlink /usr/bin/clickhouse-extract-from-config to /usr/bin/clickhouse.
Creating clickhouse group if it does not exist.
 groupadd -r clickhouse
groupadd: group 'clickhouse' already exists
Creating clickhouse user if it does not exist.
 useradd -r --shell /bin/false --home-dir /nonexistent -g clickhouse clickhouse
useradd: user 'clickhouse' already exists
Will set ulimits for clickhouse user in /etc/security/limits.d/clickhouse.conf.
Config file /etc/clickhouse-server/config.xml already exists, will keep it and extract path info from it.
/etc/clickhouse-server/config.xml has /var/lib/clickhouse/ as data path.
/etc/clickhouse-server/config.xml has /var/log/clickhouse-server/ as log path.
Users config file /etc/clickhouse-server/users.xml already exists, will keep it and extract users info from it.
 chown --recursive clickhouse:clickhouse '/etc/clickhouse-server'
Log directory /var/log/clickhouse-server/ already exists.
Data directory /var/lib/clickhouse/ already exists.
Pid directory /var/run/clickhouse-server already exists.
 chown --recursive clickhouse:clickhouse '/var/log/clickhouse-server/'
 chown --recursive clickhouse:clickhouse '/var/run/clickhouse-server'
 chown clickhouse:clickhouse '/var/lib/clickhouse/'
 groupadd -r clickhouse-bridge
groupadd: group 'clickhouse-bridge' already exists
 useradd -r --shell /bin/false --home-dir /nonexistent -g clickhouse-bridge clickhouse-bridge
useradd: user 'clickhouse-bridge' already exists
 chown --recursive clickhouse-bridge:clickhouse-bridge '/usr/bin/clickhouse-odbc-bridge'
 chown --recursive clickhouse-bridge:clickhouse-bridge '/usr/bin/clickhouse-library-bridge'
Password for default user is already specified. To remind or reset, see /etc/clickhouse-server/users.xml and /etc/clickhouse-server/users.d.
Setting capabilities for clickhouse binary. This is optional.

ClickHouse has been successfully installed.

Start clickhouse-server with:
 sudo clickhouse start

Start clickhouse-client with:
 clickhouse-client --password

Synchronizing state of clickhouse-server.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable clickhouse-server
Processing triggers for systemd (237-3ubuntu10.50) ...
Processing triggers for ureadahead (0.100.0-21) ...
ureadahead will be reprofiled on next reboot

**Comment by alexey-milovidov** [comment]
Yes, you have successfully installed ClickHouse.
