### ISSUE TITLE
Support dynamically adding tables to MaterializedPostgreSQL

### ISSUE THREAD

**Issue by mlazowik** [ClickHouse/ClickHouse#27573]
I'm not sure if this is possible at all – could the `MaterializedPostgreSQL` be extended to either support automatically replicating new tables that are added upstream, or support `ALTER`ing it to extend the set of tables?

I'm not using any table filters and right now I have to remove and recreate the whole `MaterializedPostgreSQL` instance to get the new tables.

**Comment by kssenii** [comment]
Yes, it is possible to implement.
