### ISSUE TITLE
lagInFrame returns unexpected value

### ISSUE THREAD

**Issue by jimyin-1994** [ClickHouse/ClickHouse#27607]
clickhouse version 21.7.5.29
here is a table without any partition and order by id

select id from tb1;
┌─id─┐
│  2 │
└────┘
┌─id─┐
│  1 │
└────┘
┌─id─┐
│  4 │
└────┘
if I use any() , the behavior is correct
select id, any(id) over (order by id rows between 1 preceding and 1 preceding) from tb1;

┌─id─┬─any(id) OVER (ORDER BY id ASC ROWS BETWEEN 1 PRECEDING AND 1 PRECEDING)─┐
│  1 │                                                                       0 │
│  2 │                                                                       1 │
│  4 │                                                                       2 │
└────┴─────────────────────────────────────────────────────────────────────────┘

but if I use lagInFrame, the behavior is unexpected
SELECT id, lagInFrame(id, 1, NULL) OVER (ORDER BY id ASC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS id_prev FROM tb1;

┌─id─┬─id_prev─┐
│  1 │ ᴺᵁᴸᴸ    │
└────┴─────────┘
┌─id─┬─id_prev─┐
│  2 │ ᴺᵁᴸᴸ    │
│  4 │ ᴺᵁᴸᴸ    │
└────┴─────────┘

**Comment by akuzm** [comment]
It's this one: https://github.com/ClickHouse/ClickHouse/issues/26115
Fixed in 21.9.
