### ISSUE TITLE
Can I use window function in temp view?

### ISSUE THREAD

**Issue by jimyin-1994** [ClickHouse/ClickHouse#27608]
I have set allow_experimental_window_functions = 1;
when I create a temp view with window function, and then select * from temp view;
But I received 

> Received exception from server (version 21.7.5):
> Code: 48. DB::Exception: Received from localhost:9000. DB::Exception: The support for window functions is experimental and will change in backwards-incompatible ways in the future releases. Set allow_eental_window_functions = 1 to enable it. While processing 'any(value) OVER (PARTITION BY signal, uuid ORDER BY timestamp ASC ROWS BETWEEN 1 PRECEDING AND 1 PRECEDING) AS value_prev'.
>

**Comment by akuzm** [comment]
This setting is removed in 21.9, now window functions work without it.
