### ISSUE TITLE
How to insert values into map with nested value?

### ISSUE THREAD

**Issue by rubtsovnyu** [ClickHouse/ClickHouse#27618]
```sql
CREATE TABLE nst_test
(
    `nst_map` Map(String, Nested(type Int8, value Int64))
)
ENGINE = Memory()
```

How to insert values into this table?

This doesn't work:

```sql
INSERT INTO nst_test VALUES ({'a_above’: [[1, 2, 3], [4, 5, 6]]});
```

**Comment by Kripa8702** [comment]
`// C++14 code to implement two-dimensional map
// and inserting value through insert()

#include <bits/stdc++.h>
using namespace std;

int main()
{

	// First key type is a string
	map<string, map<int, int> > m;

	map<string, map<int, int> >::iterator itr;
	map<int, int>::iterator ptr;

	m.insert(make_pair("a_above", map<int, int>()));
	m["a_above"].insert(make_pair(1, 4));

	m.insert(make_pair("a_above", map<int, int>()));
	m["a_above"].insert(make_pair(2, 5));

	m.insert(make_pair("a_above", map<int, int>()));
	m["a_above"].insert(make_pair(3, 6));

    cout<<"\nKEY\t\tVALUE 1\t\tVALUE 2"<<endl;

	for (itr = m.begin(); itr != m.end(); itr++) {

		for (ptr = itr->second.begin(); ptr != itr->second.end(); ptr++) {
			cout <<itr->first << "\t\t"<< ptr->first<<"\t\t"<<ptr->second << endl;
		}
	}
}
`

Please check whether this solves your issue

**Comment by Kripa8702** [comment]
I'll work on this in C++. I am new and having trouble adding my code to this issue to solve it

**Comment by Kripa8702** [comment]
Hope this works 
https://github.com/Kripa8702/solution/blob/0853d439ab030aa15eb344ce8af25c6df4361d1c/maps.cpp

**Comment by rubtsovnyu** [comment]
@Kripa8702 Honestly, I didn't get how this can help me. I'm talking about SQL query to ClickHouse, you are talking about cpp maps. What's the point?

**Comment by vdimir** [comment]
cc @CurtizJ

**Comment by CurtizJ** [comment]
You can insert values to Nested columns as array of tuples:
```sql
CREATE TABLE nst_test
(
    `nst_map` Map(String, Nested(type Int8, value Int64))
)
ENGINE = Memory();

INSERT INTO nst_test VALUES ({'a_above': [(1, 4), (2, 5), (3, 6)]});
```

Note, that currently syntax with named subcolumns (which is natural and you probably expect to work) is not supported with expressions:
```sql
SELECT nst_map['a_above'].type, nst_map['a_above'].value FROM nst_test; -- Doesn't work yet
```

However, you can query subcolumns by tuple index:
```sql
SELECT nst_map['a_above'].1 AS type, nst_map['a_above'].2 AS value FROM nst_test
```
```
┌─type────┬─value───┐
│ [1,2,3] │ [4,5,6] │
└─────────┴─────────┘
```

**Comment by rubtsovnyu** [comment]
Thanks!
