### ISSUE TITLE
arrayIntersect output elements order

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#27622]
Doc. arrayIntersect(arr) 

_Takes multiple arrays, returns an array with elements that are present in all source arrays. 
Elements order in the resulting array is the same as in the first array._

```
SELECT arrayIntersect(materialize([999, -11, 2, 3]), materialize([3, 2, 1, 999, -11]))
┌─arrayIntersect(materialize([999, -11, 2, 3]), materialize([3, 2, 1, 999, -11]))─┐
│ [-11,3,999,2]                                                                   │
└─────────────────────────────────────────────────────────────────────────────────┘


SELECT arrayIntersect([1, 2, 3], [3, 2, 1]) AS l
┌─l───────┐
│ [3,2,1] │
└─────────┘
```

**Comment by alexey-milovidov** [comment]
It's Ok (should be documented).
It does not aim to maintain the order.

**Comment by alexey-milovidov** [comment]
But I don't understand why it returns data out of order...
The implementation for keeping the order should be natural...

**Comment by den-crane** [comment]
@KochetovNicolai What do you think?

**Comment by KochetovNicolai** [comment]
It's cause we fill a hash table first, then iterate it - the order is not preserved. It is easy for fix if need.

**Comment by alexey-milovidov** [comment]
I thought we first fill hash table for second array,
then iterate on the elements of the first array *in their order*
making lookups to the hash table.

**Comment by KochetovNicolai** [comment]
There may be more than two arrays.
We support a map: `key -> the number of arrays seen` instead.

**Comment by alexey-milovidov** [comment]
Maybe correct the docs and close?

**Comment by KochetovNicolai** [comment]
Or we can fix it :)
@den-crane do you need this feature?

**Comment by den-crane** [comment]
I don't need this feature. I'll fix the doc.

**Comment by UnamedRus** [comment]
It would be really nice to have stable option of arrayIntersect, other alternatives is much more expensive...
