### ISSUE TITLE
Enable part_log by default

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#27628]
I don't see any reason why it's disabled by default.

**Comment by den-crane** [comment]
And maybe by default all _log tables should be partitioned by day + ttl 30 days + drop_only_part

**Comment by alexey-milovidov** [comment]
Ok.

> And maybe by default all _log tables should be partitioned by day + ttl 30 days + drop_only_part

I prefer to store data indefinitely.
