### ISSUE TITLE
Add New Indexes

### ISSUE THREAD

**Issue by Nihulrawat** [ClickHouse/ClickHouse#27633]
We have a clickhouse cluster running on prod with 1 skip index, now we are trying to add 2 new indexes using this command : 

`ALTER TABLE ****** ON CLUSTER ***** ADD INDEX new_index1 eVar1 TYPE set(100) GRANULARITY 1, ADD INDEX new_index2 prop0 TYPE set(100) GRANULARITY 1; `

I read from the documentation that in order to apply these new indexes to the existing data, we need to run below query as well, so did the same :

`OPTIMIZE TABLE ******* ON CLUSTER ****** FINAL`

But still, we don't see any performance improvements in queries using these indexes, is there any way to debug what indexes are being used in a query? I tried EXPLAIN PLAN command but the version that we are using does not support indexes setting with EXPLAIN.

**Comment by den-crane** [comment]
TYPE set(100)  -- means that if granule (8192 row) of the column eVar1 has more than 100 values  the index will not be created for this granule --> it could be that in reality there is no skip index granules created in your table.

If you want more information you should provide more info. Create table / create index / test datasample.
