### ISSUE TITLE
KILL query don‘t  work

### ISSUE THREAD

**Issue by maimaip** [ClickHouse/ClickHouse#27632]
> Make sure to check documentation https://clickhouse.yandex/docs/en/ first. If the question is concise and probably has a short answer, asking it in Telegram chat https://telegram.me/clickhouse_en is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

> If you still prefer GitHub issues, remove all this text and ask your question here.
clickhouse version : 21.4.6
question :  use jdbc drop table  dont response ， i  use  sql `select * from system.processes `  find the key , kill query key。kill_status always waiting .  the clinent process is close ，but  server query is don't close 
![企业微信截图_16288238333549](https://user-images.githubusercontent.com/28518838/129299127-d784e804-a132-42a0-b7ef-92c118d1db95.png)
![企业微信截图_16288238712503](https://user-images.githubusercontent.com/28518838/129299180-37c08f36-4d0e-43b9-8c61-a8ddef5b8979.png)

**Comment by den-crane** [comment]
_Unfortunately it's not always possible to kill the query at random moment of time.
Kill don't send any signals, it just set a flag. Which gets (synchronously) checked at certain moments of query execution, mostly after finishing processing one block and starting another.
On certain stages (executing scalar sub-query) the query can not be killed at all. This is a known issue and requires an architectural change to fix it._
