### ISSUE TITLE
Exception: Connections to all replicas failed: t@localhost:3310 as user root 

### ISSUE THREAD

**Issue by samchenws** [ClickHouse/ClickHouse#27635]
ClickHouse(docker) version: version 21.7.5.29 (official build) PORT:8123
MySql(docker)  version:8.02 PORT:3310
Exec:
CREATE TABLE t ENGINE = MergeTree ORDER BY id AS SELECT * FROM mysql('localhost:3310', 't', 't', 'root', 'root');
An error occurred:
org.jkiss.dbeaver.model.sql.DBSQLException: SQL 错误 [1000]: ClickHouse exception, code: 1000, host: localhost, port: 8123; Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = Exception: Connections to all replicas failed: t@localhost:3310 as user root (version 21.7.5.29 (official build))
Can you help me？

**Comment by alexey-milovidov** [comment]
Maybe you simply misconfigured network in Docker?
To check it you can run both containers with `--network=host`.
