### ISSUE TITLE
Deduplication doesn't work if MV exists.

### ISSUE THREAD

**Issue by wawanawna** [ClickHouse/ClickHouse#2765]
Hello, we use Materialized Views a lot.
There is one problem with them, if you use batch insert and it passes to main table but was rejected by one of MV, whole insert will return exception.
Client will retry send batch and again it can be applied by main table, so that's how duplications possible.

Ideally CH has to apply or reject batch for main table and MVs together.
Or maybe inform somehow that main insert was succeed and only MVs are problematic (not a very good solution, but better than nothing)

**Comment by alesapin** [comment]
Maybe you'll provide any method to reproduce the problem?

**Comment by wawanawna** [comment]
Hello @alesapin . Do you mean method how to force MV reject insert data?
In our case we mapped MV to disk in RAM and when there is not enough space problems happened.
I may suggest simplest way, change dir with MV access rights, pretty sure we will see same behaviour.

**Comment by jakesyl** [comment]
I believe this is intended behavior

**Comment by den-crane** [comment]
Yes it's intended behavior. Now it can be disabled by `deduplicate_blocks_in_dependent_materialized_views=1`

explanation:
https://clickhouse.tech/docs/en/operations/settings/settings/#settings-deduplicate-blocks-in-dependent-materialized-views
