### ISSUE TITLE
Clickhouse not starting in WSL

### ISSUE THREAD

**Issue by dimonnot** [ClickHouse/ClickHouse#27676]
> You have to provide the following information whenever possible.

Clickhouse crashed

> A clear and concise description of what works not as it is supposed to.

**Does it reproduce on recent release?**

Clickhouse 21.4.4.30 

**Enable crash reporting**

2021.08.14 18:34:33.525234 [ 226 ] {} <Error> bool DB::(anonymous namespace)::checkPermissionsImpl(): Code: 412, e.displayText() = DB::ErrnoException: C
an't create PF_NETLINK socket, errno: 93, strerror: Protocol not supported, Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x8914f0a in /usr
/bin/clickhouse
1. DB::throwFromErrno(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int) @ 0x8915a5b in /usr/bin/cl
ickhouse
2. DB::TaskStatsInfoGetter::TaskStatsInfoGetter() @ 0x89480a0 in /usr/bin/clickhouse
3. ? @ 0x8947eb6 in /usr/bin/clickhouse
4. DB::TaskStatsInfoGetter::checkPermissions() @ 0x8947e56 in /usr/bin/clickhouse
5. DB::TasksStatsCounters::create(unsigned long) @ 0x8940600 in /usr/bin/clickhouse
6. DB::ThreadStatus::initPerformanceCounters() @ 0xf938c81 in /usr/bin/clickhouse
7. DB::ThreadStatus::setupState(std::__1::shared_ptr<DB::ThreadGroupStatus> const&) @ 0xf938978 in /usr/bin/clickhouse
8. ? @ 0xf93a902 in /usr/bin/clickhouse
9. DB::BackgroundSchedulePool::attachToThreadGroup() @ 0xf33d6fd in /usr/bin/clickhouse
10. DB::BackgroundSchedulePool::threadFunction() @ 0xf33d7e2 in /usr/bin/clickhouse
11. ? @ 0xf33e5e2 in /usr/bin/clickhouse
12. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x8954fef in /usr/bin/clickhouse
13. ? @ 0x8958a83 in /usr/bin/clickhouse
14. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
15. clone @ 0x122103 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
 (version 21.4.4.30 (official build))
2021.08.14 18:34:34.557734 [ 193 ] {} <Error> Application: Caught exception while loading metadata: Poco::Exception. Code: 1000, e.code() = 13, e.displa
yText() = Access to file denied: /var/lib/clickhouse/store/b61/b61cfdcd-81b8-4b0c-a5d7-d068025c131c/all_46211_46211_0_46264, Stack trace (when copying t
his message, always include the lines below):

0. Poco::FileImpl::handleLastErrorImpl(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x128f31ec in /us
r/bin/clickhouse
1. Poco::File::renameTo(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x128f6b3c in /usr/bin/clickhous
e
2. DB::DiskLocal::moveDirectory(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<cha
r, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xf25cdfb in /usr/bin/clickhouse
3. DB::IMergeTreeDataPart::remove(bool) const @ 0xfe247db in /usr/bin/clickhouse
4. ? @ 0xfeab62b in /usr/bin/clickhouse
5. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0x8957a18 in /usr/bin/clickhouse
6. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::
optional<unsigned long>)::'lambda1'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1:
:optional<unsigned long>)::'lambda1'()&&...)::'lambda'()::operator()() @ 0x89599df in /usr/bin/clickhouse
7. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x8954fef in /usr/bin/clickhouse
8. ? @ 0x8958a83 in /usr/bin/clickhouse
9. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
10. clone @ 0x122103 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
 (version 21.4.4.30 (official build))
2021.08.14 18:34:35.592571 [ 193 ] {} <Error> Application: Access to file denied: /var/lib/clickhouse/store/b61/b61cfdcd-81b8-4b0c-a5d7-d068025c131c/all
_46211_46211_0_46264

Clickhouse has access to file:

dmitriu@Server:~$ sudo ls -l /var/lib/clickhouse/store/b61/b61cfdcd-81b8-4b0c-a5d7-d068025c131c/all_46211_46211_0_46264
total 12
-r--r----- 87 clickhouse clickhouse  188 Aug 13 07:17 checksums.txt
-r--r----- 87 clickhouse clickhouse  733 Aug 13 07:17 columns.txt
-r--r----- 87 clickhouse clickhouse    1 Aug 13 07:17 count.txt
-r--r----- 87 clickhouse clickhouse 1211 Aug 13 07:17 data.bin
-r--r----- 87 clickhouse clickhouse 1104 Aug 13 07:17 data.mrk3
-r--r----- 87 clickhouse clickhouse   10 Aug 13 07:17 default_compression_codec.txt
-r--r----- 87 clickhouse clickhouse   74 Aug 13 07:17 primary.idx

How to fix this error?

**Comment by alexey-milovidov** [comment]
Check version 21.8.

**Comment by dimonnot** [comment]
Upgrade version to 21.8.3.4

New error:
2021.08.17 07:24:12.580957 [ 3089 ] {} <Error> bool DB::(anonymous namespace)::checkPermissionsImpl(): Code: 412, e.displayText() = DB::ErrnoException: Can't create PF_NETLINK socket, errno: 93, strerror: Protocol not supported, Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x8f9b87a in /usr/bin/clickhouse
1. DB::throwFromErrno(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int) @ 0x8f9c40b in /usr/bin/clickhouse
2. DB::TaskStatsInfoGetter::TaskStatsInfoGetter() @ 0x8fcfce0 in /usr/bin/clickhouse
3. ? @ 0x8fcfae6 in /usr/bin/clickhouse
4. DB::TaskStatsInfoGetter::checkPermissions() @ 0x8fcfa86 in /usr/bin/clickhouse
5. DB::TasksStatsCounters::create(unsigned long) @ 0x8fc8276 in /usr/bin/clickhouse
6. DB::ThreadStatus::initPerformanceCounters() @ 0x106c519b in /usr/bin/clickhouse
7. DB::ThreadStatus::setupState(std::__1::shared_ptr<DB::ThreadGroupStatus> const&) @ 0x106c4bcf in /usr/bin/clickhouse
8. DB::CurrentThread::initializeQuery() @ 0x106c7142 in /usr/bin/clickhouse
9. DB::BackgroundSchedulePool::attachToThreadGroup() @ 0xfff17ed in /usr/bin/clickhouse
10. DB::BackgroundSchedulePool::threadFunction() @ 0xfff18e2 in /usr/bin/clickhouse
11. ? @ 0xfff2694 in /usr/bin/clickhouse
12. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x8fdc4ff in /usr/bin/clickhouse
13. ? @ 0x8fdfde3 in /usr/bin/clickhouse
14. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
15. __clone @ 0x122103 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
 (version 21.8.3.44 (official build))

**Comment by alexey-milovidov** [comment]
Is it WSL1 or WSL2?

Most likely ClickHouse only works with WSL2.
I did not use any of those though...

**Comment by alexey-milovidov** [comment]
The message about NETLINK should not prevent ClickHouse to start anyway.

**Comment by dimonnot** [comment]
We cant use WSL2, its not supported on Windows Server 2019

**Comment by alexey-milovidov** [comment]
Workaround: install Linux in VM.
