### ISSUE TITLE
build failed using clang-13 with error: variable 'y' set but not used [-Werror,-Wunused-but-set-variable]

### ISSUE THREAD

**Issue by syominsergey** [ClickHouse/ClickHouse#27705]
**Operating system**

```
semin-serg@semin-serg-ub:~/ClickHouse$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
```

**Cmake version**

```
semin-serg@semin-serg-ub:~/ClickHouse$ cmake --version
cmake version 3.16.3

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

**Ninja version**

```
semin-serg@semin-serg-ub:~/ClickHouse$ ninja --version
1.10.0
```

**Compiler name and version**
```
semin-serg@semin-serg-ub:~/ClickHouse$ clang-13 --version
Ubuntu clang version 13.0.0-++20210813082601+aac4fe380d16-1~exp1~20210813063406.40
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

semin-serg@semin-serg-ub:~/ClickHouse$ clang++-13 --version
Ubuntu clang version 13.0.0-++20210813082601+aac4fe380d16-1~exp1~20210813063406.40
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Full cmake and/or ninja output**
see in attached file [cmake-and-ninja-run.txt](https://github.com/ClickHouse/ClickHouse/files/6988608/cmake-and-ninja-run.txt)

**Comment by syominsergey** [comment]
I guess that cause in new diagnostic flag `-Wunused-but-set-variable`:
https://clang.llvm.org/docs/DiagnosticsReference.html#wunused-but-set-parameter

There is no such flag in version 12 of clang:
https://releases.llvm.org/12.0.0/tools/clang/docs/DiagnosticsReference.html

**Comment by syominsergey** [comment]
build works fine on my machine using clang-12:
```
semin-serg@semin-serg-ub:~/ClickHouse/build-clang-12$ export CC=clang-12 CXX=clang++-12
semin-serg@semin-serg-ub:~/ClickHouse/build-clang-12$ cmake ..
semin-serg@semin-serg-ub:~/ClickHouse/build-clang-12$ ninja -v
```

versions:
```
semin-serg@semin-serg-ub:~/ClickHouse/build-clang-12$ clang-12 --version
Ubuntu clang version 12.0.1-++20210802051739+fed41342a82f-1~exp1~20210802152501.132
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
semin-serg@semin-serg-ub:~/ClickHouse/build-clang-12$ clang++-12 --version
Ubuntu clang version 12.0.1-++20210802051739+fed41342a82f-1~exp1~20210802152501.132
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by syominsergey** [comment]
lets try to compare commands invoked by ninja for file `__math_divzero.c` (one of files with errors according to clang-13):

with clang-12:
```
/usr/bin/clang-12  -I../base/glibc-compatibility/libcxxabi -I../base/glibc-compatibility/musl/x86_64 -isystem ../contrib/libc-headers/x86_64-linux-gnu -isystem ../contrib/libc-headers -fdiagnostics-color=always  -gdwarf-aranges -pipe -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -fasynchronous-unwind-tables -falign-functions=32  -Wall -Wno-unused-command-line-argument  -fdiagnostics-absolute-paths -fexperimental-new-pass-manager -Werror -Wno-builtin-requires-header -fomit-frame-pointer -O2 -g -DNDEBUG -O3    -D OS_LINUX -Wno-unused-command-line-argument -std=gnu11 -MD -MT base/glibc-compatibility/CMakeFiles/glibc-compatibility.dir/musl/__math_divzero.c.o -MF base/glibc-compatibility/CMakeFiles/glibc-compatibility.dir/musl/__math_divzero.c.o.d -o base/glibc-compatibility/CMakeFiles/glibc-compatibility.dir/musl/__math_divzero.c.o   -c ../base/glibc-compatibility/musl/__math_divzero.c
```

with clang-13:
```
/usr/bin/clang-13  -I../base/glibc-compatibility/libcxxabi -I../base/glibc-compatibility/musl/x86_64 -isystem ../contrib/libc-headers/x86_64-linux-gnu -isystem ../contrib/libc-headers -fdiagnostics-color=always  -gdwarf-aranges -pipe -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -fasynchronous-unwind-tables -falign-functions=32  -Wall -Wno-unused-command-line-argument  -fdiagnostics-absolute-paths -fexperimental-new-pass-manager -Werror -Wno-builtin-requires-header -fomit-frame-pointer -O2 -g -DNDEBUG -O3    -D OS_LINUX -Wno-unused-command-line-argument -std=gnu11 -MD -MT base/glibc-compatibility/CMakeFiles/glibc-compatibility.dir/musl/__math_divzero.c.o -MF base/glibc-compatibility/CMakeFiles/glibc-compatibility.dir/musl/__math_divzero.c.o.d -o base/glibc-compatibility/CMakeFiles/glibc-compatibility.dir/musl/__math_divzero.c.o   -c ../base/glibc-compatibility/musl/__math_divzero.c
```

the only difference is compiler version
`-Wunused-but-set-variable` is not mentioned in both cases
maybe in clang-13 it is turned on by default

**Comment by syominsergey** [comment]
adding param `-Wno-unused-but-set-variable` solves problem
for example, this command for `__math_divzero.c` works correctly:
```
/usr/bin/clang-13  -I../base/glibc-compatibility/libcxxabi -I../base/glibc-compatibility/musl/x86_64 -isystem ../contrib/libc-headers/x86_64-linux-gnu -isystem ../contrib/libc-headers -fdiagnostics-color=always  -gdwarf-aranges -pipe -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -fasynchronous-unwind-tables -falign-functions=32  -Wall -Wno-unused-command-line-argument  -fdiagnostics-absolute-paths -fexperimental-new-pass-manager -Werror -Wno-builtin-requires-header -Wno-unused-but-set-variable -fomit-frame-pointer -O2 -g -DNDEBUG -O3    -D OS_LINUX -Wno-unused-command-line-argument -std=gnu11 -MD -MT base/glibc-compatibility/CMakeFiles/glibc-compatibility.dir/musl/__math_divzero.c.o -MF base/glibc-compatibility/CMakeFiles/glibc-compatibility.dir/musl/__math_divzero.c.o.d -o base/glibc-compatibility/CMakeFiles/glibc-compatibility.dir/musl/__math_divzero.c.o   -c ../base/glibc-compatibility/musl/__math_divzero.c
```

**Comment by syominsergey** [comment]
but adding mentioned param `-Wno-unused-but-set-variable` for clang-12 raises another problem:
```
semin-serg@semin-serg-ub:~/ClickHouse/build-test$ /usr/bin/clang-12  -I../base/glibc-compatibility/libcxxabi -I../base/glibc-compatibility/musl/x86_64 -isystem ../contrib/libc-headers/x86_64-linux-gnu -isystem ../contrib/libc-headers -fdiagnostics-color=always  -gdwarf-aranges -pipe -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -fasynchronous-unwind-tables -falign-functions=32  -Wall -Wno-unused-command-line-argument  -fdiagnostics-absolute-paths -fexperimental-new-pass-manager -Werror -Wno-builtin-requires-header -Wno-unused-but-set-variable -fomit-frame-pointer -O2 -g -DNDEBUG -O3    -D OS_LINUX -Wno-unused-command-line-argument -std=gnu11 -MD -MT base/glibc-compatibility/CMakeFiles/glibc-compatibility.dir/musl/__math_divzero.c.o -MF base/glibc-compatibility/CMakeFiles/glibc-compatibility.dir/musl/__math_divzero.c.o.d -o base/glibc-compatibility/CMakeFiles/glibc-compatibility.dir/musl/__math_divzero.c.o   -c ../base/glibc-compatibility/musl/__math_divzero.c
error: unknown warning option '-Wno-unused-but-set-variable'; did you mean '-Wno-unused-const-variable'? [-Werror,-Wunknown-warning-option]
```

**Comment by syominsergey** [comment]
the problem seems to be important, because official developer instruction tells the way to install clang, which leads to install clang-13 by default on Ubuntu:
https://clickhouse.tech/docs/ru/development/developer-instruction/#kompiliator-c

later in instrustion I added info about how to install older clang, but working on default clang seems to be desirable behaviour

**Comment by syominsergey** [comment]
simple definition env var `CFLAGS=-Wno-unused-but-set-variable` does not solve problem for clang-13 
[cmake-and-ninja-run-with-cflags.txt](https://github.com/ClickHouse/ClickHouse/files/6988850/cmake-and-ninja-run-with-cflags.txt)

this env var leads to add this param at the begin of compiler params, but it seems that param works only when added to the end of compiler params. See example [earlier](https://github.com/ClickHouse/ClickHouse/issues/27705#issuecomment-899103200)

**Comment by alexey-milovidov** [comment]
We have a way to add compiler options only if they are supported by compiler.

**Comment by SayeedKhan21** [comment]
Umm , sorry I am kinda new to contributing to Clickhouse and I am trying to build it locally in macOs and I am running with the same error ig
`/Users/skhan/Personal/Repos/clickhouse-mount/ClickHouse/src/Common/QueryFuzzer.cpp:1008:20: error: variable 'literal' set but not used [-Werror,-Wunused-but-set-variable]
 1008 |         if (auto * literal = typeid_cast<ASTLiteral *>(child.get()))
      |                    ^`
  I went through all the above chats however couldn't understand much on how do i resolve this error , could anyone help me with this error ?? 
  
  ` cmake --version
cmake version 3.30.4`  
` clang --version
Homebrew clang version 19.1.1`

**Comment by syominsergey** [comment]
@SayeedKhan21 unfortunately, I can't give you any practical advice howto solve the problem. I was only reporter here.
Maybe Alexey will help you later.
Or maybe you can ask help in Telegram chat:
https://telegram.me/clickhouse_en
Or in other communities mentioned at the bottom of page https://clickhouse.com/
![изображение](https://github.com/user-attachments/assets/3e58bc0f-1187-4866-a9c6-2456190cf856)

**Comment by Algunenano** [comment]
> I went through all the above chats however couldn't understand much on how do i resolve this error , could anyone help me with this error ??

Use LLVM 17 or wait until the team adapts the code to work without issues with 19.
