### ISSUE TITLE
Can clickhouse take benefit of partitioned data in s3?

### ISSUE THREAD

**Issue by gauravphoenix** [ClickHouse/ClickHouse#27712]
Let's say I have data in s3 like this -
```
s3://bucket/customer1/year/month/day/foo.json
s3://bucket/customer2/year/month/day/bar.json

```

and if I were to run query `select * from foo where customer_id= customer1`, can clickhouse only read the `s3://bucket/customer1/year/month/day/foo.json` path and skip `s3://bucket/customer2` ? 

The s3 table engine [documentation](https://clickhouse.tech/docs/en/engines/table-engines/integrations/s3/) doesn't have partition example so I can't figure out if it is possible or not. 

---
ps- moved this question from discussions github feature, the very first post on the discussion tab seems to be discouraging the use of discussions feature

**Comment by alexey-milovidov** [comment]
As far as I remember, there is a way to take this benefit.

1. Use glob patterns for path in s3: `s3://bucket/*/year/month/day/*.json`. It will select all matching files.
2. Filter by `_path` virtual column in your query: `_path` LIKE '%/customer1/%'.

You can also do it like this:

```
WITH extract(_path, '/bucket/customer(\d+)/') AS customer_id
SELECT ... FROM s3(...) WHERE customer_id = '1'
```
