### ISSUE TITLE
too many directories in tmp_path

### ISSUE THREAD

**Issue by wangxuanyue** [ClickHouse/ClickHouse#27726]
ClickHouse client version 21.3.12.2 (official build).

Why are there many empty directories under the tmp_path directory, some have more than 20,000.

like: /data/clickhouse/tmp/data/database/table/tmp_merge_20210316_2024_2363_8

What should I do with these directories???

**Comment by filimonov** [comment]
Check the logs (grep for one of that folders names). 

I.e. 

```
grep 20210316_2024_2363_8 /var/log/clickhouse-server/clickhouse-server.log
```

**Comment by wangxuanyue** [comment]
no logs found!
![image](https://user-images.githubusercontent.com/22309912/129644656-846518f1-aada-4d70-a182-9960434a79ad.png)

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/26471
