### ISSUE TITLE
DB::NetException: Connection reset by peer, while reading from socket

### ISSUE THREAD

**Issue by shadowDy** [ClickHouse/ClickHouse#27728]
I execute an SQL and do not try global join, 
When I execute on a cluster with only 10 + nodes, the data will be returned successfully.

When I execute on a 100 + node cluster,this exception will occur stably. The interval between execution and error reporting is about 5-8s.
![image](https://user-images.githubusercontent.com/18388143/129536132-4ba2486f-b421-43a4-bc29-accc6042b04a.png)

When I change the join to global join, a 300s timeout will be executed.

Version: 21.1.2 revision 54443

**Comment by shadowDy** [comment]
Question 1: why is the problem of connection reset by peer? Is fast failed related to read amplification.

Question 2: if global join is not used, how to solve this problem.

**Comment by shadowDy** [comment]
i found the "Cancelling query" before this exception in query tracing log

**Comment by Algunenano** [comment]
Hard to say without logs. From the comments it seems that the timeout was reached, the shard / remote replica cancelled the query and dropped the connection with the main server as a way to cancel the remote query.

Please verify with a recent release
