### ISSUE TITLE
Better tooling around materialized columns

### ISSUE THREAD

**Issue by macobo** [ClickHouse/ClickHouse#27730]
> (you don't have to strictly follow this form)

**Use case**

We use materialized columns extensively in our analytics app to speed up queries on a lot of free-form json data where the structure is not static.

Managing these columns is however a pain because:
- Adding them, the data starts trickling in only forwards
- To populate the data for historic data, you need to OPTIMIZE the whole data or partition. https://clickhouse.tech/docs/en/sql-reference/statements/optimize/

**Describe the solution you'd like**

Extend `optimize` statement to allow materializing only one column.

`OPTIMIZE TABLE [db.]name [ON CLUSTER cluster] [COLUMN mat_column] [PARTITION partition | PARTITION ID 'partition_id']`

Ex: `OPTIMIZE TABLE mytable ON CLUSTER cluster COLUMN mycolumn`

**Describe alternatives you've considered**

Optimizing our whole dataset every time we materialize a column. This runs into issues due to heavy I/O

**Additional context**

> Add any other context or screenshots about the feature request here.

**Comment by UnamedRus** [comment]
PR https://github.com/ClickHouse/ClickHouse/pull/27038

**Comment by larsnystrom** [comment]
So I think this was implemented by #27038? One thing that was not obvious to me was that `ALTER TABLE table MATERIALIZE COLUMN column` is executed async, so it will return immediately and the materialization process will run in the background.

**Comment by macobo** [comment]
Mostly - as an end user I still miss the PART/PARTITION controls as some of my data might be in colder storage and more expensive/less valuable to materialize.

**Comment by den-crane** [comment]
`in partition [id]` is available, but documentation does not reflect it.

```sql
clickhouse :) ALTER TABLE tmp MATERIALIZE COLUMN s in partition id 'all';

ALTER TABLE tmp
    MATERIALIZE COLUMN s IN PARTITION ID 'all'

Query id: 9b23e5cf-9945-47ca-84fa-5006a46ef79e

Ok.

0 rows in set. Elapsed: 0.006 sec.

clickhouse :) ALTER TABLE tmp MATERIALIZE COLUMN s in partition tuple();

ALTER TABLE tmp
    MATERIALIZE COLUMN s IN PARTITION tuple()

Query id: 3210acc7-6445-49e1-8c23-bdce8ce920c0

Ok.

0 rows in set. Elapsed: 0.006 sec.
```
