### ISSUE TITLE
The all data and metadata was delete when the log has "Caught exception while loading metadata" and "Considering to remove broken part"

### ISSUE THREAD

**Issue by Sallery-X** [ClickHouse/ClickHouse#27732]
the version：21.3lts
when i add/delete replica by modifying config, the log has "Caught exception while loading metadata" and ""Considering to remove broken part", and  all data and metadata was deleted,  I cant find the logic about delete data, i am confused!
![image](https://user-images.githubusercontent.com/45587738/129547470-06992187-4f65-47ff-9345-2adb4b02ea37.png)

**Comment by alexey-milovidov** [comment]
Looks like you have also done something with this server so the data cannot be found.

**Comment by Sallery-X** [comment]
> Looks like you have also done something with this server so the data cannot be found.

if the data cannot be found. why he all data and metadata was delete? and haven't log about remove all data and metadata.

**Comment by den-crane** [comment]
You need to figure out it yourself. We cannot help you. 
You provide too little information: no configs, no steps, no logs.

**Comment by alexey-milovidov** [comment]
ClickHouse does not delete all data or metadata on its own.
Most likely this is some operations error on your side.
