### ISSUE TITLE
[Question] Array vs De-normalized storage

### ISSUE THREAD

**Issue by fizerkhan** [ClickHouse/ClickHouse#2775]
We are calculating performance timing of every transaction in our backend code. Most of the things are common such as

```
{
    appName String,
    hostName String,
    ....
    version String
    tags String,

    duration UInt32 or Array(UInt32) // => This is the question
}
```

We collect this for every minute. So when multiple transactions happen, we were earlier storing this duration as an array in ElasticSearch. In ElasticSearch, the array can also be used in aggregation functions such as `min`, `max`, `sum`, `avg` etc.

Now we are looking to move this into ClickHouse. In this case, what is the recommended solution:

**Solution 1**:. To continue storing duration as array. If yes, could we apply aggregate functions such as `sum`, `avg` etc on array values? Or should we use `ARRAY JOIN` and transform it to calculate this.

**Solution 2**:. If we have to use `ARRAY JOIN` and transform, then does it make sense to denormalise and store the duration as `UInt32` and then store each row separately.

What are the pros and cons in both these approaches WRT to storage, query performance etc?

**Comment by vpanfilov** [comment]
Read these section of documentation:

- https://clickhouse.yandex/docs/en/query_language/agg_functions/combinators/
- https://clickhouse.yandex/docs/en/query_language/functions/higher_order_functions/

There are many ways for working with arrays in Clickhouse: using aggregating functions with `-Array` combinator, `arrayReduce` function or higher-order functions:
```sql
SELECT sumArray(arrayJoin([[1, 2, 3], [4, 5]])) AS result

┌─result─┐
│     15 │
└────────┘

SELECT avgArray(arrayJoin([[1, 2, 3], [4, 5]])) AS result

┌─result─┐
│      3 │
└────────┘

SELECT quantileArray(0.3)(arrayJoin([[1, 2, 3], [4, 5]])) AS result

┌─result─┐
│    2.2 │
└────────┘

SELECT arrayReduce('sum', arrayJoin([[1, 2, 3], [4, 5]])) AS result

┌─result─┐
│      6 │
│      9 │
└────────┘

SELECT arrayReduce('avg', arrayJoin([[1, 2, 3], [4, 5]])) AS result

┌─result─┐
│      2 │
│    4.5 │
└────────┘

SELECT arrayReduce('quantile(0.3)', arrayJoin([[1, 2, 3], [4, 5]])) AS result

┌─result─┐
│    1.6 │
│    4.3 │
└────────┘

SELECT arrayFilter(x -> ((x % 2) = 1), arrayJoin([[1, 2, 3], [4, 5]])) AS result

┌─result─┐
│ [1,3]  │
│ [5]    │
└────────┘

SELECT arrayMap(x -> pow(x, 2), arrayJoin([[1, 2, 3], [4, 5]])) AS result

┌─result──┐
│ [1,4,9] │
│ [16,25] │
└─────────┘
```

**Comment by vpanfilov** [comment]
Clickhouse compress data by default, so de-normalized scheme should work good enough in terms of disk space. But you should carefully choose the primary key for sorting rows in MergeTree engine (table is stored in pieces sorted by PK).

I don't know if there is any benchmarks for storing metrics in arrays. Many people prefer to use de-normalized tables in Clickhouse.

**Comment by filimonov** [comment]
> In Schema 1, I will write every single route access as single row in ClickHouse.
> In Schema 2, I will batch the 100 route access(response times in array) in a single row. 

If you will actively use that column, and most of heavy selects will require ARRAY JOIN - just prefer Scheme 1. Simple integers are more effecient than arrays.
