### ISSUE TITLE
Bit shift operations for `FixedString` and `String` data types.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#27763]
**Use case**

#8922

**Example**

```
SELECT bitShiftRight(toFixedString('abc', 3), 10)
```

**Comment by nicelulu** [comment]
Is its return value also a String data type? There should be no need to move to the left.

**Comment by nicelulu** [comment]
@alexey-milovidov Hi, may I take this task?

**Comment by alexey-milovidov** [comment]
@nicelulu 

> Hi, may I take this task?

Sure, it will be very appreciated!

> Is its return value also a String data type like "010101"?

If argument has String type, the return value also has String type.
If argument has FixedString type, the return value is also FixedString but with different size depending on shift amount.

Let's look at the example.

Suppose we have a string `Hello`. Let's shift it one bit left.
We can emulate it as following:

1. Take its binary (bitwise) representation:

```
SELECT bin('Hello')

┌─bin('Hello')─────────────────────────────┐
│ 0100100001100101011011000110110001101111 │
└──────────────────────────────────────────┘
```

2. Add zero bit to the right:

```
SELECT concat(bin('Hello'), '0')

┌─concat(bin('Hello'), '0')─────────────────┐
│ 01001000011001010110110001101100011011110 │
└───────────────────────────────────────────┘
```

3. Convert back to String:

```
SELECT unbin(concat(bin('Hello'), '0'))

┌─unbin(concat(bin('Hello'), '0'))─┐
│ �����                                 │
└──────────────────────────────────┘
```

The result is unreadable as expected.
We can look at it in hex:

```
SELECT hex(unbin(concat(bin('Hello'), '0')))

Query id: 88512e7e-4937-455a-84ef-24579ffb05de

┌─hex(unbin(concat(bin('Hello'), '0')))─┐
│ 90CAD8D8DE                            │
└───────────────────────────────────────┘
```

**Comment by nicelulu** [comment]
The result we need is this:
```
SELECT bitShiftRight('Hello', 30)

Query id: 7242126f-a7e9-4897-9727-3be5cb368bcf

┌─bitShiftRight('Hello', 30)─┐
│ 0100100001                 │
└────────────────────────────┘

```
```
SELECT unbin('0100100001')

Query id: d0cb7760-bce2-447e-8130-e84f4efaa525

┌─unbin('0100100001')─┐
│ !                   │
└─────────────────────┘

```
or this:
```
SELECT bitShiftRight('Hello', 30)

Query id: 7242126f-a7e9-4897-9727-3be5cb368bcf

┌─bitShiftRight('Hello', 30)─┐
│ !                          │
└────────────────────────────┘
```
@alexey-milovidov Which result do we use is better, ```0100100001``` or ```!```?
