### ISSUE TITLE
Allow type casts between aggregate function states with the same representation

### ISSUE THREAD

**Issue by vmihailenco** [ClickHouse/ClickHouse#27761]
For example, it is not possible to change column type from `quantilesTDigest` to `quantilesTDigestWeighted`

```sql
CREATE TABLE test
(
    `foo` AggregateFunction(quantilesTDigest(0.5), Float32)
)
ENGINE = MergeTree
ORDER BY tuple()

ALTER TABLE test
    MODIFY COLUMN `foo` AggregateFunction(quantilesTDigestWeighted(0.5), Float32, UInt32)

Received exception from server (version 21.7.7):
Code: 70. DB::Exception: Received from localhost:9000. DB::Exception: Conversion from AggregateFunction(quantilesTDigest(0.5), Float32) to AggregateFunction(quantilesTDigestWeighted(0.5), Float32, UInt32) is not supported: While processing CAST(foo, 'AggregateFunction(quantilesTDigestWeighted(0.5), Float32, UInt32)') AS foo.
```

Also it would be handy to support conversions between `groupUniqArray(100)` and `groupUniqArray(1000)`.

The suggestion is to maintain the list of such identical types and use the list only for `MODIFY COLUMN` since I guess performance can be an issue.

**Comment by tavplubix** [comment]
Related to #26847 (see discussion in comments)

**Comment by vmihailenco** [comment]
Gentle ping. Adding an option to force type conversion is probably not to hard but will save a lot of time in some cases, e.g.

```sql
alter table table
modify column col type
settings force_convert_type = 1
```

The query above will only update the table schema without changing any data on the disk. It is up to the user to make sure the type can be changed safely.
