### ISSUE TITLE
MaterializeMySQLSyncThread: Code: 1002, e.displayText() = DB::Exception: ParseMetaData: Unhandled data type:245, Stack trace (when copying this message, always include the lines below)

### ISSUE THREAD

**Issue by jiazhongyi** [ClickHouse/ClickHouse#27775]
clickhouse error log :
2021.08.17 13:51:12.862023 [ 60435 ] {} <Error> MaterializeMySQLSyncThread: Code: 1002, e.displayText() = DB::Exception: ParseMetaData: Unhandled data type:245, Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x8f9b87a in /usr/bin/clickhouse
1. DB::MySQLReplication::TableMapEvent::parseMeta(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) @ 0x1007aecb in /usr/bin/clickhouse
2. DB::MySQLReplication::TableMapEvent::parseImpl(DB::ReadBuffer&) @ 0x1007a823 in /usr/bin/clickhouse
3. DB::MySQLReplication::MySQLFlavor::readPayloadImpl(DB::ReadBuffer&) @ 0x100824a5 in /usr/bin/clickhouse
4. DB::MySQLProtocol::IMySQLReadPacket::readPayload(DB::ReadBuffer&, unsigned char&) @ 0x10066807 in /usr/bin/clickhouse
5. DB::MySQLProtocol::PacketEndpoint::tryReceivePacket(DB::MySQLProtocol::IMySQLReadPacket&, unsigned long) @ 0x1006730e in /usr/bin/clickhouse
6. DB::MaterializeMySQLSyncThread::synchronization() @ 0x10031b1d in /usr/bin/clickhouse
7. ? @ 0x10054354 in /usr/bin/clickhouse
8. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x8fdc4ff in /usr/bin/clickhouse
9. ? @ 0x8fdfde3 in /usr/bin/clickhouse
10. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
11. clone @ 0xfe8dd in /usr/lib64/libc-2.17.so
 (version 21.8.3.44 (official build))

/*!50530 SET @@SESSION.PSEUDO_SLAVE_MODE=1*/;
/*!50003 SET @OLD_COMPLETION_TYPE=@@COMPLETION_TYPE,COMPLETION_TYPE=0*/;
DELIMITER /*!*/;
# at 867644705
#210816 10:12:23 server id 439216  end_log_pos 0 CRC32 0x6b028eee       Start: binlog v 4, server v 5.7.18-log created 210816 10:12:23
BINLOG '
h8kZYQ+wswYAdwAAAAAAAAAAAAQANS43LjE4LWxvZwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAEzgNAAgAEgAEBAQEEgAAXwAEGggAAAAICAgCAAAACgoKKioAEjQA
Ae6OAms=
'/*!*/;
# at 867644705
#210817 13:51:13 server id 439216  end_log_pos 867644795 CRC32 0x8e257dd6       Table_map: `creditdebtcenter_test`.`t_cdc_change_record` mapped to number 60700
# at 867644795
#210817 13:51:13 server id 439216  end_log_pos 867644943 CRC32 0x75761c11       Write_rows: table id 60700 flags: STMT_END_F

BINLOG '
UU4bYROwswYAWgAAAHs1tzMAABztAAAAAAEAFWNyZWRpdGRlYnRjZW50ZXJfdGVzdAATdF9jZGNf
Y2hhbmdlX3JlY29yZAAGCAgP9RIPBoAABAAoAD7WfSWO
UU4bYR6wswYAlAAAAA82tzMAABztAAAAAAEAAgAG/8DGYAAAAAAAAJdysKgEAAAAEFFuU01pWkhu
ZUJiTm5Td0tCAAAAAAIAQQASAAUAFwAHAAAeAAw1AGFwcGx5b3JkZXJJZAEAFwALAAoADBUAbmV0
T3V0c2lkZQEwCzIwMDEwMDA1MTQzmapi3M0DMTEwERx2dQ

CREATE TABLE `t_cdc_change_record` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT ,
  `order_id` bigint(20) DEFAULT NULL ,
  `request_id` varchar(32) DEFAULT NULL,
  `content` json DEFAULT NULL ,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP ,
  `channel` varchar(10) DEFAULT NULL ,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=24783 DEFAULT CHARSET=utf8mb4

MaterializeMySQL sync error

**Comment by alexey-milovidov** [comment]
MaterializeMySQL is not under active development and still not recommended to be used in production.
