### ISSUE TITLE
How to populate multiple columns count in MV grouping one column

### ISSUE THREAD

**Issue by thomastatin** [ClickHouse/ClickHouse#27797]
Hi guys ! 

Thanks for this amazing project ! 

I have a question about materialized views :

I have a ReplicatedMergeTree table that contains non-aggregated data with hundreds of millions records / day and I'm trying to populate SummingMergeTree table automatically with a materialized view.

Each record of the ReplicatedMergeTree table has a timestamp, a "trigger" and 150 metrics like this : 

`timestamp | trigger | metric1 | metric2 | metric3 | ... | metric150
`

I have about a hundred different triggers values possible (triggerName1, triggerName2, ... triggerName100)

I want to count the number of each trigger by **day** for my top 8 metrics like this : 

`date | metric1 | metric2 | metric3 | ... | metric 8 | numberOfTriggerName1 | numberOfTriggerName2 | numberOfTriggerName3 | ... | numberOfTriggerName100`

This seems to work when inserted in SummingMergeTree table : 

```
CREATE MATERIALIZED VIEW mv1
TO dest
AS
SELECT toDate(timestamp) as date, metric1, metric2, metric3, metric4, metric5, metric6, metric7, metric8, 
sumIf(1, equals(trigger, 'triggerName1')) as numberOfTriggerName1 , sumIf(1, equals(trigger,'triggerName2')) as numberOfTriggerName2, ...,  sumIf(1, equals(trigger,'triggerName100')) as numberOfTriggerName100
FROM my_table
GROUP BY date, metric1, metric2, metric3, metric4, metric5, metric6, metric7, metric8;
```

but I'm really, really ashamed to write something like this

I can't create multiple tables in my usecase.

I'm fearing of missing out something, I just want sum of each trigger grouped by some metrics 

Which CH feature would be more elegant and above all more efficient ?

I don't think I'm the first to need to sum triggers or events, CH seems to be the perfect solution for it

Thanks for your help :-)

**Comment by den-crane** [comment]
It will be much easier with an example (create table / insert 3 rows / expected result ) and with 3 metrics.

You can use nested structures + SummingMergeTree https://clickhouse.tech/docs/en/engines/table-engines/mergetree-family/summingmergetree/#nested-structures

I would use trigger as another dimension `GROUP BY date, trigger, metric1, metric2, ...`

**Comment by thomastatin** [comment]
Yes, sorry for this lack of details

When inserting this : 

```
INSERT INTO replicated_mergetree_table (timestamp, trigger, metric1, metric2, metric3) VALUES 
    (1629231913, 'aa', 'London', 'Tiger', 4),
    (1629231929, 'aa', 'London', 'Tiger', 4),
    (1629231930, 'ab', 'London', 'Lion' , 5),
    (1629231941, 'aa', 'Moscow', 'Lion',  6),
    (1629231950, 'aa', 'Moscow', 'Tiger', 8),
    (1629231952, 'ac', 'Moscow', 'Tiger', 8)

```

I'm expecting this result in the materialized view : 

```
SELECT * FROM dest;

-------------------------------------------------------------------------------------
|   Date    |  metric1 |  metric2  | metric3 | trigger_aa | trigger_ab | trigger_ac |
-------------------------------------------------------------------------------------
2021-08-17  |  London  |   Tiger   |    4    |      2     |      0     |      0     |
2021-08-17  |  London  |   Lion    |    5    |      0     |      1     |      0     |
2021-08-17  |  Moscow  |   Lion    |    6    |      1     |      0     |      0     |
2021-08-17  |  Moscow  |   Tiger   |    8    |      1     |      0     |      1     |
-------------------------------------------------------------------------------------
```

yes, use trigger as another dimension was my first choice but It makes multiple records for (date, metric1, metric2, metric3).
When I use trigger as another dimension I have this result : 

```
----------------------------------------------------------------
|   Date    |  metric1 |  metric2  | metric3 | trigger | count | 
----------------------------------------------------------------
2021-08-17  |  London  |   Tiger   |    4    |    aa   |   2   |
2021-08-17  |  London  |   Lion    |    5    |    ab   |   1   |
2021-08-17  |  Moscow  |   Lion    |    6    |    aa   |   1   |
2021-08-17  |  Moscow  |   Tiger   |    8    |    aa   |   1   |
2021-08-17  |  Moscow  |   Tiger   |    8    |    ac   |   1   |
----------------------------------------------------------------
```

Thanks Denny for your help, and "Everything you should know about materialized views" which helps a lot :-)

**Comment by den-crane** [comment]
I still don't see a problem.
https://clickhouse.tech/docs/en/engines/table-engines/mergetree-family/summingmergetree/#nested-structures will work
Basically the same as  sumMap against table with trigger dimension

```
select Date  , metric1 ,  metric2  , metric3, sumMap(trigger, count)
...
group by Date  , metric1 ,  metric2  , metric3
```

You cannot return with a  query with dynamic number of columns it against SQL.

metric1... metric150 (150 dimensions) also look scary I would redesing them somehow, using arrays or one more pivot.

**Comment by thomastatin** [comment]
yes thanks :)
