### ISSUE TITLE
runningAccumulate with window

### ISSUE THREAD

**Issue by sergeevik** [ClickHouse/ClickHouse#27798]
runningAccumulate accumulate all in group. What if we want to accumulate last n rows, not all.

For example we have table from 1 to 10
runningAccumulate return 

│ 0 │   0 │
│ 1 │   1 │
│ 2 │   3 │
│ 3 │   6 │
│ 4 │  10 │
│ 5 │  15 │
│ 6 │  21 │
│ 7 │  28 │
│ 8 │  36 │
│ 9 │  45 │

In my suggestion, call runningAccumulate(column, 2), and get result:

│ 0 │   0 │
│ 1 │   1 │
│ 2 │   3 │
│ 3 │   5 │ (2+3)
│ 4 │  7 │ (3+4)
│ 5 │  9 │ (5+4)
│ 6 │  11 │ (5+6)
│ 7 │  13 │ (6+7)
│ 8 │  15 │ (7+8)
│ 9 │  17 │ (8+9)

Use case: for me is DAU/MAU report when i need calculate active users for every day with 30 day before
today minus 30 day
yesterday minus 30 day
...

Now i use materialized view with arrayJoin(30). Get this idea from [medium](https://medium.com/@andre_bodro/how-to-fast-calculating-mau-in-clickhouse-fd793559b229)

some my analytics about performance:
use ArrayJoin (calculate last 60 day): 
30 rows in set. Elapsed: 12.780 sec. Processed 8.84 million rows, 459.69 MB (691.90 thousand rows/s., 35.97 MB/s.) 

use runningAccumulate (accumulate last 60 day):
27 rows in set. Elapsed: 1.835 sec. Processed 8.37 million rows, 434.96 MB (4.56 million rows/s., 236.97 MB/s.)

**Comment by den-crane** [comment]
```sql
SET allow_experimental_window_functions = 1;

SELECT
    x,
    sum(x) OVER (ORDER BY x ASC)
FROM
(
    SELECT arrayJoin(range(10)) AS x
)

Query id: 670e090c-4088-4c7a-a366-221a4c5aebc3

┌─x─┬─sum(x) OVER (ORDER BY x ASC)─┐
│ 0 │                            0 │
│ 1 │                            1 │
│ 2 │                            3 │
│ 3 │                            6 │
│ 4 │                           10 │
│ 5 │                           15 │
│ 6 │                           21 │
│ 7 │                           28 │
│ 8 │                           36 │
│ 9 │                           45 │
└───┴──────────────────────────────┘

SELECT
    x,
    x + z
FROM
(
    SELECT
        x,
        sum(x) OVER (ORDER BY x ASC ROWS BETWEEN 1 PRECEDING AND 1 PRECEDING) AS z
    FROM
    (
        SELECT arrayJoin(range(10)) AS x
    )
)
┌─x─┬─plus(x, z)─┐
│ 0 │          0 │
│ 1 │          1 │
│ 2 │          3 │
│ 3 │          5 │
│ 4 │          7 │
│ 5 │          9 │
│ 6 │         11 │
│ 7 │         13 │
│ 8 │         15 │
│ 9 │         17 │
└───┴────────────┘

```
