### ISSUE TITLE
Connection failed at try №1, reason: Code: 32, e.displayText() = DB::Exception: Attempt to read after eo f (version 21.6.8.62 (official build))

### ISSUE THREAD

**Issue by shadowDy** [ClickHouse/ClickHouse#27805]
A distributed query, and many read EOF warning logs appear on the driver side. 
In the final aggregation return stage, there is a log of not enough idle threads, resulting in the query failure to return in time and the query timeout.
log details:
![image](https://user-images.githubusercontent.com/18388143/129857206-bb985ebd-f93d-4e0e-b9f8-c0291a8d0a52.png)
PS:The hidden table name is not a query table
After 2 minutes, the same queryid prints out the following logs, among which there are other retrieval logs and merge logs
![image](https://user-images.githubusercontent.com/18388143/129857432-8c4c4f65-b133-4c5d-af18-41780c472bab.png)

questions:

1: Why are there so many read EOF warning logs? Is there a problem.

2: How to solve this long tail problem? Is it because merge affects retrieval?

**Comment by zhbdesign** [comment]
What is the reason and how to solve it? I also encountered it

**Comment by zhanghuajieHIT** [comment]
How did you solve it？
