### ISSUE TITLE
Hints for joins and unions

### ISSUE THREAD

**Issue by GSokol** [ClickHouse/ClickHouse#27845]
**Use case**

As far ad Clickouse supports merge joins, I want to utilize it to build DWH with modal layer relying on Anchor modeling or High Normalized Hybrid Modeling. That models require a huge amount of joins. In some cases, it would be joins of rather big datamarts, when merge joins would be preferable, In other cases, the data marts would be relatively small by nature and hash joins would give more performance. So it would be great to have some kind of tool to specify implicitly which kind of join is preferred in the particular case.

**Describe the solution you'd like**

Greenplum and Vertical utilize comment-based hints to implicitly suggest the join type. These databases are highly popular in DWH community, so we could inherit this practice.

**Describe alternatives you've considered**

MS SQL supports the extended join syntax when you could specify the desired join type with keywords.

**Comment by GSokol** [comment]
I mean that I want to do something like
```sql
SELECT /*...*/
FROM h_users /* huge table */
LEFT JOIN /*JOIN_TYPE MERGE*/ s_user__height USING (user_id) /* another huge table */
LEFT JOIN /*JOIN_TYPE HASH*/ l_user__doctoral_diploma USING (user_id) /* small table */
/*...*/
```

**Comment by zhanglistar** [comment]
That's usefull.

**Comment by den-crane** [comment]
Clickouse *does not support* merge joins

 Anchor modeling is impossible with CH because of sparse indexes

**Comment by GSokol** [comment]
> Clickouse **does not support** merge joins

@den-crane in last versions, it seams, that it does, or what is that `join_algorithm=partial_merge` setting is about? https://clickhouse.tech/docs/en/operations/settings/settings/amp/#settings-join_algorithm

**Comment by GSokol** [comment]
> Anchor modeling is impossible with CH because of sparse indexes

@den-crane but what if to utilize projections (another modern feature) instead of indexes?

**Comment by den-crane** [comment]
partial_merge is very slow, it does not use indexes. It sorts the left table twice.

>but what if to utilize projections (another modern feature) or materialized view instead of indexes?

no, no.

No chance that Anchor modeling will work in CH during next 2-3 years. Nobody works on it. Yandex does not neet. Altinity does not need it. It's not in the roadmap.

**Comment by den-crane** [comment]
And actually I don't think that Anchor models is viable with billion rows.

**Comment by GSokol** [comment]
@den-crane, about Clickhouse usage for anchor modeling-- perhaps you are right! bout the billion of rows, it's literally the case. Here is, for example, the paper on it https://www.researchgate.net/publication/283896030_Big_Data_Normalization_for_Massively_Parallel_Processing_Databases

**Comment by GSokol** [comment]
Maybe, we should take Greenplum for it.

**Comment by alexey-milovidov** [comment]
Comment-based hints better remain unimplemented.
