### ISSUE TITLE
Column transformes support lambda for APPLY(x->argMax(x,number))

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#27877]
**Use case**

APPLY could be useful for making queries cleaner, but it doesn't support functions with multiple arguments.
And this feature request should make it possible to do.

**Describe the solution you'd like**
```
SELECT * EXCEPT 'a' APPLY(x->argMax(x,number)) FROM numbers(10);
```

**Comment by amosbird** [comment]
Good idea. Or we can wait for https://github.com/ClickHouse/ClickHouse/pull/27796

**Comment by amosbird** [comment]
#27901
