### ISSUE TITLE
Apache hive reading supported question

### ISSUE THREAD

**Issue by zhanglistar** [ClickHouse/ClickHouse#27898]
We have implemented accessing hive from clickhouse from a single node, BUT
we want to access hive from multi clickhouse node, does anybody have any suggestions?

Here is our plan:
first, implement a hivestorage, in the read method, get the files the table needs to read, and distributed the files to other nodes according some policy to execute the plan, and construct multiple reading stream from other nodes.
second, other nodes receive the plan and execute it, return result to initiator.
finaly, return the merging result stream to caller.

**Comment by amosbird** [comment]
You can refer to https://github.com/ClickHouse/ClickHouse/pull/22012
