### ISSUE TITLE
Clickhouse should have a proper vulnerability disclosure policy

### ISSUE THREAD

**Issue by JasonKeirstead** [ClickHouse/ClickHouse#27896]
The current vulnerability disclosure policy (VDP) is only one sentence:

"To report a potential vulnerability in ClickHouse please send the details about it to clickhouse-feedback@yandex-team.com"

Ideally, the policy should really contain a lot more details

- What is the scope of the policy?
- When should it report, when should I *NOT* report?
- What is the indemnification, if any, of the researchers?
- What is the expected timeline for each stage, from response through to resolution? Is there any committed timeline for acknowledgement? How long is the researcher expected to keep their findings private, etc?

There are a lot of projects from which Clickhouse could borrow elements of a good VDP from. One example is Kubernetes https://kubernetes.io/docs/reference/issues-security/security/

HackerOne has a good article on this: https://www.hackerone.com/vulnerability-management/vulnerability-disclosure-policy-basics-5-critical-components

**Comment by alexey-milovidov** [comment]
Thank you!

Current policy is "see something - say something". If you found potential vulnerability are not sure shoult you report it - just report it.

> What is the indemnification, if any, of the researchers?

We still don't have bug bounty program. I want to establish it, but I don't know how soon it will be created.
After vulnerability will be fixed and disclosed, we add attribution to the researcher in the changelog and in CVE entry.

> What is the expected timeline for each stage, from response through to resolution? Is there any committed timeline for acknowledgement? How long is the researcher expected to keep their findings private, etc?

Up to 90 days from the report before public disclosure.

**Comment by JasonKeirstead** [comment]
Hi @alexey-milovidov - sorry to be clear what I was suggesting is a proper documented VDP should be present at https://github.com/ClickHouse/ClickHouse/security/policy

Right now there is nothing there. None of the details you said above are present.

PS this doesn't really have anything to do with bug bounties, it has to do with communicating how to properly disclosure vulnerabilities to researchers, and the fact that you will protect them, what the disclosure window is to keep it private, etc. Without a robust VDP you risk people just releasing vulnerabilities to the public, which is dangerous.

**Comment by JasonKeirstead** [comment]
I will do a PR on the policy so you can see an example.
