### ISSUE TITLE
About clickhouse v21.7.8.58-stable compilation and installation issues

### ISSUE THREAD

**Issue by angkorthomwdd** [ClickHouse/ClickHouse#27936]
Hi,
	When I try compile and install the clickhouse in linux, It's always unable to compile through and reported error,then stop work. My compiler is the gcc11. Why this is?

The following error is reported:

[6186/9589] Building CXX object contrib/fastops-cma.../fastops.dir/__/fastops/fastops/avx2/ops_avx2.cpp.
FAILED: contrib/fastops-cmake/CMakeFiles/fastops.dir/__/fastops/fastops/avx2/ops_avx2.cpp.o 
/usr/local/bin/c++  -DSTD_EXCEPTION_HAS_STACK_TRACE=1 -I../contrib/sentry-native/include -I../base/glibc-compatibility/memcpy -isystem ../contrib/fastops -isystem ../contrib/libcxx/include -isystem ../contrib/libcxxabi/include -isystem ../contrib/libunwind/include -isystem ../contrib/libc-headers/x86_64-linux-gnu -isystem ../contrib/libc-headers -fdiagnostics-color=always -fsized-deallocation  -msse4.1 -msse4.2 -mpopcnt -fasynchronous-unwind-tables -falign-functions=32   -Wall  -Werror -w -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -O2 -g -DNDEBUG -O3  -fno-pie   -D OS_LINUX -nostdinc++ -std=gnu++2a -mavx2 -mfma -MD -MT contrib/fastops-cmake/CMakeFiles/fastops.dir/__/fastops/fastops/avx2/ops_avx2.cpp.o -MF contrib/fastops-cmake/CMakeFiles/fastops.dir/__/fastops/fastops/avx2/ops_avx2.cpp.o.d -o contrib/fastops-cmake/CMakeFiles/fastops.dir/__/fastops/fastops/avx2/ops_avx2.cpp.o -c ../contrib/fastops/fastops/avx2/ops_avx2.cpp
In file included from ../contrib/fastops/fastops/core/FastIntrinsics.h:6,
                 from ../contrib/fastops/fastops/avx2/ops_avx2.cpp:3:
../contrib/fastops/fastops/core/SIMDFunctions.h:19:1: error: '__m128i _mm_loadu_si32(const void*)' redeclared inline without 'gnu_inline' attribute
   19 | _mm_loadu_si32(void const* __a) {
      | ^~~~~~~~~~~~~~
In file included from ../contrib/fastops/fastops/core/SIMDFunctions.h:9,
                 from ../contrib/fastops/fastops/core/FastIntrinsics.h:6,
                 from ../contrib/fastops/fastops/avx2/ops_avx2.cpp:3:
/opt/gcc11/lib/gcc/x86_64-pc-linux-gnu/11.2.0/include/emmintrin.h:719:1: note: '__m128i _mm_loadu_si32(const void*)' previously defined here
  719 | _mm_loadu_si32 (void const *__P)
      | ^~~~~~~~~~~~~~

**Comment by alexey-milovidov** [comment]
It is recommended to use clang, versions 11 or newer.
