### ISSUE TITLE
select order by somefield, timestamp desc limit 1 is too slow

### ISSUE THREAD

**Issue by yandd** [ClickHouse/ClickHouse#28003]
**Describe the unexpected behaviour**
select order by somefield, timestamp desc limit 1 is too slow

**How to reproduce**
* Which ClickHouse server version to use: *v20.8.7.15*
* Queries to run that lead to unexpected result
  Q1 (ASC):
  ```sql
  SELECT *
  FROM   log.all_log
  WHERE  appName = 'WmsStatDev'
         AND timestamp >= '2021-08-19 00:00:00'
  ORDER  BY appName,
            timestamp
  LIMIT  1; 
  ```
  1 rows in set. Elapsed: **0.324 sec**. Processed 358.20 thousand rows, 649.78 MB (1.11 million rows/s., 2.01 GB/s.)

  Q2 (DESC):
  ```sql
  SELECT *
  FROM   log.all_log
  WHERE  appName = 'WmsStatDev'
         AND timestamp >= '2021-08-19 00:00:00'
  ORDER  BY appName,
            timestamp DESC
  LIMIT  1; 
  ```

  1 rows in set. Elapsed: **14.054 sec**. Processed 18.92 million rows, 29.98 GB (1.35 million rows/s., 2.13 GB/s.)

**Expected behavior**
Q2 should be faster as Q1.

**Error message and/or stacktrace**
Q1:
<Debug> MergingSortedTransform: Merge sorted 1 blocks, 1 rows in 0.057000487 sec., 17.54370975812891 rows/sec., 40.79 KiB/sec
<Debug> MergingSortedTransform: Merge sorted 1 blocks, 1 rows in 0.076000649 sec., 13.157782376305759 rows/sec., 29.36 KiB/sec

Q2:
<Debug> MergingSortedTransform: Merge sorted 1397 blocks, 7465915 rows in 3.507030134 sec., 2128842.557587217 rows/sec., 6.53 GiB/sec
<Debug> MergingSortedTransform: Merge sorted 1457 blocks, 7671357 rows in 4.940042447 sec., 1552892.9320554077 rows/sec., 4.88 GiB/sec

**Additional context**
Table defined as:
```sql
CREATE TABLE log.log
(
    `appName` String,
    `level` String,
    `host` String,
    `ip` IPv4,
    `message` String,
    `logger` String,
    `type` String,
    `title` String,
    `costTime` Int64,
    `timestamp` DateTime64(3),
    `_source` String,
    `string.names` Array(String),
    `string.values` Array(String),
    `number.names` Array(String),
    `number.values` Array(Float64),
    `bool.names` Array(String),
    `bool.values` Array(UInt8)
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/log/log', '{replica}')
PARTITION BY toYYYYMMDD(timestamp)
ORDER BY (appName, timestamp)
SETTINGS index_granularity = 8192

CREATE TABLE log.all_log
(
    `appName` String,
    `level` String,
    `host` String,
    `ip` IPv4,
    `message` String,
    `logger` String,
    `type` String,
    `title` String,
    `costTime` Int64,
    `timestamp` DateTime64(3),
    `_source` String,
    `string.names` Array(String),
    `string.values` Array(String),
    `number.names` Array(String),
    `number.values` Array(Float64),
    `bool.names` Array(String),
    `bool.values` Array(UInt8)
)
ENGINE = Distributed('ua_cluster', 'log', 'log')
```

Data Count: 18249089
```
select count() from log.all_log prewhere equals(appName, 'WmsStatDev') and timestamp >= '2021-08-19 00:00:00';
```

**Comment by den-crane** [comment]
Try: `ORDER  BY appName    DESC    , timestamp DESC`

 v20.8.7.15 is out of support. Check with 21.8

**Comment by yandd** [comment]
> Try: `ORDER BY appName DESC , timestamp DESC`
> 
> v20.8.7.15 is out of support. Check with 21.8

```sql
select * from log.all_log where appName IN ('WmsStatDev', 'WmsCenterDev') and timestamp >= '2021-08-22 00:00:00' ORDER BY timestamp DESC limit 2;
```

Clickhouse can not optimize this query too

**Comment by den-crane** [comment]
@yandd it's not that I suggested.

```
select * from log.all_log 
where appName IN ('WmsStatDev', 'WmsCenterDev') and timestamp >= '2021-08-22 00:00:00' 
ORDER BY appName DESC ,   ------<<<<<<<<<<<-----------  appName DESC !!!!
                  timestamp DESC;
````

**Comment by yandd** [comment]
> @yandd it's not that I suggested.
> 
> ```
> select * from log.all_log 
> where appName IN ('WmsStatDev', 'WmsCenterDev') and timestamp >= '2021-08-22 00:00:00' 
> ORDER BY appName DESC ,   ------<<<<<<<<<<<-----------  appName DESC !!!!
>          timestamp DESC;
> ```

Thank you! I get it. I will use `appName DESC, timestamp DESC` with `union all` for multi appName
