### ISSUE TITLE
Wrong default value for max_server_memory_usage_to_ram_ratio

### ISSUE THREAD

**Issue by depressed-pho** [ClickHouse/ClickHouse#28002]
**Describe the issue**

``max_server_memory_usage_to_ram_ratio`` is documented as being defaulted to 0, but its actually 0.9 by default.

**Additional context**

https://github.com/ClickHouse/ClickHouse/blob/e620ea15bdb08ebf3e9a580b0072350c9b3aeb9e/programs/server/Server.cpp#L838

**Comment by alexey-milovidov** [comment]
Please update the docs.

**Comment by den-crane** [comment]
documentation already fixed
