### ISSUE TITLE
MergeTreeThread has feature spill data to disk?

### ISSUE THREAD

**Issue by aaawuanjun** [ClickHouse/ClickHouse#28005]
when use sql to query distributed tables "select * from dbname.tablename_all", no limitations, it is easy to appear such exception:
"_DB::Exception: Received from localhost:9000. DB::Exception: Memory limit (for query) exceeded: would use 93.38 GiB (attempt to allocate chunk of 362340215 bytes), maximum: 93.13 GiB: **While executing MergeTreeThread.**_"

when the memory is not enough, should be spill on disk, does it has this feature "While executing MergeTreeThread"

**Comment by aaawuanjun** [comment]
Although this it not a good sql, but my goal is to export data to other clusters

**Comment by den-crane** [comment]
How many columns in your table?
Clickhouse version? `select version()`?
Can you share `set send_logs_level='trace'; select * from dbname.tablename_all format Null;`
Try `set max_threads=1, max_block_size=8192`

**Comment by aaawuanjun** [comment]
clickhouse version: 21.5.5.12
columns:34
rows:644320978

ok, I am trying 
> set max_threads=1, max_block_size=8192

at present , no error occur, I successfully to export data to local.

**Comment by sdhzwc** [comment]
> clickhouse version: 21.5.5.12 columns:34 rows:644320978
> 
> ok, I am trying
> 
> > set max_threads=1, max_block_size=8192
> 
> at present , no error occur, I successfully to export data to local.

![image](https://github.com/user-attachments/assets/3acb94ae-345a-4259-8023-9a931880607a)
![image](https://github.com/user-attachments/assets/e259e9f0-6510-42e4-953b-488f2a6960d5)
version 22.3.2.1

code:
![image](https://github.com/user-attachments/assets/150d8c3f-d5e9-42ec-9daf-7e3c83519946)
![image](https://github.com/user-attachments/assets/fcf7ac40-7719-4e54-8c80-bbc3d3766e6a)

Maximum this I feel that the display 93.13GiB is correct, why the log shows 100GiB, can you give an answer, thank you!
