### ISSUE TITLE
Upgrading format_version

### ISSUE THREAD

**Issue by killwort** [ClickHouse/ClickHouse#28006]
I have some tables with format_version=0 and wanted them to upgrade to format_version=1 ( to set up storage_policy).
How can I do that safely without losing any data? Recreating and refilling tables is not an option as they contain somewhat large amount of live data and have streaming aggregation set up over them.

I've tried naively changing 0 to 1 in that file and clickhouse was unable to read any data from the table.

**Comment by killwort** [comment]
BTW, is there any way to tell clickhouse to upgrade database directory layout to the new version (with symlinks)?

**Comment by den-crane** [comment]
The official way is to reinsert data to the new tables.

Though there is an utility https://github.com/ClickHouse/ClickHouse/blob/master/utils/convert-month-partitioned-parts/main.cpp - it converts parts from the old format to the new, but parts! not tables.

**Comment by killwort** [comment]
> The official way is to reinsert data to the new tables.
That's sad.

Regarding the utility: so it would work if I run it for one table at once? That's feasible.

**Comment by den-crane** [comment]
>Regarding the utility: so it would work if I run it for one table at once? That's feasible.

It runs against folders / files of not against tables. You need to detach table (or shutdown CH) run utility and attach parts to a new table created with matching structure / partitioning but new syntax.

**Comment by rkozlo** [comment]
I have 3 shards in Distributed engine with old format and want to add 3 more with new storage_policy. Can i just create new shards in new format or do i have to migrate all shards?

**Comment by den-crane** [comment]
@rkozlo you need to reinsert data in all shards to new tables
