### ISSUE TITLE
Right outer join with Join engine table behave improperly

### ISSUE THREAD

**Issue by NiDHanWang** [ClickHouse/ClickHouse#28017]
> You have to provide the following information whenever possible.

**Describe the bug**

I got two tables,table `table_merge_engine`'s engine is `ReplacingMergeTree`
```sql
CREATE TABLE fact_test.table_merge_engine
(
    `id` String,
    `value` Int16
)
ENGINE = ReplacingMergeTree
PRIMARY KEY id
ORDER BY id
SETTINGS index_granularity = 8192
```
table `table_join_engine`'s engine is `Join`
```sql
CREATE TABLE join_table.table_join_engine
(
    `join_id` String,
    `join_value` Int16
)
ENGINE = Join(ANY,
 RIGHT,
 join_id)


```
Data in `fact_test.table_merge_engine`:

|id	|value|
|--|--|
1	|31,321 |
4	|32,131|

Data in `join_table.table_join_engine`:

|join_id	|join_value|
|--|--|
|3|	412|
|1|	312|

I want to find out data existing in `table_join_engine` but not in  `table_merge_engine`,so my sql was like:
```sql
select t2.join_id ,t2.join_value 
from fact_test.table_merge_engine t1
any right join join_table.table_join_engine t2
	on t1.id =t2.join_id 
where t1.id = ''
```
What I expected:

|join_id	|join_value|
|--|--|
|3|412|

What actually return:
|join_id|join_value|
|--|--|
|3|412|
|1|312|

Why data`{"join_id":"1","join_value":312}` is involved?

**Comment by den-crane** [comment]
CH version? `select version()` 
Does it reproduce with 21.8 ?

**Comment by NiDHanWang** [comment]
> CH version? `select version()`
> Does it reproduce with 21.8 ?

CH version: 21.3.4.25
Didn't try it with v21.8 yet, because we don't have a server running with that version
