### ISSUE TITLE
Invalid predicate expression optimization

### ISSUE THREAD

**Issue by DimasKovas** [ClickHouse/ClickHouse#28014]
**Does it reproduce on recent release?**

Yes

**How to reproduce**

* Which ClickHouse server version to use
Latest master version

* Queries to run that lead to unexpected result
```sql
:) select * from (select * from numbers(10) where number > 0) where toInt64(10 / number) = 1

SELECT *
FROM
(
    SELECT *
    FROM numbers(10)
    WHERE number > 0
)
WHERE toInt64(10 / number) = 1

Query id: 600c4162-f58b-4ef3-8fbd-4b33a8e991b1


0 rows in set. Elapsed: 0.013 sec. 

Received exception from server (version 21.9.1):
Code: 70. DB::Exception: Received from localhost:9000. DB::Exception: Unexpected inf or nan to integer conversion: while executing 'FUNCTION toInt64(divide(10, number) :: 1) -> toInt64(divide(10, number)) Int64 : 2'.
```

**Additional context**

With enable_optimize_predicate_expression=0 query works as expected.

**Comment by zhanglistar** [comment]
I could not reproduce on master, what is the complete sql?  @DimasKovas

**Comment by DimasKovas** [comment]
@zhanglistar
Yeap, sorry. I pulled the master branch again and now it works as expected. It looks like the bug was fixed recently (I guess my brunch was a few weeks old). The issue could be closed. If you know the commit which fixed the issue, please, write it down here. Thanks
