### ISSUE TITLE
Multi-table JOIN  Code: 47, e.displayText() = DB::Exception: Missing columns

### ISSUE THREAD

**Issue by guoqlin** [ClickHouse/ClickHouse#28019]
> Make sure to check documentation https://clickhouse.yandex/docs/en/ first. If the question is concise and probably has a short answer, asking it in Telegram chat https://telegram.me/clickhouse_en is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

> If you still prefer GitHub issues, remove all this text and ask your question here.
SELECT
	`m1nckbdef438o9em38zepg`.`B商品名称` AS `B商品名称`,
	`m1nckbdef438o9em38zepg`.`同时购买A和B订单数` AS `同时购买A和B订单数2`
FROM
	`smartbimpp`.`3qcnfud0fy4lbircffaduw` `3qcnfud0fy4lbircffaduw` 
RIGHT JOIN `smartbimpp`.`m1nckbdef438o9em38zepg` `m1nckbdef438o9em38zepg` ON
	`3qcnfud0fy4lbircffaduw`.`A商品名称` = `m1nckbdef438o9em38zepg`.`A商品名称`
LEFT JOIN `smartbimpp`.`avhnzf9rr2vuyesdvryc6w` `avhnzf9rr2vuyesdvryc6w` ON
	`m1nckbdef438o9em38zepg`.`B商品名称` = `avhnzf9rr2vuyesdvryc6w`.`B商品名称`

 ClickHouse exception, code: 47, host: 10.10.111.129, port: 8123; Code: 47, e.displayText() = DB::Exception: Missing columns: '同时购买A和B订单数' while processing query: 'SELECT `A商品名称` AS `--3qcnfud0fy4lbircffaduw.A商品名称`, `同时购买A和B订单数`, m1nckbdef438o9em38zepg.`A商品名称` AS `--m1nckbdef438o9em38zepg.A商品名称`, `B商品名称` AS `--m1nckbdef438o9em38zepg.B商品名称` FROM smartbimpp.`3qcnfud0fy4lbircffaduw` AS `3qcnfud0fy4lbircffaduw` ALL RIGHT JOIN 
 smartbimpp.m1nckbdef438o9em38zepg AS m1nckbdef438o9em38zepg ON `--3qcnfud0fy4lbircffaduw.A商品名称` = `--m1nckbdef438o9em38zepg.A商品名称`', required columns: 'A商品名称' '同时购买A和B订单数' 'm1nckbdef438o9em38zepg.A商品名称' 'B商品名称', maybe you meant:  '['A商品名称']' '['A商品名称']', joined columns: 'm1nckbdef438o9em38zepg.A商品名称' 'B商品名称' 'm1nckbdef438o9em38zepg.同时购买A和B订单数' 'm1nckbdef438o9em38zepg.总订单数' (version 21.2.5.5 (official build))

**Comment by guoqlin** [comment]
Clickhouse can be successfully extracted using version 19.4.2.7, but failed to extract versions 21.6.6.51 and 21.7.4.18

**Comment by cantfu** [comment]
@guoqlin hello, any solution here?

**Comment by Algunenano** [comment]
Stale issue. Please provide reproduction steps (table schema and queries) to report possible bugs so they can be investigated
