### ISSUE TITLE
Simple questions about master node and optimize query

### ISSUE THREAD

**Issue by Aristat** [ClickHouse/ClickHouse#28015]
Hi! I have two questions (with subsections), sorry if there are some answers but I didn't found them.

1. I want to create a cluster only with shards (without replication/zookeeper), didn't find any description regarding the master node. 
  1.1 The good solution is to place the Distributed table on a separate node - the master node?
  1.2 If 1.1 is true, is there any recommendation for CPU/RAM? as far as I understood, in the master node we don't need to have the same RAM as in the data node, because we simply combine the result from the shards, is it true?
  1.3 If 1.1 is true, is it possible to scale master nodes and this solution doesn't create any problems with parallel aggregation results for n master nodes? for example configuration - 

```
load balancer, 3 master nodes with Distributed tables, and `n` data nodes 
```

or is this a weird solution and it's easier to create a distribution table for each data node without master nodes :)

2. I have one unusual metric and I hope someone help to find the solution. For example, I have these tracks from fronts - 

```
date, event_type: progress, session_id, progress_percent

date, progress, '1', 31
date, progress, '1', 52
date, progress, '1', 78
date, progress, '2', 30
date, progress, '3', 100
```

I need to calculate the maximum percentage for each session and then display it in groups. So, I need to return something like this by one request to Clickhouse - 
`[1,0,1,1]` - `countResample(0, 100, 25)(max progress_percent group by session_id)`

Somehow a better solution could there be? except that front sends 1 more event(something like progress_last to avoid `argMax`) and of course `update percent` in record because this is bad practice

I thought about creating 1 more table - AggregatingMergeTree and store max percent by session there, but I'm not sure if this is a good solution since 1 more table is being created

Thanks

**Comment by den-crane** [comment]
>or is this a weird solution and it's easier to create a distribution table for each data node without master nodes :)

1) It's uncommon solution. In 99% cases easier to create a distribution table for each data node without master nodes. In 1% cases people use this uncommon solution because they need a lot of memory for their "Master" (query-initator) nodes. So they have i.e. 1TB RAM at two nodes (two "Master" nodes) + 20 (n) data nodes with i.e. 64GB RAM. It allows them to save money and be able to do huge in-memory JOINs or/and FinalAggregations.
It has zero relation to Replication/Sharding.


2) I prefer to answer to separated questions in separated issues.

**Comment by Aristat** [comment]
@den-crane thanks 🚀
