### ISSUE TITLE
N-1 replication ?

### ISSUE THREAD

**Issue by champtar** [ClickHouse/ClickHouse#2804]
I'm wondering if there is any way to do N-1 replication (~RAID5)
ie if I have 5 servers, I would have 5 shards and each server will store 2 shards, thus allowing to loose 1 server
```
server 1: shard 1 & 2
server 2: shard 2 & 3
...
server 5: shard 5 & 1
```
Thanks in advance

**Comment by alexey-milovidov** [comment]
"Erasure coding". It's not implemented.
Main reason is implementation complexity.

Things to consider:
- modern reconstruction codes like [LRC](https://github.com/baishancloud/lrc-erasure-code) require to use multiple chunks (example: 12) - it requires sophisticated methods to spread chunks across servers;
- it's not directly compatible with async replication and async data merging on replicas - it requires engineering of complex solutions like plain replication for fresh data and converting to erasure-encoded chunks for older data;
- it's not reasonable to use both erasure codes across different servers and RAID on local disks - better to use erasure codes universally with some chunks placed locally and some across different servers; but to keep up with performance of RAID, chunk size must be small enough (about 1 MB); but small chunks are bad as a unit of replication;
- when using reconstruction codes, reads became very slow (often impractical) when few chunks are lost; significant engineering efforts required to balance between read and write performance, probability of performance degradation and data loss; amount of metadata; network amplification, etc...

**Comment by champtar** [comment]
Hi @alexey-milovidov 
Erasure coding would be awesome, but I was really thinking about something simpler (my reference to RAID5 might have mislead you), even if shard placement has to be done manually (with ansible ;) )

I see 2 simple (tm) solutions:
1) at the distributed table level
If I call my table `logs`, I could have on server 1 table `logs-s1` for the shard 1 and `logs-s2` for the shard 2, the only missing piece might be to teach distributed table to handle `suffix`
```
<remote_servers>
    <logs>
        <shard>
            <weight>1</weight>
            <internal_replication>true</internal_replication>
            <suffix>-s1</suffix>
            <replica>
                <host>server1</host>
                <port>9000</port>
            </replica>
```

2) at the replicated table level
Allow replicated tables to replicate multiple shards
for example go from
```
ReplicatedMergeTree('/clickhouse/tables/shard1/hits', '{replica}', EventDate, intHash32(UserID), (CounterID, EventDate, intHash32(UserID), EventTime), 8192)
```
to
```
ReplicatedMergeTree(['/clickhouse/tables/shard1/hits','/clickhouse/tables/shard2/hits'] , '{replica}', EventDate, intHash32(UserID), (CounterID, EventDate, intHash32(UserID), EventTime), 8192)
```

Without knowing the code I suspect solution 1 would be simpler

**Comment by filimonov** [comment]
Currently doable with one db per shard.

Check that comment: https://github.com/yandex/ClickHouse/issues/1287#issuecomment-406180820

@alexey-milovidov what do you think about  database-dependant macros (described in [comment](https://github.com/yandex/ClickHouse/issues/1287#issuecomment-406180820)) or suffixes?

**Comment by alexey-milovidov** [comment]
> what do you think about database-dependant macros (described in comment) or suffixes?

If I understand correctly, we may introduce special `{database}` macro, that will always expand to database name. And you can use something like `r1-{database}` as replica name.

Sounds Ok.

**Comment by blinkov** [comment]
@champtar, do you have any further questions?
