### ISSUE TITLE
Code: 370, e.displayText() = DB::Exception: Data type Nullable(Nothing) cannot be used in tables

### ISSUE THREAD

**Issue by rakerf** [ClickHouse/ClickHouse#28059]
CREATE MATERIALIZED VIEW xxx
TO yyy
AS
SELECT
null as ccc,
…
FROM zzz
创建物化视图时报错
Code: 370, e.displayText() = DB::Exception: Data type Nullable(Nothing) cannot be used in tables

但是，直接执行
INSERT INTO yyy
SELECT
null as ccc,
…
FROM zzz
却没有问题，请问这是什么原因
clickhouse version 21.7.1.6968

**Comment by den-crane** [comment]
You have to specify type of the null

```
...
SELECT
cast(null, 'String') as ccc,
```

**Comment by rakerf** [comment]
cast(null,'String') AS vehicle_model_name

Code: 70, e.displayText() = DB::Exception: Cannot convert NULL to a non-nullable type: While processing generateUUIDv4() AS id, CAST(NULL, 'String') AS vehicle_model_name

**Comment by rakerf** [comment]
cast(null,'String') AS vehicle_model_name

Code: 70, e.displayText() = DB::Exception: Cannot convert NULL to a non-nullable type: While processing generateUUIDv4() AS id, CAST(NULL, 'String') AS vehicle_model_name
