### ISSUE TITLE
Not found column in block

### ISSUE THREAD

**Issue by jiangxiaom** [ClickHouse/ClickHouse#28057]
Create Table :
CREATE TABLE enjoy_ghome_mysql.ghome_user_login_log
(
    `loginId` Int32 COMMENT '记录id',
    `userId` Int32 COMMENT '用户id',
    `userIp` Nullable(String) COMMENT '用户ip',
    `createDate` DateTime COMMENT '登录时间',
    `_sign` Int8 MATERIALIZED 1,
    `_version` UInt64 MATERIALIZED 1,
    INDEX _version _version TYPE minmax GRANULARITY 1
)
ENGINE = ReplacingMergeTree(_version)
PARTITION BY intDiv(loginId, 4294967)
ORDER BY (userId, createDate, loginId)
SETTINGS index_granularity = 8192

Create Table :
CREATE TABLE enjoy_ghome_mysql.ghome_user_info
(
    `userId` Int32 COMMENT '用户id',
    `mobile` String COMMENT '用户手机号',
    `checkType` Nullable(String) COMMENT '审核方式  01：自动  02：人工',
    `checkDate` Nullable(DateTime) COMMENT '审核时间',
    `createDate` DateTime COMMENT '创建时间',
    `modifyDate` Nullable(DateTime) COMMENT '修改时间',
    `_sign` Int8 MATERIALIZED 1,
    `_version` UInt64 MATERIALIZED 1,
    INDEX _version _version TYPE minmax GRANULARITY 1
)
ENGINE = ReplacingMergeTree(_version)
PARTITION BY intDiv(userId, 4294967)
ORDER BY (assumeNotNull(certificateId), status, assumeNotNull(projectCode), createDate, assumeNotNull(modifyDate), assumeNotNull(lastLoginDate), assumeNotNull(wxOpenid), assumeNotNull(selfImId), mobile, userId)
SETTINGS index_granularity = 8192

Select Query :
SELECT distinct gui0.userId 
FROM
	enjoy_ghome_mysql.ghome_user_login_log AS gull LEFT JOIN 
	enjoy_ghome_mysql.ghome_user_info AS gui0 ON gull.userId = gui0.userId 
WHERE 
	gull.createDate >= '2021-03-03 00:00:00'
	AND gull.createDate < '2021-03-23 00:00:00'
	AND gui0. status = '02' 
	AND gui0.checkDate < '2021-05-03 00:00:00'

DB::Exception: Missing columns: 'aa.createDate' while processing query: ...

**Comment by den-crane** [comment]
There is no `gui0. status = '02'` column.
And you have space in `gui0. status`

**Comment by den-crane** [comment]
Everything works with 21.8

**Comment by den-crane** [comment]
```sql
ClickHouse client version 21.8.4.51 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 21.8.4 revision 54449.

create database enjoy_ghome_mysql;

CREATE TABLE enjoy_ghome_mysql.ghome_user_login_log
(
loginId Int32 COMMENT '记录id',
userId Int32 COMMENT '用户id',
userIp Nullable(String) COMMENT '用户ip',
createDate DateTime COMMENT '登录时间',
_sign Int8 MATERIALIZED 1,
_version UInt64 MATERIALIZED 1,
INDEX _version _version TYPE minmax GRANULARITY 1
)
ENGINE = ReplacingMergeTree(_version)
PARTITION BY intDiv(loginId, 4294967)
ORDER BY (userId, createDate, loginId)
SETTINGS index_granularity = 8192;

CREATE TABLE enjoy_ghome_mysql.ghome_user_info
(
userId Int32 COMMENT '用户id',
mobile String COMMENT '用户手机号',
checkType Nullable(String) COMMENT '审核方式 01：自动 02：人工',
checkDate Nullable(DateTime) COMMENT '审核时间',
createDate DateTime COMMENT '创建时间',
modifyDate Nullable(DateTime) COMMENT '修改时间',
_sign Int8 MATERIALIZED 1,
_version UInt64 MATERIALIZED 1,
INDEX _version _version TYPE minmax GRANULARITY 1
)
ENGINE = ReplacingMergeTree(_version)
PARTITION BY intDiv(userId, 4294967)
ORDER BY ( createDate, assumeNotNull(modifyDate),  mobile, userId)
SETTINGS index_granularity = 8192;

SELECT DISTINCT gui0.userId
FROM enjoy_ghome_mysql.ghome_user_login_log AS gull
LEFT JOIN enjoy_ghome_mysql.ghome_user_info AS gui0 ON gull.userId = gui0.userId
WHERE (gull.createDate >= '2021-03-03 00:00:00') AND (gull.createDate < '2021-03-23 00:00:00') AND (gui0.checkDate < '2021-05-03 00:00:00')

Query id: d8e3ec96-0eb5-4ae8-a6a2-3989f83d83e8

Ok.

0 rows in set. Elapsed: 0.001 sec.

```
