### ISSUE TITLE
Query distributed tables takes too much time

### ISSUE THREAD

**Issue by aaawuanjun** [ClickHouse/ClickHouse#28064]
# Basic Env
ClickHouse Version: 21.5.5.12-stable
OS: Ubuntu 16.04
Kernel: 4.9.0-141-custom
Cpu: Intel(R) Xeon(R) Silver 4110 CPU @ 2.10GHz, 32 Core
Memory: 125GB
Disk: HDD, SATA, RAID10, 80TB-->40TB
Network: 10Gb/s
Clusters: cluster_01
Shard: 3
Replicates: 2 every shard

# Config1
      <default>
          <max_memory_usage>30000000000</max_memory_usage>
          <load_balancing>random</load_balancing>
      </default>
      <reader>
          <max_memory_usage>30000000000</max_memory_usage>
          <load_balancing>random</load_balancing>
          <readonly>0</readonly>
      </reader>
      <manager>
          <max_memory_usage>3000000000</max_memory_usage>
          <load_balancing>random</load_balancing>
      </manager>
# Config2
      <max_concurrent_queries>300</max_concurrent_queries>
      <max_server_memory_usage>0</max_server_memory_usage>
      <max_thread_pool_size>10000</max_thread_pool_size>
      <max_server_memory_usage_to_ram_ratio>0.9</max_server_memory_usage_to_ram_ratio>
      <total_memory_profiler_step>4194304</total_memory_profiler_step>

# Query
## Local Table:
CREATE TABLE testdb.local_v1
(
    `uid` Int64,
    `hdid` Nullable(String),
    `sex` Nullable(Int32),
    `age` Nullable(Int32),
    `nick` Nullable(String),
    `location` Nullable(String),
    `avatar` Nullable(String),
    `sign` Nullable(String),
    `hometown` Nullable(String),
    `job` Nullable(String),
    `friend_num` Nullable(Int32),
    `fb_friend_num` Nullable(Int32),
    `addr_friend_num` Nullable(Int32),
    `birthday` Nullable(String),
    `sys` Nullable(String),
    `ver` Nullable(String),
    `ip` Nullable(String),
    `nation` Nullable(String),
    `sjp` Nullable(String),
    `sjm` Nullable(String),
    `mbos` Nullable(String),
    `net` Nullable(String),
    `sdkver` Nullable(String),
    `mbl` Nullable(String),
    `ad_channel` Nullable(String),
    `ad_campaign` Nullable(String),
    `ad_group` Nullable(String),
    `reg_date` Nullable(String),
    `last_login_date` Nullable(String),
    `reg_nation_server` Nullable(String),
    `country_code` Nullable(String),
    `lang` Nullable(String),
    `dt` String COMMENT 'date',
    `prdname` String
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{layer}-{shard}/local_v1', '{replica}')
PARTITION BY (toInt32(dt), prdname)
ORDER BY uid
SETTINGS index_granularity = 8192
## Distributed Table
CREATE TABLE testdb.test_all as local_v1
ENGINE = Distributed(cluster_01, testdb, local_v1, intHash32(uid));
## Dataset
Total 644320978 rows
## Select Query
SELECT dt, prdname, count(uid) AS pv, countDistinct(uid) AS uv FROM testdb.test_all WHERE dt ='20210711' GROUP BY dt, prdname
### Test result:
![image](https://user-images.githubusercontent.com/35732071/130572114-6b6edb60-9e5b-49c9-af04-2f00a898f570.png)
It tooks 54s, expected 10s
### Log:
It sames merging blocks to bucket=165 take too much time,
And do system tables merge parts etc.

```
2021.08.23 17:14:05.840279 [ 54336 ] {085f3c26-dabd-496e-a7c3-47b7eb96be19} <Trace> Aggregator: Merging partially aggregated blocks (bucket = 165).
2021.08.23 17:14:34.029297 [ 54336 ] {085f3c26-dabd-496e-a7c3-47b7eb96be19} <Debug> Aggregator: Merged partially aggregated blocks. 1 rows, 46.00 B. in 28.188973108 sec. (0.03547486445031944 rows/sec., 1.63 B/sec.)
2021.08.23 17:14:34.039063 [ 18131 ] {085f3c26-dabd-496e-a7c3-47b7eb96be19} <Information> executeQuery: Read 321968036 rows, 11.43 GiB in 54.176122815 sec., 5942987 rows/sec., 216.03 MiB/sec.
```
### Full log:
[log.txt](https://github.com/ClickHouse/ClickHouse/files/7043152/log.txt)

Is there some suggestions to improve performance?

**Comment by aaawuanjun** [comment]
1、BgSchPool thread occupy all cpu, and QueryPipelineEx thread has no cpu resources?
2、BgSchPool thread influence  QueryPipelineEx thread to mergeBlocks?

**Comment by den-crane** [comment]
`select * from system.settings where changed`

**Comment by aaawuanjun** [comment]
![image](https://user-images.githubusercontent.com/35732071/130712096-3a183760-4877-4f97-931a-0a833f8c52db.png)
only load_balancing and max_memory_usage changed equals 1
@den-crane

**Comment by lingnancfy** [comment]
At high base dimensions, I test the distributed table and the local table. The test environment contains two shards, clickhouse version 21.3.4.25.

In distributed table testing, uniqExact is much slower in the Aggregator::mergeBlocks(BlocksList & blocks, bool final) phase than groupBitmap.
![image](https://user-images.githubusercontent.com/22337511/143025816-81372b6d-57f9-4e3f-87da-1c1448d8f41c.png)

In the query of the local table, the two function are not different.

![image](https://user-images.githubusercontent.com/22337511/143026290-282fc79e-ed76-40ee-9e03-0303ba6a77c8.png)

@aaawuanjun Your test is a distributed table, you can use groupBitmap to improve some query efficiency.

**Comment by aaawuanjun** [comment]
Thanks, I will try groupBitmap implementation, The following is the previous analysis, which was not posted in time

1、There are 18 threads in total, and the remaining threads are completed within 1-2s. 1~2 thread runs very slowly and takes 11s、32s
![image](https://user-images.githubusercontent.com/35732071/143157184-fc50d632-f1a7-4748-958e-eb3f3b93582c.png)

2、to be continue, the time consumption of the operator is mainly in the merge function of AggregateFunctionsUniq (the bottom layer is implemented through HashSet). Thread with long execution time enter merge function taske 7-8s 1 time.
![image](https://user-images.githubusercontent.com/35732071/143158342-a6b7fee7-9e01-4b4c-a74b-a67e7c262257.png)


so，I'm curious about the amount of data processed by each thread and the total amount of data processed by this HashSet?

 Due to work reasons, no further analysis was carried out

**Comment by aaawuanjun** [comment]
In this case, groupBitmap works, it takes ONLY 2s
![image](https://user-images.githubusercontent.com/35732071/143160754-1295f330-6016-4851-a5c4-0f9e2be5cf8b.png)

groupBitmap only support int type, In the actual scene，when we use string type, we can only use uniqExact

**Comment by lingnancfy** [comment]
@aaawuanjun  The execution time of a thread may depend on how much  partially aggregated data is processed in buckets sent from other servers，If more than 1 billion for loops occur, the hashtable merge is very slow. I may understand that there is an error.
