### ISSUE TITLE
TRUNCATE TABLE with ReplicatedMergeTree and S3 storage causes server to hang.

### ISSUE THREAD

**Issue by MyroTk** [ClickHouse/ClickHouse#28094]
**Describe the bug**
I have two ClickHouse nodes with a Replicated Merge Tree table on each. When I drop one and try to truncate the other, the query hangs until the 300s timeout.

**Does it reproduce on recent release?**
ClickHouse server version 21.8.4 revision 54449

**How to reproduce**

* Which ClickHouse server version to use
ClickHouse server version 21.8.4 revision 54449

* Non-default settings, if any
allow_remote_fs_zero_copy_replication =1
* `CREATE TABLE` statements for all tables involved

clickhouse1:
```
CREATE TABLE zero_copy_replication (d UInt64) 
ENGINE = ReplicatedMergeTree('/clickhouse/zero_copy_replication_delete', '1')
ORDER BY d
SETTINGS storage_policy='external'
```
clickhouse2:
```
CREATE TABLE zero_copy_replication (d UInt64) 
ENGINE = ReplicatedMergeTree('/clickhouse/zero_copy_replication_delete', '2')
ORDER BY d
SETTINGS storage_policy='external'
```
'external' storage policy uses s3

* Queries to run that lead to unexpected result
```
clickhouse1 :) INSERT INTO zero_copy_replication VALUES (0)
clickhouse2 :) DROP TABLE zero_copy_replication
clickhouse1 :) TRUNCATE TABLE zero_copy_replication
```

**Error message and/or stacktrace**
Hits the 300s timeout and cancels the query.

**Comment by alexey-milovidov** [comment]
@MyroTk `MergeTree` tables over `S3` storage are not intended for production usages in any kind.

**Comment by ianton-ru** [comment]
Reproduced regardless of S3. `DROP TABLE` removes records in ZooKeeper with delay, and `TRUNCATE TABLE` waits for other replica.
Fixed in https://github.com/ClickHouse/ClickHouse/pull/27931 (ver. 21.10+)

**Comment by alexey-milovidov** [comment]
I'm wondering, why TRUNCATE should wait for other replicas at all.
There is no even a setting like `mutations_sync`, `alter_partitions_sync`.
