### ISSUE TITLE
Code: 70, e.displayText() = DB::Exception: Cannot convert NULL to a non-nullable type

### ISSUE THREAD

**Issue by rakerf** [ClickHouse/ClickHouse#28114]
CREATE MATERIALIZED VIEW IF NOT EXISTS xxx
ON CLUSTER ck
TO yyy
AS
SELECT 
cast(null,'String') AS zzz,
...

Code: 70, e.displayText() = DB::Exception: Cannot convert NULL to a non-nullable type

#28059

**Comment by rakerf** [comment]
[](url)

**Comment by den-crane** [comment]
Please provide more info. I need reproducible example and clickhouse version.

**Comment by rakerf** [comment]
select cast(null,'String') as ccc 

SQL 错误 [70]: ClickHouse exception, code: 70, host: 10.72.0.15, port: 8123; Code: 70, e.displayText() = DB::Exception: Cannot convert NULL to a non-nullable type: While processing CAST(NULL, 'String') AS ccc (version 21.7.1.6968 (official build))

**Comment by den-crane** [comment]
ah, I see now, it should be Nullable(String)

```
SELECT cast(NULL, 'Nullable(String)') AS ccc


┌─ccc──┐
│ ᴺᵁᴸᴸ │
└──────┘
```
