### ISSUE TITLE
Automatic restart when print log: “<Warning> Removing temporary directory .. "

### ISSUE THREAD

**Issue by liubaochuan** [ClickHouse/ClickHouse#28122]
2021.04.10 12:26:41.223092 [ 32034 ] {} default.test_table: Removing temporary directory /home/program/data/clickhouse/data/default/test_table/tmp_mut_65a169db8e6913eff27422c5347536e7_187952_200424_392_1539869/
2021.04.10 14:08:00.547652 [ 41154 ] {} default.test_table: Removing temporary directory /home/program/data/clickhouse/data/default/test_table/tmp_mut_65a169db8e6913eff27422c5347536e7_187952_200424_392_1539869/
2021.04.10 15:49:07.929274 [ 46997 ] {} default.test_table: Removing temporary directory /home/program/data/clickhouse/data/default/test_table/tmp_mut_65a169db8e6913eff27422c5347536e7_187952_200424_392_1539869/
2021.04.10 17:29:11.795369 [ 52442 ] {} default.test_table: Removing temporary directory //home/program/data/clickhouse/data/default/test_table/tmp_mut_65a169db8e6913eff27422c5347536e7_187952_200424_392_1539869/

when the above log will automatically restart.
clickhouse version: 20.8.7.15-2

**Comment by liubaochuan** [comment]
> 2021.08.26 21:42:25.657197 [ 23124 ] {} ocean.cw_facedb_face_index: Removing temporary directory /home/program/data/clickhouse/data/ocean/cw_facedb_face_index/tmp_mut_f588ad9820872b84dfc3fc5d9b68fbb7_80475_90910_370_1539869/
> 2021.08.26 21:44:18.185107 [ 23882 ] {} BaseDaemon: ########################################
> 2021.08.26 21:44:18.185191 [ 23882 ] {} BaseDaemon: (version 21.7.8.58 (official build), build id: 95F91F78B10AC6F0E542A4C4F8D7B8162144DE39) (from thread 23247) (no query) Received signal Segmentation fault (11)
> 2021.08.26 21:44:18.185249 [ 23882 ] {} BaseDaemon: Address: 0x7f02f183fff8 Access: write. Attempted access has violated the permissions assigned to the memory area.
> 2021.08.26 21:44:18.185287 [ 23882 ] {} BaseDaemon: Stack trace: 0x8d2df45
> 2021.08.26 21:44:18.185895 [ 23882 ] {} BaseDaemon: 1. CurrentMemoryTracker::(anonymous namespace)::allocImpl(long, bool) (.llvm.268904552094749462) @ 0x8d2df45 in /usr/lib/debug/.build-id/95/f91f78b10ac6f0e542a4c4f8d7b8162144de39.debug
> 2021.08.26 21:44:18.397096 [ 23882 ] {} BaseDaemon: Checksum of the binary: D7592FD563E371A1433D336C2554BBA8, integrity check passed.
> 2021.08.26 21:44:49.509997 [ 22948 ] {} Application: Child process was terminated by signal 11.
> 2021.08.26 21:46:57.659335 [ 24041 ] {} ocean.cw_facedb_face_index: Removing temporary directory /home/program/data/clickhouse/data/ocean/cw_facedb_face_index/tmp_mut_f588ad9820872b84dfc3fc5d9b68fbb7_80475_90910_370_1539869/
> 2021.08.26 21:48:49.342339 [ 25014 ] {} BaseDaemon: ########################################
> 2021.08.26 21:48:49.342451 [ 25014 ] {} BaseDaemon: (version 21.7.8.58 (official build), build id: 95F91F78B10AC6F0E542A4C4F8D7B8162144DE39) (from thread 24309) (no query) Received signal Segmentation fault (11)
> 2021.08.26 21:48:49.342531 [ 25014 ] {} BaseDaemon: Address: 0x7f977e998ff8 Access: write. Attempted access has violated the permissions assigned to the memory area.
> 2021.08.26 21:48:49.342551 [ 25014 ] {} BaseDaemon: Stack trace: 0x8d2df45
> 2021.08.26 21:48:49.343365 [ 25014 ] {} BaseDaemon: 1. CurrentMemoryTracker::(anonymous namespace)::allocImpl(long, bool) (.llvm.268904552094749462) @ 0x8d2df45 in /usr/lib/debug/.build-id/95/f91f78b10ac6f0e542a4c4f8d7b8162144de39.debug
> 2021.08.26 21:48:49.581437 [ 25014 ] {} BaseDaemon: Checksum of the binary: D7592FD563E371A1433D336C2554BBA8, integrity check passed.
> 2021.08.26 21:49:19.122936 [ 24029 ] {} Application: Child process was terminated by signal 11.
> 
> The data directory remains unchanged。
> Updated version.

**Comment by alexey-milovidov** [comment]
No information about tables provided.
