### ISSUE TITLE
Full name column appears in left join of multiple tables

### ISSUE THREAD

**Issue by peterZhiFate** [ClickHouse/ClickHouse#28121]
When I execute the following sql statement, when I left join two tables, it column names are correct, as shown in picture 1.
![picture1](https://user-images.githubusercontent.com/74392381/130733049-68b1555c-e124-4944-a3e2-b4cc0166ae23.png)

But when I left join the three tables, I can see that the column names are incorrect. As shown in picture two.

![picture2](https://user-images.githubusercontent.com/74392381/130733060-10b4bbad-e306-4248-8573-4455e2f3d249.png)

Is there any solution?

**Comment by e-mars** [comment]
Hi @peterZhiFate .
thank you for submitting the question and issue.
I was able to reproduce and have created the following ticket for our Dev team:
https://github.com/ClickHouse/ClickHouse/issues/34697

As a workaround use and `AS my_column` clause on the first part of the statement.
![Screen Shot 2022-02-17 at 12 48 19 PM](https://user-images.githubusercontent.com/18219420/154559427-517537a9-af39-475e-bd18-548ce082bad1.png)

you can follow the issue link for further updates or if you have further questions.
thanks.
