### ISSUE TITLE
load data to mergetree table, how  remove duplicate data when fail and retry

### ISSUE THREAD

**Issue by jiangjiguang** [ClickHouse/ClickHouse#28127]
Load data from HDFS parquet files to mergetree table, my process is below:
1、CREATE TABLE table_src AS table_standard ENGINE = HDFS('hdfs:xxxxxx.parquet' , Parquet)
2、INSERT INTO table_temp SELECT * FROM table_src
3、ALTER TABLE table_temp MOVE PARTITION 'xxxxxx' TO TABLE table_prd

but, it may fail when loading data from a parquet file, now i will add retry.
As far as i know, the loading data has not transaction mechanism, and part of data will be written to table,  how do I to remove duplicate data ?

**Comment by gingerwizard** [comment]
Hi @jiangjiguang apologies for the delayed response. You have a few options with respect to deduplication:

1. If you are using a variant of the Replicated Merge Tree, identically inserted blocks will be de-duplicated automatically- in this case you can reliably retry INSERTS in the event of failure. Slicing up the inserts is still advised as this de-duplicated will not work across internal merges.
2. Consider using the [Replacing Merge Tree](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/replacingmergetree/ ) - noting the duplicates are performed on the sort key and on merges only. The CollapsingMergeTree and VersionedCollapsingMergeTree build on similar principles but allow more eloborate de-duplication stategies.

**Comment by gingerwizard** [comment]
No further reply. Closing.
