### ISSUE TITLE
How to upgrade from 20.3 to 21.3?

### ISSUE THREAD

**Issue by zhanglistar** [ClickHouse/ClickHouse#28124]
Hi all, we are using clickhouse version 20.3 with 100 machines and several PB data, and we want to upgrade version to 21.3 or the latest stable version, please give us some advice, thanks in advance.

**Comment by alexey-milovidov** [comment]
1. You definitely have a testing environment. Install the new version to testing.
2. Everything is ok in testing &mdash; go ahead with upgrade.
3. Zero downtime upgrade:
&mdash; install new package to all servers;
&mdash; restart ClickHouse in one region;
&mdash; wait when it is started in one region and continue to other regions;</span>
4. Check the metrics of your software and product.
