### ISSUE TITLE
received from localhost:9000.DB:exception:no hosts passed to zookeeper constructor.(bad arguments)

### ISSUE THREAD

**Issue by powerpistn** [ClickHouse/ClickHouse#28134]
I created a clickhouse cluster, the steps are as follows:
1. Created three virtual machines
2. Install zookeeper on three virtual machines to build a zookeeper cluster
3. Install clickhouse on three virtual machines to build a clickhouse cluster

The zookeeper cluster runs successfully, the metrika.xml file of the clickhous cluster is:

> <yandex>
    <remote_servers>
        <clusterName1>
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                    <host>centos-linux-master.shared</host>
                    <port>9000</port>
                </replica>
            </shard>
            <shard>
                <replica>
                    <internal_replication>true</internal_replication>
                    <host>centos-linux-node1.shared</host>
                    <port>9000</port>
                </replica>
            </shard>
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                    <host>centos-linux-node2.shared</host>
                    <port>9000</port>
                </replica>
            </shard>
        </clustersName1>
    </remote_servers>

    <zookeeper-servers>
        <node index="1">
            <host>centos-linux-master.shared</host>
            <port>2181</port>
        </node>
        <node index="2">
            <host>centos-linux-node1.shared</host>
            <port>2181</port>
        </node>
        <node index="3">
            <host>centos-linux-node2.shared</host>
            <port>2181</port>
        </node>
    </zookeeper-servers>
    <macros>
       <shard>01</shard>
        <replica>master</replica>
    </macros>
    <networks>
        <ip>::/0</ip>
    </networks>
    <clickhouse_compression>
        <case>
            <min_part_size>10000000000</min_part_size>
            <min_part_size_ratio>0.01</min_part_size_ratio>
            <method>lz4</method>
        </case>
    </clickhouse_compression>
</yandex>

when i use **select cluster,port  from system.clusters;**
 
![image](https://user-images.githubusercontent.com/43348528/130791898-3f619332-5deb-4f51-89e7-1eff6d3c423b.png)

when i use **create table st_order_mt on cluster  clustersName1(
   id UInt32,
sku_id String,
total_amount Decimal(16,2), create_time Datetime
) engine =ReplicatedMergeTree('/clickhouse/tables/{shard}/st_order_mt','{replica}')
  partition by toYYYYMMDD(create_time)
  primary key (id)
  order by (id,sku_id);**

I encountered the following error

![image](https://user-images.githubusercontent.com/43348528/130792167-db4495b9-df6e-442f-bfa5-a1757c913a3e.png)

How can i solve this problem？

**Comment by tavplubix** [comment]
Replace `zookeeper-servers` with `zookeeper` in config. 
`No hosts passed to ZooKeeper constructor` means that there is `<zookeeper>` section in config, but it does not contain any hosts. Probably you also have empty `<zookeeper>` section somewhere in configuration files.

**Comment by long1208** [comment]
hi ，Can you tell me how to use it? And how about the performance of import?
