### ISSUE TITLE
Add support for relative paths to load external machine learning models.

### ISSUE THREAD

**Issue by GrigoryPervakov** [ClickHouse/ClickHouse#28142]
> You have to provide the following information whenever possible.

Relative paths for ml models works wrong

> A clear and concise description of what works not as it is supposed to.

It's possibly broken here https://github.com/ClickHouse/ClickHouse/commit/cc65a1db972973470c282e0795818af9e0a8c0a9
In [this](https://github.com/ClickHouse/ClickHouse/blob/master/src/Interpreters/ExternalLoaderXMLConfigRepository.cpp#L39) string there is always returned default value, so if the config path is overridden we got the wrong path for the models.

**Does it reproduce on recent release?**

Yes

**How to reproduce**

Use clickhouse version 21.5>
Set a relative path to ml models in config.xml
User --config arg on server startup
Place ml models to the target directory
`SELECT COUNT(*) FROM system.models` remains zero

**Expected behavior**
As in exteranal dictionary loader

**Comment by kitaisreal** [comment]
Seems there is no bug in config we search dictionaries and models relative to clickhouse-binary not config. For example.
Folder structure:
clickhouse
dictionaries/simple_dictionary.xml
ml_models/simple_model.xml
test_config_dir/config.xml

In config.xml:
```xml
<dictionaries_config>./dictionaries/*_dictionary.xml</dictionaries_config>
<models_config>./ml_models/*_model.xml</models_config>
```
Check queries:
```
SELECT COUNT(*) FROM system.dictionaries;
┌─count()─┐
│       1 │
└─────────┘
```
```
SELECT COUNT(*) FROM system.models;
┌─count()─┐
│       1 │
└─────────┘
```

**Comment by GrigoryPervakov** [comment]
Your example is correct, because code in link always returns clickhouse-binary path.
For example:
Folder structure:
clickhouse - binary can be anywhere
/etc/clickhouse-server/dict.d/simple_dictionary.xml
/etc/clickhouse-server/model.d/simple_model.xml
/etc/clickhouse-server/config.xml
In config.xml:
`<dictionaries_config>./dict.d/*_dictionary.xml</dictionaries_config>
<models_config>./model.d/*_model.xml</models_config>`

run server with `clickhouse-sever --config /etc/clickhouse-server/config.xml` and get 1 dictionary and 0 models.
But before linked pr clickhouse mages to find this model.
