### ISSUE TITLE
Is there any globalLock on jdbcfunciton?

### ISSUE THREAD

**Issue by lichenglin** [ClickHouse/ClickHouse#28163]
> Make sure to check documentation https://clickhouse.yandex/docs/en/ first. If the question is concise and probably has a short answer, asking it in Telegram chat https://telegram.me/clickhouse_en is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

> If you still prefer GitHub issues, remove all this text and ask your question here.

I hava exucte a very long sql such as "insert into table select * from jdbc(.....)" where jdbc(....) has about 1 blilion rows.
It takes a very long time to finish the sql.

But I found that when the sql excuting , the other sql that use jdbc fuction and jdbcTable will block until the sql above has been done.

Every jdbcfunciton must be excueted one by one? sync??

I have change the default timeout to a very long time. inlude the config in server.json 、vertx.json、datasource.json.

The work.num of bridge use the default value

If I missed something??

Thank U for your Reply

the version of of jdbc-bridge and ck are both latest.

and the config of brige seems ok.

![image](https://user-images.githubusercontent.com/8294900/130904917-30c97cb9-f50e-4177-b9da-9f91876a7215.png)

**Comment by zhicwu** [comment]
This can be closed.

It's an issue with JDBC Bridge(introduced in 2.0.3 and fixed in 2.0.4). See ClickHouse/clickhouse-jdbc-bridge#113.
