### ISSUE TITLE
Extend range of Datetime64 and Date32

### ISSUE THREAD

**Issue by liuneng1994** [ClickHouse/ClickHouse#28216]
Not long ago, I submitted a pull request for Date32（https://github.com/ClickHouse/ClickHouse/pull/25774）, in order to solve the problem of too small date range, but for some banking systems, there are still data dates before 1925. I want to extend the existing date range, for example to 1900.

I want to know if this approach can be accepted by the community.

**Comment by UnamedRus** [comment]
Reason why range was limited by 1925, it's because implementing calendar further would  complicate LUT a lot.

https://github.com/ClickHouse/ClickHouse/pull/9404

```
 The Year 1925 is a starting point because most of the timezones switched to saner (mostly 15-minutes based) offsets somewhere during 1924 or before. And that significantly simplifies implementation.
 ```

**Comment by ajvol** [comment]
unfortunately, some corporate databases use 1900-01-01 as the "default" datetime value. It is not possible to transfer such datasets to CH unchanged

**Comment by UnamedRus** [comment]
And you do care about difference between 1900-01-01 and 1925-01-01?

```
SELECT toDate32('1900-01-01')

Query id: 8277b900-19fb-426c-a60b-bdc3f4d1c200

┌─toDate32('1900-01-01')─┐
│             1925-01-01 │
└────────────────────────┘
```

**Comment by Firaenix** [comment]
I have datasets for European company formations where the incorporation dates can go back to before 1800, how should I handle this if the DateTime64 only goes back to 1900?

**Comment by Slach** [comment]
@Firaenix split to separate fields
like `year UInt16, month UInt8, day UInt8, hour UInt8, minute UInt8, second UInt8, timezone LowCardinality(String)`
