### ISSUE TITLE
Return the number of inserted rows in HTTP API responses

### ISSUE THREAD

**Issue by 907th** [ClickHouse/ClickHouse#2825]
After inserting data into ClickHouse table using HTTP API the response body is empty and response headers do not contain any useful information too. It would be nice to get the number of inserted rows in the server response. What do you think?

**Comment by alexey-milovidov** [comment]
Care should be taken, because data in response body is considered as full featured resultset with its own data structure, tunable data format, etc.

Possible solutions:
- add it as a separate HTTP header;
- add it in the same way as `send_progress_in_http_headers`;

**Comment by filimonov** [comment]
Related #208

**Comment by alexey-milovidov** [comment]
See https://github.com/ClickHouse/ClickHouse/pull/5116
