### ISSUE TITLE
FixedString(16) data type problem when using MySQL table engine with MariaDB

### ISSUE THREAD

**Issue by edvnass** [ClickHouse/ClickHouse#28258]
MySQL table engine FixedString(16) type has a problem when using MariaDB as remote source and does not return rows when querying with FixedString(16) filter in the where clause. 

> A clear and concise description of what works not as it is supposed to.

- MariaDB original table has index on id field, id type is binary(16) which is used for storing uuid

- MariaDB is used for binding to clickhouse using MySQL table engine:

  CREATE TABLE tmpdata.temp_table
  (
      `id` FixedString(16)
  )
  ENGINE = MySQL('.....')

- select * from  tmpdata.temp_table where id = toFixedString(UUIDNumToString(....), 16) -> 0 rows

- select * from  tmpdata.temp_table where toFixedString(id) = toFixedString(UUIDNumToString(....), 16) -> returns correct data, however MariaDB index on id field is not used due to conversion of type in the where clause toFixedString(id) and query becomes very slow

**Expected behavior**

- Clickhouse query "select * from  tmpdata.temp_table where id = toFixedString(UUIDNumToString(....), 16) " should pass binary filter value to remote MariaDB table which would use MariaDB index which exists on the id field and return rows quickly

**Additional context**

It seems like the conflict between Binary and FixedString type was solved for MySQL table engine when remote database is MySQL but not for MariaDB

**Comment by vitlibar** [comment]
`UUIDNumToString()` returns a 36-bytes string like `3c6f395f-c759-450c-8f18-0de417be064f`. It's definitely wrong to cast it into `FixedString(16)`. Maybe it's better to use `UUIDStringToNum()` instead, for example

```
select * from tmpdata.temp_table where id = UUIDStringToNum('3c6f395f-c759-450c-8f18-0de417be064f')
```

**Comment by vitlibar** [comment]
It seems this issue is similar to https://github.com/ClickHouse/ClickHouse/issues/28576.

**Comment by edvnass** [comment]
yes indeed very similar

also similar to this https://github.com/ClickHouse/ClickHouse/issues/6556

but it was fixed in new version release a while ago... i wonder if it applies just for MariaDB remote tables or whole MySQL table engine in clickhouse

**Comment by edvnass** [comment]
Maybe will help with the issue - we discovered that there is a conflict between UTF8 and ISO-8859-1 encodings when inserting FixedString(16) data type (aka binary) from MariaDB to clickhouse
