### ISSUE TITLE
Implicit conversion  from integer to String when parse JSON format

### ISSUE THREAD

**Issue by wangqinghuan** [ClickHouse/ClickHouse#28308]
1. CREATE a table contains a capColor field which type is String.
```
CTEATE table test (
   CapColor String
)
...
```

2. insert  a JSON contains a capColor field which value is not quoted.

```
INSERT INTO test FORMAT JSONStringsEachRow {"CapColor":1};
```

3. An exception throws 
```
ParsingException: Cannot parse JSON string: expected opening quote: (while reading the value of key CapColor): While executing ParallelParsingBlockInputFormat: (at row 1) . (CANNOT_PARSE_QUOTED_STRING) (version 21.10.1.1)
```
Expected:
The table can parse  {"CapColor":1},  although value is not quoted. 
Could we provide implicit conversion  from integer to String?

**Comment by amosbird** [comment]
You can instead use `INSERT INTO test SELECT * from input('CapColor int') FORMAT JSONStringsEachRow ...`

**Comment by den-crane** [comment]
Not related to JSON. The same behavior with any format. No implicit conversions.
