### ISSUE TITLE
Why Inode is getting full frequently? 

### ISSUE THREAD

**Issue by gopiather** [ClickHouse/ClickHouse#28323]
Inode is gettiing full frequently, because of it memory is also getting spiked up?
Is there a way to clear off inode? 
And if there is any explanation of inode is getting full?

Version - 21.7.7.47

**Comment by filimonov** [comment]
Most probably you use bad partitioning schema.

**Comment by gopiather** [comment]
@filimonov I have used partition schema as toYYYYMMDD(ts) and a string column (e.g username) thats it.

Partition BY (toYYYYMMDD(ts), user_name)

**Comment by filimonov** [comment]
> @filimonov I have used partition schema as toYYYYMMDD(ts) and a string column (e.g username) thats it.
> 
> Partition BY (toYYYYMMDD(ts), user_name)
> Any changes required on this partition?

Yes.

Change it to `Partition BY toYYYYMMDD(ts)` or to `Partition BY toYYYYMM(ts)`
