### ISSUE TITLE
RangeHashedDictionary does not support integer values outside of Int64

### ISSUE THREAD

**Issue by pengliaoye** [ClickHouse/ClickHouse#28322]
> You have to provide the following information whenever possible.

```
CREATE DICTIONARY analytics.all_ipv6s_lower (
    id UInt64,
    start_addr UInt64,
    end_addr UInt64,
    subnet_mask String,
    isp String,
    province String
)
PRIMARY KEY id
SOURCE(FILE(path '/var/lib/clickhouse/user_files/all_ipv6s_lower.csv' format 'CSV'))
LIFETIME(0)
LAYOUT(RANGE_HASHED())
RANGE(MIN start_addr MAX end_addr)
```

all_ipv6s_lower.csv。content below

```
1,0,18446744073709551615,ffff:ffff::,value1,value2,value3
```

the we do.
```
select * from analytics.all_ipv6s_lower
```
only `id`,`start_addr`,`end_addr` have values。  other column no value.

> A clear and concise description of what works not as it is supposed to.

version
```
ClickHouse client version 21.8.4.51 (official build).
```

**How to reproduce**

if we change csv content to bellow
```
1,0,1,ffff:ffff::,value1,value2,value3
```

change UInt64 max value `18446744073709551615`  to  `1`.

this will work. and all column values returned.

**Expected behavior**

all_ipv6s_lower.csv :
```
1,0,18446744073709551615,ffff:ffff::,value1,value2,value3
```
all_ipv6s_lower.csv:
```
1,0,1,ffff:ffff::,value1,value2,value3
```
both work

**Additional context**

**Comment by pengliaoye** [comment]
this not work:
1,0,18446744073709551615,ffff:ffff::,value1,value2
this work:
1,0,1,ffff:ffff::,value1,value2

only 6 columns value

**Comment by kitaisreal** [comment]
Actually it is documentation issue. RangeHashedDictionary stores ranges in Int64. Updated #29038.

**Comment by pengliaoye** [comment]
can support UInt64?

**Comment by kitaisreal** [comment]
@pengliaoye currently there is no plans to support it values that does not fit Int64 type for RangeHashedDictionary.

**Comment by pengliaoye** [comment]
province: beiging
begin: 240c:0:0:0:0:0:0:0  
end: 240c:000f:ffff:ffff:ffff:ffff:ffff:ffff

ipv6: 240c:0:0:0:0:0:0:1

we want using ipv6, check if in range begin and end. then get the province.   how to use ip_trie layout.   currently the ip_trie only support cidr.  any suggestion?

**Comment by kitaisreal** [comment]
@pengliaoye please for IPTrie create separate issue and I will investigate.
