### ISSUE TITLE
How to watch the progress when I receive data from MySQL using MaterializeMySQL

### ISSUE THREAD

**Issue by Fire-DB** [ClickHouse/ClickHouse#28329]
Clickhouse can synchronize data from MySQL using MaterializeMySQL. But i don't konw how much data have been synchronized currently. So how to make sure that the data in CH is consistent with that in mysql ?

**Comment by chinayangze** [comment]
I also want to know

**Comment by stigsb** [comment]
Currently, the only way is to do this manually:

1. Count the number of rows in MySQL, either by doing `ANALYZE TABLE ...` and querying `INFORMATION_SCHEMA.TABLES`, or by `SELECT COUNT(*)` in all the tables. If you are using the `materialized_mysql_tables_list` setting, adjust accordingly.
2. While MaterializedMySQL is in full sync, you can monitor the progress by querying `system.parts` in ClickHouse: `SELECT sum(rows) FROM system.parts WHERE database = 'yourdb' AND active`.

**Comment by stigsb** [comment]
@filimonov I believe you can close this issue
