### ISSUE TITLE
Predefined connections to external data sources

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#28367]
**Use case**

Allow to connect to external sources without exposing credentials (user/password), and/or remote address.

**Describe the solution you'd like**

Named collections can be predefined in configuration file:

```
<named_collections>
    <my_conn_name>
        <user>emelya</user>
        <password>pikefish</password>
        <host>mysql.example.com</host>
        <port>3306</port>
        <database>stove</database>
    </my_conn_name>
    ...
</named_collections>
```

Then the names can be referenced in table functions, table engines, database engines and dictionaries in the following form:

```
SELECT ... FROM mysql(my_conn_name, table = 'northwind');
CREATE TABLE ... ENGINE = PostgreSQL(my_conn_name, table = 'northwind');
CREATE DICTIONARY ... SOURCE(MYSQL(NAME my_conn_name TABLE 'northwind'));
CREATE DATABASE ... ENGINE = PostgreSQL(my_conn_name, table = 'northwind');
```

Named collections can have all parameters defined (e.g. both database and table name). Then only the name is required as an argument:

```
SELECT ... FROM mysql(my_conn_name)
```

Or it can have some omitted parameters (e.g. user, password, host and port are present, but database and table name are not).
Then the remaining parameters can be specified in form of `key = 'value'` pairs:

```
SELECT ... FROM mysql(my_conn_name, database = 'stove', table = 'northwind')
```

These key-value parameters can also override parameters from configuration.

Named collections are not bounded to specific table or database engine. They are just collections of key-value parameters in free form. It is the responsibility for every table / database / dictionary engine (factory method) to initialize itself from provided collection.

We name it "named collections" instead of "named connections", because there is a chance it will be used to configure behaviour of some unrelated functions.

The expression with named collections will be disambiguated by providing first argument (collection name) in form of identifier instead of string literal.
Example:

```
SELECT ... FROM mysql(my_conn_name, table = 'northwind'); -- using named collection
SELECT ... FROM mysql('host:port', 'stove', 'northwind'); -- not using named collection
```

The configuration of named collections should update on config reload. But already established connections will remain.

**Additional context**

#3311
#23424

**Out of scope**

The host name, port or user name can be exposed in exception messages and logs.

**Comment by alexey-milovidov** [comment]
Feature request:
- also add it to `url`, `s3` table functions and `URL`, `S3` table engines;
- allow to specify custom HTTP headers in config.

Example:
```
<named_collections>
    <my_url>
        <url>https://example.com/data.tsv</url>
        <headers>
            <header>
                <name>X-Fancy-Authorization</name>
                <value>please...please...please</value>
            </header>
            ...
        </headers>
    </my_url>
```

**Comment by xqliang** [comment]
> The host name, port or user name can be exposed in exception messages and logs.

Perhaps [query-masking-rules](https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings/#query-masking-rules) can be used to solve this problem.
