### ISSUE TITLE
date_trunc with 'month' as first parameter returns Date instead of DateTime

### ISSUE THREAD

**Issue by bgrgndzz** [ClickHouse/ClickHouse#28381]
Reading the related issue, I understand that ClickHouse's `date_trunc()` was modelled after Postgres's `DATE_TRUNC()`. However, while Postgres returns `DateTime` for every unit, ClickHouse returns `Date` for any unit larger than `day`. The documentation doesn't include this behavior, but says that the only return type is `DateTime`

I pass the result of `date_trunc()` into `toUnixTimestamp()` so it's essential that the function returns `DateTime` for every unit.

**Comment by halilduygulu** [comment]
I found out about this while trying to make a `order by with fill from datetime to datetime interval 1 day`. 
Basically when there is date instead of datetime passed in from start, it just goes nuts and range starts from `1970-01-01 05:16:33` and I got thousands of rows back instead of 7 day range.
