### ISSUE TITLE
Altering column with changing type on distributed table doesn't work as expected

### ISSUE THREAD

**Issue by renatko** [ClickHouse/ClickHouse#2838]
I have altered a column on a target (MergeTree) and Distributed tables from UInt32 to UInt64:
```
ALTER TABLE default.table MODIFY COLUMN altered_column UInt64 DEFAULT 0;
ALTER TABLE default.table_distributed MODIFY COLUMN altered_column UInt64 DEFAULT 0;
```

It affected on existing data in the target table properly and on new inserted data into the distributed but not on a data waiting to be sent into shards.

As result I have errors like:
```
<Error> table_distributed.Distributed.DirectoryMonitor: Code: 53, e.displayText() = DB::Exception: Received from 10.128.0.5:9000. DB::Exception: Type mismatch for column altered_column. Column has type UInt64, got type UInt32: (when looking at destination table default.table). Stack trace:
```

To recovery we had to remove some `*.bin` from the distributed's directory

What is the proper way to do such alters? Can it be fixed on CH side?

Version: 1.1.54343

**Comment by alexey-milovidov** [comment]
The best way is to enable synchronous inserts into Distributed table
by setting `insert_distributed_sync` to 1.

The setting is located at `users.xml` file and could be tuned on per user basis.

Probably we will eventually made this behaviour as default.

**Comment by alexey-milovidov** [comment]
It can be solved even in async mode, but it is little bit more difficult.

Possible implementation:
- add a settings 'native_insert_adapt_block_structure' with default 0;
- RemoteBlockOutputStream should set it to 1;
- when this setting is 1, `InterpreterInsertQuery` should apply the same transform as `ConvertingBlockInputStream` (but to output stream).

**Comment by alexey-milovidov** [comment]
The issue is fixed and solved.
