### ISSUE TITLE
How to build ClickHouse with mysql support?

### ISSUE THREAD

**Issue by htochko** [ClickHouse/ClickHouse#28405]
Hi, I made a build for Apple Silicon  by manual https://clickhouse.tech/docs/en/development/build-osx/
but now it refuses to read mysql dictionary. 
"Dictionary source of type `mysql` is disabled because ClickHouse was built without mysql support"
Could you navigate me to any guide on make build with support?

**Comment by UnamedRus** [comment]
Related 

https://github.com/ClickHouse/ClickHouse/issues/21415
https://github.com/ClickHouse/ClickHouse/issues/21191

**Comment by alexey-milovidov** [comment]
We have implemented official builds for Mac OS X Apple Silicon, install as
```
curl https://clickhouse.com/ | sh
```
