### ISSUE TITLE
CREATE TABLE ... ENGINE=MaterializedPostgreSQL inconsistent behavior with CREATE DATABASE ... ENGINE=MaterializedPostgreSQL

### ISSUE THREAD

**Issue by Slach** [ClickHouse/ClickHouse#28423]
**Describe what's wrong**
When we can try to execute `CREATE DATABASE ... ENGINE=MaterializedPostgreSQL(...)` with wrong connection credentials or when PostgreSQL server is not available, we get the error and the database doesn't create

But when we can try to execute `CREATE TABLE ... ENGINE=MaterializedPostgreSQL(...)`, with wrong connection credentials or when PostgreSQL server is not available, we get the same error, but the table creates

> A clear and concise description of what works not as it is supposed to.

**Does it reproduce on recent release?**
yes

**How to reproduce**

* Which ClickHouse server version to use
21.8-LTS+

* Queries to run that lead to unexpected result
```
CREATE TABLE default.postgresql_replica
(
    `key` UInt64,
    `value` UInt64
)
ENGINE = MaterializedPostgreSQL('postgres1:5432', 'postgres_database', 'postgresql_replica', 'postgres_user', 'postgres_password')
PRIMARY KEY key
ORDER BY key;
```
Returns error

Code: 1001. DB::Exception: Received from localhost:9000. DB::Exception: pqxx::broken_connection: could not translate host name "postgres1" to address: Name or service not known

but after it
```
 SHOW TABLES;

┌─name───────────────┐
│ postgresql_replica │
└────────────────────┘

SELECT * FROM postgresql_replica;
Code: 60. DB::Exception: Received from localhost:9000. DB::Exception: Table default.`d3eb97fd-5a2a-432d-93eb-97fd5a2a032d_nested` doesn't exist.
```

```
CREATE DATABASE postgresql_replicated ENGINE = MaterializedPostgreSQL('postgres1:5432', 'postgres_database', 'postgres_user', 'postgres_password');
```
returns
Code: 1001. DB::Exception: Received from localhost:9000. DB::Exception: pqxx::broken_connection: could not translate host name "postgres1" to address: Name or service not known

but after it
```
SHOW DATABASES;

┌─name────┐
│ default │
│ system  │
└─────────┘
```

**Expected behavior**
Table with wrong credentials doesn't create after return errors

@kssenii could you fix it and port to 21.8?

**Comment by kssenii** [comment]
@kssenii could you fix it and port to 21.8?

Ok.
