### ISSUE TITLE
Aggregate "if" functions broken between 21.8 and 21.4 shards

### ISSUE THREAD

**Issue by genzgd** [ClickHouse/ClickHouse#28429]
We try to do rolling ClickHouse upgrades of our clusters, but we are having an issue upgrading from 21.4 to 21.8.  Distributed queries containing aggregate "if" functions fail when run from a 21.4 host to a 21.8 shard with an 'in' clause.  We get exceptions like this:

`Not found column uniqMergeIf(chi_count, and(or(in(crc, tuple(11, 12, 13, 14, 15, 16, 17, 20, 21, 22)), greaterOrEquals(pssc, 500)), notEquals(pssc, 404))) in block. There are only columns: asset_id, svc, uniqMerge(chi_count), uniqMergeIf(chi_count, and(or(in(crc, (11, 12, 13, 14, 15, 16, 17, 20, 21, 22)), greaterOrEquals(pssc, 500)), notEquals(pssc, 404))):`

and this:

`Not found column sumIf(event_count, in(cache_result, tuple(3, 5))) in block. There are only columns: datetime, svc, sumIf(event_count, in(cache_result, (3, 5))), sum(event_count), sum(ttms_gt_1200), sum(served_bytes)`

Is there an easy workaround for the tuple change while we upgrade?

**Comment by den-crane** [comment]
set `legacy_column_name_of_tuple_literal=1` during upgrade ?

https://github.com/ClickHouse/ClickHouse/blob/master/CHANGELOG.md#clickhouse-release-v217-2021-07-09

Backward Incompatible Change

    Improved performance of queries with explicitly defined large sets. Added compatibility setting legacy_column_name_of_tuple_literal. It makes sense to set it to true, while doing rolling update of cluster from version lower than 21.7 to any higher version. Otherwise distributed queries with explicitly defined sets at IN clause may fail during update.

**Comment by genzgd** [comment]
Ah, I missed that, thanks!
