### ISSUE TITLE
Kafka engine delimiter

### ISSUE THREAD

**Issue by liumengkai** [ClickHouse/ClickHouse#28436]
Hi
I have a problem about my Clickhouse，my data in kafka is split by a string '\u0001' , how to get data in kafka split by a string:'\u0001'

format_csv_delimiter argument is not good for me :

CREATE TABLE queue (
    `id` Int32,
    `name` String
  ) ENGINE = Kafka SETTINGS kafka_broker_list = '172.20.35.206:9092,172.20.39.83:9092',
                            kafka_topic_list = 'topic_test',
                            kafka_group_name = 'lmk_test',
                            kafka_format = 'CSV', 
                            format_csv_delimiter = '\u0001',
                            kafka_num_consumers = 1,
                            kafka_skip_broken_messages = 100;
![image](https://user-images.githubusercontent.com/31892927/131629597-bdc7811a-a679-401e-9dc0-f3b3b43885f9.png)
use above I will get :'A setting's value string has to be an exactly one character long.'

Need some help 
Thx!

**Comment by filimonov** [comment]
We don't support multicharacter separators. 

If you need single-char 0x01 separator - use 
```
format_csv_delimiter='\x01'
```

**Comment by liumengkai** [comment]
Thank you for your replay
After I read the #12744，I change my create table sql to this:

CREATE TABLE queue (
    `id` Int32,
    `name` String
  ) ENGINE = Kafka SETTINGS kafka_broker_list = '172.20.35.206:9092,172.20.39.83:9092',
                            kafka_topic_list = 'topic_test',
                            kafka_group_name = 'lmk_test',
                            kafka_format = 'CustomSeparated', 
                            format_custom_field_delimiter = '\u0001', 
                            kafka_num_consumers = 1,
                            kafka_skip_broken_messages = 100;
it works！
but I got another problem:after I send some message like '2\u0001lmk' to my topic,and I can successfully consumer the message.
but my clickhouse can't parse the message ,and there's an error message in my log like this:
![image](https://user-images.githubusercontent.com/31892927/131643391-9c07c373-03c0-49b3-bc6e-18c77941fb60.png)
don't know where is wrong,could you give me some advice?
Thx a lot!

**Comment by filimonov** [comment]
Can you check / dump the contents of the message in topic topic_test, partition 0, offset 22?

It look like that message is just empty.

**Comment by filimonov** [comment]
BTW: the warning there is excessive (it's not the situation requiring user actions, it was fixes some time ago to TRACE level).

**Comment by liumengkai** [comment]
Hi @filimonov 
I use a kafka-console-producer to produce message,after I send a message I will check the error_log

the message in topic topic_test, partition 0, offset 22 is '2\u0001lmk'

I cancel the argument 'kafka_skip_broken_messages' then I got error message like this:

![image](https://user-images.githubusercontent.com/31892927/131771547-75dcf328-9c85-4fec-923f-d88fabd0abc4.png)

event I add a '\n' at the end of the message,it still has this error...
can't fingurt out what's wrong,can you give me some advice?
thx a lot!

**Comment by wuyue92tree** [comment]
> Hi @filimonov I use a kafka-console-producer to produce message,after I send a message I will check the error_log
> 
> the message in topic topic_test, partition 0, offset 22 is '2\u0001lmk'
> 
> I cancel the argument 'kafka_skip_broken_messages' then I got error message like this:
> 
> ![image](https://user-images.githubusercontent.com/31892927/131771547-75dcf328-9c85-4fec-923f-d88fabd0abc4.png)
> 
> event I add a '\n' at the end of the message,it still has this error... can't fingurt out what's wrong,can you give me some advice? thx a lot!

So any solution for this ? I got this too.

**Comment by wuyue92tree** [comment]
finally, this work for me;  my kafka data split by `\u0001`
```
...
ENGINE = Kafka() 
    SETTINGS kafka_broker_list = 'kafka:9092',
    kafka_topic_list = 'haproxy_log',
    kafka_group_name = 'haproxy_log_clickhouse',
    format_csv_delimiter='\x01',
    kafka_format = 'CSV',
    kafka_num_consumers = 1,
    kafka_skip_broken_messages = 100;
```
