### ISSUE TITLE
Entry index out of range in StringDictionaryColumn (version 21.6.5.37 (official build))

### ISSUE THREAD

**Issue by maqiuyu** [ClickHouse/ClickHouse#28439]
Hi , I am facing the error when I insert orc data to clickhouse,  there is no stringDictionary column in the orc data, how can I resolve this? 

error "Entry index out of range in StringDictionaryColumn (version 21.6.5.37 (official build))"

Thanks

**Comment by filimonov** [comment]
Can you provide the example orc file  and table schema you inserting to which can help to reproduce that problem? Can you show full stacktrace of the error? (run `clickhouse-client --stacktrace` or just look for it in `/var/log/clickhouse-server/clickhouse-server.err.log`)

**Comment by maqiuyu** [comment]
I am sorry, I can't provide that you mentioned because there are private data in that, do you know any possible reasons?

**Comment by qoega** [comment]
You can try to minimize an example and reproduce with artificial data.
