### ISSUE TITLE
hdfs engine. how to split hdfs file? and how to set the parallelism in cluster-level?

### ISSUE THREAD

**Issue by gj-zhang** [ClickHouse/ClickHouse#28448]
```sql
create table test_hdfs_table on cluster datacenter
(
    `product_name`        String,
    `createdate`          DateTime64(3)
)
    engine = HDFS('hdfs://ns/test/test_hdfs_table/*', 'CSV');

create table test_hfds_mergetree_table on cluster datacenter
(
    `product_name`        String,
    `createdate`          DateTime64(3)
)
    ENGINE = ReplicatedMergeTree('/clickhouse/tables/test/test/test_hfds_mergetree_table/{shard}', '{replica}')
        PARTITION BY toYYYYMM(createdate)
        ORDER BY (product_name)

create table test_hfds_distributed_table on cluster datacenter
as test_hfds_mergetree_table
engine = Distributed(xx, xx, xx,xx);
```

is data synchronized using the following sql?
```
insert into test_hfds_mergetree_table select * from test_hdfs_table
```
and i have three questions.
1. How does each node know which part of the data it is responsible for synchronizing?
2. Does parallel reading or writing on a document refer to parallelism on a single node? 
3. How to achieve cluster-level parallelism?
please help.

Now I use Spark to synchronize data from HDFS to ClickHouse. But there are many problems, such as synchronization speed, clickhouse connection, data consistency, etc. So I want to try HDFS engine table, please help to check this problem

I have one more question need help.
We have daily synchronization scenarios.  tables on clickHouse and tables pre-aggregated by materialized views need to be emptied or dropped . How can we quickly implement data import in these scenarios? Is there a way to produce ClickHouse files directly?

I'm going crazy with hive synchronization to clickhouse and asking for help

**Comment by zhanglistar** [comment]
Just read the code.

**Comment by alexey-milovidov** [comment]
We don't support HDFS.
