### ISSUE TITLE
how to solve g++ 

### ISSUE THREAD

**Issue by sherrychenzhang** [ClickHouse/ClickHouse#28494]
cmake ..
CMake Error at cmake/tools.cmake:13 (message):
  GCC version must be at least 10.  For example, if GCC 10 is available under
  gcc-10, g++-10 names, do the following: export CC=gcc-10 CXX=g++-10; rm -rf
  CMakeCache.txt CMakeFiles; and re run cmake or ./release.
Call Stack (most recent call first):
  CMakeLists.txt:46 (include)

**Comment by sherrychenzhang** [comment]
my gcc version is 9.3.0

**Comment by tavplubix** [comment]
You have to install gcc of version 10 or remove version check from cmake and solve all build issues by yourself.
