### ISSUE TITLE
a function like translate function of oracle

### ISSUE THREAD

**Issue by l1t1** [ClickHouse/ClickHouse#28520]
https://docs.oracle.com/cd/B19306_01/server.102/b14200/functions196.htm

eg.

SELECT TRANSLATE('SQL*Plus User''s Guide', ' */''', '___') ;
returns
SQL_Plus_Users_Guide  

the characters arguments maybe utf8, so

TRANSLATE('哈哈(吗)', ' ()', '【】)
returns
哈哈【吗】

my ugly sql:
SELECT arrayStringConcat(
arrayMap(x-> case when x in ['(',')'] then ['【','】'][indexOf(['(',')'],x)] else x end, splitByRegexp('','哈哈(吗)')) 
)
as res;

**Comment by filimonov** [comment]
that reminds me perl tr operator 
https://perldoc.perl.org/perlop#tr/SEARCHLIST/REPLACEMENTLIST/cdsr
https://www.geeksforgeeks.org/perl-tr-operator/
