### ISSUE TITLE
RFC: S3 as 'tape device'

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#28527]
I want to MOVE OUT old data/partitions, or WHOLE table to s3, preserving normal folder structure.

Losing the possibility to do any kind of modifications on that data is 100% ok for me. It is 'data at rest. 

#### Usecase 1: backup 'as is'.

Monthly partitioning. At the end of the month I just do 2 commands:  

```sql
OPTIMIZE TABLE foo PARTITION ID '202103';  
ALTER TABLE foo COPY PARTITION ID '202103' TO S3 's3://aws/bucket/mytable';
```

Later I can `ATTACH` that 'offline' table as a whole or some offline partitions

```sql
ATTACH OFFLINE TABLE foo_backup FROM S3 's3://aws/bucket/mytable';  
-- now i can do whatever select on my backup, but no inserts, renames / merges etc.  
  
ALTER TABLE foo ATTACH PARTITION ID '202103' FROM foo_backup;  
-- recovery backup of some partition

-- AND / OR   
ALTER TABLE foo COPY PARTITION ID '202103' FROM S3 's3://aws/bucket/mytable';

-- AND / OR  
-- manually copy the data from s3 bucket to my disk, using fuse or aws commands, distribute it as I want between nodes, etc. 
```

#### Usecase 2: 'Very cold' \(normally detached\) storage 

After 12 months I do   
```sql
ALTER TABLE foo COPY PARTITION ID '202003' TO S3 's3://aws/bucket/mytable'  
ALTER TABLE foo DROP PARTITION ID '202003' ;
```
If needed i can attach it back to a side table   
```sql
ATTACH OFFLINE  TABLE foo_backup FROM S3 's3://aws/bucket/mytable'  
```
OR attach it temporary to the main table  
```sql
ALTER TABLE foo ATTACH OFFLINE PARTITION '202003' FROM S3 's3://aws/bucket/mytable'
```

#### Usecase 3. Share dataset and other data.
```sql
ALTER TABLE nytaxi COPY TO S3 's3://aws/bucket/mytable';  
DROP TABLE nytaxi; 

ATTACH OFFLINE TABLE foo_backup FROM S3 's3://aws/bucket/mytable'
```

do any kind of selects. inserts/merges etc are not possible. 

Copy it to the local filesystem if needed using fuse / aws-cli.

#### Usecase 4. Multiple computing nodes doing queries from the same r/o dataset

same as  above

**Comment by alexey-milovidov** [comment]
We are slowly moving towards this feature.
Now you can look at the experiments with static externally attached MergeTree tables: #28603.

**Comment by filimonov** [comment]
1. r/o disks
2. parameters for tables ? like merge tree settings -  creating the disk on the fly
3. option to use fixed disk for partition, or attach it from there
4. change the disk for partition explicitly 
5. disk over s3 with simple folder structure ('as is')

**Comment by UnamedRus** [comment]
6. Ability to land some of partitions from external disk to local disk (without changing remote layout, strictly ro access) and without multiplying it in query result. 
7. Easy sharding for this s3 disk between multiple clickhouse servers? (manually or automatically) so different shards will pick different parts. (cityHash64(part_name) % 8 = 1 and etc)

**Comment by alexey-milovidov** [comment]
@UnamedRus 7 is https://github.com/ClickHouse/ClickHouse/issues/26748 - exactly for this purpose.

**Comment by UnamedRus** [comment]
@alexey-milovidov 

Yes, i thought about it, but main use case a bit more complex, so using just replicas (what about regular MergeTree tables?) not sufficient for this as it seems to me.

General requirements:

1. Read only access to the remote storage.
2. Efficient scanning in query time (eg use seek in files, so https://github.com/ClickHouse/ClickHouse/pull/25251 doesn't have this AFAIK)
3. Move some parts from remote storage to local disk. (And if we will have only replicas, and they would try to actually replicate the same parts to local storage of 6-12 nodes, it will be pretty inefficient disk utilization)

**Comment by dkultasev** [comment]
We are looking for similar functionality. This is our vision what we would like to achieve:
![image](https://user-images.githubusercontent.com/25481568/134398455-69aeab03-38ca-48b5-8b2c-e74ae5b6e1e5.png)

1. each SSD can have its own TTL
2. each machine/cluster has its own data settings for the cold storage (row policy, quota, etc)
3. need to work across different VPCs/accounts
4. a dataset is updated (INSERT INTO) on a daily basis
5. occasional MODIFY TABLE applied both to S3 and all SSDs

**Comment by azat** [comment]
@filimonov looks like this can be solved by `s3_plain` disk and `BACKUP`/`ATTACH`?
