### ISSUE TITLE
`bitSlice` function

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#28535]
**Use case**

#8922

**Describe the solution you'd like**

`bitSlice(s, offset, length)`

s is FixedString or String
the return value has String data type.

Offset starts from 1 for consistency with `substring` and `arraySlice`.

**Comment by ljcui** [comment]
Interested in working on this, can you assign it to me？

**Comment by alexey-milovidov** [comment]
Sure, welcome!

**Comment by alexey-milovidov** [comment]
@ljcui Are you working on this? This feature makes sense.

**Comment by RogerYK** [comment]
seems easy, I want to try it

**Comment by alexey-milovidov** [comment]
@RogerYK Thank you, it will be wonderful!
