### ISSUE TITLE
how to use allow_experimental_map_type

### ISSUE THREAD

**Issue by aaawuanjun** [ClickHouse/ClickHouse#28536]
# basic env
**clusters:** cluster_01
**clickhouse version:** 21.5.5.12
1、every node in cluster_01  has set allow_experimental_map_type params to 1 in users.xml
![image](https://user-images.githubusercontent.com/35732071/131937894-b7f969c8-756d-4bf9-85c9-876d39f8098c.png)
2、every node in cluster_01 use "select * from system.settings where changed=1;", can see config success
![image](https://user-images.githubusercontent.com/35732071/131938050-e049a4bb-28af-4239-b622-86606c6dbf32.png)
# basic test
I can create table has map in one node
`create table table_map (a Map(String, String)) engine = Memory;`
what ever in clickhouse-client or send http request, it is create table success
curl -sS "0.0.0.0:8123" -d "create table table_map (a Map(String, String)) engine = Memory;"
![image](https://user-images.githubusercontent.com/35732071/131938413-a120ec7e-c945-4eca-bb15-96ea2b094ca9.png)

# Problems
but when I add code "on cluster cluster_01"
`create table table_map (channel_code_map Map(String, String)) engine = Memory on cluster cluster_01;`
 it still cause problems: 
`Code: 44. DB::Exception: Received from 0.0.0.0:9000. DB::Exception: There was an error on [0.0.0.0:9000]: Code: 44, e.displayText() = DB::Exception: Cannot create table with column 'channel_code_map' which type is 'Map(String,String)' because experimental Map type is not allowed. Set 'allow_experimental_map_type = 1' setting to enable (version 21.5.5.1).`

# Question
How to use this params when I create table use "on cluster cluster_01"

**Comment by filimonov** [comment]
When you run the `ON CLUSTER` command, it's being executed by a special background thread called DDLWorker. 

The problem is that DDLWorker thread is created at the server start and uses the default profile settings which were active at the moment when the server was started.

So clickhouse-server restart should resolve the problem.
