### ISSUE TITLE
how to run clickhouse  code directly in Clion ?

### ISSUE THREAD

**Issue by wangqinghuan** [ClickHouse/ClickHouse#28544]
I am newbie to cpp. With [developer instruction](https://clickhouse.tech/docs/en/development/developer-instruction/), I can build and run Clickhouse successfully. If I want to debug code directly in IDE  Clion, how to configure or operate in Clion?

**Comment by murfel** [comment]
@wangqinghuan were you able to compile in CLion?

**Comment by alexey-milovidov** [comment]
@murfel I've switched to CLion recently and use it for compiling ClickHouse.
