### ISSUE TITLE
How to get detail error info when reading the input stream?

### ISSUE THREAD

**Issue by wangqinghuan** [ClickHouse/ClickHouse#28562]
I create a Kafka engine table ingesting data from Kafka. Some JSON data in Kafka violates table schema and Clickhouse prints some Exception 'Skipped 1 rows with errors which reading the input stream' in clickhouse-server.log. Without  more accurate parse error, I cannot get the reason why some data was not parsed. The log.level set in config.xml  is default trace.

**Comment by xiongbl526** [comment]
> I create a Kafka engine table ingesting data from Kafka. Some JSON data in Kafka violates table schema and Clickhouse prints some Exception 'Skipped 1 rows with errors which reading the input stream' in clickhouse-server.log. Without more accurate parse error, I cannot get the reason why some data was not parsed. The log.level set in config.xml is default trace.

hey,How did you solve this problem? I'm encountering the same issue now
