### ISSUE TITLE
CROSS JOIN not documented

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#2857]
Full cartesian product is quite usefull simetimes. It's [supported](https://github.com/yandex/ClickHouse/blob/master/dbms/tests/queries/0_stateless/00202_cross_join.sql) in ClickHouse, but not [documented](https://clickhouse.yandex/docs/en/query_language/select/#join-clause).

**Comment by olgarev** [comment]
@alexey-milovidov Do we need more information here? https://clickhouse.tech/docs/en/sql-reference/statements/select/join/

**Comment by alexey-milovidov** [comment]
No, it is alright.
