### ISSUE TITLE
Разграничение прав пользователей к разным бд

### ISSUE THREAD

**Issue by hashbash** [ClickHouse/ClickHouse#2858]
Добрый день!

Нам очень нужен функционал, который позволит разграничивать права доступа к бд внутри КХ. Например, у пользователя Х должен быть доступ на Запись к бд1 и только Чтение к бд2.

Чтобы можно было реализовать такую логическую структуру:

database_name     |user_name |access   |
---------|----------|----------|
logger   |user1     |readonly  |
raw      |user1     |readwrite  |
raw |user2     |readonly |

юзкейс: у нас много аналитиков, которым нужно дать права на запись только к своим (аналитическим бд) и при этом у них должен быть доступ только на чтение другим бд (туда, куда происходит запись данных от приложений).

**Comment by blinkov** [comment]
На данный момент см. последний абзац в https://clickhouse.yandex/docs/ru/operations/access_rights/

Для таких аналитиков можно завести отдельный небольшой кластер с readwrite доступом и настроить там distributed таблицы, которые бы «смотрели» на основной кластер. Заодно это обезопасит основной кластер от неожиданно закончившегося места или излишней нагрузки на ZooKeeper.

**Comment by hashbash** [comment]
Сейчас у нас уже есть отдельный кластер для аналитиков.
Но здесь есть две проблемы для аналитиков:
- запросы работают медленнее
- большие словари не помещаются в память

Обе проблемы следствие того, что аналитическом кластере меньше железок, а дублировать мощности не хочется. Отсюда и необходимость такой фичи.

**Comment by alexey-milovidov** [comment]
This task is in development by @vitlibar.
Current estimate for the first working implementation is Nov..Dec 2019.

**Comment by alexey-milovidov** [comment]
Implemented and available in recent releases.
