### ISSUE TITLE
S3 function/engine: How to convert DateTime from ISO 8601 string?

### ISSUE THREAD

**Issue by ecc256** [ClickHouse/ClickHouse#28599]
Guys,
I have somewhat similar [issue](https://github.com/ClickHouse/ClickHouse/issues/19351) with S3 import.
I use:
```
INSERT INTO {table}
SELECT *
FROM s3(
  '...',
  '...',
  '...',
  'CSV',
  '{columns}',
  'gzip');
```
Cannot use wildcard, have to do one file at a time, b/c if a file row cannot be parsed due to any error, whole file is not imported...

Both `parseDateTimeBestEffort/parseDateTime32BestEffort` can parse `ISO 8601` string just fine, but I'm unable to figure out how/where should I add the setting:
> just add `date_time_input_format = 'best_effort'` into the list of settings

The string in question is:
```
SELECT parseDateTimeBestEffort('2021-09-03T00:00:00.014+00:00');
SELECT parseDateTime32BestEffort('2021-09-03T00:00:00.014+00:00');
```

The columns list is huge, BTW...

**Comment by UnamedRus** [comment]
```
SET date_time_input_format = 'best_effort';

INSERT INTO {table}
SELECT *
FROM s3(
  '...',
  '...',
  '...',
  'CSV',
  '{columns}',
  'gzip');

```

https://clickhouse.tech/docs/en/operations/settings/#session-settings-intro

**Comment by ecc256** [comment]
@UnamedRus,
Thanks a lot for the tip!
I didn’t provide full example, my bad totally!

Long story short:
With {columns} defined as `time_iso8601_msec DateTime` it works both way (below)
It doesn’t work with `time_iso8601_msec String`
```
SET date_time_input_format = 'best_effort';
INSERT INTO {table}
SELECT *
FROM s3(
  '...',
  '...',
  '...',
  'CSV',
  '{columns}',
  'gzip');
```
```
INSERT INTO {table}
SELECT *
FROM s3(
  '...',
  '...',
  '...',
  'CSV',
  '{columns}',
  'gzip')
SETTINGS date_time_input_format='best_effort';
```

Out of curiosity, the 2nd case statement suffix/amendment: `SETTINGS date_time_input_format='best_effort';`
Is it applied to the whole statement `INSERT INTO {table} SELECT *` or to the `SELECT *` part only?

1st looks like _“cart before the horse”_.
Google translated as _“это выглядит как телега перед лошадью”_
What does it have to do with _telegram messenger_?
Is it more secure this way, thus better?

**Comment by UnamedRus** [comment]
1. You changing this setting value in scope of session. EG for all queries which you are going to execute afterwards.
2. It's applied to a whole query.

I think it does't work with string because you parsing time as simple string (this part works) and afterwards you are trying to insert that string to DateTime (this part fails)

Didn't understand part about telegram messenger.

**Comment by ecc256** [comment]
> 1.	You changing this setting value in scope of session. EG for all queries which you are going to execute afterwards.
> 2.	It's applied to a whole query.

Got it, thanks!

> I think it doesn't work with string because you parsing time as simple string (this part works) and afterwards you are trying to insert that string to DateTime (this part fails)

Does it mean, there is no way to make these string conversion work (i.e. work implicitly):
```
SELECT toDateTime('2021-09-03T00:00:00.014+00:00')
SETTINGS date_time_input_format='best_effort';
```
```
SET date_time_input_format='best_effort';
SELECT toDateTime('2021-09-03T00:00:00.014+00:00');
```
Only these work (i.e. explicit only):
```
SELECT parseDateTimeBestEffort('2021-09-03T00:00:00.014+00:00');
SELECT parseDateTime32BestEffort('2021-09-03T00:00:00.014+00:00');
```
right?


>Didn't understand part about telegram messenger.

Me neither... Just Goolge the word “телега” - you'll see I meant.
