### ISSUE TITLE
(task description in russian) Непонятное переполнение decimal64

### ISSUE THREAD

**Issue by struvv** [ClickHouse/ClickHouse#28627]
Описание типа:

Decimal64(S) - ( -1 * 10^(18 - S), 1 * 10^(18 - S) )

Выполняем **деление** 10 на 10 лежащих в типе toDecimal64 с S = 9
Ожидаемый результат - 1.000000000
Полученный результат - Decimal math overflow: While processing toDecimal64(10, 9) / toDecimal64(10, 9)

`select toDecimal64(10, 9)/toDecimal64(10, 9)`

```
SELECT toDecimal64(10, 9) / toDecimal64(10, 9)

Query id: 4bd6b1bf-7dbd-4a58-ab9f-dc1ea2e0703f


0 rows in set. Elapsed: 0.001 sec. 

Received exception from server (version 21.8.4):
Code: 407. DB::Exception: Received from localhost:9000. DB::Exception: Decimal math overflow: While processing toDecimal64(10, 9) / toDecimal64(10, 9). 

select version();

SELECT version()

Query id: ed2277d8-6e2b-4baa-a711-3bbc59e2def6

┌─version()─┐
│ 21.8.4.51 │
└───────────┘

1 rows in set. Elapsed: 0.001 sec. 
```

Почему так происходит?  Из описания
`Internal Representation Internally data is represented as normal signed integers with respective bit width`
следовательно происходит деление 10^10/10^10 что не выходит за границы 10^18

`select toDecimal64(9, 9)/toDecimal64(9, 9)`
выполняется корректно

**Comment by alexey-milovidov** [comment]
Тип результата должен вмещать в себя количество знаков до запятой, необходимое для хранения результата деления на самое маленькое ненулевое число.

```
SELECT
    CAST('10', 'Decimal64(9)') / CAST('0.00000001', 'Decimal64(8)') AS res,
    toTypeName(res) AS type

┌────────res─┬─type───────────┐
│ 1000000000 │ Decimal(18, 9) │
└────────────┴────────────────┘
```
