### ISSUE TITLE
[Mongo DB] Exception: Cannot authenticate in MongoDB, incorrect user or password. 

### ISSUE THREAD

**Issue by zeminhuang** [ClickHouse/ClickHouse#28638]
Received exception from server (version 20.7.2):
Code: 293. DB::Exception: Received from ip:port. DB::Exception: Cannot authenticate in MongoDB, incorrect user or password.

**Comment by nkolosov** [comment]
We have a same problem
`DB::Exception: Cannot authenticate in MongoDB, incorrect user or password (version 20.10.6.27 (official build))`
