### ISSUE TITLE
ALTER ... ADD COLUMN fails for sharded table

### ISSUE THREAD

**Issue by x052bb** [ClickHouse/ClickHouse#28646]
Hi 

We've got an environment with 2 shards, each has 4 replicas. Running DDL query like this:

`ALTER TABLE TEST_TABLE ON CLUSTER test_cluster ADD COLUMN IF NOT EXISTS TEST_COLUMN String`

And getting error like this:

`DB::Exception: There was an error on [<host>:<port>]: Cannot execute replicated DDL query on leader (version 20.4.6.53 (official build))`

If I remove the "ON CLUSTER" part and execute same query on each shard separately, it works ok, column is added.

Question here:
 - is it a bug or expected behavior? 
 - if this is expected, what is the correct way of running DDLs in clustered environment?

**Comment by den-crane** [comment]
version 20.4.6.53 is obsolete. Try 21.8.

How remote_servers configured ? internal_replication true or false ?

**Comment by x052bb** [comment]
`<internal_replication>true</internal_replication>`

Unfortunately, we cannot just upgrade to 21.8, this is production and we need to do the whole testing cycle beforehand. Do I understand correctly that this is a bug that was fixed in later version?

**Comment by den-crane** [comment]
>Do I understand correctly that this is a bug that was fixed in later version?

IDKN. The issue is not clear. We just don't support old versions. 
Check clickhouse-server.log for messages around the error.
