### ISSUE TITLE
Add 4 letters words to NuRaftKeeper

### ISSUE THREAD

**Issue by JackyWoo** [ClickHouse/ClickHouse#28649]
**Use case**

To monitor NuRaftKeeper internal status such as server info, client info, watch info, ephemeral nodes info etc. Zookeeper provides 4 letters admin tool. You can check it [here](https://zookeeper.apache.org/doc/r3.4.8/zookeeperAdmin.html#sc_zkCommands).

**Describe the solution you'd like**

1. When startup register 4 letter word command with a <code, command_executor> map. The code is name reinterpreted int32.
2. When new connection comes, first extract the first 4 characters and check whether it is 4lw command, if yes, run the command.
3. add some methods to `KeeperStorageDispatcher` to   collect server info.

Because the first request of a connection is hand shake request whose first 4 characters is request length and the length is fixed 44 or 45.  All  4lw code is larger than 2^24 or lower than 0, so collision never happens. 

In JD, we already added some 4lw commands to `SvsKeeper` which is a NuRaft based system like`NuRaftKeeper` . If the idea is ok, I'd like to add it to `NuRaftKeeper`

**Comment by amosbird** [comment]
https://github.com/ClickHouse/ClickHouse/issues/26976
