### ISSUE TITLE
Transaction Check Error:   file /etc/init.d from install of clickhouse-server-18.10.3-2.noarch conflicts with file from package chkconfig-1.3.49.5-1.el6.x86_64

### ISSUE THREAD

**Issue by qinzl1** [ClickHouse/ClickHouse#2865]
system version centos6

**Comment by qinzl1** [comment]
the new version can not install in centos6?  or how can i avoid  this conflicts  Error

**Comment by alexey-milovidov** [comment]
We have rewritten our RPM packages and there is no such issue anymore.

**Comment by alexey-milovidov** [comment]
https://clickhouse.tech/
See "Quick Start", CentOS/RedHat.

CentOS 6 is Ok.
