### ISSUE TITLE
Can I use spark or MR to build Clickhouse data tools?

### ISSUE THREAD

**Issue by shadowDy** [ClickHouse/ClickHouse#28673]
Can I use spark or MR to build Clickhouse data tools?
Spark/MR builds data to HDFS and mounts it to clickhouse through the attach command

**Comment by den-crane** [comment]
CH does not support that.
You can attach parts only from `detached` folder

**Comment by filimonov** [comment]
You can create parts using clickhouse-local
Those parts can be then moved to clickhouse server (manually) / attached using ATTACH command.
See: https://gist.github.com/filimonov/62bb8216cebd315262c45fcf31bb9231

**Comment by shadowDy** [comment]
> You can create parts using clickhouse-local
> Those parts can be then moved to clickhouse server (manually) / attached using ATTACH command.
> See: https://gist.github.com/filimonov/62bb8216cebd315262c45fcf31bb9231
@filimonov 
I'm trying to call clickhouse-local in spark task. Is there a successful demo that can be shared?
thanks~

**Comment by filimonov** [comment]
> > You can create parts using clickhouse-local
> > Those parts can be then moved to clickhouse server (manually) / attached using ATTACH command.
> > See: https://gist.github.com/filimonov/62bb8216cebd315262c45fcf31bb9231
> 
> @filimonov
> I'm trying to call clickhouse-local in spark task. Is there a successful demo that can be shared?
> thanks~

I don't have it. But YOU can create it :)

**Comment by shadowDy** [comment]
> > > You can create parts using clickhouse-local
> > > Those parts can be then moved to clickhouse server (manually) / attached using ATTACH command.
> > > See: https://gist.github.com/filimonov/62bb8216cebd315262c45fcf31bb9231
> > 
> > 
> > @filimonov
> > I'm trying to call clickhouse-local in spark task. Is there a successful demo that can be shared?
> > thanks~
> 
> I don't have it. But YOU can create it :)

ok~thanks 👍
