### ISSUE TITLE
DB::Exception: Cannot modify 'allow_experimental_window_functions' setting in readonly mode (version 21.4.3.21 (official build))

### ISSUE THREAD

**Issue by icexk** [ClickHouse/ClickHouse#28680]
I execute the following code with a read-only account

select 
rank() over (  order by gmv desc) as ranking,
barid,gmv
from dws_data.dws_bar_level_screen_detail_di  
where date = yesterday()  and gmv_m > 0
SETTINGS allow_experimental_window_functions = 1

DB::Exception: Cannot modify 'allow_experimental_window_functions' setting in readonly mode (version 21.4.3.21 (official build))

**Comment by alexey-milovidov** [comment]
Upgrade to release 21.8 that does not require to set `allow_experimental_window_functions` before using window functions.
