### ISSUE TITLE
How to prevent ATTACH in old versions previous to DETACH ... PERMANENTLY

### ISSUE THREAD

**Issue by inakisoriamrf** [ClickHouse/ClickHouse#28681]
Hello,
I have a problem with an old CH version, where old materializations are reattached after each startup.
How to remove a materialized view permanently (so it doesn’t reattach on startup) in older ch versions where detach … permanently is not present? Should I just delete it from the `metadata` folder after DETACH?

Thank you!

**Comment by den-crane** [comment]
> Should I just delete it from the metadata folder after DETACH?

Yes, you can delete .sql file from metadata folder.

**Comment by inakisoriamrf** [comment]
Thank you @den-crane =)
