### ISSUE TITLE
Deleting data from a Join table

### ISSUE THREAD

**Issue by iva3682** [ClickHouse/ClickHouse#28682]
Greetings! Such a question: can I delete data from a Join type table with a composite key by one field from this key?

For example, there is a table:

```
CREATE TABLE product_data_add_join
(
    `domen_id` UInt16,
    `vendor_code_hash` FixedString(16),
    `data_hash` FixedString(16)
)
ENGINE = Join(ANTI, LEFT, domen_id, vendor_code_hash, data_hash);
```
I want to delete rows with domen_id = 1:
`ALTER TABLE product_data_add_join DELETE WHERE domen_id = 1;`

Thanks!

**Comment by ILYenBui** [comment]
Hi Iva,
You can not delete rows with domen_id = 1 for join type table with a composite key as mentioned above:
Please see the code for more detail:
```
CREATE TABLE join_test
                (
                    `a` String,
                    `b` String,
                    `domen_id` UInt16
                )
                ENGINE = Join(ANTI, left, domen_id, a, b);
```
```
Insert into join_test values
                (’1’, ‘1’, 1)
                (’2’, ‘2’, 2)
                (’3, ‘3’, 3)
                (’4’, ‘4’, 4);
```
You will get error as the following: 
<img width="1209" alt="image" src="https://user-images.githubusercontent.com/102578911/162566254-6719b206-803a-46ea-bb60-8097ecdafb90.png">

**Comment by alexey-milovidov** [comment]
It's not possible to delete the data from Join table.
