### ISSUE TITLE
Unable to install specific version of ClickHouse through apt

### ISSUE THREAD

**Issue by thedeedawg** [ClickHouse/ClickHouse#28692]
**Describe the issue**
Trying to install a specific version of ClickHouse on a clean install of Ubuntu fails to install the correct dependencies.

**How to reproduce**
* Follow the debian instructions from the official documentation [here](https://clickhouse.tech/docs/en/getting-started/install/)
* Instead of latest version, run `sudo apt-get install clickhouse-server=21.6.5.37`

**Expected behavior**
I would expect the package to be able to install its dependencies at the version required, and not attempt to install them at the latest version.

**Error message and/or stacktrace**
```
root@95849e261940:/# apt-get install clickhouse-server=21.6.5.37
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 clickhouse-server : Depends: clickhouse-common-static (= 21.6.5.37) but 21.8.5.7 is to be installed
                     Recommends: libcap2-bin but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
Installing the expected dependency manually beforehand allows the installation to proceed.

**Comment by den-crane** [comment]
You need to install 3 packages 
```
apt-get install clickhouse-server=21.8.2.19 clickhouse-client=21.8.2.19 clickhouse-common-static=21.8.2.19
```
