### ISSUE TITLE
How can I provide specific settings for kafka topic with dots in name?

### ISSUE THREAD

**Issue by tinurcity** [ClickHouse/ClickHouse#28703]
I tried provide sass configuration for topic with name like 'team.topic', but unsuccessfully
I also tried replace dot with underscore.    
<yandex>
  <kafka replace="replace">
    <debug>broker,cgrp</debug>
    <auto_offset_reset>earliest</auto_offset_reset>
  </kafka>
  <kafka_team.topic>
    <security_protocol>SASL_SSL</security_protocol>
    <sasl_mechanism>PLAIN</sasl_mechanism>
    <sasl_username>some_sasl_username</sasl_username>
    <sasl_password>some_sasl_password</sasl_password>
    <ssl_ca_location>/path/to/extra_ca.crt</ssl_ca_location>
  </kafka_team.topic>
</yandex>

**Comment by filimonov** [comment]
XML parser used to read the configuration files don't allow to have dots in tag names. 
Maybe you can just set it up globally - for all topics?

**Comment by tinurcity** [comment]
I have to provide two configs for two Kafka cluster (one PLAINTEXT and SASL_SSL another), and naming conventions
 demand me to use dots, also we have topics for debezium (dots demanded too) =( 
If I could define mask for topics, it would be great feature

**Comment by filimonov** [comment]
It can be done in recent releases using [named collections](https://github.com/ClickHouse/ClickHouse/pull/31691/)

Like that

```xml
<!-- /etc/clickhouse-server/config.d/kafka_preset1.xml -->
<clickhouse>
    <named_collections>
        <kafka_preset1>
            <kafka_broker_list>broker1:345,broker2:345</kafka_broker_list>
            <kafka_topic_list>topic.with.dot.in.name</kafka_topic_list>
            <kafka_group_name>clickhouse_topic_group</kafka_group_name>
            <kafka>
                <security_protocol>sasl_ssl</security_protocol>
                <sasl_mechanism>SCRAM-SHA-512</sasl_mechanism>
                <sasl_username>user</sasl_username>
                <sasl_password>password</sasl_password>>
                <auto_offset_reset>smallest</auto_offset_reset>
                <ssl_endpoint_identification_algorithm>https</ssl_endpoint_identification_algorithm>
                <ssl_ca_location>probe</ssl_ca_location>
            </kafka>
        </kafka_preset1>
    </named_collections>
</clickhouse>
```

```sql
CREATE TABLE kafka
(
    `key` UInt64,
    `value` UInt64
)
ENGINE = Kafka(kafka_preset1, kafka_format = 'CSV')
```

**Comment by MahmoudElhalwany** [comment]
> It can be done in recent releases using [named collections](https://github.com/ClickHouse/ClickHouse/pull/31691/)
> 
> Like that
> 
> ```
> 
> <clickhouse>
>     <named_collections>
>         <kafka_preset1>
>             <kafka_broker_list>broker1:345,broker2:345</kafka_broker_list>
>             <kafka_topic_list>topic.with.dot.in.name</kafka_topic_list>
>             <kafka_group_name>clickhouse_topic_group</kafka_group_name>
>             <kafka>
>                 <security_protocol>sasl_ssl</security_protocol>
>                 <sasl_mechanism>SCRAM-SHA-512</sasl_mechanism>
>                 <sasl_username>user</sasl_username>
>                 <sasl_password>password</sasl_password>>
>                 <auto_offset_reset>smallest</auto_offset_reset>
>                 <ssl_endpoint_identification_algorithm>https</ssl_endpoint_identification_algorithm>
>                 <ssl_ca_location>probe</ssl_ca_location>
>             </kafka>
>         </kafka_preset1>
>     </named_collections>
> </clickhouse>
> ```
> 
> ```sql
> CREATE TABLE kafka
> (
>     `key` UInt64,
>     `value` UInt64
> )
> ENGINE = Kafka(kafka_preset1, kafka_format = 'CSV')
> ```

Hello Bro, which version supports SASL_SSL? and if there is a version with support for IAM role let me know! thanks
