### ISSUE TITLE
More control over Dictionary updates

### ISSUE THREAD

**Issue by scf37** [ClickHouse/ClickHouse#28702]
**Use case**

For some analytical applications aggregating queries must be run on consistent database which includes consistent dictionaries. While ensuring MergeTree tables consistency is straightforward, it is not so easy for dictionaries.

Basically, there are only two options to enforce dictionary consistency:
a) SYSTEM RELOAD DICTIONARY
b) wait `lifetime` seconds for incremental dictionary update.

First approach works but is inefficient - even if we know only one row has been changed we have to reload entire dictionary contents.
Second is even slower.

**Describe the solution you'd like**

Add `SYSTEM UPDATE DICTIONARY` command that triggers dictionary update as if dictionary `lifetime` interval expired.

**Describe alternatives you've considered**

- `SYSTEM RELOAD DICTIONARY` and try to keep dictionaries small

**Additional context**

More complex solutions might include MQ as a data source for dictionary or extending `Clickhouse` data source to push updates to connected Dictionary immediately on insert.

**Comment by den-crane** [comment]
Are you aware about partial updates? https://kb.altinity.com/altinity-kb-dictionaries/partial-updates/

**Comment by scf37** [comment]
@den-crane Absolutely. As I wrote just above partial updates unfortunately can not be triggered by hand, only when dictionary `lifetime` expires, and `SYSTEM RELOAD DICTIONARY` always triggers full update.
