### ISSUE TITLE
When I use functions to partition, how do I specify my partition key?

### ISSUE THREAD

**Issue by liumengkai** [ClickHouse/ClickHouse#28724]
This is my create table sql:

CREATE TABLE IF NOT EXISTS adt_postback_event ON CLUSTER adt_ch_cluster1
(
`create_time`               Int32,
`app_id`                    String,
`country`                   String,
`type`                      String,
`event_name`                String,
`campaign_id`               Int32,
`advertiser_id`             Int32,
`publisher_id`              Int32,           
`platform`                  TINYINT,
`traffic_type`              TINYINT,       
`traffic_type_demand`       TINYINT,
`retargeting`               TINYINT,
`device_id`                 String)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/adt_postback_event', '{replica}')
PARTITION BY (formatDateTime(toDateTime(toUnixTimestamp(create_time)),'%Y%m%d'))
ORDER BY tuple()

You can see that I use a formatDateTime(toDateTime(toUnixTimestamp(create_time))) to partition,but how can I specify my partition key?

eg:
I want to get 20210902 data,I try this.but it tells me partition is not a known column
select * from adt_postback_event_all where partition = '20210902'

How can I figure out the partition key in this situation?

could someone give me some advice?  thanks a lot!

**Comment by alesapin** [comment]
Hi!
We have several virtual columns in MergeTree. In your case you probably want _partition_value column:
```
select formatDateTime(toDateTime(toUnixTimestamp(create_time)),'%Y%m%d'), _partition_id, _partition_value from adt_postback_event where _partition_value = tuple('20210907')

SELECT
    formatDateTime(toDateTime(toUnixTimestamp(create_time)), '%Y%m%d'),
    _partition_id,
    _partition_value
FROM adt_postback_event
WHERE _partition_value = tuple('20210907')

Query id: 889e8953-6af2-4694-9d72-1bfa45ea14b5

┌─formatDateTime(toDateTime(toUnixTimestamp(create_time)), '%Y%m%d')─┬─_partition_id────────────────────┬─_partition_value─┐
│ 20210907                                                           │ 6874279ab53fc760f1c966c5b384ef72 │ ('20210907')     │
└────────────────────────────────────────────────────────────────────┴──────────────────────────────────┴──────────────────┘

1 rows in set. Elapsed: 0.005 sec. 
```

**Comment by liumengkai** [comment]
Hi @alesapin 
thanks for your replay, is there a web page describing the parameters "_partition_value"?

**Comment by filimonov** [comment]
Just a side note: `PARTITION BY (formatDateTime(toDateTime(toUnixTimestamp(create_time)),'%Y%m%d')) ` is a bad partitioning key. 
Use `toYYYYMMDD(create_time)` and `create_time DateTime`
