### ISSUE TITLE
Can not produce coredump with SIGQUIT 

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#28721]
signal handler used to catch [SIGABRT, SIGSEGV, SIGILL, SIGBUS, SIGSYS, SIGFPE, SIGPIPE, SIGTSTP, SIGTRAP](https://github.com/ClickHouse/ClickHouse/blob/ec9769525711d9d8bb381ba1628a6dba46fac81a/base/daemon/BaseDaemon.cpp#L811) calls the [default signal hander](https://github.com/ClickHouse/ClickHouse/blob/ec9769525711d9d8bb381ba1628a6dba46fac81a/base/daemon/BaseDaemon.cpp#L156) (which can create core dump).  

But the signal handler used for [SIGQUIT](https://github.com/ClickHouse/ClickHouse/blob/ec9769525711d9d8bb381ba1628a6dba46fac81a/base/daemon/BaseDaemon.cpp#L813) don't do that (while the default behavior for SIQQUIT - is to write the core dump). 

Maybe we should just catch SIGQUIT same way as SIGABRT/SIGSEGV?

**Comment by alexey-milovidov** [comment]
Maybe, but it is questionable.

man 7 signal:
```
SIGQUIT      P1990      Core    Quit from keyboard
```

So, it is producing core dump by default.
It is also responsible for "quit from keyboard" like Ctrl+C but another.

I don't understand the motivation:
- why is should produce core dump?
- why do you need to get core dump of ClickHouse server without any errors?

The drawbacks are:
- core dump is usually very large and also sparse;
- it will slowdown the system for minutes while it will be written;

There are many alternative ways to debug a server:
- `system.stack_trace` table;
- attach gdb and do whatever you want, including generating a core dump;

What do you want to get from core dump in addition to stack traces?

It's unlikely you need it for production usage. And if you need it for development, you can simply edit the code.
Also you can generate core dump with any other ways (e.g. `kill -11 $(pidof clickhouse-server)`).

Even being ClickHouse developer you rarely need to analyze core dump (e.g. I do it maybe once a year).

**Comment by filimonov** [comment]
> I don't understand the motivation:
>why it should produce core dump?

Because it is a standard and expected behaviour when you send sigquit. 

> SIGQUIT
The SIGQUIT signal is similar to SIGINT, except that it’s controlled by a different key—the QUIT character, usually C-\—and **produces a core dump when it terminates the process**, just like a program error signal. You can think of this as a **program error condition “detected” by the user**.

Right now sigquit is processed by clickhouse **exactly** like sigint. Why do we need 2 sigint signals? 

> why do you need to get core dump of ClickHouse server without any errors?

For ex. application hungs, no segfault and other errors. Good admin just send sigquit to stop it and to get the coredump to analize it later. But cluckhouse instead of that will start graceful shutdown. 

> What do you want to get from core dump in addition to stack traces?

Variables in heap and in stack for ex., locks and other internal, race conditions etc. 

> attach gdb and do whatever you want, including generating a core dump;
> It's unlikely you need it for production usage.

On prod servers you not always have a gdb and other debug tools. And you want to save all evidences fast and make server run again, without keeping the server offline for hours. Coredump is a nice option for that - enough to send a signal. But it's not intuitive that you can not use a standard signal for it.

**Comment by filimonov** [comment]
> core dump is usually very large and also sparse (hundred gigabytes);

On modern OSes there are tools to address that, for ex. `coredumpctl` compress them by default with LZ4. 

> it will slowdown the system for minutes while it will be written;

Installing gdb on the server, and manual debugging session on the server takes much more. 

> Also you can generate core dump with any other ways (e.g. kill -11 $(pidof clickhouse-server)).

Yes, I can. But why can we use default things? :)
It makes prof. Preobrazhensky unhappy:

> — И где же я должен принимать пищу?
> — В спальне!
> — Очень возможно, что Айседора Дункан так и делает. Может быть, она в кабинете обедает, а в ванной режет кроликов. Может быть. Но я — не Айседора Дункан. Я буду обедать в столовой, а оперировать в операционной! ... 

:)

**Comment by alexey-milovidov** [comment]
Ok, send a pull request...
I hope no one was using SIGQUIT for graceful shutdown.
