### ISSUE TITLE
Build clickhouse with asan failed on x86-64 linux when using gcc 10.2

### ISSUE THREAD

**Issue by mo-avatar** [ClickHouse/ClickHouse#28725]
Here are the cmake options:
cmake .. -DENABLE_READLINE=1 -DENABLE_PARQUET=1 -DENABLE_ORC=1 -DENABLE_PROTOBUF=1 -DENABLE_SSL=1 -DENABLE_JEMALLOC=ON -DENABLE_MYSQL=1 -DENABLE_DATA_SQLITE=0 -DPOCO_ENABLE_SQL_SQLITE=0 -DENABLE_ODBC=1 -DENABLE_CLICKHOUSE_ODBC_BRIDGE=0 -DUSE_INTERNAL_BOOST_LIBRARY=1 -DUSE_INTERNAL_ODBC_LIBRARY=1 -DENABLE_EMBEDDED_COMPILER=0 -DNO_WERROR=1 -DCMAKE_CXX_COMPILER=/usr/local/bin/g++ -DCMAKE_C_COMPILER=/usr/local/bin/gcc -DCMAKE_BUILD_TYPE=Debug -DUSE_STATIC_LIBRARIES=1 -DMAKE_STATIC_LIBRARIES=1 -DCLICKHOUSE_SPLIT_BINARY=0 -DDISABLE_COLORED_BUILD=0 -DCOMPILER_PIPE=1  -DENABLE_HDFS=1 -DUSE_INTERNAL_HDFS3_LIBRARY=1 -DSANITIZE=address  -DENABLE_JEMALLOC=0 -G Ninja

Here is the error message.
FAILED: contrib/protobuf/protoc-3.13.0.0
: && /usr/local/bin/g++  -g -fno-omit-frame-pointer -DSANITIZER -fsanitize=address -fsanitize-address-use-after-scope -fdiagnostics-color=always -fsized-deallocation  -pipe -msse4.1 -msse4.2 -mpopcnt -fasynchronous-unwind-tables -falign-functions=32   -Wall  -Werror -w -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -g -O0 -g3 -ggdb3 -fno-inline  -D_LIBCPP_DEBUG=0  -fuse-ld=gold -fsanitize=address -fsanitize-address-use-after-scope -static-libasan -rdynamic -Wl,-no-pie   -rdynamic contrib/protobuf/CMakeFiles/protoc.dir/__/src/google/protobuf/compiler/main.cc.o  -o contrib/protobuf/protoc-3.13.0.0  contrib/protobuf/libprotocd.a  contrib/protobuf/libprotobufd.a  -lpthread  -Wl,--start-group  -Wl,-static -lasan -Wl,-Bdynamic  base/glibc-compatibility/libglibc-compatibilityd.a  base/glibc-compatibility/memcpy/libmemcpyd.a  contrib/libcxx-cmake/libcxxd.a  contrib/libcxxabi-cmake/libcxxabid.a  contrib/libunwind-cmake/libunwindd.a  -Wl,--end-group  -nodefaultlibs -lgcc  -lc -lm -lrt -lpthread -ldl && :
/lib/../lib64/libpthread.a(libpthread.o)(.eh_frame+0x86b73): error: undefined reference to '__gcc_personality_v0'
../../.././libsanitizer/asan/asan_linux.cpp:88: error: undefined reference to '_DYNAMIC'
/lib/../lib64/libc.a(iofclose.o):DW.ref.__gcc_personality_v0: error: undefined reference to '__gcc_personality_v0'
collect2: error: ld returned 1 exit status
[3475/8232] Building CXX object contrib/grpc/CMakeFiles/grpc.dir/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc.o
ninja: build stopped: subcommand failed.

For some reason, we can't switch to clang right now, and when I try  to enable ASAN，the build just failed. 
Any comment will be appreciated, thanks a lot !

**Comment by alesapin** [comment]
Hi! We don't support any other builds than we have in our CI configuration https://github.com/ClickHouse/ClickHouse/blob/b8cfad4ba2d0e1fb4518a01a537e0dd6660ce9cb/tests/ci/ci_config.json#L2-L166. 

But if you want to fix gcc build with asan pull requests are welcome :)

**Comment by mo-avatar** [comment]
> Hi! We don't support any other builds than we have in our CI configuration
> 
> https://github.com/ClickHouse/ClickHouse/blob/b8cfad4ba2d0e1fb4518a01a537e0dd6660ce9cb/tests/ci/ci_config.json#L2-L166
> 
> .
> But if you want to fix gcc build with asan pull requests are welcome :)
Thanks for the reply. I‘d like to fix it, but  I'm no expert of  compilation. Anyway, If I find a way to fix it , I will send a pull request.
