### ISSUE TITLE
使用https连接clickhouse

### ISSUE THREAD

**Issue by loveYu1314** [ClickHouse/ClickHouse#28726]
clickhouse如何开通https，并做SSL认证，需要验证证书，有没有比较成熟的例子供参考

**Comment by loveYu1314** [comment]
客户端使用java jdbc如何连接并认证证书？

**Comment by filimonov** [comment]
> Use https to connect to clickhouse
> 
> How does clickhouse open https, and do SSL certification, need to verify the certificate, are there any more mature examples for reference
> 
> How does the client use java jdbc to connect and authenticate the certificate? 


Check 
https://docs.altinity.com/operationsguide/security/clickhouse-hardening-guide/network-hardening/
https://altinity.com/blog/2019/3/5/clickhouse-networking-part-2
