### ISSUE TITLE
Insert failed on WSL2 and NTFS - Cannot set modification time for file

### ISSUE THREAD

**Issue by sscobici** [ClickHouse/ClickHouse#28722]
Hi,
I installed Ubuntu on Windows using WSL2 and installed clickhouse version 21.8.4.51.
I created simple create table and inserted the data successfully into default storage policy which is on ext4 in Ubuntu.

I then configured new clickhouse storage policy for NTFS disk and created a table with that policy successfully.
```
file: - /etc/clickhouse-server/config.d/storage.xml

<yandex>
  <storage_configuration>
    <disks>
      <default>
         <keep_free_space_bytes>1024</keep_free_space_bytes>
      </default>
      <diskd>
         <path>/mnt/d/clickhouse</path>
      </diskd>
    </disks>
    <policies>
      <diskd_policy>
        <volumes>  
          <diskd_volume>
            <disk>diskd</disk>
          </diskd_volume>
        </volumes>
      </diskd_policy>
    </policies>
  </storage_configuration>
</yandex>
```

When I try to insert some data into the table I get the following error:
`Cannot set modification time for file: /mnt/d/clickhouse/store/ee2/ee2ccc87-3bc0-4341-ae2c-cc873bc08341/tmp_insert_20210706_1_1_0/, errno: 1, strerror: Operation not permitted`

Disk D is mounted in Ubuntu with default options:
`(rw,noatime,dirsync,aname=drvfs;path=D:\;uid=1000;gid=1000;symlinkroot=/mnt/,mmap,access=client,msize=65536,trans=fd,rfd=8,wfd=8)`

I've created a simple c++ program in Ubuntu and it had updated modtime for that folder successfully, atime was not modified because of noatime mount setting:
```
#include <iostream>
#include <utime.h>

int main() {
    struct utimbuf tb;
    tb.actime  = 1630738133;
    tb.modtime = 1630738133;
    int result = utime("/mnt/d/clickhouse/store/ee2/ee2ccc87-3bc0-4341-ae2c-cc873bc08341/tmp_insert_20210706_1_1_0/", &tb);
    if (result != 0)
        std::cout << "Error: " << result << std::endl;
    return 0;
}
```

What can be the reason for the clickhouse error?

**Comment by musicx** [comment]
any chance you've found the solution?

**Comment by sscobici** [comment]
It is something with windows, because other applications also have some file issues. WSL2 is a bit broken

**Comment by millecodex** [comment]
This failed for me too with the same configuration: clickhouse 22.3.2.1. on WSL2. I also tried inserting into an exFAT drive to no avail.

**Comment by Geograph-us** [comment]
You can create a vhdx-file on Windows for a virtual drive (max size 64 TB), format in ext4, then mount it to WSL.
