### ISSUE TITLE
join on condition equal to a defined value will meet exception from version 21.5.5.12

### ISSUE THREAD

**Issue by DonyDong996** [ClickHouse/ClickHouse#28733]
> You have to provide the following information whenever possible.

join on condition equal to a defined value will meet exception from version 21.5.5.12

> A clear and concise description of what works not as it is supposed to.

Query works on version 21.4.7.3
----------------------------------------------

lotest :) select version()
:-] ;

SELECT version()

Query id: dc901543-9405-40f6-9464-70e567c736b2

┌─version()─┐
│ 21.4.7.3  │
└───────────┘

1 rows in set. Elapsed: 0.002 sec.

lotest :) SELECT *
:-] FROM left_t1
:-] Left jOIN right_t1 ON left_t1.a = right_t1.a AND right_t1.b=2222;

SELECT *
FROM left_t1
LEFT JOIN right_t1 ON (left_t1.a = right_t1.a) AND (right_t1.b = 2222)

Query id: 1047fede-f383-481b-8ad5-036873582883

┌─a─┬──b─┬─create_date─┬─right_t1.a─┬─right_t1.b─┬─right_t1.create_date─┐
│ 3 │ 22 │  1975-06-21 │          0 │          0 │           1970-01-01 │
└───┴────┴─────────────┴────────────┴────────────┴──────────────────────┘
┌─a─┬──b─┬─create_date─┬─right_t1.a─┬─right_t1.b─┬─right_t1.create_date─┐
│ 2 │ 22 │  1975-06-21 │          2 │       2222 │           1975-06-21 │
└───┴────┴─────────────┴────────────┴────────────┴──────────────────────┘
┌─a─┬──b─┬─create_date─┬─right_t1.a─┬─right_t1.b─┬─right_t1.create_date─┐
│ 2 │ 22 │  1975-06-21 │          2 │       2222 │           1975-06-21 │
└───┴────┴─────────────┴────────────┴────────────┴──────────────────────┘
┌─a─┬──b─┬─create_date─┬─right_t1.a─┬─right_t1.b─┬─right_t1.create_date─┐
│ 1 │ 11 │  1975-06-21 │          0 │          0 │           1970-01-01 │
└───┴────┴─────────────┴────────────┴────────────┴──────────────────────┘

4 rows in set. Elapsed: 0.004 sec.

But fail since version 21.5.5.12 
-------------------------------------------------------
lotest :) select version()

SELECT version()

Query id: 06d93cf5-3141-4aae-a81c-3f8af1368631

┌─version()─┐
│ 21.8.5.7  │
└───────────┘

1 rows in set. Elapsed: 0.001 sec.

lotest :) SELECT * FROM left_t1
:-] Left jOIN right_t1 ON left_t1.a = right_t1.a AND right_t1.b=2222;

SELECT *
FROM left_t1
LEFT JOIN right_t1 ON (left_t1.a = right_t1.a) AND (right_t1.b = 2222)

Query id: c5cf1c9f-309f-4023-aab1-774a1535ec62

0 rows in set. Elapsed: 0.001 sec.

Received exception from server (version 21.8.5):
Code: 403. DB::Exception: Received from localhost:9000. DB::Exception: Not equi-join ON expression: right_t1.b = 2222. No columns in one of equality side.: While processing right_t1.b = 2222.

someone has the same problem on version 21.5.5.12
---------------------------------------------
https://gitmemory.com/issue/ClickHouse/ClickHouse/24437/846981568

**Comment by filimonov** [comment]
> someone has the same problem on version 21.5.5.12

Yes, and there was also a clear explanation of that there: https://github.com/ClickHouse/ClickHouse/issues/24437

**Comment by filimonov** [comment]
Is working again since 21.9.
