### ISSUE TITLE
some question about clickhouse-local

### ISSUE THREAD

**Issue by shadowDy** [ClickHouse/ClickHouse#28749]
1: How to control the number of writes in stdin mode (how many entries can be input before flushing to the disk)

2: How to trigger forced merge to a single part, or force merge to a single part before exiting (one part, one folder)

3: How will min not be reached when exiting_ insert_ block_ size_ The number of rows is flushed to the disk

4: How to set to execute optimize when exiting and clean up the old version data after merge

**Comment by melvynator** [comment]
With regards with:
> 2: How to trigger forced merge to a single part, or force merge to a single part before exiting (one part, one folder)
> 4: How to set to execute optimize when exiting and clean up the old version data after merge

Maybe I'm missing some context here, did you try adding the optimize and merge query at the end of the query file?

**Comment by melvynator** [comment]
Closing since there is no reply for a month. Feel free to reopen if needed.
