### ISSUE TITLE
here document syntax make `$` as special char

### ISSUE THREAD

**Issue by benbiti** [ClickHouse/ClickHouse#28768]
**Describe the issue**
here document syntax make `$` as as special char。if use `$` as column name prefix, may cause parse problem。

**How to reproduce**
* Which ClickHouse server versions are incompatible
v21.9

* Queries to run that lead to unexpected result

`
select '1' as $doc
union all
select '2' as $doc
union all
select '2' as $doc
union all
select '2' as $doc;
`

**Error message and/or stacktrace**
`
Syntax error: failed at position 15 ('$doc
         union all
         select '2' as $doc
         union all
         select '2' as $doc
         union all
         select '2' as $') (line 1, col 15):

Expected one of: end of query, identifier
`

should we make this Feature as  Incompatible Change?

@kitaisreal

**Comment by benbiti** [comment]
https://github.com/ClickHouse/ClickHouse/pull/26671

**Comment by alexey-milovidov** [comment]
It was never intended to allow `$` in identifiers.

Maybe it was introduced for MaterializeMySQL engine or something similar.
