### ISSUE TITLE
Failed to create table with Date32 type column - Unknown data type family

### ISSUE THREAD

**Issue by pdutta777** [ClickHouse/ClickHouse#28765]
Can not create a table with column type Date32. Documentation shows that this is a data type, but it looks like it is not supported in the current version:

```
SELECT *
FROM system.data_type_families
WHERE name LIKE 'Date%'

Query id: b720b088-b774-4156-b6b5-986541e34acb

┌─name───────┬─case_insensitive─┬─alias_to─┐
│ DateTime   │                1 │          │
│ Date       │                1 │          │
│ DateTime64 │                1 │          │
│ DateTime32 │                1 │          │
└────────────┴──────────────────┴──────────┘

4 rows in set. Elapsed: 0.002 sec.
```

**How to reproduce**

* Clickhouse version 21.8.5
* `CREATE TABLE test1 (col1 Date32) engine=Memory();`

**Expected behavior**

Table should be created

**Error message and/or stacktrace**

```
Received exception from server (version 21.8.5):
Code: 50. DB::Exception: Received from localhost:9000. DB::Exception: Unknown data type family: Date32. Maybe you meant: ['Date'].
```

**Comment by kssenii** [comment]
@pdutta777 you got an error because date32 data type is available starting from 21.9, not in 21.8.

**Comment by pdutta777** [comment]
Ok, thanks. It is a bit confusing because documentation shows the Date32 type and functions. Is there any tentative release date for 21.9?

**Comment by den-crane** [comment]
21.9 was released today. https://github.com/ClickHouse/ClickHouse/releases/tag/v21.9.2.17-stable
