### ISSUE TITLE
Any plan to optimize ReplacingMergeTree's performance?

### ISSUE THREAD

**Issue by yiguolei** [ClickHouse/ClickHouse#28766]
In our cases, a lot of data is from MySQL, there are inserts, updates or deletes , we use Replacing Merge Tree to store the data, but every SQL need add keyword FINAL to ensure the result is correct.

The performance is very poor... Is there any plan to improve it's performance? 

The feature is strongly expected !!!!

**Comment by filimonov** [comment]
See 
https://kb.altinity.com/engines/mergetree-table-engine-family/replacingmergetree/ 
https://kb.altinity.com/altinity-kb-queries-and-syntax/altinity-kb-final-clause-speed/

**Comment by yiguolei** [comment]
Any plan to add a visibility bitmap for every part during insert part?  So that do not need merge by primary key between different part during query.  Lucene has such a visible map.

**Comment by alexey-milovidov** [comment]
The FINAL performance is improved in version 22.7.
