### ISSUE TITLE
CTE with aggregations backwards incompatibilities

### ISSUE THREAD

**Issue by nvartolomei** [ClickHouse/ClickHouse#28796]
```sql
with min(dummy) as d select dummy from remote('server{1,2}', system.one) group by dummy format TSVWithNames
```

When server1 is running <= v20.9 and server2 v20.10 queries against v20.9 replica are failing with 

```
DB::Exception: Not found column d in block. There are only columns: dummy: While executing Remote.
```

It seems that v20.10+ got smarter about what columns are needed for query execution and prunes them.

What PR did introduce this change? Any suggestions for workarounds beside rewriting queries to not include useless CTEs?

```
clickhouse-client --host server1 --stage with_mergeable_state --query 'with min(dummy) as d select dummy from system.one group by dummy format TSVWithNames'
dummy	d
0	\0
```

```
clickhouse-client --host server2 --stage with_mergeable_state --query 'with min(dummy) as d select dummy from system.one group by dummy format TSVWithNames'
dummy
0
```

**Comment by nvartolomei** [comment]
after a fair bit of git bisecting found #15886 to be the cause

**Comment by nvartolomei** [comment]
Here is another example, broken by a different thing:

```sql
with sum(is_aggregate) as d select count() from remote('server{1,2}', system.functions) format TSVWithNames

-- DB::Exception: Not found column d in block. There are only columns: count(): While executing Remote
```

**Comment by nvartolomei** [comment]
Last one, I think, is caused by #18684

**Comment by nvartolomei** [comment]
@amosbird do you have any ideas here? I'm a bit lost in that code.

**Comment by alexey-milovidov** [comment]
If you do rolling upgrade and encounter this error, proceed with upgrading and the error will go away after finishing the upgrading process.

It may require small downtime for small part of the queries.
