### ISSUE TITLE
Clickhouse returns 400 without trace when more than ~300 ADD COLUMN statements contained in query

### ISSUE THREAD

**Issue by ksilex** [ClickHouse/ClickHouse#28811]
**Unexpected behaviour**
Table has 550 fields, when I execute script that randomly selects less than ~300 columns and runs query:
ALTER TABLE test.forms ADD COLUMN IF NOT EXISTS account_number String, etc...
it runs without errors, when query contains more than ~300 add columns I get next error: Got status 400 (expected 200) - there's nothing more, just 400
**How to reproduce**
default settings
Clickhouse version: 21.3.5.42
**Expected behavior**
NO ERRORS
Same steps were done on latest Clickhouse  21.9 and no error occured
**Error message and/or stacktrace**
Got status 400 (expected 200)

**Comment by alesapin** [comment]
Seems like you are using HTTP ClickHouse interface? Can you try to execute the same query with `clickhouse-client`?

**Comment by alexey-milovidov** [comment]
It happens because your query is very long.
You should send it in POST body instead of URL.
