### ISSUE TITLE
What if version column in ReplacingMergeTree overflows?

### ISSUE THREAD

**Issue by grongor** [ClickHouse/ClickHouse#28849]
I know there is a possibility to use type `UInt256` for version column in `ReplacingMergeTree`, in which the overflow is probably unrealistic, but still possible. What happens then, when I reach the maximum "version" and I need to create a new one? How does ClickHouse handle it? Or how should I handle it? Thank you!

**Comment by den-crane** [comment]
Even UInt16 or UInt32 should be enough. 
4294967295 is insane number of versions "updates"

**Comment by grongor** [comment]
Well, that doesn't really answer the question. And it depends on the use cases... I'm for example trying to track all network prefixes and related data from BGP available in our network, in real time, which means  thousands of updates per second. So, when the counter overflows, there is no sane way to continue I guess.

**Comment by den-crane** [comment]
>Well, that doesn't really answer the question.

Then numeric type is overflow then number starts again with 0.
ReplacingMergeTree will treat overflowed 0 as version which less than MAX_NUMBER.
It's your responsibility to deal with it.

>which means thousands of updates per second. 

This is insane. 

Do you understand that you can omit version in ReplacingMergeTree? 
In this case ReplacingMergeTree will use internal/natural order of blocks (order of inserts).

**Comment by grongor** [comment]
> It's your responsibility to deal with it.

Thanks. That's what I needed to know, if ClickHouses accounts for the overflow, or if I have to work around it somehow.

> This is insane.

Yeah, but it must be done :D 

> Do you understand that you can omit version in ReplacingMergeTree?

Yes, but thank you for mentioning it. There will be parallel writes, that's why I went with the version column.

**Comment by alexey-milovidov** [comment]
UInt64 is good enough for 1000 updates per second (with this rate it will require ~ 100 million years to overflow).

**Comment by grongor** [comment]
Sure, I knew I would probably be okay with one of the UInt types :) The question was more or less academic - I just wanted to know how ClickHouse would handle this, if it ever were to happen :)
