### ISSUE TITLE
Logical error: Part is already written by concurrent request

### ISSUE THREAD

**Issue by zhbdesign** [ClickHouse/ClickHouse#28848]
There is a bug in inserting data

Code: 49, e.displayText() = DB::Exception: Part with name 202109_1799_1799_0 is already written by concurrent request. It should not happen for non-duplicate data parts because unique names are assigned for them. It's a bug (version 21.7.4.18 (official build))

**Comment by tavplubix** [comment]
Could you please provide more information? What happened with part 202109_1799_1799_0 before the error (`zgrep -Fa "202109_1799_1799_0" /var/lib/clickhouse-server/clickhouse-server.*`)? How did you reproduce it? Is there any suspicious messages in server logs?
