### ISSUE TITLE
Misleading doc on partitioning key not speeding up queries

### ISSUE THREAD

**Issue by simPod** [ClickHouse/ClickHouse#28850]
Here https://clickhouse.tech/docs/en/engines/table-engines/mergetree-family/custom-partitioning-key/ is says that partitioning does not speed up queries:

> In most cases you don't need partition key, and in most other cases you don't need partition key more granular than by months. Partitioning does not speed up queries (in contrast to the ORDER BY expression). You should never use too granular partitioning. Don't partition your data by client identifiers or names (instead make client identifier or name the first column in the ORDER BY expression).

But here @filimonov says it does https://github.com/ClickHouse/ClickHouse/issues/2378#issuecomment-390232297

> When you use a condition which allows to read less partitions - that will be used. I.e. if you have 12 monthly partitions and you use condition where event_date = '2018-01-01' then only one partition, containing that date will be read. If you will not provide extra conditions on primary key - whole partition will be read.

I always thought providing the date into partitioning filters the data by that date so it allows to skip partitions.

Is the doc a bit misleading?

**Comment by den-crane** [comment]
>Is the doc a bit misleading?

Yes. On the purpose. To discourage newbies to use partitioning for the wrong goal.
