### ISSUE TITLE
"fire and forget" mode for `insert ... select`

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#28896]
Special setting to fire long-running `insert... select` or `create table... as select` asynchronously, without waiting query to finish. 

That waiting locks the connection, which anyway may be timeouted and the status of the result is checked in system processes / query_log.

**Comment by alexey-milovidov** [comment]
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/33919
