### ISSUE TITLE
Should we support numeric literals in form of 1_000_000? (with underscore separator of groups).

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#28967]
Pros:
- it is convenient to type and read numbers this way;
- Ada, Perl, C++, Go and Rust already support that;
- can support thousands as well as lakhs and crores;

Cons:
- standard SQL does not have this support;
- PostgreSQL treat `SELECT 1_000_000` as number one with `_000_000` alias: http://sqlfiddle.com/#!17/0a28f/400
- C++ has `1'000'000` instead of `1_000_000`;

What do you think?

**Comment by alesapin** [comment]
I'd like to have such feature... I'm always confusing number of zeros. I'd prefer to have `1'000'000` but I understand that it's impossible in SQL.

**Comment by genzgd** [comment]
being able to do an output format with a separator would be nice too.  :)

**Comment by alexey-milovidov** [comment]
Only one thumb up in 4 months.

**Comment by alexey-milovidov** [comment]
Only one thumb up in 8 months.

**Comment by alexey-milovidov** [comment]
Wow. 7 thumb-ups.

**Comment by jh0x** [comment]
Hi, I'd like to have a try on this one.

**Comment by alexey-milovidov** [comment]
@jh0x yes, you can pull the code from this pull request: https://github.com/ClickHouse/ClickHouse/pull/39129
and continue working on it to address the review comments.

**Comment by alexey-milovidov** [comment]
Congratulations, this feature from ClickHouse was added to the SQL:2023 standard!
