### ISSUE TITLE
Space is there but still getting " Cannot reserve 1.00 MiB, not enough space"

### ISSUE THREAD

**Issue by gopiather** [ClickHouse/ClickHouse#28968]
I have still 15 % of space left in the disk and also inode is not even 2 %,
but still not able to insert more records 

Getting ** Cannot reserve 1.00 MiB, not enough space**

output of df -h

```Filesystem      Size  Used Avail Use% Mounted on
overlay          26G  9.2G   17G  37% /
tmpfs            64M     0   64M   0% /dev
tmpfs            21G     0   21G   0% /sys/fs/cgroup
/dev/sda1        26G  9.2G   17G  37% /etc/hosts
shm              64M     0   64M   0% /dev/shm
/dev/sdb        984G  832G  153G  85% /var/lib/clickhouse
tmpfs            21G   12K   21G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs            21G     0   21G   0% /proc/acpi
tmpfs            21G     0   21G   0% /proc/scsi
tmpfs            21G     0   21G   0% /sys/firmware```

df -i 

overlay         1689120 88276  1600844    6% /
tmpfs           5459700    17  5459683    1% /dev
tmpfs           5459700    17  5459683    1% /sys/fs/cgroup
/dev/sda1       1689120 88276  1600844    6% /etc/hosts
shm             5459700     1  5459699    1% /dev/shm
/dev/sdb       65536000 39389 65496611    1% /var/lib/clickhouse
tmpfs           5459700     9  5459691    1% /run/secrets/kubernetes.io/serviceaccount
tmpfs           5459700     1  5459699    1% /proc/acpi
tmpfs           5459700     1  5459699    1% /proc/scsi
tmpfs           5459700     1  5459699    1% /sys/firmware

**Comment by alesapin** [comment]
Hi! Can you provide server logs where this message appeared?

**Comment by gopiather** [comment]
@alesapin We were able to fix the issue the issue. Thanks.

Need a suggestion, we want to query with a where condition on a string column with equals expression with 10 billion rows to be read.

Currently it is taking more than 3 minutes.
Can u suggest a better way for indexing the column to make it faster?

**Comment by rtkaratekid** [comment]
@gopiather what was your fix?

**Comment by alexey-milovidov** [comment]
Space can be reserved by already running merges.

**Comment by platzhersh** [comment]
@gopiather also curious about the fix.

**Comment by mendaxjerin** [comment]
@gopiather What was the fix?

**Comment by IvanProdaiko94** [comment]
@gopiather could you pls share the fix with us?

**Comment by eazow** [comment]
> Space can be reserved by already running merges.空间可以由正在运行的合并预留。

Is the reserved space related to the parameter max_bytes_to_merge_at_max_space_in_pool?
