### ISSUE TITLE
LAION-5B Open Dataset of images.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#28964]
https://laion.ai/laion-400-open-dataset/

The dataset contains 400 million of annotated 256x256 px images.

ClickHouse is never recommended to store images. That's why we need this dataset to explore and push the boundaries.
It can also be used to test executable User Defined Functions (available since version 21.11-testing) and explore how we can do machine learning inside the database.

**Comment by alexey-milovidov** [comment]
#29926

**Comment by alexey-milovidov** [comment]
Transform metadata to tsv dump:

```
for i in *.parquet; do ../../clickhouse local --input-format Parquet --structure 'SAMPLE_ID Nullable(UInt64), URL Nullable(String), TEXT Nullable(String), WIDTH Nullable(UInt32), HEIGHT Nullable(UInt32), LICENSE Nullable(String), NSFW Nullable(String), similarity Nullable(Float64)' --query 'SELECT * FROM table' < $i >> metadata.tsv; done
```

**Comment by SadiHassan** [comment]
@alexey-milovidov We can take each image as one column and write 256x256 rows of pixel values (probably with additional 3 channel values)... So, we will get 400 millions of .bin files with 256x256x3 rows. To minimize number of .bin files, beforehand, we can group similar images together and then store them in one .bin file. BTW, what is the purpose of this endeavour?

**Comment by alexey-milovidov** [comment]
@SadiHassan

> BTW, what is the purpose of this endeavour?

1. Ensure that we can store both image data and metadata in the same table - to allow getting image data and performing fast analytics on image metadata. By the way, I have already validated it in https://github.com/ClickHouse/ClickHouse/issues/18842

2. Test vector similarity search on image embeddings.

> So, we will get 400 millions of .bin files with 256x256x3 rows.

Making every image a separate column looks very strange for me. I will definitely not work.

**Comment by alexey-milovidov** [comment]
@filimonov, it's unfinished.

**Comment by alexey-milovidov** [comment]
https://github.com/LAION-AI/laion.ai/pull/40

**Comment by alexey-milovidov** [comment]
Done: https://clickhouse.com/blog/vector-search-clickhouse-p2
