### ISSUE TITLE
Does clickhouse support querying the partition table of hive? How to write the sql?

### ISSUE THREAD

**Issue by 1069355234** [ClickHouse/ClickHouse#29011]
Does clickhouse support querying the partition table of hive? How to write the sql?

The sql of the non-partitioned table I used is as follows:
`select
	*
from
	hdfs('hdfs://hive@hdfs:8020/user/hive/warehouse/xx_default.db/table/*',
	'CustomSeparated',
	'id Int32, name String, age Int32')  order by id SETTINGS format_custom_field_delimiter = '\x01',format_custom_escaping_rule='CSV';`

**Comment by Ryado** [comment]
You can use the `hive` engine in ClickHouse. This will allow to query your partitioned Hive tables transparently and effeciently from ClickHouse, I also recommend enabling `local_cache_for_remote_fs` for a better performance. Here is a simple example (assuming we have a Hive table named `zipcodes` partitioned by `state`):

```
# inserting sample data in Hive
INSERT INTO zipcodes PARTITION (state='IDF') VALUES (1, 'FR', 'Paris', 75000);
INSERT INTO zipcodes PARTITION (state='IDF') VALUES (2, 'FR', 'Yvelines', 78000);
INSERT INTO zipcodes PARTITION (state='BDR') VALUES (3, 'FR', 'Marseille', 13000);

# creating a ClickHouse tables with the Hive integration
CREATE TABLE default.zipcodes
(
  `recordnumber` UInt32,
  `country` String,
  `city` String,
  `zipcode` UInt32,
  `state` String
)
ENGINE = Hive('thrift://X.X.X.X:9083', 'default', 'zipcodes')
PARTITION BY state;

SELECT * FROM default.zipcodes;

```

The following [documentation page](https://clickhouse.com/docs/en/engines/table-engines/integrations/hive/) contains more detailed examples.
