### ISSUE TITLE
Invalid argument: Missing port number

### ISSUE THREAD

**Issue by jiangjiguang** [ClickHouse/ClickHouse#29032]
when one thread write data to clickhouse, it succeed.
But when two thread write data to clickhouse, there is the error:
com.github.housepower.jdbc.ClickHouseSQLException: DB::ExceptionDB::Exception: Invalid argument: Missing port number. Stack trace:

0. Poco::Net::SocketAddress::init(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x125189b7 in /usr/bin/clickhouse
1. DB::ClientInfo::read(DB::ReadBuffer&, unsigned long) @ 0xefa1bc0 in /usr/bin/clickhouse
2. DB::TCPHandler::receiveQuery() @ 0xfea0f0b in /usr/bin/clickhouse
3. DB::TCPHandler::receivePacket() @ 0xfe98267 in /usr/bin/clickhouse
4. DB::TCPHandler::runImpl() @ 0xfe90b0a in /usr/bin/clickhouse
5. DB::TCPHandler::run() @ 0xfea3bb9 in /usr/bin/clickhouse
6. Poco::Net::TCPServerConnection::start() @ 0x12522d2f in /usr/bin/clickhouse
7. Poco::Net::TCPServerDispatcher::run() @ 0x125247ba in /usr/bin/clickhouse
8. Poco::PooledThread::run() @ 0x1265d8d9 in /usr/bin/clickhouse
9. Poco::ThreadImpl::runnableEntry(void*) @ 0x126598ca in /usr/bin/clickhouse
10. start_thread @ 0x76db in /lib/x86_64-linux-gnu/libpthread-2.27.so
11. __clone @ 0x12171f in /lib/x86_64-linux-gnu/libc-2.27.so

**Comment by jiangjiguang** [comment]
clickhouse version is 21.5.9.4

**Comment by den-crane** [comment]
We do not support jdbc drivers here. Ask https://github.com/housepower/ClickHouse-Native-JDBC/issues
