### ISSUE TITLE
hive data to ClickHouse is wrong on type timestamp(hive) to DateTime/DateTime64(ClickHouse)

### ISSUE THREAD

**Issue by aaawuanjun** [ClickHouse/ClickHouse#29040]
# create hive table, data is stored on hdfs

> create table if not exists olap_hive2clickhouse_sample5(
>     user_key INT COMMENT '表的主键，用户的唯一标识',
>     user_time TIMESTAMP COMMENT '用户的创建日期'
> )partitioned by (dt STRING, hr STRING)
> stored as ORC;

# insert some data to hive table

> insert overwrite table olap_hive2clickhouse_sample5 partition(dt='2021-01-01',hr='01') values(1,"2021-06-15T03:33:29.123+08:00");
> insert overwrite table olap_hive2clickhouse_sample5 partition(dt='2021-01-01',hr='02') values(2,"2021-06-16T03:33:29.345+08:00");

# data on hive is below
![image](https://user-images.githubusercontent.com/35732071/133408424-16d1160f-6303-420e-ad38-25699132bf92.png)
# create hdfs engine table on ClickHouse

> CREATE TABLE IF NOT EXISTS olap_hive2clickhouse_sample5102 (
> 	`user_key` Nullable(Int32) COMMENT '表的主键，用户的唯一标识',
> 	`user_time` DateTime64(3, 'Asia/Singapore') COMMENT '用户的创建日期'
> ) ENGINE = HDFS('hdfs://testcluster01/hive_warehouse/test.db/olap_hive2clickhouse_sample5/dt=2021-01-01/hr=*/*', 'ORC')

# data on ClickHouse
![image](https://user-images.githubusercontent.com/35732071/133409163-28b16fae-af54-4644-a49e-361eced874ee.png)

# Problems
 the ms is "000"

**Comment by den-crane** [comment]
You can use Int64 in ENGINE = HDFS
And convert Int64 to DateTime64(3) using fromUnixTimestamp64Milli  https://clickhouse.tech/docs/en/sql-reference/functions/type-conversion-functions/#fromunixtimestamp64milli

duplicate for https://github.com/ClickHouse/ClickHouse/issues/28574
