### ISSUE TITLE
Select query very slow

### ISSUE THREAD

**Issue by gopiather** [ClickHouse/ClickHouse#29056]
I am trying to query with where condition on a string column with equal expression.
It seems very slow.. I am querying for  a day (table partitioned by day which is very fast).
But adding a where condition for a string column make the query very slow. Taking more than 5 mins for the response time.
Which has data around 10 billion rows.

I did an indexing - INDEX <name> <string_column_name> TYPE set(1000) GRANULARITY 8132

Query example - select * from RawEvent where <column_name> = '<value>' and toYYYYMMDD(ts) = 20210910

Is this indexing seems ok? Or need suggestions for better indexing on this particular string column to make query atleast 10x faster..

**Comment by den-crane** [comment]
You should not use `GRANULARITY 8132` , expected here 1 or 3.  `GRANULARITY 3`
`TYPE set(1000)` -- I think it's a wrong type of index in your case, try bloom_filter


----
GRANULARITY of the skip another granularity.
table granule = 8192 rows by default -- how many rows will be addressed by a single primary key entry.
Primary key is sparse.
skip index GRANULARITY -- how many table granules include into skip index record.
usually skip index GRANULARITY = 1 or 2 (sometimes 5)
https://stackoverflow.com/questions/60255863/how-understand-the-granularity-and-block-in-clickhouse/60271529#60271529
https://github.com/ClickHouse/ClickHouse/issues/15835#issuecomment-706711503
----

**Comment by alexey-milovidov** [comment]
`set(1000)` may be too much for a String column.
Better to use index of bloom filter type.

Maybe your index is not beneficial at all - then remove it.
