### ISSUE TITLE
table_name contains dot that cause to serious error!

### ISSUE THREAD

**Issue by cantfu** [ClickHouse/ClickHouse#29066]
Before upgrading clickhouse 21.3 which support atomic database, we have many tables which table name contain dot, like `qry_c4e0ac23.cus_name`, it cause to server crash and could not restart ch any more after this upgrade.

The format of  `database_name.table_name.uuid.sql` does not match our case `database_name.xxx.xxx.uuid.sql`, so ch got a error uuid.
Could you guys give me a solution? I think it could be supported because it is allowed to create table which contains dot inside table name.

attach the error stack:
```ssh
<Error> Application: Caught exception while loading metadata: Code: 376, e.displayText() = DB::ParsingException: Cannot parse uuid cus_name, Stack trace (when copying this message, always include the lines below):

0. std::exception::capture() @ 0x96f3306 in
1. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xfcab90b in
2. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x96e86ad in
3. DB::ParsingException::ParsingException(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x96ead63 in
4. void DB::readUUIDTextImpl<void>(StrongTypedef<DB::UInt128, DB::UUIDTag>&, DB::ReadBuffer&) @ 0x9722dc4 in
5. DB::DatabaseCatalog::loadMarkedAsDroppedTables() @ 0xe089f30 in
6. DB::DatabaseCatalog::loadDatabases() @ 0xe089870 in
7. DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x97344eb in
8. Poco::Util::Application::run() @ 0xfc5831b in
9. DB::Server::run() @ 0x972d964 in
10. mainEntryClickHouseServer(int, char**) @ 0x972cabc in
11. main @ 0x96e737d in
12. __libc_start_main @ 0x22445 in /usr/lib64/libc-2.17.so
13. _start @ 0x96e6ea9 in
```

**Comment by IVitamin-C** [comment]
use `db`.`tablename`

**Comment by cantfu** [comment]
We saw there are a fixed format `database_name.table_name.uuid.sql` in DatabaseCatalog::loadMarkedAsDroppedTables(), if we  change the way to parse uuid, it could be work, but i dunno any other codes need to change.

Looking forward to your answers, thanks.

**Comment by tavplubix** [comment]
How did you get dot in `*.sql` file name? Table names are [escaped](https://github.com/ClickHouse/ClickHouse/blob/7bea8200d80b24022c285b252258805a5427e3d2/src/Interpreters/DatabaseCatalog.cpp#L754) for metadata file names, so dot is replaced with `"%2E"`. Also we have dots in default name of [materialized view target table](https://github.com/ClickHouse/ClickHouse/blob/8e9aacadd1b5b1e8daab267ab9e7a3ae500a4e98/src/Storages/StorageMaterializedView.cpp#L45-L46) and it works fine. 

Could you please show output of `ls -al /var/lib/clickhouse/metadata_dropped/`?

**Comment by cantfu** [comment]
> Table names are escaped for metadata file names, so dot is replaced with "%2E"

Ohh, that's right. Because we want to keep unescaped tablename as folder name, so we did some changes, that's the root cause. Thanks.
So, there is no way to keep  unescaped tablename as folder name?

**Comment by cantfu** [comment]
> Table names are escaped for metadata file names, so dot is replaced with "%2E"

ohh, that's right. Because we want to keep unescaped tablename as folder name, so we did some changes, that's the root cause. Thanks.
So, there is no way to keep  unescaped tablename as folder name?

**Comment by tavplubix** [comment]
> So, there is no way to keep unescaped tablename as folder name?

No, table name can contain slash, so we have to escape `/` at least. You can try custom escaping rules (and escape slashes only, for example), but you have to deal with all possible issues by yourself.
