### ISSUE TITLE
Add Maglev consistent hash as SQL function.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#29064]
**Use case**

Make it available along with the existing `yandexConsistentHash` and `jumpConsistentHash`.
To experiment with it before integrating to #26748 for better cache affinity in #28961.

**Describe the solution you'd like**

Example implementation is available in Envoy Proxy:
https://github.com/envoyproxy/envoy/blob/master/source/common/upstream/maglev_lb.h
https://github.com/envoyproxy/envoy/blob/master/source/common/upstream/maglev_lb.cc

See:
https://blog.acolyer.org/2016/03/21/maglev-a-fast-and-reliable-software-network-load-balancer/

**Comment by ucasfl** [comment]
Hi, I want to do this.

**Comment by alexey-milovidov** [comment]
:+1: Thank you!

**Comment by ucasfl** [comment]
But I'm a little cofusing about the implementation, for other consistent hash, like jumpConsistentHash, we just need to calcuate a hash value according to input and bucket number. while for this, the build method of lookup table is somehow different.

**Comment by alexey-milovidov** [comment]
Some options:
- build this table in FunctionBuilder, so it will be reused in subsequent invocations in the same query, but different queries will build it again;
- pregenerate a table for some common use case?

(I did not have a time to look into details, maybe I miss something)

**Comment by ucasfl** [comment]
The key of the hash algorithm is build lookup table, it guarantees that there are nodes in every position of the lookup table.
