### ISSUE TITLE
AggregatingMergeTree and SummingMergeTree, avoid duplicate rows

### ISSUE THREAD

**Issue by Lucgarg** [ClickHouse/ClickHouse#29098]
Hello, I am building a table, keeping in mind that it uses as little disk space as possible. 

So I would like to insert directly into my table with one of the engines that I mention in the title, the data from an external application, but of course, if I don't use an engine like replacingmergetree or collapsemergetree the duplicate rows are not eliminated.

 What would be the best way to save the data in a summingmergetree or aggreatingmergetree type table and avoid duplicate data and not try not to increase the disk space too much? 

Well, I understand that in the case of Summergetree and aggregatemerge tree, the aggregations will be made with duplicate data as well, so they will not be reliable

**Comment by den-crane** [comment]
The only way is to negate previous state.
You inserted into SummingMergeTree +10, then negate -10, then new value +25.
But obviously you need to store (id, old_value) somewhere (not in CH).
