### ISSUE TITLE
disk & storage_policy sql-driven workflow

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#29110]
**Use case**

Ability to quickly add datasets from remote filesystems without dealing with xml config files.

**Describe the solution you'd like**

Give ability to define disks and storage policies via SQL queries, it will be especially useful for remote disks (s3, hdfs, web) and wrapper disks (encrypted, cache)

```
CREATE STORAGE POLICY s3_infrequent_access VOLUME s3 (DISK s3 (s3_credentials, tier='infrequeant_access', type ='archive'))
```

Like https://postgrespro.com/docs/enterprise/13/sql-createtablespace

**Comment by alexey-milovidov** [comment]
That's dangerous.

**Comment by UnamedRus** [comment]
More dangerous adhoc disks already exist
