### ISSUE TITLE
How to use post submission of URL function?

### ISSUE THREAD

**Issue by linqingping** [ClickHouse/ClickHouse#29125]
URL — HTTP or HTTPS server address, which can accept GET or POST requests (for SELECT or INSERT queries correspondingly).

How to use POST submission of URL function?
Does anyone have any examples？

Case default GET request
```
SELECT * FROM url('http://127.0.0.1:12345/', CSV, 'column1 String, column2 UInt32') LIMIT 3;
```

**Comment by anmolarora** [comment]
Since inserts are automatically sent to the POST endpoint. You can create a table and then insert.
```
CREATE TABLE test AS url('http://127.0.0.1:12345/', CSV, 'column1 String, column2 UInt32');


INSERT INTO test (*) VALUES ('John doe', 123);

SELECT * FROM test;
```

**Comment by kssenii** [comment]
> You can create a table and then insert.

btw you can also do `INSERT INTO TABLE FUNCTION url('http://127.0.0.1:12345/', CSV, 'column1 String, column2 UInt32')`

**Comment by linqingping** [comment]
Thank you for your  @kssenii @anmolarora 
Can't query the post interface only with select?

curl -X POST "http://127.0.0.1:12345/test?keyword=test" 
select * from url('http://127.0.0.1:12345/test?keyword=test',csv,'cloumn1 string')

**Comment by kssenii** [comment]
No, select is only GET, insert is only POST.

**Comment by linqingping** [comment]
OK, I see. Thank you@kssenii

**Comment by amosbird** [comment]
> insert is only POST

It may be interesting to have INSERT returning records so that we can do POST)

**Comment by alexey-milovidov** [comment]
@amosbird Is it about using `url` table function similarly to the new-born `executable` table function to perform arbitrary transformations on data? Sounds nice :)
