### ISSUE TITLE
How to rebalance data in clickhouse cluster after adding new nodes

### ISSUE THREAD

**Issue by abhilash-radhakrishnaru** [ClickHouse/ClickHouse#29124]
I could find a lot of documentation on how to setup clickhouse cluster; but none on expanding existing cluster and rebalance data. Can someone help me with pointers on the same. Is there any best practices on this from clickhouse?

**Comment by den-crane** [comment]
There is no good and easy solution. 
Moreover there is no way magically extract part of rows from old shards and move them to the new.

You can define the new shard with bigger weight then this shard will get more data and eventually all shard became even. 

If you need row-level resharding you can only reinsert data. (by any tool: inset / select ; clickhouse-copier ...)
If you don't you can detach some old part from the old shards and copy them to the new nodes and attach them there.
