### ISSUE TITLE
Incorrect work of join_use_nulls

### ISSUE THREAD

**Issue by Fallenyasha** [ClickHouse/ClickHouse#29151]
Проверено в двух версиях КХ, запрос следующий

select toTypeName(
    (select b from
        (select 0 as a) as q1
        any left join
        (select 0 as a, 0 as b) as q2 using a
    ) as v) as type;

19.4.5.1
при join_use_nulls = 0 результат UInt8
при join_use_nulls = 1 результат Nullable(UInt8)

21.9.2.17
при join_use_nulls = 0 результат Nullable(UInt8)
при join_use_nulls = 1 результат Nullable(UInt8)

Согласно документации, получается что поведение в 19.4.5.1 было корректным.
От типа join-а не зависит, от типа данных колонок a и b не зависит.
Проверялось и на выборке данных из реальных таблиц, тип данных колонок в подзапросах не нулабл, после джоина становится нулабл.

Вот пример реального запроса
SELECT string_value is null FROM
(SELECT 0 AS key) AS a
ALL LEFT JOIN
(SELECT 0 AS key, string_value FROM temporary._70ADB78A WHERE 0 = 1) AS b
USING key

**Comment by den-crane** [comment]
никаго отношения к join_use_nulls. Подзапрос возвращает nullable

```sql
18.14.19

select (select 1) x, toTypeName(x)
┌─x─┬─toTypeName(CAST(1, 'UInt8'))─┐
│ 1 │ UInt8                        │
└───┴──────────────────────────────┘

21.8.4.51
select (select 1) x, toTypeName(x)
┌─x─┬─toTypeName(x)───┐
│ 1 │ Nullable(UInt8) │
└───┴─────────────────┘
```

join_use_nulls работает коректно

```sql
18.14.19
desc (
select b from (select 0 as a) as q1 any left join (select 0 as a, 0 as b) as q2 using a
);
┌─name─┬─type──┬─default_type─┬─default_expression─┐
│ b    │ UInt8 │              │                    │
└──────┴───────┴──────────────┴────────────────────┘

21.8.4.51

desc (
select b from (select 0 as a) as q1 any left join (select 0 as a, 0 as b) as q2 using a
);
┌─name─┬─type──┬─default_type─┬─default_expression─┬─comment─┬─codec_expression─┬─ttl_expression─┐
│ b    │ UInt8 │              │                    │         │                  │                │
└──────┴───────┴──────────────┴────────────────────┴─────────┴──────────────────┴────────────────┘

desc (
select b from (select 0 as a) as q1 any left join (select 0 as a, 0 as b) as q2 using a settings join_use_nulls=1
);
┌─name─┬─type────────────┬─default_type─┬─default_expression─┬─comment─┬─codec_expression─┬─ttl_expression─┐
│ b    │ Nullable(UInt8) │              │                    │         │                  │                │
└──────┴─────────────────┴──────────────┴────────────────────┴─────────┴──────────────────┴────────────────┘
```

**Comment by Fallenyasha** [comment]
Да, согласен, где-то ошибся в проверке, но тогда вопрос, почему в разных версиях КХ запрос select toTypeName((select 0 as a)) возвращает разные значения и как их привести к единообразию?

**Comment by alexey-milovidov** [comment]
In new versions, subquery result was changed to Nullable.
See the changelog for 21.9: https://github.com/ClickHouse/ClickHouse/blob/master/CHANGELOG.md#backward-incompatible-change

**Comment by WesleyBatista** [comment]
@alexey-milovidov I suspect the issue is still around. 

```
$ docker run -d --name some-clickhouse-server yandex/clickhouse-server:21.9
$ docker run -it --rm --link some-clickhouse-server:clickhouse-server yandex/clickhouse-client:21.9 --host clickhouse-server -nm
```
query:
```
with fruit AS (
    SELECT 1 AS id
),
vegetables AS(
    SELECT 2 AS id
)
select
 COALESCE(f.id,v.id) AS id
from fruit f
full outer join vegetables v on f.id = v.id;
```

In postgres we will get a result of
```
1
2
```
but in clickhouse we get
```
1
0
```
What should be expected here?

appending `settings join_use_nulls=1` to the query "fixes" the behaviour.

**Comment by den-crane** [comment]
>What should be expected here?

Yes. It's expected.

>appending settings join_use_nulls=1 to the query "fixes" the behaviour.

Yes. join_use_nulls is exactly for this purpose. You can set join_use_nulls =1 for all users by default in your environment.
Most of users don't need join_use_nulls and it's =0 because it gives bigger performance.
