### ISSUE TITLE
CSV parsing failure in case of nested double quotes

### ISSUE THREAD

**Issue by sogawa-sps** [ClickHouse/ClickHouse#29178]
**Describe what's wrong**
CSV parsing fails if there are nested double quotes.

**Does it reproduce on recent release?**
Yes

**How to reproduce**
Table:
```
CREATE TABLE test.test
(
    `id` Int,
    `task` String,
    `hours` Float32
)
ENGINE = MergeTree()
PRIMARY KEY id
ORDER BY id
```

File:
`1,"Build - '"Products'" tab",1`

Import:
`clickhouse-client --query "INSERT INTO test.test FORMAT CSV" < /mnt/c/temp/test.csv`

**Expected behavior**
Import processed successfully. Parser is able to identify nested double quotes.

**Error message and/or stacktrace**
```
Code: 27. DB::Exception: Cannot parse input: expected , before: Products\'" tab",1: (at row 1)

Row 1:
Column 0,   name: id,    type: Int32,   parsed text: "1"
Column 1,   name: task,  type: String,  parsed text: "<DOUBLE QUOTE>Build - <SINGLE QUOTE><DOUBLE QUOTE>"
ERROR: There is no delimiter (,). "P" found instead.
```

**Additional context**
OS: Windows
Version: 21.9.3.30
Server: Docker over WSL2
CLI: Ubuntu over WSL2

**Comment by alexey-milovidov** [comment]
CSV does not support nested quotes without proper escaping and there is no theoretical way to implement this support.

Example:

Suppose we have a table with two fields: `a String, b String` and a CSV data:
```
"Hello","World","Goodbye"
```

Then it can be parsed as:

`"Hello","World"`, `"Goodbye"`
or
`"Hello"`, `"World","Goodbye"`

**Comment by sogawa-sps** [comment]
@alexey-milovidov thank you for you answer but it I think it's totally valid case if there are no commas inside. For example PostgreSQL processes such a file correctly. And OpenCSV is also able to properly parse such a file.

Actually it was an export from PostgreSQL. I tried to migrate my data from it to ClickHouse and it failed so I can't start working with this DB. PostgreSQL can ingest it back properly.

**Comment by den-crane** [comment]
@sogawa-sps Clickhouse does not support this escaping. There is no strict standard for CSV escaping. Clickhouse has own datatypes and own rules for escaping.

You can use `"Build - ""Products"" tab"`  or `'Build - "Products" tab'`.

**Comment by den-crane** [comment]
``` psql > \copy (select 'Build - "Products" tab' x) to 'temp.csv' with csv ;

$ cat temp.csv
"Build - ""Products"" tab"
```

**Comment by sogawa-sps** [comment]
Thank you @den-crane, will try.
