### ISSUE TITLE
UBSan report in partial merge JOIN

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#29177]
**Describe the bug**
https://clickhouse-test-reports.s3.yandex.net/0/81de25d37f4a83fd6c0d8dcfd400606dfb6a4a06/fuzzer_ubsan/report.html

**How to reproduce**
```
SELECT count(NULL) = 9223372036854775806 FROM (SELECT count([NULL, NULL, '655.36', NULL, 7, -2147483647, NULL]) = NULL, [65537], [NULL, 0]) AS js1 ALL RIGHT JOIN (SELECT NULL, NULL, (NULL, NULL, NULL, NULL, NULL, 2., NULL), number AS s FROM numbers(65535)) AS js2 USING (s)
```

`Changed settings: max_block_size = '6', receive_timeout = '10', receive_data_timeout_ms = '10000', join_algorithm = 'partial_merge', memory_profiler_step = '1000000', allow_introspection_functions = '1', transform_null_in = '1'`

**Comment by vdimir** [comment]
Same issue as https://github.com/ClickHouse/ClickHouse/issues/28660, will be fixed with https://github.com/ClickHouse/ClickHouse/pull/28982
