### ISSUE TITLE
Can't import large files to server running under docker: "Broken pipe, while writing to socket"

### ISSUE THREAD

**Issue by sogawa-sps** [ClickHouse/ClickHouse#29181]
I've started ClickHouse server as a docker container on my Windows machine:

`docker run --restart always -d --name ch --ulimit nofile=262144:262144 -p 8123:8123 -p 9000:9000 -p 9009:9009 --volume=/e/ClickHouse:/var/lib/clickhouse yandex/clickhouse-server`

Then I've opened an Ubuntu session (over WSL2)  and tried to import the data (2.1G csv file):

`clickhouse-client --query "INSERT INTO test.time_test FORMAT CSV" --max_insert_block_size=100000 < /mnt/e/temp/time_test.csv`

But it failed:
`Code: 210. DB::NetException: I/O error: Broken pipe, while writing to socket (127.0.0.1:9000)`

It reproduces for any file large enough. Tiny files are imported fine. Any ideas what could went wrong and how to diagnose it?

OS: Windows 10
ClickHouse version: 21.9.3.30
ClickHouse client version: 18.16.1
Docker Desktop: 20.10.8 (over WSL2)

**Comment by den-crane** [comment]
18.16.1 is out of support.
Most probably CH server restart because of lack of memory.
Check `/var/log/clickhouse-server/clickhouse-server.log` for more info.

**Comment by sogawa-sps** [comment]
Looks like it was an issue with the client indeed. It came from official Ubuntu rep, I've updated it using ClickHouse's repository and now everything works fine. Thank you!
