### ISSUE TITLE
ClickHouse server not running because Build didn't include NuRaft library

### ISSUE THREAD

**Issue by SadiHassan** [ClickHouse/ClickHouse#29221]
**ClickHouse Version**  21.3
**tag**  v21.3.8.76-lts 
**Operating system** MacOS BigSur 11.5.2

**Cmake version**  3.21.2

**Ninja version**  1.10.2

**Compiler name and version**  clang
Apple clang version 12.0.5 (clang-1205.0.22.11)
Target: x86_64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Full cmake and/or ninja output**
<Error> Application: DB::Exception: ClickHouse server built without NuRaft library. Cannot use internal coordination.

**Comment by alesapin** [comment]
This error can be thrown only in case when you have specified `<keeper_server>` configuration in your config, but server built without NuRaft (https://github.com/ClickHouse/ClickHouse/blob/a73064679dc77a7c35111da87ded9a8f9d38cf72/programs/server/Server.cpp#L978-L1022). So it's misconfiguration, not the build issue.

**Comment by SadiHassan** [comment]
@alesapin I did not change anything in the config file. FYI, the code was cloned from tag v21.3.8.76-lts. If the config was specified `<keep_server>`, can you instruct what value should be there, which file and where need to be changed? Thanks!

**Comment by alexey-milovidov** [comment]
Simply remove the `<keeper_server>` section.

**Comment by alesapin** [comment]
I'll close the issue, reopen if you have any other questions on this topic.
