### ISSUE TITLE
[RFC] Access Apache Hive from clickhouse

### ISSUE THREAD

**Issue by zhanglistar** [ClickHouse/ClickHouse#29245]
**Use case**
Actually, apache hive(hive) is data warehouse for many companies because of its stablity, scalability and completeness, but it is slow, so presto and impala are developed on it to meet the OLAP need. 
Clickhouse is prestty fast OLAP system and widely used. There are both hive and clickhosue in many companies. 
But there are many problems because of totally independence of the two systems:
firstly, we need to maintain data pipeline from hive to clickhouse.
secondly, waste money, data need to be saved 4 or 6 replicas in hive and clickhouse.
thirdly, scaling out is not easy for clickhouse and brings high operation overload. Seperating the storage and computing node is easy to scale and operation.
We should let clickhouse to support reading access(maybe write in the future) hive like presto and impala to tackle the problems.

**Describe the solution you'd like**
We want to impletement the idea as the following steps:
1. import thrift to clickhouse and the hive storage which is a proxy to hive using hive thrift protocol.
2. support reading apache orc and parquet, csv format from hdfs using native library libhdfspp.
3. impelement the distributed reading using the remote executor mechanism.
4. support hive syntax using antlr c++ library, first parse the sql into inner ast of clickhouse, and using the interpreter to get the result.
5. user defined function support that clickhosue missing comparing to hive.
6. shuffle join to support large datasets join.

**Describe alternatives you've considered**
We need to do lots of performance optimization for remote reading from hive, mainly hive meta store(hms) and hdfs.
1. long connection to hdfs namennode and reuse it to get metadata for filesystem, and we may also cache them in clickhouse.
2. metadata cache from hms of table schema, partition keys and partition info.
3. local data cache from hdfs, likee alluxion local cache with presto, also in the rfc https://github.com/ClickHouse/ClickHouse/issues/28961
4. partition pruning and min-max index optimizations to reduce io cost.

**The progress**
In BIGO, we now have develop the future that we can read data from single clickhouse node, and doing the rest. We should contribute the code back to clickhosue in the future when maybe do the major things on hive. We need advices about it. 
Thanks for your review.

**Comment by rogerlzp** [comment]
this would be another good feature that could help lots of people

**Comment by zhanglistar** [comment]
https://github.com/ClickHouse/ClickHouse/pull/31104
