### ISSUE TITLE
Error while executing materialize projection

### ISSUE THREAD

**Issue by chrootweili** [ClickHouse/ClickHouse#29253]
Clickhouse version: 21.8.4.51 (official build)

**Error while executing mutations ``` alter table tbl MATERIALIZE PROJECTION proj_some_name```**
> Code: 49, e.displayText() = DB::Exception: Number of rows in source parts (2873190) differs from number of bytes written to rows_sources file (957730). It is a bug. (version 21.8.4.51 (official build))

**Comment by amosbird** [comment]
Could you try building a minimal test case that can reproduce this issue?

**Comment by chrootweili** [comment]
> Could you try building a minimal test case that can reproduce this issue?

I can't build this case shortly.

I guess it's because some columns was added by `alter table` after reading the clickhouse debug log.

**Comment by chrootweili** [comment]
Number of rows in source parts = 2873190
Number of bytes written to rows_sources file = 957730

2873190 / 957730 = 3

I've checked other cases, number of rows in source parts = (2 or 3) * number of bytes written to rows_sources file

**Comment by degrees-273** [comment]
I also encountered the same problem. 
Version 21.7.2.7. 
And the test is related to the number of columns selected when creating the projection. For example, there is no error when selecting 9 columns, and an error is reported when 10 columns are selected. The following is my error message:

2021.09.24 18:39:38.929089 [ 24846 ] {} <Error> default.test_table (1ad0fbe3-b86d-4c91-9ad0-fbe3b86d1c91): Cannot quickly remove directory /data/clickhouse/data/store/1ad/1ad0fbe3-b86d-4c91-9ad0-fbe3b86d1c91/delete_tmp_201910_419_493_1_786 by removing files; fallback to recursive removal. Reason: Code: 458, e.displayText() = DB::ErrnoException: Cannot unlink file /data/clickhouse/data/store/1ad/1ad0fbe3-b86d-4c91-9ad0-fbe3b86d1c91/delete_tmp_201910_419_493_1_786/checksums.txt, errno: 2, strerror: No such file or directory (version 21.7.2.7 (official build))
2021.09.24 18:39:38.929890 [ 24846 ] {} <Debug> MemoryTracker: Peak memory usage: 67.58 MiB.
2021.09.24 18:39:38.929965 [ 24846 ] {} <Error> auto DB::IBackgroundJobExecutor::jobExecutingTask()::(anonymous class)::operator()() const: Code: 49, e.displayText() = DB::Exception: Number of rows in source parts (376832) differs from number of bytes written to rows_sources file (188416). It is a bug., Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x8d35c1a in /usr/bin/clickhouse
1. DB::MergeTreeDataMergerMutator::mergePartsToTemporaryPart(DB::FutureMergedMutatedPart const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::BackgroundProcessListEntry<DB::MergeListElement, DB::MergeInfo>&, std::__1::shared_ptr<DB::RWLockImpl::LockHolderImpl>&, long, std::__1::shared_ptr<DB::Context const>, std::__1::unique_ptr<DB::IReservation, std::__1::default_delete<DB::IReservation> > const&, bool, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, DB::MergeTreeData::MergingParams const&, DB::IMergeTreeDataPart const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x103f63d7 in /usr/bin/clickhouse
2. DB::MergeTreeDataMergerMutator::writeWithProjections(std::__1::shared_ptr<DB::IMergeTreeDataPart>, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeProjection const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeProjection const> > > const&, std::__1::shared_ptr<DB::IBlockInputStream>, DB::IMergedBlockOutputStream&, long, DB::BackgroundProcessListEntry<DB::MergeListElement, DB::MergeInfo>&, std::__1::unique_ptr<DB::IReservation, std::__1::default_delete<DB::IReservation> > const&, std::__1::shared_ptr<DB::RWLockImpl::LockHolderImpl>&, std::__1::shared_ptr<DB::Context const>, DB::IMergeTreeDataPart::MinMaxIndex*) @ 0x1040dbfb in /usr/bin/clickhouse
3. DB::MergeTreeDataMergerMutator::mutateSomePartColumns(std::__1::shared_ptr<DB::IMergeTreeDataPart const> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::set<std::__1::shared_ptr<DB::IMergeTreeIndex const>, std::__1::less<std::__1::shared_ptr<DB::IMergeTreeIndex const> >, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeIndex const> > > const&, std::__1::set<std::__1::shared_ptr<DB::IMergeTreeProjection const>, std::__1::less<std::__1::shared_ptr<DB::IMergeTreeProjection const> >, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeProjection const> > > const&, DB::Block const&, std::__1::shared_ptr<DB::IMergeTreeDataPart>, std::__1::shared_ptr<DB::IBlockInputStream>, long, std::__1::shared_ptr<DB::ICompressionCodec> const&, DB::BackgroundProcessListEntry<DB::MergeListElement, DB::MergeInfo>&, bool, bool, std::__1::unique_ptr<DB::IReservation, std::__1::default_delete<DB::IReservation> > const&, std::__1::shared_ptr<DB::RWLockImpl::LockHolderImpl>&, std::__1::shared_ptr<DB::Context const>) @ 0x10403fcc in /usr/bin/clickhouse
4. DB::MergeTreeDataMergerMutator::mutatePartToTemporaryPart(DB::FutureMergedMutatedPart const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::MutationCommands const&, DB::BackgroundProcessListEntry<DB::MergeListElement, DB::MergeInfo>&, long, std::__1::shared_ptr<DB::Context const>, std::__1::unique_ptr<DB::IReservation, std::__1::default_delete<DB::IReservation> > const&, std::__1::shared_ptr<DB::RWLockImpl::LockHolderImpl>&) @ 0x103fc06b in /usr/bin/clickhouse
5. DB::StorageMergeTree::mutateSelectedPart(std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::StorageMergeTree::MergeMutateSelectedEntry&, std::__1::shared_ptr<DB::RWLockImpl::LockHolderImpl>&) @ 0x100d1642 in /usr/bin/clickhouse
6. ? @ 0x100e19d8 in /usr/bin/clickhouse
7. ? @ 0x10316257 in /usr/bin/clickhouse
8. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0x8d797f8 in /usr/bin/clickhouse
9. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()&&...)::'lambda'()::operator()() @ 0x8d7b39f in /usr/bin/clickhouse
10. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x8d76adf in /usr/bin/clickhouse
11. ? @ 0x8d7a3c3 in /usr/bin/clickhouse
12. start_thread @ 0x7dd5 in /usr/lib64/libpthread-2.17.so
13. clone @ 0xfe02d in /usr/lib64/libc-2.17.so
 (version 21.7.2.7 (official build))

**Comment by degrees-273** [comment]
Operating procedures:

CREATE TABLE default.test_table
(
    `c1` Int64 DEFAULT '0',
    `c2` String DEFAULT '',
    `c3` DateTime DEFAULT '1970-01-01 08:00:00',
    `c4` Int8 DEFAULT '0',
    `c5` String DEFAULT '',
    `c6` String DEFAULT '',
    `c7` String DEFAULT '',
    `c8` String DEFAULT '',
    `c9` String DEFAULT '',
    `c10` String DEFAULT '',
    `c11` String DEFAULT '',
    `c12` String DEFAULT '',
    `c13` Int8 DEFAULT '0',
    `c14` Int64 DEFAULT '0',
    `c15` String DEFAULT '',
    `c16` String DEFAULT '',
    `c17` String DEFAULT '',
    `c18` Int64 DEFAULT '0',
    `c19` Int64 DEFAULT '0',
    `c20` Int64 DEFAULT '0',
    `c21` Int64 DEFAULT '0',
    `c22` Int64 DEFAULT '0',
    `c23` String DEFAULT '',
    `c24` String DEFAULT '',
    `c25` String DEFAULT '',
    `c26` String DEFAULT '',
    `c27` String DEFAULT '',
    `c28` Int32 DEFAULT '0',
    `c29` Int8 DEFAULT '0',
    `c30` DateTime DEFAULT '1970-01-01 08:00:00',
    `c31` DateTime DEFAULT '1970-01-01 08:00:00',
    `c32` Decimal(16, 4) DEFAULT '0.00',
    `c33` Decimal(16, 4) DEFAULT '0.00',
    `c34` DateTime DEFAULT '1970-01-01 08:00:00',
    `c35` DateTime DEFAULT now(),
    `c36` DateTime DEFAULT now(),
    `c37` Int32 DEFAULT '0',
    `c38` Int8 DEFAULT '0',
    `c39` Int8 DEFAULT '0',
    `c40` String DEFAULT '',
    `c41` String DEFAULT '',
    `c42` Int32 DEFAULT '0',
    `c43` DateTime DEFAULT '1970-08-01 08:00:00',
    `c44` Int64 DEFAULT '0',
    `c45` String DEFAULT '',
    `c46` Decimal(16, 4) DEFAULT '0.00',
    `c47` Decimal(16, 4) DEFAULT '0.00',
    `c48` String DEFAULT '',
    `c49` Int8 DEFAULT '0',
    `c50` Int32 DEFAULT '0',
    `c51` DateTime DEFAULT '1970-01-01 08:00:00',
    `c52` Int8 DEFAULT '0',
    `c53` Int8 DEFAULT '0',
    `c54` Int32 DEFAULT '0',
    `c55` Int8 DEFAULT '0',
    `c56` DateTime DEFAULT '1970-01-01 08:00:00',
    `c57` Int8 DEFAULT '0',
    `c58` Int8 DEFAULT '0',
    `c59` Int64 DEFAULT '0',
    `c60` Int8 DEFAULT '0',
    `c61` Int8 DEFAULT '0',
    `c62` Int8 DEFAULT '0',
    `c63` Int8 DEFAULT '0',
    `c64` Decimal(16, 4) DEFAULT '0.00',
    `c65` Decimal(16, 4) DEFAULT '0.00',
    `c66` Decimal(16, 4) DEFAULT '0.00',
    `c67` Decimal(16, 4) DEFAULT '0.00',
    `c68` Decimal(16, 4) DEFAULT '0.00',
    `c69` Decimal(16, 4) DEFAULT '0.00',
    `c70` Decimal(16, 4) DEFAULT '0.00',
    `c71` Decimal(16, 4) DEFAULT '0.00',
    `c72` Int64 DEFAULT '0',
    `c73` Int32 DEFAULT '0',
    `c74` Int32 DEFAULT '0',
    `c75` Int8 DEFAULT '0',
    `c76` String DEFAULT '',
    `c77` Int64 DEFAULT '0',
    `c78` String DEFAULT '',
    `c79` Decimal(16, 4) DEFAULT '0.00',
    `c80` DateTime DEFAULT now()
ENGINE = ReplacingMergeTree(c36)
PARTITION BY toYYYYMM(c3)
ORDER BY (c2, c18, c1)
SETTINGS index_granularity = 8192;

insert into 2000w rows;

ALTER TABLE default.test_table ADD PROJECTION p_norm (select c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12, c13, c14, c15, c16, c17, c18, c19, c20, c21, c22, c23, c24, c25, c26, c27, c28, c29, c30, c31, c32, c33, c34, c35, c36, c37, c38, c39, c40, c41, c42, c43, c44, c45, c46, c47, c48, c49, c50, c51, c52, c53, c54, c55, c56, c57, c58, c59, c60, c61, c62, c63, c64, c65, c66, c67, c68, c69, c70, c71, c72, c73, c74, c75, c76, c77, c78, c79, c80 order by c20);

alter table default.test_table materialize PROJECTION p_norm;

then error;

**Comment by amosbird** [comment]
I cannot reproduce it in current master @degrees-273 . Maybe it's already fixed. Could you give it a try?

**Comment by amosbird** [comment]
@degrees-273 Thanks! The problem is related to vertical merges of projection parts, which reuse the same MergeEntry of the base process. I'll fix it asap.
