### ISSUE TITLE
(Merger): Unexpected number of parts removed when adding...

### ISSUE THREAD

**Issue by rugabarbo** [ClickHouse/ClickHouse#2927]
Столкнулись с тем, что данные не схлопываются. В логах появляются записи вида: 
```
<Warning> stat_shard_4_replica_1.leads (Merger): Unexpected number of parts removed when adding 20180401_20180425_0_9141_235: 2 instead of 6
```

Удалось найти объяснение в исходном коде CH:
https://github.com/yandex/ClickHouse/blob/9e652d8ccf1ef0fc37cba06aea70d410419f378f/dbms/src/Storages/MergeTree/MergeTreeDataMergerMutator.cpp#L1063-L1087

> This is normal, although this happens rarely.

ОК, это ожидаемое поведение CH. Но какой в итоге workaround? Как схлопнуть данные, для которых появились такие ворнинги?

**Comment by alexey-milovidov** [comment]
Это сообщение никак не связано со схлопыванием данных. То есть, появление таких ошибок не мешает схлопыванию.
