### ISSUE TITLE
Why can't I see the creation sql of system.parts?

### ISSUE THREAD

**Issue by MrSsunlight** [ClickHouse/ClickHouse#29283]
I found that desc can view the system.parts dimension, i can also use detach, but i cannot use show create；
```
:) show create table system.parts
SHOW CREATE TABLE system.parts


Received exception from server (version 20.3.11):
Code: 107. DB::Exception: Received from 127.0.0.1:9000. DB::Exception: Cannot open file /var/lib/clickhouse/metadata/system/parts.sql, errno: 2, strerror: No such file or directory. 

0 rows in set. Elapsed: 0.001 sec.
```

**Comment by nvartolomei** [comment]
@MrSsunlight `system.parts` is a "virtual" table backed by in-memory server state. It is built on the fly when queried. Implementation can be found in https://github.com/ClickHouse/ClickHouse/blob/master/src/Storages/System/StorageSystemParts.cpp

**Comment by MrSsunlight** [comment]
@nvartolomei  If I use detach to remove system.parts, what method should I use to restore it?

**Comment by nvartolomei** [comment]
@MrSsunlight i'm surprised you can detach it. Maybe it shouldn't be allowed at all.

**Comment by nvartolomei** [comment]
Forgot to answer your question. Restarting the server will restore the tables.

**Comment by MrSsunlight** [comment]
@nvartolomei Yes, I am also surprised that I can use detach to operate system.parts; it is restored after restarting, but is there a way to restore this in-memory table without restarting.

**Comment by alexey-milovidov** [comment]
No, there is no way to reattach system tables back without restarting.
