### ISSUE TITLE
Disk level encryption. Using multiple keys without specifying current_key_id parameter in configuration file.

### ISSUE THREAD

**Issue by antip00** [ClickHouse/ClickHouse#29288]
If you create configuration file that uses encrypted disk and specify two or more keys without specifying <current_key_id> configuration parameter, server will work, you will be able to create tables, insert and select from it.

**How to reproduce**

```xml
 <yandex>
   <storage_configuration>
     <disks>
       <local>
         <path>disk_local/</path>
       </local>
       <encrypted_local>
         <type>encrypted</type>
         <disk>local</disk>
         <path>encrypted/</path>
         <key id="0">firstfirstfirstf</key>
         <key id="1">secondsecondseco</key>
       </encrypted_local>
     </disks>
     <policies>
       <local_encrypted>
         <volumes>
           <encrypted_disk>
             <disk>encrypted_local</disk>
           </encrypted_disk>
         </volumes>
       </local_encrypted>
     </policies>
   </storage_configuration>
 </yandex>
```
```SQL
CREATE TABLE test
(
    ID Int32,
    Value String
)
ENGINE = MergeTree()
PARTITION BY ID
ORDER BY ID
SETTINGS storage_policy = 'local_encrypted'
```
```SQL
insert into test values (1, '1111')
```

Server works but key, that should be used for encryption is undefined.
 
21.10.1.7939 Clickhouse version

**Expected behavior**
Server should not start with configuration file like that.

**Comment by FArthur-cmd** [comment]
In cases where `current_key_id` is not defined, it will be automatically set to 0. Thus, in this cases, key with `id="0"` will be chosen. Maybe this should be recorded in documentation. (This row choose current_key src/Disks/DiskEncrypted.cpp:79)
