### ISSUE TITLE
how to calculate the absolute_delay of the table system.replicas

### ISSUE THREAD

**Issue by 825644691** [ClickHouse/ClickHouse#29313]
![image](https://user-images.githubusercontent.com/34371864/134614071-252d1861-184e-43eb-ae97-aab041ed9e1e.png)
I want to know about the calculation method about the absolute_delay,please

**Comment by 825644691** [comment]
database:                   xxxx
table:                      xxx
engine:                     ReplicatedMergeTree
is_leader:                  1
can_become_leader:          1
is_readonly:                0
is_session_expired:         0
future_parts:               10
parts_to_check:             0
zookeeper_path:             /clickhouse/tables/10/xxx
replica_name:               2
replica_path:               /clickhouse/tables/10/xxxx/replicas/2
columns_version:            -1
queue_size:                 11
inserts_in_queue:           2
merges_in_queue:            9
part_mutations_in_queue:    0
queue_oldest_time:          2021-09-17 13:39:30
inserts_oldest_time:        2021-09-17 13:39:30
merges_oldest_time:         2021-09-24 08:40:34
part_mutations_oldest_time: 1970-01-01 08:00:00
oldest_part_to_get:         b3e2a6c617348ee18bc2cb6e3a0f8105_0_9221_5
oldest_part_to_merge_to:    b3e2a6c617348ee18bc2cb6e3a0f8105_0_9221_6
oldest_part_to_mutate_to:   
log_max_index:              17030134
log_pointer:                17030135
last_queue_update:          2021-09-24 11:37:12
absolute_delay:             597462
total_replicas:             2
active_replicas:            2
zookeeper_exception:

**Comment by den-crane** [comment]
>absolute_delay: 597462

seconds.

597462/3600/24 = 6.9 days.

**Comment by 825644691** [comment]
![image](https://user-images.githubusercontent.com/34371864/134614574-32895bb2-76da-4ddd-ad0b-caa804f91005.png)
every time 
I kill the clickhouse-server process 
touch /apps/dbdat/clickhouse/flags/force_restore_data
and restart the clickhouse-server, the replica delay recover

**Comment by 825644691** [comment]
> > absolute_delay: 597462
> 
> seconds.
> 
> 597462/3600/24 = 6.9 days.
thank you for your answer
I mean that the value of '597462' how to calculate/get ，how to suddenly from 0  to 597462

**Comment by den-crane** [comment]
Please provide 

```
SELECT
    database,
    table,
    type,
    any(last_exception),
    any(postpone_reason),
    min(create_time),
    max(last_attempt_time),
    max(last_postpone_time),
    max(num_postponed) AS max_postponed,
    max(num_tries) AS max_tries,
    min(num_tries) AS min_tries,
    countIf(last_exception != '') AS count_err,
    countIf(num_postponed > 0) AS count_postponed,
    countIf(is_currently_executing) AS count_executing,
    count() AS count_all
FROM system.replication_queue
GROUP BY
    database,
    table,
    type
ORDER BY count_all DESC
```

**Comment by 825644691** [comment]
but now the replica delay is recoverd.....

Row 1:
──────
database:                xxx
table:                   table1
type:                    MERGE_PARTS
any(last_exception):     
any(postpone_reason):    
min(create_time):        2021-09-24 08:34:29
max(last_attempt_time):  2021-09-24 11:56:11
max(last_postpone_time): 2021-09-24 11:56:09
max_postponed:           462
max_tries:               1
min_tries:               1
count_err:               0
count_postponed:         4
count_executing:         12
count_all:               12

Row 2:
──────
database:                xxx
table:                   table2
type:                    MERGE_PARTS
any(last_exception):     
any(postpone_reason):    
min(create_time):        2021-09-24 10:54:00
max(last_attempt_time):  2021-09-24 11:56:08
max(last_postpone_time): 2021-09-24 11:56:04
max_postponed:           14
max_tries:               1
min_tries:               1
count_err:               0
count_postponed:         1
count_executing:         9
count_all:               9

Row 3:
──────
database:                xxxx
table:                   table3
type:                    DROP_RANGE
any(last_exception):     
any(postpone_reason):    Not executing log entry queue-0006577795 of type DROP_RANGE for part 05a96cc93712d8dd19df0054469a4daa_0_29955_999999999_999999999 because another DROP_RANGE or REPLACE_RANGE entry are currently executing.
min(create_time):        2021-09-24 11:42:08
max(last_attempt_time):  2021-09-24 11:42:08
max(last_postpone_time): 2021-09-24 11:56:11
max_postponed:           12083
max_tries:               1
min_tries:               0
count_err:               0
count_postponed:         1
count_executing:         1
count_all:               2

Row 4:
──────
database:                xxxx
table:                   table4
type:                    DROP_RANGE
any(last_exception):     
any(postpone_reason):    
min(create_time):        2021-09-24 11:46:09
max(last_attempt_time):  2021-09-24 11:46:09
max(last_postpone_time): 1970-01-01 08:00:00
max_postponed:           0
max_tries:               1
min_tries:               1
count_err:               0
count_postponed:         0
count_executing:         1
count_all:               1
