### ISSUE TITLE
After the ClickHouse version is upgraded, Whether the new version is compatible with the current data format?

### ISSUE THREAD

**Issue by wallace-clickhouse** [ClickHouse/ClickHouse#29312]
Hello，
I'm using ClickHouse 20.3.2.1 and plan to upgrade to a newer version, but I'm wondering if the newer version will be compatible with the current data format of 20.3.2.1.Can you please give me  some guidance?
Thank you very much!

**Comment by den-crane** [comment]
Yes, mostly.
Check all Backward Incompatible Change in https://github.com/ClickHouse/ClickHouse/blob/master/CHANGELOG.md
Run all DDL queries "create table" against new version in staging env.
Upgrade your staging env.
Make a backup of your prod. server restore in stage env. and upgrade this copy.
