### ISSUE TITLE
DirectoryMonitor: Code: 209, e.displayText() = DB::NetException: Timeout: connect timed out

### ISSUE THREAD

**Issue by andranyirestyan** [ClickHouse/ClickHouse#29329]
I have CH cluster with two shards with one replica each using a table created with the Distributed engine. When trying to insert data into the Distributed table I noticed that the data is not being sharded and the error I get is the following

2021.09.24 04:31:49.072428 [ 34966 ] {} <Error> hits.hits_all.DirectoryMonitor: Code: 209, e.displayText() = DB::NetException: Timeout: connect timed out: the other server's IP:9000 (the other server's hostname:9000), Stack trace (when copying this message, always include the lines below):

0. DB::Connection::connect(DB::ConnectionTimeouts const&) @ 0xf7da67c in /usr/bin/clickhouse
1. DB::ConnectionPool::get(DB::ConnectionTimeouts const&, DB::Settings const*, bool) @ 0x870ac0d in /usr/bin/clickhouse
2. DB::StorageDistributedDirectoryMonitor::processFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xf56669d in /usr/bin/clickhouse
3. DB::StorageDistributedDirectoryMonitor::run() @ 0xf5616db in /usr/bin/clickhouse
4. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0xeb35df2 in /usr/bin/clickhouse
5. DB::BackgroundSchedulePool::threadFunction() @ 0xeb38227 in /usr/bin/clickhouse
6. ? @ 0xeb394a1 in /usr/bin/clickhouse
7. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x863e73d in /usr/bin/clickhouse
8. ? @ 0x86422f3 in /usr/bin/clickhouse
9. start_thread @ 0x814a in /usr/lib64/libpthread-2.28.so
10. clone @ 0xfcdc3 in /usr/lib64/libc-2.28.so
 (version 21.1.10.3.altinity+stable (altinity build))

**Comment by alexey-milovidov** [comment]
Check your network configuration.
