### ISSUE TITLE
HDFS engine fails with Kerberos is used

### ISSUE THREAD

**Issue by jiangdaokun** [ClickHouse/ClickHouse#29320]
ClickHouse server version: 21.8.3.44

I want to use HDFS engine on Clickhouse, My HDFS cluster contains Kerberos,When I closed Kerberos, I can get HDFS data ;
However, when I open Kerberos, the query is error. I execute this command on the machine successfully
command:
kinit -R -t "/etc/hdfs1/conf/hdfs.keytab" -k hdfs/tdh1@TDHTEST|| kinit -t "/etc/hdfs1/conf/hdfs.keytab" -k hdfs/tdh1@TDHTEST

error info:
Code: 36, e.displayText() = DB::Exception: kinit failure: kinit -R -t "/etc/hdfs1/conf/hdfs.keytab" -k hdfs/tdh1@TDHTEST|| kinit -t "/etc/hdfs1/conf/hdfs.keytab" -k hdfs/tdh1@TDHTEST (version 21.8.3.44 (official build)) (from 172.0.0.1:58685) (in query: select * from da.base_agent_info_oper_hdfs FORMAT TabSeparatedWithNamesAndTypes ), Stack trace (when copying this message, always include the lines below):

create table sql:
CREATE TABLE da.base_agent_info_oper_hdfs
(
    `agent_no` String,
    `agent_name` String,
    `agent_type` String,
    `phoneno` String,
    `hdatasign` String,
    `hloadtime` String,
    `hbatchdate` String,
    `hdatasrc` String
)
ENGINE = HDFS('hdfs://172.0.0.1:8020/inceptor1/user/hive/warehouse/da.db/hbxyoper/base_agent_info_oper/*', 'ORC');

**Comment by ilejn** [comment]
@jiangdaokun it is a good idea to test kinit manually. 
Could you run it using clickhouse user credentials to avoid e.g. possible permission issues?

**Comment by jiangdaokun** [comment]
@ilejn 
When I used clickhouse.keytab, I did not have this problem, but I encountered a new problem。

https://github.com/ClickHouse/ClickHouse/issues/30317

**Comment by alexey-milovidov** [comment]
We don't support HDFS.
