### ISSUE TITLE
Dense_Rank calculation.

### ISSUE THREAD

**Issue by rspratik** [ClickHouse/ClickHouse#2934]
Hi , 

I am trying to calculate the dense rank and as, we are aware that there is no direct function for it in clickhouse, So I went with the workaround suggested in the following git hub link.
**https://gist.github.com/alexey-milovidov/2ebeb97a6dfe2e885e6cbae3bb2d7545**

The results will be wrong if the column mentioned in the order by clause has repeated values for a given partition (see the image). The rank should be 1 for both highlighted values as the order by is with salary and partition is over the deptid.

I will also try to find a fix for this but any help is appreciated.

![image](https://user-images.githubusercontent.com/11264753/44551632-bfcece80-a6f5-11e8-8634-96917096e6ca.png)

-----------------------------
Following is the query:
-----------------------------
```
SELECT 
    empid, 
    deptid, 
    salary, 
    rank
FROM 
(
    SELECT 
        groupArray(empid) AS empids, 
        groupArray(deptid) AS deptids, 
        groupArray(salary) AS salaries
    FROM 
    (
        SELECT *
        FROM employee
        ORDER BY 
            salary DESC
    )
)
ARRAY JOIN 
    empids AS empid, 
    deptids AS deptid, 
    salaries AS salary, 
    arrayEnumerateUniq(deptids) AS rank
    order by deptid, rank
```
-----------------------------

Thanks

**Comment by amosbird** [comment]
`arrayEnumerateUniq` is not the right function to generate ranks, neither is `arrayEnumerate` (as you've noticed that it doesn't handle equal values which is just a row_number function). Traditional `RANK` window function returns `1,1,3` and `DENSE_RANK` returns `1,1,2` in your example. Suppose you really want a dense_rank, you would need an `arrayEnumerateDense` function to get the expected result. 

https://github.com/yandex/ClickHouse/pull/2975
