### ISSUE TITLE
Failed assertion in `Merge` table engine with REGEXP database matching.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#29349]
**Describe the bug**
https://clickhouse-test-reports.s3.yandex.net/29341/2b2bec3679df7965af908ce3f1e8e17e39bd12fe/fuzzer_debug/report.html#fail1

**How to reproduce**
```
SELECT _database, _table, n FROM merge(REGEXP('\001902_db'), '^t') ORDER BY _database ASC, _table ASC, n ASC
```

```
std::exception. Code: 1001, type: std::out_of_range, e.what() = map::at:  key not found 
```

**Comment by alexey-milovidov** [comment]
Bug was introduced here: #25064

**Comment by alexey-milovidov** [comment]
Always reproducing:

```
SELECT * FROM merge(REGEXP('\0'), 'a')
```

**Comment by alexey-milovidov** [comment]
```
SELECT * FROM merge(REGEXP('.'), 'a')
```

**Comment by alexey-milovidov** [comment]
The code is also using `DbToTableSetMap` that is out of style.
We only allow `DBToTableSetMap`.

No surprise that it also contains a bug.

**Comment by Zhile** [comment]
@alexey-milovidov  Can we also back port this bug fix to 2.18 LTS? thanks.

**Comment by alexey-milovidov** [comment]
It's not an important bug. You will get just slightly misleading exception message, but nothing bad will happen.

**Comment by Zhile** [comment]
Got it. Thanks.
