### ISSUE TITLE
Cannot read all data. Bytes read: 39166. Bytes expected: 296440.: while receiving packet from 192.168.9.114:9000: While executing SourceFromInputStream

### ISSUE THREAD

**Issue by junjun888** [ClickHouse/ClickHouse#29363]
the problem is :

Cannot read all data. Bytes read: 39166. Bytes expected: 296440.: while receiving packet from 192.168.9.114:9000: While executing SourceFromInputStream

my clickhouse-server version:  20.3.12.112

the execute-plan error stack is:
[DE-CK-s1] 2021.09.24 14:36:04.442266 [ 135041 ] {f50702dc-73d3-4b84-b184-0f1c5eb21ce1} <Debug> MemoryTracker: Current memory usage: 40.01 GiB.
[DE-CK-s1] 2021.09.24 14:36:05.498658 [ 135041 ] {f50702dc-73d3-4b84-b184-0f1c5eb21ce1} <Trace> Aggregator: Merged partially aggregated blocks. 791508 rows, 105.800 MiB. in 1.461 sec. (541846.766 rows/sec., 72.428 MiB/sec.)
[DE-CK-s1] 2021.09.24 14:36:05.799294 [ 134703 ] {f50702dc-73d3-4b84-b184-0f1c5eb21ce1} <Trace> Aggregator: Merged partially aggregated blocks. 790450 rows, 105.637 MiB. in 1.485 sec. (532320.263 rows/sec., 71.140 MiB/sec.)
[DE-CK-s1] 2021.09.24 14:36:07.830315 [ 348799 ] {f50702dc-73d3-4b84-b184-0f1c5eb21ce1} <Error> executeQuery: Code: 33, e.displayText() = DB::Exception: Cannot read all data. Bytes read: 39166. Bytes expected: 296440.: while receiving packet from 192.168.9.114:9000: While executing SourceFromInputStream (version 20.3.12.112) (from [::1]:57676) (in query: SELECT capture_hour, toYYYYMM(capture_day), generateUUIDv4(), source_type, auth_account, auth_type, src_country, dst_country, app_name, app_type, sum(behavior_num) AS behavior_num, min(earliest_time) AS earliest_time, max(latest_time) AS latest_time, any(insert_time) FROM ads.ads_radius_app_contact_archive_action_detail_by_hour_all WHERE 
(capture_day >= toDate(1630425600)) AND (capture_day <= toDate(1632931200)) AND (moduloOrZero(sipHash64(concat(toString(capture_hour), toString(toYYYYMM(capture_day)), toString(source_type), toString(auth_account), toString(auth_type), toString(src_country), toString(dst_country), toString(app_name), toString(app_type))), 30) = 0) GROUP BY capture_hour, toYYYYMM(capture_day), source_type, auth_account, auth_type, src_country, dst_country, app_name, app_type), Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xbbad39c in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x50061f9 in /usr/bin/clickhouse
2. ? @ 0x4bc4f4b in /usr/bin/clickhouse
3. DB::CompressedReadBuffer::nextImpl() @ 0x8934695 in /usr/bin/clickhouse
4. DB::DataTypeAggregateFunction::deserializeBinaryBulk(DB::IColumn&, DB::ReadBuffer&, unsigned long, double) const @ 0x89846d5 in /usr/bin/clickhouse
5. DB::NativeBlockInputStream::readData(DB::IDataType const&, DB::IColumn&, DB::ReadBuffer&, unsigned long, double) @ 0x8963a89 in /usr/bin/clickhouse
6. DB::NativeBlockInputStream::readImpl() @ 0x8964769 in /usr/bin/clickhouse
7. DB::IBlockInputStream::read() @ 0x894ac37 in /usr/bin/clickhouse
8. DB::Connection::receiveDataImpl(std::__1::shared_ptr<DB::IBlockInputStream>&) @ 0x906e06a in /usr/bin/clickhouse
9. DB::Connection::receivePacket() @ 0x906fa4f in /usr/bin/clickhouse
10. DB::MultiplexedConnections::receivePacket() @ 0x9082e96 in /usr/bin/clickhouse
11. DB::RemoteBlockInputStream::readImpl() @ 0x8974084 in /usr/bin/clickhouse
12. DB::IBlockInputStream::read() @ 0x894ac37 in /usr/bin/clickhouse
13. DB::SourceFromInputStream::generate() @ 0x938d0e4 in /usr/bin/clickhouse
14. DB::ISource::work() @ 0x90d0717 in /usr/bin/clickhouse
15. DB::SourceFromInputStream::work() @ 0x938cffd in /usr/bin/clickhouse
16. ? @ 0x90fad1f in /usr/bin/clickhouse
17. DB::PipelineExecutor::executeSingleThread(unsigned long, unsigned long) @ 0x90fedb1 in /usr/bin/clickhouse
18. ? @ 0x90ff6ff in /usr/bin/clickhouse
19. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x500fa1d in /usr/bin/clickhouse
20. ? @ 0x500e08f in /usr/bin/clickhouse
21. start_thread @ 0x7dd5 in /usr/lib64/libpthread-2.17.so
22. __clone @ 0xfdead in /usr/lib64/libc-2.17.so

Received exception from server (version 20.3.12):
Code: 33. DB::Exception: Received from localhost:9000. DB::Exception: Cannot read all data. Bytes read: 39166. Bytes expected: 296440.: while receiving packet from 192.168.9.114:9000: While executing SourceFromInputStream.

**Comment by alexey-milovidov** [comment]
Upgrade to version 21.9.
