### ISSUE TITLE
Issue creating materialized view on table which is replica of the Postgresql, returning error

### ISSUE THREAD

**Issue by Shohjahon** [ClickHouse/ClickHouse#29401]
(you don't have to strictly follow this form)

**Description**
When i try to create materialized view for the table orders(engine: ReplacingMergeTree), clickhouse returning error.
Database migrated from Postgresql using MaterializedPostgresql engine

**Details**
* Clickhouse server version:  21.9.2.17
* Database client: Dbeaver
* `CREATE TABLE shipox.orders
(

    `id` Int64,

    `code` Nullable(String),

    `status` Nullable(String),

    `pickup_time` Nullable(DateTime64(6)),

    `pickup_time_now` Nullable(UInt8),

    `deleted` Nullable(UInt8),

    `note` Nullable(String),

    `approximate_distance` Nullable(Int64),

    `amount` Nullable(Decimal(38,
 4)),

    `completed` Nullable(DateTime64(6)),

    `payment_type` Nullable(String),

    `payment_status` Nullable(UInt8),

    `if_recipient_not_available` Nullable(String),

    `payer` Nullable(String),

    `delivered_to` Nullable(String),

    `delivered_to_phone` Nullable(String),

    `driver_id` Nullable(Int64),

    `customer_id` Nullable(Int64),

    `order_payment_id` Nullable(Int64),

    `created_by` String,

    `created_date` DateTime64(6),

    `last_modified_by` Nullable(String),

    `last_modified_date` Nullable(DateTime64(6)),

    `supplier_id` Nullable(Int64),

    `actual_delivery_option` Nullable(String),

    `package_id` Nullable(Int64),

    `sender_from` Nullable(String),

    `sender_phone` Nullable(String),

    `public_id` Nullable(String),

    `device_details` Nullable(String),

    `shipment_id` Nullable(String),

    `recipient_id` Nullable(Int64),

    `deadline_time` Nullable(DateTime64(6)),

    `promo_id` Nullable(Int64),

    `warehouse_id` Nullable(Int64),

    `fragile` Nullable(UInt8),

    `is_public` Nullable(UInt8),

    `size` Nullable(String),

    `driver_bonus_id` Nullable(Int64),

    `previous_driver_id` Nullable(Int64),

    `delivery_attemp_count` Nullable(Int64),

    `pickup_attemp_count` Nullable(Int64),

    `cod_status` Nullable(String),

    `cod_transfer_id` Nullable(Int64),

    `create_transaction` Nullable(UInt8),

    `last_mile_driver_id` Nullable(Int64),

    `withdraw_request_id` Nullable(Int64),

    `pickup_id` Nullable(String),

    `last_status_date` Nullable(DateTime64(6)),

    `last_cod_status_date` Nullable(DateTime64(6)),

    `is_uae` Nullable(UInt8),

    `shop_order` Nullable(UInt8),

    `customer_care_id` Nullable(Int64),

    `price_id` Nullable(Int64),

    `estimated_delivery_date_time` Nullable(DateTime64(6)),

    `estimated_pick_up_time` Nullable(DateTime64(6)),

    `cancellation_requires_type` Nullable(String),

    `parent_supplier_id` Nullable(Int64),

    `drop_timeslot_availability_id` Nullable(Int64),

    `pickup_timeslot_availability_id` Nullable(Int64),

    `reference_id` Nullable(String),

    `value` Nullable(Decimal(38,
 4)),

    `fetch_item_id` Nullable(Int64),

    `pick_up_driver_id` Nullable(Int64),

    `first_delivery_time` Nullable(DateTime64(6)),

    `first_pick_up_time` Nullable(DateTime64(6)),

    `allocated_from_warehouse` Nullable(UInt8),

    `api_supplier_id` Nullable(Int64),

    `actualdelivery_time` Nullable(DateTime64(6)),

    `actual_pickup_time` Nullable(DateTime64(6)),

    `marketplace_id` Nullable(Int64),

    `currency_id` Nullable(Int64),

    `rule_id` Nullable(Int64),

    `unique_id` Nullable(String),

    `parent_id` Nullable(Int64),

    `type` Nullable(String),

    `is_old` Nullable(UInt8),

    `with_driver` Nullable(UInt8),

    `with_driver_time` Nullable(DateTime64(6)),

    `merchant_promise_date` Nullable(DateTime64(6)),

    `cod_transfer_type` Nullable(String),

    `internal_promise_date` Nullable(DateTime64(6)),

    `finance_pick_up_driver_id` Nullable(Int64),

    `finance_pick_up_supplier_id` Nullable(Int64),

    `cashier_id` Nullable(Int64),

    `id_card_required` Nullable(UInt8),

    `order_count` Nullable(Int32),

    `weight` Nullable(Float64),

    `timeslot_availability_history_id` Nullable(Int64),

    `scanned_piece_count` Nullable(Int32),

    `seller_id` Nullable(String),

    `seller_name` Nullable(String),

    `heavy_type` Nullable(String),

    `first_driver_id` Nullable(Int64),

    `cod_settlement_date` Nullable(DateTime64(6)),

    `cod_settlement_reference` Nullable(String),

    `wallet_settlement_date` Nullable(DateTime64(6)),

    `wallet_settlement_reference` Nullable(String),

    `chargeable_weight` Nullable(Decimal(38,
 2)),

    `height` Nullable(Decimal(38,
 2)),

    `length` Nullable(Decimal(38,
 2)),

    `width` Nullable(Decimal(38,
 2)),

    `provided_weight` Nullable(Decimal(38,
 2)),

    `volumetric_weight` Nullable(Decimal(38,
 2)),

    `dimension_unit` Nullable(String),

    `package_type_id` Nullable(Int64),

    `order_piece_count` Nullable(Int32),

    `delivered_to_photo_id` Nullable(Int64),

    `delivery_signature_id` Nullable(Int64),

    `sender_photo_id` Nullable(Int64),

    `sender_signature_id` Nullable(Int64),

    `from_warehouse_id` Nullable(Int64),

    `to_warehouse_id` Nullable(Int64),

    `first_ofd_date` Nullable(DateTime64(6)),

    `last_ofd_date` Nullable(DateTime64(6)),

    `encrypted_id` Nullable(String),

    `eta_id` Nullable(Int64),

    `item_payment_id` Nullable(Int64),

    `from_area_id` Nullable(Int64),

    `to_area_id` Nullable(Int64),

    `last_status_updated_user_id` Nullable(Int64),

    `order_transfer_id` Nullable(Int64),

    `external_user_name` Nullable(String),

    `receipt_id` Nullable(Int64),

    `receipt_number` Nullable(String),

    `from_city` Nullable(String),

    `to_city` Nullable(String),

    `logistic_type` Nullable(String),

    `back_id` Nullable(Int64),

    `head_id` Nullable(Int64),

    `reverse_code` Nullable(String),

    `psf_status` Nullable(String),

    `request_details` Nullable(String),

    `storfox_sale_order_id` Nullable(String),

    `route_distance` Nullable(Int64),

    `is_no_service_area` Nullable(UInt8),

    `recipient_city_changed` Nullable(UInt8),

    `source_id` Nullable(String),

    `source_type` Nullable(Int32),

    `sms_verification_number` Nullable(String),

    `sms_verified` Nullable(UInt8),

    `audit_version` Nullable(Int64),

    `manifest` Nullable(String),

    `agent` Nullable(String),

    `placed_storage_address` Nullable(String),

    `last_mile_warehouse_id` Nullable(Int64),

    `solr_index_request_uuid` Nullable(String),

    `solr_index_version` Nullable(Int64),

    `driver_fee_id` Nullable(Int64),

    `_sign` Int8 MATERIALIZED 1,

    `_version` UInt64 MATERIALIZED 1
)
ENGINE = ReplacingMergeTree(_version)
ORDER BY tuple(id)
SETTINGS index_granularity = 8192

` table ddl 

* Create view statement which lead to the error: `create materialized view shipox.orders_vw
engine = ReplacingMergeTree 
partition by toYYYYMM(created_date) 
order by (created_date) 
populate as  
select status, count() as order_counts, created_date from shipox.orders 
group by status, created_date ;`

**Error message **
SQL Error [1002]: ClickHouse exception, code: 1002, host: 35.172.98.140, port: 8123; Code: 48. DB::Exception: Create table query allowed only for ReplacingMergeTree engine and from synchronization thread. (NOT_IMPLEMENTED) (version 21.9.2.17 (official build))

**Comment by Shohjahon** [comment]
@alexey-milovidov @kssenii  Can you help for resolving this issue please?

**Comment by kssenii** [comment]
Of course!

As I see here 

> create materialized view shipox.orders_vw engine = ReplacingMergeTree partition by toYYYYMM(created_date) order by (created_date) populate as select status, count() as order_counts, created_date from shipox.orders group by status, created_date ;

you are trying to create a materialized view inside a MaterializedPostgreSQL database engine. But why? Can't you just create it in some other database engine and create a view from materialized postgresql database engine table? (not sure it will work though, I never tested such case)

Also 

> shipox

It is a database with materialized postgresql engine, correct? I wonder how you managed to create a table `orders` there if its now allowed..

**Comment by Shohjahon** [comment]
Database was created using the command shown below:
`CREATE DATABASE shipox
ENGINE = MaterializedPostgreSQL('host:port', 'shipox', 'shipox', password)
SETTINGS
 materialized_postgresql_max_block_size = 65536,
 materialized_postgresql_allow_automatic_update = 1,
 materialized_postgresql_tables_list = 'orders';`
it replicated data from Postgresql database 'shipox' to Clickhouse using logical replication. Data was successfully replicated to
Clickhouse database, but creating materialized view on Clickhouse database table 'shipox.orders' is faling with the error given above.
I tried to create another database and created the materialized view, it was successful , but when i try to fetch data from the materialized view, it does not return any row from materialized view. @kssenii

**Comment by Shohjahon** [comment]
![click](https://user-images.githubusercontent.com/16575814/134885315-f6807b00-9428-43e6-bea7-6eb17dd7e402.jpg)

**Comment by kssenii** [comment]
> but creating materialized view on Clickhouse database table 'shipox.orders' is faling with the error given above.

I don't think it is correct to allow MaterializedPostgreSQL database engine to contain anything apart from tables, which are replicated from postgresql.
Therefore the error you get when creating a materialized view inside materializedPostgreSQL database is absolutely correct.

> I tried to create another database and created the materialized view, it was successful , but when i try to fetch data from the materialized view, it does not return any row from materialized view.

I think this is what needs to be fixed because it should work. I'll see why it doesn't.

**Comment by Shohjahon** [comment]
@kssenii can you share existing solution for this issue, because i should migrate our existing data on Postgresql to Clickhouse for analytical purposes, its first time we are using Clickhouse? I apreciate your efforts

**Comment by Shohjahon** [comment]
@kssenii Can you share existing solution for this issue?

**Comment by Rumte** [comment]
@Shohjahon Did you find a solution for this issue?

**Comment by kssenii** [comment]
materialised view with MaterializedPostgreSQL engine was fixed in https://github.com/ClickHouse/ClickHouse/pull/40807.
