### ISSUE TITLE
Very low mutation performance for a replicated tables

### ISSUE THREAD

**Issue by SergImmortal** [ClickHouse/ClickHouse#29411]
Hi ClickHouse team,

**Describe the unexpected behaviour**
We have 2 servers (64 CPU 128 RAM) with replicated tables (~200M rows) + recording 50-200 rows per second by 1 insert. 
And we need to update around 1M rows spread over the table for few previous months, each row by the specific query. 
While this update we caught the **error**: 

`DB::Exception: Too many optimizations applied to query plan. Current limit 10000 (version 21.4.6.55 (official build))`

The update was stopped, more than 9 000 mutations in the queue were killed but currently, servers do merging very slowly for new needed mutations. 
I see only one merging process for table and queue for more than 200 updates for the last 10 days. And updates makes 10 days ago still didn't finish.
**Questions:**
* Can we improve the performance of the process of rows updated by changing some settings for servers? Or change settings for the ReplicatedMergeTree engine?
* Is it possible to update 1M rows spread over the table using ReplicatedMergeTree? or for example delete and record these rows will be better?
* Can we reload the server without lost not updated data?

Thank you!

**Comment by den-crane** [comment]
21.4. is out of support.

Q/A:
1. No.
2. Possible, by a single mutation. Use external dictionaries.
3. yes, you should.

**Comment by den-crane** [comment]
1. I will not waste time on investigating issues in 21.4 (obsolete).
2. https://stackoverflow.com/a/55775479/11644308 + setting_allow_nondeterministic_mutations
