### ISSUE TITLE
'Coordination::Exception: Connection loss' when I exec modify TTL. 

### ISSUE THREAD

**Issue by Sallery-X** [ClickHouse/ClickHouse#29467]
1>、version 21.3 lts
2>、the replicated table has about 2300 partitions, about 6300 parts, has 45575553545 rows;
3>、when I 'exec ALTER TABLE xxx MODIFY TTL toDateTime(toDate(concat(day, ' 00:00:00'))) + toIntervalMonth(1)' 
![image](https://user-images.githubusercontent.com/45587738/135046089-a18dcba8-d9e5-40ad-8a81-b26c63ed8f17.png)

**Comment by vdimir** [comment]
Cloud you provide server logs?
