### ISSUE TITLE
MaterializeMySQL Decimal bug

### ISSUE THREAD

**Issue by wenyuanLv** [ClickHouse/ClickHouse#29468]
ClickHouse client version 21.8.4.51 (official build).

I had a problem synchronizing Nullable(Decimal(20, 8))  using the MaterializeMySQL

mysql data is  10929.00000000 

but clickhouse data is -32771294956408.94967295

Can someone help me plz

**Comment by tavplubix** [comment]
It's known bug (#25896,  #19597, #16265) with Decimals replication, but it's hard to reproduce. We need some reproducible example to debug it and fix.

**Comment by wenyuanLv** [comment]
It's hard to find examples. This is an occasional phenomenon.You may be able to modify the Decimal code in mysqlreplication.cpp. Someone has fixed it.

**Comment by baoqingkeji** [comment]
> It's hard to find examples. This is an occasional phenomenon.You may be able to modify the Decimal code in mysqlreplication.cpp. Someone has fixed it.

This bug is easy to reproduce, but no one has fixed it.
