### ISSUE TITLE
Invalid cursor state from ODBC bridge to SQL Server

### ISSUE THREAD

**Issue by jeandeniscosta** [ClickHouse/ClickHouse#29473]
We use 40 dictionaries based on SQL queries to an SQL server, feeding tables with various sizes (smallest is a few lines, biggest is a few millions). They are configured to refresh every 5 minutes
Sometimes the dictionaries get "stuck" and each refresh (automatic or via "SYSTEM RELOAD DICTIONARIES") end up failed, with the following exception:

```
Code: 86, e.displayText() = DB::Exception: Received error from remote server /?connection_string=DSN%3DSERVERNAME%3BUID%3DXXXXXX%3BPWD%3DXXXXXX&max_block_size=8192. HTTP status code: 500 Internal Server Error, body: �std::exception. Code: 1001, type: nanodbc::database_error, e.what() = ../contrib/nanodbc/nanodbc/nanodbc.cpp:1625: 2400: [FreeTDS][SQL Server]Invalid cursor state , Stack trace (when copying this message, always include the lines below):

0. ? @ 0x3a66342 in /usr/bin/clickhouse-odbc-bridge
1. ? @ 0x3a6893d in /usr/bin/clickhouse-odbc-bridge
2. ? @ 0x3a67a31 in /usr/bin/clickhouse-odbc-bridge
3. ? @ 0x2b52b7b in /usr/bin/clickhouse-odbc-bridge
4. ? @ 0x2b4c74d in /usr/bin/clickhouse-odbc-bridge
5. ? @ 0x3a05cd0 in /usr/bin/clickhouse-odbc-bridge
6. ? @ 0x52f5a8f in /usr/bin/clickhouse-odbc-bridge
7. ? @ 0x52f74fa in /usr/bin/clickhouse-odbc-bridge
8. ? @ 0x5e935b9 in ?
9. ? @ 0x5e9002a in ?
10. start_thread @ 0x76db in /lib/x86_64-linux-gnu/libpthread-2.27.so
11. clone @ 0x12188f in /lib/x86_64-linux-gnu/libc-2.27.so
 (version 21.6.4.26 (official build)) (version 21.6.4.26 (official build))
```
 
We can most if the time reset them by manually killing the clickhouse-odbc-bridge process and forcing a refresh, however it often fails once again soon after, with the same exception. Note that the distant SQL server is indeed quite unstable, so a few failures are not suprising, however I'd not expect to have to reboot the odbc bridge to make it work once again.

We only tried on version 21.6.4.26, but the issue reproduces itself quite often. 

I also noticed that the odbc-bridge comes with a very long timeout:
`
/usr/bin/clickhouse-odbc-bridge --http-port 9018 --listen-host 127.0.0.1 --http-timeout 1800000000
`
This was discussed here https://github.com/ClickHouse/ClickHouse/issues/5089 but closed with a message that I feel doesn't answer the original question. As it  is, unless I'm mistaken, the timeout is 20 days! The http_receive_timeout is set in the config at 1800s, which is much better.

Any help would be appreciated, we could always cron a check on dictionary state and autokill the bridge, but it looks like a dirty solution which an honest timeout should handle

PS: we should probably slow down the refresh rate on very big tables too, maybe it would help?

**Comment by kssenii** [comment]
> Invalid cursor state from ODBC bridge to SQL Server

Will be fixed when https://github.com/ClickHouse/ClickHouse/pull/29518 is merged.

> The http_receive_timeout is set in the config at 1800s, which is much better.

But it is 1800s already. The value you see `--http-timeout 1800000000` is in microseconds.

> PS: we should probably slow down the refresh rate on very big tables too, maybe it would help?

But dictionary lifetime is for it.

**Comment by jeandeniscosta** [comment]
> > The http_receive_timeout is set in the config at 1800s, which is much better.
> 
> But it is 1800s already. The value you see `--http-timeout 1800000000` is in microseconds.

Even so, 1800000000ms is not 1800s. There is an unexpected *1000 factor here which makes this timeout (20 days instead of 30 minutes) as good as useless.
What I meant is that I can't juste divide the http_receive_timeout by 1000 (let's round that to 2) to make up for it because then the actual value for http in Clickhouse will then be 2s (which is obviously too low)

**Comment by kssenii** [comment]
No, 1800 seconds is 1800000000 microseconds...

**Comment by jeandeniscosta** [comment]
Yes I just realised my mistake, sorry my bad, I'm not used to handling **micro**-seconds

Well then then it means that this timeout doesn't act like I expected, and the fix you propose (reopening the connection upon failure ) is really what is needed
