### ISSUE TITLE
clickhouse crash when executing JOIN query

### ISSUE THREAD

**Issue by SE2AI** [ClickHouse/ClickHouse#29484]
dear authors,

when executing JOIN query, clickhouse got crash:
for the column 'obj_id', there are about 1million records.
![20210928-211218(WeLinkPC)](https://user-images.githubusercontent.com/21308534/135093749-d1c9a394-c13f-43ff-81ec-b9b75f6c6dbb.png)

my question are:
1. I guess the reason is the amount is too large, right?
2. If so, is there any way of avoiding such kind of crash?
3. any suggestions about CH settings for join DQL

thanks a lot

**Comment by den-crane** [comment]
please provide `select version()`

**Comment by SE2AI** [comment]
> please provide `select version()`

the version is 21.6.4.26

**Comment by den-crane** [comment]
use subquery and define conditions for the right table manually

instead
```
select ...
from d_0 join d_1
where ..... and d_1. =....
```
use 
```
select ...
from d_0 join (select .... d_1 where d_1. =.... ) as d_1
where ..... 
```

**Comment by den-crane** [comment]
try to upgrade to 21.6.9.7

**Comment by SE2AI** [comment]
ok, but any ways avoiding crash? though ch can't give results, I think server shouldn't crash

**Comment by SE2AI** [comment]
ok, i ll post tomorrow, cuz it's under pressure test

**Comment by SE2AI** [comment]
thx den, I tune <max_mem_usage> to a smaller value, and the crash problem solved.
but met another `ast to big` problem, and it flushes in console continuously, even after the complex query executed
i ll create a new issue for it.
