### ISSUE TITLE
system.replication_queue is blocked

### ISSUE THREAD

**Issue by 825644691** [ClickHouse/ClickHouse#29505]
SELECT type,postpone_reason FROM system.replication_queue WHERE is_currently_executing

┌─type────────┬─postpone_reason─────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ MERGE_PARTS │                                                                                                                             │
│ MERGE_PARTS │                                                                                                                             │
│ MERGE_PARTS │                                                                                                                             │
│ MERGE_PARTS │                                                                                                                             │
│ MERGE_PARTS │                                                                                                                             │
│ GET_PART    │                                                                                                                             │
│ GET_PART    │                                                                                                                             │
│ GET_PART    │                                                                                                                             │
│ GET_PART    │                                                                                                                             │
│ GET_PART    │                                                                                                                             │
│ GET_PART    │                                                                                                                             │
│ GET_PART    │                                                                                                                             │
│ GET_PART    │                                                                                                                             │
│ GET_PART    │ Not executing fetch of part 1f92a8a309110cb78af3998adb2fb2df_1503_2997_4 because 100 fetches already executing, max 100.    │
│ GET_PART    │ Not executing fetch of part 21fb30adf1eb403d421aa7d0ec89f2fb_0_1307_4 because 100 fetches already executing, max 100.       │
│ GET_PART    │ Not executing fetch of part 288ddfe71265204f3782e75f2a2572c7_0_1512_4 because 100 fetches already executing, max 100.       │
│ GET_PART    │ Not executing fetch of part 288ddfe71265204f3782e75f2a2572c7_1513_9435_5 because 100 fetches already executing, max 100.    │
│ GET_PART    │ Not executing fetch of part 2a5a060bc8d8346efbf674f3eed17bdf_1297_7386_5 because 100 fetches already executing, max 100.    │
│ GET_PART    │ Not executing fetch of part 2a5a060bc8d8346efbf674f3eed17bdf_38077_38228_11 because 100 fetches already executing, max 100. │
│ GET_PART    │ Not executing fetch of part 2a5a060bc8d8346efbf674f3eed17bdf_38229_38340_12 because 100 fetches already executing, max 100. │
│ GET_PART    │ Not executing fetch of part 2c0e980bbfd1fdb8af4c5d604a1e5e55_0_1531_4 because 100 fetches already executing, max 100.       │
│ GET_PART    │ Not executing fetch of part 2c0e980bbfd1fdb8af4c5d604a1e5e55_1532_9797_5 because 100 fetches already executing, max 100.    │
│ GET_PART    │ Not executing fetch of part 372e3239d8e7762bd0d3fc181280982a_4380_16635_21 because 100 fetches already executing, max 100.  │
│ GET_PART    │ Not executing fetch of part 2c0e980bbfd1fdb8af4c5d604a1e5e55_76753_78918_19 because 100 fetches already executing, max 100. │
│ GET_PART    │ Not executing fetch of part 2c0e980bbfd1fdb8af4c5d604a1e5e55_9798_28812_11 because 100 fetches already executing, max 100.  │
│ GET_PART    │ Not executing fetch of part 2c0e980bbfd1fdb8af4c5d604a1e5e55_28813_38668_14 because 100 fetches already executing, max 100. │
│ GET_PART    │ Not executing fetch of part 5f0c971c5abeed1718ad4ad19680cff6_0_5345_5 because 100 fetches already executing, max 100.       │
│ GET_PART    │ Not executing fetch of part 2c0e980bbfd1fdb8af4c5d604a1e5e55_38669_48569_14 because 100 fetches already executing, max 100. │
│ GET_PART    │ Not executing fetch of part 2c0e980bbfd1fdb8af4c5d604a1e5e55_48570_58349_18 because 100 fetches already executing, max 100. │
│ GET_PART    │ Not executing fetch of part 2c0e980bbfd1fdb8af4c5d604a1e5e55_58350_67365_18 because 100 fetches already executing, max 100. │
│ GET_PART    │ Not executing fetch of part 2c0e980bbfd1fdb8af4c5d604a1e5e55_67366_72557_23 because 100 fetches already executing, max 100. │
│ GET_PART    │ Not executing fetch of part 2c0e980bbfd1fdb8af4c5d604a1e5e55_78919_79011_12 because 100 fetches already executing, max 100. │
│ GET_PART    │ Not executing fetch of part 8c632e3f2c2f614aa76bb171dc3cbd9e_13728_13751_5 because 100 fetches already executing, max 100.  │
│ GET_PART    │ Not executing fetch of part 2c0e980bbfd1fdb8af4c5d604a1e5e55_79012_79079_14 because 100 fetches already executing, max 100. │
│ GET_PART    │ Not executing fetch of part 94c06e95fdd8429401cb9fbe534a191d_83284_83284_0 because 100 fetches already executing, max 100.  │
│ GET_PART    │ Not executing fetch of part 2c0e980bbfd1fdb8af4c5d604a1e5e55_79080_79084_1 because 100 fetches already executing, max 100.  │
│ GET_PART    │ Not executing fetch of part 2c6dc0dcff59357163cb4be83dc5f286_0_3916_6 because 100 fetches already executing, max 100.       │
│ GET_PART    │ Not executing fetch of part cfb4249273daf481870905aae74e24b4_5412_5412_0 because 100 fetches already executing, max 100.    │
│ GET_PART    │ Not executing fetch of part 4f724746b2e005886f8ffc0eb82ada8d_85169_85169_0 because 100 fetches already executing, max 100.  │
│ GET_PART    │ Not executing fetch of part 6bdaf2348020ba98543b409720df4282_82035_87359_20 because 100 fetches already executing, max 100. │
│ GET_PART    │ Not executing fetch of part 2c6dc0dcff59357163cb4be83dc5f286_3917_7752_11 because 100 fetches already executing, max 100.   │
│ GET_PART    │ Not executing fetch of part 2c6dc0dcff59357163cb4be83dc5f286_7753_9618_12 because 100 fetches already executing, max 100.   │
│ GET_PART    │ Not executing fetch of part 57b9dab726e1876e2d23399af8615e01_9684_9684_0 because 100 fetches already executing, max 100.    │
│ GET_PART    │ Not executing fetch of part 2c6dc0dcff59357163cb4be83dc5f286_9619_15211_15 because 100 fetches already executing, max 100.  │
│ GET_PART    │ Not executing fetch of part e38b7ed040737de29a8d8b6e1735531b_0_3657_5 because 100 fetches already executing, max 100.       │
│ MERGE_PARTS │                                                                                                                             │
│ MERGE_PARTS │                                                                                                                             │
│ GET_PART    │ Not executing fetch of part 2c6dc0dcff59357163cb4be83dc5f286_21376_21376_0 because 100 fetches already executing, max 100.  │
│ GET_PART    │ Not executing fetch of part 3a5fb2670d9e5d4b0f5395c5a4bf62eb_6736_8906_4 because 100 fetches already executing, max 100.    │
│ MERGE_PARTS │                                                                                                                             │
│ MERGE_PARTS │                                                                                                                             │
│ GET_PART    │ Not executing fetch of part 2c6dc0dcff59357163cb4be83dc5f286_21377_21377_0 because 100 fetches already executing, max 100.  │
│ MERGE_PARTS │                                                                                                                             │
│ MERGE_PARTS │                                                                                                                             │
│ MERGE_PARTS │                                                                                                                             │
│ MERGE_PARTS │                                                                                                                             │
│ MERGE_PARTS │                                                                                                                             │
│ MERGE_PARTS │                                                                                                                             │
│ MERGE_PARTS │                                                                                                                             │
│ MERGE_PARTS │                                                                                                                             │
│ GET_PART    │ Not executing fetch of part 82ea87233ff8a311f0858f92633580d8_1583_9199_5 because 100 fetches already executing, max 100.    │
│ GET_PART    │ Not executing fetch of part 3a5fb2670d9e5d4b0f5395c5a4bf62eb_10653_19810_8 because 100 fetches already executing, max 100.  │
│ GET_PART    │ Not executing fetch of part 36ef23adec8a77f1a8cedf716e3deeab_9517_23237_10 because 100 fetches already executing, max 100.  │
│ MERGE_PARTS │                                                                                                                             │
│ GET_PART    │ Not executing fetch of part 6c7b1781be764d6d4de2331da6029577_5436_35308_17 because 100 fetches already executing, max 100.  │
│ MERGE_PARTS │                                                                                                                             │
│ MERGE_PARTS │                                                                                                                             │
│ MERGE_PARTS │                                                                                                                             │
│ MERGE_PARTS │                                                                                                                             │
│ MERGE_PARTS │                                                                                                                             │
│ MERGE_PARTS │                                                                                                                             │
│ MERGE_PARTS │                                                                                                                             │
│ MERGE_PARTS │                                                                                                                             │
│ MERGE_PARTS │                                                                                                                             │
│ MERGE_PARTS │                                                                                                                             │
│ MERGE_PARTS │                                                                                                                             │
│ MERGE_PARTS │                                                                                                                             │
│ MERGE_PARTS │                                                                                                                             │
│ MERGE_PARTS │                                                                                                                             │
│ MERGE_PARTS │                                                                                                                             │
│ GET_PART    │ Not executing fetch of part 2c6dc0dcff59357163cb4be83dc5f286_20554_20822_13 because 100 fetches already executing, max 100. │
│ GET_PART    │ Not executing fetch of part 2c6dc0dcff59357163cb4be83dc5f286_20823_21093_15 because 100 fetches already executing, max 100. │
│ GET_PART    │ Not executing fetch of part 2c6dc0dcff59357163cb4be83dc5f286_21094_21352_16 because 100 fetches already executing, max 100. │
│ GET_PART    │ Not executing fetch of part 2f0285e98a4f0452d6ce4b54593ee047_0_3817_5 because 100 fetches already executing, max 100.       │
│ GET_PART    │ Not executing fetch of part 2f0285e98a4f0452d6ce4b54593ee047_19244_47966_27 because 100 fetches already executing, max 100. │
│ GET_PART    │ Not executing fetch of part 2f0285e98a4f0452d6ce4b54593ee047_47967_52740_30 because 100 fetches already executing, max 100. │
│ GET_PART    │ Not executing fetch of part 2f0285e98a4f0452d6ce4b54593ee047_52741_54823_30 because 100 fetches already executing, max 100. │
│ GET_PART    │ Not executing fetch of part 2f0285e98a4f0452d6ce4b54593ee047_54824_55500_30 because 100 fetches already executing, max 100. │
│ GET_PART    │ Not executing fetch of part 2f0285e98a4f0452d6ce4b54593ee047_55501_55566_14 because 100 fetches already executing, max 100. │
│ GET_PART    │ Not executing fetch of part f9794e6454a7ce1de6beff20a1553a54_0_8139_6 because 100 fetches already executing, max 100.       │
│ GET_PART    │ Not executing fetch of part 2f9a26f355b8ff50b8c60744a481e263_246_4547_5 because 100 fetches already executing, max 100.     │
│ GET_PART    │ Not executing fetch of part 2f9a26f355b8ff50b8c60744a481e263_4548_14934_10 because 100 fetches already executing, max 100.  │
│ GET_PART    │ Not executing fetch of part 2f9a26f355b8ff50b8c60744a481e263_14935_19104_10 because 100 fetches already executing, max 100. │
│ GET_PART    │ Not executing fetch of part 2f9a26f355b8ff50b8c60744a481e263_19105_24793_12 because 100 fetches already executing, max 100. │
│ GET_PART    │ Not executing fetch of part 64acf5b9a1c62b58d33479c2149d5cd7_81698_81698_0 because 100 fetches already executing, max 100.  │
│ GET_PART    │ Not executing fetch of part ef3fd12ff4260892498e4a9bb0d29ae9_31811_31811_0 because 100 fetches already executing, max 100.  │
│ GET_PART    │ Not executing fetch of part 2f9a26f355b8ff50b8c60744a481e263_37759_38499_12 because 100 fetches already executing, max 100. │
│ GET_PART    │ Not executing fetch of part 2f9a26f355b8ff50b8c60744a481e263_38500_38803_11 because 100 fetches already executing, max 100. │
│ GET_PART    │ Not executing fetch of part 57b9dab726e1876e2d23399af8615e01_9699_9699_0 because 100 fetches already executing, max 100.    │
│ GET_PART    │ Not executing fetch of part 2f9a26f355b8ff50b8c60744a481e263_38804_39060_11 because 100 fetches already executing, max 100. │
│ GET_PART    │ Not executing fetch of part d4d527ac8de0e37c931204aea3602ddf_39330_39330_0 because 100 fetches already executing, max 100.  │
│ GET_PART    │ Not executing fetch of part 2fb895f242a65ff779f63f049b9f009b_0_7976_5 because 100 fetches already executing, max 100.       │
│ GET_PART    │ Not executing fetch of part 2fb895f242a65ff779f63f049b9f009b_7977_9867_4 because 100 fetches already executing, max 100.    │
│ GET_PART    │ Not executing fetch of part cfb4249273daf481870905aae74e24b4_5736_5736_0 because 100 fetches already executing, max 100.    │
│ GET_PART    │ Not executing fetch of part 14608a93af7bce833dc14b58443b1361_24076_24076_0 because 100 fetches already executing, max 100.  │
│ GET_PART    │ Not executing fetch of part 2a5a060bc8d8346efbf674f3eed17bdf_38351_38351_0 because 100 fetches already executing, max 100.  │
│ GET_PART    │ Not executing fetch of part 2a5a060bc8d8346efbf674f3eed17bdf_38352_38352_0 because 100 fetches already executing, max 100.  │
│ GET_PART    │ Not executing fetch of part 2fb895f242a65ff779f63f049b9f009b_9868_12711_7 because 100 fetches already executing, max 100.   │
│ GET_PART    │ Not executing fetch of part 2fb895f242a65ff779f63f049b9f009b_80526_85287_13 because 100 fetches already executing, max 100. │
│ GET_PART    │ Not executing fetch of part 2fb895f242a65ff779f63f049b9f009b_12712_21871_8 because 100 fetches already executing, max 100.  │
│ MERGE_PARTS │                                                                                                                             │
│ MERGE_PARTS │                                                                                                                             │
│ MERGE_PARTS │                                                                                                                             │
│ MERGE_PARTS │                                                                                                                             │
│ MERGE_PARTS │                                                                                                                             │
│ MERGE_PARTS │                                                                                                                             │
│ MERGE_PARTS │                                                                                                                             │
│ GET_PART    │ Not executing fetch of part bd6e4d898eed9a29758df70384f708d3_46653_46890_23 because 100 fetches already executing, max 100. │
│ MERGE_PARTS │                                                                                                                             │
│ MERGE_PARTS │                                                                                                                             │
│ GET_PART    │ Not executing fetch of part a142e1fcfa64281b9c98774a2b55a48f_1676_3096_4 because 100 fetches already executing, max 100.    │
│ MERGE_PARTS │                                                                                                                             │
│ MERGE_PARTS │                                                                                                                             │
│ MERGE_PARTS │                                                                                                                             │
│ MERGE_PARTS │                                                                                                                             │
│ MERGE_PARTS │                                                                                                                             │
│ MERGE_PARTS │                                                                                                                             │
│ MERGE_PARTS │                                                                                                                             │
│ MERGE_PARTS │                                                                                                                             │
│ MERGE_PARTS │                                                                                                                             │
│ MERGE_PARTS │                                                                                                                             │
│ GET_PART    │ Not executing fetch of part 6587072160b5b96ada051399848bd5bc_21597_21599_1 because 100 fetches already executing, max 100.  │
│ MERGE_PARTS │                                                                                                                             │
│ GET_PART    │ Not executing fetch of part 288ddfe71265204f3782e75f2a2572c7_4845_6804_4 because 100 fetches already executing, max 100.    │
│ MERGE_PARTS │                                                                                                                             │
│ MERGE_PARTS │                                                                                                                             │
│ MERGE_PARTS │                                                                                                                             │
│ MERGE_PARTS │                                                                                                                             │
│ MERGE_PARTS │                                                                                                                             │
│ MERGE_PARTS │                                                                                                                             │
│ MERGE_PARTS │                                                                                                                             │
│ MERGE_PARTS │                                                                                                                             │
│ MERGE_PARTS │                                                                                                                             │
│ MERGE_PARTS │                                                                                                                             │
│ MERGE_PARTS │                                                                                                                             │
│ GET_PART    │ Not executing fetch of part 6bdaf2348020ba98543b409720df4282_18077_36732_12 because 100 fetches already executing, max 100. │
│ GET_PART    │ Not executing fetch of part 1e4b213a5ba4f34f857500023405abf0_24623_26881_11 because 100 fetches already executing, max 100. │
│ GET_PART    │ Not executing fetch of part 0cf001c9729e7f54d3d6ddc81e41c45b_8379_10352_6 because 100 fetches already executing, max 100.   │
│ GET_PART    │ Not executing fetch of part 5955ab8f84329abba770c1b70eb4c27d_0_1505_4 because 100 fetches already executing, max 100.       │
│ GET_PART    │ Not executing fetch of part f6e9e1e68d07d5ebe29c2f5351e1b775_21806_21806_0 because 100 fetches already executing, max 100.  │
│ GET_PART    │ Not executing fetch of part 21fb30adf1eb403d421aa7d0ec89f2fb_53642_54056_23 because 100 fetches already executing, max 100. │
│ GET_PART    │ Not executing fetch of part 0de2376a776ff37ed7de8f35f207347b_10251_10251_0 because 100 fetches already executing, max 100.  │
│ GET_PART    │ Not executing fetch of part ca338bc7ee39836a2b1d230e64d534f2_48185_51854_21 because 100 fetches already executing, max 100. │
│ GET_PART    │ Not executing fetch of part 57b9dab726e1876e2d23399af8615e01_11430_11430_0 because 100 fetches already executing, max 100.  │
│ GET_PART    │ Not executing fetch of part 64acf5b9a1c62b58d33479c2149d5cd7_44759_50133_17 because 100 fetches already executing, max 100. │
│ GET_PART    │ Not executing fetch of part cfb4249273daf481870905aae74e24b4_6442_6449_1 because 100 fetches already executing, max 100.    │
│ GET_PART    │ Not executing fetch of part 91de3137a1261adbe328293c3993343c_35318_58332_24 because 100 fetches already executing, max 100. │
│ GET_PART    │ Not executing fetch of part 3a5fb2670d9e5d4b0f5395c5a4bf62eb_3090_3413_3 because 100 fetches already executing, max 100.    │
│ GET_PART    │ Not executing fetch of part 13f21c37d149b4e736ea9d6e518e909d_1834_2126_3 because 100 fetches already executing, max 100.    │
│ GET_PART    │ Not executing fetch of part 02850348b657da9d31a0d111e9b782e3_53694_54062_16 because 100 fetches already executing, max 100. │
│ GET_PART    │ Not executing fetch of part 3a5fb2670d9e5d4b0f5395c5a4bf62eb_54758_54758_0 because 100 fetches already executing, max 100.  │
│ GET_PART    │ Not executing fetch of part b63748c8bf324537a977b465409aa65b_63783_64905_18 because 100 fetches already executing, max 100. │
│ GET_PART    │ Not executing fetch of part 94c06e95fdd8429401cb9fbe534a191d_63914_63914_0 because 100 fetches already executing, max 100.  │
│ GET_PART    │ Not executing fetch of part 81bde1dd936ec4269e792db3dbf23693_10327_10327_0 because 100 fetches already executing, max 100.  │
└─────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

hello, I find clickhouse system.replication_queue is blocked
What should I do?
please help me please ...

**Comment by den-crane** [comment]
CH version?

```
SELECT
    name,
    value
FROM system.settings
WHERE name IN ('background_fetches_pool_size', 'background_schedule_pool_size', 'background_pool_size');
```

try 

```
cat /etc/clickhouse-server/users.d/pools.xml
<?xml version="1.0"?>
<yandex>
   <profiles>
       <default>
           <background_fetches_pool_size>8</background_fetches_pool_size>
           <background_schedule_pool_size>128</background_schedule_pool_size>
       </default>
   </profiles>
</yandex>
```
and reboot

**Comment by 825644691** [comment]
> SELECT
>     name,
>     value
> FROM system.settings
> WHERE name IN ('background_fetches_pool_size', 'background_schedule_pool_size', 'background_pool_size');

Thank you

gd15-clickhouse-accesslog17 :) SELECT
:-]     name,
:-]     value
:-] FROM system.settings
:-] WHERE name IN ('background_fetches_pool_size', 'background_schedule_pool_size', 'background_pool_size');

SELECT
    name,
    value
FROM system.settings
WHERE name IN ('background_fetches_pool_size', 'background_schedule_pool_size', 'background_pool_size')

Query id: 3d7412e7-4221-4876-abf6-e6adffe4d9da

┌─name──────────────────────────┬─value─┐
│ background_pool_size          │ 64    │
│ background_fetches_pool_size  │ 100   │
│ background_schedule_pool_size │ 100   │
└───────────────────────────────┴───────┘

3 rows in set. Elapsed: 0.003 sec. 

but it didn't work

**Comment by 825644691** [comment]
and now can't merge any part

│  1031 │ ('2021-09-28 08:00:00','compound_7') │
│  1038 │ ('2021-09-29 02:00:00','compound_7') │
│  1102 │ ('2021-09-27 20:00:00','compound_7') │
│  1107 │ ('2021-09-27 14:00:00','compound_7') │
│  1139 │ ('2021-09-27 22:00:00','compound_7') │
│  1262 │ ('2021-09-28 08:00:00','compound_7') │
│  1272 │ ('2021-09-29 04:00:00','compound_7') │
│  1336 │ ('2021-09-29 04:00:00','compound_7') │
│  1360 │ ('2021-09-28 12:00:00','compound_7') │
│  1400 │ ('2021-09-28 12:00:00','compound_7') │
│  1423 │ ('2021-09-28 14:00:00','compound_7') │
│  1501 │ ('2021-09-28 16:00:00','compound_7') │
│  1516 │ ('2021-09-28 16:00:00','compound_7') │
│  1727 │ ('2021-09-28 18:00:00','compound_7') │
│  1838 │ ('2021-09-29 00:00:00','compound_7') │
│  1890 │ ('2021-09-28 18:00:00','compound_7') │
│  1900 │ ('2021-09-29 00:00:00','compound_7') │
│  1915 │ ('2021-09-29 02:00:00','compound_7') │
│  2110 │ ('2021-09-28 22:00:00','compound_7') │
│  2485 │ ('2021-09-28 20:00:00','compound_7') │
│  4037 │ ('2021-09-29 06:00:00','compound_7') │
│  4948 │ ('2021-09-29 08:00:00','compound_7') │
│  5959 │ ('2021-09-29 08:00:00','compound_7') │
└───────┴──────────────────────────────────────┘

**Comment by 825644691** [comment]
SELECT count(*)
FROM system.replication_queue

Query id: c45b154c-444c-4a56-bf20-409de41e43b7

┌─count()─┐
│  133948 │
└─────────┘

and the queue ...
this shard has two replicas
I think is another replica 's problem?

**Comment by 825644691** [comment]
the replica delay long time 

database:                   accesslog
table:                      osp_proxy_2hour_local_7
engine:                     ReplicatedMergeTree
is_leader:                  1
can_become_leader:          1
is_readonly:                0
is_session_expired:         0
future_parts:               88
parts_to_check:             0
zookeeper_path:             /clickhouse/tables/9/osp_proxy_2hour_local_7_2
replica_name:               3
replica_path:               /clickhouse/tables/9/osp_proxy_2hour_local_7_2/replicas/3
columns_version:            -1
queue_size:                 58570
inserts_in_queue:           48384
merges_in_queue:            10186
part_mutations_in_queue:    0
queue_oldest_time:          2021-09-21 22:05:51
inserts_oldest_time:        2021-09-21 22:05:51
merges_oldest_time:         2021-09-29 08:40:58
part_mutations_oldest_time: 1970-01-01 08:00:00
oldest_part_to_get:         5deb9a9ad6461545c47f56a940a0c0ad_10961_11232_3
oldest_part_to_merge_to:    0de2376a776ff37ed7de8f35f207347b_0_7020_5
oldest_part_to_mutate_to:   
log_max_index:              10109606
log_pointer:                10109596
last_queue_update:          2021-09-29 11:07:15
absolute_delay:             651685
total_replicas:             2
active_replicas:            2
zookeeper_exception:        


SELECT
    database,
    table,
    type,
    any(last_exception),
    any(postpone_reason),
    min(create_time),
    max(last_attempt_time),
    max(last_postpone_time),
    max(num_postponed) AS max_postponed,
    max(num_tries) AS max_tries,
    min(num_tries) AS min_tries,
    countIf(last_exception != '') AS count_err,
    countIf(num_postponed > 0) AS count_postponed,
    countIf(is_currently_executing) AS count_executing,
    count() AS count_all
FROM system.replication_queue
GROUP BY
    database,
    table,
    type
ORDER BY count_all DESC

Query id: 38045177-2295-4fa7-9543-ca3cc430a72d

Row 1:
──────
database:                accesslog
table:                   osp_2hour_local_7
type:                    GET_PART
any(last_exception):     
any(postpone_reason):    Not executing log entry queue-0000185617 for part 2f9a26f355b8ff50b8c60744a481e263_39061_39283_15 because it is covered by part 2f9a26f355b8ff50b8c60744a481e263_36684_39438_16 that is currently executing.
min(create_time):        2021-09-22 07:24:12
max(last_attempt_time):  2021-09-29 10:26:14
max(last_postpone_time): 2021-09-29 11:08:35
max_postponed:           12324
max_tries:               1
min_tries:               0
count_err:               15
count_postponed:         25202
count_executing:         54
count_all:               55960

Row 2:
──────
database:                accesslog
table:                   osp_proxy_2hour_local_7
type:                    GET_PART
any(last_exception):     
any(postpone_reason):    Not executing fetch of part 02850348b657da9d31a0d111e9b782e3_52079_52609_8 because 100 fetches already executing, max 100.
min(create_time):        2021-09-21 22:05:51
max(last_attempt_time):  2021-09-29 11:02:39
max(last_postpone_time): 2021-09-29 11:08:36
max_postponed:           17555
max_tries:               1
min_tries:               0
count_err:               0
count_postponed:         27831
count_executing:         41
count_all:               48948

**Comment by den-crane** [comment]
Why have you set `│ background_fetches_pool_size │ 100 │` ?

**Comment by 825644691** [comment]
> Why have you set `│ background_fetches_pool_size │ 100 │` ?

is my fault
now is
SELECT
    name,
    value
FROM system.settings
WHERE name IN ('background_fetches_pool_size', 'background_schedule_pool_size', 'background_pool_size')

Query id: d161dc0c-0c64-4334-9ce4-c98670f20c93

┌─name──────────────────────────┬─value─┐
│ background_pool_size          │ 64    │
│ background_fetches_pool_size  │ 8     │
│ background_schedule_pool_size │ 128   │
└───────────────────────────────┴───────┘

**Comment by 825644691** [comment]
have any way to recover the replica?

**Comment by 825644691** [comment]
now I event can‘t create new replica,new replica also has this problem

**Comment by den-crane** [comment]
Can you share `select countIf(active), count() from system.parts`
How many inserts you do per second?
How many Replicated tables do you have?

**Comment by 825644691** [comment]
I delete all the data and zookeeper metadata  and restart the clickhouse, create table.
but it still always get_part and the replication_queue show me that "because 8 fetches already executing, max 8"
I have no idea what I can do

SELECT
    type,
    count(*)
FROM system.replication_queue
GROUP BY type

Query id: 6c49e9e6-fd12-4859-9ec2-927b146cf5e6

┌─type────────┬─count()─┐
│ GET_PART    │   16830 │
│ MERGE_PARTS │      21 │
└─────────────┴─────────┘

2 rows in set. Elapsed: 0.141 sec. Processed 16.85 thousand rows, 5.92 MB (119.55 thousand rows/s., 41.98 MB/s.)

gd15-clickhouse-accesslog17 :) select countIf(active), count() from system.parts

SELECT
    countIf(active),
    count()
FROM system.parts

Query id: de2e0fdb-549e-4586-86da-9b5a995e8377

┌─countIf(active)─┬─count()─┐
│             741 │    2836 │
└─────────────────┴─────────┘
┌─postpone_reason───────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Not executing fetch of part a142e1fcfa64281b9c98774a2b55a48f_1520_2688_4 because 8 fetches already executing, max 8.  │
│ Not executing fetch of part 2fb895f242a65ff779f63f049b9f009b_0_7976_5 because 8 fetches already executing, max 8.     │
│                                                                                                                       │
│ Not executing fetch of part 02850348b657da9d31a0d111e9b782e3_0_1358_4 because 8 fetches already executing, max 8.     │
│ Not executing fetch of part 02850348b657da9d31a0d111e9b782e3_1829_5234_4 because 8 fetches already executing, max 8.  │
│ Not executing fetch of part 02850348b657da9d31a0d111e9b782e3_5235_10478_5 because 8 fetches already executing, max 8. │
│ Not executing fetch of part c53381d2b2ff82dfda016be389109e87_2030_3632_4 because 8 fetches already executing, max 8.  │
│ Not executing fetch of part a969b9a500ed855215e735f9bff33233_0_4308_5 because 8 fetches already executing, max 8.     │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

**Comment by kernel288** [comment]
i use ClickHouse client version 23.3.17.13 (official build)
when i set background_fetches_pool_size 64 , alway said because 8 fetches already executing, max 8.  
I don't why it's not work? 


follow query setting 

┌─database─┬─table───────────────────┬─type─────┬─max(last_exception)─┬─max(postpone_reason)───────────────────────────────────────────────────────────────────────────────────────────┬────min(create_time)─┬─max(last_attempt_time)─┬─max(last_postpone_time)─┬─max_postponed─┬─max_tries─┬─min_tries─┬─count_err─┬─count_postponed─┬─count_executing─┬─count_all─┐
│ ztmdb    │ ZTO_SCAN_DISP_LOCAL     │ GET_PART │                     │ Not executing fetch of part ffeb18d84cbfe45fcc465c33aed39cfb_9_9_0 because 8 fetches already executing, max 8. │ 2024-04-20 04:54:33 │    2024-04-24 23:03:23 │     2024-04-24 23:03:23 │          2185 │         1 │         0 │         0 │          515812 │               2 │    515812 │
│ ztmdb    │ ZTO_SCAN_DISP_NEW_LOCAL │ GET_PART │                     │ Not executing fetch of part ffeb18d84cbfe45fcc465c33aed39cfb_0_0_0 because 8 fetches already executing, max 8. │ 2024-04-15 15:45:05 │    2024-04-24 23:03:25 │     2024-04-24 23:03:25 │          2349 │         1 │         0 │         0 │          461914 │               1 │    461914 │
└──────────┴─────────────────────────┴──────────┴─────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴─────────────────────┴────────────────────────┴─────────────────────────┴───────────────┴───────────┴───────────┴───────────┴─────────────────┴─────────────────┴───────────┘


SELECT
    name,
    value
FROM system.settings
WHERE name IN ('background_fetches_pool_size', 'background_schedule_pool_size', 'background_pool_size', 'max_concurrent_fetches')

Query id: 1c16bb82-285b-4538-ac57-dceba0b5b070

┌─name──────────────────────────┬─value─┐
│ background_pool_size          │ 96    │
│ background_fetches_pool_size  │ 64    │
│ background_schedule_pool_size │ 128   │
└───────────────────────────────┴───────┘

**Comment by tbragin** [comment]
Replication queue can get backed up because the replicas are not processing ingest workloads fast enough, for instance when merges are processing significantly slower than inserts. I’d look at overall system health first (especially around how data is inserted and how merges are happening), not at replication queue in isolation. 

Some useful resources:
https://clickhouse.com/docs/knowledgebase/exception-too-many-parts 
https://stackoverflow.com/questions/62489744/clickhouse-replica-out-of-sync 

Since the original ticket is quite a few years old, I'm going to close it. Please start new discussion if you see trouble on supported versions that are not covered by scenarios of general system overload https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md#scope-and-supported-versions
