### ISSUE TITLE
the right way to write the SQL statement?

### ISSUE THREAD

**Issue by vkingnew** [ClickHouse/ClickHouse#29517]
> SQL> select concat('user',toString(number)) u,number n,number/1000 m ,now()+(number*10) t from numbers(5);
>┌─u─────┬─n─┬─────m─┬───────────────────t─┐
│ user0 │ 0 │     0 │ 2021-09-29 06:16:12 │
│ user1 │ 1 │ 0.001 │ 2021-09-29 06:16:22 │
│ user2 │ 2 │ 0.002 │ 2021-09-29 06:16:32 │
│ user3 │ 3 │ 0.003 │ 2021-09-29 06:16:42 │
│ user4 │ 4 │ 0.004 │ 2021-09-29 06:16:52 │
└───────┴───┴───────┴─────────────────────┘

> `clickhouse-client # time clickhouse-client -q 'select concat(''user'',toString(number)) u,number n,number/1000 m ,now()+(number*10) t from numbers(100000000) format TSV' > speed.tsv`
>**Code: 47. DB::Exception: Received from localhost:9000. DB::Exception: Missing columns: 'user' while processing query: 'SELECT concat(user, toString(number)) AS u, number AS n, number / 1000 AS m, now() + (number * 10) AS t FROM numbers(100000000)', required columns: 'number' 'user', maybe you meant: ['number']. (UNKNOWN_IDENTIFIER)**

IN the clickhouse client ,how to write the right SQL statement?

**Comment by tavplubix** [comment]
```
$ time clickhouse-client -q "select concat('user',toString(number)) u,number n,number/1000 m ,now()+(number*10) t from numbers(100000000) format Null"
```
or
```
$ time clickhouse-client -q 'select concat('\''user'\'',toString(number)) u,number n,number/1000 m ,now()+(number*10) t from numbers(100000000) format Null'
```

However, your question is not about clickhouse-client, it's about bash, see https://stackoverflow.com/questions/1250079/how-to-escape-single-quotes-within-single-quoted-strings
