### ISSUE TITLE
Have a function like string_split in SQL server?

### ISSUE THREAD

**Issue by vkingnew** [ClickHouse/ClickHouse#29519]
>  master> SELECT value as name FROM STRING_SPLIT('Monday Tuesday Wednesday Thursday Friday Saturday Sunday', ' ');
Time: 0.463s
```
+-----------+
| name      |
|-----------|
| Monday    |
| Tuesday   |
| Wednesday |
| Thursday  |
| Friday    |
| Saturday  |
| Sunday    |
+-----------+
```
(7 rows affected)
[https://docs.microsoft.com/en-us/sql/t-sql/functions/string-split-transact-sql?view=sql-server-2017](url)

**Comment by kitaisreal** [comment]
@vkingnew has ArrayJoin https://clickhouse.com/docs/en/sql-reference/statements/select/array-join/, https://clickhouse.com/docs/en/sql-reference/functions/array-join/ . With arrayJoin your example can easily be implemented.
```
SELECT arrayJoin(splitByChar(' ', 'value1 value2'))
```
```
┌─arrayJoin(splitByChar(' ', 'value1 value2'))─┐
│ value1                                       │
│ value2                                       │
└──────────────────────────────────────────────┘
```
