### ISSUE TITLE
Suspiciously many (30) broken parts to remove

### ISSUE THREAD

**Issue by sagarshrestha24** [ClickHouse/ClickHouse#29522]
when i attach a table i got this issue

```
ATTACH TABLE ad_event_temp


Received exception from server (version 20.7.4):
Code: 231. DB::Exception: Received from localhost:9000. DB::Exception: Suspiciously many (30) broken parts to remove.. 

```

there is lots of data in this table

can anyone help ?

0 rows in set. Elapsed: 224.238 sec.

**Comment by pengliaoye** [comment]
have same problem

**Comment by filimonov** [comment]
https://kb.altinity.com/altinity-kb-setup-and-maintenance/suspiciously-many-broken-parts/

**Comment by sulayliu** [comment]
It looks like some parts were damaged (hard restart/filesystem issue etc). It's a circuit breaker, fired when the number of the damaged parts is high.
If you can accept the data loss, you can disable that check, like that:
`sudo -u clickhouse touch /var/lib/clickhouse/flags/force_restore_data `
then restart clickhouse

or config `max_suspicious_broken_parts` setting.

please see this article:
https://kb.altinity.com/altinity-kb-setup-and-maintenance/suspiciously-many-broken-parts/
