### ISSUE TITLE
Enable to run aggregations in TTL without GROUP BY 

### ISSUE THREAD

**Issue by alexon1234** [ClickHouse/ClickHouse#29533]
**Use case**

We are syncing MySQL to Clickhouse, but Clickhouse does not support well mutations (UPDATE, DELETE) that's why we came with a snapshot strategy in order to keep the data sync. 

We create two tables for each MySQL table: snapshot and landing.
The schema of the process is the following:

- Initial dump of the tables is inserted in the snapshot table
- Changes are being inserted in the landing table
- Periodically, a script will generate a new snapshot by merging the last changes with the last snapshot

When we want to get the data, we just need to query the last snapshot and everything is fine.

This approach works great as everything is just inserts and selects, no mutations. Less problems.
But there is a catch, the disk. 

The less lag (time needed to have a change inside the snapshot ), we want. The more frequent the script needs to run and the more disk we will need. For this, we could add a TTL to the table. 

But on the other hand, the less TTL time, the less time window we have to fix issues if something breaks. Having a small TTL could lead to losing data, so we need to have a balance.

**Describe the solution you'd like**

In this situation, it would be great to be able to define a TTL like 

```sql
TTL snapshot_time + 1 INTERVAL HOUR WHERE max(snapshot_time) != snapshot_time
```

If we would be able to define a TTL like the one above if the script would stop working, we will always keep the last snapshot. Avoiding losing data and being able to reduce TTL time.

**Describe alternatives you've considered**

Any idea or approach to dealing with real-time synchronization with MySQL is appreciated. We have checked the other MergeTree engines, but we have had no luck.

**Comment by den-crane** [comment]
How you can find max(snapshot_time) ?
`select max(snapshot_time) from snapshot_table` ?

**Comment by den-crane** [comment]
So you can make a dictionary, with a query `select 1 id, max(snapshot_time) x from snapshot_table`

And then TTL rule `TTL snapshot_time + 1 INTERVAL HOUR WHERE gictGet(..., 'x', 1) != snapshot_time

**Comment by alexon1234** [comment]
I will take a look. Thanks for the advise

**Comment by den-crane** [comment]
TTL merger processes only one part a time and considers data of a single row (single key in case of TTL group) it's impossible to access data in other parts or other tables. 

Maybe your task is possible to implement using TTL_Group_by or AggregatingMergeTree. It's unclear now because I don't see table structure and test data.
