### ISSUE TITLE
Can not insert  in clickhouse-keeper 

### ISSUE THREAD

**Issue by Data-bytes305** [ClickHouse/ClickHouse#29566]
```
<keeper_server>
        <tcp_port>2181</tcp_port>
        <server_id>99</server_id>
        <log_storage_path>/home/data/clickhouse/coordination/log</log_storage_path>
        <snapshot_storage_path>/home/data/clickhouse/coordination/snapshots</snapshot_storage_path>
        <coordination_settings>
            <operation_timeout_ms>10000</operation_timeout_ms>
            <session_timeout_ms>30000</session_timeout_ms>
            <raft_logs_level>trace</raft_logs_level>
        </coordination_settings>
        <raft_configuration>
            <server>
                <id>99</id>
                <hostname>ck_server3</hostname>
                <port>9444</port>
            </server>
            <server>
                <id>98</id>
                <hostname>ck_server2</hostname>
                <port>9444</port>
            </server>
            <server>
                <id>97</id>
                <hostname>ck_server1</hostname>
                <port>9444</port>
            </server>
        </raft_configuration>
  </keeper_server>

 <zookeeper>
        <node index="99">
            <host>ck_server3</host>
            <port>2181</port>
        </node>
        <node index="98">
            <host>ck_server2</host>
            <port>2181</port>
        </node>
         <node index="97">
            <host>ck_server1</host>
            <port>2181</port>
        </node>
    </zookeeper>

```

1. ` create table tdm.test_shard1rep2(userid UInt64,　   age UInt64　) ENGINE = ReplicatedMergeTree('/clickhouser/dev/test_shard1rep2', '{replica}') PARTITION BY userid % 100　ORDER BY userid;`

CREATE TABLE tdm.test_shard1rep2
(
    `userid` UInt64,
    `age` UInt64
)
ENGINE = ReplicatedMergeTree('/clickhouser/dev/test_shard1rep2', '{replica}')
PARTITION BY userid % 100
ORDER BY userid

Query id: a9cc48fa-e53f-45e0-9a70-1ddb1b779850

Ok.

0 rows in set. Elapsed: 0.057 sec. 

2.  `insert into tdm.test_shard1rep2(userid, age) values(1, 24);`

INSERT INTO tdm.test_shard1rep2 (userid, age) VALUES

Query id: 9bbbaf4f-59d2-4646-875f-f52db1826c26

0 rows in set. Elapsed: 0.003 sec. 

Received exception from server (version 21.10.1):
Code: 242. DB::Exception: Received from 168.30.16.99:9000. DB::Exception: Table is in readonly mode (zookeeper path: /clickhouser/dev/test_shard1rep2). (TABLE_IS_READ_ONLY)

**Comment by alesapin** [comment]
Can you provide server logs please?

**Comment by Data-bytes305** [comment]
@alesapin  Thank you. I found the reason .  solution:  config.xml add  <interserver_http_port>9009</interserver_http_port>
