### ISSUE TITLE
Support sending user defined tags with sentry crash reports

### ISSUE THREAD

**Issue by nvartolomei** [ClickHouse/ClickHouse#29587]
It would be great to allow sending of additional/arbitrary tags with sentry crash report. These would allow for better filtering and aggregations in the Sentry UI.

Eg hostname would be great to be sent as tag, this would allow seeing % of crashes by hostname (example https://try.sentry-demo.com/organizations/fresh-moccasin/issues/413055/tags/device/?project=147865)

Additional ones could be things like physical/logical cluster name, data center and so on.

An idea is to extend `send_crash_reports` section with tags, example:

```xml
<clickhouse>
    <send_crash_reports>
       <tags>
            <hostname>play.clickhouse.tech</hostname>
            <cluster>play</cluster>
            <!-- ... -->
        </tags>

        <!-- Changing <enabled> to true allows sending crash reports to -->
        <!-- the ClickHouse core developers team via Sentry https://sentry.io -->
        <!-- Doing so at least in pre-production environments is highly appreciated -->
        <enabled>false</enabled>
        <!-- Change <anonymize> to true if you don't feel comfortable attaching the server hostname to the crash report -->
        <anonymize>false</anonymize>
        <!-- Default endpoint should be changed to different Sentry DSN only if you have -->
        <!-- some in-house engineers or hired consultants who're going to debug ClickHouse issues for you -->
        <endpoint>https://6f33034cfe684dd7a3ab9875e57b1c8d@o388870.ingest.sentry.io/5226277</endpoint>
    </send_crash_reports>
</clickhouse>
```

https://github.com/ClickHouse/ClickHouse/blob/3e0d4faa1e652189e7d4efa67e6849aeadefb0c5/programs/server/config.xml#L1195-L1205

**Comment by alexey-milovidov** [comment]
Ok.

Btw, we receive zero crashes via sentry. We also don't have any crashes in Yandex Metrica production.
If you have crashes on recent updated versions in production - it will be very helpful if you can enable Sentry with default endpoint.

**Comment by alexey-milovidov** [comment]
This feature is not in our roadmap. Help needed.

**Comment by alexey-milovidov** [comment]
Not relevant.
