### ISSUE TITLE
`Column not found in block` when mixing different ClickHouse versions

### ISSUE THREAD

**Issue by nvartolomei** [ClickHouse/ClickHouse#29582]
This issue covers 2 issues, one is `sum-if` to `countIf` optimization controlled by `optimize_rewrite_sum_if_to_count_if`
and the other one is `avg(col * 2)` to `avg(col) * 2` optimization controlled by `optimize_arithmetic_operations_in_aggregate_functions`.

I have reported some other ones (and skipped reporting some...) like #28796, #26027 and #29284.

Maybe also #25371

Currently, the process of upgrading production clusters is very painful due to all these introduced incompatibilities. You have to either:

* Disable setting on new nodes. This is not always possible when servers are managed together and profiles for example are loaded from centralized config store like ZooKeeper as old servers don't understand these new settings.
* Add code to disable these settings when queries come from old servers.
* And, usually you need both.

I was thinking whether we could come up with a generic solution for solving these type of issues.

What if in distributed query processing the root server would be the only one doing query rewriting that could affect resulting block structure. This would solve the case for queries originating from older servers sent to newer servers that do "smarter" rewriting/optimizations (like the issue covered by the test at the bottom of this ticket).

```py
import pytest

from helpers.cluster import ClickHouseCluster

cluster = ClickHouseCluster(__file__)
node1 = cluster.add_instance('node1', with_zookeeper=True, image='yandex/clickhouse-server', tag='20.8', with_installed_binary=True)
node2 = cluster.add_instance('node2', with_zookeeper=True)
node3 = cluster.add_instance('node3', with_zookeeper=True)


@pytest.fixture(scope="module")
def start_cluster():
    try:
        cluster.start()
        yield cluster

    finally:
        cluster.shutdown()


def test_syntax_optimizations_aggregation(start_cluster):
    queries = [
        """
        SELECT
            sum(if(dummy IN (1), 1, 0))
        FROM
            {}
        """,
        """
        SELECT
            avg(dummy * 2)
        FROM
            {}
        GROUP BY 'const'
        """
    ]

    sources = [
        "system.one",
        "remote('node{1,2,3}', system.one)"
    ]

    for test_query in queries:
        for source in sources:
            node1.query(test_query.format(source))
            node2.query(test_query.format(source))

```

**Comment by alexey-milovidov** [comment]
> What if in distributed query processing the root server would be the only one doing query rewriting that could affect resulting block structure.

Yes, maybe we can try it.

**Comment by amosbird** [comment]
Found this issue when developing https://github.com/ClickHouse/ClickHouse/pull/28746/files#diff-03665017349505c5529e5d0eeeeae80081e064267d6035b94cd428baf11856ceR951

**Comment by alexey-milovidov** [comment]
If you do rolling upgrade and encounter this error, proceed with upgrading and the error will go away after finishing the upgrading process.

It may require small downtime for small part of the queries.
