### ISSUE TITLE
Add `getOSKernelVersion()` function.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#29599]
Returns `String` with OS Kernel version.
For simplicity, the function can be implemented only for Linux.

The version string can contain alphabetical parts at the end, we should return complete value. Example:

```
$ uname -r
5.4.0-84-generic
```

**Comment by den-crane** [comment]
may be  uname -v ?
```
uname -v
#1 SMP Debian 5.6.14-2~bpo10+1 (2020-06-09)
```

**Comment by alexey-milovidov** [comment]
Let's grab something from here :)

`man 2 uname`

```
           struct utsname {
               char sysname[];    /* Operating system name (e.g., "Linux") */
               char nodename[];   /* Name within "some implementation-defined
                                     network" */
               char release[];    /* Operating system release (e.g., "2.6.28") */
               char version[];    /* Operating system version */
               char machine[];    /* Hardware identifier */
```

**Comment by den-crane** [comment]
BTW, I see different numbers

```
uname -r
5.6.0-0.bpo.2-amd64

uname -v
#1 SMP Debian 5.6.14-2~bpo10+1 (2020-06-09)

uname -a
Linux chdw1-4 5.6.0-0.bpo.2-amd64 #1 SMP Debian 5.6.14-2~bpo10+1 (2020-06-09) x86_64 GNU/Linux
```

**Comment by Joeywzr** [comment]
hi, I'd like to do this.

**Comment by alexey-milovidov** [comment]
Thank you! Let's do it.

**Comment by Joeywzr** [comment]
What about adding some subfunctions like `String getSysName()`, `String getNodeName()`? Or we just return all of the infomation in one string?

**Comment by amosbird** [comment]
> What about adding some subfunctions like `String getSysName()`, `String getNodeName()`? Or we just return all of the infomation in one string?

If it's intended to be a relational data, we can implement as a table function like `select * from kernelInfo()` or a system table instead.

**Comment by alexey-milovidov** [comment]
@Joeywzr Let's make one function `getOSKernelVersion` that will return `char release[];    /* Operating system release (e.g., "2.6.28") */`

Other functions not needed for now.

@amosbird Or even a system table. But it looks like overkill. Let's not do that.

**Comment by Joeywzr** [comment]
@alexey-milovidov OK
