### ISSUE TITLE
Bad cast in `JSONExtractString`

### ISSUE THREAD

**Issue by vdimir** [ClickHouse/ClickHouse#29619]
Fuzzer report from [`ce844e4` (#29281)](https://github.com/ClickHouse/ClickHouse/pull/29281/commits/ce844e4f050658a1b0f12066b784ed0d35e06de4)

https://clickhouse-test-reports.s3.yandex.net/29281/ce844e4f050658a1b0f12066b784ed0d35e06de4/fuzzer_ubsan/report.html#fail1

Query:
```
SELECT JSONExtractString('["a", "b", "c", "d", "e"]', idx) FROM (SELECT arrayJoin([2, NULL, 2147483646, 65535, 65535, 3]) AS idx);
```

```
Logical error: 'Bad cast from type DB::ColumnNullable to DB::ColumnString'.
```

**Comment by tavplubix** [comment]
Can be related: #29615

**Comment by vdimir** [comment]
> Can be related: #29615

Yeah, I suppose it's duplicate
