### ISSUE TITLE
Zookeeper load balancing settings

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#29617]
There are use cases when one of the zookeeper nodes is preferred - same AZ in the cloud, or you just to avoid the situations when all the clickhouse nodes will connect accidentally to the same zookeeper node, etc. 

The proposed solution is a setting 
```xml
<zookeeper_load_balancing>random / in_order / nearest_hostname / first_or_random / round_robin</zookeeper_load_balancing>
```

`random` would be the default

**Comment by nicelulu** [comment]
Thanks for reminding.

**Comment by djuarezg** [comment]
@FrankChen021 have you tried https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings/#server-settings_zookeeper -> `index` ?
