### ISSUE TITLE
AggregatingTransform merges temporary files slowly + limit the max number of temporary files 

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#29622]
Test case:

```sql
select 
  max(length(s))
from numbers_mt(getSetting('max_block_size')*5000) as l
left join (
   select number, repeat(toString(number),1000000) s from numbers(500)
) as righ_1G_table
using (number)
group by intDiv(number,getSetting('max_block_size')*1000)
SETTINGS max_bytes_before_external_group_by='500M';
```

Here the JOIN part uses a lot of ram and leads to triggering `max_bytes_before_external_group_by` immediately. (It's actually a bit confusing).

After that GROUP BY creates a lot of temporary files (5000 in that synthetic sample).

Merging those files takes an enormous amount of time (is it expected?)

Also, we need to introduce some limit on a number of temporary files: AggregatingTransform can create  very high number of temporary files - in real life example it was:
```
AggregatingTransform: Will merge 93786 temporary files of size 2.41 GiB compressed, 22.10 GiB uncompressed.
```

And clickhouse was even hitting ulimit nofiles due to that (when few similar queries was started).

**Comment by kitaisreal** [comment]
Fixed in https://github.com/ClickHouse/ClickHouse/pull/55489.

```
select 
  max(length(s))
from numbers_mt(getSetting('max_block_size')*5000) as l
left join (
   select number, repeat(toString(number),1000000) s from numbers(500)
) as righ_1G_table
using (number)
group by intDiv(number,getSetting('max_block_size')*1000)
SETTINGS max_bytes_before_external_group_by='500M';

5 rows in set. Elapsed: 4.830 sec. Processed 327.05 million rows, 2.62 GB (67.71 million rows/s., 541.67 MB/s.)
Peak memory usage: 4.06 GiB.
```
