### ISSUE TITLE
A potential problem with detach and attach

### ISSUE THREAD

**Issue by helifu** [ClickHouse/ClickHouse#29669]
**The operation process is as follows:**
1. create a mergetree table:
_CREATE TABLE default.table1
(
    `timestamp` DateTime,
    `id` String,
    `name` String,
    `comment` String
)
ENGINE = MergeTree
PARTITION BY toDate(timestamp)
ORDER BY (timestamp, id)_

2. insert some parts:
_insert into table1 select toDate('2021-10-03'), toString(rand(1)), toString(rand(1)), toString(rand(1)) from numbers(200000);_

3. optimize table and check parts:
_optimize table table1_
_select partition,name,part_type,active,bytes_on_disk from system.parts where table = 'table1';_
┌─partition──┬─name───────────┬─part_type─┬─active─┬─bytes_on_disk─┐
│ 2021-10-03 │ 20211003_1_1_0 │ Wide      │      0 │       4655368 │
│ 2021-10-03 │ **20211003_1_5_1**│ Wide      │      1 │      21418580 │
│ 2021-10-03 │ 20211003_2_2_0 │ Wide      │      0 │       4655723 │
│ 2021-10-03 │ 20211003_3_3_0 │ Wide      │      0 │       4653946 │
│ 2021-10-03 │ 20211003_4_4_0 │ Wide      │      0 │       4654628 │
│ 2021-10-03 │ 20211003_5_5_0 │ Wide      │      0 │       4655027 │
└────────────┴────────────────┴───────────┴────────┴───────────────┘

4. detach part and check parts:
_alter table table1 detach part '20211003_1_5_1';_
_select partition,name,part_type,active,bytes_on_disk from system.parts where table = 'table1';_
┌─partition──┬─name───────────┬─part_type─┬─active─┬─bytes_on_disk─┐
│ 2021-10-03 │ 20211003_1_1_0 │ Wide      │      0 │       4655368 │
│ 2021-10-03 │ 20211003_2_2_0 │ Wide      │      0 │       4655723 │
│ 2021-10-03 │ 20211003_3_3_0 │ Wide      │      0 │       4653946 │
│ 2021-10-03 │ 20211003_4_4_0 │ Wide      │      0 │       4654628 │
│ 2021-10-03 │ 20211003_5_5_0 │ Wide      │      0 │       4655027 │
└────────────┴────────────────┴───────────┴────────┴───────────────┘

5. attach part and check part:
_alter table table1 attach part '20211003_1_5_1';_
_select partition,name,part_type,active,bytes_on_disk from system.parts where table = 'table1';_
┌─partition──┬─name───────────┬─part_type─┬─active─┬─bytes_on_disk─┐
│ 2021-10-03 │ 20211003_1_1_0 │ Wide      │      0 │       4655368 │
│ 2021-10-03 │ 20211003_2_2_0 │ Wide      │      0 │       4655723 │
│ 2021-10-03 │ 20211003_3_3_0 │ Wide      │      0 │       4653946 │
│ 2021-10-03 │ 20211003_4_4_0 │ Wide      │      0 │       4654628 │
│ 2021-10-03 │ 20211003_5_5_0 │ Wide      │      0 │       4655027 │
│ 2021-10-03 │ **20211003_6_6_1**│ Wide      │      1 │      21418580 │
└────────────┴────────────────┴───────────┴────────┴───────────────┘
6. reboot clickhouse and check part:
_select partition,name,part_type,active,bytes_on_disk from system.parts where table = 'table1';_
┌─partition──┬─name───────────┬─part_type─┬─active─┬─bytes_on_disk─┐
│ 2021-10-03 │ 20211003_1_1_0 │ Wide      │      0 │       4655368 │
│ 2021-10-03 │ **20211003_1_5_1**│ Wide      │      1 │      21418580 │
│ 2021-10-03 │ 20211003_2_2_0 │ Wide      │      0 │       4655723 │
│ 2021-10-03 │ 20211003_3_3_0 │ Wide      │      0 │       4653946 │
│ 2021-10-03 │ 20211003_4_4_0 │ Wide      │      0 │       4654628 │
│ 2021-10-03 │ 20211003_5_5_0 │ Wide      │      0 │       4655027 │
│ 2021-10-03 │ **20211003_6_6_1**│ Wide      │      1 │      21418580 │
└────────────┴────────────────┴───────────┴────────┴───────────────┘

7. the duplicate data part appears:  '20211003_1_5_1' vs '20211003_6_6_0'

**Comment by tavplubix** [comment]
Similar issue was fixed a long time ago: #8584
Which version of ClickHouse do you use?

**Comment by den-crane** [comment]
it depends of how a restart is done, if it was not graceful restart than it's expected https://github.com/ClickHouse/ClickHouse/issues/15742

**Comment by helifu** [comment]
> Similar issue was fixed a long time ago: #8584 Which version of ClickHouse do you use?

```
ecs-6f4c :) select name,value from system.build_options;

SELECT
    name,
    value
FROM system.build_options

Query id: 6feff18e-2086-4557-81f9-7edecea233d6

┌─name──────────────────────┬─value────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ VERSION_FULL              │ ClickHouse 21.11.1.1                                                                                                                                     │
│ VERSION_DESCRIBE          │ v21.11.1.1-prestable                                                                                                                                     │
│ VERSION_INTEGER           │ 21011001                                                                                                                                                 │
│ SYSTEM                    │ Linux                                                                                                                                                    │
│ VERSION_GITHASH           │ 7a4a0b0edef0ad6e0aa662cd3b90c3f4acf796e7                                                                                                                 │
│ VERSION_REVISION          │ 54456                                                                                                                                                    │
│ VERSION_DATE              │                                                                                                                                                          │
│ BUILD_TYPE                │ Release                                                                                                                                                  │
│ SYSTEM_PROCESSOR          │ x86_64                                                                                                                                                   │
│ LIBRARY_ARCHITECTURE      │                                                                                                                                                          │
│ CMAKE_VERSION             │ 3.18.2
```

**Comment by helifu** [comment]
> it depends of how a restart is done, if it was not graceful restart than it's expected #15742

Emm, I think it doesn't matter if the system restarts gracefully. If we detach and attach a part whose merge level is not zero(20211003_1_5_1), the part name will be renamed with a new max block number(20211003_6_6_1) and the coverage information between parts will be lost.

**Comment by den-crane** [comment]
It's kinda expected for **non-replicated** tables. Inactive parts are orphaned after partition drop or detach.
Probably inactive parts should be removed during  partition drop or detach / table truncate.

**Comment by helifu** [comment]
All right. If it's expected, let's close this issue. Thanks denny :)
