### ISSUE TITLE
Add `table` alias to `system.tables` and `database` alias to `system.databases`

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#29677]
This is purely for usability.

`system.tables` has table name in `name` column, but
`system.columns` has table name in `table` column.

This is consistent and logical. But better to also have an alias for convenience.

**Comment by l1t1** [comment]
will it  be confused?  since numbers is different from system. numbers.

**Comment by alexey-milovidov** [comment]
I want to do `SELECT table FROM system.tables`. 
I want `table ALIAS name`.

**Comment by l1t1** [comment]
thank you for your answer. I was misunderstood
