### ISSUE TITLE
Allow to setup retries in `URL` storage.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#29696]
**Use case**

This query should successfully finish ten million HTTP requests in around a day:

```
SELECT * FROM url('https://hacker-news.firebaseio.com/v0/item/{1..10000000}.json', JSONEachRow,
$$
id UInt32,
deleted UInt8,
type Enum('story' = 1, 'comment' = 2, 'poll' = 3, 'pollopt' = 4, 'job' = 5),
by LowCardinality(String),
time DateTime,
text String,
dead UInt8,
parent UInt32,
poll UInt32,
kids Array(UInt32),
url String,
score Int32,
title String,
parts Array(UInt32),
descendants Int32
$$)
```

**Describe the solution you'd like**

If an error happened before any data has been consumed, we can retry a request.
Let's introduce a set of settings: `storage_url_max_retries`, `storage_url_retry_initial_backoff_ms`, `storage_url_retry_max_backoff_ms`. It will do up to max retries, starting from initial backoff ms, increasing 2 times on every retry but saturating at max backoff ms.

**Comment by kssenii** [comment]
Are retries expected to start from 0 (increasing up to `k`) at each `nextImpl()` or we should have only `k` retries for the whole query? @alexey-milovidov

**Comment by alexey-milovidov** [comment]
We can do up to `k` retries for every read (nextImpl).
Motivation: make reading long files as reliable as reading small files - with the same value of `k`.
