### ISSUE TITLE
Parallel downloading for `URL` engine with ranges.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#29694]
**Use case**

Speedup download of single file using many connections.

**Describe the solution you'd like**

The settings can control the chunk size and the number of threads.
The chunks will be selected for download by multiple threads in sequential order.
Whenever a chunk is completed *and has been consumed by the caller*, the thread can select the next chunk.
The result will be present as a single `ReadBuffer` for sequential reading.
The memory usage will be limited by chunk_size * num_threads.

**Comment by nikitamikhaylov** [comment]
The implementation of this feature looks pretty the same as #19649

**Comment by antonio2368** [comment]
Closed with #35150
