### ISSUE TITLE
Function transform with decimal type not working or produce incorrect result

### ISSUE THREAD

**Issue by Grian** [ClickHouse/ClickHouse#29730]
Current stable release and some recent release
ClickHouse client version 21.9.4.35
Connected to ClickHouse server version 21.9.4 revision 54449
Connected to ClickHouse server version 21.5.9 revision 54448

SQL:
```
SELECT  transform(1, [1], [toDecimal32(1, 2)]),    toDecimal32(1, 2)
```
Produces:
```
100 │                 1
```

Expected 1 == 1

```
select transform(1, [1], [toDecimal32(42, 2)]), toDecimal32(42, 2);
```
Produces:
```
 104 │                 42
```

Expected 42 == 42

Looks as garbage ...

Second case of transform function
```
SELECT transform(1, [1], [toDecimal32(42, 2)], 0)

-- OR --

SELECT transform(1, [1], [toDecimal32(42, 2)], toDecimal32(0, 2))
```
Produce error message
```
Received exception from server (version 21.9.4):
Code: 44. DB::Exception: Received from localhost:9000. DB::Exception: Illegal column UInt8 of elements of array of second argument of function transform: While processing transform(1, [1], [toDecimal32(42, 2)], 0). (ILLEGAL_COLUMN)
```

**Comment by loneylee** [comment]
I'm working to solve this problem

**Comment by loneylee** [comment]
Official website introduction:
https://clickhouse.com/docs/en/sql-reference/functions/other-functions/#transformx-array-from-array-to
transform(T, Array(T), Array(T)) -> T
but 
transform(1, [1], [toDecimal32(42, 2)] is same like transform(UInt8, UInt8, Decimal32) -> UInt8.

transform(T, Array(T), Array(U), U) -> U
but
SELECT transform(1, [1], [toDecimal32(42, 2)], 0) => transform(UInt8, UInt8, Decimal32, UInt8) -> UInt8

Maybe it should produce error message instead gaven a wrong answer

so, could u tell me how to fix it

@alexey-milovidov
