### ISSUE TITLE
Empty Avro data in Kafka after insert

### ISSUE THREAD

**Issue by chybz** [ClickHouse/ClickHouse#29739]
**Describe the unexpected behaviour**
Inserting data into Kafka from a ClickHouse table results in empty Avro record and empty Kafka messages.

**How to reproduce**
* Which ClickHouse server version to use
21.8.5.7
* `CREATE TABLE` statements for all tables involved
```sql
CREATE TABLE out(a UInt64, b String)
ENGINE = Kafka()
SETTINGS
    kafka_broker_list='127.0.0.1:9092',
    kafka_format='Avro',
    kafka_topic_list='a_topic',
    kafka_group_name='a_group'
;
```
```sql
CREATE TABLE records(a UInt64, b String)
ENGINE=Memory;
```
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
```sql
INSERT INTO records VALUES(1, 'one');
INSERT INTO records VALUES(2, 'two');
INSERT INTO records VALUES(3, 'three');
```
* Queries to run that lead to unexpected result
```sql
INSERT INTO out SELECT * FROM records;
```
**Expected behavior**
I expect to see in Kafka:
- A Kafka message containing an Avro "file" with 3 lines
or
- 3 Kafka messages containing an Avro "file" with 1 lines

**Additional context**
What I see is 3 Kafka records:
- First one is an Avro "file" with schema only (no rows)
- Second and third are empty Kafka messages

I must be missing something but can't see what.
Thanks for any help !

**Comment by Avogar** [comment]
Looks like solved in https://github.com/ClickHouse/ClickHouse/pull/30351
