### ISSUE TITLE
Add docs for supported signals 

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#29769]
For example SIGHUP is used to rotate logs. And some signals are used internally for query profiler.
We need to add it to logs.
https://github.com/ClickHouse/ClickHouse/blob/6abb3d4c6d89d9ae6b8dc090596b3080aca9863b/base/daemon/BaseDaemon.cpp#L804-L817

**Comment by alexey-milovidov** [comment]
Outdated.
