### ISSUE TITLE
'alter table delete where' works not for all partitions

### ISSUE THREAD

**Issue by alexsubota** [ClickHouse/ClickHouse#29761]
v.21.7.7.47

So, i have table with ts column partitioned by toYYYYMM(toDateTime(ts / 1000))
i want to delete some data by condition, and use 'alter table ... delete where ...', and some data deleted, but data from some partitions not deleted.
Try to do this multiple time, same result. Try to do 'alter table ... delete in partition ... where ...' got same result.
Trying to reproduce this on test data, but cant

**Comment by nikitamikhaylov** [comment]
Try to look to `system.merges` or `system.mutations` for additional info. Also try setting `mutations_sync = 2`

**Comment by alexsubota** [comment]
> Try to look to `system.merges` or `system.mutations` for additional info. Also try setting `mutations_sync = 2`

system.mutations has is_done = 1 for all mutations of this table
try setting mutations_sync = 2, but it doesnt help
checked system.merges after start of alter table, and looks like that partition_id was skipped(and data from partition was not deleted), same with mutations, after start of mutation, column 'parts_to_do_names' have not all partition_ids

**Comment by den-crane** [comment]
>column 'parts_to_do_names' have not all partition_ids

It can be because mutation version in partition_id is bigger than the current mutation version. 
It will 10000 time easier to debug this if you reveal partition_ids, system.mutations, etc.

**Comment by alexsubota** [comment]
> > column 'parts_to_do_names' have not all partition_ids
> 
> It can be because mutation version in partition_id is bigger than the current mutation version, for example. It will be10000 timeseasier to debug this if you reveal partition_ids, system.mutations, etc.

Table PARTITION BY toYYYYMM(toDateTime(ts / 1000))
example of system.parts:
![image](https://user-images.githubusercontent.com/4305175/136058904-64817b0e-2744-41ec-b6a8-ecfb04616ac1.png)
which info from mutations you needed?

**Comment by den-crane** [comment]
The last number in the part name. _14 _5201 _4800
What is the number has the not mutated part and what is the number have mutated parts.

**Comment by alexsubota** [comment]
> The last number in the part name. _14 _5201 _4800 What is the number has the not mutated part and what is the number have mutated parts.

partition 201908 and 201909, these partitions which was not affected by mutations (alter table .. delete .. where)

**Comment by den-crane** [comment]
>partition 201908 and 201909

You mean _5201 were not mutated, but 202001...._11186 was?

**Comment by alexsubota** [comment]
so, i try to make delete from all partitions in one statement, and still have the same
![image](https://user-images.githubusercontent.com/4305175/136793680-e519a172-9401-44d6-9cac-7d768acc183b.png)

Additionally, i check system.mutations after start of mutation, and column parts_to_do_names do not have parts 201908_..., 201909_... (maybe this information can help)

**Comment by alexey-milovidov** [comment]
Cannot reproduce.
