### ISSUE TITLE
DDL/alter queries should respond with valid JSON 

### ISSUE THREAD

**Issue by genzgd** [ClickHouse/ClickHouse#29789]
We have a simple UI for various ClickHouse maintenance tasks that allows submitting simple queries and expects a standard JSON query response (meta, data, rows, statistics).  We would like to extend this and other tools to allow submitting basic DDL and alter table queries via HTTP.  Adding "FORMAT JSON" to such queries works, but the response is still in plain text, unless the query is "ON CLUSTER" and no errors are returned.

It would useful if such queries with "FORMAT JSON" always returned valid JSON.  A single JSON property of "result", or possibly array of "errors" or "messages" could be included in the response, as well the array results from the ON CLUSTER operation.

**Comment by den-crane** [comment]
probably you are looking for setting `wait_end_of_query` 
https://github.com/ClickHouse/ClickHouse/issues/10811

**Comment by Algunenano** [comment]
You can now use `http_write_exception_in_output_format` and set the format
