### ISSUE TITLE
Trait inconsistent with function in reinterpretAs.cpp

### ISSUE THREAD

**Issue by myrrc** [ClickHouse/ClickHouse#29785]
Trait: Date or DateTime allowed:

https://github.com/ClickHouse/ClickHouse/blob/199ac31b48b2d0550b7483d23bc646e094a9793e/src/Functions/reinterpretAs.cpp#L254
https://github.com/ClickHouse/ClickHouse/blob/199ac31b48b2d0550b7483d23bc646e094a9793e/src/Functions/reinterpretAs.cpp#L256
https://github.com/ClickHouse/ClickHouse/blob/199ac31b48b2d0550b7483d23bc646e094a9793e/src/Functions/reinterpretAs.cpp#L257

Function: Date, DateTime or DateTime64 allowed

https://github.com/ClickHouse/ClickHouse/blob/199ac31b48b2d0550b7483d23bc646e094a9793e/src/Functions/reinterpretAs.cpp#L260
https://github.com/ClickHouse/ClickHouse/blob/199ac31b48b2d0550b7483d23bc646e094a9793e/src/Functions/reinterpretAs.cpp#L264
https://github.com/ClickHouse/ClickHouse/blob/199ac31b48b2d0550b7483d23bc646e094a9793e/src/Functions/reinterpretAs.cpp#L265
https://github.com/ClickHouse/ClickHouse/blob/199ac31b48b2d0550b7483d23bc646e094a9793e/src/Functions/reinterpretAs.cpp#L266

As I see, the correct behaviour would be to add DateTime64 to trait but I'm not sure.

**Comment by kitaisreal** [comment]
IsDataTypeDecimalOrNumber include `DataTypeDateTime64`.
```
constexpr bool IsDataTypeDecimalOrNumber = IsDataTypeDecimal<DataType> || IsDataTypeNumber<DataType>
template <> inline constexpr bool IsDataTypeDecimal<DataTypeDateTime64> = true;
```
