### ISSUE TITLE
Drop table & Drop database keeps an old UUID reference in zookeeper

### ISSUE THREAD

**Issue by unkn0wnnnnnn** [ClickHouse/ClickHouse#29808]
**Describe the unexpected behaviour**
CREATE TABLE IF NOT EXISTS db.tablename ON CLUSTER
ENGINE = ReplicatedMergeTree

CREATE TABLE IF NOT EXISTS db.tablename_2 ON CLUSTER
ENGINE = Distributed(clustername, dbname, tablename, shardingkey)

DROP TABLE db.tablename ON CLUSTER clustername SYNC
DROP TABLE db.tablename_2 ON CLUSTER clustername SYNC
DROP DATABASE db ON CLUSTER clustername SYNC

The table drops, but zookeeper keeps a stale reference to the old tables UUID,

SELECT * FROM system.zookeeper where path = '/clickhouse/tables/'

always shows the previous UUID that the macro used to create the zookeeper reference to the previous table

This was an issue when I was manually specifying parameters on the replicated tables constructor, saying that the replica already exists even though it did not because I deleted the tables and database

**How to reproduce**
CREATE TABLE IF NOT EXISTS db.tablename ON CLUSTER
ENGINE = ReplicatedMergeTree

CREATE TABLE IF NOT EXISTS db.tablename_2 ON CLUSTER
ENGINE = Distributed(clustername, dbname, tablename, shardingkey)

DROP TABLE db.tablename ON CLUSTER clustername SYNC
DROP TABLE db.tablename_2 ON CLUSTER clustername SYNC
DROP DATABASE db ON CLUSTER clustername SYNC

**Expected behavior**
DROP TABLE db.tablename ON CLUSTER clustername SYNC
DROP TABLE db.tablename_2 ON CLUSTER clustername SYNC
DROP DATABASE db ON CLUSTER clustername SYNC

should remove the reference in the zookeeper but it does not.

SELECT * FROM system.zookeeper where path = '/clickhouse/tables/'
always shows the previous tables UUID

I've attempted to manually remove the reference but the database throws an error saying zookeeper does not support mutations

**Error message and/or stacktrace**
N/A

**Additional context**
I'm not sure if this effects performance or operation, but it does keep a stale reference in system.zookeeper to non existent databases

**Comment by den-crane** [comment]
ClickHouse  version?

https://kb.altinity.com/engines/altinity-kb-atomic-database-engine/

**Comment by unkn0wnnnnnn** [comment]
It happened on many versions, current version
ClickHouse server version 21.9.4.35 (official build).

**Comment by unkn0wnnnnnn** [comment]
Weird, what zookeeper are you using?

**Comment by den-crane** [comment]
I see, I missed to paste a query to system.zookeeper
I used system.replicas to get the zookeeper_path to query system.zookeeper

```
CREATE TABLE db.tablename on cluster segmented  (a Int64)  ENGINE = ReplicatedMergeTree() order by a;
OK

select zookeeper_path from system.replicas where table = 'tablename';
┌─zookeeper_path────────────────────────────────────────────┐
│ /clickhouse/tables/ea5e3850-c791-4580-aa5e-3850c791f580/1 │
└───────────────────────────────────────────────────────────┘

select * from system.zookeeper where path  = '/clickhouse/tables/ea5e3850-c791-4580-aa5e-3850c791f580/1';
....
16 rows in set. Elapsed: 0.002 sec.

drop table db.tablename on cluster segmented sync;
OK

select * from system.zookeeper where path  = '/clickhouse/tables/ea5e3850-c791-4580-aa5e-3850c791f580/1';

0 rows in set. Elapsed: 0.003 sec.

Received exception from server (version 21.9.4):
Code: 999. DB::Exception: Received from localhost:9000. DB::Exception: No node, path: /clickhouse/tables/ea5e3850-c791-4580-aa5e-3850c791f580/1. (KEEPER_EXCEPTION)

```

**Comment by unkn0wnnnnnn** [comment]
do:

CREATE DATABASE db on cluster segmented 
CREATE TABLE db.tablename on cluster segmented  (a Int64)  ENGINE = ReplicatedMergeTree() order by a;
CREATE TABLE db.tablename_ddl on cluster segmented  AS db.tablename ENGINE = Distributed('segmented', 'db', 'tablename', rand()) order by a;
DROP TABLE db.tablename on cluster segmented SYNC
DROP TABLE db.tablename_ddl on cluster segmented SYNC
DROP DATABASE db on cluster segmented SYNC
SELECT * FROM system.zookeeper WHERE path  = '/clickhouse/tables/'

you should see the old UUIDs of the dropped tables.
Atleast thats what is happening for me

**Comment by den-crane** [comment]
I see UUID, OK. It's expected.

But I don't really understand what is you problem.
Maybe you don't know how to define  UUID in Distributed DDL?

```
CREATE TABLE db.tablename  UUID '3bd68e3c-2693-4352-ad66-a66eba9e345e'  on cluster segmented (a Int64)  ENGINE = ReplicatedMergeTree() order by a;
OK

drop table db.tablename on cluster segmented sync;
OK

CREATE TABLE db.tablename  UUID '3bd68e3c-2693-4352-ad66-a66eba9e345e'  on cluster segmented (a Int64)  ENGINE = ReplicatedMergeTree() order by a;
OK
```

**Comment by unkn0wnnnnnn** [comment]
No its not that, I am not and do not need to manually specify UUID in the CREATE TABLE query

So, if I were to manually specify parameters to ReplicatedMergeTree like so:
#1
```
CREATE TABLE if not exists db.tablename on cluster segmented  (a Int64)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/{database}/tablename', '{replica}')

CREATE TABLE if not exists db.tablename_ddl on cluster segmented  (a Int64)
ENGINE = Distributed('segmented', 'db', 'tablename', rand())
```

Then drop the tables:
#2
```
DROP TABLE db.tablename on cluster segmented
DROP TABLE db.tablename_ddl on cluster segmented
```

Then recreate the tables again:
#3
```
CREATE TABLE if not exists db.tablename on cluster segmented  (a Int64)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/{database}/tablename', '{replica}')

CREATE TABLE if not exists db.tablename_ddl on cluster segmented  (a Int64)
ENGINE = Distributed('segmented', 'db', 'tablename', rand())
```

Even though the tables were dropped, 
system.zookeeper still has the reference to '/clickhouse/tables/{shard}/{database}/tablename'
and because of this, #3 will throw an error saying DB:Exception '/clickhouse/tables/{shard}/{database}/tablename' already exists,
even though it does not.

I've searched for fixing this and came across a lot of other posts describing the same issue
