### ISSUE TITLE
How to migrate data  from schema version 1.0 to 2.0 ? 

### ISSUE THREAD

**Issue by DipalPrajapati** [ClickHouse/ClickHouse#29824]
- I have a scenario where I need to migrate older application version of db to new application version db. 
- Where I do have changes in schema(mostly fields length) plus there is difference of shard and replica macro name. 
- Before we were using per cluster macro (replicaC1 and replicaC2) but now we have containerized clickhouse and came to know that it automatically map the macro name from cluster given. 
- Can you suggest how to restore my 1.x backup to 2.X app db ?
What should my way to migrate data from 1.x to 2.x? 

Shall I take backup of each tables
 using 
`  clickhouse-client -u clickhouse --password <pass> -h <host>  --query "SELECT * FROM $dbname.$table_name FORMAT CSV " > $table_name.csv
  `
and restore using 
` clickhouse-client  -u <> --password <> --port 9440 -h <>  "$dbname" --query="insert into $table_name format CSV" < $table_name.csv
`

-  Is this advisable? 
- Shall I take backup of Distributed Table and not local tables plus no MV? 
- What all things I should keep in mind while taking this approach?
Can you please guide me over here , what should be my way to migrate data from one schema version to another ?

**Comment by den-crane** [comment]
>Where I do have changes in schema(mostly fields length) 

you can use alter and change  fields length.
I would freeze tables move data parts using rsync from shadow folder of the old system to the new.

>Shall I take backup of each tables

Yes, you can. You can pipe clickhouse-clients no need to create file

clickhouse-client -u "SELECT * ... |  clickhouse-client  ... "insert into"

>Shall I take backup of Distributed Table and not local tables plus no MV?

Yes Distributed tables are enough.

You may use clickhouse-copier.

**Comment by DipalPrajapati** [comment]
@den-crane Is it safe to go by this approach only in production env? 
clickhouse-client -u "SELECT * ... | clickhouse-client ... "insert into"

**Comment by DipalPrajapati** [comment]
@den-crane ?

**Comment by den-crane** [comment]
I don't see why it's not safe.
