### ISSUE TITLE
SQL query parsing functions

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#29875]
**Use case**

Query log analysis (for clickhouse SQL dialect first)

Analysis of query logs for other SQL databases later?

**Describe the solution you'd like**

parseSQL function

```
parseSQL('SELECT 1', 'where')
parseSQL('SELECT 1', 'group by')
parseSQL('SELECT 1', 'columns')
parseSQL('SELECT 1', 'tables')
```

Or it will return some complex structure (JSON?, map?)

**Comment by Bulat-Ziganshin** [comment]
It's somewhat related to #29922, but may be easier to implement. CH should already have C++ AST type representing the parsed SQL statement

**Comment by UnamedRus** [comment]
Related https://github.com/ClickHouse/ClickHouse/pull/48757

**Comment by UnamedRus** [comment]
Related https://github.com/ClickHouse/ClickHouse/issues/88799
