### ISSUE TITLE
Big mutation count stops updates?

### ISSUE THREAD

**Issue by Grian** [ClickHouse/ClickHouse#29884]
I have seen if table mutation count is greater than above 100 - 1000 (aprox.) they suddenly stop progressing.

And this is very inconvenient.

What is happens?

Is there way to change this behavior?

```

**Comment by genzgd** [comment]
ClickHouse is designed for immutable data.  Its high performance is dependent on sparse indexes (in the default case there is only a single index value for every 8192 rows), and keeping all of the columnar data in the table sorted by those indexes.  Accordingly mutations are very expensive, and in many cases require resorting and rewriting one or more columns for all the data.  If there are a 100+ mutations running at once, this will definitely degrade ClickHouse performance.

In general you should only run mutations in exceptional circumstances, they should not be part of a regular business process.  Also mutations lock the affected table while processing, so only one mutation should be executed at a time in any case.

Lightweight mutations are on the roadmap for 2022, so this situation could change in the future.
