### ISSUE TITLE
clickhouse.com is blocked by Adblockers

### ISSUE THREAD

**Issue by anergictcell** [ClickHouse/ClickHouse#29915]
**Describe the issue**
The clickhouse.com URL is blocked via the `gravity` list for DNS-based adblocking. This makes it impossible to visit the `clickhouse.com` domain when one is using e.g. PiHole for ad blockling

**Additional context**
The URL was added to the blacklist in 2014, so this is most likely an artifact that only needs cleaning up. I already opened an issue with the adblocker list here: https://github.com/StevenBlack/hosts/issues/1781 but wanted to make you aware of the issue nevertheless.

**Comment by tylerhannan** [comment]
I've reached out to the upstream twice...it appears the list was last updated in March 2021  so I don't have much confidence in a reply.

**Comment by tylerhannan** [comment]
https://github.com/StevenBlack/hosts/commit/8a294be9223ad8e72592834d90d424135c5d3d6d

**Comment by Algunenano** [comment]
Should be mostly fixed now. Nothing to do here

**Comment by mIcHyAmRaNe** [comment]
it s also blocked in : [Ealenn AdGuard-Home-List](https://github.com/Ealenn/AdGuard-Home-List)
