### ISSUE TITLE
support Nullable String type in arrayStringConcat

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#29967]
For example Null can be represented as empty string

```sql
select arrayStringConcat(['x',Null], ';');

┌─arrayStringConcat(['x', Null], ';')─┐
│ x;                                  │
└─────────────────────────────────────┘
```

But mostly it for avoiding a cast in case of Nullable Strings
```
SELECT arrayStringConcat(col0, ';')
FROM
(
    SELECT [toNullable('x')] AS col0
) AS t
```

Also I think arrayStringConcat can support any types not only Strings, it allows to avoid explicit casts.

```
SELECT arrayStringConcat(col0, ';')
FROM
(
    SELECT [1, 2, 3] AS col0
) AS t
```

**Comment by nickitat** [comment]
is this task available?

**Comment by kitaisreal** [comment]
Fixed in https://github.com/ClickHouse/ClickHouse/pull/30840.
