### ISSUE TITLE
Quantile fusion does not work

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#29965]
```
SET optimize_syntax_fuse_functions = 1;
SELECT quantile(1 AS a), quantile(a AS b), quantile(b AS c);
```

**Comment by alexey-milovidov** [comment]
@vdimir 

It's strange to have two settings:
`optimize_fuse_sum_count_avg` - specifically for sum/count/avg.
`optimize_syntax_fuse_functions` - another setting that does not say anything about quantiles.

**Comment by vdimir** [comment]
> It's strange to have two settings:
> `optimize_fuse_sum_count_avg` - specifically for sum/count/avg.

It's old setting.

> `optimize_syntax_fuse_functions` - another setting that does not say anything about quantiles.

I've decided not to create separate setting for each function, but introduce new one for all. So `optimize_fuse_sum_count_avg` left, but marked as obsolete, `optimize_syntax_fuse_functions` enables fusing on syntax.

**Comment by alexey-milovidov** [comment]
But we want to enable quantile fusion by default and not enable sum/count/avg fusion by default.
