### ISSUE TITLE
Consider GROUP_CONCAT / STRING_AGG function 

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#29978]
It's about the same as 

```
arrayStringConcat( groupArray(column), ',')
```

Pros: less typing, easier migration from other dbs.

**Comment by MaceWindu** [comment]
Note that `arrayStringConcat( groupArray(column), ',')` have different behavior for empty set.
`GROUP_CONCAT / STRING_AGG` will return NULL, but `arrayStringConcat( groupArray(column), ',')` will return empty string, because `groupArray(column)` returns `[]` instead of `NULL`
