### ISSUE TITLE
[Question]: Use the lowCardinality feature to promote WHERE condition to PREWHERE ?

### ISSUE THREAD

**Issue by TH-HA** [ClickHouse/ClickHouse#2998]
Hello 
Is there any plan to use the lowCardinality columns ( where it should be easy to have an idea of the cardinality of those columns ) to promote some condition ( which can be qualified as potentially high filtering condition based on the cardinality )  from the WHERE clause to PREWHERE ?
I don't know if it make sense , but if it does it can be a nice improvement and simplification in the sql statement on the top of clickhouse. 

Regards

**Comment by KochetovNicolai** [comment]
Hello.

Sorry for late answer. I think it's a grate idea to promote low cardinality columns (and, probably, any expression with LowCardinality type at result) to PREWHERE. I haven't planned this optimization yet, but I'll add it at least for case `LowCardinality = const` if it's easy enough.

**Comment by alexey-milovidov** [comment]
@KochetovNicolai Why it should not work automatically due to small compressed size of column?

**Comment by KochetovNicolai** [comment]
I should check it. Probably, compression size won't be less then for numeric column.

**Comment by blinkov** [comment]
@TH-HA, do you have any further questions?

**Comment by alexey-milovidov** [comment]
> Probably, compression size won't be less than for numeric column.

Compressed size for LowCardinality column will be somewhat less than for ordinary column and this column can be selected for PREWHERE optimization automatically.

We should not implement any additional heuristics specifically for LowCardinality columns.
