### ISSUE TITLE
"There are no UInt128 literals in SQL" error when selecting UUID using API/HTTP 

### ISSUE THREAD

**Issue by ixodis** [ClickHouse/ClickHouse#29983]
Hello!

I have some problems with UUIDs in Clickhouse 21.3.9.83

There is table "alerts" with fields:

>     event_uuid              UUID,
>     rule_uuid               UUID,

This query returns rule_uuid's value as expected:

> SELECT rule_uuid FROM alerts WHERE event_uuid='d476380d-6e5c-45bf-bdfa-6de0049c4aea'

But if I do the same query with param using API:

> https://*ip*/?database=nba&param_event_id=d476380d-6e5c-45bf-bdfa-6de0049c4aea&query=SELECT%20rule_uuid%20from%20alerts%20where%20event_uuid={event_id:UUID}

I have the following error:

> Code: 48, e.displayText() = DB::Exception: There are no UInt128 literals in SQL: While processing SELECT rule_uuid FROM alerts WHERE event_uuid = CAST('d476380d-6e5c-45bf-bdfa-6de0049c4aea', 'UUID') (version 21.3.9.83 (official build))

I found some workaround - set param as String and bring it to UUID by toUUID() funtion:
> https://*ip*/?database=nba&param_event_id=d476380d-6e5c-45bf-bdfa-6de0049c4aea&query=with%20{event_id:String}%20as%20id%20SELECT%20rule_uuid%20from%20alerts%20where%20event_uuid=toUUID(id)

**Comment by vdimir** [comment]
Works correctly since 21.6. We'd recommend to upgrade onto latest stable version

```bash
$ curl "http://localhost:8123/?param_event_id=d476380d-6e5c-45bf-bdfa-6de0049c4aea&query=SELECT%20x%20from%20t%20where%20x=\{event_id:UUID\}"
Code: 48, e.displayText() = DB::Exception: There are no UInt128 literals in SQL: While processing x = CAST('d476380d-6e5c-45bf-bdfa-6de0049c4aea', 'UUID') (version 21.3.17.2 (official build))
$ curl "http://localhost:8123/?param_event_id=d476380d-6e5c-45bf-bdfa-6de0049c4aea&query=SELECT%20x%20from%20t%20where%20x=\{event_id:UUID\}"
Code: 48, e.displayText() = DB::Exception: There are no UInt128 literals in SQL: While processing x = CAST('d476380d-6e5c-45bf-bdfa-6de0049c4aea', 'UUID') (version 21.4.7.3 (official build))
$ curl "http://localhost:8123/?param_event_id=d476380d-6e5c-45bf-bdfa-6de0049c4aea&query=SELECT%20x%20from%20t%20where%20x=\{event_id:UUID\}"
Code: 48, e.displayText() = DB::Exception: There are no UInt128 literals in SQL: While processing x = CAST('d476380d-6e5c-45bf-bdfa-6de0049c4aea', 'UUID') (version 21.4.7.3 (official build))
$ curl "http://localhost:8123/?param_event_id=d476380d-6e5c-45bf-bdfa-6de0049c4aea&query=SELECT%20x%20from%20t%20where%20x=\{event_id:UUID\}"
Code: 48, e.displayText() = DB::Exception: There are no UInt128 literals in SQL: While processing x = CAST('d476380d-6e5c-45bf-bdfa-6de0049c4aea', 'UUID') (version 21.5.9.4 (official build))
$ curl "http://localhost:8123/?param_event_id=d476380d-6e5c-45bf-bdfa-6de0049c4aea&query=SELECT%20x%20from%20t%20where%20x=\{event_id:UUID\}"
d476380d-6e5c-45bf-bdfa-6de0049c4aea
$ curl "http://localhost:8123/?query=SELECT%20version()"                                 
21.6.9.7
```
