### ISSUE TITLE
Восстановление данных

### ISSUE THREAD

**Issue by root1336** [ClickHouse/ClickHouse#29996]
Good afternoon, colleagues. Please help, the question is as follows.

There are two folders data and metadata, they are taken from the old clickhouse, which was used two years ago and now we need to restore these databases. I copied the data and metadata folders to /var/lib/clickhouse/, it didn't help.

**Comment by root1336** [comment]
> What is the table and database engines? Do you seed databases/tables in `system.databases` and `system.tables`?

Honestly, I don't know anything about `system.databases` and` system.tables`, because I didn't work with this software at all before. Colleagues asked to restore the bases. I started looking at the information, the only thing I found in the official documentation on the recovery account https://clickhouse.com/docs/ru/engines/table-engines/mergetree-family/replication/#vosstanovlenie-v-sluchae-poteri-vsekh-dannykh

It says here that the data needs to be copied to `/var/lib/clickhouse/data/db_name/table_name/` and `/var/lib/clickhouse/metadata/`

But again, the article is generally about data replication, perhaps that's not my case.

**Comment by root1336** [comment]
> You need to do:
> 
> 1. stop clickhouse
> 2. copy folders to /var/lib/clickhouse/
> 3. start clickhouse
> 4. check for errors and share logs from (all files) /var/log/clickhouse-server/

Understood. And how is it better to copy folders in the end? In the existing clickhouse, delete the data and metadata folders and get your own data instead?

**Comment by den-crane** [comment]
I forgot one more step `chown -R clickhouse.clickhouse /var/lib/clickhouse/`

>And how is it better to copy folders in the end?
>In the existing clickhouse, delete the data and metadata folders and get your own data instead

If you  don't have overlapping tables you can leave existing tables. 
Clickhouse does not have system catalogs with tables / parts. During the start Clickhouse iterates all .sql files in metadata folder and execute SQL commands.

**Comment by root1336** [comment]
> Sorry, I meant `create table for mat.view` `cat metadata/ethereum_go/from_curr.sql`

Sorry, but I don't understand the meaning of ((

So. I understood what error you have I will introduce.

`DB :: Exception: Aggregate function count requires zero or one argument: Cannot attach table `default`.`.inner.ethereum_go.from_curr` from metadata file / var / lib / clickhouse / metadata / default /% 2Einner% 2Eethereum_go% 2Efrom_curr. sql`

` Cannot attach table `default`` from file. And here I do not quite understand the meaning `create table for mat.view`
