### ISSUE TITLE
Mark end of query when running query with http progress headers

### ISSUE THREAD

**Issue by ecyshor** [ClickHouse/ClickHouse#2999]
Currently when running queries over the http interface and requesting the http progress headers there is no easy way to tell that the query finished executing 100% or something went wrong.
For example when the query fails half way the response would look something like this:

```
`
X-ClickHouse-Progress: {"read_rows":"159466057","read_bytes":"23600976436","total_rows":"240828416"}
X-ClickHouse-Progress: {"read_rows":"161055305","read_bytes":"23836185140","total_rows":"240828416"}
X-ClickHouse-Progress: {"read_rows":"162456137","read_bytes":"24043508276","total_rows":"240828416"}
X-ClickHouse-Progress: {"read_rows":"164045385","read_bytes":"24278716980","total_rows":"240828416"}
X-ClickHouse-Progress: {"read_rows":"165438025","read_bytes":"24484827700","total_rows":"240828416"}

Code: 241, e.displayText() = DB::Exception: Memory limit (for query) exceeded: ...`

```
While a successful result would look something like this:
```
`
X-ClickHouse-Progress: {"read_rows":"1340919","read_bytes":"437228836","total_rows":"1417216"}
X-ClickHouse-Progress: {"read_rows":"1365495","read_bytes":"445829218","total_rows":"1417216"}
 
{
	"meta":
	[
		{
			"name": "sleep(3)",
			"type": "UInt8"
		},
		{
....
`
```

The only way to tell if it succeeded would be to see if the body content contains `e.displayText() = DB::Exception` or some other string, but this is not reliable in the long run.

It would be really helpful to add a final header which denotes success/failure or even just ensuring that the `X-ClickHouse-Progress` is sent for the last part of the query., so that the `read_rows` is equal with the `total_rows`.

**Comment by alexey-milovidov** [comment]
The difficulty is that the server can start to send result before query is finished.

**Comment by champtar** [comment]
Maybe you could use http trailers?

**Comment by filimonov** [comment]
Related: https://github.com/yandex/ClickHouse/issues/208

**Comment by Algunenano** [comment]
If you are using `wait_end_of_query` you now get `X-ClickHouse-Exception-Code`. In if don't use it you can try using `X-ClickHouse-Exception-Code` to get the exception in the same format as the output (if possible).

For other problems related to HTTP1.1 not being able to report errors after the start of sending the body there are other open issues.
