### ISSUE TITLE
The Buffer engine violates time thresholds in a strange way

### ISSUE THREAD

**Issue by loyd** [ClickHouse/ClickHouse#29994]
We are inserting into the `Buffer` table that should flush rows not later than after 15s according to the `max_time` setting:
```sql
CREATE TABLE indicator_log_buffer (
    `name` String,
    `time` DateTime64(9),
    `trace_id` UInt64,
    `value` Float64,
    `publisher` LowCardinality(String)
)
ENGINE = Buffer('default', 'indicator_log', 16, 5, 15, 10000, 1000000, 10000000, 100000000)
```

The schema of `indicator_log`:
```sql
CREATE TABLE indicator_log (
    `name` String,
    `platform_time` DateTime64(9),
    `trace_id` UInt64,
    `value` Float64,
    `publisher` LowCardinality(String),
    INDEX trace_id_index trace_id TYPE minmax GRANULARITY 3
)
ENGINE = ReplacingMergeTree
PARTITION BY toYYYYMM(platform_time)
ORDER BY name, platform_time
```

However, for some unknown reasons, the flush time is constantly violated.

The following query shows the difference between the buffer table and the underlying one: 
```sql
WITH
    'xxxxx' AS indicator,
    now64(9) - INTERVAL 90 MINUTE AS t0,
    now64(9) - INTERVAL 15 SECOND AS t1
SELECT ts, buf.min, raw.min
FROM (
    SELECT toStartOfInterval(platform_time, INTERVAL 10 SECOND) ts, min(value) min
      FROM indicator_log_buffer
     WHERE name = indicator
       AND platform_time BETWEEN t0 AND t1
     GROUP BY ts
) buf
FULL JOIN (
    SELECT toStartOfInterval(platform_time, INTERVAL 10 SECOND) ts, min(value) min
      FROM indicator_log
     WHERE name = indicator
       AND platform_time BETWEEN t0 AND t1
     GROUP BY ts
) raw
USING ts
WHERE buf.min != raw.min
ORDER BY ts;

```

For instance, I run this at `2021-10-11 10:26:30` and see the next results:
```
┌──────────────────ts─┬─────min─┬─raw.min─┐
│ 2021-10-11 10:16:10 │ 3590.97 │ 3591.02 │
│ 2021-10-11 10:16:20 │  3590.1 │ 3591.07 │
│ 2021-10-11 10:22:30 │    3582 │ 3582.32 │
│ 2021-10-11 10:22:40 │ 3582.07 │       0 │
│ 2021-10-11 10:22:50 │ 3581.74 │       0 │
│ 2021-10-11 10:23:00 │ 3583.21 │       0 │
│ 2021-10-11 10:24:10 │ 3579.71 │       0 │
│ 2021-10-11 10:24:30 │ 3581.44 │ 3581.59 │
│ 2021-10-11 10:24:50 │ 3579.97 │ 3579.99 │
│ 2021-10-11 10:25:00 │ 3579.32 │       0 │
│ 2021-10-11 10:25:10 │ 3579.44 │       0 │
│ 2021-10-11 10:25:20 │ 3580.12 │ 3580.21 │
│ 2021-10-11 10:25:40 │ 3581.07 │       0 │
│ 2021-10-11 10:25:50 │ 3581.26 │       0 │
│ 2021-10-11 10:26:00 │ 3581.17 │       0 │
│ 2021-10-11 10:26:10 │ 3580.53 │       0 │
└─────────────────────┴─────────┴─────────┘
```

It seems that some shards are flushed, but some of them are not.

CH version: 21.6.6 revision 54448

**Note that using only 1 internal buffer (instead of 16) solves the problem.**

Maybe related: https://github.com/ClickHouse/ClickHouse/issues/25585

**Comment by den-crane** [comment]
Data is flushed from the buffer and written to the destination table if **all the min conditions** or at least one max* condition **are met**.

try to reduce min_rows, min_bytes

It's possible that your data in 1/16 is less than 10000000 bytes.

**Comment by den-crane** [comment]
> > at least one max* condition are met.
> 
> Yep, so I have max_time = 15s

Sorry, my mistake.
Need to make reproducible example.

**Comment by loyd** [comment]
I detected that our Buffer tables have a big `total_bytes`, ~2**64. Then I found https://github.com/ClickHouse/ClickHouse/pull/24450.
Maybe it's related and doesn't reproduce with newer versions, I'll check after some time
