### ISSUE TITLE
Datetime64 INSERT from FORMAT Parquet seems to truncate milliseconds

### ISSUE THREAD

**Issue by schalekamp** [ClickHouse/ClickHouse#30002]
In my table schema I have the following datetime field:
`    ts_utc             DateTime64(3, 'UTC')`

In a pandas dataframe I have the datetime field as : 
`df = df.astype({'ts_utc': 'datetime64[ns]'})`

Saving the dataframe as parquet:
`df.to_parquet("out.paquet")`

Importing it into Clickhouse
`    clickhouse-client -h <host> --port 9001 --query="INSERT INTO mytable FORMAT Parquet" <out.parquet`

Now when we query the table the field ts_utc only shows 1 second precision, the milliseconds are .000
When we load the parquet file into a pandas Dataframe then the milliseconds are still there.

**Comment by Avogar** [comment]
DateTime64 now supported
