### ISSUE TITLE
"expected quorum" error after replica restore

### ISSUE THREAD

**Issue by protocat** [ClickHouse/ClickHouse#30043]
Hello!
We have Clickhouse instance with 3 shards, each shard have 2 replicas. 
Due to some storage problem one shard lost one of it's replica, possibly, storage problem cause data damage.

From documentation, there are an advise to clean data and start failied replica, so it will be able to replicate all tables from existing replica.

The thing is - replication process throws errors similar to provided below.
There are no active replicas until we try to push them with "system RESTART REPLICAS", after this, replications process starts for a while, but stops again.
Also there are a big queue of inserts (data and metrics) which is not decreasing, and log_max_index and log_pointer have difference about 100K. 
There are no network and i/o problems which can affect this.

Does anyone faces the similar problem?

Log message was taken from "live" replica, failied replica facing same errors.
*****************************
{TIMESTAMPHERE} [ 54 ] {} <Error> graphite.metrics_lr (ReplicatedMergeTreeRestartingThread): void DB::ReplicatedMergeTreeRestar
tingThread::run(): Code: 27, e.displayText() = DB::Exception: Cannot parse input: expected quorum:  before: part_type: Compact\n, Stack tr
ace (when copying this message, always include the lines below):

0. 0x100ac1bc Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int
)  in /usr/bin/clickhouse
1. 0x8e74849 DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int)
in /usr/bin/clickhouse
2. 0x8eaacd5 ?  in /usr/bin/clickhouse
3. 0x8ea8caa DB::assertString(char const*, DB::ReadBuffer&)  in /usr/bin/clickhouse
4. 0xd78dfd8 DB::ReplicatedMergeTreeLogEntryData::readText(DB::ReadBuffer&)  in /usr/bin/clickhouse
5. 0xd78f04b DB::ReplicatedMergeTreeLogEntry::parse(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >
const&, Coordination::Stat const&)  in /usr/bin/clickhouse
6. 0xd7bcf38 DB::ReplicatedMergeTreeQueue::pullLogsToQueue(std::__1::shared_ptr<zkutil::ZooKeeper>, std::__1::function<void (Coordination:
:WatchResponse const&)>)  in /usr/bin/clickhouse
7. 0xd7d73f8 DB::ReplicatedMergeTreeRestartingThread::tryStartup()  in /usr/bin/clickhouse
8. 0xd7d7cf8 DB::ReplicatedMergeTreeRestartingThread::run()  in /usr/bin/clickhouse
9. 0xcd939f1 DB::BackgroundSchedulePoolTaskInfo::execute()  in /usr/bin/clickhouse
10. 0xcd93fca DB::BackgroundSchedulePool::threadFunction()  in /usr/bin/clickhouse
11. 0xcd94100 ?  in /usr/bin/clickhouse
12. 0x8e97347 ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>)  in /usr/bin/clickhouse
13. 0x8e9580f ?  in /usr/bin/clickhouse
14. 0x76db start_thread  in /lib/x86_64-linux-gnu/libpthread-2.27.so
15. 0x12188f __clone  in /lib/x86_64-linux-gnu/libc-2.27.so
 (version 20.1.6.30 (official build))
*****************************

**Comment by protocat** [comment]
@filimonov 
thank you for advice

we'd updated both replicas on broken shard, now errors regarding "expected quorum" are dissappeared, but now we're facing new problem

after update all data in database folder are moved to detached, and now database is clean (not good, but OK we're can handle it)
futhermore both replicas are sets as leaders, and "inserts_in_queue" are not changing within hours

it's seems that the problem is zookeper related, are there any ways to diagnose it?

**Comment by alexey-milovidov** [comment]
Yes, it looks like you have messed something up with ZooKeeper.
Like manual intervention to the data, stored in ZooKeeper or wrong cluster configuration.
