### ISSUE TITLE
GRANT DROP VIEW

### ISSUE THREAD

**Issue by Glomywow** [ClickHouse/ClickHouse#30055]
Hello! 
Do GRANT VIEW permissions work correctly?
when a user tries to delete a VIEW with the following rights
GRANT  SELECT, INSERT, CREATE TABLE, CREATE VIEW, DROP VIEW ON dictionaries.test to fasolwbanke_test;
He gets an error:
DB::Exception: fasolwbanke_test: Not enough privileges. To execute this query it's necessary to have grant DROP TABLE, DROP VIEW ON dictionaries.test. (ACCESS_DENIED)
Is it possible to delete a VIEW without granting rights to DROP TABLE? And is it planned to separate access rights by VIEW and TABLE

**Comment by genzgd** [comment]
I've been unable to reproduce this on recent builds (in particular 22.1.).  What version of ClickHouse did you observe this on?  Can you provide minimal set of steps to reproduce?
