### ISSUE TITLE
Engine Mysql - where condition + Like

### ISSUE THREAD

**Issue by pyhbka** [ClickHouse/ClickHouse#3011]
Clickhouse query:
SELECT some_fields FROM my_table WHERE field = 123 AND field2 = 321 AND title LIKE '%title%'

Received exception from server (version 18.6.0):
Code: 1000. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: mysqlxx::BadQuery: Operand should contain 1 column(s)

Mysql query log:
SELECT some_fields FROM my_table WHERE (field = 123, field2 = 321)

**Comment by VadimPE** [comment]
#3182 #3168

**Comment by alexey-milovidov** [comment]
Fixed in recent releases.
