### ISSUE TITLE
this sql execute error. SELECT arrayMap(x->sumIf(`number`, `number`=x), [1,2]) FROM numbers(0, 100);

### ISSUE THREAD

**Issue by ltylty** [ClickHouse/ClickHouse#30153]
clickhouse version is 21.8.3.44, this sql execute error.
```SELECT arrayMap(x->sumIf(`number`, `number`=x), [1,2]) FROM numbers(0, 100);```
i change it to
```SELECT arrayMap(x->sumIf(`number`, `number`=1), [1,2]) FROM numbers(0, 100);```
then execute ok.
why? arrayMap donot push down the parameter?

```
DB::Exception: Received from localhost:9000. DB::Exception: Unknown identifier: x; there are columns: number: While processing number, number = x. (UNKNOWN_IDENTIFIER)
```

**Comment by alexey-milovidov** [comment]
This is unrelated to #23194.

It's not possible to have variable number of aggregate functions per row, that's why aggegate functions are not supported in lambdas.

Although it is possible in your example with constant arrays, it does not make sense to support just one case.
