### ISSUE TITLE
Why a non nullable field can be with null value?

### ISSUE THREAD

**Issue by flyly0755** [ClickHouse/ClickHouse#30157]
> Make sure to check documentation https://clickhouse.yandex/docs/en/ first. If the question is concise and probably has a short answer, asking it in Telegram chat https://telegram.me/clickhouse_en is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

> If you still prefer GitHub issues, remove all this text and ask your question here.

The table structure is as below:
CREATE TABLE stdfdb.tb_file
(

    `id` UUID,

    `created` DateTime DEFAULT now(),

    `updated` Nullable(DateTime),

    `remark` Nullable(FixedString(255)),

    `filename` FixedString(255),

    `type` FixedString(20)
)
ENGINE = MergeTree()
PARTITION BY id
ORDER BY id
SETTINGS index_granularity = 8192

the field type is non nullable, can add new data without type value successfully with dbeaver IDE
id                                                                 |created                             |updated   |remark   |filename      |type                |
+--------------------------------------------+----------------------------+----------+--------+-----------------
00000000-0000-0000-0000-000000000000|2021-10-14 11:26:57.000|                |               |test2.stdf     |                      |     
00000000-0000-0000-0000-000000000000|2021-10-14 11:26:31.000|                |               |test1.stdf     |                      |

**Comment by alexey-milovidov** [comment]
This is controlled by the setting `insert_null_as_default`.
You can turn this setting off if you like.

This behaviour is compatible with many other DBMS, like MySQL.

**Comment by den-crane** [comment]
> This is controlled by the setting `insert_null_as_default`.

I guess you misunderstood the problem and this setting is not applicable/relevant here.

```sql
CREATE TABLE x(a Int) ENGINE = Memory;
insert into x values (Null);

select * from x;
┌─a─┐
│ 0 │
└───┘
----------------------------------------------

mysql> CREATE TABLE x(a Int not null);

mysql> insert into x values (Null);
ERROR 1048 (23000): Column 'a' cannot be null
```
