### ISSUE TITLE
Batch insert data, got more data

### ISSUE THREAD

**Issue by ShubaoYang** [ClickHouse/ClickHouse#30216]
I have three million rows of data that I want to insert into the ClickHouse database. I inserted 10,000 rows at a time and ended up with 10 million rows in ClickHouse. After a while, it was restored to 3 million rows. What happened?

**Comment by SaltTan** [comment]
> ended up with 10 million rows in ClickHouse. After a while, it was restored to 3 million rows.

How did you check the numbers?
