### ISSUE TITLE
count is different on the PostgreSQL engine

### ISSUE THREAD

**Issue by jiangdaokun** [ClickHouse/ClickHouse#30214]
When I use CK's  PostgreSQL engine to integrate greenplum； When I counted the data on both sides, I found that the two sides were different；

CREATE TABLE da.even_trade_conf_gp (
	party_hcode Nullable(String), -- 当事人全局编码
	cust_name Nullable(String), -- 客户名称
	identi_no Nullable(String), -- 证件号码
	identi_type Nullable(String), -- 证件类型
	cust_type Nullable(String), -- 客户类型
	ta_type Nullable(String), -- TA类型
	ta_conf_no Nullable(String), -- 确认流水号
	conf_date Nullable(String) , -- 确认日期
	apply_date Nullable(String), -- 申请日期
	busi_type Nullable(String), -- 业务类型
	ex_trade_type Nullable(String), -- 外部业务类型
	ta_trade_type Nullable(String), -- 基金交易业务类型
	ta_acct Nullable(String), -- 基金账户
	trade_acct Nullable(String), -- 交易账户
	agentno Nullable(String), -- 销售商编号
	netno Nullable(String), -- 网点编号
	oper_netno Nullable(String), -- 操作网点编号
	fund_hcode Nullable(String), -- 产品全局编码
	fund_code Nullable(String), -- 产品代码
	share_type Nullable(String), -- 份额类型
	conf_amt Nullable(Decimal128(2)) , -- 确认金额
	conf_share Nullable(Decimal128(2)) , -- 确认份额
	apply_amt Nullable(Decimal128(2)) , -- 申请金额
	apply_share Nullable(Decimal128(2)) , -- 申请份额
	ttl_fee Nullable(Decimal128(2)) , -- 总费用
	comm_fee Nullable(Decimal128(2)) , -- 手续费
	transfee Nullable(Decimal128(2)) , -- 过户费
	consign_fee Nullable(Decimal128(2)) , -- 代销费
	register_fee Nullable(Decimal128(2)) , -- 未知
	fund_asset_fee Nullable(Decimal128(2)) , -- 归基金资产费
	finalsettle_comss Nullable(Decimal128(2)) , -- 后收费用
	back_chrg_agencyno Nullable(Decimal128(2)) , -- 后收费归销售机构
	back_chrg_assets Nullable(Decimal128(2)) , -- 后收费归基金资产
	oth_fee1 Nullable(Decimal128(2)) , -- 其他费用1
	int_amt Nullable(Decimal128(2)) , -- 利息
	int_amt_tax Nullable(Decimal128(2)) , -- 利息税
	stamptax Nullable(Decimal128(2)) , -- 印花税
	retrun_perm Nullable(Decimal128(2)) , -- 返还保费
	int_amt_share Nullable(Decimal128(2)) , -- 认购期利息转份额
	perfpay Nullable(Decimal128(2)) , -- 业绩报酬
	breach_amt Nullable(Decimal128(2)) , -- 违约金
	cash_unpincome Nullable(Decimal128(2)) , -- 兑现的未付收益
	cash_share Nullable(Decimal128(2)) , -- 兑付份额
	conf_unpincome Nullable(Decimal128(2)) , -- 未付收益
	deal_price Nullable(Decimal64(8)) , -- 成交价
	applyno Nullable(String), -- 申请单号
	ori_applyno Nullable(String), -- 原申请单号
	ta_sponsor_sign Nullable(String), -- TA发起标志
	bonus_type Nullable(String), -- 分红方式
	curr_hcode Nullable(String), -- 币种
	large_redem_sign Nullable(String), -- 巨额赎回处理标志
	exchange_flag Nullable(String), -- 交易所标志
	trade_handlestatus_code Nullable(String), -- 交易处理状态代码
	fail_reason_code Nullable(String), -- 失败原因代码
	opp_fund_code Nullable(String), -- 对方产品代码
	opp_share_type Nullable(String), -- 对方份额类型
	opp_ta_acct Nullable(String), -- 对方基金账户
	opp_agentno Nullable(String), -- 对方销售商编号
	opp_netno Nullable(String), -- 对方网点编号
	asset_type Nullable(String), -- 资金方式
	broker_id Nullable(String), -- 经纪人编号
	agent_chnl_code Nullable(String), -- 销售渠道编号
	trade_mode Nullable(String), -- 交易方式
	memo Nullable(String), -- 备注
	ip Nullable(String), -- 未知
	mac Nullable(String), -- 未知
	imei Nullable(String), -- 国际移动设备识别码
	uuid Nullable(String), -- 通用唯一识别码
	agio Nullable(Decimal128(10)) , -- 折扣
	request_time Nullable(String), -- 申请时间
	business_finish_flag Nullable(String), -- 未知
	error_detail Nullable(String), -- 出错详细信息
	acct_name Nullable(String), -- 投资人收款银行账户户名
	acct_no Nullable(String), -- 投资人收款银行账户户名
	clearing_agency Nullable(String), -- 投资人收款银行账户开户行
	hdatasign Nullable(String), -- 数据标识
	hloadtime Nullable(String), -- 数据时间
	hbatchdate Nullable(String), -- 批次日期
	hdatasrc Nullable(String), -- 数据源
	par_month Nullable(String) -- 未知
)
ENGINE = PostgreSQL('172.0.0.1:5432', 'gpadmin', 'even_trade_conf', 'hbxyoper', 'Hbxyoper@123','dw');

-- greenplum
select count(1) from dw.even_trade_conf where conf_date='20210506'; 
result: 8,260,023
select count(1) from dw.even_trade_conf ;
result: 2,095,769,958

-- ck
select count(1)  from da.even_trade_conf_gp where conf_date='20210506';
result: 0
select count(1)  from da.even_trade_conf_gp ;
result: 2,788,075,838

**Comment by alexey-milovidov** [comment]
You have `conf_date` as `Nullable(String)` in ClickHouse.
If it has `Date` data type in PostgreSQL, it will explain the difference.

**Comment by jiangdaokun** [comment]
@kssenii 
I guess it's because I have too much data. When I test with a table of hundreds of data, the result is right

@alexey-milovidov 
yes  conf_date is Date data type in PostgreSQL; 
However, the count results without filter conditions are also different.

--ddl in Postgres
CREATE TABLE dw.even_trade_conf (
	party_hcode text NULL,                     
	cust_name text NULL,                       
	identi_no text NULL,                       
	identi_type text NULL,                     
	cust_type text NULL,                       
	ta_type text NULL,                         
	ta_conf_no text NULL,                      
	conf_date date NULL,                       
	apply_date date NULL,                      
	busi_type text NULL,                       
	ex_trade_type text NULL,                   
	ta_trade_type text NULL,                   
	ta_acct text NULL,                         
	trade_acct text NULL,                      
	agentno text NULL,                         
	netno text NULL,                           
	oper_netno text NULL,                      
	fund_hcode text NULL,                      
	fund_code text NULL,                       
	share_type text NULL,                      
	conf_amt numeric(20,2) NULL,               
	conf_share numeric(20,2) NULL,             
	apply_amt numeric(20,2) NULL,              
	apply_share numeric(20,2) NULL,            
	ttl_fee numeric(20,2) NULL,                
	comm_fee numeric(20,2) NULL,               
	transfee numeric(20,2) NULL,               
	consign_fee numeric(20,2) NULL,            
	register_fee numeric(20,2) NULL,           
	fund_asset_fee numeric(20,2) NULL,         
	finalsettle_comss numeric(20,2) NULL,      
	back_chrg_agencyno numeric(20,2) NULL,     
	back_chrg_assets numeric(20,2) NULL,       
	oth_fee1 numeric(20,2) NULL,               
	int_amt numeric(20,2) NULL,                
	int_amt_tax numeric(20,2) NULL,            
	stamptax numeric(20,2) NULL,               
	retrun_perm numeric(20,2) NULL,            
	int_amt_share numeric(20,2) NULL,          
	perfpay numeric(20,2) NULL,                
	breach_amt numeric(20,2) NULL,             
	cash_unpincome numeric(20,2) NULL,         
	cash_share numeric(20,2) NULL,             
	conf_unpincome numeric(20,2) NULL,         
	deal_price numeric(16,8) NULL,             
	applyno text NULL,                         
	ori_applyno text NULL,                     
	ta_sponsor_sign text NULL,                 
	bonus_type text NULL,                      
	curr_hcode text NULL,                      
	large_redem_sign text NULL,                
	exchange_flag text NULL,                   
	trade_handlestatus_code text NULL,         
	fail_reason_code text NULL,                
	opp_fund_code text NULL,                   
	opp_share_type text NULL,                  
	opp_ta_acct text NULL,                     
	opp_agentno text NULL,                     
	opp_netno text NULL,                       
	asset_type text NULL,                      
	broker_id text NULL,                       
	agent_chnl_code text NULL,                 
	trade_mode text NULL,                      
	memo text NULL,                            
	ip text NULL,                              
	mac text NULL,                             
	imei text NULL,                            
	uuid text NULL,                            
	agio numeric(30,10) NULL,                  
	request_time text NULL,                    
	business_finish_flag text NULL,            
	error_detail text NULL,                    
	acct_name text NULL,                       
	acct_no text NULL,                         
	clearing_agency text NULL,                 
	hdatasign text NULL,                       
	hloadtime timestamp NULL,                  
	hbatchdate date NULL,                      
	hdatasrc text NULL,                        
	par_month text NULL,                       
	par_day text NULL                       
);

**Comment by alexey-milovidov** [comment]
@jiangdaokun Can be the reason that the data in table is constantly changing and you have queried it in different moments of time?

**Comment by alexey-milovidov** [comment]
ClickHouse does not perform any magic work, it only sends a query to Postgres.
You can check Postgres/Greenplum logs to find what query was sent and what result did it give.
