### ISSUE TITLE
Materialized view deduplication using a checksum of the main insert.

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#30240]
Imagine an internal_insert (under the hood, code level, not SQL level) that has an attribute insert_id (and it's optional, if it's missing then the checksum of a block will be used and insert_id will be populated with that checksum).
This attribute can be exposed to the SQL level using settings (for example `insert into .... settings insert_id=42`), but it's not mandatory for this FR.

The idea is that Materialized Views when they get data from the main internal_insert they also get this inherited insert_id, and they use this insert_id as deduplication checksum and store it in ZK and don't calculate a checksum of the block themselves. 
They also propagate this inherited insert_id to their heirs (cascaded MV).

The only main insert (SQL) calculates insert_id as a checksum of the inserted block if it's missing. All nested inserts have insert_id filled always.

In this case you can repeat inserts and Materialized views will be consistent because they don't calculate a checksum by themselve.

**Comment by azat** [comment]
Seems that it had been fixed by #32304.
And even the case with multiple blocks via MVs (since it simply uses increment counter in this token for multiple parts within one INSERT).

**Comment by den-crane** [comment]
Yes, insert_deduplication_token can do it. 
I even added a test for it https://github.com/ClickHouse/ClickHouse/pull/34662

Anyway I think it worth to implement without using insert_deduplication_token

And it does not work for not replicated MergeTree tables (`non_replicated_deduplication_window = 100;`)

**Comment by CheSema** [comment]
This will be covered in https://github.com/ClickHouse/ClickHouse/issues/60008.
