### ISSUE TITLE
Multiple UPDATE is not working 

### ISSUE THREAD

**Issue by ArunGust** [ClickHouse/ClickHouse#30256]
> You have to provide the following information whenever possible.

I tried to updated multiple rows in one statement but didn't work. got below error

{ status: 400, version: HTTP/1.1, headers: {"date": "Fri, 15 Oct 2021 21:50:38 GMT", "connection": "Keep-Alive", "content-type": "text/plain; charset=UTF-8", "x-clickhouse-server-display-name": "ubuntu", "transfer-encoding": "chunked", "x-clickhouse-exception-code": "62", "keep-alive": "timeout=3", "x-clickhouse-summary": "{\"read_rows\":\"0\",\"read_bytes\":\"0\",\"written_rows\":\"0\",\"written_bytes\":\"0\",\"total_rows_to_read\":\"0\"}"}, body: Body(?) }

> A clear and concise description of what works not as it is supposed to.

ALTER TABLE emptable UPDATE  CarryOverTeikyu = '4', LeftOverYukyu = '36' WHERE EmpID = '550' ;   ALTER TABLE emptable UPDATE  CarryOverTeikyu = '0', LeftOverYukyu = '10' WHERE EmpID = '1242' ;

**Comment by ArunGust** [comment]
Thanks, Do you support multiple statements in native TCP connection?

**Comment by den-crane** [comment]
>Do you support multiple statements in native TCP connection?

No, for compatibility with HTTP.
