### ISSUE TITLE
Allow to specify single disk instead of a storage_policy for MergeTree tables.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#30299]
Add `disk` setting to `MergeTreeSettings`. It can refer to disk by name in `storage_configuration` in config.
The setting will have the same effect as if a storage policy with single disk will be used.

The settings `disk` and `storage_policy` cannot be used together.

**Comment by Joeywzr** [comment]
I'd like to help:)

**Comment by alexey-milovidov** [comment]
Thank you, let's do it!

**Comment by garneja** [comment]
Instead of introducing an <disk> option to MergeTree settings, it might make more sense to just have an implicitly defined  default storage_policy for ever configured disk. Something like this would be implicitly be created as SroragePolicy for all configured disks: 

    <policies>
        <default.policy.disk._diskname_>
            <volumes>
                <default.volume.disk._diskname_>
                    <disk>_diskname_</disk>
                </default.volume.disk._diskname_> 
        </default.policy.disk._diskname_>
    </policies>

**Comment by alexey-milovidov** [comment]
I thought if we simply write `disk = 'name'` instead of `storage_policy = 'some_cryptic_name'` it will be more clear.

**Comment by garneja** [comment]
I agree it would be clearer if the setting was just ```disk = 'name'``` However, if we allow for both ```storage_policy``` and ```disk``` the MergeTree code now has to deal with a disk config and a storage_policy config and the two are mutually exclusive. It would be better, I think, if we did not have two mutually exclusive configs. 

Also the MergeTree code expects a StoragePolicyPtr to get to disks. Maybe we could just internally create a StoragePolicy for each defined disk and return that if ```disk``` is configured the storage policy.

**Comment by alexey-milovidov** [comment]
> Also the MergeTree code expects a StoragePolicyPtr to get to disks. Maybe we could just internally create a StoragePolicy for each defined disk and return that if disk is configured the storage policy.

Yes, this is exactly what I expect.

**Comment by zhongyuankai** [comment]
@alexey-milovidov I would like to work on this.

**Comment by alesapin** [comment]
@zhongyuankai Still interested?

**Comment by alexey-milovidov** [comment]
@kssenii FYI
