### ISSUE TITLE
Hints for unknown settings based on edit distance.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#30305]
**Use case**

If there is no setting that the user has typed but there is a setting with similar name, print hints.

Tests:

1. `SET input_format_with_names_use_headers = 1`
2. `clickhouse-client --input_format_with_names_use_headers 1`
3. `curl http://localhost:8123/?input_format_with_names_use_headers=1 -d 'SELECT 1'`

**Describe the solution you'd like**

See `IHints` and its usages.

**Comment by alesapin** [comment]
Done
