### ISSUE TITLE
Unable to connect to HDFS: InvalidParameter: RpcAuth: Unknown auth mechanism type: OAUTHBEARER

### ISSUE THREAD

**Issue by jiangdaokun** [ClickHouse/ClickHouse#30317]
**Describe the unexpected behaviour**
I want to use HDFS engine on Clickhouse, But an error occurred when I query:
Unable to connect to HDFS: InvalidParameter: RpcAuth: Unknown auth mechanism type: OAUTHBEARER

**How to reproduce**
* Which ClickHouse server version to use
21.8.3.44

* Non-default settings, if any
 
    <hdfs>
        <hadoop_kerberos_keytab>/etc/clickhouse-server/clickhouse.keytab</hadoop_kerberos_keytab>
        <hadoop_kerberos_principal>clickhouse@TDHTEST</hadoop_kerberos_principal>
        <hadoop_security_authentication>kerberos</hadoop_security_authentication>
        <libhdfs3_conf>/etc/clickhouse-server/hdfs-site.xml</libhdfs3_conf>
    </hdfs>

* `CREATE TABLE` statements for all tables involved
CREATE TABLE da.base_agent_info_oper_hdfs
(
    `agent_no` String,
    `agent_name` String,
    `agent_type` String,
    `phoneno` String,
    `hdatasign` String,
    `hloadtime` String,
    `hbatchdate` String,
    `hdatasrc` String
)
ENGINE = HDFS('hdfs://172.30.83.203:8020/inceptor1/user/hive/warehouse/da.db/hbxyoper/base_agent_info_oper/*', 'ORC')
--hive
CREATE  TABLE `da.base_agent_info_oper`(
  `agent_no` string DEFAULT NULL, 
  `agent_name` string DEFAULT NULL, 
  `agent_type` string DEFAULT NULL, 
  `phoneno` string DEFAULT NULL, 
  `hdatasign` string DEFAULT NULL, 
  `hloadtime` string DEFAULT NULL, 
  `hbatchdate` string DEFAULT NULL, 
  `hdatasrc` string DEFAULT NULL
)
COMMENT '产品信息维表'
CLUSTERED BY ( 
  `agent_no`) 
INTO 1 BUCKETS
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001' STORED AS ORC ;

* Queries to run that lead to unexpected result
select * from da.base_agent_info_oper_hdfs ;

**Error message and/or stacktrace**
2021.10.18 09:36:14.875756 [ 47896 ] {b4814402-ff95-4257-b314-2def8f615c20} <Debug> executeQuery: (from 172.0.0.1:64688) select * from da.base_agent_info_oper_hdfs FORMAT TabSeparatedWithNamesAndTypes 
2021.10.18 09:36:14.875992 [ 47896 ] {b4814402-ff95-4257-b314-2def8f615c20} <Trace> ContextAccess (default): Access granted: SELECT(agent_no, agent_name, agent_type, phoneno, hdatasign, hloadtime, hbatchdate, hdatasrc) ON da.base_agent_info_oper_hdfs
2021.10.18 09:36:14.876062 [ 47896 ] {b4814402-ff95-4257-b314-2def8f615c20} <Debug> HDFSClient: running kinit: kinit -R -t "/etc/clickhouse-server/clickhouse.keytab" -k clickhouse@TDHTEST|| kinit -t "/etc/clickhouse-server/clickhouse.keytab" -k clickhouse@TDHTEST
2021.10.18 09:36:14.876074 [ 47896 ] {b4814402-ff95-4257-b314-2def8f615c20} <Trace> ShellCommand: Will start shell command '/bin/sh' with arguments 'sh', '-c', 'kinit -R -t "/etc/clickhouse-server/clickhouse.keytab" -k clickhouse@TDHTEST|| kinit -t "/etc/clickhouse-server/clickhouse.keytab" -k clickhouse@TDHTEST'
2021.10.18 09:36:14.876215 [ 47896 ] {b4814402-ff95-4257-b314-2def8f615c20} <Trace> ShellCommand: Started shell command '/bin/sh' with pid 8045
2021.10.18 09:36:14.876228 [ 47896 ] {b4814402-ff95-4257-b314-2def8f615c20} <Trace> ShellCommand: Will wait for shell command pid 8045
2021.10.18 09:36:14.882050 [ 47896 ] {b4814402-ff95-4257-b314-2def8f615c20} <Trace> ShellCommand: Wait for shell command pid 8045 completed with status 0
2021.10.18 09:36:14.887460 [ 47896 ] {b4814402-ff95-4257-b314-2def8f615c20} <Error> executeQuery: Code: 210, e.displayText() = DB::Exception: Unable to connect to HDFS: InvalidParameter: RpcAuth: Unknown auth mechanism type: OAUTHBEARER (version 21.8.3.44 (official build)) (from 172.30.113.194:64688) (in query: select * from da.base_agent_info_oper_hdfs FORMAT TabSeparatedWithNamesAndTypes ), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x8f9b87a in /usr/bin/clickhouse
1. DB::createHDFSFS(hdfsBuilder*) @ 0xfa6c230 in /usr/bin/clickhouse
2. DB::StorageHDFS::read(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryInfo&, std::__1::shared_ptr<DB::Context const>, DB::QueryProcessingStage::Enum, unsigned long, unsigned int) @ 0xfa61524 in /usr/bin/clickhouse
3. DB::IStorage::read(DB::QueryPlan&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryInfo&, std::__1::shared_ptr<DB::Context const>, DB::QueryProcessingStage::Enum, unsigned long, unsigned int) @ 0x10907137 in /usr/bin/clickhouse
4. DB::InterpreterSelectQuery::executeFetchColumns(DB::QueryProcessingStage::Enum, DB::QueryPlan&) @ 0x103b2cfc in /usr/bin/clickhouse
5. DB::InterpreterSelectQuery::executeImpl(DB::QueryPlan&, std::__1::shared_ptr<DB::IBlockInputStream> const&, std::__1::optional<DB::Pipe>) @ 0x103aab9c in /usr/bin/clickhouse
6. DB::InterpreterSelectQuery::buildQueryPlan(DB::QueryPlan&) @ 0x103a9d80 in /usr/bin/clickhouse
7. DB::InterpreterSelectWithUnionQuery::buildQueryPlan(DB::QueryPlan&) @ 0x1057bdde in /usr/bin/clickhouse
8. DB::InterpreterSelectWithUnionQuery::execute() @ 0x1057ceb1 in /usr/bin/clickhouse
9. ? @ 0x1073d724 in /usr/bin/clickhouse
10. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::__1::shared_ptr<DB::Context>, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>, std::__1::optional<DB::FormatSettings> const&) @ 0x107411fd in /usr/bin/clickhouse
11. DB::HTTPHandler::processQuery(std::__1::shared_ptr<DB::Context>, DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::__1::optional<DB::CurrentThread::QueryScope>&) @ 0x10f68d2d in /usr/bin/clickhouse
12. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x10f6c489 in /usr/bin/clickhouse
13. DB::HTTPServerConnection::run() @ 0x10fee050 in /usr/bin/clickhouse
14. Poco::Net::TCPServerConnection::start() @ 0x13b5bc0f in /usr/bin/clickhouse
15. Poco::Net::TCPServerDispatcher::run() @ 0x13b5d69a in /usr/bin/clickhouse
16. Poco::PooledThread::run() @ 0x13c90519 in /usr/bin/clickhouse
17. Poco::ThreadImpl::runnableEntry(void*) @ 0x13c8c7aa in /usr/bin/clickhouse
18. start_thread @ 0x7dd5 in /usr/lib64/libpthread-2.17.so
19. clone @ 0xfeb3d in /usr/lib64/libc-2.17.so

**Comment by alexey-milovidov** [comment]
We don't support HDFS.
