### ISSUE TITLE
It's not possible to define CTE before INSERT in INSERT SELECT query.

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#30323]
**Describe the issue**
It's not possible to define CTE before INSERT in INSERT SELECT statement.

**How to reproduce**
ClickHouse 21.11

```
WITH x AS (SELECT * FROM numbers(1000)) INSERT INTO test_tbl_mem SELECT * FROM x;

Syntax error: failed at position 41 ('INSERT'):

WITH x AS (SELECT * FROM numbers(1000)) INSERT INTO test_tbl_mem SELECT * FROM x;

Expected one of: SELECT, Comma, token

INSERT INTO test_tbl_mem WITH x AS
    (
        SELECT *
        FROM numbers(1000)
    )
SELECT *
FROM x

Query id: eacdd594-49d3-4800-9fd1-7ac0f9593ff4

Ok.

0 rows in set. Elapsed: 0.003 sec.
```

**Expected behavior**
First query should work.

**Additional context**
PostgreSQL docs about CTE + INSERT SELECT

https://www.postgresql.org/docs/14/queries-with.html#QUERIES-WITH-MODIFYING

**Comment by tamilselvan-stratforge** [comment]
Any update on this?

**Comment by michaelritsema** [comment]
As a work around until this gets implemented (especially if porting a lot of code with CTE) is to use a view. This prevents needing from rearranging the code and can be usually search/replaced

**Comment by UnamedRus** [comment]
Pull request https://github.com/ClickHouse/ClickHouse/pull/70593
