### ISSUE TITLE
MaterializeMySQL engine doesn't do garbage collection for deleted row

### ISSUE THREAD

**Issue by liangli1213** [ClickHouse/ClickHouse#30354]
**Describe what's wrong**

For all ClickHouse version which has supported MaterializeMySQL, in source table (MySQL), do a delete operation, the operation can be synchronized to destination table (ClickHouse), but only mark _sign column to -1, the row will not be deleted or be garbage collected, it will be there forever.

So is this a bug? @tavplubix

**Comment by tavplubix** [comment]
Automatic cleanup is not implemented, see https://github.com/ClickHouse/ClickHouse/issues/4006#issuecomment-657486437
MaterializedMySQL feature is mostly developed and supported by community, so there is currently no progress on the remaining tasks to make it production-ready.

**Comment by liangli1213** [comment]
@tavplubix, thanks for your explanation, hope someone can help complete the gc function.

**Comment by alexey-milovidov** [comment]
I'm closing all old issues about MaterializedMySQL because the ClickHouse team does not support it.

**Comment by liangli1213** [comment]
@alexey-milovidov, what do you mean by 'doesn't support it'? will ClickHouse nolonger support MaterializedMySQL?

**Comment by alexey-milovidov** [comment]
ClickHouse has MaterializedMySQL under the experimental flag, but the only remaining maintainer of this feature is @stigsb 
The main team has no intentions or obligations to provide support for MaterializedMySQL in form of patches or answering questions. That's why the only thing we can do with the opened issues is: - wait if they will be fixed by someone else; - close after some period of time.

**Comment by R-omk** [comment]
workaround 

```SQL
TABLE OVERRIDE table1 (
    TTL now() + INTERVAL 1 MINUTE DELETE WHERE _sign = -1
)
```

**Comment by bakwc** [comment]
> workaround

This workaround sometimes not delete some rows. Even worse - before they were not deleted but hidden for user, after the workaround - they start showing to user and never deleted.
