### ISSUE TITLE
Backward compatibility replication error: Cannot read all data. Bytes read: 0. Bytes expected: 8.

### ISSUE THREAD

**Issue by evgeny-l** [ClickHouse/ClickHouse#3036]
Hello!
We are trying to add 2 new server in our cluster shard and tried to use latest ClickHouse version, but seems like they are incompatible with the old one we had.

Servers versions:
old server 1.1.54189
new server 18.10.3 (rev 54405)

Error is:

2018.09.04 15:33:57.384157 [ 16 ] <Error> events.bid_events (StorageReplicatedMergeTree): DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Code: 33, e.displayText() = DB::Exception: Cannot read all data. Bytes read: 0. Bytes expected: 8., e.what() = DB::Exception, Stack trace:

0. /usr/bin/clickhouse-server(StackTrace::StackTrace()+0x16) [0x56d06c6]
1. /usr/bin/clickhouse-server(DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)+0x22) [0x2da2d92]
2. /usr/bin/clickhouse-server() [0x502bf71]
3. /usr/bin/clickhouse-server(DB::DataPartsExchange::Fetcher::fetchPart(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, DB::ConnectionTimeouts const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x7d0) [0x502f7d0]
4. /usr/bin/clickhouse-server(DB::StorageReplicatedMergeTree::fetchPart(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, unsigned long)+0x5f0) [0x4fef8c0]
5. /usr/bin/clickhouse-server(DB::StorageReplicatedMergeTree::executeFetch(DB::ReplicatedMergeTreeLogEntry&)+0x761) [0x4ff0da1]
6. /usr/bin/clickhouse-server(DB::StorageReplicatedMergeTree::executeLogEntry(DB::ReplicatedMergeTreeLogEntry&)+0xb2) [0x4ff20b2]
7. /usr/bin/clickhouse-server() [0x4ff296f]
8. /usr/bin/clickhouse-server(DB::ReplicatedMergeTreeQueue::processEntry(std::function<std::shared_ptr<zkutil::ZooKeeper> ()>, std::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&, std::function<bool (std::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&)>)+0x55) [0x50edf45]
9. /usr/bin/clickhouse-server(DB::StorageReplicatedMergeTree::queueTask()+0x200) [0x4fce000]
10. /usr/bin/clickhouse-server(DB::BackgroundProcessingPool::threadFunction()+0x47e) [0x5029dce]
11. /usr/bin/clickhouse-server() [0x930310f]
12. /lib/x86_64-linux-gnu/libpthread.so.0(+0x76db) [0x7f8244c9c6db]
13. /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7f824442388f]

Is this error can be fixed or this is something related to backward incompatibility?
And what is the best way to replicate data in this case into new versions of ClickHouse server?

**Comment by alexey-milovidov** [comment]
It's Ok if you experience this issue when replicas have different versions.
Replication will stop and it will continue to work when upgrade of the remaining servers will be done.

The system remains available for SELECT queries during rolling update and data remains in correct state.
So, rolling upgrade remains possible even for 3-years old releases.
