### ISSUE TITLE
Speeding up Final by 500% by splitting query into UNION ALL of non overlapping PK ranges

### ISSUE THREAD

**Issue by jorisgio** [ClickHouse/ClickHouse#30387]
Hi, i am looking about optimizing merging of live updated data a recurrent question i know, but it seems a lot slower than it can be. Let's take a table like
```sql
CREATE TABLE test (
    part_key UInt8,
    key1 String,
    key2 String,
    event_time DateTime,
    hash_of_key1_key2 UInt64,
    dimension_1 String,
    metrics_1 UInt64
    )
    PARTITION BY part_key
    ORDER BY (key1, key2)
    Engine = ReplacingMergeTree(event_time)
 ```
    
where primary key contains fairly large string.
Data set is partitioned by key space to reduce merges pressure in relatively large partitions of ~3B rows. Partitioning by date does not really make sense in the access pattern. We store hash_of_key to use the method below, and for various memory optimisations in join (with bloom index), it is simply a hash of key1, key2
    
  At lookup time, if we want to get only the latest rows, there are a lot of solutions : 
  - the fastest one is : 
  
   ```sql
   SELECT any(key1), any(key2), argMax(dimension_1, event_time), argMax(metrics_1, event_time) FROM test GROUP BY hash_of_key1_key2
   ```
   In an example data set scanning ~50M rows/20G it is a baseline of 1s. But obviously, it consumes a lot of memory, and does not scale much more, because finishing aggregation is very cpu intensive. 
   
   - the "classic" method is to use FINAL. It is not clear in my head how FINAL actually works, i don't understand wether it performs a full mergeSort like optimize_read_in_order, or if it just accumulates blocks with overlapping data from sorted input stream. The problem is, final is awfully slow.
   In the same data set as above, with max_final_threads=16, max_threads=32, 12 parts to read, it runs in 20s instead of 1s. The advantage being that it runs in almost constant memory
   
   - the "optimize_aggregation_in_order=1" way, grouping primary key look roughly similar to FINAL in term of performance. With the difference that it seems to generate a lot more ranges, and split parts ranges into fair sized ranges. I'm not sure what the difference with final here is, but in anycase it is not faster.
   
   - another idea is to avoid merging alltogether, using a set, since it is ReplacingMergeTree
 ```sql
 SELECT key1, key2, dimension_1, metrics_1
 FROM test
 WHERE (hash_of_key1_key2, event_time) IN (SELECT hash_of_key1_key2, max(event_time) FROM test GROUP BY hash_of_key1_key2)
 ```
 This is already faster than FINAL and GROUP BY optimize_aggregation_in_order, and uses less memory than GROUP BY hash_of_key1_key2 but there is a high cost into building temporary set, which dominates the time.
 
 Now about the actual question. The really fast and low memory way to do this is to split primary key space into fair ranges. In my case, i'm using 500k rows blocks. Then i generate a very big UNION ALL query : 
 
```sql
SELECT * FROM test FINAL 
 WHERE 
   key1 > 'start_key1' OR (key1 = 'start_key1' AND key2 >= 'start_key2')
   AND key1 < 'end_key1' OR (key1 = 'end_key1' AND key2 < 'end_key2')
 UNION ALL SELECT * FROM test FINAL 
 ``` 
 Note it must use boolean condition to implement lexicographic order, else index code is unable to use tuple to optimize range.
 If I generate such a query for the same 50M rows data set, the query runs in 3s and ~7G ram which is bigger than FINAL ram but much lower than GROUP by. Care should be taken to set max_final_threads=1 to prevent over use of ram. Due to index granularity, it adds a bit of over-read, almost 20%, but for a 6 times speedup, i'm willing to buy it.
 
 This is more than *6 times* faster than using FINAL directly, and it cannot really be solved by using partitions, because reducing partitions to 500k/1m rows make ingestion speed very hard, and Replication stuggles to keep up. 
 But this is really complex to set up in practices for several reasons : 
 1. It is hard to compute fair ranges live, since there is no way to access the primary key index in memory directly in sql, which would allow to do that. SAMPLE key requires adding hash into the PK, and is not so fast for live fetch either. So the solution is to have a table storing ranges rebuilt periodically, very adhoc and inconvenient
 1. It makes using distributed table impossible, so client has to fetch ranges, and generate A HUUUUGE SELECT query with UNION ALL for each shard, using 'remote' function. And i didn't find a way to do it live besides generating union all programatically, which adds a round trip to the server. 
 
 My quesion becomes, is there a way to make CH behaves similarly to this *natively* or at least solutions to simplify generating concatenation queries ?

**Comment by jorisgio** [comment]
Adding more details, consider the following pipeline for aggregation_in_order, with max_threads=32 
```
┌─explain───────────────────────────────────────┐
│ (Expression)                                  │
│ ExpressionTransform × 32                      │
│   (Aggregating)                               │
│   MergingAggregatedBucketTransform × 32       │
│     Resize 1 → 32                             │
│       FinishAggregatingInOrderTransform 8 → 1 │
│         AggregatingInOrderTransform × 8       │
│           (Expression)                        │
│           ExpressionTransform × 8             │
│             (Filter)                          │
│             FilterTransform × 8               │
│               (SettingQuotaAndLimits)         │
│                 (ReadFromMergeTree)           │
│                 MergeTreeInOrder × 8 0 → 1    │
└───────────────────────────────────────────────┘
[laksa109] 2021.11.30 11:19:14.532967 [ 4223 ] {4124cea2-8b81-4988-9479-9fcdb69e4539} <Debug> backlinks.backlinks_local (dd700733-ac2d-42b5-8df0-0a51fb083c05) (SelectExecutor): Selected 9/1516 parts by partition key, 8 parts by primary key, 45/926751 marks by primary key, 44 marks to read from 8 ranges
[laksa109] 2021.11.30 11:19:14.533119 [ 4223 ] {4124cea2-8b81-4988-9479-9fcdb69e4539} <Debug> MergeTreeInOrderSelectProcessor: Reading 1 ranges in order from part 7_162648_162648_0, approx. 4096 rows starting from 0
[laksa109] 2021.11.30 11:19:14.533176 [ 4223 ] {4124cea2-8b81-4988-9479-9fcdb69e4539} <Debug> MergeTreeInOrderSelectProcessor: Reading 1 ranges in order from part 7_162641_162646_1, approx. 4096 rows starting from 12288
[laksa109] 2021.11.30 11:19:14.533237 [ 4223 ] {4124cea2-8b81-4988-9479-9fcdb69e4539} <Debug> MergeTreeInOrderSelectProcessor: Reading 2 ranges in order from part 7_161415_162640_6, approx. 8192 rows starting from 2097152
[laksa109] 2021.11.30 11:19:14.533293 [ 4223 ] {4124cea2-8b81-4988-9479-9fcdb69e4539} <Debug> MergeTreeInOrderSelectProcessor: Reading 1 ranges in order from part 7_160188_161414_5, approx. 4096 rows starting from 2142208
[laksa109] 2021.11.30 11:19:14.533351 [ 4223 ] {4124cea2-8b81-4988-9479-9fcdb69e4539} <Debug> MergeTreeInOrderSelectProcessor: Reading 2 ranges in order from part 7_139240_160187_37, approx. 8192 rows starting from 25579520
[laksa109] 2021.11.30 11:19:14.533407 [ 4223 ] {4124cea2-8b81-4988-9479-9fcdb69e4539} <Debug> MergeTreeInOrderSelectProcessor: Reading 3 ranges in order from part 7_96062_139239_11_122350, approx. 16384 rows starting from 33189888
[laksa109] 2021.11.30 11:19:14.533468 [ 4223 ] {4124cea2-8b81-4988-9479-9fcdb69e4539} <Debug> MergeTreeInOrderSelectProcessor: Reading 3 ranges in order from part 7_1419_96061_17_122350, approx. 20480 rows starting from 61992960
[laksa109] 2021.11.30 11:19:14.533518 [ 4223 ] {4124cea2-8b81-4988-9479-9fcdb69e4539} <Debug> MergeTreeInOrderSelectProcessor: Reading 5 ranges in order from part 7_0_1418_4_122350, approx. 114688 rows starting from 827176472
``` 
The execution is bounded by at least two issues : 
- contrary to the cool new MergeTreeReadPool used for Default read mode, reading is still done by part. Due to how merge works, the vast majority of data will likely end up in a few parts, so this kills read parallelism because one or two threads end up doing the vast majority of the work.
- FinishAggregatingInOrderTransform performs block based merge sorts, and it remains single thread, acting as a bottleneck even if the operation in itself is probably the cheapest in the whole pipeline, on large data it is an issue. 

As shown above, by manually splitting the part into ranges in SQL, we regain parallelism by kind of executing this pipeline in two-levels mode, except it does not need the second level since ranges are not overlapping. And the speedup can be huge as long as there are enough max-threads to read more in parallell, and to perform block merge sort in parallel.

**Comment by KochetovNicolai** [comment]
Both `FINAL` and `aggregation_in_order` read data in a single thread. Both read data in order, which may be not necessary.
What's necessary is to read in-order rows with equal pk; groups of rows with the same pk may be mixed. But, as long as rows with the same PK may be spread between different parts, it was just easier to implement single thread merge sorting scan. (Here, for `aggregation_in_order` do honest merge sort, but for parallel `FINAL` use very fast hash over PK to spread work between threads).

I suppose, we can implement `FINAL` with PK filtering (as well as aggregation-in-order). In theory, we have an index, and we can split our PK range evenly between threads (it is still not clear how we can do it, and how well). There could possibly be another setting.

Thank you for the idea. It is good to know that some queries may possibly run 5 times faster :)

**Comment by alexey-milovidov** [comment]
> we can split our PK range evenly between threads (it is still not clear how we can do it, and how well)

By the number of bytes between mark ranges.

**Comment by KochetovNicolai** [comment]
> By the number of bytes between mark ranges.

Still, it is not completely clear. Different parts may have different intersections, e.g:
```
-> PK sorting
[     |                |        ] <- part 1
      ^   [                          |     |     |   ] <- part 2
   mark       [   | | | | | | ] <- part 3
```
Also, for compact parts it is difficult to estimate the number of bytes per column per granule now.
Anyway, for every mark we can probably get an estimation in a number of bytes we need to read before it.

**Comment by jorisgio** [comment]
>Still, it is not completely clear. Different parts may have different intersections

Indeed, it is not straightforward. I am currently doing something similar at sql level. Basically I have a table storing ranges of pk with 500k rows granularity. Initially the idea was to generate a big query using cluster table functions that would contain local ranges for each shards but obviously clickhouse is not happy getting 200mb of sql.

So right now I combine ranges into fair ranges for the whole distributed tables using a greedy approximation :
- First all ranges are combined into a list of ranges in lexicographic order by lower bound
- max local ranges per shard is computed using number of maximum ranges on a single shard divided by number of wanted ranges.
- The range list is scanned in order, counting number of local ranges seen so far for each shard
- as soon as one shard reaches max ranges per shard we emit a bound. The first column is just the current values, but subsequent columns are expanded to min and max values seen on all shard so far on this range.

This is to work relatively well for my case, but clickhouse is still not handling 100 of union all very well it takes a long time to start executing it.

For parts it could also be good enough to get the bigger part and simply compute ranges for it. Though it might depend too much on insertion pattern to be applicable in general.

**Comment by KochetovNicolai** [comment]
@jorisgio nice algorithm
I think, we can implement something like this.

**Comment by UnamedRus** [comment]
> Indeed, it is not straightforward. I am currently doing something similar at sql level. Basically I have a table storing ranges of pk with 500k rows granularity. Initially the idea was to generate a big query using cluster table functions that would contain local ranges for each shards but obviously clickhouse is not happy getting 200mb of sql.

I think it's possible to add some adjustments to your query generator:

>  Basically I have a table storing ranges of pk with 500k rows granularity.

Store this (or precalculated key ranges?) in dictionary (either the same for all shards, either individual for each shard). (auto-update + extremely cheap dictGet calls, no need to generate individual query per shard)

Create VIEW on shards, which will contain your aggregation + WHERE conditions + dictGet calls. (should reduce total size of SQL query)
In order to push correct range id to the specific view call, you can use custom settings

```
SELECT getSetting('custom_range_num')
SETTINGS custom_range_num = 1
UNION ALL
SELECT getSetting('custom_range_num')
SETTINGS custom_range_num = 2

┌─getSetting('custom_range_num')─┐
│                              1 │
└────────────────────────────────┘
┌─getSetting('custom_range_num')─┐
│                              2 │
└────────────────────────────────┘
```

https://kb.altinity.com/altinity-kb-queries-and-syntax/altinity-kb-parameterized-views/

**Comment by jorisgio** [comment]
About the usecases, there are two : 
1) finalize a mergetree table
2) finalize/aggregage a mergetree table by a prefix of primary key.

We are talking about hundred of millions of rows with relatively big size (multiple big string zstd compressed), can easily reached 1TB per host. But IO is not a bottleneck, scannning the data without aggregation takes below 1s, while all current approach can take up to a minute with aggregation. Obviously aggregations are costly, but the above examples with union all shows that it could be a lot faster.

For 1), in theory FINAL is enough, but it is quite slow. One of the problem of FINAL is that it does not seem possible to PREWHERE filter before applying merge by a column outside of primary key, except by filtering mark with indices but this has high granularity.  Obviously the general case it is incorrect, but when known to be correct it can improve performance a lot by filtering a lot of data. One example is monotonic timestamp that cannot be in partition key due as it would put too many constraint in disk space since partitions are never merged, and on zookeeper due to the amount of partitions it would create. Adding timestamp constraint before final still make sense in this case.
Secondly, final does not do work stealing, parts are assigned to threads, unlinke in non final case where stream are fairly spread. I'm not sure what is the limitation but on a live database, there are many small parts and a couple big parts, so one thread will handle only the big part.
Thirdly, even if the blocks are resharded before merge sorting, as shown above it is still quite a lot slower than doing an UNION of final with fair ranges, i am not exactly sure about what is a bottleneck in the final pipeline but the numbers still show a 5 times speed up, even with the added cost of reading indices and markcache for all ranges.
So basically, the usecase of final remains a lot slower than it could be.

For 1) and 2) we can also use group by with optimize_aggregation in order. The advantage is that it allows prewhere, so in some cases it can give a nice speedup. It also seems to handle work stealing with streams, so big parts are splitted accross stream. But for some reason, this too is much much faster with union all, and in general is not really faster than final in general. 

For 2), as far as i know we have two options. First group by in order, that is also a lot slower than it could be as demonstrated with union all. But in our case, due to disk space constraints, primary key contains strings, relatively large. This is improves compression a lot to put similar data next to each over, but it obviously slows down aggregation quite a bit. A workaround is to add a hash column, with precomputed UInt64 hash of primary key prefix. This uses specialized integer aggregation code, which is a lot faster, but it cannot really work due to memory usage, and big cost of finalize aggregation on hundred of gigabyte of data. 
Indeed, since aggregation in order optimization cannot be applied, it has to read the whole data into memory (preprocessed by  AggregatingTransform). This has too big issues, first memory and secondly that aggregation is single thread. As far as i know, there is no way to tell clickhouse that it is safe to split group by by primary key ranges and finalize aggregation range by range, even when hash is computed at runtime. (tried to mark hash function as injective, even if a bit of a lie, but it does not help).

So basically the usecase is to take live updated mergetree data and read it finalized or aggregated by a prefix of primary key, which i suspect a lot of people want to do. But as testing by splitting data into fair ranges of primary key show and running parallel union all queries with the same number of threads, it is a lot slower than it could be.

**Comment by nickitat** [comment]
it was surprisingly easy to reproduce. it is the [script](https://github.com/nickitat/ClickHouse/blob/c558e63a205e1e3d814894adb4392e05b14ba3d4/script.sh) I used. timings were 6.234s, 7.345s, and 4.165s correspondingly.
