### ISSUE TITLE
Is there any method to query like sum(argMax())? Or using multiple aggregation functions?

### ISSUE THREAD

**Issue by TianyiLu** [ClickHouse/ClickHouse#3039]
My data set is organized by a group of index as key, a value and a version using ReplacingMergeTree engine. There may be several different values for a same key. Thus, I use ReplacingMergeTree to do version control.

However, due to ClickHouse's uncontrollable merging strategy, ReplacingMergeTree engine doesn't guarantee there is only the latest version in table. Besides, your query syntax doesn't support using more than one aggregation function in a single query, so, every time I query for something I need to write a select query using sum(Max) from an another select query result using argMax(value, version) as Max.

This result in obviously performance decrease and more memory cost. So, can you give me some suggestion on how to deal with such problem? The main purpose is to cut off resource waste and optimize query performance.

**Comment by amosbird** [comment]
That doesn't make sense to me as `argMax()` would collapse different values in the same key group. Can you elaborate with an example?

**Comment by TianyiLu** [comment]
For example, I have three keys {key1, key2, key3} and a value {value} and a version {version}

I may need to write query like this:

select sum(T), key2 from {select key2,  argMax(value, version) as T from SomeTable where XXX condition group by key1, key2, key3} group by key2.

The problem is that only when you use all the three keys {key1, key2, key3}, you can identify a record exactly and you can find the top version on it. But I just want to aggregate (use sum) to sum up and group by a single key, it isn't something that a single aggregation function "argMax" can solve.

**Comment by filimonov** [comment]
1) You can use FINAL keyword to get finally merged state of the table, but it has some performance penalty. But may be it will be bit faster than subselect, i.e. just ```select sum(T), key2 from SomeTable FINAL where XXX condition group by key2```
2) That is one of cases where CollapsingMergeTree is better than ReplacingMergeTree.
I.e. when you do simple aggregations like sum - you don't need to take care of those cases.
3) sounds like you need window functions, they are not supported at the moment.
4) in clickhouse there is a function called LIMIT BY which can be useful sometimes, for example in your case you can try something like```
select sum(value), key2 from ( select key2, value from SomeTable where XXX condition ORDER BY version DESC LIMIT 1 by key1, key2, key3 ) group by key2.
```

**Comment by TianyiLu** [comment]
Hi,
Your suggestion seems good!
Could you please give me an example on how to use CollapsingMergeTree on my case? Basically, I just want to pick every unique key-value pair that is the top version(or latest version) and aggregate all of them by some index, and avoid selecting from subselect result as well.

**Comment by TianyiLu** [comment]
After testing, I find it difficult to use FINAL or CollapsingMergeTree.
1. FINAL performance is really poor due to my query is very heavy. Basically, my query will hit 200 million rows and FINAL performance is even worse than query from the result of sub-query.

2. In fact, CollapsingMergeTree seems to be an incremental strategy. However, if you want to replace one row, you must know this row clearly before insertion, even the value, not only the keys. Thus, it seems that you must do some select before insertion to get the value. 

So what if I can only know my key as my key groups are numerous(around 2 million groups) that it's impossible to hold the "current" state collection(which can be seen as "values")?

For example:

Old row：

key1, key2, key3, value1, sign=1;

New row:
key1, key2, key3, value2

if you want to replace this line, you should insert
key1, key2, key3,value1, sign=-1
and 
key1,key2,key3,value2, sign=1

However, I can't hold the hold row which means I must query the value for this key group (key1,key2,key3). Only after a query on (key1,key2,key3) can I now the old value {value1} and then I can insert a same row signed as -1.

So, do I must run this "old value fetching" query before I can update the value by CollapsingMergeTree?

**Comment by filimonov** [comment]
> So, do I must run this "old value fetching" query before I can update the value by CollapsingMergeTree?

yes, if you like to go that direction.

**Comment by TianyiLu** [comment]
Yep... Your example query performs as same as my previous query. Both of them query from a sub-query result. When the query is heavy, you must load the sub-query result into memory, which costs a lot.

So, is there any other way to avoid query from a sub-query in my situation?

**Comment by alexey-milovidov** [comment]
> When the query is heavy, you must load the sub-query result into memory, which costs a lot.

Not necessarily. Subqueries can be processed in a streaming fashion. Even for queries with GROUP BY.

> So, is there any other way to avoid query from a sub-query in my situation?

No.
