### ISSUE TITLE
Flaky test: test_dictionaries_dependency_xml

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#30402]
https://clickhouse-test-reports.s3.yandex.net/0/885c4daf94541b9077230ef8753769aafa1a6f05/integration_tests_(release).html

```
        # Update the source table.
        query("INSERT INTO test.elements VALUES (3, 'fire', 30, 8)")
    
        # Wait for dictionaries to be reloaded.
        assert_eq_with_retry(instance, "SELECT dictHas('dep_y', toUInt64(3))", "1", sleep_time=2, retry_count=10)
        assert query("SELECT dictGetString('dep_x', 'a', toUInt64(3))") == "XX\n"
        assert query("SELECT dictGetString('dep_y', 'a', toUInt64(3))") == "fire\n"
>       assert query("SELECT dictGetString('dep_z', 'a', toUInt64(3))") == "ZZ\n"
E       AssertionError: assert 'fire\n' == 'ZZ\n'
E         - ZZ
E         + fire

test_dictionaries_dependency_xml/test.py:65: AssertionError
```

| check_name | pull_request_number | check_start_time | test_status | report_url | commit_sha | test_name |
|:-|-:|-:|:-|:-|:-|:-|
| Integration tests (release) | 0 | 2021-10-19 13:27:56 | FLAKY | https://clickhouse-test-reports.s3.yandex.net/0/9195e4e887e6f05cf41ce326d0de98e1ae1204f5/integration_tests_(release).html | 9195e4e887e6f05cf41ce326d0de98e1ae1204f5 | test_dictionaries_dependency_xml/test.py::test_get_data |
| Integration tests (memory) | 0 | 2021-10-19 12:30:34 | FLAKY | https://clickhouse-test-reports.s3.yandex.net/0/4396daeb1f465cf498fb708c25e7b1f9c60a3281/integration_tests_(memory).html | 4396daeb1f465cf498fb708c25e7b1f9c60a3281 | test_dictionaries_dependency_xml/test.py::test_get_data |
| Integration tests (memory) | 0 | 2021-10-19 11:54:40 | FLAKY | https://clickhouse-test-reports.s3.yandex.net/0/1e2ceeb2e7faa220abbdb5d68ba707fe391a3976/integration_tests_(memory).html | 1e2ceeb2e7faa220abbdb5d68ba707fe391a3976 | test_dictionaries_dependency_xml/test.py::test_get_data |
| Integration tests (thread) | 0 | 2021-10-19 11:45:09 | FLAKY | https://clickhouse-test-reports.s3.yandex.net/0/ea2a64772400759d445ee0308c99b940094c0a40/integration_tests_(thread).html | ea2a64772400759d445ee0308c99b940094c0a40 | test_dictionaries_dependency_xml/test.py::test_get_data |
| Integration tests (asan) | 0 | 2021-10-19 11:30:06 | FLAKY | https://clickhouse-test-reports.s3.yandex.net/0/1e2ceeb2e7faa220abbdb5d68ba707fe391a3976/integration_tests_(asan).html | 1e2ceeb2e7faa220abbdb5d68ba707fe391a3976 | test_dictionaries_dependency_xml/test.py::test_get_data |
| Integration tests (thread) | 0 | 2021-10-19 11:01:30 | FLAKY | https://clickhouse-test-reports.s3.yandex.net/0/1e2ceeb2e7faa220abbdb5d68ba707fe391a3976/integration_tests_(thread).html | 1e2ceeb2e7faa220abbdb5d68ba707fe391a3976 | test_dictionaries_dependency_xml/test.py::test_get_data |
| Integration tests (thread) | 0 | 2021-10-19 09:44:55 | FLAKY | https://clickhouse-test-reports.s3.yandex.net/0/cc7a3ea9ff4127d2d7c7f80c752fbc6d6a87b2ef/integration_tests_(thread).html | cc7a3ea9ff4127d2d7c7f80c752fbc6d6a87b2ef | test_dictionaries_dependency_xml/test.py::test_get_data |
| Integration tests (thread) | 0 | 2021-10-19 09:01:01 | FLAKY | https://clickhouse-test-reports.s3.yandex.net/0/53ad965f8ef20d4da64dab722e48c8c415a5f690/integration_tests_(thread).html | 53ad965f8ef20d4da64dab722e48c8c415a5f690 | test_dictionaries_dependency_xml/test.py::test_get_data |
| Integration tests (asan) | 0 | 2021-10-18 21:38:45 | FLAKY | https://clickhouse-test-reports.s3.yandex.net/0/885c4daf94541b9077230ef8753769aafa1a6f05/integration_tests_(asan).html | 885c4daf94541b9077230ef8753769aafa1a6f05 | test_dictionaries_dependency_xml/test.py::test_get_data |
| Integration tests (thread) | 0 | 2021-10-18 21:18:39 | FLAKY | https://clickhouse-test-reports.s3.yandex.net/0/75c16b8f8924f3e397c5b2e8a4c8da8ddfd7c79e/integration_tests_(thread).html | 75c16b8f8924f3e397c5b2e8a4c8da8ddfd7c79e | test_dictionaries_dependency_xml/test.py::test_get_data |

**Comment by alexey-milovidov** [comment]
Did not reproduce in 10 days.

https://gh-api.clickhouse.com/play?user=play&url=https%3A%2F%2Fplay-ci.clickhouse.com%2F#U0VMRUNUIGV4dHJhY3QodGVzdF9uYW1lLCAnXi4rLycpIEFTIG5hbWUsIGNvdW50KCkgQVMgYywgYXJnTWF4KHJlcG9ydF91cmwsIGNoZWNrX3N0YXJ0X3RpbWUpCkZST00gYGdoLWRhdGFgLmNoZWNrcwpXSEVSRQogICAgY2hlY2tfbmFtZSBMSUtFICdJbnRlZ3JhdGlvbiUnCiAgICBBTkQgKHRlc3Rfc3RhdHVzIExJS0UgJ0YlJyBPUiB0ZXN0X3N0YXR1cyBMSUtFICdFJScpCiAgICBBTkQgcHVsbF9yZXF1ZXN0X251bWJlciA9IDAKICAgIEFORCBjaGVja19zdGFydF90aW1lID49IHRvZGF5KCkgLSA3CkdST1VQIEJZIG5hbWUKSEFWSU5HIG1heChjaGVja19zdGFydF90aW1lKSA+PSBub3coKSAtIElOVEVSVkFMIDI0MCBIT1VSCk9SREVSIEJZIGMgREVTQw==
