### ISSUE TITLE
timeZoneNormalize function

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#30415]
**Use case**

Table has 2 columns:
timestamp DateTime,
timezone LowCardinality(String),

Each timestamp has individual timezone value and we need somehow to convert those timestamps to a single timezone.

**Describe the solution you'd like**

```
SELECT timeZoneNormalize(timestamp, timezone); -- to UTC

SELECT timeZoneNormalize(timestamp, timezone, 'Europe/Moscow'); -- destination timezone.
```

**Comment by alexey-milovidov** [comment]
It's possible to make timezone argument non-constant for `toString` function: `toString(time, tz)`

**Comment by UnamedRus** [comment]
Hm,  it could also work.

But i would prefer to avoid convert to String and back to timestamp afterwards.

**Comment by alexey-milovidov** [comment]
Timezone conversion is not specified for the DateTime column, because it is represented by Unix timestamp internally.
Unix timestamp is an absolute instant of time, there is no sense in converting it to another timezone.

**Comment by UnamedRus** [comment]
>  Unix timestamp is an absolute instant of time, there is no sense in converting it to another timezone.

Problem is:
It's quite a painful problem for several companies.
They need to keep information about Timezone, but TZ data in DateTime is part of DataType and not column value. 
So they store this information in separate column.

And they need to do 2 tasks:

1. Filter this DateTime column by DateTime in UTC timezone.
2. Show result to user in event timezone.

**Comment by alexey-milovidov** [comment]
`toString` with a non-constant timezone argument can suffice.
Let's create another task for that.

**Comment by dominikprester** [comment]
> Timezone conversion is not specified for the DateTime column, because it is represented by Unix timestamp internally.
> Unix timestamp is an absolute instant of time, there is no sense in converting it to another timezone.

"Unix timestamp is an absolute instant of time, there is no sense in converting it to another timezone." Nice and proactive response. Kudos friend.

**Comment by UnamedRus** [comment]
Similar functions, which are part of ANSI SQL 

https://docs.oracle.com/cd/E11882_01/server.112/e41084/functions068.htm#SQLRF00644

https://docs.oracle.com/cd/E11882_01/server.112/e10729/ch4datetime.htm#NLSPG264
https://docs.teradata.com/r/Enterprise_IntelliFlex_VMware/SQL-Date-and-Time-Functions-and-Expressions/DateTime-and-Interval-Functions-and-Expressions/ANSI-DateTime-Expressions/AT-LOCAL-and-AT-TIME-ZONE-Time-Zone-Specifiers
