### ISSUE TITLE
about MaterializeMySQL  change PARTITION BY toYYYYMM() 

### ISSUE THREAD

**Issue by vegastar002** [ClickHouse/ClickHouse#30445]
clickhouse version : 21.3
mysql version : 5.7

I have a MaterializeMySQL  table, it's structure:

CREATE TABLE ck.t1
(
    `XZQH` String,
    `JJDBH` String,
    `SJDBH` String,
    `BJFSDM` String,
    `JJLXDM` String,
    `CLLXDM` String,
    `JJDWDM` String,
    `JJYGH` String,
    `JJYXM` String,
    `JJTBH` String,
    `JJTIP` String,
    `HRSJ` String,
    `BJSJ` DateTime,
    `HZSJ` String,
    `BJDH` String,
    `SJXZQH` String,
    `BDLAJBZ` String,
    `RKSJ` String,
    `BJZLDM` String,
    `SFCKZDJQ` String,
    `AY` String,
    `_sign` Int8 MATERIALIZED 1,
    `_version` UInt64 MATERIALIZED 1
)
ENGINE = ReplacingMergeTree(_version)
ORDER BY (XZQH, JJDBH)
SETTINGS index_granularity = 8192

i know MaterializeMySQL  default partition is  intDiv(id, 4294967) . 
but I frequently  sql  is  like  " where  datetime1 > xxx and datetime1 < yyy "  .
so I want to ask how to change to PARTITION BY toYYYYMM()  ?

**Comment by stigsb** [comment]
Currently there is no way to do this. I am planning to contribute a patch that lets you tweak the schema, hopefully in a few weeks.

**Comment by stigsb** [comment]
See #31480 for a proposal on how this could be achieved.

**Comment by stigsb** [comment]
See #32325 for a solution.
This issue may be closed now.
