### ISSUE TITLE
Changing cluster topology giving different result due to distributed_group_by_no_merge=1

### ISSUE THREAD

**Issue by DipalPrajapati** [ClickHouse/ClickHouse#30503]
I have my  **2 shards 2 replicas** cluster , where distributed_group_by_no_merge=1 in queries works perfectly.
 
But the same query with distributed_group_by_no_merge=1 giving less number of records in **2 shards 3 replicas** cluster topology. 

I could not understand the behavior. Can you please explain ?

**Comment by den-crane** [comment]
it should work.
Please share <remote_servers> and macros shard / replica

**Comment by DipalPrajapati** [comment]
<remote_servers>
        
        <distributed>
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                    <host>host-0-0</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>host-0-1</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>host-0-2</host>
                    <port>9000</port>
                </replica>
            </shard>
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                    <host>host-1-0</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>host-1-1</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>host-1-2</host>
                    <port>9000</port>
                </replica>
            </shard>
        </distributed>
        
        <all-replicated>
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                    <host>host-0-0</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>host-0-1</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>host-0-2</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>host-1-0</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>host-1-1</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>host-1-2</host>
                    <port>9000</port>
                </replica>
            </shard>
        </all-replicated>
        <all-sharded>
            <shard>
                <internal_replication>false</internal_replication>
                <replica>
                    <host>host-0-0</host>
                    <port>9000</port>
                </replica>
            </shard>
            <shard>
                <internal_replication>false</internal_replication>
                <replica>
                    <host>host-0-1</host>
                    <port>9000</port>
                </replica>
            </shard>
            <shard>
                <internal_replication>false</internal_replication>
                <replica>
                    <host>host-0-2</host>
                    <port>9000</port>
                </replica>
            </shard>
            <shard>
                <internal_replication>false</internal_replication>
                <replica>
                    <host>host-1-0</host>
                    <port>9000</port>
                </replica>
            </shard>
            <shard>
                <internal_replication>false</internal_replication>
                <replica>
                    <host>host-1-1</host>
                    <port>9000</port>
                </replica>
            </shard>
            <shard>
                <internal_replication>false</internal_replication>
                <replica>
                    <host>host-1-2</host>
                    <port>9000</port>
                </replica>
            </shard>
        </all-sharded>
    </remote_servers>
    And replica names  are also individual and unique  across all the nodes.
