### ISSUE TITLE
clickhouse-format can't parse complex queries

### ISSUE THREAD

**Issue by siradjev** [ClickHouse/ClickHouse#30528]
**Describe the unexpected behaviour**
clickhouse-format can't parse complex queries. 
Code: 306, e.displayText() = DB::Exception: Maximum parse depth (1000) exceeded. Consider rising max_parser_depth parameter., Stack trace (when copying this message, always include the lines below):

**How to reproduce**
write any query that requires adjustment of parser settings:
max_ast_depth
max_ast_elements
max_parser_depth 
max_query_size
max_subquery_depth

**Expected behavior**
clickhouse-format shall support parameters of clickhouse-client related to query parsing.

**Comment by taiyang-li** [comment]
I wanna to try it

**Comment by taiyang-li** [comment]
Only `max_query_size` and `max_parser_depth` have affect on clickhouse-format.
