### ISSUE TITLE
S3 metadata restore - restoring to before a mutation on one table causes metadata restore of a different table to fail.

### ISSUE THREAD

**Issue by MyroTk** [ClickHouse/ClickHouse#30527]
**Describe what's wrong**
Using s3 metadata to restore a table (table0) to before a mutation causes the next table (table1) restore to fail. If I restore table0 to after the mutation or the mutation doesn't happen, table1 is restored correctly.

**How to reproduce**

* Which ClickHouse server version to use
21.8.9.13

* `CREATE TABLE` statements for all tables involved
All tables are created and attached this way but the names are different.
```
[CREATE | ATTACH] TABLE [table_name] (id UInt64, x UInt64)
ENGINE = MergeTree()
PARTITION BY id
ORDER BY id
SETTINGS storage_policy='external'
```
* Configs
node1 - bucket is 'root'
```
 <yandex>
   <!--config uid: 87d31bae_3288_11ec_825f_99724a71d554-->
   <storage_configuration>
     <disks>
       <external>
         <type>s3</type>
         <endpoint>http://minio1:9001/root/data/</endpoint>
         <access_key_id>minio</access_key_id>
         <secret_access_key>minio123</secret_access_key>
         <send_metadata>true</send_metadata>
         <list_object_keys_size>1</list_object_keys_size>
       </external>
     </disks>
     <policies>
       <external>
         <volumes>
           <external>
             <disk>external</disk>
           </external>
         </volumes>
       </external>
     </policies>
   </storage_configuration>
 </yandex>
```
node2 - bucket is 'root2'
```
 <yandex>
   <!--config uid: 87d31bae_3288_11ec_825f_99724a71d554-->
   <storage_configuration>
     <disks>
       <external>
         <type>s3</type>
         <endpoint>http://minio1:9001/root2/data/</endpoint>
         <access_key_id>minio</access_key_id>
         <secret_access_key>minio123</secret_access_key>
         <send_metadata>true</send_metadata>
         <list_object_keys_size>1</list_object_keys_size>
       </external>
     </disks>
     <policies>
       <external>
         <volumes>
           <external>
             <disk>external</disk>
           </external>
         </volumes>
       </external>
     </policies>
   </storage_configuration>
 </yandex>
```
* Queries to run that lead to unexpected result

on node1:
Create table0
`INSERT INTO table0 VALUES (1,2)`
`ALTER TABLE table0 FREEZE`
Get the revision number from /var/lib/clickhouse/disks/external/shadow/1/revision.txt - revision number before mutation
`ALTER TABLE table0 UPDATE x = 1 WHERE 1`

on node2:
Create restore file at /var/lib/clickhouse/disks/external/restore:
```
revision=[revision number]
source_bucket=root
```
`SYSTEM RESTART DISK external`
Attach table0
`SELECT sum(x) FROM table0`  - should be 2 as it's before the ALTER UPDATE.

on both node1 and node2:
`DROP TABLE table0 SYNC`
remove /var/lib/clickhouse/disks/external/*
remove /var/lib/clickhouse/shadow/*

on node1 for the rest:
Create table1
`INSERT INTO table1 VALUES (1,2)`
`DETACH TABLE table1`
Remove /var/lib/clickhouse/disks/external/*
Create empty restore file at /var/lib/clickhouse/disks/external/restore
`SYSTEM RESTART DISK external`
`ATTACH TABLE table1`
`SELECT count(*) FROM table1` - Returns 0 even though it should be 1. If the `ALTER UPDATE` doesn't happen or table0 is restore to after the mutation, this returns 1.

**Comment by alexey-milovidov** [comment]
The "send metadata" feature is not used, it is not supposed to work and is going to be removed.
