### ISSUE TITLE
Map of different data types

### ISSUE THREAD

**Issue by ilugid** [ClickHouse/ClickHouse#30531]
**Use case**

We have a table in Hive with a multiple nested data structure. Each of the nested sections has a mix of data types, such as Int, Array and Strings.

We are trying to use it as a dictionary in Clickhouse.

We are unable to create mappings due to limitation of Map type declaration.
1. It supports only one set of Key, Value declaration.
2. There is no provision to add sub-nests.

e.g hive schema.
(
`regular_col1` boolean,
`regular_col2` string,
`nested_top1` struct<
    `nested_sub1`: struct<
        `nested_sub1_2-1`: struct<
            `nested_sub1_2_3-1`: array<string>,
            `nested_sub1_2_3-2`: struct<
                `nested_sub1_2_3_2-1`: string,
                `nested_sub1_2_3_2-2`: string
    	        >,
            `nested_sub1_2_3-3`: struct<
                `nested_sub1_2_3_3-1`: string,
                `nested_sub1_2_3_3-2`: bigint
                >
            >
        >,
    `nested_sub2`: struct<
        `nested_sub2_2-1`: string,
        `nested_sub2_2-2`: string,
        `nested_sub2_2-3`: bigint,
        >
    >
)

**Describe the solution you'd like**
Ability to map above hive table in something sort of like below

CREATE TABLE clickhouse_nested_maps
(
`regular_col1` Boolean,
`regular_col2` String,
`nested_top1` Map
        (
            String, Map
            (
                String, Map
                   (
                       String: Array(String),
                       String, Map
                       (
                            String, String #####Single declaration can handle both set of strings.
                       )
                       String: Map
                       (
                           String, String,
                           String, Int64,
                       )
                     )
             )
             String, Map
             (
                 String, String,
                 String, String,
                 String, Int64,
             )
          )
)
ENGINE = HDFS('hdfs://hadoop:9000/user/hive/warehouse/nested_hive_table/*', 'Parquet')

**Describe alternatives you've considered**
Convert original table to a more flat format.

**Comment by alexey-milovidov** [comment]
Hive is not supported.
