### ISSUE TITLE
Replicated Merge Tree showing record count as multiplication of number of replication

### ISSUE THREAD

**Issue by manojrbj** [ClickHouse/ClickHouse#3058]
Hi Team,

I have create a 5 node cluster having replication factor as 3. I created ReplicatedMergeTree table on all node and created Distributed table on top of it. I am inserting data into Distributed table from a log table where record count is 2337420 (log table). I fired select row count on distributed table and finding record count as 7012260.

I have configured replication as below.

`
<Clickhouse_10shards_3replica>
            <shard>
                <replica>
                    <host>host1</host>
                    <port>9020</port>
                </replica>
		<replica>
                    <host>host2</host>
                    <port>9020</port>
                </replica>
		<replica>
                    <host>host3</host>
                    <port>9020</port>
                </replica>
            </shard>
             <shard>
                <replica>
                    <host>host2</host>
                    <port>9020</port>
                </replica>
		<replica>
                    <host>host3</host>
                    <port>9020</port>
                </replica>
		<replica>
                    <host>host4</host>
                    <port>9020</port>
                </replica>
            </shard>
            <shard>
                <replica>
                    <host>host3</host>
                    <port>9020</port>
                </replica>
		<replica>
                    <host>host4</host>
                    <port>9020</port>
                </replica>
		<replica>
                    <host>host5</host>
                    <port>9020</port>
                </replica>
            </shard>
...............
<Clickhouse_10shards_3replica>
`

Create ReplicatedMergeTree is as below:
`create table replica_table ()ENGINE = ReplicatedMergeTree('/clickhouse/Clickhouse_10shards_3replica/online/replica_table/{shard}', 'host1-01', end_date, (id), 8192)");`

Distributed table is as below.
`CREATE TABLE replica_tableD AS replica_table ENGINE = Distributed (Clickhouse_10shards_3replica, online, replica_table, rand())`

I followed the URL: https://www.altinity.com/blog/2018/5/10/circular-replication-cluster-topology-in-clickhouse

Also when we read data from distributed table, returned data is inconsistent. Please guide me. It is critical for delivery.

Please suggest why incorrect row count id being returned ?

**Comment by alexey-milovidov** [comment]
@manojrbj For circular replication, you should place different shards in different databases and specify database names in the cluster configuration for every shard.
