### ISSUE TITLE
Option `--format` for `clickhouse-local` should set both input and output formats.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#30631]
`clickhouse-local` can take three options: `--input-format`, `--output-format` and `--format`.
Currently the `--format` option only sets the output format.

Let's make it set default input and output formats that can be overriden by `--input-format` and `--output-format`.

**Comment by Armenqaa** [comment]
Wanna try it!

**Comment by alexey-milovidov** [comment]
@Armenqaa Thank you, let's do it!

**Comment by alexey-milovidov** [comment]
See ClientBase, Client and LocalServer h/cpp files.

**Comment by Armenqaa** [comment]
found smth close, but apparently not what we want:
https://github.com/ClickHouse/ClickHouse/blob/master/programs/local/LocalServer.cpp#L544 
 
and the path from here to the functions did not lead anywhere:
https://github.com/ClickHouse/ClickHouse/blob/master/src/Client/ClientBase.cpp#L1713

Is that where I'm looking?

**Comment by alexey-milovidov** [comment]
@Armenqaa Yes, we should set both `format` and `insert_format`.

**Comment by alexey-milovidov** [comment]
@Armenqaa Hi, how is it?
