### ISSUE TITLE
HTAP support/ Queries with join

### ISSUE THREAD

**Issue by itzikiusa** [ClickHouse/ClickHouse#30659]
Hi,
Wanted to know if there are any plans of supporting new table engines which will be more suitable for small transactions(even with table limit of 100mill records), which will also support updates and deletes directly?
maybe even embedding a different database within(like embedded rocksdb)

on that note(or different one)
Any plans on optimizing join queries?
Mainly the filters which are being applied, so that less data will be joined

thanks, Itzik

**Comment by gingerwizard** [comment]
hi @itzikiusa thanks for the question.

As you may already know, we already support rocks db as an engine type - https://clickhouse.com/docs/en/engines/table-engines/integrations/embedded-rocksdb/

This also supports instance updates through inserts. This ideal for small records when requesting rows by a specific key or reading random rows by a filter.

This DB can be used in conjunction with Dictionary engines, which can be used to accelerate JOINS e.g.

`CREATE DICTIONARY new_dictionary(id UInt64, value UInt64 DEFAULT 0) PRIMARY KEY id
SOURCE(CLICKHOUSE(HOST 'localhost' PORT tcpPort() USER 'default' TABLE 'rocks_db_engine')) LAYOUT(DIRECT());
`
and then create a dictionary table using a[ dictionary table engine](https://clickhouse.com/docs/en/engines/table-engines/special/dictionary/) i.e.

`CREATE TABLE new_dictionary_table (id UInt64, value UInt64 DEFAULT 0) engine = Dictionary(new_dictionary)`

This table can in turn be used for joins.

Currently, this requires the dictionary to fit into memory. The improvement https://github.com/ClickHouse/ClickHouse/issues/33582 is planned and will allow us to handle filters and join dictionaries larger than memory.

**Comment by gingerwizard** [comment]
Closing with no response in 2 weeks.
