### ISSUE TITLE
Got message DB::Exception: <path> already exists

### ISSUE THREAD

**Issue by leidruid** [ClickHouse/ClickHouse#3067]
Hi there! 
I got the following message
2018.08.27 15:41:11.969067 [ 11 ] <Error> void DB::BackgroundProcessingPool::threadFunction(): Code: 84, e.displayText() = DB::Exception: Directory /.1/clickhouse/data/db/archive/tmp_merge_20180827_20180827_1850553031_1850553061_6/ already exists, e.what() = DB::Exception, Stack trace:
1. /usr/bin/clickhouse-server(DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)+0x22) [0x2d74962]
2. /usr/bin/clickhouse-server(DB::MergeTreeDataMergerMutator::mergePartsToTemporaryPart(DB::MergeTreeDataMergerMutator::FuturePart const&, DB::MergeListEntry&, unsigned long, long, DB::DiskSpaceMonitor::Reservation*, bool)+0x4d17) [0x4fd79f7]
3. /usr/bin/clickhouse-server(DB::StorageMergeTree::merge(unsigned long, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)+0x58e) [0x4f2d13e]
4. /usr/bin/clickhouse-server(DB::StorageMergeTree::mergeTask()+0xe9) [0x4f2d6b9]
5. /usr/bin/clickhouse-server(DB::BackgroundProcessingPool::threadFunction()+0x47e) [0x4f9491e]
6. /usr/bin/clickhouse-server() [0x92cc1af]
7. /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7fe53ec776ba]
8. /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7fe53e4a041d]

It reproduces when server IO is high (see graph)
![gitissue](https://user-images.githubusercontent.com/4631781/45210657-dac64480-b298-11e8-9d7b-d50043b5547a.png)

**Comment by alexey-milovidov** [comment]
Not reproduced on recent releases.
