### ISSUE TITLE
Allow to create Merge, Distributed and Replicated tables without specifying a list of columns.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#30671]
Partially described here #14450
but I've moved to a separate task as it is only slightly related.

**Use case**

Suggested by ClickHouse user https://segment.com/ and https://www.twilio.com/.

If there is already a replica (for Replicated) or remote tables (for Distributed) or matching table (for Merge), pick the schema from it instead of requiring to repeat it in CREATE TABLE.

**Describe the solution you'd like**

Another factory method registered in StorageFactory that table engines can provide and InterpreterCreateQuery will use. By default it will throw exception that schema is required.

For Replicated tables, it will go to ZooKeeper and look for metadata. If there are no replicas, it will throw exception that schema is required.

For Distributed tables it will connect to any available replica of first shard and get schema from it. If the table does not exist on that shard or if all replicas are unavailable, try next shard, etc. If there are no tables on every shard, throw exception that schema is required.

For Merge tables it will find matching tables and create a schema by unification of their schemas.

**Comment by alexey-milovidov** [comment]
@Avogar Is it solved?

**Comment by Avogar** [comment]
Yes, was solved in https://github.com/ClickHouse/ClickHouse/pull/32455
