### ISSUE TITLE
Proposal: Bool data type

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#30684]
**Use case**

1. Allow TRUE/FALSE literals in SQL for compatibility (esp. for Postgres).
Example: `WHERE c = TRUE`. Example: `SET allow_hyperscan = FALSE`.
2. Easy parsing of True/False/T/F/Y/N/Yes/No/On/Off from CSV and TSV if the data type is Bool.
This is safe, as we will only allow it for `Bool` data type.
3. Render as true/false in JSON. Allow to choose custom representation when output data in text formats (CSV, TSV).

**Describe the solution you'd like**

As DataTypeDomain.

`Bool` data type should work in all places where UInt8 is allowed.
For example, it should be allowed to sum or take an average of values of Bool data type.

One difference is in text serialization and deserialization.
Another difference is that the values can be checked to be 0 or 1 when data is saved into table, when it is parsed from text format or deserialized from binary format.

**Comment by MaxWk** [comment]
@alexey-milovidov Hi Alexy, could you help me review this pr: https://github.com/ClickHouse/ClickHouse/pull/31072
