### ISSUE TITLE
RabbitMQ engine truncates the last character

### ISSUE THREAD

**Issue by WRMSRwasTaken** [ClickHouse/ClickHouse#30691]
(you don't have to strictly follow this form)

**Describe the unexpected behaviour**
I am using [pmacct](https://github.com/pmacct/pmacct) to stream network flow data via RabbitMQ to ClickHouse.

The data generated from pmacct in RabbitMQ looks like this when I request a message from the RabbitMQ web management:

Exchange: `pmacct`
Routing Key: `acct`
Properties: `delivery_mode: 2` & `content_type: application/json`
Payload:
```json
{"event_type": "purge", "as_src": 1234, "as_dst": 0, "as_path": "", "local_pref": 100, "med": 0, "peer_as_dst": 0, "ip_src": "<redacted ipv6>", "ip_dst": "<redacted ipv6>", "port_src": 443, "port_dst": 41930, "ip_proto": "tcp", "tos": 0, "stamp_inserted": "2021-10-26 15:20:00", "stamp_updated": "2021-10-26 15:23:14", "packets": 2, "bytes": 1216, "writer_id": "default_amqp/449206"}
```

I created the RabbitMQ engine table with:
```sql
create table pmacct.ingest (json String) engine = RabbitMQ settings rabbitmq_host_port = '10.10.3.8:5672', rabbitmq_exchange_name = 'pmacct', rabbitmq_routing_key_list = 'acct', rabbitmq_exchange_type = 'direct', rabbitmq_persistent = 1, rabbitmq_format = 'LineAsString'
```

SELECT-ing the data from that table gives me:
```
{"event_type": "purge", "as_src": 1234, "as_dst": 0, "as_path": "", "local_pref": 100, "med": 0, "peer_as_dst": 0, "ip_src": "<redacted ipv6>", "ip_dst": "<redacted ipv6>", "port_src": 443, "port_dst": 41930, "ip_proto": "tcp", "tos": 0, "stamp_inserted": "2021-10-26 15:20:00", "stamp_updated": "2021-10-26 15:23:14", "packets": 2, "bytes": 1216, "writer_id": "default_amqp/449206"
```
Where it is missing the `}` at the end, producing invalid JSON. Also, creating the table with `JSON` as `rabbitmq_format` does not work, SELECT-ing data from it yields the error: `DB::Exception: Format JSON is not suitable for input: While executing SourceFromInputStream.`, maybe because of the invalid JSON? Does ClickHouse truncate the last character because it is expecting a newline character?

My current workaround is adding the `}` back to each line with `concat()` in a MATERIALIZED VIEW:
```sql
CREATE MATERIALIZED VIEW ingest_mv TO data AS
SELECT
    JSONExtractString(concat(json, '}'), 'event_type') AS event_type,
    JSONExtractInt(concat(json, '}'), 'as_src') AS as_src,
    JSONExtractInt(concat(json, '}'), 'as_dst') AS as_dst,
    JSONExtractString(concat(json, '}'), 'as_path') AS as_path,
    JSONExtractInt(concat(json, '}'), 'local_pref') AS local_pref,
    JSONExtractInt(concat(json, '}'), 'med') AS med,
    JSONExtractInt(concat(json, '}'), 'peer_as_dst') AS peer_as_dst,
    IPv6StringToNum(JSONExtractString(concat(json, '}'), 'ip_src')) AS ip_src,
    IPv6StringToNum(JSONExtractString(concat(json, '}'), 'ip_dst')) AS ip_dst,
    JSONExtractInt(concat(json, '}'), 'port_src') AS port_src,
    JSONExtractInt(concat(json, '}'), 'port_dst') AS port_dst,
    JSONExtractString(concat(json, '}'), 'ip_proto') AS ip_proto,
    JSONExtractInt(concat(json, '}'), 'tos') AS tos,
    parseDateTime32BestEffortOrZero(JSONExtractString(concat(json, '}'), 'stamp_inserted')) AS stamp_inserted,
    parseDateTime32BestEffortOrZero(JSONExtractString(concat(json, '}'), 'stamp_updated')) AS stamp_updated,
    JSONExtractInt(concat(json, '}'), 'packets') AS packets,
    JSONExtractInt(concat(json, '}'), 'bytes') AS bytes,
    JSONExtractString(concat(json, '}'), 'writer_id') AS writer_id
FROM ingest;
```

There is another issue for me: After dropping the MATERIALIZED VIEW, the RabbitMQ table does not get filled anymore. SELECT-ing data from the RabbitMQ table says `0 rows in set.` and the messages start filling up in the RabbitMQ queue. I have to drop the RabbitMQ engine table aswell and re-create it, then I am able to SELECT message again. Also, ClickHouse sometimes crashes while dropping the view, as seen in https://github.com/ClickHouse/ClickHouse/issues/29315 with the exact stack trace.

Versions are:
Clickhouse 21.4.6.55-1
RabbitMQ 3.8.22-1

**Comment by kssenii** [comment]
@WRMSRwasTaken 
adding `rabbitmq_row_delimiter = '\n'` to the list of settings will fix the first issue.

**Comment by kssenii** [comment]
@WRMSRwasTaken
Second issue fixed here https://github.com/ClickHouse/ClickHouse/pull/30997. It happened only with select query after dropping mv. Adding mv back makes the table filling again.

Third issue same as  #29315 haven't reproduced yet. 
> while dropping the view, as seen in #29315 with the exact stack trace.

Are you sure it is connected with dropping the view? I would say it can be connected with detaching table or connection lost issue...

**Comment by WRMSRwasTaken** [comment]
> @WRMSRwasTaken adding `rabbitmq_row_delimiter = '\n'` to the list of settings will fix the first issue.
Thanks! I'm going to try this later today.

> @WRMSRwasTaken Second issue fixed here #30997. It happened only with select query after dropping mv. Adding mv back makes the table filling again.
That's some good news, also thanks for recognizing that bug.

> Third issue same as #29315 haven't reproduced yet. Added tests which will possibly reproduce in our CI.
> Are you sure it is connected with dropping the view? I would say it can be connected with detaching table or connection lost issue...
I'm going to try and test this in the next few days and see if I can correlate both things. I am also not entirely sure about this, to be honest... I was dropping the view, wanted to re-create it and the client was complaining about connection being lost because the server crashed...

**Comment by kssenii** [comment]
> I'm going to try and test this in the next few days and see if I can correlate both things. I am also not entirely sure about this, to be honest... I was dropping the view, wanted to re-create it and the client was complaining about connection being lost because the server crashed...

Ok, thanks! I really want to fix this crash. I will also take more tries to reproduce it.

**Comment by kssenii** [comment]
This issue with truncating last character is solved by using `rabbitmq_row_delimiter = '\n'`, for second mentioned issue there is https://github.com/ClickHouse/ClickHouse/issues/29315. So will closed this one.
