### ISSUE TITLE
NAS zero copy replication

### ISSUE THREAD

**Issue by Alpha-su** [ClickHouse/ClickHouse#30730]
**Reasons for the proposal**
> I saw the new feature **'Separation of storage and compute'** in roadmap 2021 but it only support S3 and HDFS filesystem, i want to extend this so that it can support zero copy replication on **NAS**(Network Attached Storage). 
A NAS system is a storage device connected to a network that allows storage and retrieval of data from a centralized location for authorized network users and heterogeneous clients, it means that different users on different ECS(Elastic Container Service)  can access NAS just like local disk. But now on clickhouse, we still need to copy data though the data path is the same one using NAS.

**Use case**

> Different Clickhouse server have the same data path which is using NAS, so the data path can be accessed by different server. As NAS is infinitely scalable, we can add servers to improve computing performance.

**Describe the solution you'd like**

>Clickhouse cluster will synchronize two types of data: metadata in memory and part data on disk, if we have the same data path, we can only  synchronize metadata in cluster.

**Comment by alexey-milovidov** [comment]
It has a low chance of being implemented, as it is not in the roadmap.

**Comment by UnamedRus** [comment]
It seems, it could work with local object storage, as it allow to use zero copy replication? 

https://github.com/ClickHouse/ClickHouse/pull/48791

**Comment by UnamedRus** [comment]
PR https://github.com/ClickHouse/ClickHouse/pull/53629

**Comment by Alpha-su** [comment]
> PR #53629

I'm glad to see this feature implemented, thanks for your information!
