### ISSUE TITLE
change the table comment after created the table is not supported now?

### ISSUE THREAD

**Issue by zhzava** [ClickHouse/ClickHouse#30784]
Change the table comment after created the table is not supported now?
Like mysql : ALTER TABLE [tableName] COMMNET [comment]; 
The sql "ALTER TABLE `system`.tables UPDATE Comment='test' WHERE NAME='t1';" also not supported!!!
My version is '21.9.4.35'。

**Comment by findczk** [comment]
@ucasfl   hi, Ask you a question: support table comment when i create a table? My version is '21.2.3.15'. thank you!

**Comment by daveguest15** [comment]
- [x] @

**Comment by findczk** [comment]
> @ucasfl hi, Ask you a question: support table comment when i create a table? My version is '21.2.3.15'. thank you!

since 21.6 version
![image](https://user-images.githubusercontent.com/68439127/141091127-32405de3-576f-4201-aec9-0cf6270c0a67.png)
