### ISSUE TITLE
ubantu20编译clickhouse21.1 失败

### ISSUE THREAD

**Issue by fjl121029xx** [ClickHouse/ClickHouse#30787]
-- Using custom linker by name: gold
-- CMAKE_BUILD_TYPE: Debug
-- Using objcopy: /usr/bin/llvm-objcopy-11.
-- Disabling compiler -pipe option (have only 1095 mb of memory)
-- Default libraries: -nodefaultlibs -lgcc  -lc -lm -lrt -lpthread -ldl
-- Some symbols from glibc will be replaced for compatibility
-- Using libunwind: unwind
-- Using exception handler: unwind
-- Using libcxx: cxx
-- Using libcxxfs: 
-- Using libcxxabi: cxxabi
-- Unit tests are enabled
-- Building for: Linux-5.11.0-38-generic x86_64 x86_64-linux-gnu ;
    USE_STATIC_LIBRARIES=ON
    MAKE_STATIC_LIBRARIES=ON
    SPLIT_SHARED=
    UNBUNDLED=OFF
    CCACHE=CCACHE_FOUND-NOTFOUND 
-- Using double-conversion:  : double-conversion
-- Using ssl=1: /home/qiyue/ClickHouse/contrib/boringssl/include : ssl;crypto
-- Using ldap=1: /home/qiyue/ClickHouse/contrib/openldap-cmake/linux_x86_64/include;/home/qiyue/ClickHouse/contrib/openldap/include : ldap_r;lber
-- Using icu=1:  : icui18n;icuuc;icudata
-- Using zlib-ng: /home/qiyue/ClickHouse/contrib/zlib-ng;/home/qiyue/ClickHouse/build/contrib/zlib-ng : zlib
-- Using zstd: /home/qiyue/ClickHouse/contrib/zstd/lib : zstd
-- Using sparsehash: /home/qiyue/ClickHouse/contrib/sparsehash-c11
-- Using re2: /home/qiyue/ClickHouse/contrib/re2 : re2;  : re2_st
-- Using krb5=1: /home/qiyue/ClickHouse/contrib/krb5/src/include;/home/qiyue/ClickHouse/build/contrib/krb5-cmake/include : krb5
-- Using libgsasl=1: /home/qiyue/ClickHouse/contrib/libgsasl/src;/home/qiyue/ClickHouse/contrib/libgsasl/linux_x86_64/include : libgsasl
-- Using cyrus-sasl: krb5=1: /home/qiyue/ClickHouse/contrib/cyrus-sasl/include : sasl2
-- Using librdkafka=1: /home/qiyue/ClickHouse/contrib/librdkafka/src : rdkafka cppkafka
-- Using AMQP-CPP=1: /home/qiyue/ClickHouse/contrib/AMQP-CPP/include;/home/qiyue/ClickHouse/contrib/AMQP-CPP/include;/home/qiyue/ClickHouse/contrib/AMQP-CPP : AMQP-CPP
-- Using capnp=1: capnpc
-- LLVM include Directory: /home/qiyue/ClickHouse/contrib/llvm/llvm/include;/home/qiyue/ClickHouse/build/contrib/llvm/llvm/include
-- LLVM library Directory: /home/qiyue/ClickHouse/build/contrib/llvm/llvm
-- LLVM C++ compiler flags: 
-- Using h3=1: /home/qiyue/ClickHouse/contrib/h3/src/h3lib/include : h3
-- Using libxml2: /home/qiyue/ClickHouse/contrib/libxml2/include;/home/qiyue/ClickHouse/contrib/libxml2-cmake/linux_x86_64/include : libxml2
-- Using brotli=1: /home/qiyue/ClickHouse/contrib/brotli/c/include : brotli
-- Using protobuf=1: /home/qiyue/ClickHouse/contrib/protobuf/src : libprotobuf : $<TARGET_FILE:protoc> : libprotoc
-- Using gRPC=1: /home/qiyue/ClickHouse/contrib/grpc/include : grpc;grpc++ : $<TARGET_FILE:grpc_cpp_plugin>
-- Using pdqsort: /home/qiyue/ClickHouse/contrib/pdqsort
-- Using miniselect: /home/qiyue/ClickHouse/contrib/miniselect/include
-- Using hdfs3=1: /home/qiyue/ClickHouse/contrib/libhdfs3/include : hdfs3
-- Using curl: /home/qiyue/ClickHouse/contrib/curl/include : curl
-- Using aws_s3=1: /home/qiyue/ClickHouse/contrib/aws/aws-cpp-sdk-s3/include : aws_s3
-- Using snappy: snappy
-- Using Parquet: arrow=arrow_static: ; parquet=parquet_static: ; thrift=thrift_static ; flatbuffers=flatbuffers
-- Using simdjson=ON
-- Using rapidjson=1: /home/qiyue/ClickHouse/contrib/rapidjson/include
-- Using fastops=1: /home/qiyue/ClickHouse/contrib/fastops/ : fastops
-- Using unixodbc
-- Using ROCKSDB=1: /home/qiyue/ClickHouse/contrib/rocksdb/include : rocksdb
-- Using NuRaft=1: /home/qiyue/ClickHouse/contrib/NuRaft/include : nuraft
-- Using snappy: snappy
-- Using internal=1 orc=1: /home/qiyue/ClickHouse/contrib/orc/c++/include : orc
-- Using snappy: snappy
-- Using avro=1: /home/qiyue/ClickHouse/contrib/avro/lang/c++/include : avrocpp
-- Using msgpack=1: /home/qiyue/ClickHouse/contrib/msgpack-c/include
-- Using cassandra=1: /home/qiyue/ClickHouse/contrib/cassandra/include/ : cassandra_static
-- Using libuv: /home/qiyue/ClickHouse/contrib/libuv : uv_a
-- Using sentry=ON: sentry
-- Using stats=1 : /home/qiyue/ClickHouse/contrib/stats/include
-- Using gcem=1: /home/qiyue/ClickHouse/contrib/gcem/include
-- Using cityhash:  : cityhash
-- Using farmhash:  : farmhash
-- Using gtest=1: /home/qiyue/ClickHouse/contrib/googletest/googletest : gtest_main;gtest : 
-- Using mysqlclient=1:  : mariadbclient; staticlib=
-- compiler C   = /usr/bin/cc  -fdiagnostics-color=always  -msse4.1 -msse4.2 -mpopcnt  -Wall  -Werror -g -O0 -g3 -ggdb3 -fno-inline 
-- compiler CXX = /usr/bin/c++  -fdiagnostics-color=always -std=gnu++2a -fsized-deallocation  -msse4.1 -msse4.2 -mpopcnt   -Wall  -Werror  -O0 -g3 -ggdb3 -fno-inline  -D_LIBCPP_DEBUG=0
-- LINKER_FLAGS =  -fuse-ld=gold -rdynamic -Wl,--no-undefined -Wl,-no-pie 
-- Packaging with tzdata version: 2020e
-- Using cctz
-- Using FastMemcpy
-- Using hyperscan
-- jemalloc malloc_conf: percpu_arena:percpu,oversize_threshold:0,muzzy_decay_ms:10000
-- Using jemalloc
-- Using cpuid
-- Using replxx
-- Using Poco::Crypto
-- Using Poco::Data::ODBC
-- ZSTD VERSION 1.4.0
-- Using CMake version 3.16.3
-- ZLIB_HEADER_VERSION: 1.2.11
-- ZLIBNG_HEADER_VERSION: 1.9.9
-- Arch detected: 'x86_64'
-- Basearch of 'x86_64' has been detected as: 'x86'
-- Architecture-specific source files: arch/x86/x86.c;arch/x86/insert_string_sse.c;arch/x86/deflate_quick.c;arch/x86/fill_window_sse.c;arch/x86/slide_sse.c;arch/x86/crc_folding.c
-- The following features have been enabled:

 * CMAKE_BUILD_TYPE, Build type: Debug (selected)
 * ZLIB_COMPAT, Provide a zlib-compatible API
 * WITH_OPTIM, Build with optimisation
 * WITH_NEW_STRATEGIES, Use new strategies
 * SSE42_CRC, Support CRC hash generation using the SSE4.2 instruction set, using "-msse4"
 * SSE42_DEFLATE_QUICK, Support SSE4.2-accelerated quick compression
 * PCLMUL_CRC, Support CRC hash generation using PCLMULQDQ, using "-mpclmul"

-- The following REQUIRED packages have been found:

 * Threads

-- The following features have been disabled:

 * WITH_GZFILEOP, Compile with support for gzFile-related functions
 * WITH_SANITIZERS, Build with address sanitizer and all supported sanitizers other than memory sanitizer
 * WITH_MSAN, Build with memory sanitizer
 * WITH_FUZZERS, Build test/fuzz
 * MAINTAINER, Build with maintainer warnings and tests enabled

-- librdkafka with SASL support
-- FLATBUFFERS_LIBRARY: flatbuffers
-- Native target architecture is X86
-- Threads enabled.
-- Doxygen disabled.
-- Go bindings disabled.
-- Ninja version: 1.10.0
-- Could NOT find OCaml (missing: OCAMLFIND OCAML_VERSION OCAML_STDLIB_PATH) 
-- Could NOT find OCaml (missing: OCAMLFIND OCAML_VERSION OCAML_STDLIB_PATH) 
-- OCaml bindings disabled.
-- LLVM host triple: x86_64-unknown-linux-gnu
-- LLVM default target triple: x86_64-unknown-linux-gnu
-- Constructing LLVMBuild project information
-- Linker detection: GNU Gold
-- LLVMHello ignored -- Loadable modules not supported on this platform.
-- Targeting X86
-- Targeting AArch64
-- 
-- 3.13.0.0
-- checking compiler: GCC (9.3.)
-- Checking whether strerror_r returns an int
-- Checking whether strerror_r returns an int -- no
-- No CMAKE_CXX_STANDARD set, assuming 11
CMake Error at contrib/grpc/cmake/cares.cmake:25 (add_subdirectory):
  The source directory

    /home/qiyue/ClickHouse/contrib/grpc/third_party/cares/cares

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  contrib/grpc/CMakeLists.txt:253 (include)

-- PROJECT version: 2.11.0
-- libuv version: v1.34.1
-- OpenSSL version: v
-- Using std::atomic implementation for atomic operations
-- Using hash header <functional> and namespace "std"
-- SENTRY_TRANSPORT=curl
-- SENTRY_BACKEND=none
-- GCE-Math version 1.13.0
-- /home/qiyue/ClickHouse/src: Have 1061 megabytes of memory.
        Limiting concurrent linkers jobs to 1 and compiler jobs to 1
-- Will build ClickHouse 21.1.10.1 revision 54445 
CMake Warning at src/Functions/CMakeLists.txt:52 (message):
  Not generating debugger info for ClickHouse functions

-- ClickHouse modes:
-- Server mode: ON
-- Client mode: ON
-- Local mode: ON
-- Benchmark mode: ON
-- Extract from config mode: ON
-- Compressor mode: ON
-- Copier mode: ON
-- Format mode: ON
-- Obfuscator mode: ON
-- ODBC bridge mode: ON
-- ClickHouse install: ON
-- ClickHouse git-import: ON
-- Target check already exists
-- /home/qiyue/ClickHouse/utils: Have 1052 megabytes of memory.
        Limiting concurrent linkers jobs to 1 and compiler jobs to OFF
-- Configuring incomplete, errors occurred!
See also "/home/qiyue/ClickHouse/build/CMakeFiles/CMakeOutput.log".
See also "/home/qiyue/ClickHouse/build/CMakeFiles/CMakeError.log".

**Comment by filimonov** [comment]
do recursive submodule update.

**Comment by alexey-milovidov** [comment]
New ClickHouse versions, starting from 21.11 don't require recursive submodules anymore.
