### ISSUE TITLE
Изменилось поведение оконных функций, перестало совпадать с MS SQL

### ISSUE THREAD

**Issue by vdimir** [ClickHouse/ClickHouse#30794]
https://github.com/ClickHouse/ClickHouse/pull/30791#issue-1038274472Ка
_authored by @az1s_

Изменилось поведение оконных функций. Расчет хэш-суммы документов за дату в версии КХ 21.8.8.29 возвращает хэш-сумму, совпадающую с аналогичным расчетом в MS SQL (с использованием оконной функции LAG).
Расчет хэш-сумм с использованием neighbor и lagInFrame в 21.8.8.29  возвращает на наборе данных одинаковую хэш-сумму, как в MS SQL.

В версиях 21.10.1.8013 и 21.10.2.15 хэш-сумма уже другая и не совпадает с расчетом в MS SQL.

Для расчета хэш-сумм в КХ использовался один и тот же запрос, сравнение выполнялось для рабочего сервера  с 
с версией 21.8.8.29 с тестовым, на котором производилась переустановка версий КХ

![изображение](https://user-images.githubusercontent.com/58112035/139224529-f198bc93-ce00-42a6-83b1-63f3d720476d.png)

Текст запроса для расчета хэш-сумм документов за дату в КХ:

![изображение](https://user-images.githubusercontent.com/58112035/139224820-7fd0a86b-4f42-41ac-8f31-cff66a1e446f.png)

**Comment by az1s** [comment]
Нашел причину. Изменилось поведение функции concat, в результате хэш-сумма в КХ отличается от вычисленной по аналогичному алгоритму в MS SQL.
![изображение](https://user-images.githubusercontent.com/58112035/139597200-b4272dfe-d6ae-46ea-b190-da306ed842e3.png)

![изображение](https://user-images.githubusercontent.com/58112035/139597211-ded04d1a-ef8e-4d0c-893f-bf6051148a6c.png)

Текст запроса для проверки функции concat:

CREATE TABLE <temp>tst 
(
  x1 Decimal64(2),
  x2 Decimal64(2),
  x3 Decimal64(2),
  x4 Decimal64(2)
)
ENGINE=Memory
;
INSERT INTO <temp>tst 
SELECT
  13.12,2,0.33,39
;
SELECT
  version(),
  x1,x2,x3,x4,
  concat(toString(x1),toString(x2),toString(x3),toString(x4))
FROM
   <temp>tst 
FORMAT  PrettyCompactNoEscapes

**Comment by alexey-milovidov** [comment]
From changelog:

> Backward Incompatible Change

>    Do not output trailing zeros in text representation of Decimal types. Example: 1.23 will be printed instead of 1.230000 for decimal with scale 6. This closes #15794. It may introduce slight incompatibility if your applications somehow relied on the trailing zeros. Serialization in output formats can be controlled with the setting output_format_decimal_trailing_zeros. Implementation of toString and casting to String is changed unconditionally. #27680 (alexey-milovidov).

**Comment by az1s** [comment]
Спасибо за ответ.  К сожалению, настройка output_format_decimal_trailing_zeros не помогла

![изображение](https://user-images.githubusercontent.com/58112035/139598483-cd8fa36f-0c66-4c7b-845e-7619040d5213.png)

**Comment by den-crane** [comment]
https://github.com/ClickHouse/ClickHouse/issues/30934
