### ISSUE TITLE
Questions about clickhouse-copier

### ISSUE THREAD

**Issue by amralaa-MSFT** [ClickHouse/ClickHouse#30804]
We would like to use clickhouse-copier tool to copy data between clusters as part of a production workflow. I appreciate if you can answer the following questions:
1. Would clickhouse-copier ever drop partitions or remove data from destination table? If so, how to guarantee this wouldn’t occur? It's mentioned in the documentation page that skipping `<enabled_partitions>` config can cause deletion of destination partitions:
> This section specifies partitions that should be copied, other partition will be ignored. … Since partition key of source and destination cluster could be different, these partition names specify destination partitions.
>
> NOTE: In spite of this section is optional (if it is not specified, all partitions will be copied), it is strictly recommended to specify them explicitly.
>
> If you already have some ready partitions on destination cluster they will be removed at the start of the copying since they will be interpeted as unfinished data from the previous copying!!!
2. What kind of inconsistencies are expected if source table changes? In case of insertion into source table, is it guaranteed that all rows already existing before starting copying process will be copied? Could insertion of new rows into destination table during the process lead to any inconsistencies?
3. How to make sure that copying process completed successfully (i.e. all rows are copied to destination table and helper tables are cleaned up)? In some cases `ALTER TABLE ... ATTACH PARTITION ... FROM *_piece_* ...` and `DROP TABLE ... *_piece_*` fail because of `max_partition_size_to_drop` limitation.

**Comment by amralaa-MSFT** [comment]
HI @den-crane. Can you help us get answers to these questions? Thanks in advance.

**Comment by amralaa-MSFT** [comment]
A kind reminder @den-crane @nikitamikhaylov

**Comment by SaltTan** [comment]
> 1. Would clickhouse-copier ever drop partitions or remove data from destination table? If so, how to guarantee this wouldn’t occur? It's mentioned in the documentation page that skipping `<enabled_partitions>` config can cause deletion of destination partitions:
> 
> > This section specifies partitions that should be copied, other partition will be ignored. … Since partition key of source and destination cluster could be different, these partition names specify destination partitions.
> > NOTE: In spite of this section is optional (if it is not specified, all partitions will be copied), it is strictly recommended to specify them explicitly.
> > If you already have some ready partitions on destination cluster they will be removed at the start of the copying since they will be interpeted as unfinished data from the previous copying!!!
> 

This is true for clickhouse-copier 20.3 and earlier.
Since 20.4 clickhouse-copier does not drop partitions in destination tables.

> 2. What kind of inconsistencies are expected if source table changes? In case of insertion into source table, is it guaranteed that all rows already existing before starting copying process will be copied? Could insertion of new rows into destination table during the process lead to any inconsistencies?

clcikhouse-copier simply runs INSERT INTO ... SELECT FROM queries.
If you continue to modify data in source or destination tables, all kinds of inconsistencies are expected.

**Comment by SaltTan** [comment]
> Since 20.4 clickhouse-copier does not drop partitions in destination tables.

Correction: since 21.7 there is a flag to drop partitions in destination tables (`allow_to_drop_target_partitions`)
