### ISSUE TITLE
alter to convert table from the OLD syntax to the NEW syntax (using mutation)

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#30821]
```
create table source( D Date, A Int64, S String) Engine=MergeTree (D, A, 8192);
insert into source values ( '2020-01-01', 1, '');
create table target( D Date, A Int64, S String) Engine=MergeTree partition by toYYYYMM(D) order by A;
```

need to implement

`alter table target attach old_partition '2020-01-01'  from source`

**Comment by den-crane** [comment]
@arthurpassos

**Comment by alexey-milovidov** [comment]
Since 2021, there is less number of tables with the old syntax, so the issue is less relevant.

**Comment by torlix** [comment]
we have lots of old format data, insert into from source table would spends lots of time, and cause the data not correctly.
