### ISSUE TITLE
Mongo connect timeout

### ISSUE THREAD

**Issue by huyhandes** [ClickHouse/ClickHouse#30836]
After I created successfully, the result return an timeout error (I used MongoDB engine)
[2021-10-29 15:17:28] Poco::Exception. Code: 1000, e.code() = 0, Timeout: connect timed out: 10.10.20.39:27017 (version 21.9.5.16 (official build))
Tested with 21.10.2.15 also.

**Comment by Hayaking** [comment]
![image](https://user-images.githubusercontent.com/10249842/139481430-f9f96f34-df09-411d-a15d-4b9f8b95cb46.png)
It looks like the code has been modified and can only be connected using SSL

**Comment by huyhandes** [comment]
Which version the code has been changed with force ssl? So I can roll back before that.

**Comment by Hayaking** [comment]
> Which version the code has been changed with force ssl? So I can roll back before that.

v21.8.10.19 is not ssl

**Comment by Junnplus** [comment]
@huyhandes @Hayaking ssl is optional.

**Comment by Junnplus** [comment]
@huyhandes You can try `ENGINE = MongoDB('localhost:27017', 'test', 'users', 'admin', 'admin', 'connectTimeoutMS=100000&connectTimeoutMS=1000000')` in create table.

**Comment by BurningLutz** [comment]
> @huyhandes You can try `ENGINE = MongoDB('localhost:27017', 'test', 'users', 'admin', 'admin', 'connectTimeoutMS=100000')` in create table.

This really helps! I struggled for a whole day to find a solution.
