### ISSUE TITLE
Is there any possibility the number of  consumers in kafka engine can exceed 16? And why the limit is setting to 16?

### ISSUE THREAD

**Issue by mo-avatar** [ClickHouse/ClickHouse#30875]
When We try to test Kafka Engine, we find such kind of exception
```
        if (num_consumers > 16)
        {
            throw Exception("Number of consumers can not be bigger than 16", ErrorCodes::BAD_ARGUMENTS);
        }
```

As we enlarge the consumers we find the consume rate increase , so why this limit is setting to 16? On what kind of machine  we find this experience value?  If we had better machines can we enlarge it some how ?
Thanks

**Comment by genzgd** [comment]
This was updated in https://github.com/ClickHouse/ClickHouse/pull/26642 to limit the number of consumers to the number of physical cores.  This change is available in recent versions.  Will that update meet your needs?

I don't know why the original was set to 16, although some limits may be desirable to prevent excessive resource consumption in ClickHouse, as each consumer requires additional buffering and any Materialized Views attached to the Kafka table also required additional overhead for each consuming stream.  There is additional discussion in the referenced PR.  Theoretically the number of consumers doesn't even need to be limited by physical cores, as Kafka consumer threads may often be waiting for network I/O, but that limit should be more than enough for most real world use cases.
