### ISSUE TITLE
Distributed table data duplication

### ISSUE THREAD

**Issue by aopetrov86** [ClickHouse/ClickHouse#30878]
### Environment
Clickhouse server version 21.8.9.13
Circular cluster analytics_cluster:
<details><summary>remote_servers.xml</summary>
<p>

```xml
<remote_servers>
    <analytics_cluster>
        <shard>
            <internal_replication>true</internal_replication>
            <replica>
                <default_database>default</default_database>
                <priority>1</priority>
                <host>ch1</host>
                <port>9000</port>
            </replica>
            <replica>
                <default_database>replica</default_database>
                <priority>2</priority>
                <host>ch2</host>
                <port>9000</port>
            </replica>
        </shard>
        <shard>
            <internal_replication>true</internal_replication>
            <replica>
                <default_database>default</default_database>
                <priority>1</priority>
                <host>ch2</host>
                <port>9000</port>
            </replica>
            <replica>
                <default_database>replica</default_database>
                <priority>2</priority>
                <host>ch3</host>
                <port>9000</port>
            </replica>
        </shard>
        <shard>
            <internal_replication>true</internal_replication>
            <replica>
                <default_database>default</default_database>
                <priority>1</priority>
                <host>ch3</host>
                <port>9000</port>
            </replica>
            <replica>
                <default_database>replica</default_database>
                <priority>2</priority>
                <host>ch1</host>
                <port>9000</port>
            </replica>
        </shard>
    </analytics_cluster>
</remote_servers>
```
</p>
</details>

<details><summary>prepare.sql</summary>
<p>

```sql
drop table if exists default.test_distr_table ON CLUSTER analytics_cluster SYNC;
drop table if exists default.test_local_table ON CLUSTER analytics_cluster SYNC;

create table default.test_local_table ON CLUSTER analytics_cluster
(
	app_id String,
	id String,
	dt DateTime,
	ver DateTime default now()
)
engine = MergeTree()
PARTITION BY toYYYYMM(dt)
ORDER BY (dt, app_id, id)
SETTINGS index_granularity = 8192;

create table default.test_distr_table ON CLUSTER analytics_cluster
(
	app_id String,
	id String,
	dt DateTime,
	ver DateTime default now()
)
engine = Distributed('analytics_cluster', 'default', 'test_local_table', cityHash64(dt, app_id, id));

insert into test_distr_table(id, app_id, dt)
select
       toString(number) as id,
       toString(number % 2) as app_id,
       toDateTime('2021-10-30 00:00:00') as dt
from numbers(6);

system flush DISTRIBUTED default.test_distr_table;
```

</p>
</details>

### Initial data in *distributed table*
```sql
select id, app_id, dt, _shard_num, getMacro('shard') as host, cityHash64(dt, app_id, id) % 3 as shard_key, ver, _part
from default.test_distr_table
order by id;
```

| id | app\_id | dt | \_shard\_num | host | shard\_key | ver | \_part |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 0 | 0 | 2021-10-29 17:00:00 | 3 | 03 | 2 | 2021-10-30 09:35:37 | 202110\_5\_5\_0 |
| 1 | 1 | 2021-10-29 17:00:00 | 3 | 03 | 2 | 2021-10-30 09:35:37 | 202110\_5\_5\_0 |
| 2 | 0 | 2021-10-29 17:00:00 | 2 | 02 | 1 | 2021-10-30 09:35:37 | 202110\_8\_8\_0 |
| 3 | 1 | 2021-10-29 17:00:00 | 3 | 03 | 2 | 2021-10-30 09:35:37 | 202110\_5\_5\_0 |
| 4 | 0 | 2021-10-29 17:00:00 | 2 | 02 | 1 | 2021-10-30 09:35:37 | 202110\_8\_8\_0 |
| 5 | 1 | 2021-10-29 17:00:00 | 1 | 01 | 0 | 2021-10-30 09:35:37 | 202110\_11\_11\_0 |

### Initial data in local table on *ch1*
```sql
select id, app_id, dt, _shard_num, getMacro('shard') as host, cityHash64(dt, app_id, id) % 3 as shard_key, ver, _part
from remote('ch1:9000', default, test_local_table)
order by id;

```
| id | app\_id | dt | \_shard\_num | host | shard\_key | ver | \_part |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 5 | 1 | 2021-10-29 17:00:00 | 1 | 01 | 0 | 2021-10-30 09:35:37 | 202110\_11\_11\_0 |

### Initial data in local table on *ch2*
```sql
select id, app_id, dt, _shard_num, getMacro('shard') as host, cityHash64(dt, app_id, id) % 3 as shard_key, ver, _part
from remote('ch2:9000', default, test_local_table)
order by id;
```
| id | app\_id | dt | \_shard\_num | host | shard\_key | ver | \_part |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 2 | 0 | 2021-10-29 17:00:00 | 1 | 02 | 1 | 2021-10-30 09:35:37 | 202110\_8\_8\_0 |
| 4 | 0 | 2021-10-29 17:00:00 | 1 | 02 | 1 | 2021-10-30 09:35:37 | 202110\_8\_8\_0 |

### Initial data in local table on *ch3*
```sql
select id,app_id,dt,_shard_num,getMacro('shard') as host,cityHash64(dt, app_id, id) % 3 as shard_key,ver,_part
from remote('ch3:9000', default, test_local_table)
order by id;
```
| id | app\_id | dt | \_shard\_num | host | shard\_key | ver | \_part |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 0 | 0 | 2021-10-29 17:00:00 | 1 | 03 | 2 | 2021-10-30 09:35:37 | 202110\_5\_5\_0 |
| 1 | 1 | 2021-10-29 17:00:00 | 1 | 03 | 2 | 2021-10-30 09:35:37 | 202110\_5\_5\_0 |
| 3 | 1 | 2021-10-29 17:00:00 | 1 | 03 | 2 | 2021-10-30 09:35:37 | 202110\_5\_5\_0 |

### *ch3* goes down
```bash
docker-compose stop ch3
```
### rows from *ch3* goes down too:
| id | app\_id | dt | \_shard\_num | host | shard\_key | ver | \_part |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 2 | 0 | 2021-10-29 17:00:00 | 2 | 02 | 1 | 2021-10-30 09:35:37 | 202110\_8\_8\_0 |
| 4 | 0 | 2021-10-29 17:00:00 | 2 | 02 | 1 | 2021-10-30 09:35:37 | 202110\_8\_8\_0 |
| 5 | 1 | 2021-10-29 17:00:00 | 1 | 01 | 0 | 2021-10-30 09:35:37 | 202110\_11\_11\_0 |
| 5 | 1 | 2021-10-29 17:00:00 | 3 | 01 | 0 | 2021-10-30 09:35:37 | 202110\_11\_11\_0 |

### Insert some data into distributed table
```sql
insert into test_distr_table(id, app_id, dt)
select
       toString(number) as id,
       toString(number % 2) as app_id,
       toDateTime('2021-10-30 00:00:00') as dt
from numbers(6);

system flush DISTRIBUTED default.test_distr_table;
```
### Data in *distributed table* after *ch3* goes down and insert:
| id | app\_id | dt | \_shard\_num | host | shard\_key | ver | \_part |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 0 | 0 | 2021-10-29 17:00:00 | 1 | 01 | 2 | 2021-10-30 09:37:18 | 202110\_13\_13\_0 |
| 0 | 0 | 2021-10-29 17:00:00 | 3 | 01 | 2 | 2021-10-30 09:37:18 | 202110\_13\_13\_0 |
| 1 | 1 | 2021-10-29 17:00:00 | 1 | 01 | 2 | 2021-10-30 09:37:18 | 202110\_13\_13\_0 |
| 1 | 1 | 2021-10-29 17:00:00 | 3 | 01 | 2 | 2021-10-30 09:37:18 | 202110\_13\_13\_0 |
| 2 | 0 | 2021-10-29 17:00:00 | 2 | 02 | 1 | 2021-10-30 09:37:18 | 202110\_9\_9\_0 |
| 2 | 0 | 2021-10-29 17:00:00 | 2 | 02 | 1 | 2021-10-30 09:35:37 | 202110\_8\_8\_0 |
| 3 | 1 | 2021-10-29 17:00:00 | 1 | 01 | 2 | 2021-10-30 09:37:18 | 202110\_13\_13\_0 |
| 3 | 1 | 2021-10-29 17:00:00 | 3 | 01 | 2 | 2021-10-30 09:37:18 | 202110\_13\_13\_0 |
| 4 | 0 | 2021-10-29 17:00:00 | 2 | 02 | 1 | 2021-10-30 09:37:18 | 202110\_9\_9\_0 |
| 4 | 0 | 2021-10-29 17:00:00 | 2 | 02 | 1 | 2021-10-30 09:35:37 | 202110\_8\_8\_0 |
| 5 | 1 | 2021-10-29 17:00:00 | 1 | 01 | 0 | 2021-10-30 09:37:18 | 202110\_12\_12\_0 |
| 5 | 1 | 2021-10-29 17:00:00 | 1 | 01 | 0 | 2021-10-30 09:35:37 | 202110\_11\_11\_0 |
| 5 | 1 | 2021-10-29 17:00:00 | 3 | 01 | 0 | 2021-10-30 09:37:18 | 202110\_12\_12\_0 |
| 5 | 1 | 2021-10-29 17:00:00 | 3 | 01 | 0 | 2021-10-30 09:35:37 | 202110\_11\_11\_0 |

### Data in *ch1* after *ch3* goes down and insert:
| id | app\_id | dt | \_shard\_num | host | shard\_key | ver | \_part |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 0 | 0 | 2021-10-29 17:00:00 | 1 | 01 | 2 | 2021-10-30 09:37:18 | 202110\_13\_13\_0 |
| 1 | 1 | 2021-10-29 17:00:00 | 1 | 01 | 2 | 2021-10-30 09:37:18 | 202110\_13\_13\_0 |
| 3 | 1 | 2021-10-29 17:00:00 | 1 | 01 | 2 | 2021-10-30 09:37:18 | 202110\_13\_13\_0 |
| 5 | 1 | 2021-10-29 17:00:00 | 1 | 01 | 0 | 2021-10-30 09:37:18 | 202110\_12\_12\_0 |
| 5 | 1 | 2021-10-29 17:00:00 | 1 | 01 | 0 | 2021-10-30 09:35:37 | 202110\_11\_11\_0 |

### Data in *ch2* after *ch3* goes down and insert:
| id | app\_id | dt | \_shard\_num | host | shard\_key | ver | \_part |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 2 | 0 | 2021-10-29 17:00:00 | 1 | 02 | 1 | 2021-10-30 09:37:18 | 202110\_9\_9\_0 |
| 2 | 0 | 2021-10-29 17:00:00 | 1 | 02 | 1 | 2021-10-30 09:35:37 | 202110\_8\_8\_0 |
| 4 | 0 | 2021-10-29 17:00:00 | 1 | 02 | 1 | 2021-10-30 09:37:18 | 202110\_9\_9\_0 |
| 4 | 0 | 2021-10-29 17:00:00 | 1 | 02 | 1 | 2021-10-30 09:35:37 | 202110\_8\_8\_0 |

### Unexpected behavior
Row with id == 5 duplicated twice, rows with id in (0,1,3) duplicated.

### Expected behavior
Row with id == 5 duplicated, rows with id in (0,1,3) not duplicated, remain rows duplicated.

**Comment by aopetrov86** [comment]
in the next episode:
### *ch3* goes up
```bash
docker-compose start ch3
```
### Data in *distributed table* after *ch3* goes down, insert and *ch3* goes up:
| id | app\_id | dt | \_shard\_num | host | shard\_key | ver | \_part |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 0 | 0 | 2021-10-29 17:00:00 | 1 | 01 | 2 | 2021-10-30 09:37:18 | 202110\_13\_13\_0 |
| 0 | 0 | 2021-10-29 17:00:00 | 3 | 03 | 2 | 2021-10-30 09:35:37 | 202110\_5\_5\_0 |
| 1 | 1 | 2021-10-29 17:00:00 | 1 | 01 | 2 | 2021-10-30 09:37:18 | 202110\_13\_13\_0 |
| 1 | 1 | 2021-10-29 17:00:00 | 3 | 03 | 2 | 2021-10-30 09:35:37 | 202110\_5\_5\_0 |
| 2 | 0 | 2021-10-29 17:00:00 | 2 | 02 | 1 | 2021-10-30 09:37:18 | 202110\_9\_9\_0 |
| 2 | 0 | 2021-10-29 17:00:00 | 2 | 02 | 1 | 2021-10-30 09:35:37 | 202110\_8\_8\_0 |
| 3 | 1 | 2021-10-29 17:00:00 | 1 | 01 | 2 | 2021-10-30 09:37:18 | 202110\_13\_13\_0 |
| 3 | 1 | 2021-10-29 17:00:00 | 3 | 03 | 2 | 2021-10-30 09:35:37 | 202110\_5\_5\_0 |
| 4 | 0 | 2021-10-29 17:00:00 | 2 | 02 | 1 | 2021-10-30 09:37:18 | 202110\_9\_9\_0 |
| 4 | 0 | 2021-10-29 17:00:00 | 2 | 02 | 1 | 2021-10-30 09:35:37 | 202110\_8\_8\_0 |
| 5 | 1 | 2021-10-29 17:00:00 | 1 | 01 | 0 | 2021-10-30 09:35:37 | 202110\_11\_11\_0 |
| 5 | 1 | 2021-10-29 17:00:00 | 1 | 01 | 0 | 2021-10-30 09:37:18 | 202110\_12\_12\_0 |

rows with id in (0,1,3) still duplicated

**Comment by den-crane** [comment]
1. You use Not Replicated tables. No any guarantees. No real replication.
2. You use `engine = MergeTree()` `<internal_replication>true</internal_replication>`  internal_replication MUST be false in case of not-Replicated engines.
3. Insert deduplication is disabled for not-Replicated tables by default. Distributed table insert data twice into turned-off node. non_replicated_deduplication_window https://clickhouse.com/docs/en/operations/settings/merge-tree-settings/#non-replicated-deduplication-window

>rows with id in (0,1,3) still duplicated
I'm not sure I understand you right. But Clickhouse does not have real protection against duplicates. So if you insert something multiple times you get duplicates. No surprises here.

**Comment by aopetrov86** [comment]
> 1. You use Not Replicated tables. == No any guarantees. No real replication.

I try to distribute new data in cluster by sharding key without replication and replace updated partitions in replicated table after that.

> 2. You use engine = MergeTree() & <internal_replication>true</internal_replication>. internal_replication MUST be false in case of not-Replicated engines.

In case of not-Replicated engine i need define a copy of my cluster with internal_replication == false?

> 3. Insert deduplication is disabled for not-Replicated tables by default. Distributed table inserts data twice into turned-off node. non_replicated_deduplication_window https://clickhouse.com/docs/en/operations/settings/merge-tree-settings/#non-replicated-deduplication-window

I don't need insert deduplication, but duplication degree in distributed table wrong. Distributed table inserts data into node ch1 while ch3 down(see **Data in ch1 after ch3 goes down and insert**).

> I'm not sure I understand you. Clickhouse does not have real protection against duplicates. So if you insert something multiple times you get duplicates. No surprises here.

My bad. First part rows from ch1(created with second insert during ch3 downtime) second part from started ch3.

**Comment by den-crane** [comment]
Read documentation about internal_replication https://clickhouse.com/docs/en/engines/table-engines/special/distributed/

>I don't need insert deduplication

You need insert deduplication if you insert into Distributed table, trust me. Distributed table will insert into underlying tables **many** times until success.

**Comment by aopetrov86** [comment]
Keys [2, 4, 5, 5] in distributed table after ch3 goes down is wrong. Really present keys is [2, 4, 5] (2,4 from ch2 and 5 from ch1)

After ch3 goes down and insert [0, 1, 2, 3, 4, 5] keys [0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 5, 5] in distributed table is wrong. Really present keys is [0, 1, 2, 2, 3, 4, 5, 5] (0,1,3,5,5 from ch1 and 2,2,4,4 from ch2).

**Comment by den-crane** [comment]
ну вообще бессмысленно разбираться что получилось при `MergeTree() & <internal_replication>true`
это тупо неправильная комбинация, которая генерит тупо мусор в результатах.

**Comment by aopetrov86** [comment]
Фух, а чё по русски тоже можно было? 
Отключил internal_replication, теперь дубли во всех таблицах сразу после первого инсёрта. При этом данные распределены по кластеру вообще хаотично. Подозреваю что при наличии циклического кластера тк и должно быть. 
Похоже в моём случае internal_replication==false таки даёт мусор в результатах.

**Comment by aopetrov86** [comment]
Я вот чё не могу понять. Разница в уже вставленных данных на узлах и в дитрибьютед таблице это не баг?

**Comment by den-crane** [comment]
>циклического кластера

aaaa, все ясно. Нет, я такое не сапорчу, циклического кластера в топку.

**Comment by aopetrov86** [comment]
@den-crane, а на трёх серверах как-то можно получить тот же результат без циклического кластера? Только добавлением ещё одной реплики? Надо перестать жадничать и наступит счастье?

**Comment by den-crane** [comment]
I removed "potential bug" label, because circle replication is not supported.

**Comment by den-crane** [comment]
циклический кластер бессмысленная трудноотлаживаемая херня, которая создает головную боль и не добавляет ничего. Кластер из двух реплик в 99% случаев быстрее чем циклический кластер из 3 серверов.

**Comment by aopetrov86** [comment]
Т.е. лучше выбирать из таких вариантов?
Сэкономить:
|                    ch1 |             ch2        |
|----------------------|-----------------------|
|shard1, replica1 | shard2, replica1 |
|shard2, replica2 | shard1, replica2 |

Ещё немного потратиться на диски:
|                    ch1 |             ch2        |             ch3         |
|----------------------|-----------------------|-----------------------|
|shard1, replica1 | shard2, replica1 | shard3, replica1 |
|shard2, replica2 | shard3, replica2 | shard1, replica2 |
|shard3, replica3 | shard1, replica3 | shard2, replica3 |

При этом гарантия отказоустойчивости при смерти одного из узлов одинаковая у обоих вариантов, но второй позволяет обрабатывать большие объёмы т.к. параллелить запросы можно на три узла.

Я всё правильно понял?

**Comment by den-crane** [comment]
Нет, неправильно. 
Есть только одна конфигурация, один сервер = один шард.

ch1 | ch2
-- | --
shard1, replica1 
shard1, replica2
<p></p>

либо делайте виртуальные машины, нарезайте 2 виртуаки на каждой железке и дальше развлекайтесь разделением ресурсов между ними как хотите. Главное чтобы в remote servers никаких default_database.
