### ISSUE TITLE
`REGEXP_MATCHES` and `REGEXP_REPLACE` function aliases for compatibility with PostgreSQL.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#30885]
**Use case**

Some people get used to PostgreSQL. Some tools also.

**Describe the solution you'd like**

Simply add the corresponding aliases. These aliases should be case insensitive.

**Comment by taiyang-li** [comment]
I'd like take this issue up.

**Comment by alexey-milovidov** [comment]
Thank you, let's do it!

**Comment by taiyang-li** [comment]
PR: https://github.com/ClickHouse/ClickHouse/pull/34334
