### ISSUE TITLE
INTO OUTFILE / FROM INFILE: autodetect FORMAT by file extension

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#30918]
**Use case**

This works:

```
SELECT * FROM hits_100m_obfuscated INTO OUTFILE 'hits.csv' FORMAT CSV
```

But I want this:

```
SELECT * FROM hits_100m_obfuscated INTO OUTFILE 'hits.csv'
```

**Describe the solution you'd like**

Every format can register file extension(s) in format factory.
If format is not specified explicitly, we can detect it automatically by file extension.
It should work for compressed files `hits.csv.gz` as well.

The following extensions should be supported at least:
csv, tsv, parquet, orc, native, json, ndjson, xml, md, avro

**Addition details**

Let's also support omitting the format argument for `file`, `url`, `s3`, `hdfs` table functions.

**Comment by cccgp** [comment]
I want wo try it! @alexey-milovidov

**Comment by cccgp** [comment]
I want to try it! @alexey-milovidov

**Comment by alexey-milovidov** [comment]
Thank you! Let's do it.

**Comment by cccgp** [comment]
Hi, I have tried for some days, but I still haven’t found a clear solution. I have read a lot of details of parsing. I think I’m lost in the details of parse. Reading widely does not help to solve this problem. Can you give me some hints? Which files should I focus on, and even introduce some related articles about clickhouse parse.I think this will make me more motivated to solve the problem. Thanks! @alexey-milovidov

**Comment by alexey-milovidov** [comment]
FormatFactory.h/cpp - add a method to get the format name from file extension. Like
`String getFormatFromFileExtension(const String & extension)`
It will return empty string if file extension is unrecognized.

Allow to register file extensions like
`void registerFileExtension(const String & extension, const String & format_name)`

Various formats can register file extensions for theirself.

**Comment by alexey-milovidov** [comment]
Then find places where FORMAT from query is interpreted.
Somewhere around Client.cpp or ClientBase.cpp, HTTPHandler.cpp, executeQuery.cpp

**Comment by alexey-milovidov** [comment]
If there is no FORMAT but there is FROM INFILE / INTO OUTFILE, parse file name (after extracting optional compression method).

**Comment by alexey-milovidov** [comment]
@cccgp How is it?

**Comment by cccgp** [comment]
> @cccgp How is it?

Sorry, I'm busy with work
