### ISSUE TITLE
FORMAT `LineAsString` should be suitable for output

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#30919]
**Use case**

For symmetry reasons, because it is already supported for input.

**Describe the solution you'd like**

The same as `TSVRaw`.

**Comment by xudong963** [comment]
New to CK, I want to try it! @alexey-milovidov

**Comment by alexey-milovidov** [comment]
Thank you!

**Comment by alexey-milovidov** [comment]
@xudong963 Did you have time to look? Do you need help locating the relevant parts in the codebase?

**Comment by xudong963** [comment]
@alexey-milovidov Sorry, I've been so busy with some things at work that I may not have time to do it.
