### ISSUE TITLE
ClickHouse FedRamp support

### ISSUE THREAD

**Issue by abhilash-radhakrishnaru** [ClickHouse/ClickHouse#30944]
I could not find any FedRamp related documentation for ClickHouse. Is it FedRamp certified to be used in a cloud solution? Any security hardening guidelines available?

**Comment by chanj** [comment]
FedRAMP applies to cloud service offerings and as such is not directly relevant to the standalone ClickHouse OSS offering. We don't currently have a security hardening guideline available (other than standard documentation on ClickHouse security features), but that is a good suggestion for potential future development.
