### ISSUE TITLE
two questions: 1、Which lts version is supported to projection?  2、 Timeout to modify a large table field like(Session expired)

### ISSUE THREAD

**Issue by Sallery-X** [ClickHouse/ClickHouse#30953]

**Comment by den-crane** [comment]
1. https://github.com/ClickHouse/ClickHouse/blob/master/CHANGELOG.md
  ClickHouse release 21.6, 2021-06-05
  Experimental Feature
     Add PROJECTION support for MergeTree* tables. #20202 (Amos Bird).

2. I don't understand the question. You should clarify and show copy/paste of the query and the error.

**Comment by Sallery-X** [comment]
> 1. https://github.com/ClickHouse/ClickHouse/blob/master/CHANGELOG.md
>    ClickHouse release 21.6, 2021-06-05
>    Experimental Feature
>    Add PROJECTION support for MergeTree* tables. [Projections #20202](https://github.com/ClickHouse/ClickHouse/pull/20202) (Amos Bird).
> 2. I don't understand the question. You should clarify and show copy/paste of the query and the error.

the sql: alter table touchstone_hourly_local on cluster default modify column pos_package_id Int64;


Received exception from server (version 21.3.5):
Code: 999. DB::Exception: Received from host:9000. DB::Exception: Session expired (Session expired).

**Comment by alexey-milovidov** [comment]
Projections are still experimental, even in version 21.11.
The progress of "graduating" this feature is here: https://github.com/ClickHouse/ClickHouse/pull/30144
