### ISSUE TITLE
Question: Which primary key is efficient?

### ISSUE THREAD

**Issue by fizerkhan** [ClickHouse/ClickHouse#3096]
We are updating metrics in clickhouse table (engine MergeTree) with following fields

```
date Date,
dateTime DateTime,
accountId String, 
appId String, 
hostname String,
cpuUsed UInt32,
memoryUsed UInt32
```

We came with two primary keys, but not sure which is better

Primary Key 1:
```
    (accountId, appId,  hostname, dateTime), 8192)
```

Primary Key 2:
```
    (accountId, appId,  dateTime, hostname,), 8192)
```

We always filter with time range. Which primary key is efficient?

**Comment by blinkov** [comment]
You should figure out which of those queries will be more frequent. For larger periods people usually use partitioning by date/week/month, so ClickHouse reads only partitions that are needed, and sort data inside partitions by something else that is in filters often. But partitioning by small periods of time might lead to way too many files in filesystem.

Anyway to know for sure you have to take exactly your data and intended queries and see how it plays out with different possible approaches.

**Comment by filimonov** [comment]
Did you check that: https://clickhouse.yandex/docs/en/operations/table_engines/mergetree/#primary-keys-and-indexes-in-queries ?

1) `(accountId, appId,  hostname, dateTime)` that option will probably give a better compression ratio and would be effective if you mostly always use conditions for `accountId, appId,  hostname` on your selects
2) `(accountId, appId,  dateTime, hostname)` that probably will give worse compression and if you have less than few thousands of events for each second for each `accountId, appId` combination then it have not too many sense to add hostname at the end of PK. So probably `(accountId, appId,  dateTime)` would be enough.

**Comment by fizerkhan** [comment]
@filimonov Thanks. That make sense.

@blinkov - you had mentioned `For larger periods people usually use partitioning by date/week/month`

How could we do that? I assumed that Clickhouse only allows partitioning by `month`

**Comment by fizerkhan** [comment]
@blinkov - you had mentioned `For larger periods people usually use partitioning by date/week/month`
How could we do that? I assumed that Clickhouse only allows partitioning by `month`

**Comment by blinkov** [comment]
@fizerkhan https://clickhouse.yandex/docs/en/operations/table_engines/custom_partitioning_key/

**Comment by filimonov** [comment]
> for e.g. when we have it grouped by month - and if we query without hostname then it would end up parsing the whole set of rows.. (if hostname is behind timestamp). Is this assumption correct?

if you have not too many hostnames, and each group defined by tuple (`accountId, appId, hostname`) will still have >100K (rather millions) rows - may be adding `hostname` to PK before time can have some sense. If those groups are quite small and most of selects will not have hostname - rather it have no sense. 

Generally clickhouse it really good in scanning of big ranges linearly - it can scan few gigabytes per second on single mid-level server, and if it need to jump a lot then performance degrades.

Anyway it's always better to make some A/B tests, as it's hard to predict properties of real data.

**Comment by champtar** [comment]
you can also use something like `toStartOfMinute(datetime)` in primary key

```
CREATE TABLE IF NOT EXISTS thetable (
date Date,
dateTime DateTime,
accountId String, 
appId String, 
hostname String,
cpuUsed UInt32,
memoryUsed UInt32
)
ENGINE = MergeTree
PARTITION BY date
ORDER BY (accountId, appId, date, toStartOfMinute(datetime), hostname)
SETTINGS index_granularity = 8192
```

**Comment by fizerkhan** [comment]
@filimonov Thanks. We have two databases:

1. In one database, we have approx 700,000 rows in a month per host. We might have around 5,000 hosts. so it will be 3500,000,000 rows in a month. And almost every select call will either have hostname in where statement or in the `group by` statemnet. So in this case, I assume your statement makes sense to add hostname before time. So the primary key will be (accountId, appId, hostname, eventDateTime). Is that what you meant? (Of course, we will run A/B testing before deciding) 

2. In a second database, instead of hostname, we have `TxnID`. In total we have approx 5MM rows in a month per `appId` with around 100 `TxnIDs` for that app. In total we might have around 5 Billion rows per month for 1000 apps, with approx 500,000 unique `TxnIDs`. And we store queries for 3 months period. However, half of our select calls will not have `TxnIDs` in where or `group by` statements. The other half of our select calls with `TxnID` in it. In this case, what would you recommend. should we have `TxnId` before or after `eventDateTime`

```
     (accountId, appId, eventDateTime, txnId) 
     ---or---
     (accountId, appId, txnId, eventDateTime)
```

**Comment by fizerkhan** [comment]
@champtar - you have mentioned about `toStartOfMinute(datetime) in primary key` -> Is there an advantage in doing this? Does it play a role

**Comment by blinkov** [comment]
@fizerkhan is this issue still relevant?
