### ISSUE TITLE
Add size/endianness traits to Hash Function descriptors

### ISSUE THREAD

**Issue by Bulat-Ziganshin** [ClickHouse/ClickHouse#30969]
CH hashtable implementation has a lot of hash functions with different properties, but there is no way to account for individual hash function properties, so it's done on ad-hoc basis. One particular example is [computing bucket number for two-level hashtable](https://github.com/ClickHouse/ClickHouse/blob/1ea637d996715d2a047f8cd209b478e946bdbfb0/src/Common/HashTable/TwoLevelHashTable.h#L56), which doesn't work for subtables larger than 16M cells.

Based on my experience with handling hash functions, I propose to add the following traits to each hash function:

1. bitness, i.e. real number of bits in the result. well, alternative is to compute it from the return type of hash function using C++ magic
2. endianness, i.e. whether hash contains better distributed bits on the high end (such as x*CONST hash function), low end, or everywhere (such as CRC hash function)

Going deeper, you can even make hash transformers, f.e. two-row hash tables may employ a transfomer that consumes the best 8 bits of the hash function and returns the remainder (with bitness-=8 and hash result either shifted or masked).

**Comment by alexey-milovidov** [comment]
This is a good proposal, but for some reason, no one was interested in two years.
