### ISSUE TITLE
ClickHouse server suddenly fails to start (exits immediately with error code 70)

### ISSUE THREAD

**Issue by pgruderman** [ClickHouse/ClickHouse#30974]
One of our ClickHouse servers starting failing after restart this morning.  Every time it tried to restart, it would exit immediately with error code 70.  The error observed in the log is: `<Error> Application: DB::Exception: If 'engine' is specified for system table, PARTITION BY parameters should be specified directly inside 'engine' and 'partition_by' setting doesn't make sense`

We do override a number of system table settings in our config.d/config.xml file.  For example:

```
<query_log>
  <database>system</database>
  <table>query_log</table>
  <engine>ENGINE = MergeTree PARTITION BY toYYYYMM(event_date) ORDER BY (event_date, event_time) TTL event_date + INTERVAL 7 day</engine>
</query_log>
```

Since we aren't defining partition_by here, I thought maybe it was picking up the setting from the base config.xml.  I tried adding:
```
  <partition_by remove="1"/>
```
But this made no difference.  I also tried `remove="remove"`.  (Incidentally, I could not find any official documentation on how to use the remove attribute properly.)

So this leads to a couple of questions:
* Why did this behaviour appear this morning?  If the configuration was fine yesterday, it should be OK today.
* What is the correct way to fix this problem?  I've commented out the custom log settings so that the server can run, but I do need to re-enable them.

ClickHouse server version is 20.8.7 revision 54438.

The stack trace doesn't look very interesting, but here it is just in case:
```
2021.11.01 13:23:07.618631 [ 4008 ] {} <Error> Application: Caught exception while loading metadata: Code: 36, e.disp
layText() = DB::Exception: If 'engine' is specified for system table, PARTITION BY parameters should be specified dir
ectly inside 'engine' and 'partition_by' setting doesn't make sense, Stack trace (when copying this message, always i
nclude the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > c
onst&, int) @ 0x18bbe140 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > con
st&, int) @ 0xe61432d in /usr/bin/clickhouse
2. ? @ 0xe67902c in /usr/bin/clickhouse
3. DB::SystemLogs::SystemLogs(DB::Context&, Poco::Util::AbstractConfiguration const&) @ 0xe67208d in /usr/bin/clickho
use
4. DB::Context::initializeSystemLogs() @ 0x155faf71 in /usr/bin/clickhouse
5. DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<ch
ar> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >
const&) @ 0xe6b5092 in /usr/bin/clickhouse
6. Poco::Util::Application::run() @ 0x18aed1d7 in /usr/bin/clickhouse
7. DB::Server::run() @ 0xe674b29 in /usr/bin/clickhouse
8. mainEntryClickHouseServer(int, char**) @ 0xe66bb63 in /usr/bin/clickhouse
9. main @ 0xe5fe891 in /usr/bin/clickhouse
10. __libc_start_main @ 0x21b97 in /lib/x86_64-linux-gnu/libc-2.27.so
11. _start @ 0xe5fe02e in /usr/bin/clickhouse
 (version 20.8.7.15 (official build))
```

**Comment by den-crane** [comment]
Check subfolders `conf.d` & `config.d`
Check or share `/var/lib/clickhouse/preprocessed_configs/config.xml`

**Comment by den-crane** [comment]
try "replace"

```
<query_log replace="1">
  <database>system</database>
  <table>query_log</table>
  <engine>ENGINE = MergeTree PARTITION BY toYYYYMM(event_date) ORDER BY (event_date, event_time) TTL event_date + INTERVAL 7 day</engine>
</query_log>
```

**Comment by pgruderman** [comment]
Thanks a lot, Denis.  I'm still confused about what happened here, but "replace" does the trick.

**Comment by alexey-milovidov** [comment]
`replace` replaces all the subtree.
Without `replace` subtrees will be merge together.

`remove` should help, I have no idea why it didn't, maybe it was in the wrong place.
