### ISSUE TITLE
replicate should work faster than arrayMap

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#30979]
**Describe the situation**
replicate work with the same speed as arrayMap

**How to reproduce**
ClickHouse 21.11
```
SELECT count()
FROM numbers(100000000)
WHERE NOT ignore(replicate(1, materialize(range(10))))
FORMAT `Null`

Ok.

0 rows in set. Elapsed: 0.637 sec. Processed 100.03 million rows, 800.21 MB (156.91 million rows/s., 1.26 GB/s.)

SELECT count()
FROM numbers(100000000)
WHERE NOT ignore(arrayMap(x -> 1, materialize(range(10))))
FORMAT `Null`

Ok.

0 rows in set. Elapsed: 0.680 sec. Processed 100.03 million rows, 800.21 MB (147.11 million rows/s., 1.18 GB/s.)

SELECT count()
FROM numbers(100000000)
WHERE NOT ignore(arrayMap(x -> 1, materialize(range(100))))
FORMAT `Null`

Ok.

0 rows in set. Elapsed: 3.692 sec. Processed 100.03 million rows, 800.21 MB (27.09 million rows/s., 216.72 MB/s.)

SELECT count()
FROM numbers(100000000)
WHERE NOT ignore(replicate(1, materialize(range(100))))
FORMAT `Null`

Ok.

0 rows in set. Elapsed: 3.456 sec. Processed 100.03 million rows, 800.21 MB (28.94 million rows/s., 231.55 MB/s.)

```
**Expected performance**

replicate is much simpler function as it doesn't iterate over array values, and don't need to do all the costly work like arrayMap.

**Comment by UnamedRus** [comment]
AFAIK replicate being used internally for arrayJoin and arrayMap-like functions (because they internally use arrayJoin)

So it's possible to have some internal representation for array with constant value per row like: size of array + value

**Comment by alexey-milovidov** [comment]
`replicate` is doing the same work as a trivial `arrayMap`, not less.

**Comment by alexey-milovidov** [comment]
> to have some internal representation for array with constant value per row

It was removed long time ago to avoid complexity.
