### ISSUE TITLE
how do i query table information 

### ISSUE THREAD

**Issue by myLouisJava** [ClickHouse/ClickHouse#30991]
if i use database engine mysql, how do i query table information(include: rows, data_uncompressed_bytes, data_compressed_bytes, etc)? 
i also want to konw where is data stored? in clickhouse or in mysql? 

![image](https://user-images.githubusercontent.com/37395295/139829426-90c75659-7827-4c4c-8c1f-ae2a83418ede.png)

**Comment by den-crane** [comment]
>how do i query table information(include: rows, data_uncompressed_bytes, data_compressed_bytes, etc)?

There is no such data in CH.

>i also want to konw where is data stored? in clickhouse or in mysql?

In Mysql. When you query data from MySQL engine Clickhouse executes this query in MySQL and fetches data from MySQL directly. No data is stored in Clickhouse

**Comment by myLouisJava** [comment]
> > how do i query table information(include: rows, data_uncompressed_bytes, data_compressed_bytes, etc)?
> 
> There is no such data in CH.
> 
> > i also want to konw where is data stored? in clickhouse or in mysql?
> 
> In Mysql. When you query data from MySQL engine Clickhouse executes this query in MySQL and fetches data from MySQL directly. No data is stored in Clickhouse

so, query data from clickhouse(MySQL engine)  compared with query data from mysql directly, it does not improve query efficiency?
When MaterializedMySQL engine can be used in production?
thank you for your answer!

**Comment by den-crane** [comment]
>so, query data from clickhouse(MySQL engine) compared with query data from mysql directly,
> it does not improve query efficiency?

It does improve, clickhouse makes aggregations faster than mysql.

>When MaterializedMySQL engine can be used in production?

Nobody works on it. It's abandoned. Maybe never.

**Comment by myLouisJava** [comment]
> > so, query data from clickhouse(MySQL engine) compared with query data from mysql directly,
> > it does not improve query efficiency?
> 
> It does improve, clickhouse makes aggregations faster than mysql.
> 
> > When MaterializedMySQL engine can be used in production?
> 
> Nobody works on it. It's abandoned. Maybe never.

ok. thanks for your answer
