### ISSUE TITLE
Using debug mode, the function fails

### ISSUE THREAD

**Issue by Faynebupt** [ClickHouse/ClickHouse#31037]
clickhouse compile by 'cmake -D CMAKE_BUILD_TYPE=Debug ..' and 'ninja -j 56 clickhouse-server clickhouse-client' order;
We can use the mergetree table function, but this error is reported when using the HDFS table, which cannot be solved.

2021.11.03 09:51:45.026673 [ 21193 ] {} <Trace> BaseDaemon: Received signal 4
2021.11.03 09:51:45.028399 [ 21355 ] {} <Fatal> BaseDaemon: ########################################
2021.11.03 09:51:45.030683 [ 21355 ] {} <Fatal> BaseDaemon: (version 21.9.2.17, build id: A3BDCD255477951E56E0BE5C7C7A90E4EC9F12D4) (from thread 21196) (query_id: 51ce24fe-67d7-41d2-ade8-b239e315bf9e) Received signal Illegal instruction (4)
2021.11.03 09:51:45.032061 [ 21355 ] {} <Fatal> BaseDaemon: Illegal operand.
2021.11.03 09:51:45.033303 [ 21355 ] {} <Fatal> BaseDaemon: Stack trace: 0x130e7e9a 0x255a78be 0x255a216f 0x255a1b8b 0x255a1ce4 0x25594678 0x1d3f9899 0x1d3eca2b 0x1ea7f53d 0x1e1aa2c3 0x1e1a3dd3 0x1e1a3106 0x1e53930a 0x1e539cdd 0x1e7df024 0x1e7dd1a5 0x1f3d2103 0x1f3df8e8 0x239edbdc 0x239ee442 0x23b47de3 0x23b446fd 0x23b4346a 0x7f864dbc2609 0x7f864dad8293
2021.11.03 09:51:45.042873 [ 21355 ] {} <Fatal> BaseDaemon: 4. /mnt/last/baidu/codelab/blackhole/blackhole/sql/cpp/clickhouse/build/../base/harmful/harmful.c:211: rand @ 0x130e7e9a in /mnt/last/baidu/codelab/blackhole/blackhole/sql/cpp/clickhouse/build/programs/clickhouse
2021.11.03 09:51:45.228638 [ 21355 ] {} <Fatal> BaseDaemon: 5. /mnt/last/baidu/codelab/blackhole/blackhole/sql/cpp/clickhouse/build/../contrib/libhdfs3/src/client/FileSystemImpl.cpp:114: Hdfs::Internal::FileSystemImpl::FileSystemImpl(Hdfs::Internal::FileSystemKey const&, Hdfs::Config const&) @ 0x255a78be in /mnt/last/baidu/codelab/blackhole/blackhole/sql/cpp/clickhouse/build/programs/clickhouse
2021.11.03 09:51:45.368564 [ 21355 ] {} <Fatal> BaseDaemon: 6. /mnt/last/baidu/codelab/blackhole/blackhole/sql/cpp/clickhouse/build/../contrib/libhdfs3/src/client/FileSystem.cpp:224: Hdfs::ConnectInternal(char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Hdfs::Internal::Token const*, Hdfs::Config&) @ 0x255a216f in /mnt/last/baidu/codelab/blackhole/blackhole/sql/cpp/clickhouse/build/programs/clickhouse
2021.11.03 09:51:45.496833 [ 21355 ] {} <Fatal> BaseDaemon: 7. /mnt/last/baidu/codelab/blackhole/blackhole/sql/cpp/clickhouse/build/../contrib/libhdfs3/src/client/FileSystem.cpp:275: Hdfs::FileSystem::connect(char const*, char const*, char const*) @ 0x255a1b8b in /mnt/last/baidu/codelab/blackhole/blackhole/sql/cpp/clickhouse/build/programs/clickhouse
2021.11.03 09:51:45.637550 [ 21355 ] {} <Fatal> BaseDaemon: 8. /mnt/last/baidu/codelab/blackhole/blackhole/sql/cpp/clickhouse/build/../contrib/libhdfs3/src/client/FileSystem.cpp:210: Hdfs::FileSystem::connect(char const*) @ 0x255a1ce4 in /mnt/last/baidu/codelab/blackhole/blackhole/sql/cpp/clickhouse/build/programs/clickhouse
2021.11.03 09:51:45.770487 [ 21355 ] {} <Fatal> BaseDaemon: 9. /mnt/last/baidu/codelab/blackhole/blackhole/sql/cpp/clickhouse/build/../contrib/libhdfs3/src/client/Hdfs.cpp:493: hdfsBuilderConnect @ 0x25594678 in /mnt/last/baidu/codelab/blackhole/blackhole/sql/cpp/clickhouse/build/programs/clickhouse
2021.11.03 09:51:45.872568 [ 21355 ] {} <Fatal> BaseDaemon: 10. /mnt/last/baidu/codelab/blackhole/blackhole/sql/cpp/clickhouse/build/../src/Storages/HDFS/HDFSCommon.cpp:186: DB::createHDFSFS(hdfsBuilder*) @ 0x1d3f9899 in /mnt/last/baidu/codelab/blackhole/blackhole/sql/cpp/clickhouse/build/programs/clickhouse
2021.11.03 09:51:46.000421 [ 21199 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 660.99 MiB, peak 660.99 MiB, will set to 727.68 MiB (RSS), difference: 66.68 MiB
2021.11.03 09:51:46.455200 [ 21355 ] {} <Fatal> BaseDaemon: 11. /mnt/last/baidu/codelab/blackhole/blackhole/sql/cpp/clickhouse/build/../src/Storages/HDFS/StorageHDFS.cpp:286: DB::StorageHDFS::read(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryInfo&, std::__1::shared_ptr<DB::Context const>, DB::QueryProcessingStage::Enum, unsigned long, unsigned int) @ 0x1d3eca2b in /mnt/last/baidu/codelab/blackhole/blackhole/sql/cpp/clickhouse/build/programs/clickhouse
2021.11.03 09:51:47.000415 [ 21199 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 727.68 MiB, peak 727.68 MiB, will set to 751.66 MiB (RSS), difference: 23.98 MiB
2021.11.03 09:51:47.105042 [ 21355 ] {} <Fatal> BaseDaemon: 12. /mnt/last/baidu/codelab/blackhole/blackhole/sql/cpp/clickhouse/build/../src/Storages/IStorage.cpp:108: DB::IStorage::read(DB::QueryPlan&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryInfo&, std::__1::shared_ptr<DB::Context const>, DB::QueryProcessingStage::Enum, unsigned long, unsigned int) @ 0x1ea7f53d in /mnt/last/baidu/codelab/blackhole/blackhole/sql/cpp/clickhouse/build/programs/clickhouse
2021.11.03 09:51:48.000637 [ 21199 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 751.66 MiB, peak 751.66 MiB, will set to 778.25 MiB (RSS), difference: 26.59 MiB
2021.11.03 09:51:48.441128 [ 21355 ] {} <Fatal> BaseDaemon: 13. /mnt/last/baidu/codelab/blackhole/blackhole/sql/cpp/clickhouse/build/../src/Interpreters/InterpreterSelectQuery.cpp:1988: DB::InterpreterSelectQuery::executeFetchColumns(DB::QueryProcessingStage::Enum, DB::QueryPlan&) @ 0x1e1aa2c3 in /mnt/last/baidu/codelab/blackhole/blackhole/sql/cpp/clickhouse/build/programs/clickhouse
2021.11.03 09:51:49.000504 [ 21199 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 778.25 MiB, peak 778.25 MiB, will set to 788.80 MiB (RSS), difference: 10.55 MiB
2021.11.03 09:51:49.763522 [ 21355 ] {} <Fatal> BaseDaemon: 14. /mnt/last/baidu/codelab/blackhole/blackhole/sql/cpp/clickhouse/build/../src/Interpreters/InterpreterSelectQuery.cpp:1039: DB::InterpreterSelectQuery::executeImpl(DB::QueryPlan&, std::__1::shared_ptr<DB::IBlockInputStream> const&, std::__1::optional<DB::Pipe>) @ 0x1e1a3dd3 in /mnt/last/baidu/codelab/blackhole/blackhole/sql/cpp/clickhouse/build/programs/clickhouse
2021.11.03 09:51:51.072524 [ 21355 ] {} <Fatal> BaseDaemon: 15. /mnt/last/baidu/codelab/blackhole/blackhole/sql/cpp/clickhouse/build/../src/Interpreters/InterpreterSelectQuery.cpp:580: DB::InterpreterSelectQuery::buildQueryPlan(DB::QueryPlan&) @ 0x1e1a3106 in /mnt/last/baidu/codelab/blackhole/blackhole/sql/cpp/clickhouse/build/programs/clickhouse
2021.11.03 09:51:51.644803 [ 21355 ] {} <Fatal> BaseDaemon: 16. /mnt/last/baidu/codelab/blackhole/blackhole/sql/cpp/clickhouse/build/../src/Interpreters/InterpreterSelectWithUnionQuery.cpp:255: DB::InterpreterSelectWithUnionQuery::buildQueryPlan(DB::QueryPlan&) @ 0x1e53930a in /mnt/last/baidu/codelab/blackhole/blackhole/sql/cpp/clickhouse/build/programs/clickhouse
2021.11.03 09:51:52.202288 [ 21355 ] {} <Fatal> BaseDaemon: 17. /mnt/last/baidu/codelab/blackhole/blackhole/sql/cpp/clickhouse/build/../src/Interpreters/InterpreterSelectWithUnionQuery.cpp:321: DB::InterpreterSelectWithUnionQuery::execute() @ 0x1e539cdd in /mnt/last/baidu/codelab/blackhole/blackhole/sql/cpp/clickhouse/build/programs/clickhouse
2021.11.03 09:51:52.914938 [ 21355 ] {} <Fatal> BaseDaemon: 18. /mnt/last/baidu/codelab/blackhole/blackhole/sql/cpp/clickhouse/build/../src/Interpreters/executeQuery.cpp:573: DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, bool, DB::ReadBuffer*) @ 0x1e7df024 in /mnt/last/baidu/codelab/blackhole/blackhole/sql/cpp/clickhouse/build/programs/clickhouse
2021.11.03 09:51:53.000421 [ 21199 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 789.82 MiB, peak 789.82 MiB, will set to 799.75 MiB (RSS), difference: 9.93 MiB
2021.11.03 09:51:53.673207 [ 21355 ] {} <Fatal> BaseDaemon: 19. /mnt/last/baidu/codelab/blackhole/blackhole/sql/cpp/clickhouse/build/../src/Interpreters/executeQuery.cpp:934: DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, bool) @ 0x1e7dd1a5 in /mnt/last/baidu/codelab/blackhole/blackhole/sql/cpp/clickhouse/build/programs/clickhouse
2021.11.03 09:51:54.000417 [ 21199 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 799.75 MiB, peak 799.75 MiB, will set to 802.48 MiB (RSS), difference: 2.73 MiB
2021.11.03 09:51:54.487885 [ 21355 ] {} <Fatal> BaseDaemon: 20. /mnt/last/baidu/codelab/blackhole/blackhole/sql/cpp/clickhouse/build/../src/Server/TCPHandler.cpp:312: DB::TCPHandler::runImpl() @ 0x1f3d2103 in /mnt/last/baidu/codelab/blackhole/blackhole/sql/cpp/clickhouse/build/programs/clickhouse
2021.11.03 09:51:55.000416 [ 21199 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 802.48 MiB, peak 802.48 MiB, will set to 810.06 MiB (RSS), difference: 7.58 MiB
2021.11.03 09:51:55.339783 [ 21355 ] {} <Fatal> BaseDaemon: 21. /mnt/last/baidu/codelab/blackhole/blackhole/sql/cpp/clickhouse/build/../src/Server/TCPHandler.cpp:1658: DB::TCPHandler::run() @ 0x1f3df8e8 in /mnt/last/baidu/codelab/blackhole/blackhole/sql/cpp/clickhouse/build/programs/clickhouse
2021.11.03 09:51:55.406610 [ 21355 ] {} <Fatal> BaseDaemon: 22. /mnt/last/baidu/codelab/blackhole/blackhole/sql/cpp/clickhouse/build/../contrib/poco/Net/src/TCPServerConnection.cpp:43: Poco::Net::TCPServerConnection::start() @ 0x239edbdc in /mnt/last/baidu/codelab/blackhole/blackhole/sql/cpp/clickhouse/build/programs/clickhouse
2021.11.03 09:51:55.513318 [ 21355 ] {} <Fatal> BaseDaemon: 23. /mnt/last/baidu/codelab/blackhole/blackhole/sql/cpp/clickhouse/build/../contrib/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x239ee442 in /mnt/last/baidu/codelab/blackhole/blackhole/sql/cpp/clickhouse/build/programs/clickhouse
2021.11.03 09:51:55.611114 [ 21355 ] {} <Fatal> BaseDaemon: 24. /mnt/last/baidu/codelab/blackhole/blackhole/sql/cpp/clickhouse/build/../contrib/poco/Foundation/src/ThreadPool.cpp:199: Poco::PooledThread::run() @ 0x23b47de3 in /mnt/last/baidu/codelab/blackhole/blackhole/sql/cpp/clickhouse/build/programs/clickhouse
2021.11.03 09:51:55.702144 [ 21355 ] {} <Fatal> BaseDaemon: 25. /mnt/last/baidu/codelab/blackhole/blackhole/sql/cpp/clickhouse/build/../contrib/poco/Foundation/src/Thread.cpp:56: Poco::(anonymous namespace)::RunnableHolder::run() @ 0x23b446fd in /mnt/last/baidu/codelab/blackhole/blackhole/sql/cpp/clickhouse/build/programs/clickhouse
2021.11.03 09:51:55.791927 [ 21355 ] {} <Fatal> BaseDaemon: 26. /mnt/last/baidu/codelab/blackhole/blackhole/sql/cpp/clickhouse/build/../contrib/poco/Foundation/src/Thread_POSIX.cpp:345: Poco::ThreadImpl::runnableEntry(void*) @ 0x23b4346a in /mnt/last/baidu/codelab/blackhole/blackhole/sql/cpp/clickhouse/build/programs/clickhouse
2021.11.03 09:51:55.792366 [ 21355 ] {} <Fatal> BaseDaemon: 27. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
2021.11.03 09:51:55.792811 [ 21355 ] {} <Fatal> BaseDaemon: 28. clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
2021.11.03 09:51:56.000413 [ 21199 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 810.06 MiB, peak 810.06 MiB, will set to 816.12 MiB (RSS), difference: 6.06 MiB
2021.11.03 09:51:57.192938 [ 21355 ] {} <Fatal> BaseDaemon: Calculated checksum of the binary: 9F683AA3C2838BB0BD0B8298376006DB. There is no information about the reference checksum.
2021.11.03 09:51:57.193148 [ 21355 ] {} <Information> SentryWriter: Not sending crash report
2021.11.03 09:51:58.182189 [ 21203 ] {} <Debug> DNSResolver: Updating DNS cache
2021.11.03 09:51:58.182672 [ 21203 ] {} <Debug> DNSResolver: Updated DNS cache

**Comment by tavplubix** [comment]
Fixed in  #29276
