### ISSUE TITLE
clickhouse support s3 like cloud native 

### ISSUE THREAD

**Issue by Faynebupt** [ClickHouse/ClickHouse#31043]
We rely heavily on the storage media of cloud S3. When can the merge tree table of CK improve the speed of supporting S3 and support cloud native.
The current support for S3 is still not comparable to tiledb's similar cloud native storage engine.
tks！

**Comment by alesapin** [comment]
Recently we improved read performance for  MergeTree tables with S3 "disks": https://github.com/ClickHouse/ClickHouse/pull/29205#issuecomment-955560698
