### ISSUE TITLE
RepliactedMergeTree is readonly if one zookeeper in the cluster in not available, stopped servers do not start

### ISSUE THREAD

**Issue by mgehlmann** [ClickHouse/ClickHouse#31052]
Hi,

I have come across an odd behavior of the clickhouse-server when one zookeeper from an otherwise healthy cluster becomes unavailable. The behavior in case of zookeeper failure is not covered by the documentation and I am not sure if this is working as intended.

I have set up replication with a cluster of 5 zookeepers. If I shut down only 1 of the 5 zookeepers, the replication stops working, although the 4 remaining zookeepers are healthy and functioning. The effects are:

* replicated tables on running servers become read only
* stopped clickhouse-servers fail to start.

Only after I manually remove the missing zookeeper from the clickhouse-server config the write requests start working again and the shut-down server can start without failure. No need to bring back the missing zookeeper node.

So it seems that when you set up replication following the documentation, every one of the zookeepers is a single point of failure, although the zookeepers themselves are set up for high availability.
Am I missing something e.g. undocumented configuration or is this the intended behavior?

**How to reproduce**

1. ClickHouse version 21.10.2.15 (official build)
2. Configure zookeeper nodes
3. Shut down one of the zookeepers while still having a number of functional nodes > quorum
4. Try to insert data into a replicated table or (re-)start a clickhouse-server

**Expected behavior**
If at least one of the configured zookeeper nodes answers requests, it means that it fulfilled its configured criteria to be considered healthy (meaning a the configured quorum was reached). So the clickhouse-server should try ALL configured nodes before failing. 

**Error message and/or stacktrace**
When I shut down the zookeeper then the clickhouse-server logs:

1. `<Error> [...]: void DB::StorageReplicatedMergeTree::queueUpdatingTask(): Code: 999. Coordination::Exception: Session expired (Session expired). (KEEPER_EXCEPTION)`
2. `<Warning> [...]: ZooKeeper session has expired. Switching to a new session.`
3. `<Error> zkutil::EphemeralNodeHolder::~EphemeralNodeHolder(): Cannot remove /clickhouse/tables/01/[...]/replicas/[...]/is_active: : Code: 999. Coordination::Exception: Session expired (Session expired). (KEEPER_EXCEPTION)`
4. `<Information> [...]: Stopped being leader`
5. `<Error> [...]: void DB::ReplicatedMergeTreeRestartingThread::run(): Code: 999. Coordination::Exception: All connection tries failed while connecting to ZooKeeper. nodes: [... missing nodes IP:PORT ...]`
6. `<Error> executeQuery: Code: 242. DB::Exception: Table is in readonly mode (zookeeper path: /clickhouse/tables/01/[...]). (TABLE_IS_READ_ONLY) (version 21.10.2.15 (official build)) (from 192.168.28.159:54816) (in query: INSERT INTO [...] VALUES)`

(Re-)starting a clickhouse-server with the zookeeper node missing leads do the clickhouse-server logging timeouts to the zookeeper node and shutting down again.

**Comment by den-crane** [comment]
It's really unexpected. I turned off one of 3 ZK node hundreds of time, no impact on CH.

Can you show how zookeeper configured in your CH.
can you share `echo mntr|nc localhost 2181` from a ZK leader when all 5 nodes UP and when 1 node down.

```
echo mntr|nc localhost 2181
...
zk_server_state	leader
....
zk_followers	2
zk_synced_followers	2
zk_pending_syncs	0
```

**Comment by mgehlmann** [comment]
My zookeeper config:

```
# cat /etc/clickhouse-server/config.d/zookeeper-servers.xml
<?xml version="1.0"?>
<yandex>
    <zookeeper>
                <node index="1">
                        <host>NODE_FQDN_0</host>
                        <port>2181</port>
                </node>
    </zookeeper>
    <zookeeper>
                <node index="2">
                        <host>NODE_FQDN_1</host>
                        <port>2181</port>
                </node>
    </zookeeper>
    <zookeeper>
                <node index="3">
                        <host>NODE_FQDN_2</host>
                        <port>2181</port>
                </node>
    </zookeeper>
    <zookeeper>
                <node index="4">
                        <host>NODE_FQDN_3</host>
                        <port>2181</port>
                </node>
    </zookeeper>
    <zookeeper>
                <node index="5">
                        <host>NODE_FQDN_4</host>
                        <port>2181</port>
                </node>
    </zookeeper>
</yandex>
```

Now:

```
# echo mntr|nc localhost 2181| grep -P 'zk_server_state|zk_followers|zk_synced_followers|zk_pending_syncs'
```
All zookeepers up:
```
# NODE_FQDN_0:
zk_server_state follower
# NODE_FQDN_1:
zk_server_state follower
# NODE_FQDN_2:
zk_server_state follower
# NODE_FQDN_3:
zk_server_state follower
# NODE_FQDN_4:
zk_server_state leader
zk_followers    4
zk_synced_followers     4
zk_pending_syncs        0
```

And shutting `NODE_FQDN_0` down:
```
# NODE_FQDN_1:
zk_server_state follower
# NODE_FQDN_2:
zk_server_state follower
# NODE_FQDN_3:
zk_server_state follower
# NODE_FQDN_4:
zk_server_state leader
zk_followers    3
zk_synced_followers     3
zk_pending_syncs        0
```

**Comment by mgehlmann** [comment]
It does not sound like an issue with the zookeeper cluster to me, especially since the clickhouse-servers work perfectly fine with the remaining 4 zookeepers as long as I remove the shut-down one from the clickhouse-config.

So if it is a misconfiguration, this behavior suggests that the issue on the side of my clickhouse-servers. But I haven't found information in the documentation about the intended behavior in case of a zookeeper node failure, or if there are config parameters that it depends on.

**Comment by mgehlmann** [comment]
OK, now I see the problem: it should be:

```
# cat /etc/clickhouse-server/config.d/zookeeper-servers.xml
<?xml version="1.0"?>
<yandex>
    <zookeeper>
                <node index="1">
                        <host>NODE_FQDN_0</host>
                        <port>2181</port>
                </node>
                <node index="2">
                        <host>NODE_FQDN_1</host>
                        <port>2181</port>
                </node>
                <node index="3">
                        <host>NODE_FQDN_2</host>
                        <port>2181</port>
                </node>
                <node index="4">
                        <host>NODE_FQDN_3</host>
                        <port>2181</port>
                </node>
                <node index="5">
                        <host>NODE_FQDN_4</host>
                        <port>2181</port>
                </node>
    </zookeeper>
</yandex>
```

So I guess I actually had only one zookeeper configured. I'm going to test it now, but that will probably solve it. I'll post the update and close the issue if it does...

**Comment by mgehlmann** [comment]
Yes, it is working now. Killing a zookeeper with active connections now triggers a proper failover on the clickhouse-server side opening a new session to a working node.

Thanks for the feedback, @den-crane
