### ISSUE TITLE
Corrupted data part doesn't get restored automatically from replica

### ISSUE THREAD

**Issue by malikas05** [ClickHouse/ClickHouse#31061]
Hi all!

My team and I have been working on setting up the Clickhouse cluster and POCing it as the solution to our analytical data store. As part of this effort, in preparation for rolling out the cluster, we were conducting different experiments in order to know more about the behavior as well as be ready for any unexpected outcomes. One of such experiments was to corrupt some data parts and observe whether those parts would be recovered automatically from the second replica. (By the way, just to give you some context on how our cluster looks like -- it contains 3 shards, 2 replicas each where most of the tables use the **ReplicatedSummingMergeTree** engine.) However, it appears that data corruption in Clickhouse is discovered/repaired from replicas only when data is accessed (e.g., via a query). This is also mentioned in the official Clickhouse docs found here: 

> When the server starts (or establishes a new session with ZooKeeper), it only checks the quantity and sizes of all files. If the file sizes match but bytes have been changed somewhere in the middle, this is not detected immediately, but only when attempting to read the data for a SELECT query. The query throws an exception about a non-matching checksum or size of a compressed block. In this case, data parts are added to the verification queue and copied from the replicas if necessary.
https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/replication/#recovery-after-failures

This has been also verified by us. We executed the query to pull some data from that specific broken data part, and initially, it returned the exception:
> Code: 33. DB::Exception: Received from ******.com:9000. DB::Exception: Cannot read all data. Bytes read: 22694. Bytes expected: 29294.: (while reading column ******): (while reading from part /opt/ch-data/store/719/7191f35e-d754-45f4-b191-f35ed75485f4/1606626000_1_1_3/ from mark 72 with max_rows_to_read = 8192): While executing MergeTreeThread.

However, the second attempt was successful, and the returned dataset was exactly the same as the one returned by replica 2. It was also confirmed that the broken data part appeared in the /detached folder and it was restored in the filesystem. 

The point is that we assumed that the recovery would be kicked off automatically in the background rather than after some action triggered by the client. This leads us to start being anxious about the possible complete data loss when the repair process is not identified automatically. For example, the following set of circumstances could lead to complete data loss:
1. Data gets corrupted on replica1 at time t0.
2. Same data part on replica 2 gets corrupted sometime later, say t0 + 10 days.
2. Corrupted data on replica1 is only accessed and attempted to get restored from replica2 at time t0 + 20 days.

Obviously, if the corrupted data was identified/fixed quickly, then there is a low risk of replica2 getting corrupted before replica1 has a chance to repair its data. However, in reality, the data may not be recognized as corrupted for a long time (e.g., 20 days, as in the example above), then it means that during that whole time that we're running on a single, accurate replica, there's a risk of us completely losing the data.

**As such, we wanted to know whether Clickhouse provides any other mechanism/option for recognizing corrupted data more quickly. If there is no such, does anyone have any experience tackling this problem? Any suggestions/insights will be much appreciated. Thank you in advance!**

**Comment by den-crane** [comment]
Options:
* backup your data
* have 3 replica
* run `check table` by cron https://clickhouse.com/docs/en/sql-reference/statements/check-table/

**Comment by malikas05** [comment]
> Options:
> 
> * backup your data
> * have 3 replica
> * run `check table` by cron https://clickhouse.com/docs/en/sql-reference/statements/check-table/

@den-crane, thanks for your reply. Regarding the third option, it's not mentioned in the documentation, but does the recovery kicks off automatically when this command is run? Or does it just provide the context of what is (un)healthy?

**Comment by den-crane** [comment]
Yes, `check table` triggers broken part removal and this eventually imitates a fetch from a healthy replica.
