### ISSUE TITLE
Zookeeper node loss using ReplicatedAggregatingMergeTree engine

### ISSUE THREAD

**Issue by jztian** [ClickHouse/ClickHouse#31068]
> You have to provide the following information whenever possible.

When using the replicatedaggregatingmergetree engine, when we write data to the distributed table or perform (optimize table) merging parts, we will report an error that the node on the zookeeper is lost. The specific error report is shown in the figure below：
![image](https://user-images.githubusercontent.com/31120351/140265542-5b4214dc-0a13-42b6-bed7-40b957ba18ab.png)

CREATE TABLE  order_db.t_trade_order_payment_thirdparty_coupon on cluster ch_2shards_3replicas (
  `id`                       Int64 NOT NULL,
  `order_id`                 SimpleAggregateFunction(anyLast, Int64)  NOT NULL COMMENT 'order id',
  `created_at`               SimpleAggregateFunction(anyLast, Nullable(DateTime)),
  `updated_at`               SimpleAggregateFunction(anyLast, Nullable(DateTime)),
  `created_by`               SimpleAggregateFunction(anyLast, Nullable(String)),
  `updated_by`               SimpleAggregateFunction(anyLast, Nullable(String)),
  `last_updated_at`          SimpleAggregateFunction(anyLast, DateTime) NOT NULL  COMMENT '最后更新时间'
) ENGINE = ReplicatedAggregatingMergeTree( '/clickhouse1/table/{shard}/order_db/t_trade_order_payment_thirdparty_coupon','{replica}') 
PARTITION BY (intHash64(id) % 6)
ORDER BY id
SETTINGS index_granularity = 8192,use_minimalistic_part_header_in_zookeeper = 1,storage_policy = 'policy_all';

CREATE TABLE   order_db.t_trade_order_payment_thirdparty_coupon_all ON CLUSTER ch_2shards_3replicas AS order_db.t_trade_order_payment_thirdparty_coupon
ENGINE = Distributed(ch_2shards_3replicas, order_db, t_trade_order_payment_thirdparty_coupon, intHash64(id));

> A clear and concise description of what works not as it is supposed to.

    ClickHouse server version 21.8.9.13 (official build)

**Comment by alesapin** [comment]
Hi, thank you for the report. Nodes cannot disappear from ZooKeeper and ClickHouse can remove them only on table drop. But there are several reasons, why it can happen:
1) Concurrent `DROP TABLE`, the most common reason.
2) Connection to the wrong ZooKeeper cluster or to the wrong node (which participate in  some other cluster).
3) ZooKeeper misconfiguration so it rollbacks it state and nodes disappear. 
I don't have any other idea how such important node as `log_pointer` can be deleted.

**Comment by jztian** [comment]
> Hi, thank you for the report. Nodes cannot disappear from ZooKeeper and ClickHouse can remove them only on table drop. But there are several reasons, why it can happen:
> 
> 1. Concurrent `DROP TABLE`, the most common reason.
> 2. Connection to the wrong ZooKeeper cluster or to the wrong node (which participate in  some other cluster).
> 3. ZooKeeper misconfiguration so it rollbacks it state and nodes disappear.
> 
> I don't have any other idea how such important node as `log_pointer` can be deleted.

I have a new discovery. When I use the multi disk strategy（storage_policy = 'policy_all';）, this problem occurs frequently. Is this a bug？

**Comment by tavplubix** [comment]
Maybe, but I have no ideas how it can be related to storage policy. Btw, do you use `SYSTEM DROP REPLICA` query?

**Comment by jztian** [comment]
> Maybe, but I have no ideas how it can be related to storage policy. Btw, do you use `SYSTEM DROP REPLICA` query?

I didn't use it （SYSTEM DROP REPLICA）

**Comment by filimonov** [comment]
How many nodes in ZooKeeper ensemble do you have? Are you sure they are configured properly - i.e. you have 3 in-sync zookeeper nodes, not 3 standalone zookeepers?

**Comment by jztian** [comment]
> How many nodes in ZooKeeper ensemble do you have? Are you sure they are configured properly - i.e. you have 3 in-sync zookeeper nodes, not 3 standalone zookeepers?

The configuration of zookeeper is correct. It is normal for me to use zookeeper for three nodes when I do not use disk policy, but not when I use disk policy

**Comment by alexey-milovidov** [comment]
This issue can appear only in case of misconfiguration or manual intervention with ZooKeeper data.
