### ISSUE TITLE
clickhouse command line tool export with error, /usr/local/clickhouse/clickhouse-client: Argument list too long

### ISSUE THREAD

**Issue by minicloudsky** [ClickHouse/ClickHouse#31069]
I export data with clickhouse command-line cli,however,an error occured,
/usr/local/clickhouse/clickhouse-client version
ClickHouse client version 19.15.2.2.
Connecting to localhost:9000 as user default.

**Operating system**
centos7
clickhouse version
/usr/local/clickhouse/clickhouse-client version
ClickHouse client version 19.15.2.2.
Connecting to localhost:9000 as user default.
Code: 210. DB::NetException: Connection refused (localhost:9000)
what is the max length of clickhouse cli argument's maxlength,I studyed the cli doc,however,t get nothing about the maxlength~

**Comment by alexey-milovidov** [comment]
There is no limit on arguments length in ClickHouse,
you may face OS or shell limits.
