### ISSUE TITLE
Code: 43. DB::Exception: Nested type Nullable(UInt32) cannot be inside Nullable type. (ILLEGAL_TYPE_OF_ARGUMENT) (version 21.10.2.15 (official build))

### ISSUE THREAD

**Issue by a747097587** [ClickHouse/ClickHouse#31075]
> You have to provide the following information whenever possible.

**Describe what's wrong**

When the table has a `Nullable(DateTime)` column, the select sql can not be executed successfully

there is only 1 row in this talbe

![image](https://user-images.githubusercontent.com/28568597/140292326-44a34761-4777-4c64-8d48-3e5e39a82bd6.png)

the column `pay_time` is `Nullable(DateTime)`

![image](https://user-images.githubusercontent.com/28568597/140291130-eed2fa6a-7855-48a4-9e1f-32c16146ce9d.png)

this can success

```sql
select * from dou_ch_item_orders final where pay_time is not null;
```

this failed

```sql
select * from dou_ch_item_orders final where pay_time between '2021-11-03 00:00:00' and '2021-11-03 23:59:59';
```

In version `21.10.2.15`, the second sql  went wrong.

![深度截图_选择区域_20211104173441](https://user-images.githubusercontent.com/28568597/140290821-178e88c8-6737-4cc2-9667-2888ddafb592.png)

In version `21.8.4.51`, all the sqls are executed successfully

> A clear and concise description of what works not as it is supposed to.

**Does it reproduce on recent release?**

[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

**Enable crash reporting**

> If possible, change "enabled" to true in "send_crash_reports" section in `config.xml`:

```
<send_crash_reports>
        <!-- Changing <enabled> to true allows sending crash reports to -->
        <!-- the ClickHouse core developers team via Sentry https://sentry.io -->
        <enabled>false</enabled>
```

**How to reproduce**

* Which ClickHouse server version to use
* Which interface to use, if matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

**Expected behavior**

> A clear and concise description of what you expected to happen.

**Error message and/or stacktrace**

> If applicable, add screenshots to help explain your problem.

**Additional context**

> Add any other context about the problem here.

**Comment by den-crane** [comment]
@a747097587 Do you have repro?

I cannot reproduce

```
create table testN (d Nullable(DateTime)) engine=ReplacingMergeTree order by tuple();
select * from testN final where d between '2020-01-01 00:00:00' and '2021-01-01 00:00:00'　;
0 rows in set. Elapsed: 0.001 sec.
```

Is it Distributed table?

Can you share `show create table dou_ch_item_orders` ?

**Comment by a747097587** [comment]
@den-crane 
**This can reproduce**


This the test table
```sql
CREATE TABLE test_for_repro
(
    `oid` UInt64,
    `user_id` UInt64,
    `create_time` DateTime,
    `pay_time` Nullable(DateTime),
    `logistics_time` Nullable(DateTime),
    `end_time` Nullable(DateTime),
    `ch_modified` DateTime,
    INDEX minmax_pay_date toYYYYMMDD(pay_time) TYPE minmax GRANULARITY 3,
    INDEX minmax_logistics_date toYYYYMMDD(logistics_time) TYPE minmax GRANULARITY 3,
    INDEX minmax_end_date toYYYYMMDD(end_time) TYPE minmax GRANULARITY 3
)
    ENGINE = ReplacingMergeTree(ch_modified)
        PARTITION BY toYYYYMM(create_time)
        ORDER BY (user_id, create_time, oid)
        SETTINGS index_granularity = 8192;
```

And only 1 row in it
```sql
INSERT INTO test_for_repro (oid, user_id, create_time, pay_time, logistics_time, end_time,
                                                ch_modified)
VALUES (4999999999999999999, 299999999999, '2021-09-30 16:30:00', '2021-09-30 16:30:00', '2021-09-30 16:30:00',
        '2021-09-30 16:30:00', '2021-11-04 10:18:13');
```

This sql success
```sql
select * from test_for_repro where pay_time is not null;
```
This sql success, too
```sql
select * from test_for_repro where create_time between '2021-09-30 15:30:00' and '2021-09-30 17:30:00';
```
This sql failure
```sql
select * from test_for_repro where pay_time between '2021-09-30 15:30:00' and '2021-09-30 17:30:00';
```
![image](https://user-images.githubusercontent.com/28568597/140445678-25d72bbd-035d-417f-97a9-7d92e54467e7.png)

The error mentions `'Nullable(UInt32)'`, but this table doesn't have a column of that type

**Comment by a747097587** [comment]
@den-crane  Sorry for bothering you, I added more specific information

**Comment by UnamedRus** [comment]
Problem in skip index:

```
ALTER TABLE test_for_repro  DROP INDEX minmax_pay_date;

SELECT *
FROM test_for_repro
WHERE (pay_time >= '2021-09-30 15:30:00') AND (pay_time <= '2021-09-30 17:30:00')

Query id: 77e50092-b317-4012-90be-742049b2b108

┌─────────────────oid─┬──────user_id─┬─────────create_time─┬────────────pay_time─┬──────logistics_time─┬────────────end_time─┬─────────ch_modified─┐
│ 4999999999999999999 │ 299999999999 │ 2021-09-30 16:30:00 │ 2021-09-30 16:30:00 │ 2021-09-30 16:30:00 │ 2021-09-30 16:30:00 │ 2021-11-04 10:18:13 │
└─────────────────────┴──────────────┴─────────────────────┴─────────────────────┴─────────────────────┴─────────────────────┴─────────────────────┘

```

**Comment by UnamedRus** [comment]
```
CREATE TABLE xxxx_null
(
    `ts` Nullable(DateTime)
)
ENGINE = MergeTree
ORDER BY toStartOfHour(ts)
SETTINGS allow_nullable_key = 1

INSERT INTO xxxx_null SELECT now();


SELECT *
FROM xxxx_null
WHERE ts > '2021-10-11 00:00:00'

Query id: 149ff83a-3e97-491f-aab0-4ebedd4e4d8d


0 rows in set. Elapsed: 0.008 sec.

Received exception from server (version 21.8.11):
Code: 43. DB::Exception: Received from localhost:9000. DB::Exception: Nested type Nullable(DateTime) cannot be inside Nullable type.
```

**Comment by alex-zaitsev** [comment]
This is broken between 21.8.7.22 and 21.8.8.29

**Comment by alex-zaitsev** [comment]
https://github.com/ClickHouse/ClickHouse/compare/v21.8.7.22-lts...v21.8.8.29-lts
Seems to be broken by https://github.com/ClickHouse/ClickHouse/pull/28636
cc @amosbird
