### ISSUE TITLE
FINAL keyword not work at JOIN queries

### ISSUE THREAD

**Issue by alexsubota** [ClickHouse/ClickHouse#31077]
FINAL keyword not work at JOIN queries.

Example:
```
CREATE table test_table
(
    ver       Int64,
    order_key String
)
    ENGINE = ReplacingMergeTree(ver)
        ORDER BY order_key;

insert into test_table
select 1, 'test value';
insert into test_table
select 1, 'test value';

select t1.*, t2.*
from (select 'test value' as order_key) t1
         join test_table t2 final
on t1.order_key = t2.order_key
```

Result:
![image](https://user-images.githubusercontent.com/4305175/140319926-d8c91d1d-48f1-48e4-a126-b10e8ff1510a.png)

Example with correct behavior:
```
select t1.*, t2.*
from (select 'test value' as order_key) t1
         join (select * from test_table final) t2 
             on t1.order_key = t2.order_key
```

Correct result:
![image](https://user-images.githubusercontent.com/4305175/140320106-b416829c-7767-40fc-bedf-f80558bac94d.png)

ClickHouse version: 21.8.5.7

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/8655
