### ISSUE TITLE
cannot build v19.11 For patch on ubuntu

### ISSUE THREAD

**Issue by huoarter** [ClickHouse/ClickHouse#31079]
> Make sure that `git diff` result is empty and you've just pulled fresh master. Try cleaning up cmake cache. Just in case, official build instructions are published here: https://clickhouse.yandex/docs/en/development/build/

**Operating system**
Ubuntu 20.04.2 LTS \n \l
Linux IIGS-A7983-L 4.4.0-19041-Microsoft #1151-Microsoft Thu Jul 22 21:05:00 PST 2021 x86_64 x86_64 x86_64 GNU/Linux
Windows subsystem Linux

**Cmake version**
cmake version 3.16.3
**Ninja version**
1.10.0
**Compiler name and version**
click
CC=clang-13
CXX=clang++-13
**Full cmake and/or ninja output**
---------------------------------------------------------cmake----------------------------------
-- Looking for strsep - found
-- Looking for timegm
-- Looking for timegm - found
-- Looking for arc4random_buf
-- Looking for arc4random_buf - not found
-- Looking for arc4random_uniform
-- Looking for arc4random_uniform - not found
-- Looking for explicit_bzero
-- Looking for explicit_bzero - found
-- Looking for getpagesize
-- Looking for getpagesize - found
-- Looking for timingsafe_bcmp
-- Looking for timingsafe_bcmp - not found
-- Looking for timingsafe_memcmp
-- Looking for timingsafe_memcmp - not found
-- Looking for memmem
-- Looking for memmem - found
-- Looking for include file err.h
-- Looking for include file err.h - found
-- Looking for clock_gettime in rt
-- Looking for clock_gettime in rt - found
-- Check size of time_t
-- Check size of time_t - done
-- Looking for C++ include initializer_list
-- Looking for C++ include initializer_list - found
-- Check if the system is big endian
-- Searching 16 bit integer
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Looking for byteswap.h
-- Looking for byteswap.h - found
-- Looking for sys/endian.h
-- Looking for sys/endian.h - not found
-- Looking for sys/mman.h
-- Looking for sys/mman.h - found
-- Looking for sys/resource.h
-- Looking for sys/resource.h - found
-- Looking for sys/time.h
-- Looking for sys/time.h - found
-- Looking for sys/uio.h
-- Looking for sys/uio.h - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for windows.h
-- Looking for windows.h - not found
-- Looking for zlibVersion in z
-- Looking for zlibVersion in z - found
-- Looking for lzo1x_1_15_compress in lzo2
-- Looking for lzo1x_1_15_compress in lzo2 - not found
-- Performing Test HAVE_VISUAL_STUDIO_ARCH_AVX
-- Performing Test HAVE_VISUAL_STUDIO_ARCH_AVX - Failed
-- Performing Test HAVE_VISUAL_STUDIO_ARCH_AVX2
-- Performing Test HAVE_VISUAL_STUDIO_ARCH_AVX2 - Failed
-- Performing Test HAVE_CLANG_MAVX
-- Performing Test HAVE_CLANG_MAVX - Success
-- Performing Test HAVE_CLANG_MBMI2
-- Performing Test HAVE_CLANG_MBMI2 - Success
-- Performing Test HAVE_BUILTIN_EXPECT
-- Performing Test HAVE_BUILTIN_EXPECT - Success
-- Performing Test HAVE_BUILTIN_CTZ
-- Performing Test HAVE_BUILTIN_CTZ - Success
-- Performing Test SNAPPY_HAVE_SSSE3
-- Performing Test SNAPPY_HAVE_SSSE3 - Success
-- Performing Test SNAPPY_HAVE_BMI2
-- Performing Test SNAPPY_HAVE_BMI2 - Failed
-- Looking for mmap
-- Looking for mmap - found
-- Looking for sysconf
-- Looking for sysconf - found
-- Looking for arpa/inet.h
-- Looking for arpa/inet.h - found
-- Looking for fcntl.h
-- Looking for fcntl.h - found
-- Looking for getopt.h
-- Looking for getopt.h - found
-- Looking for inttypes.h
-- Looking for inttypes.h - found
-- Looking for netdb.h
-- Looking for netdb.h - found
-- Looking for netinet/in.h
-- Looking for netinet/in.h - found
-- Looking for signal.h
-- Looking for signal.h - found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for sys/ioctl.h
-- Looking for sys/ioctl.h - found
-- Looking for sys/param.h
-- Looking for sys/param.h - found
-- Looking for sys/socket.h
-- Looking for sys/socket.h - found
-- Looking for sys/stat.h
-- Looking for sys/stat.h - found
-- Looking for sys/un.h
-- Looking for sys/un.h - found
-- Looking for poll.h
-- Looking for poll.h - found
-- Looking for sys/poll.h
-- Looking for sys/poll.h - found
-- Looking for sys/select.h
-- Looking for sys/select.h - found
-- Looking for sched.h
-- Looking for sched.h - found
-- Looking for string.h
-- Looking for string.h - found
-- Looking for strings.h
-- Looking for strings.h - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for gethostbyname_r
-- Looking for gethostbyname_r - found
-- Looking for strerror_r
-- Looking for strerror_r - found
-- Looking for sched_get_priority_max
-- Looking for sched_get_priority_max - found
-- Looking for sched_get_priority_min
-- Looking for sched_get_priority_min - found
-- Performing Test STRERROR_R_CHAR_P
-- Performing Test STRERROR_R_CHAR_P - Success
-- Using OpenSSL from /home/xuertao/ClickHouse/contrib/ssl
-- Looking for pthread_setaffinity_np in pthread
-- Looking for pthread_setaffinity_np in pthread - found
-- Performing Test HAVE_THREE_PARAM_SCHED_SETAFFINITY
-- Performing Test HAVE_THREE_PARAM_SCHED_SETAFFINITY - Success
-- Found PythonInterp: /usr/bin/python (found version "2.7.18")
-- checking compiler: CLANG
-- Looking for dladdr
-- Looking for dladdr - not found
-- Looking for nanosleep
-- Looking for nanosleep - found
-- Checking whether strerror_r returns an int
-- Checking whether strerror_r returns an int -- no
-- Performing Test ARCH_64_BIT
-- Performing Test ARCH_64_BIT - Success
-- Performing Test ARCH_32_BIT
-- Performing Test ARCH_32_BIT - Failed
-- Build type RELWITHDEBINFO
-- Boost version: 1.70.0
-- Build date: 2021-11-04
-- Looking for include file intrin.h
-- Looking for include file intrin.h - not found
-- Looking for C++ include intrin.h
-- Looking for C++ include intrin.h - not found
-- Looking for include file x86intrin.h
-- Looking for include file x86intrin.h - found
-- Looking for C++ include x86intrin.h
-- Looking for C++ include x86intrin.h - found
-- Looking for posix_memalign
-- Looking for posix_memalign - found
-- Looking for _aligned_malloc
-- Looking for _aligned_malloc - not found
-- Performing Test HAS_C_HIDDEN
-- Performing Test HAS_C_HIDDEN - Success
-- Performing Test HAS_CXX_HIDDEN
-- Performing Test HAS_CXX_HIDDEN - Success
-- Looking for _LIBCPP_VERSION
-- Looking for _LIBCPP_VERSION - found
-- generator is Ninja
-- Performing Test HAS_C_ATTR_IFUNC
-- Performing Test HAS_C_ATTR_IFUNC - Success
-- Performing Test HAVE_AVX512
-- Performing Test HAVE_AVX512 - Failed
-- Building without AVX512 support
-- Performing Test HAVE_CC_BUILTIN_ASSUME_ALIGNED
-- Performing Test HAVE_CC_BUILTIN_ASSUME_ALIGNED - Success
-- Performing Test HAVE_CXX_BUILTIN_ASSUME_ALIGNED
-- Performing Test HAVE_CXX_BUILTIN_ASSUME_ALIGNED - Success
-- Performing Test HAVE__BUILTIN_CONSTANT_P
-- Performing Test HAVE__BUILTIN_CONSTANT_P - Success
-- Performing Test C_FLAG_Wvla
-- Performing Test C_FLAG_Wvla - Success
-- Performing Test C_FLAG_Wpointer_arith
-- Performing Test C_FLAG_Wpointer_arith - Success
-- Performing Test C_FLAG_Wstrict_prototypes
-- Performing Test C_FLAG_Wstrict_prototypes - Success
-- Performing Test C_FLAG_Wmissing_prototypes
-- Performing Test C_FLAG_Wmissing_prototypes - Success
-- Performing Test CXX_FLAG_Wvla
-- Performing Test CXX_FLAG_Wvla - Success
-- Performing Test CXX_FLAG_Wpointer_arith
-- Performing Test CXX_FLAG_Wpointer_arith - Success
-- Performing Test CC_SELF_ASSIGN
-- Performing Test CC_SELF_ASSIGN - Success
-- Performing Test CXX_SELF_ASSIGN
-- Performing Test CXX_SELF_ASSIGN - Success
-- Performing Test CC_PAREN_EQUALITY
-- Performing Test CC_PAREN_EQUALITY - Success
-- Performing Test CXX_UNUSED_CONST_VAR
-- Performing Test CXX_UNUSED_CONST_VAR - Success
-- Performing Test CXX_IGNORED_ATTR
-- Performing Test CXX_IGNORED_ATTR - Success
-- Performing Test CXX_WEAK_VTABLES
-- Performing Test CXX_WEAK_VTABLES - Success
-- Performing Test CXX_MISSING_DECLARATIONS
-- Performing Test CXX_MISSING_DECLARATIONS - Success
-- Performing Test CXX_UNUSED_LOCAL_TYPEDEFS
-- Performing Test CXX_UNUSED_LOCAL_TYPEDEFS - Success
-- Performing Test CXX_WUNUSED_VARIABLE
-- Performing Test CXX_WUNUSED_VARIABLE - Success
-- Building for current host CPU:
-- Looking for mmap
-- Looking for mmap - found
-- Doxygen not found, unable to generate API reference
-- Sphinx not found, unable to generate developer reference
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- PCRE version 8.41 or above not found
-- PCRE 8.41 or above not found
-- Could not find libpcap - some examples will not be built
-- Link jemalloc: jemalloc
-- The ASM compiler identification is Clang
-- Found assembler: /usr/bin/clang-13
-- Looking for sys/random.h
-- Looking for sys/random.h - found
-- /home/xuertao/ClickHouse/utils: Have 5242 megabytes of memory. Limiting concurrent linkers jobs to 1 and compiler jobs to OFF
-- /home/xuertao/ClickHouse/dbms: Have 5242 megabytes of memory. Limiting concurrent linkers jobs to 1 and compiler jobs to 3
-- Will build ClickHouse 19.11.13.1 revision 54423
-- Using gperf=: GPERF-NOTFOUND
-- Using internal=OFF compiler=0: headers=/usr/share/clickhouse/headers/19.11.13.1 root=/usr/share/clickhouse/headers/19.11.13.1:  /usr/local/bin/clickhouse-clang  -fdiagnostics-color=always  -msse4.1 -msse4.2 -mpopcnt  -fno-omit-frame-pointer  -Wall -Wno-unused-command-line-argument  -Wnon-virtual-dtor -nostdinc++ -isystem /home/xuertao/ClickHouse/contrib/libcxx/include -isystem /home/xuertao/ClickHouse/contrib/libcxxabi/include -Wextra -Werror -Wpedantic -Wno-vla-extension -Wno-zero-length-array -Wno-gnu-anonymous-struct -Wno-nested-anon-types -Wshadow -Wshadow-uncaptured-local -Wextra-semi -Wcomma -Winconsistent-missing-destructor-override -Wunused-exception-parameter -Wcovered-switch-default -Wold-style-cast -Wrange-loop-analysis -Wunused-member-function -Wunreachable-code -Wunreachable-code-return -Wnewline-eof -Wembedded-directive -Wgnu-case-range -Wunused-macros -Wconditional-uninitialized -Wdeprecated -Wundef -Wreserved-id-macro -Wredundant-parens -Wzero-as-null-pointer-constant -Weverything -Wno-c++98-compat -Wno-c++98-compat-pedantic -Wno-padded -Wno-switch-enum -Wno-shadow-field-in-constructor -Wno-deprecated-dynamic-exception-spec -Wno-float-equal -Wno-weak-vtables -Wno-shift-sign-overflow -Wno-sign-conversion -Wno-conversion -Wno-exit-time-destructors -Wno-undefined-func-template -Wno-documentation-unknown-command -Wno-missing-variable-declarations -Wno-unused-template -Wno-global-constructors -Wno-c99-extensions -Wno-missing-prototypes -Wno-weak-template-vtables -Wno-zero-length-array -Wno-gnu-anonymous-struct -Wno-nested-anon-types -Wno-double-promotion -Wno-disabled-macro-expansion -Wno-vla-extension -Wno-vla -Wno-packed -Wno-return-std-move-in-c++11 -Wshadow-field -Wstring-plus-int -Wextra-semi-stmt -Wempty-init-stmt -Wno-ctad-maybe-unsupported -O2 -g -DNDEBUG -O3  -std=c++1z -x c++ -march=native -fPIC -fvisibility=hidden -fno-implement-inlines -Wno-unused-command-line-argument -Bprefix=/usr/share/clickhouse -nostdinc -nostdinc++ -isysroot=/usr/share/clickhouse/headers/19.11.13.1; clickhouse-lld
-- Looking for readpassphrase
-- Looking for readpassphrase - not found
-- Target check already exists
-- Configuring done
-- Generating done
-- Build files have been written to: /home/xuertao/ClickHouse/build
---------------------------------------------------------ninja-------------------------------------
$ ninja
[875/3790] Building C object contrib/hyperscan/CMakeFiles/hs_exec.dir/src/nfa/limex_simd512.c.o       [1044/3790] Building CXX object contrib/arrow-cma...ft/lib/cpp/src/thrift/TApplicationException.cpp.o
FAILED: contrib/arrow-cmake/CMakeFiles/thrift_static.dir/__/thrift/lib/cpp/src/thrift/TApplicationException.cpp.o
/usr/bin/clang++-13  -DARROW_WITH_LZ4 -DARROW_WITH_SNAPPY -DARROW_WITH_ZLIB -DARROW_WITH_ZSTD -Icontrib/arrow-cmake -isystem ../contrib/thrift/lib/cpp/src -isystem ../contrib/boost -fdiagnostics-color=always  -msse4.1 -msse4.2 -mpopcnt  -fno-omit-frame-pointer  -Wall -Wno-unused-command-line-argument  -Wnon-virtual-dtor -nostdinc++ -isystem /home/xuertao/ClickHouse/contrib/libcxx/include -isystem /home/xuertao/ClickHouse/contrib/libcxxabi/include -w -std=c++1z -O2 -g -DNDEBUG -O3    -std=c++14 -MD -MT contrib/arrow-cmake/CMakeFiles/thrift_static.dir/__/thrift/lib/cpp/src/thrift/TApplicationException.cpp.o -MF contrib/arrow-cmake/CMakeFiles/thrift_static.dir/__/thrift/lib/cpp/src/thrift/TApplicationException.cpp.o.d -o contrib/arrow-cmake/CMakeFiles/thrift_static.dir/__/thrift/lib/cpp/src/thrift/TApplicationException.cpp.o -c ../contrib/thrift/lib/cpp/src/thrift/TApplicationException.cpp
In file included from ../contrib/thrift/lib/cpp/src/thrift/TApplicationException.cpp:20:
In file included from ../contrib/thrift/lib/cpp/src/thrift/TApplicationException.h:23:
In file included from ../contrib/thrift/lib/cpp/src/thrift/Thrift.h:25:
In file included from ../contrib/thrift/lib/cpp/src/thrift/thrift-config.h:23:
contrib/arrow-cmake/thrift/config.h:1:1: error: cannot use dot operator on a type
../../../thrift/build/cmake/config.h.in
^
In file included from ../contrib/thrift/lib/cpp/src/thrift/TApplicationException.cpp:20:
In file included from ../contrib/thrift/lib/cpp/src/thrift/TApplicationException.h:23:
In file included from ../contrib/thrift/lib/cpp/src/thrift/Thrift.h:30:
/usr/include/x86_64-linux-gnu/sys/types.h:33:9: error: unknown type name '__u_char'
typedef __u_char u_char;
        ^
/usr/include/x86_64-linux-gnu/sys/types.h:34:9: error: unknown type name '__u_short'
typedef __u_short u_short;
        ^
/usr/include/x86_64-linux-gnu/sys/types.h:35:9: error: unknown type name '__u_int'
typedef __u_int u_int;
        ^
/usr/include/x86_64-linux-gnu/sys/types.h:36:9: error: unknown type name '__u_long'
typedef __u_long u_long;
        ^
/usr/include/x86_64-linux-gnu/sys/types.h:37:9: error: unknown type name '__quad_t'
typedef __quad_t quad_t;
        ^
/usr/include/x86_64-linux-gnu/sys/types.h:38:9: error: unknown type name '__u_quad_t'
typedef __u_quad_t u_quad_t;
        ^
/usr/include/x86_64-linux-gnu/sys/types.h:39:9: error: unknown type name '__fsid_t'
typedef __fsid_t fsid_t;
        ^
/usr/include/x86_64-linux-gnu/sys/types.h:42:9: error: unknown type name '__loff_t'
typedef __loff_t loff_t;
        ^
/usr/include/x86_64-linux-gnu/sys/types.h:47:9: error: unknown type name '__ino_t'
typedef __ino_t ino_t;
        ^
/usr/include/x86_64-linux-gnu/sys/types.h:54:9: error: unknown type name '__ino64_t'
typedef __ino64_t ino64_t;
        ^
/usr/include/x86_64-linux-gnu/sys/types.h:59:9: error: unknown type name '__dev_t'
typedef __dev_t dev_t;
        ^
/usr/include/x86_64-linux-gnu/sys/types.h:64:9: error: unknown type name '__gid_t'
typedef __gid_t gid_t;
        ^
/usr/include/x86_64-linux-gnu/sys/types.h:69:9: error: unknown type name '__mode_t'
typedef __mode_t mode_t;
        ^
/usr/include/x86_64-linux-gnu/sys/types.h:74:9: error: unknown type name '__nlink_t'
typedef __nlink_t nlink_t;
        ^
/usr/include/x86_64-linux-gnu/sys/types.h:79:9: error: unknown type name '__uid_t'
typedef __uid_t uid_t;
        ^
/usr/include/x86_64-linux-gnu/sys/types.h:97:9: error: unknown type name '__pid_t'
typedef __pid_t pid_t;
        ^
/usr/include/x86_64-linux-gnu/sys/types.h:103:9: error: unknown type name '__id_t'
typedef __id_t id_t;
        ^
/usr/include/x86_64-linux-gnu/sys/types.h:114:9: error: unknown type name '__daddr_t'
typedef __daddr_t daddr_t;
        ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
[1046/3790] Building CXX object contrib/arrow-cma...ic.dir/__/thrift/lib/cpp/src/thrift/TOutput.cpp.o
FAILED: contrib/arrow-cmake/CMakeFiles/thrift_static.dir/__/thrift/lib/cpp/src/thrift/TOutput.cpp.o
/usr/bin/clang++-13  -DARROW_WITH_LZ4 -DARROW_WITH_SNAPPY -DARROW_WITH_ZLIB -DARROW_WITH_ZSTD -Icontrib/arrow-cmake -isystem ../contrib/thrift/lib/cpp/src -isystem ../contrib/boost -fdiagnostics-color=always  -msse4.1 -msse4.2 -mpopcnt  -fno-omit-frame-pointer  -Wall -Wno-unused-command-line-argument  -Wnon-virtual-dtor -nostdinc++ -isystem /home/xuertao/ClickHouse/contrib/libcxx/include -isystem /home/xuertao/ClickHouse/contrib/libcxxabi/include -w -std=c++1z -O2 -g -DNDEBUG -O3    -std=c++14 -MD -MT contrib/arrow-cmake/CMakeFiles/thrift_static.dir/__/thrift/lib/cpp/src/thrift/TOutput.cpp.o -MF contrib/arrow-cmake/CMakeFiles/thrift_static.dir/__/thrift/lib/cpp/src/thrift/TOutput.cpp.o.d -o contrib/arrow-cmake/CMakeFiles/thrift_static.dir/__/thrift/lib/cpp/src/thrift/TOutput.cpp.o -c ../contrib/thrift/lib/cpp/src/thrift/TOutput.cpp
In file included from ../contrib/thrift/lib/cpp/src/thrift/TOutput.cpp:20:
In file included from ../contrib/thrift/lib/cpp/src/thrift/Thrift.h:25:
In file included from ../contrib/thrift/lib/cpp/src/thrift/thrift-config.h:23:
contrib/arrow-cmake/thrift/config.h:1:1: error: cannot use dot operator on a type
../../../thrift/build/cmake/config.h.in
^
In file included from ../contrib/thrift/lib/cpp/src/thrift/TOutput.cpp:20:
In file included from ../contrib/thrift/lib/cpp/src/thrift/Thrift.h:30:
/usr/include/x86_64-linux-gnu/sys/types.h:33:9: error: unknown type name '__u_char'
typedef __u_char u_char;
        ^
/usr/include/x86_64-linux-gnu/sys/types.h:34:9: error: unknown type name '__u_short'
typedef __u_short u_short;
        ^
/usr/include/x86_64-linux-gnu/sys/types.h:35:9: error: unknown type name '__u_int'
typedef __u_int u_int;
        ^
/usr/include/x86_64-linux-gnu/sys/types.h:36:9: error: unknown type name '__u_long'
typedef __u_long u_long;
        ^
/usr/include/x86_64-linux-gnu/sys/types.h:37:9: error: unknown type name '__quad_t'
typedef __quad_t quad_t;
        ^
/usr/include/x86_64-linux-gnu/sys/types.h:38:9: error: unknown type name '__u_quad_t'
typedef __u_quad_t u_quad_t;
        ^
/usr/include/x86_64-linux-gnu/sys/types.h:39:9: error: unknown type name '__fsid_t'
typedef __fsid_t fsid_t;
        ^
/usr/include/x86_64-linux-gnu/sys/types.h:42:9: error: unknown type name '__loff_t'
typedef __loff_t loff_t;
        ^
/usr/include/x86_64-linux-gnu/sys/types.h:47:9: error: unknown type name '__ino_t'
typedef __ino_t ino_t;
        ^
/usr/include/x86_64-linux-gnu/sys/types.h:54:9: error: unknown type name '__ino64_t'
typedef __ino64_t ino64_t;
        ^
/usr/include/x86_64-linux-gnu/sys/types.h:59:9: error: unknown type name '__dev_t'
typedef __dev_t dev_t;
        ^
/usr/include/x86_64-linux-gnu/sys/types.h:64:9: error: unknown type name '__gid_t'
typedef __gid_t gid_t;
        ^
/usr/include/x86_64-linux-gnu/sys/types.h:69:9: error: unknown type name '__mode_t'
typedef __mode_t mode_t;
        ^
/usr/include/x86_64-linux-gnu/sys/types.h:74:9: error: unknown type name '__nlink_t'
typedef __nlink_t nlink_t;
        ^
/usr/include/x86_64-linux-gnu/sys/types.h:79:9: error: unknown type name '__uid_t'
typedef __uid_t uid_t;
        ^
/usr/include/x86_64-linux-gnu/sys/types.h:97:9: error: unknown type name '__pid_t'
typedef __pid_t pid_t;
        ^
/usr/include/x86_64-linux-gnu/sys/types.h:103:9: error: unknown type name '__id_t'
typedef __id_t id_t;
        ^
/usr/include/x86_64-linux-gnu/sys/types.h:114:9: error: unknown type name '__daddr_t'
typedef __daddr_t daddr_t;
        ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
[1048/3790] Building CXX object contrib/arrow-cma...rift/lib/cpp/src/thrift/async/TAsyncChannel.cpp.o
FAILED: contrib/arrow-cmake/CMakeFiles/thrift_static.dir/__/thrift/lib/cpp/src/thrift/async/TAsyncChannel.cpp.o
/usr/bin/clang++-13  -DARROW_WITH_LZ4 -DARROW_WITH_SNAPPY -DARROW_WITH_ZLIB -DARROW_WITH_ZSTD -Icontrib/arrow-cmake -isystem ../contrib/thrift/lib/cpp/src -isystem ../contrib/boost -fdiagnostics-color=always  -msse4.1 -msse4.2 -mpopcnt  -fno-omit-frame-pointer  -Wall -Wno-unused-command-line-argument  -Wnon-virtual-dtor -nostdinc++ -isystem /home/xuertao/ClickHouse/contrib/libcxx/include -isystem /home/xuertao/ClickHouse/contrib/libcxxabi/include -w -std=c++1z -O2 -g -DNDEBUG -O3    -std=c++14 -MD -MT contrib/arrow-cmake/CMakeFiles/thrift_static.dir/__/thrift/lib/cpp/src/thrift/async/TAsyncChannel.cpp.o -MF contrib/arrow-cmake/CMakeFiles/thrift_static.dir/__/thrift/lib/cpp/src/thrift/async/TAsyncChannel.cpp.o.d -o contrib/arrow-cmake/CMakeFiles/thrift_static.dir/__/thrift/lib/cpp/src/thrift/async/TAsyncChannel.cpp.o -c ../contrib/thrift/lib/cpp/src/thrift/async/TAsyncChannel.cpp
In file included from ../contrib/thrift/lib/cpp/src/thrift/async/TAsyncChannel.cpp:20:
In file included from ../contrib/thrift/lib/cpp/src/thrift/async/TAsyncChannel.h:25:
In file included from ../contrib/thrift/lib/cpp/src/thrift/Thrift.h:25:
In file included from ../contrib/thrift/lib/cpp/src/thrift/thrift-config.h:23:
contrib/arrow-cmake/thrift/config.h:1:1: error: cannot use dot operator on a type
../../../thrift/build/cmake/config.h.in
^
In file included from ../contrib/thrift/lib/cpp/src/thrift/async/TAsyncChannel.cpp:20:
In file included from ../contrib/thrift/lib/cpp/src/thrift/async/TAsyncChannel.h:25:
In file included from ../contrib/thrift/lib/cpp/src/thrift/Thrift.h:37:
In file included from /home/xuertao/ClickHouse/contrib/libcxx/include/string:504:
In file included from /home/xuertao/ClickHouse/contrib/libcxx/include/string_view:175:
In file included from /home/xuertao/ClickHouse/contrib/libcxx/include/__string:57:
/home/xuertao/ClickHouse/contrib/libcxx/include/cstdio:108:9: error: no member named 'fpos_t' in the global namespace
using ::fpos_t;
      ~~^
/home/xuertao/ClickHouse/contrib/libcxx/include/cstdio:111:9: error: no member named 'fclose' in the global namespace
using ::fclose;
      ~~^
/home/xuertao/ClickHouse/contrib/libcxx/include/cstdio:112:9: error: no member named 'fflush' in the global namespace
using ::fflush;
      ~~^
/home/xuertao/ClickHouse/contrib/libcxx/include/cstdio:113:9: error: no member named 'setbuf' in the global namespace
using ::setbuf;
      ~~^
/home/xuertao/ClickHouse/contrib/libcxx/include/cstdio:114:9: error: no member named 'setvbuf' in the global namespace
using ::setvbuf;
      ~~^
/home/xuertao/ClickHouse/contrib/libcxx/include/cstdio:115:9: error: no member named 'fprintf' in the global namespace
using ::fprintf;
      ~~^
/home/xuertao/ClickHouse/contrib/libcxx/include/cstdio:116:9: error: no member named 'fscanf' in the global namespace
using ::fscanf;
      ~~^
/home/xuertao/ClickHouse/contrib/libcxx/include/cstdio:117:9: error: no member named 'snprintf' in the global namespace; did you mean 'swprintf'?
using ::snprintf;
      ~~^
/usr/include/wchar.h:590:12: note: 'swprintf' declared here
extern int swprintf (wchar_t *__restrict __s, size_t __n,
           ^
In file included from ../contrib/thrift/lib/cpp/src/thrift/async/TAsyncChannel.cpp:20:
In file included from ../contrib/thrift/lib/cpp/src/thrift/async/TAsyncChannel.h:25:
In file included from ../contrib/thrift/lib/cpp/src/thrift/Thrift.h:37:
In file included from /home/xuertao/ClickHouse/contrib/libcxx/include/string:504:
In file included from /home/xuertao/ClickHouse/contrib/libcxx/include/string_view:175:
In file included from /home/xuertao/ClickHouse/contrib/libcxx/include/__string:57:
/home/xuertao/ClickHouse/contrib/libcxx/include/cstdio:118:9: error: no member named 'sprintf' in the global namespace
using ::sprintf;
      ~~^
/home/xuertao/ClickHouse/contrib/libcxx/include/cstdio:119:9: error: no member named 'sscanf' in the global namespace
using ::sscanf;
      ~~^
/home/xuertao/ClickHouse/contrib/libcxx/include/cstdio:120:9: error: no member named 'vfprintf' in the global namespace
using ::vfprintf;
      ~~^
/home/xuertao/ClickHouse/contrib/libcxx/include/cstdio:121:9: error: no member named 'vfscanf' in the global namespace
using ::vfscanf;
      ~~^
/home/xuertao/ClickHouse/contrib/libcxx/include/cstdio:122:9: error: no member named 'vsscanf' in the global namespace
using ::vsscanf;
      ~~^
/home/xuertao/ClickHouse/contrib/libcxx/include/cstdio:123:9: error: no member named 'vsnprintf' in the global namespace; did you mean 'vswprintf'?
using ::vsnprintf;
      ~~^
/usr/include/wchar.h:611:12: note: 'vswprintf' declared here
extern int vswprintf (wchar_t *__restrict __s, size_t __n,
           ^
In file included from ../contrib/thrift/lib/cpp/src/thrift/async/TAsyncChannel.cpp:20:
In file included from ../contrib/thrift/lib/cpp/src/thrift/async/TAsyncChannel.h:25:
In file included from ../contrib/thrift/lib/cpp/src/thrift/Thrift.h:37:
In file included from /home/xuertao/ClickHouse/contrib/libcxx/include/string:504:
In file included from /home/xuertao/ClickHouse/contrib/libcxx/include/string_view:175:
In file included from /home/xuertao/ClickHouse/contrib/libcxx/include/__string:57:
/home/xuertao/ClickHouse/contrib/libcxx/include/cstdio:124:9: error: no member named 'vsprintf' in the global namespace
using ::vsprintf;
      ~~^
/home/xuertao/ClickHouse/contrib/libcxx/include/cstdio:125:9: error: no member named 'fgetc' in the global namespace; did you mean 'fgetwc'?
using ::fgetc;
      ~~^
/usr/include/wchar.h:726:15: note: 'fgetwc' declared here
extern wint_t fgetwc (__FILE *__stream);
              ^
In file included from ../contrib/thrift/lib/cpp/src/thrift/async/TAsyncChannel.cpp:20:
In file included from ../contrib/thrift/lib/cpp/src/thrift/async/TAsyncChannel.h:25:
In file included from ../contrib/thrift/lib/cpp/src/thrift/Thrift.h:37:
In file included from /home/xuertao/ClickHouse/contrib/libcxx/include/string:504:
In file included from /home/xuertao/ClickHouse/contrib/libcxx/include/string_view:175:
In file included from /home/xuertao/ClickHouse/contrib/libcxx/include/__string:57:
/home/xuertao/ClickHouse/contrib/libcxx/include/cstdio:126:9: error: no member named 'fgets' in the global namespace; did you mean 'fgetws'?
using ::fgets;
      ~~^
/usr/include/wchar.h:755:17: note: 'fgetws' declared here
extern wchar_t *fgetws (wchar_t *__restrict __ws, int __n,
                ^
In file included from ../contrib/thrift/lib/cpp/src/thrift/async/TAsyncChannel.cpp:20:
In file included from ../contrib/thrift/lib/cpp/src/thrift/async/TAsyncChannel.h:25:
In file included from ../contrib/thrift/lib/cpp/src/thrift/Thrift.h:37:
In file included from /home/xuertao/ClickHouse/contrib/libcxx/include/string:504:
In file included from /home/xuertao/ClickHouse/contrib/libcxx/include/string_view:175:
In file included from /home/xuertao/ClickHouse/contrib/libcxx/include/__string:57:
/home/xuertao/ClickHouse/contrib/libcxx/include/cstdio:127:9: error: no member named 'fputc' in the global namespace; did you mean 'fputwc'?
using ::fputc;
      ~~^
/usr/include/wchar.h:740:15: note: 'fputwc' declared here
extern wint_t fputwc (wchar_t __wc, __FILE *__stream);
              ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
[1053/3790] Building CXX object contrib/capnproto...capnp/CMakeFiles/capnpc.dir/compiler/parser.c++.o
ninja: build stopped: subcommand failed.

**Comment by filimonov** [comment]
To build old version you need to use older compilers. 

AFAIR it was build with gcc-8

**Comment by filimonov** [comment]
BTW: upgrade would be much better idea.

**Comment by huoarter** [comment]
> BTW: upgrade would be much better idea.
Yeah, Thanks
But the major version upgrade involves data compatibility issues, so it is not very fast.
I want to patch the old version with a bug fix : https://github.com/ClickHouse/ClickHouse/pull/9154

**Comment by huoarter** [comment]
> To build old version you need to use older compilers.
> 
> AFAIR it was build with gcc-8

Hi Brother:
Switch the gcc-8 ,the issuse is still exist. Can you help me .
          
[ninja.log](https://github.com/ClickHouse/ClickHouse/files/7476058/ninja.log)

**Comment by alexey-milovidov** [comment]
You need to build version 21.11 from master.

**Comment by huoarter** [comment]
> You need to build version 21.11.
One of my prod cluster is 19.11,i just want to fix a bug before upgrade .
