### ISSUE TITLE
Support more secure password storage

### ISSUE THREAD

**Issue by paulwouters** [ClickHouse/ClickHouse#31089]
Currently, the option to store a password is basically cleartext or sha256(passwprd). These are very weak.

It would be good to add a method like argon2 (RFC 9106) or PBKDF2 (older and weaker, but NIST compliant). Or to get something modern secure and still NIST compliant by using pbkdf2(argon2(password, ...)

**Comment by Bulat-Ziganshin** [comment]
I agree that it's an important feature, but it's far from core CH business. Can such functions be loaded from external .so files?

**Comment by alexey-milovidov** [comment]
> far from core CH business

Untrue :)

**Comment by alexey-milovidov** [comment]
We've implemented bcrypt, which is also an obsolete algorithm, but suitable for the purpose.
Video: https://www.youtube.com/watch?v=o8Gj1ClU71M
Presentation: https://presentations.clickhouse.com/release_23.5/
PR: #44905

**Comment by alexey-milovidov** [comment]
@paulwouters 
PS. If you want to also add Argon2 it will be wonderful!
