### ISSUE TITLE
Local join table doesn't rewrite right distributed table.

### ISSUE THREAD

**Issue by abel-cheng** [ClickHouse/ClickHouse#31099]
**Describe the unexpected behaviour**
1. Create a ditributed table on cluster default first.
Create a clickhouse cluster of more than two nodes.
Distribute table ddl:
`create table test.local (id Int32, name String, dtm Int32)  ENGINE = MergeTree PARTITION BY dtm ORDER BY id;`
`create table test.distribute as test.local engine=Distributed(default,test,local,rand()); `

2. use clickhouse-client with debug level
`clickhouse-client -m --send_logs_level=debug`

3. use local join to query distributed table
`select * from test.distribute a 
inner join 
test.distribute b on a.id = b.id 
settings distributed_product_mode='local', prefer_localhost_replica=0;`

4. Local join does't rewrite right table.
`[MacBook-Pro.local] 2021.11.05 15:25:59.215899 [ 7028989 ] {7efc41c7-1658-4365-90c8-b14cadb395f8} <Debug> executeQuery: (from [::1]:62877, initial_query_id: a6318daa-b516-47cc-b676-77c4e7b16ada) SELECT a.id, a.name, a.dtm, b.id, b.name, b.dtm FROM test.local AS a ALL INNER JOIN test.distribute AS b ON a.id = b.id
[MacBook-Pro.local] 2021.11.05 15:25:59.215975 [ 7026143 ] {fc6d29b7-1faf-44b3-8bf1-f60bf4f59cb9} <Debug> executeQuery: (from [::1]:62876, initial_query_id: a6318daa-b516-47cc-b676-77c4e7b16ada) SELECT a.id, a.name, a.dtm, b.id, b.name, b.dtm FROM test.local AS a ALL INNER JOIN test.distribute AS b ON a.id = b.id`
We can see test.distribute is not rewrite to test.local.

**Expected behavior**
    Right distributed table should be rewrite to local table in local join.

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/25809
