### ISSUE TITLE
s3-style URL does not work.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#31093]
**Describe the issue**

This works successfully:
```
aws s3 cp 'hits.csv' 's3://milovidov-clickhouse-test/hits.csv'
```

This does not:
```
SELECT count() FROM s3('s3://milovidov-clickhouse-test/hits.csv', '...', '...', 'CSV', 'WatchID UInt64, JavaEnable UInt8, Title String, GoodEvent Int16, EventTime DateTime, EventDate Date, CounterID UInt32, ClientIP UInt32, RegionID UInt32, UserID UInt64, CounterClass Int8, OS UInt8, UserAgent UInt8, URL String, Referer String, Refresh UInt8, RefererCategoryID UInt16, RefererRegionID UInt32, URLCategoryID UInt16, URLRegionID UInt32, ResolutionWidth UInt16, ResolutionHeight UInt16, ResolutionDepth UInt8, FlashMajor UInt8, FlashMinor UInt8, FlashMinor2 String, NetMajor UInt8, NetMinor UInt8, UserAgentMajor UInt16, UserAgentMinor FixedString(2), CookieEnable UInt8, JavascriptEnable UInt8, IsMobile UInt8, MobilePhone UInt8, MobilePhoneModel String, Params String, IPNetworkID UInt32, TraficSourceID Int8, SearchEngineID UInt16, SearchPhrase String, AdvEngineID UInt8, IsArtifical UInt8, WindowClientWidth UInt16, WindowClientHeight UInt16, ClientTimeZone Int16, ClientEventTime DateTime, SilverlightVersion1 UInt8, SilverlightVersion2 UInt8, SilverlightVersion3 UInt32, SilverlightVersion4 UInt16, PageCharset String, CodeVersion UInt32, IsLink UInt8, IsDownload UInt8, IsNotBounce UInt8, FUniqID UInt64, OriginalURL String, HID UInt32, IsOldCounter UInt8, IsEvent UInt8, IsParameter UInt8, DontCountHits UInt8, WithHash UInt8, HitColor FixedString(1), LocalEventTime DateTime, Age UInt8, Sex UInt8, Income UInt8, Interests UInt16, Robotness UInt8, RemoteIP UInt32, WindowName Int32, OpenerName Int32, HistoryLength Int16, BrowserLanguage FixedString(2), BrowserCountry FixedString(2), SocialNetwork String, SocialAction String, HTTPError UInt16, SendTiming UInt32, DNSTiming UInt32, ConnectTiming UInt32, ResponseStartTiming UInt32, ResponseEndTiming UInt32, FetchTiming UInt32, SocialSourceNetworkID UInt8, SocialSourcePage String, ParamPrice Int64, ParamOrderID String, ParamCurrency FixedString(3), ParamCurrencyID UInt16, OpenstatServiceName String, OpenstatCampaignID String, OpenstatAdID String, OpenstatSourceID String, UTMSource String, UTMMedium String, UTMCampaign String, UTMContent String, UTMTerm String, FromTag String, HasGCLID UInt8, RefererHash UInt64, URLHash UInt64, CLID UInt32')
```

It argues about the URL:

```
Code: 36. DB::Exception: Bucket or key name are invalid in S3 URI. (BAD_ARGUMENTS)
```

But I'm using the same URL as with `s3 aws` tool :(

**Comment by alexey-milovidov** [comment]
Because it should also know about the region.
This works: https://s3.us-east-2.amazonaws.com/milovidov-clickhouse-test/hits.csv

**Comment by alexey-milovidov** [comment]
We have the possibility to specify default region in configuration,
then `s3://milovidov-clickhouse-test/hits.csv` style URLs should work.

**Comment by alexey-milovidov** [comment]
We can easily determine the region by:

`curl http://169.254.169.254/latest/meta-data/placement/region`

**Comment by alexey-milovidov** [comment]
One issue is that there is a place for s3-related settings for DiskS3 (see DiskS3Settings and config examples), but these settings are not applied to table function s3 and StorageS3.

But they should be applicable as well. Let's allow to specify them in some global place in config (as the default) and in SETTINGS for table engine.

And this is all to add a setting `default_region_from_url`.

**Comment by alexey-milovidov** [comment]
We should have a configuration for schema-to-domain mapping, with hardcoded defaults:

```
s3 -> s3.amazonaws.com
gs -> ...
oss -> ...
cos -> ...
```

**Comment by xiedeyantu** [comment]
I am working on this issue.

**Comment by alexey-milovidov** [comment]
@xiedeyantu are you still working on this issue?

**Comment by cameronmoten** [comment]
Had this same issue; 

When using a R2 - S3 emulation URL it detects it as invalid. It seems it used to work in the past, https://blog.qryn.dev/cloudflare-r2-clickhouse so something must've changed recently. 

`
throw Exception(ErrorCodes::BAD_ARGUMENTS, "Bucket or key name are invalid in S3 URI.");`

**Comment by cameronmoten** [comment]
Testing with the URL from the Example "https://abcdefghi.r2.cloudflarestorage.com/somebucket" it also breaks with that exception. So anyone who had it working before when they update clickhouse will have their server stop working.

**Comment by cameronmoten** [comment]
as a workaround if anyone else has this issue for the R2 one at least.

"https://abcdefghi.r2.cloudflarestorage.com/somebucket" 
-->
"https://abcdefghi.r2.cloudflarestorage.com/somebucket/fakekey/" seems to solve it.

**Comment by alexey-milovidov** [comment]
Implement a global server configuration:

```
<url_scheme_mappers>
    <s3>
        <from>s3://{bucket}/</from>
        <to>https://{bucket}.s3.amazonaws.com/</to>
    </s3>
    ...
</url_scheme_mappers>
```

also, this form can be used as a shortcut:

```
<url_scheme_mappers>
    <s3>
        <domain>s3.amazonaws.com</domain>
    </s3>
    ...
</url_scheme_mappers>
```

It will be applied for both `s3`, `gcs`, and `url` functions and engines.
The code will extract the scheme from the URL, check for available mappers, and if a mapper is present, apply the rewrite rule.

**Comment by alexey-milovidov** [comment]
Also a question - why the S3 SDK by itself does not support the s3-style URLs? Maybe it does, but we missed it?

**Comment by jackgray** [comment]
Is there any solution for Min.IO? What about allowing any S3 url format? `http://10.1.1.1:9000/bucket ` does not work for me but seems like if allowed the rest would work since it's the same API

**Comment by jackgray** [comment]
Leaving this here for anyone using Min.IO or other non-aws S3 brought here by this error: https://clickhouse.com/docs/en/integrations/minio

**Comment by FelipeLema** [comment]
I'm having trouble using `url_scheme_mappers` along with `named_collections`. Can anyone point me to a MWE?
This is what I have, which doesn't seem to be working (censored private info)

docker-compose.yml:
```
version: "3.7"
services:
  database:
    image: clickhouse/clickhouse-server:23.12.3.40
    env_file:
      - .env
    ports:
      - 9090:9090
      - 8123:8123
      - 9444:9444
      - 2181:2181
    environment:
      # note: user must match ./dev-server-users.d/users.xml
      CLICKHOUSE_USER: my_clickhouse_user
      CLICKHOUSE_PASSWORD: my_password
      CLICKHOUSE_DB: ${DB_NAME}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    volumes:
      - clickhouse-data:/var/lib/clickhouse/
      - ./server-config.d:/etc/clickhouse-server/config.d/
      - ./server-users.d/users.xml:/etc/clickhouse-server/users.d/ts-users.xml:ro
    ulimits:
      nofile:
          soft: 262144
          hard: 262144
  minio:
    image: minio/minio
    command: server --console-address ":9001" /data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minio_root_user
      MINIO_ROOT_PASSWORD: minio_root_password
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - minio-data:/data


volumes:
  clickhouse-data:
  minio-data:
```

server-config.d/collections.xml
```
<clickhouse>
  <named_collections>
    <my_collection>
      <url>minio://my-bucket/my-directory/**.csv</url>
      <access_key_id from_env="AWS_ACCESS_KEY_ID"></access_key_id>
      <secret_access_key from_env="AWS_SECRET_ACCESS_KEY"></secret_access_key>
    </my_collection>
  </named_collections>

  <url_scheme_mappers>
    <minio>
      <to>http://minio:9000/{bucket}/</to>
    </minio>
  </url_scheme_mappers>
</clickhouse>
```
