### ISSUE TITLE
Timeout to modify a large table field like(Session expired) 

### ISSUE THREAD

**Issue by Sallery-X** [ClickHouse/ClickHouse#31098]
version: 21.3-lts

the sql: alter table touchstone_hourly_local on cluster default modify column pos_package_id Int64;

Received exception from server (version 21.3.5):
Code: 999. DB::Exception: Received from host:9000. DB::Exception: Session expired (Session expired).

**Comment by den-crane** [comment]
Can you provide fragments from clickhouse-server.log around the exception?
Can you provide fragments from zookeeper logs around the exception?
Can you provide steps to reproduce?

**Comment by tavplubix** [comment]
No information provided
