### ISSUE TITLE
Importing unix millis with DateTime64(3) from CSV inverts milliseconds digits

### ISSUE THREAD

**Issue by comunidadio** [ClickHouse/ClickHouse#31096]
**Describe the unexpected behaviour**
Timestamps are imported _almost_ correctly, except milliseconds got inverted digits (eg. ".007" not ".700)

**How to reproduce**
* Which ClickHouse server version to use
21.10

* Queries to run that lead to unexpected result

Add CSV testcase file in user_files folder:

```
/var/lib/clickhouse/user_files$ cat testcase_datetime64.csv 
1612137595007,1612137595007
1612137595372,1612137595372
1612137596959,1612137596959
1612137598570,1612137598570
```

Then query from it:

`SELECT timestamp,fromUnixTimestamp64Milli(fromunix) as correct,fromunix FROM file('/var/lib/clickhouse/user_files/testcase_datetime64.csv', 'CSV', 'timestamp DateTime64(3), fromunix Int64');
`

results in:
2021-01-31 23:59:55.700 | 2021-01-31 23:59:55.007 │ 1612137595007
2021-01-31 23:59:55.273 │ 2021-01-31 23:59:55.372 │ 1612137595372
2021-01-31 23:59:56.959 │ 2021-01-31 23:59:56.959 │ 1612137596959
2021-01-31 23:59:58.075 │ 2021-01-31 23:59:58.570 │ 1612137598570

Notice how the first column is _almost_ correct.... except milliseconds are somehow inverted, eg. 007 becomes 700 or 372 becomes 273... row #3 ends up correct because milliseconds are 959 so inverting 959 looks the same.

**Expected behavior**
DateTime64(3) from CSV should have correct values as per fromUnixTimestamp64Milli.

**Comment by comunidadio** [comment]
Probably introduced as part of #21053

**Comment by den-crane** [comment]
@comunidadio  why do you think that this format `1612137595007` is supported for ingestion?

**Comment by comunidadio** [comment]
@den-crane Check out #21053, scaled integers are supported according to that PR...

Also, if it weren't supported the behaviour certainly should not be this... either it would be be imported as a year far in the future (1000x seconds) or it would just be rejected as invalid.

**Comment by comunidadio** [comment]
Looking at the merged PR #21053 - it's interesting that the testcases ended in 222, so the inversion was invisible in tests (as per my initial .959 test above).

From testcase in PR:
SELECT toDateTime64('1111111111222', 3)
2005-03-18 01:58:31.222 

Using 921 milliseconds instead of 222 shows the problem clearly:
SELECT toDateTime64('1111111111921', 3)
2005-03-18 01:58:31.129

**Comment by UnamedRus** [comment]
Duplicate https://github.com/ClickHouse/ClickHouse/issues/28694

**Comment by comunidadio** [comment]
To rule out it's not merely a display bug, tried this roundtrip testcase:

```
SELECT toUnixTimestamp64Milli(toDateTime64('1111111111921', 3));
1111111111129
```

**Comment by filimonov** [comment]
https://github.com/ClickHouse/ClickHouse/pull/32240 ?

**Comment by UnamedRus** [comment]
Fixed

```

SELECT toDateTime64('1111111111921', 3)

Query id: d1628bdb-b8fd-4ecd-989f-ad65f873ee9d

┌─toDateTime64('1111111111921', 3)─┐
│          2005-03-18 01:58:31.921 │
└──────────────────────────────────┘
```
