### ISSUE TITLE
 Is there  such function：encodeURLComponent?

### ISSUE THREAD

**Issue by lichong2005** [ClickHouse/ClickHouse#31092]
there is the function : decodeURLComponent ,why not encodeURLComponent?

**Comment by melvynator** [comment]
For reference this is the behaviour of the decodeURLComponent: https://clickhouse.com/docs/en/sql-reference/functions/url-functions/#decodeurlcomponenturl

**Comment by zzsmdfj** [comment]
I will try to fix it
