### ISSUE TITLE
when use  row_number() throw exception

### ISSUE THREAD

**Issue by long1208** [ClickHouse/ClickHouse#31100]
> You have to provide the following information whenever possible.

when i select table use 

select fstruniquekey, fuiuid, (row_number() over(order by fstruniquekey desc) - 1) as fuigroupindex from test_merge_kd_user_label_info where ((((fuidaydiff_kyjd_last_refuse_td>=90 and fuidaydiff_kyjd_last_refuse_td<=360)) AND (fstrcnt_to_repay_mainloan_kdser_irr36=0) AND (fstrrefuse_type_lst_reject='E')) AND not (((fuidatediffs_lst_send>=1 and fuidatediffs_lst_send<=3)))) AND ((fstris_blacklist_reg_channel_all='0')) order by fstruniquekey desc;

> A clear and concise description of what works not as it is supposed to.

[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

**Enable crash reporting**

> If possible, change "enabled" to true in "send_crash_reports" section in `config.xml`:

```
<send_crash_reports>
        <!-- Changing <enabled> to true allows sending crash reports to -->
        <!-- the ClickHouse core developers team via Sentry https://sentry.io -->
        <enabled>false</enabled>
```

**How to reproduce**

* Which ClickHouse server version to use
* 21.10.2.15
* Which interface to use, if matters
* clickhouse-cli shell

**Expected behavior**
can use

> A clear and concise description of what you expected to happen.

**Error message and/or stacktrace**
eceived exception from server (version 21.10.2):
Code: 47. DB::Exception: Received from 127.0.0.1:9100. DB::Exception: Unknown identifier: row_number() OVER (ORDER BY fstruniquekey DESC); there are columns: not(and(greaterOrEquals(fuidatediffs_lst_send, 1), lessOrEquals(fuidatediffs_lst_send, 3))), and(greaterOrEquals(fuidatediffs_lst_send, 1), lessOrEquals(fuidatediffs_lst_send, 3)), lessOrEquals(fuidatediffs_lst_send, 3), 3, 3, greaterOrEquals(fuidatediffs_lst_send, 1), equals(fstrrefuse_type_lst_reject, 'E'), fstrrefuse_type_lst_reject, fuidatediffs_lst_send, equals(fstrcnt_to_repay_mainloan_kdser_irr36, 0), 1, 1, 0, 0, fstrcnt_to_repay_mainloan_kdser_irr36, and(equals(fstrcnt_to_repay_mainloan_kdser_irr36, 0), equals(fstrrefuse_type_lst_reject, 'E'), not(and(greaterOrEquals(fuidatediffs_lst_send, 1), lessOrEquals(fuidatediffs_lst_send, 3)))), 'E', 'E', fstruniquekey, fuiuid, fstris_blacklist_reg_channel_all, fuidaydiff_kyjd_last_refuse_td, 90, 90, greaterOrEquals(fuidaydiff_kyjd_last_refuse_td, 90), 360, 360, lessOrEquals(fuidaydiff_kyjd_last_refuse_td, 360), '0', '0', equals(fstris_blacklist_reg_channel_all, '0'), and(greaterOrEquals(fuidaydiff_kyjd_last_refuse_td, 90), lessOrEquals(fuidaydiff_kyjd_last_refuse_td, 360), equals(fstris_blacklist_reg_channel_all, '0')), and(and(equals(fstrcnt_to_repay_mainloan_kdser_irr36, 0), equals(fstrrefuse_type_lst_reject, 'E'), not(and(greaterOrEquals(fuidatediffs_lst_send, 1), lessOrEquals(fuidatediffs_lst_send, 3)))), and(greaterOrEquals(fuidaydiff_kyjd_last_refuse_td, 90), lessOrEquals(fuidaydiff_kyjd_last_refuse_td, 360), equals(fstris_blacklist_reg_channel_all, '0'))): While processing fstruniquekey, fuiuid, row_number() OVER (ORDER BY fstruniquekey DESC) - 1 AS fuigroupindex. (UNKNOWN_IDENTIFIER)

> If applicable, add screenshots to help explain your problem.

**Additional context**

> Add any other context about the problem here.

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/19857
