### ISSUE TITLE
The clickhouse groupBitmapAnd function calculation result is 0?

### ISSUE THREAD

**Issue by DavidZ1** [ClickHouse/ClickHouse#31102]
Ck tables schema (Local +  Distributed):

`CREATE TABLE test.tag_all_device_bitmap_local ( `tag_name` String , `tag_value` String, `device_bitmap` AggregateFunction(groupBitmap, UInt32), `dt` String ) ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/tag_all_device_bitmap_local', '{replica}') PARTITION BY dt ORDER BY (tag_name, tag_value) TTL parseDateTimeBestEffort(dt) + toIntervalDay(7) SETTINGS index_granularity = 8192, storage_policy = 'ssd'`

`CREATE TABLE test.tag_all_device_bitmap ( `tag_name` String , `tag_value` String , `device_bitmap` AggregateFunction(groupBitmap, UInt32) , `dt` String ) ENGINE = Distributed('ck_cluster', 'test', 'tag_all_device_bitmap_local', rand())`

CK version :

```
SELECT version()

Query id: 1c6395d4-ecf8-48e1-ac2b-7bf3b2c8fde4

Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 21.7.7 revision 54449.

┌─version()─┐
│ 21.7.7.1  │
└───────────┘
```

query ck table of bitmap ,but some query return 0 ，for this sql:

```
SELECT groupBitmapAnd(device_bitmap)
FROM test.tag_all_device_bitmap
WHERE (dt = '20211101') AND (tag_name IN ('fo618')) AND (tag_value IN ('1912'))

Query id: 2b3bcd34-cd2d-4c17-acd9-7768086e00c4

┌─groupBitmapAnd(device_bitmap)─┐
│                             0 │
└───────────────────────────────┘
```

but I check this query data, bitmap has value:

```
SELECT bitmapCardinality(device_bitmap)
FROM test.tag_all_device_bitmap
WHERE (dt = '20211101') AND (tag_name IN ('fo618')) AND (tag_value IN ('1912'))

Query id: 7c584c97-2d40-4c4e-bbb2-0f2795313694

┌─bitmapCardinality(device_bitmap)─┐
│                        175018957 │
└──────────────────────────────────┘




SELECT bitmapToArray(device_bitmap)
FROM test.tag_all_device_bitmap
WHERE (dt = '20211101') AND (tag_name IN ('fo618')) AND (tag_value IN ('1912'))

Query id: f9857dce-8b04-49e6-9708-8e6a6391e48b

┌─bitmapToArray(device_bitmap)───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ [5,8,9,13,14,20,22,26,34,40,46,49,59,64,69,71,72,73,75,76,77,78,84,86,89,90,93,95,97,98,101,104,111,114,119,121,122,123,127,133,141,142,146,158,161,168,172,174,177,181,183,185,189,193,195,200,201,204,208,210,211,222,223,224,225,229⋯│
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘


SELECT
    bitmapMax(device_bitmap),
    bitmapMin(device_bitmap)
FROM test.tag_all_device_bitmap
WHERE (dt = '20211101') AND (tag_name IN ('fo618')) AND (tag_value IN ('1912'))

Query id: e4b8d497-c5c4-4cc2-a7ce-fe9d5ca6a1c8

                                                                                                                     ┌─bitmapMax(device_bitmap)─┬─bitmapMin(device_bitmap)─┐
│               1149507995 │                        5 │
└──────────────────────────┴──────────────────────────┘
```

When I use a subquery, I can return the correct result，I do not know why？

```
SELECT groupBitmapAnd(device_bitmap)
FROM
(
    SELECT device_bitmap
    FROM hive_advert.ads_dmp_user_tag_all_device_bitmap
    WHERE (dt = '20211101') AND (tag_name IN ('fo618')) AND (tag_value IN ('1912'))
)

Query id: 7a2a8cf3-a34f-41a3-8f40-7250e4d242d1

┌─groupBitmapAnd(device_bitmap)─┐
│                     175018957 │
└───────────────────────────────┘
```

**Comment by UnamedRus** [comment]
> groupBitmapAnd

Will return non-zero answer only if all rows from this query will have at least 1 common value in their bitmaps.

```
SELECT device_bitmap
FROM test.tag_all_device_bitmap
WHERE (dt = '20211101') AND (tag_name IN ('fo618')) AND (tag_value IN ('1912'))
```


>     FROM hive_advert.ads_dmp_user_tag_all_device_bitmap

>    FROM test.tag_all_device_bitmap

Different tables.

**Comment by DavidZ1** [comment]
I may say one less condition, when it has only one record：

```

SELECT count(1)
FROM test.tag_all_device_bitmap
WHERE (dt = '20211101') AND (tag_name IN ('fo618')) AND (tag_value IN ('1912'));

Query id: e923ec1b-23ab-4a45-9238-fa8ef0b91510

┌─count()─┐
│       1 │
└─────────┘
```


When groupBitmapAnd processes this record, the result returned is 0，but use subquery can return non-zero，So i can't understand，As follows：

```
# 1）Direct query：

SELECT groupBitmapAnd(device_bitmap)
FROM test.tag_all_device_bitmap
WHERE (dt = '20211101') AND (tag_name IN ('fo618')) AND (tag_value IN ('1912'))

Query id: 2b3bcd34-cd2d-4c17-acd9-7768086e00c4

┌─groupBitmapAnd(device_bitmap)─┐
│                             0 │
└───────────────────────────────┘


# 2）Nested query

SELECT groupBitmapAnd(device_bitmap)
FROM
(
    SELECT device_bitmap
    FROM hive_advert.ads_dmp_user_tag_all_device_bitmap
    WHERE (dt = '20211101') AND (tag_name IN ('fo618')) AND (tag_value IN ('1912'))
)

Query id: 7a2a8cf3-a34f-41a3-8f40-7250e4d242d1

┌─groupBitmapAnd(device_bitmap)─┐
│                     175018957 │
└───────────────────────────────┘

```


At the same time I use the clickhouse official website example:
 https://clickhouse.com/docs/en/sql-reference/aggregate-functions/reference/groupbitmapand/

When groupBitmapAnd processes this record, the result returned is not-zero, As follows:


```

DROP TABLE IF EXISTS bitmap_column_expr_test2

Query id: 48bd321e-9fbf-4e32-8c7e-d27e305a8238

Ok.

0 rows in set. Elapsed: 0.002 sec. 



CREATE TABLE bitmap_column_expr_test2
(
    `tag_id` String,
    `z` AggregateFunction(groupBitmap, UInt32)
)
ENGINE = MergeTree
ORDER BY tag_id

Query id: 26ca47d6-ddaf-4a46-b3a1-a70dde383294

Ok.

0 rows in set. Elapsed: 0.003 sec. 

INSERT INTO bitmap_column_expr_test2 VALUES

Query id: 79d9e823-b38d-4e56-84be-5e265d9b18ae

Ok.

1 rows in set. Elapsed: 0.004 sec. 

SELECT groupBitmapAnd(z)  FROM bitmap_column_expr_test2  WHERE tag_id = 'tag1'

Query id: 87ab64a4-f5e1-4e89-a934-9fd6d7a0afda

┌─groupBitmapAnd(z)─┐
│                10 │
└───────────────────┘

1 rows in set. Elapsed: 0.004 sec. 



INSERT INTO bitmap_column_expr_test2 VALUES

Query id: db45eafb-4878-444e-ac0a-c7cd6f5d1a63

Ok.

1 rows in set. Elapsed: 0.004 sec. 



INSERT INTO bitmap_column_expr_test2 VALUES

Query id: 934ace08-ee8e-4bd1-9874-a29b98064282

Ok.

1 rows in set. Elapsed: 0.004 sec. 




SELECT groupBitmapAnd(z)
FROM bitmap_column_expr_test2
WHERE tag_id IN ('tag1', 'tag2')

Query id: 439c362b-df87-46d6-be8a-7b56f81a115e

┌─groupBitmapAnd(z)─┐
│                 1 │
└───────────────────┘

1 rows in set. Elapsed: 0.004 sec. 




SELECT groupBitmapAnd(z)
FROM bitmap_column_expr_test2
WHERE tag_id IN ('tag1', 'tag3')

Query id: eecd973e-22a9-4903-aeec-05464af150ff

┌─groupBitmapAnd(z)─┐
│                 0 │
└───────────────────┘

1 rows in set. Elapsed: 0.004 sec. 




```


Through the above test, I can understand that groupBitmapAnd may have some problems in processing a single record。

**Comment by alesapin** [comment]
Cannot reproduce on current stable 21.10:
```
CREATE TABLE bitmap_column_expr_test2                                                                                                                                                                                                         
(                                                                                                                                                                                                                                             
    `tag_id` String,                                                                                                                                                                                                                          
    `z` AggregateFunction(groupBitmap, UInt32)                                                                                                                                                                                                
)                                                                                                                                                                                                                                             
ENGINE = MergeTree                                                                                                                                                                                                                            
ORDER BY tag_id                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                              
Ok.                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
0 rows in set. Elapsed: 0.012 sec.                                                                                                                                                                                                            
                                                                                                                                                                                                                                              
:) INSERT INTO bitmap_column_expr_test2 VALUES ('tag1', bitmapBuild(cast([1,2,3,4,5,6,7,8,9,10] as Array(UInt32))));                                                                                                
                                                                                                                                                                                                                                              
INSERT INTO bitmap_column_expr_test2 VALUES                                                                                                                                                                                                   
                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                              
Ok.                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
1 rows in set. Elapsed: 0.027 sec.                                                                                                                                                                                                            
                                                                                                                                                                                                                                              
:) INSERT INTO bitmap_column_expr_test2 VALUES ('tag2', bitmapBuild(cast([6,7,8,9,10,11,12,13,14,15] as Array(UInt32))));                                                                                           

INSERT INTO bitmap_column_expr_test2 VALUES

Ok.

1 rows in set. Elapsed: 0.008 sec.

:) INSERT INTO bitmap_column_expr_test2 VALUES ('tag3', bitmapBuild(cast([2,4,6,8,10,12] as Array(UInt32))));

INSERT INTO bitmap_column_expr_test2 VALUES

Ok.

1 rows in set. Elapsed: 0.008 sec.

:) SELECT groupBitmapAnd(z)  FROM bitmap_column_expr_test2  WHERE tag_id = 'tag1'

SELECT groupBitmapAnd(z)
FROM bitmap_column_expr_test2
WHERE tag_id = 'tag1'

┌─groupBitmapAnd(z)─┐
│                10 │
└───────────────────┘

1 rows in set. Elapsed: 0.019 sec.

:) SELECT groupBitmapAnd(z)
:-] FROM bitmap_column_expr_test2
:-] WHERE tag_id IN ('tag1', 'tag2')

SELECT groupBitmapAnd(z)
FROM bitmap_column_expr_test2
WHERE tag_id IN ('tag1', 'tag2')

┌─groupBitmapAnd(z)─┐
│                 5 │
└───────────────────┘

1 rows in set. Elapsed: 0.018 sec.

:) SELECT groupBitmapAnd(z)
:-] FROM bitmap_column_expr_test2
:-] WHERE tag_id IN ('tag1', 'tag3')

SELECT groupBitmapAnd(z)
FROM bitmap_column_expr_test2
WHERE tag_id IN ('tag1', 'tag3')

┌─groupBitmapAnd(z)─┐
│                 5 │
└───────────────────┘

1 rows in set. Elapsed: 0.026 sec.
```

`tag1` has 10 bits set. `tag1` AND `tag2` has 5 common bits. `tag1` and `tag3` has 5 common bits. So it works as expected. 

Also it looks like you are using custom build, we don't have version 21.7.7.1, our official is https://github.com/ClickHouse/ClickHouse/releases/tag/v21.7.7.47-stable (21.7.7.47).

**Comment by DavidZ1** [comment]
thx, Okay, let’s test it with a higher version.

**Comment by DavidZ1** [comment]
We tested it with the official version 21.7.7.47 that you recommended, and this problem still occurs.

But it seems to have discovered a phenomenon, I don’t know if it is a hidden bug.

The official example is a single table, not a distributed table plus a local table。

So we can reproduce it .

```

CREATE TABLE bitmap_column_expr_test2_local ON CLUSTER ck_cluster
(
    `tag_id` String,
    `z` AggregateFunction(groupBitmap, UInt32)
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/bitmap_column_expr_test2_local', '{replica}')
ORDER BY tag_id
SETTINGS index_granularity = 8192, storage_policy = 'hotdata'

Query id: d72d4943-a6c0-4c4f-b594-50850b6461fd

6 rows in set. Elapsed: 0.273 sec. 


CREATE TABLE IF NOT EXISTS bitmap_column_expr_test2 ON CLUSTER ck_cluster AS bitmap_column_expr_test2_local
ENGINE = Distributed('ck_cluster', 'default', 'bitmap_column_expr_test2_local', rand())

Query id: 44c0c7aa-c8fe-4fab-8adf-330e43104927

6 rows in set. Elapsed: 0.265 sec. 



INSERT INTO bitmap_column_expr_test2 VALUES ('tag1', bitmapBuild(cast([1,2,3,4,5,6,7,8,9,10] as Array(UInt32))));

Query id: 2f80833b-4eb7-40a3-a2ed-20d6d93be9ef

Ok.

1 rows in set. Elapsed: 0.005 sec. 



SELECT count(1)
FROM bitmap_column_expr_test2

Query id: 87ecbc20-13cd-474e-98ce-18b0600559b9

┌─count()─┐
│       1 │
└─────────┘

1 rows in set. Elapsed: 0.189 sec. 




SELECT groupBitmapAnd(z)
FROM bitmap_column_expr_test2
WHERE tag_id LIKE 'tag%'

Query id: 7d5fc1ec-64c0-4e25-871d-4eeaa7dac0d3

┌─groupBitmapAnd(z)─┐
│                 0 │
└───────────────────┘

1 rows in set. Elapsed: 0.008 sec. 



SELECT groupBitmapAnd(z)
FROM
(
    SELECT z
    FROM bitmap_column_expr_test2
    WHERE tag_id LIKE 'tag%'
)

Query id: 80cd6402-be78-4721-a701-eb4448399cf7

┌─groupBitmapAnd(z)─┐
│                10 │
└───────────────────┘

1 rows in set. Elapsed: 0.010 sec. 





#query local table in data node

SELECT groupBitmapAnd(z)
FROM bitmap_column_expr_test2_local
WHERE tag_id LIKE 'tag%'

Query id: 18eb55c7-687a-4a41-a536-1e40315a5341

┌─groupBitmapAnd(z)─┐
│                10 │
└───────────────────┘


```


In summary, we can not be sure that when there is only one  bitmap data record in the local table , when we go to query, bitmapand returns 0, we cannot be sure if this is a bug.

And we tested it on the official version of 21.7.7.47 and 21.11.2.2 respectively, and the results are the same as above.

**Comment by DavidZ1** [comment]
Can anyone answer？

**Comment by dmthuc** [comment]
I know the problem, I will submit MR soon

**Comment by DavidZ1** [comment]
ok，thx~

**Comment by dmthuc** [comment]
> Cannot reproduce on current stable 21.10:
> 
> ```
> CREATE TABLE bitmap_column_expr_test2                                                                                                                                                                                                         
> (                                                                                                                                                                                                                                             
>     `tag_id` String,                                                                                                                                                                                                                          
>     `z` AggregateFunction(groupBitmap, UInt32)                                                                                                                                                                                                
> )                                                                                                                                                                                                                                             
> ENGINE = MergeTree                                                                                                                                                                                                                            
> ORDER BY tag_id                                                                                                                                                                                                                                                                                                                                                                                                                                                              
>                                                                                                                                                                                                                                               
> Ok.                                                                                                                                                                                                                                           
>                                                                                                                                                                                                                                               
> 0 rows in set. Elapsed: 0.012 sec.                                                                                                                                                                                                            
>                                                                                                                                                                                                                                               
> :) INSERT INTO bitmap_column_expr_test2 VALUES ('tag1', bitmapBuild(cast([1,2,3,4,5,6,7,8,9,10] as Array(UInt32))));                                                                                                
>                                                                                                                                                                                                                                               
> INSERT INTO bitmap_column_expr_test2 VALUES                                                                                                                                                                                                   
>                                                                                                                                                                                                                                              
>                                                                                                                                                                                                                                               
> Ok.                                                                                                                                                                                                                                           
>                                                                                                                                                                                                                                               
> 1 rows in set. Elapsed: 0.027 sec.                                                                                                                                                                                                            
>                                                                                                                                                                                                                                               
> :) INSERT INTO bitmap_column_expr_test2 VALUES ('tag2', bitmapBuild(cast([6,7,8,9,10,11,12,13,14,15] as Array(UInt32))));                                                                                           
> 
> INSERT INTO bitmap_column_expr_test2 VALUES
> 
> Ok.
> 
> 1 rows in set. Elapsed: 0.008 sec.
> 
> :) INSERT INTO bitmap_column_expr_test2 VALUES ('tag3', bitmapBuild(cast([2,4,6,8,10,12] as Array(UInt32))));
> 
> INSERT INTO bitmap_column_expr_test2 VALUES
> 
> Ok.
> 
> 1 rows in set. Elapsed: 0.008 sec.
> 
> :) SELECT groupBitmapAnd(z)  FROM bitmap_column_expr_test2  WHERE tag_id = 'tag1'
> 
> SELECT groupBitmapAnd(z)
> FROM bitmap_column_expr_test2
> WHERE tag_id = 'tag1'
> 
> ┌─groupBitmapAnd(z)─┐
> │                10 │
> └───────────────────┘
> 
> 1 rows in set. Elapsed: 0.019 sec.
> 
> :) SELECT groupBitmapAnd(z)
> :-] FROM bitmap_column_expr_test2
> :-] WHERE tag_id IN ('tag1', 'tag2')
> 
> SELECT groupBitmapAnd(z)
> FROM bitmap_column_expr_test2
> WHERE tag_id IN ('tag1', 'tag2')
> 
> ┌─groupBitmapAnd(z)─┐
> │                 5 │
> └───────────────────┘
> 
> 1 rows in set. Elapsed: 0.018 sec.
> 
> :) SELECT groupBitmapAnd(z)
> :-] FROM bitmap_column_expr_test2
> :-] WHERE tag_id IN ('tag1', 'tag3')
> 
> SELECT groupBitmapAnd(z)
> FROM bitmap_column_expr_test2
> WHERE tag_id IN ('tag1', 'tag3')
> 
> ┌─groupBitmapAnd(z)─┐
> │                 5 │
> └───────────────────┘
> 
> 1 rows in set. Elapsed: 0.026 sec.
> ```
> 
> `tag1` has 10 bits set. `tag1` AND `tag2` has 5 common bits. `tag1` and `tag3` has 5 common bits. So it works as expected.
> 
> Also it looks like you are using custom build, we don't have version 21.7.7.1, our official is https://github.com/ClickHouse/ClickHouse/releases/tag/v21.7.7.47-stable (21.7.7.47).

Hi alesapin, I found out that it has problem with Distributed table. I've submit a PR. But I can not run the CI test. Can you look at my PR to see if my fix are correct?
