### ISSUE TITLE
Problem with hdfs integration

### ISSUE THREAD

**Issue by rkozlo** [ClickHouse/ClickHouse#31107]
Hi,
I am trying to integrate ch with hdfs and have some problems. First problem is with connecting to kerberos. Here is my config for hdfs:
`<yandex>

    <hdfs>
        <hadoop_kerberos_keytab>/etc/clickhouse-server/xxx@xx.xx.keytab</hadoop_kerberos_keytab>
        <hadoop_kerberos_principal>xxx@xx.xx</hadoop_kerberos_principal>
        <hadoop_security_authentication>kerberos</hadoop_security_authentication>
        <hadoop_security_kerberos_ticket_cache_path>/tmp/chtic</hadoop_security_kerberos_ticket_cache_path>
        <hadoop_security_kerberos_ticket_cache_path>/tmp</hadoop_security_kerberos_ticket_cache_path>
    </hdfs>

    <hdfs_dedicatedcachepath>
        <hadoop_security_kerberos_ticket_cache_path>/tmp</hadoop_security_kerberos_ticket_cache_path>
    </hdfs_dedicatedcachepath> 
</yandex>`

With this config i get error
`Code: 210. DB::Exception: Received from localhost:9000. DB::Exception: Unable to connect to HDFS: AccessControlException: Failed to evaluate challenge: GSSAPI error in client while negotiating security context in gss_init_sec_context() in SASL library.  This is most likely due insufficient credentials or malicious interactions.. (NETWORK_ERROR)`
I handled the error manually by adding this line to the config:
`<hadoop_kerberos_kinit_command>true</hadoop_kerberos_kinit_command>`
And now queries seems to be working but with empty result. On clickhouse 21.3 version there was no useful infos in logs, installed 21.9 on separate host and now I can see this in logs:
`2021.11.05 15:21:17.327058 [ 4622 ] {0f9419ca-ec0e-4911-b970-8bd03589d312} <Warning> StorageHDFS: No file in HDFS matches the path: hdfs://namenode-1.hadoop.xxxx.xxx.xx:8020/user/xxx/test_chtable1`
I have checked on hdfs, file exists, user has privileges to this file. Tried creating new one with different format and still its the same. 
What is weird that insert seems to be working.

Connecting by giving hostname, through nameservice, to hdfs engine table, directly to host without hdfs engine table still the same result. I have done everything based on [documentation](https://clickhouse.com/docs/en/engines/table-engines/integrations/hdfs/)
I would appreciate any ideas what is going on here. Didn't find anyone reporting such problems.

The same problem with 21.11
Hdfs 2.6

**Comment by Evil-LLC** [comment]
I have the same. HDFS3, ClickHouse 24.1. Problem exists since early 23.x.

**Comment by alexey-milovidov** [comment]
We don't support HDFS.

**Comment by deathalt** [comment]
https://clickhouse.com/docs/en/engines/table-engines/integrations/hdfs

So what about remove it from your documentation?

**Comment by ilejn** [comment]
> I have the same. HDFS3, ClickHouse 24.1. Problem exists since early 23.x. Also I get this in Hadoop logs: `2024-02-13 12:50:03,251 INFO org.apache.hadoop.hdfs.server.datanode.DataNode: Failed to read expected SASL data transfer protection handshake from client at /xx.xx.xx.xx:59920. Perhaps the client is running an older version of Hadoop which does not support SASL data transfer protection org.apache.hadoop.hdfs.protocol.datatransfer.sasl.InvalidMagicNumberException: Received 1c50a0 instead of deadbeef from client. at org.apache.hadoop.hdfs.protocol.datatransfer.sasl.SaslDataTransferServer.doSaslHandshake(SaslDataTransferServer.java:374) at org.apache.hadoop.hdfs.protocol.datatransfer.sasl.SaslDataTransferServer.getSaslStreams(SaslDataTransferServer.java:308) at org.apache.hadoop.hdfs.protocol.datatransfer.sasl.SaslDataTransferServer.receive(SaslDataTransferServer.java:135) at org.apache.hadoop.hdfs.server.datanode.DataXceiver.run(DataXceiver.java:235) at java.lang.Thread.run(Thread.java:750)`

Does "Problem exists since early 23.x" mean that it had Ok worked before 23.x?

As far as I can see, your circumstances match known limitation
==
 Note that due to libhdfs3 limitations only old-fashioned approach is supported, datanode communications are not secured by SASL (HADOOP_SECURE_DN_USER is a reliable indicator of such security approach). Use tests/integration/test_storage_kerberized_hdfs/hdfs_configs/bootstrap.sh for reference.
 ==
