### ISSUE TITLE
IDiskRemote should use DiskPtr to handle the file system operations

### ISSUE THREAD

**Issue by LiuYangkuan** [ClickHouse/ClickHouse#31117]
In class IDiskRemote, all metadata file system operations use os file system api directly.
There is little extendiability if we want store the metadata of HDFS or S3 into distributed file system.
So I suggest change this way by using DiskPtr and will propose a pull request.

In addition, metadata of HDFS or S3 only store local FS which is not sharable.

**Comment by alexey-milovidov** [comment]
> In class IDiskRemote, all metadata file system operations use os file system api directly.
There is little extendiability if we want store the metadata of HDFS or S3 into distributed file system.
So I suggest change this way by using DiskPtr and will propose a pull request.

Let's do that.

> metadata of HDFS or S3 only store local FS which is not sharable

Yes, we need a mode with shared metadata.
I remember there is some knob to store both shared and local metadata...

**Comment by LiuYangkuan** [comment]
I'm sorry to remove assignment by mistake, please assign again @alexey-milovidov
