### ISSUE TITLE
system.tables - Querying "engine_full" hangs

### ISSUE THREAD

**Issue by yoavo-datricks** [ClickHouse/ClickHouse#31127]
Hello,
After upgrding to CH 21.10.2.15 we noticed a significant decrease in querying the "engine_full" column in the system.tables table.

**How to reproduce**
SELECT
	name,
	engine_full,
	engine,
	partition_key,
	sorting_key,
	primary_key,
	sampling_key
FROM system.tables
FORMAT TabSeparatedWithNamesAndTypes;

* Which ClickHouse server version to use
Compare 21.10.2.15 to 21.8.3.44

* Which interface to use, if matters
Any, we used clickhouse-client, SQLAlchemy and DBeaver

Since we use SQLAlchemy reflection in our Python code this is very important for us.
Thanks!

**Comment by den-crane** [comment]
Can you provide `select count() from system.tables` and 

```sql
set send_logs_level='trace';

SELECT
name,
engine_full,
engine,
partition_key,
sorting_key,
primary_key,
sampling_key
FROM system.tables format Null;

SELECT
name,
engine_full,
engine,
partition_key,
sorting_key,
primary_key,
sampling_key
FROM system.tables
FORMAT TabSeparatedWithNamesAndTypes;
```

**Comment by yoavo-datricks** [comment]
1. 218 rows
2. Read 218 rows, 25.82 KiB in 44.273188412 sec., 4 rows/sec., 597.20 B/sec. 0 rows in set. Elapsed: 44.274 sec.
3. Read 218 rows, 25.82 KiB in 60.927188387 sec., 3 rows/sec., 433.96 B/sec. 218 rows in set. Elapsed: 60.929 sec.

**Comment by den-crane** [comment]
>Can't provide complete output

No info. Closed.
