### ISSUE TITLE
How to process map with duplicated keys

### ISSUE THREAD

**Issue by taiyang-li** [ClickHouse/ClickHouse#31126]
**Describe the issue**
Currently data type map allow duplicated keys, which may be confusing for many users. 

**How to reproduce**
``` sql
SELECT
    map(1, 2, 1, 3, 3, 4) AS a,
    a[1]

Query id: 109bf467-4fff-459f-a6a9-8b8692f2bb26

┌─a─────────────┬─arrayElement(map(1, 2, 1, 3, 3, 4), 1)─┐
│ {1:2,1:3,3:4} │                                      2 │
└───────────────┴────────────────────────────────────────┘

1 rows in set. Elapsed: 0.002 sec. 
```

**Expected behavior**
Map should not allow duplicated keys. 
When creating map with `map` function, the later key/value pair should override previous kv pair with the same key. 
When get keys using `mapKeys` function, CH should return uniq keys.
When get values using `mapValues` function, CH should return latest values correspond to uniq keys.

**Comment by Aliyumuhammad** [comment]
Aliyumuhammad

**Comment by taiyang-li** [comment]
No one ever reply. Let's close it .
