### ISSUE TITLE
system.tables times out after upgrade to 21.10

### ISSUE THREAD

**Issue by felicity-iz** [ClickHouse/ClickHouse#31130]
(you don't have to strictly follow this form)

**Describe the situation**
querying system tables times out takes up to 3min.

**How to reproduce**
run this query:
SELECT
	name,
	engine_full,
	engine,
	partition_key,
	sorting_key,
	primary_key,
	sampling_key
FROM
	system.tables
WHERE
	database = 'xxx' 	
FORMAT TabSeparatedWithNamesAndTypes
* Which ClickHouse server version to use
* 21.10
* Which interface to use, if matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to slow performance

**Expected performance**
What are your performance expectation, why do you think they are realistic? Has it been working faster in older ClickHouse releases? Is it working faster in some specific other system?

**Additional context**

**Comment by felicity-iz** [comment]
its specifically the engine_full column that is slow to query, all other columns are fast.

**Comment by felicity-iz** [comment]
same for create_table_query. is it possible that these columns have become virtual again?

**Comment by alexey-milovidov** [comment]
It was changed long time ago, long before version 21.10.
Most likely won't be fixed... just avoid `SELECT * FROM system.tables`.

**Comment by felicity-iz** [comment]
its inbuild sqlalchemy can't really avoid that query

**Comment by den-crane** [comment]
_To be more precise: After upgrading from 21.8 to 21.10 selecting the column 'engine_full' from system.tables becomes very slow and times out.
Any idea why and what can be done to improve performance?_

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/31127

**Comment by alexey-milovidov** [comment]
If it's changed after 21.8, it is more suspicious.
What types of tables cause long selecting of the `engine_full` column?

**Comment by felicity-iz** [comment]
its specifically engine_full and create_table_query. Are some of the columns read from different places? for example engine_full from disk?

**Comment by den-crane** [comment]
>  engine_full and create_table_query

Yes, engine_full and create_table_query, is read from disk / mysql and it's slow, total_rows, total_bytes also slow.
Other columns from memory, and they are faster.
