### ISSUE TITLE
Engine URL - should not discard inserts in case unreachable http server

### ISSUE THREAD

**Issue by adubovikov** [ClickHouse/ClickHouse#31141]
> (you don't have to strictly follow this form)

In case you create a material view that writes data to an external table with ENGINE URL, you can have loss if your http server is unreachable

> A clear and concise description of what is the intended usage scenario is.

CREATE TABLE main (x String) ENGINE = Memory

insert into main (x) VALUES ('test string 01')

select * from main;

SELECT *
FROM main

┌─x──────────────┐
│ test string 01 │
└────────────────┘

CREATE TABLE main_url
(
    x String
)
ENGINE = URL('http://127.0.0.1:9998/', 'JSON')

# port 9998 is not open!

CREATE MATERIALIZED VIEW main_mv TO main_url
(
    x String
) AS SELECT x FROM main

insert into main (x) VALUES ('test string 02')

Code: 1000. DB::Exception: Received from localhost:9000. DB::Exception: Connection refused. 

select * from main;

SELECT *
FROM main

┌─x──────────────┐
│ test string 01 │
└────────────────┘

1 rows in set. Elapsed: 0.004 sec.

> A clear and concise description of what you want to happen.

in case you have URL Engine type and the destination IP/port is unreachable  - the error class should be in warning level and should not discard inserts to the main table.

**Comment by UnamedRus** [comment]
Related https://github.com/ClickHouse/ClickHouse/issues/21721

**Comment by adubovikov** [comment]
yeah, similar request

**Comment by alexey-milovidov** [comment]
Let's consolidate this task with #35837.
