### ISSUE TITLE
Live extending single node clickhouse install to multi-node cluster

### ISSUE THREAD

**Issue by zabiralov** [ClickHouse/ClickHouse#31162]
Hello, folks

I have a single ch node with continuously updating data inside. Total data size is about 1.7 Tb. Also, I have an empty CH cluster with 3 nodes and Zookeeper cluster in separate machines. Does any way to extend single node with data, or merge it with 3-nodes cluster, without stop writing new data to single node? As I can see in documentation for clickhouse-copier, for consistent copy, the source data must be stable with no changes during the copy process. May be, there are a some way to connect single node to the cluster and start some "data rebalance" on it?

Thanks!

**Comment by den-crane** [comment]
Everything is possible.

You can convert a table at your single ch node to Replicated table https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/replication/#converting-from-mergetree-to-replicatedmergetree as a shard=1

Then add more shards / replicas / Distributed tables, switch ingestion to distributed tables.
Then manually move/spread some old partitions from shard=1 to other shards.
