### ISSUE TITLE
execution order of my sql query  is unexpected

### ISSUE THREAD

**Issue by DataScientistSamChan** [ClickHouse/ClickHouse#31161]
**Unexpected behavior**

Clickhouse executes my query in an unexpected order

**How to reproduce**

1. create a table
CREATE TABLE debug
(
    `reporttime` String
)
ENGINE = Log

2. insert 2 rows
insert into debug values ('1636375447020'), ('DE');

3. run query(expected)
SELECT toDateTime(floor(toInt64(reporttime) / 1000)) as payTime FROM debug where startsWith(toString(reporttime),'16')

And you get 
┌─────────────payTime─┐
│ 2021-11-08 20:44:07 │
└─────────────────────┘

4. run another query(unexpected)
SELECT * from (SELECT toDateTime(floor(toInt64(reporttime) / 1000)) as payTime FROM debug where startsWith(toString(reporttime),'16')) t WHERE "payTime" >= toDateTime('2021-11-01 00:00:00')

And the error comes up

Received exception from server (version 21.4.6):
Code: 6. DB::Exception: Received from localhost:9000. DB::Exception: Cannot parse string 'DE' as Int64: syntax error at begin of string. Note: there are toInt64OrZero and toInt64OrNull functions, which returns zero/NULL instead of throwing exception.: while executing 'FUNCTION toInt64(reporttime :: 0) -> toInt64(reporttime) Int64 : 5'. 

**Expected behavior**
The field `reporttime` is actually the unix epoch. And by the first query, I filtered out some malformed string which is not a valid unix epoch, leaving me the valid one, which is `2021-11-08 20:44:07`. Then, I ran the second query which just filtered the first query to get out the epoch greater than `toDateTime('2021-11-01 00:00:00')`. Which should not gives me error, and return `2021-11-08 20:44:07`, but as it happened, the error came up.

**Comment by den-crane** [comment]
This the expected behaviour.
The query optimizer makes a predicate pushdown.

Better to use toInt64OrZero/toInt64OrNull instead of toDateTime.

You can disable pushdown or trick optimizer.

```sql
SELECT *
FROM
(
    SELECT toDateTime(floor(toInt64(reporttime) / 1000)) AS payTime
    FROM debug
    WHERE startsWith(toString(reporttime), '16')
    LIMIT 1000000000000000
) AS t
WHERE payTime >= toDateTime('2021-11-01 00:00:00')
┌─────────────payTime─┐
│ 2021-11-08 12:44:07 │
└─────────────────────┘
```

**Comment by DataScientistSamChan** [comment]
![image](https://user-images.githubusercontent.com/18599494/140853990-340d2bb5-1428-464b-90cf-9cd6c28be281.png)

I knew that the query optimizer made a predicate pushdown. But, the problem is, this optimization changed the semantics. So is there a problem with this predicate pushdown?

**Comment by den-crane** [comment]
>But, the problem is, this optimization changed the semantics.

SQL is a declarative language. Using SQL you describe a result not an algorithm.
Predicate pushdown optimization has not changed a result.
