### ISSUE TITLE
can clickhouse-local create persistent tables?

### ISSUE THREAD

**Issue by mikeTWC1984** [ClickHouse/ClickHouse#31163]
Can clickhouse-local  create persistent databases/tables or read existing ones (created by clickhouse-server)? It's not clear from docs if it possible or not.

**Comment by Algunenano** [comment]
You can use `remote()` to connect to running server. For example:

```
$ clickhouse-local --query "Select name from remote('127.0.0.1:9000', 'system.databases') limit 10"
INFORMATION_SCHEMA
d_063b96
d_0f0c56
d_0fd162
d_110d52
d_123845
d_140235
d_18d4f5
d_191524
d_191ff2
```

I would not recommend trying to access the data directories directly.

**Comment by mikeTWC1984** [comment]
Thanks @Algunenano 
I was thinking more about using it in kinda "sqlite" mode. Just realized those tables would require some background work, so then I guess the short answer is no.

**Comment by alexey-milovidov** [comment]
Yes, it's possible to create persistent tables.
By default clickhouse-local is using some subdirectory in `/tmp` for working path.
If you create a table (like MergeTree table) it will be created there.

But you can also override path by one of the following ways:
- create a config.xml / config.yml file similar to clickhouse-server's one; you can put it in the current directory or specify its path in `--config-file` command line parameter;
- specify the path with `-- --path ...` command line parameter (config overrides after `--`).

**Comment by alexey-milovidov** [comment]
The default database for clickhouse-local is storing metadata (table definitions) in memory.
But you can create more databases in clickhouse-local as well.

**Comment by alexey-milovidov** [comment]
You can load, access and modify clickhouse-server's data as well. But mind the following:
- clickhouse-server must be stopped before doing that;
- you have to check and correct files ownership (or run `clickhouse-local` under `clickhouse` user).

**Comment by mikeTWC1984** [comment]
Thanks @alexey-milovidov 
If I try to feed config.xml to clickhouse-local I always getting below error:
```
DB::Exception: Settings profile `default` not found. (THERE_IS_NO_PROFILE)
```
I tried both default config.xml and dummy config (just  ```<yandex></yandex>```)

If I use "--path" I'm getting " unrecognized option" error. Can you share a complete example of using it?

**Comment by mikeTWC1984** [comment]
I'm using yandex/clickhouse-server:21.10.2-alpine for testing

**Comment by alexey-milovidov** [comment]
This works:
```
clickhouse-local --query "CREATE TABLE test (x UInt8) ENGINE = MergeTree ORDER BY x" --path=.
```

**Comment by mikeTWC1984** [comment]
strange, I keep getting this (running your command in yandex/clickhouse-server:21.10.2-alpine )
```
bash-5.1# clickhouse-local --query "CREATE TABLE test (x UInt8) ENGINE = MergeTree ORDER BY x" --path=.
```
std::exception. Code: 1001, type: boost::wrapexcept<boost::program_options::unknown_option>, e.what() = unrecognised option '--path=.', Stack trace (when copying this message, always include the lines below):

0. boost::program_options::error_with_option_name::error_with_option_name(boost::program_options::error_with_option_name const&) @ 0x954cef9 in /usr/bin/clickhouse
1. boost::wrapexcept<boost::exception_detail::remove_error_info_injector<boost::program_options::unknown_option>::type> boost::exception_detail::enable_both<boost::program_options::unknown_option>(boost::program_options::unknown_option const&) @ 0x13f2a8c4 in /usr/bin/clickhouse
2. void boost::throw_exception<boost::program_options::unknown_option>(boost::program_options::unknown_option const&) @ 0x13f27b00 in /usr/bin/clickhouse
3. boost::program_options::detail::cmdline::finish_option(boost::program_options::basic_option<char>&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&, std::__1::vector<boost::function1<std::__1::vector<boost::program_options::basic_option<char>, std::__1::allocator<boost::program_options::basic_option<char> > >, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&>, std::__1::allocator<boost::function1<std::__1::vector<boost::program_options::basic_option<char>, std::__1::allocator<boost::program_options::basic_option<char> > >, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&> > > const&) @ 0x13f273fb in /usr/bin/clickhouse
4. boost::program_options::detail::cmdline::run() @ 0x13f20410 in /usr/bin/clickhouse
5. boost::program_options::basic_command_line_parser<char>::run() @ 0x9547ed0 in /usr/bin/clickhouse
6. DB::LocalServer::init(int, char**) @ 0x9581f5c in /usr/bin/clickhouse
7. mainEntryClickHouseLocal(int, char**) @ 0x9584c0a in /usr/bin/clickhouse
8. main @ 0x94465be in /usr/bin/clickhouse
9. __libc_start_main @ 0x270b3 in /lib/libc.so.6
10. _start @ 0x940ec2e in /usr/bin/clickhouse
 (version 21.10.2.15 (official build))

**Comment by kssenii** [comment]
in 21.10 `-- --path` should work instead of just `--path`.
The behaviour was changed here https://github.com/ClickHouse/ClickHouse/pull/30053 (since 21.11), but for some reason was marked as `not for changelog`, probably need to change to `backward incompatible change`.

**Comment by kssenii** [comment]
Tested your case - the problem exists only if you use default database, so as a temporary solution try creating tables in a non-default database, then it should work. The fact that it does not work with the default database is a bug.

**Comment by kssenii** [comment]
@leriel, after reading the code I am not sure if it is a bug that a default database does not persist tables with --path option while using non-default database allows to make persistent tables. I opened a very old code branch and it is still treats default database as DatabaseMemory regardless of the path parameter: https://github.com/ClickHouse/ClickHouse/blob/68ed4eee255816504906ef0d9785a36e5ef96bd6/programs/local/LocalServer.cpp#L272-L278
So I suggest using non-default database, then tables will be persistent with --path.

**Comment by leriel** [comment]
@kssenii Thanks a lot! Can confirm that with non default database clickhouse local can properly read tables when used with `--path`

**Comment by alexey-milovidov** [comment]
The behavior is expected. The default database of clickhouse-local is using the `Memory` engine that does not persist the `.sql` metadata files.

**Comment by danthegoodman1** [comment]
Seems that `--path` is no longer present at least in version `21.3.20.1` (latest docker image at the time)

**Comment by arctica** [comment]
Using the current version, I've tried with a non-default database and path set to current directory, I'm facing the same issue that data is persisted to disk but tables are not loaded when restarting the process and cannot be re-created as the files already exist.

`./clickhouse local -d foo -- --path=.`

Looking at the `system.databases` table I see that `foo` is using the `Overlay` engine. There are two other databases named `information_schema` which use the Memory engine and then there is `system` which uses `Atomic`.

I was able to get tables persisted by not specifying the database via `-d` but connecting to the default one and then from there creating a new database with engine Atomic. Then I had to restart again the process, switch to that database via `use foo;` and from there on the tables got persisted. When trying to use `-d` after creating the db it will refuse the start stating that the db already exists.

It's not very straightforward and I think persistence by default would be a better choice. At least if specifying the path.

ClickHouse local version 23.10.1.1611 (official build)

**Comment by cw5121** [comment]
@alexey-milovidov I found that there are missing some system tables in clickhouse local, like system.parts.
this is system tables show from clickhouse-local: 

```
ubuntu :) show tables from system;

SHOW TABLES FROM system

Query id: 3652204d-c933-4765-b540-0031f57bbbfd
┌─name───────────────────────────┐
│ aggregate_function_combinators │
│ backups                        │
│ build_options                  │
│ collations                     │
│ columns                        │
│ contributors                   │
│ current_roles                  │
│ data_skipping_indices          │
│ data_type_families             │
│ databases                      │
│ dropped_tables                 │
│ enabled_roles                  │
│ errors                         │
│ events                         │
│ formats                        │
│ functions                      │
│ grants                         │
│ kafka_consumers                │
│ licenses                       │
│ merge_tree_settings            │
│ numbers                        │
│ numbers_mt                     │
│ one                            │
│ privileges                     │
│ quota_limits                   │
│ quota_usage                    │
│ quotas                         │
│ quotas_usage                   │
│ replicated_merge_tree_settings │
│ rocksdb                        │
│ role_grants                    │
│ roles                          │
│ row_policies                   │
│ schema_inference_cache         │
│ server_settings                │
│ settings                       │
│ settings_changes               │
│ settings_profile_elements      │
│ settings_profiles              │
│ stack_trace                    │
│ table_engines                  │
│ table_functions                │
│ tables                         │
│ time_zones                     │
│ user_directories               │
│ users                          │
│ warnings                       │
│ zeros                          │
│ zeros_mt                       │
└────────────────────────────────┘
49 rows in set. Elapsed: 0.003 sec.
```

I would like to use the missing system table, how to operate it, or what operation parameters need to be set, thank you.
