### ISSUE TITLE
DB::Exception: Database engine MaterializedMySQL cannot have arguments.

### ISSUE THREAD

**Issue by hcymysql** [ClickHouse/ClickHouse#31176]
ck2 :) SET allow_experimental_database_materialize_mysql = 1
ck2 :) CREATE DATABASE t2 ENGINE = MaterializedMySQL('172.19.136.32:3306', 'test', 'hcy', '123456') ;
Received exception from server (version 21.7.4):
**Code: 36. DB::Exception: Received from localhost:9000. DB::Exception: Database engine MaterializedMySQL cannot have arguments.** 

ClickHouse server version 21.7.4 
8.0.26 MySQL Community Server - GPL

**Comment by stigsb** [comment]
In 21.7 the database engine was still called MaterializeMySQL (not materializeD), but the error message is misleading.

Change to ENGINE = MaterializeMySQL(...) and it should work.
