### ISSUE TITLE
Chunk should have AggregatedChunkInfo in GroupingAggregatedTransform

### ISSUE THREAD

**Issue by alesapin** [ClickHouse/ClickHouse#31172]
Found in stress test: https://gist.github.com/alesapin/5cd6b8901488a1f170d5ef389900a534
Report: https://s3.amazonaws.com/clickhouse-test-reports/31158/7fb9a42b119b6c3eba1784caaabde51c1ded3384/stress_tests__debug__actions_.html

**Comment by CurtizJ** [comment]
duplicate of #30692
