### ISSUE TITLE
Can a properly set partition key speed up the SELECT query? 

### ISSUE THREAD

**Issue by fsgdgsdfgsgd** [ClickHouse/ClickHouse#31170]
Hi All,
When I encountered too many parts error, I noticed that there was such a sentence in the error report: **Please note, that partitioning is not intended to speed up SELECT queries (ORDER BY key is sufficient to make range queries fast). Partitions are intended for data manipulation (DROP PARTITION, etc).. (TOO_MANY_PARTS)**
This is somewhat inconsistent with my view of partition keys all the time. If CH will divide the data into different directories according to the partition key, then the correctly set partition key should greatly improve the SELECT query speed, because this allows CH to skip a lot unwanted directory according to the partition key. In my opinion, the biggest impact on performance is the partition key, followed by the ORDER BY key, and finally the index. Am I right? (May be I should read the source code)

**Comment by den-crane** [comment]
There is no contradiction. 
The main goal of partitioning is too manage data retention (drop old data). Also partition pruning speed ups queries. BUT you should choose partitioning based to satisfy data retention requirements.
