### ISSUE TITLE
fail to build

### ISSUE THREAD

**Issue by MiaoMiaoGarden** [ClickHouse/ClickHouse#31187]
I'm failed to build the sorce code for development according to this page: [,](https://clickhouse.com/docs/en/development/build/) it got some thing wrong such like this when running ninja:
![image](https://user-images.githubusercontent.com/83738345/140951729-0601626f-b27c-43c1-9c22-8eb536f8f632.png)

my env is the docker image "ubuntu20.04".
I cannot solve this for several days, please could you tell me how to solve?

**Comment by alexey-milovidov** [comment]
Make sure your working copy is clean and you are using clang-13 and clang++-13 for build.

**Comment by alexey-milovidov** [comment]
You can also attach the full log, starting from `git clone ...`

**Comment by MiaoMiaoGarden** [comment]
here are all my history commands, starting from a clean docker image, the source code are downloaded before, contrib packages are downloaded separately and placed in the corresponding folder instead of using the git clone --recursive command.
![image](https://user-images.githubusercontent.com/83738345/140960881-3d4e9810-f2ae-47f4-8a6d-cb24c8c078b2.png)

**Comment by alexey-milovidov** [comment]
You don't need neither gcc nor boost. Only clang-13 and clang++-13 are needed.

If nothing helps, you can clone into clear working copy again and build inside Ubuntu 20.04 Docker image.

**Comment by alexey-milovidov** [comment]
Do you use Docker under Windows?
Maybe the problem is that you are using Windows filesystem with case-insensitive paths?

**Comment by MiaoMiaoGarden** [comment]
yes, under Windows, but I don't know why this may cause error "unknown types". I'm trying to build again with the mapping file in the root directory of the disk under Windows, without gcc and boost. Hope this may help.

**Comment by MiaoMiaoGarden** [comment]
hello, I'm happy to tell you that I've built ClickHouse successfully. The problem mentioned before is due to some contrib files not correctly placed in my computer. Thank you for your patience.
