### ISSUE TITLE
Replace `fsync` to `fdatasync` in all places.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#31181]
File size is updated correctly according to 

> fdatasync() is similar to fsync(), but does not flush modified metadata unless that metadata is needed in order to allow a subsequent data retrieval to be correctly handled.  For example, changes to  st_atime  or  st_mtime  (respec‐
       tively,  time  of  last  access  and  time  of last modification; see inode(7)) do not require flushing because they are not necessary for a subsequent data read to be handled correctly.  On the other hand, a change to the file size
       (st_size, as made by say ftruncate(2)), would require a metadata flush.

And we don't care about modification times.
Should work alright.

**Comment by zhanglistar** [comment]
According mysql release note, that's ok.
https://dev.mysql.com/doc/refman/8.0/en/optimizing-innodb-diskio.html
![image](https://user-images.githubusercontent.com/985418/141083863-86335e9c-cbf7-4ea9-bb95-4787d654e350.png)

**Comment by zhanglistar** [comment]
https://github.com/ClickHouse/ClickHouse/pull/31229

**Comment by azat** [comment]
If I understand correctly if there was fallocate in streams, then fsync is almost the same as fdatasync (in most cases, although there might be some differences for unwritten extents in ext4 and other things).

**Comment by azat** [comment]
And actually right now code calls fsync after the file had been written, so in this case fdatasync should be the same as fsync.
