### ISSUE TITLE
How to monitor the MaterializedMySQL synchronization status???

### ISSUE THREAD

**Issue by hcymysql** [ClickHouse/ClickHouse#31222]
In the  /var/lib/clickhouse/metadata/test/directory, could not be found the .metadata file

ClickHouse server version 21.7.4

**Comment by zzsmdfj** [comment]
it should be MaterializedMySQL initialization is not complete. we add system.materialize_mysql System Tables to help monitor the MaterializedMySQL synchronization status, I'm not sure it's helpful to others

**Comment by hcymysql** [comment]
ck1 :) select * from system.materialize_mysql;

SELECT *
FROM system.materialize_mysql

Query id: 43aae11a-d115-4522-a1ef-c61ce98b8871


0 rows in set. Elapsed: 0.001 sec. 

**Received exception from server (version 21.11.3):**
Code: 60. DB::Exception: Received from localhost:9000. DB::Exception: **Table system.materialize_mysql doesn't exist.** (UNKNOWN_TABLE)

**Comment by zzsmdfj** [comment]
i will work for this  later

**Comment by alexey-milovidov** [comment]
I'm closing all old issues about MaterializedMySQL because the ClickHouse team does not support it.

@zzsmdfj how is your work?
