### ISSUE TITLE
multi thread write same batch data to clickhouse ReplicatedMergeTree, will data duplicate?

### ISSUE THREAD

**Issue by lifulong** [ClickHouse/ClickHouse#31245]
> we need to write data to clickhouse exectly once, want to use  ReplicatedMergeTree to achieve this goal, but worry about data duplicate while do retry in some case

**Comment by den-crane** [comment]
You mean parallel into different CH servers?
If you insert data into the replicas of a shard you identical (binary identical) inserts will be deduplicated. https://clickhouse.com/docs/en/operations/settings/merge-tree-settings/#replicated-deduplication-window
