### ISSUE TITLE
Expose all GlobalThreadPool params to config.xml

### ISSUE THREAD

**Issue by gyfis** [ClickHouse/ClickHouse#31256]
**Describe the unexpected behaviour**
I'd expect GlobalThreadPool to expose all params outside to the configuration, so that they can be tweaked.

Here's the code:
https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ThreadPool.cpp#L323-L334

```cpp
void GlobalThreadPool::initialize(size_t max_threads)
{
    if (the_instance)
    {
        throw DB::Exception(DB::ErrorCodes::LOGICAL_ERROR,
            "The global thread pool is initialized twice");
    }

    the_instance.reset(new GlobalThreadPool(max_threads,
        1000 /*max_free_threads*/, 10000 /*max_queue_size*/,
        false /*shutdown_on_exception*/));
}
```

I'd expect both `max_free_threads` and `max_queue_size` to be configurable via settings.xml, similar to `max_threads`. 

Is this expansion planned? The possibility of increasing `max_queue_size` would allow us to manage table attaching in a much more direct, faster way.

**Comment by nikitamikhaylov** [comment]
Hello, you can send a PR. Implementation is pretty easy, just add a few more lines in Server.cpp https://github.com/ClickHouse/ClickHouse/blob/1579bcfd20094b158f9f82cc28f5dfacfba63b3b/programs/server/Server.cpp#L513-L516

**Comment by gyfis** [comment]
Thanks, I will!

**Comment by nikitamikhaylov** [comment]
For some reason issue didn't close automatically...
