### ISSUE TITLE
Why CH still report 'Table columns structure in ZooKeeper is different from local table structure' even if the columns are the same?

### ISSUE THREAD

**Issue by fsgdgsdfgsgd** [ClickHouse/ClickHouse#31284]
Hi All,
I tried to re-create a table with replicated merge tree engine. But I found that CH always report 'Table columns structure in ZooKeeper is different from local table structure'. I compared the data in this ZK node: '/{ReplicatedMergeTree engine path}/columns' with the columns of my table. It looks like the columns are the same. But CH still reported this exception. Is there any way to let me know which column is different?
I also have a replica node. I tried to use the create table query that select from system.tables table of this node. But it also report this exception.

**Comment by fsgdgsdfgsgd** [comment]
Forgot to mention. My CH version is 21.7.4.

**Comment by zhangjmruc** [comment]
1. Would you please show the complete ddl stmt for the create table?
2. Also please use "get" to get the content of columns in zk.
get /{ReplicatedMergeTree engine path}/columns
Then we can compare the detailed column definition for the re-create table and columns stored in zk.

**Comment by fsgdgsdfgsgd** [comment]
Actually, sharing the table schema may violate the security policy. Could you share some advices I might need to check?

**Comment by zhangjmruc** [comment]
> Actually, sharing the table schema may violate the security policy. Could you share some advices I might need to check?

I already provided. You can check the DDL of your re-create table and columns info in zk. You will find the difference.

**Comment by zhangjmruc** [comment]
Example of columns in zk for replica table with  (a int, b int):
columns format version: 1
2 columns:
`a` Int32
`b` Int32

**Comment by fsgdgsdfgsgd** [comment]
I checked and didn't see any difference. That's why I opened this issue.

**Comment by zhangjmruc** [comment]
![1636620890(1)](https://user-images.githubusercontent.com/66244986/141268057-e92fa652-8023-4d37-a59d-540875809079.png)

**Comment by zhangjmruc** [comment]
> I checked and didn't see any difference. That's why I opened this issue.

I tried to simulate your problem on CH 21.8. The replica table has (a int, b int), while the wrong one has (a int, b1 int) . You can see the RED flag  in the mismatched column. Please double check your case.

**Comment by fsgdgsdfgsgd** [comment]
The red flag would be helpful! I will upgrade my CH to 21.8 and try it again. And thanks for the help! :)

**Comment by fsgdgsdfgsgd** [comment]
I upgraded the CH to 21.9.4 and still can't solve the problem...
Could you add the column like this?
**`platform` String ALIAS IF(os LIKE '%indows%', 'Windows', IF(os LIKE 'Mac%', 'MacOS', IF(os = 'Other', 'Any', os))),**
I thought the problem may be related to this column.

**Comment by zhangjmruc** [comment]
> I upgraded the CH to 21.9.4 and still can't solve the problem... Could you add a column like this and try again? **`platform` String ALIAS IF(os LIKE '%indows%', 'Windows', IF(os LIKE 'Mac%', 'MacOS', IF(os = 'Other', 'Any', os))),** I thought the problem may be related to this column.
I add column os String as referenced in platform. I can create the replica table successfully. (Ubuntu CH21.3, Linux 21.8)
By the way, the red flag doesn't work for normal column like 'c'. Sorry for the misleading.

-------------------
Ubuntu :) create table replica_t1(a int, b int, os String, platform String ALIAS IF(os LIKE '%indows%', 'Windows', IF(os LIKE 'Mac%', 'MacOS', IF(os = 'Other', 'Any', os)))) engine=ReplicatedMergeTree('/clickhouse/tables/default/t1/1','1') order by a;

CREATE TABLE replica_t1
(
    `a` int,
    `b` int,
    `os` String,
    `platform` String ALIAS IF(os LIKE '%indows%', 'Windows', IF(os LIKE 'Mac%', 'MacOS', IF(os = 'Other', 'Any', os)))
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/default/t1/1', '1')
ORDER BY a

Query id: 8c624337-3913-4354-9043-11a9e30c81c2

Ok.

0 rows in set. Elapsed: 0.033 sec. 

Ubuntu :) create table replica_t2(a int, b int, os String, platform String ALIAS IF(os LIKE '%indows%', 'Windows', IF(os LIKE 'Mac%', 'MacOS', IF(os = 'Other', 'Any', os)))) engine=ReplicatedMergeTree('/clickhouse/tables/default/t1/1','2') order by a;

CREATE TABLE replica_t2
(
    `a` int,
    `b` int,
    `os` String,
    `platform` String ALIAS IF(os LIKE '%indows%', 'Windows', IF(os LIKE 'Mac%', 'MacOS', IF(os = 'Other', 'Any', os)))
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/default/t1/1', '2')
ORDER BY a

Query id: 70bf31bf-3ca6-4499-a676-7bc140f62e48

Ok.

0 rows in set. Elapsed: 0.035 sec.

**Comment by zhangjmruc** [comment]
> I checked and didn't see any difference. That's why I opened this issue.

You can change the zk_path for the re-create table to let it create successfully, then check the columns in zk with the original columns in old zk_path。Hope you will find the difference.

**Comment by fsgdgsdfgsgd** [comment]
This seems to be a ClickHouse bug. I just upgraded my ClickHouse to V21.11 and everything works well.

> Fix possible Table columns structure in ZooKeeper is different from local table structure exception while recreating or creating new replicas of ReplicatedMergeTree, when one of table columns have default expressions with case-insensitive functions. #29266 (Anton Popov).
