### ISSUE TITLE
Column XXX is not under aggregate function and not in GROUP BY

### ISSUE THREAD

**Issue by youtakeoff01** [ClickHouse/ClickHouse#31280]
version : 21.11.2
question:
CREATE TABLE default.test02
(
    `id` String,
    `name` String,
    `age` Int32,
    `aaa` String,
    `bbb` String,
    `ccc` Int32,
    `ddd` Int32
)
ENGINE = MergeTree
ORDER BY id
SETTINGS index_granularity = 8192

select aaa,bbb,ccc,ddd  from test02 group by 1,2,3,4;

Code: 215. DB::Exception: Received from localhost:9000. DB::Exception: Column `ddd` is not under aggregate function and not in GROUP BY: While processing aaa, bbb, ccc, ddd. (NOT_AN_AGGREGATE)

select aaa,bbb,ccc,ddd  from test02 group by aaa,bbb,ccc,ddd;

Query id: 24c43ad7-4c2e-412a-850c-d7125a211f75

┌─aaa───┬─bbb────┬─ccc─┬─ddd─┐
 │ dge                │ erdfe                │   5          │  90         │
 │ dddge           │ serdfe               │  20        │   30         │
 │ ge                 │ ere                     │   9         │  70           │
 │ qw                 │ ew                     │   3         │  78           │
└───── ┴─────── ┴───  ┴──── ┘

4 rows in set. Elapsed: 0.002 sec.

**Comment by den-crane** [comment]
```sql
psql> select a, b, c from (select 1 a, 2 b, 3 c) t group by 1,2,3;
 a | b | c
---+---+---
 1 | 2 | 3
```

**Comment by youtakeoff01** [comment]
select a, b, c ,d from (select 44 a, 88 b, 13 c,14 d) t group by 1,2,3,4;

DB::Exception: Column `d` is not under aggregate function and not in GROUP BY: While processing a, b, c, d. (NOT_AN_AGGREGATE)

**Comment by kssenii** [comment]
It did not work because you forgot to turn it on by setting `enable_positional_arguments`...

**Comment by youtakeoff01** [comment]
I have opened this parameter：
<?xml version="1.0"?>
<yandex>
    <profiles>
        <default>
            
            <enable_positional_arguments>1</enable_positional_arguments>
        </default>
    </profiles>
</yandex>

l execute sql "select a, b, c from (select 44 a, 88 b, 13 c) t group by 1,2,3;" 
this return :
a  | b  | c
----+----+----
 44 | 88 | 13
but when l execute sql "select a, b, c ,d from (select 44 a, 88 b, 13 c,14 d) t group by 1,2,3,4;"
this return :
DB::Exception: Column d is not under aggregate function and not in GROUP BY: While processing a, b, c, d. (NOT_AN_AGGREGATE)
Is there no problem with your execution？？
Which version are you using？
thanks

**Comment by kssenii** [comment]
yes, it works:
```sql
kssenii-nix :) select a, b, c ,d from (select 44 a, 88 b, 13 c,14 d) t group by 1,2,3,4 settings enable_positional_arguments=1

SELECT
    a,
    b,
    c,
    d
FROM
(
    SELECT
        44 AS a,
        88 AS b,
        13 AS c,
        14 AS d
) AS t
GROUP BY
    1,
    2,
    3,
    4
SETTINGS enable_positional_arguments = 1

Query id: 1a5fd473-5b8a-40c6-9ad5-34de2b9e4039

┌──a─┬──b─┬──c─┬──d─┐
│ 44 │ 88 │ 13 │ 14 │
└────┴────┴────┴────┘

1 rows in set. Elapsed: 0.023 sec. 

```
Version 21.12. I can check some other versions a little later.

**Comment by youtakeoff01** [comment]
l can do it use your way .
but I want this parameter（enable_positional_arguments = 1） to take effect globally
what l do is create  positional.xml in /etc/clickhouse-server/users.d
positional.xml content is：
```
<?xml version="1.0"?>
<yandex>
    <profiles>
        <default>
            <enable_positional_arguments>1</enable_positional_arguments>
        </default>
    </profiles>
</yandex>
```
later， l restart clickhouse-server
l execute sql "select a, b, c from (select 44 a, 88 b, 13 c) t group by 1,2,3;"
this return :
a | b | c
----+----+----
44 | 88 | 13
but when l execute sql "select a, b, c ,d from (select 44 a, 88 b, 13 c,14 d) t group by 1,2,3,4;"
this return :
DB::Exception: Column d is not under aggregate function and not in GROUP BY: While processing a, b, c, d. (NOT_AN_AGGREGATE)

Is there a problem with my configuration？
thanks
