### ISSUE TITLE
clickhouse-server.service: Main process exited, code=exited, status=134/n/a

### ISSUE THREAD

**Issue by FanWuu** [ClickHouse/ClickHouse#31288]
> Make sure to check documentation https://clickhouse.yandex/docs/en/ first. If the question is concise and probably has a short answer, asking it in Telegram chat https://telegram.me/clickhouse_en is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

> If you still prefer GitHub issues, remove all this text and ask your question here.
![image](https://user-images.githubusercontent.com/41465662/141270906-fceca6cc-6b1d-4052-a3ee-27a77e20fd69.png)
![image](https://user-images.githubusercontent.com/41465662/141271055-9628ec9a-9ce0-4648-81e6-2221ad81d93c.png)

**Comment by den-crane** [comment]
21.1 is out of support, and this is not official build. This is not supported.
Use official builds and latest Clickhouse versions, 21.11, 21.10, 21.10, 21.8 LTS.
