### ISSUE TITLE
Does MaterializedMySQL support cluster? 

### ISSUE THREAD

**Issue by 7omsxx** [ClickHouse/ClickHouse#31303]
When i read the doc of Offical it's said 
CREATE DATABASE [IF NOT EXISTS] db_name [ON CLUSTER cluster]
ENGINE = MaterializedMySQL('host:port', ['database' | database], 'user', 'password') [SETTINGS ...]
the grammer said it support CLUSTER  but  in this link  https://github.com/ClickHouse/ClickHouse/issues/26781, some one answered 
MaterializedMySQL  not support Cluster .

**Comment by den-crane** [comment]
`[ON CLUSTER cluster]` is just a helper to execute SQL at all nodes, it has no relation to clustering.

For example I can execute `create dictionary XXX on cluster ....` in this case dictionaries will be created at many nodes but dictionaries themselves has no relation to clustering and does not support clustering.

**Comment by tavplubix** [comment]
See https://github.com/ClickHouse/ClickHouse/issues/26781#issuecomment-966546364

**Comment by 7omsxx** [comment]
> `[ON CLUSTER cluster]` is just a helper to execute SQL at all nodes, it has no relation to clustering.
> 
> For example I can execute `create dictionary XXX on cluster ....` in this case dictionaries will be created at many nodes but dictionaries themselves has no relation to clustering and does not support clustering.

tks,create database  by =>CREATE DATABASE [IF NOT EXISTS] db_name [ON CLUSTER cluster]
ENGINE = MaterializedMySQL('host:port', ['database' | database], 'user', 'password') [SETTINGS ...]

shall my query will be send to diffrent nodes?
I mean if i create my database like above,Is this recommended？i want to create my ClickHouse Databases by a simple way. since we dont have many people to ETL data by canal or tranfer Mysql Binlog to kafka。
