### ISSUE TITLE
KafkaEngine: Null values are treated as default

### ISSUE THREAD

**Issue by ADovgalyuk** [ClickHouse/ClickHouse#31307]
Clickhouse version:
```
[root@in_monitoring bin]# rpm -qa | grep clickhouse
clickhouse-server-21.11.3.6-2.noarch
graphite-clickhouse-0.11.7-1.x86_64
clickhouse-common-static-21.11.3.6-2.x86_64
clickhouse-client-21.11.3.6-2.noarch
```
Kafka_engine_table:
```
CREATE TABLE statistics.test_null_kafka
(
    `Status` Nullable(Int16),
    `Cause` Nullable(Int16)
)
ENGINE = Kafka
SETTINGS kafka_broker_list = '192.168.126.251:9092', kafka_topic_list = 'test_null_kafka', kafka_group_name = 'clickhouse_prod', kafka_format = 'JSONEachRow'
```
Data in kafka itself:
```
[root@in_monitoring bin]# ./kafka-console-producer.sh --broker-list 192.168.126.251:9092 --topic test_null_kafka
>{"Status":"-1","Cause":""} 
```
Request to get values from kafka_table. I know that's incorrect thing to do, just in testing purposes only:
```
localhost :) select * from test_null_kafka;

SELECT *
FROM test_null_kafka

Query id: 46307158-cff1-496f-96f5-30bd9f91afce

┌─Status─┬─Cause─┐
│     -1 │     0 │
└────────┴───────┘
```

What was expected to have in kafka table
```
┌─Status─┬─Cause─┐
│     -1 │  NULL │
└────────┴───────┘
```

There are couple setting:
1. **input_format_null_as_default**
But according to description "If column type is nullable, then NULL values are inserted as is, regardless of this setting."

2. **insert_null_as_default**
But again: "If column type is nullable, then NULL values are inserted as is, regardless of this setting."

I'm not sure is it a bug or some configuration tweaks needed, which are not obvious.

**Comment by UnamedRus** [comment]
> {"Status":"-1","Cause":""} 

Are you sure that it should be parsed as null?


Can you test something like

```{"Status":"-1","Cause": null} ```

**Comment by ADovgalyuk** [comment]
You are right. I've checked on a simple table:
```
 INSERT INTO statistics.test_null_cdr FORMAT JSONEachRow {"Status":"-1","Cause":""} ;
 INSERT INTO statistics.test_null_cdr FORMAT JSONEachRow {"Status":"-1","Cause":null} ;


SELECT *
FROM statistics.test_null_cdr
┌─Status─┬─Cause─┐
│     -1 │     0 │
│     -1 │  ᴺᵁᴸᴸ │
└────────┴───────┘
```
But any idea what the hint then, to have NULL here if JSON string is empy? CH pass 0 here seems like according to
https://clickhouse.com/docs/en/sql-reference/statements/create/table/#create-default-values
> If an expression for the default value is not defined, the default values will be set to zeros for numbers

First thought to have DEFAULT NULL isn't working for me:
``
 CREATE TABLE statistics.test_null_cdr
(
    `Status` Nullable(Int16) DEFAULT -1,
    `Cause` Nullable(Int16) DEFAULT NULL
)
ENGINE = TinyLog;

 INSERT INTO statistics.test_null_cdr FORMAT JSONEachRow {"Status":"-1","Cause":""} ;

SELECT *
FROM statistics.test_null_cdr;

┌─Status─┬─Cause─┐
│     -1 │     0 │
└────────┴───────┘

```

**Comment by ADovgalyuk** [comment]
Hi team, any news? 
I understand it's not already about Kafka Null values, but the point is still the same, how can I get null from kafka in case of empty string. I'm using rsyslog and and it's not quite easy for me to get condition (if empty -> don't template in JSON) for every needed field.

**Comment by UnamedRus** [comment]
You can try to play with ALIAS / MATERIALIZED columns

```
CREATE TABLE test_null_cdr
(
    `Status` String,
    `Cause` String,
    `fixedCause` ALIAS toInt16OrNull(Cause)
)
ENGINE = TinyLog

INSERT INTO test_null_cdr FORMAT JSONEachRow {"Status":"-1","Cause":""} ;

SELECT
    *,
    fixedCause
FROM test_null_cdr

Query id: a476799d-8a11-4a32-a9c8-15caab255f4d

┌─Status─┬─Cause─┬─fixedCause─┐
│ -1     │       │       ᴺᵁᴸᴸ │
└────────┴───────┴────────────┘
```
