### ISSUE TITLE
toTimeZone function doesn't work, anyone can help?

### ISSUE THREAD

**Issue by xinzhang-0** [ClickHouse/ClickHouse#31308]
Hi there, the toTimeZone function is not working as the documentation described. Anyone can help fix it? Thank you.

**Comment by den-crane** [comment]
https://clickhouse.com/docs/en/sql-reference/functions/date-time-functions/#totimezone

Converts time or date and time to the specified time zone. 
**The time zone is an attribute of the Date and DateTime data types.** The internal value (number of seconds) of the table field or of the resultset's column **does not change**, the **column's type changes** and its string representation changes accordingly.


```sql
SELECT
    now() AS x,
    toTypeName(x),
    toTimeZone(x, 'Europe/Berlin') AS y,
    toTypeName(y),
    x = y

Query id: 0698c26f-1d62-4e70-a95a-ecf968c50c9a

┌───────────────────x─┬─toTypeName(now())─┬───────────────────y─┬─toTypeName(toTimeZone(now(), 'Europe/Berlin'))─┬─equals(now(), toTimeZone(now(), 'Europe/Berlin'))─┐
│ 2021-11-11 18:13:35 │ DateTime          │ 2021-11-11 19:13:35 │ DateTime('Europe/Berlin')                      │                                                 1 │
└─────────────────────┴───────────────────┴─────────────────────┴────────────────────────────────────────────────┴───────────────────────────────────────────────────┘
```
