### ISSUE TITLE
Inconsistent data on K8S

### ISSUE THREAD

**Issue by su-houzhen** [ClickHouse/ClickHouse#31329]
**Describe the issue**
I am using 21.1.3.32 ClickHouse cluster on kubernetes for high availability testing. But there is a data inconsistency.

Test case: When using tsbs to write, exec `kill 1` in clickhouse pod, and wait for the pod to restart automatically and data write complete. Judging the data consistency.

Then I ran the same test on the 21.3 version, and the problem did not appear.May I ask if this is a bug of version 21.1.3.32. If so, what is the reason?

**Environment**
- Test tool: tsbs
- ClickHouse version: 21.1.3.32
- ClickHouse cluster: 2 shards 2 replicas
- Data replication method: Distributed + MergeTree
- Kubernetes version: 1.17.9 with kubesphere
- Docker version: 19.03.11

The following is the performance of the data distribution: 
```bash
# kubectl exec -it chi-click-all-nodes-0-0-0 -n clickhouse -c clickhouse -- clickhouse-client --query 'SELECT COUNT() FROM test2.cpu_tags_metrics'
1726207
# kubectl exec -it chi-click-all-nodes-0-1-0 -n clickhouse -c clickhouse -- clickhouse-client --query 'SELECT COUNT() FROM test2.cpu_tags_metrics'
1726207
# kubectl exec -it chi-click-all-nodes-1-0-0 -n clickhouse -c clickhouse -- clickhouse-client --query 'SELECT COUNT() FROM test2.cpu_tags_metrics'
1729793
# kubectl exec -it chi-click-all-nodes-1-1-0 -n clickhouse -c clickhouse -- clickhouse-client --query 'SELECT COUNT() FROM test2.cpu_tags_metrics'
1728782
```

**Comment by den-crane** [comment]
21.1. is out support.
