### ISSUE TITLE
Error result when using NULL expression

### ISSUE THREAD

**Issue by kevinli1** [ClickHouse/ClickHouse#3132]
Dear ClickHouse,

  When executing the following sql, the result is not right for value_1_days_earlier and value_7_days_earlier. The table has 5000 rows for every day. Please help to check whether it is a bug, and how to fix, thanks so much.

select
        count(distinct if(p_date = '2018-09-12',user_omg_id,NULL)) as value
        ,count(distinct if(p_date = '2018-09-11',user_omg_id,NULL)) as value_1_days_earlier
        ,count(distinct if(p_date = '2018-09-05',user_omg_id,NULL)) as value_7_days_earlier
    FROM dbprd.app_duration_daily;

┌─value─┬─value_1_days_earlier─┬─value_7_days_earlier─┐
│  5136      │                              \N                       │                           \N                  │
└────┴───────────┴───────────┘

Thanks,
Kevin, Li

**Comment by alexey-milovidov** [comment]
Could you please provide more info (e.g. example data) on how to reproduce this issue?
