### ISSUE TITLE
FINAL and SAMPLE cannot be used at the same time

### ISSUE THREAD

**Issue by c3mb0** [ClickHouse/ClickHouse#3133]
In cases of `CollapsingMergeTree` and `ReplacingMergeTree`, mentioned keywords cannot be used at the same time. Furthermore, since the `max_parallel_replicas` setting makes use of SAMPLE during execution, the same problem applies.

This was talked about in the Telegram group, but I wasn't able to find an issue for it. The bug is acknowledged and is to be fixed in the future. I'm opening this issue to increase its tracking visibility. Feel free to close if inappropriate.

**Comment by alexey-milovidov** [comment]
Fixed in https://github.com/ClickHouse/ClickHouse/pull/7907.
