### ISSUE TITLE
Allow to configure FORMAT Template with string in SETTINGS

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#31363]
**Use case**

Sometimes it is too hard or impossible to deploy format output configuration for template format to directory on all nodes in cluster. Sometimes format is very specific and trivial that it is easier to add it to query.

Currently you need to place it to specific directory and pass path to file with template.
https://github.com/ClickHouse/ClickHouse/blob/a16eda68dc54ff0c3be7362dfec02061074f6e04/tests/queries/0_stateless/00938_template_input_format.sh#L46-L51

**Describe the solution you'd like**
Something like this
``` sql
SELECT
    cluster,
    shard_num,
    replica_num
FROM system.clusters
WHERE host_name = fqdn()
SETTINGS format_schema_rows_template = '|| ${cluster:Quoted} | ${shard_num:Quoted} | ${replica_num:Quoted}||', format_schema_rows_between_delimiter = '\n'
```

We add a separate setting and check that only one is set (filename or string).

**Comment by alexey-milovidov** [comment]
We also need format management for Protobuf and CapNProto.
@vitlibar started to work on some related solution for Protobuf schemas.

**Comment by Blargian** [comment]
I'll pick this one up

**Comment by alexey-milovidov** [comment]
@Blargian, thank you! This will be very helpful.

**Comment by Blargian** [comment]
@qoega what should happen if the user tries to set both `format_template_row` and `format_schema_rows_template`, do they get back a query error asking them to only set filename *or* string or do one of the settings just take preference over the other?

**Comment by qoega** [comment]
I think error is good asking to choose one. I expect having format set in setting profile to be a rare case and user can unset it anyway

**Comment by Blargian** [comment]
Opening PR #59088 for review
