### ISSUE TITLE
PointInPolygon Improvement ?

### ISSUE THREAD

**Issue by TH-HA** [ClickHouse/ClickHouse#3137]
Hello 
I'm starting to use this function but i 'm facing a few issues. 
To describe very quickly the use case: 
   We have a feed of geolocalized data stored in a MergeTree in clickhouse. This merge tree has as primary key the longitude,latitude ( we also partition the table using those 2 columns). 
On the top of those data we want to retrieve aggregated values for a particular zone ( enter manually by the user ) or some state/county/region which are predefined in another table ( which is pretty small in number of rows - few thousands) .

To be able to store polygon in another table , i'm using a array columns in the table ( i.e array(Float64),array(Float64)).

Interactive query works pretty well as there is only one polygon to be used. When i'm using a state or county , i need to use multiple polygons to define the zone and this is where things become complex. 
    Manually you can use multiple pointInPolygon with OR.
    when i want to use the definition stored in the DB , i'm unable to inject multiple polygon in the query.

One simple way to to handle that should be to have a PointInPolygons instead of PointInPolygon and to support as parameter Array(Array(Tuple(Float64,Float64))).  

Another  issue i'm facing is the speed. PointInPolygon do use the fact that longitude,latitude are the primary key. I don't if it's possible/simple , but if the function pointInPolygon can detect that the point is part of the PK and in this case can push some predicate ( typically use the min and max of the long/lat defined in the polygons as a filter on the index and also the partition in our case).

Just to share a few request which are working ( but only with county with one polygon )

The table BINS , contains longitude,latitude among other columns containing statistics.
The table containing the polygon is the SHAPES table. Every row contain one and only one polygon. 
CREATE TABLE GEO.SHAPES (
  id Int32,
  name String,
  state String,
  longitudes Array(Float64),
  latitudes Array(Float64),
  maxLongitude Float64 MATERIALIZED arrayFirst(x - > isNotNull(x), arrayReverseSort(longitudes)),
  minLongitude Float64 MATERIALIZED arrayFirst(x - > isNotNull(x), arraySort(longitudes)),
  maxLatitude Float64 MATERIALIZED arrayFirst(x - > isNotNull(x), arrayReverseSort(latitudes)),
  minLatitude Float64 MATERIALIZED arrayFirst(x - > isNotNull(x), arraySort(latitudes))
) ENGINE = Log

I'm computing automatically the min/max of long/lat to try to be able to filter the BIN table using the index. 

Here is a query which is working but only if we have only one polygon for the location ( here i'm searching the loving county in texas ).
Note :  by handling the min/max long/lat the speed of the query is improve by 200. ( 4s without the filter , 0.2 sec with ).
Note2 : Does anyone know how to structure this request to support more than one polygon ?

select
  sum( counter1)
 from
  GEO.BINS
where
  pointInPolygon(
    (longitude, latitude),(
      select
        groupArray(tuple(longitudes, latitudes)) as t
      from
        GEO.SHAPES array
        join latitudes,
        longitudes
      where
        name = 'Loving'
        and state = 'Texas'
      group by
        id
    )
  )
  and latitude <= (
    select
      max(maxLatitude)
    from
      GEO.SHAPES
    where
      name = 'Loving'
      and state = 'Texas'
  )
  and latitude >= (
    select
      min(minLatitude)
    from
      GEO.SHAPES
    where
      name = 'Loving'
  )
  and longitude <= (
    select
      max(maxLongitude)
    from
      GEO.SHAPES
    where
      name = 'Loving'
      and state = 'Texas'
  )
  and longitude >= (
    select
      min(minLongitude)
    from
      GEO.SHAPES
    where
      name = 'Loving'
      and state = 'Texas'
  )

Thanks

**Comment by alexey-milovidov** [comment]
This issue is addressed by "Geo Dictionaries" feature.
It is being implemented in #9278. The status is: final code review and evaluation.

The Geo Dictionary allows you to create an index on top of the set of polygons with some attributes and quickly extract attributes from matched polygon by location.

**Comment by alexey-milovidov** [comment]
And also we have implemented support for non-constant arguments in pointInPolygon function.
