### ISSUE TITLE
Which way is better to etl data of mysql to ClickHosue?

### ISSUE THREAD

**Issue by 7omsxx** [ClickHouse/ClickHouse#31388]
I'm confused. I don't know which tool to choose to synchronize data to ClickHosue？I was inclined to use MaterializedMysql but it is Experimental stage and Rarely updated. I hope experienced people can recommend your scheme.

**Comment by tiagokrebs** [comment]
Can you provide a little bit more context on this? What exactly you're trying to achieve? A simple table on Clickhouse that has the data from your Mysql virtually, for you to do queries over it? A stream of data from MySQL to Clickhouse?

I use the MySQL table engine integrations in some clusters, it works pretty fine for me.
https://clickhouse.com/docs/en/engines/table-engines/integrations/mysql/

**Comment by 7omsxx** [comment]
> Can you provide a little bit more context on this? What exactly you're trying to achieve? A simple table on Clickhouse that has the data from your Mysql virtually, for you to do queries over it? A stream of data from MySQL to Clickhouse?
> 
> I use the MySQL table engine integration in some clusters, it works pretty fine for me. https://clickhouse.com/docs/en/engines/table-engines/integrations/mysql/
==
thanks of ur reply
yes, i want sent my data of Mysql to Clickhouse since Our Mysql server is not much strong,complex queries are slow,If i use  MySQL table engine,shall all the queries were sent to Mysql Server ?

**Comment by tiagokrebs** [comment]
> if i use MySQL table engine,shall all the queries were sent to Mysql Server ?  

Yes.

Seems like you need the data replicated on Clickhouse then.  
If you need things near real-time you'll need to build a stream pipeline using some tool to move the data between MySQL and Clickhouse. I use Kafka and Flink on these cases, there is a bunch of other tools you can use. Or, if sync just a few times per day is enough and the increments are small you can make something in an export/import way in your language of choice.

**Comment by den-crane** [comment]
https://kb.altinity.com/altinity-kb-integrations/mysql-clickhouse/
