### ISSUE TITLE
Do not invalidate mark cache when drop mergetree table.

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#31395]
Now `drop table mergetree` drops mark cache for all tables.

```sql
SELECT value FROM system.asynchronous_metrics WHERE metric = 'MarkCacheBytes';
┌──────value─┐
│ 1880641264 │
└────────────┘

create table foo(A Int64) engine=MergeTree order by tuple();

drop table foo;

--- after several seconds  

SELECT value FROM system.asynchronous_metrics WHERE metric = 'MarkCacheBytes';
┌─value─┐
│     0 │
└───────┘
```
This behavior creates performance impact for users who use MergeTree as temporary tables, for example when they use `attach partition from temporary_table` for ingestion. Also other users create a lot of MergeTree tables with `time` in table's names using this pattern instead of partitioning, it's incorrect but they still use it.
(we have a client with 200000 MergeTree tables).

**Comment by alexey-milovidov** [comment]
It is required for non-`Atomic` databases.
As we have `Atomic` databases by default for a long time, this shouldn't be an issue.
