### ISSUE TITLE
when left distributed table and right distributed table are subquery, why right distributed table can not be written by local table?(version: 21.3.12))

### ISSUE THREAD

**Issue by cainiaodidi** [ClickHouse/ClickHouse#31404]
query: select a, b from (select id, a from table_a_dist) left join (select id, b from table_b_dist) on a.id=b.id
And I distribute data by join key(id), I want this query be written as: select a, b from (select id, a from table_a_dist) left join (select id, b from table_b_local) on a.id=b.id, but it can't. and from the source code, it is only available for ordinary table not subquery for left table.
![image](https://user-images.githubusercontent.com/65587510/141673819-5556b0fc-78e4-43fa-8e0d-634dd0c4158d.png)

**Comment by den-crane** [comment]
This behavior is defined by `( )`.
When you use use a subquery for the left table this subquery is executed at the node initiator ( it grabs results from the shards and combines them ) then the node initiator executes a join on itself. 
Basically it's a way to do joins at a initiator.
And in this case you have to use `table_b_dist` for the right table.

**Comment by cainiaodidi** [comment]
I want that each shard do join query: select a,b from (select id, a from table_a_local where xxx)tmp1 left join (select id, b from table_b_local where xxx)tmp2 on a.id=b.id, and then combine on initiator, Is there any way to do this? Because I want to filter left table, so the left table is a subquery. As I know, the rewriter is not available for subquery for left table.

**Comment by cainiaodidi** [comment]
> This behavior is defined by `( )`. When you use use a subquery for the left table this subquery is executed at the node initiator ( it grabs results from the shards and combines them ) then the node initiator executes a join on itself. Basically it's a way to do joins at a initiator. And in this case you have to use `table_b_dist` for the right table.



> This behavior is defined by `( )`. When you use use a subquery for the left table this subquery is executed at the node initiator ( it grabs results from the shards and combines them ) then the node initiator executes a join on itself. Basically it's a way to do joins at a initiator. And in this case you have to use `table_b_dist` for the right table.

I want that each shard do join query: select a,b from (select id, a from table_a_local where xxx)tmp1 left join (select id, b from table_b_local where xxx)tmp2 on a.id=b.id, and then combine on initiator, Is there any way to do this? Because I want to filter left table, so the left table is a subquery. As I know, the rewriter is not available for subquery for left table.

**Comment by cainiaodidi** [comment]
> This behavior is defined by `( )`. When you use use a subquery for the left table this subquery is executed at the node initiator ( it grabs results from the shards and combines them ) then the node initiator executes a join on itself. Basically it's a way to do joins at a initiator. And in this case you have to use `table_b_dist` for the right table.

I want that each shard do join query: select a,b from (select id, a from table_a_local where xxx)tmp1 left join (select id, b from table_b_local where xxx)tmp2 on a.id=b.id, and then combine on initiator, Is there any way to do this? Because I want to filter left table, so the left table is a subquery. As I know, the rewriter is not available for subquery for left table.

**Comment by cainiaodidi** [comment]
> This behavior is defined by `( )`. When you use use a subquery for the left table this subquery is executed at the node initiator ( it grabs results from the shards and combines them ) then the node initiator executes a join on itself. Basically it's a way to do joins at a initiator. And in this case you have to use `table_b_dist` for the right table.

Thanks very much. In other words, when I set distributed_product_mode='local' and the left and right table are subqueries, why does the right table not be rewritten to local? and then can do this: each shard do local join on itself and combine, I think this two subqueries are common case.

**Comment by den-crane** [comment]
> I want that each shard do join query: select a,b from (select id, a from table_a_local where xxx)tmp1 left join (select id, b from table_b_local where xxx)tmp2 on a.id=b.id, and then combine on initiator, Is there any way to do this? Because I want to filter left table, so the left table is a subquery. As I know, the rewriter is not available for subquery for left table.

```sql
 select a, b from table_a_dist left join (select id, b from table_b_local) b on table_a_dist.id=b.id
```

**Comment by den-crane** [comment]
```sql
in different versions of CH works in different ways, and does not work at all with circle replication 

drop table t1 on cluster segmented;
drop table t2 on cluster segmented;
create table t1 on cluster segmented (A Int64) Engine=MergeTree order by tuple();
create table t2 on cluster segmented (A Int64) Engine=MergeTree order by tuple();
create table t1d on cluster segmented as t1 Engine=Distributed(segmented, currentDatabase(), t1, A);
create table t2d on cluster segmented as t2 Engine=Distributed(segmented, currentDatabase(), t2, A);

insert into t1d select number+10 from numbers(3);
insert into t2d select number+10 from numbers(2);


select * from t1d;
┌──A─┐
│ 10 │
│ 12 │
└────┘
┌──A─┐
│ 11 │
└────┘


select * from t2d;
┌──A─┐
│ 10 │
└────┘
┌──A─┐
│ 11 │
└────┘


# distributed join!!! join locally, on the right we use the UNSHARDED table t2 
select t1d.*, t2.* from t1d left join t2 using A
┌──A─┬─t2.A─┐
│ 10 │   10 │
│ 12 │    0 │
└────┴──────┘
┌──A─┬─t2.A─┐
│ 11 │   11 │
└────┴──────┘


## SAME but via Distributed t2d 
set distributed_product_mode = 'local'
select t1d.*, t2d.* from t1d t1d left join t2d as t2d using A
┌──A─┬─t2d.A─┐
│ 10 │    10 │
│ 12 │     0 │
└────┴───────┘
┌──A─┬─t2d.A─┐
│ 11 │    11 │
└────┴───────┘


## (in older versions, SUB-REQUEST is MANDATORY)  select * from t2d
set distributed_product_mode = 'local'
select t1d.*, t2d.* from t1d t1d left join (select * from t2d) as t2d using A
┌──A─┬─t2d.A─┐
│ 11 │    11 │
└────┴───────┘
┌──A─┬─t2d.A─┐
│ 10 │    10 │
│ 12 │     0 │
└────┴───────┘


# tables are not sharded by the same key (e.g. rand ()) 
# all shards download from all the entire right table for themselves, i.e. 25 shards will make select * from td2 at the same time!
set distributed_product_mode = 'allow' 
select t1d.*, t2d.* from t1d left join t2d using A
┌──A─┬─t2d.A─┐
│ 10 │    10 │
│ 12 │     0 │
└────┴───────┘
┌──A─┬─t2d.A─┐
│ 11 │    11 │
└────┴───────┘

## Global -- the initiator downloads the right table for himself, puts it in temporary and sends it to shards, they will be set up with temporary 
set distributed_product_mode = 'deny'

select t1d.*, t2d.* from t1d global left join t2d using A
┌──A─┬─t2d.A─┐
│ 10 │    10 │
│ 12 │     0 │
└────┴───────┘
┌──A─┬─t2d.A─┐
│ 11 │    11 │
└────┴───────┘

set distributed_product_mode = 'global'
select t1d.*, t2d.* from t1d left join t2d using A
┌──A─┬─t2d.A─┐
│ 10 │    10 │
│ 12 │     0 │
└────┴───────┘
┌──A─┬─t2d.A─┐
│ 11 │    11 │
└────┴───────┘


# join on the initiator, the initiator pulls the whole t2d, goes along t1d and the join 
select t1d.*, t2d.* from (select * from t1d) as t1d left join t2d using A
┌──A─┬─t2d.A─┐
│ 10 │    10 │
│ 12 │     0 │
└────┴───────┘
┌──A─┬─t2d.A─┐
│ 11 │    11 │
└────┴───────┘
```

**Comment by cainiaodidi** [comment]
> > I want that each shard do join query: select a,b from (select id, a from table_a_local where xxx)tmp1 left join (select id, b from table_b_local where xxx)tmp2 on a.id=b.id, and then combine on initiator, Is there any way to do this? Because I want to filter left table, so the left table is a subquery. As I know, the rewriter is not available for subquery for left table.
> 
> ```sql
>  select a, b from table_a_dist left join (select id, b from table_b_local) b on table_a_dist.id=b.id
> ```

Thanks very much and I understand. And for the query below:

```sql
set distributed_product_mode = 'local'
select t1d.*, t2d.* from t1d t1d left join (select * from t2d) as t2d using A
```
it is equivalent to this query below, the right table will be written to local table query
```sql
select t1d.*, t2d.* from t1d t1d left join (select * from t2) as t2 using A
```
And each shard will make local join (select t1d.\*, t2d.\* from t1 t1 left join (select * from t2) as t2 using A), then combine on initiator, it's faster than before. But my main question is that: if table t1d is very big and I want to filter something in advance, then my query will become as below: 
```sql
select t1d.*, t2d.* from (select * from t1d where A in (numbers)) t1d left join (select * from t2d) as t2d using A
```
I believe this query will return correct result, but I think it may be slow and it won't use advantage of local join. from my opinion, if each shard make local join like (select t1d.\*, t2d.\* from (select * from t1 where A in (numbers)) t1 left join (select * from t2) as t2 using A), and then combine, I think it will be more faster and also return correct result. So I want to know if there is any way can do this?

**Comment by cainiaodidi** [comment]
> > I want that each shard do join query: select a,b from (select id, a from table_a_local where xxx)tmp1 left join (select id, b from table_b_local where xxx)tmp2 on a.id=b.id, and then combine on initiator, Is there any way to do this? Because I want to filter left table, so the left table is a subquery. As I know, the rewriter is not available for subquery for left table.
> 
> ```sql
>  select a, b from table_a_dist left join (select id, b from table_b_local) b on table_a_dist.id=b.id
> ```

could you please help answer my question above, thanks

**Comment by den-crane** [comment]
>But my main question is that: if table t1d is very big and I want to
> filter something in advance, then my query will become as below:

You don't need a subquery for this. Just use where, filter will be applied right as you want.

**Comment by cainiaodidi** [comment]
> > But my main question is that: if table t1d is very big and I want to
> > filter something in advance, then my query will become as below:
> 
> You don't need a subquery for this. Just use where, filter will be applied right as you want.

Thanks for your reply. and I tried for some cases. I find it's very useful for case of using where. 

But sometimes I want to aggregate left table using 'group by' syntax in advance, and I find that it is not very friendly for these cases. sql query like below:
```sql
select t1d.*, t2d.* from (select xxx, Aggregatefunction() from t1d where xxx group by xxx) t1d left join (select * from t2d where xxx group by xxx) as t2d using A
```
Is there any good way to solve this situation?  look forward to your reply.

**Comment by den-crane** [comment]
If you need to do aggregation before join then you can use only join at initiator, otherwise you will join half-complete aggregation state.

**Comment by cainiaodidi** [comment]
> If you need to do aggregation before join then you can use only join at initiator, otherwise you will join half-complete aggregation state.

Thanks, 'join at initiator' means I have to use distribute table for right table, right?
And how about local join for three or more tables?

**Comment by cainiaodidi** [comment]
During my join test for three tables, like this query:(and I found result is same that the third table is distribute table or local table)
```sql
select xxx
from t1d t1d
left join 
	(select * from t2d where xxx group by xxx) t2d 
using A
left join
	(select * from t3d where xxx group by xxx) t3d  -- equals to (select * from t3 where xxx group by xxx) t3
using A
where t1d.xxx
group by t1d.xxx
SETTINGS distributed_product_mode='local'
```
And I use 'explain' order to check its execution plan, as below: according to the plan, I find that the join operation of three tables doesn't do local join, why is that? or how should I change my sql query?
```shell
│ Expression ((Projection + Before ORDER BY))                                                                       │
│   Aggregating                                                                                                     │
│     Expression ((Before GROUP BY + (Projection + Before ORDER BY)))                                               │
│       Filter (HAVING)                                                                                             │
│         CreatingSets (Create sets before main query execution)                                                    │
│           Aggregating                                                                                             │
│             Expression (Before GROUP BY)                                                                          │
│               Filter (WHERE)                                                                                      │
│                 AddingDelayedSource (Add non-joined rows after JOIN)                                              │
│                   Join (JOIN)                                                                                     │
│                     Expression ((Before JOIN + Projection))                                                       │
│                       SettingQuotaAndLimits (Set limits and quota after reading from storage)                     │
│                         Union                                                                                     │
│                           Expression (Convert block structure for query from local replica)                       │
│                             CreatingSets (Create sets before main query execution)                                │
│                               Expression (Before ORDER BY)                                                        │
│                                 AddingDelayedSource (Add non-joined rows after JOIN)                              │
│                                   Join (JOIN)                                                                     │
│                                     Expression (Before JOIN)                                                      │
│                                       SettingQuotaAndLimits (Set limits and quota after reading from storage)     │
│                                         ReadFromStorage (MergeTree)                                               │
│                               CreatingSet (Create set for JOIN)                                                   │
│                                 Expression ((Projection + Before ORDER BY))                                       │
│                                   Filter (HAVING)                                                                 │
│                                     Aggregating                                                                   │
│                                       Expression (Before GROUP BY)                                                │
│                                         Filter (WHERE)                                                            │
│                                           SettingQuotaAndLimits (Set limits and quota after reading from storage) │
│                                             ReadFromStorage (MergeTree)                                           │
│                           ReadFromPreparedSource (Read from remote replica)                                       │
│           CreatingSet (Create set for JOIN)                                                                       │
│             Expression ((Projection + Before ORDER BY))                                                           │
│               Aggregating                                                                                         │
│                 Expression (Before GROUP BY)                                                                      │
│                   Filter (WHERE)                                                                                  │
│                     SettingQuotaAndLimits (Set limits and quota after reading from storage)                       │
│                       ReadFromStorage (MergeTree)
```

**Comment by cainiaodidi** [comment]
Can you help to answer my question above? thanks

**Comment by den-crane** [comment]
```
select ... from (
select xxx
from t1d t1d
left join 
	(select * from t2d where xxx group by xxx) t2d 
using A
where t1d.xxx)
    left join
	    (select * from t3d where xxx group by xxx) t3d
    using A
group by t1d.xxx
SETTINGS distributed_product_mode='local'
```

**Comment by cainiaodidi** [comment]
Thank you @den-crane
And I check the execution plan as below:
```bash
┌─explain───────────────────────────────────────────────────────────────────────────────────────────┐
│ Expression (Projection)                                                                           │
│   CreatingSets (Create sets before main query execution)                                          │
│     Expression (Before ORDER BY)                                                                  │
│       Join (JOIN)                                                                                 │
│         Expression ((Before JOIN + Projection))                                                   │
│           SettingQuotaAndLimits (Set limits and quota after reading from storage)                 │
│             Union                                                                                 │
│               Expression (Convert block structure for query from local replica)                   │
│                 CreatingSets (Create sets before main query execution)                            │
│                   Expression (Before ORDER BY)                                                    │
│                     Join (JOIN)                                                                   │
│                       Expression (Before JOIN)                                                    │
│                         SettingQuotaAndLimits (Set limits and quota after reading from storage)   │
│                           ReadFromPreparedSource (Read from NullSource)                           │
│                   CreatingSet (Create set for JOIN)                                               │
│                     Expression ((Projection + Before ORDER BY))                                   │
│                       SettingQuotaAndLimits (Set limits and quota after reading from storage)     │
│                         ReadFromStorage (MergeTree)                                               │
│               ReadFromPreparedSource (Read from remote replica)                                   │
│     CreatingSet (Create set for JOIN)                                                             │
│       Expression (Projection)                                                                     │
│         SettingQuotaAndLimits (Set limits and quota after reading from storage)                   │
│           Union                                                                                   │
│             Expression ((Convert block structure for query from local replica + Before ORDER BY)) │
│               SettingQuotaAndLimits (Set limits and quota after reading from storage)             │
│                 ReadFromStorage (MergeTree)                                                       │
│             ReadFromPreparedSource (Read from remote replica)                                     │
└───────────────────────────────────────────────────────────────────────────────────────────────────┘
```
From my understanding, I think the step as below:

1. t1_local and t2_local do local join on each shard as your reply

2. Initiator host combines the results from all shard of local join

3. each shard do query "select * from t3_local where xxx group by xxx" and combines on the initiator(maybe this is synchronized with step1)

4. Initiator do join between result of step2 and result of step3.

and my question is that: I hope on each shard can do local join like this

```sql
select xxx
from t1_local 
left join (select xxx from t2_local)
using A
left join (select xxx from t3_local)
using A
```
and then the initiator combines results from all shards. I think this is faster than above. But actually the execution plan can't show it.

**Comment by cainiaodidi** [comment]
> 

I write a sql as below:
```sql
explain
SELECT
    sex, 
    uniqExact(u) as uv
from
    (
    SELECT 
        t1d.dt as dt ,    
        t2d.u as u
    FROM t1d t1d
    LEFT JOIN
        (
        SELECT u
        FROM t2d t2d
        WHERE dt='2021-10-01'
        ) evt
    using(u)
    where t1d.id like '%2913%'
    ) a
LEFT JOIN
    (
    SELECT u, sex
    FROM t3d t3d
    WHERE dt='2021-10-01'
    ) b 
using(u)
group by sex
SETTINGS distributed_product_mode='local'
```
And the execution plan as above comment, and from explain syntax, I just see t2d is rewritten by t2_local, but t3d keep unchanging. Could you please help to see if there is any error?

**Comment by cainiaodidi** [comment]
> ```
> select ... from (
> select xxx
> from t1d t1d
> left join 
> 	(select * from t2d where xxx group by xxx) t2d 
> using A
> where t1d.xxx)
>     left join
> 	    (select * from t3d where xxx group by xxx) t3d
>     using A
> group by t1d.xxx
> SETTINGS distributed_product_mode='local'
> ```

I change my sql as another style:
```sql
select ... 
from t1d t1d
left join 
    (select ...
    from
        (select * from t2d where xxx group by xxx) t2d 
    left join
        (select * from t3d where xxx group by xxx) t3d
    using A
    ) t 
using A
where t1d.xxx
group by t1d.xxx
SETTINGS distributed_product_mode='local'
```
t2d and t3d are written by t2_local and t3_local, and it's execution plan as below:
```shell
┌─explain────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Expression ((Projection + Before ORDER BY))                                                                │
│   MergingAggregated                                                                                        │
│     SettingQuotaAndLimits (Set limits and quota after reading from storage)                                │
│       Union                                                                                                │
│         Aggregating                                                                                        │
│           Expression (Before GROUP BY)                                                                     │
│             Join (JOIN)                                                                                    │
│               Expression (Before JOIN)                                                                     │
│                 SettingQuotaAndLimits (Set limits and quota after reading from storage)                    │
│                   ReadFromMergeTree                                                                        │
│               Expression ((Joined actions + (Rename joined columns + (Projection + Before ORDER BY))))     │
│                 Join (JOIN)                                                                                │
│                   Expression ((Before JOIN + (Projection + Before ORDER BY)))                              │
│                     SettingQuotaAndLimits (Set limits and quota after reading from storage)                │
│                       ReadFromMergeTree                                                                    │
│                   Expression ((Joined actions + (Rename joined columns + (Projection + Before ORDER BY)))) │
│                     SettingQuotaAndLimits (Set limits and quota after reading from storage)                │
│                       ReadFromMergeTree                                                                    │
│         ReadFromRemote (Read from remote replica)                                                          │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```
I think it meets my expectations according to this plan, but actually this query is very slow than I thought, I don't know why. What do you think about this?
