### ISSUE TITLE
Modified this parameter(< mark_cache_size>),Memory continued to grow beyond the maximum limit

### ISSUE THREAD

**Issue by cloud-nine-GitHub** [ClickHouse/ClickHouse#31437]
Clickhouse has default setting <mark_cache_size>5368709120</mark_cache_size>. 
So eventually mark_cache occupies 5GB RAM + 5GB for queries.

This is the description of this parameter, but after I reduced it to 3GB, the memory footprint still exceeded 12GB

**Comment by den-crane** [comment]
>So eventually mark_cache occupies 5GB RAM + 5GB for queries.

No. max_memory_usage=10GB has no relation to mark_cache_size, and moreover 100 parallel queries able to 100*10GB+5GB (mark_cache).

**Comment by cloud-nine-GitHub** [comment]
We did not do the query operation, it has taken up 12GB of memory

**Comment by den-crane** [comment]
@cloud-nine-GitHub How we can reproduce it?

**Comment by cloud-nine-GitHub** [comment]
Most of my engines are MergeTree, and a few use the ReplacingMergeTree engine.   With A total of two ClickHouse hosts (A and B) deployed,A Host is responsible for data entry and creates 3000-5000 table every hour.   A host will be an hour/var/lib/clickhouse/data and /var/lib/clickhouse/metadata file copy to host B.Then execute Attach to add the table to host B Clickhouse, and finally delete the tables that host A has.   Host B needs to merge the hour tables synchronized from host A into day tables,later delete the hour table（3000-5000tables）.   In the early morning of every day, the day table is used for data calculation, and the calculated data is cached in the cache table, and then the day table is merged into the month table, and the day table is deleted.

**Comment by cloud-nine-GitHub** [comment]
The configuration of my host A is 8 core 16GB, and that of host B is 16 core 32GB.
