### ISSUE TITLE
how to  build  smaller size of clickhouse server

### ISSUE THREAD

**Issue by Johnny-Three** [ClickHouse/ClickHouse#31439]
I use ubuntu 20.4 image as base image to build clickhouse for release version.
try the command below:
cmake .. \
    -DCMAKE_C_COMPILER=$(which clang-11) \
    -DCMAKE_CXX_COMPILER=$(which clang++-11) \
    -DCMAKE_BUILD_TYPE=Debug \
    -DENABLE_CLICKHOUSE_ALL=OFF \
    -DENABLE_CLICKHOUSE_SERVER=ON \
    -DENABLE_CLICKHOUSE_CLIENT=ON \
    -DENABLE_LIBRARIES=OFF \
    -DUSE_UNWIND=ON \
    -DENABLE_UTILS=OFF \
    -DENABLE_TESTS=OFF

Then :
ninja -j 8 clickhosue

After Build:
1.6G	clickhouse

Seems official image bin size only 300M.

Wanna know how to build it for release ? 
Any suggestion will be appreciated.

**Comment by filimonov** [comment]
Strip symbols.

**Comment by Johnny-Three** [comment]
> Strip symbols

sorry I do not get the point ? you mean add or reduce cmake flags ? if it is , which one ?

**Comment by alexey-milovidov** [comment]
You have build clickhouse-server with debug information.
The official packages have debug information split into separate -dbg package.

You can remove debug info (and static symbol table) with the following command: `strip clickhouse-server`.
