### ISSUE TITLE
NULL mode for default values

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#31447]
**Use case**

Parsing values without storing raw data.

**Describe the solution you'd like**

It's possible to define some column as NULL, so it's possible to insert data in it, use it for DEFAULT value calculation for other columns but this column will not store any data in it. This column will also not appear in SELECT *

**Describe alternatives you've considered**

Null table engine for such parsing, but it's more complex to have 2 tables and 1 MV.

https://kb.altinity.com/altinity-kb-schema-design/altinity-kb-jsonasstring-and-mat.-view-as-json-parser/

**Comment by filimonov** [comment]
https://github.com/ClickHouse/ClickHouse/issues/9436 ?

**Comment by filimonov** [comment]
https://github.com/ClickHouse/ClickHouse/pull/34424
