### ISSUE TITLE
Server triggers timeouts after few minutes even when I set the timeout to be 8 hours

### ISSUE THREAD

**Issue by maciejblaz** [ClickHouse/ClickHouse#31452]
> You have to provide the following information whenever possible.

I have one clickhouse server running in kubernetes (no cluster). I'm running 5-10 queries from client vm using clickhouse driver for python. Result set of each query is iterated lazily, using "execute_iter" and I jump between the result sets. At some point some of the queries start to trigger "Timeout exceeded while writing to socket". I tried to increase the timeouts (just to see if it helps) and upgraded clickhouse server to the latest version, as the timeout message is more descriptive in the latest version. Now I'm getting:
"<Error> executeQuery: Code: 209. DB::NetException: Timeout exceeded while writing to socket ([::ffff:<ip_address>]:46084, **30000000** ms). (SOCKET_TIMEOUT) (version 21.11.3.6 (official build))"
But the problem is that whole the process fails after approx 15-30 min. While the timeout is set to over 8h (30000sec). 

The issue happens only when I go through HA proxy. When I connect directly then everything works fine. But there is something wrong with the timeout itself. It should not time out for 30000sec (8h+) while it times out after few min.

**Does it reproduce on recent release?**

I'm running latest 21.11 version:
┌─version()─┐
│ 21.11.3.6 │
└───────────┘

**Enable crash reporting**

The server doesn't crash

**How to reproduce**

That is not easy as it fails randomly in random places after random time. I run simple queries (select of multiple columns from one table). But there are multiple queries being run at a time and I switch between result sets in one thread. I have HA proxy between client and server.

**Expected behavior**

Time out settings should be respected.

**Error message and/or stacktrace**

<Error> executeQuery: Code: 209. DB::NetException: Timeout exceeded while writing to socket ([::ffff:<ip_address>]:46084, **30000000** ms). (SOCKET_TIMEOUT) (version 21.11.3.6 (official build))

**Comment by filimonov** [comment]
> The issue happens only when I go through HA proxy. When I connect directly then everything works fine.

So maybe the problem is haproxy configuration?

It maybe something related to tcp keep alive.

**Comment by maciejblaz** [comment]
I'm investigating it and most likely it has something to do with HA proxy. But something is wrong with clickhouse timeout as well. I set the timeout to over 8h, while clickhouse server timed out after 15 min or so. And it clearly stated it in the error message.

**Comment by den-crane** [comment]
> I'm investigating it and most likely it has something to do with HA proxy. But something is wrong with clickhouse timeout as well. I set the timeout to over 8h, while clickhouse server timed out after 15 min or so. And it clearly stated it in the error message.

Can you share the EXACT error message?

**Comment by maciejblaz** [comment]
The exact message is in the first post:
"executeQuery: Code: 209. DB::NetException: Timeout exceeded while writing to socket ([::ffff:<ip_address>]:46084, 30000000 ms). (SOCKET_TIMEOUT) (version 21.11.3.6 (official build))"

**Comment by alexey-milovidov** [comment]
The OS might trigger a timeout earlier for some reason.
You can check it with `strace` and `tcpdump`.
