### ISSUE TITLE
Not find column in block  when using the union all

### ISSUE THREAD

**Issue by jztian** [ClickHouse/ClickHouse#31459]
> You have to provide the following information whenever possible.

when I use the ReplicatedMergeTree engine and query with union all, It's reported with Not find column in block 
![image](https://user-images.githubusercontent.com/31120351/142110458-5a392980-ece4-4e31-95af-5e797551ce7d.png)

If I use the Mergetree engine without replicated, this problem will not occur
so, this temporary field cannot be used in conjunction with union all in an engine with a replica

sql:
SELECT
  toDate(o.time) AS xData,
  COUNT(o.distinct_id) AS value,
  ou.work_status AS yData
FROM
  onelog o
  LEFT JOIN (
    SELECT
      user_code,
      CASE
        job_status
        WHEN 1 THEN '在职'
        ELSE '其他'
      END AS work_status
    FROM
      onelog_user
    UNION ALL
    SELECT
      employee_code AS user_code,
      CASE
        job_status
        WHEN 1 THEN '在职'
        ELSE '其他'
      END AS work_status
    FROM
      onelog_user
  ) ou ON ou.user_code = o.distinct_id
GROUP BY
  toDate(o.time),
  ou.work_status
ORDER BY
  toDate(o.time)

> A clear and concise description of what works not as it is supposed to.

ClickHouse server version 21.9.2.17 (official build).

**Comment by tavplubix** [comment]
Please provide `CREATE TABLE` statements for `onelog` and `onelog_user`

**Comment by jztian** [comment]
> Please provide `CREATE TABLE` statements for `onelog` and `onelog_user`

CREATE TABLE default.onelog
(
    `distinct_id` String,

    `event` String,

    `event_duration` Float64 COMMENT '页面或视图停留时间：只有$WebStay、$pagestay、$WebPageLeave事件该列才有值',

    `login_id` String COMMENT '用户登录id',

    `response_time` Int64 COMMENT '后端接口响应时间，单位:ms',

    `terminal` String COMMENT '设备类型：pc、mobile、ipad(nginx解析)',

    `time` DateTime COMMENT '每个时间触发的时间',
 
)
ENGINE = ReplicatedMergeTree('/clickhouse1/table/{shard}/default/onelog','{replica}')
PARTITION BY toYYYYMMDD(time)
ORDER BY login_id
SETTINGS index_granularity = 8192,
 use_minimalistic_part_header_in_zookeeper = 1




CREATE TABLE default.onelog_user
(

    `user_id` String COMMENT '用户id',

    `user_code` String COMMENT '用户编码',

    `user_name` String COMMENT '用户姓名',

    `login_id` String COMMENT '登录id',

    `employee_code` String COMMENT '员工编号',

    `telphone` String COMMENT '手机号码',

    `dept_code` String COMMENT '部门编码',

    `dept_name_path` String COMMENT '部门长路径',

    `super_user_code` String COMMENT '员工上级用户编码',

    `station_code` String COMMENT '岗位编码',

    `station_name` String COMMENT '岗位名称',

    `mailbox` String COMMENT '邮箱',

    `sex` String COMMENT '性别',

    `birthday` String COMMENT '生日',

    `type` Int32 COMMENT '类型(1=内部员工，2=外部用户)',

    `status` Int32 COMMENT '状态(1=有效，2=禁用)',

    `job_status` Int32 COMMENT '在职状态(0=离职，1=在职)',

    `eff_date` DateTime COMMENT '有效期/离职日期',

    `category` Int32 ,

    `entry` DateTime COMMENT '入职日期',

    `work_address` String COMMENT '工作地点',

    `data_status` Int32 COMMENT '数据状态(0=无效，1=有效)'
)
ENGINE = ReplicatedMergeTree('/clickhouse1/table/{shard}/default/onelog_user','{replica}')
ORDER BY (user_code,employee_code)
SETTINGS index_granularity = 8192,
 use_minimalistic_part_header_in_zookeeper = 1

**Comment by tavplubix** [comment]
Cannot reproduce it, the query works fine:
```
ClickHouse client version 21.9.2.17 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 21.9.2 revision 54449.

localhost.localdomain :) CREATE TABLE default.onelog　(　    `distinct_id` String,　    `event` String,　    `event_duration` Float64 COMMENT '页面或视图停留时间：只有$WebStay、$pagestay、$WebPageLeave事件该列才有值',　    `login_id` String COMMENT '用户登录id',　    `response_time` Int64 COMMENT '后端接口响应时间，单位:ms',　    `terminal` String COMMENT '设备类型：pc、mobile、ipad(nginx解析)',　    `time` DateTime COMMENT '每个时间触发的时间'　)　ENGINE = ReplicatedMergeTree('/clickhouse1/table/1/default/onelog', '1')　PARTITION BY toYYYYMMDD(time)　ORDER BY login_id　SETTINGS index_granularity = 8192, use_minimalistic_part_header_in_zookeeper = 1

Ok.

localhost.localdomain :) CREATE TABLE default.onelog_user　(　    `user_id` String COMMENT '用户id',　    `user_code` String COMMENT '用户编码',　    `user_name` String COMMENT '用户姓名',　    `login_id` String COMMENT '登录id',　    `employee_code` String COMMENT '员工编号',　    `telphone` String COMMENT '手机号码',　    `dept_code` String COMMENT '部门编码',　    `dept_name_path` String COMMENT '部门长路径',　    `super_user_code` String COMMENT '员工上级用户编码',　    `station_code` String COMMENT '岗位编码',　    `station_name` String COMMENT '岗位名称',　    `mailbox` String COMMENT '邮箱',　    `sex` String COMMENT '性别',　    `birthday` String COMMENT '生日',　    `type` Int32 COMMENT '类型(1=内部员工，2=外部用户)',　    `status` Int32 COMMENT '状态(1=有效，2=禁用)',　    `job_status` Int32 COMMENT '在职状态(0=离职，1=在职)',　    `eff_date` DateTime COMMENT '有效期/离职日期',　    `category` Int32,　    `entry` DateTime COMMENT '入职日期',　    `work_address` String COMMENT '工作地点',　    `data_status` Int32 COMMENT '数据状态(0=无效，1=有效)'　)　ENGINE = ReplicatedMergeTree('/clickhouse1/table/1/default/onelog_user', '1')　ORDER BY (user_code, employee_code)　SETTINGS index_granularity = 8192, use_minimalistic_part_header_in_zookeeper = 1

Ok.

:) insert into onelog(time, distinct_id) values (1, 1), (2, 2)

Ok.

localhost.localdomain :) insert into onelog_user(user_code, job_status, employee_code) values (1, 1, 1), (2, 2, 2)

Ok.

localhost.localdomain :) SELECT　    toDate(o.time) AS xData,　    COUNT(o.distinct_id) AS value,　    ou.work_status AS yData　FROM onelog AS o　LEFT JOIN　(　    SELECT　        user_code,　        caseWithExpression(job_status, 1, '在职', '其他') AS work_status　    FROM onelog_user　    UNION ALL　    SELECT　        employee_code AS user_code,　        caseWithExpression(job_status, 1, '在职', '其他') AS work_status　    FROM onelog_user　) AS ou ON ou.user_code = o.distinct_id　GROUP BY　    toDate(o.time),　    ou.work_status　ORDER BY toDate(o.time) ASC

┌──────xData─┬─value─┬─yData─┐
│ 1970-01-01 │     2 │ 其他  │
│ 1970-01-01 │     2 │ 在职  │
└────────────┴───────┴───────┘

2 rows in set. Elapsed: 0.005 sec.

```
