### ISSUE TITLE
Split build failed on MacOS m1

### ISSUE THREAD

**Issue by copperybean** [ClickHouse/ClickHouse#31463]
cmake build command is

> cmake -DENABLE_S3=0 -DUSE_STATIC_LIBRARIES=0 -DSPLIT_SHARED_LIBRARIES=1 -DCLICKHOUSE_SPLIT_BINARY=1 -DCMAKE_C_COMPILER=$(brew --prefix llvm)/bin/clang -DCMAKE_CXX_COMPILER=$(brew --prefix llvm)/bin/clang++ -DCMAKE_BUILD_TYPE=RelWithDebInfo ..

ninja failed with following message:

> Undefined symbols for architecture arm64:
>   "_jump_fcontext", referenced from:
>       boost::coroutines::detail::coroutine_context::jump(boost::coroutines::detail::coroutine_context&, void*) in coroutine_context.cpp.o
>   "_make_fcontext", referenced from:
>       boost::coroutines::detail::coroutine_context::coroutine_context(void (*)(boost::context::detail::transfer_t), boost::coroutines::detail::preallocated const&) in coroutine_context.cpp.o
>       boost::coroutines::detail::coroutine_context::coroutine_context(void (*)(boost::context::detail::transfer_t), boost::coroutines::detail::preallocated const&) in coroutine_context.cpp.o
> ld: symbol(s) not found for architecture arm64
> clang-13: error: linker command failed with exit code 1 (use -v to see invocation)

Following is environment related information.

> Make sure that `git diff` result is empty and you've just pulled fresh master. Try cleaning up cmake cache. Just in case, official build instructions are published here: https://clickhouse.yandex/docs/en/development/build/

I built on fresh master. Id of git log is f1adde1b5f931dce69b38ca26fc02ea6dfb0bebf. Following is the output of git status command:
![image](https://user-images.githubusercontent.com/2949045/142136836-c55397c3-12d5-4519-965f-cb4c711aa624.png)
The modification from sysroot is because that some files in sysroot having almost same name except differences in upper or lower case, while MacOS is case insensitive. And it seems that the build failure is not caused by the modification from sysroot submodule, because I also tried with tag v21.8.10.19-lts, and the same build failure appeared, and sysroot submodule has not been added in that version.

**Operating system**

> OS kind or distribution, specific version/release, non-standard kernel if any. If you are trying to build inside virtual machine, please mention it too.

My OS is MacOS M1 Big Sur, version 11.6.

**Cmake version**
3.21.4

**Ninja version**
1.10.2

**Compiler name and version**
clang 13 installed by brew

**Full cmake and/or ninja output**
[CMake log](https://copperybean.s3.ap-southeast-1.amazonaws.com/share/cmake-master.log), [ninjia log](https://copperybean.s3.ap-southeast-1.amazonaws.com/share/ninja.log).

I also tried with tag v21.8.10.19-lts (with git id: 4273d46e037556cb17906e6f10f8c31d1ae9aa53), the same failure appeared.

**Comment by alexey-milovidov** [comment]
We don't support split build on Mac OS. Only regular build is supported.
Simply remove all the flags `-DENABLE_S3=0 -DUSE_STATIC_LIBRARIES=0 -DSPLIT_SHARED_LIBRARIES=1 -DCLICKHOUSE_SPLIT_BINARY=1`.
