### ISSUE TITLE
Debuginfo is not always used in CentOS

### ISSUE THREAD

**Issue by ilejn** [ClickHouse/ClickHouse#31466]
If ClickHouse RPMs are built by the native rpm toolchain debuginfo is not suitable for backtraces and reflection, while third party tools (e.g. gdb or readelf -n) do not have any issues.

This is happening because ClickHouse uses Program Header (ELF table) to obtain Build ID to validate debuginfo against executable. This approach does not seem reliable, it is better to use Section Header.

**Comment by ilejn** [comment]
I failed to find any proper guideline, just a number of hints.

In readelf.c from elfutils 0.176 there is a comment

> If we have section headers, just look for SHT_NOTE sections.
> In a debuginfo file, the program headers are not reliable.  */

In man elf(5)

> Program headers are meaningful only for executable and shared object files

I've tweaked readelf to use Program Headers and behaviour is the same as demonstrated by ClickHouse

> ./src/readelf -n /tmp/clickhouse.debug
> 
> Note segment of 68 bytes at offset 0x2fc:
>   Owner          Data size  Type
>                          4  <unknown>: 20
> ./src/readelf: cannot get content of note: garbage data

While intact readelf works fine

> ./src/readelf -n /tmp/clickhouse.debug
> 
> Note section [ 2] '.note.ABI-tag' of 32 bytes at offset 0x2e0:
>   Owner          Data size  Type
>   GNU                   16  GNU_ABI_TAG
>     OS: Linux, ABI: 3.2.0
> 
> Note section [ 3] '.note.gnu.build-id' of 36 bytes at offset 0x300:
>   Owner          Data size  Type
>   GNU                   20  GNU_BUILD_ID
>     Build ID: b16a083ed23e14e92d6e8017099cc9103e73d8b5

**Comment by ilejn** [comment]
I willingly handle it, while I appreciate additional information and suggestions.

Was the choice of Program Headers deliberate? 
Should we keep Program Headers as a fallback (readelf behaves in this way, if no Section Headers look into Program Headers)?
What should be tested to ensure nothing is broken (some exotic platforms may be)?

**Comment by ilejn** [comment]
This is about Elf::getBuildID

**Comment by alexey-milovidov** [comment]
Yes, separate debug info file does not necessary contain proper program headers.
We can start with section headers if we are using separate debug info.

But if we are using the binary with embedded debug info, it is better to use program headers, because they are already loaded in memory.

PS. We don't use or support native rpm toolchain, so I don't care about this issue.
Nevertheless, it will be better to fix.
