### ISSUE TITLE
Clickhouse and windows-1251

### ISSUE THREAD

**Issue by kartaris** [ClickHouse/ClickHouse#31472]
I have text encoded in windows-1251 in my Postgres database. So when I use MaterializedPostgreSQL to replicate my database those text columns are not correctly displayed after. Is there any solution to convert 1251 to UTF-8 on the fly or etc? Or any configuration option to change dafault encoding?

**Comment by qoega** [comment]
It looks client conversion can help on Postgres side but. not sure how it is done in client that reads CDC log
SET CLIENT_ENCODING TO 'value';
https://www.postgresql.org/docs/current/multibyte.html

**Comment by alexey-milovidov** [comment]
You can also convert data on the fly on ClickHouse side with `convertCharset` function.
