### ISSUE TITLE
Publish ClickHouse as an official image on docker-hub

### ISSUE THREAD

**Issue by Felixoid** [ClickHouse/ClickHouse#31473]
**Describe the issue**  
It will be more than convenient to have a way to use `docker pull clickhouse && docker run clickhouse`  
https://github.com/docker-library/official-images

**Additional context**
To achieve it, the images should be updated in two repositories:

- https://github.com/docker-library/docs
- https://github.com/docker-library/official-images

e.g.: https://github.com/docker-library/docs/tree/master/debian and https://github.com/docker-library/official-images/blob/master/library/debian

Another additional info is on https://docs.docker.com/docker-hub/official_images/

Plan:
- Take all git tags and sort by version (similar to https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)
- Compose them to supported versions (https://github.com/ClickHouse/ClickHouse/blob/master/utils/security-generator/generate_security.py)
- Create a PR with regenerated Dockerfiles for each release branch
- Generate `library definition file` https://github.com/docker-library/official-images/blob/master/README.md#library-definition-files
- Create a PR with it to https://github.com/docker-library/official-images, the file name will be `library/clickhouse`

**Comment by tylerhannan** [comment]
@alexey-milovidov - can we prioritize please? This matters more than any other artificial "verified pubblisher" or "sponsored OSS" programme

**Comment by Felixoid** [comment]
So, here we go https://github.com/docker-library/official-images/issues/14136

**Comment by Felixoid** [comment]
So, the plan to go now is the next:

1. An image in the official library requires two PRs, one to https://github.com/docker-library/docs and one to https://github.com/docker-library/official-images, see the [checklist](https://github.com/docker-library/official-images/blob/master/NEW-IMAGE-CHECKLIST.md)
2. As I've discussed in https://github.com/docker-library/official-images/issues/14136#issuecomment-1456892421 and following, I need to prepare some changes in our infrastructure, specifically:
    - Update the server's Dockerfiles in branches to the latest version in the branch in `tests/ci/release.py`
    - Generate the proper header file for `docker-library/official-images` and create PR on the daily base. Make it only after the new releases.

It looks like that's it

**Comment by Felixoid** [comment]
The idea is a little bit changed. It's easier to maintain the side repository with proper Dockerfiles generated out of the `master` branch.

I'll try to work there and prototype the autosync

**Comment by Felixoid** [comment]
The plan:

The script `tests/ci/official_docker.py` will generate the next structure in https://github.com/ClickHouse/docker-library:

`server / {ubuntu,alpine} / ${supported_branches} / {Dockerfile + other needed files}`

Each `Dockerfile + other needed files` will be taken from the according tag.

The content will be committed. Then, in the repository fork of https://github.com/docker-library/official-images, the file-description ([example](https://github.com/docker-library/official-images/blob/master/library/alt)) should be created. In the fork of https://github.com/docker-library/docs should be verified that everything in (future) directory https://github.com/docker-library/docs/tree/master/clickhouse is updated.

So, we need 3 repositories. Maybe, https://github.com/docker-library/official-images is unnecessary, and it's enough to have `docker/official` directory. It will simplify the scheme

**Comment by Felixoid** [comment]
An unexpected caveat is generating a documentation directory for https://github.com/docker-library/docs

For the first shot, I'll give a manually generated directory.

**Comment by alexey-milovidov** [comment]
Done.

**Comment by Felixoid** [comment]
It was a long nice jorney
