### ISSUE TITLE
Cannot authenticate in MongoDB 5.0

### ISSUE THREAD

**Issue by PolyProgrammist** [ClickHouse/ClickHouse#31483]
When I create user in MongoDB 4.2
```
mongo
use db1
db.createUser({ user: "user1", pwd: "password1", roles: [{role: "readWrite", db: "db1"}] } )
```
Check connection with:
```
mongo -u "user1" -p password1 db1
```
I can create table in ClickHouse with MongoDB engine:
```
CREATE TABLE default.mongo(key UInt64, data String) ENGINE=MongoDB('127.0.0.1:27017', 'db1', 'simple_table', 'user1', 'password1');
```
And use it:
```
SELECT * FROM default.mongo
```
Everything is OK. 

However, when I do the same for MongoDB 5.0, select query doesn't work:
``` 
Cannot authenticate in MongoDB, incorrect user or password. (MONGODB_CANNOT_AUTHENTICATE)
```

**How to reproduce**

* ClickHouse version 21.10.1.1
* Using ClickHouse client

**Expected behavior**

Successfully select data

**Error message and/or stacktrace**
```
Cannot authenticate in MongoDB, incorrect user or password. (MONGODB_CANNOT_AUTHENTICATE)

**Comment by alexey-milovidov** [comment]
Do you know, what has changed in MongoDB authentication in version 5.0?
Maybe they are introduced some new method that our client library does not support?

**Comment by PolyProgrammist** [comment]
There are a lot of changes in mongo 5.0 including that db.isMaster() disappeared and db.hello() appeared, however I don't know if it affects connection
