### ISSUE TITLE
Numbers or tables?

### ISSUE THREAD

**Issue by mischac** [ClickHouse/ClickHouse#31481]
Is there a hard limit on the number of tables? 
I guess it will also depend on the number of columns but is it realistic to have for example several thousand tables, each of which with max 50 columns?

**Comment by den-crane** [comment]
Clickhouse performs good only if you have small number of tables.
It depends of table engines.

You can have a lot of log tables, millions probably there are special database engine https://clickhouse.com/docs/en/engines/database-engines/lazy/

You can have 200000 MergeTree tables, though Clickhouse will start for a long time in this case, maybe hours if you disk has small number IOPS (like AWS EBS).

A number of Replicated tables should be small.
You can have 100 Replicated tables if you insert into into for example 10 of them. Each Replicated table adds CPU and Zookeeper overhead. You can get the best performance if you have 1 Replicated table.
You can create 1000 Replicated tables but you will experience various issues with replication and CPU usage.

**Comment by alexey-milovidov** [comment]
If your tables have identical or similar structure, it's better to have single MergeTree table with some key as first column of ORDER BY expression. Selection by this key is as fast (actually even faster) than having multiple tables.

There is no reason to do manual data partitioning across tables.

**Comment by mischac** [comment]
Thank you for your quick response!
One follow up question:

It is for a multi tenant application, there might be max 30 tables, and several hundreds of tenants so many identical table structures as each tenant wil have the same table structures.

> it's better to have single MergeTree table with some key as first column of ORDER BY expression.
Would it make sense to partition the MergeTree table by a discriminator column rather than order by it?
