### ISSUE TITLE
s3 table function partitioned writes 

### ISSUE THREAD

**Issue by stephenpaul2727** [ClickHouse/ClickHouse#31493]
Hello Clickhouse Team,

We are using the clickhouse s3 table functions feature to migrate cold storage to from GP2 to s3.  I was facing the following error when using the example partitioned write mentioned on this page:  https://clickhouse.com/docs/en/sql-reference/table-functions/s3/

```
//Original query has correct bucket url with working permissions
INSERT INTO TABLE FUNCTION
    s3('http://bucket.amazonaws.com/my_bucket/file_{_partition_id}.csv.gz', 'CSV', 'a String, b UInt32, c UInt32', 'gzip')
    PARTITION BY a VALUES ('x', 2, 3), ('x', 4, 5), ('y', 11, 12), ('y', 13, 14), ('z', 21, 22), ('z', 23, 24);
```
Expected one of: WATCH, OpeningRoundBracket, OVER, SELECT, VALUES, FORMAT, WITH, token

Could you advise on this?

Clickhouse-server Version: 21.7.8

**Comment by den-crane** [comment]
It's not available in 21.7.8

https://github.com/ClickHouse/ClickHouse/blob/master/CHANGELOG.md
ClickHouse release v21.10, 2021-10-16
Support for partitioned write into s3 table function. #23051 (Vladimir Chebotarev).
