### ISSUE TITLE
How to get all materialized views related to a table

### ISSUE THREAD

**Issue by shadowDy** [ClickHouse/ClickHouse#31495]
How to get all materialized views related to a table；
given a table name for example :test；
get all MaterializedView  and related store table create_table_query ;

**Comment by den-crane** [comment]
```
select arrayJoin( dependencies_table ) from system.tables where name = 'log_row_null'
```

**Comment by shadowDy** [comment]
thanks;
How to get the storage table corresponding to the materialized view?
@den-crane

**Comment by den-crane** [comment]
Probably only from create_table_query
