### ISSUE TITLE
execute concurrent request

### ISSUE THREAD

**Issue by htavakkoli1368** [ClickHouse/ClickHouse#31496]
Why there is not feature that user be able to execute concurrent request with the same session ID?
The advantage of this feature is we can load some table as default on memory for user of  different program ،when user access to system.
You can add setting to the user request that cause user wait for last session to be end.
The user request stand in queue until the already request be done.
would you mind helping me to solve the problem if there is another way?

**Comment by alexey-milovidov** [comment]
Session contains not just temporary tables but also many other things like the current database, settings...
Named session in HTTP is similar to regular connection in native interface. And one connection can be used only one client.

If you need temporary tables shared between multiple requests, it's better to create regular Memory tables under some temporary names and share these names between clients. Then drop outdated tables.

**Comment by mbtolou** [comment]
thanks for your answer .

https://github.com/ClickHouse/ClickHouse/issues/31461

**Comment by htavakkoli1368** [comment]
thanks a lot . you save my times . god bless you
