### ISSUE TITLE
Every exception message should contain info about server version and build type.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#31498]
**Use case**

#31487

**Describe the solution you'd like**

Was:
`Code: 395. DB::Exception: Received from localhost:9000. DB::Exception: Value passed to 'throwIf' function is non zero: While processing throwIf(1). (FUNCTION_THROW_IF_VALUE_IS_NON_ZERO)`

Should be:
`Code: 395. DB::Exception: Received from localhost:9000. DB::Exception: Value passed to 'throwIf' function is non zero: While processing throwIf(1). (FUNCTION_THROW_IF_VALUE_IS_NON_ZERO) (version 21.10.2.15 (official build))`

**Comment by MaxWk** [comment]
I am a bit confused about this issue, don’t we now have a version in our exception information?
I test on my local.
here is exception message in client 
```
Received exception from server (version 21.12.1):
Code: 497. DB::Exception: Received from localhost:9000. DB::Exception: default: Not enough privileges. To execute this query it's necessary to have grant CREATE USER ON *.*. (ACCESS_DENIED)
```
in server:
```
2021.11.18 20:01:03.124716 [ 4750829 ] {1a7d2389-0d96-48e2-be3b-6fdd742a1b78} <Error> executeQuery: Code: 497. DB::Exception: default: Not enough privileges. To execute this query it's necessary to have grant CREATE USER ON *.*. (ACCESS_DENIED) (version 21.12.1.1) (from [::1]:63337) (in query: CREATE USER api HOST ANY IDENTIFIED WITH sha256_password BY 'qwerty';), Stack trace (when copying this message, always include the lines below):

```

**Comment by alexey-milovidov** [comment]
My bad, I was confused by #31487
