### ISSUE TITLE
how to import java udf in clickhouse?

### ISSUE THREAD

**Issue by gongjinzz** [ClickHouse/ClickHouse#31494]
> Make sure to check documentation https://clickhouse.yandex/docs/en/ first. If the question is concise and probably has a short answer, asking it in Telegram chat https://telegram.me/clickhouse_en is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

> If you still prefer GitHub issues, remove all this text and ask your question here.

**Comment by rfraposa** [comment]
A UDF can run any command. For example, you could write a shell script that runs your Java command (making sure JAVA_HOME is set properly and the .class file is in your CLASSPATH). I saved this as `run_java.sh`:

```
#!/bin/sh

java ClickHouseUDFTest
```

Then have the UDF invoke the script:

```
<functions>
    <function>
        <type>executable</type>
        <name>hello_java</name>
        <argument>
            <type>String</type>
        </argument>
        <return_type>String</return_type>
        <format>TabSeparated</format>
        <command>run_java.sh</command>
        <lifetime>0</lifetime>
    </function>
</functions>
```

I wrote the class with a simple `main()` function:

```
  public static void main(String[] args){
    System.out.println("Hello, Java UDF!");
  }
}

```

**Comment by rfraposa** [comment]
If you want to use Java in an `Executable` or `ExecutablePool` table engine, the following script can be executed (put it in your `user_scripts` folder):

```
#!java --source 11

public class ClickHouseUDFTest {
  public static void main(String[] args){
    System.out.println("Hello, Java UDF!");
  }
}
```
