### ISSUE TITLE
Context has expired: while pushing to view

### ISSUE THREAD

**Issue by zealjoanna** [ClickHouse/ClickHouse#31502]
> Make sure to check documentation https://clickhouse.yandex/docs/en/ first. If the question is concise and probably has a short answer, asking it in Telegram chat https://telegram.me/clickhouse_en is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

> If you still prefer GitHub issues, remove all this text and ask your question here.
 after upgrading the program to v21.11.3.1-stable    
every thing seems ,ok  but when excute a insert query then i get an error

ClickHouse exception, code: 1002, host: localhost, port: 8123; Code: 49. DB::Exception: Context has expired: while pushing to view TEST.pipeline_test_merge_to_test_set (8b3cb0d0-dc28-4355-8b3c-b0d0dc28e355). (LOGICAL_ERROR) (version 21.11.3.1)

my test sql is :

create database TEST

create table TEST.test_merge
(
text String
)
engine =MergeTree()
ORDER BY text

create table TEST.test_set
(
text String
)
engine =Set()

 CREATE MATERIALIZED VIEW TEST.pipeline_test_merge_to_test_set
 to TEST.test_set
 AS
 SELECT * from TEST.test_merge
 where text!='hello'

 
i  excute  two insert query and one is ok  the other error

 insert into TEST.test_merge 
 values ('hello1')
 
 insert into TEST.test_merge 
 values ('hello')

**Comment by zealjoanna** [comment]
https://github.com/ClickHouse/ClickHouse/pull/29544   seems relate to this pull

**Comment by Algunenano** [comment]
This ticket can be closed as it was indeed fixed by #29544

**Comment by Algunenano** [comment]
I had to join CH Inc to close the ticket 😄
