### ISSUE TITLE
 build clickhouse(21.11.4.14 ) Target: aarch64-unknown-linux-gnu

### ISSUE THREAD

**Issue by qinxiangyangnet** [ClickHouse/ClickHouse#31525]
-- The C compiler identification is Clang 10.0.0
-- The CXX compiler identification is Clang 10.0.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/clang-10 - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/clang++-10 - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The ASM compiler identification is Clang
-- Found assembler: /usr/bin/clang-10
-- Cross-compiling for target: 
CMake Error at cmake/tools.cmake:40 (message):
  Clang version must be at least 12.
Call Stack (most recent call first):
  CMakeLists.txt:46 (include)

-- Configuring incomplete, errors occurred!
See also "/data/ck/ClickHouse/build-arm66/CMakeFiles/CMakeOutput.log".
See also "/data/ck/ClickHouse/build-arm66/CMakeFiles/CMakeError.log".
root@375107de880b:/data/ck/ClickHouse# cat /data/ck/ClickHouse/build-arm66/CMakeFiles/CMakeError.log
Checking whether the ASM compiler is GNU using "--version" did not match "(GNU assembler)|(GCC)|(Free Software Foundation)":
clang version 10.0.0-4ubuntu1~18.04.2 
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

**Comment by alexey-milovidov** [comment]
We are using clang-13, not clang-10.

You should not build ClickHouse by yourself unless you are willing to contribute and develop ClickHouse and you have experience with CMake to address these issues.

In other cases you need to download pre-built binary from https://clickhouse.com/#quick-start
