### ISSUE TITLE
How to alter zoo_path in ReplicatedTable?

### ISSUE THREAD

**Issue by wangqinghuan** [ClickHouse/ClickHouse#31529]
1. Create a replicated table
CREATE TABLE table_name
(
    EventDate DateTime,
    CounterID UInt32,
    UserID UInt32,
    ver UInt16
) ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/shard1/table_name', 'replica1', ver)
PARTITION BY toYYYYMM(EventDate)
ORDER BY (CounterID, EventDate, intHash32(UserID))
SAMPLE BY intHash32(UserID);
2.  Rename table name
RENAME TABLE table_name TO table_name2;
3. How to rename zoo_path from '/clickhouse/tables/shard1/table_name' to  '/clickhouse/tables/shard1/table_name2'?

**Comment by tavplubix** [comment]
> How to rename zoo_path from '/clickhouse/tables/shard1/table_name' to '/clickhouse/tables/shard1/table_name2'?

It's not possible
