### ISSUE TITLE
select Array type column showing error `Cannot read all array values`

### ISSUE THREAD

**Issue by gfunc** [ClickHouse/ClickHouse#31533]
Hey guys.

after upgrading from 21.10.x to 21.11 version, I started to experience below error:
 ```
  Code: 33.
  DB::Exception: Cannot read all array values: read just 48525 of 49000: (while reading column data): (while reading from part /var/lib/clickhouse/store/8e0/8e0d4e9a-e29f-497d-8e0d-4e9ae29fe97d/5cef2ab042e0ee48578729a50baa7390_105_3295_719/ from mark 5 with max_rows_to_read = 1225): While executing MergeTreeThread. Stack trace:
  
  0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x9b605d4 in /usr/bin/clickhouse
  1. DB::SerializationArray::deserializeBinaryBulkWithMultipleStreams(COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, DB::ISerialization::DeserializeBinaryBulkSettings&, std::__1::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, COW<DB::IColumn>::immutable_ptr<DB::IColumn> > > >*) const @ 0x11cd9fe2 in /usr/bin/clickhouse
  2. DB::SerializationArray::deserializeBinaryBulkWithMultipleStreams(COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, DB::ISerialization::DeserializeBinaryBulkSettings&, std::__1::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, COW<DB::IColumn>::immutable_ptr<DB::IColumn> > > >*) const @ 0x11cd9a00 in /usr/bin/clickhouse
  3. DB::MergeTreeReaderWide::readData(DB::NameAndTypePair const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, bool, unsigned long, unsigned long, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, COW<DB::IColumn>::immutable_ptr<DB::IColumn> > > >&, bool) @ 0x12e84a02 in /usr/bin/clickhouse
  4. DB::MergeTreeReaderWide::readRows(unsigned long, unsigned long, bool, unsigned long, std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >&) @ 0x12e837d9 in /usr/bin/clickhouse
  5. DB::MergeTreeRangeReader::DelayedStream::finalize(std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >&) @ 0x133b29ce in /usr/bin/clickhouse
  6. DB::MergeTreeRangeReader::continueReadingChain(DB::MergeTreeRangeReader::ReadResult&, unsigned long&) @ 0x133b6a79 in /usr/bin/clickhouse
  7. DB::MergeTreeRangeReader::read(unsigned long, std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange> >&) @ 0x133b5ad3 in /usr/bin/clickhouse
  8. DB::MergeTreeBaseSelectProcessor::readFromPartImpl() @ 0x133ae1ba in /usr/bin/clickhouse
  9. DB::MergeTreeBaseSelectProcessor::readFromPart() @ 0x133af40d in /usr/bin/clickhouse
  10. DB::MergeTreeBaseSelectProcessor::generate() @ 0x133adaab in /usr/bin/clickhouse
  11. DB::ISource::tryGenerate() @ 0x13114d95 in /usr/bin/clickhouse
  12. DB::ISource::work() @ 0x1311495a in /usr/bin/clickhouse
  13. DB::SourceWithProgress::work() @ 0x13320742 in /usr/bin/clickhouse
  14. ? @ 0x131301fb in /usr/bin/clickhouse
  15. DB::PipelineExecutor::executeStepImpl(unsigned long, unsigned long, std::__1::atomic<bool>*) @ 0x1312c1b1 in /usr/bin/clickhouse
  16. ? @ 0x13132185 in /usr/bin/clickhouse
  17. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x9ba2697 in /usr/bin/clickhouse
  18. ? @ 0x9ba609d in /usr/bin/clickhouse
  19. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
  20. clone @ 0xfe9fd in /usr/lib64/libc-2.17.so
```

some background:
1.  a cluster of 3,  all upgraded to version `21.11.4.14` 
2. data integrated using Kafka engine and materialized view. 
3. Kafka setting as follows:
```SQL
CREATE TABLE default.kafka_stream on cluster bi
(
    "data"      Array(Map(String,Nullable(String))),
    "database"  String,
    "es"        Int64,
    "id"        Int64,
    "isDdl"     boolean,
    "mysqlType" Map(String, String),
    "pkNames"   Array(String),
    "sql"       String,
    "sqlType"   Map(String, Int64),
    "table"     String,
    "ts"        Int64,
    "type"      String
) ENGINE = Kafka()
SETTINGS
    kafka_broker_list = 'my_brokers',
    kafka_topic_list = 'my_topic',
    kafka_group_name = 'bi_group',
    kafka_flush_interval_ms = 3500,
    kafka_num_consumers = 1,
    kafka_format = 'JSONEachRow',
    kafka_row_delimiter = '\n';
```
4. a local table and a distributed table created for storage and query, the distributed table is using `halfMD5(ts)` as sharding key
5. a materialized view created "to distributed table"

first, I thought it was a problem with the setting since there was a mention of `max_rows_to_read`, but setting `max_rows_to_read=0` did not solve the problem.

Then I start to notice that this problem was related to the where clause since the select query would work if I shrink the time range (which is the time data processed by Kafka, in this case `_timestamp`) I was querying. And further, since the error message mentioned "array", I tried to select columns  of type `array` only, and found that the problem is with column `data`

So it is probably a problem with the data itself. 

And my question is:
1. if the data was corrupted or was not of array type, how did the materialized view successfully insert the data into the merge tree table?
2. is there a way to bypass this error and only select the correct records?

thanks in advance

**Comment by gfunc** [comment]
the same thing happened intermittently with other tables that use `Array(Tuple(xx))` type columns.

In those cases, `Array()` columns were made by `groupArray()` function.

my workaround so far was to `alter table drop partition` then `insert into`

**Comment by rchadin** [comment]
We have the same error.
``
<Error> TCPHandler: Code: 33. DB::Exception: Cannot read all array values: read just 17487 of 23674: (while reading column ???????????): (while reading from part /var/lib/clickhouse/data/?????/??????/202111_3_3_0/ from mark 1234 with max_rows_to_read = 591): While executing MergeTreeThread. (CANNOT_READ_ALL_DATA), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x9b605d4 in /usr/bin/clickhouse
1. DB::SerializationArray::deserializeBinaryBulkWithMultipleStreams(COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, DB::ISerialization::DeserializeBinaryBulkSettings&, std::__1::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, COW<DB::IColumn>::immutable_ptr<DB::IColumn> > > >*) const @ 0x11cd9fe2 in /usr/bin/clickhouse
2. DB::SerializationNamed::deserializeBinaryBulkWithMultipleStreams(COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, DB::ISerialization::DeserializeBinaryBulkSettings&, std::__1::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, COW<DB::IColumn>::immutable_ptr<DB::IColumn> > > >*) const @ 0x11cf43df in /usr/bin/clickhouse
3. DB::SerializationArray::deserializeBinaryBulkWithMultipleStreams(COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, DB::ISerialization::DeserializeBinaryBulkSettings&, std::__1::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, COW<DB::IColumn>::immutable_ptr<DB::IColumn> > > >*) const @ 0x11cd9a00 in /usr/bin/clickhouse
4. DB::MergeTreeReaderWide::readData(DB::NameAndTypePair const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, bool, unsigned long, unsigned long, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const,
COW<DB::IColumn>::immutable_ptr<DB::IColumn> > > >&, bool) @ 0x12e84a02 in /usr/bin/clickhouse
5. DB::MergeTreeReaderWide::readRows(unsigned long, unsigned long, bool, unsigned long, std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >&) @ 0x12e837d9 in /usr/bin/clickhouse
6. DB::MergeTreeRangeReader::DelayedStream::finalize(std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >&) @ 0x133b29ce in /usr/bin/clickhouse
7. DB::MergeTreeRangeReader::continueReadingChain(DB::MergeTreeRangeReader::ReadResult&, unsigned long&) @ 0x133b6a79 in /usr/bin/clickhouse
8. DB::MergeTreeRangeReader::read(unsigned long, std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange> >&) @ 0x133b5ad3 in /usr/bin/clickhouse
9. DB::MergeTreeBaseSelectProcessor::readFromPartImpl() @ 0x133ae1ba in /usr/bin/clickhouse
10. DB::MergeTreeBaseSelectProcessor::readFromPart() @ 0x133af40d in /usr/bin/clickhouse
11. DB::MergeTreeBaseSelectProcessor::generate() @ 0x133adaab in /usr/bin/clickhouse
12. DB::ISource::tryGenerate() @ 0x13114d95 in /usr/bin/clickhouse
13. DB::ISource::work() @ 0x1311495a in /usr/bin/clickhouse
14. DB::SourceWithProgress::work() @ 0x13320742 in /usr/bin/clickhouse
15. ? @ 0x131301fb in /usr/bin/clickhouse
16. DB::PipelineExecutor::executeStepImpl(unsigned long, unsigned long, std::__1::atomic<bool>*) @ 0x1312c1b1 in /usr/bin/clickhouse
17. ? @ 0x13132185 in /usr/bin/clickhouse
18. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x9ba2697 in /usr/bin/clickhouse
19. ? @ 0x9ba609d in /usr/bin/clickhouse
20. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
21. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
``
When executing a query in version 21.10 for the part of data, an error does not occur

**Comment by gfunc** [comment]
should probably modify the label to `potential-bug`

**Comment by rchadin** [comment]
After updating to version 21.11.5.33, the error disappeared

**Comment by eqqeeqee** [comment]
In version 21.1.3.32 I have the same error, so this is a **bug** in previous versions? 
Or are there any rules need to follow when querying an `Array()` type?

**Comment by DerekHou** [comment]
I experienced the same error in version 21.12.3.32

**Comment by gfunc** [comment]
will test version `22.1` to see if this error persists.

**Comment by DerekHou** [comment]
In version 22.1.2.2, the same thing still happened.  

![1642731303(1)](https://user-images.githubusercontent.com/16362881/150453615-0de28f8b-901a-4e04-8f77-95d4cbb8d550.png)

After reading the comments where the exception is thrown, I guess maybe the data was broken for some reason. But actually I don't understand what the "offset" check here is used for, and how to fix it if the data is broken

**Comment by gfunc** [comment]
> In version 22.1.2.2, the same thing still happened.
> 
> ![1642731303(1)](https://user-images.githubusercontent.com/16362881/150453615-0de28f8b-901a-4e04-8f77-95d4cbb8d550.png)
> 
> After reading the comments where the exception is thrown, I guess maybe the data was broken for some reason. But actually I don't know what the "offset" check here is used for, and how to fix it if the data is broken

In my case, array data created by both `groupArray()` function and kafka engine as mentioned above, could not understand what caused the corruption, hence my production environment stayed at verion `21.10.3.9`.

I will close this issue when I raised another one with the label `potential-bug` and hopefully a reproducable example.

**Comment by DerekHou** [comment]
Same error can be seen at version 21.10.3.9 in my case.  If I used "limit" statement in the query，the error disappeared.
So I guess the error is also related to the amount of data.

**Comment by alesapin** [comment]
@gfunc @DenKoren Any idea for repro? Maybe you can send broken part privately?

**Comment by DerekHou** [comment]
Same error happend when try to export the data.  And the output like "from mark xxxxx with max_rows_to_read=xxxxx" always changed

**Comment by aipan** [comment]
We have the same error.  I experienced the same error in version  22.3.3.44

**Comment by novikd** [comment]
@aipan Could you please check if this problem is reproducible on the latest 22.3 release? Currently, it is 22.3.6.5.

**Comment by alexey-milovidov** [comment]
The user did not provide the info requested.
