### ISSUE TITLE
ClickHouse 20.8.11.17 Abnormal crash

### ISSUE THREAD

**Issue by jiugem** [ClickHouse/ClickHouse#31537]
ClickHouse 20.8.11.17
5 Shard 2 Replca
Which query was not found that caused the exception

Expect to find the cause of the triggering exception and solve it

Exception report：

2021.11.19 20:32:31.773614 [ 19007 ] {} <Fatal> BaseDaemon: ########################################
2021.11.19 20:32:31.773690 [ 19007 ] {} <Fatal> BaseDaemon: (version 20.8.11.17 (official build), no build id) (from thread 17218) (no query) Received signal Segmentation fault (11)
2021.11.19 20:32:31.773714 [ 19007 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
2021.11.19 20:32:31.773742 [ 19007 ] {} <Fatal> BaseDaemon: Stack trace: 0x160c0641 0x160b1588 0x160e7373 0x16100ffd 0x15f3d3be 0x15f405e4 0x15f7056b 0x15f7097d 0x162b5f42 0x15f20e7e 0x1
60984e3 0x16098e22 0xe65fba7 0xe65e093 0x7f2640916dd5 0x7f2640233ead
2021.11.19 20:32:31.773854 [ 19007 ] {} <Fatal> BaseDaemon: 3. std::__1::__hash_const_iterator<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::ch
ar_traits<char>, std::__1::allocator<char> >, DB::ColumnSize>, void*>*> std::__1::__hash_table<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::
__1::allocator<char> >, DB::ColumnSize>, std::__1::__unordered_map_hasher<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_ty
pe<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, DB::ColumnSize>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::_
_1::allocator<char> > >, true>, std::__1::__unordered_map_equal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_type<std::__
1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, DB::ColumnSize>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::al
locator<char> > >, true>, std::__1::allocator<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, DB::ColumnSize> > >::find
<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) con
st @ 0x160c0641 in /usr/bin/clickhouse
2021.11.19 20:32:31.773894 [ 19007 ] {} <Fatal> BaseDaemon: 4. DB::IMergeTreeDataPart::getColumnSize(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >
 const&, DB::IDataType const&) const @ 0x160b1588 in /usr/bin/clickhouse
2021.11.19 20:32:31.773913 [ 19007 ] {} <Fatal> BaseDaemon: 5. DB::MergeTreeData::removePartContributionToColumnSizes(std::__1::shared_ptr<DB::IMergeTreeDataPart const> const&) @ 0x160e7
373 in /usr/bin/clickhouse
2021.11.19 20:32:31.773930 [ 19007 ] {} <Fatal> BaseDaemon: 6. DB::MergeTreeData::Transaction::commit(std::__1::unique_lock<std::__1::mutex>*) @ 0x16100ffd in /usr/bin/clickhouse
2021.11.19 20:32:31.773945 [ 19007 ] {} <Fatal> BaseDaemon: 7. DB::StorageReplicatedMergeTree::checkPartChecksumsAndCommit(DB::MergeTreeData::Transaction&, std::__1::shared_ptr<DB::IMerg
eTreeDataPart const> const&) @ 0x15f3d3be in /usr/bin/clickhouse
2021.11.19 20:32:31.773956 [ 19007 ] {} <Fatal> BaseDaemon: 8. DB::StorageReplicatedMergeTree::tryExecuteMerge(DB::ReplicatedMergeTreeLogEntry const&) @ 0x15f405e4 in /usr/bin/clickhouse
2021.11.19 20:32:31.773963 [ 19007 ] {} <Fatal> BaseDaemon: 9. DB::StorageReplicatedMergeTree::executeLogEntry(DB::ReplicatedMergeTreeLogEntry&) @ 0x15f7056b in /usr/bin/clickhouse
2021.11.19 20:32:31.773974 [ 19007 ] {} <Fatal> BaseDaemon: 10. ? @ 0x15f7097d in /usr/bin/clickhouse
2021.11.19 20:32:31.773990 [ 19007 ] {} <Fatal> BaseDaemon: 11. DB::ReplicatedMergeTreeQueue::processEntry(std::__1::function<std::__1::shared_ptr<zkutil::ZooKeeper> ()>, std::__1::share
d_ptr<DB::ReplicatedMergeTreeLogEntry>&, std::__1::function<bool (std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&)>) @ 0x162b5f42 in /usr/bin/clickhouse
2021.11.19 20:32:31.774004 [ 19007 ] {} <Fatal> BaseDaemon: 12. DB::StorageReplicatedMergeTree::queueTask() @ 0x15f20e7e in /usr/bin/clickhouse
2021.11.19 20:32:31.774024 [ 19007 ] {} <Fatal> BaseDaemon: 13. DB::BackgroundProcessingPool::workLoopFunc() @ 0x160984e3 in /usr/bin/clickhouse
2021.11.19 20:32:31.774033 [ 19007 ] {} <Fatal> BaseDaemon: 14. ? @ 0x16098e22 in /usr/bin/clickhouse
2021.11.19 20:32:31.774055 [ 19007 ] {} <Fatal> BaseDaemon: 15. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xe65fba7 in /usr/bin/click
house
2021.11.19 20:32:31.774067 [ 19007 ] {} <Fatal> BaseDaemon: 16. ? @ 0xe65e093 in /usr/bin/clickhouse
2021.11.19 20:32:31.774088 [ 19007 ] {} <Fatal> BaseDaemon: 17. start_thread @ 0x7dd5 in /usr/lib64/libpthread-2.17.so
2021.11.19 20:32:31.774108 [ 19007 ] {} <Fatal> BaseDaemon: 18. __clone @ 0xfdead in /usr/lib64/libc-2.17.so
2021.11.19 20:32:32.842207 [ 17217 ] {} <Error> flow_origin_multi_prod.`.inner.v_visit_overview_monthly_local`: DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicated
MergeTree::LogEntryPtr&)>: Code: 128, e.displayText() = DB::Exception: Too large array size: (while reading column key_words): (while reading from part /data/clickhouse/data/flow_origin_
multi_prod/%2Einner%2Ev_visit_overview_monthly_local/20210601_0_2534854_10759/ from mark 0 with max_rows_to_read = 3902): While executing MergeTreeSequentialSource, Stack trace (when cop
ying this message, always include the lines below):

Related context error connection：
https://github.com/jiugem/jiugem.github.io/blob/master/2021.11.19_log

**Comment by alexey-milovidov** [comment]
Version 20.8 is not supported.
You should upgrade to version 21.11.

**Comment by jiugem** [comment]
@alexey-milovidov 
Can the upgrade to v21.8.11.4-lts be supported or resolved? Or other considerations ?

**Comment by alexey-milovidov** [comment]
Yes, upgrading to 21.8-lts is supported.
You can upgrade to 21.11 as well.

**Comment by jiugem** [comment]
Thank you very much.
