### ISSUE TITLE
splitByWhitespace fuction  is not working, ClickHouse version  21.3.4.25

### ISSUE THREAD

**Issue by Tomislav24i** [ClickHouse/ClickHouse#31539]
I am using ClickHouse version  21.3.4.25 and DBeaver .
When I use  splitByWhitespace  function in database I am getting an error.
example:
`SELECT splitByWhitespace('  1!  a,  b.  ');`

error message:

**org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [46]: ClickHouse exception, code: 46, host: 127.0.0.1, port: 11654; Code: 46, e.displayText() = DB::Exception: Unknown function splitByWhitespace: While processing splitByWhitespace('  1!  a,  b.  ') (version 21.3.4.25 (official build))**

If I place the same query directly on server, I am also getting error message.

error message:
**Received exception from server (version 21.3.4):
Code: 46. DB::Exception: Received from localhost:9000. DB::Exception: Unknown function splitByWhitespace: While processing splitByWhitespace('  1!  a,  b.  ').**

Is maybe function splitByWhitespace  removed from new version of ClickHouse?

**Comment by UnamedRus** [comment]
It was merged in https://github.com/ClickHouse/ClickHouse/pull/24997

So, starting from 21.9

```
Connected to ClickHouse server version 21.9.4 revision 54449.



┌─splitByWhitespace(' 1! a, b. ')─┐
│ ['1!','a,','b.']                │
└─────────────────────────────────┘

1 rows in set. Elapsed: 0.182 sec.

```

**Comment by filimonov** [comment]
W/o for older versions:
```
select extractAll(' 1! a, b. ', '\S+');
```

But upgrade is a better option.
