### ISSUE TITLE
Perf test: Arrays passed to arrayMap must have equal size

### ISSUE THREAD

**Issue by tavplubix** [ClickHouse/ClickHouse#31530]
Sometimes Performance test fails to build a report due to
```
Code: 190. DB::Exception: Arrays passed to arrayMap must have equal size: while executing 'FUNCTION arrayMap(__lambda_6 :: 6, arrayElement(medians_by_version, 1) : 8, arrayElement(medians_by_version, 2) :: 5) -> arrayMap(lambda(tuple(x, y), floor(divide(minus(y, x), x), 3)), arrayElement(medians_by_version, 1), arrayElement(medians_by_version, 2)) Array(Float64) : 9'. (SIZES_OF_ARRAYS_DOESNT_MATCH)
```
Either the following query
https://github.com/ClickHouse/ClickHouse/blob/08148e062f1c7ccc84c2e6d3cbd4f34ed3cb0faf/docker/test/performance-comparison/eqmed.sql#L5-L8
does not handle some corner case correctly or there's a bug somewhere in sh scripts that generate data for this query, it's hard to tell.

https://clickhouse-test-reports.s3.yandex.net/31391/a13ed01c05b90edd9408fe33b80c6075fcc571cd/performance_comparison/report.html#fail1

**Comment by alexey-milovidov** [comment]
It is hard to tell.
