### ISSUE TITLE
Add ability speficy `SETTINGS` for `INSERT` queries with embedded data.

### ISSUE THREAD

**Issue by alesapin** [ClickHouse/ClickHouse#31541]
For most types of queries in ClickHouse we can specify settings:
```
:) SELECT number FROM numbers(10) SETTINGS max_block_size=32;
:) ALTER TABLE querty MODIFY COLUMN x UInt64 SETTINGS replication_alter_partitions_sync=2;
:) INSERT INTO querty SELECT number FROM numbers(10) SETTINGS max_threads=16;
:) DROP TABLE querty SETTINGS database_atomic_wait_for_drop_and_detach_synchronously=1;
```
But for insert queries with embedded data it doesn't work:
```
:) INSERT INTO querty VALUES (1) SETTINGS async_insert_max_data_size=1
INSERT INTO querty VALUES

Query id: 16838a9e-6e4d-4194-95d7-53514fe1591f

Exception on client:
Code: 27. DB::ParsingException: Cannot parse input: expected '(' before: 'SETTINGS async_insert_max_data_size=1':  at row 1: While executing ValuesBlockInputFormat: data for INSERT was parsed from query. (CANNOT_PARSE_INPUT_ASSERTION_FAILED)
```

This problem is fundamental and cannot be solved with ad-hoc solution. 

So proposal is to parse `SETTINGS` section before `VALUES/FORMAT` like this:

```
INSERT INTO querty SETTINGS async_insert_max_data_size=1 VALUES (1)
```

It's not very consistent with other types queries, but looks like straightforward and easy to use and easy to implement.

**Comment by alexey-milovidov** [comment]
It already supports SETTINGS.
Unfortunately it is after FORMAT and it breaks parsing of some tsv/csv data.

**Comment by alexey-milovidov** [comment]
See https://github.com/ClickHouse/ClickHouse/issues/20343#issuecomment-778708708
