### ISSUE TITLE
Translate ClickHouse Testing doc into Chinese

### ISSUE THREAD

**Issue by cccgp** [ClickHouse/ClickHouse#31563]
**Describe the issue**
The content of the link(https://clickhouse.com/docs/zh/development/tests/ ) is in English, not Chinese

**Additional context**
I want to do this work and do it as well as possible.

**Comment by cccgp** [comment]
Can you assign this work to me？@kssenii

**Comment by alexey-milovidov** [comment]
Nothing happened in this task.
