### ISSUE TITLE
Support for multi tenancy at the s3 bucket level

### ISSUE THREAD

**Issue by kant777** [ClickHouse/ClickHouse#31578]
Clickhouse today writes all the database/table data under one bucket. In order to support true multi tenancy at the data level, ideally would want each tenant's data to be stored in a separate bucket otherwise to scale for lot of tenants one may have to create a separate database for each tenant and potentially spin up multiple clusters if there are lot of tenants and do some sort of consistent hashing at the application layer.

Also, what say if there are 10K tenants and for each tenant there is a separate db/table what is the overhead? can 10K database/tables be created in a standard 3 node cluster? (just trying to get an idea what would go wrong in this approach in clickhouse?)

**Comment by den-crane** [comment]
It's nonsense. The whole idea of MergeTree table is a small number of partitions. 10k tenants / partitions / tables is unthinkable.

**Comment by kant777** [comment]
@den-crane rather than saying it is non sense you are better of explaining why but given your tone I would report to @hodgesrm

**Comment by filimonov** [comment]
@den-crane answer is correct. Explanation takes a lot of time.

It relates to number of files / folders, memory needed for file buffers, number of file descriptors, number of threads which can do merges, 'fanout effect' on inserts, some background housekeeping things coupled with every table, number of zookeeper transactions, number of parts exchange etc. etc.

Just imagine you need to read millions of files on single select, of write milions of files at the insert. And multiple it by number of inserts/selects per sec. Or schedule merdes in thousands of tables / partitions, syn ing everything with other replicas using zookeeper. 

That's definitely not the things you want to experience. It's a very bad pattern. Please don't do it, it will hurt. 

P. S. If you're not satisfied with level of support in  community channels you can always go to some commercial support :)

P. P. S. Denny is not a native english speaker (nor me), and sometimes the answers may sound worse in English than it supposed to. Please read 'nonsense' in his answer as 'bad pattern'.

**Comment by kant777** [comment]
@filimonov Are you saying creating 10K databases is a bad pattern? if so, what is the reasonable number?  Also, why not have s3 storage write to different buckets based on tenant id column or attribute similar to other datastore like loki, bigquery, snowflake etc where there is clear data isolation per tenant? I created this ticket hoping that someone will consider the idea but unfortunately it is just closed right away

**Comment by filimonov** [comment]
> Are you saying creating 10K databases is a bad pattern?

If those 10K databases have some replicated tables - yes it's very bad scenario for clickhouse. 

Number of non-replicated tables / partitions can be higher, but if you will try to work with all of them simultaniously (like doing real-time inserts to all of them) - it's again becomes a serious problem. 

> if so, what is the reasonable number? 

Dozens of tables / partitions you works simultaniously all the time, do realtime inserts etc. 

Hundreds of replicated tables per system. 

Thousands of non-replicated tables / partitions which are not getting realtime inserts. 

> Also, why not have s3 storage write to different buckets based on tenant id column or attribute similar to other datastore like loki, bigquery, snowflake etc where there is clear data isolation per tenant?

The task about partitioning the s3 data by some column (inside single bucket) is in the backlog. The task about splitting data to different buckets can be considered for future.

But for current state of art it is not straight forward and may require changing some architectural decicions.

ClickHouse has different origin, it's not initially designed for s3. It's slowly moving in that direction, but main storage for clickhouse is (still) local filesystems.

>  I created this ticket hoping that someone will consider the idea

It's not-practical for a current architecture.

We can keep it opened and collect more feedback / have it in the backlog for a future.  But it doesn't seems it will be possible in close future.

**Comment by kant777** [comment]
@filimonov 

I can set the replication factor to 1. when you are writing to s3 I don't think anyone wants to set replication factor to be more than 1 since s3 does its own replication and moreover the chances of s3 going down is very low. so you can leverage that fact to design a simpler solution

I think having some data isolation will be great. meaning each tenant's data in its own bucket using whatever strategy you may have will be fine

**Comment by UnamedRus** [comment]
> I can set the replication factor to 1. when you are writing to s3 I don't think anyone wants to set replication factor to be more than 1 since s3 does its own replication and moreover the chances of s3 going down is very low. so you can leverage that fact to design a simpler solution

Replication it's not only about replication of storage, but also about replication of compute.
So even if you will use only one data copy in bucket. ([zero_copy_replication](https://clickhouse.com/docs/en/operations/storing-data/#zero-copy)), it's still **Replicated** tables, which needs coordination.

**Comment by kant777** [comment]
@UnamedRus so what is the right configuration for s3 for production worklods?

**Comment by alexey-milovidov** [comment]
It is possible to configure these buckets as separate storage policies, and then have multiple tables, with each table bound to its own storage policy.
