### ISSUE TITLE
clickhouse-server-21.4.5.46 Use ReplicatedReplacingMergeTree to merge partitions to remove duplicates

### ISSUE THREAD

**Issue by mjh568412187** [ClickHouse/ClickHouse#31615]
clickhouse version： 21.4.5.46
engine：ReplicatedReplacingMergeTree

Table building statement：
`CREATE TABLE local_dim.dim_goods_full
(
     xxx
    `create_date` String COMMENT '创建时间',
    `creator` String COMMENT '创建人',
    `update_time` DateTime COMMENT '更新时间',
    `update_person` String COMMENT '更新人'
)
ENGINE = ReplicatedReplacingMergeTree('/clickhouse/{ck_writer_count}/local_dim/dim_goods_full', '{replica}', update_time)
ORDER BY goods_id
SETTINGS index_granularity = 8192
`

┌─────────update_time─┐
│ 2021-06-04 00:45:00 │
└─────────────────────┘
--
local_dim.dim_goods_full is imported from hive to clickhouse through datax

`ckshard11.yonghui.cn :) select  goods_id,update_time from local_dim.dim_goods_full
:-] where  goods_id='7947464';

SELECT
    goods_id,
    update_time
FROM local_dim.dim_goods_full
WHERE goods_id = '7947464'

Query id: 93e3d8ba-dd3c-4f87-8bca-cbaa9c7249d4

┌─goods_id─┬─────────update_time─┐
│ 7947464  │ 2019-12-30 15:22:20 │
└──────────┴─────────────────────┘
┌─goods_id─┬─────────update_time─┐
│ 7947464  │ 2019-12-30 15:21:27 │
└──────────┴─────────────────────┘

2 rows in set. Elapsed: 0.004 sec. Processed 50.18 thousand rows, 1.06 MB (11.53 million rows/s., 243.84 MB/s.) 

ckshard11.yonghui.cn :) `

In theory, only one update_time is retained, but now there are two

When I execute:
optimize table local_dim.dim_goods_full FINAL;

Enough!

**Comment by den-crane** [comment]
https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/replacingmergetree/

_Data deduplication occurs only during a merge. Merging occurs in the background at an unknown time, so you can’t plan for it. Some of the data may remain unprocessed._
