### ISSUE TITLE
ClickHouse data loss after restarting the docker service

### ISSUE THREAD

**Issue by maiguoma** [ClickHouse/ClickHouse#31621]
Use the command
$ mkdir $HOME/some_clickhouse_database
$ docker run -d --name some-clickhouse-server --ulimit nofile=262144:262144 --volume=$HOME/some_clickhouse_database:/var/lib/clickhouse yandex/clickhouse-server deployment Clickhouse-server, data after docker restart What's the reason for losing everything?

**Comment by filimonov** [comment]
Can't confirm:
```
## start clickhouse container
docker run -d --name some-clickhouse-server2 --ulimit nofile=262144:262144 --volume=$HOME/some_clickhouse_database:/var/lib/clickhouse yandex/clickhouse-server

## run bash there, and create table
docker exec -it some-clickhouse-server2 bash 
root@7c107eed6ce1:/# clickhouse-client 
create table foo engine = Log as select * from numbers(10);

## check the data is still there after restarting the container:
docker restart some-clickhouse-server2

docker exec -it some-clickhouse-server2 bash 
root@7c107eed6ce1:/# clickhouse-client 
7c107eed6ce1 :) select * from foo;
┌─number─┐
│      0 │
│      1 │
│      2 │
│      3 │
│      4 │
│      5 │
│      6 │
│      7 │
│      8 │
│      9 │
└────────┘


## check the data is still there after recreating the container

docker rm -f some-clickhouse-server2 
 docker run -d --name some-clickhouse-server2 --ulimit nofile=262144:262144 --volume=$HOME/some_clickhouse_database:/var/lib/clickhouse yandex/clickhouse-server
568f013767d5be6e81773166c1c8b6a5d3253236f54ed6bd992bf63e61e0951f
mfilimonov@laptop-5591:~/workspace/ClickHouse/master$ docker exec -it some-clickhouse-server2 bash 
root@568f013767d5:/# clickhouse-client 
ClickHouse client version 21.11.4.14 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 21.11.4 revision 54450.

568f013767d5 :) select * from foo;

SELECT *
FROM foo

Query id: bb954029-dc44-4ccb-9ffd-6375157e37f1

┌─number─┐
│      0 │
│      1 │
│      2 │
│      3 │
│      4 │
│      5 │
│      6 │
│      7 │
│      8 │
│      9 │
└────────┘

10 rows in set. Elapsed: 0.003 sec. 
```

**Comment by maiguoma** [comment]
Thank you, I just solved it. It’s a table engine problem, which is stored in memory by default. I just read the document and just change to another document.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ClickHouse/ClickHouse"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月22日(星期一) 下午5:52
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [ClickHouse/ClickHouse] ClickHouse data loss after restarting the docker service (Issue #31621)





 
Can't confirm:
 ## start clickhouse container docker run -d --name some-clickhouse-server2 --ulimit nofile=262144:262144 --volume=$HOME/some_clickhouse_database:/var/lib/clickhouse yandex/clickhouse-server ## run bash there, and create table docker exec -it some-clickhouse-server2 bash  ***@***.***:/# clickhouse-client  create table foo engine = Log as select * from numbers(10); ## check the data is still there after restarting the container: docker restart some-clickhouse-server2 docker exec -it some-clickhouse-server2 bash  ***@***.***:/# clickhouse-client  7c107eed6ce1 :) select * from foo; ┌─number─┐ │      0 │ │      1 │ │      2 │ │      3 │ │      4 │ │      5 │ │      6 │ │      7 │ │      8 │ │      9 │ └────────┘ ## check the data is still there after recreating the container docker rm -f some-clickhouse-server2   docker run -d --name some-clickhouse-server2 --ulimit nofile=262144:262144 --volume=$HOME/some_clickhouse_database:/var/lib/clickhouse yandex/clickhouse-server 568f013767d5be6e81773166c1c8b6a5d3253236f54ed6bd992bf63e61e0951f ***@***.***:~/workspace/ClickHouse/master$ docker exec -it some-clickhouse-server2 bash  ***@***.***:/# clickhouse-client  ClickHouse client version 21.11.4.14 (official build). Connecting to localhost:9000 as user default. Connected to ClickHouse server version 21.11.4 revision 54450. 568f013767d5 :) select * from foo; SELECT * FROM foo Query id: bb954029-dc44-4ccb-9ffd-6375157e37f1 ┌─number─┐ │      0 │ │      1 │ │      2 │ │      3 │ │      4 │ │      5 │ │      6 │ │      7 │ │      8 │ │      9 │ └────────┘ 10 rows in set. Elapsed: 0.003 sec.   
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
