### ISSUE TITLE
ClickHouse WHERE EXISTS(subquery) fails when using main query's tables and columns in subquery

### ISSUE THREAD

**Issue by kartaris** [ClickHouse/ClickHouse#31626]
Feature described in https://github.com/ClickHouse/ClickHouse/issues/6852 works now, but fails on the next case with an exception(there is a link to the main query's table and column in subquery)

```
SELECT count()
FROM numbers(7) AS main_numbers
WHERE exists((
    SELECT sub_numbers.number
    FROM numbers(6) AS sub_numbers
    WHERE main_numbers.number > sub_numbers.number
))
```

Query id: 9d1c2731-eb31-4ba4-a3c2-9654796a307a

0 rows in set. Elapsed: 0.006 sec. 

Received exception from server (version 21.11.4):
Code: 47. DB::Exception: Received from 172.18.141.156:9000. DB::Exception: Missing columns: 'main_numbers.number' while processing query: 'SELECT number FROM numbers(6) AS sub_numbers WHERE main_numbers.number > number', required columns: 'number' 'main_numbers.number', maybe you meant: ['number']: While processing 1 IN ((SELECT 1 FROM (SELECT sub_numbers.number FROM numbers(6) AS sub_numbers WHERE main_numbers.number > sub_numbers.number) LIMIT 1) AS _subquery42). (UNKNOWN_IDENTIFIER)

**Comment by alexey-milovidov** [comment]
Correlated queries are not implemented.

**Comment by kartaris** [comment]
> Correlated queries are not implemented.

Will they be implemented sometime?

**Comment by alexey-milovidov** [comment]
Yes, not earlier than summer 2022.
