### ISSUE TITLE
`File Table Engine`  works wrong with `Parquet`, cannot read new data after multiply `INSERT`.

### ISSUE THREAD

**Issue by cmsxbc** [ClickHouse/ClickHouse#31640]
**Describe what's wrong**

If perform `Insert` multiply, just the data firstly inserted will be readable.But the appended data still eats the disk space.

**Does it reproduce on recent release?**

Yep, also reproduce in `master` branch.

**How to reproduce**

* Which ClickHouse server version to use: 21.12.1.1
* Queries to run that lead to unexpected result

```
CREATE TABLE parquet_file_engine (x Int) ENGINE=File(Parquet);
INSERT INTO parquet_file_engine VALUES (1);
INSERT INTO parquet_file_engine VALUES (2);
INSERT INTO parquet_file_engine VALUES (3);
SELECT * FROM parquet_file_engine;
```

**Current behavior**

![2021-11-23-020049_857x506_scrot](https://user-images.githubusercontent.com/3500109/142912286-6c2f44ab-7d82-4c96-acbd-329c5bc03611.png)

The `data.Parquet` appears three entire `Parquet` file. But we can only read the first one.

<img width="543" alt="parquet_duplicate" src="https://user-images.githubusercontent.com/3500109/142910943-28603f89-af8d-42e8-8316-9d3eaaa3c2a7.png">

**Expected behavior**

I'm not sure yet whether `Parquet-cpp` supports `append`. 
If it supports, make multiply `INSERT` works right. If not, throw an Exception to tell user cannot append data.

**Comment by alexey-milovidov** [comment]
Parquet does not support append at all, we should throw exception on subsequent INSERT attempts.

**Comment by alexey-milovidov** [comment]
It's theoretically possible to append to Parquet, but no libraries implement that.
It will require careful rewriting of the file suffix.

Also we don't support seeking inside writeable files, only appends.
Allowing partial file rewrite will break AES-CTR encryption. It will also break S3 and HDFS support.

http://parquet.apache.org/documentation/latest/

There is also a possibility to not stripping the old header, but writing new data and new combined header after it.
Maybe we can try...

**Comment by cmsxbc** [comment]
I'm curious why clickhouse only write data to a single file as  `data.<FORMAT>`, is it possible to work with multiply files ?

**Comment by Avogar** [comment]
> I'm curious why clickhouse only write data to a single file as `data.<FORMAT>`, is it possible to work with multiply files ?

You can work with multiple files by using `file` table function. For example:
```sql
:) insert into table function file('data1.parquet', 'Parquet', 'x UInt32, y UInt32') values (1,2)
:) insert into table function file('data2.parquet', 'Parquet', 'x UInt32, y UInt32') values (2,3)
...
:) select * from file('data*.parquet', 'Parquet', 'x UInt32, y UInt32')
```
Maybe we can try to create a new file for each insert query in table with `File` engine, we will discuss it
