### ISSUE TITLE
Ontime dataset: cannot download the raw data by provided shell script = (

### ISSUE THREAD

**Issue by Felix-neko** [ClickHouse/ClickHouse#31659]
Hi folks!

It looks like the raw partitions of Ontime test dataset have moved somewhere.

Can you please host it on your server or provide correct links?

https://clickhouse.com/docs/ru/getting-started/example-datasets/ontime/#import-iz-syrykh-dannykh -- here's the shell script that tries to download'em, and it does not find them anymore.

**Comment by alexey-milovidov** [comment]
Ok, we will find out if it's permitted to redistribute this data.
Or we can do it for archival purposes that is considered a fair use.

Looks like the source is here: https://transtats.bts.gov/DL_SelectFields.asp?gnoyr_VQ=FGJ&QO_fu146_anzr=b0-gvzr

**Comment by alexey-milovidov** [comment]
```
wget --no-check-certificate --continue https://transtats.bts.gov/PREZIP/On_Time_Reporting_Carrier_On_Time_Performance_1987_present_{1987..2021}_{1..12}.zip
```

**Comment by Felix-neko** [comment]
Thank you, comrade!

Now it works. Please update this section of documentation, if possible = )

**Comment by alexey-milovidov** [comment]
https://github.com/ClickHouse/ClickHouse/commit/2d7ff774fd7cea79b9f47ee8e79cbf1215ebb979

**Comment by veeralpatel-opsramp** [comment]
FYI - if you just copy the command above into iTerm2, adds `\` (backlashes) like so:

wget --no-check-certificate --continue https://transtats.bts.gov/PREZIP/On_Time_Reporting_Carrier_On_Time_Performance_1987_present_\{1987..2021\}_\{1..12\}.zip

This command does NOT work. You need to remove those backlashes for it to work
