### ISSUE TITLE
antlr golang generation error

### ISSUE THREAD

**Issue by rossb83** [ClickHouse/ClickHouse#31650]
@abyss7 

https://github.com/ClickHouse/ClickHouse/blob/dc34ac111e4b6441771183ed5406b4005d0bb2f8/utils/antlr/ClickHouseParser.g4#L103

I have tried to generate a parser for `golang` with 

```
antlr4 -no-listener -visitor -package DB -Dlanguage=Go ClickHouseParser.g4
```

and this is generating invalid `golang` specifically there is no `std::set<std::string>` type it should be something like `map[string]interface{}`, `...insert("default")` should be `...["default"] = ""` and `.count("default")` should be something like `_, ok := ...["default"]`

```
// IDictionaryAttrDfntContext is an interface to support dynamic dispatch.
type IDictionaryAttrDfntContext interface {
	antlr.ParserRuleContext

	// GetParser returns the parser.
	GetParser() antlr.Parser

	// GetAttrs returns the attrs attribute.
	GetAttrs() std::set<std::string>


	// SetAttrs sets the attrs attribute.
	SetAttrs(std::set<std::string>)


	// IsDictionaryAttrDfntContext differentiates from other interfaces.
	IsDictionaryAttrDfntContext()
}
...
if !(!localctx.(*DictionaryAttrDfntContext).attrs.count("default")) {
...
localctx.(*DictionaryAttrDfntContext).attrs.insert("default");
...
```

Is this an `antlr4` problem?

**Comment by genzgd** [comment]
The antlr4 visitor implementation has never worked for the GoLang target, although there is a recent PR to try to fix that:  https://github.com/antlr/antlr4/pull/3299. Also see https://github.com/ClickHouse/ClickHouse/pull/25942 -- the experimental ClickHouse antlr parser and grammar are no active
