### ISSUE TITLE
[CK][PostgreSQL] 21.2.4.6 foreign table doesn't exist when created in PostgreSQL with “”  

### ISSUE THREAD

**Issue by beeflyme** [ClickHouse/ClickHouse#31682]
============ in ck client
SQL Success:  SELECT * FROM  pg_db_7_183_30_xx.tablea limit 10; 
                      
SQL Fail [60]:  select * from  pg_db_7_183_30_4."tableB" limit 10;
SQL Fail [60]:  select * from  pg_db_7_183_30_4.tableB limit 10;

ClickHouse exception, code: 60, host: 10.144.191.xx, port: 8123; Code: 60, e.displayText() = DB::Exception: Table WinBusiness.`pg_db_7_183_30_xx.tableB` doesn't exist (version 21.2.4.6 (official build))

SQL 错误 [60]: ClickHouse exception, code: 60, host: 10.144.191.xx, port: 8123; Code: 60, e.displayText() = DB::Exception: Table pg_db_7_183_30_4.tableB doesn't exist (version 21.2.4.6 (official build))

SQL 错误 [60]: ClickHouse exception, code: 60, host: 10.144.191.xx, port: 8123; Code: 60, e.displayText() = DB::Exception: Table pg_db_7_183_30_4.tableB doesn't exist (version 21.2.4.6 (official build))

the difference between the two  tables is 
 tablea create without "" in pgdatabase;
 and tableb create with "" in pgdatabase;

=============
in pg database client,  select * from tableB failed ,and  select * from "tableB" is OK.

when add "" with table name witch have big letter, pg server sensctive with the table name.
=============
I think this problem is because ck client don't send "" around table name to the postgresql

**Comment by beeflyme** [comment]
i am abt to test the latest version 21.11.4.14 .

**Comment by beeflyme** [comment]
test with 21.11.4.14 :   select * from pg_db_190_10_10_xx."cxf_S1_temp" OK
===
in the latest version the problem sloved

**Comment by kssenii** [comment]
btw to me it works both quoted and unquoted
AFAIK double quotes are likely to be ignored
```
postgres=# create table "t" (i int);
postgres=# insert into t select 1; -- ok
postgres=# insert into "t" select 1 -- ok
postgres=# select * from "t" -- ok
postgres=# select * from t -- ok


kssenii.ru-central1.internal :) create database pg engine = PostgreSQL ('localhost:5432', 'postgres', 'postgres', 'postgres');
kssenii.ru-central1.internal :) show tables from pg

SHOW TABLES FROM pg        

Query id: de9c9b0e-9f55-4b22-98d3-f6d270f08423

┌─name─┐                   
│ t    │                   
└──────┘                   

1 rows in set. Elapsed: 0.030 sec. 

kssenii.ru-central1.internal :) select * from pg.t

SELECT *
FROM pg.t

Query id: 52cf8db0-8df9-43bf-ae9d-ac4430b43578

┌─i─┐
│ 1 │
│ 1 │
└───┘

2 rows in set. Elapsed: 0.011 sec.

kssenii.ru-central1.internal :) select * from pg."t"

SELECT *
FROM pg.t

Query id: 52cf8db0-8df9-43bf-ae9d-ac4430b43578

┌─i─┐
│ 1 │
│ 1 │
└───┘

2 rows in set. Elapsed: 0.011 sec.
```

**Comment by kssenii** [comment]
> version 21.2.4.6

> in the latest version the problem sloved

Between these versions there were a lot of changes, so it is not likely to extract and backport the fix.

**Comment by beeflyme** [comment]
> btw to me it works both quoted and unquoted AFAIK double quotes are likely to be ignored
> 
> ```
> postgres=# create table "t" (i int);
> postgres=# insert into t select 1; -- ok
> postgres=# insert into "t" select 1 -- ok
> postgres=# select * from "t" -- ok
> postgres=# select * from t -- ok
> 
> 
> kssenii.ru-central1.internal :) create database pg engine = PostgreSQL ('localhost:5432', 'postgres', 'postgres', 'postgres');
> kssenii.ru-central1.internal :) show tables from pg
> 
> SHOW TABLES FROM pg        
> 
> Query id: de9c9b0e-9f55-4b22-98d3-f6d270f08423
> 
> ┌─name─┐                   
> │ t    │                   
> └──────┘                   
> 
> 1 rows in set. Elapsed: 0.030 sec. 
> 
> kssenii.ru-central1.internal :) select * from pg.t
> 
> SELECT *
> FROM pg.t
> 
> Query id: 52cf8db0-8df9-43bf-ae9d-ac4430b43578
> 
> ┌─i─┐
> │ 1 │
> │ 1 │
> └───┘
> 
> 2 rows in set. Elapsed: 0.011 sec.
> 
> kssenii.ru-central1.internal :) select * from pg."t"
> 
> SELECT *
> FROM pg.t
> 
> Query id: 52cf8db0-8df9-43bf-ae9d-ac4430b43578
> 
> ┌─i─┐
> │ 1 │
> │ 1 │
> └───┘
> 
> 2 rows in set. Elapsed: 0.011 sec.
> ```

Thank u for your reply, the test u just done is not right, just change your table t to big letter "T" pls.
----- in  pg client test begin----
 in pg when create table A, the pg store table as a; when create table "A" ,will store table "A"            
when select "A", it will look for "A"
when select a || or select A , it will select a

---- in  pg client test  end----

**Comment by kssenii** [comment]
Ok, this way also works if selecting in ch without quotes:
```
postgres=# create table "T" (i int);
postgres=# insert into "T" select 1;
```
```
kssenii.ru-central1.internal :) show tables from pg                                                                                                                                                                
                                                                                                                                                                                                                   
SHOW TABLES FROM pg                                                                                                                                                                                                
                                                                                                                                                                                                                   
Query id: 0a330f99-f2d2-4a45-9a9b-69bb1f28366f                                                                                                                                                                     
                                                                                                                                                                                                                   
┌─name─┐                                                                                                                                                                                                           
│ T    │                                                                                                                                                                                                           
│ t    │                                                                                                                                                                                                           
└──────┘                                                                                                                                                                                                           
                                                                                                                                                                                                                   
2 rows in set. Elapsed: 0.014 sec.   
                                                                                                                                                                                                                   
kssenii.ru-central1.internal :) select * from pg.T                                                                                                                                                                 
                                                                                                                                                                                                                   
SELECT *                                                                                                                                                                                                           
FROM pg.T                                                                                                                                                                                                          
                                                                                                                                                                                                                   
Query id: 710be579-aed7-4c40-9bac-d0c64591544e                                                                                                                                                                     
                                                                                                                                                                                                                   
┌─i─┐                                                                                                                                                                                                              
│ 1 │                                                                                                                                                                                                              
└───┘                                                                                                                                                                                                              
                                                                                                                                                                                                                   
1 rows in set. Elapsed: 0.011 sec. 
```

**Comment by kssenii** [comment]
@beeflyme so the issue is resolved and can be closed?

**Comment by beeflyme** [comment]
> @beeflyme so the issue is resolved and can be closed?

yes, sloved in the latest version, i test in version 21.2.4.6 the problem sloved

thank you~
