### ISSUE TITLE
DBeaver  to Clickhouse in  Kubernetes connection 

### ISSUE THREAD

**Issue by Tomislav24i** [ClickHouse/ClickHouse#31704]
I was able to connect to the clickHouse database running via independent instance on AWS with DBeaver  without problem.
But now as database is running in Kubernetes on AWS  and ClickHouse is open to public, I am not able to connect with DBeaver.
With some other apps, I do not have problem with connection.
Do I need to adjust some special setting in DBeaver  to connect to ClickHouse running in Kubernetes on AWS?

**Comment by Tomislav24i** [comment]
Yes we use clickHouse operator.

**Comment by den-crane** [comment]
@Tomislav24i you should this in their repo https://github.com/Altinity/clickhouse-operator/issues
