### ISSUE TITLE
How to give priority to INSERT queries over SELECT queries on high load

### ISSUE THREAD

**Issue by faisalhasnain** [ClickHouse/ClickHouse#31722]
We are using Clickhouse as our main data warehouse and want to make sure that incoming data being inserted in large batches does not fail. Sometimes when Clickhouse is under high load touching max memory usage, insert fails and we get timeout or too many queries errors. Is there any way to either:
1. Give priority to write queries over select queries?
2. Allocate max memory usage limit to certain user?

**Comment by alexey-milovidov** [comment]
There is `max_memory_usage_for_user` setting.
You can put all SELECT queries under a separate user and limit memory for it.

**Comment by faisalhasnain** [comment]
thank you, that's what i was looking for :)
