### ISSUE TITLE
h3ToGeo function is missing from 21.8-lts

### ISSUE THREAD

**Issue by siradjev** [ClickHouse/ClickHouse#31725]
**Describe what's wrong**

h3ToGeo function is missing from 21.8-lts, despite being implemented in July. 
Improvement was done way before that but it seems it was reverted and readded, but after readding, it was only merged appeared to 21.9 and higher. 

Reverted implementation #25593
reimplementation #25595

Not clear why it's not merged in 21.8-lts, as it was presented and added to help way before august, 2021.

**Comment by alexey-milovidov** [comment]
It was reimplemented in July, after the branch 21.8-prestable was created.
Only features before creation of the release branch are shipped for release.
Prestable branch is created one-three weeks in advance to allow users to test the upcoming release.

**Comment by alexey-milovidov** [comment]
If you want to use this function, install version 21.11.
