### ISSUE TITLE
ingest data from hdfs when table save as orc with snappy compressed type

### ISSUE THREAD

**Issue by sinlang** [ClickHouse/ClickHouse#31750]
clickhouse seen work wrong when file save as orc when compressed with snappy

**Comment by den-crane** [comment]
any proof ? any repro ?

**Comment by den-crane** [comment]
no info

**Comment by sinlang** [comment]
sorry for , i prepare a example now

first user spark-sql client  to create two table ,  test_zjj.people2 save file with snappy，  test_zjj.people1 is not 

Spark master: local[*], Application Id: local-1639529898840
spark-sql (default)> create table test_zjj.people1(
                   > name string
                   > )
                   > stored as orc;
Response code
Time taken: 2.847 seconds
spark-sql (default)> create table test_zjj.people2(
                   > name string
                   > )
                   > stored as orc;
Response code
Time taken: 0.093 seconds
spark-sql (default)> set spark.sql.orc.compression.codec=none;
key	value
spark.sql.orc.compression.codec	none
Time taken: 0.614 seconds, Fetched 1 row(s)
spark-sql (default)> insert into test_zjj.people1 values('test1');
Response code
Time taken: 2.187 seconds
spark-sql (default)> set spark.sql.orc.compression.codec=snappy;
key	value
spark.sql.orc.compression.codec	snappy
Time taken: 0.033 seconds, Fetched 1 row(s)
spark-sql (default)> insert into test_zjj.people2 values('test2');
Response code
Time taken: 0.337 seconds
spark-sql (default)> select * from test_zjj.people1;
name
test1
Time taken: 0.575 seconds, Fetched 1 row(s)
spark-sql (default)> select * from test_zjj.people2;
name
test2
Time taken: 0.169 seconds, Fetched 1 row(s)
spark-sql (default)>

then try to load data from hdfs
than create table in clickhouse

CREATE TABLE test2.people (
   name varchar
)  engine=MergeTree
order by name;

**Comment by sinlang** [comment]
file is generate by spark 2.4.7 version， snapy-java version is 1.1.7.5

**Comment by sinlang** [comment]
[admin@ATHADOOPDQ15 ~]$ file  /usr/lib64/libsnappy.so.1
/usr/lib64/libsnappy.so.1: symbolic link to `libsnappy.so.1.1.4'
