### ISSUE TITLE
clickhouse server periodly be killed because of OOM 

### ISSUE THREAD

**Issue by Johnny-Three** [ClickHouse/ClickHouse#31763]
**Version** : 
(version 21.2.5.5 (official build))

**Phenomenon:** 
After clickhouse runs for a period of time, the process was killed by system 

**Logs:**
5183761 2021.11.24 13:21:23.353194 [ 320 ] {} <Error> void DB::SystemLog<DB::MetricLogElement>::flushImpl(const std::vector<LogElement> &, uint64_t) [LogElement = DB::MetricLogElement]: Code: 241, e.displayText() = DB::Exception: Memory limit (total) exceeded: would use 86.16 GiB (attempt to allocate chunk of 4206720 bytes), maximum: 80.00 GiB, Stack trace (when copying this message, always include the lines below):
5183762
5183763 0. DB::Exception::Exception<char const*, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, long&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const*&&, char const*&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, long&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&) @ 0x84d0515 in /usr/bin/clickhouse
5183764 1. MemoryTracker::alloc(long) @ 0x84cfe6d in /usr/bin/clickhouse
5183765 2. MemoryTracker::alloc(long) @ 0x84cfbd4 in /usr/bin/clickhouse
5183766 3. operator new(unsigned long) @ 0x84bad18 in /usr/bin/clickhouse
5183767 4. void std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> >::__emplace_back_slow_path<DB::ColumnWithTypeAndName>(DB::ColumnWithTypeAndName&&) @ 0xa00dbcc in /usr/bin/clickhouse
5183768 5. DB::Block::cloneEmpty() const @ 0xe4f0a5b in /usr/bin/clickhouse
5183769 6. DB::MergeTreeDataPartWriterCompact::write(DB::Block const&, DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 15ul, 16ul> const*) @ 0xf39694e in /usr/bin/clickhouse
5183770 7. DB::MergeTreeDataWriter::writeTempPart(DB::BlockWithPartition&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, bool) @ 0xf3d2cc7 in /usr/bin/clickhouse
5183771 8. DB::MergeTreeBlockOutputStream::write(DB::Block const&) @ 0xf2f4c2e in /usr/bin/clickhouse
5183772 9. DB::PushingToViewsBlockOutputStream::write(DB::Block const&) @ 0xe9f4d0e in /usr/bin/clickhouse
5183773 10. DB::AddingDefaultBlockOutputStream::write(DB::Block const&) @ 0xe9fd38b in /usr/bin/clickhouse
5183774 11. DB::SquashingBlockOutputStream::finalize() @ 0xe9fbdec in /usr/bin/clickhouse
5183775 12. DB::SquashingBlockOutputStream::writeSuffix() @ 0xe9fbe69 in /usr/bin/clickhouse
5183776 13. DB::SystemLog<DB::MetricLogElement>::flushImpl(std::__1::vector<DB::MetricLogElement, std::__1::allocator<DB::MetricLogElement> > const&, unsigned long) @ 0xee1e3ce in /usr/bin/clickhouse
5183777 14. DB::SystemLog<DB::MetricLogElement>::savingThreadFunction() @ 0xee1c750 in /usr/bin/clickhouse
5183778 15. ThreadFromGlobalPool::ThreadFromGlobalPool<DB::SystemLog<DB::MetricLogElement>::startup()::'lambda'()>(DB::MetricLogElement&&, DB::SystemLog<DB::MetricLogElement>::startup()::'lambda'()&&...)::'lambda'()::operator()() @ 0xee1c5f6 in /usr/bin/clickhouse
5183779 16. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x84f700f in /usr/bin/clickhouse
5183780 17. ? @ 0x84faaa3 in /usr/bin/clickhouse
5183781 18. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
5183782 19. clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
5183783  (version 21.2.5.5 (official build))

**Questions:**
From the log seems it triggered OOM because want to allocate too much memory for log flush ? 
how to fix this kind of problem, thanks in advance.

**Comment by pkit** [comment]
See [here](https://github.com/ClickHouse/ClickHouse/blob/b39c19399ff951a598dd35e575c715c5c4dfb5a2/programs/server/config.xml#L274)

`config.xml`:
```
<max_server_memory_usage>0</max_server_memory_usage>
```

**Comment by Johnny-Three** [comment]
> See [here](https://github.com/ClickHouse/ClickHouse/blob/b39c19399ff951a598dd35e575c715c5c4dfb5a2/programs/server/config.xml#L274)
> 
> `config.xml`:
> 
> ```
> <max_server_memory_usage>0</max_server_memory_usage>
> ```

the setting is:
<max_server_memory_usage>85899345920</max_server_memory_usage>

which i am not quite sure is : (From the log prints)
why MetricLog flush attempt to allocate chunk of 4206720 bytes but why it would use  86.16 GiB ?

**Comment by pkit** [comment]
> the setting is:
<max_server_memory_usage>85899345920</max_server_memory_usage>
it is already set to 80G for total

Just set it to lower value.
