### ISSUE TITLE
How to create index for Map Type Column or one key of it? [version 21.8.10 revision 54449]

### ISSUE THREAD

**Issue by phhcer** [ClickHouse/ClickHouse#31801]
Test Table:
```
Create table test.test (
    partition String
    ,map_values Map(String, String)
) ENGINE = ReplicatedMergeTree()
PARTITION BY partition
ORDER BY(map_values[‘key’])
SETTINGS index_granularity = 8192
```

Test query:
```
select count(*) from test.test where map_values[‘key’] = ‘1’;
```

ClickHouse client version 21.8.10.19 (official build)
Connected to ClickHouse server version 21.8.10 revision 54449

It seems that the query would not skipped the indexes. 
How could I create index for the map type column or one key of the map type column?

**Comment by lingtaolf** [comment]
Just like below
```sql
create table map_test 
(
    id UInt32,
    map1 Map(String,String),
    Index a map1 TYPE tokenbf_v1(256, 2, 0) GRANULARITY 1
)  
Engine = MergeTree()
Order by id
```  
It only check keys of map .

**Comment by phhcer** [comment]
> Just like below
> 
> ```sql
> create table map_test 
> (
>     id UInt32,
>     map1 Map(String,String),
>     Index a map1 TYPE tokenbf_v1(256, 2, 0) GRANULARITY 1
> )  
> Engine = MergeTree()
> Order by id
> ```
> 
> It only check keys of map .

thx！I will try it.
By the way, where could I find the src code for the skipping index  implement of ColumnMap?

**Comment by phhcer** [comment]
Could you tell me the path of the project to find it?

**Comment by lingtaolf** [comment]
> Could you tell me the path of the project to find it?

@phhcer https://github.com/ClickHouse/ClickHouse/pull/28511 & https://github.com/ClickHouse/ClickHouse/pull/29220

**Comment by kitaisreal** [comment]
You can create index for map keys, or for map values. Example:
```sql
CREATE TABLE test_table
(
    id UInt64,
    value Map(Int64, String),
    index value_key_index mapKeys(value) TYPE bloom_filter GRANULARITY 4
) ENGINE=MergeTree ORDER BY id;
```
Link to documentation https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/mergetree/#available-types-of-indices.
