### ISSUE TITLE
replicatedMergetree replication crash on Update clickhouse from v.20.1.16.120  to v.21.10.2.15

### ISSUE THREAD

**Issue by deepdivenow** [ClickHouse/ClickHouse#31807]
(you don't have to strictly follow this form)

**Describe the unexpected behaviour**
Updated system can't download new partitions.
Old parts don't have this problems.

**How to reproduce**
2 servers with ReplicationMergeTree tables
Update clickhouse from v.20.1.16.120  to v.21.10.2.15 (only on one replica)

Maybe not reproducible, only one table have a problem.

**Expected behavior**

**Error message and/or stacktrace**
`21.11.25 18:42:37.079643 [ 10496 ] {} <Error> dsp_router_v2.data2_rpl: auto DB::StorageReplicatedMergeTree::processQueueEntry(ReplicatedMergeTreeQueue::SelectedEntryPtr)::(anonymous class)::operator()(DB::StorageReplicatedMergeTree::LogEntryPtr &) const: Code: 40. DB::Exception: Part 20211125_20211125_2426215_2426215_0 from ch_10 has different columns hash. (CHECKSUM_DOESNT_MATCH), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x944bdda in /usr/bin/clickhouse
1. DB::Exception::Exception<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x10723f5e in /usr/bin/clickhouse
2. DB::StorageReplicatedMergeTree::checkPartChecksumsAndAddCommitOps(std::__1::shared_ptr<zkutil::ZooKeeper> const&, std::__1::shared_ptr<DB::IMergeTreeDataPart const> const&, std::__1::vector<std::__1::shared_ptr<Coordination::Request>, std::__1::allocator<std::__1::shared_ptr<Coordination::Request> > >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::unordered_set<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >*) @ 0x11357fab in /usr/bin/clickhouse
3. DB::StorageReplicatedMergeTree::checkPartChecksumsAndCommit(DB::MergeTreeData::Transaction&, std::__1::shared_ptr<DB::IMergeTreeDataPart const> const&) @ 0x11359957 in /usr/bin/clickhouse
4. DB::StorageReplicatedMergeTree::fetchPart(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, unsigned long, std::__1::shared_ptr<zkutil::ZooKeeper>) @ 0x1138939a in /usr/bin/clickhouse
5. DB::StorageReplicatedMergeTree::executeFetch(DB::ReplicatedMergeTreeLogEntry&) @ 0x1137fc04 in /usr/bin/clickhouse
6. DB::StorageReplicatedMergeTree::executeLogEntry(DB::ReplicatedMergeTreeLogEntry&) @ 0x1135df6f in /usr/bin/clickhouse
7. ? @ 0x11424f3f in /usr/bin/clickhouse
8. DB::ReplicatedMergeTreeQueue::processEntry(std::__1::function<std::__1::shared_ptr<zkutil::ZooKeeper> ()>, std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&, std::__1::function<bool (std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&)>) @ 0x117f312c in /usr/bin/clickhouse
9. DB::StorageReplicatedMergeTree::processQueueEntry(std::__1::shared_ptr<DB::ReplicatedMergeTreeQueue::SelectedEntry>) @ 0x113ac63d in /usr/bin/clickhouse
10. ? @ 0x11586877 in /usr/bin/clickhouse
11. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0x948fb98 in /usr/bin/clickhouse
12. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()&&...)::'lambda'()::operator()() @ 0x949173f in /usr/bin/clickhouse
13. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x948ce7f in /usr/bin/clickhouse
14. ? @ 0x9490763 in /usr/bin/clickhouse
15. start_thread @ 0x76db in /lib/x86_64-linux-gnu/libpthread-2.27.so
16. __clone @ 0x121a3f in /lib/x86_64-linux-gnu/libc-2.27.so
 (version 21.10.2.15 (official build))
`

**Additional context**
1. It's OK? update node by node ReplicationMergeTree Tables, I didn't find recommended behavior.
2. I found this code in CH https://github.com/ClickHouse/ClickHouse/blob/f320a404e0c6b7c11966dfc7acc5abe9700d66f1/src/Storages/StorageReplicatedMergeTree.cpp#L1343-L1349
How I can check this checksums from console? 
3. How expect  which replicas is source of problems old|new version?
4. How repair replica?

**Comment by den-crane** [comment]
These error are expected during upgrade because replicas with different versions produce different parts with different checksums but parts are compatible. After upgrade this issue will be automatically resolved. Replica will fetch from another replica.
