### ISSUE TITLE
Segfault in `~TCPHandler()`

### ISSUE THREAD

**Issue by longlizl** [ClickHouse/ClickHouse#31836]
2021.11.25 23:10:50.715403 [ 4269 ] {} <Error> ServerErrorHandler: Poco::Exception. Code: 1000, e.code() = 107, e.displayText() = Net Exception: Socket is not connected, Stack trace (when copying this message,
 always include the lines below):

0. Poco::Net::SocketImpl::error(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x11f767de in /usr/bin/clickhouse
1. Poco::Net::SocketImpl::peerAddress() @ 0x11f78a56 in /usr/bin/clickhouse
2. DB::ReadBufferFromPocoSocket::ReadBufferFromPocoSocket(Poco::Net::Socket&, unsigned long) @ 0xeb4e38d in /usr/bin/clickhouse
3. DB::TCPHandler::runImpl() @ 0xf8b7bde in /usr/bin/clickhouse
4. DB::TCPHandler::run() @ 0xf8cad69 in /usr/bin/clickhouse
5. Poco::Net::TCPServerConnection::start() @ 0x11f7d83f in /usr/bin/clickhouse
6. Poco::Net::TCPServerDispatcher::run() @ 0x11f7f251 in /usr/bin/clickhouse
7. Poco::PooledThread::run() @ 0x120b5979 in /usr/bin/clickhouse
8. Poco::ThreadImpl::runnableEntry(void*) @ 0x120b17da in /usr/bin/clickhouse
9. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
10. clone @ 0xfe9fd in /usr/lib64/libc-2.17.so
 (version 21.3.3.14 (official build))
2021.11.25 23:10:50.715566 [ 32196 ] {} <Trace> BaseDaemon: Received signal 11
2021.11.25 23:10:50.715738 [ 22777 ] {} <Fatal> BaseDaemon: ########################################
2021.11.25 23:10:50.715779 [ 22777 ] {} <Fatal> BaseDaemon: (version 21.3.3.14 (official build), build id: 7C39F44C9AD4D3BA36D74775616894F60A552276) (from thread 4269) (no query) Received signal Segmentation f
ault (11)
2021.11.25 23:10:50.715804 [ 22777 ] {} <Fatal> BaseDaemon: Address: 0x8 Access: read. Address not mapped to object.
2021.11.25 23:10:50.715820 [ 22777 ] {} <Fatal> BaseDaemon: Stack trace: 0xf8b42e9 0xf8b7a99 0x11f7f266 0x120b5979 0x120b17da 0x7f7a356e5ea5 0x7f7a3540e9fd
2021.11.25 23:10:50.715858 [ 22777 ] {} <Fatal> BaseDaemon: 1. DB::TCPHandler::~TCPHandler() @ 0xf8b42e9 in /usr/bin/clickhouse
2021.11.25 23:10:50.715872 [ 22777 ] {} <Fatal> BaseDaemon: 2. DB::TCPHandler::~TCPHandler() @ 0xf8b7a99 in /usr/bin/clickhouse
2021.11.25 23:10:50.715887 [ 22777 ] {} <Fatal> BaseDaemon: 3. Poco::Net::TCPServerDispatcher::run() @ 0x11f7f266 in /usr/bin/clickhouse
2021.11.25 23:10:50.715901 [ 22777 ] {} <Fatal> BaseDaemon: 4. Poco::PooledThread::run() @ 0x120b5979 in /usr/bin/clickhouse
2021.11.25 23:10:50.715916 [ 22777 ] {} <Fatal> BaseDaemon: 5. Poco::ThreadImpl::runnableEntry(void*) @ 0x120b17da in /usr/bin/clickhouse
2021.11.25 23:10:50.715932 [ 22777 ] {} <Fatal> BaseDaemon: 6. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
2021.11.25 23:10:50.715966 [ 22777 ] {} <Fatal> BaseDaemon: 7. clone @ 0xfe9fd in /usr/lib64/libc-2.17.so
2021.11.25 23:10:50.819638 [ 22777 ] {} <Fatal> BaseDaemon: Checksum of the binary: 11A63B17AD9F07EA53F49019A0B82E36, integrity check passed.
2021.11.25 23:10:50.819749 [ 22777 ] {} <Information> SentryWriter: Not sending crash report
2021.11.25 23:10:51.145451 [ 22779 ] {} <Trace> TCPHandlerFactory: TCP Request. Address: [::ffff:45.148.10.241]:55400
2021.11.25 23:10:51.145767 [ 22779 ] {} <Error> ServerErrorHandler: Code: 101, e.displayText() = DB::NetException: Unexpected packet from client, Stack trace (when copying this message, always include the line
s below):

Problem phenomenon:
It has been running very well before, but it has not happened twice in the past few days. Tasks run by flink can’t connect to clickhouse, then clickhouse will restart automatically

2021.11.25 23:11:10.757588 [ 32194 ] {} <Fatal> Application: Child process was terminated by signal 11.
2021.11.25 23:11:41.047668 [ 22940 ] {} <Information> Application: Will watch for the process with pid 22941
2021.11.25 23:11:41.047757 [ 22941 ] {} <Information> Application: Forked a child process to watch
2021.11.25 23:11:41.048038 [ 22941 ] {} <Information> SentryWriter: Sending crash reports is disabled
2021.11.25 23:11:41.048139 [ 22941 ] {} <Trace> Pipe: Pipe capacity is 1.00 MiB
2021.11.25 23:11:41.102139 [ 22941 ] {} <Information> : Starting ClickHouse 21.3.3.14 with revision 54448, build id: 7C39F44C9AD4D3BA36D74775616894F60A552276, PID 22941
2021.11.25 23:11:41.102261 [ 22941 ] {} <Information> Application: starting up
2021.11.25 23:11:41.278762 [ 22941 ] {} <Information> Application: Calculated checksum of the binary: 11A63B17AD9F07EA53F49019A0B82E36, integrity check passed.
2021.11.25 23:11:41.278911 [ 22941 ] {} <Trace> Application: Will do mlock to prevent executable memory from being paged out. It may take a few seconds.
2021.11.25 23:11:41.293572 [ 22941 ] {} <Trace> Application: The memory map of clickhouse executable has been mlock'ed, total 180.98 MiB
2021.11.25 23:11:41.294434 [ 22941 ] {} <Information> StatusFile: Status file /var/lib/clickhouse/status already exists - unclean restart. Contents:
PID: 32195
Started at: 2021-11-23 08:02:37
Revision: 54448

Hope to get help！

**Comment by tavplubix** [comment]
Fixed in  #22591
