### ISSUE TITLE
Compact or Wide Storage ?

### ISSUE THREAD

**Issue by zqw961025** [ClickHouse/ClickHouse#31841]
hello Data storage format is controlled by the min_bytes_for_wide_part  and min_rows_for_wide_part  Settings of the MergeTree table.
What I want to know is if I don't set these two parameters, what are their default values, that is, how much more data does my table have to go from Compact to Wide.

**Comment by zxealous** [comment]
M(UInt64, min_bytes_for_wide_part, 10485760, "Minimal uncompressed size in bytes to create part in wide format instead of compact", 0) \
    M(UInt64, min_rows_for_wide_part, 0, "Minimal number of rows to create part in wide format instead of compact", 0) \

**Comment by alexey-milovidov** [comment]
By default, compact storage is used only for small parts.
