### ISSUE TITLE
Skip index file

### ISSUE THREAD

**Issue by zqw961025** [ClickHouse/ClickHouse#31845]
I want to know more about the skip index, but when I look at the skp_idx_[cloumn].idx file, I can't understand the contents because it is binary, is there any command to view the file?

**Comment by genzgd** [comment]
Unfortunately there is not a command or tool to independently view the data in a skip index file.  In addition the binary format differs by skip index type -- the values for a bloom filter index are stored differently than the simpler minmax index.  The actual serialization is controlled by the implementation of IMergeTreeIndexGranule for each index type -- see, for example, the relatively simple function `MergeTreeIndexGranuleMinMax::serializeBinary` in `MergeTreeIndexMinMax.cpp`.
