### ISSUE TITLE
Executable UDFs: Cannot write to file: Broken pipe

### ISSUE THREAD

**Issue by Dong-GuoSheng** [ClickHouse/ClickHouse#31846]
Clickhouse version 21.11

cat /etc/clickhouse-server/java_function.xml 
```xml
<clickhouse>
  <function>
    <type>executable_pool</type>
    <name>sentenceScore_java</name>
    <return_type>String</return_type>
    <argument>
        <type>String</type>
    </argument>
    <format>TabSeparated</format>
    <command>/usr/bin/java -jar /var/lib/clickhouse/user_scripts/sentence_java_analyzer.jar</command>
    <send_chunk_header>0</send_chunk_header>
  </function>
</clickhouse>
```

then java file:
```
public static void main(String[] args) {
		// TODO Auto-generated method stub

		try {
			DataInputStream in = new DataInputStream(new BufferedInputStream(System.in));
			String s;

			while ((s = in.readLine()).length() != 0) {
				System.out.println("input:" + s);
				break;
			}
		} catch (Exception e) {
			e.printStackTrace();
		}

		System.out.flush();
	}
```
then export to jar。

Sometimes it succeeds, sometimes it fails; if it is executed continuously, there will be more failures and less success.

then sucess log:
Query id: 2ade89f1-a500-4d0c-afee-52c1b08c8213

[DZ01240] 2021.11.26 11:34:44.063955 [ 5035 ] {2ade89f1-a500-4d0c-afee-52c1b08c8213} <Debug> executeQuery: (from [::1]:34914) SELECT sentenceScore_java('3a') as score;
[DZ01240] 2021.11.26 11:34:44.064134 [ 5035 ] {2ade89f1-a500-4d0c-afee-52c1b08c8213} <Trace> ShellCommand: Will start shell command '/bin/sh' with arguments '/bin/sh', '-c', '/usr/bin/java -jar /var/lib/clickhouse/user_scripts/sentence_java_analyzer.jar'
[DZ01240] 2021.11.26 11:34:44.064271 [ 5035 ] {2ade89f1-a500-4d0c-afee-52c1b08c8213} <Trace> ShellCommand: Started shell command '/bin/sh' with pid 8525
[DZ01240] 2021.11.26 11:34:44.154868 [ 5035 ] {2ade89f1-a500-4d0c-afee-52c1b08c8213} <Trace> ContextAccess (default): Access granted: SELECT(dummy) ON system.one
[DZ01240] 2021.11.26 11:34:44.154970 [ 5035 ] {2ade89f1-a500-4d0c-afee-52c1b08c8213} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
┌─score────┐
│ input:3a │
└──────────┘
[DZ01240] 2021.11.26 11:34:44.155604 [ 5035 ] {2ade89f1-a500-4d0c-afee-52c1b08c8213} <Information> executeQuery: Read 1 rows, 1.00 B in 0.091614802 sec., 10 rows/sec., 10.92 B/sec.
[DZ01240] 2021.11.26 11:34:44.155683 [ 5035 ] {2ade89f1-a500-4d0c-afee-52c1b08c8213} <Debug> MemoryTracker: Peak memory usage (for query): 0.00 B.

1 rows in set. Elapsed: 0.092 sec. 

**the failed log:**
Query id: b407e367-8deb-43a6-9f59-60295732503a

[DZ01240] 2021.11.26 11:34:42.919633 [ 5035 ] {b407e367-8deb-43a6-9f59-60295732503a} <Debug> executeQuery: (from [::1]:34914) SELECT sentenceScore_java('3a') as score;
[DZ01240] 2021.11.26 11:34:42.920345 [ 5035 ] {b407e367-8deb-43a6-9f59-60295732503a} <Trace> ShellCommand: Try wait for shell command pid (8501) with timeout (10)
[DZ01240] 2021.11.26 11:34:42.920773 [ 5035 ] {b407e367-8deb-43a6-9f59-60295732503a} <Error> executeQuery: Code: 75. DB::ErrnoException: Cannot write to file (fd = 156), errno: 32, strerror: Broken pipe: While executing ShellCommandSource: While processing sentenceScore_java('3a') AS score. (CANNOT_WRITE_TO_FILE_DESCRIPTOR) (version 21.11.3.6 (official build)) (from [::1]:34914) (in query: SELECT sentenceScore_java('3a') as score;), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x9b63054 in /usr/bin/clickhouse
1. DB::throwFromErrnoWithPath(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int) @ 0x9b64429 in /usr/bin/clickhouse
2. DB::WriteBufferFromFileDescriptor::nextImpl() @ 0x9bcecfc in /usr/bin/clickhouse
3. DB::IOutputFormat::flush() @ 0x131420dc in /usr/bin/clickhouse
4. DB::formatBlock(std::__1::shared_ptr<DB::IOutputFormat>, DB::Block const&) @ 0x1310284e in /usr/bin/clickhouse
5. DB::UserDefinedFunction::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const::'lambda'()::operator()() const @ 0x1270c9ba in /usr/bin/clickhouse
6. ThreadFromGlobalPool::ThreadFromGlobalPool<DB::ShellCommandSource::ShellCommandSource(std::__1::shared_ptr<DB::Context const>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Block const&, std::__1::unique_ptr<DB::ShellCommand, std::__1::default_delete<DB::ShellCommand> >&&, std::__1::vector<std::__1::function<void ()>, std::__1::allocator<std::__1::function<void ()> > >&&, DB::ShellCommandSourceConfiguration const&, std::__1::shared_ptr<BorrowedObjectPool<std::__1::unique_ptr<DB::ShellCommand, std::__1::default_delete<DB::ShellCommand> > > >)::'lambda'()>(DB::ShellCommandSource::ShellCommandSource(std::__1::shared_ptr<DB::Context const>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Block const&, std::__1::unique_ptr<DB::ShellCommand, std::__1::default_delete<DB::ShellCommand> >&&, std::__1::vector<std::__1::function<void ()>, std::__1::allocator<std::__1::function<void ()> > >&&, DB::ShellCommandSourceConfiguration const&, std::__1::shared_ptr<BorrowedObjectPool<std::__1::unique_ptr<DB::ShellCommand, std::__1::default_delete<DB::ShellCommand> > > >)::'lambda'()&&)::'lambda'()::operator()() @ 0x100682ef in /usr/bin/clickhouse
7. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x9ba5117 in /usr/bin/clickhouse
8. ? @ 0x9ba8b1d in /usr/bin/clickhouse
9. start_thread @ 0x7fa3 in /usr/lib/x86_64-linux-gnu/libpthread-2.28.so
10. clone @ 0xf960f in /usr/lib/x86_64-linux-gnu/libc-2.28.so

0 rows in set. Elapsed: 0.002 sec. 

Received exception from server (version 21.11.3):
Code: 75. DB::Exception: Received from localhost:9000. DB::Exception: Cannot write to file (fd = 156), errno: 32, strerror: Broken pipe: While executing ShellCommandSource: While processing sentenceScore_java('3a') AS score. (CANNOT_WRITE_TO_FILE_DESCRIPTOR)

**Comment by tavplubix** [comment]
I've seen a lot of similar failures in our CI, for example https://clickhouse-test-reports.s3.yandex.net/0/351c7bc8d62686cced9c967bc364a9d55871d94a/integration_tests_(asan).html#fail1
It does not seem to be relate to java, probably there's a bug in executable UDFs implementation in ClickHouse

**Comment by Dong-GuoSheng** [comment]
Thank you, and look forward to more feedback and bug fixes in the future

**Comment by yunfeng79** [comment]
@Dong-GuoSheng  DB::Exception: Unknown function sentenceScore_java: While processing sentenceScore_java('3a') AS score.What is the reason?

**Comment by Dong-GuoSheng** [comment]
这个问题我也遇到过，是对应的“function.xml”中的“command”不是全路径引起的；官网提供的资料里面使用的是相对路径，改成绝对路径就行了。

**Comment by Dong-GuoSheng** [comment]
这个是我写的udf的名称，你应该无法直接访问的。
如果你也遇到“Unknown function xxx: While processing……” ，可能是对应的“function.xml”中的“command”不是全路径引起的；官网提供的资料里面使用的是相对路径，改成绝对路径就行了。

**Comment by Dong-GuoSheng** [comment]
> @Dong-GuoSheng DB::Exception: Unknown function sentenceScore_java: While processing sentenceScore_java('3a') AS score.What is the reason?

这个是我写的udf的名称，你应该无法直接访问的。
如果你也遇到“Unknown function xxx: While processing……” ，可能是对应的“function.xml”中的“command”不是全路径引起的；官网提供的资料里面使用的是相对路径，改成绝对路径就行了。

**Comment by yunfeng79** [comment]
@Dong-GuoSheng 我使用的是绝对路径，jar命令中绝对路径是可以验证程序是没问题的。

**Comment by yunfeng79** [comment]
@Dong-GuoSheng 怎么联系你，一起交流下

**Comment by Dong-GuoSheng** [comment]
总是成功吗？
我的验证是：成功一次，失败一次；然后循环成功和失败。

**Comment by yunfeng79** [comment]
@Dong-GuoSheng 是的，实现出来了

**Comment by kitaisreal** [comment]
It is not an issue with UDF, but an issue with script.
config.xml
```xml
<user_defined_executable_functions_config>*_function.xml</user_defined_executable_functions_config>
```
test_function.xml
```xml
<functions>

    <function>
        <type>executable</type>
        <name>test_function_java</name>
        <return_type>String</return_type>
        <argument>
            <type>String</type>
        </argument>
        <format>TabSeparated</format>
        <command>test_java.sh</command>
        <execute_direct>1</execute_direct>
    </function>

</functions>
```
If `execute_direct` = 1, then `command` will be searched inside user_scripts folder. Additional script arguments can be specified using whitespace separator. Example `<command>script_name arg1 arg2</command>`. Starting from `execute_direct` is 1 by default for executable UDF. Before you must specify full path to your script command.

Main.java
```java
import java.io.DataInputStream;
import java.io.BufferedInputStream;

public class Main {

    public static void main(String[] args) {
        try {
            DataInputStream in = new DataInputStream(new BufferedInputStream(System.in));
            String s;

            while ((s = in.readLine()).length() != 0) {
                System.out.println("input:" + s);
            }

            System.out.flush();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
```

manifest.mf
```
Manifest-version: 1.0
Main-Class: Main
```

Compile and make jar.
```
javac Main.java
jar cfm main.jar manifest.mf Main.class
```

Run function from ClickHouse.

```sql
SELECT test_function_java(toString(a)) as test_function_output, arrayJoin([1, 2, 3]) as a

SELECT
    test_function_java(toString(a)) AS test_function_output,
    arrayJoin([1, 2, 3]) AS a

Query id: df071146-aaec-4c5f-9b98-a6c8a36c65fe

┌─test_function_output─┬─a─┐
│ input:1              │ 1 │
│ input:2              │ 2 │
│ input:3              │ 3 │
└──────────────────────┴───┘
```

**Comment by windylcx** [comment]
> ```
> test_java.sh
> ```

what's the content of test_java.sh?  could you pls show the complete code?

**Comment by kitaisreal** [comment]
This script just run `/usr/bin/java -jar path_to_jar`. Where `path_to_jar` is path to your `jar` file.
Assume that you put your `main.jar` into `user_scripts` folder. You need to put `test_java.sh` into user scripts folder.

Then script can look like this for example.
test_java.sh
```bash
#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
/usr/bin/java -jar $SCRIPT_DIR/main.jar
```

**Comment by windylcx** [comment]
> This script just run `/usr/bin/java -jar path_to_jar`. Where `path_to_jar` is path to your `jar` file. Assume that you put your `main.jar` into `user_scripts` folder. You need to put `test_java.sh` into user scripts folder.
> 
> Then script can look like this for example. test_java.sh
> 
> ```shell
> #!/bin/bash
> 
> SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
> /usr/bin/java -jar $SCRIPT_DIR/main.jar
> ```

thanks for reply, i did the same thing,but it doens't work ,still Cannot write to file: Broken pipe

**Comment by windylcx** [comment]
] 2022.11.09 14:13:11.692757 [ 68256 ] {91794b6f-e9cd-431a-b450-3aaec4ba2ece} <Debug> executeQuery: (from *************:34348, user: data_dev) select getIpInfo('1');
[] 2022.11.09 14:13:11.693320 [ 68256 ] {91794b6f-e9cd-431a-b450-3aaec4ba2ece} <Trace> ShellCommand: Will start shell command '/clickhouse/node1/user_scripts//main.sh' with arguments '/clickhouse/node1/user_scripts//main.sh'
[] 2022.11.09 14:13:11.693749 [ 68256 ] {91794b6f-e9cd-431a-b450-3aaec4ba2ece} <Trace> ShellCommand: Started shell command '/clickhouse/node1/user_scripts//main.sh' with pid 36057
[] 2022.11.09 14:13:11.694333 [ 68256 ] {91794b6f-e9cd-431a-b450-3aaec4ba2ece} <Trace> ParallelParsingInputFormat: Parallel parsing is used
[] 2022.11.09 14:13:11.707261 [ 68256 ] {91794b6f-e9cd-431a-b450-3aaec4ba2ece} <Trace> ShellCommand: Try wait for shell command pid 36057 with timeout 10
[] 2022.11.09 14:13:11.708154 [ 68256 ] {91794b6f-e9cd-431a-b450-3aaec4ba2ece} <Error> executeQuery: Code: 1. DB::Exception: Function 'getIpInfo': wrong result, expected 1 row(s), actual 0: While processing getIpInfo('1'). (UNSUPPORTED_METHOD) (version 22.3.2.1) (from *************:34348) (in query: select getIpInfo('1');), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa4dde1a in /usr/lib/debug/.build-id/b5/37afa18eac3af4.debug
1. DB::Exception::Exception<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned long&, unsigned long&>(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, unsigned long&, unsigned long&) @ 0x11815894 in /usr/lib/debug/.build-id/b5/37afa18eac3af4.debug
2. DB::UserDefinedFunction::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x148976f3 in /usr/lib/debug/.build-id/b5/37afa18eac3af4.debug
3. DB::IFunction::executeImplDryRun(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0xc9bcaca in /usr/lib/debug/.build-id/b5/37afa18eac3af4.debug
4. DB::FunctionToExecutableFunctionAdaptor::executeDryRunImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0xc9bb98e in /usr/lib/debug/.build-id/b5/37afa18eac3af4.debug
5. DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x139cbf45 in /usr/lib/debug/.build-id/b5/37afa18eac3af4.debug
6. DB::IExecutableFunction::defaultImplementationForConstantArguments(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x139cb90a in /usr/lib/debug/.build-id/b5/37afa18eac3af4.debug
7. DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x139cbf05 in /usr/lib/debug/.build-id/b5/37afa18eac3af4.debug
8. DB::IExecutableFunction::executeWithoutSparseColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x139cc588 in /usr/lib/debug/.build-id/b5/37afa18eac3af4.debug
9. DB::IExecutableFunction::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x139cd68f in /usr/lib/debug/.build-id/b5/37afa18eac3af4.debug
10. DB::ActionsDAG::addFunction(std::__1::shared_ptr<DB::IFunctionOverloadResolver> const&, std::__1::vector<DB::ActionsDAG::Node const*, std::__1::allocator<DB::ActionsDAG::Node const*> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) @ 0x1403a557 in /usr/lib/debug/.build-id/b5/37afa18eac3af4.debug
11. DB::ScopeStack::addFunction(std::__1::shared_ptr<DB::IFunctionOverloadResolver> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) @ 0x141e4ec5 in /usr/lib/debug/.build-id/b5/37afa18eac3af4.debug
12. DB::ActionsMatcher::visit(DB::ASTFunction const&, std::__1::shared_ptr<DB::IAST> const&, DB::ActionsMatcher::Data&) @ 0x141eaa98 in /usr/lib/debug/.build-id/b5/37afa18eac3af4.debug
13. DB::ActionsMatcher::visit(DB::ASTExpressionList&, std::__1::shared_ptr<DB::IAST> const&, DB::ActionsMatcher::Data&) @ 0x141ed778 in /usr/lib/debug/.build-id/b5/37afa18eac3af4.debug
14. DB::InDepthNodeVisitor<DB::ActionsMatcher, true, false, std::__1::shared_ptr<DB::IAST> const>::visit(std::__1::shared_ptr<DB::IAST> const&) @ 0x141bb337 in /usr/lib/debug/.build-id/b5/37afa18eac3af4.debug
15. DB::ExpressionAnalyzer::getRootActions(std::__1::shared_ptr<DB::IAST> const&, bool, std::__1::shared_ptr<DB::ActionsDAG>&, bool) @ 0x141bb138 in /usr/lib/debug/.build-id/b5/37afa18eac3af4.debug
16. DB::SelectQueryExpressionAnalyzer::appendSelect(DB::ExpressionActionsChain&, bool) @ 0x141c7109 in /usr/lib/debug/.build-id/b5/37afa18eac3af4.debug
17. DB::ExpressionAnalysisResult::ExpressionAnalysisResult(DB::SelectQueryExpressionAnalyzer&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, bool, bool, bool, std::__1::shared_ptr<DB::FilterDAGInfo> const&, DB::Block const&) @ 0x141cbd2d in /usr/lib/debug/.build-id/b5/37afa18eac3af4.debug
