### ISSUE TITLE
Different results for native and http interfaces.

### ISSUE THREAD

**Issue by yackushevas** [ClickHouse/ClickHouse#31857]
**Describe what's wrong**

```
clickhouse-client -d database -q 'SELECT stream FROM table WHERE timestamp >= 1637762034 AND timestamp <= 1637859234' | wc -l
1000052
```

```
curl -s -H "X-ClickHouse-User: user" -H "X-ClickHouse-Key: password" -H "X-ClickHouse-Database: database" 'localhost:8123/?query=SELECT+stream+FROM+table+WHERE+timestamp+%3E%3D+1637762034+AND+timestamp+%3C%3D+1637859234' | wc -l
971012
```
(The same result gives a request via go net/http: 971012)

ClickHouse client version 21.11.3.6 (official build).

**How to reproduce**

Make a query that displays more than 100K lines through the native interface and http. Count the number of lines in the answer in both cases.

**Expected behavior**

The same number of lines in the response for native and http.

**Additional context**

The first 10 lines (head - n 10) are the same for both interfaces.

**Comment by yackushevas** [comment]
Checked https://github.com/ClickHouse/clickhouse-go – the results are the same with http.
Looks like a problem in the clickhouse-client.

**Comment by den-crane** [comment]
Check that a user is the same in all cases

**Comment by yackushevas** [comment]
> Check that a user is the same in all cases

Yes, the user is the same.

**Comment by yackushevas** [comment]
> > Check that a user is the same in all cases
> 
> Yes, the user is the same.
I was wrong, users are different (and different results, I will compare the rights).

**Comment by den-crane** [comment]
Check `system.settings where changed`, `show row policies`

**Comment by yackushevas** [comment]
I found the difference (and the reason):
If you set use_uncompressed_cache to 1
```
clickhouse-client -u user --password  -d database -q 'SELECT stream FROM table WHERE timestamp >= 1637903310 AND timestamp <= 1637914469 ORDER BY timestamp ASC' | wc -l
9691
```

If you set use_uncompressed_cache to 0
```
clickhouse-client -u user --password  -d database -q 'SELECT stream FROM table WHERE timestamp >= 1637903310 AND timestamp <= 1637914469 ORDER BY timestamp ASC' | wc -l
19181
```

**Comment by den-crane** [comment]
https://github.com/ClickHouse/ClickHouse/pull/31826

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/31449
