### ISSUE TITLE
Prometheus does not show metrics.

### ISSUE THREAD

**Issue by JackyWoo** [ClickHouse/ClickHouse#31863]
(you don't have to strictly follow this form)

**Describe the unexpected behaviour**
Prometheus does not show metrics.

**How to reproduce**
* Which ClickHouse server version to use  21.8
* Set network interface name to `irbr0-nic`
* Set up prometheus and clickhouse 
* Send some query to clickhouse
* Then no metircs appears

**Expected behavior**
There should be metics like `ClickHouseAsyncMetrics_NetworkSendBytes_virbr0-nic`.

**Comment by den-crane** [comment]
It's already fixed in 21.8.

Prometheus lables cannot contain dash "-", Clickhouse automatically replaces all dashes "-" with underscores "_".

ClickHouseAsyncMetrics_NetworkSendBytes_virbr0-nic -> ClickHouseAsyncMetrics_NetworkSendBytes_virbr0_nic

**Comment by JackyWoo** [comment]
@den-crane Thanks for reply. Version 21.8 does not handle case `irbr0-nic` [details](https://github.com/ClickHouse/ClickHouse/blob/3b2d037411cfec5e868211bfd79a4cec0ff0a0e3/src/Server/PrometheusMetricsWriter.cpp#L27-L30), but the master handles all the bad case.
