### ISSUE TITLE
PreparedStatement is not able to insert data having dateTime in record. 

### ISSUE THREAD

**Issue by DipalPrajapati** [ClickHouse/ClickHouse#31884]
While implementing a job in Java using JDBC api , I am facing issue with PreparedStatement(INSERT) 

`                query = "Insert into db.tablename values (?,`parseDateTimeBestEffortOrNull`(?))";

ru.yandex.clickhouse.except.ClickHouseException: ClickHouse exception, code: 27, host: clickhouse-distributed.clickhouse.svc.kubernetes.local, port: 8443; Code: 27, e.displayText() = DB::Exception: Cannot parse input: expected '\n' before: 'ortOrNull(2021-11-10T05:21:53\n': (at row 1)

Row 1:
Column 0,   name: field  ,  type: FixedString(150), parsed text: "+256300000009"
Column 1,   name: lastTimeAvailable, type: DateTime,         parsed text: "arseDateTimeBestEff"
ERROR: garbage after DateTime: "ortOrNull("
ERROR: DateTime must be in YYYY-MM-DD hh:mm:ss or NNNNNNNNNN (unix timestamp, exactly 10 digits) format.`

**Comment by den-crane** [comment]
ask this in https://github.com/ClickHouse/ClickHouse
It's not Clickhouse server issue

**Comment by tavplubix** [comment]
> ask this in https://github.com/ClickHouse/ClickHouse

Probably you mean https://github.com/ClickHouse/clickhouse-jdbc

**Comment by den-crane** [comment]
yes. My mistake.

**Comment by DipalPrajapati** [comment]
OK  you can close this.
