### ISSUE TITLE
Best way to start/stop clickhouse

### ISSUE THREAD

**Issue by sigirisetti** [ClickHouse/ClickHouse#31906]
Hi, 

I am referring to https://clickhouse.com/docs/en/getting-started/install/. Trying to figure out best way to start/stop clickhouse server

"sudo service clickhouse-server start" - using this command I assume root user is used to start server

If linux sysadmin objects can we use clickhouse user to start server. clickhouse user/group is created during install and all clickhouse folders ownership is transferred to clickhouse user/group. Is clickhouse user fully setup to run  server stop/start and all other  management ops 

Please kindly reply

Thanks

**Comment by den-crane** [comment]
Your question is not related to Clickhouse. 
ClickHouse in this case is a system service the same as SSH or Mysql.
If you setup requires ROOT privileges to start mysql service then it will be the same with Clickhouse service.

You don't need   ROOT privileges to run ClickHouse process but you need privileges to use services.

**Comment by sigirisetti** [comment]
Thank you
