### ISSUE TITLE
Make polling of system metrics opt-in

### ISSUE THREAD

**Issue by nahsi** [ClickHouse/ClickHouse#31947]
ClickHouse is a database, not a monitoring agent. Polling of system metrics like hwmon sensors should be opt-in.
![image](https://user-images.githubusercontent.com/28529663/143828328-b657287a-063c-4565-ad52-861b636fd940.png)

**Comment by alexey-milovidov** [comment]
As long as opt-out is possible and easy - it is alright.

**Comment by vitamin-caig** [comment]
How to opt-out system metrics polling? Log is permanently spammed with 'Cannot read from file /sys/class/hwmon...' messages.
