### ISSUE TITLE
Materialized Views Columns limit

### ISSUE THREAD

**Issue by rsaphala** [ClickHouse/ClickHouse#31953]
Are there any limitations regarding the amount of columns one can create in an MV ? How much memory will it take to process inserts?

From this issue https://github.com/ClickHouse/ClickHouse/issues/6943 I can see that the memory requirement for each column is about 2MB. Is this still the case for materialized views? We are planning to aggregate thousands of columns into a single MV

**Comment by den-crane** [comment]
Pretty same limitations. Materialized view stores data in usual table. That table is get inserts from MatView and has 0 knowledge about a  Materialized view . 
+ Materialized view SELECT section also needs memory. 
Probably if you have a table with 2000 columns , and this table use 4GB on insert it will be +8GB on matview = 12 GB total, if MatView also has 2000 columns.

**Comment by genzgd** [comment]
One other thing to keep in mind -- if your materialized view is for aggregates, some AggregateFunction columns, like uniq* and quantiles* columns, require quite a bit of memory (and disk space) to store that kind of state.

**Comment by rsaphala** [comment]
> Pretty same limitations. Materialized view stores data in a usual table. That table gets inserts from MatView and has 0 knowledge about a Materialized view . Plus Materialized view SELECT also needs memory. Probably if you have a table with 2000 columns , and this table uses 4GB on insert it will be +8GB on matview = 12 GB total, if MatView also has 2000 columns.

When inserting only a subset of the 2k columns (say 100 of 2000) to an MV, how much memory is required for inserts? 
https://github.com/ClickHouse/ClickHouse/issues/6943 mentions compact data parts. But I don't understand what it does exactly. Is there documentation available anywhere?

**Comment by tbragin** [comment]
> https://github.com/ClickHouse/ClickHouse/issues/6943 mentions compact data parts. But I don't understand what it does exactly. Is there documentation available anywhere?

For compact parts, all data is stored in one file in the system. https://clickhouse.com/docs/en/operations/system-tables/parts
