### ISSUE TITLE
Function to transform array into columns

### ISSUE THREAD

**Issue by sablastik** [ClickHouse/ClickHouse#31959]
**Use case**

To have function converting array into multiple columns depending of the longest array in source column

**Describe the solution you'd like**
For example function can be called like:` arrayToColumns(array[, number_of_columns])`

It should either by itself find the longest array in column and use its value as number_of_columns or this parameter should be set by user.

Expected behavior:

```
SELECT arrayToColumns(nums) FROM 
(SELECT [1, 2, 3] nums 
UNION ALL
SELECT [5,6] nums)
```

Result:
```
┌─nums_1─┬─nums_2─┬─nums_3─┐
│      1 │      2 │      3 │
│      5 │      6 │      0 │
└────────┴────────┴────────┘
```

**Comment by ethack** [comment]
I would add that this would make sense to do with a pair of arrays, where one has names and the other values. The column names in this case would ideally be taken from the names array instead of generated.

Another use case would be for turning maps into columns.

**Comment by den-crane** [comment]
```
SELECT arrayToColumns(nums) FROM 
(SELECT [1, 2, 3] nums 
UNION ALL
SELECT [5,6] nums)
```

Imagine there is a 10 billions rows in the query result, Clickhouse processes data in streamable manner, it returns the first rows before it starts to read the last rows, how to find out before hand how many elements in the array in the last row?

**Comment by sablastik** [comment]
> Imagine there is a 10 billions rows in the query result, Clickhouse processes data in streamable manner, it returns the first rows before it starts to read the last rows, how to find out before hand how many elements in the array in the last row?

I see the limitations, then parameter _number_of_columns_ should be made mandatory

**Comment by LukeHarrimanHQ** [comment]
+1 for this feature.

**Comment by Ninefiveblade** [comment]
+1

**Comment by alexey-milovidov** [comment]
Workaround:

```
SELECT array[1], array[2], array[3] FROM table
```

**Comment by alexey-milovidov** [comment]
This feature is unlikely to be implemented.
The reason: ClickHouse queries are statically typed - the structure of the result should be known at the query analysis stage.

**Comment by Sufiyan57** [comment]
This feature would be extremely useful for dynamic column selection and pivot-style transformations, even considering ClickHouse's static typing constraint. Allowing the user to explicitly set a `number_of_columns` parameter at query time would enable many real-world use cases and provide a form of semi-dynamic behavior. 

Hope this can be reconsidered in the future. 🤞
