### ISSUE TITLE
FileLog is able to read files only in /var/lib/clickhouse/user_files/ 

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#31962]
```
touch /tmp/aaa.csv

CREATE TABLE log (A String) ENGINE= FileLog('/tmp/aaa.csv', 'CSV');
DB::Exception: The absolute data path should be inside `user_files_path`(/var/lib/clickhouse/user_files/). (BAD_ARGUMENTS)


CREATE TABLE log (A String) ENGINE= FileLog('/tmp/aaa.csv', 'CSV');
DB::Exception: Metadata files already exist by path: /var/lib/clickhouse/.filelog_storage_metadata/default/log, remove them manually if it is intended. (TABLE_METADATA_ALREADY_EXISTS)
```

**Comment by kssenii** [comment]
> CREATE TABLE log (A String) ENGINE= FileLog('/tmp/aaa.csv', 'CSV');
DB::Exception: The absolute data path should be inside `user_files_path`(/var/lib/clickhouse/user_files/). (BAD_ARGUMENTS)

You can also put symlinks to your files by user_files path, isn't it ok?

> CREATE TABLE log (A String) ENGINE= FileLog('/tmp/aaa.csv', 'CSV');
DB::Exception: Metadata files already exist by path: /var/lib/clickhouse/.filelog_storage_metadata/default/log, remove them manually if it is intended. (TABLE_METADATA_ALREADY_EXISTS)

hm, this needs to be fixed..

**Comment by den-crane** [comment]
>You can also put symlinks to your files by user_files path, isn't it ok?

OK. Yes, I can. 
I did not expect that it's intentional. It's kinda ruins the beauty of this engine at least for me.

**Comment by alexey-milovidov** [comment]
It shouldn't be possible for the user to read arbitrary files on the server with SQL queries unless the paths of these files are preconfigured on the server side.

**Comment by ucasfl** [comment]
> > CREATE TABLE log (A String) ENGINE= FileLog('/tmp/aaa.csv', 'CSV');
> > DB::Exception: Metadata files already exist by path: /var/lib/clickhouse/.filelog_storage_metadata/default/log, remove them manually if it is intended. (TABLE_METADATA_ALREADY_EXISTS)
> 
> hm, this needs to be fixed..

I will fix it.
