### ISSUE TITLE
Official docker image for arm64 devices

### ISSUE THREAD

**Issue by makeavish** [ClickHouse/ClickHouse#31973]
**Use case**

Arm64 docker builds are not available for Clickhouse.

**Describe the solution you'd like**

Publish official arm64 builds on https://hub.docker.com/r/clickhouse/clickhouse-server/

**Describe alternatives you've considered**

Tried unofficial arm64 builds, but they aren't frequently updated and building docker image of clickhouse requires too much resources on machine which I don't have.

**Comment by R-omk** [comment]
Same issue as https://github.com/ClickHouse/ClickHouse/issues/22222,
