### ISSUE TITLE
Codes: 117, 60, 253. Error in time create table.

### ISSUE THREAD

**Issue by Saraf-SPb** [ClickHouse/ClickHouse#31983]
Hi. Noobs question, but i can don't replay this situation on test conture.
In time execution script i see it's notification and script execution crash with notification, ztestschema.test_table doesn't exists:
Stdoutput Code: 117, e.displayText() = DB::Exception: Data directory for table already containing data parts - probably it was unclean DROP table or manual intervention. You must either clear directory by hand or use ATTACH TABLE instead of CREATE TABLE if you need to use that parts., e.what() = DB::Exception
Stdoutput Code: 60, e.displayText() = DB::Exception: Table ztestschema.test_table doesn't exist., e.what() = DB::Exception
Stdoutput Code: 253, e.displayText() = DB::Exception: Replica /clickhouse/tables/shard03/ztestschema/test_table/replicas/127.0.0.1 already exists., e.what() = DB::Exception
I would be grateful for any help!

**Comment by melvynator** [comment]
Closing since there is no reply for more than a a month. Feel free to reopen if needed.
