### ISSUE TITLE
libcxx 13 compatibility

### ISSUE THREAD

**Issue by Algunenano** [ClickHouse/ClickHouse#32018]
Currently it's impossible to build ClickHouse with libcxx 13, which happens to be the standard library bundled with the recommended compiler. It's understood that you should use the provided one, but at some point that will be updated too so since I had some issues I decided to give it a try and see what break.

Tested with local libc++ (from llvm 13.0.0):

```
CC=clang CXX=clang++ cmake .. -DUSE_INTERNAL_LIBCXX_LIBRARY=False -DDISABLE_HERMETIC_BUILD=ON
```

The problems come from internal dependencies that are using result_of. This was deprecated in C++17, removed in C++20 and dropped from libc++ in v13.

* Abseil
  - Issue: https://github.com/abseil/abseil-cpp/issues/649
  - Fixed in https://github.com/abseil/abseil-cpp/commit/e19260fd7dbef881492fd73891e0be5bd4a09b95
  - Available in 20211102.0
  - ClickHouse-Extras/abseil-cpp uses lts_20202_02_25 with a patch and some backports. Both are unnecessary if switched to the upstram/lts_2021_03_24 branch. Switching the submodule to point to the official repo would be an option.

* Arrow
  - Issue https://github.com/apache/arrow/pull/10814
  - Fixed in https://github.com/apache/arrow/commit/4c02c6d7ffae6f8580aa9e7f42336cfa561d357e
  - Available in 6.0.0dev+
  - Updating to upstream apache-arrow-6.0.1 works. Patches from ClickHouse-Extras: remove submodules and add Uri::host_and_port() which doesn't seem to be used anymore.
  - Needs adapting the cmake file and some changes in the callers. I've done some changes but it seems to be missing some objects (complains about ipc).

* Boost ASIO
  - The library uses it's internal way of detecting what invoke method to use (asio/detail/config.hpp).
  - Fixed in https://github.com/boostorg/asio/commit/58050a2036ad8e2d67b9ecfc9caa4eddec92fdac
  - Available in boost-1.78.0.beta1 (no stable version released yet)
  - Applying the patch (https://github.com/boostorg/asio/commit/58050a2036ad8e2d67b9ecfc9caa4eddec92fdac.patch) over the current ClickHouse-Extras fork fixes it.

* Boost Fiber/Context/Config
  - Uses Context with result_of because BOOST_NO_CXX17_STD_INVOKE is defined.
  - BOOST_NO_CXX17_STD_INVOKE is defined in boost/config/stdlib/libcpp.hpp
  - Fixed also some time ago (multiple changes)
  - Replacing boost/config with current master one (all the files, not just libcpp.hpp) fixes the issue.

* Boost format
  - Different issue. This time with allocators
  - Issue: https://github.com/boostorg/format/issues/67
  - Fixed in https://github.com/boostorg/format/commit/5884c3d8140cdcd2d1bef374fcc216244d5faaa5 -> Boost 1.74.0+
  - Applying the patch (https://github.com/boostorg/format/commit/5884c3d8140cdcd2d1bef374fcc216244d5faaa5.patch) works.

* S2
  - Uses it's own internal absl which has the same issue.
  - Fixed pretty recently (https://github.com/google/s2geometry/pull/169) by requiring an external abseil
  - Should be updated and use the contrib/absl for building
  - Haven't tested that it works, i've disabled it with `ENABLE_S2_GEOMETRY=OFF` for now.

IMO the actions points would be:
* Push `lts_2021_03_24` branch to ClickHouse-Extras/abseil-cpp or change remote to upstream.
* Push `apache-arrow-6.0.1` branch to ClickHouse-Extras/arrow. Add a commit to remote submodules (if we want it).
* Get arrow to link and work with 6.0.1. Should require only changes here.
* Update ClickHouse-Extras/s2 to a version with off tree abseil.
* Get S2 to build with contrib/abseil.
* Either update boost to a newer version (like 1.76 + ASIO patch) or apply all 3 patches individually.

I'll try to get this done locally as long as nobody says it shouldn't be done or something but, when it all works, I'll need help pushing new branches / patches into the submodules.

**Comment by alexey-milovidov** [comment]
Yes, it should be done. We can merge PRs into submodules for every library.

**Comment by Algunenano** [comment]
Another issue found while building with an out of tree libc++.

ClickHouse defines _LIBCPP_ABI_UNSTABLE which defines _LIBCPP_ABI_ALTERNATE_STRING_LAYOUT which changes string layout to be (data, size, cap) vs the default (cap, size, data). This change is later relied upon to reinterpret the storage into char *. As far as I can see, this is an issue only in `ColumnUnique<ColumnType>::uniqueInsert`.


With CH internal libc++ and unstable API:
```
(gdb) p *(current_row.__begin_ + 1)
$3 = {storage = {__lx = "ABC", '\000' <repeats 20 times>, "\003", '\000' <repeats 23 times>}, 
  which = DB::Field::Types::String}
```

Without unstable API:

```
(gdb) p *(current_row.__begin_ + 1)
$16 = {storage = {__lx = "\006ABC", '\000' <repeats 43 times>}, which = DB::Field::Types::String}
```

Related issues: https://github.com/ClickHouse/ClickHouse/issues/10489 and https://github.com/ClickHouse/ClickHouse/issues/7754

I'm guessing either reinterpretet should take into account this based on the type or `ColumnUnique<ColumnType>::uniqueInsert` shouldn't use it.

**Comment by Algunenano** [comment]
^ Addressed in https://github.com/Algunenano/ClickHouse/commit/82c5c77d124235add793ed034ebfd9c83361e527. I'm not sure if it deserves a different PR just for that change.

**Comment by Algunenano** [comment]
After adapting the new CMakefiles everything seems to be working fine locally.

Starting with the PRs:
- Update s2 to master (keeping 8d6be45f2955ddf0ba5f07cf0d92ad90cf957e37 patch): https://github.com/ClickHouse-Extras/s2geometry/pull/2
- Update absl to 20211102.0+: I'm switching the remote to upstream to use the `lts_2021_11_02` branch. It could be pushed to the ClickHouse-Extrast too (I can't create a PR to a branch that doesn't exist).
- Arrow: I need somebody to push upstream `release-6.0.1` branch to ClickHouse-Extras to be able to push patches there. Using upstream `release-6.0.1` directly works too (but has unnecessary submodules).
- Boost: Applied all 3 changes in https://github.com/ClickHouse-Extras/boost/pull/27

With those submodules + https://github.com/Algunenano/ClickHouse/tree/libcxx13_take2 I've been able to build ClickHouse with libstdc++ 13 and pass stateless tests (with the same failures I already have in master).

**Comment by Algunenano** [comment]
I'm going to switch Arrow to point to upstream too for the moment. There are other submodules with recursive submodules too so they all could be clean up at some point in the future.

Based on this, all I need is for the 2 PRs to be merged so the changes can be tested.

**Comment by alexey-milovidov** [comment]
Ok.

**Comment by alexey-milovidov** [comment]
If recursive submodules were needed, you can flatten them,
just to avoid recursive submodules in our repo.

**Comment by Algunenano** [comment]
They are not needed, but I can't do a PR to create a new branch. Could you push release-6.0.1 from arrow upstream to ClickHouse-Extras please? I can create then a PR to remove the submodules (or just push it yourself to the branch)

**Comment by Algunenano** [comment]
It seems the boost update brought extra PRs and it's breaking the build. Partially my bad because I worked with that was in the submodule commit, not  the HEAD of the branch. I'm looking into it and will create a PR once I know what changes are required.
