### ISSUE TITLE
What would cause "Aborted (core dumped)" error when using clickhouse-client to ingest parquet data?

### ISSUE THREAD

**Issue by fsgdgsdfgsgd** [ClickHouse/ClickHouse#32028]
Hi All,
As described in the topic, I encountered "Aborted (core dumped)" error when using clickhouse-client to ingest parquet data. I thought it may be because the clickhouse-client uses too much memory. I tried to reduce the row group size when outputting the parquet file and cut the parquet file into smaller pieces. But this didn't make much difference.

Does anyone encountered this error?

**Comment by fsgdgsdfgsgd** [comment]
Version: ClickHouse client version 21.6.5.37 (official build).

**Comment by alexey-milovidov** [comment]
You can download the new `clickhouse-client` version as following:
```
curl https://clickhouse.com/ | sh
```
and check if it will help.

**Comment by fsgdgsdfgsgd** [comment]
That works for me! Thanks a lot! :)
