### ISSUE TITLE
Make HDFS replication configurable in WriteBufferFromHDFSImpl#WriteBufferFromHDFSImpl 

### ISSUE THREAD

**Issue by leosunli** [ClickHouse/ClickHouse#32039]
(you don't have to strictly follow this form)

**Describe the unexpected behaviour**
Current HDFS replication is zero in WriteBufferFromHDFSImpl#WriteBufferFromHDFSImpl and  when HDFS replication is zero in libhdfs3 client，it will set HDFS replication default num. 
Many of our users need adjust the replication num according to their own needs, so we recommend making HDFS replication configurable in WriteBufferFromHDFSImpl#WriteBufferFromHDFSImpl 
![image](https://user-images.githubusercontent.com/3837921/144203520-401f75b5-9608-4fca-9dc5-11d24ed90708.png)

**Comment by leosunli** [comment]
hi @kssenii  
I have worked on it and later issue PR. Could you help assign this issue to me and review it ?

**Comment by kssenii** [comment]
Yes, of course!

**Comment by leosunli** [comment]
hi @kssenii  I have issued PR (https://github.com/ClickHouse/ClickHouse/pull/32049/files)
Could you help review it ? Thank you.
