### ISSUE TITLE
DatabaseCatalog drop table again

### ISSUE THREAD

**Issue by superceix** [ClickHouse/ClickHouse#32032]
clickhouse version: 21.11.3.6
os: CentOS Linux release 7.9

i hava two shard in cluster,  if i create a table with same name after dropped one.  node in zookeeper will be removed by DatabaseCatalog
stap:
1. create table: 
```
CREATE TABLE `test`.`t5_all_local` ON CLUSTER cluster_1 (`id` Int64, `createtime` Date)  ENGINE = ReplicatedMergeTree('/clickhouse/cluster1/{layer}-{shard}/t5_all_local', '{replica}', createtime, id, 8192);
```
2. drop table: 
```
drop table `test`.`t5_all_local` ON CLUSTER cluster_1; 
```
    > i found message in the log file: "DatabaseCatalog: Not found any suitable tables to drop, still have 1 tables in drop queue (0 of them are in use). Will check again after 480 seconds"

    > there is a sql file in metadata_dropped dir: test.t5_all_local.68af1a27-ed20-4c93-a8af-1a27ed208c93.sql

    > node in zookeeper "/clickhouse/cluster1/05-01/" is empty

3. create table  `test`.`t5_all_local` again
4. wait a few minutes， insert will report err:
```
 :) insert into t5_all values (1, '2021-12-03');

INSERT INTO t5_all FORMAT Values

Query id: 404b5c8c-84df-4217-b773-8998cc71b4c3


1 rows in set. Elapsed: 0.009 sec.

Received exception from server (version 21.11.3):
Code: 999. DB::Exception: Received from localhost:9001. DB::Exception: Cannot allocate block number in ZooKeeper: Coordination::Exception: Transaction failed (No node): Op #0, path: /clickhouse/cluster1/05-20/t5_all_local/blocks/202112_3279515714319506403_14247152170660308628. (KEEPER_EXCEPTION)
```
5. table is exists and select sql can be executed,
6. zookeeper node was removed:
```
[zk: 127.0.0.1:2181(CONNECTED) 1] ls /clickhouse/cluster1/05-20
[]
```
7.  i found this in the log file: 
```
2021.12.01 14:34:24.591807 [ 3607952 ] {} <Information> DatabaseCatalog: Have 1 tables in drop queue (0 of them are in use), will try drop test.t5_all_local (68af1a27-ed20-4c93-a8af-1a27ed208c93)
2021.12.01 14:34:24.591912 [ 3607952 ] {} <Trace> test.t5_all_local (ReplicatedMergeTreeRestartingThread): Restarting thread finished
2021.12.01 14:34:24.591941 [ 3607952 ] {} <Trace> test.t5_all_local (ReplicatedMergeTreeRestartingThread): Waiting for threads to finish
2021.12.01 14:34:24.591968 [ 3607952 ] {} <Trace> test.t5_all_local (ReplicatedMergeTreeRestartingThread): Threads finished
2021.12.01 14:34:24.591985 [ 3607952 ] {} <Trace> test.t5_all_local (PartMovesBetweenShardsOrchestrator): PartMovesBetweenShardsOrchestrator thread finished
2021.12.01 14:34:24.592004 [ 3607952 ] {} <Information> test.t5_all_local (68af1a27-ed20-4c93-a8af-1a27ed208c93): Removing replica /clickhouse/cluster1/05-20/t5_all_local/replicas/cluster02-02-1, marking it as lost
2021.12.01 14:34:24.603020 [ 3607952 ] {} <Information> test.t5_all_local (68af1a27-ed20-4c93-a8af-1a27ed208c93): /clickhouse/cluster1/05-20/t5_all_local/replicas/cluster02-02-1 is the last replica, will remove table
2021.12.01 14:34:24.604232 [ 3607952 ] {} <Information> test.t5_all_local (68af1a27-ed20-4c93-a8af-1a27ed208c93): Removing table /clickhouse/cluster1/05-20/t5_all_local (this might take several minutes)
```

**Comment by tavplubix** [comment]
> 3. create table test.t5_all_local again

It will fail with the exception like:
```
Code: 253. DB::Exception: Received from localhost:9000. DB::Exception: There was an error on [localhost:9000]: Code: 253. DB::Exception: Replica /clickhouse/cluster1/s1/t5_all_local/replicas/r1 already exists. (REPLICA_IS_ALREADY_EXIST) (version 21.12.1.1). (REPLICA_IS_ALREADY_EXIST)
```

How did you create the table before metadata of previous table was removed from ZooKeeper?

**Comment by superceix** [comment]
> 



> > 3. create table test.t5_all_local again
> 
> It will fail with the exception like:
> 
> ```
> Code: 253. DB::Exception: Received from localhost:9000. DB::Exception: There was an error on [localhost:9000]: Code: 253. DB::Exception: Replica /clickhouse/cluster1/s1/t5_all_local/replicas/r1 already exists. (REPLICA_IS_ALREADY_EXIST) (version 21.12.1.1). (REPLICA_IS_ALREADY_EXIST)
> ```
> 
> How did you create the table before metadata of previous table was removed from ZooKeeper?

i


> > 3. create table test.t5_all_local again
> 
> It will fail with the exception like:
> 
> ```
> Code: 253. DB::Exception: Received from localhost:9000. DB::Exception: There was an error on [localhost:9000]: Code: 253. DB::Exception: Replica /clickhouse/cluster1/s1/t5_all_local/replicas/r1 already exists. (REPLICA_IS_ALREADY_EXIST) (version 21.12.1.1). (REPLICA_IS_ALREADY_EXIST)
> ```
> 
> How did you create the table before metadata of previous table was removed from ZooKeeper?

my fault, I thought that Exception REPLICA_IS_ALREADY_EXIST  is anther bug , so i delete path in zk myself. now i understand this feature....

But i don't understand why not you delete the metadata in ZooKeeper direct

**Comment by tavplubix** [comment]
See #12135
