### ISSUE TITLE
More documentation for ProfileEvents

### ISSUE THREAD

**Issue by orloffv** [ClickHouse/ClickHouse#32047]
Many fields without description https://github.com/ClickHouse/ClickHouse/blob/96ec92c7cd127b08453a83d2aca23f2ec26c67df/src/Common/ProfileEvents.cpp
For example: 
MarkCacheHits, MarkCacheMisses,  UncompressedCacheHits, UncompressedCacheMisses

**Comment by alexey-milovidov** [comment]
I have added documentation for all the fields.
Moreover, I have added a check to ensure that the documentation always exists.

And here is our **lovely** documentation:
https://pastila.nl/?00284129/c256cc8d35944ee424dbdb6267f971b1.md

Which is now guaranteed to be:
- complete;
- precise;
- up to date;
- available in your clickhouse-server;
- consistent with your ClickHouse version.
