### ISSUE TITLE
Getting error while running Clickhouse image 

### ISSUE THREAD

**Issue by rishabh-shah12** [ClickHouse/ClickHouse#32054]
```
ENV CH_VERSION 21.8.11.4
ENV DEBIAN_FRONTEND=noninteractive
RUN \
  apt-get update && \
  apt-get install --yes --no-install-recommends \
    apt-transport-https \
    apt-utils \
    dirmngr \
    gnupg && \
  apt-key adv --keyserver keyserver.ubuntu.com --recv E0C56BD4 && \
  echo "deb http://repo.yandex.ru/clickhouse/deb/stable/ main/" | tee /etc/apt/sources.list.d/clickhouse.list && \
  apt-get update && \
  apt-get install --allow-unauthenticated -y \
    clickhouse-client=${CH_VERSION} \
    clickhouse-server=${CH_VERSION} \
    clickhouse-common-static=${CH_VERSION} \
    libgcc-7-dev \
    tzdata \
    libreadline-dev \
    curl && \
  rm -rf \
    /var/lib/apt/lists/* \
    /var/cache/debconf \
    /tmp/* && \
  apt-get clean

VOLUME /var/lib/clickhouse

RUN chown -R clickhouse /etc/clickhouse-server

USER clickhouse
EXPOSE 9000 8123 9009

ENTRYPOINT exec /usr/bin/clickhouse-server --config=/etc/clickhouse-server/config.xml
```
 Build clickhouse image by running following cmd

`docker build -t clickhouse-server:21.8.11.4 .`

Running image 
`docker run clickhouse-server:21.8.11.4 .`

Error 
`error /bin/sh: 1: exec: /usr/bin/clickhouse-server: Operation not permitted`
`<Error> Application: DB::ErrnoException: Cannot open file /var/lib/clickhouse/status, errno: 13, strerror: Permission denied`

**Comment by alexey-milovidov** [comment]
Do not try to build your own Docker image.

Your Dockerfile has multiple errors:

> libgcc-7-dev

Unneeded.

> tzdata

Unneeded.

> libreadline-dev

Unneeded.

> curl

Unneeded.

---

Keep in mind: ClickHouse does not require any libraries from OS distribution.
If you install some libraries or using the OS package manager - you've making a mistake.

---

Version 21.8.11.4 is old.
Install the latest version 21.12.

Only use the official Docker image.
Never try to build your own Docker image.
