### ISSUE TITLE
Attach part increases records in the table

### ISSUE THREAD

**Issue by rajadayalan** [ClickHouse/ClickHouse#3206]
We are noticing issue when trying to attach part from backup. Recently we had to recover clickhouse using data from backup and noticed count() increased when using attach part. 

We investigated with 2 test tables using MergeTree Engine. Backup for the table has 634 parts.
In one table access_logs_local  we copied the parts  to the table's data folder directly and restarted clickhouse node. Table Count() using this procedure is 2333691415

In another table access_logs_local _attach we copied 634 parts to the table's detached folder and a script that attaches the files from detached folder using alter part. Table Count() using this procedure is 2349986051. Number of records increased when we attached part.

Did not notice any error in clickhouse logs. And confirmed from logs that all 634 parts got attached. Can you please provide some inputs on why the count() is different, is there anything specific we can do  avoid the inconsistency when attaching part?

Clickhouse server version used - 18.5.54400

Count using clickhouse-client
srv002 :) select count() from access_logs_local

SELECT count()
FROM access_logs_local

┌────count()─┐
│ 2333691415 │
└────────────┘

1 rows in set. Elapsed: 0.129 sec. Processed 2.33 billion rows, 4.67 GB (18.15 billion rows/s., 36.29 GB/s.)

srv002 :) select count() from access_logs_local_attach

SELECT count()
FROM access_logs_local_attach

┌────count()─┐
│ 2349986051 │
└────────────┘

1 rows in set. Elapsed: 0.112 sec. Processed 2.35 billion rows, 4.70 GB (20.90 billion rows/s., 41.80 GB/s.)

**Comment by alexey-milovidov** [comment]
To restore from the backup, you should use `ALTER ... ATTACH PARTITION` query. It will select active parts and attach them.

If you attach parts one by one by issuing `ALTER ... ATTACH PART` query, you will select both active and inactive parts with duplicate data. Inactive parts are the parts that are kept for some time after merging.

If you want to fix the issue and remove duplicates, you can run `OPTIMIZE TABLE ... PARTITION ... FINAL DEDUPLICATE` query.

**Comment by rajadayalan** [comment]
Thanks Alexey. Will run the OPTIMIZE TABLE ... PARTITION ... FINAL DEDUPLICATE command for the table.

We also have tables that are SummingMergeTree, does the DEDUPLICATE work for those tables also? or will it impact the columns that are summed?

**Comment by rajadayalan** [comment]
Created another table access_logs_local_attach_new and used attach partition, count looks same as  using attach part
SELECT count()
FROM test.access_logs_local_attach_new
┌────count()─┐
│ 2349986051 │
└────────────┘

Also noticed that using attach partitions does not attach all parts. When our script ran first time it attached only 50% of the parts. we tried running it manually for one partition and only few parts were getting attached everytime we ran the command. Have provided below the behaviour when we tried attaching.

[Tue Sep 25 19:22:33] root@srv002:~# ls /srv/clickhouse/data/test/access_logs_local_attach_new/detached/ | wc -l
316
[Tue Sep 25 20:30:53] root@srv002:~# ls /srv/clickhouse/data/test/access_logs_local_attach_new/detached/ | wc -l
316
[Tue Sep 25 20:50:45] root@srv002:~# ls /srv/clickhouse/data/test/access_logs_local_attach_new/detached/ | wc -l
316
[Tue Sep 25 20:52:43] root@srv002:~# clickhouse-client --port 9456 --database=default --multiquery --query="alter table test.access_logs_local_attach_new attach partition '2018-09-10-20-00000'"
[Tue Sep 25 20:53:08] root@srv002:~# ls /srv/clickhouse/data/test/access_logs_local_attach_new/detached/ | wc -l
307
[Tue Sep 25 20:59:40] root@srv002:~# ls /srv/clickhouse/data/test/access_logs_local_attach_new/detached/ | wc -l
307
[Tue Sep 25 21:07:15] root@srv002:~# clickhouse-client --port 9456 --database=default --multiquery --query="alter table test.access_logs_local_attach_new attach partition '2018-09-10-20-00000'"
[Tue Sep 25 21:07:21] root@srv002:~# ls /srv/clickhouse/data/test/access_logs_local_attach_new/detached/ | wc -l
278

**Comment by alexey-milovidov** [comment]
> We also have tables that are SummingMergeTree, does the DEDUPLICATE work for those tables also?

Yes.

> or will it impact the columns that are summed?

DEDUPLICATE does not sum the data.
The problem is that background merges could have already summed up your duplicate data before you applied the deduplication.
