### ISSUE TITLE
ClickHouse is unable to connect to MySQL 5.1

### ISSUE THREAD

**Issue by mbasunov** [ClickHouse/ClickHouse#32065]
ClickHouse server is unable to connect to MySQL 5.1 (from CentOS 6 installation) by using mysql() syntax:

How to reproduce:
Install/use CentOS 6 and MySQL server provided by CentOS 6:
```
# rpm -q mysql mysql-server
mysql-5.1.73-8.el6_8.x86_64
mysql-server-5.1.73-8.el6_8.x86_64
```
Ensure connections to TCP port 3306 are allowed and mysqld is running.
Prepare test scenario:
```
grant all on test.* to test@localhost identified by "test";
create table test.test (nn int);
insert into test.test values (42);
```
Check MySQL configured properly:
`mysql -h127.0.0.1 -utest -ptest -e'select * from test' test`
result:
```
+------+
| nn   |
+------+
|   42 |
+------+
```

Install ClickHouse from official repo:
```
rpm -q clickhouse-client clickhouse-server
clickhouse-client-21.8.11.4-2.noarch
clickhouse-server-21.8.11.4-2.noarch
```
Ensure ClickHouse running

Test:
Execute `clickhouse-client`
Execute  ClickHouse SQL:
`select * from mysql('127.0.0.1:3306', 'test'database_version', 'test', 'test');`

Expected result:
```
┌─nn──────┐
│      42 │
└─────────┘

1 rows in set. Elapsed: 0.010 sec.
```

Actual result:
`DB::Exception: Exception: Connections to all replicas failed: test@127.0.0.1:3306 as user test.`

This scenario works as expected for MySQL 5.5 from CentOS 7 and for MariaDB from Ubuntu LTS 20.04

**Comment by tavplubix** [comment]
AFAIK, MySQL 5.1 has reached its End Of Live 8 years ago.
