### ISSUE TITLE
Creating a table without a primary key will cause MaterializedMySQL to fail. Can you skip the table without a primary key and continue to synchronize?

### ISSUE THREAD

**Issue by chinayangze** [ClickHouse/ClickHouse#32109]
Creating a table without a primary key will cause MaterializedMySQL to fail. Can you skip the table without a primary key and continue to synchronize?

**Comment by alexey-milovidov** [comment]
I'm closing all old issues about MaterializedMySQL because the ClickHouse team does not support it.
