### ISSUE TITLE
did rand64() evenly distributed among all UInt64-type numbers ?

### ISSUE THREAD

**Issue by jessezax** [ClickHouse/ClickHouse#32111]
i use
`ENGINE = Distributed('monitoring03', 'aladdin_monitor', 'bid_stats', rand64(timestamp))`
and topology is
```
chi-clickhouse-shard-monitoring03-0-0-0   1/1     Running   0          15h
chi-clickhouse-shard-monitoring03-0-1-0   1/1     Running   0          18m
chi-clickhouse-shard-monitoring03-1-0-0   1/1     Running   0          47m
chi-clickhouse-shard-monitoring03-1-1-0   1/1     Running   0          14h
chi-clickhouse-shard-monitoring03-2-0-0   1/1     Running   0          15h
chi-clickhouse-shard-monitoring03-2-1-0   1/1     Running   0          15h
chi-clickhouse-shard-monitoring03-3-0-0   1/1     Running   0          14h
chi-clickhouse-shard-monitoring03-3-1-0   1/1     Running   0          6h47m
chi-clickhouse-shard-monitoring03-4-0-0   1/1     Running   0          14h
chi-clickhouse-shard-monitoring03-4-1-0   1/1     Running   0          6h47m
```
shards is 5.
but chi-clickhouse-shard-monitoring03-0-0-0 has 100G. others has 75G.
did shards number influence？

**Comment by den-crane** [comment]
1. rand64(timestamp) has no sense. Just use `rand()`
2. What is `1/1`?
3. What is `15h`?
4. chi ? open a ticket in https://github.com/Altinity/clickhouse-operator

**Comment by jessezax** [comment]
> 1. rand64(timestamp) has no sense. Just use `rand()`
> 2. What is `1/1`?
> 3. What is `15h`?
> 4. chi ? open a ticket in https://github.com/Altinity/clickhouse-operator
> 5. ClickHouse version?

1. i used `rand()`。bus same as `rand64(timestamp)`
2. pod 
3. live time
4. i use clickhouse-operator
5. ClickHouse server version 21.4.5 revision 54447

**Comment by alexey-milovidov** [comment]
Yes, rand64() is evenly distributed.
A test:

```
milovidov-desktop :) SELECT rand64() % 5 AS k, count() AS c, bar(c, 0, 1000000000, 100) FROM numbers_mt(1000000000) GROUP BY k ORDER BY k

SELECT
    rand64() % 5 AS k,
    count() AS c,
    bar(c, 0, 1000000000, 100)
FROM numbers_mt(1000000000)
GROUP BY k
ORDER BY k ASC

Query id: cdfb2f6d-b0b0-4b71-abe6-dda73db39e68

┌─k─┬─────────c─┬─bar(count(), 0, 1000000000, 100)─┐
│ 0 │ 199992940 │ ███████████████████▊             │
│ 1 │ 200000625 │ ████████████████████             │
│ 2 │ 199981526 │ ███████████████████▊             │
│ 3 │ 200003355 │ ████████████████████             │
│ 4 │ 200021554 │ ████████████████████             │
└───┴───────────┴──────────────────────────────────┘

5 rows in set. Elapsed: 0.172 sec. Processed 614.83 million rows, 4.92 GB (3.58 billion rows/s., 28.61 GB/s.)
```

**Comment by jessezax** [comment]
> Yes, rand64() is uniformly distributed. A test:
> 
> ```
> milovidov-desktop :) SELECT rand64() % 5 AS k, count() AS c, bar(c, 0, 1000000000, 100) FROM numbers_mt(1000000000) GROUP BY k ORDER BY k
> 
> SELECT
>     rand64() % 5 AS k,
>     count() AS c,
>     bar(c, 0, 1000000000, 100)
> FROM numbers_mt(1000000000)
> GROUP BY k
> ORDER BY k ASC
> 
> Query id: cdfb2f6d-b0b0-4b71-abe6-dda73db39e68
> 
> ┌─k─┬─────────c─┬─bar(count(), 0, 1000000000, 100)─┐
> │ 0 │ 199992940 │ ███████████████████▊             │
> │ 1 │ 200000625 │ ████████████████████             │
> │ 2 │ 199981526 │ ███████████████████▊             │
> │ 3 │ 200003355 │ ████████████████████             │
> │ 4 │ 200021554 │ ████████████████████             │
> └───┴───────────┴──────────────────────────────────┘
> 
> 5 rows in set. Elapsed: 0.172 sec. Processed 614.83 million rows, 4.92 GB (3.58 billion rows/s., 28.61 GB/s.)
> ```

but use  ENGINE = Kafka pull data, rand64() is not uniformly distributed. confused

**Comment by alexey-milovidov** [comment]
Does Kafka table write to Distributed table?

Otherwise if it is writing independently on every shard, it may distributed in any arbitrary way.

**Comment by jessezax** [comment]
> Does Kafka table write to Distributed table?
> 
> Otherwise if it is writing independently on every shard, it may distributed in any arbitrary way.

yes ,i use CREATE TABLE *** ON CLUSTER

**Comment by alexey-milovidov** [comment]
Then it is related to non-uniform pulling data from Kafka on servers.
