### ISSUE TITLE
 Unknown setting materialized_postgresql_schema_list: for storage MaterializedPostgreSQL. (UNKNOWN_SETTING)

### ISSUE THREAD

**Issue by josangmi** [ClickHouse/ClickHouse#32169]
Hello,
   
    I can get the table engine, but I can't get the database engine to work.
   
    Code: 115. DB::Exception: Received from localhost:9000. DB::Exception: Unknown setting 
    materialized_postgresql_schema_list: for storage MaterializedPostgreSQL. (UNKNOWN_SETTING)
  
    CREATE DATABASE postgres_database_schema
    ENGINE = MaterializedPostgreSQL('192.168.1.xx:5432', 'aa', 'postgres', 'mengde')
    SETTINGS materialized_postgresql_schema_list = 'aa,bb';

ClickHouse&Client version: 21.11.4

I've also made sure that wal_level is set to logical and that max_replication_slots is > 2 in Postgres.

**Comment by kssenii** [comment]
Hi! This feature is only in master now, not in any release yet. Will be in the next release.

**Comment by kssenii** [comment]
Mentioned this in documentation https://github.com/ClickHouse/ClickHouse/pull/32172/files#diff-e1d6f9c2bbbf1cac22d29e31dc9f4c3c403872d7b6948c502a6ecdfdaeb8e956R73
as this case it reported for the second day in a row..
