### ISSUE TITLE
toTimeZone function isn't working

### ISSUE THREAD

**Issue by michaelfyc** [ClickHouse/ClickHouse#32168]
I tried the SQL answered in the issue [#31308](https://github.com/ClickHouse/ClickHouse/issues/31308).
Here is my SQL: `select now() x, toTypeName(x), toTimeZone(x, 'Asia/Shanghai') y, toTimeZone(x,'Europe/Berlin') z`
And this is what I got after execution:
![image](https://user-images.githubusercontent.com/45136049/144538959-325948a0-b0a8-4841-a6e4-459281fca121.png)
Datetime in different timezone has the same value!
Is there anything I did wrong? My Clickhouse version is 21.11.4.14

**Comment by den-crane** [comment]
```
SELECT
    now() AS x,
    toTypeName(x),
    toTimeZone(x, 'Asia/Shanghai') AS y,
    toTimeZone(x, 'Europe/Berlin') AS z

Query id: fd724ec5-0594-40da-83cb-8b8a83fc8ed1

Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 21.9.1 revision 54449.

┌───────────────────x─┬─toTypeName(now())─┬───────────────────y─┬───────────────────z─┐
│ 2021-12-03 04:07:56 │ DateTime          │ 2021-12-03 12:07:56 │ 2021-12-03 05:07:56 │
└─────────────────────┴───────────────────┴─────────────────────┴─────────────────────┘
```

It works as expected. Java converts datetime into timezone of your desktop.
