### ISSUE TITLE
CH keeper Qs

### ISSUE THREAD

**Issue by ilejn** [ClickHouse/ClickHouse#32188]
Excellent CH keeper presentation https://www.youtube.com/watch?v=abhcCRW09Ac raises certain questions.

- how to decrease or increase number of CH keeper nodes?
  Is it a valid scenario to add an extra instance (if CH keeper is run by ClickHouse, not explicitly)
    - modify raft_configuration in all configs, add new keeper_server/server_id to a new keeper instance, propagate config
    - issue SYSTEM RELOAD CONFIG
- is it correct, that mentioned elastic CH keeper configuration is about making the service less visible from configuration standpoint? Could we expect zero configuration?
- is it true that it is possible to configure a ClickHouse instance to interact with more than one whatever-keeper cluster? How?
- does absence of can_become_leader and priority in https://github.com/ClickHouse/ClickHouse/blob/master/docs/en/operations/clickhouse-keeper.md mean that we should not use these parameters

**Comment by alesapin** [comment]
1. Yes, it's correct, but it was implemented quite recently https://github.com/ClickHouse/ClickHouse/pull/30372.
2. Probably no, you will still have some raft settings, but will be able just to specify all nodes as possible quorum candidates.
3. Yes, check for `<auxiliary_zookeeper` https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/replication/.
4. No, just forget to add it :(

**Comment by ilejn** [comment]
@alesapin , many thanks for your answers.

It was mentioned that if I want to add N boxes in CH keeper cluster, I should add 1 box N times. Is my understanding correct?

**Comment by alesapin** [comment]
> 

Yes.
