### ISSUE TITLE
clickhouse.com down?

### ISSUE THREAD

**Issue by redgloboli** [ClickHouse/ClickHouse#32221]
Hi,

i'd like to read the documentation a bit more as i have trouble using my let's encrypt privkey.pem, but unfortunately i cannot connect to clickhouse.com

**Comment by alexey-milovidov** [comment]
Most likely it is related to your adblocker.

We've bought clickhouse.com domain and it has a history of being used for some old ad network or something like this.
We already addresses this issue and most of adblockers are updated and don't block this domain anymore.
But you can still have some outdated adblocker.

**Comment by redgloboli** [comment]
i see :)

https://github.com/StevenBlack/hosts/issues/1781

**Comment by redgloboli** [comment]
i contacted every list owner for a removal, it is in 4 different lists included in pihole.
