### ISSUE TITLE
inner join  where Invalid

### ISSUE THREAD

**Issue by wbl381** [ClickHouse/ClickHouse#32225]
version : 21.5.6.6

`CREATE TABLE data_event_goods_payed
(

    `mid` String COMMENT 'mid',

    `uid` String COMMENT 'uid',

    `pay_time` DateTime COMMENT '支付时间',

    `order_id` String COMMENT '订单id',

    `sku_id` String COMMENT 'skuid',

    `spu_id` String COMMENT 'spuid',

    `name` String COMMENT '商品名称',

    `code` String COMMENT '商品编号',

    `sku_code` String COMMENT 'sku编号',

    `uk_code` String COMMENT 'UK 唯一编码',

    `cate_id` String COMMENT '分类id',

    `price` Decimal(18,2)  COMMENT '商品价格',

    `vip_price` Decimal(18,2)  COMMENT 'vip价格',

    `standard_price` Decimal(18,2)  COMMENT '标准价',

    `deal_price` Decimal(18,2)  COMMENT '配销价',

    `single_sku` UInt8 COMMENT '是否单规格',

    `sale_type` String COMMENT '销售类型 预售pre，及时达 timely',

    `take_time` String COMMENT '提货时间',

    `load_type` String COMMENT '库存类型 online 线上，store 门店',

    `attr_val` String COMMENT '规格',

    `send_amount` Decimal(18,2) COMMENT '配送金额',

    `sale_amount` Decimal(18,2) COMMENT '销售金额',

    `pay_amount` Decimal(18,2) COMMENT '支付金额',

    `qty` Decimal(18,2) COMMENT '数量',

    `bonus_rmb` Decimal(18,2) COMMENT '佣金',

    `bonus_ratio` Decimal(18,2) COMMENT '佣金比例',

    `main_img` String COMMENT '商品主图',

    `gmt_create` DateTime,

    `date_create` Date,

    `store_id` String COMMENT '店铺标识',

    `voucher_amount` Decimal(18,2) COMMENT '代金券优惠金额',

    `activity_amount` Decimal(18,2) COMMENT '优惠活动金额',

    `coupon_amount` Decimal(18,2) COMMENT '优惠活动金额'
)ENGINE = MergeTree(date_create,gmt_create, 8192)
`

`CREATE TABLE data_event_order_payed_success
(

    `mid` String,

    `uid` String,

    `rel_bill_number` String COMMENT '来源单号',

    `pay_type` String COMMENT '支付方式 微信支付Wx，会员卡支付member',

    `total_amount` Decimal(18,2) COMMENT '总金额(分)',

    `pay_amount` Decimal(18,2) COMMENT '支付金额(分)',

    `sale_type` String COMMENT '销售类型 预售pre，及时达 timely',

    `order_type` String COMMENT '订单类型 商城订单 E，门店接龙 S，拼团订单 G',

    `pay_time` DateTime COMMENT '支付时间',

    `send_type` String COMMENT '配送类型 自提get，商家自配送delivery，第三方配送 otherDelivery',

    `status` String COMMENT '订单状态',

    `order_time` DateTime COMMENT '下单时间',

    `receive_time` DateTime COMMENT '签收时间',

    `coupon_id` String COMMENT '优惠券id',

    `coupon_amount` Decimal(18,2) COMMENT '优惠金额',

    `u_name` String COMMENT '买家名称',

    `u_phone` String COMMENT '买家手机',

    `u_address` String COMMENT '买家地址',

    `u_address_name` String COMMENT '买家地址详情',

    `u_remark` String COMMENT '买家备注',

    `store_id` String COMMENT '门店id',

    `store_number` String COMMENT '门店编号',

    `store_name` String COMMENT '门店名称',

    `store_responsible_name` String COMMENT '门店负责人名称',

    `store_responsible_tel` String COMMENT '门店负责人电话',

    `timely_up_send` Decimal(18,2) COMMENT '最低起送价',

    `gmt_create` DateTime,

    `date_create` Date,

    `order_id` String,

    `first_order` UInt8,

    `activity_amount` Decimal(18,2) COMMENT '优惠活动金额',

    `voucher_amount` Decimal(18,2) COMMENT '代金券优惠金额'
)ENGINE = MergeTree(date_create,gmt_create,8192)

`

`INSERT INTO data_event_order_payed_success
(mid, uid, rel_bill_number, pay_type, total_amount, pay_amount, sale_type, order_type, pay_time, send_type, status, order_time, receive_time, coupon_id, coupon_amount, u_name, u_phone, u_address, u_address_name, u_remark, store_id, store_number, store_name, store_responsible_name, store_responsible_tel, timely_up_send, gmt_create, date_create, order_id, first_order, activity_amount, voucher_amount)
VALUES('soqa8', 'U21060800004', 'ESOQA8168297443795141', 'yy', 2580.00, 2580.00, 'pre', 'E', '2021-06-09 15:44:12.000', 'take', '20', '2021-06-09 15:44:05.000', '1970-01-01 08:00:00.000', '', 0.00, '', '', '', '', '', '2', 'GZ0002', 'xxx', 'xxx', '1111', 0.00, '2021-06-09 21:44:00.000', '2021-06-09', '50', 0, 0.00, 0.00);
INSERT INTO data_event_order_payed_success
(mid, uid, rel_bill_number, pay_type, total_amount, pay_amount, sale_type, order_type, pay_time, send_type, status, order_time, receive_time, coupon_id, coupon_amount, u_name, u_phone, u_address, u_address_name, u_remark, store_id, store_number, store_name, store_responsible_name, store_responsible_tel, timely_up_send, gmt_create, date_create, order_id, first_order, activity_amount, voucher_amount)
VALUES('rpq5w', 'U21120100003', 'ERPQ5W230301381810373', 'yy', 550.00, 550.00, 'timely', 'S', '2021-12-01 20:38:53.000', 'take', '20', '2021-12-01 20:38:45.000', '1970-01-01 08:00:00.000', '', 0.00, '', '', '', '', '', '58', '847', 'xxx', 'xxx', '1111', 0.00, '2021-12-01 20:38:53.000', '2021-12-01', '50', 1, 0.00, 0.00);
INSERT INTO data_event_order_payed_success
(mid, uid, rel_bill_number, pay_type, total_amount, pay_amount, sale_type, order_type, pay_time, send_type, status, order_time, receive_time, coupon_id, coupon_amount, u_name, u_phone, u_address, u_address_name, u_remark, store_id, store_number, store_name, store_responsible_name, store_responsible_tel, timely_up_send, gmt_create, date_create, order_id, first_order, activity_amount, voucher_amount)
VALUES('4oblt', 'U21070100006', 'E4OBLT177083951203205', 'yy', 100.00, 100.00, 'timely', 'E', '2021-07-04 11:36:36.000', 'delivery', '20', '2021-07-04 11:36:29.000', '1970-01-01 08:00:00.000', '', 0.00, '', '', '', '', '', '1', 'YH0001', 'xxx', 'xxx', '1111', 0.00, '2021-07-04 11:36:36.000', '2021-07-04', '50', 0, 0.00, 0.00);

INSERT INTO data_event_order_payed_success
(mid, uid, rel_bill_number, pay_type, total_amount, pay_amount, sale_type, order_type, pay_time, send_type, status, order_time, receive_time, coupon_id, coupon_amount, u_name, u_phone, u_address, u_address_name, u_remark, store_id, store_number, store_name, store_responsible_name, store_responsible_tel, timely_up_send, gmt_create, date_create, order_id, first_order, activity_amount, voucher_amount)
VALUES('rpq5w', 'U21120100003', 'ERPQ5W230301381810373', 'yy', 550.00, 550.00, 'timely', 'S', '2021-12-01 20:38:53.000', 'take', '20', '2021-12-01 20:38:45.000', '1970-01-01 08:00:00.000', '', 0.00, '', '', '', '', '', '58', '847', 'xxx', 'ccc', '1111', 0.00, '2021-12-01 20:38:53.000', '2021-12-01', '50', 1, 0.00, 0.00);
INSERT INTO data_event_order_payed_success
(mid, uid, rel_bill_number, pay_type, total_amount, pay_amount, sale_type, order_type, pay_time, send_type, status, order_time, receive_time, coupon_id, coupon_amount, u_name, u_phone, u_address, u_address_name, u_remark, store_id, store_number, store_name, store_responsible_name, store_responsible_tel, timely_up_send, gmt_create, date_create, order_id, first_order, activity_amount, voucher_amount)
VALUES('soqa8', 'U21060800004', 'ESOQA8168297443795141', 'yy', 2580.00, 2580.00, 'pre', 'E', '2021-06-09 15:44:12.000', 'take', '20', '2021-06-09 15:44:05.000', '1970-01-01 08:00:00.000', '', 0.00, '', '', '', '', '', '2', 'GZ0002', 'xxx', 'cc', '1111', 0.00, '2021-06-09 21:44:00.000', '2021-06-09', '50', 0, 0.00, 0.00);
INSERT INTO data_event_order_payed_success
(mid, uid, rel_bill_number, pay_type, total_amount, pay_amount, sale_type, order_type, pay_time, send_type, status, order_time, receive_time, coupon_id, coupon_amount, u_name, u_phone, u_address, u_address_name, u_remark, store_id, store_number, store_name, store_responsible_name, store_responsible_tel, timely_up_send, gmt_create, date_create, order_id, first_order, activity_amount, voucher_amount)
VALUES('4oblt', 'U21070100006', 'E4OBLT177083951203205', 'yy', 100.00, 100.00, 'timely', 'E', '2021-07-04 11:36:36.000', 'delivery', '20', '2021-07-04 11:36:29.000', '1970-01-01 08:00:00.000', '', 0.00, '', '', '', '', '', '1', 'YH0001', 'xxx', 'xxx', '1111', 0.00, '2021-07-04 11:36:36.000', '2021-07-04', '50', 0, 0.00, 0.00);`

`select t.*
from data_event_goods_payed t
inner join data_event_order_payed_success t1 on t.order_id = t1.order_id 
where 1=1 and  t.mid = '4oblt' and  t1.mid = '4oblt' and  t.date_create >= '2021-11-25' 
and  t.date_create <= '2021-12-05' and t1.order_type in ('G','E','S','C')`

![image](https://user-images.githubusercontent.com/40562593/144692955-9ac1cd10-106a-46a1-bf5f-bb3f5aa89eee.png)

**Comment by den-crane** [comment]
21.5.6.6 is invalid
issue is unreadable. 

Please provide steps to reproduce.

**Comment by Sharath-a26** [comment]
instead of 'where' try using 'and' along with 't.order_id = t1.order_id'
