### ISSUE TITLE
Show progress by default in non-interactive mode if stderr is a terminal.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#32238]
Motivation: I want all the beauty by default.

Also change the behaviour of `--progress` option.
`--progress 0` will turn off the progress indication.

Downsides: if you run a shell script with multiple invocations of clickhouse-client, you will also see the progress of every invocation while the script is being run. Actually this can be considered as improvement.

Alternatively we can write progress to `/dev/tty` instead of stderr. It will allow to show progress even if stderr is redirected.
But it may look too surprising for user.

**Comment by den-crane** [comment]
Only if terminal exists, without breaking bash/cron scripts
