### ISSUE TITLE
MaterializeMySQLSyncThread: Code: 1002, e.displayText() = DB::Exception: ParseMetaData: Unhandled data type:16

### ISSUE THREAD

**Issue by jack-tangguangjie** [ClickHouse/ClickHouse#32233]
2021.12.03 10:57:49.048253 [ 11021 ] {} <Error> MaterializedMySQLSyncThread: Code: 1002. DB::Exception: ParseMetaData: Unhandled data type:16. (UNKNOWN_EXCEPTION), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x9b737d4 in /usr/bin/clickhouse
1. DB::MySQLReplication::TableMapEvent::parseMeta(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) @ 0x11f87cf2 in /usr/bin/clickhouse
2. DB::MySQLReplication::TableMapEvent::parseImpl(DB::ReadBuffer&) @ 0x11f87455 in /usr/bin/clickhouse
3. DB::MySQLReplication::MySQLFlavor::readPayloadImpl(DB::ReadBuffer&) @ 0x11f8d1c1 in /usr/bin/clickhouse
4. DB::MySQLProtocol::IMySQLReadPacket::readPayload(DB::ReadBuffer&, unsigned char&) @ 0x11f77267 in /usr/bin/clickhouse
5. DB::MaterializedMySQLSyncThread::synchronization() @ 0x11f5e03d in /usr/bin/clickhouse
6. ? @ 0x11f6c693 in /usr/bin/clickhouse
7. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x9bb5897 in /usr/bin/clickhouse
8. ? @ 0x9bb929d in /usr/bin/clickhouse
9. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
10. __clone @ 0xfe8dd in /usr/lib64/libc-2.17.so
 (version 21.11.5.33 (official build))

Has anyone encountered the same problem？

**Comment by jack-tangguangjie** [comment]
I executed these following statements:

set allow_experimental_database_materialize_mysql=1;
CREATE DATABASE xxx ENGINE = MaterializeMySQL('127.0.0.1:3306','xxx','xxx','xxx');

Then clickhouse started to full synchronization by MaterializeMySQL from mysql.
But after a time,the log was:

2021.12.03 10:54:00.532752 [ 11023 ] {} <Information> MaterializedMySQLSyncThread: MySQL executed position: 
 
=== Binlog Position ===
Binlog: binlog.000002
Position: 357729053
GTIDSets: e82204c9-41e5-11ec-a795-00163e004429:1-1438551

2021.12.03 10:57:49.048084 [ 10906 ] {} <Error> MaterializedMySQLSyncThread: Code: 1002. DB::Exception: ParseMetaData: Unhandled data type:16. (UNKNOWN_EXCEPTION), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x9b737d4 in /usr/bin/clickhouse
1. DB::MySQLReplication::TableMapEvent::parseMeta(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) @ 0x11f87cf2 in /usr/bin/clickhouse
2. DB::MySQLReplication::TableMapEvent::parseImpl(DB::ReadBuffer&) @ 0x11f87455 in /usr/bin/clickhouse
3. DB::MySQLReplication::MySQLFlavor::readPayloadImpl(DB::ReadBuffer&) @ 0x11f8d1c1 in /usr/bin/clickhouse
4. DB::MySQLProtocol::IMySQLReadPacket::readPayload(DB::ReadBuffer&, unsigned char&) @ 0x11f77267 in /usr/bin/clickhouse
5. DB::MaterializedMySQLSyncThread::synchronization() @ 0x11f5e03d in /usr/bin/clickhouse
6. ? @ 0x11f6c693 in /usr/bin/clickhouse
7. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x9bb5897 in /usr/bin/clickhouse
8. ? @ 0x9bb929d in /usr/bin/clickhouse
9. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
10. __clone @ 0xfe8dd in /usr/lib64/libc-2.17.so
 (version 21.11.5.33 (official build))

No error will be reported when executing a simple query, but it will so  after restarting，the result was ：
Code: 1002. DB::Exception: ParseMetaData: Unhandled data type:16. (UNKNOWN_EXCEPTION)

**Comment by tavplubix** [comment]
#15182

**Comment by jack-tangguangjie** [comment]
This problem is very strange, because there is no bit type field in the mysql database I synchronized

**Comment by jack-tangguangjie** [comment]
> #15182

I have a MYSQL instance. Some of them have schemas with bit-type tables and some do not. When I use MaterializeMySQL to synchronize the schema data of tables that do not exist with bit-types, they can be synchronized. Then I go to modify the bit-type data, clickhouse will do Error: DB::Exception: ParseMetaData: Unhandled data type:16. Is this a bug?
