### ISSUE TITLE
Strange behavior:   mutation thread not exits when progess is 1

### ISSUE THREAD

**Issue by wangqinghuan** [ClickHouse/ClickHouse#32230]
1. add projection and materialize it .
2. select * from system.merges where is_mutation  = 1
![image](https://user-images.githubusercontent.com/22762150/144703863-c1532a3f-b268-4335-9e9d-622542d9f4be.png)
some threads not exit and keep occupy memory for several minutes  even though their progress is 100%. Is it a normal behavior?

**Comment by alexey-milovidov** [comment]
Yes, it is normal. It means that 100% of data was read and written but there can be some remaining bookkeeping work.
