### ISSUE TITLE
Allow marking columns as UNUSED to avoid unnecessary part mutations

### ISSUE THREAD

**Issue by siradjev** [ClickHouse/ClickHouse#32248]
**Use case**
As of now clickhouse is not very suitable for schemas with large number of partitioned tables that have high number of columns, since it eventually results in huge number of files that pushes OS limit, as well as slows down backup/restore like operations. 
E.g. 500 tables with 50 partitions with 1000 columns each result in more than 50 million files already (data+mark per column + other txt/idx files). It gets worse for nullable ones since there are 4 files per column (bin+mrk+nullablebin+nullablrmrk). 
When data accumulate for several years, it becomes nearly impossible to make modifications on tables or maintain the system.

Currently the only way to make it operable is to use COMPACT parts for all the table. 
This does not lose much in terms of performance, but gives proper manageability in terms of number of files (only databin/mrk files + 8-10 txt/idx files). 
However, alter table drop column causes whole data.bin/mrk to be rewritten, that is huge load and that problem has no direct solution. Given that dropping the columns is frequently made for the schema cleanup/convention reasons, and to prevent loading data in the future, while old/preexisting data being there as file may not be much of concern. 

**Describe the solution you'd like**

It would be great to allow special syntax for dropping column not causing mutation, with option to materialize it later on-demand (e.g. at night or during some maintenance). 

Set unused could be similar to https://oracle-base.com/articles/8i/dropping-columns#LogicalDelete
```
alter table table_name set unused (column_name1, column_name2);
```

In this case simple change would be made in metadata sql file (column will have UNUSED property). 
It will also allow to set columns back to used if there is such a need. 
```
alter table table_name set used (column_name1, column_name2);
```

Set used will have no issue, since clickhouse already makes no mutation on adding columns. 
Rename will be exactly same as it works for regular columns. 
Unused columns will be not queriable and will not be present in new parts.

and materialize could be: 
```
alter table table_name DROP UNUSED COLUMNS;
or
alter table table_name MATERIALIZE DROP COLUMNS;
```

The feature may also be useful for wide parts as well because, in case there are high number of parts in table, especially if they are replicated, since it would allow to avoid lengthy mutation altogether, similar to ADD COLUMN syntax. 

**Describe alternatives you've considered**
So far the only alternative is to create another table and use MergeEngine. But it's not that trivial, since merge engine does not work for inserts, hence some maintenance is required (either change loading logic, or stop loading logic and rename tables).

**Comment by UnamedRus** [comment]
Probably can be implemented like MATERIALIZED/ALIAS trait. (Related https://github.com/ClickHouse/ClickHouse/issues/31447)

**Comment by alexey-milovidov** [comment]
Compact parts were not meant to be used for 100% of data, only for small amount of data.

About 
> more than 50 million files already

What filesystem do you use? It should be ok for `ext4`.
