### ISSUE TITLE
Allow keeping primary key in memory partially for partitioned tables

### ISSUE THREAD

**Issue by siradjev** [ClickHouse/ClickHouse#32251]
**Use case**

As the data keeps growing primary key size keeps increasing, however primary key is same for whole the data, despite that older data is queried way less frequently.
Permanent memory usage however keeps increasing and once data is stored for a very long time, it would stop fitting memory anymore. Larger granularities could be used, however the setting is applicable table-level only,and impacts performance of queries using the key. 

**Describe the solution you'd like**

Partition-keys are generally small and they can always be kept in memory. 
There are two possible proposals that can also be complementary: 
- Define TTL-like construct to specify rule for which partitions to be kept in memory, allowing others to be read from disk on-demand as the query is executed after partition pruning (read all if no partition pruning is in query). 
- Define table property whether table index shall be kept in memory enitrely, or in LRU cache of predefined maximum size. This way more frequently used parts cache  will stay in memory, and least used once will be evicted. There could also be multiple priority levels for LRU cache usage, so lower priority ones can't evict higher priority ones. 

This can be an extension to one of below issues (allowing older data to have different partitioning, and also smaller primary key/primary key not completely in-memory):
- #16565
- #8089
- #18695

**Describe alternatives you've considered**
Multiple tables over merge engine, but it's maintenance effort would be quite high due to constant need of data moving from one table to another.  
Larger granularity can be used, however, data tends to grow infinitely, and cold data is typically kept on shared storage (S3, network, etc), and cluster memory is not increased proportionally.

**Comment by alexey-milovidov** [comment]
How many records are in your table, what is the primary key and index granularity, and what is the amount of memory on your server?

**Comment by den-crane** [comment]
There are some users with very narrow tables (3 columns / metric_id UInt64, ts UInt32, value Float64) they have
at each shard 
PK_bytes_in_memory  = 102 899 952 000

```
┌─table────────────┬─parts_─┬─────────rows_─┬─data_compressed_bytes_─┬─data_uncompres_b─┬─compress_%─┬────marks_─┬─marks_bytes_─┬─PK_bytes_in_memory─┐
│ graphite_week    │    312 │ 4655287052322 │          5500007931768 │  652139057466131 │       0.84 │ 568272793 │  68192735160 │       102899952000 │
│ graphite_tags    │     15 │     337419221 │            24909910566 │     296229026736 │        8.4 │     41212 │      8901792 │           31536256 │
```

https://t.me/clickhouse_ru/147626

**Comment by alexey-milovidov** [comment]
102 GB for 4.6 trillion records - not bad.
Maybe simply increase memory amount on server?

**Comment by den-crane** [comment]
> Maybe simply increase memory amount on server?

As I remember they decided to save money and changed index granularity to 32768

**Comment by siradjev** [comment]
> Maybe simply increase memory amount on server?
Typically most of our customers have fixed VM sizes and don't really appreciate super large RAM VMs. 
For those having HW servers, adding RAM may require quite a long time due to highly-regulated processes.

In our case another problem is that there is string that is part of the index used for prefix-search and it does take quite a space (200bytes avg length). 
Even some sort of flexible index granularity would across old/new data would be helpful, but it's not something possible (unless we change granularity, optimize-final old parts, change granularity again, optimize all parts in newly created partitions). 

There is also potential to improve clickhouse handling of string indexes with repeated prefix/substrings by "compressing" string indexes in memory by using shared dictionary or prefix information, but it's something more fundamental. 

So far the only available option is to simply use 2 tables, and use different indexing in them under a merge engine, but the data aging/moving process introduces unnecessary operation/maintenance overhead.

**Comment by siradjev** [comment]
> How many records are in your table, what is the primary key and index granularity, and what is the amount of memory on your server?

Single shard VM is with 64GB RAM. But we have individual queries that need 20-40GB of RAM to execute and those are causing issue... 

Table info (there are several tables that were versioned, so another one uses another 17GiB of RAM. 
```
SELECT
    sum(marks) / 1000000. AS millionmarks,
    sum(rows) / 1000000. AS millionrows,
    trunc(millionrows / millionmarks) AS marksPerRows,
    formatReadableSize(sum(primary_key_bytes_in_memory_allocated)) AS pkinmemsize,
    countDistinct(partition) AS partitioncnt
FROM system.parts
WHERE table = 'tblname'

┌─millionmarks─┬────millionrows─┬─marksPerRows─┬─pkinmemsize─┬─partitioncnt─┐
│   146.343633 │ 1198772.274121 │         8191 │ 26.24 GiB   │         2715 │
└──────────────┴────────────────┴──────────────┴─────────────┴──────────────┘
```

PartitionKey is date + Int32. 
PK is (Int32, String, UInt64)
String is 100 bytes on average.
