### ISSUE TITLE
Access rights changes during ALTER FREEZE

### ISSUE THREAD

**Issue by k0st1an** [ClickHouse/ClickHouse#32258]
### Describe the unexpected behaviour
When I make a backup of the table, the data rights are set to `0440`

```
ALTER TABLE DB.TABLE FREEZE WITH NAME 'ffff'
```

```
# ll data/DB/TABLE/202012_124_374523_16/
total 16641004
drwxr-x---  2 clickhouse clickhouse       4096 Dec  6 00:08 ./
drwxr-x--- 19 clickhouse clickhouse    1880064 Dec  6 00:13 ../
-r--r-----  2 clickhouse clickhouse   34828116 Dec  6 00:08 attr_type.bin
-r--r-----  2 clickhouse clickhouse         57 Dec  6 00:08 attr_type.dict.bin
...
```

### How to reproduce

```
ALTER TABLE DB.TABLE FREEZE WITH NAME 'ffff'
```

#### Which ClickHouse server version to use
```
SELECT version()

┌─version()──┐
│ 21.11.5.33 │
└────────────┘
```
### Expected behavior
There will be no expectation that the file permissions will change. For example, in version `21.7.7.47` this is not noticed.

**Comment by k0st1an** [comment]
Also the problem detected in version `21.11.2.2`.

**Comment by alexey-milovidov** [comment]
This behaviour exists since the beginning (when FREEZE command was introduced) and needed to protect files that was hardlinked and to avoid modification of backups. As all files in ClickHouse are immutable, additionally making them readonly should not be a concern.
