### ISSUE TITLE
CPU utilization

### ISSUE THREAD

**Issue by Fallenyasha** [ClickHouse/ClickHouse#32259]
Имеется свежий образ докера с КХ 21.11.4.14 установленный на Windows Docker WSL 2, и на CentOS.
Потребление ЦПУ в районе 0-2%

Создаем 500 таблиц вида create table test.table00 (f1 String) engine = MergeTree order by f1;
Нагрузка возрастает до 70-90%
Создаем 2000 таблиц и нагрузка возрастает до 270-300%

При этом никакой активности нет.

В логе только такие строки
2021.12.06 08:14:05.001473 [ 104 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 420.87 MiB, peak 1.28 GiB, will set to 424.85 MiB (RSS), difference: 3.98 MiB
2021.12.06 08:14:10.000889 [ 104 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 428.81 MiB, peak 1.28 GiB, will set to 424.80 MiB (RSS), difference: -4.01 MiB
2021.12.06 08:14:11.000139 [ 104 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 428.80 MiB, peak 1.28 GiB, will set to 424.84 MiB (RSS), difference: -3.96 MiB
2021.12.06 08:14:13.000247 [ 104 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 420.81 MiB, peak 1.28 GiB, will set to 424.80 MiB (RSS), difference: 3.99 MiB
2021.12.06 08:14:15.002225 [ 104 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 428.78 MiB, peak 1.28 GiB, will set to 424.75 MiB (RSS), difference: -4.03 MiB
2021.12.06 08:14:16.000635 [ 104 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 428.75 MiB, peak 1.28 GiB, will set to 424.77 MiB (RSS), difference: -3.98 MiB
2021.12.06 08:14:17.000131 [ 104 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 428.77 MiB, peak 1.28 GiB, will set to 424.79 MiB (RSS), difference: -3.99 MiB
2021.12.06 08:14:19.000269 [ 104 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 416.76 MiB, peak 1.28 GiB, will set to 424.77 MiB (RSS), difference: 8.01 MiB

Пробовал отключать логи, ничего не поменялось
```
<?xml version="1.0"?>
<yandex>
    <asynchronous_metric_log remove="1"/>
    <metric_log remove="1"/>
    <part_log remove="1"/>
    <text_log remove="1"/>
    <trace_log remove="1"/>
</yandex>

```

**Comment by alexey-milovidov** [comment]
This is related to background tasks for cleaning of old parts and selecting the parts to merge.

**Comment by Fallenyasha** [comment]
База с пустыми таблицами и нулевой активностью, ничего кроме создания таблиц не делалось, соответственно чистить и мержить попросту нечего. В старой версии КХ 19.* такого поведения не наблюдалось. Тут больше вопрос к зависимости нагрузки от количества объектов бд, т.е. если создать 10к таблиц, то можно предположить, что сервер попросту ляжет и не сможет обрабатывать никакие запросы.

Хотелось бы все-таки понять что же это такое и самое главное как избавиться от такой нагрузки.

**Comment by den-crane** [comment]
я не могу это воспроизвести ,  правда я использовал 21.12.1.8816

```
create database test_cpu;

for i in `seq 5000`; do echo -n $i ""; \
   clickhouse-client -q "CREATE TABLE if not exists test_cpu.test$i  (d DATE, p UInt64, s String) ENGINE = MergeTree PARTITION BY d ORDER BY p";
done;

```

единственная настройка

```
cat /etc/clickhouse-server/config.d/perf.xml
<?xml version="1.0"?>
<yandex>
   <asynchronous_metrics_update_period_s>60</asynchronous_metrics_update_period_s>
</yandex>
```

Загрузка cpu 1% до создания 5000 MergeTree!!!! таблиц, 2% после.

**Comment by den-crane** [comment]
> ничего кроме создания таблиц не делалось, соответственно чистить и мержить попросту нечего. 

ReplicatedMergeTreeCleanupThread и merge_selecting все равно постоянно просыпаются, но они не создают для такой нагрузки, их можно тюнить https://github.com/ClickHouse/ClickHouse/issues/31919

**Comment by den-crane** [comment]
а хотя да, с 21.11.4 загрузка cpu 30%

**Comment by den-crane** [comment]
21.11.5 тоже 30% ,  и merge_selecting_sleep_ms = 50000 не помогает

```
cat /etc/clickhouse-server/config.d/cat perf.xml
<?xml version="1.0"?>
<yandex>
   <asynchronous_metrics_update_period_s>60</asynchronous_metrics_update_period_s>

    <asynchronous_metric_log remove="1"/>
    <query_thread_log remove="1"/>
    <session_log remove="1"/>
    <query_log remove="1"/>
    <metric_log remove="1"/>
    <part_log remove="1"/>
    <text_log remove="1"/>
    <trace_log remove="1"/>

    <merge_tree>
	    <cleanup_delay_period>300</cleanup_delay_period>
	    <merge_selecting_sleep_ms>50000</merge_selecting_sleep_ms>
    </merge_tree>
</yandex>
```

**Comment by nikitamikhaylov** [comment]
Try to increase `merge_tree_clear_old_parts_interval_seconds` setting. Note, that is was deleted it 21.12, but present in 21.11

**Comment by den-crane** [comment]
Ah right, merge_tree_clear_old_parts_interval_seconds reduces CPU utilization significantly.

```
cat /etc/clickhouse-server/users.d/merge_tree_clear_old_parts_interval_seconds.xml
<?xml version="1.0" ?>
<yandex>
    <profiles>
        <default>
            	    <merge_tree_clear_old_parts_interval_seconds>360</merge_tree_clear_old_parts_interval_seconds>
        </default>
    </profiles>
</yandex>
```

**Comment by Fallenyasha** [comment]
Отчасти помогло, нагрузка с 270-300 упала до 50-60, однако раз в минуту секунд на 15-20 подпрыгивает до 120-150, в логе ничего нет.
Я так понимаю что в грядущей версии эту настройку убрали, т.е. процесс merge_tree_clear_old_parts оптимизирован и больше таких проблем не будет?

**Comment by den-crane** [comment]
>раз в минуту секунд на 15-20 подпрыгивает до 120-150

это скорее всего merge_selecting работает `<merge_selecting_sleep_ms>5000</merge_selecting_sleep_ms>`

**Comment by eboboshka** [comment]
Is there any update?

**Comment by alexey-milovidov** [comment]
@eboboshka There are no updates.

**Comment by den-crane** [comment]
@eboboshka can you describe your setup / issue? What version do you use? How many tables do you have?

This particular problem existed from 20.12 till 21.12. 

Plus in 22.6: Fix excessive CPU usage in background when there are a lot of tables. https://github.com/ClickHouse/ClickHouse/pull/38028 ([Maksim Kita](https://github.com/kitaisreal)).

**Comment by eboboshka** [comment]
@den-crane Thank you for the answer.
Maybe I'm overreacting right now. We are just planning to use CH (LTS) and are about to move with 5000+ databases. So before the move, we are investigating possible problems we may encounter. This issue was without status updates and associated PRs, so I just clarified the status

**Comment by den-crane** [comment]
@eboboshka read this https://kb.altinity.com/altinity-kb-schema-design/how-much-is-too-much/

**Comment by den-crane** [comment]
@eboboshka and this https://youtu.be/DP7l6Swkskw?t=3777
