### ISSUE TITLE
Randomization of settings in functional tests.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#32268]
We will create a list of settings and distributions of their values.
The settings will be randomly set before running functional tests, according to the distributions.
This can be implemented as a Python code directly inside `clickhouse-test` (no need for any configs or DSLs).

Examples:
- enable `convert_query_to_cnf` with probability 1/2;
- set `max_block_size` uniformly random in a range of 8000..100000;
- set `max_threads` uniformly random in a range of 1..64;

If a test needs fixed value of some setting, it should set it explicitly in the test.

**Comment by Avogar** [comment]
One more example: disabling setting `input_format_parallel_parsing` and changing `max_read_buffer_size` to small values. It will help to fuzz formats (using small `max_read_buffer_size` helped me to find some uncovered corner cases)

**Comment by CurtizJ** [comment]
Enabling `use_uncompressed_cache` will be also very helpful, because we almost doesn't have tests for it, but it's a surpriingly popular feature.
