### ISSUE TITLE
sequenceMatch function returns different results for tables with distributed engine

### ISSUE THREAD

**Issue by IvanStepanov** [ClickHouse/ClickHouse#32290]
`sequenceMatch` function returns different results on the same piece of data in distributed table depending on cluster node it was called. I have checked docs for both distributed engine and parametric functions and haven't found anyting related to the issue.

Steps to reproduce:

Consider cluster `mycluster` with 2 nodes (`node1` and `node2`).

Run on `node1`:
```sql
create table data on cluster mycluster (time UInt32, number UInt32) engine = MergeTree() order by time 
insert into data values (1, 2), (2, 3), (3, 4)
create table data_distributed on cluster mycluster as data engine = Distributed(mycluster, default, data)
```

Run query 
```sql
select sequenceMatch('(?1)(?2)')(time, number = 2, number = 3) from data_distributed
```
on both nodes, observe that results are different (1 on "data-owner" `node1` and 0 on `node2`).

Checked on version `21.11.5.33`

**Comment by vdimir** [comment]
Setting [distributed_group_by_no_merge](https://clickhouse.com/docs/en/operations/settings/settings/#distributed-group-by-no-merge) can be used to get result from all nodes and merge it locally:
```
SELECT countIf(r) FROM  (
	SELECT sequenceMatch('(?1)(?2)')(time, number = 2, number = 3) AS r FROM data_distributed
	SETTINGS distributed_group_by_no_merge=1
);
```

**Comment by amstel8** [comment]
Same issue.Several day ago updated from 21.3 to 21.11. 21.3 was ok.

**Comment by filimonov** [comment]
Fixed in https://github.com/ClickHouse/ClickHouse/pull/48603
