### ISSUE TITLE
when run clickhouse 20.8.8lts. get core dump  as follows:

### ISSUE THREAD

**Issue by miaojianxin** [ClickHouse/ClickHouse#32321]
(version 20.8.6.6)
2021.12.07 09:23:42.945038 [ 69114 ] {} <Fatal> BaseDaemon: ########################################
2021.12.07 09:23:42.945260 [ 69114 ] {} <Fatal> BaseDaemon: (version 20.8.6.6, no build id) (from thread 53303) (no query) Received signal Segmentation fault (11)
2021.12.07 09:23:42.945362 [ 69114 ] {} <Fatal> BaseDaemon: Address: 0x42c0 Access: write. Address not mapped to object.
2021.12.07 09:23:42.945447 [ 69114 ] {} <Fatal> BaseDaemon: Stack trace: 0x17dc11a4 0x17dc79bd 0x17dc7d26 0x17dcb997 0x17ded824 0x17db8ec4 0xeb1e5c8 0xeb1d8cb 0x16cbd10d 0x16cb6904 0x1784ef1b 0x178519d3 0x16bc52ae 0x17850a44 0x177a59d5 0x17877c29 0x177632b7 0x17532312 0x1753b2d1 0x176c9b2f 0x176ca485 0xeb1265c 0xeb10bdf 0x7f689120aea5 0x7f68909c78dd
2021.12.07 09:23:42.945572 [ 69114 ] {} <Fatal> BaseDaemon: 3. extent_deregister_impl.constprop.0 @ 0x17dc11a4 in /data/home/sqlgraph/mjx/ch1/clickhouse
2021.12.07 09:23:42.945671 [ 69114 ] {} <Fatal> BaseDaemon: 4. extent_recycle @ 0x17dc79bd in /data/home/sqlgraph/mjx/ch1/clickhouse
2021.12.07 09:23:42.945740 [ 69114 ] {} <Fatal> BaseDaemon: 5. extents_alloc @ 0x17dc7d26 in /data/home/sqlgraph/mjx/ch1/clickhouse
2021.12.07 09:23:42.945815 [ 69114 ] {} <Fatal> BaseDaemon: 6. arena_extent_alloc_large @ 0x17dcb997 in /data/home/sqlgraph/mjx/ch1/clickhouse
2021.12.07 09:23:42.945899 [ 69114 ] {} <Fatal> BaseDaemon: 7. large_malloc @ 0x17ded824 in /data/home/sqlgraph/mjx/ch1/clickhouse
2021.12.07 09:23:42.945963 [ 69114 ] {} <Fatal> BaseDaemon: 8. malloc_default @ 0x17db8ec4 in /data/home/sqlgraph/mjx/ch1/clickhouse
2021.12.07 09:23:42.946061 [ 69114 ] {} <Fatal> BaseDaemon: 9. DB::ReadBufferFromFileBase::ReadBufferFromFileBase(unsigned long, char*, unsigned long) @ 0xeb1e5c8 in /data/home/sqlgraph/mjx/ch1/clickhouse
2021.12.07 09:23:42.946148 [ 69114 ] {} <Fatal> BaseDaemon: 10. DB::ReadBufferFromFile::ReadBufferFromFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, int, char*, unsigned long) @ 0xeb1d8cb in /data/home/sqlgraph/mjx/ch1/clickhouse
2021.12.07 09:23:42.946242 [ 69114 ] {} <Fatal> BaseDaemon: 11. DB::createReadBufferFromFileBase(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, unsigned long, unsigned long, unsigned long, int, char*, unsigned long) @ 0x16cbd10d in /data/home/sqlgraph/mjx/ch1/clickhouse
2021.12.07 09:23:42.946329 [ 69114 ] {} <Fatal> BaseDaemon: 12. DB::DiskLocal::readFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, unsigned long, unsigned long, unsigned long) const @ 0x16cb6904 in /data/home/sqlgraph/mjx/ch1/clickhouse
2021.12.07 09:23:42.946440 [ 69114 ] {} <Fatal> BaseDaemon: 13. DB::MergeTreeReaderStream::MergeTreeReaderStream(std::__1::shared_ptr<DB::IDisk>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange> > const&, DB::MergeTreeReaderSettings const&, DB::MarkCache*, DB::UncompressedCache*, unsigned long, DB::MergeTreeIndexGranularityInfo const*, std::__1::function<void (DB::ReadBufferFromFileBase::ProfileInfo)> const&, int) @ 0x1784ef1b in /data/home/sqlgraph/mjx/ch1/clickhouse
2021.12.07 09:23:42.946551 [ 69114 ] {} <Fatal> BaseDaemon: 14. std::__1::__function::__func<DB::MergeTreeReaderWide::addStreams(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::IDataType const&, std::__1::function<void (DB::ReadBufferFromFileBase::ProfileInfo)> const&, int)::'lambda'(std::__1::vector<DB::IDataType::Substream, std::__1::allocator<DB::IDataType::Substream> > const&), std::__1::allocator<DB::MergeTreeReaderWide::addStreams(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::IDataType const&, std::__1::function<void (DB::ReadBufferFromFileBase::ProfileInfo)> const&, int)::'lambda'(std::__1::vector<DB::IDataType::Substream, std::__1::allocator<DB::IDataType::Substream> > const&)>, void (std::__1::vector<DB::IDataType::Substream, std::__1::allocator<DB::IDataType::Substream> > const&)>::operator()(std::__1::vector<DB::IDataType::Substream, std::__1::allocator<DB::IDataType::Substream> > const&) @ 0x178519d3 in /data/home/sqlgraph/mjx/ch1/clickhouse
2021.12.07 09:23:42.946701 [ 69114 ] {} <Fatal> BaseDaemon: 15. DB::DataTypeArray::enumerateStreams(std::__1::function<void (std::__1::vector<DB::IDataType::Substream, std::__1::allocator<DB::IDataType::Substream> > const&)> const&, std::__1::vector<DB::IDataType::Substream, std::__1::allocator<DB::IDataType::Substream> >&) const @ 0x16bc52ae in /data/home/sqlgraph/mjx/ch1/clickhouse
2021.12.07 09:23:42.946784 [ 69114 ] {} <Fatal> BaseDaemon: 16. DB::MergeTreeReaderWide::MergeTreeReaderWide(std::__1::shared_ptr<DB::MergeTreeDataPartWide const>, DB::NamesAndTypesList, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::UncompressedCache*, DB::MarkCache*, std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange> >, DB::MergeTreeReaderSettings, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, double, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, double> > >, std::__1::function<void (DB::ReadBufferFromFileBase::ProfileInfo)> const&, int) @ 0x17850a44 in /data/home/sqlgraph/mjx/ch1/clickhouse
2021.12.07 09:23:42.946892 [ 69114 ] {} <Fatal> BaseDaemon: 17. DB::MergeTreeDataPartWide::getReader(DB::NamesAndTypesList const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange> > const&, DB::UncompressedCache*, DB::MarkCache*, DB::MergeTreeReaderSettings const&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, double, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, double> > > const&, std::__1::function<void (DB::ReadBufferFromFileBase::ProfileInfo)> const&) const @ 0x177a59d5 in /data/home/sqlgraph/mjx/ch1/clickhouse
2021.12.07 09:23:42.946982 [ 69114 ] {} <Fatal> BaseDaemon: 18. DB::MergeTreeSequentialSource::MergeTreeSequentialSource(DB::MergeTreeData const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::IMergeTreeDataPart const>, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >, bool, bool, bool) @ 0x17877c29 in /data/home/sqlgraph/mjx/ch1/clickhouse
2021.12.07 09:23:42.947072 [ 69114 ] {} <Fatal> BaseDaemon: 19. DB::MergeTreeDataMergerMutator::mergePartsToTemporaryPart(DB::FutureMergedMutatedPart const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::MergeListEntry&, std::__1::shared_ptr<DB::RWLockImpl::LockHolderImpl>&, long, std::__1::unique_ptr<DB::IReservation, std::__1::default_delete<DB::IReservation> > const&, bool) @ 0x177632b7 in /data/home/sqlgraph/mjx/ch1/clickhouse
2021.12.07 09:23:42.947156 [ 69114 ] {} <Fatal> BaseDaemon: 20. DB::StorageMergeTree::merge(bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) @ 0x17532312 in /data/home/sqlgraph/mjx/ch1/clickhouse
2021.12.07 09:23:42.947216 [ 69114 ] {} <Fatal> BaseDaemon: 21. DB::StorageMergeTree::mergeMutateTask() @ 0x1753b2d1 in /data/home/sqlgraph/mjx/ch1/clickhouse
2021.12.07 09:23:42.947283 [ 69114 ] {} <Fatal> BaseDaemon: 22. DB::BackgroundProcessingPool::workLoopFunc() @ 0x176c9b2f in /data/home/sqlgraph/mjx/ch1/clickhouse
2021.12.07 09:23:42.947351 [ 69114 ] {} <Fatal> BaseDaemon: 23. ThreadFromGlobalPool::ThreadFromGlobalPool<DB::BackgroundProcessingPool::BackgroundProcessingPool(int, DB::BackgroundProcessingPool::PoolSettings const&, char const*, char const*)::'lambda'()>(DB::BackgroundProcessingPool::BackgroundProcessingPool(int, DB::BackgroundProcessingPool::PoolSettings const&, char const*, char const*)::'lambda'()&&)::'lambda'()::operator()() const @ 0x176ca485 in /data/home/sqlgraph/mjx/ch1/clickhouse
2021.12.07 09:23:42.947424 [ 69114 ] {} <Fatal> BaseDaemon: 24. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xeb1265c in /data/home/sqlgraph/mjx/ch1/clickhouse
2021.12.07 09:23:42.947533 [ 69114 ] {} <Fatal> BaseDaemon: 25. void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()> >(void*) @ 0xeb10bdf in /data/home/sqlgraph/mjx/ch1/clickhouse
2021.12.07 09:23:42.947644 [ 69114 ] {} <Fatal> BaseDaemon: 26. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
2021.12.07 09:23:42.947719 [ 69114 ] {} <Fatal> BaseDaemon: 27. __clone @ 0xfe8dd in /usr/lib64/libc-2.17.so

**Comment by alexey-milovidov** [comment]
Install the new ClickHouse version as following:
```
curl https://clickhouse.com/ | sh
```
