### ISSUE TITLE
I now have a ClickHouse cluster, how do I tell if RBAC is enabled on this cluster, because I don't want to know by looking at the configuration file, I want to know if there is a system table that records this information.

### ISSUE THREAD

**Issue by zqw961025** [ClickHouse/ClickHouse#32320]
I now have a ClickHouse cluster, how do I tell if RBAC is enabled on this cluster, because I don't want to know by looking at the configuration file, I want to know if there is a system table that records this information.

**Comment by cmsxbc** [comment]
maybe you can execute `show grants`  and `show grants for <user>`

**Comment by ILYenBui** [comment]
You can use `SHOW ROLES` to see if your cluster is already set up with roles.
You also can use the SQL command `SHOW ACCESS` to show all users, roles, profiles...and all their grants use without looking at the configuration file.
