### ISSUE TITLE
'ClickHouseMetrics_BackgroundPoolTask' Prometheus metric is missing in version 21.11.4.14

### ISSUE THREAD

**Issue by avinovarov** [ClickHouse/ClickHouse#32336]
**Describe the issue**
`ClickHouseMetrics_BackgroundPoolTask` metric in Prometheus exporter was available in version 21.3.5.42, not available now - neither in `system.metrics`, nor on exporter page.

It's important to us because currently under memory pressure some tasks get stuck in background pool which could block inserts, and we fire an alert in such cases.

**How to reproduce**
- Install Clickhouse version 21.11.4.14
- Run `SELECT * FROM system.metrics where metric like 'Background%';`
- Check `http://node:8001/metrics` page.

In 21.3 the metric existed: `BackgroundPoolTask | Number of active tasks in BackgroundProcessingPool (merges, mutations, or replication queue bookkeeping)`

* Which ClickHouse server versions are incompatible
21.11.4.14

**Comment by nikitamikhaylov** [comment]
You can use `BackgroundMergesAndMutationsPoolTask` instead. Now we have separate pools for each kind of tasks. Old metric BackgroundPoolTask was deleted intentionally, because it could lead to some misunderstanding.
