### ISSUE TITLE
feature request: Add retries to dictionary update process

### ISSUE THREAD

**Issue by xjewer** [ClickHouse/ClickHouse#3236]
Due to network nature, some blinks or spikes could happen, so the first attempt to update dictionary could be failed. 

It's nice to have some retry logic, as the remedy against an update failure is straightforward to do: `SYSTEM RELOAD DICTIONARY <dicitonary_name>`

**Comment by alexey-milovidov** [comment]
We already have (and always had) retries for dictionaries loading. 
Plase clarify your scenario.
