### ISSUE TITLE
在clickhouse 用mysql表引擎链接一张表，基于这张表做了物化视图，在mysql数据插入后，物化视图没有变化？难道还需要手动同步？

### ISSUE THREAD

**Issue by JiangTaoShi** [ClickHouse/ClickHouse#32368]
在clickhouse 用mysql表引擎链接一张表，基于这张表做了物化视图，在mysql数据插入后，物化视图没有变化？难道还需要手动同步？

**Comment by zzsmdfj** [comment]
MySQL 外表？还是物化库？外表当然不行了；在MySQL物化库里面的表上再建物化表，具我所知目前也是不可用的。
