### ISSUE TITLE
Add support for NATS

### ISSUE THREAD

**Issue by hashbash** [ClickHouse/ClickHouse#32388]
Add support for nats https://docs.nats.io/nats-concepts/what-is-nats
similar to Clickhouse Kafka connector

**Comment by tchepavel** [comment]
Taken to work

**Comment by shaneshort** [comment]
I haven't seen any update on this one, is there a public repo where we can help on this?

**Comment by alexey-milovidov** [comment]
@hashbash @shaneshort The pull request #37171 is very close to be merged.

**Comment by lesha888** [comment]
https://github.com/ClickHouse/ClickHouse/issues/41432

**Comment by lesha888** [comment]
[Nats engine used always minimum 100% of cpu core per one table](https://github.com/ClickHouse/ClickHouse/issues/41432)
