### ISSUE TITLE
Client: long queries are not removed when navigating through history

### ISSUE THREAD

**Issue by tavplubix** [ClickHouse/ClickHouse#32399]
**How to reproduce:**
1. Run several long queries in `clickhouse-client` such that query does not fit into one line in terminal
2. Try to navigate through history using "up" and "down" keys
3. You will see something like this:

![Screenshot from 2021-12-08 16-16-06](https://user-images.githubusercontent.com/14847450/145214824-6100431e-f8c5-41e6-8f5f-26449e650f64.png)

It makes query history almost impossible to use.

**Expected behavior:**
Client should remove previous query from terminal before printing the next one (just like it worked in older versions and how it works now if query fits into one line)
![Screenshot from 2021-12-08 16-20-59](https://user-images.githubusercontent.com/14847450/145215435-19951d95-f26f-4e78-9b53-bd23bb82959f.png)
![Screenshot from 2021-12-08 16-21-26](https://user-images.githubusercontent.com/14847450/145215454-ca691a3d-1dfc-4df4-ab17-66486da3ff55.png)

**Comment by alexey-milovidov** [comment]
+1, I've also noticed it.

**Comment by amosbird** [comment]
Fixed in https://github.com/AmokHuginnsson/replxx/pull/130
