### ISSUE TITLE
clickhouse支持mips架构吗

### ISSUE THREAD

**Issue by zhangshdn** [ClickHouse/ClickHouse#32428]
请问clickhouse是否支持mips架构下源码编译，如果能需要什么修改或者额外操作吗？

**Comment by den-crane** [comment]
Does clickhouse support source code compilation under mips architecture, if any modifications or additional operations are needed?

**Comment by cmsxbc** [comment]
根据之前的回答，应该是不支持的。 #25392
MIPS is not supported as answered in #25392

**Comment by alexey-milovidov** [comment]
See this: https://github.com/ClickHouse/ClickHouse/pull/29974
and this: https://github.com/ClickHouse-Extras/sysroot

**Comment by alexey-milovidov** [comment]
I appreciate if you will help adding MIPS64.

**Comment by zhangshdn** [comment]
Are there any plans to support MIPS next year or later

**Comment by alexey-milovidov** [comment]
We don't have this plans for our team.
If we will receive a pull request from community, we will help merging it and supporting the build.

**Comment by zhangshdn** [comment]
OK, thank you. Then I'll put forward this suggestion to the community. Ha ha

**Comment by alexey-milovidov** [comment]
Discussion: https://news.ycombinator.com/item?id=26846718
