### ISSUE TITLE
Unknown codec family code: 0  UNKNOWN_CODEC

### ISSUE THREAD

**Issue by alexeyrusnak** [ClickHouse/ClickHouse#32420]
Hi!

After update to 21.11 from 21.10 we have a huge amounts of errors such

2021.12.08 16:22:05.466212 [ 290791 ] {} <Error> void DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::routine(DB::TaskRuntimeDataPtr) [Queue = DB::MergeMutateRuntimeQueue]: Code: 432. DB::Exception: Unknown codec family code: 0: (while reading column subscriber_login): (while reading from part /var/lib/clickhouse-cold/data/qoestor/%2Einner%2Esubscribers_flow/1638309600_6435450_6435480_2/ from mark 0 with max_rows_to_read = 8192): While executing MergeTreeSequentialSource. (UNKNOWN_CODEC), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x9b737d4 in /usr/bin/clickhouse
1. DB::CompressionCodecFactory::get(unsigned char) const @ 0x11b84d12 in /usr/bin/clickhouse
2. DB::CompressedReadBufferBase::readCompressedData(unsigned long&, unsigned long&, bool) @ 0x11b79126 in /usr/bin/clickhouse
3. DB::CompressedReadBufferFromFile::nextImpl() @ 0x11b7b015 in /usr/bin/clickhouse
4. ? @ 0x11d5cba1 in /usr/bin/clickhouse
5. DB::ISerialization::deserializeBinaryBulkWithMultipleStreams(COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, DB::ISerialization::DeserializeBinaryBulkSettings&, std::__1::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, COW<DB::IColumn>::immutable_ptr<DB::IColumn> > > >*) const @ 0x11d26815 in /usr/bin/clickhouse
6. DB::MergeTreeReaderWide::readData(DB::NameAndTypePair const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, bool, unsigned long, unsigned long, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, COW<DB::IColumn>::immutable_ptr<DB::IColumn> > > >&, bool) @ 0x12ed9fc2 in /usr/bin/clickhouse
7. DB::MergeTreeReaderWide::readRows(unsigned long, unsigned long, bool, unsigned long, std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >&) @ 0x12ed8d99 in /usr/bin/clickhouse
8. DB::MergeTreeSequentialSource::generate() @ 0x12edcef7 in /usr/bin/clickhouse
9. DB::ISource::tryGenerate() @ 0x1316a1f5 in /usr/bin/clickhouse
10. DB::ISource::work() @ 0x13169dba in /usr/bin/clickhouse
11. DB::SourceWithProgress::work() @ 0x13376562 in /usr/bin/clickhouse
12. ? @ 0x1318565b in /usr/bin/clickhouse
13. DB::PipelineExecutor::executeStepImpl(unsigned long, unsigned long, std::__1::atomic<bool>*) @ 0x13181611 in /usr/bin/clickhouse
14. DB::PipelineExecutor::executeStep(std::__1::atomic<bool>*) @ 0x1317fe25 in /usr/bin/clickhouse
15. DB::PullingPipelineExecutor::pull(DB::Chunk&) @ 0x1318e88b in /usr/bin/clickhouse
16. DB::PullingPipelineExecutor::pull(DB::Block&) @ 0x1318eb2c in /usr/bin/clickhouse
17. DB::MergeTask::ExecuteAndFinalizeHorizontalPart::executeImpl() @ 0x12d92d6b in /usr/bin/clickhouse
18. DB::MergeTask::ExecuteAndFinalizeHorizontalPart::execute() @ 0x12d92ccb in /usr/bin/clickhouse
19. DB::MergeTask::execute() @ 0x12d979ba in /usr/bin/clickhouse
20. DB::MergePlainMergeTreeTask::executeStep() @ 0x130118ec in /usr/bin/clickhouse
21. DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::routine(std::__1::shared_ptr<DB::TaskRuntimeData>) @ 0x12da641d in /usr/bin/clickhouse
22. DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::threadFunction() @ 0x12da6eba in /usr/bin/clickhouse
23. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0x9bb848a in /usr/bin/clickhouse
24. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()&&...)::'lambda'()::operator()() @ 0x9bba2a7 in /usr/bin/clickhouse
25. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x9bb5897 in /usr/bin/clickhouse
26. ? @ 0x9bb929d in /usr/bin/clickhouse
27. start_thread @ 0x82de in /usr/lib64/libpthread-2.28.so
28. clone @ 0xfbe83 in /usr/lib64/libc-2.28.so
 (version 21.11.5.33 (official build))

**Comment by alexeyrusnak** [comment]
I don`t know what it can be. Please help. Should we downgrade?

**Comment by KochetovNicolai** [comment]
Can be after #25165

**Comment by KochetovNicolai** [comment]
@alexeyrusnak could you show a table structure?
If you can reproduce on some obfuscated data - it would be extremely helpful

**Comment by alexeyrusnak** [comment]
> @alexeyrusnak could you show a table structure?
[fullflow_agg.txt](https://github.com/ClickHouse/ClickHouse/files/7687231/fullflow_agg.txt)
[subscribers_flow.txt](https://github.com/ClickHouse/ClickHouse/files/7687232/subscribers_flow.txt)

Hi
Please see attachments 
In fullflow_agg we have problem with source_ip column
In subscribers_flow we have problem with subscriber_login column

Unfortunately I don’t have problems in lab. Only on production server and I don`t have access to it. I can only ask logs and information.

**Comment by alexeyrusnak** [comment]
We solved it by removing problem parts with  UNKNOWN_CODEC

**Comment by alexey-milovidov** [comment]
Do you use MergeTree or ReplicatedMergeTree?

**Comment by alexeyrusnak** [comment]
> Do you use MergeTree or ReplicatedMergeTree?

The problem was in 2 tables with AggregatingMergeTree  and ReplacingMergeTree engines.
We don`t use Replicated.
