### ISSUE TITLE
Extend 'X-ClickHouse-Progress' header in HTTP protocol

### ISSUE THREAD

**Issue by alex-zaitsev** [ClickHouse/ClickHouse#3242]
HTTP protocol allows to track query execution process. Currently it returns following data:

< X-ClickHouse-Progress: {"read_rows":"88089","read_bytes":"1884341","total_rows":"122925998080"}

Would be more useful for the client to have 'percent_complete' or something similar to display the progress bar, similar to clickhouse-client

**Comment by perez1987** [comment]
+1

**Comment by blinkov** [comment]
Console client basically just receives the same numbers and divides `read_rows` by `total_rows` with couple additional tricks.
See https://github.com/yandex/ClickHouse/blob/master/dbms/programs/client/Client.cpp#L1382

**Comment by alex-zaitsev** [comment]
If it is used from some JS, for example, it may be complicated, since JS does not support Int64, while total rows may easily exceed that.

**Comment by filimonov** [comment]
Javascript uses Floats for big numbers. And it's completely ok to use floats for percent calculations:

```javascript
x = JSON.parse('{"read_rows":"12292599800000000000000","read_bytes":"1884341","total_rows":"122925998000000000000000"}');
percent = 100 * x.read_rows / x.total_rows;
```

**Comment by alex-zaitsev** [comment]
There is always a workaround. This is a usability question.

**Comment by filimonov** [comment]
Actually, there are different problems with progress in HTTP.

For example when you get a streaming output  (like 'SELECT columns FROM big_table PREWHERE condition_meet_thousands_of_rows')  and server buffer is full server start sending data and stop sending progress. 

Or there are often moment when progress came to 'almost' finish - and process something which can't estimate and it you will output speed of processing (in rows/s, Gb/s) you see that progress came to 100% stop there for minutes, while speed continuously degrades.

Or you don't get the final stats in HTTP. 

But if calculating percents makes some problems for some scenarios - it's really easy to add.

**Comment by filimonov** [comment]
Please check that: https://github.com/yandex/ClickHouse/issues/208

**Comment by simPod** [comment]
The response would be larger in data size and those % are implicit and can be calculated everywhere. I think that would be a step back as there's no really need for that.
