### ISSUE TITLE
number convert error

### ISSUE THREAD

**Issue by lingbao08** [ClickHouse/ClickHouse#32430]
> You have to provide the following information whenever possible.

**Describe what's wrong**

I found error with number 0.00 from mysql to clickhouse ,it will be change to -8388611294967297.55(only one distortion value).
in mysql, the column defined with `setl_prcp decimal(16, 2) default 0.00 null`,engine is `innodb`;
in clickhouse,the column defined with `setl_prcp Nullable(Decimal(16, 2))`,engine is `MaterializedMySQL(_version)`.
it happend 4 times in 667809 piece of data. and this case is more and more frequatily.
mysql version is `5.7.24-log`,clickhouse version is `21.11.5.33`.
the question happend time : from 2021-11-19 23:12:55 to now. 
and I used lastest version('21.11.5.33') yesterday, I found 2 piece of  data was error be changed.

now, I used `toDecimal32OrZero(toString(setl_prcp),2) setl_prcp` to make the value is right because my orignal value is 0.00.
but it is not a long-term plan. it will happend with everywhere. so I hope you solve it.

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/19597

**Comment by den-crane** [comment]
Will fixed in the next CH release
