### ISSUE TITLE
Update AWS S3 SDK

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#32439]
> wondering on support for aws s3 object lambda - basically instead of providing with a bucket name, this functioanilty allows to provide a bucket ARN arn:aws:s3-object-lambda:eu-west-1:407416054022:accesspoint/test .
> What happens in the background is that a request to an s3 object with GET, will first run a lambda funtion on the specified object. This is need for GDPR compliance.
> with the current cpp sdk installed with version 21.8 I get the following error -
> Custom endpoint is not compatible with Access Point ARN or Outposts ARN in Bucket field.
> you can see here https://github.com/aws/aws-sdk-cpp/blob/e4223509ba1bcc5807dfb4f1afef01fdc83ad8c2/aws-cpp-sdk-s3/include/aws/s3/S3ARN.h#L27 that support was added to the SDK on 18/3/2021.
> sdk version that introduced it is 1.8.168, while if I'm not mistaken the current sdk in use in CH is 1.7.321
> 
> Any plans of bumping the SDK version soon ?

**Comment by alexey-milovidov** [comment]
Yes, we should update it.

**Comment by alexey-milovidov** [comment]
@filimonov Let's do it.

**Comment by alexey-milovidov** [comment]
@filimonov Why not?

**Comment by alexey-milovidov** [comment]
@filimonov Please update it as you want.

**Comment by alexey-milovidov** [comment]
@filimonov It is time to update AWS SDK.

**Comment by filimonov** [comment]
@excitoon was assigned to that. But he stuck with some other things...

**Comment by filimonov** [comment]
> sdk version that introduced it is 1.8.168, while if I'm not mistaken the current sdk in use in CH is 1.7.321

It's actually 1.8.121. 

Current is 1.9.237

**Comment by excitoon** [comment]
Let's update it.
