### ISSUE TITLE
ODBC bridge example doesn't work

### ISSUE THREAD

**Issue by x052bb** [ClickHouse/ClickHouse#32441]
(you don't have to strictly follow this form)

Clickhouse version: 21.9.2.17

ODBC bridge:
https://clickhouse.com/docs/en/operations/utilities/odbc-bridge/

Example mentioned in the above document doesn't work.
Getting error:

`
No 'sample_block' in request URL
`

**Comment by kssenii** [comment]
Need to substitute `columns` parameter name with `sample_block`. Just name.
