### ISSUE TITLE
Sizes of columns doesn't match: While executing SinkToOutputStream

### ISSUE THREAD

**Issue by lingtaolf** [ClickHouse/ClickHouse#32442]
**Clickhouse version**
21.7.4
**Describe what's wrong**
When I execute query below on the client , clickhouse will give an error message `Sizes of columns doesn't match: While executing SinkToOutputStream`  
  
```sql

INSERT INTO test3 SELECT
    mid,
    map1,
    map2,
    log_date
FROM
(
    SELECT
        mid AS mid,
        multiIf((CAST(visit_days_from_last_7d, 'Int32') > 0) AND (CAST(visit_days_from_last_30d, 'Int32') > 0), map('7d', visit_days_from_last_7d, '30d', visit_days_from_last_30d), CAST(visit_days_from_last_7d, 'Int32') > 0, map('7d', visit_days_from_last_7d), CAST(visit_days_from_last_30d, 'Int32') > 0, map('30d', visit_days_from_last_30d), map('', '')) AS map1,
        multiIf((CAST(visit_days_from_last_7d, 'Int32') > 0) AND (CAST(visit_days_from_last_30d, 'Int32') > 0), map('7d', visit_days_from_last_7d, '30d', visit_days_from_last_30d), CAST(visit_days_from_last_7d, 'Int32') > 0, map('7d', visit_days_from_last_7d), CAST(visit_days_from_last_30d, 'Int32') > 0, map('30d', visit_days_from_last_30d), map('', '')) AS map2,
        log_date AS log_date
    FROM test_source
    WHERE log_date = '20211118'
    LIMIT 50000
) AS a

Query id: a0071ba9-b339-4d4b-b11f-f94453061cb2


0 rows in set. Elapsed: 0.066 sec.

Received exception from server (version 21.7.4):
Code: 9. DB::Exception: Received from xxxx:9000. DB::Exception: Sizes of columns doesn't match: While executing SinkToOutputStream.
  
```   
The expression for `map1` and `map2` are same.    

> A clear and concise description of what works not as it is supposed to.

After debugging, I found column `map1` and column `map2` point to  the same column while squashing block in `SquashingTransform::append`. It means if clickhouse insert block to `accumulated_block`, column map1 and map2 will be inserted twice. So those two column size will be different from other columns.  
   
Clickhouse will reuse same object if the expression for different columns are same ? Is this a feature or bug?

**Comment by alexey-milovidov** [comment]
This issue has been fixed.
You can install the new version as following
```
curl https://clickhouse.com/ | sh
```

**Comment by fuwhu** [comment]
> This issue has been fixed. You can install the new version as following
> 
> ```
> curl https://clickhouse.com/ | sh
> ```

@alexey-milovidov 
could you please share the PR that fix this problem ?
