### ISSUE TITLE
Is there any way to make the materialized view delete data synchronously with the original table? 

### ISSUE THREAD

**Issue by fsgdgsdfgsgd** [ClickHouse/ClickHouse#32446]
Hi guys,
We want to calculate some metrics in ClickHouse, but because our data volume is too big, so it is difficult to get results directly on the original data. So we want to create a materialized view to incrementally calculate data and then use SummingMergeTree engine to merge data of the same dimension.
One problem with this solution is that due to the timeliness of our data, when the old data expires, we will delete them from the original table, but according to the description of the [document,](https://clickhouse.com/docs/en/sql-reference/statements/create/view/#materialized) this deletion process cannot be synchronized to the view. Is there any way can solve this problem?

**Comment by alexey-milovidov** [comment]
You can use projections for this task:
https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/mergetree/#projections

**Comment by amangoyal-angelone** [comment]
my understanding is projections apply only to a single table and not on a query. Is there any way such that we can sync deletes between table and materialized view? @alexey-milovidov
