### ISSUE TITLE
When writing concurrently，some request failed.

### ISSUE THREAD

**Issue by Sallery-X** [ClickHouse/ClickHouse#32451]
Version: 21.3-lts
The error as follows:
DB::NetException: Connection reset by peer, while writing to socket (127.0.0.1:9000): data for INSERT was parsed from stdin

**Comment by den-crane** [comment]
How I can reproduce it?

**Comment by Sallery-X** [comment]
> How I can reproduce it?

Start multiple replicas, each replica executes multiple query like 'clickhouse client -t --query "INSERT INTO lineorder_d FORMAT CSV" < lineorder.tbl', then some proc will failed and throw the exception like 'DB::NetException: Connection reset by peer, while writing to socket (127.0.0.1:9000): data for INSERT was parsed from stdin'

**Comment by den-crane** [comment]
What is lineorder_d? Where I can get  lineorder.tbl?

**Comment by den-crane** [comment]
no repro
