### ISSUE TITLE
Unwated row deduplication inserting to distributed tables

### ISSUE THREAD

**Issue by ewanwalk** [ClickHouse/ClickHouse#32486]
Clickhouse version: 21.8

I have an `AggregatingMergeTree` backed `Distributed` Table that looks similar to the following:

```sql
CREATE TABLE IF NOT EXISTS db.data ON CLUSTER '{cluster}' (
  `hour_id` Int8,
  `date` Date,
  `p_id` Int64,
  `a_id` Int64,
  `s_id` Int64,
  `z_id` Int64,
  `z_t_id` Int16,
  `c_id` Int64,
  `a` SimpleAggregateFunction(sum, Int64),
  `b` SimpleAggregateFunction(sum, Int64),
  `c` SimpleAggregateFunction(sum, Int64),
  `d` SimpleAggregateFunction(sum, Int64),
  `e` SimpleAggregateFunction(sum, Decimal128(8)),
  `f` SimpleAggregateFunction(sum, Decimal128(8))
) ENGINE = AggregatingMergeTree()
PARTITION BY `date`
ORDER BY (
  `hour_id`, `date`, `p_id`, `a_id`, `s_id`, `z_id`, `z_t_id`, `c_id`
)

CREATE TABLE IF NOT EXISTS db.dist_data ON CLUSTER '{cluster}' AS db.data
ENGINE = Distributed('{cluster}', statistics, data, hour_id);
```

When I Insert to `db.dist_data` (via. transaction) multiple rows, I should see any of the `SimpleAggregateFunction` columns incrementing but instead I am seeing only a single increment for each insert, which leads me to believe that the rows are being de-duplicated somehow. What is more odd is that I did not see this while I was developing on a local cluster.

So what I expect is that if I insert (for example)
```
INSERT INTO db.dist_data (hour_id, p_id, a) VALUES (1, 1, 1);
INSERT INTO db.dist_data (hour_id, p_id, a) VALUES (1, 1, 1);
INSERT INTO db.dist_data (hour_id, p_id, a) VALUES (1, 1, 1);
```

the `a` column should read `3` as its value, but instead its reading `1`.

Is there something I am missing here?

Edit:

It appears that using version 21.11 fixes this issue,

**Comment by ewanwalk** [comment]
> Do you use ReplicatedAggreagatingMergeTree OR AggregatingMergeTree ?

AggregatingMergeTree specifically

**Comment by den-crane** [comment]
Cannot reproduce with 21.8.10.19

```
select hour_id, p_id, sum(a) from dist_data group by hour_id, p_id;
┌─hour_id─┬─p_id─┬─sum(a)─┐
│       1 │    1 │      3 │
└─────────┴──────┴────────┘
```

**Comment by ewanwalk** [comment]
It does appear that updating to 21.11 resolved my issue, I can close this for now.
