### ISSUE TITLE
support some form of EXECUTE

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#32495]
Usecase: one query generates some query parameters / or even a full query, which can be executed via EXECUTE statement in the same clickhouse session.

Alternative: generate the query with one clickhouse-client instance and pass the query via pipe to another clickhouse-client instance.

**Comment by alexey-milovidov** [comment]
I would better avoid it, but we also have one related experimental task - to implement ad-hoc correlated subqueries like this:

```
SELECT ... WHERE eval($$ SELECT a WHERE x = {param:UInt8} $$, y) > 0
```

\- a function to evaluate parametrized query for every row.
