### ISSUE TITLE
Keep getting "Coordination::Exception: Can't get data for node ... node doesn't exist (No node). (KEEPER_EXCEPTION) on cluster

### ISSUE THREAD

**Issue by artemisiaohno** [ClickHouse/ClickHouse#32509]
We have got the simplest clickhouse cluster setup: 2 shards, 2 replicas per shard. Data is written into a distributed table on a single node. We use the internal_replication method.

Sometimes we get an exception on write:
```
executeQuery: Code: 999. Coordination::Exception: Can't get data for node /clickhouse/tables/02/_experiment_session_events/blocks/202109-15_2708049193500530745_14379102412782329402: node doesn't exist (No node). (KEEPER_EXCEPTION) (version 21.11.4.14 (official build)) (from XXX:41600) (in query: INSERT INTO ml._experiment_session_events (date, experiment, "a lot of fields") VALUES), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x9b605d4 in /usr/bin/clickhouse
1. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error, int) @ 0x134a60d5 in /usr/bin/clickhouse
2. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error) @ 0x134a6416 in /usr/bin/clickhouse
3. zkutil::ZooKeeper::get(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Stat*, std::__1::shared_ptr<Poco::Event> const&) @ 0x134b0ef2 in /usr/bin/clickhouse
4. DB::ReplicatedMergeTreeSink::commitPart(std::__1::shared_ptr<zkutil::ZooKeeper>&, std::__1::shared_ptr<DB::IMergeTreeDataPart>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__
```

```
db: version 21.11.4 revision 54450.
zookeeper: apache-zookeeper-3.6.3-bin
```

our tables:
```
-- distributed
CREATE TABLE ml.experiment_session_events
(                      
    `date` DateTime,
    `experiment` UInt16,
    ...
)
ENGINE = Distributed('ml', 'ml', '_experiment_session_events', rand())

-- local
CREATE TABLE ml._experiment_session_events
(                            
    `date` DateTime,               
    `experiment` UInt16,                                                                                                                                                                                           
    ...
)
ENGINE = ReplicatedSummingMergeTree('/clickhouse/tables/{shard}/_experiment_session_events', '{replica}', count)
PARTITION BY (toYYYYMM(date), experiment, ...)
ORDER BY (toStartOfDay(date), experiment, ...)
TTL date + toIntervalDay(730)
SETTINGS index_granularity = 8192    
```

We found out that probably there is a problem:
https://github.com/ClickHouse/ClickHouse/blob/751b2f3a7cf68537ab442be2d52b3d5af43fdb5b/src/Storages/MergeTree/ReplicatedMergeTreeSink.cpp#L342

But it's hard to evaluate how bad it is. Is it ok to get this error? Should we try to change any settings? Thanks!

**Comment by 596192804** [comment]
I also encountered this problem. I repeatedly drop and create the table several times, and then it no longer reported this error. It feels like a hidden bug.

**Comment by indexk09** [comment]
same here, any update on this?

**Comment by yi** [comment]
We encountered this problem on Clickhouse version 22.2.2.1.

This issue is 100% reproducable by following steps:

 1. create a replicated table: table A
 2. drop table A
 3. create table A again, clickhouse will then refuse to create a table, for metadata already exists on zookeeper KEEPER_EXCEPTION
 4. deleteall table A path (/clickhouse/tables/01-01/database-name/TableA)  on zookeeper
 5. check zookeeper sync, make sure all zookeeper nodes have deleted that metadata of table A
 6. create table A, everything will work fine
 7. after a few minutes, clickhouse keep saying `DB::StorageReplicatedMergeTree::mutationsUpdatingTask(): Code: 999. Coordination::Exception: No node, path: /clickhouse/tables/01-01/database-name/TableA/mutations. (KEEPER_EXCEPTION), Stack trace (when copying this message, always include the lines below)`

The root cause of this issue might be in step 2: when droping a table, for some reason its metadata is remained in zookeeper and not deleted.

We have been use clickhouse v20.x on another set, and does not experience this issue when repeatedly creating/drop tables

**Comment by yi** [comment]
Seems I misused the atomic database engine.

Solution:
 - use `DROP TABLE t SYNC`

or, which I think is better, to disable atomic engin on dev environment

refer to:
 - https://github.com/ClickHouse/ClickHouse/issues/29808#issuecomment-936878102
 - https://kb.altinity.com/engines/altinity-kb-atomic-database-engine/

**Comment by qiuyuyin** [comment]
same problem, just drop table sync can solve this.

**Comment by wangdefa7** [comment]
I also encountered this problem. However, after I synchronously deleted the table and recreated it, the problem was not solved

[ 191410 ] {98636d67-73ea-41e8-8ad3-bbf958c2f9a4} <Error> executeQuery: Code: 999. Coordination::Exception: Can't get data for node '/clickhouse/table/1/ts_kv_latest_cluster/blocks/202505_2294769104722990493_8809271246091247181': node doesn't exist. (KEEPER_EXCEPTION) (version 24.1.1.2048 (official build)) (from 172.16.11.150:58828) (in query: insert into ts_kv_latest_cluster (entity_id,key,ts,bool_v,str_v,long_v,dbl_v,json_v) FORMAT RowBinary ), Stack trace (when copying this message, always include the lines below):

0. ? @ 0x000000000c802edb in /usr/bin/clickhouse


1.
DROP TABLE iot.ts_kv_latest_cluster SYNC;
DROP TABLE iot.ts_kv_latest_cluster_all SYNC; 

2.
DROP TABLE iot.ts_kv_latest_cluster ON CLUSTER ck_cluster SYNC;
DROP TABLE iot.ts_kv_latest_cluster_all ON CLUSTER ck_cluster SYNC;

**Comment by wangdefa7** [comment]
Is the error report you encountered continuous or occasional? What I encountered was occasional, occurring approximately once every hour or every few dozen minutes

**Comment by wangdefa7** [comment]
@yi @qiuyuyin @filimonov   Please help take a look

**Comment by den-crane** [comment]
@wangdefa7 you probably experience completely other issue.

Check that you keeper/zookeeper cluster is really a cluster not standalone nodes.

```
echo stat |nc localhost 2181
...
Mode: follower
...
```

It should be like 1 leader and 2 followers.

**Comment by wangdefa7** [comment]
The two deployed nodes use CkKeeper instead of zookeeper, achieving two replicas in one shard.
The keeper that comes with clickhouse is used


[root@server150 ck-backup]# echo stat |nc server100 9181
ClickHouse Keeper version: v24.1.1.2048-testing-5a024dfc0936e062770d0cfaad0805b57c1fba17
Clients:
 172.16.11.150:46270(recved=0,sent=0)

Latency min/avg/max: 0/0/0
Received: 0
Sent: 0
Connections: 0
Outstanding: 0
Zxid: 0x1d39fe3d
Mode: follower
Node count: 41861

[root@server150 ck-backup]# echo stat |nc server150 9181
ClickHouse Keeper version: v24.1.1.2048-testing-5a024dfc0936e062770d0cfaad0805b57c1fba17
Clients:
 172.16.11.100:53300(recved=1622707,sent=1703346)
 172.16.11.150:33766(recved=0,sent=0)
 172.16.11.150:60882(recved=1381105,sent=1465275)

Latency min/avg/max: 0/10/1112
Received: 3017782
Sent: 3182785
Connections: 2
Outstanding: 0
Zxid: 0x1d3a0556
Mode: leader
Node count: 42698

**Comment by den-crane** [comment]
>v24.1.1.2048-testing

This is basically alfa version. You need to upgrade, both keeper and clickhouse.
Use 24.8.14.39

**Comment by wangdefa7** [comment]
> This is basically alfa version. You need to upgrade, both keeper and clickhouse. Use 25.4

I have upgraded to 25.4.4.25.
This deployment still involves two machines, using one keeper and two nodes (one shard and two replicas).
Two mistakes occurred

The first error was reported. After I modified the memory limit and restarted the database service, it hasn't occurred again so far. Error content：


`2025.05.20 12:40:06.197849 [ 112196 ] {bc7a8ff2-c76d-49e7-b22d-ea799dec23f7} <Error> executeQuery: Code: 252. DB::Exception: Too many parts (3006 with average size of 972.00 B) in table 'iot.ts_kv_latest_cluster (85d25d47-c4e1-4fbd-a9f3-e1ae0a0bd655)'. Merges are processing significantly slower than inserts. (TOO_MANY_PARTS) (version 25.4.4.25 (official build)) (from 172.16.11.150:43700) (in query: insert into ts_kv_latest_cluster (entity_id,key,ts,bool_v,str_v,long_v,dbl_v,json_v) FORMAT RowBinary ), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000f2c34db
1. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x0000000009c76bec
2. DB::Exception::Exception<unsigned long&, ReadableSize, String>(int, FormatStringHelperImpl<std::type_identity<unsigned long&>::type, std::type_identity<ReadableSize>::type, std::type_identity<String>::type>, unsigned long&, ReadableSize&&, String&&) @ 0x000000001426e6bc
3. DB::MergeTreeData::delayInsertOrThrowIfNeeded(Poco::Event*, std::shared_ptr<DB::Context const> const&, bool) const @ 0x000000001426ddf1
4. DB::runStep(std::function<void ()>, DB::ThreadStatus*, std::atomic<unsigned long>*) @ 0x0000000014c33abf
5. DB::ExceptionKeepingTransform::work() @ 0x0000000014c33270
6. DB::ExecutionThreadContext::executeTask() @ 0x00000000149b2516
7. DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x00000000149a5f23
8. DB::PipelineExecutor::execute(unsigned long, bool) @ 0x00000000149a4a25
9. DB::CompletedPipelineExecutor::execute() @ 0x00000000149a326f
10. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::shared_ptr<DB::Context>, std::function<void (DB::QueryResultDetails const&)>, DB::QueryFlags, std::optional<DB::FormatSettings> const&, std::function<void (DB::IOutputFormat&, String const&, std::shared_ptr<DB::Context const> const&, std::optional<DB::FormatSettings> const&)>) @ 0x000000001359fd14
11. DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::optional<DB::CurrentThread::QueryScope>&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) @ 0x0000000014866481
12. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) @ 0x000000001486a9e9
13. DB::HTTPServerConnection::run() @ 0x0000000014920baa
14. Poco::Net::TCPServerConnection::start() @ 0x000000001801bdc7
15. Poco::Net::TCPServerDispatcher::run() @ 0x000000001801c219
16. Poco::PooledThread::run() @ 0x0000000017fe753b
17. Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000017fe5a1d
`




The second error: The previous error report appeared again:

`2025.05.20 14:45:43.610297 [ 118858 ] {5b079b52-a8bf-45b1-baff-85699e1c783e} <Error> executeQuery: Code: 999. Coordination::Exception: Can't get data for node '/clickhouse/table/1/ts_kv_cluster/blocks/202505_3917364917561433794_11919867817974862222': node doesn't exist. (KEEPER_EXCEPTION) (version 25.4.4.25 (official build)) (from 172.16.11.150:50758) (in query: insert into ts_kv_cluster (entity_id,key,ts,bool_v,str_v,long_v,dbl_v,json_v) FORMAT RowBinary ), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000f2c34db
1. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x0000000009c76bec
2. DB::Exception::Exception<String const&>(int, FormatStringHelperImpl<std::type_identity<String const&>::type>, String const&) @ 0x000000000a54a70b
3. Coordination::Exception::Exception<String const&>(Coordination::Error, FormatStringHelperImpl<std::type_identity<String const&>::type>, String const&) @ 0x00000000151dabea
4. DB::ReplicatedMergeTreeSinkImpl<false>::commitPart(std::shared_ptr<DB::ZooKeeperWithFaultInjection> const&, std::shared_ptr<DB::IMergeTreeDataPart>&, String const&, unsigned long) @ 0x0000000014588a03
5. DB::ReplicatedMergeTreeSinkImpl<false>::finishDelayedChunk(std::shared_ptr<DB::ZooKeeperWithFaultInjection> const&) @ 0x0000000014585a5c
6. DB::ReplicatedMergeTreeSinkImpl<false>::onFinish() @ 0x0000000014586522
7. DB::runStep(std::function<void ()>, DB::ThreadStatus*, std::atomic<unsigned long>*) @ 0x0000000014c33abf
8. DB::ExceptionKeepingTransform::work() @ 0x0000000014c3350b
9. DB::ExecutionThreadContext::executeTask() @ 0x00000000149b2516
10. DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x00000000149a5f23
11. DB::PipelineExecutor::execute(unsigned long, bool) @ 0x00000000149a4a25
12. DB::CompletedPipelineExecutor::execute() @ 0x00000000149a326f
13. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::shared_ptr<DB::Context>, std::function<void (DB::QueryResultDetails const&)>, DB::QueryFlags, std::optional<DB::FormatSettings> const&, std::function<void (DB::IOutputFormat&, String const&, std::shared_ptr<DB::Context const> const&, std::optional<DB::FormatSettings> const&)>) @ 0x000000001359fd14
14. DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::optional<DB::CurrentThread::QueryScope>&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) @ 0x0000000014866481
15. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) @ 0x000000001486a9e9
16. DB::HTTPServerConnection::run() @ 0x0000000014920baa
17. Poco::Net::TCPServerConnection::start() @ 0x000000001801bdc7
18. Poco::Net::TCPServerDispatcher::run() @ 0x000000001801c219
19. Poco::PooledThread::run() @ 0x0000000017fe753b
20. Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000017fe5a1d
21. start_thread @ 0x0000000000007ea5
22. __clone @ 0x00000000000feb0d

2025.05.20 14:45:43.611365 [ 118858 ] {5b079b52-a8bf-45b1-baff-85699e1c783e} <Error> DynamicQueryHandler: Code: 999. Coordination::Exception: Can't get data for node '/clickhouse/table/1/ts_kv_cluster/blocks/202505_3917364917561433794_11919867817974862222': node doesn't exist. (KEEPER_EXCEPTION), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000f2c34db
1. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x0000000009c76bec
2. DB::Exception::Exception<String const&>(int, FormatStringHelperImpl<std::type_identity<String const&>::type>, String const&) @ 0x000000000a54a70b
3. Coordination::Exception::Exception<String const&>(Coordination::Error, FormatStringHelperImpl<std::type_identity<String const&>::type>, String const&) @ 0x00000000151dabea
4. DB::ReplicatedMergeTreeSinkImpl<false>::commitPart(std::shared_ptr<DB::ZooKeeperWithFaultInjection> const&, std::shared_ptr<DB::IMergeTreeDataPart>&, String const&, unsigned long) @ 0x0000000014588a03
5. DB::ReplicatedMergeTreeSinkImpl<false>::finishDelayedChunk(std::shared_ptr<DB::ZooKeeperWithFaultInjection> const&) @ 0x0000000014585a5c
6. DB::ReplicatedMergeTreeSinkImpl<false>::onFinish() @ 0x0000000014586522
7. DB::runStep(std::function<void ()>, DB::ThreadStatus*, std::atomic<unsigned long>*) @ 0x0000000014c33abf
8. DB::ExceptionKeepingTransform::work() @ 0x0000000014c3350b
9. DB::ExecutionThreadContext::executeTask() @ 0x00000000149b2516
10. DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x00000000149a5f23
11. DB::PipelineExecutor::execute(unsigned long, bool) @ 0x00000000149a4a25
12. DB::CompletedPipelineExecutor::execute() @ 0x00000000149a326f
13. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::shared_ptr<DB::Context>, std::function<void (DB::QueryResultDetails const&)>, DB::QueryFlags, std::optional<DB::FormatSettings> const&, std::function<void (DB::IOutputFormat&, String const&, std::shared_ptr<DB::Context const> const&, std::optional<DB::FormatSettings> const&)>) @ 0x000000001359fd14
14. DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::optional<DB::CurrentThread::QueryScope>&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) @ 0x0000000014866481
15. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) @ 0x000000001486a9e9
16. DB::HTTPServerConnection::run() @ 0x0000000014920baa
17. Poco::Net::TCPServerConnection::start() @ 0x000000001801bdc7
18. Poco::Net::TCPServerDispatcher::run() @ 0x000000001801c219
19. Poco::PooledThread::run() @ 0x0000000017fe753b
20. Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000017fe5a1d
21. start_thread @ 0x0000000000007ea5
22. __clone @ 0x00000000000feb0d
 (version 25.4.4.25 (official build))
`

**Comment by wangdefa7** [comment]
@den-crane   Do you have any suggestions
