### ISSUE TITLE
Pressing Ctrl+C twice should terminate `clickhouse-benchmark` immediately.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#32586]
**Describe the issue**
```
Queries executed: 0.


Queries executed: 0.

^CStopping launch of queries. SIGINT received.
^C^C^C^C^C^C^C^C^C^C^C
```

**Comment by bharatnc** [comment]
Not sure if Ctrl + C `twice` is a strict requirement. I have a PR that handles the interrupt now though it terminates on the first occurrence of the interrupt (Ctrl + C / SIGINT) itself.

**Comment by alexey-milovidov** [comment]
On the first Ctrl+C it should wait for the next query to finish, display the statistics and exit.
If you press Ctrl+C twice, it should exit immediately without waiting.
