### ISSUE TITLE
Frightening log message from NuRaft

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#32593]
`2021.12.12 04:24:12.020896 [ 491 ] {} <Information> RaftInstance: parameters: timeout 0 - 0, heartbeat 0, leadership expiry 0, max batch 100, backoff 50, snapshot distance 10000, log sync stop gap 99999, reserved logs -1530494976, client timeout 
10000, auto forwarding ON, API call type ASYNC, custom commit quorum size 0, custom election quorum size 0, snapshot receiver INCLUDED, leadership transfer wait time 0, grace period of lagging state machine 0, snapshot IO: BLOCKING`

Why `reserved logs -1530494976` (negative number)?
`timeout 0 - 0` - not obvious what does it mean.
`snapshot receiver INCLUDED` - it is screaming for what?

**Comment by alesapin** [comment]
Just incorrect numbers print type in NuRaft.

**Comment by alesapin** [comment]
Slightly better, but still cannot reproduce negative reserved logs https://github.com/ClickHouse-Extras/NuRaft/pull/30/files

**Comment by alexey-milovidov** [comment]
I can send you the logs from my machine :)

**Comment by alexey-milovidov** [comment]
https://drive.google.com/file/d/1GLfdUx3IKAvbeQSBMM0AZ6eX4rcj-_2h/view?usp=sharing
