### ISSUE TITLE
A problem running Clickhouse container through docker

### ISSUE THREAD

**Issue by quarrazzella** [ClickHouse/ClickHouse#3260]
Hey there!

Here's the issue. I'm trying to start a previously fine-working container 

```
docker ps -a

CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS                      PORTS               NAMES
4a0c75fda103        yandex/appmetrica-logsapi-loader   "python ./run.py"        3 months ago        Exited (255) 47 hours ago                       appmetrica-logsapi-loader
0d00133b517f        yandex/clickhouse-server           "/bin/sh -c 'exec /u…"   3 months ago        Exited (70) 2 minutes ago                       clickhouse
```

... and everything seems to work fine, but...

```
docker start clickhouse
clickhouse
docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

as you can see the container is not actually running. Here's what I get after launching docker ps logs

```
<Error> Application: DB::Exception: Cannot create table from metadata file /var/lib/clickhouse/metadata/mobile//events_773292_20180926.sql, error: DB::Exception: Attempt to read after eof, stack trace:
0. /usr/bin/clickhouse-server(StackTrace::StackTrace()+0x16) [0x3419e66]
1. /usr/bin/clickhouse-server(DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)+0x1f) [0x14f2a9f]
2. /usr/bin/clickhouse-server(DB::throwReadAfterEOF()+0x47) [0x14f2b07]
```
Please mind that's not the full error text. Any help appreciated greatly. Thanks!

**Comment by filimonov** [comment]
Can you check that /var/lib/clickhouse/metadata/mobile//events_773292_20180926.sql is accessible in docker, and contain proper ATTACH TABLE statement?

**Comment by quarrazzella** [comment]
> Can you check if /var/lib/clickhouse/metadata/mobile//events_773292_20180926.sql is accessible in docker, and contain proper ATTACH TABLE statement?

Thanks for the reply. I wish I knew how to do that? Any direct instructions?

**Comment by alexey-milovidov** [comment]
Run `docker exec -it your-container-name /bin/bash`.
Now you're inside your container and can explore it.

The issue is most likely related to the volume or filesystem configuration of your container.
