### ISSUE TITLE
DistributedSettings support MODIFY SETTING

### ISSUE THREAD

**Issue by zhongyuankai** [ClickHouse/ClickHouse#32608]
I don't quite understand why the modified function is not added to the `DistributedSettings`，like `ALTER TABLE ... MODIFY SETTING`.

**Comment by azat** [comment]
Distributed table engine does not support ALTER MODIFY SETTING because it is not easy to apply them on fly, and so ALTER does not make a lot of sense, i.e. simply re-create the table is a good alternative here (however you cannot atomically FLUSH and DROP)

**Comment by zhongyuankai** [comment]
Thank you for your answer, yes, it is not effective for Directory monitor settings, but I don't understand why `StorageDistributedDirectoryMonitor` does not directly use the value of `DistributedSettings`, but saves it in a member variable, such as `monitor_batch_inserts`. [DirectoryMonitor](https://github.com/ClickHouse/ClickHouse/blob/53e45c34e3c956922a3a897040fa09e21ef57fa9/src/Storages/Distributed/DirectoryMonitor.cpp#L354)

**Comment by zhongyuankai** [comment]
I think re-create the table is effective, however, for this table, continuous query and write, and `DirectoryMonitor` still accumulates files that have not been sent, and there is still a certain risk.
