### ISSUE TITLE
Use of datetime fuction required when using datetime function in primary key for SummingMergeTree

### ISSUE THREAD

**Issue by simPod** [ClickHouse/ClickHouse#3261]
```sql
CREATE TABLE IF NOT EXISTS test
(
    created_at DateTime,
    value      UInt64
)
    ENGINE = SummingMergeTree((value))
        PARTITION BY toDate(created_at)
        ORDER BY (toStartOfFiveMinute(created_at));

INSERT INTO test
VALUES (now(), 1);

SELECT *
FROM test
WHERE created_at BETWEEN '2018-09-01 00:00:00' AND now()
```

Throws 
>  DB::Exception: Illegal type String of argument of function toStartOfFiveMinute.

This works 
```sql
SELECT *
FROM test
WHERE created_at BETWEEN toDateTime('2018-09-01 00:00:00') AND now()
```
but for standard queries is not requied to convert datetime string to datetime.

**Comment by filimonov** [comment]
What is an advantage of using such type of PK ```ORDER BY (toStartOfFiveMinute(created_at))``` instead of ```ORDER BY created_at```.

Or it's just a synthetic sample, and it was complex key in real table?

**Comment by simPod** [comment]
@filimonov ugh, 1y ago, no idea... :D not even using merge tree now. I'd love to elaborate but that's all we have. Can close if invalid.

**Comment by alexey-milovidov** [comment]
It's valid but minor issue.

**Comment by UnamedRus** [comment]
It's actually fixed with https://github.com/ClickHouse/ClickHouse/pull/16253

```
SELECT *
FROM test2
WHERE (created_at >= '2018-09-01 00:00:00') AND (created_at <= now())

Query id: a3b50a70-d305-4a59-a011-71964ab33d82

┌──────────created_at─┬─value─┐
│ 2020-12-26 05:51:11 │     1 │
└─────────────────────┴───────┘

1 rows in set. Elapsed: 0.002 sec.
```
