### ISSUE TITLE
Wrong query result in arm

### ISSUE THREAD

**Issue by leet123** [ClickHouse/ClickHouse#32638]
Wrong query result in arm

![068A55F7-DBE5-40a6-AB4D-8E9EE9434C26](https://user-images.githubusercontent.com/32086146/145747719-ff2767a9-3cc8-44cf-9f9f-cc57401f2f4e.png)
![Snipaste_2021-12-10_18-32-18](https://user-images.githubusercontent.com/32086146/145747725-9e124535-a62c-4ecb-af7b-17665179b5c5.png)
![Snipaste_2021-12-10_18-06-35](https://user-images.githubusercontent.com/32086146/145747727-875000e9-ecd6-442c-9730-1afbfc543c14.png)

select * from table1 where f1='aaa' : return error list
select count(*) from table1 where f2='bbb':  success;

**Comment by leet123** [comment]
I have solved the problem, 
create table must with 'patition by fieldxx'
![72C83A7C-50A9-46bd-8FFD-F800F87143EB](https://user-images.githubusercontent.com/32086146/145908405-c11e1d8c-f403-489a-9f38-221893bdce6d.png)
![F9362FF2-F215-4d71-B797-011A3CD983D4](https://user-images.githubusercontent.com/32086146/145908406-835038eb-13d9-4698-a2fd-7ee730021da9.png)
![72BC05FD-4DD8-45dd-9399-E7368DBBD052](https://user-images.githubusercontent.com/32086146/145908408-edfb1ab1-f838-4d40-85b2-bdafc80c4bca.png)

**Comment by leet123** [comment]
I have solved the problem,
create table must with 'patition by fieldxx'
![72C83A7C-50A9-46bd-8FFD-F800F87143EB](https://user-images.githubusercontent.com/32086146/145908983-3f218ddd-3373-4fda-861d-26240a270b46.png)
![72BC05FD-4DD8-45dd-9399-E7368DBBD052](https://user-images.githubusercontent.com/32086146/145908986-59148897-0010-4c78-8755-03156ce0ba8a.png)
![F9362FF2-F215-4d71-B797-011A3CD983D4](https://user-images.githubusercontent.com/32086146/145908988-19ee52e3-0014-4c5c-8365-1a920fdd6cac.png)

**Comment by leet123** [comment]
I have solved the problem,
create table must with 'patition by fieldxx'
![F9362FF2-F215-4d71-B797-011A3CD983D4](https://user-images.githubusercontent.com/32086146/145909356-a5bb6a5c-ceca-46fc-8ef0-9d9137c19dfb.png)
![72BC05FD-4DD8-45dd-9399-E7368DBBD052](https://user-images.githubusercontent.com/32086146/145909371-9e349b30-ee58-46a2-a8b8-7b6b4e2d7a69.png)
![72C83A7C-50A9-46bd-8FFD-F800F87143EB](https://user-images.githubusercontent.com/32086146/145909381-b56d31ae-e043-449d-9423-9d38427b88ac.png)

**Comment by alexey-milovidov** [comment]
Logical error should not happen. This is a bug.

**Comment by leet123** [comment]
> Logical error should not happen. This is a bug.

Thank you very much for your reply.
How long will this bug be fixed and online?
Is it possible to use "patition by" to deal with before repairing, our project has just launched

**Comment by alexey-milovidov** [comment]
We don't have our CI infrastructure for ARM, it means that ARM builds are not production ready.
@Felixoid is working on adding the CI infrastructure, and only after that we will be able to work on the issues.

**Comment by leet123** [comment]
> We don't have our CI infrastructure for ARM, it means that ARM builds are not production ready. @Felixoid is working on adding the CI infrastructure, and only after that we will be able to work on the issues.

I used qume to simulate the arm version of centOs7.6 successfully on Windows (32G memory), and I can also simulate this bug of clickhouse. If necessary, I can provide the virtual system file, and only need to install qume on windows to start centOs7. 6 arm

**Comment by den-crane** [comment]
Check with 21.8.12.29.altinitydev.arm https://builds.dev.altinity.cloud/apt-repo/pool/main/

**Comment by Felixoid** [comment]
I've tried the following test, and can't reproduce it so far

```
CREATE TABLE NewTable
(
    `abc` String
)
ENGINE = MergeTree
ORDER BY abc
SETTINGS index_granularity = 8192;

INSERT INTO NewTable SELECT concat(toString(number), pp)
FROM system.numbers
LIMIT 100000000;

INSERT INTO NewTable SELECT concat(toString(number), 'pp')
FROM system.numbers
LIMIT 10000000000, 100000000;

SELECT *
FROM NewTable
WHERE abc = '3306022021110110002pp';

SELECT *
FROM NewTable
WHERE abc = '100000pp';

SELECT *
FROM NewTable
WHERE abc = '10000000020pp';

SELECT *
FROM NewTable
WHERE abc = '10000000000pp';

SELECT *
FROM NewTable
WHERE abc = '1000000000pp';
```

I used the following packages:

```
wget https://s3.amazonaws.com/clickhouse-builds/22.2/dfd8d4067de54c4b0850718549ccc187050c45eb/package_aarch64/clickhouse-client_22.2.1.2721_all.deb https://s3.amazonaws.com/clickhouse-builds/22.2/dfd8d4067de54c4b0850718549ccc187050c45eb/package_aarch64/clickhouse-common-static_22.2.1.2721_arm64.deb https://s3.amazonaws.com/clickhouse-builds/22.2/dfd8d4067de54c4b0850718549ccc187050c45eb/package_aarch64/clickhouse-server_22.2.1.2721_all.deb
```

Can you check it and, maybe, provide a reproducing case?

**Comment by Felixoid** [comment]
notify @leet123

**Comment by leet123** [comment]
> I've tried the following test, and can't reproduce it so far
> 
> ```
> CREATE TABLE NewTable
> (
>     `abc` String
> )
> ENGINE = MergeTree
> ORDER BY abc
> SETTINGS index_granularity = 8192;
> 
> INSERT INTO NewTable SELECT concat(toString(number), 'pp')
> FROM system.numbers
> LIMIT 100000000;
> 
> INSERT INTO NewTable SELECT concat(toString(number), 'pp')
> FROM system.numbers
> LIMIT 10000000000, 100000000;
> 
> SELECT *
> FROM NewTable
> WHERE abc = '3306022021110110002pp';
> 
> SELECT *
> FROM NewTable
> WHERE abc = '100000pp';
> 
> SELECT *
> FROM NewTable
> WHERE abc = '10000000020pp';
> 
> SELECT *
> FROM NewTable
> WHERE abc = '10000000000pp';
> 
> SELECT *
> FROM NewTable
> WHERE abc = '1000000000pp';
> ```
> 
> I used the following packages:
> 
> ```
> wget https://s3.amazonaws.com/clickhouse-builds/22.2/dfd8d4067de54c4b0850718549ccc187050c45eb/package_aarch64/clickhouse-client_22.2.1.2721_all.deb https://s3.amazonaws.com/clickhouse-builds/22.2/dfd8d4067de54c4b0850718549ccc187050c45eb/package_aarch64/clickhouse-common-static_22.2.1.2721_arm64.deb https://s3.amazonaws.com/clickhouse-builds/22.2/dfd8d4067de54c4b0850718549ccc187050c45eb/package_aarch64/clickhouse-server_22.2.1.2721_all.deb
> ```
> 
> Can you check it and, maybe, provide a reproducing case?

on centos7.6-arm
链接：https://pan.baidu.com/s/18w7qHM7U-B_dobh1Vfwwzg 
提取码：0ja5 
--来自百度网盘超级会员的分享

**Comment by Felixoid** [comment]
Sorry, it doesn't work with google translate and I have no idea what's going on there. By naive clicking on something similar to the download icon it suggests me rpm and deb packages, but I'd kindly reject installing 3rd party binaries.

Is it a clickhouse binary that you use and it's broken? What would be the minimal reproducing data then?

**Comment by leet123** [comment]
Compiled (binary) version of ARM from official download, downloaded in October

**Comment by alexey-milovidov** [comment]
October was so long ago.
Install the latest version:

```
curl https://clickhouse.com/ | sh
```
