### ISSUE TITLE
Error when using quantileDeterministicMerge

### ISSUE THREAD

**Issue by nicolasblaye** [ClickHouse/ClickHouse#32648]
Hello everyone,

When using quantileDeterministicMerge or quantileDeterministicMergeState functions, I get this error message:

`quantileDeterministicMerge(0.25)((Ecpm25thQuantileBuffer))`
> DB::Exception: Aggregate function quantileDeterministic requires two arguments.

`quantileDeterministicMerge(0.25)((Ecpm25thQuantileBuffer, 606))`
> DB::Exception: Illegal type Tuple(AggregateFunction(quantile(0.25), Decimal(18, 9)), UInt16) of argument for aggregate function with Merge suffix must be AggregateFunction(...).

I have the same behavior when I want to use quantileDeterministicMergeState.

We are using version 21.8.10.19, I tried this using the clickhouse-client.
Ecpm25thQuantileBuffer is an `AggregateFunction(quantile(0.25), Decimal(18, 9))`

To recreate:
`CREATE TABLE quantileTest(a UInt32) ENGINE MergeTree PRIMARY KEY a`
`INSERT INTO quantileTest VALUES (1), (2), (3), (4)`
`SELECT quantileDeterministicMergeState(0.25)(a, 606) FROM quantileTest`
`SELECT quantileDeterministicMergeState(0.25)(a) FROM quantileTest`

**Comment by vdimir** [comment]
https://github.com/ClickHouse/ClickHouse/issues/32107

**Comment by nicolasblaye** [comment]
Are you sure the issues are linked?

**Comment by nicolasblaye** [comment]
Ok my bad, I didn't explain well and my example was bad. Ecpm25thQuantileBuffer was a quantile state but not a deterministic one so I was wrong.

The thing is, when I try to do the correct query I have another issue.

`SELECT quantileDeterministicMerge(0.25)(Ecpm25thQuantileBuffer) AS Ecpm25thQuantile
FROM
(
    SELECT quantileDeterministicMergeState(0.25)(Ecpm25thQuantile) AS Ecpm25thQuantileBuffer
    FROM
    (
        SELECT quantileDeterministicStateIf(0.25)(ecpm, toUInt32(606), has_pixel = 1) AS Ecpm25thQuantile
        FROM table
    )
)`
> Code: 43. DB::Exception: Received from chpre211f:9000. DB::Exception: Illegal type Decimal(18, 9) of argument for aggregate function quantileDeterministic.

I don't have this issue with non deterministic quantiles
`SELECT quantileMerge(0.25)(Ecpm25thQuantileBuffer) AS Ecpm25thQuantile
FROM
(
    SELECT quantileMergeState(0.25)(Ecpm25thQuantile) AS Ecpm25thQuantileBuffer
    FROM
    (
        SELECT quantileStateIf(0.25)(ecpm, has_pixel = 1) AS Ecpm25thQuantile
        FROM demand.D_SBC_RtbSampledLogTables
        WHERE toStartOfDay(date) = toDateTime('2021-10-07T00:00:00', 'UTC')
    )
)`

I am missing something on deterministic quantiles?
In the doc I read
>Expression over the column values resulting in numeric data types, Date or DateTime.

**Comment by den-crane** [comment]
@nicolasblaye it did not help. Your example is not reproducible. And your goal is unclear.

What is has_pixel ? What is table ?

**Comment by nicolasblaye** [comment]
sorry, I didn't want to enter into specifics in our use case but I realize that I should explain some stuff. has_pixel is just something specific to our business, it's not really relevant but it's a boolean (UInt8). For the table, here is a better example of our setup.

```sql
CREATE TABLE raw_table(id UInt64, publisher_id UInt32, ecpm Decimal(18, 9), has_pixel UInt8) ENGINE = MergeTree PRIMARY Key (id, publisher_id)

CREATE TABLE quantileDeterministicTest (
    PublisherId UInt32,
    Ecpm25thQuantile AggregateFunction(quantile(0.25), Decimal(18, 9)) -- should it be quantileDeterministic? How to set up the determinator?
) ENGINE MergeTree PRIMARY KEY PublisherId

CREATE MATERIALIZED VIEW quantileDeterministicTestView TO quantileDeterministicTest AS
SELECT publisher_id, quantileDeterministicStateIf(0.25)(ecpm, publisher_id, has_pixel=1)
FROM raw_table

INSERT INTO raw_table VALUES 
(1, 606, 0.0001, 1),
(2,606, 0.0002, 1),
(3,606, 0.0003, 1),
(4,606, 0.0004, 1),
(5,606, 0.0005, 1),
(6,606, 0.0006, 1),
(7,606, 0.0007, 1),
(8,606, 0.0008, 1),
(9,606, 0.0009, 1),
(10,606, 0.0010, 1),
(11,606, 0.0000, 0),
(12,606, 0.0000, 0)
```

We have a raw table where we insert incoming logs. Then we have a MV that create a quantile state and insert into a table. Then we can query this table on multiple level, thus the combination of mergestate and merge functions.

However, when I want to create this example I have two issues:

- how to specify the type of Ecpm25thQuantile in the quantileDeterministic table?
- I can't create the materialized view, there is an error
> DB::Exception: Illegal type Decimal(18, 9) of argument for aggregate function quantileDeterministic.

**Comment by KochetovNicolai** [comment]
It looks like `quantileDeterministic` does not support decimals. You can cast to Float64 or use other quantile function (`quantile` or `quantileExact*` should work).
The correct type should look like `AggregateFunction(quantileDeterministic(0.25), Float64, UInt32)`

**Comment by nicolasblaye** [comment]
I ended up using quantileExact instead. Thank you for your answer @KochetovNicolai
