### ISSUE TITLE
Fail to drop index 

### ISSUE THREAD

**Issue by winter7** [ClickHouse/ClickHouse#32646]
I succeeded to add skipping index for a table like `ALTER TABLE ttt ADD INDEX aaaSet(field_a) TYPE set(20) GRANULARITY 1
`, 
but when I tried to drop index by `ALTER TABLE ttt DROP INDEX aaaSet`, I got exceptions:
```
<Error> executeQuery: Code: 999, e.displayText() = Coordination::Exception: Connection loss
```
I checked logs and suddenly all my ReplicatedMergeTree tables threw Warnings like
```
<Warning> database_name.table_name (ReplicatedMergeTreeRestartingThread): ZooKeeper session has expired. Switching to a new session.
```
and I got tons of Errors like
```
<Error> zkutil::EphemeralNodeHolder::~EphemeralNodeHolder(): Code: 999, e.displayText() = Coordination::Exception: Session expired (Session expired)
```

When I tried to materialize index by `ALTER TABLE ttt MATERIALIZE INDEX aaaSet`, I got same exceptions like `drop` sql.

Current state is, I can see the index by showing create table query but I can't drop that index.

**My question is, do you have any clue or idea about what might cause dropping index leads to Zookeeper session expire and connection loss exception? 
And do you have any method to force the dropping index operation?**

**Comment by den-crane** [comment]
Clickhouse version?

**Comment by winter7** [comment]
It happens in 20.12.8.5. But I can't reproduce it in small data set.
I'm wondering if there is anything I can try to force dropping index.

**Comment by winter7** [comment]
Hi @den-crane , I upgrade my server to 21.11.9.1 and still cannot drop this index.
Do you have any idea that I could forcibly drop an index?

**Comment by den-crane** [comment]
@winter7 can you share `select count() from system.parts where database = 'db' and table = 'ttt' and active`

Check ZK logs, for the error about transaction length ( https://github.com/ClickHouse/ClickHouse/issues/11933#issuecomment-654286261 )

**Comment by winter7** [comment]
Hi @den-crane , my part count was like:
```
SELECT
    count() AS part_cnt,
    countDistinct(partition) AS partition_cnt,
    formatReadableSize(sum(bytes)) AS size
FROM system.parts
WHERE active AND (table = 'ttt')

┌─part_cnt─┬─partition_cnt─┬─size───────┐
│     2035 │          1628 │ 773.84 GiB │
└──────────┴───────────────┴────────────┘
```
And at the same time I got Zookeeper logs:
```
2022-01-06 08:12:50,458 [myid:1] - WARN  [NIOWorkerThread-2:NIOServerCnxn@370] - Exception causing close of session 0x10000629b500045: Len error 2566840
```
I believe I met same issue with #11933 .
Thanks so much for the support @den-crane ! I will try to reproduce and consider to increase `-Djute.maxbuffer`.

And a few more question, 
- Do you know what are the disadvantages if I set `-Djute.maxbuffer` as an extraordinary large number like 50,000,000?
- I've set `-Dzookeeper.snapCount=3000000 -Dzookeeper.preAllocSize=131072 -Dzookeeper.forceSync=no` to improve Zookeeper outstanding requests and it worked. But if znodes under `/block_numbers` grow infinitely, I think I will suffer this znode issue again and manual deletion may not be a convenient routine. Could you guys consider about the feature that was proposed in #11779 ?

**Comment by winter7** [comment]
> Do you know what are the disadvantages if I set -Djute.maxbuffer as an extraordinary large number like 50,000,000?

I get it. Say `jute.maxbuffer` specifies the maximum size of the data that can be stored in a znode.
But I was wondering which exact znode was affected during the `alter` operation that produced "Connection loss"? I think it should not be `/path-to-table/replicas/{replica}/parts` right? Since it keeps growing all the time.

**Comment by den-crane** [comment]
>/block_numbers grow infinitely,

It's not related. block_numbers does not participate in mutations.
During `alter table` CH creates a mutation, and to solve mutations CH creates a transaction in ZK with names of all parts of the table. Parts name length can be different for different tables. In average with default Djute.maxbuffer mutations start to fail for tables with more 5000 parts.

This problem does not exists with Clickhouse-keeper.


>I've set -Dzookeeper.snapCount=3000000 -Dzookeeper.preAllocSize=131072 -Dzookeeper.forceSync=no

These not relevant to the issue.
