### ISSUE TITLE
Normality tests

### ISSUE THREAD

**Issue by stovmasyan89** [ClickHouse/ClickHouse#3266]
There are lots of rather simple tests (e.g. Shapiro–Wilk test) checking for normality and I think it will be useful to have some of them in ClickHouse.
e.g. Pearson's correlations does not assume normality but outliers can have great influence on correlation coefficient.

**Comment by 4ertus2** [comment]
Hello,

You could make a pull request for it. It's quite simple to add a new aggregation function in ClickHouse. Look at https://github.com/yandex/ClickHouse/blob/master/dbms/src/AggregateFunctions/AggregateFunctionAvg.cpp#L44

You need add analogs for AggregateFunctionAvg.cpp and AggregateFunctionAvg.h files for you function.

**Comment by alexey-milovidov** [comment]
We have a task for students for implementation of various statistical tests of choice.
This issue is perfectly aligned with their work.

PS. As first implementation, we have https://github.com/ClickHouse/ClickHouse/pull/9139 - but it's completely unrelated.

**Comment by alexey-milovidov** [comment]
We still don't have normality tests in ClickHouse. This task is worth doing.

**Comment by nikitamikhaylov** [comment]
Please take a look at https://clickhouse.com/docs/en/sql-reference/aggregate-functions/reference/kolmogorovsmirnovtest
This is a general purpose test which compares two distribution. Passing a normally distributed population as one of the argument will transform it to a normality test.
