### ISSUE TITLE
create & alter inconsistency with "on cluster" for ENGINE = Distributed 

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#3268]
```
<vscluster>
   <shard>
       <internal_replication>true</internal_replication>
       <replica><host>node1</host></replica>
       <replica><host>node2</host></replica>
   </shard>
</vscluster>
```

**CREATE works! And creates Distributed table on both replicas.**
CREATE TABLE  vs.t1_distrib ON CLUSTER vscluster (ts DATETIME,c1 VARCHAR) ENGINE=Distributed('vscluster','vs','t1')

**ALTER does not work!**
ALTER TABLE vs.t1_distrib ON CLUSTER vscluster ADD COLUMN c2 VARCHAR

Code: 371, e.displayText() = DB::Exception: Table t1_distrib isn't replicated, but shard #1 is replicated according to its cluster definition, e.what() = DB::Exception.

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/clickhouse/BmsOrL2AMN4/eQnjeC1CAQAJ

**Comment by c3mb0** [comment]
Is this ever going to be fixed?

**Comment by cw9** [comment]
Hi, I'm hitting this issue as well, any plan to get this fixed?

**Comment by den-crane** [comment]
BTW I always used workaround, just one more cluster with all nodes as dedicated shards.

**Comment by alexey-milovidov** [comment]
Our internal users also have faced this issue.

It should be trivial to fix: just skip the check for Distributed tables.

**Comment by nvartolomei** [comment]
Shouldn't we do the same for Null tables? Or just remove the check altogether?
