### ISSUE TITLE
discrepancy in aggregation between materialized views

### ISSUE THREAD

**Issue by rajadayalan** [ClickHouse/ClickHouse#3271]
We are ingesting around 25 billion records everyday to our clickhouse cluster. In clickhouse cluster   the data is ingested to one Source table. From the source table data all records are auto ingested to Materialized Views that are ReplicatedSummingMergeTree.  
We are noticing slight discrepancy in aggregation between the materialized views. 
Provided below the aggregation of hits column between two materialized views(local) of one node, there is discrepancy in aggregation though the same set of records were sent to both materialized views.
mv1
┌──sum(hits)─┬─request_date─┐
│ 3281592331 │   2018-09-29 │
│ 3426583818 │   2018-09-30 │
│ 3159305920 │   2018-10-01 │
│ 2547024208 │   2018-10-02 │
└────────────┴──────────────┘

mv2
┌──sum(hits)─┬─request_date─┐
│ 3281592384 │   2018-09-29 │
│ 3426583995 │   2018-09-30 │
│ 3159305938 │   2018-10-01 │
│ 2547024208 │   2018-10-02 │
└────────────┴──────────────┘

And we also notice the running aggregation for current day(during ingestion) are matching usually.

**Comment by vavrusa** [comment]
Do you see any errors in the log for the INSERT statements or materialization?

The materialization into views is not atomic and there's no rollback, so if you materialization succeeds for some views and fails for some others, you might end up double inserting to the views that succeeded on insert retry.

**Comment by rajadayalan** [comment]
dont see insert/materialization errors in clickhouse-server.err.log.

**Comment by filimonov** [comment]
That should't happen. The most wierd that you have proper data for current day.

Can you identify which MV have correct numbers and which - wrong by comparing the counts with directly counted from source data? 

Can you provide some datails like CREATE statements for source table and views?

**Comment by rajadayalan** [comment]
Please find the create table statements at  https://gist.github.com/rajadayalan/2c669797e33cd19153ef20a4568c2939. 

We are not retaining source table data for more than couple of hours. We will increase the source table data retention for couple of days. Can provide you with count comparison by tomorrow evening (after we retain enough data in the source table).

**Comment by rajadayalan** [comment]
There is difference between counts/aggregations of source table and materialized views also. Please find below the counts/aggregations. 

Counts from Source table (unreplicated)
----------------------------------------
srv002 :) select count(), sum(hits) from rta.access_logs_local where request_date='2018-10-09'

┌────count()─┬──sum(hits)─┐
│ 1624975700 │ 1624975700 │
└────────────┴────────────┘

1 rows in set. Elapsed: 1.670 sec. Processed 1.64 billion rows, 16.36 GB (979.66 million rows/s., 9.80 GB/s.)

srv012 :) select count(), sum(hits) from rta.access_logs_local where request_date='2018-10-09'

┌────count()─┬──sum(hits)─┐
│ 1453369879 │ 1453369879 │
└────────────┴────────────┘

1 rows in set. Elapsed: 1.797 sec. Processed 1.47 billion rows, 14.65 GB (815.16 million rows/s., 8.15 GB/s.)


Sum of count() from above two is 1624975700 + 1453369879 = 3078345579

Materialized View aggregations
--------------------------------

srv002 :) select count(), sum(hits) from rta_5m.access_logs_local where request_date='2018-10-09'

┌─count()─┬──sum(hits)─┐
│ 5507650 │ 3078345578 │
└─────────┴────────────┘

1 rows in set. Elapsed: 0.034 sec. Processed 6.22 million rows, 62.16 MB (184.81 million rows/s., 1.85 GB/s.)

srv002 :) select count(), sum(hits) from rta_5m.access_logs_url_local where request_date='2018-10-09'

┌───count()─┬──sum(hits)─┐
│ 300426744 │ 3078345578 │
└───────────┴────────────┘

1 rows in set. Elapsed: 0.472 sec. Processed 302.21 million rows, 3.02 GB (640.76 million rows/s., 6.41 GB/s.)

srv002 :) select count(), sum(hits) from rta_1d.access_logs_daily_local where request_date='2018-10-09'

┌─count()─┬──sum(hits)─┐
│  243723 │ 3078345577 │
└─────────┴────────────┘

1 rows in set. Elapsed: 0.013 sec. Processed 431.23 thousand rows, 4.31 MB (33.86 million rows/s., 338.56 MB/s.)

srv002 :) select count(), sum(hits) from rta_1d.access_logs_url_daily_local where request_date='2018-10-09'

┌──count()─┬──sum(hits)─┐
│ 51250402 │ 3078345577 │
└──────────┴────────────┘

1 rows in set. Elapsed: 0.089 sec. Processed 52.60 million rows, 525.96 MB (590.65 million rows/s., 5.91 GB/s.)

**Comment by rajadayalan** [comment]
can you please provide update on the issue?

**Comment by iameugenejo** [comment]
It's still happening with non replicated table in version 18.16.1. 

Any update on this?

Another table set we are seeing the same problem with has the following statement:

```
CREATE MATERIALIZED VIEW sample.log_stats_20181212 ( 
  timestamp DateTime,  
  m_type String,  
  hits UInt64
) ENGINE = SummingMergeTree() PARTITION BY toDate(timestamp) ORDER BY (
  timestamp, 
  m_type
) SETTINGS index_granularity = 8192 
AS 
SELECT toStartOfMinute(ingest_timestamp) AS timestamp, m_type, sum(hits) AS hits FROM sample.logs_local_20181212  GROUP BY toStartOfMinute(ingest_timestamp), m_type
```

running `SELECT toStartOfMinute(ingest_timestamp) AS timestamp, m_type, sum(hits) AS hits FROM sample.logs_local_20181212  where toStartOfMinute(ingest_timestamp) = '2019-02-11 00:00:00' GROUP BY toStartOfMinute(ingest_timestamp), m_type`

and compare the result with `select * from sample.log_stats_20181212 where timestamp = '2018-02-11 00:00:00'`

produces difference where the materialized view showing more records most of the time.

**Comment by den-crane** [comment]
@iameugenejo can you show the output

select timezone();

select toTypeName(timestamp) from  sample.log_stats_20181212 limit 1;

select toTypeName(ingest_timestamp) from  sample.logs_local_20181212 limit 1;

**Comment by iameugenejo** [comment]
* select timezone();
```UTC```

* select toTypeName(timestamp) from sample.log_stats_20181212 limit 1;
```DateTime```

* select toTypeName(ingest_timestamp) from sample.logs_local_20181212 limit 1;
```DateTime```

The clickhouse version is now `19.6.2.11`, and it's still showing the discrepancy with materialized view having about 25% more aggregated metrics.

**Comment by den-crane** [comment]
@iameugenejo and what is an engine of  logs_local_20181212 ?

**Comment by iameugenejo** [comment]
@den-crane It's MergeTree

**Comment by den-crane** [comment]
@iameugenejo 
Is there any difference in results of

select count() from sample.log_stats_20181212 where timestamp = '2019-02-11 00:00:00'

select count() from sample.log_stats_20181212 where identity(timestamp) = '2019-02-11 00:00:00'

**Comment by iameugenejo** [comment]
@den-crane There is no difference

**Comment by blinkov** [comment]
@rajadayalan, do you have any further questions?

**Comment by jakesyl** [comment]
Any update? We’re running into this as well

**Comment by filimonov** [comment]
> Any update? We’re running into this as well

We need a reproducable test case. Try to create minimał sample.

**Comment by den-crane** [comment]
>And we also notice the running aggregation for current day(during ingestion) are matching usually.

It could be that TZ is the reason. `substring(partition_code, 1, 10) as partition_code`

**Comment by iameugenejo** [comment]
We're not seeing this issue anymore and we're at 19.14.10.16 now.
