### ISSUE TITLE
UInt256 function & reinterpretAsUInt256 donot work as intended on insert

### ISSUE THREAD

**Issue by TheAlexCH** [ClickHouse/ClickHouse#32722]
why is this returning different values?

select 
toUInt256(0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF), -- 1329227995784915872831749466242416640
reinterpretAsUInt256(unhex('FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF')) -- 1329227995784915872903807060280344575

Additionally, 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF = 100433627766186892221372630771322662657637687111424552206335

Clickhouse does 

select 
toUInt256(0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF), -- 100433627766186892205039077159117616412281149670237736534000
reinterpretAsUInt256(unhex('FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF')) -- 1606938044258990275541962092341162602522202993782792835301135

**Comment by alexey-milovidov** [comment]
`0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF` is a floating point literal in SQL query.

```
milovidov-desktop :) SELECT 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF

SELECT 1.329227995784916e36

Query id: 0a0c4a6d-5393-4dc7-88e0-7a9edd0cad8f

┌─1.329227995784916e36─┐
│ 1.329227995784916e36 │
└──────────────────────┘
```
