### ISSUE TITLE
partition does not match max_time in system.parts.

### ISSUE THREAD

**Issue by xuyatian** [ClickHouse/ClickHouse#32723]
**Describe the unexpected behaviour**
I have a table which is partitioned by toYYYYMMDD(time). when I query from system.parts, I find the partition dose not match the max_time:
**partition: 20211018, max_time:2021-10-19 02:56:11**

**full query result:**
partition:                             **20211018**
name:                                  20211018_2639186_2651454_23
uuid:                                  00000000-0000-0000-0000-000000000000
part_type:                             Wide
active:                                1
marks:                                 732
rows:                                  5896248
bytes_on_disk:                         499082245
data_compressed_bytes:                 495308034
data_uncompressed_bytes:               2526307624
marks_bytes:                           3759552
modification_time:                     2021-10-26 08:31:50
remove_time:                           1969-12-31 19:00:00
refcount:                              1
min_date:                              1970-01-01
max_date:                              1970-01-01
min_time:                              2021-10-18 04:28:54
max_time:                              **2021-10-19 02:56:11** ----> why 2021-10-19??
partition_id:                          20211018
min_block_number:                      2639186
max_block_number:                      2651454
level:                                 23
data_version:                          2639186
primary_key_bytes_in_memory:           14640
primary_key_bytes_in_memory_allocated: 20480
is_frozen:                             0
database:                              siem
table:                                 __priv_adom3
engine:                                MergeTree
disk_name:                             default
path:                                  /drive0/private/clickhouse/store/e47/e473e5d0-3efd-4cfd-81b0-b7e0f8f3a01e/20211018_2639186_2651454_23/
hash_of_all_files:                     fe118601fffbd29e077e44c24061016b
hash_of_uncompressed_files:            7f3170d6a44d086f119f736c069bc861
uncompressed_hash_of_compressed_files: 3dc4a2272dd206e76e897ef75dc85333
delete_ttl_info_min:                   1969-12-31 19:00:00
delete_ttl_info_max:                   1969-12-31 19:00:00
move_ttl_info.expression:              []
move_ttl_info.min:                     []
move_ttl_info.max:                     []
default_compression_codec:             LZ4
recompression_ttl_info.expression:     []
recompression_ttl_info.min:            []
recompression_ttl_info.max:            []
group_by_ttl_info.expression:          []
group_by_ttl_info.min:                 []
group_by_ttl_info.max:                 []
rows_where_ttl_info.expression:        []
rows_where_ttl_info.min:               []
rows_where_ttl_info.max:               []

**How to reproduce**
* Which ClickHouse server version to use
   21.8.5
* Which interface to use, if matters
* Non-default settings, if any
  ┌─name────────────────────────────┬─value───────┐
│ max_insert_block_size           │ 10485760    │
│ max_threads                     │ 1           │
│ load_balancing                  │ random      │
│ max_memory_usage                │ 10000000000 │
│ max_partitions_per_insert_block │ 1000        │
│ allow_drop_detached             │ 1           │
└─────────────────────────────────┴─────────────┘
* `CREATE TABLE` statements for all tables involved
ATTACH TABLE __priv_adom3                                                                                             
(                                               
    `adom_oid` UInt32 CODEC(LZ4),                                                                                     
    `itime` DateTime CODEC(LZ4),                 
    `loguid` UInt64 CODEC(LZ4),                                                                                       
    `epid` UInt32 CODEC(LZ4),                                                                                         
    `euid` UInt32 CODEC(LZ4),                                                                                         
    `data_parsername` LowCardinality(String) CODEC(LZ4),                                                              
    `data_sourceid` LowCardinality(String) CODEC(LZ4), 
    `data_sourcename` LowCardinality(Nullable(String)) CODEC(LZ4), 
    `data_sourcetype` LowCardinality(String) CODEC(LZ4),                                                              
    `data_sourceversion` LowCardinality(Nullable(String)) CODEC(LZ4), 
    `data_timestamp` DateTime CODEC(DoubleDelta, LZ4),                                                                
    `app_cat` LowCardinality(Nullable(String)) CODEC(LZ4),                                                            
    `app_id` Nullable(UInt32) CODEC(LZ4),                                                                             
    `app_name` Nullable(String) CODEC(LZ4),                                                                           
    `app_proc` Nullable(String) CODEC(LZ4),                                                                           
    `app_ref` Nullable(String) CODEC(LZ4),           
    `app_service` LowCardinality(Nullable(String)) CODEC(LZ4), 
    `app_state` Nullable(String) CODEC(LZ4),    
    `app_ver` Nullable(String) CODEC(LZ4),                                                                            
    `dns_query` Nullable(String) CODEC(LZ4),                                                                          
    `dns_querytype` LowCardinality(Nullable(String)) CODEC(LZ4),                                                      
    `dns_response` Nullable(String) CODEC(LZ4),                                                                       
    `dst_domain` LowCardinality(Nullable(String)) CODEC(LZ4),                                                         
    `dst_geo` LowCardinality(Nullable(String)) CODEC(LZ4),       
    `dst_intf` LowCardinality(Nullable(String)) CODEC(LZ4),                                                           
    `dst_ip` Nullable(IPv6) CODEC(LZ4),         
    `dst_mac` LowCardinality(Nullable(String)) CODEC(LZ4),                                                            
    `dst_natip` Nullable(IPv6) CODEC(LZ4),       
    `dst_natport` Nullable(UInt16) CODEC(LZ4),                                                                        
    `dst_port` Nullable(UInt16) CODEC(LZ4),                                                                           
    `event_action` LowCardinality(Nullable(String)) CODEC(LZ4), 
    `event_id` Nullable(UInt32) CODEC(LZ4),                                                                           
    `event_message` Nullable(String) CODEC(LZ4), 
    `event_outcome` LowCardinality(Nullable(String)) CODEC(LZ4), 
    `event_policy` Nullable(String) CODEC(LZ4),                                                                       
    `event_profile` Nullable(String) CODEC(LZ4),    
    `event_ref` Nullable(String) CODEC(LZ4),                                                                          
    `event_severity` LowCardinality(Nullable(String)) CODEC(LZ4),                                                     
    `event_subtype` LowCardinality(Nullable(String)) CODEC(LZ4),                                                      
    `event_type` LowCardinality(Nullable(String)) CODEC(LZ4), 
    `file_accessetime` Nullable(DateTime) CODEC(LZ4), 
    `file_createtime` Nullable(DateTime) CODEC(LZ4), 
    `file_ext` LowCardinality(Nullable(String)) CODEC(LZ4),  
    `file_hash` Nullable(String) CODEC(LZ4), 
    `file_hashtype` LowCardinality(Nullable(String)) CODEC(LZ4), 
    `file_name` Nullable(String) CODEC(LZ4), 
    `file_path` Nullable(String) CODEC(LZ4), 
    `file_size` Nullable(String) CODEC(LZ4), 
    `host_classification` LowCardinality(Nullable(String)) CODEC(LZ4), 
    `host_hwvendor` LowCardinality(Nullable(String)) CODEC(LZ4), 
    `host_hwver` LowCardinality(Nullable(String)) CODEC(LZ4), 
    `host_ip` Nullable(IPv6) CODEC(LZ4), 
    `host_location` Nullable(String) CODEC(LZ4), 
    `host_mac` Nullable(String) CODEC(LZ4), 
    `host_name` LowCardinality(Nullable(String)) CODEC(LZ4), 
    `host_osfamily` LowCardinality(Nullable(String)) CODEC(LZ4), 
    `host_osname` LowCardinality(Nullable(String)) CODEC(LZ4), 
    `host_osver` LowCardinality(Nullable(String)) CODEC(LZ4), 
    `host_owner` Nullable(String) CODEC(LZ4), 
    `host_type` LowCardinality(Nullable(String)) CODEC(LZ4), 
    `host_uid` LowCardinality(Nullable(String)) CODEC(LZ4),  
    `http_cookie` Nullable(String) CODEC(LZ4), 
    `http_method` LowCardinality(Nullable(String)) CODEC(LZ4), 
    `http_referer` Nullable(String) CODEC(LZ4), 
    `http_url` Nullable(String) CODEC(LZ4), 
    `http_useragent` LowCardinality(Nullable(String)) CODEC(LZ4), 
    `mail_from` Nullable(String) CODEC(LZ4), 
    `mail_size` Nullable(UInt32) CODEC(LZ4), 
    `mail_subject` Nullable(String) CODEC(LZ4), 
    `mail_to` Nullable(String) CODEC(LZ4), 
    `net_direction` LowCardinality(Nullable(String)) CODEC(LZ4), 
    `net_name` LowCardinality(Nullable(String)) CODEC(LZ4),  
    `net_payloadid` Nullable(UInt32) CODEC(LZ4), 
    `net_proto` LowCardinality(Nullable(String)) CODEC(LZ4), 
    `net_rcvdpkts` Nullable(UInt64) CODEC(LZ4), 
    `net_recvbytes` Nullable(UInt64) CODEC(LZ4), 
    `net_sentbytes` Nullable(UInt64) CODEC(LZ4), 
    `net_sentpkts` Nullable(UInt64) CODEC(LZ4), 
    `net_sessionduration` Nullable(UInt32) CODEC(LZ4), 
    `net_sessionid` Nullable(String) CODEC(LZ4), 
    `net_ssid` LowCardinality(Nullable(String)) CODEC(LZ4),  
    `src_domain` LowCardinality(Nullable(String)) CODEC(LZ4), 
    `src_geo` LowCardinality(Nullable(String)) CODEC(LZ4),  
    `src_intf` LowCardinality(Nullable(String)) CODEC(LZ4),  
    `src_ip` Nullable(IPv6) CODEC(LZ4), 
    `src_mac` LowCardinality(Nullable(String)) CODEC(LZ4),  
    `src_natip` Nullable(IPv6) CODEC(LZ4), 
    `src_natport` Nullable(UInt16) CODEC(LZ4), 
    `src_port` Nullable(UInt16) CODEC(LZ4), 
    `threat_action` LowCardinality(Nullable(String)) CODEC(LZ4), 
    `threat_direction` LowCardinality(Nullable(String)) CODEC(LZ4), 
    `threat_id` LowCardinality(Nullable(String)) CODEC(LZ4), 
    `threat_name` LowCardinality(Nullable(String)) CODEC(LZ4), 
    `threat_pattern` Nullable(String) CODEC(LZ4), 
    `threat_ref` Nullable(String) CODEC(LZ4), 
    `threat_score` Nullable(UInt32) CODEC(LZ4), 
    `threat_severity` LowCardinality(Nullable(String)) CODEC(LZ4), 
    `threat_type` LowCardinality(Nullable(String)) CODEC(LZ4), 
    `user_authtype` LowCardinality(Nullable(String)) CODEC(LZ4), 
    `user_classification` LowCardinality(Nullable(String)) CODEC(LZ4),                                                                                                                                                                  
    `user_domain` LowCardinality(Nullable(String)) CODEC(LZ4),                                                                                                                                                                          
    `user_email` Nullable(String) CODEC(LZ4),                                                                       
    `user_group` LowCardinality(Nullable(String)) CODEC(LZ4),                                                                                                                                                                           
    `user_id` Nullable(String) CODEC(LZ4),                                                                          
    `user_location` LowCardinality(Nullable(String)) CODEC(LZ4),                                                                                                                                                                        
    `user_name` Nullable(String) CODEC(LZ4),                                                                        
    `user_org` LowCardinality(Nullable(String)) CODEC(LZ4),                                                                                                                                                                             
    `user_phone` Nullable(String) CODEC(LZ4),                                                                       
    `user_role` LowCardinality(Nullable(String)) CODEC(LZ4),                                                                                                                                                                            
    `user_social` Nullable(String) CODEC(LZ4)                                                                       
)                                                                                                                   
ENGINE = MergeTree()                                                                                                
PARTITION BY toYYYYMMDD(itime)                                                                                      
ORDER BY (adom_oid, itime, intHash32(itime), loguid)                                                                
SAMPLE BY intHash32(itime)                                                                                          
SETTINGS index_granularity = 8192 
* Sample data for all these tables, use [clickhouse-obfuscator]
* Queries to run that lead to unexpected result
select * from system.parts

**Expected behavior**
  the partition should match the max_time.

**Error message and/or stacktrace**

**Additional context**

**Comment by den-crane** [comment]
>max_time: 2021-10-19 02:56:11 ----> why 2021-10-19??
>partition_id: 20211018
...
>delete_ttl_info_min: 1969-12-31 19:00:00       <=========

It could be because timezone difference / displaying in JAVA applications.  What tool do you use? clickhouse-client?

**Comment by den-crane** [comment]
```
SELECT
    toDateTime('2021-01-01 00:00:00', 'Asia/Shanghai') AS x,
    toDate(x) AS y
┌───────────────────x─┬──────────y─┐
│ 2021-01-01 00:00:00 │ 2021-01-01 │
└─────────────────────┴────────────┘

JAVA APPLICATION
select toDateTime('2021-01-01 00:00:00', 'Asia/Shanghai') x, toDate(x) y
<html><head><style>table, th, td { border: 1px solid black; border-collapse: collapse; } th, td { padding: 5px; text-align: left; } table tr:nth-child(even) { background-color: #eee; } table tr:nth-child(odd) { background-color:#fff; } table th { background-color: black; color: white; }</style></head><body>

x                   |          y
------------------- | ----------
2020-12-31 12:00:00 | 2021-01-01


```

**Comment by xuyatian** [comment]
> > max_time: 2021-10-19 02:56:11 ----> why 2021-10-19??
> > partition_id: 20211018
> > ...
> > delete_ttl_info_min: 1969-12-31 19:00:00       <=========
> 
> It could be because timezone difference / displaying in JAVA applications. What tool do you use? clickhouse-client?

I used clickhouse-client.

**Comment by den-crane** [comment]
Can you share `select timezone()` ?

**Comment by xuyatian** [comment]
US/Eastern
