### ISSUE TITLE
show tables didnt work in arm

### ISSUE THREAD

**Issue by azjiajiajia** [ClickHouse/ClickHouse#32741]
show tables didnt work in arm

i add more than 60 tables in database
then some tables disappear,but i can still find them by using select * from xxxx

**Comment by den-crane** [comment]
Check with 21.8.12.29.altinitydev.arm https://builds.dev.altinity.cloud/apt-repo/pool/main/

**Comment by Felixoid** [comment]
> show tables didnt work in arm
> 
> i add more than 60 tables in database then some tables disappear,but i can still find them by using select * from xxxx

Hi @azjiajiajia, can you, please, provide a reproduction case? Are there some particular tables engines, or just any?

I've tried binaries from packages https://s3.amazonaws.com/clickhouse-builds/32911/b0708708cdcf09011ecd9095c395aecf92cdf27b/clickhouse_build_check_(actions)/report.html ([1](https://s3.amazonaws.com/clickhouse-builds/32911/b0708708cdcf09011ecd9095c395aecf92cdf27b/package_aarch64/clickhouse-client_21.13.1.2101_all.deb) [2](https://s3.amazonaws.com/clickhouse-builds/32911/b0708708cdcf09011ecd9095c395aecf92cdf27b/package_aarch64/clickhouse-common-static_21.13.1.2101_arm64.deb) [3](https://s3.amazonaws.com/clickhouse-builds/32911/b0708708cdcf09011ecd9095c395aecf92cdf27b/package_aarch64/clickhouse-server_21.13.1.2101_all.deb)), and it's not reproduced with the following tiny script

```
clickhouse-client -nq 'DROP DATABASE IF EXISTS test_32741; CREATE DATABASE test_32741;' && \
for i in {001..120};
  do clickhouse-client -q "CREATE TABLE test_32741.test_table_$i (name String, value Float64) Engine = Log" || break
done
clickhouse-client --database test_32741 -q 'SHOW TABLES' | wc
```
