### ISSUE TITLE
async_insert - created part for every single insert seems not working 21.11.5.33

### ISSUE THREAD

**Issue by rasstroen** [ClickHouse/ClickHouse#32767]
(you don't have to strictly follow this form)

**Describe the unexpected behaviour**
A clear and concise description of what works not as it is supposed to.

**How to reproduce**
insert into ReplicatedMergeTree 10 times with enabled async:
<async_insert>1</async_insert>
<async_insert_threads>1</async_insert_threads>
<wait_for_async_insert>1</wait_for_async_insert>
<wait_for_async_insert_timeout>30</wait_for_async_insert_timeout>
<async_insert_max_data_size>1941000000</async_insert_max_data_size>
<async_insert_busy_timeout_ms>20000</async_insert_busy_timeout_ms>
<async_insert_stale_timeout_ms>3000</async_insert_stale_timeout_ms>

**Expected behavior**
1 part created

**Error message and/or stacktrace**
AsynchronousInsertQueue: Flushed 316 rows, 439391 bytes for query - 10 times in one second, even with high timeouts and 1 insert thread

**Additional context**
Http client (smi2/phpClickHouse)

**Comment by den-crane** [comment]
```sql
21.11.5.33

create table test(a Int, b String) engine=Null;
create materialized view test_async Engine=MergeTree order by ts as select now() ts, count from test;

cat test.csv
1,'x'
2,'y'
3,'z'

-- no async_insert / 100 inserts in 10 threads
seq 1 100|xargs -P 10 -n 1 -I x curl 'http://localhost:8123/?async_insert=0&query=insert+into+test+format+CSV' --data-binary @test.csv

select min(rows), max(rows) from test_async;
┌─min(rows)─┬─max(rows)─┐
│         3 │         3 │
└───────────┴───────────┘
truncate table test_async;

-- async_insert=1
seq 1 100|xargs -P 10 -n 1 -I x curl 'http://localhost:8123/?async_insert=1&query=insert+into+test+format+CSV' --data-binary @test.csv

select min(rows), max(rows) from test_async;
┌─min(rows)─┬─max(rows)─┐
│        30 │        30 │
└───────────┴───────────┘
truncate table test_async;

```

**Comment by CurtizJ** [comment]
@den-crane, please, can you explain your example?

**Comment by den-crane** [comment]
@CurtizJ my example demonstrates that async_insert is working and 10 parallel inserts are combined into a single insert into `test` table.

**Comment by den-crane** [comment]
Here one more example

```
--async_insert_busy_timeout_ms=200
for i in `seq 10`; do echo $i; sleep 1; bash -c "seq 1 100|xargs -P 100 -n 1 -I x curl 'http://localhost:8123/?&async_insert=1&query=insert+into+test+format+CSV' --data-binary @test.csv" & done
┌─min(rows)─┬─max(rows)─┬─count()─┐
│       300 │       300 │      10 │
└───────────┴───────────┴─────────┘

--async_insert_busy_timeout_ms=5000
for i in `seq 10`; do echo $i; sleep 1; bash -c "seq 1 100|xargs -P 100 -n 1 -I x curl 'http://localhost:8123/?&async_insert=1&query=insert+into+test+format+CSV' --data-binary @test.csv" & done; wait
┌─min(rows)─┬─max(rows)─┬─count()─┐
│      1500 │      1500 │       2 │
└───────────┴───────────┴─────────┘

<profiles>
<default>
        <async_insert_busy_timeout_ms>5000</async_insert_busy_timeout_ms>
</default>
</profiles>

+restart
```

So both async_insert_busy_timeout_ms and async_insert work as expected
