### ISSUE TITLE
 No hosts passed to ZooKeeper constructor. (Bad arguments). (KEEPER_EXCEPTION) (version 21.11.3.6

### ISSUE THREAD

**Issue by wwwangch** [ClickHouse/ClickHouse#32778]
I am trying to use clickhouse-keeper,Below is my configuration file
`
 <keeper_server>
		<tcp_port>2181</tcp_port>
		<server_id>1</server_id>
		<log_storage_path>/var/lib/clickhouse/coordination/log</log_storage_path>
		<snapshot_storage_path>/var/lib/clickhouse/coordination/snapshots</snapshot_storage_path>

		<coordination_settings>
			<operation_timeout_ms>10000</operation_timeout_ms>
			<session_timeout_ms>30000</session_timeout_ms>
			<raft_logs_level>trace</raft_logs_level>
		</coordination_settings>

		<raft_configuration>
			<server>
				<id>1</id>
				<hostname>clickhouse01</hostname>
				<port>9444</port>
			</server>
			<server>
				<id>2</id>
				<hostname>clickhouse02</hostname>
				<port>9444</port>
			</server>
			<server>
				<id>3</id>
				<hostname>clickhouse03</hostname>
				<port>9444</port>
			</server>
			<server>
				<id>4</id>
				<hostname>clickhouse04</hostname>
				<port>9444</port>
			</server>
			<server>
				<id>5</id>
				<hostname>clickhouse05</hostname>
				<port>9444</port>
			</server>
			<server>
				<id>6</id>
				<hostname>clickhouse06</hostname>
				<port>9444</port>
			</server>
			<server>
				<id>7</id>
				<hostname>clickhouse07</hostname>
				<port>9444</port>
			</server>
			<server>
				<id>8</id>
				<hostname>clickhouse08</hostname>
				<port>9444</port>
			</server>
		</raft_configuration>
</keeper_server>

`

I have used clickhouse-keeper, why does it look for zookeeper，Can someone find the problem with it, thank you very much

**Comment by alesapin** [comment]
Hi! ClickHouse has two parts of configuration related to coordination with `clickhouse-keeper`. First one is server side configuration of `clickhouse-keeper` itself: number of quorum nodes, listen port, snapshot compression, etc. Another part is (zoo|clickhouse)keeper client configuration: https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings/#server-settings_zookeeper. The error `No hosts passed to ZooKeeper constructor` means that you have misconfigured client part (specified no hosts)  and it's not related to the config in the issue.
