### ISSUE TITLE
About  user-defined function

### ISSUE THREAD

**Issue by angkorthomwdd** [ClickHouse/ClickHouse#32789]
Hi,
    Does the clickhouse support the complex function customization。For example some algorithms can be implemented  c++ and then registered into clickhouse only compiled to the algorithm source files 。
     Can the current clickhouse be implemented? thanks very much !

**Comment by KochetovNicolai** [comment]
Hi,
See https://clickhouse.com/docs/en/sql-reference/functions/#executable-user-defined-functions and
