### ISSUE TITLE
Incorrect status of ClickHouse Build Check

### ISSUE THREAD

**Issue by Algunenano** [ClickHouse/ClickHouse#32799]
From https://github.com/ClickHouse/ClickHouse/pull/32484

The build check says everything went fine at https://s3.amazonaws.com/clickhouse-builds/32484/b0638b04484560bedce18b455851c87c47432976/clickhouse_special_build_check_(actions)/report.html

When you access the clang-13-darwin-aarch64 build log you see [that it failed](https://s3.amazonaws.com/clickhouse-builds/32484/b0638b04484560bedce18b455851c87c47432976/binary_darwin_aarch64/build_log.log)

```
Dec 14 13:35:27 ninja: build stopped: subcommand failed.
2021-12-14 13:35:29,995 Output placed into /home/ubuntu/actions-runner/_work/_temp/build_check/binary_darwin_aarch64
```

Note that I'm not complaining about why if failed to build (my fault) but that it's reporting a success when it shouldn't.

**Comment by alesapin** [comment]
Fixing here https://github.com/ClickHouse/ClickHouse/pull/32745

**Comment by alesapin** [comment]
Fixed.
