### ISSUE TITLE
No query_log for inserts if async_insert used

### ISSUE THREAD

**Issue by rasstroen** [ClickHouse/ClickHouse#32804]
If we are enabling async_insert, query log missing all insert queries.

We are using log for monitoring, too (inserts time, inserts frequency etc), and with  async_insert query_log is empty. Maybe log can be written anyway?

**Comment by CurtizJ** [comment]
Yes, queries with `async_insert` can be written to query log. It's not done by mistake. However, it may slightly decrease performance, but since query log has buffering too, I think, it will be ok.

**Comment by orloffv** [comment]
@CurtizJ But now in query_log columns about insert data(insert_rows, insert_bytes etc.) equals 0.
Is ok? how to get truth information about insert queries?

**Comment by CurtizJ** [comment]
For async inserts you can look at the `AsyncInsertBytes` metric in `ProfileEvents` column. Accounting rows is impossible for async inserts, because parsing is done asynchronously in the background.
