### ISSUE TITLE
"Unknown setting normalize_function_names" on cross-version remote only in subquery

### ISSUE THREAD

**Issue by loki107** [ClickHouse/ClickHouse#32818]
We have unexpected behavior with using a remote function or distdb table accessing different CH versions where the newer CH version has some query settings that are unknown to the older CH version. 

New version: v21.8.11.4
Old version: 19.11.12.69

We can't afford to upgrade all servers to a newer version simultaneously because we want to thoroughly test the newer version first on servers of lower importance. 
Also, we are typically using "query server" and "data servers/clusters" and many processes access data through Distributed tables and store intermediate processing data locally on query servers to access other Distributed tables for various subsets of data from the previous queries.
So such query constructs using a subquery to remote() table described below is quite usual for us and can't be rewritten easily. 

Usually, cross-version access between different CH versions works normally if you don't change some settings that are unique to the newer version from their default values. 

But it doesn't work when using subqueries. 

Examples:

Two simple tables on two CH servers with different versions - there is no need for any table to have any rows:
```
CREATE TABLE test.table_on_v218
(

    `inserted_on` DateTime DEFAULT now(),
    `inserted_on_date` Date DEFAULT toDate(inserted_on),    
    value1 LowCardinality(String),
    value2 UInt32    
)
ENGINE = MergeTree
PARTITION BY inserted_on_date
ORDER BY (value1, value2)
SETTINGS index_granularity = 8192;
```

1. Access from v21.8 to v19.11.

```
ch-ver-v218 :) SELECT value1 FROM remote('ch-ver-v1911','test.table_on_v1911')
```

works

2. Access from v19.11 to v21.8

```
ch-ver-v1911 :) SELECT value1 FROM remote('ch-ver-v218','test.table_on_v218')
```

works

3. Access directly from v21.8 to v19.11 in a subquery (first remote is redundant but used for clarity):
```
ch-ver-v218 :)
SELECT *
  FROM remote('ch-ver-v218','test.table_on_v218')
 WHERE value1 IN (SELECT value1 FROM remote('ch-ver-v1911','test.table_on_v1911'))
```
 works

 4. Access from v19.11 with remote to v21.8 and back to same v19.11 in a subquery
```
ch-ver-v1911 :)
SELECT *
  FROM remote('ch-ver-v218','test.table_on_v218')
 WHERE value1 IN (SELECT value1 FROM remote('ch-ver-v1911','test.table_on_v1911'))
```

Error:
```
SQL Error [115]: ClickHouse exception, code: 115, host: ch-ver-v1911, port: 8123; Code: 115, e.displayText() = DB::Exception: Received from ch-ver-v218:9000. DB::Exception: Received from ch-ver-v1911:9000. DB::Exception: Unknown setting normalize_function_names. (version 19.11.12.69 (official build))
```

 5. Access from third server also on v21.8 with remote to v21.8 and that uses remote table on v19.11 in a subquery
```
ch-ver-v218-2 :)
SELECT *
  FROM remote('ch-ver-v218','test.table_on_v218')
 WHERE value1 IN (SELECT value1 FROM remote('ch-ver-v1911','test.table_on_v1911'))
```
Error:
```
SQL Error [115]: ClickHouse exception, code: 115, host: ch-ver-v218-2, port: 8123; Code: 115, e.displayText() = DB::Exception: Received from ch-ver-v218:9000. DB::Exception: Received from ch-ver-v1911:9000. DB::Exception: Unknown setting normalize_function_names. (version 21.8.11.4 (official build))
```

This error is similar when we set some newer options to non-default values - e.g. set default_database_engine=Ordinary that causes similar errors even for cases 1. or 2. 
But in this case, the setting is kept to its default value (normalize_function_names=1) and there is no need to send it to remote only when using a subquery. 

The same behavior is when using Distributed tables instead of the remote function. 

Related to this issue there is the following question:
Is there any setting or some other way to disable propagating any settings to the remote server (changed or not changed) ?
This setting would be really useful in process of upgrading multiple servers.

Thanks !

**Comment by den-crane** [comment]
Everything is expected here. 

21.8.11.4 & 19.11.12.69 are too far from each other. 

Also you may experience incorrect results because you are using incompatible versions https://github.com/ClickHouse/ClickHouse/issues/7851 https://github.com/ClickHouse/ClickHouse/issues/26027

**Comment by loki107** [comment]
@den-crane 

Yes, I know that versions are too far from each other, but it seems that there is inconsistency in behavior in v21.8.
Compare results above of:
- case 3 - v21.8 with primary table local and subquery with remote to v19.11. - works
- case 5 - v21.8 with primary table remote to another v21.8 and subquery with remote to v19.11 - Error. 

It seems that in case 5. somehow CH v21,8 decides to send default settings to remote regardless of the fact that these settings aren't changed. The low version and the error is just an indicator of this behavior. 

Is there any recommended upgrade path in order to circumvent such incompatibilities? 

Also, can you "confirm or deny" the second question:
"
Is there any setting or some other way to disable propagating any settings to the remote server (changed or not changed) ?
"

This feature would also have other use-cases - for example, I don't want to propagate some limits from query server to data cluster because cluster nodes are more or less capable than query server or there is a different usage pattern on the cluster and I want some limits to be tighter there. 
I have set specialized user for cluster remote access (in <remote_servers> config) with a different profile than default - but all these settings get overridden by settings sent from the query server based on the profile of that user. 

We need this in order to plan for the Clickhouse future in our organization. 

Thanks !
