### ISSUE TITLE
--echo option is not used by clickhouse-client in batch mode

### ISSUE THREAD

**Issue by nkolotov** [ClickHouse/ClickHouse#32842]
`--echo` option is not used by clickhouse-client in batch mode with single query.

**Does it reproduce on recent release?**

Does not work on v21.11.5.33 03d80c491f4a1afe4032903859dba4bfbc758e30. Was working before. Regression happened sometime after v21.9.5.16 f78bedb6c1c54627bc68eab774f1a2413bfc4486

**How to reproduce**
Using official docker images:
1) start server 
```
docker run --rm -t -i --net host --ulimit nofile=262144:262144 yandex/clickhouse-server
```
2) execute some query in batch mode
```
docker run --rm -t -i --net host yandex/clickhouse-client --echo --query="CREATE TABLE tmp (val Array(UInt16)) ENGINE = Memory"
```
**Expected behavior**
Executed query should be printed to standard output by client.
```
CREATE TABLE tmp (val Array(UInt16)) ENGINE = Memory
```
**Actual behavior**
Nothing is printed even though query is properly executed and client exits with code 0.

**Comment by evillique** [comment]
@Mergifyio update
