### ISSUE TITLE
Document the types of virtual columns and _error

### ISSUE THREAD

**Issue by ppecheux** [ClickHouse/ClickHouse#32851]
Suggestions to improve [kafka table ](https://clickhouse.com/docs/en/engines/table-engines/integrations/kafka/#virtual-columns)

* document types of virtual columns because you cannot see them using `describe`
* document the new virtual column `_error`

**Comment by Kricket** [comment]
+1

Come on guys, `_error` isn't even mentioned on this page: https://clickhouse.com/docs/en/engines/table-engines/integrations/kafka

Hard to work with if we don't know what the types are.

**Comment by johnnymatthews** [comment]
It looks like `_error` documentation has been added. Closing.
