### ISSUE TITLE
Do S3 APIs not support LowCardinality()? 

### ISSUE THREAD

**Issue by millyz** [ClickHouse/ClickHouse#32889]
When I create a table which has a LowCardinality(String), it fails to write data to S3 storage; then I remove LowCardinality, it succeeds to write into and read from S3.

So do S3 APIs not support LowCardinality()? Is there any methods that I can resolve this problem? Thank you!

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/32372

**Comment by millyz** [comment]
Got it. Thank you!
