### ISSUE TITLE
dead lock happend as follows：__lll_lock_wait

### ISSUE THREAD

**Issue by miaojianxin** [ClickHouse/ClickHouse#32897]
Thread 27 (Thread 0x7efbe87e4700 (LWP 126102)):
#0  0x00007f01929aa54d in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00007f01929a5e9b in _L_lock_883 () from /lib64/libpthread.so.0
#2  0x00007f01929a5d68 in pthread_mutex_lock () from /lib64/libpthread.so.0
#3  0x000000000eb0f6ae in pthread_mutex_lock ()
#4  0x000000001a4307f5 in Poco::NotificationQueue::waitDequeueNotification(long) ()
#5  0x000000001a2fd43c in Poco::Net::TCPServerDispatcher::run() ()
#6  0x000000001a47a90e in Poco::PooledThread::run() ()
#7  0x000000001a475e17 in Poco::ThreadImpl::runnableEntry(void*) ()
#8  0x00007f01929a3ea5 in start_thread () from /lib64/libpthread.so.0
#9  0x00007f01921608dd in clone () from /lib64/libc.so.6
Thread 26 (Thread 0x7efae4f86700 (LWP 126233)):
#0  0x00007f01929a7a35 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x000000001a3d7c0b in Poco::EventImpl::waitImpl() ()
#2  0x000000001a47a9a9 in Poco::PooledThread::run() ()
#3  0x000000001a475e17 in Poco::ThreadImpl::runnableEntry(void*) ()
#4  0x00007f01929a3ea5 in start_thread () from /lib64/libpthread.so.0
#5  0x00007f01921608dd in clone () from /lib64/libc.so.6
Thread 25 (Thread 0x7efae4785700 (LWP 126234)):
#0  0x00007f01929a7a35 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x000000001a3d7c0b in Poco::EventImpl::waitImpl() ()
#2  0x000000001a47a9a9 in Poco::PooledThread::run() ()
#3  0x000000001a475e17 in Poco::ThreadImpl::runnableEntry(void*) ()
#4  0x00007f01929a3ea5 in start_thread () from /lib64/libpthread.so.0
#5  0x00007f01921608dd in clone () from /lib64/libc.so.6
Thread 24 (Thread 0x7efadf77b700 (LWP 126235)):
#0  0x00007f01929a7a35 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x000000001a3d7c0b in Poco::EventImpl::waitImpl() ()
#2  0x000000001a47a9a9 in Poco::PooledThread::run() ()
#3  0x000000001a475e17 in Poco::ThreadImpl::runnableEntry(void*) ()
#4  0x00007f01929a3ea5 in start_thread () from /lib64/libpthread.so.0
#5  0x00007f01921608dd in clone () from /lib64/libc.so.6
Thread 23 (Thread 0x7efadaf72700 (LWP 126453)):
#0  0x00007f01929a7a35 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x000000001a3d7c0b in Poco::EventImpl::waitImpl() ()
#2  0x000000001a47a9a9 in Poco::PooledThread::run() ()
#3  0x000000001a475e17 in Poco::ThreadImpl::runnableEntry(void*) ()
#4  0x00007f01929a3ea5 in start_thread () from /lib64/libpthread.so.0
#5  0x00007f01921608dd in clone () from /lib64/libc.so.6
Thread 22 (Thread 0x7efada771700 (LWP 126466)):
#0  0x00007f01929a7a35 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x000000001a3d7c0b in Poco::EventImpl::waitImpl() ()
#2  0x000000001a47a9a9 in Poco::PooledThread::run() ()
#3  0x000000001a475e17 in Poco::ThreadImpl::runnableEntry(void*) ()
#4  0x00007f01929a3ea5 in start_thread () from /lib64/libpthread.so.0
#5  0x00007f01921608dd in clone () from /lib64/libc.so.6
Thread 21 (Thread 0x7efad3770700 (LWP 126474)):
#0  0x00007f01929a7a35 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x000000001a3d7c0b in Poco::EventImpl::waitImpl() ()
#2  0x000000001a47a9a9 in Poco::PooledThread::run() ()
#3  0x000000001a475e17 in Poco::ThreadImpl::runnableEntry(void*) ()
#4  0x00007f01929a3ea5 in start_thread () from /lib64/libpthread.so.0
#5  0x00007f01921608dd in clone () from /lib64/libc.so.6
Thread 20 (Thread 0x7efad2f6f700 (LWP 126487)):
#0  0x00007f01929a7a35 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x000000001a3d7c0b in Poco::EventImpl::waitImpl() ()
#2  0x000000001a47a9a9 in Poco::PooledThread::run() ()
#3  0x000000001a475e17 in Poco::ThreadImpl::runnableEntry(void*) ()
#4  0x00007f01929a3ea5 in start_thread () from /lib64/libpthread.so.0
#5  0x00007f01921608dd in clone () from /lib64/libc.so.6
Thread 19 (Thread 0x7efad276e700 (LWP 126490)):
#0  0x00007f01929a7a35 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x000000001a3d7c0b in Poco::EventImpl::waitImpl() ()
#2  0x000000001a47a9a9 in Poco::PooledThread::run() ()
#3  0x000000001a475e17 in Poco::ThreadImpl::runnableEntry(void*) ()
#4  0x00007f01929a3ea5 in start_thread () from /lib64/libpthread.so.0
#5  0x00007f01921608dd in clone () from /lib64/libc.so.6
Thread 18 (Thread 0x7efaccf60700 (LWP 126492)):
#0  0x00007f01929a7a35 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x000000001a3d7c0b in Poco::EventImpl::waitImpl() ()
#2  0x000000001a47a9a9 in Poco::PooledThread::run() ()
#3  0x000000001a475e17 in Poco::ThreadImpl::runnableEntry(void*) ()
#4  0x00007f01929a3ea5 in start_thread () from /lib64/libpthread.so.0
#5  0x00007f01921608dd in clone () from /lib64/libc.so.6
Thread 17 (Thread 0x7efacc75f700 (LWP 126494)):
#0  0x00007f01929a7a35 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x000000001a3d7c0b in Poco::EventImpl::waitImpl() ()
#2  0x000000001a47a9a9 in Poco::PooledThread::run() ()
#3  0x000000001a475e17 in Poco::ThreadImpl::runnableEntry(void*) ()
#4  0x00007f01929a3ea5 in start_thread () from /lib64/libpthread.so.0
#5  0x00007f01921608dd in clone () from /lib64/libc.so.6
Thread 16 (Thread 0x7efacbf5e700 (LWP 126496)):
#0  0x00007f01929aa54d in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00007f01929a5e9b in _L_lock_883 () from /lib64/libpthread.so.0
#2  0x00007f01929a5d68 in pthread_mutex_lock () from /lib64/libpthread.so.0
#3  0x000000000eb0f6ae in pthread_mutex_lock ()
#4  0x0000000017df09ef in malloc_mutex_lock_slow ()
#5  0x0000000017e0d79f in tcache_arena_reassociate ()
#6  0x0000000017dce743 in arena_malloc_hard ()
#7  0x0000000017db8ec4 in malloc_default ()
#8  0x0000000016f3a8b8 in DB::WriteBufferFromPocoSocket::WriteBufferFromPocoSocket(Poco::Net::Socket&, unsigned long) ()
#9  0x00000000179d060b in DB::TCPHandler::runImpl() ()
#10 0x00000000179d1bfc in DB::TCPHandler::run() ()
#11 0x000000001a2fd067 in Poco::Net::TCPServerConnection::start() ()
#12 0x000000001a2fd4df in Poco::Net::TCPServerDispatcher::run() ()
#13 0x000000001a47a90e in Poco::PooledThread::run() ()
#14 0x000000001a475e17 in Poco::ThreadImpl::runnableEntry(void*) ()
#15 0x00007f01929a3ea5 in start_thread () from /lib64/libpthread.so.0
#16 0x00007f01921608dd in clone () from /lib64/libc.so.6
Thread 15 (Thread 0x7efa8a1ff700 (LWP 126498)):
#0  0x00007f0192160eb3 in epoll_wait () from /lib64/libc.so.6
#1  0x000000001a2f3c72 in Poco::Net::SocketImpl::pollImpl(Poco::Timespan&, int) ()
#2  0x000000001a2f42c7 in Poco::Net::SocketImpl::receiveBytes(void*, int, int) ()
#3  0x0000000016f2f918 in DB::ReadBufferFromPocoSocket::nextImpl() ()
#4  0x00000000179d1209 in DB::TCPHandler::runImpl() ()
#5  0x00000000179d1bfc in DB::TCPHandler::run() ()
#6  0x000000001a2fd067 in Poco::Net::TCPServerConnection::start() ()
#7  0x000000001a2fd4df in Poco::Net::TCPServerDispatcher::run() ()
#8  0x000000001a47a90e in Poco::PooledThread::run() ()
#9  0x000000001a475e17 in Poco::ThreadImpl::runnableEntry(void*) ()
#10 0x00007f01929a3ea5 in start_thread () from /lib64/libpthread.so.0
#11 0x00007f01921608dd in clone () from /lib64/libc.so.6
Thread 14 (Thread 0x7efa899fe700 (LWP 126520)):
#0  0x00007f01929aa54d in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00007f01929a5e9b in _L_lock_883 () from /lib64/libpthread.so.0
#2  0x00007f01929a5d68 in pthread_mutex_lock () from /lib64/libpthread.so.0
#3  0x000000000eb0f6ae in pthread_mutex_lock ()
#4  0x0000000017df09ef in malloc_mutex_lock_slow ()
#5  0x0000000017dc8758 in extent_alloc_wrapper ()
#6  0x0000000017dcba7f in arena_extent_alloc_large ()
#7  0x0000000017ded824 in large_malloc ()
#8  0x0000000017db8ec4 in malloc_default ()
#9  0x0000000016f3a8b8 in DB::WriteBufferFromPocoSocket::WriteBufferFromPocoSocket(Poco::Net::Socket&, unsigned long) ()
#10 0x00000000179d060b in DB::TCPHandler::runImpl() ()
#11 0x00000000179d1bfc in DB::TCPHandler::run() ()
#12 0x000000001a2fd067 in Poco::Net::TCPServerConnection::start() ()
#13 0x000000001a2fd4df in Poco::Net::TCPServerDispatcher::run() ()
#14 0x000000001a47a90e in Poco::PooledThread::run() ()
#15 0x000000001a475e17 in Poco::ThreadImpl::runnableEntry(void*) ()
#16 0x00007f01929a3ea5 in start_thread () from /lib64/libpthread.so.0
#17 0x00007f01921608dd in clone () from /lib64/libc.so.6
Thread 13 (Thread 0x7efa891fd700 (LWP 127489)):
#0  0x00007f01929aa54d in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00007f01929a5e9b in _L_lock_883 () from /lib64/libpthread.so.0
#2  0x00007f01929a5d68 in pthread_mutex_lock () from /lib64/libpthread.so.0
#3  0x000000000eb0f6ae in pthread_mutex_lock ()
#4  0x000000001a4309e8 in Poco::NotificationQueue::waitDequeueNotification(long) ()
#5  0x000000001a2fd43c in Poco::Net::TCPServerDispatcher::run() ()
#6  0x000000001a47a90e in Poco::PooledThread::run() ()
#7  0x000000001a475e17 in Poco::ThreadImpl::runnableEntry(void*) ()
#8  0x00007f01929a3ea5 in start_thread () from /lib64/libpthread.so.0
#9  0x00007f01921608dd in clone () from /lib64/libc.so.6
Thread 12 (Thread 0x7efa889fc700 (LWP 127492)):
#0  0x00007f0192160eb3 in epoll_wait () from /lib64/libc.so.6
#1  0x000000001a2f3c72 in Poco::Net::SocketImpl::pollImpl(Poco::Timespan&, int) ()
#2  0x000000001a2f42c7 in Poco::Net::SocketImpl::receiveBytes(void*, int, int) ()
#3  0x0000000016f2f918 in DB::ReadBufferFromPocoSocket::nextImpl() ()
#4  0x00000000179d1209 in DB::TCPHandler::runImpl() ()
#5  0x00000000179d1bfc in DB::TCPHandler::run() ()
#6  0x000000001a2fd067 in Poco::Net::TCPServerConnection::start() ()
#7  0x000000001a2fd4df in Poco::Net::TCPServerDispatcher::run() ()
#8  0x000000001a47a90e in Poco::PooledThread::run() ()
#9  0x000000001a475e17 in Poco::ThreadImpl::runnableEntry(void*) ()
#10 0x00007f01929a3ea5 in start_thread () from /lib64/libpthread.so.0
#11 0x00007f01921608dd in clone () from /lib64/libc.so.6
Thread 11 (Thread 0x7efa7a1ed700 (LWP 127493)):
#0  0x00007f0192160eb3 in epoll_wait () from /lib64/libc.so.6
#1  0x000000001a2f3c72 in Poco::Net::SocketImpl::pollImpl(Poco::Timespan&, int) ()
#2  0x000000001a2f42c7 in Poco::Net::SocketImpl::receiveBytes(void*, int, int) ()
#3  0x0000000016f2f918 in DB::ReadBufferFromPocoSocket::nextImpl() ()
#4  0x00000000179d1209 in DB::TCPHandler::runImpl() ()
#5  0x00000000179d1bfc in DB::TCPHandler::run() ()
#6  0x000000001a2fd067 in Poco::Net::TCPServerConnection::start() ()
#7  0x000000001a2fd4df in Poco::Net::TCPServerDispatcher::run() ()
#8  0x000000001a47a90e in Poco::PooledThread::run() ()
#9  0x000000001a475e17 in Poco::ThreadImpl::runnableEntry(void*) ()
#10 0x00007f01929a3ea5 in start_thread () from /lib64/libpthread.so.0
#11 0x00007f01921608dd in clone () from /lib64/libc.so.6
Thread 10 (Thread 0x7efa799ec700 (LWP 128273)):
#0  0x00007f01929aa54d in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00007f01929a5e9b in _L_lock_883 () from /lib64/libpthread.so.0
#2  0x00007f01929a5d68 in pthread_mutex_lock () from /lib64/libpthread.so.0
#3  0x000000000eb0f6ae in pthread_mutex_lock ()
#4  0x0000000017df09ef in malloc_mutex_lock_slow ()
#5  0x0000000017e0d79f in tcache_arena_reassociate ()
#6  0x0000000017db8d57 in malloc_default ()
#7  0x000000000eacff70 in operator new(unsigned long) ()
#8  0x00000000169727eb in DB::AccessControlManager::ContextAccessCache::getContextAccess(DB::ContextAccessParams const&) ()
#9  0x0000000016964991 in DB::AccessControlManager::getContextAccess(StrongTypedef<DB::UInt128, DB::UUIDTag> const&, boost::container::flat_set<StrongTypedef<DB::UInt128, DB::UUIDTag>, std::__1::less<StrongTypedef<DB::UInt128, DB::UUIDTag> >, void> const&, bool, DB::Settings const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::ClientInfo const&) const ()
#10 0x0000000016d2d2ce in DB::Context::setUser(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Poco::Net::SocketAddress const&) ()
#11 0x00000000179cb1ff in DB::TCPHandler::receiveHello() ()
#12 0x00000000179d0661 in DB::TCPHandler::runImpl() ()
#13 0x00000000179d1bfc in DB::TCPHandler::run() ()
#14 0x000000001a2fd067 in Poco::Net::TCPServerConnection::start() ()
#15 0x000000001a2fd4df in Poco::Net::TCPServerDispatcher::run() ()
#16 0x000000001a47a90e in Poco::PooledThread::run() ()
#17 0x000000001a475e17 in Poco::ThreadImpl::runnableEntry(void*) ()
#18 0x00007f01929a3ea5 in start_thread () from /lib64/libpthread.so.0
#19 0x00007f01921608dd in clone () from /lib64/libc.so.6
Thread 9 (Thread 0x7efa791eb700 (LWP 128540)):
#0  0x00007f01929aa54d in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00007f01929a5e9b in _L_lock_883 () from /lib64/libpthread.so.0
#2  0x00007f01929a5d68 in pthread_mutex_lock () from /lib64/libpthread.so.0
#3  0x000000000eb0f6ae in pthread_mutex_lock ()
#4  0x000000001a4307f5 in Poco::NotificationQueue::waitDequeueNotification(long) ()
#5  0x000000001a2fd43c in Poco::Net::TCPServerDispatcher::run() ()
#6  0x000000001a47a90e in Poco::PooledThread::run() ()
#7  0x000000001a475e17 in Poco::ThreadImpl::runnableEntry(void*) ()
#8  0x00007f01929a3ea5 in start_thread () from /lib64/libpthread.so.0
#9  0x00007f01921608dd in clone () from /lib64/libc.so.6
Thread 8 (Thread 0x7eff7a1d6700 (LWP 60951)):
#0  0x00007f01929aa54d in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00007f01929a5e9b in _L_lock_883 () from /lib64/libpthread.so.0
#2  0x00007f01929a5d68 in pthread_mutex_lock () from /lib64/libpthread.so.0
#3  0x000000000eb0f6ae in pthread_mutex_lock ()
#4  0x0000000017df09ef in malloc_mutex_lock_slow ()
#5  0x0000000017dc7b18 in extent_recycle ()
#6  0x0000000017dc7d26 in extents_alloc ()
#7  0x0000000017dcbaee in arena_extent_alloc_large ()
#8  0x0000000017ded824 in large_malloc ()
#9  0x0000000017db8ec4 in malloc_default ()
#10 0x0000000016f3a8b8 in DB::WriteBufferFromPocoSocket::WriteBufferFromPocoSocket(Poco::Net::Socket&, unsigned long) ()
#11 0x00000000179d060b in DB::TCPHandler::runImpl() ()
#12 0x00000000179d1bfc in DB::TCPHandler::run() ()
#13 0x000000001a2fd067 in Poco::Net::TCPServerConnection::start() ()
#14 0x000000001a2fd4df in Poco::Net::TCPServerDispatcher::run() ()
#15 0x000000001a47a90e in Poco::PooledThread::run() ()
#16 0x000000001a475e17 in Poco::ThreadImpl::runnableEntry(void*) ()
#17 0x00007f01929a3ea5 in start_thread () from /lib64/libpthread.so.0
#18 0x00007f01921608dd in clone () from /lib64/libc.so.6
Thread 7 (Thread 0x7eff7a9d7700 (LWP 60952)):
#0  0x00007f01929aa54d in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00007f01929a5eb6 in _L_lock_941 () from /lib64/libpthread.so.0
#2  0x00007f01929a5daf in pthread_mutex_lock () from /lib64/libpthread.so.0
#3  0x000000000eb0f6ae in pthread_mutex_lock ()
#4  0x000000001b3a9e89 in std::__1::recursive_mutex::lock() ()
#5  0x0000000016d1db79 in DB::Context::getLock() const ()
#6  0x0000000016d2d225 in DB::Context::setUser(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Poco::Net::SocketAddress const&) ()
#7  0x00000000179cb1ff in DB::TCPHandler::receiveHello() ()
#8  0x00000000179d0661 in DB::TCPHandler::runImpl() ()
#9  0x00000000179d1bfc in DB::TCPHandler::run() ()
#10 0x000000001a2fd067 in Poco::Net::TCPServerConnection::start() ()
#11 0x000000001a2fd4df in Poco::Net::TCPServerDispatcher::run() ()
#12 0x000000001a47a90e in Poco::PooledThread::run() ()
#13 0x000000001a475e17 in Poco::ThreadImpl::runnableEntry(void*) ()
#14 0x00007f01929a3ea5 in start_thread () from /lib64/libpthread.so.0
#15 0x00007f01921608dd in clone () from /lib64/libc.so.6
Thread 6 (Thread 0x7eff7b9d8700 (LWP 60953)):
#0  0x00007f01929aa54d in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00007f01929a5e9b in _L_lock_883 () from /lib64/libpthread.so.0
#2  0x00007f01929a5d68 in pthread_mutex_lock () from /lib64/libpthread.so.0
#3  0x000000000eb0f6ae in pthread_mutex_lock ()
#4  0x000000001a4309e8 in Poco::NotificationQueue::waitDequeueNotification(long) ()
#5  0x000000001a2fd43c in Poco::Net::TCPServerDispatcher::run() ()
#6  0x000000001a47a90e in Poco::PooledThread::run() ()
#7  0x000000001a475e17 in Poco::ThreadImpl::runnableEntry(void*) ()
#8  0x00007f01929a3ea5 in start_thread () from /lib64/libpthread.so.0
#9  0x00007f01921608dd in clone () from /lib64/libc.so.6
Thread 5 (Thread 0x7effa9dff700 (LWP 63195)):
#0  0x00007f01929aa54d in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00007f01929a5e9b in _L_lock_883 () from /lib64/libpthread.so.0
#2  0x00007f01929a5d68 in pthread_mutex_lock () from /lib64/libpthread.so.0
#3  0x000000000eb0f6ae in pthread_mutex_lock ()
#4  0x0000000017df09ef in malloc_mutex_lock_slow ()
#5  0x0000000017e0ac7e in tcache_bin_flush_small ()
#6  0x0000000017e0b6ba in tcache_event_hard ()
#7  0x0000000017db8c3d in malloc_default ()
#8  0x000000000eacff70 in operator new(unsigned long) ()
#9  0x000000001a43089a in Poco::NotificationQueue::waitDequeueNotification(long) ()
#10 0x000000001a2fd43c in Poco::Net::TCPServerDispatcher::run() ()
#11 0x000000001a47a90e in Poco::PooledThread::run() ()
#12 0x000000001a475e17 in Poco::ThreadImpl::runnableEntry(void*) ()
#13 0x00007f01929a3ea5 in start_thread () from /lib64/libpthread.so.0
#14 0x00007f01921608dd in clone () from /lib64/libc.so.6
Thread 4 (Thread 0x7effcbdc3700 (LWP 63197)):
#0  0x00007f01929aa54d in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00007f01929a5e9b in _L_lock_883 () from /lib64/libpthread.so.0
#2  0x00007f01929a5d68 in pthread_mutex_lock () from /lib64/libpthread.so.0
#3  0x000000000eb0f6ae in pthread_mutex_lock ()
#4  0x000000001a4309e8 in Poco::NotificationQueue::waitDequeueNotification(long) ()
#5  0x000000001a2fd43c in Poco::Net::TCPServerDispatcher::run() ()
#6  0x000000001a47a90e in Poco::PooledThread::run() ()
#7  0x000000001a475e17 in Poco::ThreadImpl::runnableEntry(void*) ()
#8  0x00007f01929a3ea5 in start_thread () from /lib64/libpthread.so.0
#9  0x00007f01921608dd in clone () from /lib64/libc.so.6
Thread 3 (Thread 0x7effcb1c1700 (LWP 72296)):
#0  0x00007f01929aa54d in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00007f01929a5e9b in _L_lock_883 () from /lib64/libpthread.so.0
#2  0x00007f01929a5d68 in pthread_mutex_lock () from /lib64/libpthread.so.0
#3  0x000000000eb0f6ae in pthread_mutex_lock ()
#4  0x000000001a4307f5 in Poco::NotificationQueue::waitDequeueNotification(long) ()
#5  0x000000001a2fd43c in Poco::Net::TCPServerDispatcher::run() ()
#6  0x000000001a47a90e in Poco::PooledThread::run() ()
#7  0x000000001a475e17 in Poco::ThreadImpl::runnableEntry(void*) ()
#8  0x00007f01929a3ea5 in start_thread () from /lib64/libpthread.so.0
#9  0x00007f01921608dd in clone () from /lib64/libc.so.6
Thread 2 (Thread 0x7eff3d822700 (LWP 72298)):
#0  0x00007f01929a7a35 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x000000001a3d7c0b in Poco::EventImpl::waitImpl() ()
#2  0x000000001a47a9a9 in Poco::PooledThread::run() ()
#3  0x000000001a475e17 in Poco::ThreadImpl::runnableEntry(void*) ()
#4  0x00007f01929a3ea5 in start_thread () from /lib64/libpthread.so.0
#5  0x00007f01921608dd in clone () from /lib64/libc.so.6
Thread 1 (Thread 0x7f0192fd3400 (LWP 77986)):
#0  0x00007f01929a7a35 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x000000001b344b62 in std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) ()
#2  0x0000000016836a23 in BaseDaemon::waitForTerminationRequest() ()
#3  0x000000000eb8ba85 in DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) ()
#4  0x000000001a30dca3 in Poco::Util::Application::run() ()
#5  0x000000000eb45c29 in DB::Server::run() ()
#6  0x000000000eb3cd68 in mainEntryClickHouseServer(int, char**) ()
#7  0x000000000eacf911 in main ()

**Comment by miaojianxin** [comment]
the clickhouse version is 20.8.6-lts

**Comment by alexey-milovidov** [comment]
You can update to the latest ClickHouse version.

**Comment by alexey-milovidov** [comment]
To quickly test the latest version, do the following:
```
curl https://clickhouse.com/ | sh
```
