### ISSUE TITLE
Connection reset by peer when importing data from CSV

### ISSUE THREAD

**Issue by Sallery-X** [ClickHouse/ClickHouse#32896]
https://stackoverflow.com/questions/56156682/clickhouse-import-data-from-csv-dbnetexception-connection-reset-by-peer-whil
I try to set max_memory_usage, it didn't work

**Comment by tavplubix** [comment]
No information provided. If you want to report a bug, please, follow [this](https://github.com/ClickHouse/ClickHouse/blob/master/.github/ISSUE_TEMPLATE/85_bug-report.md) template.
