### ISSUE TITLE
Check/review cpu-specific code 

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#32903]
Simple search shows that we have some parts of code which potentially may not work properly / misbehave on different CPU architecture: https://gist.github.com/filimonov/dee7f1c094ac58ca3410bd4ca534a0d0

Would be great to review that / confirm it's safe.

Additionally (when needed) some specializations for Neon can be created, or we can try using smth like https://github.com/DLTcollab/sse2neon

**Comment by alexey-milovidov** [comment]
Duplicate #15174.
