### ISSUE TITLE
Ошибка Code: 235. DB::Exception: Part 202109-30_65271_65281_2 (state Committed) already exists. (DUPLICATE_DATA_PART),

### ISSUE THREAD

**Issue by Papa-tut** [ClickHouse/ClickHouse#32906]
Добрый день, столкнулись с ошибкой: 
Code: 235. DB::Exception: Part 202109-30_65271_65281_2 (state Committed) already exists. (DUPLICATE_DATA_PART).

Версия clickhouse 21.11.4.14 (official build).
2 Шарда по 2 реплики в каждом
Версия zookeeper-3.6.3, кластер из 3х нод, живет отдельно от clickhouse. 
Пользуемся  Distributed.
В логах нет ничего предвещающего ошибку или понятного с её решением, в интернете мало информации на данную тему. 

Логика ошибки не известна, возникает спонтанно. Частота в зависимости от нагрузки, сейчас во время теста, держится нагрузка: ~164K c/s (чуть выше планируемой нагрузки), сервера (ОЗУ, диски) совершенно не нагружены, судя по графикам. На какое то время ошибка пропала, после внедрения балансировки на уровне шарды (<internal_replication>true</internal_replication>), но через какое то время снова вернулась (при тех же конфигурациях, ничего не менялось).

Прикладываю все конфиг файлы кластера. 
<optimize_on_insert>0</optimize_on_insert> - отключен так как это мешает части функционала нашего приложения, проводил тест с включенным <optimize_on_insert> тест дал туже самую ошибку. 

Что было проделано для борьбы с ошибкой: 
1) Прибавили java Xmx Xms для Zookeeper’а.
2) Вынесли Zookeeper на отдельные ноды
3) Обновили clickhouse до версии v21.11.4.14-stable
4 Оптимизировали сервер: 
kernel.pid_max=4194303
net.core.somaxconn=65535
net.core.wmem_max=26214400
net.core.rmem_max=26214400
net.ipv4.tcp_rmem=4096 87380 8388608
net.ipv4.tcp_wmem=4096 65536 8388608
net.ipv4.tcp_mem=8388608 8388608 8388608
net.core.rmem_default=26214400

Если вы сталкивались с подобной ошибкой, прошу любой помощи в её решении!

[clusters.txt](https://github.com/ClickHouse/ClickHouse/files/7734587/clusters.txt)
[users.txt](https://github.com/ClickHouse/ClickHouse/files/7734591/users.txt)
[zookeeper.txt](https://github.com/ClickHouse/ClickHouse/files/7734592/zookeeper.txt)
[config.txt](https://github.com/ClickHouse/ClickHouse/files/7734593/config.txt)

**Comment by den-crane** [comment]
>столкнулись с ошибкой:
>Code: 235. DB::Exception: Part 202109-30_65271_65281_2 (state Committed) already exists. (DUPLICATE_DATA_PART).

столкнулись? В смысле вы в логах наблюдаете эту ошибку, но на ваше приложение это никак не влияет? Правильно? Или нет?

**Comment by Papa-tut** [comment]
> > столкнулись с ошибкой: 
> > Код: 235. DB :: Исключение: Часть 202109-30_65271_65281_2 (состояние зафиксировано) уже существует. (DUPLICATE_DATA_PART).
> 
> столкнулись? В смысле вы в наблюдаете эту ошибку, но на ваше приложение это никак не влияет? Правильно? Или нет?

Добрый день, да, наблюдаем в логах, и это влияет на приложение, теряются данные, ошибка для нас критична. 
В данный момент кластер нагружается синтетическими тестами, не как не можем вывести в прод. (Если это важно)

**Comment by Papa-tut** [comment]
Сегодня ошибка выстрелила снова: 
2021.12.21 10:18:14.231187 [ 1131096 ] {} <Warning> ml._experiment_session_events (ReplicatedMergeTreePartCheckThread): Checking if anyone has a part 202109-30_244267_244625_170 or covering part.
2021.12.21 10:18:14.239036 [ 1131096 ] {} <Warning> ml._experiment_session_events (ReplicatedMergeTreePartCheckThread): Found parts with the same min block and with the same max block as the missing part 202109-30_244267_>
2021.12.21 10:18:14.245608 [ 1131025 ] {} <Warning> ml._experiment_session_events (ReplicatedMergeTreePartCheckThread): Checking part 202109-30_244267_244625_170
2021.12.21 10:18:14.246532 [ 1131025 ] {} <Warning> ml._experiment_session_events (ReplicatedMergeTreePartCheckThread): Checking if anyone has a part 202109-30_244267_244625_170 or covering part.
2021.12.21 10:18:14.256400 [ 1131025 ] {} <Warning> ml._experiment_session_events (ReplicatedMergeTreePartCheckThread): Found parts with the same min block and with the same max block as the missing part 202109-30_244267_>
2021.12.21 10:21:05.394179 [ 1131052 ] {} <Warning> ml._experiment_session_events (ReplicatedMergeTreePartCheckThread): Checking part 202109-15_258564_258568_1
2021.12.21 10:21:05.395045 [ 1131052 ] {} <Warning> ml._experiment_session_events (ReplicatedMergeTreePartCheckThread): Checking if anyone has a part 202109-15_258564_258568_1 or covering part.
2021.12.21 10:21:05.401755 [ 1131052 ] {} <Warning> ml._experiment_session_events (ReplicatedMergeTreePartCheckThread): Found parts with the same min block and with the same max block as the missing part 202109-15_258564_>
2021.12.21 10:21:21.881798 [ 1130962 ] {} <Error> ml._experiment_session_events (a860b6a3-737f-4aa2-a860-b6a3737faaa2): auto DB::StorageReplicatedMergeTree::processQueueEntry(ReplicatedMergeTreeQueue::SelectedEntryPtr)::(>

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x9b605d4 in /usr/bin/clickhouse
1. DB::MergeTreeData::renameTempPartAndReplace(std::__1::shared_ptr<DB::IMergeTreeDataPart>&, SimpleIncrement*, DB::MergeTreeData::Transaction*, std::__1::unique_lock<std::__1::mutex>&, std::__1::vector<std::__1::shared_p>
2. DB::MergeTreeData::renameTempPartAndReplace(std::__1::shared_ptr<DB::IMergeTreeDataPart>&, SimpleIncrement*, DB::MergeTreeData::Transaction*, DB::MergeTreeDeduplicationLog*) @ 0x12d8a3a3 in /usr/bin/clickhouse
3. DB::StorageReplicatedMergeTree::fetchPart(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::basic_st>
4. DB::StorageReplicatedMergeTree::executeFetch(DB::ReplicatedMergeTreeLogEntry&) @ 0x12a678b5 in /usr/bin/clickhouse
5. DB::StorageReplicatedMergeTree::executeLogEntry(DB::ReplicatedMergeTreeLogEntry&) @ 0x12a56ad8 in /usr/bin/clickhouse
6. ? @ 0x12b0dbfd in /usr/bin/clickhouse
7. DB::ReplicatedMergeTreeQueue::processEntry(std::__1::function<std::__1::shared_ptr<zkutil::ZooKeeper> ()>, std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&, std::__1::function<bool (std::__1::shared_ptr<DB::Repli>
8. DB::StorageReplicatedMergeTree::processQueueEntry(std::__1::shared_ptr<DB::ReplicatedMergeTreeQueue::SelectedEntry>) @ 0x12a97413 in /usr/bin/clickhouse
9. DB::ExecutableLambdaAdapter::executeStep() @ 0x12b0e4f1 in /usr/bin/clickhouse
10. DB::MergeTreeBackgroundExecutor<DB::OrdinaryRuntimeQueue>::routine(std::__1::shared_ptr<DB::TaskRuntimeData>) @ 0x12d51bdd in /usr/bin/clickhouse
11. DB::MergeTreeBackgroundExecutor<DB::OrdinaryRuntimeQueue>::threadFunction() @ 0x12d525da in /usr/bin/clickhouse
12. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0x9ba528a in /usr/bin/clickhouse
13. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&, void ThreadPoolImpl<T>
14. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x9ba2697 in /usr/bin/clickhouse
15. ? @ 0x9ba609d in /usr/bin/clickhouse
16. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
17. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
 (version 21.11.4.14 (official build))

**Comment by den-crane** [comment]
А вы никогда не восстанавливали зукипер из бекапа? Или может копировали zkCopy? 
У вас как будто автоинктементы в ЗК начали повторять значения.

**Comment by Papa-tut** [comment]
> А вы никогда не восстанавливали зукипер из бекапа? Или может копировали zkCopy? У вас как будто автоинктементы в ЗК начали повторять значения.

Мы проводили многочисленные тесты, не однократно переносили зукиперы на другие ноды, зачищали схемы в бд и начинали заново, возможно где то что то не корректно зачистилось. Возможно от этого создался такой эффект "восстановления из бекапа". Подскажите пожалуйста, как сейчас можно это подтвердить, опровергнуть, 
или возможно исправить данную ситуацию? 
В данный момент нам подойдут любые решения, так как кластер не в проде, можно проводить любые тесты, правки.

**Comment by Slach** [comment]
если кластер тестовый
попробуйте 
- остановить вставку
- почистить все данные из Zookeeper по пути /clickhouse (или что у вас в replicatedMergeTree прописано
- потом сделать SYSTEM RESTORE REPLICA db.table где db.table таблица в которой возникают DUPLICATE_DATA_PART

**Comment by den-crane** [comment]
> zookeeper-3.6.3

попробуйте zk 3.5

**Comment by filimonov** [comment]
Судя по названию парта - это была попытка выполнить мерж. Эта ошибка никак не должна отражаться на пользователях. Может быть на пользователях отражались какие-то другие ошибки? Пожалуйства перепроверьте.

Возможно это какие-то гонки между репликами. Возможно уже было починено. Если будет повторяться после обновления - то будут нужны полные стектрейсы ошибок, и по возможности фрагменты логов упоминающие проблемный парт - со всех реплик с log level = trace (используется по умолчанию), и system.replication_queue (со всех реплик).

**Comment by Papa-tut** [comment]
Обновил clickhouse до версии 21.11.9.1 (official build).
Обновил zookeeper до версии 3.7.0
Проводятся тесты, но ошибка пока что сохраняется, в данный момент тестируем и пытаемся понять "вред" от ошибки.

**Comment by Papa-tut** [comment]
@losdmi
Добрый день, к сожалению не могу помочь конструктивным ответом, у нас ошибка ушла. 
Могу дать только направление в сторону которого стоит обратить внимание: 
Обратите внимание на размер батчей, и скорость вставки, в таблицы. 
Посмотреть в сторону окна дубликации replicated_deduplication_window=""
Балансировка кластера между шардами.
Обратите внимание на схему таблицы, к нашей были замечания которые мы поправили. 
Что именно дало результат, сказать однозначно сложно.

**Comment by tbragin** [comment]
Question appears answered, closing.
