### ISSUE TITLE
Mutations cannot be listed nor killed

### ISSUE THREAD

**Issue by homeofthewizard** [ClickHouse/ClickHouse#32927]
Hello,

I have used an ALTER TABLE UPDATE query. After it I am unable to access to that table, nor to drop it.
I tried to check the mutations running and kill them, but I am unable to read the system.mutations table, nor to kill mutations.
The queries I have used:

`ALTER TABLE DATABASECHANGELOG UPDATE TAG='initial' WHERE DATEEXECUTED=(SELECT DATEEXECUTED FROM DATABASECHANGELOG DATEEXECUTEC DESC LIMIT 1)
`
Query runned ok after 59 seconds.
But then unable to do a select from the table. I have read timeouts after 1 minute.(the table has only one entry)

Then I tried to check the system.mutations, but same I have read timeouts.
When I trie to kill the mutations with the following query,
`KILL MUTATION WHERE DATABASE='default'`

The query got stuck in execution.

ClickHouse server version I use: 21.6.9.7

**Comment by den-crane** [comment]
@homeofthewizard 21.6 is out support. Check is it reproduce with 21.12 or not.

**Comment by skgmtmy** [comment]
same problem on clickhouse 21.12, any idea?
