### ISSUE TITLE
DB::Exception: Transaction failed (No node) when creating Replicated DB

### ISSUE THREAD

**Issue by simPod** [ClickHouse/ClickHouse#32938]
I'm trying to use db Replicated engine as advised in https://github.com/ClickHouse/ClickHouse/issues/31661#issuecomment-977149610 but getting `Transaction failed (No node)`

```
CREATE DATABASE tmp
ENGINE = Replicated('/clickhouse/tmp/tables', '{shard}', '{replica}')

Query id: f4e2d57f-ee0f-4706-b62f-5560e5d4f7f3


0 rows in set. Elapsed: 0.005 sec.

Received exception from server (version 21.9.4):
Code: 999. DB::Exception: Received from 127.0.0.1:9000. DB::Exception: Transaction failed (No node): Op #0, path: /clickhouse/tmp/tables/replicas/01|flop-chdb-4. (KEEPER_EXCEPTION)
```

any idea what am I doing wrong? Thanks

_I have `allow_experimental_database_replicated` enabled_ https://github.com/ClickHouse/ClickHouse/issues/32861

**Comment by bug65536** [comment]
i got same error when i want to insert data:
```
insert into t1 (id,name) values (1,'1')
```

**Comment by tavplubix** [comment]
Looks like it's #38927
