### ISSUE TITLE
Try using the mold linker in CI

### ISSUE THREAD

**Issue by amosbird** [ClickHouse/ClickHouse#32947]
Recently https://github.com/rui314/mold has released v1.0. It shows amazing speed up over the second fastest linker: lld. Perhaps we can use it to boost our CI.

**Comment by Algunenano** [comment]
I tried using it locally but it has some issues with sysroot (https://github.com/rui314/mold/issues/150) which is used in hermetic builds

**Comment by sundy-li** [comment]
I tested it yet it's not worked on MacOSX.


https://github.com/rui314/mold/issues/132

**Comment by alexey-milovidov** [comment]
The idea was also suggested by @myrrc yesterday.

I expect it will not work during lack of LTO support. 
And LTO is correctly handled only if exactly the same lld version is used as clang.

**Comment by alexey-milovidov** [comment]
I expect that linking takes only around 10s of seconds in CI, while full build takes not less than two minutes.

**Comment by alexey-milovidov** [comment]
Closing as the task has unclear perspective.
