### ISSUE TITLE
22.1 release checklist and changing of default values for some settings

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#32941]
Please list here all the issues that must be fixed before the next release in Jan 2022.

ClickHouse version 22 will be backward compatible with 21, as usual.
Changing the first version number does not imply anything more than changing the second number.

Nevertheless, we can use this release to also change default values of some settings
to enable some features that were not enabled by default.

Please list here the default values that you want to change.

**Comment by CurtizJ** [comment]
One candidate is `optimize_functions_to_subcolumns`.

**Comment by alexey-milovidov** [comment]
`GROUPING SETS` - remove this feature if the issues found by CI will not be fixed.

**Comment by ramazanpolat** [comment]
I believe the `max_memory_usage` is still 10G by default. 

How about setting it to a reasonable amount for the host? It is easy to forget about when installing and it usually **reminds itself** later with a call from the client at 3 AM.

**Comment by alexey-milovidov** [comment]
@ramazanpolat We want to implement in in several steps:
1. Add memory overcomit: https://github.com/ClickHouse/ClickHouse/issues/28375 (this task is in review and have high chance to be finished in January).
2. Enable it for queries, so any query will be able to occupy up to the whole server if there are no other queries but will preempt if there are many queries.

**Comment by Algunenano** [comment]
`asynchronous_metrics_update_period_s`, which is undocumented, defaults to 1. This seems excesive for normal use since it might involve checking many sensors.

**Comment by alexey-milovidov** [comment]
Changelog is ready: https://github.com/ClickHouse/ClickHouse/blob/master/CHANGELOG.md

**Comment by alexey-milovidov** [comment]
> asynchronous_metrics_update_period_s

I checked on one of the servers where it is enabled since July 2021 and it is 16 GB - less than 100 MB per day.
It also contains 16 billion records (almost exactly one byte per record).
Looks very small. Although maybe we can lower it to 10 seconds.
Or apply some best practices to compress it even further.
