### ISSUE TITLE
Why projection not working sometimes?

### ISSUE THREAD

**Issue by liuzhiguo630** [ClickHouse/ClickHouse#32943]
Background: I have a traceLog table
```
CREATE TABLE skywalking.segment
(
    `segment_id` String,
    `trace_id` String,
    `service_id` LowCardinality(String),
    `service_instance_id` LowCardinality(String),
    `endpoint_name` String,
    `endpoint_component_id` LowCardinality(String),
    `start_time` DateTime64(3),
    `end_time` DateTime64(3),
    `latency` Int32,
    `is_error` Enum8('error' = 1, 'success' = 0),
    `data_binary` String,
    `tag` Map(String, String),
    INDEX idx_error is_error TYPE minmax GRANULARITY 1,
    PROJECTION p_latency
    (
        SELECT start_time, service_id, endpoint_name, trace_id, is_error, latency
        ORDER BY (latency, start_time, service_id, endpoint_name)
    )
) ENGINE = MergeTree
PARTITION BY toYYYYMMDD(start_time)
ORDER BY (start_time, service_id, endpoint_name, trace_id, latency)
```
There are two ways to search for list, order by start_time: `select * from segment where start_time between '' and '' order by start_time`. Or order by latency: `select * from segment where start_time between '' and '' order by latency`

The condition start_time are always exists when searching, so I put it in DDL order by. And I found projection to resolve order by latency problem, but now it now working sometimes;

Such as:
```
-- query
select start_time, service_id, endpoint_name, trace_id, is_error, latency from segment where start_time between '2021-12-17 00:07:05.003' and '2021-12-17 01:45:23.991' order by latency  limit 1;

-- result
┌──────────────start_time─┬─service_id─┬─endpoint_name───────────────────────────────────────────────────────────────────────────┬─trace_id─────────────────────────────┬─is_error─┬─latency─┐
│ 2021-12-17 01:44:41.006 │ fb-jaguar  │ cn.jojo.edu.malacca.rpc.api.service.EduTeacherRpcService.queryUserTeacherRelationStatus │ 9dff63be-cac0-4daa-b880-f4653638504d │ error    │       1 │
└─────────────────────────┴────────────┴───────────────────────────────────────────────────────────────���─────────────────────────┴──────────────────────────────────────┴──────────┴─────────┘

1 rows in set. Elapsed: 0.057 sec. Processed 139.26 thousand rows, 17.78 MB (2.46 million rows/s., 313.85 MB/s.)

-- explain 
┌─explain─────────────────────────────────────────────────────────────────────────┐
│ Expression (Projection)                                                         │
│   Limit (preliminary LIMIT (without OFFSET))                                    │
│     Sorting                                                                     │
│       Expression (Before ORDER BY)                                              │
│         SettingQuotaAndLimits (Set limits and quota after reading from storage) │
│           ReadFromStorage (MergeTree(with Normal projection p_latency))         │
└────────────────────────────────────────────────────────────────────────────────���┘


-- it's working, but when I changed start_time such as  **2021-12-17 00:20:00.000**,  it's not working

-- query
select start_time, service_id, endpoint_name, trace_id, is_error, latency from segment where start_time between '2021-12-17 00:20:00.000' and '2021-12-17 01:45:23.991' order by latency  limit 1;

-- result
┌──────────────start_time─┬─service_id─────┬─endpoint_name──────────────────────┬─trace_id─────────────────────────────┬─is_error─┬─latency─┐
│ 2021-12-17 00:42:22.828 │ vulcan-taishan │ /noRight/campaign/get-sold-landing │ 1cfe1a12-b1dc-48b7-a5db-1021251ef26c │ error    │       1 │
└─────────────────────────┴────────────────┴────────────────────────────────────┴──────────────────────────────────────┴──────────┴─────────┘

1 rows in set. Elapsed: 124.970 sec. Processed 868.88 million rows, 110.91 GB (6.95 million rows/s., 887.51 MB/s.)

-- explain
┌─explain───────────────────────────────────────────────────────────────────────────┐
│ Expression (Projection)                                                           │
│   Limit (preliminary LIMIT (without OFFSET))                                      │
│     Sorting (Sorting for ORDER BY)                                                │
│       Expression (Before ORDER BY)                                                │
│         Filter (WHERE)                                                            │
│           SettingQuotaAndLimits (Set limits and quota after reading from storage) │
│             ReadFromMergeTree                                                     │
└────────────────────────────────────────────���──────────────────────────────────────┘

```

This problem troubled me for a long time，I need some help.

**Comment by amosbird** [comment]
1. Which version of clickhouse do you use?
2. Do you have projection `p_latency` fully materialized? You can inspect the `system.parts` table to check if all related data parts contain projection `p_latency`.


Currently the rule of picking a projection is based on the number of granules, which doesn't take the read-in-order optimization into account yet.

**Comment by liuzhiguo630** [comment]
> 1. Which version of clickhouse do you use?
> 2. Do you have projection `p_latency` fully materialized? You can inspect the `system.parts` table to check if all related data parts contain projection `p_latency`.
> 
> Currently the rule of picking a projection is based on the number of granules, which doesn't take the read-in-order optimization into account yet.

1. version
```
select version()

┌─version()─┐
│ 21.11.6.7 │
└───────────┘
```

2. Yes, I executed this after add projection: `alter table skywalking.segment MATERIALIZE PROJECTION pj_trace;`, waiting for `SELECT parts_to_do, * FROM system.mutations WHERE is_done = 0;` , and checked latest_fail_reason is null.

Later I dropped table, and add projection in create table DDL. Now system.projection_parts is:
```
select name, sum(bytes_on_disk)/1024/1024/1024 as gb_on_disk from system.projection_parts group by name;
┌─name───────┬────────gb_on_disk─┐
│ p_latency  │ 51.04777462501079 │
└────────────┴───────────────────┘
```
Just curious, why `start_time between '2021-12-17 00:07:05.003' and '2021-12-17 01:45:23.991' ` are work, smaller date range not work? BTW, this date range is from `select min(start_time), max(start_time) from segment`. 

I'm trying to use Clickhouse to handling Skywalking APM data, projection helped me to query with trace_id, but seemed not work with order by latency.  Is there any another way to achieve? I referred [jaeger with clickhouse](https://github.com/bobrik/jaeger/tree/ivan/clickhouse/plugin/storage/clickhouse), not so good.

**Comment by amosbird** [comment]
> Just curious, why start_time between '2021-12-17 00:07:05.003' and '2021-12-17 01:45:23.991' are work, smaller date range not work? 

Because you have the base table ordered with `start_time` at first, which means it can prune granules better when the filter only has `start_time` based predicates. During planing, we generate two query pipelines (with and without projection) and pick the pipeline that reads less granules.

**Comment by liuzhiguo630** [comment]
> > Just curious, why start_time between '2021-12-17 00:07:05.003' and '2021-12-17 01:45:23.991' are work, smaller date range not work?
> 
> Because you have the base table ordered with `start_time` at first, which means it can prune granules better when the filter only has `start_time` based predicates. During planing, we generate two query pipelines (with and without projection) and pick the pipeline that reads less granules.

Seemed right. I notice there are too many projection directories like `p_latency_123` in partition directory. So I executed `optimize table segment final`, after optimize done, projection finally work.

But I don't know will it work in production, obviously I can't optimize every time. Maybe `force_optimize_projection=1` could help?

**Comment by amosbird** [comment]
> But I don't know will it work in production

By working if you mean the behavior of read-in-order optimization, the answer is: it depends. Currently normal projections are mainly used to provide a different set of primary indices. It's non-trivial to tell if a projection will work better w.r.t `ORDER BY ... LIMIT `
