### ISSUE TITLE
HTTP interface overhead is high?

### ISSUE THREAD

**Issue by zhicwu** [ClickHouse/ClickHouse#32958]
When benchmarking [1] JDBC driver 0.3.2(uses http) and [2] Native JDBC 2.6.3(uses tcp) against ClickHouse 21.11, I noticed different CPU usage on server side. It looks like HTTP interface has way more overhead compare to TCP/Native in terms of CPU usage. Is it related to HTTP chunked transfer encoding?
- 4 threads
  ![image](https://user-images.githubusercontent.com/4270380/146696956-ec5a9dc1-915e-46c4-af7f-2dc9c70c90f9.png)
- single thread
  ![image](https://user-images.githubusercontent.com/4270380/146697496-33b8326e-ba0b-4668-a0a7-6e6f0196c67b.png)

Environment:
* two VMs dedicated for the testing, both with same spec(32GB RAM + 4 CPU cores)

Parameters:
* 4 concurrent threads
* queries are all based on `numbers` function so no disk I/O should be involved
* RowBinary format is used for serialization/deserialization between server and client
* sampleSize=100000, which will be used to substitute question mark in test query like `select range(100, number % 600) as v from numbers(?)`
* fetchSize=1000
* connection=reuse
* statement=prepared
* compression=true (lz4 for decompressing response from server)

Steps:
* drop and re-create ClickHouse container before [benchmarking](../../clickhouse-jdbc/blob/develop/clickhouse-benchmark/src/main/java/com/clickhouse/benchmark/jdbc/Query.java)

**Comment by den-crane** [comment]
1. You are using 2 different formats Native & RowBinary
2. No proof that queries / second are the same in both cases. You client HTTP + RowBinary probably performs much better and doing much more queries. The the load of CH server is much more.
