### ISSUE TITLE
Replication doesn't start using MaterializedPostgreSQL engine

### ISSUE THREAD

**Issue by sh4dowm4ster** [ClickHouse/ClickHouse#32989]
Hi!
I'm trying to replicate pg tables using MaterializedPostgreSQL engine like this (https://clickhouse.com/docs/en/engines/database-engines/materialized-postgresql/):
CREATE DATABASE pg_database_test
ENGINE = MaterializedPostgreSQL('hostname:5432', 'database', 'user', 'password')
SETTINGS materialized_postgresql_max_block_size = 100,
         materialized_postgresql_tables_list = 'table_name',
         materialized_postgresql_allow_automatic_update = 1;
(Same issue with the other block size and with an empty table)
Then clickhouse successfully creates a publication on the target and a replication slot, creates new database with the selected engine in Clickhouse, but can't create a table in there.

That's what I see in postgres log (repeats every second):
STATEMENT: COPY (select lsn, data FROM pg_logical_slot_peek_binary_changes('pg_database_ch_replication_slot', NULL, 10, 'publication_names', 'pg_database_ch_publication', 'proto_version', '1')) TO STDOUT
LOG: logical decoding found consistent point at A6/107CCE58
DETAIL: There are no running transactions.
STATEMENT: COPY (select lsn, data FROM pg_logical_slot_peek_binary_changes('pg_database_ch_replication_slot', NULL, 10, 'publication_names', 'pg_database_ch_publication', 'proto_version', '1')) TO STDOUT
LOG: starting logical decoding for slot "pg_database_ch_replication_slot"
DETAIL: Streaming transactions committing after A6/107CCE90, reading WAL from A6/107CCE58.
STATEMENT: COPY (select lsn, data FROM pg_logical_slot_peek_binary_changes('pg_database_ch_replication_slot', NULL, 10, 'publication_names', 'database_ch_publication', 'proto_version', '1')) TO STDOUT
LOG: logical decoding found consistent point at A6/107CCE58
DETAIL: There are no running transactions.
--repeats several times--
and terminates with:
FATAL: out of relcache_callback_list slots
Then it loops.

In clickhouse log - this:
<Debug> PostgreSQLReplicationHandler: checking for skipped tables: 0
<Debug> PostgreSQLReplicationHandler: Scheduling replication thread: now
<Debug> PostgreSQLReplicationHandler: checking for skipped tables: 0
<Debug> PostgreSQLReplicationHandler: Scheduling replication thread: now
--repeats several times--
<Debug> PostgreSQLConnection: New connection to hostname:5432
<Debug> PostgreSQLReplicationHandler: checking for skipped tables: 0
<Debug> PostgreSQLReplicationHandler: Scheduling replication thread: after 2000 ms
and it loops.
PG-user has replication role, owns selected table, able to create objects in schema and can use it.
PostgreSQL version: 12.6
Clickhouse version: 21.12.2.17
Could you help me, please. What else do I need to configure?

**Comment by kssenii** [comment]
Were there any error logs just when the database engine was created? The point is -- did it manage to load any table? There should be logs about what was tried to be loaded.

**Comment by sh4dowm4ster** [comment]
Thanks, @kssenii ! I managed this defining materialized_postgresql_schema, recently appeared parameter.
I used to set search_path before.
