### ISSUE TITLE
Неправильный вывод значений при использовании WITH ROLLUP и sumMap( )

### ISSUE THREAD

**Issue by karlen532** [ClickHouse/ClickHouse#32986]
**Describe what's wrong**
При использовании sumMap вместе с WITH ROLLUP возвращается не правильное значение для одной из строк.

**Does it reproduce on recent release?**
Проблема воспроизводится на версии v21.12.2.17

**How to reproduce**

- Clickhouse v21.12.2.17

```
CREATE TABLE bar 
(
    id String,
    n UInt32,
    w Map(UInt32, UInt32),
    y UInt32
)   
ENGINE = MergeTree()
PRIMARY KEY(id);
```

- Для воспроизведения необходимо выполнить данные запросы:
```
INSERT INTO bar 
VALUES('0',1, {1:1},1 ),('2',2, {1:2},2 ), ('3',1, {1:1},1 ), ('4',2, {1:2},2 );

SELECT 	sum(y), sumMap( w ), n
FROM bar
GROUP BY n
WITH ROLLUP 
ORDER BY n ASC;
```

**Expected behavior**
Ожидаемый результат:

```
sum(y)|sumMap(w)|n|
------|---------|-|
     6|{1=6}    |0|
     2|{1=2}    |1|
     4|{1=4}    |2|
```

Фактический результат:
(Разница в последней записи в колонке sumMap).

```
sum(y)|sumMap(w)|n|
------|---------|-|
     6|{1=6}    |0|
     2|{1=2}    |1|
     4|{1=6}    |2| <--- ошибка на данной строке в колонке sumMap(w). Ожидается: {1=4}
```

Без использования ROLLUP запрос выполнятся без проблем.
```
SELECT 	sum(y), sumMap( w ), n
FROM bar
GROUP BY n
ORDER BY n ASC;
```
Возвращает:
```
sum(y)|sumMap(w)|n|
------|---------|-|
     2|{1=2}    |1|
     4|{1=4}    |2|
```

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/32935
