### ISSUE TITLE
[RFC] How to count read rows and bytes in scalar subqueries

### ISSUE THREAD

**Issue by Algunenano** [ClickHouse/ClickHouse#32993]
Hi,

As you might be aware, ClickHouse currently doesn't count rows or bytes read/written in scalar subqueries, and it doesn't handle query cancellation or progress in them either.

While working on being able to cancel scalar queries in https://github.com/ClickHouse/ClickHouse/pull/32271 it turns out that everything was related and once you are able to cancel them you get progress reports, rows read/written and so on all with the same change.

@KochetovNicolai pointed out that we would be breaking backwards compatibility since some people might be relying in the fact that rows read by the scalar subqueries are not accounted in the final report or the limits, in fact there are many tests that needed to be changed for this reason.

Paraphrasing his comments, therea re a few things that we can do:
```
* Keep ignoring max_rows_to_read for subqueries and discuss possible changes in a separate pr. It's the easiest one, I would be happy to merge this pr. (There could be other settings which are not obvious, and we should be ready to default them too).
* Mark this pr as backward incompatibly, and introduce another one setting to roll back to old behaviour (which we can remove probably in a few month). (I don't like new settings).
* Also add a new setting, but keep current behaviour as default.
* Separate settings for subqueries (which may be zero or same for query by default).
```

Personally I would change the behaviour without any settings to turn it off for 2 reasons:
* I think that this is a good improvement and something desirable in all cases. Reporting read rows indepedently of where they were read (CTE, main query, subqueries, scalar subqueries) should be the way to go.
* It keeps the code clean. Adding more settings involves either complicating the code or breaking the ability to KILL scalar subqueries.

What does the community think? Do somebody need to keep the old behaviour and wouldn't be able to handle the change?

**Comment by alexey-milovidov** [comment]
> Personally I would change the behaviour without any settings

I'm also for this.
We should account everything for scalar subqueries.
Changes in tests are Ok.

**Comment by filimonov** [comment]
+1. It was just incorrect. There are some tiny risks that somebody relies on that incorrect behaviour, but it's a poor reason to keep it incorrect or introduce some ugly flags there. We just need to have a good & clear message for the changelog, so people can prepare for that.

**Comment by Algunenano** [comment]
Addendum question. With the changes and a query like:

```
SELECT '#02136_scalar_subquery_1', (SELECT max(number) FROM numbers(1000000)) as n format JSONCompact;
```

I get:
```
read_rows:                             1048081
read_bytes:                            8384641
```

This matches the profile events:
```
ProfileEvents:                         {'Query':1,'SelectQuery':1,'ArenaAllocChunks':1,'ArenaAllocBytes':4096,'TableFunctionExecute':1,'NetworkSendElapsedMicroseconds':61,'NetworkSendBytes':1187,'CompileFunction':1,'CompileExpressionsMicroseconds':17713,'CompileExpressionsBytes':8192,'SelectedRows':1048081,'SelectedBytes':8384641,'ContextLock':33,'RWLockAcquiredReadLocks':2,'RealTimeMicroseconds':22596,'UserTimeMicroseconds':19304,'SoftPageFaults':437,'OSCPUVirtualTimeMicroseconds':19304,'OSReadChars':1896,'OSWriteChars':3730}
```

And with some **pending** changes it will be the report too:
```
< X-ClickHouse-Progress: {"read_rows":"0","read_bytes":"0","written_rows":"0","written_bytes":"0","total_rows_to_read":"1000000"}
< X-ClickHouse-Progress: {"read_rows":"65505","read_bytes":"524040","written_rows":"0","written_bytes":"0","total_rows_to_read":"1000000"}
< X-ClickHouse-Progress: {"read_rows":"131010","read_bytes":"1048080","written_rows":"0","written_bytes":"0","total_rows_to_read":"1000000"}
< X-ClickHouse-Progress: {"read_rows":"196515","read_bytes":"1572120","written_rows":"0","written_bytes":"0","total_rows_to_read":"1000000"}
< X-ClickHouse-Progress: {"read_rows":"262020","read_bytes":"2096160","written_rows":"0","written_bytes":"0","total_rows_to_read":"1000000"}
< X-ClickHouse-Progress: {"read_rows":"327525","read_bytes":"2620200","written_rows":"0","written_bytes":"0","total_rows_to_read":"1000000"}
< X-ClickHouse-Progress: {"read_rows":"393030","read_bytes":"3144240","written_rows":"0","written_bytes":"0","total_rows_to_read":"1000000"}
< X-ClickHouse-Progress: {"read_rows":"458535","read_bytes":"3668280","written_rows":"0","written_bytes":"0","total_rows_to_read":"1000000"}
< X-ClickHouse-Progress: {"read_rows":"524040","read_bytes":"4192320","written_rows":"0","written_bytes":"0","total_rows_to_read":"1000000"}
< X-ClickHouse-Progress: {"read_rows":"589545","read_bytes":"4716360","written_rows":"0","written_bytes":"0","total_rows_to_read":"1000000"}
< X-ClickHouse-Progress: {"read_rows":"655050","read_bytes":"5240400","written_rows":"0","written_bytes":"0","total_rows_to_read":"1000000"}
< X-ClickHouse-Progress: {"read_rows":"720555","read_bytes":"5764440","written_rows":"0","written_bytes":"0","total_rows_to_read":"1000000"}
< X-ClickHouse-Progress: {"read_rows":"786060","read_bytes":"6288480","written_rows":"0","written_bytes":"0","total_rows_to_read":"1000000"}
< X-ClickHouse-Progress: {"read_rows":"851565","read_bytes":"6812520","written_rows":"0","written_bytes":"0","total_rows_to_read":"1000000"}
< X-ClickHouse-Progress: {"read_rows":"917070","read_bytes":"7336560","written_rows":"0","written_bytes":"0","total_rows_to_read":"1000000"}
< X-ClickHouse-Progress: {"read_rows":"982575","read_bytes":"7860600","written_rows":"0","written_bytes":"0","total_rows_to_read":"1000000"}
< X-ClickHouse-Progress: {"read_rows":"1048080","read_bytes":"8384640","written_rows":"0","written_bytes":"0","total_rows_to_read":"1000000"}
< X-ClickHouse-Progress: {"read_rows":"1048081","read_bytes":"8384641","written_rows":"0","written_bytes":"0","total_rows_to_read":"1000000"}
< X-ClickHouse-Progress: {"read_rows":"1048081","read_bytes":"8384641","written_rows":"0","written_bytes":"0","total_rows_to_read":"1000000"}
< X-ClickHouse-Summary: {"read_rows":"1048081","read_bytes":"8384641","written_rows":"0","written_bytes":"0","total_rows_to_read":"1000000"}
```


My question now is, why **1048081** and not **1000000**. I'm guessing CH is counting blocks or some other thing internally, not only rows read from disk. Is that expected? I don't think this is correct right? Should it always match rows from disk and ignore reads from memory / blocks?

**Comment by azat** [comment]
>My question now is, why 1048081 and not 1000000.

Clickhouse read by blocks, default size if 65505, 65505*16 = 1048080
And I guess one row for primary query, so 1048081

> not only rows read from disk

From disk it also reads in blocks.

> Is that expected?

Yes.

> Should it always match rows from disk and ignore reads from memory / blocks?

I think current behavior is OK (since those rows was read from disk/storage anyway) in statistics, and I guess it is fine to account those rows for limiting too (since I guess otherwise code will be more complex, but worth adding a note about limit should be multiple of max_block_size).

**Comment by Algunenano** [comment]
I see, it makes sense. Thanks a lot.
