### ISSUE TITLE
How to create Replicated table for Join Engine table

### ISSUE THREAD

**Issue by cainiaodidi** [ClickHouse/ClickHouse#32995]
There are Replicated shards on the cluster, and due to I can't create a 'ReplicatedJoin' engine table, I create a Distributed Engine table(join_dist) on the Join Engine local table(join_local). After I insert data into local table by proxy, I do this query: select count(1) from join_dist and I find that its result is approximate a half of actual value. I think this query only collect half shards result of cluster. How can I solve this？

**Comment by den-crane** [comment]
You can use a multiplexing feature of Distributed table.


So you create an additional cluster `remote_serves` where all Clickhouse nodes a replicas in a single shard with internal_replication = false
Then you create a Distributed table using that new cluster.
Then you insert data into Distributed table and Distributed table multiplex inserts and write exactly the same data to all replicas (to all engine=Join tables).

Then you use `select count(1) from join` -- you don't need to use select count(1) from `_dist` because all join tables have the same data.

**Comment by cainiaodidi** [comment]
Thanks for your reply. 
That means there are two cluster on the same nodes? And I have never heard this, is there any docs introducing this feature? 
First, if all nodes have the same data, all nodes will allocate memory for join table, and which will waste some memory I think. Second, in this way, is there any difference between dict engine and join engine?

**Comment by den-crane** [comment]
>That means there are two cluster on the same nodes?

You have any number of clusters over the same nodes.
For example if you have 12 nodes you can create 
1. 1 shard 12 replicas
2. 12 shars 1 replica
3. 2 shards 6 replicas
4. 3 shards 4 replicas
5. 6 shards 2 replica
6. 4 shards 3 replica
--
6 clusters simultaneously. 

>And I have never heard this, is there any docs introducing this feature?

It was from the beginning. It's kinda common knowledge.

>First, if all nodes have the same data, all nodes will allocate memory for join table, 
>and which will waste some memory if there is much data in table I think. 

It's unavoidable with with JOINs

>Second, in this way, it won't use the feature of distributed query

It's pretty same If you need local joins on shards, just create the sharded cluster and use Distributed for replication (internal_replication = false)

>Another thing is that if I insert data into Distributed table, and the data will randomly assigned to all shards if I set sharding 

I proposed a single shard.

**Comment by cainiaodidi** [comment]
> I proposed a single shard.  

I understand a little bit. if I don't need to use local joins, I need to create a cluster of 1 shard N replicas, and I can use the feature of replication, I only need to create join engine table on one shard and insert data into it, then all the nodes can get the same data. right? 

And another thing I want to confirm is that: if I create two clusters: (for example: cluster1 -> 1 shard 12 replicas, cluster2 -> 6 shard 2 replicas), the left table in cluster2 can join with right table in cluster1?

**Comment by den-crane** [comment]
>I understand a little bit. if I don't need to use local joins, I need to create a cluster of 1 shard N replicas, and I can use the 
>feature of replication, I only need to create join engine table on one shard and insert data into it, then all the nodes can get 
>the same data. right?

right.

>And another thing I want to confirm is that: if I create two clusters: (for example: cluster1 -> 1 shard 12 replicas,
> cluster2 -> 6 shard 2 replicas), the left table in cluster2 can join with right table in cluster1?

There are 3 way to do Distributed joins. Double-distribution, Global, Local. The first 2 will work.
