### ISSUE TITLE
Transaction failed (Node exists) with no logs

### ISSUE THREAD

**Issue by thyn** [ClickHouse/ClickHouse#32997]
I have Transaction failed (Node exists) error every second. It exists in system.errors, but nothing in logs(console or files). Where to find full log message?

version 21.8.12.29

**Comment by den-crane** [comment]
Can you show copy/paste? I don't understand what you mean by "every second."

**Comment by den-crane** [comment]
Check zookeeper server logs, you should see more information about "Node exists"

**Comment by thyn** [comment]
<img width="1586" alt="image" src="https://user-images.githubusercontent.com/5173734/146964754-6cecff77-0fdc-485d-911d-d76a5a400382.png">

after some seconds

<img width="1703" alt="image" src="https://user-images.githubusercontent.com/5173734/146964814-d4388e81-8696-44a1-a100-89cda73bf264.png">

I will also recheck zookeeper and come back later

**Comment by den-crane** [comment]
It's a usability issue in CH.

system.errors should not register these errors because they are not errors

```
┌─name─────────────┬─code─┬─value─┬─────last_error_time─┬─last_error_message───────────
│ KEEPER_EXCEPTION │  999 │ 32315 │ 2021-12-21 17:37:08 │ Transaction failed (No node)
└──────────────────┴──────┴───────┴─────────────────────┴──────────────────────────────

┌─name─────────────┬─code─┬─value─┬─────last_error_time─┬─last_error_message───────────────┬
│ KEEPER_EXCEPTION │  999 │ 32318 │ 2021-12-21 17:37:35 │ Transaction failed (Node exists) │
└──────────────────┴──────┴───────┴─────────────────────┴──────────────────────────────────┴
```

**Comment by den-crane** [comment]
related https://github.com/ClickHouse/ClickHouse/issues/20048

**Comment by Mall0c** [comment]
Any update on this? Experiencing this as well.

**Comment by xiaokugua250** [comment]
me too ,how to resolve this ?
![1671246819777](https://user-images.githubusercontent.com/4617763/208221282-55742d8c-1b18-4cf9-8074-fe92776e5e44.png)
