### ISSUE TITLE
Missing part and paritions in zookeeper

### ISSUE THREAD

**Issue by thyn** [ClickHouse/ClickHouse#32996]
I have a table with partition key toMonday(date). Once (i don't remember when) It started erroring every 100 ms.

2021.12.18 13:49:52.798407 [ 285 ] {} <Warning> table .table (ReplicatedMergeTreePartCheckThread): Found the missing part 21060207_0_0_0 at 21060207_0_0_0 on ch-s1-b1
2021.12.18 13:49:52.817182 [ 125 ] {} <Warning> table .table (ReplicatedMergeTreePartCheckThread): Checking part 21060207_0_0_0
2021.12.18 13:49:52.819583 [ 125 ] {} <Warning> table .table (ReplicatedMergeTreePartCheckThread): Checking if anyone has a part 21060207_0_0_0 or covering part.

How to fix it?

is it safe to delete /block_numbers/21060207 in zookeeper? 

system.parts doesn't have that part . Filesystem too

Is it connected with 

https://github.com/ClickHouse/ClickHouse/pull/32445 ?

clickhouse version 21.8.12.29

**Comment by den-crane** [comment]
I guess you don't have data for 2106 year? 
Just execute `alter table .... frop partition id '21060207'`

**Comment by thyn** [comment]
>Just execute alter table .... frop partition id '21060207'
no it's not working, it says that's  ok bur errors are not stopping. I think problem is in zookeper. I don't have that part in clickhouse system.parts or drive.

**Comment by den-crane** [comment]
https://kb.altinity.com/upgrade/removing-lost-parts/

**Comment by thyn** [comment]
It's not clear for me how to fix it. After reading documentation version 21.8.12.29 is fixed. But I see that problem exists for me (from previous version I think). It's not clear how to fix it.

**Comment by genzgd** [comment]
Did you try dropping partition id '21060207'?  Can you post the relevant log messages from version 21.8.12?
