### ISSUE TITLE
 Create user haha host any can connect, create user haha host IP '10.0 0.0/24 'cannot connect to the remote connection, that is, the database cannot be accessed normally when the IP is specified.

### ISSUE THREAD

**Issue by lizhiyou88** [ClickHouse/ClickHouse#33003]
Create user haha host any can connect, create user haha host IP '156.0 0.0/24 'cannot connect to the remote connection, that is, the database cannot be accessed normally when the IP is specified.

version:21.12.2.17

 haha    │ 8c48b9ff-9d0d-a435-6ef0-5f28387c5789 │ local directory │ sha256_password │ {}          │ ['156.0.0.0/24'] │ []            │ []                │ []

[root@federated ~]# clickhouse-client -h xxxxx  -u haha --password
ClickHouse client version 21.12.2.17 (official build).
Password for user (haha): 
Connecting to 10.1.0.189:9000 as user haha.
Code: 516. DB::Exception: Received from 10.1.0.189:9000. DB::Exception: haha: Authentication failed: password is incorrect or there is no user with such name
. (AUTHENTICATION_FAILED)

**Comment by den-crane** [comment]
156.0.0.0 - is public IP.
10.1.0.189 - is private IP.

I guess you use a firewall / proxy with address translation.

156.0.0.0 -----> firewall translates address 156.0.0.0 to some 10.x.y.z address ------> CH server sees the client with 10.x.y.z

Check CH server logs for messages about incoming connections

**Comment by lizhiyou88** [comment]
sorry 我授权的ip地址是故意写成156.0 0.0/24，实际是10.0.0.0/24，
Sorry, the IP address I authorized was deliberately written as 156.0 0.0/24, but it was actually 10.0 0.0/24，

![image](https://user-images.githubusercontent.com/39184961/147022417-7f079454-9230-47ea-8567-a6a5eeddb27d.png)

**Comment by den-crane** [comment]
`10.1.0.189` <> `10.0.0.0/24` it's another network 

`10.0.0.0/24` ===  Usable Host IP Range: | 10.0.0.1 - 10.0.0.254  
https://www.calculator.net/ip-subnet-calculator.html?cclass=c&csubnet=24&cip=10.0.0.0&ctype=ipv4&printit=0&x=51&y=27

Should be or `10.1.0.0/24` or  other class for example /8

**Comment by lizhiyou88** [comment]
Thank you for my question. I didn't pay attention to this subnet. Thank you very much。
