### ISSUE TITLE
How to separate query errors from abnormal server errors? 

### ISSUE THREAD

**Issue by q0987** [ClickHouse/ClickHouse#3302]
Hello all,

The error log contains errors generated by invalid queries.
/var/log/clickhouse-server/clickhouse-server.err.log

> For example,
> 2018.10.04 09:40:26.422333 [ 21 ] <Error> HTTPHandler: Code: 396, e.displayText() = DB::Exception: Limit for result exceeded, max rows: 5.00 thousand, current rows: 16.38 thousand, e.what() = DB::Exception, Stack trace:
> 
> 

Question> Is there a config setting that I can use to store the query errors into a different log file?

Thank you

**Comment by alexey-milovidov** [comment]
Currently there is no way to do that. We have no classification of errors to server/user.
If you really need it, you can manually collect a set of specific error codes and grep them from error log.

**Comment by blinkov** [comment]
@q0987, do you have any further questions?

**Comment by blinkov** [comment]
Feel free to re-open the issue if it is still relevant.
