### ISSUE TITLE
Type mismatch for nested Column that has type Array(LowCardinality(String))

### ISSUE THREAD

**Issue by sulayliu** [ClickHouse/ClickHouse#33028]
when I added a new column of the nested table using the type: Array(LowCardinality(String)), then insert data without this new column, it will throw an exception, the steps as follow:

- 1. Initial table
```
  CREATE TABLE nested_test
  (
      `c1` UInt32,
      `c2` DateTime,
      `nest.col1` Array(String),
      `nest.col2` Array(Int8)
  )
  ENGINE = MergeTree
  ORDER BY (c1, c2);
```

- 2. populate some data before adding new element into the nested column structure
```
INSERT INTO nested_test (c1, c2, `nest.col1`, `nest.col2`)
SELECT * FROM generateRandom('c1 UInt32, c2 DateTime, `nest.col1` Array(String), `nest.col2` Array(Int8)') LIMIT 1000000;
```
- 3. adding new element 
```
ALTER TABLE nested_test 
    ADD COLUMN `nest.col3` Array(LowCardinality(String));
```
- 4. try to add the same data:
```
INSERT INTO nested_test (c1, c2, `nest.col1`, `nest.col2`)
SELECT * FROM generateRandom('c1 UInt32, c2 DateTime, `nest.col1` Array(String), `nest.col2` Array(Int8)') LIMIT 1000000;
```
**DB::Exception:**
- CH version 21.8.12 (the same exception in version 21.12.2.17): 
Received exception from server (version 21.8.12):
Code: 53. DB::Exception: Received from localhost:9000. DB::Exception: Type mismatch for column nest.col3. Column has type Array(LowCardinality(String)), got type Array(String). 

- CH version 21.11.6:
Received exception from server (version 21.11.6):
Code: 49. DB::Exception: Received from localhost:9000. DB::Exception: Block structure mismatch in  function connect between ConvertingTransform and MergeTreeSink stream: different types:
nest.col3 Array(String) Array(size = 0, UInt64(size = 0), String(size = 0))
nest.col3 Array(LowCardinality(String)) Array(size = 0, UInt64(size = 0), ColumnLowCardinality(size = 0, UInt8(size = 0), ColumnUnique(size = 1, String(size = 1)))). (LOGICAL_ERROR)

> when I use Array(String) instead of Array(LowCardinality(String)), insert successfully, or I added the new column with default value:
```
ALTER TABLE nested_test ADD COLUMN `nest.col3` Array(LowCardinality(String)) default arrayResize(CAST([], 'Array(LowCardinality(String))'), length(`nest.col1`));
```

**Comment by den-crane** [comment]
Works with Strings but not with LowCardinality(String)

>ALTER TABLE nested_test  ADD COLUMN `nest.col3` Array(String);

All Ok


>ALTER TABLE nested_test    ADD COLUMN `nest.col3` Array(LowCardinality(String));

Not Ok

**Comment by sulayliu** [comment]
Clickhouse Version: 21.3.17.2
Clickhouse Version: 21.3.18.4
Clickhouse Version: 21.3.19.1
Clickhouse Version: 21.7.10.4
Clickhouse Version: 21.7.11.3
Clickhouse Version: 21.8.6.15
Clickhouse Version: 21.8.7.22
Clickhouse Version: 21.8.8.29
Clickhouse Version: 21.8.9.13
Clickhouse Version: 21.8.10.19
Clickhouse Version: 21.8.11.4
Clickhouse Version: 21.8.12.29
Clickhouse Version: 21.9.2.17
Clickhouse Version: 21.9.4.35
Clickhouse Version: 21.9.5.16
Clickhouse Version: 21.9.6.24
Clickhouse Version: 21.10.2.15
Clickhouse Version: 21.10.3.9
Clickhouse Version: 21.10.4.26
Clickhouse Version: 21.10.5.3
Clickhouse Version: 21.11.2.2
Clickhouse Version: 21.11.3.6
Clickhouse Version: 21.11.4.14
Clickhouse Version: 21.11.5.33
Clickhouse Version: 21.11.6.7
Clickhouse Version: 21.11.7.9
Clickhouse Version: 21.12.2.17

these CK versions also throw the same exception:
Code: 49. DB::Exception: Block structure mismatch in  function connect between ConvertingTransform and MergeTreeSink stream: different types:

added default value on the Array(LowCardinality(String)) column, works well, no exception:
```
ALTER TABLE nested_test 
        MODIFY COLUMN `nest.col3` Array(LowCardinality(String)) DEFAULT arrayResize(CAST([], 'Array(LowCardinality(String))'), length(`nest.col1`));
```
