### ISSUE TITLE
Why can not the “modify setting” operation be synchronized to the other replica

### ISSUE THREAD

**Issue by zhanghuajieHIT** [ClickHouse/ClickHouse#33029]
If I modify setting in one replica, the other replica will not be modified synchronously.

```
void StorageReplicatedMergeTree::alter(
    const AlterCommands & commands, const Context & query_context, TableLockHolder & table_lock_holder)
{
    assertNotReadonly();

    auto table_id = getStorageID();

    if (commands.isSettingsAlter()) 
    {
        /// We don't replicate storage_settings_ptr ALTER. It's local operation.
        /// Also we don't upgrade alter lock to table structure lock.
        StorageInMemoryMetadata future_metadata = getInMemoryMetadata();
        commands.apply(future_metadata, query_context);

        merge_strategy_picker.refreshState();

        changeSettings(future_metadata.settings_changes, table_lock_holder);

        DatabaseCatalog::instance().getDatabase(table_id.database_name)->alterTable(query_context, table_id, future_metadata);
        return;
    }
 ...
}
```

Could you tell me why not the “modify setting” operation be synchronized to the other replica.

**Comment by den-crane** [comment]
Not any setting, but only storage settings. 
On the purpose. Storage can be different at replicas. 
One replica can have all data locally at NVME, other replica can have tiered storage NVME -> HDD -> S3

**Comment by zhanghuajieHIT** [comment]
supporting synchronization between replicas may be more convenient

**Comment by den-crane** [comment]
> supporting synchronization between replicas may be more convenient

All settings are synchronized except  storage settings. 
Deliberately. Other users need different storage configurations for replicas.

**Comment by zhanghuajieHIT** [comment]
ok, thanks
