### ISSUE TITLE
ontime dataset: Maybe Tail_Number should be of type String?

### ISSUE THREAD

**Issue by lingnancfy** [ClickHouse/ClickHouse#33031]
I use the ontime dataset to test the width table performance, but Import failed. Maybe Tail_Number should be of type String?

https://clickhouse.com/docs/zh/getting-started/example-datasets/ontime/

**Comment by den-crane** [comment]
Can you share more information ? Error? Data sample?

**Comment by lingnancfy** [comment]
I downloaded a portion of the ontime dataset:
-rw------- 1 root root 17937103 Dec 22 11:42 On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2021_1.zip
-rw------- 1 root root 16566293 Dec 22 11:42 On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2021_2.zip

Exception as follow:

> data]# ls -1 *.zip | xargs -I{} -P $(nproc) bash -c "echo {}; unzip -cq {} '*.csv' | sed 's/\.00//g' | $CLICKHOUSE_BIN/clickhouse client --host 192.168.0.135 --input_format_with_names_use_header=0 --query='INSERT INTO ontime FORMAT CSVWithNames'"
> On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2021_1.zip
> On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2021_2.zip
> Code: 27. DB::ParsingException: Cannot parse input: expected '"' before: 'N337PQ","4628",11193,1119302,33105,"CVG","Cincinnati, OH","KY","21","Kentucky",52,10721,1072102,30721,"BOS","Boston, MA","MA","25","Massachusetts",13,"0730","07': 
> Row 1:
> Column 0,   name: Year,                            type: UInt16,          parsed text: "2021"
> Column 1,   name: Quarter,                         type: UInt8,           parsed text: "1"
> Column 2,   name: Month,                           type: UInt8,           parsed text: "1"
> Column 3,   name: DayofMonth,                      type: UInt8,           parsed text: "2"
> Column 4,   name: DayOfWeek,                       type: UInt8,           parsed text: "6"
> Column 5,   name: FlightDate,                      type: Date,            parsed text: "2021-01-02"
> Column 6,   name: Reporting_Airline,               type: String,          parsed text: "<DOUBLE QUOTE>9E<DOUBLE QUOTE>"
> Column 7,   name: DOT_ID_Reporting_Airline,        type: Int32,           parsed text: "20363"
> Column 8,   name: IATA_CODE_Reporting_Airline,     type: String,          parsed text: "<DOUBLE QUOTE>9E<DOUBLE QUOTE>"
> Column 9,   name: Tail_Number,                     type: Int32,           parsed text: "<DOUBLE QUOTE>"ERROR
> Code: 27, e.displayText() = DB::ParsingException: Cannot parse input: expected '"' before: 'N337PQ","4628",11193,1119302,33105,"CVG","Cincinnati, OH","KY","21","Kentucky",52,10721,1072102,30721,"BOS","Boston, MA","MA","25","Massachusetts",13,"0730","07' (version 21.3.4.25)
> 
> : data for INSERT was parsed from stdin: (at row 1)
> 
> 
> Code: 27. DB::ParsingException: Cannot parse input: expected '"' before: 'N552NN","5581",11057,1105703,31057,"CLT","Charlotte, NC","NC","37","North Carolina",36,13851,1385103,33851,"OKC","Oklahoma City, OK","OK","40","Oklahoma",73,"13': 
> Row 1:
> Column 0,   name: Year,                            type: UInt16,          parsed text: "2021"
> Column 1,   name: Quarter,                         type: UInt8,           parsed text: "1"
> Column 2,   name: Month,                           type: UInt8,           parsed text: "2"
> Column 3,   name: DayofMonth,                      type: UInt8,           parsed text: "19"
> Column 4,   name: DayOfWeek,                       type: UInt8,           parsed text: "5"
> Column 5,   name: FlightDate,                      type: Date,            parsed text: "2021-02-19"
> Column 6,   name: Reporting_Airline,               type: String,          parsed text: "<DOUBLE QUOTE>OH<DOUBLE QUOTE>"
> Column 7,   name: DOT_ID_Reporting_Airline,        type: Int32,           parsed text: "20397"
> Column 8,   name: IATA_CODE_Reporting_Airline,     type: String,          parsed text: "<DOUBLE QUOTE>OH<DOUBLE QUOTE>"
> Column 9,   name: Tail_Number,                     type: Int32,           parsed text: "<DOUBLE QUOTE>"ERROR
> Code: 27, e.displayText() = DB::ParsingException: Cannot parse input: expected '"' before: 'N552NN","5581",11057,1105703,31057,"CLT","Charlotte, NC","NC","37","North Carolina",36,13851,1385103,33851,"OKC","Oklahoma City, OK","OK","40","Oklahoma",73,"13' (version 21.3.4.25)
> 
> : data for INSERT was parsed from stdin: (at row 1)
>

**Comment by lingnancfy** [comment]
> Can you share more information ? Error? Data sample?

I downloaded a portion of the ontime dataset:
-rw------- 1 root root 17937103 Dec 22 11:42 On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2021_1.zip
-rw------- 1 root root 16566293 Dec 22 11:42 On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2021_2.zip

Exception as follow:

> data]# ls -1 *.zip | xargs -I{} -P $(nproc) bash -c "echo {}; unzip -cq {} '*.csv' | sed 's/\.00//g' | $CLICKHOUSE_BIN/clickhouse client --host 192.168.0.135 --input_format_with_names_use_header=0 --query='INSERT INTO ontime FORMAT CSVWithNames'"
> On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2021_1.zip
> On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2021_2.zip
> Code: 27. DB::ParsingException: Cannot parse input: expected '"' before: 'N337PQ","4628",11193,1119302,33105,"CVG","Cincinnati, OH","KY","21","Kentucky",52,10721,1072102,30721,"BOS","Boston, MA","MA","25","Massachusetts",13,"0730","07': 
> Row 1:
> Column 0,   name: Year,                            type: UInt16,          parsed text: "2021"
> Column 1,   name: Quarter,                         type: UInt8,           parsed text: "1"
> Column 2,   name: Month,                           type: UInt8,           parsed text: "1"
> Column 3,   name: DayofMonth,                      type: UInt8,           parsed text: "2"
> Column 4,   name: DayOfWeek,                       type: UInt8,           parsed text: "6"
> Column 5,   name: FlightDate,                      type: Date,            parsed text: "2021-01-02"
> Column 6,   name: Reporting_Airline,               type: String,          parsed text: "<DOUBLE QUOTE>9E<DOUBLE QUOTE>"
> Column 7,   name: DOT_ID_Reporting_Airline,        type: Int32,           parsed text: "20363"
> Column 8,   name: IATA_CODE_Reporting_Airline,     type: String,          parsed text: "<DOUBLE QUOTE>9E<DOUBLE QUOTE>"
> Column 9,   name: Tail_Number,                     type: Int32,           parsed text: "<DOUBLE QUOTE>"ERROR
> Code: 27, e.displayText() = DB::ParsingException: Cannot parse input: expected '"' before: 'N337PQ","4628",11193,1119302,33105,"CVG","Cincinnati, OH","KY","21","Kentucky",52,10721,1072102,30721,"BOS","Boston, MA","MA","25","Massachusetts",13,"0730","07' (version 21.3.4.25)
> 
> : data for INSERT was parsed from stdin: (at row 1)
> 
> 
> Code: 27. DB::ParsingException: Cannot parse input: expected '"' before: 'N552NN","5581",11057,1105703,31057,"CLT","Charlotte, NC","NC","37","North Carolina",36,13851,1385103,33851,"OKC","Oklahoma City, OK","OK","40","Oklahoma",73,"13': 
> Row 1:
> Column 0,   name: Year,                            type: UInt16,          parsed text: "2021"
> Column 1,   name: Quarter,                         type: UInt8,           parsed text: "1"
> Column 2,   name: Month,                           type: UInt8,           parsed text: "2"
> Column 3,   name: DayofMonth,                      type: UInt8,           parsed text: "19"
> Column 4,   name: DayOfWeek,                       type: UInt8,           parsed text: "5"
> Column 5,   name: FlightDate,                      type: Date,            parsed text: "2021-02-19"
> Column 6,   name: Reporting_Airline,               type: String,          parsed text: "<DOUBLE QUOTE>OH<DOUBLE QUOTE>"
> Column 7,   name: DOT_ID_Reporting_Airline,        type: Int32,           parsed text: "20397"
> Column 8,   name: IATA_CODE_Reporting_Airline,     type: String,          parsed text: "<DOUBLE QUOTE>OH<DOUBLE QUOTE>"
> Column 9,   name: Tail_Number,                     type: Int32,           parsed text: "<DOUBLE QUOTE>"ERROR
> Code: 27, e.displayText() = DB::ParsingException: Cannot parse input: expected '"' before: 'N552NN","5581",11057,1105703,31057,"CLT","Charlotte, NC","NC","37","North Carolina",36,13851,1385103,33851,"OKC","Oklahoma City, OK","OK","40","Oklahoma",73,"13' (version 21.3.4.25)
> 
> : data for INSERT was parsed from stdin: (at row 1)
>

**Comment by den-crane** [comment]
```
https://clickhouse.com/docs/en/getting-started/example-datasets/ontime/
    `Tail_Number`                     String,

https://clickhouse.com/docs/zh/getting-started/example-datasets/ontime/
    `Tail_Number`                     Int32,
```
