### ISSUE TITLE
UDF in Rust

### ISSUE THREAD

**Issue by ilejn** [ClickHouse/ClickHouse#33038]
"Integrating Rust code into ClickHouse" is listed as an Intern Task for 21/22 booked by @BoloniniD .
What is the status of it, is it in progress?
Do we have a description or a mockup or anything?

**Comment by BoloniniD** [comment]
It is still in progress. Currently, I'm trying to make BLAKE3 FFI-compatible to use its functions and methods in a local C++ "hello world" project. When it's finished, I am going to start integrating it into ClickHouse.
