### ISSUE TITLE
In prod ,it is a nightmare to see OOM everyday. Can anyone please help ?

### ISSUE THREAD

**Issue by DipalPrajapati** [ClickHouse/ClickHouse#33040]
I am getting OOM for the query which does take only 8 gb memory  in processlist , but gives OOM (total) .

I am having 2 node cluster each with 62 GB in productions. 

- Max memory usage -> fully available , set to 0 , tried with 62 GB no luck ! 
- reduced mark cache -> did not help .
- Dropped cache -> did not help . 
- set max_memory_usage_for_user to 62 gb , did not help. 

`auto DB::StorageReplicatedMergeTree::processQueueEntry(ReplicatedMergeTreeQueue::SelectedEntryPtr)::(anonymous class)::operator()(DB::StorageReplicatedMergeTree::LogEntryPtr &) const: Code: 241, e.displayText() = DB::Exception: Memory limit (total) exceeded: would use 125.50 GiB (attempt to allocate chunk of 5390352 bytes), maximum: 125.50 GiB: (while reading column imsi): (while reading from part /data/clickhouse/store/1a5/1a5b5ea1-4183-40a2-bd98-b51f99e37b99/all_1650_2401_545/ from mark 4 with max_rows_to_read = 8192): While executing MergeTreeSequentialSource, Stack trace (when copying this message, always include the lines below):`

`eceived exception from server (version 20.12.5):
Code: 241. DB::Exception: Received from node:9000. DB::Exception: Memory limit (total) exceeded: would use 125 GiB (attempt to allocate chunk of 5413332 bytes), maximum: 125 GiB: (while reading column msisdn): (while reading from part /data/clickhouse/store/730/730a7756-bfca-4ffe-a22c-c0c853d9ce65/all_0_807_647/ from mark 2022 with max_rows_to_read = 8192): While executing MergeTreeThread. `

This is giving 125 as i have set max_memory_ram_ratio.. to 2 . but even if I reduced to 0.9 , it remains stuck only due to oom. 
![Screenshot (222)](https://user-images.githubusercontent.com/3430373/147079384-7ba4d9dc-c508-4306-a3af-125e80da4ae2.png)

I am not able to query past records at least . 
Total records : 33 Million 

**select * from table** is also not working.

`SELECT
    metric,
    formatReadableSize(value)
FROM system.asynchronous_metrics

Query id: 6ddc1d69-3196-46de-aa75-84547b7cab6f

┌─metric───────────────────────────────────┬─formatReadableSize(value)─┐
│ CPUFrequencyMHz_11                       │ 2.34 KiB                  │
│ CPUFrequencyMHz_9                        │ 2.34 KiB                  │
│ CPUFrequencyMHz_0                        │ 2.34 KiB                  │
│ jemalloc.arenas.all.pactive              │ 109.68 KiB                │
│ jemalloc.arenas.all.pmuzzy               │ 94.52 KiB                 │
│ jemalloc.arenas.all.pdirty               │ 353.71 KiB                │
│ CPUFrequencyMHz_1                        │ 2.34 KiB                  │
│ jemalloc.background_thread.run_intervals │ 0.00 B                    │
│ jemalloc.background_thread.num_runs      │ 0.00 B                    │
│ jemalloc.retained                        │ 6.31 GiB                  │
│ MemoryVirtual                            │ 9.93 GiB                  │
│ jemalloc.mapped                          │ 2.24 GiB                  │
│ jemalloc.resident                        │ 2.21 GiB                  │
│ jemalloc.metadata                        │ 34.09 MiB                 │
│ jemalloc.allocated                       │ 423.55 MiB                │
│ CPUFrequencyMHz_6                        │ 2.34 KiB                  │
│ ReplicasMaxAbsoluteDelay                 │ 0.00 B                    │
│ jemalloc.epoch                           │ 16.00 B                   │
│ CPUFrequencyMHz_5                        │ 2.34 KiB                  │
│ jemalloc.active                          │ 438.73 MiB                │
│ NumberOfTables                           │ 159.00 B                  │
│ Uptime                                   │ 888.00 B                  │
│ MemoryResident                           │ 1.38 GiB                  │
│ NumberOfDatabases                        │ 4.00 B                    │
│ CPUFrequencyMHz_7                        │ 2.34 KiB                  │
│ jemalloc.background_thread.num_threads   │ 0.00 B                    │
│ MaxPartCountForPartition                 │ 17.00 B                   │
│ UncompressedCacheBytes                   │ 0.00 B                    │
│ CPUFrequencyMHz_8                        │ 2.34 KiB                  │
│ CPUFrequencyMHz_10                       │ 2.34 KiB                  │
│ ReplicasSumQueueSize                     │ 4.00 B                    │
│ jemalloc.arenas.all.dirty_purged         │ 21.55 MiB                 │
│ MemoryShared                             │ 35.89 MiB                 │
│ jemalloc.metadata_thp                    │ 0.00 B                    │
│ ReplicasMaxMergesInQueue                 │ 2.00 B                    │
│ MemoryCode                               │ 290.13 MiB                │
│ ReplicasMaxQueueSize                     │ 2.00 B                    │
│ jemalloc.arenas.all.muzzy_purged         │ 13.80 MiB                 │
│ MarkCacheBytes                           │ 256.33 KiB                │
│ ReplicasMaxInsertsInQueue                │ 0.00 B                    │
│ ReplicasMaxRelativeDelay                 │ 0.00 B                    │
│ CPUFrequencyMHz_4                        │ 2.34 KiB                  │
│ UncompressedCacheCells                   │ 0.00 B                    │
│ ReplicasSumInsertsInQueue                │ 0.00 B                    │
│ CompiledExpressionCacheCount             │ 0.00 B                    │
│ ReplicasSumMergesInQueue                 │ 4.00 B                    │
│ CPUFrequencyMHz_2                        │ 2.34 KiB                  │
│ CPUFrequencyMHz_3                        │ 2.34 KiB                  │
│ MarkCacheFiles                           │ 10.00 B                   │
│ MemoryDataAndStack                       │ 9.25 GiB                  │
└──────────────────────────────────────────┴───────────────────────────┘

50 rows in set. Elapsed: 0.002 sec. 
`

**Comment by UnamedRus** [comment]
> I am getting OOM for the query which does take only 8 gb memory in processlist , but gives OOM (total) .

OOM total does mean, that ALL queries took 125GB of RAM.

Which ClickHouse version?

https://kb.altinity.com/altinity-kb-setup-and-maintenance/altinity-kb-who-ate-my-memory/

**Comment by DipalPrajapati** [comment]
Hi  , no a single query is giving this exception. 
version 20.12 
I already visited this page and found the process memory for the query goes till 8 gb and merges increases and decreases from 20 Gib to 131 Gib

**Comment by den-crane** [comment]
20.12 is out of support.

Can you share for that table

```
SELECT
    database,
    table,
    column,
    formatReadableSize(sum(column_data_compressed_bytes) AS size) AS compressed,
    formatReadableSize(sum(column_data_uncompressed_bytes) AS usize) AS uncompressed,
    round(usize / size, 2) AS compr_rate,
    sum(rows) rows_cnt,
    round(avg(column_data_uncompressed_bytes/rows),2) avg_row_size
FROM system.parts_columns
WHERE (active = 1) AND (table LIKE '...........')
GROUP BY
    database,
    table,
    column
ORDER BY size DESC;

```
