### ISSUE TITLE
Multi-table get interface in IDatabase and caching storages in Context. 

### ISSUE THREAD

**Issue by DimasKovas** [ClickHouse/ClickHouse#33055]
**Use case**

Getting StoragePtr can be expensive (in our case it's a remote request to fetch table structure).
When there are multiple tables in one query, all of them are fetched sequentially. It leads to a long query preparation (up to several seconds).

The fact that ClickHouse can call 'getTable' several times for one table during query processing make the situation even worse.

The goal is to fetch all used tables only once in parallel.

**Describe the solution you'd like**

The IDatabase has following interface:
`std::vector<DB::StoragePtr> tryGetTables(const DB::Names& names, DB::ContextPtr context)`

Before query processing, ClickHouse collects all table names used in query and fetches them via tryGetTables. Then it stores storages in Context, so it can access them any time without creating new storage.

**Describe alternatives you've considered**

Another possible solution is to make an asynchronous interface for getting tables. (+caching in Context as described above)

**Additional context**

The task is requested by Yandex.

**Comment by alexey-milovidov** [comment]
This should be easy to implement. If you want, you can submit a PR.
PS. I did not see any cases when `getTable` method can be slow. I also did not see this method in cluster-wide performance profiles. Looks like it is relevant only for modified ClickHouse species.

**Comment by alexey-milovidov** [comment]
It wasn't done.
