### ISSUE TITLE
Antlr grammar analysis failure 

### ISSUE THREAD

**Issue by oywy** [ClickHouse/ClickHouse#33068]
Hello team, I found that some SQL statements could not be parsed by ANTLR.
For example, the INTERSECT and EXCEPT clauses from the documents.
https://clickhouse.com/docs/en/sql-reference/statements/select/intersect/
https://clickhouse.com/docs/en/sql-reference/statements/select/except/
>  SELECT * FROM t1 EXCEPT SELECT * FROM t2;

This parse tree stops at EXCEPT as an alias.
![image](https://user-images.githubusercontent.com/15909766/147177430-48c71d24-e839-477f-be6a-cdcdd0757180.png)

The Lexer does not contain the Keywords: INTERSECT and EXCEPT.

The similar situations also happen in following sql statement examples:
https://clickhouse.com/docs/en/sql-reference/statements/select/#select-clause
https://clickhouse.com/docs/en/sql-reference/statements/select/distinct/
> SELECT DISTINCT ON (a,b) * FROM t1;

t1 is recognized as an alias not a table in this case.
![image](https://user-images.githubusercontent.com/15909766/147178163-3f5bcbe9-8506-4069-a895-43aee6451d09.png)

I want to use the ANTLR to parse the ClickHouse sql statement, could the team please give some advices?

**Comment by alexey-milovidov** [comment]
We don't update ANTLR grammar, now it is unsupported.
We accept the contributions to make it up to date.
