### ISSUE TITLE
Scale vertical realtime

### ISSUE THREAD

**Issue by phamtai97** [ClickHouse/ClickHouse#33071]
Hi all.
I have a question related to scale vertical for ClickHouse. Can we add more RAM/CPU/Disk to server deploy ClickHouse realtime? And what risks does it have? If you have the documents to guide scale vertical, you can send me the link documents.

I saw the link: https://www.slideshare.net/Altinity/webinar-strength-in-numbers-introduction-to-clickhouse-cluster-performance
<img width="536" alt="Screen Shot 2021-12-23 at 13 44 37" src="https://user-images.githubusercontent.com/38773351/147199809-162d5220-c757-40f1-becf-ebe9d6d42695.png">

**Comment by phamtai97** [comment]
@alexey-milovidov Can you help me?

**Comment by alexey-milovidov** [comment]
Yes, you can scale up your servers and ClickHouse will use the hardware resources.

Typically it is done this way:
- shutdown one replica;
- add more hardware resources to it;
- bring the replica back online;
- repeat with other replicas.

This provide the way to change hardware configuration without downtime.

In it even more easy if you use cloud machines. You just attach the volume to a bigger machine or add more volumes.

**Comment by alexey-milovidov** [comment]
It is also possible to add more disks to a physical server without reboot.

First you add more physical disks to the server by hotswap capabilities. Do some device rescan command in Linux. Format partitions, create a filesystem as needed and mount it. Then edit the clickhouse-server config for `storage_configuration`. And tables will be able to use the new disks on the fly.

**Comment by phamtai97** [comment]
Tks for your answer. 
So, If we shutdown the replicated node, it maybe lost data because it was not replicated data from other node that is the same shard. So, then when it is restart, Do we lose data?

**Comment by phamtai97** [comment]
Tks for your answer.
