### ISSUE TITLE
how to skip error when pushing to view?

### ISSUE THREAD

**Issue by wangqinghuan** [ClickHouse/ClickHouse#33094]
1. create source table

```
create table hb_community_face_recognition_kafka
(
root   String
)engine = Kafka 
  ...
```

2. create target table
```
create table hb_community_face_recognition_origin
(
InfoID Nullable(String),
ShotTime DateTime,
DeviceID Nullable(String),
StorageUrl1 Nullable(String),
StorageUrl2 Nullable(String),
StorageUrl3 Nullable(String),
StorageUrl4 Nullable(String),
StorageUrl5 Nullable(String),
CommunityID Nullable(String),
IDNumber Nullable(String),
Name Nullable(String),
IDType Nullable(String),
DataSourceID Nullable(String),
_topic Nullable(String),
_insertTime Nullable(DateTime),
_timestamp Nullable(Int64)
)
ENGINE = MergeTree
 ...

```
3. create materialize view, push data from source to target
CREATE MATERIALIZED VIEW hb_community_face_recognition_origin_mv to hb_community_face_recognition_origin
AS
select InfoID, 
         ShotTime,
         DeviceID,
         StorageUrl1,
         StorageUrl2,
         StorageUrl3,
         StorageUrl4,
         StorageUrl5,
         CommunityID,
         IDType,
         IDNumber,
         Name, 
         DataSourceID, 
        _topic, 
        _insertTime,
        _timestamp from (
                            select  root,
                                      JSONExtractRaw(root,'body') as body,
                                      JSONExtractString(body,'InfoID') as InfoID,
                                      JSONExtractString(body,'ShotTime') as ShotTime,
                                      JSONExtractString(body,'DeviceID') as DeviceID,
                                      JSONExtractString(body,'StorageUrl1') as StorageUrl1,
                                      JSONExtractString(body,'StorageUrl2') as StorageUrl2,
                                      JSONExtractString(body,'StorageUrl3') as StorageUrl3,
                                      JSONExtractString(body,'CommunityID') as CommunityID,
                                      JSONExtractString(body,'StorageUrl4') as StorageUrl4,
				      JSONExtractString(body,'StorageUrl5') as StorageUrl5,
                                      JSONExtractString(body,'IDNumber') as IDNumber,
				      JSONExtractString(body,'IDType') as IDType,
                                      JSONExtractString(body,'Name') as Name,
                                      JSONExtractString(body,'DataSourceID') as DataSourceID,
                                      _topic,
                                      now() as _insertTime,
				      _timestamp
                               from hb_community_face_recognition_kafka
);
4. some exception like 'cannot parse datetime' stalled prcocessing  when pushing to view hb_community_face_recognition_origin_mv. How to skip these exeception (broken data) when pushing to materialize view?

**Comment by den-crane** [comment]
use toDateTimeOrNull

```
SELECT toDateTime('')
Cannot parse datetime: Cannot parse DateTime from String

 select toDateTimeOrNull('');
┌─toDateTimeOrNull('')─┐
│                 ᴺᵁᴸᴸ │
└──────────────────────┘

```
