### ISSUE TITLE
dictionaries SOURCE(POSTGRESQL(...)) doesn't work

### ISSUE THREAD

**Issue by zotann** [ClickHouse/ClickHouse#33095]
**Describe the bug**
XML and SQL definition for PostgreSQL external dictionaries successful created, but doesn't load data

**Does it reproduce on recent release?**
Yes

**How to reproduce**

ClickHouse server version to use 21.12.2.17 (official build)

CREATE TABLE statements for all tables involved
/etc/clickhouse-server/pg_dictionary.xml

```
<clickhouse>
    <dictionary> 
        <name>pg</name>
        <structure>
            <key>
                <attribute>
                    <name>id</name>
                    <type>UInt64</type>
                </attribute>
            </key>
            <attribute>
                <name>name</name>
                <type>String</type>
                <null_value></null_value>
            </attribute>
        </structure>
        <source>
            <postgresql>
                <host>pg_host</host>
                <port>5432</port>
                <user>postgres</user>
                <password>pg_pass</password>
                <database>olap2</database>                              
                <table>public.src_ind</table>                          
                <where>id=1</where>
                <invalidate_query>SELECT now()</invalidate_query>                 
            </postgresql>
        </source>
        <layout>
            <complex_key_hashed/>
        </layout>
        <lifetime>
            <min>10</min>
            <max>20</max>
        </lifetime>
    </dictionary>
</clickhouse>
```

**Table fro PostgreSQL**
![image](https://user-images.githubusercontent.com/81733979/147214691-a8b8b72a-facb-46b6-b206-777f8fbb9bae.png)

**Queries to run that lead to unexpected result**
` select  dictGetString('pg', 'name',1)`

**Error message** 
SELECT dictGetString('pg','name',toUInt16(1))

![image](https://user-images.githubusercontent.com/81733979/147223104-2574ff96-c1b5-45c5-bbaf-3d69d7b75bd3.png)

Code: 156. DB::Exception: Failed to load dictionary 'pg': std::exception. Code: 1001, type: pqxx::undefined_table, e.what() = ERROR:  relation "public.src_ind" does not exist. LINE 1: COPY (SELECT "id", "name" FROM "public"."src_ind" WHERE id=1... ,. (DICTIONARIES_WAS_NOT_LOADED) (version 21.12.2.17 (official build))

**Comment by alexey-milovidov** [comment]
`existLINE` - missing whitespace is not good.

**Comment by zotann** [comment]
> `existLINE` - missing whitespace is not good.

Where missing whitespace?

**Comment by zotann** [comment]
> > `existLINE` - missing whitespace is not good.
> 
> Where missing whitespace?

How to fix it?

**Comment by zotann** [comment]
Tried a lot of things.

 SELECT dictGetString('pg','name',toUInt16(1))
![image](https://user-images.githubusercontent.com/81733979/147222611-e554ae4e-6277-4be7-95c5-e56c7e50026e.png)
 SELECT dictGetString('pg','name',tuple(1))
![image](https://user-images.githubusercontent.com/81733979/147222643-0492f772-8cfc-469a-88f2-d2a2f02454f3.png)

**Comment by kssenii** [comment]
What if you remove public from here `<table>public.src_ind</table>`? By default it anyway uses default schema

**Comment by zotann** [comment]
Removed the name of the circuits. The error remains
 
![image](https://user-images.githubusercontent.com/81733979/147224814-0e98ca60-baa7-4e5f-8f53-9b3defea1125.png)

**Comment by kssenii** [comment]
Strange.. Can you try the same configuration with table function? like this `select * from postgresql('host:port', 'database_name', 'table_name', 'username', 'password')`

**Comment by zotann** [comment]
> What if you remove public from here `<table>public.src_ind</table>`? By default it anyway uses default - public - schema

If it did help, then it is not a good solution. I have over 200 circuits. I will not transfer all tables to the public scheme.

**Comment by kssenii** [comment]
>  I will not transfer all tables to the public scheme.

No need, non default schema works well (I've seen users used it already and also there are tests for that). Just your case does not seem to work.

**Comment by kssenii** [comment]
> like this select * from postgresql('host:port', 'database_name', 'table_name', 'username', 'password')

Also schema can be added as the last parameter (after password), check this also probably.

**Comment by zotann** [comment]
> select * from postgresql('host:port', 'database_name', 'table_name', 'username', 'password')

This good
![image](https://user-images.githubusercontent.com/81733979/147225552-f87b27a4-778f-4272-bc6b-e74d4919db57.png)

**Comment by zotann** [comment]
> No need, non default schema works well (I've seen users used it already and also there are tests for that). Just your case does not seem to work.

I have tried on other circuits. Does not work. How to fix it? How to make it work? Can I put another version clickHouse?

**Comment by zotann** [comment]
> > like this select * from postgresql('host:port', 'database_name', 'table_name', 'username', 'password')
> 
> Also schema can be added as the last parameter (after password), check this also probably.

select * from postgresql(..., [scheme]) - Its good. 
![image](https://user-images.githubusercontent.com/81733979/147226146-a619770d-6ae9-4098-803b-f3c29122f04f.png)

But through xml error.

**Comment by zotann** [comment]
Tried adding quotes to <table>"public"."src_ind"</table>. Escaped quotes. Added the <schema> tag. Added the <scheme> tag.

**Comment by kssenii** [comment]
Try `<db>olap2</db>` instead of `<database>olap2</database>      `

**Comment by zotann** [comment]
> Try `<db>olap2</db>` instead of `<database>olap2</database>`

Thank you. Everything works well `<db> olap2 </db>`

**Comment by alexey-milovidov** [comment]
@kssenii We should provide good error message if unexpected elements have found in configuration file.
