### ISSUE TITLE
The data are not distruted across the Shards, how to achieve it? 

### ISSUE THREAD

**Issue by surajmachamasi** [ClickHouse/ClickHouse#33096]
i have two shards up and running, the data pulled via kafka server are  not distributed across the shards. only shard 1 gets all the data but shards 2 is not receiving any  data. is there any way to configure this ?

**Comment by den-crane** [comment]
Provide: 
1. Where and how kafka tables created + tables + MaterializedViews (create table ... )
2. How your remote_servers section is configured.
3. How your macros are configured on each server.

**Comment by surajmachamasi** [comment]
the clickhouse is configured in the default configuration in kubernetes cluster.

**Comment by den-crane** [comment]
there is no such entity like " default configuration in kubernetes cluster."

**Comment by surajmachamasi** [comment]
> 2\. How your remote_servers section is configured.

      <yandex>
          <remote_servers>
              
              <prdc01>
                  <shard>
                      <internal_replication>true</internal_replication>
                      <replica>
                          <host>chi-repl-prod-prdc01-0-0</host>
                          <port>9000</port>
                      </replica>
                      <replica>
                          <host>chi-repl-prod-prdc01-0-1</host>
                          <port>9000</port>
                      </replica>
                  </shard>
                  <shard>
                      <internal_replication>true</internal_replication>
                      <replica>
                          <host>chi-repl-prod-prdc01-1-0</host>
                          <port>9000</port>
                      </replica>
                      <replica>
                          <host>chi-repl-prod-prdc01-1-1</host>
                          <port>9000</port>
                      </replica>
                  </shard>
              </prdc01>
              
              <all-replicated>
                  <shard>
                      <internal_replication>true</internal_replication>
                      <replica>
                          <host>chi-repl-prod-prdc01-0-0</host>
                          <port>9000</port>
                      </replica>
                      <replica>
                          <host>chi-repl-prod-prdc01-0-1</host>
                          <port>9000</port>
                      </replica>
                      <replica>
                          <host>chi-repl-prod-prdc01-1-0</host>
                          <port>9000</port>
                      </replica>
                      <replica>
                          <host>chi-repl-prod-prdc01-1-1</host>
                          <port>9000</port>
                      </replica>
                  </shard>
              </all-replicated>
              <all-sharded>
                  <shard>
                      <internal_replication>false</internal_replication>
                      <replica>
                          <host>chi-repl-prod-prdc01-0-0</host>
                          <port>9000</port>
                      </replica>
                  </shard>
                  <shard>
                      <internal_replication>false</internal_replication>
                      <replica>
                          <host>chi-repl-prod-prdc01-0-1</host>
                          <port>9000</port>
                      </replica>
                  </shard>
                  <shard>
                      <internal_replication>false</internal_replication>
                      <replica>
                          <host>chi-repl-prod-prdc01-1-0</host>
                          <port>9000</port>
                      </replica>
                  </shard>
                  <shard>
                      <internal_replication>false</internal_replication>
                      <replica>
                          <host>chi-repl-prod-prdc01-1-1</host>
                          <port>9000</port>
                      </replica>
                  </shard>
              </all-sharded>
          </remote_servers>
      </yandex>
    chop-generated-settings.xml: |
      <yandex>
          <prometheus>
              <asynchronous_metrics>true</asynchronous_metrics>
              <endpoint>/metrics</endpoint>
              <events>true</events>
              <metrics>true</metrics>
              <port>8888</port>
          </prometheus>
      </yandex>





> 3\. How your macros are configured on each server.

     <yandex>
            <macros>
                <installation>repl-prod</installation>
                <all-sharded-shard>0</all-sharded-shard>
                <cluster>prdc01</cluster>
                <shard>0</shard>
                <replica>chi-repl-prod-prdc01-0-0</replica>
            </macros>
        </yandex>
