### ISSUE TITLE
Secondary indexes operations with IN, Join, Dictionary, Views and various Table Engines

### ISSUE THREAD

**Issue by healiseu** [ClickHouse/ClickHouse#3310]
Hi, suppose we have this standard join operation between two MergeTree tables
```sql
    CREATE TABLE BicycleTripStar
    (
        duration UInt32, 
        start_date DateTime, 
        end_date DateTime, 
        start_station_id UInt8, merge tree 
        end_station_id UInt8, 
        bike_id UInt16, 
        member_id UInt8
    )
    ENGINE = MergeTree() 
    PARTITION BY toYYYYMM(start_date)
    ORDER BY (start_date, end_date)
    SETTINGS index_granularity = 81

    CREATE TABLE StartStation
    (        
        ndx UInt16, 
        name String,
        id UInt8 
    )
    ENGINE = MergeTree()
    ORDER BY (ndx, name)
    SETTINGS index_granularity = 8192
```
And this is a typical query to test the normal sql join
```sql
    SELECT 
        StartStation.name, 
        count(*) AS trips
    FROM BicycleTripStar 
    ANY INNER JOIN StartStation ON BicycleTripStar.start_station_id = StartStation.id
    WHERE member_id = 1
    GROUP BY StartStation.name
    HAVING trips < 10
    ORDER BY trips DESC
```
I want to rewrite this query using Clickhouse Join engine. First I created this table
```sql
    CREATE TABLE StartStationRAM
    (        
        ndx UInt16, 
        name String,
        id UInt8 
    )
    ENGINE = Join(ANY, INNER, id)
```
clickhouse-server accepted this without any error.
Then I tried the following query
```sql
SELECT 
    StartStationRAM.name, 
    count(*) AS trips
FROM BicycleTripStar 
ANY INNER JOIN StartStationRAM ON BicycleTripStar.start_station_id = StartStation.id
WHERE member_id = 1
GROUP BY StartStation.name
HAVING trips < 10
ORDER BY trips DESC
```
without any luck 
```txt
Received exception from server (version 18.12.17):
Code: 47. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Unknown identifier: StartStation.id.
```
Where is my mistake ? What is the right way to use Clickhouse `Join ENGINE` and can you explain where is the advantage compared to a normal `SQL Join` ?

Can you do the same please to demonstrate with an example the differences between a Set engine and the IN operator and explain its advantageous point ?

**Comment by iFoton** [comment]
Try to change `ON BicycleTripStar.start_station_id = StartStation.id` to `ON BicycleTripStar.start_station_id = StartStation**RAM**.id`, and in group by clause same.

**Comment by filimonov** [comment]
The idea behind that is quite simple. For using some data as right part of join (or as set of values for IN operaror) data should be read from disk (with preproseccibg if needed) and put in RAM in special memory structures (like hash tables). 

If you need to make a lot of requests with the same right part of the join (or with the same set of values for IN operator) you will need to do the same job a lot of times. But if you can ask clickhouse to not remove that preprocessed data from memory you can use it again and again in all your selects.

So engine join and engine set is just a way to name and cache the intermediate structures which Clickhouse create for execucuting IN / JOIN operations for future reuse.

You can find some samples of usage in tests: https://github.com/yandex/ClickHouse/search?l=SQL&q=engine+join&type=

**Comment by healiseu** [comment]
@iFoton thanks, I got confused with naming, Start* and *Star, so I hope this is the correct syntax
```sql
SELECT 
    StartStationRAM.name, 
    count(*) AS trips
FROM BicycleTripStar 
ANY INNER JOIN StartStationRAM ON BicycleTripStar.start_station_id = StartStationRAM.id
WHERE member_id = 1
GROUP BY StartStationRAM.name
HAVING trips < 10
ORDER BY trips DESC
```
but this time I got  a different DB::Exception
` DB::Exception: Not found column id in block. There are only columns: start_station_id`

I am not sure if this error is related to how I load data on the table, i.e.
```bash
cat 2011-tripdata-start_station.csv | clickhouse-client --database=DemoDB --query="INSERT INTO StartStationRAM FORMAT CSV"

head 2011-tripdate-start_station.csv

"31000","10th & Monroe St NE","0"
"31001","10th & U St NW","1"
"31002","10th St & Constitution Ave NW","2"
```

**Comment by healiseu** [comment]
@filimonov I think I got it, it's a hash join cashed in memory. That's a great idea you made this feature separable too in clickhouse. Thank you also for the link on how to search for examples on its usage. 

May I also ask you about the other kind of engine you have the Dictionary and how this is compared with the Join Engine. In the documentation I found there is a hashed type of dictionary in memory. And I noticed the following differences:

1. Dictionaries can be reloaded in RAM from source tables on the disk
2. Dictionaries do not allow NULLs
3. Dictionaries have more memory data structure types
  i. packed arrays (i.e. the new LowCardinality(T) data type ???)
 ii. unpacked arrays (i.e. flat array)
 iii. hashed
 iv. etc...

Is that all, do you find the above disposition accurate ?

Finally, although I have never got into a depth to view how an SQL optimizer works under the hood, it seems all these tools/features of the engine you provide makes it easier for someone to build his own optimizer or tune the engine any way he likes, and that is absolutely fabulous.

**Comment by filimonov** [comment]
> May I also ask you about the other kind of engine you have the Dictionary and how this is compared with the Join Engine. 

The biggest difference is that dictionaries have completely another syntax, and rather another usage scenarios. They are handier for scenarios like "get value by id", "create some derived column from existing column", more universal (you can use them in any part of query), and more widely used as they also allow to use some data from outside of ClickHouse (files / webservices / mysql / odbc). While `Set` / `Join` are very specific and each is able to help in very concrete scenarios.

Some examples:
1) you have the dictionary which translates postal codes to city names (by stored lets say in a webservice). After that you don't need to do any joins just write something like 
```dictGetString('postal_codes','city_name',toUInt64(postal_code_value))```
2) you need to initially find some specific group of users, which satisfy some complicated requirements and make 30 different selects passing those `userids` as a filter for IN expression. So instead of filtering them again and again, it would be better to put them inside `Engine=Set` table 
3) You need to execute some select with join every minute, left part of that table is incrementing block, the right part have > 1 columns and is always the same. You can put the right part into `Engine=Join` table. 

> Dictionaries CAN NOT be reloaded in RAM from source tables on the disk

That's not true. You can [configure](https://clickhouse.yandex/docs/en/query_language/dicts/external_dicts_dict_lifetime/#dicts-external_dicts_dict_lifetime) dictionary lifetime. Or just call manually force the reload by `SYSTEM RELOAD DICTIONARY <dictionary_name>` or `SYSTEM RELOAD DICTIONARIES` (for reloading all configured dicts). Those commands have no documentation yes (see #2511).

> Finally, although I have never got into a depth to view how an SQL optimizer works under the hood, it seems all these tools/features of clickhouse engine you provide makes it easier for someone to build his own optimizer or tune the engine any way he likes, and that is absolutely fabulous. I guess this is also reflected in the architectural design of clickhouse. 

Clickhouse has a quite primitive internal optimizer, but it compensates lack of smart optimizations by giving a lot of tools and building blocks to make manual optimizations possible, I also like that very much. Kudos to @alexey-milovidov  and Yandex team :+1:

**Comment by healiseu** [comment]
@filimonov I take your points, I still have little experience with clickhouse but I like a lot their architectural design and user features that's why I am here after all trying to learn more. From the user point of view I think what it's missing here is some better connection of clickhouse tools, i.e. building blocks, with what is commonly known in the DBMS jargon as secondary indexes and from the search engine point of view the inverted index. The most effective way to demonstrate these differences/similarities is through simple examples, use cases.

**Comment by filimonov** [comment]
AFAIK there are some plans/ ideas of introducing 'some kind' of secondary indexes.

Right now there is an option to have an extra copy of same data (or some subset) with another PK (it can take a lot of disk space, but if you really need it - it's doable) via the materialized view.

> The most effective way to demonstrate these differences/similarities is through simple examples, use cases. 

You can also help a community by sharing knowledge, creating articles, publishing comparisons, providing examples and improving docs to make ClickHouse even better :)

**Comment by healiseu** [comment]
To be more specific and to understand that we speak the same language, I am referring to **secondary indexes that improve the join operations**, not the clustered/non-clustered indexes which, if I understand it correctly, Clickhouse developers have solved to a great extend with their LSM MergeTree engines. 

In fact the reason I am interested in join, dictionary, etc features is that I have developed and demonstrated a technique where you can extrapolate a hypergraph from any set of tables that share common columns. I called the technique [Associative-Semiotic-Hypergraph][1] and it is based on applying set operations on a kind of dictionary columns the associative way. 

This is similar to the [associative style of processing data][2], i.e. Qlik associative engine. It was invented in the 90's. As far as I know there has never been an open-source project with similar features. I would like to see that happen but I need backup. If you wish we can arrange an online meeting for this. For those that are not aware what we are talking about, Qlik technology products are the only products in the market with truly ad hoc queries on non-aggregated data. This feature was the main goal of developing Click-house according to @alexey-milovidov.

[1]: http://healis.eu/triadb/
[2]: https://community.qlik.com/blogs/qlikviewdesignblog/2012/11/20/symbol-tables-and-bit-stuffed-pointers

**Comment by filimonov** [comment]
Pointers to external fact tables sounds pretty similar to well known [star schema](https://en.m.wikipedia.org/wiki/Star_schema). Am I right?

Storing values which are not byte/word aligned can give better compression but can also be less CPU effective for processing.

About qlick and supergraphs - i don't feel i have enough experience in that field to comment that.

**Comment by healiseu** [comment]
@filimonov it is a star schema only that it can be extended with as many tables as you like. This is achieved by creating a model, i.e. schema of tables and fields, I call them entities and attributes to keep consistency with the ER diagram. The trick here is to give numerical addresses to everything including the distinct values of each field and the rows of each table. Then you perform set operations to achieve joins and you take advantage of the numerical addressing that connects everything together.

**Comment by filimonov** [comment]
Not sure if I understood you correctly, but it sounds like for you the most important are key-value-alike features of the database (and now I understand why you were asking so much about JOIN engine and dictionaries). If so - I'm not sure if ClickHouse will suit that usage scenario. Engin=JOIN, Dictionaries, Engine=Set - in only some side features of ClickHouse and they have important limitations (main limitation: all of them should fit in memory). 

So at that moment, I would consider them rather as 'helpers' to process data with MergeTree engines family. MergeTree engines are the most strong and the most mature part of ClickHouse.

**Comment by healiseu** [comment]
Thanks, I will let you know...

**Comment by healiseu** [comment]
OK this is an update of a test I am currently running on a 10 x 1,226,766 flat table with reference to our previous discussion
```txt

┌─pk─┬─duration─┬──────────start_date─┬────────────end_date─┬─from_station_id─┬─from_station_name──────────────┬─to_station_id─┬─to_station_name─────────────┬─bike_code─┬─member_type─┐
│  1 │      346 │ 2011-01-01 00:02:46 │ 2011-01-01 00:08:32 │           31105 │ 14th & Harvard St NW           │         31101 │ 14th & V St NW              │ W00675    │ Casual      │
│  2 │      562 │ 2011-01-01 00:06:13 │ 2011-01-01 00:15:36 │           31400 │ Georgia & New Hampshire Ave NW │         31104 │ Adams Mill & Columbia Rd NW │ W00357    │ Member      │
│  3 │      434 │ 2011-01-01 00:09:21 │ 2011-01-01 00:16:36 │           31111 │ 10th & U St NW                 │         31503 │ Florida Ave & R St NW       │ W00970    │ Member      │
└────┴──────────┴─────────────────────┴─────────────────────┴─────────────────┴────────────────────────────────┴───────────────┴─────────────────────────────┴───────────┴─────────────┘
```
Using MergeTree engines, it's very fast to create source tables for dictionaries (lookup table) and secondary indexes. 

## Dictionary vs Secondary Index
For example let's take Duration column and execute the following queries for the Duration dictionary:
```sql
    CREATE VIEW VW_Duration AS 
    SELECT duration FROM TripFlat
    GROUP BY duration
    ORDER BY duration

    CREATE TABLE Duration
    (        
        dur_pk UInt16,
        dur_val UInt32 
    )
    ENGINE = MergeTree()
    ORDER BY dur_val

    INSERT INTO Duration SELECT rowNumberInAllBlocks() AS dur_pk, * FROM VW_Duration
```
and for the duration index

```sql
    CREATE VIEW VW_Duration_NDX AS
    SELECT pk AS trip_pk, dur_pk, dur_val
    FROM TripFlat
    ANY INNER JOIN Duration ON duration=dur_val
    ORDER BY dur_val ASC, trip_pk ASC

    CREATE TABLE Duration_NDX
    (        
        trip_pk UInt32,
        dur_pk UInt16,
        dur_val UInt32
    )
    ENGINE = MergeTree()
    ORDER BY (dur_val, trip_pk)

    INSERT INTO Duration_NDX SELECT * FROM VW_Duration_NDX

CPU times: user 4 ms, sys: 0 ns, total: 4 ms
Wall time: 531 ms
```
## Create Duration Filter
There are three ways I can create a filter based on my duration secondary index

### As a plain view
``` sql
    CREATE VIEW VW_Filter_dur AS
    SELECT 
        trip_pk AS filter_pk, 
        dur_pk, 
        dur_val
    FROM Duration_NDX 
    WHERE (dur_val >= 1000) AND (dur_val <= 1003)
    ORDER BY trip_pk ASC
```
### As a materialized view

```sql
    CREATE MATERIALIZED VIEW VWM_Filter_dur 
    (
      filter_pk UInt32, 
      dur_pk UInt16, 
      dur_val UInt32
    )
    ENGINE = Memory
    POPULATE AS SELECT 
        trip_pk AS filter_pk, 
        dur_pk, 
        dur_val
    FROM Duration_NDX 
    WHERE (dur_val >= 1000) AND (dur_val <= 1003)
    ORDER BY trip_pk ASC
```
### As a JOIN Engine
```sql
    CREATE TABLE JN_Filter_dur
    (
      trip_pk UInt32, 
      dur_pk UInt16, 
      dur_val UInt32
    )
    ENGINE = Join(ANY, INNER, trip_pk)
    
    INSERT INTO JN_Filter_dur SELECT * FROM VW_Filter_dur
```

## Apply Duration Filter on another secondary index
Now I want to JOIN two secondary indexes and I am looking for the fastest method 

### With plain view

``` sql
 SELECT count(*) from
        ( SELECT trip_pk, from_pk, from_name
          FROM StationFrom_NDX 
          ANY INNER JOIN VW_Filter_dur ON trip_pk = filter_pk
          ORDER BY from_pk
        )

16.4 ms ± 235 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

### With materialized view

```sql
SELECT count(*) from
        ( SELECT trip_pk, from_pk, from_name
          FROM StationFrom_NDX 
          ANY INNER JOIN VWM_Filter_dur ON trip_pk = filter_pk
          ORDER BY from_pk
        )

14.4 ms ± 90.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

### With JOIN engine

```sql
SELECT count(*) from
    (SELECT trip_pk, from_pk, from_name
     FROM StationFrom_NDX
     ANY INNER JOIN JN_Filter_dur ON StationFrom_NDX.trip_pk = JN_Filter_dur.trip_pk
     ORDER BY from_pk
    )

13.9 ms ± 186 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```
Is the JOIN engine the best approach for this specific task ?

**Comment by blinkov** [comment]
@healiseu, do you have any further questions?
