### ISSUE TITLE
date_diff round up

### ISSUE THREAD

**Issue by UserMMT** [ClickHouse/ClickHouse#33118]
**date_diff function round up**
When using date_diff the result is round up for example assuming 1 day = 1440 min when remove some minute to today and using date diff between yesterday and today - xmin the result continous giving 1 day according to how many minutes you remove
**How to reproduce**
* ClickHouse server version 21.12.2.17 (official build).

* Queries to run  
* --SELECT dateSub(day,1,NOW()),dateDiff(day,date_sub(day,1,NOW()),date_sub(minute,10,NOW()))
--SELECT dateSub(day,1,NOW()),dateDiff(day,date_sub(day,1,NOW()),date_sub(minute,30,NOW())) 

but 
SELECT dateSub(day,1,NOW()),dateDiff(day,date_sub(day,1,NOW()),date_sub(minute,[nb_minute_to_remove],NOW()))
* observations
* when **nb_minute_to_remove <=967** the result will be **1** else[nb_minute_to_remove >967] **0**

* What i use as temporarily solution is to change unit of date_sub from day to minute

**Comment by sulayliu** [comment]
nb_minute_to_remove this number is not constant, it comes from the current time minus 00:00:00 , 

for example if Now() = 09:02:00, nb_minute_to_remove  will be (09:02:00 - 00:00:00) * 60 mins = 542 mins, which means if nb_minute_to_remove > 542, date_sub(minute,[nb_minute_to_remove],NOW()) will be yesterday, the result will same with day,date_sub(day,1,NOW()), therefore dateDiff will be 0

**Comment by den-crane** [comment]
date_diff substracts internal relative indexes of units

https://clickhouse.com/docs/ru/sql-reference/functions/date-time-functions/#torelativeyearnum

the difference is only 1 second, but 1 year

```sql
SELECT dateDiff('year', toDateTime('2020-12-31 23:59:59'), toDateTime('2021-01-01 00:00:00')) AS diff
┌─diff─┐
│    1 │
└──────┘
```

because

```sql
SELECT
    toRelativeYearNum(toDateTime('2020-12-31 23:59:59')),
    toRelativeYearNum(toDateTime('2021-01-01 00:00:00'))
┌─toRelativeYearNum(toDateTime('2020-12-31 23:59:59'))─┬─toRelativeYearNum(toDateTime('2021-01-01 00:00:00'))─┐
│                                                 2020 │                                                 2021 │
└──────────────────────────────────────────────────────┴──────────────────────────────────────────────────────┘
```
