### ISSUE TITLE
Password exposed by SHOW CREATE TABLE command for table with MySQL engine

### ISSUE THREAD

**Issue by PhantomPhreak** [ClickHouse/ClickHouse#3311]
While creating table with `MySQL` engine engine, we have to provide a password for MySQL user:
```
my.awesome.clickhouse :)  create table mysqltest (id UInt64, field String) ENGINE = MySQL('127.0.0.1:3306', 'chtest', 'test', 'testuser', 'testpassword');                                        

CREATE TABLE mysqltest
(
    id UInt64, 
    field String
)
ENGINE = MySQL('127.0.0.1:3306', 'chtest', 'test', 'testuser', 'testpassword')

Ok.
```
After, any user having access to the database with this table, can see the password for MySQL user using `show create table` command:

```
my.awesome.clickhouse :)  show create table mysqltest;

SHOW CREATE TABLE mysqltest

┌─statement──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ CREATE TABLE test.mysqltest ( id UInt64,  field String) ENGINE = MySQL('127.0.0.1:3306', 'chtest', 'test', 'testuser', 'testpassword') │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

1 rows in set. Elapsed: 0.002 sec. 
```

It looks like a security issue, because password is exposed in plaintext. Combined with the lack of fine-grained per-table permissions, it makes a problem with keeping passwords in safe.
Is it possible to hide the password in the output of `show create table` command?
Thanks.

```
my.awesome.clickhouse :)  select * from system.build_options where name='VERSION_FULL';

SELECT *
FROM system.build_options 
WHERE name = 'VERSION_FULL'

┌─name─────────┬─value───────────────┐
│ VERSION_FULL │ ClickHouse 18.12.17 │
└──────────────┴─────────────────────┘
```

**Comment by tungdam** [comment]
+1
I have the same issue. And i believe we should hide this password somehow at least.

**Comment by filimonov** [comment]
Not really sure if it will work, but you can try to replace credentials with macros defined in config.

**Comment by PhantomPhreak** [comment]
Fair enough, let's try:
```
my.awesome.clickhouse :) create table mysqltest (id UInt64, field String) ENGINE = MySQL('127.0.0.1:3306', 'chtest', 'test', 'testuser', '{supersecurepassword}');                                         

CREATE TABLE mysqltest
(
    id UInt64, 
    field String
)
ENGINE = MySQL('127.0.0.1:3306', 'chtest', 'test', 'testuser', '{supersecurepassword}')

Ok.

0 rows in set. Elapsed: 0.114 sec. 

my.awesome.clickhouse :) show create table mysqltest;

SHOW CREATE TABLE mysqltest

┌─statement──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ CREATE TABLE default.mysqltest ( id UInt64,  field String) ENGINE = MySQL('127.0.0.1:3306', 'chtest', 'test', 'testuser', '{supersecurepassword}') │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

1 rows in set. Elapsed: 0.002 sec. 

my.awesome.clickhouse :) select * from system.macros;

SELECT *
FROM system.macros 

┌─macro───────────────┬─substitution─┐
│ supersecurepassword │ gotcha       │
└─────────────────────┴──────────────┘

1 rows in set. Elapsed: 0.006 sec. 

```

So, it doesn't help. We can also use substitutions from zookeeper, but everybody can read from `system.zookeeper` as well, because (if i'm not mistaken) tables in `system` database are readable by everyone.

**Comment by filimonov** [comment]
hm... Maybe some special macros available only for create/attach table statements can be implemented.

**Comment by filimonov** [comment]
Also: you can connect to MySQL using ODBC. And reference connection only by DSN, while storing credentials in odbc.ini. 

See here: https://www.altinity.com/blog/2018/9/20/using-odbc-with-clickhouse

**Comment by alex-krash** [comment]
@PhantomPhreak , unfortunately it looks like there is a bug in mysql odbc. It reproduces in ClickHouse integration tests, as well as my experience on local machine (Ubuntu 16.04)

**Comment by alexey-milovidov** [comment]
> @PhantomPhreak , unfortunately it looks like there is a bug in mysql odbc. It reproduces in ClickHouse integration tests, as well as my experience on local machine (Ubuntu 16.04)

`myodbc` shared library is incorrectly linked in Ubuntu - it exposes some additional symbols besides the ODBC interface (it should expose only symbols prefixed with `SQL`). And these symbols conflict with mysql client library that is linked inside ClickHouse.

It can be rebuilt from source to fix this issue.

**Comment by alexey-milovidov** [comment]
We can fix the issue by introducing a method for masking parameters.
It can be located in `IStorage` and called from `InterpreterShowCreateQuery` and `StorageSystemTables`.

**Comment by PhantomPhreak** [comment]
> We can fix the issue by introducing a method for masking parameters.
> It can be located in `IStorage` and called from `InterpreterShowCreateQuery` and `StorageSystemTables`.

It would be very nice. Thank you in advance!

**Comment by iFoton** [comment]
+1 Same problem with ODBC function and FreeTDS for SQL Server. Also we can't store Username and Password in odbc.ini [because](https://knowledgebase.progress.com/articles/Article/2987):

> The SQL Server Wire Protocol ODBC driver does not support this functionality on both Windows and Unix platforms.

And each time we should directly pass credentials to odbc function to query external databases.
Is there workaround for now to hide code of views or secure credentials another way?

**Comment by PhantomPhreak** [comment]
A new fancy RBAC approach has been implemented in a newest clickhouse versions, so i had a hope that `SHOW CREATE TABLE` clauses may be explicitly granted to the user, that may help to mask a problem decribed in this issue. Unfortunately, with any grant on a table or a database, even with a simple `SELECT` grant, user has rights to execute `SHOW CREATE QUERY` and observe a password. And it's a feature.

https://clickhouse.tech/docs/en/sql-reference/statements/grant/#grant-show
> A user has the SHOW privilege if it has any other privilege concerning the specified table, dictionary or database.

That's sad. We have a very simple task: connect an external MySQL table to the ClickHouse, and do not expose any credentials the the end-users, but it's not possible now :(

**Comment by alexey-milovidov** [comment]
This issue depends on another feature: "Predefined connections in configuration file".
So, you will be able to write something like: `ENGINE = MySQL(my_conn, table =  'test')`

This feature is in our backlog.

**Comment by alexey-milovidov** [comment]
The feature "Predefined connections in configuration file" has been implemented.
