### ISSUE TITLE
How to use named_collections?

### ISSUE THREAD

**Issue by zotann** [ClickHouse/ClickHouse#33117]
Added connection parameters to config.xml
```
     <named_collections>
         <pg_conn>
                 <host>10.241.29.63</host>
                 <port>5432</port>
                 <user>postgres</user>
                 <password>pass</password>
                 <db>olap2</db>
         </pg_conn>
     </named_collections>
```
The server ClickHouse was rebooted.

 How to use named_collections?

```
 create table   src_133.pg_cube_test2
 (
     clnd_id integer ,
     okved_id integer  ,
     type_id integer ,
     terr_id integer  ,
     fact1  Nullable(Float64),
     fact2 Nullable(Float64),
     fact3 Nullable(Float64),
     fact4 Nullable(Float64),
     group_id Nullable(Float64)

 ) 
 engine = PostgreSQL(pg_conn,  table = 'cube_data_aggr', sheme = 'src_133'    );
```

 Code: 36. DB::Exception: There is no collection named `pg_conn` in config. (BAD_ARGUMENTS) (version 21.12.2.17 (official build))
 
 @kssenii. i need help

**Comment by kssenii** [comment]
> Added connection parameters to config.xml

very strange, your configuration is correct, are you sure you put it on correct level in config and the server indeed uses that config?

**Comment by zotann** [comment]
Looked at the source file. It is required to create a file named_collections.xml and describe the structure of the collection there.

**Comment by kssenii** [comment]
Not it is not, you can just put in config.xml.

**Comment by zotann** [comment]
> very strange, your configuration is correct, are you sure you put it on correct level in config and the server indeed uses that config?

I'm confused.
In which file should you create the tag?
сonfig.xml or named_collections.xml?

**Comment by zotann** [comment]
> Not it is not, you can just put in config.xml.

Where do I add the `<named_collection>....</named_collection>` tag in file сonfig.xml ?

**Comment by kssenii** [comment]
> Looked at the source file.

When you put files in config.d directory they can be used as config files and can be named not only as config.xml -- same as the file name_collection.xml that you saw in the source file.

So putting your  configuration will also work if you out it in config,xml as well as it will work if you out it in config.d directory in a dile with different name.

**Comment by kssenii** [comment]
> Where do I add the <named_collection>....</named_collection> tag in file сonfig.xml ?

`<named_collection>` --  no, need `s` at the end -- `named_collections`

Yes, you can put it just in config.xml

**Comment by zotann** [comment]
its true?

	```
<named_collections> 
	    <pg_conn>
		<host>10.200.20.60</host>
		<port>5432</port>
		<username>postgres</user>
		<password>pass</password>
		<database>olap2</database>  
	    </pg_conn>  
	</named_collections> 
```

**Comment by kssenii** [comment]
Yes, totally correct.

**Comment by zotann** [comment]
**Config.xml**
![image](https://user-images.githubusercontent.com/81733979/147270651-4880f86b-1a6c-4375-9e67-137b0e4663b8.png)

**Query**
![image](https://user-images.githubusercontent.com/81733979/147270739-273e675b-7261-46a1-88e2-928adde5c964.png)

**Error**
Code: 36. DB::Exception: There is no collection named `pg_conn` in config. (BAD_ARGUMENTS) (version 21.12.2.17 (official build))

**Comment by zotann** [comment]
Completed **clickhouse-server restart**

**Comment by zotann** [comment]
> Yes, totally correct.

What am I doing wrong?

**Comment by zotann** [comment]
Understood. The tag <user> was wrong.

```
	<named_collections> 
	    <pg_conn>
		<host>10.241.29.63</host>
		<port>5432</port>
		<user>postgres</user>
		<password>W2NcFH7l43YL</password>
		<database>mer_olap2</database>  
	    </pg_conn>    
	</named_collections> 
```

**Comment by zotann** [comment]
This goood

**Comment by liuyuchuan** [comment]
hello
i want to know which version add the tags of named_collections?
