### ISSUE TITLE
Caught exception while loading metadata: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = JSONException: JSON: begin >= end

### ISSUE THREAD

**Issue by ArtZoick** [ClickHouse/ClickHouse#33125]
2021.12.24 10:29:26.863812 [ 49 ] {} <Information> Application: Shutting down storages.
2021.12.24 10:29:26.863822 [ 49 ] {} <Information> Context: Shutdown disk default
2021.12.24 10:29:27.833363 [ 49 ] {} <Error> Application: JSONException: JSON: begin >= end.
2021.12.24 10:29:27.833391 [ 49 ] {} <Information> Application: shutting down
2021.12.24 10:29:27.833487 [ 50 ] {} <Information> BaseDaemon: Stop SignalListener thread
2021.12.24 10:29:27.851751 [ 1 ] {} <Information> Application: Child process exited normally with code 70.
2021.12.24 10:29:29.751282 [ 1 ] {} <Information> Application: Will watch for the process with pid 48
2021.12.24 10:29:29.751438 [ 48 ] {} <Information> Application: Forked a child process to watch
2021.12.24 10:29:29.751683 [ 48 ] {} <Information> SentryWriter: Sending crash reports is disabled
2021.12.24 10:29:29.808129 [ 48 ] {} <Information> : Starting ClickHouse 21.7.4.18 with revision 54452, build id: 697A9902DCE7A291C0E5CA723B17481126142A81, PID 48
2021.12.24 10:29:29.808276 [ 48 ] {} <Information> Application: starting up
2021.12.24 10:29:29.808301 [ 48 ] {} <Information> Application: OS name: Linux, version: 5.10.0-9-amd64, architecture: x86_64
2021.12.24 10:29:29.973149 [ 48 ] {} <Information> Application: Calculated checksum of the binary: 29FC72CB092D5C4B8F07929DE59AD4B8, integrity check passed.
2021.12.24 10:29:29.973206 [ 48 ] {} <Information> Application: It looks like the process has no CAP_IPC_LOCK capability, binary mlock will be disabled. It could happen due to incorrect ClickHouse package installation. You could resolve the problem manually with 'sudo setcap cap_ipc_lock=+ep /usr/bin/clickhouse'. Note that it will not work on 'nosuid' mounted filesystems.
2021.12.24 10:29:29.973628 [ 48 ] {} <Information> SensitiveDataMaskerConfigRead: 1 query masking rules loaded.
2021.12.24 10:29:29.979532 [ 48 ] {} <Information> Application: Setting max_server_memory_usage was set to 6.99 GiB (7.77 GiB available * 0.90 max_server_memory_usage_to_ram_ratio)
2021.12.24 10:29:34.996693 [ 48 ] {} <Information> Application: Uncompressed cache size was lowered to 3.88 GiB because the system has low amount of memory
2021.12.24 10:29:34.996797 [ 48 ] {} <Information> Application: Mark cache size was lowered to 3.88 GiB because the system has low amount of memory
2021.12.24 10:29:34.997678 [ 48 ] {} <Information> Application: Loading metadata from /opt/data/clickhouse/
2021.12.24 10:29:35.003863 [ 48 ] {} <Information> DatabaseAtomic (system): Total 5 tables and 0 dictionaries.
2021.12.24 10:29:35.011482 [ 48 ] {} <Information> DatabaseAtomic (system): Starting up tables.
2021.12.24 10:29:35.011625 [ 55 ] {} <Information> BackgroundSchedulePool/BgSchPool: Create BackgroundSchedulePool with 128 threads
2021.12.24 10:29:35.036136 [ 48 ] {} <Information> DatabaseAtomic (default): Total 0 tables and 0 dictionaries.
2021.12.24 10:29:35.036161 [ 48 ] {} <Information> DatabaseAtomic (default): Starting up tables.
2021.12.24 10:29:35.051535 [ 48 ] {} <Information> DatabaseAtomic (violation_event): Total 2 tables and 0 dictionaries.
2021.12.24 10:29:35.071763 [ 48 ] {} <Error> Application: Caught exception while loading metadata: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = JSONException: JSON: begin >= end., Stack trace (when copying this message, always include the lines below):

0. JSON::checkInit() const @ 0x1331c34e in /usr/bin/clickhouse
1. DB::FileChecker::load() @ 0x10225547 in /usr/bin/clickhouse
2. DB::FileChecker::FileChecker(std::__1::shared_ptr<DB::IDisk>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x10224ff3 in /usr/bin/clickhouse
3. DB::StorageLog::StorageLog(std::__1::shared_ptr<DB::IDisk>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::StorageID const&, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, unsigned long) @ 0x10218cbc in /usr/bin/clickhouse
4. ? @ 0x10224577 in /usr/bin/clickhouse
5. DB::StorageFactory::get(DB::ASTCreateQuery const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, std::__1::shared_ptr<DB::Context>, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, bool) const @ 0x1002d481 in /usr/bin/clickhouse
6. DB::createTableFromAST(DB::ASTCreateQuery, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool) @ 0xf63f05c in /usr/bin/clickhouse
7. ? @ 0xf63d6f3 in /usr/bin/clickhouse
8. ? @ 0xf63e77f in /usr/bin/clickhouse
9. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0x8d6e638 in /usr/bin/clickhouse
10. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()&&...)::'lambda'()::operator()() @ 0x8d701df in /usr/bin/clickhouse
11. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x8d6b91f in /usr/bin/clickhouse
12. ? @ 0x8d6f203 in /usr/bin/clickhouse
13. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
14. clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
 (version 21.7.4.18 (official build))

**Comment by ArtZoick** [comment]
It seems to be an error loading the violation_event table.

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/28578
