### ISSUE TITLE
Report an error through disks3 query using debug to compile

### ISSUE THREAD

**Issue by xiedeyantu** [ClickHouse/ClickHouse#33128]
version: v21.8.10.19-lts 
build: debug
using DiskS3
sql:
create table t
(
  partition_col_1 String, 
  tc1 int,tc2 int
)engine=MergeTree() 
partition by partition_col_1 order by tc1;

insert into t values('partition1', 1,1);

The clickhouse process crashed when I executed 'select * from t;'.

client return:
Exception on client:
Code: 32. DB::Exception: Attempt to read after eof: while receiving packet from localhost:9000

server log：
2021.12.24 09:43:27.932490 [ 2844618 ] {} <Fatal> BaseDaemon: Calculated checksum of the binary: ED5E150C1C34031CB02E8BC54CE699CE. There is no information about the reference checksum.
2021.12.24 09:43:30.205675 [ 2844824 ] {} <Fatal> BaseDaemon: ########################################
2021.12.24 09:43:30.206111 [ 2844824 ] {} <Fatal> BaseDaemon: (version 21.8.10.1, no build id) (from thread 2844635) (query_id: b286ad06-ca70-46d2-910c-d87fd5df46b9) Received signal Aborted (6)
2021.12.24 09:43:30.206328 [ 2844824 ] {} <Fatal> BaseDaemon: 
2021.12.24 09:43:30.206521 [ 2844824 ] {} <Fatal> BaseDaemon: Stack trace: 0x7fdb33400e7f 0x7fdb333eb8b5 0x7fdb333eb789 0x7fdb333f9576 0x9fb4848 0x1633175c 0x9fb48c9 0x153f60d3 0x153f61f8 0x9fb48c9 0x16330033 0x9fb48c9 0x16330033 0x9fb48c9 0x13ff16ed 0x13ff477a 0x1416653a 0x141351d7 0x14c36ed3 0x14c3633e 0x15c19a68 0x15c19d3d 0x15c1a805 0x15c1e317 0x15c1d4b4 0x15bacf31 0x15bad94f 0x15bac92b 0x14ea3cb0 0x14ea3a44 0x150c74ed 0x14ef5f39 0x14ef5e9f 0x14ef5e3d 0x14ef5dfd 0x14ef5dd5 0x14ef5d9d 0x9fd68c6 0x9fd59f5 0x14ef47e7 0x14ef51a5
2021.12.24 09:43:30.206787 [ 2844824 ] {} <Fatal> BaseDaemon: 4. __GI_raise @ 0x3ae7f in /usr/lib64/libc-2.28.so
2021.12.24 09:43:30.206961 [ 2844824 ] {} <Fatal> BaseDaemon: 5. abort @ 0x258b5 in /usr/lib64/libc-2.28.so
2021.12.24 09:43:30.207107 [ 2844824 ] {} <Fatal> BaseDaemon: 6. _nl_load_domain.cold.0 @ 0x25789 in /usr/lib64/libc-2.28.so
2021.12.24 09:43:30.207276 [ 2844824 ] {} <Fatal> BaseDaemon: 7. ? @ 0x33576 in /usr/lib64/libc-2.28.so
2021.12.24 09:43:30.472941 [ 2844824 ] {} <Fatal> BaseDaemon: 8. /data/code/ClickHouse/build-v21-8/../src/IO/ReadBuffer.h:0: DB::ReadBuffer::next() @ 0x9fb4848 in /data/code/ClickHouse/build-v21-8/programs/clickhouse
2021.12.24 09:43:30.587665 [ 2844824 ] {} <Fatal> BaseDaemon: 9. /data/code/ClickHouse/build-v21-8/../src/IO/ReadBufferFromS3.cpp:57: DB::ReadBufferFromS3::nextImpl() @ 0x1633175c in /data/code/ClickHouse/build-v21-8/programs/clickhouse
2021.12.24 09:43:30.852299 [ 2844824 ] {} <Fatal> BaseDaemon: 10. /data/code/ClickHouse/build-v21-8/../src/IO/ReadBuffer.h:62: DB::ReadBuffer::next() @ 0x9fb48c9 in /data/code/ClickHouse/build-v21-8/programs/clickhouse
2021.12.24 09:43:30.917056 [ 2844824 ] {} <Fatal> BaseDaemon: 11. /data/code/ClickHouse/build-v21-8/../src/Disks/ReadIndirectBufferFromRemoteFS.cpp:118: DB::ReadIndirectBufferFromRemoteFS<DB::ReadBufferFromS3>::nextAndShiftPosition() @ 0x153f60d3 in /data/code/ClickHouse/build-v21-8/programs/clickhouse
2021.12.24 09:43:30.982286 [ 2844824 ] {} <Fatal> BaseDaemon: 12. /data/code/ClickHouse/build-v21-8/../src/Disks/ReadIndirectBufferFromRemoteFS.cpp:95: DB::ReadIndirectBufferFromRemoteFS<DB::ReadBufferFromS3>::nextImpl() @ 0x153f61f8 in /data/code/ClickHouse/build-v21-8/programs/clickhouse
2021.12.24 09:43:31.248222 [ 2844824 ] {} <Fatal> BaseDaemon: 13. /data/code/ClickHouse/build-v21-8/../src/IO/ReadBuffer.h:62: DB::ReadBuffer::next() @ 0x9fb48c9 in /data/code/ClickHouse/build-v21-8/programs/clickhouse
2021.12.24 09:43:31.303965 [ 2844824 ] {} <Fatal> BaseDaemon: 14. /data/code/ClickHouse/build-v21-8/../src/IO/ReadBufferFromFileDecorator.cpp:43: DB::ReadBufferFromFileDecorator::nextImpl() @ 0x16330033 in /data/code/ClickHouse/build-v21-8/programs/clickhouse
2021.12.24 09:43:31.568315 [ 2844824 ] {} <Fatal> BaseDaemon: 15. /data/code/ClickHouse/build-v21-8/../src/IO/ReadBuffer.h:62: DB::ReadBuffer::next() @ 0x9fb48c9 in /data/code/ClickHouse/build-v21-8/programs/clickhouse
2021.12.24 09:43:31.623996 [ 2844824 ] {} <Fatal> BaseDaemon: 16. /data/code/ClickHouse/build-v21-8/../src/IO/ReadBufferFromFileDecorator.cpp:43: DB::ReadBufferFromFileDecorator::nextImpl() @ 0x16330033 in /data/code/ClickHouse/build-v21-8/programs/clickhouse
2021.12.24 09:43:31.888032 [ 2844824 ] {} <Fatal> BaseDaemon: 17. /data/code/ClickHouse/build-v21-8/../src/IO/ReadBuffer.h:62: DB::ReadBuffer::next() @ 0x9fb48c9 in /data/code/ClickHouse/build-v21-8/programs/clickhouse
2021.12.24 09:43:31.945627 [ 2844824 ] {} <Fatal> BaseDaemon: 18.1. inlined from /data/code/ClickHouse/build-v21-8/../src/IO/ReadBuffer.h:93: DB::ReadBuffer::eof()
2021.12.24 09:43:31.945927 [ 2844824 ] {} <Fatal> BaseDaemon: 18. ../src/Compression/CompressedReadBufferBase.cpp:110: DB::CompressedReadBufferBase::readCompressedData(unsigned long&, unsigned long&, bool) @ 0x13ff16ed in /data/code/ClickHouse/build-v21-8/programs/clickhouse
2021.12.24 09:43:32.000189 [ 2844824 ] {} <Fatal> BaseDaemon: 19. /data/code/ClickHouse/build-v21-8/../src/Compression/CompressedReadBufferFromFile.cpp:107: DB::CompressedReadBufferFromFile::readBig(char*, unsigned long) @ 0x13ff477a in /data/code/ClickHouse/build-v21-8/programs/clickhouse
2021.12.24 09:43:32.105765 [ 2844824 ] {} <Fatal> BaseDaemon: 20. /data/code/ClickHouse/build-v21-8/../src/DataTypes/Serializations/SerializationNumber.cpp:152: DB::SerializationNumber<int>::deserializeBinaryBulk(DB::IColumn&, DB::ReadBuffer&, unsigned long, double) const @ 0x1416653a in /data/code/ClickHouse/build-v21-8/programs/clickhouse
2021.12.24 09:43:32.192141 [ 2844824 ] {} <Fatal> BaseDaemon: 21. /data/code/ClickHouse/build-v21-8/../src/DataTypes/Serializations/ISerialization.cpp:100: DB::ISerialization::deserializeBinaryBulkWithMultipleStreams(COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, DB::ISerialization::DeserializeBinaryBulkSettings&, std::__1::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, COW<DB::IColumn>::immutable_ptr<DB::IColumn> > > >*) const @ 0x141351d7 in /data/code/ClickHouse/build-v21-8/programs/clickhouse
2021.12.24 09:43:32.672423 [ 2844824 ] {} <Fatal> BaseDaemon: 22. /data/code/ClickHouse/build-v21-8/../src/Storages/MergeTree/MergeTreeReaderCompact.cpp:242: DB::MergeTreeReaderCompact::readData(DB::NameAndTypePair const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, unsigned long, unsigned long, bool) @ 0x14c36ed3 in /data/code/ClickHouse/build-v21-8/programs/clickhouse
2021.12.24 09:43:33.166404 [ 2844824 ] {} <Fatal> BaseDaemon: 23. /data/code/ClickHouse/build-v21-8/../src/Storages/MergeTree/MergeTreeReaderCompact.cpp:167: DB::MergeTreeReaderCompact::readRows(unsigned long, bool, unsigned long, std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >&) @ 0x14c3633e in /data/code/ClickHouse/build-v21-8/programs/clickhouse
2021.12.24 09:43:33.611116 [ 2844824 ] {} <Fatal> BaseDaemon: 24. /data/code/ClickHouse/build-v21-8/../src/Storages/MergeTree/MergeTreeRangeReader.cpp:76: DB::MergeTreeRangeReader::DelayedStream::readRows(std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >&, unsigned long) @ 0x15c19a68 in /data/code/ClickHouse/build-v21-8/programs/clickhouse
2021.12.24 09:43:34.012471 [ 2844824 ] {} <Fatal> BaseDaemon: 25. /data/code/ClickHouse/build-v21-8/../src/Storages/MergeTree/MergeTreeRangeReader.cpp:149: DB::MergeTreeRangeReader::DelayedStream::finalize(std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >&) @ 0x15c19d3d in /data/code/ClickHouse/build-v21-8/programs/clickhouse
2021.12.24 09:43:34.427907 [ 2844824 ] {} <Fatal> BaseDaemon: 26. /data/code/ClickHouse/build-v21-8/../src/Storages/MergeTree/MergeTreeRangeReader.cpp:260: DB::MergeTreeRangeReader::Stream::finalize(std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >&) @ 0x15c1a805 in /data/code/ClickHouse/build-v21-8/programs/clickhouse
2021.12.24 09:43:34.839910 [ 2844824 ] {} <Fatal> BaseDaemon: 27. /data/code/ClickHouse/build-v21-8/../src/Storages/MergeTree/MergeTreeRangeReader.cpp:784: DB::MergeTreeRangeReader::startReadingChain(unsigned long, std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange> >&) @ 0x15c1e317 in /data/code/ClickHouse/build-v21-8/programs/clickhouse

**Comment by alexey-milovidov** [comment]
DiskS3 is in development. You should use the latest master build if you want to participate in development.
And it is not ready for production usage.
