### ISSUE TITLE
Does it acceptable if clickhouse-keeper use double memory vs zookeeper?

### ISSUE THREAD

**Issue by zhanglistar** [ClickHouse/ClickHouse#33126]
I have done some improvement on clickhouse-keeper, about 1.4x of zookeeper in only writing benchmark, but with the double memory cost. 
Does that acceptable? 
@alexey-milovidov @alesapin

**Comment by zhanglistar** [comment]
Well, I think it's not good. Need to keep doing.

**Comment by alesapin** [comment]
Maybe you can publish your improvement? It's quite interesting.

**Comment by zhanglistar** [comment]
https://github.com/ClickHouse/ClickHouse/pull/33180


> Maybe you can publish your improvement? It's quite interesting.

**Comment by alexey-milovidov** [comment]
Ok. The answer - it's not acceptable, but we will look at the implementation and try to optimize it.
