### ISSUE TITLE
How to connect multiple Kafka clusters using SASL authentication

### ISSUE THREAD

**Issue by xpleaf** [ClickHouse/ClickHouse#33133]
1. **The background**

In my scenario, ClickHouse is available as a SaaS service for users who use Kafka as their data source, so you need to create tables for the Kafka engine.

2. **Problem**

There is a problem here, because in our scenario Kafka clusters are authenticated based on SASL, and different users have different usernames and passwords. The problem is that ClickHouse reads sasL authentication information from Kafka data sources in configuration files. This makes it impossible to access multiple Kafka data sources with different authentication information in our ClickHouse SaaS service.

3. **Solutions**

I think this scenario is quite common for building enterprise SaaS services. Do the community have any good solutions for this scenario?

**Comment by xpleaf** [comment]
It seems that it has some configuration:

https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md

let me have a try.

**Comment by den-crane** [comment]
Each topic can have own uniq config https://clickhouse.com/docs/en/engines/table-engines/integrations/kafka/

example for topic `log`

```xml
  <!-- Configuration specific for topic "logs" -->
  <kafka_logs>
    <retry_backoff_ms>250</retry_backoff_ms>
    <fetch_min_bytes>100000</fetch_min_bytes>
  </kafka_logs>
```

---

https://kb.altinity.com/altinity-kb-integrations/altinity-kb-kafka/altinity-kb-adjusting-librdkafka-settings/

**Comment by xpleaf** [comment]
@den-crane Thank you very much. I neglected to read the official documents carefully.
