### ISSUE TITLE
Support MILLISECOND, MICROSECOND, NANOSECOND for INTERVAL.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#33147]
**Use case**

`roundToInterval(t, INTERVAL 10 MILLISECOND)` and similar.

**Comment by UnamedRus** [comment]
Partially related https://github.com/ClickHouse/ClickHouse/issues/28684

**Comment by lingtaolf** [comment]
Any one working on this? If no, let me try .

**Comment by alexey-milovidov** [comment]
@lingtaolf Thank you, it's yours!

**Comment by alex-zaitsev** [comment]
@lingtaolf , are you working on that? If not, we have a developer who can take it.

**Comment by zvonand** [comment]
I can take this one
