### ISSUE TITLE
Broken connection error after remote Postgres server restart when using remote table engine

### ISSUE THREAD

**Issue by AviSarmani** [ClickHouse/ClickHouse#33199]
Hi all,
Hope I'm using the correct type as I couldn't find any other references to this kind of error.

In our scenario we have a couple of tables that we connect remotely via the Postgres Table Engine.
After the remote Postgres server restarts for some reason, we get the error:
DynamicQueryHandler: std::exception. Code: 1001, type: pqxx::broken_connection, e.what() = Lost connection to the database server.
although the server is up by now.
Retrying the query(a couple of times) fixes the issue

**Does it reproduce on recent release?**
Yes, we're on 21.12.2.17.

**How to reproduce**
We're getting the errors from our application but have been able to reproduce the error using only the clickhouse client locally

* Version 21.12.2.17
* Postgres version 13

1. Create any table using the Postgres Engine:

CREATE TABLE test.test
(
    `id` String,
) AS postgresql(xxxxx', 'db_name', 'test', 'user_name', 'secret', 'schema_name')

2. Restart the Postgres instance with or without querying the table beforehand

3. Try to query the table and get the following error:

exception. Code: 1001, type: pqxx::broken_connection, e.what() = Lost connection to the database server. (version 21.12.2.17 (official build))

4. Retry the query again and the query succeeds.

That's the simplest way of reproducing the issue with the clickhouse client.

From my observation I can see that for each remote table in Clickhouse, a process starts at the Postgres server and manually killing it yields the same result of broken_connection.

The expected behavior would be that Clickhouse should be able to reconnect to the remote DB in case of a failover without abrupting the flow or handling this error on the application level.

Any help will be appreciated.
Best Regards

**Comment by kssenii** [comment]
@AviSarmani I think it is sort of expected behavior. When you restarted the server, connection was lost, but the fact of lost connection can not be known until you make a query. When query fails with broken connection error, then we know it is broken and reconnect. So the next query succeeds as we reconnected.
I can add retries though, if query failed with broken connection until anything was fetched.

**Comment by AviSarmani** [comment]
Hi @kssenii ,
First of all thank you for the quick reply.
My perspective on this issue is that a table can be remote because I don't want to replicate it yet to Clickhouse or because it is "remote" to my ecosystem and I don't have any control over it so that it's not me who is restarting it.

In our scenario, the remote server can go down and get back up as part of a maintenance on some other system over the night and our users start getting errors early in the morning where in fact there is nothing preventing the system from behaving correctly.
Another point is that the error is for every remote table. I think that because we're using Flask and have a couple of processes and threads, after an error the user gets rerouted to another thread which also fails(out of scope for this issue, just for reference) so we get a user that refreshes the pages up to 10 times until every thread reconnects with every remote table.

If our assumptions are that:
1. When we connect to a remote table we reuse a connection that has been made in an earlier point in time
2. This connection get broken in case of a failover even if the server is up and running
3. From the application stand point there is nothing preventing it from working

So I think that some sort of a soft-reconnect with a low number of retries is in order.

Thanks again.

**Comment by kssenii** [comment]
Ok, I agree. I'll add a retry to make a query in case it failed with broken connection before anything was read. Then your case will be ok.

**Comment by StreamSlience** [comment]
I also encountered the same problem, after the Postgres database is restarted, I still get a connection error when I execute a query that remotely associates postgres data, the current clickhouse version is 23.10.4.25, it seems that this problem does not add a mechanism to retry the connection.
After I restarted the postgre database myself, I immediately executed the query sql and found that the results returned by two consecutive queries were connection errors, and the query was not successful until the third time.

Here's the exception log of the associated pg query immediately after restarting the pg database:
![clickhouse_001](https://github.com/ClickHouse/ClickHouse/assets/42864358/bcb11a23-c1dc-400b-9af5-f47092eb5309)
