### ISSUE TITLE
when data will be merged in a same partition?

### ISSUE THREAD

**Issue by FunkyYang** [ClickHouse/ClickHouse#33208]
I found there are 3 files in a same partition 2 days ago.and them not continuous.
 when I use
```
OPTIMIZE table xxx partition(20211221);
```
and data in 20211221 will be merged a single file and they are continuous,that seems ok,
why when I  not execute the optimize command and data will not be merged a single file

**Comment by den-crane** [comment]
Merges are eventual and may never happen. It depends on the number of inserts that happened after, the number of parts in the partition, size of parts. If the total size of input parts are greater than the maximum part size then they will never be merged.


It is very unreasonable to constantly merge up to one part.
Merger does not have such goal. In the contrary the goal is to have the minimum number of parts withing smallest number of merges. Merges consume the huge amount of disk and processor resources.

It makes no sense to merge two 300GB parts into one 600GB part for 3 hours, you have to read, decompress 600GB, merge, compress, write them back, after that the performance of the selects will not grow at all or will grow minimally.
