### ISSUE TITLE
simple query 'select 1' execute too long, cost 15 minutes, why this happen

### ISSUE THREAD

**Issue by lifulong** [ClickHouse/ClickHouse#33204]
**Describe the situation**
simple query 'select 1' execute too long, cost 15 minutes, why this happen?

i have checked cpu、memory、network、disk use info on the machine， everything is ok

below is query log info:

┌─type────────┬─event_date─┬──────────event_time─┬────event_time_microseconds─┬────query_start_time─┬─query_start_time_microseconds─┬─query_duration_ms─┬─read_rows─┬─read_bytes─┬─written_rows─┬─written_bytes─┬─result_rows─┬─result_bytes─┬─memory_usage─┬─current_database─┬─query────┬─formatted_query─┬─normalized_query_hash─┬─query_kind─┬─databases──┬─tables─────────┬─columns──────────────┬─projections─┬─views─┬─exception_code─┬─exception─┬─stack_trace─┬─is_initial_query─┬─user─────┬─query_id─────────────────────────────┬─address──────────────┬──port─┬─initial_user─┬─initial_query_id─────────────────────┬─initial_address──────┬─initial_port─┬─initial_query_start_time─┬─initial_query_start_time_microseconds─┬─interface─┬─os_user─┬─client_hostname─┬─client_name─┬─client_revision─┬─client_version_major─┬─client_version_minor─┬─client_version_patch─┬─http_method─┬─http_user_agent────┬─http_referer─┬─forwarded_for─┬─quota_key─┬─revision─┬─log_comment─┬─thread_ids───────────────────────┬─ProfileEvents──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─Settings───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─used_aggregate_functions─┬─used_aggregate_function_combinators─┬─used_database_engines─┬─used_data_type_families─┬─used_dictionaries─┬─used_formats─────┬─used_functions─┬─used_storages─┬─used_table_functions─┐
│ QueryFinish │ 2021-12-21 │ 2021-12-21 18:18:23 │ 2021-12-21 18:18:23.250436 │ 2021-12-21 18:07:25 │    2021-12-21 18:07:25.290225 │                 6 │         1 │          1 │            0 │             0 │           1 │           32 │         1448 │ default          │ SELECT 1
 │                 │  15722048748544463130 │ Select     │ ['system'] │ ['system.one'] │ ['system.one.dummy'] │ []          │ []    │              0 │           │             │                1 │ readonly │ 7b6daee0-8020-4a3c-8241-dca55e8ef1d8 │ ::ffff:10.103.106.18 │ 32462 │ readonly     │ 7b6daee0-8020-4a3c-8241-dca55e8ef1d8 │ ::ffff:10.103.106.18 │        32462 │      2021-12-21 18:07:25 │            2021-12-21 18:07:25.290225 │         2 │         │                 │             │               0 │                    0 │                    0 │                    0 │           1 │ Go-http-client/1.1 │              │               │           │    54454 │             │ [61946,22108,21498,123679,41959] │ {'Query':1,'SelectQuery':1,'IOBufferAllocs':3,'IOBufferAllocBytes':3145773,'SelectedRows':1,'SelectedBytes':1,'ContextLock':12,'RWLockAcquiredReadLocks':1,'RealTimeMicroseconds':657961220,'UserTimeMicroseconds':82438,'SystemTimeMicroseconds':14503,'SoftPageFaults':10,'OSCPUWaitMicroseconds':2698,'OSCPUVirtualTimeMicroseconds':96281,'OSWriteBytes':4096,'OSReadChars':917,'OSWriteChars':142438} │ {'max_block_size':'131075','connect_timeout_with_failover_ms':'1000','distributed_directory_monitor_batch_inserts':'1','load_balancing':'random','distributed_aggregation_memory_efficient':'1','log_queries':'1','distributed_product_mode':'global','preferred_block_size_bytes':'10000003','insert_distributed_sync':'1','max_bytes_before_external_group_by':'21474836480','max_execution_time':'301','readonly':'2','partial_merge_join_rows_in_right_blocks':'131075','max_memory_usage':'42949672960','parallel_view_processing':'1','allow_experimental_projection_optimization':'1'} │ []                       │ []                                  │ []                    │ []                      │ []                │ ['TabSeparated'] │ []             │ []            │ []                   │
└─────────────┴────────────┴─────────────────────┴────────────────────────────┴─────────────────────┴───────────────────────────────┴───────────────────┴───────────┴────────────┴──────────────┴───────────────┴─────────────┴──────────────┴──────────────┴──────────────────┴──────────┴─────────────────┴───────────────────────┴────────────┴────────────┴────────────────┴──────────────────────┴─────────────┴───────┴────────────────┴───────────┴─────────────┴──────────────────┴──────────┴──────────────────────────────────────┴──────────────────────┴───────┴──────────────┴──────────────────────────────────────┴──────────────────────┴──────────────┴──────────────────────────┴───────────────────────────────────────┴───────────┴─────────┴─────────────────┴─────────────┴─────────────────┴──────────────────────┴──────────────────────┴──────────────────────┴─────────────┴────────────────────┴──────────────┴───────────────┴───────────┴──────────┴─────────────┴──────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────┴─────────────────────────────────────┴───────────────────────┴─────────────────────────┴───────────────────┴──────────────────┴────────────────┴───────────────┴──────────────────────┘

below is metric log info:

event_date:                                                    2021-12-21
event_time:                                                    2021-12-21 18:20:00
event_time_microseconds:                                       2021-12-21 18:20:00.791625
milliseconds:                                                  791
ProfileEvent_Query:                                            0
ProfileEvent_SelectQuery:                                      0
ProfileEvent_InsertQuery:                                      0
ProfileEvent_FailedQuery:                                      0
ProfileEvent_FailedSelectQuery:                                0
ProfileEvent_FailedInsertQuery:                                0
ProfileEvent_QueryTimeMicroseconds:                            0
ProfileEvent_SelectQueryTimeMicroseconds:                      0
ProfileEvent_InsertQueryTimeMicroseconds:                      0
ProfileEvent_FileOpen:                                         380
ProfileEvent_Seek:                                             91
ProfileEvent_ReadBufferFromFileDescriptorRead:                 366
ProfileEvent_ReadBufferFromFileDescriptorReadFailed:           0
ProfileEvent_ReadBufferFromFileDescriptorReadBytes:            1393311
ProfileEvent_WriteBufferFromFileDescriptorWrite:               193
ProfileEvent_WriteBufferFromFileDescriptorWriteFailed:         0
ProfileEvent_WriteBufferFromFileDescriptorWriteBytes:          1184497
ProfileEvent_ReadCompressedBytes:                              1166178
ProfileEvent_CompressedReadBufferBlocks:                       163
ProfileEvent_CompressedReadBufferBytes:                        10729915
ProfileEvent_UncompressedCacheHits:                            0
ProfileEvent_UncompressedCacheMisses:                          0
ProfileEvent_UncompressedCacheWeightLost:                      0
ProfileEvent_MMappedFileCacheHits:                             0
ProfileEvent_MMappedFileCacheMisses:                           0
ProfileEvent_AIOWrite:                                         0
ProfileEvent_AIOWriteBytes:                                    0
ProfileEvent_AIORead:                                          0
ProfileEvent_AIOReadBytes:                                     0
ProfileEvent_IOBufferAllocs:                                   841
ProfileEvent_IOBufferAllocBytes:                               212482763
ProfileEvent_ArenaAllocChunks:                                 0
ProfileEvent_ArenaAllocBytes:                                  0
ProfileEvent_FunctionExecute:                                  1
ProfileEvent_TableFunctionExecute:                             0
ProfileEvent_MarkCacheHits:                                    0
ProfileEvent_MarkCacheMisses:                                  0
ProfileEvent_CreatedReadBufferOrdinary:                        182
ProfileEvent_CreatedReadBufferDirectIO:                        0
ProfileEvent_CreatedReadBufferDirectIOFailed:                  0
ProfileEvent_CreatedReadBufferMMap:                            0
ProfileEvent_CreatedReadBufferMMapFailed:                      0
ProfileEvent_DiskReadElapsedMicroseconds:                      5252
ProfileEvent_DiskWriteElapsedMicroseconds:                     1295
ProfileEvent_NetworkReceiveElapsedMicroseconds:                51049823
ProfileEvent_NetworkSendElapsedMicroseconds:                   499
ProfileEvent_NetworkReceiveBytes:                              12238
ProfileEvent_NetworkSendBytes:                                 4223
ProfileEvent_ThrottlerSleepMicroseconds:                       0
ProfileEvent_QueryMaskingRulesMatch:                           0
ProfileEvent_ReplicatedPartFetches:                            0
ProfileEvent_ReplicatedPartFailedFetches:                      0
ProfileEvent_ObsoleteReplicatedParts:                          0
ProfileEvent_ReplicatedPartMerges:                             0
ProfileEvent_ReplicatedPartFetchesOfMerged:                    0
ProfileEvent_ReplicatedPartMutations:                          0
ProfileEvent_ReplicatedPartChecks:                             0
ProfileEvent_ReplicatedPartChecksFailed:                       0
ProfileEvent_ReplicatedDataLoss:                               0
ProfileEvent_InsertedRows:                                     2
ProfileEvent_InsertedBytes:                                    3552
ProfileEvent_DelayedInserts:                                   0
ProfileEvent_RejectedInserts:                                  0
ProfileEvent_DelayedInsertsMilliseconds:                       0
ProfileEvent_DistributedDelayedInserts:                        0
ProfileEvent_DistributedRejectedInserts:                       0
ProfileEvent_DistributedDelayedInsertsMilliseconds:            0
ProfileEvent_DuplicatedInsertedBlocks:                         0
ProfileEvent_ZooKeeperInit:                                    0
ProfileEvent_ZooKeeperTransactions:                            37
ProfileEvent_ZooKeeperList:                                    12
ProfileEvent_ZooKeeperCreate:                                  0
ProfileEvent_ZooKeeperRemove:                                  0
ProfileEvent_ZooKeeperExists:                                  4
ProfileEvent_ZooKeeperGet:                                     21
ProfileEvent_ZooKeeperSet:                                     0
ProfileEvent_ZooKeeperMulti:                                   0
ProfileEvent_ZooKeeperCheck:                                   0
ProfileEvent_ZooKeeperClose:                                   0
ProfileEvent_ZooKeeperWatchResponse:                           0
ProfileEvent_ZooKeeperUserExceptions:                          0
ProfileEvent_ZooKeeperHardwareExceptions:                      0
ProfileEvent_ZooKeeperOtherExceptions:                         0
ProfileEvent_ZooKeeperWaitMicroseconds:                        226310
ProfileEvent_ZooKeeperBytesSent:                               4223
ProfileEvent_ZooKeeperBytesReceived:                           12238
ProfileEvent_DistributedConnectionFailTry:                     0
ProfileEvent_DistributedConnectionMissingTable:                0
ProfileEvent_DistributedConnectionStaleReplica:                0
ProfileEvent_DistributedConnectionFailAtAll:                   0
ProfileEvent_HedgedRequestsChangeReplica:                      0
ProfileEvent_CompileFunction:                                  0
ProfileEvent_CompiledFunctionExecute:                          0
ProfileEvent_CompileExpressionsMicroseconds:                   0
ProfileEvent_CompileExpressionsBytes:                          0
ProfileEvent_ExternalSortWritePart:                            0
ProfileEvent_ExternalSortMerge:                                0
ProfileEvent_ExternalAggregationWritePart:                     0
ProfileEvent_ExternalAggregationMerge:                         0
ProfileEvent_ExternalAggregationCompressedBytes:               0
ProfileEvent_ExternalAggregationUncompressedBytes:             0
ProfileEvent_SlowRead:                                         0
ProfileEvent_ReadBackoff:                                      0
ProfileEvent_ReplicaPartialShutdown:                           0
ProfileEvent_SelectedParts:                                    0
ProfileEvent_SelectedRanges:                                   0
ProfileEvent_SelectedMarks:                                    0
ProfileEvent_SelectedRows:                                     14188
ProfileEvent_SelectedBytes:                                    28716668
ProfileEvent_Merge:                                            5
ProfileEvent_MergedRows:                                       7094
ProfileEvent_MergedUncompressedBytes:                          14358334
ProfileEvent_MergesTimeMilliseconds:                           21
ProfileEvent_MergeTreeDataWriterRows:                          2
ProfileEvent_MergeTreeDataWriterUncompressedBytes:             3552
ProfileEvent_MergeTreeDataWriterCompressedBytes:               5536
ProfileEvent_MergeTreeDataWriterBlocks:                        1
ProfileEvent_MergeTreeDataWriterBlocksAlreadySorted:           1
ProfileEvent_MergeTreeDataProjectionWriterRows:                0
ProfileEvent_MergeTreeDataProjectionWriterUncompressedBytes:   0
ProfileEvent_MergeTreeDataProjectionWriterCompressedBytes:     0
ProfileEvent_MergeTreeDataProjectionWriterBlocks:              0
ProfileEvent_MergeTreeDataProjectionWriterBlocksAlreadySorted: 0
ProfileEvent_CannotRemoveEphemeralNode:                        0
ProfileEvent_RegexpCreated:                                    0
ProfileEvent_ContextLock:                                      22
ProfileEvent_StorageBufferFlush:                               0
ProfileEvent_StorageBufferErrorOnFlush:                        0
ProfileEvent_StorageBufferPassedAllMinThresholds:              0
ProfileEvent_StorageBufferPassedTimeMaxThreshold:              0
ProfileEvent_StorageBufferPassedRowsMaxThreshold:              0
ProfileEvent_StorageBufferPassedBytesMaxThreshold:             0
ProfileEvent_StorageBufferPassedTimeFlushThreshold:            0
ProfileEvent_StorageBufferPassedRowsFlushThreshold:            0
ProfileEvent_StorageBufferPassedBytesFlushThreshold:           0
ProfileEvent_StorageBufferLayerLockReadersWaitMilliseconds:    0
ProfileEvent_StorageBufferLayerLockWritersWaitMilliseconds:    0
ProfileEvent_DictCacheKeysRequested:                           0
ProfileEvent_DictCacheKeysRequestedMiss:                       0
ProfileEvent_DictCacheKeysRequestedFound:                      0
ProfileEvent_DictCacheKeysExpired:                             0
ProfileEvent_DictCacheKeysNotFound:                            0
ProfileEvent_DictCacheKeysHit:                                 0
ProfileEvent_DictCacheRequestTimeNs:                           0
ProfileEvent_DictCacheRequests:                                0
ProfileEvent_DictCacheLockWriteNs:                             0
ProfileEvent_DictCacheLockReadNs:                              0
ProfileEvent_DistributedSyncInsertionTimeoutExceeded:          0
ProfileEvent_DataAfterMergeDiffersFromReplica:                 0
ProfileEvent_DataAfterMutationDiffersFromReplica:              0
ProfileEvent_PolygonsAddedToPool:                              0
ProfileEvent_PolygonsInPoolAllocatedBytes:                     0
ProfileEvent_RWLockAcquiredReadLocks:                          26
ProfileEvent_RWLockAcquiredWriteLocks:                         0
ProfileEvent_RWLockReadersWaitMilliseconds:                    0
ProfileEvent_RWLockWritersWaitMilliseconds:                    0
ProfileEvent_DNSError:                                         0
ProfileEvent_RealTimeMicroseconds:                             0
ProfileEvent_UserTimeMicroseconds:                             0
ProfileEvent_SystemTimeMicroseconds:                           0
ProfileEvent_SoftPageFaults:                                   0
ProfileEvent_HardPageFaults:                                   0
ProfileEvent_VoluntaryContextSwitches:                         0
ProfileEvent_InvoluntaryContextSwitches:                       0
ProfileEvent_OSIOWaitMicroseconds:                             0
ProfileEvent_OSCPUWaitMicroseconds:                            0
ProfileEvent_OSCPUVirtualTimeMicroseconds:                     0
ProfileEvent_OSReadBytes:                                      0
ProfileEvent_OSWriteBytes:                                     0
ProfileEvent_OSReadChars:                                      0
ProfileEvent_OSWriteChars:                                     0
ProfileEvent_PerfCpuCycles:                                    0
ProfileEvent_PerfInstructions:                                 0
ProfileEvent_PerfCacheReferences:                              0
ProfileEvent_PerfCacheMisses:                                  0
ProfileEvent_PerfBranchInstructions:                           0
ProfileEvent_PerfBranchMisses:                                 0
ProfileEvent_PerfBusCycles:                                    0
ProfileEvent_PerfStalledCyclesFrontend:                        0
ProfileEvent_PerfStalledCyclesBackend:                         0
ProfileEvent_PerfRefCpuCycles:                                 0
ProfileEvent_PerfCpuClock:                                     0
ProfileEvent_PerfTaskClock:                                    0
ProfileEvent_PerfContextSwitches:                              0
ProfileEvent_PerfCpuMigrations:                                0
ProfileEvent_PerfAlignmentFaults:                              0
ProfileEvent_PerfEmulationFaults:                              0
ProfileEvent_PerfMinEnabledTime:                               0
ProfileEvent_PerfMinEnabledRunningTime:                        0
ProfileEvent_PerfDataTLBReferences:                            0
ProfileEvent_PerfDataTLBMisses:                                0
ProfileEvent_PerfInstructionTLBReferences:                     0
ProfileEvent_PerfInstructionTLBMisses:                         0
ProfileEvent_PerfLocalMemoryReferences:                        0
ProfileEvent_PerfLocalMemoryMisses:                            0
ProfileEvent_CreatedHTTPConnections:                           0
ProfileEvent_CannotWriteToWriteBufferDiscard:                  0
ProfileEvent_QueryProfilerSignalOverruns:                      0
ProfileEvent_CreatedLogEntryForMerge:                          0
ProfileEvent_NotCreatedLogEntryForMerge:                       0
ProfileEvent_CreatedLogEntryForMutation:                       0
ProfileEvent_NotCreatedLogEntryForMutation:                    0
ProfileEvent_S3ReadMicroseconds:                               0
ProfileEvent_S3ReadBytes:                                      0
ProfileEvent_S3ReadRequestsCount:                              0
ProfileEvent_S3ReadRequestsErrors:                             0
ProfileEvent_S3ReadRequestsThrottling:                         0
ProfileEvent_S3ReadRequestsRedirects:                          0
ProfileEvent_S3WriteMicroseconds:                              0
ProfileEvent_S3WriteBytes:                                     0
ProfileEvent_S3WriteRequestsCount:                             0
ProfileEvent_S3WriteRequestsErrors:                            0
ProfileEvent_S3WriteRequestsThrottling:                        0
ProfileEvent_S3WriteRequestsRedirects:                         0
ProfileEvent_QueryMemoryLimitExceeded:                         0
ProfileEvent_SleepFunctionCalls:                               0
ProfileEvent_SleepFunctionMicroseconds:                        0
CurrentMetric_Query:                                           0
CurrentMetric_Merge:                                           0
CurrentMetric_PartMutation:                                    0
CurrentMetric_ReplicatedFetch:                                 0
CurrentMetric_ReplicatedSend:                                  0
CurrentMetric_ReplicatedChecks:                                0
CurrentMetric_BackgroundPoolTask:                              0
CurrentMetric_BackgroundFetchesPoolTask:                       0
CurrentMetric_BackgroundMovePoolTask:                          0
CurrentMetric_BackgroundSchedulePoolTask:                      0
CurrentMetric_BackgroundBufferFlushSchedulePoolTask:           0
CurrentMetric_BackgroundDistributedSchedulePoolTask:           0
CurrentMetric_BackgroundMessageBrokerSchedulePoolTask:         0
CurrentMetric_CacheDictionaryUpdateQueueBatches:               0
CurrentMetric_CacheDictionaryUpdateQueueKeys:                  0
CurrentMetric_DiskSpaceReservedForMerge:                       0
CurrentMetric_DistributedSend:                                 0
CurrentMetric_QueryPreempted:                                  0
CurrentMetric_TCPConnection:                                   30
CurrentMetric_MySQLConnection:                                 0
CurrentMetric_HTTPConnection:                                  0
CurrentMetric_InterserverConnection:                           0
CurrentMetric_PostgreSQLConnection:                            0
CurrentMetric_OpenFileForRead:                                 23
CurrentMetric_OpenFileForWrite:                                0
CurrentMetric_Read:                                            2
CurrentMetric_Write:                                           0
CurrentMetric_NetworkReceive:                                  0
CurrentMetric_NetworkSend:                                     0
CurrentMetric_SendScalars:                                     0
CurrentMetric_SendExternalTables:                              0
CurrentMetric_QueryThread:                                     0
CurrentMetric_ReadonlyReplica:                                 0
CurrentMetric_MemoryTracking:                                  7359858424
CurrentMetric_EphemeralNode:                                   34
CurrentMetric_ZooKeeperSession:                                1
CurrentMetric_ZooKeeperWatch:                                  44
CurrentMetric_ZooKeeperRequest:                                0
CurrentMetric_DelayedInserts:                                  0
CurrentMetric_ContextLockWait:                                 0
CurrentMetric_StorageBufferRows:                               0
CurrentMetric_StorageBufferBytes:                              0
CurrentMetric_DictCacheRequests:                               0
CurrentMetric_Revision:                                        54454
CurrentMetric_VersionInteger:                                  21009005
CurrentMetric_RWLockWaitingReaders:                            0
CurrentMetric_RWLockWaitingWriters:                            0
CurrentMetric_RWLockActiveReaders:                             0
CurrentMetric_RWLockActiveWriters:                             0
CurrentMetric_GlobalThread:                                    618
CurrentMetric_GlobalThreadActive:                              159
CurrentMetric_LocalThread:                                     10
CurrentMetric_LocalThreadActive:                               0
CurrentMetric_DistributedFilesToInsert:                        0
CurrentMetric_BrokenDistributedFilesToInsert:                  0
CurrentMetric_TablesToDropQueueSize:                           0
CurrentMetric_MaxDDLEntryID:                                   911
CurrentMetric_MaxPushedDDLEntryID:                             0
CurrentMetric_PartsTemporary:                                  0
CurrentMetric_PartsPreCommitted:                               0
CurrentMetric_PartsCommitted:                                  4018
CurrentMetric_PartsOutdated:                                   153
CurrentMetric_PartsDeleting:                                   0
CurrentMetric_PartsDeleteOnDestroy:                            0
CurrentMetric_PartsWide:                                       612
CurrentMetric_PartsCompact:                                    3559
CurrentMetric_PartsInMemory:                                   0
CurrentMetric_MMappedFiles:                                    7
CurrentMetric_MMappedFileBytes:                                377135200
CurrentMetric_AsyncDrainedConnections:                         139
CurrentMetric_ActiveAsyncDrainedConnections:                   0
CurrentMetric_SyncDrainedConnections:                          0
CurrentMetric_ActiveSyncDrainedConnections:                    0

**Comment by genzgd** [comment]
That query log shows that the `SELECT 1` query took 6 milliseconds (see the `query_duration_ms` column).  Where did you run the query from and why do you think it took 15 minutes?  Where did you install ClickHouse?

**Comment by alexey-milovidov** [comment]
The time can be spent sending response to the client.
Example:
- query has finished in 6 milliseconds;
- the client hang up for 15 minutes for whatever reason;
- the server is trying to send the result to the client but blocked, because the client does not receive.

**Comment by lifulong** [comment]
> 

thanks very much for your reply

looks the query log i paste, the query finish event time is 2021-12-21 18:18:23 , and query start time in the same log is 2021-12-21 18:07:25

**Comment by lifulong** [comment]
> The time can be spent sending response to the client. Example:
> 
> * query has finished in 6 milliseconds;
> * the client hang up for 15 minutes for whatever reason;
> * the server is trying to send the result to the client but blocked, because the client does not receive.

thanks very much for your reply
i am sure it is not  hang from client, because there is at least ten querys from different client blocks, and block time is more than ten minutes, contains insert and select query

blow is clickhouse server log of 'SELECT 1' query (from 18:07:25 to 18:18:23):
2021.12.21 18:07:25.290326 [ 61946 ] {7b6daee0-8020-4a3c-8241-dca55e8ef1d8} <Debug> executeQuery: (from 10.103.106.18:32462, user: readonly) SELECT 1 
2021.12.21 18:18:23.250459 [ 61946 ] {7b6daee0-8020-4a3c-8241-dca55e8ef1d8} <Information> executeQuery: Read 1 rows, 1.00 B in 0.006988695 sec., 143 rows/sec., 143.09 B/sec.
2021.12.21 18:18:23.250666 [ 61946 ] {7b6daee0-8020-4a3c-8241-dca55e8ef1d8} <Debug> DynamicQueryHandler: Done processing query
2021.12.21 18:18:23.250711 [ 61946 ] {7b6daee0-8020-4a3c-8241-dca55e8ef1d8} <Debug> MemoryTracker: Peak memory usage (for query): 3.00 MiB.

**Comment by lifulong** [comment]
> thanks very much for your reply
> 
> looks the query log i paste, the query finish event time is 2021-12-21 18:18:23 , and query start time in the same log is 2021-12-21 18:07:25

thanks very much for your reply

looks the query log i paste, the query finish event time is 2021-12-21 18:18:23 , and query start time in the same log is 2021-12-21 18:07:25

**Comment by lifulong** [comment]
> That query log shows that the `SELECT 1` query took 6 milliseconds (see the `query_duration_ms` column). Where did you run the query from and why do you think it took 15 minutes? Where did you install ClickHouse?

thanks very much for your reply

looks the query log i paste, the query finish event time is 2021-12-21 18:18:23 , and query start time in the same log is 2021-12-21 18:07:25

**Comment by genzgd** [comment]
Can you reproduce?  Do you have system logs from that time?  Was ClickHouse running someplace (docker container, vm) where the host system could have hung it up somehow?

**Comment by alexey-milovidov** [comment]
We also have query profiler: https://clickhouse.com/docs/en/operations/optimizing-performance/sampling-query-profiler/
It records where each query execution thread has been at each time interval. By default, the interval is one second.
