### ISSUE TITLE
When send_progress_in_http_headers is true, the operation is abnormal and the return status code is 200

### ISSUE THREAD

**Issue by yangyund** [ClickHouse/ClickHouse#33205]
**Describe the unexpected behaviour**
 If the send_ progress_ in_ http_headers is true, execute the insert select operation. When the select data is small and there are exceptions, the Clickhouse returns 500, which is correct; **When there is too much select data and the statement is abnormal, Clickhouse returns 200.** The jar driver cannot recognize the exception and throw an exception upward.

**How to reproduce**
* Which ClickHouse server version to use 
    21.8.9.13
* jar driver version
    0.2.6
* Which interface to use, if matters
   [http://localhost:9001/?send_progress_in_http_headers=1&query_id=basdsadklsdf45dfag742dfg775sd4f42](url)
* execute sql
  `INSERT INTO dataops.ODS_USER_COPY_WS`
   `SELECT T1.*, T.USER_ID, T.STATE`
    `FROM (`
	`SELECT *`
	   `FROM ODS_INS_USER`
         `) T`
    `RIGHT JOIN ODS_JK_DATA T1 ON T.BILL_ID = T1.BILL_ID;`

**Expected behavior**
**_When there is too much select data and the statement is abnormal, Clickhouse returns 200._**
`HttpResponseProxy{HTTP/1.1 200 OK [Date: Mon, 27 Dec 2021 06:50:18 GMT, Connection: Keep-Alive, Content-Type: text/plain; charset=UTF-8, X-ClickHouse-Server-Display-Name: aiops-test1, Transfer-Encoding: chunked, Keep-Alive: timeout=3, X-ClickHouse-Progress: {"read_rows":"5849114","read_bytes":"229227165","written_rows":"0","written_bytes":"0","total_rows_to_read":"10734685"}, X-ClickHouse-Summary: {"read_rows":"10734685","read_bytes":"419925465","written_rows":"0","written_bytes":"0","total_rows_to_read":"10734685"}] ResponseEntityProxy{[Content-Type: text/plain; charset=UTF-8,Chunked: true]}}`

`Code: 349, e.displayText() = DB::Exception: Cannot convert NULL value to non-Nullable type: while converting source column STATE to destination column USER_STATE: while executing 'FUNCTION CAST(STATE :: 5, Int64 :: 9) -> CAST(STATE, Int64) Int64 : 8' (version 21.8.9.13 (official build))`
**jar driver checkForErrorAndThrow**
	`if (response.getStatusLine().getStatusCode() != HttpURLConnection.HTTP_OK) {`
        `    InputStream messageStream = entity.getContent();`
        `    byte[] bytes = StreamUtils.toByteArray(messageStream);`
        `    if (properties.isCompress()) {`
        `        try {`
        `            messageStream = new ClickHouseLZ4Stream(new ByteArrayInputStream(bytes));`
        `            bytes = StreamUtils.toByteArray(messageStream);`
        `        } catch (IOException e) {`
        `            log.warn("error while read compressed stream {}", e.getMessage());`
        `        }`
        `    }`
        `    EntityUtils.consumeQuietly(entity);`
        `    String chMessage = new String(bytes, StreamUtils.UTF_8);`
        `    throw ClickHouseExceptionSpecifier.specify(chMessage, properties.getHost(), properties.getPort());`
        `}`

**Comment by den-crane** [comment]
200 is sent before query started to execute because headers (progress) need to be sent after header 200.

Use wait_end_of_query https://clickhouse.com/docs/en/interfaces/http/#response-buffering

**Comment by yangyund** [comment]
> 200 在查询开始执行之前发送，因为头（进度）需要在头 200 之后发送。
> 
> 使用 wait_end_of_query https://clickhouse.com/docs/en/interfaces/http/#response-buffering


Just tested When the wait_ end_ of_query is 1 or 0, the HTTP request still returns a status code of 200,  The wait_ end_ of_query parameter should wait for the end of the query and then return the status code, but my SQL reported an error when inserting. There is no problem with the select
