### ISSUE TITLE
Questions about Backward Incompatible Change of upgrading from versions older than 20.5

### ISSUE THREAD

**Issue by taiyang-li** [ClickHouse/ClickHouse#33212]
I found one Backward Incompatible Change of clickhouse after clickhouse version v20.5 until v20.11

``` 
When upgrading from versions older than 20.5, if rolling update is performed and cluster contains both versions 20.5 or greater and less than 20.5, if ClickHouse nodes with old versions are restarted and old version has been started up in presence of newer versions, it may lead to Part ... intersects previous part errors. To prevent this error, first install newer clickhouse-server packages on all cluster nodes and then do restarts (so, when clickhouse-server is restarted, it will start up with the new version).
```

We are trying to upgrade from 20.3  to 21.10 in the production environment.  But we can't reproduce the issue above.  I have two questions about this:

- Why this Backward Incompatible Change not appeared after version v20.11. Is it solved now? 
- What's the detailed reproduce process of this issue?  

This issue is important to us,  hope for your reply.

**Comment by alexey-milovidov** [comment]
It happens only if you restart old version during upgrade and it will start again with old version while other replicas already upgraded and run with new versions. Even in this case it happens in rare cases.

**Comment by shuai-xu** [comment]
> 

@alexey-milovidov  If this do happen when upgrading, how to solve it? Is there any other way besides upgrading the replica with old version to new version?
