### ISSUE TITLE
optimized hashTable function next()

### ISSUE THREAD

**Issue by zbtzbtzbt** [ClickHouse/ClickHouse#33220]
In hashTable.h and other types hashtable

https://github.com/ClickHouse/ClickHouse/blob/0d87fa3c04fbce2f121592db35b34bd4f37ec9f6/src/Common/HashTable/HashTable.h#L245-L251

Can it be modified as follows?
```
const size_t mask = bufSize() - 1; 
...
size_t next(size_t pos) const        { ++pos; return pos & mask; }
```
I test local, it's faster than previous next() when hash table is big, it may help hashTable

**Comment by alexey-milovidov** [comment]
Caching mask may help. I tried it long time ago but did not observe performance improvement.
We can try again and see the results of performance tests.
