### ISSUE TITLE
How to use batch insert select ,I can't find a similar example

### ISSUE THREAD

**Issue by chen-shu-hao** [ClickHouse/ClickHouse#33245]
> Make sure to check documentation https://clickhouse.yandex/docs/en/ first. If the question is concise and probably has a short answer, asking it in Telegram chat https://telegram.me/clickhouse_en is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

> If you still prefer GitHub issues, remove all this text and ask your question here.

**Comment by chen-shu-hao** [comment]
How to use batch insert select ,I can't find a similar example

**Comment by chen-shu-hao** [comment]
I have a large number of insert select operations, how do I batch operations，because I'm taking too long to go through them

**Comment by den-crane** [comment]
What API do you use? What language ?

Basically batched insert this an insert which inserts several rows.

For example:

not batched
```
insert into ..... values ('a',1, '2020-01-01')
``` 

batched
```
insert into ..... values ('a',1, '2020-03-01'),  ('b,1, '2020-03-01'),  ('c',2, '2020-01-01'),  ('d',1, '2020-01-01'),  ....
```
you can insert millions values by a single insert.

The same with other formats, TSV, CSV, Parquet, they allow to insert millions rows by a single insert command.

**Comment by chen-shu-hao** [comment]
1. I use Java and ck jdbc

2. Because I am not inserting a certain value, What I do is the real-time update of a large number of user data, and some cumulative operations，I cannot use the existing TSV, CSV and parquet. Instead, I need to query and then insert ，
insert into table2

(column_name(s))

select column_ name(s)

FROM table1; 
,but I can only implement this one by one, not the effect I want

**Comment by den-crane** [comment]
You should ask these questions https://github.com/ClickHouse/clickhouse-jdbc/issues

https://github.com/ClickHouse/clickhouse-jdbc/tree/master/clickhouse-jdbc

```
Batch insert...

Tips:

    Use PreparedStatement instead of Statement
    Use input function whenever possible

// create table mytable(id String, ts DateTime64(3), desc Nullable(String)) engine=Memory

// 1. recommended as it performs the best
try (PreparedStatement ps = conn.prepareStatement(
    "insert into mytable select col1, col2 from input('col1 String, col2 DateTime64(3), col3 Int32')")) {
    // the column definition will be parsed so the driver knows there are 3 parameters: col1, col2 and col3
    ps.setString(1, "test"); // col1
    ps.setObject(2, LocalDateTime.now()); // col2, setTimestamp is slow and not recommended
    ps.setInt(3, 123); // col3
    ps.addBatch(); // parameters will be write into stream in binary format
    ...
    ps.executeBatch(); // stream everything on-hand into ClickHouse
}

// 2. easier to use but slower compare to input function
try (PreparedStatement ps = conn.prepareStatement("insert into mytable(* except (desc))")) {
    // the driver will issue query "select * except (desc) from mytable where 0" for type inferring
    // since desc column is excluded, we know there are only two parameters: col1 and col2
    ps.setString(1, "test"); // col1
    ps.setObject(2, LocalDateTime.now()); // col2
    ps.addBatch(); // parameters will be write into stream in binary format
    ...
    ps.executeBatch(); // stream everything on-hand into ClickHouse
}

// 3. not recommended as it's based on a large SQL
try (PreparedStatement ps = conn.prepareStatement("insert into mytable values(?,?,?)")) {
    ps.setString(1, "test"); // col1
    ps.setObject(2, LocalDateTime.now()); // col2
    ps.setString(3, null); // col3
    ps.addBatch(); // append parameters to the query
    ...
    ps.executeBatch(); // issue the composed query: insert into mytable values(...)(...)...(...)
}
```

**Comment by chen-shu-hao** [comment]
1.I use replacingmergetree
2.insert into table2  （select col1 + 1，col2 - 2 from table1 union all select col2 + 1，col 3- 2  from table1）  ; 
I just want to insert some fields. You need all fields to be consistent. Is there any way to do it similar to jsoneachrow? When I do mass update, I update the fields when I set them, and ignore them when I don't set them
INSERT INTO UserActivity FORMAT JSONEachRow {"PageViews":5, "UserID":"4324182021466249494", "Duration":146,"Sign":-1} {"UserID":"4324182021466249494","PageViews":6,"Duration":185,"Sign":1}
3.Or do you have any other way to implement this requirement，thanks

**Comment by den-crane** [comment]
Do you mean you need to update only some columns, but other columns get from the prev. version?

**Comment by zhicwu** [comment]
@den-crane, I think it's related to how null value was handled. It seems `insert_null_as_default` didn't consider the case of insert...select. Can we tag this issue as `bug` / `unfinished code`?

```sql
set insert_null_as_default = 1;

-- this works
insert into table2(col1, col2, col3) values (1, null, 3) (null, 2, 3)

-- but this does not
insert into table2(col1, col2, col3)
select 1, null, 3
union all
select null, 2, 3
```

**Comment by den-crane** [comment]
@zhicwu How it is related to batch inserts?

**Comment by zhicwu** [comment]
> @zhicwu How it is related to batch inserts?

It's not. The subject should be updated too.

I think @chen-shu-hao was asking how to write insert...select in a similar way of inserting values using JSONEachRow format, where no same column has to be specified. I'd suggest to consider to `insert_null_as_default` for insert...select case for consistency and better usability.

**Comment by den-crane** [comment]
> > @zhicwu How it is related to batch inserts?
> 
> It's not. The subject should be updated too.
> 
> I think @chen-shu-hao was asking how to write insert...select in a similar way of inserting values using JSONEachRow format, where no same column has to be specified. I'd suggest to consider to `insert_null_as_default` for insert...select case for consistency and better usability.

You lost me. I understood nothing.

**Comment by chen-shu-hao** [comment]
CREATE TABLE default.UserActivity
(
    `PageViews` UInt8,
    `UserID` String,
    `Duration` UInt64,
    `Sign` Int8
)
ENGINE = TinyLog

set insert_null_as_default = 1;

insert into UserActivity(PageViews, UserID, Duration) values (1, null, 3) (null, 2, 3)

insert into UserActivity(PageViews, UserID, Duration)
select 1, null, 3
union all
select null, 2, 3


 DB::Exception: Cannot convert NULL value to non-Nullable type: while converting source column `NULL` to destination column UserID: while executing 'FUNCTION _CAST(NULL :: 1, String :: 3) -> _CAST(NULL, String) String : 2'. (CANNOT_INSERT_NULL_IN_ORDINARY_COLUMN) (version 21.11.1.1)

**Comment by chen-shu-hao** [comment]
CREATE TABLE default.User_Activity
(
    `channel` SimpleAggregateFunction(anyLast, LowCardinality(Nullable(String))) ,
    `role_id` SimpleAggregateFunction(anyLast, Nullable(String)),
    `current_level` SimpleAggregateFunction(anyLast, Nullable(Int32)) 
)
ENGINE = TinyLog


insert into default.User_Activity (channel,role_id,current_level)
select 1, null, 3
union all
select null, 2, 3

This is useful

**Comment by pranavmehta94** [comment]
> Do you mean you need to update only some columns, but other columns get from the prev. version?

Hi @den-crane I am looking to achieve exactly this in clickhouse. Do you have a suggestion on how this can be achieved?
