### ISSUE TITLE
Поддержка типа Bool

### ISSUE THREAD

**Issue by az1s** [ClickHouse/ClickHouse#33244]
Запрос:
```
SELECT
  toTypeName(true),
  toTypeName(if(1=1,true,false))
```
возвращает значения UInt8 UInt8 вместо ожидаемых Bool Bool

В релизе 21.12.3.32 поддержка типа Bool анонсирована,
но перейти в запросе к типу Bool нельзя.
Например, если необходимо вывести явно тип в формате 
TSVWithNamesAndTypes.

**Comment by DarkWanderer** [comment]
На текущий момент, `CAST(...,'Bool')` - единственный способ получить значение такого типа

**Comment by alexey-milovidov** [comment]
@Avogar Why true/false are parsed as UInt8?
