### ISSUE TITLE
The Docker image usage documentation is not same as DockerHub

### ISSUE THREAD

**Issue by peter279k** [ClickHouse/ClickHouse#33248]
**Describe the issue**

It seems that the [DockerHub documentation](https://hub.docker.com/r/clickhouse/clickhouse-server/) and [Docker image usage documentation on this repository](https://github.com/ClickHouse/ClickHouse/tree/master/docker/server) are different.

I think the current problem is: the documentation on this repository cannot be synchronized to the doc on DockerHub automatically. 

**Additional context**
N/A

**Comment by Felixoid** [comment]
There is [some plugin](https://github.com/christian-korneck/docker-pushrm) for docker we can consider using.

**Comment by Felixoid** [comment]
I've updated the readme, but our robot doesn't have access to the description. We should update it manually for now
