### ISSUE TITLE
Arbitrator Node for Cluster

### ISSUE THREAD

**Issue by darthShadow** [ClickHouse/ClickHouse#33247]
Hi,

Is there any option to specify a third arbitrator node (which doesn't store any data) for clustering?

Something like this that's available for Galera Replication in MariaDB: https://galeracluster.com/library/documentation/arbitrator.html

> Galera Arbitrator is a member of a cluster that participates in voting, but not in the actual replication.

> Galera Arbitrator serves two purposes: When you have an even number of nodes, it functions as an odd node, to avoid split-brain situations. It can also request a consistent application state snapshot, which is useful in making backups.

> If one datacenter fails or loses its WAN connection, the node that sees the arbitrator—and by extension sees clients—continues operation.

If not an option right now, are there any plans to add it in the future or can it be considered for addition?

Thanks.

**Comment by UnamedRus** [comment]
ClickHouse use ZooKeeper/ClickHouse Keeper for replication.
https://zookeeper.apache.org/doc/current/zookeeperInternals.html#sc_quorum
Everything about voting and split brain protection handled here. (Outside of ClickHouse)

**Comment by darthShadow** [comment]
So I have been going through the docs, and doesn't the new Clickhouse Keeper use Raft instead of ZAB that's used by Zookeeper?

Raft doesn't seem to have the concept of a arbiter node but what NuRaft (the C++ library used by Clickhouse) does have is the zero-priority node: https://github.com/eBay/NuRaft/blob/master/docs/leader_election_priority.md

```
Priority 0 is a special value so that a node with zero priority will never be a leader.
```

This seems like what I want with the additional logic that all data sent to that node needs to be discarded. Can that be added easily in the clickhouse code itself or does it require changes upstream?

Thanks in advance for considering this.

---

As an aside, even MongoDB has the concept of an arbiter: https://docs.mongodb.com/manual/tutorial/add-replica-set-arbiter/
```
Arbiters are mongod instances that are part of a replica set but do not hold data (i.e. do not provide data redundancy). They can, however, participate in elections.

Arbiters have minimal resource requirements and do not require dedicated hardware. You can deploy an arbiter on an application server or a monitoring host.
```

**Comment by darthShadow** [comment]
Hi,

Just checking in case there is any further info required or if there is any alternative way to accomplish this.

Thanks.

**Comment by darthShadow** [comment]
Hi,

Just checking in case there is any further info required or if there is any alternative way to accomplish this.

Thanks.

**Comment by UnamedRus** [comment]
Answer remain the same:

Everything about voting and split brain protection handled in ZooKeeper or ClickHouse-Keeper. (Outside of ClickHouse actual data storage).

ClickHouse use ZooKeeper / ClickHouse-Keeper only for metadata and don't store any data in them.

**Comment by darthShadow** [comment]
Is there any way then to discard all the data sent to a `0` priority node since it will never be selected as the leader per the documentation of NuRaft? That solves my requirement of having an arbitrator node.

If not that, is there any way to have a 2-node cluster rather than the recommended minimum of 3 nodes?

Thanks.

**Comment by den-crane** [comment]
You can use `is there any way to have a 2-node cluster`. But if one node is down, other node became RO.
