### ISSUE TITLE
The  constructor of ContextAccess could casue coredump

### ISSUE THREAD

**Issue by huzhichengdd** [ClickHouse/ClickHouse#33253]
**Assigning this pointer to a smart pointer may cause coredump**

>path :  `src/Access/ContextAccess.cpp : 185`

`ContextAccess::ContextAccess(const AccessControlManager & manager_, const Params & params_)`
    `: manager(&manager_)`
    `, params(params_)`
`{`
   ` std::lock_guard lock{mutex};`

    subscription_for_user_change = manager->subscribeForChanges(
        *params.user_id, [this](const UUID &, const AccessEntityPtr & entity)
    {
        UserPtr changed_user = entity ? typeid_cast<UserPtr>(entity) : nullptr;
        std::lock_guard lock2{mutex};
        setUser(changed_user);
    });

    setUser(manager->read<User>(*params.user_id));
}
`
>path : `src/Access/AccessControlManager.cpp : 65`

`auto res = std::shared_ptr<ContextAccess>(new ContextAccess(manager, params));`

**It can be  reproduced on recent release because it has the same problem**

**How to reproduce**

*Manage user previlege in the way of RBAC
*   step 1. Use default account to keep creating table and  grant select and insert  of this  table to another user
*   step 2.  Do step 1. with two client and each client operating with 8 threads

**You could get this coredump**

>2021.10.18 06:35:55.202866 [ 148664 ] {} <Fatal> BaseDaemon: ########################################
2021.10.18 06:35:55.202934 [ 148664 ] {} <Fatal> BaseDaemon: (version 20.8.12.2, no build id) (from thread 126584) (query_id: 9070b92f-9683-4b30-8031-e41508030e58) Received signal Segmentation fault (11)
2021.10.18 06:35:55.202956 [ 148664 ] {} <Fatal> BaseDaemon: Address: 0x3f800008 Access: write. Address not mapped to object.
2021.10.18 06:35:55.202973 [ 148664 ] {} <Fatal> BaseDaemon: Stack trace: 0xf5a0fea 0xf5a1c4d 0xf5a23be 0xf5a35ba 0xf5e2d17 0xf5c4b5b 0xf5f18f3 0xf5e6ac6 0xf98c261 0xfacee48 0xfad0ad8 0xf8446fb 0xf84db2d 0xf84ec7c 0xf84fc35 0xf8537b0 0x918af6d 0x918961f 0x7f16bb094ea5 0x7f16ba9b196d
2021.10.18 06:35:55.203059 [ 148664 ] {} <Fatal> BaseDaemon: 3. DB::ContextAccess::calculateAccessRights() const @ 0xf5a0fea in /home/clickhouse/clickhouse-20.8.12.2-lts-100/bin/clickhouse
2021.10.18 06:35:55.203082 [ 148664 ] {} <Fatal> BaseDaemon: 4. DB::ContextAccess::setRolesInfo(std::__1::shared_ptr<DB::EnabledRolesInfo const> const&) const @ 0xf5a1c4d in /home/clickhouse/clickhouse-20.8.12.2-lts-100/bin/clickhouse
2021.10.18 06:35:55.203097 [ 148664 ] {} <Fatal> BaseDaemon: 5. DB::ContextAccess::setUser(std::__1::shared_ptr<DB::User const> const&) const @ 0xf5a23be in /home/clickhouse/clickhouse-20.8.12.2-lts-100/bin/clickhouse
2021.10.18 06:35:55.203147 [ 148664 ] {} <Fatal> BaseDaemon: 6. std::__1::__function::__func<DB::ContextAccess::ContextAccess(DB::AccessControlManager const&, DB::ContextAccessParams const&)::'lambda'(StrongTypedef<DB::UInt128, DB::UUIDTag> const&, std::__1::shared_ptr<DB::IAccessEntity const> const&), std::__1::allocator<DB::ContextAccess::ContextAccess(DB::AccessControlManager const&, DB::ContextAccessParams const&)::'lambda'(StrongTypedef<DB::UInt128, DB::UUIDTag> const&, std::__1::shared_ptr<DB::IAccessEntity const> const&)>, void (StrongTypedef<DB::UInt128, DB::UUIDTag> const&, std::__1::shared_ptr<DB::IAccessEntity const> const&)>::operator()(StrongTypedef<DB::UInt128, DB::UUIDTag> const&, std::__1::shared_ptr<DB::IAccessEntity const> const&) @ 0xf5a35ba in /home/clickhouse/clickhouse-20.8.12.2-lts-100/bin/clickhouse
2021.10.18 06:35:55.203194 [ 148664 ] {} <Fatal> BaseDaemon: 7. DB::IAccessStorage::notify(std::__1::vector<std::__1::tuple<std::__1::function<void (StrongTypedef<DB::UInt128, DB::UUIDTag> const&, std::__1::shared_ptr<DB::IAccessEntity const> const&)>, StrongTypedef<DB::UInt128, DB::UUIDTag>, std::__1::shared_ptr<DB::IAccessEntity const> >, std::__1::allocator<std::__1::tuple<std::__1::function<void (StrongTypedef<DB::UInt128, DB::UUIDTag> const&, std::__1::shared_ptr<DB::IAccessEntity const> const&)>, StrongTypedef<DB::UInt128, DB::UUIDTag>, std::__1::shared_ptr<DB::IAccessEntity const> > > > const&) @ 0xf5e2d17 in /home/clickhouse/clickhouse-20.8.12.2-lts-100/bin/clickhouse
2021.10.18 06:35:55.203210 [ 148664 ] {} <Fatal> BaseDaemon: 8. DB::DiskAccessStorage::updateImpl(StrongTypedef<DB::UInt128, DB::UUIDTag> const&, std::__1::function<std::__1::shared_ptr<DB::IAccessEntity const> (std::__1::shared_ptr<DB::IAccessEntity const> const&)> const&) @ 0xf5c4b5b in /home/clickhouse/clickhouse-20.8.12.2-lts-100/bin/clickhouse
2021.10.18 06:35:55.203225 [ 148664 ] {} <Fatal> BaseDaemon: 9. DB::MultipleAccessStorage::updateImpl(StrongTypedef<DB::UInt128, DB::UUIDTag> const&, std::__1::function<std::__1::shared_ptr<DB::IAccessEntity const> (std::__1::shared_ptr<DB::IAccessEntity const> const&)> const&) @ 0xf5f18f3 in /home/clickhouse/clickhouse-20.8.12.2-lts-100/bin/clickhouse
2021.10.18 06:35:55.203241 [ 148664 ] {} <Fatal> BaseDaemon: 10. DB::IAccessStorage::update(std::__1::vector<StrongTypedef<DB::UInt128, DB::UUIDTag>, std::__1::allocator<StrongTypedef<DB::UInt128, DB::UUIDTag> > > const&, std::__1::function<std::__1::shared_ptr<DB::IAccessEntity const> (std::__1::shared_ptr<DB::IAccessEntity const> const&)> const&) @ 0xf5e6ac6 in /home/clickhouse/clickhouse-20.8.12.2-lts-100/bin/clickhouse
2021.10.18 06:35:55.203285 [ 148664 ] {} <Fatal> BaseDaemon: 11. DB::InterpreterGrantQuery::execute() @ 0xf98c261 in /home/clickhouse/clickhouse-20.8.12.2-lts-100/bin/clickhouse
2021.10.18 06:35:55.203305 [ 148664 ] {} <Fatal> BaseDaemon: 12. DB::executeQueryImpl(char const*, char const*, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool, DB::ReadBuffer*) @ 0xfacee48 in /home/clickhouse/clickhouse-20.8.12.2-lts-100/bin/clickhouse
2021.10.18 06:35:55.203322 [ 148664 ] {} <Fatal> BaseDaemon: 13. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, DB::Context&, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>) @ 0xfad0ad8 in /home/clickhouse/clickhouse-20.8.12.2-lts-100/bin/clickhouse
2021.10.18 06:35:55.203341 [ 148664 ] {} <Fatal> BaseDaemon: 14. DB::DDLWorker::tryExecuteQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::DDLTask const&, DB::ExecutionStatus&) @ 0xf8446fb in /home/clickhouse/clickhouse-20.8.12.2-lts-100/bin/clickhouse
2021.10.18 06:35:55.203354 [ 148664 ] {} <Fatal> BaseDaemon: 15. DB::DDLWorker::processTask(DB::DDLTask&, std::__1::shared_ptr<zkutil::ZooKeeper> const&) @ 0xf84db2d in /home/clickhouse/clickhouse-20.8.12.2-lts-100/bin/clickhouse
2021.10.18 06:35:55.203373 [ 148664 ] {} <Fatal> BaseDaemon: 16. DB::DDLWorker::processTasks() @ 0xf84ec7c in /home/clickhouse/clickhouse-20.8.12.2-lts-100/bin/clickhouse
2021.10.18 06:35:55.203383 [ 148664 ] {} <Fatal> BaseDaemon: 17. DB::DDLWorker::runMainThread() @ 0xf84fc35 in /home/clickhouse/clickhouse-20.8.12.2-lts-100/bin/clickhouse
2021.10.18 06:35:55.203399 [ 148664 ] {} <Fatal> BaseDaemon: 18. ThreadFromGlobalPool::ThreadFromGlobalPool<void (DB::DDLWorker::*)(), DB::DDLWorker*>(void (DB::DDLWorker::*&&)(), DB::DDLWorker*&&)::'lambda'()::operator()() const @ 0xf8537b0 in /home/clickhouse/clickhouse-20.8.12.2-lts-100/bin/clickhouse
2021.10.18 06:35:55.203420 [ 148664 ] {} <Fatal> BaseDaemon: 19. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x918af6d in /home/clickhouse/clickhouse-20.8.12.2-lts-100/bin/clickhouse
2021.10.18 06:35:55.203436 [ 148664 ] {} <Fatal> BaseDaemon: 20. void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()> >(void*) @ 0x918961f in /home/clickhouse/clickhouse-20.8.12.2-lts-100/bin/clickhouse
2021.10.18 06:35:55.203463 [ 148664 ] {} <Fatal> BaseDaemon: 21. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
2021.10.18 06:35:55.203480 [ 148664 ] {} <Fatal> BaseDaemon: 22. clone @ 0xfe96d in /usr/lib64/libc-2.17.so.

**Comment by vdimir** [comment]
Closed by PR #33492. But there's no test. Is there example or it's really difficult to reproduce?
