### ISSUE TITLE
Cannot write `<secure/>` instead of `<secure>1</secure>` in cluster configuration.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#33270]

**Comment by cmsxbc** [comment]
Should this work for all possible boolean settings? It seems better to change in `Poco`

**Comment by alexey-milovidov** [comment]
It is not obvious should it work for all places... looks like it's ok for most places, but probably not for all.
Let's first fix for cluster.

**Comment by cmsxbc** [comment]
@alexey-milovidov OK, I'd like take it.
