### ISSUE TITLE
build clickhouse  clang-13: error: no such file or directory

### ISSUE THREAD

**Issue by yunfeng79** [ClickHouse/ClickHouse#33273]
CentOS Linux release 7.8
cmake version 3.21.0-rc1
ninja 1.9.0
clang-13.0.1

clickhouse-21.11.5.33

ninja

** ninja output**

FAILED: contrib/llvm/llvm/bin/llvm-tblgen 
: && /home/apps/llvmRelease/bin/clang++ -fdiagnostics-color=always -Xclang -fuse-ctor-homing -include /home/softs/clickhouse/clickhouse/ClickHouse/base/glibc-compatibility/glibc-compat-2.32.h -fsized-deallocation  -gdwarf-aranges -pipe -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -fasynchronous-unwind-tables -falign-functions=32   -Wall -Wno-unused-command-line-argument  -fdiagnostics-absolute-paths -fexperimental-new-pass-manager -Werror -w -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wcovered-switch-default -Wno-class-memaccess -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -fdiagnostics-color -ffunction-sections -fdata-sections -O2 -g -DNDEBUG -O3  -fno-pie --ld-path=/usr/bin/ld.gold -rdynamic -Wl,--no-undefined -Wl,-no-pie -fno-pie    -Wl,-O3 -Wl,--gc-sections contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/AsmMatcherEmitter.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/AsmWriterEmitter.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/AsmWriterInst.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/Attributes.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/CallingConvEmitter.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/CodeEmitterGen.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/CodeGenDAGPatterns.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/CodeGenHwModes.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/CodeGenInstruction.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/CodeGenMapTable.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/CodeGenRegisters.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/CodeGenSchedule.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/CodeGenTarget.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/DAGISelEmitter.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/DAGISelMatcherEmitter.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/DAGISelMatcherGen.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/DAGISelMatcherOpt.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/DAGISelMatcher.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/DFAEmitter.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/DFAPacketizerEmitter.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/DirectiveEmitter.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/DisassemblerEmitter.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/ExegesisEmitter.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/FastISelEmitter.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/FixedLenDecoderEmitter.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/GICombinerEmitter.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/GlobalISelEmitter.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/InfoByHwMode.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/InstrInfoEmitter.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/InstrDocsEmitter.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/IntrinsicEmitter.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/OptEmitter.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/OptParserEmitter.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/OptRSTEmitter.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/PredicateExpander.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/PseudoLoweringEmitter.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/RISCVCompressInstEmitter.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/RegisterBankEmitter.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/RegisterInfoEmitter.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/SDNodeProperties.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/SearchableTableEmitter.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/SubtargetEmitter.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/SubtargetFeatureInfo.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/TableGen.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/Types.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/X86DisassemblerTables.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/X86EVEX2VEXTablesEmitter.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/X86FoldTablesEmitter.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/X86ModRMFilters.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/X86RecognizableInstr.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/WebAssemblyDisassemblerEmitter.cpp.o contrib/llvm/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/CTagsEmitter.cpp.o -o contrib/llvm/llvm/bin/llvm-tblgen  contrib/llvm/llvm/lib/libLLVMSupport.a  contrib/llvm/llvm/lib/libLLVMTableGen.a  -lpthread  contrib/llvm/llvm/lib/libLLVMTableGenGlobalISel.a  contrib/llvm/llvm/lib/libLLVMTableGen.a  contrib/llvm/llvm/lib/libLLVMSupport.a  contrib/llvm/llvm/lib/libLLVMDemangle.a  -Wl,--start-group  base/glibc-compatibility/libglibc-compatibility.a  base/glibc-compatibility/memcpy/libmemcpy.a  contrib/libcxx-cmake/libcxx.a  contrib/libcxxabi-cmake/libcxxabi.a  contrib/libunwind-cmake/libunwind.a  -Wl,--end-group  -nodefaultlibs /home/apps/llvmRelease/lib/clang/13.0.1/lib/linux/libclang_rt.builtins-x86_64.a  -lc -lm -lrt -lpthread -ldl && :
clang-13: error: no such file or directory: '/home/apps/llvmRelease/lib/clang/13.0.1/lib/linux/libclang_rt.builtins-x86_64.a'
[3535/9800] Building CXX object contrib/llvm/llvm/lib/MC/MCParser/CMakeFiles/LLVMMCParser.dir/MasmParser.cpp.o

**Comment by alexey-milovidov** [comment]
Follow the instruction precisely: https://clickhouse.com/docs/en/development/build/
