### ISSUE TITLE
Deadlocks found in test environment

### ISSUE THREAD

**Issue by lingnancfy** [ClickHouse/ClickHouse#33282]
I can not truncate or detach table before restart clickhouse instance：and the ERROR information like that：

> DB::Exception: WRITE locking attempt on "DTDB.lineorder" has timed out! (120000ms) Possible deadlock avoided. Client should retry.

 I can obtain some information from the system table：

> SELECT
>     query_start_time,
>     query_id,
>     elapsed,
>     query,
>     ProfileEvents.Names,
>     ProfileEvents.Values,
>     thread_ids
> FROM system.processes AS p
> INNER JOIN system.query_log AS q ON p.query_id = q.query_id
> 
> Query id: ba820eb4-c980-47a2-b96d-b542e3615d88
> 
> ┌────query_start_time─┬─query_id─────────────────────────────┬─────────elapsed─┬─query──────────────────────────────────────┬─ProfileEvents.Names─────────────────────────────────────────────┬─ProfileEvents.Values─┬─thread_ids─┐
> │ 2021-12-28 20:48:29 │ e1f427df-4b30-4bb9-9a38-224efec5e8bc │ 54479.357350766 │ insert into lineorder  FORMAT TabSeparated
>  │ ['Query','InsertQuery','ContextLock','RWLockAcquiredReadLocks'] │ [1,1,8,2]            │ [1529677]  │
> │ 2021-12-28 20:48:30 │ 326b8342-7896-4d11-b473-223282570af1 │ 54479.341642614 │ insert into lineorder  FORMAT TabSeparated
>  │ ['Query','InsertQuery','ContextLock','RWLockAcquiredReadLocks'] │ [1,1,8,2]            │ [1530875]  │
> └─────────────────────┴──────────────────────────────────────┴─────────────────┴────────────────────────────────────────────┴─────────────────────────────────────────────────────────────────┴──────────────────────┴────────────┘

> tesspmrB0001.mrs-dviw.com :) WITH arrayMap(x -> demangle(addressToSymbol(x)), trace) AS all SELECT thread_id, query_id, arrayStringConcat(all, '\n') AS res FROM system.stack_trace where thread_id in (1530875,1529677) FORMAT TSV;
> 
> WITH arrayMap(x -> demangle(addressToSymbol(x)), trace) AS all
> SELECT
>     thread_id,
>     query_id,
>     arrayStringConcat(all, '\n') AS res
> FROM system.stack_trace
> WHERE thread_id IN (1530875, 1529677)
> FORMAT TSV
> 
> Query id: 51a7f53e-e07a-451d-a2d0-e78c86efea31
> 

> 1529677  e1f427df-4b30-4bb9-9a38-224efec5e8bc  pthread_cond_wait\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n__clone
> 1530875  326b8342-7896-4d11-b473-223282570af1 pthread_cond_wait\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n__clone

It appears that the insert statement keeps holding RWLockAcquiredReadLocks. As a result, the drop statement cannot obtain RWLockAcquiredWriteLocks.

**Comment by alexey-milovidov** [comment]
What version of ClickHouse do you use?
You can quickly install the latest version as following:
```
curl https://clickhouse.com/ | sh
```

It will also give you debug information to show more detailed stack traces.

**Comment by lingnancfy** [comment]
I will try to get more detailed stack traces
