### ISSUE TITLE
want to create a dashbord in Grafana to monitor inserted rates per interval for each table.

### ISSUE THREAD

**Issue by wangqinghuan** [ClickHouse/ClickHouse#33283]
this is a Elasticsearch index rate dashbord. Has any way to implement similar  dashbord for Clickhouse? 
![image](https://user-images.githubusercontent.com/22762150/147650230-fff2d374-5fb5-49ad-a6ed-4c127516921e.png)

Does Clickhouse collect metric about insert rates for each table ?

**Comment by den-crane** [comment]
You can get this info from system.part_log

```sql
SELECT
    database,
    table,
    toStartOfHour(event_time),
    count(),
    sum(rows),
    sum(bytes_uncompressed)
FROM system.part_log
WHERE (event_date >= (today() - 1)) AND (event_type = 'NewPart')
GROUP BY
    database,
    table,
    toStartOfHour(event_time)
ORDER BY
    database ASC,
    table ASC,
    toStartOfHour(event_time) ASC
LIMIT 10
```
