### ISSUE TITLE
Not sort the column again for sorted column on MergeJoin operation

### ISSUE THREAD

**Issue by Alex-Cheng** [ClickHouse/ClickHouse#33292]
**Describe the situation**
I have two tables and each table has a sorted column `id`. I want to join the two tables with id as join key, and adopt MergeJoin instead of HashJoin. However, by debugging I see the sortBlock() function is always invoked regardless of the column being a sort column.

**How to reproduce**
* Which ClickHouse server version to use
21.12.1.1

* Reproduce script
```SQL
create table cx1(event_id Int64, c1 Int64, c2 String, c3 Date, INDEX idx_c1 c1 TYPE minmax GRANULARITY 2, INDEX idx_c2 c2 TYPE bloom_filter GRANULARITY 1) ENGINE=MergeTree order by event_id;
insert into cx1(event_id, c1, c2, c3) select number, number * 10 + 3, number + 3, number + 10 from numbers(1000000);

create table cx2(event_id Int64, c4 Int64, c5 String, c6 Date) ENGINE=MergeTree order by event_id;
insert into cx2(event_id, c4, c5, c6) select number, rand(1), rand(2), rand(3) from numbers(1000000);


select * from cx1 t1 left join cx2 t2 on t1.event_id = t2.event_id settings join_algorithm='prefer_partial_merge'

```

**Expected performance**
Not sort column if the column is sort column (declared by SORT BY clause)

**Additional context**

**Comment by den-crane** [comment]
CH does not have pure MergeJoin. CH does not use indexes and order of the tables for joins. 
partial_merge is not MergeJoin. 
Improvements for JOIN is in RoadMap.
