### ISSUE TITLE
SAMPLE and Multi Tenancy 

### ISSUE THREAD

**Issue by amirvaza** [ClickHouse/ClickHouse#33328]
Hi all,

I have a quick but not simple question regarding sampling.

Currently, we are providing our customers analytics on their systems, ie: our CH cluster is serving multi tenant.

Table data is ordered by (_CustomerId_, _Timestamp_, _EventName_, _UserId_)
Currently partitioned by month (not relevant for the question)

We want to let our customers the ability to create funnels in real time on their users.

As you can see, in our table we first order by the _CustomerId_, kinda like localization, all of the customer data would be on the same granules.

One customer (C1) could have 10k rows of data, while another customer (C2) could have 1B rows.

Running windowFunnel on the entire data of customer C2 can be a disaster, so we want to add SAMPLing by UserId.

But how can we SAMPLE UserIds inside one customer?
More precisely, how can we use WHERE before SAMPLE? First filtering only the customer data, and then sampling its users?
Furthermore, how can we use the sampling between specific dates?

Thanks

**Comment by den-crane** [comment]
SAMPLing is applied as a part of WHERE but it is leveraged by a primary index.

You provide a very vague description but I guess you should never query data for several tenants in a single query and apply different SAMPLE for tenants. 

```
select ..... from ... sample .01
where tenantid = huge_tenant and ...

select ..... from ... sample 1
where tenantid = small_tenant and ...
```

https://kb.altinity.com/altinity-kb-queries-and-syntax/sampling-example/
https://kb.altinity.com/altinity-kb-queries-and-syntax/altinity-kb-sample-by/

**Comment by amirvaza** [comment]
1. I can't know which one is small and which one is big during query execution.
2. It won't work good if the big one is still only 1/100 portion of my data (or even less)

I would expect to be allowed to first filter and then sample by the result (at least filter by the ORDER BY..)

I thought about implementing it using modulo on the UserId, but obviously I would prefer SAMPLing if it would work

**Comment by den-crane** [comment]
>I can't know which one is small and which one is big during query execution.

Usually they implement SAMPLING is configurable by tenant. So basically they store in a backend metainformation which sempling to use with particular client.

>It won't work good if the big one is still only 1/100 portion of my data (or even less)

Then you should not use SAMPLING at all. It will not improve performance.

>I would expect to be allowed to first filter and then sample by the result (at least filter by the ORDER BY..)

No. The whole idea of SAMPLING is to read less data using PRIMARY INDEX, and filter out most of data on very early stages before reading it from the disk.

>I thought about implementing it using modulo on the UserId, but obviously I would prefer SAMPLing if it would work

Yes. It could be an option for you. Make proper tests, you may discover that it does not improve anything and just brings a complexity and it's not worth it.

**Comment by amirvaza** [comment]
> Yes. It could be an option for you. Make proper tests, you may discover that it does not improve anything and just brings a complexity and it's not worth it.
>
@den-crane Please elaborate, 
Why wouldn't it improve?
How to make it improve?
What would be a better solution for my use case?
What if I duplicate the data to another table and order by this modulo?

Thanks

**Comment by den-crane** [comment]
@amirvaza check this carefully https://kb.altinity.com/altinity-kb-queries-and-syntax/sampling-example/

**Comment by amirvaza** [comment]
My test:
290k users
Rows: 225M

Indeed using modulo on the same table improved it from 4.3s to 0.8s
Using a new table(need to duplicate the data), the same order by, but instead of `UserId`, ordering by `UserId%100` improved it to 0.33s
Using another table, changing order by columns order, improved it even to 0.18s

In the link its not clear why the granularity of timestamp affect the results particularly for funnels.
I understand why it could make everything slower, not specifically only funnels.

I got my answers.
Thanks.
