### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by loyd** [ClickHouse/ClickHouse#33320]
**ClickHouse version**: 21.6.6.51 (cannot update until https://github.com/ClickHouse/ClickHouse/issues/32744 is released).

Memory usage is increasing constantly and, when the RSS limit is reached, CH fails random queries (inserts into/selects from different tables). We cannot find where the memory is.

Additional information:
* All queries are done by users with `max_memory_usage=750MiB`.
* We insert rows in batches every 100ms into 32 `Buffer` tables, totally ~50k rows/s. 
* We use live views and don't use dictionaries.

## Metrics
Metrics (sharp drops are restarts). Here we set `max_server_memory_usage_to_ram_ratio` to `0.3` (37GiB) to show peaks. The same behavior remains with `0.9` (114GiB).
![2021-12-30_08-38-15](https://user-images.githubusercontent.com/952180/147724745-b65a304d-e9e2-4308-b9ce-1ed454464f13.png)

Suspiciously high values of purged metrics.

Don't see any correlation with different events:
![2021-12-30_09-26-08](https://user-images.githubusercontent.com/952180/147727209-51595b26-8924-4554-9daa-bd189a62118b.png)

## Attempts to find the reason
```sql
SELECT formatReadableSize(sum(total_bytes)) FROM system.tables WHERE engine IN ('Memory','Set','Join');
```
```
172.57 KiB
```
---
```sql
SELECT formatReadableSize(sum(memory_usage)) FROM system.merges;
```
```
249.99 MiB
```
---
```sql
SELECT formatReadableSize(sum(memory_usage)) FROM system.processes;
```
```
36.97 MiB
```
---
```sql
SELECT formatReadableSize(sum(memory_usage)), formatReadableSize(sum(peak_memory_usage)) FROM system.processes;
```
```
0.00 B                                │ 0.00 B
```
---
```sql
SELECT
    metric,
    formatReadableSize(value)
FROM system.asynchronous_metrics
WHERE metric IN ('UncompressedCacheBytes', 'MarkCacheBytes')
```
```
┌─metric─────────────────┬─formatReadableSize(value)─┐
│ UncompressedCacheBytes │ 0.00 B                    │
│ MarkCacheBytes         │ 55.91 MiB                 │
└────────────────────────┴───────────────────────────┘
```
---
```sql
SELECT
    formatReadableSize(sum(primary_key_bytes_in_memory)) AS primary_key_bytes_in_memory,
    formatReadableSize(sum(primary_key_bytes_in_memory_allocated)) AS primary_key_bytes_in_memory_allocated
FROM system.parts
```
```
┌─primary_key_bytes_in_memory─┬─primary_key_bytes_in_memory_allocated─┐
│ 337.63 MiB                  │ 624.06 MiB                            │
└─────────────────────────────┴───────────────────────────────────────┘
```

## Logs
Regularly (1-2 times per hour) wee see the following pattern in logs:
```
2021.12.28 10:22:33.397711 [ 1854971 ] {1822bef8-7c15-42d4-9113-a1bce442a4c0} <Error> executeQuery: Code: 24, e.displayText() = DB::Exception: Cannot write to ostream at offset 59798 (version 21.6.6.51 (official build)) (from 10.221.8.220:46046) (in query: WATCH lv_25bed493f7b3a63aade737679c0974f3f320bd99 FORMAT JSONEachRowWithProgress ), Stack trace (when copying this message, always include the lines below):
2021.12.28 10:22:33.400234 [ 1854971 ] {1822bef8-7c15-42d4-9113-a1bce442a4c0} <Error> DynamicQueryHandler: Code: 24, e.displayText() = DB::Exception: Cannot write to ostream at offset 59798, Stack trace (when copying this message, always include the lines below):
2021.12.28 10:22:33.400944 [ 1854971 ] {1822bef8-7c15-42d4-9113-a1bce442a4c0} <Error> DynamicQueryHandler: Cannot send exception to client: Code: 24, e.displayText() = DB::Exception: Cannot write to ostream at offset 59871, Stack trace (when copying this message, always include the lines below):
2021.12.28 10:22:33.402017 [ 1854971 ] {} <Error> ServerErrorHandler: Poco::Exception. Code: 1000, e.code() = 32, e.displayText() = I/O error: Broken pipe, Stack trace (when copying this message, always include the lines below):
```
This may be related to the client library (maybe doesn't read the whole response).

LiveView is simple enough:
```
CREATE LIVE VIEW algo.lv_17cc0dbf4232839381bb35d6b65ee11f8b51b1bb WITH TIMEOUT 5
(`now64(9)` DateTime64(9)) AS
SELECT now64(9) FROM ... WHERE some_id IN
(
    SELECT some_id
    FROM subscribers
)
LIMIT 1
```

---

What can I check else?

I haven't found related issues, except for https://github.com/ClickHouse/ClickHouse/issues/32750, but we don't use `cancel_http_readonly_queries_on_client_close`.

**Comment by den-crane** [comment]
>ClickHouse version: 21.6.6.51 

You mean you upgraded CH recently? Which version you used before the upgrade?

>RSS limit

What is RSS limit?

>CH fails random queries

What is the exact error message?

Did you check real memory consumption (real RSS) from Linux? 

I guess you observe MemoryTracker issue ? https://github.com/ClickHouse/ClickHouse/issues?q=is%3Aissue+%22Memory+Tracker%22

>This may be related to the client library (maybe doesn't read the whole response).

What is the client library?

**Comment by loyd** [comment]
> You mean you upgraded CH recently? Which version you used before the upgrade?

No, but we have started paying serious attention to the problem now. I meant that we're going to upgrade once https://github.com/ClickHouse/ClickHouse/issues/32744 is released.

> What is RSS limit?

I mean `max_server_memory_usage_to_ram_ratio`

> What is the exact error message?

```
2021.12.28 00:27:30.336532 [ 3984779 ] {} <Error> ServerErrorHandler: Code: 241, e.displayText() = DB::Exception: Memory limit (total) exceeded: would use 37.73 GiB (attempt to allocate chunk of 32 bytes), maximum: 37.66 GiB, Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x8b770fa in /usr/bin/clickhouse
1. DB::Exception::Exception<char const*, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, long&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const*&&, char const*&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, long&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&) @ 0x8b8bf69 in /usr/bin/clickhouse
2. MemoryTracker::alloc(long) @ 0x8b8b8bd in /usr/bin/clickhouse
3. Poco::Net::SocketAddress::SocketAddress() @ 0x12a6e742 in /usr/bin/clickhouse
4. Poco::Net::TCPServer::run() @ 0x12a7a079 in /usr/bin/clickhouse
5. Poco::ThreadImpl::runnableEntry(void*) @ 0x12bb12ea in /usr/bin/clickhouse
6. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
7. clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
 (version 21.6.6.51 (official build))
```

> Did you check real memory consumption (real RSS) from Linux?

Yes, the same as the `MemoryTracking` metric

> What is the client library?

Custom HTTP-based library (https://github.com/loyd/clickhouse.rs), I think it's possible that the `WATCH` queries don't read the whole response in some cases, but I haven't checked yet.

**Comment by loyd** [comment]
> I guess you observe MemoryTracker issue ? https://github.com/ClickHouse/ClickHouse/issues?q=is%3Aissue+%22Memory+Tracker%22

Of course, I haven't found related enough issues. Some (especially, https://github.com/ClickHouse/ClickHouse/issues/32750) looks similar, but use special options and so on.

**Comment by alexey-milovidov** [comment]
Does it reproduce on ClickHouse version 21.12?

To quickly test the new version, run:
```
curl https://clickhouse.com/ | sh
```

**Comment by den-crane** [comment]
I was trying to repro it. No luck so far.

```
21.6.6.51

create table subs (A Int64) Engine=MergeTree order by tuple();


for i in `seq 10000`; \
   do echo -n $i" "; \
   clickhouse-client -q "select formatReadableSize(value) FROM system.asynchronous_metrics WHERE metric='MemoryResident'"; \
   s='CREATE LIVE VIEW 'lv_${i}' WITH TIMEOUT 5 (n DateTime64(9)) AS SELECT now64(9) n FROM subs LIMIT 1'; \
   echo $s| curl  -s -o /dev/null --data-binary @- 'http://localhost:8123/?allow_experimental_live_view=1&query='; \
   curl -o /dev/null -s -m.5 "http://localhost:8123/?allow_experimental_live_view=1&query=WATCH+lv_${i}+FORMAT+JSONEachRowWithProgress"; \
done|tee out

```

**Comment by loyd** [comment]
We will check the latest version once https://github.com/ClickHouse/ClickHouse/pull/32751 is released.

**Comment by loyd** [comment]
@alexey-milovidov, we've checked master, still leaks in `22.1.1.2542`.

![2022-01-26_16-40-55](https://user-images.githubusercontent.com/952180/151173491-c1cee9d1-94cd-4e28-8f00-f4c3c546193d.png)

Reopen the issue, please. What kind of information should we provide?

**Comment by den-crane** [comment]
@loyd  any clue how to reproduce it?

Try my example but with your "HTTP-based library" instead of curl

**Comment by alexey-milovidov** [comment]
The only suspect is live view
> We use live views

because it is an experimental feature with low amount of developers attention to it.

Does the issue reproduce if live views are not used?

**Comment by loyd** [comment]
> Does the issue reproduce if live views are not used?

We need to modify our code to work without LV because now we highly depend on them.
Write here, when we check.

**Comment by derlaft** [comment]
Steps to reproduce:

1) create table
```
CREATE TABLE test_leak
(
    `timestamp_ms` Int64
)
ENGINE = MergeTree
ORDER BY timestamp_ms
```

2) create live view with timeout

```
CREATE LIVE VIEW test_leak_view WITH TIMEOUT 5 AS
SELECT *
FROM test_leak
WHERE timestamp_ms > (
    SELECT max(timestamp_ms)
    FROM test_leak
)
```

3) make a query

```
curl -v "http://clickhouse-instance/?allow_experimental_live_view=1&query=watch%20cloki.test_leak_view%20format%20Null"
```

Query hangs forever. Even after it's aborted the process can be seen in `system.process`:

```
SELECT
    query_id,
    query,
    elapsed
FROM system.processes
WHERE position(query, 'watch') > 0

Query id: a9d4c9cd-43bd-4656-9439-6d2cda51196e

┌─query_id─────────────────────────────┬─query──────────────────────────────────────────────────────────────────────────────────────┬───────elapsed─┐
│ 68bf25fd-2a8f-46e5-9d57-76994b60a682 │ watch cloki.test_leak_view format Null
                                                     │ 170.510890785 │
│ a9d4c9cd-43bd-4656-9439-6d2cda51196e │ SELECT query_id, query, elapsed FROM system.processes where position('watch' in query) > 0 │   0.000764696 │
└──────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────┴───────────────┘
```

Tested in: clickhouse-server-22.1.3.7

**Comment by derlaft** [comment]
> The [JSONEachRowWithProgress](https://clickhouse.com/docs/en/interfaces/formats/#jsoneachrowwithprogress) format should be used when watching [LIVE VIEW](https://clickhouse.com/docs/en/sql-reference/statements/create/view/#live-view) tables over the HTTP interface. The progress messages will be added to the output to keep the long-lived HTTP connection alive until the query result changes. The interval between progress messages is controlled using the [live_view_heartbeat_interval](https://clickhouse.com/docs/en/sql-reference/statements/create/view/#live-view-settings) setting.

Ugh, noticed this in documentation. With this format it works as intended.

**Comment by loyd** [comment]
That's another problem (I've faced it in https://github.com/ClickHouse/ClickHouse/issues/22996), likely not related here, but also inconvenient.
