### ISSUE TITLE
Kafka table consumer continuously exceeds maximum poll interval

### ISSUE THREAD

**Issue by Yueyu-Marky** [ClickHouse/ClickHouse#33321]
#### Description

Hi, I've been trying out Clickhouse for some time. I have built a cluster formed by 4 nods, with 2 shards and the replica factor is 1.

When I tried to use kafka table and attach a materialized to it, I though it will be good to set kafka_num_consumers to 3 because the topic I set to be consumed has 3 partitions.

But when I started to produce some messages to test it, precisely, 30000 messages to the topic and evenly(almost) distributed to three partitions,  I found that one partition cound not be consumed, indicated that one of the consumer didn't start consuming.

After a review of the log, it showed something like this:

~~~
2021.12.30 14:00:16.096987 [ 32591 ] {} <Warning> StorageKafka (testlog_kafka): [rdk:MAXPOLL] [thrd:main]: Application maximum poll interval (300000ms) exceeded by 1ms (adjust max.poll.interval.ms for long-running message processing): leaving group
~~~

 At around 5 minutes later, those messages finally got consumed, but the warning log is still coming.

After that, I repeat producing messages to that topic and every time I get the same result: one of the consumer is not getting any messages only after about five minutes when the warning log shows up, and that's when it receive those messages.

#### Question

My question is - is that something I miss understand or I mess up the configuration, causing those abnormal appearance?  Changing the kafka_num_consumers to 1 seems to solve the problem, I always get the message branch in time, But I would like to know why. 

**ch version.**21.12.2

#### Configuration Info 

cluster config:

~~~xml
<remote_servers>
    <ch_platform_cluster_2s_2r>
        <shard>
            <internal_replication>true</internal_replication>
            <replica>
                <host>ch-node1</host>
                <port>9000</port>
            </replica>
            <replica>
                <host>ch-node3</host>
                <port>9000</port>
            </replica>
        </shard>
        <shard>
            <internal_replication>true</internal_replication>
            <replica>
                <host>ch-node2</host>
                <port>9000</port>
            </replica>
            <replica>
                <host>ch-node4</host>
                <port>9000</port>
            </replica>
        </shard>
    </ch_platform_cluster_2s_2r>
</remote_servers>
~~~

Here are the query statements for more details:

1. create test database

~~~sql
CREATE DATABASE test ON CLUSTER ch_platform_cluster_2s_2r;
~~~

2. create tables to store actual data

~~~sql
CREATE TABLE test.testlog ON CLUSTER
ch_platform_cluster_2s_2r
(
    `_timestamp` DateTime64(3, 'Europe/London'),
    `domainname` String,
    `platform` String,
    `sc_byte` Float32
) ENGINE = ReplicatedMergeTree('/clickhouse/test_cluster/test/testlog/{shard}', '{replica}')
PARTITION BY toYYYYMM(_timestamp)
ORDER BY (_timestamp, platform);
~~~

3. create distributed table

~~~sql
CREATE TABLE test.testlog_all ON CLUSTER
ch_platform_cluster_2s_2r
(
    `_timestamp` DateTime64(3, 'Europe/London'),
    `domainname` String,
    `platform` String,
    `sc_byte` Float32
) ENGINE = Distributed(ch_platform_cluster_2s_2r, 'test', 'testlog', rand());
~~~

4. create tables to do aggregations

~~~sql
CREATE TABLE test.testlog_target ON CLUSTER
ch_platform_cluster_2s_2r
(
    `day` DateTime64(3, 'Europe/London'),
    `domainname` String,
    `platform` String,
    `count` Float32,
    `max_value_state` AggregateFunction(max, Float32),
    `min_value_state` AggregateFunction(min, Float32),
    `avg_value_state` AggregateFunction(avg, Float32)
) ENGINE = ReplicatedSummingMergeTree('/clickhouse/test_cluster/test/testlog_target/{shard}', '{replica}')
PARTITION BY toYYYYMMDD(day)
ORDER BY (platform, day);
~~~

5. create MT view using TO statement

~~~sql
CREATE MATERIALIZED VIEW test.testlog_mv ON CLUSTER
ch_platform_cluster_2s_2r
TO test.testlog_target AS
SELECT
    toStartOfDay(_timestamp) AS day,
    domainname,
    platform,
    count(*) AS count,
    maxState(sc_byte) AS max_value_state,
    minState(sc_byte) AS min_value_state,
    avgState(sc_byte) AS avg_value_state
FROM test.testlog
GROUP BY
    domainname,
    platform,
    day
ORDER BY
    domainname ASC,
    platform ASC,
    day ASC;
~~~

6. create distributed table for target table

~~~sql
CREATE TABLE test.testlog_target_all ON CLUSTER
ch_platform_cluster_2s_2r
(
    `day` DateTime64(3, 'Europe/London'),
    `domainname` String,
    `platform` String,
    `count` Float32,
    `max_value_state` AggregateFunction(max, Float32),
    `min_value_state` AggregateFunction(min, Float32),
    `avg_value_state` AggregateFunction(avg, Float32)
) ENGINE = Distributed(ch_platform_cluster_2s_2r, 'test', 'testlog_target', rand());
~~~

7. create kafka engine table, **only at node1**

~~~sql
CREATE TABLE test.testlog_kafka
(
    `k_timestamp` String,
    `k_domainname` String,
    `k_platform` String,
    `k_sc_byte` Float32
) ENGINE = Kafka()
SETTINGS
    kafka_broker_list = 'kafka_host:19092',
    kafka_topic_list = 'test-clickhouse-test',
    kafka_group_name = 'my_kafka_test_group',
    kafka_row_delimiter = '\n',
    kafka_format = 'JSONEachRow',
    kafka_num_consumers = 3,
    kafka_max_block_size = 524288;
~~~

8. create MT view to consume message from kafka table, only at ch-node1 too

~~~sql
CREATE MATERIALIZED VIEW test.testlog_kafka_consumer
TO test.testlog_all
AS
SELECT
    toDateTime(k_timestamp) AS _timestamp,
    k_domainname AS domainname,
    k_platform AS platform,
    k_sc_byte AS sc_byte
FROM test.testlog_kafka;
~~~

**Comment by tiagokrebs** [comment]
This is more a librdkafka thing than a Clickhouse one.  
Take a look at [this issue](https://github.com/edenhill/librdkafka/issues/2971) on librdkafka project.

> max.poll.interval.ms works like a watchdog between the consumer and the application, the application needs to call poll() at least this often or the consumer will deem the application malfunctional and then leave the group.
max.poll.interval.ms should be set to the maximum allowed per-message processing time. If your processing can get stuck you need some other mechanism to unstuck the application so that poll() is called in due time.

Even though you have 3 partitions in the Kafka topic seems like you could have an overpowering consumer when you set `kafka_num_consumers=3`. If you are not experiencing LAG issues there is no need to increase this because librdkafka already does a great job attaching consumer threads to partitions.  
If you like, test allowing each consumer/partition to flush messages independently using [`kafka_thread_per_consumer=1`](https://clickhouse.com/docs/en/engines/table-engines/integrations/kafka/#table_engine-kafka-creating-a-table) parameter on your Kafka Engine Table.

**Comment by den-crane** [comment]
>4 nods /  kafka_num_consumers to 3 

Kafka partitions are not shared among consumers. Each consumer poll own kafka partition (it's not related to Clickhouse, it's a common rule for Kafka).

**Topic should have at least 4 (nodes) *3 (kafka_num_consumers)  *2 (at least 2 partitions per consumer)= 24 partitions.** 

I suggest to create a topic with 16 partitions and set kafka_num_consumers=1.

**Comment by Yueyu-Marky** [comment]
@tiagokrebs Thanks for reply. After another test, this helps:
> If you like, test allowing each consumer/partition to flush messages independently using **kafka_thread_per_consumer=1** parameter on your Kafka Engine Table.

After apply kafka_thread_per_consumer=1 to the table config while maintaining kafka_num_consumers=3, the problem has gone - there is no more MAXPOLL warning log, and messages distributed in three partitions get consumed quickly.
I suppose three separated consumer threads can properly get their own partition, while using kafka_thread_per_consumer=0 prevents librdkafka from getting their partitions assigned.

Although, I still don't know how to explain that, since I did actually find three consumers in monitor, each consumer gets assigned with exactly one partition(one of them unable to consume any and leaves the group after 5 min) using config  kafka_num_consumers=3 and kafka_thread_per_consumer=0(default), while using kafka_num_consumers=1 it predictably only shows one consumer without suffix like '-01' in monitor, and has no problem consuming multiple partitions.

All in all please accept my appreciation.

**Comment by Yueyu-Marky** [comment]
@den-crane Thanks for reply.

I may understand that:
> 4 nodes, 16 partitions - so each node has a kafka table, and all of the 4 kafka table use the same group id while every kafka table has only 1 consumer in order to split 16 partitions  and assign to 4 consumers

to maximize the parallelism.

I'm gonna try it, and please accept my appreciation.
