### ISSUE TITLE
avgForEach is not specialised

### ISSUE THREAD

**Issue by crakjie** [ClickHouse/ClickHouse#3333]
The method `avgForEach` returns `Array(Float64)` when used on `Array(Float32)` column.
This is forcing to use `arrayMap` with `toFloat32` to have the `Array(Float32)` back.
I think this could be more effective to have a specialized version which is not keeping `Float64` in memory in forcing another loop to convert it in the initial type.

**Comment by filimonov** [comment]
avg always return Float64 (the only exception is Decimal):
```select toTypeName( arrayReduce('avg',[0]) );```

It's here:
https://github.com/yandex/ClickHouse/blob/47dd1730072d98ff2d598edbbabb3d108a37373d/dbms/src/AggregateFunctions/AggregateFunctionAvg.h#L47

**Comment by GSokol** [comment]
Could I implement the new function which should return Float32?

**Comment by abyss7** [comment]
Sure - it would be appreciated.
