### ISSUE TITLE
Having a weird experience with duplicates?

### ISSUE THREAD

**Issue by BirdyUK** [ClickHouse/ClickHouse#33357]
Sorry to be that guy to open an issue that is probably obvious! I have tried to figure out the issue for the last couple of hours but seems to be hitting a brick wall so thought someone with way more experience might be able to help out  😊

I have a table with the following structure:

```
CREATE TABLE test.t_table (
                    symbol LowCardinality(String),
                    ex_timestamp DateTime64(3),
                    local_timestamp DateTime64(3),
                    price Decimal(38, 8),
                    amount Decimal(38, 8),
                    size Decimal(38, 8)
) ENGINE = MergeTree()
      PARTITION BY toYYYYMM(timestamp)
      ORDER BY (symbol, ex_timestamp, local_timestamp, price, amount, size);
```
	  
	  
I then populated the table with the following:

```
INSERT INTO test.t_table
SELECT
       symbol,
       fromUnixTimestamp64Milli(CAST(toInt64(ex_timestamp) / 1000, 'Int64'), 'UTC') as ts1,
       fromUnixTimestamp64Milli(CAST(toInt64(local_timestamp) / 1000, 'Int64'), 'UTC') as ts2,
       toFloat64OrZero(price) as price,
       toFloat64OrZero(amount) as amount,
       toFloat64OrZero(size) as size
FROM test.source_table;
```

However if i run any type of SELECT query, it returns duplicate records for every row, So for example every row comes twice, to verify this i performed the following duplicate check:

```
SELECT
	count() AS cnt
FROM  test.t_table
WHERE t_table.timestamp = '2021-12-30'
GROUP BY *
HAVING cnt > 1

┌─cnt─┐
│   2 │
└─────┘ 

```

Which returns the count of 2 but if i run the exact same query on the source table it returns a count of 0.

At this point i am thinking there has to be something wrong with populating the table which has caused duplicates but what is confusing me is the fact the total count of rows in both tables are exactly the same.

Could this be an issue with the LowCardinality, Partition or the way i have the ORDER BY above?

My last resort is to delete all data from the test_table and re-insert but there is several billion rows so i thought asking for advice prior might help reduce the risk of the outcome being the same.

Thanks guys and happy new year! :-)

**Comment by den-crane** [comment]
1. CH version?
2. `timestamp = '2021-12-30'` , I guess timestamp is DateTime64 , and this comparison DateTime64 = '2021-12-30' can produce unexpected behaviour in some versions.
3. I don't see `timestamp` column in the t_table
4. show create table source_table
5. GROUP BY * -- I have no idea what `*` means in this case. I guess it can include  cnt column. Use a list of real columns.
6. I think if you execute `SELECT * FROM ... WHERE t_table.timestamp = '2021-12-30'` from both tables it will be more clear.

**Comment by BirdyUK** [comment]
Hi Den,

Apologies for not including the additional information, I can confirm the query you mentioned above was already tried during the debugging phrase to which returned duplicates in the new destination table but no duplicates was found in the source table.

Hopefully the following will also help:

ClickHouse client version 21.12.2.17 (official build).
Server:    21.12.2.17 

And for the query:

```

SELECT * FROM t_table WHERE t_table.timestamp = '2021-12-01'

Query id: e86e1509-5660-4cee-a7df-d14c08da07fe

┌─symbol──┬───────────────timestamp─┬─────────local_timestamp─┬─side─┬────price─┬──amount─┐
│ BTCUSDT │ 2021-12-01 00:00:00.000 │ 2021-12-01 00:00:00.009 │ buy  │ 56957.51 │ 0.00294 │
│ BTCUSDT │ 2021-12-01 00:00:00.000 │ 2021-12-01 00:00:00.009 │ buy  │ 56957.51 │ 0.00294 │
│ BTCUSDT │ 2021-12-01 00:00:00.000 │ 2021-12-01 00:00:00.009 │ sell │ 56950.56 │ 0.00019 │
│ BTCUSDT │ 2021-12-01 00:00:00.000 │ 2021-12-01 00:00:00.009 │ sell │ 56950.56 │ 0.00019 │
└─────────┴─────────────────────────┴─────────────────────────┴──────┴──────────┴─────────┘
┌─symbol──┬───────────────timestamp─┬─────────local_timestamp─┬─side─┬───price─┬─amount─┐
│ ETHUSDT │ 2021-12-01 00:00:00.000 │ 2021-12-01 00:00:00.008 │ sell │ 4630.25 │  0.011 │
│ ETHUSDT │ 2021-12-01 00:00:00.000 │ 2021-12-01 00:00:00.008 │ sell │ 4630.25 │  0.011 │
└─────────┴─────────────────────────┴─────────────────────────┴──────┴─────────┴────────┘

6 rows in set. Elapsed: 2.987 sec. Processed 11.07 million rows, 88.82 MB (3.70 million rows/s., 29.73 MB/s.)

```

In the source table the timestamp is stored in Epoch with milliseconds, we transform this to a more readable format of DateTime but also allow for the Milliseconds.


The strange thing is according to the both the following commands... they have the exact same row count.


```
hostname :) SELECT count(*) as cnt FROM tests.t_table limit 1;

Query id: fb3f06df-05e3-495b-b639-fe919ff4fdde

┌─────────cnt─┐
│ 37447804028 │
└─────────────┘

1 rows in set. Elapsed: 0.002 sec.

hostname :) SELECT count(*) as cnt FROM tests.source_table limit 1;

Query id: 114cbfb4-750b-4c8a-bd69-bf6326dc75d2

┌─────────cnt─┐
│ 37447804028 │
└─────────────┘

1 rows in set. Elapsed: 0.002 sec.
```


And finally a stats script:

```
SELECT
    parts.*,
    columns.compressed_size,
    columns.uncompressed_size,
    columns.ratio
FROM
(
    SELECT
        table,
        formatReadableSize(sum(data_uncompressed_bytes)) AS uncompressed_size,
        formatReadableSize(sum(data_compressed_bytes)) AS compressed_size,
        sum(data_compressed_bytes) / sum(data_uncompressed_bytes) AS ratio
    FROM system.columns
    WHERE database = currentDatabase()
    GROUP BY table
) AS columns
RIGHT JOIN
(
    SELECT
        table,
        sum(rows) AS rows,
        max(modification_time) AS latest_modification,
        formatReadableSize(sum(bytes)) AS disk_size,
        formatReadableSize(sum(primary_key_bytes_in_memory)) AS primary_keys_size,
        any(engine) AS engine,
        sum(bytes) AS bytes_size
    FROM system.parts
    WHERE active AND (database = 'tests')
    GROUP BY
        database,
        table
) AS parts ON columns.table = parts.table
ORDER BY parts.bytes_size DESC

Query id: 1cfac5cd-2d77-46a2-82bc-b68011829ee7

┌─parts.table─────────────────────────┬────────rows─┬─latest_modification─┬─disk_size───┬─primary_keys_size─┬─engine────┬────bytes_size─┬─compressed_size─┬─uncompressed_size─┬─ratio─┐
│ source_table                        │ 37447804028 │ 2021-12-30 18:45:38 │ 835.81 GiB  │ 17.44 MiB         │ MergeTree │  897442142329 │                 │                   │     0 │
│ t_table                             │ 37447804028 │ 2022-01-01 13:36:39 │ 361.92 GiB  │ 188.83 MiB         │ MergeTree │ 388605571092 │                 │                   │     0 │
└─────────────────────────────────────┴─────────────┴─────────────────────┴─────────────┴───────────────────┴───────────┴───────────────┴─────────────────┴───────────────────┴───────┘

83 rows in set. Elapsed: 0.019 sec. Processed 2.80 thousand rows, 208.99 KB (149.14 thousand rows/s., 11.14 MB/s.)

hostname :)
```

PS: I appreciate your time and help, thank you :-)

**Comment by den-crane** [comment]
no info

**Comment by BirdyUK** [comment]
Sorry den, i did comment and removed it due to further investigation. I have not had chance to fully debug yet however i found a rouge Materialized View that was also populating the table which i believe caused duplicates. Im working on removing the entire dataset and restart as this is a test table.

For now i believe this to be a potential error caused by us internally thus this can now be closed.

I greatly appreciate your time and effort Den, thanks for helping out.
