### ISSUE TITLE
use SELECT tumble(now(), toIntervalDay('1')) eroor

### ISSUE THREAD

**Issue by maiguoma** [ClickHouse/ClickHouse#33356]
Code: 46. DB::Exception: Unknown function tumble. Maybe you meant: ['tuple']: While processing tumble(now(), toIntervalDay('1')). (UNKNOWN_FUNCTION) (version 21.11.5.33 (official build))

**Comment by UnamedRus** [comment]
It's available starting from 21.12

https://github.com/ClickHouse/ClickHouse/commit/3c348a2998079ec0908d76fc35095223f362f7ad

**Comment by alexey-milovidov** [comment]
You should install the latest ClickHouse version:
```
curl https://clickhouse.com/ | sh
```

**Comment by maiguoma** [comment]
I use docker for deployment, the latest version on docker is 21.11, there is no 21.12;
Address: https://hub.docker.com/r/clickhouse/clickhouse-server/tags

**Comment by maiguoma** [comment]
21.12.3.32 version, still execute statement error
log：
 ClickHouse exception, code: 1002, host: 192.168.0.105, port: 8123; Code: 46. DB::Exception: Unknown function tumble. Maybe you meant: ['TUMBLE','tuple']: While processing tumble(now(), toIntervalDay('1')). (UNKNOWN_FUNCTION) (version 21.12.3.32 (official build))

**Comment by UnamedRus** [comment]
```SELECT TUMBLE(now(), toIntervalDay('1'))```

You need to use capital letters.
ClickHouse-specific functions case sensitive.

**Comment by maiguoma** [comment]
Okay, thank you. I copied the execution statement from the document and used it. In this case, your document is also wrong. The document does not indicate that specific capital letters are required, and I will tell you.
Address: https://clickhouse.com/docs/zh/sql-reference/functions/time-window-functions/

**Comment by UnamedRus** [comment]
https://github.com/ClickHouse/ClickHouse/pull/32324

They were renamed
