### ISSUE TITLE
toValidUTF8 behavior seem abnormal when applied to an actual column

### ISSUE THREAD

**Issue by tiagokrebs** [ClickHouse/ClickHouse#33352]
**Describe what's wrong**
`toValidUTF8` and `decodeURLComponent` seems abnormal when applied to a actual column. When used with sample strings all goes well but passing the same string in a stored column the conversion does not work as expected.

**How to reproduce**
```
CREATE TABLE strings
(
    `s` String
)
ENGINE = MergeTree
ORDER BY s

INSERT INTO strings VALUES ('Cura\\xC3\\xA7ao');

SELECT
    s,
    toValidUTF8(s),
    toValidUTF8('Cura\xC3\xA7ao'),
    decodeURLComponent(s),
    decodeURLComponent('Cura\xC3\xA7ao')
FROM strings

┌─s──────────────┬─toValidUTF8(s)─┬─toValidUTF8('Curaçao')─┬─decodeURLComponent(s)─┬─decodeURLComponent('Curaçao')─┐
│ Cura\xC3\xA7ao │ Cura\xC3\xA7ao │ Curaçao                │ Cura\xC3\xA7ao        │ Curaçao                       │
└────────────────┴────────────────┴────────────────────────┴───────────────────────┴───────────────────────────────┘
```

* Which ClickHouse server version to use
* 21.8.10.19

**Expected behavior**
The result string should be the same in all result columns in the query above, `'Curaçao'`.

**Additional context**
I have noticed this when using geolocation columns from Maxmind tables. This is the raw log line inserted with some obfuscation:
```
v1	2021-12-31T18:28:00+00:00	15xxt	16xxx591031584t	16xxx59103	ha	1441xxx010	www.xxxxxxxxx.gov.br	0.014	GET	HIT	200	-	-	-	https	/xxxxx/v1/Y29tYm9z/	-	-	application/json	HTTP/2.0	81	1361	-	-	-	62689	190.xxx.xxx.xxx	60535	-	$PASS	Cura\xC3\xA7ao	-	TLSv1.3	TLS_AES_256_GCM_SHA384	.	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36	https://xxxxxxx/silce-web/	-	-	443
```

**Comment by alexey-milovidov** [comment]
`decodeURLComponent` expects URL-encoded strings, like `Cura%C3%A7ao`.
It does not and should not process backslash escapes.

`toValidUTF8` function transforms invalid byte sequences to �.
The string `Cura\xC3\xA7ao` contains all the valid byte sequences, because all the characters are in ASCII, 
including `\`, `x`, `C`, `3`.

There is no function to decode C-style escape sequences in string.
