### ISSUE TITLE
Let SQLite database engine to create an empty db file if it doesn't exist.

### ISSUE THREAD

**Issue by ramazanpolat** [ClickHouse/ClickHouse#33367]
Any chance creating the sqlite db file if it doesn't exist?

```sql
CREATE DATABASE [IF NOT EXISTS] sqlite_database 
    ENGINE = SQLite('db_path')
```

**Comment by kitaisreal** [comment]
@ramazanpolat  Currently sqlite3 database engine does not support creating or modifying tables. If there is no sqlite database file and we create it, we cannot create tables inside it, does it have any reasons to do that ?

**Comment by ramazanpolat** [comment]
Because we have a number of small dimension tables that can be hosted with SQLite. The data in those dimention tables are updated frequently. So we need a table that supports actual UPDATE and DELETE statements. This way, it will be much more convinient to create dimension tables with only using ClickHouse. But if we can't create tables with SQLite table engine like you said, then it doesn't make sense to have SQLite DB engine to create the database.

**Comment by den-crane** [comment]
@ramazanpolat you can use EmbeddedRocksDB

**Comment by alexey-milovidov** [comment]
Why not?

**Comment by ramazanpolat** [comment]
> @ramazanpolat you can use EmbeddedRocksDB

In `EmbeddedRocksDB`, every table must have `is_deleted` column. Also referential integrity doesn't exist. Basictly, even small applications need some tables that support ACID. Of course we can create a SQLite database along with tables using some other tools and work on it in ClickHouse but being able to do it in CH will make it much more clean and easy. Besides, if this is implemented then `clickhouse-client` or `clickhouse-local` will be much closer to be the next-gen CLI that supports multiple databases like SQLite, PostgreSQL and so on.

**Comment by alexey-milovidov** [comment]
Also we wanted to create output format SQLite that will create .sqlite file with single table.
