### ISSUE TITLE
PostgreSQL DB Engine timestamp issue

### ISSUE THREAD

**Issue by ramazanpolat** [ClickHouse/ClickHouse#33364]
**Describe the unexpected behaviour**
We use PostgreSQL database engine and get data from PostgreSQL. Unfortunately, the `timestamp` columns in the PostgreSQL tables are not displayed correctly if the date is before `1970-01-01`.

This prevents getting data from PostgreSQL correctly.

**How to reproduce**
* ClickHouse version: 21.12.3.32
* PostgreSQL version: 14.1
* On ClickHouse: 
`CREATE DATABASE postgres ENGINE = PostgreSQL('host:5432', 'database', 'user', 'password', 'public');`
* On PostgreSQL we have a table with this definition:
```
CREATE TABLE history (
   date_action timestamp without time zone,
   org_code character varying(4)
); 
```
* Insert data into PostgreSQL table:
`INSERT INTO public.history ('1960-01-01 01:01:01','ABCD');`

* Selecting data from PostgreSQL shows the `date_action` column correctly. But when queried from ClickHouse, the `date_action` column is shown as  `1970-01-01 02:00:00.000000`

**Expected behavior**
We expect it to show the date as is, like `1960-01-01 01:01:01` or `1960-01-01 01:01:01.000000`.

**Comment by den-crane** [comment]
https://clickhouse.com/docs/en/sql-reference/data-types/datetime/
Supported range of values: [1970-01-01 00:00:00, 2105-12-31 23:59:59].

https://clickhouse.com/docs/en/sql-reference/data-types/datetime64/
Supported range from January 1, 1925 till November 11, 2283

**Comment by ramazanpolat** [comment]
> https://clickhouse.com/docs/en/sql-reference/data-types/datetime64/ Supported range from January 1, 1925 till November 11, 2283

@den-crane dunno how this will solve the problem since ClickHouse cannot convert the `timestamp` type in PostgreSQL to `DateTime64`. By default, ClickHouse treats PostgreSQL `timestamp` as ClickHouse `DateTime` instead of `DateTime64`. 

One quick work-around is creating a view for PostgreSQL table that converts `timestamp` to `text` and then we can convert the `text` to `toDateTime64` in order to insert the data into a ClickHouse table. But this conversion makes queries ugly and slower.
