### ISSUE TITLE
CHANGELOG.md has not been updated in V21.12.* tags

### ISSUE THREAD

**Issue by ruoshan** [ClickHouse/ClickHouse#33379]
Looks like that file has v21.11's changes only.

**Comment by alexey-milovidov** [comment]
Also it is published in the docs: https://clickhouse.com/docs/en/whats-new/changelog/

If you see the old changelog here - it is the issue with caching, press Ctrl+R in browser.

**Comment by ruoshan** [comment]
> Here is the changelog: https://github.com/ClickHouse/ClickHouse/blob/master/CHANGELOG.md
> And it has the changes in version 21.12.

Oh, sorry for the confusion, I mean here: https://github.com/ClickHouse/ClickHouse/blob/v21.12.3.32-stable/CHANGELOG.md
it's still 21.11 in that doc.

**Comment by ruoshan** [comment]
@alexey-milovidov ^

**Comment by alexey-milovidov** [comment]
The changelog is written after the release branch is ready.
It means that you should read the changelog for releases in the master branch.
