### ISSUE TITLE
Unable to install ClickHouse in pfsense FreeBSD

### ISSUE THREAD

**Issue by vijaytejak** [ClickHouse/ClickHouse#33384]
**Describe the unexpected behaviour**
Trying to install clickhouse in FreeBSD (pfsense firewall), following this [link ](https://clickhouse.com/#quick-start)

**How to reproduce**
1 - copy the ClickHouse file into pfsense from [here](https://builds.clickhouse.com/master/freebsd/clickhouse)
2 - chmod a+x ./clickhouse
3 - sudo ./clickhouse install

 **Which ClickHouse server version to use**
- 21.12.1.8928 (official build

**Error message and/or stacktrace**
Code: 107. DB::Exception: Cannot obtain path to the binary from /proc/self/exe, file doesn't exist. (FILE_DOESNT_EXIST) (version 21.12.1.8928 (official build))
![image](https://user-images.githubusercontent.com/14872281/148040641-26f23fc0-39e9-4dcd-97dc-860c9cdefb9b.png)

**Comment by alexey-milovidov** [comment]
Does it help to mount procfs before installation?

`sudo mount -t procfs proc /proc`
https://www.freebsd.org/cgi/man.cgi?query=procfs&sektion=&n=1

**Comment by vijaytejak** [comment]
sudo mount -t procfs proc /proc

executed above command, it executed but no output seen,

and executing the ./clickhouse give the same error as submitted above

**Comment by alexey-milovidov** [comment]
Does that command make `/proc` directory and `/proc/self/exe` file to appear in your filesystem?

**Comment by vijaytejak** [comment]
no

**Comment by alexey-milovidov** [comment]
Let me consult some FreeBSD experts...

**Comment by alexey-milovidov** [comment]
https://stackoverflow.com/questions/1023306/finding-current-executables-path-without-proc-self-exe

**Comment by alexey-milovidov** [comment]
Does `/proc/curproc/file` exists after you have mounted procfs?

**Comment by alexey-milovidov** [comment]
Workaround: simply run `./clickhouse server` without installation.

**Comment by vijaytejak** [comment]
```./clickhouse server``` command is working, and click-house client is able to connect to server with ```./clickhouse client``` command, 

and the next step is i am running a script (ntopng and click house combination), it is saying 

```
[ERROR] Missing executable clickhouse-client. Install at https://clickhouse.com/#quick-start
```

here is the script link:
https://raw.githubusercontent.com/ntop/ntopng/dev/tools/nindex_export_to_ch.sh

also here is what I am trying to achieve: ntopng with flow dump using ClickHouse in pfsense, if we make this work, this will be a new workaround.

https://www.ntop.org/guides/ntopng/clickhouse.html#migration-from-nindex

**Comment by alexey-milovidov** [comment]
Create a symlink `/usr/bin/clickhouse-client` pointing to `clickhouse` binary.

**Comment by vijaytejak** [comment]
i am able to successfully connect ntopng and clickhouse, but i do not see any data, what are the default db credentials and port number ?

**Comment by alexey-milovidov** [comment]
User: `default`
Password: (empty string)
Port: 8123 for HTTP and 9000 for native protocol.
