### ISSUE TITLE
Cannot allocate RAFT instance. (RAFT_ERROR) due to "Address family not supported by protocol" (IPv6 disabled)

### ISSUE THREAD

**Issue by 825644691** [ClickHouse/ClickHouse#33381]
Processing configuration file '/apps/conf/clickhouse-server/config.xml'.
Logging trace to /apps/logs/clickhouse-server/clickhouse-server.log
Logging errors to /apps/logs/clickhouse-server/clickhouse-server.err.log
Logging trace to console
2022.01.04 15:35:45.698159 [ 399760 ] {} <Information> SentryWriter: Sending crash reports is disabled
2022.01.04 15:35:45.713762 [ 399760 ] {} <Trace> Pipe: Pipe capacity is 1.00 MiB
2022.01.04 15:35:45.778619 [ 399760 ] {} <Information> : Starting ClickHouse Keeper 21.12.1.9017 with revision 54457, build id: 1E33508A410EF9C9, PID 399760
2022.01.04 15:35:45.778823 [ 399760 ] {} <Information> Application: starting up
2022.01.04 15:35:45.778863 [ 399760 ] {} <Information> Application: OS Name = Linux, OS Version = 3.10.0-862.9.1.el7.x86_64, OS Architecture = x86_64
2022.01.04 15:35:45.779748 [ 399760 ] {} <Debug> Application: Initializing DateLUT.
2022.01.04 15:35:45.779788 [ 399760 ] {} <Trace> Application: Initialized DateLUT with time zone 'Asia/Shanghai'.
2022.01.04 15:35:45.780169 [ 399760 ] {} <Information> Context: Cannot connect to ZooKeeper (or Keeper) before internal Keeper start, will wait for Keeper synchronously
2022.01.04 15:35:45.780204 [ 399760 ] {} <Debug> KeeperDispatcher: Initializing storage dispatcher
2022.01.04 15:35:45.783134 [ 399760 ] {} <Warning> KeeperLogStore: No logs exists in /apps/dbdat/clickhouse/coordination/log. It's Ok if it's the first run of clickhouse-keeper.
2022.01.04 15:35:45.783216 [ 399760 ] {} <Information> KeeperLogStore: force_sync enabled
2022.01.04 15:35:45.783243 [ 399760 ] {} <Debug> KeeperDispatcher: Waiting server to initialize
2022.01.04 15:35:45.783281 [ 399760 ] {} <Debug> KeeperStateMachine: Totally have 0 snapshots
2022.01.04 15:35:45.783305 [ 399760 ] {} <Debug> KeeperStateMachine: No existing snapshots, last committed log index 0
2022.01.04 15:35:45.783342 [ 399760 ] {} <Warning> KeeperLogStore: Removing all changelogs
2022.01.04 15:35:45.783374 [ 399760 ] {} <Trace> KeeperLogStore: Starting new changelog /apps/dbdat/clickhouse/coordination/log/changelog_1_100000.bin.zstd
2022.01.04 15:35:45.783445 [ 399760 ] {} <Information> KeeperServer: No config in log store and snapshot, probably it's initial run. Will use config from .xml on disk
2022.01.04 15:35:45.786780 [ 399760 ] {} <Error> RaftInstance: got exception: open: Address family not supported by protocol
2022.01.04 15:35:45.787127 [ 399760 ] {} <Error> void DB::KeeperDispatcher::initialize(const Poco::Util::AbstractConfiguration &, bool, bool): Code: 568. DB::Exception: Cannot allocate RAFT instance. (RAFT_ERROR), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa20c85a in /apps/svr/clickhouse2112/usr/bin/clickhouse-keeper
1. DB::KeeperServer::startup() @ 0x142cd613 in /apps/svr/clickhouse2112/usr/bin/clickhouse-keeper
2. DB::KeeperDispatcher::initialize(Poco::Util::AbstractConfiguration const&, bool, bool) @ 0x142b9f27 in /apps/svr/clickhouse2112/usr/bin/clickhouse-keeper
3. DB::Context::initializeKeeperDispatcher(bool) const @ 0x12c6cfde in /apps/svr/clickhouse2112/usr/bin/clickhouse-keeper
4. DB::Keeper::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0xa3b9c96 in /apps/svr/clickhouse2112/usr/bin/clickhouse-keeper
5. Poco::Util::Application::run() @ 0x16ef7d06 in /apps/svr/clickhouse2112/usr/bin/clickhouse-keeper
6. DB::Keeper::run() @ 0xa3b6f94 in /apps/svr/clickhouse2112/usr/bin/clickhouse-keeper
7. mainEntryClickHouseKeeper(int, char**) @ 0xa3b5977 in /apps/svr/clickhouse2112/usr/bin/clickhouse-keeper
8. main @ 0xa206cca in /apps/svr/clickhouse2112/usr/bin/clickhouse-keeper
9. __libc_start_main @ 0x21b35 in /usr/lib64/libc-2.17.so
10. _start @ 0xa09b1ee in /apps/svr/clickhouse2112/usr/bin/clickhouse-keeper
 (version 21.12.1.9017 (official build))
2022.01.04 15:35:45.789007 [ 399760 ] {} <Debug> KeeperDispatcher: Shutting down storage dispatcher
2022.01.04 15:35:45.789254 [ 399760 ] {} <Information> KeeperServer: RAFT doesn't start, shutdown not required
2022.01.04 15:35:45.789278 [ 399760 ] {} <Debug> KeeperDispatcher: Dispatcher shut down
2022.01.04 15:35:45.789403 [ 399769 ] {} <Information> RaftInstance: end of asio worker thread, remaining threads: 42
2022.01.04 15:35:45.789450 [ 399779 ] {} <Information> RaftInstance: end of asio worker thread, remaining threads: 37
2022.01.04 15:35:45.789571 [ 399784 ] {} <Information> RaftInstance: end of asio worker thread, remaining threads: 32
2022.01.04 15:35:45.789696 [ 399796 ] {} <Information> RaftInstance: end of asio worker thread, remaining threads: 20
2022.01.04 15:35:45.789696 [ 399797 ] {} <Information> RaftInstance: end of asio worker thread, remaining threads: 19
2022.01.04 15:35:45.789736 [ 399799 ] {} <Information> RaftInstance: end of asio worker thread, remaining threads: 17
2022.01.04 15:35:45.789858 [ 399807 ] {} <Information> RaftInstance: end of asio worker thread, remaining threads: 9
2022.01.04 15:35:45.790247 [ 399768 ] {} <Information> RaftInstance: end of asio worker thread, remaining threads: 47
2022.01.04 15:35:45.790840 [ 399772 ] {} <Information> RaftInstance: end of asio worker thread, remaining threads: 45
2022.01.04 15:35:45.791700 [ 399774 ] {} <Information> RaftInstance: end of asio worker thread, remaining threads: 43
2022.01.04 15:35:45.791711 [ 399773 ] {} <Information> RaftInstance: end of asio worker thread, remaining threads: 44
2022.01.04 15:35:45.792596 [ 399775 ] {} <Information> RaftInstance: end of asio worker thread, remaining threads: 41
2022.01.04 15:35:45.793035 [ 399776 ] {} <Information> RaftInstance: end of asio worker thread, remaining threads: 40
2022.01.04 15:35:45.793483 [ 399778 ] {} <Information> RaftInstance: end of asio worker thread, remaining threads: 38
2022.01.04 15:35:45.794059 [ 399777 ] {} <Information> RaftInstance: end of asio worker thread, remaining threads: 39
2022.01.04 15:35:45.794528 [ 399780 ] {} <Information> RaftInstance: end of asio worker thread, remaining threads: 36
2022.01.04 15:35:45.795165 [ 399782 ] {} <Information> RaftInstance: end of asio worker thread, remaining threads: 34
2022.01.04 15:35:45.795197 [ 399785 ] {} <Information> RaftInstance: end of asio worker thread, remaining threads: 31
2022.01.04 15:35:45.795204 [ 399786 ] {} <Information> RaftInstance: end of asio worker thread, remaining threads: 30
2022.01.04 15:35:45.795191 [ 399783 ] {} <Information> RaftInstance: end of asio worker thread, remaining threads: 33
2022.01.04 15:35:45.795210 [ 399788 ] {} <Information> RaftInstance: end of asio worker thread, remaining threads: 28
2022.01.04 15:35:45.795607 [ 399781 ] {} <Information> RaftInstance: end of asio worker thread, remaining threads: 35
2022.01.04 15:35:45.795223 [ 399789 ] {} <Information> RaftInstance: end of asio worker thread, remaining threads: 27
2022.01.04 15:35:45.795220 [ 399787 ] {} <Information> RaftInstance: end of asio worker thread, remaining threads: 29
2022.01.04 15:35:45.795616 [ 399790 ] {} <Information> RaftInstance: end of asio worker thread, remaining threads: 26
2022.01.04 15:35:45.795632 [ 399791 ] {} <Information> RaftInstance: end of asio worker thread, remaining threads: 25
2022.01.04 15:35:45.796511 [ 399792 ] {} <Information> RaftInstance: end of asio worker thread, remaining threads: 24
2022.01.04 15:35:45.796525 [ 399793 ] {} <Information> RaftInstance: end of asio worker thread, remaining threads: 23
2022.01.04 15:35:45.796520 [ 399794 ] {} <Information> RaftInstance: end of asio worker thread, remaining threads: 22
2022.01.04 15:35:45.797407 [ 399795 ] {} <Information> RaftInstance: end of asio worker thread, remaining threads: 21
2022.01.04 15:35:45.797413 [ 399771 ] {} <Information> RaftInstance: end of asio worker thread, remaining threads: 46
2022.01.04 15:35:45.797413 [ 399800 ] {} <Information> RaftInstance: end of asio worker thread, remaining threads: 16
2022.01.04 15:35:45.797418 [ 399802 ] {} <Information> RaftInstance: end of asio worker thread, remaining threads: 14
2022.01.04 15:35:45.797834 [ 399801 ] {} <Information> RaftInstance: end of asio worker thread, remaining threads: 15
2022.01.04 15:35:45.797425 [ 399803 ] {} <Information> RaftInstance: end of asio worker thread, remaining threads: 13
2022.01.04 15:35:45.797827 [ 399798 ] {} <Information> RaftInstance: end of asio worker thread, remaining threads: 18
2022.01.04 15:35:45.797838 [ 399804 ] {} <Information> RaftInstance: end of asio worker thread, remaining threads: 12
2022.01.04 15:35:45.798306 [ 399806 ] {} <Information> RaftInstance: end of asio worker thread, remaining threads: 10
2022.01.04 15:35:45.798330 [ 399811 ] {} <Information> RaftInstance: end of asio worker thread, remaining threads: 5
2022.01.04 15:35:45.798320 [ 399809 ] {} <Information> RaftInstance: end of asio worker thread, remaining threads: 7
2022.01.04 15:35:45.798330 [ 399810 ] {} <Information> RaftInstance: end of asio worker thread, remaining threads: 6
2022.01.04 15:35:45.798337 [ 399812 ] {} <Information> RaftInstance: end of asio worker thread, remaining threads: 4
2022.01.04 15:35:45.798342 [ 399813 ] {} <Information> RaftInstance: end of asio worker thread, remaining threads: 3
2022.01.04 15:35:45.798358 [ 399770 ] {} <Information> RaftInstance: end of asio worker thread, remaining threads: 0
2022.01.04 15:35:45.798310 [ 399808 ] {} <Information> RaftInstance: end of asio worker thread, remaining threads: 8
2022.01.04 15:35:45.798361 [ 399815 ] {} <Information> RaftInstance: end of asio worker thread, remaining threads: 1
2022.01.04 15:35:45.798361 [ 399814 ] {} <Information> RaftInstance: end of asio worker thread, remaining threads: 2
2022.01.04 15:35:45.798733 [ 399805 ] {} <Information> RaftInstance: end of asio worker thread, remaining threads: 11
2022.01.04 15:35:45.799620 [ 399760 ] {} <Error> Application: DB::Exception: Cannot allocate RAFT instance
2022.01.04 15:35:45.799663 [ 399760 ] {} <Information> Application: shutting down
2022.01.04 15:35:45.799681 [ 399760 ] {} <Debug> Application: Uninitializing subsystem: Logging Subsystem
2022.01.04 15:35:45.799776 [ 399761 ] {} <Trace> BaseDaemon: Received signal -2
2022.01.04 15:35:45.799845 [ 399761 ] {} <Information> BaseDaemon: Stop SignalListener thread

I just `ln -s clickhouse clickhouse-keeper`
version 21.12.1.9017
how to deal with this problem?

**Comment by wuxueyang96** [comment]
I think this problem may be caused by the hard code in this place.

https://github.com/ClickHouse-Extras/NuRaft/blob/ff100a8713146e1ca4b4158dd6cc4eef9af47fc3/src/asio_service.cxx#L699

**Comment by 825644691** [comment]
> If you try to execute `ping ::1` on the machine and get an error, then I think this problem may be caused by the hard code in this place.
> 
> https://github.com/ClickHouse-Extras/NuRaft/blob/ff100a8713146e1ca4b4158dd6cc4eef9af47fc3/src/asio_service.cxx#L699

yes...
ping: ::1: Address family for hostname not supported

I can't use clickhouse-keeper if ipv6 is disabled?

**Comment by Dmitriy-Muchanovskiy** [comment]
Hello.
Which command or config-string can enable IPv4-using in Clickhouse keeper?
I can't find any info about that.
How can i start clickhouse keeper with IPv4?

**Comment by alexey-milovidov** [comment]
Change `listen_host` to `0.0.0.0`.

**Comment by Dmitriy-Muchanovskiy** [comment]
i thought about that but it is't work.
in my ../clickhouse-server/config.xml next rows about "listen_host"
    
    
    
    
    <listen_host>0.0.0.0</listen_host>
clickhouse version 22.2.2.1.

When i try to start clickhouse i receive next error in log:
2022.12.14 10:17:29.006573 [ 1855122 ] {} <Error> RaftInstance: got exception: open: Address family not supported by protocol [system:97] on port 9444

**Comment by Dmitriy-Muchanovskiy** [comment]
@alexey-milovidov
I tried now version 22.3.6.5 - this the last version i can use (job specific limits).
Add to default config.xml <listen_host>0.0.0.0</listen_host>
Start up command - clickhouse-keeper --config /etc/clickhouse-server/config.xml
And it isn't work. I received the same error.

Keeper config below.
<clickhouse>
    <keeper_server>
        <tcp_port>9181</tcp_port>
        <server_id>1</server_id>
        <log_storage_path>/var/lib/clickhouse/coordination/log</log_storage_path>
        <snapshot_storage_path>/var/lib/clickhouse/coordination/snapshots</snapshot_storage_path>

        <coordination_settings>
            <operation_timeout_ms>5000</operation_timeout_ms>
            <session_timeout_ms>10000</session_timeout_ms>
            <raft_logs_level>trace</raft_logs_level>
        </coordination_settings>

        <raft_configuration>
            <server>
                <id>1</id>
                <hostname>hostname</hostname>
                <port>9234</port>
            </server>
        </raft_configuration>
    </keeper_server>
</clickhouse>

**Comment by khorn7sk** [comment]
@Dmitriy-Muchanovskiy try to set `interserver_listen_host`. This is works for me.
`<interserver_listen_host>0.0.0.0</interserver_listen_host>`

**Comment by Dmitriy-Muchanovskiy** [comment]
@khorn7sk @alexey-milovidov 
I tried to add `interserver_listen_host` in config.xml now and it isn't work.

**Comment by khorn7sk** [comment]
@Dmitriy-Muchanovskiy if you running Clickhouse in the docker, please check file `/etc/clickhouse-server/config.d/docker_related_config.xml` which also have options `<listen_host>::</listen_host>`, you should remove them.

**Comment by Dmitriy-Muchanovskiy** [comment]
@khorn7sk @alexey-milovidov 
I don't start in the docker.
Right now check just in case any phrase `listen_host`, result is below:
`/etc/clickhouse-server]# grep -R listen_host .
./config.xml:    
./config.xml:    
./config.xml:    <listen_host>0.0.0.0</listen_host>
./config.xml:    <listen_host>0.0.0.0</listen_host>
./config.xml:    <interserver_listen_host>0.0.0.0</interserver_listen_host>`

**Comment by mcarbonneaux** [comment]
> @Dmitriy-Muchanovskiy try to set `interserver_listen_host`. This is works for me.
> `<interserver_listen_host>0.0.0.0</interserver_listen_host>`

it's worked for me !

**Comment by Blargian** [comment]
Ran into this issue with a fresh install of Ubuntu 22.04.3 - solved by enabling IPv6.
