### ISSUE TITLE
Add arrayLast function (same as arrayFirst, but get the last element instead of the first)

### ISSUE THREAD

**Issue by alexsubota** [ClickHouse/ClickHouse#33390]
Currently we need to write smth like
`select arrayFilter(...)[-1]`
to get the last element. 
At the same time, we have `arrayFirst` function for the first element of array.

I think clickhouse community need analogy of function arrayFirst, but for last element.

My proposal is arrayLast function:
```
select range(10)                               as arr,
       arrayFirst((a)->(a > 3 and a < 8), arr) as first_element,
       arrayLast((a)->(a > 3 and a < 8), arr)  as last_element
```
with result
![image](https://user-images.githubusercontent.com/4305175/148060114-81e83e9b-e02e-499e-8e1c-b48e99e46f02.png)

**Comment by thotran2015** [comment]
If none of the items meets the condition defined by lambda function, clickhouse returns its default value like 0, "", etc. Can we have an option to pass in our own default value?
