### ISSUE TITLE
mutations hang after drop part

### ISSUE THREAD

**Issue by lthaooo** [ClickHouse/ClickHouse#33395]
**Describe what's wrong**

> mutations may hang after drop part

**Does it reproduce on recent release?**

> Yes. 21.8.8.1

**How to reproduce**
> SQL:  ALTER TABLE mytable DELETE IN PARTITION '2021-12-17' WHERE hour_ = toDateTime('2021-12-17 08:00:00')
> Some parts will become empty after this delete mutation which will be dropped very soon.
> Sequence Diagram
![image](https://user-images.githubusercontent.com/3897496/148074982-30296ba2-a14e-474a-b22c-03da4e53a5ea.png)

> Key logs
2021.12.17 15:45:24.133283 [ 83305 ] {2968e531-9ffe-450e-a199-abbe8aae43ca} <Debug> raw.mytable: Waiting for mmdcchsvrnew38 to apply mutation 0000000041
2021.12.17 15:45:49.970062 [ 79683 ] {} <Information> raw.mytable (ReplicatedMergeTreeQueue): Loading 1 mutation entries: 0000000041 - 0000000041
2021.12.17 15:45:52.333521 [ 79663 ] {} <Debug> raw.mytable (ReplicatedMergeTreeQueue): Pulling 11 entries to queue: log-0000378438 - log-0000378448
2021.12.17 15:45:52.686249 [ 79663 ] {} <Debug> raw.mytable (ReplicatedMergeTreeQueue): Pulled 11 entries to queue.
2021.12.17 15:46:03.148327 [ 79703 ] {} <Debug> raw.mytable (ReplicatedMergeTreeQueue): Pulling 1 entries to queue: log-0000378449 - log-0000378449
2021.12.17 15:46:03.757975 [ 79703 ] {} <Debug> raw.mytable (ReplicatedMergeTreeQueue): Pulled 1 entries to queue.
2021.12.17 15:46:05.754676 [ 61954 ] {} <Debug> raw.mytable (ReplicatedMergeTreeQueue): Removed 6 entries from queue. Waiting for 0 entries that are currently executing.

> part_0_0_0 is expected to remove from parts_to_do, but actually part_0_0_0_1 removed instead
(https://github.com/ClickHouse/ClickHouse/blob/v21.8.13.6-lts/src/Storages/MergeTree/ReplicatedMergeTreeQueue.cpp#L309)

> However this bug is fix in #30651 at the same time
![image](https://user-images.githubusercontent.com/3897496/148074508-1ff3144e-58ba-4b6c-b115-6f9032deaed0.png)

please check this issue and make a cherry pick

**Comment by alexey-milovidov** [comment]
Stable ClickHouse versions since 21.11 have no such error.
Backport is not needed, because the issue does not relate to security or stability.
