### ISSUE TITLE
<Error> DynamicQueryHandler: Code: 24, e.displayText() = DB::Exception: Cannot write to ostream at offset 10200: While executing TabSeparatedRowOutputFormat 

### ISSUE THREAD

**Issue by surajmachamasi** [ClickHouse/ClickHouse#33396]
i am getting this error in my clickhouse pod logs, what could be the issue please response soon.

**Comment by surajmachamasi** [comment]
full log :

2022.01.04 15:13:47.420770 [ 297 ] {911e8135-b24d-49b1-a5b8-aff3d44fcdfa} <Error> executeQuery: Code: 24, e.displayText() = DB::Exception: Cannot write to ostream at offset 6500: While executing TabSeparatedRowOutputFormat (version 20.7.4.11 (official build)) (from 10.233.96.233:46320) (in query:  SELECT concat('metric.', metric) AS metric, toString(value) AS value, '' AS description, 'gauge' AS type FROM system.asynchronous_metrics UNION ALL SELECT concat('metric.', metric) AS metric, toString(value) AS value, '' AS description, 'gauge' AS type FROM system.metrics UNION ALL SELECT concat('event.', event) AS metric, toString(value) AS value, '' AS description, 'counter' AS type FROM system.events UNION ALL SELECT 'metric.DiskDataBytes' AS metric, toString(sum(bytes_on_disk)) AS value, 'Total data size for all ClickHouse tables' AS description, 'gauge' AS type FROM system.parts UNION ALL SELECT 'metric.MemoryPrimaryKeyBytesAllocated' AS metric, toString(sum(primary_key_bytes_in_memory_allocated)) AS value, 'Memory size allocated for primary keys' AS description, 'gauge' AS type FROM system.parts UNION ALL SELECT 'metric.MemoryDictionaryBytesAllocated' AS metric, toString(sum(bytes_allocated)) AS value, 'Memory size allocated for dictionaries' AS description, 'gauge' AS type FROM system.dictionaries UNION ALL SELECT 'metric.LongestRunningQuery' AS metric, toString(max(elapsed)) AS value, 'Longest running query time' AS description, 'gauge' AS type FROM system.processes UNION ALL SELECT 'metric.ChangedSettingsHash' AS metric, toString(groupBitXor(cityHash64(name,value))) AS value, 'Control sum for changed settings' AS description, 'gauge' AS type FROM system.settings WHERE changed ), Stack trace (when copying this message, always include the lines below):

**Comment by surajmachamasi** [comment]
similar exception: 
<Error> DynamicQueryHandler: Cannot send exception to client: Code: 24, e.displayText() = DB::Exception: Cannot write to ostream at offset 10396, Stack trace (when copying this message, always include the lines below):

**Comment by surajmachamasi** [comment]
is this exception related to following exception.
 
 DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xa3f52bd in /usr/bin/clickhouse

**Comment by den-crane** [comment]
This error means that a client who made a request is gone and Clickhouse unable to send the result (write the result into a network socket) because the client (receiver) has disappeared.
