### ISSUE TITLE
Support column-level lineage analyze when creating mv

### ISSUE THREAD

**Issue by wangqinghuan** [ClickHouse/ClickHouse#33405]
for example

1.CREATE TABLE
```
CREATE TABLE A
(
   a1 String,
   a2 String,
   ...
)

CREATE TABLE B
(
   b1 String,
   b2 String,
   ...
)

CREATE MATERIALIZED VIEW mv_A_to_B to B AS 
SELECT
    a1,
    a2,
    ...
  FROM  A

```
2.the lineage is 

>  field B.b1 origin from  A.a1
>  field B.b2 origin from  A.a2
>  ...

**Comment by den-crane** [comment]
It was like this before 19.16. Chickhouse threw an error if select has columns which are not in the destination table. And vice versa if a column in a select is missing then Chickhouse also threw an error.
After 19.16 Chickhouse implemented a new feature (it were many feature requests about it), now column sets in the  destination table and select can be different. 

That's why there is no way to implement your  request.

It allows to do:

```
create table dest
a ...,
b ...,
c ... default / materialized  -- calculated during insert but not persists in MV select.
)

create materialized view ....
as select
   JSONExtract( ) ..... some_col_which_will_be_used_in_MV,
   func(some_col_which_will_be_used_in_MV) as a,
   func(some_col_which_will_be_used_in_MV) as b,

```

**Comment by filimonov** [comment]
> column-level lineage analyze when creating mv

Even if it would be possible - how you expect to show / use that?

**Comment by wangqinghuan** [comment]
Sorry, I don't  clarify the purpose. We are using a metadata platform [datahub](https://github.com/linkedin/datahub) as data discovery and data lineage tool in our org. And we are using Clickhouse MV as our etl tool which implies some table or cloumn-level lineages are important to our bussiness, we need to know field A in table A was from which field in which table,  table A was used by what MVs... I want to extract these lineage from these meterialized view.

**Comment by filimonov** [comment]
> I want to extract these lineage from these meterialized view.

Again i don't understand what result are you interested in. If you need to know the  exact mapping - maybe you can keep the column names fixed & unique fixed across all MV? Or fill some mapping table every time you create the MV which remap columns?
