### ISSUE TITLE
Will this std::lock_guard<std::mutex> & is necessary or just for good coding style？

### ISSUE THREAD

**Issue by wangzhen11aaa** [ClickHouse/ClickHouse#33403]
Hi, I don't think this parameter "std::lock_guard<std::mutex> &" is necessary. 
Because when we want to cancel one task, we must lock the mutex (which creates a schedule_lock), then other threads want to schedule this task will be blocked.
Then what does this argument mean here?

void BackgroundSchedulePool::cancelDelayedTask(const TaskInfoPtr & task, std::lock_guard<std::mutex> & /* task_schedule_mutex_lock */)
{
  ...
}

**Comment by kitaisreal** [comment]
It is just style. It can be used as indicator that method must be called with lock.
