### ISSUE TITLE
Failed to download data parts from another replica.

### ISSUE THREAD

**Issue by guaiguaidashu** [ClickHouse/ClickHouse#33417]
> When using Prometheus to monitor the Clickhouse cluster, it is found that the 'replicatedpartfailedfetches' always continue to increase, resulting in an alarm. What causes replica fetch failed ? why？

**Comment by den-crane** [comment]
Please provide the result for

```
SELECT
    database,
    table,
    type,
    any(last_exception),
    any(postpone_reason),
    min(create_time),
    max(last_attempt_time),
    max(last_postpone_time),
    max(num_postponed) AS max_postponed,
    max(num_tries) AS max_tries,
    min(num_tries) AS min_tries,
    countIf(last_exception != '') AS count_err,
    countIf(num_postponed > 0) AS count_postponed,
    countIf(is_currently_executing) AS count_executing,
    count() AS count_all
FROM system.replication_queue
GROUP BY
    database,
    table,
    type
ORDER BY count_all DESC

```

**Comment by den-crane** [comment]
No info. Closed.

**Comment by guaiguaidashu** [comment]
{
 "database":"onedata_acs_vm_cmbagent"
 "table":"mountpoint_local"
 "type":"MERGE_PARTS"
 "any(last_exception)":""
 "any(postpone_reason)":"Not merging into part 20220110_42595_43547_14 because part 20220110_43542_43547_1 is not ready yet (log entry for that part is being processed)."
 "min(create_time)":"2022-01-10 10:28:52"
 "max(last_attempt_time)":"2022-01-10 10:28:52"
 "max_postponed":"3"
 "max_tries":"1"
 "min_tries":"1"
 "count_err":"0"
 "count_postponed":"1"
 "count_excuting":"1"
 "count_all":"1"
}
