### ISSUE TITLE
Advise on the engines/functions to use when merging two records with the common and missing key columns

### ISSUE THREAD

**Issue by malikas05** [ClickHouse/ClickHouse#33419]
Hi.
I am raising this question to get insights into the possible solution given the use case I have. The main problem I am trying to solve is merging two records into a single record where these two records are sourced from the two different Kafka topics, yet they both have similar key columns which can be used when merging the records. However, the primary bottleneck is that some of those key columns don't exist in the row from the second topic but, ideally, the values for these "missing" columns should be taken from the row in the first topic. For example, imagine, we have two topics with the following fields:
**Topic1:**

> key_column1
> key_column2
> key_column3
> int_value_column1
> 

**Topic2:**

> key_column1
> key_column2
> int_value_column1
> 

I've set up the Kafka engine table and the pertaining Materialized View to populate the base table(MergeTree) which has the following schema:

> key_column1
> key_column2
> key_column3
> int_value_column1

However, I am unable to devise a way to merge those two aforementioned rows into a single row into a separate table, e.g., the SummingMergeTree table, because the row from the second topic is missing key_column3, i.e., the value gets defaulted to empty or zero value depending on the type of the field. Is there a way to explicitly declare that those missing columns from topic 2 should be populated with the values extracted from the pertaining row from topic 1? I was also trying to play around with the AggregatingMergeTree engine; however, I couldn't find the function to select a non-empty value. Also, please note that there can be situations when the row from topic 2 might arrive earlier than the pertaining row from topic 1 -- in such a scenario, no aggregation should be executed. 

EDIT: Possibly, I could re-use the prominent engine SummingMergeTree and don't include those key columns in the ORDER BY clause, i.e, include only those which we know will have values in both rows for sure, e.g., key_column1 and key_column2. However, is there a way to define that non-empty values(from the row of topic 1) should be used when the records are merged? I believe, the default behavior is that it selects the values randomly, so it might be from row 1 or row 2(empty values).

**Comment by den-crane** [comment]
You should do it before loading data into Clickhouse in your ETL.
I don't see how to do it in CH.
You may try https://github.com/ClickHouse/ClickHouse/pull/8331 but I doubt it will help.
