### ISSUE TITLE
cgroups & oom killed clickhouse-server: `max_server_memory_usage` does not work?

### ISSUE THREAD

**Issue by JackyWoo** [ClickHouse/ClickHouse#33410]
Environment and Configuration：

- ClickHouse version：21.3.16 revision 54447
- Run in docker
- Docker RAM is  64GB.
- `max_server_memory_usage`  is  54975581389; 
- `max_server_memory_usage_to_ram_ratio` not set.

![image](https://user-images.githubusercontent.com/3991709/148200788-456f4828-86a9-4edf-8d0e-8950a63c3c8a.png)

Clickhouse was killed by OS OOM Killer for it rss was about 66GB.  
So I wonder :

1. why `max_server_memory_usage` did not work.
2. Will `MemoryTracker` track all process memory?

**Comment by filimonov** [comment]
> ClickHouse version：21.3.16 revision 54447

Please update to recent version. There was a lot of improvements (also some related to memory management) in the meanwhile.

> why max_server_memory_usage did not work.

ClickHouse accounts the memory taken by the process itself. You can check how clickhouse account the memory by running
```
SELECT *, formatReadableSize(value) FROM system.asynchronous_metrics WHERE metric like '%Cach%' or metric like '%Mem%' order by metric format PrettyCompactMonoBlock
``` 

And AFAIK kubernetes & cgroups v2 also account page cache. See 
https://biriukov.dev/docs/page-cache/6-cgroup-v2-and-page-cache/
https://github.com/kubernetes/kubernetes/issues/43916

> Will MemoryTracker track all process memory?

Yes. As good as it can. Theoretically, some external libraries used by clickhouse can bypass clickhouse memory tracker. If you can reproduce the problem when clickhouse don't account the memory correctly - please create a test & report it.

**Comment by JackyWoo** [comment]
@filimonov thx, it really helps.
