### ISSUE TITLE
Bad size of marks file

### ISSUE THREAD

**Issue by zzzzheng** [ClickHouse/ClickHouse#33426]
Code: 246. DB::Exception: Received from clickhouse-3:9010. DB::Exception: Bad size of marks file '/data/clickhouse/node03-1/store/0b2/0b23051e-b76f-4a6a-8b23-051eb76f4a6a/9f9547464605c9b93da1f5d41738608b_466_466_0/dt.mrk2': 0, must be: 888: While executing MergeTreeThread. (CORRUPTED_DATA) (version 21.12.2.17 (official build))

{} <Error> void DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::routine(DB::TaskRuntimeDataPtr) [Queue = DB::MergeMutateRuntimeQueue]: Code: 246. DB::Exception: Bad size of marks file '/data/clickhouse/node03-1/store/0b2/0b23051e-b76f-4a6a-8b23-051eb76f4a6a/9f9547464605c9b93da1f5d41738608b_466_466_0/dth.mrk2': 0, must be: 888. (CORRUPTED_DATA), Stack trace (when copying this message, always include the lines below):

通过waterdrop导入数据到clickhouse，导入完成后，查询表数据，报该错误，连续几次，如果重启clickhouse服务器，该错误就会导致服务直接启动不了，只有将该文件移动到detached文件夹里，才能重启，后续再插入数据，又是同样的错误。
希望有大佬能解答该问题，clickhouse版本是 21.12.2.17，该表使用的引擎是ReplicatedMergeTree
第一次提issue，有欠缺之处或者问题没描述清楚，烦请指正，谢谢。

**Comment by den-crane** [comment]
Probably just inserted part "9f9547464605c9b93da1f5d41738608b_466_466_0" is corrupted by hardware reboot.
Use `check table` https://clickhouse.com/docs/en/sql-reference/statements/check-table/

**Comment by zzzzheng** [comment]
> 



> Probably just inserted part "9f9547464605c9b93da1f5d41738608b_466_466_0" is corrupted by hardware reboot. Use `check table` https://clickhouse.com/docs/en/sql-reference/statements/check-table/

不仅仅是这个一张表的一个part，有很多个part，同时几张表都是这样，为什么会发生损坏呢？后续我该怎么避免这个问题
check TABLE tmp_local.ads_sensors_event_flow_new_impala_tmp_5;
![image](https://user-images.githubusercontent.com/33900621/148335764-bc4c98a9-917c-452e-9954-d1674b3fa6f8.png)

**Comment by den-crane** [comment]
1. check uptime. `select uptime()`. Did your server reboot recently?
2. check hardware, disks. fsck https://linuxize.com/post/fsck-command-in-linux/

**Comment by alexey-milovidov** [comment]
This is the issue with your hardware.

If you use replication, the table will be repaired automatically from healthy replicas.
If you don't use replication, the data is lost.
