### ISSUE TITLE
select round(100,2) display 100 not is 100.00

### ISSUE THREAD

**Issue by MasonYangD** [ClickHouse/ClickHouse#33430]
clickhouse version is 21.11.6.7

![image](https://user-images.githubusercontent.com/38834622/148343604-6c4548a7-1173-4eb6-9e9a-03cf618f8068.png)

![image](https://user-images.githubusercontent.com/38834622/148343572-539257b8-024a-497e-b2b1-6d10985512b2.png)

**Comment by den-crane** [comment]
1. "100.00" is a TEXT representation, not a number.
2. The TEXT representation is displayed by DBeaver. Ask DBeaver.
3. Round does convert numbers to TEXT.

**Comment by alexey-milovidov** [comment]
> Round does convert numbers to TEXT.

You mean "does not".

**Comment by den-crane** [comment]
oops, right fixed

**Comment by MasonYangD** [comment]
> 1. "100.00" is a TEXT representation, not a number.
> 2. The TEXT representation is displayed by DBeaver. Ask DBeaver.
> 3. Round does **NOT** convert numbers to TEXT.

Thanks for your answer.

I want a 100.00. Please tell me how I do.
I don't think it has anything to do with dbeaver, because I execute it on the client side with the same result.

![image](https://user-images.githubusercontent.com/38834622/148478797-441bbde4-f738-43e3-9218-4eed7a807650.png)
![image](https://user-images.githubusercontent.com/38834622/148478813-9e11242a-74f6-4c4e-9915-c58059c0a47f.png)
![image](https://user-images.githubusercontent.com/38834622/148478827-f669219f-cc31-4e35-b9a3-ea7f10811e44.png)

**Comment by MasonYangD** [comment]
This is an example from the official website of clickhouse.

![image](https://user-images.githubusercontent.com/38834622/148479164-4ec8ab3f-48be-49ac-b010-e9af9cb1db09.png)

This is mine.
![image](https://user-images.githubusercontent.com/38834622/148479231-60ea3b69-6348-4e0c-9fd3-a54bc854a88c.png)
Who can tell me , why?

**Comment by den-crane** [comment]
ClickHouse release v21.9, 2021-09-09
Backward Incompatible Change

    Do not output trailing zeros in text representation of Decimal types. Example: 1.23 will be printed instead of 1.230000 for decimal with scale 6. This closes #15794. It may introduce slight incompatibility if your applications somehow relied on the trailing zeros. Serialization in output formats can be controlled with the setting output_format_decimal_trailing_zeros. Implementation of toString and casting to String is changed unconditionally. #27680 (alexey-milovidov).

**Comment by den-crane** [comment]
```sql
set output_format_decimal_trailing_zeros = 1;
select toDecimal64(1, 6);
┌─toDecimal64(1, 6)─┐
│          1.000000 │
└───────────────────┘

select toDecimal64(1, 6);
┌─toDecimal64(1, 6)─┐
│                 1 │
└───────────────────┘

```

**Comment by MasonYangD** [comment]
Thank you .  Decimal is OK .
I can't do this setup every time.

Is there a permanent configuration item?

How can I use round to round to two decimal places?
![image](https://user-images.githubusercontent.com/38834622/148492033-aa19560e-0a81-4a34-b645-72f922f572ba.png)

![image](https://user-images.githubusercontent.com/38834622/148492057-378e1e68-e7f1-4e02-9db7-1b8a9a06bb5a.png)

![image](https://user-images.githubusercontent.com/38834622/148492106-9c688f09-712a-4a71-942d-b755d0c755dd.png)

**Comment by den-crane** [comment]
"1.000000" -- text representation.

For example postgresql has a function to format strings

```sql
psql > select 1 _number, to_char(1, '999D9999999') _string;
 _number |   _string
---------+--------------
       1 |    1.0000000
```

Clickhouse does not have `to_char` function.

You can configure DBeaver to show zeroes.
![Screen Shot 2022-01-07 at 9 53 26 AM](https://user-images.githubusercontent.com/19737682/148553974-f97da2e5-3b5f-431a-853b-51e8f9ac2ae9.png)

![Screen Shot 2022-01-07 at 9 54 07 AM](https://user-images.githubusercontent.com/19737682/148553983-95d79ac0-bb5d-4486-ae77-69175d7cd99e.png)
