### ISSUE TITLE
how to remove an element from groupBitmap 

### ISSUE THREAD

**Issue by liweigong** [ClickHouse/ClickHouse#33434]
I have two table like this:

> create table IF NOT EXISTS user_tb_local (
>     gender String ,
>     user  String,
>     offset UInt64,
>     delete_flag UInt8,
>     dt String    
> )engine=Null;

> create table IF NOT EXISTS gender_bitmap_tb_local (
>     gender String ,
>     user_bitmap AggregateFunction(groupBitmap,UInt64) ,
>     dt String    
> )engine=ReplicatedAggregatingMergeTree
> PARTITION BY dt ORDER BY (dt,code)
> SETTINGS index_granularity=1,index_granularity_bytes=0;

and I want to create two marterial view  like this：
one to add user to the bitmap.

> CREATE MATERIALIZED VIEW add_user_mv  to gender_bitmap_tb_local  as
> SELECT
>     gender,groupBitmapOr(bitmapBuild(offset)),dt
> FROM user_tb_local where delete_flag = 0;

the other to remove user from the bitmap when user is delete

> CREATE MATERIALIZED VIEW remove_user_mv  to gender_bitmap_tb_local  as
> SELECT
>     gender,groupBitmapXor(bitmapBuild(offset)),dt
> FROM user_tb_local where delete_flag = 1;

but  now the   AggregateFunction(groupBitmap,UInt64) seems only support  groupBitmapMerge which equals groupBitmapOr，
how can I remove an element from a bitmap  by using the MATERIALIZED VIEW since I know that the MATERIALIZED VIEW  is like a trigger？

**Comment by filimonov** [comment]
I don't think it's possible with AggregateFunction(groupBitmap,UInt64) and AggregatingMergeTree.

Maybe you can try using couple of arrays
```
`users` AggregateFunction(sumMap, Array(UInt64), Array(UInt8))
```
Users with sum > 0 are in group. 

Or just unwind arrays into a real rows and use collapsing.

**Comment by UnamedRus** [comment]
If you don't have a lot of deletes:

It's possible to have second column:
```
 user_removed_bitmap AggregateFunction(groupBitmap,UInt64) ,
```

And populate it with removed users.

So at query time you can just do XOR between those bitmaps.

**Comment by liweigong** [comment]
> 

my  situation is : the user removed  may add back someday, and this will happen to lot of users.

so, i think ,the second column bitmap  may not solve this situation.

**Comment by alexey-milovidov** [comment]
It is possible to use the `bitmapAndnot` to remove an element:
https://clickhouse.com/docs/en/sql-reference/functions/bitmap-functions/#bitmapandnot

**Comment by liweigong** [comment]
> 

bitmapAndNot can't used in AggregateFunction

we want to use  like   AggregateFunction(bitmapAndnot,groupBitmap(bitmap type)  )
