### ISSUE TITLE
CONNECTION_LINK 

### ISSUE THREAD

**Issue by er77** [ClickHouse/ClickHouse#33471]
> (you don't have to strictly follow this form)

Possibility to avoid hardcoding external table credentials in the each tables definitions

for example 

as is 
 
CREATE TABLE s3_engine_table (name String, value UInt32)
    ENGINE = S3(path, [aws_access_key_id, aws_secret_access_key,] format, [compression])
    [SETTINGS ...] 

 to be

CREATE EXTERNAL_CONNECTION EXTERNAL_CONNECTION_NAME as 
(path, [aws_access_key_id, aws_secret_access_key,] format, [compression]) ;

CREATE TABLE s3_engine_table (name String, value UInt32)
    ENGINE = S3(EXTERNAL_CONNECTION_NAME)
    [SETTINGS ...] 
 

> A clear and concise description of what is the intended usage scenario is.

It helps to change security credentials for all external tables with one command

**Comment by kssenii** [comment]
It is already implemented. See https://github.com/ClickHouse/ClickHouse/issues/28367. Available since 21.11.

**Comment by er77** [comment]
it's not the same
   current decision with using configurations file can be managed only by system administrator with server downtime 

but this approach can be used  regular user

also store passwords in the plain text can effect to security checks 

and for cloud decision it's not possible to change server config file

**Comment by UnamedRus** [comment]
It's done https://github.com/ClickHouse/ClickHouse/pull/43252
