### ISSUE TITLE
Client echo option broken

### ISSUE THREAD

**Issue by larry-cdn77** [ClickHouse/ClickHouse#33488]
The echo option in command line batch mode appears to have stopped working:

```
% clickhouse client --echo <<< "SELECT version()"
21.12.3.32
```

Normal output:

```
% clickhouse client --echo <<< "SELECT version()"
SELECT version()

21.8.5.7
```

I have not tried versions other than above

**Comment by kssenii** [comment]
It was fixed in https://github.com/ClickHouse/ClickHouse/pull/32843. Fix is only in master now.

**Comment by alexey-milovidov** [comment]
You can install the master version as following:
```
curl https://clickhouse.com/ | sh
```

**Comment by larry-cdn77** [comment]
Thank you both

Somehow I did not find the existing issue via GitHub search
