### ISSUE TITLE
Datas don't be distributed by sharding_key

### ISSUE THREAD

**Issue by cainiaodidi** [ClickHouse/ClickHouse#33485]
On my cluster, there are 60nodes with 30 shards and 2 replicas, and I create a distributed engine table(named table_dist) with sharding_key(named id), and the config of cluster is that all of nodes are the same weight(weight=1), and I insert data into table_dist. And I find that some datas with id%30 equals 10 or 0 are on the same shard_1(shard_num=1). And there are two different value id%30 on most of nodes(eg. id%30==12 or 1 are on the shard_2; id%30==10 or 11 are on the shard_11). It's strange.  Anyway,  on a single node, there must be one value of id%30, why do this happen?

**Comment by UnamedRus** [comment]
Is order of shards in remote_servers the same on all nodes?
Did you always have 30 shards in this cluster?

```
SELECT
    host_name,
    groupUniqArray(shard_num),
    groupUniqArray(shard_weight)
FROM clusterAllReplicas('CLUSTER_NAME', system.clusters)
WHERE cluster = 'CLUSTER_NAME'
GROUP BY host_name
```

**Comment by cainiaodidi** [comment]
> Is order of shards in remote_servers the same on all nodes? Did you always have 30 shards in this cluster?
> 
> ```
> SELECT
>     host_name,
>     groupUniqArray(shard_num),
>     groupUniqArray(shard_weight)
> FROM clusterAllReplicas('CLUSTER_NAME', system.clusters)
> WHERE cluster = 'CLUSTER_NAME'
> GROUP BY host_name
> ```

┌─host_name─────┬─cnt──┬─groupUniqArray(shard_weight)─┐
│ 10.41.60.126  │ [1]  │ [1]                          │
│ 10.41.60.136  │ [1]  │ [1]                          │
│ 10.41.60.137  │ [2]  │ [1]                          │
│ 10.41.60.127  │ [2]  │ [1]                          │
│ 10.41.60.138  │ [3]  │ [1]                          │
│ 10.41.60.128  │ [3]  │ [1]                          │
│ 10.41.60.139  │ [4]  │ [1]                          │
│ 10.41.60.129  │ [4]  │ [1]                          │
│ 10.69.176.141 │ [5]  │ [1]                          │
│ 10.69.176.146 │ [5]  │ [1]                          │
│ 10.41.60.123  │ [6]  │ [1]                          │
│ 10.41.60.133  │ [6]  │ [1]                          │
│ 10.41.60.124  │ [7]  │ [1]                          │
│ 10.41.60.134  │ [7]  │ [1]                          │
│ 10.41.60.135  │ [8]  │ [1]                          │
│ 10.41.60.125  │ [8]  │ [1]                          │
│ 10.41.60.130  │ [9]  │ [1]                          │
│ 10.67.57.156  │ [9]  │ [1]                          │
│ 10.67.57.150  │ [10] │ [1]                          │
│ 10.41.60.131  │ [10] │ [1]                          │
│ 10.69.176.116 │ [11] │ [1]                          │
│ 10.69.176.106 │ [11] │ [1]                          │
│ 10.69.176.108 │ [12] │ [1]                          │
│ 10.69.176.118 │ [12] │ [1]                          │
│ 10.69.176.107 │ [13] │ [1]                          │
│ 10.69.176.117 │ [13] │ [1]                          │
│ 10.69.176.110 │ [14] │ [1]                          │
│ 10.69.176.120 │ [14] │ [1]                          │
│ 10.69.176.119 │ [15] │ [1]                          │
│ 10.69.176.109 │ [15] │ [1]                          │
│ 10.69.176.122 │ [16] │ [1]                          │
│ 10.69.176.112 │ [16] │ [1]                          │
│ 10.69.176.121 │ [17] │ [1]                          │
│ 10.69.176.111 │ [17] │ [1]                          │
│ 10.69.176.124 │ [18] │ [1]                          │
│ 10.69.176.114 │ [18] │ [1]                          │
│ 10.69.176.123 │ [19] │ [1]                          │
│ 10.69.176.113 │ [19] │ [1]                          │
│ 10.69.176.131 │ [20] │ [1]                          │
│ 10.69.176.126 │ [20] │ [1]                          │
│ 10.69.176.115 │ [21] │ [1]                          │
│ 10.69.176.125 │ [21] │ [1]                          │
│ 10.69.176.128 │ [22] │ [1]                          │
│ 10.69.176.133 │ [22] │ [1]                          │
│ 10.69.176.127 │ [23] │ [1]                          │
│ 10.69.176.132 │ [23] │ [1]                          │
│ 10.69.176.130 │ [24] │ [1]                          │
│ 10.69.176.135 │ [24] │ [1]                          │
│ 10.69.176.129 │ [25] │ [1]                          │
│ 10.69.176.134 │ [25] │ [1]                          │
│ 10.69.176.143 │ [26] │ [1]                          │
│ 10.69.176.138 │ [26] │ [1]                          │
│ 10.69.176.142 │ [27] │ [1]                          │
│ 10.69.176.137 │ [27] │ [1]                          │
│ 10.69.176.145 │ [28] │ [1]                          │
│ 10.69.176.140 │ [28] │ [1]                          │
│ 10.69.176.139 │ [29] │ [1]                          │
│ 10.69.176.144 │ [29] │ [1]                          │
│ 10.41.60.132  │ [30] │ [1]                          │
│ 10.67.57.151  │ [30] │ [1]                          │
└───────────────┴──────┴──────────────────────────────┘

**Comment by alexey-milovidov** [comment]
This may happen if `id` is a signed integer and contains negative values.
In this case, the value is converted to unsigned integer firstly and only then used as a sharding key.

For example, 

```
$ clickhouse-local 
ClickHouse local version 22.10.1.1.

milovidov-desktop :) SELECT -1 % 10

SELECT -1 % 10

Query id: 1a3c5728-7b6a-4dd8-a81b-82056160d8ec

┌─modulo(-1, 10)─┐
│             -1 │
└────────────────┘

1 row in set. Elapsed: 0.001 sec. 

milovidov-desktop :) SELECT toUInt8(-1) % 10

SELECT toUInt8(-1) % 10

Query id: 380c5c06-500b-4cce-8377-0fdb50fd2786

┌─modulo(toUInt8(-1), 10)─┐
│                       5 │
└─────────────────────────┘

1 row in set. Elapsed: 0.001 sec.
```
