### ISSUE TITLE
Unexpected behaviour of AggregatingMergeTree

### ISSUE THREAD

**Issue by Garnek20** [ClickHouse/ClickHouse#33498]
**Describe what's wrong**

> **AggregatingMergeTree** does not respect expected behaviour for fields of type `SimpleAggregateFunction(max, Array(Tuple(url String, status_code UInt16)))`. 

**Does it reproduce on recent release?**

> Tested on Clickhouse 21.13.1.1 

**How to reproduce**

* ClickHouse server version: 21.13.1.1
* Create a table 
> `CREATE TABLE test_tuple_aggreg
(
    `id` UInt32,
    `session_date` Date,
    `tuples` SimpleAggregateFunction(groupUniqArrayArray(2), Array(Tuple(
        url String,
        status_code UInt16
    )))
)
ENGINE = AggregatingMergeTree
PARTITION BY session_date
ORDER BY id`

* Inspect created table: `SHOW CREATE TABLE test_tuple_aggreg`
> Result: `CREATE TABLE default.test_tuple_aggreg
(
    `id` UInt32,
    `session_date` Date,
    `tuples.url` Array(String),
    `tuples.status_code` Array(UInt16)
)
ENGINE = AggregatingMergeTree
PARTITION BY session_date
ORDER BY id
SETTINGS index_granularity = 8192`

We loose track of `SimpleAggregateFunction`.

* Populate the table to see if correct aggregations are used
>  * `INSERT INTO `test_tuple_aggreg` VALUES (1, '2022-01-02', ['url1'], [500])`
>  * `INSERT INTO `test_tuple_aggreg` VALUES (1, '2022-01-03', ['url2'], [404])`
>  * `INSERT INTO `test_tuple_aggreg` VALUES (1, '2022-01-04', ['url3'], [503])`

* When we inspect the data we see all 3 rows
> select * from test_tuple_aggreg 
   `┌─id─┬─session_date─┬─tuples.url─┬─tuples.status_code─┐
│  1 │   2022-01-02 │ ['url1']   │ [500]              │
└────┴──────────────┴────────────┴────────────────────┘
┌─id─┬─session_date─┬─tuples.url─┬─tuples.status_code─┐
│  1 │   2022-01-02 │ ['url1']   │ [500]              │
└────┴──────────────┴────────────┴────────────────────┘
┌─id─┬─session_date─┬─tuples.url─┬─tuples.status_code─┐
│  1 │   2022-01-04 │ ['url3']   │ [503]              │
└────┴──────────────┴────────────┴────────────────────┘`

* When we optimise it we see that wrong aggregation is picked for `tuples` fields
> select * from test_tuple_aggreg final
   `┌─id─┬─session_date─┬─tuples.url─┬─tuples.status_code─┐
│  1 │   2022-01-02 │ ['url1']   │ [500]              │
└────┴──────────────┴────────────┴────────────────────┘`

**Expected behavior**

Preserved schema with `SimpleAggregateFunction` and correct aggregation of rows according to created schema `groupUniqArrayArray(2)`.

Expected aggregation result:
`┌─id─┬─session_date─┬─tuples.url─┬─tuples.status_code─┐
│  1 │   2022-01-02 │ ['url1', 'url2']   │ [500, 404]              │
└────┴──────────────┴────────────┴────────────────────┘`

**Comment by den-crane** [comment]
There is 2 independent issues.

>PARTITION BY session_date

Clickhouse merge rows only over a partition. You inserted data into different partitions  '2022-01-02' '2022-01-03' '2022-01-04'

------

Also there is an issue in CH

```sql 
CREATE TABLE test_tuple_aggreg
(
    `id` UInt32,
    `session_date` Date,
    `tuples` SimpleAggregateFunction(groupUniqArrayArray(2), Array(Tuple(url String, status_code UInt16)))
)
ENGINE = AggregatingMergeTree
PARTITION BY session_date
ORDER BY id;

show create  table test_tuple_aggreg;

CREATE TABLE test_tuple_aggreg
(
    `id` UInt32,
    `session_date` Date,
    `tuples.url` Array(String),    ----- SimpleAggregateFunction is lost
    `tuples.status_code` Array(UInt16)   ---- SimpleAggregateFunction is lost
)
ENGINE = AggregatingMergeTree
PARTITION BY session_date
ORDER BY id
SETTINGS index_granularity = 8192




set flatten_nested=0;




CREATE TABLE test_tuple_aggreg
(
    `id` UInt32,
    `session_date` Date,
    `tuples` SimpleAggregateFunction(groupUniqArrayArray(2), Array(Tuple(url String, status_code UInt16)))
)
ENGINE = AggregatingMergeTree
PARTITION BY session_date
ORDER BY id;

show create  table test_tuple_aggreg;

CREATE TABLE test_tuple_aggreg
(
    `id` UInt32,
    `session_date` Date,
    `tuples` SimpleAggregateFunction(groupUniqArrayArray(2), Array(Tuple(url String, status_code UInt16)))
)
ENGINE = AggregatingMergeTree
PARTITION BY session_date
ORDER BY id
SETTINGS index_granularity = 8192;

```

-----


```sql
set flatten_nested=0;       ----<<<<<<<-----

CREATE TABLE test_tuple_aggreg
(
    `id` UInt32,
    `session_date` Date,
    `tuples` SimpleAggregateFunction(groupUniqArrayArray(2), Array(Tuple(url String, status_code UInt16)))
)
ENGINE = AggregatingMergeTree
PARTITION BY toYYYYMM(session_date) ----<<<<<<<-----
ORDER BY id
SETTINGS index_granularity = 8192;

INSERT INTO test_tuple_aggreg VALUES (1, '2022-01-02', [('url1', 500)]);
INSERT INTO test_tuple_aggreg VALUES (1, '2022-01-03', [('url2', 404)]);
INSERT INTO test_tuple_aggreg VALUES (1, '2022-01-04', [('url3', 503)]);

optimize table test_tuple_aggreg final;

select * from test_tuple_aggreg;
┌─id─┬─session_date─┬─tuples──────────────────────┐
│  1 │   2022-01-02 │ [('url2',404),('url1',500)] │  !!!!! session_date calculated by ANY because it's a measurement in this table definition  !!!!! 
└────┴──────────────┴─────────────────────────────┘
```

**Comment by Garnek20** [comment]
Hello @den-crane ,
Thank you for you reply. Indeed I used different dates, mainly because it was for tests and I run query with **final** ignoring partitioning.

I see your workaround, thanks.

**Comment by den-crane** [comment]
>Is it another issue or am I doing something wrong?

Clickhouse creates 2 different structures depending of `flatten_nested` columnS with Arrays or a column with Arrays of Tuples.
So you should insert accordingly.

array `INSERT INTO test_nested_aggreg VALUES (1, '2022-01-02', ['url1'], [500])`
tuple `INSERT INTO test_nested_aggreg VALUES (1, '2022-01-04', [('url1', 500)])`
