### ISSUE TITLE
Support TTL with Datetime64

### ISSUE THREAD

**Issue by mr-karan** [ClickHouse/ClickHouse#33493]
**Use case**

My table structure involves a `timestamp` column (which is also used as the sorting key) but the type of that column is `Datetime64(3, 'Asia/Kolkata')`. 

```sql
CREATE TABLE IF NOT EXISTS events.local ON CLUSTER '{cluster}' (
    `_timestamp` Datetime64(3, 'Asia/Kolkata'),
    ...
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{cluster}/{shard}/table', '{replica}')
PARTITION BY toYYYYMMDD(_timestamp)
ORDER BY _timestamp
TTL _timestamp + INTERVAL 30 DAY;
```

I would like to set a TTL based on this column but I get an error right now:

```
Code: 450. DB::Exception: Received from localhost:9000. DB::Exception: There was an error on [clickhouse-green-1:9000]: Code: 450. DB::Exception: TTL expression result column should have DateTime or Date type, but has DateTime64(3, 'Asia/Kolkata'). (BAD_TTL_EXPRESSION) (version 21.12.3.32 (official build)). (BAD_TTL_EXPRESSION)
```

**Describe the solution you'd like**

Is it possible to support `DateTime64` for adding TTLs? Would be really helpful!

**Describe alternatives you've considered**

Use a separate column to store timestamp with `ms` precision and another column to store with `seconds` precision, just to satisfy the TTL limitation.

Thanks!

**Comment by UnamedRus** [comment]
For now you can do the following:

```
CREATE TABLE IF NOT EXISTS events.local ON CLUSTER '{cluster}' (
    `_timestamp` Datetime64(3, 'Asia/Kolkata'),
    ...
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{cluster}/{shard}/table', '{replica}')
PARTITION BY toYYYYMMDD(_timestamp)
ORDER BY _timestamp
TTL toDateTime(_timestamp) + INTERVAL 30 DAY;
```

**Comment by mr-karan** [comment]
@UnamedRus Ah nice. Thanks for the tip!

**Comment by alexey-milovidov** [comment]
Looks like @Enmk from Altinity is not responsible for supporting this feature. Let's close or reassign.
