### ISSUE TITLE
Does postgres engine support foreign wrappers?

### ISSUE THREAD

**Issue by simPod** [ClickHouse/ClickHouse#33502]
I'm using https://clickhouse.com/docs/en/engines/database-engines/postgresql/ to connect into a pg db that has a foreign schema wrapper.  
https://www.postgresql.org/docs/current/postgres-fdw.html

Is foreign wrapper supported by clickhouse? I'm able to create a database `CREATE DATABASE a ENGINE = PostgreSQL` but there are no tables.

```sql
CREATE DATABASE pg_old
ENGINE = PostgreSQL('pg:5432', 'db', 'clickhouse', 'pwd', `foreign_schema`); -- connection is ok, no tables fetched by clickhouse
CREATE DATABASE pg_public
ENGINE = PostgreSQL('pg:5432', 'db', 'clickhouse', 'pwd', `public`); -- this one works, tables present, selects can be done etc.
```

**Comment by kssenii** [comment]
Yes, it is supported, see https://github.com/ClickHouse/ClickHouse/blob/master/tests/integration/test_postgresql_database_engine/test.py#L186-L208 for example.

Which clickhouse version do you use?

**Comment by simPod** [comment]
Sorry for not providing it.

v21.12.3.32

Error log is empty

`SHOW TABLES FROM pg_old;` gives no rows, I wonder how to debug it.

**Comment by simPod** [comment]
Ah, tried to reload the "empty foreign db" in datagrip and clickhouse error logs give

> DB::Exception: PostgreSQL table chunk does not exist.

now I have to find what does it mean.

**Comment by kssenii** [comment]
Looks like this query
https://github.com/ClickHouse/ClickHouse/blob/master/src/Databases/PostgreSQL/fetchPostgreSQLTableStructure.cpp#L41-L43
returned tables list where there is table with name `chunk`
but this query 
https://github.com/ClickHouse/ClickHouse/blob/master/src/Databases/PostgreSQL/fetchPostgreSQLTableStructure.cpp#L256-L261
said that table does not exist.
Can you check these queries manually on postgres client?

**Comment by kssenii** [comment]
Ok, I think I found why this happened, will make a fix.

**Comment by simPod** [comment]
That was quick! I have not decrypted queries from `format()` yet. Let me know if you need me to run something on my foreign schema.
