### ISSUE TITLE
Add toEndOfMonth function 

### ISSUE THREAD

**Issue by alexandr-subota-idf** [ClickHouse/ClickHouse#33501]
Currently we need to write smth like
select toStartOfMonth(date) + interval 1 month - interval 1 day
to get the date of last day of month.

Can we have function toEndOfMonth to get the date of last day of month?
*With synonym LAST_DAY() (function name from MySql)

**Comment by alexey-milovidov** [comment]
Yes, makes sense.

**Comment by alexey-milovidov** [comment]
> select toStartOfMonth(date) + interval 1 month - interval 1 day

More like:
`toStartOfMonth(date + interval 1 month) - interval 1 day`

**Comment by holadepo** [comment]
I would like to work on this.

**Comment by alexey-milovidov** [comment]
@holadepo Thank you, it will be very appreciated!

**Comment by ryanoliverdev** [comment]
@holadepo are you still working on this issue? If not I'd like to pick it up

**Comment by holadepo** [comment]
@ryanoliverdev Yes I am still working on it.

**Comment by alexey-milovidov** [comment]
@holadepo Are you still working on it?

**Comment by alexey-milovidov** [comment]
`DateLUTImpl.h`

look at `toFirstDayOfMonth` and add similar `toLastDayOfMonth` functions
by replacing `i - (lut[i].day_of_month - 1)` to `i - lut[i].day_of_month + lut[i].days_in_month`

look at `DateTimeTransforms.h` and add a new transforms similar to others.

look at the usages of the existing DateTimeTransforms and add similar.

**Comment by holadepo** [comment]
Thanks @alexey-milovidov. This was really helpful

**Comment by holadepo** [comment]
I think the name of this function should be `toLastDayOfMonth` rather than `toEndOfMonth` as the last day of a month is not exactly the end of the month. What do you think @alexandr-subota-idf @alexey-milovidov?

**Comment by alexey-milovidov** [comment]
@holadepo Yes, this name is better.
