### ISSUE TITLE
Quick Start for macOSX Apple Silicon on public website has broken download URL

### ISSUE THREAD

**Issue by jagu2012** [ClickHouse/ClickHouse#33509]
(I can't find an active repo for the public website, so posting this issue on ClickHouse/ClickHouse).

The clickhouse.com Quick Start guide for macOSX (Apple silicon) instructs the user to download clickhouse from this URL which is currently returning a 404.

'https://builds.clickhouse.com/master/macos-aarch64/clickhouse'

To reproduce
1. Open Quick Start Page
https://clickhouse.com/#quick-start

2. Choose "macOS (Apple silicon)"
You will see these instructions
   wget 'https://builds.clickhouse.com/master/macos-aarch64/clickhouse'
   chmod a+x ./clickhouse
   ./clickhouse

3. Attempt that wget
wget 'https://builds.clickhouse.com/master/macos-aarch64/clickhouse'

HTTP request sent, awaiting response... 404 Not Found
2022-01-11 17:26:13 ERROR 404: Not Found.

**Comment by Algunenano** [comment]
Same as https://github.com/ClickHouse/ClickHouse/issues/33480
