### ISSUE TITLE
Is it OK to implement a direct ORC/Parquet input/output format? 

### ISSUE THREAD

**Issue by zhanglistar** [ClickHouse/ClickHouse#33545]
Now, the ORC and Parquet format are implemented by using Apache Arrow as a converter, but there is so much memory copy resulting a performance decreasing. 
The question is that it is OK to implement a direct reader/writer to process ORC/Parquet format data?

**Comment by alexey-milovidov** [comment]
Yes, it will be very appreciated (if there will be performance benefit).

**Comment by alexey-milovidov** [comment]
It's ok to use some library better suited for it. And it is even Ok to read the format manually.
For example, we do it for Protobuf :)
