### ISSUE TITLE
how to use  mongo engine

### ISSUE THREAD

**Issue by MadeonZedd** [ClickHouse/ClickHouse#33557]
my mongodb server address is mongodb://xxx:xxx@192.168.19.97:27017/xxx:xxxx?authSource=admin&readPreference=primary&appname=MongoDB%20Compass&directConnection=true&ssl=false

 i was use that  it can create but not work for query  Timeout: connect timed out: 192.168.19.97:27017. (POCO_EXCEPTION)
 
 CREATE TABLE t_log_demo
    (
        key UInt64,
        data String
    ) ENGINE = MongoDB('192.168.19.97:27017', 'xxx', 'xxx', 'xxx', 'xxx','authSource=admin');

**Comment by kssenii** [comment]
See solution here https://github.com/ClickHouse/ClickHouse/issues/30836#issuecomment-984254532.

**Comment by alexey-milovidov** [comment]
@kssenii Should we put it somewhere in documentation?

**Comment by MadeonZedd** [comment]
> See solution here [#30836 (comment)](https://github.com/ClickHouse/ClickHouse/issues/30836#issuecomment-984254532).

thanks....... T_T

**Comment by MadeonZedd** [comment]
> how to use options like that ?  but  authSource=amdin not work  must  set database admin  

CREATE TABLE mongo_table
(
    key UInt64,
    data String
) ENGINE = MongoDB('mongo2:27017', 'test', 'simple_table', 'testuser', 'clickhouse', 'authSource=admin&connectTimeoutMS=100000');

**Comment by kssenii** [comment]
> how to use more options like that ? but authSource=amdin not work must set database admin

options can be delimited by &, you wrote it correctly
