### ISSUE TITLE
Kafka ENGINE SETTINGS  offset reset

### ISSUE THREAD

**Issue by Folgerjun** [ClickHouse/ClickHouse#33558]
Hi, brothers.
I want to set `auto.offset.reset`. 
But I don't find doc about this.
When I setting `kafka_auto_offset_reset`  run ->  `Unknown setting kafka_auto_offset_reset`.
How should I configure?😭

**Comment by qoega** [comment]
There are some config files with examples. Probably it will work for you?
https://github.com/ClickHouse/ClickHouse/search?q=auto_offset_reset

**Comment by Folgerjun** [comment]
can't setting when I create table ? 😂

like that:
```
CREATE TABLE ffj.table_test
(
    visit_time     Int64 comment '时间戳（秒）',
    user_id        Int64 comment '用户ID'
) ENGINE = Kafka SETTINGS
    kafka_broker_list = '127.0.0.1:9092',
    kafka_topic_list = 'topic',
    kafka_group_name = 'clickhouse_group',
    kafka_format = 'JSONEachRow',
    kafka_skip_broken_messages = 10,
    kafka_num_consumers = 1;
```

**Comment by genzgd** [comment]
At this time only a small number of Kafka consumer settings can be set using the [Kafka Engine](https://clickhouse.com/docs/en/engines/table-engines/integrations/kafka).  You can add additional settings either for all Kafka Engine tables in the \<kafka> section of the server configuration file, or apply specific settings when reading a specific topic using a <kafka_[topic]> tag.  [Kafka extended configuration](https://clickhouse.com/docs/en/engines/table-engines/integrations/kafka/#configuration)
