### ISSUE TITLE
how to find out the last access_time or query_time  of a table?

### ISSUE THREAD

**Issue by windylcx** [ClickHouse/ClickHouse#33554]
case one ,I want to find out the tables that have never been access for a long time,and then need to be delete 
case two, I want to find out which table data is the hot data(query  most frequently)

I have checked the system tables,
system.table (lack of a filed like  access_time )
system.parts (lack of a field like  access_time time)
system.query_log (lack of  a filed like 'table_name')
system.zookeeper (lack of a field like  access_time)

but there's no  an easy way to do this ,for example use the sql or write some simple codes to find out 

pls help.

**Comment by nvartolomei** [comment]
`system.query_log` is probably your best bet.

```
DESCRIBE TABLE  system.query_log FORMAT JSONEachRow;

...
{"name":"databases","type":"Array(LowCardinality(String))","default_type":"","default_expression":"","comment":"","codec_expression":"","ttl_expression":""}
{"name":"tables","type":"Array(LowCardinality(String))","default_type":"","default_expression":"","comment":"","codec_expression":"","ttl_expression":""}
...
```

**Comment by windylcx** [comment]
> tables
thx,but my version is 20.9.3.45 ,there is no "databases" and "tables", maybe the only way is   parse  the db an table from  the  sql query text?

**Comment by alexey-milovidov** [comment]
@windylcx It's only possible in the recent versions.
You can quickly install the new version as following:
```
curl https://clickhouse.com/ | sh
```
