### ISSUE TITLE
Install Clickhouse on Pfsense 

### ISSUE THREAD

**Issue by AnhTuanNguyenn** [ClickHouse/ClickHouse#33572]
hello, i'm just new here, 
i try to install ntopng with dumping data but when i tried to install clickhouse that seem not working for me, 

os: freebds 12 amd64
ntop 5.1

someone have any link for tutorial ? i tried install followed link on web but dontwork too, 
thank for your help

**Comment by vijaytejak** [comment]
any update on this?
