### ISSUE TITLE
'Quick Start' download url returns 404

### ISSUE THREAD

**Issue by tekeri** [ClickHouse/ClickHouse#33586]
**Describe the issue**
The links in Quick Start page ( https://clickhouse.com/#quick-start ) is broken.

```wget 'https://builds.clickhouse.com/master/aarch64/clickhouse'```

returns 404 not found with the following content.

```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Resource>/master/aarch64/clickhouse</Resource>
<RequestId>79efc076c416ac63</RequestId>
</Error>
```

**Comment by Algunenano** [comment]
Duplicated https://github.com/ClickHouse/ClickHouse/issues/33480
