### ISSUE TITLE
clickhouse-local - support shebang

### ISSUE THREAD

**Issue by mikeTWC1984** [ClickHouse/ClickHouse#33584]
**Use case**

Since clickhouse-local act like a repl now, that would be logical to allow it to execute sql statements with shebang
That would be useful for cronjob scripts and CH based tool building (e.g. format convertor), etc
```bash
#!/usr/bin/env -S clichouse-local  --input-format Parquet
select * from table FORMAT Pretty
```

**Comment by egor-sivokhin2001** [comment]
Hello, I would like to take this issue. 

### Proposed solution
<img width="661" alt="image" src="https://user-images.githubusercontent.com/98153984/150524998-52a88f5b-901f-4932-b3f3-766ab384f470.png">

Basically I am filtering shebang from the first line of each file. So you can now do the following
```sql
#!/usr/bin/env -S clickhouse-local --structure "a Int64, b Int64" --queries-file build/query.ch --input-format "CSV" --queries-file
SELECT * FROM table FORMAT Pretty;
```
and then
```console
$ echo -e "1,3\n1,2" | query.sql
```
**Note that you need to add `--queries-file` to the end of shebang**

### Reason
Clickhouse already can read query from files via `--queries-file`. So the only thing we need to do is to filter shebang when it appears in a file. Everything else remains the same.
