### ISSUE TITLE
User_dn_detection does not work for role mapping in AD

### ISSUE THREAD

**Issue by lavasser** [ClickHouse/ClickHouse#33589]
### My test stand
**Clickhouse** 21.12.2.17
**Active Directory LDS**: company.com
**User_DN** CN=**ldap user**,CN=users,CN=test,DC=company,DC=com
**Role mapping group** CN=clickhouse_role1,CN=groups,CN=test,DC=company,DC=com

### Problem

The user is trying to log in under **ldapuser** (attribute LDAP userPrincipalName)
There are the following errors during authorization:

<Error> Access(user directories): from: 192.168.1.79, user: ldapuser: Authentication failed: Code: 192. DB::Exception: There is no user ldapuser in user directories. (UNKNOWN_USER)

<<Error> Server Error Handler: Code: 516. DB::Exception: ldapuser: Authentication failed: password is incorrect or there is no user with such name. (AUTHENTICATION_FAILED)

I understand that **user_dn_detection** replaces the username (sAMAccountName = ldapuser) with his DN (CN=ldap user,CN=users,CN=test,DC=company,DC=com).

If I disable **user_dn_detection**, then the user is successfully logged in, but without mapping roles.

How to make role mapping work in AD via user_dn_detection?

### Note
There is no sAMAccountName in AD LDS, userPrincipalName is used instead. Therefore, there is no difference.

### LDAP config
	<ldap_servers>
		<ldap_1>
			<host>192.168.1.3</host>
			<port>389</port>
			<enable_tls>no</enable_tls>
			<bind_dn>cn={user_name},cn=users,cn=test,dc=company,dc=com</bind_dn> 
			<user_dn_detection>
				<base_dn>cn=users,cn=test,dc=company,dc=com</base_dn>
				<search_filter>(&amp;(objectClass=user)(userPrincipalName={user_name}))</search_filter> 
			</user_dn_detection>
			 <tls_require_cert>never</tls_require_cert>
		</ldap_1>
	</ldap_servers>

	<user_directories>
		<ldap>
			<role_mapping>
				<base_dn>cn=groups,cn=test,dc=company,dc=com</base_dn>
				<scope>subtree</scope>
				<search_filter>(&amp;(objectClass=group)(member={user_dn}))</search_filter>
				<attribute>cn</attribute>
				<prefix>clickhouse_</prefix>
			</role_mapping>
			<server>ldap_1</server>
		</ldap>
	</user_directories>

**Comment by traceon** [comment]
May be fixed by #33401

**Comment by lavasser** [comment]
Hello! 
I create a AD domain instead of AD LDS. And **User_dn_detection** is working successfully. 
I created two users:
CN=Vasya Pupkin - successfully logged in
CN=Vasya Pupkin (123456) - not authorized.
I confirm that escaping brackets does not work.
Thank you very much!

**Comment by traceon** [comment]
>  I confirm that escaping brackets does not work.

@lavasser could you please clarify, is it fully fixed for you? So which scenario is expected to work but is not working with the latest build from `master` (with auto-escaping of brackets)?

**Comment by lavasser** [comment]
I tested on version 21.12.3.32
I'm waiting for the version where this is fixed

**Comment by traceon** [comment]
But the `master` build worked for you, right?

**Comment by lavasser** [comment]
Yes, I checked yesterday

**Comment by lavasser** [comment]
It didn 't work on version 22.1.2.2.
And which version will it be fixed?

**Comment by traceon** [comment]
Can't tell for sure, but most likely starting from 22.2.
Since the fix is there, we can probably close this issue then?

**Comment by lavasser** [comment]
Ok. Thank you!
