### ISSUE TITLE
STORJ instead of S3?

### ISSUE THREAD

**Issue by sv3t0sl4v** [ClickHouse/ClickHouse#33599]
**Use case** Shard out to STORJ instead of S3

**Describe the solution you'd like**: STORJ is **about 6 times cheaper** than S3 and is:
- cheaper - Oh! I said that already!
- more secure - you do not have to trust STORJ or node operators - nobody knows what they store and they can't use the data. On the other hand, you have to trust Amazon with your ClickHouse data, which is... Ha-ha! No.
- has no downtime as it is decentralized cloud storage: data is torn to pieces, encrypted and spread across thousands of nodes all over the world 
...

**Comment by den-crane** [comment]
STORJ is S3 Compatible. So you can use it as S3 disk ?
The same with https://www.backblaze.com/ it's cheaper and ClickHouse able to use it as S3 disk.

**Comment by sv3t0sl4v** [comment]
Did you try grant ClickHouse access to STORJ? I am not familiar with back blaze, but I would rather use a distributed storage.

**Comment by den-crane** [comment]
>Did you try grant ClickHouse access to STORJ? 

What do you mean?

**Comment by sv3t0sl4v** [comment]
You said > STORJ is S3 Compatible.
So did you try it?

**Comment by den-crane** [comment]
> You said > STORJ is S3 Compatible. 

It's stated on their site.

>So did you try it?

No

**Comment by den-crane** [comment]
https://www.storj.io/blog/what-is-s3-compatibility

The distributed security tokens (access grants) that Storj uses contain too much detail to fit into an S3 access key or secret key field. Storj offers an S3-specific authorization service, which maps S3-compatible credentials to a Storj access grant. For our upcoming multi-tenant gateway, we use the same terminology as S3 credentials: access key and secret key.

**Comment by sv3t0sl4v** [comment]
Sounds great! Thanks for pointing out! Haven't gone into that much detail, yet. The project sounds very promising, IMHO.

**Comment by sv3t0sl4v** [comment]
Looks like this is how it is done - https://docs.storj.io/dcs/how-tos/how-to-connect-s3fs-to-storj-dcs#create-the-credentials-file
