### ISSUE TITLE
uniqState(UUID) doesn't produce the same result for 21.5 and 21.6 versions

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#33607]
**Describe the issue**
In case of clickhouse upgrade between any version pre 21.6 to newer version. 

All uniqState(UUID) columns in AggregatingMergeTree tables will be screwed and produce incorrect results in case of -Merge between them.
 
**How to reproduce**
```
clickhouse-client -mn --query "SELECT version(), uniqState(toUUID('6d674e35-0171-4e5d-b09c-ea421dbf33c5')) AS a;"
21.6.9.7        \0���K

clickhouse-client -mn --query "SELECT version(), uniqState(toUUID('6d674e35-0171-4e5d-b09c-ea421dbf33c5')) AS a;"
21.5.9.4        \0�X��


clickhouse-client -mn --query "SELECT version(), uniqState(reinterpretAsInt128(toUUID('6d674e35-0171-4e5d-b09c-ea421dbf33c5'))) AS a;"
21.5.9.4        \0���K
```

**Additional context**
Related to https://github.com/ClickHouse/ClickHouse/pull/23631

**Comment by inakisoriamrf** [comment]
This is a major issue for us, we can't migrate to newer versions.

Maybe this could be controlled by a flag on how UUIDs or uniqState of UUIDs are encoded?

**Comment by inakisoriamrf** [comment]
Hi @alexey-milovidov I don't think this is obsolete. This prevent you from migrating from 21.3 LTS to 21.8 LTS

**Comment by UnamedRus** [comment]
Yes, we can choose whatever version both before and after 21.6

Both 21.3 and 21.8 are LTS

```
SELECT
    version(),
    uniqState(toUUID('6d674e35-0171-4e5d-b09c-ea421dbf33c5')) AS a

Query id: 666601ea-1461-477f-941c-63db78824b0f

┌─version()─┬─a─┐
│ 21.3.15.4 │ �X�� │
└───────────┴───┘

1 rows in set. Elapsed: 0.002 sec.
```

```
SELECT
    version(),
    uniqState(toUUID('6d674e35-0171-4e5d-b09c-ea421dbf33c5')) AS a

Query id: 85ad15b7-3bbf-4668-96b6-b82bd4a44b7e

┌─version()────────────────┬─a─┐
│ 21.8.13.6│ ���K │
└──────────────────────────┴───┘
```

**Comment by alexey-milovidov** [comment]
There is very low chance that this issue will be addressed.
It was broken once but we don't want to break it again if we return the old behaviour.

The new behaviour is correct and as we already have made this change and cannot simply revert it, better to live with it.

You can ask @filimonov or @UnamedRus for workarounds.

PS. Since version 21.12 we have introduced versioning of aggregate function states #12552 to prevent these issues in future.

**Comment by UnamedRus** [comment]
Workaround: https://kb.altinity.com/altinity-kb-setup-and-maintenance/uniq-uuid-doubled-clickhouse-upgrade/

**Comment by den-crane** [comment]
The same issue with  uniqHLL12State / uniqCombinedState / uniqCombined64State
