### ISSUE TITLE
Does async inserts work with distributed table?

### ISSUE THREAD

**Issue by gauravphoenix** [ClickHouse/ClickHouse#33617]
Let's say I have a client C that writes to distributed table D that writes to a target table T (running on a different host than the distributed table). 

Is the communication between the distributed table and the target table asynchronous? In other words does the client need to set any parameter to tell distributed table to write asynchronously?

**Comment by gingerwizard** [comment]
Inserts into distributed tables are indeed asynchronous. The table buffers the inserts to disk, forming batches. The client receives a response immediately to the insert, once the inserts have been written to disk - we provide various write guarantees for this buffering. Asynchronously we send these batches to the underlying table. These subsequent sends may fail. If this occurs, the client has no means of being informed.

The behaviour of how inserts are batched prior to sending to underlying tables can be configured - see https://clickhouse.com/docs/en/engines/table-engines/special/distributed/ for further details.

**Comment by den-crane** [comment]
Yes, async inserts work with any engine.

**Comment by den-crane** [comment]
@gauravphoenix it's two different features. 

 --async_insert arg                                                   If true, data from INSERT query is stored in queue and later flushed to table in background.

 --insert_distributed_sync arg                                        If setting is enabled, insert query into distributed waits until data will be sent to all nodes in cluster.
