### ISSUE TITLE
when i set the password and can't login

### ISSUE THREAD

**Issue by liuyuchuan** [ClickHouse/ClickHouse#33622]
> Make sure that `git diff` result is empty and you've just pulled fresh master. Try cleaning up cmake cache. Just in case, official build instructions are published here: https://clickhouse.yandex/docs/en/development/build/

when i install in my CentOS 7, i set the password is 'password!!123', then i restart the clickhouse-server and use the clickhouse-client connect the server, the server return the message require the password, then i set the password is 'password123', i reback to login and success, i want to know why i can't use the Special characters for '!!'

**Operating system**

> OS kind or distribution, specific version/release, non-standard kernel if any. If you are trying to build inside virtual machine, please mention it too.

[user@zhangsan2 ~]# uname -a
Linux zhangsan2 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Cmake version**

**Ninja version**

**Compiler name and version**

ClickHouse server version 20.8.3.18.

ClickHouse client version 20.8.3.18.

**Full cmake and/or ninja output**

**Comment by den-crane** [comment]
20.8.3.18 is end of life. 
alternative builds are not supported

**Comment by den-crane** [comment]
Check with official build and 21.12 version

**Comment by liuyuchuan** [comment]
thanks for your advice. I'll try your plan.
