### ISSUE TITLE
How can I confirm that SQL execution uses vectorized computation?

### ISSUE THREAD

**Issue by asasas234** [ClickHouse/ClickHouse#33620]
Does clickhouse use vectorisation for all SQL or some of it and if so, how do I know if my SQL is using vectorisation?

**Comment by alexey-milovidov** [comment]
Some computations are vectorized and some are not.

You can run the following commands in Ubuntu:

```
sudo apt install linux-tools-common
sudo perf top
```

Then navigate to the top functions from ClickHouse.
Open disassembly. And find vector instructions there.

On x86 CPUs vector instructions are using vector registers (named with `xmm`, `ymm`, `zmm`).
And the instructions are named starting with `p` (packed) or `vp`.
Although some other non-vector instructions can also use vector registers.

**Comment by asasas234** [comment]
Thank you for your answer @alexey-milovidov
