### ISSUE TITLE
DB::Exception: Bad hdfs url error when creating HDFS table or using hdfs engine with servicename instead of hostname:port.

### ISSUE THREAD

**Issue by alexryndin** [ClickHouse/ClickHouse#33627]
There is a degradation in transition from 21.3LTS to 21.8LTS in HDFS engine. As you may know and as the Documentation states (https://clickhouse.com/docs/en/engines/table-engines/integrations/hdfs/#namenode-ha), Clickhouse supports namenode high aviability feature, so one may use url in form of `hdfs://hacluster/path/to/file.txt`. And yet starting with version 21.8 clickhouse gives an error in attempt to create such a table or select data from hdfs:
```CREATE TABLE _hdfs_engine_table (name String, value UInt32) ENGINE=HDFS('hdfs://hacluster/clickhouse_test.txt', 'CSV');

CREATE TABLE _hdfs_engine_table
(
    `name` String,
    `value` UInt32
)
ENGINE = HDFS('hdfs://hacluster/clickhouse_test.txt', 'CSV')

Query id: c43d8cd6-ba8a-47a9-b7d5-a69c1382208b


0 rows in set. Elapsed: 0.001 sec.

Received exception from server (version 21.8.13):
Code: 36. DB::Exception: Received from localhost:9000. DB::Exception: Bad hdfs url: hdfs://hacluster/clickhouse_test.txt. It should have structure 'hdfs://<host_name>:<port>/<path>'.
```
This looks like a wrong check, enforcing user to use `<host>:<port>`  url format instead of convenient HA servicename.

## Version
```
:) select version();

SELECT version()

Query id: 40882f2a-f8ea-46b1-a060-e41a0b04dd0c

┌─version()─┐
│ 21.8.13.6 │
└───────────┘

1 rows in set. Elapsed: 0.001 sec.
```

**Comment by alexryndin** [comment]
Wrong behavior was introduced with this commit https://github.com/ClickHouse/ClickHouse/commit/3839d521a0effd4b839ca28ce1b57b259c951b5c
@Avogar Have you taken into account that Clichouse should also be able to access HDFS HA and thus this check and behavior it enforces, especially introduced by this check (https://github.com/ClickHouse/ClickHouse/commit/3839d521a0effd4b839ca28ce1b57b259c951b5c#diff-0a2145f802c308087909f075cf31b69f36caa34a69365c6b8e82bb4f35209175R22) is wrong?

**Comment by Avogar** [comment]
Was fixed in https://github.com/ClickHouse/ClickHouse/pull/32976

**Comment by Avogar** [comment]
Oh, I see, It was backported only in 21.12
