### ISSUE TITLE
sql mutation testing tool

### ISSUE THREAD

**Issue by R-omk** [ClickHouse/ClickHouse#33640]
Sometimes analytical queries are large and very large, the classical approach used in programming languages with test coverage is not applicable in this case.

Is there any approach or ready-made toolkit for [mutation testing](https://en.wikipedia.org/wiki/Mutation_testing) of clickhouse sql queries?

**Comment by UnamedRus** [comment]
Do you mean AST fuzzing tests? (If so, ClickHouse already has them)

https://clickhouse.com/blog/en/2021/fuzzing-clickhouse/

**Comment by R-omk** [comment]
Interesting article and materials on the topic, I will study it in more detail. But the terminology is still different, fuzzing and mutation are slightly different things. The last allows you to check the completeness of tests with the same input and result data at a time when fuzzing is more about randomizing everything.

Mutation testing allows it to find cases where the _test passes_ when it _should not_, while fuzzing is trying to crash the application.

**Comment by den-crane** [comment]
@R-omk https://www.youtube.com/watch?v=s_HYtH-03fA https://heisenbug-piter.ru/en/2021/spb/talks/nr1cwknssdodjkqgzsbvh/

**Comment by alexey-milovidov** [comment]
I've considered using mutation testing for ClickHouse and we discussed it with the team a year ago.

Mutation testing is a testing technique for tests.

It is the following: you introduce random bugs to the code, run your test suites and check if they are failed.
Usually it is to introduce off-by-one errors, remove some checks, etc...
If the tests are not failed - you have to add more tests.

The downside is that it is very slow and resource consuming.
For example, full compilation of ClickHouse takes around 10 minutes on a server and around 10 seconds in most cases if one file is modified. But we have many test suites that require multiple hours to run. We are running all of them in parallel but it still requires multiple hours.

**Comment by alexey-milovidov** [comment]
And we decided to introduce one small thing, slightly resembling mutation testing:
- when new test is added for bugfix we will check that this test is actually reproducing the bug in previous version.

(it should not always be true, but it's a good info)

**Comment by alexey-milovidov** [comment]
To speed up mutation testing we wanted to introduce per-test code coverage.

So, for every single test we can show what lines of code are covered.
And for every line of code we can show what tests covers it.

I did not see any other project with *per test granular* code coverage before.
We started to implement it, but it was abandoned: https://github.com/ClickHouse/ClickHouse/pull/20539

**Comment by R-omk** [comment]
@alexey-milovidov 

The most suitable example of a utility that I want to find [is the](https://content.clickhouse.tech/docs/en/operations/utilities/clickhouse-format/) `clickhouse-format --seed seed --obfuscate`, but instead of masking a query, I need the utility to generate a list of queries that have small mutations from the original query. 

I also tried to find a utility that can convert a sql query  (ch dialect) to AST representation in language neutral format like json or yaml and in reverse order. In this case, I could independently inject mutations into ast using any language and then re-create query in the sql format.

**Comment by alexey-milovidov** [comment]
@R-omk Maybe this will be helpful: https://github.com/ClickHouse/ClickHouse/pull/30012
