### ISSUE TITLE
Wrong results are returned after TTL merge When there is skip index on the column with ttl.

### ISSUE THREAD

**Issue by zhangjmruc** [ClickHouse/ClickHouse#33693]
**Describe what's wrong**
For a table with ttl, skip index and default value 'b' on a column named s, when I insert some rows, all the values in column s in a data part expire,  then ttl merge deletes this column from the data part in filesystem. Then a select on the table with an equal condition on the column s, "s='b'", where the value 'b' is the default value for column s, the skip index causes wrong result.

Since it is working as designed for column TTL, " When the values in the column expire, ClickHouse replaces them with the default values for the column data type. If all the column values in the data part expire, ClickHouse deletes this column from the data part in a filesystem.". For the problem part, there is no data column, should we return result for the query with condition on default value or not?

**Does it reproduce on recent release?**

CH 21.12.3.32 (official build).

**How to reproduce**

create table ttl (i Int, a Int, s String default 'b' ttl a % 2 = 0 ? today() - 10 : toDate('2100-01-01'),
    index ind_s (s) type set(1) granularity 1) engine = MergeTree order by i settings min_bytes_for_wide_part=0;

insert into ttl values(5,4,'a'),(6,6,'a');
insert into ttl values(1,1,'a'),(2,2,'a');

-- make sure the table is using wide part
select name, part_type from system.parts where table='ttl';

┌─name──────┬─part_type─┐
│ all_1_1_0 │ Wide      │
│ all_1_1_1 │ Wide      │ <<< TTL merge happens on the first part
│ all_2_2_0 │ Wide      │
└───────────┴───────────┘

-- List all the data in ttl
select * from ttl;

┌─i─┬─a─┬─s─┐
│ 1 │ 1 │ a │
│ 2 │ 2 │ a │
└───┴───┴───┘
┌─i─┬─a─┬─s─┐
│ 5 │ 4 │ b │
│ 6 │ 6 │ b │
└───┴───┴───┘

4 rows in set. Elapsed: 0.001 sec.

**-- For the select on s, it should return 2 rows.**
select * from ttl where s='b';

SELECT *
FROM ttl
WHERE s = 'b'

Query id: 0f8ab129-5aad-4f67-a6ee-6fdacdeff515

Ok.

**0 rows in set**. Elapsed: 0.001 sec.

**Expected behavior**
-- Should return 2 rows.
┌─i─┬─a─┬─s─┐
│ 5 │ 4 │ b │
│ 6 │ 6 │ b │
└───┴───┴───┘

**Additional context**
In the data directory, the part after ttl merge doesn't have files for column s, but only the skp index files. all the granuales are dropped by the skip index.

[root@node231 all_1_1_1]# ll
total 44
-rw-r----- 1 clickhouse clickhouse  34 Jan 17 10:56 a.bin
-rw-r----- 1 clickhouse clickhouse  48 Jan 17 10:56 a.mrk2
-rw-r----- 1 clickhouse clickhouse 292 Jan 17 10:56 checksums.txt
-rw-r----- 1 clickhouse clickhouse  57 Jan 17 10:56 columns.txt
-rw-r----- 1 clickhouse clickhouse   1 Jan 17 10:56 count.txt
-rw-r----- 1 clickhouse clickhouse  10 Jan 17 10:56 default_compression_codec.txt
-rw-r----- 1 clickhouse clickhouse  34 Jan 17 10:56 i.bin
-rw-r----- 1 clickhouse clickhouse  48 Jan 17 10:56 i.mrk2
-rw-r----- 1 clickhouse clickhouse   8 Jan 17 10:56 primary.idx
-rw-r----- 1 clickhouse clickhouse  36 Jan 17 10:56 skp_idx_ind_s.idx
-rw-r----- 1 clickhouse clickhouse  24 Jan 17 10:56 skp_idx_ind_s.mrk2

-- trace log
[node231] 2022.01.17 11:13:41.599952 [ 20500 ] {a99a151c-bc6d-491f-8cdb-b1ff3e88133a} <Debug> executeQuery: (from [::1]:40378) select * from ttl where s='b'
[node231] 2022.01.17 11:13:41.600140 [ 20500 ] {a99a151c-bc6d-491f-8cdb-b1ff3e88133a} <Debug> InterpreterSelectQuery: MergeTreeWhereOptimizer: condition "s = 'b'" moved to PREWHERE
[node231] 2022.01.17 11:13:41.600250 [ 20500 ] {a99a151c-bc6d-491f-8cdb-b1ff3e88133a} <Trace> ContextAccess (default): Access granted: SELECT(i, a, s) ON default.ttl
[node231] 2022.01.17 11:13:41.600288 [ 20500 ] {a99a151c-bc6d-491f-8cdb-b1ff3e88133a} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
[node231] 2022.01.17 11:13:41.600381 [ 20500 ] {a99a151c-bc6d-491f-8cdb-b1ff3e88133a} <Debug> default.ttl (e79c1975-0e30-46ff-a79c-19750e30a6ff) (SelectExecutor): Key condition: unknown
[node231] 2022.01.17 11:13:41.600553 [ 20500 ] {a99a151c-bc6d-491f-8cdb-b1ff3e88133a} <Debug> default.ttl (e79c1975-0e30-46ff-a79c-19750e30a6ff) (SelectExecutor): I**ndex `ind_s` has dropped 2/2 granules.**
[node231] 2022.01.17 11:13:41.600586 [ 20500 ] {a99a151c-bc6d-491f-8cdb-b1ff3e88133a} <Debug> default.ttl (e79c1975-0e30-46ff-a79c-19750e30a6ff) (SelectExecutor): Selected 2/2 parts by partition key, 0 parts by primary key, 2/2 marks by primary key, 0 marks to read from 0 ranges
[node231] 2022.01.17 11:13:41.601234 [ 20500 ] {a99a151c-bc6d-491f-8cdb-b1ff3e88133a} <Debug> MemoryTracker: Peak memory usage (for query): 0.00 B.

**Comment by alexey-milovidov** [comment]
@CurtizJ Please take a look.

**Comment by Algunenano** [comment]
The repro was incorrect as it wasn't inserting any column with `s='b'`. All of them are inserted with `s='a'`.

If I insert them to match the first select it works:
```
create table ttl (i Int, a Int, s String default 'b' ttl a % 2 = 0 ? today() - 10 : toDate('2100-01-01'), index ind_s (s) type set(1) granularity 1) engine = MergeTree order by i settings min_bytes_for_wide_part=0;

insert into ttl values(5,4,'b'),(6,6,'b');
insert into ttl values(1,1,'a'),(2,2,'a');

select name, part_type from system.parts where table='ttl';

select * from ttl;
select * from ttl where s='b';
```

Tested 21.12, 22.8 and master.
