### ISSUE TITLE
clickhouse Distributed ENGINE ALTER corresponding local tables？

### ISSUE THREAD

**Issue by 2416210017** [ClickHouse/ClickHouse#33699]
hello，I'd like to ask if CK can support modifying the distributed engine to modify the corresponding local table?

I looked at the official website and couldn't find it.
![Snipaste_2022-01-17_17-52-43](https://user-images.githubusercontent.com/52597892/149747431-8f6207f0-36ab-492d-87d6-905cc92f9b85.png)

**Comment by nvartolomei** [comment]
There is no support for this. Distributed tables are independent from the tables it points to.

**Comment by 2416210017** [comment]
> 对此没有任何支持。分布式表独立于它指向的表。

okay, thank you.
