### ISSUE TITLE
formatDatetime support for DateTime64 and fractions formatting

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#33704]

**Comment by ryanoliverdev** [comment]
Hi I'd like to pick up this issue, but is there anymore information on what's needing to be done

**Comment by den-crane** [comment]
There is https://clickhouse.com/docs/en/sql-reference/functions/date-time-functions/#formatdatetime

you can do this
```
select formatDateTime( now64(5), '%Y/%m/%d %H:%M:%S');
┌─formatDateTime(now64(5), '%Y/%m/%d %H:%M:%S')─┐
│ 2022/01/21 17:56:16                           │
└───────────────────────────────────────────────┘
```
but it's impossible to format fractions of seconds (milliseconds / nanoseconds)

like this
```
select now64(5)
┌──────────────────now64(5)─┐
│ 2022-01-21 17:57:30.79872 │
└───────────────────────────┘
```

So need to implement '%f' 

```
select formatDateTime( now64(5), '%Y/%m/%d %H:%M:%S.%f');

┌─formatDateTime(now64(5), '%Y/%m/%d %H:%M:%S')─┐
│ 2022/01/21 17:56:16.32412                     │
└───────────────────────────────────────────────┘


select formatDateTime( now64(5), '%f');
┌─formatDateTime(now64(5), '%f')─┐
│ 32412                          │
└────────────────────────────────┘
```

**Comment by ryanoliverdev** [comment]
Ok, I see what you're saying. Ya I'd like to pick this up

**Comment by ryanoliverdev** [comment]
@den-crane Hi, so I made the necessary changes and I was wondering how I could test the functionality of just the formatDateTime function to make sure my changes worked. I looked at the documentation, but am still kind of unsure how to get a test environment setup. Thanks

**Comment by den-crane** [comment]
https://clickhouse.com/docs/en/development/tests/#functional-test-locally

And You can create a draft PR and ask to run CI

**Comment by AVZhuiko** [comment]
Please, can you increase priority for this task?
Now I use this workaroud, but I don't know how it affects performance:
`formatDateTime(occurred, '%FT%T', 'UTC') || '.' || toString(toUnixTimestamp64Micro(occurred)) % 1e6) || 'Z'`

**Comment by ucasfl** [comment]
Fixed in https://github.com/ClickHouse/ClickHouse/pull/44060.

**Comment by kardymonds** [comment]
Not working with negative DateTime64 value:
`select formatDateTime(toDateTime64('1969-12-31 00:00:00.001',3, 'UTC'), '%F %T.%f');`
Result:
`1969-12-31 00:00:01.999`

Need to add code like in `inline void writeDateTimeText(DateTime64 datetime64,...`
