### ISSUE TITLE
Creating hardlinks with clickhouse-copier

### ISSUE THREAD

**Issue by melvynator** [ClickHouse/ClickHouse#33702]
* ClickHouse version: **21.11.5.33**

* Queries to run that lead to slow performance: 

When trying to load data into ClickHouse using clickhouse-copier. The process goes unexpectedly slow. In particular we see slow ALTER TABLE ATTACH PARTITION queries in the query_log.

The query ALTER ATTACH PARTITION copies data from one table to another. There is no network interaction, so the data is copied only within the local disk. This is probably an IO bound task and the speed of this operation is fully based on the speed of the reads/writes operations.

I guess we could speed up this query by creating hardlinks without the actual copying.

**Comment by SaltTan** [comment]
ALTER ATTACH PARTITION creates hardlinks.
Is the target table replicated?

**Comment by den-crane** [comment]
Check system.merges probably alter is blocked by a merge

**Comment by Prudhvi0717** [comment]
from which version.. does copier cancels a merge when doing attach?
