### ISSUE TITLE
High values of minSessionTimeout on zookeeper may lead to problems with clickhouse restart

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#33714]
Ephemeral nodes will not be removed till `minSessionTimeout` will be reached, clickhouse during restart says: 

```
Couldn't start replication (table will be in readonly mode): Replica /tables/foo/bar/replicas/ch_4/is_active appears to be already active (host: ch-4, port: 9009, tcp_port: 9000, database: foo, table: bar scheme: http, ). If you're sure it's not, try again in a minute or remove znode /clickhouse/tables/foo/bar/replicas/ch_4/is_active manually. 

REPLICA_IS_ALREADY_ACTIVE
```

To fix it you need to reconfigure & restart zookeeper, after that you may need to drop old ephemeral nodes (you can list them using `echo dump | nc zookeeper-1 2181` ) 

P.S. OK just to close the issue (added the issue to make it indexed by search engines). Optionally we can add a note about minSessionTimeout in the exception message.

**Comment by alexey-milovidov** [comment]
It occurs if you terminate clickhouse-server by kill (without waiting for shutdown). Then ephemeral nodes are remaining in ZooKeeper until session timeout and it is impossible to determine if the server with replica is no longer connected.
