### ISSUE TITLE
After 439 exception clickhouse does not release threads

### ISSUE THREAD

**Issue by rad1k4l** [ClickHouse/ClickHouse#33712]
I have a table **A** which have ~ 200M rows and table **B** with same structure. Clickhouse uses in normal state up to 1k threads. I tried transfer data from A to B with query `INSERT INTO B SELECT * FROM A`. Thread count used by clickhouse incremented to 2k and query throws exception  `Code: 439. DB::Exception: Received from localhost:9000. DB::Exception: Cannot schedule a task: no free thread`. After that clickhouse should decrement thread count using for query execution. But thread count still is 2k 

**Does it reproduce on recent release?**

No , i am use clickhouse `21.12.3.32` version

**How to reproduce**

* Which ClickHouse server version to use
*  `21.12.3.32` version
* Queries to run that lead to unexpected result
`INSERT INTO B SELECT * FROM A`

**Expected behavior**

> 1k thread using by clickhouse process

**Comment by alexey-milovidov** [comment]
Check the list in https://github.com/ClickHouse/ClickHouse/issues/18794, especially
> too low value of /proc/sys/kernel/pid_max or /proc/sys/kernel/threads-max, should be more than 30000;

**Comment by rad1k4l** [comment]
@alexey-milovidov I know the solution to 439 Exception. But the problem is that every time after this exception the number of threads grows by 1k. 6 times executed a query 6k of unused threads by clickhouse takes over and does not release them in any way

**Comment by azat** [comment]
@rad1k4l Sorry for such a long delay, but any chance that you have a reproducer for this? Or/and maybe verbose logs? Also have you tried more recent version?

**Comment by wuchunfu** [comment]
@azat I'm using `ClickHouse` version `21.9.2.1` and I'm experiencing a similar problem, which seems to be caused by threads not being released, how can I fix it?

![image](https://user-images.githubusercontent.com/29206593/195491140-255a88c8-6c65-45e2-8a90-90331e1f638d.png)

**Comment by azat** [comment]
First of all we need to understand is it a real problem, i.e. does those threads are not used.
To figure this out:
- please post full server exception (not with java trace, but with C++, you can get it from `/var/log/clickhouse-server/clickhouse-server.err.log`)
- let's see how much threads does the process has (`Threads` from `/proc/$(pgrep clickhouse-serv)/stat`)
- dump all `*Threads*` metrics from prometheus exporter
- and let's also dump stacktraces for all threads

```sql
SELECT
    thread_id, thread_name, arrayStringConcat(arrayMap(x -> demangle(addressToSymbol(x)), trace), '\n') AS sym
FROM system.stack_trace
SETTINGS allow_introspection_functions=1
FORMAT Vertical
```

- and one more question, is it easy to reproduce?

**Comment by alexey-milovidov** [comment]
No info was provided.
