### ISSUE TITLE
Aggregate function sum(allTransCount) is found inside another aggregate function in query

### ISSUE THREAD

**Issue by MrWhiteL** [ClickHouse/ClickHouse#3371]
![image](https://user-images.githubusercontent.com/32286846/46902897-bb59b180-ceff-11e8-843a-8c51f3752482.png)

**Comment by alexey-milovidov** [comment]
This is how aliases work in ClickHouse, discussion: #9715

**Comment by viktor-klestov** [comment]
That was really confusing
