### ISSUE TITLE
Access Control setup could be simpler and safer

### ISSUE THREAD

**Issue by FedericoCeratto** [ClickHouse/ClickHouse#33713]
Configuring Access Control requires various steps:

1. Lock down the default user e.g. with a temporary random password
2. Give it access management right by setting  yandex > users > default > access_management to 1. [Adding a temporary override in /etc/clickhouse-server/users.d did not seem to work]
3. Restart Clickhouse
4. Run SQL to create an admin user with special grants
5. Run SQL to remove rights to the default user (e.g. prevent write operations)
6. Unlock the default user e.g. reset the password to empty
7. Reset access_management
8. Restart Clickhouse
9. Log in as admin and create users and roles as needed

A mistake might create risk to lock oneself out of the database or leave unwanted roles open for abuse. The first 8 steps could be automated to be safer.
E.g.
```
sudo clickhouse-client --create-admin
The "admin" user has been created with password "<random_password>". The "default" user is now read-only.
```

**Comment by alexey-milovidov** [comment]
@vitlibar Override in users.d should work.

@FedericoCeratto Why don't just use the user with access management as admin user?

**Comment by FedericoCeratto** [comment]
Having clear, unambiguous names like "admin" is good for security. A superuser called "default" might encourage misunderstanding.

**Comment by den-crane** [comment]
@FedericoCeratto  you are doing something wrong. **And no need to restart CH.**

### step 1.

```
cat /etc/clickhouse-server/users.d/access_management_default.xml
<?xml version="1.0"?>
<yandex>
    <users>
        <default>
           <password>secret</password>
            <access_management>1</access_management>
        </default>
    </users>
</yandex>

clickhouse-client -mn --password secret -q "create user admin identified by 'secret'; grant all on *.* to admin"
```

### step 2.

```
cat  /etc/clickhouse-server/users.d/z_remove_user_default.xml
<?xml version="1.0" ?>
<yandex>
    <users>
        <default remove="remove"></default>
    </users>
</yandex>

clickhouse-client -mn -u admin --password secret -q "show users"
admin
```
