### ISSUE TITLE
DateTime with Daylight Saving Time

### ISSUE THREAD

**Issue by malikas05** [ClickHouse/ClickHouse#33715]
DateTime stores the underlying value as the Unit timestamp which is in the UTC timezone. I am writing the data in the America/Toronto timezone and ClickHouse converts the values into the UTC timezone. How does it handle the hour when the Daylight Saving Time starts and ends? For example, imagine, I am writing the data for the following hour: November 7, 2021, 1:00:00 am; that means it would be saved in CH as November 7, 2021, 5:00:00 am(EDT+4). Then at 2:00:00 am, clocks were turned backward for 1 hour, and again the time became November 7, 2021, 1:00:00 am, so the client would pass that value when inserting the data. How would the conversion be handled in this case? Would it be converted to 6:00:00 am(EST+5) or again 5:00:00 am(EDT+4) leading to storing of the data for the same hour twice?

**Comment by den-crane** [comment]
It will be again  5:00:00 am.

Because on November 7, 23 hours in a day in America/Toronto and 23 hours in UTC.

**Comment by alexey-milovidov** [comment]
If you are importing data in text format (INSERT VALUES, CSV, TSV, JSONEachRow...), you can specify DateTime value in one of the following ways:

1. Simple text form: `2021-11-07 01:00:00`
2. Unix timestamp: `1234567890`
3. Full ISO-8601: `2021-11-07T01:00:00-1000` and other forms, if setting `date_time_input_format = 'best_effort'`

In case 1, the conversion is ambiguous as @den-crane has explained.
In cases 2 and 3, you have full control and you get unambiguous result.

**Comment by malikas05** [comment]
Thanks, @alexey-milovidov. I assume it also applies to JDBC driver?

**Comment by alexey-milovidov** [comment]
I'm not familiar with all the details about the JDBC driver... but there should be a way to unambiguously insert data.

**Comment by den-crane** [comment]
@malikas05 it depends how you do inserts by JDBC and JDBC driver version. 
there are many ways to do insert: Insert / Batched insert / extended API. In some cases a conversion happens in JVM before reaching CH.

**Comment by malikas05** [comment]
@den-crane, I am using **clickhouse-jdbc**(https://github.com/ClickHouse/clickhouse-jdbc), version 0.3.1 and I am writing the data with the batch insert. The date field is set through the usage of the PreparedStatement, i.e.,
`preparedStatement.setTimestamp(1, new Timestamp(new DateTime().toDate().getTime()));`. Currently, `serverTimeZone` in `ClickHouseConnectionImpl` is defined to `America/Toronto` because `SELECT timezone()` returns this timezone as well as the following configs have default values, i.e., not defined in the connection string:
```
use_server_time_zone
use_time_zone
```
If I set `use_server_time_zone` to `false` and `use_time_zone` to `UTC`, would that ensure that the second hour when that shift happens to November 7, 2021, 1:00:00 am get written as November 7, 2021, 6:00:00 am? Or since CH server timezone is set to `America/Toronto`, the client would send it as November 7, 2021, 6:00:00 am but then the server would think that it's in `America/Toronto` and convert to UTC, i.e., November 7, 2021, 11:00:00 am?

Sorry, if I am making too many assumptions here. Just want to understand how to correctly handle that scenario with DST. Probably, the only feasible options is to use either option 2 or 3 as mentioned by @alexey-milovidov?

**Comment by malikas05** [comment]
Or to eliminate my second concern which I mentioned in my previous message, would setting the timezone of the server itself to UTC help to circumvent the problem completely? I.e., the client-provided DateTime(in America/Toronto) is converted on the client-side to UTC and gets stored in CH as is.
