### ISSUE TITLE
RFC: Build community SIG to improve ClickHouse world.

### ISSUE THREAD

**Issue by cnmade** [ClickHouse/ClickHouse#33719]
## Abstract
For a strong OSS project, like K8s, it has a very well Special Interest Groups (SIGs), These SIGs focus on special area, For example, Document improve, platform support.

## Create Sigs to improve on special area

| Name | Label | Chairs | Contact | Meetings |
|------|-------|--------|---------|----------|
Document | docs | | | |
Release | release | | | | 
Platform support | platform | | | | 
SDK and Client | sdk-client | | | | 

## Orgnazation and join contribute

Each SIgs can have leader and board member, who can focus on these area improvement.

And make rules, check for contribute. make RFC for changes.

Anyone can join these Sigs if they have interest.

## Reference

* K8s sig list

https://github.com/kubernetes/community/edit/master/sig-list.md

**Comment by alexey-milovidov** [comment]
We want fast, easy and maybe chaotic development process.
See https://github.com/ClickHouse/ClickHouse/blob/master/CODE_OF_CONDUCT.md
