### ISSUE TITLE
SystemD unit file: support configuration reloading

### ISSUE THREAD

**Issue by FedericoCeratto** [ClickHouse/ClickHouse#33738]
Currently the [unit file](https://github.com/ClickHouse/ClickHouse/blob/master/debian/clickhouse-server.service) does not support live configuration reload.

The unit file could be made to run `SYSTEM RELOAD CONFIG` for reloading.

**Comment by den-crane** [comment]
`SYSTEM RELOAD CONFIG` is doing nothing in the most of the cases. CH reloads configs automatically and it watches for any file changes in config directory. 
Some settings are applicable only during CH start.
`SYSTEM RELOAD CONFIG` is implemented for debug purposes.
