### ISSUE TITLE
Allow replicate subset of columns through MaterializedPostgreSQL?

### ISSUE THREAD

**Issue by Olga-par** [ClickHouse/ClickHouse#33748]
Hello!

As part of the project, we use postgresql replication in clickhouse through the creation of MaterializedPostgreSQL.
There was a need not to replicate some columns of tables.
Is it possible to limit replicated columns in a table?

**Comment by kssenii** [comment]
Hello.
It is not possible right now to limit columns of tables to be replicated.
But it is possible to implement.
But I don't think I will find time for that any time soon.
I'll keep this feature in mind.
If you want - you can try to implement it too and send a PR :) I can tell what is takes to do to implement this.

**Comment by Olga-par** [comment]
Ok, thank you. We will wait this feature :)
