### ISSUE TITLE
How to config serveral files under the clickhouse-client directory to access different clickhouse-server ?

### ISSUE THREAD

**Issue by vleyong** [ClickHouse/ClickHouse#33740]
I edited the config.xml  for my local clickhouse-server,meanwhile I wanna access remote clickhouse-server,so I added a xml file under the /clickhouse-client,named remote.xml ,but when I excute the command" clickhouse-client  ./remote.xml" ,it accessed to the loaclhoust clikchouse-server,it seems like config.xml covered  remote.xml！
Should I config the remote information to config.xml too? Thanks

**Comment by den-crane** [comment]
see https://clickhouse.com/docs/en/interfaces/cli/#configuration_files

Client's config uses another tags, see /etc/clickhouse-client/config.xml

**Comment by vleyong** [comment]
I saw the default configuration in /etc/clickhouse-client/config.xml,there was nothing else but only a root tags:<config>.
May I add some other tags for serveral remote server?
```
<config>
  
</config>
```

**Comment by genzgd** [comment]
Yes, any command line parameter in the [documentation](https://clickhouse.com/docs/en/interfaces/cli/) can be included in the configuration file.  Here's a configuration file you can use to access the data referenced in this [ClickHouse demo article](https://ghe.clickhouse.tech/#download-the-dataset):

`config.xml`

```
<config>
  <host>gh-api.clickhouse.com</host>
  <user>play</user>
  <password></password>
  <secure>true</secure>
  <port>9440</port>
</config>

```

**Comment by vleyong** [comment]
I needs access several clickhouse-server ,so how to config it?
`<config>
  <host>aaaa</host>
</config>
<config>
  <host>bbb</host>
</config>
`

**Comment by den-crane** [comment]
@vleyong make several configs and use them with ` -C [ --config-file ] arg                                             config-file path` argument
```
clickhouse-client -C server1.xml
clickhouse-client -C server2.xml
```

It's strange that ` /etc/clickhouse-client/config.xml` is empty. It should like this https://github.com/ClickHouse/ClickHouse/blob/master/programs/client/clickhouse-client.xml

**Comment by vleyong** [comment]
It's my fault. I installed an old version before.Thanks a  lot.
