### ISSUE TITLE
Integer value treated as seconds instead of milliseconds on INSERT to DateTime64(3) from Parquet

### ISSUE THREAD

**Issue by mickm** [ClickHouse/ClickHouse#33758]
**Describe the unexpected behaviour**

When inserting a 64-bit integer from a Parquet file into a DateTime64(3) millisecond precision column the integer value seems to be treated as seconds-since-epoch (instead of milliseconds).

**How to reproduce**
* Which ClickHouse server version to use: `21.13.1 revision 54455 on macOS Monterey`
* Which interface to use, if matters: `./clickhouse client`
* Non-default settings, if any: none
* `CREATE TABLE` statements for all tables involved: `create table foo (timestamp DateTime64(3)) engine = TinyLog();`
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

```
$ cat timestamp.json
{"timestamp": 1234}
$ cat timestamp.csv
1234
$ parquet-tools cat --json timestamp_uint64.parquet
{"timestamp":1234}
$ parquet-tools cat --json timestamp_int64.parquet
{"timestamp":1234}
```

```
CREATE TABLE foo (timestamp DateTime64(3)) engine = TinyLog();
INSERT INTO foo (timestamp) VALUES (1234);
INSERT INTO foo (timestamp) FROM INFILE 'timestamp.json' FORMAT JSONEachRow;
INSERT INTO foo (timestamp) FROM INFILE 'timestamp.csv' FORMAT CSV;
INSERT INTO foo (timestamp) FROM INFILE 'timestamp_uint64.parquet' FORMAT Parquet;
INSERT INTO foo (timestamp) FROM INFILE 'timestamp_int64.parquet' FORMAT Parquet;
SELECT * FROM foo;
1970-01-01 00:00:01.234 -- values
1970-01-01 00:00:01.234 -- jsoneachrow
1970-01-01 00:00:01.234 -- csv
1970-01-01 00:20:34.000 -- uint64 parquet
1970-01-01 00:20:34.000 -- int64 parquet
```

**Expected behavior**
I expected Parquet integer value to be interpreted as having same precision as destination DateTime64 column. i.e. when destination column is DateTime64(3) the value is treated as milliseconds. This would make it be consistent with CSV, Values and JSONEachRow behavior.

**Error message and/or stacktrace**
n/a

**Additional context**

Note that the value is also being clamped if is sufficiently large. e.g. If I do the same test as above with 1111111111234 I expect it would convert to 2005-03-18 01:58:31.234 (millis) or 2283-11-11 23:20:34.000 (seconds) but 2282-12-31 00:00:00.000 is what gets inserted. Perhaps due to the clamping here https://github.com/ClickHouse/ClickHouse/blob/f7e315bb0a588b4e31fc89b153c878a1c1db6603/src/Functions/FunctionsConversion.h#L564 (i.e. because 1111111111234 > 9877248000)

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/30002

**Comment by den-crane** [comment]
You can define it as UInt64 in engine=Parquet and convert during select using fromUnixTimestamp64Milli

https://clickhouse.com/docs/en/sql-reference/functions/type-conversion-functions/#fromunixtimestamp64milli
