### ISSUE TITLE
Allow to pass UUID in MessagePack

### ISSUE THREAD

**Issue by cyanide-burnout** [ClickHouse/ClickHouse#33756]
It is very efficient to use MessagePack as input data format to pass strict data to ClickHouse and UUID field type to store it. Unfortunately at this moment ClickHouse doesn't handle UUIDs presented in MessagePack and we have to store UUIDs as a fixed strings.
I want to suggest to add parsing UUIDs to MessagePack input parser in two forms:
- as a MessagePack's string of 36 chracters
- as a MessagePack's 16-bytes binary (https://github.com/msgpack/msgpack/blob/master/spec.md#bin-format-family)

**Comment by alexey-milovidov** [comment]
@Avogar I heard you like MsgPack :)

**Comment by cyanide-burnout** [comment]
Also it seems there is an EXT type for UUIDs. I‘ve found that in few sources, ExtType = 2. One of sources - https://github.com/tarantool/doc/issues/1227
