### ISSUE TITLE
Tuple to columns

### ISSUE THREAD

**Issue by BeyondNothing** [ClickHouse/ClickHouse#33764]
通过多重表连接后, select 后的字段会以 tuple 的形式默认展示, 怎么才能转换为真实的多个列呢?  untuple 函数不可用了, 使用下标后, 也会再次以tuple的形式展示

**Comment by sulayliu** [comment]
你好，能把你的SQL语句发出来吗？运行结果截图一下，谢谢

**Comment by BeyondNothing** [comment]
![image](https://user-images.githubusercontent.com/61631094/150276643-d61c5d97-cfef-4b6e-9d3d-198965ba0594.png)
纠正一下, 别名是无效...

**Comment by sulayliu** [comment]
![image](https://user-images.githubusercontent.com/65028492/150417502-a75b5bbb-5963-4823-a4a9-14108275922a.png)
