### ISSUE TITLE
MaterializedMySQL method is imported into clickhouse, the query efficiency is very low, count() 100 million data takes 40s+

### ISSUE THREAD

**Issue by owpqwe** [ClickHouse/ClickHouse#33762]
MaterializedMySQL method is imported into clickhouse, the query efficiency is very low, count() 100 million data takes 40s+

**Comment by melvynator** [comment]
Thanks for creating this issue. 

MaterializedMySQL is in experimental state. 

When the query is executed we append the FINAL modifier at the end of the query unless the `_version` is being used. 

When FINAL is specified, ClickHouse fully merges the data before returning the result and thus performs all data transformations that happen during merges.

You can find more information about FINAL [here](https://clickhouse.com/docs/en/sql-reference/statements/select/from/#select-from-final).

**Comment by owpqwe** [comment]
Thank you for your answer, but how do I determine the version(`_version`) number of the data
