### ISSUE TITLE
clickhouse server can not start up when set comment for query_log

### ISSUE THREAD

**Issue by xuyatian** [ClickHouse/ClickHouse#33768]
**Describe the unexpected behaviour**
clickhouse server(22.1.1.2542) can not start up when set comment for query_log
**How to reproduce**
add comment for query_log in config.xml
```
<query_log>
<database>system</database>
<table>query_log</table>
             <engine>ENGINE = MergeTree PARTITION BY (event_date)    
                          ORDER BY (event_time) 
                          TTL event_date + INTERVAL 14 DAY DELETE
                          SETTINGS ttl_only_drop_parts=1                              
                          COMMENT 'xxx'
             </engine>
</query_log>
```
restart clickhouse-server:
2022.01.18 23:07:04.861218 [ 3415373 ] {} <Error> Application: Caught exception while loading metadata: Code: 62. DB::Exception: Syntax error (Storage to create table for query_log): failed at position 259 ('COMMENT') (line 5, col 31): COMMENT 'xxx'
             . Expected end of query. (SYNTAX_ERROR), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa82bc3a in /usr/bin/clickhouse
1. DB::parseQueryAndMovePosition(DB::IParser&, char const*&, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, unsigned long, unsigned long) @ 0x14d6169f in /usr/bin/clickhouse
2. DB::SystemLogs::SystemLogs(std::__1::shared_ptr<DB::Context const>, Poco::Util::AbstractConfiguration const&) @ 0x13b996bb in /usr/bin/clickhouse
3. DB::Context::initializeSystemLogs() @ 0x134ac6af in /usr/bin/clickhouse
4. DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0xa8b4b9d in /usr/bin/clickhouse
5. Poco::Util::Application::run() @ 0x17471aa6 in /usr/bin/clickhouse
6. DB::Server::run() @ 0xa8a71d1 in /usr/bin/clickhouse
7. mainEntryClickHouseServer(int, char**) @ 0xa8a4787 in /usr/bin/clickhouse
8. main @ 0xa825fea in /usr/bin/clickhouse
9. __libc_start_main @ 0x7f3e9d62f0b3 in ?
10. _start @ 0xa6acfae in /usr/bin/clickhouse
 (version 22.1.1.2542)

**Expected behavior**
Clickhouse server should be up when set comment for query_log. 
21.8 is ok.

**Comment by xuyatian** [comment]
seems the issue is introduced since 21.11

**Comment by xuyatian** [comment]
Hello @Enmk , 
         I see the COMMENT is removed from ASTStorage in https://github.com/ClickHouse/ClickHouse/commit/67ff0f5dba5b95ec67c6e79f721fd5904ebb4115 ,  Is that means we don't support COMMENT in system.query_log any more?

Thanks,
Yatian

**Comment by Enmk** [comment]
> Hello @Enmk , I see the COMMENT is removed from ASTStorage in [67ff0f5](https://github.com/ClickHouse/ClickHouse/commit/67ff0f5dba5b95ec67c6e79f721fd5904ebb4115) , Is that means we don't support COMMENT in system.query_log any more?
> 
> Thanks, Yatian

Hi @xuyatian! Comments in system tables should be properly supported, it is my bad that I have unintentionally broken this feature. 
Would it be OK with you to move comment clause to a separate `comment` tag? Something like this:
```
<query_log>
<database>system</database>
<table>query_log</table>
             <engine>ENGINE = MergeTree PARTITION BY (event_date)    
                          ORDER BY (event_time) 
                          TTL event_date + INTERVAL 14 DAY DELETE
                          SETTINGS ttl_only_drop_parts=1                              
             </engine>
             <comment>Some comment text<comment>
</query_log>
```

**Comment by xuyatian** [comment]
Thanks @Enmk ! It 's OK with me to move comment clause to a sperate comment tag.

**Comment by kitaisreal** [comment]
@xuyatian seems like we need to revert refactoring that was before, without introducing comment section. `comment` must be part of `engine`.
Refactoring purpose was for Dictionaries to support `COMMENT`, if we move `comment` part on ASTLevel from `ASTStorage` to `ASTCreateQuery`. It is okay to duplicate `comment` in `ASTStorage` and `ASTDictionary`, that way previous implementation will work.

CC: @alexey-milovidov, @Enmk

**Comment by xuyatian** [comment]
@kitaisreal That's great!

**Comment by Enmk** [comment]
IMO, comment doesn't logically belong to `ASTStorage`,  this was just a mere coincidence. And having comments in both `ASTStorage` and `ASTCreateQuery` would be even worse, especially they can be used together, that would cause too much confusion.

It looks like users would be happy with having COMMENT as a separate XML-node in config. 

And maybe we could figure something out to support current layout of both ENGINE and COMMENT clause in a single XML-node if absolutely necessary. That way the only a small and pretty isolated part of the system gets a bit messy, not something as important as AST.

**Comment by kitaisreal** [comment]
@Enmk I am not sure, what if client want to add comment for materialized view table engine, that way adding comment on `ASTCreateQuery` seems like an issue.
