### ISSUE TITLE
ALTER TABLE bp_opc_db.op_order_local CLEAR PROJECTION p_argMax_all

### ISSUE THREAD

**Issue by xie132339** [ClickHouse/ClickHouse#33761]
Use the above statement
The source files in the following directory are not cleared
/var/lib/clickhouse/store/a3e
![image](https://user-images.githubusercontent.com/18162776/150058204-f4952047-a5f3-4a8b-a609-a63a1a4b3553.png)

**Comment by xie132339** [comment]
Special disk usage

**Comment by amosbird** [comment]
Please provide details. What's the version of ClickHouse? How did it end up with unexpected projection parts. Anyway, it's likely to be fixed by https://github.com/ClickHouse/ClickHouse/pull/33679 .

**Comment by xie132339** [comment]
ClickHouse server version 21.12.3.32 (official build).

**Comment by amosbird** [comment]
It should be fixed now. Please re-open the ticket if this isn't the case
