### ISSUE TITLE
can't use Point on cluster 

### ISSUE THREAD

**Issue by congbaoyangrou** [ClickHouse/ClickHouse#33773]
**Describe the unexpected behavior**
I set the setting allow_experimental_geo_types to the default user, but can't create a table with column type Point.
 error: Code: 44. DB::Exception: Cannot create table with column \'p\' which type is \'Point\' because experimental geo types are not allowed. Set setting allow_experimental_geo_types = 1 in order to allow it. (ILLEGAL_COLUMN) (version 21.10.2.15 (official build))

**How to reproduce**
* Which ClickHouse server version to use
  21.10.2.15

* Non-default settings, if any
  cluster settings:

 ```
"chop-generated-remote_servers.xml": "<yandex>
		    <remote_servers>
		        <!-- User-specified clusters -->
		        <datalake>
		            <shard>
		                <internal_replication>true</internal_replication>
		                <replica>
		                    <host>r1</host>
		                    <port>9000</port>
		                </replica>
		                <replica>
		                    <host>r2</host>
		                    <port>9000</port>
		                </replica>
		            </shard>
		        </datalake>
		        <!-- Autogenerated clusters -->
		        <all-replicated>
		            <shard>
		                <internal_replication>true</internal_replication>
		                <replica>
		                    <host>r1</host>
		                    <port>9000</port>
		                </replica>
		                <replica>
		                    <host>r2</host>
		                    <port>9000</port>
		                </replica>
		            </shard>
		        </all-replicated>
		        <all-sharded>
		            <shard>
		                <internal_replication>false</internal_replication>
		                <replica>
		                    <host>r1</host>
		                    <port>9000</port>
		                </replica>
		            </shard>
		            <shard>
		                <internal_replication>false</internal_replication>
		                <replica>
		                    <host>r2</host>
		                    <port>9000</port>
		                </replica>
		            </shard>
		        </all-sharded>
		    </remote_servers>
		</yandex>
		"
```
user settings    

```
"02-clickhouse-default-profile.xml": "<yandex>
		  <profiles>
		    <default>
		      <log_queries>1</log_queries>
		      <connect_timeout_with_failover_ms>1000</connect_timeout_with_failover_ms>
		      <distributed_aggregation_memory_efficient>1</distributed_aggregation_memory_efficient>
		      <parallel_view_processing>1</parallel_view_processing>
		      <allow_experimental_geo_types>1</allow_experimental_geo_types>
		    </default>
		  </profiles>
		</yandex>
		",
	"chop-generated-users.xml": "<yandex>
		    <users>
		        <default>
		            <networks>
		                <ip>::1</ip>
		                <ip>127.0.0.1</ip>
		            </networks>
		            <profile>default</profile>
		            <quota>default</quota>
		        </default>
		    </users>
		</yandex>
		"
}
```

* `CREATE TABLE` statements for all tables involved
 
```
CREATE TABLE testgeo.p2 ON CLUSTER '{cluster}'
(
    `p` Point
)
ENGINE = Memory
```

**Expected behavior**
the table p2 should be created successfully on both nodes.
**Error message and/or stacktrace**
none of the tables was created. The same error on both nodes:  
Code: 44. DB::Exception: Received from node-1:9000. DB::Exception: There was an error on [r2:9000]: Code: 44. DB::Exception: Cannot create table with column 'p' which type is 'Point' because experimental geo types are not allowed. Set setting allow_experimental_geo_types = 1 in order to allow it. (ILLEGAL_COLUMN) (version 21.10.2.15 (official build)).

**Additional context**
According to [this page](https://clickhouse.com/docs/en/operations/access-rights/#access-control-properties) :

> The default user account is used in any cases when the username is not defined, for example, at login from client or in distributed queries. In distributed query processing a default user account is used, if the configuration of the server or cluster does not specify the user and password properties.  

 I thought the create table with Point statement should work as we set allow_experimental_geo_types = 1 to default user.

**Comment by tavplubix** [comment]
See #32861
