### ISSUE TITLE
ROW POLICY triggering access issue

### ISSUE THREAD

**Issue by melvynator** [ClickHouse/ClickHouse#33775]
**Describe the issue**

We should clarify the behavior of

`CREATE ROW POLICY [policy_name] ON [db.table] FOR SELECT`

If any ROW POLICY is created on a table, all access to that table for other users and roles must be explicitly granted to that table by another matching ROW POLICY.  So in the case of the access rights on the node you are testing on, to continue to allow admin and other users to query system.tables, you would need an additional row policy such as

`CREATE ROW POLICY default_row_policy ON system.tables FOR SELECT USING 1 TO ALL EXCEPT test_user_3, analytics_user`

This behavior is by design but it is confusing to assign a restriction to one user or role and have it affect other users.

**How to reproduce**

```
CREATE DATABASE test;

CREATE TABLE test.test_db_3
(
    'Title' String,
    'id' UInt32
)
ENGINE = MergeTree()
ORDER BY (id)

CREATE ROLE test_role_1 SETTINGS log_profile_events = 1 READONLY, log_queries = 1 READONLY, log_query_settings = 1 READONLY, log_query_threads = 1 READONLY ;

CREATE USER test_user_3 IDENTIFIED WITH plaintext_password by 'password' DEFAULT ROLE test_role_1

CREATE ROW POLICY test_user_3_tables_filter ON system.tables FOR SELECT USING database = 'test_db_3' TO test_user_3 ;
```

* Which ClickHouse server version to use: 2021-12-15

* Non-default settings, if any:
<access_management>1</access_management>

**Expected behavior**
A ROW POLICY should only restrict the permission of the specified user or the documentation should be more clear about how to use it.

**Comment by Alex-Burmak** [comment]
Is it to possible to allow a db user to configure row level policies only to restricted list of tables? Or extend access control mechanism that it will be possible to do this?

Let's assume we have users "admin" and "teamlead". The user "admin" should have unrestricted permissions. The user "teamlead" should have restricted permissions - it should be allowed to configure row level policies for tables inside "database1", but "system" database should be restricted from any modifications.

How can I achieve this?

**Comment by vitlibar** [comment]
> Is it to possible to allow a db user to configure row level policies only to restricted list of tables? Or extend access control mechanism that it will be possible to do this?
> 
> Let's assume we have users "admin" and "teamlead". The user "admin" should have unrestricted permissions. The user "teamlead" should have restricted permissions - it should be allowed to configure row level policies for tables inside "database1", but "system" database should be restricted from any modifications.
> 
> How can I achieve this?

It can't be done with the current release of ClickHouse because the privileges `CREATE ROW POLICY`, `DROP ROW POLICY`, `ALTER ROW POLICY` are global (like `CREATE ROLE` they can be granted only for all databases and tables at once, not for a specific database or table). But actually there is no real reason why is that so. I think I'll add support for granting `CREATE ROW POLICY` at table or database level:

```
GRANT CREATE ROW POLICY ON mydb.mytable TO user1
GRANT CREATE ROW POLICY ON mydb.* TO user2
```

**Comment by vitlibar** [comment]
About the issue described in the first message. Here is an explanation why it works this way:

```
Row policies can be granted to roles, not only to users.

For example let's consider that for some table there are two row policies defined, named policy1 and policy2, and it's specified that policy1 is used with role role1, and policy2 is used with role role2:
CREATE ROW POLICY policy1 ON mydb.mytable USING filter1 FOR SELECT TO role1;
CREATE ROW POLICY policy2 ON mydb.mytable USING filter2 FOR SELECT TO role2;

Then there will be four categories of users:
1) users which have role1 granted;
2) users which have role2 granted;
3) users which have both role1 and role2 granted;
4) users which have none of role1 or role2 granted.

ClichHouse needs to determine which filters it should use depending on in which category the current user is.
For the first two categories it's pretty obvious:
1) filter1
2) filter2

If the current user has both the roles role1 and role2 granted, so we treat that as he can use any of the roles role1 and role2 separately, so there will be used a mixed filter:
3) filter1 OR filter2 (combination using the OR operator)

And if the current user doesn't have role1 or role2 granted, it means the current user doesn't have any roles allowing him to SELECT from our table, so the current user should not be able to see any rows, so the resulting filter will be
4) always FALSE
```

But I agree we have a usability issue here because having the necessity to add an extra row policy for all users except specified recently looks confusing. So in order to improve user experience probably we will add a new setting to either row policy or table's definition:

```
CREATE ROW POLICY ... SETTINGS apply_false_if_no_policies_applicable = 0
```

So if `apply_false_if_no_policies_applicable = 1` it will work as it works currently.

**Comment by vitlibar** [comment]
I've improved restrictive row policies to make them more usable in easy cases like when we want to restrict some users without any side affects on other users: https://github.com/ClickHouse/ClickHouse/pull/34596

**Comment by mafiore** [comment]
I get stuck with nearly the same problem. If I want to restrict a role with rls, I have to apply this "always true" rule to every other role. There's  a `bypass RLS` switch for roles in postgres which I found very helpful to solve this situation.

**Comment by vitlibar** [comment]
https://github.com/ClickHouse/ClickHouse/pull/36997
Implemented a new mode which can be enabled in the main configuration

```
<clickhouse>
    <access_control_improvements>
        <users_without_row_policies_can_read_rows>true</users_without_row_policies_can_read_rows>
    </access_control_improvements>
</clickhouse>
```

If `users_without_row_policies_can_read_rows` is set to false users without permissive row policies cannot see any rows.
If `users_without_row_policies_can_read_rows` is set to true users without permissive row policies see rows depending on the restrictive row policies or all rows if there is no restrictive row policies defined for those users.

For example, let's say we have three users `A`, `B`, `C`, `D` and three row policies defined for them:

```
CREATE ROW POLICY first ON mydb.mytable FOR SELECT USING id=1 TO A;
CREATE ROW POLICY second ON mydb.mytable FOR SELECT USING id=2 AS PERMISSIVE TO B;
CREATE ROW POLICY third ON mydb.mytable FOR SELECT USING id=3 AS RESTRICTIVE TO C;
```

then users will see the following rows depending on `users_without_row_policies_can_read_rows`:

|  | users_without_row_policies_can_read_rows = false | users_without_row_policies_can_read_rows = true |
| --- | --- | --- |
| A will see | rows with `id = 1` | rows with `id = 1` |
| B will see | rows with `id = 2` | rows with `id = 2` |
| C will see | no rows | rows with `id=3` |
| D will see | no rows | all rows |

**Comment by cangyin** [comment]
@vitlibar In the example setup, why user `C` sees no rows ? The docs says `RESTRICTIVE` row policies are combined with `AND` operator, but there is only one row policy applied to `C`. As I understand , `C` will see rows with `id = 3` irrespective of `users_without_row_policies_can_read_rows `

**Comment by vitlibar** [comment]
> In the example setup, why user C sees no rows ? The docs says RESTRICTIVE row policies are combined with AND operator, but there is only one row policy applied to C. As I understand , C will see rows with id = 3 irrespective of users_without_row_policies_can_read_rows 

If `users_without_row_policies_can_read_rows == false` then you need at least one permissive row policy to see any rows. If you have only restrictive row policies for you then you'll see no rows. If you have no row policies for you at all then you'll see no rows.

**Comment by cangyin** [comment]
Okay, understood. Thks!
