### ISSUE TITLE
query performance degrade when we use distributed table, how to optimize it?

### ISSUE THREAD

**Issue by surajmachamasi** [ClickHouse/ClickHouse#33778]
Query performance degrades when we use distributed table. 
 we have two shard and replica, our standalone sever with non distributed table out perform the cluster version with distributed table.

results:

      with distributed table:  1939 rows in set. Elapsed: 6.930 sec. Processed 969.82 million rows, 87.28 GB (139.95 million rows/s., 12.60 GB/s.)
      
      non Distributed table: 1939 rows in set. Elapsed: 4.039 sec. Processed 970.07 million rows, 87.31 GB (240.15 million rows/s., 21.61 GB/s.)

**Comment by gauravphoenix** [comment]
Does your query need to bring a lot of data from each shard? That happens with global joins or in queries sometimes if the right table is large. Essentially, try finding bottleneck..like is there sufficient network bandwidth between distributed table node and replicas

**Comment by surajmachamasi** [comment]
yes it query lots of data form each shards. Is there any server configuration to increase  the query processing in clickhosue?

**Comment by surajmachamasi** [comment]
whether choosing distributed table can cause performance degrade in the query?

**Comment by den-crane** [comment]
1. CH node gets the query -- this node became node initiator for distributed query.
2. The initiator sends queries to all shards
3. All shards execute the query
4. All shards reply to initiator with result
5. Initiator does final aggregation -- it can take a lot of time, bigger than step 3

You can disable step 5 

```
  --distributed_group_by_no_merge arg                                  If 1, Do not merge aggregation states from different servers for distributed queries (shards will process query up to the Complete stage, initiator just proxies the data from the shards). If 2
                                                                       the initiator will apply ORDER BY and LIMIT stages (it is not in case when shard process query up to the Complete stage)
```

Try to execute your query with `set distributed_group_by_no_merge=1`

**Comment by flyly0755** [comment]
@den-crane I also encounter this problem, with normal table xxx one 3 machines  and one distributed table xxxcluseter(base on table xxx),
basic query data scenario
```sql
select * from xxx where afield = 'avalue'
```
used 3.8 seconds on no-cluseter table xxx query machine1(used 3.8s query machine2 and 4.8s on machin3),
but used 11.5 seconds on cluster table xxxcluster(try with set distributed_group_by_no_merge=1, still need more than 11s).
```sql
select * from xxxcluster where afield = 'avalue'
```
expect used time more than 4.8s and like about 6-7 seconds.
but with 11.5, why? integrate data in master machine uses too much time?
