### ISSUE TITLE
How to remove a table from the list of available tables in MaterializedPostgreSQL?

### ISSUE THREAD

**Issue by Olga-par** [ClickHouse/ClickHouse#33800]
Hello.

I have some problem with removing tables from MaterializedPostgreSQL.
I ran command: 
       detach table <name_table> PERMANENTLY;
When I performed select * from <name_table> than it's ok.  The message appears: Table <name_table> doesn't exist. 
But when i view the list of tables in dbeaver in replicated database i see this table.
I need recreate  MaterializedPostgreSQL database without this table in order to not view this table in this database?

**Comment by kssenii** [comment]
> But when i view the list of tables in dbeaver in replicated database i see this table.

you mean SHOW TABLES query?

**Comment by Olga-par** [comment]
Yes

**Comment by Olga-par** [comment]
And when I want to return this table with command: attach table <name_atable> then appears message: Table  <name_atable> already exists.

**Comment by kssenii** [comment]
> you mean SHOW TABLES query?

I have the test which checks exatly what you told https://github.com/ClickHouse/ClickHouse/blob/master/tests/integration/test_postgresql_replica_database_engine_2/test.py#L136-L141

**Comment by kssenii** [comment]
It does not work because you added PERMANENTLY. In order to remove table from replication from Postgres and to remove it from ch you need to do just DETACH, no PERMANENTLY (it will anyway be permanently removed)

**Comment by Olga-par** [comment]
And when I want to return this table with command: attach table <name_atable> then appears message: Table <name_atable> already exists.  - this problem appears when i made simple detach <name_atable> without PERMANENTLY.
