### ISSUE TITLE
File/S3/HDFS as Database engine

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#33810]
**Use case**

Process a bunch of files in the most intuitive way.

**Describe the solution you'd like**

After #32455 is implemented, the format and structure of remote datasets is autodetected.
So, we can write `SELECT * FROM url('https://datasets.clickhouse.com/github_events_v2.native.xz')` without specifying data format or data structure.

Now let's look at the directory with files as a database.
It will allow to write something like:

```
SELECT * FROM "data.parquet"
```

The database engine should do lazy listing of the files.
The table structure should also be obtained lazily to avoid slow SHOW TABLES.

Database engine can take the following parameters:
- prefix for files;
- filter for filenames / file paths, optional (a question - should it be regexp or glob style);
- should it do recursive directory traversal or look at the immediate directory only (the latter by default);
- maybe a rule to glue some files together by pattern to represent them as a single table;
- maybe a regexp to transform names;
- default format if it is not autodetected, optional (skip unknown by default);

**Caveats**

`SELECT * FROM system.tables` without filters will become slower if these types of databases exist.

**Additional ideas**

We can introduce the notion of overlay databases (one database that can shadow tables from another database) and add File database to `clickhouse-local` to be available under default database.

**Comment by ramazanpolat** [comment]
@alexey-milovidov If this feature gets implemented do you think we'll be able to query S3 like this:

```sql
SELECT *
FROM "datasets.clickhouse.com'"

┌─Key───────────────────────────────────────────┬─LastModified─────────────┬─ETag───────────────────────────────────┬─Size────────┬─Owner────────────────────────────────────────────────────────────┬─StorageClass─┐
│ cell_towers.csv.xz                            │ 2022-02-07T02:00:24.000Z │ "f67958765b5e3cf3979347ec4b83f252-87"  │ 729138772   │ ad0f8138e7b6cb179e4dbef43a90d2304805936a92b9960987136016599a3592 │ STANDARD     │
│ disk-s3-test/anhoahjpkvdwymlmpzoxkhqtskmmdqck │ 2022-03-17T02:45:11.000Z │ "3517079828fb04b3942e636d9e92e91c"     │ 11          │ ad0f8138e7b6cb179e4dbef43a90d2304805936a92b9960987136016599a3592 │ STANDARD     │
│ disk-s3-test/apkqizfzczhsecyxxfjppamnupnccpqo │ 2022-02-09T05:52:48.000Z │ "54e96b6cca2d02ca4cde05de41408a2a"     │ 62808       │ ad0f8138e7b6cb179e4dbef43a90d2304805936a92b9960987136016599a3592 │ STANDARD     │
│ disk-s3-test/atnfsdxzgqngwfrpxwlaucxrgbuyymme │ 2022-03-17T01:59:48.000Z │ "68f0a2df225a27fef3be1fb085067be3"     │ 14926       │ ad0f8138e7b6cb179e4dbef43a90d2304805936a92b9960987136016599a3592 │ STANDARD     │
│ disk-s3-test/awbyetkiyqaxolidftzzxtchefvbxztr │ 2022-03-17T02:06:10.000Z │ "7456d8d924953c92bdf81827799034fe-8"   │ 147597936   │ ad0f8138e7b6cb179e4dbef43a90d2304805936a92b9960987136016599a3592 │ STANDARD     │
│ disk-s3-test/awjjgaqfxlrgaexafwrsdyvolcsfqzbv │ 2022-03-17T02:15:20.000Z │ "62fa530ba3e99aaab9426d653e89ed1b-566" │ 10098292833 │ ad0f8138e7b6cb179e4dbef43a90d2304805936a92b9960987136016599a3592 │ STANDARD     │
│ disk-s3-test/awxjnezqatcyvbizohcgdmuscpeuqrwh │ 2022-03-17T02:05:06.000Z │ "32f079641830b95d951673f1f8103990"     │ 150         │ ad0f8138e7b6cb179e4dbef43a90d2304805936a92b9960987136016599a3592 │ STANDARD     │
│ disk-s3-test/ayvuctobazdjlzoxmyyxhxmbzufnewfs │ 2022-03-17T02:03:33.000Z │ "e5c67fede4385a9547444e8a8e784b62-374" │ 6670229982  │ ad0f8138e7b6cb179e4dbef43a90d2304805936a92b9960987136016599a3592 │ STANDARD     │
│ disk-s3-test/baxskruadpfwqzkjkgddfpvunallvowv │ 2022-03-17T01:59:49.000Z │ "3c055689adde409f55dd2571778ed9ad-3"   │ 68211072    │ ad0f8138e7b6cb179e4dbef43a90d2304805936a92b9960987136016599a3592 │ STANDARD     │
│ disk-s3-test/bhlarfpzxpxfjjowqiqizbjqecbtthut │ 2022-03-17T02:19:10.000Z │ "8e00d713e032a6f18bddf23b26832cd1-13"  │ 236123088   │ ad0f8138e7b6cb179e4dbef43a90d2304805936a92b9960987136016599a3592 │ STANDARD     │
└───────────────────────────────────────────────┴──────────────────────────┴────────────────────────────────────────┴─────────────┴──────────────────────────────────────────────────────────────────┴──────────────┘

```

**Comment by alexey-milovidov** [comment]
@ramazanpolat 
No, it is a different feature.

This pull request does the following:
- data from a bunch of files is represented by tables inside a database;

What you describe is the following:
- metadata of a bunch of files is represented by a table.

**Comment by alexey-milovidov** [comment]
Scheduled for 23.7.

**Comment by alexey-milovidov** [comment]
Wow, it is implemented!
