### ISSUE TITLE
INSERT data cosistency problem in stress testing

### ISSUE THREAD

**Issue by SE2AI** [ClickHouse/ClickHouse#33817]
**A curious problem appeared in real business application:**

Testing clickhouse INSERT performance, got the result below:

![image](https://user-images.githubusercontent.com/21308534/150292617-e8b833de-74cf-4297-86d9-eaff44d326df.png)

relations among these columns:
1. E/F/G are COUNT queried with **ch-client**，given that G=F-E and G should be equal to D, but H=G-D shows the non-consistency, why is that, I can't figure out how it happened.
2. J/K/L are COUNT queried with **business web frontend**, the same as above, L=K-J, by checking column_N it shows that almost all the test results keep consistency well.

Obviously, the query results from ch-client are different from JDBC client.

I think the question may exists in either:
1. partition merge process
2. ch-client

anyone could help to explain the problem? 
many thanks

**Comment by den-crane** [comment]
no info / no repro
