### ISSUE TITLE
Can 'WITＨ ROLLUP' support a parameter?

### ISSUE THREAD

**Issue by AngelLittleChaochao** [ClickHouse/ClickHouse#33822]
WITH ROLLUP doc: https://clickhouse.com/docs/en/sql-reference/statements/select/group-by/ 
I like the "WITH ROLLUP" function, it reduces the SQL code. I'm wondering is there a way I can select the ROLLUP level to control how many 'group by' will be executed?

For example, in my situation, for "group by year, month, day WITH ROLLUP", I want two results: "group by year, month, day" and "group by year, month".  I don't want the result "group by year" or the totals since the calculation will cost more cpu and memory.

So I'm wondering if we can add a parameter for WITH ROLLUP? If no parameter is given, the action is as before.
For example:
group by year, month, day WITH ROLLUP 1 => group by year, month, day;  
group by year, month, day WITH ROLLUP 2 => group by year, month, day; group by year, month; 
group by year, month, day WITH ROLLUP 3 => group by year, month, day; group by year, month; group by year;

**Comment by den-crane** [comment]
GROUPING SETS ? https://www.sqltutorial.org/sql-grouping-sets/

**Comment by AngelLittleChaochao** [comment]
> GROUPING SETS ? https://www.sqltutorial.org/sql-grouping-sets/

Yes, exactly. Thanks for answering my question. I saw the PR has merged.

https://github.com/ClickHouse/ClickHouse/pull/26869
