### ISSUE TITLE
clickhouse server runs for a long time, the response of some SQL http requests is getting slower and slower

### ISSUE THREAD

**Issue by Nicholas-ehui** [ClickHouse/ClickHouse#33835]
Describe: clickhouse server runs for a long time, the response of some SQL http requests is getting slower and slower. Capture packets at the clickhouse server node and compare the clickhouse logs, It is found that some http requests (such as http request 1) are delayed by clickhouse, but the subsequent http requests are processed in advance (such as http request 2, and request 2 is processed before request 1). But restarting the clickhouse server returns to normal. 

The clickhouse version that has this problem is 20.8.7.15, and only one cluster has this problem so far.

Expected behavior: Check the poco library code: void HTTPServerConnection::run(), HTTPServer should be accept http requests sequentially, and there is no delay in SQL http responses.

Does this commit: https://github.com/ClickHouse-Extras/poco/commit/deb92a1d65764536036cbbc7db758d3db4d43ba1 solve the problem? If not, how to fix it?

**Comment by den-crane** [comment]
20.8 is end of life. Upgrade to 22.1
