### ISSUE TITLE
dictionary table detached earlier, could not attach it now.

### ISSUE THREAD

**Issue by surajmachamasi** [ClickHouse/ClickHouse#33834]
i tried to drop the dictionary table and detached the table. and now i could not attach it. i have shard the  image of outputs.

![image (2)](https://user-images.githubusercontent.com/84307751/150354052-43fcde20-b7ba-4b09-b1ac-c48924551ffe.png)

**Comment by kitaisreal** [comment]
@surajmachamasi please provide simple reproducible test scenario.

**Comment by den-crane** [comment]
`select version()` 
As I remember this problem existed 2 years ago.

**Comment by surajmachamasi** [comment]
┌─version()─┐
│ 20.7.4.11 │
└───────────┘

**Comment by surajmachamasi** [comment]
First created the dictionary
    CREATE DICTIONARY localdb.advertiser_access_dim
    (
        `advertiser_id` UInt64,
        `admins` String,
        `executives` String
    )
    PRIMARY KEY advertiser_id
    
    SOURCE(MYSQL(HOST 'local' PORT 3307 USER 'prod' TABLE 'target_dim' PASSWORD 'localp' DB 'mydbs'))
    LIFETIME(MIN 300 MAX 360)
    LAYOUT(HASHED()) 
    
  and detached table 
    detach table  localdb.advertiser_access_dim

and later when we tried to attach it doesnot get attached nor we can delete dictionary or table.
    attach  table  localdb.advertiser_access_dim

**Comment by kitaisreal** [comment]
@surajmachamasi it is okay in current master https://github.com/ClickHouse/ClickHouse/pull/33870.

**Comment by den-crane** [comment]
20.7.4.11 is obsolete. Use 22.1
