### ISSUE TITLE
Code: 1001, type: pqxx::conversion_error

### ISSUE THREAD

**Issue by mirsos** [ClickHouse/ClickHouse#33843]
I try to connect my PostgreSQL database with clickHouse, but pqxx can't convert text field to String 

2022.01.20 17:10:18.815594 [ 15592 ] {832be4b4-9bec-43eb-a6cd-96f5eeb4e5d7} <Error> executeQuery: std::exception. Code: 1001, type: pqxx::conversion_error, e.what() = Could not convert string to i: 'ksiegowosc.infor.pl'. (version 22.1.2.2 (official build)) (from [::1]:46418) (in query: select * from test3;), Stack trace (when copying this message, always include the lines below):

0. std::logic_error::logic_error(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x1a39c66d in /usr/lib/debug/.build-id/d4/467b3558d29571.debug
1. pqxx::internal::integral_traits<int>::from_string(std::__1::basic_string_view<char, std::__1::char_traits<char> >) @ 0x1a114a67 in /usr/lib/debug/.build-id/d4/467b3558d29571.debug
2. DB::insertPostgreSQLValue(DB::IColumn&, std::__1::basic_string_view<char, std::__1::char_traits<char> >, DB::ExternalResultDescription::ValueType, std::__1::shared_ptr<DB::IDataType const>, std::__1::unordered_map<unsigned long, DB::PostgreSQLArrayInfo, std::__1::hash<unsigned long>, std::__1::equal_to<unsigned long>, std::__1::allocator<std::__1::pair<unsigned long const, DB::PostgreSQLArrayInfo> > >&, unsigned long) @ 0x13314270 in /usr/lib/debug/.build-id/d4/467b3558d29571.debug
3. DB::PostgreSQLSource<pqxx::transaction<(pqxx::isolation_level)0, (pqxx::write_policy)0> >::generate() @ 0xa8089dc in /usr/lib/debug/.build-id/d4/467b3558d29571.debug
4. DB::ISource::tryGenerate() @ 0x1483f655 in /usr/lib/debug/.build-id/d4/467b3558d29571.debug
5. DB::ISource::work() @ 0x1483f21a in /usr/lib/debug/.build-id/d4/467b3558d29571.debug
6. DB::SourceWithProgress::work() @ 0x14a8a802 in /usr/lib/debug/.build-id/d4/467b3558d29571.debug
7. DB::ExecutionThreadContext::executeTask() @ 0x1485ecc3 in /usr/lib/debug/.build-id/d4/467b3558d29571.debug
8. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x1485353e in /usr/lib/debug/.build-id/d4/467b3558d29571.debug
9. DB::PipelineExecutor::executeImpl(unsigned long) @ 0x14852389 in /usr/lib/debug/.build-id/d4/467b3558d29571.debug
10. DB::PipelineExecutor::execute(unsigned long) @ 0x14852098 in /usr/lib/debug/.build-id/d4/467b3558d29571.debug
11. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) @ 0x148627e7 in /usr/lib/debug/.build-id/d4/467b3558d29571.debug
12. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa86e077 in /usr/lib/debug/.build-id/d4/467b3558d29571.debug
13. void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) @ 0xa871a7d in /usr/lib/debug/.build-id/d4/467b3558d29571.debug
14. start_thread @ 0x7ede in /lib64/libpthread-2.32.so
15. __clone @ 0xfac5f in /lib64/libc-2.32.so

2022.01.20 17:10:18.815675 [ 15592 ] {832be4b4-9bec-43eb-a6cd-96f5eeb4e5d7} <Error> TCPHandler: Code: 1001. DB::Exception: pqxx::conversion_error: Could not convert string to i: 'ksiegowosc.infor.pl'. (STD_EXCEPTION), Stack trace (when copying this message, always include the lines below):

0. std::logic_error::logic_error(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x1a39c66d in /usr/lib/debug/.build-id/d4/467b3558d29571.debug
1. pqxx::internal::integral_traits<int>::from_string(std::__1::basic_string_view<char, std::__1::char_traits<char> >) @ 0x1a114a67 in /usr/lib/debug/.build-id/d4/467b3558d29571.debug
2. DB::insertPostgreSQLValue(DB::IColumn&, std::__1::basic_string_view<char, std::__1::char_traits<char> >, DB::ExternalResultDescription::ValueType, std::__1::shared_ptr<DB::IDataType const>, std::__1::unordered_map<unsigned long, DB::PostgreSQLArrayInfo, std::__1::hash<unsigned long>, std::__1::equal_to<unsigned long>, std::__1::allocator<std::__1::pair<unsigned long const, DB::PostgreSQLArrayInfo> > >&, unsigned long) @ 0x13314270 in /usr/lib/debug/.build-id/d4/467b3558d29571.debug
3. DB::PostgreSQLSource<pqxx::transaction<(pqxx::isolation_level)0, (pqxx::write_policy)0> >::generate() @ 0xa8089dc in /usr/lib/debug/.build-id/d4/467b3558d29571.debug
4. DB::ISource::tryGenerate() @ 0x1483f655 in /usr/lib/debug/.build-id/d4/467b3558d29571.debug
5. DB::ISource::work() @ 0x1483f21a in /usr/lib/debug/.build-id/d4/467b3558d29571.debug
6. DB::SourceWithProgress::work() @ 0x14a8a802 in /usr/lib/debug/.build-id/d4/467b3558d29571.debug
7. DB::ExecutionThreadContext::executeTask() @ 0x1485ecc3 in /usr/lib/debug/.build-id/d4/467b3558d29571.debug
8. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x1485353e in /usr/lib/debug/.build-id/d4/467b3558d29571.debug
9. DB::PipelineExecutor::executeImpl(unsigned long) @ 0x14852389 in /usr/lib/debug/.build-id/d4/467b3558d29571.debug
10. DB::PipelineExecutor::execute(unsigned long) @ 0x14852098 in /usr/lib/debug/.build-id/d4/467b3558d29571.debug
11. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) @ 0x148627e7 in /usr/lib/debug/.build-id/d4/467b3558d29571.debug
12. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa86e077 in /usr/lib/debug/.build-id/d4/467b3558d29571.debug
13. void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) @ 0xa871a7d in /usr/lib/debug/.build-id/d4/467b3558d29571.debug
14. start_thread @ 0x7ede in /lib64/libpthread-2.32.so
15. __clone @ 0xfac5f in /lib64/libc-2.32.so

**Comment by kssenii** [comment]
Please provide table definition in postgres and how to fill it to get such error.

**Comment by mirsos** [comment]
(
    int_id bigint NOT NULL DEFAULT nextval('sm_visit_int_id_seq'::regclass),
    version integer NOT NULL,
    created_on timestamp without time zone NOT NULL,
    uri text COLLATE pg_catalog."default",
    location text COLLATE pg_catalog."default",
    referrer text COLLATE pg_catalog."default",
    smid character varying(16) COLLATE pg_catalog."default",
    "time" timestamp without time zone,
    ip character varying(40) COLLATE pg_catalog."default",
    host character varying(16) COLLATE pg_catalog."default",
    processed boolean,
    referrer_host text COLLATE pg_catalog."default",
    client_time timestamp without time zone,
    original_location text COLLATE pg_catalog."default",
    uuid_id integer,
    referrer_host_id integer,
    original_location_id integer,
    id character varying(36) COLLATE pg_catalog."default",
    uuid character varying(255) COLLATE pg_catalog."default",
    conversation character varying(255) COLLATE pg_catalog."default",
    client character varying(255) COLLATE pg_catalog."default",
    client_addr inet,
    CONSTRAINT sm_visit_pkey PRIMARY KEY (int_id)
        USING INDEX TABLESPACE arch01
)`

`CREATE TABLE test.test2
(
    `int_id` Int64,
    `created_on` DateTime,
    `uri` String,
    `location` String,
    `referrer` String,
    `smid` String,
    `time` DateTime,
    `ip` String,
    `host` String,
    `processed` Boolean,
    `referrer_host` String,
    `client_time` DateTime,
    `original_location` Int32,
    `referrer_host_id` Int32,
    `original_location_id` Int32,
    `id` String,
    `conversation` String,
    `client` String
) 
ENGINE = PostgreSQL('XXXXXX:XXXX', 'xxxx', 'xxxxx', 'xxxx', 'xxxx', 'xxxx')`

**Comment by mirsos** [comment]
I found problem, thx for all

**Comment by sarang-pratham** [comment]
what did you do ? @mirsos

**Comment by mirsos** [comment]
If I remember well problem wasn't with CH. That was the reason why my comment haven't explanation. Sorry.
