### ISSUE TITLE
MaterializePostgreSQL databases didn't work

### ISSUE THREAD

**Issue by kokizzu** [ClickHouse/ClickHouse#33845]
> You have to provide the following information whenever possible.

trying the exact same process defined in [MaterializePostgreSQL](https://clickhouse.com/docs/en/engines/database-engines/materialized-postgresql/) documentation

> A clear and concise description of what works not as it is supposed to.

yes
ClickHouse server version 22.1.2.2 (official build).

**Enable crash reporting**

not crashing

**How to reproduce**

* Which ClickHouse server version to use: 22.1.2.2 
* Non-default settings: only adding 1 line  
```xml
<?xml version="1.0"?>
<clickhouse>
<profiles>
<default>
<allow_experimental_database_materialized_postgresql>1</allow_experimental_database_materialized_postgresql>
```

create table on amazon RDS postgresql, some table, some data, set `wal_level=logical` and `max_replication_slots=100` 

**Expected behavior**

> A clear and concise description of what you expected to happen.

behaves exactly the same as the example written in the documentation (there's table inside the newly created database).

> If applicable, add screenshots to help explain your problem.

```sqk
pop2104.localdomain :) CREATE DATABASE IF NOT EXISTS solo_prod
ENGINE = MaterializedPostgreSQL('solo-x-db-x.x.us-west-2.rds.amazonaws.com:5432', 'xxx', 'ro_user', 'asasfasf');

CREATE DATABASE IF NOT EXISTS solo_prod
ENGINE = MaterializedPostgreSQL('solo-x-db-x.x.us-west-2.rds.amazonaws.com:5432', 'xxx', 'ro_user', 'asasfasf')

Query id: 068213ea-8e99-493b-a078-3a121b1963b9

Ok.

0 rows in set. Elapsed: 0.002 sec. 

pop2104.localdomain :) use solo_prod;

USE solo_prod

Query id: c58f8b9d-211b-42eb-9ed1-4751070fbd1e

Ok.

0 rows in set. Elapsed: 0.000 sec. 

pop2104.localdomain :) show tables;

SHOW TABLES

Query id: 985c0dcc-3c4c-41b3-97b3-a612bffe8199

Ok.

0 rows in set. Elapsed: 0.001 sec. 
```

^ there's no table, unlike in the example on the documentation.

**Additional context**

it would be better if there's info on the progress of replication, or if there's an error on authetication or something else.

**Comment by kssenii** [comment]
Can you try non materialized database? It seems to me that it might also not work with your case.

**Comment by kokizzu** [comment]
ah yes, it didn't work '__') where can i see what might be the problem?

**Comment by kokizzu** [comment]
testing with non-materialized database, it stuck on `show tables`;

**Comment by kokizzu** [comment]
oh it shows after few seconds with non-materialized database
```
56 rows in set. Elapsed: 77.717 sec.
```

**Comment by kssenii** [comment]
Any error message? something in log?

**Comment by kssenii** [comment]
Also I assume it is related to amazon RDS postgresql, I slightly remember there already was some issue with amazon RDS reported a few months ago.

**Comment by kssenii** [comment]
Also please test single PostgreSQL table engine: `create table ... engine=PostgreSQL(...)`. Does select work?

**Comment by kokizzu** [comment]
no error on the log, ok wait lemme try single engine

**Comment by kokizzu** [comment]
ah after closing `clickhouse-client` then opening again, now i'm stuck on `show databases`;
it's safe right to drop all those database on clickhouse?

**Comment by kssenii** [comment]
Yes, dropping Postgres db in clickhouse is safe. It does not delete anything.

**Comment by kokizzu** [comment]
it's ok for create table engine=postgres, then select * from that table.

`102 rows in set. Elapsed: 2.353 sec.`

**Comment by kssenii** [comment]
then the problem is with fetching postgres table structure. Please check these queries: https://github.com/ClickHouse/ClickHouse/blob/master/src/Databases/PostgreSQL/fetchPostgreSQLTableStructure.cpp#L41-L43
and
https://github.com/ClickHouse/ClickHouse/blob/master/src/Databases/PostgreSQL/fetchPostgreSQLTableStructure.cpp#L256-L261

**Comment by kokizzu** [comment]
that query on 256-261 can ba executed using that user:
```

SELECT attname AS name, format_type(atttypid, atttypmod) AS type, 
           attnotnull AS not_null, attndims AS dims, atttypid as type_id, atttypmod as type_modifier 
           FROM pg_attribute 
           WHERE attrelid = (SELECT oid FROM pg_class WHERE relname = 'users' AND relnamespace = (SELECT oid FROM pg_namespace WHERE nspname = 'public')) 
           AND NOT attisdropped AND attnum > 0
```

**Comment by kokizzu** [comment]
but how to know the replication state/progress, or this is instaneous?

**Comment by kokizzu** [comment]
ah apparently this caused by the ro_user (read only) doesn't have sufficient permission to do replication, i use higher privieleged user and it works, but it crashed, i will make another issue for that.
