### ISSUE TITLE
ZooKeeperWatch is not normal

### ISSUE THREAD

**Issue by zhongyuankai** [ClickHouse/ClickHouse#33855]
(you don't have to strictly follow this form)

**Describe the unexpected behaviour**
I understand that only three zk nodes`mutations`, `log` and `leader_election-` will register listeners in `ReplicatedMergeTree`, so the corresponding number of `ZooKeeperWatch` should be the number of tables multiplied by three, why is the time difference so much?

version: 20.8.12.2

**Error message and/or stacktrace**
```
bigdata-clickhouse00.ys :) select metric,value from system.metrics where metric  like '%ZooKeeper%';

SELECT
    metric,
    value
FROM system.metrics
WHERE metric LIKE '%ZooKeeper%'

┌─metric───────────┬─value─┐
│ ZooKeeperSession │     1 │
│ ZooKeeperWatch   │ 38336 │
│ ZooKeeperRequest │    19 │
└──────────────────┴───────┘

3 rows in set. Elapsed: 0.002 sec.

bigdata-clickhouse00.ys :) select count(*) from system.tables where engine like 'Replicated%MergeTree';

SELECT count(*)
FROM system.tables
WHERE engine LIKE 'Replicated%MergeTree'

┌─count()─┐
│    1837 │
└─────────┘

1 rows in set. Elapsed: 0.032 sec. Processed 7.04 thousand rows, 152.53 KB (221.90 thousand rows/s., 4.81 MB/s.)
```

**Comment by den-crane** [comment]
20.8.12.2 is out of support. DDLWorker watch leak was fixed later.

**Comment by den-crane** [comment]
upgrade Clickhouse version 22.1

**Comment by zhongyuankai** [comment]
@den-crane Thank you for your answer, do you know it was fixed in that patch?

**Comment by zhongyuankai** [comment]
@den-crane `DDLWorker` doesn't seem to register zookeeper watch, I'm still a little confused.

**Comment by den-crane** [comment]
https://github.com/ClickHouse/ClickHouse/pull/28446
