### ISSUE TITLE
What is the best way to compare two data sets?

### ISSUE THREAD

**Issue by x052bb** [ClickHouse/ClickHouse#33869]
Hi

Can someone help me with the following:

Suppose we have two data sets, which are a result of executing some SQL queries over same data: 

1. SELECT * FROM x WHERE [clause-1]
2. SELECT * FROM x WHERE [clause-2]

Is there a good way to check if two datasets are equal, meaning that they have same number of records, all records have same values and record order is the same?

I was thinking of calculating a checksum, something like:

SELECT count(1), hex(groupBitXor(cityHash64(*))) AS checksum FROM ( SELECT * FROM x WHERE [clause-1] ) 

However, this is not working in case there're columns with type Nullable(String) - checksum is NULL in that case (I'm using v21.9, is that a bug?). Is there any other/better way to do it, taking into account that Nullable(String) columns exist?

**Comment by den-crane** [comment]
```
select cityHash64(groupArray(x)) from(SELECT cityHash64(*) as x FROM system.tables order by x)
┌─cityHash64(groupArray(x))─┐
│       4761183170873013810 │
└───────────────────────────┘

select cityHash64(groupArray(x)) from(SELECT cityHash64(*) as x FROM system.tables order by x)
┌─cityHash64(groupArray(x))─┐
│       4761183170873013810 │
└───────────────────────────┘
```

**Comment by den-crane** [comment]
```
SELECT cityHash64( * apply(assumeNotNull)) x from( select Null::Nullable(String) a, '1' b )
┌────────────────────x─┐
│ 14766776127050545118 │
└──────────────────────┘
```


```
select cityHash64(groupArray(x)) from(SELECT cityHash64(* apply(assumeNotNull)) as x FROM system.tables order by x)
┌─cityHash64(groupArray(x))─┐
│      11460911010878452903 │
└───────────────────────────┘
```

**Comment by alexey-milovidov** [comment]
`SELECT sum(cityHash64(*)) FROM table`
