### ISSUE TITLE
Metric HTTPConnection may be incorrect

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#33864]
HTTPConnection is counted on the HTTPHandler level.  While the http connections are maintained on Poco level. 

That means for example that we can open 1000 connections to HTTP but until some HTTP requests will be sent and poco will call the HTTP hander the metric will be showing 0. 

So actually it counts in-flight http queries, not connections. 

Ideally would be to count both real connections & in-flight http queries.

Also may be a counter of served http queries could be nice (to catch / count fast queries which are hard to see via system.metrics)

Loosely related to https://github.com/ClickHouse/ClickHouse/issues/23858

**Comment by alexey-milovidov** [comment]
Let's do nothing about this observation.
