### ISSUE TITLE
Respect cgroup-v2 limits on CPU and memory

### ISSUE THREAD

**Issue by JaySon-Huang** [ClickHouse/ClickHouse#33865]
**Use case**

> A clear and concise description of what is the intended usage scenario is.

After #30574, #33342, `getMemoryAmount` and `getNumberOfPhysicalCPUCores` respect [cgroup v1](https://www.kernel.org/doc/html/latest/admin-guide/cgroup-v1/index.html) llimits and can get the right amount of CPU and memory when running inside a docker container.

Linux 4.5 introduce [control group v2](https://www.kernel.org/doc/html/latest/admin-guide/cgroup-v2.html) restriction. Those functions don't follow the restriction of cgroup v2. However, AFAIK, cgroup v2 is not enabled by default and is not widely used, so I create an issue for it. One can pick up this issue if he/she is interested in it.

/cc @bobrik from https://github.com/ClickHouse/ClickHouse/pull/33342#issuecomment-1005349821

**Describe the solution you'd like**

> A clear and concise description of what you want to happen.

Follow the CPU/Memory restriction on cgroup v2

**Describe alternatives you've considered**

> A clear and concise description of any alternative solutions or features you've considered.

**Additional context**

> Add any other context or screenshots about the feature request here.

Reference:
* Control Group v2: https://www.kernel.org/doc/html/latest/admin-guide/cgroup-v2.html

**Comment by Algunenano** [comment]
Implemented in https://github.com/ClickHouse/ClickHouse/pull/59516
