### ISSUE TITLE
Calculate unrealized profit/loss from a table using a FIFO method in Clickhouse

### ISSUE THREAD

**Issue by artemg** [ClickHouse/ClickHouse#33881]
.

**Comment by den-crane** [comment]
as I understand it should solve scenario like this

```
transaction_type, quantity, price, time
Buy,              10,       1$,    1
Buy,              5,        2$,    2
Sell,             1,        10$,   3
Buy,              10,       1$,    4
Buy,              5,        2$,    5
Sell,             1,        10$,   6
Buy,              10,       1$,    7
Buy,              5,        2$,    8
Sell,             1,        10$,   9
```
all rows can be processes only one by one sequentially. 


Clickhouse is created to solve MPP/OLAP tasks, it means that data can be separated into small pieces and each piece can be aggregated separately which is impossible if you need to find nearest in infinite window.

There is a new feature which can help https://clickhouse.com/docs/en/sql-reference/statements/create/view/#window-view  https://github.com/ClickHouse/ClickHouse/pull/8331

But in general tasks like this should be solved at ETL before loading data into ClickHouse.
