### ISSUE TITLE
[Cloud Native Feature] make one node run multi-shards

### ISSUE THREAD

**Issue by LiuYangkuan** [ClickHouse/ClickHouse#33904]
**Use case**
> A clear and concise description of what is the intended usage scenario is.

After separation of storage and compute, It will be very convenient to scale out and add nodes into cluster without data move.
But there is still an issue that dataset should be split and re-shard because size of data shards is less than compute node size.

**Describe the solution you'd like**
> A clear and concise description of what you want to happen.

If we can make one node run multi-shards, there is no need to split dataset in most cases. For example, If one node runs four shards, we can scale out four times nodes without dataset spliting.

**Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.

A cluster shard is made of (or identified by) host_address, port and default_database. We can use multi `ReplicatedDatabases` with different database name as default_database in a compute node. So we can setup a special cluster which contains compute nodes run multi-shards.

**Additional context**
> Add any other context or screenshots about the feature request here.

We can create a new entity whose kind is `CLUSTER`
```CREATE CLUSTER cluster_name SETTINGS('/clickhouse/zookeeper-path', 'share storage config', shard_size=16)```

After above statement, a ZK-node will be created, whose children contain `ReplicatedDatabase` metadata node and cluster discovery node, etc.
We can use this PR [#31442](https://github.com/ClickHouse/ClickHouse/pull/31442) idea to generate a dynamic `special cluster` map config

Supposing we have four compute nodes, and make a normal cluster `default`

```CREATE DATABASE cloud_db ON CLUSTER default ENGINE = Cloud('/clickhouse/zookeeper-path')```

Here we import a new database engine `Cloud`, it will register node itself into Cluster through zookeeper-path and join leader election.
Only one leader can play the role of shard assignment and rebalance when failover.

After shard assignment, every compute node receives multi-shards such as shard4/shard5/shard6/shard7, then the `Cloud` database engine will create four internal databases which engine is `ReplicatedDatabase` and named shard4, shard5, shard6, shard7. All tables created in these databases will use the share storage config and storage_policies from zookeeper.

Users work in cloud_db, create MergeTree family tables adding sharding_key as settings, the `Cloud` database will create `Distributed` table additionally in `ReplicatedDatabase`, for example Distributed(cluster, '', table, sharding_key), make database empty and use default_database in cluster for each shard.  And only load or show `Distributed` tables from metadata in zookeeper path.
Local table and distributed table always make user confused. Cloud database only show logical table that may be more user-friendly.

After all compute nodes register and finish shard assignment, all shards are ready and the `special cluster` can work.
If the speed of failover is fast enough, the Replicated*MergeTree is not recommended, because share storage make data service high available.

A high performance and transactional data part service will better in `Cloud Native Warehouse`

**Comment by alexey-milovidov** [comment]
Abandoned.
