### ISSUE TITLE
same select on distributed table takes different time,  80x slower

### ISSUE THREAD

**Issue by wzisheng** [ClickHouse/ClickHouse#33900]
v21.3
Hi，I have a simple select on distributed table like 

> select * from distributed_table where 'expr' limit 10

one will be end in ms level 

> 17:07:12.137298 [ 5911 ] <Debug> InterpreterSelectQuery: MergeTreeWhereOptimizer: condition "(xxx = '2022-01-19') AND (xxx = 'xxx') AND (timestamps >= xxx) AND (timestamps <= xxx)" moved to PREWHERE
17:07:12.138717 [ 5911 ] <Trace> ContextAccess (default): Access granted: xxx
17:07:12.139227 [ 5911 ] <Debug> default.table_test (889c1c33-c0f9-43b6-ba77-4a88119470ec) (SelectExecutor): Key condition: unknown, (column 1 in ['xxx', 'xxx']), and, unknown, and, unknown, and, (column 0 in [1, 1]), and, unknown, (column 1 in ['xxx', 'xxx']), and, unknown, and, unknown, and, and
17:07:12.139241 [ 5911 ] <Debug> default.table_test (889c1c33-c0f9-43b6-ba77-4a88119470ec) (SelectExecutor): MinMax index condition: (column 0 in [19011, 19011]), unknown, and, unknown, and, unknown, and, unknown, and, (column 0 in [19011, 19011]), unknown, and, unknown, and, unknown, and, and
17:07:12.139584 [ 5911 ] <Trace> default.table_test (889c1c33-c0f9-43b6-ba77-4a88119470ec) (SelectExecutor): Running binary search on index range for part 20220119_0_6744_5 (236818 marks)
17:07:12.139609 [ 5911 ] <Trace> default.table_test (889c1c33-c0f9-43b6-ba77-4a88119470ec) (SelectExecutor): Found (LEFT) boundary mark: 0
17:07:12.139632 [ 5911 ] <Trace> default.table_test (889c1c33-c0f9-43b6-ba77-4a88119470ec) (SelectExecutor): Found (RIGHT) boundary mark: 2671
17:07:12.139637 [ 5911 ] <Trace> default.table_test (889c1c33-c0f9-43b6-ba77-4a88119470ec) (SelectExecutor): Found continuous range in 35 steps
17:07:12.143257 [ 5911 ] <Debug> default.table_test (889c1c33-c0f9-43b6-ba77-4a88119470ec) (SelectExecutor): Index `c1_minmax_index` has dropped 0/891 granules.
17:07:12.143269 [ 5911 ] <Debug> default.table_test (889c1c33-c0f9-43b6-ba77-4a88119470ec) (SelectExecutor): Index `test_minmax_index` has dropped 0/891 granules.
17:07:12.143273 [ 5911 ] <Debug> default.table_test (889c1c33-c0f9-43b6-ba77-4a88119470ec) (SelectExecutor): Selected 1/34 parts by partition key, 1 parts by primary key, 2671/236818 marks by primary key, 2671 marks to read from 1 ranges
17:07:12.143422 [ 5911 ] <Trace> default.table_test (889c1c33-c0f9-43b6-ba77-4a88119470ec) (SelectExecutor): Reading approx. 21880832 rows with 16 streams
17:07:12.144269 [ 5911 ] <Trace> InterpreterSelectQuery: FetchColumns -> WithMergeableState
17:07:12.144796 [ 5911 ] <Trace> InterpreterSelectQuery: WithMergeableState -> Complete
17:07:12.173832 [ 31420 ] <Trace> StorageDistributed (table_test_all): (clickhousesgKY:9000) Cancelling query because enough data has been read
17:07:12.180020 [ 11932 ] <Trace> StorageDistributed (table_test_all): (clickhousehost2:9000) Cancelling query because enough data has been read
17:07:12.181963 [ 23398 ] <Trace> StorageDistributed (table_test_all): (clickhousehost4:9000) Cancelling query because enough data has been read
17:07:12.188269 [ 5578 ] <Trace> StorageDistributed (table_test_all): (clickhousehost1:9000) Cancelling query because enough data has been read
17:07:12.208702 [ 5911 ] <Information> executeQuery: **Read 131072 rows, 123.07 MiB in 0.074053698 sec., 1769958 rows/sec., 1.62 GiB/sec.**
17:07:12.208745 [ 5911 ] <Debug> MemoryTracker: Peak memory usage (for query): 635.56 MiB.

whiele another ends in seconds level 

> 17:06:59.704876 [ 5911 ] <Debug> InterpreterSelectQuery: MergeTreeWhereOptimizer: condition "(xxx = '2022-01-19') AND (xxx = 'xxx') AND (timestamps >= xxx) AND (timestamps <= xxx)" moved to PREWHERE
17:06:59.706266 [ 5911 ] <Trace> ContextAccess (default): Access granted: xxx
17:06:59.706787 [ 5911 ] <Debug> default.table_test (889c1c33-c0f9-43b6-ba77-4a88119470ec) (SelectExecutor): Key condition: unknown, (column 1 in ['xxx', 'xxx']), and, unknown, and, unknown, and, (column 0 in [1, 1]), and, unknown, (column 1 in ['xxx', 'xxx']), and, unknown, and, unknown, and, and
17:06:59.706814 [ 5911 ] <Debug> default.table_test (889c1c33-c0f9-43b6-ba77-4a88119470ec) (SelectExecutor): MinMax index condition: (column 0 in [19011, 19011]), unknown, and, unknown, and, unknown, and, unknown, and, (column 0 in [19011, 19011]), unknown, and, unknown, and, unknown, and, and
17:06:59.707140 [ 5911 ] <Trace> default.table_test (889c1c33-c0f9-43b6-ba77-4a88119470ec) (SelectExecutor): Running binary search on index range for part 20220119_0_6744_5 (236818 marks)
17:06:59.707170 [ 5911 ] <Trace> default.table_test (889c1c33-c0f9-43b6-ba77-4a88119470ec) (SelectExecutor): Found (LEFT) boundary mark: 0
17:06:59.707192 [ 5911 ] <Trace> default.table_test (889c1c33-c0f9-43b6-ba77-4a88119470ec) (SelectExecutor): Found (RIGHT) boundary mark: 2671
17:06:59.707198 [ 5911 ] <Trace> default.table_test (889c1c33-c0f9-43b6-ba77-4a88119470ec) (SelectExecutor): Found continuous range in 35 steps
17:06:59.710851 [ 5911 ] <Debug> default.table_test (889c1c33-c0f9-43b6-ba77-4a88119470ec) (SelectExecutor): Index `c1_minmax_index` has dropped 0/891 granules.
17:06:59.710863 [ 5911 ] <Debug> default.table_test (889c1c33-c0f9-43b6-ba77-4a88119470ec) (SelectExecutor): Index `test_minmax_index` has dropped 0/891 granules.
17:06:59.710867 [ 5911 ] <Debug> default.table_test (889c1c33-c0f9-43b6-ba77-4a88119470ec) (SelectExecutor): Selected 1/44 parts by partition key, 1 parts by primary key, 2671/236818 marks by primary key, 2671 marks to read from 1 ranges
17:06:59.711018 [ 5911 ] <Trace> default.table_test (889c1c33-c0f9-43b6-ba77-4a88119470ec) (SelectExecutor): Reading approx. 21880832 rows with 16 streams
17:06:59.711895 [ 5911 ] <Trace> InterpreterSelectQuery: FetchColumns -> WithMergeableState
17:06:59.712406 [ 5911 ] <Trace> InterpreterSelectQuery: WithMergeableState -> Complete
17:06:59.748571 [ 3536 ] <Trace> StorageDistributed (table_test_all): (clickhousehost1:9000) Cancelling query because enough data has been read
17:06:59.897405 [ 22032 ] <Trace> StorageDistributed (table_test_all): (clickhousehost2:9000) Cancelling query because enough data has been read
17:06:59.920821 [ 31850 ] <Trace> StorageDistributed (table_test_all): (clickhousehost3:9000) Cancelling query because enough data has been read
17:07:01.429952 [ 22032 ] <Trace> StorageDistributed (table_test_all): (clickhousehost4:9000) Cancelling query because enough data has been read
17:07:06.158797 [ 5911 ] <Information> executeQuery: **Read 131072 rows, 123.07 MiB in 6.457007691 sec., 20299 rows/sec., 19.06 MiB/sec.**
17:07:06.158845 [ 5911 ] <Debug> MemoryTracker: Peak memory usage (for query): 635.66 MiB.

actually they both scan 131072 rows, seems the difference is only RemoteQueryExecutor schedule, do you have any idea for this?

**Comment by den-crane** [comment]
Is it reproducible ?

**Comment by wzisheng** [comment]
> Is it reproducible ?

yes, by now it exists always,,, Continuous insert into this table ,and with some other query being executed, scenario is very simple..

anything else do you need..

**Comment by alexey-milovidov** [comment]
You should look at the query metrics and do query profiling.

https://clickhouse.com/docs/en/operations/system-tables/query_log/ - see ProfileEvents

https://clickhouse.com/docs/en/operations/optimizing-performance/sampling-query-profiler/

**Comment by wzisheng** [comment]
the slower one's profileEvents
> 'Query'	1
'SelectQuery'	1
'FileOpen'	4
'Seek'	2
'ReadBufferFromFileDescriptorRead'	6
'ReadBufferFromFileDescriptorReadBytes'	3826612
'ReadCompressedBytes'	37576
'CompressedReadBufferBlocks'	3
'CompressedReadBufferBytes'	131082
'IOBufferAllocs'	8
'IOBufferAllocBytes'	5006582
'FunctionExecute'	171
'MarkCacheHits'	
MarkCacheMisses'	
ReadBackoff'	
'CreatedReadBufferOrdinary'	4
'DiskReadElapsedMicroseconds'	1030
'NetworkSendElapsedMicroseconds'	1459
'SlowRead'	
'SelectedParts'	1
'SelectedRanges'	1
'SelectedMarks'	2671
'SelectedRows'	
'SelectedBytes'	
'ContextLock'	280
'RWLockAcquiredReadLocks'	3
'RealTimeMicroseconds'	6457298
'UserTimeMicroseconds'	13058
'SystemTimeMicroseconds'	5122
'SoftPageFaults'	50  

I'm trying to get understanding of them...  
I would be glad if you can let me know which one is abnormal.  As of now it seems 'ContextLock' of 280 is a little high...

**Comment by wzisheng** [comment]
sampling profiler shows that, 80%~90% of the three slower executions time are waitting here https://github.com/ClickHouse/ClickHouse/blob/b92692e00103113b26f9731de8c93d7bcb9ac84e/src/Processors/Executors/PipelineExecutor.cpp#L561

**Comment by den-crane** [comment]
>SlowRead | 1124 | 909 | 1700 |  535

Disk is overloaded
