### ISSUE TITLE
Understanding Explain Plan

### ISSUE THREAD

**Issue by yuval-boker** [ClickHouse/ClickHouse#33915]
What is the difference between the following:

**Expression (( + (Projection + Before ORDER BY)))**  
**Expression ((Projection + Before ORDER BY))**

For one of my queries I replaced the literal 0 with an alias to this literal, that is:
**select 0 from (select 0 as x)** instead of **select x from (select 0 as x);** and it slowed the query by a factor of two! (4 sec instead of 2)
I checked the query plan and the only thing changed is that **Expression (( + (Projection + Before ORDER BY)))**  became **Expression ((Projection + Before ORDER BY))**. 

I though exactly the obvious would happen, that using a literal would be faster than using an alias to that literal.
Any thoughts?

**Comment by tom-clickhouse** [comment]
I tried to reproduce the execution speed differences, but on my system with the current release, both queries have the same zero execution speed. 

`./clickhouse benchmark --query 'select 0 from (select 0 as x);` and 
`./clickhouse benchmark --query 'select x from (select 0 as x);` both look the same:
0.000%		       0.000 sec.	
10.000%		0.000 sec.	
20.000%		0.000 sec.	
30.000%		0.000 sec.	
40.000%		0.000 sec.	
50.000%		0.000 sec.	
60.000%		0.000 sec.	
70.000%		0.000 sec.	
80.000%		0.000 sec.	
90.000%		0.000 sec.	
95.000%		0.000 sec.	
99.000%		0.000 sec.	
99.900%		0.001 sec.	
99.990%		0.001 sec.

Could you provide your original queries and description of your execution environment?

I agree that it makes sense that `select 0 from (select 0 as x);` can/should be faster than `select x from (select 0 as x);` as the former is equivalent to just `select 0;`(the inner select is ignored/not required). But I'm not sure if these are the actual queries where you observe a slowing of the former query by a factor of two.

**Comment by yuval-boker** [comment]
Thanks Tom.

I can't share the tables but this is the query:
`SELECT "guid_2"."guid_1.0_keyword" AS "keyword", "guid_2"."guid_1.1_0" AS "tmp_col", "guid_2"."guid_1.2_SUM(visits)" AS "tmp_visits"
FROM  (
SELECT "guid_1"."keyword" AS "guid_1.0_keyword", 0 AS "guid_1.1_0", sum("guid_1"."visits") AS "guid_1.2_SUM(visits)"
FROM MY_TABLE AS "guid_1"
WHERE ( ( "guid_1"."date" >= '2020-06-01' ) AND ( ( "guid_1"."date" <= '2020-06-07' ) AND ( ( "guid_1"."site" = 'amazon.com' ) AND ( ( "guid_1"."country" = 840 ) AND "guid_1"."keyword" IN (SELECT "guid_2"."guid_1.0_keyword" AS "keyword"
FROM  (
SELECT "guid_1"."keyword" AS "guid_1.0_keyword", sum("guid_1"."visits") AS "guid_1.1_SUM(visits)"
FROM MY_TABLE AS "guid_1"
WHERE ( ( "guid_1"."country" = 840 ) AND ( ( "guid_1"."site" = 'amazon.com' ) AND ( ( "guid_1"."date" <= '2020-06-14' ) AND ( "guid_1"."date" >= '2020-06-08' ) ) ) )
GROUP BY "guid_1"."keyword"
ORDER BY sum("guid_1"."visits") DESC NULLS FIRST
 LIMIT 100
)
 AS "guid_2"
 ) ) ) ) )
GROUP BY "guid_1"."keyword", 0
ORDER BY "guid_1"."keyword" ASC NULLS LAST
)
 AS "guid_2"`

Now, my **only** change is replacing `"guid_2"."guid_1.1_0 as "tmp_col"` with  `0 AS "tmp_col"`. That is:

`SELECT "guid_2"."guid_1.0_keyword" AS "keyword", 0 AS "tmp_col", "guid_2"."guid_1.2_SUM(visits)" AS "tmp_visits"
FROM  (
SELECT "guid_1"."keyword" AS "guid_1.0_keyword", 0 AS "guid_1.1_0", sum("guid_1"."visits") AS "guid_1.2_SUM(visits)"
FROM MY_TABLE AS "guid_1"
WHERE ( ( "guid_1"."date" >= '2020-06-01' ) AND ( ( "guid_1"."date" <= '2020-06-07' ) AND ( ( "guid_1"."site" = 'amazon.com' ) AND ( ( "guid_1"."country" = 840 ) AND "guid_1"."keyword" IN (SELECT "guid_2"."guid_1.0_keyword" AS "keyword"
FROM  (
SELECT "guid_1"."keyword" AS "guid_1.0_keyword", sum("guid_1"."visits") AS "guid_1.1_SUM(visits)"
FROM MY_TABLE AS "guid_1"
WHERE ( ( "guid_1"."country" = 840 ) AND ( ( "guid_1"."site" = 'amazon.com' ) AND ( ( "guid_1"."date" <= '2020-06-14' ) AND ( "guid_1"."date" >= '2020-06-08' ) ) ) )
GROUP BY "guid_1"."keyword"
ORDER BY sum("guid_1"."visits") DESC NULLS FIRST
 LIMIT 100
)
 AS "guid_2"
 ) ) ) ) )
GROUP BY "guid_1"."keyword", 0
ORDER BY "guid_1"."keyword" ASC NULLS LAST
)
 AS "guid_2"`

Surprisingly, the **first** version is two times faster.(around 2 seconds compare to 5 seconds).
I'm adding the Logical plan:
https://www.diffchecker.com/zRJlVfrV
By the logical plan it  looks like the second version should be faster.

Hope you'll figure out.

**Comment by tbragin** [comment]
@yuval-boker Are you still experiencing this issue? If so, on what version? If it is not one of the supported versions, I'd recommend upgrading and trying again. https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md#scope-and-supported-versions
