### ISSUE TITLE
"CANNOT_PARSE_DOMAIN_VALUE_FROM_STRING" on an IPv6 parameter

### ISSUE THREAD

**Issue by DarkWanderer** [ClickHouse/ClickHouse#33928]
**Describe the unexpected behaviour**
Exception when passing an IPv6 address via HTTP parameters or command line. Same IPv6 address works when passed to `toIPv6` function

**How to reproduce**
```
$> clickhouse-client --query "SELECT toIPv6('2001:db8:85a3::8a2e:370:7334')"
2001:db8:85a3::8a2e:370:7334

$> clickhouse-client --param_var 2001:db8:85a3::8a2e:370:7334 --query "SELECT {var:IPv6}"
Received exception from server (version 22.1.2):
Code: 441. DB::Exception: Received from 127.0.0.1:9000. DB::Exception: Invalid IPv6 value.: While processing _CAST(' \r���\0\0\0\0�.ps4', 'IPv6'). (CANNOT_PARSE_DOMAIN_VALUE_FROM_STRING)
(query: SELECT {var:IPv6})
```

**Additional context**
This is a regression in versions 22.* (21.* work), potentially related to #31072

**Comment by Avogar** [comment]
It's not related to #31072, the bug was introduced in https://github.com/ClickHouse/ClickHouse/pull/29224. Will fix it
