### ISSUE TITLE
parseDateTimeBestEffort  empty string result in exception on 21.8.5.7-lts

### ISSUE THREAD

**Issue by mo-avatar** [ClickHouse/ClickHouse#33937]
(you don't have to strictly follow this form)

**Describe the issue**
parseDateTimeBestEffort with empty string result in exception on 21.8.5.7-lts, but has a weird result on v20.8.9.6-lts.

For those bi tools which use parseDateTimeBestEffort function,  when upgrade to 21.8.5.7-lts, if the dataset contains an empty string，an exception will be raised.

Is the exception an expected behavior of select parseDateTimeBestEffort('') ? thanks!

select parseDateTimeBestEffort('');

SELECT parseDateTimeBestEffort('')
Query id: e5a43b1c-af21-4303-b133-77ba34833335
0 rows in set. Elapsed: 0.001 sec.

Received exception from server (version 21.8.5):
Code: 41. DB::Exception: Received from 10.32.46.9:9000. DB::Exception: Cannot read DateTime: neither Date nor Time was parsed successfully: While processing parseDateTimeBestEffort('')

-----------------------------------------------------------------------
but result in 2000-01-01 00:00:00 on v20.8.9.6-lts
SELECT parseDateTimeBestEffort('')

┌─parseDateTimeBestEffort('')────┐
│                      2000-01-01 00:00:00  │
└──────────────────────┘

1 rows in set. Elapsed: 0.004 sec. 

**How to reproduce**
* Which ClickHouse server versions are incompatible
* Which interface to use, if matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

**Error message and/or stacktrace**

**Additional context**

**Comment by alexey-milovidov** [comment]
Yes, it is expected.

See also `parseDateTimeBestEffortOrNull`.
