### ISSUE TITLE
clickhouse supports viewfs

### ISSUE THREAD

**Issue by michael1589** [ClickHouse/ClickHouse#33934]
> Currently clickhouse doesn't support viewfs

> There're two solutions:
1.Map viewfs to hdfs, clickhouse already supported hdfs
2.Develop a viewfs engine which like hdfs engine.

Do we have a plan to do this or viewfs solution can be accepted?

**Comment by alexey-milovidov** [comment]
We don't have plans for it and I hear about ViewFs for the first time.
What will be advantage of (2) over (1)?

Reference: https://hadoop.apache.org/docs/stable/hadoop-project-dist/hadoop-hdfs/ViewFs.html

**Comment by michael1589** [comment]
Advantage of (2) over (1)：
You do not need to configure hadoop any longer(That asks you have admin rights). But can directly access viewfs uri.

**Comment by amosbird** [comment]
This should be a FR to the libhdfs3 project instead.

**Comment by amosbird** [comment]
https://github.com/ClickHouse/ClickHouse/issues/25656
