### ISSUE TITLE
CentOS compile with one linux user, run error with another user

### ISSUE THREAD

**Issue by shangshujie365** [ClickHouse/ClickHouse#3393]
We are using Centos, and our compile machine and running machine are using different user account, userA in compile machine, userB in running machine, I think this is the reason.
When we compile(make/make install) clickhouse in compile machine with user userA, and copy the result to another running machine, start it with another user (user 'clickhouse'), we got error:
2018.10.16 14:36:17.312553 [ 1 ] {} <Information> : Starting ClickHouse 18.14.8 with revision 54409
2018.10.16 14:36:17.315719 [ 1 ] {} <Information> Application: starting up
Auto configuration failed
140201974990560:error:02FFF00D:system library:func(4095):Permission denied:/home/userA/xxx/ClickHouse/contrib/ssl/crypto/bio/bss_file.c:122:fopen('/home/userA/xxx/ClickHouse/build/ch-18.14/etc/ssl/openssl.cnf', 'rb')
140201974990560:error:20FFF002:BIO routines:CRYPTO_internal:system lib:/home/userA/xxx/ClickHouse/contrib/ssl/crypto/bio/bss_file.c:127:
140201974990560:error:0EFFF002:configuration file routines:CRYPTO_internal:system lib:/home/userA/xxx/ClickHouse/contrib/ssl/crypto/conf/conf_def.c:200:

if we create account 'userA' in running machine and run ch using 'userA', everything is ok.
It seems, when compiling, ch remember the Install-path somehow
our make command: 
source code dir is /home/userA/xxx/ClickHouse, branch stable
cmake ../.. -DCMAKE_INSTALL_PREFIX=/home/userA/xxx/ClickHouse/build/ch-18.14 -DCMAKE_BUILD_TYPE=release
make
make install

**Comment by proller** [comment]
Why you change CMAKE_INSTALL_PREFIX ? It brokes config loading.

**Comment by shangshujie365** [comment]
@proller our os is centos, so, we should build ourselves

**Comment by alexey-milovidov** [comment]
Now we provide official RPM packages, no need to build manually.
