### ISSUE TITLE
parallel_distributed_insert_select + cluster('xxx',view())

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#33945]
**Use case**

Run view on each shard individually and insert into local node.

**Describe the solution you'd like**

```sql

INSERT INTO FUNCTION cluster('all-sharded', map, output, key_2) SELECT *
FROM cluster('all-sharded', view(
    SELECT *
    FROM map.input
    WHERE (key_1 % 2) = toUInt32(getMacro('all-sharded-shard'))
))
SETTINGS parallel_distributed_insert_select = 2

Query id: 0ef3707f-2b74-4367-bf6d-82939a64e0f2


0 rows in set. Elapsed: 0.002 sec.

Received exception from server (version 21.11.10):
Code: 60. DB::Exception: Received from localhost:9000. DB::Exception: Both table name and UUID are empty. (UNKNOWN_TABLE)
```

**Comment by amosbird** [comment]
Off topic: I guess you can use `shardNum()` instead of `toUInt32(getMacro('all-sharded-shard'))`.

**Comment by azat** [comment]
Actually before #34728, `parallel_distributed_insert_select=2` does not works correctly with `remote`/`cluster`.

**Comment by azat** [comment]
@UnamedRus why do you need `view` here?

**Comment by UnamedRus** [comment]
> @UnamedRus why do you need view here?

map.input is distributed table with random sharding.

By using

```
FROM cluster('all-sharded', view(
    SELECT *
    FROM map.input
    WHERE (key_1 % 2) = toUInt32(getMacro('all-sharded-shard'))
))
```

I can split single GROUP BY query in x buckets and do it in parallel on all servers.

**Comment by azat** [comment]
>map.input is distributed table with random sharding.

But in this case you get SELECT from Distributed-over-Distributed.

This looks pretty complex, but it seems that you can archive the same with the following query?

```sql
CREATE TABLE map.input_double_dist as map.input Engine=Distributed('all-sharded', map, input);
INSERT INTO FUNCTION cluster('all-sharded', map, output, key_2)
SELECT * FROM map.input_double_dist WHERE (key_1 % 2) = toUInt32(getMacro('all-sharded-shard'))
```

But #34728 should address this (it will unwrap `view`)

**Comment by UnamedRus** [comment]
> But in this case you get SELECT from Distributed-over-Distributed.

Well, if that query will be push-down to individual nodes, so we will run X queries from Distributed table. but they will not be truly Distributed-over-Distributed
