### ISSUE TITLE
How to achieve data re-balancing in Clickhouse automatically  after  new shard is added?

### ISSUE THREAD

**Issue by surajmachamasi** [ClickHouse/ClickHouse#33947]
currently i have 2 shards up and running and i have added new shard.  but the problem is, i want to distribute all existing data to each shards equally and automatically and all the existing data should be re-balanced to each shards. 
so how to achieve it? 

one shard storage is 99 % and shard 2 90% so we added 3rd shard. so will it rebalance the data on addition of shards ?
and how does the CH behaves on this situation?

**Comment by surajmachamasi** [comment]
one shard 99 % and shard 2 90%  so we added 3rd shard. so will it rebalnce the data ?

**Comment by qoega** [comment]
You can use clickhouse-copier if you want to move the data. There is no internal logic that moves data between shards. Shards are autonomous and don't interact.
https://clickhouse.com/docs/en/operations/utilities/clickhouse-copier/#clickhouse-copier

**Comment by gingerwizard** [comment]
ClickHouse does not support automatic shard rebalancing. However, there are ways to rebalance shards in order of preference:

1. Adjust shard for the [distributed table](https://clickhouse.com/docs/en/engines/table-engines/special/distributed/) allowing writes to be biased to the new shard. This potentially will cause load imbalances and hot spots on the cluster, but can be viable in most scenarios where write throughput is not extremely high. It does not require the user to change their write target i.e. i can remain as the distributed table. This does not assist with rebalancing existing data.

2. As an alternative to (1), modify the existing cluster and write exclusively to the new shard until the cluster is balanced - effectively manually weighting writes. This has the same limitations as (1).

3. If you need to rebalance existing data, and you have partitioned your data, consider detaching partitions and manually relocating them to another node before reattaching to the new shard. This is more manual than subsequent techniques but may be faster and less resource intensive. It suffers from potentially causing hot spots on reads e.g. if you move old data partitioned by time that is less likely to be queried. This is a manual operation and thus needs to consider the rebalancing of the data.

4. Create a new cluster with the new topology and copy the data using [ClickHouse Copier](https://clickhouse.com/docs/en/operations/utilities/clickhouse-copier/).  Alternatively, create a new database within the existing cluster and migrate the data using ClickHouse Copier. This can be potentially computationally expensive and may impact your production environment. Building a new cluster, on a new deployment and using this technique is an option to mitigate this, at the expense of cost.

5. Export the data from the source cluster to the new cluster via an[ INSERT FROM SELECT](https://clickhouse.com/docs/en/sql-reference/statements/insert-into/#insert_query_insert-select). This will not be performant on very large datasets and will potentially incur significant IO on the source cluster and use considerable network resources. This represents a last resort.

**Comment by gingerwizard** [comment]
@surajmachamasi any further information needed here?

**Comment by gingerwizard** [comment]
Closing as no further requests for information.
