### ISSUE TITLE
Config option to enable/disable auth type "plaintext_password"  for user ACL

### ISSUE THREAD

**Issue by HeenaBansal2009** [ClickHouse/ClickHouse#33953]
**Use case**
Currently Clickhouse allows authetication_type : NO_password ,  plaintext_password  , SHA_256 and SHA_1 type , LDAP , Kerberos of passwords in user settings.
Configuration change to allow enable/disable usage of cleartext_password for Access management in user profile. 

**Reason**
plaintext_password is easy to configure but unsafe . 

**Describe the solution you'd like**

- < enable_plaintext_password =0>

Alter/Create user identified with plaintext_password should not be allowed.
CREATE/ALTER USER IF NOT EXISTS XYZ
  IDENTIFIED WITH plaintext_password BY 'summer#1' HOST ANY DEFAULT ROLE --> Error 

-  Error is expected when user tries to set cleartext_password if enable_plaintext_password is disabled.

- ConfigReloading should be take-in to consideration.

**Describe alternatives you've considered**

- Add a build  flag option to enable/disable plaintext password auth-type - @alexey-milovidov  suggested to have a  config option which is more suitable for backward-compatibility and migration to higher version of clickhouse.

**Additional context**
This feature is not considering “NO_password” auth type.(can be done as next step)
This feature doesn’t consider the protocol level disabling of plain_text password. 

Let me know what do you feel about this feature. I am planning to implement this - please pour in your suggestions/questions.

**Comment by HeenaBansal2009** [comment]
Hi All ,
I am planning to set a config option in users.xml at profile level like this: 
```
<profiles>
      <default> // Not Needed to provide as well , by default value is unset.
          <enable_plaintext_password>0</enable_plaintext_password>
     </default>
      <profile2>
       <enable_plaintext_password>1</enable_plaintext_password>
   </profile2>
</profiles>
``` 
So , this config value can be different for different values and similar different users can set different profiles.
For example 
```
<users>
   <user1>
      <password>””qwerty”</password>.   This should be allowed
     <profile> profile2</profile>
  </user1>
  <user2>.                    
    <password></password>        -  This should not be allowed 
     <profile> default</profile>. 
  </user2>

```

Please pour in your suggestions on this design . Thanks

**Comment by HeenaBansal2009** [comment]
@vitlibar , How this globalcontext can be accessed here. 
I would like to know your opinion/thoughts on this or any alternative you can suggest here.

 I am planning to put the new config  in global context and trying to find out how global context can be accessed while parsing users.xml.  I  don’t see we have withcontext reference visible in userConfigAccessStorage.cpp. At this stage the shared pointer was created in server.cpp but will not be fully loaded because All config xmls are not yet merged and parsed .Please correct me if i am wrong here. 

As part of my design -plan , The server should throw exception/fatal error if user is configured with plaintext password when new config called allow_plaintext_password is unset. So to achieve this , I am planning to add the checks when we are reading users.xml and pushing the passwords in storage under class usersConifgAccessStorage.cpp. However , This class does have withContext base class in its herirachy and hence I am unable to get the global context.

**Comment by HeenaBansal2009** [comment]
Thanks @vitlibar for the valuable suggestions on the design of this feature. Now, The plan is to add a new config option at global context level.

**Comment by HeenaBansal2009** [comment]
This feature is delivered.

**Comment by sureshvasanthkumar** [comment]
https://github.com/ClickHouse/ClickHouse/pull/34738#issuecomment-4976383445
