### ISSUE TITLE
parallel_view_processing=0 is does not work with INSERT INTO table VALUES

### ISSUE THREAD

**Issue by Algunenano** [ClickHouse/ClickHouse#33961]
Comes from https://github.com/ClickHouse/ClickHouse/pull/33951#discussion_r791027950

```
CREATE TABLE a (a Int64) ENGINE=Memory;
CREATE TABLE b (a Int64) ENGINE=Memory;
CREATE MATERIALIZED VIEW mv1 TO b AS Select sleep(1) as a FROM a;
CREATE MATERIALIZED VIEW mv2 TO b AS Select sleep(1) as a FROM a;
CREATE MATERIALIZED VIEW mv3 TO b AS Select sleep(1) as a FROM a;
CREATE MATERIALIZED VIEW mv4 TO b AS Select sleep(1) as a FROM a;
CREATE MATERIALIZED VIEW mv5 TO b AS Select sleep(1) as a FROM a;
CREATE MATERIALIZED VIEW mv6 TO b AS Select sleep(1) as a FROM a;
CREATE MATERIALIZED VIEW mv7 TO b AS Select sleep(1) as a FROM a;
CREATE MATERIALIZED VIEW mv8 TO b AS Select sleep(1) as a FROM a;
CREATE MATERIALIZED VIEW mv9 TO b AS Select sleep(1) as a FROM a;
CREATE MATERIALIZED VIEW mv10 TO b AS Select sleep(1) as a FROM a;
```

```
INSERT INTO a SELECT * FROM system.one;
```
Takes 10 seconds as expected.

```
INSERT INTO a VALUES(1);
```
Takes 1 second, which is unexpected and means that the MVs are being executed in parallel even though `parallel_view_processing == 0`.

Fails for 21.11+

**Comment by alexey-milovidov** [comment]
What is the reason to have sequential view processing?
Maybe we can say that parallel view processing is an advantage and deprecate the setting `parallel_view_processing`?

**Comment by Algunenano** [comment]
> What is the reason to have sequential view processing?

I understand that it's mostly to limit resource usage; at some point in the past it's had some issues but I think it's been pretty stable since the pipelines introduction. In some cases people also used sequential processing because they required a specific execution order (alphabetically in traditional engine or by uuid order in atomic databases).

I think that if there are other ways to limit resource usage (insert_threads?) and they work well, then this setting might no longer makes sense.

**Comment by Algunenano** [comment]
OTOH, the bug only happes with insert from values. Other insertion method did respect the setting and execute sequentially.
