### ISSUE TITLE
Create query failed when 20.3 and 21.10 clickhouse instances are in the same cluster. 

### ISSUE THREAD

**Issue by taiyang-li** [ClickHouse/ClickHouse#33975]
**Describe what's wrong**
I have one clickhouse cluster, some shards are installed with 20.3 version, some are installed with 21.10 version. 
When I execute a create on cluster query in 21.10 instance under database with ENGINE = Ordinary, it failed with error returned from 21.3 instance like this: 
```
An error occurred before execution: Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 39: UUID '66df08f5-75e2-4a7f-a6df-08f575e2ba7f' ON CLUSTER ck_cluster_preonline AS SELECT f_date AS day, max(f_uint64) AS max_uint64, min(f_int64) AS min_int64, max. Expected one of: AS, OpeningRoundBracket, ON, TO, token (version 20.3.8.53)
```

**Does it reproduce on recent release?**
I guesss it still can be reproduced in recent release from  source code. 

**How to reproduce**
Reproduce steps
First setup clickhouse cluster as above.
Execute those queries in any 21.10 instance: 
``` sql
CREATE DATABASE test on cluster ck_cluster_preonline ENGINE = Ordinary;  
CREATE TABLE default.haha on cluster ck_cluster_preonline 
(
    `f_uint8` UInt8,
    `f_uint16` UInt16,
    `f_uint32` UInt32,
    `f_int8` Int8,
    `f_int16` Int16,
    `f_int32` Int32,
    `f_int64` Int64,
    `f_uint64` UInt64,
    `f_string` String,
    `f_float32` Float32,
    `f_float64` Float64,
    `f_datetime` DateTime,
    `f_ipv4` IPv4,
    `f_ipv6` IPv6,
    `f_date` Date DEFAULT toDate(f_datetime),
    `f_orderby` UInt64
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{layer}-{shard}/default/haha', '{replica}')
PARTITION BY toYYYYMM(f_date)
PRIMARY KEY f_datetime
ORDER BY (f_datetime, f_orderby)
TTL f_date + 100
SETTINGS index_granularity = 8192 
```

> Add any other context about the problem here.

The code causing problem. Apparently the behavior of code is consistent with the comment. In the code, when execute create query on cluster, uuid will be generated no matter if corresponding database has uuid. 
``` c++

void InterpreterCreateQuery::prepareOnClusterQuery(ASTCreateQuery & create, ContextPtr local_context, const String & cluster_name)
{
    if (create.attach)
        return;

    /// For CREATE query generate UUID on initiator, so it will be the same on all hosts.
    /// It will be ignored if database does not support UUIDs.
    generateUUIDForTable(create);
```

**Comment by tavplubix** [comment]
It's expected that some complex queries (such as distributed DDL) may not work when there are 20.3 and 21.10 versions in a cluster. 21.10 was released more that a year and a half later than 20.3, it contains too many changes and some of them are probably incompatible.

20.3 is not supported since 2021-03-12, just upgrade the remaining hosts in the cluster.
