### ISSUE TITLE
startsWith function for arrays

### ISSUE THREAD

**Issue by altvod** [ClickHouse/ClickHouse#33982]
Support for arrays in `startsWith` (and, maybe, `endsWith`)

**Use case**

Would be quite useful for handling tree-like structured data where the node paths are specified as arrays of names or IDs.

**Describe the solution you'd like**

The desired behavior would be like this:
```
startsWith([1, 2, 3, 4], [1, 2])  -- true (1)
startsWith(['qwe', 'rty', 'ui', 'op'], ['qwe', 'rty'])  -- true (1)
startsWith([1, 2, 3, 4], [2, 4])  -- false (0)
startsWith([1, 1, 2, 2], [1, 2])  -- false (0)
```

And similarly, for `endsWith`

**Describe alternatives you've considered**

Something like `arraySlice(first, 1, length(second)) = second`

But `startsWith` would be much more readable, harder to make a mistake in and, probably, can be better optimized (i.e. might not have to create new objects like `arraySlice` does)

**Comment by CurtizJ** [comment]
Also, please, consider that since version 21.10 you can create the SQL UDF:
```sql

CREATE FUNCTION arrayStartsWith AS (first, second) -> (arraySlice(first, 1, length(second)) = second);

SELECT arrayStartsWith([1, 2, 3, 4], [1, 2]);

SELECT arrayStartsWith([1, 2, 3, 4], [1, 1]);
```

It solves the usability problem, but of performance is still suboptimal.

**Comment by altvod** [comment]
Thanks for the suggestion!
However, in my case I'm not sure it would really help, as I need a solution that would work with read-only access.

**Comment by alexey-milovidov** [comment]
Yes, this makes sense. Can be solved with reusing `GatherUtils`.
The code is quite template-heavy, but it is not too hard to implement.

**Comment by usurai** [comment]
Can I take this?

**Comment by alexey-milovidov** [comment]
@usurai Sure, it's yours!
