### ISSUE TITLE
Question about translation of changelog

### ISSUE THREAD

**Issue by Tiaonmmn** [ClickHouse/ClickHouse#33987]
**Describe the issue**
I'd like to know if you accept other language translation of changelog, not only in English.
Now, other translation of changelog is redirected to English version.

**Comment by den-crane** [comment]
I guess, you can translate and publish it on your resource, just make a link to the English original.

It was translated into Russian earlier, but these translations now removed, because they just don't have any sense

**Comment by Tiaonmmn** [comment]
OK,got it.
