### ISSUE TITLE
Is there a way to store an entire kafka message in a field of a materialised view?

### ISSUE THREAD

**Issue by johnnyleitrim** [ClickHouse/ClickHouse#33993]
I have a Kafka topic that contains JSON messages like:
```json
{
  "name":"John",
  "address": "1 Somewhere Drive",
  ...
}
```
I can create a Kafka engine and associated tables to store the data like so:
```sql
CREATE TABLE topic (
    name String,
    address String
) ENGINE = Kafka('localhost:9092', 'topic', 'group1', 'JSONEachRow');

CREATE TABLE people (
    name String,
    address String
) ENGINE = Log();

CREATE MATERIALIZED VIEW consumer TO people AS SELECT * FROM topic;
```

Ideally, I'd like a `message String` field in `people` which would store the entire Kafka message received. Is there a way to achieve this?

**Comment by UnamedRus** [comment]
https://kb.altinity.com/altinity-kb-integrations/altinity-kb-kafka/error-handling/#after-216

You can check ` _raw_message` virtual column

**Comment by johnnyleitrim** [comment]
Unfortunately, that didn't work for me:
```sql
CREATE TABLE topic (
    name String,
    address String
) ENGINE = Kafka('localhost:9092', 'topic', 'group1', 'JSONEachRow');

CREATE TABLE people (
    name String,
    address String,
    raw String
) ENGINE = Log();

CREATE MATERIALIZED VIEW consumer TO people AS SELECT name, address, _raw_message AS raw FROM topic;
```

I get the following error when trying to create the materialized view:
```
0 rows in set. Elapsed: 0.004 sec. 

Received exception from server (version 22.1.3):
Code: 47. DB::Exception: Received from localhost:9000. DB::Exception: Missing columns: '_raw_message' while processing query: 'SELECT name, address, _raw_message AS raw FROM default.topic', required columns: 'name' 'address' '_raw_message', maybe you meant: ['name','address']. (UNKNOWN_IDENTIFIER)
```

**Comment by johnnyleitrim** [comment]
It looks like the virtual `_raw_message` field is empty until there was an error processing the kafka message, so I don't think there's a way to achieve what I'm looking for as I want to store the raw message in all cases.

**Comment by UnamedRus** [comment]
> It looks like the virtual _raw_message field is empty until there was an error processing the kafka message, so I don't think there's a way to achieve what I'm looking for as I want to store the raw message in all cases.

I think, you can make a FR for populating `_raw_message` column always.

**Comment by den-crane** [comment]
How about format JSONAsString or RawBLOB  instead of JSONEachRow ?

**Comment by den-crane** [comment]
https://clickhouse.com/docs/en/interfaces/formats/#rawblob

**Comment by den-crane** [comment]
https://kb.altinity.com/altinity-kb-schema-design/altinity-kb-jsonasstring-and-mat.-view-as-json-parser/

**Comment by johnnyleitrim** [comment]
Yes, using `JSONAsString` allowed me to get the raw message
