### ISSUE TITLE
[RFC] Better structure with change log 

### ISSUE THREAD

**Issue by cnmade** [ClickHouse/ClickHouse#34002]
The current change log not very good structure , I have a well print plan for rebuild change log by version and last update date display as tree list. 
Following is just a small example

----
* v1 [2018-07-12]
    * v1.1 [2018-07-12]
        * v1.1.54394 [2018-07-12]
* v18 [2018-12-15]
    * v18.1 [2018-07-20]
        * v18.1.0 [2018-07-20]
    * v18.4 [2018-07-28]
        * v18.4.0 [2018-07-28]
    * v18.5 [2018-07-31]
        * v18.5.1 [2018-07-31]
 * v19 [2020-07-20]
     * v19.17 [2020-07-20]
         * v19.17.10.1 [2020-07-20]
 * v20 [2021-03-02]
     * v20.12 [2021-03-02]
         * v20.12.8.5 [2021-03-02]
 * v21 [2021-12-10]
     * v21.12 [2021-12-10]
         * v21.12.4.1 [2021-12-10]
 * v22 [2022-01-18]
     * v22.1 [2022-01-18]
         * v22.1.3.7 [2022-01-18]

----

Why tree list to display change logs. 

For a large and long term project. we need to document the right behaviour of the special version changes.

We know the different of the two version. to read the document and change log ,we can know if we can safe upgrade to next version.

Or we can know from the change log , which version is release in which time.

The tree list view make every changes good structure, it always easy to find the right verison in the prefix version number. 

for example , the v18.5.1 will under   v18.5 node, and the v18.5 under the v18 node.

by lookup the tree list, you can get information you need.

The laste update date will tell us , is the main version too far away from us. should we pick a newer version to keep it catch up the latest features.

**Comment by alexey-milovidov** [comment]
We don't publish changelog for patch releases: 
22.1.x where x is changing.

And there is no particular meaning of the first number: 22 or 21.

We also separate changelog by years to different pages.

**Comment by alexey-milovidov** [comment]
It is better to not pay any efforts restructuring the old changelogs.
