### ISSUE TITLE
Postgres odbc connection issues after upgrade to 21.12.3.32

### ISSUE THREAD

**Issue by namepunk** [ClickHouse/ClickHouse#34004]
After upgrade clickhouse server from  20.9.2.20 to 21.12.3.32 i have issues with postgres odbc connection.
Periodically, after 2-3 days of work, connection to postgres is lost, i see error

> Received exception from server (version 21.12.3):
Code: 86. DB::Exception: Received from node1:9000. DB::Exception: Received error from remote server /?connection_string=DSN%3Dinga_pg&max_block_size=65505. HTTP status code: 500 Internal Server Error, body: �std::exception. Code: 1001, type: nanodbc::database_error, e.what() = ../contrib/nanodbc/nanodbc/nanodbc.cpp:1626: 4270: no connection to the server
;
no connection to the server
 ,. (RECEIVED_ERROR_FROM_REMOTE_IO_SERVER)

After server restart error disapeared.
If i check connection from console all is ok

> isql -v inga_pg
+---------------------------------------+
| Connected!                            |
|                                       |
| sql-statement                         |
| help [tablename]                      |
| quit                                  |
|                                       |
+---------------------------------------+

if i check from clickhouse i get an error until I restart the server.

**Comment by kssenii** [comment]
So the error persist if you retry the query and only restart helps?

**Comment by namepunk** [comment]
Yes exactly. Requests do not work until server restart

**Comment by kssenii** [comment]
You can use setting `odbc_bridge_use_connection_pooling` to resolve the problem.
In fact connection update work but there are some cases when psqlodbc driver shows incorrect error codes. One of such cases has a workaround in our code: https://github.com/ClickHouse/ClickHouse/blob/812ab9bd6b16649c86b09a8e5993860c70765691/programs/odbc-bridge/ODBCPooledConnectionFactory.h#L105-L110
From your error message it is not visible which pg state was returned, so not clear which case need to cover. I updated error message logging (https://github.com/ClickHouse/ClickHouse/pull/38364), so it will be possible to check in the future.
