### ISSUE TITLE
Do we consider add alignment for `ThreadStatus`

### ISSUE THREAD

**Issue by taiyang-li** [ClickHouse/ClickHouse#34009]
Do we consider add alignment for class `ThreadStatus` like this to reduce false sharing of cpu cache between multiple threads ? 
``` cpp
class __attribute__((__aligned__(64))) ThreadStatus : public boost::noncopyable
```

**Comment by alexey-milovidov** [comment]
It is already allocated on thread stack, so no issue with false sharing should exist, as thread stacks are already far away of each other.

**Comment by taiyang-li** [comment]
Thanks for your explaination. @alexey-milovidov
