### ISSUE TITLE
when output data is large how to read

### ISSUE THREAD

**Issue by AnberLu** [ClickHouse/ClickHouse#34003]
When the output data is particularly large, how to read while writing，like  buffer Stream

**Comment by den-crane** [comment]
You need to clarify your question.

>how to read while writing

What does it mean? Writing of fetched data in your client application?

What library / language do you use?

**Comment by alexey-milovidov** [comment]
ClickHouse is returning data in streaming fashion and you can process it while reading without allocating large amount of memory.

Some 3rd-party client drivers and tools may still buffer the result, but it is a problem of these tools, not ClickHouse itself.
