### ISSUE TITLE
Support for Mac M1 core

### ISSUE THREAD

**Issue by Vetlin** [ClickHouse/ClickHouse#34015]
Hello!

Trying to use your docker image https://hub.docker.com/r/yandex/clickhouse-server on M1 Mac and getting this error:
`runtime: failed to create new OS thread (have 2 already; errno=22). fatal error: newosproc`. I'm sure that this is because of M1 core, cause I runned the same code on Mac with Intel core and it worked.

So, can you please add support for M1 core?

**Comment by den-crane** [comment]
But images marked OS/ARCH = linux/amd64

There is no official arm docker images yet.

Try unofficial https://hub.docker.com/r/altinity/clickhouse-server/tags?page=1&name=arm

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/22222

**Comment by DingChuanV** [comment]
what to do? in a hurry
