### ISSUE TITLE
Distributed table insert validation

### ISSUE THREAD

**Issue by lapkofear** [ClickHouse/ClickHouse#3401]
Insert into distributed table with duplicated columns doesn't cause validation error. After that all inserts into this table stuck. A lot exceptions occurred on CH server when distributed table scheduler tries to insert data into original tables. Example of the wrong insert: 
INSERT INTO `default`.table_dist (column_1, column_1) VALUES(1, 1);

**Comment by alexey-milovidov** [comment]
Need to check if it's relevant for version 20.10.
