### ISSUE TITLE
system.metrics name='Query' and system.metric_log CurrentMetric_Query gauge doesn't calculate anymore

### ISSUE THREAD

**Issue by Slach** [ClickHouse/ClickHouse#34014]
**Describe what's wrong**
Query metric doesn't calculate anymore
```sql
SELECT * FROM system.metrics WHERE metric='Query'
```
always return value=0 

```sql
SELECT event_time, CurrentMetrics_Query FROM system.metric_log WHERE CurrentMetrics_Query>0
```
always return 0 rows

I check these queries during run following script in separate terminal
```bash
clickhouse-client -q "SELECT sleepEachRow(1),now() FROM numbers(60)"
```

**Does it reproduce on recent release?**
Yes it reproduce on 22.1 and 21.12
And doesn't reproduce on 21.11

**Comment by ekonkov** [comment]
I can confirm it reproduce on 22.12
and doesn't reproduce on 21.8.
