### ISSUE TITLE
Max length of IPv6 text representation

### ISSUE THREAD

**Issue by dearfl** [ClickHouse/ClickHouse#34022]
https://github.com/ClickHouse/ClickHouse/blob/289a51b61d636e9b2ac98dc912d4d1894cc31e2e/src/Common/formatIPv6.h#L14

According to this [link](https://stackoverflow.com/questions/166132/maximum-length-of-the-textual-representation-of-an-ipv6-address), the Maxiumn length of IPv6 textual representation should be 45.

**Comment by genzgd** [comment]
The 45 character size only applies to an "expanded" IPv4 representation such as `0000:0000:0000:0000:0000:ffff:123.123.123.123`.  ClickHouse will always use the shorthand representation of `::ffff:123.123.123.123` for display.   Since toIPv6 correctly parses the expanded version:

```
SELECT toIPv6('0000:0000:0000:0000:0000:ffff:123.123.123.123')

┌─toIPv6('0000:0000:0000:0000:0000:ffff:123.123.123.123')─┐
│ ::ffff:123.123.123.123                                  │
└─────────────────────────────────────────────────────────┘
```
it does not seem using 39 should cause an issue.  Is this creating some exception or unexpected behavior?

**Comment by dearfl** [comment]
no, I just came cross this code and felt a little strange, since INET6_ADDRSTRLEN is defined as 46 in Linux.

**Comment by genzgd** [comment]
I would assume the Linux value is intended to avoid any possible overflow in edge cases where the unnecessary expanded format is used.  We are not aware of any such usage in ClickHouse currently.

**Comment by alexey-milovidov** [comment]
@genzgd Maybe can add a comment in code to avoid confusion?

**Comment by dearfl** [comment]
ok, I did a bit testing and found this:

```sql
CREATE TABLE test(ip IPv6) ENGINE MergeTree() ORDER BY tuple()
```

then

```sql
INSERT INTO test(ip) VALUES ('0000:0000:0000:0000:0000:ffff:123.123.123.123')
```

will throw DB::Exception: Invalid IPv6 value.

**Comment by dearfl** [comment]
another example:

```sql
INSERT INTO test VALUES ('0000:0000:0000:0000:0000:ffff:1.12.12.12')
```

will success, but 

```sql
select * from test

┌─ip───────────────┐
│ ::ffff:1.12.12.1 │
└──────────────────┘
```

**Comment by genzgd** [comment]
Does that occur on a recent ClickHouse version?  20.9 is quite old.
