### ISSUE TITLE
Data duplication in `PART MOVE TO SHARD` feature

### ISSUE THREAD

**Issue by AlmostIvanSidorov** [ClickHouse/ClickHouse#34089]
I wrote a test for  `PART MOVE TO SHARD` runs multiple times and received some unexpected behavior.

**Test description:**
1) Create a table
2) Make 2 rows insert on one shard and 1 row insert on some other
3) Stop Merges
4) Create Distributed table
5) Receive part UUID
6) Move this part multiple times
7) Make concurrent check on the number of rows

**How to reproduce**
1) CREATE TABLE IF NOT EXISTS {table_name} on CLUSTER {cluster_name}
                                                (v UInt64) "
                                                ENGINE = {table_engine}('/clickhouse/tables/replicated/{shard}/{table_name}', '{replica}') 
                                                ORDER BY tuple() 
                                                SETTINGS assign_part_uuids=1,
                                                part_moves_between_shards_enable=1,
                                                part_moves_between_shards_delay_seconds=2;

2) INSERT INTO {table_name} VALUES ({value}) - 2 rows  on one shard and 1 row on some other

3) SYSTEM STOP MERGES {table_name} - on all nodes

4) CREATE TABLE IF NOT EXISTS {table_name_d} as {table_name} 
                                                    ENGINE = Distributed({cluster_name}, currentDatabase(), {table_name})
5) SELECT uuid FROM system.parts where name = 'all_0_0_0'

6) SELECT name FROM system.parts where uuid = '{part_uuid}'
    ALTER TABLE {table_name} MOVE PART name TO SHARD '/clickhouse/tables/replicated/{shard1}/{table_name}' - multiple times

7) select count() from {table_name_d}

* ClickHouse server version to use
22.1.2
* Queries to run that lead to an unexpected result
select count() from {table_name_d}

Result: 4

**Expected behavior**
Result: 3

**Additional information**
If make retries some time result becomes correct. The test gives the correct result if put part_moves_between_shards_delay_seconds=0.

**Comment by alexey-milovidov** [comment]
CC @nvartolomei

**Comment by alexey-milovidov** [comment]
This experimental feature is going to be removed if this issue will not be addressed in 6 months (before July 2022).

**Comment by nvartolomei** [comment]
@AlmostIvanSidorov before trying to reproduce this may I ask if have you enabled the `allow_experimental_query_deduplication` setting? @alexey-milovidov we shall enable this by default and remove obsolete `experimental_query_deduplication_send_all_part_uuids`.

**Comment by AlmostIvanSidorov** [comment]
@nvartolomei in my tests I used 3 cases:

**Comment by AlmostIvanSidorov** [comment]
@nvartolomei in my tests I used 3 cases for check:
1) select * from {table_name} ORDER BY v ASC SETTINGS allow_experimental_query_deduplication = 1 FORMAT TSV
seems this works correct (I didn't catch duplication in my tests)

2) select * from {table_name} ORDER BY v ASC FORMAT TSV -  i received visual confirm of data duplication.

3)But select count() from {table_name} SETTINGS allow_experimental_query_deduplication = 1 even with allow_experimental_query_deduplication still shows wrong result.

**Comment by nvartolomei** [comment]
@AlmostIvanSidorov can you also try with `optimize_trivial_count = false`?

**Comment by AlmostIvanSidorov** [comment]
@nvartolomei  As I understood optimize_trivial_count_query* )

`select count() from {table_name} SETTINGS allow_experimental_query_deduplication = 1,  optimize_trivial_count_query = false`

Passed test x3 times, seems to work as it should.

**Comment by compasses** [comment]
@nvartolomei Hi, I want to make clear about some confusions here.
1. This work only focus on random sharding? I have some ideas to make it support partition sharding, like do the part split at the source node, and distributed the splited parts to others shard, do you think it's workable?
2. Seems the part move between shards not operate in cluster scaling process, but it's just a balancing tool to do rebalance data, but in reality may need a solution to do balancing data during cluster scaling.

**Comment by qoega** [comment]
Test fails sometimes in CI #45398
