### ISSUE TITLE
maxsplit argument for splitByChar

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#34081]
Similar to https://docs.python.org/3/library/stdtypes.html?highlight=split#str.split 

Use case:
```
key="value_with_equal=_sign_in it"
```

Expected result:

```
SELECT splitByChar(s, '=', 1)
['key', '"value_with_equal=_sign_in it"']
```

**Comment by taiyang-li** [comment]
I'd like to take this issue if you like.

**Comment by taiyang-li** [comment]
Done: https://github.com/ClickHouse/ClickHouse/pull/34140
