### ISSUE TITLE
Error inserting data

### ISSUE THREAD

**Issue by linruoma** [ClickHouse/ClickHouse#34082]
I build a table like this

`CREATE table test1(
`id` Int64,

`head.sha` String,

`head.repo.owner.gravatar_id` String,

`head.repo.is_template` Int64,

`head.repo.topics` Array(String),

`base.repo.topics` Array(String)
)
Engine=MergeTree()
order by `id`;`

If I insert data like this
`insert into test1 (`base.repo.topics`) values(['raw','xxx'])`
It can run successfully

If I insert data like this
`insert into test1 (`head.repo.topics`) values(['raw','xxx'])`
It will produce the following errors
DB::Exception: Bad cast from type DB::DataTypeString to DB::DataTypeArray. 

Why does the program report an error？

**Comment by den-crane** [comment]
`.` - dot is a special character in column names, reserved for Nested Arrays. 

You should never use `.` dots if you don't use `Nested`.

Replace `.` with `_`

```sql
CREATE table test1( id Int64,
`head_sha` String,
`head_repo_owner_gravatar_id` String,
`head_repo_is_template` Int64,
`head_repo_topics` Array(String),
`base_repo_topics` Array(String)
)
Engine=MergeTree()
order by id;

insert into test1 (base_repo_topics) values(['raw','xxx'])
insert into test1 (head_repo_topics) values(['raw','xxx'])

select * from test1;
┌─id─┬─head_sha─┬─head_repo_owner_gravatar_id─┬─head_repo_is_template─┬─head_repo_topics─┬─base_repo_topics─┐
│  0 │          │                             │                     0 │ ['raw','xxx']    │ []               │
└────┴──────────┴─────────────────────────────┴───────────────────────┴──────────────────┴──────────────────┘
┌─id─┬─head_sha─┬─head_repo_owner_gravatar_id─┬─head_repo_is_template─┬─head_repo_topics─┬─base_repo_topics─┐
│  0 │          │                             │                     0 │ []               │ ['raw','xxx']    │
└────┴──────────┴─────────────────────────────┴───────────────────────┴──────────────────┴──────────────────┘
```
