### ISSUE TITLE
unknown serialization kind on distributed table

### ISSUE THREAD

**Issue by Tiaonmmn** [ClickHouse/ClickHouse#34091]
**Describe the unexpected behaviour**
After upgraded to ClickHouse 22.1.3 revision 54455,when using distributed table to insert data,errors occured in log.

**How to reproduce**
Version:ClickHouse 22.1.3.7

**Expected behavior**
After upgraded to ClickHouse 22.1.3 revision 54455,when using distributed table to insert data,errors occured in log.
Cluster's ClickHouse version are the same,22.1.3.7.

**Error message and/or stacktrace**
2022.01.28 18:39:41.098174 [ 80700 ] {} <Error> XXX.YYYY.DirectoryMonitor: Code: 246. DB::Exception: Unknown serialization kind 99: While sending /clickhouse/store/4db/4db5491f-555c-4c9d-8db5-491f555cbc9d/shard7_replica1/1571210.bin. (CORRUPTED_DATA), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa82d07a in /usr/bin/clickhouse
1. DB::SerializationInfo::deserializeFromKindsBinary(DB::ReadBuffer&) @ 0x1326c09c in /usr/bin/clickhouse
2. DB::NativeReader::read() @ 0x14826428 in /usr/bin/clickhouse
3. ? @ 0x14195913 in /usr/bin/clickhouse
4. DB::StorageDistributedDirectoryMonitor::processFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x1419391a in /usr/bin/clickhouse
5. DB::StorageDistributedDirectoryMonitor::run() @ 0x1418fa78 in /usr/bin/clickhouse
6. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x12f8470e in /usr/bin/clickhouse
7. DB::BackgroundSchedulePool::threadFunction() @ 0x12f870a7 in /usr/bin/clickhouse
8. ? @ 0x12f88170 in /usr/bin/clickhouse
9. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa86f4b7 in /usr/bin/clickhouse
10. ? @ 0xa872ebd in /usr/bin/clickhouse
11. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
12. __clone @ 0xfeb0d in /usr/lib64/libc-2.17.so
 (version 22.1.3.7 (official build))

**Comment by CurtizJ** [comment]
Please, can you share the schema of tables?

**Comment by shashankkoppar** [comment]
We are also facing similar issue after upgrading to 22.1.3.7

**Comment by Tiaonmmn** [comment]
create table XXX.YYYY(
BEGINTIME DateTime,
ABCD String,
DEFG String,
Flag LowCardinality(String),
QWER String,
TYUI Int32,
FGHJ String,
ZXCV String
)
engine =Distributed('example','blah','blah_base',rand());

create table blah.blah_base(
BEGINTIME DateTime,
ABCD String,
DEFG String,
Flag LowCardinality(String),
QWER String,
TYUI Int32,
FGHJ String,
ZXCV String
)
engine=MergeTree PARTITION BY toYYYYMM(BEGINTIME)
ORDER BY (ABCD,DEFG)
SETTINGS index_granularity=8192;

Besides,unknown serialization kind include 99,85,117.

**Comment by CurtizJ** [comment]
I reproduced it with the following scenario: after inserts on old version there should remain files with unflushed to shards inserted data. Then after upgrade data cannot be read back and sent to shards, because version of Native format (in which temporary  data is written) is accounted incorrectly. The Native protocol was changed in 22.1 and its version was incremented. I'll try to fix it soon.

If you want to upgrade now, then you can do the following:
1. Rollback to old version. 
2. Find directory `broken` in the directory with temporary inserted data of distributed table and move all files (if there exists some) from it back to the directory with temporary inserted data.
3. Stop inserts to distributed table.
4. Run `SYSTEM FLUSH DISTRIBUTED ...` query.
5. Upgrade to 22.1

**Comment by Tiaonmmn** [comment]
I downgrade the insert server to 21.12.9,and it seems you can transfer data from old version server to new version server.
Waiting for new release.

**Comment by shashankkoppar** [comment]
Hey @Tiaonmmn , i dont see any clickhouse version with 21.12.9 in here https://repo.yandex.ru/clickhouse/rpm/stable/x86_64/ 
could u tell me which exact version did u use?

**Comment by shashankkoppar** [comment]
Hey @CurtizJ , I tried to follow ur steps, but when i try to flush distributed tables it points some bin file which is not in broken directory 
How do u suggest to fix this issue?

**Comment by Tiaonmmn** [comment]
> Hey @Tiaonmmn , i dont see any clickhouse version with 21.12.9 in here https://repo.yandex.ru/clickhouse/rpm/stable/x86_64/ could u tell me which exact version did u use?

https://repo.clickhouse.com/rpm/stable/x86_64/clickhouse-common-static-21.9.7.2-2.x86_64.rpm

**Comment by Tiaonmmn** [comment]
> Hey @Tiaonmmn , i dont see any clickhouse version with 21.12.9 in here https://repo.yandex.ru/clickhouse/rpm/stable/x86_64/ could u tell me which exact version did u use?

Sorry,it's 21.12.4.I wrote wrong version number.
