### ISSUE TITLE
Consider checking out bitsetsort performance

### ISSUE THREAD

**Issue by chhetripradeep** [ClickHouse/ClickHouse#34115]
[BitSetSort](https://github.com/minjaehwang/bitsetsort) claims to perform better than pdqsort and std::sort for randomized inputs. I thought to open this issue to see if we can benefit from it.

**Comment by den-crane** [comment]
https://probablydance.com/2017/01/17/faster-sorting-algorithm-part-2/ https://habr.com/ru/company/wunderfund/blog/599249/

**Comment by alexey-milovidov** [comment]
@chhetripradeep A bug was found in this library by the run of ClickHouse test suite:
https://github.com/minjaehwang/bitsetsort/pull/3

**Comment by alexey-milovidov** [comment]
The library is unsupported: https://github.com/minjaehwang/bitsetsort/graphs/contributors

**Comment by alexey-milovidov** [comment]
Maybe we need to use the version that is proposed to libc++?
https://reviews.llvm.org/D93233#3195993

**Comment by alexey-milovidov** [comment]
@kitaisreal pointed out that LLVM's version also contains the same bug.

**Comment by chhetripradeep** [comment]
Thank you @alexey-milovidov @kitaisreal for doing the evaluation and being so fast. I am keeping an eye on the PR. I am curious if we have some report generated by CI jobs for performance related PRs comparing before vs after.

**Comment by alexey-milovidov** [comment]
Yes, we do. Although these report require some care to be taken during reading...

**Comment by danlark1** [comment]
> @kitaisreal pointed out that LLVM's version also contains the same bug.

I don't think so
![image](https://user-images.githubusercontent.com/15173761/152636961-293ab265-549f-43e2-b3f3-30f6b7127059.png)

**Comment by kitaisreal** [comment]
Initially we did not check diff, but thought that patch if from same author and is just mirror of GitHub repository.
After double check I write to @alexey-milovidov, that it seems that there are no same bug in LLVM patch, probably comment was not updated.
Need to test LLVM version, maybe there are some other changes, maybe some performance improvements.
Also it is better to close, mark experimental, or add fixes into GitHub repository, no one will check diff into LLVM,  https://github.com/minjaehwang/bitsetsort.

CC: @chhetripradeep, @danlark1.

**Comment by alexey-milovidov** [comment]
So, the results are questionable
https://s3.amazonaws.com/clickhouse-test-reports/34175/45fa68b4a890b1bda979cadfbd8968422fcecd9d/performance_comparison__actions__[2/4]/report.html
https://s3.amazonaws.com/clickhouse-test-reports/34175/45fa68b4a890b1bda979cadfbd8968422fcecd9d/performance_comparison__actions__[1/4]/report.html

but LLVM version appears to be better, and also @danlark1 said that there are some other optimization opportunities.
