### ISSUE TITLE
USE documentation page is in Chinese instead of English

### ISSUE THREAD

**Issue by thomas-imi** [ClickHouse/ClickHouse#34127]
**Describe the issue**
The [use.md.](https://github.com/ClickHouse/ClickHouse/blob/master/docs/en/sql-reference/statements/use.md) English documentation page has been overwritten by a Chinese translation.

**Comment by alexey-milovidov** [comment]
Fixed https://github.com/ClickHouse/ClickHouse/commit/379f8d3d7e531840503456c84cf000c14df578b0
