### ISSUE TITLE
LDAP: authentication with configured role mapping fails on a cluster with a secret

### ISSUE THREAD

**Issue by traceon** [ClickHouse/ClickHouse#34130]
When ClickHouse server is configured as a part of a cluster with a secret, and there is an LDAP user directory with a role mapping, authentications for users from that directory fails.

If the `<secret>` is removed from the cluster config, or role mapping is disabled for LDAP user directory, users are authenticated successfully.

**Comment by alexey-milovidov** [comment]
@azat is the author of the `<secret>` feature.

**Comment by azat** [comment]
@traceon can you write an integration test please? That will help a lot.

**Comment by traceon** [comment]
@azat Yes, that's the plan.

@vzakaznikov can we write a test for this case upfront, in TestFlows? This will really help to debug/implement this issue.

**Comment by vzakaznikov** [comment]
Yes, I'm working on developing extra tests that combine LDAP + secret.

**Comment by vzakaznikov** [comment]
@traceon, tests have been added per your request in (https://github.com/ClickHouse/ClickHouse/pull/34513).

**Comment by traceon** [comment]
@azat have you had a chance to reproduce using the tests above?

**Comment by azat** [comment]
@traceon the issue is clear, but I haven't had a chance to look into it yet, if this is urgent for you and you want to fix this by yourself, please go ahead!

**Comment by Enmk** [comment]
started working on it

**Comment by alexey-milovidov** [comment]
> started working on it

Not finished working on it.

**Comment by zvonand** [comment]
> Not finished working on it.

Started finishing working on this
