### ISSUE TITLE
[Question] Is it possible to build a funnel and get all events between steps as well?

### ISSUE THREAD

**Issue by artfabrique** [ClickHouse/ClickHouse#3413]
I have a challenging task and i'm not sure that it's even possible with clickhouse: Find not only the funnel steps occurrences but all events between the funnel steps as well.
Here is the scheme I need to achieve

![clickhouse algo - page 1](https://user-images.githubusercontent.com/4455555/47122500-bd18d180-d27f-11e8-85b9-1341c41ae209.jpeg)

How the events are stored initially - does not matter (can be changed)
We have around 2.7kkk events/month
Now I have a query that runs around 3 minutes on a small sample of 75kk
Maybe someone can advise a direction to research? (I'll provide current query a bit later)

I've looked through this already: #2096

**Comment by sundy-li** [comment]
This is a more complex funnel demand than windowFunnel , but I am looking forward to see your current query in solving this problem.

**Comment by blinkov** [comment]
@artfabrique can you show this 3-minutes-long query?

**Comment by panyushkins** [comment]
> @artfabrique can you show this 3-minutes-long query?

Hello! 

`SELECT

    count() as trials,
    uniq(uid) as users,  
    n_step, 
    step

FROM (
    WITH
    
        groupArray(_interface) as event_names,
        groupArray(toInt32(date)) as event_dates,
        arrayJoin(arrayFilter((i, x) -> x = '""" + first_step + """', arrayEnumerate(event_names), event_names)) AS start_index_journey,
        arraySlice(event_names, start_index_journey+1) as from_start_step_1,
        indexOf(from_start_step_1, '""" + first_step + """') as end_index,
        
        arraySlice(from_start_step_1, 1, if(end_index != 0, end_index-1, toInt32(length(from_start_step_1)))) as journey,
        if(end_index != 0, arraySlice(event_dates, start_index_journey+1, end_index-1), arraySlice(event_dates, start_index_journey+1)) as dates_journey,
        
        indexOf(journey, '""" + second_step + """') as start_index_step_2,
        if(start_index_step_2 != 0, dates_journey[start_index_step_2]-event_dates[start_index_journey], -1) as step_1_2_time,
        if(step_1_2_time < """+ max_time + """, journey, emptyArrayString()) as step1_checked,
        if(start_index_step_2 != 0, arraySlice(step1_checked, 1, start_index_step_2-1), emptyArrayString()) as step_1,
        if(start_index_step_2 != 0, arraySlice(step1_checked, start_index_step_2+1), emptyArrayString()) as from_start_step_2,
        
        indexOf(from_start_step_2, '""" + third_step + """') as start_index_step_3,
        if(start_index_step_3 != 0, dates_journey[start_index_step_2 + start_index_step_3] - dates_journey[start_index_step_2], -1) as step_2_3_time,
        if(step_2_3_time < """+ max_time + """, from_start_step_2, emptyArrayString()) as step2_checked,
        if(start_index_step_3 != 0, arraySlice(step2_checked, 1, start_index_step_3-1), emptyArrayString()) as step_2
        
    SELECT uid,
        
        
        [step_1, step_2] as steps,
        arrayJoin(arrayEnumerate(steps)) as n_step,
        steps[n_step] as step_array,
        arrayJoin(step_array) as step

              
      from (
          select uid, 
              _interface, 
              date 
          from test_events
          where date > '2018-10-10 23:30:00' and date < '2018-10-10 23:59:59'
          order by date)
      group by uid)
      
GROUP BY n_step, step`

Result: https://service.crazypanda.ru/v/monosnap/2018-10-18-17-10-20-0kx4n.png
Select * from test_events: https://service.crazypanda.ru/v/monosnap/2018-10-18-17-11-34-emaii.png

**Comment by artfabrique** [comment]
@blinkov above is the query that we are using.

**Comment by blinkov** [comment]
@artfabrique it looks roughly as I expected, but frankly speaking it's too complicated to debug via public comments without access to real ClickHouse cluster. Does it look CPU bound? If it does, what do you see in profiler? What kind of hardware do you use for this test?

**Comment by panyushkins** [comment]
> @artfabrique it looks roughly as I expected, but frankly speaking it's too complicated to debug via public comments without access to real ClickHouse cluster. Does it look CPU bound? If it does, what do you see in profiler? What kind of hardware do you use for this test?

I will answer at Monday, when I got this information from our developers. 

Also, we tried another methodic: firstly we finding all indexes and after making only one slice per one hard step with soft steps (step between hard step). I use this query:

    SELECT uid,
        
        groupArray(_interface) as event_names,
        groupArray(toInt32(date)) as event_dates,
        arrayJoin(arrayFilter((i, x) -> x = '""" + first_step + """', arrayEnumerate(event_names), event_names)) AS start_index_journey,
        arrayFilter((i, x) -> x = '""" + "game" + """' and i > start_index_journey, arrayEnumerate(event_names), event_names)[1] as i_step1,
        arrayFilter((i, x) -> x = '""" + "select_another" + """' and i > i_step1, arrayEnumerate(event_names), event_names)[1] as i_step_2,
        arraySlice(event_names, start_index_journey+1) as from_start_step_1,
        indexOf(from_start_step_1, '""" + first_step + """') as end_index,
        
        arraySlice(from_start_step_1, 1, if(end_index != 0, end_index-1, toInt32(length(from_start_step_1)))) as journey,
        if(end_index != 0, arraySlice(event_dates, start_index_journey+1, end_index-1), arraySlice(event_dates, start_index_journey+1)) as dates_journey
        
              
      from test_events
      group by uid

But! I was suprised, but this query is much more complicated and using much more RAM.

**Comment by artfabrique** [comment]
>  it's too complicated to debug via public comments without access to real ClickHouse cluster
Yeah, I know :( I thought maybe there are some fundamental mistakes it the query and maybe somebody will have an idea of some radically different approach. For example, pre-generate something when we collect data etc.

**Comment by blinkov** [comment]
@artfabrique is this issue still relevant?

**Comment by artfabrique** [comment]
Yes! We stuck completely.
----

*Alexander Vinogradov*

tel. *+7 (926) 064-14-42*
skype: *artfabrique_ru*

**Comment by artfabrique** [comment]
@blinkov also there is one more condition that seems not feasible on using present-day tech.
Here is a real usecase scenario:

Imagine you've got this "soft funnel" and showed it to user

```
1. A
1.1. X: occurs in 70% of transitions, 700 times per transition A>B
1.2. Y: occurs in 20% of transitions, 200 times per transition A>B
1.3. Z: occurs in 10% of transitions, 100 times per transition A>B
2. B
2.1. F: occurs in 70% of transitions, 700 times per transition A>B
2.2. G: occurs in 20% of transitions, 200 times per transition A>B
2.3. H: occurs in 9% of transitions, 90 times per transition A>B
2.3. A: occurs in 1% of transitions, 10 times per transition A>B
3. C | D | F (C or D or F)
```

So user should be able to set multiple events as a final funnel step. Basically this is simply multiple funnels (seems to be).

Now the user(analyst) wants to be able to pick one of the outcomes, for example D and see this:

```
1. A
1.1. X: occurs in 70% of transitions, 700 times per transition A>B
1.2. Y: occurs in 20% of transitions, 200 times per transition A>B
1.3. Z: occurs in 10% of transitions, 100 times per transition A>B
2. B
2.1. F: occurs in 70%**(1% when ends with D)** of transitions, 700 times per transition A>B
2.2. G: occurs in 20%**(90% when ends with D)** of transitions, 200 times per transition A>B
2.3. H: occurs in 9%**(5% when ends with D)** of transitions, 90 times per transition A>B
2.3. A: occurs in 1%**(4% when ends with D)** of transitions, 10 times per transition A>B
3. C | **D** | F 
```

Now analyst can see that all users that ended up with **D**  tend to perform "G" during transition from Step2 to Step3. Now the product team can fix that **G** action, for example.

It would be super cool i analyst could pick not only finite funnel state BUT the specific event inside a soft sunnel segment. E.G. pick **H** and see How often **Y** happened in pref steps.

**Comment by blinkov** [comment]
@artfabrique, do you have any further questions?

**Comment by blinkov** [comment]
Feel free to re-open the issue if it is still relevant.

**Comment by alexey-milovidov** [comment]
@blinkov You did not answer.

**Comment by amirvaza** [comment]
+1

**Comment by compasses** [comment]
Since the query so complicated, maybe a UDF can help ?

**Comment by alexey-milovidov** [comment]
[Scriptable UDFs ](https://clickhouse.com/docs/en/sql-reference/functions/#executable-user-defined-functions)
