### ISSUE TITLE
Should we support `#` for single-line comments in SQL?

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#34138]
Pros:
- very easy to support;
- compatibility with MySQL syntax;
- this #33584 get supported automatically;
- sometimes I write comments starting with `#` by mistake, and will be pleased if it worked;
- simplify creation of "quines".

Cons:
- it may be too bizarre to support all these styles of comments;
- PostgreSQL has [#>](https://www.postgresql.org/docs/14/functions-json.html) and similar operator due their own ugly quirks;
- it may interact worse with `m4` macro preprocessor;

Additional context:
- we can limit support for these comments by requiring whitespace after `#`;
- we can limit support for these comments by requiring it to be at the beginning of the line;

but MySQL supports all variants.

**Comment by aaronstephenkatz** [comment]
Leave this one to me @alexey-milovidov

**Comment by alexey-milovidov** [comment]
Solved.
