### ISSUE TITLE
TO_CHAR (number) / Printf

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#34142]
Users often ask how to format Numbers (Integers /  Floats / Decimals) ( they need to separate thousands by '.,' or format fractions.

I propose to implement either TO_CHAR or c-lang printf.

https://www.postgresql.org/docs/9.6/functions-formatting.html
https://en.wikipedia.org/wiki/Printf_format_string

Personally I prefer Printf, but TO_CHAR is more SQL way, because it exists in other RDBMS.

**Comment by alexey-milovidov** [comment]
This can be implemented as extension for `format` function.

**Comment by jtrosty** [comment]
I'd like to perform this task.  When you say as an extension for format function, where specifically? Looking around the codebase I thought maybe in the writeHelpers in IO.  I look forward to start contributing to open source projects.

**Comment by den-crane** [comment]
There is the format function 

```sql
select format ('somevar = {}, {}', c, 'other var') from (select 'Geeks' as c);
┌─format('somevar = {}, {}', c, 'other var')─┐
│ somevar = Geeks, other var                 │
└────────────────────────────────────────────┘
```

probably it could be extended?

```
select format ('{} : %2d, Portal : %5.2f', 'Geeks', 1, 05.333);
--
Geeks :  1, Portal :  5.33
```

**Comment by den-crane** [comment]
If such arguments are impossible `'Geeks', 1, 05.333`, it could be a tuple `('Geeks', 1, 05.333)`

```
select format ('{} : %2d, Portal : %5.2f', ('Geeks', 1, 05.333) );
--
Geeks :  1, Portal :  5.33
```

**Comment by jtrosty** [comment]
I understand, thank you I'll start work on it.

**Comment by alexey-milovidov** [comment]
@den-crane For consistency reasons, it will be better to use fmt-style substitutions than printf-style.

**Comment by alexey-milovidov** [comment]
By the way, I'm not sure that this task is easy.
It should be implemented by carefully reusing `fmt` library inside our `format` function while carefully keeping the current implementation (fast string substitution) as a shortcut. Also, it should be possible to use `fmt` with zero copies and allocations (some experience in C++ is required). Special handlers for Date, DateTime and Decimal are needed. This makes the task probably in a range of two weeks at least.

**Comment by den-crane** [comment]
> @den-crane For consistency reasons, it will be better to use fmt-style substitutions than printf-style.

Ah, OK.

**Comment by jtrosty** [comment]
I'm still working to understand how the ` format ` function works and am a bit lost.  I am going through the `FormatFactory` and I think the output is then determined by the code in Format.cpp in the programs/format.  
If I'm completely off base do you have some guidance?

**Comment by alexey-milovidov** [comment]
@jtrosty No, it's a different place of code, see `FunctionFormat` and `formatString.cpp` for SQL function `format`.

PS. What you've read is: table formats for data import/export and a program for pretty-printing of SQL queries.

**Comment by den-crane** [comment]
* https://github.com/ClickHouse/ClickHouse/pull/66257

**Comment by den-crane** [comment]
```
SELECT printf('%s %s %.02f', 'Hello', 'World', 2024.123456);

SELECT printf('%s %s %.06f', 'Hello', 'World', 2024.0);

Hello World 2024.12
Hello World 2024.000000
```

https://fiddle.clickhouse.com/13a0b2ca-3bf9-451a-8a0c-0657f8c31a3d
