### ISSUE TITLE
Проблема с "ALTER TABLE ..... ON CLUSTER ... DELETE ..." после обновления (18.14.8)

### ISSUE THREAD

**Issue by guram-vashakidze** [ClickHouse/ClickHouse#3415]
Добрый день. При использовании запроса ALTER TABLE ..... ON CLUSTER ... DELETE ... появилась ошибка: 

`Code: 60, e.displayText() = DB::Exception: There was an error on XX.XX.XX.XX: An error occured before execution: Code: 60, e.displayText() = DB::Exception: Table default.table doesn't exist., e.what() = DB::Exception, e.what() = DB::Exception`

Запрос выполняется через http интерфейс. название БД установлено GET параметром. Данная ошибка появилась после обновления до версии 18.14.8. Т.е. на удаленный хост запрос почему-то теперь стучится в БД по умолчанию, хотя до обновления запрос выполнялся.

Есть кластер из двух нод, создана реплецируемая таблица "db.table" (ReplicatedCollapsingMergeTree).
При выполнении на первой ноде указанного выше запроса, через http интерфейс (название БД установлено GET параметром "database=db") появляется ошибка что на второй ноде нет таблицы "default.table".
Хотя если в запросе явно задать ALTER TABLE db.table DELETE WHERE .... то такой запрос отрабатывает без ошибок.

**Comment by 4ertus2** [comment]
Возможно исправлено тут https://github.com/yandex/ClickHouse/pull/3460
