### ISSUE TITLE
`arrayFold` function

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#34155]
See

#21589
#23248
#27270

**Comment by roanhe-ts** [comment]
Hello，i want to pick this up

**Comment by alexey-milovidov** [comment]
Ok, it's yours.

Just to let you know - it's not an easy task.
We have to implement "vertical" application of the folding function to the column with arrays.

1. Filter arrays that contain more than zero elements and pick first elements.
2. Apply a function to the first elements of every arrays.
3. Repeat with (1) and (2) with the second elements and so forth.
4. Now we have columns with the results for 0-element arrays, 1-element arrays, 2-element arrays and so forth. Gather the results from these columns into the final resulting column.

@amosbird Maybe you can help @roanhe-ts with this task?

**Comment by roanhe-ts** [comment]
All right ...., I thought it was an easy task ...
So, is there any time limitation? I will consider the complexity with my capability in case of overdue too much

**Comment by alexey-milovidov** [comment]
No time limitation. You can spend several months if you want :+1: 
It should be doable maybe in a week if someone will help.

**Comment by roanhe-ts** [comment]
> It should be doable maybe in a week if someone will help.

OK, I will try my best.
