### ISSUE TITLE
Unknown column with repeated column identifier

### ISSUE THREAD

**Issue by PHaroZ** [ClickHouse/ClickHouse#34190]
Hi,

I have a strange issue with colum name in select.
tested with 21.10.2.15 and 22.1.3.7

This 2 queries work :
```sql
SELECT 1 AS dummy,t1.dummy
FROM (SELECT dummy FROM system.one) AS t1;
```
```sql
SELECT 1 AS dummy,t1.dummy
FROM (SELECT dummy, 1 FROM system.one) AS t1;
```

but this 2 others failed
```sql
SELECT 1 AS dummy,t1.dummy
FROM (SELECT 1, dummy FROM system.one) AS t1;
```
```sql
SELECT 1 AS dummy,t1.dummy
FROM (SELECT 1, dummy, 1 FROM system.one) AS t1;
```
The error message is 
> Code: 47. DB::Exception: Unknown column: dummy, there are only columns 1, 1_2, 1_2. (UNKNOWN_IDENTIFIER) (version 21.10.2.15 (official build))

Also tested with a MergeTree table instead of the sub-select, result is the same.

And thanks for your work ;)

Note : this is possibly a duplicate of  #14978

**Comment by den-crane** [comment]
it does not work for a long time.


```
SELECT 1 AS dummy,t1.dummy
FROM (SELECT 1, dummy FROM system.one) AS t1;

Received exception from server (version 19.17.10):
Code: 10. DB::Exception: Received from localhost:9000. DB::Exception: Not found column dummy in block. There are only columns: 1.
```

will be solved here https://github.com/ClickHouse/ClickHouse/issues/23194
