### ISSUE TITLE
`file` table function: an option to rename processed files

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#34207]
**Use case**

I process huge amount of files and want to see what files have been already processed and avoid processing them twice if the operation is restarted.

**Describe the solution you'd like**

A setting with some template like `{}.processed` or with regexp and replacement pattern.

It should allow moving files to another directory.
The directories should not be created. Path to destination directory should be checked according to `user_files_path`.

**Comment by kardymonds** [comment]
Implemented (https://github.com/ClickHouse/ClickHouse/pull/49626),
I think we can close issue.
