### ISSUE TITLE
Error log full of ServerErrorHandler: Poco::Exception. Code: 1000, e.code() = 107, Net Exception: Socket is not connected

### ISSUE THREAD

**Issue by simPod** [ClickHouse/ClickHouse#34218]
I've got the error log full of errors like this

```
2022.02.01 10:29:55.659210 [ 341370 ] {} <Error> ServerErrorHandler: Poco::Exception. Code: 1000, e.code() = 107, Net Exception: Socket is not connected, Stack trace (when copying this message, always include the lines below):

0. Poco::Net::NetException::NetException(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x16f242ec in /usr/bin/clickhouse
1. Poco::Net::SocketImpl::error(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x16f36164 in /usr/bin/clickhouse
2. Poco::Net::SocketImpl::peerAddress() @ 0x16f38856 in /usr/bin/clickhouse
3. DB::ReadBufferFromPocoSocket::ReadBufferFromPocoSocket(Poco::Net::Socket&, unsigned long) @ 0x129c87b1 in /usr/bin/clickhouse
4. DB::HTTPServerRequest::HTTPServerRequest(std::__1::shared_ptr<DB::Context const>, DB::HTTPServerResponse&, Poco::Net::HTTPServerSession&) @ 0x13ff7147 in /usr/bin/clickhouse
5. DB::HTTPServerConnection::run() @ 0x13ff5b03 in /usr/bin/clickhouse
6. Poco::Net::TCPServerConnection::start() @ 0x16f3d6af in /usr/bin/clickhouse
7. Poco::Net::TCPServerDispatcher::run() @ 0x16f3fb01 in /usr/bin/clickhouse
8. Poco::PooledThread::run() @ 0x1704e889 in /usr/bin/clickhouse
9. Poco::ThreadImpl::runnableEntry(void*) @ 0x1704bf80 in /usr/bin/clickhouse
10. start_thread @ 0x8ea7 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
11. clone @ 0xfddef in /usr/lib/x86_64-linux-gnu/libc-2.31.so
 (version 21.12.3.32 (official build))
```

1. It's not really visible from the trace what kind of error this is. I have no idea where to look since I don't know what connection fails
2. Any idea what might it be? I have one MergeTree table and inserting into it over http interface. I've disabled clickhouse-keeper since I suspected that might have been the cause but it is not.

**Comment by SaltTan** [comment]
Check what the thread was doing before and after the exception.
Look by the thread number `[ 341370 ]`.

**Comment by socketpair** [comment]
So, what the status ? I'm facing the same problem

**Comment by simPod** [comment]
We still don't really know, so far did not find anything that would help trace the source of the issue.

![image](https://user-images.githubusercontent.com/327717/172331465-1fda3815-b55c-49dd-827b-4d33f00370d2.png)

**Comment by makorne** [comment]
> We always have an error after inserting data, but not on every request

We have too.
```

2023.05.30 05:10:50.029653 [ 897638 ] {} <Error> ServerErrorHandler: Poco::Exception. Code: 1000, e.code() = 107, Net Exception: Socket is not connected, Stack trace (when copying this message, always include the lines below):

0. Poco::Net::SocketImpl::error(int, String const&) @ 0x17c5594b in /usr/bin/clickhouse
1. Poco::Net::SocketImpl::peerAddress() @ 0x17c58196 in /usr/bin/clickhouse
2. DB::HTTPServerRequest::HTTPServerRequest(std::shared_ptr<DB::IHTTPContext>, DB::HTTPServerResponse&, Poco::Net::HTTPServerSession&) @ 0x14cf3e40 in /usr/bin/clickhouse
3. DB::HTTPServerConnection::run() @ 0x14cf27ef in /usr/bin/clickhouse
4. Poco::Net::TCPServerConnection::start() @ 0x17c5cab4 in /usr/bin/clickhouse
5. Poco::Net::TCPServerDispatcher::run() @ 0x17c5dcdb in /usr/bin/clickhouse
6. Poco::PooledThread::run() @ 0x17ddb087 in /usr/bin/clickhouse
7. Poco::ThreadImpl::runnableEntry(void*) @ 0x17dd8abd in /usr/bin/clickhouse
8. start_thread @ 0x7ea7 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
9. clone @ 0xfca2f in /usr/lib/x86_64-linux-gnu/libc-2.31.so
 (version 23.4.2.11 (official build))
2023.05.30 05:10:50.090230 [ 903914 ] {} <Error> ServerErrorHandler: Poco::Exception. Code: 1000, e.code() = 107, Net Exception: Socket is not connected, Stack trace (when copying this message, always include the lines below):

0. Poco::Net::SocketImpl::error(int, String const&) @ 0x17c5594b in /usr/bin/clickhouse
1. Poco::Net::SocketImpl::peerAddress() @ 0x17c58196 in /usr/bin/clickhouse
2. DB::HTTPServerRequest::HTTPServerRequest(std::shared_ptr<DB::IHTTPContext>, DB::HTTPServerResponse&, Poco::Net::HTTPServerSession&) @ 0x14cf3e40 in /usr/bin/clickhouse
3. DB::HTTPServerConnection::run() @ 0x14cf27ef in /usr/bin/clickhouse
4. Poco::Net::TCPServerConnection::start() @ 0x17c5cab4 in /usr/bin/clickhouse
5. Poco::Net::TCPServerDispatcher::run() @ 0x17c5dcdb in /usr/bin/clickhouse
6. Poco::PooledThread::run() @ 0x17ddb087 in /usr/bin/clickhouse
7. Poco::ThreadImpl::runnableEntry(void*) @ 0x17dd8abd in /usr/bin/clickhouse
8. start_thread @ 0x7ea7 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
9. clone @ 0xfca2f in /usr/lib/x86_64-linux-gnu/libc-2.31.so
 (version 23.4.2.11 (official build))
2023.05.30 05:10:50.114752 [ 903914 ] {} <Error> ServerErrorHandler: Poco::Exception. Code: 1000, e.code() = 107, Net Exception: Socket is not connected, Stack trace (when copying this message, always include the lines below):

0. Poco::Net::SocketImpl::error(int, String const&) @ 0x17c5594b in /usr/bin/clickhouse
1. Poco::Net::SocketImpl::peerAddress() @ 0x17c58196 in /usr/bin/clickhouse
2. DB::HTTPServerRequest::HTTPServerRequest(std::shared_ptr<DB::IHTTPContext>, DB::HTTPServerResponse&, Poco::Net::HTTPServerSession&) @ 0x14cf3e40 in /usr/bin/clickhouse
3. DB::HTTPServerConnection::run() @ 0x14cf27ef in /usr/bin/clickhouse
4. Poco::Net::TCPServerConnection::start() @ 0x17c5cab4 in /usr/bin/clickhouse
5. Poco::Net::TCPServerDispatcher::run() @ 0x17c5dcdb in /usr/bin/clickhouse
6. Poco::PooledThread::run() @ 0x17ddb087 in /usr/bin/clickhouse
7. Poco::ThreadImpl::runnableEntry(void*) @ 0x17dd8abd in /usr/bin/clickhouse
8. start_thread @ 0x7ea7 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
9. clone @ 0xfca2f in /usr/lib/x86_64-linux-gnu/libc-2.31.so
 (version 23.4.2.11 (official build))
```

How to solve this?

**Comment by brunis** [comment]
Also seeing the same after upgrading to 24.4.0:
`sentry-self-hosted-clickhouse-1                                    | 2024.04.17 07:44:04.613891 [ 251 ] {} <Error> ServerErrorHandler: Poco::Exception. Code: 1000, e.code() = 107, e.displayText() = Net Exception: Socket is not connected, St                                      ack trace (when copying this message, always include the lines below):
sentry-self-hosted-clickhouse-1                                    |
sentry-self-hosted-clickhouse-1                                    | 0. Poco::Net::SocketImpl::error(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x13c4ee8e in /usr/bin/clickhouse
sentry-self-hosted-clickhouse-1                                    | 1. Poco::Net::SocketImpl::peerAddress() @ 0x13c510d6 in /usr/bin/clickhouse
sentry-self-hosted-clickhouse-1                                    | 2. DB::ReadBufferFromPocoSocket::ReadBufferFromPocoSocket(Poco::Net::Socket&, unsigned long) @ 0x101540cd in /usr/bin/clickhouse
sentry-self-hosted-clickhouse-1                                    | 3. DB::HTTPServerRequest::HTTPServerRequest(std::__1::shared_ptr<DB::Context const>, DB::HTTPServerResponse&, Poco::Net::HTTPServerSession&) @ 0x110e6fd5 in /usr/bin/click                                      house
sentry-self-hosted-clickhouse-1                                    | 4. DB::HTTPServerConnection::run() @ 0x110e5d6e in /usr/bin/clickhouse
sentry-self-hosted-clickhouse-1                                    | 5. Poco::Net::TCPServerConnection::start() @ 0x13c5614f in /usr/bin/clickhouse
sentry-self-hosted-clickhouse-1                                    | 6. Poco::Net::TCPServerDispatcher::run() @ 0x13c57bda in /usr/bin/clickhouse
sentry-self-hosted-clickhouse-1                                    | 7. Poco::PooledThread::run() @ 0x13d89e59 in /usr/bin/clickhouse
sentry-self-hosted-clickhouse-1                                    | 8. Poco::ThreadImpl::runnableEntry(void*) @ 0x13d860ea in /usr/bin/clickhouse
sentry-self-hosted-clickhouse-1                                    | 9. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
sentry-self-hosted-clickhouse-1                                    | 10. clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
sentry-self-hosted-clickhouse-1                                    |  (version 21.8.13.1.altinitystable (altinity build))`

**Comment by alexey-milovidov** [comment]
> (version 21.8.13.1.altinitystable (altinity build))

This is a mistake. We don't support alternative, third-party builds.
I strongly do not recommend "altinity" builds.

Read https://clickhouse.com/docs/knowledgebase/difference_between_official_builds_and_3rd_party

**Comment by Tristan971** [comment]
@alexey-milovidov other reports in the issue are for the official build though. We also experience it on official builds. Don’t close because 1 commenter uses a third-party version…

**Comment by csvan** [comment]
Confirming the same problem on vanilla Sentry 24.5.1

**Comment by mbovingfred** [comment]
Anyone has a solution to this ? I'm facing the same issue on vanilla Sentry 24.5.1

**Comment by den-crane** [comment]
@mbovingfred @csvan Do you experience related issues at a client side? Or is it only about spoiled logs?

**Comment by Tristan971** [comment]
> Do you experience related issues at a client side?

None

> Or is it only about spoiled logs?

Yes exactly

**Comment by csvan** [comment]
Same as above ^

**Comment by mbovingfred** [comment]
I get the error when i check clickhouse container logs

**Comment by csvan** [comment]
FYI error persists on Sentry 24.6.0

```
clickhouse-1                                    | 2024.06.21 16:13:47.456878 [ 61550 ] {} <Error> ServerErrorHandler: Poco::Exception. Code: 1000, e.code() = 107, Net Exception: Socket is not connected, Stack trace (when copying this message, always include the lines below):
clickhouse-1                                    |
clickhouse-1                                    | 0. Poco::Net::SocketImpl::error(int, String const&) @ 0x0000000015b3dbf2 in /usr/bin/clickhouse
clickhouse-1                                    | 1. Poco::Net::SocketImpl::peerAddress() @ 0x0000000015b40376 in /usr/bin/clickhouse
clickhouse-1                                    | 2. DB::HTTPServerRequest::HTTPServerRequest(std::shared_ptr<DB::IHTTPContext>, DB::HTTPServerResponse&, Poco::Net::HTTPServerSession&) @ 0x0000000013154417 in /usr/bin/clickhouse
clickhouse-1                                    | 3. DB::HTTPServerConnection::run() @ 0x0000000013152ba4 in /usr/bin/clickhouse
clickhouse-1                                    | 4. Poco::Net::TCPServerConnection::start() @ 0x0000000015b42834 in /usr/bin/clickhouse
clickhouse-1                                    | 5. Poco::Net::TCPServerDispatcher::run() @ 0x0000000015b43a31 in /usr/bin/clickhouse
clickhouse-1                                    | 6. Poco::PooledThread::run() @ 0x0000000015c7a667 in /usr/bin/clickhouse
clickhouse-1                                    | 7. Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000015c7893c in /usr/bin/clickhouse
clickhouse-1                                    | 8. ? @ 0x00007f4cc6a4f609 in ?
clickhouse-1                                    | 9. ? @ 0x00007f4cc6974353 in ?
clickhouse-1                                    |  (version 23.8.11.29.altinitystable (altinity build))
```

**Comment by alexey-milovidov** [comment]
The error is reported when a user immediately disconnects with TCP RST after connecting.
The fact that this error is reported is normal. It may indicate problems with your infrastructure, but usually does not require any actions.

**Comment by Tristan971** [comment]
It indicates problems with ClickHouse loudly polluting the logs for what any other system uses a debug-level « connection reset by peer » warning.

It is in fact completely inappropriate to throw stacktraces in the logs for it…

**Comment by csvan** [comment]
Yes kindly do not close this, at the very least the log level should be downgraded

**Comment by coelho** [comment]
We are experiencing this log spam as well in a production environment.

> The error is reported when a user immediately disconnects with TCP RST after connecting. The fact that this error is reported is normal. It may indicate problems with your infrastructure, but usually does not require any actions.

It is reasonable to believe there will be a degree of unreliability over a network, especially under high load. In our case, we do not observe any negative effect correlated with this debug message (besides spamming our logs).

**Comment by abrahamibo** [comment]
> Yes, no one really minds that it’s happening. The problem is that it makes logs entirely unusable.
> 
> It indicates problems with ClickHouse loudly polluting the logs for what any other system uses a debug-level « connection reset by peer » log line.
> 
> It is in fact completely inappropriate to throw error-level logs with stacktraces in the logs for it…
> 
> Closing this issue is very wrong.

So what exactly do we need to do?

**Comment by Tristan971** [comment]
> So what exactly do we need to do?

Moving this error to TRACE level (or whatever is the lowest developer-intended log level) seems appropriate to me.

If a client sends a TCP RST, which is a very appropriate way for an HTTP client to terminate a connection, it should not appear at the standard log level, especially not with an entire stacktrace.

You could argue that it’s already a debug-level log but the CH team has repeatedly indicated that users are expected to run it at debug log level rather than information level, so it is de-facto what would be considered « info » level in other software.

**Comment by alexey-milovidov** [comment]
We run all our servers with the Trace level by default.

**Comment by Tristan971** [comment]
> We run all our servers with the Trace level by default.

That's great, then you can move this to trace, still see it yourself, and anyone else who doesn't do so won't see it anymore...? Win-win

**Comment by alexey-milovidov** [comment]
Yes, this makes sense.

**Comment by alexey-milovidov** [comment]
Rate-limiting is better.

**Comment by vdimir** [comment]
> keeping it at DEBUG

Currently it's `<Error>`. So, for me either `Debug` or `Trace`  with rate limiting seems alright
