### ISSUE TITLE
ClickHouse on PFSENSE with ntopng

### ISSUE THREAD

**Issue by AnhTuanNguyenn** [ClickHouse/ClickHouse#34227]
hello, i have problem when i try install click house and pfsense, 
pfsense: 192 xx xx.14 (clickhouse installed)
debian: 31.xx.xx.16(clickhouse installed too, dont worry i usenat to foward this ip so it's same network now)

so the pb is i cant connect clickhouse-client from pfsense to debian,
i got this error, some one tell me how can i can do pls ? 
Code: 210. DB::NetException: Connection refused (32.xx.xx.xx:9000). (NETWORK_ERROR)

i would use it to stock logs from my ntopng 
thanks

**Comment by AnhTuanNguyenn** [comment]
update after connect clickhouse i got this error 

01/Feb/2022 16:52:36 [ClickHouseImport.cpp:83] WARNING Child process could not be created, or its status could not be retrieved [No child processes]
01/Feb/2022 16:52:35 [ClickHouseImport.cpp:89] WARNING
01/Feb/2022 16:52:35 [ClickHouseImport.cpp:88] WARNING Unable to execute 'cat /var/db/ntopng/tmp/clickhouse/clickhouse-2-0-333.1643730695.csv | /usr/bin/clickhouse-client --host "32.xx.xx.XX" --user "default" --password "xxxx" -d "ntopng" --format_csv_delimiter="|" --format_csv_allow_double_quotes true --query="INSERT INTO flows (FLOW_ID,IP_PROTOCOL_VERSION,FIRST_SEEN,LAST_SEEN,VLAN_ID,PACKETS,TOTAL_BYTES,SRC2DST_BYTES,DST2SRC_BYTES,SRC2DST_DSCP,DST2SRC_DSCP,PROTOCOL,IPV4_SRC_ADDR,IPV6_SRC_ADDR,IP_SRC_PORT,IPV4_DST_ADDR,IPV6_DST_ADDR,IP_DST_PORT,L7_PROTO,L7_PROTO_MASTER,L7_CATEGORY,FLOW_RISK,INFO,PROFILE,NTOPNG_INSTANCE_NAME,INTERFACE_ID,STATUS,SRC_COUNTRY_CODE,DST_COUNTRY_CODE,SRC_LABEL,DST_LABEL,SRC_MAC,DST_MAC,COMMUNITY_ID,SRC_ASN,DST_ASN,PROBE_IP,OBSERVATION_POINT_ID,SRC2DST_TCP_FLAGS,DST2SRC_TCP_FLAGS,SCORE,CLIENT_NW_LATENCY_US,SERVER_NW_LATENCY_US,CLIENT_LOCATION,SERVER_LOCATION,SRC_NETWORK_ID,DST_NETWORK_ID,INPUT_SNMP,OUTPUT_SNMP,SRC_HOST_POOL_ID,DST_HOST_POOL_ID) FORMAT CSV" 2>&1'
01/Feb/2022 16:52:35 [ClickHouseImport.cpp:83] WARNING Child process could not be created, or its status could not be retrieved [No child processes]
01/Feb/2022 16:51:07 [LuaEngine.cpp:1254] WARNING Script failure [/usr/local/share/ntopng/scripts/lua/rest/v2/get/interface/alert/list.lua][...local/share/ntopng//scripts/lua/modules/format_utils.lua:250: attempt to perform arithmetic on a nil value (local 'epoch_begin')]

**Comment by AnhTuanNguyenn** [comment]
someone pls ?

**Comment by alexey-milovidov** [comment]
Check server logs at /var/log/clickhouse-server/
