### ISSUE TITLE
Logical error if I use Altinity's operator on GKE

### ISSUE THREAD

**Issue by gauravphoenix** [ClickHouse/ClickHouse#34237]
I am inserting data while a new replica is being added to the cluster, the insertion code (JDBC) is throwing an exception sporadically- 

```
DB::Exception: Part with name 25863efe930dc432b57f69f0e4428af2_0_0_0 is already written by concurrent request. It should not happen for non-duplicate data parts because unique names are assigned for them. It's a bug. (LOGICAL_ERROR) (version 22.1.3.7 (official build))
```
it doesn't happen often, if the request fails (like above) and I retry it, it works just fine. 

CH was deployed using the Altinitiy operator. 2 shards, 5 replicas on GKE.

**Comment by den-crane** [comment]
>25863efe930dc432b57f69f0e4428af2_0_0_0

Then this error happens is it always 0_0_0 ?

**Comment by gauravphoenix** [comment]
yes!
Also, I think I know how I got into this state. I had three replicas of a shard before, I then reduced the replicas to just 1 and then re-increased the replicas to 3 and that's when I started seeing this error

**Comment by alexey-milovidov** [comment]
Do you use any experimental non-production features like s3 storage?

**Comment by gauravphoenix** [comment]
none at all, pretty standard setup-just two merge tree tables

**Comment by den-crane** [comment]
@gauravphoenix can you share `show create table ...` or at least `partition by ` and types of columns in partition by

**Comment by gauravphoenix** [comment]
@den-crane -the tables are quite simple- 
`PARTITION BY (tenant_id,retention_days)`
the cardinality of tenant_id and retention_days is also quite low. There are just 4-5 columns in the table. 

I have a feeling that the issue was caused by some GKE DNS stale cache issue. While the replicas were scaling up and down, although k8s StatefulSets give stable network identity, the identity is tied to the DNS name and not IP addresses. Since the Altinity operator uses the DNS name in the config map, it is possible that the DNS look-up returned the wrong `A` response. 

The [GKE documentation](https://cloud.google.com/kubernetes-engine/docs/how-to/nodelocal-dns-cache#requirements_and_limitations) says the cache is valid for 30 seconds

Do you reckon stale DNS cache could cause this issue?

**Comment by alexey-milovidov** [comment]
@den-crane let's answer or close.

**Comment by UnamedRus** [comment]
The same issue, but it's not related to k8s or altinity operator. 
@alexey-milovidov 
ClickHouse version 21.11.4.14

```
DB::Exception: Part with name 20220427_20220427_13925584_13925584_0 is already written by concurrent request. It should not happen for non-duplicate data parts because unique names are assigned for them. It's a bug.


0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x9b605d4 in /usr/bin/clickhouse
1. DB::Exception::Exception<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&>(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) @ 0x100377c3 in /usr/bin/clickhouse
2. DB::ReplicatedMergeTreeSink::commitPart(std::__1::shared_ptr<zkutil::ZooKeeper>&, std::__1::shared_ptr<DB::IMergeTreeDataPart>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x12f67411 in /usr/bin/clickhouse
3. DB::ReplicatedMergeTreeSink::consume(DB::Chunk) @ 0x12f62e75 in /usr/bin/clickhouse
4. DB::SinkToStorage::transform(DB::Chunk&) @ 0x13321984 in /usr/bin/clickhouse
5. ? @ 0x132a1f89 in /usr/bin/clickhouse
6. DB::ExceptionKeepingTransform::work() @ 0x132a1a7c in /usr/bin/clickhouse
7. ? @ 0x131301fb in /usr/bin/clickhouse
8. DB::PipelineExecutor::executeStepImpl(unsigned long, unsigned long, std::__1::atomic<bool>*) @ 0x1312c1b1 in /usr/bin/clickhouse
9. DB::PipelineExecutor::executeStep(std::__1::atomic<bool>*) @ 0x1312a9c5 in /usr/bin/clickhouse
10. DB::TCPHandler::processInsertQuery() @ 0x130d1786 in /usr/bin/clickhouse
11. DB::TCPHandler::runImpl() @ 0x130ca2f7 in /usr/bin/clickhouse
12. DB::TCPHandler::run() @ 0x130ddb79 in /usr/bin/clickhouse
```

**Comment by gauravphoenix** [comment]
@UnamedRus - did you add or drop a shard/replicas recently?
