### ISSUE TITLE
hasToken not works inside lambda

### ISSUE THREAD

**Issue by kiryaka** [ClickHouse/ClickHouse#34231]
I am using tokenbf_v1 index and trying to create a UDF for a string search. The idea is to have this working: 
`SELECT ... FROM largeTextTable as t WHERE hasAllTokens(t.body, 'search string')`
the function suppose to look something like this:
` (column, searchString) -> arrayAll( token -> hasToken(lower(column), token ), tokens(searchString) ) `
It does not work and I narrowed down the problem to the next one:
```
ClickHouse client version 21.12.1.8928 (official build).
...
SELECT arrayAll(token -> hasToken(column, token), ['red', 'fox'])
FROM
(
    SELECT arrayJoin(['red fox', 'brown fox']) AS column
)
...
Received exception from server (version 21.12.1):
Code: 44. DB::Exception: Received from localhost:9000. DB::Exception: Argument at index 1 for function hasToken must be constant: while executing 'FUNCTION hasToken(column :: 1, token :: 0) -> hasToken(column, token) UInt8 : 2'. (ILLEGAL_COLUMN)
```
The exact same idea works fine using the `position` function:
```
SELECT arrayAll(token -> (position(column, token) > 0), ['red', 'fox'])
FROM
(
    SELECT arrayJoin(['red fox', 'brown fox']) AS column
)
┌─arrayAll(lambda(tuple(token), greater(position(column, token), 0)), ['red', 'fox'])─┐
│                                                                                   1 │
│                                                                                   0 │
└─────────────────────────────────────────────────────────────────────────────────────┘

2 rows in set. Elapsed: 0.001 sec.
```

**Comment by alexey-milovidov** [comment]
The author @Enmk of function `hasToken` implemented it only for constant arguments.
If you apply it for elements of array inside lambda, the function becomes non applicable.

**Comment by alexey-milovidov** [comment]
I will close this issue, because @Enmk is an external contributor and the chance he will pay attention is very low.

**Comment by alexey-milovidov** [comment]
The current behavior should be documented.
