### ISSUE TITLE
S3 table function can't upload file while aws s3 CLI can

### ISSUE THREAD

**Issue by yonesko** [ClickHouse/ClickHouse#34244]
I have insert to s3 6bil rows table:
```
INSERT INTO FUNCTION
s3('https://s3.us-east-1.amazonaws.com/my-bucket/data.csv', 'DFGHJ', 'FGHJIJH, 'CSVWithNames', 'time DateTime, exchangeId UInt16, pairId UInt16, id String, price Decimal(38, 18), volume Decimal(38, 18)')
SELECT * FROM trade;
```
but it fails trying to upload part 10001 while aws s3 upload [supports](https://docs.aws.amazon.com/AmazonS3/latest/userguide/qfacts.html) only 10k parts.

I had to export this select into CSV 600GB file on the disk and then perform successful `aws s3 cp data.csv s3://my-bucket/data.csv`

I expected Clickhouse would do it on his own successfully. 

┌─version()─┐
│ 22.1.3.7  │
└───────────┘

**Comment by UnamedRus** [comment]
https://github.com/ClickHouse/ClickHouse/pull/28679

Adjust those settings

```
    M(UInt64, s3_min_upload_part_size, 32*1024*1024, "The minimum size of part to upload during multipart upload to S3.", 0) \
    M(UInt64, s3_max_single_part_upload_size, 32*1024*1024, "The maximum size of object to upload using singlepart upload to S3.", 0) \
```

**Comment by alexey-milovidov** [comment]
@UnamedRus do you know why `aws s3 cp` can successfully upload the data?
Recently I've uploaded 0.75 TB file, it did not blink an eye. Why we cannot do the same?

**Comment by UnamedRus** [comment]
AWS S3 allow to have not more than 10k parts per single multipart upload.

If you use:
32MB part size = 320GB max file size
512MB part size = 5TB max file size.

`aws s3 cp` either always use 512MB part size or adjust part size depending on the total file size.

Before https://github.com/ClickHouse/ClickHouse/pull/28679 pr ClickHouse also used 512MB part size, but value was lower due high ram usage in case of multi thread upload(i believe).

> Why we cannot do the same?

I guess we can.
So we have 2 possible scenarios:

1. We know file size in advantage. (part move to s3 for example).
In that case, we can easily predict min possible part size value.

2. We don't know for sure (INSERT INTO FUNCTION s3(....) SELECT *).
In that case, we probably can start with using 32MB parts and after some threshold (100-200 parts) switch to bigger parts with lowering amount of parallel upload threads.

**Comment by UnamedRus** [comment]
Also about writing of big files in s3-like storage.
It's possible that event 5TB limit will not be enough. 
 
In https://github.com/ClickHouse/ClickHouse/pull/33142, it was prohibited to use globs in files names in case of writing to s3.

For example in case of big query, you **need** to use `*` in uri, if you want to export big files, big query will automatically append `_000000000.format, _000000001.format, _000000002.format` to such uploads. 

https://cloud.google.com/bigquery/docs/reference/standard-sql/other-statements
https://stackoverflow.com/questions/58447205/google-bigquery-export-table-to-multiple-files-in-google-cloud-storage-and-somet

**Comment by alexey-milovidov** [comment]
Let's start with 10 MB parts and increase it twice every 1000 parts.

**Comment by alexey-milovidov** [comment]
Also found that current implementation is not good enough: https://github.com/ClickHouse/ClickHouse/issues/34346
