### ISSUE TITLE
At least one test without Docker

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#34241]
This PR #33957 passed the tests but `clickhouse` binary did not start on a clean VM in AWS.
Most likely because all the tests are run in Docker.

Let's make a check that will download a binary and run

```
sudo ./clickhouse install
clickhouse-local --query "SELECT 1"
```

**Additional context**

Later we can extend it to implement package installation tests (that we don't have for now).

**Comment by Felixoid** [comment]
Isn't it covered by building clickhouse-server and clickhouse-keeper for each PR?

I've taken a look at `clickhouse install`, it spoils a system a bit and we can't reliably clear it out.

Would something less permanent be enough?

**Comment by den-crane** [comment]
BTW, couple weeks ago `clickhouse-server.service` was incorrect/broken and I found it accidentally. https://github.com/ClickHouse/ClickHouse/pull/35869

**Comment by Felixoid** [comment]
I'll try to address it in #45568 

I plan to check deb, rpm and tgz packages with ubuntu, centos and alpine images

**Comment by Felixoid** [comment]
The issue is solved with https://github.com/ClickHouse/ClickHouse/pull/45568
