### ISSUE TITLE
Client: Always go to the previous query on arrow-up

### ISSUE THREAD

**Issue by Algunenano** [ClickHouse/ClickHouse#34259]
Currently when navigating the history using the clickhouse-client, if you press up I expect to go to the previous query. Then if I press up again, it should go to the previous one, and so on. The usability problem I have is that when the queries are multi-line then pressing arrow-up sends you to the previous line and not the previous query:

Here is an example when using clickhouse-client:
![clickhouse_client](https://user-images.githubusercontent.com/664253/152173836-5f7286f3-77d2-49ab-8557-a5600d2fb832.gif)

And a similar example when using psql (postgresql CLI):
![psql](https://user-images.githubusercontent.com/664253/152173524-cab54efe-95d2-461f-a72e-b85634ed6415.gif)

In both cases I'm only pressing arrow-up. In psql it always goes to the previous query, and in CH it goes to the previous line unless you are in the first one (then it goes to the previous query). I like the psql behaviour more.

Note that in psql if you want to edit the previous lines of a sql query you can either go left (ctrl+left to step over whole words) or `\e` to edit the query as a text file (opens up EDITOR).

**Comment by den-crane** [comment]
It was intentional change to ease query editing https://github.com/ClickHouse/ClickHouse/pull/31641

You can use M-UP/M-DOWN

**Comment by Algunenano** [comment]
> You can use M-UP/M-DOWN

I see. Then it's just unexpected to me (since it works differently from other CLI tools) but I can live with Alt+UP

**Comment by den-crane** [comment]
It was unexpected for everyone. 6 years we used UP/DOWN
