### ISSUE TITLE
How to store per-second-rates from raw counter values?

### ISSUE THREAD

**Issue by azeroc** [ClickHouse/ClickHouse#34257]
I would like to know if it is possible to store **per-second-rates** through a materialized or window view or some other mechanism from a query that calculates them from **raw counter values**.

### My current setup
I have a time-series table like this which is populated from kafka topic via materialized view:
```
CREATE TABLE IF NOT EXISTS counters_instat_ch_prod
(
  device_id UInt32 Codec(Gorilla, LZ4),
  measurement_id UInt32 Codec(Gorilla, LZ4),
  value UInt64 Codec(DoubleDelta, LZ4),
  timestamp DateTime('Europe/Stockholm') Codec(DoubleDelta, LZ4)
) ENGINE = MergeTree()
  ORDER BY (device_id, measurement_id, timestamp)
  PARTITION BY toYYYYMM(timestamp)
  TTL timestamp + INTERVAL 1 MONTH
;
```
(on unrelated note, I was quite impressed that with the codec combination and ordering I managed to achieve 1.0 bytes per row compression 👍  )

**Device ID** has cardinality of about 2 million and is neatly valued from 1 to ~2 million.
**Measurement ID** has cardinality of about 10k and is neatly valued from 1 to 10k.
**Value** is ever-increasing raw counter value gathered from sensors, interfaces, etc.
**Timestamp** described the exact time when counter value was observed

A device has roughly 20 unique measurements but some devices may have more or less. In total, there are 20 million datapoints ingested every 5 minutes, about 6 billion data points per day.

### My query to get per-second-rates from raw counters
```
SELECT 
  device_id, 
  measurement_id, 
  sorted_time, 
  time_sorted_vals, 
  running_diffs, 
  running_time_diffs, 
  if (running_time_diffs > 0 AND running_time_diffs < 900, intDiv(running_diffs, running_time_diffs), -1) as val_per_second 
FROM 
(
  WITH
    groupArray( tuple(value,timestamp) ) as val_time_tuples,
    arraySort( x -> x.2, val_time_tuples ) as val_time_tuples_sorted,
    arrayMap( t -> t.1, val_time_tuples_sorted) as time_sorted_vals,
    arrayMap( t -> t.2, val_time_tuples_sorted) as sorted_time,
    arrayMap( t -> toUInt64(t.2), val_time_tuples_sorted) as sorted_unix_time,
    arrayDifference(time_sorted_vals) as running_diffs,
    arrayDifference(sorted_unix_time) as running_time_diffs
  SELECT 
    device_id,
    measurement_id,
    sorted_time,
    time_sorted_vals,
    running_diffs,
    running_time_diffs
  FROM 
    counters_instat_ch_prod
  WHERE
    device_id = 24745 AND
    measurement_id = 8
  GROUP by device_id, measurement_id
)
ARRAY JOIN sorted_time, time_sorted_vals, running_diffs, running_time_diffs 
ORDER BY device_id, measurement_id, sorted_time DESC
```

The important result columns from that query is device_id, measurement_id, sorted_time and val_per_second.

I have an extra condition to mark a result row val_per_second with -1 if the raw counters for difference calculation are too far apart (over 900 seconds) or there was no previous counter.

The inner select WHERE statement narrows down selection to specific device and specific measurement type because otherwise I get error about query running out of memory (probably because it tries to group more than few billion rows to account for all device_id and measurement_id pairs).

### What I want

I want to take something like the above query that spits out per-second-rates calculated from raw counters values and put them in a new table (so that I can further aggregate them into larger time buckets such as hourly and daily rates via min, max and maybe quantiles).

However, as far as I understand Materialized Views don't work with such nested grouping because it will just look at incoming blocks of inserts that may not even contain full sequence of device_id, measurement_id grouped series. Even if it did, it would report 0 per-second rate for first rows in an insert block that MV is currently handling.

Can the experimental WINDOW VIEW help with this? Is it feasible to pre-calculate and store results like this for all dimensions considering there are about 20 million unique series from device_id, measurement_id pair combinations?

### Current alternative

My current alternative is that the data-collecting agents calculate deltas and per-second rates as it is collected (keeping last raw counter value and its timestamp in-memory to calculate deltas and rates for the next observed counter value). This is done outside Clickhouse and I am simply wondering if maybe there is some way to make Clickhouse automatically do something similar as well.

**Comment by azeroc** [comment]
Thank you for the quick response!

OK. I will stick with the current alternative as I don't think Window View will be good enough to replace it.

Thinking about it more and as far as I know the core issue with materialized / window views with regards to this use-case is that they have no idea about continuation of series from different blocks of inserts (i.e. series of counter raw values with the same ordering key split in multiple insert blocks, where only the very first row in the very first insert block wouldn't have a previous row to calculate delta/rate from). 

To solve this purely in Clickhouse there needs to be some sort of **sliding-window** functionality (either another special view, a special function or a special merge-tree engine) that remembers the previous block's last rows from each ordering key to calculate next block's deltas/rates from its first rows.

**Comment by gingerwizard** [comment]
@azeroc curious why you don't use `runningDifference` function and simply compute your aggregates per unit time and then use these to compute higher-order aggregations as you need? Is the reason for wanting to store sec values in a table purely a performance optimisation decision?

I would like to dig into this a little more as we feel there is potential product enhancement need her for monotonically increasing counters.

**Comment by den-crane** [comment]
```sql
select runningDifference(a) from (select number a from numbers(10));
┌─runningDifference(a)─┐
│                    0 │
│                    1 │
│                    1 │
│                    1 │
│                    1 │
│                    1 │
│                    1 │
│                    1 │
│                    1 │
│                    1 │
└──────────────────────┘


select runningDifference(a) from (select number a from numbers(10)) settings max_block_size=4 format PrettyCompactMonoBlock;
┌─runningDifference(a)─┐
│                    0 │
│                    1 │
│                    1 │
│                    1 │
│                    0 │
│                    1 │
│                    1 │
│                    1 │
│                    0 │
│                    1 │
└──────────────────────┘
```

**Comment by gingerwizard** [comment]
@den-crane Thanks for pointing out the limitation of `runningDifference` with the respect to the current block. Maybe we can consider this as a potential area for enhancement to avoid the complex logic.

**Comment by azeroc** [comment]
@den-crane Thanks, that illustrates one of my described limitations pretty clearly.

Another issue with straight-forward usage of runningDifference is that it won't work on a table where value series are grouped by certain columns (can be considered label columns).
```
SELECT
  key,
  subkey,
  value,
  runningDifference(value) as running_diff
FROM 
(
  SELECT 
   if(number % 2 == 0, 'A', 'B') as key, 
   if(number % 2 == 0, if(number % 3 == 0, 'X1', 'X2'), if(number % 3 == 0, 'Y1', 'Y2')) as subkey,
   if(number % 2 == 0, if(number % 3 == 0, 6, 4), if(number % 3 == 0, 3, 1)) as value
  FROM numbers(10)
  ORDER BY key, subkey
);
```
The above returns
```
┌─key─┬─subkey─┬─value─┬─running_diff─┐
│ A   │ X1     │     6 │            0 │
│ A   │ X1     │     6 │            0 │
│ A   │ X2     │     4 │           -2 │
│ A   │ X2     │     4 │            0 │
│ A   │ X2     │     4 │            0 │
│ B   │ Y1     │     3 │           -1 │
│ B   │ Y1     │     3 │            0 │
│ B   │ Y2     │     1 │           -2 │
│ B   │ Y2     │     1 │            0 │
│ B   │ Y2     │     1 │            0 │
└─────┴────────┴───────┴──────────────┘
```
Ideally I would want running difference there to be 0, so the running difference is aware of certain columns acting as separators for value series columns.

The workaround is that complex array-mapping query I described in the original post based on https://stackoverflow.com/a/69369952

Even if you add an extra runningDifference function to account for column grouping there is still issue of it not working for materialized views because of Dan's demonstrated block-separation.

Maybe the new and improved grouping version of runningDifference function could be implemented as AggregateFunction? It's -State version could store the state of last values in a given block **for given grouping columns**?

**Comment by gingerwizard** [comment]
@azeroc did you consider using window functions? i.e. https://clickhouse.com/docs/en/sql-reference/window-functions/

Here you have the functions `lagInFrame` - this doesn't suffer the same block level limitations @den-crane kindly pointed out. 

The query becomes a little easier - its simplest form:

```
select deviceId, measurementId, (value - previous) as delta
FROM (
      select deviceId,
             measurementId,
             value,
             lagInFrame(value, 1) OVER (PARTITION BY deviceId, measurementId ORDER BY timestamp ASC) as previous
      FROM device_counters
      LIMIT 1000
         )
```

As you point out though, this still doesn't solve you requirement fully - just simplifies your original query. I think the challenge still becomes executing this over blocks separately during insertion by the mv.

You can use the same window features to populate data for your schema I believe e.g:

```
DROP TABLE default.device_counters
CREATE TABLE device_counters
(
    deviceId      UInt32,
    measurementId UInt32,
    value         UInt64,
    timestamp     DateTime64
)
    ENGINE = MergeTree()
        ORDER BY (deviceId, measurementId, timestamp)

INSERT INTO device_counters
SELECT *
FROM (
         WITH now() as current, 100 as numDevices, 10 as maxDelta, 10 as numMeasurements, 5 as timeDiff
         SELECT deviceId,
                measurementId,
                sum(delta) OVER (PARTITION BY deviceId, measurementId ORDER BY row_number ASC) as value,
                current + row_number                                                           as timestamp
         FROM (
               SELECT deviceId,
                      measurementId,
                      row_number() OVER (PARTITION BY deviceId, measurementId ORDER BY deviceId, measurementId ASC) as row_number,
                      now()                                                                                         as current,
                      delta
               FROM (
                     SELECT floor(a / (10000000 / numDevices)) as deviceId,
                            a % numMeasurements                as measurementId,
                            a,
                            delta
                     FROM (select number a, rand(a) % maxDelta + 1 as delta FROM numbers(10000000))
                     ORDER BY deviceId, measurementId
                        ))
         ) SELECT deviceId, measurementId, min(value)
FROM device_counters
GROUP BY deviceId, measurementId
ORDER BY deviceId, measurementId
```
Note: The numbers in this are approximate. If you want to change the number of rows you need to change it in 2 places - and I'm sure the above could be improved.

**Comment by seanlaff** [comment]
I'm also struggling with turning monotonically increasing counters into rates, it seems like `runningDifference` is the most performant way to do this calculation (I need to do it very frequently over large data, which makes the `groupArray` workarounds untenable)

A similar function, [runningAccumulate](https://clickhouse.com/docs/en/sql-reference/functions/other-functions/#runningaccumulate), supports a "grouping key". Would it make sense for `runningDifference()` to also support that to handle reseting the calculation for each `deviceId`? There was an open issue about this behavior that was closed, (https://github.com/ClickHouse/ClickHouse/issues/2515) but I think it was closed incorrectly because as far a I can tell `runningDifference()` does not actually support a group key.

@gingerwizard Thanks for the example regarding window functions, I tried it but seems magnitudes slower than `runningDifference()`. Can you take a peek at this and make sure I'm using it correctly?

Here's a simple example where its one big counter (no different deviceIds)

```sql
-- Create a table of one big counter
CREATE TABLE IF NOT EXISTS counters (
    ts DateTime,
    val UInt64
) ENGINE = MergeTree()
ORDER BY (ts);

-- Insert 100mil entries at 5sec interval
INSERT INTO counters 
WITH 1000 as maxDelta
SELECT toStartOfMinute(now()) + 5 * k, runningAccumulate(sum_k)
FROM (
    SELECT number as k, sumState(rand(k) % maxDelta + 1) AS sum_k
    FROM numbers(100000000)
    GROUP BY k
    ORDER BY k
);
```

Roughly 2s execution (calculating rates via runningDifference)
```sql
SELECT ts, runningDifference(val)/runningDifference(ts) AS rate FROM counters ORDER BY ts
```

Roughly 12s execution (calculating rates via lagInFrame)
```sql
SELECT
    ts,
    (val - val_prev)/toUnixTimestamp(ts-ts_prev) AS rate
FROM
(
    SELECT
        ts,
        lagInFrame(ts, 1) OVER (ORDER BY ts ASC) AS ts_prev,
        val,
        lagInFrame(val, 1) OVER (ORDER BY ts ASC) AS val_prev
    FROM counters
)
```

There was a suggestion in https://github.com/ClickHouse/ClickHouse/issues/22098 to use a row window function, so I tried that as well, and the speed is similar to the `lagInFrame` test.

```sql
SELECT
    ts,
    (val - val_prev) / toUnixTimestamp(ts - ts_prev) AS rate
FROM
(
    SELECT
        ts,
        any(ts) OVER (Rows BETWEEN 1 PRECEDING AND 1 PRECEDING) AS ts_prev,
        val,
        any(val) OVER (Rows BETWEEN 1 PRECEDING AND 1 PRECEDING) AS val_prev
    FROM counters
) ORDER BY ts
```

Im guessing we pay a performance penalty for window functions- and I also assume that making `runningDifference()` block-aware would make it just as slow as the window functions. Is this accurate?

**Comment by gingerwizard** [comment]
@seanlaff as pointed out the runningDifference cant be used across multiple blocks e.g.

```
SELECT ts, val, runningDifference(val)/runningDifference(ts) AS rate FROM counters ORDER BY ts LIMIT 100 settings max_block_size=4
```


| ts | val | rate |
| :--- | :--- | :--- |
| 2022-02-07 15:38:00 | 86 | NaN |
| 2022-02-07 15:38:05 | 401 | 63 |
| 2022-02-07 15:38:10 | 1317 | 183.2 |
| 2022-02-07 15:38:15 | 1399 | 16.4 |
| 2022-02-07 15:38:20 | 2372 | NaN |
| 2022-02-07 15:38:25 | 3121 | 149.8 |
| 2022-02-07 15:38:30 | 3931 | 162 |
| 2022-02-07 15:38:35 | 4745 | 162.8 |
| 2022-02-07 15:38:40 | 5293 | NaN |
| 2022-02-07 15:38:45 | 6085 | 158.4 |


Thanks for the note re window functions, i'll do some tests.

**Comment by azeroc** [comment]
I ended up slightly expanding my alternative for my backend agents to calculate extra values per sensor measurement (raw value, delta, timestamp delta, few others) and storing that in Clickhouse instead of just raw counter value. The cost is simply more storage but with proper codec and compression settings few extra columns won't be an issue. As a result it will be easier to setup aggregation pipelines later with materialized views (since deltas are already pre-calculated).

For me this question is kind of answered: there are few workarounds such as array grouping or window functions, however, no support for materialized views to perform rate/delta aggregation from raw counter values.

As far as I understand there are two suggested improvements from the discussion above:
1. Add runningDifference function variant that supports grouping and should be more efficient than window function alternative
2. Add a way to calculate running difference between insert blocks which should help setting up automatic calculation in materialized views (perhaps this turns into a broader functionality of storing some metadata about previous insert blocks in a more generic way, not just for running difference)

Should the above be created as separate cases or should the discussion about possible improvements continue here?
