### ISSUE TITLE
`bitmapBuild` does not work for `TabSeparated` format when inserting data

### ISSUE THREAD

**Issue by FrankChen021** [ClickHouse/ClickHouse#34276]
**Describe what's wrong**

When inserting data to a column `groupBitmap`, `bitmapBuild` is used to construct a bitmap object on the SQL. But now we find that this expression fails to work for `TabSeparated` input format.

**Does it reproduce on recent release?**

We're using 21.8.4.1, but this problem also exists on the master branch.

## **How to reproduce**

1. Create a table with groupBitmap field

    ```sql
    CREATE TABLE default.groupBitmap
    (
        `timestamp` Int64,
        `id` AggregateFunction(groupBitmap, Int64)
    )
    ENGINE = MergeTree
    ORDER BY timestamp
    SETTINGS index_granularity = 8192 │
    ```

2. INSERT a row into the table with `VALUES` format

    ```sql
    INSERT  INTO    groupBitmap (timestamp, id)  
    values(1,	bitmapBuild([toInt64(20000),toInt64(20001),toInt64(20003),toInt64(20004),toInt64(20005),toInt64(20006),toInt64(20007),toInt64(20008)]))
    ```

3. INSERT a row with `TabSeparated` format

    ```sql
    INSERT  INTO    groupBitmap (timestamp, id)  FORMAT TabSeparated
    90001	bitmapBuild([toInt64(20000),toInt64(20001),toInt64(20003),toInt64(20004),toInt64(20005),toInt64(20006),toInt64(20007),toInt64(20008)])
    ```

4. SELECT the results from the table

    ```text
    ┌─timestamp─┬─id───────────────┐
    │         1 │ N!N#N$N%N&N'N(N │
    └───────────┴──────────────────┘
    ┌─timestamp─┬─id─┐
    │     90001 │    │
    └───────────┴────┘
    ```

We can see that the 2nd row, which is inserted with `TabSeparated` format, the `id` field has no value while the `Values` format, the 1st row, correctly insert the bitmap data into the table.

## **The parsing logic of TabSeparated format**

By looking through the code, these two input formats use two different ways to parse the `bitmapBuild` expression. 

The `TabSeparated` format calls following method to parse the 2nd column.

```
void SerializationAggregateFunction::deserializeTextEscaped(IColumn & column, ReadBuffer & istr, const FormatSettings &) const
{
    String s;
    readEscapedString(s, istr);
    deserializeFromString(function, column, s);
}
```

And this will finally goes into `RoaringBitmapWithSmallSet::read` to parse the expression.

```c
class RoaringBitmapWithSmallSet : private boost::noncopyable
{
    ...
    void read(DB::ReadBuffer & in)
    {
        UInt8 kind;
        readBinary(kind, in);
        if (BitmapKind::Small == kind)
        {
            small.read(in);
        }
        else if (BitmapKind::Bitmap == kind)
        {
            size_t size;
            readVarUInt(size, in);
            std::unique_ptr<char[]> buf(new char[size]);
            in.readStrict(buf.get(), size);
            rb = std::make_unique<RoaringBitmap>(RoaringBitmap::read(buf.get()));
        }
    }
}
```

Of course, the input buffer is a string, the first binary is neither `BitmapKind::Small` nor `BitmapKind::Bitmap`, the deserialization of `bitmapBuild(...)` does nothing.

## **The format parsing logic of `Values` format**

However, this format tries different paths to parse the `bitmapBuild` expression. It calls `SerializationAggregateFunction::deserializeTextQuoted` to deserialize the input.

```

void SerializationAggregateFunction::deserializeTextQuoted(IColumn & column, ReadBuffer & istr, const FormatSettings &) const
{
    String s;
    readQuotedStringWithSQLStyle(s, istr);
    deserializeFromString(function, column, s);
}
```

However, since the `bitmapBuild` is not quoted, a `ParseException` is thrown inside the `readQuotedStringWithSQLStyle` above.

```
template <char quote, bool enable_sql_style_quoting, typename Vector>
static void readAnyQuotedStringInto(Vector & s, ReadBuffer & buf)
{
    if (buf.eof() || *buf.position() != quote)
    {
        throw ParsingException(ErrorCodes::CANNOT_PARSE_QUOTED_STRING,
            "Cannot parse quoted string: expected opening quote '{}', got '{}'",
            std::string{quote}, buf.eof() ? "EOF" : std::string{*buf.position()});
    }
   ...
```

And this `ParsingException` is caught and handled by `ValuesInputFormat` which then tries to parse the input as an expression.

```c
bool ValuesBlockInputFormat::tryReadValue(IColumn & column, size_t column_idx)
{
    bool rollback_on_exception = false;
    try
    {
        ...
    }
    catch (const Exception & e)
    {
        /// Switch to SQL parser and don't try to use streaming parser for complex expressions
        /// Note: Throwing exceptions for each expression may be very slow because of stacktraces
        buf.rollbackToCheckpoint();
        return parseExpression(column, column_idx);
    }
}
```

This is why the `Values` format works.

Since the JDBC client is using the `TabSeparated` format for INSERT queries, currently it's not able to insert bitmap from this client. 

I have not gone through all the format code, but seems that other formats also DO NOT support `bitmap` expression to build a bitmap object for INSERT queries.

**Comment by den-crane** [comment]
TSV format expects that you insert binary STATE. TSV parser does not support any functions, only data.

Use input function https://clickhouse.com/docs/en/sql-reference/table-functions/input/

```
INSERT  INTO  groupBitmap (timestamp, id) select timestamp, bitmapBuild(arr) FROM input('timestamp Int64, arr Array(Int64)')
FORMAT TSV 90001	[20000,20001,20003,20004,20005,20006,20007,20008]

select *, bitmapToArray(id) from groupBitmap;
┌─timestamp─┬─id───────────────┬─bitmapToArray(id)─────────────────────────────────┐
│     90001 │ N!N#N$N%N&N'N(N │ [20000,20001,20003,20004,20005,20006,20007,20008] │
└───────────┴──────────────────┴───────────────────────────────────────────────────┘
```

**Comment by den-crane** [comment]
BTW JDBC supports roaringBitmap, you can do bitmapBuild in JDBC/java before sending data to CH server.
