### ISSUE TITLE
Metrics to Prometheus from custom metrics table

### ISSUE THREAD

**Issue by Heroidjsjs** [ClickHouse/ClickHouse#34278]
Hi there, I understand that it's might be an unappropriate place to ask, though I've got a question. You've included support of Prometheus for metrics from `system` tables as it's written in [here](https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings/#server_configuration_parameters-prometheus), but, nevertheless, will it be possible to expose metrics to Prometheus from custom metrics table? Or is there any chance to provide engine for Prometheus (such as Graphite)?

For example, we need to expose metrics for checking data consistency per hour/per day, and, as far as I can remember, there isn't any system tables for that, or any possibility for such checks. It won't be a problem for me & my colleagues to do custom metrics export to Prometheus, but, I would be glad if you'll do that or you already have that feature!
(maybe I'm being blind :D)

**Comment by den-crane** [comment]
here https://github.com/ClickHouse/ClickHouse/issues/20200
