### ISSUE TITLE
Any plans to optimize the Map type from the storage perspective?

### ISSUE THREAD

**Issue by andrea-s** [ClickHouse/ClickHouse#34280]
The Map type provides great syntax benefits, but the fact that all data for the Map column is stored in a single file ends up being a significant bottleneck (becoming more and more significant as the number of keys grows, especially if the dataset is somewhat sparse).

Is there any plan to optimize this and make it so that the "Map" datatype actually writes on separate files for each key? At the moment, the performance hit is just too high to use it at scale unfortunately unless the number of keys is very limited.

**Comment by CurtizJ** [comment]
Yes, there are plans to implement `Map` type that writes each key to separate column, but only after #23932 will be merged.

**Comment by andrea-s** [comment]
That's a great news, thank you!
