### ISSUE TITLE
Allow to change the size of background pools in runtime.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#34311]
**Use case**

The server is not loaded and I want to do more merges quickly.

**Describe the solution you'd like**

```
SYSTEM SET MERGE POOL SIZE 48
SYSTEM SET FETCH POOL SIZE 48
...
```

**Comment by zhongyuankai** [comment]
@alexey-milovidov Maybe i can make it.

**Comment by filimonov** [comment]
Question - how to see the effective value of that.

**Comment by UnamedRus** [comment]
Implemented by https://github.com/ClickHouse/ClickHouse/pull/36425 starting from 22.5
