### ISSUE TITLE
Store frozen partitions on remote storage (s3 etc)

### ISSUE THREAD

**Issue by gauravphoenix** [ClickHouse/ClickHouse#34322]
**Use case**
`freeze partition` is quite a useful command for partition management, backups, etc. Most likely, the frozen parts need to be moved somewhere. 

**Describe the solution you'd like**

provide an option to the freeze command like this- 
`ALTER TABLE table_name FREEZE [PARTITION partition_expr] [WITH NAME 'backup_name'] TO s3://foo`

if `to s3://foo` is not provided, the parts can be stored locally (backward compatible).

**Comment by UnamedRus** [comment]
related https://github.com/ClickHouse/ClickHouse/issues/28527

**Comment by alexey-milovidov** [comment]
https://clickhouse.com/docs/en/operations/backup#configuring-backuprestore-to-use-an-s3-endpoint
