### ISSUE TITLE
"FROM remote table" doesn't work if user password in remote server contains "!"

### ISSUE THREAD

**Issue by Wachynaky** [ClickHouse/ClickHouse#34331]
**Description**
From initial host (host1) if you uses "remote" function and the user password in remote host (host2) contains "!" show error

**How to reproduce**
1.  In **Host2**: 
`CREATE USER otherUserNameInHost2  IDENTIFIED WITH sha256_password BY 'user2Pass';`
2. From terminal in Host2
`clickhouse-client -u otherUserNameInHost2 --password 'user2Pass'  -q "select * from system.numbers limit 10"`

Results Ok
```
0
1
2
3
4
5
6
7
8
9
```

3. Go to Host1 and create tunnel to Host2
`ssh -f -N -i MyFile.pem userLinux@Host2 -L 127.0.0.1:9999:127.0.0.1:9000`

4.  From **Host1** using "remote" table in host2
`clickhouse-client -u userNameHhost1 --password user1Pass -q "SELECT * FROM remote('127.0.0.1:9999','system.numbers','otherUserNameInHost2','user2Pass' ) limit 10"`

Results Ok
```
0
1
2
3
4
5
6
7
8
9
```

5.  I change password to otherUserNameInHost2 (in Host2) by the same pass adding "!" to end
`ALTER USER otherUserNameInHost2 IDENTIFIED WITH sha256_password BY 'user2Pass!'`

6. And trie one more time from **Host2** 
`clickhouse-client -u otherUserNameInHost2 --password 'user2Pass!'  -q "select * from system.numbers limit 10"`
Reesults ok
```
0
1
2
3
4
5
6
7
8
9
```

7. Now, from Host1 using remote table
`clickhouse-client -u userNameHhost1 --password user1Pass -q "SELECT * FROM remote('127.0.0.1:9997','system.numbers','otherUserNameInHost2','user2Pass!' ) limit 10"`

Result fail
```
Code: 516. DB::Exception: Received from localhost:9000. DB::Exception: Received from 127.0.0.1:9997. DB::Exception: otherUserNameInHost2: Authentication failed: password is incorrect or there is no user with such name. (AUTHENTICATION_FAILED)
(query: SELECT * FROM remote('127.0.0.1:9997','system.numbers','otherUserNameInHost2','user2Pass' ) limit 10)"
```

**Comment by alexey-milovidov** [comment]
The unix shell (most likely bash) is doing some magic with `!` symbol.

Example:
```
$ echo "'Hello!'"
bash: !': event not found
```

See the explanation here: https://unix.stackexchange.com/questions/33339/cant-use-exclamation-mark-in-bash
