### ISSUE TITLE
node-clickhouse-orm

### ISSUE THREAD

**Issue by zimv** [ClickHouse/ClickHouse#34338]
Hello! At the beginning, I want to say that Clickhouse is a great database.

I'm developing [node-clickhouse-orm](https://github.com/zimv/node-clickhouse-orm).Because in the actual development, I need to finish the work more efficiently.

I'm not very familiar with Clickhouse, so I just realized some capabilities.

I want to know what ability Clickhouse ORM needs to achieve to be included in official documents.It is the [client-libraries](https://clickhouse.com/docs/en/interfaces/third-party/client-libraries/)

Look forward to your reply

**Comment by peledni** [comment]
Hello @zimv,

We will happily add your library to our client-libraries once it is mature enough. A few suggestions:

* Add types (using typescript) - will make the library a lot more self-explanatory and easy to use
* Research 'mongoose' - a beautiful ODM for mongo. They actually make you want to use mongo with how well designed it is.
* Make sure to define a criteria structure for queries but also remain flexible in case your library does not support a certain criterion. i.e. allow both querying using criteria and simply running SQL queries.
* Document your code well so others will not hesitate to either use the library or contribute to it.

Thanks for your contribution.
