### ISSUE TITLE
JDBC engine doesn't work with materialized view 

### ISSUE THREAD

**Issue by sliontc** [ClickHouse/ClickHouse#34356]
I'v tested JDBC engine with materialized view and found out that the view was not refreshed after data inserted into the jdbc table.

Steps:

Create Table test ENGINE = JDBC('msjdbc_keyword', 'dbo', 'NewTable') // the datasource is MS SqlServer
CREATE MATERIALIZED VIEW mv ENGINE = MergeTree AS SELECT * FROM test
Insert into Keyword.dbo.NewTable (name) VALUES('oiljkl')
Select * From mv
Result:
No data was returned.

**Comment by den-crane** [comment]
https://den-crane.github.io/Everything_you_should_know_about_materialized_views_commented.pdf

Materialized view an insert trigger which gets data from inserts

**Comment by sliontc** [comment]
I did insert data into the table as said above:
"Insert into Keyword.dbo.NewTable (name) VALUES('oiljkl')"
