### ISSUE TITLE
Update based on current value

### ISSUE THREAD

**Issue by adam-mrozik** [ClickHouse/ClickHouse#34383]
Hey,

I am struggling a little bit with finding a solution for updating certaing int rows by dividing current value by the factor of 10. But let's say I want to add 5, append a suffix to a string, whatever. The idea is just how to alter rows based on a current value.

Pseudo-code I want to perform:
```
ALTER TABLE my_table UPDATE age = age/10 WHERE time > today() - 2
```

Do you have any idea how could I do it?

**Comment by nvartolomei** [comment]
The query you posted above should work.

```sql
CREATE TABLE t
(
    `v` UInt64
)
ENGINE = MergeTree
ORDER BY tuple();

INSERT INTO t VALUES (10), (100), (1000);

SELECT *
FROM t;

┌────v─┐
│   10 │
│  100 │
│ 1000 │
└──────┘

ALTER TABLE t
    UPDATE v = v / 10 WHERE 1 = 1;

SELECT *
FROM t;

┌───v─┐
│   1 │
│  10 │
│ 100 │
└─────┘
```
