### ISSUE TITLE
Replication doesn't work. Permission denied

### ISSUE THREAD

**Issue by Pythonov** [ClickHouse/ClickHouse#34402]
Hi!
I created CH cluster with 3 nodes (1 shard and 3 replicas)
Then created a table with that query
_CREATE TABLE food ON CLUSTER default_cluster (period DateTime64, region String, indicator String, price Float64) Engine = ReplicatedMergeTree('/clickhouse/tables/shard_{shard}/test_food', 'replica_{replica}') PARTITION BY toYYYYMM(period) ORDER BY (region);_
I inserted data into 1st replica and got this exception in clickhouse-server.log:
![image](https://user-images.githubusercontent.com/61191665/152953795-d0770003-7a20-47e1-ad10-b1618b43fb49.png)
Here is **ls -l** for /var/lib/ (chmod was made recursively)
![image](https://user-images.githubusercontent.com/61191665/152954137-55ca5a3d-ba53-4472-897c-8a7393427986.png)
In system.replicas i have 3 total_replicas and 3 active_replicas.
What else can i do?

**Comment by Pythonov** [comment]
But i can't chmod folder from error
![image](https://user-images.githubusercontent.com/61191665/152984097-3bdab351-b86e-4060-9d03-ad681cd73941.png)

**Comment by mo-avatar** [comment]
try to find whether the parent directory or the file itself 's owner is clickhouse may help

**Comment by mo-avatar** [comment]
If chmod do not help, may be you can just stop clickhouse instance , chmod -R the data directory and just restart the clickhouse instance。

**Comment by Pythonov** [comment]
> If chmod do not help, may be you can just stop clickhouse instance , chmod -R the data directory and just restart the clickhouse instance。

I tried this)
It changed back after I started ch

**Comment by Pythonov** [comment]
Owner is clickhouse

**Comment by mo-avatar** [comment]
check if the path element in config.xml is in correct mode

**Comment by Pythonov** [comment]
In documentation it's said that if Zookeeper isn't set in the config file, any existing replicated tables will be read-only. But i configured that

**Comment by mo-avatar** [comment]
for now , it has nothing to do with zookeeper

**Comment by mo-avatar** [comment]
I wonder whether you have started three instance  on the same linux environment, if it is, you'd better check if you are operating on the right instance.

**Comment by Pythonov** [comment]
Config is ok i think
![image](https://user-images.githubusercontent.com/61191665/152991675-040f8116-fb93-4fba-aab7-db64d069d6e3.png)
I have 3 VMs with the same CentOs7

**Comment by mo-avatar** [comment]
Alright ,  what I mean is you might need to check whether the  permission on /var/lib/clickhouse is correct.

**Comment by Pythonov** [comment]
![image](https://user-images.githubusercontent.com/61191665/152992991-39d571fe-780f-48ad-b352-f39792dde970.png)
It's the same for all nodes

**Comment by mo-avatar** [comment]
It is beyond my knowledge now.  but the error is still most likely  caused by permission.  obviously, something weird happening, may the luck be with you

**Comment by Pythonov** [comment]
Thanks

**Comment by mo-avatar** [comment]
One more thing,  try to check if the clickhouse instance are started with the right user (clickhouse)

**Comment by Pythonov** [comment]
I don't know what did it use for config file, but it started to work after i chmod /etc/clickhouse-server/config.xml
