### ISSUE TITLE
cmake failed on macos 12.1

### ISSUE THREAD

**Issue by DogeWatch** [ClickHouse/ClickHouse#34403]
**ClickHouse version**
commit 17a245aa4de9f0028966e5c61578a3aae0716a33 (HEAD, tag: v22.1.2.2-stable)

**Cmake version**
❯ cmake --version
cmake version 3.22.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).

**Ninja version**
❯ ninja --version
1.10.2

**Compiler name and version**
Homebrew clang version 13.0.1
Target: arm64-apple-darwin21.2.0
Thread model: posix
InstalledDir: /opt/homebrew/opt/llvm/bin

**Full cmake and/or ninja output**
-- ClickHouse modes:
-- Server mode: ON
-- Client mode: ON
-- Local mode: ON
-- Benchmark mode: ON
-- Extract from config mode: ON
-- Compressor mode: ON
-- Copier mode: ON
-- Format mode: ON
-- Obfuscator mode: ON
-- ODBC bridge mode: OFF
-- Library bridge mode: ON
-- ClickHouse install: ON
-- ClickHouse git-import: ON
-- ClickHouse keeper mode: ON
-- ClickHouse keeper-converter mode: ON
-- bash_completion will be written to /usr/local/share/bash-completion/completions
-- Target check already exists
-- /Users/letang/project/temp/clickhouse-2/utils: Have 14766 megabytes of memory.
        Limiting concurrent linkers jobs to 4 and compiler jobs to OFF
CMake Error at cmake/sanitize_target_link_libraries.cmake:29 (get_property):
  Maximum recursion depth of 1000 exceeded
Call Stack (most recent call first):
  cmake/sanitize_target_link_libraries.cmake:31 (get_all_targets_recursive)
  cmake/sanitize_target_link_libraries.cmake:31 (get_all_targets_recursive)
  cmake/sanitize_target_link_libraries.cmake:31 (get_all_targets_recursive)
  cmake/sanitize_target_link_libraries.cmake:31 (get_all_targets_recursive)
  cmake/sanitize_target_link_libraries.cmake:31 (get_all_targets_recursive)
  cmake/sanitize_target_link_libraries.cmake:31 (get_all_targets_recursive)
  cmake/sanitize_target_link_libraries.cmake:31 (get_all_targets_recursive)
  cmake/sanitize_target_link_libraries.cmake:31 (get_all_targets_recursive)
  cmake/sanitize_target_link_libraries.cmake:31 (get_all_targets_recursive)
  cmake/sanitize_target_link_libraries.cmake:31 (get_all_targets_recursive)
  cmake/sanitize_target_link_libraries.cmake:31 (get_all_targets_recursive)
  cmake/sanitize_target_link_libraries.cmake:31 (get_all_targets_recursive)
  cmake/sanitize_target_link_libraries.cmake:31 (get_all_targets_recursive)

**Comment by taiyang-li** [comment]
Looks like dead loop in cmake function `get_all_targets`

**Comment by ucasfl** [comment]
It workds well for me in latest master.

**Comment by genzgd** [comment]
What is your error message?  See https://github.com/ClickHouse/ClickHouse/pull/34472

**Comment by alexey-milovidov** [comment]
@FArthur-cmd you also have Mac AArch64, let's check if it builds with step by step instructions from the docs.
If it does, let's close this issue.

**Comment by FArthur-cmd** [comment]
I've check build for master, for branch 22.1 and for that commit. All of them were successful. I have same version of cmake, ninja and clang.
