### ISSUE TITLE
Adding a column (ALTER TABLE ADD COLUMN) fails

### ISSUE THREAD

**Issue by x052bb** [ClickHouse/ClickHouse#34414]
Hi all

I have the following setup:
     - Clickhouse version 21.9
     - 8 nodes in cluster ( 2 shards / 4 replicas)
     - test.XXX is a ReplicatedMergeTree table

I need to add a column to test.XXX table , the following query is executed: 
 
> ALTER TABLE test.XXX ON CLUSTER test_cluster ADD COLUMN IF NOT EXISTS NEWCOLUMN1 String;

It fails with an error:

> [Code: 1002, SQL State: ]  ClickHouse exception, code: 1002, .... DB::Exception: There was an error on ...: Code: 517. DB::Exception: Metadata on replica is not up to date with common metadata in Zookeeper. Cannot alter. (CANNOT_ASSIGN_ALTER) (version 21.9.2.17 (official build)). (CANNOT_ASSIGN_ALTER) (version 21.9.2.17 (official build))

Some observations:

1. Sometimes the above ALTER works ok, but such cases are rare. 
2. Even though query ends with an error, the column is actually added
3. Checked metadata before running the query - it is exactly the same both on disk / in zookeeper

Question:

Am I doing something wrong? 

I know I can workaround by executing DDLs on each shard separately or just ignore CANNOT_ASSIGN_ALTER error, but this looks inconvenient. Is there a reliable way to execute DDL queries on cluster?

**Comment by den-crane** [comment]
@x052bb
Do you use JDBC ? 
Do you connect to a random server?
Do you run several `alter` one by one? `ALTER TABLE .... ADD COLUMN ..; ALTER TABLE .... ADD COLUMN ..; ALTER TABLE .... ADD COLUMN ..;` ?

**Comment by x052bb** [comment]
> Do you use JDBC ? 

Yes

> Do you connect to a random server? 

No. There's a single server in JDBC connection string, like _jdbc:clickhouse://host:port_

> Do you run several `alter` one by one? `ALTER TABLE .... ADD COLUMN ..; ALTER TABLE .... ADD COLUMN ..; ALTER TABLE .... ADD COLUMN ..;` ?

The above error is reproduced if I run single ALTER, just as in example above

**Comment by x052bb** [comment]
@den-crane 

> Does it reproduce from CH client ?

Here's how reply looks when I'm using pure HTTP:

> host1  9010    0               7       5
> host2  9010    0               6       5
> host3  9010    0               5       5
> host4  9010    0               4       4
> host5  9010    0               3       0
> host6  9010    517     Code: 517. DB::Exception: Metadata on replica is not up to date with common metadata in Zookeeper. Cannot alter. (CANNOT_ASSIGN_ALTER) (version 21.9.2.17 (official build))     2       0
> host7  9010    0               1       0
> host8  9010    0               0       0
> Code: 517. DB::Exception: There was an error on [host6:9010]: Code: 517. DB::Exception: Metadata on replica is not up to date with common metadata in Zookeeper. Cannot alter. (CANNOT_ASSIGN_ALTER) (version 21.9.2.17 (official build)). (CANNOT_ASSIGN_ALTER) (version 21.9.2.17 (official build))
> 

But

< HTTP/1.1 200 OK

Looks like there's a difference between pure-HTTP & JDBC driver request? Do you know the root cause ( I assume that since you asked about CH client)?

**Comment by alexey-milovidov** [comment]
This issue should be directed to the repository of the JDBC driver.
