### ISSUE TITLE
Rename ORDER BY to SORT BY or SORTED BY

### ISSUE THREAD

**Issue by ramazanpolat** [ClickHouse/ClickHouse#34427]
ORDER BY clause used in MergeTree engine family usually gets confused with the ORDER BY in SELECT statements.

I suggest that renaming it to SORT BY or SORTED BY will prevent this confusion.

```sql
CREATE TABLE test(
    a UInt64,
    s String,
)
ENGINE=MergeTree
SORT BY (a ASC, s DESC)
```

**Comment by alexey-milovidov** [comment]
Isn't it too late to change?

IIRC Vertica is using ORDER BY similarly to ClickHouse:
https://www.vertica.com/docs/9.2.x/HTML/Content/Authoring/AdministratorsGuide/ConfiguringTheDB/PhysicalSchema/ChoosingSortOrderBestPractices.htm

**Comment by alexey-milovidov** [comment]
The fact that it is similar to ORDER BY in SELECT queries is alright, because the ORDER BY in table will also optimize ORDER BY queries.

**Comment by UnamedRus** [comment]
The only problem with ORDER BY is that people assume, that they will get fully sorted data even without ORDER BY in query.

**Comment by amosbird** [comment]
The `(a ASC, s DESC)` part might be useful in some cases.

**Comment by alexey-milovidov** [comment]
Theoretically DESC can be useful if most of SELECT queries are using optimize_read_in_order and DESC order.
But I don't recommend trying to implement it.
