### ISSUE TITLE
Why always get first disk of volume of data part when selecting parts to move ?

### ISSUE THREAD

**Issue by fuwhu** [ClickHouse/ClickHouse#34438]
When i read the code of MergeTreePartsMover::selectPartsForMove, i could not understand the code below : 
https://github.com/ClickHouse/ClickHouse/blob/master/src/Storages/MergeTree/MergeTreePartsMover.cpp#L138

Per my understanding, it aims at choosing the data parts  stored on the disks whose free space is not enough. So it use `part->volume->getDisk()` to get the disk of current data part.

But the function IVolume::getDisk() always return the first disk of the volume which may not be the disk that the data part resides in.

Could anyone help me understand the logic here ?

**Comment by fuwhu** [comment]
Is IMergeTreeDataPart::volume always of SingleDiskVolume type ?

**Comment by JackyWoo** [comment]
@fuwhu yes, because a data part is a single file.

**Comment by fuwhu** [comment]
> @fuwhu As my understanding yes, because a data part is a single file.

Thanks for your reply. I quickly check the code, it seems all createPart calls pass a SingleDiskVolume parameter.
Just feel a bit confusing here, but it's ok.
