### ISSUE TITLE
0 is handled improperly as a column constant value

### ISSUE THREAD

**Issue by estaine** [ClickHouse/ClickHouse#34441]
We upgraded from v. 21.2.2.8 to v. 21.12.4.1 a few days ago and started to experience a weird issue.
Some queries having 0 as a column constant value started to return the following error:

> Received exception from server (version 21.12.4):
> Code: 44. DB::Exception: DB::Exception: Cannot convert column `enabled` because it is non constant in source stream but must be constant in result. (ILLEGAL_COLUMN)

I wasn't able to define exact criteria but it seems that a JOIN and a UNION ALL, as in the example below, are a must.

The query is:

```
SELECT *
FROM
(
    SELECT
        ef.frequency AS frequency,
        0 AS enabled,
        NULL as name
    FROM e_frequencies AS ef
    UNION ALL
    SELECT
        tf.frequency AS frequency,
        0 AS enabled,
        t.name AS name
    FROM t_frequencies AS tf
    INNER JOIN tags AS t ON toUInt64(tf.tag_id) = t.id
)
WHERE frequency > 0
LIMIT 0, 50
```

Things start working properly if I replace 0 with, say, `1-1` or `toUInt8('0')` in both `0 AS enabled` lines or in `frequency > 0` condition. It also works perfectly fine if there's any numeric literal other than 0 in any of those two places (`0 AS enabled` or `frequency > 0`)

Tables schemas are as follows:

`e_frequencies`:
```
CREATE TABLE e_frequencies
(
    `id` UInt32,
    `frequency` UInt64
)
ENGINE = Distributed('default_cluster', 'default', 'e_frequencies_data', rand())
```

`t_frequencies`:
```
CREATE TABLE t_frequencies
(
    `tag_id` UInt32,
    `frequency` UInt64
)
ENGINE = Distributed('default_cluster', 'default', 't_frequencies_data', rand())
```
`tags`:
```
CREATE DICTIONARY tags
(
    `id` UInt64,
    `name` String
)
PRIMARY KEY id
SOURCE(MYSQL(...))
LIFETIME(MIN 300 MAX 360)
LAYOUT(HASHED()) 
```

I tried to reproduce the issue using non-distributed table engines but with no success, so that makes me think that the problem might be related to the previously solved issue #8165

Please let me know if any other information is needed and thank you in advance

**Comment by den-crane** [comment]
is it reproduce if instead of `0 AS enabled,` you use `materialize(0) AS enabled,`

**Comment by estaine** [comment]
@den-crane 
It works now, thanks a lot!
Nevertheless, it's still unclear to me why 1 is materialized implicitly, while 0 isn't.
Isn't that a bug?

**Comment by tavplubix** [comment]
> Nevertheless, it's still unclear to me why 1 is materialized implicitly, while 0 isn't.
> Isn't that a bug?

Looks like it is, but provided example is incomplete, and unfortunately I cannot reproduce it. The following works as expected:
```
    <test_shard_localhost2>
            <shard>
                <replica>
                    <host>127.0.0.2</host>
                    <port>9000</port>
                </replica>
            </shard>
    </test_shard_localhost2>
```
```
CREATE TABLE e_frequencies_data (id UInt32, frequency UInt64) ENGINE = Memory;
CREATE TABLE t_frequencies_data (id UInt32, frequency UInt64) ENGINE = Memory;
INSERT INTO e_frequencies_data VALUES (1, 1);
INSERT INTO t_frequencies_data VALUES (1, 2);

CREATE TABLE e_frequencies (id UInt32, frequency UInt64) ENGINE = Distributed('test_shard_localhost2', 'default', 'e_frequencies_data', rand());
CREATE TABLE t_frequencies (id UInt32, frequency UInt64) ENGINE = Distributed('test_shard_localhost2', 'default', 't_frequencies_data', rand());

CREATE TABLE dict_data (id UInt64, name String) ENGINE = Memory;
INSERT INTO dict_data VALUES (1, 'test');

CREATE DICTIONARY tags (id UInt64, name String) PRIMARY KEY id SOURCE(CLICKHOUSE(HOST '127.0.0.2' PORT tcpPort() TABLE 'dict_data')) LIFETIME(MIN 300 MAX 360) LAYOUT(HASHED()); 

SELECT *
FROM
(
    SELECT
        ef.frequency AS frequency,
        0 AS enabled,
        NULL AS name
    FROM e_frequencies AS ef
    UNION ALL
    SELECT
        tf.frequency AS frequency,
        0 AS enabled,
        t.name AS name
    FROM t_frequencies AS tf
    INNER JOIN tags AS t ON toUInt64(tf.id) = t.id
)
WHERE frequency > 0
LIMIT 0, 50

Query id: 7d41609c-3faa-4c32-9b07-48e96ead17ac

┌─frequency─┬─enabled─┬─name─┐
│         1 │       0 │ ᴺᵁᴸᴸ │
└───────────┴─────────┴──────┘
┌─frequency─┬─enabled─┬─name─┐
│         2 │       0 │ test │
└───────────┴─────────┴──────┘

-- and the same result with 127.0.0.1
```

@estaine, do you use some non-default settings (`select * from system.settings where changed`) or non-standard cluster configuration? What is `tag_id`? (there is no such column in DDL queries). What are CREATE queries of `e_frequencies_data` and `f_frequencies_data`?

**Comment by alexey-milovidov** [comment]
No info provided.
