### ISSUE TITLE
Add settings to allow parts merge in same disk

### ISSUE THREAD

**Issue by JackyWoo** [ClickHouse/ClickHouse#34447]
**Use case**

In case of mulit-disk cluster,  part merging may lead to disk usage inbalance.  

Because merging will select parts from all disks and the merged part will reside in only one disk. If a partition has too many data it will lead to one disk usage very high.

I have 100+ CH clusters in production some of them the difference may be 30%.   After investigation, the cause of disk usage inbalance is some oversized merged parts.

**Describe the solution you'd like**

Add a settings to  allow parts merge only in the same disk.

If the idea is ok, I will work on it.

**Comment by amosbird** [comment]
You can try using `min_bytes_to_rebalance_partition_over_jbod`.

**Comment by JackyWoo** [comment]
@amosbird thx,  I will consider upgrading version.

**Comment by JackyWoo** [comment]
BTW parts distributes in disks by partition will also benefit queries.

**Comment by amosbird** [comment]
> BTW parts distributes in disks by partition will also benefit queries.

That's the original motivation of this setting.

**Comment by JackyWoo** [comment]
Close first.
