### ISSUE TITLE
how to drop ttl column （exception: not found column ... in block）

### ISSUE THREAD

**Issue by caoweiwei** [ClickHouse/ClickHouse#34440]
### Table Structure: ###
``` sql
CREATE TABLE default.demo_user
(
    `uid` String,
     ...,
    `demo` SimpleAggregateFunction(anyLast, Nullable(String)) TTL demo_ts,
    `demo_ts` SimpleAggregateFunction(max, DateTime)
)
ENGINE = AggregatingMergeTree()
PARTITION BY xxHash64(uid) % 8
ORDER BY uid
SETTINGS min_bytes_for_wide_part = 500000000, min_rows_for_wide_part = 1000000, index_granularity = 8192

CREATE TABLE default.demo_user_d
(
    `uid` String,
     ...,
    `demo` SimpleAggregateFunction(anyLast, Nullable(String)) TTL demo_ts,
    `demo_ts` SimpleAggregateFunction(max, DateTime)
)
ENGINE = Distributed('default', 'default', 'demo_user', xxHash64(uid))
```

### Steps ###
1. Stop data writing
2. SYSTEM FLUSH DISTRIBUTED default.demo_user_d
3. Execute ddl：
``` alter table default.demo_user_d ON CLUSTER default DROP COLUMN IF EXISTS demo,DROP COLUMN IF EXISTS demo_ts;```
```alter table default.demo_user ON CLUSTER default DROP COLUMN IF EXISTS demo,DROP COLUMN IF EXISTS demo_ts; ```
4. Restore data write

### Exception in Step 4 ###
Exception：**_Not found column demo_ts in block. There are only columns: uid, ..._**

Only when drop column with the suffix "_ts", got this exception, and then add column "xxx_ts", exception disappear. what is the right way of drop ttl column?

**Comment by den-crane** [comment]
Clickhouse version? `select version()` ?

**Comment by caoweiwei** [comment]
> 

version : 20.8.17.25

**Comment by den-crane** [comment]
20.8.17.25 is obsolete. I was unable to reproduce it with 22.1.

@caoweiwei Can you check this against 22.1.
