### ISSUE TITLE
Ability to specify `TTL MOVE TO [DISK|VOLUME] [IF EXISTS]` 

### ISSUE THREAD

**Issue by alesapin** [ClickHouse/ClickHouse#34455]
Different replicas can have different disks/volumes/storage policies configuration. But `TTL MOVE` expression is a part of the table definition and cannot be different on different replicas. 

So the idea is to implement `TTL MOVE IF EXSITS` which works only if disk exists on replica. Other replicas just ignores this expression.

**Comment by UnamedRus** [comment]
Maybe it should be the default behavior? 
How often do we want to see exception in merge/move/mutation in case of missing disk in disk policy?

**Comment by alexey-milovidov** [comment]
> How often do we want to see exception in merge/move/mutation in case of missing disk in disk policy?

I want to always get exception if `IF EXISTS` is not specified
to prevent typos.

**Comment by ramazanpolat** [comment]
I personally didn't like the idea of using `IF EXISTS` for this. It is like asking for a workaround to have what you want. Why not have a more definitive way to tell CH what to do on each replica?

Let's imagine a scenario where I have N replicas and 2 disks (`SLOW` and `FAST`) for each replica.

On R1, R2, ... R(N-1):
* Move rows older than 3 years to `SLOW` disk
* Keep newer rows on `FAST` disk

On RN:
* Move rows older than 3 years to `FAST` disk
* Keep newer rows on `SLOW` disk

This way I can still get results faster even if the data is older than 3 years, by simply sending my query to RN. I know that queries asking for old data is not that often, but I still want to serve them fast.

So having able to tell ClickHouse have different TTL definitions for different replicas would be great, but doing it with `IF EXISTS` is kinda a workaround.

How about having something like this:
```
CREATE TABLE table_name ON CLUSTER cluster 
(
    col1 String,
    col2 String,
    ...
)
ENGINE = ...
TTL WHERE (exp) DO
    d + INTERVAL 1 MONTH [DELETE],
    d + INTERVAL 1 WEEK TO VOLUME 'aaa',
    d + INTERVAL 2 WEEK TO DISK 'bbb';
TTL WHERE (exp) DO
    d + INTERVAL 1 MONTH [DELETE],
    d + INTERVAL 1 WEEK TO VOLUME 'aaa',
    d + INTERVAL 2 WEEK TO DISK 'bbb';
TTL
    d + INTERVAL 1 MONTH [DELETE],
    d + INTERVAL 1 WEEK TO VOLUME 'aaa',
    d + INTERVAL 2 WEEK TO DISK 'bbb';
```


Here `exp` can be conditions that satisfy `system.clusters` table like:
```
TTL WHERE shard_num=1 and replica_num=1 and is_local=1 DO ...
```

and if there is no `WHERE` after `TTL` that applies for all replicas.
