### ISSUE TITLE
PostgreSQL new insert data not sync to ClickHouse

### ISSUE THREAD

**Issue by Zkuns** [ClickHouse/ClickHouse#34464]
Hello
**My problem is:**
I want to use ClickHouse to load the PostgreSQL data. I create table success but the new insert data is not synced here.

I create a database from my remote **amazon PostgreSQL 11 database**.
<img width="1676" alt="image" src="https://user-images.githubusercontent.com/8684193/153219803-8dbb798f-06bf-40d9-9167-67c5f1ea746f.png">
The log show database is create success
<img width="1654" alt="image" src="https://user-images.githubusercontent.com/8684193/153220235-dfb17c1f-6c97-437e-beea-1014575892fc.png">
And the data is load success
<img width="743" alt="image" src="https://user-images.githubusercontent.com/8684193/153220458-6a4d1c0d-169c-4003-8184-d63e619d249b.png">

But after I add new data in PostgreSQL videos table. The new data will not sync to the ClickHouse videos table. There is nothing in the log.
<img width="1637" alt="image" src="https://user-images.githubusercontent.com/8684193/153221477-bb9ea609-992e-4f4f-90ae-e881b72e5419.png">

And after the videos table create on ClickHouse. The replication_slot in my remote PG database will keep growing. I have to delete it manually.
<img width="1099" alt="image" src="https://user-images.githubusercontent.com/8684193/153225314-1a499061-f8f2-47ca-9314-afc7a539c89c.png">

### Test on my localhost database
But if I connect ClickHouse to my **localhost PG database**. It will sync success. 
Here is the log where I create a tables from my localhost database. 
<img width="1673" alt="image" src="https://user-images.githubusercontent.com/8684193/153224284-8fbeaf3c-ab8c-44c8-ab94-26d1bb00c0de.png">
It will schedule check my localhost replication
<img width="1672" alt="image" src="https://user-images.githubusercontent.com/8684193/153224649-78bb2c0a-1608-4316-acee-8c9a60fac0a1.png">

The ClickHouse version is 22.1.1.1
The database I use on amazon is PG 11.12
My localhost PG database version is 12.7

Do you know what is going on here?  

Thanks
zkun

**Comment by Zkuns** [comment]
After I change the amazon PG version from 11.12 to 12.7, the problem is resolved. Now I change sync the data from PG to ClickHouse.

Is ClickHouse does not support the PG 11 version?

**Comment by zkuser2002** [comment]
Hello
I want to sync data from Postgresql to clickhouse and use this query:

CREATE DATABASE postgres_db
ENGINE = MaterializedPostgreSQL('*****:5432', '****', '****', '****')
SETTINGS materialized_postgresql_tables_list = 'tb,***,tb.****,tb.****',
materialized_postgresql_tables_list_with_schema = 1,
materialized_postgresql_schema = 'public',
materialized_postgresql_allow_automatic_update = 0;


it copy data from postgres to clickhouse, but after it, i have two problem:
1- if i add some data to postgresql i cant see it on clickhouse, I check my postgres version is 12.8 and clickhouse version is 22.1.3.7
2- After a day or two, the CPU usage goes up dramatically and I have to delete the ClickHouse database and do the process again from the beginning.

**Comment by kssenii** [comment]
Please check clickhouse logs for error messages.

**Comment by zkuser2002** [comment]
ok' i'll do that again and send an error when  the CPU usage goes up ,because this happens after one to two days.

**Comment by zkuser2002** [comment]
Hi @kssenii 
I do same as before, don't get any error yet, but some of tables update and some other not updated yet, whats its reason?
