### ISSUE TITLE
Does clickhouse suppport functions that like SQLServer Table-Valued function?

### ISSUE THREAD

**Issue by AngelLittleChaochao** [ClickHouse/ClickHouse#34478]
I have many SELECT SQL queries that are very similar. I'm wondering whether there has a way to implement functions like SQLServer Table-Valued function?

`CREATE FUNCTION udfProductInYear (
    @model_year INT
)
RETURNS TABLE
AS
RETURN
    SELECT 
        product_name,
        model_year,
        list_price
    FROM
        production.products
    WHERE
        model_year = @model_year;
`

Usage like:
`SELECT 
    * 
FROM 
    udfProductInYear(2017);
`
Referenced sample from https://www.sqlservertutorial.net/sql-server-user-defined-functions/sql-server-table-valued-functions/.

**Comment by qoega** [comment]
https://github.com/ClickHouse/ClickHouse/pull/27796

**Comment by AngelLittleChaochao** [comment]
> #27796
> 
> > Syntax CREATE FUNCTION {function_name} as ({parameters}) -> {function core}. Example CREATE FUNCTION plus_one as (a) -> a + 1

Thanks for answering my question. 
The SQLServer Table-Valued function is not like ClickHouse function. ClickHouse function only applies each row. The SQLServer Table-Valued function is more like parameter view in ClickHouse, the result is a "table".

**Comment by AngelLittleChaochao** [comment]
> 

I haven't found a solution. It looks like a Parameter View in ClickHouse, but it doesn't support now. I plan to implement it but haven't started.

**Comment by AngelLittleChaochao** [comment]
> Did you found any way of doing that? return a table as result of a function in clickhouse?

I found a way can do this. Reference the link: https://kb.altinity.com/altinity-kb-queries-and-syntax/altinity-kb-parameterized-views/
