### ISSUE TITLE
Breaking a source table row into multiple rows using materialized views

### ISSUE THREAD

**Issue by a-dot** [ClickHouse/ClickHouse#34474]
Is it possible to create two rows in a MV from a single row in a source table?

Example:
Insert in source table:
|when | col_1 | col_2|
|-----|-------|------|
|datetime | val_1 | val_2|

I would like to end up with something like this in the Materialized view:
| when | col_x |
|------|-------|
|datetime | val_1|
|datetime | val_2|

Is it possible to do that? Thanks!!

**Comment by den-crane** [comment]
Yes it's possible `arrayJoin( [ col_1 , col_2 ] ) `

```sql
SELECT arrayJoin([col1, col2]) AS colx
FROM
(
    SELECT
        1 AS col1,
        2 AS col2
)
┌─colx─┐
│    1 │
│    2 │
└──────┘



create materialized view ...
...
select arrayJoin( [ col_1 , col_2 ] ) as col_x, 
from ...
```

**Comment by a-dot** [comment]
Thanks den-crane, as always!
One follow up question if I may... the array approach is stumping me and I simply can't figure out how to do this. In my first post I gave you a simple example but what I'm trying to do is slightly more complicated.. I want to unfold col1 and col2 but I want to assign val_3 as such:

Before:
|when|col_1|col_2|col_3|
|------|-----|-----|------|
| datetime | val_1 | val_2 | val_3|

After:
|when|col_x|col_y|col_z|
|-----|-----|------|-----|
|datetime| val_1|val_3|0|
|datetime|val_2|0|val_3|

Hopefully you can still help! Thanks again!!

**Comment by den-crane** [comment]
```sql
SELECT col_x, col_y, col_z
FROM
(
    SELECT
        'val_1' AS col_1,
        'val_2' AS col_2,
        'val_3' col_3
)
array join [col_1, col_2] AS col_x, [col_3, '0'] as col_y, ['0', col_3] as col_z
┌─col_x─┬─col_y─┬─col_z─┐
│ val_1 │ val_3 │ 0     │
│ val_2 │ 0     │ val_3 │
└───────┴───────┴───────┘
```


```sql
SELECT
    (arrayJoin(arrayZip([col_1, col_2], [col_3, '0'], ['0', col_3])) AS xx).1 AS col_x,
    xx.2 AS col_y,
    xx.3 AS col_z
FROM
(
    SELECT
        'val_1' AS col_1,
        'val_2' AS col_2,
        'val_3' AS col_3
)
┌─col_x─┬─col_y─┬─col_z─┐
│ val_1 │ val_3 │ 0     │
│ val_2 │ 0     │ val_3 │
└───────┴───────┴───────┘
```

**Comment by a-dot** [comment]
thank you so much!
