### ISSUE TITLE
SBE message format

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#34477]
https://real-logic.github.io/simple-binary-encoding/

**Comment by alexey-milovidov** [comment]
What is the motivation?

**Comment by den-crane** [comment]
Some clients who work in trading area asked about it couple times. Not sure how widely this format is used.

**Comment by alexey-milovidov** [comment]
@den-crane, find a customer that needs this format and let them write to https://clickhouse.com/company/contact
Then the implementation of this feature will be accelerated.
