### ISSUE TITLE
clickhouse to dataframe

### ISSUE THREAD

**Issue by Alpha-su** [ClickHouse/ClickHouse#34485]
I use clickhouse-driver(a python package) read data from clickhouse, clickhouse is really fast, but time cost at building dataframe. So i think one solveion, if clickhouse can output data in format of binary dataframe or numpy, i can convert them to dataframe or numpy faster in python. 
Thanks very much, best wishes.

**Comment by qoega** [comment]
It is very interesting, but DataFrame has no serialization format as I understand. If I am not right you can put a link to binary dataframe or numpy serialized specification.

By the way [clickhouse-driver](https://github.com/mymarilyn/clickhouse-driver) is currently maintained not in ClickHouse organization. T

**Comment by Alpha-su** [comment]
Thanks for the reply, in python, **[pickle](https://docs.python.org/3/library/pickle.html)** is a binary protocols for serializing and de-serializing, you can load a python object very fast from a .pkl file.  maybe we can impl an output format like pickle? clickhouse-driver is a good package, but it still can't solve some of my needs, just like watching live view. 

> It is very interesting, but DataFrame has no serialization format as I understand. If I am not right you can put a link to binary dataframe or numpy serialized specification.
> 
> By the way [clickhouse-driver](https://github.com/mymarilyn/clickhouse-driver) is currently maintained not in ClickHouse organization. T

**Comment by ThomAub** [comment]
@Alpha-su maybe you can check https://github.com/sfu-db/connector-x

**Comment by Alpha-su** [comment]
Thanks，that looks so cool， and i will test the performance to find the most fast way to dataframe~

**Comment by wangzhichao-github** [comment]
> Thanks，that looks so cool， and i will test the performance to find the most fast way to dataframe~

你找到什么好的办法 了吗？我们目前也遇到了python中读clickhouse转dataframe慢的问题
