### ISSUE TITLE
Grant and Revoke are becoming slower and slower

### ISSUE THREAD

**Issue by huzhichengdd** [ClickHouse/ClickHouse#34483]
I found that [Grant] and [Revoke] are becoming slower and slower when there are more and more items  in the users' [.sql] file.

Sometimes thousands are not so slow, but sometimes hundreds are very slow.

Example is provided as follow : 
--------------------------------------------------------------

![长时间](https://user-images.githubusercontent.com/83016994/153355872-9ebea07d-a5a5-4407-be12-26b69e335b58.png)

----------------------------------------------------------------------------------

As we can see , 5.035  or  6.944  is  a little long .

**Comment by huzhichengdd** [comment]
Background :
I create a role called tmp_role and  execute [grant all on *.* to tmp_role]
Then ,  I grant tmp_role to supply_chain

**Comment by qoega** [comment]
You use deprecated version 20.8.
Can you reproduce with recent stable?

**Comment by huzhichengdd** [comment]
> You use deprecated version 20.8. Can you reproduce with recent stable?

I have not reproduced with recent stable but l am working on it .

Is this situation optimized in the stable version? I searched the related issue but I cannot find anything about this .

**Comment by den-crane** [comment]
```sql
create database test;
create user foo identified by 'x';

for i in `seq 10000`;    do echo -n $i" time: ";     clickhouse-client -q "create table if not exists test.test_$i (A Int64) Engine=Log";    clickhouse-client -tq "grant select on test.test_$i to foo"; done
...
...
405 time: 0.002
406 time: 0.002
...
1989 time: 0.013
1990 time: 0.006
...
3748 time: 0.008
3749 time: 0.009
...
9999 time: 0.022
10000 time: 0.022

select count() from system.grants;
┌─count()─┐
│   10003 │
└─────────┘

revoke select on  test.test_42 from foo;
0 rows in set. Elapsed: 0.037 sec.

revoke select on  test.test_442 from foo;
0 rows in set. Elapsed: 0.025 sec.

```

**Comment by huzhichengdd** [comment]
I restart the CK-server and find that [Grant] and [Revoke] action become faster：

![image](https://user-images.githubusercontent.com/83016994/153815588-3d1efcce-8b8d-43fa-bcba-682cef83f725.png)

It seems related with my change：

````cpp
ContextAccess::ContextAccess(const AccessControlManager & manager_, const Params & params_)
    : manager(&manager_)
    , params(params_)
{
    setUser(manager->read<User>(*params.user_id));
}

void ContextAccess::subscribeForChanges(const std::shared_ptr<ContextAccess> &res)
{
    subscription_for_user_change = manager->subscribeForChanges(
        *params.user_id, [res](const UUID &, const AccessEntityPtr & entity)
        {
            UserPtr changed_user = entity ? typeid_cast<UserPtr>(entity) : nullptr;
            std::lock_guard lock{res->mutex};
            res->setUser(changed_user);
        });
}
````
I cannot understand whether this change could cause this.
