### ISSUE TITLE
wrong float comparison with constant for Float32

### ISSUE THREAD

**Issue by bvt123** [ClickHouse/ClickHouse#34493]
create table test1 (a Float32,  b Float32 ) engine = MergeTree order by a ;
insert into test1 values (0.1,0.1), (0.2,0.2);
select count() from test1 where b = 0.1;
0 
select count() from test1 where b = toFloat32(0.1);
1
select count() from test1 where a > 0;
0
select count() from test1 where a > 0.0;
2
select count() from test1 where b > 0;
2

version 22.1.3.7

**Comment by alexey-milovidov** [comment]
Looks like a bug in index analysis (KeyCondition).
