### ISSUE TITLE
Invalid version for SerializationLowCardinality key column  when use hdfs disk

### ISSUE THREAD

**Issue by windylcx** [ClickHouse/ClickHouse#34494]
**hdfs config:**

![image](https://user-images.githubusercontent.com/917238/153400253-792c66a9-0695-476e-8577-b470d1517d6e.png)

**my table:**
```sql
CREATE TABLE test.hdfs_table2
(
    `id` LowCardinality(String),
    `log_time` DateTime,
    `device_id` String
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(log_time)
ORDER BY device_id
SETTINGS storage_policy = 'hdfs' AS
SELECT
    app_key,
    log_time,
    device_id
FROM test.test6
```

it 's ok for string column:
![image](https://user-images.githubusercontent.com/917238/153398355-e64cb1ec-5ad6-4446-981e-8367cfd406b5.png)

and fail when query LowCardinality(String) column
```sql
SELECT id
FROM test.hdfs_table2
LIMIT 1
```
![image](https://user-images.githubusercontent.com/917238/153399371-abd5f258-403a-47c7-bfc8-06fcb027c01b.png)

Received exception from server (version 21.12.2):
Code: 117. DB::Exception: Received from ******. DB::Exception: Invalid version for SerializationLowCardinality key column.: (while reading column id): (while reading from part ****node1/disks/hdfs/store/3c0/3c04b60e-32c9-4b21-bc04-b60e32c94b21/20200101_1_6_1/ from mark 0 with max_rows_to_read = 1): While executing MergeTreeInOrder. (INCORRECT_DATA)

here is the detail logs:
> <Error> executeQuery: Code: 117. DB::Exception: Invalid version for SerializationLowCardinality key column.: (while reading column id): (while reading from part ***/clickhouse/node1/disks/hdfs/store/3c0/3c04b60e-32c9-4b21-bc04-b60e32c94b21/20200101_1_6_1/ from mark 0 with max_rows_to_read = 1): While executing MergeTreeInOrder. (INCORRECT_DATA) (version 21.12.2.17 (official build)) (from ***:27713) (in query: select id from test.hdfs_table2 limit 1;), Stack trace (when copying this message, always include the lines below):
0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa20d85a in /usr/lib/debug/.build-id/29/eda0cc01fd10e7.debug
1. DB::KeysSerializationVersion::checkVersion(unsigned long) @ 0x12a3ab2a in /usr/lib/debug/.build-id/29/eda0cc01fd10e7.debug
2. DB::SerializationLowCardinality::deserializeBinaryBulkStatePrefix(DB::ISerialization::DeserializeBinaryBulkSettings&, std::__1::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>&) const @ 0x12a3ae43 in /usr/lib/debug/.build-id/29/eda0cc01fd10e7.debug
3. DB::MergeTreeReaderWide::readData(DB::NameAndTypePair const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, bool, unsigned long, unsigned long, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, COW<DB::IColumn>::immutable_ptr<DB::IColumn> > > >&, bool) @ 0x13b40800 in /usr/lib/debug/.build-id/29/eda0cc01fd10e7.debug
4. DB::MergeTreeReaderWide::readRows(unsigned long, unsigned long, bool, unsigned long, std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >&) @ 0x13b3f6cc in /usr/lib/debug/.build-id/29/eda0cc01fd10e7.debug
5. DB::MergeTreeRangeReader::DelayedStream::finalize(std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >&) @ 0x1426926e in /usr/lib/debug/.build-id/29/eda0cc01fd10e7.debug
6. DB::MergeTreeRangeReader::startReadingChain(unsigned long, std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange> >&) @ 0x1426dc20 in /usr/lib/debug/.build-id/29/eda0cc01fd10e7.debug
7. DB::MergeTreeRangeReader::read(unsigned long, std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange> >&) @ 0x1426c415 in /usr/lib/debug/.build-id/29/eda0cc01fd10e7.debug
8. DB::MergeTreeBaseSelectProcessor::readFromPartImpl() @ 0x14264b5f in /usr/lib/debug/.build-id/29/eda0cc01fd10e7.debug
9. DB::MergeTreeBaseSelectProcessor::readFromPart() @ 0x14265c6d in /usr/lib/debug/.build-id/29/eda0cc01fd10e7.debug
10. DB::MergeTreeBaseSelectProcessor::generate() @ 0x1426444b in /usr/lib/debug/.build-id/29/eda0cc01fd10e7.debug
11. DB::ISource::tryGenerate() @ 0x13fc99d5 in /usr/lib/debug/.build-id/29/eda0cc01fd10e7.debug
12. DB::ISource::work() @ 0x13fc959a in /usr/lib/debug/.build-id/29/eda0cc01fd10e7.debug
13. DB::SourceWithProgress::work() @ 0x141e2682 in /usr/lib/debug/.build-id/29/eda0cc01fd10e7.debug
14. DB::ExecutionThreadContext::executeTask() @ 0x13fe8fa3 in /usr/lib/debug/.build-id/29/eda0cc01fd10e7.debug
15. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x13fdd81e in /usr/lib/debug/.build-id/29/eda0cc01fd10e7.debug
16. DB::PipelineExecutor::executeImpl(unsigned long) @ 0x13fdc669 in /usr/lib/debug/.build-id/29/eda0cc01fd10e7.debug
17. DB::PipelineExecutor::execute(unsigned long) @ 0x13fdc378 in /usr/lib/debug/.build-id/29/eda0cc01fd10e7.debug
18. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) @ 0x13fecac7 in /usr/lib/debug/.build-id/29/eda0cc01fd10e7.debug
19. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa24e6b7 in /usr/lib/debug/.build-id/29/eda0cc01fd10e7.debug
20. void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) @ 0xa2520bd in /usr/lib/debug/.build-id/29/eda0cc01fd10e7.debug
21. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
22. __clone @ 0xfeb0d in /usr/lib64/libc-2.17.so

**Comment by windylcx** [comment]
here is the detail logs:
> <Error> executeQuery: Code: 117. DB::Exception: Invalid version for SerializationLowCardinality key column.: (while reading column id): (while reading from part ***/clickhouse/node1/disks/hdfs/store/3c0/3c04b60e-32c9-4b21-bc04-b60e32c94b21/20200101_1_6_1/ from mark 0 with max_rows_to_read = 1): While executing MergeTreeInOrder. (INCORRECT_DATA) (version 21.12.2.17 (official build)) (from ***:27713) (in query: select id from test.hdfs_table2 limit 1;), Stack trace (when copying this message, always include the lines below):
0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa20d85a in /usr/lib/debug/.build-id/29/eda0cc01fd10e7.debug
1. DB::KeysSerializationVersion::checkVersion(unsigned long) @ 0x12a3ab2a in /usr/lib/debug/.build-id/29/eda0cc01fd10e7.debug
2. DB::SerializationLowCardinality::deserializeBinaryBulkStatePrefix(DB::ISerialization::DeserializeBinaryBulkSettings&, std::__1::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>&) const @ 0x12a3ae43 in /usr/lib/debug/.build-id/29/eda0cc01fd10e7.debug
3. DB::MergeTreeReaderWide::readData(DB::NameAndTypePair const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, bool, unsigned long, unsigned long, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, COW<DB::IColumn>::immutable_ptr<DB::IColumn> > > >&, bool) @ 0x13b40800 in /usr/lib/debug/.build-id/29/eda0cc01fd10e7.debug
4. DB::MergeTreeReaderWide::readRows(unsigned long, unsigned long, bool, unsigned long, std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >&) @ 0x13b3f6cc in /usr/lib/debug/.build-id/29/eda0cc01fd10e7.debug
5. DB::MergeTreeRangeReader::DelayedStream::finalize(std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >&) @ 0x1426926e in /usr/lib/debug/.build-id/29/eda0cc01fd10e7.debug
6. DB::MergeTreeRangeReader::startReadingChain(unsigned long, std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange> >&) @ 0x1426dc20 in /usr/lib/debug/.build-id/29/eda0cc01fd10e7.debug
7. DB::MergeTreeRangeReader::read(unsigned long, std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange> >&) @ 0x1426c415 in /usr/lib/debug/.build-id/29/eda0cc01fd10e7.debug
8. DB::MergeTreeBaseSelectProcessor::readFromPartImpl() @ 0x14264b5f in /usr/lib/debug/.build-id/29/eda0cc01fd10e7.debug
9. DB::MergeTreeBaseSelectProcessor::readFromPart() @ 0x14265c6d in /usr/lib/debug/.build-id/29/eda0cc01fd10e7.debug
10. DB::MergeTreeBaseSelectProcessor::generate() @ 0x1426444b in /usr/lib/debug/.build-id/29/eda0cc01fd10e7.debug
11. DB::ISource::tryGenerate() @ 0x13fc99d5 in /usr/lib/debug/.build-id/29/eda0cc01fd10e7.debug
12. DB::ISource::work() @ 0x13fc959a in /usr/lib/debug/.build-id/29/eda0cc01fd10e7.debug
13. DB::SourceWithProgress::work() @ 0x141e2682 in /usr/lib/debug/.build-id/29/eda0cc01fd10e7.debug
14. DB::ExecutionThreadContext::executeTask() @ 0x13fe8fa3 in /usr/lib/debug/.build-id/29/eda0cc01fd10e7.debug
15. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x13fdd81e in /usr/lib/debug/.build-id/29/eda0cc01fd10e7.debug
16. DB::PipelineExecutor::executeImpl(unsigned long) @ 0x13fdc669 in /usr/lib/debug/.build-id/29/eda0cc01fd10e7.debug
17. DB::PipelineExecutor::execute(unsigned long) @ 0x13fdc378 in /usr/lib/debug/.build-id/29/eda0cc01fd10e7.debug
18. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) @ 0x13fecac7 in /usr/lib/debug/.build-id/29/eda0cc01fd10e7.debug
19. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa24e6b7 in /usr/lib/debug/.build-id/29/eda0cc01fd10e7.debug
20. void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) @ 0xa2520bd in /usr/lib/debug/.build-id/29/eda0cc01fd10e7.debug
21. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
22. __clone @ 0xfeb0d in /usr/lib64/libc-2.17.so

**Comment by alexey-milovidov** [comment]
We don't support HDFS.
