### ISSUE TITLE
Scriptable UDF example doesn't work

### ISSUE THREAD

**Issue by ramazanpolat** [ClickHouse/ClickHouse#34497]
**Describe the unexpected behaviour**
The scriptable UDF example introduced in ClickHouse v21.11 Release [Youtube Video ](https://youtu.be/S_kJ4tk8AaI?t=1399) does not work.

When run, produces this error message:
```bash
Received exception from server (version 22.1.3):
Code: 1. DB::Exception: Received from localhost:9000. DB::Exception: Executable file awk does not
 exist inside user scripts folder /var/lib/clickhouse/user_scripts/: While processing myPlus(1, 2). (UNSUPPORTED_METHOD)
```

**How to reproduce**
* Using version `22.1.3.7`
* Create a file named `my_plus_function.xml` with the following content:
```xml
<functions>
    <function>
        <type>executable</type>
        <name>myPlus</name>
        <argument><type>UInt64</type></argument>
        <argument><type>UInt64</type></argument>
        <return_type>UInt64</return_type>
        <format>TabSeparated</format>
        <command>awk '{ print $1 + $2 }'</command>
    </function>
</functions>
```
* Put the file in `/etc/clickhouse-server`
* Run `SYSTEM RELOAD FUNCTIONS`
* See the `system.function` shows the function: `SELECT name WHERE origin != 'System'`

**Additional context**
Also tried the [UDF example in clickhouse.com/learn/ ](https://clickhouse.com/learn/lessons/whatsnew-clickhouse-21.11/)which worked very well. But when tried on the installed version, it fails with same error message.

**Comment by ramazanpolat** [comment]
Thank you @kitaisreal your solution worked.

I've also have problems related to UDF.

### 1. Example in docs doesn't work
The example in https://clickhouse.com/docs/en/sql-reference/functions/#executable-user-defined-functions still doesn't work.

I placed `test_function.xml` file into `/etc/clickhouse-server` and `test_function.py` file under `/var/lib/clickhouse/user_scripts` folder.

I get this error message:
```bash
clickhouse-server :) select test_function_python(toUInt64(2))

SELECT test_function_python(toUInt64(2))

Query id: 8ad30a77-746c-49dd-a248-dbd4b385f4b7


0 rows in set. Elapsed: 0.007 sec.

Received exception from server (version 22.1.3):
Code: 75. DB::Exception: Received from localhost:9000. DB::Exception: Cannot write into pipe , 
errno: 32, strerror: Broken pipe: While executing TabSeparatedRowOutputFormat: While processing
 test_function_python(toUInt64(2)). (CANNOT_WRITE_TO_FILE_DESCRIPTOR)
```

### 2. Need clarification on the location of UDF config files
From the documentation:
> ClickHouse can call any external executable program or script to process data. Describe such functions in a [configuration file](https://clickhouse.com/docs/en/operations/configuration-files/) and add the path of that file to the main configuration in user_defined_executable_functions_config setting.

From this, I understand that we must place `test_function.xml` file under `/etc/clickhouse-server` directory.  But then, documentation says this:
> User defined function configurations are searched relative to the path specified in the `user_files_path` setting.

While `user_files_path` is configured in `config.xml` as to be `/var/lib/clickhouse/user_files/` by default.

### 3. Clarification of user_* folders
Can you please clarify the roles of these folders?
* /var/lib/clickhouse/user_defined
* /var/lib/clickhouse/user_files
* /var/lib/clickhouse/user_scripts

**Comment by alexey-milovidov** [comment]
Yes, that's a problem. I'm copy-pasting the example between my presentations without noticing:
```
$ rg -F "awk '"
release_21.10/index.html
156:  &lt;command><b>awk '{ print $1 + $2 }'</b>&lt;/command>

stw2021/index.html
109:  &lt;command><b>awk '{ print $1 + $2 }'</b>&lt;/command>

meetup56/new_features/index.html
70:  &lt;command><b>awk '{ print $1 + $2 }'</b>&lt;/command>

yatalks_2019_moscow/index.html
240:awk '

meetup57/top_features/index.html
182:  &lt;command><b>awk '{ print $1 + $2 }'</b>&lt;/command>

release_21.11/index.html
123:  &lt;command><b>awk '{ print $1 + $2 }'</b>&lt;/command>
```

**Comment by alexey-milovidov** [comment]
https://github.com/ClickHouse/clickhouse-presentations/commit/1b8adc177a9b436fffdfaf99c52ee50b71ddb62d

**Comment by Dong-GuoSheng** [comment]
> ```shell
> test_function_python
> ```

chmod +x test_function_python.py

**Comment by standchan** [comment]
make sure file *_function.xml、test_function_python.py belong to clickhouse:clickhouse
chown *_function.xml、test_function_python.py clickhouse:clickhouse AND
chmod 750 *_function.xml、test_function_python.py

it will work

**Comment by imysm** [comment]
> make sure file *_function.xml、test_function_python.py belong to clickhouse:clickhouse chown *_function.xml、test_function_python.py clickhouse:clickhouse AND chmod 750 *_function.xml、test_function_python.py
> 
> it will work

But I got this error:

Received exception from server (version 22.3.2):
Code: 46. DB::Exception: Received from localhost:9000. DB::Exception: Unknown function test_function_python: While processing test_function_python(toUInt64(2)). (UNKNOWN_FUNCTION)

**Comment by oleg-savko** [comment]
> make sure file *_function.xml、test_function_python.py belong to clickhouse:clickhouse chown *_function.xml、test_function_python.py clickhouse:clickhouse AND chmod 750 *_function.xml、test_function_python.py
> 
> it will work

still not worked for me :(

```
root@18ca02355088:/# ls -lah /etc/clickhouse-server/
total 64K
drwxr-xr-x 5 root       root       4.0K Apr 26 11:43 .
drwxr-xr-x 1 root       root       4.0K Apr 26 11:49 ..
-rwxr-x--- 1 clickhouse clickhouse  855 Apr 26 11:39 user_function.xml
...
```

```
root@18ca02355088:/# ls -lah /var/lib/clickhouse/user_scripts
total 16K
drwxr-xr-x  2 clickhouse clickhouse 4.0K Apr 26 11:39 .
drwxr-xr-x 15 clickhouse clickhouse 4.0K Apr 26 11:49 ..
-rwxr-x---  1 clickhouse clickhouse  151 Apr 26 11:39 test_function.py
-rwxr-xr-x  1 clickhouse clickhouse  349 Apr 26 11:39 test_function_sum_json.py
```

```
SELECT test_function_python(toUInt64(2));
Code: 75. DB::ErrnoException: Cannot write into pipe , errno: 32, strerror: Broken pipe: While executing TabSeparatedRowOutputFormat: While processing test_function_python(toUInt64(2)). (CANNOT_WRITE_TO_FILE_DESCRIPTOR) (version 22.3.3.44 (official build))
```

**Comment by ramazanpolat** [comment]
@oleg-savko Can you try the following sample. 

`/etc/clickhouse-server/test_function.xml`:

```xml
<functions>                                    
    <function>                                 
        <type>executable</type>                
        <name>test_function_python</name>      
        <return_type>String</return_type>      
        <argument><type>Int64</type></argument>
        <format>TabSeparated</format>          
        <command>test_function.py</command>    
        <execute_direct>1</execute_direct>     
    </function>                                
</functions>
```

`/var/lib/clickhouse/user_scripts/test_function.py`:
```py
#!/usr/bin/python3

import sys

if __name__ == '__main__':
    i = 0
    for line in sys.stdin:
        print(i, line, end='')
        sys.stdout.flush()
        i += 1
```

Fix permission:
```bash
chmod a+x /var/lib/clickhouse/user_scripts/test_function.py
```

From `clickhouse-client`:
```sql
ELECT test_function_python(number) AS x                     
FROM numbers(5)                                              
                                                             
Query id: 32a8e725-5267-4aae-bb21-5e537ff377c0               
                                                             
Connecting to localhost:9000 as user default.                
Connected to ClickHouse server version 22.2.2 revision 54455.
                                                             
┌─x───┐                                                      
│ 0 0 │                                                      
│ 1 1 │                                                      
│ 2 2 │                                                      
│ 3 3 │                                                      
│ 4 4 │                                                      
└─────┘                                                      
                                                             
5 rows in set. Elapsed: 0.147 sec.
```

**Comment by oleg-savko** [comment]
also I run clickhouse in docker container, maybe he dont have installed python?
and I should prepare custom image with him, for that? 

what is the best option for using it in docker?

**Comment by ramazanpolat** [comment]
@oleg-savko I've just tried it and it worked for me.

```sql
SELECT
    now(),
    test_function_python(number)
FROM numbers(10)

Query id: 05ee4f93-dba8-4577-b947-3a42ba537ca2

┌───────────────now()─┬─test_function_python(number)─┐
│ 2022-04-28 15:30:12 │ 0 0                          │
│ 2022-04-28 15:30:12 │ 1 1                          │
│ 2022-04-28 15:30:12 │ 2 2                          │
│ 2022-04-28 15:30:12 │ 3 3                          │
│ 2022-04-28 15:30:12 │ 4 4                          │
│ 2022-04-28 15:30:12 │ 5 5                          │
│ 2022-04-28 15:30:12 │ 6 6                          │
│ 2022-04-28 15:30:12 │ 7 7                          │
│ 2022-04-28 15:30:12 │ 8 8                          │
│ 2022-04-28 15:30:12 │ 9 9                          │
└─────────────────────┴──────────────────────────────┘
```

**Comment by kitaisreal** [comment]
@ramazanpolat
1. Example in docs doesn't work - Updated examples.
2. Need clarification on the location of UDF config files - Updated documentation https://github.com/ClickHouse/ClickHouse/pull/36757.
3. Documentation for user_defined folder updated in https://github.com/ClickHouse/ClickHouse/pull/36753. Documentation for user_scripts updated in https://github.com/ClickHouse/ClickHouse/pull/36757. Documentation for user_files folder already exists.
