### ISSUE TITLE
Columnar JSON format

### ISSUE THREAD

**Issue by pibi** [ClickHouse/ClickHouse#34509]
**Use case**
We are using clickhouse in a fintech web application. We manage financial data, generate reports in real time and even stream bars and trade events for real-time like simulations. Latency is a very strict requirement in this scenario. We are actually using a custom HTTP based driver using the `JSONCompactEachRowWithNamesAndTypes` format and we are also planning to move most of our heavy data computations directly on the database's nodes via UDF.  

From the documentation and some in-house tests, we know that the `Native` format is the most efficient, followed by `RowBinary`, and `TabSeparated*` & `JSONCompact*`. We are actually using a JSON based output format for the sake of readibility on both the transport level and the client parser.

**Describe the solution you'd like**

Documentation says that every row-based output format is less efficient than the column-based one. We think a "human-readable" column-based output format could be more efficient than the current JSON formats. Also, columnar serialization and data management is pretty common on the fintech field. For example, typical bars being submitted to a charting library like tradingview, have this format:

```
{
   s: "ok",
   t: [1386493512, 1386493572, 1386493632, 1386493692],
   c: [42.1, 43.4, 44.3, 42.8],
   o: [41.0, 42.9, 43.7, 44.5],
   h: [43.0, 44.1, 44.8, 44.5],
   l: [40.4, 42.1, 42.8, 42.3],
   v: [12000, 18500, 24000, 45000]
}
```
Beside the `s` property (which is out of the scope of this issue) , all the others could be just unordered column dumps. 

With these  `JSONColumnar*` output formats we can avoid useless conversions on the client side and improve the latency of our applications.

**Describe alternatives you've considered**

We have considered to parse the 'Native' format, but we we would like to keep the 'human-readable' characteristic of our current APIs

**Comment by Avogar** [comment]
https://github.com/ClickHouse/ClickHouse/issues/36338
