### ISSUE TITLE
Reload Function bug report

### ISSUE THREAD

**Issue by IVitamin-C** [ClickHouse/ClickHouse#34514]
hi,
v21.12.3.1-stable
clickhouse-client execute 'system RELOAD FUNCTION on cluster cluster test_function;'
Actual execution differs from expectations.

![image](https://user-images.githubusercontent.com/35019926/153533788-53ed9c1f-d383-4bc8-b85e-d1828328ad7e.png)

**Comment by kitaisreal** [comment]
Fixed in https://github.com/ClickHouse/ClickHouse/pull/34696.
