### ISSUE TITLE
Missed `regex:` in the predefined_query_handler example

### ISSUE THREAD

**Issue by darkleaf** [ClickHouse/ClickHouse#34530]
https://clickhouse.com/docs/ru/interfaces/http/#predefined_query_handler
https://github.com/ClickHouse/ClickHouse/blob/b29e877f269e84ae452c446e70b406a695863470/tests/integration/test_http_handlers_config/test_predefined_handler/config.xml

Instead of `<url><![CDATA[/query_...` it should be `<url><![CDATA[regex:/query_...`.
`regex:` is missed.

**Comment by rfraposa** [comment]
Thanks! Fixed

**Comment by LGDHuaOPER** [comment]
I have a question. Why do I add `http_handlers > rule` configuration in config.xml, then I exec `curl localhost:8123` or `curl localhost:8123/replicas_status`, it made the following error:
![550AC34ECE7B64EBC8325B007F1EC20E](https://user-images.githubusercontent.com/22699037/205584310-c0f07e58-b295-4028-aca5-adaf58606104.jpg)

The http_handlers rule is:
![image](https://user-images.githubusercontent.com/22699037/205584755-29ce8688-aad7-4c48-85ff-0892c1f5e548.png)

Thanks!
