### ISSUE TITLE
Credentials from environment variables for `clickhouse-client`

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#34538]
The idea from @qoega 

**Use case**

Connect to your cloud ClickHouse instance easily.

**Describe the solution you'd like**

If user and/or password is not specified in command line or configuration file, get them from `CLICKHOUSE_USER` / `CLICKHOUSE_PASSWORD` environment variables.

If there is no such variable, it should work as before (with user `default` and empty password).

**Comment by freedomDR** [comment]
Maybe I can achieve it？

**Comment by alexey-milovidov** [comment]
@freedomDR Yes, it will be wonderful!
