### ISSUE TITLE
A setting `content_type` to force specified `Content-Type` in output.

### ISSUE THREAD

**Issue by darkleaf** [ClickHouse/ClickHouse#34531]
I want to add a `predefined_query_handler` to serve a single JSON from my query.
For example

```xml
<rule>
      <url>/my/url</url>
      <methods>GET</methods>
      <handler>
        <type>predefined_query_handler</type>
        <query>select '{"my": "json"}' format JSONAsString</query>
      </handler>
    </rule>
```

I can use `RawBLOB` but it sets up Content-Type 'text/plain' instead of 'application/json'.
I think JSONAsString should also work with output.

**Comment by alexey-milovidov** [comment]
I'm concerned that this format will mean nothing different to `LineAsString`, `TSVRaw` except the Content-Type,
and you can easily write invalid JSON with this format. It makes the semantic of this format very subtle.

Maybe we can add a setting `content_type` to force content type for all formats?

**Comment by darkleaf** [comment]
Setting content_type will be ok.
