### ISSUE TITLE
Website: top menu not visible on mobile

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#3454]
When screenwidth is smaller than 1024 pixels top menu disappears (enough to make browswer window smaller or check the site on mobile), and it's hard to navigate / find a link to documentation page.

**Comment by blinkov** [comment]
I think it's about front page, not documentation itself. 

There's a second link to documentation at "Quick start" section near the bottom, so it's just two taps if you know what you are doing. Maybe we could add a third link as some sort of icon on first screen in narrow mode, but there's not much room and it'll distract the newcomers.

**Comment by filimonov** [comment]
New version of the website solves the issue. Thanks, @blinkov
