### ISSUE TITLE
Sub-queries and I/O error: Broken pipe

### ISSUE THREAD

**Issue by x052bb** [ClickHouse/ClickHouse#34553]
Hi all

I have a ReplicatedMergeTree table X in a cluster that has 2 shards 4 replicas per shard - so 8 nodes in total.
I have a Distributed table Y that looks at table X.

There're some quite complex queries running selecting data from Y, they finish successfully. However, I can see a lot of errors like this in the log:

> Code: 210. DB::NetException: I/O error: Broken pipe, while writing to socket (XXX.XXX.XXX.XXX:42762). (NETWORK_ERROR) 

Looking at the queries that fail with the above error, I can see that they are sub-queries spawned by original query and running on different replicas.

Question: 

Is this something I should worry about? If yes, what could be the root cause? (Clickhouse v21.9)

**Comment by e-mars** [comment]
Hi @x052bb ,

From the error, this appears to be mainly related to network infrastructure or to the hosts closing the network connections.

the connection was established as some point and the connection got closed or network in between stopped communicating.
The system should try to re-establish the connection.

when you see the error in the log, is it to random nodes? or is it only between certain nodes?
Are these nodes physical onsite or are they on cloud instances (AWS EC2, etc.)
Could you give us an idea of what the node resource specifications are and what the approximate size of the datasets and queries performed (such as joins, etc.)?

ensure that you have sufficient memory resources.
Check the logs to see if there are connection timeouts from the client.
you can try to increase the send and receive timeouts:
https://clickhouse.com/docs/en/operations/settings/settings/#connect-timeout-receive-timeout-send-timeout 

thanks.

**Comment by xinobu** [comment]
I restart the clickhouse servers and get some errors on the nodes of shard 1(cdh01, cdh02, cdh03) as follows:

> : While sending /data/clickhouse/store/da8/da80bfd4-7a20-489a-b867-4f7a93399920/shard2_all_replicas/1.bin. 

> (ALL_CONNECTION_TRIES_FAILED), Stack trace (when copying this message, always include the lines below):
> 
> 0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa82d07a in /usr/bin/clickhouse
> 1. PoolWithFailoverBase<DB::IConnectionPool>::getMany(unsigned long, unsigned long, unsigned long, unsigned long, bool, std::__1::function<PoolWithFailoverBase<DB::IConnectionPool>::TryResult (DB::IConnectionPool&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)> const&, std::__1::function<unsigned long (unsigned long)> const&) @ 0x145327bb in /usr/bin/clickhouse
> 2. PoolWithFailoverBase<DB::IConnectionPool>::get(unsigned long, bool, std::__1::function<PoolWithFailoverBase<DB::IConnectionPool>::TryResult (DB::IConnectionPool&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)> const&, std::__1::function<unsigned long (unsigned long)> const&) @ 0x1453033f in /usr/bin/clickhouse
> 3. DB::ConnectionPoolWithFailover::get(DB::ConnectionTimeouts const&, DB::Settings const*, bool) @ 0x14530230 in /usr/bin/clickhouse
> 4. DB::StorageDistributedDirectoryMonitor::processFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x14193e05 in /usr/bin/clickhouse
> 5. DB::StorageDistributedDirectoryMonitor::run() @ 0x1418fa78 in /usr/bin/clickhouse
> 6. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x12f8470e in /usr/bin/clickhouse
> 7. DB::BackgroundSchedulePool::threadFunction() @ 0x12f870a7 in /usr/bin/clickhouse
> 8. ? @ 0x12f88170 in /usr/bin/clickhouse
> 9. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa86f4b7 in /usr/bin/clickhouse
> 10. ? @ 0xa872ebd in /usr/bin/clickhouse
> 11. start_thread @ 0x76db in /lib/x86_64-linux-gnu/libpthread-2.27.so
> 12. /build/glibc-uZu3wS/glibc-2.27/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:97: clone @ 0x12161f in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.27.so
>  (version 22.1.3.7 (official build))
> 2022.09.28 13:21:35.291411 [ 35082 ] {} <Warning> ConnectionPoolWithFailover: Connection failed at try №1, reason: Code: 210. DB::NetException: Connection refused (cdh06:9000). (NETWORK_ERROR) (version 22.1.3.7 (official build))
> 2022.09.28 13:21:35.291931 [ 35082 ] {} <Warning> ConnectionPoolWithFailover: Connection failed at try №1, reason: Code: 210. DB::NetException: Connection refused (cdh04:9000). (NETWORK_ERROR) (version 22.1.3.7 (official build))
> 2022.09.28 13:21:35.292482 [ 35082 ] {} <Warning> ConnectionPoolWithFailover: Connection failed at try №1, reason: Code: 210. DB::NetException: Connection refused (cdh05:9000). (NETWORK_ERROR) (version 22.1.3.7 (official build))
> 2022.09.28 13:21:35.292836 [ 35082 ] {} <Error> network_2s_3r.t_dhcp_all.DirectoryMonitor: Code: 279. DB::NetException: All connection tries failed. Log:
> 
> Code: 210. DB::NetException: Connection refused (cdh06:9000). (NETWORK_ERROR) (version 22.1.3.7 (official build))
> Code: 210. DB::NetException: Connection refused (cdh04:9000). (NETWORK_ERROR) (version 22.1.3.7 (official build))
> Code: 210. DB::NetException: Connection refused (cdh05:9000). (NETWORK_ERROR) (version 22.1.3.7 (official build))
