### ISSUE TITLE
I'm about to collapse...Why can't I connect after installation?

### ISSUE THREAD

**Issue by YiFlower** [ClickHouse/ClickHouse#34563]
Today, after I installed clickhouse, I did two operations on the configuration:
1. Modify the port number to 9090
config.xml
`<tcp_port>9090</tcp_port>`
`<!-- Default values - try listen localhost on IPv4 and IPv6. -->`
 `   <listen_host>::1</listen_host>`
`    <listen_host>127.0.0.1</listen_host>` 

2. Modify the plaintext password
user.xml
`<password>password</password>`

Then, two problems arose
1. You cannot use IP to connect, you can only use localhost
2. Port 8123 cannot be accessed
![image](https://user-images.githubusercontent.com/70850418/153755109-b591dff9-e07e-4d46-ac66-8dd8d9557aa1.png)

I think this problem is very confusing, I tried to find a solution on the official website, but did not find it.
I want to accomplish two things
1. Ability to connect clickhouse using DBeaver
2. Create a three-node clickhouse cluster
But now I have a problem with a single node and can't connect.

Hope you all can help me!!!THAAAAAAAAAAAKS!!!

**Comment by den-crane** [comment]
set only `<listen_host>::1</listen_host>` 

When you use `<listen_host>::1</listen_host><listen_host>127.0.0.1</listen_host>` the second setting overwrites the first.

**Comment by alexey-milovidov** [comment]
@den-crane You did not answer about the misuse of HTTP port for clickhouse-client.

**Comment by den-crane** [comment]
>You did not answer about the misuse of HTTP port for clickhouse-client.

I guessed it was just a test that port is unavailable.

@YiFlower 
Anyway, OK: clickhouse-client supports only TCP/Native protocol == port 9000.

And steps are
1. Make sure CH listen the proper host / port
```
netstat -nltp|grep click
tcp6       0      0 :::9000                 :::*                    LISTEN      29214/clickhouse-se
tcp6       0      0 :::9004                 :::*                    LISTEN      29214/clickhouse-se
tcp6       0      0 :::9005                 :::*                    LISTEN      29214/clickhouse-se
tcp6       0      0 :::9009                 :::*                    LISTEN      29214/clickhouse-se
tcp6       0      0 :::9363                 :::*                    LISTEN      29214/clickhouse-se
tcp6       0      0 :::8123                 :::*                    LISTEN      29214/clickhouse-se
```
2. make sure firewall allows required ports.
3. check ports are available remotely
```
$ curl chservernameOrIP:8123/ping
Ok. 

$ curl chservernameOrIP:9000
Port 9000 is for clickhouse-client program.
You must use port 8123 for HTTP.
```

**Comment by Algunenano** [comment]
> Is there a way to use clickhouse-client via http?

No, clickhouse-client is native only.
