### ISSUE TITLE
Why keeper quorum read perform a whole raft algorithm?

### ISSUE THREAD

**Issue by zhanglistar** [ClickHouse/ClickHouse#34564]
In my option, quorum read is a way to do a strong consistent read. If so, why not just forward read request to leader which does not need perform a whole raft algorithm resulting a higher performance?

**Comment by den-crane** [comment]
In some cases it has sense to send request to localhost (if keeper in the same process) or to the nearest keeper node.

The network traffic between CH and ZK can be quite large ~ 100 - 300 Mbit.
In AWS cloud we setup CH replicas and Keeper servers in different availability zones (AZ). And the traffic is not free among different AZ. So if replica uses ZK in another availability zone then it's not cheap.

Also it allows to share read load among several nodes. 

And it's much faster if you read from localhost.

**Comment by alexey-milovidov** [comment]
Maybe @alesapin can help?

**Comment by zhanglistar** [comment]
> 
@den-crane 
Thanks for your reply. But I think that my question is not answered yet. 
Let's make more details here, 1st question is: is quorum read for strong consistent read?
If yes, then what about just forward the read request to leader without running the whole raft algorithm?
Because:
1) read request dost not cause the state machine changing
2) whole raft algorithm is heavy, involving disk appending and network replication
Am I wrong at some point?

**Comment by zhanglistar** [comment]
OK, I have got that only read leader still can not satisfy the strong consistent read if network partition occurs.
That is original leader is not the leader now.

**Comment by zhanglistar** [comment]
Update: in nuraft, we can get linearizable read by reading leader state machine which is much faster than read as proposal method, nuraft provides:
1. Leadership Expiration
2. pre-vote
refer to: https://github.com/eBay/NuRaft/blob/master/docs/leadership_expiration.md
Wha's your advice? @alesapin

**Comment by zhanglistar** [comment]
@alesapin Does there need to do this? I mean, in clickhouse, linearizable read is a must or not? @alexey-milovidov
