### ISSUE TITLE
Using `SETTINGS` in the definition of a system table causes repeated table renaming and creation

### ISSUE THREAD

**Issue by depressed-pho** [ClickHouse/ClickHouse#34572]
**Describe what's wrong**

The [documentation](https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings/#server_configuration_parameters-query-log) says that we can use an element `<engine>` to customize the engine used for a system table. However, when the `<engine>` contains a `SETTINGS` clause like the following example, each time a new entry is to be inserted ClickHouse considers the current table schema as obsolete so it renames and re-creates the table:
```xml
<query_log>
    <database>system</database>
    <table>query_log</table>
    <engine>
        Engine = MergeTree
            PARTITION BY event_date
            ORDER BY event_time
            TTL event_date + INTERVAL 30 day
            SETTINGS ttl_only_drop_parts=1   <!-- This is the line that causes the trouble. -->
    </engine>
    <flush_interval_milliseconds>7500</flush_interval_milliseconds>
</query_log>
```

The issue is presumably in [getCreateTableQueryClean()](https://github.com/ClickHouse/ClickHouse/blob/master/src/Interpreters/SystemLog.cpp#L115) which removes `SETTINGS` in the table schema before the comparison. I'm not sure what is the best way to fix this. Maybe it should fill default settings in the new schema, instead of removing settings from the old one?

**Does it reproduce on recent release?**

It happens on 21.12.2.17-release.

**Expected behavior**

System tables get renamed and re-created only when their schema actually change, regardless of whether they have SETTINGS or not.

**Comment by rschu1ze** [comment]
Fixed by #34949
