### ISSUE TITLE
Allow to require password complexity for SQL password creation

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#34588]
**Use case**

Force strong passwords for all users created in SQL.

**Describe the solution you'd like**

1) Add configuration with some predefined strength configs and probably custom ones. There is length, requirements of special symbols, allowed symbols etc are defined.
2) Check password strength on user creation when password is passed in plaintext.

**Comment by pavan-datazip** [comment]
@qoega Is this feature implemented? I am looking for the same thing

**Comment by qoega** [comment]
@santrancisco maybe you know how configuration of password complexity is called and how to add it? I can't find docs around it. @justindeguzman fyi

**Comment by melvynator** [comment]
This is the PR: https://github.com/ClickHouse/ClickHouse/pull/43719
The config is defined in

**Comment by melvynator** [comment]
This is the PR: https://github.com/ClickHouse/ClickHouse/pull/43719
The config is defined in the config file: https://github.com/ClickHouse/ClickHouse/blob/master/programs/server/config.xml#L495
