### ISSUE TITLE
Why not allowed to change a timeout setting, sync_request_timeout?

### ISSUE THREAD

**Issue by zhangjmruc** [ClickHouse/ClickHouse#34597]
There are many settings that related to timeout, like send_timeout, receive_timeout. Some of them are configurable, like receive_timeout. However, there is a timeout for synchronous request-result protocol call (like Ping or TableStatus): **sync_request_timeout** (default is 5s), the one is not allowed to set by user. In some cases, when the servers are busy and timeout may happen in Connection::getTablesStatus(), since 5 seconds is very short.

Would you mind to explain why the "sync_request_timeout" is not allowed to be changed? Or what kind of considerations for this behavior?

**Comment by sgycs** [comment]
sync_request_timeout – timeout for server ping. Defaults to 5 seconds.
In some cases, if the data sync request time out, it may be casued by many different reasons, basically it shouldn't take more than 5 seconds for synchronous request-result protocol call (like Ping or TableStatus) in most of the normal circumstances , thus if time out setting too long, eg. 5 minutes or longer than that , then you will run into more overall performance issues.  This is not good for any application on the server.

**Comment by melvynator** [comment]
Thanks @sgycs
