### ISSUE TITLE
Dotall flag seems to be True by default in regex pattern matching functions

### ISSUE THREAD

**Issue by xoelop** [ClickHouse/ClickHouse#34603]
ClickHouse uses the [re2 syntax](https://github.com/google/re2/wiki/Syntax) for regular expressions matching. According to the re2 docs, the `s` flag is `false` by default, but in CH it seems to be `true` by default. 

For example, the string `a\nb` shouldn't match the pattern `a.b`, but it does. Tested both in 20.7 and in 21.8

To reproduce
```sql
SELECT match('a\nb', 'a.b')
```
returns 1 instead of 0

IMO the default behavior should be to have that flag disables, as stated by the docs. 

Note: A workaround is to disable the flag in every pattern, adding `(?-s)` to the beginning of the pattern, like in 
```sql
SELECT match('a\nb', '(?-s)a.b')
```

**Comment by rschu1ze** [comment]
Thanks for the hint. I don't think `match()`'s behavior can't be changed due to backwards compat but we should at least mention this + the workaround in the docs.
