### ISSUE TITLE
create table failed, because dictionary table was not created

### ISSUE THREAD

**Issue by sunny19930321** [ClickHouse/ClickHouse#34602]
Create a table that contains the dictionary table, but the dictionary is created later，
```
CREATE TABLE behavior_follow_local
(
    `user_log_acct` String,
    `item_sku_id` String,
    `self_or_pop` String,
    `is_worldwide_buy` String,
    `item_first_cate_cd` String,
    `item_second_cate_cd` String,
    `item_third_cate_cd` String,
    `brand_cd` String,
    `shop_id` String,
    `follow_flag` UInt8,
    `uid` UInt64 DEFAULT dictGet('label.user_pin_dict_local', 'uid', user_log_acct),
    `dt` String
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/default/behavior_follow_local/{shard}', '{replica}')
PARTITION BY dt
ORDER BY (dt, user_log_acct)
SETTINGS index_granularity = 8192

Query id: 9d90145c-9404-4cdc-b819-6f9c845f4ab7


0 rows in set. Elapsed: 0.009 sec.

Received exception from server (version 22.2.1):
Code: 36. DB::Exception: Received from localhost:9000. DB::Exception: Dictionary (`label.user_pin_dict_local`) not found: While processing _CAST(dictGet('label.user_pin_dict_local', 'uid', user_log_acct) AS uid_tmp_alter16543853608632959774, 'UInt64') AS uid: default expression and column type are incompatible.. (BAD_ARGUMENTS)
```

**Comment by sunny19930321** [comment]
I think if the dictionary table does not exist to give a default value for a type, I plan to add this feature

**Comment by tavplubix** [comment]
This feature is questionable, because `DEFAULT` clause will be silently ignored if there's a typo in dictionary name, such behavior may be misleading. We could add a setting, but I think that this feature does not worth adding a setting. You should either create dictionary first or create table without `DEFAULT` clause in column definition and add it later using `ALTER MODIFY COLUMN`.

**Comment by sunny19930321** [comment]
there will be dependencies between table creations, which can be problematic when machine failure data is recovered

**Comment by tavplubix** [comment]
See #15170, #7944, #34343

**Comment by sunny19930321** [comment]
yes, as with this problem,  if I know the dependencies between tables,  I can create the dependent tables before restoring the tables
