### ISSUE TITLE
Executable UDF: read / write other data formats than TabSeparated 

### ISSUE THREAD

**Issue by youennL-cs** [ClickHouse/ClickHouse#34604]
Hi, 
I'm trying to figure out how read / write some data formats that are not TabSeparated (e.g. [Native](https://clickhouse.com/docs/en/interfaces/formats/#native) or [JSONEachRow](https://clickhouse.com/docs/en/interfaces/formats/#jsoneachrow)) in my EUDF -  C++ script. 

Context:
I already succeed to implement some EUDF but always with TabSeparated or CSV. However, in one of my script I'm looking for performance on a quite big array. The query is executed in ~10sec while my script takes ~2sec to execute (bench with RDTSC). Since the query is just calling my script (called in the same way that the example), I guess that the data format conversion may be too heavy. 
In order to benchmark several types and find the best compromise between fastest input/output transfert and serialisation/deserialisation  speed, I made a very simple c++ code. This code writes in standard output, what is read from standard input (see below). However, as you already guessed, I'm struggling with some data formats.

I have a table (`table1`) with one column of `Array(UInt64)` that I send as one block of `Array(Array(UInt64))` to my script using `groupArray`. 
In the below example I'm just writing what I read from the client.

info:
Clickhouse version 22.2.1

This is what I use for my tests.

my_function.xml
```
<clickhouse>
<functions>
        <type>executable</type>
        <name>data_debug</name>
        <return_type>Array(Array(UInt64))</return_type>
        <argument>
            <type>Array(Array(UInt64))</type>
        </argument>
        <format>Native</format>
        <command>data_debug</command>
</functions>
</clickhouse>
```
My c++ script data_debug.cpp:
```
#include <iostream>

int main(int argc, char **argv)
{
  std::string line;

  std::cin.tie(nullptr);
  std::cin.sync_with_stdio(false);

  std::cout.tie(nullptr);
  std::cout.sync_with_stdio(false);

  while(std::cin >> line) {
    std::cout << line << "\n";
    std::cout.flush();
  }
  return 0;
}
```
Compile with:
`g++ -std=c++11 -O3  data_debug.cpp -o data_debug`
Executed in CH client as follow:
`SELECT data_debug(groupArray(table1.journey)) FROM table1`

Leads to this error:
```
Received exception from server (version 22.2.1):
Code: 10. DB::Exception: Received from localhost:9000. DB::Exception: Not found column groupArray(journey) in block. There are only columns: result: While executing Native: While executing ShellCommandSource. (NOT_FOUND_COLUMN_IN_BLOCK)
```
When I use the JSONEachRows format I get: 
```
Received exception from server (version 22.2.1):
Code: 117. DB::Exception: Received from localhost:9000. DB::Exception: Unknown field found while parsing JSONEachRow format: groupArray(journey): (at row 1)
: While executing ParallelParsingBlockInputFormat: While executing ShellCommandSource: while executing 'FUNCTION data_debug(groupArray(journey) :: 0) -> data_debug(groupArray(journey)) Array(Array(UInt64)) : 1'. (INCORRECT_DATA)
```

Can you tell me what I'm doing wrong with these two types ? Cause if even if CH doesn't accept what he sent itself, I don't know what to do differently.

**Comment by UnamedRus** [comment]
I have some doubts about Native format, RowBinary looks like a better option for me.

**Comment by youennL-cs** [comment]
I have same kind of issue (with the same program and config, etc) with RowBinary
```
Received exception from server (version 22.2.1):
Code: 33. DB::Exception: Received from localhost:9000. DB::Exception: Cannot read all data. Bytes read: 1. Bytes expected: 8.: (at row 1)
: While executing BinaryRowInputFormat: While executing ShellCommandSource: while executing 'FUNCTION data_debug(groupArray(journey) :: 0) -> data_debug(groupArray(journey)) Array(Array(UInt64)) : 1'. (CANNOT_READ_ALL_DATA)
```

**Comment by UnamedRus** [comment]
I'm not a true cpp developer, but something like that works for me:

```
// standard includes
#include <iostream>
#include <fstream>
#include <cassert>
#include <vector>
#include <sstream>

std::string write_uleb128 (size_t x) {
    unsigned char buf[10];
    size_t bytes = 0;
    do {
        buf[bytes] = x & 0x7fU;
        if (x >>= 7) buf[bytes] |= 0x80U;
        ++bytes;
    } while (x);
    std::string ret(&buf[0], &buf[bytes]);
    return ret;
}

size_t read_uleb128 (std::istream *in, uint64_t *x) {
    unsigned char buf;
    size_t bytes = 0;
    while (in->read((char*)&buf,1)) {
        if (bytes == 0) *x = 0;
        *x |= (buf & 0x7fULL) << (7 * bytes++);
        if (!(buf & 0x80U)) break;
    }
    return bytes;
}

int main()
{
  size_t size = 0;
  read_uleb128(&std::cin, &size);
  while(size > 0)
  {
    for (size_t i=0; i < size; ++i)
    {
      std::cin.read((char*)&points[i].x, sizeof(long));
      std::cin.read((char*)&points[i].y, sizeof(long));
    }


....
    std::cout << write_uleb128((size_t)size); 
    size=0;
    read_uleb128(&std::cin, &size);
  }
  return 0;
}
```

**Comment by youennL-cs** [comment]
Where did you get this code ? 
On one side, I understand the decode/encode part to know what to read. However, on the other side, it miss me few information to fully understand. 
For example what is that `points` struct ? It looks like it reads two points (coordinate? int?) as tuple and set a vector of coordinates. 

By the way, if I send what I receive it should be the same **LEB128 + message**, right ? But it returns the previous error. Same if I try to change your code into something closer to what I have I still have an error so I'm wondering, again, what I missed. And same again if I don't change anything, just replace points by strings (as well as types in the *"_function.xml")

**Comment by UnamedRus** [comment]
> Where did you get this code ?

Write it.

>  For example what is that points struct ? It looks like it reads two points (coordinate? int?) as tuple and set a vector of coordinates.

Yeah, it was using some lib, i just removed all unrelated parts

> By the way, if I send what I receive it should be the same LEB128 + message, right ?

You need to send LEB128 only for arrays or strings https://clickhouse.com/docs/en/interfaces/formats/#rowbinary

```
Integers use fixed-length little-endian representation. For example, UInt64 uses 8 bytes.
DateTime is represented as UInt32 containing the Unix timestamp as the value.
Date is represented as a UInt16 object that contains the number of days since 1970-01-01 as the value.
String is represented as a varint length (unsigned [LEB128](https://en.wikipedia.org/wiki/LEB128)), followed by the bytes of the string.
FixedString is represented simply as a sequence of bytes.

Array is represented as a varint length (unsigned [LEB128](https://en.wikipedia.org/wiki/LEB128)), followed by successive elements of the array.
```

```
main.cpp


// standard includes
#include <iostream>
#include <fstream>
#include <cassert>
#include <vector>
#include <sstream>


std::string write_uleb128 (size_t x) {
    unsigned char buf[10];
    size_t bytes = 0;
    do {
        buf[bytes] = x & 0x7fU;
        if (x >>= 7) buf[bytes] |= 0x80U;
        ++bytes;
    } while (x);
    std::string ret(&buf[0], &buf[bytes]);
    return ret;
}

size_t read_uleb128 (std::istream *in, uint64_t *x) {
    unsigned char buf;
    size_t bytes = 0;
    while (in->read((char*)&buf,1)) {
        if (bytes == 0) *x = 0;
        *x |= (buf & 0x7fULL) << (7 * bytes++);
        if (!(buf & 0x80U)) break;
    }
    return bytes;
}

int main()
{
  size_t size = 0;
  read_uleb128(&std::cin, &size);

  while(size > 0)
  {

    double x;
    double y;

    std::cout << write_uleb128(size);

    for (size_t i=0; i < size; ++i)
    {
      std::cin.read((char*)&x, sizeof(double));
      std::cin.read((char*)&y, sizeof(double));
      std::cout.write((char*)(&x), 8);
      std::cout.write((char*)(&y), 8);
    }

    size=0;
    read_uleb128(&std::cin, &size);
  }
  return 0;
}


test_function.xml

<yandex>
  <function>
    <type>executable</type>
    <execute_direct>1</execute_direct>
    <name>test</name>
    <return_type>Array(Tuple(Float64,Float64))</return_type>
    <argument>
      <type>Array(Tuple(Float64,Float64))</type>
    </argument>
    <format>RowBinary</format>
    <command>program2</command>
    <send_chunk_header>0</send_chunk_header>
  </function>
</yandex>

SELECT test([(CAST('1.1', 'Float64'), CAST('1.2', 'Float64'))]) AS res

Query id: f32c92d2-529a-49e0-a6ab-a728489be9b1

┌─res─────────┐
│ [(1.1,1.2)] │
└─────────────┘
```

**Comment by youennL-cs** [comment]
> Write it.

Not bad for a "not true cpp dev" ahah

> You need to send LEB128 only for arrays or strings https://clickhouse.com/docs/en/interfaces/formats/#rowbinary

Yes I read that, but have you an explanation about why it fails when I send exactly what I receive ? 
Why it's not the same that extracting the varint length and re-write it, as well as for data ? 

---
Thanks for your example. Thanks to it I succeed to make few change to adapt to my use case of Array(Array(Uint64)).
I'm writing below the main function that I changed (write_uleb128 and read_uleb128 stay the same) in case if someone, one day, will need it :) 

```
int main() {
  size_t size = 0;
  read_uleb128(&std::cin, &size);

  while(size > 0) {
    uint64_t x;
    std::cout << write_uleb128(size);
    for (size_t i=0; i < size; ++i) {
      size_t subsize = 0;
      read_uleb128(&std::cin, &subsize);
      std::cout << write_uleb128(subsize);
      for (size_t j=0; i < subsize; ++i) {
        std::cin.read((char*)&x, sizeof(uint64_t));
        std::cout.write((char*)(&x), 8);
      }
    }

    size=0;
    read_uleb128(&std::cin, &size);
  }
  return 0;
}
```

```
<clickhouse>
...
<function>
    <type>executable</type>
    <execute_direct>1</execute_direct>
    <name>data_debug2</name>
    <return_type>Array(Array(UInt64))</return_type>
    <argument>
      <type>Array(Array(UInt64))</type>
    </argument>
    <format>RowBinary</format>
    <command>data_debug 1</command>
    <send_chunk_header>0</send_chunk_header>
</function>
...
</clickhouse>
```

`SELECT data_debug2([[CAST(1,'UInt64'),CAST(10,'UInt64'),CAST(20,'UInt64'),CAST(30,'UInt64'),CAST(45,'UInt64'),CAST(60,'UInt64'),CAST(110,'UInt64'),CAST(4,'UInt64')]]) AS res`

```
┌─res────────────────────────┐
│ [[1,10,20,30,45,60,110,4]] │
└────────────────────────────┘
```

**Comment by youennL-cs** [comment]
I would also come back to initial question. Have you a clear list of what format is available or not (even best would be to have small example as above but it would required too much work i think) ?
Because you have [this page](https://clickhouse.com/docs/en/interfaces/formats/) that describes what can be get on input or output. However, since you seem to say that Native is not supported, and I still don't know why it fails with JSONEachRow, is there any other format that are supported in input/output but not by EUDF ?

**Comment by UnamedRus** [comment]
> Yes I read that, but have you an explanation about why it fails when I send exactly what I receive ?

I'm not sure about this new line thing.

```
  while(std::cin >> line) {
    std::cout << line << "\n";
    std::cout.flush();
  }
```

In rowBinary Clickhouse doesn't have concept of new line afaik. (next row data goes after previous without delimiter)
May be the same is right for Native too.

**Comment by youennL-cs** [comment]
About that I start re-using what I found [here](https://github.com/ClickHouse/ClickHouse/issues/33284)
For RowBinary I tried with and without but doesn't change things.

**Comment by youennL-cs** [comment]
And I have to correct my previous post/code because it works for Array(Array(UInt64)) like [[1,2,3]] but not [[1],[2,3]] ..

**Comment by kitaisreal** [comment]
@youennL-cs all formats that do not contain input argument names are supported. `Native`, `JSONEachRow` are not supported, because you actually could not parse them, argument names will be different from query to query, but this https://github.com/ClickHouse/ClickHouse/pull/34653 will add support for specifying it.
Now example, you should not use iostreams if you want fast IO for Executable UDF.
Small executable UDF example using our buffers.
```c++
using namespace DB;

int main(int argc, char **argv)
{
    (void)(argc);
    (void)(argv);

    std::string buffer;

    ReadBufferFromFileDescriptor read_buffer(0);
    WriteBufferFromFileDescriptor write_buffer(1);

    while (!read_buffer.eof())
    {
        readString(buffer, read_buffer);
        writeString(buffer, write_buffer);

        write_buffer.next();
    }

    return 0;
}
```

```xml
<function>
    <type>executable</type>
    <name>test_function</name>
    <return_type>Array(Array(String))</return_type>
    <argument>
	<type>Array(Array(String))</type>
	<name>result</name>
    </argument>
    <format>Native</format>
    <command>test_function</command>
</function>
```
```sql
SELECT test_function_cpp([['1']]);
```
```
┌─test_function_cpp([['1']])─┐
│ [['1']]                    │
└────────────────────────────┘
```
Additionally for format support, script should serialize output values with column name `result`, I will add this into documentation, in example I specify `result` as argument name, so my script just read data and write it back with same format.

**Comment by UnamedRus** [comment]
>  Small executable UDF example using our buffers.

Cool idea of using ClickHouse codebase.
How long it take to compile that from scratch?

**Comment by kitaisreal** [comment]
@UnamedRus without libraries, only core part Core, Common, IO, Columns, DataTypes release build should take no more than 15-20 minutes.
Then you can reuse ClickHouse serializations and a lot of other core components that are battle proved, and tested using our CI.

**Comment by youennL-cs** [comment]
@kitaisreal , that awesome, thanks for the [PR](https://github.com/ClickHouse/ClickHouse/pull/34653), it will be very useful. 
It's a very good idea, I asked if it was possible to avoid iostreams with EUDF during our last meetup, but I hadn't this answer.  However, your message leads to two questions:
 1) Is this way to do is documented somewhere ? with more (complex) examples, like which functions can/should we use, how to manipulate it, is it working with all kind of format, etc.
 2) Is it possible to have very simple include to add, something like `#include <clickhouse.h>`  with a libclickhouse.so or .a to link, in order to avoid to find all includes needed. Even if it comes with a limited API that just allow us to work with essential functions. Because for now I don't know how just add only CH "core parts" in my EUDF build.
