### ISSUE TITLE
alias into CASE

### ISSUE THREAD

**Issue by hardstep33** [ClickHouse/ClickHouse#34626]
> the CASE statement allows you to assign an alias inside yourself, which is not described in the SQL standards

```
with arrayJoin([1,2]) as arg
select arg,
       (case
           when arg = 1
           then 1 as one
           when arg = 2
           then one / 2
       end) as imposible
--arg;imposible
--1;1
--2;0.5
```
release version = 21.11.6.7

**Comment by qoega** [comment]
And why is it a problem? There are many extensions to sql standard in ClickHouse.
You can just not write such queries..

**Comment by alexey-milovidov** [comment]
I confirm - this behavior is normal. Watch the video about modern SQL: https://www.youtube.com/watch?v=zhrOYQpgvkk
