### ISSUE TITLE
How is partition directory named when using tuple partition

### ISSUE THREAD

**Issue by Ravojay** [ClickHouse/ClickHouse#34638]
As described in the title, I have a table that has tuple styled partition like (Date, string). When I checked the directory, they are named like this: fec76dd7e3db37a6cc3add4af8fa7261_0_100_22

I wonder how is the directory named in this case.
Thanks in advance.

**Comment by den-crane** [comment]
it 128 bit hash function of values of tuple(Date, string) 

https://github.com/ClickHouse/ClickHouse/blob/b92efed35055d79c54c09425677986a84541beb0/src/Storages/MergeTree/MergeTreePartition.cpp#L109
