### ISSUE TITLE
Prepare for large number of columns: avoid copying of columns list from `ColumnsDescription`

### ISSUE THREAD

**Issue by CurtizJ** [ClickHouse/ClickHouse#34640]
Now we have a lot of places in code in which we create temporary list of columns from `ColumnsDescription` by `getAll`, `getAllPhysical` methods and similar. Often this list is used just to iterate over columns. In case when there are a huge number of columns (several thousands) it may make noticeable contribution in query execution time. 

I suggest to implement methods `all`, `allPhysical` and similar, which will return iterable range of columns in similar like it's done in `Settings` with `allChanged` or `allCustom` methods.

This task is mostly needed for #23932.

**Comment by alexey-milovidov** [comment]
Obsolete.
