### ISSUE TITLE
Incorrect setting name in ru documentation `output_format_csv_null_representation`

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#34667]
[(you don't have to strictly follow this form)](https://clickhouse.com/docs/ru/operations/settings/settings/#output_format_csv_null_representation)

**Describe the issue**
`output_format_csv_null_representation` instead of `format_tsv_null_representation`

**Additional context**
[Add any other context about the problem here.](https://github.com/ClickHouse/ClickHouse/pull/30497)

**Comment by rfraposa** [comment]
Thanks for finding this! It is fixed
