### ISSUE TITLE
What does the function 'loadDataParts' do and when is the function called ? 

### ISSUE THREAD

**Issue by guaiguaidashu** [ClickHouse/ClickHouse#34671]
> What is the difference between these three functions ?

https://github.com/ClickHouse/ClickHouse/blob/2340a6c6849ebc05a8efbf97ba8de3ff9dc0eff4/src/Storages/MergeTree/MergeTreeData.cpp#L1190

https://github.com/ClickHouse/ClickHouse/blob/2340a6c6849ebc05a8efbf97ba8de3ff9dc0eff4/src/Storages/MergeTree/MergeTreeData.cpp#L929-L936

https://github.com/ClickHouse/ClickHouse/blob/2340a6c6849ebc05a8efbf97ba8de3ff9dc0eff4/src/Storages/MergeTree/MergeTreeData.cpp#L1158-L1162

**Comment by alesapin** [comment]
`loadDataParts` is caller of `loadDataPartsFromDisk` and `loadDataPartsFromWAL`. This function is called when `MergeTreeData` object is created to load information about data parts into memory.

In 99% of cases all data parts are stored on disk and to load metainfo about them we use `loadDataPartsFromDisk`. But we have write (INSERT) optimization which is called `in-memory data parts`. It's a special setting which allow to store parts in memory and in the write ahead log (WAL). Such parts are loaded in a special way with `loadDataPartsFromWAL` function.

**Comment by guaiguaidashu** [comment]
> `loadDataParts` is caller of `loadDataPartsFromDisk` and `loadDataPartsFromWAL`. This function is called when `MergeTreeData` object is created to load information about data parts into memory.
> 
> In 99% of cases all data parts are stored on disk and to load metainfo about them we use `loadDataPartsFromDisk`. But we have write (INSERT) optimization which is called `in-memory data parts`. It's a special setting which allow to store parts in memory and in the write ahead log (WAL). Such parts are loaded in a special way with `loadDataPartsFromWAL` function.

thank you~
