### ISSUE TITLE
```parallel_distributed_insert_select``` will work with s3Cluster (hdfsCluster, HiveCluster) function

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#34670]
**Use case**

Parallelize INSERT query across whole cluster.
Now s3Cluster just send all data to initiator node, which almost instantly limit maximum possible performance.

**Describe the solution you'd like**

```
INSERT INTO distributed SELECT * FROM s3Cluster(....)
```

**Additional context**
Related https://github.com/ClickHouse/ClickHouse/issues/33945
https://github.com/ClickHouse/ClickHouse/pull/34449

**Comment by matiasdominguez** [comment]
will this feature be brought back after rework? thanks
