### ISSUE TITLE
Can clickhouse local Join (hash join) using multi threads ? 

### ISSUE THREAD

**Issue by qingping209** [ClickHouse/ClickHouse#34707]
When I am doing aggregation over join between two tables, I found CPU usage is quite low in join phase, only 1 core hits 100%;
after join set was created, CPU usage goes  high.  does clickhouse use multi  threads when doing join between tables ?

**Comment by sgycs** [comment]
I believe it has max_threads option provided by clickhouse, and the data is processed by blocks (sets of column parts).  Idealy, by using multiple threads could increase the performance but also it may consume too much memory or disk expenditures when extracting a loarge number of columns.

**Comment by helifu** [comment]
FYI. [36415](https://github.com/ClickHouse/ClickHouse/pull/36415)

**Comment by qingping209** [comment]
> FYI. [36415](https://github.com/ClickHouse/ClickHouse/pull/36415)

nice !
