### ISSUE TITLE
one of the replicated is down, when it's restarted, how to fetch data from anther replicated ?

### ISSUE THREAD

**Issue by guaiguaidashu** [ClickHouse/ClickHouse#34704]

**Comment by den-crane** [comment]
It will fetch missed data automatically.

**Comment by guaiguaidashu** [comment]
> It will fetch missed data automatically.

when we insert data, the replicated can produce LogEnrey, than another replicated pull logs to queue to fetch data, but if another replicated down, the logs will miss, than how to fetch the missed data?

**Comment by den-crane** [comment]
https://stackoverflow.com/a/69038983/11644308


```
SELECT *
FROM system.merge_tree_settings
WHERE name LIKE '%replicated_logs%'
FORMAT Vertical

Query id: 534466cf-1624-4ca0-b559-bc8c381ff547

Row 1:
──────
name:        max_replicated_logs_to_keep
value:       1000
changed:     0
description: How many records may be in log, if there is inactive replica. Inactive replica becomes lost when when this number exceed.
type:        UInt64

Row 2:
──────
name:        min_replicated_logs_to_keep
value:       10
changed:     0
description: Keep about this number of last records in ZooKeeper log, even if they are obsolete. It doesn't affect work of tables: used only to diagnose ZooKeeper log before cleaning.
type:        UInt64
```

max_replicated_logs_to_keep now is 1000. During the past this default value were changing, it was 10000, 100, 1000 :) .

If a replication log is "rotated" (a replica delay is >1000), it's not a problem at all, the stale replica starts a special bootstrap procedure, it does not use log at all, but it syncs it's metadata and a list of parts with other replicas, this procedure is slightly longer than rolling the log.

**Comment by guaiguaidashu** [comment]
> the stale replica starts a special bootstrap procedure, it does not use log at all, but it syncs it's metadata and a list of parts with other replicas
does the special bootstrap refers to the function `void StorageReplicatedMergeTree::checkParts(bool skip_sanity_checks)` ?

https://github.com/ClickHouse/ClickHouse/blob/e13a90e641b8ab05e582ba9e3c2ce9d120a32ffe/src/Storages/StorageReplicatedMergeTree.cpp#L974-L1123
