### ISSUE TITLE
AsynchronousMetrics Cannot read from file /sys/block/rbd4/stat

### ISSUE THREAD

**Issue by electrical** [ClickHouse/ClickHouse#34702]
**Describe the unexpected behaviour**

At the moment we are receiving this alert every second:
```
<Error> void DB::AsynchronousMetrics::update(std::chrono::system_clock::time_point): Code: 74, e.displayText() = DB::ErrnoException: Cannot read from file /sys/block/rbd4/stat
```

While checking on the filesystem seems to indicate it's there.

```
clickhouse@chi-clickhouse-main-0-0-0:/$ cat /sys/block/rbd4/stat
     181      272    18778      202       57       41      784      207        0      340      100        0        0        0        0

clickhouse@chi-clickhouse-main-0-0-0:/$ ls -lash /sys/block/rbd4/stat
0 -r--r--r-- 1 root root 4.0K Feb 17 22:13 /sys/block/rbd4/stat
```

Clickhouse version: 21.8.14.5
OS: Docker/ubuntu ( running official yandex/clickhouse-server docker image )

**Comment by alexey-milovidov** [comment]
It may be related to Linux namespaces in containers.
The error message is correct.

This is related to system metrics and does not affect queries processing and normal server operation.
You can ignore this message.

**Comment by electrical** [comment]
Hi @alexey-milovidov I strongly disagree with your statement and closing the issue. Can you please re-open it?
Although it doesn't effect query processing, it does fill up the logfile with useless log information since it gets logged every second.
Its interesting that other block devices don't have this issue ( I have rbd0 to rbd8 )

**Comment by alexey-milovidov** [comment]
Will it be sufficient if we change log level of these messages to "Debug"?

**Comment by den-crane** [comment]
related https://github.com/ClickHouse/ClickHouse/issues/32807

**Comment by SaltTan** [comment]
I was getting an exception like this one after a disk was replaced in a server.
A restart fixed the issue.

**Comment by electrical** [comment]
> Will it be sufficient if we change log level of these messages to "Debug"?

That is one option yeah, but i'm still confused to why we can access the file inside the container but Clickhouse can't access it.
Restarting CH will solve it for a while but at some point it starts to alert again.

**Comment by jpiper** [comment]
@alexey-milovidov I think setting the log level to debug makes sense, I do can't just ignore these logs in our production environment as they're really frequent and it causes confusion to people that aren't aware these logs are not an issue


not a contribution

**Comment by jun0tpyrc** [comment]
same issues for me,  it is kind of spamming our log pipelines

**Comment by aadant** [comment]
can you make that happen (debug instead of error) ?

**Comment by filimonov** [comment]
Similar to 
https://github.com/ClickHouse/ClickHouse/pull/27031
https://github.com/ClickHouse/ClickHouse/pull/33639

I think that exception should be either suppressed at all either reported once.

**Comment by Slach** [comment]
@electrical 
according to 
https://github.com/ClickHouse/ClickHouse/blame/master/src/Interpreters/AsynchronousMetrics.cpp#L1082-L1096
should device list should re-create after error
change available in 21.9+

**Comment by Slach** [comment]
@alexey-milovidov could you share pull request where issue was fixed?

**Comment by filimonov** [comment]
https://github.com/ClickHouse/ClickHouse/pull/44895 (23.1)
