### ISSUE TITLE
A lot of old "NO_REPLICA_HAS_PART" errors for GET_PART records in replication_queue

### ISSUE THREAD

**Issue by sokolov-alexey** [ClickHouse/ClickHouse#34700]
I have 3 ClickHouse v21.11.4.14 servers with some replicated tables on them.

On one (the elder one and the only one with this issue) server in **system.replication_queue** there are about 60 GET_PART records that are created on 7 jul 2021 (all 60 records created within 20 minutes) with up to 6.000.000 `num_tries` and up to 8.000.000 `num_postponed`. Mentioned in **system.replication_queue** tables are replicated on all servers but none of servers has mentioned parts (tables has 4 month TTL and the elder existing part created 4 months ago while mentioned in error part should have been created 7 months ago).

I've tried to run `system restart replica` on all 3 servers but it doesn't helped and only `num_tries` and `num_postponed` counters were reset. I've also tried to detach/attach table - no effect too.

```
SELECT *
FROM system.replication_queue
WHERE (table = 'Other') AND (type = 'GET_PART')
LIMIT 1
FORMAT Vertical

Query id: 1ed664dd-363a-48f6-a7c8-10b4fcd039f9

Row 1:
──────
database:               reindex
table:                  Other
replica_name:           chi-clickhouse-replicated-0-0
position:               0
node_name:              queue-0000565430
type:                   GET_PART
create_time:            2021-07-11 17:54:50
required_quorum:        0
source_replica:
new_part_name:          20210711_1218_1222_1
parts_to_merge:         []
is_detach:              0
is_currently_executing: 0
num_tries:              6026504
last_exception:         Code: 234. DB::Exception: No active replica has part 20210711_1218_1222_1 or covering part. (NO_REPLICA_HAS_PART) (version 21.11.4.14 (official build))
last_attempt_time:      2022-02-17 21:10:28
num_postponed:          3173505
postpone_reason:        Not executing fetch of part 20210711_1218_1222_1 because 8 fetches already executing, max 8.
last_postpone_time:     2022-02-17 21:10:28
merge_type:

1 rows in set. Elapsed: 0.004 sec.
```
```
SELECT *
FROM system.parts
WHERE name = '20210711_1218_1222_1'

Query id: 83949d04-29b5-4fb8-9ac8-08fa7c27a443

Ok.

0 rows in set. Elapsed: 0.742 sec. Processed 26.90 thousand rows, 17.02 MB (36.23 thousand rows/s., 22.92 MB/s.)
```

How can I stop these replication queues?

**Comment by den-crane** [comment]
Do you have data in this 20210711 partition? If you don't then just drop this partition.

https://kb.altinity.com/upgrade/removing-lost-parts/

**Comment by sokolov-alexey** [comment]
Denis, thanks a lot.
That helped.

**Comment by dozer111** [comment]
what to do if i have the data in partition?
