### ISSUE TITLE
JSON data type is not working in 22.2

### ISSUE THREAD

**Issue by sophie-jeong** [ClickHouse/ClickHouse#34711]
After watching a webinar last night, ( https://www.youtube.com/watch?v=6EG1gwhSTPg ) 
here is webinar's contents which i tried again.
-- Example : NBA games dataset 
CREATE TABLE games ( data String) 
Engine = MergeTree ORDER BY tuple() ;
SELECT JSONExtractString(data, 'teams',1,'name') FROM games ;
-- 0.520 sec.
-- now support for semistructured data 
CREATE TABLE games ( data JSON ) 
ENGINE = MergeTree ;
SELECT data.teams.name[1] FROM games ;
-- 0.015 sec.

 I tried to create a table with column of JSON data type after upgrading to 22.2, but it failed.
Maybe it hasn't been developed yet?

CREATE TABLE games
(
    `data` JSON
)
ENGINE = MergeTree

Received exception from server (version 22.2.2):
Code: 50. DB::Exception: Received from localhost:9000. DB::Exception: Unknown data type family: JSON. (UNKNOWN_TYPE)

**Comment by UnamedRus** [comment]
It's not done yet.

https://github.com/ClickHouse/ClickHouse/pull/23932

**Comment by filimonov** [comment]
> After watching a webinar last night, 

Watch it more carefully :) https://youtu.be/6EG1gwhSTPg?t=3658

'It is planned for the first quarter of the year, probably one of the few next releases'
