### ISSUE TITLE
compressed output formats

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#3473]
Quite often I have cases when some data need to be extracted from ClickHouse and passed/uploaded somewhere.

Right now I do `SELECT ... INTO OUTFILE ... FORMAT ... ` and compress the resulting file afterwards. In some cases compression takes more time than extracting data from clickhouse :)

AFAIK for clickhouse steaming compressed data should not be a big problem, so may be for ```INTO OUTFILE ... ``` additional clause like ```COMPRESSION='gzip'```  or even just ```INTO COMPRESSED OUTFILE ...``` can be added.

**Comment by alexey-milovidov** [comment]
We can support compression for INTO OUTFILE in the same way as for File-related storages (with a switch: `auto`, `none`, `gz`, `br` where auto means "detect by file extension" and it is by default).

The question is where to place this switch: in settings (easy) or in special syntax clause.
I prefer first. (Most of the time, the default (autodetect) will be used and it will work as expected magically).

**Comment by sv3t0sl4v** [comment]
This will be **VERY** useful. Our **.native** backup files are quite huge, so we smash them into tarballs after output with the **--remove-files** flag. This way we reduce their size about 5 times.
