### ISSUE TITLE
query to format / check syntax of query :)

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#3474]
I know that there is `clickhouse-format` executable, but it's not very usable in interactive mode, and you need to have it installed to do the formatting (so not possible via HTTP-interface for example).

Use cases:
1) I'm looking for some snippet in clickhouse-client history. Queries in history are stored without formatting, some queries are very big, so the only way to see it pretty w/o leaving clickhouse-client session - is to run it (it's not a good idea usually). Or I need to exit clickhouse-client, and pipe the query to `clickhouse-format`. So instead of that, it would be nice if it will be possible just to prepend/append some keyword to existing query, and instead of executing it will be formatted & printed.
2) If it will be supported also via HTTP interface it will be possible also to check the query syntax / show pretty print query without installing anything on the client. (like with simple curl query).

**Comment by alexey-milovidov** [comment]
1 is implemented with:

`EXPLAIN AST your query`

**Comment by alexey-milovidov** [comment]
2 is not implemented.
