### ISSUE TITLE
Confusing message on a cli client flag misuse.

### ISSUE THREAD

**Issue by nikandfor** [ClickHouse/ClickHouse#34747]
**Describe the issue**
It's hard to understand what I did wrong or how can I fix the problem.

I rechecked my typing 5 times, it's fine.
```
# clickhouse-client --file -
Code: 552. DB::Exception: Unrecognized option '--file'. Maybe you meant ['--file','--time']. (UNRECOGNIZED_ARGUMENTS)
```

This is a minimal flag set to get into the problem. I tried multiple flag sets, with `--format`, `--name`, reading from stdin or file, used = or not. It's all the same.

**Expected behavior**
Some short description how it was expected to be used or at least the message that do not confuse you more.

**Comment by taiyang-li** [comment]
@nikandfor  You should add -external before --file, like this 
``` bash 
$CLICKHOUSE_CLIENT --query="SELECT count() FROM data" --external --file="${CLICKHOUSE_TMP}"/empty.tsv --name=data --types=UInt32
```
