### ISSUE TITLE
how to get durable inserts when using kafka table? insert_quorum doesn't work on the kafka table (UNKNOWN_SETTING)

### ISSUE THREAD

**Issue by gauravphoenix** [ClickHouse/ClickHouse#34756]
```sql
create table foo (`foo` String) Engine=Kafka SETTINGS  ... ,insert_quorum=2;
```
gives error
```
Unknown setting insert_quorum: for storage Kafka. (UNKNOWN_SETTING)
```

and if I put the same setting in the MV, it has no effect- 

```sql
CREATE MATERIALIZED VIEW IF NOT EXISTS mv TO xyz AS SELECT * from kafka SETTINGS insert_quorum=2;
```
I have only one replica so I expected the inserts to fail but I could see data flowing in the target table. 

cc @vavrusa  and @filimonov  as I saw a similar post https://github.com/ClickHouse/ClickHouse/issues/3307 (I am not using dist table, each replica is pulling data from kafka table)

**Comment by gingerwizard** [comment]
Hi @gauravphoenix i think there two questions here (less related to Kafka)

1. Can the materialized view trigger use `insert_quorum` on its inserts to the target table?
2. How does `insert_quorum` behave when there is only one replica.

Will test and let you know asap.

**Comment by gingerwizard** [comment]
@gauravphoenix spent some time investigating this.

The `insert_quroum` should be respected by the MV on insert to the target table. This is, however, currently only respected if the setting is placed in a profile in the user config and not if its declared in the MV inline e.g.

```
<profiles>
        <!-- Default settings. -->
        <default>
	    <insert_quorum>2</insert_quorum>
    	</default>
    </profiles>
```

Assuming you only have only 1 replica:

Setup source table. target table and MV trigger.
```
CREATE TABLE default.test
(
    `key` String
)
ENGINE = MergeTree
ORDER BY (key)
SETTINGS index_granularity = 8192;



CREATE TABLE default.target_test
(
    `key` String
)
ENGINE = ReplicatedMergeTree('/clickhouse/pulse/default/target/0', '0')
ORDER BY (key)
SETTINGS index_granularity = 8192;


CREATE MATERIALIZED VIEW default.test_mv TO default.target_test AS SELECT * FROM default.test;
```

This with then fail

`INSERT INTO default.test VALUES ('z');`

`Code: 285. DB::Exception: Number of alive replicas (1) is less than requested quorum (2).: while pushing to view default.test_mv (10e0351d-3d06-49b4-a5c4-a3593c714550). (TOO_FEW_LIVE_REPLICAS) (version 22.2.2.1)`
SELECT * FROM default.target_test;`

Add a replica and this insert will succeed.

With reference to Kafka specifically, i tested this and MV does not move the consumer offset forward until the insert succeeds. Once replicas are available, the MV will continue consuming from Kafka.

The `insert_quorum` setting inline in the MV declaration does not  currently have any effect - i think this is a bug. The setting is accepted and it makes sense for it to be specified at a MV level vs for all tables relevant to the profile. I'll raise an issue.
Thanks for raising.

**Comment by gauravphoenix** [comment]
@gingerwizard , thank you so much for the detailed response. It helped tremendously
