### ISSUE TITLE
row_number window function doesn't treat the full result set when using with LIMIT

### ISSUE THREAD

**Issue by AviSarmani** [ClickHouse/ClickHouse#34757]
**Describe the unexpected behaviour**
When using the row_number window function with LIMIT, the results are numbered after the LIMIT was executed so the row_numbers are not from the full result set

**How to reproduce**
Version - 22.1.2.2
Create any table with sufficient number of records:
SELECT row_number() OVER () AS id
FROM test

result is id = 1,2,3,4,5....

SELECT row_number() OVER () AS id
FROM cases_bs1000
LIMIT 5 OFFSET 20

result is id = 1,2,3,4,5

**Expected behavior**
The second result should be 21,22,23,24,25

**Additional context**
We're in the process of migrating from Postgres and that was the result there.
As far as I've read in other DB's documentation, it looks like row_number should run before the limit or provide us with another window function to get this functionality.

It looks like the issue doesn't reproduce with count or sum as we have queries like this and they perform as expected(before limiting)

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/23125
