### ISSUE TITLE
About building ReplicatedMergeTree table

### ISSUE THREAD

**Issue by linruoma** [ClickHouse/ClickHouse#34761]
If I build such a ReplicatedMergeTree table
`CREATE TABLE test_create_table_local on
cluster cluster001(
	id Int64,
    date Date,
    timeslot DateTime,
    statusMap Nested(
        status UInt16,
        requests UInt64
    ),
    statusMapTuple Tuple(Array(Int32),
Array(Int32))
) 
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/test_create_table_local',
 '{replica}')
ORDER BY
id;`

Shards and replicas configuration
`<cluster001>
            <shard>
                <weight>1</weight>
                <internal_replication>true</internal_replication>
                <replica>
                    <host>ch-cluster-0-0</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>ch-cluster-0-1</host>
                    <port>9000</port>
                </replica>
            </shard>
            <shard>
                <weight>1</weight>
                <internal_replication>true</internal_replication>
                <replica>
                    <host>ch-cluster-1-0</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>ch-cluster-1-1</host>
                    <port>9000</port>
                </replica>
            </shard>
        </cluster001>`

If I change the configuration of Shards and replicas , can I do it without moving data,Instead of rebuilding a new table and inserting data into it?
`<cluster002>
            <shard>
                <weight>1</weight>
                <internal_replication>true</internal_replication>
                <replica>
                    <host>ch-cluster-0-0</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>ch-cluster-0-1</host>
                    <port>9000</port>
                </replica>
            </shard>
            <shard>
                <weight>1</weight>
                <internal_replication>true</internal_replication>
                <replica>
                    <host>ch-cluster-1-0</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>ch-cluster-1-1</host>
                    <port>9000</port>
                </replica>
            </shard>
             <shard>
                <weight>1</weight>
                <internal_replication>true</internal_replication>
                <replica>
                    <host>ch-cluster-2-0</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>ch-cluster-2-1</host>
                    <port>9000</port>
                </replica>
            </shard>
        </cluster002>`

**Comment by den-crane** [comment]
>can I do it without moving data

No. You cannot. You need to re-insert data.
