### ISSUE TITLE
If there is `<keeper_server>` section in config, infer keeper's client configuration from it.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#34767]
**Use case**

If `clickhouse-keeper` is enabled in clickhouse-server and there is no configuration of `zookeeper` or `keeper` (a config for client connections to connect to ZooKeeper/Keeper), reuse the configuration from `<keeper_server><raft_configuration>`.

See also #34766

**Comment by taiyang-li** [comment]
I'd like to try
