### ISSUE TITLE
Recognize `<keeper>` as alternative to `<zookeeper>` in server's config.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#34766]
**Use case**

Avoid confusion when people are using `clickhouse-keeper`.

**Describe the solution you'd like**

`keeper` section will be identical to `zookeeper`, but don't allow both sections to be present.

**Comment by taiyang-li** [comment]
I'd like to try, together with previous issue

**Comment by taiyang-li** [comment]
@alexey-milovidov  I noticed that  there is a config section named `auxiliary_zookeepers`, it is reasonable to also set `auxiliary_keepers` as alternative of `auxiliary_zookeepers`

**Comment by alexey-milovidov** [comment]
@taiyang-li Yes, let's allow `auxiliary_keepers`.

**Comment by taiyang-li** [comment]
Ok.

**Comment by SakshiT25** [comment]
Hi, I'm interested in working on this feature. Kindly guide me for the further steps.

**Comment by alexey-milovidov** [comment]
@SakshiT25 this task is already being implemented by @taiyang-li.
