### ISSUE TITLE
clickhouse-client ignores port parameter from config file, ClickHouse 22.2.2

### ISSUE THREAD

**Issue by Alex-Burmak** [ClickHouse/ClickHouse#34776]
**Describe the issue**
In the latest version (22.2.2.1) clickhouse-client ignores `port` parameter from config file.
 
**How to reproduce**
Create `config.xml` with arbitrary value for `port` parameter. 
```
<config>
    <port>9001</port>
</config>
```

Run `clickhouse-client` with custom config file
```
# clickhouse-client --log-level trace -c config.xml
Processing configuration file 'config.xml'.
ClickHouse client version 22.2.2.1.
Connecting to localhost:9000 as user default.
Connecting. Database: (not specified). User: default. Uncompressed
Code: 210. DB::NetException: Connection refused (localhost:9000). (NETWORK_ERROR)

Uninitializing subsystem: Logging Subsystem
```

The output indicates that it's used default port value (9000) instead of the value from config file (9001).

**Comment by mtselishchev** [comment]
May that also be a reason of error while performing:
```
clickhouse-client --secure
```
?
Now it says 
```
ClickHouse client version 22.2.2.1.
Connecting to localhost:9000 as user my_user.
Code: 210. DB::NetException: SSL Exception: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER (localhost:9000). (NETWORK_ERROR)
```
Downgraded to 21.1.3.7, everything works fine...

**Comment by sv3t0sl4v** [comment]
I obviously have the same problem. I run it with --port and it works.

**Comment by vdimir** [comment]
@sv3t0sl4v @mtselishchev 
Version 22.3 tries to connect to `9440` by defult with `--secure`

```
clickhouse-client --secure

ClickHouse client version 22.3.1.1.
Connecting to localhost:9440 as user default.
Code: 210. DB::NetException: Connection refused (localhost:9440). (NETWORK_ERROR)
```

What is expected behavior?
