### ISSUE TITLE
ClickHouse API for external tools + documentation

### ISSUE THREAD

**Issue by youennL-cs** [ClickHouse/ClickHouse#34789]
In a previous [discussion](https://github.com/ClickHouse/ClickHouse/issues/34604), at some point we mentioned the possibility to use the ClickHouse API. The initial goal of this discussion was to limit EUDF IOs as much as possible.

Since the discussion drifted, I open this new topic, where I would like to discuss more about the possibility to use ClickHouse API. 
We would like to use the CH API to implement new tools around CH. Most of our tools are too specific to our cases to be included in the CH code and we don't want to fork CH.
In the previous discussion @kitaisreal [mention](https://github.com/ClickHouse/ClickHouse/issues/34604#issuecomment-1041813105) a way to use CH buffers to avoid iostreams and told me that "this process currently is not documented". 

So, I would like to know if there is any possibility to document it with end-to-end examples. Like how only include CH "needed parts" in our tools and how add them to our cmake (for example).

In addition, I would also know if there is a way to get a CH library (e.g. libclickhouse.so, libclickhousecore.so, etc), with simple includes (e.g #include <clickhouse.h>).

**Comment by pkit** [comment]
Subscribing.
Pretty interested in getting MergeTree family as a library (or Native format as a library, which is almost the same).

**Comment by alexey-milovidov** [comment]
Implementing C++ API for ClickHouse internals is difficult for the following reasons:
- we are changing the code too frequently;
- we don't support shared linking;
- there is too much stuff to decide on.
