### ISSUE TITLE
how to fetch data manually between two replicated ? 

### ISSUE THREAD

**Issue by guaiguaidashu** [ClickHouse/ClickHouse#34781]
`clickhouse version : 20.8 `
`engine : replicatedMergeTree`

One of the replicated down a long time, when we restart the replicated, I know replicated can fetch data automatically. 

But too many data need to fetch, it will reduce clickhouse performance, can i fetch some data manually?

**Comment by vdimir** [comment]
You can try recover replica, (see "Recovery After Failures") or even recover it as if it was data loss (section "Recovery After Complete Data Loss")

https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/replication/#recovery-after-failures

**Comment by den-crane** [comment]
You don't need it, it's impossible with 20.8
Update Clickhouse and use https://clickhouse.com/docs/en/operations/settings/merge-tree-settings/#max_replicated_fetches_network_bandwidth

**Comment by guaiguaidashu** [comment]
> You don't need it, it's impossible with 20.8 Update Clickhouse and use https://clickhouse.com/docs/en/operations/settings/merge-tree-settings/#max_replicated_fetches_network_bandwidth

Thank you a lot, which version should i update ?

**Comment by vdimir** [comment]
> Thank you a lot, which version should i update ?

@guaiguaidashu
We recommend to use latest stable branch
