### ISSUE TITLE
topK with counts

### ISSUE THREAD

**Issue by madejejej** [ClickHouse/ClickHouse#34807]
**Use case**

We have a few fields with very low cardinality and we want to create materialized views with `SummingMergeTrees` for them that count the number of each value. Currently, we have to create a materialized view for each field and time period. For example, if `event_action` and `event_status` fields have very low cardinality and we want to have a 1-hour aggregates, we need these two materialized views:

```
CREATE MATERIALIZED VIEW production.event_actions_per_1h
            ENGINE = SummingMergeTree(event_action)
                ORDER BY (tenant_id, ts, event_name, event_action)
            POPULATE AS
SELECT
    tenant_id,
    tumbleStart(FROM_UNIXTIME(created_at), INTERVAL '1' HOUR) as ts,
    event_name,
    event_action,
    COUNT(*) as value
FROM production.events
GROUP BY tenant_id, ts, event_name, event_action;

CREATE MATERIALIZED VIEW production.event_statuses_per_1h
            ENGINE = SummingMergeTree(event_status)
                ORDER BY (tenant_id, ts, event_name, event_status)
            POPULATE AS
SELECT
    tenant_id,
    tumbleStart(FROM_UNIXTIME(created_at), INTERVAL '1' HOUR) as ts,
    event_name,
    event_status,
    COUNT(*) as value
FROM production.events
GROUP BY tenant_id, ts, event_name, event_status;
```

If we have to group N low-cardinality fields with K different time intervals, we need N*K materialized views.

**Describe the solution you'd like**

Clickhouse already has a `topK` [function](https://clickhouse.com/docs/en/sql-reference/aggregate-functions/reference/topk/)  that returns the approximate most frequent values for a field. It would be great if there was a `topKWithCount` function that would work similarly, but also return the approximate counts:

```
SELECT topKWithCounts(3)(event_status) AS res
FROM production.events
```

```
┌─res─────────────────────────────────────────┐
│ [('succeeded', 20526), ('failed', 522)]     │
└─────────────────────────────────────────────┘

```

Using it, we should be able to use `AggregatingMergeTree` and reduce the number of materialized views from N*K to only K:

```
CREATE MATERIALIZED VIEW production.event_statuses_per_1h
            ENGINE = AggregatingMergeTree()
                ORDER BY (tenant_id, ts, event_name)
            POPULATE AS
SELECT
    tenant_id,
    tumbleStart(FROM_UNIXTIME(created_at), INTERVAL '1' HOUR) as ts,
    event_name,
    topKWithCountsState(3)(event_status) as event_status,
    topKWithCountsState(3)(event_action) as event_action,
    COUNT(*) as value
FROM production.events
GROUP BY tenant_id, ts, event_name
```

**Comment by UnamedRus** [comment]
>     topKWithCountsState(3)(event_status) as event_status,
    topKWithCountsState(3)(event_action) as event_action,
    
You can do that via sumMap or Nested.
https://kb.altinity.com/engines/mergetree-table-engine-family/summingmergetree/
https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/summingmergetree/#nested-structures

**Comment by madejejej** [comment]
@UnamedRus Thank you, this works!

For all the people struggling with the same problem, here's a snippet that fulfills this:

```
CREATE TABLE production.test_summing
(
    tenant_id Int32,
    ts DateTime,
    event_name String,
    action_countsMap Nested(key String, count UInt32),
    event_statusMap Nested(key String, count UInt32)
) ENGINE = SummingMergeTree()
ORDER BY (tenant_id, ts, event_name);

INSERT INTO production.test_summing_1h
SELECT
    tenant_id,
    tumbleStart(FROM_UNIXTIME(created_at), INTERVAL '1' HOUR) as ts,
    event_name,
    [risk_policy_action] as `action_countsMap.key`,
    [1] as `action_countsMap.count`,
    [event_status] as `event_statusMap.key`,
    [1] as `event_statusMap.count`
FROM production.events;

select
       tenant_id,
       ts,
       event_name,
       `action_countsMap.key` as status,
       `action_countsMap.count` as total
from production.test_summing_1h
array join action_countsMap
where tenant_id = 1 AND ts BETWEEN '2022-02-10' AND '2022-02-16'
order by ts asc;
```
