### ISSUE TITLE
Unable to send async insert query via Http Interface

### ISSUE THREAD

**Issue by wilsonwang213** [ClickHouse/ClickHouse#34809]
Hi, Team

After setting async_insert=1 and wait_for_async_insert=0, I submitted an insert query (insert into table A select * from table B) via Postman to the Clickhouse server.

However it did not instantly return 200 OK response, but still waiting the insertion progress to complete and then returned the 200 response.

Also I tried to set those 2 properties in the request url like server_address/?async_insert=1&wait_for_async_insert=0, it also did not work as expected.

Can you guide me how to submit an async insert query via Http Interface ?

**Comment by den-crane** [comment]
async_insert is not for `insert into table A select * from table B`
They should work only with `insert into table A + datastream (values/TSV/CSV ...)`

**Comment by wilsonwang213** [comment]
Thanks @den-crane 

Another question is that, if I submit an insert query via Http and manually stop it. Would the insert query run and complete at Clickhouse server ?

**Comment by den-crane** [comment]
>Another question is that, if I submit an insert query via Http and manually stop it. 
>Would the insert query run and complete at Clickhouse server ?

It can complete or can partially complete.

**Comment by gauravphoenix** [comment]
@den-crane can async insert work for table functions? E.g. `insert into table select * from s3(...)` not sure if s3 function will be considered a datastream here

**Comment by wilsonwang213** [comment]
> > Another question is that, if I submit an insert query via Http and manually stop it.
> > Would the insert query run and complete at Clickhouse server ?
> 
> It can complete or can partially complete.

In what circumstance it will partially complete?

**Comment by alexey-milovidov** [comment]
@wilsonwang213 Asynchronous inserts work for queries with explicit data, not for INSERT SELECT, not for table functions.
