### ISSUE TITLE
Expose (some) SimpleMergeSelector settings

### ISSUE THREAD

**Issue by Algunenano** [ClickHouse/ClickHouse#34813]
**Use case**

For some tables, it would be interesting to have a more aggressive merge algorithm to ensure a table has a lower amount of parts, even if that comes with a cost of higher CPU and disk usage.

Some scenarios:
* A partition receives 4-5 parts of a few MBs and stops ingesting (in that partition). It might take days or weeks before those parts are merged and in the meantime all the queries over that partition have to read many more files (3-4x more) than what they would read if the data was already merged.
* A partition receives frequent inserts of data and many reads at the same time. Some of those reads are partially slowed down by having to read 8-10 parts and we'd like to try what's the cost of forcing a lower amount of parts (3-4).

In both situations it is possible that the current coefficients are the best, but maybe they aren't and you'd rather pay with more CPU, disk and network so you can have faster read queries.

**Describe alternatives you've considered**

Running `OPTIMIZE` is an option, but it requires external monitoring and intervention.

**Describe the solution you'd like**

Currently, it seems that in order to tweak things you'd need to build your custom CH with custom values (which would affect all tables).

I think that, in the same way `max_parts_to_merge_at_once` is currently exposed at the merge tree level I think it'd be useful to have access to other SimpleMergeSelector settings too, as long as there is a good validation and documentation (which is kind of there already in the code).

Some settings I think it'd be interesting to expose:
* base
* min_size_to_lower_base / max_size_to_lower_base
* min_age_to_lower_base_at_min_size / min_age_to_lower_base_at_max_size
* max_age_to_lower_base_at_min_size / max_age_to_lower_base_at_max_size
* min_parts_to_lower_base / max_parts_to_lower_base

Any thoughts? Maybe there is already a better way to do this that I'm missing.

**Comment by alexey-milovidov** [comment]
@Algunenano let's implement https://github.com/ClickHouse/ClickHouse/issues/35836 first.

About exposing SimpleMergeSelector settings, I don't like it because the algorithm may change and we did not completely explore it.
