### ISSUE TITLE
Error code 509 on user admin SQL queries after upgrade to 22.2.2.1-stable

### ISSUE THREAD

**Issue by chestel** [ClickHouse/ClickHouse#34815]
After upgrading Clickhouse-server to **22.2.2.1-stable** from 22.1.3.7-stable our user management has stopped working. All user managment operations fail with error:

`Received exception from server (version 22.2.2):
Code: 509. DB::Exception: Received from server:9000. DB::Exception: CREATE FUNCTION cannot be granted on the database level. (INVALID_GRANT)
`

**How to reproduce**
* ClickHouse server version 22.2.2.1-stable
* Use admin user defined in users.xml with access_management = 1 OR SQL created admin user granted all on *.* with grant option.
* Any user query operation fails with `Code: 509. DB::Exception: Received from server:9000. DB::Exception: CREATE FUNCTION cannot be granted on the database level. (INVALID_GRANT)`
* E.g. `select * from system.users`
or `show users`
* Other queries e.g. `select * from db.table` or `show databases` work fine
* I've tried with the original XML for an admin user and also created a user with SQL and the result is the same
* Uninstalling and installing the older server version 22.1.3.7-stable fixes the issue without config changes.

**Expected behavior**
Usually `show users` or `select * from system.users` will return results.

**Error message and/or stacktrace**
Trace in error log (same message returned to client):
`2022.02.22 17:34:22.509053 [ 2681 ] {bb4cc7d4-2232-442c-bead-a21d7b5c4246} <Error> TCPHandler: Code: 509
. DB::Exception: CREATE FUNCTION cannot be granted on the database level. (INVALID_GRANT), Stack trace (
when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocato
r<char> > const&, int, bool) @ 0xaebed1a in /usr/bin/clickhouse
1. ? @ 0x15f93c07 in /usr/bin/clickhouse
2. DB::ParserGrantQuery::parseImpl(DB::IParser::Pos&, std::__1::shared_ptr<DB::IAST>&, DB::Expected&) @
0x15f8fc08 in /usr/bin/clickhouse
3. DB::IParserBase::parse(DB::IParser::Pos&, std::__1::shared_ptr<DB::IAST>&, DB::Expected&) @ 0x15f16137 in /usr/bin/clickhouse
4. ? @ 0x140a4327 in /usr/bin/clickhouse
5. DB::IParserBase::parse(DB::IParser::Pos&, std::__1::shared_ptr<DB::IAST>&, DB::Expected&) @ 0x15f16137 in /usr/bin/clickhouse
6. DB::tryParseQuery(DB::IParser&, char const*&, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, unsigned long, unsigned long) @ 0x15f68d8d in /usr/bin/clickhouse
7. DB::parseQueryAndMovePosition(DB::IParser&, char const*&, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, unsigned long, unsigned long) @ 0x15f69bda in /usr/bin/clickhouse
8. DB::deserializeAccessEntity(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x140a2c8c in /usr/bin/clickhouse
9. DB::DiskAccessStorage::readAccessEntityFromDisk(StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag> const&) const @ 0x1409d0c5 in /usr/bin/clickhouse
10. DB::DiskAccessStorage::readImpl(StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag> const&, bool) const @ 0x1409cefb in /usr/bin/clickhouse
11. DB::MultipleAccessStorage::readImpl(StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag> const&, bool) const @ 0x140dfa7e in /usr/bin/clickhouse
12. std::__1::shared_ptr<DB::User const> DB::IAccessStorage::read<DB::User>(StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag> const&, bool) const @ 0x13deeeb4 in /usr/bin/clickhouse
13. DB::StorageSystemUsers::fillData(std::__1::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn> > >&, std::__1::shared_ptr<DB::Context const>, DB::SelectQueryInfo const&) const @ 0x13decaaf in /usr/bin/clickhouse
14. DB::IStorageSystemOneBlock<DB::StorageSystemUsers>::read(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryInfo&, std::__1::shared_ptr<DB::Context const>, DB::QueryProcessingStage::Enum, unsigned long, unsigned int) @ 0x13d9d596 in /usr/bin/clickhouse
15. DB::IStorage::read(DB::QueryPlan&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryInfo&, std::__1::shared_ptr<DB::Context const>, DB::QueryProcessingStage::Enum, unsigned long, unsigned int) @ 0x15081b12 in /usr/bin/clickhouse
16. DB::InterpreterSelectQuery::executeFetchColumns(DB::QueryProcessingStage::Enum, DB::QueryPlan&) @ 0x14c68f45 in /usr/bin/clickhouse
17. DB::InterpreterSelectQuery::executeImpl(DB::QueryPlan&, std::__1::optional<DB::Pipe>) @ 0x14c60f34 in /usr/bin/clickhouse
18. DB::InterpreterSelectQuery::buildQueryPlan(DB::QueryPlan&) @ 0x14c60a70 in /usr/bin/clickhouse
19. DB::InterpreterSelectWithUnionQuery::buildQueryPlan(DB::QueryPlan&) @ 0x14cb1b83 in /usr/bin/clickhouse
20. DB::InterpreterSelectWithUnionQuery::execute() @ 0x14cb2c28 in /usr/bin/clickhouse
21. ? @ 0x14ee8a79 in /usr/bin/clickhouse
22. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x14ee65f5 in /usr/bin/clickhouse
23. DB::InterpreterShowAccessEntitiesQuery::execute() @ 0x14f237bb in /usr/bin/clickhouse
24. ? @ 0x14ee8a79 in /usr/bin/clickhouse
25. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x14ee65f5 in /usr/bin/clickhouse
26. DB::TCPHandler::runImpl() @ 0x159ef43a in /usr/bin/clickhouse
27. DB::TCPHandler::run() @ 0x15a03419 in /usr/bin/clickhouse
28. Poco::Net::TCPServerConnection::start() @ 0x18667a0f in /usr/bin/clickhouse
29. Poco::Net::TCPServerDispatcher::run() @ 0x18669e61 in /usr/bin/clickhouse
30. Poco::PooledThread::run() @ 0x1881a549 in /usr/bin/clickhouse
31. Poco::ThreadImpl::runnableEntry(void*) @ 0x18817c40 in /usr/bin/clickhouse`

**Comment by chestel** [comment]
Update - it seems to be triggered by a user having been granted permissions on an older server version e.g.

grant all on testdb1.* to testuser1;

When the server installation is upgraded it any queries of the user table or other operations which I presume do the same fail with "Code: 509
. DB::Exception: CREATE FUNCTION cannot be granted on the database level. (INVALID_GRANT)"

When that user is dropped and recreated, including with that same grant:

grant all on testdb1.* to testuser1;

The DB is fixed and user queries and other operations are normal.

**Comment by chestel** [comment]
Further update: on older server version a user that has had "grant all on testdb1.* to testuser1" will show it has been granted "CREATE FUNCTION" when querying select * from system.grants.

On the newer server this seems to trigger an error disabling user admin features, not just for that one user but for all users.

**Comment by tavplubix** [comment]
Related to #34404

**Comment by vitlibar** [comment]
https://github.com/ClickHouse/ClickHouse/pull/34404 changed the privilege `CREATE FUNCTION`: not it should be granted at global level:

```
GRANT CREATE FUNCTION ON *.* TO username
```

It's more correct than how it was before when the privilege `CREATE FUNCTION` could be granted on database, because user defined functions don't have anything to do with databases. So the statement

```
GRANT CREATE FUNCTION ON mydb.* TO username
```
is now considered as meaningless.

However the change https://github.com/ClickHouse/ClickHouse/pull/34404 wasn't supposed to affect updating ClickHouse to a new version, and we will fix that issue.

**Comment by DarkWanderer** [comment]
I would suggest the problem is with the fact that `GRANT ALL` statement is not actually stored as `ALL` in `/var/lib/clickhouse/access`, but rather as a list of explicit permissions - which creates problems in scenarios like above (and also does not automatically grant permissions added in new releases)

**Comment by chestel** [comment]
HI Oleg - that is exactly what I am struggling with. If the grants in the
DB (e.g. from GRANT ALL on X.*) don't match the server
version's expectations then it throws errors preventing basic user
management making it hard to get yourself out of the situation.

**Comment by chestel** [comment]
Does anyone have any advice as to how to workaround this issue so as to
enable us to upgrade releases without breakage?

I have been trying to revoke whichever incorrect db-level grants got setup
when we did a "grant all on x.* to user" in the past. This does not seem to
work.

Is there a way to avoid dropping and recreating affected users?

Best Regards
Leo

**Comment by DarkWanderer** [comment]
You can edit .sql files in `/var/lib/clickhouse/access` to remove the offending grants, then restart the server (try it in UAT first!)

**Comment by vitlibar** [comment]
I've merged a fix now which makes ClickHouse ignore outdated grants while reading `/var/lib/clickhouse/access`.
