### ISSUE TITLE
Fetch columns not necessary for query with limit, after the limit is applied 

### ISSUE THREAD

**Issue by sundarv85** [ClickHouse/ClickHouse#34829]
We have a table with around 30+ fields. 

> ```
> variableInt1 to variableInt10
> varString1 to varString10
> nestedString1 { name, value } to nestedString10 { name, value }
> 
> ```

In these, the **nestedString Values** are **huge strings**.

We do a select operation in this way

```
SELECT

variableInt1, variableInt2.... variableInt10, 
varString1, varString2, ... varString10, 
nestedString1.name as varString1Name, nestedString1.value as varString1Value,... nestedString5.name as varString5Name, nestedString5.value as varString5Value 

FROM table 
WHERE date >= toDate('2022-01-22 09:05:00') AND date <= toDate('2022-02-23 09:05:00') AND teamId = '212312412' AND dateTime >= '2022-01-22 09:05:00' AND dateTime <= '2022-02-23 09:05:00'  
                
ORDER BY timestamp DESC 
LIMIT 0, 20
```

We are fetching for the last 1 month, sorting it by timestamp and the limiting it to the first 20.

When we do this, we see the response coming in

> **8 seconds Processed 420 thousand rows, 13 GB**

If we **remove** the **nestedString1-5 name, value** - then the response comes in

> **0.220 seconds Processed 420 thousand rowse, 300MB**

So what I assume is happening is it is fetching all the columns and then orders and applies the limit. We thought that the PREWHERE would behave differently that it  `With prewhere optimization, at first only the columns necessary for executing prewhere expression are read` as noted [here](https://clickhouse.com/docs/en/sql-reference/statements/select/prewhere/) ​

I suppose it is only doing this  for the columns in the  WHERE field, but does not apply to the ORDER and LIMIT. So with WHERE or PREWHERE the size of processing is still 13 GB.

Is there a way to reduce this. Ideally we would like to process with only 300MB (the second method) and only after the limit is applied, fetch the remaining nested columns.

**Comment by UnamedRus** [comment]
Related https://github.com/ClickHouse/ClickHouse/issues/5329
