### ISSUE TITLE
Unknown codec family（ version 22.2.2.1）

### ISSUE THREAD

**Issue by zhuokun** [ClickHouse/ClickHouse#34827]
```
<Error> void DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::routine(DB::TaskRuntimeDataPtr) [Queue = DB::MergeMutateRuntimeQueue]: Code: 432. DB::Exception: Unknown codec family code: 4: (while reading column event_date): While executing MergeTreeSequentialSource. (UNKNOWN_CODEC), Stack trace (when copying this message, always include the lines below):
```

**Comment by vdimir** [comment]
Could you please provide minimal example to reproduce? Did it works on previous versions?

**Comment by zhuokun** [comment]
I had dropped the database I created, but keep printng these error logs.


================================================
2022.02.23 22:31:03.049159 [ 24622 ] {}  void DB::MergeTreeBackgroundExecutor::routine(DB::TaskRuntimeDataPtr) [Queue = DB::MergeMutateRuntimeQueue]: Code: 432. DB::Exception: Unknown codec family code: 4: (while reading column event_date): While executing MergeTreeSequentialSource. (UNKNOWN_CODEC), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string, std::__1::allocator > const&, int, bool) @ 0xaebed1a in /usr/bin/clickhouse
1. DB::CompressionCodecFactory::get(unsigned char) const @ 0x1426fc92 in /usr/bin/clickhouse
2. DB::CompressedReadBufferBase::readCompressedData(unsigned long&, unsigned long&, bool) @ 0x14261ac2 in /usr/bin/clickhouse
3. DB::CompressedReadBufferFromFile::readBig(char*, unsigned long) @ 0x14264148 in /usr/bin/clickhouse
4. DB::SerializationNumber::deserializeBinaryBulk(DB::IColumn&, DB::ReadBuffer&, unsigned long, double) const @ 0xada8a6a in /usr/bin/clickhouse
5. DB::ISerialization::deserializeBinaryBulkWithMultipleStreams(COW::immutable_ptr&, unsigned long, DB::ISerialization::DeserializeBinaryBulkSettings&, std::__1::shared_ptr&, std::__1::unordered_map, std::__1::allocator >, COW::immutable_ptr, std::__1::hash, std::__1::allocator > >, std::__1::equal_to, std::__1::allocator > >, std::__1::allocator, std::__1::allocator > const, COW::immutable_ptr > > >*) const @ 0x14424895 in /usr/bin/clickhouse
6. DB::MergeTreeReaderCompact::readData(DB::NameAndTypePair const&, COW::immutable_ptr&, unsigned long, unsigned long, unsigned long, unsigned long, bool) @ 0x1557a690 in /usr/bin/clickhouse
7. DB::MergeTreeReaderCompact::readRows(unsigned long, unsigned long, bool, unsigned long, std::__1::vector::immutable_ptr, std::__1::allocator::immutable_ptr > >&) @ 0x15579e9e in /usr/bin/clickhouse
8. DB::MergeTreeSequentialSource::generate() @ 0x1559096e in /usr/bin/clickhouse
9. DB::ISource::tryGenerate() @ 0x15a40dd5 in /usr/bin/clickhouse
10. DB::ISource::work() @ 0x15a4099a in /usr/bin/clickhouse
11. DB::SourceWithProgress::work() @ 0x15c92a62 in /usr/bin/clickhouse
12. DB::ExecutionThreadContext::executeTask() @ 0x15a60ca3 in /usr/bin/clickhouse
13. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic*) @ 0x15a54b7e in /usr/bin/clickhouse
14. DB::PipelineExecutor::executeStep(std::__1::atomic*) @ 0x15a54280 in /usr/bin/clickhouse
15. DB::PullingPipelineExecutor::pull(DB::Chunk&) @ 0x15a6542c in /usr/bin/clickhouse
16. DB::PullingPipelineExecutor::pull(DB::Block&) @ 0x15a656ec in /usr/bin/clickhouse
17. DB::MergeTask::ExecuteAndFinalizeHorizontalPart::executeImpl() @ 0x154394ab in /usr/bin/clickhouse
18. DB::MergeTask::ExecuteAndFinalizeHorizontalPart::execute() @ 0x1543940b in /usr/bin/clickhouse
19. DB::MergeTask::execute() @ 0x1543e3ba in /usr/bin/clickhouse
20. DB::MergePlainMergeTreeTask::executeStep() @ 0x1542ffac in /usr/bin/clickhouse
21. DB::MergeTreeBackgroundExecutor::routine(std::__1::shared_ptr) @ 0xae95feb in /usr/bin/clickhouse
22. DB::MergeTreeBackgroundExecutor::threadFunction() @ 0xae95c39 in /usr/bin/clickhouse
23. ThreadPoolImpl::worker(std::__1::__list_iterator) @ 0xaf6546a in /usr/bin/clickhouse
24. ThreadFromGlobalPool::ThreadFromGlobalPool::scheduleImpl(std::__1::function, int, std::__1::optional)::'lambda0'()>(void&&, void ThreadPoolImpl::scheduleImpl(std::__1::function, int, std::__1::optional)::'lambda0'()&&...)::'lambda'()::operator()() @ 0xaf674a4 in /usr/bin/clickhouse
25. ThreadPoolImpl::worker(std::__1::__list_iterator) @ 0xaf62837 in /usr/bin/clickhouse
26. ? @ 0xaf662fd in /usr/bin/clickhouse
27. start_thread @ 0x817a in /usr/lib64/libpthread-2.28.so
28. __GI___clone @ 0xfcdc3 in /usr/lib64/libc-2.28.so
(version 22.2.2.1)



| |
TT
|
|
***@***.***
|
On 2/23/2022 21:09，Vladimir ***@***.***> wrote：

Could you please provide minimal example to reproduce? Did it works on previous versions?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by alexey-milovidov** [comment]
Do you use MergeTree or ReplicatedMergeTree?

**Comment by DipalPrajapati** [comment]
It is in ReplicatedMergeTree.

**Comment by vbmithr** [comment]
Same here.

**Comment by den-crane** [comment]
22.2.2.1 is out of support. Not actionable issue. No repro. No info.
