### ISSUE TITLE
If adding an output format Null is reasonable? 

### ISSUE THREAD

**Issue by taiyang-li** [ClickHouse/ClickHouse#34825]
**Use case**
In some cases, we only want to see other information except the real output data of query in clickhouse-client.  Maybe we can add an output format Null to realize it.

**Comment by den-crane** [comment]
But it exists for many years?

```
select * from numbers(1000000) format Null;
0 rows in set. Elapsed: 0.003 sec. Processed 1.05 million rows, 8.38 MB (326.46 million rows/s., 2.61 GB/s.)
```
