### ISSUE TITLE
"Unexpected inf or nan to integer conversion" error when using toInt32 and if/isNaN check

### ISSUE THREAD

**Issue by wentsul** [ClickHouse/ClickHouse#34854]
**Describe the unexpected behaviour**

"Unexpected inf or nan to integer conversion" error is thrown when calling `toInt32` on the result of an `if` expression that checks for `isNaN` and evaulates to `NULL`.

**How to reproduce**

* Which ClickHouse server version to use:  **21.12.4 revision 54452** & **22.2.2 revision 54455**
* Which interface to use, if matters: **clickhouse-client**
* Non-default settings, if any: **none**

* `CREATE TABLE` statements for all tables involved

```
create temporary table tmp_repro_nan_check (
  foo Nullable(Int32)
);
```

* Sample data for all these tables, use [clickhouse-obfuscator]

```
insert into tmp_repro_nan_check values (nan);
```

* Queries to run that lead to unexpected result
```
SELECT toInt32(if(isNaN(foo), NULL, foo))
FROM tmp_repro_nan_check
```

**Expected behavior**

Expect the result to be `NULL` similar to the following:

```
SELECT toInt32(NULL)
```

**Error message and/or stacktrace**

```
Code: 70. DB::Exception: Received from localhost:9000. DB::Exception: Unexpected inf or nan to integer conversion: while executing 'FUNCTION toInt32(if(isNaN(foo), NULL, foo) :: 3) -> toInt32(if(isNaN(foo), NULL, foo)) Nullable(Int32) : 0'. (CANNOT_CONVERT_TYPE)
```

**Additional context**

There seems to be an issues with returning `NULL` in the truthy/left branch of the condition. Updating the select statement to return `0` does not throw an error

```
SELECT toInt32(if(isNaN(foo), 0, foo))
FROM tmp_repro_nan_check

Query id: 6f91e2e3-caf2-4aa8-96a0-83bd6755ca37

┌─toInt32(if(isNaN(foo), 0, foo))─┐
│                               0 │
└─────────────────────────────────┘
```

**Comment by alexey-milovidov** [comment]
Related to short-circuit execution, CC @Avogar

**Comment by cipriancraciun** [comment]
I've just stumbled upon this with the following simple test-case, and it doesn't require `NaN`, just some `NULL` values:

~~~~
create temporary table tests (
		a Nullable(Float32),
		b Nullable(Float32),
		r Nullable(UInt8) alias round (least (a, b) / greatest (a / b) * 100)
);

insert into tests (a, b) values (1, 2), (2, 1), (3, null), (null, 3);


select a, b, round (least (a, b) / greatest (a / b) * 100) from tests;
select a, b, r from tests where a is not null and b is not null;
select a, b, r from tests;
~~~~

The output is:
~~~~
-- select a, b, round (least (a, b) / greatest (a / b) * 100) from tests;
┌────a─┬────b─┬─round(multiply(divide(least(a, b), greatest(divide(a, b))), 100))─┐
│    1 │    2 │                                                               200 │
│    2 │    1 │                                                                50 │
│    3 │ ᴺᵁᴸᴸ │                                                              ᴺᵁᴸᴸ │
│ ᴺᵁᴸᴸ │    3 │                                                              ᴺᵁᴸᴸ │
└──────┴──────┴───────────────────────────────────────────────────────────────────┘

-- select a, b, r from tests where a is not null and b is not null;
┌─a─┬─b─┬───r─┐
│ 1 │ 2 │ 200 │
│ 2 │ 1 │  50 │
└───┴───┴─────┘

-- select a, b, r from tests;
Code: 70. DB::Exception: Unexpected inf or nan to integer conversion: while executing 'FUNCTION _CAST(round(multiply(divide(least(a, b), greatest(divide(a, b))), 100)) :: 2, 'Nullable(UInt8)' :: 3) -> _CAST(round(multiply(divide(least(a, b), greatest(divide(a, b))), 100)), 'Nullable(UInt8)') Nullable(UInt8) : 6'. (CANNOT_CONVERT_TYPE)
~~~~

**Comment by fancyqlx** [comment]
> It's not related to short-circuit execution. I can get the same error even without function if:
> 
> ```sql
> select toInt32(materialize(CAST(nan, 'Nullable(Float64)')) / materialize(CAST(NULL, 'Nullable(Float64)')))
> ```
> 
> The error occurs because when we execute function `toInt32` on Nullable column we execute it on underlying column and then make the result Nullable according to Nullable mask. But if the value in nested column under NULL is `nan`, we will get the exception. It could be fixed by proper work with Nullable in case of conversion from Float to Int. Will see how to do it
@Avogar hi，any update for this problem, we had the same problem recently

**Comment by Avogar** [comment]
No updates. Our implementation of converting functions is really complicated and the fix is not obvious, I didn't have time for it yet.

**Comment by taiyang-li** [comment]
@Avogar I think I had fix the issue in https://github.com/ClickHouse/ClickHouse/pull/60129. And it is ready to review now, thanks!

**Comment by Ollysparse** [comment]
https://lnkr.fun/c654e5b



Nailed it—the answer’s mine
