### ISSUE TITLE
Failed to rename column in table

### ISSUE THREAD

**Issue by peter-gribanov** [ClickHouse/ClickHouse#34865]
Hi!

Has anyone encountered problems when renaming columns?

```sql
ALTER TABLE my_table
RENAME COLUMN my_column TO my_column_old
```

Result:

```
Received exception from server (version 20.5.2):
Code: 999. DB::Exception: Received from clickhouse:9001. DB::Exception: Connection loss.

0 rows in set. Elapsed: 2.270 sec.
```

Surprisingly, applying the migration aborted after 2 seconds it started.

Moreover, on another table with a similar structure in the same database, the migration was applied without problems.
On the dev server, the migration was applied without problems.

Perhaps the problem is in the number of partitions?

```sql
SELECT count()
FROM system.parts
WHERE database = 'my_database' AND table = 'my_table' AND active = 1
```

Result:

```
┌─count()─┐
│   21963 │
└─────────┘
```

**ClickHouse: 20.5.2**

**Comment by den-crane** [comment]
Check these https://github.com/ClickHouse/ClickHouse/issues/15882 https://github.com/ClickHouse/ClickHouse/issues/11933

**Comment by den-crane** [comment]
Is it replicated table? 
Check CH server.log, provide fragments with a stacktrace and surrounded rows.
Check Zookeeper logs.

**Comment by peter-gribanov** [comment]
There is nothing in the logs of ClickHouse and Zookeeper.

**Comment by peter-gribanov** [comment]
Checked again and no, the problem is clearly not in [this](https://github.com/ClickHouse/ClickHouse/issues/11933#issuecomment-654286261).

**Comment by den-crane** [comment]
Anyway, 20.5.2 is not supported. 
You have to reproduce the issue with supported or better with the latest version like 22.2. Only after that developers will start to investigate.

**Comment by den-crane** [comment]
@peter-gribanov There is no sense to leave it open.
1. 95% chances that the issue is already solved.
2. there is no sense to reproduce the issue.

( I am not a Clickhouse developer, I am Altinity support Eng. )
