### ISSUE TITLE
ninja-build missing in AUR repository

### ISSUE THREAD

**Issue by amab8901** [ClickHouse/ClickHouse#34867]
Here is the documentation I'm referring to:
https://clickhouse.com/docs/en/development/build/

It says that I should run this code in terminal:
$ sudo apt-get install git cmake python ninja-build

Problem is that ninja-build cannot be found in the AUR repository (I use ArchLinux, specifically Garuda.). Either update the name (perhaps you meant "ninja" rather than "ninja-build"?) or upload ninja-build in AUR repository

**Comment by vdimir** [comment]
There's ninja in official Arch repo https://archlinux.org/packages/community/x86_64/ninja/
so `pacman -S ninja` should work

**Comment by vdimir** [comment]
There's section https://clickhouse.com/docs/en/development/build/#how-to-build-clickhouse-on-any-linux

For example for "_Example for OpenSUSE Tumbleweed_" it's `sudo zypper install git cmake ninja clang-c++ python lld`

You can add section for arch if you want, it will be really appreciated
