### ISSUE TITLE
Syntex issues 

### ISSUE THREAD

**Issue by iamhimanshu0** [ClickHouse/ClickHouse#34863]
My ClickHouse client version 18.16.1 and I'm following this article https://altinity.com/blog/2020/5/21/clickhouse-kafka-engine-tutorial

when creating the table I'm using 
`CREATE TABLE readings (
    readings_id Int32 Codec(DoubleDelta, LZ4),
    time DateTime Codec(DoubleDelta, LZ4),
    date ALIAS toDate(time),
    temperature Decimal(5,2) Codec(T64, LZ4)
)
ENGINE = MergeTree()
Partition by toYYYYMM(time)
ORDER BY (readings_id, time);`

but I'm getting an error that says 
`
 Codec(DoubleDelta, LZ4),
    time DateTime Codec(DoubleDelta, LZ4),
    date ALIAS toDate(time),
    temperature Decimal(5,2) Codec(T64, LZ4)
)
ENGINE = MergeTr. Expected one of: token, ClosingRoundBracket, Comma, DEFAULT, MATERIALIZED, ALIAS, COMMENT, e.what() = DB::Exception`

**Comment by den-crane** [comment]
Upgrade ClickHouse client .
Upgrade Clickhouse. 

clickHouse-client validates SQL and 18.16.1 does not support `Codec(DoubleDelta, LZ4` syntax because Codecs were implemented later.
