### ISSUE TITLE
Method optimize is not supported by storage Distributed (version 21.3.9.83 (official build))

### ISSUE THREAD

**Issue by sbbug** [ClickHouse/ClickHouse#34861]
Code: 48, e.displayText() = DB::Exception: Method optimize is not supported by storage Distributed (version 21.3.9.83 (official build))

hello,
we build a clickhouse cluster in three machine, after insert data to distribution table,we use cmd 'optimize table dis_alerts on cluster default_cluster FINAL' to merge repeated record,but errors below:
`
┌─host──────┬─port─┬─status─┬─error───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─num_hosts_remaining─┬─num_hosts_active─┐
│ 9.0.16.11 │ 9000 │     48 │ Code: 48, e.displayText() = DB::Exception: Method optimize is not supported by storage Distributed (version 21.3.9.83 (official build)) │                   2 │                0 │
│ 9.0.16.17 │ 9000 │     48 │ Code: 48, e.displayText() = DB::Exception: Method optimize is not supported by storage Distributed (version 21.3.9.83 (official build)) │                   1 │                0 │
│ 9.0.16.4  │ 9000 │     48 │ Code: 48, e.displayText() = DB::Exception: Method optimize is not supported by storage Distributed (version 21.3.9.83 (official build)) │                   0 │                0 │
└───────────┴──────┴────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴─────────────────────┴──────────────────┘

`
following:

`
disk table:
┌─statement──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ CREATE TABLE dis_test.test_alerts
(
    `tenant_id` UInt32,
    `alert_id` String,
    `timestamp` DateTime CODEC(Delta(4), LZ4),
    `alert_data` String,
    `acked` UInt8 DEFAULT 0,
    `ack_time` DateTime DEFAULT toDateTime(0),
    `ack_user` LowCardinality(String) DEFAULT ''
)
ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{layer}-{shard}/dis_test/test_alerts', '{replica}', ack_time)
PARTITION BY tenant_id % 10
ORDER BY (tenant_id, timestamp, alert_id)
SETTINGS index_granularity = 8192 │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

logic table:
┌─statement──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ CREATE TABLE dis_test.dis_alerts
(
    `tenant_id` UInt32,
    `alert_id` String,
    `timestamp` DateTime CODEC(Delta(4), LZ4),
    `alert_data` String,
    `acked` UInt8 DEFAULT 0,
    `ack_time` DateTime DEFAULT toDateTime(0),
    `ack_user` LowCardinality(String) DEFAULT ''
)
ENGINE = Distributed('default_cluster', 'dis_test', 'test_alerts', tenant_id) │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
`

**Comment by den-crane** [comment]
You should use `optimize table dis_test.test_alerts on cluster default_cluster FINAL`

Only MergeTree family supports `optimize`.

**Comment by sbbug** [comment]
Nice!
It's ok and thank you!
