### ISSUE TITLE
ClickHouse Kafka Engine : dataraw_table nothing to commit

### ISSUE THREAD

**Issue by tietouwaa** [ClickHouse/ClickHouse#34899]
I deployed single node clickhouse. There are three kafka engine tables in total. Now I have added a Kafka engine table. Its topics and consumers are consumed normally, and no errors are reported in the log, but no data can be found in this table. The following is my build table and related configuration information.

**1. create table statement**

```
CREATE TABLE tmp.ngx_starfm_queue
(
    `@timestamp` String,
    `host` String,
    `clientip` String,
    `size` UInt32,
    `responsetime` Array(Float32),
    `upstreamtime` String,
    `upstreamaddr` String,
    `http_host` String,
    `uri` String,
    `scheme` String,
    `request_length` String,
    `request_uri` String,
    `request_method` String,
    `country` String,
    `xff` String,
    `referer` String,
    `agent` String,
    `status` String,
    `user_id` String
)
ENGINE = Kafka
SETTINGS kafka_broker_list = 'XXX', kafka_topic_list = 'ngx-starfm', kafka_group_name = 'CK-prod-starfm', kafka_format = 'JSONEachRow', kafka_num_consumers = 3, kafka_skip_broken_messages = 100, kafka_thread_per_consumer = 1, kafka_max_block_size = 262020, kafka_commit_every_batch = 2 │


CREATE TABLE ngx_log.starfm_local
(
    `timestamp` DateTime,
    `date` Date,
    `hour` UInt16,
    `host` LowCardinality(String),
    `clientip` String,
    `size` UInt32,
    `responsetime` Array(Float32),
    `upstreamtime` Array(Float32),
    `upstreamaddr` Nullable(String),
    `http_host` String,
    `uri` String,
    `scheme` String,
    `request_length` String,
    `request_uri` String,
    `request_method` String,
    `country` String,
    `xff` Nullable(String),
    `referer` String,
    `agent` String,
    `status` UInt16,
    `user_id` Nullable(String)
)
ENGINE = MergeTree
PARTITION BY date
PRIMARY KEY status
ORDER BY (status, timestamp, hour)
TTL timestamp + toIntervalHour(2) TO VOLUME 'volume_cfs1', timestamp + toIntervalDay(7)
SETTINGS storage_policy = 'hot_to_cold', index_granularity = 8192


CREATE MATERIALIZED VIEW tmp.ngx_starfm_queue_to_local TO ngx_log.starfm_local
(
    `timestamp` DateTime,
    `date` String,
    `hour` String,
    `host` String,
    `clientip` String,
    `size` UInt32,
    `responsetime` Array(Float32),
    `upstreamtime` String,
    `upstreamaddr` String,
    `http_host` String,
    `uri` String,
    `scheme` String,
    `request_length` String,
    `request_uri` String,
    `request_method` String,
    `country` String,
    `xff` String,
    `referer` String,
    `agent` String,
    `status` String,
    `user_id` String
) AS
SELECT
    parseDateTimeBestEffort(`@timestamp`) AS timestamp,
    formatDateTime(toDate(parseDateTimeBestEffort(`@timestamp`)), '%F') AS date,
    formatDateTime(toDateTime(parseDateTimeBestEffort(`@timestamp`)), '%H') AS hour,
    host,
    clientip,
    size,
    responsetime,
    upstreamtime,
    upstreamaddr,
    http_host,
    uri,
    scheme,
    request_length,
    request_uri,
    request_method,
    country,
    xff,
    referer,
    agent,
    status,
    user_id
FROM tmp.ngx_starfm_queue

```
**2、【topic & consumer configure.  Picture 1】**
![gthB7NjK2z](https://user-images.githubusercontent.com/39645491/155697837-5d91950a-2464-42c9-b41c-f201ce799142.png)
**3、【clickhouse log.  Picture 2&3 】** 
![image](https://user-images.githubusercontent.com/39645491/155698926-00ce96ae-eb54-4c9c-b534-b881d69bface.png)
![image](https://user-images.githubusercontent.com/39645491/155699806-c6c4bb47-d16d-48a0-bc3c-d008024bee25.png)
**4、【clickhouse's configure & current situation.  Picture 4 】**

![VPr3sa3QZe](https://user-images.githubusercontent.com/39645491/155699840-ad44dbc4-defe-4c27-85b6-706b0e3f9629.png)

Looking forward to your answer, this has been bothering me for a long time, thank you 🙏

**Comment by tietouwaa** [comment]
1. I tried restarting clickhouse but it didn't work;
2. The original log is in json format, not nested json. But I still tried to add kafka_row_delimiter, it didn't work;
3. My click house version is 21.11.5.33 (official build);
4. I try to modify this parameter kafka_skip_broken_messages = 65539 or remove this parameter, it didn't work

**Comment by filimonov** [comment]
```
kafka_commit_every_batch = 2 
```

remove that

**Comment by tietouwaa** [comment]
> ```
> kafka_commit_every_batch = 2 
> ```
> 
> remove that

thanks for your reply
 but. didn't work   And this is the latest log
![image](https://user-images.githubusercontent.com/39645491/155708867-75d41f55-e7dc-4d90-9feb-69fac54932f8.png)

![image](https://user-images.githubusercontent.com/39645491/155708744-9eb609c5-b7ea-430a-921e-cda4f19889bc.png)

**Comment by tietouwaa** [comment]
@vdimir @filimonov  Do you have any other troubleshooting ideas or do you need me to provide other information?

**Comment by filimonov** [comment]
"Parsing return no rows" - are your messages empty / malformed?

**Comment by tietouwaa** [comment]
> "Parsing return no rows" - are your messages empty / malformed?
No I also use filebeat to store logs to local disk via the same topic. Local logs are updated in real time. This is the log format
![image](https://user-images.githubusercontent.com/39645491/157487092-a6f5a522-331d-4d45-bff0-dbc999bba6f1.png)

**Comment by filimonov** [comment]
Try to remove `kafka_skip_broken_messages = 100` and check what exceptions you will have.

**Comment by tietouwaa** [comment]
I have solved this problem thanks for the support
