### ISSUE TITLE
Problem with projections

### ISSUE THREAD

**Issue by alps99w** [ClickHouse/ClickHouse#34891]
> You have to provide the following information whenever possible.

sum(round((caseWithExpression(num, 1, 0.13, 2, 0.14, 3, 0.07, 4, 0.02, 5, 0.01, 6, 0.03, 7, 0.02, 8, 0.001, 9, 0.002, 10, 0.0202, 0) * value) + 0.01)) AS sum_num_value,

instead of using alias as the filename (sum_num_value.bin).  CH use the full column as a file name (sum(round((caseWithExpression(num, 1, 0.13, 2, 0.14, 3, 0.07, 4, 0.02, 5, 0.01, 6, 0.03, 7, 0.02, 8, 0.001, 9, 0.002, 10, 0.0202, 0) * value) + 0.01)).bin)

in the backend, CH throws a filename too long exception

Cannot open file /var/lib/clickhouse/store/5f8/5f88c9e5-d041-46fb-89e7-984410bcce30/tmp_merge_202201_118_125_1/rg_agg.proj/sum%28round%28plus%28multiply%28caseWithExpression%28true_rank%2C%201%2C%200%2E193%2C%202%2C%200%2E114%2C%203%2C%200%2E077%2C%204%2C%200%2E052%2C%205%2C%200%2E041%2C%206%2C%200%2E033%2C%207%2C%200%2E026%2C%208%2C%200%2E021%2C%209%2C%200%2E02%2C%2010%2C%200%2E022%2C%200%29%2C%20avg_search_volume%29%2C%200%2E01%29%29%29.bin, errno: 36, strerror: File name too long. (CANNOT_OPEN_FILE), Stack trace (when copying this message, always include the lines below)...
> A clear and concise description of what works not as it is supposed to.

CH Version 22.2

**Comment by amosbird** [comment]
It's a known limitation. You can try replacing those long expressions with materialized columns for now.

**Comment by freemanoid** [comment]
> It's a known limitation. You can try replacing those long expressions with materialized columns for now.

Can confirm that this workaround works on `22.1.3.7`. Use `materialize` instead of `alias` in `ALTER TABLE table_name ADD COLUMN ...` and make sure to run `OPTIMIZE ... FINAL` to actually materialize the column.

**Comment by vilia** [comment]
Added a small test workaround for this which is failed on 

```
3ac210a90644 :) select version();

SELECT version()

┌─version()────┐
│ 22.10.1.1877 │
└──────────────┘
```

```SQL
CREATE DATABASE test;

CREATE TABLE test.test_table
(
    `pk` Int32,
    `long_long_long_long_long_column_name_1` UInt8,
    `long_long_long_long_long_column_name_2` UInt8,
    `long_long_long_long_long_column_name_3` UInt8,
    `long_long_long_long_long_column_name_4` UInt8,
    `long_long_long_long_long_column_name_5` UInt8,
    `long_long_long_long_long_column_name_6` UInt8,
    `long_long_long_long_long_column_name_7` UInt8,
    `long_long_long_long_long_column_name_8` UInt8,
    `long_long_long_long_long_column_name_9` UInt8,
    PROJECTION test_projection
    (
        SELECT
            pk,
            countIf((long_long_long_long_long_column_name_1 = 1) AND (long_long_long_long_long_column_name_2 = 1) AND (long_long_long_long_long_column_name_3 = 1) AND (long_long_long_long_long_column_name_4 = 1) AND (long_long_long_long_long_column_name_5 = 1) AND (long_long_long_long_long_column_name_6 = 1) AND (long_long_long_long_long_column_name_7 = 1) AND (long_long_long_long_long_column_name_8 = 1) AND (long_long_long_long_long_column_name_9 = 1))
        GROUP BY pk
    )
)
ENGINE = MergeTree
ORDER BY pk
SETTINGS min_bytes_for_wide_part = 0, min_rows_for_wide_part = 0;

insert into test.test_table values (1, 1, 1, 1, 1, 1, 1, 1, 1, 1);
```

the most tricky moment regarding this limitation that it doesn't somehow affects projection functionality while the table data stored in one file in `Compact` format . But once `min_bytes_for_wide_part` / `min_rows_for_wide_part` are exceeded even the process of merging couldn't be done with the errors like in initial message

therefore while such behaviour isn't fixed it's reasonable to make `column in projection` length check on table\projection creation

**Comment by XiaoqiMa** [comment]
@amosbird we had also encoutered the same issue, does the community have future plans to fix this issue?
e.g 
alter table testadd projection if not exists pro0 (select d, tt, dt, sum(case when d >= toDate(1625068800) or d >= toDate(1593532800) and d < toDate(1608220800) then toFloat64(mm) ELSE NULL END) group by d,  tt,  dt);

**Comment by amosbird** [comment]
https://github.com/ClickHouse/ClickHouse/pull/50612 will help

**Comment by yiyitaba-sjy** [comment]
Verify that clickhouse 24.3 still has strerror: File name too long. In addition to replacing those long expressions with materialized columns. Are there any other options? The solution, the issue:https://github.com/ClickHouse/ClickHouse/pull/50612, no cover to the Projection. Just for dataPart and table
