### ISSUE TITLE
Inserting JSON with Array(Tuple<T>) type fails in JSONEachRow

### ISSUE THREAD

**Issue by RubieV** [ClickHouse/ClickHouse#34904]
**Describe the unexpected behaviour**
Inserting JSON with Array(Tuple<T>) type fails in `JSONEachRow`. The exact type implemented using `JSONExtract` works as expected.

**How to reproduce**
* yandex/clickhouse-server:21.3.20.1
* interface: JDBC
```SQL
DROP TABLE IF EXISTS test_json;
CREATE TABLE test_json (
    `array-of-tuples` Array(Tuple(id String, name String))
)
ENGINE = Memory();

SET input_format_skip_unknown_fields = 0;
SET input_format_import_nested_json = 0;
SET flatten_nested = 0;

INSERT INTO test_json FORMAT JSONEachRow {"array-of-tuples":[{"id": "test-1", "name": "test"}]}
SELECT * FROM test_json

```

**Expected behavior**
```SQL
SELECT
    JSONExtract(message, 'array-of-tuples', 'Array(Tuple(id String, name String))')
    FROM (
        SELECT ( '{"array-of-tuples":[{"id": "test-1", "name": "test"}]}' as message ))
;
```

**Error message and/or stacktrace**
`DB::Exception: Unknown field found while parsing JSONEachRow format: attack: (at row 1)`

**Comment by den-crane** [comment]
flatten_nested -- impacts on `CREATE TABLE` command.

```
SET flatten_nested = 0;

CREATE TABLE test_json (
    `array-of-tuples` Array(Tuple(id String, name String))
)
ENGINE = Memory();

insert into test_json format JSONEachRow {"array-of-tuples":[["a","b"],["c","d"]]}
;

select * from test_json;
┌─array-of-tuples───────┐
│ [('a','b'),('c','d')] │
└───────────────────────┘
```

AFAIK `{"array-of-tuples":[{"id": "test-1", "name": "test"}]}` is impossible to ingest with JSONEachRow

Try JSONExtract https://kb.altinity.com/altinity-kb-schema-design/altinity-kb-jsonasstring-and-mat.-view-as-json-parser/  https://kb.altinity.com/altinity-kb-queries-and-syntax/jsonextract-to-parse-many-attributes-at-a-time/

**Comment by RubieV** [comment]
Hi Danny,

Thanks for your alternative, I'm currently using that. I think this is the current best practice.

I might have missed the mark in my initial description. The behavior is inconsistent: JSONExtract successfully parses the data structure, but the JSONEachRow fails to parse the same structure.

**Comment by den-crane** [comment]
JSONEachRow is a subset of JSON. JSONEachRow is simple JSON, it does not support nesting.

In the contrary JSONExtract supports JSON.
