### ISSUE TITLE
Distributed table loads before parent table

### ISSUE THREAD

**Issue by rasstroen** [ClickHouse/ClickHouse#34914]
0) version 22.1.3.7

1) Created distributed table on existing table
`CREATE TABLE test_daily.membersDistributed
ENGINE = Distributed('cluster', 'test_daily', 'members')
`
2) Restart server

3) In logs seeing membersDistributed attaching before members and restart fails with error:

`2022.02.25 17:25:40.757552 [ 1888598 ] {} <Debug> test_daily.incomes (63f715e6-22df-4532-a3f7-15e622dfb532): Loading data parts
2022.02.25 17:25:40.757733 [ 1888598 ] {} <Debug> test_daily.incomes (63f715e6-22df-4532-a3f7-15e622dfb532): There are no data parts
2022.02.25 17:25:40.768269 [ 1888588 ] {} <Debug> test_daily.memberQualityEvents (fe884245-65c7-48ea-be88-424565c748ea): Loading data parts
2022.02.25 17:25:40.770835 [ 1888588 ] {} <Debug> test_daily.memberQualityEvents (fe884245-65c7-48ea-be88-424565c748ea): Loaded data parts (2 items)
2022.02.25 17:25:40.771141 [ 1888589 ] {} <Debug> test_daily.lastClickVerificationEvents (e700288a-8784-4326-a700-288a87840326): Loading data parts
2022.02.25 17:25:40.776903 [ 1888592 ] {} <Debug> test_daily.ltvReportData (823fb4f4-0900-425f-823f-b4f40900725f): Loading data parts
2022.02.25 17:25:40.780658 [ 1888592 ] {} <Debug> test_daily.ltvReportData (823fb4f4-0900-425f-823f-b4f40900725f): Loaded data parts (3 items)
2022.02.25 17:25:40.781979 [ 1888589 ] {} <Debug> test_daily.lastClickVerificationEvents (e700288a-8784-4326-a700-288a87840326): Loaded data parts (3 items)
2022.02.25 17:25:40.814546 [ 1888589 ] {} <Information> TablesLoader: 8.882720333102013%
2022.02.25 17:25:40.939701 [ 1888535 ] {} <Error> Application: Caught exception while loading metadata: Code: 60. DB::Exception: Table test_daily.members doesn't exist: Cannot attach table `test_daily`.`membersDistributed` from metadata file /var/lib/clickhouse/store/8c0/8c04fffb-0043-4888-8c04-fffb00434888/membersDistributed.sql from query ATTACH TABLE test_daily.membersDistributed UUID '48ed7649-b0e4-4d71-9048-bc6a0868582b' ENGINE = Distributed('cluster', 'test_daily', 'members'). (UNKNOWN_TABLE), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa82d07a in /usr/bin/clickhouse
1. DB::Exception::Exception<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&) @ 0xa89b823 in /usr/bin/clickhouse
2. void std::__1::__optional_storage_base<DB::Exception, false>::__construct<int const&, char const (&) [23], std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(int const&, char const (&) [23], std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&) @ 0x1352ac0f in /usr/bin/clickhouse
3. DB::DatabaseCatalog::getTableImpl(DB::StorageID const&, std::__1::shared_ptr<DB::Context const>, std::__1::optional<DB::Exception>*) const @ 0x13519082 in /usr/bin/clickhouse
4. DB::DatabaseCatalog::getTable(DB::StorageID const&, std::__1::shared_ptr<DB::Context const>) const @ 0x1352126b in /usr/bin/clickhouse
5. DB::getStructureOfRemoteTableInShard(DB::Cluster const&, DB::Cluster::ShardInfo const&, DB::StorageID const&, std::__1::shared_ptr<DB::Context const>, std::__1::shared_ptr<DB::IAST> const&) @ 0x140d136e in /usr/bin/clickhouse
6. DB::getStructureOfRemoteTable(DB::Cluster const&, DB::StorageID const&, std::__1::shared_ptr<DB::Context const>, std::__1::shared_ptr<DB::IAST> const&) @ 0x140d56d7 in /usr/bin/clickhouse
7. DB::StorageDistributed::StorageDistributed(DB::StorageID const&, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context const>, std::__1::shared_ptr<DB::IAST> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::DistributedSettings const&, bool, std::__1::shared_ptr<DB::Cluster>, std::__1::shared_ptr<DB::IAST>) @ 0x13eb91fa in /usr/bin/clickhouse
8. ? @ 0x13ed0602 in /usr/bin/clickhouse`

4) On 6 servers only 2 fails with this restart, order  of attach tables on different servers differs.

Maybe its a good idea to attach Distributed only after all others tables (because Distributed based on other tables)

**Comment by rasstroen** [comment]
src/Databases/TablesLoader.cpp:24 found logic was changed recently of dependencies in tables, but cant find a bug if it exists

**Comment by rasstroen** [comment]
seems because i doesnt add "AS" into create query

**Comment by tavplubix** [comment]
Hm, probably it's because table structure is not specified in CREATE query, so ClickHouse is trying to get structure of the source table. It should be fixed in #34684

cc: @Avogar

**Comment by Avogar** [comment]
> Hm, probably it's because table structure is not specified in CREATE query, so ClickHouse is trying to get structure of the source table. It should be fixed in #34684

Yes, you are right. Will add such test in my PR
