### ISSUE TITLE
LineAsString drop one char

### ISSUE THREAD

**Issue by Dwrite** [ClickHouse/ClickHouse#34918]
VersionInfo:

ClickHouse client version 21.11.4.1.
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 21.11.4 revision 54450.

 CREATE TABLE default.test_queue
(
    `message` String
)
ENGINE = Kafka
SETTINGS kafka_broker_list = '******', kafka_topic_list = 'test', kafka_group_name = 'krooswu_test', kafka_format = 'LineAsString', kafka_skip_broken_messages = 100, kafka_num_consumers = 1, kafka_thread_per_consumer = 1 

bin/kafka-console-producer.sh --broker-list ***** --topic test 
check11
check22

SELECT *
FROM test_queue

Query id: d691e3cc-9cf7-45ed-a1e7-2b4dd6ff52dd

┌─message─┐
│ check1 │
│ check2

**Comment by Dwrite** [comment]
I found the bug on src/Processors/Formats/Impl/LineAsStringRowInputFormat.cpp 
<img width="739" alt="image" src="https://user-images.githubusercontent.com/1624810/155847007-63983ffe-7a5f-48d7-836b-d78a738821f1.png">

**Comment by filimonov** [comment]
I think you should use RawBLOB format instead. But yep that seems like an issue.

**Comment by Dwrite** [comment]
ok. should i close this issue ？

**Comment by alexey-milovidov** [comment]
Thank you for reporting!

I also found this absolutely wrong and horrible code a month ago and fixed it: https://github.com/ClickHouse/ClickHouse/pull/34306
