### ISSUE TITLE
Auditing log for user log in history

### ISSUE THREAD

**Issue by thalesvon** [ClickHouse/ClickHouse#34928]
Hi Clickhouse team,

Looking through the Operations and Monitoring documentation I did not find anything regarding auditing my clickhouse cluster.
At this point I am interest in auditing and keeping track of user login history into my clickhouse cluster. 

On the table `system.query_log` I can have a rough understanding of when my user log in based on the timestamps of their queries, but dealing with that just to get their login would be additional work I imagine I can get around it.

Is there an mechanism implemented on Clickhouse out of the box to keep track of user log in history or that is something I would need to implement myself?

Thanks

**Comment by KochetovNicolai** [comment]
As far as I know, there is no a good way to get this information. Probably you can try to parse system.text_log.
Likely, there will be a special system table for it.

**Comment by den-crane** [comment]
I don't think that audit to table is good enough for audit purposes. Usually audit trail requires right separation. But in case of table a malicious user with full access to Clickhouse will be able to clean trail.

**Comment by alexey-milovidov** [comment]
There is the `system.session_log` table for this purpose.
