### ISSUE TITLE
Provide bare minimal default configuration

### ISSUE THREAD

**Issue by knoguchi** [ClickHouse/ClickHouse#34927]
**Issue**

I configure my ClickHouse using /etc/clickhouse-server/config.xml unmodified, and /etc/clickhouse-server/config.d/overrides.xml (and  yaml).   The config.d overriding is a great feature that separates essential configuration keys and sane default values from my customizations.  Very clean.  It's especially nice when we upgrade ClickHouse versions.

However it's not perfect at this moment.

As of now the default config.xml contains a lot of example configurations, and configs for tests.  While they are great for feature demo, they are problematic for production deployment.   Currently I put `remove` attributes in my config.d overrides to remove tests, and disable optional features.  It still doesn't prevent accidental enablement of new optional features in the future.

For example <remote_servers> has configs for testing.   https://github.com/ClickHouse/ClickHouse/blob/ba9150abb00b31234ec1a6b426f3b36978f068c8/programs/server/config.xml#L622-L756

MySQL and Postgres features are no longer new but I consider them optional.  They open ports 9004 and 9005 by default.   What if a future version ClickHouse would add more features and would open more ports by default?  It's not great.  Anyone who wants to enable them can do that using config.d quite easily instead.
https://github.com/ClickHouse/ClickHouse/blob/ba9150abb00b31234ec1a6b426f3b36978f068c8/programs/server/config.xml#L109-L114

**Proposal**
- I would like a bare minimal default config.xml.  Examples for optional features in &lt;!-- comment --&gt; are totally fine.
- Create config.test.xml and move all configs for testing.
- Create config.example.xml for full feature example.

**Comment by alexey-milovidov** [comment]
By the way, there is also an embedded default config for the server.
If you run it without a `--config` parameter or withour a `config.xml` file in the current working directory, it will start up with the embedded config.

**Comment by alexey-milovidov** [comment]
Here it is: https://github.com/ClickHouse/ClickHouse/blob/master/programs/server/embedded.xml

**Comment by knoguchi** [comment]
Ok, thanks.  My observation is it's common to include the config.xml as default configuration in distribution packages.  For example the official Debian package does that.  So does Yandex container image for Kubernetes.   Do you recommend the package maintainers to create their own default config.xml? If so, I will move this discussion to appropriate places e.g. Debian bug tracker, Yandex, or clickhouse-operator
