### ISSUE TITLE
TTL Don't work

### ISSUE THREAD

**Issue by Data-bytes305** [ClickHouse/ClickHouse#34939]
version:   clickhouse-22.2.2.1

select * from system.disks;

![image](https://user-images.githubusercontent.com/83893570/155937399-f564e1b5-5d2d-416f-959d-ff5d93b6eba2.png)

CREATE TABLE test.table_ttl_to_hdd
(
    d Date,
    a Int
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(d)
ORDER BY d
TTL  d +  toIntervalDay(45)  to DISK 'hdd';

but throw error.
Code: 450. DB::Exception: No such disk `hdd` for given storage policy. (BAD_TTL_EXPRESSION) (version 22.2.2.1)
 

but i change  'hdd' to 'default' , it work successfully.

**Comment by rkozlo** [comment]
Show your storage policies. As i can see it using 'default' one which hasn't 'hdd' if you not overwrite config.

**Comment by Data-bytes305** [comment]
<img width="1006" alt="image" src="https://user-images.githubusercontent.com/83893570/155942054-ca3e8a06-f319-4982-a370-0921914ab46b.png">

**Comment by rkozlo** [comment]
As you can see 'default' storage policy hasn't disk like 'hdd'. If you want to use it, you have to overwrite 'default' storage policy and 'default' volume. Consider if you really need this since 'default' disk and 'hdd' disk are the same drive.

**Comment by Data-bytes305** [comment]
@rkozlo  thank you !
