### ISSUE TITLE
Can I use 'replicated_max_parallel_fetches' to limit the speed of data fetch between replicas ?

### ISSUE THREAD

**Issue by guaiguaidashu** [ClickHouse/ClickHouse#34943]
> ClickHouse Version 21.3

`replicated_max_parallel_fetches`
`replicated_max_parallel_fetches_for_table`
`replicated_max_parallel_fetches_for_host`

What are these three parameters for ?

What is the difference between these three parameters ?

**Comment by KochetovNicolai** [comment]
All those settings are obsolete already. In 31.3, you can probably decrease `replicated_max_parallel_fetches`, it may throttle fetches implicitly, however, no guarantees on result speed.

It's better to use `max_replicated_fetches_network_bandwidth` and `max_replicated_sends_network_bandwidth`, see #24573
