### ISSUE TITLE
Woboq online code browser stopped working

### ISSUE THREAD

**Issue by kashwy** [ClickHouse/ClickHouse#34948]
[**https://clickhouse.com/codebrowser/html_report/ClickHouse/src/index.html**
  ](https://clickhouse.com/codebrowser/html_report/ClickHouse/src/index.html)

returns the following message:

```xml
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Resource>/codebrowser/html_report/ClickHouse/src/index.html</Resource>
<RequestId>fd88bda5f268d124</RequestId>
</Error>
```

**Comment by alesapin** [comment]
Sorry, forget to update redirect... you can temporarily use https://s3.amazonaws.com/clickhouse-test-reports/codebrowser/ClickHouse/index.html.

**Comment by alexey-milovidov** [comment]
https://github.com/ClickHouse/clickhouse-website-worker/pull/125

**Comment by alexey-milovidov** [comment]
https://clickhouse.com/codebrowser/ClickHouse/src/index.html

**Comment by kashwy** [comment]
Thanks, but there's an issue, I was able to move cursor the link on the popup window when mouse over a variable in previous URL.
When I use this new link,  if I move cursor , the popup disappeared , so I am not able to go the reference on the popup.
