### ISSUE TITLE
[aarch64] On the CentOS 7.6 operating system for ClickHouse 21.8 ，a core dump occurs after the startup

### ISSUE THREAD

**Issue by hantaoliulinux** [ClickHouse/ClickHouse#34958]
log info:
  .....
 <Debug> Application [Server.cpp] : begin add supergroup clickhouse to cache.
 <Debug> Application [Server.cpp] : begin to listening HTTP.
 <Debug> Application [Server.cpp] : begin to listening HTTPS.
 <Information> Application [Server.cpp] : Listening for https:XXXXX:XX
 <Debug> Application [Server.cpp] : begin to listening TCP.
 <Debug> Application [Server.cpp] : begin to listening TCP SSL.
 <Information> Application [Server.cpp:1321] : Listening for connections with secure native protocol (tcp_secure):
 <Debug> Application [Server.cpp] : begin to listening Interserver IO HTTP.
 <Information> Application [Server.cpp] : Listening for secure replica communication (interserver): https://XXXXXX:XXXX
 <Debug> Application [Server.cpp] : begin to listening mysql.
 <Debug> Application [Server.cpp] : begin to listening prometheus.
 <Trace> AsynchronousMetrics [AsynchronousMetrics.cpp:558] : MemoryTracking: was 10.14 MiB, peak 14.87 MiB, will set to 363.50 MiB (RSS), difference: 353.36 MiB
 <Fatal> Application: Child process was terminated by signal 11.

Problems I found by adding logs：
in this file base/common/shift10.cpp,  when  multiplication of data of the long double type , the core occur ; However, in the 21.3 version, this is already the case, and no similar problem occurs.
I also found that this problem occurs when compiling the release version, but not when compiling the debug version. Appears only in the combination of arm and centos.

**Comment by KochetovNicolai** [comment]
Could you please attach the stacktrace? If you can't find it in the logs, try to run the server with gdb:
```
sudo -u clickhouse gdb clickhouse
run --config-file /etc/clickhouse-server/config.xml
...
bt
```

**Comment by hantaoliulinux** [comment]
Add the following information: The debug version compiled by me can work normally, so the gdb clickhouse is normal. Core occurs only in the compiled release version.

**Comment by vdimir** [comment]
@hantaoliulinux

Does our binary work? https://builds.clickhouse.com/master/aarch64/clickhouse

Provide, please build command you use (`cmake`, `ninja` etc)

**Comment by hantaoliulinux** [comment]
> 



> run --config-file

This GDB was configured as "aarch64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /mnt/ClickHouse_Kernel/buildE/programs/clickhouse...(no debugging symbols found)...done.
(gdb) run --config-file /mnt/ClickHouse_Kernel/programs/server/config.xml
Starting program: /mnt/ClickHouse_Kernel/buildE/programs/clickhouse --config-file /mnt/ClickHouse_Kernel/programs/server/config.xml
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Use one of the following commands:
clickhouse local [args]
clickhouse client [args]
clickhouse benchmark [args]
clickhouse server [args]
clickhouse extract-from-config [args]
clickhouse compressor [args]
clickhouse format [args]
clickhouse copier [args]
clickhouse obfuscator [args]
clickhouse git-import [args]
clickhouse keeper [args]
clickhouse keeper-converter [args]
clickhouse install [args]
clickhouse start [args]
clickhouse stop [args]
clickhouse status [args]
clickhouse restart [args]
clickhouse hash-binary [args]
[Inferior 1 (process 31219) exited with code 0377]
Missing separate debuginfos, use: debuginfo-install glibc-2.17-260.el7.aarch64 xz-libs-5.2.2-1.el7.aarch64
(gdb) bt
No stack.
(gdb)

**Comment by alexey-milovidov** [comment]
```
Application [Server.cpp] : begin add supergroup clickhouse to cache.
Application [Server.cpp] : begin to listening HTTP.
Application [Server.cpp] : begin to listening HTTPS.
Application [Server.cpp] : Listening for https:XXXXX:XX
Application [Server.cpp] : begin to listening TCP.
Application [Server.cpp] : begin to listening TCP SSL.
Application [Server.cpp:1321] : Listening for connections with secure native protocol (tcp_secure):
Application [Server.cpp] : begin to listening Interserver IO HTTP.
Application [Server.cpp] : Listening for secure replica communication (interserver): https://XXXXXX:XXXX
Application [Server.cpp] : begin to listening mysql.
Application [Server.cpp] : begin to listening prometheus.
AsynchronousMetrics [AsynchronousMetrics.cpp:558] : MemoryTracking: was 10.14 MiB, peak 14.87 MiB, will set to 363.50 MiB (RSS), difference: 353.36 MiB
Application: Child process was terminated by signal 11.
```

This does not look like ClickHouse logs.

**Comment by alexey-milovidov** [comment]
Older versions are not tested for ARM.
You should install the latest official build.

**Comment by alexey-milovidov** [comment]
> begin add supergroup clickhouse to cache.

This is not ClickHouse, it is something else.
