### ISSUE TITLE
Attempt to read after eof

### ISSUE THREAD

**Issue by sdd1998** [ClickHouse/ClickHouse#34953]
DB::Exception: Attempt to read after eof: (while reading column http_user): (while reading from part /xxxxx/01/store/b4f/b4f7cad2-943c-49b4-b8e1-44399bcc45a6/457190_82_107_4/ from mark 0 with max_rows_to_read = 8192): While executing MergeTreeReverse. (ATTEMPT_TO_READ_AFTER_EOF), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa82d07a in /home/clickhouse/bin/clickhouse-server
1. DB::throwReadAfterEOF() @ 0xa83e4db in /home/clickhouse/bin/clickhouse-server
2. ? @ 0xa87c16b in /home/clickhouse/bin/clickhouse-server
3. ? @ 0x1328c4fc in /home/clickhouse/bin/clickhouse-server
4. DB::ISerialization::deserializeBinaryBulkWithMultipleStreams(COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, DB::ISerialization::DeserializeBinaryBulkSettings&, std::__1::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, COW<DB::IColumn>::immutable_ptr<DB::IColumn> > > >*) const @ 0x132536f5 in /home/clickhouse/bin/clickhouse-server
5. DB::SerializationArray::deserializeBinaryBulkWithMultipleStreams(COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, DB::ISerialization::DeserializeBinaryBulkSettings&, std::__1::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, COW<DB::IColumn>::immutable_ptr<DB::IColumn> > > >*) const @ 0x1325f4d1 in /home/clickhouse/bin/clickhouse-server
6. DB::MergeTreeReaderWide::readData(DB::NameAndTypePair const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, bool, unsigned long, unsigned long, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, COW<DB::IColumn>::immutable_ptr<DB::IColumn> > > >&, bool) @ 0x143a5f0f in /home/clickhouse/bin/clickhouse-server
7. DB::MergeTreeReaderWide::readRows(unsigned long, unsigned long, bool, unsigned long, std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >&) @ 0x143a4e8b in /home/clickhouse/bin/clickhouse-server
8. DB::MergeTreeRangeReader::DelayedStream::finalize(std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >&) @ 0x14b1fb8e in /home/clickhouse/bin/clickhouse-server
9. DB::MergeTreeRangeReader::continueReadingChain(DB::MergeTreeRangeReader::ReadResult&, unsigned long&) @ 0x14b23c79 in /home/clickhouse/bin/clickhouse-server
10. DB::MergeTreeRangeReader::read(unsigned long, std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange> >&) @ 0x14b22cd3 in /home/clickhouse/bin/clickhouse-server
11. DB::MergeTreeBaseSelectProcessor::readFromPartImpl() @ 0x14b18c08 in /home/clickhouse/bin/clickhouse-server
12. DB::MergeTreeReverseSelectProcessor::readFromPart() @ 0x14b37485 in /home/clickhouse/bin/clickhouse-server
13. DB::MergeTreeBaseSelectProcessor::generate() @ 0x14b18480 in /home/clickhouse/bin/clickhouse-server
14. DB::ISource::tryGenerate() @ 0x148414b5 in /home/clickhouse/bin/clickhouse-server
15. DB::ISource::work() @ 0x1484107a in /home/clickhouse/bin/clickhouse-server
16. DB::SourceWithProgress::work() @ 0x14a8c662 in /home/clickhouse/bin/clickhouse-server
17. DB::ExecutionThreadContext::executeTask() @ 0x14860b23 in /home/clickhouse/bin/clickhouse-server
18. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x1485539e in /home/clickhouse/bin/clickhouse-server
19. ? @ 0x14856b22 in /home/clickhouse/bin/clickhouse-server
20. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa86f4b7 in /home/clickhouse/bin/clickhouse-server
21. ? @ 0xa872ebd in /home/clickhouse/bin/clickhouse-server
22. start_thread @ 0x7dd5 in /usr/lib64/libpthread-2.17.so
23. __clone @ 0xfdead in /usr/lib64/libc-2.17.so
 (version 22.1.3.7 (official build))

**Comment by sdd1998** [comment]
sql  
SELECT uid,last_packet,ip_protocol,first_packet,src_ip,src_port,dst_ip,dst_port,tot_packets,http_xff_ip,http_user,http_status_code,http_method,http_referer FROM session WHERE (last_packet BETWEEN '2022-02-22 09:20:50' AND '2022-03-01 09:20:50') and has(protocols,'http') order by last_packet desc LIMIT 10 FORMAT TabSeparatedWithNamesAndTypes;

**Comment by sdd1998** [comment]
2022.03.01 09:57:37.993015 [ 41257 ] {} <Warning> default.session_local (ReplicatedMergeTreePartCheckThread): Checking part 457190_82_107_4
2022.03.01 09:57:37.993857 [ 41257 ] {} <Warning> default.session_local (ReplicatedMergeTreePartCheckThread): Checking data of part 457190_82_107_4.
2022.03.01 09:57:38.005506 [ 41129 ] {4bf28373-2aaf-4fae-96e5-aab662e46de7} <Error> executeQuery: Code: 32. DB::Exception: Attempt to read after eof: (while reading column http_user): (while reading from part /data0/clickhouse/01/store/b4f/b4f7cad2-943c-49b4-b8e1-44399bcc45a6/457190_82_107_4/ from mark 0 with max_rows_to_read = 8192): While executing MergeTreeReverse. (ATTEMPT_TO_READ_AFTER_EOF) (version 22.1.3.7 (official build)) (from [::1]:33412) (in query: SELECT uid,last_packet,ip_protocol,first_packet,src_ip,src_port,dst_ip,dst_port,tot_packets,http_xff_ip,http_user,http_status_code,http_method,http_referer FROM session WHERE (last_packet BETWEEN '2022-02-22 09:20:50' AND '2022-03-01 09:20:50') and has(protocols,'http') order by last_packet desc LIMIT 10 FORMAT TabSeparatedWithNamesAndTypes;), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa82d07a in /home/clickhouse/bin/clickhouse-server
1. DB::throwReadAfterEOF() @ 0xa83e4db in /home/clickhouse/bin/clickhouse-server
2. ? @ 0xa87c16b in /home/clickhouse/bin/clickhouse-server
3. ? @ 0x1328c4fc in /home/clickhouse/bin/clickhouse-server
4. DB::ISerialization::deserializeBinaryBulkWithMultipleStreams(COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, DB::ISerialization::DeserializeBinaryBulkSettings&, std::__1::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, COW<DB::IColumn>::immutable_ptr<DB::IColumn> > > >*) const @ 0x132536f5 in /home/clickhouse/bin/clickhouse-server
5. DB::SerializationArray::deserializeBinaryBulkWithMultipleStreams(COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, DB::ISerialization::DeserializeBinaryBulkSettings&, std::__1::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, COW<DB::IColumn>::immutable_ptr<DB::IColumn> > > >*) const @ 0x1325f4d1 in /home/clickhouse/bin/clickhouse-server
6. DB::MergeTreeReaderWide::readData(DB::NameAndTypePair const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, bool, unsigned long, unsigned long, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, COW<DB::IColumn>::immutable_ptr<DB::IColumn> > > >&, bool) @ 0x143a5f0f in /home/clickhouse/bin/clickhouse-server
7. DB::MergeTreeReaderWide::readRows(unsigned long, unsigned long, bool, unsigned long, std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >&) @ 0x143a4e8b in /home/clickhouse/bin/clickhouse-server
8. DB::MergeTreeRangeReader::DelayedStream::finalize(std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >&) @ 0x14b1fb8e in /home/clickhouse/bin/clickhouse-server
9. DB::MergeTreeRangeReader::continueReadingChain(DB::MergeTreeRangeReader::ReadResult&, unsigned long&) @ 0x14b23c79 in /home/clickhouse/bin/clickhouse-server
10. DB::MergeTreeRangeReader::read(unsigned long, std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange> >&) @ 0x14b22cd3 in /home/clickhouse/bin/clickhouse-server
11. DB::MergeTreeBaseSelectProcessor::readFromPartImpl() @ 0x14b18c08 in /home/clickhouse/bin/clickhouse-server
12. DB::MergeTreeReverseSelectProcessor::readFromPart() @ 0x14b37485 in /home/clickhouse/bin/clickhouse-server
13. DB::MergeTreeBaseSelectProcessor::generate() @ 0x14b18480 in /home/clickhouse/bin/clickhouse-server
14. DB::ISource::tryGenerate() @ 0x148414b5 in /home/clickhouse/bin/clickhouse-server
15. DB::ISource::work() @ 0x1484107a in /home/clickhouse/bin/clickhouse-server
16. DB::SourceWithProgress::work() @ 0x14a8c662 in /home/clickhouse/bin/clickhouse-server
17. DB::ExecutionThreadContext::executeTask() @ 0x14860b23 in /home/clickhouse/bin/clickhouse-server
18. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x1485539e in /home/clickhouse/bin/clickhouse-server
19. ? @ 0x14856b22 in /home/clickhouse/bin/clickhouse-server
20. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa86f4b7 in /home/clickhouse/bin/clickhouse-server
21. ? @ 0xa872ebd in /home/clickhouse/bin/clickhouse-server
22. start_thread @ 0x7dd5 in /usr/lib64/libpthread-2.17.so
23. __clone @ 0xfdead in /usr/lib64/libc-2.17.so

**Comment by sdd1998** [comment]
![image](https://user-images.githubusercontent.com/77827496/156090947-3fea1cf6-5bba-4340-b9d5-ddc6c33a5ed9.png)

**Comment by sdd1998** [comment]
version = 22.1.3.7

**Comment by KochetovNicolai** [comment]
It is likely the part is broken for some reason. An exception was thrown for Array column which we start reading from the very beginning. Would it be possible to send this broken part somehow to investigate the issue?

**Comment by KochetovNicolai** [comment]
The part is `/data0/clickhouse/01/store/b4f/b4f7cad2-943c-49b4-b8e1-44399bcc45a6/457190_82_107_4/`. Probably, just `http_user.*` column would be enough

**Comment by sdd1998** [comment]
[http_user.zip](https://github.com/ClickHouse/ClickHouse/files/8161138/http_user.zip)

**Comment by sdd1998** [comment]
@KochetovNicolai 
help me

**Comment by KochetovNicolai** [comment]
I have attached the file and it seem to be correct, at least I can read from it.
```
SELECT
    http_user,
    count()
FROM http_user
GROUP BY http_user

Query id: d30e28d8-8896-4a54-9740-58d3f67c4d83

┌─http_user───────┬─count()─┐
│ []              │  239999 │
│ ['itworkzhang'] │       1 │
└─────────────────┴─────────┘
```

Probably there was some bug during reading. By now, the only thing I can suggest is to update ClickHouse.

**Comment by rolinh** [comment]
I'm hitting an issue that seems to be the same as this one, both with `22.3.3.44` and `22.3.2.2`. When reverting to the previous LTS release (`21.8.15.7`), I don't hit this issue anymore.
The error message looks like this:
```
code: 32, message: Attempt to read after eof: (while reading column foo): (while reading from part /var/lib/clickhouse/store/a4d/a4db5c3c-6ffd-4071-b101-205eee45d10a/20220408_1835_1851_2/ from mark 13 with max_rows_to_read = 8192): While executing MergeTreeReverse
```
The table is using the `ReplacingMergeTree` engine and I hit this issue with queries that lookup a certain amount of data. Unfortunately, I don't have clear steps to reproduce but I hope the information I provided could help the investigation.

**Comment by tephrocactus** [comment]
I'm hitting this issue as well with 22.3.2.2. Never observed this on 21.x.

This **unstable** error may happen during MergeTreeReverse execution when I try to select most recent data which is constantly inserted (logs) using DESC ordering by Timestamp field (PK). In my case this error is also always related to a column X of type **Array(String)**, which is the only array field in a table.

If I use ASC ordering - query performs without errors.
If I don't use SELECT * or exclude column X from projection - query performs without errors.
If I stop data insertion - I can read already inserted data without issues, so data parts are not broken.

My only guess is that Clickhouse tries to read column's data file at offset which is already present in index (or .mrk file), but actual length of a file at that moment is less than expected.

**Comment by den-crane** [comment]
duplicate ? https://github.com/ClickHouse/ClickHouse/issues/34647#issuecomment-1088215628
https://github.com/ClickHouse/ClickHouse/pull/34327

**Comment by den-crane** [comment]
@tephrocactus 

>If I stop data insertion - I can read already inserted data without issues, so data parts are not broken.

CH does not expose not finished inserts to queries.
Probably the issue is related either compact parts (for test you can disable them for this table temporary) or the issue disappears after data merge (for example you insert data with empty arrays and the issue reproduce because all rows have empty array in a part, but after a merge these rows are mixed with rows other parts and the issue stops to reproduce.

**Comment by supun-io** [comment]
In my case, I got this error I had missed a column in an insert query. It's not a very descriptive error through.

**Comment by radash123** [comment]
Received exception from server (version 23.4.2):
Code: 32. DB::Exception: Received from localhost:9000. DB::Exception: Attempt to read after eof:
