### ISSUE TITLE
Aggregate data within each partition independently to made merging unnecessary

### ISSUE THREAD

**Issue by nickitat** [ClickHouse/ClickHouse#34950]
**Describe the solution you'd like**

Merging of aggregated data is fairly time consuming and may be unnecessary under some circumstances. One example is when partition keys set is a subset of group by keys set. In that case we could process each partition's data on its own thread independently and return the results immideately.
Likely this functionality should be disabled by default because how it will affect performance is havely depend on the number and the sizes of partitions involved.

**Additional context**

If injective functions were applied to partition keys the optimization is still possible.

**Comment by KochetovNicolai** [comment]
It is not always better to process partitions in parallel threads. It's unlikely that data is distributed evenly between partitions. Some common case is to partition by month and select only recent data (e.g. also for the last month) - which will use only a couple of partitions.

But it may be possible to enable only with a setting.

**Comment by nickitat** [comment]
Yeah, some reasonable amount of partitions should be envolved in the aggregation for this to work well. I'll mention that in the description.

**Comment by alexey-milovidov** [comment]
> If injective functions were applied to partition keys the optimization is still possible.

Any deterministic function will suffice.
Example:

```
CREATE ... PARTITION BY user_id % 100
SELECT ... GROUP BY user_id
```

**Comment by alexey-milovidov** [comment]
The table's ORDER BY key can also help for this purpose.
Instead of the "group by in order" pipeline, we can implement "group by with auto partitioning by ranges".
