### ISSUE TITLE
How to set 'replicated_max_parallel_fetches_for_host' in clickhouse 21.3 ?

### ISSUE THREAD

**Issue by guaiguaidashu** [ClickHouse/ClickHouse#34959]

**Comment by e-mars** [comment]
Hi @guaiguaidashu ,
this setting is for the MergeTree engine family.
The settings is set when creating a replicated table.
example:
```
CREATE TABLE db3.table3 (
  id UInt64,
  column1 String
) 
ENGINE = ReplicatedMergeTree('/clickhouse/tables/db3_table3/shard1','replica2')
ORDER BY column1
SETTINGS replicated_max_parallel_fetches_for_host = 1024
```
you can view the default values of this setting as well as other MergeTree settings here:
[settings](https://github.com/ClickHouse/ClickHouse/blob/733ed7cb5406b9089b9e1bb2accc56e74dd3c3a6/src/Storages/MergeTree/MergeTreeSettings.h#:~:text=M(UInt64%2C%20replicated_max_parallel_fetches_for_host%2C%20DEFAULT_COUNT_OF_HTTP_CONNECTIONS_PER_ENDPOINT%2C%20%22Limit%20parallel%20fetches%20from%20endpoint%20(actually%20pool%20size).%22%2C%200)%20%5C)

thanks.
