### ISSUE TITLE
build failed with gcc or clang

### ISSUE THREAD

**Issue by zhanghuajieHIT** [ClickHouse/ClickHouse#34956]
**Operating system**
Linux x86_64

**Cmake version**
cmake version 3.18.2

**Compiler name and version**
GCC 11.2.0

**Full cmake and/or ninja output**
[root@ecs-6d32 build]# cmake .. -DCMAKE_BUILD_TYPE=Release
g++ (GCC) 11.2.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

CMake Warning at cmake/tools.cmake:20 (message):
  GCC compiler is not officially supported for ClickHouse.  You should
  migrate to clang.
Call Stack (most recent call first):
  CMakeLists.txt:46 (include)

-- Using custom linker by name: gold
-- Using objcopy: /usr/local/bin/llvm-objcopy
-- HEAD's commit hash 165eeeb50d477fc2621775da320c98c87998be15
On branch v22.2.3.5-stable
Your branch is up to date with 'origin/v22.2.3.5-stable'.
-- CMAKE_BUILD_TYPE: Release
-- Default libraries: -nodefaultlibs -lgcc  -lc -lm -lrt -lpthread -ldl
-- Some symbols from glibc will be replaced for compatibility
-- Using libunwind: unwind
-- Using exception handler: unwind
-- Unit tests are enabled
-- Building for: Linux-4.18.0-147.5.1.6.h579.eulerosv2r9.x86_64 x86_64  ;
    USE_STATIC_LIBRARIES=ON
    SPLIT_SHARED=
    CCACHE=CCACHE_FOUND-NOTFOUND 
-- Adding contrib module miniselect (configuring with miniselect-cmake)
-- Adding contrib module pdqsort (configuring with pdqsort-cmake)
-- Adding contrib module sparsehash-c11 (configuring with sparsehash-c11-cmake)
-- Adding contrib module abseil-cpp (configuring with abseil-cpp-cmake)
-- Adding contrib module magic_enum (configuring with magic-enum-cmake)
-- Adding contrib module boost (configuring with boost-cmake)
-- Adding contrib module cctz (configuring with cctz-cmake)
-- Packaging with tzdata version: 2021c
-- Adding contrib module consistent-hashing (configuring with consistent-hashing)
-- Adding contrib module dragonbox (configuring with dragonbox-cmake)
-- Adding contrib module hyperscan (configuring with hyperscan-cmake)
-- Adding contrib module jemalloc (configuring with jemalloc-cmake)
-- jemalloc malloc_conf: percpu_arena:percpu,oversize_threshold:0,muzzy_decay_ms:5000,dirty_decay_ms:5000
-- Adding contrib module libcpuid (configuring with libcpuid-cmake)
-- Adding contrib module libdivide (configuring with libdivide)
-- Adding contrib module libmetrohash (configuring with libmetrohash)
-- Adding contrib module lz4 (configuring with lz4-cmake)
-- Adding contrib module murmurhash (configuring with murmurhash)
-- Adding contrib module replxx (configuring with replxx-cmake)
-- Adding contrib module unixodbc (configuring with unixodbc-cmake)
-- Adding contrib module nanodbc (configuring with nanodbc-cmake)
-- Adding contrib module capnproto (configuring with capnproto-cmake)
-- Adding contrib module yaml-cpp (configuring with yaml-cpp-cmake)
-- Adding contrib module re2 (configuring with re2-cmake)
-- Adding contrib module xz (configuring with xz-cmake)
-- Adding contrib module brotli (configuring with brotli-cmake)
-- Adding contrib module double-conversion (configuring with double-conversion-cmake)
-- Adding contrib module boringssl (configuring with boringssl-cmake)
-- Adding contrib module poco (configuring with poco-cmake)
-- Using Poco::Crypto
-- Using Poco::Data::ODBC
-- Adding contrib module croaring (configuring with croaring-cmake)
-- Adding contrib module zstd (configuring with zstd-cmake)
-- ZSTD VERSION 1.5.0
-- Adding contrib module zlib-ng (configuring with zlib-ng-cmake)
-- Adding contrib module bzip2 (configuring with bzip2-cmake)
-- Adding contrib module minizip-ng (configuring with minizip-ng-cmake)
-- Adding contrib module snappy (configuring with snappy-cmake)
-- Adding contrib module rocksdb (configuring with rocksdb-cmake)
-- Adding contrib module thrift (configuring with thrift-cmake)
-- Adding contrib module arrow (configuring with arrow-cmake)
-- CMAKE_CXX_FLAGS:  -fsized-deallocation -fcoroutines  -pipe -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -fasynchronous-unwind-tables -ffile-prefix-map=/home/code/github/clickhouse_github=. -falign-functions=32   -Wall  -w -std=c++0x -Wall -pedantic -Werror -Wextra -Werror=shadow -faligned-new -Werror=implicit-fallthrough=2 -Wunused-result -Werror=unused-result -Wunused-parameter -Werror=unused-parameter -fsigned-char
fatal: No names found, cannot describe anything.
CMake Warning at contrib/flatbuffers/CMake/Version.cmake:22 (message):
  git describe failed with exit code: 128
Call Stack (most recent call first):
  contrib/flatbuffers/CMakeLists.txt:562 (include)

-- Proceeding with version: 2.0.0.0
-- Adding contrib module avro (configuring with avro-cmake)
-- Adding contrib module protobuf (configuring with protobuf-cmake)
-- Adding contrib module openldap (configuring with openldap-cmake)
-- Adding contrib module grpc (configuring with grpc-cmake)
-- Adding contrib module msgpack-c (configuring with msgpack-c-cmake)
-- Adding contrib module cityhash102 (configuring with cityhash102)
-- Adding contrib module libfarmhash (configuring with libfarmhash)
-- Adding contrib module icu (configuring with icu-cmake)
-- Adding contrib module h3 (configuring with h3-cmake)
-- Adding contrib module mariadb-connector-c (configuring with mariadb-connector-c-cmake)
-- Adding contrib module googletest (configuring with googletest-cmake)
-- Adding contrib module llvm (configuring with llvm-cmake)
-- LLVM include Directory: /home/code/github/clickhouse_github/contrib/llvm/llvm/include;/home/code/github/clickhouse_github/build/contrib/llvm/llvm/include
-- LLVM library Directory: /home/code/github/clickhouse_github/build/contrib/llvm/llvm
-- LLVM C++ compiler flags: 
-- Native target architecture is X86
-- Threads enabled.
-- Doxygen disabled.
-- Go bindings disabled.
-- Could NOT find OCaml (missing: OCAMLFIND OCAML_VERSION OCAML_STDLIB_PATH) 
-- OCaml bindings disabled.
-- LLVM host triple: x86_64-unknown-linux-gnu
-- LLVM default target triple: x86_64-unknown-linux-gnu
-- LLVMHello ignored -- Loadable modules not supported on this platform.
-- Targeting X86
-- Targeting AArch64
-- Adding contrib module libxml2 (configuring with libxml2-cmake)
-- Adding contrib module aws;aws-c-common;aws-c-event-stream;aws-checksums (configuring with aws-s3-cmake)
-- Adding contrib module base64 (configuring with base64-cmake)
-- Adding contrib module simdjson (configuring with simdjson-cmake)
-- Adding contrib module rapidjson (configuring with rapidjson-cmake)
-- Adding contrib module fastops (configuring with fastops-cmake)
-- Adding contrib module libuv (configuring with libuv-cmake)
-- Adding contrib module AMQP-CPP (configuring with amqpcpp-cmake)
-- Adding contrib module cassandra (configuring with cassandra-cmake)
-- Adding contrib module curl (configuring with curl-cmake)
-- Adding contrib module azure (configuring with azure-cmake)
By default, if no option is selected, on POSIX, libcurl transport adapter is used.
-- Adding contrib module sentry-native (configuring with sentry-native-cmake)
-- Adding contrib module fmtlib (configuring with fmtlib-cmake)
-- Adding contrib module krb5 (configuring with krb5-cmake)
-- Adding contrib module cyrus-sasl (configuring with cyrus-sasl-cmake)
-- Adding contrib module libgsasl (configuring with libgsasl-cmake)
-- Adding contrib module librdkafka (configuring with librdkafka-cmake)
-- librdkafka with SASL support
-- librdkafka with SSL support
-- Adding contrib module libhdfs3 (configuring with libhdfs3-cmake)
-- Enable kerberos for HDFS
-- checking compiler: GCC (11.2.)
-- Checking whether strerror_r returns an int
-- Checking whether strerror_r returns an int -- yes
-- Adding contrib module hive-metastore (configuring with hive-metastore-cmake)
-- Adding contrib module cppkafka (configuring with cppkafka-cmake)
-- Adding contrib module libpqxx (configuring with libpqxx-cmake)
-- Adding contrib module libpq (configuring with libpq-cmake)
-- Adding contrib module NuRaft (configuring with nuraft-cmake)
-- Adding contrib module fast_float (configuring with fast_float-cmake)
-- Adding contrib module datasketches-cpp (configuring with datasketches-cpp-cmake)
-- Adding contrib module libstemmer_c (configuring with libstemmer-c-cmake)
-- Adding contrib module wordnet-blast (configuring with wordnet-blast-cmake)
-- Adding contrib module lemmagen-c (configuring with lemmagen-c-cmake)
-- Adding contrib module nlp-data (configuring with nlp-data-cmake)
-- Adding contrib module cld2 (configuring with cld2-cmake)
-- Adding contrib module sqlite-amalgamation (configuring with sqlite-cmake)
-- Adding contrib module s2geometry (configuring with s2geometry-cmake)
-- Performing Test SUPPORTS_CXXFLAG_frame_larger_than=65536
-- Performing Test SUPPORTS_CXXFLAG_frame_larger_than=65536 - Success
-- Performing Test SUPPORTS_CFLAG_frame_larger_than=65536
-- Performing Test SUPPORTS_CFLAG_frame_larger_than=65536 - Success
-- compiler C   = /usr/local/gcc-11.2/bin/gcc   -pipe -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -fasynchronous-unwind-tables -ffile-prefix-map=/home/code/github/clickhouse_github=. -falign-functions=32  -Wall  -Wframe-larger-than=65536 -O3 -DNDEBUG
-- compiler CXX = /usr/local/gcc-11.2/bin/g++  -fsized-deallocation -fcoroutines  -pipe -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -fasynchronous-unwind-tables -ffile-prefix-map=/home/code/github/clickhouse_github=. -falign-functions=32   -Wall  -Wextra -Wframe-larger-than=65536 -O3 -DNDEBUG
-- LINKER_FLAGS =  -fuse-ld=gold -rdynamic -no-pie -Wl,-no-pie 
-- /home/code/github/clickhouse_github/src: Have 14283 megabytes of memory.
        Limiting concurrent linkers jobs to 4 and compiler jobs to 5
-- Will build ClickHouse 22.2.3.1 revision 54459 
CMake Warning at src/Functions/CMakeLists.txt:51 (message):
  Not generating debugger info for ClickHouse functions

-- ClickHouse modes:
-- Server mode: ON
-- Client mode: ON
-- Local mode: ON
-- Benchmark mode: ON
-- Extract from config mode: ON
-- Compressor mode: ON
-- Copier mode: ON
-- Format mode: ON
-- Obfuscator mode: ON
-- ODBC bridge mode: ON
-- Library bridge mode: ON
-- ClickHouse install: ON
-- ClickHouse git-import: ON
-- ClickHouse keeper mode: ON
-- ClickHouse keeper-converter mode: ON
-- bash_completion will be written to /usr/local/share/bash-completion/completions
-- Target check already exists
-- /home/code/github/clickhouse_github/utils: Have 14277 megabytes of memory.
        Limiting concurrent linkers jobs to 4 and compiler jobs to OFF
-- Configuring done
-- Generating done
-- Build files have been written to: /home/code/github/clickhouse_github/build

**build error**
make[2]: *** No rule to make target 'contrib/protobuf-cmake/protoc', needed by 'contrib/libhdfs3-cmake/datatransfer.pb.h'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:19368: contrib/libhdfs3-cmake/CMakeFiles/_hdfs3.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by zhanghuajieHIT** [comment]
the **protoc**  cannot be generated

**Comment by KochetovNicolai** [comment]
I've tried build with g++-11, and got a different error
```
FAILED: src/CMakeFiles/clickhouse_common_io.dir/Common/clickhouse_malloc.cpp.o 
/usr/bin/ccache /usr/bin/g++-11 -DAWS_SDK_VERSION_MAJOR=1 -DAWS_SDK_VERSION_MINOR=7 -DAWS_SDK_VERSION_PATCH=231 -DBOOST_ASIO_STANDALONE=1 -DENABLE_OPENSSL_ENCRYPTION -DLZ4_DISABLE_DEPRECATE_WARNINGS=1 -DMZ_COMPAT_VERSION=110 -DPOCO_ENABLE_CPP11 -DPOCO_HAVE_FD_EPOLL -DPOCO_OS_FAMILY_UNIX -DSTD_EXCEPTION_HAS_STACK_TRACE=1 -DUNALIGNED_OK -DWITH_COVERAGE=0 -DWITH_GZFILEOP -DX86_64 -DZLIB_COMPAT -I/home/ubuntu/dev/ClickHouse/build-gcc/includes/configs -I/home/ubuntu/dev/ClickHouse/src -I/home/ubuntu/dev/ClickHouse/build-gcc/src -I/home/ubuntu/dev/ClickHouse/build-gcc/src/Core/include -I/home/ubuntu/dev/ClickHouse/base/glibc-compatibility/memcpy -I/home/ubuntu/dev/ClickHouse/contrib/jemalloc-cmake/include -I/home/ubuntu/dev/ClickHouse/base/widechar_width -I/home/ubuntu/dev/ClickHouse/base/base/.. -I/home/ubuntu/dev/ClickHouse/build-gcc/base/base/.. -I/home/ubuntu/dev/ClickHouse/contrib/cctz/include -I/home/ubuntu/dev/ClickHouse/base/pcg-random/. -I/home/ubuntu/dev/ClickHouse/contrib/miniselect/include -I/home/ubuntu/dev/ClickHouse/contrib/zstd/lib -I/home/ubuntu/dev/ClickHouse/contrib/lz4/lib -I/home/ubuntu/dev/ClickHouse/contrib/minizip-ng -I/home/ubuntu/dev/ClickHouse/contrib/minizip-ng-cmake -isystem /home/ubuntu/dev/ClickHouse/contrib/libcxx/include -isystem /home/ubuntu/dev/ClickHouse/contrib/libcxxabi/include -isystem /home/ubuntu/dev/ClickHouse/contrib/libunwind/include -isystem /home/ubuntu/dev/ClickHouse/contrib/cityhash102/include -isystem /home/ubuntu/dev/ClickHouse/contrib/boost -isystem /home/ubuntu/dev/ClickHouse/contrib/poco/Net/include -isystem /home/ubuntu/dev/ClickHouse/contrib/poco/Foundation/include -isystem /home/ubuntu/dev/ClickHouse/contrib/poco/NetSSL_OpenSSL/include -isystem /home/ubuntu/dev/ClickHouse/contrib/poco/Crypto/include -isystem /home/ubuntu/dev/ClickHouse/contrib/boringssl/include -isystem /home/ubuntu/dev/ClickHouse/contrib/poco/Util/include -isystem /home/ubuntu/dev/ClickHouse/contrib/poco/JSON/include -isystem /home/ubuntu/dev/ClickHouse/contrib/poco/XML/include -isystem /home/ubuntu/dev/ClickHouse/contrib/replxx/include -isystem /home/ubuntu/dev/ClickHouse/contrib/fmtlib-cmake/../fmtlib/include -isystem /home/ubuntu/dev/ClickHouse/contrib/magic_enum/include -isystem /home/ubuntu/dev/ClickHouse/contrib/double-conversion -isystem /home/ubuntu/dev/ClickHouse/contrib/dragonbox/include -isystem /home/ubuntu/dev/ClickHouse/contrib/re2 -isystem /home/ubuntu/dev/ClickHouse/build-gcc/contrib/re2-cmake -isystem /home/ubuntu/dev/ClickHouse/contrib/zlib-ng -isystem /home/ubuntu/dev/ClickHouse/build-gcc/contrib/zlib-ng-cmake -isystem /home/ubuntu/dev/ClickHouse/contrib/libcpuid -isystem /home/ubuntu/dev/ClickHouse/contrib/pdqsort -isystem /home/ubuntu/dev/ClickHouse/contrib/xz/src/liblzma/api -isystem /home/ubuntu/dev/ClickHouse/contrib/aws-c-common/include -isystem /home/ubuntu/dev/ClickHouse/contrib/aws-c-event-stream/include -isystem /home/ubuntu/dev/ClickHouse/contrib/aws/aws-cpp-sdk-s3/include -isystem /home/ubuntu/dev/ClickHouse/contrib/aws/aws-cpp-sdk-core/include -isystem /home/ubuntu/dev/ClickHouse/build-gcc/contrib/aws-s3-cmake/include -isystem /home/ubuntu/dev/ClickHouse/contrib/azure/sdk/core/azure-core/inc -isystem /home/ubuntu/dev/ClickHouse/contrib/azure/sdk/identity/azure-identity/inc -isystem /home/ubuntu/dev/ClickHouse/contrib/azure/sdk/storage/azure-storage-common/inc -isystem /home/ubuntu/dev/ClickHouse/contrib/azure/sdk/storage/azure-storage-blobs/inc -isystem /home/ubuntu/dev/ClickHouse/contrib/brotli/c/include -isystem /home/ubuntu/dev/ClickHouse/contrib/snappy -isystem /home/ubuntu/dev/ClickHouse/build-gcc/contrib/snappy-cmake -isystem /home/ubuntu/dev/ClickHouse/contrib/msgpack-c/include -isystem /home/ubuntu/dev/ClickHouse/contrib/fast_float/include -isystem /home/ubuntu/dev/ClickHouse/contrib/bzip2 -isystem /home/ubuntu/dev/ClickHouse/build-gcc/contrib/bzip2 -fdiagnostics-color=always -fsized-deallocation -fcoroutines  -pipe -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -fasynchronous-unwind-tables -ffile-prefix-map=/home/ubuntu/dev/ClickHouse=. -falign-functions=32   -Wall  -Wextra -Wframe-larger-than=65536 -O2 -g -DNDEBUG -O3 -g -gdwarf-4  -fno-pie   -D OS_LINUX -fno-tree-loop-distribute-patterns -Wbool-compare -Wcast-align -Wcast-qual -Wdelete-incomplete -Wdisabled-optimization -Wduplicated-cond -Wenum-compare -Winit-self -Wlogical-not-parentheses -Wlogical-op -Wmaybe-uninitialized -Wmisleading-indentation -Wmissing-include-dirs -Wnon-virtual-dtor -Wno-return-local-addr -Wodr -Wold-style-cast -Wplacement-new=2 -Wpointer-arith -Wredundant-decls -Wreorder -Wshadow -Wshift-negative-value -Wsized-deallocation -Wsizeof-array-argument -Wsizeof-pointer-memaccess -Wsuggest-override -Wswitch-bool -Wtautological-compare -Wtrampolines -Wunused -Wundef -Wvector-operation-performance -Wzero-as-null-pointer-constant -Wno-sequence-point -Wno-stringop-overflow -Wno-error=class-memaccess -Wno-error=free-nonheap-object -Wno-error=nonnull -Werror -nostdinc++ -pthread -std=gnu++20 -MD -MT src/CMakeFiles/clickhouse_common_io.dir/Common/clickhouse_malloc.cpp.o -MF src/CMakeFiles/clickhouse_common_io.dir/Common/clickhouse_malloc.cpp.o.d -o src/CMakeFiles/clickhouse_common_io.dir/Common/clickhouse_malloc.cpp.o -c /home/ubuntu/dev/ClickHouse/src/Common/clickhouse_malloc.cpp
In file included from /home/ubuntu/dev/ClickHouse/contrib/jemalloc-cmake/include/jemalloc/jemalloc.h:8,
                 from /home/ubuntu/dev/ClickHouse/src/Common/memory.h:10,
                 from /home/ubuntu/dev/ClickHouse/src/Common/clickhouse_malloc.cpp:1:
/home/ubuntu/dev/ClickHouse/contrib/jemalloc-cmake/include/jemalloc/jemalloc_rename.h:14:21: error: redundant redeclaration of ‘void* malloc(size_t)’ in same scope [-Werror=redundant-decls]
   14 | #  define je_malloc malloc
      |                     ^~~~~~
/home/ubuntu/dev/ClickHouse/contrib/jemalloc-cmake/include/jemalloc/jemalloc_protos.h:24:34: note: in expansion of macro ‘je_malloc’
   24 |     void JEMALLOC_SYS_NOTHROW   *je_malloc(size_t size)
      |                                  ^~~~~~~~~
In file included from /home/ubuntu/dev/ClickHouse/contrib/libcxx/include/stdlib.h:93,
                 from /home/ubuntu/dev/ClickHouse/contrib/libcxx/include/cstdlib:85,
                 from /home/ubuntu/dev/ClickHouse/contrib/libcxx/include/new:92,
                 from /home/ubuntu/dev/ClickHouse/src/Common/memory.h:3,
                 from /home/ubuntu/dev/ClickHouse/src/Common/clickhouse_malloc.cpp:1:
/usr/include/stdlib.h:539:14: note: previous declaration of ‘void* malloc(size_t)’
  539 | extern void *malloc (size_t __size) __THROW __attribute_malloc__
      |              ^~~~~~
In file included from /home/ubuntu/dev/ClickHouse/contrib/jemalloc-cmake/include/jemalloc/jemalloc.h:8,
                 from /home/ubuntu/dev/ClickHouse/src/Common/memory.h:10,
                 from /home/ubuntu/dev/ClickHouse/src/Common/clickhouse_malloc.cpp:1:
/home/ubuntu/dev/ClickHouse/contrib/jemalloc-cmake/include/jemalloc/jemalloc_rename.h:8:21: error: redundant redeclaration of ‘void* calloc(size_t, size_t)’ in same scope [-Werror=redundant-decls]
    8 | #  define je_calloc calloc
      |                     ^~~~~~
/home/ubuntu/dev/ClickHouse/contrib/jemalloc-cmake/include/jemalloc/jemalloc_protos.h:27:34: note: in expansion of macro ‘je_calloc’
   27 |     void JEMALLOC_SYS_NOTHROW   *je_calloc(size_t num, size_t size)
      |                                  ^~~~~~~~~
In file included from /home/ubuntu/dev/ClickHouse/contrib/libcxx/include/stdlib.h:93,
                 from /home/ubuntu/dev/ClickHouse/contrib/libcxx/include/cstdlib:85,
                 from /home/ubuntu/dev/ClickHouse/contrib/libcxx/include/new:92,
                 from /home/ubuntu/dev/ClickHouse/src/Common/memory.h:3,
                 from /home/ubuntu/dev/ClickHouse/src/Common/clickhouse_malloc.cpp:1:
/usr/include/stdlib.h:542:14: note: previous declaration of ‘void* calloc(size_t, size_t)’
  542 | extern void *calloc (size_t __nmemb, size_t __size)
      |              ^~~~~~
In file included from /home/ubuntu/dev/ClickHouse/contrib/jemalloc-cmake/include/jemalloc/jemalloc.h:8,
                 from /home/ubuntu/dev/ClickHouse/src/Common/memory.h:10,
                 from /home/ubuntu/dev/ClickHouse/src/Common/clickhouse_malloc.cpp:1:
/home/ubuntu/dev/ClickHouse/contrib/jemalloc-cmake/include/jemalloc/jemalloc_rename.h:23:29: error: redundant redeclaration of ‘int posix_memalign(void**, size_t, size_t)’ in same scope [-Werror=redundant-decls]
   23 | #  define je_posix_memalign posix_memalign
      |                             ^~~~~~~~~~~~~~
/home/ubuntu/dev/ClickHouse/contrib/jemalloc-cmake/include/jemalloc/jemalloc_protos.h:29:42: note: in expansion of macro ‘je_posix_memalign’
   29 | JEMALLOC_EXPORT int JEMALLOC_SYS_NOTHROW je_posix_memalign(
      |                                          ^~~~~~~~~~~~~~~~~
In file included from /home/ubuntu/dev/ClickHouse/contrib/libcxx/include/stdlib.h:93,
                 from /home/ubuntu/dev/ClickHouse/contrib/libcxx/include/cstdlib:85,
                 from /home/ubuntu/dev/ClickHouse/contrib/libcxx/include/new:92,
                 from /home/ubuntu/dev/ClickHouse/src/Common/memory.h:3,
                 from /home/ubuntu/dev/ClickHouse/src/Common/clickhouse_malloc.cpp:1:
/usr/include/stdlib.h:580:12: note: previous declaration of ‘int posix_memalign(void**, size_t, size_t)’
  580 | extern int posix_memalign (void **__memptr, size_t __alignment, size_t __size)
      |            ^~~~~~~~~~~~~~
In file included from /home/ubuntu/dev/ClickHouse/contrib/jemalloc-cmake/include/jemalloc/jemalloc.h:8,
                 from /home/ubuntu/dev/ClickHouse/src/Common/memory.h:10,
                 from /home/ubuntu/dev/ClickHouse/src/Common/clickhouse_malloc.cpp:1:
/home/ubuntu/dev/ClickHouse/contrib/jemalloc-cmake/include/jemalloc/jemalloc_rename.h:7:28: error: redundant redeclaration of ‘void* aligned_alloc(size_t, size_t)’ in same scope [-Werror=redundant-decls]
    7 | #  define je_aligned_alloc aligned_alloc
      |                            ^~~~~~~~~~~~~
/home/ubuntu/dev/ClickHouse/contrib/jemalloc-cmake/include/jemalloc/jemalloc_protos.h:33:34: note: in expansion of macro ‘je_aligned_alloc’
   33 |     void JEMALLOC_SYS_NOTHROW   *je_aligned_alloc(size_t alignment,
      |                                  ^~~~~~~~~~~~~~~~
In file included from /home/ubuntu/dev/ClickHouse/contrib/libcxx/include/stdlib.h:93,
                 from /home/ubuntu/dev/ClickHouse/contrib/libcxx/include/cstdlib:85,
                 from /home/ubuntu/dev/ClickHouse/contrib/libcxx/include/new:92,
                 from /home/ubuntu/dev/ClickHouse/src/Common/memory.h:3,
                 from /home/ubuntu/dev/ClickHouse/src/Common/clickhouse_malloc.cpp:1:
/usr/include/stdlib.h:586:14: note: previous declaration of ‘void* aligned_alloc(size_t, size_t)’
  586 | extern void *aligned_alloc (size_t __alignment, size_t __size)
      |              ^~~~~~~~~~~~~
In file included from /home/ubuntu/dev/ClickHouse/contrib/jemalloc-cmake/include/jemalloc/jemalloc.h:8,
                 from /home/ubuntu/dev/ClickHouse/src/Common/memory.h:10,
                 from /home/ubuntu/dev/ClickHouse/src/Common/clickhouse_malloc.cpp:1:
/home/ubuntu/dev/ClickHouse/contrib/jemalloc-cmake/include/jemalloc/jemalloc_rename.h:25:22: error: redundant redeclaration of ‘void* realloc(void*, size_t)’ in same scope [-Werror=redundant-decls]
   25 | #  define je_realloc realloc
      |                      ^~~~~~~
/home/ubuntu/dev/ClickHouse/contrib/jemalloc-cmake/include/jemalloc/jemalloc_protos.h:37:34: note: in expansion of macro ‘je_realloc’
   37 |     void JEMALLOC_SYS_NOTHROW   *je_realloc(void *ptr, size_t size)
      |                                  ^~~~~~~~~~
In file included from /home/ubuntu/dev/ClickHouse/contrib/libcxx/include/stdlib.h:93,
                 from /home/ubuntu/dev/ClickHouse/contrib/libcxx/include/cstdlib:85,
                 from /home/ubuntu/dev/ClickHouse/contrib/libcxx/include/new:92,
                 from /home/ubuntu/dev/ClickHouse/src/Common/memory.h:3,
                 from /home/ubuntu/dev/ClickHouse/src/Common/clickhouse_malloc.cpp:1:
/usr/include/stdlib.h:550:14: note: previous declaration of ‘void* realloc(void*, size_t)’
  550 | extern void *realloc (void *__ptr, size_t __size)
      |              ^~~~~~~
In file included from /home/ubuntu/dev/ClickHouse/contrib/jemalloc-cmake/include/jemalloc/jemalloc.h:8,
                 from /home/ubuntu/dev/ClickHouse/src/Common/memory.h:10,
                 from /home/ubuntu/dev/ClickHouse/src/Common/clickhouse_malloc.cpp:1:
/home/ubuntu/dev/ClickHouse/contrib/jemalloc-cmake/include/jemalloc/jemalloc_rename.h:10:19: error: redundant redeclaration of ‘void free(void*)’ in same scope [-Werror=redundant-decls]
   10 | #  define je_free free
      |                   ^~~~
/home/ubuntu/dev/ClickHouse/contrib/jemalloc-cmake/include/jemalloc/jemalloc_protos.h:39:49: note: in expansion of macro ‘je_free’
   39 | JEMALLOC_EXPORT void JEMALLOC_SYS_NOTHROW       je_free(void *ptr)
      |                                                 ^~~~~~~
In file included from /home/ubuntu/dev/ClickHouse/contrib/libcxx/include/stdlib.h:93,
                 from /home/ubuntu/dev/ClickHouse/contrib/libcxx/include/cstdlib:85,
                 from /home/ubuntu/dev/ClickHouse/contrib/libcxx/include/new:92,
                 from /home/ubuntu/dev/ClickHouse/src/Common/memory.h:3,
                 from /home/ubuntu/dev/ClickHouse/src/Common/clickhouse_malloc.cpp:1:
/usr/include/stdlib.h:565:13: note: previous declaration of ‘void free(void*)’
  565 | extern void free (void *__ptr) __THROW;
      |             ^~~~
In file included from /home/ubuntu/dev/ClickHouse/contrib/jemalloc-cmake/include/jemalloc/jemalloc.h:8,
                 from /home/ubuntu/dev/ClickHouse/src/Common/memory.h:10,
                 from /home/ubuntu/dev/ClickHouse/src/Common/clickhouse_malloc.cpp:1:
/home/ubuntu/dev/ClickHouse/contrib/jemalloc-cmake/include/jemalloc/jemalloc_rename.h:30:21: error: redundant redeclaration of ‘void* valloc(size_t)’ in same scope [-Werror=redundant-decls]
   30 | #  define je_valloc valloc
      |                     ^~~~~~
/home/ubuntu/dev/ClickHouse/contrib/jemalloc-cmake/include/jemalloc/jemalloc_protos.h:82:34: note: in expansion of macro ‘je_valloc’
   82 |     void JEMALLOC_SYS_NOTHROW   *je_valloc(size_t size) JEMALLOC_CXX_THROW
      |                                  ^~~~~~~~~
In file included from /home/ubuntu/dev/ClickHouse/contrib/libcxx/include/stdlib.h:93,
                 from /home/ubuntu/dev/ClickHouse/contrib/libcxx/include/cstdlib:85,
                 from /home/ubuntu/dev/ClickHouse/contrib/libcxx/include/new:92,
                 from /home/ubuntu/dev/ClickHouse/src/Common/memory.h:3,
                 from /home/ubuntu/dev/ClickHouse/src/Common/clickhouse_malloc.cpp:1:
/usr/include/stdlib.h:574:14: note: previous declaration of ‘void* valloc(size_t)’
  574 | extern void *valloc (size_t __size) __THROW __attribute_malloc__
      |              ^~~~~~
cc1plus: all warnings being treated as errors

```

But here probably we need to disable `redundant-decls`.

Right now we do not support g++ in ci, so it's not unusual it was broken. However, I don't think we want to fix it right now (but you can do a pr).

Just in case, check all your submodules up-to-date (`git submodule update --init --recursive`), or even build from freshly-cloned repo (with `--recursive`).

**Comment by zhanghuajieHIT** [comment]
Thanks!

I've met some problems due to compilation parameters before, such as `redundant-decls` and so on.
But, when I finished these, I still have the last one that can not  generate the protoc.

If I use the **protoc** provided by the operating system instead of being generated by compilation, it can build successfully.

And, in my env, clang with ninja also have this problem.
Maybe, you can reproduce it by removing the **protoc**.

**Comment by alexey-milovidov** [comment]
Build ClickHouse exactly as in the build log here: https://s3.amazonaws.com/clickhouse-builds/0/c48c13601dd84eee70cfd0904827ff9859076b1a/clickhouse_build_check_(actions)/report.html

Successful build is guaranteed by our CI and you can reproduce it.

**Comment by seabean1999** [comment]
> Build ClickHouse exactly as in the build log here: https://s3.amazonaws.com/clickhouse-builds/0/c48c13601dd84eee70cfd0904827ff9859076b1a/clickhouse_build_check_(actions)/report.html
> 
> Successful build is guaranteed by our CI and you can reproduce it.

Alexey, this file link was invalid.

**Comment by Felixoid** [comment]
Our reports live for a few months.

Open any master commit and search for the build report in commit statuses
