### ISSUE TITLE
Password hashing with salt for User Authentication in Clickhouse

### ISSUE THREAD

**Issue by varadarajkumar** [ClickHouse/ClickHouse#34969]
> (you don't have to strictly follow this form)

**Use case**

Clickhouse user password hash can be added with extra security for user authentication. To provide one more level security, password hash potentially, can add an extra salt entry in configuration and user table.

**Describe the solution you'd like**

while creating user, there should be some option to indicate salt to be added to password, Similarly, Create user command has option IDENTIFIED WITH to specify sha256_has or double_sha1_hash inorder to have hash password. Every user has to have unique salt key of some specified length. Clickhouse has to store the salt generated for that particular user and that can be used when authenticating the user. As system.users table is readonly data. salt can be stored in .sql file along with password under Access folder.

The OWASP best practices recommend using a hashing algorithm with implicit salting like Argon2ID, bcrypt, scrypt or PBKDF2).
i can recommend to use PBKDF2 as clickhouse is already supporting it.  PBKDF2 need to two parameters like iterations .. etc can be read from configuration file ( config.xml of clickhouse server).

**Describe alternatives you've considered**

CREATE USER [IF NOT EXISTS | OR REPLACE] name1 [ON CLUSTER cluster_name1]
        [, name2 [ON CLUSTER cluster_name2] ...]
    [NOT IDENTIFIED | IDENTIFIED {[WITH {no_password | plaintext_password | sha256_password | sha256_hash | double_sha1_password | double_sha1_hash}] BY {'password' | 'hash'}} | {WITH ldap SERVER 'server_name'} | {WITH kerberos [REALM 'realm']}]
    [HOST {LOCAL | NAME 'name' | REGEXP 'name_regexp' | IP 'address' | LIKE 'pattern'} [,...] | ANY | NONE]
    [DEFAULT ROLE role [,...]]
    [DEFAULT DATABASE database | NONE]
    [GRANTEES {user | role | ANY | NONE} [,...] [EXCEPT {user | role} [,...]]]
    [SETTINGS variable [= value] [MIN [=] min_value] [MAX [=] max_value] [READONLY | WRITABLE] | PROFILE 'profile_name'] [,...]

new command can be : 

CREATE USER [IF NOT EXISTS | OR REPLACE] name1 [ON CLUSTER cluster_name1]
        [, name2 [ON CLUSTER cluster_name2] ...]
    [NOT IDENTIFIED | IDENTIFIED {[WITH {no_password | plaintext_password | sha256_password | sha256_hash | double_sha1_password | double_sha1_hash}] BY {'password' | 'hash'}} | {WITH ldap SERVER 'server_name'} | {WITH kerberos [REALM 'realm']}]
    [HOST {LOCAL | NAME 'name' | REGEXP 'name_regexp' | IP 'address' | LIKE 'pattern'} [,...] | ANY | NONE]
    [DEFAULT ROLE role [,...]]
    [SALT ON/OFF | NONE] 
    [DEFAULT DATABASE database | NONE]
    [GRANTEES {user | role | ANY | NONE} [,...] [EXCEPT {user | role} [,...]]]
    [SETTINGS variable [= value] [MIN [=] min_value] [MAX [=] max_value] [READONLY | WRITABLE] | PROFILE 'profile_name'] [,...]

other alternative is adding keyword after IDENTIFIED WITH : 

  [NOT IDENTIFIED | IDENTIFIED {[WITH {no_password | plaintext_password | sha256_password | sha256_hash | double_sha1_password | double_sha1_hash} AND SALT] 

**Additional context**

PBKDF2(Password-Based Key Derivation Function 2) is key derivation function, clickhouse is can use this for generating password with salt.

**Comment by alexey-milovidov** [comment]
Let's implement salted password hashes.
The proposed syntax is alright.

We can use PBKDF2 or bcrypt or Argon2, etc... but it is hardly reasonable, because there are usage scenarios when password is checked on every request. Maybe it is ok if the number of iterations is specified in config and is low by default. Or if you cache credentials with successful auth in memory. Also looks strange and requires some care to implement.

**Comment by alexey-milovidov** [comment]
Could you please provide some examples from MySQL and Postgres and also cloud databases like RDS, CockroachDB, PlanetScale?

**Comment by vitlibar** [comment]
Why do you expect it will add security? I mean you're going to generate a unique salt for each user and keep it in the file where password hashes are stored. If someone steals that file he will know password hashes or password hashes with salts, and what's the difference?

**Comment by larryluogit** [comment]
@vitlibar The purpose of salt is to stop precomputation attacks or 'Dictionary Attacks' are run against hashed passwords, such as [rainbow tables](http://en.wikipedia.org/wiki/Rainbow_table). 
These attacks involve creating a database of hashes and their plaintexts, so that hashes can be searched for and immediately reversed into plaintext.
When salt is used in hashed password, the attacker has to re-code the dictionary for each individually stored password with the salt. It's computationally infeasible to do so.

**Comment by larryluogit** [comment]
Salt Password Hash has been implemented for **sha256_password** by the following PR
https://github.com/ClickHouse/ClickHouse/pull/36172
The feature is transparent to user. A FIPS compliant random generator salt password before hashing it.
