### ISSUE TITLE
show create table remote(...)

### ISSUE THREAD

**Issue by ramazanpolat** [ClickHouse/ClickHouse#34967]
We can issue SELECT, INSERT and even DESCRIBE commands on a `remote` table function. 

It would be nice to see the `CREATE TABLE` statement using `remote` table funciton

**Use case**

When transferring data from one server to another, it will be easier to table DDL with `show create table remote(...)`

**Comment by KochetovNicolai** [comment]
`remote` itself creates a temporary Distributed table which in fact don't have `CREATE TABLE` statement. In case if you want create statement for remote tables, you can read it from `system.tables`, using as well `remote` on top of the same cluster.
It can't be single `CREATE TABLE` statement for `remote` also cause we read from many tables, and they could be created differently.
