### ISSUE TITLE
SQL query parser error depending on values order

### ISSUE THREAD

**Issue by absorbb** [ClickHouse/ClickHouse#34966]
**Describe what's wrong**

Strange error:
 `Code: 62. DB::Exception: Cannot parse expression of type String here: 1.0): While executing ValuesBlockInputFormat. (SYNTAX_ERROR)`
that depends on parameters order in query or parameters values.

**Does it reproduce on recent release?**

Tested on Yandex Cloud:
Versions: 22.1.3.7, 21.12.4.1, 21.11.11.1
Reproducible on all these version

**How to reproduce**

* Which ClickHouse server version to use: 22.1.3.7 Yandex Cloud
* `CREATE TABLE` statements for all tables involved
```sql
CREATE TABLE test4
(
    `_timestamp` DateTime DEFAULT now(),
    `c` String,
    `did` String,
    `dil` Float32,
    `da` String,
    `dd` DateTime,
    `dal` String,
    `dfc` String,
    `df` String,
    `db` String
)
    ENGINE = MergeTree
        PARTITION BY toYYYYMM(_timestamp)
        ORDER BY _timestamp
        SETTINGS index_granularity = 8192;
```
* Queries to run that lead to unexpected result
```sql
INSERT INTO test4 ("_timestamp", "c", "dfc", "dal", "da", "dd", "db" , "df", "did", "dil") 
VALUES ('2022-03-01 09:28:17','','','','TEST','2022-03-11','','','',1.0);
```

**Expected behavior**

Successful insert.

**Error message and/or stacktrace**

`Code: 62. DB::Exception: Cannot parse expression of type String here: 1.0): While executing ValuesBlockInputFormat. (SYNTAX_ERROR) (version 22.1.3.7 (official build))`

**Additional context**

Making slight changes to the query may lead to successful insert. E.g.:

change parameters order (move `dil` parameter to the first place):
```sql
INSERT INTO test4 ("dil","_timestamp", "c", "dfc", "dal", "da", "dd", "db" , "df", "did")
VALUES (1.0,'2022-03-01 09:28:17','','','','TEST','2022-03-11','','','');
```
`completed in 43 ms`

or provide VALUE for `df` parameter:
```sql
INSERT INTO test4 ("_timestamp", "c", "dfc", "dal", "da", "dd", "db" , "df", "did", "dil") 
VALUES ('2022-03-01 09:28:17','','','','TEST','2022-03-11','','VALUE','',1.0);
```
`completed in 39 ms`

or `did` parameter:
```sql
INSERT INTO test4 ("_timestamp", "c", "dfc", "dal", "da", "dd", "db" , "df", "did", "dil") 
VALUES ('2022-03-01 09:28:17','','','','TEST','2022-03-11','','','VALUE',1.0);
```
`completed in 41 ms`

**Comment by absorbb** [comment]
It looks like real cause of error is short date format `2022-03-01`
But it is very hard to investigate. And what is more strange that error can be avoided with slight changes in query

**Comment by alexey-milovidov** [comment]
It's not fixed.

**Comment by alexey-milovidov** [comment]
https://github.com/ClickHouse/ClickHouse/issues/36949
