### ISSUE TITLE
Can clickhouse-copier rezone partitions?

### ISSUE THREAD

**Issue by wbxsGithub** [ClickHouse/ClickHouse#34978]
source cluster partition : '20220101'
target cluster partition : ('20220101',22)

**Comment by KochetovNicolai** [comment]
With copier you can copy data into a different table, with a different partition key. But you can't change partition "in place" for table. 
With copier, full copy of data will happen.

**Comment by wbxsGithub** [comment]
It's correct!

**Comment by wbxsGithub** [comment]
Is it possible to change the 'order by key'?

**Comment by alexey-milovidov** [comment]
Yes, both partition and sorting key can change.

**Comment by wbxsGithub** [comment]
Thanks!
