### ISSUE TITLE
Engine = Log + kafka + mat view

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#34976]
22.2.2.1.

```sql
drop table if exists test_log_mv; 
drop table if exists test_log; 
drop table if exists kafka; 

CREATE TABLE IF NOT EXISTS kafka
(
  a String
)ENGINE = Kafka()
     SETTINGS kafka_broker_list = 'kafka1:9092',
         kafka_topic_list = 'test',
         kafka_group_name = 'test',
         kafka_format = 'CSV';


create table test_log (a String) Engine=Log;

select count() from test_log;
0 rows in set. Elapsed: 0.007 sec.    ----<<<<-- before create MATERIALIZED view

create MATERIALIZED view test_log_mv to test_log as select * from kafka;


select count() from test_log;
0 rows in set. Elapsed: 4.666 sec.   ----<<<<-- after create MATERIALIZED view
```

**Comment by astudnev** [comment]
Does this concern only Log engine or Merge as well?

**Comment by astudnev** [comment]
Merge* engine does not have this problem.
Log engine has long waiting time, and sometimes respond with  error that it can't get lock

**Comment by den-crane** [comment]
@astudnev Why do you use engine = Log ? 

https://clickhouse.com/docs/en/engines/table-engines/log-family/log/

For concurrent data access, the read operations can be performed simultaneously, **while write operations block reads** and each other.

Similarly**, if writing to a table failed, the table is broken**, and reading from it returns an error. **The Log engine is appropriate for temporary data**, write-once tables, and for testing or demonstration purposes.
