### ISSUE TITLE
Confuse about the difference between background_schedule_pool_size  and background_fetches_pool_size 

### ISSUE THREAD

**Issue by Yanbuc** [ClickHouse/ClickHouse#34987]
I think ReplicatedMerge table has two type background tasks , one is merge and another is fetch parts from another replica. 
In my opinion, background_fetches_pool_size is for fetch and background_pool_size  is for merge, so i confuse why the document for clickhouse say background_schedule_pool_size is about background task for replicated task. Is there another backgraound task for replicated table ?

**Comment by KochetovNicolai** [comment]
There are fetches and merges which are background tasks. Recently there were a single pool for both type of tasks, but now we use different pools for better tuning.

**Comment by Yanbuc** [comment]
> There are fetches and merges which are background tasks. Recently there were a single pool for both type of tasks, but now we use different pools for better tuning.

I see. Thank you .
