### ISSUE TITLE
How to insert nested with flatten_nested = 0

### ISSUE THREAD

**Issue by alespour** [ClickHouse/ClickHouse#34997]
I just cannot figure out how to insert data (`INSERT INTO`) into table with `Nested` column **and** `flatten_nested = 0`. Advice much appreciated, thank you very much in advance

**Comment by den-crane** [comment]
flatten_nested impacts only on CREATE_TABLE.
After you have created table, use `DESC table` to see types. 

https://github.com/ClickHouse/ClickHouse/issues/33826
