### ISSUE TITLE
Remote disk managing tool

### ISSUE THREAD

**Issue by GrigoryPervakov** [ClickHouse/ClickHouse#34998]
Sometimes it's quite hard to debug problems with an S3 disk(in our case S3), so we want to create a tool that simplifies manipulations with it.

**Use case**

Debug and fix remote disk issues.

**Describe the solution you'd like**

We propose to implement a c++ tool that uses the IDisk interface in ClickHouse src, that distributed in ClickHouse binary like a clickhouse-client.
This tool should be able to read clickhouse-server config files to obtain disks configuration.
In the first version, it should provide a basic filesystem interface, such as **ls, mv, ln, cat**

**Describe alternatives you've considered**

We also thought about implementing such features via system tables like system.zookeeper for zookeeper do, but we think it's good for read-only operations and require a lot of work to implement a good modifying interface.

**Comment by kssenii** [comment]
1. non-interactive mode:

```
> ./clickhouse disk <disk_name> ls / cat / rm / ln / mv ...
```

2. interactive mode:

```
> ./clickhouse disk

:) show disks

disk1
...
diskn

:) use disk1
Ok.

:) cd / ls / rm / mv / cat ...

:) ls -la  -- shows local paths + metadata (like path in s3, size, ref count etc)

local_path1  remote_path1  size  ref_count  ...
local_path2  remote_path2  size  ref_count ...

```

@alesapin @alexey-milovidov ok?

**Comment by alexey-milovidov** [comment]
Ok, but I find interactive mode unneeded. Non-interactive is enough.
Also the examples lack of `--config-file` parameter.

**Comment by alexey-milovidov** [comment]
Also there are some inconsistencies in command names.

`cat` is a abbreviation of `concatenate`, but our tool will not suppport concatenation, so naming it `cat` is wrong.
The most natural name will be `read`.

But if we start to use different names for the tools, we should better use proper names for all of them:

- read
- write
- list
- move
- copy
- link
- remove

**Comment by GrigoryPervakov** [comment]
Currently we planned only non-interactive mode.
Now we are implementing syntax like:
- `clickhouse disks ls /path` is using default disk
- `clickhouse disks --disk my_dysk ls /path` global flag overrides default disk
- `clickhouse disks ls my_disk:/path` disk name present in listing path
Last example will be useful in cases like `clickhouse disks mv my_disk:/path other_disk:/otherpath` moves files between disks

**Comment by filimonov** [comment]
> Ok, but I find interactive mode unneeded. Non-interactive is enough.

traversing / debugging is handier in interactive mode (i.e. sequences like `cd /folder/; ls; cd subfolder; cat filename.txt` ). But it's not a priority for sure.

**Comment by filimonov** [comment]
BTW - maybe even create fuse driver?

**Comment by GrigoryPervakov** [comment]
Great idea, if it realy will be easy I think it should be implemented as clickhouse-disks mount --disk gfoo /path
But as a separate tool we can implement more features, like debug local cache, s3 revisions(modification history), zookeeper hardlinks on parts(created in zk by freeze table to avoid blob deletion )

**Comment by alexey-milovidov** [comment]
Please don't create a FUSE driver. Our virtual filesystem interface is extremely limited.

**Comment by alexey-milovidov** [comment]
> clickhouse disks ls my_disk:/path disk name present in listing path

This feature is also unneeded.

**Comment by alesapin** [comment]
Impl: https://github.com/ClickHouse/ClickHouse/pull/36060
