### ISSUE TITLE
Fail to kill distributed ddl 

### ISSUE THREAD

**Issue by GeraltXLi** [ClickHouse/ClickHouse#34990]
All database cannot be queried properly.
Use `show processlist`, I saw one distributed ddl exists, but I can not kill it.
Even if I restart the server, this ddl always reappears. 
How can I kill it or solve this problem.

DDL :
```sql
EXCHANGE TABLES xxx.v2  AND xxx.v1 ON CLUSTER ''xxx_cluster'
```

**Comment by e-mars** [comment]
hi @GeraltXLi ,

wasn't quite able to replicate the issue mentioned with `exchange tables` command.

could you give a bit more info on how this particular table is configured?
is it replicated?
could you get me the output of:
```
show create table <your_table>;
```

and the output of `show processlist`?
*you can edit and anonymize if needed

is the table using `ReplicatedMergeTree`? if not could you let us know what table engine is being used?

thanks.

**Comment by GeraltXLi** [comment]
Because I have temporarily solved, so now there is no live information, sorry.
I ended up changing the `distributed_ddl.path` in the configuration as a way to skip the ddl task that keeps pulling up after every reboot. 
```
Clickhouse server version: 21.2.4.6
Table engine: `ReplicatedSummingMergeTree`
```
