### ISSUE TITLE
Allow to query projection directly. 

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#35017]
**Use case**

Manually run query against specific projection. 
For https://kb.altinity.com/altinity-kb-queries-and-syntax/partial-projection-optimization/ it will allow to remove double GROUP BY from query.
Also it will allow to not run index scan against source table, which could take some time.

**Describe the solution you'd like**

```
SELECT key, sum(value) FROM database.table.projection_name GROUP BY key
```

**Comment by amosbird** [comment]
There is a setting `force_data_skipping_indices` which enforces what skip indices should be used. We can add `force_projections`

**Comment by UnamedRus** [comment]
It's not only about forcing of using specific projection, but also about ability to read projection without using GROUP BY in inner query.

**Comment by aderouineau** [comment]
@alexey-milovidov What is the reason for wontfix?
