### ISSUE TITLE
how to clickhouse dump all tables schema from database ?

### ISSUE THREAD

**Issue by rfyiamcool** [ClickHouse/ClickHouse#35012]
same as `mysqldump -u user -h localhost --no-data -p database > database.sql`, thank u !!!

**Comment by rkozlo** [comment]
You can take this from metadata. In /var/lib/clickhouse/metadata

**Comment by abraithwaite** [comment]
For folks arriving to this issue from google: there's now a feature request for this here: 

https://github.com/ClickHouse/ClickHouse/issues/60681

For a quickfix before that gets completed, check this out, I've written this small utility program if it's helpful:

https://github.com/runreveal/chdump
