### ISSUE TITLE
use about Parallel reading from replicas

### ISSUE THREAD

**Issue by LvLiangLiang-dev** [ClickHouse/ClickHouse#35013]
hi, i want use the feature about Parallel reading from replicas,But the effect is different from what I thought.
1：i create ReplicatedMergeTree
<img width="1267" alt="image" src="https://user-images.githubusercontent.com/19455764/156527552-c8b5d2bd-33f7-40bb-80c2-887cfcad8e3b.png">
2：i insert 0.1b rows data
<img width="565" alt="image" src="https://user-images.githubusercontent.com/19455764/156527770-a69a82e7-408a-485d-b821-8f6bb632bfbc.png">

3： open set 
<img width="611" alt="image" src="https://user-images.githubusercontent.com/19455764/156527687-59386320-215f-4644-b340-f8976977b922.png">
4：select with parallel
Parallel reading is not implemented. The log shows that only the replica on the left has read all data, and the replica on the right has no log to show reading
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/19455764/156527993-9ebf73b1-765b-4840-b66e-63150b26ec67.png">
5：Is there something wrong with my understanding or use？
tks

**Comment by Faynebupt** [comment]
version :
<img width="505" alt="image" src="https://user-images.githubusercontent.com/19455764/156528251-f30ddf97-cf50-4a3f-a3dd-00db8759ad6c.png">

**Comment by Faynebupt** [comment]
I also tried distributed tables with the following two replica tables,but  behave the same

**Comment by yej2021** [comment]
Which of the parameters must configured to take effect?@LvLiangLiang-dev

**Comment by LvLiangLiang-dev** [comment]
> Which of the parameters must configured to take effect?@LvLiangLiang-dev

set allow_experimental_parallel_reading_from_replicas=true
set use_hedged_requests =false
set max_parallel_replicas=2(your numbers)

by my side

**Comment by Anton-Rodionov** [comment]
@LvLiangLiang-dev apparently you need to read through a distributed table that points to your shard with N replicas, then it works. All settings that you listed are required, too.
```
create table rt1_distributed as rt1 engine = Distributed(<your cluster name with 1 shard N replicas>, default, rt1)
select count() from rt1_distributed settings allow_experimental_parallel_reading_from_replicas=1, max_parallel_replicas=2, use_hedged_requests=0
```
