### ISSUE TITLE
enumerateStreams result of data type `LowCardinality(Nullable(String))` changed after serialization refactoring

### ISSUE THREAD

**Issue by taiyang-li** [ClickHouse/ClickHouse#35016]
**Describe the issue** 
enumerateStreams result of data type `LowCardinality(Nullable(String))` changed after this refactoring: https://github.com/ClickHouse/ClickHouse/pull/21562/files.

It may bring some critical issues when upgrade clickhouse version: 
- When replica with old version fetch part from another replica with new version, exception will be thrown because some metadata files are missing. 
- When replica with old version upgrade to new version in place, local data parts may not be loading correctly(I guess). 

1. Create table and insert some data both in elder versions before above pr for example 21.3 and 21.10
``` sql
CREATE TABLE default.test_lcn
(
    `events_event_info_ownerStatus` LowCardinality(Nullable(String)),
    `itime` DateTime,
    `day` Date DEFAULT toDate(itime)
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(day)
ORDER BY itime
TTL day + toIntervalDay(15)
SETTINGS min_bytes_for_wide_part = 0, min_rows_for_wide_part = 0

insert into test_lcn select null, now(), today() from system.numbers limit 1000000
```

3. View files under part directory of above table.

In 21.3 version:  
``` bash 
$ sudo ls -l ./data/default/test_lcn/20220303_1_1_0 | grep events_event_info_ownerStatus 
-rw-r----- 1 clickhouse clickhouse  4715 Mar  3 18:48 events_event_info_ownerStatus.bin
-rw-r----- 1 clickhouse clickhouse    41 Mar  3 18:48 events_event_info_ownerStatus.dict.bin
-rw-r----- 1 clickhouse clickhouse  2976 Mar  3 18:48 events_event_info_ownerStatus.dict.mrk2
-rw-r----- 1 clickhouse clickhouse     0 Mar  3 18:48 events_event_info_ownerStatus.dict.null.bin
-rw-r----- 1 clickhouse clickhouse  2976 Mar  3 18:48 events_event_info_ownerStatus.dict.null.mrk2
-rw-r----- 1 clickhouse clickhouse  2976 Mar  3 18:48 events_event_info_ownerStatus.mrk2
```  
In 21.10 version, files with suffix `.null.bin` and `.null.mark2` are absent. 
``` bash
$ sudo ls -l ./data/default/test_lcn/20220303_3_3_0 | grep events_event_info_ownerStatus 
-rw-r----- 1 clickhouse clickhouse  4715 Mar  3 18:05 events_event_info_ownerStatus.bin
-rw-r----- 1 clickhouse clickhouse    41 Mar  3 18:05 events_event_info_ownerStatus.dict.bin
-rw-r----- 1 clickhouse clickhouse  2976 Mar  3 18:05 events_event_info_ownerStatus.dict.mrk2
-rw-r----- 1 clickhouse clickhouse  2976 Mar  3 18:05 events_event_info_ownerStatus.mrk2
```

**Additional context**
I compare codes of `DataTypeLowCardinality` and `SerializationLowCardinality.cpp` before and after above pr: 

Consider calling `enumerateStreams` with type `LowCardinality(Nullable(String))`

Before: the nested `enumerateStreams` is called  on a nullable type, that is `Nullable(String)`
https://github.com/ClickHouse/ClickHouse/blob/39465b3fb6f158fae0a795608db976d275663310/src/DataTypes/DataTypeLowCardinality.cpp#L41-L60

After:   the nested `enumerateStreams` is called on a non-null type, because `Nullable` is remove in `SerializationLowCardinality::SerializationLowCardinality`
https://github.com/ClickHouse/ClickHouse/blob/eb68c21152093925bb35991b0c3b65229acab797/src/DataTypes/Serializations/SerializationLowCardinality.cpp#L37-L68

**Comment by KochetovNicolai** [comment]
Missing files `.null.bin` and `.null.mrk2` should not affect reading. Those files were created by mistake, and always empty. We newer read it's content. The only possible issue can be with inconsistent hash in zk (did not actually check) - in which case result of a merge could be rejected (and fetched). I suppose, it's acceptable.

@CurtizJ what do you think?

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/26556
