### ISSUE TITLE
uniqHLL12/uniqExact/uniq is unreasonably slow

### ISSUE THREAD

**Issue by xiaobingxia** [ClickHouse/ClickHouse#35023]
Hello, we have following sql statement:
SELECT
        DATE,
        COL_1,
        COL_2,
        COL_3,
        COL_4,
        COL_5,
        COL_6,
        sumMerge(COL_7) AS DOLLAR_VOLUME,
        uniqHLL12Merge(COL_8_ID) AS CUSTOMER_CNT,
        uniqHLL12Merge(COL_9_ID) AS DELIVERY_CNT
    FROM "TABLE"
    WHERE (DATE >= '2020-02-01') AND (DATE < '2022-02-01')
    GROUP BY
        DATE,
        COL_1,
        COL_2,
        COL_3,
        COL_4,
        COL_5,
        COL_6

"TABLE" has 73m rows of data.
But the above query would take 87 seconds.
`46394106 rows in set. Elapsed: 87.137 sec. Processed 46.39 million rows, 31.59 GB (532.43 thousand rows/s., 362.59 MB/s.)`

If I remove the uniqHLL12Merge part, and only run following sql statement:
SELECT
        DATE,
        COL_1,
        COL_2,
        COL_3,
        COL_4,
        COL_5,
        COL_6,
        sumMerge(COL_7) AS DOLLAR_VOLUME
    FROM "TABLE"
    WHERE (DATE >= '2020-02-01') AND (DATE < '2022-02-01')
    GROUP BY
        DATE,
        COL_1,
        COL_2,
        COL_3,
        COL_4,
        COL_5,
        COL_6

It takes only 7 seconds.
`46394106 rows in set. Elapsed: 7.294 sec. Processed 46.39 million rows, 7.17 GB (6.36 million rows/s., 982.80 MB/s.)`

May I know why is that happening? and also anyway to speed up the performance?
Thanks!

version:
`ClickHouse client version 21.12.2.17 (official build).`

table setup:
CREATE TABLE "TABLE" ON CLUSTER distributed_shards (
    DATE                          Date32,
    COL_1               Decimal(18, 0),
    COL_2                    String,
    COL_3                        String,
    COL_4                String,
    COL_5                      String,
    COL_6                  String,
    COL_7                 AggregateFunction(sum, Nullable(Decimal(38, 10))),
    COL_8_ID                  AggregateFunction(uniqHLL12, Nullable(Decimal(38, 0))),
    COL_9_ID                  AggregateFunction(uniqHLL12, Nullable(Decimal(38, 0)))
) ENGINE=AggregatingMergeTree()
PARTITION BY toYYYYMM(DATE)
ORDER BY (COL_1, COL_2, COL_3, COL_4, COL_5, COL_6, COL_7);
--ORDER BY key sequence is sorted by cardinality (low -> high)

Expectation: <5 seconds

**Comment by den-crane** [comment]
That is expected. uniq....States are huge. Clickhouse spends a lot of resources on their processing.

Elapsed: 87.137 sec.  ... 31.59 GB 
Elapsed: 7.294 sec. .... 7.17 GB

**Comment by xiaobingxia** [comment]
@den-crane  thanks for replying. I have a further question, from another thread, I noticed that: "merge" process is not parallel, that's why it is slow. That thread is 2019, may I know whether the merge process is fully parallel at the moment?

Also I want to know if there is any walk around to speed up performance. Really appreciate it. (Could you please re-open the ticket? since I have above further questions, thanks again)

**Comment by xiaobingxia** [comment]
@den-crane also I have another question, I was using uniqHLL12 aggregate function above, which is using HyperLogLog. I'm very new to HyperLogLog, but per https://en.wikipedia.org/wiki/HyperLogLog#:~:text=HyperLogLog%20is%20an%20algorithm%20for,for%20very%20large%20data%20sets.
It only takes very few memory, so I'm assuming using uniqHLL12 should be fast? But per my experimentation, the latency doesn't differ too much between uniqHLL12, and uniq. Is it expected?

Thanks again!

**Comment by den-crane** [comment]
Also `settings index_granularity=256`

```
create table z(d Date, z String, u String) Engine=Null;
CREATE MATERIALIZED VIEW mvz ENGINE = AggregatingMergeTree order by (z,d)  settings index_granularity=256
as select d, z,
          uniqState(u) as uniqs,
          uniqHLL12State(u) as hll12s
from z 
group by z,d;


insert into z select today()-1, toString(rand()%1000),concat('usr',toString(number)) from numbers(100000000);
insert into z select today()-2, toString(rand()%1000),concat('usr',toString(number)) from numbers(100000000);
insert into z select today()-3, toString(rand()%1000),concat('usr',toString(number)) from numbers(100000000);


set max_threads=16;
select d,uniqMerge(uniqs) as unique from mvz prewhere z='555' group by d order by d;
┌──────────d─┬─unique─┐
│ 2022-02-28 │  99791 │
│ 2022-03-01 │ 100484 │
│ 2022-03-02 │ 100490 │
└────────────┴────────┘
3 rows in set. Elapsed: 1.125 sec. Processed 4.35 thousand rows, 582.71 KB (3.87 thousand rows/s., 518.13 KB/s.)


set max_threads=1;
select d,uniqMerge(uniqs) as unique from mvz prewhere z='555' group by d order by d;
┌──────────d─┬─unique─┐
│ 2022-02-28 │  99791 │
│ 2022-03-01 │ 100484 │
│ 2022-03-02 │ 100490 │
└────────────┴────────┘
3 rows in set. Elapsed: 1.980 sec. Processed 1.79 thousand rows, 239.94 KB (904.91 rows/s., 121.16 KB/s.)


set max_threads=16;
select d,uniqHLL12Merge(hll12s) as unique from mvz prewhere z='555' group by d order by d;
┌──────────d─┬─unique─┐
│ 2022-02-28 │  97814 │
│ 2022-03-01 │  97393 │
│ 2022-03-02 │  99502 │
└────────────┴────────┘
3 rows in set. Elapsed: 0.026 sec. Processed 1.79 thousand rows, 469.32 KB (69.73 thousand rows/s., 18.26 MB/s.)


set max_threads=1;
select d,uniqHLL12Merge(hll12s) as unique from mvz prewhere z='555' group by d order by d;
┌──────────d─┬─unique─┐
│ 2022-02-28 │  97814 │
│ 2022-03-01 │  97393 │
│ 2022-03-02 │  99502 │
└────────────┴────────┘
3 rows in set. Elapsed: 0.014 sec. Processed 1.79 thousand rows, 469.32 KB (127.55 thousand rows/s., 33.40 MB/s.)
```

**Comment by xiaobingxia** [comment]
@den-crane that's amazing! really appreciate your detailed response!
