### ISSUE TITLE
Using map in sorting key

### ISSUE THREAD

**Issue by alespour** [ClickHouse/ClickHouse#35022]
I'm trying to use map in sorting key (together with datetime). If I am reading `PLAN EXPLAIN` correctly, when I query without time, I can see the whole primary key is used. However, when I add time condition to query, only datetime key of the primary is used and query is several time slower. Is there a way to rephrase the query to get better PK utilization? Thank you.

```sql
CREATE TABLE ts
(
    `time` DateTime,
    `tags` Map(LowCardinality(String), String),
    `value` Int64
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(time)
ORDER BY (tags, time)

INSERT INTO ts (time, tags, value) VALUES (now(),{'hostname':'host_1'}, 1234)

SELECT time,tags,value FROM ts WHERE tags['hostname']='host_1' // indexes used: MinMax, Partition, PrimaryKey
SELECT time,tags,value FROM ts WHERE tags['hostname']='host_1' AND time < now() //// indexes used: MinMax, Partition, PrimaryKey / [Keys: "time"]
```

**Comment by alexey-milovidov** [comment]
Usage of Map in sorting key does not make sense.
Data will be sorted by the array of key-value pairs in lexicographical order, but it does not allow to efficiently locate the data with specific map keys or values.

**Comment by alanhe** [comment]
I understand users should not make assumptions on the order of map keys. But I find sorting the keys before insertion helps to improve compression ratio.

Here's my test:
1. Create two tables:
```SQL
CREATE TABLE mytest2
(
    `id` Map(String, String)
)
ENGINE = MergeTree
ORDER BY tuple();

CREATE TABLE mytest3
(
    `id` Map(String, String)
)
ENGINE = MergeTree
ORDER BY tuple();
```
2. Insert some mock data. For table `mytest2`, the keys are in arbitrary order; for table `mytest3`, the keys are sorted before insertion. Here're the data distributions:
```plain
# Run select id, count() from mytest2 group by id;
# mytest2:
┌─id────────────────────┬─count()─┐
│ {'k2':'v2','k1':'v1'} │   12555 │
│ {'k1':'v1','k2':'v2'} │   87445 │
└───────────────────────┴─────────┘

# mytest3:
┌─id────────────────────┬─count()─┐
│ {'k1':'v1','k2':'v2'} │  100000 │
└───────────────────────┴─────────┘
```

3. Count the table size:
```
SELECT
    database,
    table,
    formatReadableSize(sum(data_compressed_bytes) AS size) AS compressed,
    formatReadableSize(sum(data_uncompressed_bytes) AS usize) AS uncompressed,
    round(usize / size, 2) AS compr_rate,
    sum(rows) AS rows,
    count() AS part_count
FROM system.parts
WHERE (active = 1) AND (table in ('mytest2', 'mytest3'))
GROUP BY
    database,
    table
ORDER BY size DESC;

┌─table───┬─compressed─┬─uncompressed─┬─compr_rate─┬───rows─┬─part_count─┐
│ mytest2 │ 142.84 KiB │ 1.91 MiB     │      13.67 │ 100000 │          1 │
│ mytest3 │ 8.30 KiB   │ 1.91 MiB     │     235.35 │ 100000 │          1 │
└─────────┴────────────┴──────────────┴────────────┴────────┴────────────┘
```

The ClickHouse version is 22.7.3.5. From my test, `Map(String, String)` has better compression ratio when keys are sorted before insertion.

I wonder,
1. Is this the right direction to optimize for the space taken of a Map column, or should I use arrays in this case?
2. Are there any benchmarks on the Map v.s. Array query performance comparison?

**Comment by alexey-milovidov** [comment]
> 1. Is this the right direction to optimize for the space taken of a Map column, or should I use arrays in this case?

Yes, it is reasonable to put columns in the ORDER BY for improving the compression ratio. This key will be useless for data indexing (filtering by index) but will improve the performance due to better compression and data locality.

> 2. Are there any benchmarks on the Map v.s. Array query performance comparison?

No. I expect there will be no performance difference as the Map type is using a pair of Arrays under the hood.
