### ISSUE TITLE
./contrib/libcxx/include/atomic:876: error: undefined reference to '__aarch64_ldadd8_relax'

### ISSUE THREAD

**Issue by huxiangyang2018** [ClickHouse/ClickHouse#35040]
When I compile clickhouse on the ARM machine，the command is as follows:
    cmake -DENABLE_TCMALLOC=OFF -DENABLE_JEMALLOC=OFF  -DCMAKE_INSTALL_PREFIX=/usr/local/clickhouse ../
    ninja -j16
I have encountered an error  as follows：
[3604/8498] Building CXX object contrib/icu-cmake/CMakeFiles/_icui18n.dir/__/icu/icu4c/source/i18n/chnsecal.cpp.o
/home/huxiangyang/ClickHouse/contrib/icu/icu4c/source/i18n/chnsecal.cpp: In member function ‘virtual int32_t icu_66::ChineseCalendar::newMoonNear(double, UBool) const’:
/home/huxiangyang/ClickHouse/contrib/icu/icu4c/source/i18n/chnsecal.cpp:574:84: note: parameter passing for argument of type ‘icu_66::CalendarAstronomer::MoonAge’ when C++17 is enabled changed to m
atch C++14 in GCC 10.1
  574 |     UDate newMoon = gChineseCalendarAstro->getMoonTime(CalendarAstronomer::NEW_MOON(), after);
      |                                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
[3663/8498] Linking CXX executable contrib/protobuf-cmake/protoc
FAILED: contrib/protobuf-cmake/protoc
: && /usr/lib64/ccache/c++ -fdiagnostics-color=always -fsized-deallocation -fcoroutines  -pipe -march=armv8-a+crc -fasynchronous-unwind-tables -ffile-prefix-map=/home/huxiangyang/ClickHouse=. -fali
gn-functions=32   -Wall  -w -O2 -g -DNDEBUG -O3 -g -gdwarf-4 -fuse-ld=gold -rdynamic    -Wl,--no-undefined contrib/protobuf-cmake/CMakeFiles/protoc.dir/__/protobuf/src/google/protobuf/compiler/main
.cc.o -o contrib/protobuf-cmake/protoc -L/usr/lib/gcc/aarch64-unknown-linux-gnu/8.3.0 contrib/protobuf-cmake/lib_libprotoc.a  contrib/protobuf-cmake/lib_libprotobuf.a  -lpthread  contrib/zlib-ng-cm
ake/lib_zlib.a  -Wl,--start-group  base/glibc-compatibility/libglibc-compatibility.a  contrib/libcxx-cmake/libcxx.a  contrib/libcxxabi-cmake/libcxxabi.a  contrib/libunwind-cmake/libunwind.a  -Wl,--
end-group  -nodefaultlibs -lgcc  -lc -lm -lrt -lpthread -ldl && :
./contrib/libcxx/include/atomic:876: error: undefined reference to '__aarch64_ldadd8_relax'
./contrib/libcxx/include/atomic:876: error: undefined reference to '__aarch64_ldadd8_relax'
./contrib/libcxx/include/atomic:876: error: undefined reference to '__aarch64_ldadd8_relax'
./contrib/libcxx/include/atomic:876: error: undefined reference to '__aarch64_ldadd8_relax'
./contrib/libcxx/include/atomic:845: error: undefined reference to '__aarch64_cas8_rel'
./contrib/libcxx/include/atomic:876: error: undefined reference to '__aarch64_ldadd4_acq_rel'
./contrib/libcxx/include/atomic:892: error: undefined reference to '__aarch64_ldadd4_acq_rel'
./contrib/libcxx/src/include/atomic_support.h:82: error: undefined reference to '__aarch64_ldadd4_acq_rel'
./contrib/libcxx/include/memory:2419: error: undefined reference to '__aarch64_ldadd8_acq_rel'
./contrib/libcxx/include/memory:2419: error: undefined reference to '__aarch64_ldadd8_acq_rel'
./contrib/libcxx/include/memory:2419: error: undefined reference to '__aarch64_ldadd8_acq_rel'
./contrib/libcxx/include/memory:2419: error: undefined reference to '__aarch64_ldadd8_acq_rel'
./contrib/libcxx/src/include/atomic_support.h:100: error: undefined reference to '__aarch64_cas8_acq_rel'
./contrib/libcxx/src/support/runtime/../../include/atomic_support.h:82: error: undefined reference to '__aarch64_ldadd4_acq_rel'
./contrib/libcxxabi/src/include/atomic_support.h:94: error: undefined reference to '__aarch64_swp8_acq_rel'
./contrib/libcxxabi/src/include/atomic_support.h:94: error: undefined reference to '__aarch64_swp8_acq_rel'
./contrib/libcxxabi/src/include/atomic_support.h:94: error: undefined reference to '__aarch64_swp8_acq_rel'
./contrib/libunwind/src/DwarfParser.hpp:74: error: undefined reference to '__aarch64_cas8_acq_rel'
./contrib/libunwind/src/DwarfParser.hpp:74: error: undefined reference to '__aarch64_cas8_acq_rel'
./contrib/libunwind/src/DwarfParser.hpp:74: error: undefined reference to '__aarch64_cas8_acq_rel'
collect2: error: ld returned 1 exit status
[3728/8498] Building CXX object contrib/grpc/CMakeFiles/grpc.dir/src/core/lib/transport/static_metadata.cc.o
ninja: build stopped: subcommand failed.
How can I fix it?

**Comment by huxiangyang2018** [comment]
I have modified parameterss of cmake , now I got a new trouble.
my parameters : cmake -DENABLE_TCMALLOC=ON -DENABLE_JEMALLOC=OFF  -DCMAKE_CXX_FLAGS="-Wno-pessimizing-move -Wno-redundant-move "  DCMAKE_INSTALL_PREFIX=/usr/local/clickhouse ../


ClickHouse/src/Formats/MsgPackExtensionTypes.h:8:5: error: declaration of ‘UUID’ shadows a global declaration [-Werror=shadow]

ClickHouse/src/Processors/Transforms/MergingAggregatedTransform.cpp:52:27: error: unused variable ‘in_order_info’ [-Werror=unused-variable]
   52 |     else if (const auto * in_order_info = typeid_cast<const ChunkInfoWithAllocatedBytes *>(info.get()))
      |                           ^~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
[7325/8275] Building CXX object 

src/CMakeFiles/dbms.dir/Processors/Transforms/MergingAggregatedMemoryEfficientTransform.cpp.o
FAILED: src/CMakeFiles/dbms.dir/Processors/Transforms/MergingAggregatedMemoryEfficientTransform.cpp.o
src/Processors/Transforms/MergingAggregatedMemoryEfficientTransform.cpp:269:27: error: unused variable ‘in_order_info’ [-Werror=unused-variable]
  269 |     else if (const auto * in_order_info = typeid_cast<const ChunkInfoWithAllocatedBytes *>(info.get()))
      |                           ^~~~~~~~~~~~~


ClickHouse/src/Processors/Transforms/MergingAggregatedMemoryEfficientTransform.cpp:337:31: error: unused variable ‘in_order_info’ [-Werror=unused-variable]
  337 |         else if (const auto * in_order_info = typeid_cast<const ChunkInfoWithAllocatedBytes *>(cur_info.get()))
      |                               ^~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
[7344/8275] Building CXX object src/CMakeFiles/dbms.dir/Storages/StorageReplicatedMergeTree.cpp.o
FAILED: src/CMakeFiles/dbms.dir/Storages/StorageReplicatedMergeTree.cpp.o

**Comment by huxiangyang2018** [comment]
comment  cmake/warnings.cmake： add_cxx_compile_options(-Wunused)   and  add_cxx_compile_options(-Wshadow).

**Comment by alexey-milovidov** [comment]
You should not use gcc. Only clang.
