### ISSUE TITLE
Clickhouse bulk load problem

### ISSUE THREAD

**Issue by BenJFan** [ClickHouse/ClickHouse#35042]
I want use clickhouse-local generate clickhouse file, and send file to clickhouse server. Then attach the part. This logic will run in spark cluster. So we can generate and send files incrementally. Clickhouse will auto merge file. But there have a problem, when clickhouse node number up to 100, I hope clickhouse have port to received this file, not use linux scp,rsync etc command.

This is ours plan: https://github.com/apache/incubator-seatunnel/issues/1382

Any can worked method in clickhouse side?

**Comment by den-crane** [comment]
>I hope clickhouse have port to received this file, not use linux scp,rsync etc command.

There is no such feature.

**Comment by BenJFan** [comment]
> > I hope clickhouse have port to received this file, not use linux scp,rsync etc command.
> 
> There is no such feature.

Any other method in clickhouse side can make this work?
