### ISSUE TITLE
Arm64  docker clickhouse-server RES unnormal

### ISSUE THREAD

**Issue by Hillstone4Ever** [ClickHouse/ClickHouse#35043]
i am using  docker image "altinity/clickhouse-server:21.12.3.32.altinitydev " for arm64 architecture .
the clickhouse-server function is ok . but the  clickhouse-server`s RES is very high.
on virtual machine almost 2G RES (4 CPU Core)
on real machine almost 20G RES （128 CPU Core）
did anyone meet this situation ?

**Comment by den-crane** [comment]
>on virtual machine almost 2G RES (4 CPU Core)
>on real machine almost 20G RES （128 CPU Core）

The same application? 
The same amount of data?
The same number of queries?

**Comment by Hillstone4Ever** [comment]
> 

just start the container with its ‘entrypoint.sh’ , the clickhouse-server  RES is very high。

**Comment by alexey-milovidov** [comment]
Version 21.12 is not supported anymore.

**Comment by alexey-milovidov** [comment]
We give no guarantee about "altinitydev" stuff. It is maintained by 3rd-party and we don't control their build process.
