### ISSUE TITLE
The get started page not found.

### ISSUE THREAD

**Issue by ucasfl** [ClickHouse/ClickHouse#35069]
![image](https://user-images.githubusercontent.com/22127746/156869336-7edc9f72-e0d0-4383-b214-f1685480c708.png)

**Comment by alexey-milovidov** [comment]
Thank you! The URL is:
https://clickhouse.com/learn/learn/lessons/gettingstarted/

I will get @rfraposa to know.

**Comment by rfraposa** [comment]
Thanks for finding this! It's fixed
