### ISSUE TITLE
SELECT greatest(0., (sum(0) / 0)) differs in result

### ISSUE THREAD

**Issue by LIR-56** [ClickHouse/ClickHouse#35074]
**Describe the unexpected behaviour**
`SELECT greatest(0., (sum(0) / 0)) `
or
`SELECT greatest(0., (sum(0) / nan))`
results in nan firstly, but after several tries changes to 0.

**How to reproduce**
* version - 21.12.3.32
* From console clickhouse-client

[example.txt](https://github.com/ClickHouse/ClickHouse/files/8191043/example.txt)
just run `SELECT greatest(0., (sum(0) / 0))`  several times - results changes from nan to 0;

**Expected behavior**
`SELECT greatest(0., (sum(0) / 0))` always returns nan;

**Comment by alexey-milovidov** [comment]
Comparison between 0 and nan has implementation specific behavior and different internal algorithms can have different behavior for this case. ClickHouse is switching between different algorithms internally due to JIT compilation.
