### ISSUE TITLE
`filesystemAvailable` and similar functions should take optional argument with disk name.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#35076]
When disk name is not specified, it should use the default disk.
They should return max UInt64 for "infinite" virtual filesystems.

**Use case**

ClickHouse cloud.

**Comment by ucasfl** [comment]
Since we should get the space info by Disk, maybe it's better to change and rename these functions to:
`diskTotalSpace`, `diskAvailableSpace` and `diskUnreservedSpace`?

**Comment by alexey-milovidov** [comment]
`filesystem` is better.

**Comment by ucasfl** [comment]
> `filesystem` is better.
fi
OK, but former functions are `filesystemCapacity`, `filesystemFree` and `filesystemAvailable`, maybe we should change `filesystemFree` to `filesystemUnreserved`?
