### ISSUE TITLE
Release 22.3 LTS checklist

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#35078]
Please list here all the issues that must be fixed before the next release in March 2022.
This release is going to have Long Term Support.
Release is scheduled for mid-March.

**Comment by gauravphoenix** [comment]
https://github.com/ClickHouse/ClickHouse/issues/35192

**Comment by KANLON** [comment]
https://github.com/ClickHouse/ClickHouse/issues/5329

this issues hope support .  I think this is important and a lot of people have this issues！

**Comment by alexey-milovidov** [comment]
@gauravphoenix we will try to address it before the release.

@KANLON this performance optimization is not ready, so it cannot be in version 22.3.

**Comment by aderouineau** [comment]
@alexey-milovidov since I am able to reproduce #34759 (I provided an example in the ticket) maybe it should be part of the list?

**Comment by alexey-milovidov** [comment]
@aderouineau Ok. This is not blocking the release, because it is a safe (logical) race condition and only related to projections and CHECK TABLE. The fix can be backported to 22.3 when it will be available.

**Comment by alexey-milovidov** [comment]
Release is ready.
