### ISSUE TITLE
If `clickhouse-client` is run with interactive password prompt and if connection is reestablished, it asks for password again and shows misleasing message.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#35077]
```
Password for user (default): 
Connecting to ... as user default.
Exception on client:
Code: 36. DB::Exception: Parameters 'default_database', 'user' and 'password' must not contain ASCII control characters. (BAD_ARGUMENTS)
```

Even if the password is correct.

**Comment by davenger** [comment]
@alexey-milovidov are there any specifics to the configuration?
I wasn't able to reproduce this behavior neither with clickhouse-server/client binaries built from current master (version 22.4.1 revision 54455) nor with the binaries installed from ubuntu packages (version 18.16.1). I connected with `clickhouse-client --ask-password` and tried killing and restarting the server, bringing network interface down and then up.

**Comment by alexey-milovidov** [comment]
I also cannot reproduce. Looks like there is something special with my setup.

PS. Keeping password in memory of clickhouse-client is reasonably safe (nevertheless, we don't perform "secure erasing" of it from memory, it probably copied between std::string objects several time), so there is no point in asking it again.

**Comment by alexey-milovidov** [comment]
Does not reproduce for unknown reason.
