### ISSUE TITLE
MaterializedPostgreSQL Not syncing

### ISSUE THREAD

**Issue by eni9889** [ClickHouse/ClickHouse#35083]
> You have to provide the following information whenever possible.

**Describe what's wrong**

I have created a table using the MaterializedPostgreSQL Engine:
```
CREATE DATABASE postgres_db
ENGINE = MaterializedPostgreSQL('*****:5432', '****', '****', '****')
SETTINGS materialized_postgresql_tables_list = 'users,shops,shopify_shop_app_events',
materialized_postgresql_tables_list_with_schema = 1,
materialized_postgresql_schema = 'public',
materialized_postgresql_allow_automatic_update = 0,
materialized_postgresql_max_block_size = 10;
```

The initial data gets copied over but then replication does not continue. I do not see any error logs.

**Does it reproduce on recent release?**

```
ClickHouse client version 22.1.3.7 (official build).
```

**How to reproduce**

Please take a look at my example of table creation above

**Expected behavior**

I expect the table to get new updates from the Postgres DB

**Additional context**

I am using Postgres 10 on RDS

**Comment by kssenii** [comment]
This Postgres version is not supported now. It should work starting from version 12.
(Similar issue: https://github.com/ClickHouse/ClickHouse/issues/34464#issuecomment-1035005766)
