### ISSUE TITLE
build failed with 22.2 :  1c8bbaed 

### ISSUE THREAD

**Issue by etah000** [ClickHouse/ClickHouse#35091]
**Operating system**
Ubuntu 20.04.4 LTS

**Cmake version**
cmake version 3.16.3

**Ninja version**
not use ninja.

**Compiler name and version**
Ubuntu clang version 14.0.0-++20220301114924+19149538e9a9-1~exp1~20220301234936.84
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

**Full cmake and/or ninja output**

[cmake_ouptput.txt](https://github.com/ClickHouse/ClickHouse/files/8197105/cmake_ouptput.txt)

code version: github/22.2:  1c8bbaed

** make error **
[ 63%] Building CXX object contrib/grpc/CMakeFiles/grpc.dir/src/core/lib/iomgr/endpoint_pair_posix.cc.o
Scanning dependencies of target intrinsics_gen
make[2]: *** No rule to make target 'contrib/llvm/llvm/NATIVE/Release/bin/llvm-tblgen', needed by 'contrib/llvm/llvm/include/llvm/IR/Attributes.inc'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:14235: contrib/llvm/llvm/include/llvm/IR/CMakeFiles/intrinsics_gen.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by tavplubix** [comment]
> code version: github/22.2: https://github.com/ClickHouse/ClickHouse/commit/1c8bbaedcce9709c9909587fb3cf1da53329dff9

`ClickHouse build check` successfully passed on this commit: https://s3.amazonaws.com/clickhouse-builds/34676/1c8bbaedcce9709c9909587fb3cf1da53329dff9/clickhouse_build_check_(actions)/report.html

> not use ninja
> clang version 14.0.0

We use ninja and clang 14 in our CI (you can find exact commands in the [log](https://s3.amazonaws.com/clickhouse-builds/22.2/1c8bbaedcce9709c9909587fb3cf1da53329dff9/package_release/build_log.log)). If you use custom build environment, then you should resolve all possible issues by yourself.

**Comment by zhanghuajieHIT** [comment]
I have the same problem
```
ninja --version
1.10.2

clang -v
clang version 13.0.1
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.3.0
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.3.0
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
```

And, the build log shows the clang version is 13.
https://s3.amazonaws.com/clickhouse-builds/22.2/1c8bbaedcce9709c9909587fb3cf1da53329dff9/package_release/build_log.log

![image](https://user-images.githubusercontent.com/22310751/158308257-99b0d4f4-cf09-44de-9dd6-2c3669d1c84e.png)

**Comment by zhanghuajieHIT** [comment]
@etah000 Do you have solve it?

**Comment by etah000** [comment]
Not yet.

**Comment by zhanghuajieHIT** [comment]
> Not yet.

I solve it.
Use ninja
My previous compilation failed because I didn't use ld.lld

**Comment by etah000** [comment]
What are your compiling options?  I failed with "-DUSE_STATIC_LIBRARIES=0 -DSPLIT_SHARED_LIBRARIES=1 -DCLICKHOUSE_SPLIT_BINARY=1  -DENABLE_MULTITARGET_CODE=OFF -DCMAKE_INSTALL_PREFIX=/clickhouse"。

**Comment by zhanghuajieHIT** [comment]
```
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release
ninja
```

**Comment by zhanghuajieHIT** [comment]
The error` No rule to make target 'contrib/llvm/llvm/NATIVE/Release/bin/llvm-tblgen'` is due to function `build_native_tool `in `contrib/llvm/llvm/cmake/modules/CrossCompile.cmake` can not produce llvm-tblgen in contrib/llvm/llvm/NATIVE/Release/

Can we add `COMMAND ${CMAKE_COMMAND} -E copy ${${PROJECT_NAME}_NATIVE_BUILD}/bin/${target} ${output_path}` like this:  @tavplubix 
```
function(build_native_tool target output_path_var)
  cmake_parse_arguments(ARG "" "" "DEPENDS" ${ARGN})

  if(CMAKE_CONFIGURATION_TYPES)
    set(output_path "${${PROJECT_NAME}_NATIVE_BUILD}/Release/bin/${target}")
  else()
    set(output_path "${${PROJECT_NAME}_NATIVE_BUILD}/bin/${target}")
  endif()

  llvm_ExternalProject_BuildCmd(build_cmd ${target} ${${PROJECT_NAME}_NATIVE_BUILD}
                                CONFIGURATION Release)
  add_custom_command(OUTPUT "${output_path}"
                     COMMAND ${build_cmd}
                     COMMAND ${CMAKE_COMMAND} -E copy ${${PROJECT_NAME}_NATIVE_BUILD}/bin/${target} ${output_path}
                     DEPENDS CONFIGURE_${PROJECT_NAME}_NATIVE ${ARG_DEPENDS}
                     WORKING_DIRECTORY "${${PROJECT_NAME}_NATIVE_BUILD}"
                     COMMENT "Building native ${target}..."
                     USES_TERMINAL)
  set(${output_path_var} "${output_path}" PARENT_SCOPE)
endfunction()
```

What is more, with clang and ninja, there is no `llvm-tblgen` in `contrib/llvm/llvm/NATIVE/Release/bin/`
![image](https://user-images.githubusercontent.com/22310751/158744331-1afe39cb-c14d-42f1-8817-4f696e44a424.png)
