### ISSUE TITLE
Does Clickhouse support the XA standard?

### ISSUE THREAD

**Issue by LuPan2015** [ClickHouse/ClickHouse#35095]
Does clickhouse support the XA standard? 
If it is not supported, how to guarantee exactly one time when using flink to write?

**Comment by genzgd** [comment]
ClickHouse does not currently support the XA standard for distributed transactions.  Some limited transaction work is on the 2022 roadmap but for the near future ClickHouse lacks transaction support and has no Global Transaction Manager for sharded/distributed tables.  It looks like Alibaba has a proposal/solution in this area:  https://www.alibabacloud.com/blog/the-open-source-real-time-data-warehouse-solution-based-on-emr-olap---clickhouse-transaction-implementation_598583 but it's not clear if or when pieces of this solution will be publicly available.


There is some discussion here about the issue of exactly once writes:  https://github.com/ClickHouse/ClickHouse/issues/7522.  However, in general the loosely coupled nature of ClickHouse distributed tables make global transaction coordination a hard problem that requires either a external coordinator component or an significant addition to the ClickHouse code base that is not presently planned.
