### ISSUE TITLE
How to insert CSV data for map data type

### ISSUE THREAD

**Issue by gegorov2030** [ClickHouse/ClickHouse#35104]
I am trying to insert data via CSV into map data type column 
Something like:
```SQL
CREATE TABLE table_map (a Map(String, UInt64)) ENGINE=Memory;
INSERT INTO table_map VALUES ('{\'key1\':1, \'key2\':10}');
```
In CSV I tried:
```CSV
"{'key1': 1,'key2':10}"
"{\'key1\': 1,\'key2\':10}"
```
but always have errors
` DB::Exception: Syntax error: failed at position 35 (')') (line 1, col 35): ) FORMAT CSV`

What is the right way to insert data?

Also map data type is not the same as json, do we have some kind of array to map (PHP) converter?

**Comment by den-crane** [comment]
```
select * from table_map format CSV;
"{'key1':1,'key2':10}"


insert into table_map format CSV "{'key1':1111,'key111112':1011}"
;

select * from table_map ;
┌─a────────────────────┐
│ {'key1':1,'key2':10} │
└──────────────────────┘
┌─a──────────────────────────────┐
│ {'key1':1111,'key111112':1011} │
└────────────────────────────────┘
```

**Comment by gegorov2030** [comment]
@den-crane 

curl --location --request POST 'http://localhost:8123/?extremes=0&readonly=0&max_execution_time=20&enable_http_compression=1&database=bla&query=INSERT+INTO+table_map+%28%29+FORMAT+CSV' \
--header 'X-ClickHouse-User: bla' \
--header 'X-ClickHouse-Key: bla' \
--header 'Content-Type: text/plain' \
--data-raw '"{'\''key1'\'': 3,'\''key2'\'':4}"'

![Screen Shot 2022-03-07 at 2 48 25 PM](https://user-images.githubusercontent.com/59376336/157131103-5e2c9af5-4c26-45c3-8e80-ca0907e09517.png)
