### ISSUE TITLE
clickhouse 22.2.2 verison    still can`t  support  settings materialized_mysql_tables_list  

### ISSUE THREAD

**Issue by Jaincy** [ClickHouse/ClickHouse#35119]
Received exception from server (version 22.2.2):
Code: 501. DB::Exception: Received from 10.1.3.176:9000. DB::Exception: Cannot create MySQL database, because Code: 115. DB::Exception: Unknown setting materialized_mysql_tables_list: for database MaterializedMySQL. (UNKNOWN_SETTING),. (CANNOT_CREATE_DATABASE)

**Comment by tavplubix** [comment]
It was merged just 5 days ago (#34487), of course 22.2 does not support it.
