### ISSUE TITLE
How to use count in AggregatingMergeTree table

### ISSUE THREAD

**Issue by vincenzon** [ClickHouse/ClickHouse#35122]
I am trying to create an aggregating table driven by a materialized view. Here is my setup: 

```
  drop table if exists foo;
  drop table if exists foo_sec;
  drop view if exists foo_sec_mv;

  create table foo
  (
      id String,
      tmMs Int64
  )
  engine = MergeTree()
  order by (id, tmMs);

  create table foo_sec (
    id String,
    sec Int64,
    n AggregateFunction(count, Int64)
  )
  engine = AggregatingMergeTree()
  partition by tuple()
  order by (id, sec);

  create materialized view if not exists foo_sec_mv 
  to foo_sec
  as select
    id,  
    cast(tmMs/1000 as Int64) as sec,
    countState() as nState
  from foo
  group by id, sec
  order by id, sec;
```

Then I insert rows into the base table: 

```
  insert into foo values ('A',12345678), ('A',12345679),('A',12345678);
```

But when I select from the aggregating table the count is zero: 
```
  select id, sec, countMerge(n) from foo_sec group by id, sec;
┌─id─┬───sec─┬─countMerge(n)─┐
│ A  │ 12345 │             0 │
└────┴───────┴───────────────┘
```

I can make it work using a sum aggregate of 1, but that seems a hack. How is a count aggregate supposed to work? And where is the best place to find documentation on this sort of thing? Thanks.

**Comment by den-crane** [comment]
Column names should match in select and in the table

>n AggregateFunction(count, Int64)

>countState() as nState


https://den-crane.github.io/Everything_you_should_know_about_materialized_views_commented.pdf page 14

https://clickhouse.com/docs/en/sql-reference/statements/create/view/#materialized

Important

**Materialized views in ClickHouse use column names instead of column order during insertion into destination table. If some column names are not present in the SELECT query result, ClickHouse uses a default value, even if the column is not [Nullable](https://clickhouse.com/docs/en/sql-reference/data-types/nullable/). A safe practice would be to add aliases for every column when using Materialized views.**

**Comment by den-crane** [comment]
>     tmMs Int64
>   countState(tmMs) as nState

This is incorrect. It should be `countState() as nState` 

count() === number of rows.
count(tmMs) === number of rows `where tmMs is not Null`

**Comment by den-crane** [comment]
BTW, you should use SimpleAggregateFunction sum from performance perspective.


```sql
  drop table if exists foo;
  drop table if exists foo_sec;
  drop view if exists foo_sec_mv;

create table foo
  (
      id String,
      tmMs Int64
  )
  engine = MergeTree()
  order by (id, tmMs);

  create table foo_sec (
    id String,
    sec Int64,
    nState SimpleAggregateFunction(sum, Int64)
  )
  engine = AggregatingMergeTree()
  partition by tuple()
  order by (id, sec);

  create materialized view if not exists foo_sec_mv 
  to foo_sec
  as select
    id,  
    cast(tmMs/1000 as Int64) as sec,
    count() as nState
    from foo
    group by id, sec
    order by id, sec;

  insert into foo values ('A',12345678), ('A',12345679),('A',12345678);

select id, sec, sum(nState) from foo_sec group by id, sec;
┌─id─┬───sec─┬─sum(nState)─┐
│ A  │ 12345 │           3 │
└────┴───────┴─────────────┘

optimize table foo_sec final;
select * from foo_sec;

┌─id─┬───sec─┬─nState─┐
│ A  │ 12345 │      3 │
└────┴───────┴────────┘
```

**Comment by vincenzon** [comment]
If I use `countState()` instead of `countState(tmMs)` I get this error: 
```
Received exception from server (version 22.1.3):
Code: 70. DB::Exception: Received from localhost:9000. DB::Exception: Conversion from AggregateFunction(count) to AggregateFunction(count, Int64) is not supported: while converting source column nState to destination column nState: while pushing to view default.foo_sec_mv (947b27f0-36d4-4c02-a004-dc4c598bde24). (CANNOT_CONVERT_TYPE)
```
I assumed the `tmMs` forced the type for me and was why it was needed. 

Your change to use `SimpleAggregateFunction(sum,Int64)` , `count()` instead of `countState()`, and `sum(nState)` instead of `sumMerge(nState)` works for me also, but I admit I find it confusing that I don't use State and Merge to get it to work. 

Thanks for the help!

**Comment by den-crane** [comment]
Because it should be 

```
 nState AggregateFunction(count)        --------<<<<<---- not  AggregateFunction(count, Int64)


countState() AS nState
```

**Comment by vincenzon** [comment]
Got it. No Int64 because the count is taking no args. Thanks.
