### ISSUE TITLE
Code: 1000. DB::Exception: Received from 127.0.0.1:9000. DB::Exception: File not found

### ISSUE THREAD

**Issue by Jack012a** [ClickHouse/ClickHouse#35137]
ClickHouse client version 21.4.6.55 (official build).

We start to have issues on querying the table similar as follow:

 CREATE TABLE default.TableABC (
  `date` Date DEFAULT toDate(intDiv(timestamp, 1000000000)),
  `name` String,
...
) ENGINE = MergeTree PARTITION BY date
ORDER BY
  (name, timestamp) SETTINGS index_granularity = 8192
;;

First query failed.

:) select distinct(date) from default.TableABC ;

SELECT DISTINCT date
FROM default.TableABC 
Query id: fffd18c4-1c79-46e0-8edf-bf01b903a758
↙ Progress: 1.38 million rows, 2.75 MB (6.56 million rows/s., 13.12 MB/s.)  0%
0 rows in set. Elapsed: 0.225 sec. Processed 1.38 million rows, 2.75 MB (6.11 million rows/s., 12.22 MB/s.)
Received exception from server (version 21.4.6):
Code: 1000. DB::Exception: Received from 127.0.0.1:9000. DB::Exception: File not found: /var/lib/clickhouse/store/61e/61e48cbb-c5aa-4443-9872-cfa75ca5b1cf/20220125_6661_6802_3_10820/date.mrk2.

Second query passed but the result is wrong b/c we have more data than this.

:) select distinct(date) from default.TableABC;
SELECT DISTINCT date
FROM default.TableABC
Query id: 57f9c392-4e92-4425-a682-77ffd1cb9b00

┌───────date─┐
│ 2022-03-08 │
└────────────┘
┌───────date─┐
│ 2022-03-04 │
└────────────┘
┌───────date─┐
│ 2022-03-07 │
└────────────┘

3 rows in set. Elapsed: 0.211 sec. Processed 201.97 million rows, 403.94 MB (956.42 million rows/s., 1.91 GB/s.)

We have data from 20220126 to 20220308 but the above query only returns a few days.
$ ls -l /var/lib/clickhouse/store/61e/61e48cbb-c5aa-4443-9872-cfa75ca5b1cf

drwxr-x--- 2 clickhouse clickhouse 24576 Mar  4 18:35 20220126_6804_6941_3_10820
..
drwxr-x--- 2 clickhouse clickhouse 24576 Mar  4 18:35 20220301_10387_10387_0_10820
..
drwxr-x--- 2 clickhouse clickhouse 20480 Mar  7 06:57 20220307_10821_10855_2
..
drwxr-x--- 2 clickhouse clickhouse 20480 Mar  8 15:31 20220308_11102_11102_0
drwxr-x--- 2 clickhouse clickhouse  4096 Nov 19 10:06 detached
-rw-r----- 1 clickhouse clickhouse     1 Nov 19 10:06 format_version.txt
-rw-r----- 1 clickhouse clickhouse   116 Mar  4 18:35 mutation_10820.txt

$ ls -l /var/lib/clickhouse/store/61e/61e48cbb-c5aa-4443-9872-cfa75ca5b1cf/20220125_6661_6802_3_10820/date.mrk2
ls: cannot access /var/lib/clickhouse/store/61e/61e48cbb-c5aa-4443-9872-cfa75ca5b1cf/20220125_6661_6802_3_10820/date.mrk2: No such file or directory

error log:
2022.03.08 15:35:44.467598 [ 38310 ] {4088f588-9a88-4927-9cb7-d87d6504f679} <Error> TCPHandler: Code: 1000, e.displayText() = DB::Exception: File not found: /var/lib/clickhouse/store/61e/61e48cbb-c5aa-4443-9872-cfa75ca5b1cf/20220125_6661_6802_3_10820/date.mrk2, Stack trace:

0. Poco::FileImpl::handleLastErrorImpl(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x12683e35 in /usr/bin/clickhouse
1. DB::DiskLocal::getFileSize(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const @ 0xefecb9d in /usr/bin/clickhouse
2. DB::MergeTreeMarksLoader::loadMarksImpl() @ 0xfd22247 in /usr/bin/clickhouse
3. DB::MergeTreeMarksLoader::loadMarks() @ 0xfd21c78 in /usr/bin/clickhouse
4. DB::MergeTreeReaderStream::MergeTreeReaderStream(std::__1::shared_ptr<DB::IDisk>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange> > const&, DB::MergeTreeReaderSettings const&, DB::MarkCache*, DB::UncompressedCache*, unsigned long, DB::MergeTreeIndexGranularityInfo const*, std::__1::function<void (DB::ReadBufferFromFileBase::ProfileInfo)> const&, int) @ 0xfd2a7b1 in /usr/bin/clickhouse
5. ? @ 0xfd2e3e4 in /usr/bin/clickhouse
6. DB::MergeTreeReaderWide::addStreams(DB::NameAndTypePair const&, std::__1::function<void (DB::ReadBufferFromFileBase::ProfileInfo)> const&, int) @ 0xfd2c298 in /usr/bin/clickhouse
7. DB::MergeTreeReaderWide::MergeTreeReaderWide(std::__1::shared_ptr<DB::MergeTreeDataPartWide const>, DB::NamesAndTypesList, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::UncompressedCache*, DB::MarkCache*, std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange> >, DB::MergeTreeReaderSettings, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, double, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, double> > >, std::__1::function<void (DB::ReadBufferFromFileBase::ProfileInfo)> const&, int) @ 0xfd2bf04 in /usr/bin/clickhouse
8. DB::MergeTreeDataPartWide::getReader(DB::NamesAndTypesList const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange> > const&, DB::UncompressedCache*, DB::MarkCache*, DB::MergeTreeReaderSettings const&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, double, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, double> > > const&, std::__1::function<void (DB::ReadBufferFromFileBase::ProfileInfo)> const&) const @ 0xfc8a19f in /usr/bin/clickhouse
9. DB::MergeTreeThreadSelectBlockInputProcessor::getNewTask() @ 0xfd5c5f7 in /usr/bin/clickhouse
10. DB::MergeTreeBaseSelectProcessor::generate() @ 0xfd31f93 in /usr/bin/clickhouse
11. DB::ISource::tryGenerate() @ 0xff2bdb5 in /usr/bin/clickhouse
12. DB::ISource::work() @ 0xff2b9aa in /usr/bin/clickhouse
13. DB::SourceWithProgress::work() @ 0x100dd52a in /usr/bin/clickhouse
14. ? @ 0xff6504d in /usr/bin/clickhouse
15. DB::PipelineExecutor::executeStepImpl(unsigned long, unsigned long, std::__1::atomic<bool>*) @ 0xff61d01 in /usr/bin/clickhouse
16. ? @ 0xff66846 in /usr/bin/clickhouse
17. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x88372bf in /usr/bin/clickhouse
18. ? @ 0x883ade3 in /usr/bin/clickhouse
19. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
20. clone @ 0xfe9fd in /usr/lib64/libc-2.17.so

If you query the data directly through a specific date, you still can get data:

:) select count(*) from default.TableABC where date='2022-02-22';
SELECT count(*)
FROM default.TableABC
WHERE date = '2022-02-22'
Query id: ae4b4a24-3a7c-4b70-ab85-94e7a8243aa0
┌───count()─┐
│ 102544705 │
└───────────┘
1 rows in set. Elapsed: 0.002 sec.

Question> What was the issue that caused this problem?

Thank you

**Comment by melvynator** [comment]
It seems that there is a corrupted file. 

Is there any specific reason for the file to be corrupted? Do you have the server log by any chance?

Could you try to detach and reattach the corrupted part?

**Comment by q0987** [comment]
Hello,
As shown in the post, the corrupted file doesn't exist on the system. I can fix this issue by restarting the server but after a day or two the same errors come back again. FYI: we have scheduled a task to delete the data from N days ago, so this might triggered this issue. The schedule task has been running for a year without issue. So it must be something else. The only major changes we did is to drop a few columns from the table. I am not sure whether there are some bugs here that cause the problem.

Is there a way that we can purge the DB w/o restarting the system?

Thank you

**Comment by melvynator** [comment]
In order to delete older data there is now a new feature called TTL that will do that for you: https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/mergetree/#mergetree-table-ttl 

I'm not not sure what you mean my "purge" the DB. 

> As shown in the post, the corrupted file doesn't exist on the system.

My point was that the file that you are mentionning is only one of the many data structure defined by clickhouse to optimize read. Byt `DETACH/ATTACH` the damaged part you may eventually fix the issue: https://clickhouse.com/docs/en/sql-reference/statements/alter/partition/#alter_attach-partition-from
