### ISSUE TITLE
dateAdd overflow

### ISSUE THREAD

**Issue by roma-lezhnin** [ClickHouse/ClickHouse#35155]
```SQL
select dateAdd(month, step, toStartOfMonth(toDateTime(1643932800))) as tm
  from (select arrayJoin(range(3000)) as step)
  where tm <> toDateTime('1970-01-01 00:00:00')
    and tm <= toDateTime(1646438399);
```

The selection condition is incorrectly execute and the query result returns 1400 instead of 2 rows.

**Environment**

CH version: 21.8.10.19.
Server timezone: Etc/UTC.

**Expected behavior**

| tm | 
| ----------- | 
| 2022-02-01 |
| 2022-03-01 |

**Behavior**

| tm | 
| ----------- | 
| 2022-02-01 |
| 2022-03-01 |
| 2106-03-01 |
| 2106-04-01 |
| 2106-05-01 |
| 2106-06-01 |
| 2106-07-01 |
| 2106-08-01 |
| 2106-09-01 |
| 2106-10-01 |
| 2106-11-01 |
| 2106-12-01 |
| 2107-01-01 |
| 2107-02-01 |
| etc... + 1400 rows |

**Comment by filimonov** [comment]
Workaround - cast it to DateTime64

```
SELECT toDateTime64(toStartOfMonth(toDateTime(1643932800)), 0) + toIntervalMonth(step) AS tm
FROM
(
    SELECT arrayJoin(range(3000)) AS step
)
WHERE (tm != toDateTime('1970-01-01 00:00:00')) AND (tm <= toDateTime(1646438399))

Query id: 6f0f0d66-e0eb-4214-b495-8bbdc4a767c2

┌──────────────────tm─┐
│ 2022-02-01 00:00:00 │
│ 2022-03-01 00:00:00 │
└─────────────────────┘
```

**Comment by roma-lezhnin** [comment]
Thank you very much for your help
