### ISSUE TITLE
Bazel build for ClickHouse

### ISSUE THREAD

**Issue by smahapatra1** [ClickHouse/ClickHouse#35163]
Hello,

ClickHouse code seems really nice and I'd like to use as a library in addition to the database. As we use a lot of open source software from Google and Bazel for them, it'd be really nice to get Bazel build for Clickhouse. Is there any plan for it or has anybody contributed Bazel build files for CH?

Thanks for such a wonderful open-source software!

**Comment by alexey-milovidov** [comment]
This is very low priority task and it's unlikely that it will appear to be implemented. Let's close for now.

**Comment by alexey-milovidov** [comment]
CC @azat maybe you can be interested.

**Comment by alexey-milovidov** [comment]
But first need to make this task: https://github.com/ClickHouse/ClickHouse/issues/35630

**Comment by azat** [comment]
>CC @azat maybe you can be interested.

Not really, AFAIR @traceon was interested in this (but he was talking about clickhouse-odbc).

And actually I would prefer cmake over bazel.

>But first need to make this task: #35630

But if this will be done, converting cmake files should not block it, since you need to write own bazel files anyway (FWIW here is bazel for llvm - https://github.com/google/llvm-bazel)

**Comment by traceon** [comment]
It makes sense to use Bazel for integrations (when used as a library), but for a standalone software, CMake has more pros: packaging, GUI IDEs, different build systems, etc. Maybe it is possible to combine these.

**Comment by azat** [comment]
>Maybe it is possible to combine these

I don't think that it worth it, supporting two build systems (with lots of contrib) sounds too complex.

**Comment by smahapatra1** [comment]
Google Abseil supports both Bazel and CMAKE, but I agree it is not worth given a lot of contrib software.
  
  
  
  
  
  
  

  
  
>
