### ISSUE TITLE
result_rows and written_rows different with no exception

### ISSUE THREAD

**Issue by Ravojay** [ClickHouse/ClickHouse#35168]
When I execute the following query (getting some query log):
`select query_start_time,query_duration_ms,query,event_time,written_rows,result_rows,exception,exception_code from clusterAllReplicas('xxx', 'system', 'query_log') where event_time >= 'xxx' and event_time <= 'xxx' and type != 'QueryStart' and query_kind = 'Insert' and query like '%local%' and query not like '%zookeeper%' and is_initial_query = 1`

I got the following result: 

Row 98:
───────
query_start_time:  2022-03-09 18:00:43
query_duration_ms: 24
query:             insert into xxx.xxx_local  FORMAT TabSeparated

event_time:        2022-03-09 18:00:43
written_rows:      137
result_rows:       0
exception:
exception_code:    0

Row 99:
────────
query_start_time:  2022-03-09 18:00:43
query_duration_ms: 48
query:             insert into xxx.xxxx_local  FORMAT TabSeparated

event_time:        2022-03-09 18:00:43
written_rows:      102
result_rows:       102
exception:
exception_code:    0

seems that result_rows is not always the same as written_rows for Insert queries, even with no exceptions. 
From the information given by the [documentation](https://clickhouse.com/docs/en/operations/system-tables/query_log/), I don't se how this is happening. Why could result_rows be 0 if written_rows is not? Anyone knows what is going on here ? 
Thanks in advance!!

**Comment by den-crane** [comment]
1. Clickhouse version?
2. provide steps to reproduce

**Comment by den-crane** [comment]
no info. closed
