### ISSUE TITLE
Code: 1001. DB::Exception: Received from 192.168.1.1:9000 DB::Exception: std::runtime_error: failed alloc while reading. (STD_EXCEPTION)(vesrion 22.2.2.1)

### ISSUE THREAD

**Issue by rootwhois** [ClickHouse/ClickHouse#35167]
We tried to upgrade the Clickhouse server from 20.9.6.14 to 22.2.2.1, but it occurs an error while querying a distributed tables belows: Code: 1001. DB::Exception: Received from 192.168.1.1:9000 DB::Exception: std::runtime_error: failed alloc while reading. (STD_EXCEPTION)(vesrion 22.2.2.1)

**Comment by melvynator** [comment]
Thank you for reaching out to us. There is a big gap in the two versions of the software (more than 2 years of releases). Some internal data structure might have changed. That's a lot of change in the changelogs to go through. 

You could eventually spin up additional instances of ClickHouse with the newest version. With the two set of instances running, you could then use a `SELECT FROM remote` to ingest your old data in your new cluster. Is that a solution that could work for you?

**Comment by rootwhois** [comment]
> Thank you for reaching out to us. There is a big gap in the two versions of the software (more than 2 years of releases). Some internal data structure might have changed. That's a lot of change in the changelogs to go through.
> 
> You could eventually spin up additional instances of ClickHouse with the newest version. With the two set of instances running, you could then use a `SELECT FROM remote` to ingest your old data in your new cluster. Is that a solution that could work for you?

Thx, it might be the bitmap struction changed, we tried to recreate the table on our cluster and it works fine until now.
Do we need to ingest the data form old version while before upgrade? There's too much data to deal with....

**Comment by melvynator** [comment]
I mean with such a big difference in your software version you will struggle in figuring out which data structure changed. We have a list of changelog for the last two years: https://github.com/ClickHouse/ClickHouse/blob/master/CHANGELOG.md

**Comment by rootwhois** [comment]
Okay, thanks for your suggestion. And thanks for your outstanding contribution!
