### ISSUE TITLE
Can clickhouse-copier migrate data incrementally? 

### ISSUE THREAD

**Issue by FanWuu** [ClickHouse/ClickHouse#35165]
Can clickhouse-copier migrate data incrementally?

**Comment by rkozlo** [comment]
As i know it can, but you will have to increment this by whole partitions and specific partition to migrate in clickhouse-copier config file. For example you have migrated partition 202201, 202202 and after 31.03.2022 you will move another partition 202203

**Comment by FanWuu** [comment]
> As i know it can, but you will have to increment this by whole partitions and specific partition to migrate in clickhouse-copier config file. For example you have migrated partition 202201, 202202 and after 31.03.2022 you will move another partition 202203

Do you have a case or link?

**Comment by rkozlo** [comment]
In documentation is about this. https://clickhouse.com/docs/en/operations/utilities/clickhouse-copier/
Option enabled_partitions

**Comment by alexey-milovidov** [comment]
It cannot work incrementally. An example how it can be done manually is:
- partition data by month;
- assuming data for older months is not modified;
- enable insertion of the new data to both clusters;
- copy older months with clickhouse-copier to the new cluster;
- wait until next month;
- drop partition of partially written new data for previous month;
- copy previous month with clickhouse-copier to the new cluster;
- switch customer workload to the new cluster;
- remove insertion of the data to the old cluster.
