### ISSUE TITLE
Low performance in [uniqCombined64Merge]

### ISSUE THREAD

**Issue by zjjDuke** [ClickHouse/ClickHouse#35177]
Here is the SQL:

select user_bucket_number,
uniqCombined64MergeIf(20)(l28, dtm >= '20220112' and dtm<= '20220208') as l28_20220208,
uniqCombined64MergeIf(20)(l28, dtm >= '20220113' and dtm<= '20220209') as l28_20220209,
uniqCombined64MergeIf(20)(l28, dtm >= '20220114' and dtm<= '20220210') as l28_20220210,
from (
    select dtm, user_bucket_number, uniqCombined64State(20)(user_id) as l28
    from experiment.dm_exp_user_global_engagement_v1_day_inc
    where dtm >= '20220112' and dtm <= '20220210'
    group by dtm, user_bucket_number
)
group by user_bucket_number

We have about 60,000,000 records per dtm in experiment.dm_exp_user_global_engagement_v1_day_inc,
and the ddl is :

(
    `user_id` String,
    `user_bucket_number` Int COMMENT 'put user_id into 20 different buckets'
)
ENGINE = ServerMergeTree(javaHash(user_id), 40)
PARTITION BY toInt32(dtm)

My plan is to calculate uniqCombined64 for each dtm and combine them together afterwards. It is based on the wrong hypothesis that merge operation will not take much time. 

I have not read the code about this part but I guess someone may know the mistake I have made in this sql.

Thx

**Comment by den-crane** [comment]
1. There is no such engine like ServerMergeTree
2. Clickhouse version?
3. Steps to reproduce?

**Comment by den-crane** [comment]
no info. closed
