### ISSUE TITLE
How to write `Group By` like MySQL?

### ISSUE THREAD

**Issue by billcoding** [ClickHouse/ClickHouse#35170]
table
---

|col1|col2|col3|col4|col5|col6|
|-|-|-|-|-|-|
|a|b|c|d|1|1|
|a|b|c|d|2|2|
|aa|bb|cc|dd|11|11|
|aa|bb|cc|dd|22|22|

SQL
---
```sql
select col1,col2,col3,col4,col5,col6 from table group by col1,col2,col3,col4;
```

In MySQL, the SQL is valid.

And what's the ClickHouse way?

**Comment by nickitat** [comment]
Try the [any](https://clickhouse.com/docs/en/sql-reference/aggregate-functions/reference/any) aggregate function.
