### ISSUE TITLE
Play UI Could Be More Clear About Showing it is in the Middle of a Long Running Query

### ISSUE THREAD

**Issue by andymjames** [ClickHouse/ClickHouse#35188]
**Describe the issue**
Context when I noticed it: I was following the bootcamp and got to the insert data step https://clickhouse.com/learn/lessons/bootcamp/lab/#3-insert-data
Here's a screenshot of what it looked like while my long query ran

<img width="1535" alt="Screen Shot 2022-03-10 at 11 48 32 AM" src="https://user-images.githubusercontent.com/31216945/157714297-292f1e42-2d8b-4b29-90f5-bbb257c98dfe.png">

When the Play UI is issuing a long-running query, it isn't very clear that that's happening. The only reaction the UI has to a long-running query is to show a subtle, non-animated status indicator as far as I can tell

**Expected behavior**
I don't think it's my place to prescribe how to change the UI, but there are a few strategies I've seen in other UIs that could be applied here.

1) The hour glass indicator icon could be animated to draw the user's attention and the motion gives users comfort that things are working and not crashed.
2) The `Run` button could be disabled so that the user doesn't try to send another query before the first one finishes.
3) The results pane could clear out when the new query is sent to show it's waiting for new results to show. Results pane could also be set to show a message like `Query running...`

**Comment by peledni** [comment]
Per @alexey-milovidov's request, the Run button will not be disabled (so users can abort the current query and run another). I only animated the hourglass icon to indicate to the user that the query is running.
