### ISSUE TITLE
Some engine will save and display the user's plaintext password

### ISSUE THREAD

**Issue by zhanghuajieHIT** [ClickHouse/ClickHouse#35180]
In clickhouse, some engine will save  and display the user‘s plaintext password, such as: MySQL，MaterializeMySQL，PostgreSQL，MaterializedPostgreSQL，S3，MongoDB，ExternalDistributed，JDBC.

For instance,
```
create table mysql(id UInt32, name String)Engine=MySQL('127.0.0.1:3306', 'default', 'table', 'root', 'zhanghuajie');
```
In metadata file `mysql.sql`, it records the password:
```
ATTACH TABLE _ UUID '796611d3-e62d-4722-b966-11d3e62d2722'
(
    `id` UInt32,
    `name` String
)
ENGINE = MySQL('127.0.0.1:3306', 'default', 'table', 'root', 'zhanghuajie')
```

Of course,  the sql `show create table` is also can show it
```
show create table mysql;

SHOW CREATE TABLE mysql

Query id: 61648bb9-2e96-48b3-94d8-4eef58396945

┌─statement───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ CREATE TABLE default.mysql
(
    `id` UInt32,
    `name` String
)
ENGINE = MySQL('127.0.0.1:3306', 'default', 'table', 'root', 'zhanghuajie') │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

1 rows in set. Elapsed: 0.002 sec.
```

So, what I want to ask is if we can hide these plaintext passwords?
Of course, if we should hide these plaintext passwords, I'd be happy to do that.

**Comment by den-crane** [comment]
There are named collections/named connections feature
```
<yandex>
    <named_collections>
        <postgres1>
            <user>postgres</user>
            <password>mysecretpassword</password>
            <host>postgres1</host>
            <port>5432</port>
            <database>postgres</database>
        </postgres1>
    </named_collections>
</yandex>
```
then

`create table mysql(id UInt32, name String)Engine=MySQL(postgres1, table = 'table');`

**Comment by zhanghuajieHIT** [comment]
> There are named collections/named connections feature
> 
> ```
> <yandex>
>     <named_collections>
>         <postgres1>
>             <user>postgres</user>
>             <password>mysecretpassword</password>
>             <host>postgres1</host>
>             <port>5432</port>
>             <database>postgres</database>
>         </postgres1>
>     </named_collections>
> </yandex>
> ```
> 
> then
> 
> `create table mysql(id UInt32, name String)Engine=MySQL(postgres1, table = 'table');`

What about database?
If I create database, it has the same problem:
```
show create database mysql;

SHOW CREATE DATABASE mysql

Query id: 4b081fb8-3d25-4b7f-8a33-7b2cb432ca48

┌─statement────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ CREATE DATABASE mysql
ENGINE = MySQL('127.0.0.1:3306', 'mysql', 'root', 'zhanghuajie')
SETTINGS mysql_datatypes_support_level = '' │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

1 rows in set. Elapsed: 0.001 sec. 
```

**Comment by den-crane** [comment]
```
<yandex>
    <named_collections>
        <mysql1>
            <user>root</user>
            <password>clickhouse</password>
            <host>mysql57</host>
            <port>3306</port>
            <database>test_database</database>
            <table>test_table</table>
        </mysql1>
        <mysql2>
            <user>postgres</user>
            <password>mysecretpassword</password>
            <host>postgres1</host>
        </mysql2>
        <mysql3>
            <user>root</user>
            <password>clickhouse</password>
            <host>mysql57</host>
            <port>1111</port>
            <database>clickhouse</database>
            <table>test_table</table>
        </mysql3>
    </named_collections>
</yandex>
```

```
CREATE DATABASE test_database ENGINE = MySQL(mysql2)
```

https://github.com/ClickHouse/ClickHouse/pull/28577/files

**Comment by den-crane** [comment]
> Do we need to hide the password in the configuration file?

I don't understand the question.

**Comment by zhanghuajieHIT** [comment]
> > Do we need to hide the password in the configuration file?
> 
> I don't understand the question.

Others can see the passward in the config file, whether this can lead to security risks?

**Comment by alexey-milovidov** [comment]
Config file is not readable to others, only for `clickhouse` users.

**Comment by liuyuchuan** [comment]
hello,
I want to know if this configuration has version restrictions?
