### ISSUE TITLE
Disk Encryption is supported in 20.12.6.29? 

### ISSUE THREAD

**Issue by DipalPrajapati** [ClickHouse/ClickHouse#35208]
I am getting below exception with clickhouse 20.12.6.29 . 
 DB::Exception: DiskFactory: the disk 'disk2' has unknown disk type: encrypted

May I know from which version the clickhouse encryption at rest  (disk encryption) is supported?

**Comment by genzgd** [comment]
Disk encryption added in Version 21.9, see the changelog here:  https://github.com/ClickHouse/ClickHouse/blob/master/docs/en/whats-new/changelog/2021.md#new-feature-3
