### ISSUE TITLE
a question about timeSlots function

### ISSUE THREAD

**Issue by Cloud-Roc-i** [ClickHouse/ClickHouse#35205]
I want to get an array of time like [2022-03-06, 2022-03-13] , and I use timeSlot like this
```sql
 select
          toDate(
            arrayJoin(
              timeSlots(
                toDateTime('2022-03-06 00:00:00','UTC'),
                toUInt32(86400 * 7),
                86400 * 7 
              )
            )
          )
```
but I got [2022-03-03, 2022-03-10]
why it doesn't start with 2022-03-06 ?

version:21.11.2.1

**Comment by vegastar002** [comment]
```sql
 select
          toDate(
            arrayJoin(
              timeSlots(
                toDateTime('2022-03-06 00:00:00', 'UTC'),
                toUInt32(86400 * 4),
                86400
              )
            )
          );
```

**Comment by Cloud-Roc-i** [comment]
What I want is a time series which takes one day every seven days, such as every Tuesday of March, so I use following sql to replace
```sql
SELECT arrayJoin(arrayMap(x -> toDate(x), range(toUInt32(toStartOfDay(toDate('2022-03-01')) AS start), toUInt32(toStartOfDay(toDate('2022-03-31'))), 86400*7  )))
```
But I'm wondering why didn't the result of the timeSlots function (timeSlots(StartTime, Duration,[, Size])) start with the 'StartTime'


```sql
 select
          toDate(
            arrayJoin(
              timeSlots(
                toDateTime('2022-03-01 00:00:00','UTC'),
                toUInt32(86400 * 31),
                86400 * 7 
              )
            )
          ) as day
```


|       day        |
| 2022-02-24 |
| 2022-03-03 |
| 2022-03-10 |
| 2022-03-17 |
| 2022-03-24 |
| 2022-03-31 |

**Comment by vegastar002** [comment]
```sql
select
          toDate(
            arrayJoin(
              timeSlots(
                toDateTime('2022-03-01 00:00:00','UTC'),
                toUInt32(86400 * 31),
                86400 * 1  <------ chang 7 to 1  will be start with the 'startTime' 
              )
            )
          ) as day;
```

**Comment by Cloud-Roc-i** [comment]
OMG, you still don't know what I need :(
I want something like this:
2022-03-01
2022-03-08
2022-03-15
2022-03-22
2022-03-29


so I set it 86400 * 7 which means every 7 days


but you give me:
2022-03-01
2022-03-02
2022-03-03
2022-03-04
2022-03-05
2022-03-06
2022-03-07
2022-03-08
2022-03-09
2022-03-10
2022-03-11
2022-03-12
2022-03-13
2022-03-14
2022-03-15
2022-03-16
2022-03-17
2022-03-18
2022-03-19
2022-03-20
2022-03-21
2022-03-22
2022-03-23
2022-03-24
2022-03-25
2022-03-26
2022-03-27
2022-03-28
2022-03-29
2022-03-30
2022-03-31
2022-04-01

**Comment by vegastar002** [comment]
oooh, yes, you way is right ,  timeSlots cannot do it .

**Comment by SaltTan** [comment]
https://clickhouse.com/docs/en/sql-reference/functions/date-time-functions/#timeslotsstarttime-duration-size
For a time interval starting at ‘StartTime’ and continuing for ‘Duration’ seconds, it returns an array of moments in time, consisting of points from this interval **rounded down to the ‘Size’ in seconds**.
```sql
select  toDate(86400 * 7 * 2722)

toDate(multiply(multiply(86400, 7), 2722))
------------------------------------------
2022-03-03                                
```

**Comment by Cloud-Roc-i** [comment]
Oh, I got it. The Chinese version document hasn't translated your bold sentences, which confuse me for a long time.
By the way, thanks a lot my friend!
