### ISSUE TITLE
Overriding of virtual columns doesn't work

### ISSUE THREAD

**Issue by CurtizJ** [ClickHouse/ClickHouse#35215]
```sql
CREATE TABLE mt_test (_part UInt32) ENGINE = MergeTree ORDER BY tuple()

INSERT INTO mt_test VALUES (1);

SELECT _part FROM mt_test;

Received exception from server (version 22.3.1):
Code: 352. DB::Exception: Received from localhost:9000. DB::Exception: Block structure mismatch in (columns with identical name must have identical structure) stream: different types:
_part UInt32 UInt32(size = 0)
_part String String(size = 0). (AMBIGUOUS_COLUMN_NAME)
```

It's expected that virtual column can be overridden. If there exists column with the same name as some virtual column in table definition, it's preferred for reading in queries.

**Comment by alexey-milovidov** [comment]
+1, this logic will be better.

**Comment by awakeljw** [comment]
if SELECT _part, _part,_part, _part from mt_test, what should we return? if we override the virtual column,how can we return virtual column if we really need.

**Comment by Algunenano** [comment]
Works fine right and it's understood that having the ability of overriding the virtual columns is desirable. Let's add a test and close this
