### ISSUE TITLE
Fuzzer issue in #35196

### ISSUE THREAD

**Issue by Felixoid** [ClickHouse/ClickHouse#35210]
(you don't have to strictly follow this form)

**Describe the bug**
A link to the report: https://s3.amazonaws.com/clickhouse-test-reports/35196/fe8df7128e44358f1c20cda72d5813c5919eec60/fuzzer_astfuzzerasan,actions//report.html

**How to reproduce**
Try to reproduce the report and copy the tables and queries involved.

The attached report and logs:
[fuzzer_logs.tar.gz](https://github.com/ClickHouse/ClickHouse/files/8231515/fuzzer_logs.tar.gz)

**Comment by Avogar** [comment]
Reproduced in 22.3, but not in master. Seems like it's fixed.
