### ISSUE TITLE
RFC: column modifier to apply 'proper' function automatically

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#35213]
```
SELECT
 dim1, dim2,
* EXCEPT(dim1,dim2) APPLY(AUTO)
FROM table
GROUP BY dim1, dim2;
```

* For SimpleAggregateFunction(min, ...) it will apply min
* For SimpleAggregateFunction(max, ...) it will apply max
* For AggregateFunction(max, ...) it will apply maxMerge (or maxMergeState?)

The disadvantage here: the column names will have the function name after that tranformation

**Comment by erikdubbelboer** [comment]
This way the code that generates the query doesn't have to know if a column is `SimpleAggregateFunction(min, ...)` etc. Alternative is that the code does know what kind of aggregation there is and expands the expressions itself.

**Comment by SaltTan** [comment]
> For SimpleAggregateFunction(min, ...) it will apply min
For SimpleAggregateFunction(max, ...) it will apply max
For AggregateFunction(max, ...) it will apply maxMerge (or maxMergeState?)

For all other data types it will apply ANY

**Comment by UnamedRus** [comment]
> The disadvantage here: the column names will have the function name after that tranformation

It can be covered by RENAME combinator https://github.com/ClickHouse/ClickHouse/issues/30411


Related  https://github.com/ClickHouse/ClickHouse/issues/29109

**Comment by amosbird** [comment]
Column transformers can only understand AST without type information. We can introduce a "smart" function which does the dynamic dispatching based on argument types.

**Comment by amosbird** [comment]
fjapwoeifjpwef
pewijfpwaoeifjp
paoiwejfpaoiewjf

> fwef

**Comment by alexey-milovidov** [comment]
The proposed `APPLY(AUTO)` syntax looks weird - it will be difficult to remember it, and it will be hard to explain the intuition behind it to other people.

**Comment by alexey-milovidov** [comment]
I don't know what syntax sugar will be appropriate, but the task is solvable by creating a view manually.

**Comment by Slind14** [comment]
Unfortunately, this is not applicable to our use case. It would be great if this could be reconsidered. We are open to any kind of syntax. It would just need to be possible without query computational overhead through SQL.
