### ISSUE TITLE
GRANT permissions to system tables don't work

### ISSUE THREAD

**Issue by loyd** [ClickHouse/ClickHouse#35239]
> You have to provide the following information whenever possible.

It seems that `GRANT` permissions don't work well with system tables that aren't based on `MergeTree`, e.g. `system.parts` (`SystemParts`) and `system.mutations` (`SystemMutations`).

> A clear and concise description of what works not as it is supposed to.

We have a dedicated `grafana` user that's used for queries from dashboards. Permissions for the user are set using `GRANT` instead of `users.xml` in order to provide per-table control.

**SHOW CREATE USER grafana**
```
CREATE USER grafana IDENTIFIED WITH sha256_password SETTINGS PROFILE grafana
```

**SHOW GRANTS FOR grafana**
```
┌─GRANTS FOR grafana──────────────────────────────────────────┐
│ GRANT SHOW SETTINGS PROFILES ON *.* TO grafana              │
│ GRANT SELECT ON system.mutations TO grafana                 │
│ GRANT SELECT ON system.parts TO grafana                     │
│ GRANT SELECT ON system.processes TO grafana                 │
│ GRANT SELECT ON system.query_log TO grafana                 │
│ GRANT SELECT ON system.settings_profile_elements TO grafana │
└─────────────────────────────────────────────────────────────┘
```

Queries to `system.query_log` work well, but ones to `system.mutations` and `system.parts` return empty results.

**Does it reproduce on recent release?**

22.1.3.7

**Comment by alexey-milovidov** [comment]
As far as I understand, the system tables that show per table info also check permissions to filter the data.
For example, unless you have permission for a table, this table will not appear in the list of merges.

@vitlibar Please clarify and close this task if needed.

**Comment by den-crane** [comment]
related https://github.com/ClickHouse/ClickHouse/issues/24887

**Comment by loyd** [comment]
It seems it's not enough to give access to `system.*` tables. In order to see any information about parts, we need to grant access to production databases. That's unacceptable due to security reasons =(. Are there variants to provide access to `system.parts` and all tables inside but do not give permissions to select any data from that tables? Is it intended behavior?

**Comment by loyd** [comment]
Hmm... `GRANT SHOW on some_db_name.* TO grafana;` is enough.
Thanks for your attention)
