### ISSUE TITLE
Cannot create table with Map column

### ISSUE THREAD

**Issue by wbxsGithub** [ClickHouse/ClickHouse#35244]
> Make sure to check documentation https://clickhouse.yandex/docs/en/ first. If the question is concise and probably has a short answer, asking it in Telegram chat https://telegram.me/clickhouse_en is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

> If you still prefer GitHub issues, remove all this text and ask your question here.

There is a question about clickhouse-copier:(the version is v21.7.18)
 <Error> Application: Will retry: Code: 44, e.displayText() = DB::Exception: Cannot create table with column 'mmap' which type is 'Map(String,UInt64)' because experimental Map type is not allowed. Set 'allow_experimental_map_type = 1' setting to enable, Stack trace (when copying this message, always include the lines below):

I put 'allow_experimental_map_type' in 'config.xml',but it is unuseful.
What am I supposed to do with 'allow_experimental_map_type'?

**Comment by den-crane** [comment]
1. 21.7 is out support. Upgrade to 22.2.
2. allow_experimental_map_type is user's setting.

```xml
cat /etc/clickhouse-server/users.d/allow_experimental_map_type.xml
<?xml version="1.0" ?>
<yandex>
    <profiles>
        <default>
            <allow_experimental_map_type>1</allow_experimental_map_type>
        </default>
    </profiles>
</yandex>
```
https://kb.altinity.com/altinity-kb-setup-and-maintenance/altinity-kb-server-config-files/
