### ISSUE TITLE
How to compile the clickhouse-v20.11.4.13-stable with gcc and libstdc++ instead of libc++

### ISSUE THREAD

**Issue by starrysky9959** [ClickHouse/ClickHouse#35246]

**Comment by alexey-milovidov** [comment]
It is not possible.

**Comment by alexey-milovidov** [comment]
The main asset of ClickHouse is our set of test suites and continuous integration system.
With our tests, including randomized tests, we find and fix bugs in most of third-party open-source libraries.

To ensure that ClickHouse is stable and secure, the only way is to build it with exactly the same versions of libraries with exactly the same patches as we do.

If you don't know, it's difficult to imagine how many bugs (race conditions, memory safety issues) exist in C++ libraries.

**Comment by starrysky9959** [comment]
Thanks!
