### ISSUE TITLE
The libc.so in sysroot not an elf file

### ISSUE THREAD

**Issue by zhanghuajieHIT** [ClickHouse/ClickHouse#35252]
The libc.so in contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc/usr/lib64 not an elf file. Should we fix it?

![image](https://user-images.githubusercontent.com/22310751/158092335-982bcc7f-477b-4d13-8a0c-bd8720b4edcc.png)

**Comment by amosbird** [comment]
It's a gnu linker script (text file).
