### ISSUE TITLE
Does UDF can achieve user defined aggregate function?

### ISSUE THREAD

**Issue by standchan** [ClickHouse/ClickHouse#35258]
> Make sure to check documentation https://clickhouse.yandex/docs/en/ first. If the question is concise and probably has a short answer, asking it in Telegram chat https://telegram.me/clickhouse_en is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

> If you still prefer GitHub issues, remove all this text and ask your question here.

**Comment by kitaisreal** [comment]
The only possible way for now is to use ExecutableStorage, that way you can potentially aggregate data from multiple input streams into single output, but interface is not very convenient.
