### ISSUE TITLE
Clickhouse MergeFromLogEntryTask: Code: 74. DB::ErrnoException: Cannot read from file

### ISSUE THREAD

**Issue by rishabh-shah12** [ClickHouse/ClickHouse#35259]
CH is running on VM base (ubuntu)

I have upgraded CH version form **20.8.12.2 ⇾ 21.12.4.1** 

After upgrading, we are getting this error on some node (instance).

`MergeFromLogEntryTask: virtual bool DB::ReplicatedMergeMutateTaskBase::executeStep(): Code: 74. DB::ErrnoException: Cannot read from file /mnt/local/clickhouse/data/default/Metrics/e4ff46e55238867b9ad76fa7f690df39_0_6410_8_7603/appId.bin, errno: 22, strerror: Invalid argument: (while reading column appId): (while reading from part /mnt/local/clickhouse/data/default/Metrics/e4ff46e55238867b9ad76fa7f690df39_0_6410_8_7603/ from mark 49842 with max_rows_to_read = 8192): While executing MergeTreeSequentialSource. (CANNOT_READ_FROM_FILE_DESCRIPTOR), Stack trace (when copying this message, always include the lines below):
0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa21a61a in /usr/bin/clickhouse`

**Comment by alesapin** [comment]
Hi! Please send directory `e4ff46e55238867b9ad76fa7f690df39_0_6410_8_7603` and table schema.

**Comment by alexey-milovidov** [comment]
The info has not been provided.
