### ISSUE TITLE
users with allow_databases unable to query system.dictionaries

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#35250]
Connected to ClickHouse server version 22.2.2 revision 54455.

```sql
create table source(id UInt64, attr String) Engine=MergeTree order by id;
insert into source values(1, '1'),(2,'2');

CREATE DICTIONARY dict ( id UInt64, attr String ) 
PRIMARY KEY id SOURCE(CLICKHOUSE(TABLE source))
LIFETIME(MIN 0 MAX 0) LAYOUT(HASHED());


cat /etc/clickhouse-server/users.d/u.xml
<?xml version="1.0"?>
<clickhouse>
    <users>
        <u>
            <password>u</password>
            <profile>default</profile>
            <quota>default</quota>
        </u>
    <users>
</clickhouse>


clickhouse-client -u u --password=u -q "select count() from system.dictionaries where name='dict'"
1     --- expected
```

Let's add allow_databases
```sql
cat u.xml
<?xml version="1.0"?>
<yandex>
    <users>
        <u>
            <password>u</password>
            <profile>default</profile>
            <quota>default</quota>
            <allow_databases>
                  <database>default</database>
                  <database>system</database>
            </allow_databases>
        </u>
   </users>
</yandex>


clickhouse-client -u u --password=u -q "select count() from system.dictionaries where name='dict'"
0     --- unexpected
```

no issue in 20.8.17.25.
any dictionary XML, SQL.
any database.

**Comment by beda42** [comment]
This seems to be related to #42137 - both `system.dictionaries` and `SHOW DICTIONARIES FROM` seem empty unless `SHOW DICTIONARIES ON *.*` is granted.

In effect, this means that users created with `allow_databases` in `'users.xml` cannot be made to see any dictionaries as it is impossible to grant them additional privileges in SQL and there seems to be no syntax to do it in `users.xml` :frowning_face:

**Comment by pufit** [comment]
> In effect, this means that users created with allow_databases in 'users.xml cannot be made to see any dictionaries as it is impossible to grant them additional privileges in SQL and there seems to be no syntax to do it in users.xml ☹️

There is such syntax now:
https://clickhouse.com/docs/en/operations/settings/settings-users#grants-user-setting
