### ISSUE TITLE
Mutex in ReadBufferFromHDFS has bad effect on perfomance, can we remove it？

### ISSUE THREAD

**Issue by shuchaome** [ClickHouse/ClickHouse#35292]
[mutex](https://github.com/ClickHouse/ClickHouse/blob/435d60c9e9b5835856cd8c99abbf109a97ec5912/src/Storages/HDFS/ReadBufferFromHDFS.cpp#L26) 

The comment says that HDFS create/open functions are not thread safe, but i did not find the detail in libhdfs3.
Can we remove it，or any way to improve？

**Comment by lgbo-ustc** [comment]
All I found that relates to this is
https://issues.apache.org/jira/browse/HAWQ-1210

Do ClickHouse have meet something like that? @alesapin

**Comment by shuchaome** [comment]
related pr #15675

**Comment by zhanglistar** [comment]
![image](https://user-images.githubusercontent.com/985418/160092891-89b5de1b-ede3-428d-9c03-8f5f8e09bad0.png)
Here is not thread safe, but it is easy to fix, just remove the init code to init process, and latter function just read the structure without modifying.
