### ISSUE TITLE
Popups on Woboq are not usable

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#35303]
Thanks, but there's an issue, I was able to move cursor to the link on the popup window when mouse over a variable in previous URL.
When I use this new link,  if I move cursor , the popup disappeared , so I am not able to go to the reference on the popup.

_Originally posted by @kashwy in https://github.com/ClickHouse/ClickHouse/issues/34948#issuecomment-1056091617_

**Comment by kashwy** [comment]
Hi, can this issue be fixed ? the popups are very useful when reading the code


Thanks

**Comment by alexquuie** [comment]
is this fixed? I'm still facing the same issue

**Comment by Felixoid** [comment]
A fixed show/hide function from https://github.com/ClickHouse/woboq_codebrowser/pull/10 is deployed manually to https://s3.amazonaws.com/clickhouse-test-reports/codebrowser/ClickHouse/src/Access/AccessBackup.h.html#DB::BackupPtr, so you can check if is it fixed. The fix will become permanent after the mentioned PR is merged

**Comment by alexquuie** [comment]
> is this fixed? I'm still facing the same issue

I tried and now it works! Awesome
