### ISSUE TITLE
destructor of 'Logger' is protected and virtual

### ISSUE THREAD

**Issue by varadarajkumar** [ClickHouse/ClickHouse#35322]
(you don't have to strictly follow this form)

**Describe the bug**
Clang-tidy reported as Medium. Logger is part of POCO Foundation and its a different repo.

**How to reproduce**
clang-tidy report

**Error message and/or stacktrace**
![image](https://user-images.githubusercontent.com/65994812/158593799-ce1fcdf0-f0e1-4af2-a2f2-f9ffed60d17b.png)

**Comment by kitaisreal** [comment]
@varadarajkumar it is okay for Logger to have protected virtual destructor, because we want to destroy logger only throught subclass destructor.
