### ISSUE TITLE
How can I check the insertion rate?

### ISSUE THREAD

**Issue by q0987** [ClickHouse/ClickHouse#35331]
Does click house provide a way so that I can check the insertion rate(i.e. bytes per second)?

_Received exception from Server (version 21.4.6):
Code: 252. DB::Exception: Received from 127.0.0.1:9000. DB::Exception: Too many parts (305). Parts cleaning are processing significantly slower than inserts._

I start to see the above errors and based on my understanding, the issue was caused by inserting too much data too fast.

Question> Does ClickHouseDB have some internal monitors/logs/traces where I can check the insertion rate when the above issues happen?

FYI:
I have installed the TABiX and it has some Metrics, but I don't know whether it offers such a monitor.

Thank you

**Comment by jeandeniscosta** [comment]
You can have interesting metadata on Insertions by looking at the query_log:
`SELECT top 10 *
FROM system.query_log
WHERE query_kind = 'Insert' -- filter on insertions
and type='QueryFinish' -- filter on finished ones to have metrics like nbLines, bytes, etc.
and event_time > addHours(now(), -1) -- table can be big, the select * of my exemple is costly, you should probably do some aggregation anyway
order by event_time desc`

The system.merges table also displays pending merges, which will block your inserts

**Comment by den-crane** [comment]
```sql
select database, table, event_type, partition_id, count() c, round(avg(rows)) from system.part_log where event_date >= today() and event_type = 'NewPart'
group by database, table, event_type, partition_id
order by c desc
```

**Comment by melvynator** [comment]
> I start to see the above errors and based on my understanding, the issue was caused by inserting too much data too fast.

Yes this is the most frequent cause for this error. 

To answer a few of your other questions: 

> Does ClickHouseDB have some internal monitors/logs/traces where I can check the insertion rate when the above issues happen?

The `clickhouse-client` by default will give you a few information about the ingesting speed. But this is not directly related to the number of parts that are going to be created. 

A few recommendation for your problem when it comes to avoiding the creation of too many parts:

1. You can use the buffer table to avoid having too many parts: https://clickhouse.com/docs/en/engines/table-engines/special/buffer/ 
2. You can also enable async insert: https://clickhouse.com/docs/en/operations/settings/settings/#async-insert

**Comment by q0987** [comment]
I have a question regarding the `async_insert`.

Based on the documentation, `async_insert` only works for HTTP protocol. Currently, I am using TCP protocol through the following command 

`cat abc.clickhouse | /usr/bin/clickhouse-client --query="INSERT INTO tableabc(....)" --host=127.0.0.1 --port=9000`

Also, each data file is around 600MB with 65K rows. Based on my understanding, this added feature is specific for small insertion.

**Question**> Is it true that this feature will not help in my case?

Thank you

**Comment by den-crane** [comment]
@q0987 You don't need async_insert for 600MB batches. 
async_insert can improve very small inserts, like 10KB.
