### ISSUE TITLE
Distinct vs Limit

### ISSUE THREAD

**Issue by Fallenyasha** [ClickHouse/ClickHouse#35350]
Хотелось бы понять, почему запросы возвращают разный результат, т.е. результат фактически зависит от порядка данных, что кажется невалидным:
```
select distinct a from (
    select 10 as a, 20 as b union all
    select 11 as a, 20 as b union all
    select 10 as a, 21 as b
)
order by a desc
limit 1 by b
```
возвращает только одну строку 11

```
select distinct a from (
    select 10 as a, 21 as b union all
    select 10 as a, 20 as b union all
    select 11 as a, 20 as b
)
order by a desc
limit 1 by b
```
возвращает 2 строки, 10 и 11

И есть ли способ исправить данные запросы, чтобы результат был детерменирован?

Версия КХ 22.1.2.2

**Comment by den-crane** [comment]
На самом деле непонятно как это должно работать, сначала limit потом distinct или сначала distinct потом limit

я бы написал

```sql
select distinct a from (
         select  a from (
           select 10 as a, 21 as b union all
           select 10 as a, 20 as b union all
           select 11 as a, 20 as b
         )
         order by a desc
         limit 1 by b
)
```

**Comment by Fallenyasha** [comment]
А каков порядок выполнения операторов? order by -> distinct -> limit by? или иной?

**Comment by den-crane** [comment]
да order by -> distinct -> limit by
