### ISSUE TITLE
memory used gradually rises

### ISSUE THREAD

**Issue by amy108** [ClickHouse/ClickHouse#35351]
![CZNloLYko4](https://user-images.githubusercontent.com/48902828/158775499-d68641d3-bfab-4d3f-a7a0-6cf10feecf61.png)
as the picture says，clickhouse server memory gradually rises and never goes down. i dont know the reason.

**Comment by lichenglin** [comment]
In fact , I have met the same situation.
`select version()`
┌─version()─┐
│ 22.2.2.1  │
└───────────┘
`select *,formatReadableSize(value) from system.asynchronous_metrics where  metric ilike '%mem%'`
┌─metric────────────────────┬───────value─┬─formatReadableSize(value)─┐
│ MemoryDataAndStack        │ 61178953728 │ 56.98 GiB                 │
│ OSMemoryFreeWithoutCached │ 18921803776 │ 17.62 GiB                 │
│ OSMemoryTotal             │ 33006567424 │ 30.74 GiB                 │
│ OSMemoryCached            │  5173174272 │ 4.82 GiB                  │
│ MemoryShared              │    83656704 │ 79.78 MiB                 │
│ MemoryCode                │   455340032 │ 434.25 MiB                │
│ MemoryResident            │  6009040896 │ 5.60 GiB                  │
│ MemoryVirtual             │ 62242316288 │ 57.97 GiB                 │
│ OSMemoryAvailable         │ 24180281344 │ 22.52 GiB                 │
│ OSMemoryFreePlusCached    │ 24094978048 │ 22.44 GiB                 │
└───────────────────────────┴─────────────┴───────────────────────────┘
`SELECT database, table, sum(rows) rows, count() part_count, sum(marks) count_marks, formatReadableSize(sum(marks_bytes)) marks_size,
    formatReadableSize(sum(primary_key_bytes_in_memory)) AS bytes_in_memory,
    formatReadableSize((sum(primary_key_bytes_in_memory_allocated)) as s) AS bytes_in_memory_allocated
FROM system.parts
group by  database, table
order by s desc
limit 10;`

┌─database────────────┬─table───────────────────────────┬───────rows─┬─part_count─┬─count_marks─┬─marks_size─┬─bytes_in_memory─┬─bytes_in_memory_allocated─┐
│ amazong_pacvue_test │ ChangeEventDailyLogV2           │ 2154791657 │         79 │      263240 │ 102.42 MiB │ 6.53 MiB        │ 9.41 MiB                  │
│ instacart_pacvue    │ MonitorKeywordSearchLog         │  654591256 │        111 │       80382 │ 55.15 MiB  │ 5.21 MiB        │ 8.39 MiB                  │
│ cdc_log             │ cdc_detail                      │  201704706 │        243 │       26543 │ 9.06 MiB   │ 1.51 MiB        │ 5.64 MiB                  │
│ amazong_pacvue_test │ dayreportKeyword                │ 1427043200 │        192 │      175887 │ 478.72 MiB │ 3.02 MiB        │ 4.99 MiB                  │
│ amazong_pacvue_test │ fead_sp_traffic                 │  170483350 │         20 │       20916 │ 10.05 MiB  │ 2.48 MiB        │ 4.03 MiB                  │
│ amazong_pacvue_test │ dayreportKeywordQuery           │  347212622 │        189 │       42917 │ 91.69 MiB  │ 2.01 MiB        │ 3.80 MiB                  │
│ amazong_pacvue_test │ MonitorKeyword_SearchSpaLog     │  584166724 │         72 │       71512 │ 35.98 MiB  │ 2.25 MiB        │ 3.58 MiB                  │
│ system              │ asynchronous_metric_log         │ 2389396269 │        143 │      291910 │ 40.08 MiB  │ 1.67 MiB        │ 3.20 MiB                  │
│ amazong_pacvue_test │ dayreportProductAd              │  788821119 │        209 │       97243 │ 208.95 MiB │ 1.67 MiB        │ 3.00 MiB                  │
│ amazong_pacvue_test │ MonitorKeyword_SearchSpaLog_bak │  285911433 │         15 │       34974 │ 17.61 MiB  │ 1.86 MiB        │ 2.69 MiB                  │
└─────────────────────┴─────────────────────────────────┴────────────┴────────────┴─────────────┴────────────┴─────────────────┴───────────────────────────┘

![image](https://user-images.githubusercontent.com/8294900/159901712-502df1bc-b2ea-4f86-8799-18b585359f80.png)

I upgrade clickhouse from  21.11.2.1 to  22.2.2.1 at 3/18 .

you can see mem increase after that

**Comment by amy108** [comment]
![image](https://user-images.githubusercontent.com/48902828/173763942-cd18ad66-1833-491a-b1e2-97d733fc86d9.png)
![image](https://user-images.githubusercontent.com/48902828/173764046-0df77058-d0e7-456e-80f1-755d67e81a48.png)
it worked when execute system drop mark cache,  but if it's manual operation every time only?

**Comment by den-crane** [comment]
20.7 is out support. Use 22.3 or 22.5.

This is expected behaviour mark cache max size by default is 5GB. 
Just change `<mark_cache_size>5368709120</mark_cache_size>` in config.xml to smaller value.
