### ISSUE TITLE
How to restore click house node from cluster

### ISSUE THREAD

**Issue by 5centscdn** [ClickHouse/ClickHouse#35353]
We are using ClickHouse with 3 replica and 1 shard (3 node).  due to hardware failure we have replace one node from ClickHouse cluster. We are using inbuilt ClickHouse keeper instead of zoo keeper. How to restore failed databases and tables which is using Distributed engine. Is there any documentation available for replacing or restoring node in ClickHouse cluster?

**Comment by den-crane** [comment]
CH Keeper will fetch automatically own database from other Keeper nodes (all Keeper nodes have the same data).

https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/replication/#recovery-after-complete-data-loss
