### ISSUE TITLE
LIVE VIEW DB::Exception: Not found column in(fingerprint, _subquery433) in block

### ISSUE THREAD

**Issue by akvlad** [ClickHouse/ClickHouse#35362]
Error: NOT_FOUND_COLUMN_IN_BLOCK for LIVE VIEW (possibly with Merge tables)

Version: docker clickhouse/clickhouse-server:22.2.3.5

**How to reproduce**

- open clickhouse-client
- run the following commands:

```
create database test1

use test1

set allow_experimental_live_view=1

CREATE TABLE IF NOT EXISTS time_series (
  date Date,
  fingerprint UInt64,
  labels String, 
  name String
) ENGINE = ReplacingMergeTree(date) PARTITION BY date ORDER BY fingerprint

CREATE TABLE IF NOT EXISTS samples_v3
    (
      fingerprint UInt64,
      timestamp_ns Int64 CODEC(DoubleDelta),
      value Float64 CODEC(Gorilla),
      string String
    ) ENGINE = MergeTree
    PARTITION BY toStartOfDay(toDateTime(timestamp_ns / 1000000000))
    ORDER BY (timestamp_ns)

CREATE TABLE IF NOT EXISTS samples_read
   (fingerprint UInt64,timestamp_ms Int64,value Float64,string String)
   ENGINE=Merge('test1', '^(samples|samples_v2)$')

CREATE TABLE IF NOT EXISTS samples_read_v2_2
(fingerprint UInt64,timestamp_ns Int64,value Float64,string String)
ENGINE=Merge('test1', '^(samples_read_v2_1|samples_v3)$')

CREATE LIVE VIEW lv_3379620598786728097 WITH TIMEOUT 10 AND PERIODIC REFRESH 5 AS
WITH
    str_sel AS
    (
        SELECT DISTINCT
            fingerprint,
            JSONExtractKeysAndValues(labels, 'String') AS labels
        FROM time_series AS time_series
        WHERE JSONExtractString(time_series.labels, 'test_id') = '_TEST_'
    ),
    main AS
    (
        SELECT
            samplos_rr.fingerprint AS fingerprint,
            str_sel.labels AS labels,
            samplos_rr.string AS string,
            samplos_rr.timestamp_ns AS timestamp_ns
        FROM samples_v3 AS samplos_rr
        LEFT JOIN str_sel ON samplos_rr.fingerprint = str_sel.fingerprint
        WHERE (samplos_rr.timestamp_ns > ((toUnixTimestamp(now()) - 36000) * 1000000000)) AND (samplos_rr.timestamp_ns <= (toUnixTimestamp(now()) * 1000000000)) AND (samplos_rr.fingerprint IN (
            SELECT fingerprint AS fingerprint
            FROM str_sel
        ))
        ORDER BY samplos_rr.timestamp_ns DESC
    )
SELECT
    *
FROM main
ORDER BY
    labels ASC,
    timestamp_ns ASC

WATCH lv_3379620598786728097
```
- open the second clickhouse-client and run the following commands
```
use test1

INSERT INTO time_series (fingerprint, date, labels) VALUES (1234, '2022-03-17', '{"test_id":"_TEST_"}')

INSERT INTO samples_v3 (fingerprint, timestamp_ns, string) VALUES (1234, toUnixTimestamp(now()) * 1000000000, 'MSG2')

INSERT INTO samples_v3 (fingerprint, timestamp_ns, string) VALUES (1234, toUnixTimestamp(now()) * 1000000000, 'MSG2')
```

**Expected behavior**

> Both inserts should finish successfully

**Error message and/or stacktrace**

After the second insert I receive an error:
`Code: 10. DB::Exception: Received from localhost:9000. DB::Exception: Not found column in(fingerprint, _subquery433) in block: while pushing to view test1.lv_3379620598786728097 (aeb83b00-e59a-4d6c-acaf-2731c576b72f). (NOT_FOUND_COLUMN_IN_BLOCK)`

**Comment by sylvinho81** [comment]
Hi @akvlad. Not sure if you found a solution for this issue.  I had a similar issue and I fixed it by creating a [Normal View](https://clickhouse.com/docs/en/sql-reference/statements/create/view/) and put there the query that I need to perform. 

In your case encapsulate the next piece of code in a Normal View:

`WITH
    str_sel AS
    (
        SELECT DISTINCT
            fingerprint,
            JSONExtractKeysAndValues(labels, 'String') AS labels
        FROM time_series AS time_series
        WHERE JSONExtractString(time_series.labels, 'test_id') = '_TEST_'
    ),
    main AS
    (
        SELECT
            samplos_rr.fingerprint AS fingerprint,
            str_sel.labels AS labels,
            samplos_rr.string AS string,
            samplos_rr.timestamp_ns AS timestamp_ns
        FROM samples_v3 AS samplos_rr
        LEFT JOIN str_sel ON samplos_rr.fingerprint = str_sel.fingerprint
        WHERE (samplos_rr.timestamp_ns > ((toUnixTimestamp(now()) - 36000) * 1000000000)) AND (samplos_rr.timestamp_ns <= (toUnixTimestamp(now()) * 1000000000)) AND (samplos_rr.fingerprint IN (
            SELECT fingerprint AS fingerprint
            FROM str_sel
        ))
        ORDER BY samplos_rr.timestamp_ns DESC
    )
`

And then just use the Normal View in the CREATE LIVE VIEW statement.

**Comment by akvlad** [comment]
@sylvinho81 I have avoided this issue. I think this is about the depth of the subrequest tree. I removed the main `SELECT *` and used the `main` CTE instead.  Then the exception disappeared.

But this is definitely a bug. And the described procedure 100% reproduces it for me.

**Comment by alexey-milovidov** [comment]
LIVE VIEW is non production feature. It is not supported and most likely will be removed altogether.

**Comment by lmangani** [comment]
@alexey-milovidov is there a deprecation notice for LIVE VIEW? We understand experimental features are never guaranteed to land in production but it seems otherwise natural to file bug reports for anything that's out there for testing regardless.

**Comment by alexey-milovidov** [comment]
This feature will stay in the codebase for some time.
I'm closing this issue only to make room and prioritize other issues.
