### ISSUE TITLE
Decimal data corruption when upcasting NULL

### ISSUE THREAD

**Issue by EdToro74** [ClickHouse/ClickHouse#35367]
When upcasting a NULL decimal value, other rows have their values corrupted.

> A clear and concise description of what works not as it is supposed to.

I went down a rabbit hole when creating some rollups recently and ended up writing something that showed very odd behavior.  I realize now that the solution to my initial need was much simpler than I thought but I figured I'd still show the bug here in case it affects anyone or causes server instability.

**Does it reproduce on recent release?**

apt-get says 22.2.3.5 is the latest but after installation the server reports as 22.2.3.1.

**Enable crash reporting**

Crash reporting is enabled.

**How to reproduce**

Run the following query, observe that the first column of the non-NULL row has data corruption, usually represented by a very large number.  The number is usually different on every invocation.

```
SELECT if(v IS NOT NULL AND v != 0, v, CAST(NULL, 'Nullable(Decimal(18, 4))')) default_to_NULL_cast,
       if(v IS NOT NULL AND v != 0, v, NULL)                                   default_to_NULL_no_cast
FROM (
         SELECT CAST(2, 'Decimal(9,4)') v
         UNION ALL
         SELECT NULL
         ) d;
```

Running the query without the NULL value in the source data produces the correct results:

```
SELECT if(v IS NOT NULL AND v != 0, v, CAST(NULL, 'Nullable(Decimal(18, 4))')) default_to_NULL_cast,
       if(v IS NOT NULL AND v != 0, v, NULL)                                   default_to_NULL_no_cast
FROM (
         SELECT CAST(2, 'Decimal(9,4)') v
         ) d;

```

**Expected behavior**

Both columns in the non-NULL row of data should have a value of `2`.

**Comment by den-crane** [comment]
`select version();`

It throws an error in 22.2.3.1.

```
SELECT
    if((v IS NOT NULL) AND (v != 0), v, CAST(NULL, 'Nullable(Decimal(18, 4))')) AS default_to_NULL_cast,
    if((v IS NOT NULL) AND (v != 0), v, NULL) AS default_to_NULL_no_cast
FROM
(
    SELECT CAST(2, 'Decimal(9,4)') AS v
    UNION ALL
    SELECT NULL
) AS d

Query id: f2517eef-a9c8-411a-a0ab-e0bd130fffa6


0 rows in set. Elapsed: 0.002 sec.

Received exception from server (version 22.2.3):
Code: 49. DB::Exception: Received from localhost:9000. DB::Exception: Bad cast from type DB::ColumnDecimal<DB::Decimal<int> > to DB::ColumnDecimal<DB::Decimal<long> >. (LOGICAL_ERROR)
```

and works correctly if both branches are cast

```
SELECT if(v IS NOT NULL AND v != 0, CAST(v,'Nullable(Decimal(18, 4))'), CAST(NULL, 'Nullable(Decimal(18, 4))')) default_to_NULL_cast,
       if(v IS NOT NULL AND v != 0, v, NULL)                                   default_to_NULL_no_cast
FROM (
         SELECT CAST(2, 'Decimal(9,4)') v UNION ALL SELECT NULL
         ) d;
┌─default_to_NULL_cast─┬─default_to_NULL_no_cast─┐
│                 ᴺᵁᴸᴸ │                    ᴺᵁᴸᴸ │
└──────────────────────┴─────────────────────────┘
┌─default_to_NULL_cast─┬─default_to_NULL_no_cast─┐
│                    2 │                       2 │
└──────────────────────┴─────────────────────────┘
```

**Comment by Avogar** [comment]
The bug is in function `if`. Best way to reproduce it:
```
SELECT if(materialize(1) > 0, CAST(NULL, 'Nullable(Int64)'), materialize(toInt32(1)))
```
It leads to
```
Logical error: 'Bad cast from type DB::ColumnVector<int> to DB::ColumnVector<long>'.
``` 
Will fix it.
