### ISSUE TITLE
Map operations

### ISSUE THREAD

**Issue by petar-dambovaliev** [ClickHouse/ClickHouse#35416]
How to delete/append to a map?

If i have a column as `map{"a" => 1, "b" => 2}`
How can i delete `"b" => 2` or add `"c" => 3` ?
And even merge this with a map from another row?

**Comment by e-mars** [comment]
hi @petar-dambovaliev ,
I'm not seeing that it currently possible, however, i may be misunderstanding which and how map functions are being used.
could you send me an example of the definitions and row syntax you are using?
is it something like this?
```
create table db2.table6 
(
  id UInt64,
  column1 Map(String, UInt64)
)
ENGINE = MergeTree
ORDER BY (id);

INSERT INTO db2.table6 
VALUES 
(1,{'a':1, 'b':2})
(2,{'a':3, 'b':4});
```
thanks.

**Comment by petar-dambovaliev** [comment]
> hi @petar-dambovaliev , I'm not seeing that it currently possible, however, i may be misunderstanding which and how map functions are being used. could you send me an example of the definitions and row syntax you are using? is it something like this?
> 
> ```
> create table db2.table6 
> (
>   id UInt64,
>   column1 Map(String, UInt64)
> )
> ENGINE = MergeTree
> ORDER BY (id);
> 
> INSERT INTO db2.table6 
> VALUES 
> (1,{'a':1, 'b':2})
> (2,{'a':3, 'b':4});
> ```
> 
> thanks.

Yes, that is the schema.
How can i take the map from one row and insert those values into a map in another row?
In a single query, without fetching the data over the network.
There seem to be some kind of an update operation on maps https://clickhouse.com/docs/en/sql-reference/functions/tuple-map-functions/#function-mappopulateseries
So i don't see it being a problem to have other update operations.

**Comment by e-mars** [comment]
Hi @petar-dambovaliev .

i'm still a little unclear about some of the data goals (my fault) but I think the following examples are close to what you are looking for.
These new map functions were added in the latest version, `22.3.2.1`:
[2022-03 Release Notes](https://clickhouse.com/docs/en/whats-new/changelog/#:~:text=Add%20three%20functions,Map.%20%2333698%20(hexiaoting).)
(NOTE: in the release notes, the `mapReplace` was renamed to `mapUpdate` and `mapMap` was renamed to `mapApply`.  we'll be updating our docs to reflect the change)

* assuming we have the following table:
```
CREATE TABLE db1_map.table1 
(
  id UInt64,
  column1 Map(String, UInt64),
  column2 Map(String, UInt64)
)
ENGINE = MergeTree
ORDER BY (id);

INSERT INTO db1_map.table1 
(id, column1, column2)
VALUES 
(1,{'a':1, 'b':2}, {'c':3})
(2,{'a':4, 'b':5, 'd':6}, {'c':3});
```

* to filter out map `{'b':2}`  :  

```
ch_env_2 :) SELECT id, column1, mapFilter(("b", v) -> (v != 2), column1) as column1_new FROM db1_map.table1
            ORDER BY id ASC;

SELECT
    id,
    column1,
    mapFilter((b, v) -> (v != 2), column1) AS column1_new
FROM db1_map.table1
ORDER BY id ASC

Query id: 39a2ddaf-199e-497c-81da-0426c666d96a

┌─id─┬─column1─────────────┬─column1_new─────────┐
│  1 │ {'a':1,'b':2}       │ {'a':1}             │
│  2 │ {'a':4,'b':5,'d':6} │ {'a':4,'b':5,'d':6} │
└────┴─────────────────────┴─────────────────────┘

```

* to update a map with a new added value (in this example, just adding map from column2 to column1):

```
ch_env_2 :) SELECT id, column1, mapUpdate(column1, column2) AS column1_new FROM db1_map.table1
            ORDER BY id ASC;

SELECT
    id,
    column1,
    mapUpdate(column1, column2) AS column1_new
FROM db1_map.table1
ORDER BY id ASC

Query id: a8ec463c-f18c-43e3-a060-647402fa064e

┌─id─┬─column1─────────────┬─column1_new───────────────┐
│  1 │ {'a':1,'b':2}       │ {'a':1,'b':2,'c':3}       │
│  2 │ {'a':4,'b':5,'d':6} │ {'a':4,'b':5,'d':6,'c':3} │
└────┴─────────────────────┴───────────────────────────┘
```

* to update the maps values from one row to another row:

```
ch_env_2 :) select id, column1, mapUpdate(column1,(SELECT column1
            FROM db1_map.table1
            WHERE id = 2)) AS column1_new
            from db1_map.table1
            where id=1;

SELECT
    id,
    column1,
    mapUpdate(column1, (
        SELECT column1
        FROM db1_map.table1
        WHERE id = 2
    )) AS column1_new
FROM db1_map.table1
WHERE id = 1

Query id: 5eff1ec6-4348-4252-a7b0-9339ebc73f41

┌─id─┬─column1───────┬─column1_new─────────┐
│  1 │ {'a':1,'b':2} │ {'a':4,'b':5,'d':6} │
└────┴───────────────┴─────────────────────┘

```

thanks.
