### ISSUE TITLE
Concerns and performance of using view as table `alias`

### ISSUE THREAD

**Issue by rmanisthebest** [ClickHouse/ClickHouse#35427]
We are looking for a solution that do not need to change much coding or having downtime when we alter/have new MergeTree table settings (including adding new columns or change Primary keys). So, we are considering using View as an alias of our target table to prevent downtime/changing table name in our coding, sth like `create view target_view as select * from target_v1`

We would constantly insert events into the target table, and create some materialised view with diff engines from this target mergetree table.

May i ask would it have any concerns or performance issue when i am doing that?

**Comment by den-crane** [comment]
>May i ask would it have any concerns or performance issue when i am doing that?

Yes. It's very bad from performance perspective.

I suggest Engine=Merge
see example 2 https://clickhouse.com/docs/en/engines/table-engines/special/merge/#examples
