### ISSUE TITLE
Where is replication logs from MaterializedPostgreSQL?

### ISSUE THREAD

**Issue by Olga-par** [ClickHouse/ClickHouse#35447]
Hello!

We use postgresql replication in clickhouse through the creation of MaterializedPostgreSQL. But replication doesn't work.
In clickhouse logs no error in replication. In table pg_replication_slots slots are not active. We used command 

CREATE DATABASE IF NOT EXISTS name_database
ENGINE = MaterializedPostgreSQL(
    'host:port',
    'database',
    'user',
    'password'
)
SETTINGS materialized_postgresql_allow_automatic_update=1,
         materialized_postgresql_tables_list ='table1, table, table3';
 
Why replication doesn't work? Where could we see logs of replication?

version clickhouse client 21.11.5.33
version clickhouse server 22.3.2

**Comment by melvynator** [comment]
Thanks for creating this issue. Which version of PostgreSQL are you using? Also when you are reffering to the replication, are you talking about the replication between ClickHouse and PostgreSQL or within ClickHouse itself?

**Comment by Olga-par** [comment]
Thank you for answer. Version PostgreSQL 10.17 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 7.3.1 20180712 (Red Hat 7.3.1-12), 64-bit. I talk about the replication between ClickHouse and PostgreSQL

**Comment by Olga-par** [comment]
This problem is very important. @melvynator When can we answer my question?

**Comment by e-mars** [comment]
Hi @Olga-par ,

I've been assigned to this question.

basically, I've been testing with PostgreSQL 10 and I've tested the configuration and functionality.
It does not work with versions <12 and  currently do not have plans to backport compatibility.
your postgresql instance would need to be upgraded.

However, I did test with version 12.

below is a preview of the new documentation pages we will have and is something that you can test.
could you review, provide any feedback after testing?


# Connecting ClickHouse to PostgreSQL using the MaterializedPostgreSQL database engine

The PostgreSQL database engine uses the Postgres replication features to create a replica of the database with all or a subset of schemas and tables. 
This article is to illustrate basic methods of integration sing one database, one schema and one table.

***In the following procedures, the Postgres CLI (psql) and the ClickHouse CLI (clickhouse-client) are used. The PostgreSQL server is installed on linux. The following has minimum settings if the postgresql database is new test install***

## 1. In PostgreSQL
1.  In `postgresql.conf`, set minimum listen levels, replication wal level and replication slots:

add the following entries:
```
listen_addresses = '*' 
max_replication_slots = 10
wal_level = logical
```
_*ClickHouse needs minimum of `logical` wal level and minimum `2` replication slots_

2. Using an admin account, create a user to connect from ClickHouse:
```sql
CREATE ROLE clickhouse_user SUPERUSER LOGIN PASSWORD 'ClickHouse_123';
```
_*for demonstration purposes, full superuser rights have been granted._


3. create a new database:
```sql
CREATE DATABASE db1;
```

4. connect to the new database in `psql`:
```
\connect db1
```

5. create a new table:
```sql
CREATE TABLE table1 (
    id         integer primary key,
    column1    varchar(10)
);
```

6. add initial rows:
```sql
INSERT INTO table1
(id, column1)
VALUES
(1, 'abc'),
(2, 'def');
```

7. Configure the Postgres to allow connections to the new database with the new user for replication:
below is the minimum entry to add to the `pg_hba.conf` file:
```
# TYPE  DATABASE        USER            ADDRESS                 METHOD
host    db1             clickhouse_user 192.168.1.0/24          password
```
_*for demonstration purposes, this is using clear text password authentication method. update the address line with either the subnet or the address of the server per PostgreSQL documentation_

8. reload the `pg_hba.conf` configuration with ssomething like this (adjust for your version):
```
/usr/pgsql-12/bin/pg_ctl reload
```

9. Test the login with new `clickhouse_user`:
```
 psql -U clickhouse_user -W -d db1 -h <your_postgresql_host>
```

## 2. In ClickHouse
1. log into the ClickHouse CLI
```
clickhouse-client --user default --password ClickHouse123!
```

2. Enable the PosgreSQL experimental feature for the database engine:
```sql
SET allow_experimental_database_materialized_postgresql=1
```

3. Create the new database to be replicated and define the intitial table:
```sql
CREATE DATABASE db1_postgres
ENGINE = MaterializedPostgreSQL('postgres-host.domain.com:5432', 'db1', 'clickhouse_user', 'ClickHouse_123')
SETTINGS materialized_postgresql_tables_list = 'table1';
```
minimum options:

|parameter|Description                 |example              |
|---------|----------------------------|---------------------|
|host:port|hostname or IP and port     |postgres-host.domain.com|
|database |postgres database name         |db1                  |
|user     |username to connect to postgres|clickhouse_user     |
|password |password to connect to postgres|ClickHouse_123       |
|settings |additional settings for the engine| materialized_postgresql_tables_list = 'table1'|

**For complete guide to the PostgreSQL database engine, refer to: **
https://clickhouse.com/docs/en/engines/database-engines/materialized-postgresql/#settings

4. Verify initial table has data
```sql
ch_env_2 :) select * from db1_postgres.table1;

SELECT *
FROM db1_postgres.table1

Query id: df2381ac-4e30-4535-b22e-8be3894aaafc

┌─id─┬─column1─┐
│  1 │ abc     │
└────┴─────────┘
┌─id─┬─column1─┐
│  2 │ def     │
└────┴─────────┘
```

## 3. Test basic replication
1. In PostgreSQL, add new rows:
```sql
INSERT INTO table1
(id, column1)
VALUES
(3, 'ghi'),
(4, 'jkl');
```

2. In ClickHouse, verify new rows are visible:
```sql
ch_env_2 :) select * from db1_postgres.table1;

SELECT *
FROM db1_postgres.table1

Query id: b0729816-3917-44d3-8d1a-fed912fb59ce

┌─id─┬─column1─┐
│  1 │ abc     │
└────┴─────────┘
┌─id─┬─column1─┐
│  4 │ jkl     │
└────┴─────────┘
┌─id─┬─column1─┐
│  3 │ ghi     │
└────┴─────────┘
┌─id─┬─column1─┐
│  2 │ def     │
└────┴─────────┘
```

## 4. Summary
This integration guide focused on a simple example on how to replicate a database with a table, however, there exist more advanced options which include replicating the whole database or adding new tables and schemas to the existing replications. Although DDL commands are not supported for this replication, the engine can be set to detect changes and reload the tables when there are structural changes made.

**For more features available for advanced options, please see the reference documenation:**
https://clickhouse.com/docs/en/engines/database-engines/materialized-postgresql/

**Comment by Olga-par** [comment]
Hi @e-mars. Thank you for answer. I will test replication in PostgreSQL version 10 and will provide feedback after testing.  
I read about problem with logical replication in PostgreSQL: maybe pg_wal/ takes up a lot of space. We will use SETTINGS materialized_postgresql_allow_automatic_update=1 and replicate 110 tables in one database. We replicate 10 databases with 110 tabled each of them.

**Comment by Olga-par** [comment]
@e-mars where is replication logs? In our databases replication worked and broke with some reasons.

**Comment by e-mars** [comment]
Hi @Olga-par ,
please test on version pg 12+ , version 10 has issues.

The `materialized_postgresql_allow_automatic_update` is there to try to detect and reload tables where it sees structure has changed. 

unfortunately, we do not have verbose logging for some modules (such as this one, especially when in the experimental stage)  in ClickHouse currently. we are working on improving logging in the future.
```
<logging>
  <level>trace</level>
</logging>
```
is where we'd emit any messages configured in the module.

thanks.

**Comment by Olga-par** [comment]
Thank you @e-mars. We will test in version pg 12+.

**Comment by e-mars** [comment]
Hi @Olga-par,
Also, I would appreciate it if you could give me a little feedback on the doc preview.
it would really help us. our goal is to boil down our documentation to basics of getting something working and then providing reference materials for more advanced setups in separate reference materials.
thank you in advance!

**Comment by Olga-par** [comment]
OK, @e-mars. I will informate you about testing in version pg 12+. Thank you.

**Comment by Olga-par** [comment]
Hello @e-mars. We will test replication in version Postgresql >12 and it's work. In version Postgresql 10 replication doesn't work. But we use version Postgresql 10 and very important  in order to work replitaction in this version. Will the problem with replication be fixed in the version 10 in Postgresql?

**Comment by Olga-par** [comment]
Logs in replication in postgresql version 10

2022-03-25 16:00:25 UTC:172.29.34.152(57476):root@postgres:[28700]:LOG: logical decoding found consistent point at 0/5B006268
2022-03-25 16:00:25 UTC:172.29.34.152(57476):root@postgres:[28700]:DETAIL: There are no running transactions.
2022-03-25 16:00:25 UTC:172.29.34.152(57476):root@postgres:[28700]:LOG: exported logical decoding snapshot: "0000000A-00000238-1" with 0 transaction IDs
2022-03-25 16:00:25 UTC:172.29.34.152(57478):root@postgres:[28701]:ERROR: function pg_replication_slot_advance(unknown, unknown) does not exist at character 21
2022-03-25 16:00:25 UTC:172.29.34.152(57478):root@postgres:[28701]:HINT: No function matches the given name and argument types. You might need to add explicit type casts.
2022-03-25 16:00:25 UTC:172.29.34.152(57478):root@postgres:[28701]:STATEMENT: SELECT end_lsn FROM pg_replication_slot_advance('test_pg10_ch_replication_slot', '0/5B0062A0')
2022-03-25 16:01:27 UTC::@:[5529]:LOG: checkpoint starting: time
2022-03-25 16:01:29 UTC::@:[5529]:LOG: checkpoint complete: wrote 16 buffers (0.0%); 0 WAL file(s) added, 0 removed, 1 recycled; write=1.612 s, sync=0.003 s, total=1.625 s; sync files=15, longest=0.003 s, average=0.001 s; distance=16385 kB, estimate=16627 kB
----------------------- END OF LOG

**Comment by e-mars** [comment]
Hi @Olga-par,
From I can see, Postgres 10 is not supported:
https://github.com/ClickHouse/ClickHouse/issues/35083#issuecomment-1060504042

@kssenii is ^this^ correct ? likely not backporting to PG10?

**Comment by kssenii** [comment]
Yes, it is not supported for earlier versions because there is no analog for `pg_replication_slot_advance` but current implementation relies on it.
It is possible to avoid using this function, but the implementation without it will not be fault-tolerant.
It is also possible to use another PostgreSQL replication API to make a little different implementation, but it is not planned to be implemented by me.

**Comment by mistakeNot7** [comment]
@kssenii, continous (streaming) replication doesn't work with PG 14.2 and CH 22.2.2.1 or CH 22.3.2.1. After the initial database creation using MaterializedPostgreSQL, the tables are created and populated in CH, but no later inserts or deletes are streamed to CH. The publication on PG side is still open. Also from documentation is not clear what is the recovery mechanism in case either PG or CH servers are restarted, how the replication resumes.

**Comment by asmhack** [comment]
@kssenii 
Same here. 
PostgreSQL 13.6 on x86_64-pc-linux-gnu, compiled by gcc, a cf00366d51 p 86b4810fd9, 64-bit
Clickhouse 22.4.5.9 as well as older one 22.3.3.44 

Initial sync works fine but no further change synced from PG to CH. 

The result of this query in PG:
`select name, setting from pg_settings where name in ('max_replication_slots', 'wal_level', 'max_wal_senders', 'hot_standby');`

| name | setting |
| :--- | :--- |
| hot\_standby | on |
| max\_replication\_slots | 20 |
| max\_wal\_senders | 20 |
| wal\_level | logical |


Also the replication slot has status active = false
`select slot_name, pg_size_pretty(pg_wal_lsn_diff(pg_current_wal_lsn(), restart_lsn)) as replicationSlotLag, active from pg_replication_slots;`

| slot\_name | replicationslotlag | active |
| :--- | :--- | :--- |
| pghoard\_local | 12 MB | true |
| equals\_pg\_replica\_ch\_replication\_slot | 16 GB | false |

Also it growth a lot over time.

In CH it was created using:
`
    CREATE DATABASE equals_pg_replica
    ENGINE = MaterializedPostgreSQL('HOST.db.ondigitalocean.com:25060', 'DB_NAME', 'XXXX', 'XXX')
    SETTINGS
            materialized_postgresql_tables_list = 'table1,table2',
            materialized_postgresql_allow_automatic_update = 1
;`

Overall 11 tables. With total size around 50MB. So replica 16GB looks weird.


Please let us know about possible workaround or recovery mechanism.

**Comment by kssenii** [comment]
Looks like command `pg_replication_slot_advance` is not working as expected for you and replication slot remains the same, continueing to grow. I think there should be some exception message in clickhouse server logs. Can you please take a look?

**Comment by asmhack** [comment]
Thank you @kssenii for quick reply.

Also from PG logs I see pretty much a lot such messages:
`FATAL: out of relcache_callback_list slots`.

Let me enable logs in clickhouse and check it out.

**Comment by asmhack** [comment]
From clickhouse-server.err.log - almost every second such error. Not sure it's related (maybe it's DataGrip introspecting server or whatever, despite I have root access)

```

2022.05.11 08:02:06.662744 [ 9307 ] {82966fc8-5d94-4911-8d68-75224a75cfa4} <Error> DynamicQueryHandler: Code: 497. DB::Exception: default: Not enough privileges. To execute this query it's necessary to have grant SHOW USERS ON *.*. (ACCESS_DENIED), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xb6fc2fa in /usr/bin/clickhouse
1. bool DB::ContextAccess::checkAccessImplHelper<true, false>(DB::AccessFlags const&) const::'lambda'(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int)::operator()(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) const @ 0x15495e97 in /usr/bin/clickhouse
2. bool DB::ContextAccess::checkAccessImplHelper<true, false>(DB::AccessFlags const&) const @ 0x15494acc in /usr/bin/clickhouse
3. DB::Context::checkAccess(DB::AccessFlags const&) const @ 0x15cdb868 in /usr/bin/clickhouse
4. DB::StorageSystemUsers::fillData(std::__1::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn> > >&, std::__1::shared_ptr<DB::Context const>, DB::SelectQueryInfo const&) const @ 0x151be2f5 in /usr/bin/clickhouse
5. DB::IStorageSystemOneBlock<DB::StorageSystemUsers>::read(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageSnapshot const> const&, DB::SelectQueryInfo&, std::__1::shared_ptr<DB::Context const>, DB::QueryProcessingStage::Enum, unsigned long, unsigned int) @ 0x1516f3b9 in /usr/bin/clickhouse
6. DB::IStorage::read(DB::QueryPlan&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageSnapshot const> const&, DB::SelectQueryInfo&, std::__1::shared_ptr<DB::Context const>, DB::QueryProcessingStage::Enum, unsigned long, unsigned int) @ 0x165f0497 in /usr/bin/clickhouse
7. DB::InterpreterSelectQuery::executeFetchColumns(DB::QueryProcessingStage::Enum, DB::QueryPlan&) @ 0x16113bf4 in /usr/bin/clickhouse
8. DB::InterpreterSelectQuery::executeImpl(DB::QueryPlan&, std::__1::optional<DB::Pipe>) @ 0x1610aed3 in /usr/bin/clickhouse
9. DB::InterpreterSelectQuery::buildQueryPlan(DB::QueryPlan&) @ 0x1610a850 in /usr/bin/clickhouse
10. DB::InterpreterSelectWithUnionQuery::buildQueryPlan(DB::QueryPlan&) @ 0x16161803 in /usr/bin/clickhouse
11. DB::InterpreterSelectWithUnionQuery::execute() @ 0x16162968 in /usr/bin/clickhouse
12. ? @ 0x1642be95 in /usr/bin/clickhouse
13. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::__1::shared_ptr<DB::Context>, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>, std::__1::optional<DB::FormatSettings> const&) @ 0x1642f267 in /usr/bin/clickhouse
14. DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::__1::optional<DB::CurrentThread::QueryScope>&) @ 0x16d74397 in /usr/bin/clickhouse
15. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x16d78bc2 in /usr/bin/clickhouse
16. DB::HTTPServerConnection::run() @ 0x16fff17b in /usr/bin/clickhouse
17. Poco::Net::TCPServerConnection::start() @ 0x1b3eadef in /usr/bin/clickhouse
18. Poco::Net::TCPServerDispatcher::run() @ 0x1b3ed241 in /usr/bin/clickhouse
19. Poco::PooledThread::run() @ 0x1b5b3c89 in /usr/bin/clickhouse
20. Poco::ThreadImpl::runnableEntry(void*) @ 0x1b5b0fe0 in /usr/bin/clickhouse
21. start_thread @ 0x7fa3 in /usr/lib/x86_64-linux-gnu/libpthread-2.28.so
22. clone @ 0xf8eff in /usr/lib/x86_64-linux-gnu/libc-2.28.so
 (version 22.4.5.9 (official build))

```

And the second longer piece of logs I posted here:
https://gist.github.com/asmhack/efc5da8662e0cd45144e1c5780b870d4

Thanks in advance!

**Comment by asmhack** [comment]
@kssenii was my logs helpful? Is there anything else I can provide to help you investigate this issue?

**Comment by asmhack** [comment]
@kssenii Any luck with this? 
It remains from version to version without any change.

**Comment by kssenii** [comment]
Hi, sorry I missed these messages. I checked 14 PostgreSQL version now as you mentioned and it works for me.. May be you can check clickhouse master version? (master version can be installed this way https://clickhouse.com/docs/en/getting-started/install/#from-single-binary)

**Comment by simPod** [comment]
I can see the error on pg 14 with citus extension installed (v11) on clickhouse v22.11maco

```
2023-01-11 14:40:40.938 UTC [107] FATAL:  out of relcache_callback_list slots
2023-01-11 14:40:40.938 UTC [107] STATEMENT:  COPY (select lsn, data FROM pg_logical_slot_peek_binary_changes('___tests__4e44a026_pg_ch_replication_slot', NULL, 65536, 'publication_names', '___tests__4e44a026_pg_ch_publication', 'proto_version', '1')) TO STDOUT
```

According to the description here

https://github.com/ClickHouse/ClickHouse/blob/bb3c4641a7ab888a8e2361124d1c664e8fee2624/src/Storages/PostgreSQL/MaterializedPostgreSQLConsumer.cpp#L807-810 it seems like it's expected and should not be a problem.

**Comment by kssenii** [comment]
> out of relcache_callback_list slots

should be fixed in https://github.com/ClickHouse/ClickHouse/pull/40511. (in 22.3)

**Comment by simPod** [comment]
Ok thanks for reply. I've found out it really does not matter that I see the error in pg log.

**Comment by sobomax** [comment]
Just in case someone still needs to get CH replicating from PG 10.x, I've ported pg_replication_slot_advance() from 12.x branch to 10. It seems to be DTRT, the only caveat is that a wrapper function needs to be created by hand like the following:

`CREATE OR REPLACE FUNCTION pg_replication_slot_advance (
    IN slot_name name, IN upto_lsn pg_lsn,
    OUT slot_name name, OUT end_lsn pg_lsn)
RETURNS RECORD
LANGUAGE INTERNAL
STRICT VOLATILE
AS 'pg_replication_slot_advance';`

Patch is here:

https://github.com/postgres/postgres/compare/postgres:postgres:REL_10_STABLE...sobomax:postgres:REL_10_STABLE_pg_replication_slot_advance?expand=1
