### ISSUE TITLE
CREATE FUNCTION cannot be granted on the database level. (INVALID_GRANT) 

### ISSUE THREAD

**Issue by xiyandd** [ClickHouse/ClickHouse#35458]
**Describe the unexpected behaviour**
 (version 22.2.2.1) When I create a new user and execute the following command. 
`GRANT on cluster clickhouse_cluster_name ALL ON *.*  TO user_name;`
The following error will be triggered

**Error message and/or stacktrace**
`
2022.03.21 16:38:17.215458 [ 24801 ] {7d3a4077-29e1-49d1-8d46-a139591afec1} <Error> DynamicQueryHandler: Code: 509. DB::Exception: CREATE FUNCTION cannot be granted on the database level. (INVALID_GRANT), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xaebed1a in /usr/bin/clickhouse
1. ? @ 0x15f93c07 in /usr/bin/clickhouse
2. DB::ParserGrantQuery::parseImpl(DB::IParser::Pos&, std::__1::shared_ptr<DB::IAST>&, DB::Expected&) @ 0x15f8fc08 in /usr/bin/clickhouse
3. DB::IParserBase::parse(DB::IParser::Pos&, std::__1::shared_ptr<DB::IAST>&, DB::Expected&) @ 0x15f16137 in /usr/bin/clickhouse
4. ? @ 0x140a4327 in /usr/bin/clickhouse
5. DB::IParserBase::parse(DB::IParser::Pos&, std::__1::shared_ptr<DB::IAST>&, DB::Expected&) @ 0x15f16137 in /usr/bin/clickhouse
6. DB::tryParseQuery(DB::IParser&, char const*&, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, unsigned long, unsigned long) @ 0x15f68d8d in /usr/bin/clickhouse
7. DB::parseQueryAndMovePosition(DB::IParser&, char const*&, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, unsigned long, unsigned long) @ 0x15f69bda in /usr/bin/clickhouse
8. DB::deserializeAccessEntity(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x140a2c8c in /usr/bin/clickhouse
9. DB::DiskAccessStorage::readAccessEntityFromDisk(StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag> const&) const @ 0x1409d0c5 in /usr/bin/clickhouse
10. DB::DiskAccessStorage::readImpl(StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag> const&, bool) const @ 0x1409cefb in /usr/bin/clickhouse
11. DB::MultipleAccessStorage::readImpl(StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag> const&, bool) const @ 0x140dfa7e in /usr/bin/clickhouse
12. std::__1::shared_ptr<DB::Role const> DB::IAccessStorage::read<DB::Role>(StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag> const&, bool) const @ 0x13df00b4 in /usr/bin/clickhouse
13. DB::StorageSystemRoles::fillData(std::__1::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn> > >&, std::__1::shared_ptr<DB::Context const>, DB::SelectQueryInfo const&) const @ 0x13defbfa in /usr/bin/clickhouse
14. DB::IStorageSystemOneBlock<DB::StorageSystemRoles>::read(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryInfo&, std::__1::shared_ptr<DB::Context const>, DB::QueryProcessingStage::Enum, unsigned long, unsigned int) @ 0x13d9e0d6 in /usr/bin/clickhouse
15. DB::IStorage::read(DB::QueryPlan&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryInfo&, std::__1::shared_ptr<DB::Context const>, DB::QueryProcessingStage::Enum, unsigned long, unsigned int) @ 0x15081b12 in /usr/bin/clickhouse
16. DB::InterpreterSelectQuery::executeFetchColumns(DB::QueryProcessingStage::Enum, DB::QueryPlan&) @ 0x14c68f45 in /usr/bin/clickhouse
17. DB::InterpreterSelectQuery::executeImpl(DB::QueryPlan&, std::__1::optional<DB::Pipe>) @ 0x14c60f34 in /usr/bin/clickhouse
18. DB::InterpreterSelectQuery::buildQueryPlan(DB::QueryPlan&) @ 0x14c60a70 in /usr/bin/clickhouse
19. DB::InterpreterSelectWithUnionQuery::buildQueryPlan(DB::QueryPlan&) @ 0x14cb1b83 in /usr/bin/clickhouse
20. DB::InterpreterSelectWithUnionQuery::execute() @ 0x14cb2c28 in /usr/bin/clickhouse
21. ? @ 0x14ee8a79 in /usr/bin/clickhouse
22. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::__1::shared_ptr<DB::Context>, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>, std::__1::optional<DB::FormatSettings> const&) @ 0x14eebe2a in /usr/bin/clickhouse
23. DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::__1::optional<DB::CurrentThread::QueryScope>&) @ 0x157a42bd in /usr/bin/clickhouse
24. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x157a8a52 in /usr/bin/clickhouse
25. DB::HTTPServerConnection::run() @ 0x15a0d67b in /usr/bin/clickhouse
26. Poco::Net::TCPServerConnection::start() @ 0x18667a0f in /usr/bin/clickhouse
27. Poco::Net::TCPServerDispatcher::run() @ 0x18669e61 in /usr/bin/clickhouse
28. Poco::PooledThread::run() @ 0x1881a549 in /usr/bin/clickhouse
29. Poco::ThreadImpl::runnableEntry(void*) @ 0x18817c40 in /usr/bin/clickhouse
30. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
31. __clone @ 0xfe9fd in /usr/lib64/libc-2.17.so

`
**Additional context**

**Comment by xiyandd** [comment]
I have found it has been fixed ,closed

**Comment by tavplubix** [comment]
#34815
