### ISSUE TITLE
Hints if user mistyped table name or database name

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#35450]
**Use case**

```
SELECT max(created_at) FROM guthub_events
Code: 60. DB::Exception: Table default.guthub_events doesn't exist. (UNKNOWN_TABLE) (version 22.3.1.1)
```

See `IHints` and its usage.

**Comment by blazingbhavneek** [comment]
Hey there! 👋 I'm new to this repository and eager to contribute! 🌟 Seems like previous PR was not merged, is someone still working on this? Or is it up for grabs?

**Comment by tavplubix** [comment]
Refs: https://github.com/ClickHouse/ClickHouse/pull/49606,  https://github.com/ClickHouse/ClickHouse/pull/49610, https://github.com/ClickHouse/ClickHouse/pull/49801

**Comment by alexey-milovidov** [comment]
Solved by @yariks5s
