### ISSUE TITLE
Why not use separate type name for Object/JSON?

### ISSUE THREAD

**Issue by zhicwu** [ClickHouse/ClickHouse#35461]
Object/JSON is newly added data type in 22.3. I noticed the type name returned from ClickHouse server is Tuple with names and types, for example: `Tuple(k1 Int8)`. I think it's more expressive than `Map` and the structure may have better performance in most cases. However, I have two questions hoping you can answer:

1. Are we going to retire `Nested` data type moving forward?
2. Why not use a separate type name like `Object(k1 Int8)` instead? This way, it will be easier for ClickHouse client to handle, for examples map value to an Object or a Map like many JSON libs do.

I've updated Java client to support the new data type, but I think it's better to hold the pull request before this clarified.

**Comment by den-crane** [comment]
but Tuple is a general solution which allows to describe arbitrary JSON object?  And Map and Nested does not allow this?

**Comment by den-crane** [comment]
```
DESCRIBE TABLE test_nested_types
┌─name─┬─type───────────┬─default_type─┬─default_expression─┬─comment─┬─codec_expression─┬─ttl_expression─┐
│ id   │ Int32          │              │                    │         │                  │                │
│ o    │ Object('json') │              │                    │         │                  │                │
│ t    │ Tuple(k1 Int8) │              │                    │         │                  │                │
└──────┴────────────────┴──────────────┴────────────────────┴─────────┴──────────────────┴────────────────┘


set describe_extend_object_types=1;
┌─name─┬─type───────────┬─default_type─┬─default_expression─┬─comment─┬─codec_expression─┬─ttl_expression─┐
│ id   │ Int32          │              │                    │         │                  │                │
│ o    │ Tuple(k1 Int8) │              │                    │         │                  │                │
│ t    │ Tuple(k1 Int8) │              │                    │         │                  │                │
└──────┴────────────────┴──────────────┴────────────────────┴─────────┴──────────────────┴────────────────┘

set describe_include_subcolumns=1;
┌─name─┬─type───────────┬─default_type─┬─default_expression─┬─comment─┬─codec_expression─┬─ttl_expression─┬─is_subcolumn─┐
│ id   │ Int32          │              │                    │         │                  │                │            0 │
│ o    │ Tuple(k1 Int8) │              │                    │         │                  │                │            0 │
│ t    │ Tuple(k1 Int8) │              │                    │         │                  │                │            0 │
│ o.k1 │ Int8           │              │                    │         │                  │                │            1 │
│ t.k1 │ Int8           │              │                    │         │                  │                │            1 │
└──────┴────────────────┴──────────────┴────────────────────┴─────────┴──────────────────┴────────────────┴──────────────┘
```

probably describe_extend_object_types can change `toTypeName` beh. too.

**Comment by CurtizJ** [comment]
Column of type `Object` can have arbitrary set of subcolumns and it's used only temporarily to parse and transfer data during inserts. Columns of type `Object` are never stored in the tables, but deduced types, which are always `Tuple` or `Nested` types with arbitrary multiple nesting, are stored instead. Those deduced types can vary from query to query depending on the context that is stored in the table at the moment of start of the query. So, for insert queries `Object` type is always returned, while for select queries concrete `Tuple` type, deduced from current snapshot of  data, is returned.

`Nested` is still the alias to `Array(Tuple(...))` with optimization, which allows to store offsets of arrays only once. It has fixed number of its elements and can be the part of the concrete deduced type for the `Object` type.

**Comment by zhicwu** [comment]
@den-crane, but it's really inconvenient to issue additional query like `DESCRIBE TABLE test_nested_types` to get the true data type :<

@CurtizJ, thanks for sharing implementation details. I understand the schema is dynamic and may vary between queries, but how can I tell the exact column type? As of now, I have to treat Object and Tuple in the same way, but if there's any hint from server to tell me the exact data type, I should be able to further optimize the code on client side. For example: I can simply map `Tuple` to List in Java, and `Object` to POJO(Plain Old Java Object) by generating bytecode in runtime.

**Comment by zhicwu** [comment]
> @zhicwu see #37482

Thanks for the heads up @gingerwizard. Just tried `clickhouse/clickhouse-server:head` and it seems JDBC driver still works.

I'm not sure what was changed, but using RowBinaryWithNamesAndTypes format the column type is still something like `Tuple(k1 Int8, k2 Int8, k3 Tuple(k31 String, k32 String))`.
