### ISSUE TITLE
clickhouse-keeper ability to do maintenance operations when quorum lost

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#35465]
Currently is no way to start clickhouse-keeper that has lost its quorum. We can not change its configuration to use different nodes. We can not access the data stored inside.

There is no maintenance mode, etc, there is no way to rebuild/reconfigure the cluster if the quorum is lost.

We need to have something like catastrophic mode in filesystems when you can manually edit the configuration.

That can be done either by setting up some flag like
```
/var/lib/clickhouse/force_keeper_recovery
```
And we can put a clear statement in the documentation that using that flag is unsafe, dangerous and in most cases will lead to inconsistencies.

Alternatively: we can enable starting that with some extra command-line switch / or by listening to localhost only, or on a different port etc.

/cc @Slach @alesapin

**Comment by antonio2368** [comment]
Please check the steps described in the [PR](https://github.com/ClickHouse/ClickHouse/pull/36258/files#diff-380a02c367deb97304024ceaf14298817d5ccc43eaa2b84a9ec46752906e4b6a) and tell me if it works for you.

**Comment by Slach** [comment]
@antonio2368 `rcvr` command doesn't look like easily maintainable solution
why we just can't change XML config with node list to change peer list?

**Comment by antonio2368** [comment]
> rcvr command doesn't look like easily maintainable solution

Why do you think that?

> why we just can't change XML config with node list to change peer list?

Because the configuration is maintained by RAFT also. If you modify XML, the changes are proposed to the cluster, 1 by 1.
There needs to be a "trigger" to tell the Keeper to ignore normal way of operating and manually override the configuration which is stored in the cluster.
`rcvr` seemed to me the easiest way of implementing it but adding additional ways of starting recovery is not a problem.
For example, you can manually start Keeper instances with `--force-recovery` argument instead of sending the `rcvr` command.

**Comment by Slach** [comment]
> Because the configuration is maintained by RAFT also.

What kind of configuration do you mean?
 just PEER LIST or all other keeper related parameters also stored inside database and try to applied synchonously to all nodes?


> Why do you think that?

from Kubernetes declarative perspective
`rvcr`  require using bash script in runtime 
  - wait when node start
  - detect current cluster size and it l, run somtething like 
 
 instead just change XML file and write all available current nodes which defined as replicas: X inside statefulset
 
 > For example, you can manually start Keeper instances with --force-recovery argument instead of sending the rcvr command.
 
please implement these possibility, for kubernetes we will use it constantly

**Comment by antonio2368** [comment]
> just PEER LIST or all other keeper related parameters also stored inside database and try to applied synchonously to all nodes?

Yes, the peer list is stored using Raft, everything else should be local.

>> For example, you can manually start Keeper instances with --force-recovery argument instead of sending the rcvr command.

> please implement these possibility, for kubernetes we will use it constantly

This is already implemented for the standalone `clickhouse-keeper` binary. 
So the steps still remain the same, the only difference is that the picked leader node needs to be restarted with that flag.
Adding the Keeper nodes 1 by 1 is still needed to avoid the split brain.

**Comment by Slach** [comment]
> Yes, the peer list is stored using Raft, everything else should be local.

Zookeeper itself have two typical approaches

- first, store server.X=... in zoo.cfg statically, and change zoo.cfg require restart zookeeper server, then peer list stored in memory only and read from file once time
- second, use `reconfigEnabled=true` and use `zkCli.sh reconfigure -add X ...` and `zkCli.sh reconfigre -remove X` for reconfigure without restart, then peer list stored in zookeeper database

maybe we should allow the same behavior for clickhouse-keeper?

**Comment by antonio2368** [comment]
We rely on the NuRaft library for the configuration and that's the way they handle those things.

Again, keep in mind that such configuration changes are already possible with the Keeper if there is a quorum by just changing the XML.
The method that is added and asked by this PR is a disaster recovery when the cluster cannot be restored in any other way and you forcefully need to change it.
