### ISSUE TITLE
argMax returns different results for single value and tuple

### ISSUE THREAD

**Issue by ertaquo** [ClickHouse/ClickHouse#35472]
Hello.

I have table `current_orders`:
```sql
CREATE TABLE current_orders
(
    `user_id` UUID,
    `current_order_id` Nullable(UUID),
    `updated_at` DateTime
) ENGINE = ReplacingMergeTree(updated_at) ORDER BY user_id SETTINGS index_granularity = 8192;
```

Table contents:

|user_id|current_order_id|updated_at|
|-------|----------------|----------|
|e26d26d4-a730-428c-92e5-5f0c430c605e|NULL|2022-03-21 11:55:39|
|601e7007-9ca9-4483-bf6a-75a2ca9a580c|NULL|2022-03-21 12:06:57|
|095a7ac7-1614-4a78-88da-1443485b96fa|e23b20f7-d262-4fdf-9eed-ce06efab0e07|2022-03-21 12:15:38|
|095a7ac7-1614-4a78-88da-1443485b96fa|NULL|2022-03-21 12:16:21|

```sql
INSERT INTO current_orders (user_id,current_order_id,updated_at) VALUES ('e26d26d4-a730-428c-92e5-5f0c430c605e',NULL,'2022-03-21 11:55:39');
INSERT INTO current_orders (user_id,current_order_id,updated_at) VALUES ('601e7007-9ca9-4483-bf6a-75a2ca9a580c',NULL,'2022-03-21 12:06:57');
INSERT INTO current_orders (user_id,current_order_id,updated_at) VALUES ('095a7ac7-1614-4a78-88da-1443485b96fa','e23b20f7-d262-4fdf-9eed-ce06efab0e07','2022-03-21 12:15:38');
INSERT INTO current_orders (user_id,current_order_id,updated_at) VALUES ('095a7ac7-1614-4a78-88da-1443485b96fa',NULL,'2022-03-21 12:16:21');
```

When I do request
```sql
SELECT user_id, argMax(current_order_id, updated_at) AS current_order_id
FROM current_orders
GROUP BY user_id;
```

It returns:

|user_id|current_order_id|
|-------|----------------|
|e26d26d4-a730-428c-92e5-5f0c430c605e|NULL|
|601e7007-9ca9-4483-bf6a-75a2ca9a580c|NULL|
|095a7ac7-1614-4a78-88da-1443485b96fa|e23b20f7-d262-4fdf-9eed-ce06efab0e07|

Please look at `current_order_id` for `user_id = 095a7ac7-1614-4a78-88da-1443485b96fa` - the value is outdated, it should be `NULL`.

But when I do request using tuple, it shows correct results:

```sql
SELECT user_id, argMax(tuple(current_order_id, updated_at), updated_at) AS current_order_id
FROM current_orders
GROUP BY user_id;
```

|user_id|current_order_id|
|-------|----------------|
|e26d26d4-a730-428c-92e5-5f0c430c605e|(NULL,'2022-03-21 11:55:39')|
|601e7007-9ca9-4483-bf6a-75a2ca9a580c|(NULL,'2022-03-21 12:06:57')|
|095a7ac7-1614-4a78-88da-1443485b96fa|(NULL,'2022-03-21 12:16:21')|

Am I do something wrong, or there's kind of bug?

Reproduced this behaviour on Clickhouse v20.8.12.2 and v22.2.2.1.

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/16400
