### ISSUE TITLE
using LIMIT BY <COLUMN> uses 20GB memory

### ISSUE THREAD

**Issue by andr-kole** [ClickHouse/ClickHouse#35473]
**Describe the situation**

from system.query_log

we have 25M rows that match where condition. And it looks like clickhouse downloads all "model" column in memory and then does limit by <column>

[
  {
    "query": "SELECT model\r\nFROM jaeger_spans_local\r\nPREWHERE traceID ='b3e35d6a1607c364'\r\norder by timestamp\r\nlimit 10000\nFORMAT TabSeparatedWithNamesAndTypes",
    "dur": 2075,
    "memory": "947.71 MiB"
  }
]
 
[
  {
    "query": "SELECT model\r\nFROM jaeger_spans_local\r\nPREWHERE traceID ='b3e35d6a1607c364'\r\norder by timestamp\r\nlimit 10000 by traceID\nFORMAT TabSeparatedWithNamesAndTypes",
    "dur": 26386,
    "memory": "28.77 GiB"
  }
]

so the difference is only between "LIMIT 10000" and "LIMIT 10000 by traceID"

"model" here is a field that contains string about 1k long

* Which ClickHouse server version to use
22.1.3.7

EXPLAIN shows that we do ExpressionTransform twice after sorting and after limitby. Maybe this might be the problem

![image](https://user-images.githubusercontent.com/89205731/159273742-38b2826e-beef-4f04-a9fe-0a355a49d70b.png)

Cheers,
Andrey

**Comment by den-crane** [comment]
Check with `order by traceID, timestamp limit 10000 by traceID`

**Comment by andr-kole** [comment]
> Check with `order by traceID, timestamp limit 10000 by traceID`

[
  {
    "query": "SELECT model\r\nFROM jaeger_spans_local\r\nPREWHERE traceID ='b3e35d6a1607c364'\r\norder by traceID, timestamp\r\nLIMIT 10000 by traceID\nFORMAT TabSeparatedWithNamesAndTypes",
    "dur": 56562,
    "memory": "31.87 GiB"
  },
  {
    "query": "SELECT model\r\nFROM jaeger_spans_local\r\nPREWHERE traceID ='b3e35d6a1607c364'\r\norder by timestamp\r\nLIMIT 10000 by traceID\nFORMAT TabSeparatedWithNamesAndTypes",
    "dur": 37438,
    "memory": "33.35 GiB"
  }
]

**Comment by alexey-milovidov** [comment]
LIMIT BY memory usage is similar to DISTINCT operator and proportional to the number of distinct values.

**Comment by andr-kole** [comment]
we managed to avoid memory usage by rewriting the query not to use the LIMIT BY <column> construct

[
  {
    "query": "SELECT model FROM jaeger_spans_local PREWHERE traceID = 'b3e35d6a1607c364'ORDER BY timestamp LIMIT 10000\r\nUNION ALL\r\nSELECT model FROM jaeger_spans_local PREWHERE traceID = 'af2b93e1edd1b9c8' ORDER BY timestamp LIMIT 10000\r\nUNION ALL\r\nSELECT model FROM jaeger_spans_local PREWHERE traceID = '73dee0b82aa0b87b' ORDER BY timestamp LIMIT 10000\nFORMAT TabSeparatedWithNamesAndTypes",
    "dur": 4690,
    "memory": "1.06 GiB"
  },
  
  {
    "query": "SELECT model\r\nFROM jaeger_spans_local\r\nPREWHERE traceID IN (\r\n'b3e35d6a1607c364',\r\n'af2b93e1edd1b9c8',\r\n'73dee0b82aa0b87b'\r\n)\r\nORDER BY timestamp LIMIT 10000 BY traceID\nFORMAT TabSeparatedWithNamesAndTypes",
    "dur": 40005,
    "memory": "40.70 GiB"
  }
]
