### ISSUE TITLE
Clickhouse Copier Queries

### ISSUE THREAD

**Issue by darthShadow** [ClickHouse/ClickHouse#35487]
Hi,

Had a few queries about the usage of clickhouse-copier:

* What happens if there are duplicate parts i.e. same value for the partition field in the system.parts table? Will clickhouse-copier copy all of those parts?

* Is there any any way to queue a series of tasks for clickhouse-copier to execute? For example, if I want to copy partition A of a table now and partition B of that table a few mins later, then partition C and so on. The partitions B & C were not available when the task for A for created so I can't add those to the enabled_partitions in the config.

Thanks.

**Comment by rkozlo** [comment]
1. AFAIK it is processing on partitions. So if those rows are available it will be also copied. Don't know about situation when some active duplicates will be alive.
2. Copier hasn't any configs. My proposition is to make separate tasks for partitions. Don't know if it helps because you can't make dynamic config file.

**Comment by darthShadow** [comment]
Thanks for the suggestions.

> Don't know about situation when some active duplicates will be alive.

I will test it eventually but I wanted to know the expected behaviour before the test so I can handle the situation appropriately in the tool calling clickhouse-copier.

> My proposition is to make separate tasks for partitions.

I can create different tasks in a new task file but I was under the impression that force uploading a new file to zookeeper under the same path/description overwrites the previous task file which is not what I want. And uploading it to a separate path/description will create separate workers for each task and increase the load on the system which seems sub-optimal.

**Comment by darthShadow** [comment]
Active duplicates seem to be causing the rows to be duplicated repeatedly in the destination by copying different partitions every time I run the task. Any solution or workaround to solve this problem?

**Comment by alexey-milovidov** [comment]
The question is not quite correct.

Partitions in ClickHouse contain multiple data parts. The subset of the data parts which is called "active" is representing the table. Every partition can have up to several hundreds of active parts. clickhouse-copier needs to copy all the active parts.

The reason why you get duplicates is probably unrelated to this observation.
