### ISSUE TITLE
Mutation with "in partition" not working

### ISSUE THREAD

**Issue by mrodonnpaw** [ClickHouse/ClickHouse#35494]
**Mutation with "in partition" gets stuck because of running merges, even that those running merges are from other partitions**
We expect that only merges from the affected partition would block the mutation.

**Comment by den-crane** [comment]
clarify "gets stuck "

**Comment by Avogar** [comment]
@tavplubix, @KochetovNicolai can someone look at it?

**Comment by mrodonnpaw** [comment]
Hi, any news about it? @tavplubix @KochetovNicolai

**Comment by mrodonnpaw** [comment]
Hi, could someone have a look at it, please? Using in partition, the process should skip the partitions involved in a merge as well.

**Comment by tavplubix** [comment]
You did non provide any diagnostics/information, so we cannot help you (what is your clickhouse-server version? what is the table engine? anything interesting in logs? output of queries from system tables showing the issue?). And it's still not clear what you mean by "gets stuck". Maybe it just works slowly and will be executed eventually.

> Using in partition, the process should skip the partitions involved in a merge as well.

It should not, see https://github.com/ClickHouse/ClickHouse/pull/40589 and linked issues.

**Comment by mrodonnpaw** [comment]
That is not what we observed. It gets stuck during hours (for long merges). In these cases, there isn't any pending part to do related to the in partition selected. For example:

I'm running a mutation with in partition 20230424:

`ch20 :) select mutation_id, parts_to_do, parts_to_do_names from system.mutations where is_done = 0\G

SELECT
    mutation_id,
    parts_to_do,
    parts_to_do_names
FROM system.mutations
WHERE is_done = 0

Query id: 2c62ffbd-3744-43a1-ac20-3f5a15a3769a

Row 1:
──────
mutation_id:       mutation_190972761.txt
parts_to_do:       8
parts_to_do_names: ['20230520_189930118_189931397_5_190966160','20230520_189928847_189930117_5_190966160','20230520_189927606_189928846_5_190966160','20230520_189920507_189927605_6_190966160','20230520_189913980_189920505_6_190966160','20230520_189907252_189913978_6_190966160','20230520_189901475_189907251_6_190966160','20230520_189895556_189901473_6_190966160']

1 row in set. Elapsed: 0.008 sec. 

ch20 :) select progress, num_parts, result_part_name, elapsed, merge_type, is_mutation from system.merges where table = 'youbora_events_l3000'

SELECT
    progress,
    num_parts,
    result_part_name,
    elapsed,
    merge_type,
    is_mutation
FROM system.merges
WHERE table = 'youbora_events_l3000'

Query id: 1ca1a40f-12ef-479f-8211-1c3967b6179b

┌───────────progress─┬─num_parts─┬─result_part_name─────────────────────────┬────────elapsed─┬─merge_type─┬─is_mutation─┐
│ 0.5891874513517237 │         8 │ 20230520_189895556_189931397_7_190966160 │ 4522.656129461 │ Regular    │           0 │
│ 0.3428544291010406 │         9 │ 20230530_190977214_190978302_4           │   56.958992236 │ Regular    │           0 │
│ 0.9681977919994949 │         8 │ 20230530_190978303_190978344_2           │   15.795712382 │ Regular    │           0 │
└────────────────────┴───────────┴──────────────────────────────────────────┴────────────────┴────────────┴─────────────┘
`

As you can see, the mutation has still 8 parts to do. Checking the names, these correspond to the running merge with the resulting part 20230520_189895556_189931397_7_190966160. The mutation does not have any pending part for the partition 20230424.

**Comment by tavplubix** [comment]
Yes, it's expected that the mutation waits for these merges. Yes, it may work for hours. Nothing got stuck here, it will finish eventually.

**Comment by den-crane** [comment]
@mrodonnpaw WIP https://github.com/ClickHouse/ClickHouse/pull/48941

**Comment by tavplubix** [comment]
> Are you planning to improve it?

https://github.com/ClickHouse/ClickHouse/pull/41344 was failed and https://github.com/ClickHouse/ClickHouse/pull/48941 looks abandoned

> Is it possible to exclude the parts that are not involved in the partition, even if there is a merge running?

No. However, `ReplicatedMergeTree` does not have this issue.

**Comment by mrodonnpaw** [comment]
Ok, cool! I've seen it's assigned to you. Let me know if you do any progress on it. Thanks for the reply.

**Comment by Mizoguchee** [comment]
@mrodonnpaw  Did it complete by any chance ? Facing the same problem. Mutation is running for days and the parts_to_do is not reducing .

**Comment by Mizoguchee** [comment]
Oh okay Thanks

**Comment by zero-element** [comment]
same performance issue
