### ISSUE TITLE
Clickhouse-client optional arguments parsing error with special characters

### ISSUE THREAD

**Issue by lzydmxy** [ClickHouse/ClickHouse#35495]
Clickhouse-client cannot parse optional arguments values with special characters  correctly .For example：
```shell
 $ /usr/bin/clickhouse-client --host 11.125.147.233 --port 9600 --password "-fkbWE-Jvyq2TvX41Im4" --user test 
ClickHouse client version 21.12.3.32 (official build).
Password for user (test): 
```
The client failed to resolve the password. And I enter password again, and execute sql `select 1;` 
```sql
lf10-ch-000009-clickhouse-0-0.lf10-ch-000009-clickhouse.realtime-data-platform.svc.lf10.n.jd.local :) select 1;

SELECT 1

Query id: 3baf1e2d-6933-4281-a645-11dddcb63244

Exception on client:
Code: 73. DB::Exception: Unknown format kbWE-Jvyq2TvX41Im4. (UNKNOWN_FORMAT)
```
It’s seem like clickhouse-client parse password "-fkbWE-Jvyq2TvX41Im4" as `-f`  "kbWE-Jvyq2TvX41Im4"
`-f` is  optional arguments: `--format, -f `– Use the specified default format to output the result.

**Comment by alexey-milovidov** [comment]
This is a limitation of unix command line.
You can use `--password="-fkbWE-Jvyq2TvX41Im4"` form (with `=`) to overcome this limitation.
