### ISSUE TITLE
projection: can not hit projection when use dt partition key

### ISSUE THREAD

**Issue by freedomDR** [ClickHouse/ClickHouse#35493]
reproduce
```
CREATE TABLE test1
(
    `dt` String,
    `val` Int32,
    `v` UInt32,
    PROJECTION p1
    (
        SELECT
            val,
            sum(v)
        GROUP BY val
    )
)
ENGINE = MergeTree
PARTITION BY dt
ORDER BY tuple();

insert into test1 select '20220318' as dt, number as val, number%2 as v from numbers(1000);
```
when I execute query with dt **explain plan select val, sum(v) from test1 where dt='20220318' group by val**. I can not find hit projection
![image](https://user-images.githubusercontent.com/11146756/159402199-51104dfa-4b01-4fe2-9c4f-9c10e7d3d206.png)
when I execute query **explain plan select val, sum(v) from test1 group by val**. I can find hit projection
![image](https://user-images.githubusercontent.com/11146756/159402301-253bac87-4a6b-423b-b340-f40b3caeec5c.png)

@amosbird  **MergeTreeData::getQueryProcessingStageWithAggregateProjection** this code have some problem...

**Comment by freedomDR** [comment]
version v22.3-lts

**Comment by amosbird** [comment]
Partition pruning doesn't work with projection currently. https://github.com/ClickHouse/ClickHouse/issues/31670 . You can specify the partition key in projection for now.

```
CREATE TABLE test1
(
    `dt` String,
    `val` Int32,
    `v` UInt32,
    PROJECTION p1
    (
        SELECT
            val,
            sum(v)
        GROUP BY dt, val
    )
)
ENGINE = MergeTree
PARTITION BY dt
ORDER BY tuple();
```

**Comment by freedomDR** [comment]
ok... I understand it. thanks
