### ISSUE TITLE
CLI is broken starting with v22.3

### ISSUE THREAD

**Issue by alexryndin** [ClickHouse/ClickHouse#35501]
Cli is broken starting with v22.3-lts:
1. When I try to copy-paste multiline sql query, clickhouse-client (launched with -m flag ofc) goes insane and breaks query:
```
CREATE TABLE test
(
    Date Date,
    user_id Nullable(UInt32),
    custom_audience_id UInt32,
    segment_id Nullable(UInt32),
)
ENGINE = MergeTree() partition by Date order by (Date, user_id);
```
![grim-22 03 2022-152400](https://user-images.githubusercontent.com/8342078/159481333-b936cdf1-dda8-426c-88f6-e9466277a301.png)
2. When I press enter, query should kind of split and continue on a new line with prompt `:-]` as it was in previous versions, but starting with 22.3 I just get newline feed:
![grim-22 03 2022-152657](https://user-images.githubusercontent.com/8342078/159481823-ebcece37-58c4-46d9-aab1-fc7220231cc3.png)

**How to reproduce?**
1. Using your linux disro (ubuntu for instance) open any text editor, gedit for instance, and paste in it the query above:
![grim-22 03 2022-154645](https://user-images.githubusercontent.com/8342078/159485238-6f68d340-593a-4fea-8ed9-74ffe5ee6c52.png)
2. Using your mouse, select query and press `CTRL+C` on your keyboard.
3. Open your terminal emulator and launch `clickhouse-client -m`. I use `alacritty` terminal emulator, but may be there are some more affected emulator. I also tried `foot` terminal -- same result.
4. Press `CTRL+SHIFT+V`
Expected behavior:
![grim-22 03 2022-155246](https://user-images.githubusercontent.com/8342078/159486319-ab738dd5-de09-4a2d-b242-b07783889636.png)
Not expected behavior:
![grim-22 03 2022-155328](https://user-images.githubusercontent.com/8342078/159486388-48d25aae-8029-47ce-8f67-d92cd8701e75.png)

**Does it reproduce on recent release?**
yes, `ClickHouse server version 22.3.2 revision 54455`

**Comment by alexey-milovidov** [comment]
@alexryndin 

How exactly do you paste query? (how to reproduce?)
Could you please write a test with `expect`?
See `tests/queries/0_stateless/*.expect`

@amosbird Looks like it's a bug in replxx library that was updated recently.

> 2. When I press enter, query should kind of split and continue on a new line with prompt :-] as it was in previous versions, but starting with 22.3 I just get newline feed

This is expected behavior for multi-line editing.

**Comment by alexryndin** [comment]
@alexey-milovidov 
I've updated the issue and added steps to reproduce.
I don't think `expect` tests will be helpful here, because `clickhouse-client -m < sql.sql` works fine, it is prompt handling library (readline or what clickhouse uses) who breaks query
> This is expected behavior for multi-line editing.
I don't think so. Compare old 21.3:
![grim-22 03 2022-155746](https://user-images.githubusercontent.com/8342078/159487170-5b5ef9fb-eaa0-46ad-a306-8dfa06f48fd7.png)
and new 22.3-lts:
![grim-22 03 2022-155813](https://user-images.githubusercontent.com/8342078/159487213-2a18428f-2328-4442-ad14-b95a7397981a.png)

**Comment by amosbird** [comment]
Please share your terminfo. I cannot reproduce the issue with either xterm-256color or screen-256color.

**Comment by amosbird** [comment]
which terminal emulator do you use? And is it inside some terminal multiplexer (screen or tmux)?

**Comment by alexryndin** [comment]
@amosbird 
I use alactritty and I tried it with and without tmux. я попробовал другой эмулятор (xterm) and (suprise) it works fine.
So now I don't think it is exactly clickhouse issue, but it worked in previous versions so nevetherless I think there is some degradation. Could you try alacritty?

**Comment by alexey-milovidov** [comment]
We use `expect` to test interactive behavior like autocomplete, progress bar, history, typing multiline queries...

**Comment by Slach** [comment]
@amosbird @alexey-milovidov 
I confirm cli behavior is broken after 22.3

inside Linux WSL kubectl exec
wrong prompt show and it looks like that

![image](https://user-images.githubusercontent.com/105560/161475837-d65340b8-60c8-4add-8fe6-bf8e2b16e374.png)
![image](https://user-images.githubusercontent.com/105560/161475944-d3941303-b835-4e29-b6bf-badc9f4745c0.png)

**Comment by amosbird** [comment]
@Slach This looks like a different issue. (maybe the terminal doesn't understand bracketed paste enable sequence). I don't have a Windows env to reproduce for the moment. Will try it next week.

**Comment by tzanko-matev** [comment]
I want to report that I encounter the same weird pasting behavior when using `kitty` and Clickhouse client v22.3.2.1. Running the client from `xterm` works as expected

**Comment by amosbird** [comment]
@tzanko-matev v22.3.2.1 doesn't have https://github.com/ClickHouse/ClickHouse/pull/35541 . Please try using to a new version of clickhouse-client.

**Comment by alexey-milovidov** [comment]
No recent complains about this issue.
