### ISSUE TITLE
Create or Drop tables on cluster are not working and timing out after recovering from bad ZooKeeper.

### ISSUE THREAD

**Issue by piyushsriv** [ClickHouse/ClickHouse#35506]
Hi Team, 

Our Clickhouse cluster (version 21.8.3) Zookeeper went into a bad state and hence we did ZK re-install and restored all tables metadata as explained in the [document](https://altinity.com/blog/a-new-way-to-restore-clickhouse-after-zookeeper-metadata-is-lost). 

Now, when we are trying to create or drop any table on the cluster then the query gets stuck for some time and then we get the following error.

```
CREATE TABLE tmp.test on cluster '{cluster}'
(
    n UInt32
) 
ENGINE = ReplicatedMergeTree('/clickhouse/tables/test/', '{replica}')
ORDER BY n PARTITION BY n % 10;

Received exception from server (version 21.8.3):
Code: 341. DB::Exception: Received from localhost:9000. DB::Exception: Cannot provide query execution status. The query's node /clickhouse/rollworks-production/task_queue/ddl/query-0000000014 has been deleted by the cleaner since it was finished (or its lifetime is expired).
```

Running the query on one machine of the cluster without on cluster works fine.

What could be the problem here.

Thanks

**Comment by den-crane** [comment]
21.8.3 is obsolete.
You need to upgrade to 21.8.15.7

**Comment by Algunenano** [comment]
Without CH logs it's not possible to know what was the issue
