### ISSUE TITLE
Option for offset date range

### ISSUE THREAD

**Issue by infisamk** [ClickHouse/ClickHouse#35516]
Now Date32 stored in four bytes as the number of days since 1925-01-01. Allows storing values till 2283-11-11.

Some people have birthday before 1925-01-01, and we can't keep and use them. But we don't use dates above 2183-11-11.

I suggest adding a setting to the ClickHouse that will include shifting the date range 1 century down.

So we can work with the range from 1825-01-01 to 2183-11-11. When configured, byte storage will be completely identical to the current one. But the interpretation of dates will simply be shifted by 1 century. This will circumvent the possible problems of leap years.

**Comment by den-crane** [comment]
It's covered by https://github.com/ClickHouse/ClickHouse/issues/32006
Why reason why they decided to use 1925-01-01 is because we don't have singe calendar before 1925-01-01, all countries used different calendars, because of THE shift. See https://en.wikipedia.org/wiki/Proleptic_Gregorian_calendar
