### ISSUE TITLE
clickhouse connect hive error

### ISSUE THREAD

**Issue by yangshike** [ClickHouse/ClickHouse#35515]
when i used :
SELECT * FROM hive('thrift://xxx:9083', 'ods_qn', 'ods_crm_prod_on_off_line_msg_es_df', 'bizid Nullable(String), corpid Nullable(Int32),time Nullable(Int64),reasontype Nullable(Int32),weworkid Nullable(Int64), type Nullable(Int8),pt String', 'pt');

i get:

Received exception from server (version 22.3.2):
Code: 210. DB::Exception: Received from localhost:9000. DB::Exception: Unable to connect to HDFS: InvalidParameter: Cannot create namenode proxy, does not contain host or port. (NETWORK_ERROR)

ps:
my hdfs used HA mode
this is my clickhouse config.xnl about hdfs:

<libhdfs3_conf>/etc/clickhouse-server/hdfs-client.xml</libhdfs3_conf>
how can i do? thank you

**Comment by yangshike** [comment]
not supplied hive with HA hdfs?
ps:
when i use :
CREATE TCREATE TABLE hdfs_engine_table (name String, value UInt32) ENGINE=HDFS('hdfs://nn1:8020/testck/other_test', 'TSV')
INSERT IINSERT INTO hdfs_engine_table VALUES ('one', 1), ('two', 2), ('three', 3)
 select * from hdfs_engine_table;

SELECT *
FROM hdfs_engine_table

Query id: f736cbf4-09e5-4a0f-91b4-4d869b78e6e7

┌─name──┬─value─┐
│ one   │     1 │
│ two   │     2 │
│ three │     3 │
└───────┴───────┘
it works ok!
but when i use  hive url.
i got error

**Comment by git-kids** [comment]
hello，你这个问题解决了吗，我最近也遇到了相同的情况，但是怪异的是我们测试环境的hive引擎可以正常使用，但是生产环境的跟你这个情况一样报HA的错误？

**Comment by yangshike** [comment]
没解决，你的测试环境 hive 后面是ha的hdfs吗？

**Comment by Mew97** [comment]
hello，你这个问题解决了吗，我最近也遇到了相同的情况, 我使用的是HDFS引擎

**Comment by yangshike** [comment]
解决了
clickhouse config.xml
<hdfs>
    <libhdfs3_conf>/etc/clickhouse-server/hdfs-client.xml</libhdfs3_conf>
   <dfs_default_uri>hdfs://hadoopnamenodeHA</dfs_default_uri>
  </hdfs>

hadoopnamenodeHA 来自于： /etc/clickhouse-server/hdfs-client.xml（<name>dfs.ha.namenodes.hadoopnamenodeHA</name>）

**Comment by alexey-milovidov** [comment]
We don't support HDFS.
