### ISSUE TITLE
Some problems about the separation scheme of storage and Computing

### ISSUE THREAD

**Issue by shadowDy** [ClickHouse/ClickHouse#35527]
In roadmap, I see the main work on the separation of storage and computing;

1: Does it mainly support the separation of objects from storage.

2: Is there a plan for the separation of storage and computing based on HDFS.

At present, it seems that the same file is stored on the local disk and the path of HDFS is stored in the file. Will the storage scheme of meta and path be upgraded in the future?

3: How does the community plan for the storage and calculation separation of real-time import scenarios and the multi read + multi write mode

**Comment by melvynator** [comment]
I think you can ask these questions directly in: #32513
