### ISSUE TITLE
Problem with "global in" after update

### ISSUE THREAD

**Issue by rkozlo** [ClickHouse/ClickHouse#35523]
Hi
First of all my clusters and table relations:
Cluster A - table a MergeTree
Cluster B - table b MergeTree
Cluster C - table Ca Distributed to cluster A table a, table Cb Distributed to cluster B table b

Some time ago i had problems with very slow executing query and timeout receive. In that time i had 21.3.15 version. I have found reported and fixed problem [#28997](https://github.com/ClickHouse/ClickHouse/pull/28997) with "global in" which were executed on single thread. So i updated my cluster C where query were executed to version 21.3.20 with that fix and problem disappeared in that time. After some time updated also cluster A without any problems.
Lately i had to update clickhouse so i chosen next LTS version 21.8. Started with cluster C without any problems.Then i updated cluster B  21.3.15 →21.8.14 and after that the same query started executing event 10 times longer than before update. Query is executed on cluster C it selects data from Ca and have "global in" to Cb. Something like this
`SELECT some_column  FROM Ca  WHERE someIds GLOBAL IN (  SELECT DISTINCT someIds  FROM Cb )   GROUP BY some_column FORMAT TSVWithNamesAndTypes`
Tried to execute the same query without cluster C. From cluster A or B but the same result. So i downgraded to 21.3.20 but there were still a problem and had to downgrade to 21.3.15 and then execution time query started to be reasonable.
Made some test with skipping cluster B completely with creating and feeding the same table on cluster C and the same problem.
Anyone have such problems? Am I missing something maybe?

**Comment by Avogar** [comment]
@KochetovNicolai maybe you have some thoughts?

**Comment by nickitat** [comment]
likely related https://github.com/ClickHouse/ClickHouse/issues/35740#issuecomment-1179611012

**Comment by nickitat** [comment]
@rkozlo does it reproduce on the current release?

**Comment by Algunenano** [comment]
Please reopen if it reproduces in 24.3+

**Comment by rkozlo** [comment]
I am pretty sure i had to workaround this bug still in 23.8
