### ISSUE TITLE
How to Remove a replica table 

### ISSUE THREAD

**Issue by andycol** [ClickHouse/ClickHouse#35545]
Using the new clickhouse keeper how do i remove a replica from the system.replicas table?
i dropped a table and want to re-create it but it wont as it says the replica already exists
i see it in the system.replica table

i remember with zookeeper you used to do it from zookeeper but with clickhouse keeper im not sure?

Thanks

**Comment by genzgd** [comment]
This will normally happen automatically, but there is a (configurable) delay of 8 minutes.  If you still find you have to remove the replica manually after 8 minutes  you can do it in the same way (by deleting the relevant zookeeper node under `/clickhouse/tables/table/replicas`

**Comment by den-crane** [comment]
@andycol atomic database? 8 minutes drop delay?

https://kb.altinity.com/engines/altinity-kb-atomic-database-engine/
