### ISSUE TITLE
Segfault after Right outer Join , when the left side is LowCardinality(String) and the right side is LowCardinality(Nullable(String)) 

### ISSUE THREAD

**Issue by rzilkha** [ClickHouse/ClickHouse#35551]
Happens on Version 21.8, we managed to easily reproduce it by the following setup:

**create table with nullable field** 
```
CREATE TABLE IF NOT EXISTS with_nullable
(
    timestamp UInt32,
        country LowCardinality(Nullable(String))
)
ENGINE = MergeTree
PARTITION BY toRelativeWeekNum(toDateTime(timestamp))
ORDER BY (timestamp );
```
    
**create table without nullable field** 
```
CREATE TABLE IF NOT EXISTS without_nullable
(
    timestamp UInt32,
    country LowCardinality(String)
)
ENGINE = MergeTree
PARTITION BY toRelativeWeekNum(toDateTime(timestamp))
ORDER BY (timestamp );
    
```

**insert data to both**

```
insert into with_nullable values(0,'f')
insert into with_nullable values(0,'usa')
insert into without_nullable values(0,'usa')
insert into without_nullable values(0,'us2a')
```
 
**run the following query** 
` select if(t0.country is null ,t2.country,t0.country) "country" from without_nullable t0 right outer join with_nullable t2 on t0.country=t2.country`
 
it will result in the following error

2022.03.23 23:17:22.341785 [ 91736 ] {} <Fatal> BaseDaemon: (version 21.8.13.1, no build id) (from thread 91011) (query_id: 42a749ca-9a49-4b3a-88f8-a787ea7e8f3a) Received signal Bus error: 10 (10)
2022.03.23 23:17:22.341801 [ 91736 ] {} <Fatal> BaseDaemon: Invalid address alignment.
2022.03.23 23:17:22.342639 [ 91736 ] {} <Fatal> BaseDaemon: Stack trace: 0x1028b744c
2022.03.23 23:17:22.342667 [ 91736 ] {} <Fatal> BaseDaemon: 0. 0x1028b744c
2022.03.23 23:17:42.377725 [ 90809 ] {} <Fatal> Application: Child process was terminated by signal 10.

**Comment by den-crane** [comment]
confirm for 21.8.14.5

```
Connected to ClickHouse server version 21.8.14 revision 54449.

96512570d0ad :) select if(t0.country is null ,t2.country,t0.country) "country" from without_nullable t0 right outer join with_nullable t2 on t0.country=t2.country　;

SELECT if(isNull(t0.country), t2.country, t0.country) AS country
FROM without_nullable AS t0
RIGHT JOIN with_nullable AS t2 ON t0.country = t2.country

Query id: 429a215f-9ea2-4b2e-a310-6f7f39675dfe

┌─country─┐
│ ᴺᵁᴸᴸ    │
└─────────┘
Aborted
```

22.3.2.1 works

```
SELECT if(t0.country IS NULL, t2.country, t0.country) AS country
FROM without_nullable AS t0
RIGHT JOIN with_nullable AS t2 ON t0.country = t2.country

Query id: 571d58e9-487c-407c-bf50-d5fcc3108d8b

┌─country─┐
│ usa     │
└─────────┘
┌─country─┐
│         │
└─────────┘

2 rows in set. Elapsed: 0.008 sec.
```

**Comment by rzilkha** [comment]
@den-crane Thank you for the quick replay , do you know any workaround we can use, I am assuming the best way is to apply a coalesce  on the right side , thereby making it not nullable

**Comment by den-crane** [comment]
@rzilkha you use cast to remove LowCardinality in `on`

```sql
select if(t0.country is null ,t2.country,t0.country) "country" 
from without_nullable t0 
    right outer join 
      with_nullable t2 on cast(t0.country, 'Nullable(String)')= cast(t2.country, 'Nullable(String)')
┌─country─┐
│ usa     │
└─────────┘
┌─country─┐
│         │
└─────────┘
```
