### ISSUE TITLE
clickhouse22.3.2 start failed

### ISSUE THREAD

**Issue by Data-bytes305** [ClickHouse/ClickHouse#35566]
step 1: 
    when i  installed  clickhouse , it start successfully.

step 2:
   I change data path ,  it start failed.
![20220324-163541](https://user-images.githubusercontent.com/83893570/159875665-3e61c88f-c89e-40a5-8b20-e49b9af16ffc.png).

but  the path belong to clickhouse user.

![20220324-163550](https://user-images.githubusercontent.com/83893570/159875870-f2821667-3422-4492-9302-36c6bbd9be4d.png)

why ????

**Comment by alexey-milovidov** [comment]
It is possible if parent directories have no list access (bit `x`) for `clickhouse` user.
