### ISSUE TITLE
LIMIT BY - allow for different group sizes

### ISSUE THREAD

**Issue by reflection** [ClickHouse/ClickHouse#3556]
Currently the LIMIT BY clause only allows for one group_size to be applied across all groups:
`LIMIT 10 BY a, b, c`

We have an important use case where we want different limits for each group:
`LIMIT 5, 10, 20 BY a, b, c`

Could LIMIT BY be extended or have slightly different syntax to allow this?

**Comment by alexey-milovidov** [comment]
One possibility is to allow more than one LIMIT BY sections:

`LIMIT 10 BY a, b LIMIT 5 BY b`

This is not so hard to implement.
But you can already write it with subqueries and we don't have to introduce unusual syntax.
