### ISSUE TITLE
 v22.3.2.2 ASOF join Nullable column error(Not conditional Nullable)

### ISSUE THREAD

**Issue by yingyingqiqi** [ClickHouse/ClickHouse#35565]
> You have to provide the following information whenever possible.

**ASOF left join run error**
``` SQL Error [48] [07000]: Code: 48. DB::Exception: ASOF join over right table Nullable column is not implemented. (NOT_IMPLEMENTED) (version 22.3.2.1)
```

> A clear and concise description of what works not as it is supposed to.

**This error occurs when the right table selects a Nullable column, in the V22.3.2.2 version.(Not conditional Nullable)**

[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

**How to reproduce**

* Which ClickHouse server version to use  *docker   22.3.2.2*
* Which interface to use, if matters  ASOF join
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
```
create table test_left (
`rec_id` String
,`testA` String
,`testB` Nullable(String)
,`valid_from` DateTime64(3, 'Asia/Shanghai')
)
ENGINE = MergeTree()
ORDER BY tuple();

select * from test_right

create table test_right (
`rec_id_right` String
,`testA_right` String
,`testB_right` Nullable(String)
,`valid_from_right` DateTime64(3, 'Asia/Shanghai')
)
ENGINE = MergeTree()
ORDER BY tuple();

insert into test_left values('A001','b','c',now())
insert into test_left values('A002','b','c',now())

insert into test_right values('A001','b','c',now())
insert into test_right values('A002','b','c',now())

```
* Queries to run that lead to unexpected result
When running the following statement, appear this mistake：
SQL erro [48] [07000]: Code: 48. DB::Exception: ASOF join over right table Nullable column is not implemented. (NOT_IMPLEMENTED) (version 22.3.2.1)
```
select * from test_left 
ASOF left join (select rec_id_right,testA_right,valid_from_right,testB_right from test_right)  as test_right
on test_left.rec_id = test_right.rec_id_right 
and test_left.valid_from < test_right.valid_from_right
```
When removing `testB_right` Nullable columns, normal, as follows
```
select * from test_left 
ASOF left join (select rec_id_right,testA_right,valid_from_right from test_right)  as test_right
on test_left.rec_id = test_right.rec_id_right 
and test_left.valid_from < test_right.valid_from_right
```

> If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/48437786/159870311-f2b88c64-b6a7-4590-aa5e-b29aee86e9c8.png)

**Comment by Avogar** [comment]
@vdimir can you look at it?
