### ISSUE TITLE
Does async insert support WAL?

### ISSUE THREAD

**Issue by etah000** [ClickHouse/ClickHouse#35603]
It seems that "async insert" does not support WAL.  It will cause data loss when a server suddenly crashes down.

**Comment by den-crane** [comment]
>server suddenly crashes down.
CH server or hardware server / outage?

Async insert does not change MergeTree insert behavior. 
By default data inserted into MergeTree is not synced to disk and does not guaranteed to survive unexpected hardware reboot. 

You can use mergeTree setting fsync_after_insert + fsync_part_directory

```
 fsync_after_insert                        │ 0     │       0 │ Do fsync for every inserted part. Significantly decreases performance of inserts, not recommended to use with wide parts.
 fsync_part_directory                      │ 0     │       0 │ Do fsync for part directory after all part operations (writes, renames, etc.).
───────────────────────────────────────────┴───────┴─────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

**Comment by etah000** [comment]
"async insert" puts small inserts in its cache. If it does not write WAL, CH will loss data when a server crashed.  This feature should have no relation with CH's "fsync write".

I want to make sure whether it supports WAL or not.

**Comment by den-crane** [comment]
It does need WAL.

With "async insert" ClickHouse starts to accumulate inserted data in some internal async_insert buffer and **postpone** INSERT commands **responses** until data is written into the **real table**. 
For example by default `async_insert_busy_timeout_ms=200` and `async_insert_max_data_size=100000 (bytes)`, when one this limits has reached, the inserted from the async_insert buffer will be flushed/written into the real table and INSERT command will return success (OK result).

**Comment by fkuner** [comment]
> 

But If we set `wait_for_async=0`, the client seems not to wait for this response.

**Comment by fkuner** [comment]
> 

Thanks. By the way, is there any comparison or benchmark about `normal insert` and `async insert`. If we open `wait_for_async=1` to let client wait for the response. Can `async insert` gains better throughput than `normal insert`？
