### ISSUE TITLE
Connection hangs frequently or login fails

### ISSUE THREAD

**Issue by kingwide** [ClickHouse/ClickHouse#35606]
[system.table.txt](https://github.com/ClickHouse/ClickHouse/files/8347732/system.table.txt)

clickhouse version is v20.3.12.112-stable ， when ck run long time about 6 month，we often find the error 

The network is in good condition
some simple query changed slow,  set send_logs_level=information'; 
we find the query is blocked,need 100s and more 
<img width="724" alt="slow_query" src="https://user-images.githubusercontent.com/48897677/160051723-35968287-45fd-4577-a1d2-7937b0805aa6.png">

when we signd in datanode
clickhouse-client -h 127.0.0.1 --port 9001 -m -u default --password ****

case 1:
Connecting to *** as user default.
Connecting. Database: (not specified). User: default
Code: 32. DB::Exception: Attempt to read after eof

case 2: hang  about  50s-60s
ClickHouse client version 20.3.12.112.
Connecting to 127.0.0.1:9001 as user default

print clickhouse-server.err.log
2022.03.25 11:02:27.031034 [ 70918 ] {87787686-3596-4ff5-b33b-12faf7cfd4e9} <Error> executeQuery: Code: 210, e.displayText() = DB::NetException: I/O error: Broken pipe, while writing to socket (10.111.72.3:50036) (version 20.3.12.112) (from 10.111.72.3:50036) (in query: ********************** Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xbbad39c in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x50061f9 in /usr/bin/clickhouse
2. ? @ 0x4d7752b in /usr/bin/clickhouse
3. DB::WriteBuffer::next() @ 0x501a695 in /usr/bin/clickhouse
4. DB::TCPHandler::processOrdinaryQueryWithProcessors() @ 0x505a9b9 in /usr/bin/clickhouse
5. DB::TCPHandler::runImpl() @ 0x505f67f in /usr/bin/clickhouse
6. DB::TCPHandler::run() @ 0x5060489 in /usr/bin/clickhouse
7. Poco::Net::TCPServerConnection::start() @ 0x9c75867 in /usr/bin/clickhouse
8. Poco::Net::TCPServerDispatcher::run() @ 0x9c75c5d in /usr/bin/clickhouse
9. Poco::PooledThread::run() @ 0xbc1c07f in /usr/bin/clickhouse
10. Poco::ThreadImpl::runnableEntry(void*) @ 0xbc192e8 in /usr/bin/clickhouse
11. ? @ 0xbc1aa19 in /usr/bin/clickhouse
12. start_thread @ 0x7e65 in /usr/lib64/libpthread-2.17.so
13. __clone @ 0xfe88d in /usr/lib64/libc-2.17.so

2022.03.25 11:03:35.241681 [ 218756 ] {} <Error> ServerErrorHandler: Code: 210, e.displayText() = DB::NetException: Connection reset by peer, while reading from socket (10.111.72.3:55026), Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xbbad39c in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x50061f9 in /usr/bin/clickhouse
2. ? @ 0x4d75702 in /usr/bin/clickhouse
3. DB::TCPHandler::runImpl() @ 0x505fac1 in /usr/bin/clickhouse
4. DB::TCPHandler::run() @ 0x5060489 in /usr/bin/clickhouse
5. Poco::Net::TCPServerConnection::start() @ 0x9c75867 in /usr/bin/clickhouse
6. Poco::Net::TCPServerDispatcher::run() @ 0x9c75c5d in /usr/bin/clickhouse
7. Poco::PooledThread::run() @ 0xbc1c07f in /usr/bin/clickhouse
8. Poco::ThreadImpl::runnableEntry(void*) @ 0xbc192e8 in /usr/bin/clickhouse
9. ? @ 0xbc1aa19 in /usr/bin/clickhouse
10. start_thread @ 0x7e65 in /usr/lib64/libpthread-2.17.so
11. __clone @ 0xfe88d in /usr/lib64/libc-2.17.so
 (version 20.3.12.112)

**This problem is not inevitable，restart ck can resolve the problem. 
after a long time problem will recur**

**Comment by rkozlo** [comment]
This version is obsolete. Relaease date june 2020. Update to newer one first.

**Comment by kingwide** [comment]
> This version is obsolete. Relaease date june 2020. Update to newer one first.

I want to konw if this bug is the same as another bug
https://github.com/ClickHouse/ClickHouse/issues/19409

**Comment by den-crane** [comment]
obsolete versions are not supported
