### ISSUE TITLE
How to merge array column in SummingMergeTree

### ISSUE THREAD

**Issue by leex90** [ClickHouse/ClickHouse#35609]
Hi,

Is there any way to merge the array values instead of just selecting arbitrary one?

```
DROP TABLE IF EXISTS summing;

CREATE TABLE summing (k String, x Array(String) ) ENGINE = SummingMergeTree ORDER BY k;
INSERT INTO summing SELECT 'k1', ['x1'] LIMIT 1;
INSERT INTO summing SELECT 'k1', ['x2'] LIMIT 1;

OPTIMIZE TABLE summing;
SELECT k, x FROM summing;
```
I get this result:
| k  | x      |
|----|--------|
| k1 | ['x1'] |

But I want to get:
| k  | x      |
|----|--------|
| k1 | ['x1', 'x2'] |

I have tried to set column `x` to `AggregateFunction` with some combinator:

```
DROP TABLE IF EXISTS summing;

CREATE TABLE summing (k String, x AggregateFunction(groupUniqArrayArray, Array(String)) ) ENGINE = SummingMergeTree ORDER BY k;
INSERT INTO summing SELECT 'k1', groupUniqArrayArrayState(['x1']) LIMIT 1;
INSERT INTO summing SELECT 'k1', groupUniqArrayArrayState(['x2']) LIMIT 1;

OPTIMIZE TABLE summing;
SELECT groupUniqArray(x) FROM summing;
```

But I still have no luck, Is there any solution to do this?

Thank you

**Comment by den-crane** [comment]
If you use AggregateFunction and -State, you must you -Merge to get final result.

SELECT groupUniqArrayArrayMerge(x) FROM summing
┌─groupUniqArrayArrayMerge(x)─┐
│ ['x1','x2']                 │
└─────────────────────────────┘
```

You can achieve the same with SimpleAggregateFunction 

```
CREATE TABLE summing (k String, x SimpleAggregateFunction(groupUniqArrayArray, Array(String)) ) ENGINE = SummingMergeTree ORDER BY k;
INSERT INTO summing SELECT 'k1', ['x1'] LIMIT 1;
INSERT INTO summing SELECT 'k1', ['x2'] LIMIT 1;

OPTIMIZE TABLE summing;
SELECT groupUniqArrayArray(x) FROM summing;
┌─groupUniqArrayArray(x)─┐
│ ['x1','x2']            │
└────────────────────────┘


SELECT * FROM summing;
┌─k──┬─x───────────┐
│ k1 │ ['x1','x2'] │
└────┴─────────────┘
```
more examples: https://gist.github.com/den-crane/048ce66bc59f5577d56e42d76934682e
