### ISSUE TITLE
Details about how distribute_group_by_no_merge works

### ISSUE THREAD

**Issue by catwang01** [ClickHouse/ClickHouse#35605]
I'm wondering how distribute_group_by_no_merge = 1 works. 

I'm using distribute_group_by_no_merge=1 to optimize the following query

original query: 

```
WITH Date(now()) AS in_endDate
SELECT COUNT(DISTINCT client_id) AS tmp, ext_ingest_date
FROM (
  SELECT client_id
  , Date(ext_ingest_time) AS ext_ingest_date
  FROM test
  WHERE ext_ingest_time >= date_add(day, -54, in_endDate)
      AND ext_ingest_time <= in_endDate
GROUP BY ext_ingest_date
```

And I wrote two queries using distributed_group_by_no_merge = 1 as optimized versions

A:
```
WITH Date(now()) AS in_endDate
SELECT SUM(tmp) AS count_distinct, ext_ingest_date
FROM (
    SELECT COUNT(DISTINCT client_id) AS tmp, ext_ingest_date
    FROM (
      SELECT client_id
      , Date(ext_ingest_time) AS ext_ingest_date
      FROM test
      WHERE ext_ingest_time >= date_add(day, -54, in_endDate)
      AND ext_ingest_time <= in_endDate
    )
    GROUP BY ext_ingest_date SETTINGS distributed_group_by_no_merge = 1
)
GROUP BY ext_ingest_date
```

B: 
```
WITH Date(now()) AS in_endDate
    SELECT SUM(tmp) AS count_distinct, ext_ingest_date
    FROM (
        SELECT
            COUNT(DISTINCT client_id) AS tmp
            , Date(ext_ingest_time) AS ext_ingest_date
            FROM test_table
        WHERE ext_ingest_time >= date_add(day, -54, in_endDate)
        AND ext_ingest_time <= in_endDate
        GROUP BY ext_ingest_date SETTINGS distributed_group_by_no_merge = 1
)
GROUP BY ext_ingest_date
```

And I found the distributed_group_by_no_merge = 1 only works for B.  It seems because I imposed distributed_group_by_no_merge = 1 to a subquery in query A so it doesn't work. 

But I need professional interpretation about the difference between A and B, as well as how distributed_group_by_no_merge = 1  influences these two queries.

Besides, I have a few more questions:
1. I know distributed_group_by_no_merge = 1  can be used to optimize `count distinct`. Does it also work for other aggregations like Min, Max, Sum, and Count?
2. Can we use distributed_group_by_no_merge = 1  along with window functions?

Wait for your response! Thanks a lot!

**Comment by den-crane** [comment]
This is expected. Because of `( )` `select_at_initator ( select distributed ) `

Only part of the query inside `( .... )` is executed at shards.



```
WITH Date(now()) AS in_endDate
SELECT SUM(tmp) AS count_distinct, ext_ingest_date
FROM (
    SELECT COUNT(DISTINCT client_id) AS tmp, ext_ingest_date
    FROM (                                                                                          --- executed on initator
      SELECT client_id                                                                          ---- executed on shards
      , Date(ext_ingest_time) AS ext_ingest_date
      FROM test
      WHERE ext_ingest_time >= date_add(day, -54, in_endDate)
      AND ext_ingest_time <= in_endDate
    )
    GROUP BY ext_ingest_date SETTINGS distributed_group_by_no_merge = 1
)
GROUP BY ext_ingest_date
```

by ` SELECT client_id`  you fetching all data to initator, after that `distributed_group_by_no_merge` loses sense because all data at the iniator.

**Comment by den-crane** [comment]
>I know distributed_group_by_no_merge = 1 can be used to optimize count distinct.
> Does it also work for other aggregations like Min, Max, Sum, and Count?

yes it works with all agg.functions, also check 

```
--optimize_distributed_group_by_sharding_key arg                     Optimize GROUP BY sharding_key queries (by avoiding costly aggregation on the initiator server).
```
it's the automatic mode for `distributed_group_by_no_merge`

------

>Can we use distributed_group_by_no_merge = 1 along with window functions?

No, window functions work at the query initator now. Use `optimize_distributed_group_by_sharding_key`.

**Comment by catwang01** [comment]
Thanks @den-crane ! That helps a lot!
