### ISSUE TITLE
select smth == any(0)

### ISSUE THREAD

**Issue by zlobober** [ClickHouse/ClickHouse#35610]
> You have to provide the following information whenever possible.

Something wrong with `select smth == any(0)`.

https://play.clickhouse.com/play?user=play#c2VsZWN0IDAgPT0gYW55KDAp

The reverse form works fine.

https://play.clickhouse.com/play?user=play#c2VsZWN0IGFueSgwKSA9PSAw

**Does it reproduce on recent release?**

I believe it is an official 22.3.1.1 release.

**Enable crash reporting**

I would leave that to you :)

**How to reproduce**

Use links above.

**Expected behavior**

Second query works fine.

**Error message and/or stacktrace**

```
Code: 62. DB::Exception: Syntax error: failed at position 17 ('0'): 0). Expected one of: SELECT query, possibly with UNION, list of union elements, SELECT query, subquery, possibly with UNION, SELECT subquery, SELECT query, WITH, SELECT. (SYNTAX_ERROR) (version 22.3.1.1)
```

**Comment by CurtizJ** [comment]
Duplicate #35489.

**Comment by alexey-milovidov** [comment]
It is confused with

>, <, <=, >=, =, != ANY (SELECT ...)
