### ISSUE TITLE
clickhouse String length  > 260kb error

### ISSUE THREAD

**Issue by yuiog** [ClickHouse/ClickHouse#35648]
Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 64 
 xxx_html   type              String

ALTER TABLE xxx.xxx
UPDATE
    xxx_html = 'size > 260kb'
WHERE book_page_uid = 'xxx';

**Comment by den-crane** [comment]
Increase https://clickhouse.com/docs/en/operations/settings/settings/#settings-max_query_size

```sql
cat /etc/clickhouse-server/users.d/max_query_size.xml
<?xml version="1.0" ?>
<yandex>
    <profiles>
        <default>
            <max_query_size >1048576</max_query_size >
        </default>
    </profiles>
</yandex>
```
