### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by icedrugs89** [ClickHouse/ClickHouse#35642]
启动报错，挂载的磁盘如下图：
<img width="802" alt="image" src="https://user-images.githubusercontent.com/100941547/160283768-9a294369-2d17-474d-830a-14d726c2e47f.png">
配置data路径如下：
<img width="734" alt="image" src="https://user-images.githubusercontent.com/100941547/160283855-e322a124-1044-4c81-acf2-9e62f8d12177.png">

具体错误如下
<img width="1195" alt="image" src="https://user-images.githubusercontent.com/100941547/160283725-78b1d09a-cabf-4b48-8dc5-5fbfa01dc528.png">

**Comment by den-crane** [comment]
@sulayliu

**Comment by alexey-milovidov** [comment]
The error is below, see `statvfs`. It happens, because ClickHouse cannot get the amount of free space on the filesystem of the data directory.

**Comment by alexey-milovidov** [comment]
```
sudo chmod 777 /data2
sudo chown clickhouse:clickhouse /data2/clickhouse
```

Should help.

**Comment by icedrugs89** [comment]
![image](https://user-images.githubusercontent.com/100941547/160310166-473a3819-ff33-44a7-977c-be2eed13af18.png)
![image](https://user-images.githubusercontent.com/100941547/160310189-0bd21fce-427d-4a3f-896e-148d95034dc6.png)
这个/data2/clickhouse是给了对应权限的

**Comment by sulayliu** [comment]
`ls -alt /`
从根目录看一下 data2 权限
你的操作系统是什么，ClickHouse的版本和安装包是什么？
