### ISSUE TITLE
Is ClickHouse support the remote file system storage?

### ISSUE THREAD

**Issue by openxxx** [ClickHouse/ClickHouse#35649]
I was trying to extend my ClickHouse server's storage. Below is my steps:
Step1: mounting a remote file system with the SSHFS by following this guide: 
https://www.bing.com/videos/search?q=SSHFS+Permanently+mounting+a+remote+folder&docid=608002799119374042&mid=884CCE840EA84A176623884CCE840EA84A176623&view=detail&FORM=VIRE
Step2: create a new storage policy that use the remote file system as the data directory.
Step3: create a mergetree table that use the new storage policy.

After these 3 steps, I tried insert the data on this table but failed. the error msg is: 
Code: 76. DB::Exception: Received from localhost:9000. DB::Exception: Cannot open file /mnt/titan/data/bing_prod/bing_sample_data_rm/tmp_insert_20211001-20211001-0-0_27_27_0/sydney_toosmalltoshow.bin, errno: 1, strerror: Operation not permitted. (CANNOT_OPEN_FILE)

How can I extend my ClickHouse server's storage by connecting to another server's disk? Is there any solution?
Does anyone have any good suggestions? It would be really helpful.

**Comment by rkozlo** [comment]
Maybe privileges missing. But even though, I don't think mounting remote fs(over sshfs) and treat it as another space for regular tables is a good idea.

**Comment by den-crane** [comment]
Officially SSHFS is not supported. It could be issues because CH requires some features from filesystems and these features maybe not implemented in such filesystems (see https://man7.org/linux/man-pages/man2/rename.2.html ).
see https://bugzilla.redhat.com/show_bug.cgi?id=1656826
