### ISSUE TITLE
with,how to execute locally?

### ISSUE THREAD

**Issue by IVitamin-C** [ClickHouse/ClickHouse#35650]
hi,with,how to execute locally?
version : 21.3 lts or 21.8 lts
case:
set load_balancing='in_order';
with (
    select hostName() as h
    from system.one
) as x
select x,hostName() as h,sum(1) as pv 
from cluster({cluster},system,one)
group by x,h

result:
x  h pv
cluster_s1_r1 cluster_s1_r1 1
cluster_s1_r1 cluster_s1_r2 1
cluster_s1_r1 cluster_s2_r1 1
cluster_s1_r1 cluster_s2_r2 1 

I want to get the result：
cluster_s1_r1 cluster_s1_r1 1
cluster_s1_r2 cluster_s1_r2 1
cluster_s2_r1 cluster_s2_r1 1
cluster_s2_r2 cluster_s2_r2 1 

thanks!

**Comment by taiyang-li** [comment]
You can try like this: 
```
select  getMacro('shard'), getMacro('replica'), hostName() from clusterAllReplicas(cluster_name, system, one) order by  getMacro('shard')
```

**Comment by wongxingjun** [comment]
> You can try like this:
> 
> ```
> select  getMacro('shard'), getMacro('replica'), hostName() from clusterAllReplicas(cluster_name, system, one) order by  getMacro('shard')
> ```

Certainly this is a feasible solution to the case, how ever the core issue is to execute "with" subquery locally, not just get the replica and host names.

**Comment by IVitamin-C** [comment]
> 

I just gave a simple example. I want to get a bitmap through with subquery, and then filter it on each node. The distributed query takes a long time and is unnecessary.

**Comment by wongxingjun** [comment]
> > 
> 
> I gave a simple example. however,I want to get a bitmap through "with" subquery, and then filter it on each node. The distributed query takes a long time and is unnecessary.

tbl_1_local is a local table, while tbl_2_dist is a distributed table

`with (
    select groupBitmapMergeState(bits) from tbl_1_local
) as filter

select b
from
( 
  select b
  from tbl_2_dist
  where bitmapContains(filter, b)
)`
