### ISSUE TITLE
Bloom filter for new Object type 

### ISSUE THREAD

**Issue by darkleaf** [ClickHouse/ClickHouse#35661]
Thank for Object type. It's really cool.

I have a json column and I want to use skipping index to speed up `equals`, `has` and other conditions.

```
create table example (
  json JSON,
  INDEX json_idx json TYPE bloom_filter GRANULARITY 1
)
engine = MergeTree()
primary key tuple();

select * from example where json.foo = 'abc';
select * from example where has(json.my_array, 42);

```

So each block should contain a bloom filter of all values of a json.
Is it possible?

**Comment by alexey-milovidov** [comment]
It's not currently possible.

**Comment by alexey-milovidov** [comment]
Also it is unlikely to be implemented in nearest time.
