### ISSUE TITLE
Clickhouse API - Fail using INTERVAL operator

### ISSUE THREAD

**Issue by ArjunMG** [ClickHouse/ClickHouse#35677]
I have a query similar to the following

`CREATE TABLE test_table ( id UInt CODEC(DoubleDelta, LZ4), created_date DateTime CODEC(Delta, LZ4) ) ENGINE = MergeTree() TTL created_date + INTERVAL 60 DAY;`

Tried calling the API like below,
`<apiendpoint>?query=CREATE TABLE test_table ( id UInt CODEC(DoubleDelta, LZ4), created_date DateTime CODEC(Delta, LZ4) ) ENGINE = MergeTree() TTL created_date + INTERVAL 60 DAY;`

But the response is,
```
Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 584: INTERVAL 60 DAY;
. Expected one of: LIKE, GLOBAL NOT IN, PRIMARY KEY, IS, INTO OUTFILE, OR, QuestionMark, BETWEEN, NOT LIKE, AND, Comma, ORDER BY, SETTINGS, IN, SAMPLE BY, ILIKE, FORMAT, Dot, NOT ILIKE, NOT, Arrow, token, NOT IN, GLOBAL IN (version 20.6.3.28 (official build))
```

Seems like an issue while using the INTERVAL operator. I removed the interval operator and tried to create the table using API call and it works fine.

And the CREATE query is working fine through Tabix.IO tool

**Comment by den-crane** [comment]
Your URL is invalid. 

+ is a special character for HTTP URI. You need to encode + as %2B

https://www.urlencoder.org/

CREATE%20TABLE%20test_table%20%28%20id%20UInt%20CODEC%28DoubleDelta%2C%20LZ4%29%2C%20created_date%20DateTime%20CODEC%28Delta%2C%20LZ4%29%20%29%20ENGINE%20%3D%20MergeTree%28%29%20TTL%20created_date%20%2B%20INTERVAL%2060%20DAY%3B

**Comment by den-crane** [comment]
BTW clikhouse HTTP GET allows only readonly queries. 
You must use POST for CREATE TABLE as documented.
