### ISSUE TITLE
s3 zero copy replication in cross region clusters

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#35684]
**Use case**

1. ClickHouse clusters spans across multiple regions. 
2. In order to improve s3 performance (and costs) local s3 buckets being used. 
3. Zero copy replication being used in order to not store the same data twice in single region.

**Describe the solution you'd like**

Ability to set some MergeTree (or disk) setting, which will group replicas in groups which share the same bucket. 
In case of cross group access regular replication will be used.

**Additional context**

AWS support cross-region replication at bucket level, but looks like it can't be applied here

https://aws.amazon.com/about-aws/whats-new/2015/03/amazon-s3-introduces-cross-region-replication/

**Comment by UnamedRus** [comment]
@alexey-milovidov @ianton-ru Can you confirm, that some issues or bugs known with this approach? 

I tried to test it with simple example and looks like it working.  (but i defined different `remote_fs_zero_copy_zookeeper_path` for different buckets)

**Comment by alexey-milovidov** [comment]
@UnamedRus I did not test this approach.
Also it should be noted, that zero copy replication is not production ready in general.

**Comment by ianton-ru** [comment]
@UnamedRus I think it can produce some kind of race condition between AWS replication and ClickHouse replication. In this case when you have two copy of data in different regions better turn off zero-copy replication and AWS bucket replication and use simple ClickHouse replicaion. In any case zero-copy here useless.

**Comment by UnamedRus** [comment]
> In any case zero-copy here useless.

No, 

Imagine situation:
You have multiple replicas per region and have 2-3 regions.

So if you use zero-copy replication you can cut costs on not storing the same data twice (depending on amount of replicas in single region)
