### ISSUE TITLE
Allow to specify `ALL` instead of partition in partition related queries.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#35696]
**Describe the issue**

I want to write `ALTER TABLE t DETACH PARTITION ALL` instead of `ALTER TABLE t DETACH PARTITION tuple()`.

The keyword ALL can have two compatible meanings:
- identify the only partition when table has no partitions;
- all partitions.

**Comment by awakeljw** [comment]
I‘d like to take this task. i will achieve it by add a flag remove_all_partition in AstPartition，when we dropPartition.we can use getDataPartsVector (in MergeTreeData Storage) instead. 

`void StorageMergeTree::dropPartition(const ASTPtr & partition, bool detach, ContextPtr local_context)
{
    DataPartsVector parts_to_remove;
    /// New scope controls lifetime of merge_blocker.
    {
        /// Asks to complete merges and does not allow them to start.
        /// This protects against "revival" of data for a removed partition after completion of merge.
        auto merge_blocker = stopMergesAndWait();
        String partition_id = getPartitionIDFromQuery(partition, local_context);
        const auto * partition_ast = partition->as<ASTPartition>();
        if (partition_ast->remove_all_partition) 
            parts_to_remove = getDataPartsVector();
        else
            parts_to_remove = getDataPartsVectorInPartition(MergeTreeDataPartState::Active, partition_id);
`

**Comment by awakeljw** [comment]
pr: https://github.com/ClickHouse/ClickHouse/pull/35794
