### ISSUE TITLE
use projection data loss 

### ISSUE THREAD

**Issue by xie132339** [ClickHouse/ClickHouse#35699]
0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa21959a in /usr/bin/clickhouse
1. DB::MergeTreeDataPartChecksum::checkEqual(DB::MergeTreeDataPartChecksum const&, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const @ 0x13aebb93 in /usr/bin/clickhouse
2. DB::MergeTreeDataPartChecksums::checkEqual(DB::MergeTreeDataPartChecksums const&, bool) const @ 0x13aec4b4 in /usr/bin/clickhouse
3. DB::checkDataPart(std::__1::shared_ptr<DB::IMergeTreeDataPart const>, std::__1::shared_ptr<DB::IDisk> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::NamesAndTypesList const&, DB::MergeTreeDataPartType const&, std::__1::unordered_set<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, bool, std::__1::function<bool ()>) @ 0x13c87327 in /usr/bin/clickhouse
4. DB::checkDataPart(std::__1::shared_ptr<DB::IMergeTreeDataPart const>, bool, std::__1::function<bool ()>) @ 0x13c8a985 in /usr/bin/clickhouse
5. DB::ReplicatedMergeTreePartCheckThread::checkPart(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x13c35379 in /usr/bin/clickhouse
6. DB::ReplicatedMergeTreePartCheckThread::run() @ 0x13c36d23 in /usr/bin/clickhouse
7. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x12b0cdae in /usr/bin/clickhouse
8. DB::BackgroundSchedulePool::threadFunction() @ 0x12b0f747 in /usr/bin/clickhouse
9. ? @ 0x12b107b0 in /usr/bin/clickhouse
10. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa25a3b7 in /usr/bin/clickhouse
11. ? @ 0xa25ddbd in /usr/bin/clickhouse
12. start_thread @ 0x7e65 in /usr/lib64/libpthread-2.17.so
13. clone @ 0xfe88d in /usr/lib64/libc-2.17.so
 (version 21.12.3.32 (official build))
2022.03.29 09:41:56.234801 [ 18048 ] {} <Error> bp_opc_db.op_order_local (ReplicatedMergeTreePartCheckThread): Part 202006_657_731_3_2744 looks broken. Removing it and will try to fetch.
2022.03.29 09:41:56.234900 [ 18048 ] {} <Warning> bp_opc_db.op_order_local (ReplicatedMergeTreePartCheckThread): Checking if anyone has a part 202006_657_731_3_2744 or covering part.
2022.03.29 09:41:56.237337 [ 18048 ] {} <Error> bp_opc_db.op_order_local (ReplicatedMergeTreePartCheckThread): No replica has part covering 202006_657_731_3_2744 and a merge is impossible: we didn't find smaller parts with either the same min block or the same max block.
2022.03.29 09:41:56.237375 [ 18048 ] {} <Warning> bp_opc_db.op_order_local (ReplicatedMergeTreePartCheckThread): Part 202006_657_731_3_2744 exists in ZooKeeper but not locally and not found on other replica. Removing it from ZooKeeper.
2022.03.29 09:41:56.243560 [ 18048 ] {} <Error> bp_opc_db.op_order_local (ReplicatedMergeTreePartCheckThread): Part 202006_657_731_3_2744 is lost forever.
2022.03.29 09:41:56.243782 [ 17982 ] {} <Warning> bp_opc_db.op_order_local (ReplicatedMergeTreePartCheckThread): Checking part 202006_732_1821_14_2744
2022.03.29 09:41:56.244404 [ 17982 ] {} <Warning> bp_opc_db.op_order_local (ReplicatedMergeTreePartCheckThread): Checking data of part 202006_732_1821_14_2744.
2022.03.29 09:41:56.920251 [ 17982 ] {} <Error> bp_opc_db.op_order_local (ReplicatedMergeTreePartCheckThread): DB::CheckResult DB::ReplicatedMergeTreePartCheckThread::checkPart(const DB::String &): Code: 228. DB::Exception: Unexpected uncompressed size of file app_code.bin in data part. (BAD_SIZE_OF_FILE_IN_DATA_PART), Stack trace (when copying this message, always include the lines below):

**Comment by xie132339** [comment]
use ClickHouse server version 21.12.3.32 (official build).

**Comment by xie132339** [comment]
Lose half of your data
It is uncertain whether it is caused by using projection

**Comment by amosbird** [comment]
Projection is not production ready before 22.3 and there were known issues with part checking in old versions https://github.com/ClickHouse/ClickHouse/issues/34744 . However, it only happens when you run `check table` manually. Please try upgrading to latest LTS version and see if it helps.

**Comment by DipalPrajapati** [comment]
How did you solve this?
