### ISSUE TITLE
Allow to use more memory for zstd decompression.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#35693]
**Use case**

```
SELECT count() FROM url('http://files.pushshift.io/reddit/comments/RC_{2018..2021}-{01..12}.zst', JSONEachRow)
```

```
Code: 561. DB::Exception: Zstd stream encoding failed: error 'Frame requires too much memory for decoding'; zstd version: 1.5.0. (ZSTD_DECODER_FAILED) (version 22.4.1.662)
```

**Describe the solution you'd like**

A setting for max memory usage on decoding.

**Comment by xlwh** [comment]
I'd like to try, thanks!

**Comment by alexey-milovidov** [comment]
> </div><div id=":6slv" style="color: rgb(34, 34, 34); font-family: Roboto, RobotoDraft, Helvetica, Arial, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="qQVYZb"></div><div class="utdU2e"></div><div class="lQs8Hd" jsaction="SN3rtf:rcuQ6b" jscontroller="i3Ohde"></div><div class="btm"></div></div><div class="" style="color: rgb(34, 34, 34); font-family: Roboto, RobotoDraft, Helvetica, Arial, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="aHl" style="margin-left: -38px;"></div><div id=":a7j5" tabindex="-1"></div><div id=":a7fq" class="ii gt" jslog="20277; u014N:xr6bB; 4:W251bGwsbnVsbCxbXV0." style="direction: ltr; margin: 8px 0px 0px; padding: 0px; position: relative; font-size: 0.875rem;"><div id=":6sgx" class="a3s aiL " style="font: small / 1.5 Arial, Helvetica, sans-serif; overflow: hidden;"><div class="adM"><p></p></div><p dir="auto">I'd like to try, thanks!</p></div></div></div>

@hongbin This will be wonderful!

**Comment by wuxiaobai24** [comment]
I think we can configure zstd decompression context's parameter `windowLogMax` to allow zstd use more memory. the zstd decompressor uses `(1 << windowLogMax)` memory at most. Do you think this parameter can solve the problem? May i try to pull a request to fix this issue?

You can read the [comments](https://facebook.github.io/zstd/zstd_manual.html#Chapter6) about `ZSTD_d_windowLogMax` in zsdt manual to find more infomation about `windowLogMax`.

**Comment by alexey-milovidov** [comment]
@wuxiaobai24 Yes, it will solve the task. Let's do it.

**Comment by laurids-reichardt** [comment]
Hi! Was this issue resolved? I'm trying to read the zstd compressed Pushshift dataset as well and get the following error:

```
default> SET zstd_window_log_max=2147483648
[2022-07-13 16:01:57] completed in 5 ms

default> DESCRIBE file('pushshift/RS_2022-05.zst', 'JSONEachRow')
[2022-07-13 16:02:00] Code: 561. DB::Exception: zstd_stream_decoder init failed: Parameter is out of bound. (ZSTD_DECODER_FAILED) (version 22.7.1.1200 (official build))

```

**Comment by laurids-reichardt** [comment]
Sorry, set the wrong `zstd_window_log_max`. Should be 31:

```
SET zstd_window_log_max=31;
```

Seems to work now.
