### ISSUE TITLE
Projection does not work for ORDER BY .. LIMIT ..

### ISSUE THREAD

**Issue by makeavish** [ClickHouse/ClickHouse#35701]
**Describe the unexpected behaviour**
Projection does not work for ORDER BY .. LIMIT ..queries.

**How to reproduce**
```
CREATE TABLE video_log
              (
                  `datetime` DateTime, -- 20,000 records per second
                  `user_id` UInt64, -- Cardinality == 100,000,000
                  `device_id` UInt64, -- Cardinality == 200,000,000
                  `domain` LowCardinality(String), -- Cardinality == 100
                  `bytes` UInt64, -- Ranging from 128 to 1152
                  `duration` UInt64 -- Ranging from 100 to 400
              )
              ENGINE = MergeTree
              PARTITION BY toDate(datetime) -- Daily partitioning
              ORDER BY (user_id, device_id); -- Can only favor one column here
```

```
 CREATE TABLE rng
(
    `user_id_raw` UInt64,
    `device_id_raw` UInt64,
    `domain_raw` UInt64,
    `bytes_raw` UInt64,
    `duration_raw` UInt64
)
ENGINE = GenerateRandom(1024);


INSERT INTO video_log SELECT
    toUnixTimestamp(toDateTime(today()))
       + (rowNumberInAllBlocks() / 20000),
    user_id_raw % 100000000 AS user_id,
    device_id_raw % 200000000 AS device_id,
    domain_raw % 100,
    (bytes_raw % 1024) + 128,
    (duration_raw % 300) + 100
FROM rng
LIMIT 10000000;

```

Adding projections:

```
ALTER TABLE video_log ADD PROJECTION p_norm
(SELECT
                 datetime,
                 device_id,
                 bytes,
                 duration
             ORDER BY device_id);

ALTER TABLE video_log MATERIALIZE PROJECTION p_norm;

SET allow_experimental_projection_optimization = 1;
```

Now when I try to run below query then it doesn't use projections and scans all rows:

`SELECT datetime FROM video_log order by device_id limit 1`

I also checked with EXPLAIN and found it's not using projections

**Comment by makeavish** [comment]
@amosbird Please help me here.
Thanks!

**Comment by amosbird** [comment]
Currently normal projections are mainly used to provide a different set of primary indices. It's non-trivial to tell if a projection will work better w.r.t `ORDER BY ... LIMIT ...`

Duplicate https://github.com/ClickHouse/ClickHouse/issues/32943

**Comment by makeavish** [comment]
Thanks for quick response!

1. Actually I see that projection is not being used at all, is there a way to query directly on a projection instead of depending on query analyser?

2. It's expected that if there is a different set of primary index, then it will be faster to iterate over it when using ORDER BY.

**Comment by amosbird** [comment]
> Actually I see that projection is not being used at all, is there a way to query directly on a projection instead of depending on query analyser?

It's already in the roadmap)  Do you have real use cases for such feature?

**Comment by makeavish** [comment]
Yes, we want to run ORDER BY queries on multiple columns but main table ORDER BY is only useful for a single column.
So if we can query over projection directly then we can use ORDER BY projections instead of depending upon query analyzer/optimizer to decide if projection has to be queried which is unpredictable for us.

**Comment by makeavish** [comment]
Also when I enable `force_optimize_projection` then I am getting this error:
```
Code: 584. DB::Exception: Received from 3.142.77.15:9000. DB::Exception: No projection is used when allow_experimental_projection_optimization = 1 and force_optimize_projection = 1. (PROJECTION_NOT_USED)
```

**Comment by makeavish** [comment]
@amosbird I used Materialized view as a workaround for now.

**Comment by mayank-pant** [comment]
@amosbird Will this get resolved, pls let me know ? I have opened an issue with apache superset which has connection to this issue, assignee of the superset issue is confused whether this issue will get resolved in clickhouse or not. issue link for refernece -> https://github.com/apache/superset/issues/19690

**Comment by amosbird** [comment]
@mayank-pant  The original feature request (automatically select projection if certain query pattern of `ORDER BY ... LIMIT ...` is met) is not easy to achieve. However, we'll provide a way to directly query a projection.

From the superset issue:

>  If a table being queried uses projection(similar to indexes) in DB then clickhouse query optimizer gives inconsistent/wrong result for the query when using both LIMIT and ORDER BY in query.

What do you mean by `inconsistent/wrong result`. If that's the case, please file a bug report.
