### ISSUE TITLE
clickhouse install vs package managers

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#35703]
Scenario: i have clickhouse installed via package manager (apt), and later install one with `clickhouse install`. 

Now package manager will still think that the binary was installed by it, and will not know the proper version and will try to do upgrades & introduce some mess.

Proposal:

clickhouse install should detect the clickhouse installed by package manager and ask to uninstall it first.

**Comment by alexey-milovidov** [comment]
Won't fix because it is non-trivial to do.
