### ISSUE TITLE
Clickhouse support for IBM Z

### ISSUE THREAD

**Issue by vibhaKulka** [ClickHouse/ClickHouse#35700]
Hi Clickhouse community ,

We are working on porting Clickhouse to work on Linux on Z VM . We are exploring the codebase and making code changes to compile and build from source.

We would like to actively engage with the community for any guidance here.

Looking forward to working with you all .

**Comment by filimonov** [comment]
Great. Please create the pull request with the changes.

In general use latest compilers (i hope latest clang is available), use master branch.

Check how CI/CD works in clickhouse: https://github.com/ClickHouse/ClickHouse/tree/master/.github/workflows

Try to run as many tests as you can. Stateless & stateful is a minimal required set. After that try to run integration tests.

**Comment by vibhaKulka** [comment]
@filimonov Thank you , We are using clang14 to build the master branch . 

With our code changes , we were able to get the cmake successful , but we are hitting issues with libunwind . Z support has been added to  https://github.com/libunwind/libunwind but Clickhouse is consuming  from https://github.com/llvm-mirror/libunwind where its not supported by Z.

Can I use https://github.com/libunwind/libunwind  and continue to build on Z and can you suggest any code changes we need to take care of while switching to this source repo. 

Thank you for your help!

**Comment by vibhaKulka** [comment]
@alexey-milovidov Can you please take a look at this question?

**Comment by alexey-milovidov** [comment]
It is possible to use other libunwind only if `system.stack_trace` and `QueryProfiler` will be disabled.
You should include the alternative libunwind's source code in contrib.

The names are:

What we use: LLVM's libunwind;
Alternative: HP's libunwind.

But better to carefully patch LLVM's libunwind to support System Z.

**Comment by vibhaKulka** [comment]
@alexey-milovidov Thank you ! 

We will be trying out with https://github.com/libunwind/libunwind for now to uncover any other build issues. We are also trying to patch LLVM libunwind .

Needed your inputs if this the right path to disable  `QueryProfiler` https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ThreadStatus.h#L179

I could not find any references to disable StackTrace, Can you point it out .  I was looking here https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/StackTrace.h#L25

**Comment by vibhaKulka** [comment]
I am also having trouble integrating https://github.com/libunwind/libunwind , I copied the source code to contrib , but I am not sure on the changes needed to be done to https://github.com/ClickHouse/ClickHouse/blob/master/contrib/libunwind-cmake/CMakeLists.txt to have the ninja build proceed further.

Can you please help me here.

**Comment by alexey-milovidov** [comment]
The `system.stack_trace` table is implemented in StorageSystemStackTrace files.

**Comment by vibhaKulka** [comment]
@alexey-milovidov Hi Alexey, one of our teams worked on patching libunwind for Z support . We received the patch for https://github.com/llvm/llvm-project/tree/main/libunwind which is the latest version of llvm libunwind.

But Clickhouse uses a very old version  https://github.com/llvm-mirror/libunwind , do we have plans to move to the latest ?

We hit few issues while patching the older version .

**Comment by alexey-milovidov** [comment]
Yes, we should update to the latest version of libunwind.
But please note that we have multiple patches on top of it.

The patches are needed for asynchronous unwinding, like this:
https://bugs.llvm.org/show_bug.cgi?id=48186

And the most important patches for signal-safe unwinding.

**Comment by vibhaKulka** [comment]
@alexey-milovidov We have made some progress on the CH for Z , but we are stuck with some clang linking errors with s390x toolchain . 

I have been going through your changes for adding power support and would really appreciate if you could take a look on the build issues for Z , I can work with my team to get a Z ubuntu system to try and debug together.

Would that be a good approach ?  Can I start raising some PR for my initial changes to get them reviewed and see if I am on the right path. 

Thank you so much for your help!

**Comment by vibhaKulka** [comment]
fyi @[SriramaSharma](https://github.com/SriramaSharma)

**Comment by alexey-milovidov** [comment]
Yes, you can set up remote access to the machine for our team.
We don't guarantee that we will be able to help, but I hope this task will be interesting for our team.

**Comment by vibhaKulka** [comment]
@alexey-milovidov Thank you so much , thats great news. This will help us in debugging ay build issues and getting your help to quickly add Z support.

**Comment by vibhaKulka** [comment]
@alexey-milovidov here is the [link](https://developer.ibm.com/gettingstarted/ibm-linuxone) to request for a VM with 120-day free trial .

Can you please fill a form  to request for LinuxOne VM under the section `Get your own enterprise-grade LinuxONE virtual server`

**Comment by vibhaKulka** [comment]
@alexey-milovidov As we have made some progress on CH for Z , can we raise PRs for the changes done for review?

**Comment by alexey-milovidov** [comment]
@vibhaKulka Sure, please send a PR.

> here is the [link](https://developer.ibm.com/gettingstarted/ibm-linuxone) to request for a VM with 120-day free trial .

Interesting, will check it.

**Comment by vibhaKulka** [comment]
@alexey-milovidov I was able to build the CH successfully . 

```
<><><> ~/C/b/programs (master)# ls -l clickhouse*  
-rwxr-xr-x 1 root root 2484719160 May 18 14:06 clickhouse*
lrwxrwxrwx 1 root root         10 May 18 14:06 clickhouse-benchmark -> clickhouse*
lrwxrwxrwx 1 root root         10 May 18 14:06 clickhouse-client -> clickhouse*
lrwxrwxrwx 1 root root         10 May 18 14:06 clickhouse-compressor -> clickhouse*
lrwxrwxrwx 1 root root         10 May 18 14:06 clickhouse-copier -> clickhouse*
lrwxrwxrwx 1 root root         10 May 18 14:06 clickhouse-extract-from-config -> clickhouse*
lrwxrwxrwx 1 root root         10 May 18 14:06 clickhouse-format -> clickhouse*
lrwxrwxrwx 1 root root         10 May 18 14:06 clickhouse-git-import -> clickhouse*
lrwxrwxrwx 1 root root         10 May 18 14:06 clickhouse-keeper -> clickhouse*
lrwxrwxrwx 1 root root         10 May 18 14:06 clickhouse-keeper-converter -> clickhouse*
-rwxr-xr-x 1 root root 1267257344 May 18 13:54 clickhouse-library-bridge*
lrwxrwxrwx 1 root root         10 May 18 14:06 clickhouse-local -> clickhouse*
lrwxrwxrwx 1 root root         10 May 18 14:06 clickhouse-obfuscator -> clickhouse*
-rwxr-xr-x 1 root root 1274054928 May 18 13:54 clickhouse-odbc-bridge*
lrwxrwxrwx 1 root root         10 May 18 14:06 clickhouse-server -> clickhouse*
lrwxrwxrwx 1 root root         10 May 18 14:06 clickhouse-static-files-disk-uploader -> clickhouse*
<>@<><>  ~/C/b/programs (master)# 
```

Can you please let me know how do I test this further ?

```
root@prismoid1:~/ClickHouse/build-s390x/programs# ./clickhouse server
Processing configuration file 'config.xml'.
There is no file 'config.xml', will use embedded config.
2022.05.19 07:00:49.101099 [ 46563 ] {} <Information> SentryWriter: Sending crash reports is disabled
2022.05.19 07:00:49.125320 [ 46563 ] {} <Trace> Pipe: Pipe capacity is 1.00 MiB
2022.05.19 07:00:50.230227 [ 46563 ] {} <Information> : Starting ClickHouse 22.5.1.1 with revision 54462, build id: FBD368BA0B43E82878153E73DFF0F7FCFF1D4F51, PID 46563
2022.05.19 07:00:50.232069 [ 46563 ] {} <Information> Application: starting up
2022.05.19 07:00:50.232094 [ 46563 ] {} <Information> Application: OS name: Linux, version: 5.4.0-109-generic, architecture: s390x
2022.05.19 07:00:50.557509 [ 46563 ] {} <Warning> Context: Linux is not using a fast TSC clock source. Performance can be degraded.
2022.05.19 07:00:50.562948 [ 46563 ] {} <Trace> AsynchronousMetrics: Scanning /sys/class/thermal
2022.05.19 07:00:50.563796 [ 46563 ] {} <Trace> AsynchronousMetrics: Scanning /sys/block
2022.05.19 07:00:50.563892 [ 46563 ] {} <Trace> AsynchronousMetrics: Scanning /sys/devices/system/edac
2022.05.19 07:00:50.563905 [ 46563 ] {} <Trace> AsynchronousMetrics: Scanning /sys/class/hwmon
2022.05.19 07:00:52.725371 [ 46563 ] {} <Warning> Application: Calculated checksum of the binary: 4AFDD28EDF4265CB66A5352FB6587934. There is no information about the reference checksum.
2022.05.19 07:00:52.725599 [ 46563 ] {} <Trace> Application: Will do mlock to prevent executable memory from being paged out. It may take a few seconds.
2022.05.19 07:00:52.796263 [ 46563 ] {} <Trace> Application: The memory map of clickhouse executable has been mlock'ed, total 434.43 MiB
2022.05.19 07:00:52.803726 [ 46563 ] {} <Debug> Application: Set max number of file descriptors to 1048576 (was 1024).
2022.05.19 07:00:52.803753 [ 46563 ] {} <Debug> Application: rlimit on number of threads is 64232
2022.05.19 07:00:52.803781 [ 46563 ] {} <Debug> Application: Initializing DateLUT.
2022.05.19 07:00:52.803795 [ 46563 ] {} <Trace> Application: Initialized DateLUT with time zone 'Etc/UTC'.
2022.05.19 07:00:52.805751 [ 46563 ] {} <Debug> Application: Setting up ./tmp/ to store temporary data in it
2022.05.19 07:00:52.806127 [ 46563 ] {} <Debug> Application: Initiailizing interserver credentials.
2022.05.19 07:00:52.809103 [ 46563 ] {} <Debug> ConfigReloader: Loading config 'config.xml'
Processing configuration file 'config.xml'.
There is no file 'config.xml', will use embedded config.
Saved preprocessed configuration to './preprocessed_configs/config.xml'.
2022.05.19 07:00:52.812514 [ 46563 ] {} <Debug> ConfigReloader: Loaded config 'config.xml', performing update on configuration
2022.05.19 07:00:52.812856 [ 46563 ] {} <Information> Application: Setting max_server_memory_usage was set to 14.14 GiB (15.71 GiB available * 0.90 max_server_memory_usage_to_ram_ratio)
2022.05.19 07:00:52.814102 [ 46563 ] {} <Information> CertificateReloader: One of paths is empty. Cannot apply new configuration for certificates. Fill all paths and try again.
2022.05.19 07:00:52.814117 [ 46563 ] {} <Debug> ConfigReloader: Loaded config 'config.xml', performed update on configuration
2022.05.19 07:00:52.817242 [ 46563 ] {} <Debug> ConfigReloader: Loading config 'config.xml'
Processing configuration file 'config.xml'.
There is no file 'config.xml', will use embedded config.
Saved preprocessed configuration to './preprocessed_configs/config.xml'.
2022.05.19 07:00:52.819744 [ 46563 ] {} <Debug> ConfigReloader: Loaded config 'config.xml', performing update on configuration
2022.05.19 07:00:52.820554 [ 46563 ] {} <Debug> ConfigReloader: Loaded config 'config.xml', performed update on configuration
2022.05.19 07:00:52.820953 [ 46563 ] {} <Debug> Access(user directories): Added users.xml access storage 'users.xml', path: config.xml
2022.05.19 07:00:52.820971 [ 46563 ] {} <Information> Application: Uncompressed cache size was lowered to 7.85 GiB because the system has low amount of memory
2022.05.19 07:00:52.830428 [ 46563 ] {} <Information> Context: Initialized background executor for merges and mutations with num_threads=16, num_tasks=32
2022.05.19 07:00:52.830781 [ 46563 ] {} <Information> Context: Initialized background executor for move operations with num_threads=8, num_tasks=8
2022.05.19 07:00:52.831109 [ 46563 ] {} <Information> Context: Initialized background executor for fetches with num_threads=8, num_tasks=8
2022.05.19 07:00:52.834670 [ 46563 ] {} <Information> Context: Initialized background executor for common operations (e.g. clearing old parts) with num_threads=8, num_tasks=8
2022.05.19 07:00:52.834897 [ 46563 ] {} <Information> Application: Loading user defined objects from ./
2022.05.19 07:00:52.834908 [ 46563 ] {} <Debug> UserDefinedSQLObjectsLoader: loading user defined objects
2022.05.19 07:00:52.834947 [ 46563 ] {} <Debug> Application: Loaded user defined objects
2022.05.19 07:00:52.834952 [ 46563 ] {} <Information> Application: Loading metadata from ./
2022.05.19 07:00:52.896380 [ 46563 ] {} <Information> DatabaseAtomic (system): Metadata processed, database system has 0 tables and 0 dictionaries in total.
2022.05.19 07:00:52.896414 [ 46563 ] {} <Information> TablesLoader: Parsed metadata of 0 tables in 1 databases in 9.2099e-05 sec
2022.05.19 07:00:52.896423 [ 46563 ] {} <Information> TablesLoader: Loading 0 tables with 0 dependency level
2022.05.19 07:00:52.896437 [ 46563 ] {} <Debug> SystemLog: Not creating system.query_log since corresponding section 'query_log' is missing from config
2022.05.19 07:00:52.896449 [ 46563 ] {} <Debug> SystemLog: Not creating system.query_thread_log since corresponding section 'query_thread_log' is missing from config
2022.05.19 07:00:52.896457 [ 46563 ] {} <Debug> SystemLog: Not creating system.part_log since corresponding section 'part_log' is missing from config
2022.05.19 07:00:52.896464 [ 46563 ] {} <Debug> SystemLog: Not creating system.trace_log since corresponding section 'trace_log' is missing from config
2022.05.19 07:00:52.896472 [ 46563 ] {} <Debug> SystemLog: Not creating system.crash_log since corresponding section 'crash_log' is missing from config
2022.05.19 07:00:52.896483 [ 46563 ] {} <Debug> SystemLog: Not creating system.text_log since corresponding section 'text_log' is missing from config
2022.05.19 07:00:52.896493 [ 46563 ] {} <Debug> SystemLog: Not creating system.metric_log since corresponding section 'metric_log' is missing from config
2022.05.19 07:00:52.896500 [ 46563 ] {} <Debug> SystemLog: Not creating system.filesystem_cache_log since corresponding section 'filesystem_cache_log' is missing from config
2022.05.19 07:00:52.896510 [ 46563 ] {} <Debug> SystemLog: Not creating system.asynchronous_metric_log since corresponding section 'asynchronous_metric_log' is missing from config
2022.05.19 07:00:52.896516 [ 46563 ] {} <Debug> SystemLog: Not creating system.opentelemetry_span_log since corresponding section 'opentelemetry_span_log' is missing from config
2022.05.19 07:00:52.896523 [ 46563 ] {} <Debug> SystemLog: Not creating system.query_views_log since corresponding section 'query_views_log' is missing from config
2022.05.19 07:00:52.896532 [ 46563 ] {} <Debug> SystemLog: Not creating system.zookeeper_log since corresponding section 'zookeeper_log' is missing from config
2022.05.19 07:00:52.896543 [ 46563 ] {} <Debug> SystemLog: Not creating system.session_log since corresponding section 'session_log' is missing from config
2022.05.19 07:00:52.896554 [ 46563 ] {} <Debug> SystemLog: Not creating system.transactions_info_log since corresponding section 'transactions_info_log' is missing from config
2022.05.19 07:00:52.896565 [ 46563 ] {} <Debug> SystemLog: Not creating system.processors_profile_log since corresponding section 'processors_profile_log' is missing from config
2022.05.19 07:00:52.906606 [ 46563 ] {} <Information> DatabaseCatalog: Found 0 partially dropped tables. Will load them and retry removal.
2022.05.19 07:00:52.910293 [ 46563 ] {} <Information> DatabaseAtomic (default): Metadata processed, database default has 0 tables and 0 dictionaries in total.
2022.05.19 07:00:52.910305 [ 46563 ] {} <Information> TablesLoader: Parsed metadata of 0 tables in 1 databases in 2.1498e-05 sec
2022.05.19 07:00:52.910309 [ 46563 ] {} <Information> TablesLoader: Loading 0 tables with 0 dependency level
2022.05.19 07:00:52.910314 [ 46563 ] {} <Information> DatabaseAtomic (default): Starting up tables.
2022.05.19 07:00:52.910328 [ 46563 ] {} <Information> DatabaseAtomic (system): Starting up tables.
2022.05.19 07:00:52.911700 [ 46563 ] {} <Information> BackgroundSchedulePool/BgSchPool: Create BackgroundSchedulePool with 128 threads
2022.05.19 07:00:52.916060 [ 46563 ] {} <Debug> Application: Loaded metadata.
2022.05.19 07:00:52.916072 [ 46563 ] {} <Information> Application: Query Profiler and TraceCollector is only tested on x86_64. It also known to not work under qemu-user.
2022.05.19 07:00:52.916082 [ 46563 ] {} <Information> Application: Tasks stats provider: netlink
2022.05.19 07:00:52.916598 [ 46565 ] {} <Trace> BaseDaemon: Received signal 6
2022.05.19 07:00:52.916706 [ 46744 ] {} <Fatal> BaseDaemon: ########################################
2022.05.19 07:00:52.916735 [ 46744 ] {} <Fatal> BaseDaemon: (version 22.5.1.1, build id: FBD368BA0B43E82878153E73DFF0F7FCFF1D4F51) (from thread 46563) (no query) Received signal Aborted (6)
2022.05.19 07:00:52.916746 [ 46744 ] {} <Fatal> BaseDaemon: 
2022.05.19 07:00:52.916766 [ 46744 ] {} <Fatal> BaseDaemon: Stack trace: 0x55671ec
2022.05.19 07:00:53.218768 [ 46744 ] {} <Fatal> BaseDaemon: 0. ./build-s390x/../src/Common/StackTrace.cpp:278: StackTrace::StackTrace(ucontext_t const&) @ 0x55671ec in /root/ClickHouse/build-s390x/programs/clickhouse
2022.05.19 07:00:53.913217 [ 46744 ] {} <Fatal> BaseDaemon: Calculated checksum of the binary: 4AFDD28EDF4265CB66A5352FB6587934. There is no information about the reference checksum.
2022.05.19 07:00:53.913515 [ 46744 ] {} <Information> SentryWriter: Not sending crash report
Aborted (core dumped)
```

**Comment by bkuschel** [comment]
@vibhaKulka we can run the functional tests against the build

**Comment by alexey-milovidov** [comment]
@MariaElena24

If we will be able to make cross-compilation for s390x work in our CI, we can ensure that the build does not break by subsequent changes. We also encourage and help with the review of the pull requests related to the CI, build support, and fixes.

The open-source support for alternative builds is provided on a random-effort basis without guarantees. Whenever we are interested in something we do something.

**Comment by MariaElena24** [comment]
Thanks a lot @alexey-milovidov for your immediate attention on this my request and for the details provided.

I was just wondering if there could be any way to have the support we need even joining a special program (kind of paying program) to be sure we get support when we need in a timely manner.
Or moving to a specific version of the product for which such support is granted.
Can you please confirm?

Thanks a lot.
Ciao
Maria Elena.

**Comment by vibhaKulka** [comment]
@alexey-milovidov We hit an issue with the libunwind while starting the CH server and we are debugging it . 

In Parallel , We were looking to generate CH rpms for consumptions, can you please provide some pointers on how we can generate rpms that can be used in our product .

Thank you!

**Comment by vibhaKulka** [comment]
@alexey-milovidov We are hitting issues with BoringSSL , can you give some pointers if we can use openssl installed on the system instead of boringssl ?

**Comment by alexey-milovidov** [comment]
It can be a temporary workaround for IBM Z, but then we will have to add it to the toolchain to allow cross-compilation.

**Comment by mikehayesclickhouse** [comment]
> Thanks a lot @alexey-milovidov for your immediate attention on this my request and for the details provided.
> 
> I was just wondering if there could be any way to have the support we need even joining a special program (kind of paying program) to be sure we get support when we need in a timely manner. Or moving to a specific version of the product for which such support is granted. Can you please confirm?
> 
> Thanks a lot. Ciao Maria Elena.

@MariaElena24 --- Hey Maria, can you send me an email so we can connect on this topic? mike@clickhouse.com

**Comment by vibhaKulka** [comment]
@alexey-milovidov Thank you for the help in merging our PRs, we were attempting to perform Cross -Compilation  and hit the below error.

Can you please let us know the steps used for cross-compilation for any other platforms ?



```
[2709/4872] Running cpp protocol buffer compiler on clickhouse_grpc.proto
FAILED: src/Server/grpc_protos/clickhouse_grpc.pb.h src/Server/grpc_protos/clickhouse_grpc.pb.cc src/Server/grpc_protos/clickhouse_grpc.grpc.pb.h src/Server/grpc_protos/clickhouse_grpc.grpc.pb.cc 
cd /root/ch-2/ClickHouse/build-s390x/src/Server/grpc_protos && /root/ch-2/ClickHouse/build-s390x/contrib/protobuf/build/protoc --cpp_out /root/ch-2/ClickHouse/build-s390x/src/Server/grpc_protos --grpc_out /root/ch-2/ClickHouse/build-s390x/src/Server/grpc_protos --plugin=protoc-gen-grpc=/root/ch-2/ClickHouse/build-s390x/contrib/grpc/grpc_cpp_plugin -I /root/ch-2/ClickHouse/src/Server/grpc_protos /root/ch-2/ClickHouse/src/Server/grpc_protos/clickhouse_grpc.proto
/root/ch-2/ClickHouse/build-s390x/contrib/grpc/grpc_cpp_plugin: program not found or is not executable
Please specify a program using absolute path or make sure the program is available in your PATH system variable
--grpc_out: protoc-gen-grpc: Plugin failed with status code 1.
[2714/4872] Building CXX object src/Parsers/CMakeFiles/clickhouse_parsers.dir/MySQL/ASTDeclareTableOptions.cpp.o
ninja: build stopped: subcommand failed.
root@dendroid1 ~/c/ClickHouse (remotes/origin/s390x-support) [1]# ls -l build-s390x/contrib/grpc/grpc_cpp_plugin
-rwxr-xr-x 1 root root 30519336 Jul 14 02:16 build-s390x/contrib/grpc/grpc_cpp_plugin*
root@dendroid1 ~/c/ClickHouse (remotes/origin/s390x-support)#
```

Steps :
```
cmake . -DCMAKE_TOOLCHAIN_FILE=cmake/linux/toolchain-s390x.cmake -Bbuild-s390x
post this
ninja -C build-s390x
```
https://github.com/vibhaKulka/ClickHouse/blob/s390x-support/cmake/linux/toolchain-s390x.cmake

**Comment by alexey-milovidov** [comment]
@vibhaKulka simply disable GRPC on this platform.

**Comment by vibhaKulka** [comment]
> @vibhaKulka simply disable GRPC on this platform.

@alexey-milovidov Thank you! cross-compilation was successful with this workaround. But can you please explain the impact of turning this off for s390x. When I build on Z directly , i am able to bring up CH server and client and also perform db operations.

**Comment by hkrutzer** [comment]
@vibhaKulka gRPC is an alternative to the HTTP, native, MySQL etc. interface. I don't think it's in use much and I've heard it labeled as not production ready.
