### ISSUE TITLE
Are there any plans to support zero copy replication for AWS EFS?

### ISSUE THREAD

**Issue by marising** [ClickHouse/ClickHouse#35708]
**Use case**

https://aws.amazon.com/efs/

To mount the AWS EFS to the local machine, there is no need for a replication copy in ClickHouse,  because the EFS with a replication, which can expand the local storage.

Now both s3 and hdfs disk types support zero copy replication #16240,  are there any plans to support EFS?

**Comment by den-crane** [comment]
discussed  https://github.com/ClickHouse/ClickHouse/discussions/33998

**Comment by marising** [comment]
thanks @den-crane
