### ISSUE TITLE
How to dynamically pass parameters to URL table engine？

### ISSUE THREAD

**Issue by nickscut** [ClickHouse/ClickHouse#35710]
CREATE TABLE url_engine_table (word String, value UInt64)
ENGINE=URL('http://127.0.0.1:12345?name=${name}&age=${age}', CSV)

Does this way of writing support？

select * from url_engine_table where name = 'xxx' and age = xxx ，The name parameter is passed directly to the URL，
like this：http://127.0.0.1:12345?name=xxxx&age=xxx

See related document descriptions without explanation

**Comment by kssenii** [comment]
Query parameters are supported but not supported to be put in url currently.

**Comment by nickscut** [comment]
> Query parameters are supported but not supported to be put in url currently.

how to use？is there any examples？

See related document descriptions without explanation

**Comment by joshuataylor** [comment]
Hi,

That seems to be for parameters, not for the url function (https://clickhouse.com/docs/en/sql-reference/table-functions/url/ or https://clickhouse.com/docs/en/engines/table-engines/special/url/ )?

Is there a way to add query parameters dynamically? Or is that a feature request?
