### ISSUE TITLE
Throw exception if WITH TOTALS specified without any aggregate functions

### ISSUE THREAD

**Issue by tdingus** [ClickHouse/ClickHouse#3571]
Use, /usr/bin/clickhouse-client
Connected to ClickHouse server version 1.1.54385.

CREATE TABLE test (time UInt64, v1 UInt64, v2 UInt32) ENGINE = MergeTree ORDER BY time;
INSERT INTO test SELECT number AS time, rand() AS v1, v1 FROM numbers(100);
SELECT bytes_on_disk, data_compressed_bytes, data_uncompressed_bytes FROM system.parts WHERE database = 'default' AND table = 'test' AND active WITH TOTALS;

┌─bytes_on_disk─┬─data_compressed_bytes─┬─data_uncompressed_bytes─┐
│          1993 │                  1570 │                    2000 │

Totals:
┌─bytes_on_disk─┬─data_compressed_bytes─┬─data_uncompressed_bytes─┐
│             0 │                     0 │                       0 │

As you may see, totals are all zeros.

**Comment by alexey-milovidov** [comment]
`WITH TOTALS` make sense only when you apply aggregation (specify at lease one aggregate function).
Totals row will contain total values for each aggregate column in a query and default values (zeros, NULLs, empty strings) for all other columns.

Example for system.parts table:

```
SELECT table, sum(bytes_on_disk), sum(data_compressed_bytes), sum(data_uncompressed_bytes) FROM system.parts WHERE database = 'default' AND table = 'test' AND active GROUP BY table WITH TOTALS;
```

**Comment by alexey-milovidov** [comment]
This is not a bug.
But for better usability we can throw an exception when `WITH TOTALS` is specified without any aggregate functions.

**Comment by sfod** [comment]
I've resolved this issue on September, 2019.
Current master returns exception on the example from the initial comment.

Corresponding pull request is https://github.com/ClickHouse/ClickHouse/pull/6976

I thought that PR name is enough to link it with the issue but apparently I was wrong.
