### ISSUE TITLE
ZooKeeper Out of memory due to ClickHouse

### ISSUE THREAD

**Issue by chandrabhushansingh16** [ClickHouse/ClickHouse#35715]
> Using Clickhouse version: 20.12.4 revision 54442
Number of replicas: 2
Number of shard on each replica: 2
> Getting an issue where zookeeper is going out of memory even after giving heap of 3GiB.
The Number of children in one of replica : 2964027

> It seems due to large number of children it is going OOM.

> Whenever ZooKeeper is crashing- It throws commonly 2 exceptions 
`<Error> DB_1.metrics_v2 (a9cd2831-324f-4bba-8d8d-96ba6c60d6c9): auto DB::StorageReplicatedMergeTree::processQueueEntry
(ReplicatedMergeTreeQueue::SelectedEntryPtr)::(anonymous class)::operator()(DB::StorageReplicatedMergeTree::LogEntryPtr &) const: Poco::Exception. Code: 1000
, e.code() = 111, e.displayText() = Connection refused, Stack trace (when copying this message, always include the lines below):
`

> OR
`DB_0.metrics_v2 (ReplicatedMergeTreeCleanupThread): void DB::ReplicatedMergeTreeCleanupThread::run(): Code: 999, e.displayText() = Coordination::Exception: Transaction failed (No node): Op #0, path: /clickhouse/tables/shard_0/metrics_v2/blocks/202202_7133862859622441240_16962971050174568009, Stack trace (when copying this message, always include the lines below): `

**Comment by den-crane** [comment]
20.12 is obsolete. Upgrade.

>It seems due to large number of children it is going OOM.

Do you use mutations? Alter table update / delete ?

**Comment by chandrabhushansingh16** [comment]
> 20.12 is obsolete. Upgrade.
> 
> > It seems due to large number of children it is going OOM.
> 
> Do you use mutations? Alter table update / delete ?

Hi @den-crane 
Yes, The retention runs every mid night to delete data older than 30 days.

**Comment by alexey-milovidov** [comment]
It indicates that ZooKeeper needs more memory for its operation.

**Comment by den-crane** [comment]
>Yes, The retention runs every mid night to delete data older than 30 days. ALTER TABLE DELETE is used.

Consider table TTL https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/mergetree/#mergetree-table-ttl

**Comment by chandrabhushansingh16** [comment]
> > Yes, The retention runs every mid night to delete data older than 30 days. ALTER TABLE DELETE is used.
> 
> Consider table TTL https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/mergetree/#mergetree-table-ttl

Hi @den-crane 
Is there any work around for existing deployment?
