### ISSUE TITLE
Separator the  resource for Insert and Query，Keep the  insert ability.

### ISSUE THREAD

**Issue by yunchat** [ClickHouse/ClickHouse#3575]
Now  insert and query share the resource ( Max Process Count control) 。 When the query with high TPS，the insert will get error (“error: too many process”).   I think separator the resource for Insert and Query will makes sense.   Ensure enough resource for insert。It looks like Use Yarn， Insert and Query use the different resource quota。 
       Or the simple way , Can we set Ratio for Insert and Query in the total max process count？

**Comment by abyss7** [comment]
Right now I only can advise to update your current configuration settings (like, `max_concurrent_queries` and `max_connections`). Also, there is no such error message "too many process" - maybe you meant: "Too many simultaneous queries". The possible solution in the future is to implement separate configuration options for pools of read-only and read-write queries.

**Comment by yunchat** [comment]
@abyss7  thanks .Yes, I meant the errors message: 'Too many simultaneous queries. Maxmum:xx'。the configuration set "max_concurrent_queries and max_connections" can't guaranteed write stability。Hope the feature like ' pools of read-only and read-write queries' in the future。

**Comment by alexey-milovidov** [comment]
It's easy to add new settings
`max_concurrent_insert_queries`
`max_concurrent_select_queries`

Up for grabs.

**Comment by tangwz** [comment]
Is this active?I'm a newbee.I want to fix it.

**Comment by GinGin3203** [comment]
2 years have passed and still no PRs. Is it really an "easy task"? :)

**Comment by alexey-milovidov** [comment]
@GinGin3203 Yes, the task is easy to implement.
