### ISSUE TITLE
two group by works very slow

### ISSUE THREAD

**Issue by gavrmike** [ClickHouse/ClickHouse#35769]
Hi!

I have clickhouse server version 20.8.2.3 and table with order by keys a, b, c, d, and column e, f with type decimal. All keys columns are string. 

I would like to make query like:
(query1)
```sql
select a, sum(abs(e -f)) as ae
from (
select a, b, c, sum(e) as e, sum(f) as f
from my_table
group by a, b, c
) as sub_query
group by a.
```

When i call it first time it looks very slow for these query and make a lot of useless operation.
I started test some another queries, for example:
(query2)
```sql
select a, sum(e) as e, sum(f) as f
from (
select a, b, c, sum(e) as e, sum(f) as f
from my_table
group by a, b, c
) as sub_query
group by a
```

But these query few times slower than the query:
(query3)
```sql
select a, sum(e) as e, sum(f) as f
from my_table
group by a

```
Semantically these query are identical, but execution time differ signigicanly. 

Additional information, table have around 1kkk rows, for each triplet a, b, c around 7-10 rows, unique "a" values are around thousands. 

Is It possible to speedup query1 and query2?

**Comment by kssenii** [comment]
This clickhouse server version is too old, please check latest versions.

**Comment by den-crane** [comment]
2 reasons

1. https://github.com/ClickHouse/ClickHouse/issues/35096 Aggregation over aggregation is single threaded 
2. There is no automatic optimization to reduce 2 aggregation to one. And you read additional columns `b, c`, they can be heavy to read and aggregate.

**Comment by ongbo** [comment]
You can create a materalized view with tow group
Then query like this
select
  dim1, dime2,  sumMerge(value), avg(value)
group by dim1, dime2

but you should pay attention to my issuse https://github.com/ClickHouse/ClickHouse/issues/38080

**Comment by yej2021** [comment]
@gavrmike Have you soved this problem?

**Comment by helifu** [comment]
> @gavrmike Have you soved this problem?

@nickitat  has fixed this issue. [38295](https://github.com/ClickHouse/ClickHouse/pull/38295)
