### ISSUE TITLE
Does the 19.X version have an ARM installation package or docker image?

### ISSUE THREAD

**Issue by pingguodaren** [ClickHouse/ClickHouse#35795]
We use right Join to supplement the situation that the field is set to 0 when the data is empty. At present, after upgrading to the version of 20.x, there are problems in performing right Join, so we hope to reduce the version to 19.x(arm)

**Comment by pingguodaren** [comment]
@kssenii

**Comment by kssenii** [comment]
No it does not. 19.x version is too old and not supported.
