### ISSUE TITLE
Why system.query_log doesn't have record in system.part_log table  

### ISSUE THREAD

**Issue by Yanbuc** [ClickHouse/ClickHouse#35824]
I enable system.query_log and system.part_log , and  system.query_log table is MergeTree engine, but why I can't find record in
system.part_log.  The sql which i run was 
select * from system.part_log where event_date = toDate(now()) and database = 'system'

**Comment by tom-clickhouse** [comment]
You are using the predicate `database = 'system'` in your query. 

But the system.part_log will only contain entries for part events that happened outside of the systems database.

When you change your predicate to `database = 'default'` then you will see entries for all part events that happened 'today' in your default database.

**Comment by Yanbuc** [comment]
> You are using the predicate `database = 'system'` in your query.
> 
> But the system.part_log will only contain entries for part events that happened outside of the systems database.
> 
> When you change your predicate to `database = 'default'` then you will see entries for all part events that happened 'today' in your default database.

Thanks for your help. ` the system.part_log will only contain entries for part events that happened outside of the systems database ` , so what should i do if i want to monitor tables in system when tables in system belongs to mergeTree. Because I want to monitor merge and if i can't find system tables in system.part_log, i think it will be a problem.

**Comment by alexey-milovidov** [comment]
@Yanbuc, it isn't possible.
