### ISSUE TITLE
Is there any transaction isolation in clickhouse?

### ISSUE THREAD

**Issue by ymmihw** [ClickHouse/ClickHouse#35829]
for example, there is a merge table with 100 columns.

when client A insert some rows, and client B query same row at same time, does client B would get only 50 columns avaiable? 

during the mutation (delete or update data) process, does client would get outdated columns with uptodate columns?

**Comment by UnamedRus** [comment]
> when client A insert some rows, and client B query same row at same time, does client B would get only 50 columns avaiable?

No.

during the mutation (delete or update data) process, does client would get outdated columns with uptodate columns?

Yes, it's possible to see some updated and not updated data yet.

**Comment by ymmihw** [comment]
> > during the mutation (delete or update data) process, does client would get outdated columns with uptodate columns?
> 
> Yes, it's possible to see some updated and not updated data yet.

Thanks for your reply. 

What about merge process? Is it possible to see some updated and not updated data yet in ONE row?

**Comment by UnamedRus** [comment]
> Is it possible to see some updated and not updated data yet in ONE row?

No, part being added to table only when it will be written completely.

**Comment by ymmihw** [comment]
> > Is it possible to see some updated and not updated data yet in ONE row?
> 
> No, part being added to table only when it will be written completely.

> > during the mutation (delete or update data) process, does client would get outdated columns with uptodate columns?
> 
> Yes, it's possible to see some updated and not updated data yet.

So the 'updated and not updated yet data' is in different rows, not in one row. Am I right?

Thanks!!
