### ISSUE TITLE
Most efficient way to get one record for each group?

### ISSUE THREAD

**Issue by wangqinghuan** [ClickHouse/ClickHouse#35826]
`select distinct on (deviceID) deviceID, col1, col2,,, from hb_face_recognition where time >= '2022-04-01' and  time <= '2022-04-02' `
This can give me a record for each deviceID.  It's not efficient when this table is large.
Do you have a better one?

**Comment by nickitat** [comment]
Try this query with `group by` instead of distinct.

**Comment by den-crane** [comment]
Any record?

`select tuple(*) from .. group by deviceID`

`select * from ... limit 1 by deviceID`

**Comment by wangqinghuan** [comment]
> Any record?
> 
> `select tuple(*) from .. group by deviceID`
> 
> `select * from ... limit 1 by deviceID`

Yes, any record.  I'll try.
