### ISSUE TITLE
Nested field structure lost when restarting the server

### ISSUE THREAD

**Issue by OriolLopezMassaguerCNAG** [ClickHouse/ClickHouse#35830]
**Describe what's wrong**

We have a nested field in a table.
The table is created using SET flatten_nested = 0.
When the server is restarted the field is no longer nested (only flattened arrays appear).

**Does it reproduce on recent release?**

version 22.2.3.1

**How to reproduce**

Create a table using:

` 
SET flatten_nested = 0            
` 
` 
CREATE TABLE test.test    
    (     
        id String,  
       nested_field Nested (nf1 String, nf2 String)  
    ) ENGINE = MergeTree ORDER BY id  
`

Recover the table structure using describe:
`
describe test.test
`
`
name           type
id             String
nested_field   Nested(nf1 String, nf2 String) 
`

Restart click-house server.

Recover the table structure using describe:
`
 name               type            
 id                 String                                                                                          
 nested_field.nf1   Array(String)                                                                                   
 nested_field.nf2   Array(String)                                                                                   
`

*Expected behavior**

Recover the initial structure of the table not he flatenned one.

**Comment by kssenii** [comment]
may be @CurtizJ can take a look?
