### ISSUE TITLE
Assume User Defined Function as heavy-to-process in Short Circuit Processing

### ISSUE THREAD

**Issue by akvlad** [ClickHouse/ClickHouse#35841]
**Use case**

Please look at the next request:
```
SELECT * FROM numbers(1000000) WHERE number % 10000 == 0 and extremely_heavy_udf(number) == 'ok'
```
Now as far as all the functions are "eager" the heavy UDF will drastically reduce performance of the request. 

**Describe the solution you'd like**

As far as I understood after a conversation with @alexey-milovidov you have a "Short Circuit Processing" optimization for simple logical predicates (like conjunctive normal form) doing "lazy calculate" for heavy functions.

So it would be nice to assume all UDF functions as heavy-to-process (which is very close to the truth).

**Comment by kitaisreal** [comment]
Short circuit execution was supported already, but UDF could be executed during query analysis. Fixed that in https://github.com/ClickHouse/ClickHouse/pull/35917 and also added test for short circuit.
