### ISSUE TITLE
How many tables can be created in ClickHouse?

### ISSUE THREAD

**Issue by LGDHuaOPER** [ClickHouse/ClickHouse#35896]
VERSION: 21.3
QUESTION: How many tables can be created in ClickHouse? For the whole, or one database

I have a demand to build one table for one goods every, and the number of goods may have tens of thousands to hundreds of millions, so I need to know the relevant situation.

Please give me some advice. Fuzzy is OK also. Only give the order of magnitude is OK also.

**Comment by alexey-milovidov** [comment]
You should better create single table and put all goods there. Use ORDER BY key for fast queries on goods.

PS. Answering your question:

You can have around 10 000 ReplicatedMergeTree tables, around 100 000 non replicated MergeTree tables and around 1 000 000 StripeLog tables per server.

**Comment by LGDHuaOPER** [comment]
> You should better create single table and put all goods there. Use ORDER BY key for fast queries on goods.
> 
> PS. Answering your question:
> 
> You can have around 10 000 ReplicatedMergeTree tables, around 100 000 non replicated MergeTree tables and around 1 000 000 StripeLog tables per server.

Thank you very much for your reply! Let me ask one more question. Whether each server refers to the limitations of the program? Are there any restrictions on the same database?

**Comment by alexey-milovidov** [comment]
ClickHouse has no restrictions on the number of tables.

Too large number of tables will result of bad performance, long startup time, high memory consumption, high network traffic and CPU usage.

The numbers are from my practice.
