### ISSUE TITLE
Parse collations in CREATE TABLE, throw exception or ignore.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#35892]
**Use case**

Easy migration from MySQL.

**Describe the solution you'd like**

Syntax like `x varchar(255) COLLATE utf8_unicode_ci NOT NULL,` should be parsed and supported on AST level.
Interpreter should throw exception if collation is provided, unless a setting `compatibility_ignore_collation_in_create_table` is set to 1 (in that case they are ignored).

**Comment by yuuch** [comment]
I can take this work. Could you please assignme
