### ISSUE TITLE
Parse AUTO_INCREMENT in CREATE TABLE, throw exception or ignore.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#35893]
**Use case**

Easy migration from MySQL.

**Describe the solution you'd like**

Syntax like `x int(11) NOT NULL AUTO_INCREMENT,` should be parsed and supported on AST level.
Interpreter should throw exception, unless a setting `compatibility_ignore_auto_increment_in_create_table` is set to 1 (in that case it is ignored).

**Comment by awakeljw** [comment]
keyword.ignore(AUTO_INCREMENT) if compatibility_ignore_auto_increment_in_create_table=1 ?

**Comment by yuuch** [comment]
For MySQL ENGINE?

**Comment by vdimir** [comment]
We have similar thing in https://github.com/ClickHouse/ClickHouse/issues/35892
Maybe it's better to create one option, like `compatibility_ignore_mysql_features_in_create`, because they all do almost the same, what do you think?

**Comment by devcrafter** [comment]
From a user perspective, it looks as the right thing to do, - just set one option. But from a flexibility point of view, it can be desirable to not ignore a specific keyword(s) (I'm not really know use cases here, just logically)
So, probably, provide both is a viable option here.

Opinions?
