### ISSUE TITLE
Test 00140_rename `DB::Exception: Cannot drop or rename test.hits, because some tables depend on it: db_dict.cache_hits`

### ISSUE THREAD

**Issue by nickitat** [ClickHouse/ClickHouse#35905]
`2022-04-02 03:32:18 [cc2342a20ed8] 2022.04.02 03:32:18.009225 [ 1041 ] {5ed14b87-6522-4a8c-bd4d-36a1b8fa5483}  executeQuery: Code: 630. DB::Exception: Cannot drop or rename test.hits, because some tables depend on it: db_dict.cache_hits. (HAVE_DEPENDENT_OBJECTS) (version 22.4.1.1162) (from [::1]:58312) (comment: 00140_rename.sql) (in query: RENAME TABLE test.hits TO test.visits_tmp, test.visits TO test.hits, test.visits_tmp TO test.visits;), Stack trace (when copying this message, always include the lines below):`

[test run](https://s3.amazonaws.com/clickhouse-test-reports/35612/9982b49549eba5b417a323aa6592c84fb896c6f2/stateful_tests__debug__actions_.html)

**Comment by tavplubix** [comment]
It happened because of `00157_cache_dictionary` test failure. We can add `set check_table_dependencies=0` to `00140_rename`, but `00157_cache_dictionary` should be fixed anyway.

**Comment by alexey-milovidov** [comment]
The last failure was in February:

https://play.clickhouse.com/play?user=play#U0VMRUNUIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgcmVwb3J0X3VybApGUk9NIGNoZWNrcwpXSEVSRSBjaGVja19zdGFydF90aW1lID49IG5vdygpIC0gSU5URVJWQUwgMSBZRUFSCiAgICBBTkQgcHVsbF9yZXF1ZXN0X251bWJlciA9IDAKICAgIEFORCB0ZXN0X3N0YXR1cyAhPSAnU0tJUFBFRCcKICAgIEFORCAodGVzdF9zdGF0dXMgTElLRSAnRiUnIE9SIHRlc3Rfc3RhdHVzIExJS0UgJ0UlJykgCiAgICBBTkQgY2hlY2tfc3RhdHVzICE9ICdzdWNjZXNzJwogICAgQU5EIHBvc2l0aW9uKHRlc3RfbmFtZSwgJzAwMTQwX3JlbmFtZScpID4gMApPUkRFUiBCWSBjaGVja19zdGFydF90aW1l
