### ISSUE TITLE
How to track down what contributes to "Too many simultaneous queries"

### ISSUE THREAD

**Issue by YoannBuch** [ClickHouse/ClickHouse#35903]
Hi there,

I'm running into some `Too many simultaneous queries. Maximum: 120.` errors.

Yet I cannot figure out where these queries come from.

Here is what my monitoring tells me:
- `Query`: 120
- `SelectQuery`: 3
- `InsertQuery`: 0
- `FailedQuery`; 13

It does not add up.

Is there any other metric I could check?
Or other methods to understand where these extra queries come from?

![Screenshot from 2022-04-04 12-51-20](https://user-images.githubusercontent.com/513669/161529207-a8d3ba12-a5dc-4f35-be7d-9279bdc3514e.png)

Thanks.

**Comment by genzgd** [comment]
Have you look at the system.query_log table?

**Comment by YoannBuch** [comment]
Good call.

I realized that the above monitoring could not report proper values because the underlying queries are probably rejected... 
Only KILL and SELECt to `system.processes` queries are not affected by the `max_concurrent_queries`:
https://github.com/ClickHouse/ClickHouse/blob/75366fc95e510b7ac76759ef670702ae5f488a51/src/Interpreters/ProcessList.cpp#L38-L68

I used the `system.query_log` query and could see that queries piled up most likely because the Zookeeper leader was restarted around that time: seeing many queries failing with errors:
```
Code: 999, e.displayText() = DB::Exception: Cannot allocate block number in ZooKeeper: Coordination::Exception: Cannot push request to queue within operation timeout (Operation timeout) (version 21.3.8.1)
```
or
```
 Cannot allocate block number in ZooKeeper: Coordination::Exception: Session expired (Session expired) (version 21.3.8.1)
```

So my next question would then be, could we at least allow SELECT queries and only reject INSERT queries (which do rely on Zookeeper)?

We now have these 2 settings `max_insert_queries_amount` and `max_select_queries_amount` which I thought may help but these are checked after checking the global `max_concurrent_queries` so it's too late:
https://github.com/ClickHouse/ClickHouse/blob/75366fc95e510b7ac76759ef670702ae5f488a51/src/Interpreters/ProcessList.cpp#L88-L107

That said it sounds we may be able to use the guidance given here to differentiate SELECT and INSERT queries:
https://github.com/ClickHouse/ClickHouse/blob/75366fc95e510b7ac76759ef670702ae5f488a51/src/Interpreters/ProcessList.cpp#L110-L127
