### ISSUE TITLE
22.3lts ,some query performance is too slow

### ISSUE THREAD

**Issue by IVitamin-C** [ClickHouse/ClickHouse#35932]
Hi,
we have some queries running online, and there is a very high time-consuming increase in the 22.3 version test environment.

* Which ClickHouse server version to use
For the same sql, I compared the two versions, 21.8.15 lts and 22.3.2 lts (two replicas of the same shard and the same dateset).
* Which interface to use, if matters
**clickhouse-client of the same version as the clickhouse-server.**

Settings:                             
```{'max_block_size':'4194304','max_insert_block_size':'16777216','max_insert_threads':'10','max_threads':'32','use_uncompressed_cache':'1','background_buffer_flush_schedule_pool_size':'32','background_pool_size':'64','background_move_pool_size':'32','background_fetches_pool_size':'32','background_schedule_pool_size':'64','background_message_broker_schedule_pool_size':'32','background_distributed_schedule_pool_size':'64','distributed_directory_monitor_sleep_time_ms':'1000','distributed_directory_monitor_max_sleep_time_ms':'10000','distributed_directory_monitor_batch_inserts':'1','optimize_move_to_prewhere':'1','load_balancing':'random','skip_unavailable_shards':'1','distributed_product_mode':'allow','insert_quorum':'2','enable_http_compression':'1','send_progress_in_http_headers':'0','preferred_block_size_bytes':'4194304','insert_distributed_sync':'0','max_execution_time':'300','max_ast_elements':'1000000','max_memory_usage':'85899345920','max_memory_usage_for_user':'214748364800','parallel_view_processing':'1','optimize_aggregation_in_order':'1','cancel_http_readonly_queries_on_client_close':'1','max_partitions_per_insert_block':'10000','default_database_engine':'Ordinary','mutations_sync':'1','lock_acquire_timeout':'10','input_format_skip_unknown_fields':'1'}```

* `CREATE TABLE` statements for all tables involved
```sql 
CREATE TABLE db.table0
(
    `ds` Date,
    `x1` String,
    `x2` UInt32,
    `x3` UInt32,
    `x4` UInt32,
    `bm` AggregateFunction(groupBitmap, UInt32)
)
ENGINE = MergeTree
PARTITION BY (ds, x1)
ORDER BY (x2, x3, x4)
SETTINGS index_granularity = 1

CREATE TABLE db.table
(
    `ds` Date,
    `y1` UInt32,
    `x4` UInt32,
    `y2` UInt32,
    `y3` UInt32,
    `bm` AggregateFunction(groupBitmap, UInt32),
    `y4` UInt32 DEFAULT 0,
)
ENGINE = MergeTree
PARTITION BY (ds, y1)
ORDER BY (x4, y2, y3)
SETTINGS index_granularity = 8192, max_parts_in_total = 10000000
```

* Sample data for all these tables, use [clickhouse-obfuscator]
data generation method：
```sql 
CREATE DATABASE IF NOT EXISTS db
ENGINE = Ordinary;
CREATE TABLE db.table0
(
    `ds` Date,
    `x1` String,
    `x2` UInt32,
    `x3` UInt32,
    `x4` UInt32,
    `bm` AggregateFunction(groupBitmap, UInt32)
)
ENGINE = MergeTree
PARTITION BY (ds, x1)
ORDER BY (x2, x3, x4)
SETTINGS index_granularity = 1;

insert into table db.table0
with murmurHash3_32(toUInt32(rand())) as uid
select toDate('2022-03-01')+rand()%7 as ds,
       concat('xx',toString(rand()%10+1)) as x1,
       1 as x2,
       2 as x3,
       bitShiftRight(uid, 22) as x4,
       groupBitmapState(uid)  as bm 
from numbers(1000000000)
where x4%40=0
group by ds,
        x1,
        x2,
        x3,
        x4 ;

CREATE TABLE db.table
(
    `ds` Date,
    `y1` UInt32,
    `x4` UInt32,
    `y2` UInt32,
    `y3` UInt32,
    `bm` AggregateFunction(groupBitmap, UInt32),
    `y4` UInt32 DEFAULT 0
)
ENGINE = MergeTree
PARTITION BY (ds, y1)
ORDER BY (x4, y2, y3)
SETTINGS index_granularity = 8192, max_parts_in_total = 10000000;

insert into table db.table
with murmurHash3_32(toUInt32(rand())) as uid 
select toDate('2022-03-01')+rand()%7 as ds,
       rand()%1000+5000 as y1,
       bitShiftRight(uid, 22) as x4,
       rand()%100 as y2,
       rand()%2000 as y3,
       groupBitmapState(uid)  as bm,
       rand()%1 as y4
from numbers(1000000000)
where x4%40=0
group by ds,
        y1,
        x4,
        y2,
        y3,
        y4;
```

* Queries to run that lead to slow performance
```sql
CREATE TEMPORARY TABLE tmp_acc_hit AS
SELECT
    x1,
    x2,
    x3,
    arrayReduceInRanges('groupBitmapMergeState', [(1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7)], bs) AS bs
FROM
(
    SELECT
        x1,
        x2,
        x3,
        groupArrayInsertAt(b, multiIf(ds = '2022-03-01', 0, ds = '2022-03-02', 1, ds = '2022-03-03', 2, ds = '2022-03-04', 3, ds = '2022-03-05', 4, ds = '2022-03-06', 5, ds = '2022-03-07', 6, 7)) AS bs
    FROM
    (
        SELECT
            x1,
            x2,
            x3,
            ds,
            groupBitmapOrState(bm) AS b
        FROM db.table0
        WHERE ((ds >= '2022-03-01') AND (ds <= '2022-03-07')) AND (((x1 = 'xx1') AND (x2 = 1) AND (x3 = 2)) OR ((x1 = 'xx2') AND (x2 = 1) AND (x3 = 2)) OR ((x1 = 'xx3') AND (x2 = 1) AND (x3 = 2)) OR ((x1 = 'xx4') AND (x2 = 1) AND (x3 = 2)) OR ((x1 = 'xx5') AND (x2 = 1) AND (x3 = 2)) OR ((x1 = 'xx6') AND (x2 = 1) AND (x3 = 2)) OR ((x1 = 'xx7') AND (x2 = 1) AND (x3 = 2)) OR ((x1 = 'xx8') AND (x2 = 1) AND (x3 = 2)) OR ((x1 = 'xx9') AND (x2 = 1) AND (x3 = 2)) OR ((x1 = 'xx10') AND (x2 = 1) AND (x3 = 2))) AND (x4 IN (0, 40, 80, 120, 160, 200, 240, 280, 320, 360, 400, 440, 480, 520, 560, 600, 640, 680, 720, 760, 800, 840, 880, 920, 960, 1000))
        GROUP BY
            x1,
            x2,
            x3,
            ds
    ) AS t_hit
    GROUP BY
        x1,
        x2,
        x3
);


WITH (
        SELECT groupArrayInsertAt(b, multiIf((x1 = 'xx1') AND (x2 = 1) AND (x3 = 2), 0, (x1 = 'xx2') AND (x2 = 1) AND (x3 = 2), 1, (x1 = 'xx3') AND (x2 = 1) AND (x3 = 2), 2, (x1 = 'xx4') AND (x2 = 1) AND (x3 = 2), 3, (x1 = 'xx5') AND (x2 = 1) AND (x3 = 2), 4, (x1 = 'xx6') AND (x2 = 1) AND (x3 = 2), 5, (x1 = 'xx7') AND (x2 = 1) AND (x3 = 2), 6, (x1 = 'xx8') AND (x2 = 1) AND (x3 = 2), 7, (x1 = 'xx9') AND (x2 = 1) AND (x3 = 2), 8, (x1 = 'xx10') AND (x2 = 1) AND (x3 = 2), 9, 10))
        FROM
        (
            SELECT
                x1,
                x2,
                x3,
                bs AS b
            FROM tmp_acc_hit
        )
    ) AS bs
SELECT
    y1,
    x4,
    toString(flat_arr) AS flat_arr,
    toString([bitmapAndCardinality(bmor1, (bs[1])[1]), bitmapAndCardinality(bmor2, (bs[1])[1]), bitmapAndCardinality(bmor3, (bs[1])[1]), bitmapAndCardinality(bmor1, (bs[2])[1]), bitmapAndCardinality(bmor2, (bs[2])[1]), bitmapAndCardinality(bmor3, (bs[2])[1]), bitmapAndCardinality(bmor1, (bs[3])[1]), bitmapAndCardinality(bmor2, (bs[3])[1]), bitmapAndCardinality(bmor3, (bs[3])[1]), bitmapAndCardinality(bmor1, (bs[4])[1]), bitmapAndCardinality(bmor2, (bs[4])[1]), bitmapAndCardinality(bmor3, (bs[4])[1]), bitmapAndCardinality(bmor1, (bs[5])[1]), bitmapAndCardinality(bmor2, (bs[5])[1]), bitmapAndCardinality(bmor3, (bs[5])[1]), bitmapAndCardinality(bmor1, (bs[6])[1]), bitmapAndCardinality(bmor2, (bs[6])[1]), bitmapAndCardinality(bmor3, (bs[6])[1]), bitmapAndCardinality(bmor1, (bs[7])[1]), bitmapAndCardinality(bmor2, (bs[7])[1]), bitmapAndCardinality(bmor3, (bs[7])[1]), bitmapAndCardinality(bmor1, (bs[8])[1]), bitmapAndCardinality(bmor2, (bs[8])[1]), bitmapAndCardinality(bmor3, (bs[8])[1]), bitmapAndCardinality(bmor1, (bs[9])[1]), bitmapAndCardinality(bmor2, (bs[9])[1]), bitmapAndCardinality(bmor3, (bs[9])[1]), bitmapAndCardinality(bmor1, (bs[10])[1]), bitmapAndCardinality(bmor2, (bs[10])[1]), bitmapAndCardinality(bmor3, (bs[10])[1])]) AS flat_arr_2
from (
SELECT
        toString(y1) AS y1,
        toString(x4) AS x4,
        arrayFlatten(groupArrayInsertAt(flat_arr, multiIf(date_ = '2022-03-01', 0, 1))) AS flat_arr,
        groupBitmapOrState(bmor1) AS bmor1,
        groupBitmapOrState(bmor2) AS bmor2,
        groupBitmapOrState(bmor3) AS bmor3
    FROM
    (
        WITH '2022-03-01' AS start_ds
        SELECT
            y1,
            x4,
            groupBitmapOrState(bm) AS bmor1,
            groupBitmapOrStateIf(bm, y2 > 0) AS bmor2,
            groupBitmapOrStateIf(bm, y4 = 1) AS bmor3,
            [sum(y2 * bitmapAndCardinality(bm, (bs[1])[1])), sum(y2 * bitmapAndCardinality(bm, (bs[2])[1])), sum(y2 * bitmapAndCardinality(bm, (bs[3])[1])), sum(y2 * bitmapAndCardinality(bm, (bs[4])[1])), sum(y2 * bitmapAndCardinality(bm, (bs[5])[1])), sum(y2 * bitmapAndCardinality(bm, (bs[6])[1])), sum(y2 * bitmapAndCardinality(bm, (bs[7])[1])), sum(y2 * bitmapAndCardinality(bm, (bs[8])[1])), sum(y2 * bitmapAndCardinality(bm, (bs[9])[1])), sum(y2 * bitmapAndCardinality(bm, (bs[10])[1]))] AS flat_arr,
            start_ds AS date_
        FROM db.table 
        WHERE (ds = start_ds) AND (y1 IN (7063, 5010, 5006, 6788, 6176, 6203, 6769, 6555, 7062, 5119, 5007, 5212, 6814, 6177, 6789, 5095, 4942, 6243, 7061, 6744, 6201, 7196, 6181, 7195, 6178, 5004, 6790, 5008, 6877, 7281, 6791, 6179, 5214, 5005, 7146, 6980, 6322, 5222, 5217, 5137, 6561, 5133, 6937, 5142, 5130, 6885, 7250, 5103, 6867, 7066, 5096, 6868, 6199, 7269, 5131, 6414, 6884, 6560, 5136, 6883, 5158, 6869, 5097, 5132, 5102, 7251, 5219, 4695, 5220, 5202, 4203, 4204, 5098, 6870, 7064, 5101, 5105, 5140, 5135, 5139, 6880, 6194, 5218, 4202, 6655, 5104, 5183, 7245, 5100, 7065, 5099, 6938, 5138, 6881, 5134, 6886, 5141, 5129)) AND (x4 IN (0, 40, 80, 120, 160, 200, 240, 280, 320, 360, 400, 440, 480, 520, 560, 600, 640, 680, 720, 760, 800, 840, 880, 920, 960, 1000)) AND (y4 IN (0, 1))
        GROUP BY
            y1,
            x4
    )
        GROUP BY
        y1,
        x4
) LIMIT 1;
```

**Expected performance**
What are your performance expectation, why do you think they are realistic? Has it been working faster in older ClickHouse releases? Is it working faster in some specific other system?
**21.8.15lts it takes 8-10 seconds to execute,660MB memory is used.**
![image](https://user-images.githubusercontent.com/35019926/161600783-f82ca346-f7bd-4c2d-a410-1ffe492dc4ff.png)
**But on 22.3lts , it takes 80-120 seconds to execute,17GB memory is used.** 
![image](https://user-images.githubusercontent.com/35019926/161600828-cb4e2b95-d0c5-42ec-a890-c0ddeb2ffc66.png)

**Additional context**
Through system.query_thread_log and system.trace_log, it is found that 90% of the time is spent on a thread,this thread only report "{'ContextLock':2,'RealTimeMicroseconds':50410}" on ProfileEvents.
They are performing the same work repeatedly, which may be caused by waiting due to lock competition.
**ps: query_log and flamegraph execution start time is different. The problem can be reproduced stably.
The 21.12.3.32 version is the same as 21.8, without this performance problem.**
![image](https://user-images.githubusercontent.com/35019926/161601453-c2034104-5a1a-40b8-8a4d-00769873723b.png)
![5d76bf68-e0d6-43b8-855b-74d34c9afad0 CPU](https://user-images.githubusercontent.com/35019926/161601757-8e8e66f8-34aa-43f8-be38-aed085d57329.svg)
![5d76bf68-e0d6-43b8-855b-74d34c9afad0 Real](https://user-images.githubusercontent.com/35019926/161601785-47e8d6fd-da49-4f5f-9b97-3fec6ac73518.svg)

**Comment by den-crane** [comment]
https://kb.altinity.com/altinity-kb-setup-and-maintenance/cgroups_k8s/

**Comment by IVitamin-C** [comment]
> https://kb.altinity.com/altinity-kb-setup-and-maintenance/cgroups_k8s/
The machine is a physical machine, not a docker

**Comment by IVitamin-C** [comment]
Machine hardware configuration:
>CPU:Intel(R) Xeon(R) Gold 6133 CPU @ 2.50GHz *2 ,32cores *2
>Mem: 256G 
>Storage: 3.5TB NVME SSD raid0 ,11GB/s

**Comment by IVitamin-C** [comment]
https://github.com/ClickHouse/ClickHouse/issues/34642

**Comment by IVitamin-C** [comment]
22.3lts explain pipeline header=1 this query ,it takes 80-90 seconds to execute

**Comment by IVitamin-C** [comment]
> Hi, we have some queries running online, and there is a very high time-consuming increase in the 22.3 version test environment.
> 
> * Which ClickHouse server version to use
>   For the same sql, I compared the two versions, 21.8.15 lts and 22.3.2 lts (two replicas of the same shard and the same dateset).
> * Which interface to use, if matters
>   **clickhouse-client of the same version as the clickhouse-server.**
> 
> Settings: `{'max_block_size':'4194304','max_insert_block_size':'16777216','max_insert_threads':'10','max_threads':'32','use_uncompressed_cache':'1','background_buffer_flush_schedule_pool_size':'32','background_pool_size':'64','background_move_pool_size':'32','background_fetches_pool_size':'32','background_schedule_pool_size':'64','background_message_broker_schedule_pool_size':'32','background_distributed_schedule_pool_size':'64','distributed_directory_monitor_sleep_time_ms':'1000','distributed_directory_monitor_max_sleep_time_ms':'10000','distributed_directory_monitor_batch_inserts':'1','optimize_move_to_prewhere':'1','load_balancing':'random','skip_unavailable_shards':'1','distributed_product_mode':'allow','insert_quorum':'2','enable_http_compression':'1','send_progress_in_http_headers':'0','preferred_block_size_bytes':'4194304','insert_distributed_sync':'0','max_execution_time':'300','max_ast_elements':'1000000','max_memory_usage':'85899345920','max_memory_usage_for_user':'214748364800','parallel_view_processing':'1','optimize_aggregation_in_order':'1','cancel_http_readonly_queries_on_client_close':'1','max_partitions_per_insert_block':'10000','default_database_engine':'Ordinary','mutations_sync':'1','lock_acquire_timeout':'10','input_format_skip_unknown_fields':'1'}`
> 
> * `CREATE TABLE` statements for all tables involved
> 
> ```sql
> CREATE TABLE db.table0
> (
>     `ds` Date,
>     `x1` String,
>     `x2` UInt32,
>     `x3` UInt32,
>     `x4` UInt32,
>     `bm` AggregateFunction(groupBitmap, UInt32)
> )
> ENGINE = MergeTree
> PARTITION BY (ds, x1)
> ORDER BY (x2, x3, x4)
> SETTINGS index_granularity = 1
> 
> CREATE TABLE db.table
> (
>     `ds` Date,
>     `y1` UInt32,
>     `x4` UInt32,
>     `y2` UInt32,
>     `y3` UInt32,
>     `bm` AggregateFunction(groupBitmap, UInt32),
>     `y4` UInt32 DEFAULT 0,
> )
> ENGINE = MergeTree
> PARTITION BY (ds, y1)
> ORDER BY (x4, y2, y3)
> SETTINGS index_granularity = 8192, max_parts_in_total = 10000000
> ```
> 
> * Sample data for all these tables, use [clickhouse-obfuscator]
>   data generation method：
> 
> ```sql
> CREATE DATABASE IF NOT EXISTS db
> ENGINE = Ordinary;
> CREATE TABLE db.table0
> (
>     `ds` Date,
>     `x1` String,
>     `x2` UInt32,
>     `x3` UInt32,
>     `x4` UInt32,
>     `bm` AggregateFunction(groupBitmap, UInt32)
> )
> ENGINE = MergeTree
> PARTITION BY (ds, x1)
> ORDER BY (x2, x3, x4)
> SETTINGS index_granularity = 1;
> 
> insert into table db.table0
> with murmurHash3_32(toUInt32(rand())) as uid
> select toDate('2022-03-01')+rand()%7 as ds,
>        concat('xx',toString(rand()%10+1)) as x1,
>        1 as x2,
>        2 as x3,
>        bitShiftRight(uid, 22) as x4,
>        groupBitmapState(uid)  as bm 
> from numbers(1000000000)
> where x4%40=0
> group by ds,
>         x1,
>         x2,
>         x3,
>         x4 ;
> 
> CREATE TABLE db.table
> (
>     `ds` Date,
>     `y1` UInt32,
>     `x4` UInt32,
>     `y2` UInt32,
>     `y3` UInt32,
>     `bm` AggregateFunction(groupBitmap, UInt32),
>     `y4` UInt32 DEFAULT 0
> )
> ENGINE = MergeTree
> PARTITION BY (ds, y1)
> ORDER BY (x4, y2, y3)
> SETTINGS index_granularity = 8192, max_parts_in_total = 10000000;
> 
> insert into table db.table
> with murmurHash3_32(toUInt32(rand())) as uid 
> select toDate('2022-03-01')+rand()%7 as ds,
>        rand()%1000+5000 as y1,
>        bitShiftRight(uid, 22) as x4,
>        rand()%100 as y2,
>        rand()%2000 as y3,
>        groupBitmapState(uid)  as bm,
>        rand()%1 as y4
> from numbers(1000000000)
> where x4%40=0
> group by ds,
>         y1,
>         x4,
>         y2,
>         y3,
>         y4;
> ```
> 
> * Queries to run that lead to slow performance
> 
> ```sql
> CREATE TEMPORARY TABLE tmp_acc_hit AS
> SELECT
>     x1,
>     x2,
>     x3,
>     arrayReduceInRanges('groupBitmapMergeState', [(1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7)], bs) AS bs
> FROM
> (
>     SELECT
>         x1,
>         x2,
>         x3,
>         groupArrayInsertAt(b, multiIf(ds = '2022-03-01', 0, ds = '2022-03-02', 1, ds = '2022-03-03', 2, ds = '2022-03-04', 3, ds = '2022-03-05', 4, ds = '2022-03-06', 5, ds = '2022-03-07', 6, 7)) AS bs
>     FROM
>     (
>         SELECT
>             x1,
>             x2,
>             x3,
>             ds,
>             groupBitmapOrState(bm) AS b
>         FROM db.table0
>         WHERE ((ds >= '2022-03-01') AND (ds <= '2022-03-07')) AND (((x1 = 'xx1') AND (x2 = 1) AND (x3 = 2)) OR ((x1 = 'xx2') AND (x2 = 1) AND (x3 = 2)) OR ((x1 = 'xx3') AND (x2 = 1) AND (x3 = 2)) OR ((x1 = 'xx4') AND (x2 = 1) AND (x3 = 2)) OR ((x1 = 'xx5') AND (x2 = 1) AND (x3 = 2)) OR ((x1 = 'xx6') AND (x2 = 1) AND (x3 = 2)) OR ((x1 = 'xx7') AND (x2 = 1) AND (x3 = 2)) OR ((x1 = 'xx8') AND (x2 = 1) AND (x3 = 2)) OR ((x1 = 'xx9') AND (x2 = 1) AND (x3 = 2)) OR ((x1 = 'xx10') AND (x2 = 1) AND (x3 = 2))) AND (x4 IN (0, 40, 80, 120, 160, 200, 240, 280, 320, 360, 400, 440, 480, 520, 560, 600, 640, 680, 720, 760, 800, 840, 880, 920, 960, 1000))
>         GROUP BY
>             x1,
>             x2,
>             x3,
>             ds
>     ) AS t_hit
>     GROUP BY
>         x1,
>         x2,
>         x3
> );
> 
> 
> WITH (
>         SELECT groupArrayInsertAt(b, multiIf((x1 = 'xx1') AND (x2 = 1) AND (x3 = 2), 0, (x1 = 'xx2') AND (x2 = 1) AND (x3 = 2), 1, (x1 = 'xx3') AND (x2 = 1) AND (x3 = 2), 2, (x1 = 'xx4') AND (x2 = 1) AND (x3 = 2), 3, (x1 = 'xx5') AND (x2 = 1) AND (x3 = 2), 4, (x1 = 'xx6') AND (x2 = 1) AND (x3 = 2), 5, (x1 = 'xx7') AND (x2 = 1) AND (x3 = 2), 6, (x1 = 'xx8') AND (x2 = 1) AND (x3 = 2), 7, (x1 = 'xx9') AND (x2 = 1) AND (x3 = 2), 8, (x1 = 'xx10') AND (x2 = 1) AND (x3 = 2), 9, 10))
>         FROM
>         (
>             SELECT
>                 x1,
>                 x2,
>                 x3,
>                 bs AS b
>             FROM tmp_acc_hit
>         )
>     ) AS bs
> SELECT
>     y1,
>     x4,
>     toString(flat_arr) AS flat_arr,
>     toString([bitmapAndCardinality(bmor1, (bs[1])[1]), bitmapAndCardinality(bmor2, (bs[1])[1]), bitmapAndCardinality(bmor3, (bs[1])[1]), bitmapAndCardinality(bmor1, (bs[2])[1]), bitmapAndCardinality(bmor2, (bs[2])[1]), bitmapAndCardinality(bmor3, (bs[2])[1]), bitmapAndCardinality(bmor1, (bs[3])[1]), bitmapAndCardinality(bmor2, (bs[3])[1]), bitmapAndCardinality(bmor3, (bs[3])[1]), bitmapAndCardinality(bmor1, (bs[4])[1]), bitmapAndCardinality(bmor2, (bs[4])[1]), bitmapAndCardinality(bmor3, (bs[4])[1]), bitmapAndCardinality(bmor1, (bs[5])[1]), bitmapAndCardinality(bmor2, (bs[5])[1]), bitmapAndCardinality(bmor3, (bs[5])[1]), bitmapAndCardinality(bmor1, (bs[6])[1]), bitmapAndCardinality(bmor2, (bs[6])[1]), bitmapAndCardinality(bmor3, (bs[6])[1]), bitmapAndCardinality(bmor1, (bs[7])[1]), bitmapAndCardinality(bmor2, (bs[7])[1]), bitmapAndCardinality(bmor3, (bs[7])[1]), bitmapAndCardinality(bmor1, (bs[8])[1]), bitmapAndCardinality(bmor2, (bs[8])[1]), bitmapAndCardinality(bmor3, (bs[8])[1]), bitmapAndCardinality(bmor1, (bs[9])[1]), bitmapAndCardinality(bmor2, (bs[9])[1]), bitmapAndCardinality(bmor3, (bs[9])[1]), bitmapAndCardinality(bmor1, (bs[10])[1]), bitmapAndCardinality(bmor2, (bs[10])[1]), bitmapAndCardinality(bmor3, (bs[10])[1])]) AS flat_arr_2
> from (
> SELECT
>         toString(y1) AS y1,
>         toString(x4) AS x4,
>         arrayFlatten(groupArrayInsertAt(flat_arr, multiIf(date_ = '2022-03-01', 0, 1))) AS flat_arr,
>         groupBitmapOrState(bmor1) AS bmor1,
>         groupBitmapOrState(bmor2) AS bmor2,
>         groupBitmapOrState(bmor3) AS bmor3
>     FROM
>     (
>         WITH '2022-03-01' AS start_ds
>         SELECT
>             y1,
>             x4,
>             groupBitmapOrState(bm) AS bmor1,
>             groupBitmapOrStateIf(bm, y2 > 0) AS bmor2,
>             groupBitmapOrStateIf(bm, y4 = 1) AS bmor3,
>             [sum(y2 * bitmapAndCardinality(bm, (bs[1])[1])), sum(y2 * bitmapAndCardinality(bm, (bs[2])[1])), sum(y2 * bitmapAndCardinality(bm, (bs[3])[1])), sum(y2 * bitmapAndCardinality(bm, (bs[4])[1])), sum(y2 * bitmapAndCardinality(bm, (bs[5])[1])), sum(y2 * bitmapAndCardinality(bm, (bs[6])[1])), sum(y2 * bitmapAndCardinality(bm, (bs[7])[1])), sum(y2 * bitmapAndCardinality(bm, (bs[8])[1])), sum(y2 * bitmapAndCardinality(bm, (bs[9])[1])), sum(y2 * bitmapAndCardinality(bm, (bs[10])[1]))] AS flat_arr,
>             start_ds AS date_
>         FROM db.table 
>         WHERE (ds = start_ds) AND (y1 IN (7063, 5010, 5006, 6788, 6176, 6203, 6769, 6555, 7062, 5119, 5007, 5212, 6814, 6177, 6789, 5095, 4942, 6243, 7061, 6744, 6201, 7196, 6181, 7195, 6178, 5004, 6790, 5008, 6877, 7281, 6791, 6179, 5214, 5005, 7146, 6980, 6322, 5222, 5217, 5137, 6561, 5133, 6937, 5142, 5130, 6885, 7250, 5103, 6867, 7066, 5096, 6868, 6199, 7269, 5131, 6414, 6884, 6560, 5136, 6883, 5158, 6869, 5097, 5132, 5102, 7251, 5219, 4695, 5220, 5202, 4203, 4204, 5098, 6870, 7064, 5101, 5105, 5140, 5135, 5139, 6880, 6194, 5218, 4202, 6655, 5104, 5183, 7245, 5100, 7065, 5099, 6938, 5138, 6881, 5134, 6886, 5141, 5129)) AND (x4 IN (0, 40, 80, 120, 160, 200, 240, 280, 320, 360, 400, 440, 480, 520, 560, 600, 640, 680, 720, 760, 800, 840, 880, 920, 960, 1000)) AND (y4 IN (0, 1))
>         GROUP BY
>             y1,
>             x4
>     )
>         GROUP BY
>         y1,
>         x4
> ) LIMIT 1;
> ```
> 
> **Expected performance** What are your performance expectation, why do you think they are realistic? Has it been working faster in older ClickHouse releases? Is it working faster in some specific other system? **21.8.15lts it takes 8-10 seconds to execute,660MB memory is used.** ![image](https://user-images.githubusercontent.com/35019926/161600783-f82ca346-f7bd-4c2d-a410-1ffe492dc4ff.png) **But on 22.3lts , it takes 80-120 seconds to execute,17GB memory is used.** ![image](https://user-images.githubusercontent.com/35019926/161600828-cb4e2b95-d0c5-42ec-a890-c0ddeb2ffc66.png)
> 
> **Additional context** Through system.query_thread_log and system.trace_log, it is found that 90% of the time is spent on a thread,this thread only report "{'ContextLock':2,'RealTimeMicroseconds':50410}" on ProfileEvents. They are performing the same work repeatedly, which may be caused by waiting due to lock competition. **ps: query_log and flamegraph execution start time is different. The problem can be reproduced stably. The 21.12.3.32 version is the same as 21.8, without this performance problem.** ![image](https://user-images.githubusercontent.com/35019926/161601453-c2034104-5a1a-40b8-8a4d-00769873723b.png) ![5d76bf68-e0d6-43b8-855b-74d34c9afad0 CPU](https://user-images.githubusercontent.com/35019926/161601757-8e8e66f8-34aa-43f8-be38-aed085d57329.svg) ![5d76bf68-e0d6-43b8-855b-74d34c9afad0 Real](https://user-images.githubusercontent.com/35019926/161601785-47e8d6fd-da49-4f5f-9b97-3fec6ac73518.svg)

Added test data generation methods

**Comment by IVitamin-C** [comment]
Added test data generation methods
