### ISSUE TITLE
Wrong tag in Postgres table integration documentation

### ISSUE THREAD

**Issue by mxalis** [ClickHouse/ClickHouse#35955]
**Describe the issue**
Wrong tag in [Postgres table integration documentation ](https://github.com/ClickHouse/ClickHouse/blob/4479b68980f03a5adc30b315c38793ffef95e7d4/docs/en/engines/table-engines/integrations/postgresql.md?plain=1#L46) lines 46 and 53, should be ```<user>``` instead of ```<username>```

**Comment by rfraposa** [comment]
Thanks - fixed for the next release.
