### ISSUE TITLE
about corr

### ISSUE THREAD

**Issue by LvLiangLiang-dev** [ClickHouse/ClickHouse#35979]
Is there any way to generate corr matrix by using corr function...

**Comment by e-mars** [comment]
hi @Faynebupt ,

could provide a simple example of what your schema looks like and what kind of results you are looking to end up with?

For example, do you have a single table with two columns and looking to use the `corr` function to correlate values between them?
or multiple columns where you might be looking to create a matrix for coefficients like `column1-->column2`, `column1-->column3`, `column2-->column3`, etc. 

I might be misunderstanding the use-case, let me know.
thanks.

**Comment by Faynebupt** [comment]
I have a parquet file with 10 columns of data. If I directly use pandas to obtain the corr matrix, it will take a lot of time. If I use Clickhouse's file engine to process it directly, I need to write a lot of Corrs.
Is there any simple way to obtain the corr matrix through Clickhouse
<img width="423" alt="image" src="https://user-images.githubusercontent.com/19455764/162111445-f77581a2-2c38-47fc-801b-3cf1362f0c7b.png">

**Comment by Faynebupt** [comment]
Does Clickhouse  RDs have the idea of making feature engineering API?

**Comment by alexey-milovidov** [comment]
@amosbird Maybe we can implement it with column transformers?
Implement something like `* PRODUCT` (n^2 combinations), `* EXCLUSIVE_PRODUCT` (n^2 combinations except combinations of a column with itself)?

**Comment by alexey-milovidov** [comment]
No, this approach has too many flaws.

**Comment by alexey-milovidov** [comment]
Let's add a function `corrMatrix`, taking an arbitrary number of arguments and returning a 2d array.
Note: this matrix will somewhat redundant - symmetric with 1 on the diagonal, but let's return it as a whole for simplicity.

**Comment by alexey-milovidov** [comment]
I've created a feature request: https://github.com/ClickHouse/ClickHouse/issues/44587.
