### ISSUE TITLE
Int256 and UInt256 columns of a table have a maximum value that is less than expected.

### ISSUE THREAD

**Issue by MyroTk** [ClickHouse/ClickHouse#35970]
When inserting a value larger than `57896044618658097702369839901263932781391731748390190090761097376371310592000` into a Int256 or UInt256 column, the value gets capped at `57896044618658097702369839901263932781391731748390190090761097376371310592000`. This is less than the maximum of Int256 and definitely less than UInt256.

**How to reproduce**

* Which ClickHouse server version to use
22.3-alpine

* Non-default settings, if any
 --allow_experimental_bigint_types "1"

* `CREATE TABLE` statements for all tables involved
`CREATE TABLE table0 (a UInt256) ENGINE = Memory`

* Queries to run that lead to unexpected result
`INSERT INTO table0 SELECT 115792089237316195423570985008687907853269984665640564039457584007913129639935-1`

value on the table:
`57896044618658097702369839901263932781391731748390190090761097376371310592000`

**Expected behavior**
Entire range of UInt256 and Int256 is available to use when table columns are declared with these types. Or a warning that the input to the table has been rounded.

**Comment by Algunenano** [comment]
> INSERT INTO table0 SELECT 115792089237316195423570985008687907853269984665640564039457584007913129639935-1

There is an implicit conversion here to Float64 (and then to UInt64) with a precision loss.

You should do something like:

 ```sql
INSERT INTO table0 SELECT '115792089237316195423570985008687907853269984665640564039457584007913129639935'::UInt256-1
```

**Comment by MyroTk** [comment]
> > INSERT INTO table0 SELECT 115792089237316195423570985008687907853269984665640564039457584007913129639935-1
> 
> There is an implicit conversion here to Float64 (and then to UInt64) with a precision loss.
> 
> You should do something like:
> 
> ```sql
> INSERT INTO table0 SELECT '115792089237316195423570985008687907853269984665640564039457584007913129639935'::UInt256-1
> ```

is `::UInt256` same as `toUint256()` ?

**Comment by Algunenano** [comment]
> is ::UInt256 same as toUint256() ?

Yes. `::Type` is a cast. It's the same as `CAST ('10101010' AS UInt256)` or `toUInt256('10101010')`.

**Comment by MyroTk** [comment]
I'm seeing the issue with divide, even using the type cast.
```
clickhouse1 :) INSERT INTO table0 SELECT '115792089237316195423570985008687907853269984665640564039457584007913129639935'::UInt256/'1'::UInt256

INSERT INTO table0 SELECT CAST('115792089237316195423570985008687907853269984665640564039457584007913129639935', 'UInt256') / CAST('1', 'UInt256')

Query id: 8a3bfccc-37e5-4bc0-9793-e15cb11ae7d3

Ok.

0 rows in set. Elapsed: 0.001 sec. 

clickhouse1 :) select * from table0

SELECT *
FROM table0

Query id: dc77d29c-afcb-4d70-9082-2bd946b607bc

┌─────────────────────────────────────────────────────────────────────────────a─┐
│ 57896044618658097702369839901263932781391731748390190090761097376371310592000 │
└───────────────────────────────────────────────────────────────────────────────┘

**Comment by Algunenano** [comment]
https://clickhouse.com/docs/en/sql-reference/functions/arithmetic-functions/#dividea-b-a-b-operator: 

divide(a, b), a / b operator
Calculates the quotient of the numbers. **The result type is always a floating-point type**. It is not integer division. For integer division, use the ‘intDiv’ function. When dividing by zero you get ‘inf’, ‘-inf’, or ‘nan’.

```
INSERT INTO table0 SELECT intDiv(CAST('115792089237316195423570985008687907853269984665640564039457584007913129639935', 'UInt256'), CAST('1', 'UInt256'))
 ```

```
Select * from table0;

SELECT *
FROM table0

Query id: 50401ad7-ea92-4be2-b07d-3e92004631d4

┌──────────────────────────────────────────────────────────────────────────────a─┐
│ 115792089237316195423570985008687907853269984665640564039457584007913129639935 │
└────────────────────────────────────────────────────────────────────────────────┘
```

**Comment by MyroTk** [comment]
That resolved it.
Thank you.
