### ISSUE TITLE
Received signal Segmentation fault (11)

### ISSUE THREAD

**Issue by jumping** [ClickHouse/ClickHouse#35988]
(you don't have to strictly follow this form)

**Describe the unexpected behaviour**
The server  keeps stopping and starting.

**How to reproduce**
* Which ClickHouse server version to use
ClickHouse server version 19.4.0.
* Which interface to use, if matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

**Expected behavior**

**Error message and/or stacktrace**
2022.04.06 15:09:15.300706 [ 47 ] {} <Error> BaseDaemon: ########################################
2022.04.06 15:09:15.300834 [ 47 ] {} <Error> BaseDaemon: (from thread 38) Received signal Segmentation fault (11).
2022.04.06 15:09:15.300849 [ 47 ] {} <Error> BaseDaemon: Address: NULL pointer.
2022.04.06 15:09:15.300859 [ 47 ] {} <Error> BaseDaemon: Access: read.
2022.04.06 15:09:15.300893 [ 47 ] {} <Error> BaseDaemon: Address not mapped to object.
2022.04.06 15:09:15.391033 [ 47 ] {} <Error> BaseDaemon: 0. /usr/bin/clickhouse-server(memcpy+0x87) [0x71e2a57]
2022.04.06 15:09:15.391150 [ 47 ] {} <Error> BaseDaemon: 1. /usr/bin/clickhouse-server(DB::DataTypeString::serializeBinary(DB::Field const&, DB::WriteBuffer&) const+0x267) [0x6426e37]
2022.04.06 15:09:15.391253 [ 47 ] {} <Error> BaseDaemon: 2. /usr/bin/clickhouse-server(DB::MergeTreeDataPart::MinMaxIndex::store(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<std::shared_ptr<DB::IDataType const>, std::allocator<std::shared_ptr<DB::IDataType const> > > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, DB::MergeTreeDataPartChecksums&) const+0x3e4) [0x67e6254]
2022.04.06 15:09:15.391285 [ 47 ] {} <Error> BaseDaemon: 3. /usr/bin/clickhouse-server(DB::MergedBlockOutputStream::writeSuffixAndFinalizePart(std::shared_ptr<DB::MergeTreeDataPart>&, DB::NamesAndTypesList const*, DB::MergeTreeDataPartChecksums*)+0x10da) [0x684779a]
2022.04.06 15:09:15.391298 [ 47 ] {} <Error> BaseDaemon: 4. /usr/bin/clickhouse-server(DB::MergeTreeDataWriter::writeTempPart(DB::BlockWithPartition&)+0xa54) [0x6807674]
2022.04.06 15:09:15.391332 [ 47 ] {} <Error> BaseDaemon: 5. /usr/bin/clickhouse-server(DB::MergeTreeBlockOutputStream::write(DB::Block const&)+0xc9) [0x67ab149]
2022.04.06 15:09:15.391345 [ 47 ] {} <Error> BaseDaemon: 6. /usr/bin/clickhouse-server(DB::PushingToViewsBlockOutputStream::write(DB::Block const&)+0x4a) [0x69fb58a]
2022.04.06 15:09:15.391375 [ 47 ] {} <Error> BaseDaemon: 7. /usr/bin/clickhouse-server(DB::PushingToViewsBlockOutputStream::process(DB::Block const&, unsigned long)+0x4d0) [0x69fafe0]
2022.04.06 15:09:15.391399 [ 47 ] {} <Error> BaseDaemon: 8. /usr/bin/clickhouse-server(DB::PushingToViewsBlockOutputStream::write(DB::Block const&)+0x9e) [0x69fb5de]
2022.04.06 15:09:15.391410 [ 47 ] {} <Error> BaseDaemon: 9. /usr/bin/clickhouse-server(DB::SquashingBlockOutputStream::writeSuffix()+0x13e) [0x6a03fce]
2022.04.06 15:09:15.391423 [ 47 ] {} <Error> BaseDaemon: 10. /usr/bin/clickhouse-server(DB::copyData(DB::IBlockInputStream&, DB::IBlockOutputStream&, std::atomic<bool>*)+0x4b1) [0x639bb01]
2022.04.06 15:09:15.391443 [ 47 ] {} <Error> BaseDaemon: 11. /usr/bin/clickhouse-server(DB::StorageKafka::streamToViews()+0x627) [0x70d34b7]
2022.04.06 15:09:15.391454 [ 47 ] {} <Error> BaseDaemon: 12. /usr/bin/clickhouse-server(DB::StorageKafka::streamThread()+0x1a8) [0x70d3af8]
2022.04.06 15:09:15.391470 [ 47 ] {} <Error> BaseDaemon: 13. /usr/bin/clickhouse-server(DB::BackgroundSchedulePool::TaskInfo::execute()+0xef) [0x6977b9f]
2022.04.06 15:09:15.391481 [ 47 ] {} <Error> BaseDaemon: 14. /usr/bin/clickhouse-server(DB::BackgroundSchedulePool::threadFunction()+0xba) [0x697896a]
2022.04.06 15:09:15.391498 [ 47 ] {} <Error> BaseDaemon: 15. /usr/bin/clickhouse-server() [0x6978b49]
2022.04.06 15:09:15.391509 [ 47 ] {} <Error> BaseDaemon: 16. /usr/bin/clickhouse-server(ThreadPoolImpl<std::thread>::worker(std::_List_iterator<std::thread>)+0x1e2) [0x7112752]
2022.04.06 15:09:15.391519 [ 47 ] {} <Error> BaseDaemon: 17. /usr/bin/clickhouse-server() [0xb11577f]
2022.04.06 15:09:15.391530 [ 47 ] {} <Error> BaseDaemon: 18. /lib64/libpthread.so.0(+0x7ea5) [0x7f2c72c65ea5]

**Additional context**

**Comment by tavplubix** [comment]
> ClickHouse server version 19.4.0.

This version is not supported (it was released about 3 years ago). List of supported versions is here: https://github.com/ClickHouse/ClickHouse/pulls?q=is%3Aopen+is%3Apr+label%3Arelease
