### ISSUE TITLE
Add setting `forbid_non_metadata_only_alter_queries`

### ISSUE THREAD

**Issue by alesapin** [ClickHouse/ClickHouse#35990]
Need to add a boolean setting `forbid_non_metadata_only_alter_queries` that will be disabled by default. If the setting is enabled ClickHouse must throw an exception in the case when ALTER query will execute mutation of data on disk.

**Comment by xiedeyantu** [comment]
I'd like to take this task

**Comment by CurtizJ** [comment]
The `allow_non_metadata_alters` is the same, isn't it?

**Comment by alesapin** [comment]
Really and I've implemented it...
