### ISSUE TITLE
add last_insert_time to system.tables or system.parts

### ISSUE THREAD

**Issue by ramazanpolat** [ClickHouse/ClickHouse#36013]
**Use case**

Sometimes, data ingestion jobs stuck and it is hard to detect if the user has lots of tables. This is a common problem for users. Querying each and every table like `SELECT max(dt) FROM table` takes too much time. Also, some tables don't even have the DateTime column or worse, they may have a DateTime column but it may not be in the ORDER BY list. So the query takes too much time to execute.

**Describe the solution you'd like**

Having a `last_insert_time` in either `system.table` or `system.parts` would solve this problem. Having both tables to have that column would be even better.

**Describe alternatives you've considered**

Another alternative is to have a system wide materialized view for all tables that acts like INSERT trigger for ALL tables like this:
```sql
CREATE GLOBAL MATERIALIZED VIEW global_insert AS
SELECT 
  database, 
  table, 
  insert_statement, 
  columns,
  now()
FROM
  system.global_insert
```

**Comment by alexey-milovidov** [comment]
I also had some thoughts about this task. Currently it is non trivial to implement, because we don't track insert times in data parts and the approach with trigger does not work with replication.

**Comment by ramazanpolat** [comment]
I've found a workaround (thanks to @den-crane):
```sql
SELECT
    database,
    table,
    max(event_time)
FROM system.part_log
WHERE ((event_type = 'NewPart') OR (event_type = 'DownloadPart')) AND (event_date > (now() - toIntervalDay(5)))
GROUP BY
    database,
    table
```

Do you think this will be a viable alternative?

**Comment by alexey-milovidov** [comment]
It is incorrect, because the time of download does not correspond to the time of INSERT.
One example is replica repair. Another example is downloading of merged parts.

**Comment by ramazanpolat** [comment]
What if we create a `Distributed` table for `system.part_log` table and query only `event_type='NewPart'`? Since we'll be asking for `max(event_time)` and if `event_type='NewPart'` then it will get the most recently **"inserted"** data in all replicas, right?


```sql
SELECT
    database,
    table,
    max(event_time)
FROM part_log_distributed
WHERE (event_type = 'NewPart') AND (event_date > (now() - toIntervalDay(5)))
GROUP BY
    database,
    table
```

**Comment by alexey-milovidov** [comment]
Yes, the trick with part_log could suit as a workaround.
