### ISSUE TITLE
How to find bottlenecks of my queries?

### ISSUE THREAD

**Issue by catwang01** [ClickHouse/ClickHouse#36019]
Hi Team,

I run into some slow queries and want to find the bottlenecks of them. I find there are many metrics in system.query_log and I'm kind of overwhelmed. Is there any guidences or suggestions on how to use system.query_log to perf my queries? Like which columns or events I should pay attention to and what they imply. 

Waiting for your replies. Thanks a lot!

**Comment by yuuch** [comment]
AFAIK, There are some ways to speed up query:
1. ADD INDEX
2. ADD PROJECTION
3. Choose the right ORDER BY and PARTITION BY
 
wish this help you :)

**Comment by catwang01** [comment]
> AFAIK, There are some ways to speed up query:
> 
> 1. ADD INDEX
> 2. ADD PROJECTION
> 3. Choose the right ORDER BY and PARTITION BY
> 
> wish this help you :)

Yes. These are exactly what I'm trying. Thanks! 
Besides, I'm also testing local join + distributed_group_by_no_merge. There are some things we could do to make queries faster. However, I think the more important is to know how to find the bottlenecks of queries and what makes them slow. This leads us to the right way. That's why I'm asking for help here.

**Comment by seanlaff** [comment]
https://clickhouse.com/docs/en/operations/opentelemetry/

<img width="1350" alt="Screen Shot 2022-04-05 at 1 35 11 PM" src="https://user-images.githubusercontent.com/3194832/162336065-ed45bb7d-aa60-48f4-ab4a-a1c15d0a097d.png">

The `Query` spans in the traces are annotated with the query thats being ran

It's been the most useful tool for me. Sometimes I find clickhouse doing unexpected things (sometimes intentionally, sometimes unintentionally)

**Comment by catwang01** [comment]
> https://clickhouse.com/docs/en/operations/opentelemetry/
> 
> <img alt="Screen Shot 2022-04-05 at 1 35 11 PM" width="1350" src="https://user-images.githubusercontent.com/3194832/162336065-ed45bb7d-aa60-48f4-ab4a-a1c15d0a097d.png">
> 
> The `Query` spans in the traces are annotated with the query thats being ran
> 
> It's been the most useful tool for me. Sometimes I find clickhouse doing unexpected things (sometimes intentionally, sometimes unintentionally)

It looks cool! However, I'm only a user of clickhouse server. I don't have the permission to config the server to use tools like this.

**Comment by yuuch** [comment]
> 

by default, there are openTelemetry config in the `config.xml.`
You can just execute:
`SET opentelemetry_start_trace_probability=1`

 `SELECT * FROM system.opentelemetry_span_log` 

otherwise, connect your server manager to edit the `config.xml`

**Comment by catwang01** [comment]
> > 
> 
> by default, there are openTelemetry config in the `config.xml.` You can just execute: `SET opentelemetry_start_trace_probability=1`
> 
> `SELECT * FROM system.opentelemetry_span_log`
> 
> otherwise, connect your server manager to edit the `config.xml`

There is no `system.opentelemetry_span_log` or similar tables in our databases. It seems the server management team has disabled it intentionally for some reason and I don't think they'll help me modify `config.xml` in a short time. 

So, I need to find a more general way to perf my queries and locate what makes them slow.

**Comment by seanlaff** [comment]
`opentelemetry_span_log` by default doesn't show up until you've ran a query with `SET opentelemetry_start_trace_probability=1` (which I find quite annoying)

**Comment by catwang01** [comment]
> 



> `opentelemetry_span_log` by default doesn't show up until you've ran a query with `SET opentelemetry_start_trace_probability=1` (which I find quite annoying)

I don't have permission to run `SET opentelemetry_start_trace_probability=1`. And I tried to use 

```
SELECT 1
SETTINGS opentelemetry_start_trace_probability=1
```

and it doesn't help. I still can't find `system.opentelemetry_span_log`.

**Comment by alexey-milovidov** [comment]
You can use Query Profiler: https://clickhouse.com/docs/en/operations/optimizing-performance/sampling-query-profiler/
and Profile Counters: https://presentations.clickhouse.com/meetup58/building_for_fast/#12
