### ISSUE TITLE
Inaccurate Release Version Number on multiple releases

### ISSUE THREAD

**Issue by muzammilar** [ClickHouse/ClickHouse#36012]
> You have to provide the following information whenever possible.

**Describe what's wrong**

> The `SELECT version()` and the `SELECT * FROM system.build_options` queries return older release versions. On the `22.3.2.2` version of clickhouse is described as `22.3.2.1` (and not `22.3.2.2`). 
Examples: 
https://github.com/ClickHouse/ClickHouse/blob/v22.3.2.2-lts/cmake/autogenerated_versions.txt#L10-L11
https://github.com/ClickHouse/ClickHouse/blob/v22.2.3.5-stable/cmake/autogenerated_versions.txt#L10-L11

**Does it reproduce on recent release?**

Yes. Versions checked
```
v22.3.2.2-lts 
v22.3.3.44-lts
v22.2.3.5-stable
```

**Enable crash reporting**

> No crash

**How to reproduce**

* Which ClickHouse server version to use: 22.3.2.2
* Which interface to use, if matters: clickhouse-client
* Perform a `dpkg -l | grep clickhouse` on the server to check version
* Perform `SELECT version()` or `SELECT * FROM system.build_options` to see the incorrect description of the version

**Expected behavior**

> The correct version `22.3.2.2` should be displayed instead of `22.3.2.1`

**Error message and/or stacktrace**

> N/A

**Additional context**

> This appears to be a CI build problem. It would be best to have a test that uses CI's tag and compare against the built versions

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/35518
