### ISSUE TITLE
Power build is throwing libcxx error and binaries from ci pipeline also throws the error.

### ISSUE THREAD

**Issue by sanjusnair** [ClickHouse/ClickHouse#36025]
Hello there,

As part of a system porting requirement we need to port **clickhouse** along with some other datasources to **PPC64LE**.
We were port clickhouse for a long time now as we ran into several issues, it got delayed. We are now stuck in a problem where we are able to build it from source but not able to run it. 

We are using **master** branch.

compiler **CLANG-LLVM-13**

**Operating system**

> PPC64le ubuntu focal

inside docker container with base image ubuntu:focal itself

**Dockerfile**

> FROM ubuntu:focal
> ARG DEBIAN_FRONTEND=noninteractive
> RUN apt update
> RUN apt install -y git cmake ninja-build python
> RUN git clone --recursive https://github.com/ClickHouse/ClickHouse.git
> RUN apt update -y && apt install -y  build-essential gcc wget xz-utils
> RUN wget https://github.com/llvm/llvm-project/releases/download/llvmorg-13.0.1/clang+llvm-13.0.1-powerpc64le-linux-ubuntu-18.04.5.tar.xz
> RUN tar -xf clang+llvm-13.0.1-powerpc64le-linux-ubuntu-18.04.5.tar.xz
> RUN mv clang+llvm-13.0.1-powerpc64le-linux-ubuntu-18.04.5 clang-13-ppc64le && \
> cd clang-13-ppc64le && \
> cp -R * /usr/local/
> RUN apt install -y libncurses5
> RUN clang --version
> RUN export CMAKE_PREFIX_PATH=/clang-13-ppc64le/bin/
> 
> WORKDIR ClickHouse
> 
> RUN apt install -y ninja-build
> 
> RUN mkdir build-ppc64le
> RUN CC=/clang-13-ppc64le/bin/clang \
> CXX=/clang-13-ppc64le/bin/clang++ \
> cmake . -Bbuild-ppc64le \
> -DCMAKE_TOOLCHAIN_FILE=cmake/linux/toolchain-ppc64le.cmake \
> -DCMAKE_C_COMPILER=/clang-13-ppc64le/bin/clang \
> -DCMAKE_CXX_COMPILER=/clang-13-ppc64le/bin/clang++ && \
> ninja -C build-ppc64le
> 
> RUN cd build-ppc64le && \
> echo ' set(CMAKE_INSTALL_PREFIX "/usr") ' | cat - cmake_install.cmake > temp && mv temp cmake_install.cmake && \
> cat cmake_install.cmake && \
> cmake -P \
> cmake_install.cmake -DCMAKE_INSTALL_PREFIX=/usr
> 
> 
> CMD clickhouse start

### Error ###
The image is built successfully but when doing docker run ie.

When trying to run **clickhouse start**, throwing an 
> Illegal instruction (core dumped)

while debugging with **gdb** got the following trace.

> Program received signal SIGILL, Illegal instruction.
0x00000000275a71b8 in _GLOBAL__sub_I_db_impl_open.cc () at ../contrib/libcxx/include/vector:650
650	../contrib/libcxx/include/vector: No such file or directory.

tried to copy **libxx** files (from clang libcxx using _cp -R /clang-13-ppc64le/include/c++/v1/* ClickHouse/contrib/libcxx_)  to **contrib/include** but nothing worked.

### Any help will be much helpful and appreciated.

_ Thank you _

**Comment by alexey-milovidov** [comment]
What kind of POWER machine - POWER 8, 9?

**Comment by alexey-milovidov** [comment]
What machine instructuion triggered SIGILL?

**Comment by sanjusnair** [comment]
> What kind of POWER machine - POWER 8, 9?

POWER 9


> What machine instructuion triggered SIGILL?
0x00000000275a71b8 in _GLOBAL__sub_I_db_impl_open.cc () at ../contrib/libcxx/include/vector:650
650 ../contrib/libcxx/include/vector: No such file or directory.

**Comment by alexey-milovidov** [comment]
If you write `disas` or `disasm` or `disassembly` in gdb at this moment, what will happen?

**Comment by sanjusnair** [comment]
> If you write `disas` or `disasm` or `disassembly` in gdb at this moment, what will happen?

Program received signal SIGILL, Illegal instruction.
0x00000000275a71b8 in _GLOBAL__sub_I_db_impl_open.cc () at ../contrib/libcxx/include/vector:650
650	../contrib/libcxx/include/vector: No such file or directory.
(gdb) disassemble
Dump of assembler code for function _GLOBAL__sub_I_db_impl_open.cc:
   0x00000000275a7170 <+0>:	addis   r2,r12,230
   0x00000000275a7174 <+4>:	addi    r2,r2,25992
   0x00000000275a7178 <+8>:	mflr    r0
   0x00000000275a717c <+12>:	std     r28,-32(r1)
   0x00000000275a7180 <+16>:	std     r29,-24(r1)
   0x00000000275a7184 <+20>:	std     r30,-16(r1)
   0x00000000275a7188 <+24>:	std     r0,16(r1)
   0x00000000275a718c <+28>:	stdu    r1,-64(r1)
   0x00000000275a7190 <+32>:	addis   r3,r2,72
   0x00000000275a7194 <+36>:	addis   r5,r2,8
   0x00000000275a7198 <+40>:	li      r28,0
   0x00000000275a719c <+44>:	xxlxor  vs0,vs0,vs0
   0x00000000275a71a0 <+48>:	addi    r4,r3,-27136
   0x00000000275a71a4 <+52>:	addis   r3,r2,-231
   0x00000000275a71a8 <+56>:	addi    r30,r5,-14752
   0x00000000275a71ac <+60>:	addi    r3,r3,-7416
   0x00000000275a71b0 <+64>:	mr      r5,r30
   0x00000000275a71b4 <+68>:	std     r28,16(r4)
=> 0x00000000275a71b8 <+72>:	stxv    vs0,0(r4)
   0x00000000275a71bc <+76>:	bl      0x25e0f868 <__plt___cxa_atexit>
   0x00000000275a71c0 <+80>:	ld      r2,24(r1)
   0x00000000275a71c4 <+84>:	addis   r3,r2,72
   0x00000000275a71c8 <+88>:	li      r5,7
   0x00000000275a71cc <+92>:	addi    r4,r3,-27112
   0x00000000275a71d0 <+96>:	stb     r28,-27105(r3)
   0x00000000275a71d4 <+100>:	stb     r5,23(r4)
   0x00000000275a71d8 <+104>:	lis     r5,26723
   0x00000000275a71dc <+108>:	ori     r5,r5,29281
   0x00000000275a71e0 <+112>:	stw     r5,-27112(r3)
   0x00000000275a71e4 <+116>:	lis     r5,25974
   0x00000000275a71e8 <+120>:	ori     r5,r5,26984
   0x00000000275a71ec <+124>:	stw     r5,-27109(r3)
   0x00000000275a71f0 <+128>:	addis   r3,r2,-99
   0x00000000275a71f4 <+132>:	mr      r5,r30
   0x00000000275a71f8 <+136>:	addi    r29,r3,-15064
   0x00000000275a71fc <+140>:	mr      r3,r29
   0x00000000275a7200 <+144>:	bl      0x25e0f868 <__plt___cxa_atexit>
   0x00000000275a7204 <+148>:	ld      r2,24(r1)
   0x00000000275a7208 <+152>:	addis   r3,r2,72
   0x00000000275a720c <+156>:	li      r5,8
   0x00000000275a7210 <+160>:	addi    r4,r3,-27088
   0x00000000275a7214 <+164>:	stb     r5,23(r4)
   0x00000000275a7218 <+168>:	lis     r5,11603
   0x00000000275a721c <+172>:	stb     r28,8(r4)
   0x00000000275a7220 <+176>:	ori     r5,r5,20047
--Type <RET> for more, q to quit, c to continue without paging--c
   0x00000000275a7224 <+180>:	rldic   r5,r5,32,2
   0x00000000275a7228 <+184>:	oris    r5,r5,18772
   0x00000000275a722c <+188>:	ori     r5,r5,20559
   0x00000000275a7230 <+192>:	std     r5,-27088(r3)
   0x00000000275a7234 <+196>:	mr      r3,r29
   0x00000000275a7238 <+200>:	mr      r5,r30
   0x00000000275a723c <+204>:	bl      0x25e0f868 <__plt___cxa_atexit>
   0x00000000275a7240 <+208>:	ld      r2,24(r1)
   0x00000000275a7244 <+212>:	addis   r3,r2,72
   0x00000000275a7248 <+216>:	li      r5,5
   0x00000000275a724c <+220>:	addi    r4,r3,-27064
   0x00000000275a7250 <+224>:	stb     r5,23(r4)
   0x00000000275a7254 <+228>:	lis     r5,28020
   0x00000000275a7258 <+232>:	ori     r5,r5,25188
   0x00000000275a725c <+236>:	stw     r5,-27064(r3)
   0x00000000275a7260 <+240>:	li      r5,112
   0x00000000275a7264 <+244>:	sth     r5,-27060(r3)
   0x00000000275a7268 <+248>:	mr      r3,r29
   0x00000000275a726c <+252>:	mr      r5,r30
   0x00000000275a7270 <+256>:	bl      0x25e0f868 <__plt___cxa_atexit>
   0x00000000275a7274 <+260>:	ld      r2,24(r1)
   0x00000000275a7278 <+264>:	addi    r1,r1,64
   0x00000000275a727c <+268>:	ld      r0,16(r1)
   0x00000000275a7280 <+272>:	ld      r30,-16(r1)
   0x00000000275a7284 <+276>:	ld      r29,-24(r1)
   0x00000000275a7288 <+280>:	ld      r28,-32(r1)
   0x00000000275a728c <+284>:	mtlr    r0
   0x00000000275a7290 <+288>:	blr
   0x00000000275a7294 <+292>:	.long 0x0
   0x00000000275a7298 <+296>:	.long 0x0
   0x00000000275a729c <+300>:	.long 0x0
End of assembler dump.

**Comment by sanjusnair** [comment]
[alexey-milovidov](https://github.com/alexey-milovidov) Could you please provide some guidance on this?

**Comment by pranavpandit1** [comment]
Hello,

We are trying to build ClickHouse on ppc64le VM, and also facing the same issue mentioned by @sanjusnair.
please find below info as required - 

**Branch** : Master
**OS** :  ppc64le: ubuntu
**Exception** :  able to build a package successfully, but while running **clickhouse**  
Illegal instruction (core dumped)

GDB Logs -
gdb
GNU gdb (GDB) Red Hat Enterprise Linux 8.2-15.el8
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "ppc64le-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
(gdb) file clickhouse
Reading symbols from clickhouse...done.
(gdb) r
Starting program: /home/ClickHouse/build/programs/clickhouse
Missing separate debuginfos, use: yum debuginfo-install glibc-2.28-151.el8.ppc64le
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

Program received signal SIGILL, Illegal instruction.
0x0000000014d63488 in _GLOBAL__sub_I_db_impl_open.cc () at ../contrib/libcxx/include/vector:650
650     ../contrib/libcxx/include/vector: No such file or directory.
(gdb) disassemble
Dump of assembler code for function _GLOBAL__sub_I_db_impl_open.cc:
   0x0000000014d63440 <+0>:     lis     r2,10455
   0x0000000014d63444 <+4>:     addi    r2,r2,-27904
   0x0000000014d63448 <+8>:     mflr    r0
   0x0000000014d6344c <+12>:    std     r28,-32(r1)
   0x0000000014d63450 <+16>:    std     r29,-24(r1)
   0x0000000014d63454 <+20>:    std     r30,-16(r1)
   0x0000000014d63458 <+24>:    std     r0,16(r1)
   0x0000000014d6345c <+28>:    stdu    r1,-64(r1)
   0x0000000014d63460 <+32>:    addis   r3,r2,29
   0x0000000014d63464 <+36>:    addis   r5,r2,-27
   0x0000000014d63468 <+40>:    li      r28,0
   0x0000000014d6346c <+44>:    xxlxor  vs0,vs0,vs0
   0x0000000014d63470 <+48>:    addi    r4,r3,19384
   0x0000000014d63474 <+52>:    addis   r3,r2,-1286
   0x0000000014d63478 <+56>:    addi    r30,r5,27912
   0x0000000014d6347c <+60>:    addi    r3,r3,-17568
   0x0000000014d63480 <+64>:    mr      r5,r30
   0x0000000014d63484 <+68>:    std     r28,16(r4)
=> 0x0000000014d63488 <+72>:    stxv    vs0,0(r4)
   0x0000000014d6348c <+76>:    bl      0x168e87a0 <00000000.plt_call.__cxa_atexit>
   0x0000000014d63490 <+80>:    ld      r2,24(r1)
   0x0000000014d63494 <+84>:    addis   r3,r2,29
   0x0000000014d63498 <+88>:    li      r5,7
   0x0000000014d6349c <+92>:    addi    r4,r3,19408
   0x0000000014d634a0 <+96>:    stb     r28,19415(r3)
   0x0000000014d634a4 <+100>:   stb     r5,23(r4)
   0x0000000014d634a8 <+104>:   lis     r5,26723
   0x0000000014d634ac <+108>:   ori     r5,r5,29281
   0x0000000014d634b0 <+112>:   stw     r5,19408(r3)
   0x0000000014d634b4 <+116>:   lis     r5,25974
   0x0000000014d634b8 <+120>:   ori     r5,r5,26984
   0x0000000014d634bc <+124>:   stw     r5,19411(r3)
   0x0000000014d634c0 <+128>:   addis   r3,r2,-1160
   0x0000000014d634c4 <+132>:   mr      r5,r30
   0x0000000014d634c8 <+136>:   addi    r29,r3,25760
   0x0000000014d634cc <+140>:   mr      r3,r29
   0x0000000014d634d0 <+144>:   bl      0x168e87a0 <00000000.plt_call.__cxa_atexit>
   0x0000000014d634d4 <+148>:   ld      r2,24(r1)
   0x0000000014d634d8 <+152>:   addis   r3,r2,29
   0x0000000014d634dc <+156>:   li      r5,8
   0x0000000014d634e0 <+160>:   addi    r4,r3,19432
   0x0000000014d634e4 <+164>:   stb     r5,23(r4)
   0x0000000014d634e8 <+168>:   lis     r5,11603
   0x0000000014d634ec <+172>:   stb     r28,8(r4)
   0x0000000014d634f0 <+176>:   ori     r5,r5,20047
   0x0000000014d634f4 <+180>:   rldic   r5,r5,32,2
   0x0000000014d634f8 <+184>:   oris    r5,r5,18772
   0x0000000014d634fc <+188>:   ori     r5,r5,20559
   0x0000000014d63500 <+192>:   std     r5,19432(r3)
   0x0000000014d63504 <+196>:   mr      r3,r29
   0x0000000014d63508 <+200>:   mr      r5,r30
   0x0000000014d6350c <+204>:   bl      0x168e87a0 <00000000.plt_call.__cxa_atexit>
   0x0000000014d63510 <+208>:   ld      r2,24(r1)
   0x0000000014d63514 <+212>:   addis   r3,r2,29
   0x0000000014d63518 <+216>:   li      r5,5
   0x0000000014d6351c <+220>:   addi    r4,r3,19456
   0x0000000014d63520 <+224>:   stb     r5,23(r4)
   0x0000000014d63524 <+228>:   lis     r5,28020
   0x0000000014d63528 <+232>:   ori     r5,r5,25188
   0x0000000014d6352c <+236>:   stw     r5,19456(r3)
   0x0000000014d63530 <+240>:   li      r5,112
   0x0000000014d63534 <+244>:   sth     r5,19460(r3)
   0x0000000014d63538 <+248>:   mr      r3,r29
   0x0000000014d6353c <+252>:   mr      r5,r30
   0x0000000014d63540 <+256>:   bl      0x168e87a0 <00000000.plt_call.__cxa_atexit>
   0x0000000014d63544 <+260>:   ld      r2,24(r1)
   0x0000000014d63548 <+264>:   addi    r1,r1,64
   0x0000000014d6354c <+268>:   ld      r0,16(r1)
   0x0000000014d63550 <+272>:   ld      r30,-16(r1)
   0x0000000014d63554 <+276>:   ld      r29,-24(r1)
   0x0000000014d63558 <+280>:   ld      r28,-32(r1)
   0x0000000014d6355c <+284>:   mtlr    r0
   0x0000000014d63560 <+288>:   blr
   0x0000000014d63564 <+292>:   .long 0x0
   0x0000000014d63568 <+296>:   .long 0x0
   0x0000000014d6356c <+300>:   .long 0x0
End of assembler dump.

**Comment by alexey-milovidov** [comment]
I'm not an expert in Power architecture.
So, the question, what is that `stxv` instruction and why it is illegal for your CPU?

**Comment by alexey-milovidov** [comment]
Maybe we accidentally generating code for Power10?

**Comment by alexey-milovidov** [comment]
I have no access to PowerPC machine but here it the fix: #36529

**Comment by pranavpandit1** [comment]
I tried the suggested fix and clean and built the package to test.
unfortunately, the issue still persists with the same exception.

**Comment by alexey-milovidov** [comment]
Maybe you need to bring a real PowerPC machine for us.

**Comment by alexey-milovidov** [comment]
Now I have the machine and this task can be continued.

**Comment by alexey-milovidov** [comment]
First tests:
- binary is built correctly;
- clickhouse-local works;
- exception handling works;
- clickhouse-server can start up and shutdown;

https://pastila.nl/?001c5a5c/71f1de4249f7b711651643cef8e9061e

**Comment by alexey-milovidov** [comment]
Server can be installed:

https://pastila.nl/?0272f397/21b0df71b95f27b053ede6e19abdaeb9

**Comment by alexey-milovidov** [comment]
So, the issue does not reproduce with the recent official binary.

**Comment by alexey-milovidov** [comment]
@pranavpandit1 I can conclude that the problem is with your own build, not with our pre-built binaries.

**Comment by alexey-milovidov** [comment]
Benchmark run successfully: https://github.com/ClickHouse/ClickHouse/pull/37059

**Comment by bkuschel** [comment]
The build still only works on >POWER8 even if mcpu=power8 is set because of what i *think* is related to this:

https://github.com/llvm/llvm-project/commit/335e8bf1008fff5723ba36f27350eb6d5e7f187c

llvm-15 has the fix

**Comment by alexey-milovidov** [comment]
Ok. Clang-15 will be released very soon, we will switch to it as soon as it will be released.
