### ISSUE TITLE
Limit select count subquery work in 21.4.5.46 version but can not work in 21.10.2.15

### ISSUE THREAD

**Issue by 15863004186sunchi** [ClickHouse/ClickHouse#36027]
Limit select count subquery work in 21.4.5.46 version but can not work in 21.10.2.15

Sql is  select * from mytable order by sid limit (select toInt64(count(cid)*0.01)　from mytable);

The sql can work very well in in 21.4.5.46 version but can not work in 21.10.2.15

Exception is : [1002] ClickHouse exception, message: Code: 440. DB::Exception: Illegal type Nullable(Int32) of LIMIT expression, must be numeric type. (INVALID_LIMIT_EXPRESSION) (version 21.10.2.15 (official build))

**How to reproduce**
1 create table sql:
create table mytable
(
    cid     String,
    create_time String,
    sid  String
)
    engine = MergeTree PARTITION BY sid
        ORDER BY cid
        SETTINGS index_granularity = 8192;

2 execute sql

select * from mytable order by sid limit (select toInt64(count(cid)*0.01)　from mytable);

**Comment by den-crane** [comment]
Now you should use

```sql
SELECT *
FROM mytable
ORDER BY sid ASC
LIMIT assumeNotNull((
    SELECT toUInt64(count(cid) * 0.01)
    FROM mytable
))

Query id: e3ab56af-96e4-4e01-812d-39af945d7878

Ok.

0 rows in set. Elapsed: 0.004 sec.
```

see https://github.com/ClickHouse/ClickHouse/issues/30972

**Comment by 15863004186sunchi** [comment]
The solution can work very well.Thank you vert much.

**Comment by 15863004186sunchi** [comment]
> I guess limit should accept Nullable and Float types and do implicit cast.
Yes. it can accept Nullable and Float types and do implicit cast.

**Comment by 15863004186sunchi** [comment]
> I guess limit should accept Nullable and Float types and do implicit cast.

I just tested the case

**Comment by 15863004186sunchi** [comment]
Thanks
