### ISSUE TITLE
Documentation pages for example datasets return 404

### ISSUE THREAD

**Issue by anelook** [ClickHouse/ClickHouse#36036]
(you don't have to strictly follow this form)

**Describe the issue**
1. Landing on the main page of documentation https://clickhouse.com/docs/en/
2. Select Example Datasets in the left menu
3. see 404 error

**Comment by alexey-milovidov** [comment]
It may require dropping browser cache. Open the following page:
https://clickhouse.com/docs/en/getting-started/example-datasets/
and press Ctrl+Shift+R.
