### ISSUE TITLE
MaterializedPostgreSQL : Clickhouse-server keeps crashing : Segmentation Fault (11)

### ISSUE THREAD

**Issue by vivek-shoonyai** [ClickHouse/ClickHouse#36030]
> You have to provide the following information whenever possible.

I am using MaterializedPostgreSQL. Clickhouse-Server keeps crashing every 20-30 seconds. 

Error message:-

2022.04.07 13:11:24.212860 [ 149258 ] {} <Fatal> BaseDaemon: (version 22.3.3.44 (official build), build id: F9D3C2B8666BEF5D) (from thread 146958) (no query) Received signal Segmentation fault (11)
2022.04.07 13:11:24.212894 [ 149258 ] {} <Fatal> BaseDaemon: Address: 0x18 Access: read. Address not mapped to object.
2022.04.07 13:11:24.212927 [ 149258 ] {} <Fatal> BaseDaemon: Stack trace: 0x152e0eb2 0x152d7129 0x152d7c13 0x152d8c3d 0x152dd21a 0x152ddad9 0x152a6a00 0x14f02cee 0x14f05667 0x14f06670 0xb418757 0xb41c2dd 0x7f353de44609 0x7f353dd69163
2022.04.07 13:11:24.213004 [ 149258 ] {} <Fatal> BaseDaemon: 2. DB::insertPostgreSQLValue(DB::IColumn&, std::__1::basic_string_view<char, std::__1::char_traits<char> >, DB::ExternalResultDescription::ValueType, std::__1::shared_ptr<DB::IDataType const>, std::__1::unordered_map<unsigned long, DB::PostgreSQLArrayInfo, std::__1::hash<unsigned long>, std::__1::equal_to<unsigned long>, std::__1::allocator<std::__1::pair<unsigned long const, DB::PostgreSQLArrayInfo> > >&, unsigned long) @ 0x152e0eb2 in /usr/bin/clickhouse
2022.04.07 13:11:24.213032 [ 149258 ] {} <Fatal> BaseDaemon: 3. DB::MaterializedPostgreSQLConsumer::insertValue(DB::MaterializedPostgreSQLConsumer::StorageData::Buffer&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long) @ 0x152d7129 in /usr/bin/clickhouse
2022.04.07 13:11:24.213047 [ 149258 ] {} <Fatal> BaseDaemon: 4. DB::MaterializedPostgreSQLConsumer::readTupleData(DB::MaterializedPostgreSQLConsumer::StorageData::Buffer&, char const*, unsigned long&, unsigned long, DB::MaterializedPostgreSQLConsumer::PostgreSQLQuery, bool) @ 0x152d7c13 in /usr/bin/clickhouse
2022.04.07 13:11:24.213068 [ 149258 ] {} <Fatal> BaseDaemon: 5. DB::MaterializedPostgreSQLConsumer::processReplicationMessage(char const*, unsigned long) @ 0x152d8c3d in /usr/bin/clickhouse
2022.04.07 13:11:24.213093 [ 149258 ] {} <Fatal> BaseDaemon: 6. DB::MaterializedPostgreSQLConsumer::readFromReplicationSlot() @ 0x152dd21a in /usr/bin/clickhouse
2022.04.07 13:11:24.213110 [ 149258 ] {} <Fatal> BaseDaemon: 7. DB::MaterializedPostgreSQLConsumer::consume(std::__1::vector<std::__1::pair<int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > >&) @ 0x152ddad9 in /usr/bin/clickhouse
2022.04.07 13:11:24.213135 [ 149258 ] {} <Fatal> BaseDaemon: 8. DB::PostgreSQLReplicationHandler::consumerFunc() @ 0x152a6a00 in /usr/bin/clickhouse
2022.04.07 13:11:24.213172 [ 149258 ] {} <Fatal> BaseDaemon: 9. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x14f02cee in /usr/bin/clickhouse
2022.04.07 13:11:24.213190 [ 149258 ] {} <Fatal> BaseDaemon: 10. DB::BackgroundSchedulePool::threadFunction() @ 0x14f05667 in /usr/bin/clickhouse
2022.04.07 13:11:24.213200 [ 149258 ] {} <Fatal> BaseDaemon: 11. ? @ 0x14f06670 in /usr/bin/clickhouse
2022.04.07 13:11:24.213221 [ 149258 ] {} <Fatal> BaseDaemon: 12. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xb418757 in /usr/bin/clickhouse
2022.04.07 13:11:24.213241 [ 149258 ] {} <Fatal> BaseDaemon: 13. ? @ 0xb41c2dd in /usr/bin/clickhouse
2022.04.07 13:11:24.213260 [ 149258 ] {} <Fatal> BaseDaemon: 14. ? @ 0x7f353de44609 in ?
2022.04.07 13:11:24.213284 [ 149258 ] {} <Fatal> BaseDaemon: 15. __clone @ 0x7f353dd69163 in ?
2022.04.07 13:11:24.358478 [ 149258 ] {} <Fatal> BaseDaemon: Calculated checksum of the binary: FD20C2FC24F8B8996C15BF97FA841B03. There is no information about the reference checksum.
2022.04.07 13:11:44.441911 [ 146846 ] {} <Fatal> Application: Child process was terminated by signal 11.

> A clear and concise description of what works not as it is supposed to.
Clickhouse server should not crash. 

**Does it reproduce on recent release?**
Yes it does. (22.3.3.44)

Using the latest clickhouse version 22.3.3.44
Using the following method for starting replication:-

CREATE DATABASE database1
ENGINE = MaterializedPostgreSQL('postgres1:5432', 'postgres_database', 'postgres_user', 'postgres_password')
SETTINGS materialized_postgresql_tables_list = 'schema1.table1,schema2.table2,schema1.table3',
         materialized_postgresql_tables_list_with_schema = 1,
        materialized_postgresql_allow_automatic_update = 1;

I have found the above error only occurs for replicating a specific table. When that table is removed from materialized_postgresql_tables_list clickhouse-server works fine, with no crash.

DDL for the postgres table whose replication is causing clickhouse crash:-

create table table_x
(
    id                   integer                  default nextval('table_x_id_seq'::regclass) not null
        constraint demand_tracker_pkey1
            primary key,
    some_id           integer,
    some_2_id          integer,
    load_blue_type  table_x_load_blue_type,
    some_3_id            integer,
    some_4_id     integer,
    some_5_id       integer,
    some_6_id         integer,
    some_7_id    integer,
    yellow                 integer,
    ver              smallint,
    some_via          smallint,
    black             varchar(10)              default NULL::character varying,
    one_location       geometry(Point, 4326)    default NULL::geometry,
    two_location         geometry(Point, 4326)    default NULL::geometry,
    one_stato         integer,
    two_stato            integer,
    one_admn       varchar(300)             default NULL::character varying,
    two_admn          varchar(300)             default NULL::character varying,
    samay                smallint,
    red_location     geometry(Point, 4326)    default NULL::geometry,
    created_at           timestamp with time zone default CURRENT_TIMESTAMP                          not null,
    updated_at           timestamp with time zone default CURRENT_TIMESTAMP                          not null,
    some_req      jsonb,
    meta_data            jsonb,
    rsome_count          smallint,
    test_opt_details jsonb,
    dead_metadata     jsonb,
    count_atemp       integer,
    black_ucity      jsonb
);

**Comment by kssenii** [comment]
Is it possible for you to check master version? There was a fix https://github.com/ClickHouse/ClickHouse/pull/35614, which fixed a crush in the same place.

**Comment by vivek-shoonyai** [comment]
Yes, I have checked the master version. I have used a single binary installation method. I have created a new isolated server for testing. I only tested the replication of a single table(table which was causing crashes).

The result is clickhouse server does not crash. I have tested it for 6-7 hours.


I have a few questions:
1. How I can upgrade my prod server from latest version(22.3.3.44) to master safely. Can I use a single binary installation method to upgrade the ubuntu server?
2. Should I wait for the master change to be part of latest release? How long it will take?

**Comment by vivek-shoonyai** [comment]
> Is it possible for you to check master version? There was a fix #35614, which fixed a crush in the same place.

Yes, I have checked the master version. I have used a single binary installation method. I have created a new isolated server for testing. I only tested the replication of a single table(table which was causing crashes).

The result is clickhouse server does not crash. I have tested it for 6-7 hours.

I have a few questions:

How I can upgrade my prod server from latest version(22.3.3.44) to master safely. Can I use a single binary installation method to upgrade the ubuntu server?
Should I wait for the master change to be part of latest release? How long it will take?

**Comment by kssenii** [comment]
>  Should I wait for the master change to be part of latest release? How long it will take?

The next release 22.4 will be in a few days.
Or you can use master version.

> Can I use a single binary installation method to upgrade the ubuntu server?

Yes
