### ISSUE TITLE
How to build ClickHouse entirely from source code (not using pre-compiled binaries)?

### ISSUE THREAD

**Issue by Mirraz** [ClickHouse/ClickHouse#36042]
Prior version 22.x I could build ClickHouse entirely from source code (including submodules). But after merging this PR:
https://github.com/ClickHouse/ClickHouse/pull/29974
ClickHouse build system now uses pre-compiled binary files from "sysroot" submodule (https://github.com/ClickHouse/sysroot). How can I build ClickHouse entirely from source code (not using pre-compiled binaries)? Or can I build these pre-compiled binaries (in "sysroot") from source code and then use it to build ClickHouse? I really need to be able to do this because I have such requirement in my company.

**Comment by alexey-milovidov** [comment]
https://github.com/oriansj/stage0
and https://github.com/fosslinux/live-bootstrap/blob/master/parts.rst

More details in a hour.

**Comment by alexey-milovidov** [comment]
sysroot contains libc binary from the operating system.
You can take it from your Linux (Ubuntu) or from its Docker image or from installation ISO.
You can also build glibc from sources: https://www.gnu.org/software/libc/

**Comment by alexey-milovidov** [comment]
Also read this:
https://reproducible-builds.org/
https://bootstrappable.org/
for the details.

**Comment by Algunenano** [comment]
You can also disable using those blobs by passing `-DDISABLE_HERMETIC_BUILD=TRUE`. Note that this means that the resulting binary won't be necessarily reproducible nor usable on other systems (if they have older system libraries).

**Comment by Mirraz** [comment]
@Algunenano It works, thank you!
