### ISSUE TITLE
Rating looks broken in Russian, Chinese and Japanese versions of documentation

### ISSUE THREAD

**Issue by besteffects** [ClickHouse/ClickHouse#36046]
Example:
https://github.com/ClickHouse/ClickHouse/blob/master/docs/ru/engines/table-engines/index.md
![image](https://user-images.githubusercontent.com/14294615/162260325-80cb953d-22e6-45af-b15d-92fc97b1c96e.png)
Chrome Version 99.0.4844.51 (Official Build) (64-bit)

**Comment by alexey-milovidov** [comment]
It is in transitional period and broken ratings is not a big issue.
It will migrate to a different docs engine in one-two weeks.
