### ISSUE TITLE
Why has many inactive parts under the 'moving' directory?

### ISSUE THREAD

**Issue by openxxx** [ClickHouse/ClickHouse#36059]
I think clickhouse should delete all these inactive parts automatically. but the fact is not. What's the usage of this 'moving' directory? How can I set the configuration then can delete them automatically?
![1649404451(1)](https://user-images.githubusercontent.com/10058357/162392221-a40dd3de-7273-48e9-8b81-4d79184b1088.png)

**Comment by den-crane** [comment]
What Clickhouse version do you use?

**Comment by openxxx** [comment]
My ClickHouse version is 21.11.10.1.  Any updates? @den-crane

**Comment by json-lrj** [comment]
the datapart is outdated when moving, it just take part in moving and merging at the same time。

**Comment by alexey-milovidov** [comment]
It is ok to ignore these data parts.
