### ISSUE TITLE
merge engine showing duplicates for view and table merge

### ISSUE THREAD

**Issue by mayank-pant** [ClickHouse/ClickHouse#36087]
When i am merging one table and one view using merge engine. The value of view tables gets duplicated.

**How to reproduce**
CREATE TABLE x1(x String, y String)Engine=MergeTree ORDER BY tuple()
CREATE TABLE x2(x String, y String)Engine=MergeTree ORDER BY tuple()
CREATE VIEW x2_view AS SELECT * FROM x1
CREATE TABLE all_x (x String, y String) ENGINE=Merge('default','x2*');
insert into x1(*) values('4','5')
insert into x2(*) values('1','2')

**Expected behavior**
Select * from all_x
─x─┬─y─
  4        5
  1        2

**Output i am getting**
Select * from all_x
─x─┬─y─
  4        5
  1        2
  4        5

**Comment by den-crane** [comment]
It's another regexp dialect. RE2. You need . (dot)


```sql
select match('x1', 'x2*');
┌─match('x1', 'x2*')─┐
│                  1 │
└────────────────────┘

select match('x1', 'x2.*');
┌─match('x1', 'x2.*')─┐
│                   0 │
└─────────────────────┘
```


```sql
CREATE TABLE all_x (x String, y String) ENGINE=Merge('default','x2.*');
select _table,* from all_x;
┌─_table─┬─x─┬─y─┐
│ x2     │ 1 │ 2 │
└────────┴───┴───┘
┌─_table──┬─x─┬─y─┐
│ x2_view │ 4 │ 5 │
└─────────┴───┴───┘
```
