### ISSUE TITLE
Inf in Float32 can display correctly after upgrade from 21.1.8 to 22.3.2

### ISSUE THREAD

**Issue by tong900801** [ClickHouse/ClickHouse#36094]
After upgrade clickhouse v21.1.8 to v22.3.2, float32 type inf(eg. 1/0) cannot display correctly.
In clickhouse v21.1.8, it shows correctly.
In clickhouse v22.3.2, it shows an error message in datagrip(jdbc 0.3.1)
<img width="420" alt="截屏2022-04-09 下午1 05 12" src="https://user-images.githubusercontent.com/44745938/162557401-f70b2188-c49a-439f-8c8e-d5f43f61f40b.png">

In clickhouse-client, they both show correctly. But in datagrip they show differently.
Does it a jdbc issue?
Why it happens after clickhouse upgraded?

Thanks a Lot.

**Comment by genzgd** [comment]
I am unable to reproduce this in DataGrip (latest version, using the bundled JDBC driver `Driver: ru.yandex.clickhouse-jdbc (ver. 0.3.1-patch, JDBC0.1)`)
![query](https://user-images.githubusercontent.com/625882/162583668-44485332-0d01-41fe-909e-0ad62517d844.png)
![result](https://user-images.githubusercontent.com/625882/162583678-2c786703-15af-43ea-87f0-c9df3711de89.png)

Can you provide any additional information that might explain why it works differently on your system?  Does the issue occur with any "Infinity" Float64 or just data from one of your server tables?

**Comment by den-crane** [comment]
No changes in CH.

```
20.8.17.25

cl -q 'select 1/0 format RowBinary' | od
0000000 000000 000000 000000 077760
0000010

cl -q 'select 1/0 format TabSeparatedWithNamesAndTypes '
divide(1, 0)
Float64
inf

22.3.2.1
cl -q 'select 1/0 format RowBinary' | od
0000000 000000 000000 000000 077760
0000010

cl -q 'select 1/0 format TabSeparatedWithNamesAndTypes '
divide(1, 0)
Float64
inf
```

**Comment by tong900801** [comment]
Sorry, it's float32. Please try this:
`DROP TABLE IF EXISTS divide_test2;
CREATE TABLE divide_test2
(m Float32)
ENGINE = Memory
AS
SELECT 1/0;
SELECT * FROM divide_test2;`

**Comment by genzgd** [comment]
Actually this also seems broken (with Float32) on 21.1.8.30 in DataGrip.  Do you have DataGrip configured the same for both ClickHouse servers you are testing?  I will see if I can narrow the problem down further.

**Comment by genzgd** [comment]
I am unable to reproduce this outside of DataGrip.  Using the same version of the JDBC driver as reported by DataGrip, this Java code works as expected:

```
  ResultSet rs = stmt.executeQuery("select cast(1/0, 'Float32') as m");
  while (rs.next()) {
       assert rs.getFloat(0) == Float.POSITIVE_INFINITY;
  }
```

The same query produces a "parse exception" in DataGrip.  Note that the exception only appears in the console, not in the DataGrip application or SQL logs.  At this point it appears to be a DataGrip bug.
