### ISSUE TITLE
Excessive disk writes when idle

### ISSUE THREAD

**Issue by pkese** [ClickHouse/ClickHouse#36097]
Clickhouse, even when running idle, is writing something to disk every second and cumulatively writes hundreds of GB of data to disk every day.  
This makes it is by far the biggest SSD-wear culprit at least on my machine.

Is this expected or a bug?
Is there any organized documentation on how configure Clickhouse in a way to reduce excessive wear on SSDs?

**Comment by genzgd** [comment]
ClickHouse executes background merges of data to further sort data and improve compression and sorting.  Each merge involves rewriting all the table columns files in each merged part.   Merges continue until historical data is stored in a small number of parts per table partition.

These background merges are fundamental to the design of ClickHouse and key to its high performance.  For the typical big data application the tradeoff between ClickHouse performance and additional SSD wear is well worth it, especially with the constant increasing lifespans of modern SSD/NVME drives.

Note if you continue to write new data into a table that needs to be resorted, it will continue to be merged and rewritten.  You can potentially reduce the amount of background writes/merges by ensuring the new data does not have to be integrated with old data, often by partitioning by time/date.  You can also somewhat reduce the intensity of background merges by inserting already sorted or partially data (by the primary/order by) key.

**Comment by stas-sl** [comment]
Also you can turn off excessive logging if you don't need it:
- https://theorangeone.net/posts/calming-down-clickhouse/
- https://kb.altinity.com/altinity-kb-setup-and-maintenance/altinity-kb-system-tables-eat-my-disk/

**Comment by den-crane** [comment]
because `asynchronous_metrics_update_period_s = 1s` by default

```
<yandex>
   <asynchronous_metrics_update_period_s>60</asynchronous_metrics_update_period_s>

    <asynchronous_metric_log remove="1"/>
    <query_thread_log remove="1"/>
    <session_log remove="1"/>
    <query_log remove="1"/>
    <metric_log remove="1"/>
    <part_log remove="1"/>
    <text_log remove="1"/>
    <trace_log remove="1"/>

    <merge_tree>
	    <!--merge_tree_clear_old_temporary_directories_interval_seconds>30</merge_tree_clear_old_temporary_directories_interval_seconds-->
    </merge_tree>
</yandex>
```

**Comment by pkese** [comment]
@den-crane  
Thanks. After applying your suggestion, clickhouse is now not writing any more to disk every second.
