### ISSUE TITLE
What is Memory DataBase?

### ISSUE THREAD

**Issue by taotaizhu-pw** [ClickHouse/ClickHouse#36108]
What is Memory DataBase? I found "Memory Database" in some doc, and execute "create database memdb engine=Memory" successfully.  I also can create MergeTree table in this database. What's the difference between "Memory Database" and "Memory Table"?  Is it mean all the tables are in memory when I use memory database, even I create mergetree table? 
Thanks!

**Comment by alexey-milovidov** [comment]
Memory database does not store tables' metadata persistently. It is an implementation part of `clickhouse-local`.
Tables' metadata is forgotten on exit, while tables data remain.
