### ISSUE TITLE
[error] Sending 'http' logs from haproxy to kafka and use kafka engine to Clickhouse table

### ISSUE THREAD

**Issue by awsmaythem** [ClickHouse/ClickHouse#36102]
Hello 
i need to send logs from haproxy to clickhouse using kafka, i tried using kafka between servers and sending it as json using rsyslog but i get an error in importing to table in clickhouse like "{" or "," in the message, how can i config it to allow Special symbols in raw message using kafka table engine in clickhouse

**CONFIG in clickhouse:**
`CREATE TABLE default.ha6
(
    `logdate` Date,
    `logdatetime` DateTime,
    `type` String,
    `hostname` String,
    `client_ip` String,
    `client_port` UInt16,
    `accept_date` String,
    `frontend_name` String,
    `backend_name` String,
    `server_name` String,
    `time_request` Int32,
    `time_queue` Int32,
    `time_backend_connect` Int32,
    `time_backend_response` Int32,
    `time_duration` Int32,
    `http_status_code` Int16,
    `bytes_read` Int64,
    `captured_request_cookie` String,
    `captured_response_cookie` String,
    `termination_state` String,
    `actconn` UInt32,
    `feconn` UInt32,
    `beconn` UInt32,
    `srvconn` UInt32,
    `retries` Int16,
    `srv_queue` UInt32,
    `backend_queue` UInt32,
    `request_header_origin` String,
    `request_header_host` String,
    `request_header_x_forwarded_for` String,
    `request_header_accept_language` String,
    `request_header_referer` String,
    `request_header_user_agent` String,
    `response_header_content_type` String,
    `response_header_content_encoding` String,
    `response_header_cache_control` String,
    `response_header_last_modified` String,
    `http_verb` String,
    `http_request` String,
    `http_version` String,
    `haproxy_year` UInt16,
    `haproxy_month` String,
    `haproxy_monthday` UInt8,
    `haproxy_hour` UInt8,
    `haproxy_minute` UInt8,
    `haproxy_second` UInt8,
    `haproxy_milliseconds` UInt16,
    `haproxy_time` String,
    `host` String
)
ENGINE = MergeTree
ORDER BY logdatetime

CREATE TABLE ha6_queue
(
    `logdate` Date,
    `logdatetime` DateTime,
    `type` String,
    `hostname` String,
    `client_ip` String,
    `client_port` UInt16,
    `accept_date` String,
    `frontend_name` String,
    `backend_name` String,
    `server_name` String,
    `time_request` Int32,
    `time_queue` Int32,
    `time_backend_connect` Int32,
    `time_backend_response` Int32,
    `time_duration` Int32,
    `http_status_code` Int16,
    `bytes_read` Int64,
    `captured_request_cookie` String,
    `captured_response_cookie` String,
    `termination_state` String,
    `actconn` UInt32,
    `feconn` UInt32,
    `beconn` UInt32,
    `srvconn` UInt32,
    `retries` Int16,
    `srv_queue` UInt32,
    `backend_queue` UInt32,
    `request_header_origin` String,
    `request_header_host` String,
    `request_header_x_forwarded_for` String,
    `request_header_accept_language` String,
    `request_header_referer` String,
    `request_header_user_agent` String,
    `response_header_content_type` String,
    `response_header_content_encoding` String,
    `response_header_cache_control` String,
    `response_header_last_modified` String,
    `http_verb` String,
    `http_request` String,
    `http_version` String,
    `haproxy_year` UInt16,
    `haproxy_month` String,
    `haproxy_monthday` UInt8,
    `haproxy_hour` UInt8,
    `haproxy_minute` UInt8,
    `haproxy_second` UInt8,
    `haproxy_milliseconds` UInt16,
    `haproxy_time` String,
    `host` String
)
ENGINE = Kafka
SETTINGS kafka_broker_list = 'kafka1:9092',
       kafka_topic_list = 'aws',
       kafka_group_name = 'aws_consumer_group1',
       kafka_format = 'JSONEachRow',
       kafka_row_delimiter = '\n';

CREATE MATERIALIZED VIEW ha6_mv TO ha6 AS
SELECT logdate, logdatetime, type, hostname, client_ip, client_port, accept_date, frontend_name, backend_name, server_name, time_request, time_queue, time_backend_connect, time_backend_response, time_duration, http_status_code, bytes_read, Int64, captured_request_cookie, captured_response_cookie, termination_state, actconn, feconn, beconn, srvconn, retries, srv_queue, backend_queue, request_header_origin, request_header_host, request_header_x_forwarded_for, request_header_accept_language, request_header_referer, request_header_user_agent, response_header_content_type, response_header_content_encoding, response_header_cache_control, response_header_last_modified, http_verb, http_request, http_version, haproxy_year, haproxy_month, haproxy_monthday, haproxy_hour, haproxy_minute, haproxy_second, haproxy_milliseconds, haproxy_time, host
FROM ha6_queue;`

**error msg:**
`2022.04.02 11:38:35.816621 [ 12289 ] {} <Error> void DB::StorageKafka::threadFunc(size_t): Code: 27. DB::ParsingException: Cannot parse input: expected '{' before: '2022-04-01T20:22:19+03:00 elintha1 haproxy[215]: xxxx:xxxx [01/Apr/2022:20:22:19.353] graph~ graph_BE/graph01 0/0/0/6/6 200 243 - - ---- 488/158/6/0': while parsing Kafka message (topic: ha-proxy1, partition: 0, offset: 31181689)': While executing Kafka: (at row 1)
. (CANNOT_PARSE_INPUT_ASSERTION_FAILED), Stack trace (when copying this message, always include the lines below)`

**Comment by gingerwizard** [comment]
hi @awsmaythem the challenge here is you aren't sending JSON messages to the Kafka.  They key part is when you create the Kafka table engine, specifically

```
ENGINE = Kafka
SETTINGS kafka_broker_list = 'kafka1:9092',
kafka_topic_list = 'aws',
kafka_group_name = 'aws_consumer_group1',
kafka_format = 'JSONEachRow',
kafka_row_delimiter = '\n';
```

Note the use of `kafka_format` implies these are JSON - which they clearly aren't. What format are the messages being stored on Kafka? If they String you could potentially try using [LineAsString](https://clickhouse.com/docs/en/interfaces/formats/#lineasstring) and extracting the fields in the materialized view with functions. I'd advise against this though and simply fix your source i.e. send as JSON.

Note, that we have some [new docs in development ](https://github.com/ClickHouse/clickhouse-docs/tree/main/docs/integrations/kafka)for Kafka. For sending syslog, have you considered using [Vector](https://vector.dev)? We have a getting started guide [here](https://github.com/ClickHouse/clickhouse-docs/blob/main/docs/integrations/kafka/kafka-vector.md). You will need to adapt the examples to use the [syslog input](https://vector.dev/docs/reference/configuration/sources/syslog/).

**Comment by awsmaythem** [comment]
thanks Dale i'll try to change the source format to json.
have a nice day :)
