### ISSUE TITLE
What's the process in Memory Engine for update/delete mutation operation?

### ISSUE THREAD

**Issue by taotaizhu-pw** [ClickHouse/ClickHouse#36105]
I would use Memory engine for some special requirement. After the 'ALTER UPDATE/DELET' operation, can I query this table immediately?  Is the mutation operation in Memory engine is also an asyc action? How can I check whether the "UPDATE/DELETE" action is done for Memory Engine/Table?  Thanks!

**Comment by ucasfl** [comment]
The execution of mutations for `Memory` engine is synchronous, you can query the table immediately after `alter` operation done.

**Comment by ucasfl** [comment]
But `Memory` engine is not for production usage, and the mutation process is single-threaded.

**Comment by taotaizhu-pw** [comment]
> But `Memory` engine is not for production usage, and the mutation process is single-threaded.

Need I  manually to set the "max_threads = 1"?  Or it would be set by system when execute mutation operation? Thanks

**Comment by ucasfl** [comment]
Default by system.

**Comment by taotaizhu-pw** [comment]
> Default by system.

Thanks! :)
