### ISSUE TITLE
Any solution for Memory Engine cluster? replicate date to slave node

### ISSUE THREAD

**Issue by taotaizhu-pw** [ClickHouse/ClickHouse#36107]
Is there any solution for Memory Engine cluster? Replicate the data to slave node. 
As I know that the "Replicated" function can only be used in MergeTree table/engine. Is there work around solution for Memory Engine? Thanks!

**Comment by alexey-milovidov** [comment]
No, Memory engine is not for large scale storage.

In fact, it can work slower than MergeTree, due to lack of indexes, lack of sorting, lack of prewhere optimization and limited support for compression.

**Comment by alexey-milovidov** [comment]
TLDR: In-memory != better.

**Comment by taotaizhu-pw** [comment]
> TLDR: In-memory != better.

Thanks alex. Our case is based on MergeTree engine, push some special data into memory table at 8:00AM in everyday . Each table less than 50000 lines, even most of the special tables are about 5000~10000 lines. And we found the mutation "UPDATE/DELETE" operation in memory is synchronized, it matched our requirements.  After testing, our sql queries saved 70%~80% time rather than mergetree table.
