### ISSUE TITLE
clickhouse-server can not start up when hive is not available

### ISSUE THREAD

**Issue by july2018** [ClickHouse/ClickHouse#36116]
hi：
   
latest, we  use  hive   engine,but , after dropped  table in hive,  clickhouse server can not  startup, the message is
"
<Error> Application: TException - service has thrown: NoSuchObjectException(message=hive.test.tetst table not found)
"
what can I  do ?(when  I remove  metadata in  clickhouse ,it works)
is this a new bug?
  thanks !

**Comment by alexey-milovidov** [comment]
It is related to Hive integration, which has been contributed recently
and may take time to mature.

You can file an issue here:
https://github.com/ClickHouse/ClickHouse/pulls?q=is%3Apr+is%3Aopen+hive
Or connect directly with the author: https://github.com/taiyang-li

**Comment by taiyang-li** [comment]
@july2018 Can you provide more detailed information?

**Comment by taiyang-li** [comment]
Maybe it is better just logging error message instead of throwing exception.

**Comment by tavplubix** [comment]
Yes, StorageHive should be initialized lazily, so clickhouse-server will be able to start if Hive is not available

**Comment by july2018** [comment]
step1:  create table  "test1" in hive 
step2:  create table test1_ck  reference to  hive  in clickhouse-server   using StorageHive 
step3:  drop table "test1"  in hive
step4:  restart  clickhouse-server , after  n seconds,   clickhouse -server  crash, error message is "
 <Error> Application: Caught exception while loading metadata: std::exception. Code: 1001, type: Apache::Hadoop::Hive::NoSuchObjectException, e.what() = TException - service has thrown: NoSuchObjectException(message=hive.test.test1_ck table not found), Stack trace (when copying this message, always include the lines below):

0. Apache::Hadoop::Hive::NoSuchObjectException::NoSuchObjectException(Apache::Hadoop::Hive::NoSuchObjectException const&) @ 0x1a77020a in /usr/lib/debug/.build-id/5f/3d9e4f48d4cc47.debug
1. Apache::Hadoop::Hive::ThriftHiveMetastoreClient::recv_get_table(Apache::Hadoop::Hive::Table&) @ 0x1a85e2bb in /usr/lib/debug/.build-id/5f/3d9e4f48d4cc47.debug
2. DB::HiveMetastoreClient::getTableMetadata(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x13f9c64a in /usr/lib/debug/.build-id/5f/3d9e4f48d4cc47.debug
3. DB::StorageHive::StorageHive(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::StorageID const&, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::IAST> const&, std::__1::unique_ptr<DB::HiveSettings, std::__1::default_delete<DB::HiveSettings> >, std::__1::shared_ptr<DB::Context const>) @ 0x13f85b3c in /usr/lib/debug/.build-id/5f/3d9e4f48d4cc47.debug
4. std::__1::shared_ptr<DB::IStorage> std::__1::__function::__policy_invoker<std::__1::shared_ptr<DB::IStorage> (DB::StorageFactory::Arguments const&)>::__call_impl<std::__1::__function::__default_alloc_func<DB::registerStorageHive(DB::StorageFactory&)::$_2, std::__1::shared_ptr<DB::IStorage> (DB::StorageFactory::Arguments const&)> >(std::__1::__function::__policy_storage const*, DB::StorageFactory::Arguments const&) (.llvm.16590060161902136914) @ 0x13f9a95d in /usr/lib/debug/.build-id/5f/3d9e4f48d4cc47.debug
5. DB::StorageFactory::get(DB::ASTCreateQuery const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, std::__1::shared_ptr<DB::Context>, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, bool) const @ 0x150d699a in /usr/lib/debug/.build-id/5f/3d9e4f48d4cc47.debug
6. DB::createTableFromAST(DB::ASTCreateQuery, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool) @ 0x1446cf3b in /usr/lib/debug/.build-id/5f/3d9e4f48d4cc47.debug
7. DB::DatabaseOrdinary::loadTableFromMetadata(std::__1::shared_ptr<DB::Context>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::QualifiedTableName const&, std::__1::shared_ptr<DB::IAST> const&, bool) @ 0x1450f76a in /usr/lib/debug/.build-id/5f/3d9e4f48d4cc47.debug
8. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::TablesLoader::startLoadingIndependentTables(ThreadPoolImpl<ThreadFromGlobalPool>&, unsigned long)::$_1, void ()> >(std::__1::__function::__policy_storage const*) @ 0x1453e26a in /usr/lib/debug/.build-id/5f/3d9e4f48d4cc47.debug
9. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0xaf6546a in /usr/lib/debug/.build-id/5f/3d9e4f48d4cc47.debug
10. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()&&...)::'lambda'()::operator()() @ 0xaf674a4 in /usr/lib/debug/.build-id/5f/3d9e4f48d4cc47.debug
11. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xaf62837 in /usr/lib/debug/.build-id/5f/3d9e4f48d4cc47.debug
12. void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) @ 0xaf662fd in /usr/lib/debug/.build-id/5f/3d9e4f48d4cc47.debug
13. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
14. clone @ 0xfeb0d in /usr/lib64/libc-2.17.so
 (version 22.2.2.1)
2022.04.06 17:22:27.723344 [ 31308 ] {} <Error> Application: TException - service has thrown: NoSuchObjectException(message=hive.test.test1_ck table not found)
"
PS :
1.  if you don't  restart clickhouse-server ,  clickhouse-server  can work
2.  hive is HA

**Comment by taiyang-li** [comment]
@tavplubix  @july2018  the issue was fixed after pr: https://github.com/ClickHouse/ClickHouse/pull/34940, in which accessing hive metastore is executed lazily in `StorageHive::read` instead of `StorageHive::StorageHive`.
