### ISSUE TITLE
Supporting \G and semicolon after query in clickhouse-client to enable Vertical format

### ISSUE THREAD

**Issue by melvynator** [ClickHouse/ClickHouse#36111]
Currently executing queries like: 

```
SELECT * FROM system.tables LIMIT 10;\G 
SELECT * FROM system.tables LIMIT 10\G;
```

Ends up with a syntax error.

From the documentation, it should not be an error:

> You can specify \G instead of or after the semicolon.

**Comment by alexey-milovidov** [comment]
@melvynator Your issue description is incorrect.

This query works perfectly as per documentation:
```
SELECT * FROM system.tables LIMIT 10;\G
```

**Comment by alexey-milovidov** [comment]
People asked about the following query:

```
SELECT * FROM system.tables LIMIT 10\G;
```

Which is not supposed to work but can be implemented as a bonus feature.

**Comment by melvynator** [comment]
Ok thanks, I will update the the description

**Comment by alexey-milovidov** [comment]
Already updated.

**Comment by yuuch** [comment]
I wanna try this  ;)

**Comment by yuuch** [comment]
#36130
