### ISSUE TITLE
Are Materialized Views synced with ReplacingMergeTree ?

### ISSUE THREAD

**Issue by adam-mrozik** [ClickHouse/ClickHouse#36124]
Hello All,

I want to make sure that my data within the table is deduplicated eventually and wanted to use ReplacingMergeTree.

However, one uncertainty that I have is this: If I have Materialized Views that are selecting data from this table to another one (let's say for the sake of aggregation), will it take deduplication into the account?

I worry that even though `ReplacingMergeTree` will deduplicate `Table1` eventually, `AggregateTable2` will still aggregate the duplicated data as well. Is it true?

**Comment by den-crane** [comment]
>will it take deduplication into the account?

It will not. 
Materialized view is an insert trigger. It never reads the SOURCE table. It gets data from the insert command.

>Is it true?

true

https://den-crane.github.io/Everything_you_should_know_about_materialized_views_commented.pdf

**Comment by arruw** [comment]
Hi, is there some more guidance on how to combine replacing merge tree table and materialized view or maybe a work around?

**Comment by den-crane** [comment]
@arruw https://clickhouse.com/docs/en/materialized-view/refreshable-materialized-view
