### ISSUE TITLE
configure keep_free_space_bytes param

### ISSUE THREAD

**Issue by rfyiamcool** [ClickHouse/ClickHouse#36122]
Whether  must configure `keep_free_space_bytes` param in clickhouse config files?  What does this param do ？ If the disk is 500GB, How much this param needs to be configured？

thank u.

**Comment by rkozlo** [comment]
It is optional. If not specified then there is no space reserved on disk. This config is specific per disk defined in configuration. On few servers i have not typical configuration after resizing default storage policy and i set 30% of whole drive to be reserved since it is not good for ssd.

**Comment by den-crane** [comment]
https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/mergetree/#table_engine-mergetree-multiple-volumes_configure
