### ISSUE TITLE
LoadBalancer Issue： 50% bad replicas, but the load balance still hit the bad replica as the error_count in System.clusters is 0

### ISSUE THREAD

**Issue by Ac-Rush** [ClickHouse/ClickHouse#36156]
Note: When I query distributed table, I got below error, as 50% replica has Volume issue.  But the load balance still hit the bad replica as the error_count in System.clusters is 0
 DB::Exception: std::__1::__fs::filesystem::filesystem_error: filesystem error: in file_size: Input/output error [/var/lib/clickhouse/store/5fb/5fbd5b3e-31ca-4e35-ac4c-26127777ba11/202203_0_1044_4/DateKey.mrk2]. (STD_EXCEPTION) (version 22.1.3.7 (official build))

SELECT *
FROM system.errors

![image](https://user-images.githubusercontent.com/37987464/162890962-ea1fa2e7-544b-4ecd-9323-57d9fdb12bc8.png)

The total count from System.errors is 14
![image](https://user-images.githubusercontent.com/37987464/162891014-e7bcd2c9-8a98-4c0e-9989-ab81ed8603e1.png)

The error_Count in system.clusters is 0

![image](https://user-images.githubusercontent.com/37987464/162891145-8420ac96-86f1-4da0-8d03-e59b2a043227.png)

**Comment by alexey-milovidov** [comment]
Load balancer counts two types of failures:
- network failures;
- non existing tables.

It does not count filesystem errors.
