### ISSUE TITLE
Are there plans to develop ClickHouse-Keeper ?

### ISSUE THREAD

**Issue by EminemJK** [ClickHouse/ClickHouse#36160]
Will clickHouse-Keeper be available for production this year? Zk has too many problems, breaking away from ZK was the right move.

**Comment by genzgd** [comment]
ClickHouse Keeper is production ready as of the version 22.3 (long term support).  See the release webinar:  https://www.youtube.com/watch?v=GzeANZzPras

**Comment by EminemJK** [comment]
> ClickHouse Keeper is production ready as of the version 22.3 (long term support). See the release webinar: https://www.youtube.com/watch?v=GzeANZzPras

Documentation is still pre-production, can you update the document synchronously?
[[pre-production] ClickHouse Keeper](https://clickhouse.com/docs/en/operations/clickhouse-keeper/#clickHouse-keeper)

**Comment by genzgd** [comment]
Documentation will be updated shortly.  There is a migration to an improved documentation platform in progress that has affected temporarily delayed doc changes.
