### ISSUE TITLE
Watching on LiveView raises cursor errors

### ISSUE THREAD

**Issue by voronindev** [ClickHouse/ClickHouse#36173]
During watching the query met some exceptions. Looks like it's some race condition.

**How to reproduce**
*  watch updates on `SELECT now64(9) as ts FROM {} LIMIT 1`

**Expected behavior**
Cursor working without any exceptions

**Error message and/or stacktrace**
```
bad response: Code: 76. DB::ErrnoException: Cannot open file /var/lib/clickhouse/store/7fd/7fdbc368-2b79-4564-bcb9-19667acad1fc/lv_46e0e1b3004fb8d6faa85f3ff89ee14b1445d5bb.sql.tmp, errno: 17, strerror: File exists. (CANNOT_OPEN_FILE) (version 22.1.3.7 (official build))
```

**Comment by tavplubix** [comment]
Is there a stacktrace in server log?
```
zgrep -A 50 -Fa "Cannot open file /var/lib/clickhouse/store/7fd/7fdbc368-2b79-4564-bcb9-19667acad1fc/lv_46e0e1b3004fb8d6faa85f3ff89ee14b1445d5bb" /var/log/clickhouse-server.*
```

**Comment by alexey-milovidov** [comment]
LIVE VIEW is non production feature. It is not supported and most likely will be removed altogether.
