### ISSUE TITLE
version 21.3.4.25, data is not  immediately synchronized between replicas about Replicated table.

### ISSUE THREAD

**Issue by hantaoliulinux** [ClickHouse/ClickHouse#36184]
In kernel version 21.3.4.25, a problem was found. For a Replicated table, a large amount of data (about 1 TB) is attached to one node, but the corresponding copy does not synchronize data immediately. Instead, waited an hour to sync. The wait time to start synchronization is proportional to the data volume.
 have queried historical problems, but I do not see related trouble tickets.

**Comment by melvynator** [comment]
Hello,

Thanks for creating this GitHub issue. 
When you say your data is attached to one node, what exactly do you mean?
Can you share your cluster configuration? 
Did you see any specific error logs?
