### ISSUE TITLE
Why LIMIT is required when query table function with custom format?

### ISSUE THREAD

**Issue by zhicwu** [ClickHouse/ClickHouse#36183]
`select 1 format JSONEachRow` works but not the followings:

```sql
select * from numbers(5) format JSONEachRow

select * from url('http://localhost:8123/ping', LineAsString) format JSONEachRow

select * from jdbc('datasource1', "select col1 from table1") format JSONEachRow
```

The first query ended up with below error. I had to add LIMIT in the query to make it work(e.g. `select * from numbers(5) limit 10 format JSONEachRow`). Is this by design or a defect?
```
SQL Error [62] [07000]: Code: 62. DB::Exception: Syntax error: failed at position 45 ('LIMIT') (line 2, col 1): LIMIT 0, 200. Expected one of: SETTINGS, end of query. (SYNTAX_ERROR) (version 22.3.3.44 (official build))
```

**Comment by tavplubix** [comment]
It's not required. The first two queries work fine with `clickhouse-client`:
```
ClickHouse client version 22.4.1.1.
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 22.4.1 revision 54455.

Warnings:
 * Server was built in debug mode. It will work slowly.

dell9510 :) select * from numbers(5) format JSONEachRow

SELECT *
FROM numbers(5)
FORMAT JSONEachRow

Query id: 796151f8-bb9a-4149-a8bd-75062d0e1689

{"number":"0"}
{"number":"1"}
{"number":"2"}
{"number":"3"}
{"number":"4"}

5 rows in set. Elapsed: 0.006 sec. 

dell9510 :) select * from url('http://localhost:8123/ping', LineAsString) format JSONEachRow

SELECT *
FROM url('http://localhost:8123/ping', LineAsString)
FORMAT JSONEachRow

Query id: f2ccc62e-01c7-480f-91c3-1d275c43f8ea

{"line":"Ok."}

1 rows in set. Elapsed: 0.009 sec. 

dell9510 :) 
```

(haven't tested the third one, because I don't have jdbc bridge installed)

What is `SQL Error [62] [07000]`?

**Comment by zhicwu** [comment]
Thanks @tavplubix. The issue exists in latest 22.3 release, but good to know it's been fixed in the upcoming new version.

> What is SQL Error [62] [07000]?

Sorry the error message was copied from DBeaver output. 62 is the error code in ClickHouse, while 07000 is the mapped [SQL State](https://en.wikipedia.org/wiki/SQLSTATE) in JDBC driver.

**Comment by tavplubix** [comment]
> The issue exists in latest 22.3 release, but good to know it's been fixed in the upcoming new version.

> DBeaver

Probably the issue has never existed in ClickHouse, it looks like a bug in DBeaver.

I cannot reproduce it in 22.3 too:
```
ClickHouse local version 22.3.1.1.

dell9510 :) select * from numbers(5) format JSONEachRow

SELECT *
FROM numbers(5)
FORMAT JSONEachRow

Query id: 036a7274-1367-4c61-8a12-0193d336c6b3

{"number":"0"}
{"number":"1"}
{"number":"2"}
{"number":"3"}
{"number":"4"}

5 rows in set. Elapsed: 0.002 sec. 

dell9510 :) 
```

**Comment by zhicwu** [comment]
You're right, it's an issue in DBeaver - submitted dbeaver/dbeaver#16189 to track this.
