### ISSUE TITLE
DB::Exception: A setting's value string has to be an exactly one character long

### ISSUE THREAD

**Issue by FanWuu** [ClickHouse/ClickHouse#36197]
this is my data file 
```bash
cat  a.txt  
aaa|!bbbbb|!cccccc|!ddddddd|!eeee
aaa|!bbbbb|!cccccc|!ddddddd|!eeee
aaa|!bbbbb|!cccccc|!ddddddd|!eeee
aaa|!bbbbb|!cccccc|!ddddddd|!eeee
aaa|!bbbbb|!cccccc|!ddddddd|!eeee 
```

I get an error when I import this file
``` bash
cat  ./a.txt  | clickhouse-client --query "INSERT INTO  test.a FORMAT CSV"  --format_csv_delimiter='|!'
```
 DB::Exception: A setting's value string has to be an exactly one character long 
![image](https://user-images.githubusercontent.com/41465662/163189019-8e66e674-c8b9-45ab-8aa7-1b07420ec821.png)

Is this a bug and is there a fix planned ?

**Comment by FanWuu** [comment]
> It's not a bug. `format_csv_delimiter` is designed to use only one character.
> 
> You need to use `FORMAT CustomSeparated` + `SETTINGS format_custom_escaping_rule = 'CSV', format_custom_field_delimiter = '|!'`
> 
> ```
> cat  ./a.txt  | clickhouse-client --query "INSERT INTO  test.a FORMAT CSV CustomSeparated SETTINGS format_custom_escaping_rule = 'CSV', format_custom_field_delimiter = '|!' "
> ```

![image](https://user-images.githubusercontent.com/41465662/163301661-8d6e2d2b-8c97-4cc4-bff8-570f75de0582.png)
This does not work for '|!', how to solve this problem

**Comment by FanWuu** [comment]
> It's not a bug. `format_csv_delimiter` is designed to use only one character.
> 
> You need to use `FORMAT CustomSeparated` + `SETTINGS format_custom_escaping_rule = 'CSV', format_custom_field_delimiter = '|!'`
> 
> ```
> cat  ./a.txt  | clickhouse-client --query "INSERT INTO  test.a FORMAT CSV CustomSeparated SETTINGS format_custom_escaping_rule = 'CSV', format_custom_field_delimiter = '|!' "
> ```

![image](https://user-images.githubusercontent.com/41465662/163301661-8d6e2d2b-8c97-4cc4-bff8-570f75de0582.png)
This does not work for '|!', how to solve this problem

**Comment by zlianzhuang** [comment]
export ZZ='|!'
cat  ./a.txt  | clickhouse-client --query "INSERT INTO  test.a FORMAT CSV CustomSeparated SETTINGS format_custom_escaping_rule = 'CSV', format_custom_field_delimiter = '$ZZ' "
'|!' is also don't work.

**Comment by den-crane** [comment]
Oops, sorry. Copy/paste error "FORMAT CSV CustomSeparated" -> "FORMAT CustomSeparated"

Special characters should be escapes.

```
 create table s ( S1 String, S2 String, S3 String, S4 String, S5 String) Engine=Memory;

cat a.txt | clickhouse-client --query "INSERT INTO s FORMAT CustomSeparated settings format_custom_field_delimiter="\'\|\!\'",format_custom_escaping_rule='CSV'"

select * from s;
┌─S1──┬─S2────┬─S3─────┬─S4──────┬─S5───┐
│ aaa │ bbbbb │ cccccc │ ddddddd │ eeee │
│ aaa │ bbbbb │ cccccc │ ddddddd │ eeee │
│ aaa │ bbbbb │ cccccc │ ddddddd │ eeee │
│ aaa │ bbbbb │ cccccc │ ddddddd │ eeee │
│ aaa │ bbbbb │ cccccc │ ddddddd │ eeee │
└─────┴───────┴────────┴─────────┴──────┘
```

**Comment by FanWuu** [comment]
Every character of '|!' needs to be Anti escape , maybe   --format_custom_field_delimiter  shoule be  optimize
