### ISSUE TITLE
Default socket file for communicate with MySQL

### ISSUE THREAD

**Issue by edonin** [ClickHouse/ClickHouse#3621]
Hello,

I am using a MySQL table in clickhouse 18.14.12 for retreiving data from MySQL. The MySQL is on the same machine.
When I create the table, I get an exception :
2018.11.20 11:21:36.038910 [ 20 ] {} <Error> HTTPHandler: Poco::Exception. Code: 1000, e.code() = 2002, e.displayText() = mysqlxx::ConnectionFailed: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) ((nullptr):0), e.what() = mysqlxx::ConnectionFailed

From my understanding, Clickhouse is trying to use the mysql socket file '/var/run/mysqld/mysqld.sock' for communicate locally with MySQL. Nevertheless, my MySQL standard installation is using '/tmp/mysql.sock'.
This seems to be a quite recent change : https://github.com/yandex/ClickHouse/commit/26aabc9f23f8b43ae95b46ff6d7466cbf857f8fb

So, I have the following questions :
* What are the reasons behind the previous commit ?
* Is there a way to specify the socket file to use when using a mysql table or the mysql SQL function (I found it when using a mysql dictionnary) ?
* Is there a way to define globally the socket file to use ?

Thanks,

**Comment by filimonov** [comment]
Looks like you can't specify socket in connection settings for MySQL storage, only for dicts.

Fast workaround - connect using tcp  (just use 127.0.0.1 instead of localhost).

Probably socket syntax should be added, as work via unix socket is faster.

**Comment by edonin** [comment]
Thanks for the explanation Alexey. I will use 127.0.0.1 until it will be configurable.

**Comment by alexey-milovidov** [comment]
It can be made configurable, see https://github.com/ClickHouse/ClickHouse/pull/983

**Comment by filimonov** [comment]
Not clear why closed? It is not implemented.

**Comment by alexey-milovidov** [comment]
Workaround possible.

**Comment by alexey-milovidov** [comment]
The fact that MySQL client silently using unix socket when the user specified `localhost` - it is an infamous usability issue that we have to be aware.
