### ISSUE TITLE
How about enable Zero-copy Replication on Ora.. ASM / Ver.. CFS / GPFS / OCFS2 shared disks ?

### ISSUE THREAD

**Issue by maskshell** [ClickHouse/ClickHouse#36247]
https://clickhouse.com/docs/en/operations/storing-data/#zero-copy

According to my understanding of the above document, if we use the "Zero-copy Replication" feature, it means that I can quickly scale compute nodes without worrying about the storage behind the compute nodes.

Currently, this feature is only available on S3, HDFS. However, if you consider "Share", then Oracle ASM / Veritas CFS / GPFS / OCFS2, or Alibaba Cloud's cloud native DBFS, which created "Shared Disks" also have the same features as HDFS.

So, is it possible to experiment with the "Zero-copy Replication" feature on the premise that the underlying architecture is Shared Disks?

**Comment by alexey-milovidov** [comment]
In fact, zero copy replication is not available for production usage.
It is under development and known issues exist.

So, the answer - you should not enable it.

**Comment by den-crane** [comment]
Zero-copy Replication is supported only for remote block storages.
Shared filesystem are not supported.  https://github.com/ClickHouse/ClickHouse/discussions/33998

**Comment by alexey-milovidov** [comment]
@den-crane There are known issues with "zero copy replication". In fact is has not been finished, so it is not supported.

**Comment by zhaojintaozhao** [comment]
> @den-crane There are known issues with "zero copy replication". In fact is has not been finished, so it is not supported.

What's kown issues abount “zero-copy replication” (ensure one copy of data if there are more than one replica in a region) and the local cache?

**Comment by alexey-milovidov** [comment]
@zhaojintaozhao it is unfinished and has bugs.
