### ISSUE TITLE
APPLY column modifier with lambda?

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#36273]
something like 

```
SELECT * APPLY( x -> if(x<10, 0, x))  FROM table

SELECT * APPLY( x -> replace(x, 'secret', 'xxx') )  FROM table
```

Additionally: sometimes some manipulation with column names may be desired. Not sure how to do that, but maybe also with (extra) syntax? 

```
SELECT * APPLY( (x, col_name) -> ( if(x<10, 0, x), col_name || '_normalized'  )  FROM table
```

/cc @amosbird

**Comment by amosbird** [comment]
I think it's covered in https://github.com/ClickHouse/ClickHouse/pull/35660

**Comment by filimonov** [comment]
> I think it's covered in #35660

Yep, almost. Maybe that second arg for the APPLY can also be lambda getting the column name? (adding suffixes is only one of the potential transformations which may be needed)

**Comment by amosbird** [comment]
> APPLY can also be lambda getting the column name?

It's not feasible to use lambda, see https://github.com/ClickHouse/ClickHouse/issues/30411#issuecomment-1080134482

I'll make it consistent with the `RENAME` format.

**Comment by mbtolou** [comment]
https://github.com/ClickHouse/ClickHouse/issues/45618
