### ISSUE TITLE
Suggestion: Certificates as GitHub Secrets

### ISSUE THREAD

**Issue by juliojimenez** [ClickHouse/ClickHouse#36280]
I wasn't sure which bucket to place this issue under, so I opted for the blank issue. Apologies if this is incorrect.

In keeping with the security best practice of not committing secrets to source control, I would like to suggest adding the certificate mentioned in #36161 as a GitHub Secret and adding a step to prepare the certificate for use in GitHub Workflows as follows, or something that fits better with CH-codestyle.

```
- name: Prepare MONGO_CERT_TEST
        run: |
          echo "${{ secrets.MONGO_CERT_TEST }}" > tests/integration/helpers/mongo_cert.pem
          chmod 400 tests/integration/helpers/mongo_cert.pem
```

**Comment by nikitamikhaylov** [comment]
@juliojimenez We want these tests to be fully reproducible locally. How can an external contributor run this tests otherwise?

**Comment by alexey-milovidov** [comment]
This certificate is not a secret, so placing it in "secrets" will be inappropriate.
