### ISSUE TITLE
Local Cache Implement Issue

### ISSUE THREAD

**Issue by KinderRiven** [ClickHouse/ClickHouse#36289]
[loca cache pull request](https://github.com/ClickHouse/ClickHouse/commit/818459b9f05383dc671809cc2075f65f1b8ab94e)
Hello, I would like to ask whether the local cache function has been perfected, and whether the official has a follow-up plan for the local cache? @kssenii

**Comment by den-crane** [comment]
https://clickhouse.com/blog/clickhouse-22-3-lts-released/

https://youtu.be/GzeANZzPras?t=393

**Comment by KinderRiven** [comment]
> https://clickhouse.com/blog/clickhouse-22-3-lts-released/
> 
> https://youtu.be/GzeANZzPras?t=393

Thank you !~
