### ISSUE TITLE
UDF. reduce ts data

### ISSUE THREAD

**Issue by e11it** [ClickHouse/ClickHouse#36290]
Hi!
I need to reduce time series data and keep only important point.
I proposed that UDF can be a right way for this task and have some questions.

1. Can the result of UDF be Null?
   Function decleared as `<return_type>Nullable(Float64)</return_type>`
   If script return '\n' than the result in CH is default value for type(0 in my case)
   If script return 'Null' - error: Cannot parse NaN. (CANNOT_PARSE_INPUT_ASSERTION_FAILED)
2. Can function return more than one column?
3. Is it possible to use functions to defeat a series (example: to output only even numbers).

Thx!

**Comment by Algunenano** [comment]
> Can the result of UDF be Null?

Yes. But you need to return the same string as it's used for NULL for the format you are using

Example:
```
<functions>
    <function>
        <type>executable</type>
        <name>test_function</name>
        <return_type>Nullable(UInt64)</return_type>
        <argument>
            <type>UInt64</type>
        </argument>
        <argument>
            <type>UInt64</type>
        </argument>
        <format>TabSeparated</format>
        <command>cd /; clickhouse local --input-format TabSeparated --output-format TabSeparated --structure 'x UInt64, y UInt64' --query "SELECT NULL::Nullable(UInt64) FROM table"</command>
        <execute_direct>0</execute_direct>
    </function>
</functions>
```

```
SELECT test_function(0, 1)

Query id: 009d234b-1e06-4858-8c0a-2a96614451c5

   ┌─test_function(0, 1)─┐
1. │                ᴺᵁᴸᴸ │
   └─────────────────────┘
```

> Can function return more than one column?

No. A function must return exactly one value for each input.

> Is it possible to use functions to defeat a series (example: to output only even numbers).

No. The function must return always one value.
