### ISSUE TITLE
The Bool data type is not documented in the official documentation.

### ISSUE THREAD

**Issue by nayakravi** [ClickHouse/ClickHouse#36294]
It appears that the Bool data type is now supported and this was added to the release notes back in the ClickHouse release `v21.12, 2021-12-15` - see https://clickhouse.com/docs/en/whats-new/changelog/2021/.
However, the documentation here https://clickhouse.com/docs/en/sql-reference/data-types/boolean/ indicates:
`There is no separate type for boolean values. Use UInt8 type, restricted to the values 0 or 1.`.
Is the Bool data type officially supported?

**Comment by alexey-milovidov** [comment]
@rfraposa Let's close this task to highlight the fact that we have failed to solve it.

**Comment by avraam-inside** [comment]
Why did you close the task?!

Open back and fix the documentation, what is the absurdity?

**Comment by avraam-inside** [comment]
Great. It turned out that Google leads to an incorrect, incomprehensibly existing site with murky documentation, instead: https://content.clickhouse.tech/docs/en/sql-reference/data-types/boolean/

**Comment by alexey-milovidov** [comment]
@avraam-inside Thank you! I'm deleting this website.
