### ISSUE TITLE
LIVE VIEW ONLY UPDATES

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#36298]
**Use case**

Run query and get only new rows as new data being inserted in table.

Ability to get only new data in live view, without recalculating:

**Describe the solution you'd like**

```
 CREATE LIVE VIEW insert_view AS SELECT * FROM test_lv;
 WATCH insert_view  ONLY UPDATES
```

**Comment by alexey-milovidov** [comment]
This feature is unrelated to LIVE VIEWs and should be better to be implemented separately.
