### ISSUE TITLE
Segmentation fault in su-exec on Linux ARM64 Docker image

### ISSUE THREAD

**Issue by martin-g** [ClickHouse/ClickHouse#36293]
> You have to provide the following information whenever possible.

```
$ docker run --rm -it clickhouse/clickhouse-server:22.3.3.44 bash
/entrypoint.sh: line 39:    10 Segmentation fault      $gosu test -f "$CLICKHOUSE_CONFIG" -a -r "$CLICKHOUSE_CONFIG"
Configuration file '/etc/clickhouse-server/config.xml' isn't readable by user with id '101'
```

> A clear and concise description of what works not as it is supposed to.

I use the latest version of the Docker image - 22.3.3.44.

**Enable crash reporting**

> If possible, change "enabled" to true in "send_crash_reports" section in `config.xml`:

config.xml is not related. 
The problem is that the Docker image has corrupted /bin/su-exec which prevents starting the server.

**How to reproduce**

On Linux ARM64 machine execute: 

1) `docker run --rm -it -v --entrypoint bash  clickhouse/clickhouse-server:22.3.3.44`
2) inside docker try to use `su-exec`
```
# su-exec test
Segmentation fault
```

**Expected behavior**

> A clear and concise description of what you expected to happen.

su-exec should print its usage text:
```
Usage: su-exec user-spec command [args]
```
instead of failing with segmentation fault

Initially reported at https://github.com/housepower/spark-clickhouse-connector/pull/85

**Comment by martin-g** [comment]
The problem seems to be caused by the usage of `tcc` for the [compilation.](https://github.com/ClickHouse/ClickHouse/blob/722af5a2f5e81eedc20667de11daf7e5ba116ee6/docker/server/Dockerfile.ubuntu#L23)

```
root@99703fe58717:/# tcc su-exec.c
root@99703fe58717:/# ./a.out 
Segmentation fault
root@99703fe58717:/# gcc su-exec.c
root@99703fe58717:/# ./a.out 
Usage: ./a.out user-spec command [args]
```

**Comment by alexey-milovidov** [comment]
Looks like tcc is not cross-platform: https://bellard.org/tcc/

> tcc generates x86 code

**Comment by alexey-milovidov** [comment]
Workaround: use ClickHouse without Docker
(Docker gives nothing on top of ClickHouse, it gives no advantages at all)

**Comment by martin-g** [comment]
Thanks for the suggested workaround!
But we want to build a "one-click setup" demo of https://github.com/housepower/spark-clickhouse-connector. It is based on Docker Compose and includes several more services.

I hope a new version based on clang/gcc will be released soon!
Thank you in advance!

**Comment by den-crane** [comment]
@martin-g you can build own CH image temporary with gcc or with go-su https://github.com/anselmodadams/ClickHouse/blob/51219f9935ffc15b794bd43fed3226f194423f2e/docker/server/Dockerfile#L72
