### ISSUE TITLE
How to disable cache when query

### ISSUE THREAD

**Issue by yandongl** [ClickHouse/ClickHouse#36301]
Is there a way to disable query optimization when debugging?

I want to test the select performance of my table by  querying like 
```
select * from default.my_table where id='abc'
```
The first time, it will take about 40 seconds.
However, The elapsed time will be less than 1 second, when I query the same SQL again, or just change the condition to `where id = 'xxx'`.

It seems something has been cached, but it is not expected in performance testing.

There is a method here on stackoverflow, but it needs to be executed manually before every query, which is very inconvenient.

https://stackoverflow.com/questions/58653313/clickhouse-select-query-without-cache

**Comment by den-crane** [comment]
There is no cache in CH. Clickhouse access files using Linux (OS) pagecache

You can try to use

```
 --min_bytes_to_use_direct_io arg                                     The minimum number of bytes for reading the data with O_DIRECT option during SELECT queries execution. 0 - disabled.

```

```
select * from default.my_table where id='abc' settings min_bytes_to_use_direct_io=1
```

**Comment by yandongl** [comment]
Thanks

**Comment by champ0617** [comment]
> There is no cache in CH. Clickhouse accesses files using Linux (OS) pagecache
> 
> You can try to use
> 
> ```
>  --min_bytes_to_use_direct_io arg                                     The minimum number of bytes for reading the data with O_DIRECT option during SELECT queries execution. 0 - disabled.
> ```
> 
> ```
> select * from default.my_table where id='abc' settings min_bytes_to_use_direct_io=1
> ```

![image](https://user-images.githubusercontent.com/24335956/233523610-824fa772-4dac-4fe6-931c-04022f90e03e.png)
after add settings min_bytes_to_use_direct_io=1 , it seems to read in cache ,  I can not understand, this is why?

**Comment by xoelop** [comment]
You can disable the filesystem cache by doing `set enable_filesystem_cache = 0;`, as described in https://clickhouse.com/blog/a-simple-guide-to-clickhouse-query-optimization-part-1
