### ISSUE TITLE
Dockerfile in the repository is not updated on releases.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#36304]
See `ARG VERSION=22.1.1.*`.

**Comment by Felixoid** [comment]
Should be a part of #34900

As well as updating contributors for each new tag

**Comment by alexey-milovidov** [comment]
@Felixoid No, it is not updated: https://github.com/ClickHouse/ClickHouse/blob/master/docker/server/Dockerfile.ubuntu#L32

**Comment by Felixoid** [comment]
Yep, it looks like I've been distracted and forgot to add it to the linked issue.

**Comment by alexey-milovidov** [comment]
Looks like it's fixed.
