### ISSUE TITLE
JSONColumns data format

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#36338]
**Use case**

https://github.com/leeoniya/uPlot/tree/master/docs#data-format

**Describe the solution you'd like**

Variant 1:
```
[
 [1, 2, 3, ...],
 ["Hello", "world", "goodbye", ...]
]
```

Variant 2:
```
{
    "name1": [1, 2, 3, ...],
    "name2": ["Hello", "world", "goodbye", ...]
}
```

Variant 3:
```
{
    "data": ... see above
    "metadata": ...
    "stats": ...
}
```

**Comment by pibi** [comment]
Variant 2 is the one we are suggesting in #34509., but Variant 3 could also work for us.

**Comment by Avogar** [comment]
> Variant 2 is the one we are suggesting in #34509., but Variant 3 could also work for us.

I think I will implement all 3 variants. Like we already have 3 variants for row-based json formats - JSONCompactEachRow, JSONEachRow, JSON

**Comment by pibi** [comment]
Sounds good, although I'm not sure how it works with Variant 1 without the column names. Are the subarrays listed in the same order as the columns from the select?

**Comment by Avogar** [comment]
> Are the subarrays listed in the same order as the columns from the select?

Yep, It will be like transposing the JSONCompactEachRow result
