### ISSUE TITLE
"Revert" PRs should be processed as "Not for changelog"

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#36339]
https://github.com/ClickHouse/ClickHouse/pull/36337

**Comment by Felixoid** [comment]
Here's the issue. Templates don't work for `revert` PRs

https://github.com/ClickHouse/ClickHouse/compare/master...revert-36337-revert-36126-fork_chmaster2?expand=1

So we need to analyze a body. A way to go would be checking lines for `\AReverts ClickHouse/ClickHouse#[\d+]\Z` regexp. And if it's found, than don't check the rest body and label it `pr-not-for-changelog`
