### ISSUE TITLE
A setting `throw_if_no_data_to_insert`

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#36336]
**Use case**

ClickHouse already throws exception if the data for INSERT is empty:

```
Code: 108. DB::Exception: No data to insert
```

Let's introduce a setting, enabled by default, to control this behavior.
The user will be able to disable it to allow empty INSERTs.

This is useful in some batch scripts.

**Comment by ucasfl** [comment]
In interactive mode: `insert into ... values;` will succeed, but `insert into ... values` without `;` will throw exception.
