### ISSUE TITLE
Hostile environments can poison ClickHouse with LD_PRELOAD

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#36340]
**Use case**

https://colab.research.google.com/drive/1wzYn59PA9EDyra6356a8rUpwd3zUX0Zt?usp=sharing

**Describe the solution you'd like**

There are multiple ways to prevent LD_PRELOAD:

- link statically with musl to prevent any chance for LD_PRELOAD working;
- add some flag to the binary like capabilities or setuid to also prevent LD_PRELOAD working;
- don't allow it with some env variable;
- implement our own dynamic loader.

Also possible workaround:

- check if LD_PRELOAD is set very early at program startup. If it is, reset it and exec ourself with the same argc, argv.

**Comment by htfy96** [comment]
Hi, I noticed that clickhouse local stopped working after the latest release and found this issue. It's very common in my firm to set custom `LD_LIBRARY_PATH` pointing to `$HOME/local/.lib` to allow users to install their own libraries. I can work around this by writing a wrapper script to `unset LD_LIBRARY_PATH` before invoking `clickhouse`, but perhaps a builtin solution like auto-reexec could improve the usability.

**Comment by itrofimow** [comment]
This breaks out of the box usage of ClickHouse with https://github.com/actions/setup-python in CI, because setup-python uses `LD_LIBRARY_PATH`.

We had to freeze ClickHouse version in our repository (https://github.com/yandex/yandex-taxi-testsuite/commit/b5a7b85b5d4963dc18b296a46c24e68427eb6de4) as a temporary workaround and it would be really nice if it could be fixed without forcing users to write custom wrappers for unsetting/setting some environment variables.

@alexey-milovidov

**Comment by alexey-milovidov** [comment]
I'm considering re-running with exec.
Long term solution is removing dynamic linking altogether.

**Comment by ivan-tkatchev** [comment]
There are legitimate use-cases for LD_PRELOAD - for example, for custom malloc() and free() implementations.

Is there a deeper rationale why LD_PRELOAD is labeled as 'harmful' by a blanket statement? If yes, it would be nice if this was documented.

**Comment by alexey-milovidov** [comment]
Custom malloc/free doesn't work with ClickHouse.
LD_PRELOAD is harmful, because it lets external untrusted code into the process' address space.

**Comment by ivan-tkatchev** [comment]
> Custom malloc/free doesn't work with ClickHouse.

Is there a documented reason? Do custom allocators need special support for Clickhouse? (I see in other tickets that allocators other than jemalloc have been tested, so at least it should be possible.)
