### ISSUE TITLE
branch 22.3 build fails on x64 centos 

### ISSUE THREAD

**Issue by JimWen** [ClickHouse/ClickHouse#36347]
> You have to provide the following information whenever possible.

Fail to build clickhouse under centos 7.9

> A clear and concise description of what works not as it is supposed to.

Failed when compile contrib/aws-s3-cmake/CMakeFiles/_aws_s3_checksums.dir/__/aws-checksums/source/intel/crc32c_sse42_asm.c.o.

But when compile contrib/aws-s3-cmake seperately , it's ok.

> version info

**system**
CentOS Linux release 7.7.1908 (Core)
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                96
On-line CPU(s) list:   0-95
Thread(s) per core:    2
Core(s) per socket:    24
座：                 2
NUMA 节点：         2
厂商 ID：           GenuineIntel
CPU 系列：          6
型号：              85
型号名称：        Intel(R) Xeon(R) Gold 5220R CPU @ 2.20GHz
步进：              7
CPU MHz：             1000.097
CPU max MHz:           4000.0000
CPU min MHz:           1000.0000
BogoMIPS：            4400.00
虚拟化：           VT-x
L1d 缓存：          32K
L1i 缓存：          32K
L2 缓存：           1024K
L3 缓存：           36608K
NUMA 节点0 CPU：    0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58,60,62,64,66,68,70,72,74,76,78,80,82,84,86,88,90,92,94
NUMA 节点1 CPU：    1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49,51,53,55,57,59,61,63,65,67,69,71,73,75,77,79,81,83,85,87,89,91,93,95
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 intel_ppin intel_pt ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke avx512_vnni md_clear spec_ctrl intel_stibp flush_l1d arch_capabilities

**git**
commit 8cc7a0fe33c390c8eb9d063caeb757956fe5619f
Merge: 0bc20e6 3ca2ee7
Author: Anton Popov <ap@clickhouse.com>
Date:   Thu Apr 14 14:08:03 2022 +0200

    Merge pull request #36242 from ClickHouse/backport/22.3/35687

    Backport #35687 to 22.3: Fix reading from type object

**cmake**
cmake version 3.22.4

**ninja**
1.10.2

**clang**
clang -x c++ -E - -v < /dev/null
clang version 14.0.1
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-redhat-linux/11
Selected GCC installation: /usr/lib/gcc/x86_64-redhat-linux/11
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
 (in-process)
 "/usr/local/bin/clang-14" -cc1 -triple x86_64-unknown-linux-gnu -E -disable-free -clear-ast-before-backend -main-file-name - -mrelocation-model static -mframe-pointer=all -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -debugger-tuning=gdb -v -fcoverage-compilation-dir=/home/wenzhou/ClickHouse -resource-dir /usr/local/lib/clang/14.0.1 -internal-isystem /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11 -internal-isystem /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/x86_64-redhat-linux -internal-isystem /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/backward -internal-isystem /usr/local/lib/clang/14.0.1/include -internal-isystem /usr/local/include -internal-isystem /usr/lib/gcc/x86_64-redhat-linux/11/../../../../x86_64-redhat-linux/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdeprecated-macro -fdebug-compilation-dir=/home/wenzhou/ClickHouse -ferror-limit 19 -fgnuc-version=4.2.1 -fcxx-exceptions -fexceptions -fcolor-diagnostics -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o - -x c++ -
clang -cc1 version 14.0.1 based upon LLVM 14.0.1 default target x86_64-unknown-linux-gnu
ignoring nonexistent directory "/usr/lib/gcc/x86_64-redhat-linux/11/../../../../x86_64-redhat-linux/include"
ignoring nonexistent directory "/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11
 /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/x86_64-redhat-linux
 /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/backward
 /usr/local/lib/clang/14.0.1/include
 /usr/local/include
 /usr/include
End of search list.

**g++**
g++ -x c++ -E - -v < /dev/null
Using built-in specs.
COLLECT_GCC=g++
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/opt/rh/devtoolset-11/root/usr --mandir=/opt/rh/devtoolset-11/root/usr/share/man --infodir=/opt/rh/devtoolset-11/root/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --with-default-libstdcxx-abi=gcc4-compatible --enable-plugin --enable-initfini-array --with-isl=/builddir/build/BUILD/gcc-11.2.1-20210728/obj-x86_64-redhat-linux/isl-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 11.2.1 20210728 (Red Hat 11.2.1-1) (GCC)
COLLECT_GCC_OPTIONS='-E' '-v' '-shared-libgcc' '-mtune=generic' '-march=x86-64'
 /opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/cc1plus -E -quiet -v -D_GNU_SOURCE - -mtune=generic -march=x86-64 -dumpbase -
ignoring nonexistent directory "/opt/rh/devtoolset-11/root/usr/lib/gcc/x86_64-redhat-linux/11/include-fixed"
ignoring nonexistent directory "/opt/rh/devtoolset-11/root/usr/lib/gcc/x86_64-redhat-linux/11/../../../../x86_64-redhat-linux/include"
#include "..." search starts here:
#include <...> search starts here:
 /opt/rh/devtoolset-11/root/usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11
 /opt/rh/devtoolset-11/root/usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/x86_64-redhat-linux
 /opt/rh/devtoolset-11/root/usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/backward
 /opt/rh/devtoolset-11/root/usr/lib/gcc/x86_64-redhat-linux/11/include
 /usr/local/include
 /opt/rh/devtoolset-11/root/usr/include
 /usr/include
End of search list.

COMPILER_PATH=/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/:/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/:/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/:/opt/rh/devtoolset-11/root/usr/lib/gcc/x86_64-redhat-linux/11/:/opt/rh/devtoolset-11/root/usr/lib/gcc/x86_64-redhat-linux/
LIBRARY_PATH=/opt/rh/devtoolset-11/root/usr/lib/gcc/x86_64-redhat-linux/11/:/opt/rh/devtoolset-11/root/usr/lib/gcc/x86_64-redhat-linux/11/../../../../lib64/:/lib/../lib64/:/usr/lib/../lib64/:/opt/rh/devtoolset-11/root/usr/lib/gcc/x86_64-redhat-linux/11/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-E' '-v' '-shared-libgcc' '-mtune=generic' '-march=x86-64'

> **Error message and/or stacktrace**

```
[5036/10108] Building C object contrib/aws-s3-cmak...__/aws-checksums/source/intel/crc32c_sse42_asm.c.o
FAILED: contrib/aws-s3-cmake/CMakeFiles/_aws_s3_checksums.dir/__/aws-checksums/source/intel/crc32c_sse42_asm.c.o
/usr/local/bin/clang --target=x86_64-linux-gnu --sysroot=/home/wenzhou/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc -DHAS_RESERVED_IDENTIFIER -DSTD_EXCEPTION_HAS_STACK_TRACE=1 -I/home/wenzhou/ClickHouse/base/glibc-compatibility/memcpy -isystem /home/wenzhou/ClickHouse/contrib/aws-checksums/include -isystem /home/wenzhou/ClickHouse/contrib/libcxx/include -isystem /home/wenzhou/ClickHouse/contrib/libcxxabi/include -isystem /home/wenzhou/ClickHouse/contrib/libunwind/include --gcc-toolchain=/home/wenzhou/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64 --gcc-toolchain=/home/wenzhou/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64 -fdiagnostics-color=always  -pipe -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -mavx512f -mavx512bw -mavx512vl -fasynchronous-unwind-tables -ffile-prefix-map=/home/wenzhou/ClickHouse=. -falign-functions=32  -Wall -Wno-unused-command-line-argument  -fdiagnostics-absolute-paths -fexperimental-new-pass-manager -w -O3 -DNDEBUG   -D OS_LINUX -g0 -Werror -std=gnu99 -MD -MT contrib/aws-s3-cmake/CMakeFiles/_aws_s3_checksums.dir/__/aws-checksums/source/intel/crc32c_sse42_asm.c.o -MF contrib/aws-s3-cmake/CMakeFiles/_aws_s3_checksums.dir/__/aws-checksums/source/intel/crc32c_sse42_asm.c.o.d -o contrib/aws-s3-cmake/CMakeFiles/_aws_s3_checksums.dir/__/aws-checksums/source/intel/crc32c_sse42_asm.c.o -c /home/wenzhou/ClickHouse/contrib/aws-checksums/source/intel/crc32c_sse42_asm.c
clang: /home/wenzhou/llvm-project-llvmorg-14.0.1/llvm/lib/CodeGen/TwoAddressInstructionPass.cpp:1492: void {anonymous}::TwoAddressInstructionPass::processTiedPairs(llvm::MachineInstr*, {anonymous}::TwoAddressInstructionPass::TiedPairList&, unsigned int&): Assertion `i == DstIdx || !MI->getOperand(i).isReg() || MI->getOperand(i).getReg() != RegA' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /usr/local/bin/clang --target=x86_64-linux-gnu --sysroot=/home/wenzhou/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc -DHAS_RESERVED_IDENTIFIER -DSTD_EXCEPTION_HAS_STACK_TRACE=1 -I/home/wenzhou/ClickHouse/base/glibc-compatibility/memcpy -isystem /home/wenzhou/ClickHouse/contrib/aws-checksums/include -isystem /home/wenzhou/ClickHouse/contrib/libcxx/include -isystem /home/wenzhou/ClickHouse/contrib/libcxxabi/include -isystem /home/wenzhou/ClickHouse/contrib/libunwind/include --gcc-toolchain=/home/wenzhou/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64 --gcc-toolchain=/home/wenzhou/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64 -fdiagnostics-color=always -pipe -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -mavx512f -mavx512bw -mavx512vl -fasynchronous-unwind-tables -ffile-prefix-map=/home/wenzhou/ClickHouse=. -falign-functions=32 -Wall -Wno-unused-command-line-argument -fdiagnostics-absolute-paths -fexperimental-new-pass-manager -w -O3 -DNDEBUG -D OS_LINUX -g0 -Werror -std=gnu99 -MD -MT contrib/aws-s3-cmake/CMakeFiles/_aws_s3_checksums.dir/__/aws-checksums/source/intel/crc32c_sse42_asm.c.o -MF contrib/aws-s3-cmake/CMakeFiles/_aws_s3_checksums.dir/__/aws-checksums/source/intel/crc32c_sse42_asm.c.o.d -o contrib/aws-s3-cmake/CMakeFiles/_aws_s3_checksums.dir/__/aws-checksums/source/intel/crc32c_sse42_asm.c.o -c /home/wenzhou/ClickHouse/contrib/aws-checksums/source/intel/crc32c_sse42_asm.c
1.	<eof> parser at end of file
2.	Code generation
3.	Running pass 'Function Pass Manager' on module '/home/wenzhou/ClickHouse/contrib/aws-checksums/source/intel/crc32c_sse42_asm.c'.
4.	Running pass 'Two-Address instruction pass' on function '@aws_checksums_crc32c_hw'
 #0 0x0000000003fcc287 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/usr/local/bin/clang+0x3fcc287)
 #1 0x0000000003fcc34a PrintStackTraceSignalHandler(void*) Signals.cpp:0:0
 #2 0x0000000003fca18b llvm::sys::RunSignalHandlers() (/usr/local/bin/clang+0x3fca18b)
 #3 0x0000000003fcbbc0 llvm::sys::CleanupOnSignal(unsigned long) (/usr/local/bin/clang+0x3fcbbc0)
 #4 0x0000000003eefef0 (anonymous namespace)::CrashRecoveryContextImpl::HandleCrash(int, unsigned long) CrashRecoveryContext.cpp:0:0
 #5 0x0000000003ef03a5 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #6 0x00007fac1eeae630 __restore_rt sigaction.c:0:0
 #7 0x00007fac1dedc387 raise (/lib64/libc.so.6+0x36387)
 #8 0x00007fac1dedda78 abort (/lib64/libc.so.6+0x37a78)
 #9 0x00007fac1ded51a6 __assert_fail_base (/lib64/libc.so.6+0x2f1a6)
#10 0x00007fac1ded5252 (/lib64/libc.so.6+0x2f252)
#11 0x000000000308d727 (anonymous namespace)::TwoAddressInstructionPass::processTiedPairs(llvm::MachineInstr*, llvm::SmallVector<std::pair<unsigned int, unsigned int>, 4u>&, unsigned int&) TwoAddressInstructionPass.cpp:0:0
#12 0x000000000308ed7f (anonymous namespace)::TwoAddressInstructionPass::runOnMachineFunction(llvm::MachineFunction&) TwoAddressInstructionPass.cpp:0:0
#13 0x0000000002d885cc llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (/usr/local/bin/clang+0x2d885cc)
#14 0x00000000033e7225 llvm::FPPassManager::runOnFunction(llvm::Function&) (/usr/local/bin/clang+0x33e7225)
#15 0x00000000033e7495 llvm::FPPassManager::runOnModule(llvm::Module&) (/usr/local/bin/clang+0x33e7495)
#16 0x00000000033e78bc (anonymous namespace)::MPPassManager::runOnModule(llvm::Module&) LegacyPassManager.cpp:0:0
#17 0x00000000033e2b74 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/usr/local/bin/clang+0x33e2b74)
#18 0x00000000033e80e1 llvm::legacy::PassManager::run(llvm::Module&) (/usr/local/bin/clang+0x33e80e1)
#19 0x000000000443031f (anonymous namespace)::EmitAssemblyHelper::RunCodegenPipeline(clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >&, std::unique_ptr<llvm::ToolOutputFile, std::default_delete<llvm::ToolOutputFile> >&) BackendUtil.cpp:0:0
#20 0x00000000044304f6 (anonymous namespace)::EmitAssemblyHelper::EmitAssembly(clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) BackendUtil.cpp:0:0
#21 0x0000000004431b35 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::StringRef, llvm::Module*, clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) (/usr/local/bin/clang+0x4431b35)
#22 0x00000000056e0885 clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) (/usr/local/bin/clang+0x56e0885)
#23 0x00000000070fae84 clang::ParseAST(clang::Sema&, bool, bool) (/usr/local/bin/clang+0x70fae84)
#24 0x0000000004dcd4f3 clang::ASTFrontendAction::ExecuteAction() (/usr/local/bin/clang+0x4dcd4f3)
#25 0x00000000056e3e47 clang::CodeGenAction::ExecuteAction() (/usr/local/bin/clang+0x56e3e47)
#26 0x0000000004dcce35 clang::FrontendAction::Execute() (/usr/local/bin/clang+0x4dcce35)
#27 0x0000000004d13f24 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/usr/local/bin/clang+0x4d13f24)
#28 0x0000000004f510f6 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/usr/local/bin/clang+0x4f510f6)
#29 0x0000000000bf9c47 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/usr/local/bin/clang+0xbf9c47)
#30 0x0000000000bee109 ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) driver.cpp:0:0
#31 0x0000000004bef0d7 clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::string*, bool*) const::'lambda'()::operator()() const Job.cpp:0:0
#32 0x0000000004bf0260 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::string*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#33 0x0000000003ee0f22 llvm::function_ref<void ()>::operator()() const (/usr/local/bin/clang+0x3ee0f22)
#34 0x0000000003ef056d llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/usr/local/bin/clang+0x3ef056d)
#35 0x0000000004bef2c2 clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::string*, bool*) const (/usr/local/bin/clang+0x4bef2c2)
#36 0x0000000004ba0938 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&) const (/usr/local/bin/clang+0x4ba0938)
#37 0x0000000004ba0c5d clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) const (/usr/local/bin/clang+0x4ba0c5d)
#38 0x0000000004bb1920 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) (/usr/local/bin/clang+0x4bb1920)
#39 0x0000000000bef5e7 main (/usr/local/bin/clang+0xbef5e7)
#40 0x00007fac1dec8555 __libc_start_main (/lib64/libc.so.6+0x22555)
#41 0x0000000000beae34 _start (/usr/local/bin/clang+0xbeae34)
clang-14: error: clang frontend command failed with exit code 134 (use -v to see invocation)
clang version 14.0.1
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin
clang-14: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-14: note: diagnostic msg: /tmp/crc32c_sse42_asm-53bc2d.c
clang-14: note: diagnostic msg: /tmp/crc32c_sse42_asm-53bc2d.sh
clang-14: note: diagnostic msg:

********************
```

**Comment by alexey-milovidov** [comment]
Clang (the C++ compiler) crashed.

This is an issue with either clang or hardware on your machine.
I recommend to install some other version of clang or do build on different server.

PS. We validate our builds with CI infrastructure.
The case when build is broken in release branch (or master) is not possible.

**Comment by alexey-milovidov** [comment]
You can report this issue to LLVM/Clang, but first check if master version works alright: https://github.com/llvm/llvm-project

**Comment by JimWen** [comment]
@alexey-milovidov

**Comment by JimWen** [comment]
@JimWen  ref to this https://github.com/llvm/llvm-project/issues/54957
it seems that this should trigger that bug, how can the official CI work ok.
it's wierd.

**Comment by JimWen** [comment]
> You can report this issue to LLVM/Clang, but first check if master version works alright: https://github.com/llvm/llvm-project

ref to this https://github.com/llvm/llvm-project/issues/54957
it seems that this should trigger that bug, how can the official CI work ok.
it's wierd.

**Comment by DimitryAndric** [comment]
> ref to this [llvm/llvm-project#54957](https://github.com/llvm/llvm-project/issues/54957) it seems that this should trigger that bug, how can the official CI work ok. it's wierd.

A possibility is that the CI build uses a version of clang that was built with assertions turned off, as that is often done by package maintainers, for better performance. Unfortunately clang doesn't show this information in its `--version` output, so it is probably easiest to attempt to compile the following test case from llvm/llvm-project#40330:

```c
unsigned f(const unsigned char *input)
{
  unsigned crc = ~0;
  asm("crc32b (%[in]), %[crc]" : "+c"(crc) : [crc] "c"(crc), [in] "r"(input));
  return ~crc;
}
```

Any clang built with assertions enabled will crash on this example.

**Comment by JimWen** [comment]
> > ref to this [llvm/llvm-project#54957](https://github.com/llvm/llvm-project/issues/54957) it seems that this should trigger that bug, how can the official CI work ok. it's wierd.
> 
> A possibility is that the CI build uses a version of clang that was built with assertions turned off, as that is often done by package maintainers, for better performance. Unfortunately clang doesn't show this information in its `--version` output, so it is probably easiest to attempt to compile the following test case from [llvm/llvm-project#40330](https://github.com/llvm/llvm-project/issues/40330):
> 
> ```c
> unsigned f(const unsigned char *input)
> {
>   unsigned crc = ~0;
>   asm("crc32b (%[in]), %[crc]" : "+c"(crc) : [crc] "c"(crc), [in] "r"(input));
>   return ~crc;
> }
> ```
> 
> Any clang built with assertions enabled will crash on this example.

So the question is 
does clang work well with assertions turned off？is that right？

**Comment by JimWen** [comment]
@alexey-milovidov could you check the clang in CI？

**Comment by DimitryAndric** [comment]
> So the question is does clang work well with assertions turned off？is that right?

It will:
* likely work faster since less things are checked
* never give an assertion failure like the above, since they're compiled out
* possibly produce incorrect output in case of a real bug, or maybe even segfault

That said, my suspicion is that your original assertion failure is caused by inline assembler constraints, similar to the ones reported in llvm/llvm-project#40330. If you must work around the assertion failures, you can either use a clang binary without assertions (with a small risk of getting bad output), change the constraints so they no longer trigger the asssertions, or disable the inline assembly altogether.

**Comment by JimWen** [comment]
solution just for the same question (ref here https://github.com/llvm/llvm-project/issues/40330)
just turn off this assert when compile clang
