### ISSUE TITLE
zookeeper session expired and all the table read only

### ISSUE THREAD

**Issue by 825644691** [ClickHouse/ClickHouse#36343]
**clickhouse version :21.12.4.1**
** I am use clickhouse-keeper**

**err log**
**1. Operation timeout**

2022.04.16 22:33:09.111091 [ 5508 ] {} <Error> ZooKeeperClient: Code: 999. Coordination::Exception: Operation timeout (no response) for request Remove for path: /clickhouse/tables/9/osp_local_proxy_ts2hour_local_7/replicas/1/queue/queue-0001508432 (Operation timeout). (KEEPER_EXCEPTION), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa21a61a in /apps/svr/clickhouse21124/usr/bin/clickhouse-server
1. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error, int) @ 0x143c30d5 in /apps/svr/clickhouse21124/usr/bin/clickhouse-server
2. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error) @ 0x143c3416 in /apps/svr/clickhouse21124/usr/bin/clickhouse-server
3. Coordination::ZooKeeper::receiveThread() @ 0x14407c4a in /apps/svr/clickhouse21124/usr/bin/clickhouse-server
4. ? @ 0x1440df90 in /apps/svr/clickhouse21124/usr/bin/clickhouse-server
5. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa25b3b7 in /apps/svr/clickhouse21124/usr/bin/clickhouse-server
6. ? @ 0xa25edbd in /apps/svr/clickhouse21124/usr/bin/clickhouse-server
7. start_thread @ 0x7dc5 in /usr/lib64/libpthread-2.17.so
8. clone @ 0xf773d in /usr/lib64/libc-2.17.so
 (version 21.12.4.1 (official build))
2022.04.16 22:33:09.111799 [ 5252 ] {} <Error> MergeFromLogEntryTask: virtual bool DB::ReplicatedMergeMutateTaskBase::executeStep(): Code: 999. Coordination::Exception: Connection loss, path: /clickhouse/tables/9/osp_local_proxy_ts2hour_local_7/replicas. (KEEPER_EXCEPTION), Stack trace (when copying this message, always include the lines below):

**2.Connection loss**
2022.04.16 22:33:09.111828 [ 5314 ] {} <Error> accesslog.osp_local_proxy_ts2hour_local_7 (7b972d06-aea7-47ae-bb97-2d06aea737ae): auto DB::StorageReplicatedMergeTree::processQueueEntry(ReplicatedMergeTreeQueue::SelectedEntryPtr)::(anonymous class)::operator()(DB::StorageReplicatedMergeTree::LogEntryPtr &) const: Code: 999. Coordination::Exception: Connection loss, path: /clickhouse/tables/9/osp_local_proxy_ts2hour_local_7/replicas/1/parts/eab10be823ea978141fc827bb52f4b27_2439_2439_0. (KEEPER_EXCEPTION), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa21a61a in /apps/svr/clickhouse21124/usr/bin/clickhouse-server
1. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error, int) @ 0x143c30d5 in /apps/svr/clickhouse21124/usr/bin/clickhouse-server
2. Coordination::Exception::Exception(Coordination::Error, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x143c38e8 in /apps/svr/clickhouse21124/usr/bin/clickhouse-server
3. zkutil::ZooKeeper::existsWatch(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Stat*, std::__1::function<void (Coordination::WatchResponse const&)>) @ 0x143cd4f3 in /apps/svr/clickhouse21124/usr/bin/clickhouse-server
4. zkutil::ZooKeeper::exists(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Stat*, std::__1::shared_ptr<Poco::Event> const&) @ 0x143cd395 in /apps/svr/clickhouse21124/usr/bin/clickhouse-server
5. DB::StorageReplicatedMergeTree::executeLogEntry(DB::ReplicatedMergeTreeLogEntry&) @ 0x1378c97d in /apps/svr/clickhouse21124/usr/bin/clickhouse-server
6. ? @ 0x1384c57f in /apps/svr/clickhouse21124/usr/bin/clickhouse-server
7. DB::ReplicatedMergeTreeQueue::processEntry(std::__1::function<std::__1::shared_ptr<zkutil::ZooKeeper> ()>, std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&, std::__1::function<bool (std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&)>) @ 0x13c5a405 in /apps
/svr/clickhouse21124/usr/bin/clickhouse-server
8. DB::StorageReplicatedMergeTree::processQueueEntry(std::__1::shared_ptr<DB::ReplicatedMergeTreeQueue::SelectedEntry>) @ 0x137ced33 in /apps/svr/clickhouse21124/usr/bin/clickhouse-server
9. DB::ExecutableLambdaAdapter::executeStep() @ 0x1384ce71 in /apps/svr/clickhouse21124/usr/bin/clickhouse-server
10. DB::MergeTreeBackgroundExecutor<DB::OrdinaryRuntimeQueue>::routine(std::__1::shared_ptr<DB::TaskRuntimeData>) @ 0xa1f47fa in /apps/svr/clickhouse21124/usr/bin/clickhouse-server
11. DB::MergeTreeBackgroundExecutor<DB::OrdinaryRuntimeQueue>::threadFunction() @ 0xa1f46b5 in /apps/svr/clickhouse21124/usr/bin/clickhouse-server
12. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0xa25dfaa in /apps/svr/clickhouse21124/usr/bin/clickhouse-server
13. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1
::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()&&...)::'lambda'()::operator()() @ 0xa25fdc4 in /apps/svr/clickhouse21124/usr/bin/clickhouse-server
14. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa25b3b7 in /apps/svr/clickhouse21124/usr/bin/clickhouse-server
15. ? @ 0xa25edbd in /apps/svr/clickhouse21124/usr/bin/clickhouse-server
16. start_thread @ 0x7dc5 in /usr/lib64/libpthread-2.17.so
17. clone @ 0xf773d in /usr/lib64/libc-2.17.so
 (version 21.12.4.1 (official build))

**3. session expire**
2022.04.16 22:33:09.112507 [ 5406 ] {} <Error> accesslog.nginx_default_local (933e463d-24bb-4e22-933e-463d24bbae22): void DB::StorageReplicatedMergeTree::queueUpdatingTask(): Code: 999. Coordination::Exception: Session expired (Session expired). (KEEPER_EXCEPTION), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa21a61a in /apps/svr/clickhouse21124/usr/bin/clickhouse-server
1. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error, int) @ 0x143c30d5 in /apps/svr/clickhouse21124/usr/bin/clickhouse-server
2. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error) @ 0x143c3416 in /apps/svr/clickhouse21124/usr/bin/clickhouse-server
3. Coordination::ZooKeeper::pushRequest(Coordination::ZooKeeper::RequestInfo&&) @ 0x14409899 in /apps/svr/clickhouse21124/usr/bin/clickhouse-server
4. Coordination::ZooKeeper::get(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<void (Coordination::GetResponse const&)>, std::__1::function<void (Coordination::WatchResponse const&)>) @ 0x1440adce in /app
s/svr/clickhouse21124/usr/bin/clickhouse-server
5. zkutil::ZooKeeper::asyncTryGetNoThrow(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<void (Coordination::WatchResponse const&)>) @ 0x143cdb93 in /apps/svr/clickhouse21124/usr/bin/clickhouse-server
6. zkutil::ZooKeeper::getImpl(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, Coordination::Stat*, std::__1::function<void (Coordination
::WatchResponse const&)>) @ 0x143cd5a0 in /apps/svr/clickhouse21124/usr/bin/clickhouse-server
7. zkutil::ZooKeeper::tryGetWatch(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, Coordination::Stat*, std::__1::function<void (Coordina
tion::WatchResponse const&)>, Coordination::Error*) @ 0x143ce37c in /apps/svr/clickhouse21124/usr/bin/clickhouse-server
8. zkutil::ZooKeeper::tryGet(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, Coordination::Stat*, std::__1::shared_ptr<Poco::Event> cons
t&, Coordination::Error*) @ 0x143ce087 in /apps/svr/clickhouse21124/usr/bin/clickhouse-server
9. zkutil::ZooKeeper::get(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Stat*, std::__1::shared_ptr<Poco::Event> const&) @ 0x143cde3a in /apps/svr/clickhouse21124/usr/bin/clickhouse-server
10. DB::ReplicatedMergeTreeQueue::pullLogsToQueue(std::__1::shared_ptr<zkutil::ZooKeeper>, std::__1::function<void (Coordination::WatchResponse const&)>, DB::ReplicatedMergeTreeQueue::PullLogsReason) @ 0x13c45262 in /apps/svr/clickhouse21124/usr/bin/clickhouse-server
11. DB::StorageReplicatedMergeTree::queueUpdatingTask() @ 0x137cdb2d in /apps/svr/clickhouse21124/usr/bin/clickhouse-server
12. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x12b0e5ee in /apps/svr/clickhouse21124/usr/bin/clickhouse-server
13. DB::BackgroundSchedulePool::threadFunction() @ 0x12b10f87 in /apps/svr/clickhouse21124/usr/bin/clickhouse-server
14. ? @ 0x12b11ff0 in /apps/svr/clickhouse21124/usr/bin/clickhouse-server
15. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa25b3b7 in /apps/svr/clickhouse21124/usr/bin/clickhouse-server
16. ? @ 0xa25edbd in /apps/svr/clickhouse21124/usr/bin/clickhouse-server
17. start_thread @ 0x7dc5 in /usr/lib64/libpthread-2.17.so
18. clone @ 0xf773d in /usr/lib64/libc-2.17.so
 (version 21.12.4.1 (official build))

**4. switch to new session**
<Warning> accesslog.`.inner_id.1f9f64a1-653f-4a83-9f9f-64a1653f3a83` (ReplicatedMergeTreeRestartingThread): ZooKeeper session has expired. Switching to a new session.

**5.  table readonly**
2022.04.16 22:33:12.083049 [ 10052 ] {55acea09-cb21-4304-8fa2-a17309539e74} <Error> executeQuery: Code: 242. DB::Exception: Table is in readonly mode (zookeeper path: /clickhouse/tables/9/osp_local_proxy_1m_local). (TABLE_IS_READ_ONLY) (version 21.12.4.1 (official build)) (from 10.151.213.10:40540) (in query: INSERT INTO accesslog.osp_local_proxy_ts2hour_local_7(topic,timestamp,domain,host,ip,thread,result,traceId,CSeq,PSeq,clientIp,proxyIp1,proxyIp2,serverIp,service,method,version,errorGroup,returnCode,requestSize,responseSize,t1,t2,t3,t4,t5,t6,raw) FORMAT TabSeparated ), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa21a61a in /apps/svr/clickhouse21124/usr/bin/clickhouse-server
1. DB::Exception::Exception<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xa2878c3 in /apps/svr/clickhouse21124/usr/bin/clickhouse-server
2. DB::StorageReplicatedMergeTree::assertNotReadonly() const @ 0x137e38f9 in /apps/svr/clickhouse21124/usr/bin/clickhouse-server
3. DB::StorageReplicatedMergeTree::write(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::Context const>) @ 0x137e3a68 in /apps/svr/clickhouse21124/usr/bin/clickhouse-server
4. DB::buildPushingToViewsChain(std::__1::shared_ptr<DB::IStorage> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::Context const>, std::__1::shared_ptr<DB::IAST> const&, bool, DB::ThreadStatus*, std::__1::atomic<unsigned long>*, DB::Block const&) @ 0x1422a9a9 in /apps/svr/clickhouse21124/usr/bin/clickhouse-server
5. DB::InterpreterInsertQuery::buildChainImpl(std::__1::shared_ptr<DB::IStorage> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::Block const&, DB::ThreadStatus*, std::__1::atomic<unsigned long>*) @ 0x1326514b in /apps/svr/clickhouse21124/usr/bin/clickhouse-server
6. DB::buildPushingToViewsChain(std::__1::shared_ptr<DB::IStorage> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::Context const>, std::__1::shared_ptr<DB::IAST> const&, bool, DB::ThreadStatus*, std::__1::atomic<unsigned long>*, DB::Block const&) @ 0x142282b8 in /apps/svr/clickhouse21124/usr/bin/clickhouse-server
7. DB::InterpreterInsertQuery::buildChainImpl(std::__1::shared_ptr<DB::IStorage> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::Block const&, DB::ThreadStatus*, std::__1::atomic<unsigned long>*) @ 0x1326514b in /apps/svr/clickhouse21124/usr/
bin/clickhouse-server
8. DB::InterpreterInsertQuery::execute() @ 0x13267524 in /apps/svr/clickhouse21124/usr/bin/clickhouse-server
9. ? @ 0x1352a6f0 in /apps/svr/clickhouse21124/usr/bin/clickhouse-server
10. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::__1::shared_ptr<DB::Context>, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<cha
r>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>, std::__1::optional<DB::FormatSettings> c
onst&) @ 0x1352db7c in /apps/svr/clickhouse21124/usr/bin/clickhouse-server
11. DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::__1::optional<DB::CurrentThread::QueryScope>&) @ 0x13d9137a in /apps/svr/clickhouse21124/usr/bin/clickhouse-server
12. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x13d95a87 in /apps/svr/clickhouse21124/usr/bin/clickhouse-server
13. DB::HTTPServerConnection::run() @ 0x13ff981a in /apps/svr/clickhouse21124/usr/bin/clickhouse-server
14. Poco::Net::TCPServerConnection::start() @ 0x16f4152f in /apps/svr/clickhouse21124/usr/bin/clickhouse-server
15. Poco::Net::TCPServerDispatcher::run() @ 0x16f43981 in /apps/svr/clickhouse21124/usr/bin/clickhouse-server
16. Poco::PooledThread::run() @ 0x170526a9 in /apps/svr/clickhouse21124/usr/bin/clickhouse-server
17. Poco::ThreadImpl::runnableEntry(void*) @ 0x1704fda0 in /apps/svr/clickhouse21124/usr/bin/clickhouse-server
18. start_thread @ 0x7dc5 in /usr/lib64/libpthread-2.17.so
19. clone @ 0xf773d in /usr/lib64/libc-2.17.so

**how can I solve this problem ?**
**can I set the keeper timeout session_timeout_ms/operation_timeout_ms  0  (never timeout ?)**

**Comment by alexey-milovidov** [comment]
ZooKeeper session will restore automatically. No action required.

There is no way to avoid readonly state during network partitions in strong consistent system, see https://aphyr.com/posts/313-strong-consistency-models
