### ISSUE TITLE
Maybe SELECT ... FROM input(...) can work without INSERT

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#36355]
**Use case**

Validate that server is correctly reading my data and process it on server side without insertion.

**Additional context**

I end up using `INSERT INTO FUNCTION null()`, see: #36334

**Comment by azat** [comment]
I guess `file` could be used for this purpose?

```sh
$ chl -q "select * from file(stdin)" <<<foo
   ┌─c1──┐
1. │ foo │
   └─────┘
```

**Comment by alexey-milovidov** [comment]
That's true! So we can avoid complications.

**Comment by azat** [comment]
I was actually thinking about map `input` to `file` for `clickhouse-local`, but then I decided that it does not worth it.

**Comment by azat** [comment]
What can be useful is `input()` support in `clickhouse-local` - https://github.com/ClickHouse/ClickHouse/pull/61923
