### ISSUE TITLE
Choose decent codec for system.asynchronous_metric_log

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#36357]
```
play-eu :) SELECT name, type, data_compressed_bytes, data_uncompressed_bytes, data_uncompressed_bytes / data_compressed_bytes AS ratio FROM system.columns WHERE table = 'asynchronous_metric_log'

SELECT
    name,
    type,
    data_compressed_bytes,
    data_uncompressed_bytes,
    data_uncompressed_bytes / data_compressed_bytes AS ratio
FROM system.columns
WHERE table = 'asynchronous_metric_log'

Query id: 7920a1ca-2cd3-4adc-a389-aceb2d2ef117

┌─name────────────────────┬─type───────────────────┬─data_compressed_bytes─┬─data_uncompressed_bytes─┬──────────────ratio─┐
│ event_date              │ Date                   │              50191963 │             11226421168 │ 223.66969723818133 │
│ event_time              │ DateTime               │             122579348 │             22452842336 │ 183.16986264276753 │
│ event_time_microseconds │ DateTime64(6)          │             248282292 │             44905684672 │ 180.86543470446134 │
│ metric                  │ LowCardinality(String) │             486369012 │             11245322027 │ 23.120967309899257 │
│ value                   │ Float64                │            5124740586 │             44905684672 │  8.762528350152083 │
└─────────────────────────┴────────────────────────┴───────────────────────┴─────────────────────────┴────────────────────┘
```

metric and value probably should use ZSTD.

**Comment by alexey-milovidov** [comment]
Primary key should be (metric, event_date, event_time)

**Comment by alexey-milovidov** [comment]
Better get rid of `event_time_microseconds`, it costs a lot.

**Comment by alexey-milovidov** [comment]
```
CREATE TABLE asynchronous_metric_log2
(
    `event_date` Date CODEC(Delta, ZSTD),
    `event_time` DateTime CODEC(Delta, ZSTD),
    `metric` LowCardinality(String) CODEC(ZSTD),
    `value` Float64 CODEC(Gorilla, ZSTD(3))
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(event_date)
ORDER BY (metric, event_date, event_time);


SELECT
    name,
    type,
    data_compressed_bytes,
    data_uncompressed_bytes,
    data_uncompressed_bytes / data_compressed_bytes AS ratio
FROM system.columns
WHERE table = 'asynchronous_metric_log'

Query id: b52186ed-b273-4d12-bff1-162f98bf8db1

┌─name────────────────────┬─type───────────────────┬─data_compressed_bytes─┬─data_uncompressed_bytes─┬──────────────ratio─┐
│ event_date              │ Date                   │              50206100 │             11229585516 │  223.6697436367294 │
│ event_time              │ DateTime               │             122613788 │             22459171032 │  183.1700284147489 │
│ metric                  │ LowCardinality(String) │             486506605 │             11248492397 │ 23.120944878024833 │
│ value                   │ Float64                │            5126384378 │             44918342064 │   8.76218768470974 │
└─────────────────────────┴────────────────────────┴───────────────────────┴─────────────────────────┴────────────────────┘
```

**Comment by alexey-milovidov** [comment]
If we convert value to Float32 it will take 1433794957 instead of 5126384378 bytes.

**Comment by alexey-milovidov** [comment]
But Float32 cannot accomodate small changes in byte sizes for data volume.
Another option is to round value to three significant digits: then it will take just 625625696 bytes.

**Comment by alexey-milovidov** [comment]
Yes, rounding is reasonable: https://pastila.nl/?0314cd85/41e7f1c796abb8e33130dd692d76a2a6

**Comment by amosbird** [comment]
> ```
> CREATE TABLE asynchronous_metric_log2
> (
>     `event_date` Date CODEC(Delta, ZSTD),
>     `event_time` DateTime CODEC(Delta, ZSTD),
>     `metric` LowCardinality(String) CODEC(ZSTD),
>     `value` Float64 CODEC(Gorilla, ZSTD(3))
> )
> ENGINE = MergeTree
> PARTITION BY toYYYYMM(event_date)
> ORDER BY (metric, event_date, event_time);
> 
> 
> SELECT
>     name,
>     type,
>     data_compressed_bytes,
>     data_uncompressed_bytes,
>     data_uncompressed_bytes / data_compressed_bytes AS ratio
> FROM system.columns
> WHERE table = 'asynchronous_metric_log'
> 
> Query id: b52186ed-b273-4d12-bff1-162f98bf8db1
> 
> ┌─name────────────────────┬─type───────────────────┬─data_compressed_bytes─┬─data_uncompressed_bytes─┬──────────────ratio─┐
> │ event_date              │ Date                   │              50206100 │             11229585516 │  223.6697436367294 │
> │ event_time              │ DateTime               │             122613788 │             22459171032 │  183.1700284147489 │
> │ metric                  │ LowCardinality(String) │             486506605 │             11248492397 │ 23.120944878024833 │
> │ value                   │ Float64                │            5126384378 │             44918342064 │   8.76218768470974 │
> └─────────────────────────┴────────────────────────┴───────────────────────┴─────────────────────────┴────────────────────┘
> ```

It seems there is almost no improvement after adjusting column codec.
