### ISSUE TITLE
Is it possible to have different index granularity per wide column

### ISSUE THREAD

**Issue by yandd** [ClickHouse/ClickHouse#36370]
I use ClickHouse for log analysis. The `message` column is used to store the original log lines, and the `level` column is used to store the log level. Generally, the length of the `message` column is much larger than the length of the `level` column. I set the index_granularity_bytes to 320 kb, which improves the query efficiency of the message, but the query performance of the level decreases. So is it possible to have different index granularity per wide column, the `message` colmun use low index_granularity_bytes and the `level` column use index_granularity = 8192.

**Comment by genzgd** [comment]
`index_granularity`, like the names suggests, applies **only** to the granularity of the index on the column -- the ORDER BY parameter of the MergeTree engine.  It does not make sense to discuss the index_granularity of different columns.  Index granularity determines how many rows are stored in each "granule" for **all columns**.

`index_granular_bytes` limits the size of each granule, so by reducing it from the default of 10MB, you are increasing the total number of granules for your wide rows.  The only real effect of this is to make ClickHouse do more data reads, so it's unclear why it would significantly affect your query performance.

It's more likely that your query performance is affected by your ORDER BY key and your query filter/WHERE clause.  What is the ORDER BY and PARTITION BY of your table, and what do your "fast" and "slow" queries look like?  Are you using any secondary indexes?
