### ISSUE TITLE
JSONEachRow export without column name

### ISSUE THREAD

**Issue by srinikom** [ClickHouse/ClickHouse#36373]
I am planning to keep mandatory/aggr fields separate and everything under a map. When I export, I would like to export just the Map as json.

```sql
CREATE TABLE table_map (t UInt32, kvs Map(String, UInt32)) ENGINE=Memory;
INSERT INTO table_map VALUES (11, {'key1':1, 'key2':11})
INSERT INTO table_map VALUES (12, {'key1':1, 'key2':12})
INSERT INTO table_map VALUES (13, {'key1':1, 'key3': 14})

SELECT kvs FROM table_map FORMAT JSONEachRow

DROP TABLE if exists table_map;
```

```
dev-mc :) SELECT kvs FROM table_map FORMAT JSONEachRow

SELECT kvs
FROM table_map
FORMAT JSONEachRow

Query id: 7ae1cf18-132f-45e4-a85e-15571230ba29

{"kvs":{"key1":1,"key2":11}}
{"kvs":{"key1":1,"key2":12}}
{"kvs":{"key1":1,"key3":14}}

3 rows in set. Elapsed: 0.004 sec.
```

In the output, I don't need column name 'kvs' repeated every row. Is it possible to achieve? I would like to get output like below.

```
{"key1":1,"key2":11}
{"key1":1,"key2":12}
{"key1":1,"key3":14}
```

Thanks for an awesome piece of OS sw and thanks for help.

**Comment by genzgd** [comment]
This is not possible using the "JSONEachRow" output format unless you know all of possible keys in the Map, and essentially "pivot" the kvs map column.  To understand why, consider that what ClickHouse is returning is a matrix of column names and column values.  Forgetting JSON for the moment, what you want is this:

```
key1 | key2 | key3
-----------------
1     11
1     12
1            14
```

for an unknown number of keys.  Any ClickHouse output format is simply a representation of this kind of matrix, so any time you use the JSONEachRow output format, each JSON string/object will have exactly the same keys.

Of course, if you know exactly what keys are possible, you could do something like this:

```
select kvs['key1'] as key1, kvs['key2'] as key2, kvs['key3'] as key3 from table_map FORMAT JSONEachRow;

SELECT
    kvs['key1'] AS key1,
    kvs['key2'] AS key2,
    kvs['key3'] AS key3
FROM table_map
FORMAT JSONEachRow

{"key1":1,"key2":12,"key3":0}
{"key1":1,"key2":11,"key3":0}
{"key1":1,"key2":0,"key3":14}
```

but then you will have the default value (0) or null if you use a Nullable value type for each missing key in your JSON output.

Finally depending on how you plan to consume this JSON you could use a different output format and apply the toJSONString function to the kvs column:

```
SELECT toJSONString(kvs) AS kvs
FROM table_map
FORMAT TSV

{"key1":1,"key2":11}
{"key1":1,"key3":14}
{"key1":1,"key2":12}
```

**Comment by srinikom** [comment]
Thanks for the reply. 

I am looking at a similar setting like below. 
```
SET output_format_json_array_of_rows = 1;
```
Where I can change the default behavior. Implementation is checked in here: https://github.com/ClickHouse/ClickHouse/commit/8cde88440b833235c5eab2d857812815f7419210  Are you open for a PR under a flag for JSONEachRow so that it doesn't include column name as a root object. It only makes sense for map/nested objects. 

Your TSV option looks very interesting but it does introduce extra escapes for string formatting and don't get array out option like output_format_json_array_of_rows as I would need to generate a JSON out as an array.

**Comment by genzgd** [comment]
You might be able to use TabSeparatedRaw to avoid the string formatting issues, since everything should be properly escaped in the JSON string to begin with, you should be able to process just by splitting on the tab character.

Your PR idea is interesting, particularly because we probably have a related issues with new Object/jSON datatypes.  I'll reopen this as a feature request.

**Comment by alexey-milovidov** [comment]
You can format JSON inside the query, and then use the output format that will output it as is:

```
CREATE TABLE table_map (t UInt32, kvs Map(String, UInt32)) ENGINE=Memory;
INSERT INTO table_map VALUES (11, {'key1':1, 'key2':11});
INSERT INTO table_map VALUES (12, {'key1':1, 'key2':12});
INSERT INTO table_map VALUES (13, {'key1':1, 'key3': 14});

SELECT toJSONString(kvs) FROM table_map FORMAT LineAsString;
```

```
{"key1":1,"key2":12}
{"key1":1,"key2":11}
{"key1":1,"key3":14}
```
