### ISSUE TITLE
Inconsistent behavior with mysql: order by collate 'zh'

### ISSUE THREAD

**Issue by cantfu** [ClickHouse/ClickHouse#36383]
Why there is a inconsistent behavior with MYSQL when i using order by collate 'zh'?
If there is  both Chinese and English characters, then i use order by collate 'zh', it will show Chinese first. But the correct behavior is  show English first?
**Is it a bug or there is other solution to show English first?**

version: 22.3.2.1
reproduce in **clickhouse**:

1. create table
```sql
CREATE TABLE default.`test_orderby_locale` (
`num` Int32,
`str` Nullable(String)
) ENGINE = MergeTree() PARTITION BY num
ORDER BY
num SETTINGS index_granularity = 8192;
```

2. insert values
```sql
insert into default."test_orderby_locale" values(1, 'aaa'),(2, 'aaabb'),(3, 'bb'),(4, '李四（L）'),(5, '王五（W）'),(6, '张三（Z）');
```

3. select order by with collate 'zh'
```shell
ck130 :) select * from default."test_orderby_locale" order by str asc COLLATE 'zh';

SELECT *
FROM default.test_orderby_locale
ORDER BY str ASC COLLATE 'zh'

Query id: 8e2395bb-638d-4f9a-af11-3c25c420bacb

┌─num─┬─str───────┐
│   4 │ 李四（L） │
│   5 │ 王五（W） │
│   6 │ 张三（Z） │
│   1 │ aaa       │
│   2 │ aaabb     │
└─────┴───────────┘
┌─num─┬─str─┐
│   3 │ bb  │
└─────┴─────┘

6 rows in set. Elapsed: 0.004 sec.
```

We can see the Chinese is displayed first.
But if we use following sql in **MYSQL**, it will show the result what is I expect.

```sql
SELECT num, str FROM testdb.test_orderby_locale order by convert(str USING GBK);
```

the result is:

```shell
1	aaa
2	aaabb
3	bb
4	李四（L）
5	王五（W）
6	张三（Z）
```
 
Btw, **jdk behavior** also will get following result which show english first?

java code:
```java
@Test
 void test_orderby_locale() {
    String[] arr = new String[] {"aa", "aaabb", "bb", "李四（L）", "王五（W）", "张三（Z）"};
    Collator instance = Collator.getInstance(Locale.ENGLISH);
    Arrays.sort(arr, instance);
    System.out.println(Arrays.toString(arr));
 }
```

result:
```shell
[aa, aaabb, bb, 李四（L）, 王五（W）, 张三（Z）]
```

**Comment by e-mars** [comment]
hi @cantfu.
I think this is bug but at minimum an enhancement request.  
added potential bug label.

**Comment by cantfu** [comment]
@e-mars Ok thanks.
So, Is there no other temporary solution? Will you fix it in next release?

**Comment by alexey-milovidov** [comment]
@e-mars First we need to check, what is the expected behavior.
We are using unicode collation algorithm implemented in ICU library.
Compatibility with MySQL or JDK should not be expected.
