### ISSUE TITLE
22.4 Release Checklist

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#36395]
Please list here all the issues that must be fixed before the next release.
Release is scheduled for mid-April.

Stabilize CI:
- [x] #36363
- [x] #36361
- [x] #36358
- [x] #36337

Blocker issues:
- [ ] #36416

**Comment by alexey-milovidov** [comment]
Changelog is being prepared here: #36397

**Comment by alexey-milovidov** [comment]
Major issue has been found: https://github.com/ClickHouse/ClickHouse/issues/36416

**Comment by alesapin** [comment]
Important to merge in the release: https://github.com/ClickHouse/ClickHouse/pull/36198/
And this: https://github.com/ClickHouse/ClickHouse/pull/36299

**Comment by alexey-milovidov** [comment]
"Zero-copy replication" is not for production, and their users will be happy to download the build from master.

**Comment by alexey-milovidov** [comment]
@zhaojintaozhao 

It is entirely unusable in version 22.4.
Wrong tracking of hard links. Parts after mutation may become broken. Example: adding secondary index to a table.

In master version it is mostly ready for use.
Install master version as following:
```
curl https://clickhouse.com/ | sh
```

**Comment by alexey-milovidov** [comment]
Local cache: logical errors have been found with fuzz testing.

**Comment by zhaojintaozhao** [comment]
> @zhaojintaozhao
> 
> It is entirely unusable in version 22.4. Wrong tracking of hard links. Parts after mutation may become broken. Example: adding secondary index to a table.
> 
> In master version it is mostly ready for use. Install master version as following:
> 
> ```
> curl https://clickhouse.com/ | sh
> ```
Hi, @alexey-milovidov , thank you very much for your response..
Which MR has resolved this unusable problem?  MR #36299 ?

**Comment by alexey-milovidov** [comment]
Yes, this PR.
