### ISSUE TITLE
22.3 lts,unable to update view because of dictionary dependency

### ISSUE THREAD

**Issue by IVitamin-C** [ClickHouse/ClickHouse#36392]
I have a dictionary, the data of the dictionary comes from a clickhouse view .
When I update this view, I cannot execute create or replace because the dictionary depends on the view.
So how should I update the data of this dictionary

**Comment by filimonov** [comment]
Can you show the example - both the steps you do and exceptions you get?

**Comment by IVitamin-C** [comment]
I modified the configuration to skip this restriction.
<check_table_dependencies>false</check_table_dependencies>

We will use the ClickHouse view as the data source for the dictionary.

case:
```sql
create or replace view test.test_view 
as 
select toUInt64(rand()) as key 
     , rand() as value 
from numbers(10);
CREATE DICTIONARY test.test_dict
(
    `key` UInt64,
    `value` UInt32
)
PRIMARY KEY key
SOURCE(CLICKHOUSE(HOST 'localhost' PORT 9000 USER 'default' PASSWORD '' DB 'test' TABLE 'test_view'))
LIFETIME(MIN 600 MAX 1200)
LAYOUT(HASHED());
select * from test.test_dict;

create or replace view test.test_view 
as 
select toUInt64(rand()) as key 
     , rand() as value 
from numbers(20);
DB::Exception: Cannot drop or rename test.test_view, because some tables depend on it: test.test_dict. (HAVE_DEPENDENT_OBJECTS)
```
The dictionary is used in the materialized view, so the dictionary cannot be deleted, the view is used in the dictionary, the view cannot be deleted or updated, and the calculationq query of the view cannot be modified.

**Comment by kill1549** [comment]
set check_table_dependencies = 0
