### ISSUE TITLE
Including a Data Skipping Index for a Materialized View

### ISSUE THREAD

**Issue by a-dot** [ClickHouse/ClickHouse#36403]
Hello! Is it possible to include the creation of a Data Skipping Index while creating a materialized view in a single command? I understand that I can create a target table for the materialized view and create the index there but I would like to know if it's possible to have the index create with the `CREATE MATERIALIZED VIEW...` construct. Thanks!

**Comment by genzgd** [comment]
This is not supported.  In general the TO form of Materialized Views is to be preferred in almost any use case except for the simplest test tables, so the functionality for "automatic" MVs is limited and unlikely to be enhanced.   The TO form allows all the features of a table in a transparent and maintainable way.
