### ISSUE TITLE
Virtual columns not presented in paquet file

### ISSUE THREAD

**Issue by KanaSukita** [ClickHouse/ClickHouse#36405]
Hi,

Clickhouse is a very powerful OLAP tool, thanks a lot!

I am unable to use virtual columns like '_path' and '_file' in Clickhouse with S3 engine and fileformat Parquet.
```
select _path, count(*) from default.table_parquet
```

![image](https://user-images.githubusercontent.com/32619535/163907778-b979b060-3f74-41cb-b9fe-758bcc89c0c1.png)

But when I use an another table in S3 with csv format, the virtual column _path canbe used.

**Comment by kssenii** [comment]
This was fixed in https://github.com/ClickHouse/ClickHouse/pull/35586, but not back ported to 22.3.
