### ISSUE TITLE
reasoning of the potential leakage mentioned in the comment

### ISSUE THREAD

**Issue by Jasdent** [ClickHouse/ClickHouse#36418]
Code: https://github.com/ClickHouse/ClickHouse/blob/master/src/Processors/Port.h#L121

Could anyone elaborate the situation mentioned in the comment? 
As far as I cound understand, the `expected` variable is in the local call stack that should not be visible to the outside in normal use. Does it suggest the data could corrupt after CAS (hence having exception) before the assignment?

**Comment by KochetovNicolai** [comment]
Hi!
Actually, this situation is imaginary. Technically, exceptions are not possible at this point.
You can ignore this comment, it's overpessimistic :)
