### ISSUE TITLE
DB::Exception: Limit for result exceeded, max bytes: 690.73 MiB, current bytes: 697.25 MiB.** (TOO_MANY_ROWS_OR_BYTES) 

### ISSUE THREAD

**Issue by kiwimg** [ClickHouse/ClickHouse#36421]
> You have to provide the following information whenever possible.

clickhouse version :21.11.4.14
use clickhouse-jdbc execute sql
`select id, flow_code,merger_mode from dc_clientorg_all WHERE seller_code GLOBAL IN ( 'W23431111123000' ) and partition_time = toDate('2022-02-01') and is_invalid IN ('0','2')`
dc_clientorg_all  is Distributed Table
**query result count only 110 ;**

users.xml   configuration 
`
<max_rows_to_read>1000000000</max_rows_to_read>
 <max_bytes_to_read>100000000000</max_bytes_to_read>
<max_query_size>40000000</max_query_size>
<max_rows_to_group_by>10000000</max_rows_to_group_by>
<max_rows_to_sort>1000000</max_rows_to_sort>
<max_bytes_to_sort>1000000000</max_bytes_to_sort>
<max_result_rows>7000000</max_result_rows>
<max_result_bytes>2024288000</max_result_bytes>
<max_memory_usage>25000000000</max_memory_usage>
<max_bytes_before_external_group_by>20000000000</max_bytes_before_external_group_by>
<max_partitions_per_insert_block>200</max_partitions_per_insert_block>
`
I don't know how to solve it

`
... 35 more Caused by: ru.yandex.clickhouse.except.ClickHouseUnknownException: ClickHouse exception, code: 1002, host: 192.168.2.191, port: 8123; Code: 396. **DB::Exception: Limit for result exceeded, max bytes: 953.67 MiB, current bytes: 979.08 MiB.** (TOO_MANY_ROWS_OR_BYTES) (version 21.11.4.14 (official build)) at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.getException(ClickHouseExceptionSpecifier.java:92) at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:56) at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:29) at ru.yandex.clickhouse.ClickHouseStatementImpl.checkForErrorAndThrow(ClickHouseStatementImpl.java:1099) at ru.yandex.clickhouse.ClickHouseStatementImpl.getInputStream(ClickHouseStatementImpl.java:778) at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQueryStatement(ClickHouseStatementImpl.java:272) at ru.yandex.clickhouse.ClickHousePreparedStatementImpl.execute(ClickHousePreparedStatementImpl.java:138) at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:3461) at com.alibaba.druid.filter.FilterEventAdapter.preparedStatement_execute(FilterEventAdapter.java:440) at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:3459) at com.alibaba.druid.proxy.jdbc.PreparedStatementProxyImpl.execute(PreparedStatementProxyImpl.java:167) at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:497) at org.apache.ibatis.executor.statement.PreparedStatementHandler.queryCursor(PreparedStatementHandler.java:71) at org.apache.ibatis.executor.statement.RoutingStatementHandler.queryCursor(RoutingStatementHandler.java:84) at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.doQueryCursor(MybatisSimpleExecutor.java:81) at org.apache.ibatis.executor.BaseExecutor.queryCursor(BaseExecutor.java:178) at com.baomidou.mybatisplus.core.executor.MybatisCachingExecutor.queryCursor(MybatisCachingExecutor.java:98) at jdk.internal.reflect.GeneratedMethodAccessor223.invoke(Unknown Source) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:566) at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:63) at com.sun.proxy.$Proxy184.queryCursor(Unknown Source) at org.apache.ibatis.session.defaults.DefaultSqlSession.selectCursor(DefaultSqlSession.java:123) ... 38 more Caused by: java.lang.Throwable: Code: 396. DB::Exception: Limit for result exceeded, max bytes: 690.73 MiB, current bytes: 697.25 MiB. (TOO_MANY_ROWS_OR_BYTES) (version 21.11.4.14 (official build))`

**Comment by kiwimg** [comment]
0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x9b605d4 in /usr/lib/debug/.build-id/83/32e80f7acf6de1033e1a6d9f16415c6e03dbf0.debug
1. DB::SizeLimits::check(unsigned long, unsigned long, char const*, int, int) const @ 0x122689fc in /usr/lib/debug/.build-id/83/32e80f7acf6de1033e1a6d9f16415c6e03dbf0.debug
2. DB::LimitsCheckingTransform::transform(DB::Chunk&) @ 0x132b9db7 in /usr/lib/debug/.build-id/83/32e80f7acf6de1033e1a6d9f16415c6e03dbf0.debug
3. DB::ISimpleTransform::transform(DB::Chunk&, DB::Chunk&) @ 0x1001a1f0 in /usr/lib/debug/.build-id/83/32e80f7acf6de1033e1a6d9f16415c6e03dbf0.debug
4. DB::ISimpleTransform::work() @ 0x13111ac5 in /usr/lib/debug/.build-id/83/32e80f7acf6de1033e1a6d9f16415c6e03dbf0.debug
5. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0, void ()> >(std::__1::__function::__policy_storage const*) @ 0x131301fb in /usr/lib/debug/.build-id/83/32e80f7acf6de1033e1a6d9f16415c6e03dbf0.debug
6. DB::PipelineExecutor::executeStepImpl(unsigned long, unsigned long, std::__1::atomic<bool>*) @ 0x1312c1b1 in /usr/lib/debug/.build-id/83/32e80f7acf6de1033e1a6d9f16415c6e03dbf0.debug
7. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PipelineExecutor::executeImpl(unsigned long)::$_4>(DB::PipelineExecutor::executeImpl(unsigned long)::$_4&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) @ 0x13132185 in /usr/lib/debug/.build-id/83/32e80f7acf6de1033e1a6d9f16415c6e03dbf0.debug
8. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x9ba2697 in /usr/lib/debug/.build-id/83/32e80f7acf6de1033e1a6d9f16415c6e03dbf0.debug
9. void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) @ 0x9ba609d in /usr/lib/debug/.build-id/83/32e80f7acf6de1033e1a6d9f16415c6e03dbf0.debug
10. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
11. clone @ 0xfe8dd in /usr/lib64/libc-2.17.so

2022.04.19 22:13:53.679438 [ 1965 ] {21d2d420-61aa-4def-8d74-bd2c3bb829c3} <Error> TCPHandler: Code: 396. DB::Exception: Limit for result exceeded, max bytes: 953.67 MiB, current bytes: 979.08 MiB. (TOO_MANY_ROWS_OR_BYTES), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x9b605d4 in /usr/lib/debug/.build-id/83/32e80f7acf6de1033e1a6d9f16415c6e03dbf0.debug
1. DB::SizeLimits::check(unsigned long, unsigned long, char const*, int, int) const @ 0x122689fc in /usr/lib/debug/.build-id/83/32e80f7acf6de1033e1a6d9f16415c6e03dbf0.debug
2. DB::LimitsCheckingTransform::transform(DB::Chunk&) @ 0x132b9db7 in /usr/lib/debug/.build-id/83/32e80f7acf6de1033e1a6d9f16415c6e03dbf0.debug
3. DB::ISimpleTransform::transform(DB::Chunk&, DB::Chunk&) @ 0x1001a1f0 in /usr/lib/debug/.build-id/83/32e80f7acf6de1033e1a6d9f16415c6e03dbf0.debug
4. DB::ISimpleTransform::work() @ 0x13111ac5 in /usr/lib/debug/.build-id/83/32e80f7acf6de1033e1a6d9f16415c6e03dbf0.debug
5. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0, void ()> >(std::__1::__function::__policy_storage const*) @ 0x131301fb in /usr/lib/debug/.build-id/83/32e80f7acf6de1033e1a6d9f16415c6e03dbf0.debug
6. DB::PipelineExecutor::executeStepImpl(unsigned long, unsigned long, std::__1::atomic<bool>*) @ 0x1312c1b1 in /usr/lib/debug/.build-id/83/32e80f7acf6de1033e1a6d9f16415c6e03dbf0.debug
7. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PipelineExecutor::executeImpl(unsigned long)::$_4>(DB::PipelineExecutor::executeImpl(unsigned long)::$_4&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) @ 0x13132185 in /usr/lib/debug/.build-id/83/32e80f7acf6de1033e1a6d9f16415c6e03dbf0.debug
8. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x9ba2697 in /usr/lib/debug/.build-id/83/32e80f7acf6de1033e1a6d9f16415c6e03dbf0.debug
9. void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) @ 0x9ba609d in /usr/lib/debug/.build-id/83/32e80f7acf6de1033e1a6d9f16415c6e03dbf0.debug
10. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
11. clone @ 0xfe8dd in /usr/lib64/libc-2.17.so

**Comment by tavplubix** [comment]
Probably related to #29895

**Comment by kiwimg** [comment]
query result count only 110 ;   why  **DB::Exception: Limit for result exceeded, max bytes: 953.67 MiB, current bytes: 979.08 MiB.** (TOO_MANY_ROWS_OR_BYTES) (version 21.11.4.14 (official build)) at？

**Comment by alexey-milovidov** [comment]
Duplicate.
