### ISSUE TITLE
Allow specifying LowCardinality settings per column

### ISSUE THREAD

**Issue by stas-sl** [ClickHouse/ClickHouse#36428]
Hi, with help in ClickHouse chat (thanks @UnamedRus), I understood that in order LowCardinality settings (like e.g. `low_cardinality_max_dictionary_size`) to have effect you need to specify it for default user in config file and restart the server, which means that the same dictionary size will be applied to all tables/columns on the whole server. 

But in reality it seems more logical to be able to tune this settings per column like codecs/compression to optimize storage depending on specific data stored in each particular column. I'm not sure about exact syntax, maybe it could be something like this:

```sql
CREATE TABLE t (
  user_name LowCardinality(String) SETTINGS low_cardinality_max_dictionary_size = 100000 
) ENGINE = MergeTree ...;
```
And if not specified, it could fallback to the default value from the server config.

**Comment by alexey-milovidov** [comment]
I don't recommend to change `low_cardinality_max_dictionary_size` at all. It is a fine tune setting, mostly for developers.
It's not our intention that users have to change this setting. I'd prefer to not allow to change it on column level.

**Comment by stas-sl** [comment]
Well, today I run some benchmarks to find out that it is probably not very good idea to have more than 8192 different values in LowCardinality column at all. While with < 8192 values it works really well, being quite close to Int32 column, but after that, even if you increase cardinality not that much - up to 10K, you'll get rather significant performance degradation. It could be still a bit better than a plain String, but only by a small margin. And by reaching 100K with dictionary size 8192, it definitely performs worse than a String.

Increasing dictionary size seems like helps sometimes. Especially it is visible in disk usage: even with 1M unique values, if you have large enough dictionary to fit them all, you'll get up to 8x space savings. Though with CPU and RAM the effect is not as pronounced. While it might be a bit faster with cardinality 100K, if you increase dictionary size up to 100K at expense of a bit more RAM usage, but for cardinality 1M any dictionary size works slower than plain Strings.

Test details:
- Ubuntu 20.04
- 4GB RAM
- 2 CPU
- ClickHouse 22.4.2.1
- 10M rows, 100 bytes each, single partition
- max_insert_block_size=min_insert_block_size_rows=10M, max_threads=1, low_cardinality_use_single_dictionary_for_part=0, low_cardinality_max_dictionary_size=8192/10K/100K/1M
- all values distributed uniformly

Here are the results:
<img width="984" alt="image" src="https://user-images.githubusercontent.com/4602302/164995224-198221e4-9d45-460d-9e2e-a41cb563acf4.png">

And also for convenience relative numbers (all values divided by corresponding numbers of plain String):
<img width="1118" alt="image" src="https://user-images.githubusercontent.com/4602302/164995245-29959cd0-c04f-44f1-bd54-de449ae599b9.png">

I was just confused by same articles, stating that it might work with millions of unique values.

From https://www.instana.com/blog/reducing-clickhouse-storage-cost-with-the-low-cardinality-type-lessons-from-an-instana-engineer/

> And according to our tests, it still performs better and is faster even when the column contains millions of different values.

From https://altinity.com/blog/2019/3/27/low-cardinality

> There is no hard limit in ClickHouse, the results are usually good if number of distinct values is below 10M. For big tables with many partitions and parts, the total number of distinct values can even be higher, if 10M limit is preserved at part level.

Though official documentation seems to be closer to the results I got:
> The efficiency of using LowCardinality data type depends on data diversity. If a dictionary contains less than 10,000 distinct values, then ClickHouse mostly shows higher efficiency of data reading and storing. If a dictionary contains more than 100,000 distinct values, then ClickHouse can perform worse in comparison with using ordinary data types.

So, I'll probably will either store all high cardinality strings as is, or will put them into another table.

From this, I indeed see less value in modifying this setting at all, and probably the issue could be closed.

**Comment by UnamedRus** [comment]
Outstanding research. 

How big is your l2/l3 cache? Btw

**Comment by UnamedRus** [comment]
I think, it make sense to test numbers like:
254,255,256 
65534,65535,65536

Because, LC being encoded by UInt8/UInt16 dict keys, so you should notice big performance changes when ClickHouse will change data type.

**Comment by filimonov** [comment]
Data distribution / locality can impact the behavior of LC quite drastically. 

The main gain of using LC is visible when you have a lot of repeating values. For example, if there is something like a normal distribution, and there is some limited subset of heavy-hitters - LC usually shows good results (even if there is a 'long tail' with millions of keys).

With uniform random distribution (like in your test) LC works well only if the cardinality of the set is low.

That means - using LC for all kind of 'unique' or 'close to unique' row ids don't have sense.

**Comment by stas-sl** [comment]
@UnamedRus, @filimonov thanks for the clarifications! Now my understanding of LowCardinality type improved. It evolved from "it is just a single big dictionary that maps string to int, each string is stored once, and it should work as fast as ints, as long as it fits into the memory" to "there could be multiple dictionaries, and performance highly depends not only on plain cardinality, but on data distribution, locality and order". So if you're going beyond 8192 distinct values, just cardinality numbers don't mean much, but you need to know other details. It could work slow with just 10K values distributed uniformly, or it could work fast with 1M unique values with default dictionary size, if those values are somehow grouped into clusters with low number of unique values inside each of them. Maybe it worth to add this to the documentation, as it seems to be quite an important detail, and I've seen also other people asking similar question.

@UnamedRus, as for cache sizes, I'm not sure how much it could affect performance, but looks like there is no L3 cache, I used just quite basic DigitalOcean server for 20$.
```
L1d cache:                       64 KiB
L1i cache:                       64 KiB
L2 cache:                        8 MiB
```

> I think, it make sense to test numbers like:
254,255,256
65534,65535,65536

I run a few tests, it indeed matters, and often memory/disk space doubles when going from 250 to 260 or 65000 to 66000 values, which is quite expected, but sometimes not. Though it seems not affecting CPU time that much. I believe that not fitting into a single dictionary is a more important factor, which affects performance quite a lot, but with integers ClickHouse works fast anyway whether it Int8 or Int16 or Int32.

> using LC for all kind of 'unique' or 'close to unique' row ids don't have sense.

Yes, now I understand it, though there could be cases when you have millions of distinct values, and each of them repeats 10-100 times, but it is not always possible to place them together. It is quite tempting to store them once, especially if they could be quite long, to save 10x-100x space. But turns out that naively increasing dictionary size, especially >100K doesn't work that great.

**Comment by UnamedRus** [comment]
> ZSTD codec

BTW, it doesn't make a lot of sense to use ZSTD encoding for LowCardinality(String) values, it can slowdown query execution quite a bit.

**Comment by stas-sl** [comment]
Well, I used default minimal ZSTD(1) compression level, which seems to be only slightly slower than LZ4, and doesn't change the overall picture.

<img width="1021" alt="image" src="https://user-images.githubusercontent.com/4602302/165568005-eda328e5-f0f3-4491-834c-7153eaaf8fa9.png">

I think one might benefit sometimes from ZSTD even with LowCardinality, if you have multiple dictionaries with the same values, or if there are similar values in one dictionary, as I believe compression is also used for dictionaries.

**Comment by srikanthccv** [comment]
> Data distribution / locality can impact the behavior of LC quite drastically.
> 
> The main gain of using LC is visible when you have a lot of repeating values. For example, if there is something like a normal distribution, and there is some limited subset of heavy-hitters - LC usually shows good results (even if there is a 'long tail' with millions of keys).
> 
> With uniform random distribution (like in your test) LC works well only if the cardinality of the set is low.
> 
> That means - using LC for all kind of 'unique' or 'close to unique' row ids don't have sense.

@filimonov I have a dataset that will contain more unique values (> 100k & ~ a few million) in total but the data is ordered in such a way that each granule will have few distinct values. Can I expect it to perform better in this case? How does ClickHouse work in this? Is there any heuristic approach it relies on to maintain dictionaries such as one for X granules or rows?

**Comment by UnamedRus** [comment]
>  Can I expect it to perform better in this case? 

If you talk about LowCardinality, then yes.
