### ISSUE TITLE
Providing some aarch64 binaries and images

### ISSUE THREAD

**Issue by n0vad3v** [ClickHouse/ClickHouse#36443]
I've seen issues as like https://github.com/ClickHouse/ClickHouse/issues/25030 requesting for versions of ClickHouse binary on Aarch64, and found a reply with:

```
There are plans for that, but help is needed:

we need to debug several crash reports on aarch64
we need to ensure that base functionality works properly on aarch64 and unsupported things are properly turned off.
build some CI for that.
test clickhouse on aarch64 with some production use-cases and create good bug reports / fix those bugs
```

Recently I've build several versions of ClickHouse Multi-Arch Images on releases from v22.2.3.5-stable ~ v21.8.x and done several (stress) tests on several machines(with different architects(ARM64/AMD64)).

> My original plan is to build ARM64 image for my own personal use, since I've created those images, I started to do testing on them. I've written a post on it https://nova.moe/performance-comparison-clickhouse/ (In Chinese)

![](https://user-images.githubusercontent.com/24852034/164153604-110d8c5b-2f46-42b4-9413-ab687488d298.png)

* Those Multi-Arch Images can be found on https://hub.docker.com/r/knatnetwork/clickhouse-server
* Binaries can be downloaded at: https://clickhouse.knat.network/
* Benchmark results at: https://clickperf.knat.network/

My personal plan in the future are:

* Keep building Multi-Arch Images and Binaries when newer version of ClickHouse releases 
* Run daily builds(along with benchmarks) (maybe)

Not sure if this does some help on this topic. 😂

**Comment by n0vad3v** [comment]
I think this issue can be labelled in `label:comp-aarch64` and `label:build`. 🤔

**Comment by Felixoid** [comment]
Hello @n0vad3v, I guess you're interested in the current arm64/aarch64 state

- The binaries and packages (deb, rpm, apk, tgz) are built for each commit via CI, see `ClickHouse build check (actions)` commit status, e.g. https://s3.amazonaws.com/clickhouse-builds/0/57686b842226b3a65c042a341b48105f4919ec9d/clickhouse_build_check_(actions)/report.html
- The docker images `clickhouse/clickhouse-server` are built with multiarch for a couple of months, see https://hub.docker.com/r/clickhouse/clickhouse-server/tags?page=2
- Finally, the packages publishing will be done in #38580

That's it =)
