### ISSUE TITLE
'Not enough space for external aggregation' exception when consuming Kafka messsage

### ISSUE THREAD

**Issue by winter7** [ClickHouse/ClickHouse#36440]
Sometimes recently, I got exceptions when my Kafka engine table was consuming messages.
```
2022.04.18 22:59:07.675145 [ 202 ] {} <Error> void DB::StorageKafka::threadFunc(size_t): Code: 243. DB::Exception: Not enough space for external aggregation in /var/lib/clickhouse/tmp/: While executing AggregatingTransform: while pushing to view database.materialized_view_tablename. (NOT_ENOUGH_SPACE), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x9b71b54 in /usr/bin/clickhouse
1. DB::Aggregator::executeOnBlock(std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >, unsigned long, DB::AggregatedDataVariants&, std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*> >&, std::__1::vector<std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*> >, std::__1::allocator<std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*> > > >&, bool&) const @ 0x12405181 in /usr/bin/clickhouse
2. DB::AggregatingTransform::consume(DB::Chunk) @ 0x133306e0 in /usr/bin/clickhouse
3. DB::AggregatingTransform::work() @ 0x1332e056 in /usr/bin/clickhouse
4. ? @ 0x131cd6db in /usr/bin/clickhouse
5. DB::PipelineExecutor::executeStepImpl(unsigned long, unsigned long, std::__1::atomic<bool>*) @ 0x131c9691 in /usr/bin/clickhouse
6. DB::PipelineExecutor::executeStep(std::__1::atomic<bool>*) @ 0x131c7ea5 in /usr/bin/clickhouse
7. DB::PullingPipelineExecutor::pull(DB::Chunk&) @ 0x131d690b in /usr/bin/clickhouse
8. DB::PullingPipelineExecutor::pull(DB::Block&) @ 0x131d6bac in /usr/bin/clickhouse
9. DB::ExecutingInnerQueryFromViewTransform::transform(DB::Chunk&) @ 0x133b8c88 in /usr/bin/clickhouse
10. ? @ 0x1334b0e9 in /usr/bin/clickhouse
11. DB::ExceptionKeepingTransform::work() @ 0x1334abdc in /usr/bin/clickhouse
12. ? @ 0x131cd6db in /usr/bin/clickhouse
13. DB::PipelineExecutor::executeStepImpl(unsigned long, unsigned long, std::__1::atomic<bool>*) @ 0x131c9691 in /usr/bin/clickhouse
14. ? @ 0x131cf665 in /usr/bin/clickhouse
15. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x9bb3c17 in /usr/bin/clickhouse
16. ? @ 0x9bb761d in /usr/bin/clickhouse
17. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
18. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
 (version 21.11.9.1 (official build))
```
When I restart my instance, this exception won't occur anymore. But after a few days it may happen again.
**Kafka message information**
I have 30 dimension fields and 10 metric fields in my target table which is a SummingMergeTree table.
And I do summing aggregate in materialized view logic. All metrics would be operated a sum() in mv.
The throughput of topic is approximately 100k ~ 200k offsets/s, 5M ~ 10M bytes/s

**server version**
21.11.9.1

**settings**
```
max_memory_usage = 10000000000
max_bytes_before_external_group_by = 5000000000
```
**Kafka settings**
```
kafka_max_block_size = 1048576
kafka_num_consumers = 16
kafka_thread_per_consumer = 1
```
**instance information**
36cores, 72G memories. I got more than 1T free space on my disk.

Do you have any idea that would cause 'Not enough space for external aggregation' exception when consuming and aggregating Kafka messages even we have sufficient free disk in fact? 
Is it may related to some unreleased memory issue?
I thought about 16 thread * aggregating size of message might be large, but I don't think they are that large.
Now I have no idea. Please help.

**Comment by winter7** [comment]
Hi, just want to know if we are making progress on it. Please let me know if you need any more information. Thanks!

**Comment by genzgd** [comment]
Some explanation of this process is described in this issue:  https://github.com/ClickHouse/ClickHouse/issues/9241. In particular the error message you see occurs where there is not enough space on the ClickHouse temporary volume.  By default this is configured to `<tmp_path>/var/lib/clickhouse/tmp/</tmp_path>`.  Is it possible that this is mounted on a different volume than your main disk? 

What AggregateFunctions are you using in your summingMergeTree table?  Some functions take a great deal of space especially during calculation.  Also, are you running other queries at the same time as this ingest?  All queries that involve calculating large aggregate functions store intermediate results in the same shared directory.

At 5-10m bytes per second throughput, you might also consider simply keeping more free space on your data volumes.

**Comment by winter7** [comment]
Hi @genzgd , thanks for your support! I read about #9241 and #10375.
> Is it possible that this is mounted on a different volume than your main disk?

No. It located in my data volume and the volume had more than 1T free space.

> What AggregateFunctions are you using in your summingMergeTree table?

In my summingMergeTree table, I have 30 dimension fields and 10 metric fields. For those 10 metrics field I only use sum() aggregate function.

> Also, are you running other queries at the same time as this ingest? All queries that involve calculating large aggregate functions store intermediate results in the same shared directory.

I did have other running queries. Could you tell me how to calculate the tmp size that my scenario would use in sum() aggregate function? Because I thought more than 1T free space should be large enough to handle that. Could you tell me which system metric could indicate the reserved status? Or is there any settings that can optimize this kind of limitation?

**Comment by genzgd** [comment]
Summing aggregate functions don't take significant space, however 30 dimension fields in a single materialized view seems dangerously high.  If these dimension fields are not highly correlated you will have almost as many rows in this table as messages in the Kafka source, but calculating the intermediate group by results on 30 fields is going to take a lot of memory/disk space.  I'm not sure but that calculation might be even more expensive since it has to be coordinated across 16 threads.  

You should also consider your total data volume and total disk size.  That 1T of free space will also be used for intermediate results of merges, plus old parts that that are preserved for some time after merges (by default for 8 minutes), so during heavy load (with lots of small merges in progress) you may well have much less than 1TB free.  Again my gut feeling is you don't have enough spare disk space for that size of machine and data ingest rate.

**Comment by jianhanke** [comment]
I have encountered the same problem. How did you solve it? Thank you very much

**Comment by winter7** [comment]
Hi @genzgd , encountered this issue again. J
ust wondering why the disk usage (exported by datadog) seems so smooth and  free space is continuous 1T when I got this `NOT_ENOUGH_SPACE ` exception?
Is the aggregating really using the disk? Or it's kind of logical bug?

**Comment by genzgd** [comment]
The aggregation normally uses disk, but the error message means ClickHouse has calculated there is not enough room on disk to store the temporary results it needs to put there.  Again 1TB is not enough free space to run any moderately sized ClickHouse server that uses aggregating functions.

**Comment by winter7** [comment]
@genzgd , thanks for your explanation, but I wonder Shouldn't disk utilization be seen to be high when temporary storage is used by ClickHouse? The truth is I can see the free space is always around 1T. I'm a little confused.

**Comment by genzgd** [comment]
You'd have to look in to the details of your free space and correlate it with the ingest.  How much space is available in /var/lib/clickhouse-server/tmp?  How much data are you ingesting per batch that has to be aggregated by your materialized view?  What is your setting for `max_bytes_before_external_group_by`?  How much memory do you have and how much is being used during heavy inserts?

Some details about how this functionality works are here:  https://clickhouse.com/docs/en/sql-reference/statements/select/group-by#group-by-in-external-memory.  In fact if you have `max_bytes_before_external_group_by` disabled it's possible you are running out of memory rather than disk space, although I would think the error would be different.

**Comment by winter7** [comment]
I think we are getting closer here.
The `/var/lib/clickhouse` was mounted with a big disk. So the `/var/lib/clickhouse/tmp` shared the 1T free disk. Like I mentioned above in this issue, I have these settings in Kafka engine table:
```
kafka_max_block_size = 1048576
kafka_num_consumers = 16
kafka_thread_per_consumer = 1
```
So I got like 16 threads and 1M message per batch.

My EC2 memory is 72G.
And I have these settings:
```
max_memory_usage = 10000000000
max_bytes_before_external_group_by = 5000000000
```
the max_memory_usage(10G) is twice as high as max_bytes_before_external_group_by(5G).

So when my materialized view is aggregating, it would use real disk. It just doesn't make much sense that it would use 1T

**Comment by genzgd** [comment]
How big are inserted parts for your table (uncompressed) based on select  * from system.parts (where the part name ends with 0 indicating it hasn't been merged)

**Comment by winter7** [comment]
Hi @genzgd , according to `system.parts` table, compressed size for the table is about 200G, and uncompressed size is more than 2T.

**Comment by genzgd** [comment]
I meant the individual parts when you do an insert, not the entire table.  If you are inserting large parts they will take more memory to run the aggregations.

**Comment by winter7** [comment]
Get it. A single active '%_0' part is about 4MB as compressed size and 40MB as uncompressed size.

**Comment by genzgd** [comment]
That seems like it should be okay, especially if you just have sum() aggregations.  Note that if you running at full speed (16 consumers) you actually don't have enough memory to process the data entirely in memory (16 * 10GB is a lot more than 72GB).  I would try adjusting the number of consumers and the max_bytes_before_external_group_by setting, as it's possible in rare circumstances you might be running out of memory before it even tries to spool to disk.

**Comment by winter7** [comment]
Thanks @den-crane  You mean do not use aggregation logic in MaterializedView and just select raw fields? Utilize the feature of SummingMergeTree(in my case) for the background summing aggregation. That sounds reasonable. 
Is it the best practice that we don't use group-by in MaterializedView?

**Comment by den-crane** [comment]
>Is it the best practice that we don't use group-by in MaterializedView 
>when we have AggregatingMergeTree or SummingMergeTree as target?

In many cases GROUPBY has nothing to collapse/reduce in MAT.VIEW inserted block because all GROUPBY columns are unique, so it's excessive step.

In some cases you have a tradeoff: bigger insertion VS less aggregation in MAT.VIEW
