### ISSUE TITLE
Show memory usage of different clickhouse subsystems

### ISSUE THREAD

**Issue by scf37** [ClickHouse/ClickHouse#36445]
**Use case**

Clickhouse uses a lot of memory but not by queries

**Describe the solution you'd like**

List subsystems (queries, dictionaries, join engine, merges....) together with memory usage to find the culprit

**Describe alternatives you've considered**

Check potential culprits one by one hoping not to miss something

**Additional context**

Could be top_log table with columns for every subsystem or sql command to output current values.

**Comment by alexey-milovidov** [comment]
It is not possible to show memory usage by different ClickHouse subsystems, because their memory allocations are not isolated from each other.
