### ISSUE TITLE
keeper delete path command

### ISSUE THREAD

**Issue by vegastar002** [ClickHouse/ClickHouse#36446]
### env
ver 22.2.1
clickhouse keeper

### error
when I create Replicated table, report below error, yes I have a incorrect opt before 
```
Replica /clickhouse/xxx/replica1 already exists. (REPLICA_IS_ALREADY_EXIST)
```
I need  delete the path, 
what's the command like zookeeper can delete the path in clickhouse keeper ?

**Comment by tavplubix** [comment]
You don't need to remove it from [Zoo]Keeper directly, use something like
```
:) SYSTEM DROP REPLICA 'replica1' FROM ZK PATH '/clickhouse/xx'
```
https://clickhouse.com/docs/en/sql-reference/statements/system/#query_language-system-drop-replica
