### ISSUE TITLE
Mongo Engine with SRV record

### ISSUE THREAD

**Issue by raghub1** [ClickHouse/ClickHouse#36447]
Hi all,

I'm trying to connect to a mongodb server with srv record instead of direct hostname and not sure why it doesn't seem to be connecting. It says that the specified host address is not found. Can anyone help me on this please ? 

<img width="966" alt="image" src="https://user-images.githubusercontent.com/102507675/164196603-8a850d43-9632-4299-a466-7e60cd4ad50d.png">

**Comment by raghub1** [comment]
But when i connect to it with the MongoDB URI : **mongodb+srv://<user>:<pass>@<host>/<db>**, it connects fine and i'm able to query through python

**Comment by alexey-milovidov** [comment]
Most likely, we don't support SRV records for MongoDB.
Let's consider it a feature request.

**Comment by jmtt89** [comment]
Hi, is this still not supported? I can't find docs on how to connect my mongodb atlas cluster to clickhouse table using MongoDB Engine.

exist some workaround to support mongodb+srv URI?
