### ISSUE TITLE
Parquet/Arrow import date types

### ISSUE THREAD

**Issue by seca-rca** [ClickHouse/ClickHouse#36459]
Hello,

the docs regarding Parquet/Arrow import data types and the actual implementation don't match.

1) The implementation at the address below compares against DATE_LUT_MAX_EXTEND_DAY_NUM, but prints DATE_LUT_MAX_DAY_NUM in the error message.

https://github.com/ClickHouse/ClickHouse/blob/d7b88d76830e641130715b35194f350347e7caae/src/Processors/Formats/Impl/ArrowColumnToCHColumn.cpp#L167

2) The docs at https://clickhouse.com/docs/en/interfaces/formats/#data_types-matching-2 say:
Date32 (Arrow) --> Date (CH)
Date64 --> DateTime (CH)

The implemenation is different (which is good, but not documented):

Date32 --> readColumnWithDate32Data
Date64 --> readColumnWithDate64Data

https://github.com/ClickHouse/ClickHouse/blob/d7b88d76830e641130715b35194f350347e7caae/src/Processors/Formats/Impl/ArrowColumnToCHColumn.cpp#L352

**Comment by Avogar** [comment]
All issed were fixed
