### ISSUE TITLE
Clickhouse can't connect on ntopng

### ISSUE THREAD

**Issue by AnhTuanNguyenn** [ClickHouse/ClickHouse#36460]
Hello, 
i have installed clickhouse on a remote server and i connected with clickhouse via command line in file ntopng.conf 
`
-F="clickhouse;IP@9004;ntopng;default;MyPassword"`

and then i check in system i saw all alert was save in ntop service instead clickhouse service with code 
![Capture](https://user-images.githubusercontent.com/24913199/164269862-bec8a765-6aeb-4b21-8f14-ce67fe4b4322.PNG)
i see clickhouse client cant connected to port 9000 but when i try connect it manual it's work, 

```
/usr/bin/clickhouse-client --port 9000 --host "192.168.75.26" --user "default" --password "xxx" -d "ntopng"
ClickHouse client version 22.2.1.3751.
Connecting to database ntopng at 192.168.75.26:9000 as user default.
Connected to ClickHouse server version 22.1.3 revision 54455.

ClickHouse server version is older than ClickHouse client. It may indicate that the server is out of date and can be upgraded.

DATA000.xxx.fr :)
```
someone have pb same me ? 
And how can i save all log/alerts on only clickhouse server ? thanks you

**Comment by den-crane** [comment]
You ran `/usr/bin/clickhouse-client` , but the picture shows `/usr/local/bin/clickhouse-client`.
We don't support `ntopng`. Ask these questions in `ntopng` community.
