### ISSUE TITLE
关于TTL数据丢失问题

### ISSUE THREAD

**Issue by Mr-ZhangJie** [ClickHouse/ClickHouse#36478]
以下分别为2张表的DDL 数据:
```sql
CREATE TABLE tower_view_server.tm_collection_record
(
    `id` String,
    `monitor_time` DateTime,
    `fan_id` String,
    `device_number` String,
    `monitor_start_time` DateTime,
    `monitor_end_time` DateTime,
    `monitor_result` UInt8,
    `summary` String,
    `remark` String,
    `create_time` DateTime,
    `detection_time_setting` String,
    `tower_status` UInt8,
    `work_mode` UInt8,
    `device_status` UInt8,
    `monitor_equ_code` String,
    `monitor_equ_name` String,
    `ip_address` String,
    `displacement_threshold` String,
    `inclination_threshold` String,
    `always_on` UInt8,
    `led_delay_time` UInt8,
    `detection_interval_setting` String
)
ENGINE = MergeTree
ORDER BY id
TTL monitor_time + toIntervalYear(3)
SETTINGS index_granularity = 8192
```
```sql

CREATE TABLE tower_view_server.data_collection
(
    `monitor_start_time` DateTime64(3),
    `monitor_time` DateTime,
    `record_id` String,
    `device_number` String,
    `serial` UInt8,
    `dip_angle` Float64,
    `dip_angle_x` Float64,
    `dip_angle_y` Float64,
    `dip_angle2` Float64,
    `dip_angle_x2` Float64,
    `dip_angle_y2` Float64,
    `displacement` Float64,
    `displacement_x` Float64,
    `displacement_y` Float64,
    `displacement2` Float64,
    `displacement_x2` Float64,
    `displacement_y2` Float64,
    `dir_angle` Float64,
    `dir_angle_x` Float64,
    `dir_angle_y` Float64,
    `dir_angle2` Float64,
    `dir_angle_x2` Float64,
    `dir_angle_y2` Float64,
    `inspect_result` UInt8,
    `inspect_result2` UInt8,
    `image_time_points` Float64,
    `image_time_points2` Float64,
    `displacement_threshold_max` Float64,
    `displacement_threshold_min` Float64,
    `inclination_threshold_max` Float64,
    `inclination_threshold_min` Float64
)
ENGINE = MergeTree
ORDER BY monitor_start_time
TTL toDateTime(monitor_start_time) + toIntervalYear(3)
SETTINGS index_granularity = 8192
```

其中TTL 都是3年期限
但是实际数据中 data_collection 表的数据只能保存几个小时

**Comment by den-crane** [comment]
هیچ چیز روشن نیست

**Comment by Mr-ZhangJie** [comment]
> 什么都不清楚

就是说 我将数据设置为3年的保质期, 保质期一过 数据就自动删除,但是我设置后数据仅仅只有最近几个小时的数据,其他数据意外删除掉了

**Comment by Mr-ZhangJie** [comment]
> هیچ چیز روشن نیست

您可能需要翻译一下我的问题

**Comment by den-crane** [comment]
`select version()`

`select min(monitor_start_time) , max(monitor_start_time) from tower_view_server.data_collection`

**Comment by Mr-ZhangJie** [comment]
> `select version()`
>  22.2.3.1
> `select min(monitor_start_time) , max(monitor_start_time) from tower_view_server.data_collection`
2022-04-22 12:20:19.000	2022-04-22 13:29:24.800
![image](https://user-images.githubusercontent.com/42841916/164609358-4d0dfd3e-ea7f-4044-8a82-3245500e9cf4.png)


以上是运行的结果

**Comment by Mr-ZhangJie** [comment]
> 下面分别为2张表的DDL数据：
> 
> ```sql
> 创建 表 tower_view_server .tm_collection_record
> (
>     ` id`String ,
>      ` monitor_time`DateTime ,
>      ` fan_id`String ,
>      ` device_number`String ,
>      ` monitor_start_time`DateTime ,
>      ` monitor_end_time`DateTime ,
>      ` monitor_result`UInt8 ,
>      ` summary`String
>     ,
>      ` remark`String ,
>      ` create_time`DateTime , _ _ _ _ _ _ _ _ _ _ `检测时间设置`字符串
>     ，` tower_status`UInt8，
>      ` work_mode`UInt8，
>      ` device_status`UInt8，
>      ` monitor_equ_code`String，
>      ` monitor_equ_name`String，
>      ` ip_address`String，
>      ` displacement_threshold`String，
>      ` inclination_threshold`String，
>      ` always_on`UInt8，
>      ` led_delay_time` _ _ _ _ _ _ _ _ _ UInt8，
>      `检测间隔设置`字符串
> )
> ENGINE = MergeTree
>  ORDER BY id
> TTL monitor_time + toIntervalYear( 3 )
> 设置 index_granularity =  8192
> ```
> 
> ```sql
> 创建 表 tower_view_server .data_collection
> (
>     ` monitor_start_time ` DateTime64( 3 ),
>      ` monitor_time ` DateTime,
>      ` record_id ` String,
>      ` device_number ` String,
>      ` serial ` UInt8,
>      ` dip_angle ` Float64,
>      ` dip_angle_x ` Float64,
>      ` dip_angle_y ` Float64,
>      ` dip_angle2 ` Float64,
>      ` dip_angle_x2 ` Float64，
>      ` dip_angle_y2` Float64
>     ，`位移` Float64
>     ，
>      ` displacement_x`Float64 ，` displacement_y`Float64，
>      ` displacement2`Float64，
>      ` displacement_x2`Float64，
>      ` displacement_y2`Float64，
>      ` dir_angle`Float64
>     ，
>      ` dir_angle_x`Float64，
>      ` dir_angle_y`Float64 ，` dir_angle _ _ _ _ _ _ `浮点64，
>      `dir_angle_x2` float64 ，
>      ` dir_angle_y2` float64，
>      ` inspect_result`uint8
>      ，
>      ` inspect_time_points` float64，
>      ` image_time_points2` float64，
>      ` displacement_ponthold_max` float64，
>      ` displacement_threshold_min` float64
>      ，
>      ` contenting_threshold_min` float64 _ _ _ _ _ _ _ _ _ _
> )
> ENGINE = MergeTree
>  ORDER BY monitor_start_time
> TTL toDateTime(monitor_start_time) + toIntervalYear( 3 )
> 设置 index_granularity =  8192
> ```
> 
> 其中 TTL 都是 3 年有效期 的实际时间数据中 data_collection 表但只能保存几个数据

问题继续出现了

**Comment by Mr-ZhangJie** [comment]
> `select version()`
> 
> `select min(monitor_start_time) , max(monitor_start_time) from tower_view_server.data_collection`

![image](https://user-images.githubusercontent.com/42841916/164615618-0f6420d5-8e06-48c8-a8fd-2a2ce6d7c5d7.png)
Duplicate of #

**Comment by Mr-ZhangJie** [comment]
![image](https://user-images.githubusercontent.com/42841916/164615729-ae5c527e-881f-4e1d-8af1-b1e53a1d3c02.png)

**Comment by mofei920** [comment]
could you please show your test data, and how to reproduce？

**Comment by Mr-ZhangJie** [comment]
> 能否请您展示您的测试数据，以及如何重现？

数据我是真实的设备生产出来的 几乎是每5分钟25条数据 之前没有设置TTL 的时候数据不会丢失,但是设置TTL 后数据就只能会丢死

**Comment by Mr-ZhangJie** [comment]
> > 可以请您展示您的测试数据，以及怎么样？
> 
> 数据我是真实的设备生产出来的后几乎是每 5 分钟 25 条数据之前没有设置 TTL 的数据不会遗弃，设置 TTL 数据只会丢死

![image](https://user-images.githubusercontent.com/42841916/164685390-98435081-21dd-4ef0-9fee-91f986e9eb66.png)

**Comment by mofei920** [comment]
Please check the system time on your clickhouse server is correct.

**Comment by Mr-ZhangJie** [comment]
> 

是的  昨天我发现是时区的问题  感谢您的解答

**Comment by Mr-ZhangJie** [comment]
> 请检查您的 clickhouse 服务上的系统时间是否正确。

是的我发现是时区问题的感谢您的答复
