### ISSUE TITLE
Functions `YYYYMMDDToDate`, `changeYear` and similar.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#36470]
**Describe solution you'd like:**

```
YYYYMMDDToDate(num)
YYYYMMDDToDate32(num)
YYYYMMDDhhmmssToDateTime(num, [timezone])
YYYYMMDDhhmmssToDateTime64(num, [resolution], [timezone]) -- no fraction arg, it's implicitly extracted from floating point or decimal num.

-- returns the same data type as dt:
changeYear(dt, new_value)
changeMonth(dt, new_value)
changeDay(dt, new_value)

-- if argument is Date - returns DateTime, if Date32, returns DateTime64:
changeHour(dt, new_value)
changeMinute(dt, new_value)
changeSecond(dt, new_value)
```

See  #30895

**Comment by dentiscalprum** [comment]
I'd like to pick up this issue. Could you assign this task to me?
Thanks !

**Comment by dentiscalprum** [comment]
Hi, may I have a try on this?
Thank you !

**Comment by alexey-milovidov** [comment]
@dentiscalprum Yes, it will be very helpful! Thank you!

**Comment by dentiscalprum** [comment]
> YYYYMMDDhhmmssToDateTime64(num, [resolution], [timezone]) -- no fraction arg, it's implicitly extracted from floating point or decimal num.

**floating point** Which parameter is the floating point ?

Thanks !

**Comment by alexey-milovidov** [comment]
The `number` argument can be an integer, decimal, or floating point.
In the latter cases, the fractional part should be extracted and used in the DateTime64 return value.

**Comment by dentiscalprum** [comment]
> The `number` argument can be an integer, decimal, or floating point. In the latter cases, the fractional part should be extracted and used in the DateTime64 return value.

Is that only YYYYMMDDhhmmss DateTime64 supports floating point numbers or decimal num, the other three are YYYYMMDDToDate, YYYYMMDDToDate32, YYYYMMDDhhmmssToDateTime  do not support floating point numbers?

Thanks !

**Comment by alexey-milovidov** [comment]
The functions ending with ToDate, ToDate32, and ToDateTime will support floating point and decimal arguments but ignore the fractional part, because, in contrast to DateTime64, the types Date, Date32, and DateTime don't have the fractional part.

**Comment by dentiscalprum** [comment]
Extracting fraction from the decimal point will lead to inaccuracy

For example:
```cpp
int main() {
  double i = 20181222051414.55555;
  printf("%lf\n", i);
}
```

should print `20181222051414.55555`, but instead prints `20181222051414.554688`

**Comment by alexey-milovidov** [comment]
@dentiscalprum This is acceptable.

**Comment by dentiscalprum** [comment]
@alexey-milovidov #45070 
Implemented the function `YYYYMMDDToDate`, `YYYYMMDDToDate32`, `YYYYMMDDhhmmssToDateTime ` and `YYYYMMDDhhmmssToDateTime64`
Please review, thanks !!!

**Comment by alexey-milovidov** [comment]
Thank you! The first part of this task is done. The second part remains.

**Comment by alexey-milovidov** [comment]
Continued in #66194.
