### ISSUE TITLE
Users are not restricted from accessing some system tables, and sensitive information is leaked

### ISSUE THREAD

**Issue by ygrzjh** [ClickHouse/ClickHouse#36477]
Current clickhouse version: `22.3.3`

1. create not enough privileges user

```sql
create user test;
```

2. access system database.(ACCESS_DENIED)
```sql
use system;
```
```
Received exception from server (version 22.3.3):
Code: 497. DB::Exception: Received from localhost:9000. DB::Exception: test: Not enough privileges. To execute this query it's necessary to have grant SHOW DATABASES ON system.*. (ACCESS_DENIED)
```

3. access system zookeeper table (sensitive information leakage).
e.g 
- clickhouse config in zookeeper.
- Replicated database metadata.
- Replicated table metadata.
- ddl
- ...
```sql
select * from system.zookeeper where path = '/';
```
```
┌─name───────┬─value─┬─czxid─┬─mzxid─┬───────────────ctime─┬───────────────mtime─┬─version─┬─cversion─┬─aversion─┬─ephemeralOwner─┬─dataLength─┬─numChildren─┬─pzxid─┬─path─┐
│ zookeeper  │       │     0 │     0 │ 1970-01-01 00:00:00 │ 1970-01-01 00:00:00 │       0 │       -2 │        0 │              0 │          0 │           2 │     0 │ /    │
│ clickhouse │       │     3 │     3 │ 2022-04-21 07:07:51 │ 2022-04-21 07:07:51 │       0 │        3 │        0 │              0 │          0 │           3 │    16 │ /    │
└────────────┴───────┴───────┴───────┴─────────────────────┴─────────────────────┴─────────┴──────────┴──────────┴────────────────┴────────────┴─────────────┴───────┴──────┘
```

5. Other system tables with the same problem
- clusters
- macros
- disks
- errors
- events
- query_log
- metric_log
- session_log
- trace_log
- ...

**Comment by UnamedRus** [comment]
You can add row policy for such tables.

**Comment by e-mars** [comment]
Hi @ygrzjh .
yes, you can use row policy: https://clickhouse.com/docs/en/guides/sre/users-and-roles
and also if admin access for another user is needed can look at this for additional permissions:
https://github.com/ClickHouse/ClickHouse/issues/26238

thanks.

**Comment by den-crane** [comment]
https://github.com/ClickHouse/ClickHouse/issues/24887

https://github.com/ClickHouse/ClickHouse/pull/35635
