### ISSUE TITLE
Unexpected behavior during 21.8lts upgrade to 22.3 lts

### ISSUE THREAD

**Issue by IVitamin-C** [ClickHouse/ClickHouse#36471]
Hi, we are upgrading the cluster version.  I found nexpected behavior during 21.8lts upgrade to 22.3 lts.
case 1:
21.3 lts
```sql
SELECT
    _shard_num AS shard_num,
    1 - (sum(free_space) / sum(total_space)) AS rate
FROM cluster(cluster, system, disks)
WHERE name IN ('default', 'data', 'data1')
GROUP BY shard_num
ORDER BY rate ASC
```
22.3 lts
sql will be rewritten
```sql
SELECT                                                                
    shardNum() AS shard_num,                                          
    1 - (sum(free_space) / sum(total_space)) AS rate                  
FROM cluster('cluster', 'system', 'disks')                       
WHERE name IN ('default', 'data', 'data1') 
GROUP BY shard_num                                                    
ORDER BY rate ASC 
```
But during the upgrade, the cluster has both 21.8 lts and 22.3lts
The query throws an exception：
DB::Exception: Unknown function shardNum.

Some existing queries will be affected, and the upgrade process will affect user usage

case 2: 

22.3 lts .Unexpected behavior of toString Function.
```sql
SELECT toString(dummy) AS dummy
FROM cluster('cluster', 'system', 'one')
GROUP BY dummy
DB::Exception: Not found column dummy in block. There are only columns: toString(dummy): While executing Remote.
```
But in 21.8 lts , this query works fine.

thanks

**Comment by sunny19930321** [comment]
have the same problem, issue https://github.com/ClickHouse/ClickHouse/issues/36406

**Comment by benbiti** [comment]
@IVitamin-C case 2  which 22.3 minor version affect?
It works version 22.3.4.44。

**Comment by IVitamin-C** [comment]
> @IVitamin-C case 2 which 22.3 minor version affect? It works version 22.3.4.44。
version is 22.3.4.44.

**Comment by sunny19930321** [comment]
> 

I test 22.3.4.44,  its not work
