### ISSUE TITLE
Documentation: Impossible to use search with other languages.

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#36503]
Two issues, kinda.

1. When you switch a language, it redirects you to the main page (in the old documentation you stayed in the same article).
2. Search always returns results with links to EN site it does not matter which language is current.

Select Russian. Search for quantileExact, you will get EN link 
`https://clickhouse.com/docs/en/sql-reference/aggregate-functions/reference/quantileexact#quantileexact` 

then switch language to Russian you will get `https://clickhouse.com/docs/ru`.

Desired link is `https://clickhouse.com/docs/ru/sql-reference/aggregate-functions/reference/quantileexact#quantileexact`

**Comment by rfraposa** [comment]
Thanks Denny. The search is temporarily using Lunr until we get Algolia up and running again with the new docs. That should resolve the search issue.

In terms of switching languages, I realize it is not idea, but when the searching is switched to Algolia then hopefully this will be less of an issue.

**Comment by rfraposa** [comment]
FWIW: switching to Algolia did not immediately provide any nice solution for multi-language search. More research and configuration will need to be done.

**Comment by alexey-milovidov** [comment]
@rfraposa most likely forgot about this issue.
But the fact is - we don't support any language other than English at all.

**Comment by rfraposa** [comment]
Yes - I did forget actually. 😬  I don't know how to get the language search to work easily, and it's such a low priority I'm not sure when this task will get completed. However, if we do add another language someday (like French or Japanese for example) then we will probably invest our efforts into getting search to work for multiple languages.

**Comment by DanRoscigno** [comment]
unplanned
