### ISSUE TITLE
quantile & NaN & Inf

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#36522]
```sql
select quantiles(0.5)(inf) FROM numbers(5)     --- 5 times inf --> nan
┌─quantiles(0.5)(inf)─┐
│ [nan]               │
└─────────────────────┘

select quantiles(0.5)(inf) FROM numbers(300)   --- 300 times inf --> inf
┌─quantiles(0.5)(inf)─┐
│ [inf]               │
└─────────────────────┘


select quantiles(0.5)(arrayJoin([inf, 0, -inf]))
┌─quantiles(0.5)(arrayJoin([inf, 0, -inf]))─┐
│ [nan]                                     │
└───────────────────────────────────────────┘

select quantiles(0.5)(arrayJoin([inf, inf, 0, -inf, -inf, -0]))
┌─quantiles(0.5)(arrayJoin([inf, inf, 0, -inf, -inf, 0]))─┐
│ [0]                                                     │
└─────────────────────────────────────────────────────────┘

select median(x) from (select arrayJoin([1.0, inf]) x);
┌─median(x)─┐
│       inf │
└───────────┘
```

I have no idea what is correct behavior here 

https://www.wolframalpha.com/input?i2d=true&i=median%5C%2840%291%5C%2844%29++inf%5C%2841%29
`median(1, inf) -> (undefined)`

May be all quantile computations should end-up with `nan` result if `nan` or `inf` participated.

related to quantilesTDigest state de-serialize issue https://github.com/ClickHouse/ClickHouse/issues/32107

**Comment by den-crane** [comment]
```sql
SELECT medianMerge(x)
FROM
(
    SELECT medianState(inf) AS x
    FROM numbers(5)
    UNION ALL
    SELECT medianState(1.)
    FROM numbers(5)
)
┌─medianMerge(x)─┐
│            inf │
└────────────────┘



SELECT medianMerge(x)
FROM
(
    SELECT medianState(inf) AS x
    FROM numbers(5)
    UNION ALL
    SELECT medianState(1.)
    FROM numbers(6)
)

┌─medianMerge(x)─┐
│            nan │
└────────────────┘


SELECT medianMerge(x)
FROM
(
    SELECT medianState(inf) AS x
    FROM numbers(5)
    UNION ALL
    SELECT medianState(1.)
    FROM numbers(7)
)

┌─medianMerge(x)─┐
│              1 │
└────────────────┘
```

**Comment by alexey-milovidov** [comment]
The current behavior is ok for me. It is also entirely correct.

The `quantile` function is using the Reservoir Sampling algorithm, the reservoir is partially sorted,
the floating point values are sorted using a total order relation, where the order of Inf and -Inf is natural,
and the order of NaN related to other values is implementation defined,
and in fact there are only two possibilities: all NaNs are considered either less than all numbers or greater than all numbers,
then approximation of two nearest neighbor values is taken to get the result,
and if the nearest neighbor values in the ordered reservoir sample contain NaN, the approximated result will be NaN as well.
