### ISSUE TITLE
intersect in clickhouse

### ISSUE THREAD

**Issue by yst001** [ClickHouse/ClickHouse#36527]
Does clickhouse support interest keywords?

When I use intersect in clickhouse, there is a syntax error, it seems that clickhouse can only support union all?

**Comment by amosbird** [comment]
`interest  -> intersect` ?

**Comment by yst001** [comment]
> `interest -> intersect` ?

Sorry, it's INTERSECT, I made a typo in the question

**Comment by yst001** [comment]
In the process of using INTERSECT, there is a syntax error, the click house version is 21.4.6.55

**Comment by amosbird** [comment]
`INTERSECT` is available in newer versions.

**Comment by yst001** [comment]
> `INTERSECT` is available in newer versions.

Can you recommend me a stable version of clickhouse that supports intersect syntax?

**Comment by amosbird** [comment]
The latest LTS version (22.3-LTS) is a good candidate to try.

**Comment by yst001** [comment]
> The latest LTS version (22.3-LTS) is a good candidate to try.

thank you
