### ISSUE TITLE
Where is core dump saved?

### ISSUE THREAD

**Issue by SadiHassan** [ClickHouse/ClickHouse#36528]
Hi,
I generated a server crash with log message `Segmentation fault (core dumped)` and trying to see where the core dump file is saved. I found two places in the code (`Basedaemon.cpp` and `Server.cpp`) where they indicate to save core dump in either `/opt/cores/` pr `/var/lib/clickhouse/cores`. 
But I couldn't find any file in those folders. In fact, I had to create both the `cores` folders manually.
Also, in the `config.xml`, I added this tag `<core_path>/opt/cores/</core_path>` as mentioned in `Basedaemon.cpp` like this: `std::string core_path = config().getString("core_path", "");`.

I am really confused, is there anything I am missing? Where can I find cored dump file?

P.S. I know crash report is sent to sentry server if it's enabled. I don't want that. Rather I want to keep the dump file in my server for analysis.

**Comment by tavplubix** [comment]
I depends on your system settings, `core_path` config parameter works only if your system is configured to save core files to current directory. See https://stackoverflow.com/questions/2065912/core-dumped-but-core-file-is-not-in-the-current-directory

Btw, it makes sense to check `/proc/sys/kernel/core_pattern` before changing working dir to `core_path` and maybe print some warning to log here:
https://github.com/ClickHouse/ClickHouse/blob/07e66e690d1f3c1f6a6ff79f604c67dc8a75691b/base/daemon/BaseDaemon.cpp#L739-L755
