### ISSUE TITLE
Implement ULID function

### ISSUE THREAD

**Issue by nstrappazzonc** [ClickHouse/ClickHouse#36536]
**Use case**

Implement ULID (Universally Unique Lexicographically Sortable Identifier) this a new way to create unique identify, and many projects adopting this algorithm.

Please check this follow projects:
- https://github.com/oklog/ulid
- https://github.com/ulid/javascript

**Comment by pdomitor** [comment]
Thumbs up. Really looking forward this feature.

**Comment by lingtaolf** [comment]
Let me have a try.

**Comment by UnamedRus** [comment]
BTW, why ULID use 26 bytes for storage, it's not efficient.

It should be able to pack it in 16 bytes like UUID
