### ISSUE TITLE
Degraded performance in 22.3 when scanning through large volume of items

### ISSUE THREAD

**Issue by tonickkozlov** [ClickHouse/ClickHouse#36553]
**Describe the situation**
Running a query that potentially reads a large number of files leads to degraded performance with `--local_filesystem_read_method=pread` enabled

**How to reproduce**
* Which ClickHouse server version to use
22.3

* Non-default settings, if any
`--local_filesystem_read_method=pread`

* `CREATE TABLE` statements for all tables involved

```
drop table if exists test_tenant;
create table test_tenant(
    partition UInt64,
    value1 UInt64,
    value2 UInt64,
    value3 UInt64,
    value4 UInt64,
    value5 UInt64,
    value6 UInt64,
    value7 UInt64,
    value8 UInt64,
    value9 UInt64
) engine = MergeTree()
    partition by partition
    order by value1
    settings
        min_bytes_for_wide_part = 0,
        min_rows_for_wide_part = 0;

set max_partitions_per_insert_block = 0;

insert into test_tenant
    select
        round(number / 5000) as partition,
        rand64() as value1,
        value1 % 10 as value2,
        value1 % 100 as value3,
        value1 % 1000 as value4,
        value1 % 10000 as value5,
        value1 % 100000 as value6,
        value1 as value7,
        value1 as value8,
        value1 as value9
    from
        numbers(1000000);

optimize table test_tenant final;
```
* Queries to run that lead to slow performance
```
seq 10000 | xargs -n1 echo "SELECT COLUMNS('value') APPLY max FROM test_tenant where value3 = " | clickhouse benchmark -t 30 -c8 --delay 0 --cumulative --local_filesystem_read_method=pread
...
0.000%        0.145 sec.
10.000%        0.170 sec.
20.000%        0.174 sec.
30.000%        0.177 sec.
40.000%        0.180 sec.
50.000%        0.184 sec.
60.000%        0.192 sec.
70.000%        0.225 sec.
80.000%        0.257 sec.
90.000%        0.281 sec.
95.000%        0.297 sec.
99.000%        0.332 sec.
99.900%        0.357 sec.
99.990%        0.367 sec.
```

**Expected performance**
```
seq 10000 | xargs -n1 echo "SELECT COLUMNS('value') APPLY max FROM test_tenant where value3 = " | clickhouse benchmark -t 30 -c8 --delay 0 --cumulative --local_filesystem_read_method=read
...
0.000%        0.092 sec.
10.000%        0.106 sec.
20.000%        0.109 sec.
30.000%        0.112 sec.
40.000%        0.114 sec.
50.000%        0.116 sec.
60.000%        0.118 sec.
70.000%        0.120 sec.
80.000%        0.123 sec.
90.000%        0.127 sec.
95.000%        0.131 sec.
99.000%        0.138 sec.
99.900%        0.151 sec.
99.990%        0.151 sec.
```

**Additional context**
Note the difference is only in `--local_filesystem_read_method` used.

cc @nvartolomei

**Comment by tonickkozlov** [comment]
![36s982_flame](https://user-images.githubusercontent.com/4903895/164748004-58938334-e672-47a5-bb73-f8c17fbe8c3a.svg)
Attaching a flame graph I've captured when running a similar workload. Seems like `DB::OpenedFileCache::get` could be a bottleneck

**Comment by alexey-milovidov** [comment]
Please make differential flame graph or attach two flame graphs (for old and new version).

**Comment by alexey-milovidov** [comment]
Please check if changing `pread` to `read` as `local_filesystem_read_method` solving the issue.

**Comment by nickitat** [comment]
@tonickkozlov with which version you are comparing 22.3?

**Comment by tonickkozlov** [comment]
@nickitat 21.8. Although I think the performance of 21.8 is on par with 22.3 with setting `local_filesystem_read_method=read `.

I'll try to capture a flame graph that compares the `read` and `pread` for 22.3 now, I think it'll be more descriptive.

**Comment by tonickkozlov** [comment]
@nickitat Thanks for looking into this! Please see the updated flame graph comment above.

**Comment by tonickkozlov** [comment]
Attempted a fix: https://github.com/ClickHouse/ClickHouse/pull/36682
