### ISSUE TITLE
how to upgrade expat version in clickhouse?

### ISSUE THREAD

**Issue by wangdonsy** [ClickHouse/ClickHouse#36565]
when i use command strings /usr/bin/clickhouse | grep  expat   get clickhouse use expat version is 2.27

[root@smartdba ~]# strings /usr/bin/clickhouse | grep  expat
expat_2.2.7
[root@smartdba ~]#

when i search the expat security vulnerability
https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=expat
https://nvd.nist.gov/vuln/search/results?form_type=Basic&results_type=overview&query=expat&search_type=all&isCpeNameSearch=false

there are many security vulnerability about expat,  how to upgrade expat to high version?

**Comment by alexey-milovidov** [comment]
"Expat" is used as part of "Poco" library for parsing XML.
XML is used to parse configuration files of ClickHouse.
If you want to upgrade "Expat", look here: https://github.com/ClickHouse/poco
