### ISSUE TITLE
Update Architecture page: BlockInputStream interfaces don't exist anymore

### ISSUE THREAD

**Issue by sergeyqz** [ClickHouse/ClickHouse#36568]
[Remove BlockInputStream interfaces](https://github.com/ClickHouse/ClickHouse/commit/ab28c6c855dfc57b40938f858a99c091896d166e) was commited on October 14, 2021. But the [Overview of ClickHouse Architecture](https://github.com/ClickHouse/ClickHouse/blob/3936b3e800a947b399feb7276e10a110f36b1f61/docs/en/development/architecture.md#block-streams-block-streams) page still mentions those interfaces. The string `IBlockOutputStream` appears 7 times in the next sections of the page:

  - Block Streams
  - Formats
  - I/O
  - Interpreters

**Comment by alexey-milovidov** [comment]
@serxa wanted to update the architecture page.

**Comment by alexey-milovidov** [comment]
#42547
