### ISSUE TITLE
A lightweight system table for analyzing the caching access  of one query 

### ISSUE THREAD

**Issue by KinderRiven** [ClickHouse/ClickHouse#36574]
Information such as the cache hit rate in the storage-calculation separation scenario can effectively help users analyze the reasons for request performance fluctuations. Currently, ClickHouse does not seem to record relevant information. Whether the community considers supporting related implementations in the future or receiving related PRs.

**Example:**
`select quey_id, hit_count, miss_count, hit_ratio from system.cache_log`

<img width="981" alt="image" src="https://user-images.githubusercontent.com/10573698/164955669-7084d449-5a25-4b31-89f2-105099faf988.png">

**Comment by kssenii** [comment]
This information is partially covered by `system.filesystem_cache`, but there is no link to query id at the moment.
