### ISSUE TITLE
table function obs Code: 46. DB::Exception: Unknown table function obs

### ISSUE THREAD

**Issue by WillMeng** [ClickHouse/ClickHouse#36581]
Clickhouse version 22.3.2.1

`select * FROM obs('','CSV','')`

Code: 46. DB::Exception: Unknown table function obs. (UNKNOWN_FUNCTION) (version 22.3.2.1)

but I saw Clickhouse has supported, [https://github.com/ClickHouse/ClickHouse/pull/29511](url), and I saw source code(v22.3.2.2-lts) in src/IO/S3Common.cpp: 
`
static constexpr auto S3 = "S3";
static constexpr auto COSN = "COSN";
static constexpr auto COS = "COS";
static constexpr auto OBS = "OBS";
static constexpr auto OSS = "OSS";
`

**Comment by den-crane** [comment]
It's not about function. Function is the same for all `s3`. It's about URL check. 

`select * FROM s3('https://some-bucket.obs.ru-moscow-1.hc.sbercloud.ru/some/path/file.txt','CSV','')`
