### ISSUE TITLE
22.4.2 revision 54455 merge question

### ISSUE THREAD

**Issue by yangshike** [ClickHouse/ClickHouse#36597]
![image](https://user-images.githubusercontent.com/13585274/165006744-0e0a064e-961d-4830-9079-683c11bfebe5.png)

**Comment by yangshike** [comment]
with version of 22.3 has no problem.  when i updated to 22.4.2 , some merges got this error

**Comment by yangshike** [comment]
![image](https://user-images.githubusercontent.com/13585274/165008005-3c714329-65c6-4e9a-a123-43d90f298dd0.png)
this is my table columns desc , when i run: alter table xx modify column course_number UInt64 ;  
then  the error  disappear.
i think new version when  merge  has force check column whether Nullable？

**Comment by tavplubix** [comment]
Please follow the template: https://github.com/ClickHouse/ClickHouse/blob/master/.github/ISSUE_TEMPLATE/85_bug-report.md
Post error messages/logs/table definitions/etc as text, not as screenshots.
Your screenshot does not even contain full error message.

**Comment by den-crane** [comment]
see https://github.com/ClickHouse/ClickHouse/issues/36687
