### ISSUE TITLE
Is there a plan to connect with table format?

### ISSUE THREAD

**Issue by Faynebupt** [ClickHouse/ClickHouse#36603]
Iceberg/hudi/delta is  popular. Do clickhouse have a connection plan

**Comment by alexey-milovidov** [comment]
No plans so far. Let's keep it in mind as a feature request.

**Comment by rupurt** [comment]
Would love to have support for Iceberg table format

**Comment by alexey-milovidov** [comment]
We implemented Hudi and DeltaLake with read-only support.
@ucasFL is implementing Iceberg.
