### ISSUE TITLE
isIPAddressInRange wrong for ipv4 mapped to ipv6

### ISSUE THREAD

**Issue by asafcombo** [ClickHouse/ClickHouse#36605]
When using a mapped ipv4 the function gives the wrong response. see below - 

```sql
isIPAddressInRange('::ffff:108.59.80.5'  , '108.59.80.0/16') as with_mapped,
isIPAddressInRange('108.59.80.5'  , '108.59.80.0/16') as normal
```

return values are `0,1` but expectation is `1,1`.

version `21.8.6.15`

**Comment by HeenaBansal2009** [comment]
This is expected.Prefix IP version should be same as in address. 
This worked.
` 
SELECT
    isIPAddressInRange('::ffff:108.59.80.5', **'::ffff:108.59.80.0/16'**) AS with_mapped,
    isIPAddressInRange('108.59.80.5', '108.59.80.0/16') AS normal

Query id: d9d1c10c-e4d7-4db7-af4a-a0df7d29b6cf

┌─with_mapped─┬─normal─┐
│           1 │      1 │
└─────────────┴────────┘

`

**Comment by timotm** [comment]
Addresses outside of the range seem to behave differently, though
```
curl "https://play.clickhouse.com/?user=explorer" --data-binary "SELECT isIPAddressInRange('::ffff:108.60.80.5', '::ffff:108.59.80.0/16') AS with_mapped, isIPAddressInRange('108.60.80.5', '108.59.80.0/16') AS normal"
1	0
```

**Comment by ni1l** [comment]
After reading the code, I found that there was a problem with my understanding. The number of mask bits of IPV6 should be used here. Look like this:
![image](https://user-images.githubusercontent.com/94829417/167372726-d1eeb6e4-f083-4cf8-b485-20cea5f6694e.png)

**Comment by timotm** [comment]
Nice finding! The [documentation](https://github.com/ClickHouse/ClickHouse/blob/v22.4.5.9-stable/docs/en/sql-reference/functions/ip-address-functions.md) is a bit (or many, actually) misleading in one of the examples, though

> Query:

``` sql
SELECT isIPAddressInRange('127.0.0.1', 'ffff::/16');
```

> Result:

``` text
┌─isIPAddressInRange('127.0.0.1', 'ffff::/16')─┐
│                                            0 │
└──────────────────────────────────────────────┘
```

**Comment by ni1l** [comment]
I also mistakenly thought that the mask which mapped from ipv4 to ipv6 has special treatment after reading the document, but it does not.
