### ISSUE TITLE
Materialized views is not consistent with source table(ReplicateMergeTree)

### ISSUE THREAD

**Issue by jerry4free** [ClickHouse/ClickHouse#36606]
Materialized views is not consistent with source table.  And the dest table is less than it's source table. The dest and source table both are ReplicateMergeTree

But if I use a MergeTree(non Replicated) source table and MergeTree dest table, the des table is consistent with source table! This is very weird.

* Clickhouse-server version: 22.3.3.44. There's only two nodes(one shard, two replicates)
* My application is a flink app, which read from kafka and write to clickhouse by jdbc(sbt config: "ru.yandex.clickhouse" % "clickhouse-jdbc" % "0.3.1")
* I always write to one node

* dest table: `CREATE TABLE  biz.dest_table
(
    `ts_min` String,
    `pv1` Int64,
    `top_pv2` Int64,
    `top_pv3` Int64,
    `click` Int64,
    `price` Int64,
    `cv` Int64,
    `dt` String,
    `hour` String
)
    ENGINE = ReplicatedMergeTree('/clickhouse/tables/{cluster}-{shard}/dest_table_replica', '{replica}')
        PARTITION BY (dt, hour)
        ORDER BY (ts_min)
        SETTINGS index_granularity = 8192;`
* materialized view: `CREATE MATERIALIZED VIEW biz.mv_source_table
            to biz.dest_table
AS
SELECT
    ts_min,
    pv1,
    top_pv2,
    top_pv3,
    click,
    price,
    cv,
    dt,
    hour
FROM biz.source_table;`
* source table: `CREATE TABLE biz.source_table
(
    `ts_min` String,
    `pid` String,
    `city` Int32,
    `exp_tag` Array(String),
    `query_classify` Int32,
    `pv1` Int64,
    `top_pv2` Int64,
    `top_pv3` Int64,
    `click` Int64,
    `price` Int64,
    `cv` Int64,
    `dt` String,
    `hour` String
)
    ENGINE = ReplicatedMergeTree('/clickhouse/tables/{cluster}-{shard}/source_table_replica', '{replica}')
        PARTITION BY (dt, hour)
        ORDER BY (ts_min, exp_tag, pid, query_classify, city)
        SETTINGS index_granularity = 8192;`

* Queries to run that lead to unexpected result
** source table's query: `select dt, hour, sum(pv1), sum(click) from source_table where dt = '20220425' and hour >= '13' and hour <= '15' group by dt, hour order by dt, hour;

SELECT
    dt,
    hour,
    sum(pv1),
    sum(click)
FROM source_table
WHERE (dt = '20220425') AND (hour >= '13') AND (hour <= '15')
GROUP BY
    dt,
    hour
ORDER BY
    dt ASC,
    hour ASC

Query id: 5d9df610-d7fe-4e47-b75a-00ada0862897

┌─dt───────┬─hour─┬─sum(pv1)─┬─sum(click)─┐
│ 20220425 │ 13   │ 11514335 │     122887 │
│ 20220425 │ 14   │ 12206347 │     123787 │
│ 20220425 │ 15   │ 12945058 │     127005 │
└──────────┴──────┴──────────┴────────────┘

3 rows in set. Elapsed: 0.402 sec. Processed 37.04 million rows, 1.63 GB (92.07 million rows/s., 4.05 GB/s.)`

** dest table's query: `select dt, hour, sum(pv1), sum(click) from dest_table where dt = '20220425' and hour >= '13' and hour <= '15' group by dt, hour order by dt, hour

SELECT
    dt,
    hour,
    sum(pv1),
    sum(click)
FROM dest_table
WHERE (dt = '20220425') AND (hour >= '13') AND (hour <= '15')
GROUP BY
    dt,
    hour
ORDER BY
    dt ASC,
    hour ASC

Query id: 2442bea2-8b49-43c1-9801-932c3c8a0d5a

┌─dt───────┬─hour─┬─sum(pv1)─┬─sum(click)─┐
│ 20220425 │ 13   │  6773573 │      73052 │
│ 20220425 │ 14   │  6084114 │      61928 │
│ 20220425 │ 15   │  7430102 │      73050 │
└──────────┴──────┴──────────┴────────────┘

3 rows in set. Elapsed: 0.270 sec. Processed 20.50 million rows, 901.82 MB (75.97 million rows/s., 3.34 GB/s.)`

**I aggregate pv1 metric and click metric by hour, the dest table's pv1 is almost 55% of source table! I expect both are same.**

**There's no exception on the flink client**

**Additional context**

> I stats `Wrote` keyword in clickhouse-server.log for dest table and source table(in one hour), which can imply the number of writes
`grep 'source_table' -iI   clickhouse-server.log | grep 'Wrote' | grep '2022.04.25 15' | awk -F '{' '{print $2}' | awk -F '}' '{print $1}' | uniq | wc -l`, result is 130
`grep 'dest_table' -iI   clickhouse-server.log | grep 'Wrote' | grep '2022.04.25 15' | awk -F '{' '{print $2}' | awk -F '}' '{print $1}' | uniq | wc -l`, result is 72
> There's no error log for both table in clickhouse-server.err.log

<img width="1506" alt="wecom-temp-a3bef7965317e03dbfb310bfac9af77d" src="https://user-images.githubusercontent.com/3926621/165056942-0dcfa115-2800-4fd5-8d43-dc391faa68d4.png">
<img width="1510" alt="wecom-temp-0ab580e98a0f627f219da86c989278e9" src="https://user-images.githubusercontent.com/3926621/165057031-0d2ace77-847a-492d-a7f6-55e72671332b.png">
> As shows, the first is log of source table, the second is log of dest table for the same time period. The source table has 5 writes, but the dest table has 3 writes.

**Comment by den-crane** [comment]
Do you use `deduplicate_blocks_in_dependent_materialized_views` ?

provide 

```
select * from system.settings where changed
```

https://clickhouse.com/docs/en/operations/settings/settings#settings-deduplicate-blocks-in-dependent-materialized-views

https://den-crane.github.io/Everything_you_should_know_about_materialized_views_commented.pdf

**Comment by jerry4free** [comment]
No, the setting `deduplicate_blocks_in_dependent_materialized_views` is disabled(default).
<img width="1484" alt="image" src="https://user-images.githubusercontent.com/3926621/165214362-421f11ef-4c2a-4caa-9106-4bafcdf439ea.png">

I have already read the pdf. 
Do you means i can try to enable `deduplicate_blocks_in_dependent_materialized_views` and retry insert on the client in case of failure?
But there is no failure exception on the client.
And if I use SummingMergeTree  as MV, Should I have to add a column into the source table with an insert unique identifier and propagate this column into MV?

**Comment by jerry4free** [comment]
I enable `deduplicate_blocks_in_dependent_materialized_views `, and the source table is consistent with materialized view.
Thanks a lot!
But i still have a question about the `deduplicate_blocks_in_dependent_materialized_views` setting doc which is described as `If an INSERT into the main table was successful and INSERT into a materialized view failed (e.g. because of communication failure with Zookeeper) a client will get an error and can retry the operation`. 
And it's not entirely true, because my jdbc client haven't got any exception or error. This mislead me. 😅
So i think `will get an error` should be replace with `maybe get an error`.

**Comment by den-crane** [comment]
>I enable deduplicate_blocks_in_dependent_materialized_views , and the source table is consistent with materialized view.

I was expecting the opposite. 
Can you reproduce the issue? Can you share reproducible example?

Documentation is correct. (but I think I wrote this sentence in the doc).

**Comment by jerry4free** [comment]
I can reproduce the issue on our product environment, but i can't reproduce it based on some easy examples.
