### ISSUE TITLE
CREATE TABLE ... AS SELECT ... does not copy default values

### ISSUE THREAD

**Issue by FedericoCeratto** [ClickHouse/ClickHouse#36617]
EmbeddedRocksDB does not support multi-column key and row deletion. As a workaround I tried using a tuple key and creating a new table to delete a row.

The new table does not have default values.

Steps to reproduce:
```
CREATE TABLE foo 
( 
    `tuplekey` Tuple(String, String) DEFAULT (a, b), 
    `a` String, 
    `b` String DEFAULT '*' 
) 
ENGINE = EmbeddedRocksDB 
PRIMARY KEY tuplekey; 
 
CREATE TABLE foo2 
ENGINE = EmbeddedRocksDB 
PRIMARY KEY tuplekey AS 
SELECT * 
FROM foo;

SHOW CREATE TABLE foo2; 
```

The documentation at https://clickhouse.com/docs/en/sql-reference/statements/create/table/#with-a-schema-similar-to-other-table does not clarify what to expect regarding default values.

**Comment by alexey-milovidov** [comment]
This is expected.

SELECT query does not transfer the information about the original default values, because it can apply arbitrary expression and generate arbitrary resultset.

Imagine `CREATE TABLE ... AS SELECT a || b || toString(tupleKey) FROM foo`

**Comment by FedericoCeratto** [comment]
@alexey-milovidov thanks for the answer. The documentation on the URL liked above does not clarify what is the expected behavior. Maybe this issue could be reopened as a documentation issue...?

**Comment by alexey-milovidov** [comment]
@FedericoCeratto let's quickly fix the documentation (press on "edit this page"), otherwise there is a high chance to forget about this issue.
