### ISSUE TITLE
Int128 question

### ISSUE THREAD

**Issue by Faynebupt** [ClickHouse/ClickHouse#36615]
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/19455764/165082214-c030223e-8113-4026-8436-d27212fb6ec0.png">

 The type 'Int128' of a column 'value' is not supported for conversion into Parquet data format. (UNKNOWN_TYPE)

**Comment by Faynebupt** [comment]
The type 'Int128' of a column 'value' is not supported for conversion into Arrow data format. (UNKNOWN_TYPE)

how solve this problem?

**Comment by den-crane** [comment]
Use cast to String (toString).
