### ISSUE TITLE
How to edit the table column from MaterializedPostgreSQL

### ISSUE THREAD

**Issue by Zkuns** [ClickHouse/ClickHouse#36620]
I use the MaterializedPostgreSQL to connect my PG database.

But one of my PG tables has a very large Json column. I don't want to import and sync this JSON column. Is there any way I can stop only this column sync?

Do I have to change my database structure and move this column to another table?

**Comment by kssenii** [comment]
try `TABLE OVERRIDE` syntax: https://github.com/ClickHouse/ClickHouse/blob/f53040b95e4c2c160dc594b561c36b464405ab05/tests/integration/test_postgresql_replica_database_engine_2/test.py#L639
