### ISSUE TITLE
How we do some way to  ignore the connection errors caused by the health check?

### ISSUE THREAD

**Issue by xiaods** [ClickHouse/ClickHouse#3665]
In general, TCP three-way handshakes are conducted to establish a TCP connection. After the LVS node server receives an SYN + ACK data packet from the backend ECS instance, the LVS node server sends an ACK data packet, and then immediately sends an RST data packet to terminate the TCP connection.
This process may cause backend server to think an error occurred in the TCP connection, such as an abnormal exit, and then throw a corresponding error message, such as Connection reset by peer.

currently ClickHouse's behavior same with above  description,  how to elegantly fix it.

![2549_en-us](https://user-images.githubusercontent.com/37678/48989064-8af26d80-f163-11e8-999d-223c6addc9e4.png)

**Comment by alexey-milovidov** [comment]
@xiaods Why it's closed? Is it fixed or still actual?

**Comment by filimonov** [comment]
Related https://github.com/ClickHouse/ClickHouse/issues/23858
