### ISSUE TITLE
ClickHouse can't be started with error "meta file xxx still in cache"

### ISSUE THREAD

**Issue by chen9t** [ClickHouse/ClickHouse#36671]
## Unexpected behavior
When testing the experimental feature "parts loading speed up"(#32928), we found that ClickHouse can't be restarted with error
```
{} <Error> Application: DB::Exception: Data part 202204_43680_43690_2 with type Compact with meta file store/87f/87fd1c2b-113c-4840-87fd-1c2b113cf840/202204_43680_43690_2/minmax_event_date.idx still in cache: Cannot attach table `system`.`query_thread_log` from metadata file /data1/clickhouse-data/store/aeb/aeb28fea-8252-4939-95b7-66ca9336f208/query_thread_log.sql from query ATTACH TABLE system.query_thread_log UUID '87fd1c2b-113c-4840-87fd-1c2b113cf840' ...
``` 

## Analysis
Before this issue happens, ClickHouse exited accidently because of hardware issue, and part 202204_43680_43690_2 created but not flushed to disk.

When server restarted, the empty part was expected to move to detached directories, and thie `renameTo` operation will tigger 
`deleteAll()` and `assertAllDeleted()`:
```
void IMergeTreeDataPart::renameTo(const String & new_relative_path, bool remove_new_dir_if_exists) const
{
    ...
    metadata_manager->deleteAll(true);
    metadata_manager->assertAllDeleted(true);
    volume->getDisk()->setLastModified(from, Poco::Timestamp::fromEpochTime(time(nullptr)));
    volume->getDisk()->moveDirectory(from, to);
    relative_path = new_relative_path;
    metadata_manager->updateAll(true);

    SyncGuardPtr sync_guard;
    if (storage.getSettings()->fsync_part_directory)
        sync_guard = volume->getDisk()->getDirectorySyncGuard(to);
   ...
}
```

`deleteAll()` collects meta files manually, in `appendFilesOfPartitionAndMinMaxIndex()`:
```
void IMergeTreeDataPart::appendFilesOfPartitionAndMinMaxIndex(Strings & files) const
{
    ...
    if (!isEmpty())
        if (!parent_part)
            minmax_idx->appendFiles(storage, files);
}
```
minmax_idx was skipped because of empty part.

`assertAllDeleted()` collects meta file by rocksdb scan, so minmax_idx will be checked and asserted here.

Is it OK to implement `deleteAll()` just as `assertAllDeleted()` does, so we can make sure there's no corner issues?

@taiyang-li @CurtizJ

**Comment by taiyang-li** [comment]
@chen9t  thanks for your feedback.  I'll try to fix it.

**Comment by chen9t** [comment]
@taiyang-li Any update on this issue? We are looking forward to use this feature.

May be we can talk about the solution here, and let me implement it once you are busy, if it's OK to you~

**Comment by taiyang-li** [comment]
@chen9t  Sorry to reply late, you can implement it of course, thanks!

**Comment by chen9t** [comment]
@taiyang-li Thanks~

> Is it OK to implement `deleteAll()` just as `assertAllDeleted()` does, so we can make sure there's no corner issues?
What do you think about this solution? I mean do RocksDB prefix scan in `deleteAll()`.

Except for performance, if we implement `deleteAll()` with RocksDB prefix scan, projections will also be removed by parent part deletion. I'm not sure if it is your concern about this solution?

But projections are sub directories of parent part, if we meant to delete parent part, projections should also be deleted.

So is it OK to remove `include_projection` parameter among several functions, and just delete everything under any part in `deleteAll()`?

**Comment by taiyang-li** [comment]
It's definitely not ok to remove include_projection. Sometimes we want to remove metadata cache in root part, without changing

**Comment by taiyang-li** [comment]
Can you provide how to reprofuce this issue, I guess there maybe a easier way without refactor `deleteAll` ?

**Comment by chen9t** [comment]
> Root part and projection parts share the same prefix. We have to distinguish them by parameter include_projection, even if you get all cache keys by prefix scan. Sometimes we want to remove cache of root part without touching cache in projection part. See IMergeTreeDataPart::remove and IMergeTreeDataPart::projectionRemove

Thanks for the declaration. It's true that we can't just simply remove `include_projection`.

But I prefer to accept that, because root part and projection parts share the same prefix, sometimes we want to remove cache of projection part without touching cache in root part. Projections are sub directories under root part, if we want to remove root part, there's no reason we leave the projection part, so as the meta cache.

> Can you provide how to reproduce this issue?

It's hard to reproduce this issue, caused by some accident exit.

> Besides, I have question about this issue:
> * Before restart, if part files is not flushed to disk, how come minmax_event_date.idx still in cache. Notice that cache entry is set only if corresponding metadata file exists.

It's true. But there's condition that, part files meta data(OS VFS meta data, not ClickHouse) can be flushed to disk while file contents can still be in memory.

**Comment by taiyang-li** [comment]
It's projection part's duty to remove cache by itself , as it is projection parts's duty to remove metadata files on disk by itself. See `IMergeTreeDataPart::remove`.
Remove `include_projection` and delete all cache entries of projection parts in parent part is not graceful, and I'am not sure if it will cause other logical errors.

**Comment by taiyang-li** [comment]
The output of `IMergeTreeDataPart::appendFilesOfPartitionAndMinMaxIndex` depends on another metadata file `rows.txt`(not exists or contains `0`)

I think if we remove this dependency, minmax index metadata file should be remove from cache successfully.

**Comment by chen9t** [comment]
> Can you show me ls -l result of the part directory ?

```
-rw-r----- 1 user users  261 Apr 23 10:47 checksums.txt
-rw-r----- 1 user users 1.1K Apr 23 10:47 columns.txt
-rw-r----- 1 user users    2 Apr 23 10:47 count.txt
-rw-r----- 1 user users 8.0K Apr 23 10:47 data.bin
-rw-r----- 1 user users 1.4K Apr 23 10:47 data.mrk3
-rw-r----- 1 user users   10 Apr 23 10:47 default_compression_codec.txt
-rw-r----- 1 user users    4 Apr 23 10:47 minmax_event_date.idx
-rw-r----- 1 user users    4 Apr 23 10:47 partition.dat
-rw-r----- 1 user users   12 Apr 23 10:47 primary.idx
```

**Comment by chen9t** [comment]
> The output of `IMergeTreeDataPart::appendFilesOfPartitionAndMinMaxIndex` depends on another metadata file `rows.txt`(not exists or contains `0`)
> 
> I think if we remove this dependency, minmax index metadata file should be remove from cache successfully.

Yes, it also works and do no harm. But I like the logic you check empty part before add minmax_idx, to be honest.

Anyway, I'm OK with this solution.

**Comment by taiyang-li** [comment]
Ok. Let's wait for review. Thanks.
