### ISSUE TITLE
WHERE clause changes array arithmetics result

### ISSUE THREAD

**Issue by hombit** [ClickHouse/ClickHouse#36677]
> You have to provide the following information whenever possible.

Some queries fives different calculation results when this result is a part of a WHERE expression and when it is not.

> A clear and concise description of what works not as it is supposed to.

**Does it reproduce on recent release?**

The bug is reproduced in 22.4.1.2039 (playground), 22.2.2.1 (binary installation on Redhat), 21.6.4.1 (Debian package installed inside Docker)

**How to reproduce**

This query gives right result ([playground](https://play.clickhouse.com/play?user=play#U0VMRUNUCiAgICBhcnJheVN1bSh4IC0+ICgoeC4xKSAvICgoeC4yKSAqICh4LjIpKSksIGFycmF5WmlwKG1hZywgbWFnZXJyKSkgLyBhcnJheVN1bSh4IC0+ICgxLiAvICh4ICogeCkpLCBtYWdlcnIpIEFTIHdlaWdodGVkbWVhbm1hZywKICAgIGFycmF5U3VtKHggLT4gKCgoKHguMSkgLSB3ZWlnaHRlZG1lYW5tYWcpICogKCh4LjEpIC0gd2VpZ2h0ZWRtZWFubWFnKSkgLyAoKHguMikgKiAoeC4yKSkpLCBhcnJheVppcChtYWcsIG1hZ2VycikpIEFTIGNoaTIsCiAgICBbMSwgMiwgMywgNF0gQVMgbWFnLAogICAgWzAuMSwgMC4yLCAwLjEsIDAuMl0gQVMgbWFnZXJyCg==))
```sql
SELECT
    arraySum(x -> ((x.1) / ((x.2) * (x.2))), arrayZip(mag, magerr)) / arraySum(x -> (1. / (x * x)), magerr) AS weightedmeanmag,
    arraySum(x -> ((((x.1) - weightedmeanmag) * ((x.1) - weightedmeanmag)) / ((x.2) * (x.2))), arrayZip(mag, magerr)) AS chi2,
    [1, 2, 3, 4] AS mag,
    [0.1, 0.2, 0.1, 0.2] AS magerr
```
```
┌────weightedmeanmag─┬───────────────chi2─┬─mag───────┬─magerr────────────┐
│ 2.1999999999999997 │ 289.99999999999994 │ [1,2,3,4] │ [0.1,0.2,0.1,0.2] │
└────────────────────┴────────────────────┴───────────┴───────────────────┘
```

And this makes `chi2` to be zero ([playground](https://play.clickhouse.com/play?user=play#U0VMRUNUCiAgICBhcnJheVN1bSh4IC0+ICgoeC4xKSAvICgoeC4yKSAqICh4LjIpKSksIGFycmF5WmlwKG1hZywgbWFnZXJyKSkgLyBhcnJheVN1bSh4IC0+ICgxLiAvICh4ICogeCkpLCBtYWdlcnIpIEFTIHdlaWdodGVkbWVhbm1hZywKICAgIGFycmF5U3VtKHggLT4gKCgoKHguMSkgLSB3ZWlnaHRlZG1lYW5tYWcpICogKCh4LjEpIC0gd2VpZ2h0ZWRtZWFubWFnKSkgLyAoKHguMikgKiAoeC4yKSkpLCBhcnJheVppcChtYWcsIG1hZ2VycikpIEFTIGNoaTIsCiAgICBbMSwgMiwgMywgNF0gQVMgbWFnLAogICAgWzAuMSwgMC4yLCAwLjEsIDAuMl0gQVMgbWFnZXJyCldIRVJFIGlzRmluaXRlKGNoaTIpCg==))

```sql
SELECT
    arraySum(x -> ((x.1) / ((x.2) * (x.2))), arrayZip(mag, magerr)) / arraySum(x -> (1. / (x * x)), magerr) AS weightedmeanmag,
    arraySum(x -> ((((x.1) - weightedmeanmag) * ((x.1) - weightedmeanmag)) / ((x.2) * (x.2))), arrayZip(mag, magerr)) AS chi2,
    [1, 2, 3, 4] AS mag,
    [0.1, 0.2, 0.1, 0.2] AS magerr
WHERE isFinite(chi2)
```
```
┌────weightedmeanmag─┬─chi2─┬─mag───────┬─magerr────────────┐
│ 2.1999999999999997 │    0 │ [1,2,3,4] │ [0.1,0.2,0.1,0.2] │
└────────────────────┴──────┴───────────┴───────────────────┘
```

**Expected behavior**

WHERE shouldn't change calculation results

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/28083

**Comment by hombit** [comment]
Probably server should return an error for such cases instead of giving a wring result. Should I open an issue for this?

**Comment by den-crane** [comment]
I don't know. It's like common knowledge. I stumble on this issue twice a week.

**Comment by den-crane** [comment]
>It would be nice if clickhouse server shares this knowledge and yields an error =)

Actually I think it will break all existing production systems.

**Comment by den-crane** [comment]
> Maybe add this to the documentation?

You should definitely add this to the documentation.

**Comment by hombit** [comment]
> > It would be nice if clickhouse server shares this knowledge and yields an error =)
> 
> Actually I think it will break all existing production systems.

I don't understand this point, does anyone use this behavior as a feature?

**Comment by den-crane** [comment]
>I don't understand this point, does anyone use this behavior as a feature?

People who unaware (like you) happily live with this issue (it reproduces only in corner cases). So this change will break backward compatibility.

May be a new setting should be introduced `strict_lambda` = by default false.

**Comment by hombit** [comment]
I see, thank you!

**Comment by den-crane** [comment]
As I understood it will solved with https://github.com/ClickHouse/ClickHouse/issues/9715
