### ISSUE TITLE
Moving from s3 to local does not automatically delete s3 data

### ISSUE THREAD

**Issue by IVitamin-C** [ClickHouse/ClickHouse#36693]
Hi,
Because the SSD disk usage rate exceeds 90%, the strategy of automatically moving to s3 is triggered, and then under the TTL strategy, it is moved to HDD disks. Now the part of s3 cannot be found on the node, but the part on s3 is not deleted normally.
So you need to manually delete S3 data?

**Comment by tavplubix** [comment]
> So you need to manually delete S3 data?

No, probably it's a bug. Could you please provide more information (server version, discs configuration, changed settings, table definition, server logs, etc)? Do you have some reproducible example?

**Comment by IVitamin-C** [comment]
thanks！
server version: tag 22.3.3.44 lts
disks configuration:
```xml
<disks>
    <s3>
        <type>s3</type>
        <endpoint>http://xxx/</endpoint>
        <access_key_id>xxx</access_key_id>
        <secret_access_key>xxx</secret_access_key>
        <connect_timeout_ms>10000</connect_timeout_ms>
        <request_timeout_ms>5000</request_timeout_ms>
        <retry_attempts>10</retry_attempts>
        <single_read_retries>4</single_read_retries>
        <min_bytes_for_seek>1000</min_bytes_for_seek>
        <metadata_path>/data/clickhouse/default/disks/s3/</metadata_path>
        <cache_enabled>true</cache_enabled>
        <cache_path>/data/clickhouse/default/disks/s3/cache/</cache_path>
        <skip_access_check>false</skip_access_check>
    </s3>
</disks>
<policies>
    <default>
        <volumes>
            <single>
                <disk>default</disk>
            </single>
            <cold>
                <disk>data10</disk>
            </cold>
            <s3_cold>
                <disk>s3</disk>
                <prefer_not_to_merge>true</prefer_not_to_merge>
            </s3_cold>
        </volumes>
    </default>
<policies>
```
I did not modify the parameters related to the s3 disk.
```
merge_tree_settings:
min_bytes_for_wide_part=0
in_memory_parts_enable_wal=0
max_bytes_to_merge_at_max_space_in_pool=53687091200
old_parts_lifetime=0
temporary_directories_lifetime=3600
settings:
max_block_size=4194304
max_insert_block_size=16777216
max_insert_threads=10
max_threads=16 (physical core:38)
background_pool_size=64
background_move_pool_size=32
background_schedule_pool_size=128
enable_http_compression=1
send_progress_in_http_headers=0
preferred_block_size_bytes=4194304
```
Because the debug level log is turned on, the log at that time is no longer available.

The earliest disk volume order is single ->cold -> s3_cold,
Because the disk usage of the cold volume exceeds 90%, the data is automatically moved to s3, so I adjusted the order single -> s3_cold -> cold. I manually deleted the data of cold. Because of the TTL policy, the data was automatically moved from s3_cold to cold. At this time, I found that there was no s3 part in the cluster, but the part on s3 was not deleted. Many shards have the same case

Shard1:
Now the cluster shows that I am using S3 933.61 GiB, but S3 shows that I am using 1.36TB, some time ago. I suspect that this is the most part of data. But because the data is encoded and transformed, I can't identify which parts are extra.
I use a bucket for the two replicas of each shard to achieve the maximum bandwidth, 22.3lts, and zero-copy is enabled by default.

**Comment by alexey-milovidov** [comment]
Yes, it is possible that part is not deleted from S3 if there were errors during deletion attempts, and all retries didn't help, or the server was terminated at the moment between removing parts metadata and the part from S3.
