### ISSUE TITLE
Does gRPC work on ARM64?

### ISSUE THREAD

**Issue by pan3793** [ClickHouse/ClickHouse#36691]
Related configuration and expect gRPC work but seems not :(
```
    <grpc_port>9100</grpc_port>

    <grpc>
        <enable_ssl>false</enable_ssl>

        <!-- Default compression algorithm (applied if client doesn't specify another algorithm). Supported algorithms: none, deflate, gzip, stream_gzip -->
        <compression>gzip</compression>

        <!-- Default compression level (applied if client doesn't specify another level). Supported levels: none, low, medium, high -->
        <compression_level>medium</compression_level>

        <!-- Send/receive message size limits in bytes. -1 means unlimited -->
        <max_send_message_size>-1</max_send_message_size>
        <max_receive_message_size>-1</max_receive_message_size>

        <verbose_logs>false</verbose_logs>
    </grpc>
```

**Comment by den-crane** [comment]
HDFS HYPERSCAN GRPC SENTRY are not supported with ARM build.

```
select * from build_options where value <> '1' and value <> 'ON' and name like 'USE%';
┌─name──────────────────┬─value─┐
│ USE_EMBEDDED_COMPILER │       │
│ USE_HDFS              │       │
│ USE_HYPERSCAN         │       │
│ USE_GRPC              │       │
│ USE_SENTRY            │       │
└───────────────────────┴───────┘
```

**Comment by den-crane** [comment]
GRPC    https://github.com/ClickHouse/ClickHouse/blob/master/cmake/target.cmake#L29

HYPERSCAN is implemented by Intel and they implemented it only for x86_64

**Comment by pan3793** [comment]
After removing `set (ENABLE_GRPC OFF CACHE INTERNAL "")` I can build and start success on ARM64 platform(Ubuntu 22.04), gRPC looks working
<img width="981" alt="image" src="https://user-images.githubusercontent.com/26535726/165780198-95082e5a-e6f5-4b09-8a4c-25b804d96321.png">
<img width="658" alt="image" src="https://user-images.githubusercontent.com/26535726/165780717-8ebb0bac-f4c7-4d89-bf27-99e25a67e60b.png">

**Comment by pan3793** [comment]
Raised a PR and see what CI happens https://github.com/ClickHouse/ClickHouse/pull/36754

**Comment by zhanghuajieHIT** [comment]
> GRPC https://github.com/ClickHouse/ClickHouse/blob/master/cmake/target.cmake#L29
> 
> HYPERSCAN is implemented by Intel and they implemented it only for x86_64

Why is HDFS not compiled on ARM
