### ISSUE TITLE
Wrong behaviour of toDate() function

### ISSUE THREAD

**Issue by dimkas78** [ClickHouse/ClickHouse#36703]
ClickHouse version 22.3.3.44

toDate() function can handle exactly 31 day in each month of the year,
but there is not such thing as 31.02.2022 or 31.04.2022

Reproducing script: 
result of query presents after comment mark at then end of each row:

```
select toDate('2022-01-31'); -- 2022-01-31 - OK
select toDate('2022-01-32'); -- 1970-01-01 - OK, but why not exception?!
	
select toDate('2022-02-28') -- 2022-02-28 - OK 
select toDate('2022-02-29') -- 2022-03-01 - ERROR
select toDate('2022-02-30') -- 2022-03-02 - ERROR
select toDate('2022-02-31') -- 2022-03-03 - ERROR
select toDate('2022-02-32') -- 1970-01-01 - OK, but why not exception?!
    
select toDate('2022-04-31') -- 2022-05-01 - ERROR
select toDate('2022-06-31') -- 2022-07-01 - ERROR

```

**Comment by den-crane** [comment]
https://clickhouse.com/docs/en/sql-reference/functions/date-time-functions#tostartofmonth

The behavior of parsing incorrect dates is implementation specific. ClickHouse may return zero date, throw an exception or do “natural” overflow.

**Comment by den-crane** [comment]
duplicate of 

https://github.com/ClickHouse/ClickHouse/issues/21782
https://github.com/ClickHouse/ClickHouse/issues/8031
https://github.com/ClickHouse/ClickHouse/issues/7633
