### ISSUE TITLE
Use named connection in  remote(...) 

### ISSUE THREAD

**Issue by oleg-savko** [ClickHouse/ClickHouse#36709]
Can we use named connection in  remote(...) ?

I try:
`SELECT count() FROM remote(mxch, db='mx_master', table='health_watch');
`
but get:

`Code: 36. DB::Exception: Unexpected key-value argument.Got: db, but expected: sharding_key. (BAD_ARGUMENTS) (version 22.3.3.44 (official build))`

**Comment by kssenii** [comment]
Please try `database` instead of `db`

**Comment by oleg-savko** [comment]
> Please try `database` instead of `db`

thanks thats work! It whould be grate if that will be in docs)
