### ISSUE TITLE
I execute alter table xxxx MODIFY TTL event_date + toIntervalDay(30) delay error 21.4.5.46

### ISSUE THREAD

**Issue by mjh568412187** [ClickHouse/ClickHouse#36716]
Hello:
I have a problem
I found that the system.query_thread_log of my cluster has 2T data, I want to clean it up, my cluster currently has 7 nodes, I picked a node and executed it
alter table system.query_thread_log MODIFY TTL event_date + toIntervalDay(30);

The client returns:
Timeout exceeded while receiving data from server. Waited for 300 seconds, timeout is 300 seconds.
Cancelling query.

Then I went to show create table system.query_thread_log I found that the time has been changed to 30, I think it is ok and there is no problem
But something strange happens:
1) Read timed out appears when create table on cluster
      What exactly does this Read timed out mean? What are the reasons for this
2) When executing truncate table/alter table drop partition, a large number of cards were stuck on the server that executed alter table, resulting in as many as 81 processes on this server at that time.
3) When I go to the manual kill query, I can't kill it, I have to restart the server.

I give a screenshot of the status of the server when alter table system.query_thread_log was executed
<img width="801" alt="image" src="https://user-images.githubusercontent.com/26197792/165558327-42af45d3-f05a-4f85-87d5-d8de4597a5a7.png">

<img width="793" alt="image" src="https://user-images.githubusercontent.com/26197792/165558399-f01dc3b0-5a8b-4f83-bd69-d06cd25ab7f1.png">

<img width="794" alt="image" src="https://user-images.githubusercontent.com/26197792/165558499-d9d735d5-817e-493b-9a97-339f9adcd3aa.png">

<img width="809" alt="image" src="https://user-images.githubusercontent.com/26197792/165558570-5cc0244b-208d-415c-96f8-47b9eb9f08ad.png">

<img width="1606" alt="image" src="https://user-images.githubusercontent.com/26197792/165558663-d4e5975b-3d07-4fe5-9133-7c4831384c29.png">

<img width="817" alt="image" src="https://user-images.githubusercontent.com/26197792/165558729-b77a03d2-aaa9-48b8-9089-c16f8c98596d.png">

**Comment by mjh568412187** [comment]
I guess
1) Will it be because of the TTl deletion of a large amount of data? After all, there are 2T data to be deleted, which is related to the performance of zookeeper
2) This operation caused all changes to MUTATION to be problematic, and the server seemed to be in a hang state at the time

I need help

**Comment by den-crane** [comment]
query_thread_log does not use zookeeper because it's not replicated

**Comment by den-crane** [comment]
all of this is expected is some sense.

You should have drop the old partition, then apply MODIFY TTL.

**Comment by den-crane** [comment]
And 21.4 is obsolete. MODIFY TTL was improved in recent releases. Upgrade to 22.3.

**Comment by mjh568412187** [comment]
> all of this is expected is some sense.
> 
> You should have dropped the old partition, then apply MODIFY TTL.

Thank you very much for your suggestion:
I have a question
Why does my MODIFY TTL. operation cause the normal truncate table to be invalid? It takes a few hours or even gets stuck
Because truncate table is the ReplicatedMergeTree engine table and some use truncate table on cluster

At present, it is observed that I have performed operations such as MODIFY TTL that affects the cluster's truncate table.

**Comment by mjh568412187** [comment]
> all of this is expected is some sense.
> 
> You should have dropped the old partition, then apply MODIFY TTL.

Thank you very much for your suggestion:
From the monitoring point of view, the connection link has not been released. The reason for not releasing it is because the ck processlist in the background is all truncate table, alter table and other processing ReplicatedMergeTree engine tables, so I doubt whether it has something to do with zookeeper,
