### ISSUE TITLE
Query returns wrong result when reading constant from MergeTree with GROUP BY

### ISSUE THREAD

**Issue by EscaperLL** [ClickHouse/ClickHouse#36728]
### The problem is reproduced in 22.3.2.1

`CREATE TABLE test02( id Int,col1 String,col2 String,create_date Date ) ENGINE = MergeTree() order by id;

INSERT into  default.test02 (id,col1,col2,create_date) VALUES (4,'1','1','2021-12-31 23:59:59')`

sql:
`select version() as version from test02 group by version order by version

SELECT version() AS version
FROM test02
GROUP BY version
ORDER BY version ASC

Query id: e0eb958d-54ac-4444-9d11-341035adcc02

Ok.

0 rows in set. Elapsed: 0.011 sec.`

**Expected behavior**

> get the function result

**Triggering conditions**

1. Use merge tree table engine
2. Do not reference column elements in tables in functions
3. use group by

**Comment by tavplubix** [comment]
Simpler example:
```
dell9510 :) create table test03 (n int) engine=MergeTree order by n

Ok.

0 rows in set. Elapsed: 0.011 sec. 

dell9510 :) insert into test03 values (1)

Ok.

1 rows in set. Elapsed: 0.006 sec. 

dell9510 :) select version() from test03 group by 1

Ok.

0 rows in set. Elapsed: 0.008 sec.
```

**Comment by den-crane** [comment]
related https://github.com/ClickHouse/ClickHouse/issues/36608

**Comment by tavplubix** [comment]
Workaround (and the reason):
```
dell9510 :) set allow_experimental_projection_optimization=0

Ok.

0 rows in set. Elapsed: 0.002 sec. 

dell9510 :) select version() as version from test03 group by 1

┌─version──┐
│ 22.5.1.1 │
└──────────┘

1 rows in set. Elapsed: 0.011 sec. 

```

cc: @amosbird
