### ISSUE TITLE
Network Prefix data type

### ISSUE THREAD

**Issue by simPod** [ClickHouse/ClickHouse#36741]
**Use case**

I have these network prefixes which represent the same address+mask

`2001:b400:e000::/36`  
`2001:b400:e000:0:0:0:0:0/36`

I'd like to query ClickHouse `where column = '2001:b400:e000::/36'` and get also values with `2001:b400:e000:0:0:0:0:0/36`

**Describe the solution you'd like**

...therefore, this could be IMO achieved by having a datatype that represent the values `2001:b400:e000:0:0:0:0:0/36` and `2001:b400:e000::/36` as the same identical value. 

E.g. the same way as is done for IP address

`select toIPv6('2001:b400:e000:0:0:0:0:0') = toIPv6('2001:b400:e000::');` -> `true`

**Describe alternatives you've considered**

Storing ip and mask separately but that introduces complexity to select queries where one cannot simply to `WHERE column IN (:prefixes)` but `WHERE (column_a, column_b) IN ((:prefix1, :mask1), ...)`

**Comment by vdimir** [comment]
IP is comparable, so you can just use begin/end of IP address range
e.g.
```
:) SELECT arrayJoin([toIPv4('192.168.1.12'), toIPv4('127.0.0.0')]) as addr, toIPv4('192.168.0.0') <= addr and addr <= toIPv4('192.168.255.255') as m;

┌─addr─────────┬─m─┐
│ 192.168.1.12 │ 1 │
│ 127.0.0.0    │ 0 │
└──────────────┴───┘
```

**Comment by simPod** [comment]
That is clumsy as well. I'd have to store the value in two columns and filter against two values as well.

With your proposal my filter value `2001:b400:e000::/36` -> must be converted to 

```
start = 2001:b400:e000:0000:0000:0000:0000:0000
end = 2001:b400:efff:ffff:ffff:ffff:ffff:ffff
```

and then filtered like

`WHERE column_a <= :start and column_b >= :end`.

Now consider 100 filter values. Using IN is super-comfortable compared to  
`column_a <= :start1 and column_b >= :end1 OR ...... OR column_a <= :start100 and column_b >= :end100`.

**Comment by vdimir** [comment]
Another option is to load your ranges into [ip_trie](https://clickhouse.com/docs/en/sql-reference/dictionaries/external-dictionaries/external-dicts-dict-layout/#ip-trie) dictionary. It also doesn't cover all possible use-cases, but if your list of prefixes is changed not so often (because you need to reload the dictionary on change), it may suit.

<details>
<summary>Details</summary>

```
:) create table prefix_table (prefix String, value UInt32) ENGINE = Memory;

:) CREATE DICTIONARY somedict (
               prefix String,
               value UInt32
           )
           PRIMARY KEY prefix LAYOUT (ip_trie) LIFETIME (0) SOURCE(CLICKHOUSE(TABLE 'prefix_table'));

:) select dictHas('somedict', '192.168.1.12' :: IPv4);

SELECT dictHas('somedict', CAST('192.168.1.12', 'IPv4'))

Query id: 40be8822-6ec1-4758-86d7-44aeac942bd3

┌─dictHas('somedict', CAST('192.168.1.12', 'IPv4'))─┐
│                                                 0 │
└───────────────────────────────────────────────────┘

1 rows in set. Elapsed: 0.010 sec. 

:) insert into prefix_table VALUES ('192.168.0.0/16', 1);

:) SYSTEM RELOAD DICTIONARY somedict;
Ok.

:) select dictHas('somedict', '192.168.1.12' :: IPv4);

┌─dictHas('somedict', CAST('192.168.1.12', 'IPv4'))─┐
│                                                 1 │
└───────────────────────────────────────────────────┘

1 rows in set. Elapsed: 0.010 sec. 
```


</details>

**Comment by simPod** [comment]
Cool approach!

However, the data are rather dynamic. The use case is that it's connected to API endpoint and also user inputs.

**Comment by UnamedRus** [comment]
I guess, we just need two functions: `normalizeIPv6[Prefix]`

Which will remove excessive 0 from IPv6/Prefix

**Comment by simPod** [comment]
I guess it's so far the best option. Maybe something like compressIPv6Prefix.

I guess that it would work for IPv4 prefixes as well? `compressIPV4Prefix('::ffff:1.2.3.4')`

**Comment by vdimir** [comment]
`bitAnd` can be used to apply mask:
 
```
 :) select reinterpret(bitAnd(toIPv6('::ffff:127.1.1.1'), toIPv6('ffff:ffff:ffff:ffff:ffff:ffff:0000:0000')), 'IPv6');


┌─reinterpret(bitAnd(toIPv6('::ffff:127.1.1.1'), toIPv6('ffff:ffff:ffff:ffff:ffff:ffff:0000:0000')), 'IPv6')─┐
│ ::ffff:0.0.0.0                                                                                             │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

 :) select reinterpret(bitAnd(toIPv4('127.1.1.1'), toIPv4('255.255.0.0')), 'IPv4');


┌─reinterpret(bitAnd(toIPv4('127.1.1.1'), toIPv4('255.255.0.0')), 'IPv4')─┐
│ 127.1.0.0                                                               │
└─────────────────────────────────────────────────────────────────────────┘
```

But again it doesn't fully solve the problem when we have lots of prefixes with different length, query would be a rather complex as with `... <= ... and ... <=...`

**Comment by vdimir** [comment]
And we do have [`isIPAddressInRange`](https://clickhouse.com/docs/en/sql-reference/functions/ip-address-functions#isipaddressinrange) as well

**Comment by UnamedRus** [comment]
I guess we can just add function `isIPAddressInRanges(ip, [range])`

**Comment by simPod** [comment]
Yup, my proposal to add a datatype might be an overkill. I don't know much about clickhouse internals. 

Although, there's another aspect that storing prefix as a String might not be as effective as storing it as ipv6 + length (int) . Not sure if it's something worth considering on clickhouse side.

**Comment by simPod** [comment]
@alexey-milovidov is this a `won't-fix`?
