### ISSUE TITLE
insert_distributed_sync == 0 decreases INSERT parallelism?

### ISSUE THREAD

**Issue by jaroslawr** [ClickHouse/ClickHouse#36742]
I am trying to understand the difference in performance of parallel INSERT queries to a DISTRIBUTED table in a small Clickhouse cluster (4 servers, 2 shards, each shard replicated twice) when using `insert_distributed_sync == 0` and when using `insert_distributed_sync == 1` - do I understand correctly that:

- With `insert_distributed_sync == 0` all the INSERTs issued in parallel will be queued on disk and then StorageDistributedDirectoryMonitor will pick up one file at a time, do a synchronous remote insert, and hence effectively serialize the INSERTs

- Only with `insert_distributed_sync == 1` the INSERTs will actually be processed in parallel

?

**Comment by melvynator** [comment]
Hey thank you for your question and interest in ClickHouse.

So in both case, the insertion is parralelized the only difference will be when it comes to acknowledgment.

You can have more info here: https://github.com/ClickHouse/ClickHouse/blob/1cbdc1ef3a6d37adc2af55e988dce8ea4958574b/src/Storages/Distributed/DistributedSink.cpp#L420-L510

**Comment by jaroslawr** [comment]
@melvynator Doesn't this code only prove it's parallelised across shards in both cases? We have only 2 shards. Let's say I issue 16 INSERTs in parallel, does it work like this:

- with `insert_distributed_sync == 1` all the inserts would be running in parallel AND each insert would be parallelised across shards, so the level of parallelism would be 16 INSERTs * 2 shards = 32 threads issuing `write()` calls to disk

- with `insert_distributed_sync == 0` all the inserts would be serialized to disk, then one INSERT at a time would be issued (due to DirectoryMonitor processing one file at a time) and then parallelised across shards, so that there are only 2 threads issueing `write()` calls to disk?

?

**Comment by jaroslawr** [comment]
@alexey-milovidov Many thanks for the detailed answer!
