### ISSUE TITLE
How to do clickhouse keeper setup in 22.3.3 version

### ISSUE THREAD

**Issue by shubham696** [ClickHouse/ClickHouse#36750]
I'm using clickhouse/clickhouse-server 22.3.3 image to use clickhouse keeper. Have followed [this](https://kb.altinity.com/altinity-kb-setup-and-maintenance/altinity-kb-zookeeper/clickhouse-keeper/) article by replacing my remote server ips in hostname 1 and 2 respectively. But I'm getting the issue->
           1) DB::Exception: All connection tries failed while connecting to ZooKeeper. nodes: x.x.x.x:2181 .
           2) RaftInstance: peer (2) response error: failed to connect to peer 2, x.x.x.x:8123, Election timeout, initiate leader election
When I run command **sudo netstat -tlnp** i can see services running at 8123, 9000 but cant see 2181

**Comment by shubham696** [comment]
> @shubham696 can you please try the official guides https://clickhouse.com/docs/en/guides/sre/clickhouse-keeper

@gingerwizard  I have tried from above documentation but it's failing with following error logs:

`2022.04.28 15:43:17.366085 [ 255 ] {} <Error> virtual bool DB::DDLWorker::initializeMainThread(): Code: 999. Coordination::Exception: All connection tries failed while connecting to ZooKeeper. nodes: x.x.x.1:9181, x.x.x.2:9181, x.x.x.3:9181
Poco::Exception. Code: 1000, e.code() = 111, Connection refused (version 22.3.3.44 (official build)), x.x.x.1:9181
Poco::Exception. Code: 1000, e.code() = 111, Connection refused (version 22.3.3.44 (official build)), x.x.x.2:9181
Poco::Exception. Code: 1000, e.code() = 111, Connection refused (version 22.3.3.44 (official build)), x.x.x.3:9181
Poco::Exception. Code: 1000, e.code() = 111, Connection refused (version 22.3.3.44 (official build)), x.x.x.1:9181
Poco::Exception. Code: 1000, e.code() = 111, Connection refused (version 22.3.3.44 (official build)), x.x.x.2:9181
Poco::Exception. Code: 1000, e.code() = 111, Connection refused (version 22.3.3.44 (official build)), x.x.x.3:9181
Poco::Exception. Code: 1000, e.code() = 111, Connection refused (version 22.3.3.44 (official build)), x.x.x.1:9181
Poco::Exception. Code: 1000, e.code() = 111, Connection refused (version 22.3.3.44 (official build)), x.x.x.2:9181
Poco::Exception. Code: 1000, e.code() = 111, Connection refused (version 22.3.3.44 (official build)), x.x.x.3:9181
 (Connection loss). (KEEPER_EXCEPTION), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xb3712fa in /usr/bin/clickhouse
1. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error, int) @ 0x16cf8375 in /usr/bin/clickhouse
2. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error) @ 0x16cf86b6 in /usr/bin/clickhouse
3. Coordination::ZooKeeper::connect(std::__1::vector<Coordination::ZooKeeper::Node, std::__1::allocator<Coordination::ZooKeeper::Node> > const&, Poco::Timespan) @ 0x16d3f9a5 in /usr/bin/clickhouse
4. Coordination::ZooKeeper::ZooKeeper(std::__1::vector<Coordination::ZooKeeper::Node, std::__1::allocator<Coordination::ZooKeeper::Node> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Poco::Timespan, Poco::Timespan, Poco::Timespan, std::__1::shared_ptr<DB::ZooKeeperLog>) @ 0x16d3dfdf in /usr/bin/clickhouse
5. zkutil::ZooKeeper::init(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x16cfadee in /usr/bin/clickhouse
6. zkutil::ZooKeeper::ZooKeeper(Poco::Util::AbstractConfiguration const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::ZooKeeperLog>) @ 0x16cfd3ad in /usr/bin/clickhouse
7. void std::__1::allocator<zkutil::ZooKeeper>::construct<zkutil::ZooKeeper, Poco::Util::AbstractConfiguration const&, char const (&) [10], std::__1::shared_ptr<DB::ZooKeeperLog> >(zkutil::ZooKeeper*, Poco::Util::AbstractConfiguration const&, char const (&) [10], std::__1::shared_ptr<DB::ZooKeeperLog>&&) @ 0x154c7a9b in /usr/bin/clickhouse
8. DB::Context::getZooKeeper() const @ 0x154a66b6 in /usr/bin/clickhouse
9. DB::DDLWorker::getAndSetZooKeeper() @ 0x154ff2ec in /usr/bin/clickhouse
10. DB::DDLWorker::initializeMainThread() @ 0x1550fe08 in /usr/bin/clickhouse
11. DB::DDLWorker::runMainThread() @ 0x154fcbc1 in /usr/bin/clickhouse
12. ThreadFromGlobalPool::ThreadFromGlobalPool<void (DB::DDLWorker::*)(), DB::DDLWorker*>(void (DB::DDLWorker::*&&)(), DB::DDLWorker*&&)::'lambda'()::operator()() @ 0x15511077 in /usr/bin/clickhouse
13. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xb418757 in /usr/bin/clickhouse
14. ? @ 0xb41c2dd in /usr/bin/clickhouse
15. ? @ 0x7fc314ecf609 in ?
16. __clone @ 0x7fc314df4163 in ?
 (version 22.3.3.44 (official build))
`

When I try to check zookeeper table (step 6 from part 1)
getting above error with: `Code: 999. DB::Exception: Received from localhost:9000.`


note: My server support IpV6

**Comment by shubham696** [comment]
> @shubham696 could you share the config for both `<keeper_server>` and `<zookeeper>` sections? could you check from this server that it is able to connect to the port `9181` to other servers? something like this: `echo ruok | nc chnode2.marsnet.local 9181; echo` *use same name that was used in the clickhouse-keeper config.

@e-mars  thanks for the fast reply
I have tried **echo ruok | nc chnode2.marsnet.local 9181; echo** not getting any response/empty response

keeper_server

```
<keeper_server>

    <tcp_port>9181</tcp_port>
    <server_id>1</server_id>
    <log_storage_path>/var/lib/clickhouse/coordination/log</log_storage_path>
    <snapshot_storage_path>/var/lib/clickhouse/coordination/snapshots</snapshot_storage_path>
    <coordination_settings>
        <operation_timeout_ms>10000</operation_timeout_ms>
        <session_timeout_ms>30000</session_timeout_ms>
        <raft_logs_level>warning</raft_logs_level>
    </coordination_settings>
    <raft_configuration>
        <server>
            <id>1</id>
            <hostname>x.x.x.1</hostname>
            <port>9444</port>
        </server>
        <server>
            <id>2</id>
            <hostname>x.x.x.2</hostname>
            <port>9444</port>
        </server>
        <server>
            <id>3</id>
            <hostname>x.x.x.3</hostname>
            <port>9444</port>
        </server>
    </raft_configuration>
</keeper_server>
```
zookeeper

```
<clickhouse>
   <zookeeper>
        <node>
            <host>x.x.x.1</host>
            <port>9181</port>
        </node>
        <node>
            <host>x.x.x.2</host>
            <port>9181</port>
        </node>
        <node>
            <host>x.x.x.3</host>
            <port>9181</port>
        </node>
    </zookeeper>
</clickhouse>
```

**Comment by e-mars** [comment]
@shubham696 the configuration looks fine.
if the command, `echo ruok | nc <your_IP> 9181; echo` did not respond with anything, then either the port is blocked on the target machine or clickhouse-keeper service is not running.

would it be possible to temporarily stop any firewalls running on these nodes and test?
also, for each machine, ensure that `<server_id>` is different for each one.

**Comment by shubham696** [comment]
> @shubham696 the configuration looks fine. if the command, `echo ruok | nc <remote_IP> 9181; echo` did not respond with anything, then either the port is blocked on the target machine or clickhouse-keeper service is not running.
> 
> would it be possible to temporarily stop any firewalls running on these nodes and test? also, for each machine, ensure that `<server_id>` is different for each one.

@e-mars i have different server_id for all the three.
will check if possible by turning off firewalls

- I have checked all the services (systemctl list-units --type=service --all) are running on the system I can't find clickhouse-keeper in it.

**Comment by e-mars** [comment]
are you using an official prepackaged binary (deb, rpm, etc.)? 
it's already bundled in with default install, the clickhouse keeper won't show separately in the services. will only show `clickhouse-server.service`.

**Comment by shubham696** [comment]
> are you using an official prepackaged binary (deb, rpm, etc.)? it's already bundled in with default install, the clickhouse keeper won't show separately in the services. will only show `clickhouse-server.service`.

@e-mars  yes, I'm using official build 22.3.3.44```docker pull clickhouse/clickhouse-server:22.3.3.44```.
 You can see that in my error log ```version 22.3.3.44 (official build)```

**Comment by shubham696** [comment]
It was a mistake on my side. Dint use the 9181,9444 port in docker-compose.yml.
Sorry for the trouble and thanks for helping out
