### ISSUE TITLE
Keep types of subcolumns while converting from `Tuple` to `Object`

### ISSUE THREAD

**Issue by CurtizJ** [ClickHouse/ClickHouse#36761]
In this example it's better to keep type of subcolumn `value`, since it specified explicitly.

```sql
DROP TABLE IF EXISTS test_json;
SET allow_experimental_object_type = 1;

CREATE TABLE test_json
(
    `id` Int32,
    `obj` JSON
)
ENGINE = MergeTree
ORDER BY tuple();

INSERT INTO test_json VALUES (1, ('a', 1)::Tuple(key String, value Int32));

SELECT toTypeName(obj) FROM test_json;

--  better to be Int32 as declared

┌─toTypeName(obj)───────────────┐
│ Tuple(key String, value Int8) │
└───────────────────────────────┘
```

**Comment by zhicwu** [comment]
Thanks @CurtizJ. Just so be clear, the declared type will be only considered for new sub-columns, right? Does it make sense to you to support additional case like converting an existing sub-column from `Int8` to `Int32`?

**Comment by awakeljw** [comment]
I have a question,  if we keep every sub-columns different as declared type? take a example, if we  insert ('a', 1)::Tuple(key String, value Int32) first and then insert insert ('a', 1)::Tuple(key String, value Int8) , we should have a  Tuple(key String, value Int32) and  Tuple(key String, value Int8) ?
