### ISSUE TITLE
zxid overflow cause table readonly long time (table has a large merge)

### ISSUE THREAD

**Issue by freedomDR** [ClickHouse/ClickHouse#36775]
When zookeeper of zxid overflow, zookeeper will leader election, ReplicatedMergeTreeRestartingThread will check zookeeper is expired. If there have one very large merge task is runing(about 10 billion records merge), table will be readonly in very long time, we can not execute insert query. This is diffcult to reproduce it.

**Comment by UnamedRus** [comment]
clickhouse-keeper doesn't have `zxid overflow` problem

**Comment by freedomDR** [comment]
sorry [pr25306](https://github.com/ClickHouse/ClickHouse/pull/25306) always fix it....
