### ISSUE TITLE
How many UNION ALL can be used in a SQL statement?

### ISSUE THREAD

**Issue by LGDHuaOPER** [ClickHouse/ClickHouse#36771]
I have hundreds of tables, and I need to query data from these hundreds of tables. How many UNION ALL can be used in a SQL statement in this case?

**Comment by LGDHuaOPER** [comment]
Thank you very much for your reply!We have used CH for more than two months, and we should continue to use it later!
Having said that, it is a little regrettable to support up to 100 ***UNION ALL***. I think I may need an additional programming workload to solve this kind of problem.

**Comment by alexey-milovidov** [comment]
@LGDHuaOPER You misunderstood the answer. There is no limit on the number of UNION ALL.
