### ISSUE TITLE
Add miscellaneous function `displayName()`

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#36770]
**Use case**

It is better than hostname in the following example:
```
SELECT hostname() AS host, event_time, round(value, 2) AS v, bar(v, 0, 10, 100) FROM system.asynchronous_metric_log WHERE event_date >= yesterday() AND event_time >= now() - 300 AND metric = 'LoadAverage1' ORDER BY host, event_time
```

Because hostnames can be non-informative like `ip-172-31-5-46`.

**Comment by HeenaBansal2009** [comment]
@alexey-milovidov , I am willing to take this up.
Here, Are  we intend to change the existing function name "hostname()" to displayName() ?

**Comment by alexey-milovidov** [comment]
No, these will be two separate functions.
Maybe you will be interested in implementing access control for functions.
So, you will be able to give access to displayName and remove access for hostname and fqdn.

**Comment by HeenaBansal2009** [comment]
> No, these will be two separate functions.
> Maybe you will be interested in implementing access control for functions.
> So, you will be able to give access to displayName and remove access for hostname and fqdn.

@alexey-milovidov , What kind of output is expected from new function displayName(). I would like to understand the  difference in output  from this new function and hostname() and FQDN() which returns 'hostname -f' output.

**Comment by alexey-milovidov** [comment]
See `server_display_name` inside the code and `display_name` in config.xml

**Comment by SakshiT25** [comment]
Hi, I'm interested in working on this feature. Kindly guide me for the further steps.
