### ISSUE TITLE
Clickhouse-server returns exception given requests with large body size

### ISSUE THREAD

**Issue by SneedusSnake** [ClickHouse/ClickHouse#36783]
When I'm trying to insert data, where one particular field is a large string (3mb), through a curl request I have a following exception returned from server:

`Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = HTML Form Exception: Field value too long (version 21.8.15.7)`

I tried passing 'max_query_size=100000000' and other such options, like http_max_field_value, as query parameters and also in request's body to no avail. Is there some kind of default limit setting that prevents me from passing a large set of data to server?

**Comment by gingerwizard** [comment]
Have you tried [http_max_field_value_size](https://github.com/ClickHouse/ClickHouse/blob/7dc084419e16c52650088a3ae948850d94c4edf5/src/Core/Settings.h#L272)?

This [should be ](https://github.com/ClickHouse/ClickHouse/pull/25296) available in 21.8

**Comment by SneedusSnake** [comment]
> Have you tried [http_max_field_value_size](https://github.com/ClickHouse/ClickHouse/blob/7dc084419e16c52650088a3ae948850d94c4edf5/src/Core/Settings.h#L272)?
> 
> This [should be ](https://github.com/ClickHouse/ClickHouse/pull/25296) available in 21.8

Yes, I tried sending this as a query param, still got the same result.

**Comment by den-crane** [comment]
@SneedusSnake Proper Insert does not have size limitations. You can insert many TB of data.
Show an example how you insert data.

**Comment by gingerwizard** [comment]
thanks i only asked as you originally stated `I tried passing 'max_query_size=100000000' and other such options, like http_max_field_value` - i assume `http_max_field_value` was a misspelling of the parameter.

Can you provide the exact command how you are using to insert? Specifically the post headers and content type

Insert size is unlimited e.g.
```
CREATE TABLE test (value String) ENGINE=MergeTree() ORDER BY tuple()
base64 /dev/urandom | head -c 3000000 > file.txt
cat file.txt | curl 'http://localhost:8123/?query=INSERT%20INTO%20test%20FORMAT%20RawBLOB' --data-binary @-
```

The above error suggests you are passing the values in the headers.

**Comment by SneedusSnake** [comment]
```
  $headers = [
          'X-ClickHouse-User: ' . $_ENV['CLICKHOUSE_USER'],
          'X-ClickHouse-Key: ' . $_ENV['CLICKHOUSE_PASSWORD'],
      ];

```
    $url = "{$_ENV['CLICKHOUSE_HOST']}:{$_ENV['CLICKHOUSE_PORT']}/?database= 
    {$_ENV['CLICKHOUSE_DB']}&http_max_field_value_size=1000000000";

    $handler = curl_init();

    curl_setopt($handler, CURLOPT_URL, $url);
    curl_setopt($handler, CURLOPT_SSL_VERIFYPEER, true);
    curl_setopt($handler, CURLOPT_POST, true);
    curl_setopt($handler, CURLOPT_POSTFIELDS, ['query' => $query]);
    curl_setopt($handler, CURLOPT_HTTPHEADER, $headers);

    curl_exec($handler);


This is how I form my request.

**Comment by den-crane** [comment]
@SneedusSnake Show an example of your insert. 
Do you have functions in values section? now(), generateUUID.... ?

**Comment by SneedusSnake** [comment]
Im not setting content-type explicitly, but debugging curl request shows me that it sets it to Content-Type: multipart/form-data;

**Comment by genzgd** [comment]
It appears that `http_max_field_value_size` is a setting that must go into the default profile and only takes effect on server restart.  Can you try increasing that value in your `default` profile and restarting your server?

**Comment by DerekChia** [comment]
This issue can be reproduced below. The solution is to update setting in the default profile and restart. 

```
echo "<clickhouse><profiles><default><http_max_field_value_size>100</http_max_field_value_size></default></profiles></clickhouse>" > http_max_field_value_size.xml

docker run -d --name clickhouse-server -p 8123:8123 clickhouse/clickhouse-server:24.8 

docker cp http_max_field_value_size.xml clickhouse-server:/etc/clickhouse-server/users.d/http_max_field_value_size.xml

docker restart clickhouse-server

SHORTVALUE=$(printf "%0.sa" $(seq 1 99))

LONGVALUE=$(printf "%0.sa" $(seq 1 101))


❯ curl "http://localhost:8123?param_foo=$SHORTVALUE" -d 'select {foo:String}'

aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
❯ curl "http://localhost:8123?param_foo=$LONGVALUE" -d 'select {foo:String}'

Poco::Exception. Code: 1000, e.code() = 0, HTML Form Exception: Field value too long (version 24.8.5.115 (official build))
```
