### ISSUE TITLE
Documentation for `CREATE SETTINGS PROFILE` is incomplete

### ISSUE THREAD

**Issue by rkozlo** [ClickHouse/ClickHouse#36793]
Version 22.3
Create/alter settings profile requiere any SETTINGS passed to make READONLY|WRITABLE working.
```
host :) create settings profile readonly_test READONLY

Syntax error: failed at position 39 ('READONLY'):

create settings profile readonly_test READONLY

Expected one of: token, Comma, SETTINGS, ON, TO, end of query

host :) create settings profile readonly_test SETTINGS READONLY

Syntax error: failed at position 56 (end of query):

create settings profile readonly_test SETTINGS READONLY 

Expected one of: token, Dot, Equals, MIN, MAX, READONLY, WRITABLE, end of query
```
The same for alter.
It can be workarounded by adding any setting for this query

**Comment by tavplubix** [comment]
It works this way, `READONLY/WRITABLE` modifier belongs to each setting:
```
dell9510 :) CREATE PROFILE sp SETTINGS max_memory_usage=5000000 READONLY, max_threads=8 WRITABLE;

CREATE SETTINGS PROFILE sp SETTINGS max_memory_usage = 5000000 READONLY, max_threads = 8 WRITABLE

Query id: 9f12693e-40e2-4776-a21c-6ba6f43523ca

Ok.

0 rows in set. Elapsed: 0.003 sec.
```

AFAIK this `READONLY/WRITABLE` modifier means "(do not) allow to change the specified setting value", so it does not make sense to specify these modifiers without any settings. What are you trying to do by query like `create settings profile readonly_test READONLY`? Probably you meant something like `create settings profile readonly_test settings readonly=1`. Unfortunately, our documentation is incomplete, I had to take a look at code to find out how `CREATE PROFILE` queries work.

**Comment by rkozlo** [comment]
Ahh ok. I thought it is applicatable on access level to specific users for readonly mode. Actually how it works now has more sense. I'll do it on old way with grants then.

**Comment by DanRoscigno** [comment]
https://clickhouse.com/docs/en/sql-reference/statements/create/settings-profile/
