### ISSUE TITLE
Support Kusto Query Language (KQL)

### ISSUE THREAD

**Issue by larryluogit** [ClickHouse/ClickHouse#36806]
**Overview**

Kusto Query Language is a powerful tool to explore data and discover patterns, identify anomalies and outliers, create statistical modeling, and more. The query uses schema entities that are organized in a hierarchy similar to SQL's: databases, tables, and columns.
A Kusto query is a read-only request to process data and return results. The request is stated in plain text, using a data-flow model that is easy to read, author, and automate. Kusto queries are made of one or more query statements.

**Use case**

The primary use case is to query massive amounts of streamed data like application logs  stored in ClickHouse.

**Describe the solution you'd like**

Support Kusto Query Language (KQL) as a native read-only data access query language that can be used in all read-only data access scenarios.

**Additional context**

[Kusto Query Language Reference](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/)

**Comment by UnamedRus** [comment]
Just curious, which benefits is add compared to SQL?

Especially compared to SQL + match_recognize 

https://modern-sql.com/feature/match_recognize

**Comment by larryluogit** [comment]
@UnamedRus 
KQL was designed with the “simple things must be simple” philosophy in mind. The main design goals for KQL were: low barrier of entry, easy to read syntax, ability to “scale” the language and provide a smooth transition from simple one-liners to complex data processing “scripts”.

This makes generating KQL query relatively easy, especially in complex data processing scenarios. Further more, explaining a data processing procedure written in KQL is much easier comparing to SQL.
