### ISSUE TITLE
Code: 12. DB::Exception: Parameters start = 0, length = 2 are out of bound in ColumnVector<T>::insertRangeFrom method (data.size() = 1). (PARAMETER_OUT_OF_BOUND)

### ISSUE THREAD

**Issue by bytadaniel** [ClickHouse/ClickHouse#36814]
**Describe the unexpected behaviour**
Since we try to connect Kafka to our yandex cloud managed clickhouse cluster, we face same error everytime sending messages to Kafka

For example, I had copied DDL queries from this guide https://altinity.com/blog/2020/5/21/clickhouse-kafka-engine-tutorial to exclude a possibility of participation in the creating error myself.

`CREATE TABLE prod.readings (
    readings_id Int32 Codec(DoubleDelta, LZ4),
    time DateTime Codec(DoubleDelta, LZ4),
    date ALIAS toDate(time),
    temperature Decimal(5,2) Codec(T64, LZ4)
) Engine = MergeTree
PARTITION BY toYYYYMM(time)
ORDER BY (readings_id, time)`

`CREATE TABLE prod.readings_queue (
    readings_id Int32,
    time DateTime,
    temperature Decimal(5,2)
)
ENGINE = Kafka
SETTINGS kafka_broker_list = 'rc1b-20ue8a299ijt7c6b.mdb.yandexcloud.net:9091',
      kafka_topic_list = 'remaining_0_1_2',
      kafka_group_name = 'ch-remaining-group',
      kafka_format = 'CSV',
      kafka_max_block_size = 1048576
`

`CREATE MATERIALIZED VIEW prod.readings_queue_mv TO prod.readings AS
SELECT readings_id, time, temperature
FROM prod.readings_queue`

Following the attached guide, I am sending messages to kafka like that
`(async function () {
    await kafka.connection()
    let num = 0
    while (num <= 10) {
        console.log({ num })
        await kafka.producer.sendMessage('remaining_0_1_2', `1,"2020-05-16 23:55:44",14.2`)
        num++
    }
})()`
*I had tried to send as string, Buffer, JSONEachRow, CSV, TabSeparated format, but no one is not working fine 

In conclusion, I face this error
{
  "component": "void DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::routine(DB::TaskRuntimeDataPtr) [Queue = DB::MergeMutateRuntimeQueue]",
  "hostname": "rc1c-nzwzwydtcuhw3jl3.mdb.yandexcloud.net",
  "message": "Code: 12. DB::Exception: Parameters start = 0, length = 2 are out of bound in ColumnVector<T>::insertRangeFrom method (data.size() = 1). (PARAMETER_OUT_OF_BOUND), Stack trace (when copying this message, always include the lines below):\\n\\n0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xb6fa67a in /usr/bin/clickhouse\\n1. DB::ColumnVector<unsigned long>::insertRangeFrom(DB::IColumn const&, unsigned long, unsigned long) @ 0xb5f99a0 in /usr/bin/clickhouse\\n2. DB::ColumnTuple::insertRangeFrom(DB::IColumn const&, unsigned long, unsigned long) @ 0x16566170 in /usr/bin/clickhouse\\n3. DB::ColumnArray::insertRangeFrom(DB::IColumn const&, unsigned long, unsigned long) @ 0x164aea8f in /usr/bin/clickhouse\\n4. DB::MergeTreeDataPartWriterCompact::write(DB::Block const&, DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 15ul, 16ul> const*) @ 0x16aac8e8 in /usr/bin/clickhouse\\n5. DB::MergedBlockOutputStream::write(DB::Block const&) @ 0x16b91c40 in /usr/bin/clickhouse\\n6. DB::MergeTask::ExecuteAndFinalizeHorizontalPart::executeImpl() @ 0x169e8b09 in /usr/bin/clickhouse\\n7. DB::MergeTask::ExecuteAndFinalizeHorizontalPart::execute() @ 0x169e880b in /usr/bin/clickhouse\\n8. DB::MergeTask::execute() @ 0x169ee1fa in /usr/bin/clickhouse\\n9. DB::MergePlainMergeTreeTask::executeStep() @ 0x169ddb8c in /usr/bin/clickhouse\\n10. DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::routine(std::__1::shared_ptr<DB::TaskRuntimeData>) @ 0xb6d1045 in /usr/bin/clickhouse\\n11. DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::threadFunction() @ 0xb6d0a8e in /usr/bin/clickhouse\\n12. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0xb7a8afa in /usr/bin/clickhouse\\n13. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&)::'lambda'()::operator()() @ 0xb7aaae4 in /usr/bin/clickhouse\\n14. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xb7a5f27 in /usr/bin/clickhouse\\n15. ? @ 0xb7a995d in /usr/bin/clickhouse\\n16. start_thread @ 0x76db in /lib/x86_64-linux-gnu/libpthread-2.27.so\\n17. __clone @ 0x12161f in /lib/x86_64-linux-gnu/libc-2.27.so\\n (version 22.4.2.1 (official build))",
  "query_id": "",
  "severity": "Error",
  "thread": "1379090"
}
And have no one row in table readings
Guys, I have no idea why I can't insert rows through Kafka. It should work, but it doesn't

**Comment by bytadaniel** [comment]
Additionally, i've created same configuration with kafka_format = 'JSONEachRow' and have sent 10 messages
`{"readings_id":1,"time":"2020-05-16 23:55:44","temperature":14.2}`, bot got only 6 rows. Message queue is empty.
After that each attempt to send message leads to error i ve explained above

**Comment by genzgd** [comment]
I assume you haven't changed the settings of `deduplicate_blocks_in_dependent_materialized_views`.  You might start by sending data that is different and see if deduplication is affecting the process at some point.  That said your error doesn't look like it's related to deduplication since it's happening in the background merge.

Are you sure that the error above is actually related to your Kafka inserts and not some other table?  What is in the `system.merges` table?

**Comment by bytadaniel** [comment]
> I assume you haven't changed the settings of `deduplicate_blocks_in_dependent_materialized_views`. You might start by sending data that is different and see if deduplication is affecting the process at some point. That said your error doesn't look like it's related to deduplication since it's happening in the background merge.
> 
> Are you sure that the error above is actually related to your Kafka inserts and not some other table? What is in the `system.merges` table?

Hi! Thank you for your reply. There is no any info in `system.merges` related to tables `readings_queue`, `readings`, `readings_queue_mv`

What about error, it may be indirectly dependent, because we faced this error when started to integrate kafka in our project and I get this exactly when try sending messages to kafka

**Comment by bytadaniel** [comment]
I have just inspected tracing of this error and it seems you to be right. This error has no relation with Kafka, because it is throwing every second

**Comment by bytadaniel** [comment]
Despite of this fact, I have to now how to fix this error

**Comment by genzgd** [comment]
It's possible you have something like a corrupted part file.  There should be some indication of what it is in the `system.merges` table or possibly the `system.mutations` table where the `is_done` column is 0.

**Comment by bytadaniel** [comment]
> It's possible you have something like a corrupted part file. There should be some indication of what it is in the `system.merges` table or possibly the `system.mutations` table where the `is_done` column is 0.

`system.merges` is completely empty and `system.mutations` with flag is_done=0 does not contain any rows in select result

**Comment by bytadaniel** [comment]
Thank you for help. I have found the cause of this error. There was a table, which had `Map` as  primary key and `ReplacingMergeTree` engine. Trying to deduplicate column was throwing error for long time.
I had truncated this table and error stopped to throw
