### ISSUE TITLE
Client --query run mode write number of rows inserted to stdout on exit

### ISSUE THREAD

**Issue by reflection** [ClickHouse/ClickHouse#3682]
We insert by running `clickhouse client --query INSERT INTO <table> FORMAT CSV` and writing the next batch of rows to stdin.  Unfortunately, when the client exits, we do not know how many rows were actually inserted.

Just a number printed to stdout on exit would be fine.  Compare ClickHouse to Postgres:
```
$ clickhouse-client --query "INSERT INTO test VALUES (1)"
$
```
```
$ psql -U postgres -d config -c "INSERT INTO test VALUES (1)"
INSERT 0 1
$
```

**Comment by alexey-milovidov** [comment]
We can do it under `--progress` option. This will not break backward compatibility.
