### ISSUE TITLE
Type JSON seems not compatible with the scenarios of JSON with keys start with digit.

### ISSUE THREAD

**Issue by sunnyfun888** [ClickHouse/ClickHouse#36827]
Use this way is OK:

```
CREATE TABLE games1 (id UInt64 ,data_raw String) ENGINE = MergeTree ORDER BY id;

INSERT INTO games1(id, data_raw) VALUES(1, '{"111":"v1"}');

SELECT JSONExtractString(data_raw, '111') FROM games1;
```
You can get:

┌─JSONExtractString(data_raw, '111')──┐
│ v1　　　　　　　　　　　　　　　　│
└────────────────────── ──┘

But use this way, can't even do the insert:
```
CREATE TABLE games2 (id UInt64 ,data_json JSON) ENGINE = MergeTree ORDER BY id;

INSERT INTO games2(id, data_json) VALUES(1, '{"111":"v1"}');
```
Get error, DB::Exception: Explicitly specified names of tuple elements cannot start with digit. (BAD_ARGUMENTS) (version 22.4.4.7 (official build))

**Does it reproduce on recent release?**

22.4.4.7

**Comment by CurtizJ** [comment]
Fixed in #36544.
