### ISSUE TITLE
LowCardinality->ArrowDictionary Invalid Output

### ISSUE THREAD

**Issue by mhconradt** [ClickHouse/ClickHouse#36832]
When using the `Arrow` output format, `LowCardinality(String)` columns and `output_format_arrow_low_cardinality_as_dictionary=1`, an invalid result is produced when the number of distinct values in the dictionary exceeds 128. It's invalid because the data type of the indices is always `int8` even when there are more than 256 values. This is bad because each distinct value needs a distinct index and by the pigeonhole principle if there are > 256 dictionary values and only 256 indices, some indices will represent multiple dictionary values. Moreover, if the number of distinct values is greater than 128, this results in some `int8` values that are negative (since the most significant bit of the uint8 is 1 and this maps to the sign in int8), and all indices must be positive.

**Does it reproduce on recent release?**

Reproduces on ClickHouse 22.4.4.

**How to reproduce**

* Which ClickHouse server version to use
22.4
* Which interface to use, if matters
Can use ./clickhouse client

```
$ ./clickhouse client -q "select * from ftx_trades;" -f Arrow --output_format_arrow_low_cardinality_as_dictionary 0 > trades.feather                                                                                                                                 (base)
$ ./clickhouse client -q "select * from ftx_trades;" -f Arrow --output_format_arrow_low_cardinality_as_dictionary 1 > trades_dict.feather
```

`trades_dict.feather` will contain valid Arrow data (using a `string` type for the market), but `trades.feather` will not (it's dictionary type is incorrect).

* `CREATE TABLE` statements for all tables involved
```
CREATE TABLE ftx_trades (
  market LowCardinality(String),
  time DateTime64(9),
  id Int64,
  price Float64,
  size Float64,
  side LowCardinality(String),
  liquidation UInt8,
  INDEX time_range (time) TYPE minmax GRANULARITY 1
) ENGINE = MergeTree()
PRIMARY KEY (market, time)
ORDER BY (market, time, id);
```
* Sample data for all these tables

[example_trades.csv](https://github.com/ClickHouse/ClickHouse/files/8597765/example_trades.csv)

* Non-default settings

`output_format_arrow_low_cardinality_as_dictionary=1`

* Queries to run that lead to unexpected result

`select * from ftx_trades;` (any query that references the `market` column).

**Expected behavior**

Each distinct value in ClickHouse must have a unique positive index in the Arrow dictionary.

In the meantime I'm going to not set `output_format_arrow_low_cardinality_as_dictionary=1`

**Comment by mhconradt** [comment]
This is kind of unrelated, but it would be nice if `String` mapped to Arrow's string type instead of its binary type.

**Comment by alexey-milovidov** [comment]
@mhconradt ClickHouse String can contain arbitrary sequence of bytes, including zero bytes, as well as UTF-8 text.
Arrow's string type can only contain UTF-8 text.

https://arrow.apache.org/docs/cpp/api/datatype.html
> enumerator STRING
    UTF8 variable-length string as List<Char>

**Comment by alexey-milovidov** [comment]
Does Arrow support more than 256 dictionary entries?

**Comment by mhconradt** [comment]
Yes it does:
```
from string import ascii_uppercase

import pandas as pd
import pyarrow as pa

strings = pd.Categorical([a + b for a in ascii_uppercase for b in
                          ascii_uppercase])
print(strings)

"""
['AA', 'AB', 'AC', 'AD', 'AE', ..., 'ZV', 'ZW', 'ZX', 'ZY', 'ZZ']
Length: 676
Categories (676, object): ['AA', 'AB', 'AC', 'AD', ..., 'ZW', 'ZX', 'ZY', 'ZZ']
"""

array = pa.DictionaryArray.from_pandas(strings)
print(array.type, array)

"""
dictionary<values=string, indices=int16, ordered=0>
-- dictionary:
  [
    "AA",
    "AB",
    "AC",
    "AD",
    "AE",
    "AF",
    "AG",
    "AH",
    "AI",
    "AJ",
    ...
    "ZQ",
    "ZR",
    "ZS",
    "ZT",
    "ZU",
    "ZV",
    "ZW",
    "ZX",
    "ZY",
    "ZZ"
  ]
-- indices:
  [
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    ...
    666,
    667,
    668,
    669,
    670,
    671,
    672,
    673,
    674,
    675
  ]
"""
```

**Comment by andykernahan** [comment]
This issue still occurs when the number of distinct values exceeds 128.

Using the method in [#37043](../pull/37043#issuecomment-1139570143), we can reproduce it by inserting precisely 128 distinct values:

```sql
$ clickhouse-client --version
ClickHouse client version 23.3.2.37 (official build).

:) select version()

SELECT version()

Query id: a0e88793-fb36-4494-8ac1-aa608c584513

┌─version()─┐
│ 23.3.2.37 │
└───────────┘

1 row in set. Elapsed: 0.002 sec.

:) insert into function file(data.arrow) select toLowCardinality(toString(number)) as x from numbers(128) settings output_format_arrow_low_cardinality_as_dictionary=1

INSERT INTO FUNCTION file(data.arrow)
SETTINGS output_format_arrow_low_cardinality_as_dictionary = 1
SELECT toLowCardinality(toString(number)) AS x
FROM numbers(128)
SETTINGS output_format_arrow_low_cardinality_as_dictionary = 1

Query id: c3231b56-d228-48f4-b28d-e9a43e358e9c

Ok.

0 rows in set. Elapsed: 0.005 sec.

:) select uniq(x) from file(data.arrow)

SELECT uniq(x)
FROM file(data.arrow)

Query id: 05ac7410-a6a4-4e28-9dbd-9729d7606ce1

┌─uniq(x)─┐
│      65 │
└─────────┘

1 row in set. Elapsed: 0.007 sec.
```
I suspect the issue is related to the arrow schema inference, specifically this [function](../blob/c8619ee6e4acaf7718a790d15e03261df4d4d3a7/src/Processors/Formats/Impl/CHColumnToArrowColumn.cpp#LL799C58-L799C58) where the indices type is inferred. The function incorrectly maps unsigned types to signed types of the same width (e.g. `arrow::int8()` cannot represent the same range as `TypeIndex::UInt8`).

**Comment by andykernahan** [comment]
@Avogar would you prefer I open a new ticket?

**Comment by Avogar** [comment]
Yes, please, open another ticket so I can assign it to me and fix when I have time
