### ISSUE TITLE
If Python files are not modified in the pull request, we should not run Python linters and formatters

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#36871]
See https://github.com/ClickHouse/ClickHouse/pull/36295

**Comment by Felixoid** [comment]
As discussed in slack, style check now tests everything for every run. We can distinguish changed files and run all checks only for them on the one hand. On the other hand, it now costs only a few minutes.

And I'm really against placing python in a second-class room.
