### ISSUE TITLE
How to move data directory to another device/folder ?

### ISSUE THREAD

**Issue by athanhat** [ClickHouse/ClickHouse#36870]
Hi, I have installed  latest ClickHouse Server version 22.4.4 revision 54455 from [deb packages][1]
I started the server with
`sudo systemctl start clickhouse-server`
and checked the status with 
`sudo systemctl status clickhouse-server`

There were not any problems, my question is how do I change all data directory paths to a new folder on an SSD device that is mounted at `/evo'. This is what I have tried

1. I stopped the service
```
 sudo systemctl stop clickhouse-server
 clickhouse-server.service - ClickHouse Server (analytic DBMS for big data)
     Loaded: loaded (/lib/systemd/system/clickhouse-server.service; disabled; vendor preset: enabled)
     Active: inactive (dead)
```

3. I edited the following 6 point inside `/etc/clickhouse-server/config.xml`
```
<!-- Path to data directory, with trailing slash. -->
    <path>/evo/clickhouse/</path>

<!-- Path to temporary data for processing hard queries. -->
    <tmp_path>/evo/clickhouse/tmp/</tmp_path>

<!-- Directory with user provided files that are accessible by 'file' table function. -->
    <user_files_path>/evo/clickhouse/user_files/</user_files_path>

<!-- Path to folder where users created by SQL commands are stored. -->
     <path>/evo/clickhouse/access/</path>

<!-- <top_level_domains_path>/evo/clickhouse/top_level_domains/</top_level_domains_path> -->

<!-- Directory in <clickhouse-path> containing schema files for various input formats.
         The directory will be created if it doesn't exist.
      -->
    <format_schema_path>/evo/clickhouse/format_schemas/</format_schema_path>
```

4. I created a folder `/evo/clickhouse` and changed the owner/group to
sudo chown clickhouse:clickhouse /evo/clickhouse
ls -l
total 50331708
drwxrwxr-x  2 clickhouse clickhouse        4096 May  3 14:14 clickhouse

5. And finally I made an attempt to start the server again
```
(base) athan@zenith:/evo$ sudo systemctl restart clickhouse-server
(base) athan@zenith:/evo$ sudo systemctl status clickhouse-server
● clickhouse-server.service - ClickHouse Server (analytic DBMS for big data)
     Loaded: loaded (/lib/systemd/system/clickhouse-server.service; disabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Tue 2022-05-03 15:23:10 EEST; 6s ago
    Process: 30360 ExecStart=/usr/bin/clickhouse-server --config=/etc/clickhouse-server/config.xml --pid-file=/run/clickhouse-server/clickhouse-server.pid (code=exited, status=233/RUNTIME_DIRECTORY)
   Main PID: 30360 (code=exited, status=233/RUNTIME_DIRECTORY)
```

and I have also tried
```
sudo -u clickhouse clickhouse-server --pid-file=/var/run/clickhouse-server/clickhouse-server.pid --config-file=/etc/clickhouse-server/config.xml
Processing configuration file '/etc/clickhouse-server/config.xml'.
std::exception. Code: 1001, type: std::__1::__fs::filesystem::filesystem_error, e.what() = filesystem error: in create_directories: Permission denied ["/evo/clickhouse/preprocessed_configs"]
```
But `/evo/clickhouse` is empty and see output of ls above for its permissions and ownership

Nothing was written in 
/var/log/clickhouse-server/clickhouse-server.err.log 

I have also switched back to /var/lib by changing again all the paths in config. xml
and started the server here is the output from the status and the error.log

```
sudo systemctl status clickhouse-server
● clickhouse-server.service - ClickHouse Server (analytic DBMS for big data)
     Loaded: loaded (/lib/systemd/system/clickhouse-server.service; disabled; vendor preset: enabled)
     Active: active (running) since Tue 2022-05-03 15:33:15 EEST; 2min 33s ago
   Main PID: 31069 (clckhouse-watch)
      Tasks: 207 (limit: 38323)
     Memory: 231.8M
     CGroup: /system.slice/clickhouse-server.service
             ├─31069 clickhouse-watchdog        --config=/etc/clickhouse-server/config.xml --pid-file=/run/clickhouse-server/clickhouse-server.pid
             └─31083 /usr/bin/clickhouse-server --config=/etc/clickhouse-server/config.xml --pid-file=/run/clickhouse-server/clickhouse-server.pid

2022.05.03 15:33:15.947614 [ 31083 ] {} <Warning> Application: Calculated checksum of the binary: 446925F9F90364DA31ABA69A242F232C. There is no information about the reference checksum.
2022.05.03 15:33:15.973136 [ 31083 ] {} <Error> CertificateReloader: Cannot obtain modification time for certificate file /etc/clickhouse-server/server.crt, skipping update. errno: 2, strerror: No such file or directory
2022.05.03 15:33:15.973153 [ 31083 ] {} <Error> CertificateReloader: Cannot obtain modification time for key file /etc/clickhouse-server/server.key, skipping update. errno: 2, strerror: No such file or directory
2022.05.03 15:33:15.973387 [ 31083 ] {} <Error> CertificateReloader: Poco::Exception. Code: 1000, e.code() = 0, SSL context exception: Error loading private key from file /etc/clickhouse-server/server.key: error:02000002:system library:OPENSSL_internal:No such file or directory (version 22.4.4.7 (official build))
2022.05.03 15:33:16.275590 [ 31083 ] {} <Error> CertificateReloader: Cannot obtain modification time for certificate file /etc/clickhouse-server/server.crt, skipping update. errno: 2, strerror: No such file or directory
2022.05.03 15:33:16.275615 [ 31083 ] {} <Error> CertificateReloader: Cannot obtain modification time for key file /etc/clickhouse-server/server.key, skipping update. errno: 2, strerror: No such file or directory
2022.05.03 15:33:16.275745 [ 31083 ] {} <Error> CertificateReloader: Poco::Exception. Code: 1000, e.code() = 0, SSL context exception: Error loading private key from file /etc/clickhouse-server/server.key: error:02000002:system library:OPENSSL_internal:No such file or directory (version 22.4.4.7 (official build))
```

I am not sure what is the best way to do this task, i.e. move data directory to some other device/folder and I have not found anything in the official documentation. Can you help ?

PS: I have also searched in Google for similar issues, but I found no solution to the problem  I described above. It would be also nice to have some utility/tool that can automate the procedure of moving clickhouse data to another device/folder. Another suggestion is to ask the user during installation what folder to use to store data

[1]: https://clickhouse.com/docs/en/getting-started/install/#install-from-deb-packages

**Comment by genzgd** [comment]
Can you get the full journalctl output?

**Comment by genzgd** [comment]
Actually can the clickhouse user create this directory?  `Permission denied ["/evo/clickhouse/preprocessed_configs"]`

**Comment by melvynator** [comment]
It seems like a permission issue on the ClickHouse user. Will it be possible to show us the directories's permission(mode and owner)?

**Comment by athanhat** [comment]
@genzgd and @melvynator you are right it was a permission issue. I gave access to `clickhouse` user on the mounted device `evo` and the problem is now solved.

**Comment by melvynator** [comment]
Glad we could help :)

**Comment by genzgd** [comment]
Also you only have to change the `<path>` element in config.xml.  You only need to configure the additional directories separately if you want them under another directory other than the `<path>`.  (Note this does not apply to certificates or keys, since the full path for those is defined in the openSSL section of config.xml).

**Comment by powelleric** [comment]
For me, I had to modify the paths in `/etc/clickhouse-server/config.d/data-paths.xml`.  In fact, I can't tell if  changing the paths in `/etc/clickhouse-server/config.xml` had any effect.

**Comment by Navneetsan** [comment]
Hey guys @athanhat , @genzgd , @melvynator , @powelleric . 
So, I tried the above part of changing the <path> so i changed the path from '/var/lib/clickhouse' to '/mnt/my_share/ClickhouseData' in config.xml file and giving permission to clickhouse of the mounted path then too these error occured when i started the clickhouse-server, Can you help me with this?

navneet@dev:~$ sudo systemctl start clickhouse-server
Job for clickhouse-server.service failed because the control process exited with error code.
See "systemctl status clickhouse-server.service" and "journalctl -xeu clickhouse-server.service" for details.
navneet@dev:~$ sudo systemctl status clickhouse-server 
● clickhouse-server.service - ClickHouse Server (analytic DBMS for big data)
     Loaded: loaded (/usr/lib/systemd/system/clickhouse-server.service; enabled>
     Active: activating (auto-restart) (Result: exit-code) since Tue 2024-05-14>
    Process: 2104935 ExecStart=/usr/bin/clickhouse-server --config=/etc/clickho>
   Main PID: 2104935 (code=exited, status=233/RUNTIME_DIRECTORY)

**Comment by Navneetsan** [comment]
@tongle1 , hey were you able to figure out this issue ? Can you help me with this ?

**Comment by tongle1** [comment]
> @tongle1 , hey were you able to figure out this issue ? Can you help me with this ?
hi,I had this problem a long time ago. I tried the following two things but forgot which one worked.
1、check the user permission of '/mnt/my_share/ClickhouseData. switch to clickhouse and try to make a new dir /mnt/my_share/ClickhouseData/xxx
2、you can try create a link from /mnt/my_share/ClickhouseData to the defaule path /var/lib/clickhouse

**Comment by Navneetsan** [comment]
> > @tongle1 , hey were you able to figure out this issue ? Can you help me with this ?
> > hi,I had this problem a long time ago. I tried the following two things but forgot which one worked.
> > 1、check the user permission of '/mnt/my_share/ClickhouseData. switch to clickhouse and try to make a new dir /mnt/my_share/ClickhouseData/xxx
> > 2、you can try create a link from /mnt/my_share/ClickhouseData to the defaule path /var/lib/clickhouse

Thankyou for replying, and did you also created a user names 'clickhouse' on your NAS Synology??

**Comment by tongle1** [comment]
> > > @tongle1 , hey were you able to figure out this issue ? Can you help me with this ?
> > > hi,I had this problem a long time ago. I tried the following two things but forgot which one worked.
> > > 1、check the user permission of '/mnt/my_share/ClickhouseData. switch to clickhouse and try to make a new dir /mnt/my_share/ClickhouseData/xxx
> > > 2、you can try create a link from /mnt/my_share/ClickhouseData to the defaule path /var/lib/clickhouse
> 
> Thankyou for replying, and did you also created a user names 'clickhouse' on your NAS Synology??

I start my clickhouse with user root.so I did not create a user names clickhouse.

**Comment by den-crane** [comment]
https://kb.altinity.com/altinity-kb-setup-and-maintenance/altinity-kb-moving-table-to-another-device./
