### ISSUE TITLE
Exception "Column is not under aggregate function and not in GROUP BY" do not raise as expected

### ISSUE THREAD

**Issue by dimkas78** [ClickHouse/ClickHouse#36895]
ClickHouse version 22.3.3.44

I made script with obvious error in last string:
```
select a, max(b) max_b, min(b) min_b from      
(      
	select 1 as a, 10 as b
	union all
	select 1 as a, 20 as b
	union all
	select 1 as a, 30 as b
)
group by a
having b = 10 or max(b) = 30 
```
ClickHouse throw an exception  "Code: 215. DB::Exception: Column `b` is not under aggregate function and not in GROUP BY..."

But there is no exception, when i write just 'having b = 10' in last string:
```
select a, max(b) max_b, min(b) min_b from      
(      
	select 1 as a, 10 as b
	union all
	select 1 as a, 20 as b
	union all
	select 1 as a, 30 as b
)
group by a
having b = 10
``` 
ClickHouse processed this like `WHERE b = 10`
I think this is bug - plain column 'b', without any aggregate function, should not be accessible in HAVING statement.

**Comment by nikitamikhaylov** [comment]
Exception will be thrown if you execute `SET enable_optimize_predicate_expression = 0`

**Comment by egor-ryashin** [comment]
It still throws an error and it complains when the alias is used:
```
macbook :) select abs(id) id, sum(a) from a group by abs(id);

SELECT
    abs(id) AS id,
    sum(a)
FROM a
GROUP BY abs(id)

Query id: 14e421e9-ed13-4386-a60c-9c7d3ee9659c


Elapsed: 0.031 sec. 

Received exception from server (version 24.8.1):
Code: 215. DB::Exception: Received from localhost:9000. DB::Exception: Column default.a.id is not under aggregate function and not in GROUP BY keys. In query SELECT abs(id) AS id, sum(a) FROM a GROUP BY abs(id). (NOT_AN_AGGREGATE)

macbook :) select abs(id), sum(a) from a group by abs(id);

SELECT
    abs(id),
    sum(a)
FROM a
GROUP BY abs(id)

Query id: 4d910f68-7147-4abc-b693-a56a8d815fb4

   ┌─abs(id)─┬─sum(a)─┐
1. │       3 │      5 │
2. │       2 │      3 │
3. │       1 │    inf │
   └─────────┴────────┘

3 rows in set. Elapsed: 0.006 sec. 
```

**Comment by Algunenano** [comment]
> It still throws an error and it complains when the alias is used:

That's a different issue. CH by default prefers alias created in the column clause, so when you write `GROUP BY abs(id)` it's understanding it as `GROUP BY abs(abs(id))` which means that `abs(id)` is not being used to group by. If you want the behaviour of other RDBMS where aliases are ignored you can use `prefer_column_name_to_alias=0`.

In any case, the original report is already fixed by the new analyzer, so I'm closing the issue.
