### ISSUE TITLE
Flaky test_postgresql_replica_database_engine_2

### ISSUE THREAD

**Issue by tavplubix** [ClickHouse/ClickHouse#36898]
https://s3.amazonaws.com/clickhouse-test-reports/36872/dbbe2062af065cfdd96b3618c6ab3e43fee7ef21/integration_tests__asan__actions__[1/3].html

https://s3.amazonaws.com/clickhouse-test-reports/36872/dbbe2062af065cfdd96b3618c6ab3e43fee7ef21/integration_tests__thread__actions__[3/4].html

cc: @kssenii

**Comment by alexey-milovidov** [comment]
Last failure was in October: https://play.clickhouse.com/play?user=play#U0VMRUNUIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgcmVwb3J0X3VybApGUk9NIGNoZWNrcwpXSEVSRSBwdWxsX3JlcXVlc3RfbnVtYmVyID0gMAogICAgQU5EIHRlc3Rfc3RhdHVzICE9ICdTS0lQUEVEJwogICAgQU5EIHRlc3Rfc3RhdHVzIExJS0UgJ0YlJwogICAgQU5EIGNoZWNrX3N0YXR1cyAhPSAnc3VjY2VzcycKICAgIEFORCBwb3NpdGlvbih0ZXN0X25hbWUsICdwb3N0Z3Jlc3FsX3JlcGxpY2EnKSA+IDAKT1JERVIgQlkgY2hlY2tfc3RhcnRfdGltZSBERVND

**Comment by tavplubix** [comment]
> Last failure was in October

It's because the test is disabled: 
https://github.com/ClickHouse/ClickHouse/blob/9ffaf2fef2de730d9724615cae6235a381ff3086/tests/integration/test_postgresql_replica_database_engine_2/test.py#L3-L8

**Comment by tavplubix** [comment]
The test is still a bit flacky: https://s3.amazonaws.com/clickhouse-test-reports/58393/ef52f9d8b3cb1b47d815b779be3f44065e8fcd63/integration_tests__asan__analyzer__[1_6].html

**Comment by tavplubix** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/58649/2cf74aea5c618bb228eb582b9aaa4481f2879e11/integration_tests__tsan__[1_6].html

**Comment by kssenii** [comment]
This should have been fixed by https://github.com/ClickHouse/ClickHouse/pull/58951.
