### ISSUE TITLE
toInt64() returned string type when format is JSONEachRow

### ISSUE THREAD

**Issue by HeenaBansal2009** [ClickHouse/ClickHouse#36893]
**Describe the unexpected behaviour**
Clickhouse returned the string value  of toInt64(toDateTime(time,'UTC')) when format is JSONEachRow.

Table Schema
Table Schema 👍 CREATE TABLE hackernews
(
id UInt32,
deleted UInt8,
type Enum('story' = 1, 'comment' = 2, 'poll' = 3, 'pollopt' = 4, 'job' = 5),
by LowCardinality(String),
time DateTime,
text String,
dead UInt8,
parent UInt32,
poll UInt32,
kids Array(UInt32),
url String,
score Int32,
title String,
parts Array(UInt32),
descendants Int32
)
ENGINE = MergeTree ORDER BY id

**How to reproduce**
```
select id , time  from hackernews LIMIT 5 FORMAT JSONEachRow

SELECT
    id,
    time
FROM hackernews
LIMIT 5
FORMAT JSONEachRow

Query id: b21bc8c1-43d0-443e-b981-75aa615b6db2

{"id":1,"time":"2006-10-09 11:21:51"}
{"id":2,"time":"2006-10-09 11:30:28"}
{"id":3,"time":"2006-10-09 11:40:33"}
{"id":4,"time":"2006-10-09 11:47:42"}
{"id":5,"time":"2006-10-09 11:51:04"}

5 rows in set. Elapsed: 0.047 sec. 


select id, toInt64(toDateTime(time,'UTC')) AS time  from hackernews LIMIT 5 FORMAT JSONEachRow

SELECT
    id,
    toInt64(toDateTime(time, 'UTC')) AS time
FROM hackernews
LIMIT 5
FORMAT JSONEachRow

Query id: 07ee229d-18db-42cc-905f-ee34c6726f2c

{"id":1,"time":"1160418111"}
{"id":2,"time":"1160418628"}
{"id":3,"time":"1160419233"}
{"id":4,"time":"1160419662"}
{"id":5,"time":"1160419864"}

15 rows in set. Elapsed: 0.020 sec. 

```

**Additional Context: 
 I am following  https://github.com/ClickHouse/ClickHouse/issues/29693  to ingest data in clickhouse as well as in QuickWit.
 However , Data ingestion went through in clickhouse, However in quickwit, I am getting error while parsing the time value , because it is string type and the table describes it as i64.

**Comment by genzgd** [comment]
By default 64 bit int values are quoted in JSON because the Javascript Number type doesn't handle them well (Javascript Numbers are stored as a 64 bit float value).  You can change this behavior by changing this settings to '0' either in your query or for your users/user profile: https://clickhouse.com/docs/en/operations/settings/settings/#session_settings-output_format_json_quote_64bit_integers

**Comment by HeenaBansal2009** [comment]
@genzgd ,Thanks for prompt response.
