### ISSUE TITLE
Euclidean distance

### ISSUE THREAD

**Issue by cmdares** [ClickHouse/ClickHouse#3691]
in postgresql Euclidean distance can be implement as:
CREATE OR REPLACE FUNCTION euc_distance(l float8[], r float8[]) RETURNS float8 AS $$  
DECLARE  
  s float8 := 0;
  x float8;
  i int := 1;
  r_len int := array_length(r,1); 
  l_len int := array_length(l,1);
BEGIN  
  if l_len >= r_len then  
    foreach x in array l LOOP  
      s := s + ( (x - case when i<=r_len then r[i] else 0 end) ^ 2 );  
      i := i+1;  
    END LOOP;  
  else  
    foreach x in array r LOOP  
      s := s + ( (x - case when i<=l_len then l[i] else 0 end) ^ 2 );  
      i := i+1;  
    END LOOP;  
  end if;  
  RETURN |/ s;  
END;  
$$ LANGUAGE plpgsql;  

usage:
# select euc_distance(array[1,2,3], array[1,2,3]);  
# select euc_distance(array[1,2,3], array[1,2,3,4,5]);  

Is it possible to implement efficient native Euclidean distance function through c++ in clickhouse?
thanks!
expected!

**Comment by alexey-milovidov** [comment]
`SELECT sqrt(arraySum(arrayMap((x, y) -> (x - y) * (x - y), [1, 2, 3], [4, 5, 6])))`

**Comment by bicubic** [comment]
Would be nice to see greatCircleDistance support array inputs like this too.
