### ISSUE TITLE
Use floating point values to set time related settings

### ISSUE THREAD

**Issue by Algunenano** [ClickHouse/ClickHouse#36940]
Currently all time span settings are being parsed as `UInt64` with 2 problems:
* It's silently ignoring decimal values. For example `SET max_execution_time = 1.5` will set the max_execution_time to 1, and what is worse, `0.5` will be set as `0`.
* The smallest values you can set is 1.

In order to allow for more granularity I'd like to change the value to be a Float64 (positive and finite) instead which would fix both instances and allow reducing timeouts (`connect_timeout`, `max_execution_time`, `http_connection_timeout`, etc) under a second.

Although the internal representation would still be a `TimeDiff` (i.e. `Int64`), this would still be a breaking change since not all UInt64 values can be accurately represented as Float64. Nevertheless, I don't expect anyone to be using values over 2^53.

Any thoughts?

**Comment by alexey-milovidov** [comment]
Good, but please do it only for settings that accept seconds.
Millisecond, microsecond and nanoseconds should not accept floats.

**Comment by alexey-milovidov** [comment]
Also check for negative values, subnormal values, infinities and nans.

**Comment by Algunenano** [comment]
The changes seem pretty straightforward with a caveat: The communication between processes:

In (very) old CH versions, settings were transmitted in binary form: For seconds what was used was `UInt64` with the seconds, not the internal times(Int64) which would have made things much simpler. In more recent versions that was changed to be made as strings (`DBMS_MIN_REVISION_WITH_SETTINGS_SERIALIZED_AS_STRINGS`) (also as UInt64).

As far as I can tell, the only problems that can appear is that you might get the old behaviour back if the client is old, but when both client and server are using a "Float64" compatible release then you'll get float64 automatically:

* Binary client + ThisChangeServer: The value was already an integer, will be passed as integer, read as integer and used as integer. No changes in behaviour.
* Current String client + ThisChangeServer: Same as above. Some numbers (above 2^53) might see some changes but it's acceptable.
* ThisChangeClient + ThisChangeServer: The string value will be a float64 and not an integer. It will work as expected (0.5 will be treated as 0.5).
 <br>

* Binary client + Binary Server: Nothing is changed (Binary is used)
* String client + Binary Server: Nothing is changed (Binary protocol used)
* ThisChangeClient+ Binary Server: The binary protocol will be used so 0.5 will become 0 (as it happened until now), so it won't change.
<br>

* Binary client + Current server: Nothing is changed (Binary is used)
* String client + Current server: Nothing is changed (String is used passing integers)
* ThisChangeClient + Current server: The string client will pass a float as a string, i.e "2.3". The server will read it as integer and discard the decimal part, leaving the old behaviour in place.


An example with the modified client:
* Against a recent release:
```
SELECT count()
FROM
(
    SELECT *
    FROM system.numbers
)
SETTINGS max_execution_time = 2.3

Query id: 17e391dd-61f0-4553-a54e-a3c16323a7b1

↙ Progress: 3.71 billion rows, 29.70 GB (1.95 billion rows/s., 15.59 GB/s.)                                                                                                                                                       (0.9 CPU)
0 rows in set. Elapsed: 2.002 sec. Processed 3.71 billion rows, 29.70 GB (1.85 billion rows/s., 14.84 GB/s.)

Received exception from server (version 22.4.5):
Code: 159. DB::Exception: Received from localhost:9000. DB::Exception: Timeout exceeded: elapsed 2.000045797 seconds, maximum: 2. (TIMEOUT_EXCEEDED)
```


* Against a release with the change:

```
SELECT count()
FROM
(
    SELECT *
    FROM system.numbers
)
SETTINGS max_execution_time = 2.3

Query id: 4315ca2c-dd5a-49f6-b993-1c4316ca9e75

Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 22.5.1 revision 54455.

↗ Progress: 4.01 billion rows, 32.09 GB (1.81 billion rows/s., 14.51 GB/s.)                                                                                                                                                       (0.9 CPU)
0 rows in set. Elapsed: 2.312 sec. Processed 4.01 billion rows, 32.09 GB (1.73 billion rows/s., 13.88 GB/s.)

Received exception from server (version 22.5.1):
Code: 159. DB::Exception: Received from localhost:9000. DB::Exception: Timeout exceeded: elapsed 2.300057733 seconds, maximum: 2.3. (TIMEOUT_EXCEEDED)
```

I haven't tested against a server with binary settings, but since the binary representation isn't changed it should remain exactly the same. I think that this compatibility is not only ok but the only way to move forward.

In addition to this, there is another small change which is the Field() function, which now will return a Float64 for seconds. This one seems harmless and only used in `stringToValueUtil` so changing it should be ok (AFAICS).

I'll add some comments and tests and send a PR.
