### ISSUE TITLE
RFC: named_collections: sql interface?

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#36943]
i think can be done similarly to dictionaries (i.e. remapping to config-alike structure)
```
CREATE NAMED COLLECTION foo HOST(foo) PASSWORD(bar);
```

Concerns: 
- rules of remapping things (in some corner cases that can be problematic)
- security (CREATE NAMED COLLECTION queries can be written to logs) 
- introspection functionality ? 
- GRANTs

**Comment by alexey-milovidov** [comment]
Named collections feature was developed specifically to hide credentials and to maintan them securely in configuration that users have no access.

**Comment by filimonov** [comment]
> that users have no access.

There are different kinds of users ;) Superusers who have access to a filesystem of the clickhouse node - have that access.

If the root user can define a named collection in the XML so the regular users can use it in the queries, why can't (root) user define the same in the SQL.

Nobody (including root) should be able to see the contents of that collection, but it can be used/redefined.

So it sounds like it may have sense.

At the same time, I also have some concerns about that (listed above) and am not sure if investing efforts in that is worth it now (maybe someday).
