### ISSUE TITLE
Clickhouse Watchdog exits with code 0 if child process killed by SIGKILL

### ISSUE THREAD

**Issue by socketpair** [ClickHouse/ClickHouse#36971]
```
мая 06 17:17:08 localhost clickhouse-server[1478172]: 2022.05.06 17:17:08.250884 [ 1478172 ] {} <Fatal> Application: Child process was terminated by signal 9 (KILL). If it is not done by 'forcestop' command or manually, the possible cause is OOM Killer (see 'dmesg' and look at the '/var/log/kern.log' for the details).
мая 06 17:17:08 localhost systemd[1]: clickhouse-server.service: Succeeded.
мая 06 17:17:08 localhost systemd[1]: clickhouse-server.service: Consumed 2h 15min 18.911s CPU time.
```

In my case, it was EarlyOOM. As you can see, CH terminated normally (exit code 0). it's a bug. It should not.

**Comment by den-crane** [comment]
Watchdog only logs the cause of a process unexpected finish. 
It does not restart CH server.

**Comment by socketpair** [comment]
@den-crane please reopen. If so, watchdog MUST exit with nonzero code if child exitted with nonzero code.

**Comment by den-crane** [comment]
@socketpair do you mean CH server exits with non-zero exit code, but watchdog with zero ?

**Comment by den-crane** [comment]
Change the issue title

**Comment by socketpair** [comment]
Yes, exactly. Try killing child process with SIGKILL

**Comment by urusha** [comment]
Don't know if it's related, but with 23.2.4.12 (amd64, ubuntu 22) systemctl  doesn't restart service after killing main process with `SIGKILL`. `SIGTERM` is ok.
Here is the state after sigkill:
```
# systemctl status clickhouse-server.service 
● clickhouse-server.service - ClickHouse Server (analytic DBMS for big data)
     Loaded: loaded (/lib/systemd/system/clickhouse-server.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2023-03-23 16:02:24 UTC; 19min ago
   Main PID: 4084999
      Tasks: 11 (limit: 154363)
     Memory: 40.1G
        CPU: 3h 17min 36.503s
     CGroup: /system.slice/clickhouse-server.service
             └─4085447 /usr/bin/clickhouse-odbc-bridge --http-port 9018 --listen-host 127.0.0.1 --http-timeout 1800000000
```
Watchdog and main process (PID) disappeared, but `clickhouse-odbc-bridge` is still alive and systemd thinks it's ok.
A workaround is to add `CLICKHOUSE_WATCHDOG_ENABLE=0` env.

**Comment by socketpair** [comment]
@urusha try adding

```
[Service]
Restart=always
```

If it helps – I know what to do.


Also, it's best to test this way:
1. stop service
2. change .service file
3. call `systemctl daemon-reload`
4. start service
5. make an experiment.

**Comment by urusha** [comment]
@socketpair no, this doesn't work. I guess it's because this instance uses odbc-bridge which is a separate process which stays alive, systemd thinks that the service is in normal state (even so, the main process doesn't exist anymore). Here is the reason for this:
```
systemd[1]: clickhouse-server.service: Supervising process 4084999 which is not our child. We'll most likely not notice when it exits.
```

Without `odbc-bridge`  `Restart=always` would work, because there would be no processes at all after killing.
Anyway restarts after sigkill are broken and since OOMs with clickhouse are pretty possible, this becomes a serious issue.

**Comment by socketpair** [comment]
Personally, I don't see any reasons to have ClickHouse watchdog when CH run under systemd. AFAIK, systemd logs everything what ClickHouse watchdog logs (source of kill signal). I would turn it off in the default `.service` file.

But anyway, for non-systemd users, the bug is still relevant.

**Comment by socketpair** [comment]
I found the bug. `src/Daemon/BaseDaemon.cpp`

```c++
        if (WIFSIGNALED(status))
        {
            int sig = WTERMSIG(status);
    
            if (sig == SIGKILL)
            {
                logger().fatal(fmt::format("Child process was terminated by signal {} (KILL)."
                    " If it is not done by 'forcestop' command or manually,"
                    " the possible cause is OOM Killer (see 'dmesg' and look at the '/var/log/kern.log' for the details).", sig));
            }
            else
            {
                logger().fatal(fmt::format("Child process was terminated by signal {}.", sig));
        
                if (sig == SIGINT || sig == SIGTERM || sig == SIGQUIT)
                    _exit(128 + sig);
            }
        }
        else
        {
            logger().fatal("Child process was not exited normally by unknown reason.");
        }

        if (restart)
        {
            logger().information("Will restart.");
            if (argv0)
                memcpy(argv0, original_process_name.c_str(), original_process_name.size());
        }
        else
            _exit(WEXITSTATUS(status));
```

As you can see, on KILL it exits with `WEXITSTATUS(status)` which is completely WRONG. And seems to happen to be zeroes (my case)

But your case is different - in your case systemd does not understand Clickhouse ended. Please provide exact steps to reproduce the problem
