### ISSUE TITLE
SELECT * FROM (SELECT 1, 1, 1) unexpected result

### ISSUE THREAD

**Issue by InquisitorGray** [ClickHouse/ClickHouse#36973]
Clickhouse version 22.5.1.458

https://gh-api.clickhouse.tech/play?user=play

### Correct behavior
```SQL
SELECT 1, 1, 1;
-- expected 1, 1, 1
-- returned 1, 1, 1
```

### Unexpected behavior
```SQL
SELECT * FROM (SELECT 1, 1, 1);
-- expected 1, 1, 1
-- returned 1
```
Looks like the check for MULTIPLE_EXPRESSIONS_FOR_ALIAS is bypassed

**Comment by alexey-milovidov** [comment]
This behavior is ok although it will be better to throw exception.

https://www.db-fiddle.com/f/mgLQrM84XkM74KD61Ha1yT/0

**Comment by InquisitorGray** [comment]
I have some doubts about OK-behavior returning single 1.
The same query in Postgres returns 1, 1, 1 as expected in the above mentioned db-fiddle.
I guess, both behaviors can not be correct at the same time.

The exception would be correct, though.

**Comment by alexey-milovidov** [comment]
Works perfectly with Analyzer:
```
SELECT * FROM (SELECT 1, 1, 1) SETTINGS allow_experimental_analyzer = 1;
```

Waiting while Analyzer will be enabled by default.
