### ISSUE TITLE
I want to store and aggregrate data for every 5 minutes but here it not storing timestamp in interval of 5 minutes and hence not summing the data

### ISSUE THREAD

**Issue by dhruvanand96** [ClickHouse/ClickHouse#36980]
Below is my create query
CREATE MATERIALIZED VIEW IF NOT EXISTS analytics.uflow_topapps_bytes_flowdir_or_013_mv
ENGINE = SummingMergeTree PARTITION BY toYYYYMMDD ( Timestamp )
ORDER BY (CpeCNID, name_top_apps, name_remote_top_emdpoints, Timestamp)
AS SELECT
   toString(AppId) as name_top_apps,
   IPv6NumToString(DstIP) as name_remote_top_emdpoints,
   sum(FlowStatsBytesFwd) as upload_bytes,
   sum(FlowStatsBytesRev) as download_bytes,
   sum(FlowStatsBytesFwd + FlowStatsBytesRev) as cumulative_bytes,
   sum(FlowStatsPktsFwd) as upload_flows,
   sum(FlowStatsPktsFwd) as download_flows,
   sum(FlowStatsPktsFwd + FlowStatsPktsRev) as cumulative_flows,
   toInt64((sum(FlowStatsBytesFwd)* 8)/least(sum(Duration),60)) as upload_rate,
   toInt64((sum(FlowStatsBytesRev)* 8)/least(sum(Duration),60)) as download_rate,
   toInt64(((sum(FlowStatsBytesRev) + sum(FlowStatsBytesFwd)) * 8)/least(sum(Duration),60)) as cumulative_rate,
   toStartOfInterval(Timestamp, INTERVAL 300 second) AS Timestamp,
   CpeCNID as CpeCNID
from analytics.sampled_uflow where AccessDenied = 0 and ( FlowDir == 2 or FlowDir == 0 or FlowDir == 3 )
Group by  CpeCNID, name_top_apps, name_remote_top_emdpoints, Timestamp

and also result of my query when i fetch timestamp
select Timestamp from uflow_topapps_bytes_flowdir_or_013_mv order by Timestamp DESC limit 10;
SELECT Timestamp
FROM uflow_topapps_bytes_flowdir_or_013_mv
ORDER BY Timestamp DESC
LIMIT 10
Query id: 28505584-ffb9-4672-8094-3c6830465e35
┌───────────Timestamp─┐
│ 2022-05-07 00:10:00 │
│ 2022-05-06 23:20:00 │
│ 2022-05-06 23:20:00 │
│ 2022-05-06 23:20:00 │
│ 2022-05-06 23:20:00 │
│ 2022-05-06 23:20:00 │
│ 2022-05-06 23:20:00 │
│ 2022-05-06 23:20:00 │
│ 2022-05-06 23:20:00 │
│ 2022-05-06 23:20:00 │
└─────────────────────┘
10 rows in set. Elapsed: 0.033 sec. Processed 22.53 million rows, 90.13 MB (675.21 million rows/s., 2.70 GB/s.)

**Comment by den-crane** [comment]
Provide

```sql
select toStartOfInterval(Timestamp, INTERVAL 300 second) AS Timestamp
from analytics.sampled_uflow where AccessDenied = 0 and ( FlowDir == 2 or FlowDir == 0 or FlowDir == 3 )
order by Timestamp DESC limit 10;
```

**Comment by dhruvanand96** [comment]
> 

select toStartOfInterval(Timestamp, INTERVAL 300 second) AS Timestamp
                    from analytics.sampled_uflow where AccessDenied = 0 and ( FlowDir == 2 or FlowDir == 0 or FlowDir == 3 )
                    order by Timestamp DESC limit 10;

SELECT toStartOfInterval(Timestamp, toIntervalSecond(300)) AS Timestamp
FROM analytics.sampled_uflow
WHERE (AccessDenied = 0) AND ((FlowDir = 2) OR (FlowDir = 0) OR (FlowDir = 3))
ORDER BY Timestamp DESC
LIMIT 10

Query id: 4b6ce8c4-1f53-4e94-8152-6774d4a3992e

┌───────────Timestamp─┐
│ 2022-05-07 00:10:00 │
│ 2022-05-07 00:10:00 │
│ 2022-05-07 00:10:00 │
│ 2022-05-07 00:10:00 │
│ 2022-05-07 00:10:00 │
│ 2022-05-07 00:10:00 │
│ 2022-05-07 00:10:00 │
│ 2022-05-07 00:10:00 │
│ 2022-05-07 00:10:00 │
│ 2022-05-07 00:10:00 │
└─────────────────────┘

10 rows in set. Elapsed: 9.067 sec. Processed 4.96 billion rows, 29.74 GB (546.65 million rows/s., 3.28 GB/s.)

@den-crane

**Comment by den-crane** [comment]
I see. 

Can you also share

```
select distinct toStartOfInterval(Timestamp, INTERVAL 300 second) AS Timestamp
from analytics.sampled_uflow where AccessDenied = 0 and ( FlowDir == 2 or FlowDir == 0 or FlowDir == 3 )
order by Timestamp DESC limit 10;

```

**Comment by dhruvanand96** [comment]
SELECT DISTINCT toStartOfInterval(Timestamp, toIntervalSecond(300)) AS Timestamp
FROM analytics.sampled_uflow
WHERE (AccessDenied = 0) AND ((FlowDir = 2) OR (FlowDir = 0) OR (FlowDir = 3))
ORDER BY Timestamp DESC
LIMIT 10

Query id: 6b70abdb-f55a-4db7-9e60-fb793203ce19

┌───────────Timestamp─┐
│ 2022-05-07 00:20:00 │
│ 2022-05-07 00:15:00 │
│ 2022-05-07 00:10:00 │
│ 2022-05-07 00:05:00 │
│ 2022-05-07 00:00:00 │
│ 2022-05-06 23:55:00 │
│ 2022-05-06 23:50:00 │
│ 2022-05-06 23:45:00 │
│ 2022-05-06 23:40:00 │
│ 2022-05-06 23:35:00 │
└─────────────────────┘

10 rows in set. Elapsed: 10.350 `sec.```

@den-crane

**Comment by den-crane** [comment]
Do you use replication? 
Can you show `show create table analytics.sampled_uflow`

**Comment by dhruvanand96** [comment]
│ CREATE TABLE analytics.sampled_uflow
(
    `CpeCNID` UInt32 CODEC(ZSTD(9)),
    `SrcIP` IPv6 CODEC(ZSTD(9)),
    `DstIP` IPv6 CODEC(ZSTD(9)),
    `AppCatId` UInt8 CODEC(T64, ZSTD(9)),
    `FlowDir` UInt8 CODEC(T64, ZSTD(9)),
    `AccessDenied` Int8 CODEC(T64, ZSTD(9)),
    `AppId` UInt16 CODEC(T64, ZSTD(9)),
    `Duration` UInt32 CODEC(Gorilla, ZSTD(9)),
    `Timestamp` DateTime CODEC(DoubleDelta, ZSTD(9)),
    `FlowStatsPktsFwd` UInt32 CODEC(T64, ZSTD(9)),
    `FlowStatsPktsRev` UInt32 CODEC(T64, ZSTD(9)),
    `FlowStatsBytesFwd` UInt64 CODEC(T64, ZSTD(9)),
    `FlowStatsBytesRev` UInt64 CODEC(T64, ZSTD(9)),
    `AppUrl` String CODEC(ZSTD(9)),
    `FlowId` FixedString(16) CODEC(ZSTD(9))
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(Timestamp)
ORDER BY (Timestamp, CpeCNID, FlowId)
SETTINGS index_granularity = 8192 │

No we dont use

**Comment by den-crane** [comment]
But this is another table. No columns like `DstIP, AppId, FlowStatsBytesFwd, CpeCNID` ?

Can you share `select version()` ?

**Comment by dhruvanand96** [comment]
> 

`CREATE TABLE analytics.sampled_uflow
(
    `CpeCNID` UInt32 CODEC(ZSTD(9)),
    `SrcIP` IPv6 CODEC(ZSTD(9)),
    `DstIP` IPv6 CODEC(ZSTD(9)),
    `AppCatId` UInt8 CODEC(T64, ZSTD(9)),
    `FlowDir` UInt8 CODEC(T64, ZSTD(9)),
    `AccessDenied` Int8 CODEC(T64, ZSTD(9)),
    `AppId` UInt16 CODEC(T64, ZSTD(9)),
    `Duration` UInt32 CODEC(Gorilla, ZSTD(9)),
    `Timestamp` DateTime CODEC(DoubleDelta, ZSTD(9)),
    `FlowStatsPktsFwd` UInt32 CODEC(T64, ZSTD(9)),
    `FlowStatsPktsRev` UInt32 CODEC(T64, ZSTD(9)),
    `FlowStatsBytesFwd` UInt64 CODEC(T64, ZSTD(9)),
    `FlowStatsBytesRev` UInt64 CODEC(T64, ZSTD(9)),
    `AppUrl` String CODEC(ZSTD(9)),
    `FlowId` FixedString(16) CODEC(ZSTD(9))
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(Timestamp)
ORDER BY (Timestamp, CpeCNID, FlowId)
SETTINGS index_granularity = 8192 │`

this is the create table 

and version is  22.3.2.1

**Comment by den-crane** [comment]
I don't see any issues in your DDL.
For how long  `CREATE MATERIALIZED ... POPULATE` works ?

**Comment by dhruvanand96** [comment]
i had stop using populate i am creating new table and then creating new view and then start inserting the data populate was causing some issues
