### ISSUE TITLE
ClickHouse 22.4 does not handle DateTime64 correctly

### ISSUE THREAD

**Issue by zhicwu** [ClickHouse/ClickHouse#36994]
`select '1969-12-31 23:59:59.123'::DateTime64(3, 'UTC') v` should return `1969-12-31 23:59:59.123` but somehow it returns `1970-01-01 00:00:00.877` on 22.4.

This was first mentioned in ClickHouse/clickhouse-jdbc#906 as it failed below case only on 22.4:
```sql
create table test_default_value_datetime64(i Int8, v DateTime64(3, 'UTC') DEFAULT '1969-12-31 23:59:59.123')engine=Memory

insert into test_default_value_datetime64(1, null)

select * from test_default_value_datetime64
┌─i─┬───────────────────────v─┐
│ 1 │ 1969-12-31 23:59:59.123 │
└───┴─────────────────────────┘
```

**Comment by nickitat** [comment]
@taiyang-li can you please take a look

**Comment by taiyang-li** [comment]
@nickitat OK.

**Comment by taiyang-li** [comment]
> @taiyang-li can you please take a look

What is the `DB::DecimalUtils::DecimalComponents<DateTime64>` value we expect to represent `0.123` or `-0.123`? 

The current problem is that we can't distinguish `0.123` or `-0.123` because when whole = 0, fractional = 123(fractional is expected to be always positive).

**Comment by nickitat** [comment]
seems like 0.123 could be represented as (0, 123) and -0.123 as (-1, 877).

**Comment by taiyang-li** [comment]
> seems like 0.123 could be represented as (0, 123) and -0.123 as (-1, 877).

@nickitat  That's against the contract that fractional share the same signature with whole. For example in (-1, 877)'s value should be -1 * 10^scale - 877.

**Comment by taiyang-li** [comment]
@vdimir  @nickitat  It's fixed in https://github.com/ClickHouse/ClickHouse/pull/37039.  Can you guys review it if have time?
