### ISSUE TITLE
Setup of 1-Shard 3-Replicas with clickhouse-keeper

### ISSUE THREAD

**Issue by shubham696** [ClickHouse/ClickHouse#37003]
I have 1-shard 3-replicas setup ([files](https://github.com/ClickHouse/ClickHouse/issues/36750#issuecomment-1112436400)) 
Whenever im trying to create replicated table on a cluster with internal_replication true I'm getting an error as:

```

┌─host──────────────────┬─port─┬─status─┬─error──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─num_hosts_remaining─┬─num_hosts_active─┐
│ database-1 │ 9000 │    253 │ Code: 253. DB::Exception: Replica /clickhouse/tables/testing_cluster/default/testingTableNew6/replicas/replicaNew6 already exists. (REPLICA_IS_ALREADY_EXIST) (version 22.3.4.20 (official build)) │                   2 │                1 │
│ database-3 │ 9000 │    253 │ Code: 253. DB::Exception: Replica /clickhouse/tables/testing_cluster/default/testingTableNew6/replicas/replicaNew6 already exists. (REPLICA_IS_ALREADY_EXIST) (version 22.3.4.20 (official build)) │                   1 │                1 │
└───────────────────────┴──────┴────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴─────────────────────┴──────────────────┘
↘ Progress: 0.00 rows, 0.00 B (0.00 rows/s., 0.00 ┌─host──────────────────┬─port─┬─status─┬─error─┬─num_hosts_remaining─┬─num_hosts_active─┐
│ database-2 │ 9000 │      0 │       │                   0 │                0 │
└───────────────────────┴──────┴────────┴───────┴─────────────────────┴──────────────────┘
↓ Progress: 0.00 rows, 0.00 B (0.00 rows/s., 0.00 B/s.)  0%
3 rows in set. Elapsed: 0.179 sec. 

```

In this case it was run on database-1 and successful only for database-2 (**everytime successful only for leader, failing for follower nodes**).

query:-

```
create table testingTableNew6 on  cluster '{cluster}'   ( A Int64, S String) Engine = ReplicatedMergeTree('/clickhouse/tables/{cluster}/default/testingTableNew6','replicaNew6') Order by A;
```

cluster file:-
```
<clickhouse>
	<remote_servers>
		<testing_cluster>
			<shard>
	                    <weight>1</weight>
             	            <internal_replication>true</internal_replication>
		            <replica>
                		<host>database-1</host>
		                <port>9000</port>
		            </replica>
		            <replica>
                		<host>database-2</host>
		                <port>9000</port>
			    </replica>
			    <replica>
                                <host>database-3</host>
                                <port>9000</port>
                            </replica>

		        </shard>
		</testing_cluster>
	</remote_servers>
</clickhouse>
```

I have tried [dropping replica](https://clickhouse.com/docs/en/sql-reference/statements/system/#query_language-system-drop-replica) but, still no success with creating replicated table.

**But when creating a database on a cluster it is successful, I can see DB on all three nodes**

issue no.2->
Whenever im adding
```
    <listen_host>::</listen_host>
```
my docker is going into restarting state

**Comment by shubham696** [comment]
> I have 1-shard 3-replicas setup ([files](https://github.com/ClickHouse/ClickHouse/issues/36750#issuecomment-1112436400)) Whenever im trying to create replicated table on a cluster with internal_replication true I'm getting an error as:
> 
> ```
> 
> ┌─host──────────────────┬─port─┬─status─┬─error──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─num_hosts_remaining─┬─num_hosts_active─┐
> │ database-1 │ 9000 │    253 │ Code: 253. DB::Exception: Replica /clickhouse/tables/testing_cluster/default/testingTableNew6/replicas/replicaNew6 already exists. (REPLICA_IS_ALREADY_EXIST) (version 22.3.4.20 (official build)) │                   2 │                1 │
> │ database-3 │ 9000 │    253 │ Code: 253. DB::Exception: Replica /clickhouse/tables/testing_cluster/default/testingTableNew6/replicas/replicaNew6 already exists. (REPLICA_IS_ALREADY_EXIST) (version 22.3.4.20 (official build)) │                   1 │                1 │
> └───────────────────────┴──────┴────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴─────────────────────┴──────────────────┘
> ↘ Progress: 0.00 rows, 0.00 B (0.00 rows/s., 0.00 ┌─host──────────────────┬─port─┬─status─┬─error─┬─num_hosts_remaining─┬─num_hosts_active─┐
> │ database-2 │ 9000 │      0 │       │                   0 │                0 │
> └───────────────────────┴──────┴────────┴───────┴─────────────────────┴──────────────────┘
> ↓ Progress: 0.00 rows, 0.00 B (0.00 rows/s., 0.00 B/s.)  0%
> 3 rows in set. Elapsed: 0.179 sec. 
> ```
> 
> In this case it was run on database-1 and successful only for database-2 (which is random when i run query multiple time with different table and replica name).
> 
> query:-
> 
> ```
> create table testingTableNew6 on  cluster '{cluster}'   ( A Int64, S String) Engine = ReplicatedMergeTree('/clickhouse/tables/{cluster}/default/testingTableNew6','replicaNew6') Order by A;
> ```
> 
> cluster file:-
> 
> ```
> <clickhouse>
> 	<remote_servers>
> 		<testing_cluster>
> 			<shard>
> 	                    <weight>1</weight>
>              	            <internal_replication>true</internal_replication>
> 		            <replica>
>                 		<host>database-1</host>
> 		                <port>9000</port>
> 		            </replica>
> 		            <replica>
>                 		<host>database-2</host>
> 		                <port>9000</port>
> 			    </replica>
> 			    <replica>
>                                 <host>database-3</host>
>                                 <port>9000</port>
>                             </replica>
> 
> 		        </shard>
> 		</testing_cluster>
> 	</remote_servers>
> </clickhouse>
> ```
> 
> I have tried [dropping replica](https://clickhouse.com/docs/en/sql-reference/statements/system/#query_language-system-drop-replica) but, still no success with creating replicated table.
> 
> issue no.2-> Whenever im adding
> 
> ```
>     <listen_host>::</listen_host>
> ```
> 
> my docker is going into restarting state

But when creating a database on a cluster it is successful, I can see DB on all three nodes

**Comment by e-mars** [comment]
hi @shubham696 ,

A few notes on the issues and configurations:
For creating the replicated table, ensure that each node will have a unique shard name, you can do this by using macros.
for example if you had two nodes, 

on node1:
```
<macros>
    <shard>1</shard>
    <replica>replica_1</replica>
</macros>
```

on node 2:
```
<macros>
    <shard>1</shard>
    <replica>replica_2</replica>
</macros>
```
and use something like this:
```
CREATE TABLE repl_table ON CLUSTER cluster_1S_2R
            (
                id UInt64,
                column1 Date,
                column2 String
            )
            ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/default/repl_table', '{replica}' )
            ORDER BY (id);
```
*update above with your names and parameters.

When dropping replica or table, it normally takes up to 8 mins to sync in clickhouse keeper.
If you drop the table, use this to force drop on each node:
```
DROP TABLE ... SYNC
```
and ensure the `ON CLUSTER` is used.

If ON CLUSTER was not used then you can go to each of the nodes and drop each replica table independently.
You can also use this setting for the tables:
`database_atomic_wait_for_drop_and_detach_synchronously`
https://clickhouse.com/docs/en/operations/settings/settings/#database_atomic_wait_for_drop_and_detach_synchronously

For the 2nd issue, can you test with just:
`<listen_host>0.0.0.0</listen_host>`
Forces just to listen on IPv4, instead of both IPv4 and IPv6.

thanks.

**Comment by shubham696** [comment]
@e-mars I have provided a unique shard name and different replica names and created a table on the replicated table on a cluster. I can see the table on all three nodes but, when I insert data in the table from the leader node, it's not getting inserted(replicated) on the other two nodes.

i have currently forced to listen on IPv4 only

**Comment by e-mars** [comment]
hi @shubham696 ,

If you have used the standard deb or rpm distribution and set a password for the `default` user,  the cluster created will need credentials or the `<secret>` option to be set.

could you try to update the cluster with credentials; something like this? 
```
    <remote_servers>
        <cluster_1S_2R>
            <shard>
                <replica>
                    <host>chnode1.marsnet.local</host>
                    <port>9440</port>
                    <user>default</user>
                    <password>ClickHouse123!</password>
                    <secure>1</secure>
                </replica>
                <replica>
                    <host>chnode2.marsnet.local</host>
                    <port>9440</port>
                    <user>default</user>
                    <password>ClickHouse123!</password>
                    <secure>1</secure>
                </replica>
            </shard>
        </cluster_1S_2R>
    </remote_servers>
```
*update your cluster with your settings, you can use any user account in your cluster with sufficient privileges, this example uses the `default` account.

then create your table, insert sample data in your primary node, then connect to your secondary replica nodes and issue a SELECT from those nodes.

Also, if you've defined `<weight>1</weight>` in your primary node, set this on the other nodes also but with different weights according to which you'd like to get updated next, like `<weight>2</weight>`, etc. although this parameter is not necessary unless you need a certain order due to proxy, gateway, etc. 
You can remove this parameter and insert into the table on any node and it will replicate to the others.

thanks.

**Comment by shubham696** [comment]
hi @e-mars,
Have removed the weight from all the nodes and added username and password to all the nodes. But, still same issue is happening i.e. data is not getting replicated to all nodes.

**Comment by e-mars** [comment]
hi @shubham696 ,

do you see any errors in the logs when inserting data? 
especially networking ones on the port you are using for the cluster definition? (normally 9000 or 9440 if you are using SSL)

**Comment by e-mars** [comment]
HI @shubham696 ,

Recommend to use consistent way to refer to the different nodes but mixed should work as long as DNS can resolve.
From the config, looks like you're likely using containers on the same machine.
I found this option to use the local host stack, see if this applies to your environment:
https://stackoverflow.com/questions/32079364/how-can-you-make-the-docker-container-use-the-host-machines-etc-hosts-file

thanks.
