### ISSUE TITLE
How to set `client_name` in query_log?

### ISSUE THREAD

**Issue by simPod** [ClickHouse/ClickHouse#37004]
I'm using http interface. How can I pass `client_name` with the request so it's shown in `system.query_log` `client_name` column?

**Comment by genzgd** [comment]
`client_name` is sent as part of the native TCP protocol, it cannot be set using the http protocol, since HTTP has no concept of a client name.   The closest equivalent is the `http_user_agent column`, which will be set to the User-Agent header in the http request.
