### ISSUE TITLE
[Umbrella] Make ClickHouse great on AArch64

### ISSUE THREAD

**Issue by danlark1** [ClickHouse/ClickHouse#37005]
# Objective

Improve performance of ClickHouse for AArch64 and share the knowledge on how to do that.

# Plan

This is list of what can be done to improve performance for AArch64.

# Contrib/third_party libraries

Ideal case: try to run all benchmarks on Neoverse-N1/N2 and compare with equivalents to x86. Normalize by average and find all tails of normalized distribution to find most affected and less affected.

Some skimming showed the following results:

## Update Hyperscan to Vectorscan

Recently a lot of work has been done by me to make Vectorscan correct https://github.com/VectorCamp/vectorscan/pull/103 on both platforms including sanitizers, etc. 

Not so long ago after a year of silence Hyperscan started to fix long standing bugs

![2022-05-07-123657_1875x819_scrot](https://user-images.githubusercontent.com/15173761/167252584-a16b4a7c-e6ee-4826-b919-5d1db8b98dee.png)

Goal: merge these fixes and enable Vectorscan for ARM

## Snappy

Seem to be updated. More optimization are coming soon. Will update this section

## Farmhash

Requires AArch64 optimizations, see [code](https://github.com/google/farmhash/blob/0d859a811870d10f53a594927d0d0b97573ad06d/src/farmhash.cc#L799)

## Fastops

[Does not have](https://github.com/ClickHouse/fastops/tree/1460583af7d13c0e980ce46aec8ee9400314669a/fastops) NEON optimized versions

## Base64

There were some NEON [optimizations](https://github.com/powturbo/Turbo-Base64/commit/eed535a8c4b9e3886a8cb7ed43c8e7155ae1e070) since the last fetch

## Simdjson

There were [optimizations](https://github.com/simdjson/simdjson/commit/64b62fd3b320b038f1aa53beb8d1838557ec6153) since the last fetch

## Zlib-ng

There were lots of [optimizations](https://github.com/zlib-ng/zlib-ng/commits/develop/arch/arm)

# Code inside ClickHouse

# General instructions

Use [SSE2NEON](https://github.com/DLTcollab/sse2neon) as a piece of documentation, if there 1to1 mapping, that's great, if not, for example, for _mm_movemask_epi8, think of different approach

## [src/Common/memcpySmall.h](https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/memcpySmall.h)

**Difficulty**: easy

```cpp
while (n > 0)
{
    _mm_storeu_si128(reinterpret_cast<__m128i *>(dst),
        _mm_loadu_si128(reinterpret_cast<const __m128i *>(src)));

    dst += 16;
    src += 16;
    n -= 16;
}
```

Easy load store: vst1q, vld1q

## [src/Common/memcmpSmall.h](https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/memcmpSmall.h)

**Difficulty**: moderate

```cpp
inline bool memequal16(const void * a, const void * b)
{
    return 0xFFFF == _mm_movemask_epi8(_mm_cmpeq_epi8(
        _mm_loadu_si128(reinterpret_cast<const __m128i *>(a)),
        _mm_loadu_si128(reinterpret_cast<const __m128i *>(b))));
}
```

Has lots of _mm_movemask_epi8, might be good to stick to defaults of memcmp, anyway needs investigation to figure out if we can benefit from additional 15 bytes at the end

## [src/Columns/ColumnsCommon.cpp](https://github.com/ClickHouse/ClickHouse/blob/master/src/Columns/ColumnsCommon.cpp), [src/Columns/ColumnsCommon.h](https://github.com/ClickHouse/ClickHouse/blob/master/src/Columns/ColumnsCommon.h)

**Difficulty**: hard

```cpp
static UInt64 toBits64(const Int8 * bytes64)
{
    static const __m128i zero16 = _mm_setzero_si128();
    UInt64 res =
        static_cast<UInt64>(_mm_movemask_epi8(_mm_cmpeq_epi8(
            _mm_loadu_si128(reinterpret_cast<const __m128i *>(bytes64)), zero16)))
        | (static_cast<UInt64>(_mm_movemask_epi8(_mm_cmpeq_epi8(
            _mm_loadu_si128(reinterpret_cast<const __m128i *>(bytes64 + 16)), zero16))) << 16)
        | (static_cast<UInt64>(_mm_movemask_epi8(_mm_cmpeq_epi8(
            _mm_loadu_si128(reinterpret_cast<const __m128i *>(bytes64 + 32)), zero16))) << 32)
        | (static_cast<UInt64>(_mm_movemask_epi8(_mm_cmpeq_epi8(
            _mm_loadu_si128(reinterpret_cast<const __m128i *>(bytes64 + 48)), zero16))) << 48);

    return ~res;
}
```

Even though it contains _mm_movemask_epi8, AArch64 has [UZP1, UZP2](https://developer.arm.com/documentation/100069/0609/A64-SIMD-Vector-Instructions/UZP1--vector-) which can extract odd/even bytes. Worth exploring the shuffling in that area.

## [src/Interpreters/AggregationCommon.h](https://github.com/ClickHouse/ClickHouse/blob/master/src/Interpreters/AggregationCommon.h) and [src/Common/ColumnsHashing.h](https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ColumnsHashing.h)

**Difficulty**: easy

```cpp
#if defined(__SSSE3__) && !defined(MEMORY_SANITIZER)
template <typename T>
static T inline packFixedShuffle(
    const char * __restrict * __restrict srcs,
    size_t num_srcs,
    const size_t * __restrict elem_sizes,
    size_t idx,
    const uint8_t * __restrict masks)
{
    assert(num_srcs > 0);

    __m128i res = _mm_shuffle_epi8(
        _mm_loadu_si128(reinterpret_cast<const __m128i *>(srcs[0] + elem_sizes[0] * idx)),
        _mm_loadu_si128(reinterpret_cast<const __m128i *>(masks)));

    for (size_t i = 1; i < num_srcs; ++i)
    {
        res = _mm_xor_si128(res,
            _mm_shuffle_epi8(
                _mm_loadu_si128(reinterpret_cast<const __m128i *>(srcs[i] + elem_sizes[i] * idx)),
                _mm_loadu_si128(reinterpret_cast<const __m128i *>(&masks[i * sizeof(T)]))));
    }

    T out;
    __builtin_memcpy(&out, &res, sizeof(T));
    return out;
}
#endif
```

All _mm_shuffle_epi8 can be replaced with correct vqtbl1q_s8, don't forget to check high bits of masks!

## [src/Common/CpuId.h](https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/CpuId.h)

**Difficulty**: easy

```cpp
inline bool cpuid(UInt32 op, UInt32 * res) noexcept /// NOLINT
{
#if defined(__x86_64__) || defined(__i386__)
    __cpuid(op, res[0], res[1], res[2], res[3]);
    return true;
#else
    (void)op;

    memset(res, 0, 4 * sizeof(*res));

    return false;
#endif
}
```

Figure out if used, add NEON from [getauxval](https://man7.org/linux/man-pages/man3/getauxval.3.html) if needed

## [src/Common/IPv6ToBinary.cpp](https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/IPv6ToBinary.cpp)

**Difficulty**: moderate

```cpp
bool matchIPv6Subnet(const uint8_t * addr, const uint8_t * cidr_addr, UInt8 prefix)
{
    uint16_t mask = _mm_movemask_epi8(_mm_cmpeq_epi8(
        _mm_loadu_si128(reinterpret_cast<const __m128i *>(addr)),
        _mm_loadu_si128(reinterpret_cast<const __m128i *>(cidr_addr))));
    mask = ~mask;

    if (mask)
    {
        auto offset = __builtin_ctz(mask);

        if (prefix / 8 != offset)
            return prefix / 8 < offset;

        auto cmpmask = ~(0xff >> (prefix % 8));
        return (addr[offset] & cmpmask) == (cidr_addr[offset] & cmpmask);
    }
    return true;
}
```

Again movemask, figure out if beneficial.

## [src/Common/remapExecutable.cpp](https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/remapExecutable.cpp)

**Difficulty**: hard

```cpp
__attribute__((__noinline__)) int64_t our_syscall(...)
{
    __asm__ __volatile__ (R"(
        movq %%rdi,%%rax;
        movq %%rsi,%%rdi;
        movq %%rdx,%%rsi;
        movq %%rcx,%%rdx;
        movq %%r8,%%r10;
        movq %%r9,%%r8;
        movq 8(%%rsp),%%r9;
        syscall;
        ret
    )" : : : "memory");
    return 0;
}

{
        __m128i * __restrict dst = reinterpret_cast<__m128i *>(begin);
        const __m128i * __restrict src = reinterpret_cast<const __m128i *>(scratch);
        const __m128i * __restrict src_end = reinterpret_cast<const __m128i *>(reinterpret_cast<const char *>(scratch) + size);
        while (src < src_end)
        {
            _mm_storeu_si128(dst, _mm_loadu_si128(src));

            ++dst;
            ++src;
        }
    }
```

I don't see any blockers, should be doable but requires meticulous testing. Need to figure out calling conventions for ARM syscalls.

## [src/Common/StringSearcher.h](https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/StringSearcher.h)

**Difficulty**: hard

```cpp
#ifdef __SSE4_1__
        patl = _mm_set1_epi8(l);
        patu = _mm_set1_epi8(u);

        const auto * needle_pos = needle;

        for (const auto i : collections::range(0, n))
        {
            cachel = _mm_srli_si128(cachel, 1);
            cacheu = _mm_srli_si128(cacheu, 1);

            if (needle_pos != needle_end)
            {
                cachel = _mm_insert_epi8(cachel, std::tolower(*needle_pos), n - 1);
                cacheu = _mm_insert_epi8(cacheu, std::toupper(*needle_pos), n - 1);
                cachemask |= 1 << i;
                ++needle_pos;
            }
        }
#endif

const auto v_haystack = _mm_loadu_si128(reinterpret_cast<const __m128i *>(pos));
const auto v_against_l = _mm_cmpeq_epi8(v_haystack, cachel);
const auto v_against_u = _mm_cmpeq_epi8(v_haystack, cacheu);
const auto v_against_l_or_u = _mm_or_si128(v_against_l, v_against_u);
const auto mask = _mm_movemask_epi8(v_against_l_or_u);
```

Lots of movemasks, requires benchmarks, probably additional ones and ideally fully revisit these optimizations. Otherwise I see no blockers, should be able to optimize faster.

## [src/Functions/GatherUtils/sliceHasImplAnyAll.h](https://github.com/ClickHouse/ClickHouse/blob/master/src/Functions/GatherUtils/sliceHasImplAnyAll.h), [src/Common/TargetSpecific.cpp](https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/TargetSpecific.cpp), [src/Functions/FunctionsHashing.h](https://github.com/ClickHouse/ClickHouse/blob/master/src/Functions/FunctionsHashing.h), [src/Functions/FunctionStartsEndsWith.h](https://github.com/ClickHouse/ClickHouse/blob/master/src/Functions/FunctionStartsEndsWith.h), [src/Functions/generateUUIDv4.cpp](https://github.com/ClickHouse/ClickHouse/blob/master/src/Functions/generateUUIDv4.cpp), [src/Functions/greatCircleDistance.cpp](https://github.com/ClickHouse/ClickHouse/blob/master/src/Functions/greatCircleDistance.cpp), [src/Functions/randomFixedString.cpp](https://github.com/ClickHouse/ClickHouse/blob/master/src/Functions/randomFixedString.cpp), [src/Functions/randomString.cpp](https://github.com/ClickHouse/ClickHouse/blob/master/src/Functions/randomString.cpp)

**Difficulty**: hard

```cpp
bitmask =
    _mm_or_si128(
            _mm_or_si128(
                _mm_andnot_si128(
                    first_nm_mask,
                    _mm_cmpeq_epi64(second_data, first_data)),
                _mm_andnot_si128(
                    _mm_shuffle_epi32(first_nm_mask, _MM_SHUFFLE(1,0,3,2)),
                    _mm_cmpeq_epi64(second_data, _mm_shuffle_epi32(first_data, _MM_SHUFFLE(1,0,3,2))))),
        bitmask);
```

Don't see any SIMD blockers, all have 1:1 mapping including _mm_test_all_ones. Huge potential. TargetSpecific.cpp should be updated as well.

Also should support `DECLARE_MULTITARGET_CODE` for AArch64.

## [src/Common/UTF8Helpers.cpp](https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/UTF8Helpers.cpp), [src/Common/UTF8Helpers.h](https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/UTF8Helpers.h)

**Difficulty**: moderate

```cpp
#ifdef __SSE2__
    constexpr auto bytes_sse = sizeof(__m128i);
    const auto * src_end_sse = data + size / bytes_sse * bytes_sse;

    const auto threshold = _mm_set1_epi8(0xBF);

    for (; data < src_end_sse; data += bytes_sse)
        res += __builtin_popcount(_mm_movemask_epi8(
            _mm_cmpgt_epi8(_mm_loadu_si128(reinterpret_cast<const __m128i *>(data)), threshold)));
#endif
```

```cpp
#if defined(__SSE2__)
        const auto lower_bound = _mm_set1_epi8(32);
        const auto upper_bound = _mm_set1_epi8(126);

        while (i + 15 < size)
        {
            __m128i bytes = _mm_loadu_si128(reinterpret_cast<const __m128i *>(&data[i]));

            const uint16_t non_regular_width_mask = _mm_movemask_epi8(
                _mm_or_si128(
                    _mm_cmplt_epi8(bytes, lower_bound),
                    _mm_cmpgt_epi8(bytes, upper_bound)));

            if (non_regular_width_mask)
            {
                auto num_regular_chars = __builtin_ctz(non_regular_width_mask);
                width += num_regular_chars;
                i += num_regular_chars;
                break;
            }
            else
            {
                i += 16;
                width += 16;
            }
        }
#endif
```

16 byte skip of ASCIIs, again UZP1, UZP2 trick might work. At least add 8 byte skip if needed, right now only one 1 byte skip

```cpp
while (i < size && isPrintableASCII(data[i]))
{
    ++width;
    ++i;
}
```

## [src/DataTypes/Serializations/SerializationString.cpp](https://github.com/ClickHouse/ClickHouse/blob/master/src/DataTypes/Serializations/SerializationString.cpp)

**Difficulty**: easy

```cpp
#ifdef __SSE2__
            /// An optimistic branch in which more efficient copying is possible.
            if (offset + 16 * UNROLL_TIMES <= data.capacity() && istr.position() + size + 16 * UNROLL_TIMES <= istr.buffer().end())
            {
                const __m128i * sse_src_pos = reinterpret_cast<const __m128i *>(istr.position());
                const __m128i * sse_src_end = sse_src_pos + (size + (16 * UNROLL_TIMES - 1)) / 16 / UNROLL_TIMES * UNROLL_TIMES;
                __m128i * sse_dst_pos = reinterpret_cast<__m128i *>(&data[offset - size - 1]);

                while (sse_src_pos < sse_src_end)
                {
                    for (size_t j = 0; j < UNROLL_TIMES; ++j)
                        _mm_storeu_si128(sse_dst_pos + j, _mm_loadu_si128(sse_src_pos + j));

                    sse_src_pos += UNROLL_TIMES;
                    sse_dst_pos += UNROLL_TIMES;
                }

                istr.position() += size;
            }
            else
#endif
```

No blockers for loads, stores. You can also write absolutely portable version through `memcpy(dst, src, 16)`

## [src/Functions/divide/divide.cpp](https://github.com/ClickHouse/ClickHouse/blob/master/src/Functions/divide/divide.cpp), [src/Functions/divide/divideImpl.cpp](https://github.com/ClickHouse/ClickHouse/blob/master/src/Functions/divide/divideImpl.cpp)

**Difficulty**: easy

```cpp
#if defined(__x86_64__)
    if (DB::Cpu::CpuFlagsCache::have_AVX2)
        AVX2::divideImpl(a_pos, b, c_pos, size);
    else if (DB::Cpu::CpuFlagsCache::have_SSE2)
        SSE2::divideImpl(a_pos, b, c_pos, size);
#else
    Generic::divideImpl(a_pos, b, c_pos, size);
#endif

#if defined(__SSE2__)
    static constexpr size_t values_per_simd_register = REG_SIZE / sizeof(A);
    const A * a_end_simd = a_pos + size / values_per_simd_register * values_per_simd_register;

    while (a_pos < a_end_simd)
    {
#if defined(__AVX2__)
        _mm256_storeu_si256(reinterpret_cast<__m256i *>(c_pos),
            _mm256_loadu_si256(reinterpret_cast<const __m256i *>(a_pos)) / divider);
#else
        _mm_storeu_si128(reinterpret_cast<__m128i *>(c_pos),
            _mm_loadu_si128(reinterpret_cast<const __m128i *>(a_pos)) / divider);
#endif

        a_pos += values_per_simd_register;
        c_pos += values_per_simd_register;
    }
#endif
```

No blockers to support AArch64 given libdivide supports it.

## [src/Functions/FunctionsCodingIP.cpp](https://github.com/ClickHouse/ClickHouse/blob/master/src/Functions/FunctionsCodingIP.cpp)

**Difficulty**: easy

```cpp
#if defined(__SSE2__)

#include <emmintrin.h>

    static inline void applyCIDRMask(const UInt8 * __restrict src, UInt8 * __restrict dst_lower, UInt8 * __restrict dst_upper, UInt8 bits_to_keep)
    {
        __m128i mask = _mm_loadu_si128(reinterpret_cast<const __m128i *>(getCIDRMaskIPv6(bits_to_keep).data()));
        __m128i lower = _mm_and_si128(_mm_loadu_si128(reinterpret_cast<const __m128i *>(src)), mask);
        _mm_storeu_si128(reinterpret_cast<__m128i *>(dst_lower), lower);

        __m128i inv_mask = _mm_xor_si128(mask, _mm_cmpeq_epi32(_mm_setzero_si128(), _mm_setzero_si128()));
        __m128i upper = _mm_or_si128(lower, inv_mask);
        _mm_storeu_si128(reinterpret_cast<__m128i *>(dst_upper), upper);
    }

#else
```

No blockers, should be 1:1.

## [src/Functions/FunctionsRandom.cpp](https://github.com/ClickHouse/ClickHouse/blob/master/src/Functions/FunctionsRandom.cpp), [src/Functions/FunctionsRandom.h](https://github.com/ClickHouse/ClickHouse/blob/master/src/Functions/FunctionsRandom.h)

**Difficulty**: uncertain

```cpp
inline UInt64x4 combineValues(UInt64x4 a, UInt64x4 b)
{
    auto xa = reinterpret_cast<__m256i>(a);
    auto xb = reinterpret_cast<__m256i>(b);
    /// Every state is 8-byte value and we need to use only 4 from the middle.
    /// Swap the low half and the high half of every state to move these bytes from the middle to sides.
    /// xa = xa[1, 0, 3, 2, 5, 4, 7, 6]
    xa = _mm256_shuffle_epi32(xa, 0xb1);
    /// Now every 8-byte value in xa is xx....xx and every value in xb is ..xxxx.. where x is random byte we want to use.
    /// Just blend them to get the result vector.
    /// result = xa[0],xb[1,2],xa[3,4],xb[5,6],xa[7,8],xb[9,10],xa[11,12],xb[13,14],xa[15]
    __m256i result = _mm256_blend_epi16(xa, xb, 0x66);
    return reinterpret_cast<UInt64x4>(result);
}
```

Might be worth investigating some approach for blending 16 byte vectors for NEON with zip/unzip instructions.

## [src/Functions/FunctionsRound.h](https://github.com/ClickHouse/ClickHouse/blob/master/src/Functions/FunctionsRound.h)

**Difficulty**: moderate

```cpp
    static VectorType load(const ScalarType * in) { return _mm_loadu_ps(in); }
    static VectorType load1(const ScalarType in) { return _mm_load1_ps(&in); }
    static void store(ScalarType * out, VectorType val) { _mm_storeu_ps(out, val);}
    static VectorType multiply(VectorType val, VectorType scale) { return _mm_mul_ps(val, scale); }
    static VectorType divide(VectorType val, VectorType scale) { return _mm_div_ps(val, scale); }
    template <RoundingMode mode> static VectorType apply(VectorType val) { return _mm_round_ps(val, int(mode)); }
```

Neon has all kinds of vrndnq_f32, vrndq_f32, vrndiq_f32. Should be doable.

## [src/Functions/isValidUTF8.cpp](https://github.com/ClickHouse/ClickHouse/blob/master/src/Functions/isValidUTF8.cpp)

**Difficulty**: easy

```cpp
/* tmp1 = saturate_sub(first_len, 1) */
tmp1 = _mm_subs_epu8(first_len, _mm_set1_epi8(1));
/* tmp2 = saturate_sub(prev_first_len, 1) */
tmp2 = _mm_subs_epu8(prev_first_len, _mm_set1_epi8(1));
/* range |= (tmp1, tmp2) << 2 bytes */
range = _mm_or_si128(range, _mm_alignr_epi8(tmp1, tmp2, 14));

/* Fourth Byte: set range index to saturate_sub(first_len, 2) */
/* 0 for 00~7F, 0 for C0~DF, 0 for E0~EF, 1 for F0~FF */
/* tmp1 = saturate_sub(first_len, 2) */
tmp1 = _mm_subs_epu8(first_len, _mm_set1_epi8(2));
/* tmp2 = saturate_sub(prev_first_len, 2) */
tmp2 = _mm_subs_epu8(prev_first_len, _mm_set1_epi8(2));
/* range |= (tmp1, tmp2) << 3 bytes */
range = _mm_or_si128(range, _mm_alignr_epi8(tmp1, tmp2, 13));
```

Taken from https://github.com/cyb70289/utf8/, it has NEON accelerated version, we should just add it.

## [src/Functions/LowerUpperImpl.h](https://github.com/ClickHouse/ClickHouse/blob/master/src/Functions/LowerUpperImpl.h)

**Difficulty**: easy

```cpp
#ifdef __SSE2__
        const auto bytes_sse = sizeof(__m128i);
        const auto * src_end_sse = src_end - (src_end - src) % bytes_sse;
        const auto v_not_case_lower_bound = _mm_set1_epi8(not_case_lower_bound - 1);
        const auto v_not_case_upper_bound = _mm_set1_epi8(not_case_upper_bound + 1);
        const auto v_flip_case_mask = _mm_set1_epi8(flip_case_mask);
        for (; src < src_end_sse; src += bytes_sse, dst += bytes_sse)
        {
            /// load 16 sequential 8-bit characters
            const auto chars = _mm_loadu_si128(reinterpret_cast<const __m128i *>(src));
            /// find which 8-bit sequences belong to range [case_lower_bound, case_upper_bound]
            const auto is_not_case
                = _mm_and_si128(_mm_cmpgt_epi8(chars, v_not_case_lower_bound), _mm_cmplt_epi8(chars, v_not_case_upper_bound));
            /// keep `flip_case_mask` only where necessary, zero out elsewhere
            const auto xor_mask = _mm_and_si128(v_flip_case_mask, is_not_case);
            /// flip case by applying calculated mask
            const auto cased_chars = _mm_xor_si128(chars, xor_mask);
            /// store result back to destination
            _mm_storeu_si128(reinterpret_cast<__m128i *>(dst), cased_chars);
        }
#endif
```

No blockers.

## [src/Functions/LowerUpperUTF8Impl.h](https://github.com/ClickHouse/ClickHouse/blob/master/src/Functions/LowerUpperUTF8Impl.h)

**Difficulty**: moderate

```cpp
const auto is_not_case
    = _mm_and_si128(_mm_cmpgt_epi8(chars, v_not_case_lower_bound), _mm_cmplt_epi8(chars, v_not_case_upper_bound));
const auto mask_is_not_case = _mm_movemask_epi8(is_not_case);
/// everything in correct case ASCII
if (mask_is_not_case == 0)
    _mm_storeu_si128(reinterpret_cast<__m128i *>(dst), chars);
else
{
    /// ASCII in mixed case
    /// keep `flip_case_mask` only where necessary, zero out elsewhere
    const auto xor_mask = _mm_and_si128(v_flip_case_mask, is_not_case);
    /// flip case by applying calculated mask
    const auto cased_chars = _mm_xor_si128(chars, xor_mask);
    /// store result back to destination
    _mm_storeu_si128(reinterpret_cast<__m128i *>(dst), cased_chars);
}
```

Movemask with uzp1/2 should be doable. Needs benchmarks

## [src/Functions/modulo.cpp](https://github.com/ClickHouse/ClickHouse/blob/master/src/Functions/modulo.cpp), [src/Interpreters/createBlockSelector.cpp](https://github.com/ClickHouse/ClickHouse/blob/master/src/Interpreters/createBlockSelector.cpp)

**Difficulty**: easy

```cpp
#if defined(__SSE2__)
#    define LIBDIVIDE_SSE2 1
#endif
```

Should enable AArch64 as well.

## [src/Functions/toValidUTF8.cpp](https://github.com/ClickHouse/ClickHouse/blob/master/src/Functions/toValidUTF8.cpp), [src/IO/WriteBufferValidUTF8.cpp](https://github.com/ClickHouse/ClickHouse/blob/master/src/IO/WriteBufferValidUTF8.cpp)

**Difficulty**: moderate

```cpp
#ifdef __SSE2__
            /// Fast skip of ASCII
            static constexpr size_t SIMD_BYTES = 16;
            const char * simd_end = p + (end - p) / SIMD_BYTES * SIMD_BYTES;

            while (p < simd_end && !_mm_movemask_epi8(_mm_loadu_si128(reinterpret_cast<const __m128i *>(p))))
                p += SIMD_BYTES;

            if (!(p < end))
                break;
#endif
```

UZP1/UZP2 trick as well.

## [src/Interpreters/ITokenExtractor.cpp](https://github.com/ClickHouse/ClickHouse/blob/master/src/Interpreters/ITokenExtractor.cpp)

**Difficulty**: hard

```cpp
#if defined(__SSE4_2__)
        // With the help of https://www.strchr.com/strcmp_and_strlen_using_sse_4.2
        const auto alnum_chars_ranges = _mm_set_epi8(0, 0, 0, 0, 0, 0, 0, 0,
                '\xFF', '\x80', 'z', 'a', 'Z', 'A', '9', '0');
        // Every bit represents if `haystack` character is in the ranges (1) or not (0)
        const int result_bitmask = _mm_cvtsi128_si32(_mm_cmpestrm(alnum_chars_ranges, 8, haystack, haystack_length, _SIDD_CMP_RANGES));
#else
        // NOTE: -1 and +1 required since SSE2 has no `>=` and `<=` instructions on packed 8-bit integers (epi8).
        const auto number_begin =      _mm_set1_epi8('0' - 1);
        const auto number_end =        _mm_set1_epi8('9' + 1);
        const auto alpha_lower_begin = _mm_set1_epi8('a' - 1);
        const auto alpha_lower_end =   _mm_set1_epi8('z' + 1);
        const auto alpha_upper_begin = _mm_set1_epi8('A' - 1);
        const auto alpha_upper_end =   _mm_set1_epi8('Z' + 1);
        const auto zero =              _mm_set1_epi8(0);

        // every bit represents if `haystack` character `c` satisfies condition:
        // (c < 0) || (c > '0' - 1 && c < '9' + 1) || (c > 'a' - 1 && c < 'z' + 1) || (c > 'A' - 1 && c < 'Z' + 1)
        // < 0 since _mm_cmplt_epi8 threats chars as SIGNED, and so all chars > 0x80 are negative.
        const int result_bitmask = _mm_movemask_epi8(_mm_or_si128(_mm_or_si128(_mm_or_si128(
                _mm_cmplt_epi8(haystack, zero),
                _mm_and_si128(_mm_cmpgt_epi8(haystack, number_begin),      _mm_cmplt_epi8(haystack, number_end))),
                _mm_and_si128(_mm_cmpgt_epi8(haystack, alpha_lower_begin), _mm_cmplt_epi8(haystack, alpha_lower_end))),
                _mm_and_si128(_mm_cmpgt_epi8(haystack, alpha_upper_begin), _mm_cmplt_epi8(haystack, alpha_upper_end))));
#endif
```

No matching of SSE4_2 but second part might be worth exploring.

## [src/IO/ReadHelpers.cpp](https://github.com/ClickHouse/ClickHouse/blob/master/src/IO/ReadHelpers.cpp)

**Difficulty**: moderate

```cpp
#ifdef __SSE2__
                auto rc = _mm_set1_epi8('\r');
                auto nc = _mm_set1_epi8('\n');
                auto dc = _mm_set1_epi8(delimiter);
                for (; next_pos + 15 < buf.buffer().end(); next_pos += 16)
                {
                    __m128i bytes = _mm_loadu_si128(reinterpret_cast<const __m128i *>(next_pos));
                    auto eq = _mm_or_si128(_mm_or_si128(_mm_cmpeq_epi8(bytes, rc), _mm_cmpeq_epi8(bytes, nc)), _mm_cmpeq_epi8(bytes, dc));
                    uint16_t bit_mask = _mm_movemask_epi8(eq);
                    if (bit_mask)
                    {
                        next_pos += __builtin_ctz(bit_mask);
                        return;
                    }
                }
#endif
```

Same movemask challenge

## [src/Storages/MergeTree/MergeTreeRangeReader.cpp](https://github.com/ClickHouse/ClickHouse/blob/master/src/Storages/MergeTree/MergeTreeRangeReader.cpp)

**Difficulty**: moderate

```cpp
#if defined(__SSE2__) && defined(__POPCNT__)
    const __m128i zero16 = _mm_setzero_si128();
    while (end - begin >= 64)
    {
        end -= 64;
        const auto * pos = end;
        UInt64 val =
                static_cast<UInt64>(_mm_movemask_epi8(_mm_cmpeq_epi8(
                        _mm_loadu_si128(reinterpret_cast<const __m128i *>(pos)),
                        zero16)))
                | (static_cast<UInt64>(_mm_movemask_epi8(_mm_cmpeq_epi8(
                        _mm_loadu_si128(reinterpret_cast<const __m128i *>(pos + 16)),
                        zero16))) << 16u)
                | (static_cast<UInt64>(_mm_movemask_epi8(_mm_cmpeq_epi8(
                        _mm_loadu_si128(reinterpret_cast<const __m128i *>(pos + 32)),
                        zero16))) << 32u)
                | (static_cast<UInt64>(_mm_movemask_epi8(_mm_cmpeq_epi8(
                        _mm_loadu_si128(reinterpret_cast<const __m128i *>(pos + 48)),
                        zero16))) << 48u);
        val = ~val;
        if (val == 0)
            count += 64;
        else
        {
            count += __builtin_clzll(val);
            return count;
        }
    }
#endif
```

Same uzp1/uzp2 trick should work

## [src/Common/HashTable/Hash.h](https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/HashTable/Hash.h), [src/Common/HashTable/StringHashTable.h](https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/HashTable/StringHashTable.h), [src/Functions/FunctionsStringHash.cpp](https://github.com/ClickHouse/ClickHouse/blob/master/src/Functions/FunctionsStringHash.cpp), [src/Functions/FunctionsStringSimilarity.cpp](https://github.com/ClickHouse/ClickHouse/blob/master/src/Functions/FunctionsStringSimilarity.cpp)

**Difficulty**: moderate

```cpp
#ifdef __SSE4_2__

struct UInt256HashCRC32
{
    size_t operator()(UInt256 x) const
    {
        UInt64 crc = -1ULL;
        crc = _mm_crc32_u64(crc, x.items[0]);
        crc = _mm_crc32_u64(crc, x.items[1]);
        crc = _mm_crc32_u64(crc, x.items[2]);
        crc = _mm_crc32_u64(crc, x.items[3]);
        return crc;
    }
};

#else

/// We do not need to use CRC32 on other platforms. NOTE This can be confusing.
struct UInt256HashCRC32 : public UInt256Hash {};

#endif
```

Not all places are optimized with CRC which aarch64 absolutely has.

**Comment by UnamedRus** [comment]
AFAIK CRC32Hash doesn't work on arm at all: https://github.com/ClickHouse/ClickHouse/issues/35664

**Comment by alexey-milovidov** [comment]
@UnamedRus You are messing CRC32, which is only available as SQL function with CRC32-C which is used as a hash function for many internal data structures.

**Comment by pan3793** [comment]
Could you please consider adding gRPC support on AArch64? Ref: https://github.com/ClickHouse/ClickHouse/pull/36754#issuecomment-1112538464

**Comment by rschu1ze** [comment]
Not directly about performance but related: ARM64 currently has no stack unwinding: #37044.

**Comment by danlark1** [comment]
For 64 bit mask you can use something like [this](https://github.com/facebook/zstd/blob/f349d18776001f39791323e59ef2395983c1cd2e/lib/compress/zstd_lazy.c#L1023)

```cpp
*src = "The past is a foreign country; they do things differently there."

// ld4 (vld4q_u8)
dst.val[0] = "Tp arnuyhdhsfeye"
dst.val[1] = "hai e n;eoi fn r"
dst.val[2] = "essfict y ndette"
dst.val[3] = " t ogort tgirlh."

// Combine and interleave 64-byte comparisons into a single 64-bit bitmask.
// vsriq_n_u8() is the intrinsic for VSRI, Vector Shift Right and Insert.
// Each VSRI shifts each byte in the operand vector by an immediate value
// and merges the result with the destination vector by copying only the set
// bits. This allows us to re-interleave as we reduce to 64 bits, such that
// the index of each bit in the resultant mask corresponds to the match
// status of the byte of the same index in the input.
// Merge 1, 2, 4 bits
uint8x16_t result1 = vsriq_n_u8(comparison2, comparison1, 1);
uint8x16_t result2 = vsriq_n_u8(comparison4, comparison3, 1);
uint8x16_t result3 = vsriq_n_u8(result2, result1, 2);
uint8x16_t result4 = vsriq_n_u8(result3, result3, 4);
// Shift to move 4 bits of each byte
uint8x8_t result = vshrn_n_u16(vreinterpretq_u16_u8(result4), 4);
```

Can be used for something in [src/Columns/ColumnsCommon.cpp](https://github.com/ClickHouse/ClickHouse/blob/master/src/Columns/ColumnsCommon.cpp), [src/Columns/ColumnsCommon.h](https://github.com/ClickHouse/ClickHouse/blob/master/src/Columns/ColumnsCommon.h) and others who use 64 bit masks
