### ISSUE TITLE
При использовании функции ODBC для Postgres в столбец типа Date приходит NULL

### ISSUE THREAD

**Issue by yutrostin** [ClickHouse/ClickHouse#3700]
При попытке экспорта таблицы из Postgres с помощью функции ODBC в поле типа Date приходит либо NULL, либо 0000-00-00, либо 1970-01-01. Использую версию v1.0.0.20181017

Допустим, в Postgres есть таблица users, где есть столбцы:

- created_at DateTime NOT NULL
- birthday Date
- name Varchar

Настроен DSN postgres_database для подключения. В КХ выполняете команду:
`SELECT * FROM odbc('DSN=postgres_database', 'users')`

При ее выполнении в КХ приедут данные из таблицы users, со столбцами created_at и name все будет хорошо, а вот в birthday приедет NULL.

**Comment by alesapin** [comment]
На какой версии ClickHouse это воспроизводится? Сделайте, пожалуйста, полный пример воспроизведения проблемы.

> Использую версию v1.0.0.20181017
Это версия чего?

**Comment by yutrostin** [comment]
сейчас использую версию КХ `19.4.0`

Воспроизведение проблемы:
1. Поднимаете постгрес, создаете базу данных `postgres_database` и в ней таблицу `users` со следующими столбцами:
* created_at DateTime NOT NULL
* birthday Date
* name Varchar

Создаете в ней записи
2. Настраиваете на сервере КХ DSN так, чтобы можно было подключиться к этому постгресу
3. В КХ исполняете `SELECT * FROM odbc('DSN=postgres_database', 'users')`

В поле birthday в КХ после исполнения этого запроса будет либо NULL, либо 0000-00-00, либо 1970-01-01

**Comment by Tri0L** [comment]
Поймал такое же поведение на версии CH `20.1.2.4`.

Помогло конвертирование даты в timestamp.
Для словарей используем вот такой грязный хак:
```
        <expression>cast(my_date_param as timestamp)</expression>
```

**Comment by van4oza** [comment]
> Поймал такое же поведение на версии CH `20.1.2.4`.
> 
> Помогло конвертирование даты в timestamp.
> Для словарей используем вот такой грязный хак:
> 
> ```
>         <expression>cast(my_date_param as timestamp)</expression>
> ```

ClickHouse server version 20.4.5.36 (official build).
ClickHouse client version 20.4.5.36 (official build).

Получается такой запрос, Postgres 10 ругается на запятую в CAST.

`SELECT "id", (CAST(changed, 'timestamp')) AS "changed" FROM "serpent_client";`

**Comment by den-crane** [comment]
I marked it prio-major because it's annoying question. I see it very often in chats.

**Comment by alexey-milovidov** [comment]
Please provide full steps to reproduce.

**Comment by erste** [comment]
>     changed      Date EXPRESSION cast(changed as timestamp)
@van4oza попробуйте c кавычками:
```
changed      Date EXPRESSION 'cast(changed as timestamp)'
```

**Comment by kssenii** [comment]
Fixed in https://github.com/ClickHouse/ClickHouse/pull/17301
