### ISSUE TITLE
Could Clickhouse  predict  time-series?

### ISSUE THREAD

**Issue by wangqinghuan** [ClickHouse/ClickHouse#37029]
I learned [MindsDB](https://clickhouse.com/blog/how-to-enable-predictive-capabilities-in-clickhouse-databases/) can provide time-series analysis on data. Does Clickhouse have plan support time-series predict function?

**Comment by melvynator** [comment]
You can find the roadmap for 2022 https://github.com/ClickHouse/ClickHouse/issues/32513

It's not on the short-term roadmap.
