### ISSUE TITLE
Question with row policies 

### ISSUE THREAD

**Issue by kaynewu** [ClickHouse/ClickHouse#37041]
Using 22.2.3.1

I have a table in clickhouse and I want that some users can only access to certain rows.
For that, I've created a row policy:

CREATE ROW POLICY user1_fliter ON default.product FOR SELECT USING productType = 120 TO user1

productType is a PARTITION  key

Q1: 'select * from default.product order by time limit 100'  Processed 10.0 thousand rows,
Q2: 'select * from default.product where productType = 120  order by time limit 100'  Processed 1.0 thousand rows,

It seems  query without productType condition it still scan all the partitions,
how to make Q1 work with only scan productType = 120 partition?
Thanks!

**Comment by den-crane** [comment]
This optimization is not implemented.

**Comment by kaynewu** [comment]
> This optimization is not implemented.

Is there any other way to achieve this, for now?
