### ISSUE TITLE
show error: unable to create target: 'No available targets are compatible with triple "aarch64-unknown-linux-gnu"'

### ISSUE THREAD

**Issue by songzhian** [ClickHouse/ClickHouse#37060]
> Make sure that `git diff` result is empty and you've just pulled fresh master. Try cleaning up cmake cache. Just in case, official build instructions are published here: https://clickhouse.com/docs/en/development/build/

**Operating system**
aarch64

**Cmake version**
 cmake 3.21.0-rc1
**Ninja version**

**Compiler name and version**
clang 13.0.0
**Full cmake and/or ninja output**
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: /usr/local/llvm/bin/clang
-- Check for working C compiler: /usr/local/llvm/bin/clang - broken
CMake Error at /usr/local/share/cmake-3.21/Modules/CMakeTestCCompiler.cmake:66 (message):
  The C compiler

    "/usr/local/llvm/bin/clang"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/test/use/gito/ClickHouse2/build/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/gmake -f Makefile cmTC_cbc57/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_cbc57.dir/build.make CMakeFiles/cmTC_cbc57.dir/build
    gmake[1]: 进入目录“/home/test/use/gito/ClickHouse2/build/CMakeFiles/CMakeTmp”
    Building C object CMakeFiles/cmTC_cbc57.dir/testCCompiler.c.o
    /usr/local/llvm/bin/clang    -o CMakeFiles/cmTC_cbc57.dir/testCCompiler.c.o -c /home/test/use/gito/ClickHouse2/build/CMakeFiles/CMakeTmp/testCCompiler.c
    error: unable to create target: 'No available targets are compatible with triple "aarch64-unknown-linux-gnu"'
    1 error generated.
    gmake[1]: *** [CMakeFiles/cmTC_cbc57.dir/build.make:78：CMakeFiles/cmTC_cbc57.dir/testCCompiler.c.o] 错误 1
    gmake[1]: 离开目录“/home/test/use/gito/ClickHouse2/build/CMakeFiles/CMakeTmp”
    gmake: *** [Makefile:127：cmTC_cbc57/fast] 错误 2
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:35 (project)

**Comment by alexey-milovidov** [comment]
We don't support using `gmake` as a build job runner. Only `ninja` is supported.
