### ISSUE TITLE
column and table access management 

### ISSUE THREAD

**Issue by Ravojay** [ClickHouse/ClickHouse#37062]
In the official documentation and other documents, I could only find access management of database/row in the following formats (if not using sql)
`<user1>
    <databases>
        <database_name>
            <table1>
                <filter>id = 1000</filter>
            </table1>
        </database_name>
    </databases>
</user1>`

`        <allow_databases>
           <database>test</database>
        </allow_databases>`

is there any way to manage table/column access using xml? eg. granting user with access to only databaseA.tableA and not databaseA.tableB.

**Comment by melvynator** [comment]
Thank you for creating this GitHub issue.

It's not implemented in XML. Using XML you won't be able to create a column or table-level security.

If you want to define such a thing you will need to use SQL queries.

**Comment by melvynator** [comment]
@Ravojay Why would you want to do it in XML rather than using SQL queries?

**Comment by Ravojay** [comment]
> @Ravojay Why would you want to do it in XML rather than using SQL queries?
@melvynator 
we are using clickhouse on containers, so need to copy the access control file/system tables if the containers migrate in the self-healing process. would be possible, need development though.
The xml files are generated by service inside our company based on some configuration file we provide. So would be easier for us this way.
Looks like we have to adopt the sql driven way if we want access control on all granularities.

Thanks for the reply!
