### ISSUE TITLE
graphite_rollup tag value with space

### ISSUE THREAD

**Issue by Hipska** [ClickHouse/ClickHouse#37084]
Hi, I'm trying to specify a `graphite_rollup` pattern where I want to match a tagged metric where the value of the tag has a space in it.

I tried `<regexp>technology=Evolved Backhaul;hostname=EBH-.*</regexp>` and also `<regexp>technology=Evolved\sBackhaul;hostname=EBH-.*</regexp>`, but both don't work. So I'm using `<regexp>technology=Evolved.Backhaul;hostname=EBH-.*</regexp>` in the meantime, but that matches any character and not just space.

Is this a bug or do i need to do some escaping? The docs are not helpful in this specific case.

**Comment by alexey-milovidov** [comment]
> Okay, it looks like those data are stored with + character instead of a space :face_with_rolling_eyes:

**Comment by Hipska** [comment]
@alexey-milovidov it looks like that was a mistake by `carbon-clickhouse`. The tags are again stored with an actual space. Can this issue be re-opened please?

**Comment by Hipska** [comment]
The working solution is to use `<regexp>technology=Evolved\+Backhaul;hostname=EBH-.*</regexp>`.
