### ISSUE TITLE
proposal: groupArraySorted ? 

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#3708]
there is already groupArray, there is also arraySort, merging of two sorted arrays is O(n+m) operation.
Is it possible to implement groupArraySorted? And also with limit? With limit it should be efficient even on very big datasets.

It could be used to solve 'take fist/last N elements in each group' / lastpoint -alike tasks in selects and incrementally in materialized view (with AggregatingMergeTree).

**Comment by amosbird** [comment]
I'd like to  share my two cents from several months ago. The following is a dialog with @alexey-milovidov 

```
Amos Bird, [30.07.18 16:42]
Hi, I'm thinking of extending the groupArray function for a while. The idea is
to add an additional order by clause as a decorator to each groupArray function.
It's like a WINDOW clause but performs at the aggregation phase. Since it's an
intrusive implementation, we have the oppotunities to build arbitrary operators
over WINDOW FUNCTIONS.


table_a :

| x | y | z |
-------------
| 1 | 2 | 2 |
| 2 | 2 | 2 |
| 3 | 3 | 2 |
| 2 | 4 | 4 |
| 4 | 5 | 4 |
| 3 | 6 | 4 |
| 5 | 7 | 6 |
| 7 | 7 | 6 |
| 8 | 2 | 6 |
-------------

SELECT groupArray(x) OVER (ORDER BY y DESC, z) c1, groupArray(y) OVER (w) c2
FROM table_a ORDER o AS (ORDER BY x) GROUP BY z;

output:

|   c1     |    c2    |
-----------------------
|[3, 2, 1] | [2, 2, 3]|
|[3, 4, 2] | [4, 6, 5]|
|[5, 7, 8] | [7, 7, 2]|
-----------------------

Then we can add a bunch of array functions operating on these ordered arrays. What do you think?

Alexey Milovidov, [30.07.18 20:55]
Hi! Good idea and notation is reasonable, but it could be difficult or non-efficient in implementation - because you have to buffer sorted values before passing to aggregate function.
```

**Comment by filimonov** [comment]
I see few options of implementation possible
1) the most straight ahead: two parameters first used as sorting key, second - containing data.
```sql
select groupArraySorted( timestamp, page_type ); -- unlimited
select groupArraySorted(1000)( timestamp, page_type ); -- limited to first 1000
select groupArraySorted(-1000)( timestamp, page_type ); -- syntax sugar, handy but not necessary, 
```
That is simpler in implementation (as all needed 'parts of the puzzle' already there), but will need to process two arrays at at time (one with sorting key, second - with the data), and agregation function state will need to store 2 arrays. Quite often it will lead to data duplication (i.e. if you need to collect the same column as used for sorting),

2) with Schwartzian transform - that can be harder as it needs to store & parse lambda in data type. It can have some advantages (syntax conform to arraySort, one array to store & process, code for supporting aggregate functions with lambdas can be reused for other functions in future), and disadvantages (harder to implement, need to parse lambda expression during state merges, how to make 2 parameters optional?). Samples:
```sql
select groupArraySorted( timestamp ); -- unlimited
select groupArraySorted(x -> x, 1000)( timestamp ); -- collect by timestamp, sort by timestamp, first 1000 elements
select groupArraySorted(x -> x.1)( tuple( timestamp, page_type) ); -- collect tuples, sort by first element
```
3) special winodws-function like syntax like @amosbird propose
4) special syntax similar to MySQL: `GROUP_CONCAT(DISTINCT cate_id ORDER BY  cate_id)`
5) other options?
6) some combination of above?

**Comment by inv2004** [comment]
5.
To have special parameter for query which will call merge for aggregation in correct order of blocks if possible.

Something like:
```sql
SELECT groupArray(x) FROM T SORTED
```

it would help a lot to many window- and other order-related function.

**Comment by alexey-milovidov** [comment]
This is closely related to the task https://clickhouse.tech/docs/ru/whats-new/extended-roadmap/#modifikatory-distinct-order-by-dlia-agregatnykh-funktsii

**Comment by alexey-milovidov** [comment]
`agg(x, y ORDER BY a, b LIMIT 10)` will be nice to have.

**Comment by amosbird** [comment]
Is it covered by #34055 @filimonov ?

**Comment by filimonov** [comment]
The https://github.com/ClickHouse/ClickHouse/pull/34055 was reverted due to problems with implementation. The issue is vacant again.

**Comment by fm4v** [comment]
Function was added in 20c1f0c1
```
SELECT groupArraySorted(10)(number)
FROM numbers(100)

   ┌─groupArraySorted(10)(number)─┐
1. │ [0,1,2,3,4,5,6,7,8,9]        │
   └──────────────────────────────┘
```
