### ISSUE TITLE
How to populate data from existing table into materilized view table

### ISSUE THREAD

**Issue by dhruvanand96** [ClickHouse/ClickHouse#37091]
I am following this steps
-- in the shell 
-- mv /var/lib/clickhouse/shadow/1/data/default/source/* /var/lib/clickhouse/data/default/temp_snapshot/detached/
-- cd /var/lib/clickhouse/data/default/temp_snapshot/detached/
-- let i=1;for f in `ls -1` ; do echo $i $f;((i++)); echo "alter table temp_snapshot attach part '$f';"|clickhouse-client ; do

but /var/lib/clickhouse/shadow/ does not exist my clickhouse version is │ 22.3.2.1 and i am referring https://gist.github.com/den-crane/64c05be67ef8a926242011188ce96f44

**Comment by den-crane** [comment]
Check the last pages https://den-crane.github.io/Everything_you_should_know_about_materialized_views_commented.pdf for more ideas.

**Comment by dhruvanand96** [comment]
> `alter table source freeze;` creates shadow.
> 
> Also you can use `alter table source freeze with name 'source-2020-05-10'; `

now shadow directory got created but data directory did not got created


/var/lib/clickhouse/shadow/1# ls
store

**Comment by den-crane** [comment]
data directory inside store. 

It's a feature or Atomic database.

```
create database DA Engine=Atomic;
create database DO Engine=Ordinary;
create table DA.test(A Int64)Engine=MergeTree order by A as select number from numbers(100);
create table DO.test(A Int64)Engine=MergeTree order by A as select number from numbers(100);
alter table DA.test freeze with name 'test_atomic';
alter table DO.test freeze with name 'test_ordinary';

ls -l /var/lib/clickhouse/shadow/test_atomic/store/16e/16e36b05-d9e7-41ad-97ab-938c1b92aca0/
total 4
drwxr-x--- 2 clickhouse clickhouse 4096 May 11 22:03 all_1_1_0

ls -l /var/lib/clickhouse/shadow/test_ordinary/data/DO/test
total 4
drwxr-x--- 2 clickhouse clickhouse 4096 May 11 22:03 all_1_1_0
```

**Comment by dhruvanand96** [comment]
> data directory inside store.
> 
> It's a feature or Atomic database.
> 
> ```
> create database DA Engine=Atomic;
> create database DO Engine=Ordinary;
> create table DA.test(A Int64)Engine=MergeTree order by A as select number from numbers(100);
> create table DO.test(A Int64)Engine=MergeTree order by A as select number from numbers(100);
> 
> alter table DA.test freeze with name 'test_atomic';
> 
> alter table DO.test freeze with name 'test_ordinary';
> 
> ls -l /var/lib/clickhouse/shadow/test_atomic/store/16e/16e36b05-d9e7-41ad-97ab-938c1b92aca0/
> total 4
> drwxr-x--- 2 clickhouse clickhouse 4096 May 11 22:03 all_1_1_0
> 
> ls -l /var/lib/clickhouse/shadow/test_ordinary/data/DO/test
> total 4
> drwxr-x--- 2 clickhouse clickhouse 4096 May 11 22:03 all_1_1_0
> ```

 i am using atomic base
