### ISSUE TITLE
ClickHouse server fails to start after upgrading from `22.3.6.5-lts` to `22.4.5.9-stable`

### ISSUE THREAD

**Issue by svbrunov** [ClickHouse/ClickHouse#37099]
Dear ClickHouse maintainers,

Please, kindly find the reported issue below.

# Issue
The ClickHouse server fails to start after upgrading from the `22.3.6.5-lts` version to the `22.4.5.9-stable` version.

# Scenario
## Steps
1. Install the ClickHouse server `22.3.6.5-lts` by using the `*.deb` files (`dpkg -i *.deb`).
2. Create a database. Create a table within the created database. Insert a record into the created table.
3. Upgrade the ClickHouse server to the `22.4.5.9-stable` version by using the `*.deb` files (`dpkg -i *.deb`).
4. Restart the ClickHouse server (`service clickhouse-server restart`).

## Actual result
The ClickHouse server failed to restart:

```
# service clickhouse-server status
● clickhouse-server.service - ClickHouse Server (analytic DBMS for big data)
     Loaded: loaded (/etc/systemd/system/clickhouse-server.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Wed 2022-05-11 06:31:21 MSK; 1s ago
    Process: 17550 ExecStart=/usr/bin/clickhouse-server --config=/etc/clickhouse-server/config.xml --pid-file=/run/clickhouse-server/clickhouse-server.pid (code=exited, status=203/EXEC)
   Main PID: 17550 (code=exited, status=203/EXEC)
        CPU: 10ms
```

## Expected result
The ClickHouse server restarted successfully.

### `dpkg -i` output (log)
[dpkg-i-22.4.5.9-stable-deb.log](https://github.com/ClickHouse/ClickHouse/files/8670143/dpkg-i-22.4.5.9-stable-deb.log).

### After upgrading: Log files: No output
When performing the restart (and start) attempts, new log records (lines) are not appended to (do not appear in) both log files:

* `/var/log/clickhouse-server/clickhouse-server.log`.
* `/var/log/clickhouse-server/clickhouse-server.err.log`.

### After upgrading: Diagnostics
```
# ls -la /usr/bin/clickhouse-server
lrwxrwxrwx 1 root root 19 May 11 16:01 /usr/bin/clickhouse-server -> /usr/bin/clickhouse

# ls -la /usr/bin/clickhouse
-r-xr-xr-x 1 root root 482748504 May  6 13:20 /usr/bin/clickhouse

# ls -la /etc/clickhouse-server
total 96
drwx------   4 clickhouse clickhouse  4096 May 11 16:01 .
drwxr-xr-x 150 root       root       12288 May 12 13:22 ..
dr-x------   2 clickhouse clickhouse  4096 Apr 23 14:48 config.d
-r--------   1 clickhouse clickhouse 61817 May  6 13:03 config.xml
dr-x------   2 clickhouse clickhouse  4096 Feb 20 06:27 users.d
-r--------   1 clickhouse clickhouse  6258 May  6 13:03 users.xml

# cat /lib/systemd/system/clickhouse-server.service | grep CapabilityBoundingSet
CapabilityBoundingSet=CAP_NET_ADMIN CAP_IPC_LOCK CAP_SYS_NICE CAP_NET_BIND_SERVICE

# cat /etc/systemd/system/clickhouse-server.service | grep CapabilityBoundingSet
CapabilityBoundingSet=CAP_NET_ADMIN CAP_IPC_LOCK CAP_SYS_NICE

# getcap /usr/bin/clickhouse
/usr/bin/clickhouse cap_net_bind_service,cap_net_admin,cap_ipc_lock,cap_sys_nice=ep
```

Best regards,
Sergey Vyacheslavovich Brunov.

**Comment by den-crane** [comment]
>Upgrade the ClickHouse server to the 22.4.5.9-stable version by using the *.deb files (dpkg -i *.deb)

Please provide an output of `dpkg -i` from step 3

**Comment by svbrunov** [comment]
Dear Denny Crane (@den-crane),

I have just attached the output (log) file.
Please, see the updated issue comment. 

Best regards,
Sergey Vyacheslavovich Brunov.

**Comment by den-crane** [comment]
Can you share 

```
ls -la /usr/bin/clickhouse-server

ls -la /etc/clickhouse-server

cat /lib/systemd/system/clickhouse-server.service |grep CapabilityBoundingSet
getcap /usr/bin/clickhouse

```

**Comment by svbrunov** [comment]
Dear Denny Crane (@den-crane),

Sure. I have just updated the issue comment.
Please, see the updated issue comment: the «After upgrading: Diagnostics» section.

Best regards,
Sergey Vyacheslavovich Brunov.

**Comment by den-crane** [comment]
@svbrunov you need to do 

```
rm /etc/systemd/system/clickhouse-server.service
systemctl daemon-reload
service clickhouse-server restart
```

**Comment by den-crane** [comment]
@Felixoid somehow `/etc/systemd/system/clickhouse-server.service` is not removed during 22.3 de-install.
may it needs to add `rm /etc/systemd/system/clickhouse-server.service` into install script.

**Comment by Felixoid** [comment]
It's users's files. I don't get, why we should touch it. We don't provide `/etc/systemd/system/clickhouse-server.service`, do we?

**Comment by Felixoid** [comment]
@svbrunov is the file created by some configuration management system? Is it copied somehow from the one we provide?

Usually, a file in `/etc/systemd/system` is used to overwrite a default one. I'd suggest, if needed, using `/etc/systemd/system/clickhouse-server.service.d/` to overwrite only necessary parameters.

**Comment by den-crane** [comment]
@Felixoid `/etc/systemd/system/clickhouse-server.service` is created by CH .deb <22.4
Installer of 22.3 creates this file and does not remove during deb deinstallation

**Comment by Felixoid** [comment]
You are right. But it's controversial, what we can do here..

The only thing I can see as a not_so_bad_solution is checking for a particular file.

```
> cat clickhouse-server_21.12.3.32/etc/systemd/system/clickhouse-server.service && echo && echo clickhouse-server.service: && sha256sum clickhouse-server_21.12.3.32/etc/systemd/system/clickhouse-server.service
[Unit]
Description=ClickHouse Server (analytic DBMS for big data)
Requires=network-online.target
# NOTE: that After/Wants=time-sync.target is not enough, you need to ensure
# that the time was adjusted already, if you use systemd-timesyncd you are
# safe, but if you use ntp or some other daemon, you should configure it
# additionaly.
After=time-sync.target network-online.target
Wants=time-sync.target

[Service]
Type=simple
User=clickhouse
Group=clickhouse
Restart=always
RestartSec=30
RuntimeDirectory=clickhouse-server
ExecStart=/usr/bin/clickhouse-server --config=/etc/clickhouse-server/config.xml --pid-file=/run/clickhouse-server/clickhouse-server.pid
LimitCORE=infinity
LimitNOFILE=500000
CapabilityBoundingSet=CAP_NET_ADMIN CAP_IPC_LOCK CAP_SYS_NICE

[Install]
# ClickHouse should not start from the rescue shell (rescue.target).
WantedBy=multi-user.target

clickhouse-server.service:
d1dcc1dbe92dab3ae17baa395f36abf1876b4513df272bf021484923e0111eef  clickhouse-server_21.12.3.32/etc/systemd/system/clickhouse-server.service
```

As I said, the file _can_ be a user modified, I struggle to touch it blindly.

It makes sense to check sha256 for the following versions:

```
> git log --oneline --since 2020-01-01 -- debian/clickhouse-server.service
b6a39e78d0 (clean-debian) Clean out old packaging
4debd3b609 fix service start with systemd
9f23caab0e Update clickhouse-server.service
8f00b59a71 make systemd to use EnvironmentFile
748d5a86d2 Add some comments for systemd service.
aa5f1d77fa Add After/Wants time-sync.target for the clickhouse-server.service
f56653f43e ensure network be up before staring clickhouse
```

**Comment by svbrunov** [comment]
Dear Denny Crane (@den-crane),

Thank you very much for your support!
I have just checked the [proposed solution](https://github.com/ClickHouse/ClickHouse/issues/37099#issuecomment-1125315887): it works.

1. The ClickHouse server has started.
2. The ClickHouse server seems to work fine: some smoke tests have been run successfully.

Best regards,
Sergey Vyacheslavovich Brunov.

**Comment by svbrunov** [comment]
Dear  Mikhail f. Shiryaev (@Felixoid),

> @svbrunov is the file created by some configuration management system? Is it copied somehow from the one we provide?

No, I have not created any systemd-related configuration files for the ClickHouse server.

I have been using the ClickHouse server for quite some now and, if it would be helpful to you, I may share the current upgrade path (a list of versions) later on.

Best regards,
Sergey Vyacheslavovich Brunov.

**Comment by larry-cdn77** [comment]
Same thing here following upgrade to v22.5.1.2079-stable. Delete service file and systemctl reload fixed it. Thanks.

**Comment by Felixoid** [comment]
I'll implement a self-cleaning postinst hook for our `/etc/systemd/system/clickhouse-server.service` files

**Comment by stouch** [comment]
I just did : 
```
sudo systemctl disable clickhouse-server
```

to disable the old clickhouse-server service.
