### ISSUE TITLE
Clickhouse MySql Interface raised unexpected error: Syntax error

### ISSUE THREAD

**Issue by vhp1360** [ClickHouse/ClickHouse#37107]
**Describe what's wrong**
I should use IBM Cognos as a report Studio. Unfortunately, Cognos does not support this magic Database.
so I tried to use _MySQL_ Interface to connect to ClickHouse from IBM Cognos.
I created a Test table with to field(P1 Int32, T1 String) and run the `select P1, P2 From Test` query.
I faced a strange error

>Data source adapter error: java.sql.SQLException: Code: 62. DB::Exception: Syntax error: failed at position 11 ('DEFAULT'): DEFAULT. Expected one of: TRUE, FALSE, literal, NULL, number, Bool, true, false, string literal. (SYNTAX_ERROR) (version 22.4.5.9 (official build))

this error occured while I could connect with other db-browser like DBeaver.
I'm not sure this a Clickhouse bug but the error came from clickhouse.

**Does it reproduce on a recent release?**
I face it on 22.2 and Upgraded to 22.4.5.9 the error is still here.

**Enable crash reporting**
it is impossible for us, because discounnected from Internet

**How to reproduce**
in IBM Cognos 11.7, create connection with MySQL type and use below
connection String: `jdbc:mysql://IP:9004/default?allowPublicKeyRetrieval=true`
Driver class Name: `com.mysql.cj.jdbc.Driver`

* Which ClickHouse server version to use
latest version
* Which interface to use, if matters
   - MySql 
* Non-default settings, if any
  * Nothing
* `CREATE TABLE` statements for all tables involved
 ```sql
 CREATE TABLE Test(
 P1 Int32 , 
 T1 String
 )
	ENGINE=MergeTree();
```

* Queries to run that lead to unexpected result
`Select P1,T1 From Test`

**Expected behavior**

> A clear and concise description of what you expected to happen.

**Error message and/or stacktrace**
> {mysql:246} <Error> executeQuery: Code: 62. DB::Exception: Syntax error: failed at position 11 ('DEFAULT'): DEFAULT. Expected one of: TRUE, FALSE, literal, NULL, number, Bool, true, false, string literal. (SYNTAX_ERROR) (version 22.2.2.1) (from 172.26.40.133:49325) (in query: SET limit=DEFAULT), Stack trace (when copying this message, always include the lines below):
> 
> 0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xaebed1a in /usr/bin/clickhouse
> 1. DB::parseQueryAndMovePosition(DB::IParser&, char const*&, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, unsigned long, unsigned long) @ 0x15f69c3f in /usr/bin/clickhouse
> 2. ? @ 0x14ee6990 in /usr/bin/clickhouse
> 3. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::__1::shared_ptr<DB::Context>, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >
const&)>, std::__1::optional<DB::FormatSettings> const&) @ 0x14eebe2a in /usr/bin/clickhouse
> 4. DB::MySQLHandler::comQuery(DB::ReadBuffer&) @ 0x157dfd02 in /usr/bin/clickhouse
> 5. DB::MySQLHandler::run() @ 0x157dc72f in /usr/bin/clickhouse
> 6. Poco::Net::TCPServerConnection::start() @ 0x18667a0f in /usr/bin/clickhouse
> 7. Poco::Net::TCPServerDispatcher::run() @ 0x18669e61 in /usr/bin/clickhouse
> 8. Poco::PooledThread::run() @ 0x1881a549 in /usr/bin/clickhouse
> 9. Poco::ThreadImpl::runnableEntry(void*) @ 0x18817c40 in /usr/bin/clickhouse
> 10. ? @ 0x7fe91eb64609 in ?
> 11. clone @ 0x7fe91ea8b103 in ?

> If applicable, add screenshots to help explain your problem.

**Additional context**

Cognos connected to ClickHouse through the MySQL Interface and deted tablename,field name and every things, but could not retrive data.

**Comment by vdimir** [comment]
@kssenii Does it look like some misconfiguration?

**Comment by alexey-milovidov** [comment]
A DEFAULT keyword for the SET query has been added.
