### ISSUE TITLE
Adding Checks on the column name to avoid: strerror: File name too long.

### ISSUE THREAD

**Issue by melvynator** [ClickHouse/ClickHouse#37119]
ClickHouse should have checks on the column name to avoid long column names that could lead to the following error:

> <Error> MergeFromLogEntryTask: virtual bool DB::ReplicatedMergeMutateTaskBase::executeStep(): Code: 76. DB::ErrnoException: Cannot open file /var/lib/clickhouse/data/yc%2Dosquery/shard_syslog_shell/tmp_merge_20220422_46793_50514_2474/sudo__command_continued__cr%2Ecorp_yc%2Dcr%2Dinternal_container%2Dregistry%2Dmigrator_cr%2D2022%2D04%2D21%2Dcloud%2D98762%2Dpeasa%2D25602%2D58a09ee3f3_java_%2Djar_maven_container%2Dregistry%2Dmigrator%2Dcr%2D2022%2D04%2D21%2Dcloud%2D98762%2Dpeasa%2D25602%2D58a09ee3f3%2Ejar__migration.bin, errno: 36, strerror: File name too long.

This kind of issue might happen if you have an automated process of creating tables and columns. It would be nice if there was a hard/soft limit implemented to make sure that column names do not exceed a specific threshold.

Or maybe we could find a different mechanism to create the name of the file.

**Comment by Alex-Cheng** [comment]
Is this feature completed now?

**Comment by alesapin** [comment]
I think we can introduce user-level settings like:
max_table_name_bytes_length
max_column_name_bytes_length
max_table_and_column_name_bytes_length.
