### ISSUE TITLE
Use tuple functions for arrays

### ISSUE THREAD

**Issue by eugeneradionov** [ClickHouse/ClickHouse#37111]
Is there any way to use tuple functions for arrays?
My use-case: I have an array with numbers in the DB table:

```
id | data
--------------
1  | [1,2,3]
2  | [4,5,6]
```

and I have an incoming array, e.g. [7,8,9]
and I need to calculate the L2 Distance and Cosine Distance between incoming array and arrays in my table.
Arrays have 512 elements each.
I saw the functions for this in docs, but they are accepting only tuples as parameters.

**Comment by vdimir** [comment]
Currently this functions supports only tuples. Implementation for array is in progress, https://github.com/ClickHouse/ClickHouse/pull/37033
