### ISSUE TITLE
clickhouse-keeper-converter fail to converte zookeeper data to clickhouse-keeper

### ISSUE THREAD

**Issue by 825644691** [ClickHouse/ClickHouse#37150]
**KeeperStateMachine: Failed to load from snapshot with index 30188828932, with error DB::Exception: Cannot read all data. Bytes read: 3. Bytes expected: 4., will remove it from disk**

how to solve this problems

my operations
https://clickhouse.com/docs/en/operations/clickhouse-keeper
1. stop zookeeper
2. restart zookeeper master
3. run the clickhouse-keeper-converter
4. scp to all the clickhouse-keeper snapshot dir
5. start the clickhouse-keeper

2022.05.12 19:14:21.427409 [ 13420 ] {} <Warning> Application: bool tryCreateDirectories(Poco::Logger *, const std::string &): when creating /opt/cores/, std::exception. Code: 1001, type: std::__1::__fs::filesystem::filesystem_error, e.what() = filesystem error: in create_directory: Permission denied [/opt/cores], Stack trace (when copying this message, always include the lines below):

0. std::runtime_error::runtime_error(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x1c49dbad in ?
1. std::__1::system_error::system_error(std::__1::error_code, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x1c4a7b57 in ?
6. ? @ 0x15340681 in /apps/svr/clickhouse223344/usr/bin/clickhouse
7. ? @ 0x1c44beb6 in /apps/svr/clickhouse223344/usr/bin/clickhouse
8. ? @ 0x1c450422 in /apps/svr/clickhouse223344/usr/bin/clickhouse
9. std::__1::__fs::filesystem::__create_directory(std::__1::__fs::filesystem::path const&, std::__1::error_code*) @ 0x1c450fd0 in /apps/svr/clickhouse223344/usr/bin/clickhouse
10. std::__1::__fs::filesystem::__create_directories(std::__1::__fs::filesystem::path const&, std::__1::error_code*) @ 0x1c450c5f in /apps/svr/clickhouse223344/usr/bin/clickhouse
11. std::__1::__fs::filesystem::__create_directories(std::__1::__fs::filesystem::path const&, std::__1::error_code*) @ 0x1c450cc2 in /apps/svr/clickhouse223344/usr/bin/clickhouse
12. ? @ 0x14c80aae in /apps/svr/clickhouse223344/usr/bin/clickhouse
13. BaseDaemon::initialize(Poco::Util::Application&) @ 0x14c7eb56 in /apps/svr/clickhouse223344/usr/bin/clickhouse
14. DB::Keeper::initialize(Poco::Util::Application&) @ 0xb54d5f9 in /apps/svr/clickhouse223344/usr/bin/clickhouse
15. Poco::Util::Application::run() @ 0x19b9693a in /apps/svr/clickhouse223344/usr/bin/clickhouse
16. DB::Keeper::run() @ 0xb54d3e6 in /apps/svr/clickhouse223344/usr/bin/clickhouse
17. mainEntryClickHouseKeeper(int, char**) @ 0xb54bcb3 in /apps/svr/clickhouse223344/usr/bin/clickhouse
18. main @ 0xb36b6ca in /apps/svr/clickhouse223344/usr/bin/clickhouse
19. __libc_start_main @ 0x21b35 in /usr/lib64/libc-2.17.so
20. _start @ 0xb15606e in /apps/svr/clickhouse223344/usr/bin/clickhouse

Cannot print extra info for Poco::Exception (version 22.3.3.44 (official build))
2022.05.12 19:14:21.469060 [ 13420 ] {} <Warning> KeeperLogStore: No logs exists in /apps/dbdat/clickhouse/coordination/log. It's Ok if it's the first run of clickhouse-keeper.
2022.05.12 19:14:21.624040 [ 13420 ] {} <Warning> KeeperStateMachine: Failed to load from snapshot with index 30188828932, with error DB::Exception: Cannot read all data. Bytes read: 3. Bytes expected: 4., will remove it from disk
2022.05.12 19:14:21.625579 [ 13420 ] {} <Warning> KeeperStateMachine: All snapshots broken, last committed log index 0
2022.05.12 19:14:21.625612 [ 13420 ] {} <Warning> KeeperLogStore: Removing all changelogs
2022.05.12 19:14:23.487533 [ 13429 ] {} <Warning> RaftInstance: Election timeout, initiate leader election
2022.05.12 19:14:23.488849 [ 13438 ] {} <Warning> RaftInstance: peer (1) response error: failed to connect to peer 1, 10.235.95.23:9444, error 111
2022.05.12 19:14:23.499833 [ 13444 ] {} <Warning> RaftInstance: peer (1) response error: failed to connect to peer 1, 10.235.95.23:9444, error 111
2022.05.12 19:14:23.509846 [ 13454 ] {} <Warning> RaftInstance: peer (1) response error: failed to connect to peer 1, 10.235.95.23:9444, error 111
2022.05.12 19:14:23.990464 [ 13459 ] {} <Warning> RaftInstance: peer (1) response error: failed to connect to peer 1, 10.235.95.23:9444, error 111
2022.05.12 19:14:24.590719 [ 13466 ] {} <Warning> RaftInstance: peer (1) response error: failed to connect to peer 1, 10.235.95.23:9444, error 111
2022.05.12 19:14:25.241519 [ 13435 ] {} <Warning> RaftInstance: declined append: peer 1, prev next log idx 2, resp next 1, new next log idx 1

**Comment by 825644691** [comment]
/apps/svr/clickhouse223344/usr/bin/clickhouse keeper-converter --zookeeper-logs-dir /apps/dat/zookeeper/version-2 --zookeeper-snapshots-dir /apps/dat/zookeeper/version-2 --output-dir /home/apps/lxl/
Totally have 10 snapshots, will use latest
Deserializing storage snapshot /apps/dat/zookeeper/version-2/snapshot.8001c7876
Magic deserialized, looks OK
Sessions and timeouts deserialized
ACLs deserialized
Deserializing data from snapshot
Deserialized nodes from snapshot: 1000
Deserialized nodes from snapshot: 2000
Deserialized nodes from snapshot: 3000
Deserialized nodes from snapshot: 4000
Deserialized nodes from snapshot: 5000
Deserialized nodes from snapshot: 6000
Deserialized nodes from snapshot: 7000
Deserialized nodes from snapshot: 8000
Deserialized nodes from snapshot: 9000
Deserialized nodes from snapshot: 10000
Deserialized nodes from snapshot: 11000
Deserialized nodes from snapshot: 12000
Deserialized nodes from snapshot: 13000
Deserialized nodes from snapshot: 14000
Deserialized nodes from snapshot: 15000
Deserialized nodes from snapshot: 16000
Deserialized nodes from snapshot: 17000
Deserialized nodes from snapshot: 18000
Deserialized nodes from snapshot: 19000
Deserialized nodes from snapshot: 20000
Deserialized nodes from snapshot: 21000
Deserialized nodes from snapshot: 22000
Deserialized nodes from snapshot: 23000
Deserialized nodes from snapshot: 24000
Deserialized nodes from snapshot: 25000
Deserialized nodes from snapshot: 26000
Deserialized nodes from snapshot: 27000
Deserialized nodes from snapshot: 28000
Deserialized nodes from snapshot: 29000
Deserialized nodes from snapshot: 30000
Deserialized nodes from snapshot: 31000
Deserialized nodes from snapshot: 32000
Deserialized nodes from snapshot: 33000
Deserialized nodes from snapshot: 34000
Deserialized nodes from snapshot: 35000
Deserialized nodes from snapshot: 36000
Deserialized nodes from snapshot: 37000
Deserialized nodes from snapshot: 38000
Deserialized nodes from snapshot: 39000
Deserialized nodes from snapshot: 40000
Deserialized nodes from snapshot: 41000
Deserialized nodes from snapshot: 42000
Deserialized nodes from snapshot: 43000
Deserialized nodes from snapshot: 44000
Deserialized nodes from snapshot: 45000
Deserialized nodes from snapshot: 46000
Deserialized nodes from snapshot: 47000
Deserialized nodes from snapshot: 48000
Deserialized nodes from snapshot: 49000
Deserialized nodes from snapshot: 50000
Deserialized nodes from snapshot: 51000
Deserialized nodes from snapshot: 52000
Deserialized nodes from snapshot: 53000
Deserialized nodes from snapshot: 54000
Deserialized nodes from snapshot: 55000
Deserialized nodes from snapshot: 56000
Deserialized nodes from snapshot: 57000
Deserialized nodes from snapshot: 58000
Deserialized nodes from snapshot: 59000
Deserialized nodes from snapshot: 60000
Deserialized nodes from snapshot: 61000
Deserialized nodes from snapshot: 62000
Deserialized nodes from snapshot: 63000
Deserialized nodes from snapshot: 64000
Deserialized nodes from snapshot: 65000
Deserialized nodes from snapshot: 66000
Deserialized nodes from snapshot: 67000
Deserialized nodes from snapshot: 68000
Deserialized nodes from snapshot: 69000
Deserialized nodes from snapshot: 70000
Deserialized nodes from snapshot: 71000
Deserialized nodes from snapshot: 72000
Deserialized nodes from snapshot: 73000
Deserialized nodes from snapshot: 74000
Deserialized nodes from snapshot: 75000
Deserialized nodes from snapshot: 76000
Deserialized nodes from snapshot: 77000
Deserialized nodes from snapshot: 78000
Deserialized nodes from snapshot: 79000
Deserialized nodes from snapshot: 80000
Deserialized nodes from snapshot: 81000
Deserialized nodes from snapshot: 82000
Deserialized nodes from snapshot: 83000
Deserialized nodes from snapshot: 84000
Deserialized nodes from snapshot: 85000
Deserialized nodes from snapshot: 86000
Deserialized nodes from snapshot: 87000
Deserialized nodes from snapshot: 88000
Deserialized nodes from snapshot: 89000
Deserialized nodes from snapshot: 90000
Deserialized nodes from snapshot: 91000
Deserialized nodes from snapshot: 92000
Deserialized nodes from snapshot: 93000
Deserialized nodes from snapshot: 94000
Deserialized nodes from snapshot: 95000
Deserialized nodes from snapshot: 96000
Deserialized nodes from snapshot: 97000
Deserialized nodes from snapshot: 98000
Deserialized nodes from snapshot: 99000
Deserialized nodes from snapshot: 100000
Deserialized nodes from snapshot: 101000
Deserialized nodes from snapshot: 102000
Deserialized nodes from snapshot: 103000
Deserialized nodes from snapshot: 104000
Deserialized nodes from snapshot: 105000
Deserialized nodes from snapshot: 106000
Deserialized nodes from snapshot: 107000
Deserialized nodes from snapshot: 108000
Deserialized nodes from snapshot: 109000
Deserialized nodes from snapshot: 110000
Deserialized nodes from snapshot: 111000
Deserialized nodes from snapshot: 112000
Deserialized nodes from snapshot: 113000
Deserialized nodes from snapshot: 114000
Deserialized nodes from snapshot: 115000
Deserialized nodes from snapshot: 116000
Deserialized nodes from snapshot: 117000
Deserialized nodes from snapshot: 118000
Deserialized nodes from snapshot: 119000
Deserialized nodes from snapshot: 120000
Deserialized nodes from snapshot: 121000
Deserialized nodes from snapshot: 122000
Deserialized nodes from snapshot: 123000
Deserialized nodes from snapshot: 124000
Deserialized nodes from snapshot: 125000
Deserialized nodes from snapshot: 126000
Deserialized nodes from snapshot: 127000
Deserialized nodes from snapshot: 128000
Deserialized nodes from snapshot: 129000
Deserialized nodes from snapshot: 130000
Deserialized nodes from snapshot: 131000
Deserialized nodes from snapshot: 132000
Deserialized nodes from snapshot: 133000
Deserialized nodes from snapshot: 134000
Deserialized nodes from snapshot: 135000
Deserialized nodes from snapshot: 136000
Deserialized nodes from snapshot: 137000
Deserialized nodes from snapshot: 138000
Deserialized nodes from snapshot: 139000
Deserialized nodes from snapshot: 140000
Deserialized nodes from snapshot: 141000
Deserialized nodes from snapshot: 142000
Deserialized nodes from snapshot: 143000
Deserialized nodes from snapshot: 144000
Deserialized nodes from snapshot: 145000
Deserialized nodes from snapshot: 146000
Deserialized nodes from snapshot: 147000
Deserialized nodes from snapshot: 148000
Deserialized nodes from snapshot: 149000
Deserialized nodes from snapshot: 150000
Deserialized nodes from snapshot: 151000
Deserialized nodes from snapshot: 152000
Deserialized nodes from snapshot: 153000
Deserialized nodes from snapshot: 154000
Deserialized nodes from snapshot: 155000
Deserialized nodes from snapshot: 156000
Deserialized nodes from snapshot: 157000
Deserialized nodes from snapshot: 158000
Deserialized nodes from snapshot: 159000
Deserialized nodes from snapshot: 160000
Deserialized nodes from snapshot: 161000
Deserialized nodes from snapshot: 162000
Deserialized nodes from snapshot: 163000
Deserialized nodes from snapshot: 164000
Deserialized nodes from snapshot: 165000
Deserialized nodes from snapshot: 166000
Deserialized nodes from snapshot: 167000
Deserialized nodes from snapshot: 168000
Deserialized nodes from snapshot: 169000
Deserialized nodes from snapshot: 170000
Deserialized nodes from snapshot: 171000
Deserialized nodes from snapshot: 172000
Deserialized nodes from snapshot: 173000
Deserialized nodes from snapshot: 174000
Deserialized nodes from snapshot: 175000
Deserialized nodes from snapshot: 176000
Deserialized nodes from snapshot: 177000
Deserialized nodes from snapshot: 178000
Deserialized nodes from snapshot: 179000
Deserialized nodes from snapshot: 180000
Deserialized nodes from snapshot: 181000
Deserialized nodes from snapshot: 182000
Deserialized nodes from snapshot: 183000
Deserialized nodes from snapshot: 184000
Deserialized nodes from snapshot: 185000
Deserialized nodes from snapshot: 186000
Deserialized nodes from snapshot: 187000
Deserialized nodes from snapshot: 188000
Deserialized nodes from snapshot: 189000
Deserialized nodes from snapshot: 190000
Deserialized nodes from snapshot: 191000
Deserialized nodes from snapshot: 192000
Deserialized nodes from snapshot: 193000
Deserialized nodes from snapshot: 194000
Deserialized nodes from snapshot: 195000
Deserialized nodes from snapshot: 196000
Deserialized nodes from snapshot: 197000
Deserialized nodes from snapshot: 198000
Deserialized nodes from snapshot: 199000
Deserialized nodes from snapshot: 200000
Deserialized nodes from snapshot: 201000
Deserialized nodes from snapshot: 202000
Deserialized nodes from snapshot: 203000
Deserialized nodes from snapshot: 204000
Deserialized nodes from snapshot: 205000
Deserialized nodes from snapshot: 206000
Deserialized nodes from snapshot: 207000
Deserialized nodes from snapshot: 208000
Deserialized nodes from snapshot: 209000
Deserialized nodes from snapshot: 210000
Deserialized nodes from snapshot: 211000
Deserialized nodes from snapshot: 212000
Deserialized nodes from snapshot: 213000
Deserialized nodes from snapshot: 214000
Deserialized nodes from snapshot: 215000
Deserialized nodes from snapshot: 216000
Deserialized nodes from snapshot: 217000
Deserialized nodes from snapshot: 218000
Deserialized nodes from snapshot: 219000
Deserialized nodes from snapshot: 220000
Deserialized nodes from snapshot: 221000
Deserialized nodes from snapshot: 222000
Deserialized nodes from snapshot: 223000
Deserialized nodes from snapshot: 224000
Deserialized nodes from snapshot: 225000
Deserialized nodes from snapshot: 226000
Deserialized nodes from snapshot: 227000
Deserialized nodes from snapshot: 228000
Deserialized nodes from snapshot: 229000
Deserialized nodes from snapshot: 230000
Deserialized nodes from snapshot: 231000
Deserialized nodes from snapshot: 232000
Deserialized nodes from snapshot: 233000
Deserialized nodes from snapshot: 234000
Deserialized nodes from snapshot: 235000
Deserialized nodes from snapshot: 236000
Deserialized nodes from snapshot: 237000
Deserialized nodes from snapshot: 238000
Deserialized nodes from snapshot: 239000
Deserialized nodes from snapshot: 240000
Deserialized nodes from snapshot: 241000
Deserialized nodes from snapshot: 242000
Deserialized nodes from snapshot: 243000
Deserialized nodes from snapshot: 244000
Deserialized nodes from snapshot: 245000
Deserialized nodes from snapshot: 246000
Deserialized nodes from snapshot: 247000
Deserialized nodes from snapshot: 248000
Deserialized nodes from snapshot: 249000
Deserialized nodes from snapshot: 250000
Deserialized nodes from snapshot: 251000
Deserialized nodes from snapshot: 252000
Deserialized nodes from snapshot: 253000
Deserialized nodes from snapshot: 254000
Deserialized nodes from snapshot: 255000
Deserialized nodes from snapshot: 256000
Deserialized nodes from snapshot: 257000
Deserialized nodes from snapshot: 258000
Deserialized nodes from snapshot: 259000
Deserialized nodes from snapshot: 260000
Deserialized nodes from snapshot: 261000
Deserialized nodes from snapshot: 262000
Deserialized nodes from snapshot: 263000
Deserialized nodes from snapshot: 264000
ZooKeeper snapshot was in inconsistent (fuzzy) state. Will try to apply log. ZooKeeper create non fuzzy snapshot with restart. You can just restart ZooKeeper server and get consistent version.
Finished, snapshot ZXID 34361604214
Totally have 0 logs
Snapshot serialized to path:/home/apps/lxl/snapshot_34361604214.bin.zstd


**here is the result of the clickhouse-keeper-converter**

**Comment by 825644691** [comment]
version 22.3.3.4

**Comment by alexey-milovidov** [comment]
Please share the snapshot from ZooKeeper as well as the resulting snapshot from Keeper.

**Comment by alexey-milovidov** [comment]
I see it tells what to do.

> ZooKeeper snapshot was in inconsistent (fuzzy) state. Will try to apply log. ZooKeeper create non fuzzy snapshot with restart. You can just restart ZooKeeper server and get consistent version.
