### ISSUE TITLE
Pruning of partitions by _path when using S3 table engine

### ISSUE THREAD

**Issue by tbragin** [ClickHouse/ClickHouse#37174]
(raising on behalf of a user)

**Use case**

Trying to use ClickHouse on top of data in S3 bucket. 

**Describe the solution you'd like**

Pruning of partitions doesn’t work even when using a condition on _path in the where clause. The query

```
select count()
from table_name
```

takes roughly the same time as 

```
select count()
from table_name
where splitByChar('/',_path)[3] = 'foo=azc'
```

with the table definition
```
CREATE TABLE default.table_name
(
    …
)
ENGINE = S3('https://....s3.eu-west-1.amazonaws.com/Messages/foo=*/bar=*/*.parquet', 
'xxx', 'yyy, 'Parquet')
```

**Comment by UnamedRus** [comment]
related https://github.com/ClickHouse/ClickHouse/issues/23494

**Comment by amosbird** [comment]
It's doable with our PartitionPruner.
