### ISSUE TITLE
how to run clickhouse in termux

### ISSUE THREAD

**Issue by l1t1** [ClickHouse/ClickHouse#37175]
I use https://builds.clickhouse.com/master/aarch64/clickhouse
and strip it.
it reports `No such file or directory`
```
~/ch $ chmod +x clickhouse
~/ch $ ./clickhouse
bash: ./clickhouse: No such file or directory
~/ch $ ls -la
total 314307
drwx------ 2 u0_a200 u0_a200      3488 May 12 10:07 .
drwx------ 8 u0_a200 u0_a200      3488 May 12 10:02 ..
-rwxrw---- 1 u0_a200 u0_a200 321522936 May 12 09:07 clickhouse
-rw------- 1 u0_a200 u0_a200         0 May 12 10:07 nohup.out

~/ch $ file clickhouse
clickhouse: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[xxHash]=5ce89edc577d9bf0, stripped
~/ch $ file `which file`
/data/data/com.termux/files/usr/bin/file: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /system/bin/linker64, stripped
```

**Comment by l1t1** [comment]
and I can run following databend-meta in termux which is included in databend-v0.7.41-nightly-aarch64-unknown-linux-musl.tar.gz

~/databend $ file databend-meta
databend-meta: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, with debug_info, not stripped

**Comment by rschu1ze** [comment]
Termux mean you tried on Android, i.e. on arm64 using a somewhat crippled / locked-down Linux underneath, right?

`OS_ANDROID` is marked as experimental and without CI builds in cmake/target.cmake. Actually, the code was added in the context of the blog post by Alexander Kuzmenkov with (*) and perhaps this commit can be a starting point if @l1t1 like to work on this. But I think making Android a fully supported platform will be a lot of effort.

(*) https://github.com/ClickHouse/ClickHouse/commit/3e6b9f297fed35185e4fa98eae7bbe05502693ad

**Comment by melvynator** [comment]
Closing as multiple answer has been provided.
