### ISSUE TITLE
how often does clickhouse do sum in summingmergetree?

### ISSUE THREAD

**Issue by seaner90** [ClickHouse/ClickHouse#37180]
From document

> ClickHouse merges the inserted parts of data periodically...

**My questions is how often do it merge? is therey any way to control it?**

I'm considering using summingmergetree for my analysis flow, about 10 million events a day, each event is ~1kb, summingmergetree seems a perfect solution for saving disk space and speed performance, the only concern is when data is not mergeed, I have do `optimize table`, which is costly, especially in large table.

**Comment by den-crane** [comment]
When it necessary. Sum is a byproduct of merges. Usually CH merges after 6 inserts. In average I see 22 parts in a partition.

Merges are eventual and may never happen. It depends on the number of inserts that happened after, the number of parts in the partition, size of parts. If the total size of input parts are greater than the maximum part size then they will never be merged.

You should not use `optimize table`. 
All queries to summingmergetree should finalize aggregation using `sum / groupby`

**Comment by seaner90** [comment]
@den-crane clear, informational answers!! thank you very much
