### ISSUE TITLE
What magic clickhouse does  by using new group by column key.

### ISSUE THREAD

**Issue by HeenaBansal2009** [ClickHouse/ClickHouse#37201]
I am dealing with one issue where my customer reported that ClickHouse sometimes will not fully merge result data for same GROUP BY key even if all cluster nodes are running on same X86 CPU arch and of same ClickHouse version.

However ,

1 .  Fine tune the group_by_two_level_threshold_bytes from 1MB to 1GB , works too.
2. Adding a new column key (which is also a search criteria)to the GROUP BY statement  somehow qualified for a full-merge.
I am wandering logically what magic did point1 and point2 does during distributed merging and which one is preferrable?

PS: I didn't find any information in clickhouse docs for setting `group_by_two_level_threshold_bytes `

**Comment by alexey-milovidov** [comment]
> not fully merge result data for same GROUP BY key

It should be a bug report. Do you use some unofficial build of ClickHouse?

**Comment by HeenaBansal2009** [comment]
No , We ate using official version and All nodes are running same version (21.3.8.1) of Clickhouse

**Comment by alexey-milovidov** [comment]
But version 21.3 is not supported anymore.
And you don't even use the latest bugfix release 21.3.20.
