### ISSUE TITLE
Unable to insert json data type when async_insert is enabled

### ISSUE THREAD

**Issue by maxpain** [ClickHouse/ClickHouse#37207]
Hello. I'm trying to insert a row with a field with the `JSON` data type. When `async_insert` is enabled, this field is empty, but if I disable `async_insert` then insert goes well.

**Comment by CurtizJ** [comment]
Please, can you share an example? I can't reproduce it.

**Comment by maxpain** [comment]
Sorry, I've updated to the latest version and now it's working.
