### ISSUE TITLE
ClickHouse server `22.4.5.9-stable`: Missing changelog?

### ISSUE THREAD

**Issue by svbrunov** [ClickHouse/ClickHouse#37202]
Dear ClickHouse maintainers,

Please, kindly find the reported issue below.

# Issue
I could not find the changelog for the `22.4.5.9-stable` version of the ClickHouse server.
Maybe, I have overlooked it.

Could you please provide the location of the changelog or, if the changelog does not exist, consider creating it?

Best regards,
Sergey Vyacheslavovich Brunov.

**Comment by alexey-milovidov** [comment]
https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelogs/v22.4.5.9-stable.md

**Comment by svbrunov** [comment]
Dear Alexey Milovidov (@alexey-milovidov),

Thank you very much for the prompt answer!
This is exactly what I needed.

Best regards,
Sergey Vyacheslavovich Brunov.
