### ISSUE TITLE
Inverted Indices (RFC)

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#37216]
We already have "data skipping" indices in ClickHouse.

Data skipping index is a data structure (aggregation, data sketch, etc) that is created for every data granule (or every n granules) and allows to quickly answer - if some condition can be possibly true or possibly false on this range of data. This way, we can scan through the granules and the corresponding index data and filter out the irrelevant granules by asking every granule of the data skipping index.

In comparison, the inverted index is a single data structure created for all the granules and contains a mapping: value -> list of granules (marks) where the value might be.

We can have an independent immutable inverted index in every data part (it is the most simple approach compatible with replication, transactions, and MVCC...).

Inverted indices can reuse and extend the interface of `IMergeTreeIndex`. We can imagine it as having only one "index granule" per data part.

Inverted indices can be quite heavy (in some cases heavier than the data itself) and work well only when presented in memory. Nevertheless, we can experiment with fully in-memory indices (HashMap + Arena), reusing SSDCache data structure and RocksDB.

The main application will be text search. But we still need inverted indices on exact values as a first step in approaching text search. Then we will use tokenization or ngrams, normalization, and ensure that the intersection of granule lists works alright - to implement text search.

**Comment by KochetovNicolai** [comment]
Note that inverse index more difficult to write (especially if we expect them not to fit in memory). It looks like we need a separate algorithm for it (like, merge two sorted indexes on disk and re-calculate indexes). Just `IMergeTreeIndex` may be not enough.

**Comment by den-crane** [comment]
May be for now it has sense to implement indexes using orderby projections?

Now you can create ORDERBY projection like `select all_pk_columns order by secondary_col` But such projection is excessive because it stores all_pk_columns instead of mark (primary index) indexes and it requires to make a subquery in SQL.

**Comment by alexey-milovidov** [comment]
> Note that inverse index more difficult to write (especially if we expect them not to fit in memory).

A minimal variant is to always keep it in memory but support lazy loading, limitations on its size, and fallback to unused index instead of OOM.

> like, merge two sorted indexes on disk and re-calculate indexes

The first implementation will forget about part's indices during merge and simply build a new index.
Keep in mind that data can change during merge, which means that merging indices in a smart way won't always work.

**Comment by alexey-milovidov** [comment]
@den-crane 

> Now you can create ORDERBY projection like select all_pk_columns order by secondary_col But such projection is excessive because it stores all_pk_columns instead of the mark (primary index) indexes and it requires to make a subquery in SQL.

It is not possible to have ORDER BY projection only with an index without the data (the values of ORDER BY key) because if we do, then merging of these projections is not possible.

**Comment by alexey-milovidov** [comment]
@larryluogit told me why it is reasonable to use row numbers instead of just granule numbers.
\- because it will make the intersection of posting lists more efficient, and we will filter more granules.

Imagine the search terms are "ClickHouse good" and the granule contains the following rows

```
Granule 0:
Row 0: "ClickHouse is awesome"
Row 1: "MongoDB is good"
```

Then if we have only granule numbers, the granule 0 will be scanned, because it contains both "ClickHouse" and "good".
But if we have row numbers, we will intersect two lists: "ClickHouse": 0 and "good": 1, and get empty intersection and successfully skip this granule.

**Comment by larryluogit** [comment]
@alexey-milovidov 
We implemented an inverted index in ClickHouse from scratch. A prototype solution has been built and will be submitted for review soon.

**Comment by kaynewu** [comment]
> @alexey-milovidov We implemented an inverted index in ClickHouse from scratch. A prototype solution has been built and will be submitted for review soon.

@larryluogit 
Is this solution has been submitted now ?

**Comment by kaynewu** [comment]
> @alexey-milovidov We implemented an inverted index in ClickHouse from scratch. A prototype solution has been built and will be submitted for review soon.

@larryluogit 
Is this solution has been submitted now ?

**Comment by qieqieplus** [comment]
Wow, large scale vector approximate search could be implemented based on such kind of index as well.
