### ISSUE TITLE
Start populating data in materialized view after 1 hour of it creation

### ISSUE THREAD

**Issue by dhruvanand96** [ClickHouse/ClickHouse#37247]
i am using this as a where clause but is not populating seems it always taking the current timestamp and adding to it
WHERE Timestamp > (now() + toIntervalHour(1))

**Comment by den-crane** [comment]
https://den-crane.github.io/Everything_you_should_know_about_materialized_views_commented.pdf

materialized view is an insert trigger. It never reads the real table

**Comment by dhruvanand96** [comment]
> https://den-crane.github.io/Everything_you_should_know_about_materialized_views_commented.pdf
> 
> materialized view is an insert trigger. **It never reads the real table**

that part i understood but i wanted to understand that is any way i can start populating the data after certain time  without hard coding the time in where
