### ISSUE TITLE
when i debug build clickhouse-server on clion ,but err

### ISSUE THREAD

**Issue by xiongcp** [ClickHouse/ClickHouse#37248]
> Make sure that `git diff` result is empty and you've just pulled fresh master. Try cleaning up cmake cache. Just in case, official build instructions are published here: https://clickhouse.com/docs/en/development/build/
ClickHouse 21.10.2.15 with revision 54455
**Operating system**
ubuntu 16
> OS kind or distribution, specific version/release, non-standard kernel if any. If you are trying to build inside virtual machine, please mention it too.

**Cmake version**
3.18.3
**Ninja version**
1.11
**Compiler name and version**
clang11
**Full cmake and/or ninja output**
debug build
/usr/bin/cmake --build /mnt/data/work/ClickHouse/cmake-build-debug-system --target clickhouse-server -- -j 10

error log
[ 69%] Building CXX object contrib/libhdfs3-cmake/CMakeFiles/hdfs3.dir/__/libhdfs3/src/common/Hash.cpp.o
[ 69%] Building CXX object contrib/libhdfs3-cmake/CMakeFiles/hdfs3.dir/__/libhdfs3/src/common/SWCrc32c.cpp.o
[ 69%] Building CXX object contrib/libhdfs3-cmake/CMakeFiles/hdfs3.dir/__/libhdfs3/src/common/Thread.cpp.o
[ 69%] Building CXX object contrib/libhdfs3-cmake/CMakeFiles/hdfs3.dir/ClientDatanodeProtocol.pb.cc.o
[ 69%] Building CXX object contrib/libhdfs3-cmake/CMakeFiles/hdfs3.dir/hdfs.pb.cc.o
[ 69%] Building CXX object contrib/libhdfs3-cmake/CMakeFiles/hdfs3.dir/Security.pb.cc.o
[ 69%] Building CXX object contrib/libhdfs3-cmake/CMakeFiles/hdfs3.dir/ProtobufRpcEngine.pb.cc.o
[ 69%] Building CXX object contrib/libhdfs3-cmake/CMakeFiles/hdfs3.dir/ClientNamenodeProtocol.pb.cc.o
[ 69%] Building CXX object contrib/libhdfs3-cmake/CMakeFiles/hdfs3.dir/IpcConnectionContext.pb.cc.o
[ 69%] Building CXX object contrib/libhdfs3-cmake/CMakeFiles/hdfs3.dir/RpcHeader.pb.cc.o
[ 69%] Building CXX object contrib/libhdfs3-cmake/CMakeFiles/hdfs3.dir/datatransfer.pb.cc.o
[ 69%] Linking CXX static library libhdfs3d.a
[ 69%] Built target hdfs3
CMakeFiles/Makefile2:24419: recipe for target 'programs/CMakeFiles/clickhouse-server.dir/rule' failed
make[1]: *** [programs/CMakeFiles/clickhouse-server.dir/rule] Error 2
Makefile:5482: recipe for target 'clickhouse-server' failed
make: *** [clickhouse-server] Error 2

**Comment by KochetovNicolai** [comment]
It's not clear to me from this log what's wrong.
Now we are using clang-13 in ci, maybe using it will help.
Ubuntu 16 is also pretty old (but I don't know if it matters).
