### ISSUE TITLE
Allow Configuring ClickHouse to Use Arrow String Type for String Columns

### ISSUE THREAD

**Issue by mhconradt** [ClickHouse/ClickHouse#37254]
I have several text columns in my datasets and would like them to use a string data type instead of binary when using either `ArrowStream` or `Arrow` output formats. Currently, I have to cast them to `string`, which somewhat defeats the purpose of using Arrow.

> A clear and concise description of what is the intended usage scenario is.

I propose adding a flag `output_format_arrow_string_as_string` similar to `output_format_arrow_low_cardinality_as_dictionary`.

> A clear and concise description of what you want to happen.

String columns in the result would use Arrow's `string` type if and only if `output_format_arrow_string_as_string=1`.

> A clear and concise description of any alternative solutions or features you've considered.

A setting that allows multiple output types: `output_format_arrow_string_type=large_string`, `output_format_arrow_string_type=string`, etc. It would default to `binary` for backwards compatibility.

**Comment by solipfuct** [comment]
It would be nice to add this behavior to Parquet as well. If possible.
https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#string-types

**Comment by mhconradt** [comment]
@Avogar what release should this be included in, 22.6?
