### ISSUE TITLE
Which ports need to enable for firewall for Clickhoue-Keeper?

### ISSUE THREAD

**Issue by taotaizhu-pw** [ClickHouse/ClickHouse#37260]
I installed two clickhouse nodes(docker version) in one server, everythis is fine.

Then, I installed two clickhosue servers in two physical server(also docker version). The log is fine, but when I execute "create DATABASE pwtest on cluster jxshares;", just pending to timeout, even no error in log file。 Is it needs to enable some special ports for firewall? I just enabled 8123, 9000, 9234, 9009, 9181

config.xml: 

<keeper_server>
        <tcp_port>9181</tcp_port>
        <server_id>1</server_id>
        <log_storage_path>/var/lib/clickhouse/coordination/log</log_storage_path>
        <snapshot_storage_path>/var/lib/clickhouse/coordination/snapshots</snapshot_storage_path>

        <coordination_settings>
            <operation_timeout_ms>5000</operation_timeout_ms>
            <session_timeout_ms>10000</session_timeout_ms>
            <snapshot_distance>75</snapshot_distance>
            <raft_logs_level>trace</raft_logs_level>
        </coordination_settings>

        <raft_configuration>
            <server>
                <id>1</id>
                <hostname>192.168.60.31</hostname>
                <port>9234</port>
                <can_become_leader>true</can_become_leader>
                <priority>1</priority>
            </server>
            <server>
                <id>2</id>
                <hostname>192.168.60.191</hostname>
                <port>9234</port>
                <can_become_leader>true</can_become_leader>
                <start_as_follower>true</start_as_follower>
                <priority>2</priority>
            </server>
        </raft_configuration>
    </keeper_server>

    <include_from>/etc/clickhouse-server/metrika.xml</include_from>
    <remote_servers incl="clickhouse_remote_servers" />
    <zookeeper incl="zookeeper-servers" optional="true" />
    <compression incl="clickhouse_compression" optional="true" />
    <interserver_http_host>192.168.60.31</interserver_http_host>
    <macros incl="macros" optional="true"/>

metrika.xml:

<?xml version="1.0"?>
<clickhouse>
    <clickhouse_remote_servers>
        <jxshares>
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                    <host>192.168.60.31</host>
                    <port>9200</port>
                    <user>cebrisk</user>
                    <password>cebrisk</password>
                </replica>
                <replica>
                    <host>192.168.60.191</host>
                    <port>9200</port>
                    <user>cebrisk</user>
                    <password>cebrisk</password>
                </replica>
            </shard>
        </jxshares>
    </clickhouse_remote_servers>

    <macros>
        <shard>node01</shard>
        <replica>192.168.60.31</replica>
    </macros>

   <zookeeper-servers>
        <node index="1">
            <host>192.168.60.31</host>
            <port>9181</port>
        </node>
        <node index="2">
            <host>192.168.60.191</host>
            <port>9181</port>
        </node>
    </zookeeper-servers>

    <clickhouse_compression>
        <case>
            <min_part_size>10000000000</min_part_size>
            <min_part_size_ratio>0.01</min_part_size_ratio>
            <method>lz4</method>
        </case>
    </clickhouse_compression>
</clickhouse>

**Comment by den-crane** [comment]
check this https://stackoverflow.com/questions/64947277/clickhouse-create-database-on-cluster-ends-with-timeout/64947962#64947962

**Comment by den-crane** [comment]
remote_servers ?
select * from system.clusters

**Comment by e-mars** [comment]
hi @taotaizhu-pw ,
non-ssl:
8123: http
9000: native tcp
9444: raft (appears you have updated to 9234
9181: keeper
9009: interserver http

getting started config: https://clickhouse.com/docs/en/guides/sre/clickhouse-keeper/

if using SSL: https://clickhouse.com/docs/en/guides/sre/configuring-ssl

thx.
