### ISSUE TITLE
What's the logic for optimize function on cluster? 

### ISSUE THREAD

**Issue by taotaizhu-pw** [ClickHouse/ClickHouse#37282]
The table is ReplicatedCollapsingMergeTree engin in cluster jxshares .  

Table "test_tb" exist on dbA and dbB.  After I executed "optimize table test_tb final" in dbA, is this command affect dbB.test_tb?

Must I execute "optimize table test_tb  on cluster jxshares final" ?  

Is there any system table store whehere the table is cluster table?

Thanks!

**Comment by den-crane** [comment]
What is dbA and dbB ? Two servers / two replicas? Or two databases?

**Comment by den-crane** [comment]
I don't really understand what is the point. If you have two different unrelated tables but with the same name, they still two different unrelated tables.
