### ISSUE TITLE
DB::Exception: Unknown setting ratio_for_sparse_serialization

### ISSUE THREAD

**Issue by srikanthccv** [ClickHouse/ClickHouse#37292]
Hello,

I was looking for the ways to work with sparse json column and found that this pr https://github.com/ClickHouse/ClickHouse/pull/22535 introduced a setting `ratio_for_sparse_serialization` to enable it but when I try to use the setting it throws an exception

```
Code: 115. DB::Exception: Received from localhost:9000. DB::Exception: Unknown setting ratio_for_sparse_serialization. (UNKNOWN_SETTING)
```

Is this setting removed in latest version or it never existed?

I am using server (version 22.5.1)

**Comment by CurtizJ** [comment]
There was a mistake in the description of PR. The right name of the setting is `ratio_of_defaults_for_sparse_serialization`.

**Comment by srikanthccv** [comment]
@CurtizJ It still throws an unknown setting exception for `ratio_of_defaults_for_sparse_serialization`. Is there something I am missing?

```
Received exception from server (version 22.5.1):
Code: 115. DB::Exception: Received from localhost:9000. DB::Exception: Unknown setting ratio_of_defaults_for_sparse_serialization. (UNKNOWN_SETTING)
```

**Comment by CurtizJ** [comment]
Looks like you are trying to set it as query setting, but it's a MergeTree setting and should be specified at table creation.

```sql
CREATE TABLE table (...) ENGINE = MergeTree ORDER BY ... SETTINGS ratio_of_defaults_for_sparse_serialization = 0.9
```

**Comment by srikanthccv** [comment]
It makes sense, thank you.
