### ISSUE TITLE
Exception Code: 1000. query_log file not found

### ISSUE THREAD

**Issue by guaiguaidashu** [ClickHouse/ClickHouse#37309]
> ClickHouse version 20.8.7
```mysql
select * from system.query_log limit 10
```

Code: 1000. DB::Exception: Received from 99.**.**.100:9000. DB::Exception: File not found: /data/store/clickhouse/store/02e/02edc3c1-9e50-49f6-8170-ec488bf41e63/202105_1_134351_2002/type.mrk2.

query_log and query_thread_log neither can be queried.

**Comment by genzgd** [comment]
Are there other errors in your clickhouse-server.err.log file?  Did you have hardware problems?  Have you recently updated ClickHouse?

At some point a data file was incorrectly deleted or not created.  If you don't need old data the simplest solution may be to just `DROP TABLE system.query_log`.

In any case you should definitely upgrade your ClickHouse version to something newer.

**Comment by den-crane** [comment]
20.8.7 is out support. Upgrade to 22.4.
