### ISSUE TITLE
how to get train data for Catboost Model

### ISSUE THREAD

**Issue by wangqinghuan** [ClickHouse/ClickHouse#37313]
I am trying [Applying a Catboost Model in ClickHouse](https://clickhouse.com/docs/en/guides/developer/apply-catboost-model#insert-data-to-table).
In the second step,
`$ clickhouse client --host 127.0.0.1 --query 'INSERT INTO amazon_train FORMAT CSVWithNames' < ~/amazon/train.csv
`
Where can i get this train.csv from?

**Comment by Wachynaky** [comment]
> I am trying [Applying a Catboost Model in ClickHouse](https://clickhouse.com/docs/en/guides/developer/apply-catboost-model#insert-data-to-table). In the second step, `$ clickhouse client --host 127.0.0.1 --query 'INSERT INTO amazon_train FORMAT CSVWithNames' < ~/amazon/train.csv ` Where can i get this train.csv from?

I acknowledge that I don't have a deep knowledge about Machine learning, but I think there are features and use cases for which I feel adding as many examples as possible would be useful. 

- Catboost 
- stochasticLogisticRegression
- stochasticLinearRegression
- etc

**Comment by DanRoscigno** [comment]
Hi @wangqinghuan and @Wachynaky 

The command `docker run -it -p 8888:8888 yandex/tutorial-catboost-clickhouse` up top in the prerequisites starts a Docker container that has ClickHouse installed and running and also includes the file `~/amazon/train.csv`

**Comment by DanRoscigno** [comment]
For Catboost info, have a look at https://catboost.ai/ , there is info there and a video to get you introduced.

**Comment by wangqinghuan** [comment]
> Hi @wangqinghuan and @Wachynaky
> 
> The command `docker run -it -p 8888:8888 yandex/tutorial-catboost-clickhouse` up top in the prerequisites starts a Docker container that has ClickHouse installed and running and also includes the file `~/amazon/train.csv`

Thank you. @DanRoscigno
