### ISSUE TITLE
The function `toTimeZone` does not throw an error if `timezone` is not constant.

### ISSUE THREAD

**Issue by DimasKovas** [ClickHouse/ClickHouse#37321]
**Describe the unexpected behaviour**

The function `toTimeZone` does not throw an error and returns unexpected results if `timezone` argument is not constant.

**How to reproduce**
* Queries to run that lead to unexpected result
```sql
SELECT toTimeZone(dt, tz) FROM (
SELECT toDateTime('2022-05-11 00:00:00') AS dt, arrayJoin(['Europe/Moscow', 'UTC']) AS tz
)
```

This example on [clickhouse playground](https://play.clickhouse.com/play?user=play#ClNFTEVDVCB0b1RpbWVab25lKGR0LCB0eikgRlJPTSAoClNFTEVDVCB0b0RhdGVUaW1lKCcyMDIyLTA1LTExIDAwOjAwOjAwJykgQVMgZHQsIGFycmF5Sm9pbihbJ0V1cm9wZS9Nb3Njb3cnLCAnVVRDJ10pIEFTIHR6CikK).

**Expected behavior**
The function `toTimeZone` should take a constant argument `timezone` (as described in [docs](https://clickhouse.com/docs/en/sql-reference/functions/date-time-functions#totimezone)) and throw an error, if the column isn't constant.

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/16414
