### ISSUE TITLE
CREATE USER fails with "ON CLUSTER" and "sha256_password"

### ISSUE THREAD

**Issue by a-dot** [ClickHouse/ClickHouse#37331]
I'm trying to create a new user on a clickhouse cluster with  3 shards using this command:
`CREATE USER IF NOT EXISTS user ON CLUSTER '{cluster}' IDENTIFIED WITH sha256_password BY 'password' DEFAULT ROLE NONE`

This command gets expanded to:

`CREATE USER IF NOT EXISTS user ON CLUSTER {cluster} IDENTIFIED WITH sha256_hash BY '<hash>' SALT '<salt>' DEFAULT ROLE NONE`

However, on each of the shard I get this error:

`Syntax error: failed at position 123 ('SALT'): SALT '<salt>' DEFAULT ROLE NONE. Expected one of: HOST, SETTINGS, DEFAULT ROLE, GRANTEES, DEFAULT DATABASE, end of query.`

However, if I switch to use `plaintext_password` instead, everything works fine. Looks like the expansion and the addition of the "SALT" was not expected when handling this command.

* Which ClickHouse server version to use: 22.4

**Expected behavior**
The user to be created with no errors.

Thanks!

**Comment by tavplubix** [comment]
Probably related to #36172
cc: @varadarajkumar, @yakov-olkhovskiy

**Comment by alexey-milovidov** [comment]
Do you use identical ClickHouse versions on the cluster?

**Comment by a-dot** [comment]
> Do you use identical ClickHouse versions on the cluster?

Yes. 22.4 on all three shards

**Comment by tavplubix** [comment]
> Do you use identical ClickHouse versions on the cluster?

I does not matter. Just try execute:
```
dell9510 :) CREATE USER IF NOT EXISTS user IDENTIFIED WITH sha256_password BY 'password' DEFAULT ROLE NONE
```
it will be formatted to
```
CREATE USER IF NOT EXISTS user IDENTIFIED WITH sha256_hash BY '187247EF0CEC311D19250A94C26E8817DA3090687592C67898552A6F2251D79C' SALT 'E742A265D18C33C53A1764F67ED81F568B12D88CF7B51A673C0D53C56009E615' DEFAULT ROLE NONE
```
then try execute formatted query - ClickHouse will fail to parse it:
```
dell9510 :) CREATE USER IF NOT EXISTS user IDENTIFIED WITH sha256_hash BY '187247EF0CEC311D19250A94C26E8817DA3090687592C67898552A6F2251D79C' SALT 'E742A265D18C33C53A1764F67ED81F568B12D88CF7B51A673C0D53C56009E615' DEFAULT ROLE NONE
            

Syntax error: failed at position 130 ('SALT'):

CREATE USER IF NOT EXISTS user IDENTIFIED WITH sha256_hash BY '187247EF0CEC311D19250A94C26E8817DA3090687592C67898552A6F2251D79C' SALT 'E742A265D18C33C53A1764F67ED81F568B12D88CF7B51A673C0D53C56009E615' DEFAULT ROLE NONE

Expected one of: HOST, SETTINGS, DEFAULT ROLE, ON, GRANTEES, DEFAULT DATABASE, end of query
```
It means that parser and formatter implementations are inconsistent. It's definitely a bug.

**Comment by varadarajkumar** [comment]
Hi,  The password salt hash feature is applicable only for sha256_password option, it will generate salt internally and adds to password before hashing it. internally saves as sha256_hash after hash generation done.  SALT key word is used to identify and retrieve correct salt information during server restart scenario. The user create command syntax is not changed and it wont understand SALT keyword if you mention during user creation command. 
for sha256_hash option, user has to provide the hash value of the password, So we cannt add salt to already generated hash. and this scenario is not applicable to verify this feature. Hope it clears the reason for the error.

**Comment by yakov-olkhovskiy** [comment]
I figured out the problem, working on it.

**Comment by yakov-olkhovskiy** [comment]
@varadarajkumar the problem is that this generated sha256_hash form is passed to servers in cluster and along loses attach mode flag during execution. My solution is to remove restriction of im_mode for processing SALT parameter - in this way it solves the problem and also provides additional capability to accept precalculated sha256_hash with salt. Stay tuned, I will provide solution tomorow.
