### ISSUE TITLE
<Error> executeQuery: Code: 33, e.displayText() = DB::Exception: Cannot read all data. Bytes read: XXX. Bytes expected: XXXX.

### ISSUE THREAD

**Issue by juyonychen** [ClickHouse/ClickHouse#37340]
Hi guys. The exception just exist when I insert into distrubuted table with megre+distributed table  mode。
**Describe the bug**
Clickhouse cluster metrika.xml such as :

![image](https://user-images.githubusercontent.com/29190877/169223864-ccbd4ef2-af4a-4c6a-ba5d-db77cc07949d.png)

I create a Distributed table table_all with node node161 and create a MergeTree tablexxx with all  nodes；
the create table_all sql such as :
CREATE TABLE table_all (`dqdm` Nullable(String) ... ... ... ) ENGINE = Distributed(cluster, visual_formal, table_xx, rand())

when I insert data into table_all with datax , i found node36 and node136 has any data. node node161 data is normal, but load speed is very very slow. node161 has not any error message , bug node136 has error message 。
the first kind error : Cannot read all data. Bytes read: 170586. Bytes expected: 233264
the second kind error : Timeout exceeded while reading from socket (138.20.69.161:42280) (version 19.9.2.4) (from 138.20.69.161:42280)

i am sure the network is connected。
**Clickhouse version**
I used 19.9

**Error message and/or stacktrace**

2022.05.19 10:45:15.135686 [ 100 ] {2f52b399-4950-42af-a1b4-d2117c709191} <Error> executeQuery: Code: 33, e.displayText() = DB::Exception: Cannot read all data. Bytes read: 170586. Bytes expected: 233264. (version 19.9.2.4) (from 138.20.69.161:42274) (in query: INSERT INTO visual_formal.tablexxx Stack trace:

0. clickhouse-server(StackTrace::StackTrace()+0x16) [0x641b266]
1. clickhouse-server(DB::Exception::Exception(std::string const&, int)+0x1f) [0x31decef]
2. clickhouse-server(DB::CompressedReadBufferBase::readCompressedData(unsigned long&, unsigned long&)+0x353) [0x6166503]
3. clickhouse-server(DB::CompressedReadBuffer::nextImpl()+0x28) [0x6162a28]
4. clickhouse-server(DB::NativeBlockInputStream::readImpl()+0x1cdd) [0x598b83d]
5. clickhouse-server(DB::IBlockInputStream::read()+0x145) [0x597dea5]
6. clickhouse-server(DB::TCPHandler::receiveData()+0x4f) [0x31e723f]
7. clickhouse-server(DB::TCPHandler::receivePacket()+0xf5) [0x31e8295]
8. clickhouse-server(DB::TCPHandler::readData(DB::Settings const&)+0x193) [0x31e8733]
9. clickhouse-server(DB::TCPHandler::processInsertQuery(DB::Settings const&)+0x223) [0x31e8bc3]
10. clickhouse-server(DB::TCPHandler::runImpl()+0x7d8) [0x31e9528]
11. clickhouse-server(DB::TCPHandler::run()+0x1c) [0x31e9b3c]
12. clickhouse-server(Poco::Net::TCPServerConnection::start()+0xf) [0x665e22f]
13. clickhouse-server(Poco::Net::TCPServerDispatcher::run()+0xe5) [0x665e915]
14. clickhouse-server(Poco::PooledThread::run()+0x81) [0x677fe71]
15. clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0x38) [0x677bc38]
16. clickhouse-server() [0x6fb07ef]
17. /lib64/libpthread.so.0(+0x7e25) [0x7f0d8757ae25]
18. /lib64/libc.so.6(clone+0x6d) [0x7f0d8688034d]

2022.05.19 10:45:15.135886 [ 100 ] {2f52b399-4950-42af-a1b4-d2117c709191} <Debug> MemoryTracker: Peak memory usage (for query): 1.26 MiB.
2022.05.19 10:45:15.137114 [ 100 ] {2f52b399-4950-42af-a1b4-d2117c709191} <Information> TCPHandler: Processed in 300.006 sec.

2022.05.19 10:45:41.809668 [ 99 ] {c02f4597-b1b4-4ff2-bd15-2e2cc777b2d2} <Error> executeQuery: Code: 209, e.displayText() = DB::NetException: Timeout exceeded while reading from socket (138.20.69.161:42280) (version 19.9.2.4) (from 138.20.69.161:42280) (in query: INSERT INTO  sxmx_tj (id, lbdm, lb, dq, fydm, fymc, yy, ajfl, cs, ah, rq, kssj, jssj, rqcz, c_date) VALUES), Stack trace:

0. clickhouse-server(StackTrace::StackTrace()+0x16) [0x641b266]
1. clickhouse-server(DB::Exception::Exception(std::string const&, int)+0x1f) [0x31decef]
2. clickhouse-server() [0x3145628]
3. clickhouse-server(DB::CompressedReadBufferBase::readCompressedData(unsigned long&, unsigned long&)+0xa94) [0x6166c44]
4. clickhouse-server(DB::CompressedReadBuffer::nextImpl()+0x28) [0x6162a28]
5. clickhouse-server(DB::NativeBlockInputStream::readImpl()+0x1cdd) [0x598b83d]
6. clickhouse-server(DB::IBlockInputStream::read()+0x145) [0x597dea5]
7. clickhouse-server(DB::TCPHandler::receiveData()+0x4f) [0x31e723f]
8. clickhouse-server(DB::TCPHandler::receivePacket()+0xf5) [0x31e8295]
9. clickhouse-server(DB::TCPHandler::readData(DB::Settings const&)+0x193) [0x31e8733]
10. clickhouse-server(DB::TCPHandler::processInsertQuery(DB::Settings const&)+0x223) [0x31e8bc3]
11. clickhouse-server(DB::TCPHandler::runImpl()+0x7d8) [0x31e9528]
12. clickhouse-server(DB::TCPHandler::run()+0x1c) [0x31e9b3c]
13. clickhouse-server(Poco::Net::TCPServerConnection::start()+0xf) [0x665e22f]
14. clickhouse-server(Poco::Net::TCPServerDispatcher::run()+0xe5) [0x665e915]
15. clickhouse-server(Poco::PooledThread::run()+0x81) [0x677fe71]
16. clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0x38) [0x677bc38]
17. clickhouse-server() [0x6fb07ef]
18. /lib64/libpthread.so.0(+0x7e25) [0x7f0d8757ae25]
19. /lib64/libc.so.6(clone+0x6d) [0x7f0d8688034d]

2022.05.19 10:45:41.809829 [ 99 ] {c02f4597-b1b4-4ff2-bd15-2e2cc777b2d2} <Debug> MemoryTracker: Peak memory usage (for query): 1.03 MiB.
2022.05.19 10:45:41.809981 [ 99 ] {c02f4597-b1b4-4ff2-bd15-2e2cc777b2d2} <Information> TCPHandler: Processed in 300.001 sec.

**Comment by tavplubix** [comment]
> (version 19.9.2.4) 

This is 3-years-old release, it's obsolete. Please upgrade to newer version. The list of supported versions is here:
https://github.com/ClickHouse/ClickHouse/pulls?q=is%3Aopen+is%3Apr+label%3Arelease

**Comment by juyonychen** [comment]
tks! so i have on choice but  upgrade the clickhouse version .

**Comment by juyonychen** [comment]
enn, when i drop the table and recreated, everything is all right.
perhaps, it's a solution about this problem.
