### ISSUE TITLE
more  then one HDFS( HA) ,how config the hdfs

### ISSUE THREAD

**Issue by july2018** [ClickHouse/ClickHouse#37350]
when I have only one hdfs,I can config as follow:

<hdfs> 
<libhdfs3_conf>/etc/clickhouse-server/hdfs-site.xml</libhdfs3_conf>
 </hdfs>

but ，now ,I have more then one HDFS cluster , and i want use them , how can I config

**Comment by lgbo-ustc** [comment]
You can configure multi clusters in the same hdfs-site.xml ?

**Comment by july2018** [comment]
> You can configure multi clusters in the same hdfs-site.xml ?

NO ,then hdfs HA name are different

**Comment by lgbo-ustc** [comment]
Do you make a configure like follwoing
```XML

<!-- hz-cluster1 is old one，try to add hz-cluster2 -->
<property>
    <name>dfs.nameservices</name>
    <value>hz-cluster1,hz-cluster2</value>
</property>
<!-- HA configuration for  hz-cluster2 -->
<property>
    <name>dfs.ha.namenodes.hz-cluster2</name>
    <value>nn1,nn2</value>
</property>
<property>
    <name>dfs.namenode.rpc-address.hz-cluster2.nn1</name>
    <value>hadoop40.photo.163.org:8020</value>
</property>
<property>
    <name>dfs.namenode.rpc-address.hz-cluster2.nn2</name>
    <value>hadoop41.photo.163.org:8020</value>
</property>
<property>
    <name>dfs.namenode.http-address.hz-cluster2.nn1</name>
    <value>hadoop40.photo.163.org:50070</value>
</property>
<property>
    <name>dfs.namenode.http-address.hz-cluster2.nn2</name>
    <value>hadoop41.photo.163.org:50070</value>
</property>
<property>
    <name>dfs.client.failover.proxy.provider.hz-cluster2</name>
    <value>org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider</value>
</property>
```

**Comment by july2018** [comment]
> Do you make a configure like follwoing ?
> 
> ```
> 
> <property>
>     <name>dfs.nameservices</name>
>     <value>hz-cluster1,hz-cluster2</value>
> </property>
> 
> <property>
>     <name>dfs.ha.namenodes.hz-cluster2</name>
>     <value>nn1,nn2</value>
> </property>
> <property>
>     <name>dfs.namenode.rpc-address.hz-cluster2.nn1</name>
>     <value>hadoop40.photo.163.org:8020</value>
> </property>
> <property>
>     <name>dfs.namenode.rpc-address.hz-cluster2.nn2</name>
>     <value>hadoop41.photo.163.org:8020</value>
> </property>
> <property>
>     <name>dfs.namenode.http-address.hz-cluster2.nn1</name>
>     <value>hadoop40.photo.163.org:50070</value>
> </property>
> <property>
>     <name>dfs.namenode.http-address.hz-cluster2.nn2</name>
>     <value>hadoop41.photo.163.org:50070</value>
> </property>
> <property>
>     <name>dfs.client.failover.proxy.provider.hz-cluster2</name>
>     <value>org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider</value>
> </property>
> ```
ditto

and  another ha cluseter property "dfs.internal.nameservices"  is "hz-cluster3"

**Comment by alexey-milovidov** [comment]
We don't support HDFS.
