### ISSUE TITLE
Unexpected behaviour of common subexpression elimination

### ISSUE THREAD

**Issue by ioan-badila** [ClickHouse/ClickHouse#37366]
**Describe the unexpected behaviour**
`generateUUIDv4()`  in an SELECT for more than once will returns the same UUID.

**How to reproduce**
* Queries to run that lead to unexpected result
```
ClickHouse client version 22.3.3.44 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 22.3.3 revision 54455.

4b1121e247c9 :) SELECT  generateUUIDv4() = generateUUIDv4();

SELECT generateUUIDv4() = generateUUIDv4()

Query id: a5c92b33-78ec-4d3d-9197-a6f7b8811c3b

┌─equals(generateUUIDv4(), generateUUIDv4())─┐
│                                          1 │
└────────────────────────────────────────────┘

1 rows in set. Elapsed: 0.008 sec. 
```

**Expected behavior**
generateUUIDv4() should generate a new UUID each time is used.

**Comment by alexey-milovidov** [comment]
Similar with MySQL: http://sqlfiddle.com/#!9/0a28f18/726

**Comment by den-crane** [comment]
BTW, there is kinda workaround for rand `select rand(1), rand(2);`
may be `generateUUIDv4` also can accept some 'fake' argument ?

**Comment by ioan-badila** [comment]
Thanks for quick answers. I was used with PostgreSQL `uuid_generate_v4()`  from `uuid-ossp` extension.
Maybe this can be added to the docs (I didn't find it).

If something like @den-crane can be added would be awesome.

For now we could use this (but somehow is weird):
```
 4b1121e247c9 :) SELECT (SELECT generateUUIDv4()) = generateUUIDv4();

SELECT (
        SELECT generateUUIDv4()
    ) = generateUUIDv4()

Query id: e3a78ecf-a56f-4cc3-89e8-e6d2d7e65669

┌─equals(_subquery3490, generateUUIDv4())─┐
│                                       0 │
└─────────────────────────────────────────┘
```

**Comment by den-crane** [comment]
implemented https://github.com/ClickHouse/ClickHouse/pull/37415

**Comment by ioan-badila** [comment]
Great! Thank you!
