### ISSUE TITLE
Possible memory leaks in system.certificates implementation

### ISSUE THREAD

**Issue by yakov-olkhovskiy** [ClickHouse/ClickHouse#37368]
Memory leaks in system.certificates implementation due to possible exception. Example:
https://github.com/ClickHouse/ClickHouse/pull/37142/files#diff-1e24e43bfc38cec9770c3cc831b14d045c8138a60d7b77de8d32d96f4a2387e7R110

ref #37142

**Comment by alexey-milovidov** [comment]
unique_ptr with custom deleter will suffice.

**Comment by alexey-milovidov** [comment]
SCOPE_EXIT as well.
