### ISSUE TITLE
generateUUIDv4(tag argument)

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#37395]
to make it possible to generate two columns with UUID.

```
select generateUUIDv4(1), generateUUIDv4(2);

┌─generateUUIDv4(1)────────────────────┬─generateUUIDv4(2)────────────────────┐
│ bc834744-236b-4860-a961-4f8aafcae2b5 │ 37e7908c-e1d4-491f-b34d-dee0de7794df │
└──────────────────────────────────────┴──────────────────────────────────────┘
```

the same as rand() https://clickhouse.com/docs/en/sql-reference/functions/random-functions#rand

_x — [Expression](https://clickhouse.com/docs/en/sql-reference/syntax#syntax-expressions) resulting in any of the [supported data types](https://clickhouse.com/docs/en/sql-reference/data-types/#data_types). The resulting value is discarded, but the expression itself if used for bypassing [common subexpression elimination](https://clickhouse.com/docs/en/sql-reference/functions/#common-subexpression-elimination) if the function is called multiple times in one query. Optional parameter._

https://github.com/ClickHouse/ClickHouse/issues/37366

**Comment by Joeywzr** [comment]
I'd like to do that.
