### ISSUE TITLE
How to compile ClickHouse using the library libstdc++?

### ISSUE THREAD

**Issue by infzo** [ClickHouse/ClickHouse#37409]
### Scenario

I want to integrate the C++ version of `cuDF` and `ClickHouse` to expand some functions. However, some problems occurred during the build compilation process.

### Question

ClickHouse uses `libcxx`, which is incompatible with `libstdc++` in cuDF. The conflict occurs because the namespace of `std::__1` is not recognized during compilation.

According to the source code in ClickHouse, the `USE_LIBCXX` parameter is found. However, after the parameter is modified to `OFF`, an error occurs in the build and compilation of the ClickHouse.

How to set parameters correctly to meet the requirement?

**Comment by alexey-milovidov** [comment]
It's not possible at all. Only `libc++` can be used as a C++ standard library implementation.

**Comment by alexey-milovidov** [comment]
It's better to try build cuDF with libc++.
