### ISSUE TITLE
Topk(enumColumn) returns int

### ISSUE THREAD

**Issue by orloffv** [ClickHouse/ClickHouse#3740]
Version: ClickHouse 18.12.17
<img width="961" alt="screen shot 2018-12-03 at 22 33 01" src="https://user-images.githubusercontent.com/504986/49399003-1c0fa880-f751-11e8-8a1d-160fc55f8368.png">

**Comment by orloffv** [comment]
@blinkov  @abyss7 а какое правильное поведение то?

**Comment by alexey-milovidov** [comment]
@orloffv Я не понял, почему коллеги забили на эту задачу. Исправление тривиально. Сделаю.
