### ISSUE TITLE
Fork and improve hashidsxx library

### ISSUE THREAD

**Issue by yakov-olkhovskiy** [ClickHouse/ClickHouse#37418]
**Use case**
Library, used for hashid function can be optimized.

**Describe the solution you'd like**
At least function encode can be overloaded with external buffer, so one copy can be eliminated.

**Describe alternatives you've considered**
Some other inefficiencies can be fixed.

**Additional context**
hashid function was implemented in #37013

**Comment by alexey-milovidov** [comment]
You didn't do it in a year - let's give up.
We should not have substandard code in the ClickHouse codebase.
