### ISSUE TITLE
Why docker image clickhouse-client does not updating?

### ISSUE THREAD

**Issue by was-av** [ClickHouse/ClickHouse#37410]
Last update: 4 month ago, but clickhouse-server has periodical updates. 

https://hub.docker.com/r/clickhouse/clickhouse-client/tags

**Comment by Felixoid** [comment]
it will be basically the same image without entrypoint. `clickhouse` is a monolithic binary. That's why it has a pretty low priority to bring it back.

**Comment by alexey-milovidov** [comment]
Plus you don't really need docker for clickhouse-client, you can install it as following:

```
curl https://clickhouse.com/ | sh
```

**Comment by alexey-milovidov** [comment]
Also you can run like this:

```
docker run -it --rm --network host clickhouse/clickhouse-server:22.5 clickhouse-client --host play.clickhouse.com --secure --user play
```

**Comment by was-av** [comment]
@alexey-milovidov, thank you for the answer

Also, I found a way for Docker

`COPY --from=clickhouse/clickhouse-server:22.5 /usr/bin/clickhouse /usr/bin/clickhouse-client /usr/bin/`

**Comment by genzgd** [comment]
This is still causing confusion and I think we should restore a specific clickhouse-client docker image.

**Comment by Felixoid** [comment]
We updated the description for https://hub.docker.com/r/clickhouse/clickhouse-client. As well, there aren't any mentioned `clickhouse/clickhouse-client` or `yandex/clickhouse-client` left in the documentation.

When clickhouse-client will become a lightweight stand-alone binary, the image will be ressurected
