### ISSUE TITLE
MaterializedMySQL query slowly  after  version 21.7

### ISSUE THREAD

**Issue by yusht000** [ClickHouse/ClickHouse#37411]
hi !
MaterializedMySQL produce a new problem that make our team troubled
as  follows:
old clickhouse version 21.7
the same sql execute in old clusters :
Elapsed : 0.122 sec .Proccessed 65.65 million rows, 328.69MB (537.22 million rows/s, 2.69GB/s)
but  replace  version 21.8 21.9 22.1 22.4 22.5
this Proccessed  become  very  very  very slow  ….. why ??????

**Comment by yusht000** [comment]
<img width="929" alt="image" src="https://user-images.githubusercontent.com/17878748/169636842-97ecd3d1-4810-4d24-9647-9552b2ffabe8.png">

**Comment by yusht000** [comment]
<img width="870" alt="image" src="https://user-images.githubusercontent.com/17878748/169636856-6d12b7e9-f877-4f72-a051-4bcc008e4794.png">

**Comment by alexey-milovidov** [comment]
`MaterializedMySQL` is an experimental feature, it has been implemented by external contributors, but most of them have vanished. Maybe we will not be able to answer this question.

**Comment by tavplubix** [comment]
Please provide `CREATE TABLE` statements (from `MySQL` side) of involved tables and `SELECT` queries that slowed down (as text, not as screenshots).

**Comment by yusht000** [comment]
our teams  every try to work  on  aws  by docker, it  is  not  reproduce the same quesition;   
we have use the version 21.7  in production on physical machine  instead of  version 22.4 ; 

I am sorry to provide the statements tables to you , because  online of tables  is  a secret；
