### ISSUE TITLE
clickhouse removing part from filesystem

### ISSUE THREAD

**Issue by salmanaalfariz01** [ClickHouse/ClickHouse#37412]
![image](https://user-images.githubusercontent.com/79123656/169643144-a8e0e6f0-c13c-4a47-b0a8-f66d15d6f4c5.png)

● clickhouse-server.service - LSB: Yandex clickhouse-server daemon
   Loaded: loaded (/etc/rc.d/init.d/clickhouse-server; bad; vendor preset: disabled)
   Active: active (exited) since Sat 2022-05-21 05:10:31 WIB; 10h ago
     Docs: man:systemd-sysv-generator(8)
  Process: 38012 ExecStop=/etc/rc.d/init.d/clickhouse-server stop (code=exited, status=0/SUCCESS)
  Process: 39988 ExecStart=/etc/rc.d/init.d/clickhouse-server start (code=exited, status=0/SUCCESS)

Clickhouse not connected after systemctl start clickhouse-server , port is lose
Clickhouse version 19.5

**Comment by den-crane** [comment]
Clickhouse version 19.5 is obsolete.

Upgrade CH.

Share the full log.
