### ISSUE TITLE
How to disable curl components at compile time,

### ISSUE THREAD

**Issue by wangdonsy** [ClickHouse/ClickHouse#37429]
For safety reasons，we have disable clickhouse http port access,  only use JDBC to access clickhouse database, and  can not use AWS S3 storage.
What parameters can be added during compilation to disable curl and aws,
we use the clickhouse 21.8.8.29 and 20.3.2.1 version

**Comment by alexey-milovidov** [comment]
The versions you are using are insecure.
For example, 21.8 has at least 6 patches after 21.8.8 and the latest patch is 21.8.14.

**Comment by alexey-milovidov** [comment]
Most likely it's possible to build ClickHouse without curl,
you need to disable the "Sentry" and "Azure" libraries.
