### ISSUE TITLE
Data race in `ColumnsDescription`/`FunctionNameNormalizer`

### ISSUE THREAD

**Issue by tavplubix** [ClickHouse/ClickHouse#37452]
https://s3.amazonaws.com/clickhouse-test-reports/37253/3bad21cea7b14273e5144302923e80d736146215/stateless_tests__thread__actions__[3/3].html

stderr: https://pastila.nl/?00bfc54a/ad680f480260559318cc65b2f0ca1253

Maybe related to #29266

**Comment by alexey-milovidov** [comment]
Obsolete.
