### ISSUE TITLE
Does distributed table support select with order?

### ISSUE THREAD

**Issue by zouyonghao** [ClickHouse/ClickHouse#37475]
I know that distributed table does support create with order by, but it seems select from a distrbuted with order by also does not work.

Does distributed table support select with order?

**Comment by zouyonghao** [comment]
Oops, I figure it out. It seems distributed table does not support order with position?

**Comment by den-crane** [comment]
Distributed table supports order with position.
What CH version do you use?

**Comment by zouyonghao** [comment]
Hi @den-crane, I'm using version `ClickHouse server version 22.4.5.9 (official build).`
I noticed that I don't set `enable_positional_arguments` to 1, but a query result from a local db is still orderd while result from distributed db is not.
If I set `enable_positional_arguments` to 1, all results from local/distributed are orderd.
