### ISSUE TITLE
Tiered Storage support

### ISSUE THREAD

**Issue by zhanglistar** [ClickHouse/ClickHouse#37473]
Now, data is stored on disk or remote disk, but it may be much slower than memory during query processing. The accelerating method are caching data or supporting tired storage. The first is that we can cache SQL result or middle result or hot blocks in memory, which is doing by some PRs.
The later is supporting memory fist and tiered storage, say we can storage recently data blocks in memory first, and then warm data on disk, and cold data in low cost storage say aws S3.
After doing this, it may be much more faster in many cases.

**Comment by alexey-milovidov** [comment]
We already have it with the feature "local cache from remote filesystem".
