### ISSUE TITLE
Why is JSONExtractString is much faster the JSON Object type?

### ISSUE THREAD

**Issue by srikanthccv** [ClickHouse/ClickHouse#37519]
Hi, 

I have a simple table where one column has semi structured data. I was trying to using the new Object('json') feature and see how it helps me improve the performance of my queries. Contrary to my assumption, the queries with new JSON type are much slower than the ones with `JSONExtractString`. This was a surprise for me. Are there any pre-requisites that should be kept in mind when working with JSON object type. What could be reason for performance degradation?

Here is sample result for a simple query

```sh
SELECT [columns] from [table] WHERE JSONExtractString(labels, '__name__') = 'node_memory_VmallocChunk_bytes' AND JSONExtractString(labels, 'host_number') = 'cfg_464' settings min_bytes_to_use_direct_io=1;
SELECT [columns] from [table_with_json_type] WHERE labels.__name__ = 'node_memory_VmallocChunk_bytes' AND labels.host_number = 'cfg_464' settings min_bytes_to_use_direct_io=1;

```

```sh
19 rows in set. Elapsed: 3.992 sec. Processed 28.79 million rows, 8.13 GB (7.21 million rows/s., 2.04 GB/s.)
19 rows in set. Elapsed: 8.297 sec. Processed 28.79 million rows, 17.92 GB (4.73 million rows/s., 3.38 GB/s.)
```

Clickhouse version: 22.4.5.9

Machine details if that matters:
```sh
BIOS Information
	Vendor: Xen
	Version: 4.2.amazon
	Release Date: 08/24/2006
	Address: 0xE8000
	Runtime Size: 96 kB
	ROM Size: 64 kB
	Characteristics:
		PCI is supported
		EDD is supported
		Targeted content distribution is supported
	BIOS Revision: 4.2

System Information
	Manufacturer: Xen
	Product Name: HVM domU
	Version: 4.2.amazon
	Serial Number: ec204910-760d-eb65-fb57-cfe76558ec63
	UUID: ec204910-760d-eb65-fb57-cfe76558ec63
	Wake-up Type: Power Switch
	SKU Number: Not Specified
	Family: Not Specified

Chassis Information
	Manufacturer: Xen
	Type: Other
	Lock: Not Present
	Version: Not Specified
	Serial Number: Not Specified
	Asset Tag: Not Specified
	Boot-up State: Safe
	Power Supply State: Safe
	Thermal State: Safe
	Security Status: Unknown

Processor Information
	Socket Designation: CPU 1
	Type: Central Processor
	Family: Other
	Manufacturer: Intel
	ID: F1 06 04 00 FF FB 89 17
	Version: Not Specified
	Voltage: Unknown
	External Clock: Unknown
	Max Speed: 2300 MHz
	Current Speed: 2300 MHz
	Status: Populated, Enabled
	Upgrade: Other

Processor Information
	Socket Designation: CPU 2
	Type: Central Processor
	Family: Other
	Manufacturer: Intel
	ID: F1 06 04 00 FF FB 89 17
	Version: Not Specified
	Voltage: Unknown
	External Clock: Unknown
	Max Speed: 2300 MHz
	Current Speed: 2300 MHz
	Status: Populated, Enabled
	Upgrade: Other

Processor Information
	Socket Designation: CPU 3
	Type: Central Processor
	Family: Other
	Manufacturer: Intel
	ID: F1 06 04 00 FF FB 89 17
	Version: Not Specified
	Voltage: Unknown
	External Clock: Unknown
	Max Speed: 2300 MHz
	Current Speed: 2300 MHz
	Status: Populated, Enabled
	Upgrade: Other

Processor Information
	Socket Designation: CPU 4
	Type: Central Processor
	Family: Other
	Manufacturer: Intel
	ID: F1 06 04 00 FF FB 89 17
	Version: Not Specified
	Voltage: Unknown
	External Clock: Unknown
	Max Speed: 2300 MHz
	Current Speed: 2300 MHz
	Status: Populated, Enabled
	Upgrade: Other

OEM Strings
	String 1: Xen

Physical Memory Array
	Location: Other
	Use: System Memory
	Error Correction Type: Multi-bit ECC
	Maximum Capacity: 16 GB
	Number Of Devices: 1

Memory Device
	Total Width: 64 bits
	Data Width: 64 bits
	Size: 16384 MB
	Form Factor: DIMM
	Set: None
	Locator: DIMM 0
	Bank Locator: Not Specified
	Type: RAM
	Type Detail: None
	Speed: Unknown
	Manufacturer: Not Specified
	Serial Number: Not Specified
	Asset Tag: Not Specified
	Part Number: Not Specified
	Rank: Unknown
	Configured Memory Speed: Unknown

Memory Array Mapped Address
	Starting Address: 0x00000000000
	Ending Address: 0x003FFFFFFFF
	Range Size: 16 GB
	Partition Width: 1

Memory Device Mapped Address
	Starting Address: 0x00000000000
	Ending Address: 0x003FFFFFFFF
	Range Size: 16 GB
	Partition Row Position: 1

System Boot Information
	Status: No errors detected
```

**Comment by tom-clickhouse** [comment]
Your query
```
SELECT [columns] from [table_with_json_type] 
WHERE 
  labels.__name__ = 'node_memory_VmallocChunk_bytes' AND 
  labels.host_number = 'cfg_464' 
  settings min_bytes_to_use_direct_io=1;
```
is not using the [index features](https://clickhouse.com/docs/en/guides/improving-query-performance/sparse-primary-indexes) in ClickHouse. 

We have a [guide](https://clickhouse.com/docs/en/guides/developer/working-with-json/json-semi-structured#adding-primary-keys) that shows how you can extract the values of `labels.__name__` and `labels.host_number` during data insert in order to add them to into dedicated table columns that you can then use in a compound primary key of your table and in your query.

That should significantly improve your query performance.

**Comment by alexey-milovidov** [comment]
@tom-clickhouse but the number of read rows is the same for both queries, so there is no difference due to index usage.

**Comment by alexey-milovidov** [comment]
Any chance that the original query used LowCardinality?
The JSON data type is using String instead of LowCardinality(String), so it can be slower.

**Comment by srikanthccv** [comment]
> the number of read rows is the same for both queries, so there is no difference due to index usage.

Yes, I was looking at this issue https://github.com/ClickHouse/ClickHouse/issues/35661 and realised at the time there is no way to specify data skipping index for JSON type.

> Any chance that the original query used LowCardinality?

@alexey-milovidov No, It's not a `LowCardinality `. Here is the table definition for both. 

table 1:
```sh
┌─statement──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ CREATE TABLE table1
(
    `date` Date CODEC(DoubleDelta, LZ4),
    `fingerprint` UInt64 CODEC(DoubleDelta, LZ4),
    `labels` String CODEC(ZSTD(5))
)
ENGINE = ReplacingMergeTree
PARTITION BY date
ORDER BY fingerprint
SETTINGS index_granularity = 8192 │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

table 2:
```sh
┌─statement──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ CREATE TABLE table2
(
    `date` Date CODEC(DoubleDelta, LZ4),
    `fingerprint` UInt64 CODEC(DoubleDelta, LZ4),
    `labels` Object('json')
)
ENGINE = ReplacingMergeTree
PARTITION BY date
ORDER BY fingerprint
SETTINGS index_granularity = 8192 │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

And also attaching the flame graph for queries in the order. It was easier to reason about what is dominating part in first query but I am not familiar with ClickHouse internals enough to reason why reader is taking up most time in second query. 

query 1 flame graph:
![9eb962bc-2631-4387-a2ea-908d509c3b6a Real](https://user-images.githubusercontent.com/22846633/170396960-6a012936-228a-49e9-85e2-f814c4b7fe6e.svg)

query 2 flame graph:

![6c713927-0ed1-41e8-b21c-723d32637a7e Real](https://user-images.githubusercontent.com/22846633/170397036-da2519a2-366a-4f7f-8a75-db1cd813acfd.svg)

**Comment by CurtizJ** [comment]
Is `labels` column is included in your query: `SELECT [columns] from [table_with_json_type] WHERE labels.__name__ = 'node_memory_VmallocChunk_bytes' AND labels.host_number = 'cfg_464' settings min_bytes_to_use_direct_io=1`?

**Comment by srikanthccv** [comment]
@CurtizJ Yes, sometimes.

**Comment by alexey-milovidov** [comment]
@CurtizJ answered:

If you include the `labels` column to the list (a whole object), it will require reading all the subcolumns, and it is less efficient than if they are located inside a single String column.

**Comment by srikanthccv** [comment]
@alexey-milovidov does it still load the whole object even when I am just accessing the sub column from the labels (such as `labels.host` or `labels.machine`)?

**Comment by alexey-milovidov** [comment]
No, if you query only subcolumns, only they will be read.
