### ISSUE TITLE
Cannot use user_files_absolute_path in function file

### ISSUE THREAD

**Issue by Vxider** [ClickHouse/ClickHouse#37521]
**Describe what's wrong**

Cannot use `user_files_absolute_path` when executing query `INSERT INTO xxx VALUES(file(path))`

**Does it reproduce on recent release?**

22.6.1.1 with revision 54463

**Enable crash reporting**

**How to reproduce**

1. set `user_files_absolute_path` in server config to `path_user`
2. copy file `test.jpg` to `path_user`
3. `SELECT file('test.jpg')` works fine;
4. `INSERT INTO test SELECT file('test.jpg')` works fine
5. But `INSERT INTO test VALUES (file('test.jpg'));` will using `build path` as `user_files_absolute_path` instead of `path_user`

```
CREATE TABLE test(src String) ENGINE=Log;

INSERT INTO test VALUES (file('test.jpg'));

Ok.
Error on processing query: Code: 107. DB::ErrnoException: Cannot open file /xxx/build/test.jpg, errno: 2, strerror: No such file or directory: while executing 'FUNCTION file(_dummy_0 : 0) -> file(_dummy_0) Nullable(String) : 3': While executing ValuesBlockInputFormat: data for INSERT was parsed from query. (FILE_DOESNT_EXIST) (version 22.6.1.1)

```

**Comment by amosbird** [comment]
`... VALUES (file('test.jpg'));` is evaluated at client side instead of server.
