### ISSUE TITLE
Remove `Block Streams` from architecture document in development section

### ISSUE THREAD

**Issue by devcrafter** [ClickHouse/ClickHouse#37529]
**Describe the issue**
The [architecture document](https://github.com/ClickHouse/ClickHouse/blob/master/docs/en/development/architecture.md) often refers to `block streams` (`IBlockInputStream/IBlockOutputStream` interfaces) which was replaced with `IProcessor & Co`. It'd be nice to update the document accordingly.
See, special section about `block streams` [here](https://github.com/ClickHouse/ClickHouse/blob/master/docs/en/development/architecture.md#block-streams-block-streams)

**Comment by alexey-milovidov** [comment]
#42547
