### ISSUE TITLE
JSON data type provide ability to handle error Uncompatible types of subcolumn

### ISSUE THREAD

**Issue by pavel-naumenko** [ClickHouse/ClickHouse#37526]
### Description
Currently if record contains JSON value with attributes that aren't compatible with previous entries, exception raised "Uncompatible types of subcolumn '{}'" and record not inserted.

It would be beneficial if some setting would allow:
- skip  error and still populate record with all columns except problematic subcolumn
  E.g.
```
    <table>(
        column1,
        column2, 
        ...
        obj JSON
    )

    <record1>
        (values...,  {"property": value, "mutable_property": scalar}) 
    -> 
        write record  with columns populated +  obj.property = value, obj.mutable_property = scalar, 
    
    <record2>
        (values...,  {"property": value, "mutable_property": Array() }) 
    ->
        write record  with columns populated +  obj.property = value, obj.mutable_property = not popuplated/empty as conflicts with existing subcolumn type
```
or

- skip  error and still populate record with all columns except JSON type column

or

- allow to have different subcolumn definitions per namespace defined by specific column
```
E.g. table that stores events for different applications/clients with uncontrollable structure across apps
<table>(
      app_id,
      context JSON
  )
  ENGINE = MergeTree()
  
allow some setting to define app_id as namespace
then   store data in context.<app_id>.<property> instead of context.<property>
select  context.<property> -> retrieve context.<app_id>.<property>
 ```

**Comment by shaeqahmed** [comment]
@CurtizJ Would it be possible to take a strategy similar to Rocket ["smart schema"](https://rockset.com/docs/commands/#mixed-types), where nested JSON fields of incompatible type are stored separately and matched based on the query? This would make it much easier to forward / query any JSON in Clickhouse without worrying about schema conflicts when using dynamic data sources such as AWS Cloudtrail.

**Comment by codeselim** [comment]
We are experiencing the very same issue and we would appreciate if you can implement this feature. 
We are using Kafka Engine tables with MV. This missing error handling totally blocks the data ingestion.
