### ISSUE TITLE
Dictionary background reload 393. DB::Exception: THERE_IS_NO_QUERY

### ISSUE THREAD

**Issue by kolsys** [ClickHouse/ClickHouse#37538]
For dictionaries over VIEW Clickhouse throws exception while reloading by TTL.

Version: 22.3.3.44

**How to reproduce**

Create view
```sql
CREATE VIEW  testing.bad_dict_source (`key` String, `name` String) as 
SELECT * FROM VALUES('key String, name String', ('foo', 'bar'), ('bar', 'baz'))
```
Create dictionary over view
```
CREATE DICTIONARY testing.bad_dict (
  `key` String DEFAULT '',
  `name` String DEFAULT ''
) PRIMARY KEY key SOURCE(
  CLICKHOUSE(
    HOST 'localhost' PORT tcpPort() DB 'testing' TABLE 'bad_dict_source'
  )
) LIFETIME(MIN 5 MAX 10) LAYOUT(COMPLEX_KEY_HASHED())
```

Load dictionary
```
SELECT *
FROM testing.bad_dict

Query id: 70f7acb2-26fe-47ce-a289-cf58ab697ae0

┌─key─┬─name─┐
│ foo │ bar  │
│ bar │ baz  │
└─────┴──────┘
```
Check errors:
```
SELECT
    status,
    last_exception
FROM system.dictionaries
WHERE (name = 'bad_dict') AND (database = 'testing')

Query id: d23f05dd-9e50-4ee4-8164-c81536f75fc9

┌─status─┬─last_exception─┐
│ LOADED │                │
└────────┴────────────────┘
```
Wait for 10 seconds and check again
```
SELECT
    status,
    last_exception
FROM system.dictionaries
WHERE (name = 'bad_dict') AND (database = 'testing')

Query id: 0dd04f00-41dc-4bb3-ad95-2be578698632

┌─status─┬─last_exception─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ LOADED │ Code: 393. DB::Exception: There is no query or query context has expired. (THERE_IS_NO_QUERY) (version 22.3.3.44 (official build)) │
└────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

**Error message and/or stacktrace**
```
Could not update external dictionary 'testing.bad_dict', leaving the previous version, next update is scheduled at 2022-05-25 18:24:53: Code: 393. DB::Exception: There is no query or query context has expired. (THERE_IS_NO_QUERY), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xb3712fa in /usr/bin/clickhouse
1. DB::Context::getQueryContext() const @ 0x1549c24a in /usr/bin/clickhouse
2. DB::JoinedTables::getLeftTableStorage() @ 0x15b109dd in /usr/bin/clickhouse
3. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const>, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::unordered_map<DB::PreparedSetKey, std::__1::shared_ptr<DB::Set>, DB::PreparedSetKey::Hash, std::__1::equal_to<DB::PreparedSetKey>, std::__1::allocator<std::__1::pair<DB::PreparedSetKey const, std::__1::shared_ptr<DB::Set> > > >) @ 0x15a895e6 in /usr/bin/clickhouse
4. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const>, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x15a88854 in /usr/bin/clickhouse
5. DB::InterpreterSelectWithUnionQuery::buildCurrentChildInterpreter(std::__1::shared_ptr<DB::IAST> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x15ae54ca in /usr/bin/clickhouse
6. DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const>, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x15ae3910 in /usr/bin/clickhouse
7. DB::StorageView::read(DB::QueryPlan&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageSnapshot const> const&, DB::SelectQueryInfo&, std::__1::shared_ptr<DB::Context const>, DB::QueryProcessingStage::Enum, unsigned long, unsigned int) @ 0x16145665 in /usr/bin/clickhouse
8. DB::InterpreterSelectQuery::executeFetchColumns(DB::QueryProcessingStage::Enum, DB::QueryPlan&) @ 0x15a9c69c in /usr/bin/clickhouse
9. DB::InterpreterSelectQuery::executeImpl(DB::QueryPlan&, std::__1::optional<DB::Pipe>) @ 0x15a93d2f in /usr/bin/clickhouse
10. DB::InterpreterSelectQuery::buildQueryPlan(DB::QueryPlan&) @ 0x15a936b0 in /usr/bin/clickhouse
11. DB::InterpreterSelectWithUnionQuery::buildQueryPlan(DB::QueryPlan&) @ 0x15ae6783 in /usr/bin/clickhouse
12. DB::InterpreterSelectWithUnionQuery::execute() @ 0x15ae79a8 in /usr/bin/clickhouse
13. ? @ 0x15d27d3a in /usr/bin/clickhouse
14. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x15d258b5 in /usr/bin/clickhouse
15. DB::ClickHouseDictionarySource::createStreamForQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::atomic<unsigned long>*) @ 0x12918ec2 in /usr/bin/clickhouse
16. DB::ClickHouseDictionarySource::loadAll() @ 0x12919b32 in /usr/bin/clickhouse
17. DB::HashedDictionary<(DB::DictionaryKeyType)1, false>::loadData() @ 0x12f687f4 in /usr/bin/clickhouse
18. DB::HashedDictionary<(DB::DictionaryKeyType)1, false>::HashedDictionary(DB::StorageID const&, DB::DictionaryStructure const&, std::__1::shared_ptr<DB::IDictionarySource>, DB::HashedDictionaryStorageConfiguration const&, std::__1::shared_ptr<DB::Block>) @ 0x12f6853e in /usr/bin/clickhouse
19. DB::HashedDictionary<(DB::DictionaryKeyType)1, false>::clone() const @ 0x12f69a35 in /usr/bin/clickhouse
20. DB::ExternalLoader::LoadingDispatcher::loadSingleObject(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::ExternalLoader::ObjectConfig const&, std::__1::shared_ptr<DB::IExternalLoadable const>) @ 0x157c5ed5 in /usr/bin/clickhouse
21. DB::ExternalLoader::LoadingDispatcher::doLoading(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, bool, unsigned long, bool, std::__1::shared_ptr<DB::ThreadGroupStatus>) @ 0x157c3159 in /usr/bin/clickhouse
22. ThreadFromGlobalPool::ThreadFromGlobalPool<void (DB::ExternalLoader::LoadingDispatcher::*)(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, bool, unsigned long, bool, std::__1::shared_ptr<DB::ThreadGroupStatus>), DB::ExternalLoader::LoadingDispatcher*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, unsigned long&, bool&, unsigned long&, bool, std::__1::shared_ptr<DB::ThreadGroupStatus> >(void (DB::ExternalLoader::LoadingDispatcher::*&&)(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, bool, unsigned long, bool, std::__1::shared_ptr<DB::ThreadGroupStatus>), DB::ExternalLoader::LoadingDispatcher*&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, unsigned long&, bool&, unsigned long&, bool&&, std::__1::shared_ptr<DB::ThreadGroupStatus>&&)::'lambda'()::operator()() @ 0x157ca3cd in /usr/bin/clickhouse
23. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xb418757 in /usr/bin/clickhouse
24. ? @ 0xb41c2dd in /usr/bin/clickhouse
25. start_thread @ 0x76db in /lib/x86_64-linux-gnu/libpthread-2.27.so
26. clone @ 0x12161f in /lib/x86_64-linux-gnu/libc-2.27.so
 (version 22.3.3.44 (official build))
```

**Additional context**

After manually reloading dictionary the status is ok but after expiration it's throws exception again.

**Comment by jeejeeone** [comment]
With version 22.3.12.20.altinitystable there is a similar looking problem when dict source is view which has queries postgresql. Dicts sourced with views without postgresql queries do work.

Stacktrace:

`2022.10.20 10:01:22.294588 [ 1815 ] {} <Error> ExternalDictionariesLoader: Could not update external dictionary 'xx.somedict', leaving the previous version, next update is scheduled at 2022-10-20 10:01:27: Code: 393. DB::Exception: There is no query or query context has expired. (THERE_IS_NO_QUERY), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xb3765ba in /usr/bin/clickhouse
1. DB::Context::getQueryContext() const @ 0x154aa7aa in /usr/bin/clickhouse
2. DB::JoinedTables::getLeftTableStorage() @ 0x15b2021d in /usr/bin/clickhouse
3. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const>, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, DB::SubqueryForSet, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, DB::SubqueryForSet> > >, std::__1::unordered_map<DB::PreparedSetKey, std::__1::shared_ptr<DB::Set>, DB::PreparedSetKey::Hash, std::__1::equal_to<DB::PreparedSetKey>, std::__1::allocator<std::__1::pair<DB::PreparedSetKey const, std::__1::shared_ptr<DB::Set> > > >) @ 0x15a984dc in /usr/bin/clickhouse
4. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const>, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x15a97602 in /usr/bin/clickhouse
5. DB::InterpreterSelectWithUnionQuery::buildCurrentChildInterpreter(std::__1::shared_ptr<DB::IAST> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x15af4c6a in /usr/bin/clickhouse
6. DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const>, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x15af2f90 in /usr/bin/clickhouse
7. DB::InterpreterSelectWithUnionQuery::getSampleBlock(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const>, bool) @ 0x15af5918 in /usr/bin/clickhouse
8. DB::getDatabaseAndTablesWithColumns(std::__1::vector<DB::ASTTableExpression const*, std::__1::allocator<DB::ASTTableExpression const*> > const&, std::__1::shared_ptr<DB::Context const>, bool, bool) @ 0x15d4d8fc in /usr/bin/clickhouse
9. DB::JoinedTables::resolveTables() @ 0x15b2089f in /usr/bin/clickhouse
10. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const>, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, DB::SubqueryForSet, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, DB::SubqueryForSet> > >, std::__1::unordered_map<DB::PreparedSetKey, std::__1::shared_ptr<DB::Set>, DB::PreparedSetKey::Hash, std::__1::equal_to<DB::PreparedSetKey>, std::__1::allocator<std::__1::pair<DB::PreparedSetKey const, std::__1::shared_ptr<DB::Set> > > >) @ 0x15a9837c in /usr/bin/clickhouse
11. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const>, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x15a97602 in /usr/bin/clickhouse
12. DB::InterpreterSelectWithUnionQuery::buildCurrentChildInterpreter(std::__1::shared_ptr<DB::IAST> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x15af4c6a in /usr/bin/clickhouse
13. DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const>, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x15af2f90 in /usr/bin/clickhouse
14. DB::StorageView::read(DB::QueryPlan&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageSnapshot const> const&, DB::SelectQueryInfo&, std::__1::shared_ptr<DB::Context const>, DB::QueryProcessingStage::Enum, unsigned long, unsigned int) @ 0x16156e85 in /usr/bin/clickhouse
15. DB::InterpreterSelectQuery::executeFetchColumns(DB::QueryProcessingStage::Enum, DB::QueryPlan&) @ 0x15aad92c in /usr/bin/clickhouse
16. DB::InterpreterSelectQuery::executeImpl(DB::QueryPlan&, std::__1::optional<DB::Pipe>) @ 0x15aa3081 in /usr/bin/clickhouse
17. DB::InterpreterSelectQuery::buildQueryPlan(DB::QueryPlan&) @ 0x15aa2a10 in /usr/bin/clickhouse
18. DB::InterpreterSelectWithUnionQuery::buildQueryPlan(DB::QueryPlan&) @ 0x15af5f23 in /usr/bin/clickhouse
19. DB::InterpreterSelectWithUnionQuery::execute() @ 0x15af7148 in /usr/bin/clickhouse
20. ? @ 0x15d3940f in /usr/bin/clickhouse
21. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x15d36eb5 in /usr/bin/clickhouse
22. DB::ClickHouseDictionarySource::createStreamForQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::atomic<unsigned long>*) @ 0x12920442 in /usr/bin/clickhouse
23. DB::ClickHouseDictionarySource::loadAll() @ 0x129210b2 in /usr/bin/clickhouse
24. DB::HashedDictionary<(DB::DictionaryKeyType)1, false>::loadData() @ 0x12f70814 in /usr/bin/clickhouse
25. DB::HashedDictionary<(DB::DictionaryKeyType)1, false>::HashedDictionary(DB::StorageID const&, DB::DictionaryStructure const&, std::__1::shared_ptr<DB::IDictionarySource>, DB::HashedDictionaryStorageConfiguration const&, std::__1::shared_ptr<DB::Block>) @ 0x12f7055e in /usr/bin/clickhouse
26. DB::HashedDictionary<(DB::DictionaryKeyType)1, false>::clone() const @ 0x12f71a55 in /usr/bin/clickhouse
27. DB::ExternalLoader::LoadingDispatcher::loadSingleObject(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::ExternalLoader::ObjectConfig const&, std::__1::shared_ptr<DB::IExternalLoadable const>) @ 0x157d4995 in /usr/bin/clickhouse
28. DB::ExternalLoader::LoadingDispatcher::doLoading(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, bool, unsigned long, bool, std::__1::shared_ptr<DB::ThreadGroupStatus>) @ 0x157d1c19 in /usr/bin/clickhouse
29. ThreadFromGlobalPool::ThreadFromGlobalPool<void (DB::ExternalLoader::LoadingDispatcher::*)(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, bool, unsigned long, bool, std::__1::shared_ptr<DB::ThreadGroupStatus>), DB::ExternalLoader::LoadingDispatcher*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, unsigned long&, bool&, unsigned long&, bool, std::__1::shared_ptr<DB::ThreadGroupStatus> >(void (DB::ExternalLoader::LoadingDispatcher::*&&)(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, bool, unsigned long, bool, std::__1::shared_ptr<DB::ThreadGroupStatus>), DB::ExternalLoader::LoadingDispatcher*&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, unsigned long&, bool&, unsigned long&, bool&&, std::__1::shared_ptr<DB::ThreadGroupStatus>&&)::'lambda'()::operator()() @ 0x157d8e8d in /usr/bin/clickhouse
30. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xb41b337 in /usr/bin/clickhouse
31. ? @ 0xb41eebd in /usr/bin/clickhouse
 (version 22.3.12.20.altinitystable (altinity build))`

A simplified example of our dict setup:

```
CREATE DICTIONARY db.some_dict
(
    `id` UInt64
	`sub_id` UInt64
)
PRIMARY KEY id, sub_id
SOURCE(CLICKHOUSE(HOST 'localhost' DB 'db' TABLE 'vuew'))
LIFETIME(MIN 1 MAX 5)
LAYOUT(COMPLEX_KEY_HASHED())

CREATE VIEW db.some_view
(
    `id` UInt64
	`sub_id` UInt64
) AS 
SELECT id, sub_id FROM (
	SELECT id, sub_id FROM postgresql('psql:5432', 'db', 'table', 'user', 'pw')
)
```
@kolsys Any news on this one?

**Comment by kolsys** [comment]
After upgrade to the 22.8-LTS the issue was gone. Before that we was using workaround with cron task that fetching all affected dictionaries and force to reload it.

```
SELECT origin FROM system.dictionaries WHERE last_exception LIKE '%THERE_IS_NO_QUERY%'
```

**Comment by alexey-milovidov** [comment]
Good.

> (version 22.3.12.20.altinitystable (altinity build))

The bug was present in the unofficial Altinity build, that should not be used.

> After upgrade to the 22.8-LTS the issue was gone.

The official ClickHouse build has the issue fixed.

Note that Altinity versions should be avoided - they are known to have bugs and security vulnerabilities not been fixed for a long time.
