### ISSUE TITLE
Can't delete column

### ISSUE THREAD

**Issue by alexey-egoshin** [ClickHouse/ClickHouse#37535]
Table:
```
create table rates
(
    symbol_id   UInt64,
    symbol_code String,
    created_at  Nullable(DateTime),
    tstamp      DateTime        default now(),
    value       Decimal(22, 10) default 0
)
    engine = MergeTree ORDER BY created_at
        SETTINGS index_granularity = 8192;
```
SQL-command:
`alter table rates drop column created_at;`

Result:
`Code: 47. DB::Exception: Missing columns: 'created_at' while processing query: 'created_at', required columns: 'created_at' 'created_at'. (UNKNOWN_IDENTIFIER) (version 22.1.3.7 (official build)).`

**Comment by phantom943** [comment]
This obscure error message tries to tell you that `created_at` is an ordering key column (part of ` ORDER BY` in the table creation statement), so it can't be dropped without modifying the table create statement, because data is actually physically stored using `created_at` as a partition key.

**Comment by alexey-egoshin** [comment]
> This obscure error message tries to tell you that `created_at` is an ordering key column (part of ` ORDER BY` in the table creation statement), so it can't be dropped without modifying the table create statement, because data is actually physically stored using `created_at` as a partition key.

Thank you bro. How can we delete column without lost data (INSERTs are all time)? Or should create new table?

**Comment by phantom943** [comment]
> > This obscure error message tries to tell you that `created_at` is an ordering key column (part of ` ORDER BY` in the table creation statement), so it can't be dropped without modifying the table create statement, because data is actually physically stored using `created_at` as a partition key.
> 
> Thank you bro. How can we delete column without lost data (INSERTs are all time)? Or should create new table?

I think something like this should work:
https://clickhouse.com/docs/en/sql-reference/statements/alter/order-by/

**Comment by alexey-egoshin** [comment]
> I think something like this should work: https://clickhouse.com/docs/en/sql-reference/statements/alter/order-by/
We can't set another column. How to remove ORDER BY query from DDL?
