### ISSUE TITLE
Cpu Peaks After Upgrading Clickhouse Version

### ISSUE THREAD

**Issue by ilkerdemirci08** [ClickHouse/ClickHouse#37550]
Hello,

I have a clickhouse cluster with 3 seperate servers with version 20.11.4.13-2.
I updated the versions to 21.5.9.4-2, by the time i updated it cpu usages went crazy.

Here is the before and the after,
![image](https://user-images.githubusercontent.com/94440576/170368567-02aefa3e-3151-459e-b69b-c673c0ff56f0.png)

Other metrics are also effected, ram usage seems to be lower than before but disk usage is more aggresive.
But those are not peaking and not causing any trouble.

Servers have 4 core cpus, they were perfectly fine before the upgrade but now they are struggling.
Is this version bugged or something? Maybe the cpu and the ram usages' logic changed drastically after a certain version.

Any help will be appreciated.

**Comment by den-crane** [comment]
21.5.9.4 is obsolete and out of support. Why do you upgrade to it?

How many *MergeTree tables do you have?
How many Replicated*MergeTree tables do you have?

**Comment by ilkerdemirci08** [comment]
Hello, i see that there are 237 tables when i typed show tables. Is this the correct way to check it?

**Comment by alexey-milovidov** [comment]
237 tables is not much, but you should upgrade ClickHouse to the latest version.
