### ISSUE TITLE
ttl_only_drop_parts explanation

### ISSUE THREAD

**Issue by rkozlo** [ClickHouse/ClickHouse#37564]
Hi,
it may be a stupid question but this option in merge tree settings `ttl_only_drop_parts` is affected also on ttl's where is used different action than delete? For example moving or grouping whole partition

**Comment by UnamedRus** [comment]
> For example moving

No, ClickHouse will move only whole partition

> grouping whole partition

No, (AFAIK) because if we talk about GROUP BY, it doesn't make sense to wait whole partition expire.

> different action than delete? 

I don't think so.
