### ISSUE TITLE
Projection `SELECT * APPLY groupUniqArray` corrupts metadata

### ISSUE THREAD

**Issue by markandrus** [ClickHouse/ClickHouse#37590]
**Describe what's wrong**

1. Create a ReplicatedMergeTree (probably any table supporting projections is fine):

```
CREATE TABLE foo (bar String) ENGINE = ReplicatedMergeTree('/clickhouse/{installation}/{cluster}/tables/{shard}/{database}/{table}', '{replica}') ORDER BY bar;
```

2. Observe that `SELECT * APPLY groupUniqArray(100) FROM foo` works just fine:

```
:) SELECT * APPLY groupUniqArray(100) FROM foo;

SELECT * APPLY groupUniqArray 100
FROM foo

Query id: 3baddc69-ecee-4409-bdea-fb84b27dba3c

┌─groupUniqArray(100)(bar)─┐
│ []                       │
└──────────────────────────┘

1 rows in set. Elapsed: 0.228 sec. 
```

3. Add a projection, using the same query. Notice that the pretty-printed SQL looks incorrect (`SELECT * APPLY groupUniqArray100` instead of `SELECT * APPLY groupUniqArray 100`). Notice also that the query hangs. It will timeout and will fail to cancel.

```
:) ALTER TABLE foo ADD PROJECTION bug (SELECT * APPLY groupUniqArray(100))

ALTER TABLE foo
    ADD PROJECTION bug
    (
        SELECT * APPLY groupUniqArray100
    )

Query id: de5fb17e-a563-42b1-9d58-0b60d0dd845f

Timeout exceeded while receiving data from server. Waited for 300 seconds, timeout is 300 seconds.
Cancelling query.
```

4. At this point, metadata in ZooKeeper is corrupted. See `groupUniqArray100`…

```
:) SELECT * FROM system.zookeeper WHERE path = '/clickhouse/v2/v2/tables/0/default/foo' AND name = 'metadata'\G

SELECT *
FROM system.zookeeper
WHERE (path = '/clickhouse/v2/v2/tables/0/default/foo') AND (name = 'metadata')

Query id: 9c43597b-a399-4e1f-ab94-acb5e975201f

Row 1:
──────
name:           metadata
value:          metadata format version: 1
date column: 
sampling expression: 
index granularity: 8192
mode: 0
sign column: 
primary key: bar
data format version: 1
partition key: 
projections: bug (SELECT * APPLY groupUniqArray100)
granularity bytes: 10485760

czxid:          4295025988
mzxid:          4295026032
ctime:          2022-05-27 07:57:43
mtime:          2022-05-27 08:01:18
version:        5
cversion:       0
aversion:       0
ephemeralOwner: 0
dataLength:     245
numChildren:    0
pzxid:          4295025988
path:           /clickhouse/v2/v2/tables/0/default/foo

1 rows in set. Elapsed: 0.232 sec.
```

It's very unfortunate if you then restart the ClickHouse server, because it will crash on startup with "Unknown function groupUniqArray100". I eventually recovered by messing around with zkCli.sh on our ZooKeeper hosts. I tried removing the bad projection, but this didn't work because the metadata format really wants a trailing newline, which I could not figure out how to insert with zkCli.sh… (maybe something like https://github.com/ClickHouse/ClickHouse/issues/22130 would help). Finally, I had to do this (repeating for all replicas):

1. `DETACH TABLE default.foo;`
2. `SYSTEM DROP REPLICA 'chi-v2-v2-0-0' FROM zkpath '/clickhouse/v2/v2/tables/0/default/foo';`
3. `ATTACH TABLE default.foo;`
4. `SYSTEM RESTORE REPLICA default.foo;`

**Does it reproduce on recent release?**

Yes, on 22.3.3.44.

**Comment by UnamedRus** [comment]
Related https://github.com/ClickHouse/ClickHouse/issues/33684
