### ISSUE TITLE
Cleanup branches in the repo

### ISSUE THREAD

**Issue by fredgan** [ClickHouse/ClickHouse#37615]
Hi folks,
I found that there are **5,880 branches** in the repo. Many of them are cherry-pick branches which is useless now. Maybe they should be cleaned. How do you think?

**Comment by alexey-milovidov** [comment]
I don't care at all about these branches.

What is the advantage of cleanup?
But if we do the cleanup, we may accidentally mess up something and lose some parts of the history stored on GitHub.

**Comment by tavplubix** [comment]
I agree that old branches are useful sometimes. Example: https://github.com/ClickHouse/ClickHouse/issues/36792#issuecomment-1119254489

But I'm doubt that automatically generated branches like `backport/*` and `cherrypick/*` are useful for the history (these branches rather polluting the history).

**Comment by fredgan** [comment]
@alexey-milovidov 

Today I ran into a problem when I clone this repo:

```sh
$ git clone https://github.com/ClickHouse/ClickHouse.git
Cloning into 'ClickHouse'...

error: RPC failed; HTTP 403 curl 22 The requested URL returned error: 403
fatal: expected 'packfile'
```

While other repo such as `ClickBench` doesn't have this problem.

I don't know if it has anything to do with the excessive number of branches.
