### ISSUE TITLE
Continuous error log of Exception: Unexpected merged part intersecting drop range

### ISSUE THREAD

**Issue by ibahnasy** [ClickHouse/ClickHouse#37646]
Cluster of ClickHouse server version 21.6.3.14.

I'm getting the below error continuously in the log, please suggest a way to solve it. 

`<Error> mydb.mytable: auto DB::StorageReplicatedMergeTree::processQueueEntry(ReplicatedMergeTreeQueue::SelectedEntryPtr)::(anonymous class)::operator()(DB::StorageReplicatedMergeTree::LogEntryPtr &) const: Code: 49, e.displayText() = DB::Exception: Unexpected merged part 202112_0_343830_54621_343572 intersecting drop range 202112_301227_301227_0_301451, Stack trace (when copying this message, always include the lines below):
--
  |  
  | 0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x8b5b17a in /usr/bin/clickhouse
  | 1. DB::Exception::Exception<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&) @ 0xda7767e in /usr/bin/clickhouse
  | 2. DB::MergeTreeData::removePartsInRangeFromWorkingSet(DB::MergeTreePartInfo const&, bool, std::__1::unique_lock<std::__1::mutex>&) @ 0x100ebedf in /usr/bin/clickhouse
  | 3. DB::StorageReplicatedMergeTree::executeDropRange(DB::ReplicatedMergeTreeLogEntry const&) @ 0xfea349e in /usr/bin/clickhouse
  | 4. DB::StorageReplicatedMergeTree::executeLogEntry(DB::ReplicatedMergeTreeLogEntry&) @ 0xfea15cd in /usr/bin/clickhouse
  | 5. ? @ 0xff2565f in /usr/bin/clickhouse
  | 6. DB::ReplicatedMergeTreeQueue::processEntry(std::__1::function<std::__1::shared_ptr<zkutil::ZooKeeper> ()>, std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&, std::__1::function<bool (std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&)>) @ 0x102a6a8c in /usr/bin/clickhouse
  | 7. DB::StorageReplicatedMergeTree::processQueueEntry(std::__1::shared_ptr<DB::ReplicatedMergeTreeQueue::SelectedEntry>) @ 0xfed54bd in /usr/bin/clickhouse
  | 8. ? @ 0x1006b8d7 in /usr/bin/clickhouse
  | 9. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0x8b9df58 in /usr/bin/clickhouse
  | 10. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()&&...)::'lambda'()::operator()() @ 0x8b9f91f in /usr/bin/clickhouse
  | 11. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x8b9b49f in /usr/bin/clickhouse
  | 12. ? @ 0x8b9e9c3 in /usr/bin/clickhouse
  | 13. start_thread @ 0x76db in /lib/x86_64-linux-gnu/libpthread-2.27.so
  | 14. clone @ 0x12161f in /lib/x86_64-linux-gnu/libc-2.27.so`

**Comment by tavplubix** [comment]
> Cluster of ClickHouse server version 21.6.3.14

This version is outdated. List of supported versions is here: https://github.com/ClickHouse/ClickHouse/pulls?q=is%3Aopen+is%3Apr+label%3Arelease

Since 21.6 we made a lot of fixes for this error and similar error. Consider upgrading to 22.3.

> please suggest a way to solve it

See https://github.com/ClickHouse/ClickHouse/issues/35863#issuecomment-1092787460. But the error will appear again if you do not upgrade.

**Comment by ibahnasy** [comment]
I performed the suggestions in that above comment and then upgraded to version 22.5.1, then all tables are in readonly mode.
How can I them work properly again?

` <Error> mydb.mytbl (079a8241-0dde-4651-879a-82410dde3651): void DB::StorageReplicatedMergeTree::mutationsFinalizingTask(): Code: 242. DB::Exception: Table is in readonly mode (replica path: /clickhouse/tables/1-1/mydb.mytbl/replicas/clickhouse-secondary). (TABLE_IS_READ_ONLY), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xb4903fa in /usr/bin/clickhouse
1. DB::Exception::Exception<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>(int, fmt::v8::basic_format_string<char, fmt::v8::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>::type>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xb4ff4f8 in /usr/bin/clickhouse
2. DB::StorageReplicatedMergeTree::getZooKeeperAndAssertNotReadonly() const @ 0x1639efa3 in /usr/bin/clickhouse
3. DB::StorageReplicatedMergeTree::mutationsFinalizingTask() @ 0x1641852f in /usr/bin/clickhouse
4. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x1502aa6e in /usr/bin/clickhouse
5. DB::BackgroundSchedulePool::threadFunction() @ 0x1502de86 in /usr/bin/clickhouse
6. ? @ 0x1502ee30 in /usr/bin/clickhouse
7. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xb53fc47 in /usr/bin/clickhouse
8. ? @ 0xb54367d in /usr/bin/clickhouse
9. start_thread @ 0x76db in /lib/x86_64-linux-gnu/libpthread-2.27.so
10. __clone @ 0x12161f in /lib/x86_64-linux-gnu/libc-2.27.so
 (version 22.5.1.2079 (official build))
2022.05.31 10:27:23.961655 [ 9479 ] {} <Error> mydb.mytbl (079a8241-0dde-4651-879a-82410dde3651): void DB::StorageReplicatedMergeTree::mutationsFinalizingTask(): Code: 242. DB::Exception: Table is in readonly mode (replica path: /clickhouse/tables/1-1/mydb.mytbl/replicas/clickhouse-secondary). (TABLE_IS_READ_ONLY), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xb4903fa in /usr/bin/clickhouse
1. DB::Exception::Exception<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>(int, fmt::v8::basic_format_string<char, fmt::v8::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>::type>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xb4ff4f8 in /usr/bin/clickhouse
2. DB::StorageReplicatedMergeTree::getZooKeeperAndAssertNotReadonly() const @ 0x1639efa3 in /usr/bin/clickhouse
3. DB::StorageReplicatedMergeTree::mutationsFinalizingTask() @ 0x1641852f in /usr/bin/clickhouse
4. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x1502aa6e in /usr/bin/clickhouse
5. DB::BackgroundSchedulePool::threadFunction() @ 0x1502de86 in /usr/bin/clickhouse
6. ? @ 0x1502ee30 in /usr/bin/clickhouse
7. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xb53fc47 in /usr/bin/clickhouse
8. ? @ 0xb54367d in /usr/bin/clickhouse
9. start_thread @ 0x76db in /lib/x86_64-linux-gnu/libpthread-2.27.so
10. __clone @ 0x12161f in /lib/x86_64-linux-gnu/libc-2.27.so
 (version 22.5.1.2079 (official build))`

**Comment by tavplubix** [comment]
See https://github.com/ClickHouse/ClickHouse/issues/35863#issuecomment-1092787460
