### ISSUE TITLE
Which version can be used for clickhouse-keeper? No server.key file issue in 22.3.6.5 version

### ISSUE THREAD

**Issue by taotaizhu-pw** [ClickHouse/ClickHouse#37660]
We want to use clickhouse-keeper for cluster. We see 22.3 is a lst version, and the clickhouse-keeper is production ready. But after update to 22.3.6.5, we found the following issue when start the server: 

 <Error> CertificateReloader: Cannot obtain modification time for certificate file /etc/clickhouse-server/server.crt, skipping update. errno: 2, strerror: No such file or directory
<Error> CertificateReloader: Cannot obtain modification time for key file /etc/clickhouse-server/server.key, skipping update. errno: 2, strerror: No such file or directory
<Error> CertificateReloader: Poco::Exception. Code: 1000, e.code() = 0, SSL context exception: Error loading private key from file /etc/clickhouse-server/server.key: error:02000002:system library:OPENSSL_internal:No such file or directory (version 22.3.6.5 (official build))

How to resolve this issue? Which version can we use for production? Thanks!

**Comment by taotaizhu-pw** [comment]
any reply? thanks

**Comment by novikd** [comment]
Could you please provide the whole error message? Probably related to #35751. Does workaround from that issue helps you?

**Comment by taotaizhu-pw** [comment]
> Could you please provide the whole error message? Probably related to #35751. Does workaround from that issue helps you?

It seems can be related to #35552 (https://github.com/ClickHouse/ClickHouse/issues/35552). It was fixed, when it will be released ? thanks

**Comment by novikd** [comment]
You can use workaround provided in that issue. It was released with 22.5 (not backported to 22.3).

**Comment by novikd** [comment]
Because it's not a bug, but a usability issue. Did you solve the problem?

**Comment by taotaizhu-pw** [comment]
> Because it's not a bug, but a usability issue. Did you solve the problem?

Thanks! got it
