### ISSUE TITLE
Stress test: The local set of parts doesn't look like the set of parts in ZooKeeper

### ISSUE THREAD

**Issue by tavplubix** [ClickHouse/ClickHouse#37664]
Sometimes server fails to start after BC check with errors like
```
2022.05.29 03:17:31.597820 [ 213989 ] {} <Error> Application: Caught exception while loading metadata: Code: 231. DB::Exception: The local set of parts of table test_metadata_cache.check_part_metadata_cache (2383e9d1-92b1-4e45-b207-780cd6192e1d) doesn't look like the set of parts in ZooKeeper: 12.00 rows of 12.00 total rows in filesystem are suspicious. There are 3 unexpected parts with 12 rows (0 of them is not just-written with 0 rows), 0 missing parts (with 0 blocks).
```

Example:
https://s3.amazonaws.com/clickhouse-test-reports/37622/313f4833d641993a4d090691c0f8d1921ded97a3/stress_test__debug__actions_.html

**Comment by tavplubix** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/0/85cb151fcbc14daf3f455a37ffdb49a6f29c5340/stress_test__memory__actions_.html

**Comment by qoega** [comment]
I have this error live on ClickHouse cluster. 
Inserted data -> 'Query failed because of max_memory_usage'  -> `TRUNCATE TABLE` -> Repeat. 
Then restarted server.

**Comment by qoega** [comment]
```
2022.08.19 10:56:36.660311 [ 47 ] {} <Error> Application: DB::Exception: The local set of parts of table default.catalog_sales (3f9d51f2-5be7-4c42-b141-ca09369b8c41) doesn't look like the set of parts in ZooKeeper: 31.85 million rows of 31.85 million total rows in filesystem are suspicious. There are 16 uncovered unexpected parts with 31850496 rows (2 of them is not just-written with 15335424 rows), 0 missing parts (with 0 blocks), 0 covered unexpected parts (with 0 rows).: Cannot attach table `default`.`catalog_sales` from metadata file /var/lib/clickhouse/store/03f/03fe488d-11f9-4b99-b7d7-a2b4f4c67e15/catalog_sales.sql from query ATTACH TABLE default.catalog_sales UUID '3f9d51f2-5be7-4c42-b141-ca09369b8c41' (`cs_sold_date_sk` Nullable(Int64), `cs_sold_time_sk` Nullable(Int64), `cs_ship_date_sk` Nullable(Int64), `cs_bill_customer_sk` Nullable(Int64), `cs_bill_cdemo_sk` Nullable(Int64), `cs_bill_hdemo_sk` Nullable(Int64), `cs_bill_addr_sk` Nullable(Int64), `cs_ship_customer_sk` Nullable(Int64), `cs_ship_cdemo_sk` Nullable(Int64), `cs_ship_hdemo_sk` Nullable(Int64), `cs_ship_addr_sk` Nullable(Int64), `cs_call_center_sk` Nullable(Int64), `cs_catalog_page_sk` Nullable(Int64), `cs_ship_mode_sk` Nullable(Int64), `cs_warehouse_sk` Nullable(Int64), `cs_item_sk` Int64, `cs_promo_sk` Nullable(Int64), `cs_order_number` Int64, `cs_quantity` Nullable(Int32), `cs_wholesale_cost` Nullable(Decimal(7, 2)), `cs_list_price` Nullable(Decimal(7, 2)), `cs_sales_price` Nullable(Decimal(7, 2)), `cs_ext_discount_amt` Nullable(Decimal(7, 2)), `cs_ext_sales_price` Nullable(Decimal(7, 2)), `cs_ext_wholesale_cost` Nullable(Decimal(7, 2)), `cs_ext_list_price` Nullable(Decimal(7, 2)), `cs_ext_tax` Nullable(Decimal(7, 2)), `cs_coupon_amt` Nullable(Decimal(7, 2)), `cs_ext_ship_cost` Nullable(Decimal(7, 2)), `cs_net_paid` Nullable(Decimal(7, 2)), `cs_net_paid_inc_tax` Nullable(Decimal(7, 2)), `cs_net_paid_inc_ship` Nullable(Decimal(7, 2)), `cs_net_paid_inc_ship_tax` Nullable(Decimal(7, 2)), `cs_net_profit` Decimal(7, 2)) ENGINE = ReplicatedMergeTree('/clickhouse/tables/{uuid}/{shard}', '{replica}') PRIMARY KEY (cs_item_sk, cs_order_number) ORDER BY (cs_item_sk, cs_order_number) SETTINGS index_granularity = 8192, use_metadata_cache = 1
```

**Comment by vijay1811** [comment]
I have seen same issue

**Comment by vijay1811** [comment]
`10:31:15.865419 [ 64 ] {} <Error> Application: DB::Exception: The local set of parts of table DB_1.tags_v3 (51a10fb6-360d-4b55-8911-f1928567a01a) doesn't look like the set of parts in ZooKeeper: 94.65 thousand rows of 155.07 thousand total rows in filesystem are suspicious. There are 2 unexpected parts with 94646 rows (2 of them is not just-written with 94646 rows), 0 missing parts (with 0 blocks).: Cannot attach table `DB_1`.`tags_v3` from metadata file /bp2/data/store/8c3/8c39bfe0-f8d3-4d84-9685-53f25137ee6c/tags_v3.sql from query ATTACH TABLE DB_1.tags_v3 UUID '51a10fb6-360d-4b55-8911-f1928567a01a' `DB_1` from path /bp2/data/metadata/DB_1
`

**Comment by tavplubix** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/46820/7ff8d2d3d5a5ff77bff2e3c41b57458183bbf623/stress_test__asan_.html

**Comment by tavplubix** [comment]
> Are there any workarounds that help to recover from this state?

https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/replication/#recovery-after-failures

**Comment by xsong123** [comment]
i have the same error:
Application: Caught exception while loading metadata: Code: 231. DB::Exception: The local set of parts of table ls_chdb.dwd_acc_valtable (13bf9dbf-909c-4e35-941e-54579af0b68e) doesn't look like the set of parts in ZooKeeper: 1.86 million rows of 3.68 million total rows in filesystem are suspicious. There are 3 unexpected parts with 1855466 rows (1 of them is not just-written with 1824024 rows), 0 missing parts (with 0 blocks).: Cannot attach table `ls_chdb`.`dwd_acc_valtable` from metadata file /var/lib/clickhouse/store/a61/a614fce3-631f-4494-ade2-9104abb9a24e/dwd_acc_valtable.sql from query ATTACH TABLE ls_chdb.dwd_acc_valtable UUID '13bf9dbf-909c-4e35-941e-54579af0b68e' (`SEQ_NO` String COMMENT '流水号', `PORT_ID` Nullable(String) COMMENT '组合代码', `PORT_NAME` Nullable(String) COMMENT '组合名称', `BOOKSET_ID` Nullable(String) COMMENT '账套代码', `PROFIT_TYPE` Nullable(String) COMMENT '收益类型', `VAL_DATE` Date COMMENT '估值日期', `DETAIL_DIST` Nullable(String) COMMENT '明细区分', `LAYERING_ID` Nullable(String) COMMENT '分层代码', `SUBJECT_NO` Nullable(String) COMMENT '科目号', `SUBJECT_NAME` Nullable(String) COMMENT '科目名称', `FSUBJECT_ID` Nullable(String) COMMENT '上级科目号', `NUM_AMT` Nullable(Decimal(24, 7)) COMMENT '数量', `UNIT_COST` Nullable(Decimal(24, 7)) COMMENT '单位成本', `O_CCY` Nullable(String) COMMENT '原币币种', `B_CCY` Nullable(String) COMMENT '本币币种', `EX_RATE` Nullable(Decimal(30, 14)) COMMENT '汇率', `O_COST` Nullable(Decimal(24, 7)) COMMENT '原币成本', `B_COST` Nullable(Decimal(24, 7)) COMMENT '本币成本', `B_COST_PERCENT` Nullable(Decimal(30, 14)) COMMENT '本币成本占比', `CLOSE_PRICE` Nullable(Decimal(30, 14)) COMMENT '行情', `O_MARKET_VALUE` Nullable(Decimal(24, 7)) COMMENT '原币市值', `B_MARKET_VALUE` Nullable(Decimal(24, 7)) COMMENT '本币市值', `B_VALUE_PERCENT` Nullable(Decimal(30, 14)) COMMENT '本币市值占比', `O_VALUE_INCREMENT` Nullable(Decimal(24, 7)) COMMENT '原币估值增值', `B_VALUE_INCREMENT` Nullable(Decimal(24, 7)) COMMENT '本币估值增值', `SEC_STATE` Nullable(String) COMMENT '证券状态', `EQUITY_INFO` Nullable(String) COMMENT '权益信息', `BAL_FLAG` Nullable(String) COMMENT '余额方向', `SHADOW_PRICE_VALUE` Nullable(Decimal(24, 7)) COMMENT '影子价格估值', `MARKET_VAL_DATE` Nullable(DateTime) COMMENT '行情日期', `CREATE_USER` String COMMENT '创建人', `CREATE_DEPT` Nullable(String) COMMENT '创建部门', `CREATE_TIME` DateTime COMMENT '创建时间', `UPDATE_USER` String COMMENT '更新人', `UPDATE_TIME` DateTime COMMENT '更新时间', `INPUT_TYPE` String COMMENT '导入方法', `_sign` Int8 DEFAULT 1, `SUBJECT_SEQ` Decimal(20, 0) COMMENT '科目序号') ENGINE = ReplicatedCollapsingMergeTree('/clickhouse/tables/13bf9dbf-909c-4e35-941e-54579af0b68e/{shard}', '{replica}', _sign) ORDER BY SEQ_NO SETTINGS index_granularity = 8192. (TOO_MANY_UNEXPECTED_DATA_PARTS), Stack trace (when copying this message, always include the lines below):

**Comment by xsong123** [comment]
> > Are there any workarounds that help to recover from this state?
> 
> https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/replication/#recovery-after-failures

this solution can solve below error:
Caught exception while loading metadata: Code: 231. DB::Exception: The local set of parts of table ls_chdb.dwd_acc_valtable (13bf9dbf-909c-4e35-941e-54579af0b68e) doesn't look like the set of parts in ZooKeeper: 1.86 million rows of 3.68 million total rows in filesystem are suspicious

**Comment by xsong123** [comment]
> [vijay1811](/vijay1811)

i have the same error , do you have solve?
Caught exception while loading metadata: Code: 231. DB::Exception: The local set of parts of table ls_chdb.dwd_acc_valtable (13bf9dbf-909c-4e35-941e-54579af0b68e) doesn't look like the set of parts in ZooKeeper: 1.86 million rows of 3.68 million total rows in filesystem are suspicious

**Comment by xsong123** [comment]
> Sometimes server fails to start after BC check with errors like
> 
> ```
> 2022.05.29 03:17:31.597820 [ 213989 ] {} <Error> Application: Caught exception while loading metadata: Code: 231. DB::Exception: The local set of parts of table test_metadata_cache.check_part_metadata_cache (2383e9d1-92b1-4e45-b207-780cd6192e1d) doesn't look like the set of parts in ZooKeeper: 12.00 rows of 12.00 total rows in filesystem are suspicious. There are 3 unexpected parts with 12 rows (0 of them is not just-written with 0 rows), 0 missing parts (with 0 blocks).
> ```
> 
> Example: https://s3.amazonaws.com/clickhouse-test-reports/37622/313f4833d641993a4d090691c0f8d1921ded97a3/stress_test__debug__actions_.html

i have the same error , do you have solve?
Caught exception while loading metadata: Code: 231. DB::Exception: The local set of parts of table ls_chdb.dwd_acc_valtable (13bf9dbf-909c-4e35-941e-54579af0b68e) doesn't look like the set of parts in ZooKeeper: 1.86 million rows of 3.68 million total rows in filesystem are suspicious

**Comment by HattabbI4** [comment]
> 941e

I solved this error with help of manual: https://kb.altinity.com/altinity-kb-setup-and-maintenance/x-rows-of-y-total-rows-in-filesystem-are-suspicious/

**Comment by alexey-milovidov** [comment]
We didn't notice these errors in the Stress Test in a year.

**Comment by alexey-milovidov** [comment]
@xsong123, your question is unrelated to this issue. See the documentation: https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/replication#recovery-after-failures
