### ISSUE TITLE
Package listing for macOS

### ISSUE THREAD

**Issue by melvynator** [ClickHouse/ClickHouse#37718]
**Use case**

Working with a specific version in a MacOS environment (especially for devs)

**Describe the solution you'd like**

Currently, we have a list for a lot of build packages for Linux distributions, it would be nice to do the same thing for MacOS. Something like: https://packages.clickhouse.com/tgz/stable/ but for macOS

**Describe alternatives you've considered**

If I want to find a specific macOS build I need to go to the specific release, find the last commit, search for the build history, find the S3 bucket and then play around with the URL. It's not the best experience.

**Comment by brodock** [comment]
The provided alternatives (to look at the pre-built binaries from release tags).

I've followed the instructions for: https://github.com/ClickHouse/ClickHouse/releases/tag/v22.5.1.2079-stable

which brings me to some builds like for example: https://github.com/ClickHouse/ClickHouse/runs/6493573871

when trying out binaries for different OS/architectures and testing reported versions:

```
clickhouse client --version
```

they don't match the expected `22.5.1.2079`

this is what I got so far: 

* MacOS with ARM64: https://s3.amazonaws.com/clickhouse-builds/37289/36b4ed19c54aeba59ff842499980c2d38ecda212/binary_darwin_aarch64/clickhouse
   - `ClickHouse client version 22.5.1.1.`
* MacOS with Intel: https://s3.amazonaws.com/clickhouse-builds/37289/36b4ed19c54aeba59ff842499980c2d38ecda212/binary_darwin/clickhouse
   - `ClickHouse client version 22.5.1.1.`
* Linux 64 binary: https://s3.amazonaws.com/clickhouse-builds/37289/36b4ed19c54aeba59ff842499980c2d38ecda212/binary_release/clickhouse
   - `ClickHouse client version 22.5.1.1.`
* Linux 64 binary performance (tgz): https://s3.amazonaws.com/clickhouse-builds/37289/36b4ed19c54aeba59ff842499980c2d38ecda212/performance/performance.tgz
   - `ClickHouse client version 22.5.1.1988.`
* Linux 64 binary (from packages tgz): https://packages.clickhouse.com/tgz/stable/clickhouse-common-static-22.5.1.2079-amd64.tgz
   - `ClickHouse client version 22.5.1.2079 (official build).`

**Comment by Felixoid** [comment]
Hello @brodock, I can answer regarding the version.

Version is generated automatically based on complete or shallow repository checkout, and we didn't think of macOS binaries being critical before, so they have a mock version generated, see https://github.com/ClickHouse/ClickHouse/runs/6493573871#step:6:463.

It's possible to have them with a proper version, though.

Another point, we didn't build them yet in release branches yet.

**Comment by brodock** [comment]
@Felixoid having MacOS binaries being built in the release branches would be very helpful for us, as I could them automate easier the install and update in our development kit

Is this more or less a matter of changing a few lines in the CI build ?

**Comment by filimonov** [comment]
Also https://github.com/Altinity/homebrew-clickhouse

**Comment by nikitamikhaylov** [comment]
Why not to use Docker images? Macs on M1 processor can run both x86 and AArch64 binaries and we have both of them available in Dockerhub.

**Comment by brodock** [comment]
@nikitamikhaylov I understand that docker works for some users, but part of our internal process is to provide binaries people can run internally and poke them as needed. It's much easier to run a tracing or hack some configuration when its not behind many layers of emulation. This is also allows us to run the software closer to how we package and ship it to our users.

our internal development kit can be found here: https://gitlab.com/gitlab-org/gitlab-development-kit

that's not to say we also don't support docker, we do, but in an alternate version: https://gitlab.com/gitlab-org/gitlab-compose-kit/

**Comment by Felixoid** [comment]
Hi @brodock, sorry I have been really blocked by our OSS packages distribution system for the last month.

It's not only a listing, it requires some more. You can see it in #41088.

After it will be merged and backported, I hope to see binaries in assets
