### ISSUE TITLE
Stress test: Part already exists, but it will be deleted soon

### ISSUE THREAD

**Issue by CurtizJ** [ClickHouse/ClickHouse#37722]
**Describe the bug**
Backward compatibility check:
https://s3.amazonaws.com/clickhouse-test-reports/37666/30f8eb800a9b2249462f2a72e07ddbae60ec876d/stress_test__undefined__actions_.html

```
2022.05.31 03:26:03.767267 [ 981816 ] {} <Error> void DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::routine(DB::TaskRuntimeDataPtr) [Queue = DB::MergeMutateRuntimeQueue]: Code: 384. DB::Exception: Part all_38_41_1 (state Outdated) already exists, but it will be deleted soon. (PART_IS_TEMPORARILY_LOCKED), Stack trace (when copying this message, always include the lines below):
```

As I understand this behaviour is ok. Probably we need to ignore this error in backward compatibility check.

**Comment by tavplubix** [comment]
> As I understand this behaviour is ok. Probably we need to ignore this error in backward compatibility check.

Yes, it's ok

cc: @Avogar
