### ISSUE TITLE
Exception: There is no physical column or subcolumn labels in table

### ISSUE THREAD

**Issue by srikanthccv** [ClickHouse/ClickHouse#37730]
Hello 👋 ,

I am trying to use the `MODIFY COLUMN` to change the type of column from `String` to `Object('json')` and it throws an exception while doing that. Any `SELECT` after that also fails with same exception.

```sh
Received exception from server (version 22.4.5):
Code: 341. DB::Exception: Received from localhost:9000. DB::Exception: Exception happened during execution of mutation 'mutation_2.txt' with part '20220512_1_1_0' reason: 'Code: 16. DB::Exception: There is no physical column or subcolumn labels in table: While executing MergeTreeInOrder. (NO_SUCH_COLUMN_IN_TABLE) (version 22.4.5.9 (official build))'. This error maybe retryable or not. In case of unretryable error, mutation can be killed with KILL MUTATION query. (UNFINISHED)
```

Here is the schema of already existing table
```sql
CREATE TABLE IF NOT EXISTS [table] (
			id UInt64 Codec(DoubleDelta, LZ4),
			labels String Codec(ZSTD(5))
		)
		ENGINE = ReplacingMergeTree
			ORDER BY id

```

And here is the mutation query which is throwing the exception

```
ALTER TABLE [table] MODIFY COLUMN labels JSON CODEC(ZSTD(5))
```

I was expecting ClickHouse converts the JSON encoded string type to JSON Object type introduced recently. Is this an expected exception? How do I modify the column type to `Object('json')`?

**Comment by Avogar** [comment]
@CurtizJ Can you look at it?

**Comment by filimonov** [comment]
Related https://github.com/ClickHouse/ClickHouse/issues/37205 and https://github.com/ClickHouse/ClickHouse/pull/37266

**Comment by iosifnicolae2** [comment]
Any news about this issue?

**Comment by glmdev** [comment]
Sorry to necropost an old issue, but we encountered this same issue on a table w/ an Object('json') column.

Not sure what the root cause was, but dropping the table and re-creating it resolved the issue for us. Also dropped our CPU utilization from ~95% to ~30%.

**Comment by Nonegrace** [comment]
Same here. Jsonextract doesn't fulfill our requirements. Is there any plan for this issue?
