### ISSUE TITLE
The upstream table queries the data incorrectly after the error data is inserted into materialized view

### ISSUE THREAD

**Issue by leegean** [ClickHouse/ClickHouse#37736]
I have the following lists：

```
-- test.kfk_user1 definition

CREATE TABLE test.kfk_user1
(

    `id` UInt64,

    `name` String
)
ENGINE = Kafka
SETTINGS kafka_broker_list = '192.168.6.165:9092',
 kafka_topic_list = 't_user1',
 kafka_group_name = 'g_user1',
 kafka_format = 'JSONEachRow';



-- test.view_user1 source

CREATE MATERIALIZED VIEW test.view_user1 TO test.user1
(

    `id` UInt64,

    `name` String
) AS
SELECT *
FROM test.kfk_user1;

-- test.user1 definition

CREATE TABLE test.user1
(

    `id` UInt64,

    `name` String
)
ENGINE = ReplacingMergeTree
ORDER BY id
SETTINGS index_granularity = 8192;

-- test.mv_user1 source

CREATE MATERIALIZED VIEW test.mv_user1
(

    `id` UInt64,

    `name` String
)
ENGINE = ReplacingMergeTree
ORDER BY id
SETTINGS index_granularity = 8192 AS
SELECT
    id,
    dictGetOrNull('jideos_data.agent_consumer_dict',
 'consumer_name',
 name) AS name
FROM test.user1;
```

When I send a message to the subject t_user1,like `{"id":11,"name":null}`.
The error log will print the following:
`2022.06.01 18:34:01.193923 [ 111252 ] {} <Error> void DB::StorageKafka::threadFunc(size_t): Code: 349. DB::Exception: Cannot convert NULL value to non-Nullable type: while converting source column name to destination column name: while executing 'FUNCTION _CAST(name :: 1, String :: 2) -> _CAST(name, String) String : 3': while pushing to view test.mv_user1: while pushing to view test.view_user1. (CANNOT_INSERT_NULL_IN_ORDINARY_COLUMN), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xaebed1a in /usr/bin/clickhouse
1. DB::FunctionCast<DB::CastInternalName>::prepareRemoveNullable(std::__1::shared_ptr<DB::IDataType const> const&, std::__1::shared_ptr<DB::IDataType const> const&, bool) const::'lambda0'(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> >&, std::__1::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long)::operator()(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> >&, std::__1::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long) const @ 0xd959640 in /usr/bin/clickhouse
2. COW<DB::IColumn>::immutable_ptr<DB::IColumn> std::__1::__function::__policy_invoker<COW<DB::IColumn>::immutable_ptr<DB::IColumn> (std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> >&, std::__1::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long)>::__call_impl<std::__1::__function::__default_alloc_func<DB::FunctionCast<DB::CastInternalName>::prepareRemoveNullable(std::__1::shared_ptr<DB::IDataType const> const&, std::__1::shared_ptr<DB::IDataType const> const&, bool) const::'lambda0'(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> >&, std::__1::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long), COW<DB::IColumn>::immutable_ptr<DB::IColumn> (std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> >&, std::__1::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long)> >(std::__1::__function::__policy_storage const*, std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> >&, std::__1::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long) @ 0xd9593ac in /usr/bin/clickhouse
3. DB::ExecutableFunctionCast::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0xd825774 in /usr/bin/clickhouse
4. DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x13feab3e in /usr/bin/clickhouse
5. DB::IExecutableFunction::executeWithoutSparseColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x13feb26d in /usr/bin/clickhouse
6. DB::IExecutableFunction::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x13fec26f in /usr/bin/clickhouse
7. DB::ExpressionActions::execute(DB::Block&, unsigned long&, bool) const @ 0x14759885 in /usr/bin/clickhouse
8. DB::ExpressionTransform::transform(DB::Chunk&) @ 0x15c0ae5c in /usr/bin/clickhouse
9. DB::ISimpleTransform::transform(DB::Chunk&, DB::Chunk&) @ 0x12017410 in /usr/bin/clickhouse
10. DB::ISimpleTransform::work() @ 0x15a3db27 in /usr/bin/clickhouse
11. DB::ExecutionThreadContext::executeTask() @ 0x15a60ca3 in /usr/bin/clickhouse
12. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x15a54b7e in /usr/bin/clickhouse
13. DB::PipelineExecutor::executeStep(std::__1::atomic<bool>*) @ 0x15a54280 in /usr/bin/clickhouse
14. DB::PullingPipelineExecutor::pull(DB::Chunk&) @ 0x15a6542c in /usr/bin/clickhouse
15. DB::ExecutingInnerQueryFromViewTransform::onGenerate() @ 0x15c7af7b in /usr/bin/clickhouse
16. ? @ 0x15c0a8b8 in /usr/bin/clickhouse
17. ? @ 0x15c0a4e9 in /usr/bin/clickhouse
18. DB::ExceptionKeepingTransform::work() @ 0x15c09fd2 in /usr/bin/clickhouse
19. DB::ExecutionThreadContext::executeTask() @ 0x15a60ca3 in /usr/bin/clickhouse
20. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x15a54b7e in /usr/bin/clickhouse
21. DB::PipelineExecutor::executeImpl(unsigned long) @ 0x15a53ddb in /usr/bin/clickhouse
22. DB::PipelineExecutor::execute(unsigned long) @ 0x15a53718 in /usr/bin/clickhouse
23. DB::CompletedPipelineExecutor::execute() @ 0x15a52244 in /usr/bin/clickhouse
24. DB::StorageKafka::streamToViews() @ 0x144f6a9a in /usr/bin/clickhouse
25. DB::StorageKafka::threadFunc(unsigned long) @ 0x144f49d8 in /usr/bin/clickhouse
26. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x14147f2e in /usr/bin/clickhouse
27. DB::BackgroundSchedulePool::threadFunction() @ 0x1414a8c7 in /usr/bin/clickhouse
28. ? @ 0x1414b8f0 in /usr/bin/clickhouse
29. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xaf62837 in /usr/bin/clickhouse
30. ? @ 0xaf662fd in /usr/bin/clickhouse
31. ? @ 0x7fe8277fd609 in ?
 (version 22.2.2.1)
`

This error is normal, but when I query test.user1, the result is inconclusive, like this：
![image](https://user-images.githubusercontent.com/9957334/171385718-da923613-55c1-440d-ab1c-fdf4f7710767.png)
or like this:
![image](https://user-images.githubusercontent.com/9957334/171385765-2dda6a2e-affc-44b5-b262-a09007a07def.png)
![image](https://user-images.githubusercontent.com/9957334/171386036-42d7be6f-456f-4e10-867f-90df5afcc293.png)

When I deleted test.mv_user1, the error log stopped printing, but the data in the test_user1 table was still wrong.

**Comment by den-crane** [comment]
And what is wrong here? 
You need to provide reproducible example. 
I don't see how you insert `kubi`. 
What is `jideos_data.agent_consumer_dict` ?

MaterializedView is an insert trigger. https://den-crane.github.io/Everything_you_should_know_about_materialized_views_commented.pdf

**Comment by leegean** [comment]
> What is `jideos_data.agent_consumer_dict` ?
'jideos_data.agent_consumer_dict' is a dictionary.

> You need to provide reproducible example.
Only the dictionary 'jideos_data.agent_consumer_dict' has data, but does not include records where the key is 'kubi1'.

> I don't see how you insert `kubi`.
I insert the data using the Kafka script tool kafka-console-producer.sh

> And what is wrong here?
When I use the Kafka script to send a message to the Kafka engine table test.kfk_user1, for example:{"id":11,"name":"kubi1"}, materialized view test.mv_user1 will save the value of the key 'kubi1' obtained from dictGetOrNull, but an error will be reported because the keyword 'kubi1' does not exist in the dictionary table.

When I insert only one record with ID 11 into 'test.user1', I expect only one record with ID 11, but in fact 'test.user1' has multiple queries due to problems with materialized view 'test.mv_user1'
