### ISSUE TITLE
Default value of max_threads

### ISSUE THREAD

**Issue by HeenaBansal2009** [ClickHouse/ClickHouse#37752]
**Describe the issue**
In clickhouse it is mentioned, max_threads default value is equal to number of physical cores which is actually by 2 of available number of cpu cores.
 
Reference :https://clickhouse.com/docs/en/operations/settings/settings/#settings-max_threads

**Additional context**
The code relevant to the ^ context:
https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/getNumberOfPhysicalCPUCores.cpp#L51

**Comment by HeenaBansal2009** [comment]
the default value information needs to be fixed in codebase as well like settings.h.

**Comment by DanRoscigno** [comment]
The code has been updated to use `/proc/cpuinfo`, and I believe that it is now reporting the number of cores properly.
```
    /// The CPUID instruction isn't reliable across different vendors and CPU models. The best option to get the physical core count is
    /// to parse /proc/cpuinfo. boost::thread::physical_concurrency() does the same, so use their implementation.
    ///
    /// See https://doc.callmematthi.eu/static/webArticles/Understanding%20Linux%20_proc_cpuinfo.pdf
    std::ifstream proc_cpuinfo("/proc/cpuinfo");
```
