### ISSUE TITLE
Some questions about local cache implementation

### ISSUE THREAD

**Issue by KinderRiven** [ClickHouse/ClickHouse#37758]
Hello @kssenii , because my recent work is related to local cache, I have some questions to ask. I took a look at the [PR ](https://github.com/ClickHouse/ClickHouse/pull/36171) that you haven't submitted recently , and there are some implementations that I'm more concerned about.
In the new implementation, it seems to set up a new disk of type `cache`, which contains a disk to be cached. This implementation seems a little counter-intuitive, as it implies a one-to-one correspondence between cache and disk. In this implementation, the disk is more like part of cache as follows:

```
<disks>
  <disk_1>
       <type>s3</type>
       ...
  </disk_1>
  <cache_disk>
      <type>cache</type>
      <disk>disk_1</disk>
      ...
  </cache_disk>
</disks>

```
In this case, why not configure cache as an option of disk as follows:

```
<cache>
   <cache_1>...</cache_1>
</cache>
<disks>
  <disk_1>
    <type>s3</type>
    <cache>cache_1</cache>
    ...
  </disk_1>
  <disk_2>
    <type>s3</type>
    <cache>cache_1</cache>
    ...
  </disk_2>
</disks>
```

This approach can specify the same cache instance for multiple disks during configuration, and can also enable or disable the cache of a disk according to whether the cache option is set (instead of directly configuring a disk type). In addition, it may be easier to implement multi-level cache in the future as follows (although this feature is not currently available):

```
<cache>
   <cache_1>...</cache_1>
  <cache_2>...</cache_2>
</cache>
<disks>
  <disk_1>
    <type>s3</type>
    <cache>
            <L0>cache_1</L0>
            <L1>cache_2</L2>
    </cache>
    ...
  </disk_1>
</disks>
```

The above are just my questions. Your current implementation must have your consideration. I would like to know the reason for the current implementation. I would be very grateful if you could answer my doubts. :)

**Comment by kssenii** [comment]
Hello!

> I would like to know the reason for the current implementation.

This new implementation of "composable cache" was intended to allow cache to be applied to any disk type (Local, Encrypted, StaticWeb, etc) without any need to write additional code for this support and to make cache layer as an independent layer.
Even though it is not really needed to have cache for non-remote storage, it is useful for testing.

Though I do agree that the way you propose on the second configuration example is good: it is compact and convenient to use. With new "composable" implementation it will be not be as convenient to define the same cache configuration for multiple remote storages as it will require to write all cache layers separately even though they are the same. I will think about what should we do with it and write back.

**Comment by UnamedRus** [comment]
> Even though it is not really needed to have cache for non-remote storage, it is useful for testing.

It actually make sense for NAS attached storage / slow HDD disks / SAN disks / EBS disks.

With cache, ClickHouse can put most common used columns/projections to the fast local disk.

**Comment by UnamedRus** [comment]
Another syntax idea:

```
<clickhouse>
    <storage_configuration>
        <policies>
            <s3_tiered>
                <volumes>
                    <local>
                        <disk>default<disk>
                    </local>
                    <main>
                        <disk>s3</disk>
                        <cache>local</cache>
                    </main>
                </volumes>
            </s3_tiered>
        </policies>
   </storage_configuration>
</clickhouse>
```

**Comment by alexey-milovidov** [comment]
@KinderRiven I would like to make a low-level but fully orthogonal and composable variant first.
When a cached disk is a disk that is configured on top of any other disk.

It makes sense - you can define cached disk on top of encrypted disk on top of web disk. Or encrypted disk on top of cached disk on top of s3 disk. Also, imagine cache on top of AWS's `efs`. Or SSD cache on top of HDDs.

We use this principle everywhere. For example, we already use it for encrypted disks.
We specify it as: an encrypted disk on top of any other disk. Not as "local disk, encrypted = 1".

The same inside other areas in the code. We use CompressedReadBuffer on top of another ReadBuffer, not "AnotherReadBuffer(bool compressed = 1)".

But then we can also implement your configuration variant as a facade for our low-level variant.

**Comment by alexey-milovidov** [comment]
> I would like to make a low-level but fully orthogonal and composable variant first.

Done.

**Comment by amit-cashify** [comment]
> It makes sense - you can define cached disk on top of encrypted disk on top of web disk. Or encrypted disk on top of cached disk on top of s3 disk. Also, imagine cache on top of AWS's `efs`. Or SSD cache on top of HDDs. You can even define a cache on top of another cache for several caching layers.

@alexey-milovidov 

I am interested to use this functionality. I am using a Clickhouse OSS installation on EC2 r6g/r7g with EBS gp3 volume to store all data. I want to use the instance local SSD on EC2 r6gd/r7gd as a cache layer between EBS and the EC2 instance, so that often used parts are available on the local SSD. Is there a straightforward way to set this up. I was unable to locate the relevant docs for setting this up.
