### ISSUE TITLE
【alter_lock related】Is there any way to find which operation is holding the alter_lock in Storage?

### ISSUE THREAD

**Issue by mo-avatar** [ClickHouse/ClickHouse#37768]
【alter_lock related】Is there any way to find which operation is holding the alter_lock in Storage?
we are encounter a problem of RW write  lock timeout now in 20.8 lts(we are going to upgrade it now).
After reading the code I find the alter operation and the  drop,truncate and rename the table  operation will acquire the alter_lock too.
So if this operations are in processing, the lock will definitely can't be acquired by other request.
besides filter the related operation in system.query_log  or mutation table, is there any way we can find the  operation which holding alter_lock  precisely any quickly?
Thanks

**Comment by genzgd** [comment]
Unfortunately there isn't any logging when the alter_lock is set.  However, in the version of ClickHouse you are using that lock is held longer than necessary and in some circumstances (in particular, unavailable replicas) where it is unnecessary.  Upgrading to version 22.3 LTS or later will fix almost all issues where that lock times out, as it is held for a much shorter time and only when truly required.

**Comment by mo-avatar** [comment]
Thanks for your answer!
