### ISSUE TITLE
cast to date-time, specify format

### ISSUE THREAD

**Issue by sbhkmndl** [ClickHouse/ClickHouse#37782]
Is there any function that can cast a column to a date-time column, where I can specify its format manually?

**Comment by den-crane** [comment]
Try to use `parseDateTimeBestEffortUS`

**Comment by sbhkmndl** [comment]
In my case the data is dynamic, it can contain any format. For different formats, I have to use different functions, where I know the date-time format.

**Comment by den-crane** [comment]
> In my case the data is dynamic, it can contain any format. For different formats, I have to use different functions, where I know the date-time format.

Yes, there is no such feature in CH yet. You have to normalize/transform input data before the loading into Clickhouse.
