### ISSUE TITLE
clickhouse-zk-client: CLI application for accessing zookeeper

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#37780]
Alternative for [zkCli](https://zookeeper.apache.org/doc/r3.6.0/zookeeperCLI.html) / [zk-shell](https://pypi.org/project/zk-shell/ ) / [zookeepercli](https://github.com/openark/zookeepercli) / [zkcli](https://github.com/go-zkcli/zkcli) ect

Pros:
1) no need to install extra tools on clickhouse servers to check zookeeper data
2) can be better than zkCli (it has a lot of silly limitations)
3) is easy to do - a lot of code from clickhouse-client / clickhouse-local (including REPL loop) can be reused.

**Comment by xiedeyantu** [comment]
Has anyone started to do it？

**Comment by filimonov** [comment]
Not yet

**Comment by filimonov** [comment]
Closing in favor to #46229
