### ISSUE TITLE
ALTER TABLE table_name MOVE PARTITION/PART and S3 volume

### ISSUE THREAD

**Issue by rustwizard** [ClickHouse/ClickHouse#37781]
Hi! I have 2 replicas in the shard with such storage configuration: first volume is JBOD of local disks and second volume is s3 disk.
On first replica moving data to the s3 volume works like a charm, but on a second I've always get an error: 
`
Cannot move part '202203_2_2_0_2382546' because it's participating in background process. (PART_IS_TEMPORARILY_LOCKED)`

How can I debug such errors? In what processes that part is participating in? There is no info about it in` system.parts`, neither in `replication_queue` and so on.

Thanks in advance.

**Comment by genzgd** [comment]
What version of ClickHouse are you using? 

You should also check `system.merges` and `system.mutations` for the affected part.  Since this is a replicated table you should also check the zookeeper queue.

Does this happen on all tables?  Does it happen on multiple replicas?

**Comment by rustwizard** [comment]
>What version of ClickHouse are you using?
22.5.1.2079
>You should also check system.merges and system.mutations for the affected part. Since this is a replicated table you should also check the zookeeper queue.

There is no such partition name in the tables (`system.merges` and `system.mutations`) with  PART_IS_TEMPORARILY_LOCKED error. Also there is no nodes with that parts in ZK. I've check it in ` /clickhouse/tables/shard_01/table_name/replicas/replica_name1/queue` and ` /clickhouse/tables/shard_01/table_name/replicas/replica_name2/queue`

>Does this happen on all tables?
No, only with one big replicated table.

>Does it happen on multiple replicas?
No, moving parts to s3-storage in first replica  works like a charm. I've tried syncing from first replica, it was successful, then I've tried to move some parts and it worked at the first glance but then moving procces stuck with PART_IS_TEMPORARILY_LOCKED error

At local disk mapping for S3 disk I see many folders with /moving names, tell me. please, is CH using such folders to indicates parts that participating in moves to s3-disk?
Can I delete such folders and start moving data to S3 from scratch?

**Comment by genzgd** [comment]
Is it only that single part or do you get the error with different part names?  Have you tried restarting ClickHouse on the replica where the error occurs?  Do you have any TTL based merges on that table?

**Comment by rustwizard** [comment]
>Is it only that single part or do you get the error with different part names?
Not only that single part raise an error. With parts that don't raise an error(PART_IS_TEMPORARILY_LOCKED) I've getting read timeout error, but I can see my `alter move`  queries in the output of `show processlist` in that case. But nothing is happens also. No moves at all. 

> Do you have any TTL based delete or moves on that table?
No, there is no TTL's on the table.

**Comment by maxuewen** [comment]
I‘m get same error then move data to HDFS disk and the replicas have different endpoints.
You can try to modify the endpoints of multiple replicas to be the same.

**Comment by tbragin** [comment]
Looks like the question was answered, closing.
