### ISSUE TITLE
Functions to estimate Bloom FIlter size

### ISSUE THREAD

**Issue by vdimir** [ClickHouse/ClickHouse#37799]
For configuring the parameters of `ngrambf_v1` we need to estimate the number of ngrams in the granule and perform some calculations.

It's good to add some bloom filter-related functions into ClickHouse.

These functions are just arithmetic expressions, so it should be possible to calculate them now, but it may be easier with some aliases.
It shouldn't be implemented with lots of new code. Even we can add some examples into the docs on how to create it using `CREATE FUNCTION bloomFilterEstimate AS (...) -> expression`

https://hur.st/bloomfilter/

**Comment by lingtaolf** [comment]
Let me have a try.

**Comment by vdimir** [comment]
@lingtaolf you are welcome, let us know if you have any questions

**Comment by lingtaolf** [comment]
This all seems like simple math, and it feels like there's no need to change the code. So I plan to change the documentation to add some custom function creation SQL. Is that ok ?
@vdimir

**Comment by vdimir** [comment]
> So I plan to change the documentation to add some custom function creation SQL

Yes, sounds good. Maybe somewhere around `ngrambf_v1` index doc.

https://github.com/ClickHouse/ClickHouse/blob/5a72125ab74195216fdd624ec61448e758141402/docs/en/engines/table-engines/mergetree-family/mergetree.md?plain=1#L425-L440

BTW, `bloom_filter` already accepts `false_positive` rate as an argument.

It's calculated in `calculationBestPractices`

https://github.com/ClickHouse/ClickHouse/blob/5a72125ab74195216fdd624ec61448e758141402/src/Storages/MergeTree/MergeTreeIndexBloomFilter.cpp#L108

https://github.com/ClickHouse/ClickHouse/blob/5a72125ab74195216fdd624ec61448e758141402/src/Interpreters/BloomFilterHash.h#L246
