### ISSUE TITLE
Optimize predicate expression with ASOF JOINs leads to incorrect results

### ISSUE THREAD

**Issue by roncohen** [ClickHouse/ClickHouse#37813]
**Describe what's wrong**

`--enable_optimize_predicate_expression=1` is on by default ([since](https://github.com/ClickHouse/ClickHouse/commit/118bea2be6a7a2f0720adcc3f67c559d8c49bd71) v19.6.2.11-stable?) but the optimization can break ASOF JOINS and result in incorrect results.

**Does it reproduce on recent release?**

Reproduced in 22.6.1.231 and 21.12.1.8928 

**How to reproduce**

**bug.sql:**
```sql
DROP TABLE IF EXISTS t1;
CREATE TABLE t1 (c1 Int32, c2 Int32) Engine=MergeTree ORDER BY c1;
INSERT INTO t1 (c1, c2) VALUES (1, 10), (1, 20), (1, 30); 

DROP TABLE IF EXISTS t2;
CREATE TABLE t2 (c1 Int32, c2 Int32, c3 String) Engine=MergeTree ORDER BY (c1, c2, c3);
INSERT INTO t2 (c1, c2, c3) VALUES (1, 5, 'a'), (1, 15, 'b'), (1, 25, 'c'); 

WITH 
  v1 AS (SELECT t1.c2, t2.c2, t2.c3 FROM t1 ASOF JOIN t2 USING (c1, c2))
  SELECT * FROM v1 WHERE c3 = 'b';
```

**Expected behavior**

The results should not change when enabling/disabling `enable_optimize_predicate_expression`:
```
❯ cat bug.sql | clickhouse client -n --enable_optimize_predicate_expression=0
20      15      b

❯ cat bug.sql | clickhouse client -n --enable_optimize_predicate_expression=1
20      15      b
30      15      b
```

**Comment by vdimir** [comment]
Thank you for a good reproducible example! It seems that we cant push down the expression for `ASOF` join so we will disable it. And `ANY JOIN` has the same peculiarity, but for `ANY` it's okay because it doesn't have guarantees which row should be chosen (unlike ASOF, where we have to pick the closest one).
