### ISSUE TITLE
"SELECT 9223372036854775807 * 9223372036854775807" returns 1

### ISSUE THREAD

**Issue by liyinsg** [ClickHouse/ClickHouse#37816]
Expected behavior is either give the correct answer or throw exception.

**Comment by tavplubix** [comment]
It's expected, see https://clickhouse.com/docs/en/sql-reference/ansi/#differences-in-behaviour
```
ClickHouse overflows instead of checked arithmetic and changes the result data type based on custom rules
```

And https://clickhouse.com/docs/en/sql-reference/functions/arithmetic-functions/
```
Overflow is produced the same way as in C++.
```
