### ISSUE TITLE
stddev* and var* family of function cannot be applied to Decimal* types

### ISSUE THREAD

**Issue by marcioapm** [ClickHouse/ClickHouse#37821]
**Describe the unexpected behaviour**
`stddev*` family of function cannot be applied to Decimal*

**How to reproduce**
* Which ClickHouse server version to use
22.3.5.6

* Queries to run that lead to unexpected result
`SELECT 1::Decimal128(6) count, stddevPopStable(count);`

Result:
`Illegal type Decimal(38, 6) of argument for aggregate function varPopStable. (ILLEGAL_TYPE_OF_ARGUMENT)`

**Expected behavior**
The function should be applicable to all numeric data types.

**Comment by alexey-milovidov** [comment]
-Stable functions make sense only for floating-point arguments, as they are using a numerically stable algorithm (resembling Kahan summation). It does not make sense for fixed-point data types.

Solution: use `stddevPop` instead of `stddevPopStable`.
