### ISSUE TITLE
OOM in query with `if` and large `FixedString`

### ISSUE THREAD

**Issue by CurtizJ** [ClickHouse/ClickHouse#37831]
**How to reproduce**
`clickhouse benchmark -c16 <<< "SELECT if(number % 2 = 0, toFixedString(toString(number), 100000), '') FROM numbers(100000) format Null"`

**Comment by alexey-milovidov** [comment]
@CurtizJ Most likely OOM happens only in presence of other applications.
I checked, and the memory limits work fine in this case:

```
clickhouse benchmark --max_memory_usage_for_user '40G' -c16 <<< "SELECT if(number % 2 = 0, toFixedString(toString(number), 100000), '') FROM numbers(100000) format Null"
```

\- server does not consume more than 40 GB
