### ISSUE TITLE
Which row will leave if rows with the same sorting key have the same 'ver' column specified in ReplacingMergeTree?

### ISSUE THREAD

**Issue by libinyl** [ClickHouse/ClickHouse#37858]
The doc says,

```
When merging, ReplacingMergeTree from all the rows with the same sorting key leaves only one:

- The last in the selection, if ver not set. A selection is a set of rows in a set of parts participating in the merge. The most recently created part (the last insert) will be the last one in the selection. Thus, after deduplication, the very last row from the most recent insert will remain for each unique sorting key.

- With the maximum version, if ver specified.
```

But which row will survive if there are other rows with the same sorting key **and** the same 'ver' column, with 'ver' specified?  Will clickhouse then choose the last in the selection? I can't find the description in the documentation. Is there any guarantee? Thanks!

**Comment by filimonov** [comment]
No strict guarantees then. It will pick ONE of the rows with a maximum version.

https://github.com/ClickHouse/ClickHouse/blob/bd89fcafdbc44b4b41f1c7458af5eeedec062774/src/Processors/Merges/Algorithms/ReplacingSortedAlgorithm.cpp#L77

**Comment by nickitat** [comment]
we will pick the last one row (as comment above this if stands). and since we read data from MT in order, it will be the last inserted row.

**Comment by libinyl** [comment]
got it, thanks!
