### ISSUE TITLE
CollapsingMergeTree: warning after insert two same keys record

### ISSUE THREAD

**Issue by taotaizhu-pw** [ClickHouse/ClickHouse#37857]
Our project used RelicatedCollapsingMergeTree to update and delete data.  We insert a new row record has the same keys to update an old row record. After execute "optimize table xxx final", a warning message was prompted:  "<Warning> CollapsingSortedTransform: Incorrect data: number of rows with sign = 1 (2) differs with number of rows with sign = -1 (0) by more than one (for key: 'AAA').).".  The max numbers of prompt messages is 10, whatever how many duplicated records. Can we ignore these warning message? 

Old Record in DB:  AAA, 2022-01-01, 1
New Record: AAA,2022-01-02,1

Waring: CollapsingSortedTransform: Incorrect data: number of rows with sign = 1 (2) differs with number of rows with sign = -1 (0) by more than one (for key: 'AAA').).".

I knew the best method is insert sign=-1 record first, then insert the new record.  My question is can we insert the new record directly, and ignore the waring, it there any problem? 

Could you give us some suggestion？ Thanks! 

ClickHouse Version: 22.3.6.5

**Comment by tom-clickhouse** [comment]
When this is your old/current row: 
`AAA, 2022-01-01, 1`

Then you can overwrite that row by using two rows: 
1. `AAA, 2022-01-01, -1`
2. `AAA, 2022-01-02, 1`

The first row is required for canceling the previous state of the row and the second row is the new state - see the [second case of the collapsing algorithm](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/collapsingmergetree/#table_engine-collapsingmergetree-collapsing-algorithm).

Your warning messages are indicating that no entries are collapsed - see the [fourth case of the collapsing algorithm](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/collapsingmergetree/#table_engine-collapsingmergetree-collapsing-algorithm)
