### ISSUE TITLE
Better management of DateTime partitionning

### ISSUE THREAD

**Issue by edonin** [ClickHouse/ClickHouse#3786]
Hi,

 Currently, when you create a mergeTree with a Date column inside your sorting index, in the system.parts table, you have access to the min_date and max_date of all of your partitions.

Nevertheless, if you do a MergeTree with based on a DateTime column (timestamp), the two columns are not filled. 

So, is it acceptable to add two columns in the system.parts table called min_time and max_time containing the min DateTime and the max DateTime of the DateTime column of your sorting index ? These two columns will be filled only if the sorting column is based on one and only one Datetime, and if there is no Date in the sorting index.

It will allow me: 
- to know the latest and the oldest timestamp of every table in a very fast query
- to have a partition purging mechanism that will drop a partition once all of its data have reach the table lifetime in an efficient way.

I started to work on a small prototype, but I prefer to ask before submitting a pull request.

Thanks,

**Comment by alexey-milovidov** [comment]
Yes, it is acceptable.

**Comment by alexey-milovidov** [comment]
Both min/max date and min/max time columns look like collection of special cases. Not good in general.
But as we also have min/max date, adding min/max time looks perfectly reasonable.

I appreciate if you will add this enhancement!
