### ISSUE TITLE
Merge tasks exceeded background_pool_size.

### ISSUE THREAD

**Issue by 7hong** [ClickHouse/ClickHouse#37861]
VERSION_DESCRIBE: v21.11.10.1-stable

Merge tasks exceeded background_pool_size. Why? How should I control the Merge task to avoid occupying too many disks?
<img width="881" alt="image" src="https://user-images.githubusercontent.com/24261938/172044085-33260aae-a9d5-4964-ad63-79f49cc760f8.png">

**Comment by filimonov** [comment]
New behavior in 21.11 

Check details in https://github.com/ClickHouse/ClickHouse/pull/29140 and in  https://github.com/ClickHouse/ClickHouse/issues/22381

If you don't like that you can adjust background_merges_mutations_concurrency_ratio
