### ISSUE TITLE
To run ClickHouse on processors that do not support SSE 4.2

### ISSUE THREAD

**Issue by cw1322311203** [ClickHouse/ClickHouse#37875]
To run ClickHouse on processors that do not support SSE 4.2，how should I build ClickHouse from source code with proper configuration adjustments.The official website does not introduce the detailed operation

**Comment by seaner90** [comment]
if you mean arm64 cpus, then

```bash
cmake . -Bbuild-arm64 -DUSE_STATIC_LIBRARIES=0 -DSPLIT_SHARED_LIBRARIES=1 -DCLICKHOUSE_SPLIT_BINARY=1
ninja -C build-arm64 clickhouse
```

**Comment by filimonov** [comment]
> To run ClickHouse on processors that do not support SSE 4.2

Check first if your platform does not have precompiled binaries: https://clickhouse.com/docs/en/getting-started/install

> how should I build ClickHouse from source code

We support officially only a limited number of platforms.
If you need to build clickhouse on some non-platform that is not officially supported - most probably you will need to understand cmake, be able to read some sources, and maybe do some changes in CMake scripts / c++ sources.

See
https://clickhouse.com/docs/en/development/cmake-in-clickhouse and especially [ENABLE_SSE42](https://github.com/clickhouse/clickhouse/blob/master/cmake/cpu_features.cmake#L16) 

> The official website does not introduce the detailed operation

See https://clickhouse.com/docs/en/development/

ClickHouse is an open-source project (also the documentation is open source). 
You can improve that by sending the PR.
