### ISSUE TITLE
Add an ability to pass headers to url table function

### ISSUE THREAD

**Issue by j0tunn** [ClickHouse/ClickHouse#37897]
**Use case**
To be able to retrieve data from the external source during the request in most cases it is necessary to pass `Authorization` header.

**Describe the solution you'd like**

It would be nice to pass headers to the [url](https://clickhouse.com/docs/en/sql-reference/table-functions/url) table function as a parameter. Example:
```sql
SELECT * FROM url('http://127.0.0.1:12345/', CSV, 'column1 String, column2 UInt32', ['Authorization: <token>']) LIMIT 3;
```
It can be also some source constructor of the first parameter like [Http(s) source](https://clickhouse.com/docs/en/sql-reference/dictionaries/external-dictionaries/external-dicts-dict-sources#https):
```sql
SELECT * FROM url(
   HTTP(
        url 'http://127.0.0.1:12345/',
        headers(header(name 'Authorization' value '<token>'))
    ),
    CSV,
    'column1 String, column2 UInt32'
)
LIMIT 3;
```

**Comment by kssenii** [comment]
it is possible with `named_collections` https://clickhouse.com/docs/en/operations/named-collections/
https://github.com/ClickHouse/ClickHouse/blob/edc6b6880192e1956d95ea0b27878b874bc40626/tests/config/config.d/named_collection.xml#L17-L23

**Comment by j0tunn** [comment]
Yes. But it requires to have an access to config. This issue is about ability to pass headers directly from the query

**Comment by UnamedRus** [comment]
You can pass headers in external dictionary definition.

**Comment by j0tunn** [comment]
> You can pass headers in external dictionary definition.
Yes, but this needs write access. I should create external dictionary first. And I need it with only read access

**Comment by kssenii** [comment]
example:
```
select * from url('http://127.0.0.1:8123?query=select+12', 'RawBLOB', headers('X-ClickHouse-Format'='JSONEachRow', 'X-ClickHouse-Database'='db'));
```

**Comment by j0tunn** [comment]
Thanks! When this feature will be released?

**Comment by kssenii** [comment]
On the next release, releases are made once a month, usually in the middle of each month.

**Comment by j0tunn** [comment]
@kssenii 
I'm trying to get token from table, and pass it to the url function
```
WITH (
    SELECT value FROM secrets WHERE key == 'OAuth'
) as token
SELECT * FROM url('https://some-host', 'CSVWithNames', headers('Authorization'='OAuth ' + token))
```
But getting an error:
```
DB::Exception: Missing columns: 'token' while processing query: ''OAuth ' + token', required columns: 'token' 'token'. (UNKNOWN_IDENTIFIER) (version 22.7.4.16 (official build))
```

Can you explain why this happens? And what should I do to avoid the error? Thanks

**Comment by kssenii** [comment]
because the value of header (in your case `'OAuth ' + token`) is interpreted as a single `Identifier` and the string contention is not performed. Try concatenating in advance and then putting the result into header value.

**Comment by j0tunn** [comment]
@kssenii 

> because the value of header (in your case 'OAuth ' + token) is interpreted as a single Identifier and the string contention is not performed. Try concatenating in advance and then putting the result into header value.

This time I have no error about missing columns. But it still doesn't work.
In case
```
WITH 'OAuth <token>' as fooBar
SELECT * FROM url('https://some-host', 'CSVWithNames', headers('Authorization'=fooBar))
```
it just passes 'fooBar' as a value in 'Authorization' header

**Comment by kssenii** [comment]
Indeed, because aliases are not substituted for table function arguments

**Comment by j0tunn** [comment]
> Indeed, because aliases are not substituted for table function arguments

Sounds like a big problem. It makes this feature less useful.
Any chances this fill be fixed in near future?

**Comment by kssenii** [comment]
don't know, please create a separate issue for that

**Comment by j0tunn** [comment]
> don't know, please create a separate issue for that

I've found this issue: https://github.com/ClickHouse/ClickHouse/issues/33051
