### ISSUE TITLE
Regression:  ClickHouse 22.5.1.2079 can't INSERT Protobuf

### ISSUE THREAD

**Issue by knoguchi** [ClickHouse/ClickHouse#37895]
**Describe what's wrong**
The Protobuf example from the document that INSERT Protobuf messages failed with 22.5.1.2079.
https://clickhouse.com/docs/en/interfaces/formats/#protobuf

**Does it reproduce on recent release?**
22.5.1.2079 failed. 
Last working version that I know is 22.3.6.5-LTS.

**Crash reporting**

It doesn't crash.  No error logs generated.

**How to reproduce**
Create /var/lib/clickhouse/format_schemas/schemafile.proto, file mode 0644, owned by clickhouse:clickhouse.  Restart ClickHouse server.
```
syntax = "proto3";

message MessageType {
  string name = 1;
  string surname = 2;
  uint32 birthDate = 3;
  repeated string phoneNumbers = 4;
};
```

Create this file as create.sql
```
CREATE DATABASE IF NOT EXISTS test;
CREATE TABLE IF NOT EXISTS test.table (
       name String,
       surname String,
       birthDate UInt32,
       phoneNumbers Array(String)
) ENGINE=Memory;


INSERT INTO test.table VALUES ('kenji', 'noguchi', 11112233, ['555-555-5555']), ('michael', 'jackson', 44445566, ['666-666-6666']);
SELECT * FROM test.table FORMAT Protobuf SETTINGS format_schema = 'schemafile:MessageType';
```
and run like this.  Please note SELECT successfully created delimited Protobuf messages..
```
clickhouse-client -n < create.sql > protobuf_messages.bin
```
Then INSERT the generated messages
```
cat protobuf_messages.bin | clickhouse-client --query "INSERT INTO test.table FORMAT Protobuf SETTINGS format_schema='schemafile:MessageType'"
```

**Error message and/or stacktrace**
```
Code: 36. DB::Exception: The format Protobuf requires a schema. The corresponding setting should be set: data for INSERT was parsed from query: (in query: INSERT INTO test.table FORMAT Protobuf SETTINGS format_schema='schemafile:MessageType'). (BAD_ARGUMENTS)
```

**Comment by Avogar** [comment]
Your INSERT query is incorrect. We don't allow settings after format name because we expect data after it. The next INSERT query will work:
```sql
INSERT INTO test.table SETTINGS format_schema='schemafile:MessageType' FORMAT Protobuf
```

**Comment by Avogar** [comment]
See https://github.com/ClickHouse/ClickHouse/pull/35883

**Comment by knoguchi** [comment]
Also the parser should raise syntax error instead of "The format Protobuf requires a schema."

**Comment by Avogar** [comment]
> Also the parser should raise syntax error instead of "The format Protobuf requires a schema."

It's not possible, we treat all data after `FORMAT <format_name>` as data in corresponding format. We support inserting data both from stdin and from query at the same time. Like:
```sql
cat data | clickhouse-client -q "INSERT INTO <table> FORMAT <format> <some data>"
```
