### ISSUE TITLE
Batch insert data use sql "insert into table values (),()" appear data column lose  

### ISSUE THREAD

**Issue by MatrixCheng** [ClickHouse/ClickHouse#37896]
**version**
21.12.2.17
**How to reproduce**

> CREATE  TABLE if not exists test_src_soc_log (
    log_type_id         UInt8,
    src_ip              Nullable(IPv4),
    dst_ip              Nullable(IPv4),
    received_date       Date
    ) ENGINE = MergeTree
    PARTITION BY toMonday(received_date)
    ORDER BY (log_type_id);

> insert into test_src_soc_log values ('1','192.168.6.100','1.1.1.1','2022-06-02'),('1','1.1.1.2','','2022-06-02'),('1','192.168.6.100','1.1.1.1','2022-06-02'),('1','1.1.1.2','','2022-06-02');

> select * from test_src_soc_log;

the result is :
┌─log_type_id─┬─src_ip────┬─dst_ip─┬─received_date─┐
│                     1 │ 192.168.6.100 │ 1.1.1.1  │    2022-06-02     │
│                     1 │ 1.1.1.2             │ ᴺᵁᴸᴸ       │    2022-06-02     │
│                     1 │ 192.168.6.100 │ ᴺᵁᴸᴸ       │    2022-06-02     │
│                     1 │ 1.1.1.2             │ ᴺᵁᴸᴸ       │    2022-06-02     │
└─────────┴─────────┴─────┴───────────┘
the third data dst_ip lose

**Comment by e-mars** [comment]
hi @MatrixCheng .

In newer versions, tested with 22.5, using `''` for `null` will now cause an error:
```
clickhouse :)  insert into test_src_soc_log
               values
               ('1','192.168.6.100','1.1.1.1','2022-06-02'),
               ('1','1.1.1.2','','2022-06-02'),
               ('1','192.168.6.100','1.1.1.1','2022-06-02'),
               ('1','1.1.1.2','','2022-06-02');

INSERT INTO test_src_soc_log FORMAT Values

Query id: 864a29a2-12ef-4d25-aec0-432d80730cf9

Ok.
Exception on client:
Code: 441. DB::Exception: Invalid IPv4 value: while executing 'FUNCTION _CAST(_dummy_0 : 0, 'Nullable(IPv4)' :: 1) -> _CAST(_dummy_0, 'Nullable(IPv4)') Nullable(IPv4) : 2': While executing ValuesBlockInputFormat: data for INSERT was parsed from query. (CANNOT_PARSE_DOMAIN_VALUE_FROM_STRING)
```
Could you try using a `NULL` instead of empty string?
```
clickhouse :)  insert into test_src_soc_log
               values
               ('1','192.168.6.100','1.1.1.1','2022-06-02'),
               ('1','1.1.1.2',NULL,'2022-06-02'),
               ('1','192.168.6.100','1.1.1.1','2022-06-02'),
               ('1','1.1.1.2',NULL,'2022-06-02');

INSERT INTO test_src_soc_log FORMAT Values

Query id: 98c1349a-1767-4d30-a797-991068cce5b6

Ok.

4 rows in set. Elapsed: 0.007 sec.

clickhouse :) select * from test_src_soc_log;

SELECT *
FROM test_src_soc_log

Query id: eaa0d4eb-3953-412a-9063-ae87c53828e3

┌─log_type_id─┬─src_ip────────┬─dst_ip──┬─received_date─┐
│           1 │ 192.168.6.100 │ 1.1.1.1 │    2022-06-02 │
│           1 │ 1.1.1.2       │ ᴺᵁᴸᴸ    │    2022-06-02 │
│           1 │ 192.168.6.100 │ 1.1.1.1 │    2022-06-02 │
│           1 │ 1.1.1.2       │ ᴺᵁᴸᴸ    │    2022-06-02 │
└─────────────┴───────────────┴─────────┴───────────────┘
```

This should work for you.
thanks.
