### ISSUE TITLE
Support post-filters for query tables

### ISSUE THREAD

**Issue by KochetovNicolai** [ClickHouse/ClickHouse#37918]
> (you don't have to strictly follow this form)

**Use case**

It would be helpful for grafana support. Additional conditions could be applied to specified table.

Example:
```
select sum(x), y from table_a group by y
union all
select a, b from table_b
```
condition: `y > 0 for table_a`

Rewrite a query:
```
select sum(x), y from table_a where y > 0 group by y
union all
select a, b from table_b
```

**Describe the solution you'd like**

A setting with mapping `table_name -> condition_text`.

Implemented in the same way as row-level filter.

**Describe alternatives you've considered**

Exposing an API to modify AST. Would be harder to implement, need maintenance. 

**Additional context**

It's an alternative approach to https://github.com/grafana/clickhouse-datasource/issues/131

**Comment by alexey-milovidov** [comment]
> A setting with mapping table_name -> condition_text.

Some use cases need to apply an "out of band" filter to the resulting dataset (not for the tables).
Example: a spreadsheet application (smart grid widget).
