### ISSUE TITLE
Join fails when join_algorithm set to partial_merge

### ISSUE THREAD

**Issue by dima898** [ClickHouse/ClickHouse#37928]
> You have to provide the following information whenever possible.

**Describe what's wrong**
We are running queries of following format:

```
CREATE TABLE final_table
ENGINE = MergeTree
ORDER BY tuple() as
select 
	   'smth1' as col1,
            'smth2' as  col2,
            'smth3'  as col3,
            'some_string_here' as col4,
			'even_longer_string_here' as col5
from "source_table"
        join joined_table on
				joined_table.col9 = source_table.col6
			and joined_table.col10 = source_table.col7
			and joined_table.col11 = source_table.col8
			and joined_table.col12 = 'R' -- this clause makes query fail when join_algorithm is partial_merge               
        SETTINGS max_parser_depth = 100000, join_algorithm = 'partial_merge'
```

We get the following error:
`Code: 44. DB::Exception: Conflicting column name '--': While executing JoiningTransform. (ILLEGAL_COLUMN) (version 22.5.1.2079 (official build))`

It is only reproducible when join_algorithm param is set to partial_merge and clause contains constant filter ( joined_table.col12 = 'R' ).

When we insert the filter to sub-select , our query finishes successfully:
```
CREATE TABLE final_table
ENGINE = MergeTree
ORDER BY tuple() as
            select 
			'smth1' as col1,
            'smth2' as  col2,
            'smth3'  as col3,
            'some_string_here' as col4,
			'even_longer_string_here' as col5
from "source_table"
        join (select * from joined_table where joined_table .col12 = 'R')  on
				joined_table.col9 = source_table.col6
			and joined_table.col10 = source_table.col7
			and joined_table.col11 = source_table.col8             
        SETTINGS max_parser_depth = 100000, join_algorithm = 'partial_merge'
```

**Does it reproduce on recent release?**

Reproducible on 22.5.1.2079 

**Error message and/or stacktrace**

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xb4903fa in /usr/bin/clickhouse
1. DB::Exception::Exception<char const*, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, long&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(int, fmt::v8::basic_format_string<char, fmt::v8::type_identity<char const*>::type, fmt::v8::type_identity<char const*>::type, fmt::v8::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::type, fmt::v8::type_identity<long&>::type, fmt::v8::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::type>, char const*&&, char const*&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, long&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&) @ 0xb4a8843 in /usr/bin/clickhouse
2. MemoryTracker::allocImpl(long, bool, MemoryTracker*) @ 0xb4a8575 in /usr/bin/clickhouse
3. MemoryTracker::allocImpl(long, bool, MemoryTracker*) @ 0xb4a7fb7 in /usr/bin/clickhouse
4. MemoryTracker::allocImpl(long, bool, MemoryTracker*) @ 0xb4a7fb7 in /usr/bin/clickhouse
5. MemoryTracker::allocImpl(long, bool, MemoryTracker*) @ 0xb4a7fb7 in /usr/bin/clickhouse
6. Allocator<true, true>::realloc(void*, unsigned long, unsigned long, unsigned long) @ 0xb29778c in /usr/bin/clickhouse
7. HashTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, DB::RowRefList, UInt128TrivialHash, HashTableNoState>, UInt128TrivialHash, HashTableGrower<8ul>, Allocator<true, true> >::resize(unsigned long, unsigned long) @ 0x1594fd01 in /usr/bin/clickhouse
8. ? @ 0x1594fa7a in /usr/bin/clickhouse
9. ? @ 0x159476d6 in /usr/bin/clickhouse
10. DB::HashJoin::addJoinedBlock(DB::Block const&, bool) @ 0x1591bcd4 in /usr/bin/clickhouse
11. DB::JoinSwitcher::addJoinedBlock(DB::Block const&, bool) @ 0x15e1ec93 in /usr/bin/clickhouse
12. DB::FillingRightJoinSideTransform::work() @ 0x16ee4ca1 in /usr/bin/clickhouse
13. DB::ExecutionThreadContext::executeTask() @ 0x16d18ee8 in /usr/bin/clickhouse
14. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x16d0cbfe in /usr/bin/clickhouse
15. ? @ 0x16d0e4c4 in /usr/bin/clickhouse
16. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xb53fc47 in /usr/bin/clickhouse
17. ? @ 0xb54367d in /usr/bin/clickhouse
18. ? @ 0x7f88e94f7609 in ?
19. __clone @ 0x7f88e941c163 in ?

**Additional context**

> Add any other context about the problem here.

**Comment by Avogar** [comment]
@vdimir Please take a look

**Comment by qoega** [comment]
Can you add tables schema or try to minimise the case?

It also will probably help if you can add result of `EXPLAIN actions = 1 <your query>`, `EXPLAIN AST <your query>`, `EXPLAIN SYNTAX <your query>`

**Comment by vdimir** [comment]
There's `JoinSwitcher` in the stack trace, so it should be related to `join_algorithm = 'auto'`

Could you please provide a schema for the tables? 
It's not reproduced on these tables:
<details>
<summary>Full example</summary>

```sql
DROP TABLE IF EXISTS joined_table;
DROP TABLE IF EXISTS source_table;

CREATE TABLE IF NOT EXISTS source_table (col6 UInt32, col7 UInt32, col8 UInt32, col12 String)
ENGINE = MergeTree ORDER BY col6;

INSERT INTO source_table VALUES (1, 2, 3, 'X');

CREATE TABLE IF NOT EXISTS joined_table (col9 Int32, col10 Int32, col11 Int32, col12 String)
ENGINE = MergeTree ORDER BY col9;

INSERT INTO joined_table VALUES (1, 2, 3, 'R');

select
'smth1' as col1,
    'smth2' as  col2,
    'smth3'  as col3,
    'some_string_here' as col4,
    'even_longer_string_here' as col5
from "source_table"
join joined_table on
        joined_table.col9 = source_table.col6
    and joined_table.col10 = source_table.col7
    and joined_table.col11 = source_table.col8
    and joined_table.col12 = 'R'
SETTINGS max_parser_depth = 100000, join_algorithm = 'partial_merge'
;
```



</details>

**Comment by vdimir** [comment]
I'll keep it reopened before we will have a reproducible test case and ensure that the fix works

**Comment by vdimir** [comment]
No example, will close

**Comment by jonashaag** [comment]
I hit this problem with a `partial_merge` with version 23.9.1.1533:

```
Code: 44. DB:: Exception: Received from localhost:9000
DB:: Exception: Conflicting column name '--pmj_cond_left_in(mycol1, ('6', '19))'
in block my_sort_col Nullable(String) ..., in(mycol1, ('6', '19')) ...),
--pmj_cond_left_in(mycol1, ('6', '19')) ...):
While executing JoiningTransform. (ILLEGAL_COLUMN)
```

**Comment by vdimir** [comment]
@jonashaag Do you have a repro?

**Comment by jonashaag** [comment]
Unfortunately not because I can't share the data, but I can do some debugging if you let me know what to do.

**Comment by vdimir** [comment]
Does the issue fires each time for the same query? Maybe it's possible to have a minimized example without a real data but with some sample?
Also may you try to run the same query and check if it works with `SETTINGS allow_experimental_analyzer = 1` ?

**Comment by jonashaag** [comment]
Yes, every time and yes, also with the new experimental analyzer if this is all it takes to enable it:

```
clickhouse client --allow_experimental_analyzer=1 < my_script.sql
```

**Comment by vdimir** [comment]
@jonashaag
Thank you for the information. I think I've figured problem out.

Here is the repro:

```sql
SET join_algorithm = 'partial_merge';
SET max_joined_block_size_rows = 100;

SELECT * FROM ( SELECT number AS a, number AS b FROM numbers(10000) ) t1
JOIN  ( SELECT number + 100 AS a FROM numbers(10000) ) t2
ON t1.a = t2.a AND t1.b > 0;
```

I'm going fix it soon.

As a workaround, if you need to stick with the `partial_merge` algorithm, you can set the `max_joined_block_size_rows` to a higher value (the default is 65409). You can try using 2x or 3x the default value. However, please be aware that this may impact performance and increase memory consumption.
