### ISSUE TITLE
LeadInFrame returns 0 for every row

### ISSUE THREAD

**Issue by Elvira91** [ClickHouse/ClickHouse#37946]
Clickhouse version: 22.6.1.1468

The LeadInFrame function returns 0
Example of query https://play.clickhouse.com/play?user=play#c2VsZWN0IExPX09SREVSS0VZLCBMT19MSU5FTlVNQkVSLCBMT19RVUFOVElUWSwgbGVhZEluRnJhbWUoTE9fUVVBTlRJVFkpCm92ZXIgKHBhcnRpdGlvbiBieSBMT19PUkRFUktFWSBvcmRlciBieSBMT19RVUFOVElUWSkKZnJvbSAoCiAgU0VMRUNUIDEgTE9fT1JERVJLRVksIDEgTE9fTElORU5VTUJFUiwgMSBMT19RVUFOVElUWQogIFVOSU9OIEFMTAogIFNFTEVDVCAxIExPX09SREVSS0VZLCAyIExPX0xJTkVOVU1CRVIsIDIgTE9fUVVBTlRJVFkKKSAKQVMgbGluZW9yZGVyCm9yZGVyIGJ5IExPX09SREVSS0VZLCBMT19RVUFOVElUWQ==

I have thought it may be my mistake, but the lagInFrame works normally
Example of query https://play.clickhouse.com/play?user=play#c2VsZWN0IExPX09SREVSS0VZLCBMT19MSU5FTlVNQkVSLCBMT19RVUFOVElUWSwgbGFnSW5GcmFtZShMT19RVUFOVElUWSkKb3ZlciAocGFydGl0aW9uIGJ5IExPX09SREVSS0VZIG9yZGVyIGJ5IExPX1FVQU5USVRZKQpmcm9tICgKICBTRUxFQ1QgMSBMT19PUkRFUktFWSwgMSBMT19MSU5FTlVNQkVSLCAxIExPX1FVQU5USVRZCiAgVU5JT04gQUxMCiAgU0VMRUNUIDEgTE9fT1JERVJLRVksIDIgTE9fTElORU5VTUJFUiwgMiBMT19RVUFOVElUWQopIApBUyBsaW5lb3JkZXIKb3JkZXIgYnkgTE9fT1JERVJLRVksIExPX1FVQU5USVRZ

**Comment by den-crane** [comment]
```sql
SELECT
    LO_ORDERKEY,
    LO_LINENUMBER,
    LO_QUANTITY,
    leadInFrame(LO_QUANTITY) OVER (PARTITION BY LO_ORDERKEY ORDER BY LO_QUANTITY ASC Rows BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS lead,
    lagInFrame(LO_QUANTITY) OVER (PARTITION BY LO_ORDERKEY ORDER BY LO_QUANTITY ASC Rows BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS lag
FROM
(
    SELECT
        1 AS LO_ORDERKEY,
        1 AS LO_LINENUMBER,
        1 AS LO_QUANTITY
    UNION ALL
    SELECT
        1 AS LO_ORDERKEY,
        2 AS LO_LINENUMBER,
        2 AS LO_QUANTITY
    UNION ALL
    SELECT
        1 AS LO_ORDERKEY,
        3 AS LO_LINENUMBER,
        3 AS LO_QUANTITY
) AS lineorder
ORDER BY
    LO_ORDERKEY ASC,
    LO_QUANTITY ASC

Query id: 03544a06-5893-4a34-92a8-ac6653476430

┌─LO_ORDERKEY─┬─LO_LINENUMBER─┬─LO_QUANTITY─┬─lead─┬─lag─┐
│           1 │             1 │           1 │    2 │   0 │
│           1 │             2 │           2 │    3 │   1 │
│           1 │             3 │           3 │    0 │   2 │
└─────────────┴───────────────┴─────────────┴──────┴─────┘
```

https://clickhouse.com/docs/en/sql-reference/window-functions/ 



lag/lead(value, offset) | Not supported. Workarounds:
-- | --
  | 1) replace with any(value) over (.... rows between <offset> preceding and <offset> preceding), or following for lead
  | 2) use lagInFrame/leadInFrame, which are analogous, but respect the window frame. To get behavior identical to lag/lead, use rows between unbounded preceding and unbounded following
