### ISSUE TITLE
Feature: implement RESPECT/IGNORE NULLS modifier for FIRST_VALUE window function

### ISSUE THREAD

**Issue by MaceWindu** [ClickHouse/ClickHouse#37950]
Version: 22.5.1.2079

`FIRST_VALUE` returns different and incorrect values for different records within same group.

Test data:
```sql
create table Position(Group Int32, Order Int32, Id Nullable(Int32)) ENGINE = Memory();

insert into Position values
(7, 10, 5),
(7, 20, 6),
(7, 30, NULL),
(7, 40, NULL);
```

failing query:
```sql
SELECT
    	p.Id,
    	FIRST_VALUE(p.Id) OVER(ORDER BY p.Order DESC)
    FROM
    	Position p
    WHERE
    	p.Group = 7
```

Results

|Id|FIRST_VALUEOrNull(Id) OVER (ORDER BY Order DESC)|
|-|-|
|NULL |                                             NULL   |
 |NULL |                                     NULL           |
 |6|                                               6|
|5|                                               6|

Expected:

|Id|FIRST_VALUEOrNull(Id) OVER (ORDER BY Order DESC)|
|-|-|
|NULL |                                             NULL   |
 |NULL |                                     NULL           |
 |6|                                              NULL           |
|5|                                               NULL           |

**Comment by alexey-milovidov** [comment]
Looks good to me. It returns the first non-NULL value.

**Comment by alexey-milovidov** [comment]
MS SQL Server has a special disambiguation clause: https://docs.microsoft.com/en-us/sql/t-sql/functions/first-value-transact-sql?view=sql-server-ver16

**Comment by alexey-milovidov** [comment]
Snowflake has the same disambiguation clause with default behavior to respect NULLs: https://docs.snowflake.com/en/sql-reference/functions/first_value.html

**Comment by alexey-milovidov** [comment]
PostgreSQL does not implement such clause but use RESPECT NULLs implicitly: https://www.postgresql.org/docs/current/functions-window.html

**Comment by alexey-milovidov** [comment]
I convert this task to a feature request.

**Comment by alexey-milovidov** [comment]
Workaround: `FIRST_VALUE(tuple(x))`

**Comment by alexey-milovidov** [comment]
The behavior can be changed quite easily, see `IAggregateFunction::getOwnNullAdapter`
The syntax for RESPECT NULLS / IGNORE NULLS can be added quite easily, and we can implement FIRST_VALUE_RESPECT_NULLS and FIRST_VALUE_IGNORE_NULLS functions under the hood.

**Comment by MaceWindu** [comment]
Just want to add that this behavior for `FIRST_VALUE` without `NULLS` clause observed at least for:
- Sql Server
- DB2 (at least DB2 LUW)
- Firebird
- Informix
- MySQL/MariaDB
- Oracle
- Pgsql
- SAP HANA 2
- SQLite

Oonly ClickHouse fails our test here.

**Comment by den-crane** [comment]
it was implemented https://github.com/ClickHouse/ClickHouse/pull/46467

https://fiddle.clickhouse.com/4edfc51f-0907-4f32-98c4-5e4063227a12

```sql
create table Position(Group Int32, Order Int32, Id Nullable(Int32)) ENGINE = Memory();

insert into Position values (7, 10, 5), (7, 20, 6), (7, 30, NULL),(7, 40, NULL);

SELECT
    	p.Id,
    	first_value(p.Id)      OVER(ORDER BY p.Order DESC) def,  
    	first_value(p.Id) respect nulls   OVER(ORDER BY p.Order DESC) resp,
      	first_value(p.Id) ignore nulls    OVER(ORDER BY p.Order DESC) ign
    FROM
    	Position p
    WHERE
    	p.Group = 7
format PrettyCompact;

+---Id-+--def-+-resp-+--ign-+
| NULL | NULL | NULL | NULL |
| NULL | NULL | NULL | NULL |
|    6 |    6 | NULL |    6 |
|    5 |    6 | NULL |    6 |
+------+------+------+------+
```
