### ISSUE TITLE
Unknown database engine: Atomic

### ISSUE THREAD

**Issue by metaIhead** [ClickHouse/ClickHouse#37955]
I try `CREATE DATABASE service ENGINE = Atomic;`  and i have error.

`Received exception from server (version 18.16.1):
Code: 336. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Unknown database engine: Atomic.`.

What i am doing wrong?

```
ClickHouse client version 18.16.1.
ClickHouse server version 18.16.1 revision 54412.
```

**Comment by genzgd** [comment]
You are running a very old version of ClickHouse that doesn't support Atomic databases.
