### ISSUE TITLE
why i can not select newest data from clickhouse when use limit.

### ISSUE THREAD

**Issue by xeonnicer** [ClickHouse/ClickHouse#37963]
this is my create table statement :
CREATE TABLE auditor.clickhousesecalert
(
    `id` UInt64,
    `category` UInt8,
    `level` UInt8,
    `src_mac` Nullable(String),
    `src_ip` Nullable(String),
    `src_port` Nullable(UInt16),
    `src_port_search` Nullable(String),
    `dst_mac` Nullable(String),
    `dst_ip` Nullable(String),
    `dst_port` Nullable(UInt16),
    `dst_port_search` Nullable(String),
    `origin_mac` Nullable(String),
    `conflict_mac` Nullable(String),
    `protocol` Nullable(String),
    `illegal_ip` Array(String),
    `last_at` DateTime64(6) DEFAULT now(),
    `count` UInt16,
    `other_info` Nullable(String),
    `payload` Nullable(String),
    `is_read` UInt8,
    `read_at` Nullable(DateTime),
    `memo` Nullable(String)
)
ENGINE = ReplacingMergeTree
PARTITION BY toYYYYMM(last_at)
ORDER BY -id
SETTINGS index_granularity = 8192

These two pictures indicate that when limit is used, the returned data is not the latest，Could you please tell me why?
![nolimit](https://user-images.githubusercontent.com/34495927/173006588-dbbc05ff-31b5-4abc-99f3-990f812eafd9.png)
![with limit](https://user-images.githubusercontent.com/34495927/173006625-a8be714f-e2eb-4083-af38-0bf2e316835d.png)

**Comment by Ryado** [comment]
This is expected, it's the normal behaviour of `LIMIT`:


> If there is no ORDER BY clause that explicitly sorts results, the choice of rows for the result may be arbitrary and non-deterministic.

From: https://clickhouse.com/docs/en/sql-reference/statements/select/limit/

You can just add an ORDER BY statement

**Comment by xeonnicer** [comment]
Thanks for your answer, my problem is solved.
