### ISSUE TITLE
Not found column in block

### ISSUE THREAD

**Issue by zhnpeng** [ClickHouse/ClickHouse#37962]
**Describe what's wrong**

raise exception ClickHouse exception, code: 10, DB::Exception: Not found column sum(value1) in block, when using sub query

**Does it reproduce on recent release?**

[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

Yes, v21.8.4.51

**Enable crash reporting**

N/A

**How to reproduce**

```
CREATE TABLE db.table_1(`column1` String, `column2` String, `value1` Int32, `value2` Int32) ENGINE = MergeTree ORDER BY (column1, column2);

insert into db.table_1 (column1, column2, value1, value2)  VALUES  ('col1', 'col2', 1, 2);

select * from (
  select column1, column2, sum(value1) / sum(value2) as v1_div_v2
  from db.table_1
  where column1 = 'col1'
  group by column1, column2
  limit 10
) where column2 = 'col2'
```

**Expected behavior**

execute sql correctly and do not raise exception, behave like below

```
select column1, column2, sum(value1) / sum(value2) as v1_div_v2
from db.table_1
where column1 = 'col1' and column2 = 'col2'
group by column1, column2
limit 10
```

**Error message and/or stacktrace**

ClickHouse exception, code: 10, host: 10.1.4.160, port: 8123; Code: 10, e.displayText() = DB::Exception: Not found column sum(value1) in block (version 21.8.4.51 (official build))

**Additional context**

we has a pipeline style DSL,  likely to be:

```
column1 == "col1" limit 10 | column2 == "col2"
```

and we will construct sql base on this pipeline style DSL, as below:

```
select * from (
  select column1, column2, sum(value1) / sum(value2) as v1_div_v2
  from db.table_1
  where column1 = 'col1'
  group by column1, column2
  limit 10
) where column2 = 'col2'
```

and then, exception raised from clickhouse

**Comment by Avogar** [comment]
It's already fixed and backported. In 21.8.16.16 your query works as expected.

**Comment by zhnpeng** [comment]
Thanks @Avogar
