### ISSUE TITLE
Why clickhouse with clickhouse-keeper get Obviously lower performance in writing  compared to zookeeper

### ISSUE THREAD

**Issue by didiaibiancheng** [ClickHouse/ClickHouse#37974]
**background**
In the new version 22.3.6.6LTS of clickhouse, we introduce clickhouse-keeper to relplace zk and try to apply it to the Pro env. finding that the writing speed slow down obviously after zk being replaced.After doing a pressure test in dev to compare the performance between zk and ck, I find that ch with zk get much better performance when writing than ck. I feel pullzed about the decrease performance of ck.

**info about my pressure test**
machine✖️5
cpu:40core, Intel(R) Xeon(R) Silver 4210 CPU @ 2.20GHz
memory:64G
disk: 1T SSD ✖️2
system:CentOS Linux release 7.5.1804 (Core)
3 of them using for clickhouse server and the rest for zk/ck. in testing with 3 zk/ck mode, There will be one machine for both clickhouse server and zk/ck.

my test are based like this:
Execute 3000 insert sql statements in a loop using official  clickhouse-benchmark tool , each sql inserts 3000 records, and the inserted id keeps changing. create_time takes the value of the now() function.
insert batchsize: 3000
pressure time: 60s
concurrency: 80
parts_to_throw_insert: 3000
replicas:3
rowSize:about 30byte
ddl:
```
CREATE TABLE db_test.t32_local
(
    `id` String,
    `price` Float64,
    `create_time` DateTime
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/db_test/t32_local',
 '{replica}')
ORDER BY id
SETTINGS index_granularity = 8192,
 parts_to_throw_insert = 3000;

```
**test result**
ck/zk of one node:
metrics\middleware-type | ck(engine=ReplicatedMergeTree) | zk(engine=ReplicatedMergeTree)
-- | -- | --
qps | 540 | 650
rps | 1.58million | 1.88million
cpu | 630% | 700%
io(disk) | max:ck(40m/s)ch-server(85m/s) | max:zk(6m/s)chserver(105m/s)
lat(99.99%) | less than 1.809 sec | less than 1.241s
lat(50%) | less than 0.123 sec | less than 0.119s

ck/zk of three node:
metrics\middleware-type | ck(engine=ReplicatedMergeTree) | zk(engine=ReplicatedMergeTree)
-- | -- | --
qps | 269 | 651
rps | 0.850million | 1.960million
cpu | 380% | 648%
io(disk) | max:ch-keeper(37m/s)ch-server(25m/s) | max:zk(8m/s)chserver(105m/s)
lat(99.99%) | less than 0.950s | less than 0.913s
lat(50%) | less than 0.242s | less than 0.113s

In stand-alone mode, clichouse with ck is only about 15% lower than zk's performance. But ck get much lower performance of 60% compared to zk in 3-node mode.
my keeper-server conf are mostly default，and I also try to adjust some params like force_sync snapshot_distance or reserved_log_items, but make no obvious effect
![image](https://user-images.githubusercontent.com/46508720/173034816-2cf4476b-f391-4960-bba3-6e0d2ece354c.png)

**Expected performance**
In my opinion, clickhouse with ck should get comparable performance in wtring compared to zk.  Is  there someting wrong with my testing or potential bug with clickhoue keeper？and I have tried to find the official benchmark testing between zk and ck in clickhouse writing performance,but get nothing.I will be appriciate if someone can offer help. 

**Additional context**
By the way,In our pro env,we find that the io  %util of zk/ck is always very high(zk is about 85%,ck reaches 100%) ,but the write amount of zk/ck is lower than 30mBps.That is to say,the disk is always very busy, Im not sure wether the high util% of ck limit the speed of writing in pro env when using ck.I have not reproduce this high util% for limitation of concurrency in dev yet.

**Comment by qoega** [comment]
snapshot_distance=10 is too low. Set it to something like 100000 or more

**Comment by qoega** [comment]
Actually it is very cool that you make independent tests of ClickHouse Keeper vs ZooKeeper. We would be very happy if you will publish some results in the end. You can also write a blog post in our blog if you are interested.

**Comment by didiaibiancheng** [comment]
> snapshot_distance=10 is too low. Set it to something like 100000 or more. After each 10 writes it creates new full snapshot. This setting is in log entries.

Actually the test results above are based on the default setting of napshot_distance=100000. I just adjust napshot_distanc to 10 to see if this will result in high util% of io. Sorry for forgetting set the parameters back when posted the conf picture.

**Comment by didiaibiancheng** [comment]
> Actually it is very cool that you make independent tests of ClickHouse Keeper vs ZooKeeper. We would be very happy if you will publish some results in the end. You can also write a blog post in our blog if you are interested.

Yeah,I'm very glad to do that. My test also show that the avg latency of ck(more than 10ms) is larger than zk(about 2ms). I'm not sure what's the root cause of that.

**Comment by didiaibiancheng** [comment]
> Actually it is very cool that you make independent tests of ClickHouse Keeper vs ZooKeeper. We would be very happy if you will publish some results in the end. You can also write a blog post in our blog if you are interested.

Yeah, I'll be glad to do that. In my new test,ck get about 15-20% lower than zk in 3-node mode after adjusting the snap_distance to default 100000.But in standalone mode, they get comparable performance.
