### ISSUE TITLE
AsynchronousMetrics: add info about the total memory amount with respect to cgroup limits.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#37983]
**Use case**

Better monitoring of ClickHouse in Kubernetes.

**Describe the solution you'd like**

Add a new metric.

**Comment by mdonkers** [comment]
Some input from where max memory can be fetched from: (and CPU but places should be comparable):

cgroupv1:
- `/sys/fs/cgroup/memory/memory.limit_in_bytes`
- `/sys/fs/cgroup/cpu/cpu.shares`

cgroupv2 - container:
-> get the cgroup via the hosts file, bit of a hack but so far guaranteed to work. In Bash would completely look like:
- `cat "$(find /sys/fs/cgroup/ -iname "*$(sed -n 's/.*\([a-f0-9]\{64\}\)\/hosts.*/\1/p' /proc/self/mountinfo)*" | head -n 1)/memory.max`

cgroupv2 - systemd:
- `/sys/fs/cgroup/memory.max`

cgroupv1 - container, backup:
-> similar hack as cgroupv2
- `cat "$(grep -E '[^\/]+\/\S+\s+\/sys\/fs\/cgroup\/.*' /proc/self/mountinfo | head -n 1 | awk '{ print "/sys/fs/cgroup/memory/" $4 "/memory.limit_in_bytes" }')"`

SystemD v232+ 
-> check the `INVOCATION_ID` environment variable to detect if running via this way
-> then grep the 'memory' cgroup id from `/proc/$$/cgroup`
- `/sys/fs/cgroup/memory${cgroup_memory}/memory.limit_in_bytes`

**Comment by nikitamikhaylov** [comment]
@alekar Will do this task

**Comment by alekar** [comment]
Thanks @nikitamikhaylov. I'll add this support to `src/Interpreters/AsynchronousMetrics.cpp`.

**Comment by sichenzhao** [comment]
need follow up to support cgroup-v2

**Comment by sichenzhao** [comment]
working in dev for cgroup-v1 
![image](https://user-images.githubusercontent.com/3507205/216483519-57266efc-f41b-410e-8a20-62545afd7957.png)
