### ISSUE TITLE
Can we use clickhouse to query the rows

### ISSUE THREAD

**Issue by sridhard** [ClickHouse/ClickHouse#37989]
Hi,

we want to use click house for analytics. I know that click house is very good in analytics like calculating of averages/sum etc.

In addition to analytics we have a usecase to query the rows from clickhouse db.

Example: consider the below tables
Table: Videos                               Fields: ID, video title, price, duration etc
Table: users                                 Fields: ID, name, email, age, etc
Table:VideoWatchStats              Fields: userId, watchDuration, watchDate

VideoWatchStats contains the daily aggregated watch time of a user for a video.

Now I want to query like: Get the aggregated watch time between 10-Dec-2020 to 29-dec-2020 Group by UserId and videoId.
To show the data to user we want to show like (In table format with pagenation)
username | age | email | videoTitle | videoDuration | AggregatedWatchDuration

Assume we have millions of users and millions of videos and millions of video watches.

1. We want to show the data to the user as shown above with page numbers(pagination). User can select any page and see the data
2. We want to send emails to the users with these stats. So we will query 10000 records at a time using offset and then send email.

This query will involve Join of 3 tables.

Since this query has heavy aggregation mysql will not work. Also since we have given the option of date range we cannot aggregate monthly data. So to get the aggregates clickhouse is best. After the aggregation we want to get the records also with multiple columns. can we use clickhouse for this usecase?

We want to use click house because we have many other analytics requirements. So i want to know can we use clickhouse for querying records also. Will click house perform better in querying records and joins compared to others like mysql or redshift etc?

**Comment by melvynator** [comment]
This is a use that can easily be managed by ClickHouse. There is a myth about ClickHouse not being able to join, which is not really true. In your scenario, the joins are pretty straightforwards. In your setup, you will probably have a main table with most of your raw data and you are going to build materialized views to get your analytics using tables like: 

- [SummingMergeTree](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/summingmergetree)
- [AggregatingMergeTree](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/aggregatingmergetree) 

You can use a [materialized view](https://clickhouse.com/docs/en/engines/table-engines/special/materializedview/) to populate these tables very easily. Now once you have created your materialized views you will be able to do your JOIN (in your scenario you will probably use the left and right side joins), you can see all the supported JOINS [here](https://clickhouse.com/docs/en/sql-reference/statements/select/join/). 

In terms of performance, it's always hard to say that ClickHouse will perform better than X or Y without testing things out for your specific scenario. We have a benchmark [here](https://clickhouse.com/benchmark/dbms/#[100000000,[%22ClickHouse%22,%22MySQL%22],[%221%22,%222%22]]) that you can use as a reference. It does not include redshift though.

**Comment by sridhard** [comment]
thanks a lot
