### ISSUE TITLE
Docs said I can run clickhouse-client with `-qf` parameter, while it does not have the desired effect.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#37984]
**Describe the issue**
`-qf` will be parsed as `-q -f`, not as `--queries-file`.

**Comment by HeenaBansal2009** [comment]
Options like -if and -of are also not working .
@alexey-milovidov , Aspart of this do we need to update the document or looking  to fix the code to allow -qf as --queries-file

**Comment by alexey-milovidov** [comment]
We need to fix the docs (including the embedded docs in the code).

**Comment by alexey-milovidov** [comment]
Normal command line option parsers only allow `-s` (one dash, single character) or `--long`.

**Comment by DanRoscigno** [comment]
@alexey-milovidov I believe that you already fixed this, can it be closed?

**Comment by alexey-milovidov** [comment]
@DanRoscigno I fixed it yesterday.
