### ISSUE TITLE
How to slow down insert process or reduce the memory usage?

### ISSUE THREAD

**Issue by frank-zsy** [ClickHouse/ClickHouse#37991]
ClickHouse server edition: 20.8.7.15

We are using ClickHouse for education purpose, so we created some datasets extracted from a large table with `Native` format and compressed to a single file.

Then we want the students to start a ClickHouse server container locally and import the data on init. The shell script is [here](https://github.com/X-lab2017/open-digger/blob/master/sample_data/build/initdb.sh#L15). But no matter what size the data is, the import process always requires like 6 GB memory to complete which is not quite friendly to students' laptop.

Is there something we can do to slow down the insert process or reduce the memory usage on data insert? I tried to limit the memory setting of the server, but it fails anyway.

Thanks.

**Comment by den-crane** [comment]
How many columns in the table?

Try to reduce block size in the Native format. `set max_block_size=512` (when you create Native)

**Comment by frank-zsy** [comment]
About 100 columns, so the memory usage is related to the column number? I will try to limit the block size first and see how it works, thanks a lot.

**Comment by UnamedRus** [comment]
Just a side note, may be ClickHouse over web server be more memory efficient and faster (to import data) https://github.com/ClickHouse/ClickHouse/pull/25251

**Comment by frank-zsy** [comment]
> Try to reduce block size in the Native format. `set max_block_size=512` (when you create Native)

If I add --max_block_size=512 on creating the sample dataset, it will significantly reduce the memory usage but it still fails on inserting the data. Although the memory usage won't go up to 1 GB during the insert process if I monitor the resource, the following error will also occur if I set the memory limit to 3 GB for container:

```
DB::Exception: Memory limit (total) exceeded: would use 2.64 GiB ( attempt to allocate chunk of 4194903 bytes). maximum: 2.63 GiB.
```

I have no idea why this happens.

BTW, if you follow the [doc](https://github.com/X-lab2017/open-digger/blob/master/sample_data) with the smallest dataset and the image we provide, the error may occur during the initialization if the memory limit set to 3 GB.

**Comment by frank-zsy** [comment]
> Just a side note, may be ClickHouse over web server be more memory efficient and faster (to import data) #25251

Thanks, I will look into the feature~
