### ISSUE TITLE
[MySql Interface] Column of Bool type reported to client using TINYINT type and value returned as `true`/`false` string literal value

### ISSUE THREAD

**Issue by MaceWindu** [ClickHouse/ClickHouse#37999]
Version: `22.5.1.2079`

Selection of Bool field using MySQL interface reports type incompatible with provided value:
- reported type is TINYINT
- values, returned to client are "true" or "false" strings (not a number)

```sql
create table booltable(field Bool) ENGINE=Memory()

insert into booltable values (true),(false)

select field from booltable
```

This could lead to incorrect data interpretation by client libraries: they will try to parse them as number and fail.

E.g. in my case [`MySqlConnector`](https://github.com/mysql-net/MySqlConnector/) adapter fails with following error, which cannot be workarounded currently:
```
System.FormatException
  HResult=0x80131537
  Message=One of the identified items was in an invalid format.
  Source=MySqlConnector
  StackTrace:
   at MySqlConnector.Core.TextRow.ParseInt32(ReadOnlySpan`1 data)
   at MySqlConnector.Core.TextRow.GetValueCore(ReadOnlySpan`1 data, ColumnDefinitionPayload columnDefinition)
   at MySqlConnector.Core.Row.GetValue(Int32 ordinal)
   at MySqlConnector.Core.Row.GetByte(Int32 ordinal)
```

**Comment by MaceWindu** [comment]
@bgrainger, FYI

**Comment by bgrainger** [comment]
> reported type is TINYINT
> values, returned to client are "true" or "false" strings (not a number)

This doesn't follow the MySQL text protocol. `TINYINT` columns must store a numeric value that will be returned as an ASCII string (between `-128` and `127`).

MySqlConnector supports `BOOL` (in DDL) being an alias for `TINYINT(1)` by treating the returned values `0` and `1` as false and true iff the "column length" of the column is 1 (and the column is signed).

(It would certainly be possible to build support for a custom `BOOL` column type that has `true` and `false` values, but doing so would probably be incompatible with almost every off-the-shelf MySQL client library, as I'm not aware of any other MySQL-compatible server that supports that.)
