### ISSUE TITLE
Allow partial result on query cancellation.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#38009]
**Use case**

Exploratory data analysis.

**Describe the solution you'd like**

Add a setting to enable the following behavior:
if the query is canceled, cancel all the data sources as if they were ended, but let the query pipeline finish processing the data as usual and return the result.

The client should clearly indicate that the result is partial.
Double cancellation should cancel the query pipeline as usual.

**Additional context**

As a related feature, a stream of partial results can be returned during a normal query run.

**Comment by amosbird** [comment]
> Double cancellation should cancel the query pipeline as usual.

Current implementation will kill clickhouse-client when the second `ctrl-c` is received. It requires special treatment to support this setting.

**Comment by alexey-milovidov** [comment]
@amosbird Another option for the second `Ctrl+C` is to terminate the connection and return to the prompt.

**Comment by alexey-milovidov** [comment]
Implemented.

**Comment by amosbird** [comment]
https://github.com/ClickHouse/ClickHouse/pull/45689
