### ISSUE TITLE
Hangs at reading HDFS EC data

### ISSUE THREAD

**Issue by zhanglistar** [ClickHouse/ClickHouse#38012]
Now libhdfs3 does not support erasure encoding data in HDFS, causing clickhouse hangs. We just throw "not supported" hint for now, and we will develop libhdfs3 to support EC in later days，see PR:https://github.com/ClickHouse/libhdfs3/pull/20.
And then I will update submodule version.

**Comment by alexey-milovidov** [comment]
Merged. Let's update the submodule.

**Comment by zhanglistar** [comment]
> Merged. Let's update the submodule.

In this PR: https://github.com/ClickHouse/ClickHouse/pull/37949
