### ISSUE TITLE
CREATE TABLE ... EMPTY AS SELECT

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#38049]
CREATE TABLE ... **EMPTY** AS SELECT

**Use case**

Create a table with the same structure as SELECT query returns but don't fill it.

**Describe alternatives you've considered**

CREATE TABLE ... AS DESCRIBE (SELECT ...)

\- more consistent but also more clunky.

**Comment by ykahlon** [comment]
Hi, is there an ETA for fixing this issue?

**Comment by alexey-milovidov** [comment]
@ykahlon It's a proposal for a new feature. There is nothing to "fix".
If you want to kindly ask the engineer @tavplubix about his thoughts - please do.
