### ISSUE TITLE
multiFuzzyMatchAny function requirement 

### ISSUE THREAD

**Issue by sophie-jeong** [ClickHouse/ClickHouse#38046]
In the multiFuzzyMatchAny function, Please make it possible to use column values instead of constants for the third variable
I really need this feature so much!
I need to extract names that match ( like operator ) similarly to the data in the array value category.names , and I plan to do this regularly.

**Use case**
```
SELECT
    names,
    multiFuzzyMatchAny(names, 1, a.`category.names`)
FROM
(
    SELECT category.names AS names
    FROM mall
    ARRAY JOIN category
) AS A
CROSS JOIN a
LIMIT 10
DB::Exception: Argument at index 2 for function multiFuzzyMatchAny must be constant. (ILLEGAL_COLUMN)
```

**Describe the solution you'd like**

> A clear and concise description of what you want to happen.

**Describe alternatives you've considered**

> A clear and concise description of any alternative solutions or features you've considered.

**Additional context**

> Add any other context or screenshots about the feature request here.

**Comment by alexey-milovidov** [comment]
The reason why it requires a constant argument is that compiling a regular expression (especially for fuzzy matching) can be heavy. Doing it for every record is unreasonable. The only viable case is when you have only a few different regexes.

**Comment by sophie-jeong** [comment]
I'm expecting it to be heavy.
But isn't Clickhouse an analytics-specialized DBMS?
if so, I think a function that matches similar text is absolutely necessary.
How about providing the function as an on/off function by setting a set parameter?

**Comment by rschu1ze** [comment]
Similar functionality (non-const pattern/regex arguments) was added very recently for functions `(I)LIKE()` and `MATCH()` with #37251. Haven't checked in detail yet but I have at least a rough idea what needs to be changed for `multiFuzzyMatchAny()`.

`multiFuzzyMatchAny()` leverages Intel's hyperscan library (at least on x86). Alexey proposed to replace this lib by vectorscan which is a community fork with SIMD support on other platforms. Having vectorscan is not a strict requirement for this ticket, but it would simplify things later on (+ make string matching functions faster on ARM). Guess we should do this first.
