### ISSUE TITLE
[MySQL interface] It is not possible to distinguish String vs FixedString columns

### ISSUE THREAD

**Issue by MaceWindu** [ClickHouse/ClickHouse#38059]
Version: `22.5.1.2079`

Server returns same type `CHAR(0)` for both `String` and `FixedString` data, which makes it impossible to distinguish between filler  \0 characters that could be ignored (for FixedString-typed column) and \0 data bytes for String column.

**Comment by alexey-milovidov** [comment]
We have to use VARCHAR for both String and FixedString, because CHAR in MySQL is counted in the number of code points, not the number of bytes like in ClickHouse. Although maybe CHAR(n) COLLATE latin1 can suffice.
