### ISSUE TITLE
Clickhouse behaving abnormally - Query response is intermittently wrong on one of the replicas in a non-sharded clickhouse cluster

### ISSUE THREAD

**Issue by rastogiaashi** [ClickHouse/ClickHouse#38063]
**Problem statement:**

> I have a ReplicatedMergeTree table (distributed as well) on a non-sharded clickhouse cluster. The clickhouse version is 21.11.3.6. There are 4 replica machines behind the cluster. Intermittently some of my queries give a wrong response on one machine at a time. 

Sample query:

`SELECT reporting_time, processing_time,`test_table`.`agId`, `test_table`.`tId`, `test_table`.`cId`, sum(test_table.engagements)/sum(test_table.views) AS ctr FROM db.`test_table` WHERE `test_table`.`tId` = 'xyz' AND `test_table`.`cId` = 'abc' AND `test_table`.`place` = 'F' AND `test_table`.`processing_time` >= '2022-06-01 00:00:00' AND `test_table`.`processing_time` <= '2022-07-07 23:59:59' AND `test_table`.`reporting_time` >= '2022-06-07 00:00:00' AND `test_table`.`reporting_time` <= '2022-06-07 23:59:59' GROUP BY `test_table`.`agId`, `test_table`.`tId`, `test_table`.`cId`,reporting_time, processing_time ORDER BY SUM(`test_table`.`views`) DESC LIMIT 50`

Hierarchy of the data is somewhat like this: A tId can have multiple cId and a cId can have multiple agId. Response sometime gives "agId" belonging to different cId and tId and the corresponding tId and cId are same as the filters. 

**Does it reproduce on recent release?**

I had upgraded my clickhouse version from 20.4.2 to 21.11.3.6 and the intermittent issues have surfaced since then.

**Error message and/or stacktrace**

> No error messages have surfaced in the error log.

**Additional context**

> After further investigation we figured that data from other partitions show up in a particular partition's response. The issues have been intermittent and the queries have been different as well. The issue generally happens when current date data is queried. 

Kindly help me with a direction to further debug this issue.

**Comment by den-crane** [comment]
Check 

```
SELECT
    database,
    table,
    type,
    max(last_exception),
    max(postpone_reason),
    min(create_time),
    max(last_attempt_time),
    max(last_postpone_time),
    max(num_postponed) AS max_postponed,
    max(num_tries) AS max_tries,
    min(num_tries) AS min_tries,
    countIf(last_exception != '') AS count_err,
    countIf(num_postponed > 0) AS count_postponed,
    countIf(is_currently_executing) AS count_executing,
    count() AS count_all
FROM system.replication_queue
GROUP BY
    database,
    table,
    type
ORDER BY count_all DESC

```
at all replicas.

Which table is distributed?

**Comment by rastogiaashi** [comment]
The query above gives 0 rows in response set. 

Here are my local and distributed tables:

```
CREATE TABLE db.test_table
(
    `reporting_time` DateTime,
    `processing_time` DateTime,
    `ingestion_source` String DEFAULT 'na',
    ...
    `agId` String DEFAULT 'null',
    `cId` String DEFAULT 'null',
    `tId` String DEFAULT 'null',
   ....
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/cluster_name/db/test_table/{shard}', '{replica}')
PARTITION BY (processing_time, ingestion_source)
ORDER BY (reporting_time, tId, cIdd, agId, ..)
SETTINGS index_granularity = 8192



CREATE TABLE db.test_table_distributed
(
    `reporting_time` DateTime,
    `processing_time` DateTime,
    `ingestion_source` String DEFAULT 'na',
    ...
    `agId` String DEFAULT 'null',
    `cId` String DEFAULT 'null',
    `tId` String DEFAULT 'null',
)
ENGINE = Distributed('cluster_name', 'db', 'test_table', rand())
```

**Comment by rastogiaashi** [comment]
I checked our dashboards where we log metrics on data replication delays and there was no lag logged.

**Comment by rastogiaashi** [comment]
> Check
> 
> ```
> SELECT
>     database,
>     table,
>     type,
>     max(last_exception),
>     max(postpone_reason),
>     min(create_time),
>     max(last_attempt_time),
>     max(last_postpone_time),
>     max(num_postponed) AS max_postponed,
>     max(num_tries) AS max_tries,
>     min(num_tries) AS min_tries,
>     countIf(last_exception != '') AS count_err,
>     countIf(num_postponed > 0) AS count_postponed,
>     countIf(is_currently_executing) AS count_executing,
>     count() AS count_all
> FROM system.replication_queue
> GROUP BY
>     database,
>     table,
>     type
> ORDER BY count_all DESC
> ```
> 
> at all replicas.
> 
> Which table is distributed?

@den-crane , rephrasing the issue here that the filters coming from the query are not honoured as the data coming in the response doesn't exist in the table. The issue doesn't seem like a replication lag issue but intermittent wrong response dishonouring the filters in the query.

**Comment by den-crane** [comment]
Upgrade to 22.3 or 22.5

**Comment by rastogiaashi** [comment]
Hi all, the issue has been resolved. The issue here was w.r.t uncompressed cache.
https://github.com/ClickHouse/ClickHouse/issues/31986#issuecomment-983423493
https://github.com/ClickHouse/ClickHouse/issues/31449
https://github.com/ClickHouse/ClickHouse/pull/31826

This helped. We will be updating the clickhouse version to see if the fix works for us.
