### ISSUE TITLE
Alter of type 'ADD_COLUMN' is not supported by storage Kafka.

### ISSUE THREAD

**Issue by SpringHgui** [ClickHouse/ClickHouse#38078]
```
Code: 48. DB::Exception: Alter of type 'ADD_COLUMN' is not supported by storage Kafka. (NOT_IMPLEMENTED) (version 22.5.1.2079 (official build))
```
how to ADD COLUMN ? create new table?

**Comment by e-mars** [comment]
Not currently supported.
Table would need to be dropped and recreated.
see below:
https://clickhouse.com/docs/en/integrations/kafka/kafka-table-engine#adding-kafka-metadata
