### ISSUE TITLE
How skip kafka message when error

### ISSUE THREAD

**Issue by SpringHgui** [ClickHouse/ClickHouse#38076]
my  Kafka consumer 
```
CREATE TABLE logs.consumer (
    Timestamp String,
    Level String,
    RenderedMessage String
   ) ENGINE = Kafka SETTINGS kafka_broker_list = 'xxxxx:9092',
                            kafka_topic_list = 'my-topic',
                            kafka_group_name = 'group1',
                            kafka_format = 'JSONEachRow',
                            kafka_num_consumers = 1;
```
When my message is individually not in json format, I expect him to skip these problematic messages and process the correct messages subsequently

**Comment by e-mars** [comment]
Below is a link on handling malformed messages:
https://clickhouse.com/docs/en/integrations/kafka/kafka-table-engine/#handling-malformed-messages

could you take a look?
