### ISSUE TITLE
delete_tmp_moving error: doesn't exist or one of nested files has gone

### ISSUE THREAD

**Issue by young-scott** [ClickHouse/ClickHouse#38073]
clickhouse version: v22.3.6.5-lts

I built 3 shard 2 replica cluster of clickhouse. ssd as hot disk, nfs disk  as cold disk。

today, I get lots of error message like this:

2022.06.15 08:00:56.517028 [ 634101 ] {} <Error> cloud_loghouse.gxinferencesd_local: Directory /mnt/cfs/data/cloud_loghouse/gxinferencesd_local/delete_tmp_moving/20220614_20695_29130_6 (part to remove) doesn't exist or one of nested files has gone. Most likely this is due to manual removing. This should be discouraged. Ignoring.
2022.06.15 08:01:29.829031 [ 634096 ] {} <Error> cloud_loghouse.gxinferencesd_local: Directory /mnt/cfs/data/cloud_loghouse/gxinferencesd_local/delete_tmp_moving/20220614_33277_41720_6 (part to remove) doesn't exist or one of nested files has gone. Most likely this is due to manual removing. This should be discouraged. Ignoring.

**this is the  table schema**

CREATE TABLE cloud_loghouse.gxinferencesd_local
(
    `flags` UInt32,
    `severityText` String,
    `name` String,
    `subPath` String MATERIALIZED resValue[indexOf(resKey, 'subPath')],
    `timeUnixNano` UInt64,
    `instrumLibLogSchemaUrl` String,
    `groupName` String MATERIALIZED resValue[indexOf(resKey, 'groupName')],
    `instanceName` String MATERIALIZED resValue[indexOf(resKey, 'instanceName')],
    `bodyValue` Array(String),
    `instrumLibName` String,
    `severityNumber` Int32,
    `spanId` String,
    `appName` String MATERIALIZED resValue[indexOf(resKey, 'appName')],
    `realPath` String MATERIALIZED resValue[indexOf(resKey, 'realPath')],
    `traceIdStr` String,
    `schemaUrl` String,
    `_source` String,
    `bodyKey` Array(String),
    `traceId` String,
    `psa` String MATERIALIZED resValue[indexOf(resKey, 'psa')],
    `uuid` UUID DEFAULT generateUUIDv4(),
    `timestamp` DateTime,
    `resKey` Array(String),
    `droppedAttriCnt` UInt32,
    `ip` String MATERIALIZED resValue[indexOf(resKey, 'ip')],
    `passzonecode` String MATERIALIZED resValue[indexOf(resKey, 'passzonecode')],
    `instrumLibVersion` String,
    `resValue` Array(String),
    `attrKey` Array(String),
    `resDroppedAttriCnt` UInt32,
    `spanIdStr` String,
    `appKey` String MATERIALIZED resValue[indexOf(resKey, 'app.key')],
    `attrValue` Array(String)
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/cloud_loghouse/gxinferencesd_local2/{shard}', '{replica}')
PARTITION BY toYYYYMMDD(timestamp)
ORDER BY timestamp
TTL timestamp + toIntervalDay(7), timestamp + toIntervalDay(1) TO VOLUME 'cold'
SETTINGS storage_policy = 'hot_cold', index_granularity = 8192

**I use data part 20220614_33277_41720_6 to explain what happened. this is the part log.**  

SELECT *
FROM system.part_log
WHERE part_name = '20220614_33277_41720_6'

Query id: 7b33dcc6-b96c-44ef-bf84-53f9c5edc323

Row 1:
──────
query_id:
event_type:              MergeParts
event_date:              2022-06-14
event_time:              2022-06-14 21:34:33
event_time_microseconds: 2022-06-14 21:34:33.210907
duration_ms:             4047597
database:                cloud_loghouse
table:                   gxinferencesd_local
part_name:               20220614_33277_41720_6
partition_id:            20220614
disk_name:               default
path_on_disk:            /home/service/var/clickhouse/data/data/cloud_loghouse/gxinferencesd_local/20220614_33277_41720_6/
rows:                    1366630549
size_in_bytes:           152335725406
merged_from:             ['20220614_33277_35557_5','20220614_35558_37758_5','20220614_37759_39583_4','20220614_39584_41720_4']
bytes_uncompressed:      3902888367452
read_rows:               1366630549
read_bytes:              2250536449205
peak_memory_usage:       115022401
error:                   0
exception:

Row 2:
──────
query_id:
event_type:              MovePart
event_date:              2022-06-15
event_time:              2022-06-15 08:01:29
event_time_microseconds: 2022-06-15 08:01:29.827456
duration_ms:             982596
database:                cloud_loghouse
table:                   gxinferencesd_local
part_name:               20220614_33277_41720_6
partition_id:            20220614
disk_name:               cfs
path_on_disk:            /mnt/cfs/data/cloud_loghouse/gxinferencesd_local/moving/20220614_33277_41720_6/
rows:                    1366630549
size_in_bytes:           152335725406
merged_from:             ['20220614_33277_41720_6']
bytes_uncompressed:      0
read_rows:               0
read_bytes:              0
peak_memory_usage:       0
error:                   84
exception:               Code: 84. DB::Exception: Part directory /mnt/cfs/data/cloud_loghouse/gxinferencesd_local/20220614_33277_41720_6/ already exists. (DIRECTORY_ALREADY_EXISTS) (version 22.3.6.5)

1. The data part was created at 2022-06-14 21:34:33
the directory /home/service/var/clickhouse/data/cloud_loghouse/gxinferencesd_local/20220614_33277_41720_6  was created.

2. Then start moving to cold disk in 2022-06-15 08:01:29.
/home/service/var/clickhouse/data/cloud_loghouse/gxinferencesd_local/20220614_33277_41720_6 move to
/mnt/cfs/data/cloud_loghouse/gxinferencesd_local/moving/20220614_33277_41720_6/

3. rename the /mnt/cfs/data/cloud_loghouse/gxinferencesd_local/moving/20220614_33277_41720_6/
to  /mnt/cfs/data/cloud_loghouse/gxinferencesd_local/20220614_33277_41720_6/

there is an exception in  third step;   i found that  step needs three small steps.
 a. copy xxx/moving/20220614_33277_41720_6 to  xxx/20220614_33277_41720_6
 b. fs::rename xxx/moving/20220614_33277_41720_6 to  xxx/delete_tmp_moving/20220614_33277_41720_6
 c. remove xxx/delete_tmp_moving/20220614_33277_41720_6.

 xxx/delete_tmp_moving is not created before and throw the  exception 'no such directory'.

**Comment by den-crane** [comment]
> nfs disk as cold disk。

Do you share files / folders using NFS among replicas?

**Comment by young-scott** [comment]
> 



> > nfs disk as cold disk。
> 
> Do you share files / folders using NFS among replicas?
> 
> Each replica must have own files / folders.

no, replicas do not share folders.  they use different space.

**Comment by young-scott** [comment]
this is my storage.xml 

`<yandex>
    <storage_configuration>
        <disks>
            <localdisk> 
                <path>/home/service/var/clickhouse/</path>
            </localdisk>
            <cos>
                <type>s3</type>
                <endpoint>xxxxxx/default_01_02/</endpoint>
                <access_key_id>xxxxx</access_key_id>
                <secret_access_key>xxxxx</secret_access_key>
                <connect_timeout_ms>10000</connect_timeout_ms>
                <request_timeout_ms>60000</request_timeout_ms>
                <retry_attempts>10</retry_attempts>
                <single_read_retries>4</single_read_retries>
                <min_bytes_for_seek>1000</min_bytes_for_seek>
            </cos>
            <cfs>
                <path>/mnt/cfs/</path>
            </cfs>
        </disks>
        <policies>
            <hot_cold_separation>
                <volumes>
                    <default>
                        <disk>default</disk>
                    </default>
                    <cold>
                        <disk>cos</disk>
                    </cold>
                </volumes>
            </hot_cold_separation>
            <hot_cold>
                <volumes>
                    <default>
                        <disk>default</disk>
                    </default>
                    <cold>
                        <disk>cfs</disk>
                    </cold>
                </volumes>
            </hot_cold>
        </policies>
    </storage_configuration>
</yandex>
`

**Comment by young-scott** [comment]
sorry, we make a mistake. The nfs config is wrong。 we use the same user to aceess the nfs files, so the files are shared.  And i correct the nfs config and check logs later.
