### ISSUE TITLE
quantileExact(level)(column), how can I set level from other columns.

### ISSUE THREAD

**Issue by AngelLittleChaochao** [ClickHouse/ClickHouse#38077]
I need to calculate quantile on different levels, and the level is depend on other columns. 
For the simulated sql, the quantile level depends on **val** column. 

```
with (SELECT CAST(([0, 1, 2, 3], [0.1, 0.4, 0.7, 0.8]), 'Map(UInt8, String)')) AS map

select step, val, quantileExact(val)(number) as t
from (
select number%4 as step, map[step] as val, number from numbers(100)
)
group by step, val
```

But it has error, it seems the quantile level parameter must be a calculated value before the select query is executed.

ClickHouse version: 21.11.10

```
Code: 47. DB::Exception: Received from localhost:9000. DB::Exception: Missing columns: 'val' while processing query: 'val', required columns: 'val' 'val'. (UNKNOWN_IDENTIFIER)
(query: with (SELECT CAST(([0, 1, 2, 3], [0.1, 0.4, 0.7, 0.8]), 'Map(UInt8, String)')) AS map

select step, val, quantileExact(val)(number) as t
from (
select number%4 as step, map[step] as val, number from numbers(100)
)
group by step, val

)
```

Anyone knows how to solve this problem?

**Comment by alexey-milovidov** [comment]
If the set of possible levels is fixed, you can use `quantilesExact` function:

`SELECT quantilesExact(0.1, 0.2, 0.9, ..., 0.95, 0.99)(x)[level_idx] ...`

**Comment by AngelLittleChaochao** [comment]
> 



> If the set of possible levels is fixed, you can use `quantilesExact` function:
> 
> `SELECT quantilesExact(0.1, 0.2, 0.9, ..., 0.95, 0.99)(x)[level_idx] ...`

The possible values are not fixed, it is dynamically calculated.

**Comment by aseemk** [comment]
I've run into this too. My values are also dynamically calculated (using `generate_series` or `numbers`). Is there any workaround?

Ultimately, I'd like to produce a table of rows with two columns: percentile, and calculated value at that percentile. How can I achieve this without support for dynamic `level` in `quantile()`?
