### ISSUE TITLE
Use of any in materialized view is returning unexpected results

### ISSUE THREAD

**Issue by nsweeting** [ClickHouse/ClickHouse#38115]
**Describe the unexpected behaviour**

We currently are hitting a strange issue where a materialized view making use of `any` is returning incorrect values in highly specific contexts that are somewhat hard to reproduce.

**How to reproduce**

So far we've been unable to reproduce the issue within a test environment. It only manifests in production - which is all the more frustrating.

Currently - we are doing the following:

1. Many (100-200 - each around 120 MB) parquet files are written to a GCS bucket from an outside process.
2. As these files land - we're streaming them directly into a ClickHouse table via `FORMAT Parquet`. We have about 4 "writers" operating at a time. Lets call this table `table_a`. `table_a` has a structure like:

```
CREATE TABLE IF NOT EXISTS table_a (
  col_a UInt16,
  col_b UInt64,
  col_c UInt32,
  col_d UInt32,
  col_e UInt32,
  col_f Array(UInt8),
  col_g Array(Array(Nullable(UInt32)))
)
ENGINE = MergeTree()
ORDER BY (col_a, col_b, col_c)
```

3. We have a materialized view hooked up to this table which is writing to another table - lets call it `table_b`.

```
CREATE TABLE IF NOT EXISTS table_b (
  col_a UInt16,
  col_b UInt64,
  col_c UInt32,
  col_d UInt32,
  col_e UInt32,
  col_f Array(UInt8),
  col_g Array(Array(Nullable(UInt32))),
  col_h UInt64
)
ENGINE = SummingMergeTree()
ORDER BY (col_a, col_b, col_c, col_d)
```

And our materialized view:

```
CREATE MATERIALIZED VIEW IF NOT EXISTS table_b_mv
TO table_b
AS SELECT
  col_a,
  col_b,
  col_c,
  col_d,
  any(col_e) AS col_e,
  any(col_f) AS col_f,
  any(col_g) AS col_g,
  count() AS col_h
FROM table_a
GROUP BY
  col_a,
  col_b,
  col_c,
  col_d
```

As of now - our `col_e` in `table_b` is returning an incorrect value based on the values in `table_a`. In our case - we know that there is only ever 1 value for `col_e` based on the grouping of `col_a`, `col_b`, `col_c` and `col_d`. 

```
SELECT DISTINCT col_e
FROM table_a
WHERE (col_a = 1) AND (col_b =2) AND (col_c = 3) AND (col_d = 4)

┌─col_e─┐
│ 79427 │
└───────┘
```

My expectation would be that `col_e` in `table_b` would then only contain value `79427` - but that is not whats happening.

```
SELECT DISTINCT col_e
FROM table_b
WHERE (col_a = 1) AND (col_b = 2) AND (col_c = 3) AND (col_d = 4)

┌──col_e─┐
│ 158854 │
└────────┘
┌──col_e─┐
│ 873697 │
└────────┘
```

This behaviour IS NOT present for `col_f` and `col_g` (the array types) in `table_b` though.

```
SELECT DISTINCT col_f
FROM table_a
WHERE (col_a = 1) AND (col_b = 2) AND (col_c = 3) AND (col_d = 4)

┌─col_f──────────────────────────────────────────────────────────────────────────┐
│ [1615,1583,1581,1942,1974,1948,1947,924,1679,853,854,1584,1582,1589,1587,1628] │
└────────────────────────────────────────────────────────────────────────────────┘
```

Which is an exact match as `table_b`.

```
SELECT DISTINCT col_f
FROM table_b
WHERE (col_a = 1) AND (col_b = 2) AND (col_c = 3) AND (col_d = 4)

┌─col_a──────────────────────────────────────────────────────────────────────────┐
│ [1615,1583,1581,1942,1974,1948,1947,924,1679,853,854,1584,1582,1589,1587,1628] │
└────────────────────────────────────────────────────────────────────────────────┘
```

**Expected behavior**

My expectation is that `col_e` in `table_b` would only contain the value `79427` based on the materialized view using `any(col_e)`. Is my assumption correct?

**Additional context**

We've tested inserting additional rows into `table_a` with different values for `col_e` and they show up correctly in `table_b`. We've also tested streaming a few of these parquet files at once in tests and got the correct values. So the issue seems to only manifest when streaming many files with many rows (200k-300k) at once.

```
SELECT VERSION()

┌─version()─┐
│ 22.3.6.5  │
└───────────┘
```

**Comment by den-crane** [comment]
https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/summingmergetree/

_If columns not specified, ClickHouse **summarizes the values in all columns with a numeric data type** that are not in the primary key._

solution is `SimpleAggregateFunction(any)`
Also check https://den-crane.github.io/Everything_you_should_know_about_materialized_views_commented.pdf (materialized view is not aware about the table_b engine. table_b (SummingMergeTree) is not aware about Mat.View.

```sql
CREATE TABLE IF NOT EXISTS table_b (
  col_a UInt16,
  col_b UInt64,
  col_c UInt32,
  col_d UInt32,
  col_e SimpleAggregateFunction(any,UInt32), -------<<<<<<<<<--
  col_f Array(UInt8),
  col_g Array(Array(Nullable(UInt32))),
  col_h UInt64
)
ENGINE = SummingMergeTree()
ORDER BY (col_a, col_b, col_c, col_d)
```

Also I suggest to use `SimpleAggregateFunction(any` for all measurements in this case (it's more clear syntax).

```sql
CREATE TABLE IF NOT EXISTS table_b (
  col_a UInt16,
  col_b UInt64,
  col_c UInt32,
  col_d UInt32,
  col_e SimpleAggregateFunction(any,UInt32), 
  col_f SimpleAggregateFunction(any,Array(UInt8)),
  col_g SimpleAggregateFunction(any,Array(Array(Nullable(UInt32)))),
  col_h UInt64
)
ENGINE = SummingMergeTree()
ORDER BY (col_a, col_b, col_c, col_d)
```
