### ISSUE TITLE
asynchronous_metric_log: `value Float64 CODEC(Gorilla, ZSTD(3))` is worse than simply `ZSTD(3)`

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#38134]
Maybe all the specialized codecs: DoubleDelta, Gorilla, etc. are obsolete and people should simply use ZSTD instead.

**Comment by filimonov** [comment]
> DoubleDelta, Gorilla, etc.

I don't think they should be used with zstd. 

Those 2 do compression by thier own.

https://kb.altinity.com/altinity-kb-schema-design/codecs/codecs-speed/

**Comment by alexey-milovidov** [comment]
@filimonov Compression of DoubleDelta and Gorilla is too low - they are not pareto-optimal.

**Comment by alexey-milovidov** [comment]
Gorilla may be ok, but I don't recommend it to a random user, as it's a specialized codec. More potential for misuse.
People can be misguided even by the existence of this codec. They may think that it's something advanced and good and start to misuse it. While ZSTD is both good and fast and you can always use it.

**Comment by filimonov** [comment]
It very depends on the data. In the example (see link above) both gorilla and doubledelta compressed the data better (without extra compressiom) comparing to ZSTD(1). Gorilla was also faster, while double Delta was a bit slower.

**Comment by filimonov** [comment]
And yes, decision which CODEC is the best is non always obvious (even for me)
