### ISSUE TITLE
IN vs JOIN performance

### ISSUE THREAD

**Issue by sridhard** [ClickHouse/ClickHouse#38140]
Hi,

I am trying to find the count of users who have not purchased any course. I have tried 2 methods to find this information.

1. select count(*) as count,school_id from users where users.id not in (select user_id from user_courses) group by school_id order by count desc
2. select count(*) as count, users.school_id from users left anti join user_courses on users.id=user_courses.user_id group by users.school_id order by count desc

First is using IN query. 2nd is using LEFT ANTI JOIN
IN query takes 0.414 secs and LEFT ANTI JOIN takes 0.620 seconds.

In databases like mysql use of IN query is not suggested because it does not use indexes.

How it works in clickhouse? why IN query performance is better than JOIN performance?

**Comment by vdimir** [comment]
cc @devcrafter

**Comment by den-crane** [comment]
@sridhard check this trick https://gist.github.com/den-crane/fb1108e4843250a71bac7528a79700c2

**Comment by den-crane** [comment]
There is a trick to leverage an index if one table is small
https://gist.github.com/den-crane/fb1108e4843250a71bac7528a79700c2

**Comment by alexey-milovidov** [comment]
IN is always better.
