### ISSUE TITLE
Does CH Console support defining variables?

### ISSUE THREAD

**Issue by Jack012a** [ClickHouse/ClickHouse#3815]
`:) select name from default.MyTable where timestamp=(select max(timestamp) from default.MyTable where date='2018-12-11') limit 1`

Here, the table name needs to be repeated twice. Is there a way that I can define the tablename as a variable?
Similar as follows[fake code]:

```
:) tablename=MyTable
:) select name from default.$tablename 
where timestamp=(select max(timestamp) from 
default.$tablename where date='2018-12-11') limit 1
```

Thank you

**Comment by blinkov** [comment]
There's a `WITH` clause https://github.com/yandex/ClickHouse/blob/master/dbms/tests/queries/0_stateless/00490_with_select.sql , but it has limitations that prevent its usage in specifically your case.

**Comment by jangorecki** [comment]
Could we remove `queston` label and add `feature request` instead? I would find that useful to create scripts that can be easily customised for table name to query from.

**Comment by selitsky** [comment]
> There's a `WITH` clause https://github.com/yandex/ClickHouse/blob/master/dbms/tests/queries/0_stateless/00490_with_select.sql , but it has limitations that prevent its usage in specifically your case.

WITH clause only work in particular select, but not inside subqueries.

**Comment by amosbird** [comment]
There is now custom settings which can be utilized but in a somehow contorted way.  https://github.com/ClickHouse/ClickHouse/blob/master/tests/queries/0_stateless/01418_custom_settings.sql

**Comment by jangorecki** [comment]
@amosbird thanks, that looks promising and flexible enough to address cases mentioned by me above. Do you have any idea how can I declare variables (`SET custom_a = 5;`) from command line just before running script? Or if there is `getSetting`'s style way to access environment variables?
Without passing the variable from parent process I still have to substitute script before running it.

**Comment by amosbird** [comment]
> Without passing the variable from parent process I still have to substitute script before running it.

Aren't env vars expanded by shells automatically? You can build a `sql.sh` which exports all your needed variables to ClickHouse.

`SELECT getEnv('ENVVAR1')` will be far away from your expectation as the SQL is running on the server-side.

Nevertheless, `getSetting` is limited. You cannot use it to substituted a table name, neither can those settings live out of current session.

**Comment by jangorecki** [comment]
Agree, although my client is running on same machine as server. Could you please point to a documentation that describes how to export all needed env vars so I can use them inside sql script?

**Comment by amosbird** [comment]
It's just bare shell interpolation.

```bash
sql_prelude="
set custom_foo=$foo;
set custom_bar=$bar;
"
query=...
clickhouse client --query "$sql_prelude $query"
```

**Comment by jangorecki** [comment]
and when I use sql script rather thn query?
```sh
cat "clickhouse/task-clickhouse.sql" | clickhouse-client ...
```
I have to still substitute vars in sql having `.sql.in` template script, isn't it?

**Comment by amosbird** [comment]
Then you'd better use https://clickhouse.tech/docs/en/interfaces/cli/#cli-queries-with-parameters

**Comment by jangorecki** [comment]
@amosbird could you provide an example how `--param_VAR` would address my use case provided above, to replace table name?
```sh
clickhouse-client --param_TBL="my_table" -q "SELECT * FROM {TBL:String}"
```
doesn't seem to work

**Comment by amosbird** [comment]
It's because ParserTableExpression doesn't take query parameters into account. 

 https://github.com/ClickHouse/ClickHouse/blob/master/src/Parsers/ParserTablesInSelectQuery.cpp#L20
https://github.com/ClickHouse/ClickHouse/blob/master/src/Parsers/ExpressionElementParsers.cpp#L1479

Maybe you can try to extend it. It seems to be a valid use case.

**Comment by alexey-milovidov** [comment]
@amosbird We want to support substitution for identifiers in a form of `{tbl:Identifier}`.
It is almost easy to add, the only tricky part is that it should parse as parts of compound identifiers as well.
Examples:

`SELECT * FROM {tbl:Identifier}`
`SELECT * FROM db.{tbl:Identifier}`
`SELECT {column:Identifier} FROM table`
`SELECT table.{column:Identifier} FROM table`
`SELECT {tbl:Identifier}.{column:Identifier} FROM db.{tbl:Identifier}`

**Comment by aploium** [comment]
For those using Jetbrains' IDE such as PyCharm/DataGrip/Intelij, when you are running sql in console (as you doing exploration), the ide support sql User Parameters like
```sql
SELECT * FROM foo WHERE a=${foo};
```
when you execute, the IDE will pop up a dialog to let you fill the params
![image](https://user-images.githubusercontent.com/15957250/177580580-836c92c0-e145-4992-8113-fa16c8d2f558.png)

Actually, it's JB's generic params, not only for clickhouse, which can be customized too.
![image](https://user-images.githubusercontent.com/15957250/177581226-ee5ff2ce-c4ff-411d-b3d6-6b10002bb31d.png)

This does NOT affect your program, but just in the IDE itself.

**Comment by amosbird** [comment]
I guess this is completed by https://github.com/ClickHouse/ClickHouse/pull/39906

**Comment by jangorecki** [comment]
It could be, but I don't see an example usage there to substitute a table name by a parameter value. So far I don't think it qualifying to close this request.

**Comment by amosbird** [comment]
@jangorecki  

```
set param_x = 'some_table';
select * from {x:Identifier};
```

**Comment by jangorecki** [comment]
Does it work from command line, as the example presented above? If so then it will resolve my request.

**Comment by alexey-milovidov** [comment]
Yes.
