### ISSUE TITLE
Librdkafka update

### ISSUE THREAD

**Issue by racevedoo** [ClickHouse/ClickHouse#38151]
Hi all!

While trying to use librdkafka plugins (`plugin.library.paths` config) to enable some custom oauthbearer authentication, I hit the following error: `*** ../contrib/librdkafka/src/rdkafka.c:3841:rd_kafka_poll_cb: assert: !*"cant handle op type" ***` (full trace [here](https://gist.github.com/racevedoo/64562f6eaa0eb8a5121f2b3907f09615))

Looking at librdkafka, recent releases, a specific patch released with librdkafka 1.9.0 closes a related issue: https://github.com/edenhill/librdkafka/commit/bead2e4acc8f0723fa44d21451f85859d0da76e0.

My guess is that updating https://github.com/ClickHouse/librdkafka/ with the latest changes from https://github.com/edenhill/librdkafka should solve this issue.

Thoughts?

**Comment by racevedoo** [comment]
Update: I can confirm that applying https://github.com/edenhill/librdkafka/commit/bead2e4acc8f0723fa44d21451f85859d0da76e0 on top of Clickhouse's fork of librdkafka fixes this issue, I will submit a PR

**Comment by racevedoo** [comment]
PR submitted: https://github.com/ClickHouse/librdkafka/pull/5

**Comment by alexey-milovidov** [comment]
Ok. Please note that shared library plugins are extremely dangerous and are not supported by ClickHouse.
If you are using any plugins, it can compromise security and we will refuse to support it.
We will also going to forbid any usage of `dlopen` in the code and 3rd-party libraries, so any plugins will become defunct in one of the subsequent releases.

**Comment by tavplubix** [comment]
Updated in #38225
