### ISSUE TITLE
clickhouse start failed

### ISSUE THREAD

**Issue by zdyj3170101136** [ClickHouse/ClickHouse#38167]
i change the config file in /etc/clickhouse-server/config.xml to mv the data directory.
  

    <path>/home/data/clickhouse/</path>

    
    <tmp_path>/home/data/clickhouse/tmp/</tmp_path>`

Nohup could start it successfully.
`sudo nohup /usr/bin/clickhouse-server --config-file /etc/clickhouse-server/config.xml &`
But i wang to use service start it and fix some permission error:
`
sudo chown -R clickhouse.clickhouse /etc/clickhouse-server/
sudo chown -R clickhouse.clickhouse /home/data/clickhouse
sudo service clickhouse-server start
`
It start error:
<img width="1373" alt="截屏2022-06-17 下午12 35 53" src="https://user-images.githubusercontent.com/52686065/174225718-57bba72f-a4f9-43b9-aac8-ef3ef1632f1c.png">
and i could not find more information in log:
<img width="1379" alt="截屏2022-06-17 下午12 37 01" src="https://user-images.githubusercontent.com/52686065/174225828-00796984-1a7e-4096-917a-da028bd45fcc.png">

**Comment by qoega** [comment]
You can try to look in `/var/log/clickhouse-server/clickhouse-server.log` for more information

**Comment by alexey-milovidov** [comment]
You can also use

```
sudo clickhouse start
```

\- embedded init script, without systemd.
