### ISSUE TITLE
Date timezone not work as expected when inserting data

### ISSUE THREAD

**Issue by roccia** [ClickHouse/ClickHouse#38168]
I have a table 
``` 
CREATE TABLE metric_test
(

    `metric_name` String,

    `ts` Int64,

    `labels` Map(String,
 String),

    `value` Float64,

    `created_at` Date
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(created_at)
PRIMARY KEY (metric_name,
 ts,
 created_at)
ORDER BY (metric_name,
 ts,
 created_at)
TTL created_at + toIntervalMonth(1) TO VOLUME 'one_month',
 created_at + toIntervalMonth(3) TO VOLUME 'three_month',
 created_at + toIntervalMonth(6) TO VOLUME 'six_month',
 created_at + toIntervalYear(1) TO VOLUME 'one_year'
SETTINGS index_granularity = 8192
```
and insert data as:
<img width="740" alt="image" src="https://user-images.githubusercontent.com/5943684/174238581-2099bf82-9e8d-4aba-86da-c261633c2ee7.png">
The dataType `created_at` in `Row` struct is time.Time 
When I insert some data between `Friday, June 17, 2022 12:00:00 AM GMT+08:00 -- Friday, June 17, 2022 12:03:20 AM [GMT+08:00]`   (timestamp: 1655395200-- 1655395400)
Then query as:
```
select *, toDateTime(ts) as ts_date from lakecore_metrics lm
where metric_name in ('cpu_used_rate') and ts >= 1655395200 and ts <= 1655395400
order by ts desc limit 10; 
```
I got:
<img width="704" alt="image" src="https://user-images.githubusercontent.com/5943684/174240448-f0453242-4987-4ba2-ae56-c91b594a5f45.png">
`ts` is the actual time when data is collected, `created_at` is used for partition, as you can see the date of these two are not matched, no idea why `created_at` is not my timezone, at first I thought I'm not setting clickhouse-client config correctly, so I tried to set jdbc driver properties: `use_server_timezong=false, use_time_zone=Asia/Shanghai`, but still got the same result. I also tried to change the time location in the code abrove from just using `now = time.now()` to `now = time.Now().In(loc)` ,still not working.
it seems the `created_at` was set to wrong timezone when inserting
Query with 
```
WITH now() AS ts

SELECT

    timezone(),

    ts,

    toTimeZone(ts, 'UTC') AS ts_utc,

    toTypeName(ts),

    toTypeName(ts_utc),

    toUnixTimestamp(ts),

    toUnixTimestamp(ts_utc)

FORMAT Vertical;
```
I got 
<img width="376" alt="image" src="https://user-images.githubusercontent.com/5943684/174241679-ea5aa2c7-62f4-4628-aad4-55e6a4e71eab.png">
also I double checked linux system timezone , all been set to Asia/Shanghai.
So what am I missing here? how to fix it? any help could be useful, thanks!

**Comment by qoega** [comment]
1) You do not use DateTime in table schema. It is much easier not to do a mistake if it is a DateTime column with fixed timezone(I recommend `DateTime('UTC'`). Or at least add expected timezone in column name: `ts` -> `ts_utc`
2) Actually behaviour of DateTime without tz depends on server timezone. I have timezone UTC set in my server, but if I change this setting, toDateTime(0) will have different result. In this example if I will change my server timezone(it it set in the system or in server config) the result of `toDateTime(0)` will be `1970-01-01 08:00:00`

```
SELECT
    timezone(),
    toDateTime(0),
    toDateTime(0, 'UTC'),
    toDateTime(0, 'Asia/Shanghai')

Query id: 5c1ed4c9-6223-482a-91ed-ffbf3ace71e5

┌─timezone()─┬───────toDateTime(0)─┬─toDateTime(0, 'UTC')─┬─toDateTime(0, 'Asia/Shanghai')─┐
│ Etc/UTC    │ 1970-01-01 00:00:00 │  1970-01-01 00:00:00 │            1970-01-01 08:00:00 │
└────────────┴─────────────────────┴──────────────────────┴────────────────────────────────┘

```

I don't want to confuse you even more, but if you parse a sting representation in toDateTime it would consider that you pass the destination tz.

```
SELECT
    '2022-06-17 12:00:00' AS str,
    toDateTime('2022-06-17 12:00:00') AS a,
    toDateTime('2022-06-17 12:00:00', 'UTC') AS b,
    toDateTime(str, 'Asia/Shanghai'),
    toDateTime(a, 'Asia/Shanghai'),
    toDateTime(b, 'Asia/Shanghai')

Query id: 9b4b3d36-1792-4874-8cab-c78e79d72acf

┌─str─────────────────┬───────────────────a─┬───────────────────b─┬─toDateTime('2022-06-17 12:00:00', 'Asia/Shanghai')─┬─toDateTime(toDateTime('2022-06-17 12:00:00'), 'Asia/Shanghai')─┬─toDateTime(toDateTime('2022-06-17 12:00:00', 'UTC'), 'Asia/Shanghai')─┐
│ 2022-06-17 12:00:00 │ 2022-06-17 12:00:00 │ 2022-06-17 12:00:00 │                                2022-06-17 12:00:00 │                                            2022-06-17 20:00:00 │                                                   2022-06-17 20:00:00 │
└─────────────────────┴─────────────────────┴─────────────────────┴────────────────────────────────────────────────────┴────────────────────────────────────────────────────────────────┴───────────────────────────────────────────────────────────────────────┘
```
But if you pass integer instead of a string it is considered in server tz.
```
SELECT
    '2022-06-17 12:00:00' AS str,
    1655467200 AS int,
    toDateTime(str) AS a,
    toDateTime(int) AS b,
    toDateTime(str, 'Asia/Shanghai'),
    toDateTime(int, 'Asia/Shanghai'),
    toDateTime(a, 'Asia/Shanghai')

Query id: 60a34a90-0804-4ab6-accf-708d06ef652c

┌─str─────────────────┬────────int─┬───────────────────a─┬───────────────────b─┬─toDateTime('2022-06-17 12:00:00', 'Asia/Shanghai')─┬─toDateTime(1655467200, 'Asia/Shanghai')─┬─toDateTime(toDateTime('2022-06-17 12:00:00'), 'Asia/Shanghai')─┐
│ 2022-06-17 12:00:00 │ 1655467200 │ 2022-06-17 12:00:00 │ 2022-06-17 12:00:00 │                                2022-06-17 12:00:00 │                     2022-06-17 20:00:00 │                                            2022-06-17 20:00:00 │
└─────────────────────┴────────────┴─────────────────────┴─────────────────────┴────────────────────────────────────────────────────┴─────────────────────────────────────────┴────────────────────────────────────────────────────────────────┘
```

3) Date data type also supports timezones. It converts your timestamp to date time of a given timezone and then converts to date.

```
SELECT
    '2022-06-17 18:00:00' AS str,
    1655488800 AS int,
    toDateTime(str) AS a,
    toDateTime(int) AS b,
    toDateTime(str, 'Asia/Shanghai'),
    toDateTime(int, 'Asia/Shanghai'),
    toDateTime(a, 'Asia/Shanghai'),
    toDate(int),
    toDate(int, 'UTC'),
    toDate(str, 'UTC'),
    toDate(int, 'Asia/Shanghai'),
    toDate(int, 'Asia/Shanghai'),
    toDate(a, 'Asia/Shanghai')

Query id: da473dc5-cfe4-4516-9b46-8d2d8bc3cc08

Row 1:
──────
str:                                                            2022-06-17 18:00:00
int:                                                            1655488800
a:                                                              2022-06-17 18:00:00
b:                                                              2022-06-17 18:00:00
toDateTime('2022-06-17 18:00:00', 'Asia/Shanghai'):             2022-06-17 18:00:00
toDateTime(1655488800, 'Asia/Shanghai'):                        2022-06-18 02:00:00
toDateTime(toDateTime('2022-06-17 18:00:00'), 'Asia/Shanghai'): 2022-06-18 02:00:00
toDate(1655488800):                                             2022-06-17
toDate(1655488800, 'UTC'):                                      2022-06-17
toDate('2022-06-17 18:00:00', 'UTC'):                           2022-06-17
toDate(1655488800, 'Asia/Shanghai'):                            2022-06-18
toDate(1655488800, 'Asia/Shanghai'):                            2022-06-18
toDate(toDateTime('2022-06-17 18:00:00'), 'Asia/Shanghai'):     2022-06-18

```

**Comment by roccia** [comment]
@qoega  thanks for such detailed explaintation, I did solve this issue by forcing the tz of `created_at` to UTC in the code like: 
<img width="808" alt="image" src="https://user-images.githubusercontent.com/5943684/174467548-cc0f296e-44f1-4621-ba26-06ec671f6cce.png">
the reason I used Date datatype for `created_at` is to do the table partition, last time I use `partition by toYYYYMM(toDateTime(intDiv(ts,1000)))
`  but it did not work, the partitions I have are 
![image](https://user-images.githubusercontent.com/5943684/174467626-6ba50ab6-4546-427f-b769-f219c7d09666.png).  

I also have another question about TTL, as you can see I set 4 ttls, one_month,three_month,six_month,one_year, is this necessary? 
I checked the folder size
![image](https://user-images.githubusercontent.com/5943684/174467723-4a6bbccf-2b69-41a4-9120-a8833ebca991.png)
why one_year is much bigger than others ,but six_month only have 200k, I thought the data size for one_month to one_year should be incremental
