### ISSUE TITLE
ClickHouse keeper not loading configurations

### ISSUE THREAD

**Issue by BenjaminDoctolib** [ClickHouse/ClickHouse#38189]
Hi,

I have been trying to start up clickhouse cluster with 3 nodes clickhouse and 3 clickhouse keeper nodes. I haven't got any problems on clickhouse nodes as we used it previously with Zookeeper. However, we got some problems for ClickHouse keeper. The thing is that ClickHouse keeper kept ignoring our file conf. We put the file conf in the /etc/clickhouse-server/config.d/keeper_config.xml. What happens is that clickhouse look for conf file in /etc/clickhouse-server/ as the default file config.xml is in there. Then if it doesn't find the conf file it loads default config on each server and thus assigning the id 1 to ALL servers. Then it loads the conf file that we put inside the config.d file and only check for rafts configuration but does not check for server id. We end up having all our servers with id 1 and we have 3 standalone clickhouse keeper instead of 1 cluster.

We had to put our conf file into the /etc/clickhouse/ to make it work properly. I don't know if this is a wanted behavior but it seems like a bug to me.

Regards

**Comment by den-crane** [comment]
Do you use Keepeer as embedded process or do you run it as a service? If you put some `xml` into `/etc/clickhouse-server/` then this xml will be used by clickhouse-server and this clickhouse-server will start a keeper as an embedded sub-process.

**Comment by BenjaminDoctolib** [comment]
Hi,

Sorry, but I'm not quite sure of what you mean by embedded or as a service but the way we start it is from a terraform with the following command (on each server)
`sudo clickhouse-keeper --config /etc/clickhouse-server/config.d/keeper_config.xml`
As we put the keeper_config.xml in the /etc/clickhouse-server/ as well it now process the `<server_id>` properly but before then all server_id where set to 1 by default and /config.d/keeper_config.xml server_id part was ignored

I was also wondering as I didn't see it in the 2022 roadmap if it was planned to add some management command such as clickhouse-keeper stop/start/status because so far I didn't find any convenient way to stop clickhouse-keeper and all its process.

Regards

**Comment by den-crane** [comment]
Do you share a server with clickhouse-server and clickhouse-keeper ?

**Comment by BenjaminDoctolib** [comment]
Nope, we have 3 distincts clickhouse servers and 3 distinct clickhouse keeper servers

Regards

**Comment by DanRoscigno** [comment]
@antonio2368 clickhouse server uses files in `/etc/clickhouse-server/config.d/` to modify the default config in `/etc/clickhouse-server/config.xml`.  Should Keeper do the same?

**Comment by antonio2368** [comment]
Keeper should already handle configs in the same way as CH server.
You specify the `xml` file as the main config and server/Keeper will look into that directory for the `config.d`. If no config file is set or specified in some way then just the embedded config will be used and no other files will be processed.
I.e. `config.d` is a supplement to a config file, if there is no file, nothing will be added.

**Comment by den-crane** [comment]
@antonio2368 

I tried to use config.d and it does not work.

I installed `clickhouse-keeper            23.7.5.30`
Installer has created `/etc/clickhouse-keeper/keeper_config.xml`

If I put my config into `/etc/clickhouse-keeper/config.d/keeper.xml`
Then keeper never reads this file.

I don't see mentions of it in `/var/log/clickhouse-keeper/clickhouse-keeper.log`

And it is not included into `/etc/clickhouse-keeper/keeper_config-preprocessed.xml`

clickhouse-server reads configs from relative folders (config.d/users.d/conf.d), but clickhouse-keeper does not.

I see that keeper is run
```
/usr/bin/clickhouse-keeper --config=/etc/clickhouse-keeper/keeper_config.xml --pid-file=/run/clickhouse-keeper/clickhouse-keeper.pid
```

So I would expect that keeper should read `/etc/clickhouse-keeper/config.d`

**Comment by den-crane** [comment]
>/etc/clickhouse-keeper/keeper_config.xml

aaaa, I realized that the problem that the file has to be named `config.xml` not keeper_config.xml

I file is named `config.xml` then XMLs from `conf.d` and `config.d` will be merged.

```
/etc/clickhouse-keeper/keeper_config.xml -- not OK
/etc/clickhouse-keeper/config.xml -- OK
```

**Comment by Felixoid** [comment]
does it actually work? https://github.com/ClickHouse/ClickHouse/blob/a4144b4fda3b559626af63751e49429b120a5a54/packages/clickhouse-keeper.service#L19C85-L19C85

**Comment by yukha-dw** [comment]
> > /etc/clickhouse-keeper/keeper_config.xml
> 
> aaaa, I realized that the problem that the file has to be named `config.xml` not `keeper_config.xml`
> 
> If file is named `config.xml` then XMLs from `conf.d` and `config.d` will be merged.
> 
> ```
> /etc/clickhouse-keeper/keeper_config.xml -- not OK
> /etc/clickhouse-keeper/config.xml -- OK
> ```

any plan to rename this? latest clickhouse-keeper still using keeper_config.xml

**Comment by den-crane** [comment]
it seems:

```
config.xml --> config.d

keeper_config.xml --> keeper_config.d

abc.xml --> abc.d
```

**Comment by antonio2368** [comment]
@den-crane that should be correct, also `conf.d` should be used regardless of the name of the main config file
