### ISSUE TITLE
[Question] why some parts always can't merged

### ISSUE THREAD

**Issue by lamber-ken** [ClickHouse/ClickHouse#3818]
hi, I create table partition by date, but I found that some parts always can't merged. 
example, except `20181118_4_8299_6_20602`, other parts can't merged. 
```
event_shard/20181118_4_8299_6_20602
event_shard/20181118_8300_16805_6_20602
event_shard/20181118_16806_18848_5_20602
event_shard/20181118_18849_20572_6_20602
event_shard/20181118_20573_20577_1_20602
event_shard/20181118_20578_20580_1_20602
```

**Comment by blinkov** [comment]
@lamber-ken you can run `SET optimize_throw_if_noop = 1;` and then https://clickhouse.yandex/docs/en/query_language/misc/#optimize will throw an exception with some explanation of why it doesn't want to merge anything (or will just do it).

**Comment by lamber-ken** [comment]
@blinkov , thanks very match. I'll your seggestion

**Comment by blinkov** [comment]
@lamber-ken, do you have any further questions?
