### ISSUE TITLE
Complete ClickHouse Keeper docs

### ISSUE THREAD

**Issue by DanRoscigno** [ClickHouse/ClickHouse#38188]
For ClickHouse Keeper we need:
- configuration with external and embedded clickhouse-keepers;
- setting up TLS connections for communication;
- optional authentication support.

Look at the ClickHouse Keeper reference docs, the MergeTree Replication guide, and the SRE guides and see what is missing.  

See ClickHouse/tests/integration/test_keeper_internal_secure/configs

**Comment by DanRoscigno** [comment]
TLS is here: https://clickhouse.com/docs/en/guides/sre/configuring-ssl/

**Comment by joshbartley** [comment]
Documentation for four letter commands for clickhouse keeper does not mention ssl/tls. Following the ssl guide you can't query keeper anymore.

**Comment by DanRoscigno** [comment]
> Documentation for four letter commands for clickhouse keeper does not mention ssl/tls. Following the ssl guide you can't query keeper anymore.

@joshbartley  do you have a Keeper system with TLS handy?  I think something like this might work.  I can't spin one up at the moment to test:


`echo "ruok" | openssl s_client -connect host:9181`

https://www.openssl.org/docs/man1.0.2/man1/openssl-s_client.html

cc: @e-mars

**Comment by e-mars** [comment]
Hi @joshbartley,

unfortunately the `echo` doesn't seem to work. 
for SSL, you can make the connection first:
if the SSL guide was followed, then in the example, i used port `9281`
```
root@chnode1:~# openssl s_client -connect chnode1.marsnet.local:9281
```
ensure that you have the certificate and chain defined locally

The connection should open displaying the cert info:
```
CONNECTED(00000003)
depth=0 CN = chnode1
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN = chnode1
verify error:num=21:unable to verify the first certificate
verify return:1
---
Certificate chain
 0 s:CN = chnode1
   i:CN = marsnet.local CA
---
Server certificate
-----BEGIN CERTIFICATE-----
MIICtDCCAZwCFD321grxU3G5pf6hjitf2u7vkusYMA0GCSqGSIb3DQEBCwUAMBsx
...
```

at the end of the output openssl is waits for the command in the client console, type in your 4LW:
```
...
---
mntr
```

it will display SSL negotiation info and at the end will be the output from it:
```
---
Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
...
read R BLOCK
zk_version      v22.7.3.5-stable-e140b8b5f3a5b660b6b576747063fd040f583cf3
zk_avg_latency  0
zk_max_latency  4087
zk_min_latency  0
zk_packets_received     4565774
zk_packets_sent 4565773
zk_num_alive_connections        2
zk_outstanding_requests 0
zk_server_state leader
zk_znode_count  1087
zk_watch_count  26
zk_ephemerals_count     12
zk_approximate_data_size        426062
zk_key_arena_size       258048
zk_latest_snapshot_size 0
zk_open_file_descriptor_count   187
zk_max_file_descriptor_count    18446744073709551615
zk_followers    2
zk_synced_followers     1
closed
```
thanks.

**Comment by DanRoscigno** [comment]
Thanks @e-mars I will update docs

**Comment by jaigopinathmalempati** [comment]
Hello @DanRoscigno  , looking out at similar issues connecting to clickhouse-keeper-client when TLS is enabled .

Getting the following error while trying to connect 

chkeeper-0:/# clickhouse-keeper client -p 9281 -q "get /keeper/config"
Coordination::Exception: All connection tries failed while connecting to ZooKeeper. nodes: [::1]:9281
Poco::Exception. Code: 1000, e.code() = 111, Connection refused (version 23.8.4.69 (official build)), [::1]:9281
Poco::Exception. Code: 1000, e.code() = 111, Connection refused (version 23.8.4.69 (official build)), [::1]:9281
Poco::Exception. Code: 1000, e.code() = 111, Connection refused (version 23.8.4.69 (official build)), [::1]:9281
