### ISSUE TITLE
Proper use of replace as an attribute in custom configuration XML files

### ISSUE THREAD

**Issue by DanRoscigno** [ClickHouse/ClickHouse#38202]
I have seen different ways of replacing configuration items, all of these work, but i have some questions:
- does it matter what value I assign to `replace`?  Below there are `1`, `replace`, and `true` that I found. From looking at src/Common/Config/ConfigProcessor.cpp I think that it does not matter what the value is.  Is that correct?
- I do not understand `incl="networks"` in the example below. Does this change the processing, or does it do the same as if `incl="networks"` was not there?   

`replace="1"`
```
<session_timeout_ms replace="1">3000</session_timeout_ms>```
```

`incl="networks" replace="replace"`
```
<networks incl="networks" replace="replace">
    <ip>::/0</ip>
</networks>```
```

`replace="replace"`
```
<user_directories replace="replace">
    <users_xml>
        <path>users.xml</path>
    </users_xml>
    <local_directory>
        <path>access/</path>
    </local_directory>
</user_directories>
```

`replace="true"`
```
<user_directories replace="true">
```

**Comment by alexey-milovidov** [comment]
> does it matter what value I assign to replace? Below there are 1, replace, and true that I found.

Does not matter.

> I do not understand incl="networks" in the example below.

To substitute from config.d files, you don't need `incl`.

Additional attributes can request substituting from other places:
- `from_zk` - substitute from ZooKeeper or ClickHouse Keeper - the contents of the node at the specified path in ZK;
- `from_env` - substitute from environment variable - the contents of the variable with the specified name;
- `incl` includes from the `include_from` file, `/etc/metrika.xml` by default - the contents of the element in the XML file (this is the oldest option, not used nowadays); if you don't have the `include_from` file, it is ignored.

Include attributes can be placed in the main and users configs, in dictionaries configs and in the config.d files as well. In the latter case, the includes will be substituted first, then the resulting elements will be substituted into the resulting configs.
