### ISSUE TITLE
how to solve the problem that the number of columns in TSV is inconsistent with the number of columns in database

### ISSUE THREAD

**Issue by shaojiankui** [ClickHouse/ClickHouse#38210]
When importing TSV, how to solve the problem that the number of columns in TSV is inconsistent with the number of columns in database. I have a big TSV file. I have five columns, and I have five columns in my database. But occasionally a row in the TSV will have six or four columns. This will cause the import to terminate.

**Comment by den-crane** [comment]
You have 2 options: 
1) Use https://clickhouse.com/docs/en/interfaces/formats/#tabseparatedwithnames https://clickhouse.com/docs/en/interfaces/formats/#tabseparatedwithnames
2) Mention inserted columns in insert `insert into table_name(col1, col2, .... col5) format TSV`

**Comment by shaojiankui** [comment]
` cat /test.txt | awk '
     BEGIN { found = 0;}
        {found = gsub(/\t/,"&"); }
        {
            if (found==4) {
                printf "%s\n", $0;
            } else {
                next;
            }
        }
' |clickhouse-client --query="INSERT INTO test FORMAT TabSeparated"
`

**Comment by shaojiankui** [comment]
tsv:
dev.java.	172800	in	ns	ns1.p04.dynect.net.	xxxxx.	zzzz
de333.java.	in	ns	ns3.p04.dynect.net.
dev.java.	172800	in	ns	ns4.p04.dynect.net.
go-stage.java.	172800	in	ns	a1-198.akam.net.
0-1.app.	10800	in	ns	pdns2.registrar-servers.com.

cat /test.txt | clickhouse-client  -n --input_format_skip_unknown_fields=1 --query="INSERT INTO zone_data.com2(domain,tld,ns,svalue,stld) FORMAT TabSeparated"


Error on processing query: Code: 27. DB::ParsingException: Cannot parse input: expected '\n' before: '\txxxxx.\tzzzz\nde333.java.\tin\tns\tns3.p04.dynect.net.\ndev.java.\t172800\tin\tns\tns4.p04.dynect.net.\ngo-stage.java.\t172800\tin\tns\ta1-198.akam.net.\n0-1.app.\t10800\tin\tns\t': 
Row 1:
Column 0,   name: domain, type: String, parsed text: "dev.java."
Column 1,   name: tld,    type: String, parsed text: "172800"
Column 2,   name: ns,     type: String, parsed text: "in"
Column 3,   name: svalue, type: String, parsed text: "ns"
Column 4,   name: stld,   type: String, parsed text: "ns1.p04.dynect.net."
ERROR: Tab found where line feed is expected. It's like your file has more columns than expected.
And if your file has the right number of columns, maybe it has an unescaped tab in a value.
  

Why doesn't input_format_skip_unknown_fields solve this problem。I don't think a few column errors should affect the import process。

**Comment by den-crane** [comment]
`input_format_skip_unknown_fields` is only for formats with named columns JSONEachRow, TSVWithNames, ....

**Comment by shaojiankui** [comment]
Is it possible to add a configuration similar to skip_ illeg_fields to solve the problem of a few illegal rows in a large amount of data? Instead of reporting an error stop
