### ISSUE TITLE
Special release to include window function expressions?

### ISSUE THREAD

**Issue by andrea-s** [ClickHouse/ClickHouse#38228]
Given the importance of https://github.com/ClickHouse/ClickHouse/pull/37848, is there any plan to release an extra version this month (which could be just 22.6 plus this PR)? I'm sure a lot of people have been waiting for it with great anticipation.

Just to know - otherwise I'll learn how to build from source ;-)

**Comment by alexey-milovidov** [comment]
Yes, it's already released, install as folowing:

```
curl https://clickhouse.com/ | sh
```
