### ISSUE TITLE
Huawei's OBS has a problem.

### ISSUE THREAD

**Issue by arunmarathe** [ClickHouse/ClickHouse#38234]
I observed a strange issue for partitioned Parquet files.

When I create a non-partitioned Parquet file, and create an S3 table on top of it, I can query it by issuing "select count(*) from table_name".

However, when I do the same exercise for a partitioned table, the count(*) query returns:

arunm-testvm :)         select count(*) from orders;

```
SELECT count(*)
FROM orders

Query id: 73a39de0-6b18-4b6e-9e13-947b5b94b220


0 rows in set. Elapsed: 0.843 sec.

Received exception from server (version 22.5.1):
Code: 631. DB::Exception: Received from localhost:9000. DB::Exception: Cannot find out size of file: While executing ParquetBlockInputFormat: While executing OBS. (UNKNOWN_FILE_SIZE)
```

Am I doing something wrong, or is this a bug?

Here is the CREATE TABLE statement for the partitioned orders table:

```
use tpch_100g_parquet;

CREATE TABLE orders (
    o_orderkey                UInt64,
    o_custkey                 UInt64,
    o_orderstatus             FixedString(1),
    o_totalprice              Decimal64(10),
    o_orderdate               Date,
    o_orderpriority           FixedString(15),
    o_clerk                   FixedString(15),
    o_shippriority            UInt32,
    o_comment                 String
)
ENGINE=S3('http://some_domain.com/arun/tpch/100G/partitioned/orders/o_orderdate%3D1992-02-18/2022*',
'access_key',
'secret_key', 'Parquet');
```

The orders table is partitioned by o_orderdate.

One more piece of information: the storage being accessed is Huawei's OBS storage, but I don't know how to access is using ClickHouse. I have been using S3 table engine to access OBS successfully so far.

Thanks,
Arun

**Comment by den-crane** [comment]
@arunmarathe try the same but with CSV format

**Comment by arunmarathe** [comment]
> @arunmarathe try the same but with CSV format

It works with CSV.

```
arunm-testvm :) select cselect count(*) from orders;

SELECT count(*)
FROM orders

Query id: 55c93d41-ea6c-4b31-bbee-8c71951a433a

┌───count()─┐
│ 150000000 │
└───────────┘

1 row in set. Elapsed: 22.793 sec. Processed 150.00 million rows, 21.40 GB (6.58 million rows/s., 938.66 MB/s.)

```

The orders table was defined as follows. Can you create partitioned CSV table with S3 engine (I am unsure)?

```
CREATE TABLE orders (
    o_orderkey       BIGINT not null,
    o_custkey        BIGINT not null,
    o_orderstatus    CHAR(1) not null,
    o_totalprice     DECIMAL(15,2) not null,
    o_orderdate      DATE not null,
    o_orderpriority  CHAR(15) not null,
    o_clerk          CHAR(15) not null,
    o_shippriority   BIGINT not null,
    o_comment        VARCHAR(79) not null,
    PRIMARY KEY (o_orderkey)
)
ENGINE=S3('http://obs.cn-north-5.myhuaweicloud.com/erie-obs-bucket/tpch/100G_csv/orders/*',
'access_key',
'secret_key', 'CSV')
SETTINGS format_csv_delimiter = '|';
```

**Comment by den-crane** [comment]
How did you insert data  into  Parquet table ?

**Comment by arunmarathe** [comment]
@den-crane:

The partitioned table was created as follows.

```
CREATE TABLE orders (
    o_orderkey                BIGINT,
    o_custkey                 BIGINT,
    o_orderstatus             CHAR(1),
    o_totalprice              DECIMAL(12,2),
    o_orderpriority           CHAR(15),
    o_clerk                   CHAR(15),
    o_shippriority            INTEGER,
    o_comment                 VARCHAR(79),
    o_orderdate               DATE
)
WITH (format='parquet', partitioned_by=array['o_orderdate'], external_location='obs://bucket-name/tpch/100G/partitioned/orders');
```

Then dbgen was used to create (synthetic) TPC-H data of which "orders" is a part.
Then the dbgen data in CSV format was converted to Parquet using a tool.
Then Huawei's "obs_util" program was used to copy the Parquet files to the partitioned tables (lineitem and orders).

Thanks,
Arun

**Comment by arunmarathe** [comment]
On a side note: @den-crane 

I use S3 to access obs data. I heard rumors that ClickHouse directly supports accessing Huawei's OBS. I tried the obvious method: using OBS( ....) instead of S3(....). That didn't work. Do you or someone have an OBS example handy? I couldn't find it in the documentation.
