### ISSUE TITLE
Remove `dlopen` and forbid its usage.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#38245]
`dlopen` should be only possible with `RTLD_SELF`.

### Motivation

Other usages are unsafe for several reasons:
- it allows to run third-party code in the process' address space, but this code has not been tested in CI by sanitizers and fuzzing;
- the external library can accidentally link to the symbols from the clickhouse binary which have different ABI, then everything will break;

dlopen prevents building a fully static binary. Currently, we are using statically linked libraries into the binary that requires the dynamic loader from glibc. But we want a fully static binary for the following reasons:
- it will simplify Alpine-based Docker images;
- separate images for small tools like clickhouse-client and clickhouse-keeper will become even smaller;
- we need to migrate to Musl;
- maybe we can use a single build for AArch64 Linux and [Android](https://clickhouse.com/blog/running-click-house-on-an-android-phone/);
- it will simplify cross-compilation for RISC-V;
- it looks better;

We need to migrate to Musl or LLVM's libc (if it will be ready) for the following reasons:
- it will be easier to put the source code of the libc into the main repository and compile it with the project, and it will simplify cross-compilation;
- we can modify the libc code to apply better testing, for example - randomization of time to prevent time bombs;
- we can modify the libc code to apply hardening, for example - eliminate harmful functions from the source code or apply some filesystem and network isolation on libc level, which is a good additional layer of defense;

### Remaining usages

The only remaining usage of `dlopen` is for loading [catboost](https://github.com/catboost/catboost) models. We should move it into clickhouse-library-bridge.

### Notes

ClickHouse already has full support for cross-compilation and hermetic reproducible builds. It is also distributed as a single binary that can work on almost any Linux (checked starting from Ubuntu 8.04 and CentOS 5). So, the main problems are already solved :)

**Comment by rschu1ze** [comment]
Looking into migrating catboost to library-bridge right now.

**Comment by filimonov** [comment]
clickhouse-odbc-bridge and library bridge will still be comiled against libc and will work?

Also i think some 3rd party libraries may have support to load some dynamic libs on demand. 

For example: https://blog.weghos.com/clickhouse/ClickHouse/contrib/librdkafka/src/rdkafka_plugin.c.html

But it is not mandatory, and should work / compile without

**Comment by alexey-milovidov** [comment]
@filimonov Yes, the bridges will be linked as usual.

About 3rd-party libraries and dlopen - this is what we want to prevent.
So, the loading of plugins by rdkafka will not work.

**Comment by rschu1ze** [comment]
Fixed with #41428 and #41429.
