### ISSUE TITLE
Code: 60, e.displayText() = DB::Exception: Table

### ISSUE THREAD

**Issue by huoarter** [ClickHouse/ClickHouse#38255]
When I delete table data, I often encounter problems
version:  20.3.15.133
query: alter table vip.al_ma_rpt_hive_vip_play_duration_income_local_ha delete where 1=1 settings mutations_sync=2;
engine: ReplacatedMergeTree 

![image](https://user-images.githubusercontent.com/17919074/174735710-a7f6605f-ed5b-4eb0-862a-824ab34e026d.png)

**Comment by genzgd** [comment]
This version of ClickHouse is out of support.  Please upgrade.  

In addition this is not enough information to provide any kind of answer.  Why do you believe the table exists?  Does it show in `SELECT * FROM system.tables`?  Is it a replicated table that exists on all nodes.
