### ISSUE TITLE
make max_table/partition_size_to_drop merge_tree setting

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#38250]
Make max_table/partition_size_to_drop merge_tree setting to be able to define for a table individually.

**Comment by den-crane** [comment]
Though malicious user will be able to change it with SQL.
But from other perspective they can use `alter table ... delete where 1` anyway.

**Comment by AVMusorin** [comment]
https://github.com/ClickHouse/ClickHouse/pull/57452

**Comment by azat** [comment]
Closed in https://github.com/ClickHouse/ClickHouse/pull/57452
