### ISSUE TITLE
Start Failed

### ISSUE THREAD

**Issue by wlkfec** [ClickHouse/ClickHouse#38266]
logs:

2022.06.21 18:23:31.054339 [ 14201 ] {} <Trace> BackgroundSchedulePool/BgSchPool: Waiting for threads to finish.
2022.06.21 18:23:31.057754 [ 14201 ] {} <Debug> MemoryTracker: Peak memory usage (for query): 11.42 KiB.
2022.06.21 18:23:31.057843 [ 14201 ] {} <Debug> Application: Shut down storages.
2022.06.21 18:23:32.011520 [ 14201 ] {} <Debug> Application: Destroyed global context.
2022.06.21 18:23:32.012257 [ 14201 ] {} <Error> Application: DB::Exception: Listen [::]:8123 failed: Poco::Exception. Code: 1000, e.code() = 0, DNS error: EAI: Address family for hostname not supported (version 22.6.1.1983 (official build))
2022.06.21 18:23:32.012292 [ 14201 ] {} <Information> Application: shutting down
2022.06.21 18:23:32.012303 [ 14201 ] {} <Debug> Application: Uninitializing subsystem: Logging Subsystem
2022.06.21 18:23:32.012405 [ 14202 ] {} <Trace> BaseDaemon: Received signal -2
2022.06.21 18:23:32.012466 [ 14202 ] {} <Information> BaseDaemon: Stop SignalListener thread
2022.06.21 18:23:32.062021 [ 14200 ] {} <Information> Application: Child process exited normally with code 70.

os version:
Linux version 3.10.0-862.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-28) (GCC) ) #1 SMP Fri Apr 20 16:44:24 UTC 2018

start command:
clickhouse install
clickhouse start

**Comment by thealexjo** [comment]
Please refer to this similar issue resolved earlier. It should answer your question:
https://github.com/ClickHouse/ClickHouse/issues/20965

**Comment by alexey-milovidov** [comment]
It happens, because the host system does not have IPv6 stack enabled,
while your configuration file has `::` as the listen-to address, and it is an IPv6 address.

**Comment by wlkfec** [comment]
I have modified the listening address in the configuration file, <listen_host>0.0.0.0</listen_host>, but still the same error
