### ISSUE TITLE
Remote Query: DB::NetException: Timeout: connect timed out

### ISSUE THREAD

**Issue by xpleaf** [ClickHouse/ClickHouse#38261]
I built ClickHouse clusters clusterA and clusterB in two different regions.

I was about to use ClickHouse's Remote query function to migrate data from clusterB to clusterA, but a rather strange problem occurred:
1. Port 9000 of the Telnet clusterB ClickHouse instance is reachable from clusterA. In addition, there is no problem connecting to clusterB machine through Python client on clusterA machine.

telnet: 
```
test@clusterA-ck01:~$ telnet clusterB-ck01 9000
Trying 192.168.56.101...
Connected to clusterB-ck01.
Escape character is '^]'.
^CConnection closed by foreign host.
```
Python Client:
```
test@clusterA-ck01:~$ python
>>> from clickhouse_driver import Client
>>> client = Client(host='clusterB-ck01', user='gac', password='*')
>>> 
>>> 
>>> client.execute('select count(*) from test_db.customer')
[(1000448,)]
```
2. However, WHEN I query the ClickHouse instance of clusterB via Remote on clusterA, I have a problem
```
clusterA-ck01 :) select * from remote('clusterB-ck01','test_db.customer','gac','*')
:-] 

SELECT *
FROM remote('clusterB-ck01', 'test_db.customer', 'gac', '*')

Query id: 7f693785-567f-48be-a8b4-ee298f43f579


0 rows in set. Elapsed: 0.164 sec. 

Received exception from server (version 21.8.3):
Code: 519. DB::Exception: Received from localhost:9000. DB::Exception: All attempts to get table structure failed. Log: 

Code: 279, e.displayText() = DB::NetException: All connection tries failed. Log: 

Code: 209, e.displayText() = DB::NetException: Timeout: connect timed out: 192.168.56.101:9000 (clusterB-ck01:9000) (version 21.8.3.44)
Code: 209, e.displayText() = DB::NetException: Timeout: connect timed out: 192.168.56.101:9000 (clusterB-ck01:9000) (version 21.8.3.44)
Code: 209, e.displayText() = DB::NetException: Timeout: connect timed out: 192.168.56.101:9000 (clusterB-ck01:9000) (version 21.8.3.44)
```

At present, I have no good idea to locate this problem. I have checked the network connection and firewall and found no problem (and AS I just described, Telnet can be connected, and python client can also be queried).

Are there any good ideas to solve this problem? Can provide some ideas to locate this problem, thank you very much!

**Comment by den-crane** [comment]
Connection timeout by default is 50ms!!! https://github.com/ClickHouse/ClickHouse/issues/5188

try 
```
set connect_timeout_with_failover_ms = 1000;

select * from remote('clusterB-ck01','test_db.customer','gac','*')
```

  --connect_timeout_with_failover_ms arg                                             Connection timeout for selecting first healthy replica.
  --connect_timeout_with_failover_secure_ms arg                                      Connection timeout for selecting first healthy replica (for secure connections).

**Comment by xpleaf** [comment]
Yes, it is caused by this. I changed this parameter to make it work:

```shell
clusterA-ck01 :) set connect_timeout_with_failover_ms = 1000;

SET connect_timeout_with_failover_ms = 1000

Query id: 81153e99-bdd5-4b6d-ae10-4f58d14b5d5a

Ok.

0 rows in set. Elapsed: 0.001 sec. 

clusterA-ck01 :) select count(*) from remote('clusterA-ck01','test_db.customer','gac','*')

SELECT count(*)
FROM remote('clusterA-ck01', 'test_db.customer', 'gac', '*')

Query id: f04c15a4-122f-4b7e-81c8-db7b9e73372c

┌─count()─┐
│ 1000448 │
└─────────┘

1 rows in set. Elapsed: 0.794 sec. 
```

I have a look at the network delay of the two areas, and it is indeed quite large:

```shell
test@clusterA-ck01:~$ ping clusterB-ck01
PING clusterB-ck01 (192.168.56.101) 56(84) bytes of data.
64 bytes from clusterB-ck01 (192.168.56.101): icmp_seq=1 ttl=64 time=131 ms
64 bytes from clusterB-ck01 (192.168.56.101): icmp_seq=2 ttl=64 time=131 ms
64 bytes from clusterB-ck01 (192.168.56.101): icmp_seq=3 ttl=64 time=131 ms
64 bytes from clusterB-ck01 (192.168.56.101): icmp_seq=4 ttl=64 time=131 ms
```

By the way, this timeout parameter is really too low, will the community consider increasing the default value of this parameter later?

**Anyway, thank you very much!**
