### ISSUE TITLE
Support for ALL_VALUES in IN clause

### ISSUE THREAD

**Issue by gingerwizard** [ClickHouse/ClickHouse#38263]
**Use case**

Users in Grafana can use [query variables](https://grafana.com/docs/grafana/latest/variables/variable-types/add-query-variable/) when constructing visualizations. These variables are substituted into queries. These variables are populated using a query and displayed as a multi-select. Users in turn select values, causing variables to be populated and SQL queries to be modified. In most cases, users use a query variable in an IN clause e.g.

`WHERE city IN (${cities})`

As well as supporting multi-select, users can also select an `All` value - effectively meaning the variable should not be populated OR populated with all values. We can populate the variable with all values, comma separating them. This introduces two issues:

1. Potentially very large IN clauses. Not ideal for performance.
2. The query populating the variable may not get all values in the first place - as Grafana recommends top 1000 values only. An incomplete dataset is, in turn, matched by selecting `All`.

**Describe the solution you'd like**

Support a special value for IN clause, which causes the IN to be optimized away. For example, 'where colA IN (ALL_VALUES)`

**Describe alternatives you've considered**

An AST in Grafana parses the query and removes the clause when `All` is selected. Current implementation - this is brittle.

**Additional context**

Consider https://github.com/ClickHouse/ClickHouse/issues/37918

cc @blinkov @ykahlon

**Comment by qoega** [comment]
Don't you think that there should be just one `if` in Grafana that will just remove `var IN ($values)` if there is no $values set?
Or user can write something like `WHERE (${values}='All') OR var IN (${values})`

**Comment by gingerwizard** [comment]
@qoega other ClickHouse plugins use macros, so Grafana knows where to remove the clause if `All` is set. users can also wrap in an If manually and have it substitute 1=1 for example if `All` is set. This is a poor user experience, however, and requires users to remember to insert these. We can do the macro approach as a stop gap but its not a good experience imo.

**Comment by alexey-milovidov** [comment]
> Support a special value for IN clause, which causes the IN to be optimized away. For example, 'where colA IN (ALL_VALUES)`

It looks strange.
Either you require pre-quoted string values like `'London'` or you cannot substitute ALL_VALUES correctly.

**Comment by alexey-milovidov** [comment]
I think we need to solve the problem in some other way.
