### ISSUE TITLE
Clickhouse doesn't use actual clickhouse-keeper configuration

### ISSUE THREAD

**Issue by vladkuzmich** [ClickHouse/ClickHouse#38270]
Hey, guys

At the moment I am setting up a CH cluster via **clickhouse-keeper**. Cluster consists of **4 nodes (EC2)**: 2 shards x 2 replicas.

Thus, in general, I have **4 nodes**, on **3 of which** I also launch **clickhouse-keeper**. A week ago I successfully set up this cluster, created **ReplicatedMergeeTree** & **Distibuted** tables and tested replication & sharding. So far so good, cluster is working as expected.

After the test I stopped all 4 nodes in AWS console, now I have started all nodes again to continue configuration, all nodes now have new IP addresses, so that I need to update configs:
-  **_/etc/clickhouse-server/confid.d/enable_keeper.xml_** (`<keeper_server></keeper_server>` section)
-  **_/etc/clickhouse-server/confid.d/use_keeper.xml_** (`<zookeeper></zookeeper>` section)
-  **_/etc/clickhouse-server/confid.d/remote_servers.xml_** (`<remote_servers></remote_servers>` section)

So, I updated all the configs on each node, BUT, when I try start **clickhouse** again it fails and in the logs I can see the reason - clickhouse still use old IP address (attached log picture)

In **_/var/lib/clickhouse/preprocessed_configs/config.xml_** I can see actual IPs.

May be it's due to fact that I created tables based on previous configuration. 

Sorry if it's not the issue at all and I'm doing something in wrong order/way. 

![log](https://user-images.githubusercontent.com/32732269/174801388-4e2890aa-c50b-49de-9922-92058d39ee4a.png)

**Comment by vladkuzmich** [comment]
Updated: fixed it by manually removing **/var/lib/clickhouse/coordination** directory on the nodes where keeper is enabled, but seems like it's not ideal.

**Comment by antonio2368** [comment]
The correct process in this case would be the one described here:
https://clickhouse.com/docs/en/operations/clickhouse-keeper/#recovering-after-losing-quorum

In short, cluster reconfiguration is possible with quorum because config is also replicated using RAFT.
You removed all the old nodes, so there are 0 nodes available for voting. To preserve the data, you need to force recovery with new config using the steps described above.

**Comment by vladkuzmich** [comment]
@antonio2368 Thank you so much, I will try in practice
It would be really really helpful if under this section in documentation - **User Guids** -> **SRE Guids** -> **Clickhouse Keeper** we can add a guid with testing some of this edge cases, e.g 1 clickhouse-keeper node down, 2 clickhouse-keeper node down (read only mode) and etc. similar like [here](https://mrkaran.dev/posts/clickhouse-replication/), because there are not many good guides regarding to **clickhouse-keeper**.

**Comment by antonio2368** [comment]
No problem! I agree, the documentation for Keeper is a bit rough now, but we are working on improving it, alongside the Keeper itself. So if you think something can be improved, even from the usability side like it is in this case feel free to create an issue. 😄
