### ISSUE TITLE
TTL Delete is performed multiple times in replication

### ISSUE THREAD

**Issue by Mall0c** [ClickHouse/ClickHouse#38271]
My setup is simple: three Clickhouse server and ReplicatedMergeTrees. The default merge_with_ttl_timeout is 4 hours, so TTL merges are scheduled every 4 hours. What I see, is that apparently they are executed three times. It takes them about 10-15 minutes, then after like 1-2 minutes, TTL DELETE merges are performed again, likely because server A schedules them, then server B schedules them and then server C. 

Expected behavior would be that only one server schedules them, since the TTL DELETE merges are perfomred on every server.

Clickhouse server version: 22.3.2.1

Does anyone notice this as well?

**Comment by rkozlo** [comment]
Here  #37324
