### ISSUE TITLE
Operation not permitted: While executing MergeTreeThread. (CANNOT_OPEN_FILE)

### ISSUE THREAD

**Issue by akshatknsl** [ClickHouse/ClickHouse#38281]
(you don't have to strictly follow this form)

We had a working database and all of a sudden, it has started responding to queries
When we do a count(*) it works, but select count it breaks, with below exception.

Code: 76. DB::Exception: Received from localhost:9000. DB::Exception: Cannot open file /var/lib/clickhouse/store/7d6/7d667bfe-d486-4b51-9910-6f9a7f091a93/all_10526_10526_0/data.bin, errno: 1, strerror: Operation not permitted: While executing MergeTreeThread. (CANNOT_OPEN_FILE)

Can someone please help, we have a production data on this instance.

**Comment by akshatknsl** [comment]
filesystem looks healthy and the permissions are proper, moreover its only some schemas which are giving problem, some of them are working fine.
Are there any chances of corruption?

**Comment by filimonov** [comment]
Can you open the file listed in the exception message with bash tools also as clickhouse user?

**Comment by filimonov** [comment]
For example

```
wc -c /var/lib/clickhouse/store/7d6/7d667bfe-d486-4b51-9910-6f9a7f091a93/all_10526_10526_0/data.bin

sudo clickhouse wc -c /var/lib/clickhouse/store/7d6/7d667bfe-d486-4b51-9910-6f9a7f091a93/all_10526_10526_0/data.bin
```

**Comment by akshatknsl** [comment]
Seeing this error in one more environment, all mentioned above seems to be working, still getting same error.

Received exception from server (version 22.3.7):
Code: 76. DB::Exception: Received from localhost:9000. DB::Exception: Cannot open file /data/var/lib/clickhouse/store/699/699902b4-25a6-4431-837d-5a0c816db0ed/202209_70923_70923_0/data.bin, errno: 1, strerror: Operation not permitted: While executing MergeTreeThread. (CANNOT_OPEN_FILE)

**Comment by j27bcn** [comment]
Same problem here, in latest version (23.4.2.11). In queries it gives the same error, but launching the same query several times complains about different files, and in the end, after launching the same query several times, it manages to respond correctly.
The file system is fine, and verifying all the files that it indicates cannot be opened, manually they are accessible with the user "clickhouse".

For example:
2023.05.19 10:46:15.648239 [ 2840 ] {86d1cd8c-f97f-4bcc-ae18-583b34b28f1d} <Error> executeQuery: Code: 76. DB::ErrnoException: Cannot open file /home/clickhouse/data/store/ea9/ea928042-6fb9-439b-8881-e7a951f1e0f7/20230513_708_708_0/fecha.mrk2, errno: 1, strerror: Operation not permitted: (while reading column fecha): (while reading from part /home/clickhouse/data/store/ea9/ea928042-6fb9-439b-8881-e7a951f1e0f7/20230513_708_708_0/ from mark 0 with max_rows_to_read = 65409): While executing MergeTreeThread. (CANNOT_OPEN_FILE) (version 23.4.2.11 (official build)) (from 127.0.0.1:37846) (in query: select date(fecha), count(*) from hfc group by 1 order by 1;), Stack trace (when copying this message, always include the lines below):

0. ./build_docker/./src/Common/Exception.cpp:91: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0xe3bb175 in /usr/lib/debug/usr/bin/clickhouse.debug
1. ./build_docker/./contrib/llvm-project/libcxx/include/string:1499: DB::ErrnoException::ErrnoException(String const&, int, int, std::optional<String> const&) @ 0xe3bbeb3 in /usr/lib/debug/usr/bin/clickhouse.debug
2. ./build_docker/./src/Common/Exception.cpp:0: DB::throwFromErrnoWithPath(String const&, String const&, int, int) @ 0xe3bc1f1 in /usr/lib/debug/usr/bin/clickhouse.debug
3. ./build_docker/./src/IO/OpenedFile.cpp:0: DB::OpenedFile::open() const @ 0x1269694a in /usr/lib/debug/usr/bin/clickhouse.debug
4. ./build_docker/./src/IO/OpenedFile.cpp:42: DB::OpenedFile::getFD() const @ 0x126969f4 in /usr/lib/debug/usr/bin/clickhouse.debug
5. ./build_docker/./src/IO/AsynchronousReadBufferFromFile.h:73: DB::AsynchronousReadBufferFromFileWithDescriptorsCache::AsynchronousReadBufferFromFileWithDescriptorsCache(DB::IAsynchronousReader&, int, String const&, unsigned long, int, char*, unsigned long, std::optional<unsigned long>, std::shared_ptr<DB::Throttler>) @ 0x1269635d in /usr/lib/debug/usr/bin/clickhouse.debug
6. ./build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:0: DB::createReadBufferFromFileBase(String const&, DB::ReadSettings const&, std::optional<unsigned long>, std::optional<unsigned long>, int, char*, unsigned long)::$_0::operator()(unsigned long, unsigned long, int) const @ 0x12693a04 in /usr/lib/debug/usr/bin/clickhouse.debug
7. ./build_docker/./src/Disks/IO/createReadBufferFromFileBase.cpp:223: DB::createReadBufferFromFileBase(String const&, DB::ReadSettings const&, std::optional<unsigned long>, std::optional<unsigned long>, int, char*, unsigned long) @ 0x1269359c in /usr/lib/debug/usr/bin/clickhouse.debug
8. ./build_docker/./src/Disks/DiskLocal.cpp:0: DB::DiskLocal::readFile(String const&, DB::ReadSettings const&, std::optional<unsigned long>, std::optional<unsigned long>) const @ 0x12ec0292 in /usr/lib/debug/usr/bin/clickhouse.debug
9. ./build_docker/./src/Storages/MergeTree/DataPartStorageOnDiskFull.cpp:0: DB::DataPartStorageOnDiskFull::readFile(String const&, DB::ReadSettings const&, std::optional<unsigned long>, std::optional<unsigned long>) const @ 0x1475d0c8 in /usr/lib/debug/usr/bin/clickhouse.debug
10. ./build_docker/./src/Storages/MergeTree/MergeTreeMarksLoader.cpp:0: DB::MergeTreeMarksLoader::loadMarksImpl() @ 0x14969e74 in /usr/lib/debug/usr/bin/clickhouse.debug
11. ./build_docker/./contrib/llvm-project/libcxx/include/__utility/swap.h:37: DB::MergeTreeMarksLoader::loadMarks() @ 0x1496930c in /usr/lib/debug/usr/bin/clickhouse.debug
12. ./build_docker/./contrib/llvm-project/libcxx/include/__utility/swap.h:37: DB::MergeTreeMarksLoader::getMark(unsigned long, unsigned long) @ 0x14968107 in /usr/lib/debug/usr/bin/clickhouse.debug
13. ./build_docker/./src/Storages/MergeTree/MergeTreeReaderStream.cpp:71: DB::MergeTreeReaderStream::init() @ 0x14990e61 in /usr/lib/debug/usr/bin/clickhouse.debug
14. ./build_docker/./src/Storages/MergeTree/MergeTreeReaderStream.cpp:275: DB::getStream(bool, DB::ISerialization::SubstreamPath const&, std::map<String, std::unique_ptr<DB::MergeTreeReaderStream, std::default_delete<DB::MergeTreeReaderStream>>, std::less<String>, std::allocator<std::pair<String const, std::unique_ptr<DB::MergeTreeReaderStream, std::default_delete<DB::MergeTreeReaderStream>>>>>&, DB::NameAndTypePair const&, unsigned long, bool, unsigned long, std::unordered_map<String, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>>&) @ 0x14996588 in /usr/lib/debug/usr/bin/clickhouse.debug
15. ./build_docker/./src/Storages/MergeTree/MergeTreeReaderWide.cpp:350: DB::ReadBuffer* std::__function::__policy_invoker<DB::ReadBuffer* (DB::ISerialization::SubstreamPath const&)>::__call_impl<std::__function::__default_alloc_func<DB::MergeTreeReaderWide::readData(DB::NameAndTypePair const&, std::shared_ptr<DB::ISerialization const> const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, bool, unsigned long, unsigned long, std::unordered_map<String, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>>&, bool)::$_3, DB::ReadBuffer* (DB::ISerialization::SubstreamPath const&)>>(std::__function::__policy_storage const*, DB::ISerialization::SubstreamPath const&) @ 0x14996927 in /usr/lib/debug/usr/bin/clickhouse.debug
16. ./build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:848: DB::ISerialization::deserializeBinaryBulkWithMultipleStreams(COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, DB::ISerialization::DeserializeBinaryBulkSettings&, std::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>&, std::unordered_map<String, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>>*) const @ 0x12de821e in /usr/lib/debug/usr/bin/clickhouse.debug
17. ./build_docker/./contrib/boost/boost/smart_ptr/intrusive_ptr.hpp:194: DB::MergeTreeReaderWide::readData(DB::NameAndTypePair const&, std::shared_ptr<DB::ISerialization const> const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, bool, unsigned long, unsigned long, std::unordered_map<String, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>>&, bool) @ 0x149953fb in /usr/lib/debug/usr/bin/clickhouse.debug
18. ./build_docker/./src/Storages/MergeTree/MergeTreeReaderWide.cpp:157: DB::MergeTreeReaderWide::readRows(unsigned long, unsigned long, bool, unsigned long, std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>&) @ 0x14994a5b in /usr/lib/debug/usr/bin/clickhouse.debug
19. ./build_docker/./src/Storages/MergeTree/MergeTreeRangeReader.cpp:106: DB::MergeTreeRangeReader::DelayedStream::finalize(std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>&) @ 0x149aa623 in /usr/lib/debug/usr/bin/clickhouse.debug
20. ./build_docker/./src/Storages/MergeTree/MergeTreeRangeReader.h:122: DB::MergeTreeRangeReader::startReadingChain(unsigned long, DB::MarkRanges&) @ 0x149b5849 in /usr/lib/debug/usr/bin/clickhouse.debug
21. ./build_docker/./src/Storages/MergeTree/MergeTreeRangeReader.cpp:0: DB::MergeTreeRangeReader::read(unsigned long, DB::MarkRanges&) @ 0x149b3043 in /usr/lib/debug/usr/bin/clickhouse.debug
22. ./build_docker/./src/Storages/MergeTree/MergeTreeBaseSelectProcessor.cpp:402: DB::IMergeTreeSelectAlgorithm::readFromPartImpl() @ 0x149a6cc8 in /usr/lib/debug/usr/bin/clickhouse.debug
23. ./build_docker/./src/Storages/MergeTree/MergeTreeBaseSelectProcessor.cpp:445: DB::IMergeTreeSelectAlgorithm::readFromPart() @ 0x149a7a51 in /usr/lib/debug/usr/bin/clickhouse.debug
24. ./build_docker/./src/Storages/MergeTree/MergeTreeBaseSelectProcessor.cpp:166: DB::IMergeTreeSelectAlgorithm::read() @ 0x149a4a78 in /usr/lib/debug/usr/bin/clickhouse.debug
25. ./build_docker/./src/Storages/MergeTree/MergeTreeSource.cpp:181: DB::MergeTreeSource::tryGenerate() @ 0x15125bf7 in /usr/lib/debug/usr/bin/clickhouse.debug
26. ./build_docker/./contrib/llvm-project/libcxx/include/optional:344: DB::ISource::work() @ 0x14d21da6 in /usr/lib/debug/usr/bin/clickhouse.debug
27. ./build_docker/./src/Processors/Executors/ExecutionThreadContext.cpp:0: DB::ExecutionThreadContext::executeTask() @ 0x14d3aa6a in /usr/lib/debug/usr/bin/clickhouse.debug
28. ./build_docker/./src/Processors/Executors/PipelineExecutor.cpp:255: DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x14d3073b in /usr/lib/debug/usr/bin/clickhouse.debug
29. ./build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:833: void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<DB::PipelineExecutor::spawnThreads()::$_0, void ()>>(std::__function::__policy_storage const*) @ 0x14d3246f in /usr/lib/debug/usr/bin/clickhouse.debug
30. ./build_docker/./base/base/../base/wide_integer_impl.h:789: ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0xe490475 in /usr/lib/debug/usr/bin/clickhouse.debug
31. ./build_docker/./src/Common/ThreadPool.cpp:0: void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, long, std::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0xe492cb5 in /usr/lib/debug/usr/bin/clickhouse.debug

The file is accesible:

-bash-4.2$ whoami
clickhouse
-bash-4.2$ wc /home/clickhouse/data/store/ea9/ea928042-6fb9-439b-8881-e7a951f1e0f7/20230513_708_708_0/fecha.mrk2^C
-bash-4.2$ ls -l /home/clickhouse/data/store/ea9/ea928042-6fb9-439b-8881-e7a951f1e0f7/20230513_708_708_0/fecha.mrk2
-rw-r--r-- 1 clickhouse clickhouse 528 May 19 08:36 /home/clickhouse/data/store/ea9/ea928042-6fb9-439b-8881-e7a951f1e0f7/20230513_708_708_0/fecha.mrk2
-bash-4.2$ wc /home/clickhouse/data/store/ea9/ea928042-6fb9-439b-8881-e7a951f1e0f7/20230513_708_708_0/fecha.mrk2
  0   7 528 /home/clickhouse/data/store/ea9/ea928042-6fb9-439b-8881-e7a951f1e0f7/20230513_708_708_0/fecha.mrk2
-bash-4.2$
