### ISSUE TITLE
Querying on a column that isn't part of primary key

### ISSUE THREAD

**Issue by a-dot** [ClickHouse/ClickHouse#38297]
I'm working with a table that has network related data and the queries are always for either the src_ip or the dst_ip. For example, select * from xyz where src_ip = a.b.c.d. The src_ip is the primary and queries are extremely fast. However, dst_ip is not. Not knowing much about query optimization I created a data skipping index for the dst_ip of type bloom_filter. It significantly improved the performance of queries but is no where near the performance I'm getting when querying for src_ip, the primary key. Is there a way to get similar performance as querying for the primary key when the queries revolve around two (or more?) columns? Thanks for your help!

**Comment by UnamedRus** [comment]
There is pr for that kind of task:
 https://github.com/ClickHouse/ClickHouse/pull/28130 

But it's still not done.

Which kind of IP's do you store? V4 or V6

**Comment by a-dot** [comment]
> ClickHouse is not designed for such tasks. The best you can do is to create one more table ordered by dst_ip and store and insert data twice. Another way is to use ORDER BY projection but it's such good solutions as the second table. How many columns in your table?

Only ~15 columns or so, it's netflow data so IP's, ports, protocol, bytes in/out, packets in/out that sort of thing.

**Comment by a-dot** [comment]
> There is pr for that kind of task: #28130
> 
> But it's still not done.
> 
> Which kind of IP's do you store? V4 or V6

There's a mix of 4 and 6 but all stored in the IPv6 type.

**Comment by den-crane** [comment]
expample with projection

```sql
CREATE TABLE test_a
(
    `src` String,
    `dst` String,
    `other_cols` String,
    PROJECTION p1
    (
        SELECT
            src,
            dst
        ORDER BY dst
    )
)
ENGINE = MergeTree
ORDER BY src;

insert into test_a select number, -number, 'other_col '||toString(number) from numbers(1e8);

select * from test_a where src='42';
┌─src─┬─dst─┬─other_cols───┐
│ 42  │ -42 │ other_col 42 │
└─────┴─────┴──────────────┘
1 row in set. Elapsed: 0.005 sec. Processed 16.38 thousand rows, 988.49 KB (3.14 million rows/s., 189.43 MB/s.)


select * from test_a where dst='-42';
┌─src─┬─dst─┬─other_cols───┐
│ 42  │ -42 │ other_col 42 │
└─────┴─────┴──────────────┘
1 row in set. Elapsed: 0.625 sec. Processed 100.00 million rows, 1.79 GB (160.05 million rows/s., 2.86 GB/s.)

-- optimization using projection
select * from test_a where src in (select src from test_a where dst='-42') and dst='-42';
┌─src─┬─dst─┬─other_cols───┐
│ 42  │ -42 │ other_col 42 │
└─────┴─────┴──────────────┘
1 row in set. Elapsed: 0.013 sec. Processed 32.77 thousand rows, 660.75 KB (2.54 million rows/s., 51.26 MB/s.)
```

>Elapsed: 0.625 sec. Processed 100.00 million rows
VS
>Elapsed: 0.013 sec. Processed 32.77 thousand rows
