### ISSUE TITLE
Hung check: slow JSON deserialization

### ISSUE THREAD

**Issue by tavplubix** [ClickHouse/ClickHouse#38305]
https://s3.amazonaws.com/clickhouse-test-reports/0/0b8fc627d80013c0288ddf5a7d91546a7d9d6264/stress_test__debug__actions_.html

Seems like `SerializationObject<DB::JSONDataParser<DB::SimdJSONParser> >::deserializeWholeText` may be too slow, so it triggers Hung Check in Stress Tests sometimes. Probably it's because of `getLeastSupertype`.

Query: https://pastila.nl/?030770f4/763c48c7ea794cfd4cb77f01c736978d
Stacktrace: https://pastila.nl/?0062e195/229dc868bd7bed9a75396eaf61cb3346

I would ignore it if it was the only failure, but there's another one with similar stacktrace:
https://s3.amazonaws.com/clickhouse-test-reports/0/0d80874d400e3591ba7aff05eaac970ca6e7ac49/stress_test__debug__actions_.html

Query: https://pastila.nl/?027b3a99/63002ee740e15dcedcd2412289337976
Stacktraces: https://pastila.nl/?0062e195/f08dd310bd9a5d608e8e55eda4fa6c39

**Comment by CurtizJ** [comment]
We can disable this test with debug build. With release build its execution takes 1.5 seconds.
