### ISSUE TITLE
Examples from doc page "Semi-Structured Approach" throw exception: "Not implemented for SerializationObject"

### ISSUE THREAD

**Issue by vibl** [ClickHouse/ClickHouse#38314]
Running this example from documentation page https://clickhouse.com/docs/en/guides/developer/working-with-json/json-semi-structured/ :
```sql
SELECT type, actor, repo FROM 
s3('https://datasets-documentation.s3.eu-west-3.amazonaws.com/github/github-2022.ndjson.gz', 
'JSONEachRow') LIMIT 2;
```
throws:
```
SQL Error [48] [07000]: Code: 48. DB::Exception: 
Not implemented for SerializationObject: 
While executing ParallelFormattingOutputFormat. (NOT_IMPLEMENTED) 
(version 22.7.1.391 (official build))
, server ClickHouseNode(addr=http:localhost:8123, db=my_db)@-1506010914
```
And so do all the examples following it, and the same queries with my own data.

I added the `allow_experimental_object_type` setting before executing these queries:
```sql
CREATE SETTINGS PROFILE allow_experimental_object_type SETTINGS allow_experimental_object_type = 1 TO default;
```

My need is schema inferrence for nested json fields.

Config is the default from fresh install.

**Comment by alexey-milovidov** [comment]
What client application do you use to run these queries?
Chances are this application does not support the new JSON type.

**Comment by vibl** [comment]
The queries indeed work in the clickhouse-client CLI.

I used DBeaver latest (v22.1), which uses clickhouse-jdbc v0.3.2. 

I've just upgraded to clickhouse-jdbc v0.3.2-patch9 and I get the same error.

Yet [v0.3.2-patch8](https://github.com/ClickHouse/clickhouse-jdbc/releases/tag/v0.3.2-patch8) release log says `initial support of experimental data type JSON/Object('JSON')`.

I've tried to install clickhouse-jdbc v0.3.2-patch10 but it's in pre-release in not in Maven Central yet, so I have to install it manually and I couldn't manage to do it. Also, it doesn't mention anything about JSON in https://github.com/ClickHouse/clickhouse-jdbc/releases/tag/v0.3.2-patch10). Is it still worth trying further to install it?

**Comment by zhicwu** [comment]
Hi @vibl, patch10 has been released and you can get shaded jar from either github or maven central.

Below case "works" for me on 22.6 - it produces no error but the result is not expected.

```sql
set allow_experimental_object_type = 1;
create table json_test(j JSON)engine=Memory;

insert into json_test format JSONEachRow
{ "j": { "a": 1, "b": { "c": null }  } }

insert into json_test(j) values( (1, (''))::Tuple(a Int8, b Tuple(c Nullable(String))) )

select * from json_test
```

**Comment by arniwesth** [comment]
I get the same error in ver `23.3.1.1087`

```
set allow_experimental_object_type = 1;
select '{"a": 1}'::JSON
```
results in
```
SQL Error [48] [07000]: Code: 48. DB::Exception: Not implemented for SerializationObject: While executing ParallelFormattingOutputFormat. (NOT_IMPLEMENTED) (version 23.3.1.1087 (official build))
, server ClickHouseNode [uri=http://xxx:8123/default, options={socket_timeout=3000000,use_server_time_zone=false,use_time_zone=false}]@1823626602
```

**Comment by metal450** [comment]
I'm still getting this error in 24.0.2; not sure why the issue was closed if it hasn't been fixed...

**Comment by alexey-milovidov** [comment]
It will never be fixed - we don't support the experimental Object type.
