### ISSUE TITLE
Create an option to limitation IO operations with remote storage.

### ISSUE THREAD

**Issue by ianton-ru** [ClickHouse/ClickHouse#38315]
ClickHouse has ability to use several types of remote storage - AWS S3, HDFS, MS Azure.
Providers of this storages may bill for every request or for traffic. Some manipulations with data on this storage can produce lots of operations and can have unexpectable cost in money.
Also in some cases this can produce huge load on network and/or storage.

When MergeTree table has a large part on remote storage, and user adds some data in this partition, ClickHouse merges this parts. For this large part loads form remote storage and merged large part uploads back, even when new portion of data is small.

When ClickHouse has this table on multiple shards and user add data in distributed table then every shard merges own portion of data. In this case all shards start merge in the same time, and network or remote storage can be overloaded.

ClickHouse has option **prefer_not_to_merge**, but with this option user starts to get error "Too many parts" in short time.

Is it possible to make some limit for operations?

It may be limits for RPS/traffic (may be separate settings for different kind of requests, at least for read and for write), better with ability to change limit on the fly (it will be useful for clusters with multiple host).

**Comment by ianton-ru** [comment]
@alesapin Yes, with ability to throttle requests from single host will be possible to manage total request rate with some kind of external script.

**Comment by serxa** [comment]
@ianton-ru Options have been added, please check if it is good enough for your purpose

**Comment by ianton-ru** [comment]
> @ianton-ru Options have been added, please check if it is good enough for your purpose

Yes, I think we can use it. Thank you!
