### ISSUE TITLE
Ability to restrict allowed table engines

### ISSUE THREAD

**Issue by Alex-Burmak** [ClickHouse/ClickHouse#38316]
**Use case**

As an admin of ClickHouse cluster I want to restrict creation of tables with particular table engines. In particular, I want to forbid usage of tables with Log engines because backup tools like https://github.com/AlexAkulov/clickhouse-backup do not support backuping data of such tables.

**Describe the solution you'd like**

A server setting with list of table engines that cannot be used.

**Comment by alesapin** [comment]
`set allowed_engines='MergeTree,ReplicatedMergeTree'`

**Comment by Alex-Burmak** [comment]
@alesapin, for cases when it's required to forbid one particular engine, it would be convenient to have `disallowed_engines` or `forbidden_engines`. Otherwise it will be required to specify very long list of supported engines and update it when upgrading ClickHouse versions.

**Comment by vitlibar** [comment]
I thought about implementing that as privileges:

```
GRANT SET TABLE ENGINE ON * TO john; <-- grant user john an ability to use any table engine when creating tables
REVOKE SET TABLE ENGINE ON Log TO john; <-- prohibit user john to create tables with the table engine Log
```

**Comment by alesapin** [comment]
@vitlibar Is it possible? How big this implementation will be?

**Comment by vitlibar** [comment]
> @vitlibar Is it possible? How big this implementation will be?

It's possible of course. And thanks to @kssenii and her PR https://github.com/ClickHouse/ClickHouse/pull/46241, now it must not be difficult.

**Comment by jsc0218** [comment]
If my understanding is correct, SET is session-wise, so GRANT approach is better.

**Comment by jsc0218** [comment]
I find it is easy to implement the approach of GRANT table engine, but there is an issue arising up. For existing users (not default) after the implementation, they have to get granted for the usage of their current table engine, which is not good since it is a change of existing user behavior. I am thinking of an approach of separation of table engines, some of them granted by default, others not. Still, the approach is not applicable to existing users since we cannot tell whether the user is created before or after the implementation.

**Comment by alexey-milovidov** [comment]
Let it be required for CREATE and ATTACH (only on table creation), but not checked on SELECT, DROP, etc...

**Comment by vitlibar** [comment]
> Let it be required for CREATE and ATTACH (only on table creation), but not checked on SELECT, DROP, etc...

Of course. It should be only for CREATE TABLE because ATTACH never check any grants (because it's executed only internally on startup).

**Comment by vitlibar** [comment]
> I find it is easy to implement the approach of GRANT table engine, but there is an issue arising up. For existing users (not default) after the implementation, they have to get granted for the usage of their current table engine, which is not good since it is a change of existing user behavior.

That's a difficult part. We can implement it anyway but it will be a breaking change. Or we can hide that new privilege type under a setting in the configuration file but it's unclear what should be its default value then.

**Comment by jsc0218** [comment]
@alexey-milovidov Would you mind compare this with #55911? There is some overlap in terms of functionality. The difference is "set is temporary, grant is durable".

**Comment by alexey-milovidov** [comment]
@jsc0218, Your implementation will cover that old task completely.
