### ISSUE TITLE
Control of referential integrity between tables and views

### ISSUE THREAD

**Issue by Alex-Burmak** [ClickHouse/ClickHouse#38326]
Right now it's possible to delete table with dependent views. It will result to the broken views and attempts to perform query for these views will fail.

```
# clickhouse-client
ClickHouse client version 22.6.1.1985 (official build).

:) CREATE TABLE t1 (n Int32) ENGINE = Log

Ok.

:) CREATE VIEW v1 AS SELECT * FROM t1

Ok.

:) DROP TABLE t1

Ok.

:) SELECT count() FROM v1

Received exception from server (version 22.6.1):
Code: 60. DB::Exception: Received from localhost:9001. DB::Exception: Table default.t1 doesn't exist. (UNKNOWN_TABLE)
```

Adding referential integrity checks will help to avoid errors in database schema. Attempt to delete a table should fail if there are views with references to this table.

**Comment by tavplubix** [comment]
> Although it's disabled by default (not sure why).

Because the referential integrity check may break queries for some users (for example, if they just drop or rename tables in arbitrary order)
