### ISSUE TITLE
Some tests with Live View are disabled

### ISSUE THREAD

**Issue by tavplubix** [ClickHouse/ClickHouse#38332]
As far as I remember, a long time ago we have disabled some tests with live view temporarily, because they were flaky. 
We should either enable these tests back or remove them (maybe together with live view feature):
```
00963_temporary_live_view_watch_live_timeout.py.disabled
00979_live_view_watch_live_moving_avg.py.disabled
00991_live_view_watch_event_live.sh.disabled
00991_live_view_watch_http.sh.disabled
00991_temporary_live_view_watch_events_heartbeat.sh.disabled
00991_temporary_live_view_watch_live.sh.disabled
```

cc: @vzakaznikov

**Comment by alexey-milovidov** [comment]
Let's remove these tests.

**Comment by alexey-milovidov** [comment]
Live View can be removed after we will provide some alternative.

**Comment by tavplubix** [comment]
#40440
