### ISSUE TITLE
If you specify FINAL, optimization is performed even when all the data is already in one part.

### ISSUE THREAD

**Issue by mbtolou** [ClickHouse/ClickHouse#38330]
Hi.

You have given the following sentence in the software guide. What does that mean ?

`If you specify FINAL, optimization is performed even when all the data is already in one part.`

```sql
create table
  ahe.up_hourly_data (
    `device_id` String ,
    `clock` DateTime('Asia/Tehran') ,
    `ptf_g1` SimpleAggregateFunction(anyLast, Nullable(decimal(12, 0))) ,
    `ptf_g2` SimpleAggregateFunction(anyLast, Nullable(decimal(12, 0))) ,
    `ptf_g3` SimpleAggregateFunction(anyLast, Nullable(decimal(12, 0))) ,
    `ptf_g4` SimpleAggregateFunction(anyLast, Nullable(decimal(12, 0))) ,
    `ptf_g5` SimpleAggregateFunction(anyLast, Nullable(decimal(12, 0))) ,
    `ptf_g6` SimpleAggregateFunction(anyLast, Nullable(decimal(12, 0))) ,
    `ptf_g7` SimpleAggregateFunction(anyLast, Nullable(decimal(12, 0))) ,
    `lav1` SimpleAggregateFunction(anyLast, Nullable(decimal(18, 5))) 
) ENGINE = AggregatingMergeTree partition by toYYYYMMDD(clock)
order by (clock, device_id) SETTINGS index_granularity = 8192;
```

When I store data in this table in different partitions and although I optimize final, there is still a lot of data based on (clock, device_id) in the table !!

I also enable the following settings when inserting:

```
optimize_on_insert
max_partitions_per_insert_block
```

**Comment by den-crane** [comment]
>You have given the following sentence in the software guide. What does that mean ?
>If you specify FINAL, optimization is performed even when all the data is already in one part.

It means that `SELECT .... FROM t FINAL` is much slower than `SELECT .... FROM t`

**Comment by mbtolou** [comment]
In my data, after finalizing, there are still two rows for the order key !!!!

**Comment by den-crane** [comment]
Final merge is possible if the resources is enough. Check the size of the part and disk free space. 

If you use use multi-disk / multi-volume configuration check that all parts of this partition is on the same disk.

**Comment by mbtolou** [comment]
I only have 69 million records.
24 GB RAM and one terabyte hard drive.
And an octa-core cpu.
I do not think the problem is with system resources.

**Comment by mbtolou** [comment]
For a device, I took a list of records that are in several partitions and send it to you in an Excel file.

```sql
select device_id, clock, _part
from ahe.up_hourly_data
where
	clock > addDays(today(), -70)
	and (clock, device_id) in (
		select clock, device_id
		from ahe.up_hourly_data
		where device_id in ('11070002382126')
		group by clock, device_id
		having count(1) > 1
		limit 100
	)
order by clock;
```

[1655998280806.xlsx](https://github.com/ClickHouse/ClickHouse/files/8968712/1655998280806.xlsx)

**Comment by mbtolou** [comment]
[New Text Document.txt](https://github.com/ClickHouse/ClickHouse/files/8968868/New.Text.Document.txt)

**Comment by den-crane** [comment]
>device_id	clock	_part
>12040070014104	2022-06-23 18:15:00	20220623_338951_338951_0
>12040070014104	2022-06-23 18:15:00	20220623_338950_338950_0

Most probably they were inserted after `optimize`

Can you share 

```sql
set optimize_throw_if_noop=1;
optimize table ahe.up_hourly_data partition id '20220623' final;
```
and check for duplicates again

**Comment by mbtolou** [comment]
no.

I have optimized three times after this data was recorded.

new data:
[1656000455253.txt](https://github.com/ClickHouse/ClickHouse/files/8968956/1656000455253.txt)

**Comment by den-crane** [comment]
But you inserted new data. That's expected.

**Comment by den-crane** [comment]
Check that Distributed table finished to propagate data.

`system.distribution_queue`

**Comment by mbtolou** [comment]
This is empty table!

I don't have distribution tables .

**Comment by mbtolou** [comment]
After 2 optimizations, all the same records were finally combined.
