### ISSUE TITLE
Incorrect null logic for SELECT 0 or null

### ISSUE THREAD

**Issue by ketbra** [ClickHouse/ClickHouse#3834]
I'm using version 18.14.12

SELECT 0 OR null

Result: 0
Expected: null

Please let me know if you need any more information, and thank you!

**Comment by alexey-milovidov** [comment]
We are planning to fix this issue in nearest month.

More details: https://yandex.github.io/clickhouse-presentations/database_saturday_2018_2/octonica/meetup.pptx (slide 12).

**Comment by ketbra** [comment]
Perfect.  Thank you!

**Comment by alexey-milovidov** [comment]
Now works as expected.
