### ISSUE TITLE
When final query processing is done at Initiator node?

### ISSUE THREAD

**Issue by HeenaBansal2009** [ClickHouse/ClickHouse#38358]
In terms of memory usage , 
Is there any difference when final query processing is done on the initiator node and when it is done on the shard and initiator only proxy the data.

**Comment by HeenaBansal2009** [comment]
@den-crane , I am not sure if I understand your answer . 
My question is around the below comments in doc:

0 — Disabled (final query processing is done on the initiator node).
1 - Do not merge aggregation states from different servers for distributed query processing (query completelly processed on the shard, initiator only proxy the data), can be used in case it is for certain that there are different keys on different shards.

Keeping this value to default , does it make any difference in terms of memory usage ?

**Comment by den-crane** [comment]
I see. I thought you were asking about FROM ... FINAL.

**Comment by HeenaBansal2009** [comment]
> I see. I thought you were asking about FROM ... FINAL.

No , My bad I was not clear on the very first stage.  My question is around distributed_group_by_no_merge. 
Does toggling its value make difference w.r.t memory usage for query processing ?

**Comment by den-crane** [comment]
`1 - Do not merge aggregation` is faster and uses less memory. In this case initator just proxies the results from shards to the client (there is more to do sort at the initiator without aggregation)

Final Aggregation is quite expensive it better to avoid it if possible.

There is new feature

```
 --optimize_distributed_group_by_sharding_key arg                                   Optimize GROUP BY sharding_key queries (by avoiding costly aggregation on the initiator server).
```
It disables Final Aggregation automatically if groupby is suitable for sharding key.

**Comment by den-crane** [comment]
>Do you think any possible reasons behind ?

Yes, distributed_group_by_no_merge=0 require more resources.

I already answered.

> 1 - Do not merge aggregation is faster and **uses less memory.**

**Comment by HeenaBansal2009** [comment]
> > Do you think any possible reasons behind ?
> 
> Yes, distributed_group_by_no_merge=0 requires more resources.
> @den-crane , I agree that executor nodes only processed subquery of initial query and merging of partial aggregation happens at initiator node. Hence this scenario consumes more memory.
However , executing the same query on same distributed table works fine with same set of data on single node cluster. How ?

> I already answered.
> 
> > 1 - Do not merge aggregation is faster and **uses less memory.**
