### ISSUE TITLE
Docs mention max_concurrent_queries_for_all_users as server-level but it produces an error

### ISSUE THREAD

**Issue by fillest** [ClickHouse/ClickHouse#38357]
`max-concurrent-queries-for-all-users` (and `max_concurrent_queries_for_user`) are in [server configuration docs](https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings/#max-concurrent-queries-for-all-users) but using it like this leads to `<Error> Application: DB::Exception: A setting 'max_concurrent_queries_for_all_users' appeared at top level in config /etc/clickhouse-server/config.xml. But it is user-level setting that should be located in users.xml inside <profiles> section for specific profile.`
ClickHouse version: 22.6.1.1985

**Comment by filimonov** [comment]
Confirmed. Either docs should be changed, either the location of the setting should be moved. Similar to https://github.com/ClickHouse/ClickHouse/pull/36425/files

**Comment by rfraposa** [comment]
@filimonov - shall I update the docs for now? We can always move it back to the server config page if the location of the setting is moved.

**Comment by DanRoscigno** [comment]
I am not sure where we document all of the user settings.  I started to move these to https://github.com/ClickHouse/ClickHouse/tree/master/docs/en/operations/settings/settings-profiles.md , but that is not where all of them are.  I am going to mark my PR with draft while we figure this out.

**Comment by DanRoscigno** [comment]
notes:
- Global server settings belong to config.xml and are viewable in `system.server_settings`. These settings are rigid, and cannot be changed for a user or query.
- Query-level settings belong to users.xml, are viewable in `system.settings`, but also can be set for a user profile with SQL queries, and changed dynamically for a session or a query.

**Comment by DanRoscigno** [comment]
SELECT format('### {}\n\n{}\n\nType: {}\n\nDefault: {}\n\n', name, description, type, default)
FROM system.settings
ORDER BY name ASC
FORMAT TSVRaw
