### ISSUE TITLE
inner join empty table optimization 

### ISSUE THREAD

**Issue by tahayk** [ClickHouse/ClickHouse#38378]
Hello everyone, 

I have 2 tables, T1 is empty (CollapsingMergeTree), and T2 contains 20B records (ReplacingMergeTree)

```sql
SELECT COUNT()
FROM T1 INNER JOIN T2 USING(key);
```

this query takes a couple of seconds, Is there a way to optimize it ? 

thank you in advance.

**Comment by den-crane** [comment]
swap tables?

```
SELECT COUNT()
FROM T2 INNER JOIN T1 USING(key);
```

**Comment by tahayk** [comment]
@den-crane thank you for the reply
yes, in some cases swapping tables makes it faster (which is the case of the example I provided), 
but for my specific use-case (more complex then the example) it does not change anything, 
but I found out that using [IN](https://clickhouse.com/docs/en/sql-reference/statements/select/join/#performance) would make it as fast as expected
```sql
SELECT COUNT()
FROM T2
WHERE key IN (SELECT key FROM T1);
```
