### ISSUE TITLE
v22.3.7.28-lts arm build error

### ISSUE THREAD

**Issue by gechengxiang1224** [ClickHouse/ClickHouse#38373]
v22.3.7.28-lts arm build
clang version=13
build command：
CC=/home/logsaas/clang+llvm-13.0.0-aarch64-linux-gnu/bin/clang CXX=/home/logsaas/clang+llvm-13.0.0-aarch64-linux-gnu/bin/clang++ cmake  -DENABLE_CLICKHOUSE_ALL=OFF -DGLIBC_COMPATIBILITY=OFF  -DENABLE_CCACHE=0 . -Bpp -DCMAKE_TOOLCHAIN_FILE=cmake/linux/toolchain-aarch64.cmake

The error is as follows：
- Local mode: OFF
-- Benchmark mode: OFF
-- Extract from config mode: OFF
-- Compressor mode: OFF
-- Copier mode: OFF
-- Format mode: OFF
-- Obfuscator mode: OFF
-- ODBC bridge mode: OFF
-- Library bridge mode: OFF
-- ClickHouse install: OFF
-- ClickHouse git-import: OFF
-- ClickHouse keeper mode: OFF
-- ClickHouse keeper-converter mode: OFF
-- bash_completion will be written to /usr/local/share/bash-completion/completions
-- Target check already exists
-- /home/logsaas/ClickHouse/utils: Have 251499 megabytes of memory.
        Limiting concurrent linkers jobs to 71 and compiler jobs to OFF (system has 64 logical cores)
-- Configuring incomplete, errors occurred!
See also "/home/logsaas/ClickHouse/pp/CMakeFiles/CMakeOutput.log".
See also "/home/logsaas/ClickHouse/pp/CMakeFiles/CMakeError.log".

**Comment by alexey-milovidov** [comment]
Download pre-built official binary instead of building it by yourself.

**Comment by hsming** [comment]
> 

@alexey-milovidov  Where is the pre-built official binary  for arm ?

**Comment by alexey-milovidov** [comment]
https://s3.amazonaws.com/clickhouse-builds/35373/5519a4c5fb5085fe37ceec4d384ca0d2259413a9/clickhouse_build_check_(actions)/report.html

**Comment by jackzhangsir** [comment]
wtf
