### ISSUE TITLE
Max() is significant slower than ORDER BY DESC LIMIT 1

### ISSUE THREAD

**Issue by astronom** [ClickHouse/ClickHouse#38388]
We have a table with approximately 31 billion rows and 4.5 TB data. Created_at column contains constantly growing data
```sql
CREATE TABLE data ON CLUSTER cluster (
    id                              UInt64,
    created_at                DateTime
   ... some other columns
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/data', '{replica}')
ORDER BY (created_at, some other columns)
PARTITION BY toStartOfWeek(created_at, 1)
```

The query to get the max of created_at value from period was:

```sql
SELECT max(created_at)
FROM data
WHERE created_at >= :start
  AND created_at < :end
```
Elapsed time is about 40-50 seconds.

Rewrited query

```sql
SELECT created_at
FROM data
WHERE created_at >= :start
  AND created_at < :end
ORDER BY created_at DESC LIMIT 1
```
Elapsed time is 1-2 seconds.

**Expected behavior**
It seems that `max` should be first value of sorted desc `created_at` column values, or I'm not right?

* ClickHouse server 21.8.13.6

**Comment by canhld94** [comment]
My guess is the first query need to read all values from start to end and compute the max, while the second query will read much less data (probably only 1 granule) because of read in order and limit pushdown optimization for pk prefix columns.
May be can provide a special implementation for min and max function when argument is prefix of pk.

**Comment by den-crane** [comment]
This **expected** behaviour. 

CH does not have optimization for `max(created_at)` using primary_index and does have an optimization for `ORDER BY created_at`

**Comment by den-crane** [comment]
BTW, New versions of CH use a virtual projection and instantly calculate `max(created_at)` from `PARTITION BY toStartOfWeek(created_at, 1)` (using only memory, no disk involved) .

**Comment by den-crane** [comment]
```
21.8

select max(day) from t;
Elapsed: 25.904 sec. Processed 1.68 trillion rows

upgrade to 22.3
select max(day) from t;
Elapsed: 0.063 sec. Processed 5.09 thousand rows
```

**Comment by astronom** [comment]
After upgrade to 22.3.7.28 the issue is still relevant. Yes, selecting `max(created_at)` without other where clauses is quick. 

But this query is slow
```sql
SELECT max(created_at)
FROM data
WHERE created_at >= :start
  AND created_at < :end
```

**Comment by astronom** [comment]
@[den-crane](https://github.com/den-crane) the issue is still relevant
