### ISSUE TITLE
Add extended range support for Date32 and DateTime64

### ISSUE THREAD

**Issue by rvasin** [ClickHouse/ClickHouse#38393]
I am currently working on the problem of extending Date32 and DataTime64 ranges. I found similar issue #[28216](https://github.com/ClickHouse/ClickHouse/issues/28216). But here I want to explain my arguments and my ideas how to extend the ranges. 
I made some analysis for ranges for DATE data type in different DBMS:

DBMS | Data Type | Data Type Size | Low | High
-- | -- | -- | -- | --
ClickHouse | Date32 | 4 bytes | 1925 | 2283
Postgresql / Greenplum | Date | 4 bytes | 4713 BC | 5874897 AD
MySQL / MariaDB | Date | ? | 1000 | 9999
Oracle | Date | ? | 1000 | 9999
Microsoft SQL Server | Date | 3 bytes | 0001 | 9999
Firebird | Date | ? | 0001 | 9999
Vertica | Date | 8 bytes | 25e+15 BC | 25e+15 AD

Clear that year of 1925 in ClickHouse looks very strange. And it’s hard to explain such limit for banking and insurance people which use dates since at least 1900. Storing dates are strings is not a choice (banks needs to calculate ages of their clients using date_diff() and so on).
I think we need to extend the range in correct way without much performance degradation. 
In this issue I want to make some kind of a public discussion with ClickHouse core team and other ClickHouse contributors in free way how do they think it’s better to implement extended date range support.

I suggest the following:
    1. For config.xml create new option: use_extended_date_range. Default value is false. It does not much performance of servers of existing customers. 
    2. Extend range to 01..9999 for Date32 and DateTime64. 4 bytes for Date32 is far enough for it. Currently dates stored in existing databases will not suffer because we don’t change storage format. 
    3. Keep using LUT for 1925..2283. There is no way to create extended LUT for 1900..2300 for example. Thus dates filled into 1925..2283 will use LUT for all date/time functions. Hence there is no performance degradation.
    4. If use_extended_date_range  == true AND date is out of LUT range 1925..2283 then we don’t use LUT and we calculate for example, DayOfWeek in place.
This way I think there is no much performance degradation. And still we will have 01..9999 range as most of other DBMS have.

Also there is one more note about how other DBMS do it. For example, in PostgreSQL:
https://www.postgresql.org/docs/current/datetime-units-history.html

> PostgreSQL follows the SQL standard's lead by counting dates exclusively in the **Gregorian** calendar, even for years before that calendar was in use. This rule is known as the proleptic Gregorian calendar.

I think ClickHouse also should follow to SQL standard and use Gregorian calendar for all dates. It’s clear that it’s not 100% correct. The same way we don’t have to worry much about LUT before 1925. We may implement some kind of solution. Or I suggest to simply use the same timezone rules/algorithms as ClickHouse is using now for dates before 1925. The same way as PostgesSQL is using Gregorian rules for dates before invention of  Gregorian calendar. Which is also not 100% correct for date calculation. 

Plus in banking industry I think it’s not the questions of time zones for years before 1925. Time zones is not critical for this case use. But banks need to record birth dates like 1920, 1922. and then make SQL SELECT queries like: show list of all bank’s clients younger 25 years in given city. Simple select to calculate age of bank’s client. Thus correct work of functions like date_diff with extended date ranges is important.

What do you think? Please share your ideas how to correctly extend date ranges without performance degradation.

**Comment by den-crane** [comment]
> limit for banking and insurance people which use dates since at least 1900

BTW, I guess proleptic calendar provides incorrect results if insurance people use real Gregorian calendar.

**Comment by rvasin** [comment]
For example? My idea that if all other DBMS support dates before 1925 and just one CH does not support it - it looks very strange. And CH must follow to SQL standards and support dates before 1925 in the way as all other DBMS support it.

**Comment by den-crane** [comment]
NVM, just use proleptic calendar.

**Comment by rvasin** [comment]
My further thoughts:

Maybe it’s a good idea to slightly extend LUT by making the  start of range as 1900. And apply the same LUT building rules for 1900..1924 as for 1925..2283. It will cover needs of the most banking/insurance people. The calculations will be fast. And we should clearly state in documentation of CH that time zones for 1900..1924 maybe incorrect for some cases. It should be considered as a first step improvement, but still 01..9999 range is needed to be implemented.

I saw a video with @alexey-milovidov released about 4 months ago he was saying the CH was adopted in wide range of industries astronomy including. I don’t know what are the usage cases for astronomy. They probably record current satellites/stars coordinates. For such usages1970+   (Unix epoch) is enough. But I know there are very high precise astronomy math for date calculations. So astronomy scientists will not glad using current PostgreSQL/MySQL date calculation algorithms. They will use they own slow and high  precise algorithms. Hence there is no need to implement slow high precision date/time algorithms in CH.

Another point is that Vertica’s date range is 25e+15 BC .. 25e+15 AD. How precisely do they calculate the dates? I don’t think CH needs that range. Do they they use time zones at all for such calculations? There is such [TIMESTAMPTZ](https://www.vertica.com/docs/9.2.x/HTML/Content/Authoring/SQLReferenceManual/DataTypes/Date-Time/DateTimeDataTypes.htm?tocpath=SQL%20Reference%20Manual%7CSQL%20Data%20Types%7CDate%252FTime%20Data%20Types%7C_____0) supporting timezones.
Thus I think CH should use the standard range 01..9999 as other DBMS use and use the same algorithms (proleptic calendar ? :) 

I just want to say that these are just my ideas about improving CH. I am glad to read any other suggestions.

**Comment by alexey-milovidov** [comment]
Extending DateLUT before 1900 with inaccurate support of time zones will be ok for me.

**Comment by filimonov** [comment]
There is an accuracy problem with *TIME* in many timezones before 1925 (i think we can just switch to slow path with direct usage of cctz there).

But dates without time - should not have any problems

**Comment by den-crane** [comment]
@filimonov Nobody care. All other databases implement proleptic! Gregorian calendar. 

BTW, 

Последний деньюлианского календаря | Первый деньгригорианского календаря | Государства и территории
-- | -- | --
1 января 1926 | Турция[13] (переход со счёта лет по румийскому календарю на счёт лет по григорианскому календарю)
17 сентября 1928 | 1 октября 1928 | Египет
1949 | Китай (переход со счёта лет по календарю Миньго на счёт лет по григорианскому календарю; на Тайване сохранился календарь Миньго)[14]
1 октября 2016 | Саудовская Аравия[20][21]


Ну ведь никто не собирается для Китая внедрять лунный календарь для дат до 49 года? Где число месяцев другое и недель не существует? Т.е. сейчас для Китая уже используется пролептический календарь, поэтому надо просто заиспользовать его для дат до 1925 года. 

Я думаю все современные записи во всех метриках уже подвинуты на 13 дней, т.е. если контракт начался 1 января 1900 года, то в современных базах написано 13 января 1900, если там все еще написано 1 января, то они сами себе буратины.

**Comment by den-crane** [comment]
и про

>cctz

Да там например пять шестидневных недель в месяце было, какая разница про время. Мы считаем что там понедельник был, а там был 4-й день 5 недели месяца и слова понедельник не было.

**Comment by filimonov** [comment]
Those are different things. Lack of support of the timestamp before 1925 different.

There are non trivial tinrshifts (like 67 seconds) for timestamp in some timezones before 1925 (and it can't be  properly served by lookup tables used in DateLUT). 

There is no such problem with dates. It just inherit the limitation from DateTime64.

Support of other calendar (Julian, hebrew, chineese etc) is out of scope here.

**Comment by filimonov** [comment]
Т.е. поддержка таймстампов до 1925 года не была реализована не из-за разных календарей (конечно имеет смысл только григорианский  пролептичесеюкий) а потому что часы во всех странах до 20х годов 20 века ходили очень странно. Там был такой хаос (разницы в минуты/десятки секунд и т.п) который в простые таблицы "временной диапазон => смещение" запихать очень сложно. Точная арифметика там возможна только с применением более сложных (и медленных) вычислений.

**Comment by den-crane** [comment]
Ну в некоторых странах не было наших понятий час, минута, секунда, они время измеряли по другому. 
Я не понимаю зачем переживать про точное местное время, мы даже день не можем правильно показать. Пусть во всех зонах будет UTC.

**Comment by filimonov** [comment]
>  Пусть во всех зонах будет... самая первая/ранняя

Это не невозможно и более-менее должно работать. Но будут разногласия с другими системами и не исключаю что для каких-то таймзон ошибка будет нарастать по мере "углубления" в прошлое. 

Так или иначе это потребует отдельной обработки лат старше 1925 года (лукап таблицы имеют ограниченный размер), и кажется что вместо этого можно просто для всех дат старше 1925 напрямую воспользоваться cctz (будет точно, хотя и несколько медленнее).

**Comment by rvasin** [comment]
Тема с датами очень спорная, если рассматривать время (datetime) до 1925 - так это еще более спорно (получается какая то абстрактная фиктивная вещь). Но решать проблему как то все таки надо. Т.к. банки рассматривают лимит 1925 как серьезный недостаток КХ. Игнорировать банковский сектор со стороны КХ - неразумно. Т.к. это один из главных секторов экономики. 
В банках (как даже писали китайские коллеги), за начальную дату рассматривается 1900. Раньше им особо и не нужно. Но если другие БД используют 01 или 1000 как начальную дату - то надо тоже самое сделать и в КХ. 

Поэтому тут много вопросов:
1. Спорный момент: Может быть хотябы расширить LUT - сделать стартовой 1900. Раньше точно не нужно. Это малая задача. Которую точно надо как то решать. То есть надо принять решение - использовать LUT для 1900-1924 или нет?
2. Большая задача - расширение диапазона  Date32 и DateTime64
   а. что считать за начальный диапазон Date32: 4713 BC, 01, 1000?
   б. что считать за конечный диапазон Date32: 5874897 AD (4х байтов в Date32 хватит), 9999?
   г. что читать за начальный диапазон в DateTime64: 4713 BC, 01, 1000, 1900, 1925? 
   д. что читать за начальный диапазон в DateTime64: 5874897 AD, 9999.
3. Какие библиотеки использовать для расширенного диапазона? Возможно CCTZ - хороший выбор.

Я работаю в Аренадата. Проблема насущная, возникла с одним крупным банком, да и не только (раскрывать много информации нельзя). Текущий диапазон 1925 это очень серьезный недостаток в выборе банком использовать КХ или нет.
Поэтому могу взяться за "малую" и/или "большую" задачи. Если надо - сделать разные тесты производительности, написать все тесты по новым диапазонам и т.п. В общем провести всю разработку в любом объеме. 
Надо найти ответы на вопросы выше и вообще чтобы сообщество как то КХ одобрило эту затею - расширения диапазона дат.

Вообще алгоритм расчета количества дней между двумя датами на разных языках можно найти на странице:
https://rosettacode.org/wiki/Days_between_dates#C.2B.2B
Для С++ вариант реализации:
```
int diffDays(Date date1, Date date2) {
    // skip
    int days1 = 365 * d1y + d1y / 4 - d1y / 100 + d1y / 400 + (d1m * 306 + 5) / 10 + (date1.getDay() - 1);
    int days2 = 365 * d2y + d2y / 4 - d2y / 100 + d2y / 400 + (d2m * 306 + 5) / 10 + (date2.getDay() - 1);
    return days2 - days1;
}

```

То есть всё достаточно достаточно просто и точно. Вопрос со временем как быть? 
Насчет диапазонов, по датам все получается так:
За последнюю "правильную" принимают 325 AD когда Юлианский календарь еще был точен. Затем папа Григорий реально предложил свой календарь только в 1582. К тому времени ошибка составляла уже 10 дней. Переходили страны на Григорианский календарь очень по разному. 
Длина (тропического) солнечного года составляет 365.2422. 
Длина года по Григорианскому календарю составляет 365.2425. 
Получаем: 1/(365.2425-365.2422) = 3333 лет. То есть реальное расхождение в 1 день (когда Григорианский календарь станет неточен):  325 + 3333 = 3658 AD.
Ну кому это важно? Т.е. если у всех конечный диапазон 9999, то лучше делать также 9999. А 25e+15 AD - как в Вертика - наверное перебор :)

**Comment by filimonov** [comment]
Расширить - не проблема, но при этом сохранить точность внутри LUT для таймстампов до 1925 не просто.

Cctz уже используется для заполнения lut и это самый естественный выбор.

Я думаю @Enmk может рассказать подробнее.

**Comment by rvasin** [comment]
Согласен - cctz уже используется для формарования LUT. Поэтому это самый ествественный выбор. Я посмотрел исходный код cctz там повсюду используется Грирогианский календарь и вообще нет каких то существенных ограничений диапазонам дат. Например функция day_difference (которая пока не используется в КХ) - считает строго по Григорианскому календаю. И эту функцию можно использовать для диапазона 01..9999
```
// Support years that at least span the range of 64-bit time_t values.
using year_t = std::int_fast64_t;
```
Как первый этап я приступлю к расширению LUT, чтобы начальная дата была 1900 с учетом того, что будет неточная поддержка временных зон в интервале 1900..1924 @alexey-milovidov выше одобрил такой подход. То есть я берусь за это дело и оформлю код отдельным pull request.

Дальнейшие задача - расширение диапазона до  01..9999 я думаю надо точно использовать cctz для всех дат, которые не попали в LUT. При этом оставить LUT в новом диапазоне 1900..2283. А эту задачу я, возможно, тоже возьмусь после завершения первой задачи.

**Comment by rvasin** [comment]
Я сделал достаточно интересный анализ по CCTZ, MySQL, PostgreSQL.
Главный вывод - CCTZ работает с диапазоном 1900+ и выдает результаты такиже же как и PostgreSQL для тех же дат. То есть можно использовать CCTZ для диапазона 1900+. Анализ ниже:


## Time zones support in different DBMS  


### Using CCTZ functions directly

```C++
    cctz::time_zone tz1;
    if (!cctz::load_time_zone("Europe/Moscow", &tz1))
    {
        std::cout << "error loading tz" << "\n";
    }
    // find unique civil time.
    auto date01 = tz1.lookup(cctz::civil_second(2022, 7, 1, 10, 0, 0));
    std::time_t pre_t1 = std::chrono::system_clock::to_time_t(date01.pre);
    std::cout << "date01 pre " << std::ctime(&pre_t1) << "\n";
```

ClickHouse uses CCTZ functions for ranges 1925..2283

The following code maybe used o lookup civil (local) time from given absolute time.

For following code maybe used to lookup years in loop (after prior loading of time zone):

```C++
    for (cctz::year_t y = 1890; y < 2023; ++y)
    {
        auto date02 = tz1.lookup(cctz::civil_second(y, 7, 1, 10, 0, 0));
        std::time_t pre_t2 = std::chrono::system_clock::to_time_t(date02.pre);
        std::cout << "CCTZTest year " << y << " date01 pre " << std::ctime(&pre_t2) << "\n";
    }
```

The results for certain years for Europe/Moscow July 1 at 10:00:

> year 1890 date01 pre Tue Jul 1 07:29:43 1890  
> year 1900 date01 pre Sun Jul 1 07:29:43 1900  
> year 1916 date01 pre Sat Jul 1 07:29:43 1916  
> year 1917 date01 pre Sun Jul 1 07:28:41 1917  
> year 1918 date01 pre Mon Jul 1 05:28:41 1918  
> year 1919 date01 pre Tue Jul 1 06:00:00 1919  
> year 1925 date01 pre Wed Jul 1 08:00:00 1925  
> year 2013 date01 pre Mon Jul 1 06:00:00 2013  
> year 2022 date01 pre Fri Jul 1 07:00:00 2022

### MySQL

The specific of MySQL time zone related tables are created on the moment of MySQL installation in database with name MySQL. The following time zone related tables are created:

- time\_zone
- time\_zone\_leap\_second
- time\_zone\_name
- time\_zone\_transition
- time\_zone\_transition\_type

But these tables are empty. And they must be filled with time zones information from external sources. Usually on Linux system such source is /usr/share/zoneinfo

To fill time zones database the following command must be executed:

```
mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root -p mysql
```

This is the most common way in MySQL community. While other time zone sources maybe used to fill the time zone tables. Read [time zones support](https://dev.mysql.com/doc/refman/8.0/en/time-zone-support.html) article for details.

After then to convert from local time to absolute time we use [CONVERT\_TZ](https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_convert-tz) function. For example:

```
SELECT CONVERT_TZ('1970-07-01 10:00:00','Europe/Moscow','UTC');
```

For all dates 1900..1969 the function returns time part without any conversion:

1969-07-01 10:00:00

For all dates after 1970 (Unix epoch) it correctly uses transition table:

for 2013: 2013-07-01 06:00:00

for 2018: 2018-07-01 07:00:00

### PostgreSQL  


After installation of PostgreSQL server - all time zones information is already loaded. We don't need to make a separate step to load time zones tables as we did for MySQL.

In PostgreSQL [AT TIME ZONE](https://www.postgresql.org/docs/current/functions-datetime.html#FUNCTIONS-DATETIME-ZONECONVERT) must be used to make conversion between time zones. It seems that PostgreSQL uses IANA database. Because the results are very close to the results produced by CCTZ functions (and CCTZ also uses IANA database).

> select timestamp without time zone '1400-07-01 10:00:00' at time zone 'Europe/Moscow';  
> 1400-07-01 07:29:43+00
> 
> select timestamp without time zone '1890-07-01 10:00:00' at time zone 'Europe/Moscow';  
> 1890-07-01 07:29:43+00
> 
> select timestamp without time zone '1900-07-01 10:00:00' at time zone 'Europe/Moscow';  
> 1900-07-01 07:29:43+00
> 
> select timestamp without time zone '1916-07-01 10:00:00' at time zone 'Europe/Moscow';  
> 1916-07-01 07:29:43+00
> 
> select timestamp without time zone '1918-07-01 10:00:00' at time zone 'Europe/Moscow';  
> 1918-07-01 05:28:41+00
> 
> select timestamp without time zone '1919-07-01 10:00:00' at time zone 'Europe/Moscow';  
> 1919-07-01 06:00:00+00
> 
> select timestamp without time zone '1925-07-01 10:00:00' at time zone 'Europe/Moscow';  
> 1925-07-01 08:00:00+00
> 
> select timestamp without time zone '2013-07-01 10:00:00' at time zone 'Europe/Moscow';  
> 2013-07-01 06:00:00+00
> 
> select timestamp without time zone '2022-07-01 10:00:00' at time zone 'Europe/Moscow';  
> 2022-07-01 07:00:00+00

**Comment by rvasin** [comment]
На странице https://en.wikipedia.org/wiki/Moscow_Time#Past_usage
Приведены исторические данные по Moscow Time. То есть когда и что менялось. 
Как показывают мои тесты cctz строго следует историческим данным по Москве даже для диапазона 1900..1924. Также тестировал некоторые другие города. Там тоже все работает. То есть я считаю что можно смело использовать cctz для 1900..1924 и доля "мусора"/неверных данных будет небольшая (если вообще будет). Похоже IANA по возможности очень полно использует все доступные исторические данные по смене time zones.

**Comment by filimonov** [comment]
Все верно. Cctz абсолютно корректен.

Проблемы только с DateLUT.

**Comment by rvasin** [comment]
Просто дело в том, что для банков - рабочий диапазон это 1900+. Очень желательно чтобы эти даты были в DateLUT для быстроты
А уже как вторая задача - использовать cctz для расширенного диапазона 01..9999. 
С чем я сейчас столкнулся:
date_lut_mask = 0x1ffff;
по сути дела если сделать началом диапазона 1900, то тогда конец диапазона 
2283-25 = 2258
То есть это не расширение DateLUT получается. А сдвиг на более ранний диапазон 1900..2258 при сохранении размера DateLUT тем же 0x20000
Опять же, банкам, что 2283, что 2258 большой разницы не имеет, т.к. эти верхние даты не нужны. А важно чтобы было 1900+ и работало быстро.

**Comment by ilejn** [comment]
I am wondering why this discussion is in Russian,
lets switch back to English please unless we have special reasons.

**Comment by ilejn** [comment]
Mikhail @filimonov , could you clarify what are the benefits of uzing cctz directly, not via LUT ?

My concern is some performance penalty for extended date or datetime types needed to check if a date (or both) are covered by LUT. It is pretty hard to avoid extra condition check.
In other words, prolonging LUT for 1900+ we effectively prevent ourselves from covering earlier dates: no motivation to pay the price for pre-1900 dates.

**Comment by rvasin** [comment]
Do you have any suggestions about changing the mask value for such case? 
The logic behind the mask is very simple. For example:

```
template <typename T>
    friend inline LUTIndex operator+(const T v, const LUTIndex & index)
    {
        return LUTIndex{(v + index.toUnderType()) & date_lut_mask};
    }
```

It's used in many parts of code this way. I don't see how the mask's logic maybe improved. Maybe delete using of the mask from code. But this is not a good choice.

**Comment by ilejn** [comment]
This is nasty, while I suggest switching to explicit "if" .

**Comment by rvasin** [comment]
I want to get some feedback from community ( @alexey-milovidov @filimonov @ilejn  ) about design decisions about the extending range of dates. 

Current DatLUT’s size is 0x20000. It allows to work with range 1925..2283. 
I was trying to extend DateLUT by just moving the left boundary to 1900. So it would make it possible to work with range: 1900..2283. But I found an obstacle that date_lut_mask = 0x1ffff is used as a basic protection against overflow. 

Thus initially in Arenadata we thought about the variant 1: 
Keep size of LUT  0x20000 and just move the whole range from 1925..2283 to 1900..2258. 
pros: 
*  it’s simple to implement.
*  range 1900..1924 is fast because we still use DateLUT for this range.
Cons:
*  years 2258.. 2283 are not covered. Maybe some customers already use it.
*  there are flaws in mask usage for negative numbers (read below).

Then I found the variant 2:
Instead of using the mask implement new function like normalizeLUTIndex() which will change ranges. 
In fact I found that the mask protects against positive numbers changer that DATE_LUT_SIZE. But it does not protect against negative numbers. 
Consider the operator:
```
    template <typename T>
    friend inline LUTIndex operator-(const LUTIndex & index, const T v)
    {
        return LUTIndex{(index.toUnderType() - UInt32(v)) & date_lut_mask};
    }
```

For example, it’s used in function:

```
    inline Time toFirstDayOfWeek(DateOrTime v) const
    {
        const LUTIndex i = toLUTIndex(v);
        if constexpr (std::is_unsigned_v<DateOrTime> || std::is_same_v<DateOrTime, DayNum>)
            return lut_saturated[i - (lut[i].day_of_week - 1)].date;
        else
            return lut[i - (lut[i].day_of_week - 1)].date;
    }

```

For example (see in calendar) January 2, 1925 is Friday. And we want to find the first day of week. It should return December 28, 1924. but because dates are not supported before 1925-01-01, it should return the beginning of LUT which is January 1, 1925. This is how it “should work”. At least it works similar way in findIndex(). But because of incorrect work of mask with negative numbers it return a day close to DATE_LUT_SIZE (a day somewhere in 2283). 

There are other functions implemented the similar way: toFirstDayNumOfWeek, toFirstDayOfMonth, toFirstDayNumOfMonth. 
Thus the mask usage is fast but it does not protect against negative numbers at all. 
Furthermore there is the comment it the source code:

```
// TODO: make sure that any arithmetic on LUTIndex actually results in valid LUTIndex.
    STRONG_TYPEDEF(UInt32, LUTIndex)
```

So arithmetic on LUTIndex does not always return valid  LUTIndex. I think the correct way is to use new normalizeLUTIndex() function in such way:
```
    static inline LUTIndex normalizeLUTIndex(Int64 index)
    {
        if unlikely(index < 0 )
            return LUTIndex(0);
        if (index >= DATE_LUT_SIZE)
            LUTIndex(DATE_LUT_SIZE - 1);
        return LUTIndex{index};
    }

```

usage example:

```
template <typename T>
    friend inline LUTIndex operator-(const LUTIndex & index, const T v)
    {
        return normalizeLUTIndex(static_cast<Int64>(index.toUnderType() - UInt32(v)));
    }

```

Pros:
* LUTIndex arithmetic is correct. Code is more secure.
* in future if needed we may put an exception handling into normalizeLUTIndex() function. All range checks are one single function normalizeLUTIndex(). 
* We may implement range 1900..2300. LUT size will grow in about 10% in size. Which is not too much to notice for existing customers
* We still use LUT for 1900..1924. So it’s fast.
Cons:
* code maybe a bit slower. But we may use things like  if unlikely(index < 0 ). Thus branch prediction will be more accurate for processors. Thus more much penalty in terms of performance.

Variant 3:
Continue to use the mask. But increase the size of LUT in two times. Instead of 0x20000. It will be 0x40000. 
Pros:
* we still use the mask and it’s fast.
Cons:
* using the mask does not protect again negative numbers.
* increasing DateLUT in two times will increase server startup time, RAM usage. Which maybe not OK for existing customers. 

Variant 4:
Keep the range 1925..2283 covered by DateLUT and extend range to 01..9999.
For all operations out of 1925..2283 but within  01..9999 use CCTZ.
Pros: 
* wide range it covered 01..9999.
* We keep LUT size small (the same size as now).
cons:
* performance degradation for 1900..1924 because CCTZ is used for this range. And this range is important for banking/insurance customers.
* many parts of code to rewrite.
* mask is still used but there is not protection against negative numbers.

In Arenadata our favorites are variant 2 and 4, although I'd prefer 2. I already implemented a prototype in my branch which is working for 1900..2300. 

Up to know I did the several tests of CCTZ itself for 1900..1924 (I described it earlier in the issue). It works OK for 1900..1924. Also in current of CH version I created the table:

```
CREATE TABLE date32test1 (`date_test` Date32, `event_id` UInt8) ENGINE = TinyLog;
INSERT INTO date32test1 VALUES ('1930-01-01', 1), ('1970-01-01', 2), ('2100-01-01', 3);

```
and then on my prototype with 1900.2300 I fetched fine the entered data: 
`SELECT * FROM date32test1; `
it displays correctly the data and insertion of new data with new range values is also possible:
```
INSERT INTO date32test1 VALUES ('1900-01-01', 4);
SELECT * FROM date32test1;
```
So this approach works. I want to know if this approach is OK. And on the second phase (as another pull request) I will probably implement extension of range to 01..9999 with usage of CCTZ out of range 1900..2300. Any suggestions are appreciated.

**Comment by alexey-milovidov** [comment]
Variant 1 is problematic because it does not solve the source of the problem, only "shifts" it, and it can cause some incompatibilities for existing users.

Variant 2 can be ok, but we need to check performance tests. I'm afraid if it gives at least some noticeable performance penalty (5% or more), we cannot merge it, or we will have to make some performance optimizations to cover it. Maybe there will be no difference due to instruction-level parallelism. But maybe there will be if existing inlining and subsequent vectorization will stop working. And we will look at the performance tests on both x86_64 and ARM.

Variant 3: the safest variant. I'm sure that the potential increase in startup time is ok. This variant can be subsequently improved if needed by lazy LUT filling and page fault handling (although it's hacky). If you can implement it quickly and submit a PR, let's do it.

Variant 4: ok if there will be no performance degradation due to added branching, which I doubt.

If you can submit multiple variants, let's do it for comparison and merge something. At least variant 3 is guaranteed to work.

**Comment by filimonov** [comment]
AFAIR variant of using LUT on timestamps before 1925 just lead to incorrect results. For creating correct lookup tables there you may need more 'granular' lookup tables, because the moments of TZ shift and time shift between timezones are so 'strange' and don't follow simple rules like 'tzshift is always in quaters of hour', or 'tz changes happens on full hours' etc. 

Also that does not solve the 'bigger' problem - most of databases support range from year 0000 to 9999. The next request will be 'lets support 19th century', etc. :) 

>  I think that cutting the upper bound from 2283 to 2258 is not an option,

+1. Additionally LUT math will be incorrect in the years before 1925, while it is correct for the future. 

Also there are use cases when some insitutions (also financial usually) calculate some models for a long future. 

For me variant 4 sounds the safest, but yes there is a risk of performance impact because of extra branch.

**Comment by ilejn** [comment]
Mikhail, Alexey, thanks for the feedback.

Let me repeat Mikhail's point (as I got it): cctz works fine for 1900-1925, but it is impossible to fit its results in LUT. 

The mask leads to strange underflow processing where instead of going out of range behind the left bound we get a result close to the upper bound. As far as I understand it never happens in reality because of DateLUTImpl::findIndex and because of other bound checks we have in the code, so **mask is completely useless and it never actually works** 
Could someone please (@rvasin ?) confirm or disprove this statement.

Note, that https://github.com/ClickHouse/ClickHouse/issues/38435 is not related, it is about wrong conversion.
```
:) select toStartOfWeek(toDateTime64('1925-01-01', 3))
2104-06-03
```
but
```
:) select toStartOfWeek(toDateTime64('1955-01-01', 3))
2134-06-01

**Comment by ilejn** [comment]
@roman, it does not look like a valid perftest: the cost of parsing is too high.
You should execute the operation against a columns with, say, a million dates.

**Comment by rvasin** [comment]
@ilejn It's true for the first test. But it's "less true" for the second test.

**Comment by ilejn** [comment]
> @ilejn It's true for the first test. But it's "less true" for the second test.

@rvasin try Format Null

**Comment by rvasin** [comment]
> AFAIR variant of using LUT on timestamps before 1925 just lead to incorrect results. For creating correct lookup tables there you may need more 'granular' lookup tables, because the moments of TZ shift and time shift between timezones are so 'strange' before 1925 and don't follow simple rules like 'tzshift is always in quaters of hour', or 'tz changes happens on full hours' etc.
@filimonov What I see now that ClickHouse built with variant 2 produces the same results as CCTZ (standalone) or PostgreSQL for the same dates. For example:
![Screenshot from 2022-07-11 18-21-45](https://user-images.githubusercontent.com/18441691/178299797-4df7ed5c-9f52-4f56-8c35-ff7e1aaa7201.png)

**Comment by rvasin** [comment]
> > @ilejn It's true for the first test. But it's "less true" for the second test.
> 
> @rvasin try Format Null

@ilejn when I run with format Null:

`time echo "select UserID, toStartOfWeek(EventDate), EventTime, toISOYear(EventTime), dateDiff('hour', EventTime, toDateTime('2018-01-02 23:00:00')) from datasets.hits_v1 order by EventDate desc, timeSlot(EventTime) limit 100 format Null" | clickhouse-benchmark --host=10.92.16.76 -c 40 -i 1000 -d 0`

1. CH from master: first run: 1m8.162s, QPS: 14.855, second run: 1m8.551s, QPS: 14.758
2. CH with variant 2: first run: 1m8.033s, QPS: 14.854, second run: 1m7.195s, QPS: 15.069,

So CH with variant 2 is faster than CH from master (using the mask) :)

**Comment by den-crane** [comment]
@rvasin check this

```sql
SELECT
    toDateTime('1970-01-01 00:00:00') + intDiv(number, 1000) AS EventTime,
    toStartOfWeek(EventTime),
    EventTime,
    toISOYear(EventTime),
    dateDiff('hour', EventTime, toDateTime('2018-01-02 23:00:00'))
FROM numbers_mt(1000000000.)
FORMAT `Null`

Query id: d030e7a2-bd6d-40d3-88c7-4a34f9394aa4

Ok.

0 rows in set. Elapsed: 0.435 sec. Processed 1.00 billion rows, 8.00 GB (2.30 billion rows/s., 18.40 GB/s.)
```

**Comment by rvasin** [comment]
> @rvasin check this
> 
@den-crane Thank you for the good ideas about the tests. I will try it tomorrow and I will share the results. I already thought about using numbers_mt to create many date/times but I did not come to create the my queries with numbers_mt. So I will use your queries for tests.

**Comment by filimonov** [comment]
> @filimonov What I see now that ClickHouse built with variant 2 produces the same results as CCTZ (standalone) or PostgreSQL for the same dates. 

I don't remember the details right now, but i remember there was some issues. Cover it with more tests: try reverse direction? (utc - > Moscow), check the timestamps around time shift etc.

**Comment by rvasin** [comment]
@den-crane 
Here are results of the first test:

`time echo "SELECT toDateTime('1970-01-01 00:00:00') + intDiv(number, 1000) AS EventTime, toStartOfWeek(EventTime),     EventTime, toISOYear(EventTime), dateDiff('hour', EventTime, toDateTime('2018-01-02 23:00:00')) FROM numbers_mt(1000000000.) FORMAT Null" | clickhouse-benchmark --host=$SERVER_IP -c 2 -i 100 -d 0`


  | CH from master |   | CH with variant 2 |  
-- | -- | -- | -- | --
  | Run time | QPS | Run time | QPS
first run | 47.835 | 2.097 | 47.567 | 2.11
second run | 47.563 | 2.109 | 47.649 | 2.104
third run | 47.869 | 2.097 | 47.646 | 2.104
total | 143.267 |   | 142.862 |  

Again variant 2 is faster. But I think these are random fluctuations.

**Comment by rvasin** [comment]
These are the results of running the second test:

`time echo "SELECT toDateTime64('1970-01-01 00:00:00', 3) + intDiv(number, 1000) AS EventTime, toStartOfWeek(EventTime),     EventTime, toISOYear(EventTime), dateDiff('hour', EventTime, toDateTime('2018-01-02 23:00:00')) FROM numbers_mt(1000000000.) FORMAT Null" | clickhouse-benchmark --host=$SERVER_IP -c 2 -i 100 -d 0`
	
  | CH from master |   | CH with variant 2 |  
-- | -- | -- | -- | --
  | Run time | QPS | Run time | QPS
first run | 72.341 | 1.400 | 70.415 | 1.435
second run | 72.606 | 1.391 | 71.491 | 1.414
third run | 72.246 | 1.402 | 71.059 | 1.424
total | 217.193 |   | 212.965 |

**Comment by alexey-milovidov** [comment]
Thank you for the research! Yes, let's do it this way.

**Comment by rvasin** [comment]
I created this pull request #39425 to implement the variant 2 for ranges 1900..2299.

**Comment by alexey-milovidov** [comment]
Thank you for implementing the support for the years 1900..2300!
