### ISSUE TITLE
clickhouse-client SSL Exception: error

### ISSUE THREAD

**Issue by tsolodov** [ClickHouse/ClickHouse#38403]
certificate is correct, It looks like it is OS version specific. I faced this problem on amazon linux:
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"

**According to the test below it expects to have /etc/ssl/cert.pem file in place.**

strace -e open,openat  clickhouse-client --host XXXX                 --secure     --po
rt 9440                   --password XXXXXXXX 2>&1 | grep "such file"

_openat(AT_FDCWD, "/etc/ssl/cert.pem", O_RDONLY) = -1 ENOENT (No such file or directory)_

**Workaround:  sudo ln -s   /etc/pki/tls/certs/ca-bundle.crt  /etc/ssl/cert.pem** 

**Does it reproduce on recent release?**

Yes, ClickHouse client version 22.6.1.1985 (official build).

**How to reproduce**

Deploy AWS EC2 using Amazon Linux2 OS and install clickhouse client from official ym repository. Then try to connect to ClickHouse server using TLS.

**Expected behavior**

clickhouse-client picks CA certs from other locations, like /etc/pki/tls/certs/

**Comment by filimonov** [comment]
Related https://github.com/ClickHouse/ClickHouse/issues/17803

**Comment by yakov-olkhovskiy** [comment]
fix in progress - issue related to poco/boringssl
https://github.com/ClickHouse/poco/pull/62
