### ISSUE TITLE
Nonstandard behavior of `NOT IN (...NULL...)`

### ISSUE THREAD

**Issue by MaceWindu** [ClickHouse/ClickHouse#38439]
version: 22.6.1.1985
`transform_null_in`: 0 (default)

```sql
-- correct: returns empty dataset
select * from (select 1 as col union all select null) t where t.col in (null, 2)

-- incorrect?: returns `1`
select * from (select 1 as col union all select null) t where t.col not in (null, 2)
```

Second query returns 1 while most of databases evaluate `not in (..., null, ...)` as non-true condition.

Behavior observed for:
- DB2 LUW (and other DB2 versions probably)
- Firebird
- Informix
- MySQL/MariaDB
- Oracle
- Pgsql
- SAP HANA 2
- SQL CE
- SQLite
- SQL Server
- SAP ASE

Same behavior as current ClickHouse behavior observed for:
- Access

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/34737
