### ISSUE TITLE
Strange toLastDayOfMonth behavior for DateTime64

### ISSUE THREAD

**Issue by ilejn** [ClickHouse/ClickHouse#38435]
SELECT toLastDayOfMonth(toDateTime64('1950-02-02 10:20:30', 3));

:) 2129-08-04

SELECT version()

:) 22.6.1.1978

Actually reproduced against  play.clickhouse.com

Looking into this.

DateTime32 is not affected, other date functions seem to be Ok.

**Comment by ilejn** [comment]
As far as I can see the LUT logic is fine, while
```
struct ToLastDayOfMonthImpl
{
    static constexpr auto name = "toLastDayOfMonth";

    static inline UInt16 execute(Int64 t, const DateLUTImpl & time_zone)
    {
        return time_zone.toLastDayNumOfMonth(time_zone.toDayNum(t));
    }
    static inline UInt16 execute(UInt32 t, const DateLUTImpl & time_zone)
    {
        return time_zone.toLastDayNumOfMonth(time_zone.toDayNum(t));
    }
    static inline UInt16 execute(Int32 d, const DateLUTImpl & time_zone)
    {
        return time_zone.toLastDayNumOfMonth(ExtendedDayNum(d));
    }
    static inline UInt16 execute(UInt16 d, const DateLUTImpl & time_zone)
    {
        return time_zone.toLastDayNumOfMonth(DayNum(d));
    }
```
in DateTimeTransforms.h looks problematic.
Here we try to fit Int32 into UInt16, and we do have negative numbers here for pre-1970 dates.

**Comment by ilejn** [comment]
toLastDayOfMonth returns date, not number of days in a month (which might be initially intended).

**Comment by rvasin** [comment]
According to #33501 and #34394 this function initially intended to return date (not number of days). In fact it has registered alias LAST_DATE. 
```
void registerFunctionToLastDayOfMonth(FunctionFactory & factory)
{
    factory.registerFunction<FunctionToLastDayOfMonth>();

    /// MySQL compatibility alias.
    factory.registerFunction<FunctionToLastDayOfMonth>("LAST_DAY", FunctionFactory::CaseInsensitive);
}
```
Which is a standard function in Oracle and MySQL. It returns date.

**Comment by ilejn** [comment]
Yes, sure, but the function name is toLastDay**Num**OfMonth.

**Comment by rvasin** [comment]
Very interesting that function:
`inline Time toLastDayOfMonth(DateOrTime v) const`
is defined. But it's never used in CH code (it's used only in gtest_DateLUTImpl.cpp).
Instead toLastDay**Num**OfMonth function is used.

**Comment by ilejn** [comment]
The code looks like there is no quick fix, it is designed in this way.

In documentation we have
``
The return type toStartOf* functions described below is Date or DateTime. Though these functions can take DateTime64 as an argument, passing them a DateTime64 that is out of the normal range (years 1925 - 2283) will give an incorrect result.
``
Having in mind that 
* DateTime starts at 1970
* It is not about DateTime64, but about DateTime32 as well
* It is not about toStartOf* only , but about anything any date function that returns date
* It is not about out of 1925 - 2283, it is about pre-1970

We can either extend the warning or fix the issue.



ilejn-latitude-7490 :) SELECT toStartOfYear(toDateTime32('1930-01-01 00:00:00'));

SELECT toStartOfYear(toDateTime32('1930-01-01 00:00:00'))

Query id: 9cbb8fab-7752-4228-a915-e38991ed465f

┌─toStartOfYear(toDateTime32('1930-01-01 00:00:00'))─┐
│                                         1970-01-01 │
└────────────────────────────────────────────────────┘

1 row in set. Elapsed: 0.012 sec. 

ilejn-latitude-7490 :) SELECT toStartOfYear(toDateTime64('1930-01-01 00:00:00', 3));

SELECT toStartOfYear(toDateTime64('1930-01-01 00:00:00', 3))

Query id: a521ac4a-01ef-4317-a1d3-4e3be785d5cf

┌─toStartOfYear(toDateTime64('1930-01-01 00:00:00', 3))─┐
│                                            2109-06-07 │
└───────────────────────────────────────────────────────┘

1 row in set. Elapsed: 0.013 sec.


Honestly, it looks too bad to be true. 
Don't I misunderstand something?

**Comment by ilejn** [comment]
toLastDayOfMonth works exactly
:) SELECT toLastDayOfMonth(toDateTime64('1950-02-02 10:20:30', 3))
2129-08-04
toLastDayOfMonth works exactly as conversion to Date
:) SELECT toDate(toDateTime64('1950-02-28 10:20:30', 3))
2129-08-04
so it is not a problem of a toLastDayOfMonth at all.

**Comment by ilejn** [comment]
1950-02-28 is -7247 (number of days from 1970-01-01)
toUInt16(-7247) is 58289
toDate(58289) is 2129-08-04

**Comment by ilejn** [comment]
I've created a mockup https://github.com/arenadata/ClickHouse/commit/f1064d4c88406433fbe44efd33b1ac05234e4867
Works Ok.
It brings return types deduction we have for date internal arithmetic to date functions.
The code should be cleaned up, improved, and maybe unified with FunctionDateOrDateTimeAddInterval. 
I think that realistically we (Arenadata) can make PR by the end of August.

**Comment by alexey-milovidov** [comment]
It will require changing the function return type, which is only possible if you introduce a new setting for this behavior and cover it in the `compatibility` setting.

**Comment by ilejn** [comment]
> It will require changing the function return type, which is only possible if you introduce a new setting for this behavior and cover it in the `compatibility` setting.

Yes, correct, Date is not enough, it is going to be an incompatible change.
I believe that it is worth doing anyway.
Alternatively, we can introduce toLastDayOfMonth64 and suchlike, but it looks too heavy for me.

**Comment by alexey-milovidov** [comment]
So, the proposal is to change the result type of Date-returning functions of DateTime64 from Date to Date32.
Ok, let's try to do it until it's too late :)

**Comment by rvasin** [comment]
@alexey-milovidov  It’s about 10:00 PM in my UTC+3 timezone. I hope it’s not too late :)
After a talk with @ilejn  I want to say that I started to work in this issue.

I am trying to compare pros and cons of different approaches. Do we need some kind of intelligent “return types deduction“ or should we simply use Date32 for return types when needed in a more simple way?
 
What I see now that  some part of functions modified in https://github.com/arenadata/ClickHouse/commit/f1064d4c88406433fbe44efd33b1ac05234e4867  work in master branch. So we don’t need to touch at all these functions. For example,

SELECT toYear(toDateTime64('1930-01-01 00:00:00', 3));
1930

SELECT toYYYYMMDD(toDateTime64('1930-01-01 00:00:00', 3));
19300101

These functions work fine. 

It’s not clear with toTime function:
SELECT toTime(toDateTime64('1930-01-01 10:15:00', 3));
1970-01-02 10:15:00

SELECT toTime(toDateTime('1989-01-01 10:15:00', 3));
1970-01-02 10:15:00
It seems like it’s correct too. @den-crane  could we please comment is it OK output of toTime?

It’s seems what is really needed to correct : all toStartOf and toLast functions for the case when they accept DateTime64 or Date32 as arguments. So I will make some code analysis first and then probably ask here for advice about the best approach to use.

**Comment by den-crane** [comment]
>It seems like it’s correct too. @den-crane could we please comment is it OK output of toTime?

Yes, I think it's correct, at least consistent.

Though it's surprising date `1970-01-02`, I never probably used this func. before.

```sql
ClickHouse client version 20.8.17.25 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 20.8.17 revision 54438.

d3005c90f081 :) SELECT toTime(now());

SELECT toTime(now())

┌───────toTime(now())─┐
│ 1970-01-02 20:04:35 │
└─────────────────────┘
```

**Comment by alexey-milovidov** [comment]
@ilejn yes, looks like we need to replace the Date return type to Date32 return type whenever the function takes DateTIme64,
and from DateTime to DateTime64 (most likely already have done a long time ago) whenever the function takes DateTIme64.

About `toTime` function. It normalized the date component to some predetermined point of time and keeps the offset from midnight. 1970-01-02 has been used, because it does not underflow for all timezones.

**Comment by rvasin** [comment]
@alexey-milovidov  OK. Let’s consider that toTime function works fine.

To start the correction of the issue from just one ToLastDayOfMonthImpl function, I created the following Plan B branch: https://github.com/ClickHouse/ClickHouse/compare/master...arenadata:ClickHouse:ADQM-528-B

It's clear that ideally the logic should be like this:

if argument is Date then toLastDayOfMonth function must return Date
if argument is DataTime then the return is Date
if argument is Date32 then the return is Date32
if argument is DateTime64 then the return is Date32

My plan B branch works fine:
```
SELECT toLastDayOfMonth(toDate('1980-01-03'));
1980-01-31
SELECT toTypeName(toLastDayOfMonth(toDate('1980-01-03')));
Date32

SELECT toLastDayOfMonth(toDateTime('1980-02-02 10:20:30', 3));
1980-02-29
SELECT toTypeName(toLastDayOfMonth(toDateTime('1980-02-02 10:20:30', 3)));
Date32

SELECT toLastDayOfMonth(toDate32('1950-02-02'));
1950-02-28
SELECT toTypeName(toLastDayOfMonth(toDate32('1950-02-02')));
Date32

SELECT toLastDayOfMonth(toDateTime64('1950-02-02 10:20:30', 3));
1950-02-28
SELECT toTypeName(toLastDayOfMonth(toDateTime64('1950-02-02 10:20:30', 3)));
Date32
```

Now the function always returns Date32 as shown by toTypeName.
And it create backward compatibility problems. Right? 

One of possible solutions could be creation of  toLastDayOfMonth32. The following corrections are needed:
1. if Date32 or DateTime64  is passed as argument to toLastDayOfMonth. Then display an exception that these types of arguments are not supported. It will also create backward compatibility problems.
2.  toLastDayOfMonth32 function should work only with Date32 or DateTime64   arguments (not with Date or DateTime).

Right now I don’t like the idea of creation  toLastDayOfMonth32 and such functions. But as I see FunctionDateOrDateTimeToSomething is designed in such way that it only allows one return type. 
Maybe we should create another class: FunctionDateOrDateTimeToDateorDate32 which will return  Date or Date32 based on arguments. So right now I am making analysis of Ilya’s branch maybe do some kind of cleanup or concept borrowing from the branch to create more balanced and clear solution.

I tested all functions in Ilya’s branch I see the functions which does not work:
* all toLast functions
* all toStartOf functions
* toMonday
* timeSlot
* all toRelative functions which must be tested more carefully later.

All other functions works fine. So I think it's good to start from correction of toLastDayOfMonth function, then create a working concept and then correct other functions and correct corresponding tests.

**Comment by ilejn** [comment]
> @ilejn yes, looks like we need to replace the Date return type to Date32 return type whenever the function takes DateTIme64, and from DateTime to DateTime64 (most likely already have done a long time ago) whenever the function takes DateTIme64.

Yes.
But the problem is we have number of functions that work with Date, but not with Date32.
So the code like 
`SELECT dateDiff('day', toLastDayOfMonth(toDateTime('1978-02-02 10:20:30', 3)), toLastDayOfMonth(toDateTime('1980-02-02 10:20:30', 3)))`   (thanks to Roman for the example)
whould be invalidated by the change.

The solution seems obvious: functions that accept only Date should be modified in the similar way.

**Comment by rvasin** [comment]
In this commit https://github.com/ClickHouse/ClickHouse/commit/19cb6d87c86d782d0c2eca9aa49cff997274d823 I implemented FunctionDateOrDateTimeToDateOrDate32 and I started to use it for  toLastDayOfMonth function. 

The results are correct now: 
toLastDayOfMonth returns Date for Date or DateTime arguments 
and it returns Date32 for Date32 or DateTime4 arguments:

```
SELECT toLastDayOfMonth(toDate('1980-01-03'));
1980-01-31
SELECT toTypeName(toLastDayOfMonth(toDate('1980-01-03')));
Date

SELECT toLastDayOfMonth(toDateTime('1980-02-02 10:20:30', 3));
1980-02-29
SELECT toTypeName(toLastDayOfMonth(toDateTime('1980-02-02 10:20:30')));
Date

SELECT toLastDayOfMonth(toDate32('1950-02-02'));
1950-02-28
SELECT toTypeName(toLastDayOfMonth(toDate32('1950-02-02')));
Date32

SELECT toLastDayOfMonth(toDateTime64('1950-02-02 10:20:30', 3));
1950-02-28
SELECT toTypeName(toLastDayOfMonth(toDateTime64('1950-02-02 10:20:30', 3)));
Date32

```

BTW I did not know that:
```
SELECT toTypeName(toDateTime('1980-02-02 10:20:30'));
DateTime

SELECT toTypeName(toDateTime('1980-02-02 10:20:30',3));
DateTime64(3)
```
What is also interesting: Date and Date32 types don't have time zone support. 

So for example in getReturnTypeImpl I commented it: 
```
// return std::make_shared<DataTypeDate>(time_zone);
return std::make_shared<DataTypeDate>();
```
the same case when argument is DateTime64 in this case scale and timezone is not needed at all:
```
// return std::make_shared<DataTypeDate32>(scale, extractTimeZoneNameFromFunctionArguments(arguments, 1, 0));
return std::make_shared<DataTypeDate32>();
```
