### ISSUE TITLE
Got ILLEGAL_TYPE_OF_ARGUMENT when query with sub-queries with enable_positional_arguments = 1  

### ISSUE THREAD

**Issue by nkthien** [ClickHouse/ClickHouse#38433]
**Describe the unexpected behaviour**
I need function to use number as argument in group by clause and order by clause just as other database system. We migrate data from other dbs and we have existing sql that already use number as argument. So I turn on enable_positional_arguments setting to allow clickhouse to parse number argument in group by clause and order by clause.
The query works fine when it is a flatten query, but when the number part is in a nested query (select from result of another query), it throws a ILLEGAL_TYPE_OF_ARGUMENT exception.

**How to reproduce**
```
set enable_positional_arguments = 1

select count(*) 
from (
    select Region, sum(Revenue)
    from test.sales
    group by 1
)
==> got: Received exception from server (version 21.12.4):
Code: 43. DB::Exception: Received from localhost:9000. DB::Exception: Illegal value (aggregate function) for positional argument in GROUP BY. (ILLEGAL_TYPE_OF_ARGUMENT)

```
Same behavior happens to other aggregate function like sum, min, max...
and it also happens when I try to rewrite the query with WITH Clause
* ClickHouse server version: 
```
ClickHouse client version 21.12.4.1 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 21.12.4 revision 54452.
```

* Non-default settings: enable_positional_arguments = 1

**Expected behavior**
Query executed normally as when enable_positional_arguments = 0 and use alias_name in group by and order by clause.

**Error message and/or stacktrace**
Received exception from server (version 21.12.4):
Code: 43. DB::Exception: Received from localhost:9000. DB::Exception: Illegal value (aggregate function) for positional argument in GROUP BY. (ILLEGAL_TYPE_OF_ARGUMENT)

**Comment by kssenii** [comment]
Works in later versions:
```
SELECT count(*)
FROM
(
    SELECT
        number,
        number
    FROM numbers(10)
    GROUP BY 1
)
SETTINGS enable_positional_arguments = 1

Query id: c04bcbab-5e4a-46fa-b654-cf14d677e902

┌─count()─┐
│      10 │
└─────────┘

1 row in set. Elapsed: 0.008 sec.
```

**Comment by nkthien** [comment]
Your query works for me too. It seems like it happens with data on real table.

**Comment by nkthien** [comment]
> Works in later versions:
> 
> ```
> SELECT count(*)
> FROM
> (
>     SELECT
>         number,
>         number
>     FROM numbers(10)
>     GROUP BY 1
> )
> SETTINGS enable_positional_arguments = 1
> 
> Query id: c04bcbab-5e4a-46fa-b654-cf14d677e902
> 
> ┌─count()─┐
> │      10 │
> └─────────┘
> 
> 1 row in set. Elapsed: 0.008 sec.
> ```
Your query works for me too. I still get the error with queries on data on real tables.

**Comment by kssenii** [comment]
This still works:
```
ip-172-31-4-213.eu-west-1.compute.internal :) create table tp (a Int32) engine=MergeTree() order by tuple();

CREATE TABLE tp
(
    `a` Int32
)
ENGINE = MergeTree
ORDER BY tuple()

Query id: 1c3fce4f-1229-4012-8ed0-74ec8caed43d

Ok.

0 rows in set. Elapsed: 0.010 sec.

ip-172-31-4-213.eu-west-1.compute.internal :) select count(*)
                                              from (
                                                  select a, sum(a)
                                                  from tp
                                                  group by 1
                                              ) settings enable_positional_arguments=1

SELECT count(*)
FROM
(
    SELECT
        a,
        sum(a)
    FROM tp
    GROUP BY 1
)
SETTINGS enable_positional_arguments = 1

Query id: 9f1df578-f357-498f-8b49-d6f30452adc3

┌─count()─┐
│       0 │
└─────────┘

1 row in set. Elapsed: 0.009 sec.
```

**Comment by nkthien** [comment]
I try your case and it also works. But when I add another column to the table and group by other column, the problem is occured.
It happens when grouped column differs from aggregated column I think.

Can you check this case:
```
clickhouse01 :) create table tp2(first_col String, second_col Int32) engine = MergeTree() order by tuple()

CREATE TABLE tp2
(
    `first_col` String,
    `second_col` Int32
)
ENGINE = MergeTree
ORDER BY tuple()

Query id: 891eea82-8f42-465c-8291-ab9c85c230ec

Ok.

0 rows in set. Elapsed: 0.211 sec. 


clickhouse01 :) select count(*) from (select first_col, count(second_col) from tp2 group by 1) SETTINGS enable_positional_arguments = 1

SELECT count(*)
FROM
(
    SELECT
        first_col,
        count(second_col)
    FROM tp2
    GROUP BY 1
)
SETTINGS enable_positional_arguments = 1

Query id: 4e266aa4-d2b9-4f24-b81d-446bdfa9bc24


0 rows in set. Elapsed: 0.002 sec. 

Received exception from server (version 22.1.3):
Code: 43. DB::Exception: Received from localhost:9000. DB::Exception: Illegal value (aggregate function) for positional argument in GROUP BY. (ILLEGAL_TYPE_OF_ARGUMENT)


clickhouse01 :) select total from (select first_col, count(second_col) as total from tp2 group by 1) SETTINGS enable_positional_arguments = 1

SELECT total
FROM
(
    SELECT
        first_col,
        count(second_col) AS total
    FROM tp2
    GROUP BY 1
)
SETTINGS enable_positional_arguments = 1

Query id: 7a06bee5-f8cb-4fda-be5c-fce4daa5dba0


0 rows in set. Elapsed: 0.005 sec. 

Received exception from server (version 22.1.3):
Code: 43. DB::Exception: Received from localhost:9000. DB::Exception: Illegal value (aggregate function) for positional argument in GROUP BY. (ILLEGAL_TYPE_OF_ARGUMENT)


```
