### ISSUE TITLE
ALTER TABLE xxx SET PROJECTION xxx_different_order AS MAIN

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#38442]
**Use case**

Table is just set of projections, one of them is **main** (basically what is table now)
And we can easily change what is considered as main projection now. (with removal of old **main** projection in future)

For example it will allow us to run experiments with new table order by, codecs, types on subset of queries and promotion of best working schema as main schema silently. 

**Describe the solution you'd like**

```
ALTER TABLE xxx SET PROJECTION xxx_different_order AS MAIN;
ALTER TABLE xxx DROP PROJECTION xxx_old_main;
```

**Describe alternatives you've considered**

ALTER TABLE MODIFY ORDER BY https://github.com/ClickHouse/ClickHouse/pull/28065

**Additional context**

Related https://github.com/ClickHouse/ClickHouse/pull/34944

**Comment by alexey-milovidov** [comment]
Projections are non-perfect, and adding more features is risky.
