### ISSUE TITLE
How to write a executable UDF script to read the query result and retrun the modified result?

### ISSUE THREAD

**Issue by srikanthccv** [ClickHouse/ClickHouse#38446]
Hello 👋 ,

I am trying to use https://clickhouse.com/docs/en/sql-reference/functions/#executable-user-defined-functions to perform some custom computation and produce the final result. I could get the examples provided in the documentation to work but I have little complex requirement. I am trying to figure out how to pass the query result table and get back the new computed table? Assume that number of columns and thier types are fixed and know beforehand. I couldn't find any documentation or examples around it. It would be really awesome if you can give me some pointers about how to achieve this.

**Comment by filimonov** [comment]
Check that test: 
https://github.com/ClickHouse/ClickHouse/blob/36d1c8238a03d2dbe29c4b872ec50bfeb63fa693/tests/integration/test_executable_table_function/test.py#L95

BTW: it looks like documentation for that is missing...

**Comment by e-mars** [comment]
@DanRoscigno looks like doc update.

**Comment by srikanthccv** [comment]
Thank everyone for the pointers. It would be great if doc contained some clear example with input/output table with few columns reflecting the real world needs.

**Comment by pkit** [comment]
@srikanthccv 
```sql
SELECT * FROM executable('<your script>', '<data format>', '<output schema>', <source0>, <source1>, ...)
```
Example:
```sql
CREATE TABLE table1 (id UInt32, name String) ENGINE=Memory();
INSERT INTO table1 VALUES (0, 'aaa'), (1, 'bbb'), (2, 'ccc');
SELECT * FROM executable('my_script.py', 'TabSeparated', 'id UInt32, name String', (SELECT id, name FROM table1));
```
`my_script.py` can look like this:
```python
#!/usr/bin/python3

import sys
import traceback

if __name__ == "__main__":
    fd = open("/tmp/debug.log", "w")
    try:
        for line in sys.stdin:
            row = line.rstrip("\n").split("\t")
            print("\t".join([str(int(row[0]) + 1), row[1] + "_done"]))
    except Exception as e:
        traceback.print_exc(file=fd)
        fd.close()
    sys.stdout.flush()

```
```bash
$ ./clickhouse-client --query="SELECT * FROM executable('my_script.py', 'TabSeparated', 'id UInt32, name String', (SELECT id, name FROM table1))"
1	aaa_done
2	bbb_done
3	ccc_done
```
As you can see it adds 1 to each `id` and adds `"_done"` to each `name`
Don't forget to `chmod +x my_script.py`
Here `/tmp/debug.log` is just a convenient way to get some errors when your script fails

**Comment by srikanthccv** [comment]
@pkit Thanks for the full example.

**Comment by rfraposa** [comment]
The `executable` table function and `Executable` table engine are both now described in detail in the docs: https://clickhouse.com/docs/en/engines/table-functions/executable
