### ISSUE TITLE
clickhouse dictionary source and named collection for secure connections

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#38450]
```sql
CREATE DICTIONARY IF NOT EXISTS dict (
...
)
PRIMARY KEY 
SOURCE(
    CLICKHOUSE(
        NAME named_col1 TABLE 'foo'
    )
)
```

and 

```xml
<clickhouse>
    <named_collections>
        <named_col1>
            <host>localhost</host>
            <user>default</user>
            <port>9440</port>
            <secure>1</secure>
        </named_col1>
    <named_collections>
</clickhouse>
```

doesn't work. 

Workaround:
```
CREATE DICTIONARY IF NOT EXISTS dict (
...
)
PRIMARY KEY 
SOURCE(
    CLICKHOUSE(
        NAME named_col1 TABLE 'foo'
    )
   SECURE 1
)
```

is not very 'clear' (mixing the responsibilities). 

I guess the reason is here (settings_config_prefix vs config_prefix):

https://github.com/ClickHouse/ClickHouse/blob/bc166e439427cfe6e2a33a74fdc68c2a3228f6ed/src/Dictionaries/ClickHouseDictionarySource.cpp#L231-L235

The similar problem may exists with remote / remoteSecure (maybe we can generalize remote to work with secure also?).

**Comment by ilejn** [comment]
I do not see a similarity between this case and remote/remoteSecure.
The choice between remote and remoteSecure is explicit, based on a function name.
Port may be specified in addresses_expr (host:port), if not it is from local config or default.
@filimonov am I missing something?

**Comment by filimonov** [comment]
I've meant passing the named_collection to remote as a parameter. Now if we will change the connection setting (in named collection) to use secure porr - that will not work (need to change remote to remoteSecure in the query)

**Comment by ilejn** [comment]
I see. Did not realise that remote/remoteSecure can use named_collections (because it is not mentioned https://clickhouse.com/docs/en/sql-reference/table-functions/remote/#syntax ).

Such generalization looks natural, agree.

**Comment by ilejn** [comment]
Fixed by https://github.com/ClickHouse/ClickHouse/pull/46323
