### ISSUE TITLE
Object/JSON data type: Allow querying field by name

### ISSUE THREAD

**Issue by macobo** [ClickHouse/ClickHouse#38478]
**Use case**

One use-case for semi-structured data like the new `Object('json')` data type is dealing with customer-provided data in a clean way.

The current way to query fields off of a Object is either `SELECT object_column.field` or `SELECT object_column."field"`. For user-provided inputs, this can easily lead to query sanitization/SQL injection problems.

**Describe the solution you'd like**

Support `SELECT object_column['field']` for selecting fields based off of strings. This way normal SQL sanitization methods can be used to pass field names in clickhouse client libraries.

Note that non-static strings need not be supported for this usecase and may error - this is primarily about sanitization. 

Same goes for implementation - it's okay if this is implemented as a normalization/rewrite rule.

**Describe alternatives you've considered**

Solving this via functions, e.g. `SELECT object_field(object_column, 'field')`

**Additional context**

cc @CurtizJ who added this exciting new feature.

**Comment by alexey-milovidov** [comment]
Should be nice to have, and it is also useful for named tuples.
