### ISSUE TITLE
`urlCluster` table function

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#38499]
**Use case**

Distributed processing of a large number of files.

**Describe the solution you'd like**

Similar to `s3Cluster` and `hdfsCluster`

**Additional context**

Note that the url table function only supports `{...}` expansions, not `*` or `?`.

**Comment by white-cc** [comment]
I'd like to try :)

**Comment by white-cc** [comment]
I'd like to try :) @alexey-milovidov

**Comment by attack204** [comment]
@alexey-milovidov Can you assign it to me? I have read the s3Cluster and hdfsCluster source code and maybe 5-7 days are needed to code.
