### ISSUE TITLE
Clickhouse does not work on a system without sse4 even though I disabled this feature when build

### ISSUE THREAD

**Issue by stm32repo** [ClickHouse/ClickHouse#38508]
System: Ubuntu 22.04 LTS, kernel 4.19.0-20-amd64
Clickhouse version: v22.3.2.2-lts
cmake version: 3.22.1
clang version: 14.0.0
Compile options:
`cmake -DENABLE_SSE:BOOL=OFF -DENABLE_SSE41:BOOL=OFF -DENABLE_SSE42:BOOL=OFF -DENABLE_PCLMULQDQ:BOOL=OFF -DENABLE_POPCNT:BOOL=OFF -DHAVE_PCLMULQDQ:INTERNAL=0 -DLLVM_TARGETS_TO_BUILD:STRING=X86 -DENABLE_SSSE3:BOOL=OFF -DCMAKE_BUILD_TYPE=Release ../`
Down trace:

> 2022.06.16 11:44:09.173318 [ 14662 ] {} <Trace> BaseDaemon: Received signal 4                                                                                                      [124/1569]
> 2022.06.16 11:44:09.183452 [ 14945 ] {} <Fatal> BaseDaemon: ########################################
> 2022.06.16 11:44:09.183631 [ 14945 ] {} <Fatal> BaseDaemon: (version 22.3.2.1, build id: 3EE2622E198FA62B) (from thread 14663) (query_id: a45f61be-f188-439d-a8b2-d4ccd5d2a5bb) (query: INSERT INTO table (uind, name, date) VALUES) Received signal Illegal instruction (4)
> 2022.06.16 11:44:09.183698 [ 14945 ] {} <Fatal> BaseDaemon: Illegal operand.
> 2022.06.16 11:44:09.183765 [ 14945 ] {} <Fatal> BaseDaemon: Stack trace: 0x103a6106 0x11ee523c 0x11edbf72 0x11ef8aef 0x11efc71f 0x121f765e 0x121f21a7 0x121ee2fd 0x121ec9b4 0x13046b44 0x121d
> 7c05 0x121d977f 0x125341bc 0x1253272d 0x12e44a3f 0x12e52139 0x13a46c07 0x13a470c7 0x13bb1a87 0x13baf686 0x7f6e4cc99b43 0x7f6e4cd2abb4
> 2022.06.16 11:44:10.000112 [ 14731 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 500.10 MiB, peak 509.81 MiB, will set to 702.54 MiB (RSS), difference: 202.43 MiB
> 2022.06.16 11:44:10.417335 [ 14662 ] {} <Trace> BaseDaemon: Received signal -1
> 2022.06.16 11:44:10.417416 [ 14662 ] {} <Fatal> BaseDaemon: (version 22.3.2.1, build id: 3EE2622E198FA62B) (from thread 14945) Terminate called for uncaught exception:
> 2022.06.16 11:44:10.417485 [ 14662 ] {} <Fatal> BaseDaemon: Code: 465. DB::Exception: invalid info version. (CANNOT_PARSE_DWARF), Stack trace (when copying this message, always include the lines below):
> 2022.06.16 11:44:10.417514 [ 14662 ] {} <Fatal> BaseDaemon:
> 2022.06.16 11:44:10.417539 [ 14662 ] {} <Fatal> BaseDaemon: 0. ./build/./contrib/libcxx/include/exception:133: Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x13b508cc in /usr/bin/clickhouse
> 2022.06.16 11:44:10.417631 [ 14662 ] {} <Fatal> BaseDaemon: 1. ./build/./src/Common/Exception.cpp:58: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x9f2f59a in /usr/bin/clickhouse
> 2022.06.16 11:44:10.417689 [ 14662 ] {} <Fatal> BaseDaemon: 2. ./build/./src/Common/Dwarf.cpp:0: DB::Dwarf::getCompilationUnit(std::__1::basic_string_view<char, std::__1::char_traits<char>>, unsigned long) @ 0x9f4c5d0 in /usr/bin/clickhouse
> 2022.06.16 11:44:10.417764 [ 14662 ] {} <Fatal> BaseDaemon: 3. ./build/./src/Common/Dwarf.cpp:1141: DB::Dwarf::findAddress(unsigned long, DB::Dwarf::LocationInfo&, DB::Dwarf::LocationInfoMode, std::__1::vector<DB::Dwarf::SymbolizedFrame, std::__1::allocator<DB::Dwarf::SymbolizedFrame> >&) const @ 0x9f4dd12 in /usr/bin/clickhouse
> 2022.06.16 11:44:10.417832 [ 14662 ] {} <Fatal> BaseDaemon: 4. ./build/./src/Common/StackTrace.cpp:361: toStringEveryLineImpl(bool, std::__1::array<void*, 45ul> const&, unsigned long, unsigned long, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>) @ 0x9f4796f in /usr/bin/clickhouse
> 2022.06.16 11:44:10.417893 [ 14662 ] {} <Fatal> BaseDaemon: 5. ./build/./contrib/libcxx/include/functional:2191: StackTrace::toStringEveryLine(std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>) const @ 0x9f47670 in /usr/bin/clickhouse
> 2022.06.16 11:44:10.417952 [ 14662 ] {} <Fatal> BaseDaemon: 6. ./build/./contrib/libcxx/include/functional:2191: SignalListener::onFault(int, siginfo_t const&, ucontext_t*, StackTrace const&, unsigned int, DB::ThreadStatus*) const @ 0x11886ea9 in /usr/bin/clickhouse
> 2022.06.16 11:44:10.418013 [ 14662 ] {} <Fatal> BaseDaemon: 7. ./build/./contrib/libcxx/include/memory:1655: void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__
> thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, SignalListener::run()::'lambda'()> >(void*) @ 0x11885db5 in /usr/bin/clickhouse
> 2022.06.16 11:44:10.418074 [ 14662 ] {} <Fatal> BaseDaemon: 8. ? @ 0x7f6e4cc99b43 in ?
> 2022.06.16 11:44:10.418130 [ 14662 ] {} <Fatal> BaseDaemon: 9. clone @ 0x7f6e4cd2abb4 in ?
> 2022.06.16 11:44:10.418186 [ 14662 ] {} <Fatal> BaseDaemon:  (version 22.3.2.1)
> 2022.06.16 11:44:10.418247 [ 14662 ] {} <Trace> BaseDaemon: Received signal 6
> 2022.06.16 11:44:10.427445 [ 14950 ] {} <Fatal> BaseDaemon: ########################################

**Comment by filimonov** [comment]
Find/show the query `a45f61be-f188-439d-a8b2-d4ccd5d2a5bb` in the logs or in the system.query_log 

What is the CPU you use?

**Comment by tavplubix** [comment]
CPUs without SSE4 are not supported

**Comment by stm32repo** [comment]
Error after service restart:
> 2022.06.29 08:49:37.703556 [ 2650 ] {} <Fatal> BaseDaemon: ########################################
> 2022.06.29 08:49:37.703603 [ 2650 ] {} <Fatal> BaseDaemon: (version 22.3.2.1, build id: BCC43B9323C4578F07A4171D3EBD6D30E1C416ED) (from thread 2646) (no query) Received signal Illegal instruction (4)
> 2022.06.29 08:49:37.703629 [ 2650 ] {} <Fatal> BaseDaemon: Illegal operand.
> 2022.06.29 08:49:37.703664 [ 2650 ] {} <Fatal> BaseDaemon: Stack trace: 0xb9b5042 0xd11fd7c 0xd1165f2 0xd135d99 0xd78bf05 0xd3279e3 0xd03054e 0xd03dbe0 0xd061f2a 0xedd0897 0xedd1fcc 0xedcef30 0xedd11f3 0x7f1d20ed5b43 0x7f1d20f66bb4
> 2022.06.29 08:49:37.703738 [ 2650 ] {} <Fatal> BaseDaemon: 3. std::__1::pair<std::__1::__hash_iterator<std::__1::__hash_node<unsigned long, void*>*>, bool> std::__1::__hash_table<unsigned long, std::__1::hash<unsigned long>, std::__1::equal_to<unsigned long>, std::__1::allocator<unsigned long> >::__emplace_unique_key_args<unsigned long, unsigned long const&>(unsigned long const&, unsigned long const&) @ 0xb9b5042 in /usr/bin/clickhouse
> 2022.06.29 08:49:37.703814 [ 2650 ] {} <Fatal> BaseDaemon: 4. DB::setLazyExecutionInfo(DB::ActionsDAG::Node const*, DB::(anonymous namespace)::ActionsDAGReverseInfo const&, std::__1::unordered_map<DB::ActionsDAG::Node const*, DB::IFunctionBase::ShortCircuitSettings, std::__1::hash<DB::ActionsDAG::Node const*>, std::__1::equal_to<DB::ActionsDAG::Node const*>, std::__1::allocator<std::__1::pair<DB::ActionsDAG::Node const* const, DB::IFunctionBase::ShortCircuitSettings> > > const&, std::__1::unordered_map<DB::ActionsDAG::Node const*, DB::(anonymous namespace)::LazyExecutionInfo, std::__1::hash<DB::ActionsDAG::Node const*>, std::__1::equal_to<DB::ActionsDAG::Node const*>, std::__1::allocator<std::__1::pair<DB::ActionsDAG::Node const* const, DB::(anonymous namespace)::LazyExecutionInfo> > >&) @ 0xd11fd7c in /usr/bin/clickhouse
> 2022.06.29 08:49:37.703847 [ 2650 ] {} <Fatal> BaseDaemon: 5. DB::ExpressionActions::ExpressionActions(std::__1::shared_ptr<DB::ActionsDAG>, DB::ExpressionActionsSettings const&) @ 0xd1165f2 in /usr/bin/clickhouse
> 2022.06.29 08:49:37.703872 [ 2650 ] {} <Fatal> BaseDaemon: 6. DB::ExpressionAnalyzer::getActions(bool, bool, DB::CompileExpressions) @ 0xd135d99 in /usr/bin/clickhouse
> 2022.06.29 08:49:37.703898 [ 2650 ] {} <Fatal> BaseDaemon: 7. DB::validateColumnsDefaultsAndGetSampleBlock(std::__1::shared_ptr<DB::IAST>, DB::NamesAndTypesList const&, std::__1::shared_ptr<DB::Context const>) @ 0xd78bf05 in /usr/bin/clickhouse
> 2022.06.29 08:49:37.703927 [ 2650 ] {} <Fatal> BaseDaemon: 8. DB::InterpreterCreateQuery::getColumnsDescription(DB::ASTExpressionList const&, std::__1::shared_ptr<DB::Context const>, bool) @ 0xd3279e3 in /usr/bin/clickhouse
> 2022.06.29 08:49:37.703956 [ 2650 ] {} <Fatal> BaseDaemon: 9. DB::createTableFromAST(DB::ASTCreateQuery, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool) @ 0xd03054e in /usr/bin/clickhouse
> 2022.06.29 08:49:37.703995 [ 2650 ] {} <Fatal> BaseDaemon: 10. DB::DatabaseOrdinary::loadTableFromMetadata(std::__1::shared_ptr<DB::Context>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::QualifiedTableName const&, std::__1::shared_ptr<DB::IAST> const&, bool) @ 0xd03dbe0 in /usr/bin/clickhouse
> 2022.06.29 08:49:37.704025 [ 2650 ] {} <Fatal> BaseDaemon: 11. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::TablesLoader::startLoadingIndependentTables(ThreadPoolImpl<ThreadFromGlobalPool>&, unsigned long)::$_1, void ()> >(std::__1::__function::__policy_storage const*) @ 0xd061f2a in /usr/bin/clickhouse
> 2022.06.29 08:49:37.704053 [ 2650 ] {} <Fatal> BaseDaemon: 12. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0xedd0897 in /usr/bin/clickhouse
> 2022.06.29 08:49:37.704086 [ 2650 ] {} <Fatal> BaseDaemon: 13. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()&&...)::'lambda'()::operator()() @ 0xedd1fcc in /usr/bin/clickhouse
> 2022.06.29 08:49:37.704114 [ 2650 ] {} <Fatal> BaseDaemon: 14. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xedcef30 in /usr/bin/clickhouse
> 2022.06.29 08:49:37.704145 [ 2650 ] {} <Fatal> BaseDaemon: 15. void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) @ 0xedd11f3 in /usr/bin/clickhouse
> 2022.06.29 08:49:37.704170 [ 2650 ] {} <Fatal> BaseDaemon: 16. ? @ 0x7f1d20ed5b43 in ?
> 2022.06.29 08:49:37.704187 [ 2650 ] {} <Fatal> BaseDaemon: 17. clone @ 0x7f1d20f66bb4 in ?
> 2022.06.29 08:49:37.973859 [ 2650 ] {} <Fatal> BaseDaemon: Calculated checksum of the binary: 6CE4FA1038E23579ABF2B1CB9C8D1DE5. There is no information about the reference checksum.
