### ISSUE TITLE
Error populating Object('json') column with ALTER TABLE UPDATE

### ISSUE THREAD

**Issue by macobo** [ClickHouse/ClickHouse#38517]
**Does it reproduce on recent release?**

Tested on 22.6.1 revision 54455

**How to reproduce**

Repro:
```sql

SET allow_experimental_object_type = 1;

CREATE TABLE IF NOT EXISTS test_json (id Int64, data VARCHAR) ENGINE = MergeTree() ORDER BY id
INSERT INTO test_json(id, data) VALUES (1, '{"foo": 123}')

ALTER TABLE test_json ADD COLUMN data_json JSON DEFAULT data
ALTER TABLE test_json UPDATE data_json = data_json WHERE 1=1 SETTINGS mutations_sync=1
```

**Expected behavior**

Expected behavior: Column is correctly populated

**Error message and/or stacktrace**

Actual behavior: `Code: 341. DB::Exception: Received from localhost:9000. DB::Exception: Exception happened during execution of mutation 'mutation_2.txt' with part 'all_1_1_0' reason: 'Code: 16. DB::Exception: There is no physical column or subcolumn data_json in table: While executing MergeTreeInOrder. (NO_SUCH_COLUMN_IN_TABLE) (version 22.6.1.1985 (official build))'. This error maybe retryable or not. In case of unretryable error, mutation can be killed with KILL MUTATION query. (UNFINISHED)`

**Additional context**

Note using `default` this way is suggested in the documentation: https://clickhouse.com/docs/en/guides/developer/working-with-json/json-semi-structured/#adding-primary-keys

**Comment by CurtizJ** [comment]
Related #37730

**Comment by Astlol** [comment]
I have the same problem (migrations)
ALTER TABLE test_json ADD COLUMN data_json JSON; (with null default)
