### ISSUE TITLE
Best way to migrate old database  from V.20 to V.22.5

### ISSUE THREAD

**Issue by arikodelabs** [ClickHouse/ClickHouse#38527]
**Describe the issue**
Source tables from V.20.5  contain following fields s Nullable(String) but materialized view contains s AggregateFunction(argMax, String, DateTime), which require s` as not nullable after clickhouse-server version 22.4
Question is what is the best way to migrate to newer clickhouse versions

**How to reproduce**
* Which ClickHouse server versions are incompatible
V20.5.3.27 > V22.4.4.7
* Which interface to use, if matters
* Non-default settings, if any

**Error message and/or stacktrace**
[logleveldebug.log](https://github.com/ClickHouse/ClickHouse/files/9000576/logleveldebug.log)

**Additional context**

**Comment by arikodelabs** [comment]
Just tested with clickhouse-server v21 and v20.8, tables are blank

**Comment by alexey-milovidov** [comment]
The best way is to recreate and fill the materialized views from the source table.
