### ISSUE TITLE
Handle comments in queries properly when logging

### ISSUE THREAD

**Issue by abyss7** [ClickHouse/ClickHouse#3853]
For example, the following query:

    -- Should fail because second shard is unavailable
    SELECT count(*)
    -- don't do SELECT count(*)
    FROM test.distributed;

will appear in the logs as one-liner: `-- Should fail because second shard is unavailable SELECT count(*) -- don't SELECT count(*) FROM test.distributed`, in which case it's hard to understand what query was actually executed.

There are two proposed solutions: leave such queries multi-line (not good), or convert sql-comments to c-style comments (better, but hacky).

**Comment by alexey-milovidov** [comment]
Accidentially solved in https://github.com/yandex/ClickHouse/pull/5630

Now queries are logged after reformatting and all comments are lost:

```
milovidov-Pro-P30 :) SET send_logs_level = 'trace'

SET send_logs_level = 'trace'

Ok.

0 rows in set. Elapsed: 0.007 sec. 

milovidov-Pro-P30 :) SELECT /* test */ 1 -- hello

SELECT 1

[milovidov-Pro-P30] 2019.07.17 13:37:18.369449 {efb444af-a2fb-4c3e-8681-528135fb95d1} [ 44 ] <Debug> executeQuery: (from [::ffff:127.0.0.1]:34098) SELECT 1
↘ Progress: 0.00 rows, 0.00 B (0.00 rows/s., 0.00 B/s.) [milovidov-Pro-P30] 2019.07.17 13:37:18.372603 {efb444af-a2fb-4c3e-8681-528135fb95d1} [ 44 ] <Trace> InterpreterSelectQuery: FetchColumns -> Complete
[milovidov-Pro-P30] 2019.07.17 13:37:18.372964 {efb444af-a2fb-4c3e-8681-528135fb95d1} [ 44 ] <Debug> executeQuery: Query pipeline:
Expression
 Expression
  One

┌─1─┐
│ 1 │
└───┘
[milovidov-Pro-P30] 2019.07.17 13:37:18.374281 {efb444af-a2fb-4c3e-8681-528135fb95d1} [ 44 ] <Information> executeQuery: Read 1 rows, 1.00 B in 0.004 sec., 250 rows/sec., 250.07 B/sec.
[milovidov-Pro-P30] 2019.07.17 13:37:18.374444 {efb444af-a2fb-4c3e-8681-528135fb95d1} [ 44 ] <Debug> MemoryTracker: Peak memory usage (for query): 1.07 MiB.

1 rows in set. Elapsed: 0.019 sec.
```

**Comment by alexey-milovidov** [comment]
It's also written in query_log without comments that is an issue.

**Comment by alexey-milovidov** [comment]
But that's only for queries from clickhouse-client.

**Comment by alexey-milovidov** [comment]
The issue is still relevant and it can be solved pretty easily.
Just replace single-line comments with multi-line comments with the help of Lexer.
