### ISSUE TITLE
Insert csv file via clickhouse-client in new version not working

### ISSUE THREAD

**Issue by avraam-inside** [ClickHouse/ClickHouse#38543]
## Input data
1) csv-file with content: 
    
    | case_id |
    | -------- |
    | 1           |
  

2) Table in clickhouse:
    ```sql
    CREATE OR REPLACE TABLE BD.DELETE_ME
    (
        `col0` String COMMENT 'case_id'
    )
    ENGINE = MergeTree
    PARTITION BY tuple()
    ORDER BY tuple()
    SETTINGS index_granularity = 8192
    ```
    
3) Query to insert csv-file via clickhouse-client:
    ```bash
    cat <path_to_csv_file> | clickhouse-client -h localhost --database=DB --query="INSERT INTO DELETE_ME FORMAT CSVWithNames SETTINGS input_format_with_names_use_header=0"
    ```

## Problem description
    
Previously, the **code above worked** for the clickhouse client version 21.10.2.15

I had to upgrade to 22.5.1.2079.

Now this request is not working!

The error is this:
    
```
Code: 117. DB::Exception: Unknown field found in format header: 'SETTINGS input_format_with_names_use_header=0' at position 0
Set the 'input_format_skip_unknown_fields' parameter explicitly to ignore and proceed: While executing ParallelParsingBlockInputFormat: data for INSERT was parsed from query: (in query: INSERT INTO DELETE_ME FORMAT CSVWithNames SETTINGS input_format_with_names_use_header=0). (INCORRECT_DATA)
```

Is this a mistake, or maybe I didn't follow the trends and now the query needs to be written differently?

**Comment by Algunenano** [comment]
Since 22.4 SETTINGS must appear before FORMAT: #35883

**Comment by den-crane** [comment]
CH has changed the order of SETTINGS and FORMAT

```sql
cat x.csv | clickhouse-client --query="INSERT INTO DELETE_ME SETTINGS input_format_with_names_use_header=0 FORMAT CSVWithNames"

select * from DELETE_ME;
┌─col0─┐
│ 1    │
└──────┘
```

https://github.com/ClickHouse/ClickHouse/blob/master/CHANGELOG.md#-clickhouse-release-224-2022-04-19

Backward Incompatible Change

  *  Do not allow SETTINGS after FORMAT for INSERT queries (there is compatibility setting allow_settings_after_format_in_insert to accept such queries, but it is turned OFF by default). https://github.com/ClickHouse/ClickHouse/pull/35883 ([Azat Khuzhin](https://github.com/azat)).

**Comment by avraam-inside** [comment]
And will it not be possible to make a correct error output? I've spent hours trying to figure out what the problem is. I probably won't be the only one.

**Comment by avraam-inside** [comment]
It's not very difficult, is it, to check the request for order and tell about it? Once he SUDDENLY became important and changed.

There is another interesting point that I could not quickly/simply/clearly get information about the setup procedure/FORMAT somewhere in the clickhouse documentation, unfortunately.

**Comment by den-crane** [comment]
>And will it not be possible to make a correct error output? 

Yes, unfortunately because of lack of manpower it was not implemented.

>It's not very difficult, is it, to check the request for order and tell about it? Once he SUDDENLY became important and changed.
>There is another interesting point that I could not quickly/simply/clearly get information about the setup SETTINGS/FORMAT in query somewhere in the clickhouse documentation, unfortunately.

Yes, unfortunately because of lack of manpower it is not documented.

**Comment by avraam-inside** [comment]
I mean, should I mark the current request as at least a backlog?

Because of the fuss, I got a little unpleasant emotions, so I could be harsh in my statements.

In any case, thank you for the prompt response!

**Comment by den-crane** [comment]
I guess the behaviour has changed already

Now it silently does nothing

```sql
cat x.csv | clickhouse-client --query="INSERT INTO DELETE_ME FORMAT CSVWithNames SETTINGS input_format_with_names_use_header=0"

select * from DELETE_ME;
┌─col0─┐
│      │
└──────┘
```

**Comment by den-crane** [comment]
@azat

**Comment by avraam-inside** [comment]
> I guess the behaviour has changed already
> 
> Now it silently does nothing
> 
> ```sql
> cat x.csv | clickhouse-client --query="INSERT INTO DELETE_ME FORMAT CSVWithNames SETTINGS input_format_with_names_use_header=0"
> 
> select * from DELETE_ME;
> ┌─col0─┐
> │      │
> └──────┘
> ```

This is even worse than the incomprehensible error text))))
