### ISSUE TITLE
Type mismatch for column active_user_ue_rrc_connected_avg

### ISSUE THREAD

**Issue by arifSuwadji** [ClickHouse/ClickHouse#38552]
> Make sure to check documentation https://clickhouse.com/docs/en/ first. If the question is concise and probably has a short answer, asking it in Telegram chat https://telegram.me/clickhouse_en is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

> If you still prefer GitHub issues, remove all this text and ask your question here.

we was change column type, when we query we found error like this, anybody can help us?

![image](https://user-images.githubusercontent.com/32253996/176382561-614a4a1a-ea14-4570-b280-89688c10f428.png)

**Comment by genzgd** [comment]
This is an extremely old version of ClickHouse.  Please upgrade.

You might be able to fix the issue by changing the column type back, creating a new column of the new type, updating that column using a statement such as 'ALTER TABLE UPDATE COLUMN new_col = old_col (with a cast or conversion function as necessary), dropping the old col, and renaming the new column.
