### ISSUE TITLE
isNullable function

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#38611]
**Use case**

Is that column nullable or not 

**Describe the solution you'd like**

SELECT isNullable(NULL);

1 -- or true

**Describe alternatives you've considered**

```
WITH materialize(NULL) AS x
SELECT match(toColumnTypeName(x), 'Nullable') AS res

Query id: fa279bf2-38d5-41ae-89cb-187e588908db

┌─res─┐
│   1 │
└─────┘
```

**Additional context**

**Comment by lokax** [comment]
Is anyone doing this task? I'm new to the source code of Clickhouse. This task looks like a good start for me.

**Comment by UnamedRus** [comment]
> Is anyone doing this task?

No
