### ISSUE TITLE
BC check: Cannot quickly remove directory ... by removing files

### ISSUE THREAD

**Issue by tavplubix** [ClickHouse/ClickHouse#38629]
https://s3.amazonaws.com/clickhouse-test-reports/0/bd4a208428c8f17c4c3148886e6bf008bb064f58/stress_test__memory__actions_.html

```
2022.06.30 05:04:05.434426 [ 461303 ] {} <Error> test_35.tp_1 (1ff2034b-af50-401f-90fd-ac714bb9d202): Cannot quickly remove directory /var/lib/clickhouse/store/1ff/1ff2034b-af50-401f-90fd-ac714bb9d202/delete_tmp_all_0_0_0_2 by removing files; fallback to recursive removal. Reason: Code: 458. DB::ErrnoException: Cannot unlink file /var/lib/clickhouse/store/1ff/1ff2034b-af50-401f-90fd-ac714bb9d202/delete_tmp_all_0_0_0_2/pp.proj, errno: 21, strerror: Is a directory. (CANNOT_UNLINK) (version 22.7.1.1 (official build))
2022.06.30 05:04:05.434439 [ 461316 ] {} <Error> test_35.tp_2 (2c15d3ff-aa27-4370-b90d-fa14236c603b): Cannot quickly remove directory /var/lib/clickhouse/store/2c1/2c15d3ff-aa27-4370-b90d-fa14236c603b/delete_tmp_all_0_0_0_2 by removing files; fallback to recursive removal. Reason: Code: 458. DB::ErrnoException: Cannot unlink file /var/lib/clickhouse/store/2c1/2c15d3ff-aa27-4370-b90d-fa14236c603b/delete_tmp_all_0_0_0_2/pp.proj, errno: 21, strerror: Is a directory. (CANNOT_UNLINK) (version 22.7.1.1 (official build))
2022.06.30 05:04:05.436398 [ 461303 ] {} <Error> test_35.tp_1 (1ff2034b-af50-401f-90fd-ac714bb9d202): Cannot quickly remove directory /var/lib/clickhouse/store/1ff/1ff2034b-af50-401f-90fd-ac714bb9d202/delete_tmp_all_1_1_0_2 by removing files; fallback to recursive removal. Reason: Code: 458. DB::ErrnoException: Cannot unlink file /var/lib/clickhouse/store/1ff/1ff2034b-af50-401f-90fd-ac714bb9d202/delete_tmp_all_1_1_0_2/pp.proj, errno: 21, strerror: Is a directory. (CANNOT_UNLINK) (version 22.7.1.1 (official build))
2022.06.30 05:04:05.436486 [ 461316 ] {} <Error> test_35.tp_2 (2c15d3ff-aa27-4370-b90d-fa14236c603b): Cannot quickly remove directory /var/lib/clickhouse/store/2c1/2c15d3ff-aa27-4370-b90d-fa14236c603b/delete_tmp_all_1_1_0_2 by removing files; fallback to recursive removal. Reason: Code: 458. DB::ErrnoException: Cannot unlink file /var/lib/clickhouse/store/2c1/2c15d3ff-aa27-4370-b90d-fa14236c603b/delete_tmp_all_1_1_0_2/pp.proj, errno: 21, strerror: Is a directory. (CANNOT_UNLINK) (version 22.7.1.1 (official build))
```

Seems like the issue was introduced in #36555

**Comment by tavplubix** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/38680/a3d3e03b14b5db3c0b275da557e16f2c61715328/stress_test__undefined__actions_.html

**Comment by tavplubix** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/38749/8e9c1eaa73b78390d78a25b2867bcfc0d55412a7/stress_test__address__actions_.html

**Comment by tavplubix** [comment]
More failures: https://github.com/ClickHouse/ClickHouse/issues/38791

**Comment by tavplubix** [comment]
If fails too often (almost on every commit in master), let's temporarily disable `01710_projection_fetch_long`: #38798

**Comment by qoega** [comment]
>If fails too often (almost on every commit in master), let's temporarily disable 01710_projection_fetch_long: https://github.com/ClickHouse/ClickHouse/pull/38798

It did not help? Fail from today's master
https://s3.amazonaws.com/clickhouse-test-reports/38978/e898f65cc523b8b06b1e903ea113818419ca8b68/stress_test__undefined__actions_.html

**Comment by tavplubix** [comment]
That's really funny. There's `tp_1` table in error message and `01710_projection_fetch_long` is the only test that creates table with this name, so `no-backward-compatibility-check` tag was ignored for some reason and this test was run in BC check. Seems like after #38978 BC check took old version of the test that does not contain `no-backward-compatibility-check` tag yet... 
cc: @Avogar

**Comment by tavplubix** [comment]
Suppressed this failure another way

**Comment by Avogar** [comment]
> Seems like after https://github.com/ClickHouse/ClickHouse/pull/38978 BC check took old version of the test that does not contain no-backward-compatibility-check tag yet...

Yeah, that's not good, I didn't think about such problem. We can process these tags in a different way, we can find all tests with this tag from current repo (just grep files with this tag) and add them in skip list while running clickhouse-test. What do you think?

**Comment by tavplubix** [comment]
I think it's minor issue, because `no-backward-compatibility-check` should not be needed at all after #38978. Seems like the only case when we may need it is when something is broken in master and we want to temporarily suppress it, this should not happen often. I'm mostly fine with available ways to suppress a failure (the list of error to ignore, ability to disable test with all builds except release (and therefore in Stress Tests)). And sometimes we will need ad-hoc ways to suppress failures anyway (like in  https://github.com/ClickHouse/ClickHouse/pull/38965/commits/4d43e8aa152a96a122cb1fe02b6a3f006a812455).

**Comment by qoega** [comment]
>I think it's minor issue, because no-backward-compatibility-check should not be needed at all after https://github.com/ClickHouse/ClickHouse/pull/38978.

Is it a wrong link? This one is about integration tests. Not about stress.

**Comment by tavplubix** [comment]
> > I think it's minor issue, because no-backward-compatibility-check should not be needed at all after #38978.
> 
> Is it a wrong link? This one is about integration tests. Not about stress.

Yep, I meant #38717, sorry
