### ISSUE TITLE
execute query in clickhouse throw execption: CANNOT_READ_ALL_DATA

### ISSUE THREAD

**Issue by coolskys** [ClickHouse/ClickHouse#38620]
>cls-v-ck-test-a-dn-0-0-0.clickhouse-xx.cls-v-test.svc.cluster.local :) select  select  ip from mt_local where ip = 297445061774368769 limit 2;

SELECT ip
FROM mt_local
WHERE ip = 297445061774368769
LIMIT 2

Query id: 8e519d61-de92-4ba5-934b-a66d299d4dac

↘ Progress: 153.87 million rows, 1.23 GB (61.14 million rows/s., 489.15 MB/s.) ██████████▎                                                                                            (1.0 CPU, 31.65 MB RAM) 8%
0 rows in set. Elapsed: 2.542 sec. Processed 153.87 million rows, 1.23 GB (60.53 million rows/s., 484.27 MB/s.)

Received exception from server (version 22.5.1):
Code: 33. DB::Exception: Received from 127.0.0.1:9000. DB::Exception: Cannot read all data. Bytes read: 28248. Bytes expected: 38739.: (while reading column ip): (while reading from part /var/lib/clickhouse/disks/hdfs/store/e9f/e9f92c8c-c34c-4836-b3a0-2a113203e386/202206_10626_10770_3/ from mark 0 with max_rows_to_read = 63002): While executing MergeTreeInOrder. (CANNOT_READ_ALL_DATA)

SELECT version()

Query id: 7f3815f0-f134-4448-831d-be4c148fb36b

┌─version()───┐
│ 22.5.1.2079 │
└─────────────┘

> when i execute this query in clickhouse, it got this error,  i wonder why this happen, help.....

**Comment by coolskys** [comment]
0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xb4903fa in /usr/bin/clickhouse
1. DB::ReadBuffer::readStrict(char*, unsigned long) @ 0xb4ef834 in /usr/bin/clickhouse
2. DB::CompressedReadBufferBase::readCompressedData(unsigned long&, unsigned long&, bool) @ 0x15151ed3 in /usr/bin/clickhouse
3. DB::CompressedReadBufferFromFile::readBig(char*, unsigned long) @ 0x151543d7 in /usr/bin/clickhouse
4. DB::SerializationNumber<unsigned long>::deserializeBinaryBulk(DB::IColumn&, DB::ReadBuffer&, unsigned long, double) const @ 0xb2c8073 in /usr/bin/clickhouse
5. DB::ISerialization::deserializeBinaryBulkWithMultipleStreams(COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, DB::ISerialization::DeserializeBinaryBulkSettings&, std::__1::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, COW<DB::IColumn>::immutable_ptr<DB::IColumn> > > >*) const @ 0x1533d555 in /usr/bin/clickhouse
6. DB::MergeTreeReaderWide::readData(DB::NameAndTypePair const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, bool, unsigned long, unsigned long, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, COW<DB::IColumn>::immutable_ptr<DB::IColumn> > > >&, bool) @ 0x168203ef in /usr/bin/clickhouse
7. DB::MergeTreeReaderWide::readRows(unsigned long, unsigned long, bool, unsigned long, std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >&) @ 0x1681f36b in /usr/bin/clickhouse
8. DB::MergeTreeRangeReader::DelayedStream::finalize(std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >&) @ 0x16fe86ee in /usr/bin/clickhouse
9. DB::MergeTreeRangeReader::startReadingChain(unsigned long, std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange> >&) @ 0x16fedaa5 in /usr/bin/clickhouse
10. DB::MergeTreeRangeReader::read(unsigned long, std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange> >&) @ 0x16febffa in /usr/bin/clickhouse
11. DB::MergeTreeBaseSelectProcessor::readFromPartImpl() @ 0x16fe0980 in /usr/bin/clickhouse
12. DB::MergeTreeBaseSelectProcessor::readFromPart() @ 0x16fe178d in /usr/bin/clickhouse
13. DB::MergeTreeBaseSelectProcessor::generate() @ 0x16fdfb60 in /usr/bin/clickhouse
14. DB::ISource::tryGenerate() @ 0x16cfc835 in /usr/bin/clickhouse
15. DB::ISource::work() @ 0x16cfc4da in /usr/bin/clickhouse
16. DB::SourceWithProgress::work() @ 0x16f43602 in /usr/bin/clickhouse
17. DB::ExecutionThreadContext::executeTask() @ 0x16d18ee8 in /usr/bin/clickhouse
18. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x16d0cbfe in /usr/bin/clickhouse
19. DB::PipelineExecutor::executeImpl(unsigned long) @ 0x16d0bb01 in /usr/bin/clickhouse
20. DB::PipelineExecutor::execute(unsigned long) @ 0x16d0b798 in /usr/bin/clickhouse
21. ? @ 0x16d1cdad in /usr/bin/clickhouse
22. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xb53fc47 in /usr/bin/clickhouse
23. ? @ 0xb54367d in /usr/bin/clickhouse
24. start_thread @ 0x814a in /usr/lib64/libpthread-2.28.so
25. __clone @ 0xfcdc3 in /usr/lib64/libc-2.28.so

This is detail the stack trace.

**Comment by genzgd** [comment]
This could be a problem with your network connection assuming you are reading from HDFS.   Otherwise it could represent corrupted file in your data storage.   If that is the case there is not much ClickHouse can do with an unreadable file that has not been successfully replicated or backed up.

**Comment by coolskys** [comment]
Thanks
