### ISSUE TITLE
S3 function in tutorial doesn't work

### ISSUE THREAD

**Issue by geronimogoemon** [ClickHouse/ClickHouse#38649]
**Describe the issue**
I am trying to follow the starting tutorial but unfortunately got blocked on the second step 
https://clickhouse.com/docs/en/tutorial#2-insert-the-dataset. 
When trying to run the command in web UI
```
INSERT INTO trips
    SELECT * FROM s3(
        'https://datasets-documentation.s3.eu-west-3.amazonaws.com/nyc-taxi/trips_{1..2}.gz',
        'TabSeparatedWithNames'
    )
```

I get the error 
```
Code: 42. DB::Exception: The signature of table function s3 could be the following:
 - url, format, structure
 - url, format, structure, compression_method
 - url, access_key_id, secret_access_key, format, structure
 - url, access_key_id, secret_access_key, format, structure, compression_method. (NUMBER_OF_ARGUMENTS_DOESNT_MATCH) (version 21.9.4.35 (official build))
```
Looking up the documentation of function `s3` it seems I have to pass the column names? It seems the API has changed since the tutorial got written and the tutorial is outdated?

**Comment by den-crane** [comment]
Documentation reflects the latest version of Clickhouse (22.6 / 22.7)

What is your version of Clickhouse ?

**Comment by geronimogoemon** [comment]
Hmm running 
```
select version()
```

gives me
```
21.9.4.35
```

Though I have followed steps from https://clickhouse.com/docs/en/quick-start#1-start-clickhouse

My OS is Ubuntu 22.04 LTS

**Comment by den-crane** [comment]
```
INSERT INTO trips
                  SELECT * FROM s3(
                      'https://datasets-documentation.s3.eu-west-3.amazonaws.com/nyc-taxi/trips_{1..2}.gz',
                      'TabSeparatedWithNames'
                  )
              ;
```
it works in 22.6.

21.9 is out of support

**Comment by geronimogoemon** [comment]
If someone has a similar problem the reason turned out to be that I still had a docker container running from one of the tutorials in https://clickhouse.com/learn/ and  that was running on `21.9.4.35`
