### ISSUE TITLE
MySQL Engine not functioning as expected with ClickHouse MacOS precompiled binary

### ISSUE THREAD

**Issue by thomoco** [ClickHouse/ClickHouse#38650]
> You have to provide the following information whenever possible.

**Describe what's wrong**
When using the ClickHouse precompiled binary on MacOS, the MySQL Engine is not functioning. Currently testing on Macbook Pro M1 (Apple Silicon), although using the x86_64 build due to this tangential issue: https://github.com/ClickHouse/ClickHouse/issues/38648

> A clear and concise description of what works not as it is supposed to.
Using the latest version:
```
$ curl -O 'https://builds.clickhouse.com/master/macos/clickhouse' && chmod a+x ./clickhouse
$ ./clickhouse server
2022.06.30 11:29:22.956608 [ 4737072 ] {} <Information> : Starting ClickHouse 22.7.1.1016 with revision 54464, no build id, PID 14745
...
2022.06.30 11:29:23.309347 [ 4737072 ] {} <Information> Application: Listening for http://[::1]:8123
2022.06.30 11:29:23.309435 [ 4737072 ] {} <Information> Application: Listening for native protocol (tcp): [::1]:9000
2022.06.30 11:29:23.309518 [ 4737072 ] {} <Information> Application: Listening for MySQL compatibility protocol: [::1]:9004
2022.06.30 11:29:23.309602 [ 4737072 ] {} <Information> Application: Listening for http://127.0.0.1:8123
2022.06.30 11:29:23.309771 [ 4737072 ] {} <Information> Application: Listening for native protocol (tcp): 127.0.0.1:9000
2022.06.30 11:29:23.309860 [ 4737072 ] {} <Information> Application: Listening for MySQL compatibility protocol: 127.0.0.1:9004
2022.06.30 11:29:23.309868 [ 4737072 ] {} <Information> Application: Ready for connections.
```

The binary seems to be compiled with USE_MYSQL support:
```
$ ./clickhouse client
`localhost.localdomain :) select * from system.build_options where name like 'USE_MYSQL';

SELECT *
FROM system.build_options
WHERE name LIKE 'USE_MYSQL'

Query id: 53edbcd8-abc6-4ca6-99ae-7853fb4f6a8c

┌─name──────┬─value─┐
│ USE_MYSQL │       │
└───────────┴───────┘

1 row in set. Elapsed: 0.040 sec.`
```

However, when attempting to use the MySQL Engine, am getting this error:
```
`localhost.localdomain :) CREATE TABLE IF NOT EXISTS mysql_test1
(
    `id` UInt64,
    `column1` String
)
ENGINE = MySQL('localhost:3306', 'db1', 'mysql_test1', 'root', 'password')

Query id: ce5a765b-b717-4adf-9a5d-8c14104b00e1

0 rows in set. Elapsed: 0.012 sec.

Received exception from server (version 22.7.1):
Code: 56. DB::Exception: Received from localhost:9000. DB::Exception: Unknown table engine MySQL. (UNKNOWN_STORAGE)`
```

**Does it reproduce on recent release?**
Yes, currently testing with latest precompiled binary for MacOS - currently using the x86_64 download as discussed in this tangential issue: https://github.com/ClickHouse/ClickHouse/issues/38648

**Enable crash reporting**
did not do so currently, can do so if needed

> If possible, change "enabled" to true in "send_crash_reports" section in `config.xml`:
did not do so currently, can do so if needed

**How to reproduce**
see above

**Expected behavior**
Expected MYSQL Engine to function normally since this related issue was closed: https://github.com/ClickHouse/ClickHouse/issues/28405

> A clear and concise description of what you expected to happen.

**Error message and/or stacktrace**

> If applicable, add screenshots to help explain your problem.

**Additional context**

> Add any other context about the problem here.

**Comment by tavplubix** [comment]
MySQL-related features are not supported on MacOS

> The binary seems to be compiled with USE_MYSQL support:

It's not, `value` must be 1:
```
dell9510 :) select * from system.build_options where name like 'USE_MYSQL';

SELECT *
FROM system.build_options
WHERE name LIKE 'USE_MYSQL'

Query id: f7b2ee81-92cf-4c9b-a13f-e0a6f5a0f2a1

┌─name──────┬─value─┐
│ USE_MYSQL │ 1     │
└───────────┴───────┘

1 row in set. Elapsed: 0.024 sec.
```

**Comment by tavplubix** [comment]
Related: #21191, #37167, #3927
