### ISSUE TITLE
Support All setting for insert_quorum

### ISSUE THREAD

**Issue by gingerwizard** [ClickHouse/ClickHouse#38700]
Currently, this setting requires the user to know the number of replicas in their system. In some serverless cloud offerings, this might not be known to the user - rendering this feature difficult to use.

The proposal is an `All` setting that would require a majority of nodes to ack the insert i.e. `(number_of_replicas + 1) / 2`. In the event insufficient nodes were available, inserts would be rejected.

This setting should be compatible with [select_sequential_consistency](https://clickhouse.com/docs/en/operations/settings/settings/#settings-select_sequential_consistency) which would only use replicas known to be consistent. This introduces questions as to what happens if different inserts achieve a quorum on different replicas...

**Comment by alexey-milovidov** [comment]
Maybe `majority`, not `all`?
