### ISSUE TITLE
<Error> DB::IBackgroundJobExecutor::execute(DB::JobAndPool)::<lambda()>: std::exception. Code: 1001, type: std::__1::__fs::filesystem::filesystem_error, e.what() = filesystem error: in file_size: No such file or directory

### ISSUE THREAD

**Issue by beijishiqidu** [ClickHouse/ClickHouse#38727]
Hello, my friends, I now encounter a problem, hope can get everyone's help;

The clickhouse version we are using is **21.8.8.29**;

Recently, we found that an error was reported when we queried a table, indicating that the TIMEVALUE.mrk2 file cannot be found. I know that the TIMEVALUE is a field in the table.

**And I found the TIMEVALUE field in the columns.txt file in the all_37_64_2 directory.**

But, The error log is as follows:

./clickhouse-server.err.log.1:2022.06.20 14:30:17.654103 [ 14727 ] {} <Warning> TEST.PHNR_NRCELL_191_LOC: Removing temporary directory /opt/clickhouse/data/data/TEST/PHNR_NRCELL_191_LOC/tmp_merge_all_37_64_2/

./clickhouse-server.err.log.1:2022.06.20 14:33:21.562299 [ 12810 ] {} <Error> DB::IBackgroundJobExecutor::execute(DB::JobAndPool)::<lambda()>: std::exception. Code: 1001, type: std::__1::__fs::filesystem::filesystem_error, e.what() = filesystem error: in file_size: No such file or directory [/opt/clickhouse/data/data/TEST/PHNR_NRCELL_191_LOC/all_37_64_2/TIMEVALUE.mrk2], Stack trace (when copying this message, always include the lines below):

My table creation SQL statement:
CREATE TABLE IF NOT EXISTS TEST.PHNR_NRCELL_191 (
TIMEVALUE  Int64 ,
OPTID  Nullable(Int64) ,
PERIOD  Nullable(Int64) ,
BUSYHOURID  Nullable(Int64) ,
GNODEBID  Int64 ,
CELLKEY  Int64 ,
INTEGRITYCNT  Nullable(Float64) ,
M1911831582  Nullable(Int64) ,
M1911831583  Nullable(Int64))  ENGINE = Distributed(TESTCluster,TEST,PHNR_NRCELL_191_LOC,rand())

CREATE TABLE IF NOT EXISTS TEST.PHNR_NRCELL_191_LOC (
TIMEVALUE  Int64 ,
OPTID  Nullable(Int64) ,
PERIOD  Nullable(Int64) ,
BUSYHOURID  Nullable(Int64) ,
GNODEBID  Int64 ,
CELLKEY  Int64 ,
INTEGRITYCNT  Nullable(Float64) ,
M1911831582  Nullable(Int64) ,
M1911831583  Nullable(Int64)   )  ENGINE MergeTree() PARTITION BY floor(TIMEVALUE) ORDER BY (TIMEVALUE,CELLKEY,GNODEBID) SETTINGS index_granularity=8192;

**Comment by alexey-milovidov** [comment]
Update ClickHouse to the latest version.

If the error is shown in the background, not interfering with the queries, you can ignore it before the upgrading.
