### ISSUE TITLE
High concurrency queries lead to a surge in threads of single shard and multiple replicas, and read-write queues

### ISSUE THREAD

**Issue by shadowDy** [ClickHouse/ClickHouse#38724]
ch-server vresion:ClickHouse server version 21.9.5 revision 54449

deploy：Real time read-write cluster, multi shards and  3 replica

When I launch a highly concurrent count () query，The number of multiple replica threads and connections of a shard (random) starts to increase abruptly；

By sampling a query ID for analysis, it is found that the increase in the number of connections is caused by multiple replica retries. The reason for retry is that the other two copies did not return results。

query_log exception:

` Code: 210. DB::NetException: I/O error: Broken pipe, while writing to socket (10.150.142.34:57725). (NETWORK_ERROR) (version 21.9.5.16 (official build))`

Viewing the log of the failed replica, it is found that the ch service starts to execute after an interval of 3min+ after receiving the query.

replica 1
`
2022.07.01 17:50:37.362236 [ 18248 ] {0105ff42-13ab-4187-8300-230bc0060464} <Debug> executeQuery: (from xxx, initial_query_id: 16EC3E430A019060) SELECT count() AS countNum FROM xx_local WHERE xxxx
2022.07.01 17:54:22.043408 [ 18248 ] {0105ff42-13ab-4187-8300-230bc0060464} <Debug> InterpreterSelectQuery: MergeTreeWhereOptimizer: condition "(x) AND (x) AND (x) AND (x)" moved to PREWHERE
2022.07.01 17:54:23.047892 [ 18248 ] {0105ff42-13ab-4187-8300-230bc0060464} <Debug> xxx (412683c0-9e75-4604-8126-83c09e751604) (SelectExecutor): Key condition: (column 2 in ['xx', 'xx']), (column 1 in ['xx', 'xx']), and, unknown, and, (column 3 in ['xx', 'cc']), and, (column 0 in ['dd', 'cc']), (column 5 in ['xxx', 'xxxx']), and, (column 6 in [xx, xx]), and, (column 4 in [xx, +Inf)), and, (column 4 in (-Inf, xxx]), and, and, (column 2 in ['xxx', 'xxx']), (column 1 in ['xxx', 'xxx']), and, unknown, and, (column 3 in ['xxx', 'xxx']), and, and
2022.07.01 17:54:24.040810 [ 18248 ] {0105ff42-13ab-4187-8300-230bc0060464} <Debug> xxxx (412683c0-9e75-4604-8126-83c09e751604) (SelectExecutor): MinMax index condition: unknown, unknown, and, unknown, and, unknown, and, unknown, unknown, and, unknown, and, (column 0 in [1656669000, +Inf)), and, (column 0 in (-Inf, 1656669029]), and, and, unknown, unknown, and, unknown, and, unknown, and, and
2022.07.01 17:54:24.040953 [ 18248 ] {0105ff42-13ab-4187-8300-230bc0060464} <Debug> xxxx (412683c0-9e75-4604-8126-83c09e751604) (SelectExecutor): Selected 0/28 parts by partition key, 0 parts by primary key, 0/0 marks by primary key, 0 marks to read from 0 ranges
2022.07.01 17:54:24.041691 [ 17118 ] {0105ff42-13ab-4187-8300-230bc0060464} <Debug> AggregatingTransform: Aggregated. 0 to 1 rows (from 0.00 B) in 0.000422909 sec. (0.000 rows/sec., 0.00 B/sec.)
2022.07.01 17:54:24.042372 [ 18248 ] {0105ff42-13ab-4187-8300-230bc0060464} <Error> executeQuery: Code: 210. DB::NetException: I/O error: Broken pipe, while writing to socket (xxxx). (NETWORK_ERROR) (version 21.9.5.16 (official build)) (from xxxx) (in query: xxxxx), Stack trace (when copying this message, always include the lines below):
2022.07.01 17:54:26.040756 [ 18248 ] {0105ff42-13ab-4187-8300-230bc0060464} <Error> TCPHandler: Code: 210. DB::Exception: I/O error: Broken pipe, while writing to socket (xxxx). (NETWORK_ERROR), Stack trace (when copying this message, always include the lines below):
2022.07.01 17:54:26.041034 [ 18248 ] {0105ff42-13ab-4187-8300-230bc0060464} <Warning> TCPHandler: Client has gone away.
2022.07.01 17:54:26.041416 [ 18248 ] {0105ff42-13ab-4187-8300-230bc0060464} <Debug> MemoryTracker: Peak memory usage (for query): 0.00 B
`

replica 2:
`
2022.07.01 17:50:33.361419 [ 42430 ] {b77f25c6-602c-4d96-a902-159ddb2da716} <Debug> executeQuery: (from 10.150.142.34:57725, initial_query_id: 16EC3E430A019060) SELECT count() AS countNum FROM xxx
2022.07.01 17:53:21.938410 [ 42430 ] {b77f25c6-602c-4d96-a902-159ddb2da716} <Debug> InterpreterSelectQuery: MergeTreeWhereOptimizer: condition "( 'xxx') AND ( 'xxx') AND ( 'xxxx') AND (= 'xxxx')" moved to PREWHERE
2022.07.01 17:53:23.930190 [ 42430 ] {b77f25c6-602c-4d96-a902-159ddb2da716} <Debug>   xxxx (1efe2fba-df67-4abd-9efe-2fbadf676abd) (SelectExecutor): Key condition: (column 2 in ['xx', 'xx']), (column 1 in ['xx', 'xx']), and, unknown, and, (column 3 in ['xx', 'cc']), and, (column 0 in ['dd', 'cc']), (column 5 in ['xxx', 'xxxx']), and, (column 6 in [xx, xx]), and, (column 4 in [xx, +Inf)), and, (column 4 in (-Inf, xxx]), and, and, (column 2 in ['xxx', 'xxx']), (column 1 in ['xxx', 'xxx']), and, unknown, and, (column 3 in ['xxx', 'xxx']), and, and
2022.07.01 17:53:24.929112 [ 42430 ] {b77f25c6-602c-4d96-a902-159ddb2da716} <Debug> xxxx(1efe2fba-df67-4abd-9efe-2fbadf676abd) (SelectExecutor): MinMax index condition: unknown, unknown, and, unknown, and, unknown, and, unknown, unknown, and, unknown, and, (column 0 in [1656669000, +Inf)), and, (column 0 in (-Inf, 1656669029]), and, and, unknown, unknown, and, unknown, and, unknown, and, and
2022.07.01 17:53:26.928331 [ 42430 ] {b77f25c6-602c-4d96-a902-159ddb2da716} <Debug> xxxl (1efe2fba-df67-4abd-9efe-2fbadf676abd) (SelectExecutor): Selected 0/26 parts by partition key, 0 parts by primary key, 0/0 marks by primary key, 0 marks to read from 0 ranges
2022.07.01 17:53:26.929185 [ 11047 ] {b77f25c6-602c-4d96-a902-159ddb2da716} <Debug> AggregatingTransform: Aggregated. 0 to 1 rows (from 0.00 B) in 0.000539473 sec. (0.000 rows/sec., 0.00 B/sec.)
2022.07.01 17:53:27.029087 [ 42430 ] {b77f25c6-602c-4d96-a902-159ddb2da716} <Information> TCPHandler: Query was cancelled.
2022.07.01 17:53:27.930676 [ 42430 ] {b77f25c6-602c-4d96-a902-159ddb2da716} <Error> executeQuery: Code: 210. DB::NetException: I/O error: Broken pipe, while writing to socket (xxx). (NETWORK_ERROR) (version 21.9.5.16 (official build)) (from xxxx) (in query: xxx), Stack trace (when copying this message, always include the lines below):
2022.07.01 17:53:29.930535 [ 42430 ] {b77f25c6-602c-4d96-a902-159ddb2da716} <Error> TCPHandler: Code: 210. DB::Exception: I/O error: Broken pipe, while writing to socket (xxxx5). (NETWORK_ERROR), Stack trace (when copying this message, always include the lines below):
2022.07.01 17:53:29.933796 [ 42430 ] {b77f25c6-602c-4d96-a902-159ddb2da716} <Warning> TCPHandler: Client has gone away.
2022.07.01 17:53:31.930876 [ 42430 ] {b77f25c6-602c-4d96-a902-159ddb2da716} <Debug> MemoryTracker: Peak memory usage (for query): 0.00 B.
`

You can see the logs of both replica. After receiving the query request, the execution starts after an interval of 3 minutes; 

Why does this problem occur and how to solve  it ? thanks

**Comment by melvynator** [comment]
Can you try to upgrade to a more recent version: https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md ?

**Comment by mirajgodha** [comment]
Please check if system clocks are in sync in all the machines.
You can use NTP service to sync time

**Comment by SaltTan** [comment]
There could be more information on the 'trace' log level.
Maybe the initiator sent some data to the shards along with the query.
