### ISSUE TITLE
S3 table engine clickhouse dynamic data insertion

### ISSUE THREAD

**Issue by sanjaybobble** [ClickHouse/ClickHouse#38746]
I have successfully loaded a parquet file from AWS s3 into click house. But how to load data the data dynamically.

Please find below the steps to understanding 

`CREATE TABLE s3_direct_table
(
	app_name FixedString(100),
	package_name FixedString(100)
)ENGINE=S3('https://bucket.ap-south-1.amazonaws.com/event_date=2022-04-12/*.parquet','','','Parquet');`

* The above script will pull data from 12th April 2022 into click house but I would like the data to be loaded automatically for further data.
* In the Redshift, we can perform by Stored procedure but in click house how can we do that.

**Comment by UnamedRus** [comment]
Related https://github.com/ClickHouse/ClickHouse/issues/37012

**Comment by sanjaybobble** [comment]
Hi UnamedRus,

On top of that, I used the insert statement.
`INSERT INTO test.tb_customer_raw (event_date, app_name, package_name)
SELECT EXTRACT(_path, '\s*event_date=\s*([\S\s]+)/') AS event_date, * FROM test.tb_customer_raw_s3
WHERE _path LIKE 'bobble-data-intelligence/market-intelligence-datalake-sanjay-testing/pranay_date_test/event_date=2022-01-02/%.parquet'
`

**Comment by alexey-milovidov** [comment]
If you want to process the data on the fly, add another wildcard:

```
CREATE TABLE s3_direct_table ( app_name FixedString(100), package_name FixedString(100) )ENGINE=S3('https://bucket.ap-south-1.amazonaws.com/event_date=*/*.parquet','','','Parquet');
```

If you are interested in inserting all the new data into another table - this is not implemented, see my feature request here: https://github.com/ClickHouse/ClickHouse/issues/37012
