### ISSUE TITLE
CPU metric in clickhouse-client is wrong

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#38756]
CPU usage is misreported.

Currently "0 CPU" means "no CPU metric received in the previous ProfileEvents packet". But there can be many ProfileEvents packets and only a few with CPU increment.

That's why the CPU metric shows something weird like:
```
0
0
0
0
0
1234
0
0
0
...
```

This is unbearable, and the CPU metric should be either fixed or removed altogether.

**Comment by alexey-milovidov** [comment]
@novikd please be aware of how wrong it is.

**Comment by serxa** [comment]
Is there some simple query to reproduce?

**Comment by alexey-milovidov** [comment]
Run this query in clickhouse-local:
```
SELECT count() FROM system.numbers WHERE NOT ignore(base58Encode(randomString(100)))
```

**Comment by serxa** [comment]
> Run this query in clickhouse-local:
> 
> ```
> SELECT count() FROM system.numbers WHERE NOT ignore(base58Encode(randomString(100)))
> ```

This query reports it's CPU consumption only every ~1.3 s, and now with default 3.0 s period averaging I got a "saw" falling down from 1.2 CPU to 0.8 CPU exponentially and then jumping up back to 1.2 CPU. My estimate was that with 100ms updates we will also get this "saw", but with ~3% ( = 0.1s / 3s) difference between low and high values. This is actually third significant digit and is not displayed by client normally. And this is the case, for example, for the same query but with `base64Encode` function instead. After first 500ms it shows 1.0 CPU stable.

I think we should leave this averaging implementation in client as it is now (after merge) and start investigating why CPU is reported only every ~1.3 s

**Comment by alexey-milovidov** [comment]
The task is to convert a set of points into a continuous curve.

Previously resampling to a fixed grid (100ms) was used.
Now exponential smoothing is used.
Another option would be - approximate with a piecewise constant function.
