### ISSUE TITLE
Data processing is not parallelized if the source returns one stream of data.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#38755]
**Use case**

```
SELECT sum(length(base58Encode(toString(number)))) FROM system.numbers
```

or

```
SELECT sum(length(base58Encode(URL))) FROM file('hits.parquet')
```

**Describe the solution you'd like**

Simply add ResizeProcessor.

**Comment by filimonov** [comment]
It seems the similar issue exists with:

```
INSERT INTO table SELECT * FROM cluster(...)
SETTINGS max_insert_threads = 8
```
the number of insert threads is limited by the number of streams returned by the `cluster` function (=number of shards in the cluster). So max_insert_threads is not working as expected.

**Comment by devcrafter** [comment]
> It seems the similar issue exists with:
> 
> ```
> INSERT INTO table SELECT * FROM cluster(...)
> SETTINGS max_insert_threads = 8
> ```
> 
> the number of insert threads is limited by the number of streams returned by the `cluster` function (=number of shards in the cluster). So max_insert_threads is not working as expected.

Please create an issue if there is no such. It's another issue.
