### ISSUE TITLE
 undefined reference to `operator delete(void*)'

### ISSUE THREAD

**Issue by josehu-t** [ClickHouse/ClickHouse#38785]
> Make sure that `git diff` result is empty and you've just pulled fresh master. Try cleaning up cmake cache. Just in case, official build instructions are published here: https://clickhouse.com/docs/en/development/build/

**Operating system**
CentOS Linux release 7.9
> OS kind or distribution, specific version/release, non-standard kernel if any. If you are trying to build inside virtual machine, please mention it too.

**Cmake version**
cmake3 version 3.17.5
**Ninja version**
1.10.2
**Compiler name and version**
clang version 15.0.0
echo $CC   
/data/dev/llvm/bin/clang
echo $CXX
/data/dev/llvm/bin/clang++
 gcc --version
gcc (GCC) 10.2.1 20210130 (Red Hat 10.2.1-11)
**Full cmake and/or ninja output**
JSON.cpp:(.text._ZN4llvm12DenseMapBaseINS_8DenseMapINS_4json9ObjectKeyENS2_5ValueENS_12DenseMapInfoINS_9StringRefEEENS_6detail12DenseMapPairIS3_S4_EEEES3_S4_S7_SA_E11try_emplaceIJDnEEESt4pairINS_16DenseMapIteratorIS3_S4_S7_SA_Lb0EEEbEOS3_DpOT_[_ZN4llvm12DenseMapBaseINS_8DenseMapINS_4json9ObjectKeyENS2_5ValueENS_12DenseMapInfoINS_9StringRefEEENS_6detail12DenseMapPairIS3_S4_EEEES3_S4_S7_SA_E11try_emplaceIJDnEEESt4pairINS_16DenseMapIteratorIS3_S4_S7_SA_Lb0EEEbEOS3_DpOT_]+0x69): undefined reference to `std::string::_Rep::_S_empty_rep_storage'
/opt/rh/devtoolset-11/root/usr/lib/gcc/x86_64-redhat-linux/11/../../../../bin/ld: JSON.cpp:(.text._ZN4llvm12DenseMapBaseINS_8DenseMapINS_4json9ObjectKeyENS2_5ValueENS_12DenseMapInfoINS_9StringRefEEENS_6detail12DenseMapPairIS3_S4_EEEES3_S4_S7_SA_E11try_emplaceIJDnEEESt4pairINS_16DenseMapIteratorIS3_S4_S7_SA_Lb0EEEbEOS3_DpOT_[_ZN4llvm12DenseMapBaseINS_8DenseMapINS_4json9ObjectKeyENS2_5ValueENS_12DenseMapInfoINS_9StringRefEEENS_6detail12DenseMapPairIS3_S4_EEEES3_S4_S7_SA_E11try_emplaceIJDnEEESt4pairINS_16DenseMapIteratorIS3_S4_S7_SA_Lb0EEEbEOS3_DpOT_]+0x73): undefined reference to `operator delete(void*)'
/opt/rh/devtoolset-11/root/usr/lib/gcc/x86_64-redhat-linux/11/../../../../bin/ld: JSON.cpp:(.text._ZN4llvm12DenseMapBaseINS_8DenseMapINS_4json9ObjectKeyENS2_5ValueENS_12DenseMapInfoINS_9StringRefEEENS_6detail12DenseMapPairIS3_S4_EEEES3_S4_S7_SA_E11try_emplaceIJDnEEESt4pairINS_16DenseMapIteratorIS3_S4_S7_SA_Lb0EEEbEOS3_DpOT_[_ZN4llvm12DenseMapBaseINS_8DenseMapINS_4json9ObjectKeyENS2_5ValueENS_12DenseMapInfoINS_9StringRefEEENS_6detail12DenseMapPairIS3_S4_EEEES3_S4_S7_SA_E11try_emplaceIJDnEEESt4pairINS_16DenseMapIteratorIS3_S4_S7_SA_Lb0EEEbEOS3_DpOT_]+0xd5): undefined reference to `std::string::_Rep::_M_destroy(std::allocator<char> const&)'
/opt/rh/devtoolset-11/root/usr/lib/gcc/x86_64-redhat-linux/11/../../../../bin/ld: lib/libLLVMSupport.a(JSON.cpp.o): in function `llvm::DenseMap<llvm::json::ObjectKey, llvm::json::Value, llvm::DenseMapInfo<llvm::StringRef>, llvm::detail::DenseMapPair<llvm::json::ObjectKey, llvm::json::Value> >::copyFrom(llvm::DenseMap<llvm::json::ObjectKey, llvm::json::Value, llvm::DenseMapInfo<llvm::StringRef>, llvm::detail::DenseMapPair<llvm::json::ObjectKey, llvm::json::Value> > const&)':
JSON.cpp:(.text._ZN4llvm8DenseMapINS_4json9ObjectKeyENS1_5ValueENS_12DenseMapInfoINS_9StringRefEEENS_6detail12DenseMapPairIS2_S3_EEE8copyFromERKSA_[_ZN4llvm8DenseMapINS_4json9ObjectKeyENS1_5ValueENS_12DenseMapInfoINS_9StringRefEEENS_6detail12DenseMapPairIS2_S3_EEE8copyFromERKSA_]+0x2b): undefined reference to `std::string::_Rep::_S_empty_rep_storage'
/opt/rh/devtoolset-11/root/usr/lib/gcc/x86_64-redhat-linux/11/../../../../bin/ld: JSON.cpp:(.text._ZN4llvm8DenseMapINS_4json9ObjectKeyENS1_5ValueENS_12DenseMapInfoINS_9StringRefEEENS_6detail12DenseMapPairIS2_S3_EEE8copyFromERKSA_[_ZN4llvm8DenseMapINS_4json9ObjectKeyENS1_5ValueENS_12DenseMapInfoINS_9StringRefEEENS_6detail12DenseMapPairIS2_S3_EEE8copyFromERKSA_]+0x44): undefined reference to `operator delete(void*)'
/opt/rh/devtoolset-11/root/usr/lib/gcc/x86_64-redhat-linux/11/../../../../bin/ld: JSON.cpp:(.text._ZN4llvm8DenseMapINS_4json9ObjectKeyENS1_5ValueENS_12DenseMapInfoINS_9StringRefEEENS_6detail12DenseMapPairIS2_S3_EEE8copyFromERKSA_[_ZN4llvm8DenseMapINS_4json9ObjectKeyENS1_5ValueENS_12DenseMapInfoINS_9StringRefEEENS_6detail12DenseMapPairIS2_S3_EEE8copyFromERKSA_]+0xa6): undefined reference to `std::string::_Rep::_M_destroy(std::allocator<char> const&)'
/opt/rh/devtoolset-11/root/usr/lib/gcc/x86_64-redhat-linux/11/../../../../bin/ld: lib/libLLVMSupport.a(JSON.cpp.o): in function `void llvm::function_ref<void ()>::callback_fn<llvm::json::OStream::value(llvm::json::Value const&)::$_2>(long)':
JSON.cpp:(.text._ZN4llvm12function_refIFvvEE11callback_fnIZNS_4json7OStream5valueERKNS4_5ValueEE3$_2EEvl+0x86): undefined reference to `operator delete(void*)'
clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
[78/4459] Building CXX object contrib/azure-cmake/CMakeFiles/_azure_sdk.dir/__/azure/sdk/identity/azure-identity/src/environment_credential.cpp.o
FAILED: contrib/llvm/llvm/NATIVE/Release/bin/llvm-tblgen 
cd /data/dev/ClickHouse/Debug/contrib/llvm/llvm/NATIVE && /usr/bin/cmake3 --build /data/dev/ClickHouse/Debug/contrib/llvm/llvm/NATIVE --target llvm-tblgen --config Release
[88/4459] Building CXX object contrib/azure-cmake/CMakeFiles/_azure_sdk.dir/__/azure/sdk/identity/azure-identity/src/environment_credential.cpp.o
ninja: build stopped: subcommand failed.

**Comment by josehu-t** [comment]
the master branch can not be compiled properly, is there someone for help, thanks a lot.

**Comment by alexey-milovidov** [comment]
You are compiling not per manual.
Take the build log: https://s3.amazonaws.com/clickhouse-builds/22.7/2e2ef087129ed072404bdc084e8028a5c5869dc0/binary_release/build_log.log and reproduce it verbatim.
