### ISSUE TITLE
[MySQL Interface] ClickHouse should use Binary characterset for String/FixedString columns instead of UTF8

### ISSUE THREAD

**Issue by MaceWindu** [ClickHouse/ClickHouse#38790]
Currently ClickHouse specify UTF8 character set for String/FixedString data in mysql interface, which doesn't allow clients to handle non-utf8 (binary non string data) properly as they instructed to parse it to string using utf8 encoding.

This leads to corrupted data, when column used to store binary data - not all byte sequences could be parsed to string and then back (not even talking about efficiency of such coversion).

E.g. 0xFF value as invalid UTF8 sequence will be parsed into substitution character, which use 3 bytes.

**Comment by slvrtrn** [comment]
@MaceWindu, this is about this part, right?
https://github.com/slvrtrn/ClickHouse/blob/master/src/Core/MySQL/PacketsProtocolText.cpp#L222-L225

Here's an overview of what falls into that category with my encoding assumptions that we can introduce as a fix:

| ClickHouse type  | Encoding after the fix |
|---|---|
| String | binary |
| FixedString | binary |
| Decimal*      | binary      |
| Array  | utf8  |
| Map |  utf8 |
| UUID  | utf8  |
| IPv4/v6  | utf8  |
| JSON  | utf8  |


*NB on Decimal: with high enough precision (>65) or scale (>30).

Can you please confirm that my assumptions are correct? Especially with the types that will still use utf8 encoding.

**Comment by MaceWindu** [comment]
1. string/fixedstring - agree
2. decimal - cannot comment here as I don't see issues with 23.9 behavior consuming decimal values as they sent currently, but I see some inconsistencies with Decimal128:
- `Decimal32`/`Nullable(Decimal32)`/`Decimal64`/`Nullable(Decimal64)`/`Decimal128` reported to client as decimal
- `Nullable(Decimal128)`/`Decimal256`/`Nullable(Decimal256)` reported as string
3. Array - cannot comment as we currently don't work with this type
4. UUID - agree, it is common for MySql (mariadb even introduced [type alias](https://mariadb.com/kb/en/uuid/) for it) to have it as string. Binary representation is problematic as it could be in big-endian and little-endian formats
5. IPv4/v6 - agree
6. JSON - agree

**Comment by slvrtrn** [comment]
It is clear, thank you :+1: 

> Nullable(Decimal128)/Decimal256/Nullable(Decimal256) reported as string

Should be fixed in the scope of https://github.com/ClickHouse/ClickHouse/issues/39297, the same bug.

**Comment by slvrtrn** [comment]
@MaceWindu, can you please provide some sample data for non-utf8 strings that currently lead to incorrect results on the client side?

**Comment by MaceWindu** [comment]
It could be any binary data that doesn't represent UTF8 stream

```sql
select '\xFF\xFE'::FixedString(2), '\xFF\xFE'::String
```

client library tries to parse it as UTF8 which results in string with two 0xFD characters (substitution symbol for invalid data) - original data is lost

**Comment by MaceWindu** [comment]
because ClickHouse String/FixedString are actually binary types which could store string values in UTF8 encoding it will be better if server return it as binary type so consumer knowing nature of data could treat it as binary or string data

**Comment by slvrtrn** [comment]
@MaceWindu, can you please provide a more concrete scenario where you might experience data corruption with the current version?

Following your example with MySQL JDBC Connector/J:

```java
    private static void testColumnDefinition(Connection conn) throws SQLException {
        ResultSet rs = conn.prepareStatement("select '\\xFF\\xFE'::FixedString(2) a, '\\xFF\\xFE'::String b").executeQuery();
        int rowNum = 1;
        while (rs.next()) {
            System.out.printf("Row #%d\n", rowNum++);
            printHexBytes(rs, "a");
            printHexBytes(rs, "b");
        }
    }

    private static void printHexBytes(ResultSet rs, String col) throws SQLException {
        StringBuilder sb = new StringBuilder();
        for (byte b : rs.getBytes(col)) {
            sb.append(String.format("%02X ", b));
        }
        System.out.println("Col " + col + " in hex: " + sb.toString());
    }
```

prints 

```
Row #1
Col a in hex: FF FE 
Col b in hex: FF FE 
```

i.e., no corruption here?

**Comment by alexey-milovidov** [comment]
No answer, closing.
