### ISSUE TITLE
Inactive parts not being removed 

### ISSUE THREAD

**Issue by rsyvarth** [ClickHouse/ClickHouse#38807]
**Describe the unexpected behaviour**
Our instance is seeing a growing number of inactive parts which are never getting cleaned up
```
> select active, count(*) from system.parts group by active
+------+-------+
|active|count()|
+------+-------+
|0     |118616 |
|1     |754    |
+------+-------+
```
* New inactive parts are being cleaned up correctly, the issue seems to be with this set of ~100k old inactive parts (these inactive parts are several days old at this point)
* We have tried increasing `max_part_removal_threads` as suggested in #14403 thinking that maybe there was just a backlog of inactive parts but this made no impact
* Digging through the source a bit more, I came across the `removal_tid_lock` field on the `system.parts` table and noticed that it is set to `0` for all of the parts which are failing to be removed
  * Reviewing [`MergeTreeData::loadDataParts`](https://github.com/ClickHouse/ClickHouse/blob/42ea79c266850239c5640a3f4ea34531b92ba62c/src/Storages/MergeTree/MergeTreeData.cpp#L1350) it seems that at least in some cases inactive parts with empty removal lock values have them re-set on boot to ensure they are eligible to get cleaned up 
  * We attempted to reboot clickhouse to see if this logic would trigger cleanup but this made no impact
* I don't know enough about the underlying data model here to know whether or not this is intentional, but it does seem to be that the empty `removal_tid_lock` value is causing these parts to be filtered out when they are being checked for removal

**How to reproduce**
We run clickhouse in kubernetes and recently had high memory pressure lead to clickhouse getting OOM killed by the OS which I think may have triggered this bad state, but I am not 100% sure about that. 

**Expected behavior**
Inactive parts should be removed

**Comment by den-crane** [comment]
CH version ?

Probably https://github.com/ClickHouse/ClickHouse/pull/24258 fixed https://github.com/ClickHouse/ClickHouse/pull/38486

**Comment by rsyvarth** [comment]
Oops! Currently on 22.6
