### ISSUE TITLE
Multireplace / Transliterate? 

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#38833]
> (you don't have to strictly follow this form)

**Use case**

Change the used aphabet for some encoding (see https://github.com/ClickHouse/ClickHouse/issues/38832,  https://github.com/ClickHouse/ClickHouse/issues/38002 etc), implement  Caesar cipher, change DNA to RNA etc. 

:) 

**Describe the solution you'd like**

Something similar to  [`tr` operator in perl](https://perldoc.perl.org/perlop#tr/SEARCHLIST/REPLACEMENTLIST/cdsr) 

Single pass through the string with all replaces applied. 

```
Select transliterate(dna, 'ACGTacgt', 'TGCAtgca') AS rna
-- if first arg have some characters listed in the   second arg, then they will be replaced by corresponding chars from the third arg
-- other characters are passed as is
```

Or more expressive (but more noisy) format with map

```
Select transliterate(dna,{ 'A' :'T', 'C' :'G',...}) AS rna
```

**Describe alternatives you've considered**

Sequence of replace calls - when aphabet is long (like base64) it looks ugly, and create a lot of copies of the string, so slow.

**Comment by alexey-milovidov** [comment]
Should be pretty easy to implement.
The name is either `transliterate` or `replaceCharacters`.
With plain and `-UTF8` variant.

The plain variant can be implemented by a lookup table and UTF-8 with a hash table.

PS. I would like to have first-class support for base64 for URL.

**Comment by den-crane** [comment]
BTW, oracle rdbms has similar function and it named `translate`

https://www.oracletutorial.com/oracle-string-functions/oracle-translate/

**Comment by den-crane** [comment]
PG as well https://www.postgresqltutorial.com/postgresql-string-functions/postgresql-translate/

```
psql> SELECT TRANSLATE('11-22', '12', 'ab');
 translate
-----------
 aa-bb
(1 row)
```

**Comment by filimonov** [comment]
> PS. I would like to have first-class support for base64 for URL.

sure. That just reminded me that I used in the past at least 4 different options for base64 alphabets (standard, URL-safe, another variant of URL-safe, and the one to preserve the monotonicity).

**Comment by UnamedRus** [comment]
Related https://github.com/ClickHouse/ClickHouse/issues/28520
