### ISSUE TITLE
Is there anyway to do the intersection operator for HHL or Datasketches object

### ISSUE THREAD

**Issue by einvince** [ClickHouse/ClickHouse#38842]
For Datasketches, from this issue https://github.com/ClickHouse/ClickHouse/issues/14893, it mentioned  **_intersection & difference_**  is not supported now.

How about the HHL, is there any way to do it?

**Comment by den-crane** [comment]
No. No such feature.

**Comment by pzhdfy** [comment]
we add https://github.com/ClickHouse/ClickHouse/pull/39919
https://github.com/ClickHouse/ClickHouse/pull/39919
