### ISSUE TITLE
 SimpleAggregateFunction was incorrect result

### ISSUE THREAD

**Issue by 171563857** [ClickHouse/ClickHouse#38855]
==== kafka engine ====
CREATE TABLE com_report_sdk_example_kafka  on cluster default  (
    event_id String,
    event_name String,
    scene String default '',
    platform String default '',
    platform_code UInt16 default 0,
    os String default '',
    os_version String default '',
    app_version String default '',
    first_qid String default '',
    this_qid String default '',
    first_lid String default '',
    this_lid String default '',
    brand String default '',
    model String default '',
    ip String default '',
    network UInt8 default 0,
    time_stamp DateTime('Asia/Shanghai'),
    time_stamp_millis DateTime64(3, 'Asia/Shanghai'),
    city String default '',
    province String default '',
    country String default '',
    lib_version String default '',
    device_id String default '',
    source_pkg String default '',
    newer_state UInt8 default 0,
    icon_state UInt8 default 0,
    menubar_state UInt8 default 0,
    ad_id String default '',
    ad_network UInt8 default 0,
    ad_position String default '',
    ad_style String default '',
    ad_type String default '',
    screen_width UInt16 default 0,
    screen_height UInt16 default 0,
    login_state UInt8 default 0,
    pay_state UInt8 default 0,
    mode_state UInt8 default 0,
    page_url String default '',
    referer String default '',
    result String default '',
    page_type String default '',
    page_name String default '',
    element_name String default '',
    pay_amount Decimal32(4) default 0.0,
    session_id String default '',
    utm_ad_id String default '',
    utm_campaign String default '',
    utm_content String default '',
    utm_medium String default '',
    utm_source String default '',
    utm_term String default '',
    duration UInt32 default 0,
    ext_field_1 String default '',
    ext_field_2 String default '',
    ext_field_3 String default '',
    ext_field_4 String default '',
    ext_field_5 String default '',
    ext_field_6 String default '',
    ext_field_7 String default '',
    ext_field_8 String default '',
    ext_field_9 String default '',
    ext_field_10 String default ''
) ENGINE = Kafka() 
SETTINGS
    	input_format_allow_errors_num = 3,
    	kafka_broker_list = '192.168.2.91:9092',
    	kafka_num_consumers = 4,
    	kafka_topic_list = 'com_report_sdk_example_kafka',
    	kafka_group_name = 'com_report_sdk_example_group',
    	kafka_row_delimiter = '\n',
    	kafka_format = 'JSONEachRow';

==== master table ====
CREATE TABLE com_report_sdk_example  on cluster default  (
    event_id String,
    event_name String,
    scene String default '',
    platform String default '',
    platform_code UInt16 default 0,
    os String default '',
    os_version String default '',
    app_version String default '',
    first_qid String default '',
    this_qid String default '',
    first_lid String default '',
    this_lid String default '',
    brand String default '',
    model String default '',
    ip String default '',
    network UInt8 default 0,
    time_stamp DateTime('Asia/Shanghai'),
    time_stamp_millis UInt64,
    city String default '',
    province String default '',
    country String default '',
    lib_version String default '',
    device_id String default '',
    source_pkg String default '',
    newer_state UInt8 default 0,
    icon_state UInt8 default 0,
    menubar_state UInt8 default 0,
    ad_id String default '',
    ad_network UInt8 default 0,
    ad_position String default '',
    ad_style String default '',
    ad_type String default '',
    screen_width UInt16 default 0,
    screen_height UInt16 default 0,
    login_state UInt8 default 0,
    pay_state UInt8 default 0,
    mode_state UInt8 default 0,
    page_url String default '',
    referer String default '',
    result String default '',
    page_type String default '',
    page_name String default '',
    element_name String default '',
    pay_amount Decimal32(4) default 0.0,
    session_id String default '',
    utm_ad_id String default '',
    utm_campaign String default '',
    utm_content String default '',
    utm_medium String default '',
    utm_source String default '',
    utm_term String default '',
    duration UInt32 default 0,
    ext_field_1 String default '',
    ext_field_2 String default '',
    ext_field_3 String default '',
    ext_field_4 String default '',
    ext_field_5 String default '',
    ext_field_6 String default '',
    ext_field_7 String default '',
    ext_field_8 String default '',
    ext_field_9 String default '',
    ext_field_10 String default ''
) ENGINE = ReplicatedMergeTree() PARTITION BY toYYYYMMDD(time_stamp) ORDER BY (
   event_id, event_name, login_state, pay_state, newer_state, icon_state, menubar_state, mode_state,
   os, brand, network, lib_version, app_version, os_version, platform, platform_code,
   referer, ad_style, ad_type, ad_network, ad_position, ad_id,
   scene, element_name, country, province, city, screen_width, screen_height,
   first_qid, this_qid, first_lid, this_lid, model, page_url, page_name, page_type, result, source_pkg,
   utm_campaign, utm_content, utm_medium, utm_source, utm_term, utm_ad_id, pay_amount, duration,
   time_stamp, ip, device_id, session_id, time_stamp_millis,
   ext_field_1, ext_field_2, ext_field_3, ext_field_4, ext_field_5, ext_field_6, ext_field_7, ext_field_8, ext_field_9, ext_field_10
);

==== kafka to master view ====
CREATE MATERIALIZED VIEW com_report_sdk_example_view  on cluster default  TO com_report_sdk_example
AS SELECT
	event_id, event_name, scene, platform, platform_code, os, os_version, app_version, 
	first_qid, this_qid, first_lid, this_lid, brand, model, ip, network, time_stamp, time_stamp_millis, city, province, country,
	lib_version, device_id, source_pkg, newer_state, icon_state, menubar_state, 
	ad_id, ad_network, ad_position, ad_style, ad_type, screen_width, screen_height, 
	login_state, pay_state, mode_state, page_url, referer, result, 
	page_type, page_name, element_name, pay_amount, session_id, duration, utm_ad_id, utm_campaign, utm_content, utm_medium, utm_source, utm_term, 
	ext_field_1, ext_field_2, ext_field_3, ext_field_4, ext_field_5, ext_field_6, ext_field_7, ext_field_8, ext_field_9, ext_field_10
	FROM com_report_sdk_example_kafka;

==== analysis table granularity by hour ====
CREATE TABLE com_report_sdk_example_analysis  on cluster default  (
    event_id String default '',
    scene String default '',
    platform String default '',
    platform_code UInt16 default 0,
    os String default '',
    os_version String default '',
    app_version String default '',
    this_qid String default '',
    this_lid String default '',
    brand String default '',
    model String default '',
    network UInt8 default 0,
    city String default '',
    province String default '',
    country String default '',
    lib_version String default '',
    newer_state UInt8 default 0,
    icon_state UInt8 default 0,
    menubar_state UInt8 default 0,
    ad_id String default '',
    ad_network UInt8 default 0,
    ad_position String default '',
    ad_style String default '',
    ad_type String default '',
    screen_width UInt16 default 0,
    screen_height UInt16 default 0,
    login_state UInt8 default 0,
    pay_state UInt8 default 0,
    mode_state UInt8 default 0,
    page_url String default '',
    referer String default '',
    result String default '',
    page_type String default '',
    page_name String default '',
    element_name String default '',
    pay_amount Decimal32(4) default 0.0,
    utm_ad_id String default '',
    utm_campaign String default '',
    utm_content String default '',
    utm_medium String default '',
    utm_source String default '',
    utm_term String default '',
    day Date,
    hour DateTime('Asia/Shanghai'),
    total_duration SimpleAggregateFunction(sum, UInt64),
    ext_field_1 String default '',
    ext_field_2 String default '',
    ext_field_3 String default '',
    ext_field_4 String default '',
    ext_field_5 String default '',
    ext_field_6 String default '',
    ext_field_7 String default '',
    ext_field_8 String default '',
    ext_field_9 String default '',
    ext_field_10 String default '',
    uv AggregateFunction(uniqCombined, String),
    pv SimpleAggregateFunction(sum, UInt64)
) ENGINE = ReplicatedMergeTree() PARTITION BY day ORDER BY (
   day, login_state, pay_state, newer_state, icon_state, menubar_state, mode_state,
   os, brand, network, lib_version, app_version, os_version, platform, platform_code,
   hour, referer, ad_style, ad_type, ad_network, ad_position, ad_id,
   event_id, scene, element_name, country, province, city, screen_width, screen_height,
   this_qid, this_lid, model, page_url, page_name, page_type, result,
   utm_campaign, utm_content, utm_medium, utm_source, utm_term, utm_ad_id, pay_amount,
   ext_field_1, ext_field_2, ext_field_3, ext_field_4, ext_field_5, ext_field_6, ext_field_7, ext_field_8, ext_field_9, ext_field_10
);

==== master to analysis view ====
create MATERIALIZED VIEW com_report_sdk_example_analysis_view  on cluster default  to com_report_sdk_example_analysis
AS 
SELECT event_id, scene, platform, platform_code, os, os_version, app_version, this_qid, this_lid, brand,
       model, network, city, province, country, lib_version, newer_state, icon_state, menubar_state,
       ad_id, ad_network, ad_position, ad_style, ad_type, screen_width, screen_height, login_state,
       pay_state, mode_state, page_url, referer, result, page_type, page_name, element_name,
       pay_amount, utm_ad_id, utm_campaign, utm_content, utm_medium, utm_source, utm_term,
       ext_field_1, ext_field_2, ext_field_3, ext_field_4, ext_field_5, ext_field_6, ext_field_7, ext_field_8, ext_field_9, ext_field_10,
       toDate(time_stamp) as day, toStartOfHour(time_stamp) as hour, sum(duration) as total_duration,
       uniqCombinedState(device_id) as uv, sum(1) as pv 
from com_report_sdk_example 
group by event_id, scene, platform, platform_code, os, os_version, app_version, this_qid, this_lid, brand,
         model, network, city, province, country, lib_version, newer_state, icon_state, menubar_state,
         ad_id, ad_network, ad_position, ad_style, ad_type, screen_width, screen_height, login_state,
         pay_state, mode_state, page_url, referer, result, page_type, page_name, element_name,
         pay_amount, utm_ad_id, utm_campaign, utm_content, utm_medium, utm_source, utm_term,
         ext_field_1, ext_field_2, ext_field_3, ext_field_4, ext_field_5, ext_field_6, ext_field_7, ext_field_8, ext_field_9, ext_field_10,
         day,hour;

============================================================================
about 40million data a day
ck: 32 core 64g

my problem is the test_hour table "pv" and "uv" was incorrect result
there will be an error of about 10% by target table and master table
same table structure was error more than 30%~40% in some scene, it's very terrible !!!

**Comment by den-crane** [comment]
Provide  `ORDER BY` for `) ENGINE = ReplicatedMergeTree() PARTITION BY day ORDER BY (.....);`

**Comment by 171563857** [comment]
> Provide `ORDER BY` for `) ENGINE = ReplicatedMergeTree() PARTITION BY day ORDER BY (.....);`
has provide, thx

**Comment by den-crane** [comment]
Provide full reproducible example. Full create table / create mater.view / insert / selects.

**Comment by 171563857** [comment]
> Provide full reproducible example. Full create table / create mater.view / insert / selects.

has provide, thx

**Comment by 171563857** [comment]
clickhouse was restarted yesterday, but the problem still exists

**Comment by den-crane** [comment]
It's kinda strange to use `AggregateFunction(uniqCombined, String), SimpleAggregateFunction(sum, UInt64)` with ReplicatedMergeTree. ReplicatedMergeTree does not collapse/merge rows. 
And never calculates AggregateFunctions.

**Comment by den-crane** [comment]
No info
