### ISSUE TITLE
runningDifference WRONG RESULT with enable_optimize_predicate_expression

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#3885]
Connected to ClickHouse server version 18.16.0 revision 54412.

set enable_optimize_predicate_expression = 1

```
select n, z, changed from (
   select n, z, runningDifferenceStartingWithFirstValue(n) as changed from (
       select ts, n,z from system.one array join [1,3,4,5,6] as ts, 
          [1,2,2,2,1] as n, ['a', 'a', 'b', 'a', 'b'] as z 
    order by n, ts DESC)
) where changed = 0

┌─n─┬─z─┬─changed─┐
│ 2 │ b │       0 │
└───┴───┴─────────┘

```

set enable_optimize_predicate_expression = 0
The same query

```
┌─n─┬─z─┬─changed─┐
│ 1 │ a │       0 │
│ 2 │ b │       0 │
│ 2 │ a │       0 │
└───┴───┴─────────┘
```

**Comment by den-crane** [comment]
@zhang2014

**Comment by zhang2014** [comment]
@den-crane Because the calculation of the function depends on the order of the data. 

 @alexey-milovidov  Maybe we don't push down in this case? or , do you have any good suggestions ? : )

**Comment by den-crane** [comment]
> Maybe we don't push down in this case? or , do you have any good suggestions ? : 
Of cause you should not. The same as with order by limit ... and so on.

**Comment by zombiemonkey** [comment]
Unfortunately this fix in 19.3.3 has broken some key features we've been using where we calculate deltas on 30-40 million series of realtime data (billions of rows per day). We had some very complex logic we were able to encapsulate in views with predicate push down. In our case we are not dependent on the result of the stateful function in a where clause so don't get an incorrect result as per den-crane's original report. I've tried using plain arrayMap calculations with enable_optimize_predicate_expression.. and this doesn't work either - "DB::Exception: Unknown function lambda."

Example query:

```
SET enable_optimize_predicate_expression = 1

Ok.

0 rows in set. Elapsed: 0.001 sec. 

WITH arrayJoin(arrayMap(x -> x, arraySort(groupArray((ts, n))))) AS k
SELECT 
    z, 
    k
FROM 
(
    SELECT 
        ts, 
        n, 
        z
    FROM system.one 
    ARRAY JOIN 
        [1, 3, 4, 5, 6] AS ts, 
        [1, 2, 2, 2, 1] AS n, 
        ['a', 'a', 'b', 'a', 'b'] AS z
    ORDER BY 
        n ASC, 
        ts DESC
) 
WHERE z = 'a'
GROUP BY z

Received exception from server (version 19.3.3):
Code: 46. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Unknown function lambda. 

0 rows in set. Elapsed: 0.003 sec.
```

**Comment by zombiemonkey** [comment]
I actually think this may be justification for parameterized views instead. That would be a very powerful feature.

**Comment by zombiemonkey** [comment]
https://github.com/yandex/ClickHouse/issues/4389

**Comment by den-crane** [comment]
@abyss7 

clickhouse-client --enable_optimize_predicate_expression=1

```
select count() 
from (
  select a, runningDifference(a) rd
  from 
  (   select * 
    from (
      select 1 a
      union all 
      select 2 a
    )
    order by a desc
  )
  Where rd=-1
)

0 rows in set.
```

clickhouse-client --enable_optimize_predicate_expression=0
```
┌─count()─┐
│       1 │
└─────────┘

1 rows in set.
```

19.8.1.562

**Comment by den-crane** [comment]
```
SELECT k, v, d, i FROM
(    SELECT t.1 AS k, t.2 AS v,
        runningDifference(v) AS d,
        runningDifference(xxHash32(t.1)) AS i
    FROM
    (   SELECT arrayJoin([('a', 1), ('a', 2), ('a', 3), ('b', 11), ('b', 13), ('b', 15)]) AS t))
WHERE i = 0

WRONG RESULT 
enable_optimize_predicate_expression=1
┌─k─┬──v─┬──d─┬─i─┐
│ a │  1 │  0 │ 0 │
│ a │  2 │  1 │ 0 │
│ a │  3 │  1 │ 0 │
│ b │ 13 │ 10 │ 0 │
│ b │ 15 │  2 │ 0 │
└───┴────┴────┴───┘

Right Result
enable_optimize_predicate_expression=0
┌─k─┬──v─┬─d─┬─i─┐
│ a │  1 │ 0 │ 0 │
│ a │  2 │ 1 │ 0 │
│ a │  3 │ 1 │ 0 │
│ b │ 13 │ 2 │ 0 │
│ b │ 15 │ 2 │ 0 │
└───┴────┴───┴───┘
```

**Comment by den-crane** [comment]
.
