### ISSUE TITLE
Getting CANNOT_PARSE_INPUT_ASSERTION_FAILED sometimes during RowBinary inserts

### ISSUE THREAD

**Issue by x052bb** [ClickHouse/ClickHouse#38854]
Hi all

We use JDBC driver to insert data into Clickhouse (v 21.12) using RowBinary format. Recently we noticed that there are periodic errors in logs of the following kind:

`Code: 27. DB::ParsingException: Cannot parse input: expected '\r\n' before: '\0eM6\0\0\0\0\0\0\0\0\0\0\0\0��+a?\0\0\0\0\0\0\0\0\0\0\0\0\\��}\0\0\0\0\0\0\0\0\0\0\0���I\0\0\0\0\0\0\0\0\0\0\0P�;\0\0\0\0\0\0\0\0\0\0\0\0�0�\0\0\0\0\0\0\0\0\0\0\0\0z�4V�(\0\0\0\0\0\0\0\0\0\0\0��"�\0\0\0\0\0\0\0\0\0\0\0\0���2�\0\0\0\0\0\0\0\0\0\0N�X\0'. (CANNOT_PARSE_INPUT_ASSERTION_FAILED), Stack trace (when copying this message, always include the lines below):`

The problem seems not related to specific data sent to the server, I couldn't reproduce the issue sending the same data that failed previously. We are inserting tens of thousands of batches per day and only 2-3 of them fail with this error (looks random). The error message hints that the server is not able to parse chunked-encoded data sent by client.

What seems weird is that **although the data is not inserted, HTTP request returns 200 status**. So there's no way to detect if something went wrong from client perspective, we just lose the data. Is this behavior known/expected?

**Comment by zhicwu** [comment]
> Code: 27. DB::ParsingException: Cannot parse input

Similar issue was reported in ClickHouse/clickhouse-jdbc#961 and maybe ClickHouse/clickhouse-jdbc#893. Is there any proxy sits between client and server? Are you using input function for insertion?

> What seems weird is that although the data is not inserted, HTTP request returns 200 status. So there's no way to detect if something went wrong from client perspective, we just lose the data. Is this behavior known/expected?

It's a known issue. ClickHouse/ClickHouse#21136 could be a solution. You can use `curl --get --data-urlencode 'query=select throwIf(number>=100000000) from numbers(500000000)' -v 'localhost:8123' | grep -v '^0$'` to reproduce. Query will usually end up with deserialization error and mutation can be addressed once ClickHouse/clickhouse-jdbc#975 is implemented.

**Comment by x052bb** [comment]
>  Is there any proxy sits between client and server? 

Yes. But why does it matter?

>Are you using input function for insertion?

No

> It's a known issue. 

Do I understand correctly that using **wait_end_of_query=1** will help us get an error HTTP status in this case?

**Comment by den-crane** [comment]
BTW it is strange `Cannot parse input: expected '\r\n'` 
Can you share full fragment from CH logs? With the query and a stacktrace ?

**Comment by x052bb** [comment]
> BTW it is strange for rowBinary `Cannot parse input: expected '\r\n'` 

Looks like this "\r\n" is HTTP protocol chunked transfer delimiter, so it's not related to any specific clickhouse data format

> Can you share full fragment from CH logs? With the query and a stacktrace ?

The query text won't help as it's simple 
`INSERT INTO table (column1, ...., columnN) FORMAT RowBinary`

Stacktrace:

```
Code: 27. DB::ParsingException: Cannot parse input: expected '\r\n' before: '\0eM6\0\0\0\0\0\0\0\0\0\0\0\0��+a?\0\0\0\0\0\0\0\0\0\0\0\0\\��}\0\0\0\0\0\0\0\0\0\0\0���I\0\0\0\0\0\0\0\0\0\0\0P�;\0\0\0\0\0\0\0\0\0\0\0\0�0�\0\0\0\0\0\0\0\0\0\0\0\0z�4V�(\0\0\0\0\0\0\0\0\0\0\0��"�\0\0\0\0\0\0\0\0\0\0\0\0���2�\0\0\0\0\0\0\0\0\0\0N�X\0'. (CANNOT_PARSE_INPUT_ASSERTION_FAILED), Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x140a842c in /home/snow/apps/clickhouse/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x9b50bfa in /home/snow/apps/clickhouse/bin/clickhouse
2. DB::ParsingException::ParsingException(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x9b5454b in /home/snow/apps/clickhouse/bin/clickhouse
3. DB::throwAtAssertionFailed(char const*, DB::ReadBuffer&) @ 0x9b953ff in /home/snow/apps/clickhouse/bin/clickhouse
4. ? @ 0x9b956af in /home/snow/apps/clickhouse/bin/clickhouse
5. DB::HTTPChunkedReadBuffer::nextImpl() @ 0x11e432cd in /home/snow/apps/clickhouse/bin/clickhouse
6. DB::wrapReadBufferReference(DB::ReadBuffer&)::ReadBufferWrapper::nextImpl() @ 0x10b628ec in /home/snow/apps/clickhouse/bin/clickhouse
7. DB::wrapReadBufferReference(DB::ReadBuffer&)::ReadBufferWrapper::nextImpl() @ 0x10b628ec in /home/snow/apps/clickhouse/bin/clickhouse
8. DB::ConcatReadBuffer::nextImpl() @ 0x112727ca in /home/snow/apps/clickhouse/bin/clickhouse
9. DB::LimitReadBuffer::nextImpl() @ 0x9bd41fc in /home/snow/apps/clickhouse/bin/clickhouse
10. DB::(anonymous namespace)::copyDataImpl(DB::ReadBuffer&, DB::WriteBuffer&, bool, unsigned long, std::__1::atomic<int> const*, std::__1::shared_ptr<DB::Throttler>) @ 0x9c77c88 in /home/snow/apps/clickhouse/bin/clickhouse
11. DB::copyData(DB::ReadBuffer&, DB::WriteBuffer&) @ 0x9c77c1d in /home/snow/apps/clickhouse/bin/clickhouse
12. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::__1::shared_ptr<DB::Context>, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>, std::__1::optional<DB::FormatSettings> const&) @ 0x11668667 in /home/snow/apps/clickhouse/bin/clickhouse
13. DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::__1::optional<DB::CurrentThread::QueryScope>&) @ 0x11dedca7 in /home/snow/apps/clickhouse/bin/clickhouse
14. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x11df158e in /home/snow/apps/clickhouse/bin/clickhouse
15. DB::HTTPServerConnection::run() @ 0x11e416d8 in /home/snow/apps/clickhouse/bin/clickhouse
16. Poco::Net::TCPServerConnection::start() @ 0x1401caa7 in /home/snow/apps/clickhouse/bin/clickhouse
17. Poco::Net::TCPServerDispatcher::run() @ 0x1401cf67 in /home/snow/apps/clickhouse/bin/clickhouse
18. Poco::PooledThread::run() @ 0x14109227 in /home/snow/apps/clickhouse/bin/clickhouse
19. Poco::ThreadImpl::runnableEntry(void*) @ 0x14106be6 in /home/snow/apps/clickhouse/bin/clickhouse
20. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
21. clone @ 0xfe9fd in /usr/lib64/libc-2.17.so
```

**Comment by x052bb** [comment]
> @x052bb do you use compression=1 in JDBC driver ?

@den-crane Yes

**Comment by zhicwu** [comment]
> > Is there any proxy sits between client and server?
> 
> Yes. But why does it matter?

When I test load balancing using chproxy with multiple concurrent users sending same query, I found one de-serialization error which didn't happen if I changed to connect to CH servers directly. I'm not sure if it's an issue with JDBC driver, chproxy, or the network inbetween, but as a general approach for troubleshooting, I'd suggest you to try again without any proxy.
