### ISSUE TITLE
Change in seconds parsing behaviour

### ISSUE THREAD

**Issue by gingerwizard** [ClickHouse/ClickHouse#38863]
The behaviour of seconds parsing for settings appears to have changed for 22.6.

Consider,

```
CREATE SETTINGS PROFILE test_profile SETTINGS wait_for_async_insert_timeout = 3 TO default;
SHOW CREATE SETTINGS PROFILE test_profile;
```
in 22.6 this gives,

`CREATE SETTINGS PROFILE test_profile SETTINGS wait_for_async_insert_timeout = 3000000. TO default `

vs 22.5

`CREATE SETTINGS PROFILE test_profile SETTINGS wait_for_async_insert_timeout = 3 TO default`

**Comment by Algunenano** [comment]
It seems related yes. I'm not sure how to reproduce it (never used profile settings and it doesn't seem to be active by default) but I'll have a look

**Comment by Algunenano** [comment]
Ok, found the issue. It's a problem with implicit casts and my wrong expectation.

The constructor from Field (`SettingFieldSeconds::SettingFieldTimespan(const Field & f)`) is calling a constructor with `Poco::Timespan::TimeDiff` which I was expecting to be casted as `Poco::Timespan` but its being casted as `UInt64`, which multiplies the value by `1000000`.

It needs a proper explicit cast and tests. I'll send a PR with the fix tomorrow.

**Comment by tavplubix** [comment]
One more issue caused by `Poco::Timespan`, it's really hard to use it correctly :)
I hope we will remove `Poco::Timespan` at all sometime
