### ISSUE TITLE
How to realize the aggregate function like sum with UDF?

### ISSUE THREAD

**Issue by feichendingxiangyong** [ClickHouse/ClickHouse#38867]
Hi all:
I am new in ClickHouse, i want to realize an aggregate function with UDF(python program language). 
But I got an exception: wrong result, expected 10 row(s), actual 1

My python script:

```
#!/usr/bin/python3

import sys

if __name__ == "__main__":
    res = 0
    for line in sys.stdin:
        res+=int(line)
    print(res, end="\n")
    sys.stdout.flush()

```
I have found one similar [issue](https://github.com/ClickHouse/ClickHouse/issues/35258) , but still no idea. 
Thank you.

**Comment by feichendingxiangyong** [comment]
Why i need do this:
i want to do something like logistic regression or decision tree generation with Sklearn lib.  
The benefits are obvious. Compared with executing Python externally, it eliminates the overhead of network transmission, additional data storage, and data serialization / deserialization.

**Comment by UnamedRus** [comment]
Executable table function or collapse all data in arrays and use simple UDF.

ClickHouse doesnt support aggregating udf for now

**Comment by feichendingxiangyong** [comment]
@UnamedRus Thanks, it works. What's the plan for supporting aggregating udf?

**Comment by UnamedRus** [comment]
> What's the plan for supporting aggregating udf?

No plans AFAIK, but you can create feature request for it.

**Comment by jzombi** [comment]
Hi @UnamedRus, by the following:
> Executable table function or collapse all data in arrays and use simple UDF.

did you mean this:
```
SELECT * FROM executable('input.py', 'TabSeparated', (SELECT 'value String'), {source})
```
([source](https://github.com/ClickHouse/ClickHouse/blob/31891322a51febe79ec3edba6278b5cecdd9e8df/tests/integration/test_executable_table_function/test.py#L95)) ?

Checking the udfs in the [user_scrips](https://github.com/ClickHouse/ClickHouse/tree/31891322a51febe79ec3edba6278b5cecdd9e8df/tests/integration/test_executable_table_function/user_scripts) directory next to the test file, I got the impression, that these work similarly to regular executable udfs (process the input source line-by-line). Is it possible to use them for aggregation? Could you show me an example?

**Comment by jzombi** [comment]
Answering my above question https://github.com/ClickHouse/ClickHouse/issues/38867#issuecomment-1329509482:

The executable table function / engine seems to execute the script on the whole input source sequentially (by default). It is in contrast with executable UDFs, as those run on chunks of data (running in multiple background processes concurrently), and it is not possible to track a global aggregation state with them.

Some limitations that I've encountered when using the executable table functions for aggregation function:
* undocumented feature (helpful example: https://github.com/ClickHouse/ClickHouse/issues/38446#issuecomment-1173123259)
* source query inside the table function does not support CTEs from outer query
* syntax is complicated
* sequential processing

**Comment by UnamedRus** [comment]
> and it is not possible to track a global aggregation state with them.

Do you mean, that clickhouse expect exactly the same amount of rows on udf output?

**Comment by jzombi** [comment]
> > and it is not possible to track a global aggregation state with them.
> 
> Do you mean, that clickhouse expect exactly the same amount of rows on udf output?

My point was that (if I understand it correctly) there are multiple instances of the same executable UDF process, the input blocks are distributed among these processes for concurrent execution, and it is not possible to update a shared state between them.

But I think you are right too, and ClickHouse expects the same amount of output rows, which also restricts the usability of executable UDFs for aggregation purposes.
