### ISSUE TITLE
provide a ./clickhouse uninstall

### ISSUE THREAD

**Issue by rafaelvanoni** [ClickHouse/ClickHouse#38877]
First time user here, I installed clichouse using the method described in 

https://clickhouse.com/docs/en/quick-start/#1-start-clickhouse

Which doesn't use a package manager, so there's no equivalent way of removing it other than finding/deleting the files manually. It would be very helpful to have a clean way of uninstalling it with that method.

**Comment by geekyouth** [comment]
i also want to uninstall my clickhouse which installed from tgz.

**Comment by lil5** [comment]
```
sudo system stop clickhouse
sudo rm -rf \
   /usr/bin/clickhouse* \
   /etc/clickhouse-server \
   /var/log/clickhouse-server \
   /var/lib/clickhouse-server \
   /var/run/clickhouse-server \
   /etc/clickhouse-server
sudo groupdel clickhouse
sudo userdel -r clickhouse
sudo rm /etc/security/limits.d/clickhouse.conf
```

**Comment by alexey-milovidov** [comment]
It is more complicated than that. For example, the uninstall script should not touch data or the modified configuration files (in contrast to "purge").

**Comment by alexey-milovidov** [comment]
It is better to not bother with uninstalling because it is difficult to test.
It can be error-prone (see https://github.com/MrMEEE/bumblebee-Old-and-abbandoned/issues/123 as an example).

**Comment by alexey-milovidov** [comment]
Also worth noting is that our Debian, RPM, and tgz packages provide the uninstall script.

**Comment by yukha-dw** [comment]
> Also worth noting is that our Debian, RPM, and tgz packages provide the uninstall script.

Hello @alexey-milovidov, I couldn't find uninstallation script on `clickhouse-client-24.4.1.2088-amd64.tgz`, it only has `/install/doinst.sh` command.

**Comment by khusniridh0** [comment]
# Find file & directory
sudo find / -name *clickhouse* > delete.txt

# Output
/run/clickhouse-server
/tmp/clickhouse.decompression.879593.lock
/usr/bin/clickhouse-git-import
/usr/bin/clickhouse-local
/usr/bin/clickhouse-keeper-converter
/usr/bin/clickhouse-keeper
/usr/bin/clickhouse-client
/usr/bin/clickhouse-extract-from-config
/usr/bin/clickhouse-server
/usr/bin/clickhouse-compressor
/usr/bin/clickhouse-disks
/usr/bin/clickhouse-format
/usr/bin/clickhouse
/usr/bin/clickhouse-benchmark
/usr/bin/clickhouse-obfuscator
/home/ubuntu/.clickhouse-client-history
/home/ubuntu/Downloads/clickhouse
/etc/clickhouse-server
/etc/security/limits.d/clickhouse.conf
/var/lib/clickhouse
/var/log/clickhouse-server

# Confirmation (Optional)
sudo ls -l \
    /run/clickhouse-server \
    /tmp/clickhouse.decompression.879593.lock \
    /usr/bin/clickhouse-git-import \
    /usr/bin/clickhouse-local \
    /usr/bin/clickhouse-keeper-converter \
    /usr/bin/clickhouse-keeper \
    /usr/bin/clickhouse-client \
    /usr/bin/clickhouse-extract-from-config \
    /usr/bin/clickhouse-server \
    /usr/bin/clickhouse-compressor \
    /usr/bin/clickhouse-disks \
    /usr/bin/clickhouse-format \
    /usr/bin/clickhouse \
    /usr/bin/clickhouse-benchmark \
    /usr/bin/clickhouse-obfuscator \
    /home/ubuntu/.clickhouse-client-history \
    /home/ubuntu/Downloads/clickhouse \
    /etc/clickhouse-server \
    /etc/security/limits.d/clickhouse.conf \
    /var/lib/clickhouse \
    /var/log/clickhouse-server

# Delete all related
sudo rm -r \
    /run/clickhouse-server \
    /tmp/clickhouse.decompression.879593.lock \
    /usr/bin/clickhouse-git-import \
    /usr/bin/clickhouse-local \
    /usr/bin/clickhouse-keeper-converter \
    /usr/bin/clickhouse-keeper \
    /usr/bin/clickhouse-client \
    /usr/bin/clickhouse-extract-from-config \
    /usr/bin/clickhouse-server \
    /usr/bin/clickhouse-compressor \
    /usr/bin/clickhouse-disks \
    /usr/bin/clickhouse-format \
    /usr/bin/clickhouse \
    /usr/bin/clickhouse-benchmark \
    /usr/bin/clickhouse-obfuscator \
    /home/ubuntu/.clickhouse-client-history \
    /home/ubuntu/Downloads/clickhouse \
    /etc/clickhouse-server \
    /etc/security/limits.d/clickhouse.conf \
    /var/lib/clickhouse \
    /var/log/clickhouse-server

# Delete user & group
sudo groupdel clickhouse
sudo userdel -r clickhouse

**Comment by jmoraispk** [comment]
> sudo system stop clickhouse

Use `sudo systemctl stop clickhouse-server` instead now.
