### ISSUE TITLE
Reload dictionary failed: `Setting table or where cannot be used with query parameter` while upgrading ClickHouse version from  21.3.13.9 to 22.3.2.1

### ISSUE THREAD

**Issue by lzydmxy** [ClickHouse/ClickHouse#38879]
```sql
21.3.13.9
CREATE DICTIONARY rico.user_pin_dict_local
(
    `user_log_acct` String,
    `uid` UInt64
)
PRIMARY KEY user_log_acct
SOURCE(CLICKHOUSE(HOST 'localhost' PORT 9600 USER 'default' PASSWORD '1234' DB 'rico' TABLE 'user_pin_local' QUERY 'SELECT user_log_acct, uid FROM rico.user_pin_local'))
LIFETIME(MIN 0 MAX 0)
LAYOUT(COMPLEX_KEY_HASHED())


SELECT count(*)
FROM rico.user_pin_dict_local

Query id: 503fa19a-b730-42db-9d64-9be63d76c164

┌─count()─┐
│       3 │
└─────────┘
```

```sql
22.3.2.1
CREATE DICTIONARY rico.user_pin_dict_local
(
    `user_log_acct` String,
    `uid` UInt64
)
PRIMARY KEY user_log_acct
SOURCE(CLICKHOUSE(HOST 'localhost' PORT 9600 USER 'default' PASSWORD '1234' DB 'rico' TABLE 'user_pin_local' QUERY 'SELECT user_log_acct, uid FROM rico.user_pin_local'))
LIFETIME(MIN 0 MAX 0)
LAYOUT(COMPLEX_KEY_HASHED())


SELECT count(*)
FROM rico.user_pin_dict_local

Query id: 653bf6ff-ef3c-4c97-833f-212c8d615492


0 rows in set. Elapsed: 0.002 sec.

Received exception from server (version 22.3.2):
Code: 1. DB::Exception: Received from 10.203.23.118:9600. DB::Exception: Setting `table` or `where` cannot be used with `query` parameter. (UNSUPPORTED_METHOD)
```

In the version 21.3.13.9, `table` or `where` fields can be used together with the `query` field. Tests found that when used `table` or `where` fields  together with the `query` field,  ClickHouse prefer `table` or `where` to `query`. However, in the new version, we will get an exception, when try to reload this dictionary.

Due to the example of documents, we got a lot of dictionaries used `table` or `where` fields together with the `query` field. 
```sql
-- example of documents
SOURCE(CLICKHOUSE(
    host 'example01-01-1'
    port 9000
    user 'default'
    password ''
    db 'default'
    table 'ids'
    where 'id=10'
    secure 1
    query 'SELECT id, value_1, value_2 FROM default.ids'
));
```

There are two possible solutions：

- Add a configuration that prefer `table` or `where`  to `query` ,when `table` or `where` fields used together with the `query` field
- Compare `query` field with `table` or `where` fields. There is no need to throw an exception, if the result parse from `query` field is the same with `table` or `where` fields.

**Comment by Algunenano** [comment]
This is expected. You can't expect to declare 2 sources and have the DB randomly choose one. It's much better for UX to only admit one of them.
