### ISSUE TITLE
There is no merge process even though tens of thounds of small(<6M) parts exists

### ISSUE THREAD

**Issue by ramseyxu** [ClickHouse/ClickHouse#38880]
(you don't have to strictly follow this form)

**Describe the unexpected behaviour**
After inserting lots of data into clickhouse, there are many small parts on the disk, but there is no merge process

**How to reproduce**
* Which ClickHouse server version to use
ClickHouse server version 21.8.4 revision 54449

* Which interface to use, if matters
ClickHouse client version vSClickhouse-21.8.4.1-007

* `CREATE TABLE` statements for all tables involved
```
CREATE TABLE default.lineorder1 ON CLUSTER cluster_admin
(
    `LO_ORDERKEY` UInt32,
    `LO_LINENUMBER` UInt8,
    `LO_CUSTKEY` UInt32,
    `LO_PARTKEY` UInt32,
    `LO_SUPPKEY` UInt32,
    `LO_ORDERDATE` Date,
    `LO_ORDERPRIORITY` LowCardinality(String),
    `LO_SHIPPRIORITY` UInt8,
    `LO_QUANTITY` UInt8,
    `LO_EXTENDEDPRICE` UInt32,
    `LO_ORDTOTALPRICE` UInt32,
    `LO_DISCOUNT` UInt8,
    `LO_REVENUE` UInt32,
    `LO_SUPPLYCOST` UInt32,
    `LO_TAX` UInt8,
    `LO_COMMITDATE` Date,
    `LO_SHIPMODE` LowCardinality(String)
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{layer}-{shard}/insert_tpch1000s.lineorder1', '{replica}')
PARTITION BY toYear(LO_ORDERDATE)
ORDER BY (LO_ORDERDATE, LO_ORDERKEY)
SETTINGS storage_policy = 's3', index_granularity = 8192
```
* Sample data for all these tables, use [clickhouse-obfuscator]
I'm inserting lineorder.tbl of star-schema
https://clickhouse.com/docs/en/getting-started/example-datasets/star-schema/
clickhouse-client --query "INSERT INTO lineorder FORMAT CSV" < lineorder.tbl

* Queries to run that lead to unexpected result
I have created 40 lineorder tables, and using 100 client on 5 server to execute 
```clickhouse-client --query "INSERT INTO lineorder FORMAT CSV" < lineorder.tbl```
each tbl file 680G, but not all data has been inserted

```
SELECT count(*)
FROM parts
WHERE active = 1

SELECT count(*)
FROM parts
WHERE (active = 1) AND (bytes_on_disk < 6000000)

SELECT *
FROM system.merges
```
**Expected behavior**
There is some merge processes background, and I can see them in system.merges

**Error message and/or stacktrace**

**Additional context**
All insert processes have been canceled
The cpu and disk capacity of our cluster is enough to run merge (Actually, there is no and query )

<img width="877" alt="image" src="https://user-images.githubusercontent.com/4744175/177461937-a1126c7a-7a42-49f6-88f7-658b55131fe6.png">

<img width="1193" alt="image" src="https://user-images.githubusercontent.com/4744175/177461974-0e54e487-2120-4a71-add1-abfb82ef0b5f.png">

**Comment by den-crane** [comment]
>storage_policy = 's3'

Did you disabled merges for s3 disk ?
Provide disk/volume/storage configuration.

**Comment by ramseyxu** [comment]
Merges for S3 disk is enabled
Merges are not stopped, just too slow: after two days, the amount of data parts  has decreased to 200000

I'm facing merge slow issues on Kubernetes+S3 env, and I failed to reproduce this issue on physical machine + S3 env

Could you give me some advice about how to accelerate merges? Since our CPU usage is relatively low, there is no new read/write query.

**Comment by alexey-milovidov** [comment]
Kubernetes is hard to use - if you have trouble with it, I recommend to avoid using Kubernetes.
