### ISSUE TITLE
Can clickhouse-copier trigger a Materialized view

### ISSUE THREAD

**Issue by sivanovhm** [ClickHouse/ClickHouse#38885]
Hello,

I've successfully setup clickhouse-copier as a daemon to copy from a table with S3 table engine to e table with MergeTree (initially the goal was Null but I discovered that is not possible). 

Anyhow, the goal is to evaluate if we can stream data into Clickhouse that way, since there has not been any movement on [Kinesis integration](https://github.com/ClickHouse/ClickHouse/issues/11776), we decided to workaround that. 

The whole process should be similar to:
`S3 table engine -> clickhouse-copier daemon -> MergeTreeTable -> MATERIALIZED VIEW -> MergeTree table with Transformed data`

I have the following problem: 
 * when the data is copied to the MergeTree table, the MATERIALIZED VIEW does **not** get triggered. 

Note: I've tried out the MATERIALIZED VIEW on two other tables and it works, so the problem is not in it.

Is this behavior intended or is my set up wrong?

As mentioned, we are in a testing phase still. Everything is conducted on docker. Below you will find my configurations:

<details><summary>enable clickhouse-keeper</summary>

```XML

<clickhouse>
<keeper_server>
    <tcp_port>9181</tcp_port>
    <server_id>1</server_id>
    <log_storage_path>/var/lib/clickhouse/coordination/log</log_storage_path>
    <snapshot_storage_path>/var/lib/clickhouse/coordination/snapshots</snapshot_storage_path>

    <coordination_settings>
        <operation_timeout_ms>10000</operation_timeout_ms>
        <session_timeout_ms>30000</session_timeout_ms>
        <raft_logs_level>warning</raft_logs_level>
    </coordination_settings>

    <raft_configuration>
        <server>
            <id>1</id>
            <hostname>localhost</hostname>
            <port>9444</port>
        </server>
    </raft_configuration>
</keeper_server>
</clickhouse>
```
</details>

<details><summary>keeper.xml (used in the clickhouse-copier command)</summary>

```XML

<clickhouse>
    <logger>
        <level>trace</level>
        <size>100M</size>
        <count>3</count>
    </logger>

    <zookeeper>
        <node index="1">
            <host>127.0.0.1</host>
            <port>9181</port>
        </node>
    </zookeeper>
</clickhouse>
```
</details>

<details><summary>Task definition (either initially loaded into ZooKeeper or used as an CMD argument to the clickhouse-copier command to load the task in clickhouse-keeper</summary>

```XML

<clickhouse>
<remote_servers>
    <source_cluster>
        <shard>
            <weight>1</weight>
            <replica>
                <host>127.0.0.1</host>
                <port>9000</port>
            </replica>
        </shard>
    </source_cluster>
    <destination_cluster>
        <shard>
            <weight>1</weight>
            <replica>
                <host>127.0.0.1</host>
                <port>9000</port>
            </replica>
        </shard>
    </destination_cluster>
</remote_servers>
<max_workers>1</max_workers>
<tables>
    <table_events>
        <cluster_pull>source_cluster</cluster_pull>
        <database_pull>default</database_pull>
        <table_pull>analytics_source</table_pull>

        <cluster_push>destination_cluster</cluster_push>
        <database_push>default</database_push>
        <table_push>analytics_raw</table_push>
           <engine>
            ENGINE=MergeTree order by tuple()
            </engine>
        <sharding_key>rand()</sharding_key>
    </table_events>
</tables>
</clickhouse>
```
</details>

Command to start the copy process: `clickhouse-copier --config ./keeper.xml --task-path /testtask/1 --task-file=./copier-task.xml`

**Comment by den-crane** [comment]
(mat.views don't not work with copier)
copier uses attach partition instead of insert. 
attach partition does not trigger materialized view because it's impossible.

**Comment by sivanovhm** [comment]
Yes, thank you for yout answer. I also found some info about how the copier process works in [altinity knowledge base](https://kb.altinity.com/altinity-kb-setup-and-maintenance/altinity-kb-data-migration/altinity-kb-clickhouse-copier/altinity-kb-clickhouse-copier-20.4+/).

We have to figure out another workaround to integrate with Kinesis, then.
