### ISSUE TITLE
atomic table replacing problem

### ISSUE THREAD

**Issue by mbtolou** [ClickHouse/ClickHouse#38881]
When granting full permissions on an atomic table using the following

'''

--_tmp_replace_
grant
create,
create table,
drop,
drop table,
select
,
	  insert,
	  delete
	  on db_base_atmc.phzr_tbl_nmbrs to userx
with grant OPTION;

'''

due to the inherint nature of atomic tables, any drop or modification operations on the virtual tables which are based on it is not possible. 
Is there a workaround to this problem or an upcoming bug fix?

**Comment by filimonov** [comment]
> any drop or modification operations on the virtual tables which are based on it is not possible.

What exactly do you mean by that? Some examples?
