### ISSUE TITLE
Performance Degradation from 22.2 to 22.6.1

### ISSUE THREAD

**Issue by melvynator** [ClickHouse/ClickHouse#38903]
After upgrading from 22.2 to 22.6.1 we noticed a performance degradation for some queries:

```
SELECT
    instances.account_name,
    instances.industry,
    sum(count) AS c
FROM data_points AS dtp
INNER JOIN remote('my.instance.com', my.instance_local) AS instances ON dtp.instance_id2 = instances.instance_id
WHERE (definition_id = '123')
GROUP BY
    instances.account_name,
    instances.industry
ORDER BY c ASC
```

On version 22.2 the performance were the following: 
> 10000 rows in set. Elapsed: 2.439 sec. Processed 112.10 million rows, 5.73 GB (45.96 million rows/s., 2.35 GB/s.)

But in version 22.6.1

> 10000 rows in set. Elapsed: 7.138 sec. Processed 112.10 million rows, 5.73 GB (15.70 million rows/s., 802.49 MB/s.)

Another example of performance degradation: 

```
SELECT
toStartOfDay(time) as day,
uniq(instances.account_name) AS c
FROM data_points AS dtp
INNER JOIN remote('my.instance.com',  my.instance_local) AS instances ON dtp.instance_id2 = instances.instance_id
WHERE (definition_id = '123') and count>0
GROUP BY
   day
ORDER BY day ASC
```

On version 22.2 the performance were the following: 
> 372 rows in set. Elapsed: 2.581 sec. Processed 112.10 million rows, 6.17 GB (43.43 million rows/s., 2.39 GB/s.)

But in version 22.6.1:
> 372 rows in set. Elapsed: 6.203 sec. Processed 112.10 million rows, 6.17 GB (18.07 million rows/s., 994.18 MB/s.)

These are the setting that are being used:

```
<async_insert>1</async_insert>
<wait_for_async_insert>0</wait_for_async_insert>
<async_insert_max_data_size>15728640</async_insert_max_data_size>
<async_insert_busy_timeout_ms>2000</async_insert_busy_timeout_ms>
<async_insert_threads>32</async_insert_threads>
<max_threads>16</max_threads>
<distributed_directory_monitor_batch_inserts>1</distributed_directory_monitor_batch_inserts>
<distributed_directory_monitor_sleep_time_ms>1000</distributed_directory_monitor_sleep_time_ms>
<min_bytes_to_use_direct_io>1</min_bytes_to_use_direct_io>
<max_bytes_before_external_group_by>10000000000</max_bytes_before_external_group_by>
<distributed_aggregation_memory_efficient>1</distributed_aggregation_memory_efficient>
```

The queries are ran without cache.

**Comment by UnamedRus** [comment]
Related

https://github.com/ClickHouse/ClickHouse/pull/38052
https://github.com/ClickHouse/ClickHouse/issues/37489

**Comment by alexey-milovidov** [comment]
No info provided.

https://presentations.clickhouse.com/meetup58/building_for_fast/#12
