### ISSUE TITLE
Client: environment variables CLICKHOUSE_{USER,PASSWORD} have precedence over --user and --password

### ISSUE THREAD

**Issue by adriangoransson** [ClickHouse/ClickHouse#38909]
**Describe the unexpected behaviour**
If the environment variables `CLICKHOUSE_USER` and `CLICKHOUSE_PASSWORD` are set, `clickhouse-client` will ignore flags `--user`, `--ask-password`, and `--password`.

I noticed this issue with Kubernetes, where during setup of ClickHouse I had no direct access to the container, and instead relied on `kubectl exec`.

**How to reproduce**
Tested with server/client 22.6.3.

```
$ docker run -d \
  --rm --name clickhouse-server \
  -e CLICKHOUSE_USER=user CLICKHOUSE_PASSWORD=pass \
  clickhouse/clickhouse-server
```

```
$ docker exec -it clickhouse-server clickhouse-client --user doesnotexist --password none
ClickHouse client version 22.3.3.44 (official build).
Connecting to localhost:9000 as user user.
Connected to ClickHouse server version 22.3.3 revision 54455.
```

```
$ docker exec -it clickhouse-server clickhouse-client --user admin --ask-password
ClickHouse client version 22.3.3.44 (official build).
Code: 36. DB::Exception: Specified both --password and --ask-password. Remove one of them. (BAD_ARGUMENTS)
```

**Expected behavior**
The passed command line flags should be prioritized over environment variables.

**Comment by rkozlo** [comment]
The same about clickhouse-client config file. Passing flags do nothing since there is a client config file.
