### ISSUE TITLE
CI/CD ability to run subset of tests only for PR

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#38905]
Sometimes it's hard to run some kind of tests in the local environment, and it may be wanted to run some (usually limited) subset of tests in CI/CD. 

Currently, it is very time-consuming and burns a lot of money - for example, I change the integration test and need to wait for some other tests (which I don't care about) to get feedback about how my test change behaves in CI/CD.

After I finish the debugging of the test, the reviewer can decide either to run all the tests or merge as-is.

P.S. I don't know how to achieve that in practice - may put some markers in the PR comment? And parse it by the CI/CD?

**Comment by pkit** [comment]
Typical solution for that one is:
1. A checkmark inside the PR template: `run_manually` or something
2. A listener which fires on specific comments in PR issue, ex.: `clickhouse-test run <some test name>`

**Comment by pkit** [comment]
Not on top of my head, usually you have no idea how that is implemented anyway as github hooks are opaque.
