### ISSUE TITLE
Enable vectorscan for ARM

### ISSUE THREAD

**Issue by rschu1ze** [ClickHouse/ClickHouse#38906]
**Describe the unexpected behaviour**
VectorScan is cross-platform, yet ClickHouse enables it only for x86

**Additional context**
- #38171 replaced hyperscan by vectorscan which is a cross-platform fork of hyperscan. Due to wrong results on ARM (see the PR), we currently compile vectorscan only for x86. Need to check if a new version resolves the problem or continue investigation.
- Once done, we can remove the non-vectorscan fallback code in file "Functions/MultiMatchAnyImpl.h"

**Comment by rschu1ze** [comment]
Related: #41033

**Comment by danlark1** [comment]
Also, please, update vectorscan, I pushed some perf improvements for Arm there and we ported recent fixes from hyperscan

**Comment by rschu1ze** [comment]
> Also, please, update vectorscan, I pushed some perf improvements for Arm there and we ported recent fixes from hyperscan

@danlark1 ClickHouse references the latest vectorscan `master` branch which was last updated in May 2022, the perf improvements, especially https://github.com/VectorCamp/vectorscan/pull/119/ and https://github.com/VectorCamp/vectorscan/pull/118, currently exist only in branch `develop`. I feel a bit uneasy with switching ClickHouse to `develop` but I'll ask if the friends at VectorCamp can make a new release.

**Comment by rschu1ze** [comment]
@danlark1 Upgrade to vectorscan 5.4.8 with your optimizations: #41270
