### ISSUE TITLE
Wrong data inserted into temporary table

### ISSUE THREAD

**Issue by carlosefr** [ClickHouse/ClickHouse#38926]
When inserting data into a temporary table, the table ends up with the wrong data. The testcase below shows clickhouse inserting data that doesn't exist in an insert statement, while completely missing data that does exist in the same insert statement.

**Does it reproduce on recent release?**

Reproducible as late as 22.1.3.7.

**How to reproduce**

Start clickhouse running in a container:
`docker run --rm -p 127.0.0.1:8123:8123 --name clickhouse-server yandex/clickhouse-server:latest`

Run the testcase script with `clickhouse-cli` (tested with v0.3.8, also tested with other clients):
`clickhouse-cli -h 'http://127.0.0.1:8123' -u default -d default script.sql`

Contents of the testcase script:
```
create temporary table test_tmp (
   id UInt16,
   value Float64
);

insert into test_tmp (id, value)
   values
   (296529, 0.00044394646451164174),
   (230993, 0.00036624266890788163)
;

select id
     , count() as entries
  from test_tmp
 group by id
having entries > 1
 order by entries desc
;

select id
     , value
  from test_tmp
 where id in (34385, 230993, 296529)
 order by id
;
```

The (erroneus) output I'm getting is as follows:

```
34385	2
34385	0.00044394646451164174
34385	0.00036624266890788163
```

ID `34385` **isn't even present** in the insert statement, while the two IDs that are don't show at all (but note that the contents of the `values` column come from the inserted data).

**Expected behavior**

Running the testcase script should output (or something like it):
```
296529	0.00044394646451164174
230993	0.00036624266890788163
```

**Comment by carlosefr** [comment]
That seems to be it, yes. The real case where this comes from is originally an `UInt32` and the type was wrong in the temporary table. I didn't expect the conversion to overflow silently, though.

**Comment by den-crane** [comment]
CH is famous by it silent overflows:

```sql
select toDate('2022-02-31');
┌─toDate('2022-02-31')─┐
│           2022-03-03 │
└──────────────────────┘

select toDate('haha-02-31');
┌─toDate('haha-02-31')─┐
│           1970-01-01 │
└──────────────────────┘
```
