### ISSUE TITLE
After LVM shrink volume,CK can not load LVM data 

### ISSUE THREAD

**Issue by liuze0118** [ClickHouse/ClickHouse#38939]
![lQLPJxZ49DAH5cZSzQX0sNnRbUpp2wuPAsc8s57AbgA_1524_82](https://user-images.githubusercontent.com/49011972/177677106-8d18b910-1dd0-4ada-bee5-92a4c674536d.png)
![lQLPJxZ49GgPJxbNAs_NBKOwznZfqQq1fb8Cxz0N8MBCAA_1187_719](https://user-images.githubusercontent.com/49011972/177677272-a2fcfbc2-399e-4cab-9791-8731852ff705.png)
 
As we see ,the partition data still exists ， but  when i reload CK server , i  can not find the data by sql.

**Comment by filimonov** [comment]
Whar do you mean by 'can not load'? Pleaae provide related log fragments
