### ISSUE TITLE
While executing MergeTreeInOrder. (CANNOT_READ_ALL_DATA)

### ISSUE THREAD

**Issue by duoluodexiaokeke** [ClickHouse/ClickHouse#38940]
SELECT *
FROM mt_local
WHERE dt_ipv4 = 10

Query id: 795224a6-ee30-4b47-b5f7-a0d0c1086cda

↙ Progress: 3.80 billion rows, 30.40 GB (230.55 million rows/s., 1.84 GB/s.) ███████████████████████████▎                         (1.0 CPU, 11.70 GB RAM) 35%
0 rows in set. Elapsed: 16.687 sec. Processed 3.80 billion rows, 30.40 GB (227.76 million rows/s., 1.82 GB/s.)

Received exception from server (version 22.5.1):
Code: 33. DB::Exception: Received from 127.0.0.1:9000. DB::Exception: Cannot read all data. Bytes read: 8. Bytes expected: 16.: While executing MergeTreeInOrder. (CANNOT_READ_ALL_DATA)

SELECT version()

Query id: 0fa20c2c-fde0-4d37-84ca-4f788302482e

┌─version()───┐
│ 22.5.1.2079 │
└─────────────┘

the stack is
0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xb4903fa in /usr/bin/clickhouse
1. DB::ReadBuffer::readStrict(char*, unsigned long) @ 0xb4ef834 in /usr/bin/clickhouse
2. DB::MergeTreeMarksLoader::loadMarksImpl() @ 0x16813267 in /usr/bin/clickhouse
3. DB::MergeTreeMarksLoader::loadMarks() @ 0x16812441 in /usr/bin/clickhouse
4. DB::MergeTreeReaderStream::MergeTreeReaderStream(std::__1::shared_ptr<DB::IDisk>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange> > const&, DB::MergeTreeReaderSettings const&, DB::MarkCache*, DB::UncompressedCache*, unsigned long, DB::MergeTreeIndexGranularityInfo const*, std::__1::function<void (DB::ReadBufferFromFileBase::ProfileInfo)> const&, int, bool) @ 0x1681c6bf in /usr/bin/clickhouse
5. ? @ 0x16820dc3 in /usr/bin/clickhouse
6. DB::ISerialization::enumerateStreams(DB::ISerialization::SubstreamPath&, std::__1::function<void (DB::ISerialization::SubstreamPath const&)> const&, DB::ISerialization::SubstreamData const&) const @ 0x1533cbf1 in /usr/bin/clickhouse
7. DB::ISerialization::enumerateStreams(std::__1::function<void (DB::ISerialization::SubstreamPath const&)> const&, DB::ISerialization::SubstreamPath&) const @ 0x1533cfc4 in /usr/bin/clickhouse
8. DB::MergeTreeReaderWide::addStreams(DB::NameAndTypePair const&, std::__1::function<void (DB::ReadBufferFromFileBase::ProfileInfo)> const&, int) @ 0x1681ec16 in /usr/bin/clickhouse
9. DB::MergeTreeReaderWide::MergeTreeReaderWide(std::__1::shared_ptr<DB::MergeTreeDataPartWide const>, DB::NamesAndTypesList, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::UncompressedCache*, DB::MarkCache*, std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange> >, DB::MergeTreeReaderSettings, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, double, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, double> > >, std::__1::function<void (DB::ReadBufferFromFileBase::ProfileInfo)> const&, int) @ 0x1681e897 in /usr/bin/clickhouse
10. DB::MergeTreeDataPartWide::getReader(DB::NamesAndTypesList const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange> > const&, DB::UncompressedCache*, DB::MarkCache*, DB::MergeTreeReaderSettings const&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, double, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, double> > > const&, std::__1::function<void (DB::ReadBufferFromFileBase::ProfileInfo)> const&) const @ 0x1677363f in /usr/bin/clickhouse

how can slove this problem?

**Comment by den-crane** [comment]
can you share the output of

```
SET check_query_single_value_result = 0;
CHECK TABLE mt_local;
```

**Comment by duoluodexiaokeke** [comment]
> can you share the output of
> 
> ```
> SET check_query_single_value_result = 0;
> CHECK TABLE mt_local;
> ```

execute CHECK TABLE mt_local;
Timeout exceeded while receiving data from server. Waited for 300 seconds, timeout is 300 seconds.
Cancelling query

**Comment by duoluodexiaokeke** [comment]
> ```
> Timeout exceeded while receiving data from server. Waited for 300 seconds, timeout is 300 seconds.
> Cancelling query
> ```
> 
> It does not matter. Wait for the end.

wait 1 hours, not get the result;
the table hive 10599829014 lines and 3.3TB data and 809 avtive part;
column time is the partition by column and order by column.
SELECT time FROM mt_local WHERE dt_ipv4 = 10;  The above error occurred
but select other column is right.
select count(time) is right.

**Comment by duoluodexiaokeke** [comment]
> > ```
> > Timeout exceeded while receiving data from server. Waited for 300 seconds, timeout is 300 seconds.
> > Cancelling query
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It does not matter. Wait for the end.
> 
> wait 1 hours, not get the result; the table hive 10599829014 lines and 3.3TB data and 809 avtive part; column time is the partition by column and order by column. SELECT time FROM mt_local WHERE dt_ipv4 = 10; The above error occurred but select other column is right. select count(time) is right.

CHECK TABLE mt_local;

**Comment by radash123** [comment]
Received exception from server (version 23.4.2):
Code: 32. DB::Exception: Received from localhost:9000. DB::Exception: Attempt to read after eof:
