### ISSUE TITLE
Use a nullable column as partition key, the partition column contains null value can't be selected out

### ISSUE THREAD

**Issue by rickyrick2002** [ClickHouse/ClickHouse#38941]
**Describe what's wrong**

I made a test and found that if I use a nullable column as partition key, then I can’t select  those rows by `select * from table where partition_key_column is null` , even though that column in fact has null values. 

**Does it reproduce on recent release?**

I am running `ClickHouse server version 22.6.1.1985 (official build)` in Docker, pulled from Clickhouse official docker image.

**How to reproduce**

* Which ClickHouse server version to use: `ClickHouse server version 22.6.1.1985 (official build)`
* Create a table in Amazon Redshift, make a column contains `null` value and choose it as the clickhouse partition key.
* unload the redshift table s3. by
```
UNLOAD ('SELECT * FROM my_table')
TO 's3://s3path/20220707_'
ACCESS_KEY_ID 'abc'
SECRET_ACCESS_KEY 'abc'
FORMAT AS PARQUET
MAXFILESIZE 200MB
ALLOWOVERWRITE;
```
* In clickhouse: 
```
create table if not exists db.table_name engine = MergeTree ORDER BY (tuple()) partition by (nullable_column) SETTINGS allow_nullable_key = 1 as select * from s3('https://s3_https_path/20220707_*.parquet', 'abc', 'abc')
```
* Try to select the rows which `nullable_column is null`
```
select * from db.table_name where nullable_column is null
```
returns nothing. If `nullable_column` is not partition key, it will return the rows that `nullable_column is null`.

**Expected behavior**

```
select * from db.table_name where nullable_column is null
```
should return rows that `nullable_column is null`.

**Comment by amosbird** [comment]
Great! Now we have use cases for nullable partitions. Will investigate.

**Comment by rickyrick2002** [comment]
Hi team, why is this tagged as "Bug in the feature that should not be used in production", bug experimental? So using **a nullable partition key** is the **experimental feature**? Do I get it right?
