### ISSUE TITLE
MaterializedMySQL connection to MySQL is breaking down

### ISSUE THREAD

**Issue by bollustrado** [ClickHouse/ClickHouse#38960]
ClickHouse server version 22.1.3 
MySQL Server version: 5.7.38-0ubuntu0.18.04.1

CREATE DATABASE hub ENGINE = MaterializeMySQL('10.132.0.31:3306', 'hub', '***', '***') settings allows_query_when_mysql_lost=true, max_wait_time_when_mysql_unavailable=10000;

After about 2022.07.07 11:00:00 connection is down

`| 460205336 | ***          | clickhouse-1.c.***-api.internal:35966                    | hub  | Sleep            |    3508 |                                                               | NULL`

After clickhouse-server restarted, connection is restoring

```
| 467881532 | ***          | clickhouse-1.c.***-api.internal:59362                    | hub  | Sleep            |       4 |                                                               | NULL                   |
| 467881533 | ***          | clickhouse-1.c.***-api.internal:59372                    | NULL | Binlog Dump GTID |     226 | Sending to client                                             | NULL

```
[ch-logs.zip](https://github.com/ClickHouse/ClickHouse/files/9064271/ch-logs.zip)

**Comment by alexey-milovidov** [comment]
I'm closing all old issues about MaterializedMySQL because the ClickHouse team does not support it.
