### ISSUE TITLE
new users are created when the login case is changed

### ISSUE THREAD

**Issue by AntonArgon** [ClickHouse/ClickHouse#38968]
1) Clickhouse settings are made for user authorization through Active Directory
2) Users can make their logins case insensitive. For example, they can get Azotova, azotova, azoTova. At the same time, authorization passes correctly in Active Directory, since for AD logins it is case-insensitive.
3) When connecting to ClickHouse, three different users are created in the system.users table: Azotova, azotova, azoTova. Accordingly, access rights are invalid for some of them.

Question: Is there some setting that allows ClickHouse to force user logins to upper or lower case?

**Comment by AntonArgon** [comment]
hi, is there any answer to the question?

**Comment by e-mars** [comment]
Hi @AntonArgon ,
I've set up an AD test environment.
Case sensitivity is affected depending on what field you are using to do authentication.
for example, if you are using DNs, "cn=something, ou=something.." will be different than "CN=Something, OU=SomeThing".
Could you provide an example of the `<ldap>` config? (please anonymize).

Are you using UPN (user@domain.com), sAMAccountName (user), Windows Domain\User format or fullname DN (CN=FirstName, LastName...)?

**Comment by e-mars** [comment]
Hi @AntonArgon ,

I tested the issue with the following sample configuration:
```
    <ldap_servers>
         <marsnet_ad>
             <host>marsdc0.marsnet.local</host>
             <port>389</port>
             <bind_dn>MARSNET\{user_name}</bind_dn>
             <user_dn_detection>
                 <base_dn>OU=Users,OU=ClickHouse,DC=marsnet,DC=local</base_dn>
                 <search_filter>(&amp;(objectClass=user)(sAMAccountName={user_name}))</search_filter>
             </user_dn_detection>
                    <enable_tls>no</enable_tls>
         </marsnet_ad>
    </ldap_servers>
    <user_directories>
        <users_xml>
            <path>users.xml</path>
        </users_xml>
        <local_directory>
            <path>/var/lib/clickhouse/access/</path>
    </local_directory>
                <ldap>
          <server>marsnet_ad</server>
          <roles>
             <clickhouse_ad_admins_role />
          </roles>
          <role_mapping>
             <base_dn>OU=ClickHouse,DC=marsnet,dc=local</base_dn>
             <search_filter>(&amp;(objectClass=group)(member={bind_dn}))</search_filter>
             <attribute>CN</attribute>
             <scope>subtree</scope>
          </role_mapping>
    </ldap>
```

and set up the role and permissions like this:
```
clickhouse :) CREATE ROLE clickhouse_ad_admins_role;
clickhouse :) GRANT ALL ON *.* TO clickhouse_ad_admins_role;
```

Windows user config is like this:
![Screen Shot 2022-07-20 at 1 39 28 PM](https://user-images.githubusercontent.com/18219420/180067619-dd6ce226-bbc1-4c42-82d5-c7d12e467de6.png)

And security group definition and membership is like this:
![Screen Shot 2022-07-20 at 1 41 21 PM](https://user-images.githubusercontent.com/18219420/180067859-00460b4b-025f-493d-9f99-cdba9a4401d8.png)

I was able to verify that ClickHouse creates different records if the case differs when logging in.
this:
```
clickhouse-client --user ClickHouseAdmin --password MyPassword123  --port 9440 --secure --host chnode1.marsnet.local 
```
vs.
```
clickhouse-client --user clickhouseadmin --password MyPassword123  --port 9440 --secure --host chnode1.marsnet.local
```

in the users table:
```
clickhouse :) select name, id, auth_type, auth_params from system.users where auth_type = 'ldap';

SELECT
    name,
    id,
    auth_type,
    auth_params
FROM system.users
WHERE auth_type = 'ldap'

Query id: 392620cc-1f23-4b77-941a-e299201381e7

┌─name────────────┬─id───────────────────────────────────┬─auth_type─┬─auth_params─────────────┐
│ clickhouseadmin │ 744dd6f6-2b1e-194f-48f9-7904cb8926a9 │ ldap      │ {"server":"marsnet_ad"} │
│ ClickHouseAdmin │ b54b34f9-39de-af2f-82c0-3210eecd3daa │ ldap      │ {"server":"marsnet_ad"} │
└─────────────────┴──────────────────────────────────────┴───────────┴─────────────────────────┘

```

However, I was not able to replicate a difference in access to ClickHouse.
Although, it creates two user records, either case works with appropriate permissions.

Is this configuration similar to what you have?
Could you send me a sample of yours? (anonymized).

This might need to be turned in as a bug, if access is being denied or at least an enhancement request to avoid duplicates.

Thanks.

**Comment by AntonArgon** [comment]
Hi @e-mars ,
My config:

_<?xml version="1.0"?>
<clickhouse>
	<ldap_servers>
		<ad_server1>
			<host>xxx.xxx.xxx.xxx</host>
			<port>yyy</port>
			<bind_dn>DOMEN\{user_name}</bind_dn>
			<user_dn_detection>
				<base_dn>OU=zzz,DC=kkk</base_dn>
				<scope>subtree</scope>
				<search_filter>(&amp;(objectClass=user)(sAMAccountName={user_name}))</search_filter>
			</user_dn_detection>
			<enable_tls>no</enable_tls>
		</ad_server1>
	</ldap_servers>
	<user_directories>
		<users_xml>
			<path>users.xml</path>
		</users_xml>
		<local_directory>
			<path>/var/lib/clickhouse/access/</path>
		</local_directory>
		<ldap>
			<roles>
				<ClickHouse_ALL_Roles />
			</roles>
			<server>ad_server1</server>
			<role_mapping>
				<base_dn>OU=fff,DC=kkk</base_dn>
				<attribute>CN</attribute>
				<scope>subtree</scope>
				<search_filter>(&amp;(objectClass=group)(member={user_dn}))</search_filter>
			</role_mapping>
		</ldap>
	</user_directories>
</clickhouse>_

**Comment by AntonArgon** [comment]
The sequence of my actions is as follows:

1) a user, role, grants is created for authorization through Active Directory
`CREATE USER IF NOT EXISTS Shirobokov 
IDENTIFIED WITH ldap SERVER 'ad_server1'
HOST ANY
DEFAULT ROLE Shirobokov_Role 
DEFAULT DATABASE atest
SETTINGS PROFILE default;

CREATE ROLE Shirobokov_Role;
GRANT SELECT ON atest.* TO Shirobokov_Role;
GRANT Shirobokov_Role TO Shirobokov;`

query `select * from system.users where name like 'Shi%'` returns result:
![image](https://user-images.githubusercontent.com/108890829/180445870-764921f0-4d07-4f04-9080-7c4a5b61ac79.png)

**Comment by alexey-milovidov** [comment]
@AntonArgon Yes, we don't normalize the user names.
If we want to handle this, how will we know that user names are case-insensitive?
Is it specified by the LDAP standard or different from one implementation to another?

**Comment by AntonArgon** [comment]
@alexey-milovidov ,
Based on experience in LDAP, only passwords and boolean types are case-sensitive, and user names are case-insensitive.
In the standard itself, there is no indication of the case-sensitivity of the name (unfortunately, there is no converse statement either) https://www.rfc-editor.org/rfc/rfc4511

**Comment by alexey-milovidov** [comment]
Interesting how to adapt to it.

We don't have the notion of case-insensitive user names in ClickHouse.
If we try normalizing the user names to lowercase, it will break the existing access control users.
So, the only way is to introduce the proper support for case-insensitive names for user directory providers.

Does not sound like a small change.
