### ISSUE TITLE
OpNum for watch response doesn't exist (Run time inconsistency)

### ISSUE THREAD

**Issue by tavplubix** [ClickHouse/ClickHouse#38962]
https://s3.amazonaws.com/clickhouse-test-reports/0/10dc83b7a9c18228c4a4fc0dcfe6b18d2427462e/stress_test__debug__actions_.html

I found weird exception while investigating why ephemeral nodes were not removed for a long time:
https://pastila.nl/?00ec9776/d8858e442f8453f9b9e31a2f1da3cc8b

**Comment by alesapin** [comment]
cc @antonio2368
