### ISSUE TITLE
What is clickhouse-watchdog?

### ISSUE THREAD

**Issue by Jack012a** [ClickHouse/ClickHouse#38976]
I would like to know what clickhouse-watchdog is and how it works.
However, I didn't find any related documentation online.

Thank you

**Comment by den-crane** [comment]
clickhouse-watchdog starts clickhouse-server as a child process and monitor the process and logs if clickhouse-server is killed by OOM killer or other application.

You can disable watctdog using:

```
cat /etc/default/clickhouse
CLICKHOUSE_WATCHDOG_ENABLE=0
```

**Comment by Jack012a** [comment]
Hello,

ClickHouse client version 22.7.2.15 (official build).

I only see the  following files:
```
/usr/bin/clickhouse
/usr/share/bash-completion/completions/clickhouse
```

But I cannot find `/etc/default/clickhouse`
```
$ ls -l /etc/default/
total 12
-rw-r--r-- 1 root root  279 Mar 10 12:58 grub
-rw-r--r-- 1 root root 1756 Oct 13  2021 nss
-rw-r--r-- 1 root root  119 Aug  6  2019 useradd
```

Question> May you tell me where the setup file is located for this newer version of clickhouse?

Thank you

**Comment by alexey-milovidov** [comment]
This file is not included in the package and you can create it on your own.
