### ISSUE TITLE
distributed tables randomly drops rows

### ISSUE THREAD

**Issue by amrhivestack** [ClickHouse/ClickHouse#38973]
(you don't have to strictly follow this form)
Installation:
```
clickhouse-server --version
ClickHouse server version 22.6.1.1985 (official build).
```

**Describe the unexpected behaviour**
When selecting from a distributed table, i sometimes get 3 records (correct), and sometimes get 1 records, below are sample queries:

```
SELECT count()
FROM plays.confirmed_plays_distributed AS t
LIMIT 501

Query id: 20f78eac-eb8b-4c9f-8d69-dee7d6c68c82

┌─count()─┐
│       3 │
└─────────┘

1 row in set. Elapsed: 0.005 sec.

ip-172-31-28-108.ec2.internal :) SELECT count()
                                        FROM plays.confirmed_plays_distributed t
                                        LIMIT 501
                                 ;

SELECT count()
FROM plays.confirmed_plays_distributed AS t
LIMIT 501

Query id: 3d3c0b3c-6ce7-4f38-9d1e-bc65a8995614

┌─count()─┐
│       3 │
└─────────┘

1 row in set. Elapsed: 0.004 sec.

ip-172-31-28-108.ec2.internal :) SELECT count()
                                        FROM plays.confirmed_plays_distributed t
                                        LIMIT 501
                                 ;

SELECT count()
FROM plays.confirmed_plays_distributed AS t
LIMIT 501

Query id: 6424a17f-a9c7-411f-b45d-5c0d202427d0

┌─count()─┐
│       3 │
└─────────┘

1 row in set. Elapsed: 0.015 sec.

ip-172-31-28-108.ec2.internal :) SELECT count()
                                        FROM plays.confirmed_plays_distributed t
                                        LIMIT 501
                                 ;

SELECT count()
FROM plays.confirmed_plays_distributed AS t
LIMIT 501

Query id: 6d78f1ff-cafe-4ba9-84e6-9968827e7ab8

┌─count()─┐
│       1 │
└─────────┘

1 row in set. Elapsed: 0.008 sec.
```

The setup is made up of 4 nodes, i verified they can talk to each others on the specified port (port 9000), no notable errors in the logs.

**Expected behavior**
getting 3 records

Create table:

```
-- auto-generated definition
create table confirmed_plays_distributed
(
    ....
)
    engine = Distributed('<cluster>', 'plays', 'confirmed_plays', rand());
```

**Comment by amrhivestack** [comment]
server 1:
```
ip-172-31-24-200.ec2.internal,2
ip-172-31-28-108.ec2.internal,1
```

server 2 (not seeing other nodes at all):
```
ip-172-31-28-108.ec2.internal,1
```

server 3: fluctuates between:
```
ip-172-31-24-200.ec2.internal,2
ip-172-31-28-108.ec2.internal,1
```
and 
```
ip-172-31-28-108.ec2.internal,1
```
server 4: fluctuates between:
```
ip-172-31-28-108.ec2.internal,1
```
and
```
ip-172-31-24-200.ec2.internal,2
ip-172-31-28-108.ec2.internal,1
```

**Comment by den-crane** [comment]
Please share result of 

```
SELECT fqdn() h, count()
FROM clusterAllReplicas('<cluster>', plays.confirmed_plays)
group by h
```

**Comment by amrhivestack** [comment]
Identical result on all nodes:

clickhouse01,1
clickhouse04,1
clickhouse02,1
clickhouse03,1

**Comment by den-crane** [comment]
share from all servers

```sql
select shard_num,replica_num, host_name from system.clusters where cluster = '<cluster>';
```

**Comment by den-crane** [comment]
```
1,   1,    clickhouse01
1,   2,   clickhouse02
2,   1,   clickhouse03
3,   1,   clickhouse04
```

but it's incorrect.

Should be

```
1,   1,    clickhouse01
1,   2,   clickhouse02
2,   1,   clickhouse03
2,   2,   clickhouse04
```

provide `remote_servers` config.

**Comment by den-crane** [comment]
>I am getting the expected results running select shard_num,replica_num, host_name from system.clusters where cluster = 'hivestack02';

Check config and this query at all 4 nodes.

Also please share incorrect result for

```
SELECT fqdn() h, count()
FROM plays.confirmed_plays_distributed AS t
group by h
```

**Comment by amrhivestack** [comment]
`SELECT fqdn() h, count()
FROM plays.confirmed_plays_distributed AS t
group by h`

Node1:
clickhouse01,1
clickhouse03,1


Node2:
clickhouse04,1
clickhouse02,1

Node3:
clickhouse02,1
clickhouse03,1


Node4:
clickhouse01,1
clickhouse04,1

**Comment by alexey-milovidov** [comment]
This behavior can happen in case of incorrect configuration. For example, if you specified unrelated servers as replicas.

**Comment by amrhivestack** [comment]
What's the definition of unrelated servers?

**Comment by den-crane** [comment]
> `SELECT fqdn() h, count() FROM plays.confirmed_plays_distributed AS t group by h`
> 
> Node1: clickhouse01,1 clickhouse03,1
> 
> Node2: clickhouse04,1 clickhouse02,1
> 
> Node3: clickhouse02,1 clickhouse03,1
> 
> Node4: clickhouse01,1 clickhouse04,1

but these results are correct. Can reproduce incorrect result using this query?

**Comment by alexey-milovidov** [comment]
No info, abandoned.
