### ISSUE TITLE
Can be resource usage be optimized here ?

### ISSUE THREAD

**Issue by HeenaBansal2009** [ClickHouse/ClickHouse#38984]
If external aggregration is defined by max_bytes_before_external_group_by:

Step(1) is done on initiator node as well as worker node . We push the chunk of memory to RAM until max_bytes_before_external_group_by is reached and then push the data to filesystem.
and step2() is done on initiator node which is actually processing the stream by step(1) mergeBlocks() results. 

At this place  of code : 
https://github.com/ClickHouse/ClickHouse/blob/master/src/Processors/Transforms/AggregatingTransform.cpp#L568-L576

I see that we are pushing those  AggrerateVariants to disk as well which were pushed in RAM before reaching max_bytes_before_external_group_by limit . For easier merging of data in RAM and disk from whole data in disk and hence  flusing these RAM variants to disk .... which make sense.
 
Now , Since , complete partial aggregration data is in disk , is it not good to free max_bytes_before_external_group_by of partial agg data  which was initially put  in RAM can be freed .

**Comment by nickitat** [comment]
yeap, we'll free that memory [here](https://github.com/ClickHouse/ClickHouse/blob/master/src/Interpreters/Aggregator.cpp#L1730) during converting current state in ram to serialized data that will be written to disk

**Comment by HeenaBansal2009** [comment]
@nickitat , I would like to work on this if you don't mind.

**Comment by HeenaBansal2009** [comment]
@nickitat , Thanks  for the response. 
One more strange observation I have seen in the code traced by  trace logs. 

According to the explain pipeline command for query shows  that  MergingAggregatedBucketTransform *4 according to max_threads value = 4.
<img width="435" alt="image" src="https://user-images.githubusercontent.com/86018844/179337940-a451828b-fae2-44e6-b9ca-5f7da3614d5b.png">


However in traces , I see that `MergingAggregatedBucketTransform::transform()` is called 256 times which is NUM_BUCKETS time. Is it expected ???

However, `MergingAggregatedBucketTransform::transform()` should be called 4 times as no of max_threads which internally iterate over no of temp_files spooled to disk for step1 (external aggregration) and  2 iteration for step(2) when no of  shards involved in query processing with intermediate data.

**Comment by nickitat** [comment]
each call to `transform` merges a single bucket, so regardless of the `max_threads` value it should be called 256 times for each aggregation query. `max_threads` controls in this case only how much buckets could be merged in parallel (there will be 4 `MergingAggregatedBucketTransform` instances, each will merge some bucket on its own thread).

the following doesn't change anything, I just want to mention it for your understanding. `MergingAggregatedBucketTransform`-s which will be used for merging external aggr results are not displayed here, 'cause they are added at runtime if aggr happened to offload smth to disk. we don't know in advance would it happen or not.
