### ISSUE TITLE
view performance

### ISSUE THREAD

**Issue by taotaizhu-pw** [ClickHouse/ClickHouse#38992]
we used view （not MATERIALIZED VIEW） to select data from three tables.  The performance is not good, it scaned the whole three tables data.  We cannot use the materialized view, because all the three tables' data would be updated or delete. 

Can we create the view with params? I think it can reduce the data target range.  

Or is there any other solutions for this case?

thanks!

**Comment by taotaizhu-pw** [comment]
By the way,  we used collapsingmergetree engine

**Comment by taotaizhu-pw** [comment]
any reply? thanks

**Comment by filimonov** [comment]
> Can we create the view with params?

Try.

> Or is there any other solutions for this case?

Yes.

P.S. If you want a concrete answers please ask concrete questions. :)
