### ISSUE TITLE
【External dictionary source related】 may be it is better to offer something like  clickhouse local mode

### ISSUE THREAD

**Issue by mo-avatar** [ClickHouse/ClickHouse#38991]
when we use dictionary,  we may specify source like this.
```
SOURCE(CLICKHOUSE(
    host 'example01-01-1'
    port 9000
    user 'default'
    password ''
    db 'default'
    table 'ids'
    where 'id=10'
    secure 1
    query 'SELECT id, value_1, value_2 FROM default.ids'
));
```
after predefined connections provided. we may defined clickhouse source like this:
```
SOURCE(CLICKHOUSE(
    connection_string
    db 'default'
    table 'ids'
    where 'id=10'
    secure 1
    query 'SELECT id, value_1, value_2 FROM default.ids'
));
```

This is better than the original way which we  must type the whole connection parameters.

But when it comes to clickhouse source, especially when we want to use  a  table  as source in the same instance  of the dictionary,  it is not that perfect。

Because the source table and the dictionary are in the same clickhouse instance， it is unnecessary to  offer the  host port password thing,  and the user of the query session is enough for authentication(may be the relation is more like distribute table  and mergetree)

lets see a senario:
if usera  has dicta, and userb has  tableb,  then if usera knows the predefined connection which can connect to table b,  then usera can  
access tableb through dicta.

assume that  there are many users which belong to diffierent team using the same cluster, it is hard to keep the connection string  from leaking to some one which should not know it.

Is it possible to offer something like source (clickhouselocal(db, table)) which means to access  the source in the same instance which use the current user of the query?

**Comment by den-crane** [comment]
But it's already available:

```sql
create table test(a Int64, b String) Engine=MergeTree order by a;
insert into test values (1,'a'), (2,'b');

CREATE DICTIONARY test_dict( `a` Int64,`b` String)
PRIMARY KEY a
SOURCE(CLICKHOUSE(QUERY 'SELECT a,b FROM dw.test'))
LIFETIME(MIN 0 MAX 0) LAYOUT(FLAT())
));

select dictGet('test_dict', 'b', 1);
┌─dictGet('test_dict', 'b', 1)─┐
│ a                            │
└──────────────────────────────┘
```

**Comment by den-crane** [comment]
When a dictionary fetches data from the source it needs a user because we don't know the **userS** who will be execute dictGet.

**Comment by mo-avatar** [comment]
> But it's already available:
> 
> ```sql
> create table test(a Int64, b String) Engine=MergeTree order by a;
> insert into test values (1,'a'), (2,'b');
> 
> CREATE DICTIONARY test_dict( `a` Int64,`b` String)
> PRIMARY KEY a
> SOURCE(CLICKHOUSE(QUERY 'SELECT a,b FROM default.test'))
> LIFETIME(MIN 0 MAX 0) LAYOUT(FLAT())
> ));
> 
> select dictGet('test_dict', 'b', 1);
> ┌─dictGet('test_dict', 'b', 1)─┐
> │ a                            │
> └──────────────────────────────┘
> ```
I am sorry, but I didn't find it work when I enable password authentication in 21.8.3-lts
```
 CREATE DICTIONARY default.test_dict
(
    `a` Int64,
    `b` String
)
PRIMARY KEY a
SOURCE(CLICKHOUSE(QUERY 'SELECT a,b FROM default.test'))
LIFETIME(MIN 0 MAX 0)
LAYOUT(FLAT())

select dictGet('test_dict', 'b', 1);

SELECT dictGet('test_dict', 'b', 1)

Query id: 72ce6f1e-e5f5-497e-bae6-5c9af0fdbbf9


0 rows in set. Elapsed: 0.001 sec.

Received exception from server (version 21.8.3):
Code: 1000. DB::Exception: Received from x.x.x.x:9000. DB::Exception: Not found: dictionary.source.clickhouse.table.
```

and 

```
CREATE DICTIONARY default.test_dict2
(
    `a` Int64,
    `b` String
)
PRIMARY KEY a
SOURCE(CLICKHOUSE(DB 'default' TABLE 'test' QUERY 'SELECT a,b FROM default.test'))
LIFETIME(MIN 0 MAX 0)
LAYOUT(FLAT()) 

 select dictGet('test_dict2', 'b', 1);

SELECT dictGet('test_dict2', 'b', 1)

Query id: c0398842-b8c7-44db-b0a1-5a02dec8e875


0 rows in set. Elapsed: 0.001 sec.

Received exception from server (version 21.8.3):
Code: 516. DB::Exception: Received from x.x.x.x:9000. DB::Exception: default: Authentication failed: password is incorrect or there is no user with such name: While processing dictGet('test_dict2', 'b', 1).

```
It seems that we must specify an  user and password  when  password authentication is enabled.

**Comment by mo-avatar** [comment]
What I want to explain is that ,  in the scenario when the source table  of the dict is  in the very same clickhouse server instance(which is a common practice in production),
Is it better to use the user which is executing the  query on the dict to authenticate if it has the rights on source table automatically instead of some predefined user password combination.
It seems more safe and convenient, cause most of the data scientist  do not need to know  the very user they are using of clickhouse , cause it is a machine to machine interface, they really shouldn't care about it .

**Comment by filimonov** [comment]
User 1 which create a dict should have access to underlying table (otherwise he can use that trick to read the things which he should not access).

So dicts can't be populated by something like a 'system' user. 

Populating dicts by a DB user which uses the dict is not an option also (because they are often loaded in the background) 

So options are
* as we have right now (works but there are issues with password rotation and similar - can be bit better if named collection used) 
* DEFINER for dictt
* introducing special 'service accounts' which can normal users use for those type of things.

**Comment by mo-avatar** [comment]
> User which create a dict should have access to underlying table (otherwise he can use that trick to read the things which he should not access).
> 
> So dicts can't be populated by something like a 'system' user.
> 
> Populating dicts by a DB user which uses the dict is not an option also (because they are often loaded in the background)
> 
> So options are
> 
> * as we have right now (works but there are issues with password rotation and similar - can be bit better if named collection used)
> * DEFINER for dictt
> * introducing special 'service accounts' which can normal users use (if it's allowed for them) for those type of things.

Probably the definer for dict  is an possible way, which means to fill the user with the definer automatically and do not allow to change to anyone else(after all an user is not allow to use other user in this scenario). but it will cause a weird problem that we may not execute the sql which we can get  through  show create table if we persistent the user directly  in metadata sql.

Or may  be  perform authentication on dict and  source table  “in advance” is another option, let the dictionary loading running 
without authentication. the query can be performed or not depends on the privilege combination of both dict and source table，but it seems unrealistic to carry out the feature。

**Comment by den-crane** [comment]
>Received exception from server (version 21.8.3):
>Code: 1000. DB::Exception: Received from x.x.x.x:9000. DB::Exception: Not found: dictionary.source.clickhouse.table.

@mo-avatar QUERY in external dictionaries is available from 21.9

**Comment by mo-avatar** [comment]
> > Received exception from server (version 21.8.3):
> > Code: 1000. DB::Exception: Received from x.x.x.x:9000. DB::Exception: Not found: dictionary.source.clickhouse.table.
> 
> @mo-avatar QUERY in external dictionaries is available from 21.9

I have tried it again in 22.3, it seems not work when we enable password authentication of default user.

**Comment by misuzu** [comment]
Still no way to create a dictionary from a local clickhouse table without passing a password?
I don't want any passwords in my database schema...

**Comment by VincentAntoine** [comment]
Pretty annoying indeed
