### ISSUE TITLE
how to differ two tables

### ISSUE THREAD

**Issue by shaojiankui** [ClickHouse/ClickHouse#39018]
I have two similar data tables, Each table has about 300 million pieces of data. My use of INSERT and Select Join sql,but run out of memory, but I do have limited memory and cannot add hareware.

`DB::Exception: Memory limit (total) exceeded: would use 3.83 GiB (attempt to allocate chunk of 1612185944 bytes), maximum: 3.46 GiB. OvercommitTracker decision: Query was selected to stop by OvercommitTracker..: While executing FillingRightJoinSide. (MEMORY_LIMIT_EXCEEDED) (version 22.6.1.1985 (official build))
, server ClickHouseNode(addr=http:localhost:8123, db=default)@50871353`

such as query delete data:
INSERT  into 2022_07_07_delete select old.* from  2022_07_06 old left  join  2022_07_07  xin on old.account = xin.account where coalesce(xin.account,'') = '';

how to compare their differences and use less memory

**Comment by den-crane** [comment]
use `set join_algorithm='partial_merge'`

or `select where id not in (select id... from another table `

**Comment by alexey-milovidov** [comment]
The generic and efficient option will be something like

```
SELECT * FROM table1 WHERE sipHash64(*) NOT IN (SELECT sipHash64(*) FROM table2)
```

It will require up to 16 * 4 = 64 bytes per table row, so your 300-million table will require up to 19.2 GB of memory.
Looks like your server has only 4 GiB of memory, so it's not enough.

Alternatively, you can use the following way:
```
SELECT * FROM
(
SELECT 1 AS t, * FROM table1
UNION ALL
SELECT 2 AS t, * FROM table2
)
GROUP BY columns...
HAVING min(t) != max(t)
SETTINGS max_bytes_before_external_group_by = '1G'
```
