### ISSUE TITLE
MODIFY TTL seems to merge everything despite `ttl_only_drop_parts`

### ISSUE THREAD

**Issue by larry-cdn77** [ClickHouse/ClickHouse#39015]
Similar to the report in #36389, a MODIFY TTL to shorten the retention time created an enormous mutation of considerable CPU and I/O drain (table has around 70 TBs on disk). According to system.mutations, it's a MATERIALIZE TTL that includes all parts (`parts_to_do` par with system.parts for given table). My simplistic understanding of #27019 is that with `ttl_only_drop_parts` set, ALTER should only scan ttl.txt files and drop whole parts. No re-merging.

I haven't had a chance to triage different scenarios such as a table without an explicit storage policy. The one used below (see 'S') has a hot SSD and cold HDD volumes. Could that have an effect on the TTL materialise? Does replication make a difference? Or the disabled `always_fetch_merged_part` I use? None of these seem used in test of #27019.

In #27019, I noticed `materialize_ttl_recalculate_only`, which does not show up in official documentation. Do I need it set alongside `ttl_only_drop_parts`?

Simplified CREATE statement:

```sql
CREATE TABLE T (
  t DateTime,
  ...
)
ENGINE = ReplicatedMergeTree
PARTITION BY toStartOfInterval(t, something)
ORDER BY t
TTL t + something
SETTINGS ttl_only_drop_parts = 1, storage_policy = 'S', always_fetch_merged_part = 0
```

ClickHouse server version 22.5.1

**Comment by larry-cdn77** [comment]
Chart of aggregated CPU usage illustrates how dramatic this apparent TTL re-merge looked in the case of my 70TB table 😄

![Screenshot 2022-07-09 at 18 17 58](https://user-images.githubusercontent.com/72978202/178114257-7d288318-9d20-44a0-b048-9aa8577d81d7.png)

**Comment by den-crane** [comment]
try to change TTL to match with partition by `TTL toStartOfInterval(t, something) + something`

Also please provide rows from `system.part_log` and clickhouse-server.log related to these TTL merges.

**Comment by larry-cdn77** [comment]
TTL expression changed from `t + toIntervalHour(168)` to `t + toIntervalHour(120)`, ie an integer multiple of the partition size. My actual partitioning expression is `toStartOfInterval(t, toIntervalMinute(5))`. Will an explicit rounding in the TTL expression using `toStartOfInterval` make a difference? I can try the following:

```sql
TTL toStartOfInterval(t, toIntervalMinute(5)) + toIntervalHour(120)
```

In case you wonder, with this apparently fine partitioning I hope to reduce unnecessary merging in this large table — typical use for is to read out in one-minute chunks (by `t`).

Attached is a sample of clickhouse-server.log (lines with the word 'TTL') once it has already gone doing the merges. The moment of ALTER query has unfortunately rotated away in my log directory, but if needed I can recreate it. In clickhouse-server.err.log, which is preserved entirely, I did not see any relevant messages.

Also attached is the output of the below SQL. The time periods cover the beginning and end of the apparent TTL merging. The ALTER query's UUID does is not found in the part log.

```sql
SELECT
  query_id,
  event_type,
  event_time,
  duration_ms,
  part_name,
  partition_id,
  disk_name,
  path_on_disk,
  rows,
  length(merged_from),
  error,
  exception
FROM system.part_log
WHERE
  (event_time BETWEEN '2022-07-08 06:30:00' AND '2022-07-08 06:45:00') OR
  (event_time BETWEEN '2022-07-09 13:30:00' AND '2022-07-09 13:45:00')
ORDER BY event_time ASC
```

[part.log.gz](https://github.com/ClickHouse/ClickHouse/files/9078640/part.log.gz)
[ttl.log.gz](https://github.com/ClickHouse/ClickHouse/files/9078641/ttl.log.gz)

**Comment by larry-cdn77** [comment]
> In #27019, I noticed `materialize_ttl_recalculate_only`, which does not show up in official documentation. Do I need it set alongside `ttl_only_drop_parts`?

With `materialize_ttl_recalculate_only` set on my table a repeated ALTER led to an 'everything' mutation, like before, so it looks like the answer is no

**Comment by larry-cdn77** [comment]
> I haven't tried if an explicit rounding in the TTL expression using toStartOfInterval would make a difference

I have tried a TTL expression like `toStartOfInterval(t, toIntervalMinute(5)) + toIntervalHour(...)` which also produced an 'everything' mutation

**Comment by den-crane** [comment]
There is a setting

```
  --materialize_ttl_after_modify arg                        Apply TTL for old data, after ALTER MODIFY TTL query
```

you can set `materialize_ttl_after_modify=0`

**Comment by alex-zaitsev** [comment]
It should probably be a default setting. There is MATERIALIZE TTL to force if needed.

**Comment by den-crane** [comment]
>partitioning by as little as 5 minutes

Be aware that your ZK database will grow infinitely https://github.com/ClickHouse/ClickHouse/issues/3322 

```sql
with 'db.table' as tbl 
select 'rm '|| path||name from system.zookeeper 
where path = ( select zookeeper_path||'/block_numbers/' from system.replicas where database||'.'||table = tbl )
and name not in (select distinct partition_id from system.parts where database||'.'||table = tbl )　
and ctime < now() - interval 30 day and mtime < now() - interval 30 day  
format TSVRaw;
```

**Comment by larry-cdn77** [comment]
Thank you both for the comments

First, a correction on my part. I said that `materialize_ttl_recalculate_only` created a long mutation but the mutation turned out to be only half an hour or so. That is entirely manageable. I will retest to be sure but at first glance it did look like that's what made the difference. I will additionally go and see what `materialize_ttl_after_modify` does.

The ZooKeeper node count has been an ongoing struggle that regularly ends up with a ZooKeeper clean-up. The query you advised looks very useful indeed.

**Comment by larry-cdn77** [comment]
Did I understand correctly that `materialize_ttl_after_modify` is something I want in order to free up disk space of any parts no longer live under new TTL expression? Just to be clear, I am not trying to prevent the new TTL from materialising. I imagined it can materialise by doing no more then selecting whole parts outside of the retention period and dropping them. No merging, at least provided TTL is expressed in multiples of partition size.

**Comment by larry-cdn77** [comment]
In the meantime I can indeed disable automatic TTL materialise and manually drop partitions when shortening table life (mindful of stray-znode build-up). So I am good for now. Thanks!

**Comment by den-crane** [comment]
`alter table ...MODIFY TTL` does not use ttl_only_drop_parts.
Just use `materialize_ttl_after_modify=0` and drop old parts manually.

**Comment by larry-cdn77** [comment]
Yes, that was the bit I had been missing!

And with `materialize_ttl_after_modify` disabled I don't have to worry about ttl.txt of existing parts?

**Comment by larry-cdn77** [comment]
> you can clean ZK with

Just a note to say that the manual clean-up of stale block entries ZooKeeper worked perfectly for me and removed as much as a third of my znodes. I replaced `rm` with `delete` for use with the zkCli.sh interface. Thanks once again.

**Comment by krokwen-tftc** [comment]
what if i want to increase table TTL.
in this case ALTER TTL also causes a lot of merging.

i tested the behavior with `materialize_ttl_after_modify=0` and it works smooth, but now i'm in doubt about future TTL cleanup - would it still work automatically when my new TTL will be exceeded?
