### ISSUE TITLE
Memory consumption when executing a query with the limit statement

### ISSUE THREAD

**Issue by tishden** [ClickHouse/ClickHouse#39026]
Hi,
I have a table like this:

```
CREATE TABLE mytable on cluster '{cluster_name}' (
`id` Int64,
`version` Int64,
`lastupdated` DateTime
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/mytable', '{replica_v2}')
PARTITION BY toYYYYMM(lastupdated)
ORDER BY (id, version);
```
Rows count is around **3 bln**.
Clickhouse version: **21.12.5.1**

And the following query

`select id, max(version) from mytable group by id limit 10;`

In the **system.query_log** I see that
**query_duration_ms** varies from 31798 to 200761
**read_rows** is 3 033 228 513, **read_bytes** 48 531 656 208 (48 GB)
and **memory_usage** is around **110 GB**, but sometimes it can throw an exception “_Memory limit (total) exceeded: would use 1.33 TiB_”

I have a few questions:
1.	Why memory_usage is so high? I requested just 10  rows with two columns. I was under impression that it’s enough to keep in memory just these 10 rows and it should take just 10 * 2 * 8 = 160 bytes (even if we want to sort the result by max(version) we need only 10 rows in memory). If we put all read data into memory for some reason it shouldn’t take more than 48 GB (3 bln * 8 * 2 = 48). And why is it required 1.33 TiB in some cases?
2.	Why execution time is so long? I see in the execution plan that the limit statement is processed at the end of the query execution (read all data first and only then take 10 rows). Wouldn’t it make sense to execute the limit statement as earlier as possible? It could dramatically reduce execution time and memory consumption.

I would much appreciate if you point me out to some documentation where explained how memory allocation works in clickhouse for query executions.

**Comment by tishden** [comment]
> Since there is no filter clause, to determine the max value, the system has to scan all rows. The limit will only limit the output rows.

ok, but as an end user I just ask to show 10 any random rows with the max value.
Even if I have a query which has more sense:
`select id, max(version) as m from mytable  group by id order by m desc limit 10;`
I asks to show 10 rows with the max versions.
It has the same issue with memory consumption (around 110GB). Does it mean that this query will be limited by the number of rows in my dataset not in result? As I mentioned in the question it's not expected that we should keep the whole dataset in memory for calculation max values for 10 rows.

**Comment by tishden** [comment]
> How many unique ids are in this table?
1.2 bln unique ids

**Comment by genzgd** [comment]
Because of your group by, intermediate max state for each of those ids has to be kept in memory.  That's a lot of state.  Any group by that is going to produce 1.2 billion unique rows is going to consume a great deal of memory.  

You may be able to reduce memory usage by using the `max_bytes_before_external_group_by` setting to write some of the temporary state to disk, but it's not clear that will help in this case.

Since you only want 10 ids anyway, perhaps you could limit the query this way?

```
SELECT id, max(version) as m FROM mytable group by id WHERE id in (SELECT distinct(id) FROM mytable LIMIT 10) GROUP BY id
```

**Comment by tishden** [comment]
>Any group by that is going to produce 1.2 billion unique rows is going to consume a great deal of memory

I would expect 1.2 bln * 2 column * 8 byte = 19.2GB not 110GB, how could it be produced?

>Since you only want 10 ids anyway, perhaps you could limit the query this way?

The original query is a synthetic query which can be used only for development purposes (this is also the case) and your aproach will help, but for more real query like
`select id, max(version) as m from mytable group by id order by m desc limit 10;`
it won't work

**Comment by den-crane** [comment]
```sql
set optimize_aggregation_in_order=1;
```

--optimize_aggregation_in_order arg                                             
     Enable GROUP BY optimization for aggregating data in corresponding order in MergeTree tables.

**Comment by den-crane** [comment]
```sql
CREATE TABLE mytable  (
`id` Int64,
`version` Int64,
`lastupdated` DateTime
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(lastupdated)
ORDER BY (id, version);

insert into mytable select number, 1, now() from numbers(1e9);
insert into mytable select number, 2, now() from numbers(2e8);

set send_logs_level = 'debug';
set optimize_aggregation_in_order=1;
select id, max(version) from mytable group by id limit 10;

Elapsed: 0.133 sec.
Peak memory usage (for query): 117.67 MiB.
```

**Comment by den-crane** [comment]
>and memory_usage is around 110 GB, but sometimes it can throw an exception “Memory limit (total) exceeded: would use 1.33 TiB”

try to disable hash_table size prediction `set collect_hash_table_stats_during_aggregation=0`

**Comment by tishden** [comment]
> ```sql
> set optimize_aggregation_in_order=1;
> ```

thanks, on my dataset
```
set optimize_aggregation_in_order=1;
select id, max(version) from mytable group by id limit 10;
```
is executed in 375 ms and memory usage is 1.2GB what is significantly better then without this flag.

Unfortenatelly for the 
`select id, max(version) as m from mytable group by id order by m desc limit 10;`
execution time is 563262 (95305 without the flag) and memory usage is 1.36GB
I don't know what is better to sacrifice 110GB of RAM for a single query or wait 10 mins of execution)

**Comment by tishden** [comment]
> try to disable hash_table size prediction set collect_hash_table_stats_during_aggregation=0

looks like this setting is available on the newest CH versions, not in  21.12.5.1. Will try it after migration to the new version, thanks

**Comment by den-crane** [comment]
>group by id order by m desc limit 10

What is the goal / meaning of such query?

```
CREATE TABLE mytable  (
              `id` Int64,
              `version` Int64,
              `lastupdated` DateTime
              )
              ENGINE = MergeTree
              PARTITION BY toYYYYMM(lastupdated)
              ORDER BY (version, id);

insert into mytable select number, 1, now() from numbers(1e8);
insert into mytable select number, 2, now() from numbers(1e8) where rand()%100=0;
insert into mytable select number, 23, now() from numbers(1e8) where rand()%1000=0;

select id, max(version) as m from mytable group by id order by m desc limit 10;
┌───────id─┬──m─┐
│   758613 │ 23 │
│ 29861755 │ 23 │
│ 37109024 │ 23 │
│ 88705425 │ 23 │
│ 31604169 │ 23 │
│ 65027684 │ 23 │
│ 88365393 │ 23 │
│ 92103570 │ 23 │
│ 14226528 │ 23 │
│ 74526271 │ 23 │
└──────────┴────┘

10 rows in set. Elapsed: 6.555 sec. Processed 101.10 million rows, 1.62 GB (15.42 million rows/s., 246.77 MB/s.)

select * from (select id, version from mytable order by version desc,id limit 1 by id)  limit 10;
┌───id─┬─version─┐
│  431 │      23 │
│ 2660 │      23 │
│ 3211 │      23 │
│ 3627 │      23 │
│ 3865 │      23 │
│ 4245 │      23 │
│ 4668 │      23 │
│ 4846 │      23 │
│ 5121 │      23 │
│ 5450 │      23 │
└──────┴─────────┘

10 rows in set. Elapsed: 0.025 sec. Processed 403.76 thousand rows, 6.46 MB (15.87 million rows/s., 253.89 MB/s.)
```

**Comment by tishden** [comment]
> What is the goal / meaning of such query?

`select id, max(version) as m from mytable group by id order by m desc limit 10;`

let's replace id with employee_id and version with salary_per_month for example 
`select employee_id, max(salary_per_month) as m from mytable group by employee_id order by m desc limit 10;`

and the meaning will be: show me top 10 employees who had hightest salaries (max can be replaces with sum or any other aggregation function).

Looks like **limit 1 by id** solves the performance problem, the query is executed in 7 sec instead of 95 sec, unfortunatelly it still uses 45GB of memory, at least it twice lower the with group by.

Thanks!

Is there any chance that we will see improvments of memory utilizations with the limit clause? It's a common case that we need just a subset as a result and we have good data structures to keep in memory only limited number of rows for executing a query with **order by** or **group by**?

**Comment by alexey-milovidov** [comment]
@e-mars @genzgd both of your answers are incorrect.

```
select id, max(version) from mytable group by id limit 10;
```

This query does not have to calculate all the groups, as it can take any 10 results.

It can be demonstrated by enabling the following settings:
```
SET max_rows_to_group_by = 10, group_by_overflow_mode = 'any';
```

There is no reason why we cannot apply this optimization automatically,
and this issue represents a valid request for improvement.

**Comment by genzgd** [comment]
I wasn't aware of max_rows_to_group_by plus group_by_overflow_mode.  Do you mean applying those setting automatically based on the LIMIT clause?

**Comment by alexey-milovidov** [comment]
@genzgd I've thought more about this optimization, looks like it will not fork if there is more than one thread.
Nevertheless, slightly different optimization is possible.

**Comment by tishden** [comment]
@den-crane, I've looked deeply into **limit by**.
It has very good performance if there is result in the output, unfortunately if there is no result
`select * from (select id, version from mytable order by version desc,id limit 1 by id) where id = <some not existed id>  limit 10;` 
after 20 mins it fails with
`Code: 241. DB::Exception: Memory limit (total) exceeded: would use 1.34 TiB ... (version 21.12.5.1)`
on my dataset

**Comment by den-crane** [comment]
@tishden you've missed the point. I was answering on a specific question. 

My answer is `ORDER BY (version, id)` + `version desc,id limit 1 by id)  limit 10`

```sql
CREATE TABLE mytable  (
....
              ORDER BY (version, id);   -------<<<<<<<<<----
```

My proposal is steamable and does use memory.

**Comment by tishden** [comment]
and what the difference with
```
ORDER BY (id, version) + id, version desc limit 1 by id) limit 10
```
?

**Comment by tishden** [comment]
@den-crane ok, 
`select * from (select id, version from mytable order by version desc,id limit 1 by id)  limit 10;`
works fine in your example, but try to execute
`select * from (select id, version from mytable order by version desc,id limit 1 by id) where id = 12345678 limit 10;`
memory_usage = 7.5 GB - size of the whole uncompressed data set is 1.9 GB
query_duration_ms = 93 619
read_rows = 184 362 920 (despite count is 100 009 896 rows)

**Comment by den-crane** [comment]
@tishden you cannot get all / arbitrary queries to work fast & with limited memory. 
You need to find the most frequents, most important queries and optimize table for them.
Also there are other tools -- skip indexes, projections.

**Comment by tishden** [comment]
I just wanted to highlight an issue that simple constructions like **group by** and **limit by** doesn't work optimally on medium size dataset.
And still haven't got an answer on the original question why memory_usage and execution time are so huge, what is also demonstrated with my last example. It was needed for designing more complex quires.

So, let's just close the ticket. Thanks for the answers.

**Comment by den-crane** [comment]
`group by` by 100 millions keys is very hard task, actually CH does it faster and using less memory than other databases.
