### ISSUE TITLE
Mac OS: Added log_queries=1 but system.trace_log does not exist

### ISSUE THREAD

**Issue by dheeraj-326** [ClickHouse/ClickHouse#39021]
I am on a ARM64 M1 Mac and I have build Clickhouse fro sources as seen here https://clickhouse.com/docs/en/development/build-osx.

system.trace_log table is not getting created despite me having done the following:

1. Set log_queries to 1 (both in client session and config)
2. Set query_profiler_real_time_period_ns to 10 (both session and config)
3. Set query_profiler_cpu_time_period_ns to 10 (both session and config)

I know that the above is not the recommended build steps for M1 Mac but I got no build errors and the server is working fine. I imported a sample dataset and everything else seems to be working fine except this one.

**Comment by dheeraj-326** [comment]
Hi @alexey-milovidov , it will be helpful if you can give me some pointers. I intend to contribute to the project if I get to a solution which is a code change.

**Comment by dheeraj-326** [comment]
Hi @alexey-milovidov, can you please point me to the place in code where system.trace_log gets created when trace_log section is active on the config file?

**Comment by alexey-milovidov** [comment]
@dheeraj-326 

Server.cpp:

```
#if USE_UNWIND && !WITH_COVERAGE
    /// Profilers cannot work reliably with any other libunwind or without PHDR cache.
    if (hasPHDRCache())
```

phdr_cache.cpp:
```
#if defined(OS_LINUX) && !defined(THREAD_SANITIZER) && !defined(USE_MUSL)
    #define USE_PHDR_CACHE 1
#endif
```

It means the profiler is only enabled on Linux.
Solving this task can be slightly hard; it requires systems programming knowledge.

**Comment by dheeraj-326** [comment]
> @dheeraj-326
> 
> Server.cpp:
> 
> ```
> #if USE_UNWIND && !WITH_COVERAGE
>     /// Profilers cannot work reliably with any other libunwind or without PHDR cache.
>     if (hasPHDRCache())
> ```
> 
> phdr_cache.cpp:
> 
> ```
> #if defined(OS_LINUX) && !defined(THREAD_SANITIZER) && !defined(USE_MUSL)
>     #define USE_PHDR_CACHE 1
> #endif
> ```
> 
> It means the profiler is only enabled on Linux. Solving this task can be slightly hard; it requires systems programming knowledge.

Thank you for the info @alexey-milovidov
