### ISSUE TITLE
Join execution performance

### ISSUE THREAD

**Issue by tishden** [ClickHouse/ClickHouse#39029]
Hi,
I have two tables with the same structure

```
CREATE TABLE mytable_1/2 on cluster '{cluster_name}' (
`id` Int64,
`version` Int64,
`lastupdated` DateTime
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/mytable_1/2', '{replica_v2}')
PARTITION BY toYYYYMM(lastupdated)
ORDER BY (id, version);
```

The first query
`select id, version from mytable_1 where lastupdated >= '2022-04-01' and lastupdated < '2022-05-01' limit 1000;`
is executed in 48 ms (read_rows 1853009)

The second query
`select id, version from mytable_2 where lastupdated >= '2022-04-01' and lastupdated < '2022-05-01' limit 1000;`
is executed in 36 ms (read_rows 1914011)

The third query

```
select id, version from mytable_1 a inner join (select id, version, lastupdated
                     from mytable_2
                     where lastupdated >= '2022-04-01' and lastupdated < '2022-05-01') b
                    on  a.id = b.id and a.version = b.version
where lastupdated >= '2022-04-01' and lastupdated < '2022-05-01' limit 1000;
```
is executed in 13541 ms, read rows 61819659, memory_usage 5.7 GB

1. Why the query with the inner join is executed significantly slower even if two tables have the same structure and sorted by the same key? The expectation is that the execution shouldn’t take longer than a single query execution multiplied by 3 (1. Read the data from the mytable_1 2. Read the data from the mytable_2. 3. Compare them row by row).
2. Why the read rows is 61819659 not 1853009 + 1914011 =  3 767 020

Would be much appreciated for the explanation.

**Comment by vdimir** [comment]
Right now, we don't use sorting info in joins, unfortunately. And all data for the right table is loaded into the memory, and then we build the hash table with this data. It's pretty time-consuming. You can try `join_algorithm = 'parallel_hash'` to speed up the process of creating the hash table

> Why the read rows is 61819659 not 1853009 + 1914011 = 3 767 020

It's weird, need check, thanks

**Comment by tishden** [comment]
> Right now, we don't use sorting info in joins, unfortunately

Is there any chance we will see such feature in the future?) Looks like it can speed up some queries significantly.

> join_algorithm = 'parallel_hash' 

Unfortunately it's a new feature which is not supported on our version 21.12.5.1.

Thanks for the answers.

**Comment by vdimir** [comment]
> Is there any chance we will see such feature in the future?) Looks like it can speed up some queries significantly.

Most probably it would be supported by `full_sorting_merge` algorithm, related to https://github.com/ClickHouse/ClickHouse/pull/38719

**Comment by fzyzcjy** [comment]
@vdimir Hi, I wonder whether this has changed:

> And all data for the right table is loaded into the memory, and then we build the hash table with this data

Thanks!

**Comment by vdimir** [comment]
@fzyzcjy now full_sorting_merge supports primary key in some use-cases.

Two important notices:
- `max_rows_in_set_to_optimize_join` should be disabled (it's enabled by default, we are going to disable it automatically when in order can be applied)
- Order of keys on `JOIN ... ON` (or `USING`) section should match the ones specified in `CREATE TABLE ... ORDER BY`

These two pitfalls should be resolved in https://github.com/ClickHouse/ClickHouse/pull/45909


Example:

```sql
CREATE TABLE t1 (x Int32, y Int32) Engine = MergeTree ORDER BY (x, y);
INSERT INTO t1 SELECT number % 17, number % 199 FROM numbers(1_000_000);

CREATE TABLE t2 (a Int32, b Int32) Engine = MergeTree ORDER BY (a, b);
INSERT INTO t2 SELECT number % 13, number % 97 FROM numbers(1_000_000);

EXPLAIN PLAN sorting = 1, actions =1
SELECT count() FROM t1 JOIN t2 ON t1.x = t2.a AND t1.y = t2.b
SETTINGS join_algorithm = 'full_sorting_merge', max_rows_in_set_to_optimize_join = 0;
```

```
Expression ((Projection + Before ORDER BY))
Sorting (None)
Actions: INPUT :: 0 -> count() UInt64 : 0
Positions: 0
  Aggregating
  Sorting (None)
  Keys: 
  Aggregates:
      count()
        Function: count() → UInt64
        Arguments: none
  Skip merging: 0
    Expression (Before GROUP BY)
    Sorting (None)
    Positions:
      Join (JOIN YShaped)
      Sorting (None)
        Sorting (Sort Left before JOIN)
        Sorting (Global): x ASC, y ASC
        Prefix sort description: x ASC, y ASC
        Result sort description: x ASC, y ASC
          Expression (Before JOIN)
          Sorting (Stream): x ASC, y ASC
          Actions: INPUT :: 0 -> x Int32 : 0
                   INPUT :: 1 -> y Int32 : 1
          Positions: 0 1
            ReadFromMergeTree (default.t1)
            Sorting (Stream): x ASC, y ASC
            ReadType: InOrder
            Parts: 1
            Granules: 122
        Sorting (Sort Right before JOIN)
        Sorting (Global): a ASC, b ASC
        Prefix sort description: a ASC, b ASC
        Result sort description: a ASC, b ASC
          Expression ((Joined actions + (Rename joined columns + (Projection + Before ORDER BY))))
          Sorting (Stream): a ASC, b ASC
          Actions: INPUT :: 0 -> a Int32 : 0
                   INPUT :: 1 -> b Int32 : 1
          Positions: 0 1
            ReadFromMergeTree (default.t2)
            Sorting (Stream): a ASC, b ASC
            ReadType: InOrder
            Parts: 1
            Granules: 122
```


> `ReadType: InOrder`
