### ISSUE TITLE
group by section's issue for 'on cluster' request with materialized view

### ISSUE THREAD

**Issue by Blackmorse** [ClickHouse/ClickHouse#39023]
Clickhouse version: 22.1.3.7, 22.6.3.35 (do not reproduce for 21.8 and lower)

I have a test cluster of two replicas and two tables
```
CREATE TABLE IF NOT EXISTS test.requests_log on cluster replicated (
    upstream_id UInt64,
    datetime DateTime64(9)
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/test/request_log', '{replica}')
ORDER BY datetime
;

CREATE TABLE IF NOT EXISTS test.requests_5min on cluster replicated  (
    upstream_id UInt64,
    datetime DateTime64(9),
    cnt UInt64
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/test/requests_5min', '{replica}')
ORDER BY (upstream_id, datetime);
```

When I'm trying to create materialized view ON CLUSTER
```
CREATE MATERIALIZED VIEW IF NOT EXISTS test.requests_handler ON CLUSTER replicated TO test.requests_5min
AS SELECT
    upstream_id,
    datetime,
    count() as cnt
FROM test.requests_log
GROUP BY (upstream_id, datetime);
```
I have an error:
```
Received exception from server (version 22.6.3):
Code: 215. DB::Exception: Received from localhost:9000. DB::Exception: There was an error on [clickhouse-replica:9000]: Code: 215. DB::Exception: Column `upstream_id` is not under aggregate function and not in GROUP BY: While processing upstream_id, datetime, count() AS cnt. (NOT_AN_AGGREGATE) (version 22.6.3.35 (official build)). (NOT_AN_AGGREGATE)
```
If I will create this table manually on each of replicas (without `ON CLUSTER` section), It works fine. Problem arises only when executing on cluster.

Also, when brackets from GROUP BY section are removed, this also works.

Seems like an inconsistent behaviour. 
In case brackets are not allowed at GROUP BY section (or clickhouse treats it like GROUP BY tuple(...)) It should now work withour ON CLUSTER section.
If it is valid , then ON CLUSTER should work.

**Comment by den-crane** [comment]
It's because `GROUP BY (upstream_id, datetime);` should be `GROUP BY upstream_id, datetime;`

duplicate: https://github.com/ClickHouse/ClickHouse/issues/36016
