### ISSUE TITLE
Is there a way to skip errors from distributed sub queries ?

### ISSUE THREAD

**Issue by jorisgio** [ClickHouse/ClickHouse#39038]
If you have say 200 shards with replica and execute a lot of distributed queries via distributed engines, if one shard misbehave and somehow this escalates to replica, everything is down. Even if you are happy to get results from 199 shards until things resolve.
There are a lot of tools to mitigate downtimes, hedged connections, skip_unvavailbe_shards etc. But as far as i understand there are two assumptions : 
1) problem will not escalate to replica
2) if the instance is bad, then you cannot connect. 
But this is not always true (overload, cannot schedule a task, or corrupted data,  or one cpu becoming throttled making things slower and locking up the server...). In those cases, the shard accept connections but will timeout/fail. Since errors handling in load balancing is only based on connections, requests will still being pushed, and in bad situation replica can also collapse. 
I don't find a way to have distributed subqueries returning whatever data it has gathered from everything that works and ignoring one shard, is there something for that ?
Thanks !

**Comment by genzgd** [comment]
There is not currently such a feature.  At the moment skipping bad data is limited to the `skip_unavailable_shards` setting.
