### ISSUE TITLE
Calculate expression with Window function and another column

### ISSUE THREAD

**Issue by royxact** [ClickHouse/ClickHouse#39031]
The issue is being able to use a Window function with another column, for example for calculate pct of max:

select amount / (max(amount) over ()) as pct
from 
(select 12 as amount) as mytable

That works great in Postgres.
But in clickhouse it fails. I have to do this:

select amount / max_amount as pct
from 
(select amount, (max(amount) over ()) as max_amount
from
(select 12 as amount) as mytable
) as subselect

Would be great to be able to use Window functions more naturally (and ANSI compatible).

**Comment by den-crane** [comment]
Already implemented.

```sql
SELECT
    g,
    sum(number) AS sm,
    max(sm) OVER () AS mx,
    max(sm) OVER () / sm AS res
FROM
(
    SELECT
        number % 5 AS g,
        number
    FROM numbers(10)
)
GROUP BY g

Query id: 51af94e4-b46c-474f-8063-4fddb0c03838

┌─g─┬─sm─┬─mx─┬────────────────res─┐
│ 0 │  5 │ 13 │                2.6 │
│ 1 │  7 │ 13 │ 1.8571428571428572 │
│ 2 │  9 │ 13 │ 1.4444444444444444 │
│ 3 │ 11 │ 13 │ 1.1818181818181819 │
│ 4 │ 13 │ 13 │                  1 │
└───┴────┴────┴────────────────────┘
```

Will be available from 20 July. CH version 22.7.
