### ISSUE TITLE
Current version of zstd seems to be broken.

### ISSUE THREAD

**Issue by yakov-olkhovskiy** [ClickHouse/ClickHouse#39052]
**Describe what's wrong**
I'm trying to use self-extracting-executable utility, and while compression goes fine, decompression fails with core dump in ZSTD_decompressDCtx function call.
Reverting zstd to the state of commit of this merge:
https://github.com/ClickHouse/ClickHouse/commit/e13dc23d344454ecda401df4b23b696a691421fe
fixes issue.

**Does it reproduce on recent release?**
Not sure, didn't try yet.

**How to reproduce**
Build `compressor`, use utils/self-extracting-executable/compressor on any file, then run resulting self-extracting executable - unpacked file will contain zeroes. There will no core dump message, since decompression happens in forked process and core dump here is not caught by parent process (needed correction also)

**Expected behavior**
Self-extracting executable should unpack correctly.

**Comment by alexey-milovidov** [comment]
@yakov-olkhovskiy The code of self-extracting-executable is much more suspicious than zstd.
If it crashes, show the stack trace, and the sanitizer output.

**Comment by alexey-milovidov** [comment]
The label "potential bug" is only for "Wrong behavior (visible to users) in the official ClickHouse release."

**Comment by yakov-olkhovskiy** [comment]
The bug actually is in our decompressor utility - function ZSTD_decompressDCtx became intolerant to buffer output size bigger than required (third parameter) since commit https://github.com/facebook/zstd/commit/6a7ede3d , and tends to core dump with signal 11.
