### ISSUE TITLE
Ingestion Throughput between non-replicated cluster and replicated cluster

### ISSUE THREAD

**Issue by xiaobingxia** [ClickHouse/ClickHouse#39053]
Hello I'm using Clickhouse version 22.6.2.12
I have a question about the data ingestion throughput of Clickhouse cluster.

I have 2 Clickhouse clusters:

- r5.24x large * 2, 1 shard, 2 replicas. 
- r5.24x large, 1 shard, 1 replica.

When I ingest data into the first replicated cluster's one node's replicated merge tree engine table (only one node), the throughput I got is 32MB per second per node.
When I ingest data into the non-replicated cluster's merge tree engine table, the throughput I got is 120MB per second per node.

Replication is a very important feature for me, but I also concerns about the ingestion throughput of replication cluster, since I have a a lot of data to ingest every day. 

Right now I'm thinking creating two independent Clickhouse non-replicated cluster, when I ingest data, I ingest data to each of them. If one cluster is going down, I can route query to the other. In other words, I'm doing replication myself.

I believe there is better approach. Any suggestion is appreciated.

**Comment by alexey-milovidov** [comment]
Insertion into a replicated table can be slower due to the latency needed for write confirmation. It depends on the network latency between nodes, and between Keeper.

You can achieve higher throughput by simply running more than one INSERT in parallel.

> Right now I'm thinking creating two independent Clickhouse non-replicated cluster, when I ingest data, I ingest data to each of them. If one cluster is going down, I can route query to the other. In other words, I'm doing replication myself.

This approach is not a replacement for replication, because it will not give you an automatic replica recovery after failover and does not guarantee consistency.

**Comment by den-crane** [comment]
>I got is 32MB per second per node

>I got is 120MB per second per node

Such big difference probably because you insert by a small number or rows or partitioning is too granular. Make bigger inserts.

**Comment by xiaobingxia** [comment]
@alexey-milovidov @den-crane thanks for replying. Here's more information:
I have a comprehensive ingestion service, which can provide parallel ingestion. Right now I'm using 12 sinks threads doing sink at the same time. Each sink is roughly sending 50MB (one big insert http request) data once per 6 seconds. If I put > 12 sinks doing ingestion, it would complain "too many parts" error. So I assume 32MB per second per node with 12 sinks is the maximum throughput I can get. 

Also I'm using toYYYYMM(createdAt) as the partition key. I'm doing the ingestion of 9 years data, which is 108 partitions. So partitioning is NOT too granular.

Here's what I did:
I disabled the insert_quorom (yes, I used insert_quorom to do the ingestion, which is a concern for throughput), and then try again, I got 43MB per second per node throughput, which is a little bit better than before. 

I also feel another potential root cause is:
I ingest data randomly, which means: for every batch of data (50MB size), it contains 108 partitions. And the table has 130 columns. If my understanding is correct, for each batch of data, it will create 108 * 130 = 14040 parts?
That's why it comes to the upper limit of "Too many parts complain" so fast once I increased the number of parallel sinks.

I guess, I need to lower the number of partitions and number of columns, so I could enable a larger number of parallel sinks. So I could have higher throughput.

let me know if this makes sense. Thank you!

**Comment by xiaobingxia** [comment]
Oh, I just noticed sth new about Buffer Table: https://clickhouse.com/docs/en/engines/table-engines/special/buffer/
I will try that out as well.

**Comment by den-crane** [comment]
>I ingest data randomly, which means: for every batch of data (50MB size), it contains 108 partitions. 

This is main reason of the issue. You need to presort data in ETL and insert only one partition per insert. 
And make inserts bigger -- 500MB.

You can disable checks `"Too many parts "` and `Limit maximum number of partitions in single INSERTed block` if you're doing initial load.

**Comment by xiaobingxia** [comment]
Yes, this is initial load, that's why it has 108 partitions. When doing incremental data loading every day, it would have only 1 partition. I believe that could definitely help.

Regarding 500MB batch size, I tried to do 150MB size batch before. And it just complains exception (Too Many Parts). 
So I believe lower # of partitions could also help.

Regarding disable checks "Too many parts" and "Max Partitions per insert blocks", I guess it will still hit the upper limit of file system for example "max number of open files" etc if there are too many parts?

**Comment by xiaobingxia** [comment]
But with exactly same setup, just with different table type (MergeTree vs ReplicatedMergeTree). The ingestion throughput indeed differs a lot. Maybe there is some potential to improve ingestion throughput about Replicated Tree Engine in the future.

**Comment by den-crane** [comment]
>different table type (MergeTree vs ReplicatedMergeTree)

You don't understand. Zookeeper communication overhead is huge with such inserts. Basically CH waits for Zookeeper all time, because Zookeeper need to sync all transactions to disks.

**Comment by den-crane** [comment]
BTW, you can load data into MergeTree and then convert it to ReplicatedMT.
https://kb.altinity.com/altinity-kb-setup-and-maintenance/altinity-kb-converting-mergetree-to-replicated/

**Comment by xiaobingxia** [comment]
Yeah I understand that data ingestion needs the coordination of Zookeeper, but don't know details how much cost would that be. Thanks for your explanation, that makes a lot of sense. 
Will definitely try converting merge tree to replicated MT, thank you a lot!
