### ISSUE TITLE
Is it possible to change sharding key of a Distributed table

### ISSUE THREAD

**Issue by jacoffee** [ClickHouse/ClickHouse#39068]
Currently, I have a history(almost 2yrs) distributed table with rand sharding key.  However,  recently I come across lots of business scenarios where I have to do distribute join on business key, such as userid(**which is evenly distributed by nature**). So I want to change the sharing key to userid.
1. it is possible at the moment
2. if not, is there any possible way i can make the minimal change to get it done

**Comment by den-crane** [comment]
You can drop Distributed table and create it back with another sharding key.
Existing (history) data stays unchanged (sharded by rand). If you need to change it, you need to re-insert it.

**Comment by jacoffee** [comment]
Thanks, I got it. I will try with your suggestion.
