### ISSUE TITLE
Is there any tool to manage the clickhouse keeper?

### ISSUE THREAD

**Issue by taotaizhu-pw** [ClickHouse/ClickHouse#39082]
Is there any tool to manage the clickhoue keeper? How to run it? I have not found from the documents

Thanks!

**Comment by melvynator** [comment]
What type of management operation you want to do? What is the equivalent from Zookeeper that you are missing with ClickHouse Keeper? We have a guide to help you migrate to it: https://clickhouse.com/docs/en/guides/sre/clickhouse-keeper

**Comment by den-crane** [comment]
Probably it has sense to add systemd/initV keeper services.

by analogue with `cat /lib/systemd/system/clickhouse-server.service`

**Comment by filimonov** [comment]
Related https://github.com/ClickHouse/ClickHouse/issues/37780#

**Comment by alexey-milovidov** [comment]
```
sudo -u clickhouse clickhouse-keeper --config-file ... --daemon
```
