### ISSUE TITLE
无法读写kerberos认证的hdfs文件数据

### ISSUE THREAD

**Issue by huangce** [ClickHouse/ClickHouse#39088]
**CDH版本：         CDH6.3.2 (Hadoop3.0.0)
Clickhouse版本：22.6.2.12-amd64（使用Tgz安装）**

**问题：**
Clickhouse读写存储在Hdfs文件系统上的Hive表，Kerberos认证显示已通过，但是无法读写hive表。

1.如果Hive表没有数据的话，在Clickhouse上可以正常执行查询(select *  from test01)，显示查询为空;  如果Hive表内有数据的话，客户端上一直转圈也不报错，但无法读取数据。
2.不管Hive表内有无数据，都无法写入数据。但是在Clickhouse上执行Insert 的时候会自动在Hdfs上创建对应的空白小文件。

**hive建表语句：**
 CREATE TABLE test01(                           
   `test1` varchar(100),                            
   `test2` varchar(100))                            
 ROW FORMAT SERDE                                   
   'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'  
 WITH SERDEPROPERTIES (                             
   'field.delim'='\t',                               
   'serialization.format'=',')  ；

**Clickhouse建表语句：**
CREATE TABLE  test01 (test1 String,test2 String ) 
ENGINE=HDFS('hdfs://nameservice1/user/hive/warehouse/test01/*', 'TSV');

**config.xml配置：**
<hdfs>
    <hadoop_security_authentication>kerberos</hadoop_security_authentication>
    <hadoop_kerberos_keytab>xx.keytab</hadoop_kerberos_keytab>
    <hadoop_kerberos_principal>xx@xx.COM</hadoop_kerberos_principal>
    <libhdfs3_conf>/xx/hdfs-site.xml</libhdfs3_conf>
</hdfs>

<hdfs_default>
    <hadoop_kerberos_principal>xx@xx.COM</hadoop_kerberos_principal>
</hdfs_default>

**Comment by vegastar002** [comment]
本来就不支持读取kerberos认证的表

**Comment by alexey-milovidov** [comment]
We don't support HDFS.
