### ISSUE TITLE
【multi-disk auto-recovery related】After disk  is set to broken, the query will still return an exception. is it intentional?

### ISSUE THREAD

**Issue by mo-avatar** [ClickHouse/ClickHouse#39083]
Hi， Dr Zheng and anyone who want's to give an discussion to this question.
  
We are going to upgrade our clickhouse to 22.3 lts now ，and we find the great feature multi disk auto recovery.

After some manual testing. we find that the query will still return exception about reading error like filesystem_error.

After reading the code , we find  that after disk  broken status be set.  reportBrokenPart and checkBrokenDisks function would be invoked and the part will be handled properly.

the quesition is :
1. why we still wants to throw exception when we find disk error, after all we will trigger an automatic recovery，is it an reasonable  way to make the query just go smoothly without the broken part (say just remove the part  participate in query  with broken disk)?

2. the disk recovery process is in passive mode, which means they seems always waiting for any other "reading action" to trigger the recovery, if  I haven't miss something. Is it possible to make it more active, at least using a  dedicated thread to check the status periodically say 3 seconds. or  just trigger ReplicatedMergeTreePartCheckThead  every 3 seconds to perform disk checking.  Surely, it will certainly cause an background load uprising, I don't know whether it is affordable ?

@amosbird 
Thanks.

**Comment by amosbird** [comment]
> why we still wants to throw exception when we find disk error

Because otherwise you won't get correct query result.

> which means they seems always waiting for any other "reading action" to trigger the recovery

I didn't come up with a proper solution to trigger data part recovering.

> Is it possible to make it more active, at least using a dedicated thread to check the status periodically

It's possible. If we only need to tell the status of disks, we can enqueue one part per disk on a regular basis.

**Comment by mo-avatar** [comment]
Got it, thanks for your answer

**Comment by mo-avatar** [comment]
Because otherwise you won't get correct query result.
