### ISSUE TITLE
map CH Bool to Arrow Bool (not UInt8)

### ISSUE THREAD

**Issue by kcajf** [ClickHouse/ClickHouse#39104]
Arrow has a native Bool type. When selecting data with `FORMAT Arrow`, Clickhouse currently appears to map clickhouse Bool columns to Arrow UInt8 columns. I think these should be mapped to arrow native Bool.

**Comment by Avogar** [comment]
Was added in https://github.com/ClickHouse/ClickHouse/pull/48126
