### ISSUE TITLE
Dictionary source setting updated_field doubling memory usage 

### ISSUE THREAD

**Issue by bvt123** [ClickHouse/ClickHouse#39128]
When I try to use updated_field for incremental Dictionary reloading, memory usage increases by factor 2 and is not reduced after reload.

CREATE DICTIONARY ubug (id UInt64, uuid  UUID, updated DateTime)
    PRIMARY KEY id
SOURCE(CLICKHOUSE(  
    QUERY 'select number as id, generateUUIDv4() as uuid, now() updated from numbers(2*1E7)'
    --update_field 'updated'
    ))
LAYOUT(HASHED_Array())
LIFETIME(200);

Memory usage (system.dictionaries)
1. without update_field - 659.08 MiB
2. with update_field     - 1.52 GiB 

clickhouse version 22.6.1.1985

* Non-default settings, if any
use_uncompressed_cache	0
load_balancing	random
do_not_merge_across_partitions_select_final	1
join_use_nulls	0
any_join_distinct_right_table_keys	1
distributed_ddl_task_timeout	7200
joined_subquery_requires_alias	0
max_result_rows	0
result_overflow_mode	break
timeout_overflow_mode	break
max_subquery_depth	20
join_overflow_mode	break
max_memory_usage	300000000000
parallel_view_processing	1
external_table_functions_use_nulls	0
allow_experimental_database_materialized_mysql	1
optimize_skip_merged_partitions	1
optimize_on_insert	0
allow_experimental_object_type	1
background_pool_size	32
background_move_pool_size	16
input_format_import_nested_json	1
date_time_input_format	best_effort

**Expected behavior**

Memory usage will be the same as without update_field.

**Comment by den-crane** [comment]
by design (implementation).

https://github.com/ClickHouse/ClickHouse/issues/23870
