### ISSUE TITLE
build clickhouse 21.3.20.1 on arm linux failed

### ISSUE THREAD

**Issue by romberli** [ClickHouse/ClickHouse#39126]
I tried to build clickhouse 21.3.20.1 on arm64 linux, this virtual machine is running on MacBook  Pro with m1 max chip,
I used build command below:
cmake -DCMAKE_C_COMPILER=/usr/local/bin/clang -DCMAKE_CXX_COMPILER=/usr/local/bin/clang++ -DCMAKE_CXX_FLAGS=-stdlib=libc++ -DCMAKE_EXE_LINKER_FLAGS=-stdlib=libc++ CFLAGS=-Wno-unused-but-set-variable -DGLIBC_COMPATIBILITY=OFF ../
ninja

it's complaining errors like below:
error: implicit conversion changes signedness: 'int' to 'unsigned int' [-Werror,-Wsign-conversion]
error: disabled expansion of recursive macro [-Werror,-Wdisabled-macro-expansion]

**Operating system**
AlmaLinux release 9.0 (Emerald Puma) on ARM64
**Cmake version**
3.20.2
**Ninja version**
1.11.0
**Compiler name and version**
clang version 14.0.6
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin
**Full cmake and/or ninja output**
[0/2] Re-checking globbed directories...
[1379/7478] Building CXX object contrib/poco-cmake/Data/ODBC/CMakeFiles/_poco_data_odbc.dir/__/__/__/poco/Data/ODBC/src/Parameter.cpp.ocontrib/mariadb-connector-c/cmake/ConnectorName.cmakec[1380/7478] Building CXX object contrib/poco-cmake/Data/ODBC/CMakeFiles/_poco_data_odbc.dir/__/__/__/poco/Data/ODBC/src/Preparator.cpp.ocontrib/mariadb-connector-c/cmake/ConnectorName.cmake[4382/7478] Creating preprocessed file /data/source_code/clickhouse-21/contrib/krb5/src/lib/krb5/error_tables/k5e1_err.c
+ /usr/bin/awk -f /data/source_code/clickhouse-21/contrib/krb5/src/util/et/et_h.awk outfile=k5e1_err.h /data/source_code/clickhouse-21/contrib/krb5/src/lib/krb5/error_tables/k5e1_err.et
+ /usr/bin/awk -f /data/source_code/clickhouse-21/contrib/krb5/src/util/et/et_c.awk outfile=k5e1_err.c textdomain= localedir= /data/source_code/clickhouse-21/contrib/krb5/src/lib/krb5/error_tables/k5e1_err.et
[4383/7478] Creating preprocessed file /data/source_code/clickhouse-21/contrib/krb5/src/lib/krb5/error_tables/kdb5_err.c
+ /usr/bin/awk -f /data/source_code/clickhouse-21/contrib/krb5/src/util/et/et_h.awk outfile=kdb5_err.h /data/source_code/clickhouse-21/contrib/krb5/src/lib/krb5/error_tables/kdb5_err.et
+ /usr/bin/awk -f /data/source_code/clickhouse-21/contrib/krb5/src/util/et/et_c.awk outfile=kdb5_err.c textdomain= localedir= /data/source_code/clickhouse-21/contrib/krb5/src/lib/krb5/error_tables/kdb5_err.et
[4384/7478] Creating preprocessed file /data/source_code/clickhouse-21/contrib/krb5/src/lib/krb5/error_tables/krb5_err.c
+ /usr/bin/awk -f /data/source_code/clickhouse-21/contrib/krb5/src/util/et/et_h.awk outfile=krb5_err.h /data/source_code/clickhouse-21/contrib/krb5/src/lib/krb5/error_tables/krb5_err.et
+ /usr/bin/awk -f /data/source_code/clickhouse-21/contrib/krb5/src/util/et/et_c.awk outfile=krb5_err.c textdomain= localedir= /data/source_code/clickhouse-21/contrib/krb5/src/lib/krb5/error_tables/krb5_err.et
[4385/7478] Creating preprocessed file /data/source_code/clickhouse-21/contrib/krb5/src/lib/krb5/error_tables/asn1_err.c
+ /usr/bin/awk -f /data/source_code/clickhouse-21/contrib/krb5/src/util/et/et_h.awk outfile=asn1_err.h /data/source_code/clickhouse-21/contrib/krb5/src/lib/krb5/error_tables/asn1_err.et
+ /usr/bin/awk -f /data/source_code/clickhouse-21/contrib/krb5/src/util/et/et_c.awk outfile=asn1_err.c textdomain= localedir= /data/source_code/clickhouse-21/contrib/krb5/src/lib/krb5/error_tables/asn1_err.et
[4386/7478] Creating preprocessed file /data/source_code/clickhouse-21/contrib/krb5/src/lib/krb5/error_tables/krb524_err.c
+ /usr/bin/awk -f /data/source_code/clickhouse-21/contrib/krb5/src/util/et/et_h.awk outfile=krb524_err.h /data/source_code/clickhouse-21/contrib/krb5/src/lib/krb5/error_tables/krb524_err.et
+ /usr/bin/awk -f /data/source_code/clickhouse-21/contrib/krb5/src/util/et/et_c.awk outfile=krb524_err.c textdomain= localedir= /data/source_code/clickhouse-21/contrib/krb5/src/lib/krb5/error_tables/krb524_err.et
[4388/7478] Creating preprocessed file /data/source_code/clickhouse-21/contrib/krb5/src/lib/krb5/error_tables/kv5m_err.c
+ /usr/bin/awk -f /data/source_code/clickhouse-21/contrib/krb5/src/util/et/et_h.awk outfile=kv5m_err.h /data/source_code/clickhouse-21/contrib/krb5/src/lib/krb5/error_tables/kv5m_err.et
+ /usr/bin/awk -f /data/source_code/clickhouse-21/contrib/krb5/src/util/et/et_c.awk outfile=kv5m_err.c textdomain= localedir= /data/source_code/clickhouse-21/contrib/krb5/src/lib/krb5/error_tables/kv5m_err.et
[4390/7478] Creating preprocessed file /data/source_code/clickhouse-21/contrib/krb5/src/lib/gssapi/krb5/gssapi_err_krb5.c
+ /usr/bin/awk -f /data/source_code/clickhouse-21/contrib/krb5/src/util/et/et_h.awk outfile=gssapi_err_krb5.h /data/source_code/clickhouse-21/contrib/krb5/src/lib/gssapi/krb5/gssapi_err_krb5.et
+ /usr/bin/awk -f /data/source_code/clickhouse-21/contrib/krb5/src/util/et/et_c.awk outfile=gssapi_err_krb5.c textdomain= localedir= /data/source_code/clickhouse-21/contrib/krb5/src/lib/gssapi/krb5/gssapi_err_krb5.et
[4391/7478] Creating preprocessed file /data/source_code/clickhouse-21/contrib/krb5/src/lib/gssapi/generic/gssapi_err_generic.c
+ /usr/bin/awk -f /data/source_code/clickhouse-21/contrib/krb5/src/util/et/et_h.awk outfile=gssapi_err_generic.h /data/source_code/clickhouse-21/contrib/krb5/src/lib/gssapi/generic/gssapi_err_generic.et
+ /usr/bin/awk -f /data/source_code/clickhouse-21/contrib/krb5/src/util/et/et_c.awk outfile=gssapi_err_generic.c textdomain= localedir= /data/source_code/clickhouse-21/contrib/krb5/src/lib/gssapi/generic/gssapi_err_generic.et
[4395/7478] Creating preprocessed file /data/source_code/clickhouse-21/contrib/krb5/src/util/profile/prof_err.c
+ /usr/bin/awk -f /data/source_code/clickhouse-21/contrib/krb5/src/util/et/et_h.awk outfile=prof_err.h /data/source_code/clickhouse-21/contrib/krb5/src/util/profile/prof_err.et
+ /usr/bin/awk -f /data/source_code/clickhouse-21/contrib/krb5/src/util/et/et_c.awk outfile=prof_err.c textdomain= localedir= /data/source_code/clickhouse-21/contrib/krb5/src/util/profile/prof_err.et
[5315/7478] Building C object base/readpassphrase/CMakeFiles/readpassphrase.dir/readpassphrase.c.o
FAILED: base/readpassphrase/CMakeFiles/readpassphrase.dir/readpassphrase.c.o
/usr/local/bin/clang -DSTD_EXCEPTION_HAS_STACK_TRACE=1 -I../contrib/sentry-native/include -Iincludes/configs -I../base/readpassphrase/. -isystem ../contrib/libcxx/include -isystem ../contrib/libcxxabi/include -isystem ../contrib/libunwind/include -fdiagnostics-color=always  -gdwarf-aranges  -Wall -Wno-unused-command-line-argument  -fdiagnostics-absolute-paths -fexperimental-new-pass-manager -Werror -Wframe-larger-than=65536 -Wpedantic -Wno-vla-extension -Wno-zero-length-array -Wno-c11-extensions -Wcomma -Wconditional-uninitialized -Wcovered-switch-default -Wdeprecated -Wembedded-directive -Wempty-init-stmt -Wextra-semi-stmt -Wextra-semi -Wgnu-case-range -Winconsistent-missing-destructor-override -Wnewline-eof -Wold-style-cast -Wrange-loop-analysis -Wredundant-parens -Wreserved-id-macro -Wshadow-field -Wshadow-uncaptured-local -Wshadow -Wstring-plus-int -Wundef -Wunreachable-code-return -Wunreachable-code -Wunused-exception-parameter -Wunused-macros -Wunused-member-function -Wzero-as-null-pointer-constant -Weverything -O2 -g -DNDEBUG -O3    -D OS_LINUX -Wno-unused-result -Wno-reserved-id-macro -MD -MT base/readpassphrase/CMakeFiles/readpassphrase.dir/readpassphrase.c.o -MF base/readpassphrase/CMakeFiles/readpassphrase.dir/readpassphrase.c.o.d -o base/readpassphrase/CMakeFiles/readpassphrase.dir/readpassphrase.c.o -c ../base/readpassphrase/readpassphrase.c
/data/source_code/clickhouse-21/base/readpassphrase/readpassphrase.c:97:29: error: implicit conversion changes signedness: 'int' to 'unsigned int' [-Werror,-Wsign-conversion]
            term.c_lflag &= ~(ECHO | ECHONL);
                         ~~ ^~~~~~~~~~~~~~~~
/data/source_code/clickhouse-21/base/readpassphrase/readpassphrase.c:117:8: error: disabled expansion of recursive macro [-Werror,-Wdisabled-macro-expansion]
    sa.sa_handler = handler;
       ^
/usr/include/bits/sigaction.h:39:41: note: expanded from macro 'sa_handler'
# define sa_handler     __sigaction_handler.sa_handler
                                            ^
/data/source_code/clickhouse-21/base/readpassphrase/readpassphrase.c:138:32: error: disabled expansion of recursive macro [-Werror,-Wdisabled-macro-expansion]
                    ch = (char)tolower((unsigned char)ch);
                               ^
/usr/include/ctype.h:220:35: note: expanded from macro 'tolower'
#  define tolower(c)    __tobody (c, tolower, *__ctype_tolower_loc (), (c))
                                     ^
/data/source_code/clickhouse-21/base/readpassphrase/readpassphrase.c:140:32: error: disabled expansion of recursive macro [-Werror,-Wdisabled-macro-expansion]
                    ch = (char)toupper((unsigned char)ch);
                               ^
/usr/include/ctype.h:221:35: note: expanded from macro 'toupper'
#  define toupper(c)    __tobody (c, toupper, *__ctype_toupper_loc (), (c))
                                     ^
4 errors generated.
[5320/7478] Building CXX object contrib/nuraft-cmake/CMakeFiles/nuraft.dir/__/NuRaft/src/asio_service.cxx.o
ninja: build stopped: subcommand failed.

**Comment by alexey-milovidov** [comment]
Official ARM support in ClickHouse has been introduced in 2022.
It does not make sense to build old museum ClickHouse versions.
