### ISSUE TITLE
how to remove disks in ck safely? 

### ISSUE THREAD

**Issue by rfyiamcool** [ClickHouse/ClickHouse#39165]
current clickhouse node has 1T SSD,  then ops add one 5T SSD on the node， I want to move data from  1T ssd to 5T ssd, remove the 1T ssd. how to do ?  

thank u.

**Comment by den-crane** [comment]
Do you need it online? Or you can use downtime?

**Comment by rfyiamcool** [comment]
I can't stop clickhouse, other service always read and write ck.

**Comment by UnamedRus** [comment]
We need feature request for `drain mode` for disks.

**Comment by den-crane** [comment]
https://kb.altinity.com/altinity-kb-setup-and-maintenance/altinity-kb-moving-table-to-another-device./

**Comment by rfyiamcool** [comment]
If i has 500+ tabels, need to run `alter modify storage_policy` 500 times ? 😅

**Comment by rkozlo** [comment]
You could also try to overwrite your default storage policy. It wont work without problems #35568 here i reported some.
The easiest would be rsync everything to new disk, stop ch, rsync again and start ch. Downtime would be like 1-2 minutes probably. If tables are not replicated then apps always should be prepared to some clickhouse crash/restart.

**Comment by alexey-milovidov** [comment]
Assuming you have replicas:
Create an empty replica, and wait for replication.

**Comment by rfyiamcool** [comment]
@alexey-milovidov thank u. 😁
