### ISSUE TITLE
BUG when using MV. The rollup table have time unexpected.

### ISSUE THREAD

**Issue by chuquanghopbk** [ClickHouse/ClickHouse#39162]
I'm using ClickHouse client version 22.3.6.5.
1. I have row table:

CREATE TABLE dpiNew.subscriber  ON CLUSTER prod_cluster
(
session_id UInt64,
start_time UInt64,
end_time UInt64,
up_application String,
up_application_description String,
up_application_category LowCardinality(String),
up_application_subcategory LowCardinality(String),
rat String,
ue_ip String,
imsi String,
msisdn String,
imei String,
reallac String,
realcell String,
up_app_id UInt64,
) 
Engine=ReplicatedMergeTree('/clickhouse/{cluster}/{database}/tables/{table}/{layer}-{shard}', '{replica}') 
PARTITION BY toYYYYMMDD(toDate(end_time/1000000000, 'Asia/Ho_Chi_Minh'))
ORDER BY (msisdn,end_time,rat,reallac, realcell,imei, device_model,up_application_category,up_application)
SETTINGS storage_policy = 'ebs_hot_and_cold', index_granularity = 8192; 
!--------------------------------------------------!
!--------------------------------------------------!
2. I create rollup table:
CREATE TABLE dpiNew.subscriber_hour  ON CLUSTER prod_cluster (
end_time DateTime('Asia/Ho_Chi_Minh'),
msisdn String,
rat String,
reallac String,
realcell String,
imei String,
device_model String,
up_application_category LowCardinality(String),
up_application String,
crecord AggregateFunction(sum,UInt64)
 )
Engine=ReplicatedMergeTree('/clickhouse/{cluster}/{database}/tables/{table}/{layer}-{shard}', '{replica}') 
PARTITION BY toYYYYMMDD(end_time)
ORDER BY (msisdn,end_time,rat,reallac, realcell,imei, device_model,up_application_category,up_application)
SETTINGS storage_policy = 'ebs_hot_and_cold', index_granularity = 8192;
!--------------------------------------------------!
!--------------------------------------------------!
3. Create MV:
CREATE MATERIALIZED VIEW dpiNew.subscriber_hour_v  ON CLUSTER prod_cluster
TO dpiNew.subscriber_hour
AS SELECT
toDateTime(end_time/1000000000, 'Asia/Ho_Chi_Minh') as end_time_H,
msisdn,
rat,
reallac,
realcell,
imei,
device_model,
up_application_category,
up_application,
sumState(up_app_id) as crecord 
FROM dpiNew.subscriber
WHERE end_time_H >= toDateTime('2022-07-01 00:00:00')
GROUP BY msisdn,end_time_H,rat,reallac, realcell,imei, device_model,up_application_category,up_application
ORDER BY msisdn,end_time_H,rat,reallac, realcell,imei, device_model,up_application_category,up_application;
4. Ingest to row table:
after ingest subscriber table. I've check rollup table. The result of end_time is stranger:
![image](https://user-images.githubusercontent.com/29943959/178692008-544255d7-ee37-4d9c-b6a8-bdfff6a5401b.png)

6. Ingest to rollup table from select in row: THE FORMAT DATE IS OK.
INSERT INTO dpiNew.subscriber_hour
SELECT
toDateTime(end_time/1000000000, 'Asia/Ho_Chi_Minh') as end_time_H,
msisdn,
rat,
reallac,
realcell,
imei,
device_model,
up_application_category,
up_application,
sumState(up_app_id) as crecord 
FROM dpiNew.subscriber
WHERE end_time_H >= toDate('2022-06-01 00:00:00')
GROUP BY msisdn,end_time_H,rat,reallac, realcell,imei, device_model,up_application_category,up_application
ORDER BY msisdn,end_time_H,rat,reallac, realcell,imei, device_model,up_application_category,up_application;
![image](https://user-images.githubusercontent.com/29943959/178692353-c043c793-b01b-4400-90c6-c730bdc52276.png)

CAN ANYONE TELL ME WHY internally ingest from row table (subscriber) to rollup table (subscriber_hour) have difference time

**Comment by Slach** [comment]
When `end_time` is `0` or `end_time/1000000000` is `0` then you will have toDateTime`1970-01-01`

check ingested values
`SELECT count() FROM  dpiNew.subscriber WHERE end_time=0`

**Comment by den-crane** [comment]
First of all ReplicatedMergeTree does not make sense for AggregateFunction(sum,UInt64)

**Comment by chuquanghopbk** [comment]
> When `end_time` is `0` or `end_time/1000000000` is `0` then you will have toDateTime`1970-01-01`
> 
> check ingested values `SELECT count() FROM dpiNew.subscriber WHERE end_time=0 OR end_time/1000000000 = 0`

dpi228.vnpt.vn :) SELECT count() FROM dpiNew.subscriber WHERE end_time=0 OR end_time/1000000000 = 0;

SELECT count()
FROM dpiNew.subscriber
WHERE (end_time = 0) OR ((end_time / 1000000000) = 0)

Query id: 3ee448d4-7d13-4441-a63f-07d2d3c4340f

┌─count()─┐
│       0 │
└─────────┘

1 rows in set. Elapsed: 0.006 sec. 

dpi228.vnpt.vn :) SELECT count() FROM dpiNew.subscriber;

SELECT count()
FROM dpiNew.subscriber

Query id: f576be15-7167-4aa8-a574-0074d40455c6

┌─count()─┐
│   59084 │
└─────────┘

1 rows in set. Elapsed: 0.004 sec. 
===> This not issue by case you mention.

**Comment by den-crane** [comment]
Column names does not match `end_time DateTime('Asia/Ho_Chi_Minh'),` VS `toDateTime(end_time/1000000000, 'Asia/Ho_Chi_Minh') as end_time_H,`

Materialized View uses column names to insert data.

**Comment by chuquanghopbk** [comment]
Thanks @den-crane  very much !
That Exactly error.
> Column names does not match `end_time DateTime('Asia/Ho_Chi_Minh'),` VS `toDateTime(end_time/1000000000, 'Asia/Ho_Chi_Minh') as end_time_H,`
> 
> `end_time` <> `end_time_H`
> 
> Materialized View uses column names to insert data.
> 
> see https://den-crane.github.io/Everything_you_should_know_about_materialized_views_commented.pdf page 14

**Comment by chuquanghopbk** [comment]
Final, I'm note:
#############
CREATE TABLE dpiNew.subscriber_hour  ON CLUSTER prod_cluster (
end_time DateTime('Asia/Ho_Chi_Minh'),
msisdn String,
rat String,
reallac String,
realcell String,
imei String,
device_model String,
up_application_category LowCardinality(String),
up_application String,
crecord SimpleAggregateFunction(sum,UInt64)
 )
Engine=ReplicatedAggregatingMergeTree('/clickhouse/{cluster}/{database}/tables/{table}/{layer}-{shard}', '{replica}') 
PARTITION BY toYYYYMMDD(end_time)
ORDER BY (msisdn,end_time,rat,reallac, realcell,imei, device_model,up_application_category,up_application)
SETTINGS storage_policy = 'ebs_hot_and_cold', index_granularity = 8192;
###############
CREATE MATERIALIZED VIEW dpiNew.subscriber_hour_v  ON CLUSTER prod_cluster
TO dpiNew.subscriber_hour
AS SELECT
toStartOfFifteenMinutes(end_time) as end_time,
msisdn,
rat,
reallac,
realcell,
imei,
device_model,
up_application_category,
up_application,
sum(up_app_id) as crecord 
FROM dpiNew.subscriber
WHERE end_time >= toDateTime('2022-07-01 00:00:00')
GROUP BY msisdn,end_time,rat,reallac, realcell,imei, device_model,up_application_category,up_application
ORDER BY msisdn,end_time,rat,reallac, realcell,imei, device_model,up_application_category,up_application;
=====
It run okie now.

**Comment by chuquanghopbk** [comment]
Final, I'm note:
#############
CREATE TABLE dpiNew.subscriber_hour  ON CLUSTER prod_cluster (
end_time DateTime('Asia/Ho_Chi_Minh'),
msisdn String,
rat String,
reallac String,
realcell String,
imei String,
device_model String,
up_application_category LowCardinality(String),
up_application String,
crecord SimpleAggregateFunction(sum,UInt64)
 )
Engine=ReplicatedAggregatingMergeTree('/clickhouse/{cluster}/{database}/tables/{table}/{layer}-{shard}', '{replica}') 
PARTITION BY toYYYYMMDD(end_time)
ORDER BY (msisdn,end_time,rat,reallac, realcell,imei, device_model,up_application_category,up_application)
SETTINGS storage_policy = 'ebs_hot_and_cold', index_granularity = 8192;
###############
CREATE MATERIALIZED VIEW dpiNew.subscriber_hour_v  ON CLUSTER prod_cluster
TO dpiNew.subscriber_hour
AS SELECT
toStartOfFifteenMinutes(end_time) as end_time,
msisdn,
rat,
reallac,
realcell,
imei,
device_model,
up_application_category,
up_application,
sum(up_app_id) as crecord 
FROM dpiNew.subscriber
WHERE end_time >= toDateTime('2022-07-01 00:00:00')
GROUP BY msisdn,end_time,rat,reallac, realcell,imei, device_model,up_application_category,up_application
ORDER BY msisdn,end_time,rat,reallac, realcell,imei, device_model,up_application_category,up_application;
=====
It run okie now.
