### ISSUE TITLE
Can't rename table

### ISSUE THREAD

**Issue by dmitriyshashkin** [ClickHouse/ClickHouse#3917]
The following query `RENAME TABLE old_name TO new_name` produces the following error: Directory not empty: %path to old table's directory%

CH version `18.14.54409`.

**Comment by alesapin** [comment]
This message mean, that table `new_name` already exists or some files for this table persist on disk. 

- In first case you have to remove table `new_name` with query `DROP TABLE db_name.new_name`. `db_name` may be omitted if table stored in `default` database. 
- In other case you have to remove files for this table manually. Default path for clickhouse database is `/var/lib/clickhouse/`, but it maybe changed in your configuration file. You can use following command:
`rm -r /var/lib/clickhouse/data/db_name/new_name && rm /var/lib/clickhouse/metadata/db_name/new_name.sql`

**Comment by dmitriyshashkin** [comment]
But the error said that the directory for the OLD table wasn't empty. Not for the new one.

**Comment by alesapin** [comment]
Need example and full error text.

**Comment by dgrr** [comment]
Seems that you can rename tables if it does not have comments. When a table contains a comment it shows the following error:
```
Received exception from server (version 19.4.1):
Code: 62. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Syntax error (in file /var/lib/clickhouse/metadata/db/supertable.sql): failed at position 62 (line 3, col 37): COMMENT 'Date when the event occurred', 
    campaign_id Int32 CODEC(ZSTD(22)) COMMENT 'Campaign identifier', 
    event_type LowCardinality(String) COMMENT 'Type o. Expected one of: token, ClosingRoundBracket, Comma.```

**Comment by filimonov** [comment]
Can't reproduce at 19.14:

```
c39ddd31ab1c :) CREATE TABLE foo
(
    `date` Date COMMENT 'Date when the event occurred', 
    `campaign_id` Int32 COMMENT 'Campaign identifier' CODEC(ZSTD(22)), 
    `event_type` LowCardinality(String) COMMENT 'Type of event'
)
ENGINE = MergeTree()
ORDER BY campaign_id

Ok.

0 rows in set. Elapsed: 0.083 sec. 

c39ddd31ab1c :) insert into foo values ('2000-01-01', 12123,'event');

Ok.
1 rows in set. Elapsed: 0.079 sec. 

c39ddd31ab1c :) RENAME TABLE foo to bar;

RENAME TABLE foo TO bar

Ok.

0 rows in set. Elapsed: 0.075 sec. 

c39ddd31ab1c :) select * from bar;

┌───────date─┬─campaign_id─┬─event_type─┐
│ 2000-01-01 │       12123 │ event      │
└────────────┴─────────────┴────────────┘

1 rows in set. Elapsed: 0.019 sec. 
```
