### ISSUE TITLE
Projections bug with MAX fuction

### ISSUE THREAD

**Issue by alps99w** [ClickHouse/ClickHouse#39180]
CH Version 
22.2.3.1.

Table definition
CREATE TABLE alps_test_local_v1
(
    `cid` UInt32,
    `useragent` String,
    `useragent_hash` UInt64 DEFAULT URLHash(lower(useragent)),
    `ua_group_id` UInt64,
    `url` String,
    `urlhash` UInt64 DEFAULT URLHash(lower(url)),
    `ip_address` String,
    `date` Date,
    `timestamp` DateTime,
    `response_code` UInt16,
    `versioning` UInt16 DEFAULT CAST(0, 'UInt16'),
    `url_murmur_hash` UInt64 DEFAULT murmurHash3_64(url),
    INDEX urlhash_bloomfilter urlhash TYPE bloom_filter GRANULARITY 1,
    PROJECTION pro_agg_1
    (
        SELECT
            decodeURLComponent(any(url)) AS decodeUrl,
            max(date) AS lastCrawlDate,
            count(urlhash) AS total_urls,
            uniqHLL12(urlhash) AS unique_urls,
            uniqHLL12(date) AS total_days,
            uniqHLL12(useragent_hash) AS agentUniqCount,
            uniqHLL12(cityHash64(ip_address)) AS ipUniqCount,
            sum(multiIf((response_code >= 0) AND (response_code < 100), 1, 0)) AS count0xx,
            sum(multiIf((response_code >= 200) AND (response_code < 300), 1, 0)) AS count2xx,
            sum(multiIf((response_code >= 300) AND (response_code < 400), 1, 0)) AS count3xx,
            sum(multiIf((response_code >= 400) AND (response_code < 500), 1, 0)) AS count4xx,
            sum(multiIf((response_code >= 500) AND (response_code < 600), 1, 0)) AS count5xx,
            any(useragent) AS useragentName,
            useragent_hash,
            ua_group_id,
            response_code,
            urlhash
        GROUP BY
            date,
            cid,
            versioning,
            ua_group_id,
            useragent_hash,
            response_code,
            urlhash
    )
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(date)
ORDER BY (cid, ua_group_id, date, versioning)
SETTINGS index_granularity = 8192

#######
 insert into alps_test_local_v1(urlhash,date,cid,timestamp) values (33791521711502031,'2022-04-07',12345, '2022-04-07 13:04:18'),(33791521711502031,'2022-04-07',12345, '2022-04-07 16:14:18');

#######
Run the same query multiple times. but the max(date) changes every time. 

SELECT
    urlhash,
    MAX(date)
FROM alps_test_local_v1
WHERE (cid = 12345) AND (urlhash = 33791521711502031) AND (versioning = 0) AND (date = '2022-04-07')
GROUP BY urlhash
┌───────────urlhash─┬──max(date)─┐
│ 33791521711502031 │ **2077-05-04** │
└───────────────────┴────────────┘

SELECT
    urlhash,
    MAX(date)
FROM alps_test_local_v1
WHERE (cid = 12345) AND (urlhash = 33791521711502031) AND (versioning = 0) AND (date = '2022-04-07')
GROUP BY urlhash
┌───────────urlhash─┬──max(date)─┐
│ 33791521711502031 │ **2056-09-20** │
└───────────────────┴────────────┘

SELECT
    urlhash,
    MAX(date)
FROM alps_test_local_v1
WHERE (cid = 12345) AND (urlhash = 33791521711502031) AND (versioning = 0) AND (date = '2022-04-07')
GROUP BY urlhash
┌───────────urlhash─┬──max(date)─┐
│ 33791521711502031 │ **2067-07-23** │
└───────────────────┴────────────┘

**Comment by den-crane** [comment]
@alps99w   `PROJECTION pro_agg_1 ... max(date) AS lastCrawlDate ...  GROUP BY date,`

has no sense ? should be always `max(date) = date`

**Comment by amosbird** [comment]
What if you set `optimize_aggregators_of_group_by_keys = 0` ?

**Comment by den-crane** [comment]
> What if you set `optimize_aggregators_of_group_by_keys = 0` ?

No difference

```sql
set optimize_aggregators_of_group_by_keys=0;

┌───────────urlhash─┬──max(date)─┐
│ 33791521711502031 │ 1970-01-01 │
└───────────────────┴────────────┘

set optimize_aggregators_of_group_by_keys=1;
┌───────────urlhash─┬──max(date)─┐
│ 33791521711502031 │ 1970-01-01 │
└───────────────────┴────────────┘

set allow_experimental_projection_optimization=0;
┌───────────urlhash─┬──max(date)─┐
│ 33791521711502031 │ 2022-04-07 │
└───────────────────┴────────────┘
```

**Comment by amosbird** [comment]
@den-crane It's related. You need to disable that setting before creating and populating the projection.

**Comment by amosbird** [comment]
@alps99w As @den-crane pointed out: `MAX(date)` doesn't make sense because you already did `group by date`. Try rebuild the projection without `MAX(date)` or without the date key.

**Comment by alps99w** [comment]
thanks @amosbird will give it a try

**Comment by amosbird** [comment]
BTW, you should consider upgrade to 22.3-lts from which the projection feature is production-ready.
