### ISSUE TITLE
FreeBSD: quick start guide is broken, scripts are wrong, and installer dies

### ISSUE THREAD

**Issue by widduck** [ClickHouse/ClickHouse#39204]
> You have to provide the following information whenever possible.

**Describe what's wrong**

CH doesn't start on on FreeBSD 13.1-RELEASE amd64 when following the Quick Start guide
and using the default download / installer.

`ClickHouse 22.7.1.1993 with revision 54464, no build id`

There are multiple errors and basic mistakes, which, once worked around, end up here:

`<Error> Application: DB::Exception: FunctionFactory: the function name '' is not unique`

this comes from https://github.com/ClickHouse/ClickHouse/blob/master/src/Storages/StorageFactory.cpp#L54

> A clear and concise description of what works not as it is supposed to.

**Does it reproduce on recent release?**

yes, also tried on aarch64 without success.

**How to reproduce**

* Which ClickHouse server version to use

`ClickHouse 22.7.1.1993 with revision 54464, no build id`

- install FreeBSD 13.1-RELEASE amd64 & follow quick-start guide at https://clickhouse.com/docs/en/quick-start/ or https://clickhouse.com/docs/en/getting-started/install/

**Expected behavior**

if a platform is supported, then the guides should work as expected.

**Error message and/or stacktrace**

### following quickstart:

Downloading and running `https://clickhouse.com/docs/en/quick-start/` downloads a shell script

curl https://clickhouse.com/ | sh

this script incorrectly checks on FreeBSD for `x86_64` when it should check for `amd64`.
Once corrected, this script does download the tarball, and we end up at the same install process as 
when following https://clickhouse.com/docs/en/getting-started/install/ - 

curl -O 'https://builds.clickhouse.com/master/freebsd/clickhouse' && chmod a+x ./clickhouse

when we run this,

```
root# ./clickhouse install
Copying ClickHouse binary to /usr/bin/clickhouse.new
Renaming /usr/bin/clickhouse.new to /usr/bin/clickhouse.
Creating symlink /usr/bin/clickhouse-server to /usr/bin/clickhouse.
Creating symlink /usr/bin/clickhouse-client to /usr/bin/clickhouse.
Creating symlink /usr/bin/clickhouse-local to /usr/bin/clickhouse.
Creating symlink /usr/bin/clickhouse-benchmark to /usr/bin/clickhouse.
Creating symlink /usr/bin/clickhouse-copier to /usr/bin/clickhouse.
Creating symlink /usr/bin/clickhouse-obfuscator to /usr/bin/clickhouse.
Creating symlink /usr/bin/clickhouse-git-import to /usr/bin/clickhouse.
Creating symlink /usr/bin/clickhouse-compressor to /usr/bin/clickhouse.
Creating symlink /usr/bin/clickhouse-format to /usr/bin/clickhouse.
Creating symlink /usr/bin/clickhouse-extract-from-config to /usr/bin/clickhouse.
Creating symlink /usr/bin/clickhouse-keeper to /usr/bin/clickhouse.
Creating symlink /usr/bin/clickhouse-keeper-converter to /usr/bin/clickhouse.
Creating symlink /usr/bin/clickhouse-disks to /usr/bin/clickhouse.
Creating clickhouse group if it does not exist.
 pw groupadd clickhouse
pw: group name `clickhouse' already exists
Creating clickhouse user if it does not exist.
 pw useradd -s /bin/false -d /nonexistent -g clickhouse -n clickhouse
pw: login name `clickhouse' already exists
Will set ulimits for clickhouse user in /etc/security/limits.d/clickhouse.conf.
Creating config directory /etc/clickhouse-server.
Creating config directory /etc/clickhouse-server/config.d that is used for tweaks of main server configuration.
Creating config directory /etc/clickhouse-server/users.d that is used for tweaks of users configuration.
Data path configuration override is saved to file /etc/clickhouse-server/config.d/data-paths.xml.
Log path configuration override is saved to file /etc/clickhouse-server/config.d/logger.xml.
User directory path configuration override is saved to file /etc/clickhouse-server/config.d/user-directories.xml.
OpenSSL path configuration override is saved to file /etc/clickhouse-server/config.d/openssl.xml.
Creating log directory /var/log/clickhouse-server.
Creating data directory /var/lib/clickhouse.
Creating pid directory /var/run/clickhouse-server.
 chown -R clickhouse:clickhouse '/var/log/clickhouse-server'
 chown -R clickhouse:clickhouse '/var/run/clickhouse-server'
 chown  clickhouse:clickhouse '/var/lib/clickhouse'
Enter password for default user:
Password for default user is saved in file /etc/clickhouse-server/users.d/default-password.xml.
Allow server to accept connections from the network (default is localhost only), [y/N]: y
The choice is saved in file /etc/clickhouse-server/config.d/listen.xml.
 chown -R clickhouse:clickhouse '/etc/clickhouse-server'

ClickHouse has been successfully installed.

Start clickhouse-server with:
 su -m root -c 'clickhouse start'

Start clickhouse-client with:
 clickhouse-client --password
```

lets run that now, it seems ok:

```
# clickhouse start
 chown -R clickhouse: '/var/run/clickhouse-server/'
Will run clickhouse su 'clickhouse' /usr/bin/clickhouse-server --config-file /etc/clickhouse-server/config.xml --pid-file /var/run/clickhouse-server/clickhouse-server.pid --daemon
Waiting for server to start
Waiting for server to start
Waiting for server to start
Waiting for server to start
Waiting for server to start
...
Waiting for server to start
Cannot start server. You can execute clickhouse su 'clickhouse' /usr/bin/clickhouse-server --config-file /etc/clickhouse-server/config.xml --pid-file /var/run/clickhouse-server/clickhouse-server.pid --daemon without --daemon option to run manually.
Look for logs at /var/log/clickhouse-server/ and for /var/log/clickhouse-server/stderr.log.
```

OK lets run that manually

```
# /usr/bin/clickhouse-server --config-file /etc/clickhouse-server/config.xml --pid-file /var/run/clickhouse-server/clickhouse-server.pid
Processing configuration file '/etc/clickhouse-server/config.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/data-paths.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/listen.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/logger.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/openssl.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/user-directories.xml'.
Logging trace to /var/log/clickhouse-server/clickhouse-server.log
Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
2022.07.13 22:44:21.470705 [ 100319 ] {} <Information> : Starting ClickHouse 22.7.1.1993 with revision 54464, no build id, PID 32758
2022.07.13 22:44:21.477662 [ 100319 ] {} <Information> Application: starting up
2022.07.13 22:44:21.477705 [ 100319 ] {} <Information> Application: OS name: FreeBSD, version: 13.1-RELEASE, architecture: amd64
2022.07.13 22:44:21.478428 [ 100319 ] {} <Error> Application: DB::Exception: FunctionFactory: the function name '' is not unique
2022.07.13 22:44:21.478453 [ 100319 ] {} <Information> Application: shutting down
2022.07.13 22:44:21.478463 [ 100319 ] {} <Debug> Application: Uninitializing subsystem: Logging Subsystem
2022.07.13 22:44:21.478542 [ 156725 ] {} <Trace> BaseDaemon: Received signal -2
2022.07.13 22:44:21.478586 [ 156725 ] {} <Information> BaseDaemon: Stop SignalListener thread
```

time to stop, this clearly hasn't been tested recently.

I tried to build from source but could do with some more detailed instructions.

**Comment by widduck** [comment]
this might be some missing config setting `2022.07.13 22:44:21.478428 [ 100319 ] {} <Error> Application: DB::Exception: FunctionFactory: the function name '' is not unique` but the installer should do that correctly for us.

**Comment by nickitat** [comment]
@Felixoid could you pls take a look?

**Comment by Felixoid** [comment]
I am not sure where to start. It looks to me like the script done everything right, but the binary is not running. I don't have a freebsd host to try =\

**Comment by alexey-milovidov** [comment]
@Felixoid 

> I don't have a freebsd host to try

You can create FreeBSD hosts in AWS EC2.

**Comment by alexey-milovidov** [comment]
#39302

**Comment by widduck** [comment]
Thanks for PR to address installer bugs!

But where does this runtime error originate?

‘’’
 2022.07.13 22:44:21.478428 [ 100319 ] {} <Error> Application: DB::Exception: FunctionFactory: the function name '' is not unique
‘’’

 the installer should do that correctly for us? Or is this different bug? Do you also get this on FreeBSD too?

**Comment by pkit** [comment]
@alexey-milovidov err...when that FreeBSD madness started?
Anyway, I don't see a dev guide for it too... cross-compiler? toolchain?

**Comment by alexey-milovidov** [comment]
I confirm, the build is broken: https://pastila.nl/?0067bece/9c1db428bf6f7297cdf6f77d667b4d79

@pkit Simply follow the build log in ClickHouse Special Build Check.

**Comment by alexey-milovidov** [comment]
Related to Vector Math functions: https://pastila.nl/?004acaf7/9cc8226d76f4f3790ab0872568d0a946
Let's ask for help from @davenger

**Comment by widduck** [comment]
gracias!
