### ISSUE TITLE
hive data to clickhouse, Datetime format column increase 8 hours

### ISSUE THREAD

**Issue by sailhf** [ClickHouse/ClickHouse#39217]
When I synchronize hive data to clickhouse, I found that all Datetime format columns increase 8 hours. For example, one column named 'event_time', the value is: '2022-07-14 00:00:00' in hive, it changed to '2022-07-14 08:00:00' after synchronization.
The command is like: 
cat xxx | clickhouse --client -h xxx --port xx--password xx --query "INSERT INTO table FORMAT ORC" --use_client_time_zone true

**Comment by alexey-milovidov** [comment]
Most likely the data is imported correctly, but being displayed in your local time zone.
You can inspect the UNIX timestamp value of the DateTime by querying

`SELECT toUInt32(event_time)`
