### ISSUE TITLE
Failed to attach table after manual metadata change in ZooKeeper

### ISSUE THREAD

**Issue by sky9611** [ClickHouse/ClickHouse#39211]
ClickHouse version:21.12.3.32

Error message: 
```
<Error> Application: DB::ParsingException: Cannot parse input: expected 'date column: ' before: '\nsampling expression:\nindex granularity: 8192\nmode: 0\nsign column:\nprimary key: EventName, Client, OS, AppLanguage, Country, TenantId\ndata format version: 1\npar'
```

This happened after I manually updated metadata node value in zookeeper, because replica's metadata version is lower than its parent's.

Here is the metadata node after update:

```
metadata format version: 1
date column:
sampling expression:
index granularity: 8192
mode: 0
sign column:
primary key: EventName, Client, OS, AppLanguage, Country, TenantId
data format version: 1
partition key: toYYYYMM(Time)
granularity bytes: 10485760
```

It does have `date column: ` part as mentioned in the error log. 

Could anyone help take a look?

**Comment by chhetripradeep** [comment]
This generally happens if you are using an editor which automatically trims extra white space at the end.

As you can see in the error message: `Cannot parse input: expected 'date column: ' before:`

Notice the extra space after `:` 

So if you add that extra space, it will fix the issue.
