### ISSUE TITLE
Does  AggregationReplicatedMergeTree work with Encryption ?

### ISSUE THREAD

**Issue by DipalPrajapati** [ClickHouse/ClickHouse#39221]
Have you guys tested AggregationReplicatedMergeTree with encryption? 
It is not working with 22.6.1.1985

`Exception in thread "main" ru.yandex.clickhouse.except.ClickHouseException: ClickHouse exception, code: 40, host: clickhouse-clickhouse.clickhouse.svc.kubernetes.local, port: 8443; Code: 40. DB::Exception: Checksum doesn't match: corrupted data. Reference: b4cead3e25bfadff2840150300813519. Actual: 8b83bf749382c4f3039dc34e60fcafae. Size of compressed block: 1564: (while reading column lastVisibleTime): While executing MergeTreeInOrder. (CHECKSUM_DOESNT_MATCH) (version 22.6.1.1985 (official build))
`
@filimonov @den-crane  
I am stuck on this, please revert.

**Comment by tom-clickhouse** [comment]
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/38381
