### ISSUE TITLE
Deduplication in ReplicatedMergeTree by `optimize final` OR `optimize [..] deduplicate by [..]`?

### ISSUE THREAD

**Issue by manufacturist** [ClickHouse/ClickHouse#39236]
I have a ReplicatedMergeTree table with more than 1 billion records (110 GB). Currently, after inserting data into this table (once per day), we run `OPTIMIZE TABLE table FINAL`, to remove duplicates (it's how we receive data externally). This takes about 15 minutes to execute.

We are trying to optimize the time for this query by doing `OPTIMIZE TABLE table DEDUPLICATE BY primary_key_column, order_by_date` (The `order_by_column` is enforced here by clickhouse 🤷 otherwise the query is invalid). After running this, I have a query that runs every couple of seconds that checks if there are any duplicates left, from a certain point in time onwards (specified by `order_by_date`):

```sql
SELECT primary_key_column, COUNT(*) AS row_counts
FROM merged.data_raw_unmapped
WHERE order_by_date >= toDate(our_specified_date)
GROUP BY primary_key_column
HAVING row_counts > 1
LIMIT 1
SETTINGS optimize_aggregation_in_order = 1
```
^ This query is blazingly fast due to the condition & flag in settings. It runs in ~10 seconds if there are no duplicates, otherwise it short-circuits faster on the first one found.

We are using version `21.10.2.15` of ClickHouse.

1. Is this a valid approach to deduplicating by not enforcing a merge? I am aware of other solutions such as the ones mentioned here https://kb.altinity.com/altinity-kb-schema-design/row-level-deduplication/, however some of them imply heavy refactoring & we don't have time for this right now. We tested with 1k rows duplicates and it seemed to work (The effect being noticeable in ~10-60 seconds); however we are not entirely convinced of this approach as a go-to solution. We would require confirmation, since the documentation does not provide many details.
    * `If you specify DEDUPLICATE, then completely identical rows (unless by-clause is specified) will be deduplicated (all columns are compared), it makes sense only for the MergeTree engine.`
    * Can someone explain to us how this works behind the scene? Does this apply to the MergeTree family, or only to the MergeTree engine?
2. Are there any advices OR are we doing any bad practices here with this solution?
3. Would a different approach such as optimising partitions work better? I wasn't sure about this one for the following scenario:
    * We have partition A (January) & partition B (February)
    * In February we receive duplicated data that is timestamped for January
    * We call `OPTIMIZE TABLE table PARTITION A` & `OPTIMIZE TABLE table PARTITION B`
    * Our suspicion is that the merger of parts only occurs at a local, partition level, so we might still have duplicates between A & B, even though all rows in A are unique & in B as well

**Comment by alexey-milovidov** [comment]
OPTIMIZE with DEDUPLICATE is involving the merge and works very similarly to OPTIMIZE in terms of performance.
It works on a partition basis, and if you have duplicates across partitions, it will not clean it out.

Issuing a SELECT query for checking the duplicates before running OPTIMIZE DEDUPLICATE is reasonable.
It makes sense to add the partition key to GROUP BY in this query.

**Comment by manufacturist** [comment]
For future reference:
Our data is partitioned by month. When we receive data, we might receive duplicates from the previous months. We went with running `OPTIMIZE TABLE table PARTITION partition_key_by_month` for each affected month (parallel queries). Versus the `OPTIMIZE TABLE table FINAL` solution, this approach has shortened this step from 15 minutes to 1-2 minutes.

The effect of `OPTIMIZE TABLE table DEDUPLICATE` would not fire when required. It would take awhile for it to come into effect, and we are in need of deduplication as soon as the data gets in the system.

**Note** `OPTIMIZE TABLE table PARTITION partition_key_by_month` returns instantly if the partition is already optimised.
