### ISSUE TITLE
Using S3 Table Functions Exporting Data to S3 file error.

### ISSUE THREAD

**Issue by maczam** [ClickHouse/ClickHouse#39232]
**sql** 
` INSERT INTO FUNCTION s3('https://dataeye-sdk1.s3.ap-east-1.amazonaws.com/dataeye-report/11.csv.lz4', 's3_key', 's3_secret', 'CSV') SELECT * FROM bi.dw_table limit 10 ;`

**os :** 
Linux version 3.10.0-957.1.3.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) ) #1 SMP Thu Nov 29 14:49:43 UTC 2018

**error :** 
`Received exception from server (version 22.1.2):
Code: 499. DB::Exception: Received from 127.0.0.1:9000. DB::Exception: Access Denied. (S3_ERROR)`

**error log :**
`2022.07.14 14:43:58.603020 [ 1987 ] {fec1d7b6-5fab-4528-a1e5-5c3b97fc34f3} <Warning> AWSClient: AWSErrorMarshaller: Encountered AWSError 'AccessDenied': Access Denied
2022.07.14 14:43:58.603074 [ 1987 ] {fec1d7b6-5fab-4528-a1e5-5c3b97fc34f3} <Error> AWSClient: HTTP response code: 403
Resolved remote host IP address: 
Request ID: JXCCEPNXVQB9HXEY
Exception name: AccessDenied
Error message: Access Denied
7 response headers:
connection : close
content-type : application/xml
date : Thu, 14 Jul 2022 14:43:58 GMT
server : AmazonS3
transfer-encoding : chunked
x-amz-id-2 : 3eFGDyEwiFw3YGqetBOIhW7bjhlwAO6h0E8kihNqJQIcKfDok1stHcJjEXwgzlsUFShCWM4lbYk=
x-amz-request-id : JXCCEPNXVQB9HXEY
2022.07.14 14:43:58.603249 [ 1987 ] {fec1d7b6-5fab-4528-a1e5-5c3b97fc34f3} <Warning> AWSClient: If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.
2022.07.14 14:43:58.603392 [ 1987 ] {fec1d7b6-5fab-4528-a1e5-5c3b97fc34f3} <Debug> ReadBufferFromS3: Caught exception while reading S3 object. Bucket: dataeye-sdk, Key: dataeye-report/11.csv.lz4, Offset: 0, Attempt: 3, Message: Access Denied
2022.07.14 14:43:58.603576 [ 1987 ] {fec1d7b6-5fab-4528-a1e5-5c3b97fc34f3} <Error> executeQuery: Code: 499. DB::Exception: Access Denied. (S3_ERROR) (version 22.1.2.2 (official build)) (from 127.0.0.1:56075) (in query: INSERT INTO FUNCTION s3('https://dataeye-sdk1.s3.ap-east-1.amazonaws.com/dataeye-report/11.csv.lz4', 's3_key', 's3_secret', 'CSV') SELECT * FROM bi.dw_table limit 10 ;), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa82bc3a in /usr/bin/clickhouse
1. DB::ReadBufferFromS3::initialize() @ 0x133aaf58 in /usr/bin/clickhouse
2. DB::ReadBufferFromS3::nextImpl() @ 0x133a9ec7 in /usr/bin/clickhouse
3. DB::Lz4InflatingReadBuffer::nextImpl() @ 0x115939b1 in /usr/bin/clickhouse
4. DB::readSchemaFromFormat(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::optional<DB::FormatSettings> const&, std::__1::function<std::__1::unique_ptr<DB::ReadBuffer, std::__1::default_delete<DB::ReadBuffer> > ()>, std::__1::shared_ptr<DB::Context const>) @ 0x1482852d in /usr/bin/clickhouse
5. DB::StorageS3::getTableStructureFromDataImpl(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::StorageS3::ClientAuthentication const&, unsigned long, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, std::__1::optional<DB::FormatSettings> const&, std::__1::shared_ptr<DB::Context const>) @ 0x1407c750 in /usr/bin/clickhouse
6. DB::StorageS3::getTableStructureFromData(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::S3::URI const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, unsigned long, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, std::__1::optional<DB::FormatSettings> const&, std::__1::shared_ptr<DB::Context const>) @ 0x1407f777 in /usr/bin/clickhouse
7. DB::TableFunctionS3::getActualTableStructure(std::__1::shared_ptr<DB::Context const>) const @ 0x12b7f2dd in /usr/bin/clickhouse
8. DB::TableFunctionS3::executeImpl(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::ColumnsDescription) const @ 0x12b7f960 in /usr/bin/clickhouse
9. DB::ITableFunction::execute(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::ColumnsDescription, bool) const @ 0x132a96fb in /usr/bin/clickhouse
10. DB::InterpreterInsertQuery::getTable(DB::ASTInsertQuery&) @ 0x13a481d4 in /usr/bin/clickhouse
11. DB::InterpreterInsertQuery::execute() @ 0x13a4a6a9 in /usr/bin/clickhouse
12. ? @ 0x13d1324c in /usr/bin/clickhouse
13. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x13d10d55 in /usr/bin/clickhouse
14. DB::TCPHandler::runImpl() @ 0x147ee6af in /usr/bin/clickhouse
15. DB::TCPHandler::run() @ 0x148023f9 in /usr/bin/clickhouse
16. Poco::Net::TCPServerConnection::start() @ 0x1745b96f in /usr/bin/clickhouse
17. Poco::Net::TCPServerDispatcher::run() @ 0x1745ddc1 in /usr/bin/clickhouse
18. Poco::PooledThread::run() @ 0x1760ea49 in /usr/bin/clickhouse
19. Poco::ThreadImpl::runnableEntry(void*) @ 0x1760c140 in /usr/bin/clickhouse
20. start_thread @ 0x7dd5 in /usr/lib64/libpthread-2.17.so
21. __clone @ 0xfdead in /usr/lib64/libc-2.17.so

2022.07.14 14:43:58.603708 [ 1987 ] {fec1d7b6-5fab-4528-a1e5-5c3b97fc34f3} <Error> TCPHandler: Code: 499. DB::Exception: Access Denied. (S3_ERROR), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa82bc3a in /usr/bin/clickhouse
1. DB::ReadBufferFromS3::initialize() @ 0x133aaf58 in /usr/bin/clickhouse
2. DB::ReadBufferFromS3::nextImpl() @ 0x133a9ec7 in /usr/bin/clickhouse
3. DB::Lz4InflatingReadBuffer::nextImpl() @ 0x115939b1 in /usr/bin/clickhouse
4. DB::readSchemaFromFormat(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::optional<DB::FormatSettings> const&, std::__1::function<std::__1::unique_ptr<DB::ReadBuffer, std::__1::default_delete<DB::ReadBuffer> > ()>, std::__1::shared_ptr<DB::Context const>) @ 0x1482852d in /usr/bin/clickhouse
5. DB::StorageS3::getTableStructureFromDataImpl(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::StorageS3::ClientAuthentication const&, unsigned long, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, std::__1::optional<DB::FormatSettings> const&, std::__1::shared_ptr<DB::Context const>) @ 0x1407c750 in /usr/bin/clickhouse
6. DB::StorageS3::getTableStructureFromData(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::S3::URI const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, unsigned long, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, std::__1::optional<DB::FormatSettings> const&, std::__1::shared_ptr<DB::Context const>) @ 0x1407f777 in /usr/bin/clickhouse
7. DB::TableFunctionS3::getActualTableStructure(std::__1::shared_ptr<DB::Context const>) const @ 0x12b7f2dd in /usr/bin/clickhouse
8. DB::TableFunctionS3::executeImpl(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::ColumnsDescription) const @ 0x12b7f960 in /usr/bin/clickhouse
9. DB::ITableFunction::execute(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::ColumnsDescription, bool) const @ 0x132a96fb in /usr/bin/clickhouse
10. DB::InterpreterInsertQuery::getTable(DB::ASTInsertQuery&) @ 0x13a481d4 in /usr/bin/clickhouse
11. DB::InterpreterInsertQuery::execute() @ 0x13a4a6a9 in /usr/bin/clickhouse
12. ? @ 0x13d1324c in /usr/bin/clickhouse
13. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x13d10d55 in /usr/bin/clickhouse
14. DB::TCPHandler::runImpl() @ 0x147ee6af in /usr/bin/clickhouse
15. DB::TCPHandler::run() @ 0x148023f9 in /usr/bin/clickhouse
16. Poco::Net::TCPServerConnection::start() @ 0x1745b96f in /usr/bin/clickhouse
17. Poco::Net::TCPServerDispatcher::run() @ 0x1745ddc1 in /usr/bin/clickhouse
18. Poco::PooledThread::run() @ 0x1760ea49 in /usr/bin/clickhouse
19. Poco::ThreadImpl::runnableEntry(void*) @ 0x1760c140 in /usr/bin/clickhouse
20. start_thread @ 0x7dd5 in /usr/lib64/libpthread-2.17.so
21. __clone @ 0xfdead in /usr/lib64/libc-2.17.so`

**Comment by alexey-milovidov** [comment]
It means that AWS S3 denied access with the credentials which you've provided.

**Comment by alexey-milovidov** [comment]
You should configure your s3 bucket to allow access.
