### ISSUE TITLE
Insertion to S3 bucket generates lots of exceptions while parts are put to S3 successfully

### ISSUE THREAD

**Issue by ywangtht** [ClickHouse/ClickHouse#39240]
Setup:
Two storage tiers, hot(local hdd) and archive(S3).
openSSL/client configured.
disk and policy configured under storage_configuration.
move_factor 50%

Problem:
The parts can be uploaded to S3 bucket.
But I see lots of exceptions from clickhouse.err.log:

Does this indicate something wrong?

 (version 22.6.1.1985 (official build))
2022.07.14 10:55:57.007924 [ 2463528 ] {} <Error> AWSClient: HTTP response code: -1
Resolved remote host IP address:
Request ID:
Exception name:
Error message: Poco::Exception. Code: 1000, e.code() = 0, Timeout: connect timed out: 52.219.112.153:443 (version 22.6.1.1985 (official build))
0 response headers:
2022.07.14 10:55:57.007953 [ 2463528 ] {} <Warning> AWSClient: If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.
2022.07.14 10:55:57.007964 [ 2463528 ] {} <Warning> AWSClient: Request failed, now waiting 6400 ms before attempting again.
2022.07.14 10:55:57.109528 [ 2458978 ] {} <Error> AWSClient: Failed to make request to: https://my-bucket.s3.us-west-1.amazonaws.com/my-subdir/aadtuuhmtelyhzejoegyypvcipprfjbp?partNumber=9&uploadId=VWaoYvFvVoeuPA4RpyJhQcAyiuA4ICc_cpIFPLJ3eisCnqaRwqtE8D30KBHkUtQwhLQFUpuO0W0Maf0u06f0TpMvM8Hf5Kfs7zQExC3LmoJMAd_JZoQbTFKluZCW13vI: Poco::Exception. Code: 1000, e.code() = 0, Timeout, Stack trace (when copying this message, always include the lines below):

0. Poco::Net::SecureSocketImpl::mustRetry(int, Poco::Timespan&) @ 0x19d6ec41 in /usr/bin/clickhouse
1. Poco::Net::SecureSocketImpl::sendBytes(void const*, int, int) @ 0x19d6f9a2 in /usr/bin/clickhouse
2. Poco::Net::HTTPClientSession::write(char const*, long) @ 0x19d8b35d in /usr/bin/clickhouse
3. Poco::Net::HTTPFixedLengthStreamBuf::writeToDevice(char const*, long) @ 0x19d8e890 in /usr/bin/clickhouse
4. Poco::BasicBufferedStreamBuf<char, std::__1::char_traits<char>, Poco::Net::HTTPBufferAllocator>::overflow(int) @ 0x19d86131 in /usr/bin/clickhouse
5. std::__1::basic_streambuf<char, std::__1::char_traits<char> >::xsputn(char const*, long) @ 0xb88d19e in /usr/bin/clickhouse
6. std::__1::basic_ostream<char, std::__1::char_traits<char> >::write(char const*, long) @ 0xb890fcd in /usr/bin/clickhouse
7. Poco::StreamCopier::copyStream(std::__1::basic_istream<char, std::__1::char_traits<char> >&, std::__1::basic_ostream<char, std::__1::char_traits<char> >&, unsigned long) @ 0x19f68cce in /usr/bin/clickhouse
8. DB::S3::PocoHTTPClient::makeRequestInternal(Aws::Http::HttpRequest&, std::__1::shared_ptr<DB::S3::PocoHTTPResponse>&, Aws::Utils::RateLimits::RateLimiterInterface*, Aws::Utils::RateLimits::RateLimiterInterface*) const @ 0x150aed4e in /usr/bin/clickhouse
9. DB::S3::PocoHTTPClient::MakeRequest(std::__1::shared_ptr<Aws::Http::HttpRequest> const&, Aws::Utils::RateLimits::RateLimiterInterface*, Aws::Utils::RateLimits::RateLimiterInterface*) const @ 0x150ad409 in /usr/bin/clickhouse
10. Aws::Client::AWSClient::AttemptOneRequest(std::__1::shared_ptr<Aws::Http::HttpRequest> const&, Aws::AmazonWebServiceRequest const&, char const*, char const*, char const*) const @ 0x19fc1fc7 in /usr/bin/clickhouse
11. Aws::Client::AWSClient::AttemptExhaustively(Aws::Http::URI const&, Aws::AmazonWebServiceRequest const&, Aws::Http::HttpMethod, char const*, char const*, char const*) const @ 0x19fbf27e in /usr/bin/clickhouse
12. Aws::Client::AWSXMLClient::MakeRequest(Aws::Http::URI const&, Aws::AmazonWebServiceRequest const&, Aws::Http::HttpMethod, char const*, char const*, char const*) const @ 0x19fcc60d in /usr/bin/clickhouse
13. Aws::S3::S3Client::UploadPart(Aws::S3::Model::UploadPartRequest const&) const @ 0x1a0eebaa in /usr/bin/clickhouse
14. DB::WriteBufferFromS3::processUploadRequest(DB::WriteBufferFromS3::UploadPartTask&) @ 0x159c8fb2 in /usr/bin/clickhouse
15. ? @ 0x159cab40 in /usr/bin/clickhouse
16. ? @ 0x16592900 in /usr/bin/clickhouse
17. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0xb94f72a in /usr/bin/clickhouse
18. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&)::'lambda'()::operator()() @ 0xb951705 in /usr/bin/clickhouse
19. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xb94d0b7 in /usr/bin/clickhouse
20. ? @ 0xb9504dd in /usr/bin/clickhouse
21. start_thread @ 0x81cf in /usr/lib64/libpthread-2.28.so
22. __clone @ 0x39d83 in /usr/lib64/libc-2.28.so
 (version 22.6.1.1985 (official build))

**Comment by surbhiarorasehgal** [comment]
Hello

The logs here are not errors. They are trying to establish a connection here and the connection was successful after retry. This can happen a lot of times during making a connection and it should not be a problem.

As we can see from logs here that the request was succcessful and the upload is taking place.

```
Aws::Client::AWSXMLClient::MakeRequest(Aws::Http::URI const&, Aws::AmazonWebServiceRequest const&, Aws::Http::HttpMethod, char const*, char const*, char const*) const @ 0x19fcc60d in /usr/bin/clickhouse
Aws::S3::S3Client::UploadPart(Aws::S3::Model::UploadPartRequest const&) const @ 0x1a0eebaa in /usr/bin/clickhouse
```

Please verify the same from your end once and do let me know in case you face any issues.

Surbhi

**Comment by ywangtht** [comment]
Hi @surbhiarorasehgal ,
You are right. This is because I deployed ClickHouse instances in our data center instead of in AWS.
After I deployed it in AWS, everything is fine.
Thanks!
