### ISSUE TITLE
> if does not support UNION ALL,How can I merge two views

### ISSUE THREAD

**Issue by miaoyc666** [ClickHouse/ClickHouse#39246]
I try this method, but it does not work

> if does not support UNION ALL,How can I merge two views

CREATE TABLE t1()
ENGINE = MergeTree()...

CREATE MATERIALIZED VIEW `v1` TO t1
AS SELECT ...;

CREATE MATERIALIZED VIEW `v2` TO t1
AS SELECT ...;

_Originally posted by @jimmykuo in https://github.com/ClickHouse/ClickHouse/issues/17058#issuecomment-1138508221_

**Comment by miaoyc666** [comment]
v1 and v2 will have same data, but we can use t1

**Comment by surbhiarorasehgal** [comment]
Hello

As per your request you can check out the documentation for UNION ALL here https://clickhouse.com/docs/en/sql-reference/statements/select/union/.

Please check this out if it works for you.
