### ISSUE TITLE
A problem with running UPDATE for a table with subquery

### ISSUE THREAD

**Issue by woshiyega** [ClickHouse/ClickHouse#39264]
This is my query : 
alter table bdp_ck_label_crowd update account_ids = (
 select account_ids from bdp_ck_label_crowd where process_date=20220714091553 and crowd_id='101013')
where process_date=20220715084425 and crowd_id='101013';

The column `account_ids` is bitmap type. The query took long time, and I cannot kill the query. Also, I cannot query this table at all. I tried to rename table, but it but it doesn't  work. This The data in this table is very important and not backed up. How can I fix it? 

My version is 21.4.5.46.

**Comment by alexey-milovidov** [comment]
No info was provided.
