### ISSUE TITLE
clickhouse-copier Can't get data for node

### ISSUE THREAD

**Issue by Fkylwj** [ClickHouse/ClickHouse#39282]
**Version:**
ClickHouse server version 22.5.2.53 (official build).

**Run command:**
clickhouse-copier --daemon --config /etc/clickhouse-server/copier/keeper.xml --task-path /etc/clickhouse-server/copier/task --base-dir /var/log/clickhouse-server

use clickhouse-keeper (not zookeeper)

**Error:**
2022.07.16 10:28:03.012579 [ 835 ] {} <Information> SentryWriter: Sending crash reports is disabled
2022.07.16 10:28:03.012613 [ 835 ] {} <Trace> Pipe: Pipe capacity is 1.00 MiB
2022.07.16 10:28:03.103184 [ 835 ] {} <Information> : Starting ClickHouse 22.5.2.53 with revision 54462, build id: C243EBDB2954755B, PID 835
2022.07.16 10:28:03.103273 [ 835 ] {} <Information> Application: Starting clickhouse-copier (id 20220716102803_835, host_id idc1%2Dsingle%2Dch1#20220716102803_835, path /var/log/clickhouse-server/clickhouse-copier_20220716102803_835, revision 54462)
2022.07.16 10:28:03.149902 [ 835 ] {} <Trace> ZooKeeper: Initialized, hosts: idc1-single-ch1:9181
2022.07.16 10:28:03.150339 [ 835 ] {} <Debug> MemoryTracker: Peak memory usage (for query): 0.00 B.
2022.07.16 10:28:03.151443 [ 835 ] {} <Error> : virtual int DB::ClusterCopierApp::main(const std::vector<std::string> &): Code: 999. Coordination::Exception: Can't get data for node /etc/clickhouse-server/copier/task/description: node doesn't exist (No node). (KEEPER_EXCEPTION), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xb49447a in /usr/bin/clickhouse
1. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error, int) @ 0x17107d95 in /usr/bin/clickhouse
2. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error) @ 0x171080d6 in /usr/bin/clickhouse
3. zkutil::ZooKeeper::get(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Stat*, std::__1::shared_ptr<Poco::Event> const&) @ 0x17113f52 in /usr/bin/clickhouse
4. DB::ClusterCopier::reloadTaskDescription() @ 0xb5efff8 in /usr/bin/clickhouse
5. DB::ClusterCopier::init() @ 0xb5ef03e in /usr/bin/clickhouse
6. DB::ClusterCopierApp::mainImpl() @ 0xb5ec839 in /usr/bin/clickhouse
7. DB::ClusterCopierApp::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0xb5ed3dd in /usr/bin/clickhouse
8. Poco::Util::Application::run() @ 0x1b0ddd86 in /usr/bin/clickhouse
9. mainEntryClickHouseClusterCopier(int, char**) @ 0xb5ed6a0 in /usr/bin/clickhouse
10. main @ 0xb48ddda in /usr/bin/clickhouse
11. __libc_start_main @ 0x7fbaa495d083 in ?
12. _start @ 0xb25eaae in /usr/bin/clickhouse
 (version 22.5.2.53 (official build))
2022.07.16 10:28:03.151462 [ 835 ] {} <Debug> Application: Uninitializing subsystem: Logging Subsystem
2022.07.16 10:28:03.151487 [ 836 ] {} <Trace> BaseDaemon: Received signal -2
2022.07.16 10:28:03.151501 [ 836 ] {} <Information> BaseDaemon: Stop SignalListener thread

**keeper.xml**
```
<clickhouse>
    <logger>
        <level>trace</level>
        <size>100M</size>
        <count>3</count>
    </logger>

    <zookeeper>
        <node index="1">
            <host>idc1-single-ch1</host>
<!--            <port>2181</port>-->
<!--            clickhouse-keeper 端口为9181-->
            <port>9181</port>
        </node>
    </zookeeper>
</clickhouse>
```

**tasks.xml**
```
<clickhouse>
    <!-- Configuration of clusters as in an ordinary server config -->
    <remote_servers>
        <source_cluster>
            <!--
                source cluster & destination clusters accept exactly the same
                parameters as parameters for the usual Distributed table
                see https://clickhouse.com/docs/en/engines/table-engines/special/distributed/
            -->
            <shard>
                <internal_replication>false</internal_replication>
                <replica>
                    <host>idc1-single-ch1</host>
                    <port>8000</port>
                    <user>uos</user>
                    <password>Udcp2022cs</password>
                    <!--
                    <user>default</user>
                    <password>default</password>
                    <secure>1</secure>
                    -->
                </replica>
            </shard>
        </source_cluster>

        <destination_cluster>
            <shard>
                <internal_replication>false</internal_replication>
                <replica>
                    <host>idc2-single-ch1</host>
                    <port>8000</port>
                    <user>uos</user>
                    <password>Udcp2022cs</password>
                </replica>
            </shard>
        </destination_cluster>
    </remote_servers>

    <!-- How many simultaneously active workers are possible. If you run more workers superfluous workers will sleep. -->
    <max_workers>2</max_workers>

    <!-- Setting used to fetch (pull) data from source cluster tables -->
    <settings_pull>
        <readonly>1</readonly>
    </settings_pull>

    <!-- Setting used to insert (push) data to destination cluster tables -->
    <settings_push>
        <readonly>0</readonly>
    </settings_push>

    <!-- Common setting for fetch (pull) and insert (push) operations. Also, copier process context uses it.
         They are overlaid by <settings_pull/> and <settings_push/> respectively. -->
    <settings>
        <connect_timeout>3</connect_timeout>
        <!-- Sync insert is set forcibly, leave it here just in case. -->
        <insert_distributed_sync>1</insert_distributed_sync>
    </settings>

    <!-- Copying tasks description.
         You could specify several table task in the same task description (in the same ZooKeeper node), they will be performed
         sequentially.
    -->
    <tables>
        <!-- A table task, copies one table. -->
        <table_hits>
            <!-- Source cluster name (from <remote_servers/> section) and tables in it that should be copied -->
            <cluster_pull>source_cluster</cluster_pull>
            <database_pull>udcp_log_ch</database_pull>
            <table_pull>udcp_log_user_softwares</table_pull>

            <!-- Destination cluster name and tables in which the data should be inserted -->
            <cluster_push>destination_cluster</cluster_push>
            <database_push>udcp_log_ch</database_push>
            <table_push>udcp_log_user_softwares</table_push>

            <!-- Engine of destination tables.
                 If destination tables have not be created, workers create them using columns definition from source tables and engine
                 definition from here.

                 NOTE: If the first worker starts insert data and detects that destination partition is not empty then the partition will
                 be dropped and refilled, take it into account if you already have some data in destination tables. You could directly
                 specify partitions that should be copied in <enabled_partitions/>, they should be in quoted format like partition column of
                 system.parts table.
            -->
<!--            <engine>-->
<!--                ENGINE=ReplicatedMergeTree('/clickhouse/tables/{cluster}/{shard}/hits2', '{replica}')-->
<!--                PARTITION BY toMonday(date)-->
<!--                ORDER BY (CounterID, EventDate)-->
<!--            </engine>-->

            <!-- Sharding key used to insert data to destination cluster -->
<!--            <sharding_key>jumpConsistentHash(intHash64(UserID), 2)</sharding_key>-->
            <sharding_key>rand()</sharding_key>

            <!-- Optional expression that filter data while pull them from source servers -->
            <where_condition>CounterID != 0</where_condition>

            <!-- This section specifies partitions that should be copied, other partition will be ignored.
                 Partition names should have the same format as
                 partition column of system.parts table (i.e. a quoted text).
                 Since partition key of source and destination cluster could be different,
                 these partition names specify destination partitions.

                 NOTE: In spite of this section is optional (if it is not specified, all partitions will be copied),
                 it is strictly recommended to specify them explicitly.
                 If you already have some ready partitions on destination cluster they
                 will be removed at the start of the copying since they will be interpeted
                 as unfinished data from the previous copying!!!
            -->
            <enabled_partitions>
                <partition>'202207'</partition>
            </enabled_partitions>
        </table_hits>

        <!-- Next table to copy. It is not copied until previous table is copying. -->

    </tables>
</clickhouse>
```

**Comment by Fkylwj** [comment]
It is normal if using zookeeper

Before running the following command, you need to use zookeeper to create node /clickhouse/copier/task)

**Run command:**
```
clickhouse-copier --daemon --config /etc/clickhouse-server/copier/keeper.xml --task-path /clickhouse/copier/task --base-dir /var/log/clickhouse-server
```

It may be that when using zookeeper, you need to create a node (/clickhouse/copier/task) first, and clickhouse-keeper does not create a node

No instructions found for creating nodes with clickhouse-keeper  in ([docs1](https://clickhouse.com/docs/en/guides/sre/keeper/clickhouse-keeper/)) and ([docs2](https://clickhouse.com/docs/en/guides/sre/keeper/clickhouse-keeper-uuid)) and ([docs3](https://clickhouse.com/docs/en/operations/clickhouse-keeper/))

**Comment by Smelly-calf** [comment]
I have a question：both the source_cluster and the destination_cluster use clickhouse-keeper？

**Comment by Smelly-calf** [comment]
I use ClickHouse version 22.5.2.53 copier to transfer data from two clusters, and it's success.
Maybe you need create the description node on clickhouse-keeper, which content is the tasks.xml. Because I do this.

**Comment by 207214** [comment]
@Fkylwj  , hello, have you solved it? Have the same error when running clickhouse-copier. Also using clickhouse-keeper

**Comment by Fkylwj** [comment]
> the question here is：both the source_cluster and the destination_cluster using clickhouse-keeper？

both using clickhouse-keeper

**Comment by Fkylwj** [comment]
> I use ClickHouse server version 22.5.2.53 and I use clickhouse-keeper. Mine copier working, the data of the source cluster was transfered successfully to the destination cluster.
> 
> Maybe you need create the description node on clickhouse-keeper, which content is the tasks.xml. Because I do this.

I don't know how to create the description node on clickhouse-keeper;
no instructions found for creating nodes with clickhouse-keeper in ([docs1](https://clickhouse.com/docs/en/guides/sre/keeper/clickhouse-keeper/)) and ([docs2](https://clickhouse.com/docs/en/guides/sre/keeper/clickhouse-keeper-uuid)) and ([docs3](https://clickhouse.com/docs/en/operations/clickhouse-keeper/))
Can you tell me how to do it? Or are you using version 22.6?

ClickHouse server version [22.6](https://clickhouse.com/docs/en/whats-new/changelog/) support INSERTs into system.zookeeper table, which is equivalent to creating nodes with clickhouse-keeper.

**Comment by Fkylwj** [comment]
> @Fkylwj , hello, have you solved it? Have the same error when running clickhouse-copier. Also using clickhouse-keeper

I have solved it.
ClickHouse server version [22.6](https://clickhouse.com/docs/en/whats-new/changelog/) support INSERTs into system.zookeeper table, which is equivalent to creating nodes with clickhouse-keeper.

using sql like this:
`insert into system.zookeeper (name, path, value) values ('description', '/clickhouse/copier', '$(/etc/clickhouse-copier/tasks.xml)')`
The value field is the specific content of the tasks.xml file; **attention**: there are many special characters that are not supported, such as single quotes.
The path field is the clickhouse-copier node.
