### ISSUE TITLE
modulo function behavior doesn't match description

### ISSUE THREAD

**Issue by MaceWindu** [ClickHouse/ClickHouse#39287]
https://clickhouse.com/docs/en/sql-reference/functions/arithmetic-functions/#moduloa-b-a--b-operator

**modulo(a, b), a % b operator**
`
Calculates the remainder after division. If arguments are floating-point numbers, they are pre-converted to integers by dropping the decimal portion. The remainder is taken in the same sense as in C++. Truncated division is used for negative numbers. An exception is thrown when dividing by zero or when dividing a minimal negative number by minus one.
`

```sql
select 11.5::Float64 % 3.5::Float64
--
1

-- truncate decimal portion as in description:
11.0::Float64 % 3.0::Float64
--
2
```

**Comment by evillique** [comment]
It looks like the documentation is wrong here because ClickHouse modulo operator behavior with floating-point numbers seems to be similar to e.g. Python. For example:

``` sql
SELECT 9.2 % 2.3

┌─modulo(9.2, 2.3)─┐
│                0 │
└──────────────────┘

SELECT 9.2 % 2.0

┌────modulo(9.2, 2.)─┐
│ 1.1999999999999993 │
└────────────────────┘
```

```
>>> 9.2 % 2.3
0.0

>>> 9.2 % 2.0
1.1999999999999993
```
