### ISSUE TITLE
DB::Exception: Maximum distributed depth exceeded

### ISSUE THREAD

**Issue by MouflinGuillaume** [ClickHouse/ClickHouse#39284]
Hi everybody,

I use clickhouse cluster with zookeeper. I setup my cluster with remote servers, config users and config zookeeper but I have this error when I create a table on my cluster : 

```
DB::Exception: Maximum distributed depth exceeded. Stack trace:

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xb8a20fa in /usr/bin/clickhouse
1. DB::DistributedSink::DistributedSink(std::__1::shared_ptr<DB::Context const>, DB::StorageDistributed&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::Cluster> const&, bool, unsigned long, DB::StorageID, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x16ab5afa in /usr/bin/clickhouse
2. DB::StorageDistributed::write(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::Context const>) @ 0x1679e950 in /usr/bin/clickhouse
3. DB::buildPushingToViewsChain(std::__1::shared_ptr<DB::IStorage> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::Context const>, std::__1::shared_ptr<DB::IAST> const&, bool, DB::ThreadStatus*, std::__1::atomic<unsigned long>*, DB::Block const&) @ 0x173e5683 in /usr/bin/clickhouse
4. DB::InterpreterInsertQuery::buildChainImpl(std::__1::shared_ptr<DB::IStorage> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::Block const&, DB::ThreadStatus*, std::__1::atomic<unsigned long>*) @ 0x16223432 in /usr/bin/clickhouse
5. DB::InterpreterInsertQuery::execute() @ 0x16227501 in /usr/bin/clickhouse
6. ? @ 0x16562276 in /usr/bin/clickhouse
7. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x1655fa95 in /usr/bin/clickhouse
8. DB::TCPHandler::runImpl() @ 0x171424fa in /usr/bin/clickhouse
9. DB::TCPHandler::run() @ 0x17154ab9 in /usr/bin/clickhouse
10. Poco::Net::TCPServerConnection::start() @ 0x19dbd2d3 in /usr/bin/clickhouse
11. Poco::Net::TCPServerDispatcher::run() @ 0x19dbe651 in /usr/bin/clickhouse
12. Poco::PooledThread::run() @ 0x19f6f91b in /usr/bin/clickhouse
13. Poco::ThreadImpl::runnableEntry(void*) @ 0x19f6d020 in /usr/bin/clickhouse
14. start_thread @ 0x8ea7 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
15. clone @ 0xfddef in /usr/lib/x86_64-linux-gnu/libc-2.31.so
: While sending /var/lib/clickhouse/store/5f1/5f12ada8-0cd5-4e71-be11-b1e63b46f4c1/shard1_all_replicas/1446.bin. (TOO_LARGE_DISTRIBUTED_DEPTH)

```

My two remote servers contact each other. I can use the cli clickhouse-client with the host of each server like this `clickhouse-client -h myIpServer`. My connection is successfully.

When I run this request on my first server: 
`SELECT * FROM system.clusters LIMIT 2` 

My result is : 
`
┌─cluster─┬─shard_num─┬─shard_weight─┬─replica_num─┬─host_name─────┬─host_address──┬─port─┬─is_local─┬─user────┬─default_database─┬─errors_count─┬─slowdowns_count─┬─estimated_recovery_time─┐
│ cluster_test │         1 │            1 │           1 │ myFirstIpPublicServer │ myFirstIpPublicServer │ 9000 │        0 │ default │                  │            0 │               0 │                       0 │
│ cluster_test │         1 │            1 │           2 │ mySecondIpPublicServer │ mySecondIpPublicServer │ 9000 │        0 │ default │                  │            0 │               0 │                       0 │
└─────────`

I don't understand why on my first server, this result has not is_local to true. I saw on the code of clickhouse, the variable is_local is set to true if this is a local IP address looks like 127.0.0.1. But how tell this is my local server on my first server ? 

I think it's about the definition of hosts on /etc/hosts but I'm not sure and I don't kown what I must write. 

**How to reproduce**
ClickHouse server version 22.6.3.35 (official build).
This is my remote-servers.xml : 
`<clickhouse>
  <remote_servers>
    <cluster_test>
        <shard>
          <internal_replication>true</internal_replication>
          <replica>
            <host>myFirstIpPublicServer</host>
            <port>9000</port>
          </replica>
          <replica>
            <host>mySecondIpPublicServer</host>
            <port>9000</port>
          </replica>
      </shard>
    </cluster_test>
  </remote_servers>
</clickhouse>`

This is my zookeeper.xml : 
`<clickhouse>
  <zookeeper>
    <node>
      <host>myFirstIpPublicServer</node>
      <port>2181</port>
    </node>
    <node>
      <host>mySecondIpPublicServer</node>
      <port>2181</port>
    </node>
  </zookeeper>
</clickhouse>
`

This is my macros.xml on my first server : 
`<clickhouse>
  <macros>
    <cluster>cluster_test</cluster>
    <shard>1</shard>
    <replica>myFirstIpPublicAddress</replica>
  </macros>
</clickhouse>`

I use `<listen_host>0.0.0.0</listen_host>` in config.xml

This is my request I launch on the first server and failed with Maximum distributed depth exceeded : 
`CREATE TABLE test ON CLUSTER '{cluster}'
                                              (
                                                  timestamp DateTime,
                                                  contractid UInt32,
                                                  userid UInt32
                                              ) ENGINE = ReplicatedMergeTree('/clickhouse/tables/{cluster}/{shard}/default/test', '{replica}')
                                              PARTITION BY toYYYYMM(timestamp)
                                              ORDER BY (contractid, toDate(timestamp), userid)
                                              SAMPLE BY userid`
**Expected behavior**
I would like my request creates the table test on the cluster

@alexey-milovidov

**Comment by puduan** [comment]
Please check your distributed table create SQL, it might be your distributed table is based on itself instead of local table.
