### ISSUE TITLE
Overhead of multiple EUDF calls 

### ISSUE THREAD

**Issue by jcuenod** [ClickHouse/ClickHouse#39291]
**Describe the situation**
 I have a python `UDF` (that reads `ROWBINARY` input) that runs on a set of aggregate function results to further filter them. I use `VIEW` to process those aggregates before passing the data into my UDF (i.e., `SELECT * FROM VIEW(SELECT FROM <aggregate functions>...) WHERE my_udf(...)`). I expected `VIEW` to cause the UDF to be called once but in some cases it gets called multiple times.

Testing my python function on a full set of rows from the `VIEW`, I could get results in 250ms. But when called hundreds of times, the performance goes down to the tens of seconds. I rewrote the function in rust, which significantly improves the situation but it still gets called hundreds of times. This inevitably degrades performance.

Let me know what other information would be pertinent to add to this issue.

**Comment by kitaisreal** [comment]
@jcuenod could you please provide simplified reproducible example ? EUDF with `executable` type must be called for each block, that can be significant. On the other hand EUDF with type `executable_pool` can do the job. ClickHouse will run pool of processes and will reuse them.

**Comment by jcuenod** [comment]
Thanks, I'm trying out executable pools, that may be the solution I was looking for but I need to benchmark a bit more.
