### ISSUE TITLE
Cross-version upgrade

### ISSUE THREAD

**Issue by mofei920** [ClickHouse/ClickHouse#39294]
I want to upgrade cluster from v21.8.9.13-lts to latest lts v22.3.8.39-lts directly, are there any problems?
or it's necessary upgrade to latest v21 lts version v21.8.15.7-lts first, then upgrade to v22.3.8.39-lts?

**Comment by alexey-milovidov** [comment]
You can upgrade directly to the latest version. No intermediate steps are needed.

About the potential problems, you can pay attention to the release notes in the changelog like "Backward Incompatible Change":
https://github.com/ClickHouse/ClickHouse/blob/master/CHANGELOG.md
