### ISSUE TITLE
[MySQL Interface] Nullable type reported as string to client

### ISSUE THREAD

**Issue by MaceWindu** [ClickHouse/ClickHouse#39297]
version: `22.6.3.35`

For `Float32` column server reports `FLOAT` type, but for `Nullable(Float32)` it returns `CHAR(0)`.

Same for `Float64`: `FLOAT` vs `CHAR(0)`

**Comment by MaceWindu** [comment]
Actually it is also for other types. Not checked all, but e.g. `Date` is affected

**Comment by JTMosaic** [comment]
This is still an issue in 22.9.2.7 for MySQL (5.7.30) **decimal** type which becomes **String** in CH

**Comment by zzsmdfj** [comment]
`set mysql_datatypes_support_level = 'decimal';` will see correctly decimal type.

don't see many advantages when char(1) became FixedString(1)

**Comment by slvrtrn** [comment]
There were fixes to Nullable/LowCardinality columns reporting in #54115, [this line](https://github.com/ClickHouse/ClickHouse/pull/54115/files#diff-a0d1e11afc0e80db3ef9e542d4589bb86109206fc08c47348ab52e8bf1971600R145) in particular.

For example:

```sql
CREATE TABLE f
(
    `f1` Float32,
    `f2` Nullable(Float32),
    `f3` LowCardinality(Nullable(Float32))
)
ENGINE = Memory

```

Having the following in the `users.xml` file:
```
  <profiles>
    <default>
      <use_mysql_types_in_show_columns>1</use_mysql_types_in_show_columns>
    </default>
  </profiles>
```

MySQL client prints:
```
mysql> show full columns from f;
+-------+-------+------+------+---------+-------+-----------+---------+------------+
| field | type  | null | key  | default | extra | collation | comment | privileges |
+-------+-------+------+------+---------+-------+-----------+---------+------------+
| f1    | FLOAT | NO   |      | NULL    |       | NULL      |         |            |
| f2    | FLOAT | NO   |      | NULL    |       | NULL      |         |            |
| f3    | FLOAT | NO   |      | NULL    |       | NULL      |         |            |
+-------+-------+------+------+---------+-------+-----------+---------+------------+
```

Column definition was also tested for a few other types ([sql](https://github.com/ClickHouse/ClickHouse/blob/44e1f6b53d7822330902af7ab524ce26be58793e/tests/integration/test_mysql_protocol/prepared_statements_test.sql#L43-L52), [reference](https://github.com/ClickHouse/ClickHouse/blob/e31cfdefa7fd9315a9ec27e884ca8d690710eb69/tests/integration/test_mysql_protocol/prepared_statements.reference#L47-L55)).

Can you please confirm if this is still an issue?

**Comment by rschu1ze** [comment]
> (it is a bit weird that null is NO for f2, though).

Known glitch: https://github.com/ClickHouse/ClickHouse/blob/28e2ebf9db0671816d4e13154b8167fc5e31be89/src/Interpreters/InterpreterShowColumnsQuery.cpp#L45

**Comment by MaceWindu** [comment]
@slvrtrn, I will check tomorrow.
Issue not about types reported in table shema, but about column types reported in data set when data sent to client.
E.g.
```sql
select 1::Float32, 1::Nullable(Float32)
```
was sent to client as float and string columns

**Comment by slvrtrn** [comment]
@MaceWindu, please check. I think it should work as expected now (this is confirmed by the tests with the JDBC driver).

**Comment by slvrtrn** [comment]
@MaceWindu, thanks. 

This is odd cause we have [this particular bit](https://github.com/ClickHouse/ClickHouse/blob/master/src/Core/MySQL/PacketsProtocolText.cpp#L144-L145) to handle Nullable/LowCardinality combinations.

I will look into it.
