### ISSUE TITLE
Permission denied for `tmp-fetch` dir

### ISSUE THREAD

**Issue by Ac-Rush** [ClickHouse/ClickHouse#39309]
> You have to provide the following information whenever possible.

one replication is keeping throw error: std::exception. Code: 1001, type: std::__1::__fs::filesystem::filesystem_error, e.what() = filesystem error: in weakly_canonical: Permission denied [store/838/838b0e91-39cc-4c8e-baee-25a86099df1b/tmp-fetch_202207_13173_13789_299/checksums.txt]\nCannot print extra info for Poco::Exception (version 22.3.3.44 (official build))

But the ClickHouse should write the data to **/var/lib/clickhouse/store** instead. After I deleted/recreated that pod, the pod automatically recovered the data.

**Comment by tavplubix** [comment]
It's definitely not related to replication, but may be related to #38265.
Please share relevant server logs. For example, the following can be useful:
```
zgrep -Fa "838b0e91-39cc-4c8e-baee-25a86099df1b" /var/log/clickhouse-server.* > log.txt
```

**Comment by tavplubix** [comment]
> may be related to https://github.com/ClickHouse/ClickHouse/pull/38265

Hm, no, it may not. Your version is 22.3.3.44 and it does not have this feature. So probably it's some kind of misconfiguration.

**Comment by Ac-Rush** [comment]
> > may be related to #38265
> 
> Hm, no, it may not. Your version is 22.3.3.44 and it does not have this feature. So probably it's some kind of misconfiguration.
Thanks, we haven't changed any settings, we use Clickhouse-Operator. Our service runs will for months, but suddenly has this issue in only one CH instance(K8S pod). I resolved this issue by deleting the Pod, with no config change.

**Comment by den-crane** [comment]
it could be that a filesystem was automatically remounted as readonly by the kernel because an issue with a block storage.

**Comment by den-crane** [comment]
https://www.mail-archive.com/llvm-bugs@lists.llvm.org/msg49365.html
