### ISSUE TITLE
Proper add/substract to dates

### ISSUE THREAD

**Issue by simPod** [ClickHouse/ClickHouse#3931]
Today I tried something similar:

```sql
SELECT now() + 60 * 60 * 24
```

To my suprise, it worked and even the result is of type DateTime `select toTypeName(now() + 60 * 60 * 24)` -> `DateTime` 👏 

However, I wondered that it would be better to comply with more common ways how to handle working with dates additions/substractions like `select now() + INTERVAL '1 day'`

What do you think?

**Comment by alesapin** [comment]
Yes, this way is also supported:
``` 
 :) select now() + INTERVAL 1 day

SELECT now() + toIntervalDay(1)

┌─plus(now(), toIntervalDay(1))─┐
│           2018-12-27 18:18:16 │
└───────────────────────────────┘

1 rows in set. Elapsed: 0.006 sec. 

```

**Comment by alexey-milovidov** [comment]
Note that `now() + 60 * 60 * 24` does not respect clock adjustments (example: daylight saving time).
And the `INTERVAL` syntax or `addDays` function is always preferred.

**Comment by simPod** [comment]
Also, not sure about the convention used here, it seems to be similar to MySQL? Is there a way to mix units like in Postgres eg.? Something like `24 hours 1 seconds`

Tried `NOW() - INTERVAL 24 HOUR - INTERVAL 1 SECOND`. As it seems to call underlying _minus_ function 
> Wrong argument types for function minus: if one argument is Interval, then another must be Date or DateTime

I also tried `(NOW() - INTERVAL 24 HOUR) - 1` 

I though that putting parenthesis there would call minus twice. Didn't find a way tho.

**Comment by simPod** [comment]
@blinkov yes, in [Postgres](https://wiki.postgresql.org/wiki/Working_with_Dates_and_Times_in_PostgreSQL#3._You_may_add_or_subtract_two_INTERVALS). Also [Oracle](https://oracle-base.com/articles/misc/oracle-dates-timestamps-and-intervals#interval) but that is slightly different.

**Comment by blinkov** [comment]
@simPod thanks. Actually, they look significantly different and incompatible with each other.

**Comment by alexey-milovidov** [comment]
Ok. We can implement addition of intervals of different kinds as "external" addition in "direct product" of kinds, resulting in Tuple of Interval types.

In Postgres it works slightly different: https://www.db-fiddle.com/f/8hpz64orQDo76HhD2a4Asw/0

**Comment by alexey-milovidov** [comment]
At least Postgres works correctly with respect to time zone adjustments:
https://www.db-fiddle.com/f/x99vPcZa9QFJhhzjAbb5Jh/1

**Comment by alexey-milovidov** [comment]
This task to be reassigned when the time will come.

**Comment by olgarev** [comment]
Internal documentation ticket DOCSUP-9861

**Comment by DanRoscigno** [comment]
closed by https://github.com/ClickHouse/ClickHouse/pull/25236
