### ISSUE TITLE
Union all for a lot of tables

### ISSUE THREAD

**Issue by Andrey250419** [ClickHouse/ClickHouse#39319]
Hello, I have a set of tables (about 100) in schema named qgep and which names start with t_. They have all the same columns (colA, colB, colC). What I'd like to do is to get one big table which is the union of all my t_* tables?

**Comment by den-crane** [comment]
https://clickhouse.com/docs/en/engines/table-engines/special/merge

Merge Table Engine

```sql

CREATE TABLE ... Engine=Merge(qgep, 't_.*')

```
