### ISSUE TITLE
Obsolete Yandex repository is still abailable, but not updated (and it's really confusing)

### ISSUE THREAD

**Issue by tavplubix** [ClickHouse/ClickHouse#39358]
ClickHouse packages are still available in Yandex repository (https://repo.yandex.ru/clickhouse/), but this repository is not updated for about half a year, it does not contain new versions (the latest available version is 22.2.2.1). Moreover, this repo is available as https://repo.clickhouse.com/ that can be easily confused with official ClickHouse repo (https://packages.clickhouse.com/). Some users think that there are no versions newer then 22.2 at all (https://github.com/ClickHouse/ClickHouse/issues/39279#issuecomment-1187841591) and cannot upgrade. 

Does it make sense to completely disable this repo? It does not work anyway, but disabling it will make users to move to new official ClickHouse repo.

cc: @Felixoid, @alesapin

**Comment by Felixoid** [comment]
I think we're ready to disable repo.clickhouse.com. We are almost a half year away from migration and can disable it. It was there because we wanted to have a graceful period, but have had to enforce pushing only to artifactory.

Although https://repo.yandex.ru/clickhouse/ is rather out of our scope. If one uses it, there's nothing I'd do about it.

**Comment by filimonov** [comment]
Can you move old releases to new repo first?

Why? 

- I know big setups still using very old versions. They need to have some reference repo. 
- sometimes i need to install symbols package for old versions
- Sometimes i do some version archeology, or even do bisect using testing releases.
- just historical reasons

**Comment by filimonov** [comment]
But I'm also ok with renaming old one to repo-old.clickhouse.com or similar

**Comment by tavplubix** [comment]
> Although https://repo.yandex.ru/clickhouse/ is rather out of our scope. If one uses it, there's nothing I'd do about it.

Maybe we can ask Yandex to remove ClickHouse packages from it.

> Can you move all old releases to new repo first?

Of course we cannot just disable old repo, we have to move old packages somewhere first (I though we already have old packages in new repo). We should not loose old packages even with version 1.x

**Comment by Felixoid** [comment]
We haven't plans to move anything older than 2021

**Comment by filimonov** [comment]
> We haven't plans to move anything older than 2021

In that case you need to preserve old repo somehow.

**Comment by Felixoid** [comment]
It's a good topic for daily flame-sync-meeting, but the plan was to have repo.clickhouse.com as is, and have updating packages.clickhouse.com.

We can just clone the whole repo.yandex.net/clickhouse to S3/r2 cheap slow public bucket and have cloudflare on top of it as it was now, for sure. But there is no intent to have everything moved to artifactory. It would be too expensive

**Comment by Felixoid** [comment]
I didn't update the ticket, but we have moved the repository to https://packages.clickhouse.com/repo-archive/

**Comment by alexey-milovidov** [comment]
Fixed.

**Comment by alexey-milovidov** [comment]
Support contact in case of any troubles: https://t.me/AndreyGodin

**Comment by tavplubix** [comment]
https://repo.yandex.ru/clickhouse/ still contains ClickHouse packages

**Comment by alexey-milovidov** [comment]
@tavplubix it is not a problem as long as it is a proper, updated mirror.
