### ISSUE TITLE
`Session is locked by a concurrent client` with `FORMAT RowBinary` inserts

### ISSUE THREAD

**Issue by MaceWindu** [ClickHouse/ClickHouse#39374]
version: `22.6.3.35`

HTTP client with session support fails with `SESSION_IS_LOCKED` error when it performs many `INSERT ... FORMAT RowBinary` queries over same connection (around ~200-3000 inserts, looks like it depends on overall resources load).

Client code: https://github.com/DarkWanderer/ClickHouse.Client/blob/master/ClickHouse.Client/Copy/ClickHouseBulkCopy.cs#L153

Client issue: https://github.com/DarkWanderer/ClickHouse.Client/issues/152

**Comment by tavplubix** [comment]
It's how it works. `SESSION_IS_LOCKED` literally means that session is locked by concurrent query. You have to either wait for that query to finish or use separate session with different session id.

**Comment by MaceWindu** [comment]
But it works for plain insert without RowBinary and server configured with `mutations_sync = 1`

**Comment by MaceWindu** [comment]
Also where you see that there is no wait? it's not true

**Comment by tavplubix** [comment]
> Also where you see that there is no wait? it's not true

I don't know what is `DarkWanderer` and how does it work, I only know that `SESSION_IS_LOCKED` is thrown on concurrent query with the same session id. Probably there's a bug in `DarkWanderer`. If you think that it's a bug in ClickHouse, then provide a reproducible example please. It may be a script on `bash` that run `curl`/`wget` or script on `python` using `requests` or other simple library.

**Comment by MaceWindu** [comment]
Hmm, maybe you are right about wait. I see in client code that for regular queries there is additional read from response, missing in RowBinary code

https://github.com/DarkWanderer/ClickHouse.Client/blob/master/ClickHouse.Client/ADO/ClickHouseCommand.cs#L71

I will close it for now.
