### ISSUE TITLE
Clickhouse ReplicatedAggregatingMergeTree engine incorrect result vs AggregatingMergeTree engine

### ISSUE THREAD

**Issue by li1234yun** [ClickHouse/ClickHouse#39409]
Hello! 

**Describe the unexpected behaviour**
When I use AggregatingMergeTree engine at my local ck server, the MATERIALIZED VIEW has the correct result based on the select statement. But I always got wrong result at ReplicatedAggregatingMergeTree clickhouse cluster.

**How to reproduce**
* Which ClickHouse server version to use
ClickHouse server version 22.2.3.1.

* Which interface to use, if matters
AggregatingMergeTree  => ReplicatedAggregatingMergeTree

* Non-default settings, if any
Except password

* `CREATE TABLE` statements for all tables involved

```sql
CREATE TABLE IF NOT EXISTS report.idl_access_local ON CLUSTER report_cluster
(
    a String,
    b String,
    c String,
    hour Int64
) ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/idl_access_local', '{replica}')
      PARTITION BY hour
      ORDER BY (a, b, c)
      TTL timestamp + INTERVAL 3 DAY;


CREATE TABLE report.idl_access ON CLUSTER report_cluster AS report.idl_access_local
ENGINE = Distributed(report_cluster, report, idl_access_local, rand());

CREATE MATERIALIZED VIEW report.idl_access_view_local
            ON CLUSTER report_cluster
            ENGINE = ReplicatedAggregatingMergeTree('/clickhouse/tables/{shard}/idl_access_view', '{replica}')
                PARTITION BY (hour)
                ORDER BY (hour, a, b)
AS
SELECT hour, a, b, countState() as cnt_state
FROM report.idl_access
WHERE a != '-'
  AND NOT endsWith(a, '_WHITE')
GROUP BY hour, a, b;

CREATE TABLE report.cdl_attack_type ON CLUSTER report_cluster AS report.idl_access_view
ENGINE = Distributed(report_cluster, report, idl_access_view, rand());
```

* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
None

* Queries to run that lead to unexpected result

I run the `select statement` sql, I always got the correct result. I got right MATERIALIZED VIEW result on my local single ck server, but I got wrong result 1 on my ck cluster.

**Expected behavior**

I should get the same result when I use ck single server or ck cluster.

```sql
SELECT hour, a, b, count()
FROM report.idl_access
WHERE a != '-'
  AND NOT endsWith(a, '_WHITE')
GROUP BY hour, a, b;
```
I got right result.

```sql
select hour, a, b, countMerge(cnt_state) from report.cdl_attack_type group by hour, a, b;
```

I always got 1

**Error message and/or stacktrace**
None

**Additional context**
None

**Comment by den-crane** [comment]
22.2 is out support. I suggest to upgrade to 22.6

**Comment by den-crane** [comment]
no info / no repro

**Comment by li1234yun** [comment]
Thank you! @den-crane 

I'm sorry for that I don't reply you. I just try and It seems not work. I will try later again.

**Comment by li1234yun** [comment]
Thank you! @den-crane 

I dropped my database on the cluster and I recreate it. It works now! Thanks!
