### ISSUE TITLE
Please provide some pointers on configuring QtCreator to build ClickHouse

### ISSUE THREAD

**Issue by dheeraj-326** [ClickHouse/ClickHouse#39406]
It will be very helpful if someone can give me some pointers/docs as to how to configure Clickhouse in QtCreator so that it parses and builds correctly.

**Comment by evillique** [comment]
I have not seen any instructions on how to do it in QtCreator and do not have any experience with it myself, but maybe CLion instruction will give you some insight on how to do it similarly in QtCreator: https://github.com/ClickHouse/ClickHouse/issues/34736

**Comment by Enmk** [comment]
@dheeraj-326 what platform are you on? What are compiler/cmake/ninja versions?

**Comment by dheeraj-326** [comment]
> @dheeraj-326 what platform are you on? What are compiler/cmake/ninja versions?

I am on a Mac Monterey 12.2.1 and using cmake 3.23.2, ninja 1.11.0 and clang 14.0.6. Clang is installed with brew but the default one on the path is 13.1.6. I am using the brew installed clang for command line builds.
