### ISSUE TITLE
Clickhouse analogue function

### ISSUE THREAD

**Issue by bilelik** [ClickHouse/ClickHouse#39407]
What will be the analogue of function DAYOFWEEK( date_format(b.createdon_date, '%Y-01-06'))? 

And also I need help to know how to start the week not from monday or sunday but from Thursday on clickhouse?

**Comment by evillique** [comment]
1. Considering Monday is 1, and Sunday is 7:
`DAYOFWEEK(toDateTime(formatDateTime(date, '%Y-01-06')))`

2. If we only need to change the day of the week:
`(DAYOFWEEK(date) + 3) % 7 + 1`
```
WITH today() + number AS date
SELECT
    date,
    DAYOFWEEK(date) AS old,
    ((DAYOFWEEK(date) + 3) % 7) + 1 AS new
FROM numbers(7)

Query id: 840ca0cb-9176-4ea0-a4f6-e319a9c58a8b

┌───────date─┬─old─┬─new─┐
│ 2022-07-20 │   3 │   7 │
│ 2022-07-21 │   4 │   1 │
│ 2022-07-22 │   5 │   2 │
│ 2022-07-23 │   6 │   3 │
│ 2022-07-24 │   7 │   4 │
│ 2022-07-25 │   1 │   5 │
│ 2022-07-26 │   2 │   6 │
└────────────┴─────┴─────┘
```
