### ISSUE TITLE
Question: What is the status of enable_optimize_predicate_expression ?

### ISSUE THREAD

**Issue by TH-HA** [ClickHouse/ClickHouse#3942]
Hello 
This setting is still deactivated by default due to a few bugs. 
We have made a few test and in certain context, activating the setting allow us to gain a factor of  100 ( 2.3 sec vs 0.026 sec) on views and in some case a factor 20 on complex group by ( I also don't speak about the memory usage which is much lower in our use case. We are oblige to activate the external sort/group by when this parameters is not set).  

Do you have an ETA on this feature ? Do you plan to release it soon as the gain is really huge and view are a key point for us to expose our data to third party tools ( which are not supporting the full Clickhouse sql syntax - such as dictionaries , states , arrays ). 

Thanks

**Comment by zhang2014** [comment]
I've been tracking the feedback on this setting (there doesn't seem to be a lot of problems right now : ) #3885),  this is a reply from @alexey-milovidov : https://github.com/yandex/ClickHouse/pull/2929#issuecomment-415650398

**Comment by den-crane** [comment]
enable_optimize_predicate_expression enabled by default
