### ISSUE TITLE
When does CH check table estimation for using 'explain estimate' 

### ISSUE THREAD

**Issue by chu1070y** [ClickHouse/ClickHouse#39438]
Hello,

I am checking whether we can use 'explain estimate' or not.

I think It seems that CH takes a long time to get estimation for tables.
so, Most of my tables has no results for 'explain estimate'...

I wonder when CH estimate tables. or Does it have period for checking? or Is there any configuration for this?

**Comment by den-crane** [comment]
`explain estimate` works only for queries to mergetree tables.

It analyzes the estimation when you run it. There is no delay. It works instantly.
