### ISSUE TITLE
COUNT(*) over array join yields incorrect result

### ISSUE THREAD

**Issue by jiacheng-celonis** [ClickHouse/ClickHouse#39431]
**Describe the unexpected behaviour**

COUNT(*)  over array join yields incorrect result.

**How to reproduce**
* Which ClickHouse server version to use

`ClickHouse server version 22.3.7 revision 54455`

* Which interface to use, if matters

`clienthouse-client CLI (client version 22.3.7.28 (official build))`

* `CREATE TABLE` statements for all tables involved

```create table t(`id` UInt32) ENGINE = MergeTree ORDER BY id;```

* Sample data for all these tables, use [clickhouse-obfuscator]

```insert into t (`id`) VALUES (1);```

* Queries to run that lead to unexpected result

```select count(*) from `t` ARRAY JOIN range(2) AS a;```

```select count(*) from `t` ARRAY JOIN [0,1] AS a;```

```select count(a) from `t` ARRAY JOIN range(2) AS a;```

```select count(a) from `t` ARRAY JOIN [0,1] AS a;```

**Expected behavior**

Expect queries above to return 2 rows, but they only return 1 row. Changing `count(*)` to `count(t.id)` returns the correct row count of 2.

**Comment by den-crane** [comment]
```sql

set optimize_trivial_count_query=0;
select count(*) from `t` ARRAY JOIN range(2) AS a;
┌─count()─┐
│       2 │
└─────────┘

set optimize_trivial_count_query=1;
select count(*) from `t` ARRAY JOIN range(2) AS a;
┌─count()─┐
│       1 │
└─────────┘
```

@amosbird

**Comment by den-crane** [comment]
fix reverted
