### ISSUE TITLE
Enhance `implicit_transaction` setting to support read-uncommitted isolation level

### ISSUE THREAD

**Issue by zhicwu** [ClickHouse/ClickHouse#39435]
**Use case**

JDBC driver supports auto commit(implicitly uses one transaction for each query), and it allows user to change transaction isolation level as needed at connection level, for examples:

```java
// auto commit
conn.setAutoCommit(true);
try (Statement stmt = conn.createStatement()) {
  stmt.executeUpdate("insert into mytable values(1)");
}

// manual
conn.setAutoCommit(false);
try (Statement stmt = conn.createStatement()) {
  stmt.executeUpdate("insert into table1 values(2)");
  stmt.executeUpdate("insert into table2 values(3)");
}
conn.commit();

// change transaction isolation level
conn.setTransactionIsolation(Connection.TRANSACTION_READ_UNCOMMITTED);
try (Statement stmt = conn.createStatement()) {
  stmt.executeQuery("select * from table1");
}
```

As far as I know, ClickHouse supports two transaction isolation levels: read-committed and read-uncommitted. The former one is default for all transactions, and it can be changed to the latter by issue `set transaction snapshot 3`. And uncommitted data is visible for all non-transactional queries on the same node.

[implicit_transaction](../pull/38344) is a great feature as it reduces unnecessary network calls between client and server for single queries. However, it only supports read-committed.

**Describe the solution you'd like**

Enhance `implicit_transaction` setting to support read-uncommitted isolation level, for example:
`0` - no transaction
`1` - implicit transaction (read-committed)
`2` - implicit transaction (read-uncommitted)

**Describe alternatives you've considered**

Perhaps it's better to introduce a new setting like `implicit_transaction_isolation_level` or `implicit_transaction_snapshot` to customize snapshot as needed.

**Additional context**

N/A

**Comment by Algunenano** [comment]
> Enhance implicit_transaction setting to support read-uncommitted isolation level, for example:

I guess this could be applied to any transaction, not only the implicit ones right? If so I'd think of having something like `transaction_isolation` to select the level of any transaction.

What's the use case for being able to have uncommitted reads with implicit transactions? I can only think of scenarios where you are doing an insert with materialized views that include JOINs and you don't care about which data gets used in those views. Or maybe this setting makes more sense once replication is supported and you want to decide whether to wait for the data committed by other replicas or not. Just curious.

**Comment by tavplubix** [comment]
> As far as I know, ClickHouse supports two transaction isolation levels: read-committed and read-uncommitted.

It's not true, for now ClickHouse supports only one isolation level: Snapshot Isolation (a bit stricter than Repeatable Read, but not Serializable). There are plans to implement Read Committed (can be useful to avoid serialization failures), but not in the nearest future. It does not make sense to add any settings for isolation levels until then.

> it can be changed to the latter by issue `set transaction snapshot 3`

Not exactly, 3 is special reserved value of snapshot version that means "absolutely everything is visible in this snapshot". "Everything" includes not only "uncommitted" parts, but also outdated parts (and parts that were merged). It cannot be used for any purposes except debugging/introspection:
https://github.com/ClickHouse/ClickHouse/blob/e4d4d0a8543700c2bc85b688c9f8f6cfff64cc48/src/Interpreters/TransactionVersionMetadata.cpp#L170-L172

Anyway, if you want Read Uncommitted for SELECT query, you can simply run non-transactional SELECT (it will read the newest data, including uncommitted).

**Comment by zhicwu** [comment]
Thanks for the clarification @tavplubix. I'll change the default isolation level in JDBC driver to repeatable-read and drop support for read-committed and read-uncommitted.

@Algunenano, I was trying to add multiple transaction isolation levels support in JDBC driver for user to choose - I myself don't have any specific use case for read-uncommitted. I'll leave this issue open in case you guys want to revisit when more isolation levels are supported.
