### ISSUE TITLE
A question (in Chinese): join中的表 final 未生效

### ISSUE THREAD

**Issue by gongzh021** [ClickHouse/ClickHouse#39441]
select * from db.table1 as a final
join db.table12 as c final on 
a.id = b.id 

这里 table2 的 final 未生效

**Comment by ramseyxu** [comment]
> select * from db.table1 as a final join db.table12 as c final on a.id = b.id
> 
> 这里 table2 的 final 未生效

This should be an Unexpected behavior
You should supply information  using the "Unexpected behavior" issue template

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/8655
