### ISSUE TITLE
New merge tree setting to apply final by default

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#39463]
**Use case**

Migration from other databases and updates/deletes are mimicked by Collapsing/Replacing. 
Want to use the same SELECT queries without adding FINAL to all the existing queries.

**Describe the solution you'd like**

```
CREATE TABLE table (... )
Engine=ReplacingMergeTree
SETTTING apply_final_by_default=1

SELECT * FROM table; -- actually does SELECT * FROM table FINAL

SELECT * FROM table SETTINGS auto_final=0; -- 1 by default, 0 - means ignore apply_final_by_default from merge tree.
```

**Describe alternatives you've considered**

**Additional context**

**Comment by UnamedRus** [comment]
Related https://github.com/ClickHouse/ClickHouse/issues/29109

**Comment by R-omk** [comment]
It might also be worth specifying the `do_not_merge_across_partitions_select_final` option as it has more to do with the data schema than with the query parameters.
This option indicates whether it is allowed by logic in this data not to merge data in different partitions.

**Comment by UnamedRus** [comment]
PR https://github.com/ClickHouse/ClickHouse/pull/40945
