### ISSUE TITLE
S3 proxy resolver maybe should contain break on successful request

### ISSUE THREAD

**Issue by tom-clickhouse** [ClickHouse/ClickHouse#39471]
When the proxy resolver's endpoint resolves to multiple IP addresses, it looks like [ProxyResolverConfiguration::getConfiguration ](https://github.com/ClickHouse/ClickHouse/blob/22.7/src/Disks/ObjectStorages/S3/ProxyResolverConfiguration.cpp#L27)will send HTTP request to every of the IP addresses, regardless of success.
[A problem arises when the last IP address does not respond](https://github.com/ClickHouse/ClickHouse/blob/22.7/src/Disks/ObjectStorages/S3/ProxyResolverConfiguration.cpp#L75).

Maybe the [loop](https://github.com/ClickHouse/ClickHouse/blob/22.7/src/Disks/ObjectStorages/S3/ProxyResolverConfiguration.cpp#L62) should contain a `break` on successful HTTP request?
Something like:
```
try
{
    session->sendRequest(request);
    break;
}
catch (...)
{
    ...
}
```

**Comment by aalexfvk** [comment]
It looks like this was fixed in https://github.com/ClickHouse/ClickHouse/pull/40353
