### ISSUE TITLE
projections are production ready but stays experimental in doc

### ISSUE THREAD

**Issue by lksv** [ClickHouse/ClickHouse#39476]
By the ClickHouse [release v22.2, 2022-02-17](https://github.com/ClickHouse/ClickHouse/blob/master/CHANGELOG.md#new-feature-5) the projections are set as production ready:

> Projections are production ready. Set allow_experimental_projection_optimization by default and deprecate this setting. https://github.com/ClickHouse/ClickHouse/pull/34456 ([Nikolai Kochetov](https://github.com/KochetovNicolai)).

But [(at least english) doc](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/mergetree/#projections) still says:

> Projections are an experimental feature. To enable them you must set the [allow_experimental_projection_optimization](https://clickhouse.com/docs/en/operations/settings/settings#allow-experimental-projection-optimization) to 1. See also the [force_optimize_projection](https://clickhouse.com/docs/en/operations/settings/settings#force-optimize-projection) setting.

**Comment by alexey-milovidov** [comment]
The docs need to be edited.

**Comment by lksv** [comment]
https://clickhouse.com/docs/en/guides/improving-query-performance/sparse-primary-indexes/sparse-primary-indexes-multiple#option-3-projections still says:

> [Projections](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/mergetree/#projections) are an experimental feature at the moment, therefore we need to tell ClickHouse that we know what we are doing first

**Comment by DanRoscigno** [comment]
Thanks @lksv fixed in https://github.com/ClickHouse/clickhouse-docs/pull/291
