### ISSUE TITLE
Exception "Unknown identifier" in unexpected place

### ISSUE THREAD

**Issue by dimkas78** [ClickHouse/ClickHouse#39487]
ClickHouse version 22.3.3.44|

Script to reproduce error:
```
create table sandbox.test (id Int8, value String)  engine = Memory() order by tuple();

insert into sandbox.test values (1, 'a');

select 100 as id, value  
from sandbox.test as t 
where t.id = 1
```
Last statement throws an exception " Unknown identifier: id; there are columns: value".

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/27068
