### ISSUE TITLE
From ZooKeeper to ClickHouse Keeper Table is in readonly mode (zookeeper path: /clickhouse/tables/shard01/default/st_order_mt0722), Stack trace:

### ISSUE THREAD

**Issue by jiangbiao910** [ClickHouse/ClickHouse#39489]
Hello：
Clickhouse Version is 21.8.5，
I want to try to  migration  **ZooKeeper to ClickHouse Keeper**   but I can't insert data，the Error is
![image](https://user-images.githubusercontent.com/23710717/180400420-c671bdf1-21a5-4bc6-8ae6-a195a69f0910.png)

clickhouse keeper-converter --zookeeper-logs-dir /opt/module/zookeeper-3.7.0/zkData/version-2 --zookeeper-snapshots-dir /opt/module/zookeeper-3.7.0/zkData/version-2 --output-dir /data/clickhouse/coordination/snapshots

systemctl start clickhouse-server
I can see the servers are on  
![image](https://user-images.githubusercontent.com/23710717/180401164-4549a51c-a0c2-4201-99fe-2e140a9adab5.png)

In the config.xml ,I add the keeper_server

[root@ck01 clickhouse-server]# cat config.xml
<?xml version="1.0"?>
<yandex>
    <logger>
       <level>information</level>
       <log>/data/clickhouse/logs/clickhouse.log</log>
       <errorlog>/data/clickhouse/logs/error.log</errorlog>
       <size>1000M</size>
       <count>10</count>
    </logger>
    <http_port>8123</http_port>
    <tcp_port>9000</tcp_port>
    <mysql_port>3306</mysql_port>
    <interserver_http_port>9009</interserver_http_port>
    <listen_host>::</listen_host>
    <max_connections>4096</max_connections>
    <keep_alive_timeout>3</keep_alive_timeout>

    
    <max_concurrent_queries>1000</max_concurrent_queries>

    
    <max_server_memory_usage_to_ram_ratio>0.8</max_server_memory_usage_to_ram_ratio>

    <uncompressed_cache_size>8589934592</uncompressed_cache_size>
    <mark_cache_size>5368709120</mark_cache_size>
    <path>/data/clickhouse/</path>
    <tmp_path>/data/clickhouse/tmp/</tmp_path>
    <user_files_path>/data/clickhouse/user_files/</user_files_path>
    <users_config>users.xml</users_config>
    <default_profile>default</default_profile>
    <default_database>default</default_database>
    <timezone>Asia/Shanghai</timezone>

    <remote_servers incl="clickhouse_remote_servers"  />
    <zookeeper incl="zookeeper-servers" optional="true" />
    <macros incl="macros" optional="true" />

    
    <builtin_dictionaries_reload_interval>3600</builtin_dictionaries_reload_interval>

    
    <max_session_timeout>3600</max_session_timeout>

    <default_session_timeout>800</default_session_timeout>
    <max_table_size_to_drop>0</max_table_size_to_drop>
    <max_partition_size_to_drop>0</max_partition_size_to_drop>

    
    <query_log>
        <database>system</database>
        <table>query_log</table>
        <partition_by>toYYYYMM(event_date)</partition_by>
        
        <flush_interval_milliseconds>7500</flush_interval_milliseconds>
    </query_log>

    <trace_log>
        <database>system</database>
        <table>trace_log</table>

        <partition_by>toYYYYMM(event_date)</partition_by>
        <flush_interval_milliseconds>7500</flush_interval_milliseconds>
    </trace_log>
    <metric_log>
        <database>system</database>
        <table>metric_log</table>
        <flush_interval_milliseconds>7500</flush_interval_milliseconds>
        <collect_interval_milliseconds>1000</collect_interval_milliseconds>
    </metric_log>

    <query_thread_log>
        <database>system</database>
        <table>query_thread_log</table>
        <partition_by>toYYYYMM(event_date)</partition_by>
        <flush_interval_milliseconds>7500</flush_interval_milliseconds>
    </query_thread_log>

    <distributed_ddl>
        <path>/data/clickhouse/task_queue/ddl</path>
    </distributed_ddl>
    <include_from>/etc/clickhouse-server/metrika.xml</include_from>
    <format_schema_path>/data/clickhouse/format_schemas/</format_schema_path>
    <access_control_path>/data/clickhouse-access/</access_control_path>
<default_replica_path>/clickhouse/tables/{shard}/{database}/{table}</default_replica_path>
    <default_replica_name>{replica}</default_replica_name>

<keeper_server>
    <tcp_port>9181</tcp_port>
    <server_id>1</server_id>  
    <log_storage_path>/data/clickhouse/coordination/log</log_storage_path>
    <snapshot_storage_path>/data/clickhouse/coordination/snapshots</snapshot_storage_path>

    <coordination_settings>
        <operation_timeout_ms>10000</operation_timeout_ms>
        <session_timeout_ms>30000</session_timeout_ms>
        <raft_logs_level>trace</raft_logs_level>
    </coordination_settings>

    <raft_configuration>
        <server>
            <id>1</id>
            <hostname>ck01</hostname>
            <port>9444</port>
        </server>
        <server>
            <id>2</id>
            <hostname>ck02</hostname>
            <port>9444</port>
        </server>
        <server>
            <id>3</id>
            <hostname>ck03</hostname>
            <port>9444</port>
        </server>
    </raft_configuration>
</keeper_server>

</yandex>

[root@ck01 clickhouse-server]# cat metrika.xml
<yandex>
    
    <clickhouse_remote_servers>
    <ch_cluster>

    
    <shard>
    <internal_replication>true</internal_replication>
    <replica>
            <host>ck01</host>
    <port>9000</port>
    </replica>
    <replica>
            <host>ck02</host>
    <port>9000</port>
    </replica>
    </shard>

    <shard>
    <internal_replication>true</internal_replication>
    <replica>
            <host>ck03</host>
    <port>9000</port>
    </replica>
    <replica>
            <host>ck04</host>
    <port>9000</port>
    </replica>
    </shard>
    </ch_cluster>
    </clickhouse_remote_servers>

    <macros>
    <shard>shard02</shard>
    <replica>replica01</replica>
    </macros>
    <networks>
    <ip>::/0</ip>
    </networks>

    <clickhouse_compression>
    <case>
    <min_part_size>10000000000</min_part_size>
    <min_part_size_ratio>0.01</min_part_size_ratio>
    <method>lz4</method>
    </case>
    </clickhouse_compression>

</yandex>

Whether additional other configurations are required？thank you for your help.

**Comment by antonio2368** [comment]
Can you provide some kind of logs?

**Comment by jiangbiao910** [comment]
metrika.xml  should add some configuration such as：

<zookeeper-servers>
  <node index="1">
          <host>ck01</host>
    <port>9181</port>
  </node>
  <node index="2">
          <host>ck02</host>
    <port>9181</port>
  </node>
  <node index="3">
          <host>ck03</host>
    <port>9181</port>
  </node>
</zookeeper-servers>

and the port must be the same as 
<keeper_server>
<tcp_port>9181</tcp_port>

**Comment by alexey-milovidov** [comment]
No logs were provided.
