### ISSUE TITLE
hive table column prune didn't take effect?

### ISSUE THREAD

**Issue by LvLiangLiang-dev** [ClickHouse/ClickHouse#39485]
![image](https://user-images.githubusercontent.com/19455764/180381897-7c6360e2-018e-4ece-a5c1-767fa5200b43.png)
Total size of the table is more 14GB, SQL queries only one column, query msg showes 924.79MB memory;
But iftop showes 14.4GB RX.
why this appear? 
should ck hive engine scan only one column in parquet, and then iftop displays about 1g?

**Comment by taiyang-li** [comment]
Pls give me your CH version.

**Comment by LvLiangLiang-dev** [comment]
22.6

**Comment by LvLiangLiang-dev** [comment]
![image](https://user-images.githubusercontent.com/19455764/180399418-5eea2ccd-254e-463d-827d-d272dbf35130.png)
memory useage ~~ 1g 
but io is too big... ~ 14g == parquet size on hdfs

**Comment by LvLiangLiang-dev** [comment]
![image](https://user-images.githubusercontent.com/19455764/180401849-ddededd5-0701-4481-9dbd-9a15c2fa3990.png)

In fact, HDFS has a similar problem. 
The memory is correct, and column prune is executed, but IO is the full file size;
The above is a hive partition test, with data of about 1.5g, io of 1.5g and memory of 86mb

I guess it's question of HDFS parquet read seeking....
