### ISSUE TITLE
projection not support the where clause

### ISSUE THREAD

**Issue by zhouerlin** [ClickHouse/ClickHouse#39483]
@amosbird
hi，At present, projection does not support the where clause, and there is no idea for the range comparison.
Do you have any good suggestions for implementing where clause range comparison? Thanks！

**Comment by e-mars** [comment]
As you mentioned, there is no where clause available in projections. Would suggest to try a materialized view to implement ranges. 
There is an issue for enhancement requested here: https://github.com/ClickHouse/ClickHouse/issues/33678
You can add your comments there also.

**Comment by den-crane** [comment]
Do you mean to create a projection which covers only part of table / data?
Because projections support filtering by range.

**Comment by zhouerlin** [comment]
> Do you mean to create a projection which covers only part of table / data? Because projections support filtering by range.

Yes, Filter unwanted data when creating projections
