### ISSUE TITLE
Add SYSTEM DROP DATABASE REPLICA query for Replicated database engine

### ISSUE THREAD

**Issue by shahargv** [ClickHouse/ClickHouse#39512]
Hi,
I've found that SYSTEM DROP REPLICA doesn't work the way I expected it to work according to the documentation, on a database that's using the Replicated database engine.

**Steps to reproduce**
1. Execute `CREATE DATABASE tests ENGINE = Replicated('/dbs/test', '{shard}', '{replica}')` on 4 nodes (2 shards, 2 replicas). For ease of use, we'll call them clickhouse0[1-4].
2. Execute on one of the nodes : `CREATE TABLE tests.local_testTable 
(
	InsertionTime Datetime32,
	Blah1 String,
	Blah2 Int32
) 
ENGINE=ReplicatedMergeTree 
PARTITION BY toYYYYMM(InsertionTime)
ORDER BY InsertionTime`
3. The DDL statement gets replicated as expected, and the table now exists on all nodes. The new cluster in system.clusters also looks as expected.
4. Now, shut down node clickhouse04. Assuming it's dead for good and not going to be replaced.
5. When executing any other DDL statement, it's get stuck as expected, since it can't be replicated on all nodes.
6. Now, trying to run `SYSTEM DROP REPLICA 'clickhouse04'` or `SYSTEM DROP REPLICA 'clickhouse04' FROM DATABASE tests` on one of the nodes. 

According to the documentation, it sounds like it supposed to remove the replica metadata. I'm expecting it to allow further DDL statements to run without getting stuck, and to allow me to create a new replica with the same name (since the previous one was removed). I'd also expect the ZooKeeper entries of the replica to be removed.

In practice, other DDL statements on this database keeps getting stuck, and I can't add a new replica using the same name.

The only workaround worked for me was to remove the replica metadata from the ZooKeeper using ` deleteall '/dbs/test/replicas/02|clickhouse04'` from zkCli.

I'd be happy to get some clarifications on what SYSTEM DROP REPLICA should actually do in a Replicated database engine (if that's an expected behavior). 

Thanks.

**Comment by tavplubix** [comment]
`SYSTEM DROP REPLICA` drops a replica of `ReplicatedMergeTree` table, it does not know about `Replicated` database. That's why database replica still exists and DDL queries wait for it.

**Comment by evillique** [comment]
Closed in https://github.com/ClickHouse/ClickHouse/pull/42807
