### ISSUE TITLE
Disk spill related question on ClickHouse

### ISSUE THREAD

**Issue by arunmarathe** [ClickHouse/ClickHouse#39514]
I was trying a memory-intensive query on CH: specifically TPC-H Query 19. It ran out of memory, and failed. I searched through CH documentation, and could not find any information on disk spill related parameters (which are usually involved when executing memory hog queries). Does CH have any disk spill related parameters? The only one I could find using documentation was to try settings join_algorithm to "auto", but doing that did not help Q19.

Thanks,
Arun

**Comment by den-crane** [comment]
`join_algorithm = 'partial_merge'` 
`max_bytes_before_external_group_by` https://clickhouse.com/docs/en/operations/settings/query-complexity/#settings-max_bytes_before_external_group_by
`max_bytes_before_external_sort` https://clickhouse.com/docs/en/sql-reference/statements/select/order-by/#implementation-details
