### ISSUE TITLE
Updating a dictionary by `update_field`, even if there is no data to update

### ISSUE THREAD

**Issue by rchadin** [ClickHouse/ClickHouse#39548]
```
select version();
┌─version()───┐
│ 22.7.1.2484 │
└─────────────┘

CREATE TABLE test_dictionary_time
(
    `ID` UInt64,
    `Value` String,
    ModifiedTime DateTime default now()
)
ENGINE = MergeTree
ORDER BY ID;

INSERT INTO test_dictionary_time (ID, Value) SELECT     number,     concat('value_', toString(number)) FROM numbers(100000);

create dictionary test_dictionary_updated_field
(
  ID UInt64,
  Value String
)
PRIMARY KEY ID
SOURCE(CLICKHOUSE(HOST 'localhost' PORT 9000 USER 'default' PASSWORD '' DB 'default' TABLE 'test_dictionary_time' update_field 'ModifiedTime'))
LIFETIME(30)
LAYOUT(Complex_Key_Hashed ());

select * from test_dictionary_updated_field;
```
Dictionary loaded
```
select name, status, type, element_count, load_factor, lifetime_min, lifetime_max, loading_start_time, last_successful_update_time, loading_duration, last_exception, comment from system.dictionaries where name = 'test_dictionary_updated_field';
```
Data is not added to the table
After 30 seconds of seconds in the logs the message
```
2022.07.25 08:04:10.682885 [ 17232 ] {} <Debug> executeQuery: (internal) SELECT `ID`, `Value` FROM `default`.`test_dictionary_time` WHERE ModifiedTime >= '2022-07-25 08:04:04'; (stage: Complete)
```
Repeating in the database
```
SELECT
    ID,
    Value
FROM default.test_dictionary_time
WHERE ModifiedTime >= '2022-07-25 08:04:04'

Query id: 01279644-53c6-4df7-a87f-330a8ff93de0

Ok.

0 rows in set. Elapsed: 0.008 sec. Processed 1.00 million rows, 4.00 MB (124.75 million rows/s., 499.02 MB/s.)

```
Watching dictionary update time
```
select name, status, type, element_count, load_factor, lifetime_min, lifetime_max, loading_start_time, last_successful_update_time, loading_duration, last_exception, comment from system.dictionaries where name = 'test_dictionary_updated_field';

┌─name──────────────────────────┬─status─┬─type─────────────┬─element_count─┬───────load_factor─┬─lifetime_min─┬─lifetime_max─┬──loading_start_time─┬─last_successful_update_time─┬─loading_duration─┬─last_exception─┬─comment─┐
│ test_dictionary_updated_field │ LOADED │ ComplexKeyHashed │       1000000 │ 0.476837158203125 │            0 │           30 │ 2022-07-25 08:05:55 │         2022-07-25 08:05:56 │            0.426 │                │         │
└───────────────────────────────┴────────┴──────────────────┴───────────────┴───────────────────┴──────────────┴──────────────┴─────────────────────┴─────────────────────────────┴──────────────────┴────────────────┴─────────┘
```
The dictionary is still reloaded even if there is no data to update.
The dictionary is loaded into memory every 30 seconds, even if no data is added to the table.

**Comment by den-crane** [comment]
I don't understand. It works as it supposed to work.

Dictionary reloads `LIFETIME(30)` checks the source, and changes `loading_start_time` `last_successful_update_time` because it was reloaded.

**Comment by rchadin** [comment]
Dictionary uses ```update_field 'ModifiedTime'```
As far as I understand from the documentation, in this case it should check for new entries, and reload the dictionary only when they appear, as indicated by the log message that I cited above.

**Comment by den-crane** [comment]
Apparently we put different meanings in the "dictionary reload".

Dictionary reload does not mean that it loaded all data from the source. 

Though a dictionary with update_field rebuild its internal structure with each iteration.

`last_successful_update_time` -- reflects time of last successful iteration, does not matter how many rows were updated.

**Comment by rchadin** [comment]
Maybe. Thanks for the clarification. I understood this field in such a way that if there is no data to update, then it will not reload the structure. If the dictionary is large, then resources will be spent on rebuilding it, although this does not make sense. I tested it on big data. And the documentation stated that when using this modifier, only new data is loaded, but in general it looks like the entire dictionary is being reloaded.
Thank you.
