### ISSUE TITLE
Effective user of the process (clickhouse) does not match the owner of the data (root) in k8s

### ISSUE THREAD

**Issue by alex-zaitsev** [ClickHouse/ClickHouse#39547]
In k8s volume is always mounted as a root, if is only possible to set fsGroup to  'clickhouse': 
```
clickhouse@chi-test-test-0-0-0:/$ ls -la /var/lib/clickhouse/
total 2804
drwxrwsr-x 19 root       clickhouse    4096 Jul 25 08:37 .
...
```
That results in warning when starting clickhouse-client. Maybe the startup logic introduced in https://github.com/ClickHouse/ClickHouse/pull/3785 can be improved to check the group as well.

**Comment by alexey-milovidov** [comment]
There was an attempt to implement this feature in #36073
