### ISSUE TITLE
TCPHandlerFactory creating TCPhandler is slow. Takes 3 sec within intranet

### ISSUE THREAD

**Issue by daggerin3** [ClickHouse/ClickHouse#39549]
checked log file, /var/log/clickhouse-server/clickhouse-server.log, I got logs below,

2022.07.25 17:02:23.535994 [ 12473 ] {} <Trace> TCPHandlerFactory: TCP Request. Address: [::ffff:172.22.254.xx]:57308
2022.07.25 17:02:26.554058 [ 12473 ] {} <Debug> TCPHandler: Connected ClickHouse client version 1.1.0, revision: 54380, database: xxxxx, user: xxxx.

It takes 3 sec to create a TCP connection in my opion,

Already done below,
1. Ping is OK, stable and fast. Intranet.
2. It returns the correct results, just slow.
3. ClickHouse Server version: 20.8.3 revision 54438
4. Stop the firewall on both machines.
5. No error logs in /var/log/clickhouse-server/clickhouse-server.err.log

Any suggestion will be grateful. 

Warm Regards,

**Comment by tavplubix** [comment]
> ClickHouse Server version: 20.8.3

Upgrade to supported version

**Comment by tavplubix** [comment]
> ClickHouse client version 1.1.0

And upgrade client as well (versions 1.x are almost 4 years old)

**Comment by den-crane** [comment]
Looks like a DNS timeout / issue.

**Comment by daggerin3** [comment]
> Looks like a DNS timeout / issue.

Thanks a lot. Problem solved. 1st DNS server is unreachable.
