### ISSUE TITLE
Mechanism to migrate databases from Ordinary to Atomic engine

### ISSUE THREAD

**Issue by Alex-Burmak** [ClickHouse/ClickHouse#39546]
Ordinary database engine is deprecated but there is no simple mean to change database engine to Atomic for existing databases.

Possible options:
- ALTER DATABASE MODIFY ENGINE query.
- Flag that triggers migration at ClickHouse startup.

The latter should be easier to implement.

**Comment by tavplubix** [comment]
Related: https://github.com/ClickHouse/ClickHouse/pull/38335

I prefer the option with flag, but it makes sense to add a query that creates this flag as well (but not a synchronous query that converts database in runtime).

**Comment by ilejn** [comment]
Hello @tavplubix ,
is not it possible to use this feature for seamless upgrade from 20.7 and older to recent versions?
Currently it is does not work, it is effectively prohibited by checkUnsupportedVersion().
Or there are real reasons to disable direct update and make upgrade through intermediate versions mandatory?

**Comment by tavplubix** [comment]
This feature is not related to upgrades at all.

**Comment by ilejn** [comment]
> This feature is not related to upgrades at all.

Yes, and the question is why.

But actually I am satisfied by your responce in chat https://t.me/clickhouse_ru/303054 , thanks.
