### ISSUE TITLE
Question regarding using AWS S3 Backup - while using S3 Backed Merge Tree

### ISSUE THREAD

**Issue by SimSama** [ClickHouse/ClickHouse#39545]
Hi CH Team,

I read through the documentation regarding S3 Backed Merge tree. I had some questions regarding using AWS S3 backup on this data stored in S3, as well as some viable data redundancy options using S3 object storage.

TLDR; For Merge Tree and Replicated Merge Tree on S3, do we need to freeze the tables on that S3 storage prior to being backed up using AWS backup? Is there some option (assuming this data is forever immutable and/or read-only) to store it in S3 in a quiesced format (pre-frozen), suitable for backup? 

Use Case 1:

CH data nodes with local disk will have Merge Tree tables, ReplicatedMergeTree tables will be on S3 storage, getting a copy of the local data. I use AWS S3 backup to handle regular backups of the data. 

Use Case 2: 
Large CH cluster has MergeTree tables in Local Disk / Storage policy to move to S3 when they fill up. 
Meanwhile, data in local disk is also replicated to S3 for redundancy. 

Local Disk and S3 disk is actively query-able, but the data in S3 is write-once, read occasionally.

Local Disk -> Replicate to S3 Bucket/ prefix X
Local Disk (upon move factor threshold) -> Move to S3 Bucket/ prefix Y

Data in prefix X -- optional to query, but can we store in a backup ready state, or need freeze timed before backup?
Data in prefix Y -- occasional queries, but is read-only. No writes on existing data needed, expands as local disk ages out old data and moves to S3

We like the simplicity of backing up S3 storage, just want to be sure that data stuffed into S3 is in a state to do so. 

Thanks,

**Comment by SimSama** [comment]
Bump request for this question. Thanks for your time in advance!

**Comment by DerekChia** [comment]
> For Merge Tree and Replicated Merge Tree on S3, do we need to freeze the tables on that S3 storage prior to being backed up using AWS backup?

No. Even if you try to freeze a partition for a s3 backed MergeTree table, there will not be any local partition created. The `shadow` directory along with the `increment.txt` will be created and nothing else. 

In 22.11, write-once-read-many (WORM) operations is supported through `s3_plain` disk. This allows reading from S3 without metadata. See https://github.com/ClickHouse/ClickHouse/pull/45626/files#r1091041492

> Introduce s3_plain disk type for write-once-read-many operations. Implement ATTACH of MergeTree table for s3_plain disk. [#42628](https://github.com/ClickHouse/ClickHouse/pull/42628) ([Azat Khuzhin](https://github.com/azat)).

Regarding "Data in prefix X", for the purpose of backing up and having a point-in-time snapshot, you can simply use the standard backup process - https://clickhouse.com/docs/en/operations/backup/#configuring-backuprestore-to-use-an-s3-endpoint

For "Data in prefix Y", perhaps `s3_plain` disk is suitable.
