### ISSUE TITLE
Chain#addSink

### ISSUE THREAD

**Issue by zouxiang1993** [ClickHouse/ClickHouse#39553]
src/QueryPipeline/Chain.cpp
```
void Chain::addSink(ProcessorPtr processor)
{
    checkTransform(*processor);

    if (!processors.empty())
        connect(getOutputPort(), processor->getInputs().front());

    processors.emplace_front(std::move(processor));
}
```
Is there should be : 
```
processors.emplace_back(...) 
```
    /// -> source -> transform -> ... -> transform -> sink ->
    ///  ^        ->           ->     ->           ->       ^
    ///  input port                               output port
    std::list<ProcessorPtr> processors;

**Comment by KochetovNicolai** [comment]
@zouxiang1993 indeed, thank you. I am lucky that this method called only once for an empty chain.
