### ISSUE TITLE
How to hide sensitive information in query_log

### ISSUE THREAD

**Issue by zhanghuajieHIT** [ClickHouse/ClickHouse#39554]
If I use the sql like below:
```
select * from remote('127.0.0.1', default, test, 'admin', 'zhanghuajie');
```
The query_log will record the password, which will leak my sensitive information.

So, how to hide the sensitive information in query_log.

**Comment by blinkov** [comment]
It doesn't have an example specifically for `remote`, but see https://clickhouse.com/docs/en/operations/named-collections/

**Comment by den-crane** [comment]
You may try https://github.com/ClickHouse/ClickHouse/issues/24887

ClickHouse release 22.7, 2022-07-21 New Feature
Add an option to require explicit grants to SELECT from the system database. Details: https://github.com/ClickHouse/ClickHouse/pull/38970 ([Vitaly Baranov](https://github.com/vitlibar)).
