### ISSUE TITLE
toStartOfMonth doesn't work correctly with Date32

### ISSUE THREAD

**Issue by rsdouglas** [ClickHouse/ClickHouse#39561]
**Describe what's wrong**
toStartOfMonth produces incorrect results on Date32 before 1970

**Does it reproduce on recent release?**
ClickHouse server version 22.7.1.906 (official build).

**How to reproduce**
```sql
select toStartOfMonth('1960-01-01'::Date32);

SELECT toStartOfMonth(CAST('1960-01-01', 'Date32'))

Query id: 05e9ac72-51ee-400b-998e-721a55f170c9

┌─toStartOfMonth(CAST('1960-01-01', 'Date32'))─┐
│                                   2139-06-07 │
└──────────────────────────────────────────────┘
```

**Comment by den-crane** [comment]
https://github.com/ClickHouse/ClickHouse/issues/38995
