### ISSUE TITLE
Working with big PostgreSQL DBs (Materialized)

### ISSUE THREAD

**Issue by mhkarimi1383** [ClickHouse/ClickHouse#39577]
Since MaterializedPostgreSQL Feature is using Logical Replication and we have limitation of number of slots in our PostgreSQL instances what we should do about databases with lots of table inside?
I think using Physical Replication can handle this problem by making just a single Slot
And also Physical Slots are more reliable

**Comment by kssenii** [comment]
> we have limitation of number of slots

There was a problem related to this fixed in https://github.com/ClickHouse/ClickHouse/pull/40511. Please check master version. (master branch can be installed this way https://clickhouse.com/docs/en/getting-started/install/#from-single-binary)
