### ISSUE TITLE
Encryption at REST problem: CANNOT_DECOMPRESS error

### ISSUE THREAD

**Issue by x052bb** [ClickHouse/ClickHouse#39608]
Hi. 

I'm trying to play with data encryption, my goal is to make existing table use data encryption. Clickhouse version is 22.3.
The table is simple:

```
CREATE TABLE TEST (TIMESTAMP DateTime, VALUE Nullable(String), KEY Nullable(String)) 
ENGINE = MergeTree()
PARTITION BY toYYYYMM(TIMESTAMP)
ORDER BY tuple()
```

This table has approximately 12M existing records in two partitions.
The sample test query:

`select TIMESTAMP, KEY, VALUE from TEST where KEY = '10548423660090478384'`

Storage configuration:

```
 <storage_configuration>
    <disks>
      <default/>
      <test>
        <type>encrypted</type>
        <disk>default</disk>
        <path>test/</path>
        <algorithm>AES_128_CTR</algorithm>
        <key_hex id="0">0123456789ABCDEF0123456789ABCDEF</key_hex>
        <current_key_id>0</current_key_id>
      </test>
    </disks>
    <policies>
      <test>
        <volumes>
          <secure>
            <disk>test</disk>
          </secure>
          <default>
            <disk>default</disk>
          </default>
        </volumes>
        <move_factor>0.0</move_factor>
      </test>
    </policies>
  </storage_configuration>

```

Then I change table's policy and move two existing partitions to secure volume:

```
ALTER TABLE TEST MODIFY SETTING storage_policy='test'
ALTER TABLE TEST MOVE PARTITION '202112' TO VOLUME 'secure'
ALTER TABLE TEST MOVE PARTITION '202203' TO VOLUME 'secure'
```

Now running the same sample query as above gives an error:

`DB::Exception: Data compressed with different methods, given method byte 0x63, previous method byte 0x82: (while reading column VALUE): (while reading from part /home/snow/clickhouse/data/test/store/179/17960ffe-a394-4c05-8764-3854097892df/202203_8_13_2/ from mark 3 with max_rows_to_read = 6471): While executing MergeTreeThread. (CANNOT_DECOMPRESS) `

Note:

-  Instead of moving partitions to 'secure' volume I tried doing INSERT INTO ... SELECT ... - same error
-  Moving both partitions back to 'default' volume makes it work again

Any ideas?

**Comment by melvynator** [comment]
I would suggest that you upgrade your ClickHouse version to leverage this PR: https://github.com/ClickHouse/ClickHouse/pull/39687
