### ISSUE TITLE
Separate the configuration items involved in named-collections into an independent configuration file, and use "include_from" and "incl" in the config.xml file. After the ClickHouse is restarted, the configuration items do not take effect.

### ISSUE THREAD

**Issue by qmdt** [ClickHouse/ClickHouse#39615]
(you don't have to strictly follow this form)

**Describe the unexpected behaviour**
1.Separate the configuration items involved in named-collections into an independent configuration file, 
2.use "include_from" and "incl" in the config.xml file. 
3.After the ClickHouse is restarted, the configuration items do not take effect.

**How to reproduce**
* Which ClickHouse server version to use
22.3.2.2

* reproduce step
* 1.  config independent configuration file: named_collections.xml
![image](https://user-images.githubusercontent.com/8369775/181001698-fc2df2c3-fb42-4641-a056-023d32de2c99.png)

* 2.  use "include_from" and “incl” in the config.xml file for loading the configurations items involved in named-conllections:
![image](https://user-images.githubusercontent.com/8369775/181002338-6c558a68-c1c9-440f-af51-4692810125ff.png)

* or when the tag in named_collections.xml is clickhouse_named_collections,  as follows:
![image](https://user-images.githubusercontent.com/8369775/181002798-8e9e234f-c996-4008-95ac-5135773bee9f.png)

* 3.  restart the ClickHouse
* 4.  when run the following SQL, exception throws:
![image](https://user-images.githubusercontent.com/8369775/181002633-f0d44217-92e7-40c3-9f9b-8fd9269961d0.png)

**Expected behavior**
use "include_from" and "incl" can load the configurations items involved in named-conllections

**Error message and/or stacktrace**
Except metika.xml and users.xml, other configuration files cannot be decoupled from config.xml and use independent configuration files.

**Additional context**
NA

**Comment by den-crane** [comment]
read this https://kb.altinity.com/altinity-kb-setup-and-maintenance/altinity-kb-server-config-files/

**you don't need  "include_from" and "incl" and  metika.xml** !!!
