### ISSUE TITLE
Memory tracker accounts for dirty pages, which can amount of hundred of GB of ram

### ISSUE THREAD

**Issue by jorisgio** [ClickHouse/ClickHouse#39614]
After #10293 Global memory tracker is periodically reset to resident memory. This clashes with the way jemalloc works with lazy purging of dirty/muzzy page. A lot of the resident memory is in fact technically free, but it is accounted in memory tracker. 
On big ram server, this can amount to hundred of gibabytes of ram, which are prevented from being used for no reason.
I suspect the periodic reset should use jemalloc active tracker and not resident memory to play nice with jemalloc purging ?

**Comment by den-crane** [comment]
@azat

**Comment by jorisgio** [comment]
Actually it is not so easy because big allocations bypass jemalloc for mremap 😭.

**Comment by azat** [comment]
@jorisgio indeed it is possible, and you are absolutely right, such memory should not be taken into account.

Fortunately jemalloc provide a way to get amount of such memory - [`stats.retained`](https://jemalloc.net/jemalloc.3.html#stats.retained).

This issue can be solved by #38682 I guess.
