### ISSUE TITLE
How to quickly load file data into local tables？

### ISSUE THREAD

**Issue by longfeizheng** [ClickHouse/ClickHouse#39616]
hello everyone

I wanted to load some data to CH for using  it.

After spending a long time with CH, found that write Distributed table is faster then local table

First file: csv.data  **60GB+**
Sample data:

```
1,SEX,1,2022-06-12 00:00:00,1
2,SEX,1,2022-06-12 00:00:00,1
3,SEX,1,2022-06-12 00:00:00,1
```

Second file: This is the local table  load.

```
CREATE TABLE tag.tag_test_base_info
(
     `offset` UInt64,
    `tag_code` String,
    `tag_value` String,
     `ts` DateTime,
    `sign` Int8
)
ENGINE = ReplicatedCollapsingMergeTree('/clickhouse/tables/{shard}/tag_test_base_info', '{replica}', sign)
PARTITION BY ts
ORDER BY (ts, tag_code, offset)
SETTINGS storage_policy = 'default', use_minimalistic_part_header_in_zookeeper = 1, index_granularity = 8192
```

Testing CSV load:
```
cat csv.dat | clickhouse-client -h 127.0.0.1 -d default -m -u default --password 123456 --format_csv_delimiter= ',' --query="INSERT INTO tag.tag_test_base_info FORMAT CSV";

```

So it took **39:12.29** seconds.

Three file:This is the Distributed table load.

```
CREATE TABLE tag.tag_test_base_info
(
     `offset` UInt64,
    `tag_code` String,
    `tag_value` String,
     `ts` DateTime,
    `sign` Int8
)
ENGINE = Distributed('tagclickhouse', 'tag', 'tag_test_base_info', rand())
```

Testing CSV load:
```
cat csv.dat | clickhouse-client -h 127.0.0.1 -d default -m -u default --password 123456 --format_csv_delimiter= ',' --query="INSERT INTO tag.tag_test_base_info_dist FORMAT CSV";

```

So it took **16:50.01** seconds.

The  Server is  6  virtual machine  **16C+64g+500G** 

That means using Distributed table  is = **2X** faster (39:12.29 seconds / 16:50.01 seconds)
Or local table  is **2X** slower! 

My question

1. Why is it faster to load Distributed tables than local tables
2. How to quickly load data into local tables？(i 'am using ``` --input_format_parallel_parsing=0 --compression=0``` ,args There is no change in speed) 

thank you

**Comment by den-crane** [comment]
you problem is here `PARTITION BY ts` 

expected `PARTITION BY toYYYYMM(ts)`

**Comment by longfeizheng** [comment]
> technically the insert is faster but data is not inserted because insert into Distributed is async by default
> 
> check with `--insert_distributed_sync arg If setting is enabled, insert query into distributed waits until data will be sent to all nodes in cluster.`
> 
> ```
> cat csv.dat | clickhouse-client --insert_distributed_sync=1 -h 127.0.0.1 -d default -m -u default --password 123456 --format_csv_delimiter= ',' --query="INSERT INTO tag.tag_test_base_info_dist FORMAT CSV";
> ```

No wonder distributed tables are written so fast

**Comment by longfeizheng** [comment]
> you problem is here `PARTITION BY ts` it's too granular
> 
> expected `PARTITION BY toYYYYMM(ts)`
> 
> Also try `ORDER BY (tag_code, offset, ts)`

Although the partition is ```PARTITION BY ts```, the data is ```2022-06-12 00:00:00``` format 

I am tring to change ```ORDER BY (tag_code, offset, ts)``` testing

**Comment by longfeizheng** [comment]
hi everyone:

I used the shard file (Each file is about 30g in size) to load local tables from multiple clients and finished it.
