### ISSUE TITLE
output_format_arrow_string_as_string and output_format_arrow_low_cardinality_as_dictionary in combination

### ISSUE THREAD

**Issue by kcajf** [ClickHouse/ClickHouse#39624]
I am using the Arrow output format, and I am making a query of a column with type `LowCardinality(String)` with the following settings applied:
```
output_format_arrow_string_as_string=true
output_format_arrow_low_cardinality_as_dictionary=1
```

I expect to receive a column with Arrow type `dictionary<values=string, indices=int8, ordered=0> not null`, but instead I get the error:

```
Code: 49. DB::Exception: Cannot fill arrow array with LowCardinality(String) data.: While executing ArrowBlockOutputFormat. (LOGICAL_ERROR) (version 22.6.2.12 (official build))
```

Individually, these two settings work:
- The first one returns `String/LowCardinality(String)` columns as Arrow `string` instead of `binary`
- The second one returns `LowCardinality(String)` columns as Arrow `dictionary<values=binary, indices=int8, ordered=0> not null`. 

But the combination of the two does not work.

**Comment by kcajf** [comment]
https://github.com/ClickHouse/ClickHouse/issues/37254

@Avogar it looks like this is a recent change?

**Comment by Avogar** [comment]
That's a bug, I will fix it

**Comment by kcajf** [comment]
Thanks!
