### ISSUE TITLE
Window function "any" cannot work on datetime

### ISSUE THREAD

**Issue by catchex** [ClickHouse/ClickHouse#39632]
Clickhouse Version: v22.6.4.35-stable
Built At: 22006004

SQL:
<img width="1074" alt="image" src="https://user-images.githubusercontent.com/875473/181172888-45e9c3db-06c1-4ed2-a2be-be2f9d9f4153.png">

Result:
<img width="737" alt="image" src="https://user-images.githubusercontent.com/875473/181172928-7451aa85-30e2-4941-861b-43a939a6a380.png">

The column 'co_2', 'co_3' is original, and the column 'co_9' is values in window frame, but co_11 is not the last value of the window frame.
The `lagInFrame` and `first_value` is correct, but which cannot be calculated in other expressions, for example: toYear, case when expression and binary expression, etc. I can only wrap it in a sub query.

Error message:
Code: 47. DB::Exception: Unknown identifier: lagInFrame(sum(qu_2.co_2)) OVER (PARTITION BY co_1 AS co_1 ORDER BY co_2 AS co_2 ASC);

**Comment by den-crane** [comment]
`lagInFrame(sum(qu_2.co_2)) OVER ` -- this incorrect. You cannot do Window function over aggregate function.

**Comment by catchex** [comment]
@den-crane Did you see column 'co_10' and 'co_9', 'co_10' is the result of groupArray, it is correct, the `co_9` is the result of any function. Logically, they should be the same, but the 'co_9' is the value of current row.
