### ISSUE TITLE
How to ignore errors during insertion(JSON Object type related)

### ISSUE THREAD

**Issue by Yueyu-Marky** [ClickHouse/ClickHouse#39639]
Version: 22.5.1.2079

Test table's structure:

~~~SQL
CREATE TABLE default.tb_target
(
    `event_time` DateTime64(3, 'Asia/Shanghai'),
    `log_name` LowCardinality(String),
    `event` Object('json')
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(event_time)
ORDER BY (log_name, event_time)
SETTINGS index_granularity = 8192
~~~

Another table:

~~~SQL
CREATE TABLE default.tb_target_ingest
(
    `logdatetime` String,
    `logname` String,
    `message_raw` String
)
ENGINE = TinyLog
~~~

(the reason I use another table is to simulate kafka table)

Then the MV:

~~~SQL
CREATE MATERIALIZED VIEW default.tb_mv TO default.tb_target
(
    `event_time` DateTime64(3),
    `log_name` String,
    `event` String
) AS
SELECT
    toDateTime64(logdatetime, 3) AS event_time,
    logname AS log_name,
    JSONExtractString(message_raw) AS event
FROM default.tb_target_ingest
~~~

Finally, insert data into tb_target_ingest:

~~~SQL
INSERT INTO default.tb_target_ingest FORMAT JSONEachRow
{"logdatetime":"2022-07-26 15:34:20.540","message_raw":"{\"reason\": {\"reason\": 2}}","logname":"test_log"}
~~~

Now I can query the result from tb_target table:

~~~SQL
SELECT *
FROM tb_target
SETTINGS output_format_json_named_tuples_as_objects = 1
FORMAT JSONEachRow
SETTINGS output_format_json_named_tuples_as_objects = 1;

Query id: 9fdb974c-b346-4c4f-b243-ef15047b25c9

{"event_time":"2022-07-26 15:34:20.540""log_name":"test_log","event":{"reason":{"reason":1}}}
~~~

Inserting next row below will trigger an exception which is expected since there is already a field called reason that is an Object:

~~~sql
INSERT INTO default.tb_target_ingest FORMAT JSONEachRow
{"logdatetime":"2022-07-26 15:34:20.540","message_raw":"{\"reason\": 123}","logname":"test_log"}
~~~

> DB::Exception: Data in Object has ambiguous paths: 'reason.reason' and 'reason'

When I use kafka table, the exception will block kafka consumer from consuming messages. It just stuck there and keep throwing exceptions.

Q: How to ignore / suppress these errors since messages sometimes have conflict field types(dropping those messages is OK). Thanks.

**Comment by fatelei** [comment]
has same issue, one data format error block the other data

**Comment by DenisGee** [comment]
some issue,  it would be nice if we could storage those messages, not dropping)

**Comment by rewiaca** [comment]
has same issue, JSON is valid and has no problems with typing https://github.com/ClickHouse/ClickHouse/issues/38530#issue-1287270511
But it doesnt like same key names in array

> DB::Exception: Data in Object has ambiguous paths: 'reason.reason' and 'reason'

I was force to change column type from JSON to String
