### ISSUE TITLE
How could I import kafka message with json

### ISSUE THREAD

**Issue by olegtap** [ClickHouse/ClickHouse#39645]
I have a json message in kafka.
```
[
        {
        "partner_id":156,
        "id":"bc238532-e400-786c-1e86-c821b49776fd",
        "type":4,
        "remove":0,
        "segments":[
        "M103zyb0n0000054"
        ]
     }, 
        {
        "partner_id":156,
        "id":"038ef8a7-b55e-4ea2-8889-444a9dda6424",
        "type":4,
        "remove":0,
        "segments":[
        "M103zyb0n0000054"
        ]
     }
]
```

How can I import the message into CH?

**Comment by UnamedRus** [comment]
Can you check this approach? https://kb.altinity.com/altinity-kb-schema-design/altinity-kb-jsonasstring-and-mat.-view-as-json-parser/

**Comment by olegtap** [comment]
Thanks, I will check

**Comment by filimonov** [comment]
https://clickhouse.com/docs/en/integrations/kafka/kakfa-intro/

**Comment by axel-hk** [comment]
> I tried this:
> 
> ```
> CREATE TABLE testdb.queue_json (
>         `message` String
> ) 
> ENGINE = Kafka 
> SETTINGS 
>         kafka_broker_list = 'xxx', 
>         kafka_topic_list = 'mytopic', 
>         kafka_group_name = 'mygroup1', 
>         kafka_format = 'JSONAsString',
>         kafka_max_block_size = 1048576
> ```
> 
> I get this error in the log `<Error> void DB::StorageKafka::threadFunc(size_t): Code: 27. DB::ParsingException: Cannot parse input: expected ']' before: '{"partner_id": 156, "id": "9e8c4e5b-2468-be69-3d3b-43e1a6eb28f5", "type": 4, "remove": 0, "segments": ["M103zyb0n0000054"]}, {"partner_id": 156, "id": "6897d272': while parsing Kafka message ... (CANNOT_PARSE_INPUT_ASSERTION_FAILED)`

I get the same error. Is there any fix?

**Comment by axel-hk** [comment]
@olegtap, greeting oleg! Have you found any solution?
