### ISSUE TITLE
How to control insertion rate and disk space usage (another `not enough space`)

### ISSUE THREAD

**Issue by DGolubets** [ClickHouse/ClickHouse#39659]
**My use case**

I've got two tables:
- Table A ~ 347.03 MiB ~ 14 mil rows
- Table B ~ 392.54 MiB ~ 44 mil rows

I need to join both tables and produce Table C.
I do this in multiple steps, iterating over some partitioning key, executing a query like this (from Python):
```
insert into table_c
select a.*, b.* 
from table_a a
join (select * from table_b where p_key = '{p_key}') b on a.join_key=b.join_key
```
The resulting Table C is 63.73 GiB and 2.5 bil rows.

**Observation**
Somewhere in the middle of generating Table C I got an error saying `not enough space`.
I then resumed the process and monitored the disk space at the same time. The used disk space was growing much faster than the reported table size, up to 90%. After the table was generated the used disk space started to shrink until it got back to 58% (of 120GB).
It looks like that there are some temporary files being created by Clickhouse which are destroyed later, but asynchronously.

**Question**
How do I make sure that I generate my table as fast as possible, but not that fast to go out of disk space? 
Is there a command that would block until all file IO that needs to be done is done?

**Comment by mirajgodha** [comment]
When data is inserted in a table, separate data parts are created and each of them is lexicographically sorted by primary key.  For example, if the primary key is (CounterID, Date), the data in the part is sorted by CounterID, and within each CounterID, it is ordered by Date.

Data belonging to different partitions are separated into different parts. In the background, ClickHouse merges data parts for more efficient storage. Details here: https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/mergetree/#mergetree-data-storage

This is the reason you see temporary surge in disc usage.

You can try using Quotas. https://clickhouse.com/docs/en/operations/quotas/
