### ISSUE TITLE
toDecimal(1,2) returing int

### ISSUE THREAD

**Issue by alrpal** [ClickHouse/ClickHouse#39677]
running clickhouse-server, clickhouse-client Version: 22.7.1.2484

when I run a simple query like below, I'm expecting the result to be 1.00 but im getting 1.

Previously I was running version ~18 and it was returing 1.00 as expected. Not sure if this is a bug or I'm using it wrong:

```
SELECT toDecimal32(1, 2)

Query id: aeb540b7-ab1d-4477-a8c3-011eff9ba315

┌─toDecimal32(1, 2)─┐
│                 1 │
└───────────────────┘

1 row in set. Elapsed: 0.005 sec.
```

**Comment by tavplubix** [comment]
It actually returns Decimal, not Int:

```
dell9510 :) SELECT toTypeName(toDecimal32(1, 2))

SELECT toTypeName(toDecimal32(1, 2))

Query id: 916d8619-dc65-487e-9e8f-691dff948136

┌─toTypeName(toDecimal32(1, 2))─┐
│ Decimal(9, 2)                 │
└───────────────────────────────┘

1 row in set. Elapsed: 0.008 sec. 

dell9510 :) SELECT toDecimal32(1, 2) FORMAT TSVWithNamesAndTypes

SELECT toDecimal32(1, 2)
FORMAT TSVWithNamesAndTypes

Query id: 83b3db91-5e73-4417-9337-45d2b5bd8f83

toDecimal32(1, 2)
Decimal(9, 2)
1

1 row in set. Elapsed: 0.007 sec. 

```

**Comment by alrpal** [comment]
Thanks for that, I was mistaken.

**Comment by techkuz** [comment]
> @techkuz
> 
> set documentation of toDecimalString
> 
> ```sql
> set output_format_decimal_trailing_zeros=1;
> 
> SELECT toDecimal32(2, 4) AS x
> ┌──────x─┐
> │ 2.0000 │
> └────────┘
> 
> SELECT toDecimalString(toDecimal64(6, 6), 6)
> ┌─toDecimalString(toDecimal64(6, 6), 6)─┐
> │ 6.000000                              │
> └───────────────────────────────────────┘
> ```

Thanks, I guess than docs should be fixed as well
