### ISSUE TITLE
Function

### ISSUE THREAD

**Issue by bilelik** [ClickHouse/ClickHouse#39670]
Hi!

Please help if you know function that can find capital letters in brackets []. 
For example, I have a table 'text'  with column 'words'

There are different text symbols in column 'words', for example:
1. Dear [usr_name], please follow the instruction
2. This [Country_name] is wrong
... and so on
So how can I find capital letters in [] like 'Country_name' ?

Thank you in advance!

**Comment by den-crane** [comment]
```sql
SELECT
    'Dear [usr_name], please follow the instruction This [Country_name] is wrong' AS s,
    extractAll(s, '\\[(\\w+)\\]') AS g,
    arrayFilter(i -> (i != lower(i)), g) AS r

Row 1:
──────
s: Dear [usr_name], please follow the instruction This [Country_name] is wrong
g: ['usr_name','Country_name']
r: ['Country_name']

```

**Comment by bilelik** [comment]
Thank you! 
I also tried this one but it doesn't find all of the brackets in one cell

```
select a.* from 
(
select translation,
substring_index(substring_index(translation, '[', -1),
            ']', 1) as substr_tx
            FROM tran 
            where translation like ('%[%')
         ) a   
WHERE substr_tx REGEXP BINARY '[A-Z]'
```
