### ISSUE TITLE
Inconsistent behavior of back-slash escaping in json format for meta and data 

### ISSUE THREAD

**Issue by ywangtht** [ClickHouse/ClickHouse#39693]
Reproducible on 22.7.1 and 22.6.1
**How to reproduce**

SELECT 1 AS `\\"ph"`
FORMAT JSON

Query id: 0159c301-b91e-4b59-b8e1-840056d18ffb

```
{
	"meta":
	[
		{
			"name": "\\\\\\\"ph\\\"",
			"type": "UInt8"
		}
	],

	"data":
	[
		{
			"\\\"ph\"": 1
		}

	],

	"rows": 1,

	"statistics":
	{
		"elapsed": 0.000840535,
		"rows_read": 1,
		"bytes_read": 1
	}
}
```
Expected result: column name in meta and data should be the same.
Actual result: They are not.

It used to work on 22.3.15 - Even though it has another issue back then.

**Comment by alexey-milovidov** [comment]
@ywangtht They are identical in your example: 
`"\\\"ph\""`
and
`"\\\"ph\""`

**Comment by ywangtht** [comment]
@alexey-milovidov 
Sorry, I pasted wrong output.
I updated the output again.

**Comment by ywangtht** [comment]
Here is a simpler example. Where is the additional \\ from in meta/name?

SELECT 1 AS `"ph"`
FORMAT JSON

Query id: c2e3ee74-74fc-4dce-ac9d-61a0d960ff34
```

{
	"meta":
	[
		{
			"name": "\\\"ph\\\"",
			"type": "UInt8"
		}
	],

	"data":
	[
		{
			"\"ph\"": 1
		}

	],

	"rows": 1,

	"statistics":
	{
		"elapsed": 0.000580457,
		"rows_read": 1,
		"bytes_read": 1
	}
}
```

**Comment by ywangtht** [comment]
Note that there are back-ticks ` ` around column alias, but somehow github does not display them.

**Comment by alexey-milovidov** [comment]
Yes, the field is double-escaped by mistake.

**Comment by ywangtht** [comment]
It will be great to back port the fix to previous releases.
