### ISSUE TITLE
Restarting the server takes near half an hour to complete

### ISSUE THREAD

**Issue by AbrahamQll** [ClickHouse/ClickHouse#39697]
**Slow restart**
Restarting a clickhouse server with near a million records, takes almost half an hour to complete. The reason seems to be the materialize column.

**Request**
How can I get the load time of the tables to be able to figure out exactly where the performance bottleneck is?

Thank you <3

**Comment by den-crane** [comment]
please share `show create table`

**Comment by AbrahamQll** [comment]
> please share `show create table`
The identifying information was redacted from this post.

`
CREATE TABLE main.base_one
(
    `clock` DateTime('Asia/Tehran'),
    `id` UInt64,
    `unique_id` LowCardinality(String),
    `net_id` LowCardinality(String),
    `message` Nullable(String),
    `byte_message` Nullable(String),
    `result` Nullable(Int16),
    `address` Nullable(String),
    `response` LowCardinality(Nullable(String)),
    `transaction` Nullable(Enum8('None' = 0, 'F' = 1, 'Y' = 2)),
    `request` Enum8('None' = 0, 'X' = 1, 'Y' = 2, 'Z' = 3, 'W' = 4, 'R' = 5, 'S' = 6, 'U' = 7, 'V' = 8, 'A' = 9, 'L' = 10, 'I' = 11) DEFAULT 0,
    `evcode` Enum16('None' = 0, 'R' = 1, 'C' = 2, 'l' = 3, 'Q' = 4, 'S' = 5, 'U' = 6, 'p' = 7, 'd' = 8, 'n' = 9, 'e' = 10, 'M' = 11, 't' = 200, 'k' = 201, 'X' = 202, 'H' = 203, 'x' = 204) DEFAULT 0,
    `software` UInt8 DEFAULT 0,
    `r_time` Nullable(DateTime('Asia/Tehran')) DEFAULT now('Asia/Tehran') COMMENT 'receive time'
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(clock)
ORDER BY (clock, net_id, id)
SETTINGS index_granularity = 8192
========================================================
CREATE TABLE main.base_two
(
    `customer_id` String COMMENT ' customer_id',
    `clock` DateTime('Asia/Tehran') COMMENT ' clock',
    `clock_str` String ALIAS formatDateTime(clock, '%Y-%m-%d %R:%S'),
    `pt_text` Nullable(String) MATERIALIZED dictGet('main.axy_dict', 'pt_text', tuple(customer_id)),
    `ct_text` Nullable(String) MATERIALIZED dictGet('main.axy_dict', 'ct_text', tuple(customer_id)),
    `book` Nullable(String) MATERIALIZED dictGet('main.axy_dict', 'book', tuple(customer_id)),
    `a` Nullable(String) MATERIALIZED dictGet('main.axy_dict', 'a', tuple(customer_id)),
    `b` Nullable(String) MATERIALIZED dictGet('main.axy_dict', 'b', tuple(customer_id)),
    `c` Nullable(String) MATERIALIZED dictGet('main.axy_dict', 'c', tuple(customer_id)),
    `d` Nullable(Int32) MATERIALIZED dictGet('main.axy_dict', 'd', tuple(customer_id)),
    `e` Nullable(Int64) MATERIALIZED dictGet('main.axy_dict', 'e', tuple(customer_id)),
    `f` Nullable(Int64) MATERIALIZED dictGet('main.axy_dict', 'f', tuple(customer_id)),
    `g` Nullable(Int32) MATERIALIZED dictGet('main.axy_dict', 'g', tuple(customer_id)),
    `h` Nullable(Int64) MATERIALIZED dictGet('main.axy_dict', 'h', tuple(customer_id)),
    `i` Nullable(Int16) MATERIALIZED dictGet('main.axy_dict', 'i', tuple(customer_id)),
    `j` Nullable(String) MATERIALIZED dictGet('main.axy_dict', 'j', tuple(customer_id)),
    `k` Nullable(String) MATERIALIZED dictGet('main.axy_dict', 'k', tuple(customer_id)),
    `l` Nullable(String) MATERIALIZED dictGet('main.axy_dict', 'l', tuple(customer_id)),
    `m` Nullable(String) MATERIALIZED dictGet('main.axy_dict', 'm', tuple(customer_id)),
    `n` Nullable(String) MATERIALIZED dictGet('main.axy_dict', 'n', tuple(customer_id)),
    `o` Nullable(String) MATERIALIZED dictGet('main.axy_dict', 'o', tuple(customer_id)),
    `p` Nullable(String) MATERIALIZED dictGet('main.axy_dict', 'p', tuple(customer_id)),
    `q` Nullable(String) MATERIALIZED dictGet('main.axy_dict', 'q', tuple(customer_id)),
    `r` Nullable(String) MATERIALIZED dictGet('main.axy_dict', 'r', tuple(customer_id)),
    `s` Nullable(String) MATERIALIZED dictGet('main.axy_dict', 's', tuple(customer_id)),
    `t` Nullable(String) MATERIALIZED dictGet('main.axy_dict', 't', tuple(customer_id)),
    `u` Nullable(String) MATERIALIZED dictGet('main.axy_dict', 'u', tuple(customer_id)),
    `v` Nullable(String) MATERIALIZED dictGet('main.axy_dict', 'v', tuple(customer_id)),
    `w` Nullable(String) MATERIALIZED dictGet('main.axy_dict', 'w', tuple(customer_id)),
    `x` Nullable(String) MATERIALIZED dictGet('main.axy_dict', 'x', tuple(customer_id)),
    `y` Nullable(String) MATERIALIZED dictGet('main.axy_dict', 'y', tuple(customer_id)),
    `z` Nullable(String) MATERIALIZED dictGet('main.axy_dict', 'z', tuple(customer_id)),
    `aa` Nullable(String) MATERIALIZED dictGet('main.axy_dict', 'aa', tuple(customer_id)),
    `ab` Nullable(String) MATERIALIZED dictGet('main.axy_dict', 'ab', tuple(customer_id)),
    `ac` Nullable(String) MATERIALIZED dictGet('main.axy_dict', 'ac', tuple(customer_id)),
    `ad` SimpleAggregateFunction(anyLast, Nullable(Decimal(12, 0))) COMMENT 'XXXXXXXXXX',
    `ae` SimpleAggregateFunction(anyLast, Nullable(Decimal(12, 0))) COMMENT 'XXXXXXXXXX',
    `af` SimpleAggregateFunction(anyLast, Nullable(Decimal(12, 0))) COMMENT 'XXXXXXXXXX',
    `ag` SimpleAggregateFunction(anyLast, Nullable(Decimal(12, 0))) COMMENT 'XXXXXXXXXX',
    `ah` SimpleAggregateFunction(anyLast, Nullable(Decimal(12, 0))) COMMENT 'XXXXXXXXXX',
    `ai` SimpleAggregateFunction(anyLast, Nullable(Decimal(12, 0))) COMMENT 'XXXXXXXXXX',
    `aj` SimpleAggregateFunction(anyLast, Nullable(Decimal(12, 0))) COMMENT 'XXXXXXXXXX',
    `ak` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `al` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `am` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `an` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `ao` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `ap` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `aq` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `ar` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `as` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `at` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `au` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `av` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `aw` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `ax` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `ay` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `az` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `ba` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `bb` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `bc` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `bd` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `be` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `bf` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `bg` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `bh` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `bi` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `bj` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `bk` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `bl` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `bm` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `bn` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `bo` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `bp` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `bq` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `br` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `bs` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `bt` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `bu` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `bv` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `bw` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `bx` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `by` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `bz` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `ca` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `cb` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `ce` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `cf` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `cg` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `ch` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `ci` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `cj` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `ck` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `cl` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `cm` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `cn` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `co` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `cp` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `cq` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `cr` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `cs` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `ct` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `cu` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `cv` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `cw` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `cx` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `cz` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `da` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `db` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `dc` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `dd` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `de` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `df` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `dg` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `dh` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `di` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `dj` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `dk` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `dl` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `dm` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `dn` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `do` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `dp` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `dq` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `dr` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `ds` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `dt` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `du` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `dv` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `dw` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `dx` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `dz` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `ea` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `eb` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `ec` SimpleAggregateFunction(anyLast, Nullable(Decimal(18, 5))) COMMENT 'XXXXXXXXXX',
    `ed` SimpleAggregateFunction(anyLast, Nullable(DateTime('Asia/Tehran'))) DEFAULT now('Asia/Tehran') COMMENT 'XXXXXXXXXX'
)
ENGINE = AggregatingMergeTree
PARTITION BY toYYYYMMDD(clock)
ORDER BY (clock, customer_id)
SETTINGS index_granularity = 8192
========================================================
CREATE DICTIONARY main.axy_dict
(
    `a` Nullable(String),
    `b` Int32,
    `c` String,
    `d` Nullable(UInt16),
    `e` Nullable(String),
    `f` Nullable(String),
    `g` Nullable(String),
    `h` Nullable(String),
    `i` decimal(15, 2),
    `j` Nullable(String),
    `k` decimal(15, 2),
    `l` Nullable(String),
    `l` Nullable(String),
    `m` Nullable(UInt16),
    `n` Nullable(String),
    `o` Nullable(String),
    `p` Nullable(String),
    `q` Nullable(Int16),
    `r` Nullable(UInt16),
    `s` Nullable(String),
    `t` Nullable(String),
    `u` Int64,
    `v` Nullable(String),
    `w` decimal(15, 5),
    `x` Nullable(String),
    `z` Nullable(String),
    `aa` decimal(15, 5),
    `ab` Nullable(Int16),
    `ac` Nullable(String),
    `ad` Nullable(String),
    `ae` Nullable(Int16),
    `af` String,
    `ag` Nullable(Int16),
    `ah` Nullable(UInt16),
    `ai` Nullable(String),
    `aj` DateTime('Asia/Tehran'),
    `ak` Nullable(DATE),
    `al` Nullable(Int16),
    `am` Nullable(String),
    `an` Nullable(String),
    `ao` Nullable(Int8),
    `ap` Nullable(String),
    `aq` Nullable(UInt16),
    `ar` Nullable(String),
    `as` Nullable(Int8),
    `at` Nullable(String),
    `au` decimal(15, 2),
    `av` Nullable(String),
    `aw` Int16,
    `ax` Int16,
    `ay` Nullable(String),
    `az` Nullable(String),
    `ba` Nullable(Int16),
    `bb` String,
    `bc` Nullable(Int16),
    `bd` Nullable(Int32),
    `be` Nullable(String),
    `bf` Nullable(String),
    `bg` Nullable(String),
    `bh` Nullable(String),
    `bi` Nullable(String),
    `bj` Nullable(String),
    `bk` Nullable(String)
)
PRIMARY KEY b
SOURCE(POSTGRESQL(HOST '192.168.33.66' PORT 6565 USER 'user_a' TABLE 'mother_of_all_tables' SCHEMA 'master' DB 'db_db' PASSWORD 'password_goes_here___'))
LIFETIME(MIN 120 MAX 3600)
LAYOUT(COMPLEX_KEY_HASHED_ARRAY())
========================================================
CREATE TABLE main.base_three
(
    `a` Int64 DEFAULT bitOr(bitShiftLeft(toUInt64(now64()), 24), rowNumberInAllBlocks()),
    `b` String COMMENT 'b',
    `c` DateTime('Asia/Tehran'),
    `d` DateTime('Asia/Tehran'),
    `e` Nullable(UInt16) MATERIALIZED dateDiff('second', c, d),
    `f` Nullable(String),
    `g` Enum8('None' = 0, 'a' = 1, 'b' = 2, 'c' = 3),
    `h` Enum8('a' = -1, 'b' = 0, 'c' = 1, 'd' = 2, 'e' = 3, 'f' = 4, 'g' = 5) DEFAULT -1,
    `i` Int16,
    `j` Nullable(String),
    `k` Int8,
    `l` Int8,
    `m` Int64,
    `n` UInt16,
    `o` String,
    `p` String,
    `q` Int8,
    `r` UInt32,
    `s` Nullable(DateTime('Asia/Tehran')),
    `t` Nullable(DateTime('Asia/Tehran'))
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(c)
ORDER BY (c, m, b)
SETTINGS index_granularity = 8192
=======================================================
`

**Comment by den-crane** [comment]
Can you also please share `select count() from system.parts_columns;`

**Comment by alexey-milovidov** [comment]
No answer, closing.
