### ISSUE TITLE
add do_not_merge_across_partitions_select_final as default

### ISSUE THREAD

**Issue by mofei920** [ClickHouse/ClickHouse#39713]
Version: 22.3.8.39-lts

as i know before, do_not_merge_across_partitions_select_final=1 will impove performance when read from multi partitions on ReplaceMergeTree Engine，Is it necessary to use the do_not_merge_across_partitions_select_final now for the version 22.3.8.39-lts？or  is it possiable to set the parameter as default in config file? then i do not need to set the parameter in lots query.

**Comment by nickitat** [comment]
you should use this setting carefully, with understanding when it is applicable. so, I would say that it is dangerous to set it on server-wide level.
but if you sure in what you are doing, you can add it in users.xml config.

**Comment by CurtizJ** [comment]
If partition key doesn't contain any column from primary key, then you can get wrong result of query with `do_not_merge_across_partitions_select_final`.

But we can implement another optimization, that will automatically apply `do_not_merge_across_partitions_select_final` if partition key interscets primary key in at least one column (which is actuall a popular case).

**Comment by mofei920** [comment]
> But we can implement another optimization, that will automatically apply `do_not_merge_across_partitions_select_final` if partition key intersects primary key in at least one column (which is actually a popular case).

Yes，it's a good idea。
automatically apply better than add parameter.
