### ISSUE TITLE
FORMAT and SETTINGS parsing leads to errors

### ISSUE THREAD

**Issue by Scartiloffista** [ClickHouse/ClickHouse#39712]
Query parsing related to `FORMAT` and `SETTINGS` clauses is inconsistent.

`select 1 settings log_comment='test' Format {{format}}` works as intended
`(select 1) settings log_comment='test' Format {{format}}` and `(select 1) union (select 2) settings log_comment='test' Format {{format}}` give a parsing error:

```
Syntax error: failed at position 50 ('Format'):

(select 1)  settings log_comment='prova valerio' Format JSONCompact

Expected end of query
```

Queries without the `FORMAT` clause work as intended.

**Does it reproduce on recent release?**
22.7.1.2484 is affected

**How to reproduce**
Connect to clickhouse-client and run the queries

**Expected behavior**

Same behaviour between different versions

> If applicable, add screenshots to help explain your problem.

![image](https://user-images.githubusercontent.com/36407154/181772096-6d3d88e9-7909-41fe-8ab9-1490ae0818f4.png)

**Comment by tavplubix** [comment]
It's because two SETTINGS clauses are possible: before and after FORMAT:
```
dell9510 :) select 1 settings log_comment='qwerty' Format TSV settings log_comment='test'

SELECT 1
SETTINGS log_comment = 'test'
FORMAT TSV
SETTINGS log_comment = 'test'

Query id: 22453be5-776e-44f5-a3e5-768ceb92c861

1

1 row in set. Elapsed: 0.006 sec.
```

The first clause is part of `ASTSelectQuery` and the second one is part of `ASTSelectWithUnionQuery`. It looks weird and confusing in the example above, but the following example makes it a bit more clear:
```
dell9510 :) (select 1 settings log_comment='asdfgh') union all (select 2 settings log_comment='qwerty') Format TSV settings log_comment='test'


SELECT 1
SETTINGS log_comment = 'asdfgh'
UNION ALL
SELECT 2
SETTINGS log_comment = 'qwerty'
FORMAT TSV
SETTINGS log_comment = 'test'

Query id: d8ea97d4-dc82-4133-9e56-e360e2d83f0f

2
1

2 rows in set. Elapsed: 0.012 sec. 

```

See also https://github.com/ClickHouse/ClickHouse/pull/11804 and linked issues/PRs

**Comment by tavplubix** [comment]
https://github.com/ClickHouse/ClickHouse/pull/60197 was reverted: https://github.com/ClickHouse/ClickHouse/pull/68608
