### ISSUE TITLE
Odd toDateTime behavior

### ISSUE THREAD

**Issue by andrea-s** [ClickHouse/ClickHouse#3972]
83b6f0483a5c :) select toDateTime('Paris Saint-Germain');

SELECT toDateTime('Paris Saint-Germain')

┌─toDateTime(\'Paris Saint-Germain\')─┐
│                 1970-01-11 12:31:00 │
└─────────────────────────────────────┘

**Comment by alexey-milovidov** [comment]
That's technically ok: implementation specific behaviour on garbage data.

**Comment by andrea-s** [comment]
Thank you! What would be the recommended way to check wheter a field can be parsed as a datetime though? Since random strings of 19 characters seem to result in "valid" values...

**Comment by blinkov** [comment]
@andrea-s, do you have any further questions?

**Comment by alexey-milovidov** [comment]
1. Use regular expression with `match` function:
```
SELECT match('Paris Saint-Germain', '^\\d\\d\\d\\d-\\d\\d-\\d\\d[ T]\\d\\d:\\d\\d:\\d\\d$')
```

2. Use `parseDateTimeBestEffort` function:

```
SELECT parseDateTimeBestEffort('Paris Saint-Germain')

Received exception from server (version 20.4.1):
Code: 41. DB::Exception: Received from localhost:9000. DB::Exception: Cannot read DateTime: unexpected word.
```
