### ISSUE TITLE
The release binary is not stripped at the step 1 of Quick Start

### ISSUE THREAD

**Issue by katsusan** [ClickHouse/ClickHouse#39736]
**Describe the issue**

Operation: https://clickhouse.com/docs/en/quick-start#1-start-clickhouse

After doing `curl https://clickhouse.com/ | sh`, I got a 2.2GB local binary.

```
 /usr/local/src  size -A ./clickhouse                                                       
./clickhouse  :
section                    size        addr
.interp                      28     2097888
.note.ABI-tag                32     2097916
.note.gnu.build-id           24     2097948
.dynsym                12194016     2097976
.gnu.version            1016168    14291992
.gnu.version_r              272    15308160
.gnu.hash               3586344    15308432
.dynstr                73450855    18894776
.rela.dyn                   936    92345632
.rela.plt                 13344    92346568
.rodata                55384432    92360704
.gcc_except_table      10270000   147745136
.eh_frame_hdr           4405124   158015136
.eh_frame              30549764   162420264
.text                 303130319   192974144
.init                        27   496104464
.fini                        13   496104492
malloc_hook                 574   496104512
.plt                       8912   496105088
.tdata                     7016   496118144
.tbss                     25688   496125168
.fini_array                  32   496125160
.init_array                9512   496125192
.dynamic                    448   496134704
.got                        120   496135152
.bss.rel.ro                  48   496135296
.data                   1767456   496139456
.tm_clone_table               0   497906912
.got.plt                   4472   497906912
.bss                    4460488   497911424
.comment                    153           0
.debug_line           118559695           0
.debug_info           670540812           0
.debug_abbrev          12391332           0
.debug_aranges             1296           0
.debug_loc            446107968           0
.debug_ranges         122129072           0
.debug_str            261990434           0
.clickhouse.hash             32           0
Total                2132007258
```

It seems that most binary space is taken up by debugging info. I think the info is
unnecessary for these reasons:
1. Quick start is usually for ClickHouse newcomers, who are unlikely to debug it.
2. If they want to use it to debug, they need to clone clickhouse source and put to right path.
3. The download url(https://builds.clickhouse.com/master/${DIR}/clickhouse) is hosted at USA,
   for both world-wide users and CDN it can reduce considerable network overhead.

**Additional context**
// some stripped results
```
 /usr/local/src  ll clickhouse*                                                            
-rwxr-xr-x 1 root root 2.2G 7月  30 08:04 clickhouse
-rwxr-xr-x 1 root root 595M 7月  30 14:59 clickhouse-strip # strip --strip-debug clickhouse
-rwxr-xr-x 1 root root 473M 7月  30 15:04 clickhouse-stripall # strip --strip-all clickhouse
```

**Comment by alexey-milovidov** [comment]
Debug info is not only for debugging. It is useful even in absence of any bugs.
It contains the relationship between machine code and line numbers in the source code.
It allows getting line numbers in the error messages and in Query Profiler.

Although it is not needed to use ClickHouse, it is more convenient to have only one variant of the binary file, to avoid thinking if the debug info exists or not, or if should you download another file, and to make sure, that if you will need, you already have debug info in hands.

We will implement compression for this binary that will lower the size to 400 MB.

The download URL is using Cloudflare CDN. For some reason, the speed is not as fast as it can be, maybe we forgot to pay for a premium plan for that...
