### ISSUE TITLE
clickhouse keeper Keeper server rejected the connection during the handshake. Possibly it's overloaded, doesn't see leader or stale"

### ISSUE THREAD

**Issue by kiwimg** [ClickHouse/ClickHouse#39756]
What is the reason for this exception?
clickhouse version  Release v22.6.3.35-stable

Keeper server rejected the connection during the handshake. Possibly it's overloaded, doesn't see leader or stale"

<img width="1211" alt="image" src="https://user-images.githubusercontent.com/13777509/182022011-fd1e38ec-87ed-46fa-a8e5-5c133adf620a.png">

**Comment by jiangbiao910** [comment]
I have the same error!

**Comment by alexey-milovidov** [comment]
There can be one of the following reasons: possibly it's overloaded, doesn't see a leader or it is stale.

**Comment by matavital** [comment]
same error here...

**Comment by Mizoguchee** [comment]
Any fix for this ? 

Getting the Overload issue now ..

All connection tries failed while connecting to ZooKeeper. nodes: 10.100.100.1:2181
Code: 999. Coordination::Exception: Keeper server rejected the connection during the handshake. Possibly it's overloaded, doesn't see leader or stale: while receiving handshake from ZooKeeper. (KEEPER_EXCEPTION) (version 24.9.1.3278 (official build)), 10.100.100.1:2181
Code: 999. Coordination::Exception: Keeper server rejected the connection during the handshake. Possibly it's overloaded, doesn't see leader or stale: while receiving handshake from ZooKeeper. (KEEPER_EXCEPTION) (version 24.9.1.3278 (official build)), 10.100.100.1:2181
Code: 999. Coordination::Exception: Keeper server rejected the connection during the handshake. Possibly it's overloaded, doesn't see leader or stale: while receiving handshake from ZooKeeper. (KEEPER_EXCEPTION) (version 24.9.1.3278 (official build)), 10.100.100.1:2181

**Comment by rohithrqube** [comment]
systemctl stop clickhouse-keeper
rm -rf /var/lib/clickhouse/coordination/log/*
rm -rf /var/lib/clickhouse/coordination/snapshots/*
systemctl start clickhouse-keeper
