### ISSUE TITLE
Retries on ZooKeeper errors inside INSERT

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#39764]
**Use case**

When ZooKeeper nodes are distributed on different continents across the world and you are running long INSERT under high load, there is an increased chance of getting timeouts. But instead, we can do several retries trying to establish a new session with ZooKeeper, even up to several minutes.

**Comment by UnamedRus** [comment]
PR https://github.com/ClickHouse/ClickHouse/pull/41734

**Comment by devcrafter** [comment]
Should be finally closed by #43122
Retries are disabled, by default.
