### ISSUE TITLE
Not able to run zookeeper/clickhouse-keeper stateless query tests while building from source following developers guide.

### ISSUE THREAD

**Issue by SachinSetiya** [ClickHouse/ClickHouse#39765]
**Describe what's wrong**

I build the latest master, I am able to run the tests without zookeeper , but the tests with zookeeper are failing.
` 
022.07.31 20:31:46.626844 [ 228022 ] {} <Error> test_k5oc4l.quorum2 (3ef62d55-9623-4798-a788-2eb6c8cc6f50): auto DB::StorageReplicatedMergeTree::processQueueEntry(ReplicatedMergeTreeQueue::SelectedEntryPtr)::(anonymous class)::operator()(DB::StorageReplicatedMergeTree::LogEntryPtr &) const: Poco::Exception. Code: 1000, e.code() = 111, Connection refused, Stack trace (when copying this message, always include the lines below):
`
full error https://pastebin.com/bGjA0XAy
**Does it reproduce on recent release?**
Yes, I build the master branch

**How to reproduce**
I copy pasted and added (zookeeper.xml , and keeper_port.xml) in the end of config.xml in (program/server).
And then I run the clickhouse from program/server directory.
Some zookeeper test passed after I changed the config 
```

╰─$ ./tests/clickhouse-test --zookeeper  02311                                                                                                1 ↵
Using queries from '/home/sachin/ClickHouse/tests/queries' directory
Using clickhouse-client as client program (expecting split build)
Connecting to ClickHouse server................................ OK

Running 6 stateless tests (MainProcess).

02311_normalize_utf8_constant:                                          [ OK ]
02311_create_table_with_unknown_format:                                 [ OK ]
02311_system_zookeeper_insert_priv:                                     [ OK ]
02311_hashed_array_dictionary_hierarchical_functions:                   [ OK ]
02311_system_zookeeper_insert:                                          [ OK ]
02311_range_hashed_dictionary_range_cast:                               [ OK ]

6 tests passed. 0 tests skipped. 22.01 s elapsed (MainProcess).

```
But this test is always failing

```
./tests/clickhouse-test --zookeeper  00732_quorum_insert_simple_test_1_parts_zookeeper_long   
Using queries from '/home/sachin/ClickHouse/tests/queries' directory
Using clickhouse-client as client program (expecting split build)
Connecting to ClickHouse server... OK

Running 1 stateless tests (MainProcess).

00732_quorum_insert_simple_test_1_parts_zookeeper_long:                 [ FAIL ] - return code: 209
Error on processing query: Code: 209. DB::NetException: Timeout exceeded while reading from socket (127.0.0.1:9000, 300000 ms): while receiving packet from localhost:9000. (SOCKET_TIMEOUT) (version 22.8.1.1)
(query: INSERT INTO quorum1 VALUES (1, '2018-11-15');)
, result:

```

Am I missing something ?

**Comment by alexey-milovidov** [comment]
Check the configs located at /tests/config

**Comment by alexey-milovidov** [comment]
As the master branch is green, you can read the log:
https://s3.amazonaws.com/clickhouse-test-reports/0/ab5a1470659557f9a3f19681279298ab9aa31cb2/stateless_tests__release_.html
(click on runlog.log)
