### ISSUE TITLE
Replacing certificates without restarting Clickhouse

### ISSUE THREAD

**Issue by lavasser** [ClickHouse/ClickHouse#39766]
It would be nice to implement the possibility of replacing certificates.

**Conditions:**

- do not restart Clickhouse cluster nodes
- do not break the current connections and interconnects between replicas
- do not change the configuration of ```<yandex><openSSL><server>```. That is, the path to the certificates should not change.

**Comment by lavasser** [comment]
> Client certificate or server?
> 
> #15765 #15764

Server certificate

**Comment by lavasser** [comment]
I do it this way: I copy new certificates with the same names (ca.crt and node.crt, node.key) to the folder specified in ```<yandex><OpenSSL><server>```
Then I update the date of the Clickhouse configuration file:
`touch clickhouse-config.xml `
After that, clickhouse-client connects with a new certificate. This can be seen through the command
openssl s_client -connect $HOSTNAME:9440
But if I replace the certificates again, replication breaks down. Restarting the node helps. It is necessary that there is no restart after replacing the certificate.

**Comment by den-crane** [comment]
So everything is OK with Native/HTTP protocols but the problem is with Replication protocol?
Can you share how you configured secure Replication protocol ?

**Comment by lavasser** [comment]
> So everything is OK with Native/HTTP protocols but the problem is with Replication protocol? Can you share how you configured secure Replication protocol ?

``` xml 
<yandex>
	<tcp_port_secure>9440</tcp_port_secure>
	<tcp_port remove="1">9000</tcp_port>

	<interserver_http_port remove="1">9009</interserver_http_port>
	<interserver_https_port>9010</interserver_https_port>

	<remote_servers>
		<test_cluster>
			<shard>
				<replica>
					<host>host1</host>
					<port>9440</port>
					<secure>1</secure>
					<user>ch_admin</user>
					<password>12345</password>
				</replica>
				<replica>
					<host>host2</host>
					<port>9440</port>
					<secure>1</secure>
					<user>ch_admin</user>
					<password>12345</password>
				</replica>
			</shard>
		</test_cluster>
	</remote_servers>

    <openSSL>
        <server>
           <dhParamsFile>/app/clickhouse/certs/dhparam.pem</dhParamsFile>
	   <certificateFile>/app/clickhouse/certs/node.crt</certificateFile>
	   <privateKeyFile>/app/clickhouse/certs/node.key</privateKeyFile>
	   <caConfig>/app/clickhouse/certs/ca.crt<caConfig>
        </server>

        <client> <!-- Used for connecting to https dictionary source and secured Zookeeper communication -->
		<caConfig>/app/clickhouse/certs/ca.crt<caConfig>
                <invalidCertificateHandler>
                    <name>RejectCertificateHandler</name>
                </invalidCertificateHandler>
        </client>
    </openSSL>
</yandex>
```

**Comment by lavasser** [comment]
Do you have any ideas?

**Comment by lavasser** [comment]
The issue is resolved. There was a problem with the structure of certificates

**Comment by nshah14285** [comment]
Hello,
When replacing the SSL certificate for a single ClickHouse server, do I need to restart the clickhouse-server service? If yes, then is there any method to apply the new certificate without restarting the service?
Please let me know.

Thank You.
