### ISSUE TITLE
Can mysql sync to clickhouse exclude table

### ISSUE THREAD

**Issue by charliecen** [ClickHouse/ClickHouse#39769]
ClickHouse server version 21.12.3.32 (official build).

mysql  Ver 14.14 Distrib 5.7.31, for linux-glibc2.12 (x86_64) using  EditLine wrapper

CREATE DATABASE test1  ENGINE = MaterializeMySQL('localhost:3306', 'test', 'root', 'root') 

When the inserted data table field in mysql is in json format, the clickhouse synchronization fails and the data cannot be queried. How can I exclude the current table? Is there any other way to solve it?

**Comment by melvynator** [comment]
Currently we don't support exclude, but we support "includes": https://clickhouse.com/docs/en/engines/database-engines/materialized-mysql/#materialized_mysql_tables_list . A work-around will be to move the problematic table to a different database on the MySQL side.

Keep in mind also that it is an experimental feature.

**Comment by charliecen** [comment]
I use materialized_mysql_tables_list='a,b,c', but not valid.

Is it spelled incorrectly?

**Comment by charliecen** [comment]
CREATE DATABASE IF NOT EXISTS test
ENGINE = MaterializedMySQL('localhost:3306', 'test', 'root', 'root')
SETTINGS materialized_mysql_tables_list = 'user, orders'

Query id: 87700832-b5cc-4c44-aa2f-d9ebce5ebb32


0 rows in set. Elapsed: 0.001 sec.

Received exception from server (version 21.12.3):
Code: 501. DB::Exception: Received from localhost:9000. DB::Exception: Cannot create MySQL database, because Code: 115. DB::Exception: Unknown setting materialized_mysql_tables_list: for database MaterializedMySQL. (UNKNOWN_SETTING),. (CANNOT_CREATE_DATABASE)

**Comment by charliecen** [comment]
clickhouse-server]# clickhouse-client  --host 127.0.0.1 --port 9900
ClickHouse client version 22.7.1.2484 (official build).
Connecting to 127.0.0.1:9900 as user default.
Connected to ClickHouse server version 22.7.1 revision 54457.

It can be solved after upgrading clickhouse， thinks
