### ISSUE TITLE
When upgrade to 22.7.1.2484  from 21.8.14.5, server crash because of "<Error> Application: Not found: profiles.default.background_merges_mutations_concurrency_ratio"

### ISSUE THREAD

**Issue by Sallery-X** [ClickHouse/ClickHouse#39768]
2022.08.01 17:03:54.093648 [ 42 ] {} <Error> Application: Not found: profiles.default.background_merges_mutations_concurrency_ratio

my users.xml  is as follows: 
![image](https://user-images.githubusercontent.com/45587738/182114406-9944ef08-4994-4915-b110-5aceb01ebe5b.png)

**Comment by melvynator** [comment]
Did you try to remove this setting from the configuration file since the default is 2?
