### ISSUE TITLE
Question: TLS Certificates

### ISSUE THREAD

**Issue by PascalWithopf** [ClickHouse/ClickHouse#3977]
Hi,
I want to establish a TLS connection with ClickHouse using Certificates.
I have created the certificates as described in the standard configuration and am using the default CA file.

How do I create the certificates for the client? And is it possible to authenticate with the certificates so I don't need to provide the user and password extra?

Thanks

**Comment by filimonov** [comment]
Theoretically it should work. You need to provide openssl parameters in client config file ([like here](https://github.com/yandex/ClickHouse/blob/0eed697623afd251c1908073c4a2850a9bfc9cdc/dbms/tests/client-test.xml)) and set up your client certificate parameters like described [here](https://pocoproject.org/docs/Poco.Net.SSLManager.html)
