### ISSUE TITLE
clickhouse-client does not respect server profile settings for insert processing

### ISSUE THREAD

**Issue by genzgd** [ClickHouse/ClickHouse#39779]
Some settings in the clickhouse-server are not respected when processing INSERTs in clickhouse-client.  In particular, if `input_format_skip_unknown_fields` is set for the user/profile, the setting is ignored when executing an INSERT INTO query from clickhouse-client.

This behavior is seen in 22.6.1 as well as 22.2.2, and presumably other releases.

To reproduce on ClickHouse 22.6.1:

(1) Set `input_format_skip_unknown_fields=0` in the default profile:

```
<profiles>
        <default>
            <input_format_skip_unknown_fields>0</input_format_skip_unknown_fields>
        </default>
</profiles>
```

(2) Create a simple test table:

```
CREATE TABLE default.skip_test
(
    `key` UInt32,
    `value` String
)
ENGINE = MergeTree
ORDER BY key
```

(3) Execute the following with clickhouse-client:

```
echo '{"key": 3, "value": "value", "unknown": "unknown"}' | ./clickhouse client --query="INSERT INTO skip_test FORMAT JSONEachRow"
```

This should fail because of the unknown field (and it does if using a query level setting).

```
echo '{"key": 3, "value": "value", "unknown": "unknown"}' | ./clickhouse client --query="INSERT INTO skip_test FORMAT JSONEachRow" --input_format_skip_unknown_fields=0

Code: 117. DB::Exception: Unknown field found while parsing JSONEachRow format: unknown: (at row 1)
: While executing ParallelParsingBlockInputFormat: data for INSERT was parsed from stdin: (in query: INSERT INTO skip_test FORMAT JSONEachRow). (INCORRECT_DATA)
```

Note that on ClickHouse 22.2 the default for input_format_skip_unknown_fields is 1, so it fails in the "reverse" way.  That is, inserts that should success fail unless sending ` --input_format_skip_unknown_fields=0` with the query.

**Comment by den-crane** [comment]
related https://github.com/ClickHouse/ClickHouse/issues/24164
