### ISSUE TITLE
Support TTL for EmbeddedRocksDB

### ISSUE THREAD

**Issue by roncohen** [ClickHouse/ClickHouse#39789]
**Use case**

We've considered using RocksDB to cache some results. It's great to have cached results directly in Clickhouse because we can then use them in other queries directly. For example, store a few rows that are very heavy to compute as JSON in a RocksDB table and JOIN with some live data from other tables. Unfortunately, EmbeddedRocksDB does not support deletions or TTL despite RocksDB having built in TTL support.

**Describe the solution you'd like**

Ability to set a TTL for EmbeddedRocksDB. RocksDB natively supports TTL so it could just be a "pass-through": https://github.com/facebook/rocksdb/wiki/Time-to-Live

**Comment by Lloyd-Pottiger** [comment]
I would like to work on it, could you please assign it to me?

**Comment by den-crane** [comment]
> I would like to work on it, could you please assign it to me?

assigned

**Comment by Lloyd-Pottiger** [comment]
> > I would like to work on it, could you please assign it to me?
> 
> assigned

thank you very much~ I will talk about my ideas here later.

**Comment by Lloyd-Pottiger** [comment]
@roncohen @den-crane hello, maybe we can just replace `rocksdb::DBWithTTL` with `rocksdb::DB`.
https://github.com/ClickHouse/ClickHouse/blob/b4f5d9ca10b2ee4285fce354c232b8d50c829380/src/Storages/RocksDB/StorageEmbeddedRocksDB.h#L77

And the add two member variables `int32_t ttl = 0` and `bool read_only = false` into class `StorageEmbeddedRocksDB`
https://github.com/ClickHouse/ClickHouse/blob/b4f5d9ca10b2ee4285fce354c232b8d50c829380/src/Storages/RocksDB/StorageEmbeddedRocksDB.h#L30-L35

**Comment by Lloyd-Pottiger** [comment]
implemented in #39986 

I think this issue can be closed.

**Comment by roncohen** [comment]
thanks!
