### ISSUE TITLE
New function: throwError

### ISSUE THREAD

**Issue by ramazanpolat** [ClickHouse/ClickHouse#39793]
Is there any way to manually make CH throw a specific error?

Something like this:
```sql
SELECT throwError(999);

Received exception from server (version 22.2.2):
Code: 999. DB::Exception: KEEPER_EXCEPTION ...
```

PS:
*Although there is a similar function (`throwIf`), it only returns code=395 (FUNCTION_THROW_IF_VALUE_IS_NON_ZERO).*

**Use case**

We're looking something like this so we can simulate errors and take relevant actions agains some errors.

**Comment by filimonov** [comment]
> We're looking something like this so we can simulate errors and take relevant actions agains some errors.

Is it needed for building / debugging some client library? 

Maybe for some subset of error you can just create a scenario in clickhouse leading to that error? 
Or use some mock WS which will return needed data?

**Comment by Algunenano** [comment]
I find this useful as well to test exceptions on an application built on top of ClickHouse; for example, verify the behaviour when you reach `TOO_MANY_PARTS`.

It can be done through mocking, or by forcing CH to trigger the exception by normal means, but something like this could be a simpler way to inject errors. Maybe there are better ways though.

**Comment by ramazanpolat** [comment]
@filimonov 
> Is it needed for building / debugging some client library?

We'll be using it for testing purposes. 
* To react against some specific errors (e.g. retry insert, only if it is failed because of error code X)
* To use different alert levels for some specific error codes.
* To see how our software reacts to different errors.

> Maybe for some subset of error you can just create a scenario in clickhouse leading to that error?

It is practically impossible to create a scenario for each and every error. Even for a subset of errors, it is not feasible to make it happen because it takes too much time and resource (e.g. Too Many Parts, Keeper Exception, Memory Limit Exceeded, ...)

**Comment by alexey-milovidov** [comment]
Ok. It can be an extension for `throwIf` with an additional argument.
But it should be disabled by default and enabled only with a special configuration.

Because we don't want to have "fake errors" in normal environments.
