### ISSUE TITLE
Create Projection error

### ISSUE THREAD

**Issue by yangshike** [ClickHouse/ClickHouse#39806]
when i create  projection use :
 alter table t_customer add projection p1(
                select id  order by mobile_encrypt
                );
i forget add select mobile_encrypt.  so . I got error in system.mutations:
 Code: 10. DB::Exception: Not found column mobile_encrypt in block. There are only columns: id. (NOT_FOUND_COLUMN_IN_BLOCK) (version 22.6.3.35 (official build))

what can  i do  when i got tihis error？

**Comment by yangshike** [comment]
Unfortunately， 
I've been waiting for a while. The mistake hasn't disappeared yet。
so  I  do :
>alter table t_customer drop projection p1;
then i got two tasks in system.mutations:
one with error info  :  (MATERIALIZE PROJECTION p1) Code: 582. DB::Exception: There is no projection p1 in table. (NO_SUCH_PROJECTION_IN_TABLE) (version 22.3.3.44 (official build))

two Always waiting :   DROP PROJECTION p1 

What can I do to make this mistake disappear  and  Recreate projection p1 

despairing ！！！
Looking forward to your reply

**Comment by den-crane** [comment]
Can you please share reproducible example?

**Comment by yangshike** [comment]
create table xxx (
id Int32,
id2 Int32,
id3 Int32
) engine =…………
alter table xxx add projection p1 (select id1 order by id2 ); alter table xxx materialize projection p1;
then , you will got this error;

But, Finally! I    I found a solution

：   KILL MUTATION where mutation_id = 'xxx' ,   then every thing is ok !!!

**Comment by yangshike** [comment]
thank you very much!!
