### ISSUE TITLE
Wrong result of intersect

### ISSUE THREAD

**Issue by ucasfl** [ClickHouse/ClickHouse#39818]
```sql
select 1 from numbers(10) intersect select 1 from numbers(10)

SELECT 1
FROM numbers(10)
INTERSECT
SELECT 1
FROM numbers(10)

Query id: 9f2d11c5-269c-41dc-9b4c-8f1423aafcc7

┌─1─┐
│ 1 │
│ 1 │
│ 1 │
│ 1 │
│ 1 │
│ 1 │
│ 1 │
│ 1 │
└───┘

8 rows in set. Elapsed: 0.002 sec. 
```

**Comment by kssenii** [comment]
Related to https://github.com/ClickHouse/ClickHouse/issues/39787. To get your behaviour need to implement `intersect distinct`.

**Comment by ucasfl** [comment]
> Related to #39787. To get your behaviour need to implement `intersect distinct`.

But it's also strange that the result have 8 rows, and it will produce different results when execute it more than one time.

**Comment by kssenii** [comment]
oh, did not notice it was 8 rows and not 10
