### ISSUE TITLE
antlr4 files do not support cte

### ISSUE THREAD

**Issue by qianmoQ** [ClickHouse/ClickHouse#39810]
> You have to provide the following information whenever possible.

antlr4 files do not support cte

https://github.com/ClickHouse/ClickHouse/blob/master/utils/antlr/ClickHouseLexer.g4
https://github.com/ClickHouse/ClickHouse/blob/master/utils/antlr/ClickHouseParser.g4

**Does it reproduce on recent release?**

[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

**Enable crash reporting**

**How to reproduce**

* Compile antlr4 syntax file （in java maven）
* use code

```sql
with 
t0 AS (select 1),
t1 AS (select 2)
select * from t0, t1
```

**Expected behavior**

> A clear and concise description of what you expected to happen.

**Error message and/or stacktrace**

```
line 2:3 missing SELECT at 'AS'
```

**Additional context**

None

**Comment by tavplubix** [comment]
Unfortunately, antlr4 files are abandoned (and not officially supported)

**Comment by qianmoQ** [comment]
Supported
