### ISSUE TITLE
Table system.query_log does't exist

### ISSUE THREAD

**Issue by AceHCL** [ClickHouse/ClickHouse#39821]
After  creating clickhouse server instance, not executing any sql query. When execute `select * from remote(${address},system.query_log,${user},${password})` by `http protocol`, i get `Table system.query_log does't not exist` error.
when enter`clickhouse client` terminal, execute such as `select 1`, execute `select * from remote(.......)` again, it is successful.
Do `query_log` init after executing query sql ?
why?

**Comment by den-crane** [comment]
https://clickhouse.com/docs/en/sql-reference/statements/system/#flush-logs

**Comment by den-crane** [comment]
see flush_interval_milliseconds

```
    <query_log>
        <!-- What table to insert data. If table is not exist, it will be created.
             When query log structure is changed after system update,
              then old table will be renamed and new table will be created automatically.
        -->
        <database>system</database>
        <table>query_log</table>
        <!--
            PARTITION BY expr: https://clickhouse.com/docs/en/table_engines/mergetree-family/custom_partitioning_key/
            Example:
                event_date
                toMonday(event_date)
                toYYYYMM(event_date)
                toStartOfHour(event_time)
        -->
        <partition_by>toYYYYMM(event_date)</partition_by>
        <!--
            Table TTL specification: https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/mergetree/#mergetree-table-ttl
            Example:
                event_date + INTERVAL 1 WEEK
                event_date + INTERVAL 7 DAY DELETE
                event_date + INTERVAL 2 WEEK TO DISK 'bbb'

        <ttl>event_date + INTERVAL 30 DAY DELETE</ttl>
        -->

        <!-- Instead of partition_by, you can provide full engine expression (starting with ENGINE = ) with parameters,
             Example: <engine>ENGINE = MergeTree PARTITION BY toYYYYMM(event_date) ORDER BY (event_date, event_time) SETTINGS index_granularity = 1024</engine>
          -->

        <!-- Interval of flushing data. -->
        <flush_interval_milliseconds>7500</flush_interval_milliseconds>
    </query_log>
```

**Comment by AceHCL** [comment]
> query_log is created during 7 seconds interval after the first insert into query_log
Thanks for your answer.   

 I have a scenes: SQL history statistics.  Our `clickhouse server` with `chproxy`, we query `system.query_log` by http for visiting `chproxy`, but random route CH node, the result is different。So i use `select * remote(....)` way to replace `select * from system.query_log`, but got `Table query_log does't not exist` first time.

`Flush force` and `set query_log settings` are helpless for me, There are some good ideas to meet my need?

**Comment by xzy256** [comment]
why lazy create `system.query_log` instead of auto creating it after server startup like `system.clusters`.
