### ISSUE TITLE
Question about something similar to secondary indexes in ClickHouse

### ISSUE THREAD

**Issue by arunmarathe** [ClickHouse/ClickHouse#39828]
Is there something similar to secondary indexes in ClickHouse?
My guess is not, but it's possible I am unaware of some tricks that can accomplish something similar.

Take for example, TPC-H's Lineitem table. Its primary key is (l_orderkey, l_linenumber), and so it makes
sense to set it as PRIMARY KEY (l_orderkey, l_linenumber) clause of CREATE TABLE statement.
That still leaves ORDER BY clause available, and that can be used for something similar to secondary
index. I can add ORDER BY (l_orderkey, l_linenumber, l_shipdate) for example as long as I include PK
as a prefix. But only one ORDER BY clause can be present which limits choice.

Apart from the above, the only other tricks to make available something similar to secondary indexes
(but not quite) are the SummingMergeTree and AggregationMergeTree engines.

Am I missing some other tricks?

Thanks,
Arun

**Comment by den-crane** [comment]
>Am I missing some other tricks?

Usually OLAP databases and TPC-H not require index access because secondary indexes are very slow (you need to read an index sequentially (random I/O) + jump to the table (random I/O)).

**Comment by den-crane** [comment]
check skip indexes and projections

**Comment by arunmarathe** [comment]
> > Am I missing some other tricks?
> 
> Usually OLAP databases and TPC-H does not require index access because secondary indexes are very slow (you need to read an index sequentially (random I/O) + jump to the table (random I/O)).

Why would reading an index sequentially cause random I/O? It will be sequential I/O.
Jumping to the table itself will cause random I/O, I agree, but the point is: if you have
already zoomed in on a tiny fraction of the data using sequential I/O enabled by a 
secondary index, one can pay the price of random I/O to a base table. That will be a net win.

Thanks,
Arun

**Comment by arunmarathe** [comment]
> check skip indexes and projections

Thanks; I will check them out. My initial impression is that skip indexes are more relevant.

**Comment by den-crane** [comment]
>Why would reading an index sequentially cause random I/O?

It depends on how you store your index. Usually in OLTP databases with b+ tree indexes you need random jumps because the next index page can be stored anywhere on the disk because otherwise you need to move all tail pages to insert data into the middle.

**Comment by arunmarathe** [comment]
> > Why would reading an index sequentially cause random I/O?
> 
> It depends on how you store your index. Usually in OLTP databases with b+ tree indexes you need random jumps because the next index page can be stored anywhere on the disk because otherwise you need to move all tail pages to insert data into the middle with a page split.

Yes, but there are index "rebuild" and "reorg" operations which can remove fragmentation nicely. The former is simply drop and recreate of the index. You need to run these operations only occasionally.

**Comment by den-crane** [comment]
Anyway inverted indexes are under development https://github.com/ClickHouse/ClickHouse/issues/37216
you will be able your ideas soon.
