### ISSUE TITLE
Is there any support for using hfs engine on arm64?

### ISSUE THREAD

**Issue by flyfox0928** [ClickHouse/ClickHouse#39846]
I use ch's hdfs engine in my application, now need to migrate from x86 to arm64 nodes.
But after installing official arm packages and running the application, ch shows some error info like "not support hdfs"
Appreciate it if someone tell me the root cause why not support, or is there any way we can make it working ?

**Comment by lhuang09287750** [comment]
I've worked it out recently
will give a PR soon

**Comment by alexey-milovidov** [comment]
We don't support HDFS.
