### ISSUE TITLE
alter table xxx delete where f1='if101' fail

### ISSUE THREAD

**Issue by submergerock** [ClickHouse/ClickHouse#3984]
I use  alter table xxx delete where f1='if101'  in dbeaver. Use select * from table, find that the data still exists in the table.This phenomenon was discovered after using the same condition delete multiple times.
![image](https://user-images.githubusercontent.com/2242678/50678578-544d2400-103a-11e9-88c3-4317aca893f9.png)

**Comment by submergerock** [comment]
os:centos7.5 kernel:3110
create table bpmtp.bpm_tp_ind_result_local(
       tran_seq     UInt64,    
       tran_date    Date,        
       data_time    DateTime,   
       ind_no       String,     
       ind_name     String,  
       ind_value    Float64,
       ccy          String, 
       dim_one      String,
       dim_two      String,
       company_code String
)ENGINE=ReplicatedMergeTree('/clickhouse/tables/bpm_tp_ind_result_local','ck01')
PARTITION BY tran_date          
ORDER BY (data_time);

**Comment by submergerock** [comment]
SELECT table, create_time, command, is_done
FROM system.mutations 
ORDER BY create_time DESC

table             |create_time         |command                                                                                         |is_done |
------------------|--------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------|
bpm_tp_ind_flow   |2019-01-04 09:38:18 |DELETE WHERE (ind_no IN 'PT0011') AND (client_name = '肖无')                                    |1       |
bpm_tp_ind_result |2019-01-04 08:07:32 |DELETE WHERE (toDateTime(data_time) = toDateTime('2017-12-06 01:45:11')) AND (ind_no = 'GL0043')|0       |
bpm_tp_ind_result |2019-01-04 08:07:06 |DELETE WHERE (toDateTime(data_time) = toDateTime('2017-12-06 01:45:11')) AND (ind_no = 'GL0043')|0       |
bpm_tp_ind_result |2019-01-04 08:07:01 |DELETE WHERE (toDateTime(data_time) = toDateTime('2017-12-06 01:45:11')) AND (ind_no = 'GL0043')|0       |

**Comment by filimonov** [comment]
@submergerock your mutations has status is_done = 0, so they are either failed, either still working. 

Select all columns from system.mutations to see what's exactly is going on.

**Comment by den-crane** [comment]
outdated, no repro
