### ISSUE TITLE
`Not implemented for SerializationObject: While executing BinaryRowInputFormat.` when insert JSON as string

### ISSUE THREAD

**Issue by zhicwu** [ClickHouse/ClickHouse#39866]
With table `test_insert_json(a Int32, b JSON)engine=Memory`, `insert into test_insert_json format RowBinary` or `insert into test_insert_json select a, b from input('a Int32, b JSON')` using RowBinary format via http interface will end up with below error:
```
Code: 48. DB::Exception: Not implemented for SerializationObject: While executing BinaryRowInputFormat. (NOT_IMPLEMENTED) (version 22.7.2.15 (official build))
```

Changing the query to `insert into test_insert_json select a, b from input('a Int32, b String')` (replace `JSON` to `String` or even `Nullable(String)`) works well.

**Comment by alexey-milovidov** [comment]
The JSON data type is not supported.
