### ISSUE TITLE
Strange behaviour Converting from MergeTree to ReplicatedMergeTree

### ISSUE THREAD

**Issue by yurigazinskiy** [ClickHouse/ClickHouse#3987]
I want to change my tables ENGINE from MergeTree to ReplicatedMergeTree.
I followed the instructions [docs](https://clickhouse.yandex/docs/en/operations/table_engines/replication/)
* Renamed existing MergeTree table
* Created ReplicatedMergeTree table with old name.
* Moved data from MergeTree table directory to newly created tables *detached* directory.
* There are 2 partitions 201812 and 201901. Executed the alter command

ALTER TABLE  mytable ATTACH PARTITION 201812;

It says ok but count() returns 0.

This is the log from clickhouse-server.log file

"(StorageReplicatedMergeTree) Looking for parts for partition 19840401 in detached"

clickhouse version = 18.14.15

**Comment by filimonov** [comment]
19840401 doesn't sound like 201812. What partition key do you  use (on both tables)?

**Comment by yurigazinskiy** [comment]
partition key is  *insertdate Date DEFAULT toDate(now())*

**Comment by yurigazinskiy** [comment]
I think its related with MergeTreePartition::getID function [source code](https://github.com/yandex/ClickHouse/blob/cec49357da502c511e006ea8b5d8fbffeb521478/dbms/src/Storages/MergeTree/MergeTreePartition.cpp)
Behaves different for mergetree and replicatedmergetree.

**Comment by den-crane** [comment]
>It says ok

ATTACH PARTITION  just iterates detached folder and looking for accessible and suitable parts and returns OK if found nothing.

ALTER TABLE xp  ATTACH PARTITION 9999
Ok.

In your case partitions had names like '2018-12-31' and CH converted 201812 toDate and got something like '1984-04-01'

**Comment by blinkov** [comment]
@yurigazinskiy, do you have any further questions?
