### ISSUE TITLE
libhdfs3 Illegal instruction on source build...

### ISSUE THREAD

**Issue by mcarbonneaux** [ClickHouse/ClickHouse#3988]
I have cloned last stable with `git clone --recursive --branch stable https://github.com/yandex/ClickHouse.git`.

```
# git describe --tags
v18.16.1-stable
```

i'm on rhel7, and i use rhscl gcc 7... and i've compiled without problem the 18.14.15...

```
# mkdir build
# cd build
# cmake3 -DCMAKE_INSTALL_PREFIX:PATH=/product/clickhouse ..
```

i use cmake3 and the cmake phase has worked fine... 

But when i've done make they stop à 59% on libhdfs3...
```
# make -j4 

[ 59%] Running C++ protocol buffer compiler on /product/src/ClickHouse/contrib/libhdfs3/src/proto/datatransfer.proto
/bin/sh: line 1: 17828 Illegal instruction     ../protobuf/cmake/protoc --cpp_out /product/src/ClickHouse/build/contrib/libhdfs3-cmake -I /product/src/ClickHouse/contrib/libhdfs3/src/proto /product/src/ClickHouse/contrib/libhdfs3/src/proto/datatransfer.proto
make[2]: *** [contrib/libhdfs3-cmake/datatransfer.pb.cc] Error 132
make[1]: *** [contrib/libhdfs3-cmake/CMakeFiles/hdfs3.dir/all] Error 2
```

**Comment by filimonov** [comment]
# Which cmake flags did you use?
# What is your cpu / platform?
# Can you provide full ninja and cmake output?

**Comment by mcarbonneaux** [comment]
-     Which cmake flags did you use?
`cmake3 -DCMAKE_INSTALL_PREFIX:PATH=/product/clickhouse ..`

-     What is your cpu / hw platform?
i compile on amd (without sse 4.2) and execute on intel with sse2...
* AMD Opteron(tm) Processor 6176
* Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz

-     Can you provide full ninja / cmake output?
how to do that ? (i'm not cmake expert...)

**Comment by alexey-milovidov** [comment]
@proller How the user can disable SSE4 from the command line?

**Comment by proller** [comment]
`cmake -DHAVE_SSE42=0 -DHAVE_SSE41=0 -DHAVE_POPCNT=0 ..`
