### ISSUE TITLE
Include ClickHouse to Apache Ambari and Apache Bigtop

### ISSUE THREAD

**Issue by kevinw66** [ClickHouse/ClickHouse#39899]
### Discussed in https://github.com/ClickHouse/ClickHouse/discussions/39889

<div type='discussions-op-text'>

<sup>Originally posted by **kevinw66** August  4, 2022</sup>
Hi ClickHouse community,

After the resurrection of Apache Ambari<sup>[[1]]</sup>, the community wants to support more bigdata-related components, and Ambari will use the components provided by Apache Bigtop<sup>[[2]]</sup> by default, so we are considering to add ClickHouse to Bigtop stack<sup>[[3]]</sup>, for future user's ability to deploy and manage ClickHouse on Ambari.
Adding ClickHouse to Bigtop requires compiling ClickHouse from source code, providing smoke tests, writing RPM/DEB build scripts to provide packages that support multiple distros and archs.

But before adding, there are two more questions we need to discuss with you.

1、if there are any license conflicts with Apache License(ClickHouse and it's dependencies)?
2、if there are any restrictions or concerns from ClickHouse community?

[1]: https://ambari.apache.org/
[2]: https://bigtop.apache.org/
[3]: https://cwiki.apache.org/confluence/display/BIGTOP/Bigtop+3.1.0+Release</div>

**Comment by alexey-milovidov** [comment]
> 1、if there are any license conflicts with Apache License(ClickHouse and it's dependencies)?

No.

> 2、if there are any restrictions or concerns from ClickHouse community?

No.

> Adding ClickHouse to Bigtop requires compiling ClickHouse from source code, providing smoke tests, writing RPM/DEB build scripts to provide packages that support multiple distros and archs.

We use portable binaries - a single binary without dependencies run for any Linux distribution, and is wrapped in .deb, .rpm as well. No need to have more than a single universal build.

**Comment by kevinw66** [comment]
> > 1、if there are any license conflicts with Apache License(ClickHouse and it's dependencies)?
> 
> No.
> 
> > 2、if there are any restrictions or concerns from ClickHouse community?
> 
> No.
> 
> > Adding ClickHouse to Bigtop requires compiling ClickHouse from source code, providing smoke tests, writing RPM/DEB build scripts to provide packages that support multiple distros and archs.
> 
> We use a portable binary - a single binary without dependencies that runs on any Linux distribution, and is wrapped in .deb, .rpm, .tgz as well. No need to have more than a single universal build. See also https://notes.volution.ro/v1/2022/01/notes/fbf3f06c/ I don't recommend maintaining any packaging scripts other than those ClickHouse is already using.

Thank you @alexey-milovidov , I'll talk to community and make final decision.
