### ISSUE TITLE
What does the 'Current memory usage' recorded in the log mean?

### ISSUE THREAD

**Issue by xhsky** [ClickHouse/ClickHouse#39891]
```clickhouse-server.log
<Debug> MemoryTracker: Current memory usage (for query): 1.00 GiB.                                                                        
<Debug> MemoryTracker: Current memory usage (for query): 2.00 GiB.
....
```
I found that the memory recorded in the log does not match the memory used by the clickhouse service (the memory in the log is much larger). And the process of sql is affected by the memory in the log. If this value exceeds the physical memory, an error will be reported as memory exceeded (but the memory used by clickhouse is far from the size of the physical memory).
how to solve memory problem?

**Comment by alexey-milovidov** [comment]
It is the amount of allocated memory. The allocated memory can contain pages of virtual memory that are not used at this moment. It can be greater than the amount of physical memory, but most of the time it is consistent. Nevertheless, this is the only way to track how much memory is used and to apply the limitations.

**Comment by xhsky** [comment]
> It is the amount of allocated memory. The allocated memory can contain pages of virtual memory that are not used at this moment. It can be greater than the amount of physical memory, but most of the time it is consistent. Nevertheless, this is the only way to track how much memory is used and to apply the limitations.

What I'm currently encountering is that the two memory values do not match at all, about ten times the difference. And, this memory size in the log seems to be controlled by the max_memory_usage parameter? If this parameter is set to physical memory, when the actual memory used is very small, the memory in the log has reached the limit, and then an error is reported. what to do with this
