### ISSUE TITLE
Error ATTEMPT_TO_READ_AFTER_EOF after trying to load protobuf data from kafka topic

### ISSUE THREAD

**Issue by vla4253** [ClickHouse/ClickHouse#39897]
I have a topic on kafka server with one protobuf byte array object with value containing single string "abc". The proto schema of the object is:
syntax = "proto2";

message SimpleExample {
  required string sessionId = 1;
};

In clickhouse I also have this schema defined in clickhouse/format_schemas/schemafile.proto
syntax = "proto2";

message SimpleExample {
  required string sessionId = 1;
};

Then I am trying to download this data to database called "dataM" via clickhouse executing the following commands:

CREATE TABLE dataM.units (
   sessionId String
) Engine = MergeTree
ORDER BY (sessionId);

CREATE TABLE dataM.units_queue (
   sessionId String
)
ENGINE = Kafka
SETTINGS kafka_broker_list = 'kafkaIp:9092',
              kafka_topic_list = 'example3',
              kafka_group_name = 'group1',
              kafka_format = 'Protobuf',
              kafka_schema = 'schemafile.proto:SimpleExample';

CREATE MATERIALIZED VIEW dataM.units_queue_mv TO dataM.units AS
SELECT sessionId
FROM dataM.units_queue

After these operations I get the error with following stacktrace
<Error> void DB::StorageKafka::threadFunc(size_t): Code: 32. DB::Exception: Attempt to read after eof: while parsing Kafka message (topic: example3, partition: 0, offset: 0)': While executing Kafka. (ATTEMPT_TO_READ_AFTER_EOF), Stack trace (when copying this message, always include the lines below):

 

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xba0d0da in /usr/bin/clickhouse

1. DB::ReadBuffer::throwReadAfterEOF() @ 0xba76e5b in /usr/bin/clickhouse

2. ? @ 0x1784ecae in /usr/bin/clickhouse

3. DB::ProtobufReader::ignoreGroup() @ 0x1784f18c in /usr/bin/clickhouse

4. DB::ProtobufReader::readFieldNumber(int&) @ 0x1784f21c in /usr/bin/clickhouse

5. DB::(anonymous namespace)::ProtobufSerializerMessage::readRow(unsigned long) (.5148c01914a435fef48b1981c9fd26f3) @ 0x17848457 in /usr/bin/clickhouse

6. DB::ProtobufRowInputFormat::readRow(std::__1::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn> > >&, DB::RowReadExtension&) @ 0x17855cad in /usr/bin/clickhouse

7. DB::IRowInputFormat::generate() @ 0x17740713 in /usr/bin/clickhouse

8. DB::ISource::tryGenerate() @ 0x176d4e95 in /usr/bin/clickhouse

9. DB::ISource::work() @ 0x176d4a26 in /usr/bin/clickhouse

10. DB::StreamingFormatExecutor::execute() @ 0x176fa204 in /usr/bin/clickhouse

11. DB::KafkaSource::generateImpl() @ 0x15de31e2 in /usr/bin/clickhouse

12. DB::KafkaSource::generate() @ 0x15de5c8f in /usr/bin/clickhouse

13. DB::ISource::tryGenerate() @ 0x176d4e95 in /usr/bin/clickhouse

14. DB::ISource::work() @ 0x176d4a26 in /usr/bin/clickhouse

15. DB::ExecutionThreadContext::executeTask() @ 0x176f0877 in /usr/bin/clickhouse

16. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x176e5abe in /usr/bin/clickhouse

17. DB::PipelineExecutor::executeImpl(unsigned long) @ 0x176e4b81 in /usr/bin/clickhouse

18. DB::PipelineExecutor::execute(unsigned long) @ 0x176e4918 in /usr/bin/clickhouse

19. DB::CompletedPipelineExecutor::execute() @ 0x176e3628 in /usr/bin/clickhouse

20. DB::StorageKafka::streamToViews() @ 0x15dd8787 in /usr/bin/clickhouse

21. DB::StorageKafka::threadFunc(unsigned long) @ 0x15dd68d8 in /usr/bin/clickhouse

22. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x15a1ba98 in /usr/bin/clickhouse

23. DB::BackgroundSchedulePool::threadFunction() @ 0x15a1ead6 in /usr/bin/clickhouse

24. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) @ 0x15a1f8ee in /usr/bin/clickhouse

25. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xbad59b7 in /usr/bin/clickhouse

26. void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) @ 0xbad8c9d in /usr/bin/clickhouse

27. start_thread @ 0x8ea7 in /usr/lib/x86_64-linux-gnu/[libpthread-2.31.so](http://libpthread-2.31.so/)

28. clone @ 0xfddef in /usr/lib/x86_64-linux-gnu/[libc-2.31.so](http://libc-2.31.so/)

(version 22.7.1.2033 (official build))

**Comment by alexey-milovidov** [comment]
If your messages in the Kafka topic are formatted as length-prefixed Protobuf, you can use the `Protobuf` format,
but if your messages represent a single Protobuf object without the length prefix, you should use the `ProtobufSingle` format.
