### ISSUE TITLE
hide password in process list

### ISSUE THREAD

**Issue by mofei920** [ClickHouse/ClickHouse#39890]
> v22.3.8.39-lts

Can I hide password in process list  when making a remote() or mysql() query? 
or is it possible to forbid query system.processes on some users?

**Comment by den-crane** [comment]
I believe it's possible using named-collections
https://clickhouse.com/docs/en/operations/named-collections/

https://github.com/ClickHouse/ClickHouse/issues/39554#issuecomment-1193974893


https://github.com/ClickHouse/ClickHouse/blob/5c6b84c398017256d47bc381dc7227371a522b6f/tests/config/config.d/named_collection.xml

https://github.com/ClickHouse/ClickHouse/blob/4667ea78838148572713ea7b20d67585d1f59fb7/tests/queries/0_stateless/02046_remote_table_function_named_collections.sql
