### ISSUE TITLE
NO_SUCH_COLUMN_IN_TABLE Error after removing the column

### ISSUE THREAD

**Issue by kant777** [ClickHouse/ClickHouse#39892]
I am seeing the following logs continuously in CH logs

```
(in query: INSERT INTO myapp.events (id, timestamp, db_timestamp, raw_timestamp, clickhouse_timestamp, name, body, `attributes.key`, `attributes.value`) VALUES), Stack trace (when copying this message, always include the lines below):
2022.08.03 14:56:28.037875 [ 4268 ] {3933b537-7c49-4d9d-aeb8-f3be9ac7e227} <Error> TCPHandler: Code: 16. DB::Exception: No such column raw_timestamp in table myapp.events. (NO_SUCH_COLUMN_IN_TABLE), Stack trace (when copying this message, always include the lines below):


<Error> myapp.events_distributed.DirectoryMonitor: Code: 16. DB::Exception: Received from chi-chi-cluster-chi-cluster-1-1:9000. DB::Exception: No such column raw_timestamp in table myapp.events. Stack trace:

``` 

`raw_timestamp` used to a column in my table at one point but not anymore. I did remove `raw_timestamp` in the whole cluster and manually verified in every node that is removed however I still see the above logs continuously in the CH logs. I always used distributed table to do the writes so in my app it is always `INSERT INTO myapp.events_distributed` not `INSERT INTO myapp.events` (as in the logs)

There is no other app writing to my clickhouse cluster (I double and triple checked it) and again my app always uses distributed as opposed to the local table in the logs. I also verified `system.query_log` I see only the INSERT statements into `myapp.events_distributed` not `INSERT INTO myapp.events` 

so wondering why CH is throwing these logs? how to fix?

**Comment by kant777** [comment]
what is `myapp.events_distributed.DirectoryMonitor` ?

**Comment by kant777** [comment]
It looks like it is related to this https://github.com/ClickHouse/ClickHouse/pull/37966

**Comment by den-crane** [comment]
You need to delete a column from the distributed table, after that from MergeTree.

`INSERT INTO myapp.events_distributed` data goes to .bin files in the events_distributed folder, after that DirectoryMonitor forwards data using `INSERT INTO myapp.events`. 

You need to remove $$$$$.bin file from events_distributed folder, this file has more columns than `myapp.events` table.

Or you can add the column back to `myapp.events` wait while $$$$$.bin file been propagated, and remove the column again.

**Comment by kant777** [comment]
@den-crane Thanks! which one of the two strategies is safer so there is no data loss?

**Comment by den-crane** [comment]
I would add the column back to myapp.events wait while $$$$$.bin file been propagated, and remove the column again.

checked that `system.distribution_queue` does not have old inserts.

**Comment by kant777** [comment]
@den-crane That worked. However this also raises an important question. so I can't remove the columns when I want? I need to make sure the replication is done before I can remove the column? how do I make sure the replication is done?

**Comment by den-crane** [comment]
What do you mean by "replication is done" ? 
You have an issue with Distributed propagation, not with replication.

Here is the steps to remove a column:

1. remove column from distributed table.
2. wait 10 minutes
3. remove column from *mergeTree table.
