### ISSUE TITLE
Contribute Helm to chart

### ISSUE THREAD

**Issue by gajus** [ClickHouse/ClickHouse#3990]
What would really help with ClickHouse adoption is if there was a Helm chart for deploying an HA instance on a Kubernetes cluster.

https://github.com/helm/charts/

**Comment by gajus** [comment]
@diafour perhaps this is something that you could contribute given your work at

https://github.com/flant/loghouse/tree/master/charts/loghouse

?

**Comment by junneyang** [comment]
https://github.com/Altinity/clickhouse-operator

**Comment by diafour** [comment]
@gyrter FYI

There was already an attempt to add Clickhouse to helm/charts: https://github.com/helm/charts/pull/6371 with more options in values.yaml and without loghouse specific settings.
