### ISSUE TITLE
Salt in "interserver mode" is useless and does not protect from replay attack

### ISSUE THREAD

**Issue by tavplubix** [ClickHouse/ClickHouse#39903]
"Interserver mode" was introduced in #13156. The idea is great, however, the implementation is questionable. In particular, `salt` is generated on client and sent to server (see `receiveClusterNameAndSalt()`). Seems like it was supposed to protect from replay attack, but since salt is controlled by client, we cannot rely on it, which makes salt completely useless. Maybe we should re-implement it a proper way (server should ask client to calculate hash with specific salt generated by server), switch to  "interserver move v2" and remove current implementation. 

cc: @azat, @vitlibar

**Comment by alexey-milovidov** [comment]
+1 to reimplement it in a proper way.
We can even break the backwards compatibility, because this feature is mostly unknown.

**Comment by nvartolomei** [comment]
At least one person would appreciate if you don't break backwards compatibility.

**Comment by azat** [comment]
Yes, right now this salt is useless.

Initially, security was not the major side of the inter-server mode, for this SSL can be used, that will not allow any replay attacks.
But I agree, it worth to improve it, I will finish it (if no one already looking into this).

**Comment by alexey-milovidov** [comment]
@azat it makes sense to implement this feature properly because otherwise, it highlights the ignorance of the authors.
