### ISSUE TITLE
Support return the execution time of each step in execution plan

### ISSUE THREAD

**Issue by Lloyd-Pottiger** [ClickHouse/ClickHouse#39918]
> (you don't have to strictly follow this form)

**Use case**
> A clear and concise description of what is the intended usage scenario is.

Now we can use `EXPLAIN` to shows the execution plan of a statement, but we can not get the execution time of each step which may be much helpful for analyzing the execution.

**Describe the solution you'd like**
> A clear and concise description of what you want to happen.

Add support for this, we can use keyword like `EXPLAIN ANALYZE` to get the detail execution time of each step.

**Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.

none

**Additional context**
> Add any other context or screenshots about the feature request here.

none

**Comment by alexey-milovidov** [comment]
Implemented in #15261.

**Comment by Lloyd-Pottiger** [comment]
> Implemented in #15261.

sorry for do not notice this pr. Now we need to get the query-id first and query the system table to get the execution time of each step. Do we consider merging into one step and making it return more information like the number of rows processed and the number of rows returned?

**Comment by alexey-milovidov** [comment]
Yes, it makes sense to present it as a single EXPLAIN ANALYZE query.

**Comment by Lloyd-Pottiger** [comment]
> Yes, it makes sense to present it as a single EXPLAIN ANALYZE query.

cool, I will add a new issue to state that, and we could support returning the number of action rows and etc? Meanwhile, I would like to work on it.

**Comment by alexey-milovidov** [comment]
Yes, we can add the number of rows.

> Meanwhile, I would like to work on it.

Thank you! You can ask @KochetovNicolai if help will be needed.
