### ISSUE TITLE
Bug problem of union all in groupBitmapAnd

### ISSUE THREAD

**Issue by doyodo** [ClickHouse/ClickHouse#39916]
![9357377d5040dbca4e683a70a4558fd](https://user-images.githubusercontent.com/28794788/183009639-c1de88e1-f06f-451d-bb96-27283b90a4ab.jpg)
The above figure is my test SQL：
The first result of my test is empty, and the second and third results have data, but the data is not empty after groupbitmapand, and the final result is the intersection of the second and third results ,But I do the intersection of three results, and the result should be empty
.
After testing, I found that when the first result has no data, the result will not be returned, resulting in the intersection of the second result and the third result, which affects the actual result.

**Comment by alexey-milovidov** [comment]
No information was provided.
