### ISSUE TITLE
Discrepancy in the docs and actual behaviour

### ISSUE THREAD

**Issue by vicdashkov** [ClickHouse/ClickHouse#3992]
In the docks for collapsingMergeTree (https://clickhouse.yandex/docs/en/operations/table_engines/collapsingmergetree/) it goes

> We use two INSERT queries to create two different data parts. If we insert the data with one query ClickHouse creates one data part and will not perform any merge ever.

I played with it a bit and it looks like this engine still collapses no problem. Am I doing something wrong, or has the behaviour changed? 

Steps to reproduce:

```
CREATE TABLE collapsing_merge_tree.pokemon_age_0
(
    pokemon_id UInt64,
    age UInt8,
    health String,
    sign Int8
)
ENGINE = CollapsingMergeTree(sign)
ORDER BY pokemon_id;

INSERT INTO collapsing_merge_tree.pokemon_age_0 VALUES (1, 1, 'good', 1);
INSERT INTO collapsing_merge_tree.pokemon_age_0 VALUES (1, 1, 'good', -1);
INSERT INTO collapsing_merge_tree.pokemon_age_0 VALUES (1, 2, 'mhe', 1);

INSERT INTO collapsing_merge_tree.pokemon_age_0 VALUES (2, 10, 'mhe', 1), (2, 10, 'mhe', -1), (2, 11, 'almost there', 1);
INSERT INTO collapsing_merge_tree.pokemon_age_0 VALUES (2, 11, 'almost there', -1), (2, 12, 'almost there again', 1);

-- as I keep updating pokemon number 2 will get collapsed according to

SELECT *
FROM pokemon_age_0 

┌─pokemon_id─┬─age─┬─health──────────────┬─sign─┐
│          1 │   2 │ mhe                 │    1 │
│          2 │  13 │ almost there enough │    1 │
└────────────┴─────┴─────────────────────┴──────┘
```

**Comment by alexey-milovidov** [comment]
@vicdashkov ClickHouse will collapse data even if it is located in one data part if there is background merge process involved this data part among others. And background merge process is initiated if there is more than a single data part.
