### ISSUE TITLE
How to using a select SQL with case insensitive？

### ISSUE THREAD

**Issue by martin-chips** [ClickHouse/ClickHouse#39920]
hi, team,

I'm sorry to have your attention, but i just want to know how to make query condition case insensitive like MySQL query. just only can using lower function convert it  like this?

`select * from log_table_test where lower(file) = lower('File_name')`

**Comment by den-crane** [comment]
yes, `lower(file) = lower('File_name')` is the right way with ClickHouse.

**Comment by den-crane** [comment]
Also you may use `ilike`

```
select * from log_table_test where file ilike 'File_name'
```

**Comment by martin-chips** [comment]
Thank you for your prompt reply.
