### ISSUE TITLE
Get data in 7 days fixed intervals(not calendar intervals) 

### ISSUE THREAD

**Issue by mashahabi15** [ClickHouse/ClickHouse#39937]
Hello everyone.
How can I get data in 7 days fixed intervals buckets?
I tried date functions that are related to week(toStartOfWeek, ...) but these functions work almost with calendar intervals, and not fixed intervals. I've also tried `interval` operator, but data is not counted based on my own criteria. This is how I wrote my query:

```
select toStartOfWeek(datefield2) + interval 5 day,
       toStartOfWeek(datefield1) + interval 5 day,
       count(distinct user_id) as unique_users
from my_db.my_table 
where (datefield1 >= '2022-04-01 00:00:00' AND datefield1 <= '2022-05-30 23:59:59')
  and (datefield2 >= '2022-04-01 00:00:00' and datefield2 <= '2022-05-30 23:59:59')
group by toStartOfWeek(datefield2) , toStartOfWeek(datefield1)
order by toStartOfWeek(datefield2), toStartOfWeek(datefield1)
limit 100 offset 0;
```

without `interval`, buckets start from 2022-03-27 by default(which is Sunday):

|datefield2|            datefield1|                 unique_users|
|--------|--------|--------|
|2022-03-27 |   2022-03-27|              10000|
|2022-03-27|              2022-04-03              |50000|
|2022-03-27|              2022-04-10|              40000|

When I added `interval`, buckets start from 2022-04-01(the date I want) but the data count is the same. It means that it is still counting data based on calendar, and not based on my interval:
|datefield2|                 datefield1|                 unique_users|
|--------|--------|--------|
|2022-04-01|              2022-04-01|              10000|
|2022-04-01|              2022-04-08              |50000|
|2022-04-01|              2022-04-15|              40000|

Thank you for your consideration.

**Comment by den-crane** [comment]
What is datefield2 ? datefield1? Why do you have 2 datetime columns?

**Comment by den-crane** [comment]
Can you make an example? Create table / insert into and desired result ?

**Comment by den-crane** [comment]
the task is unclear.

**Comment by mashahabi15** [comment]
Hello @den-crane, apologies for the late response.
We save the time when user installs our application(datefield1 -> installed_at), and also we have several events in the application that if the user triggers them, we save his data.(time of the event: datefield2 -> creation_time).
This is a sample of my data: (events_table)

|creation_time|            installed_at|                 user_id|                 event_id|
|--------|--------|--------|--------|
|2022-08-02 07:16:57 |   2022-08-01 19:11:33|              00gok0goqmhofy1cxqal66krwh719olx|              512987|
|2022-08-05 20:15:27|              2022-08-05 16:34:52              |00id672inpoqlkk2cb3yxm8b1rrzpptv|              516487|
|2022-08-05 17:56:51|              2022-08-05 06:37:39|              01vcjnvbg74rj1yotlbpdqxrebfzl6fk|              516487|
