### ISSUE TITLE
Support Object('json') sub-columns in Kafka table engine

### ISSUE THREAD

**Issue by shahargv** [ClickHouse/ClickHouse#39932]
**Use case**

It's a common use-case to read from a Kafka topic to a *MergeTree table using a materialized view.

The new JSON data-type can't be used in a Kafka table engine as a sub-column. For example, if I have this JSON:
```
{
    "A": "b",
    "C": 1,
    "AdditionalData": {
        "Something1": "something",
        "Something2": true
    }
}
```
I'd like to have a table defined like this:
```
CREATE TABLE default.kafka_test
(
    A String,
    C String,
    AdditionalData JSON
)
ENGINE = Kafka('localhost:9092', 'test1', 'test1', 'JSONEachRow')
```
And to use it later to insert data to a MergeTree table (with the same schema) using a materialized view.

**Describe the solution you'd like**
Support JSON sub-columns in a Kafka table, and allow to use it to push data into a MergeTree table with a JSON sub-column defined as well.

Thanks.

**Comment by ramazanpolat** [comment]
Maybe you can get the data from Kafa using `JSONAsString` format.

```sql
CREATE TABLE default.kafka_test
(
    json_string String
)
ENGINE = Kafka('localhost:9092', 'test1', 'test1', 'JSONAsString')
```

Then in MV, you can convert it to JSON like this:
```sql
CREATE MATERIALIZED VIEW mv1 TO target
AS
  WITH json_string::JSON as my_json
  SELECT 
    my_json.A as A, 
    my_json.B as B, 
    my_json.AdditionalData as AdditionalData 
 FROM default.kafka_test
```

Assuming you have this target table:
```sql
CREATE TABLE target
(
    A String,
    C String,
    AdditionalData JSON
)
ENGINE = MergeTree ...
```

**Comment by shahargv** [comment]
Hey Ramazan, 
Thanks for your reply.
I've tried this methods, it cause syntax error. It looks like simple casting doesn't cause the schema-inference to work. I tried both your original approach, and some other modification (using cte). Both failed with syntax errors. 

Here is the full snippet:
```
CREATE TABLE default.kafka_test
(
    json_string String
)
ENGINE = Kafka('localhost:9092', 'test1', 'test1', 'JSONAsString')

CREATE TABLE default.target
(
	ColA String,
	ColB String,
	AdditionalStrings JSON
)
ENGINE=MergeTree()
ORDER BY ColA

--Doesn't work: Missing columns: 'my_json.AdditionalStrings' 'my_json.b' 'my_json.a' while processing query
CREATE MATERIALIZED VIEW mv1 TO target
AS
  WITH json_string::JSON as my_json
  SELECT 
    my_json.a as ColA, 
    my_json.b as ColB, 
    my_json.AdditionalStrings as AdditionalStrings 
 FROM default.kafka_test

--Doesn't work: Missing columns: 'my_json.AdditionalStrings' 'my_json.b' 'my_json.a' while processing query
CREATE MATERIALIZED VIEW mv1 TO target
AS
  WITH cte as (SELECT json_string::JSON as my_json FROM default.kafka_test)
  SELECT 
    my_json.a as ColA, 
    my_json.b as ColB, 
    my_json.AdditionalStrings as AdditionalStrings 
 FROM cte
```

The samples I've seen that combine both regular columns and JSON column are all without Kafka, and while inserting data directly with INSERT statements, where you can control the FORMAT. I hope I miss something, but it looks like it's a missing feature.

Thanks.

**Comment by Algunenano** [comment]
The feature will be removed, so no new features will be done
