### ISSUE TITLE
Flag in config to disable username and password in URL parameter for HTTP endpoint

### ISSUE THREAD

**Issue by santrancisco** [ClickHouse/ClickHouse#39934]
**Use case**

Having username and password in URL parameter means a Server Side Request Forgery (SSRF) issue in a web application could easily turn into full access to Clickhouse DB if weak password or default password is used and the HTTP port is not properly secured.  

![image](https://user-images.githubusercontent.com/3240146/183226545-52762818-abc4-4901-b74c-56ec09c83622.png)

**Describe the solution you'd like**

Now that [this pull request](https://github.com/ClickHouse/ClickHouse/pull/39910) to let play.html to authenticate via basic auth header is in, I think we should be able to disable using username and password in url parameter by default to prevent this attack surface. Users who rely on this can re-enabled it so this fix should go into changelog to make users aware of this change. 

**Additional context**

Note that in most application, SSRF attack is usually carried out via GET request with no way to modify headers and thus the V1 AWS metadata endpoint was such a big issue due to not having any protection in place while GCP metadata when it first came out already force user to have a header attached to the request to metadata endpoint and eliminate most of this risk.

**Comment by santrancisco** [comment]
Actually.. just thought about it today and even disabling this feature, it is still possible, in many cases, to perform SSRF attack against clickhouse http endpoint if the credentials is weak or compromised  by using URL such as: http://username:password@clickhouse.server.address . Most http client library will automatically translate this to request with basic authentication. To enhance clickhouse security and help prevent these type of attack, CH either should force query request being made with POST request instead of GET (should stop majority of SSRF attack) or force a special header attached to them (similar to how GCP protect their metadata) or users just need to do better at network isolation  & protect their Clickhouse HTTP endpoint.  I will think about this abit more.

**Comment by alexey-milovidov** [comment]
@santrancisco ClickHouse only allows readonly requests with GET.
