### ISSUE TITLE
Downgrade support

### ISSUE THREAD

**Issue by zamazan4ik** [ClickHouse/ClickHouse#39952]
Hi.

After reading the documentation it is not clear for me, how downgrade process should be performed over the solution. Could you please describe somewhere in the documentation:

- How to downgrade Clickhouse to the older version (hopefully with no downtime) and for which versions downgrade is supported

Thanks in advance!

**Comment by den-crane** [comment]
To downgrade you need to install the old packages and restart Clickhouse. (the same procedure as upgrade)

Downgrade is mostly works if the distance between the version is less than year and if you did not use new features which are absent in the old version. In some cases you need to remove tables in system catalog. In some cases downgrade is impossible without removing Zookeeper metadata and recreating it back. So basically each downgrade is unique and should be tested in a stage env. 

If you have specific issues with the your downgrade you can ask here and most probably we can suggest the specific solution.

**Comment by zamazan4ik** [comment]
@den-crane could you please put this imformation somewhere into the documentation? Now it is not clear that downgrade is possible. And is it possible to perform with no downtime or not.
