### ISSUE TITLE
Loss data after renaming table

### ISSUE THREAD

**Issue by fpinta** [ClickHouse/ClickHouse#39953]
I have two clickhouse nodes in a double shards and mutual replications. After node 2 crashes, i copy the distributed tables to a local copy on node 1.
Then I rebuild the cluster and I created new distributed tables to re-copy the local table of node 1 to the corresponding distributed ones.
The system is live and. Data is continuously ingested into the tables.
So I made this:
1. Rename table tablename to tablename_local, tablename_cluster to tablename
So the systems continue to insert data to the table (the clustered after the rename)
2. Insert into tablename select * from tablename_local
In order to copy the local data in the distributed table
I made these steps for a table and result was ok.
I made the same steps to another table but I notice the insert result 0 rows. I checked the commands I made because I think to a my mistake but commands was ok. Both the local and clustered table loss data completely. I very strange behaviour is that Also others tables not involved in the commands losses data!
I checked the filesystem if the files were presents in other directories (for example in the detached dir) but no. I check also the filesystem usage and after that the usage decreases, so data was really losses.

**Comment by den-crane** [comment]
You need to clarify your question with DDL queries and clickhouse configs. Now it's impossible to understand.

**Comment by den-crane** [comment]
Check this https://kb.altinity.com/engines/

**Comment by fpinta** [comment]
As I said, the are two nodes in cluster and two shards and 2 replicas:

```
<nemodata_cluster>
    <shard>
      <replica>
        <default_database>shard</default_database>
        <host>10.155.199.132</host>
        <port>9000</port>
      </replica>
      <replica>
        <default_database>replica</default_database>
        <host>10.155.199.134</host>
        <port>9000</port>
      </replica>
    </shard>

    <shard>
      <replica>
        <default_database>shard</default_database>
        <host>10.155.199.134</host>
        <port>9000</port>
      </replica>
      <replica>
        <default_database>replica</default_database>
        <host>10.155.199.132</host>
        <port>9000</port>
      </replica>
    </shard>
</nemodata_cluster>
```
The tables are defined as distributed tableds and shards and replica for the distributed tables are defined inside the shards and replica database:
```
==========
DATABASE 1
==========

CREATE TABLE shard.datad
(
    `id_inventario` UInt64,
    `timestamp` DateTime64(3),
    `in_val` Float64,
    `out_val` Float64,
    `writetime` DateTime,
    `deleted` UInt8
)
ENGINE = ReplicatedMergeTree('/clickhouse/tbl/shard1/datad', 'datad_1')
PARTITION BY toMonday(timestamp)
PRIMARY KEY (id_inventario, timestamp)
ORDER BY (id_inventario, timestamp)
SETTINGS index_granularity = 8192


CREATE TABLE replica.datad
(
    `id_inventario` UInt64,
    `timestamp` DateTime64(3),
    `in_val` Float64,
    `out_val` Float64,
    `writetime` DateTime,
    `deleted` UInt8
)
ENGINE = ReplicatedMergeTree('/clickhouse/tbl/shard2/datad', 'datad_2')
PARTITION BY toMonday(timestamp)
PRIMARY KEY (id_inventario, timestamp)
ORDER BY (id_inventario, timestamp)
SETTINGS index_granularity = 8192


CREATE TABLE newdatalog.datad_clu
(
    `id_inventario` UInt64,
    `timestamp` DateTime64(3),
    `in_val` Float64,
    `out_val` Float64,
    `writetime` DateTime,
    `deleted` UInt8
)
ENGINE = Distributed('nemodata_cluster', '', datad, id_inventario);



==========
DATABASE 2
==========

CREATE TABLE shard.datad
(
    `id_inventario` UInt64,
    `timestamp` DateTime64(3),
    `in_val` Float64,
    `out_val` Float64,
    `writetime` DateTime,
    `deleted` UInt8
)
ENGINE = ReplicatedMergeTree('/clickhouse/tbl/shard2/datad', 'datad_1')
PARTITION BY toMonday(timestamp)
PRIMARY KEY (id_inventario, timestamp)
ORDER BY (id_inventario, timestamp)
SETTINGS index_granularity = 8192


CREATE TABLE replica.datad
(
    `id_inventario` UInt64,
    `timestamp` DateTime64(3),
    `in_val` Float64,
    `out_val` Float64,
    `writetime` DateTime,
    `deleted` UInt8
)
ENGINE = ReplicatedMergeTree('/clickhouse/tbl/shard1/datad', 'datad_2')
PARTITION BY toMonday(timestamp)
PRIMARY KEY (id_inventario, timestamp)
ORDER BY (id_inventario, timestamp)
SETTINGS index_granularity = 8192


CREATE TABLE newdatalog.datad_clu
(
    `id_inventario` UInt64,
    `timestamp` DateTime64(3),
    `in_val` Float64,
    `out_val` Float64,
    `writetime` DateTime,
    `deleted` UInt8
)
ENGINE = Distributed('nemodata_cluster', '', datad, id_inventario);

```
There are other tables defined in the same way. 

In the node1 I had the tables defined as MergeTree and I want to transfer data from the single node MergeTree to the distributed table. So I made:
rename table datad to datad_tmp, datad_clu to datad
insert into datad select * from datad_tmp
The first time, operation was ok. The second time some tables lost data (not only the table defined in the rename)!

Unfortunately this behaviour is not sistematic, I made some test in order to replicate the problem but results were ok.
I think there is a side effect on particular situation.

**Comment by alexey-milovidov** [comment]
Does not reproduce.
