### ISSUE TITLE
when i use Database Engines postgresql ，it comes an error（version 20.12.4.5 (official build)）

### ISSUE THREAD

**Issue by dopenser** [ClickHouse/ClickHouse#39951]
CREATE DATABASE mysql_db ENGINE=PostgreSQL ('xxxx:5432', 'xxx', 'xx', 'xx')
clickhouse提示错误如下，请问是版本不支持，还是说要在哪开启什么设置

Code: 36, e.displayText() = DB::Exception: Database engine PostgreSQL cannot have arguments (version 20.12.4.5 (official build))

**Comment by kssenii** [comment]
This engine was implemented starting from version 21.1.
