### ISSUE TITLE
build error on Ubuntu20.04

### ISSUE THREAD

**Issue by chloro-pn** [ClickHouse/ClickHouse#39950]
> Make sure that `git diff` result is empty and you've just pulled fresh master. Try cleaning up cmake cache. Just in case, official build instructions are published here: https://clickhouse.com/docs/en/development/build/

**Operating system**
Ubuntu20.04 (Virtualbox)

> OS kind or distribution, specific version/release, non-standard kernel if any. If you are trying to build inside virtual machine, please mention it too.

**Cmake version**
3.16.3

**Ninja version**
1.10.0

**Compiler name and version**
gcc-11\g++11

**Full cmake and/or ninja output**
ClickHouse/contrib/llvm/llvm/cmake/config.guess: 71: Syntax error: word unexpected (expecting "in")

**solve**
It seems that llvm fails to compile on Ubuntu 20.04 system, but I wonder if I can record this problem here so that other people can quickly solve the same problem.

There are some dos line endings in the config.guess file, which need to be converted to UNIX line endings:
```
sudo apt-get install dos2unix
dos2unix path/to/config.guess
```

**Comment by pkit** [comment]
There's no such problem in the current master. I would suspect your git client.
```
$ file contrib/llvm/llvm/cmake/config.guess
contrib/llvm/llvm/cmake/config.guess: POSIX shell script, ASCII text executable
```

**Comment by chloro-pn** [comment]
my git version is 2.25.1.

 I download the source code on windows system, share the source code to the virtual machine(through the "shared folder" of VritualBox.) and compile it. Perhaps this is the cause of the problem.

I mistakenly thought that cmake would handle format problems between systems. Anyway, no problem is the best.

**Comment by pkit** [comment]
Yup, I think git on windows will try to add CRLF to some files.
