### ISSUE TITLE
02293_part_log_has_merge_reason is flaky

### ISSUE THREAD

**Issue by devcrafter** [ClickHouse/ClickHouse#39958]
**Describe the bug**
https://s3.amazonaws.com/clickhouse-test-reports/39955/254d14b1d360eb873ffb055bba28aeef463e54d8/stateless_tests__release_.html

**Comment by tavplubix** [comment]
#40047 did not help, it's still flaky:
https://s3.amazonaws.com/clickhouse-test-reports/0/35ee71a908ca3459ec16717518553a3ce3a8b331/stateless_tests__aarch64_.html

**Comment by tavplubix** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/30498/747d74121c794c9c02dc0fbb6ff7782413199bf9/stateless_tests__release_.html

**Comment by tavplubix** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/0/68e98e43ed58d08deedfa7776b45b9b441db33a0/stateless_tests__release_.html

**Comment by CheSema** [comment]
I think I fixed it, finally.
https://github.com/ClickHouse/ClickHouse/pull/40455
