### ISSUE TITLE
Is it possible that the materialized view can be triggered by the ReplicatedMergeTree's copy data?

### ISSUE THREAD

**Issue by smartiscool** [ClickHouse/ClickHouse#39971]
There is one table TABLE_A, ReplicatedMergeTree on both node1 and node2.

On node2, I created a TABLE_B, materialized view and a target table TABLE_C, MergeTree.

When I insert data from node1's TABLE_A, I can get the copy data on node2's TABLE_A, but I found that the materialized view TABLE_B (on node2) will not write the result data to TABLE_C, unless I insert data from node2's TABLE_A.

I would like to ask if there is any possible that when I insert data from node1's TABLE_A, it can trigger node2's materialized view TABLE_B and write data to TABLE_C?

```
[node1]  INSERT INTO ---> TABLE_A (ReplicatedMergeTree)
                             |
[node2]                   TABLE_A (ReplicatedMergeTree) ---> TABLE_B (MATERIALIZED VIEW) ---> TABLE_C (MergeTree)
```

**Comment by genzgd** [comment]
No, this is not possible.  A materialized view acts as an insert trigger on the source table, and is not connected to replication in any way.

The standard way of handling this situation is to make TABLE_C a ReplicatedMergeTree as well.
