### ISSUE TITLE
Tests `test_storage_nats` are broken 

### ISSUE THREAD

**Issue by tavplubix** [ClickHouse/ClickHouse#39983]
Tests stopped working for no obvious reason, probably because some docker images/python libraries were updated

Example:
https://s3.amazonaws.com/clickhouse-test-reports/0/cb7f072fe88a66387a0f990920db626c1774741f/integration_tests__thread__[2/4].html

cc: @tchepavel, @kssenii

**Comment by tavplubix** [comment]
May be related to https://github.com/ClickHouse/ClickHouse/pull/39527, but first failures in master happened before it was merged

**Comment by kssenii** [comment]
But in later commits it is fine again, may be the same docker issue that happens from time to time?

**Comment by alexey-milovidov** [comment]
@Felixoid we need to lock all the images in Docker to avoid supply channel attacks.
