### ISSUE TITLE
Parquet files are generated with "BLOB" datatype in all columns

### ISSUE THREAD

**Issue by andrea-s** [ClickHouse/ClickHouse#40000]
How to reproduce:

`select database, name from system.tables limit 25 into outfile '/tmp/dbs.parquet' format Parquet;`

The resulting parquet file has "BLOB" as column type for all columns. This makes it harder to work with the file in other software (we were trying DuckDB but we can confirm that it's the same for other software packages).

Here's the output of parquet-tools:

```statwolf@DESKTOP-4U7NJTU:/tmp$ parquet-tools inspect dbs.parquet

############ file meta data ############
created_by: parquet-cpp version 1.5.1-SNAPSHOT
num_columns: 2
num_rows: 25
num_row_groups: 1
format_version: 1.0
serialized_size: 280


############ Columns ############
database
name

############ Column(database) ############
name: database
path: database
max_definition_level: 0
max_repetition_level: 0
physical_type: BYTE_ARRAY
logical_type: None
converted_type (legacy): NONE
compression: SNAPPY (space_saved: 2%)

############ Column(name) ############
name: name
path: name
max_definition_level: 0
max_repetition_level: 0
physical_type: BYTE_ARRAY
logical_type: None
converted_type (legacy): NONE
compression: SNAPPY (space_saved: 42%)```

**Comment by andrea-s** [comment]
P.S. reading the same file from ClickHouse results in the two columns being parsed as `Nullable(String)` rather than `String`

**Comment by andrea-s** [comment]
Ok, I can see now that this is related to the `output_format_parquet_string_as_string` setting. I don't understand why that would be false by default, though.

**Comment by alexey-milovidov** [comment]
Strings in ClickHouse can contain any sequence of bytes, including zero bytes and non-UTF-8 sequences of bytes.
That's why the only option for one-to-one mapping is using BLOBs.
