### ISSUE TITLE
The netmask are different and the cluster cannot connect

### ISSUE THREAD

**Issue by guosk123** [ClickHouse/ClickHouse#40016]
### env
---
1、host：10.0.0.110（netmask：255.0.0.0）、10.0.1.110（netmask：255.255.0.0）
2、10.0.0.110 clickhouse config.xml：
```
<remote_servers incl="clickhouse_remote_servers">
      <clickhouse_servers>  
            <shard node_ip="10.0.1.110">
                <replica>
                    <host>10.0.1.110</host>
                    <port>9440</port>
                    <user>xxx</user>
                    <password>xxx</password>
                    <secure>1</secure>
                </replica>
            </shard>
        </clickhouse_servers>
 </remote_servers>
```
### options
---
when i query 10.0.0.110 table, result：
```
Code: 279. DB::NetException: All connection tries failed. Log:

Code: 209. DB::NetException: Timeout: connect timed out: 10.0.0.110:9440 (10.0.0.110:9440, receive timeout 0 ms, send timeout 0 ms). (SOCKET_TIMEOUT) (version 22.4.1.725)
```

_netmask is different, but i can ping each other_

### question
---
The netmask is different and cannot be connected. Is it designed like this, or the configuration needs to be modified?

**Comment by den-crane** [comment]
check with curl from CH server `curl http://10.0.1.110:9440`

**Comment by guosk123** [comment]
@den-crane 
[root@localhost ~]# curl http://10.0.1.110:9440
curl: (28) Failed to connect to 10.0.1.110 port 9440: connection timed out

**Comment by den-crane** [comment]
>[root@localhost ~]# curl http://10.0.1.110:9440
>curl: (28) Failed to connect to 10.0.1.110 port 9440: connection timed out

firewall/network issue, it should work. Problem is not related to ClickHouse.

BTW, try https `curl https://10.0.1.110:9440`
