### ISSUE TITLE
Flat materialized view hierarchy – a viable alternative to a cascade?

### ISSUE THREAD

**Issue by larry-cdn77** [ClickHouse/ClickHouse#40023]
I have one MergeTree table receiving a stream of a few million rows a second that represent timestamped events. Multiple AggregatingMergeTree tables produce statistics on this incoming stream of events and as described in Denny's _Everything You Should Know About Materialized Views_, they are arranged in a cascade with respect to time resolution of each aggregation.

![2022-08-09 12 29 49](https://user-images.githubusercontent.com/72978202/183627024-16a6acc6-8c05-4cf9-a3af-00c1525bb89a.png)

Arrows in my diagram represent FROM and TO clauses of my MV create statements. What actually happens when a new block arrives is, I believe, that MV1 transforms it for inserting into its table and output goes to MV2 where a second transformation makes a block for MV2's table. This is how I understood cascading materialised views.

It should be more efficient to cascade than not to cascade. Cascading means less GROUP BY to do. But by how much? Because I have been finding the cascade somewhat impractical (mainly due to repeatedly making mistakes while back-filling data), I experimented and converted my views to a flat hierarchy. All views are now sourcing from the input MergeTree table.

![2022-08-09 12 35 54](https://user-images.githubusercontent.com/72978202/183628133-bbbc449a-e3b8-4d72-ab0c-dd2ee2f6442d.png)

There has been no obvious increase in CPU usage above this cluster's normal 20-40%. I noticed some increase in ZooKeeper activity, as if a greater number of parts were being made. I am interested in any quick thoughts about why there would little to no difference in resource usage. I imagined that, say for MV2 (orange circle in diagram) in my example:

- 1 million rows to 1 thousand rows (MV2 from raw table, the flat scenario) is harder than
- 10 thousand rows to 1 thousand rows (MV2 from result of MV1., the cascade scenario)

![2022-08-09 13 18 54](https://user-images.githubusercontent.com/72978202/183635460-06ac95a4-f0e1-424c-ac62-33c33a69ae5c.png)

My hunch is that the GROUP BY is just monstrously fast (entirely in RAM, I suppose) and not allowing any major difference to show. Appreciate any comments.

**Comment by den-crane** [comment]
Mostly cascades have sense if you have heavy CPU calculations in the first MatView, for example multiple JSONExtract.

**Comment by den-crane** [comment]
Schema without cascades allows to process all mat views in parallel (`parallel_view_processing`) and can be faster

**Comment by larry-cdn77** [comment]
Thanks, this helped me!
