### ISSUE TITLE
Version 22.3.10: SELECT from tables on encrypted disk returns UNKNOWN_CODEC exception

### ISSUE THREAD

**Issue by MyroTk** [ClickHouse/ClickHouse#40029]
**Describe what's wrong**
I have a table that uses an encrypted disk. When I try to SELECT from the table, ClickHouse returns the following exception `Code: 432. DB::Exception: Received from localhost:9000. DB::Exception: Unknown codec family code: 181: (while reading column a): While executing MergeTreeThread. (UNKNOWN_CODEC)`

**How to reproduce**

* Which ClickHouse server version to use
22.3.10.22-alpine

* Non-default settings, if any
```
    <storage_configuration>
      <disks>
        <local>
          <path>/disk_local/</path>
        </local>
        <encrypted_local>
          <type>encrypted</type>
          <disk>local</disk>
          <path>encrypted/</path>
          <key>firstfirstfirstf</key>
        </encrypted_local>
      </disks>
     <policies>
       <local_encrypted>
         <volumes>
           <encrypted_disk>
             <disk>encrypted_local</disk>
           </encrypted_disk>
         </volumes>
       </local_encrypted>
     </policies>
   </storage_configuration>
```
* `CREATE TABLE` statements for all tables involved
```
CREATE TABLE table0
(
       Date DateTime,
       a Int TTL Date + INTERVAL 1 HOUR,
       b Int TTL Date + INTERVAL 2 HOUR
)
ENGINE = MergeTree()
ORDER BY Date
SETTINGS storage_policy = 'local_encrypted'
```

* Queries to run that lead to unexpected result
```
INSERT INTO table0 VALUES (toDateTime(1659978022.1352155), 3, 3)
SELECT Date as Seconds, a, b FROM table0 FORMAT JSONEachRow
Code: 432. DB::Exception: Received from localhost:9000. DB::Exception: Unknown codec family code: 181: (while reading column a): While executing MergeTreeThread. (UNKNOWN_CODEC)
```

**Comment by MyroTk** [comment]
Message from the clickhouse-server.log
```
2022.08.09 16:11:30.652409 [ 788 ] {8ba0201e-4f09-4a53-871f-10ac3a1121e4} <Error> executeQuery: Code: 432. DB::Exception: Unknown codec family code: 181: (while reading column a): While executing MergeTreeThread. (UNKNOWN_CODEC) (version 22.3.10.22 (official build)) (from 127.0.0.1:44074) (in query: SELECT Date as Seconds, a, b FROM table0 FORMAT JSONEachRow ), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xb37453a in /usr/bin/clickhouse
1. DB::CompressionCodecFactory::get(unsigned char) const @ 0x15036812 in /usr/bin/clickhouse
2. DB::CompressedReadBufferBase::readCompressedData(unsigned long&, unsigned long&, bool) @ 0x15027a75 in /usr/bin/clickhouse
3. DB::CompressedReadBufferFromFile::readBig(char*, unsigned long) @ 0x1502a286 in /usr/bin/clickhouse
4. DB::SerializationNumber<int>::deserializeBinaryBulk(DB::IColumn&, DB::ReadBuffer&, unsigned long, double) const @ 0xb1c6673 in /usr/bin/clickhouse
5. DB::ISerialization::deserializeBinaryBulkWithMultipleStreams(COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, DB::ISerialization::DeserializeBinaryBulkSettings&, std::__1::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, COW<DB::IColumn>::immutable_ptr<DB::IColumn> > > >*) const @ 0x15210d55 in /usr/bin/clickhouse
6. DB::MergeTreeReaderCompact::readData(DB::NameAndTypePair const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, unsigned long, unsigned long, unsigned long, bool) @ 0x16416bb2 in /usr/bin/clickhouse
7. DB::MergeTreeReaderCompact::readRows(unsigned long, unsigned long, bool, unsigned long, std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >&) @ 0x1641634c in /usr/bin/clickhouse
8. DB::MergeTreeRangeReader::DelayedStream::finalize(std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >&) @ 0x16bf390e in /usr/bin/clickhouse
9. DB::MergeTreeRangeReader::startReadingChain(unsigned long, std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange> >&) @ 0x16bf8460 in /usr/bin/clickhouse
10. DB::MergeTreeRangeReader::read(unsigned long, std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange> >&) @ 0x16bf6c55 in /usr/bin/clickhouse
11. DB::MergeTreeBaseSelectProcessor::readFromPartImpl() @ 0x16bec468 in /usr/bin/clickhouse
12. DB::MergeTreeBaseSelectProcessor::readFromPart() @ 0x16bed56d in /usr/bin/clickhouse
13. DB::MergeTreeBaseSelectProcessor::generate() @ 0x16bebce0 in /usr/bin/clickhouse
14. DB::ISource::tryGenerate() @ 0x16905175 in /usr/bin/clickhouse
15. DB::ISource::work() @ 0x16904d3a in /usr/bin/clickhouse
16. DB::SourceWithProgress::work() @ 0x16b5c6c2 in /usr/bin/clickhouse
17. DB::ExecutionThreadContext::executeTask() @ 0x169254c3 in /usr/bin/clickhouse
18. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x16918f1e in /usr/bin/clickhouse
19. ? @ 0x1691a884 in /usr/bin/clickhouse
20. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xb419317 in /usr/bin/clickhouse
21. ? @ 0xb41ce9d in /usr/bin/clickhouse
22. ? @ 0x7f084b8eb609 in ?
23. clone @ 0x7f084b812293 in ?

**Comment by MyroTk** [comment]
This works on 22.3.8.39-alpine

**Comment by vzakaznikov** [comment]
This issue was introduced by https://github.com/ClickHouse/ClickHouse/pull/39687.

**Comment by vzakaznikov** [comment]
Hi @vitlibar, would you be able to take a look?

**Comment by alexey-milovidov** [comment]
@MyroTk check on the latest ClickHouse version.

**Comment by MyroTk** [comment]
Works as intended on 22.7.2.15

**Comment by alexey-milovidov** [comment]
https://github.com/ClickHouse/ClickHouse/pull/40052

**Comment by RO-29** [comment]
Hi, I am facing the exact issue in `22.8.5.29-lts`

Should the "Revert "Backport #39687" be applied for it too?

Table definition

```
CREATE TABLE events.email_transactional_aggregated_stats_local_replicated
(
    `organization_id` Int64 CODEC(ZSTD(1)),
    `event_date` DateTime('UTC') CODEC(DoubleDelta, ZSTD(1)),
    `event_type` String CODEC(ZSTD(1)),
    `event_month` Date CODEC(DoubleDelta, ZSTD(1)),
    `count` AggregateFunction(count) CODEC(ZSTD(1)),
    `unique_count` AggregateFunction(uniqCombined64, String) CODEC(ZSTD(1)),
    `tags` Array(String) CODEC(ZSTD(1))
)
ENGINE = ReplicatedAggregatingMergeTree('/clickhouse/tables/{cluster}/{shard}/events.email_transactional_aggregated_stats_local_replicated_v2', '{replica}')
PARTITION BY toYYYYMM(event_month)
ORDER BY (organization_id, event_date, event_type, tags, event_month)
SETTINGS index_granularity = 8192
```


`DB::Exception: Unknown codec family code: 10: (while reading column event_date): (while reading from part /data/clickhouse/data/store/436/436463b9-3aca-4996-8d78-4472ea4c0718/202209_0_0_0/ from mark 10 with max_rows_to_read = 8192): While executing MergeTreeThread. Stack trace: 0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa3c597a in /usr/bin/clickhouse 1. DB::CompressionCodecFactory::get(unsigned char) const @ 0x13f92913 in /usr/bin/clickhouse 2. ? @ 0x13f83f95 in /usr/bin/clickhouse 3. DB::CompressedReadBufferBase::readCompressedDataBlockForAsynchronous(unsigned long&, unsigned long&) @ 0x13f85599 in /usr/bin/clickhouse 4. DB::CompressedReadBufferFromFile::readBig(char*, unsigned long) @ 0x13f868b7 in /usr/bin/clickhouse 5. DB::SerializationNumber<unsigned int>::deserializeBinaryBulk(DB::IColumn&, DB::ReadBuffer&, unsigned long, double) const @ 0xa1e1772 in /usr/bin/clickhouse 6. DB::ISerialization::deserializeBinaryBulkWithMultipleStreams(COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, DB::ISerialization::DeserializeBinaryBulkSettings&, std::__1::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, COW<DB::IColumn>::immutable_ptr<DB::IColumn> > > >*) const @ 0x14133016 in /usr/bin/clickhouse 7. DB::MergeTreeReaderWide::readData(DB::NameAndTypePair const&, std::__1::shared_ptr<DB::ISerialization const> const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, bool, unsigned long, unsigned long, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, COW<DB::IColumn>::immutable_ptr<DB::IColumn> > > >&, bool) @ 0x158c6bfa in /usr/bin/clickhouse 8. DB::MergeTreeReaderWide::readRows(unsigned long, unsigned long, bool, unsigned long, std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >&) @ 0x158c5e70 in /usr/bin/clickhouse 9. DB::MergeTreeRangeReader::DelayedStream::finalize(std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >&) @ 0x15f7620f in /usr/bin/clickhouse 10. DB::MergeTreeRangeReader::continueReadingChain(DB::MergeTreeRangeReader::ReadResult const&, unsigned long&) @ 0x15f7b5e9 in /usr/bin/clickhouse 11. DB::MergeTreeRangeReader::read(unsigned long, std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange> >&) @ 0x15f79a69 in /usr/bin/clickhouse 12. DB::MergeTreeBaseSelectProcessor::readFromPartImpl() @ 0x15f6edab in /usr/bin/clickhouse 13. DB::MergeTreeBaseSelectProcessor::readFromPart() @ 0x15f6fd8d in /usr/bin/clickhouse 14. DB::MergeTreeBaseSelectProcessor::generate() @ 0x15f6b591 in /usr/bin/clickhouse 15. DB::ISource::tryGenerate() @ 0x15bf1575 in /usr/bin/clickhouse 16. DB::ISource::work() @ 0x15bf10c6 in /usr/bin/clickhouse 17. DB::ExecutionThreadContext::executeTask() @ 0x15c0db4a in /usr/bin/clickhouse 18. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x15c020bb in /usr/bin/clickhouse 19. ? @ 0x15c04959 in /usr/bin/clickhouse 20. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa487348 in /usr/bin/clickhouse 21. ? @ 0xa48a55d in /usr/bin/clickhouse 22. start_thread @ 0x74a4 in /lib/x86_64-linux-gnu/libpthread-2.24.so 23. __clone @ 0xe8d0f in /lib/x86_64-linux-gnu/libc-2.24`
