### ISSUE TITLE
Improve the setting `use_structure_from_insertion_table_in_table_functions`

### ISSUE THREAD

**Issue by Avogar** [ClickHouse/ClickHouse#40028]
This setting is disabled by default, but it's really helpful in case of queries like `insert into <table> select * from <table_function>`. We should try to enable/disable this setting automatically depending on select query.

**Comment by alexey-milovidov** [comment]
Maybe: if there are no expressions in SELECT clause, only column names (possibly as asterisk).
It can be named `use_structure_from_insertion_table_in_table_functions = 'auto'`.
