### ISSUE TITLE
Anchor link is broken

### ISSUE THREAD

**Issue by mgrobaker** [ClickHouse/ClickHouse#40044]
The anchor link on [this page](https://clickhouse.com/docs/en/integrations/s3/s3-table-functions/#exporting-data) gives me a page not found. That page suggested I open a github issue, so I came here.

It seems the link is correct. However the anchor only works if you are already on the page in question. You cannot go to the anchor on another page.

![image](https://user-images.githubusercontent.com/5614366/183755196-6eb150ff-8a9f-48a3-9115-32643dd95d5e.png)
![image](https://user-images.githubusercontent.com/5614366/183755340-53f349da-a33a-41cd-a151-09019a164980.png)

**Additional context**
I am not a front end person, but did a quick google search. It seems this kind of issue could occur due to the pages being stored in different directories.

I am not sure if this is an isolated issue, or affects other anchor links throughout the documentation

**Comment by rfraposa** [comment]
Thanks @mgrobaker - I can not reproduce, and the link is correct, so I am not sure what happened. I will close it for now, but if this is still an issue for you then please reopen.

**Comment by mgrobaker** [comment]
Hm. Yes I just tried again in two browsers and get the same error

**Comment by rfraposa** [comment]
OK - I will research and figure this out. Thanks

**Comment by DanRoscigno** [comment]
doc has many full urls and a few ./ with no `.md` externsion.  fixed in PR 395
