### ISSUE TITLE
why do i still get Transactions are not support? after upgrade ClickHouse from 22.3 to 22.7+ 

### ISSUE THREAD

**Issue by FishLai** [ClickHouse/ClickHouse#40054]
Hi, I have installed ClickHouse 22.3 via HomeBrew.
And recently, I upgrade it to 22.7 for transaction feature
No matter I use clickhouse-jdbc-0.3.2-patch11 `jdbc:ch://localhost:8123/default?transactionSupport` 
or use clickhouse-client `begin transaction ..`

I still get exception that "Transactions are not support: while starting a transaction with 'implicit_transaction'"

is there anything i miss?

**Comment by lelezhan** [comment]
I also met this problem too..
It seems that some function using the default settings, transaction support might be in test staging

**Comment by lelezhan** [comment]
> Hi, I have installed ClickHouse 22.3 via HomeBrew. And recently, I upgrade it to 22.7 for transaction feature No matter I use clickhouse-jdbc-0.3.2-patch11 `jdbc:ch://localhost:8123/default?transactionSupport` or use clickhouse-client `begin transaction ..`
> 
> I still get exception that "Transactions are not support: while starting a transaction with 'implicit_transaction'"
> 
> is there anything i miss?

**Comment by lelezhan** [comment]
> 

Add some setting values in conf.xml, 
I set allow_experimental_transactions,   <allow_experimental_transactions>42</allow_experimental_transactions> .
Then restart the server, it works;
You can reference https://github.com/ClickHouse/ClickHouse/issues/22086

**Comment by DerekChia** [comment]
You can also reference this PR https://github.com/ClickHouse/ClickHouse/pull/38344
