### ISSUE TITLE
How to disabled system.asynchronous_metric_log table？

### ISSUE THREAD

**Issue by LuPan2015** [ClickHouse/ClickHouse#40056]
Because the data in the system.asynchronous_metric table has been collected into promethues. So I don't need to keep system.asynchronous_metric_log . How can I disable system.asynchronous_metric_log table

**Comment by melvynator** [comment]
1. Stop your server 
2. Remove https://github.com/ClickHouse/ClickHouse/blob/de49e1ae9a124a2d8d9fb8166a9d17a5faee1e20/programs/server/config.xml#L1077 from your config file
3. Drop the `system.asynchronous_metric_log`: `drop table system.asynchronous_metric_log`
4. profit

**Comment by LuPan2015** [comment]
> 1. Stop your server
> 2. Remove https://github.com/ClickHouse/ClickHouse/blob/de49e1ae9a124a2d8d9fb8166a9d17a5faee1e20/programs/server/config.xml#L1077
>     from your config file
> 3. Restart your server
> 4. Drop the `system.asynchronous_metric_log`: `drop table system.asynchronous_metric_log`
> 5. profit

yes. thanks
