### ISSUE TITLE
FR: Support MaterializeMySQL database engine

### ISSUE THREAD

**Issue by zhang2014** [ClickHouse/ClickHouse#4006]
When executing `CREATE DATABASE database_name ENGINE = MaterializeMySQL(mysql_host:mysql_port, mysql_database, mysql_user, mysql_password)`.

- [x] Step 1:
    We need to create the tables existing in MySQL in the ClickHouse and input the data at the same time.

    It does the following(one MySQL session):
    ``` sql
    MySQL :> FLUSH TABLES;
    MySQL :> FLUSH TABLES WITH READ LOCK;
    MySQL :> SHOW MASTER STATUS; /* fetch binlog_file binlog_position*/
    MySQL :> SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
    MySQL :> START TRANSACTION /*!40100 WITH CONSISTENT SNAPSHOT */;
    MySQL :> SHOW CREATE TABLE ... /* each tables in mysql_database */;
    MySQL :> UNLOCK TABLES;

    ClickHouse :> CREATE TABLE dump_table_name(..., `_sign` Int8, `_version` UInt64) ENGINE = ReplacingMergeTree(_version) PARTITION primary_keys, ORDER BY primary_keys[not increment], keys[not increment], unique_keys[not increment], keys[increment], unique_keys[increment], primary_keys[increment]; /* dump table struct */
    ClickHouse :> INSERT INTO dump_table_name SELECT *, 1 AS _sign, 1 AS _version FROM mysql(mysql_host:mysql_port, mysql_database, dump_table_name, mysql_user, mysql_password); /* dump table data */

    MySQL :> COMMIT;
    ```

- [x] Step 2:
    We need to consume MySQL binlog event in real time to pull real-time data( [MySQL Replication Protocol](https://dev.mysql.com/doc/internals/en/replication-protocol.html)  )

    It does the following(one thread):
    - MYSQL_WRITE_ROWS_EVENT : write data to buffer and flush data when (bytes | rows | time  > settings)
        - sign_column = 1, version_column = ++version(Initial value: UInt64(2))
    - MYSQL_DELETE_ROWS_EVENT: write data to buffer and flush data when (bytes | rows | time  > settings)
        - sign_column = -1, version_column = ++version(Initial value: UInt64(2))
    - MYSQL_UPDATE_ROWS_EVENT: write data to buffer and flush data when (bytes | rows | time  > settings)
        - When not modified order by expression columns
            - old data: no insert.
            - new data: sign_column = 1, version_column = ++version(Initial value: UInt64(2))
        - When modify order by expression columns
            - old data: sign_column = -1, version_column = ++version(Initial value: UInt64(2))
            - new data: sign_column = 1, version_column = ++version(Initial value: UInt64(2))
    - MYSQL_QUERY_EVENT: flush data, transform and execute the query
        - CREATE TABLE Query: Same as dump table structure
        - DROP TABLE Query: Same as ClickHouse drop table query
        - RENAME TABLE Query: Same as ClickHouse rename table query
        - ALTER TABLE Query: transform ADD_COLUMN, DROP_COLUMN, RENAME_COLUMN, MODIFY_COLUMN
        - Ignore other query.

**Comment by filimonov** [comment]
Related https://www.altinity.com/blog/2017/12/1/mysql-to-clickhouse-data-migration-and-replication-airlineontime-dataset

**Comment by zhang2014** [comment]
Update:

Maybe we can :
``` sql
CREATE DATABASE clickhouse_database_name ENGINE = MySQL(...) SETTINGS locality = true
[, default_table_engine = CollapsingMergeTree]
```
`MySQL` tables will be created in `ClickHouse`(table engine = `CollapsingMergeTree`), And the data will be obtained through the [MySQL Replication Protocol](https://dev.mysql.com/doc/internals/en/replication-protocol.html) and written to the local table. 

TODO list:
- [ ] Support Settings for MySQL Database (Related #3929)
- [ ] Support MySQL Replication Protocol for MySQL Database
- [ ] Forward alter, update, delete, create, drop statement to MySQL

**Comment by BohuTANG** [comment]
Update:
https://github.com/ClickHouse/ClickHouse/pull/10306

Binlog Network Stream:
- [x] Client handshake
- [x] Client ping
- [x] Client register slave
- [x] Client binlog event dump
- [x] Client receive binlog events over the network stream

Binlog Event:
- [x] FormatDescriptionEvent
- [x] RotateEvent
- [x] QueryEvent
     - [x] DDL
     - [x] XA START/END/PREPARE/COMMIT, not ROLLBACK
- [x] XIDEvent
- [x] TableMapEvent
- [x] RowsEvent
     - [x] MYSQL_TYPE_NULL -> Null
     - [x] MYSQL_TYPE_TINY -> UInt8
     - [x] MYSQL_TYPE_SHORT -> UInt16
     - [x] MYSQL_TYPE_INT24 -> UInt32
     - [x] MYSQL_TYPE_LONG -> UInt32
     - [x] MYSQL_TYPE_LONGLONG -> UInt64
     - [x] MYSQL_TYPE_FLOAT -> Float64
     - [x] MYSQL_TYPE_DOUBLE -> Float64
     - [x] MYSQL_TYPE_TIMESTAMP -> UInt32, Unix Timestamp 
     - [x] MYSQL_TYPE_TIME -> String, format("%02d:%02d:%02d")
     - [x] MYSQL_TYPE_DATE -> String, format("%04d-%02d-%02d")
     - [x] MYSQL_TYPE_YEAR -> String, format("%04d")
     - [x] MYSQL_TYPE_TIME2 -> String, format("%02d:%02d:%02d") or format("%02d:%02d:%02d.%06d") with fractional
     - [x] MYSQL_TYPE_TIMESTAMP2 -> UInt64, Unix Timestamp
     - [x] MYSQL_TYPE_DATETIME2 -> UInt64, Unix Timestamp
     - [x] MYSQL_TYPE_ENUM -> Int32
     - [x] MYSQL_TYPE_NEWDECIMAL -> String
     - [x] MYSQL_TYPE_VARCHAR -> String
     - [x] MYSQL_TYPE_VAR_STRING -> String
     - [x] MYSQL_TYPE_STRING -> String
     - [x] MYSQL_TYPE_GEOMETRY -> String
     - [x] MYSQL_TYPE_BLOB -> String
     - [x] MYSQL_TYPE_JSON -> String, JSONB(JSON binary format)
     - [x] Others -> throw exception

**Comment by zhang2014** [comment]
To be compatible SQL:
- [ ] ALTER TABLE table_name ADD COLUMN column_name, RENAME COLUMN column_name TO new_column_name;

**Comment by zhang2014** [comment]
Update:

Maybe we also need `ReplicateMaterializeMySQL`
- It is highly available MaterializedMySQL. The SyncThread always works in the leader and will switch if the leader is not available.
- Use ReplicateReplacingMergeTree

**Comment by BohuTANG** [comment]
Update:

- [ ] GTID replication support, depend on this #13672 finished

**Comment by andy-zhang2016** [comment]
MaterializeMySQL database engine is a nice feature.  I tried it and found the replication missed to refresh the stats information of total rows, total bytes,  in system tables like system.tables.
Can we have it ? @BohuTANG @zhang2014

**Comment by zhang2014** [comment]
Planned task:  Implement more methods for StorageMaterializeMySQL, such as optimize, getActionLock, supportsPrewhere, mayBenefitFromIndexForIn, checkData, totalRows

**Comment by andy-zhang2016** [comment]
> Planned task: Implement more methods for StorageMaterializeMySQL, such as optimize, getActionLock, supportsPrewhere, mayBenefitFromIndexForIn, checkData, totalRows

So, what's the schedule then?

**Comment by EmmyMiao87** [comment]
This is a very nice feature to connect Mysql(OLTP) and Clickhouse(OLAP). There is a question that is it possible to ensure that multiple rows are atomically updated to Clickhouse?

**Comment by zhang2014** [comment]
> This is a very nice feature to connect Mysql(OLTP) and Clickhouse(OLAP). There is a question that is it possible to ensure that multiple rows are atomically updated to Clickhouse?

Of course. but there are some bugs that we're trying to fix.

**Comment by imysm** [comment]
Report issue:
 when talbe include data type of timestamp(6) or timestamp(8) and so on,MaterializeMySQL could not create the table. 
Error log is : 
`2020.09.17 14:15:30.953389 [ 32249 ] {} <Error> MaterializeMySQLSyncThread(wxeedb): Query EXTERNAL DDL FROM MySQL(wxeedb, wxeedb)  CREATE TABLE `dd_wxee_openids` (
  `ID` bigint(65) NOT NULL AUTO_INCREMENT,
  `LAST_TIME` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNION_ID_IDX` (`UNION_ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=44 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci wasn't finished successfully: Code: 43, e.displayText() = DB::Exception: Parameter for DateTime data type must be string literal, Stack trace (when copying this message, always include the lines below):
`

**Comment by zhang2014** [comment]
@imysm It implemented in https://github.com/ClickHouse/ClickHouse/pull/14535 (no merge)

**Comment by hei-** [comment]
Env:
    clickhouse:  21.1.2.15 
    mysql: 5.7.9

Execute SQL:

    CREATE DATABASE  xxx ENGINE = MaterializeMySQL('x.x.x.x:3306', 'db_name', 'xxx', 'xxx.')

Error:

    2021.04.12 02:13:05.623932 [ 46 ] {c4ad0e3d-f7d3-47dd-8f38-7dbaa9524ca4} <Error> TCPHandler: Code: 1000, e.displayText() = DB::Exception: mysqlxx::BadQuery: Unknown column 'Value' in 'where clause' (x.x.x.x:3306), Stack trace:
    
    0. mysqlxx::Query::executeImpl() @ 0x11d46de4 in /usr/bin/clickhouse
    1. DB::MySQLBlockInputStream::Connection::Connection(mysqlxx::Pool::Entry const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xf8b0524 in /usr/bin/clickhouse
    2. DB::MySQLBlockInputStream::MySQLBlockInputStream(mysqlxx::Pool::Entry const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Block const&, unsigned long, bool, bool) @ 0xf8b0602 in /usr/bin/clickhouse
    3. DB::MaterializeMySQLSyncThread::startSynchronization() @ 0xeb86aa1 in /usr/bin/clickhouse
    4. DB::DatabaseMaterializeMySQL<DB::DatabaseAtomic>::loadStoredObjects(DB::Context&, bool, bool) @ 0xebc6d9c in /usr/bin/clickhouse
    5. DB::InterpreterCreateQuery::createDatabase(DB::ASTCreateQuery&) @ 0xedbd4b6 in /usr/bin/clickhouse
    6. DB::InterpreterCreateQuery::execute() @ 0xedcc9c7 in /usr/bin/clickhouse
    7. ? @ 0xf17d029 in /usr/bin/clickhouse
    8. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool) @ 0xf17b99d in /usr/bin/clickhouse
    9. DB::TCPHandler::runImpl() @ 0xf8844d6 in /usr/bin/clickhouse
    10. DB::TCPHandler::run() @ 0xf8932e7 in /usr/bin/clickhouse
    11. Poco::Net::TCPServerConnection::start() @ 0x11dd646f in /usr/bin/clickhouse
    12. Poco::Net::TCPServerDispatcher::run() @ 0x11dd7e81 in /usr/bin/clickhouse
    13. Poco::PooledThread::run() @ 0x11f03809 in /usr/bin/clickhouse
    14. Poco::ThreadImpl::runnableEntry(void*) @ 0x11eff79a in /usr/bin/clickhouse
    15. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
    16. clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so


tcpdump :

    SHOW VARIABLES WHERE (Variable_name = 'log_bin' AND upper(Value) = 'ON') OR (Variable_name = 'binlog_format' AND upper(Value) = 'ROW') OR (Variable_name = 'binlog_row_image' AND upper(Value) = 'FULL') OR (Variable_name = 'default_authentication_plugin' AND upper(Value) = 'MYSQL_NATIVE_PASSWORD')

find  run this sql  error :  Unknown column 'Value' in 'where clause'

but ,   this sql  can run in mysql 5.7.28、5.7.17、5.6.16 .

**Comment by tavplubix** [comment]
> mysql: 5.7.9
> find run this sql error : Unknown column 'Value' in 'where clause'
> but , this sql can run in mysql 5.7.28、5.7.17、5.6.16 .

Looks like a bug in MySQL. Maybe it related somehow to https://bugs.mysql.com/bug.php?id=79549, but I'm not sure.

**Comment by TCeason** [comment]
In 5.7.9 the query is not supported. But may be you can try to use this model:

Master 5.7.9->Slave 5.7.28->ClickHouse

Or upgrade your 5.7.9 to a new version.

**Comment by hei-** [comment]
How to check MaterializeMySQL's sync stauts? Does it has method like: show sync status, stop sync, start sync ,re-sync
