### ISSUE TITLE
groupArray on tuple returns unexpected result

### ISSUE THREAD

**Issue by iNetJoJo** [ClickHouse/ClickHouse#40077]
**groupArray on tuple returns unexpected result**

Queries that result this issue

```sql
SELECT groupArray((col1, col2)) as arrayOfTuples FROM table
```
![image](https://user-images.githubusercontent.com/48105082/184010005-a637c8d8-4646-4ba4-acac-2b228398e57b.png)

**Comment by den-crane** [comment]
JDBC issue https://github.com/ClickHouse/clickhouse-jdbc

**Comment by den-crane** [comment]
Moreover it's a JAVA way to render `Array(Tuple(<T>,<T>) )` to a String.
