### ISSUE TITLE
Parts are created indefinitely after mutation

### ISSUE THREAD

**Issue by M1ha-Shvn** [ClickHouse/ClickHouse#40076]
* Which ClickHouse server version to use*
19.10.1.5

**Describe the issue**
Hi.
Two hours after executing a mutation query `ALTER TABEL my_table DELETE WEHRE id IN (...)`, we saw, that table, it had been executed at, have lots of parts in partitions (which had been used by the query) and their number grows indefinitely. A little bit digging inside showed, that:
1. number of merged rows according to metrics significantly reduced after query (from 5 million of records to 200k records. May be these records left are from other tables)
2. mutations has not been executed yet, they were still present in `system.mutations` table with `is_done=0`.

I've killed all mutations with `KILL MUTATION ...` query. `system.mutations` table is now empty. But the problem with parts has not gone. They are still growing indefinitely.

The only message I see in logs is (in different variations for different parts and sizes):
`2022.08.10 21:19:43.976987 [ 10 ] {} <Debug> carrot.chevent (ReplicatedMergeTreeQueue): Not executing log entry for part 202208_0_26606_179 because source parts size (2.13 GiB) is greater than the current maximum (100.59 MiB).`

I also found out, that there is a `system.replication_queue` with type `MUTATION` which can not process itself with same error as in logs, for example:
```
┌─database─┬─table───────────────────┬─new_part_name─────────────┬─type────────┬─replica_name─────┬─source_replica───┬─postpone_reason─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─is_currently_executing─┬─num_postponed─┬─last_exception─┐
│ carrot   │ chconversationpart      │ 201912_27326_33233_229    │ MERGE_PARTS │ ru-db-ch-node-02 │ ru-db-ch-node-01 │ Not executing log entry for part 201912_27326_33233_229 because source parts size (105.47 MiB) is greater than the current maximum (100.59 MiB).    │                      0 │         23658 │                │
```

I've tried stopping all inserts to CH for 10 minutes. But no significant changes occured: negther more merged rows, nor less parts.

What can I do now? Is there a way to kill this replication processes? or replicate them manually? Or may be you can give some other suggestions where I can look?
Thanks

**Comment by den-crane** [comment]
19.10.1.5 is out of support. 
Use 22.7

**Comment by den-crane** [comment]
Probably you need to clean ZK tasks manually.

**Comment by M1ha-Shvn** [comment]
For future readers:
1. Found mutated parts, not replicated with `SELECT replica_path || '/queue/' || node_name FROM system.replication_queue  JOIN system.replicas USING (database, table) WHERE type='MUTATE_PART';` on each data node separately
2. Removed found tasks using `zkCli.sh rmr`, than calling `SYSTEM RESTART REPLICAS` sql query
3. After that, merges in tables started working, but number of parts stuck on ~700 parts in some partitions (from 2k before removing bad replication tasks)
4. Next, I played a little bit more with [`max_bytes_to_merge_at_max_space_in_pool`, `max_bytes_to_merge_at_min_space_in_pool`, `number_of_free_entries_in_pool_to_lower_max_size_of_merge` MergeTree settings](https://clickhouse.com/docs/en/operations/settings/merge-tree-settings/#max-bytes-to-merge-at-max-space-in-pool), trying to increase the max size of parts to be merged. Size is calculated by [this function](https://github.com/ClickHouse/ClickHouse/blob/42ea79c266850239c5640a3f4ea34531b92ba62c/src/Storages/MergeTree/MergeTreeDataMergerMutator.cpp#L83). So I:
    * Decreased `number_of_free_entries_in_pool_to_lower_max_size_of_merge`
    * Increased `max_bytes_to_merge_at_max_space_in_pool`
5. After this modification lots of parts have been merged, from 700 per partition to less than 50 in my case
