### ISSUE TITLE
Why the TTL policy doesn't have an effect?

### ISSUE THREAD

**Issue by rfyiamcool** [ClickHouse/ClickHouse#40098]
### clickhouse don't  delete the expired partiton ?

I found many expired partions in system.parts, i don't konw what caused this problem ?  😅 

<img width="1742" alt="image" src="https://user-images.githubusercontent.com/3785409/184058069-59114f2d-ede5-497b-a63b-11d2e4e93592.png">

show current ttl policy.

```sql
CREATE TABLE logging.`or-domain-service`
(
    ....
)
ENGINE = MergeTree
PARTITION BY toStartOfInterval(datetime, toIntervalHour(12))
ORDER BY datetime
TTL logging_create_time + toIntervalDay(30)
SETTINGS index_granularity = 8192, storage_policy = 'jbod_policy'
```

get the current time.

```sql
clickhouse-02.ali.bj :) select now();

SELECT now()

Query id: 9b4e4ec6-0adc-4f81-a817-d5debbd545ee

┌───────────────now()─┐
│ 2022-08-11 11:04:47 │
└─────────────────────┘

1 row in set. Elapsed: 0.007 sec.
```

then query some previous values of `logging_create_time` in table or-domain-service.

```sql
clickhouse-02.ali.bj :) select datetime, logging_create_time from `or-domain-service` limit 10 FORMAT Pretty;

Query id: 22c86dc1-ffc0-4300-8c55-4bb7764b61cd

┏━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━┓
┃                datetime ┃ logging_create_time ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━┩
│ 2022-06-25 10:18:40.688 │ 2022-06-25 11:53:21 │
├─────────────────────────┼─────────────────────┤
│ 2022-06-25 10:18:42.053 │ 2022-06-25 11:53:09 │
├─────────────────────────┼─────────────────────┤
│ 2022-06-25 10:18:42.415 │ 2022-06-25 11:53:09 │
├─────────────────────────┼─────────────────────┤
│ 2022-06-25 10:18:45.960 │ 2022-06-25 11:53:09 │
├─────────────────────────┼─────────────────────┤
│ 2022-06-25 10:18:46.312 │ 2022-06-25 11:53:09 │
├─────────────────────────┼─────────────────────┤
│ 2022-06-25 10:18:46.381 │ 2022-06-25 11:53:20 │
├─────────────────────────┼─────────────────────┤
│ 2022-06-25 10:18:46.384 │ 2022-06-25 11:53:21 │
├─────────────────────────┼─────────────────────┤
│ 2022-06-25 10:18:46.425 │ 2022-06-25 11:53:09 │
├─────────────────────────┼─────────────────────┤
│ 2022-06-25 10:18:46.490 │ 2022-06-25 11:53:21 │
├─────────────────────────┼─────────────────────┤
│ 2022-06-25 10:18:46.545 │ 2022-06-25 11:53:21 │
└─────────────────────────┴─────────────────────┘

**Comment by rfyiamcool** [comment]
clickhouse-server version

```
clickhouse-server  --version
ClickHouse server version 22.2.2.1.
```

**Comment by rkozlo** [comment]
Consider using partition key column as TTL rule.

**Comment by rfyiamcool** [comment]
Thank you for answering my question. @rkozlo 

But i have 200+ table,  then the tables use `logging_create_table` field in the same way, the field is not partiton key.

what should i do ?  😅

**Comment by rkozlo** [comment]
Hard to say. I don't know what data you have there. Think what using different column as TTL rule causes. Clickhouse will look through all partitions because can't use any index. It isn't efficient.
Btw. you are looking in system.parts and partition name and want to delete this parts because you know data there is obsolete and shoule be deleted. Even if `datetime` and `logging_create_time` indicates the same Date clickhouse isn't aware of this and have to check every single row there. When partition key is used, clickhouse can easily use minmax_index and skip whole partitions.

**Comment by sunny19930321** [comment]
If there is only 1 part left, it will not be in the merge, and the data will not be deleted
