### ISSUE TITLE
Is it ok and good to use intHash64(createdAtDateTime) for the Sample By?

### ISSUE THREAD

**Issue by veqryn** [ClickHouse/ClickHouse#40093]
We are using clickhouse server version 22.3.2.2 on linux.  Our cluster is 12-24 nodes, and has many other tables and schemas on it.
I have a replicated table like so:
```sql
CREATE TABLE IF NOT EXISTS mydb.mytable_local ON CLUSTER mycluster (
    created          DateTime,
    eventday         Date DEFAULT toDate(created),
    user_id          UInt32,
    ttldays          UInt16 DEFAULT 548
    -- lots of other columns
)
    ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/mydb.mytable_local', '{replica}')
    PARTITION BY toYYYYMM(eventday)
    ORDER BY (user_id, eventday, toStartOfHour(created), toStartOfMinute(created), intHash64(created))
    TTL eventday + toIntervalDay(ttldays) DELETE
    SAMPLE BY intHash64(created);

CREATE TABLE IF NOT EXISTS mydb.mytable ON CLUSTER mycluster AS mydb.mytable_local ENGINE = Distributed(mycluster, mydb, mytable_local, rand());
```

My first question is:
Can I use `intHash64(created)` as the sample by value?  Or does it need to be `intHash64(toUInt32(created))`?
It seems to be valid right now, but I wanted to make sure it would be valid in the future as well, in case things got more strict with the types.  My understanding is that DateTime is a UInt32 under the hood.

My second question is:
Is this a good sample by value?
Right now, we get around 200-400 million rows per day, average.  The average user has maybe 1500 rows per minute, but the max rows per minute I've seen for some users is around 100000.
We do a lot of queries the group by eventday, or group by toStartOfHour(created), or group by toStartOfMinute(created).  That is why those are in the Order By.
The reason I thought to use intHash64(created) as a SAMPLE BY is because no other column is all that evenly distributed or filled in all the time.  
If this isn't a good sample by value, what would you recommend we do?

**Comment by genzgd** [comment]
You are correct, DateTime is stored and processed as a UInt32 value and most functions that accept a UInt32 will work with a DateTime column.  This will not change as it would be a significant breaking change.  You might also check the performance of intHash32 vs intHash64.

Given your table structure it is probably a reasonable selection for SAMPLE KEY.  Unless there is some weird distribution of your data that all of your events end up in the same second, you should get a good distribution.

Note that your ORDER BY is unnecessarily long . . . ORDER BY (user_id, created, intHash64(created)) should have the same effect, as your rows on disk will be saved in exactly the same order and the query processor will correctly account for expressions that include 'created'.
