### ISSUE TITLE
How to replace data with the average of all data for the current hour in increasing table 

### ISSUE THREAD

**Issue by DangoTinker** [ClickHouse/ClickHouse#40108]
reater than the average of all data for the current hour in Table A. Table A is continuously increasing.

I tried to use materialized views but it didn't seem feasible.

I found that using the Time Window worked. But I can't upgrade ClickHouse

Is there any way to achieve this?

**Comment by den-crane** [comment]
`AggregateFunction(avg` ?

```sql
create table in(key Int64, hour DateTime, value Float64) Engine=MergeTree order by key;

create table out (key Int64, hour DateTime, value AggregateFunction(avg,Float64))
Engine=AggregatingMergeTree order by (key, hour);

create materialized view mv1 to out
as select key, toStartOfHour(hour) hour, avgState(value) as value 
from in 
group by key, hour;

insert into in values(1, '2020-10-01 01-01-01', 1);
insert into in values(1, '2020-10-01 01-01-31', 5);

optimize table out final;

select count() from out;
┌─count()─┐
│       1 │
└─────────┘

select key,hour, avgMerge(value) from out group by key,hour;
┌─key─┬────────────────hour─┬─avgMerge(value)─┐
│   1 │ 2020-10-01 01:00:00 │               3 │
└─────┴─────────────────────┴─────────────────┘
```

**Comment by DangoTinker** [comment]
in:

**Comment by DangoTinker** [comment]
> `AggregateFunction(avg` ?
> 
> ```sql
> create table in(key Int64, hour DateTime, value Float64) Engine=MergeTree order by key;
> 
> create table out (key Int64, hour DateTime, value AggregateFunction(avg,Float64))
> Engine=AggregatingMergeTree order by (key, hour);
> 
> create materialized view mv1 to out
> as select key, toStartOfHour(hour) hour, avgState(value) as value 
> from in 
> group by key, hour;
> 
> insert into in values(1, '2020-10-01 01-01-01', 1);
> insert into in values(1, '2020-10-01 01-01-31', 5);
> 
> optimize table out final;
> 
> select count() from out;
> ┌─count()─┐
> │       1 │
> └─────────┘
> 
> select key,hour, avgMerge(value) from out group by key,hour;
> ┌─key─┬────────────────hour─┬─avgMerge(value)─┐
> │   1 │ 2020-10-01 01:00:00 │               3 │
> └─────┴─────────────────────┴─────────────────┘
> ```

I need :

in :
insert into in values(1, '2020-10-01 01-01-01', 1);
insert into in values(1, '2020-10-01 01-01-31', 5);

avg: (1+5)/2 = 3

because 5 > avg : 5 -> 3

out:
1, '2020-10-01 01-01-01', 1
1, '2020-10-01 01-01-01', 3

I can do it by execution sql regularly. I wonder if this can be done automatically within clickhouse or other way?
