### ISSUE TITLE
ReplicatedMergeTree tables should be able to start up if ZooKeeper is configured but unavailable

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#40105]
**Describe the solution you'd like**

We already can run clickhouse-server without configured ZooKeeper (the tables will start in read-only mode)
and with configured ZooKeeper, if it starts to be inaccessible at runtime (the tables will be read-only until the session is re-established).

Let's also make it possible to start up when ZooKeeper is unavailable.

**Additional context**

If that will be very hard to implement, we can consider other options:
- lazy attaching of the tables after sever start-up;
- a maintenance mode when the tables are not attached at start-up and require manual ATTACH queries.

**Comment by antonio2368** [comment]
The biggest problem is the checks being done during the startup.

What if it fails in the background while we try to attach a table (a check that notices some inconsistencies with the ZK data)?
Is it okay to leave it just as readonly?

**Comment by tavplubix** [comment]
> What if it fails in the background while we try to attach a table (a check that notices some inconsistencies with the ZK data)?
Is it okay to leave it just as readonly?

Yes, I think it's totally fine to leave table readonly in this case (it's even ok to just keep retrying to initialize replication and infinitely print exceptions into logs)
