### ISSUE TITLE
Add `%z` format descriptor for `formatDateTime` function.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#40103]
**Use case**

It should output the offset in format `+hhmm` or `-hhmm`,
if the offset is zero, it should print `+0000`.

**Describe the solution you'd like**

See `formatDateTime.cpp`
and `DateLUTImpl::getTimezoneOffset`
and `man strptime`

**Additional context**

Continuation of #9959.

**Comment by HeenaBansal2009** [comment]
Do we have any function which returns any/specific date format in to IS0 8601 format ?
something like : from (2017-10-15 12:00) -->    2017-10-15T12:00:00.0000000Z

**Comment by alexey-milovidov** [comment]
@HeenaBansal2009 no, although it will be easy to implement.

We can name it `formatDateTimeISO8601UTC`.
