### ISSUE TITLE
Using `JSONEachRowWithProgress` format produces strange progress numbers with LIMIT

### ISSUE THREAD

**Issue by pkit** [ClickHouse/ClickHouse#40126]
As you can see the `total_rows_to_read` is the whole result and not a limited one, which produces strange behavior for progress bars.
As there is no way to know when it's really finished.
```
$ echo 'SELECT number FROM numbers(10000*1000000) limit 10000' | curl -i -H 'X-ClickHouse-Format: JSONEachRowWithProgress' -s 'http://localhost:8123/' --data-binary @- | grep progress
{"progress":{"read_rows":"0","read_bytes":"0","written_rows":"0","written_bytes":"0","total_rows_to_read":"0","result_rows":"0","result_bytes":"0"}}
{"progress":{"read_rows":"0","read_bytes":"0","written_rows":"0","written_bytes":"0","total_rows_to_read":"10000000000","result_rows":"0","result_bytes":"0"}}
{"progress":{"read_rows":"10000","read_bytes":"80000","written_rows":"0","written_bytes":"0","total_rows_to_read":"10000000000","result_rows":"0","result_bytes":"0"}}
```

**Comment by alexey-milovidov** [comment]
As far as I know this format is only usable with LIVE VIEW.

**Comment by alexey-milovidov** [comment]
This behavior is expected.

It is not always possible to derive the number of total rows to read in presence of the LIMIT clause.
For example, if the WHERE clause or GROUP BY or DISTINCT or ... anything is also present.
Another example: if there is a FINAL modifier on reading from a MergeTree table.
Or if there is a row-level security policy.

It can be improved but will require additional logic in code for this specific case.
You can open a feature request for this.
