### ISSUE TITLE
Insert into distributed table could lose data.

### ISSUE THREAD

**Issue by asxdfd** [ClickHouse/ClickHouse#40143]
Recently I met a problem that sometimes I could lose some data after inserting to a distributed table.
I have checked the code and do some tests, here's some cases I found could lead to data lost while inserting into distributed table.

- case1: Remote server is closed during inserting. This would throw `Connection refused`.
- case2: Local server is terminated before temp files sent to remote shard. This would be recovered after local server restart.
- case3: Local server is terminated before temp files sent to remote shard, and remote shard is removed from cluster. This would throw `Cannot get connection from ConnectionPoolWithFailover cause nested pools are empty`
- case4: After throw `Cannot get connection from ConnectionPoolWithFailover cause nested pools are empty` for local temp files, add remote shard back to the cluster. Then new data can't be sent to the shard. The exception will be throwed because of retry.

In my scenario, I just add some new shards into my cluster. No shard has been removed from the cluster. And all remote servers are running correctly because I executed other insert queries and no exception has been throwed. Besides, I have checked disk files, there's only an old file in the local folder (created 7 days ago).
So is there any other cases that will lead to data lost for `insert into distributed_table`?

**Comment by den-crane** [comment]
Do you use MergeTree or ReplicatedMergeTree tables?

Are you aware about insert deduplication? https://kb.altinity.com/altinity-kb-schema-design/insert_deduplication/

**Comment by asxdfd** [comment]
I use ReplicatedMergeTree. I have learned insert dedupication for ReplicatedMergeTree, it's implemented by `block_id`, which is generated **using hash of the block data** (Is it right?). So maybe there can be different blocks with same hash results. But I think the probability is very low.
