### ISSUE TITLE
insert_deduplication_token documentation incorrect

### ISSUE THREAD

**Issue by scottix** [ClickHouse/ClickHouse#40140]
**Describe the issue**
The example for [insert_deduplication_token](https://clickhouse.com/docs/en/operations/settings/settings/#insert_deduplication_token) is incorrect.

Values should be after the settings

**wrong**
INSERT INTO test_table Values SETTINGS insert_deduplication_token = 'test' (1);

**correct**
INSERT INTO test_table SETTINGS insert_deduplication_token = 'test' VALUES (1);

**Comment by devcrafter** [comment]
Fixed in #40166
