### ISSUE TITLE
Zookeeper and ClickhouseKeeper

### ISSUE THREAD

**Issue by jiangbiao910** [ClickHouse/ClickHouse#40145]
Hello EveryBody,
Recently , I want to  migration Zookeeper and ClickhouseKeeper。
I want to know  does ClickhouseKeeper has client cmd？
because I can use  /opt/module/zookeeper-3.7.0/bin/zkCli.sh  
and “ls /” 
![image](https://user-images.githubusercontent.com/23710717/184299974-286a9470-5c0a-4b48-9e32-91a81901867f.png)
thank you for your help!

**Comment by den-crane** [comment]
ClickhouseKeeper implements Zookeeper API and Zookeeper network protocol.

You can use ClickhouseKeeper as a substitute of Zookeeper with any other product or tool.

zkCli.sh and zkshell work with ClickhouseKeeper.

**Comment by jiangbiao910** [comment]
Thank you very much！
But I have another question：
How to Restart or Stop Clickhouse Keeper？

I use `sudo -u clickhouse clickhouse-keeper --config /etc/clickhouse-server/keeper.xml --daemon` to start clikhouse keeper ，But I don't know  how to restart？ kill the pid？
