### ISSUE TITLE
Actions: Maybe wrong package type 

### ISSUE THREAD

**Issue by cangyin** [ClickHouse/ClickHouse#40159]
See screenshot below, `build_check.py` specifies "--package-type=deb", but `docker/packager/packager` actually runs with image `clickhouse/binary-builder`.

The error exists in branch 22.3:
[`docker/packager/packager:334`](https://github.com/ClickHouse/ClickHouse/blob/22.3/docker/packager/packager#L334)
```c++
    image_name = "clickhouse/binary-builder"
```

In branch 22.2, the error does not exist:
[`docker/packager/packager:223`](https://github.com/ClickHouse/ClickHouse/blob/4dcd392c6b774f3463b6e758c3bb038edb2e173b/docker/packager/packager#L223)
```c++
    image_name = IMAGE_MAP[image_type]
```

![image](https://user-images.githubusercontent.com/50256182/184366252-b63f96b4-e01b-4438-8198-52bdb71c63dd.png)

**Comment by Felixoid** [comment]
we have only one image for both debian and binary builds
