### ISSUE TITLE
Timed out query leads to AST fuzzer error

### ISSUE THREAD

**Issue by nickitat** [ClickHouse/ClickHouse#40164]
I have a fuzzer [report](https://s3.amazonaws.com/clickhouse-test-reports/40142/c85d1fdb30afee43638e455b6e481f9645a567ce/fuzzer_astfuzzermsan//fuzzer.log) and afaiu the problem is that we lost connection due to query timeout. see `Changed settings: receive_timeout = '10', receive_data_timeout_ms = '10000'` at the very end of the report.
the query itself took much more than 10s. 
```
2022.08.12 03:59:33.092801 [ 206 ] {48dda01d-ee6d-4924-a532-2f61f386a1df} <Debug> executeQuery: (from [::ffff:127.0.0.1]:49480) SELECT 0.9998999834060669, (1.1754943508222875e-38 AND arrayJoin([NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL])) AND NULL AND arrayJoin([NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL]), (0.00009999999747378752 AND arrayJoin([NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL])) AND NULL AND arrayJoin([NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL]) FROM min_if (stage: Complete)
2022.08.12 03:59:58.705512 [ 468 ] {48dda01d-ee6d-4924-a532-2f61f386a1df} <Debug> MemoryTracker: Current memory usage (total): 28.65 GiB.
```
to detect this case we have a [check](https://github.com/ClickHouse/ClickHouse/blob/master/docker/test/fuzzer/run-fuzzer.sh#L256-L262), but I don't see this test query in server.log for some reason.

probably we need to add retries for this test query. and maybe rerun fuzzer.

**Comment by alexey-milovidov** [comment]
But we also set limitations on query run time in Fuzzer.
And fuzzer checks that these limitations work for every query.
