### ISSUE TITLE
Two questions about ClickHouse in-memory data formats

### ISSUE THREAD

**Issue by arunmarathe** [ClickHouse/ClickHouse#40165]
I have two questions about ClickHouse in-memory data format.

The most performant on-disk data format would, of course, be MergeTree. For a given table, would it be accurate to say that the "in-memory" image of that table would be its memtable? Or is it the case that MergeTree format somehow continues to show up "in memory" as well? Of course, the answer to this question is probably complicated because in addition to memtable, various Bloom filters make up "in memroy" format too. I am not looking for a comprehensive list of data structures that make up a table's "in memory" footprint, but just the major players' names would be adequate. I can think of memtable and Bloom filters. Did I miss anything major? Does compression/decompression provided by various codecs play a role in "in memory" formats?

Second question: Does CH implement memtable using red-black tree?

Any pointer to documentation would be helpful too in addition to the answers to these questions.

Thanks,
Arun

PS: I find this question particularly interesting because the in-memory data format for traditional disk-based data structures such as B-trees has relatively straightforward mappings to their in-memory formats without huge differences. This is unlike the case in CH MergeTrees.

**Comment by den-crane** [comment]
MergeTree does not have in-mem format. When you execute a query data is read from the disk (or a OS page cache) and from uncompressed cache (if enabled). 
Primary key index stored in memory always. 
In general each query reads files and decompresses data.

**Comment by arunmarathe** [comment]
> MergeTree does not have in-mem format. When you execute a query data is read from the disk (or a OS page cache) and from uncompressed cache (if enabled). Primary key index stored in memory always. In general each query reads files and decompresses data.

Thanks. What do you mean by "primary key index"? Isn't that the merge tree?
Also, for inserts, CH must be keeping memtable in memory before a full segment is persisted to disk (and becomes part of MergeTree), no? Bloom filters should be handy there too. Or you would consider memtable (eg, red-black tree) unrelated to a MergeTree's in-mem format? The reason I would tend to consider is related because eventually, memtable will be persisted on disk, and become part of MergeTree.

More info (in documentation or elsewhere) would be appreciated. Thanks.

**Comment by den-crane** [comment]
What do you mean by memtable?

**Comment by canhld94** [comment]
> > MergeTree does not have in-mem format. When you execute a query data is read from the disk (or a OS page cache) and from uncompressed cache (if enabled). Primary key index stored in memory always. In general each query reads files and decompresses data.
> 
> Thanks. What do you mean by "primary key index"? Isn't that the merge tree? Also, for inserts, CH must be keeping memtable in memory before a full segment is persisted to disk (and becomes part of MergeTree), no? Bloom filters should be handy there too. Or you would consider memtable (eg, red-black tree) unrelated to a MergeTree's in-mem format? The reason I would tend to consider is related because eventually, memtable will be persisted on disk, and become part of MergeTree.
> 
> More info (in documentation or elsewhere) would be appreciated. Thanks.

Primary key index is a fundamental concept of CH merge tree, I think there's a very good article on the company document page about how data is organised logically and physically as well as primary and skip indices; you may want to check it out.

There's no memtable in MergeTree, in each single write act, data is written to disk as an immutable data part (may include several files), and small parts will be compacted in the background to a bigger part. I also believe there's nothing like a in-memory format of MergeTree. Of course after reading from MergeTree files, CH will store the data in some in-memory format for query processing, but that format is not designated to MergeTree.

The design of CH MergeTree is quite different from some others traditional dbms, so It's hard to relate the component in CH MergeTree <-> components in traditional dbms storage engines. Unfortunately there's no technical paper about the MergeTree engine now, so the only way to understand how it works is to read the code.

**Comment by arunmarathe** [comment]
> What do you mean by memtable?

I was referring to traditional LSM (log structured MergeTree) and one of its secondary data structure is memtable (sometimes implemented using red-black tree) .. and Bloom filter is another secondary data structure.

**Comment by arunmarathe** [comment]
> > > MergeTree does not have in-mem format. When you execute a query data is read from the disk (or a OS page cache) and from uncompressed cache (if enabled). Primary key index stored in memory always. In general each query reads files and decompresses data.
> > 
> > 
> > Thanks. What do you mean by "primary key index"? Isn't that the merge tree? Also, for inserts, CH must be keeping memtable in memory before a full segment is persisted to disk (and becomes part of MergeTree), no? Bloom filters should be handy there too. Or you would consider memtable (eg, red-black tree) unrelated to a MergeTree's in-mem format? The reason I would tend to consider is related because eventually, memtable will be persisted on disk, and become part of MergeTree.
> > More info (in documentation or elsewhere) would be appreciated. Thanks.
> 
> Primary key index is a fundamental concept of CH MergeTree, I think there's a very good article on the company document page about how data is organised logically and physically as well as primary and skip indices; you may want to check it out.
> 
> There's no memtable in MergeTree, in each single write act, data is written to disk as an immutable data part (may include several files), and small parts will be compacted in the background to a bigger part. I also believe there's nothing like a in-memory format of MergeTree. Of course after reading from MergeTree files, CH will store the data in some in-memory format for query processing, but that format is not designated to MergeTree.
> 
> The design of CH MergeTree is quite different from some others traditional dbms, so It's hard to relate the component in CH MergeTree <-> components in traditional dbms storage engines. Unfortunately there's no technical paper about the MergeTree engine now, so the only way to understand how it works is to read the code.

Thanks! By any chance you are referring to this?
https://clickhouse.com/docs/en/guides/improving-query-performance/sparse-primary-indexes/sparse-primary-indexes-design/#data-is-organized-into-granules-for-parallel-data-processing

I will read it. If you refer to something else, let me know.

**Comment by alexey-milovidov** [comment]
Apache Arrow's format is very similar to ClickHouse.
ClickHouse's format has been developed since 2011, and Arrow's since 2016.
I think they independently converged to almost the same format as in ClickHouse.
