### ISSUE TITLE
Is "optimize final" synchronized? We used it to update and delete records in batch job (CollapsingMergeTree)

### ISSUE THREAD

**Issue by taotaizhu-pw** [ClickHouse/ClickHouse#40170]
user.xml:  "set optimize_throw_if_noop=1"

we used "optimize table xxx final" after update or delete records (CollapsingMergeTree, sign=1/-1), with single thread batch job.  At that time, only the batch job operate the clickhouse database.

After execute "optimize table xxx final", Our currect logic:
 
1. If no exception, we judge the merge is done
2. If got exception, execute "optimize table xxx final" after 5 seconds. After try 5 times, if also got exception, we judge the job failed

I want to confirm and check whether my batch job logic is correct? 

Thanks!

**Comment by den-crane** [comment]
>I want to confirm and check whether my batch job logic is correct?

is it replicated table ?

You can use 

```
--optimize_skip_merged_partitions arg                                              Skip partitions with one part with level > 0 in optimize final
```

In this optimize will skip unneeded merges.

Also you can use `system SYNC REPLICA xxx` if your table is replicated, it allows to wait until ongoing merges are finished.

And you can use `select ... from system.parts` and check that data is merged in a partition.

**Comment by taotaizhu-pw** [comment]
> titions with

yes, it is replicated tables.  Thanks for your reply, I would add these logics

**Comment by den-crane** [comment]
> > titions with
> 
> yes, it is replicated tables. Thanks for your reply, I would add these logics

then you should use `system SYNC REPLICA xxx` as a first to wait for finish of current merges.
