### ISSUE TITLE
(Zero-copy replication - not ready for production) ClickHouse does not remove uuid.txt file of remote fs system in Zero-Copy replication after mutation.

### ISSUE THREAD

**Issue by zhaojintaozhao** [ClickHouse/ClickHouse#40187]
Hi all.
In my system, there are two replicas and use zero copy replication. These are my test steps.
```
create table test on cluster '{cluster}' (key UInt32, value1 String, value2 String, value3 String) engine=ReplicatedMergeTree('/test', '{replica}') order by key partition by (key % 4) settings storage_policy='object_storage'

insert into test select * from generateRandom('key UInt32, value1 String, value2 String, value3 String') limit 1000000

alter table test add column valueX String materialized value1

alter table test materialize column valueX
```
I find that the remote file of uuid.txt from old original part is different the remote file of uuid.txt from new part.
After 20 min（ClickHouse removes old original parts in 8 min）, I find that the all the old original part's metadata file had been removed in local disk. But there is remote file of uuid.txt from old original in remote fs(just like in s3). 

Problem:
**This remote file of uuid.txt from old original does not relcated to part metadata. This file is unused and will never be removed.**

**How to reproduce**
```
create table test on cluster '{cluster}' (key UInt32, value1 String, value2 String, value3 String) engine=ReplicatedMergeTree('/test', '{replica}') order by key partition by (key % 4) settings storage_policy='object_storage'

insert into test select * from generateRandom('key UInt32, value1 String, value2 String, value3 String') limit 1000000

alter table test add column valueX String materialized value1

alter table test materialize column valueX
```

ClickHouse server version: 22.3.6.5 

**Expected behavior**

> After mutation, ClickHouse will remove all remote files of old original part if that doesn't hardlink to new part.

**Error message and/or stacktrace**

> ClickHouse does not remove remote file of uuid.txt from old original part.

**Comment by alexey-milovidov** [comment]
Zero-copy replication is a feature under development and it is not ready for production usage.
