### ISSUE TITLE
[JIT] Will Clickhouse support overflow check?

### ISSUE THREAD

**Issue by sherrytonger** [ClickHouse/ClickHouse#40190]
I deduce Clickhouse doesn't support overflow check and throw an exception from below picture. Will it be supported in the future or the developers think it's unnecessary for jit?

<img width="911" alt="图片" src="https://user-images.githubusercontent.com/2483534/184495881-ab29893e-3ab3-40b9-afd7-202174e31dd6.png">

**Comment by alexey-milovidov** [comment]
We don't have an overflow check for regular integer types even without JIT.
Most likely it will not be added, at least by default.

**Comment by alexey-milovidov** [comment]
Although there is a chance it can be added as a special switch for the mission-critical enterprise business applications.
