### ISSUE TITLE
More metrics for on-disk temporary data

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#40206]
**Use case**

Track the amount of space used for temporary data.

**Describe the solution you'd like**

We already have the following ProfileEvents:

`ExternalSortWritePart`
`ExternalSortMerge`
`ExternalAggregationWritePart`
`ExternalAggregationMerge`
`ExternalAggregationCompressedBytes`
`ExternalAggregationUncompressedBytes`

But there is no information about CompressedBytes and UncompressedBytes for external sort.
And there is no information about external JOIN at all.

Let's add it.
Let's also add ProfileEvents for the values (num files, compressed bytes, uncompressed bytes) of all operations in total.

Let's also add `CurrentMetrics` for the number of currently used files, compressed bytes, and uncompressed bytes, for all of the three types of operations, and for all the operations in total.

**Comment by alexey-milovidov** [comment]
We also need to use MemoryTracker for this data and be able to set the limitations on per-query, per-user, and server level, with memory overcommit as well.

**Comment by vdimir** [comment]
> And there is no information about external JOIN at all.

How should we count the space used for `full_sorting_merge_join`? It uses SortingStep, so data should be treated as used for sort, is it ok, or it's better to mark it as for Join?
