### ISSUE TITLE
Function minus() always convert UInt64 to Int64

### ISSUE THREAD

**Issue by devcrafter** [ClickHouse/ClickHouse#40216]
**Describe the unexpected behaviour**
Function minus() always convert UInt64 to Int64

**How to reproduce**
<pre>
:) create table t_uint (a UInt64) Engine=MergeTree() order by a

CREATE TABLE t_uint
(
    `a` UInt64
)
ENGINE = MergeTree
ORDER BY a

Query id: a907e4ae-5907-4907-84d9-0498fc5e107b

Ok.

0 rows in set. Elapsed: 0.007 sec.

:) insert into t_uint values (0), (0xFFFFFFFFffffffff)

INSERT INTO t_uint FORMAT Values

Query id: 9a435f68-d0e3-4356-b11f-b6daeb855695

Ok.

2 rows in set. Elapsed: 0.002 sec.

:) select a from t_uint order by a

SELECT a
FROM t_uint
ORDER BY a ASC

Query id: 3fd7680b-cd4b-43a8-abee-aa972335721f

┌────────────────────a─┐
│                    0 │
│ 18446744073709551615 │
└──────────────────────┘

2 rows in set. Elapsed: 0.001 sec.

ip-10-2-4-167.eu-west-1.compute.internal :) select a, a-1 from t_uint order by a-1

SELECT
    a,
<b>    a - 1</b>
FROM t_uint
<b>ORDER BY a - 1 ASC</b>

Query id: 7f502b37-58de-4571-b2c3-25f2ea34a7a8

┌────────────────────a─┬─minus(a, 1)─┐
<b>│ 18446744073709551615 │          -2 │</b>
│                    0 │          -1 │
└──────────────────────┴─────────────┘

2 rows in set. Elapsed: 0.002 sec.
</pre>

**Expected behavior**
minus() should respect input type

**Comment by alexey-milovidov** [comment]
> Function minus() always convert UInt64 to Int64

We cannot convert to Int64 not always, because otherwise, the behavior will be inconsistent with constant and non-constant arguments. This behavior is documented.
