### ISSUE TITLE
 Cannot provide query execution status. The query's node /clickhouse/task_queue/ddl/query-0000000053

### ISSUE THREAD

**Issue by kiwimg** [ClickHouse/ClickHouse#40212]
clickhouse  version :22.6.3.35

`CREATE TABLE test.dc_sku_all on cluster 'ck_cluster'`

An error occurred while I was creating the Distributed table

`
0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xb8a20fa in /usr/bin/clickhouse
1. DB::DDLQueryStatusSource::generate() @ 0x1655bb92 in /usr/bin/clickhouse
2. DB::ISource::tryGenerate() @ 0x1718ffd5 in /usr/bin/clickhouse
3. DB::ISource::work() @ 0x1718fb66 in /usr/bin/clickhouse
4. DB::ExecutionThreadContext::executeTask() @ 0x171abefa in /usr/bin/clickhouse
5. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x171a0e1e in /usr/bin/clickhouse
6. DB::PipelineExecutor::executeImpl(unsigned long) @ 0x1719fe21 in /usr/bin/clickhouse
7. DB::PipelineExecutor::execute(unsigned long) @ 0x1719fbb8 in /usr/bin/clickhouse
8. DB::CompletedPipelineExecutor::execute() @ 0x1719e74b in /usr/bin/clickhouse
9. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::__1::shared_ptr<DB::Context>, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>, std::__1::optional<DB::FormatSettings> const&) @ 0x16566a98 in /usr/bin/clickhouse
10. DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::__1::optional<DB::CurrentThread::QueryScope>&) @ 0x16ef45c4 in /usr/bin/clickhouse
11. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x16ef8b04 in /usr/bin/clickhouse
12. DB::HTTPServerConnection::run() @ 0x1715d36d in /usr/bin/clickhouse
13. Poco::Net::TCPServerConnection::start() @ 0x19dbd2d3 in /usr/bin/clickhouse
14. Poco::Net::TCPServerDispatcher::run() @ 0x19dbe651 in /usr/bin/clickhouse
15. Poco::PooledThread::run() @ 0x19f6f91b in /usr/bin/clickhouse
16. Poco::ThreadImpl::runnableEntry(void*) @ 0x19f6d020 in /usr/bin/clickhouse
17. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
18. clone @ 0xfe8dd in /usr/lib64/libc-2.17.so

2022.08.14 16:19:49.001245 [ 16238 ] {34824d1d-63e9-4622-9d38-24fff8d60bbe} <Error> DynamicQueryHandler: Code: 341. DB::Exception: Cannot provide query execution status. The query's node /clickhouse/task_queue/ddl/query-0000000053 has been deleted by the cleaner since it was finished (or its lifetime is expired). (UNFINISHED), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xb8a20fa in /usr/bin/clickhouse
1. DB::DDLQueryStatusSource::generate() @ 0x1655bb92 in /usr/bin/clickhouse
2. DB::ISource::tryGenerate() @ 0x1718ffd5 in /usr/bin/clickhouse
3. DB::ISource::work() @ 0x1718fb66 in /usr/bin/clickhouse
4. DB::ExecutionThreadContext::executeTask() @ 0x171abefa in /usr/bin/clickhouse
5. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x171a0e1e in /usr/bin/clickhouse
6. DB::PipelineExecutor::executeImpl(unsigned long) @ 0x1719fe21 in /usr/bin/clickhouse
7. DB::PipelineExecutor::execute(unsigned long) @ 0x1719fbb8 in /usr/bin/clickhouse
8. DB::CompletedPipelineExecutor::execute() @ 0x1719e74b in /usr/bin/clickhouse
9. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::__1::shared_ptr<DB::Context>, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>, std::__1::optional<DB::FormatSettings> const&) @ 0x16566a98 in /usr/bin/clickhouse
10. DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::__1::optional<DB::CurrentThread::QueryScope>&) @ 0x16ef45c4 in /usr/bin/clickhouse
11. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x16ef8b04 in /usr/bin/clickhouse
12. DB::HTTPServerConnection::run() @ 0x1715d36d in /usr/bin/clickhouse
13. Poco::Net::TCPServerConnection::start() @ 0x19dbd2d3 in /usr/bin/clickhouse
14. Poco::Net::TCPServerDispatcher::run() @ 0x19dbe651 in /usr/bin/clickhouse
15. Poco::PooledThread::run() @ 0x19f6f91b in /usr/bin/clickhouse
16. Poco::ThreadImpl::runnableEntry(void*) @ 0x19f6d020 in /usr/bin/clickhouse
17. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
18. clone @ 0xfe8dd in /usr/lib64/libc-2.17.so
 (version 22.6.3.35 (official build))

`

**Comment by e-mars** [comment]
hi @kiwimg ,

is this the full CREATE TABLE statement? was any engine specified?
any parameters?

when the error was received, had there been tests previously; such as running the create command, dropping the table and re-running it?

could you try with using `{uuid}` in the path parameter for zookeeper?

thanks.

**Comment by kiwimg** [comment]
> hi @kiwimg ,
> 
> is this the full CREATE TABLE statement? was any engine specified? any parameters?
> 
> when the error was received, had there been tests previously; such as running the create command, dropping the table and re-running it?
> 
> could you try with using `{uuid}` in the path parameter for zookeeper?
> 
> thanks.

 I use Clickhouse keeper

The creation statement is correct. I just explained the effect of the cluster，
Before creation, I executed the delete command,

now, I restart Clickhouse and it will return to normal

**Comment by tavplubix** [comment]
Please share relevant part of logs from all hosts of the cluster:
```
zgrep -Fa "DDLWorker" /var/log/clickhouse-server/* | grep -a "clean|delete|remove"
```

Have you changed `distributed_ddl.task_max_lifetime`, `distributed_ddl.cleanup_delay_period` and `distributed_ddl.max_tasks_in_queue` configuration parameters?

**Comment by tavplubix** [comment]
Similar issues: https://github.com/ClickHouse/ClickHouse/issues/35506, https://github.com/ClickHouse/ClickHouse/issues/19027, https://github.com/ClickHouse/ClickHouse/issues/18247
