### ISSUE TITLE
Is it necessary to add "on cluster xxx" when Execute "optimize table tbA final" for ReplicatedCollapsingMergeTree table?

### ISSUE THREAD

**Issue by taotaizhu-pw** [ClickHouse/ClickHouse#40213]
Is it necessary to add "on cluster clusterA" when Execute "optimize table tableA final" for ReplicatedCollapsingMergeTree table?

The following steps are right logic?

1. execute "optimize table tableA final"
2. execute "system SYNC REPLICA tableA" to check whether  all the data was merged

what is the best logic to check the table data were merged? Thanks!

**Comment by den-crane** [comment]
There is Replication and there is sharding.

`optimize table` is replicatable command, so if you run it at one replica it will initiate a merge and all other replicas of the current shard will execute this merge, so you need to run `optimize table` only once per shard.

`on cluster clusterA` allows to run `optimize` at all shards of clusterA. 
`on cluster` is smart enough to run it only at one replica in each shard.

`system SYNC REPLICA tableA` waits for all current replication tasks to finish.

>what is the best logic to check the table data were merged? 

Probably the best you can do is to run "system SYNC REPLICA tableA", then "optimize table tableA final".
