### ISSUE TITLE
The execution time is different by the two ways to connect to Clickhouse playground

### ISSUE THREAD

**Issue by Lloyd-Pottiger** [ClickHouse/ClickHouse#40223]
https://ghe.clickhouse.tech/#clickhouse-demo-access
I use the two ways to connect the Clickhouse playground. But the execution time of WebUI is much smaller than Clickhouse client.
![](https://user-images.githubusercontent.com/60744015/184308627-0930fdab-ce2e-45c0-92ae-b26d999a83d9.png)

I have tried different SQLs, and the execution time of WebUI is always much smaller than Clickhouse client. Is the two ways connect to the same cluster?

**Comment by alexey-milovidov** [comment]
clickhouse-client is displaying the time needed to send and receive data over network, not the server-side metric.
It will be changed since version 22.8 in https://github.com/ClickHouse/ClickHouse/issues/38070.

**Comment by Lloyd-Pottiger** [comment]
<img width="394" alt="image" src="https://user-images.githubusercontent.com/60744015/184572736-181d2a8c-3168-401d-a9f7-1d39fe00a1d6.png">
 the version of clickhouse-client I used is 22.8.1.1543.
