### ISSUE TITLE
Is there any way to know how many parts a query reads?

### ISSUE THREAD

**Issue by chenlx0** [ClickHouse/ClickHouse#40221]
Hi, guys, I am now doing some simple research on ClickHouse merge tree merge policy. And I want to know how many parts a query read. But it seems that `system.query_log` does not provide such a column. Is there any way to know how many parts a query reads?

If not, can we add a `read_parts` column to `system.query_log` table? I think this metric is useful if we want to evaluate our merge policy.

Thanks!

**Comment by alexey-milovidov** [comment]
There is the `ProfileEvents` map, and you can access the needed metric by `ProfileEvents['SelectedParts']`.
