### ISSUE TITLE
Wrong error message from table function `remote`

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#40220]
**Use case**

```
clickhouse-cloud :) INSERT INTO github_events SELECT * FROM remoteSecure('test', default.github_events, import_from_cloud, 'xyz')

INSERT INTO github_events SELECT *
FROM remoteSecure('test', default.github_events, import_from_cloud, 'xyz')

Query id: 0aec7802-2980-4eed-8c5f-fac04b290acf


0 rows in set. Elapsed: 0.042 sec. 

Received exception from server (version 22.7.1):
Code: 42. DB::Exception: Received from host.aws.clickhouse.cloud:9440. DB::Exception: Table function 'remote' requires from 2 to 6 parameters: <addresses pattern or cluster name>, <name of remote database>, <name of remote table> [, username[, password], sharding_key]. (NUMBER_OF_ARGUMENTS_DOESNT_MATCH)

clickhouse-cloud :) INSERT INTO github_events SELECT * FROM remoteSecure('test', default, github_events, import_from_cloud, 'xyz')

INSERT INTO github_events SELECT *
FROM remoteSecure('test', default, github_events, import_from_cloud, 'xyz')

Query id: 04afbe19-df67-42af-9271-08470fb7dd04


0 rows in set. Elapsed: 0.042 sec. 

Received exception from server (version 22.7.1):
Code: 42. DB::Exception: Received from host.aws.clickhouse.cloud:9440. DB::Exception: Table function 'remote' requires from 2 to 6 parameters: <addresses pattern or cluster name>, <name of remote database>, <name of remote table> [, username[, password], sharding_key]. (NUMBER_OF_ARGUMENTS_DOESNT_MATCH)

clickhouse-cloud :) INSERT INTO github_events SELECT * FROM remoteSecure('test', default, github_events, 'import_from_cloud', 'xyz')
```

This happens when the username is not quoted.

**Comment by kuriousengineer** [comment]
As per the argument parsing code, if `username` is not valid string literal then default value "default" is used. So to fix this error message, there are two options:
1)- Don't use the default value of invalid `username` is provided and throw exception about it.
2)- Continue parsing (and not give existing false error message) to communicate with given remote server and let is fail.

I think (1) seems logical to me but I would like to understand why we use default value even if invalid username argument is provided.

**Comment by abhaagar** [comment]
@alexey-milovidov please provide your input.

**Comment by alexey-milovidov** [comment]
@abhaagar 

There are the following problems we want to fix:

1. When I type `remoteSecure('test', default.github_events, import_from_cloud, 'xyz')`
It is saying that I have to pass `from 2 to 6` parameters.
But it is incorrect because I have passed 4 parameters that fall into the range "from 2 to 6".

2. I'm allowed to pass the database and table name unquoted (as an identifier), so I expect that I will be allowed to also pass the user name as an identifier (without quotes). Most likely allowing it will also fix №1.

> if username is not valid string literal then default value "default" is used.

This looks incorrect. The default value should be used only if the user name is omitted.

**Comment by Neyromancer** [comment]
Hey, I will try to address this issue, if you don't mind. looks interesting to me.

**Comment by alexey-milovidov** [comment]
@Neyromancer thanks, let's try!
