### ISSUE TITLE
sequenceMatch returns inconsistent results with vs. without max_bytes_before_external_group_by

### ISSUE THREAD

**Issue by nhoeft** [ClickHouse/ClickHouse#40231]
Hey, I ran into some unexpected behaviour of `sequenceMatch` in conjunction with `max_bytes_before_external_group_by`.

**Describe the unexpected behaviour**
`sequenceMatch` returns only zeros when `max_bytes_before_external_group_by` is reached by a query. 

**How to reproduce**
Using clickhouse 22.6.3.35

Here is a minimal example that can be used to reproduce:

```
-- no value set for max_bytes_before_external_group_by
with mock_data as (
select my_key, addSeconds('2022-08-10':: timestamp, sequence) as sequence, event
from generateRandom('my_key Nullable(Enum(\'key1\' = 1, \'key2\' = 2, \'key3\' = 3)), sequence UInt16, event Enum(\'event1\' = 1, \'event2\' = 2)', 1, 5, 42)
limit 5000000)
select my_key, sequenceMatch('(?1).*(?2)')(sequence, event = 'event1', event = 'event2') as seqs1
from mock_data
group by my_key;

-- max_bytes_before_external_group_by is reached
with mock_data as (
select my_key, addSeconds('2022-08-10':: timestamp, sequence) as sequence, event
from generateRandom('my_key Nullable(Enum(\'key1\' = 1, \'key2\' = 2, \'key3\' = 3)), sequence UInt16, event Enum(\'event1\' = 1, \'event2\' = 2)', 1, 5, 42)
limit 5000000)
select my_key, sequenceMatch('(?1).*(?2)')(sequence, event = 'event1', event = 'event2') as seqs1
from mock_data
group by my_key
settings max_bytes_before_external_group_by=1000;

-- max_bytes_before_external_group_by is not reached
with mock_data as (
select my_key, addSeconds('2022-08-10':: timestamp, sequence) as sequence, event
from generateRandom('my_key Nullable(Enum(\'key1\' = 1, \'key2\' = 2, \'key3\' = 3)), sequence UInt16, event Enum(\'event1\' = 1, \'event2\' = 2)', 1, 5, 42)
limit 5000000)
select my_key, sequenceMatch('(?1).*(?2)')(sequence, event = 'event1', event = 'event2') as seqs1
from mock_data
group by my_key
settings max_bytes_before_external_group_by=10000000000;
```

**Expected behavior**
I would expect the results from all queries to be identical.

**Additional context**
The problem was first observed after upgrading clickhouse from 21.8.8.29 to 22.6.3.35.
In this specific example the problem can be fixed by removing the `Nullable()` for `my_key`. However, in my original data, the problem still persists even when re-creating the table with only non-nullable columns.

**Comment by WesleyBatista** [comment]
One can confirm that queries were indeed returning the same results on 21.8.8.29 with these commands:
```
docker run --name ch-21.8.8.29 --rm clickhouse/clickhouse-server:21.8.8.29 clickhouse-server   # terminal 1
docker exec -it ch-21.8.8.29 clickhouse-client -mn   # terminal 2
# <paste queries on terminal 2>
```

...but not when we use 22.6.3.35.

**Comment by nhoeft** [comment]
The issue first occurs in [21.10](https://clickhouse.com/docs/en/whats-new/changelog/2021#clickhouse-release-v2110-2021-10-16). The only explicit reference to `sequenceMatch` in the release notes is https://github.com/ClickHouse/ClickHouse/pull/27729.

**Comment by filimonov** [comment]
Related / duplicate: https://github.com/ClickHouse/ClickHouse/issues/37296

**Comment by filimonov** [comment]
Also: https://github.com/ClickHouse/ClickHouse/issues/32290
