### ISSUE TITLE
Allow to modify constrained settings in readonly mode.

### ISSUE THREAD

**Issue by KochetovNicolai** [ClickHouse/ClickHouse#40244]
It may be useful to allow modifying specified set of setting for readonly user.
[Example](https://play.clickhouse.com/play?user=play#c2VsZWN0IDEgc2V0dGluZ3MgZXh0cmVtZXMgPSAxOw==).

Now, we can specify [constraints](https://clickhouse.com/docs/en/operations/settings/constraints-on-settings/) for settings. However, readonly user can't change it:
```
users.xml:
    <profiles>
        <readonly>
            <readonly>1</readonly>
            <constraints>
                <max_threads>
                   <min>3</min>
                   <max>16</max>
                </max_threads>
            </constraints>
        </readonly>
    </profiles>

$ clickhouse client --user readonly --max_threads=4 -q 'select 1'
Received exception from server (version 22.8.1):
Code: 164. DB::Exception: Received from localhost:9000. DB::Exception: Cannot modify 'max_threads' setting in readonly mode. (READONLY)
```

We can just allow to change only specified settings for readonly user.
Probably, add compatibility setting/tag.

**Comment by alexey-milovidov** [comment]
We can come up with just a different name instead of `constraints`.
What is the opposite term? `allowances`?

**Comment by alexey-milovidov** [comment]
```
<profiles>
        <readonly>
            <readonly>1</readonly>
            <allowances>
                <max_threads>
                   <min>3</min>
                   <max>16</max>
                </max_threads>
            </allowances>
        </readonly>
    </profiles>
```

**Comment by devcrafter** [comment]
> We can come up with just a different name instead of `constraints`. What is the opposite term? `allowances`?

`except`, `exclude` - "settings are readonly except ..."

**Comment by alexey-milovidov** [comment]
@devcrafter The `readonly` can be set somewhere far away, in another inherited user profile, that's why naming the exceptions `exclude` would not give a clue.

**Comment by alexey-milovidov** [comment]
Let's name it `<allow>`.

It will work in the same way as constraints but will override previous constraints by allowing to change settings in this range.
If there is no "readonly" or inherited constraints, then there is no difference between `<constraints>` and `<allow>`.

**Comment by serxa** [comment]
While implementing I've found that `<constraints>` and `<allow>` are really tightly bound together. For example allowed range must be inside constrained range. Also in the simplest possible implementation that I came up with, they appear in the same structures, for example:
```
    struct Constraint
    {
        std::shared_ptr<const String> setting_name;
        bool read_only = false;
        Field min_value;
        Field max_value;
        Field min_value_in_readonly;
        Field max_value_in_readonly;
    };
```
Maybe we should use syntax that is more natural to describe this relationship, but putting things together inside the same xml element:
```
    <profiles>
        <readonly>
            <readonly>1</readonly>
            <constraints>
                <max_threads>
                   <min>3</min>
                   <max>16</max>
                   <max_in_readonly>4</max_in_readonly>
                </max_threads>
            </allowances>
        </readonly>
    </profiles>
```
WDYT? @alexey-milovidov @KochetovNicolai

**Comment by serxa** [comment]
This will also be more natural for SQL workflow, that we even not discussed here yet

**Comment by serxa** [comment]
We discussed this issue with @vitlibar and came to conclusion that specifications proposed above are all lead to some confusing corner case. So here is what we propose:

1. If settings profile has a constraint for specific setting, then this constraint completely cancels all actions of previous constraint (defined in other profiles) for the same specific setting, including fields that are not set by new constraint. This greatly simplifies settings profile "inheritance" logic.

2. pt.1 is not backward incompatible, so new config option is introduced to enabled this:
```
<access_control_improvements>
    <settings_constraints_replace_previous>true<settings_constraints_replace_previous>
</access_control_improvements>
```

3. A setting constraint may contain `min` and `max` in any combinations. Absent value is default, meaning no constrain what so ever for this boundary.

4. A setting constraint may contain either `const` (it is new name for `<readonly/>` to avoid confusion with `readonly` setting) or `changeable_in_readonly` but not both. 

5. `const` may not be used with `min` or `max`.

**Comment by alexey-milovidov** [comment]
Looks good to me.
