### ISSUE TITLE
TPC-H Q3: Join order impacts query performance 10x in presence of projections

### ISSUE THREAD

**Issue by arunmarathe** [ClickHouse/ClickHouse#40245]
Do projections not work with S3 Backed MergeTrees?

I have the TPC-H Orders tables created as S3 Backed MergeTree.

```
arunm-testvm :)         show create table orders;

SHOW CREATE TABLE orders

Query id: 1d7aff22-24a7-4d5b-ad2a-1836b470bc12

┌─statement──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ CREATE TABLE tpch_10g_parquet_s3.orders
(
    `o_orderkey` UInt64,
    `o_custkey` UInt64,
    `o_orderstatus` FixedString(1),
    `o_totalprice` Float64,
    `o_orderdate` Date,
    `o_orderpriority` FixedString(15),
    `o_clerk` FixedString(15),
    `o_shippriority` UInt32,
    `o_comment` String,
    PROJECTION o_1
    (
        SELECT *
        ORDER BY o_orderdate
    )
)
ENGINE = MergeTree
PRIMARY KEY o_orderkey
ORDER BY o_orderkey
SETTINGS index_granularity = 8192, storage_policy = 's3_main' │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

Projection o_1 has been defined as above.

This projection should help with the following TPC-H Query 3.

```
select
        l_orderkey,
        sum(l_extendedprice * (1 - l_discount)) as revenue,
        o_orderdate,
        o_shippriority
from
        customer,
        orders,
        lineitem
where
        c_mktsegment = 'BUILDING'
        and c_custkey = o_custkey
        and l_orderkey = o_orderkey
        and o_orderdate < date '1995-03-22'
        and l_shipdate > date '1995-03-22'
group by
        l_orderkey,
        o_orderdate,
        o_shippriority
order by
        revenue desc,
        o_orderdate
limit 10;
```

Notice that there is a nice filtering condition available on `o_orderdate`, but the query execution does not pick up the `o_1` projection.

Second question:
Create projection (alter table create projection ...) command returns immediately, but from the server log, I can see that the actual projection creation continues for several minutes after the creation command returns. Is that expected? I don't see a huge problem with this behavior, but immediately returning the cli prompt back is misleading because work has not been done yet.

**Comment by arunmarathe** [comment]
> Do you use Zero copy replication?
> 
> #38322

I didn't explicitly set up zero-copy replication, but how can I tell?

**Comment by den-crane** [comment]
> > Do you use Zero copy replication?
> > #38322
> 
> I didn't explicitly set up zero-copy replication, but how can I tell?

it's enabled by default, and it works if you use the same S3 path/bucket for all replicas.
You need to disable  Zero copy replication

```xml
cat /etc/clickhouse-server/config.d/mts.xml
<?xml version="1.0"?>
<clickhouse>
  <merge_tree>
      <allow_remote_fs_zero_copy_replication>0</allow_remote_fs_zero_copy_replication>
  </merge_tree>
</clickhouse>
```

**Comment by arunmarathe** [comment]
> ```
> allow_remote_fs_zero_copy_replication
> ```

Thanks. I don't have such a section in a config file.

The query can use projections, by the way. The problem was this: The `system.query_log` table has a `projections` columns, and that was showing `[]` indicating that no projection was used. But querying the `system.query_log` again and again, projections did appear in that empty array. So looks like `system.query_log` needs some catching up to do. This is ok; not a big problem.

I did find another issue though.

Notice that the query Q3 above joins three tables in this order: `customer, orders, lineitem`. It runs in about 35-40 sec using two projections.

If I reverse the order to `lineitem, orders, customer`, it runs in 3.4 sec or x10 faster. (Everything else is the same.)

Why is that? This seems rather undesirable. Is there a setting to "fix" it?

**Comment by den-crane** [comment]
>But querying the system.query_log again and again, projections did appear in that empty array. So looks like system.query_log needs some catching up to do. This is ok; not a big problem.

emm, can you show an example ? 
Do you mean query_log type =1 , type =2 ?
`select * from system.query_log where query_id = .... format Vertical`

**Comment by den-crane** [comment]
>Thanks. I don't have such a section in a config file.

It's `allow_remote_fs_zero_copy_replication=1` by default.

**Comment by den-crane** [comment]
>If I reverse the order to lineitem, orders, customer, it runs in 3.4 sec or x10 faster. (Everything else is the same.)
>Why is that? This seems rather undesirable. Is there a setting to "fix" it?

That is expected. Clickhouse does not have an optimization which changes the order of access to joined tables.

**Comment by arunmarathe** [comment]
> > But querying the system.query_log again and again, projections did appear in that empty array. So looks like system.query_log needs some catching up to do. This is ok; not a big problem.
> 
> emm, can you show an example ? Do you mean query_log type =1 , type =2 ? `select * from system.query_log where query_id = .... format Vertical`




```
arunm-testvm :) select qselect query, projections from system.query_log;
```

First time, it shows:

```
┌─query────────────────────────────┬─projections─┐
│ truncate table system.query_log; │ []          │
│ truncate table system.query_log; │ []          │
└──────────────────────────────────┴─────────────┘
```

Second time, it shows:

```
┌─query──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─projections────────────────────────┐
│ select l_orderkey, sum(l_extendedprice * (1 - l_discount)) as revenue, o_orderdate, o_shippriority from lineitem, orders, tpch_10g_parquet.customer where c_mktsegment = 'BUILDING' and c_custkey = o_custkey and l_orderkey = o_orderkey and o_orderdate < date '1995-01-15' and l_shipdate > date '1995-01-15' group by l_orderkey, o_orderdate, o_shippriority order by revenue desc, o_orderdate limit 10; │ ['tpch_10g_parquet_s3.orders.o_1'] │
│ select l_orderkey, sum(l_extendedprice * (1 - l_discount)) as revenue, o_orderdate, o_shippriority from lineitem, orders, tpch_10g_parquet.customer where c_mktsegment = 'BUILDING' and c_custkey = o_custkey and l_orderkey = o_orderkey and o_orderdate < date '1995-01-15' and l_shipdate > date '1995-01-15' group by l_orderkey, o_orderdate, o_shippriority order by revenue desc, o_orderdate limit 10; │ ['tpch_10g_parquet_s3.orders.o_1'] │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────────────────────┘
```

**Comment by arunmarathe** [comment]
> > Thanks. I don't have such a section in a config file.
> 
> It's `allow_remote_fs_zero_copy_replication=1` by default.

Thanks. I explicit set `allow_remote_fs_zero_copy_replication=0` in `config.xml`. Create partition command still returned instantaneously.

**Comment by den-crane** [comment]
`system.query_log` buffer is flushed every 7.5 seconds.

```
/etc/clickhouse-server/config.xml

   <query_log>
....
        <database>system</database>
        <table>query_log</table>
...

        <!-- Interval of flushing data. -->
        <flush_interval_milliseconds>7500</flush_interval_milliseconds>
    </query_log>
```
