### ISSUE TITLE
Roskomnadzon blocked access to ClickHouse sites and services

### ISSUE THREAD

**Issue by ilya-vv** [ClickHouse/ClickHouse#40252]
It seems that Russian State Agency Roscomnadzor blocked access to IP range which includes ClickHouse services.

Example:
```
> ipconfig /flushdns
Windows IP Configuration
Successfully flushed the DNS Resolver Cache.

> nslookup clickhouse.com 8.8.8.8
Server:  dns.google
Address:  8.8.8.8

Non-authoritative answer:
Name:    clickhouse.com
Addresses:  2a06:98c1:3122:a000::b
          2a06:98c1:3123:a000::b
          188.114.98.171
          188.114.99.171

> telnet 188.114.98.171 443
Connecting To 188.114.98.171...Could not open connection to the host, on port 443: Connect failed
```

Checking blocked resources at [https://blocklist.rkn.gov.ru/](https://blocklist.rkn.gov.ru/) returns several documents according the mentioned IP addresses.

Affected services:
- https://clickhouse.com - documentation
- https://repo.clickhouse.com - repository to install and upgrade software

With enabled VPN everything work fine.

Sincerely,
Ilya

**Comment by alexey-milovidov** [comment]
ClickHouse website and package repository are using Cloudflare CDN.
If Cloudflare CDN is banned, there's not much we can do about it.

I recommend continuing to use VPN.
