### ISSUE TITLE
Allow to delete by a object('json') column

### ISSUE THREAD

**Issue by DenisGee** [ClickHouse/ClickHouse#40255]
👋  Hello, there is a problem with deleting by a json column =)
Deleting by a object('json') column produces an infinite loop of deletion attempts
an example:

```
set allow_experimental_object_type = 1;

CREATE TABLE test.dropJSON
(
	i Int8,
	jsonMesage JSON
) ENGINE = MergeTree
order by i;

insert into test.dropJSON
select 1, '{"a":1, "b":"aaa"}';

alter table test.dropJSON delete where jsonMesage.a = 1;
```
So in system.mutations i see that is_done = 0, latest_fail_time always updating, latest_fail_reason is "Code: 47. DB::Exception: Missing columns: 'jsonMesage.a' while processing query: 'SELECT count() WHERE jsonMesage.a = 1', required columns: 'jsonMesage.a', maybe you meant: ['jsonMesage']. (UNKNOWN_IDENTIFIER) (version 22.7.1.2484 (official build))"
and when i started the deleting i got high CPU utilization
![image](https://user-images.githubusercontent.com/110493658/184818809-e1be9d91-c567-4b85-b28d-0a4d2860c7d8.png)

**Comment by bgrgndzz** [comment]
Just ran into this issue as well. Hacked a solution together by replicating needed data, deleting everything by a non-json key, and then re-inserting replicated data. Huge pain in the ass.

**Comment by alexey-milovidov** [comment]
Object('json') is not supported.
