### ISSUE TITLE
Has Clickhouse considered GPU-accelerated aggregation recently?

### ISSUE THREAD

**Issue by mjshare** [ClickHouse/ClickHouse#40258]
> Make sure to check documentation https://clickhouse.com/docs/en/ first. If the question is concise and probably has a short answer, asking it in Telegram chat https://telegram.me/clickhouse_en is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

> If you still prefer GitHub issues, remove all this text and ask your question here.

**Comment by alexey-milovidov** [comment]
ClickHouse team cooperated with Nvidia to conduct an experiment with implementing GPU accelerated aggregation.
Here is the prototype: https://github.com/ClickHouse/ClickHouse/pull/37307
It gives moderately good results, although the perspective of production usage is still in question.
