### ISSUE TITLE
Materialized View misses some data

### ISSUE THREAD

**Issue by wawanawna** [ClickHouse/ClickHouse#4026]
Hello. First of all thx for a great product. Very fast and flexible.

Recently we started using MaterializedView and noticed one issue (or not an issue but we did something wrong)

We created MVs based on local Metrics tables (they use ReplicatedMergeTree() engine and we constantly writes to those local tables (each second)) like:

```
CREATE MATERIALIZED VIEW default.MetricStats ON CLUSTER metrics 
ENGINE = ReplicatedAggregatingMergeTree('/clickhouse/tables/metrics/{shard}/MetricStats', '{replica}')
PARTITION BY floor(time / 86400)
ORDER BY (time, appId) POPULATE AS
SELECT 
    uniqExactState(host) AS `os.host`, 
    uniqExactState(container) AS `container.id`, 
    uniqExactState(containerHostname) AS `container.host.hostname`, 
    appId, 
    floor(timestamp / 60) * 60 AS time
FROM default.Metrics 
WHERE timestamp > now()-300
GROUP BY 
    time, 
    appId
```

Then we created distributed table based on MVs

```
CREATE TABLE IF NOT EXISTS  default.MetricStatsDistributed ON CLUSTER metrics AS default.MetricStats
ENGINE = Distributed(metrics, default, MetricStats, rand());
```

After all we select data from Distributed table (which based on MVs)

```
SELECT 
    uniqExactMerge(`os.host`) AS `os.host`, 
    uniqExactMerge(`container.id`) AS `container.id`, 
    uniqExactMerge(`container.host.hostname`) AS `container.host.hostname`, 
    appId, 
    time
FROM MetricStatsDistributed 
WHERE appId = XXX
GROUP BY 
    appId, 
    time
ORDER BY time ASC
```
And got following
```
┌─os.host─┬─container.id─┬─container.host.hostname─┬─appId─┬──────────time─┐
│      35 │          486 │                       1 │ XXX   │ 1546932480000 │
│      35 │          486 │                       1 │ XXX   │ 1546932540000 │
│      35 │          486 │                       1 │ XXX   │ 1546932600000 │
│      35 │          486 │                       1 │ XXX   │ 1546932660000 │
│      35 │          486 │                       1 │ XXX   │ 1546932720000 │
│      35 │          480 │                       1 │ XXX   │ 1546932780000 │ >>> at that time we created MVs
│      29 │          287 │                       1 │ XXX   │ 1546932840000 │
│      27 │          376 │                       1 │ XXX   │ 1546932900000 │
│      27 │          330 │                       1 │ XXX   │ 1546932960000 │
│      21 │          309 │                       1 │ XXX   │ 1546933020000 │
└─────────┴──────────────┴─────────────────────────┴───────┴───────────────┘
```

35 are right values. 29, 27, 21 values are wrong and it means that we missed some unique values. 
As you can see we see wrong values only after MVs were created, so during POPULATE we agg data right, But then during realtime insertion/aggregating we started to see issue.

We have a feeling that maybe not everything was added to MVs and aggregated with `uniqExactState`, or maybe aggregation into MVs triggers only once for (time, appId) pair (order key) and it something was added to "main" table later will be missed?

Thx for future answer&investigation.

**Comment by wawanawna** [comment]
Yes, we know, this is not a case here. We insert only last minute data usually
I even tried 

> WHERE timestamp > now()-1800

No effect, so cause is somewhere else

**Comment by filimonov** [comment]
> No effect, so cause is somewhere else

Just to be sure - can you try to remove that condition? Anyway you "insert only last minute data". 

Why: maybe now() is beeing calculated once - at the moment of MV initialization?

**Comment by den-crane** [comment]
Try to calculate MV countState or sum(1) to locate the issue (missing rows or uniqExact)

**Comment by wawanawna** [comment]
> > No effect, so cause is somewhere else
> 
> Just to be sure - can you try to remove that condition? Anyway you "insert only last minute data".
> 
> Why: maybe now() is beeing calculated once - at the moment of MV initialization?

Hello, thx for suggestion, I've tried create MV without any conditions, didn't help neither

**Comment by filimonov** [comment]
@wawanawna Did you find the reason?

**Comment by wawanawna** [comment]
No, we didn't find a reason @filimonov 
We stopped using MV, found workaround.

**Comment by nupursinghbaghel** [comment]
Hi @wawanawna, 
What is the workaround you found ?

**Comment by den-crane** [comment]
@nupursinghbaghel it could be https://github.com/yandex/ClickHouse/issues/5274
Then workaround is to add some column to MV to break de-duplication
as select  , now() as workaround -- or generateUUIDv4()
and collapse it using any

**Comment by wawanawna** [comment]
> Hi @wawanawna,
> What is the workaround you found ?

We just stopped using MVs @nupursinghbaghel

**Comment by nezed** [comment]
We using MV that selecs data from replicated table:
```sql
CREATE TABLE db.`replicated_table` (…) ENGINE = ReplicatedMergeTree(…, '{replica}') ORDER BY (…) PARTITION BY … SAMPLE BY CAST(…);
```
Table is replicated across 3 machines, only 1 machine handles `INSERT` queries.

We've created MV on "slave" replica, and a lot of documents are missing on it.
```sql
CREATE MATERIALIZED VIEW db2.`mv` ENGINE = MergeTree() ORDER BY (…) PARTITION BY … POPULATE AS SELECT … FROM db.`replicated_table`;
```
or same behaviour with `ENGINE=ReplicatedMergeTree`
```sql
CREATE MATERIALIZED VIEW db2.`mv` ENGINE = ReplicatedMergeTree(…, '{replica}') ORDER BY (…) PARTITION BY … POPULATE AS SELECT … FROM db.`replicated_table`;
```

Fixed by creating MV with `ENGINE=ReplicatedMergeTree` on each insertable replica. Now all works fine.

**Comment by blinkov** [comment]
@wawanawna, do you have any further questions?

**Comment by blinkov** [comment]
Feel free to re-open the issue if it is still relevant.

**Comment by brunorpinho** [comment]
Hi @den-crane,

I have a table `MergeTree` with two columns: one experimental `Object('json')` and one `timestamp` column. I am then creating a MV out of that table with a simple select of one of the json fields `json.key1`  and the timestamp. For some reason, the MV does not update on any inserts on that initial table. 

Is this a limitation? Can I make this work?

**Comment by den-crane** [comment]
There is no repro, there is no ideas what is the reason of inconsistency. Closing.
