### ISSUE TITLE
Many queries at once degrades all queries

### ISSUE THREAD

**Issue by tasdflkjweio** [ClickHouse/ClickHouse#40279]
I'm testing out the boundaries of our ClickHouse db, so I put together a query runner where I can bombard it with queries. The test runner sends up to `x` of the same query in parallel with `y` ms sleep between them. I notice that queries, when run one-at-a-time, behave well. However, the same query under moderate load begins to struggle in a disproportionate manner. For example:

- A single execution of the query will resolve in 500 ms
- 10 parallel executions (delayed 75ms between query) of that same query will resolve in 5,000 ms _for all queries_
- 20 parallel executions (delayed 75ms between query) of that same query will resolve in 10,000 ms _for all queries_

That is to say that none of the queries resolve in 500ms. Instead, they are all degrading together as a group. I'm assuming that ClickHouse is just greedily trying to execute all queries at once which creates contention and performance takes a hit across the board. It seems to behave like this on 3 separate versions - one from 2018, one from 2020, and a current version, so I don't think it's version-specific.

I was expecting that there may be a priority to finish the first query first. OR recognize that a query is already in flight/pending so any duplicate queries would be resolved by that first query's response. Our system is almost entirely read-heavy. Data is ingested just once per week, and it comes in a pre-aggregated format. It seems like there are no optimizations in place to avoid hitting the disk and having queries fight each other for resources. Is this the expected behavior?

**Comment by den-crane** [comment]
@tasdflkjweio https://github.com/ContentSquare/chproxy solves it
