### ISSUE TITLE
clickhouse client non interactive mode does not spit the query id

### ISSUE THREAD

**Issue by kalpesh6641** [ClickHouse/ClickHouse#40271]
**Description**:

As per the documentation when we run the click house client in non interactive mode for example `clickhouse client --query "some query"` it does not spit the query id.

**Question**:

So is there any provision we will be enabling the click house client non interactive mode to spit the query id. Since the query id is more helpful in order to identify errors/troubleshooting purpose or query performance side of the work.

**Comment by alexey-milovidov** [comment]
No, query_id is only printed in the interactive mode.
