### ISSUE TITLE
Insert from JSONEachRow doesnt cast number as string

### ISSUE THREAD

**Issue by mikeTWC1984** [ClickHouse/ClickHouse#40288]
Insert into table will fail for JSONEachRow if destination column type is string but JSON value is number. It works if you insert from values.

```SQL
create table test (id String, val String) Engine=MergeTree Order by id

-- this works
insert into test values ('123', 'from values as string')
insert into test values (123, 'from values as int')
```

```bash
# this works too
echo '{"id":"123", "val":"fron json as string"}' | clickhouse-client --query 'INSERT INTO test FORMAT JSONEachRow'

#this DOESN'T work 
echo '{"id":123, "val":"from json as int"}' | clickhouse-client --query 'INSERT INTO test FORMAT JSONEachRow'
```
Error:
Code: 26. DB::ParsingException: Cannot parse JSON string: expected opening quote: (while reading the value of key id):

**Comment by DerekChia** [comment]
@mikeTWC1984 I tried inserting different data types against tables with different column types. Indeed, there is a difference when inserting as VALUES or JSONEachRow. 

Some observations:
- For column of String type, JSONEachRow is not able to parse value that is non-String
- For column of Int type, JSONEachRow is not able to parse value of Float type

|                                     | `CREATE TABLE table_int (id UInt32, val String) Engine=MergeTree ORDER BY id`                                                                                                                                                                                                                                                                                                                                                                                                     | `CREATE TABLE table_string (id String, val String) Engine=MergeTree ORDER BY id`                                                                                                                                                                                                                                                                                                                                                                                                          | `CREATE TABLE table_float (id Float32, val String) Engine=MergeTree ORDER BY id`                                                 |
| ----------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------ |
| VALUES: insert as string | `INSERT INTO table_int VALUES ('123', 'from values as string')`                                                                                                                                                                                                                                                                                                                                                                                                              | `INSERT INTO table_string VALUES ('123', 'from values as string')`                                                                                                                                                                                                                                                                                                                                                                                                                   | `INSERT INTO table_float VALUES ('123.1', 'from values as string')`                                                         |
| VALUES: insert as int    | `INSERT INTO table_int VALUES (123, 'from values as int')`                                                                                                                                                                                                                                                                                                                                                                                                                   | `INSERT INTO table_string VALUES (123, 'from values as int')`                                                                                                                                                                                                                                                                                                                                                                                                                        | `INSERT INTO table_float VALUES (123, 'from values as int')`                                                                |
| VALUES: insert as float  | `INSERT INTO table_int VALUES (123.1, 'from values as float')`                                                                                                                                                                                                                                                                                                                                                                                                               | `INSERT INTO table_string VALUES (123.1, 'from values as float')`                                                                                                                                                                                                                                                                                                                                                                                                                    | `INSERT INTO table_float VALUES (123.1, 'from values as float')`                                                            |
| VALUES: insert as bool   | `INSERT INTO table_int VALUES (true, 'from values as bool')`                                                                                                                                                                                                                                                                                                                                                                                                                 | `INSERT INTO table_string VALUES (true, 'from values as bool')`                                                                                                                                                                                                                                                                                                                                                                                                                      | `INSERT INTO table_float VALUES (true, 'from values as bool')`                                                              |
| JSONEachRow: insert as string              | `INSERT INTO table_int FORMAT JSONEachRow {"id":"123", "val":"from json as string"}`                                                                                                                                                                                                                                                                                                                                                       | `INSERT INTO table_string FORMAT JSONEachRow {"id":"123", "val":"from json as string"}`                                                                                                                                                                                                                                                                                                                                                            | `INSERT INTO table_float FORMAT JSONEachRow {"id":"123.1", "val":"from json as string"}`  |
| JSONEachRow: insert as int                 | `INSERT INTO table_int FORMAT JSONEachRow {"id":123, "val":"from json as string"}`                                                                                                                                                                                                                                                                                                                                 | `INSERT INTO table_string FORMAT JSONEachRow {"id":123, "val":"from json as int"}` <br /> <br /> Exception on client: Code: 26. DB::ParsingException: Cannot parse JSON string: expected opening quote: (while reading the value of key id): While executing ParallelParsingBlockInputFormat: data for INSERT was parsed from query: (at row 1).(CANNOT_PARSE_QUOTED_STRING)                                                                                                                  | `INSERT INTO table_float FORMAT JSONEachRow {"id":123, "val":"from json as int"}`        |
| JSONEachRow: insert as float               | `INSERT INTO table_int FORMAT JSONEachRow {"id":123.1, "val":"from json as float"}` <br /> <br />   Exception on client: Code: 27. DB::ParsingException: Cannot parse input: expected ',' before: '.1, "val":"from json as float"}': While executing ParallelParsingBlockInputFormat: data for INSERT was parsed from query: (at row 1). (CANNOT_PARSE_INPUT_ASSERTION_FAILED) | `INSERT INTO table_string FORMAT JSONEachRow {"id":123.1, "val":"from json as float"}`     <br /> <br /> Exception on client: Code: 26. DB::ParsingException: Cannot parse JSON string: expected opening quote: (while reading the value of key id): While executing ParallelParsingBlockInputFormat: data for INSERT was parsed from query: (at row 1). (CANNOT_PARSE_QUOTED_STRING) | `INSERT INTO table_float FORMAT JSONEachRow {"id":123.1, "val":"from json as float"}`     |
| JSONEachRow: insert as bool                | `INSERT INTO table_int FORMAT JSONEachRow {"id":true, "val":"from json as bool"}`                                                                                                                                                                                                                                                                                                                                                         | `INSERT INTO table_string FORMAT JSONEachRow {"id":true, "val":"from json as bool"}` <br /> <br /> Code: 26. DB::ParsingException: Cannot parse JSON string: expected opening quote: (while reading the value of key id): While executing ParallelParsingBlockInputFormat: data for INSERT was parsed from query: (at row 1). (CANNOT_PARSE_QUOTED_STRING)       | `INSERT INTO table_float FORMAT JSONEachRow {"id":true, "val":"from json as bool"}`       |

**Comment by DerekChia** [comment]
Got a reply from engineering stating that JSON* input formats (i.e. JSONEachRow, JSONStringsEachRow, etc.) do not perform automatic casting from numbers to strings. 

As for inserting using VALUES, it does automatic casting and there are [settings](https://clickhouse.com/docs/en/interfaces/formats/#values-format-settings) to control how the expressions are interpreted.

**Comment by DerekChia** [comment]
PR https://github.com/ClickHouse/ClickHouse/pull/40910 merged with the following new feature. 

> Add new setting input_format_json_read_numbers_as_strings that allows to parse numbers in String column, the setting is disabled by default.
