### ISSUE TITLE
/ (shortcut) to repeat the last (previous) SQL command  (clickHouse-client) 

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#40280]
Oracle cli client (sqlplus) has a neat feature, if you put `/[enter]` in the prompt, it re-executes the last SQL.

```sql
:) select 1;
┌─1─┐
│ 1 │
└───┘

:) /
┌─1─┐
│ 1 │
└───┘
```

currently `<up><enter>` pollutes the screen by the SQL text and can contain SQL script, not a single query. Probably echo should be disabled in this case as well.

**Comment by alexey-milovidov** [comment]
Nice. Should be good to implement.

What is the initial reasoning for using `/` to repeat the query?
We need to understand before implementing.

In many UNIX tools, `/` means "search by regular expression" for some other reason.

**Comment by den-crane** [comment]
I don't know/remember exactly why. 
I think \ is a mark of end of SQL script.
I like this character because it's very near to enter key, so it can typed by one stroke.
Probably we should/we can use `;` instead. 
; is also very near to enter key.

**Comment by alexey-milovidov** [comment]
`;` is worse, because it may indicate an intent to do nothing.

**Comment by alexey-milovidov** [comment]
We need to find any explanation why `/` means "re-run the last query", otherwise adding this feature will look stupid.

**Comment by mikeTWC1984** [comment]
May also try ctrl+enter. In bash  there is a similar feature - !! which also let you to extend previous command (e.g. sudo !!), might be a neat functionality in sql repl  e.g. select * from !!

**Comment by alexey-milovidov** [comment]
`!!` looks bad.

**Comment by alexey-milovidov** [comment]
@den-crane we still need to figure out why sqlplus has this behavior.
Try contacting its author. Interesting how they will justify it.

**Comment by rschu1ze** [comment]
What about `.`? It doesn't look like SQL, it is close to the Enter key and it means ["repeat the last command"](https://initialcommit.com/blog/7-versatile-vim-commands#1-the-dot-command) in Vim.

Clickhouse-client currently provides three shortcuts:
- `\l` for `SHOW DATABASES`
- `\d` for `SHOW TABLES`
- `\c` for `USE`

So for consistency's sake, another option would be a shortcut with `\` prefix, e.g. `\.` or `\g`. That's also how [PostgreSQL does it](https://www.geeksforgeeks.org/postgresql-psql-commands/) (`\g`).

Btw., I don't think we need to be super-careful with the naming ... the shortcut is syntactic sugar for interactive mode and could be changed later if necessary.

Will push a draft and can finalize it once the naming is fixed.

**Comment by alexey-milovidov** [comment]
Let's add both `.` and `/` without the backslash.

**Comment by den-crane** [comment]
> @den-crane we still need to figure out why sqlplus has this behavior. Try contacting its author. Interesting how they will justify it.

:) It was implemented probably 40 years ago. We cannot find why and who decided it.
