### ISSUE TITLE
Clickhouse cluster in Nomad 

### ISSUE THREAD

**Issue by Hanmask21** [ClickHouse/ClickHouse#40308]
Running clickhouse cluster in nomad throws the following errors.
`2022.08.17 08:45:08.203862 [ 69 ] {} <Error> RaftInstance: session 5 failed to read rpc header from socket ::ffff:127.0.0.1:35528 due to error 2, End of file, ref count 1`

 Qurum is not working
 
 How to launch clickhouse correctly in nomad?

**Comment by alexey-milovidov** [comment]
Looks like no one used ClickHouse in Nomad.
