### ISSUE TITLE
Documentation with versions

### ISSUE THREAD

**Issue by ramazanpolat** [ClickHouse/ClickHouse#40304]
**Describe the issue**
CH gets updated frequently and if we do not upgrade our setup for a couple of months then some parts of the docs become irrelevant because the docs do not indicate the change over the CH versions.

We need to see the document relavant to our CH version.

Something like this:

![image](https://user-images.githubusercontent.com/3527695/185113989-f42bc8d4-d387-4dcd-ba0c-c54ebed299ba.png)

The first example that comes to my mind is `enable_positional_arguments` setting.

[Here ](https://clickhouse.com/docs/en/operations/settings/settings/#enable-positional-arguments)it says the default value is 0 while in recent versions it is 1. In this case this is only true for older versions, for example with 22.7, it is enabled by default. We don't know when it is set to 1 by default. Also we don't know if it is set to 1 for our version without testing.

Also, there are some sample SQL statements using positional arguments while it is disabled by default for older versions. So those samples does not run.

There are lots of other problems because docs are not alligned with CH versions.

**Comment by alexey-milovidov** [comment]
Ideally, we want to make the version selector in the documentation, but it appeared to be out of what our team is capable to support as of now. That's why we don't add a version selector.
