### ISSUE TITLE
ClickHouse takes more than 3-4 minutes to start when s3 send_metadata is enabled.

### ISSUE THREAD

**Issue by HeenaBansal2009** [ClickHouse/ClickHouse#40316]
**Describe the situation**
when s3 disk is defined with send_metadata  is true , CH takes way longer than expected to start.

**How to reproduce**
Configure s3 disk storage_configuration in config.xml and set send_metadata = true*
Clickhouse takes almost 4 minutes to start and it varies from environment to environment. 

**Expected Performance:**
Clickhouse should not take more than 2 minutes to start up.

I see that CH registered disk as part of main thread  and  what if clickhouse only register disk in disk factory and startup can be done as a background thread. 
Currently , regsisterdisks3() won't return until diskobjectstorage is initialized which also includes finding the lastRevision() for s3 object which tries to construct the  64 bit revision  which makes s3 disk startup slower.
I see we use revision_counter only during operations on disk objects.

What could be the impact to findLastRevision() after server startup and clickhouse-server comes up before.

**Comment by HeenaBansal2009** [comment]
@alexey-milovidov , I understand if this improvement cannot be in your do to list. I can take this up .
I am looking for some background information to work on this. 

Thanks.

**Comment by alexey-milovidov** [comment]
We don't use `send_metadata` in production and we are not sure about the applicability of this feature.

**Comment by alexey-milovidov** [comment]
You may want to ask the author: https://github.com/ClickHouse/ClickHouse/pull/18377

**Comment by alexey-milovidov** [comment]
The author can be found in Telegram: @JokserFN
If there will be no success in supporting this feature, it is going to be removed.

**Comment by HeenaBansal2009** [comment]
Thanks @alexey-milovidov .
I see there was internal documentation ticket raised  DOCSUP-18488 for the documentation of this feature. 

Can you share the doc link delivered as part of this ticket .

**Comment by alexey-milovidov** [comment]
There are no docs for this feature. This feature is not implemented and the remaining parts are going to be removed.
