### ISSUE TITLE
Improve merge_tree_metadata_cache usability

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#40313]
1) You can successfully create table with enabled `use_metadata_cache=1` but insert will fail with incorrect config of merge_tree_metadata_cache.
2) Error should not be LOGICAL_ERROR. Just misconfiguration.
```
Code: 49. DB::Exception: Received from localhost:9000. DB::Exception: Received from fzunqu5yfc.eu-west-1.aws.clickhouse-staging.com:9440. DB::Exception: Merge tree metadata cache is not initialized, please add config merge_tree_metadata_cache in config.xml and restart. (LOGICAL_ERROR)
```
3) We removed default configuration. Why not enable back as you have to enable feature in table settings? https://github.com/ClickHouse/ClickHouse/pull/36838/files

**Comment by alexey-milovidov** [comment]
The `use_metadata_cache` is an experimental feature that is unlikely to be supported.

**Comment by mo-avatar** [comment]
> feature
Alexey
Do you mean it is very likely that  we won't have metadata_cache feature in the future? and why?
Thanks.

**Comment by mo-avatar** [comment]
> The `use_metadata_cache` is an experimental feature that is unlikely to be supported.
Alexey
Do you mean it is very likely that  we won't have metadata_cache feature in the future? and why?
Thanks.

**Comment by Algunenano** [comment]
Feature was removed https://github.com/ClickHouse/ClickHouse/pull/51303
