### ISSUE TITLE
Extract specific symbols in the string

### ISSUE THREAD

**Issue by sabinajvdva** [ClickHouse/ClickHouse#40327]
Hi!

I would be grateful if you help me to find specific symbols in the string. 
I have a table **'comment'** with the column **'text'**
In that column i have some text, for example : 
"_Address: Chicago, 15 and Number of people: **2**_" 

How can I extract "**2**" out of this text? I mean I need only "**2**" in this string

**Comment by DerekChia** [comment]
Hello! Does your text always conform to the structure of `Address: XX, YY and Number of people: ZZ`? And do you only want to extract the last integer?

**Comment by den-crane** [comment]
extractAll ?

```sql
SELECT
    'Address: Chicago, 15 and Number of people: 2' AS text,
    extractAll(text, '2') AS r

Query id: f728b623-2743-4056-87b3-efe7e041cd41

┌─text─────────────────────────────────────────┬─r─────┐
│ Address: Chicago, 15 and Number of people: 2 │ ['2'] │
└──────────────────────────────────────────────┴───────┘
```

**Comment by den-crane** [comment]
substring ?

```sql
select 'Address: Chicago, 15 and Number of people: 2' text, substring(text, -1) r;
┌─text─────────────────────────────────────────┬─r─┐
│ Address: Chicago, 15 and Number of people: 2 │ 2 │
└──────────────────────────────────────────────┴───┘
```

**Comment by den-crane** [comment]
```sql
SELECT
    'Address: Chicago, 15 and Number of people: 2' AS text,
    extract(text, '(\\d)$') AS r

┌─text─────────────────────────────────────────┬─r─┐
│ Address: Chicago, 15 and Number of people: 2 │ 2 │
└──────────────────────────────────────────────┴───┘
```

```sql
SELECT
    'Address: Chicago, 15 and Number of people: 22' AS text,
    extractAll(text, '(\\d+)') AS r

┌─text──────────────────────────────────────────┬─r───────────┐
│ Address: Chicago, 15 and Number of people: 22 │ ['15','22'] │
└───────────────────────────────────────────────┴─────────────┘
```

**Comment by sabinajvdva** [comment]
> Hello! Does your text always conform to the structure of `Address: XX, YY and Number of people: ZZ`? And do you only want to extract the last integer?

No text is always different, but it has 'Number of people: 2', so I need only the integer (2) out of this text. 

> ```sql
> ```sql
> SELECT
>     'Address: Chicago, 15 and Number of people: 2' AS text,
>     extract(text, '(\\d)$') AS r
> 
> ┌─text─────────────────────────────────────────┬─r─┐
> │ Address: Chicago, 15 and Number of people: 2 │ 2 │
> └──────────────────────────────────────────────┴───┘
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```sql
> SELECT
>     'Address: Chicago, 15 and Number of people: 22' AS text,
>     extractAll(text, '(\\d+)') AS r
> 
> ┌─text──────────────────────────────────────────┬─r───────────┐
> │ Address: Chicago, 15 and Number of people: 22 │ ['15','22'] │
> └───────────────────────────────────────────────┴─────────────┘
> ```
> ```

Thank you! I will try that. 

And I also found this way and it worked: 
```
toInt32OrZero(cast(
				if 
				(
				trim(
					replace(
						mid
						(text,
						POSITION (text,'Number of people:')+LENGTH('Number of people:'),
						POSITION(mid(bc.text,POSITION(text,'Number of people:')+LENGTH('Number of people:')),'.')
						)
					,'.',' ')
				)='',
				trim(mid(text,POSITION(text,'Number of people:')+LENGTH('Number of people:'))),
				trim(
					replace(
						mid
						(text,
						POSITION(text,'Number of people:')+LENGTH('Number of people:'),
						POSITION(mid(text,POSITION(text,'Number of people:')+LENGTH('Number of people:')),'.')
						)
					,'.',' ')
				)
				) as text ) 
```
