### ISSUE TITLE
Automatically merge the best pull requests

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#40325]
If a pull request is approved and has no modifications after it is approved and all the checks are green and there are more than 100 checks, merge automatically.

https://github.com/ClickHouse/ClickHouse/blob/be29057de1835f6f4a17e03a422b45b81efe6833/docs/ru/whats-new/extended-roadmap.md#735-%D0%BD%D0%B0%D1%87%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B5-%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D0%BB%D0%B0-%D0%B4%D0%BB%D1%8F-%D0%B0%D0%B2%D1%82%D0%BE-merge-nachalnye-pravila-dlia-avto-merge

**Comment by Felixoid** [comment]
Usually, it's the github button `automatic merge on the green`. But with our `Mergeable` we can't actually use this.

In our case, it works another way around. `Mergeable` is green from the beginning, and eventually can be red.

What we can do is add an automatic merge to the `Finish` check. But once added, it will merge anything green.

**Comment by alexey-milovidov** [comment]
> What we can do is add an automatic merge to the Finish check. But once added, it will merge anything green.

Just check if there is approval, and no commits after the approval.

**Comment by Felixoid** [comment]
It makes sense. Would work, for sure.

Do we consider only merges to master, or backports too?

**Comment by alexey-milovidov** [comment]
This is for master.

For backports we need to use an even simpler method - only check for green checks and nothing else (no review).
