### ISSUE TITLE
Metric for the number of detached parts

### ISSUE THREAD

**Issue by Alex-Burmak** [ClickHouse/ClickHouse#40332]
It would be useful to have a metric in system.metrics with the total number of detached parts. It will allow to easily configure charts for detached parts and set up alerting.

Also it probably makes sense to create additional metrics for manually detached parts and parts detached by ClickHouse itself. These types of detached parts can be easily differentiated by checking reason - for manually detached parts it will be empty.

**Comment by CheSema** [comment]
So. I have read the code around. I try to describe what I am going to do and what was the alternatives.

As I see Clickhouse has 2 types of metrics: metrics and asynchronous_metrics. I think here is appropriate to use asynchronous_metrics.

With asynchronous_metrics the implementation would be easy and the behaviour would be strightforward. Clickhouse would have the code which times to time looks into detached directories and refreshes the statistic about detached parts. And I think the refresh period should be large then 1s, something like 1m is fine. That code could be triggired by AsynchronousMetrics thread.

With [sync] metrics the implementation become heavy with no significant advantages. With such type of metrics implementation has to have designated variables which are incrementing/decrementing by some actions in code. Like user request "DETACH PART" and similar request or like when clickhouse moves broken parts to detached and ttl cleans some detached parts. The are some set of such actions. And that aspect I considering as heavy. Even if implementation covers all the actions the behaviour is still not obvious du to possibility that part could be removed or placed to the detached directory by administrator. Clickhouse would newer notice that by himself without asynchronous checks as described above. The is no point to provide instant changes in metrics if the values are out of our control.

**Comment by alexey-milovidov** [comment]
@CheSema Totally agree, let's put it in the AsynchronousMetrics thread and make some update period not more frequently than one minute.
