### ISSUE TITLE
Warning suppression mechanism

### ISSUE THREAD

**Issue by Alex-Burmak** [ClickHouse/ClickHouse#40330]
I have ClickHouse server running in virtual environment that reports the following warning:

```
# clickhouse-client
ClickHouse client version 22.7.2.15 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 22.7.2 revision 54457.

Warnings:
 * Linux is not using a fast TSC clock source. Performance can be degraded. Check /sys/devices/system/clocksource/clocksource0/current_clocksource

# cat /sys/devices/system/clocksource/clocksource0/current_clocksource
kvm-clock
```

It looks like a false positive as kvm-clock is considered a preferable clock source for kvm-based VMs.
https://opensource.com/article/17/6/timekeeping-linux-vms

Regardless of whether it's a bug or not, I'd like to have some mechanism that allows to disable particular warnings. There are may be other questionable warnings in the future.

**Comment by alexey-milovidov** [comment]
I prefer to not have any questionable warnings at all.
