### ISSUE TITLE
INET_NTOA and INET6_NTOA functions return different result from mariadb functions

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#40340]
> You have to provide the following information whenever possible.

**Describe what's wrong**

INET_NTOA and INET6_NTOA is just an alias to IPv4NumToString, IPv6NumToString function and looks like behavior of ClickHouse functions differs from mariadb.

**Does it reproduce on recent release?**

Yes. 22.7

**How to reproduce**

mariadb
```
SELECT INET6_NTOA(CAST(UNHEX('663B3DB1') AS BINARY)) as v4, INET6_NTOA(CAST(UNHEX('663B3DB1000000000000000000000000') AS BINARY)) as v6;

v4 | v6
-- | --
102.59.61.177 | 663b:3db1::


clickhouse

SELECT
    INET6_NTOA(CAST(UNHEX('663B3DB1'), 'BINARY(16)')) AS v4,
    INET6_NTOA(CAST(UNHEX('663B3DB1000000000000000000000000'), 'BINARY(16)')) AS v6

Query id: 2e1b6fd8-8d7a-4974-b8b9-e1dc5e726607

┌─v4──────────┬─v6──────────┐
│ 663b:3db1:: │ 663b:3db1:: │
└─────────────┴─────────────┘

SELECT
    INET_NTOA(reinterpretAsUInt32(UNHEX('663B3DB1'))) AS v4,
    INET_NTOA(reinterpretAsUInt32(reverse(UNHEX('663B3DB1')))) AS v4_rev

Query id: 31c6a53e-8ab0-44ec-8500-94faf20b3aef

┌─v4────────────┬─v4_rev────────┐
│ 177.61.59.102 │ 102.59.61.177 │
└───────────────┴───────────────┘
```

mariadb takes as input String and automatically convert it to ipv4 or ipv6 depending on string length. (If it 4 or less it uses ipv4)

**Expected behavior**

Result will be the same as in mariadb

**Additional context**

Workaround:

```
if(length(toString(ip)) = 4,
INET_NTOA(reinterpretAsUInt32(reverse(toString(ip)))),
if(length(toString(ip)) < 4,
INET_NTOA(reinterpretAsUInt32(256*toUInt64(toString(reinterpretAsUInt32(reverse(toString(ip))))))) ,
INET6_NTOA(ip))) AS ip_str
```

But it still have some issues.

**Comment by alexey-milovidov** [comment]
MariaDB's behavior is hardly correct.

**Comment by UnamedRus** [comment]
If you explicitly add functions with the **same** name to be "compatible" with **specific** dbms.

https://github.com/ClickHouse/ClickHouse/pull/19387

I guess they shoud return the **same** result as in source system.

**Comment by UnamedRus** [comment]
Otherwise, its complete garbage on which people spend time and only after hours of work understand that they cannot be used

**Comment by UnamedRus** [comment]
Same behavior in singlestore https://docs.singlestore.com/cloud/reference/sql-reference/string-functions/inet-6-ntoa/
