### ISSUE TITLE
How about arrays in materialized views? Does that make it slower?

### ISSUE THREAD

**Issue by DangoTinker** [ClickHouse/ClickHouse#40342]
like:
```

CREATE TABLE test_mv_t (
    other columns
  `rtt_arr` AggregateFunction(groupArrayIf, Float32, UInt8)
)
```

then
 select quantile(0.8)(arrayJoin(groupArrayIfMerge(rtt_arr))) AS rtt_p80 from test_mv_t
 or quantile(0.8) or avg() or other changes without change mv

what's a better way?

**Comment by den-crane** [comment]
kinda. If all arrays in a block are very long

1. I doubt you need `if` in AggregateFunction, probably you made a mistake in MatView
2. Arrays has a hard limit in the max length -- 1 million elements.
3. It has sense to store quantile in Mat.View
