### ISSUE TITLE
How do I use jdbctemplate to set the queryId before a query？

### ISSUE THREAD

**Issue by zhengwenhao07** [ClickHouse/ClickHouse#40344]
How do I use jdbctemplate to set the queryId before a query？ Or, how can get queryId by jdbc? I use springboot.
According to the issue:https://github.com/ClickHouse/ClickHouse/issues/11987, [siradjev](https://github.com/siradjev)
I enter 【select 1 settings max_threads=1, customsetting.query_id='2222'】, client shows 【Code: 115. DB::Exception: Received from localhost:9000. DB::Exception: Unknown setting customsetting.query_id. (UNKNOWN_SETTING)】

**Comment by genzgd** [comment]
Assuming you are using the supported ClickHouse JDBC driver, this PR describes how to set the query_id by implementing the ClickHouseRequestManager:  https://github.com/ClickHouse/clickhouse-jdbc/issues/870

**Comment by zhengwenhao07** [comment]
> Assuming you are using the supported ClickHouse JDBC driver, this PR describes how to set the query_id by implementing the ClickHouseRequestManager: [ClickHouse/clickhouse-jdbc#870](https://github.com/ClickHouse/clickhouse-jdbc/issues/870)

Thank you for your reply ! This is my code, I still don't know how to use it
`@Component
@Log4j2
public class ClickHouseUtil {
    
    @Autowired
    @Qualifier(value = "clickHouseTemplate")
    private JdbcTemplate clickHouseTemplate;
    // how to use?
    private static final ClickHouseRequestManager instance = ClickHouseUtils.getService(ClickHouseRequestManager.class, ClickHouseRequestManager::new);

    public List<Map<String, Object>> queryList(final String sql) {
        return queryList(sql, Function.identity());
    }

    public List<Map<String, Object>> queryList(final String sql, final Function<Object, Object> resultConvert) {
        return clickHouseTemplate.query(sql, new ColumnMapRowMapper() {
            @Override
            protected Object getColumnValue(final ResultSet rs, final int index) throws SQLException {
                Object value = super.getColumnValue(rs, index);
                return resultConvert.apply(value);
            }
        });
    }
}`

**Comment by zhengwenhao07** [comment]
> Assuming you are using the supported ClickHouse JDBC driver, this PR describes how to set the query_id by implementing the ClickHouseRequestManager: [ClickHouse/clickhouse-jdbc#870](https://github.com/ClickHouse/clickhouse-jdbc/issues/870)

What class of 'request' in https://github.com/ClickHouse/clickhouse-jdbc/issues/870

**Comment by genzgd** [comment]
Answered here:  https://github.com/ClickHouse/clickhouse-jdbc/issues/1047
