### ISSUE TITLE
Question about server log

### ISSUE THREAD

**Issue by arunmarathe** [ClickHouse/ClickHouse#40351]
Is information in CH server log documented somewhere? I don't need every little detail, but an overview doc would be nice. I didn't find much in the CH documentation regarding this. I build server, and run it in a console, and see that it's doing quite a bit of things behind the scenes, and some of them can even be deciphered (eg, building projections), but any more information would be welcome.

Thanks,
Arun

**Comment by alexey-milovidov** [comment]
No, the server logs are not documented.

**Comment by DerekChia** [comment]
Hey @arunmarathe, depending on the logging level set at the [logging setting](https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings/#server_configuration_parameters-logger), you will see the logs at different verbosity i.e. `trace, debug, information, warning, error`

Alternatively, if you'd like to see the code that triggers the different type of errors, you can search for the terms `LOG_TRACE`, `LOG_DEBUG` and so on. 

You can also search for these terms in the ClickHouse source code in Github: 
- https://github.com/ClickHouse/ClickHouse/search?l=C%2B%2B&q=LOG_TRACE
- https://github.com/ClickHouse/ClickHouse/search?l=C%2B%2B&q=LOG_DEBUG

Hope that helps!
