### ISSUE TITLE
Configured background pool size does not match system.settings

### ISSUE THREAD

**Issue by larry-cdn77** [ClickHouse/ClickHouse#40384]
**Describe what's wrong**

Value of background_fetches_pool_size configured in config.xml (as per #36425):

```xml
<background_fetches_pool_size>64</background_fetches_pool_size>
```

does not show system.settings which has the default value instead:

```sql
SELECT name, value FROM system.settings WHERE name LIKE 'background_fetches_pool_size'
┌─value─┐
│ 8     │
└───────┘
```

while the correct value shows in the log:

```
Initialized background executor for fetches with num_threads=64, num_tasks=64
```

and BackgroundFetchesPoolTask sometimes exceeds the default so it looks like it's actually using the configured value

**Does it reproduce on recent release?**

Yes (suppose 22.8 LTS will be added to version_date.tsv)

**How to reproduce**

ClickHouse server version 22.8.1.2097

**Comment by tavplubix** [comment]
This setting is obsolete:
```
ClickHouse client version 22.8.1.1.
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 22.8.1 revision 54460.

dell9510 :) select * from system.settings where name='background_fetches_pool_size'

SELECT *
FROM system.settings
WHERE name = 'background_fetches_pool_size'

Query id: c4256263-ee40-4cf4-ad2d-9352fea6b5e7

┌─name─────────────────────────┬─value─┬─changed─┬─description─────────────────────┬─min──┬─max──┬─readonly─┬─type───┐
│ background_fetches_pool_size │ 8     │       0 │ Obsolete setting, does nothing. │ ᴺᵁᴸᴸ │ ᴺᵁᴸᴸ │        0 │ UInt64 │
└──────────────────────────────┴───────┴─────────┴─────────────────────────────────┴──────┴──────┴──────────┴────────┘

1 row in set. Elapsed: 0.036 sec. 
```

 It was replaced with configuration parameter with the same name.

**Comment by larry-cdn77** [comment]
Thank you, indeed the confusion I had was in thinking that this configuration parameter (config.xml) can be viewed via system.settings
