### ISSUE TITLE
Allow to send revision over HTTP for native format

### ISSUE THREAD

**Issue by gingerwizard** [ClickHouse/ClickHouse#40397]
Currently we can't get timezone information for datetime columns as this isn't returned - see https://github.com/ClickHouse/ClickHouse/issues/38209

Request that we be able to send a revision number over HTTP as a parameter so this information is returned.

**Comment by genzgd** [comment]
At what point do we sunset backward compatibility?  The timezone format change was in release 1.1.54337, which is January 18, 2018, more than five years ago.  Maybe we could remove some of those checks?

**Comment by genzgd** [comment]
Draft PR with a rough fix for this:   https://github.com/ClickHouse/ClickHouse/pull/46360 -- needs tests and I'm not sure sticking the revision in the Context is the right approach.

**Comment by jkaflik** [comment]
Well done @genzgd ! Thanks

**Comment by mshustov** [comment]
@genzgd https://github.com/ClickHouse/ClickHouse/pull/46360 is merged. Can we close the issue?
