### ISSUE TITLE
tupleToNameValuePairs lost its beauty in the new version (22.6.3.35)

### ISSUE THREAD

**Issue by dmkolesova** [ClickHouse/ClickHouse#40396]
> You have to provide the following information whenever possible.

**Describe what's wrong**

We're testing new release 22.6.3.35 and have discovered that function tupleToNameValuePairs lost some of functionality. 
In previous versions (at least, 22.1.3.7) we could use tupleToNameValuePairs  for unpivot operations (as described [here](https://kb.altinity.com/altinity-kb-queries-and-syntax/pivot-unpivot/#using-tupletonamevaluepairs-starting-from-clickhouse-219) )
What's wrong in 22.6.3.35?
When we're perform this part `ARRAY JOIN tupleToNameValuePairs((AA, AB, AC, AD)) AS tpl` we have obtained not names but indexes:
![image](https://user-images.githubusercontent.com/60538827/185612220-62bd7156-4afb-4425-bacf-eed28d2c46cc.png)

While in the 22.1.3.7 we get this result:
![image](https://user-images.githubusercontent.com/60538827/185612330-74227959-4165-4b8b-8f10-004c37c10f71.png)

**Does it reproduce on recent release?**
I can be sure that this issue can be reproduced here 22.6.3.35

[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

**Enable crash reporting**

> If possible, change "enabled" to true in "send_crash_reports" section in `config.xml`:

```
<send_crash_reports>
        <!-- Changing <enabled> to true allows sending crash reports to -->
        <!-- the ClickHouse core developers team via Sentry https://sentry.io -->
        <enabled>false</enabled>
```

**How to reproduce**

* Which ClickHouse server version to use - 22.6.3.35
* Which interface to use, if matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
```
CREATE TABLE sales_w(suppkey UInt8, brand String, AA UInt32, AB UInt32, AC UInt32, AD UInt32) ENGINE=Memory();

INSERT INTO sales_w VALUES (1, 'BRAND_A', 1500, 4200, 1600, 9800), (2, 'BRAND_B', 6200, 1300, 5800, 3100), (3, 'BRAND_C', 5000, 8900, 6900, 3400);

SELECT
    suppkey,
    brand,
    category,
    quantity
FROM sales_w
ARRAY JOIN
    [AA, AB, AC, AD] AS quantity,
    splitByString(', ', 'AA, AB, AC, AD') AS category
ORDER BY suppkey ASC
;
SELECT
    suppkey,
    brand,
    tpl.1 AS category,
    tpl.2 AS quantity
FROM sales_w
ARRAY JOIN tupleToNameValuePairs((AA, AB, AC, AD)) AS tpl
ORDER BY suppkey ASC
;
```
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

**Expected behavior**

[Result as in the documentation](https://kb.altinity.com/altinity-kb-queries-and-syntax/pivot-unpivot/#using-tupletonamevaluepairs-starting-from-clickhouse-219)

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/36773
