### ISSUE TITLE
Nested columns default value does not match other nested columns length 

### ISSUE THREAD

**Issue by jan-osch** [ClickHouse/ClickHouse#40401]
**Describe the unexpected behaviour**
I've encountered a strange issue when adding new `nested` sub-columns. I'm trying to avoid a situation when outdated application code fails on inserts to a Clickhouse table, because of missing data for the new sub-columns. I tried using an explicit default value for the new sub-columns, but then the new sub-column arrays don't match the length of existing nested sub-columns.

### This is the behaviour with implicit default value:
```
ALTER TABLE my_table ADD COLUMN IF NOT EXISTS `metadata_BROWSER_pages.onContentLoad` Array(Float32);
```  

<img width="858" alt="Screenshot 2022-08-19 at 14 44 46" src="https://user-images.githubusercontent.com/11651780/185622787-e4aa93d0-1060-4d5a-8e4a-6df5c83fe6dd.png">

### This is the behaviours with explicit default value:
```
ALTER TABLE my_table ADD COLUMN IF NOT EXISTS `metadata_BROWSER_pages.onContentLoad` Array(Float32) DEFAULT [0];
```
<img width="865" alt="Screenshot 2022-08-19 at 14 45 18" src="https://user-images.githubusercontent.com/11651780/185622994-69aa144c-4f64-4677-8084-16c749c93287.png">

It is also causing application code errors,  
```
DB::Exception: Elements 'metadata_BROWSER_pages.TTFB' and 'metadata_BROWSER_pages.onContentLoad' of Nested data structure 'metadata_BROWSER_pages' (Array columns) have different array sizes. (SIZES_OF_ARRAYS_DOESNT_MATCH) (version 21.12.3.32.armprestable.arm (altinity build))
```

Is there a way to provide an explicit default value, that will automatically match the length of other nested arrays?

**Comment by alexey-milovidov** [comment]
Oops, you are using the wrong "altinity" build. Their build is not going to work.
https://clickhouse.com/docs/knowledgebase/difference_between_official_builds_and_3rd_party
