### ISSUE TITLE
Don't know how to debug MySQLHandler: DB::Exception: Cannot read all data. 

### ISSUE THREAD

**Issue by edo888** [ClickHouse/ClickHouse#40427]
Hi,

I have ClickHouse 22.1.3.7 installed and it is working fine and my inserts are going as expected. However in log I have multiple lines like this:

`<Error> MySQLHandler: DB::Exception: Cannot read all data. Bytes read: 0. Bytes expected: 3.`

I have tried to set logging level to test, but I am unable to get any useful information to understand what is going on.

Can you possibly hint me to the right direction?

Thanks!

**Comment by alexey-milovidov** [comment]
@edo888 Someone is connecting to the MySQL endpoint and does not send any data.
It might be a monitoring script.

This error does not necessarily require attention.

**Comment by edo888** [comment]
Yes, that was exactly that. I have connection reuse mechanism in place and connections can stay open for up to 30 seconds.

Is it better to do that or close and reopen connection every time a query needs to be pushed?

Thanks!

**Comment by alexey-milovidov** [comment]
For clickhouse-server it does not make any difference. For clients, reusing connections can be better (for latency).
