### ISSUE TITLE
Does CH run in debug or release mode?

### ISSUE THREAD

**Issue by arunmarathe** [ClickHouse/ClickHouse#40423]
I build and run CH server in console. Usually, I use one of the latest stable builds.

My question is: when running CH in this fashion, does it run in debug or release mode?

Depending on the answer, how do I run it in the "other" mode?

Thanks,
Arun

**Comment by nickitat** [comment]
Default build provides you with Release With Debug Info. To get debug binary you need to rebuild with other build type ([see](https://stackoverflow.com/a/59314670))
