### ISSUE TITLE
Documentation missing for required AVX cpu instruction set support

### ISSUE THREAD

**Issue by jzombi** [ClickHouse/ClickHouse#40437]
**Describe the issue**
It seems that the latest build (22.8.1-lts) works only on CPUs with AVX instruction set (see: https://github.com/ClickHouse/ClickHouse/pull/39000)

The [documentation](https://clickhouse.com/docs/en/operations/requirements#cpu) is not updated, it lists only SSE4.2 as a requirement.

**Sidenote**
IMHO the rationale for changing the required instruction set is a bit misleading.
> Prebuild ClickHouse x86 binaries now require support for AVX instructions, i.e. a CPU not older than Intel Sandy Bridge / AMD Bulldozer, both released in 2011

Having CPUs released in 2011 with AVX support does not mean that ALL CPUs released since have AVX support. CPUs targeted for embedded devices and small ITX boards usually lag behind desktop and server CPUs. (Eg. my [J1900](https://ark.intel.com/content/www/us/en/ark/products/78867/intel-celeron-processor-j1900-2m-cache-up-to-2-42-ghz.html) was released in 2013, it is not marked as discontinued, and lacks AVX support.)

**Comment by alexey-milovidov** [comment]
Currently, there are no performance advantages in enabling AVX (1).
Although we already have many pieces of AVX-2 and AVX-512 code that is selected at runtime with dynamic dispatching.

We enabled it to check if there will be no complaints and to move forward towards AVX-2.

**Comment by rschu1ze** [comment]
And speaking about complaints about the AVX requirement - we also found that Rosetta is no longer able to run the Mac x86 binaries on M1/M2 systems due to a [known limitation](https://developer.apple.com/documentation/apple-silicon/about-the-rosetta-translation-environment). But since one can also compile ARM binaries or get them from clickhouse.com, this is not a severe restriction.

**Comment by konnectr** [comment]
Unless support for Intel Celeron which will not be used in Clickhouse production. Is Clickhouse performance more important to the wider public?

**Comment by rschu1ze** [comment]
Performance is very important to the project. At the same time we should not forget about the many hobbyists with less recent hardware. And there is an (admittedly small) chance that ClickHouse is used in production on pre-2011 x86 hardware w/o AVX.
See the follow-up issue #40459.

**Comment by alexey-milovidov** [comment]
> Is Clickhouse performance more important to the wider public?

Simply enabling AVX-1 in the compiler does not improve performance.

**Comment by konnectr** [comment]
I think it just needs to be done like Windows 11 did with TPM 2.0

**Comment by rschu1ze** [comment]
Let's continue the discussion in https://github.com/ClickHouse/ClickHouse/issues/40459.
