### ISSUE TITLE
How to create a cluster for about 200T data?

### ISSUE THREAD

**Issue by ggservice007** [ClickHouse/ClickHouse#4044]
We have about 200TB data, how to create a cluster?

How to create the distributed table?

If the one server disk is almost full, I will add a new server. How to do ?

**Comment by den-crane** [comment]
>We have about 200TB data
200TB raw data in CSV or 200TB in single CH instance?
Do you have CH already?

>How to create the distributed table?
https://www.altinity.com/blog/2017/6/5/clickhouse-data-distribution
https://clickhouse.yandex/docs/en/operations/table_engines/distributed/

>If the one server disk is almost full, I will add a new server. How to do ?
There is no resharding in CH. You can just add new server into cluster and put more data there using weights.

**Comment by ggservice007** [comment]
@den-crane  @blinkov 
It is not raw 200TB Data.
Now we have CH with a single server.
My question is how to create the cluster.

**Comment by ggservice007** [comment]
@den-crane  @den-crane 
https://github.com/Vertamedia/chproxy

The chproxy is bad.

Any better solution for it?

**Comment by ggservice007** [comment]
@den-crane  @blinkov 
https://www.altinity.com/blog/2017/6/5/clickhouse-data-distribution

In this solution, when the server disk almost full, how to do?

**Comment by blinkov** [comment]
These articles are more or less about the same thing. But they are mostly about creating a fresh cluster. If the disks on this server are indeed almost full (like 80%+), it's probably better to create separate empty cluster and transfer data there via INSERT+SELECT or https://clickhouse.yandex/docs/en/operations/utils/clickhouse-copier/ (duplicating new data to either old server and new cluster during migration).

P.S. @ggservice007 are you in ClickHouse WeChat group? Maybe it'll be easier for people there to help you.

**Comment by ggservice007** [comment]
What number is the WebChat group?

**Comment by ggservice007** [comment]
@den-crane 
Can not auto copy from old server to new cluster?

**Comment by blinkov** [comment]
> The WeChat group is full. My WeChat number is zhaoshanhe007.
There are few of them and only one is full, I've sent a request to add you to not yet full one.

**Comment by volfco** [comment]
@ggservice007 You need to rewrite the data into a cluster. If you have a cluster already created, you just need to run `INSERT INTO <new distributed database> SELECT * FROM <old database>` to move the data from your single node to a cluster's distributed table.
