### ISSUE TITLE
system.replicas error

### ISSUE THREAD

**Issue by zhwuhuang** [ClickHouse/ClickHouse#40479]
execute  (SELECT * FROM `system`.replicas LIMIT 0, 200  ） error：
SQL Error [1000]: ClickHouse exception, code: 1000, host: 10.99.84.60, port: 31197; Poco::Exception. Code: 1000, e.code() = 2002, e.displayText() = mysqlxx::ConnectionFailed: Can't connect to MySQL server on '10.99.85.241' (115) ((nullptr):0) (version 20.3.8.53 (official build))

**Comment by rkozlo** [comment]
Version 20.3 is a version of clickhouse? Start with update because this version years behind its support.

**Comment by den-crane** [comment]
Upgrade your CH to 22.8.

**Comment by zhwuhuang** [comment]
OK, solved. Thank you
