### ISSUE TITLE
User arg in Linux ENV CLICKHOUSE_USER overrides the command line User arg -u

### ISSUE THREAD

**Issue by ramseyxu** [ClickHouse/ClickHouse#40477]
(you don't have to strictly follow this form)

**Describe the unexpected behaviour**
User arg in Linux ENV CLICKHOUSE_USER overrides the command line User arg -u

**How to reproduce**
* Which ClickHouse server version to use
22.3-lts
* Which interface to use, if matters
clickhouse-client
* Non-default settings, if any
CLICKHOUSE_USER=test

**Expected behavior**
command line -u arg can override CLICKHOUSE_USER env arg

**Error message and/or stacktrace**
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/4744175/185833724-0cc939c1-a56a-4afb-9bf8-308daf4955be.png">

Clickhouse-client parses command line user arg first and then parses CLICKHOUSE_USER env arg
It's unobvious for people may not notice CLICKHOUSE_USER env exist and confused by command -u argument not working

**Comment by rkozlo** [comment]
Seems to be already reported #38909
