### ISSUE TITLE
RabbitMQ headers

### ISSUE THREAD

**Issue by sossaman** [ClickHouse/ClickHouse#40481]
Hello, 
I am trying to connect ClickHouse (v22.8.1) to RabbitMQ (v3.10.7) using the following ddl script: 
```
CREATE DATABASE BI;

CREATE TABLE IF NOT EXISTS BI.opr (
    timestamp DateTime64(3,'Europe/Rome') CODEC(DoubleDelta),
    failure Bool,
    error LowCardinality(Nullable(String)),
    reasonError LowCardinality(Nullable(String)),
    message LowCardinality(Nullable(String))
) ENGINE = RabbitMQ 
SETTINGS 
    rabbitmq_host_port = 'rabbitmq:5672',
    rabbitmq_exchange_name = 'amq.headers',
    rabbitmq_exchange_type = 'headers',
    rabbitmq_queue_base = 'oprchannel',
    rabbitmq_routing_key_list = 'x-match=all,__Type__=log.opr,event=auditing',
    rabbitmq_queue_consume = 1,
    rabbitmq_format = 'JSONEachRow',
    date_time_input_format = 'best_effort';

CREATE TABLE IF NOT EXISTS BI.opr_data_source (
    timestamp DateTime64(3,'Europe/Rome') CODEC(DoubleDelta),
    failure Bool,
    error LowCardinality(Nullable(String)),
    reasonError LowCardinality(Nullable(String)),
    message LowCardinality(Nullable(String))
) ENGINE MergeTree()
  ORDER BY tuple();

CREATE MATERIALIZED VIEW BI.opr_view TO BI.opr_data_source
  AS SELECT * FROM BI.opr;
```
On RabbitMQ there is a queue named oprchannel binded to the default exchange amq.headers.
Theoretically ClickHouse should ingest only the messages having both the headers matching what indicated in the script, but it does not happen.
ClickHouse ingest any message regarding the headers.
Do you believe is it a bug or a misconfiguration made by me?
Thanks in advance for any suggestions!

**Comment by kssenii** [comment]
Yes, it should go only where both headers match. But as I see there is the test https://github.com/ClickHouse/ClickHouse/blob/master/tests/integration/test_storage_rabbitmq/test.py#L1551-L1640 which checks exactly that `x-macth=all` works and no redundant messages appeared. So not sure for now why it does not work for you.

**Comment by sossaman** [comment]
As far as I understod from row 1621 to 1624 there is the composition of the headers: 
```
    fields = {}
    fields["format"] = "logs"
    fields["type"] = "report"
    fields["year"] = "2020"
```
The It tests if it reads messages with those headers ... but not if it does not read messages with different headers.
Am I wrong ?

**Comment by kssenii** [comment]
It checks that messages go to tables where `format=logs && type=report && year=2020` are do not go where the year is different `format=logs && type=report && year=2019` by checking https://github.com/ClickHouse/ClickHouse/blob/c5c6f8a3fe496ae588a2d96b672b7839bf45dd5d/tests/integration/test_storage_rabbitmq/test.py#L1636-L1639 where `num_tables_to_receive` have 2020 year https://github.com/ClickHouse/ClickHouse/blob/c5c6f8a3fe496ae588a2d96b672b7839bf45dd5d/tests/integration/test_storage_rabbitmq/test.py#L1561-L1574 and there are +2 tables which have 2019 year https://github.com/ClickHouse/ClickHouse/blob/c5c6f8a3fe496ae588a2d96b672b7839bf45dd5d/tests/integration/test_storage_rabbitmq/test.py#L1584-L1596
e.g. we have 4 tables, but only 2 of them - where ALL headers match, received the messages. Am I missing something?

**Comment by sossaman** [comment]
After some testing I found out that the routing that ClickHouse creates on RabbitMQ is quite more complex than the one that was set up.
In my setting I used: **rabbitmq_queue_consume = 1**
in order to make ClickHouse use an existing exchange , the default **amq.headers**.
As a solution I proposed to the developers to let ClickHouse create the exchange.
So problem solved, thanks for the cooperation!
