### ISSUE TITLE
MaterializedMySQL cannot handle database names requiring backquotes

### ISSUE THREAD

**Issue by ericatpolar** [ClickHouse/ClickHouse#40503]
Creating a MaterializedMySQL from a db-name containing a hyphen does not work.

It looks like `rewriteMysqlQueryColumn()` incorrectly add back-ticks incorrectly: https://github.com/ClickHouse/ClickHouse/blob/b7d4c78/src/Databases/MySQL/MaterializedMySQLSyncThread.cpp#L398

Query appearing in MySQL query log:

    SELECT COLUMN_NAME AS column_name, COLUMN_TYPE AS column_type 
    FROM 
        INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '`test-db`' 
        AND TABLE_NAME = '`test-table`' ORDER BY ORDINAL_POSITION

** how to reproduce **

In MySQL:
        
    CREATE DATABASE `test-db`;
    CREATE TABLE `test-db`.`test-table` (
      `id` INT NOT NULL AUTO_INCREMENT,
      PRIMARY KEY (`id`)
    ) ENGINE=MyISAM;

In Clickhouse:

    CREATE DATABASE `test-db` ENGINE = MaterializedMySQL(
        'mysql-master-analytics:3306', 
        'test-db', 
        'username', 
        'password'
    ) SETTINGS materialized_mysql_tables_list='test-table';

clickhouse error trace:

```
2022.08.22 19:57:20.569588 [ 458 ] {} <Error> MaterializedMySQLSyncThread: Poco::Exception. Code: 1000, e.code() = 1064, mysqlxx::BadQuery: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM `test-db`.`test-table`' at line 1 (mysql-master-analytics:3306), Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x19ce216c in /usr/bin/clickhouse
1. mysqlxx::Query::executeImpl() @ 0x19a63fb3 in /usr/bin/clickhouse
2. DB::MySQLSource::Connection::Connection(mysqlxx::Pool::Entry const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x16b575a8 in /usr/bin/clickhouse
3. DB::MySQLSource::MySQLSource(mysqlxx::Pool::Entry const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Block const&, DB::StreamSettings const&) @ 0x16b5786c in /usr/bin/clickhouse
4. ? @ 0x1555b499 in /usr/bin/clickhouse
5. ? @ 0x15558205 in /usr/bin/clickhouse
6. void DB::commitMetadata<std::__1::function<void ()> const&>(std::__1::function<void ()> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x15582132 in /usr/bin/clickhouse
7. DB::MaterializeMetadata::transaction(DB::MySQLReplication::Position const&, std::__1::function<void ()> const&) @ 0x15581f39 in /usr/bin/clickhouse
8. DB::MaterializedMySQLSyncThread::prepareSynchronized(DB::MaterializeMetadata&) @ 0x15548d76 in /usr/bin/clickhouse
9. DB::MaterializedMySQLSyncThread::synchronization() @ 0x155481aa in /usr/bin/clickhouse
10. ? @ 0x15557510 in /usr/bin/clickhouse
11. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xb41d957 in /usr/bin/clickhouse
12. ? @ 0xb4214dd in /usr/bin/clickhouse
13. ? @ 0x7fb2f9a84609 in ?
14. clone @ 0x7fb2f99a9133 in ?
 (version 22.3.8.40.altinitystable (altinity build))
```

Error is caused by an unexpected empty string return value from `rewriteMysqlQueryColumn()` which means tables with no fields may also break replication.

**Comment by alexey-milovidov** [comment]
I'm closing all old issues about MaterializedMySQL because the ClickHouse team does not support it.

**Comment by zoyu01** [comment]
I can  also reproduce  this issue (mysql 8.0.28)
<pre>
... FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '`99pay`' AND TABLE_NAME = 't_trade_order' ORDER BY ORDINAL_POSITION
</pre>
with my configuration 
<code>
CREATE DATABASE matr_99pay_apos_pro_db ENGINE = MaterializedMySQL('127.0.0.1:3306', '99pay', 'root', 'root')
</code>
but TABLE_SCHEMA column did not contains "`" 

is it better like this?:
<code>
                            //" WHERE TABLE_SCHEMA = '"  + backQuoteIfNeed(database_name) +
                            //"' AND TABLE_NAME = '" + backQuoteIfNeed(table_name) +  "' ORDER BY ORDINAL_POSITION";
                            " WHERE TABLE_SCHEMA = "  + quoteString(database_name) +
                            " AND TABLE_NAME = " + quoteString(table_name) +  " ORDER BY ORDINAL_POSITION"; 
</code>
