### ISSUE TITLE
How to Restart or Stop Clickhouse Keeper

### ISSUE THREAD

**Issue by jiangbiao910** [ClickHouse/ClickHouse#40507]
I use `sudo -u clickhouse clickhouse-keeper --config /etc/clickhouse-server/keeper.xml --daemon` to start clikhouse keeper ，But I don't know how to restart？ kill the pid？

**Comment by DerekChia** [comment]
Yes, you can kill the pid of `clickhouse-keeper` using `kill $(pidof clickhouse-keeper)` and then start it again.

The tool that ZooKeeper offers to restart ZooKeeper server (`zkServer.sh restart`) does similar something [similar](https://github.com/apache/zookeeper/blob/master/bin/zkServer.sh#L213) as well.

**Comment by jiangbiao910** [comment]
Thank you very much.
