### ISSUE TITLE
Find a exception and cant' be recover, any suggestions?

### ISSUE THREAD

**Issue by yanglfyangl1978** [ClickHouse/ClickHouse#4051]
![image](https://user-images.githubusercontent.com/26271882/51108856-61ce8f00-182e-11e9-8b29-bad92417d2b1.png)

Dear supporter:

Could you help to take a look for above issue? It happened without too much clues, and can't recover unless we clean and re-install a new clickhouse. 

Thanks.

**Comment by filimonov** [comment]
Binary was compiled for a platform which not match the actual platform?

Please give more information about how did you get the binary, and what a platform you run.

**Comment by yanglfyangl1978** [comment]
We didn't compiled by ourself, but use the release version. 

And also, it not happened always, when we reinstall the server, it works. it happened like 1/10 chance as we tested. 

Next are the info for binary and platform. 

> Description:    Ubuntu 18.04.1 LTS
> Release:        18.04
> Codename:       bionic
> 
> ClickHouse 18.14.10 with revision 54409

**Comment by alexey-milovidov** [comment]
`Illegal Instruction` may have one of the following reasons:
- the server does not support SSE 4.2 instruction set that is required to run official ClickHouse build;
- the server has malfunctioning filesystem, RAM or CPU and the machine code of clickhouse get corrupted.
