### ISSUE TITLE
When will the replicated table be triggered to check all parts?

### ISSUE THREAD

**Issue by xpleaf** [ClickHouse/ClickHouse#40515]
ClickHouse Version：

```
21.8.3.44
```

Written for my scenario is a large number of real time data, I found some time, plenty of ReplicatedMergeTreePartCheckThread thread will print the log below:

```
2022.08.22 21:18:59.851553 [ 90640 ] {} <Warning> test_gac.src_test_gac_new (ReplicatedMergeTreePartCheckThread): Checking part 20220820_474713_474726_1
2022.08.22 21:18:59.880882 [ 90640 ] {} <Warning> test_gac.src_test_gac_new (ReplicatedMergeTreePartCheckThread): Checking if anyone has a part 20220820_474713_474726_1 or covering part.
2022.08.22 21:18:59.974659 [ 90640 ] {} <Warning> test_gac.src_test_gac_new (ReplicatedMergeTreePartCheckThread): Found parts with the same min block and with the same max block as the missing part 20220820_474713_474726_1. Hoping that it will eventually appear as a result of a merge.
```

At this time, according to the monitoring, the active part of the corresponding data table has increased from hundreds to tens of thousands (my table has a large amount of data, about 100TB for a single replica, partitioned by day), which brings great pressure to the cluster at this time.
<img width="599" alt="1 ClickHouse checking part问题" src="https://user-images.githubusercontent.com/14944242/186100202-cd1b4906-2ce4-4d57-9bc6-fee15cb039ad.png">

And sometimes, it seems, this happens even when no data is being written.

It would be interesting to know under what circumstances ClickHouse triggers this checking mechanism, and if all parts of the table are checked and active Parts are generated?

I would appreciate it very much!

@den-crane @kssenii

**Comment by den-crane** [comment]
21.8 is obsolete. Upgrade to 22.8.

Probably you need to increase background_fetches_pool_size

```
 cat /etc/clickhouse-server/users.d/background_fetches_pool_size.xml
<?xml version="1.0"?>
<yandex>
    <profiles>
        <default>
            <background_fetches_pool_size>32</background_fetches_pool_size>
        </default>
    </profiles>
</yandex>
````

**Comment by xpleaf** [comment]
Thanks @den-crane
