### ISSUE TITLE
Self-extracting: possible race condition on decompression.

### ISSUE THREAD

**Issue by yakov-olkhovskiy** [ClickHouse/ClickHouse#40547]
**Describe the unexpected behaviour**
When compressed clickhouse started multiple times it is possible (and maybe quite probable) that some of them will end up with errors. It happens due to the fact that decompression process is trying to manipulate files in order to substitute compressed clickhouse with decompressed and run it.
This issue can affect CI environment leading to seemingly unrelated to PR tests failures.

**How to reproduce**
Run compressed clickhouse multiple times.

**Expected behavior**
No errors related to decompression and process startup.

**Error message and/or stacktrace**
Various - depends on the clashing stages of decompression process.

**Comment by yakov-olkhovskiy** [comment]
**Proposed solution:**
Compressed executable should run as a singleton process based on physical file on the disk.

**Proposed implementation:**
On startup compressed executable should create and lock /var/run/clickhouse.decompression.\<inode\>.lock file, where \<inode\> is an inode of this executable itself acquired from /process/self/maps - by this means lock is per physical executable on  the disk. Lock acquisition should be blocking. Upon lock acquisition stat should be acquired from executable's file name and inode should be compared with one acquired previously - if equal (which means no extraction yet performed) then proceed with extraction and further execv of extracted, else (which means extraction was already performed) - just proceed with execv of extracted.

**Comment by Felixoid** [comment]
The path `/var/run` is a bad option, since usually is not accessible by non-privileged users. It rather should be `/tmp/${HASH_VALUE}.lock`, where `$HASH_VALUE` is already pre-calculated for `clickhouse` binary and available as result of `clickhouse hash-binary` command.

**Comment by yakov-olkhovskiy** [comment]
Agree on path. Regarding file name - it should be unique on physical file - i.e. identical copies should not interfere in the first place, and the second issue - lock file is created before decompression - we just can't run clickhouse yet...
