### ISSUE TITLE
Join algorithm - auto with parallel_hash

### ISSUE THREAD

**Issue by royxact** [ClickHouse/ClickHouse#40544]
Hi,

Is there a way to combine 'parallel_hash' with 'auto' as join_algorithm?
So we try parallel_hash, and if out of RAM we fallback to partial_merge or full_sort_merge?

Thanks!

**Comment by den-crane** [comment]
you can set `set join_algorithm = 'parallel_hash, auto';`

**Comment by den-crane** [comment]
or `set join_algorithm = 'parallel_hash, partial_merge, full_sort_merge';

**Comment by den-crane** [comment]
it's just an example
