### ISSUE TITLE
 lightweight delete make the clickhouse become almost unresponsive.

### ISSUE THREAD

**Issue by WillMeng** [ClickHouse/ClickHouse#40563]
ClickHouse server version 22.8.1.2097 (official build).

**The table system.mutations** where is done=0, column "latest_fail_reason" is "Code: 241. DB::Exception: Memory limit (total) exceeded: would use 28.14 GiB (attempt to allocate chunk of 4198784 bytes), maximum: 28.13 GiB. OvercommitTracker decision: Memory overcommit isn't used. Waiting time or overcommit denominator are set to zero.: while executing 'FUNCTION equals(conver_id : 1, '1ad4506652e82b216014286daa4c65e8' :: 23922) -> equals(conver_id, '1ad4506652e82b216014286daa4c65e8') UInt8 : 23921'. (MEMORY_LIMIT_EXCEEDED) (version 22.8.1.2097 (official build))"

**column "cmd"** is "UPDATE _row_exists = 0 WHERE ((data_date = '2022-07-29') AND (chan_pub_id = '69496') AND (conver_id = '7097f185a3e915a301dfc4f5f79501c3')) OR ((data_date = '2022-07-29') AND (chan_pub_id = '69496') AND (conver_id = 'b774b199a1300d907a862e12c28da53b')) OR ((data_date = '2022-07-29') AND (chan_pub_id = '69496') AND (conver_id = 'ab179817007ae6382d53b6571b3e6516')) OR ((data_date = '2022-07-29') AND (chan_pub_id = '69496') AND (conver_id = 'bb6be3404099a8ae4e35204a381ca899')) OR ((data_date = '2022-07-29') AND (chan_pub_id = '69496') AND (conver_id = 'd7ab1463549f1c56d99e1fb68f584c62')) OR ((data_date = '2022-07-29') AND (chan_pub_id = '69496') AND (conver_id = 'a53c8eeb1707001736cd210e61e4cdd1')) OR ((data_date = '2022-07-29') AND (chan_pub_id = '69496') AND (conver_id = 'b8c8b08c55321e1fd4624bffc0adb87b')) OR ((data_date = '2022-07-29') AND (chan_pub_id = '69496') AND (conver_id = 'a2ad90472ca44fe020dfe83e0e280561')) OR ((data_date = '2022-08-21') AND (chan_pub_id = '1086927') AND (conver_id = '953a498c731c3ccbd423726d8414d6c8')) OR ((data_date = '2022-08-21') AND (chan_pub_id = '1086927') AND (conver_id = 'd215fed835aff5edacea9ed5b46e0760')) OR ((data_date = '2022-08-21') AND (chan_pub_id = '1086927') AND (conver_id = 'c857ecb322e6863852eb1d4aef5c66a8')) OR ((data_date = '2022-08-21') AND (chan_pub_id = '1086927') AND (conver_id = 'f0a921da532460c38b7538a9aa77e8bf')) OR ((data_date = '2022-08-21') AND (chan_pub_id = '1086927') AND (conver_id = 'bbad0d461980da6b7def032684dd50fc')) OR ((data_date = '2022-08-21') AND (chan_pub_id = '1086927') AND (conver_id = 'f8d1a0d2b26f32a58dc512b29e0961b1')) OR ((data_date = '2022-08-21') AND (chan_pub_id = '1086927') AND (conver_id = '16a7a181a7f687b52a7ce73c6837cd18')) OR ((data_date = '2022-08-21') AND (chan_pub_id = '1086927') AND (conver_id = 'fce7f3d4cf58b67067d188a73a9d2027')) OR ((data_date = '2022-07-29') AND (chan_pub_id = '1077252') AND (conver_id = '900ccbc715c72b2ed6337cda9e8211ce')) OR ((data_date = '2022-07-29') AND (chan_pub_id = '1077252') AND (conver_id = '42fb"

**error log :** 2022.08.24 11:50:20.465036 [ 1740 ] {d683e831-c75c-4ba1-8a97-75b02900cb44::20220805_307_307_0_5816} <Error> MutatePlainMergeTreeTask: Code: 241. DB::Exception: Memory limit (total) exceeded: would use 28.14 GiB (attempt to allocate chunk of 4198560 bytes), maximum: 28.13 GiB. OvercommitTracker decision: Memory overcommit isn't used. Waiting time or overcommit denominator are set to zero.: while executing 'FUNCTION equals(conver_id : 1, 'd9522f1d6bc92dc1b07f2d9cd794978a' :: 10351) -> equals(conver_id, 'd9522f1d6bc92dc1b07f2d9cd794978a') UInt8 : 10350'. (MEMORY_LIMIT_EXCEEDED) (version 22.8.1.2097 (official build))
2022.08.24 11:50:23.138772 [ 1740 ] {d683e831-c75c-4ba1-8a97-75b02900cb44::20220805_307_307_0_5816} <Error> virtual bool DB::MutatePlainMergeTreeTask::executeStep(): Code: 241. DB::Exception: Memory limit (total) exceeded: would use 28.14 GiB (attempt to allocate chunk of 4198560 bytes), maximum: 28.13 GiB. OvercommitTracker decision: Memory overcommit isn't used. Waiting time or overcommit denominator are set to zero.: while executing 'FUNCTION equals(conver_id : 1, 'd9522f1d6bc92dc1b07f2d9cd794978a' :: 10351) -> equals(conver_id, 'd9522f1d6bc92dc1b07f2d9cd794978a') UInt8 : 10350'. (MEMORY_LIMIT_EXCEEDED), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa38beba in /usr/bin/clickhouse
1. DB::Exception::Exception<char const*, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, long&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string_view<char, std::__1::char_traits<char> > >(int, fmt::v8::basic_format_string<char, fmt::v8::type_identity<char const*>::type, fmt::v8::type_identity<char const*>::type, fmt::v8::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::type, fmt::v8::type_identity<long&>::type, fmt::v8::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::type, fmt::v8::type_identity<std::__1::basic_string_view<char, std::__1::char_traits<char> > >::type>, char const*&&, char const*&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, long&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, std::__1::basic_string_view<char, std::__1::char_traits<char> >&&) @ 0xa37e539 in /usr/bin/clickhouse
2. MemoryTracker::allocImpl(long, bool, MemoryTracker*) @ 0xa37df1e in /usr/bin/clickhouse
3. MemoryTracker::allocImpl(long, bool, MemoryTracker*) @ 0xa37d968 in /usr/bin/clickhouse
4. MemoryTracker::allocImpl(long, bool, MemoryTracker*) @ 0xa37d968 in /usr/bin/clickhouse
5. void DB::PODArrayBase<1ul, 4096ul, Allocator<false, false>, 15ul, 16ul>::alloc<>(unsigned long) @ 0xa401cbb in /usr/bin/clickhouse
6. ? @ 0xe5f1544 in /usr/bin/clickhouse
7. DB::FunctionComparison<DB::EqualsOp, DB::NameEquals>::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0xe5d10b1 in /usr/bin/clickhouse
8. DB::FunctionToExecutableFunctionAdaptor::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0xcb0514e in /usr/bin/clickhouse

**Comment by WillMeng** [comment]
@zhangjmruc Hi, please review above issue, thank you very much

**Comment by zhangjmruc** [comment]
Copied more descriptions from lightweight delete PR:
Hi, We had try out this feature at first time. We found those problem:

SELECT COUNT() FROM system.mutations WHERE is_done = 0, The result is 92568, and read timed out(30 seconds) at often
The destination table become so slow when read it, and read timed out at often.
Our table schema like this :
`CREATE TABLE default.custom_conversion_day_details
(

`chan_pub_id` Int64,

`channel_id` Int32,

`publisher_id` Int32,

`pub_account_id` Int64,

`pub_account_name` String,

`pub_campaign_id` Int64,

`pub_campaign_name` String,

`pub_adgroup_id` Int64,

`pub_adgroup_name` String,
`data_date` Date)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(data_date)
PRIMARY KEY chan_pub_id
ORDER BY chan_pub_id
SETTINGS min_bytes_for_wide_part = '100M',
index_granularity = 8192;`

**Comment by davenger** [comment]
@WillMeng looks like you are doing deletes like this:
```
DELETE WHERE
 ((data_date = '2022-07-29') AND (chan_pub_id = '69496') AND (conver_id = '7097f185a3e915a301dfc4f5f79501c3')) OR
 ((data_date = '2022-07-29') AND (chan_pub_id = '69496') AND (conver_id = 'b774b199a1300d907a862e12c28da53b')) OR
 ...
```
Could you please tell how many conditions ```((data_date = A) AND (chan_pub_id = B) AND (conver_id = C))``` do you have in one query and how many query like this do you do?

**Comment by WillMeng** [comment]
> 
one query have one thousand conditions, and 10 similar query executed at one time. Thanks

**Comment by WillMeng** [comment]
> @WillMeng looks like you are doing deletes like this:
> 
> ```
> DELETE WHERE
>  ((data_date = '2022-07-29') AND (chan_pub_id = '69496') AND (conver_id = '7097f185a3e915a301dfc4f5f79501c3')) OR
>  ((data_date = '2022-07-29') AND (chan_pub_id = '69496') AND (conver_id = 'b774b199a1300d907a862e12c28da53b')) OR
>  ...
> ```
> 
> Could you please tell how many conditions `((data_date = A) AND (chan_pub_id = B) AND (conver_id = C))` do you have in one query and how many query like this do you do?

one query have one thousand conditions, and 10 similar query executed at one time. Thanks

**Comment by davenger** [comment]
Could you please provide some more info?
1. the schema of the table
2. how many parts does it have and that are their sizes in rows and bytes:
```
SELECT name, part_type, rows, bytes_on_disk, data_compressed_bytes, data_uncompressed_bytes
FROM system.parts
WHERE database=currentDatabase() and table=_TABLE_NAME_ and active;
```

**Comment by davenger** [comment]
Also, do you ```SET mutations_sync=2;``` when you do deletes?

**Comment by WillMeng** [comment]
> Also, do you `SET mutations_sync=2;` when you do deletes?

No, I write sql like this: delete from tableA where xxx

**Comment by zhangjmruc** [comment]
"one query have one thousand conditions, and 10 similar query executed at one time. Thanks"
"Memory limit (total) exceeded: would use 28.14 GiB (attempt to allocate chunk of 4198560 bytes), maximum: 28.13 GiB."

@WillMeng The failure reason for your deletes is that TOTAL memory limit exceeded. Therefore, you cannot execute 10 queries at one time due to the memory limit. With the "mutations_sync = 2; ", the delete is executed synchronously.

To avoid the memory limit exceeded exception, you can try with `SET mutations_sync=2;` before you do deletes. And also reduce the concurrent query count.  

max_memory_usage_for_user - Maximum memory usage for processing all concurrently running queries for the user. Zero means unlimited.

**Comment by WillMeng** [comment]
> 

Thanks. We had try out above 2 way, it works well until now. We will continuous testing this feature.

**Comment by WillMeng** [comment]
> "one query have one thousand conditions, and 10 similar query executed at one time. Thanks" "Memory limit (total) exceeded: would use 28.14 GiB (attempt to allocate chunk of 4198560 bytes), maximum: 28.13 GiB."
> 
> @WillMeng The failure reason for your deletes is that TOTAL memory limit exceeded. Therefore, you cannot execute 10 queries at one time due to the memory limit. With the "mutations_sync = 2; ", the delete is executed synchronously.
> 
> To avoid the memory limit exceeded exception, you can try with `SET mutations_sync=2;` before you do deletes. And also reduce the concurrent query count.
> 
> `max_memory_usage_for_user - Maximum memory usage for processing all concurrently running queries for the user. Zero means unlimited.`

Thanks. We had try out above 2 way, it works well until now. We will continuous testing this feature.

**Comment by WillMeng** [comment]
> @WillMeng do you also have `SETTINGS min_bytes_for_wide_part = '100M',` on the table? Could you please provide the info on how many part the table has, how big they are and if they are Wide or Compact:
> 
> ```
> SELECT name, part_type, rows, bytes_on_disk, data_compressed_bytes, data_uncompressed_bytes
> FROM system.parts
> WHERE database=currentDatabase() and table=_TABLE_NAME_ and active;
> ```
> 
> I suspect that your table might have many Compact parts because and LWD currently works in sub-optimal way with them, because it rewrites the whole Compact part data file when updating _row_exists column. You can try decrease the value of min_bytes_for_wide_part to make parts Wide so that columns are stored in separate files.

Thanks reply. Our clickhouse has many many tables and partitions, if we do not use min_bytes_for_wide_part, then trigger centos 7 inode threshold, so our most of the tables used min_bytes_for_wide_part=100M.

**Comment by filimonov** [comment]
> SELECT COUNT() FROM system.mutations WHERE is_done = 0, The result is 92568, and read timed out(30 seconds) at often
> The destination table become so slow when read it, and read timed out at often.

It's a known issue of the current implementation. p. 4 there: https://github.com/ClickHouse/ClickHouse/issues/39870

**Comment by filimonov** [comment]
@davenger maybe we should still not name those 'lightweight delete' a real 'delete'? It's still too heavy... And as you see people think that since 'real' delete exists - it's ok to use them very aggressively.

> If we will name it a usual DELETE - it will not sound like something you should be careful with. DELETEs for all RDBMs are light operations, and you can have a lot of them per sec.
> ... 
> But may be it would be better to still call it `alter` (mayby `ALTER table LIGHTWEIGHT DELETE ...` like in the PR)

**Comment by filimonov** [comment]
Also when you have a lot of (unfinished) mutations clickhouse tries to execute all of them at once by merging where conditions of the mutations. Sometimes the final (merged) where condition is superheavy / slow / even require too big AST.
