### ISSUE TITLE
Potential Memory Leak Issue

### ISSUE THREAD

**Issue by Ankk98** [ClickHouse/ClickHouse#40566]
**Describe the unexpected behavior**
Memory usage of our clickhouse server keeps increasing slowly. Fixes after restart and then the same.

**Expected behavior**
The memory usage should remain constant as our load and queries are not changing.

**Error message and/or stack trace**
![screenshot-netdata blogvault net-2022 08 24-14_55_19](https://user-images.githubusercontent.com/24476799/186383328-82fbc9c6-65e0-4e0a-b57e-97d99cf83167.png)

**Additional context**
- We only have 2 tables in a single server.
- We use Merge Tree Engine (default).
- We have added skipping indexes with almost all default settings.
- We use HTTP interface
- DB version: version 22.1.3 revision 54455
- OS: Ubuntu 20 LTS
- The amount of data that we have is increasing.
- DB works fine with low ram usage after restart.

**Please advise**
- How can we debug why the ram usage keeps increasing?
- Any known memory leak issues?
- Can use of skipping index be a cause of this?

**Comment by rkozlo** [comment]
Firstly i recommend go through this commands  [who ate my memory](https://kb.altinity.com/altinity-kb-setup-and-maintenance/altinity-kb-who-ate-my-memory/). Lately i had problem with memory leak and it was because of hungry ttl with group by clause.

**Comment by den-crane** [comment]
@Ankk98 do you use Kafka engine or RabbitMq Engine?

**Comment by den-crane** [comment]
22.1.3  obsolete. Upgrade to 22.8 or 22.3

**Comment by Ankk98** [comment]
@den-crane
We do not use any of these. We have a rails application and a gem is being used which uses HTTP protocol.
Table engine is MergeTree.

**Comment by den-crane** [comment]
22.1.3 obsolete. Upgrade to 22.8 or 22.3

**Comment by alexey-milovidov** [comment]
> Any known memory leak issues?

No. I have production servers with ReplicatedMergeTree, the memory usage is mostly flat, only with occasional increases and decreases for heavy queries.

**Comment by alexey-milovidov** [comment]
![Screenshot_20220825_230006](https://user-images.githubusercontent.com/18581488/186767905-fa2a61ec-adce-4f51-92b6-40869c7b43dc.png)

**Comment by Ankk98** [comment]
# Memory usage sometime after restart
```
SELECT
    *,
    formatReadableSize(value)
FROM system.asynchronous_metrics
WHERE (metric LIKE '%Cach%') OR (metric LIKE '%Mem%')
ORDER BY metric ASC
FORMAT PrettyCompactMonoBlock

Query id: 6810ae10-26b0-472d-b13b-481cd60c89c3

┌─metric───────────────────────┬────────value─┬─formatReadableSize(value)─┐
│ CompiledExpressionCacheBytes │        16384 │ 16.00 KiB                 │
│ CompiledExpressionCacheCount │            2 │ 2.00 B                    │
│ MMapCacheCells               │            0 │ 0.00 B                    │
│ MarkCacheBytes               │   4445188960 │ 4.14 GiB                  │
│ MarkCacheFiles               │       172710 │ 168.66 KiB                │
│ MemoryCode                   │    438099968 │ 417.80 MiB                │
│ MemoryDataAndStack           │  56509165568 │ 52.63 GiB                 │
│ MemoryResident               │   8142278656 │ 7.58 GiB                  │
│ MemoryShared                 │    302489600 │ 288.48 MiB                │
│ MemoryVirtual                │  57398992896 │ 53.46 GiB                 │
│ OSMemoryAvailable            │ 125381455872 │ 116.77 GiB                │
│ OSMemoryBuffers              │    464240640 │ 442.73 MiB                │
│ OSMemoryCached               │  63897956352 │ 59.51 GiB                 │
│ OSMemoryFreePlusCached       │ 123518496768 │ 115.04 GiB                │
│ OSMemoryFreeWithoutCached    │  59620540416 │ 55.53 GiB                 │
│ OSMemorySwapCached           │      1982464 │ 1.89 MiB                  │
│ OSMemoryTotal                │ 135056728064 │ 125.78 GiB                │
│ UncompressedCacheBytes       │            0 │ 0.00 B                    │
│ UncompressedCacheCells       │            0 │ 0.00 B                    │
└──────────────────────────────┴──────────────┴───────────────────────────┘
```

# Memory usage few days after restart
```
SELECT
    *,
    formatReadableSize(value)
FROM system.asynchronous_metrics
WHERE (metric LIKE '%Cach%') OR (metric LIKE '%Mem%')
ORDER BY metric ASC
FORMAT PrettyCompactMonoBlock

Query id: 8084fd3e-292b-4460-8bb0-d77c49de1b7f

┌─metric───────────────────────┬────────value─┬─formatReadableSize(value)─┐
│ CompiledExpressionCacheBytes │        16384 │ 16.00 KiB                 │
│ CompiledExpressionCacheCount │            2 │ 2.00 B                    │
│ MMapCacheCells               │            0 │ 0.00 B                    │
│ MarkCacheBytes               │   5368708832 │ 5.00 GiB                  │
│ MarkCacheFiles               │       536477 │ 523.90 KiB                │
│ MemoryCode                   │    438099968 │ 417.80 MiB                │
│ MemoryDataAndStack           │  80659267584 │ 75.12 GiB                 │
│ MemoryResident               │  12773093376 │ 11.90 GiB                 │
│ MemoryShared                 │    300732416 │ 286.80 MiB                │
│ MemoryVirtual                │  81549447168 │ 75.95 GiB                 │
│ OSMemoryAvailable            │ 120727068672 │ 112.44 GiB                │
│ OSMemoryBuffers              │   1180016640 │ 1.10 GiB                  │
│ OSMemoryCached               │ 110598447104 │ 103.00 GiB                │
│ OSMemoryFreePlusCached       │ 118580293632 │ 110.44 GiB                │
│ OSMemoryFreeWithoutCached    │   7981846528 │ 7.43 GiB                  │
│ OSMemorySwapCached           │     36401152 │ 34.71 MiB                 │
│ OSMemoryTotal                │ 135056728064 │ 125.78 GiB                │
│ UncompressedCacheBytes       │            0 │ 0.00 B                    │
│ UncompressedCacheCells       │            0 │ 0.00 B                    │
└──────────────────────────────┴──────────────┴───────────────────────────┘
```

**Comment by den-crane** [comment]
@Ankk98 

>│ MemoryResident               │   8142278656 │ 7.58 GiB                  │
>
>│ MemoryResident               │  12773093376 │ 11.90 GiB                 │

It proofs nothing. It could be normal mark_cache behavior.

Execute `system drop mark cache` and check MemoryResident again.

**Comment by den-crane** [comment]
No valid info.

**Comment by hantaoliulinux** [comment]
@Ankk98 Did you finally solve your problem? Did you upgrade the version to solve it? Which version did you upgrade to?
