### ISSUE TITLE
How to recreate table(replicatedMergeTree) when a replica dies in Atomic database

### ISSUE THREAD

**Issue by lingpeng0314** [ClickHouse/ClickHouse#40564]
I have 3 replicas in a ClickHouse cluster
Server A died due to some unexpected reason and disk is broken.
But zk still have the metadata for this replica.

So how can i recreate the replica tables?

In old Ordinary database, i just `attach table XXX <table defination>` and works fine.
But in Atomic database, seems it is not possible because the ATTACH query above is not supported anymore.
So only one way left? delete the Replica A metadata in zk then execute CREATE query?

Indeed i didn't want to delete data in ZK because it is a critical operation.
So pls. help me!

`2022.08.23 13:19:32.477926 [ 6894 ] {39d7a19c-68c0-45d1-81ee-352148664872} <Error> executeQuery: Code: 80. DB::Exception: Incorrect ATTACH TABLE query for Atomic database engine. Use one of the following queries instead:
1. ATTACH TABLE appevent_v2;
2. CREATE TABLE appevent_v2 <table definition>;
3. ATTACH TABLE appevent_v2 FROM '/path/to/data/' <table definition>;
4. ATTACH TABLE appevent_v2 UUID '<uuid>' <table definition>;. (INCORRECT_QUERY) (version 22.7.1.2295 (official build)) (from [::ffff:10.207.22.241]:53906) (in query: attach table if not exists sherlockio.`appevent_v2` XXX), Stack trace (when copying this message, always include the lines below):
````

**Comment by den-crane** [comment]
The easiest way is to use `system drop replica deadreplica` from the live replica and after `create table` (the same as adding a new replica.
Another way https://kb.altinity.com/altinity-kb-setup-and-maintenance/recovery-after-complete-data-loss/
