### ISSUE TITLE
If stop merges when parts are merging, It is failed to detach stopped merging part and catch  exception

### ISSUE THREAD

**Issue by zhaojintaozhao** [ClickHouse/ClickHouse#40562]
If stop merges when parts are merging, It is failed to detach stopped merging part and catch  exception "Part xxx is currently participating in a background operation(mutation/merge), try again later. (PART_IS_TEMPORARILY_LOCKED)"

Hi all.
In my system, there are two shards and two replicas and use multi local disk.

The procedure is as follows:
1st, Create a ReplicatedMergeTree table on cluster.
2nd, Import data to the shard1 replica1 node.
3rd, Stop merges when parts are merging.
4th. Detach these stopped merging parts.
5th. It is failed to detach part and cache exception.

How to reproduce:
```
ClickHouse version: v22.3.6.5-lts
In shard1 replica1:
1st: Create table test on cluster '{cluster}' (key UInt32, value1 String, value2 String, value3 String) engine=ReplicatedMergeTree('/clickhouse/{shard}/test', '{replica}') order by key partition by (key % 2) 

2nd: Insert into test select * from generateRandom('key UInt32, value1 String, value2 String, value3 String') limit 100000.
Insert into test select * from generateRandom('key UInt32, value1 String, value2 String, value3 String') limit 2000000.
Insert into test select * from generateRandom('key UInt32, value1 String, value2 String, value3 String') limit 3000000
Insert into test select * from generateRandom('key UInt32, value1 String, value2 String, value3 String') limit 4000000
Insert into test select * from generateRandom('key UInt32, value1 String, value2 String, value3 String') limit 5000000

3rd: when parts are merging, execute this sql: "SYSTEM STOP MERGES";

4th. Alter table test detach part "0_0_0_0";

5th. It is failed to detach part and cache exception "Part 0_0_0_0 is currently participating in a background operation(mutation/merge), try again later. (PART_IS_TEMPORARILY_LOCKED)".
```
Do other friends have similar problems? How to avoid this problems?

**Comment by SaltTan** [comment]
Operations with parts are replicated (all replicas must perform them).
Even if merges are stopped on one replica they continue to run on other replicas.
You want to detach the part that might not exist anymore on other replicas.

**Comment by tavplubix** [comment]
Yes, it's expected behavior
