### ISSUE TITLE
Can `async_insert` be used with gRPC interface

### ISSUE THREAD

**Issue by alexvanolst** [ClickHouse/ClickHouse#40574]
Is it possible to use the `async_insert` setting (https://clickhouse.com/docs/en/operations/settings/settings/#async-insert) when doing inserts via gRPC?

The docs indicate that this "makes sense only for insertion over HTTP protocol" but I don't see why it would not make sense for inserts through gRPC. Currently I am aggregating large batches in my client, because otherwise throughput struggles but this is quite expensive, so the `async_insert` sounds like an appealing solution but I'd prefer not to have to switch to HTTP.

**Comment by alexey-milovidov** [comment]
No, only Native and HTTP protocols support async inserts.
