### ISSUE TITLE
Add precise Decimal division

### ISSUE THREAD

**Issue by zvonand** [ClickHouse/ClickHouse#40573]
Right now, `Decimal` devision (#30341, #38054) can cause some pain. 
It works fine, but with strict limitations -- e.g. we cannot divide Decimals that have scale more than half of max scale (#39600).

Currently used division has good speed -- in fact, we just make 1 division (expensive) and multiplication (not so expensive), but precision is poor. 

I suggest adding separate function (smth like `preciseDecimalDiv(a: Decimal, b: Decimal, prcsn: UInt8)` with user-defined result precision) for decimal division (alongside "usual" one).
Maybe even we can replace currently existing division by this more precise version, but it will be like 10 times slower (more division operations are to be made), and it may be unacceptable if you don't need high precision.
That's why I suggest having 2 separate functions.

**Comment by filimonov** [comment]
> but it will be like 10 times slower (more division operations are to be made)

Should it be?

SQL Server: 

https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2005/ms190476(v=sql.90)?redirectedfrom=MSDN 
https://www.sqlservercentral.com/forums/topic/decimal-truncation-in-division

Python
https://www.digitalocean.com/community/tutorials/python-decimal-division-round-precision


http://sqlfiddle.com/#!9/3d854a/1
http://sqlfiddle.com/#!18/57020a/1

**Comment by zvonand** [comment]
@filimonov 
Decimal division with controlled scale implicitly involves multple divisions (see "Controllling Precision for single operation" in [link you provided](https://www.digitalocean.com/community/tutorials/python-decimal-division-round-precision)). We can't get required precision operation w/o either using multiple division operands or moving to wider data types (e.g. Int128 -> Int256, which itself can be pain)

**Comment by zvonand** [comment]
Currently working on this

**Comment by UnamedRus** [comment]
```
SELECT CAST('10', 'Decimal(10, 0)') / CAST('20', 'Decimal(10, 0)') AS result

┌─result─┐
│      0 │
└────────┘
```

It's not obvious for people.

**Comment by zvonand** [comment]
@UnamedRus well, it's like C++ does: `int` / `int` -> `int`. What can be more obvious?

**Comment by UnamedRus** [comment]
For example mysql 5.7, 8.0

```
SELECT CAST('10' as Decimal(10, 0)) / CAST('20' as Decimal(10, 0)) AS result


0.5000
```

**Comment by UnamedRus** [comment]
```
SELECT divideDecimal(CAST('10', 'Decimal(10, 0)'), CAST('20', 'Decimal(10, 0)'), 10) AS result

┌─result─┐
│    0.5 │
└────────┘
```
