### ISSUE TITLE
insert data loss

### ISSUE THREAD

**Issue by yanjunyich** [ClickHouse/ClickHouse#40596]
make one replicatedMergeTree cluster table  , then execute sql : insert into XXX_VIEW values (),(),(),(),(),(),(),(),(),()
sometime insert  10  data , then excute query  select * from XXX_VIEW  only find 5 data,loss 5 data
sometime insert same data again (change a field data in every  data) ,then excute query select * from XXX_VIEW  can find all the new 10 data
![f74407b000faa174478b28e8f9e8470](https://user-images.githubusercontent.com/112045175/186563168-4843b588-1409-4e1c-b2c3-87d93f29b682.jpg)
![c8030a67d454ce172b4293d606fce93](https://user-images.githubusercontent.com/112045175/186563206-a2953280-5418-4d50-a6a1-837ec811d740.jpg)
![fd9768143464575e651c2479ee08097](https://user-images.githubusercontent.com/112045175/186563218-05fff244-e635-4a22-9225-e33c680c99c9.jpg)

**Comment by den-crane** [comment]
read this https://kb.altinity.com/altinity-kb-schema-design/insert_deduplication/

**Comment by alexey-milovidov** [comment]
Your photos have moire: https://en.wikipedia.org/wiki/Moir%C3%A9_pattern

**Comment by yanjunyich** [comment]
thans let me see see
