### ISSUE TITLE
22.8.2.11 sql filter exception

### ISSUE THREAD

**Issue by xujinlong0314** [ClickHouse/ClickHouse#40599]
> Make sure to check documentation https://clickhouse.com/docs/en/ first. If the question is concise and probably has a short answer, asking it in Telegram chat https://telegram.me/clickhouse_en is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

> If you still prefer GitHub issues, remove all this text and ask your question here.

sql【1】:  
`select count()
from (
         SELECT event_dt
         FROM (select event_dt, 403 AS event_id
               from (
                        select event_dt
                        from tba as tba
                        where event_id = 9
                          and ((tba.event_dt >= 20220822 and tba.event_dt <= 20220822))
                        )) tba
         WHERE tba.event_dt >= 20220822
           and tba.event_dt <= 20220822
         );`

sql【2】:
`select count()
from (
         SELECT event_dt
         FROM (select event_dt, 403 AS event_id
               from (
                        select event_dt
                        from tba as tba
                        where event_id = 9
                          and ((tba.event_dt >= 20220822 and tba.event_dt <= 20220822))
                        )) tba
         WHERE tba.event_dt >= 20220822
           and tba.event_dt <= 20220822
           and event_id = 403
         );`

why sql【2】result less data

**Comment by den-crane** [comment]
Clickhouse version?

Do you get a right result If you execute this?

```
select count() from ( SELECT event_dt FROM (select event_dt, 403 AS event_id from ( select event_dt from tba as tba where event_id = 9 and ((tba.event_dt >= 20220822 and tba.event_dt <= 20220822)) )) tba WHERE tba.event_dt >= 20220822 and tba.event_dt <= 20220822 and event_id = 403 )
settings enable_optimize_predicate_expression=0, allow_experimental_projection_optimization=0;
```

**Comment by xujinlong0314** [comment]
> 
The problem still exists. I think it is a bug because there is no problem in 22.3

**Comment by xujinlong0314** [comment]
> Clickhouse version?
> 
> Do you get a right result If you execute this?
> 
> ```
> select count() from ( SELECT event_dt FROM (select event_dt, 403 AS event_id from ( select event_dt from tba as tba where event_id = 9 and ((tba.event_dt >= 20220822 and tba.event_dt <= 20220822)) )) tba WHERE tba.event_dt >= 20220822 and tba.event_dt <= 20220822 and event_id = 403 )
> settings enable_optimize_predicate_expression=0, allow_experimental_projection_optimization=0;
> ```
The problem still exists. I think it is a bug because there is no problem in 22.3

**Comment by den-crane** [comment]
ah, I missed a version in the title.

**Comment by den-crane** [comment]
Please share `show create table tba` , engine, order by, partittion by ...

**Comment by xujinlong0314** [comment]
> 



> show create table tba

I think you have found it. Do you still need  show create table tba .Looking forward to bug fixes

**Comment by xujinlong0314** [comment]
/ClickHouse/ClickHouse/issues/40595  You can also have a look at this if you are free

**Comment by den-crane** [comment]
22.7.4

```sql
 create table tba (event_id Int64, event_dt Int64) Engine =MergeTree order by event_id 
as select number%10, 20220822 from numbers(10);

SELECT count() FROM ( select event_dt, 403 AS event_id from tba ) tba
WHERE tba.event_dt >= 20220822 and tba.event_dt <= 20220822 and event_id = 403 ;
┌─count()─┐
│      10 │
└─────────┘
```

22.8.1.2097
```sql
 create table tba (event_id Int64, event_dt Int64) Engine =MergeTree order by event_id 
as select number%10, 20220822 from numbers(10);

SELECT count() FROM ( select event_dt, 403 AS event_id from tba ) tba
WHERE tba.event_dt >= 20220822 and tba.event_dt <= 20220822 and event_id = 403 ;
0 rows in set. Elapsed: 0.002 sec.
```

**Comment by den-crane** [comment]
```
set query_plan_optimize_primary_key=0;

SELECT count()
FROM
(
    SELECT
        event_dt,
        403 AS event_id
    FROM tba
) AS tba
WHERE (tba.event_dt >= 20220822) AND (tba.event_dt <= 20220822) AND (event_id = 403)

Query id: 2f1a0c96-3032-4fe7-a997-9eb39ddb5835

┌─count()─┐
│      10 │
└─────────┘

set query_plan_optimize_primary_key=1;

SELECT count()
FROM
(
    SELECT
        event_dt,
        403 AS event_id
    FROM tba
) AS tba
WHERE (tba.event_dt >= 20220822) AND (tba.event_dt <= 20220822) AND (event_id = 403)

Query id: c3671b38-0437-4fd5-b08b-af9be1e8d7e6

Ok.

0 rows in set. Elapsed: 0.001 sec.
```

@xujinlong0314 you need to disable query_plan_optimize_primary_key

**Comment by xujinlong0314** [comment]
> ```
> set query_plan_optimize_primary_key=0;
> 
> SELECT count()
> FROM
> (
>     SELECT
>         event_dt,
>         403 AS event_id
>     FROM tba
> ) AS tba
> WHERE (tba.event_dt >= 20220822) AND (tba.event_dt <= 20220822) AND (event_id = 403)
> 
> Query id: 2f1a0c96-3032-4fe7-a997-9eb39ddb5835
> 
> ┌─count()─┐
> │      10 │
> └─────────┘
> 
> set query_plan_optimize_primary_key=1;
> 
> SELECT count()
> FROM
> (
>     SELECT
>         event_dt,
>         403 AS event_id
>     FROM tba
> ) AS tba
> WHERE (tba.event_dt >= 20220822) AND (tba.event_dt <= 20220822) AND (event_id = 403)
> 
> Query id: c3671b38-0437-4fd5-b08b-af9be1e8d7e6
> 
> Ok.
> 
> 0 rows in set. Elapsed: 0.001 sec.
> ```
> 
> @xujinlong0314 you need to disable query_plan_optimize_primary_key

Compared with 22.3, will this configuration affect the performance of other queries

**Comment by den-crane** [comment]
>Compared with 22.3, will this configuration（disable query_plan_optimize_primary_key） affect the performance of other queries？

No, it will not
