### ISSUE TITLE
22.8.2 version   users.xml <host_regexp> abnormal

### ISSUE THREAD

**Issue by xujinlong0314** [ClickHouse/ClickHouse#40595]
> Make sure to check documentation https://clickhouse.com/docs/en/ first. If the question is concise and probably has a short answer, asking it in Telegram chat https://telegram.me/clickhouse_en is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

> If you still prefer GitHub issues, remove all this text and ask your question here.

`            <networks incl="networks" replace="replace">
                <ip>127.0.0.1</ip>
                <host_regexp>^abc00[1-6]$</host_regexp>
            </networks>
`
`clickhouse-client --host abc003
ClickHouse client version 22.8.2.11 (official build).
Connecting to abc003:9000 as user default.

If you have installed ClickHouse and forgot password you can reset it in the configuration file.
The password for default user is typically located at /etc/clickhouse-server/users.d/default-password.xml
and deleting this file will reset the password.
See also /etc/clickhouse-server/users.xml on the server where ClickHouse is installed.

Code: 516. DB::Exception: Received from abc003:9000. DB::Exception: default: Authentication failed: password is incorrect or there is no user with such name. (AUTHENTICATION_FAILED)`

`if use <host> no problem`

**Comment by den-crane** [comment]
Did it work before? Which version?

**Comment by xujinlong0314** [comment]
> Did it work before? Which version?

It was 22.3.10.22 before,

**Comment by alexey-milovidov** [comment]
@tavplubix should we revert https://github.com/ClickHouse/ClickHouse/pull/37827?

**Comment by tavplubix** [comment]
We can try to fix it and revert if it cannot be easily fixed. More information is needed:

@xujinlong0314, please find the corresponding message in server log:
```
zgrep -Fa "Authentication failed" /var/log/clickhouse-server/clickhouse-server.log
```
The message will look like:
```
2022.08.25 20:53:09.705658 [ 94932 ] {} <Error> Access(user directories): from: ::1, user: user_name: Authentication failed: Code: 192. DB::Exception: There is no user `user_name` in local directory. (UNKNOWN_USER), Stack trace (when copying this message, always include the lines below):
```
We are interested in the client address (in the example above it's here: `from: ::1`)

Then we need to know to which host names are this address resolved:
```
dig -x <that address>
python3 -c "import socket;print(socket.getnameinfo(('<that address>', 0), socket.NI_NAMEREQD));print(socket.gethostbyaddr('<that address>'))"
```
(output of both commands is required)

cc: @arthurpassos

**Comment by arthurpassos** [comment]
I have just tested a similar setup in my local environment.

```
157     IN      PTR     abc003.
abc003. IN A 192.168.0.157

arthur@arthur:~$ nslookup 192.168.0.157
157.0.168.192.in-addr.arpa	name = abc003.


arthur@arthur:~$ nslookup abc003
Server:		127.0.0.1
Address:	127.0.0.1#53

Name:	abc003
Address: 192.168.0.157


```

ClickHouse host config:
```
<yandex>
    <users>
        <test_dns>
            <password/>
            <networks>
                <host_regexp>^abc00[1-6]$</host_regexp>
            </networks>
            <profile>default</profile>
        </test_dns>
    </users>
</yandex>
```

Test:
```
arthur@arthur:~$ curl --interface 192.168.0.157 'http://127.0.0.1:8123/?query=SELECT+version()&user=test_dns'
22.9.1.1
```
The differences lie in `incl="networks" replace="replace"`. I am not sure what those refer to, but don't seem related. I am not using localhost, but doesn't seem related either.

Please let me know if I have missed anything @tavplubix @xujinlong0314

**Comment by xujinlong0314** [comment]
> We can try to fix it and revert if it cannot be easily fixed. More information is needed:
> 
> @xujinlong0314, please find the corresponding message in server log:
> 
> ```
> zgrep -Fa "Authentication failed" /var/log/clickhouse-server/clickhouse-server.log
> ```
> 
> The message will look like:
> 
> ```
> 2022.08.25 20:53:09.705658 [ 94932 ] {} <Error> Access(user directories): from: ::1, user: user_name: Authentication failed: Code: 192. DB::Exception: There is no user `user_name` in local directory. (UNKNOWN_USER), Stack trace (when copying this message, always include the lines below):
> ```
> 
> We are interested in the client address (in the example above it's here: `from: ::1`)
> 
> Then we need to know to which host names is this address resolved to:
> 
> ```
> dig -x <that address>
> python3 -c "import socket;print(socket.getnameinfo(('<that address>', 0), socket.NI_NAMEREQD));print(socket.gethostbyaddr('<that address>'))"
> ```
> 
> (output of both commands is required)
> 
> cc: @arthurpassos


`<networks incl="networks" replace="replace">
	<ip>127.0.0.1</ip>
	<host_regexp>^ck[1-9]$</host_regexp>
</networks>
`

`cat /etc/hosts
10.0.7.18 ck1
10.0.7.19 ck2
10.0.7.20 ck3`

`2022.08.29 09:25:57.586934 [ 3179 ] {} <Error> Access(user directories): from: 10.0.7.18, user: default: Authentication failed: Code: 195. DB::Exception: Connections from 10.0.7tack trace (when copying this message, always include the lines below):
`

`python -c "import socket;print(socket.getnameinfo(('10.0.7.18', 0), socket.NI_NAMEREQD));print(socket.gethostbyaddr('10.0.7.18'))"
('ck1', '0')
('ck1', [], ['10.0.7.18'])`

`dig -x 10.0.7.18;
; <<>> DiG 9.11.4-P2-RedHat-9.11.4-9.P2.el7 <<>> -x 10.0.7.18
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 28784
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;18.7.0.10.in-addr.arpa.		IN	PTR
;; AUTHORITY SECTION:
10.in-addr.arpa.	10800	IN	SOA	localhost. nobody.invalid. 1 3600 1200 604800 10800
;; Query time: 1 msec
;; SERVER: 10.0.1.146#53(10.0.1.146)
;; WHEN: Mon Aug 29 09:35:05 CST 2022
;; MSG SIZE  rcvd: 110`

**Comment by tavplubix** [comment]
> `cat /etc/hosts 10.0.7.18 ck1 10.0.7.19 ck2 10.0.7.20 ck3`

This is really important, better to mention things like that when creating an issue.

So `getnameinfo` respects `/etc/hosts` and `dig` does not. Maybe `c-ares` does not respect it too for some reason (but it [should](https://github.com/c-ares/c-ares/blob/de042a65f492f8a8b0a10bf21494623b9ac345fd/src/lib/ares_gethostbyaddr.c#L169)). Please also share the content of `/etc/resolv.conf`.

**Comment by arthurpassos** [comment]
> > `cat /etc/hosts 10.0.7.18 ck1 10.0.7.19 ck2 10.0.7.20 ck3`
> 
> This is really important, better to mention things like that when creating an issue.
> 
> So `getnameinfo` respects `/etc/hosts` and `dig` does not. Maybe `c-ares` does not respect it too for some reason (but it [should](https://github.com/c-ares/c-ares/blob/de042a65f492f8a8b0a10bf21494623b9ac345fd/src/lib/ares_gethostbyaddr.c#L169)). Please also share the content of `/etc/resolv.conf`.

`c-ares` does query `/etc/hosts`. It fills out the `hostent::h_name` member, but we are checkin only for `hostent::h_aliases` in the resolver [callback](https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/CaresPTRResolver.cpp#L22).

There are a couple of ways to approach this, each with its pros and cons:

1. Append `hostent::h_name` to the return vector if it's not null. It would solve the problem, but could cause duplicates.
2. Use a `std::unordered_set` instead of a `vector` to avoid duplicates. It could add some extra overhead, but probably fine to do so.
3. Understand all the inner workings and small details of the `c-ares` library to properly handle corner cases. This is time consuming and prone to future problems in case the inner workings of the library change, we should strive to rely on the public interface and documentation.
4. Skip the first alias in case `hostent::h_name` is not null. Dangerous because we do not know if the first entry will always match the `h_name`

I'll publish a PR with approach 2 and we can discuss it there.
