### ISSUE TITLE
clickhouse keeper Keeper server Start Error

### ISSUE THREAD

**Issue by jiangbiao910** [ClickHouse/ClickHouse#40604]
My clickhouse-keeper.xml is
`<?xml version="1.0"?>
<clickhouse>
<listen_host>0.0.0.0</listen_host>
<keeper_server>
    <tcp_port>9181</tcp_port>
    <server_id>3</server_id>
    <four_letter_word_allow_list>*</four_letter_word_allow_list>
    <log_storage_path>/app/clickhouse/coordination/log</log_storage_path>
    <snapshot_storage_path>/app/clickhouse/coordination/snapshots</snapshot_storage_path>

    <coordination_settings>
        <operation_timeout_ms>20000</operation_timeout_ms>
        <session_timeout_ms>60000</session_timeout_ms>
        <raft_logs_level>error</raft_logs_level>
    </coordination_settings>

    <raft_configuration>
        <server>
            <id>1</id>
            <hostname>dev-bigdatadataplatform-node-29</hostname>
            <port>9444</port>
        </server>
        <server>
            <id>2</id>
            <hostname>dev-dataplatform-node-30</hostname>
            <port>9444</port>
        </server>
        <server>
            <id>3</id>
            <hostname>dev-dataplatform-node-22</hostname>
            <port>9444</port>
        </server>
    </raft_configuration>
</keeper_server>

</clickhouse>
`
and I start the Keeper by `sudo -u clickhouse clickhouse-keeper --config /etc/clickhouse-server/keeper.xml `

But Error as:

session 76 failed to read rpc header from socket ::ffff:10.136.11.51:40650 due to error 2, End of file, ref count 1
session 77 failed to read rpc header from socket ::ffff:10.136.11.51:40702 due to error 2, End of file, ref count 1
Got exception processing session #217949904738255102: Code: 210. DB::NetException: I/O error: Broken pipe, while writing to socket (10.136.11.43:41782). (NETWORK_ERROR), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa38beba in /usr/bin/clickhouse
1. DB::WriteBufferFromPocoSocket::nextImpl() @ 0x1435c2dc in /usr/bin/clickhouse
2. Coordination::ZooKeeperResponse::write(DB::WriteBuffer&) const @ 0x161fff3b in /usr/bin/clickhouse
3. DB::KeeperTCPHandler::runImpl() @ 0x15ab0377 in /usr/bin/clickhouse
4. Poco::Net::TCPServerConnection::start() @ 0x18a617b3 in /usr/bin/clickhouse
5. Poco::Net::TCPServerDispatcher::run() @ 0x18a62c2d in /usr/bin/clickhouse
6. Poco::PooledThread::run() @ 0x18c2d9c9 in /usr/bin/clickhouse
7. Poco::ThreadImpl::runnableEntry(void*) @ 0x18c2b242 in /usr/bin/clickhouse
8. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
9. __clone @ 0xfeb0d in /usr/lib64/libc-2.17.so

Requesting session ID for the new client
Received session ID 217949904738255103
Got exception processing session #217949904738255099: Code: 210. DB::NetException: I/O error: Broken pipe, while writing to socket (10.136.11.46:51836). (NETWORK_ERROR), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa38beba in /usr/bin/clickhouse
1. DB::WriteBufferFromPocoSocket::nextImpl() @ 0x1435c2dc in /usr/bin/clickhouse
2. Coordination::ZooKeeperResponse::write(DB::WriteBuffer&) const @ 0x161fff3b in /usr/bin/clickhouse
3. DB::KeeperTCPHandler::runImpl() @ 0x15ab0377 in /usr/bin/clickhouse
4. Poco::Net::TCPServerConnection::start() @ 0x18a617b3 in /usr/bin/clickhouse
5. Poco::Net::TCPServerDispatcher::run() @ 0x18a62c2d in /usr/bin/clickhouse
6. Poco::PooledThread::run() @ 0x18c2d9c9 in /usr/bin/clickhouse
7. Poco::ThreadImpl::runnableEntry(void*) @ 0x18c2b242 in /usr/bin/clickhouse
8. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
9. __clone @ 0xfeb0d in /usr/lib64/libc-2.17.so

Got exception processing session #217949904738255101: Code: 210. DB::NetException: I/O error: Broken pipe, while writing to socket (10.136.11.44:34648). (NETWORK_ERROR), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa38beba in /usr/bin/clickhouse
1. DB::WriteBufferFromPocoSocket::nextImpl() @ 0x1435c2dc in /usr/bin/clickhouse
2. Coordination::ZooKeeperResponse::write(DB::WriteBuffer&) const @ 0x161fff3b in /usr/bin/clickhouse
3. DB::KeeperTCPHandler::runImpl() @ 0x15ab0377 in /usr/bin/clickhouse
4. Poco::Net::TCPServerConnection::start() @ 0x18a617b3 in /usr/bin/clickhouse
5. Poco::Net::TCPServerDispatcher::run() @ 0x18a62c2d in /usr/bin/clickhouse
6. Poco::PooledThread::run() @ 0x18c2d9c9 in /usr/bin/clickhouse
7. Poco::ThreadImpl::runnableEntry(void*) @ 0x18c2b242 in /usr/bin/clickhouse
8. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
9. __clone @ 0xfeb0d in /usr/lib64/libc-2.17.so

Requesting session ID for the new client
Received session ID 217949904738255106
session 78 failed to read rpc header from socket ::ffff:10.136.11.51:40714 due to error 2, End of file, ref count 1
session 79 failed to read rpc header from socket ::ffff:10.136.11.51:40816 due to error 2, End of file, ref count 1
session 75 failed to read rpc header from socket ::ffff:10.136.11.52:47746 due to error 2, End of file, ref count 1

**Comment by e-mars** [comment]
hi @jiangbiao910 .
i see that the config for server 3 is included as an example.
Are you getting this on the other servers also?

This appears to be a network issue, this server has received packets on its defined port but looks like it cannot connect back to the servers that initiated the connection through the ephemeral ports.
Could you check to ensure that you can reach the other servers? 

thanks.

**Comment by jiangbiao910** [comment]
hi @e-mars  thank you for your help.
I try to modify  clickhouse-keeper.xml and set parameter larger，such as    `<session_timeout_ms>120000</session_timeout_ms>`
`<coordination_settings>
         <operation_timeout_ms>20000</operation_timeout_ms>
        <min_session_timeout_ms>500000</min_session_timeout_ms>
        <session_timeout_ms>120000</session_timeout_ms>
        <raft_logs_level>information</raft_logs_level>
        <election_timeout_lower_bound_ms>12000</election_timeout_lower_bound_ms>
        <election_timeout_upper_bound_ms>24000</election_timeout_upper_bound_ms>
        <dead_session_check_period_ms>10000</dead_session_check_period_ms>
        <heart_beat_interval_ms>10000</heart_beat_interval_ms>
    </coordination_settings>
`
after modify the xml ，it work seems normal.

**Comment by e-mars** [comment]
thanks for the update @jiangbiao910 .
appears to have been a perf issue then. timeouts being exceeded for keeper operations.
