### ISSUE TITLE
Ambiguous column exception when creating materialized view

### ISSUE THREAD

**Issue by wuzhe1234** [ClickHouse/ClickHouse#40605]
when I use following code to generate a materialized view.

**create materialized view stock_daily_adj_mv to stock_daily_adj 
as
select
    a.order_book_id as order_book_id
    , a.date as date
    , if(b.ex_cum_factor is null, 1.0, b.ex_cum_factor) as ex_cum_factor
    , a.open * ex_cum_factor as open
    , a.high * ex_cum_factor as high
    , a.low * ex_cum_factor as low
    , a.close * ex_cum_factor as close
    , a.prev_close * ex_cum_factor as prev_close
    , a.total_turnover as total_turnover 
    , a.volume / ex_cum_factor as volume
from
    stock_daily a
asof
left join stock_ex_factor b on
    a.order_book_id = b.order_book_id
    and a.date >= b.ex_date
order by
    a.order_book_id
    , a.date
settings join_use_nulls = 1**

I got a `DB::Exception: Ambiguous column in expression 'a.order_book_id = b.order_book_id' in JOIN ON section: While processing a.order_book_id = b.order_book_id.`

But if I just use the select part, it works perfectly. I was wondering if the materialized view support `join`?

**Comment by den-crane** [comment]
CH does not support aliases in materialized views (and views) https://github.com/ClickHouse/ClickHouse/issues/10894
