### ISSUE TITLE
Problem running integration test

### ISSUE THREAD

**Issue by dheerajathrey** [ClickHouse/ClickHouse#40612]
Hi, I am trying to contribute to clickhouse. 
I am trying to run integration test for test_storage_kafka following the documentation [at](https://github.com/ClickHouse/ClickHouse/tree/master/tests/integration) and I face the following issue
<pre>
Cannot start service zoo1: failed to create shim: OCI runtime create failed: runc create failed: unable to start container process: exec: "clickhouse-keeper": executable 
</pre>

Docker version
<pre>
Client:
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.2
 Git commit:        20.10.12-0ubuntu2~20.04.1
 Built:             Wed Apr  6 02:14:38 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
</pre>

Clickhouse version: 22.7.1.1

Command used for test: `pytest -k test_kafka_formats`

Sample stacktrace of the error: 
<pre>
2022-08-25 10:55:34 [ 815313 ] DEBUG : Stderr: (cluster.py:105, run_and_check)
2022-08-25 10:55:34 [ 815313 ] DEBUG : Stderr:ERROR: for zoo3  Cannot start service zoo3: failed to create shim: OCI runtime create failed: runc create failed: unable to start container process: exec: "clickhouse-keeper": executable file not found in $PATH: unknown (cluster.py:105, run_and_check)
2022-08-25 10:55:34 [ 815313 ] DEBUG : Stderr:compose.cli.main.exit_with_metrics: Encountered errors while bringing up the project. (cluster.py:105, run_and_check)
2022-08-25 10:55:34 [ 815313 ] DEBUG : Exitcode:1 (cluster.py:107, run_and_check)
</pre>

Going through the code, I realized that the issue is at  [docker_compose_keeper.yml](https://github.com/ClickHouse/ClickHouse/blob/master/docker/test/integration/runner/compose/docker_compose_keeper.yml) where three keeper containers zoo1, zoo2 and zoo3 are being launched using the image `clickhouse/integration-test` and with entrypoint  `clickhouse-keeper --config=/etc/clickhouse-keeper/keeper_config1.xml .....`.  And here `clickhouse-keeper` is not present in the newly created containers' paths.

From the documentation [here](https://github.com/ClickHouse/ClickHouse/tree/master/tests/integration#rebuilding-the-docker-containers), I see that `docker/test/integration/runner/Dockerfile` is the dockerfile that is used to build the image `clickhouse/integration-test`. When I launch a container locally using an image from this Dockerfile, I don't see clickhouse or clickhouse-keeper installed in it.

Am I doing something wrong here? Has the approach to do integration tests changed?
Please help me here.

**Comment by dheerajathrey** [comment]
@alexey-milovidov Hi, is this a bug or the approach to do integration tests is different?

**Comment by lincion** [comment]
I faced the same problem and solved by [https://github.com/ClickHouse/ClickHouse/pull/41143](url)
