### ISSUE TITLE
Minus function doesn't work with DataTypeDateTime64

### ISSUE THREAD

**Issue by HeenaBansal2009** [ClickHouse/ClickHouse#40626]
**Describe the unexpected behaviour**
Minus function doesn't work with DataTypeDateTime64
```
select now64(9,'UTC') - now64(9,'UTC') throws error
Code: 43. DB::Exception: Illegal types DateTime64(9, 'UTC') and DateTime64(9, 'UTC') of arguments of function minus: While processing now64(9, 'UTC') - now64(9, 'UTC'). (ILLEGAL_TYPE_OF_ARGUMENT) (version 22.8.1.1231 (official build))
```
`select now() - now() returns 0 `

Expected Behaviour.
Minus function should work with DataTypeDateTime64

**Comment by HeenaBansal2009** [comment]
I see that DataTypeDateTime64 is not in the TypeList of castType(), Hence castType return false and minus function tow exception for operands of type DataTypeDateTime64.
https://github.com/ClickHouse/ClickHouse/blob/master/src/Functions/FunctionBinaryArithmetic.h#L631

**Comment by alexey-milovidov** [comment]
Looks reasonable.

**Comment by HeenaBansal2009** [comment]
Any plans to support  in future ?

**Comment by den-crane** [comment]
@HeenaBansal2009  It's unclear what should be a result, seconds? 

You can use `fromUnixTimestamp64Nano(...) - fromUnixTimestamp64Nano(...)` if you need nanoseconds

**Comment by HeenaBansal2009** [comment]
> @HeenaBansal2009 It's unclear what should be a result, seconds?
> You can use `fromUnixTimestamp64Nano(...) - fromUnixTimestamp64Nano(...)` if you need nanoseconds

I am not looking for nanoseconds specifically  . 
I wanted to do something 
if datetIme64_1 - datetime64_2  > (5*24*3600)  seconds // do something.

**Comment by den-crane** [comment]
```
if toUInt32(datetIme64_1) - toUInt32(datetime64_2) > (5243600) seconds // do something.
```
