### ISSUE TITLE
Support manually snapshot for Keeper.

### ISSUE THREAD

**Issue by JackyWoo** [ClickHouse/ClickHouse#40621]
> (you don't have to strictly follow this form)

**Use case**

Support manually snapshot for Keeper.

**Describe the solution you'd like**

Throught 4lw commands, such as `csnp`.

**Comment by JackyWoo** [comment]
@alesapin @antonio2368 Wether the idea is ok, if not I will close the issue.

**Comment by antonio2368** [comment]
@JackyWoo it makes sense to me.
What about the snapshot after it, should it be after `snapshot_distance`, or should the snapshot creation after commits ignore the manually created one?

**Comment by JackyWoo** [comment]
The next snapshot will be created after `snapshot_distance `.

https://github.com/eBay/NuRaft/blob/e1a5fb43443fc9410e5e64d0f64b5eef4500986a/src/handle_commit.cxx#L499-L502
