### ISSUE TITLE
enable_positional_arguments converts fields into numbers

### ISSUE THREAD

**Issue by kolya7k** [ClickHouse/ClickHouse#40634]
enable_positional_arguments converts fields into numbers when using construction like `0 as data GROUP BY data`

```
CREATE TABLE `test`
(
	`id`  UInt32,
	`time` UInt32,
	INDEX `id` (`id`) TYPE set(0) GRANULARITY 3,
	INDEX `time` (`time`) TYPE minmax GRANULARITY 3
) ENGINE = MergeTree()
ORDER BY (`time`);

INSERT INTO `test` (`id`, `time`) VALUES (0, 1600000000), (1, 1600000000), (2, 1600000000), (3, 1600000000), (4, 1600000000), (5, 1600000000), (10, 1610000000), (11, 1610000000), (12, 1610000000), (13, 1610000000), (14, 1610000000), (20, 1620000000);

SELECT COUNT(*) as `value`, 0 as `data` FROM `test` GROUP BY `data` SETTINGS enable_positional_arguments=1;

DROP TABLE `test`;
```

SELECT will return
_Received exception from server (version 22.8.2):
Code: 43. DB::Exception: Received from localhost:9000. DB::Exception: Positional argument out of bounds: 0 (exprected in range [1, 2]. (ILLEGAL_TYPE_OF_ARGUMENT)_

Expected:
```
┌─value─┬─data─┐
│    12 │    0 │
└───────┴──────┘
```

**Comment by sharmadhiraj86** [comment]
I would like to contribute to solve this issue. So if possible, can you please assign this issue to me. @kolya7k

**Comment by sharmadhiraj86** [comment]
@kolya7k @den-crane @kssenii @Enmk @ludv1x

**Comment by sharmadhiraj86** [comment]
@kssenii Can you assign this issue to me please?

**Comment by alexey-milovidov** [comment]
This should be easy to solve.
We should recognize positional arguments before AST normalization.

```
SELECT 0 AS data ORDER BY data; -- here data is not a positional argument
SELECT 1 AS data ORDER BY 1; -- here 1 is a positional argument
```

@sharmadhiraj86 it might be not easy to find the exact place of code to solve this issue in the most natural way.
But if you want to try, it will be very appreciated.

**Comment by alexey-milovidov** [comment]
@sharmadhiraj86 This task is solved, you can look at the linked pull request for the solution.
