### ISSUE TITLE
when querying with like operator, don't use tokenbf index.

### ISSUE THREAD

**Issue by rfyiamcool** [ClickHouse/ClickHouse#40632]
![image](https://user-images.githubusercontent.com/3785409/186703931-31c06ed9-6178-4886-a8ed-f35af0b2aeb9.png)

I do not know why the index has no effect, the query speed is the same as before.

```
CREATE TABLE `pusher18-copy`
(
    `logging_idc` String ,
    `logging_host` String ,
    `logging_relative_index` Int64 ,
    `logging_create_time` DateTime ,
    `logging_instance_id` String ,
    `logging_json` String ,
    `logging_raw_data` String,
    ...
    INDEX raw_idx logging_raw_data TYPE tokenbf_v1(32000, 2, 0) GRANULARITY 2,
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(datetime)
ORDER BY datetime
TTL toDateTime(datetime) + toIntervalDay(14)
SETTINGS index_granularity = 8192, storage_policy = 'jbod_policy'
```

The sql query took 30 seconds.

![image](https://user-images.githubusercontent.com/3785409/186708461-5218d07b-af3f-4094-9575-c3c3cdffe208.png)

ck don't  use the tokenbf index when the sql contains like operator? 

![image](https://user-images.githubusercontent.com/3785409/186708749-21b2bb1f-ec3e-40eb-9858-d4c0f3afa6bc.png)

when query by hasToken(), speed of the query is fast.

![image](https://user-images.githubusercontent.com/3785409/186709718-c6b34563-d825-42ad-a647-d8651c7a59f3.png)

**Comment by alexey-milovidov** [comment]
LIKE operator cannot use the token index, because it searches for a substring inside a string without respect to tokenization.

You should either use the `hasToken` function or the `ngrambf` index.

**Comment by rfyiamcool** [comment]
😅  but hasToken() don't support multi string,  I have such a similar use requirement, what should I do ？ 

actual sql

```sql
select * from xxx where hasToken(xx, 'aa') and hasToken(xx, 'cc') and hasToken(xx, 'cc') and hasToken(xx, 'ddd')
```

expected sql

```sql
select * from xxx where hasToken(xx, 'aa bb - cc, ddd')
```

i want ck trim space and other invliad char when query with hasToken() .  😁

**Comment by alexey-milovidov** [comment]
@rfyiamcool there is no such function for now, so the only option is to prepare a query with multiple `hasToken` calls.

**Comment by srikanthccv** [comment]
@alexey-milovidov I am running into the same issue and realised it works well with `hasToken` but not with `LIKE` operator. What does it mean that `like`/`notLike` supported for `tokenbf_v1` in this table https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/mergetree/#functions-support? Since it's mentioned with `✔` I was expecting it uses the skip index but it didn't.

**Comment by alexey-milovidov** [comment]
@srikanthccv I don't know why it is marked as supported in the docs.
But another person connected with me in Slack and convinced me that it works if there are isolated tokens in between the LIKE condition. For example, it cannot work for `%Hello%` but can work for `% Hello!%`. I did not check that.
