### ISSUE TITLE
clickhouse-jdbc: clickhouseParser

### ISSUE THREAD

**Issue by dqrqtag** [ClickHouse/ClickHouse#40657]
clickhouse-jdbc version 0.3.2 not  support **use_metadata_cache**
error img:
![image](https://user-images.githubusercontent.com/112159638/186849471-1e58f9c2-c3f4-40a3-b01b-ba301958106a.png)
error info:
 If you believe the SQL is valid, please feel free to open an issue on Github with this warning and the following SQL attached.

**Comment by den-crane** [comment]
You have to open this issue in https://github.com/ClickHouse/clickhouse-jdbc
