### ISSUE TITLE
Cannot convert tuple with Decimal to JSON

### ISSUE THREAD

**Issue by lksv** [ClickHouse/ClickHouse#40656]
**Describe the unexpected behaviour**

JSON spec is quite clear that JSON numbers are unlimited size.  So I suppose Decimal128 should be supported.

**How to reproduce**

```sql
CREATE TABLE named_tuples2 (`a` Tuple(s String, i Int64, d Decimal(20,0))) ENGINE = Memory;

INSERT INTO named_tuples2 VALUES (('y', 10, 123456789012345)), (('x',-10,1));

SELECT a::JSON FROM named_tuples2
```

Getting error:
```
Received exception from server (version 22.7.3)
Code: 49. DB::Exception: Received from localhost:9000. DB::Exception: Cannot get data type of column Decimal128. (LOGICAL_ERROR)
```

**Expected behavior**

1. rows cloud be converted to JSON
2. it is surprising for me that the resulting type of smaller types (e.g. UInt64) is String. Better would be number. But documentation do not say anything so maybe it's a feature?

```
CREATE TABLE named_tuples (`a` Tuple(s String, i Int64)) ENGINE = Memory;
INSERT INTO named_tuples VALUES (('y', 10)), (('x',-10));
SELECT * FROM named_tuples;
┌─a─────────┐
│ ('y',10)  │
│ ('x',-10) │
└───────────┘
SELECT *::JSON FROM named_tuples;
┌─CAST(a, 'JSON')─────┐
│ {"i":"10","s":"y"}  │
│ {"i":"-10","s":"x"} │
└─────────────────────┘
```

**Additional info**

Query `SELECT '{"a": 12345678901234567123}'::JSON` works, but query with longer number `SELECT '{"a": 12345678901234567123456}'::JSON` does not (`Cannot parse object: While processing CAST('{"a": 12345678901234567123456}', 'JSON'). (INCORRECT_DATA)`)

**Comment by alexey-milovidov** [comment]
We are deprecating the JSON data type.
