### ISSUE TITLE
Why does not `JSONEachRowOutputFormat` validate UTF-8 sequences?

### ISSUE THREAD

**Issue by FrankChen021** [ClickHouse/ClickHouse#40654]
When exporting data from ClickHouse via URL engine in JSONEachRow format, we find that sometimes the exported data can't be deserialized by remote HTTP server because the data contains some invalid UTF-8 characters.

While looking throught the `JSONEachRowOutputFormat`, we find that it's intentionally designed to output what it receives and does not validate if the input is valid UTF-8 string sequences.

However, `JSONRowOutputFormat` and it's subclasses DO have the logic to valid input string and replace any non-UTF-8 characters into a valid UTF-8 byte sequence.

My question is why does `JSONEachRowOutputFormat` differ from `JSONRowOutputFormat` on the point of UTF-8 validation?
It does not make senses that these two have different behaviour.

**Comment by alexey-milovidov** [comment]
JSON, JSONCompact, and similar are "presentation" formats - they are designed to be consumed by JavaScript applications and browsers, but not designed for data storage, and don't support data import.

JSONEachRow is for storage/import/export, it is bidirectional, and designed to allow creating a dump and loading it back without losing any data.

But ClickHouse itself is charset agnostic, it supports all possible charsets and arbitrary bytes in Strings (while encouraging usage of [UTF-8 everywhere](https://utf8everywhere.org/)), and more importantly, the FixedString data type is specifically for binary data without encoding. Transforming everything to UTF-8 will lose data.

Nevertheless, let's:
- add a setting for UTF-8 validation for JSONEachRow, JSONCompactEachRow;
- make "presentation" JSON, JSONCompact formats suitable for data import, for completeness;

**Comment by FrankChen021** [comment]
Thank you for your explanation @alexey-milovidov  
Looking forward to the new feature.
