### ISSUE TITLE
After upgrading to v22.8, we can't create distributed dictionaries anymore.

### ISSUE THREAD

**Issue by nayakravi** [ClickHouse/ClickHouse#40652]
**Describe the unexpected behaviour**
Attempting to create a simple distributed external dictionary that looks up data in postgres fails with the message:
Received exception from server (version 22.8.2): 
"Code: 48. DB::Exception: Received from `<remote server IP>`. DB::Exception: Value 3 of setting distributed_ddl_entry_format_version is incompatible with cross-replication. (NOT_IMPLEMENTED)"

* Which ClickHouse server version to use - 22.8.2
* `CREATE TABLE` statements for all tables involved

```
CREATE DICTIONARY IF NOT EXISTS default.my_dict ON CLUSTER mycluster
(
	id String,
	name String
)
PRIMARY KEY id
SOURCE(POSTGRESQL(
    NAME 'my_pg_prd'
    DB 'mydb'
    TABLE 'config.name_lookup'
    ))
LAYOUT(COMPLEX_KEY_HASHED())
LIFETIME(MIN 43200 MAX 86400); -- 16-24 hours
```

**Expected behavior**
A distributed dictionary should be created.

**Error message and/or stacktrace**
Received exception from server (version 22.8.2):
Code: 48. DB::Exception: Received from `<remote server>:9000`. DB::Exception: Value 3 of setting distributed_ddl_entry_format_version is incompatible with cross-replication. (NOT_IMPLEMENTED)

**Comment by tavplubix** [comment]
Set `distributed_ddl_entry_format_version` to 2 (queries will not be normalized on initiator, so you may face issues like https://github.com/ClickHouse/ClickHouse/issues/39917)

**Comment by nayakravi** [comment]
great thanks @tavplubix - that worked. It wasn't very clear from the documentation how to handle this.

**Comment by lhbsaldana** [comment]
If you're working with dictionaries in a ClickHouse cluster, and want to ensure your dictionary is properly loaded across all nodes, here's what worked for me:

After creating the dictionary using: 
```
CREATE DICTIONARY IF NOT EXISTS `<dictionary>` ON CLUSTER `<cluster>`....  
```
You can trigger loading it across all nodes by running: 
```
 SYSTEM RELOAD DICTIONARY ON CLUSTER `<cluster>` <db>.<dictionary>;
```

To verify that the dictionary has been loaded on all cluster nodes, you can use 
```
SELECT
    hostName(),
    name,
    status,
    origin,
    last_exception
FROM clusterAllReplicas('<cluster>', system.dictionaries)
WHERE name = '<dictionary>'
```
