### ISSUE TITLE
Test `test_sharding_key_from_default_column` is flaky

### ISSUE THREAD

**Issue by tavplubix** [ClickHouse/ClickHouse#40667]
https://play.clickhouse.com/play?user=play#c2VsZWN0IAp0b1N0YXJ0T2ZEYXkoY2hlY2tfc3RhcnRfdGltZSkgYXMgZCwKY291bnQoKSwgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlciksICBhbnkocmVwb3J0X3VybCkKZnJvbSBjaGVja3Mgd2hlcmUgJzIwMjItMDEtMDEnIDw9IGNoZWNrX3N0YXJ0X3RpbWUgYW5kIHRlc3RfbmFtZSBsaWtlICcldGVzdF9zaGFyZGluZ19rZXlfZnJvbV9kZWZhdWx0X2NvbHVtbiUnIGFuZCB0ZXN0X3N0YXR1cyBpbiAoJ0ZBSUwnLCAnRkxBS1knKSBncm91cCBieSBkIG9yZGVyIGJ5IGQgZGVzYw==

Example: https://s3.amazonaws.com/clickhouse-test-reports/0/c9dea66f8d37c13e27678eeeec246c6a97e40e67/integration_tests__asan__[1/3].html
```
>           assert node1.query("SELECT x, y, z FROM dist") == TSV(
                [[2, 102, 104], [4, 104, 108], [1, 101, 102], [3, 103, 106]]
            )
E           AssertionError: assert '1\t101\t102\n3\t103\t106\n2\t102\t104\n4\t104\t108\n' == 2	102	104\n4	104	108\n1	101	102\n3	103	106
E            +  where '1\t101\t102\n3\t103\t106\n2\t102\t104\n4\t104\t108\n' = <bound method ClickHouseInstance.query of <helpers.cluster.ClickHouseInstance object at 0x7fcd52824130>>('SELECT x, y, z FROM dist')
E            +    where <bound method ClickHouseInstance.query of <helpers.cluster.ClickHouseInstance object at 0x7fcd52824130>> = <helpers.cluster.ClickHouseInstance object at 0x7fcd52824130>.query
E            +  and   2	102	104\n4	104	108\n1	101	102\n3	103	106 = TSV([[2, 102, 104], [4, 104, 108], [1, 101, 102], [3, 103, 106]])

```

Seems like `ORDER BY` is missing

**Comment by qoega** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/0/911bb8e6abddf7d8b1891fadb764835205605af5/integration_tests__asan__[1/3].html

**Comment by tavplubix** [comment]
Fixed in https://github.com/ClickHouse/ClickHouse/commit/eeb5a4c24138695e1b72977f4b29eb45d423f968
