### ISSUE TITLE
Column data corrupted after 'ALTER TABLE ... MODIFY ...' fails when changing column type

### ISSUE THREAD

**Issue by nilaymk** [ClickHouse/ClickHouse#40664]
**Describe what's wrong**

Column data is left in corrupt state when an attempt to `ALTER TABLE ... MODIFY ...` column's type results in failure due to `CAST` related errors.
(e.g. when casting a `String` column with empty or alpha values to `Int64`)

**Does it reproduce on recent release?**
YES: Reproduced in and `22.8.2.11` (and also `22.7.1.2484`).

**How to reproduce**
- Create a database and table, and insert a row with empty ('') text for `String` column 
  ```
   CREATE DATABASE test_convs
   CREATE TABLE test_convs.t_conv (test_str_to_int64 String, int64_col_1 Int64) engine=MergeTree() ORDER BY int64_col_1
   INSERT INTO test_convs.t_conv VALUES ('', 0);
   ```
- Now try to MODIFY the column's type `String` to `Int64` 
  
  `ALTER TABLE test_convs.t_conv MODIFY COLUMN test_str_to_int64 Int64 DEFAULT -1`
  
  results in expected error as conversion of `''` string to `Int64` fails.
  ```
  Code: 341. DB::Exception: Exception happened during execution of mutation 'mutation_2.txt' with
  part 'all_1_1_0' reason: 'Code: 32. DB::Exception: Attempt to read after eof: Cannot parse Int64 from String,
  because value is too short: while executing 'FUNCTION _CAST(test_str_to_int64 :: 0, 'Int64' :: 2) ->
  _CAST(test_str_to_int64, 'Int64') Int64 : 3': (while reading from part
  /var/lib/clickhouse/store/fb1/fb14ca4a-bfa6-4c66-aec5-66204145e1b6/all_1_1_0/):
  While executing MergeTreeInOrder. (ATTEMPT_TO_READ_AFTER_EOF) (version 22.8.2.11 (official build))'.
  This error maybe retryable or not. In case of unretryable error, mutation can be killed with KILL MUTATION
  query. (UNFINISHED) (version 22.8.2.11 (official build))
  ```
- However, now the column is corrupted and can not be read or written to.
 `select test_str_to_int64 from test_convs.t_conv`

  will result into error:
  ```
  Code: 32. DB::Exception: Attempt to read after eof: Cannot parse Int64 from String, because value
  is too short: while executing 'FUNCTION _CAST(test_str_to_int64 :: 0, 'Int64' :: 1) ->
  _CAST(test_str_to_int64, 'Int64') Int64 : 2': (while reading from part
  /var/lib/clickhouse/store/fb1/fb14ca4a-bfa6-4c66-aec5-66204145e1b6/all_1_1_0/): While executing
  MergeTreeInOrder. (ATTEMPT_TO_READ_AFTER_EOF) (version 22.8.2.11 (official build))  
  ```
- KILLing the MUTATION doesn't help either:
  `KILL MUTATION WHERE database='test_convs' and table='t_conv'`
   Column is still corrupted as before.  

**Expected behavior**
- On type conversion failure the column should not be left in a corrupt state.

**Potential Workaround**
- Workaround 1
   Of course one can either perform an in place cast
   ```
   ALTER TABLE test_convs.t_conv
   UPDATE test_str_to_int64 = toString(toInt64OrDefault(test_str_to_int64, cast('-1' as Int64)))
   WHERE 1
   ```
   and then change column type using MODIFY
- Workaround 2 (safer)
   Similar to above but use a temporary column and swap it.

**Comment by den-crane** [comment]
It's not a bug. It's expected behaviour. By design.

**Comment by nilaymk** [comment]
If it's by design, then it's strange that the potential for data corruption on failure is not documented.

In any case, is there a way to recover the column once it is left in such corrupt state?

**Comment by den-crane** [comment]
>If it's by design, then it's strange that the potential for data corruption on failure is not documented.

Because nobody care to document it.

>In any case, is there a way to recover the column once it is left in such corrupt state?

see https://github.com/ClickHouse/ClickHouse/issues/39403#issuecomment-1190272864

**Comment by nilaymk** [comment]
@den-crane  Thanks!!!!

Setting the column back to `String` resolved the corruption issue.

I'll follow the workaround of copying the column to a temp column and swapping it with the old column.

The issue can be closed now.
