### ISSUE TITLE
how to export bitmap as string?

### ISSUE THREAD

**Issue by Ccheers** [ClickHouse/ClickHouse#40701]
in this case , i want to export bitmap to a file. 
But i get so many bit-1 when i decode it to bytes
```sql
select hex(groupBitmapState(ID))
from
tablexx
```

**Comment by Ccheers** [comment]
> Are you looking at something like this?
> 
> ```
> -- create table
> CREATE TABLE tablexx
> (
>     `ID` Int16
> )
> ENGINE = MergeTree
> ORDER BY ID;
> 
> -- insert
> INSERT INTO tablexx VALUES (1), (1), (2), (3);
> 
> -- save to outfile
> SELECT * 
> FROM
> 	(SELECT hex(groupBitmapState(ID)) as h FROM tablexx)
> INTO OUTFILE 'file';
> ```
> 
> ```
> b0cb632665c5 :)     SELECT hex(groupBitmapState(ID)) AS h
>                     FROM tablexx
> 
> SELECT hex(groupBitmapState(ID)) AS h
> FROM tablexx
> 
> Query id: a3ac8309-1afc-46bc-8091-9f8f7762bd6f
> 
> ┌─h────────────────┐
> │ 0003010002000300 │
> └──────────────────┘
> ```
> 
> ```
> ❯ cat file
> 0003010002000300
> ```

it's useless,  roaringbitmap can't decode it. And convert it to []byte it has too many bit-1

**Comment by Algunenano** [comment]
CH internal states are not a 1-1 match to roaring states. You can always try to `finalize()` it and read that instead
