### ISSUE TITLE
Interval parsing from string is wrong.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#40730]
**Describe the unexpected behaviour**
```
SELECT '2022-01-30'::Date + INTERVAL '1 DAY 1 MONTH'
```

It ignores everything after 1 DAY.

**Comment by evillique** [comment]
With the current solution interval day and interval month have different types and cannot be added to each other (they can only be added to a date).
```sql
SELECT INTERVAL '1 DAY', toTypeName(INTERVAL '1 DAY'), INTERVAL '1 DAY', toTypeName(INTERVAL '1 DAY') 

┌─toIntervalDay(1)─┬─toTypeName(toIntervalDay(1))─┬─toIntervalDay(1)─┬─toTypeName(toIntervalDay(1))─┐
│                1 │ IntervalDay                  │                1 │ IntervalDay                  │
└──────────────────┴──────────────────────────────┴──────────────────┴──────────────────────────────┘

SELECT INTERVAL '1 DAY' + INTERVAL '1 MONTH'

Received exception from server (version 22.9.1):
Code: 43. DB::Exception: Received from localhost:9000. DB::Exception: Illegal types IntervalDay and IntervalMonth of arguments of function plus: While processing toIntervalDay(1) + toIntervalMonth(1). (ILLEGAL_TYPE_OF_ARGUMENT)
```

So how should expected behavior look like: should `INTERVAL '1 DAY 1 MONTH'` transform to `toIntervalDay(1) + toIntervalMonth(1)` even considering that it will throw an exception if we select it without a date? 

Even with this solution, it will take some effort to make it work because after the plain transformation 
```
'...'::Date + INTERVAL '1 DAY 1 MONTH'
->
'...'::Date + (toIntervalDay(1) + toIntervalMonth(1))
```
we will still try to compute the sum of the intervals first and throw an exception.

**Comment by alexey-milovidov** [comment]
@evillique The first and easy step of this task will be:
- throw exception if there is something more than one interval in the string.

A test case:
```
SELECT '2022-01-30'::Date + INTERVAL '1 DAY this is trash and we do everything wrong'
```

**Comment by alexey-milovidov** [comment]
The second step is more interesting.

We should support compound intervals in the following way:

1. Operators plus/minus on intervals will form a tuple of them, coalescing intervals of identical types.
Example:

`toIntervalDay(1) - toIntervalDay(2) + toIntervalMonth(1) + toIntervalDay(1)`
will return
`(toIntervalDay(-1), toIntervalMonth(1), toIntervalDay(1))` of type `Tuple(IntervalDay, IntervalMonth, IntervalDay)`

2. Operators plus/minus with date/time argument should support a tuple of intervals argument and apply the components sequentially.

Notes:

Addition of intervals is not commutative:

```
milovidov-desktop :) SELECT '2022-01-30'::Date + INTERVAL 1 DAY + INTERVAL 1 MONTH

┌─plus(plus(CAST('2022-01-30', 'Date'), toIntervalDay(1)), toIntervalMonth(1))─┐
│                                                                   2022-02-28 │
└──────────────────────────────────────────────────────────────────────────────┘

milovidov-desktop :) SELECT '2022-01-30'::Date + INTERVAL 1 MONTH + INTERVAL 1 DAY

┌─plus(plus(CAST('2022-01-30', 'Date'), toIntervalMonth(1)), toIntervalDay(1))─┐
│                                                                   2022-03-01 │
└──────────────────────────────────────────────────────────────────────────────┘
```

For curiosity: this operation is named "direct product" or "external product" in the mathematical sense.
