### ISSUE TITLE
I want to define more that 32 conditions in windowFunnel

### ISSUE THREAD

**Issue by rezamnkh79** [ClickHouse/ClickHouse#40744]
Hello,I want to define more that 32 conditions in windowFunnel but I get this error

`Code: 42, e.displayText() = DB::Exception: Too many event arguments for aggregate function windowFunnel (version 21.7.2.7 (official build))`
 
 and my query is :
  ```
SELECT level,
       count() as result

	FROM (
	      SELECT myid,
		     windowFunnel(6048000000000000)(creation_time,
			          event_token = 'nfv', event_token = 'c56'
			 , event_token = 'klp', event_token = '77o', event_token = 'p19'
			 , event_token = '9rs', event_token = '8w0', event_token = '8s3'
			 , event_token = '6jb', event_token = 'hxk', event_token = 'ho6'
			 , event_token = 'sil', event_token = 'f66', event_token = 'mq6'
			 , event_token = 'j8y', event_token = '8xe', event_token = '6xi'
			 , event_token = 'xyp', event_token = 'rwa', event_token = 'ws8'
			 , event_token = 'bsz', event_token = 'nkp', event_token = '7r4'
			 , event_token = 'kxj', event_token = 'tde', event_token = 'fm3'
			 , event_token = 'j9n', event_token = 'bfb', event_token = 'wha'
			 , event_token = '0q1', event_token = 'uhy', event_token = 'q63'
			 , event_token = 'ihx', event_token = 'x8z', event_token = 'ete'
			 , event_token = 'zs3', event_token = 'kcr', event_token = 'gra'
			 , event_token = 'd5i', event_token = 'bi5', event_token = '021'
			 , event_token = 'xqc', event_token = '9rd', event_token = 'azq'
			 , event_token = 'xsq', event_token = 'rx4', event_token = '030'
			 ) AS level
	      from mydb.events as event_table
	      GROUP BY myid
		 )

	GROUP BY level
	ORDER BY level ASC;

```
thanks

**Comment by e-mars** [comment]
hi @rezamnkh79 .

The max_events parameter is hard set and not configurable. 
Decision was likely to avoid performance and resource usage issues.
https://github.com/ClickHouse/ClickHouse/blob/fe1bed0b401691be3bcc12e8b7d4f35073399b37/src/AggregateFunctions/AggregateFunctionWindowFunnel.h#L23

Could you provide a bit more info on the use-case?
What size would be needed?

**Comment by rezamnkh79** [comment]
Thank you very much for your consideration. I save actions and behaviors of the users in the system in special events and then I want to have some analytics on their behavior. So I want to use `windowFunnel` in order to measure special events sequences and some of these sequences include more than 32 events. How can I solve this issue by the help of ClickHouse?

> hi @rezamnkh79 .
> 
> The max_events parameter is hard set and not configurable. Decision was likely to avoid performance and resource usage issues.
> 
> https://github.com/ClickHouse/ClickHouse/blob/fe1bed0b401691be3bcc12e8b7d4f35073399b37/src/AggregateFunctions/AggregateFunctionWindowFunnel.h#L23
> 
> Could you provide a bit more info on the use-case? What size would be needed?

Thank you very much for your consideration. I save actions and behaviors of the users in the system in special events and then I want to have some analytics on their behavior. So I want to use `windowFunnel` in order to measure special events sequences and some of these sequences include more than 32 events. How can I solve this issue by the help of ClickHouse?

**Comment by e-mars** [comment]
With the current hardset limit of 32, you'd need to likely perform client-side where might need to combine results of multiple window funnel ops.
I think the resource usage might be very high on allowing an increase to > 32. 
You can submit a feature/enhancement request with your use-case and details as a new issue to get a bit more feedback from Dev team/contributors. 
thanks.
