### ISSUE TITLE
What privs are needed for  "DELETE FROM[...]"

### ISSUE THREAD

**Issue by rkozlo** [ClickHouse/ClickHouse#40743]
With new version came new functionality for DELETE. There is no privilege to this action in [doc](https://clickhouse.com/docs/en/sql-reference/statements/grant#privileges). I am pretty sure it is "ALTER DELETE" but there could be information for that.

**Comment by DanRoscigno** [comment]
Removed documentation label, the question is about the permissions needed to use DELETE FROM.

**Comment by DanRoscigno** [comment]
You are correct, it is `ALTER DELETE`:
```
DB::Exception: dan: Not enough privileges. To execute this query it's necessary to have grant ALTER DELETE ON helloworld.my_first_table. (ACCESS_DENIED)
```
