### ISSUE TITLE
How to configure cluster to have 1 write-only + 2 read-only replicas?

### ISSUE THREAD

**Issue by tasdflkjweio** [ClickHouse/ClickHouse#40761]
### Background
I'm beginning work to set up a ClickHouse cluster with 3 CH nodes. The first node (Node A) would be write-only, and the remaining 2 (Nodes B + C) would be read-only. By this I mean that writes for a given table to Node A would automatically replicate to Nodes B + C. When querying the cluster, reads would only be resolved against Nodes B + C.

I'm also unclear whether I should be using ClickHouse Keeper or Zookeeper. Based on a brief conversation I had with Altinity, I'm under the impression that ZooKeeper is more stable/battle-tested and I should use this. Any guidance here is also appreciated.

### Question
I'm not finding much specific information in the CH documentation, and am wondering whether this might be possible. If so, what would the cluster configuration look like?

**Comment by coelho** [comment]
@tasdflkjweio You would have WRITE clients only connect to Node A, and READ clients connect to Node B + C. 
The node that you send the query is the node that executes it.
Note: Distributed (Sharded) tables do change this behavior, but this is not required for replication.

**Comment by tasdflkjweio** [comment]
@coelho thank you for the response. Am I mistaken that if queries go against a replicated table (within a cluster), those queries are automatically load balanced across the cluster? I had originally been planning on connecting to specific nodes to handle load distributing, but thought the load balancer would be more practical. Is the load balancer only used to query across shards?

**Comment by alexey-milovidov** [comment]
> I'm also unclear whether I should be using ClickHouse Keeper or Zookeeper. Based on a brief conversation I had with Altinity, I'm under the impression that ZooKeeper is more stable/battle-tested and I should use this. Any guidance here is also appreciated.

You should use ClickHouse Keeper.

Don't listen to what Altinity said. We have no trust in them.
