### ISSUE TITLE
Create array string from columns with different datatypes

### ISSUE THREAD

**Issue by mison6** [ClickHouse/ClickHouse#40763]
I am trying to create a string label from an array of columns.  The columns are of type Lowcardinality(String), LowCardinality(FixedString), and/or Date.  This worked in version 21.9, but after upgrading to 22.7, I get an error:
> There is no supertype for types String, Date

A query snippet to reproduce the error:

```sql
SELECT arrayMap(x -> toString(x), ['Hello', toDate('2022-01-01')])
```

The use case is as follows: Via a templated query, a user can select a list of columns to group by and plot with an auto-generated label.

Template is formatted like `arrayStringConcat(arrayMap(x -> toString(x), {{ group_by_list }}), ':')`,

Which results in a rendered query like:

```sql
SELECT
  ...
  arrayStringConcat(arrayMap(x -> toString(x), [my_string, my_date]), ':') AS label
FROM
  my_table
GROUP BY
  my_string,
  my_date
```
And a desired `label` as `Hello:2022-01-01`

 `arrayMap` was the perfect solution to convert all elements to the same datatype, but now I can no longer create the initial array to pass into arrayMap.

In clickhouse >= 22.7, is there a way to create a string array from a generic list of columns with different datatypes?

**Comment by den-crane** [comment]
It never worked https://fiddle.clickhouse.com/a967892c-7881-4340-a67b-0a7c2d17cf9d

All elements in the array mush have the same type.

**Comment by mison6** [comment]
Interesting. I guess our users had never selected a date and string column together until after the upgrade.

Is there any workaround to create an array with a desired data type from a generic set of columns?

We've tried passing in the list as a string of column names (like `['my_string', 'my_date']`), but couldn't figure out how to get the value of the column that way.

**Comment by den-crane** [comment]
I don't really understand the task. Try make an example, create table , insert , ....

**Comment by mison6** [comment]
Let's say a simple time series table with some numeric and categorical values:

```sql
CREATE TABLE my_table (
  timestamp UInt64,
  value Int64,
  my_date1 Date,
  my_string1 LowCardinality(String),
  my_date2 Date,
  my_string2 LowCardinality(String)
)
ENGINE = MergeTree()
PARTITION BY my_date1
ORDER BY timestamp
```

```sql
INSERT INTO my_table (*) VALUES (0, 1, '2022-01-01', 'category1', '2022-01-31', 'category2'), (0, 2, '2022-01-01, 'category2', '2022-01-31', 'category2'), (0, 3, '2022-02-01', 'category2', '2022-02-28', 'category1'), (0, 4, '2022-02-01', 'category1', '2022-02-28', 'category2')
```

The goal is to have [redash visualizations](https://redash.io/help/user-guide/visualizations/visualization-types) of this data using some subset of {my_date1, my_string1, my_date2, my_string2} as the grouping. To accomplish this, we define three variables to use in a query template:

* start -- The start timestamp of data
* end -- The end timestamp of data
* group_by_list -- Comma separated list of table columns to group by for data visualization

For simplicity say we want to make a boxplot of the values. The goal is to create a label of the grouping to compare across the different groups in the boxplot.

```sql
SELECT
  value, 
  arrayStringConcat(arrayMap(x -> toString(x), [{{ group_by_list }}]), ':') AS label,
FROM my_table
WHERE timestamp BETWEEN {{ start }} AND {{ end }}
GROUP BY
  {{ group_by_list }}
```

Say we want to visualize the relationship between my_date1 and my_string1. We can set
  * start = 0
  * end = 1000
  * group_by_list = 'my_date1, my_string1'

This gets rendered as 

```sql
SELECT
  value, 
  arrayStringConcat(arrayMap(x -> toString(x), [my_date1, my_string1), ':') AS label,
FROM my_table
WHERE timestamp BETWEEN 0 AND 1000
GROUP BY
  my_date1, my_string1
```

And ideally we end up with 4 boxplots, labeled as:
* 2022-01-01:category1
* 2022-01-01:category2
* 2022-02-01:category1
* 2022-02-01:category2

The goal is to have a single query template that can handle as many as 4 and as few as 1 columns used in the group by statement, so we can easily visualize the relationship between different sets of columns.

We need a way to condense the unknown number of groups into a single label to output in the visualization. The template above works great, except when a Date and String column are included in the group by set.

**Comment by den-crane** [comment]
```sql
create table xxx Engine = Memory as select 1 a, 'x' b, today() c;

select * from xxx;
┌─a─┬─b─┬──────────c─┐
│ 1 │ x │ 2022-08-29 │
└───┴───┴────────────┘

SELECT arrayStringConcat([columns(a,b,c) APPLY(toString)], ': ')  FROM xxx ;
┌─arrayStringConcat(array(toString(a), toString(b), toString(c)), ': ')─┐
│ 1: x: 2022-08-29                                                      │
└───────────────────────────────────────────────────────────────────────┘
```

**Comment by mison6** [comment]
Amazing! Thank you!
