### ISSUE TITLE
Nested identical combinator 'ForEach' is not supported

### ISSUE THREAD

**Issue by sablastik** [ClickHouse/ClickHouse#40776]
Up to version 21.10.5.3 such query with Nested ForEach was valid:

```
SELECT sumForEachForEach(a)
FROM 
(
SELECT
    [[1], [1, 1, 1, 1, 1]] AS a
UNION ALL
SELECT
    [[1, 0], [1, 1, 1], [1, 0, 0]] AS a
)
```

Result:
`[[2,0],[2,2,2,1,1],[1,0,0]]
`
Example: https://fiddle.clickhouse.com/a58774e7-7f88-4187-bb54-7041eca44353

And since 21.11.x it's not working with following error:
```
Received exception from server (version 21.11.2):
Code: 184. DB::Exception: Received from localhost:9000. DB::Exception: Nested identical combinator 'ForEach' is not supported. (ILLEGAL_AGGREGATION)
```

**Comment by sablastik** [comment]
Looks like this commit https://github.com/ClickHouse/ClickHouse/commit/1e7714d56d21ed8a225c59d0ce3e0c013e356bf6 banned all nested combinators even if they worked =/

**Comment by alexey-milovidov** [comment]
If the issue is still relevant, you can ask @azat for clarification.
