### ISSUE TITLE
zero copy replication (a feature is development, not production ready) does not work when using S3 with cache disk

### ISSUE THREAD

**Issue by ryoid** [ClickHouse/ClickHouse#40773]
**Describe what's wrong**

When using `allow_remote_fs_zero_copy_replication`  for S3 with cache disk, data still duplicates for each replica. 

**Does it reproduce on recent release?**

Yes

**How to reproduce**

ClickHouse server version: `22.8.2.11`

<details>
  <summary>Relevant Storage Config</summary>

  ```xml
<storage_configuration>
  <disks>
    <object_storage>
      <type>s3</type>
    </object_storage>

    <object_storage_cache>
      <type>cache</type>
      <disk>object_storage</disk>
    </object_storage_cache>
  </disks>

  <merge_tree>
    <allow_remote_fs_zero_copy_replication>1</allow_remote_fs_zero_copy_replication>
  </merge_tree>

  <policies>
    <object_storage>
      <volumes>
        <main>
          <disk>object_storage_cache</disk>
        </main>
      </volumes>
    </object_storage>

    <s3_storage>
      <volumes>
        <main>
          <disk>object_storage</disk>
        </main>
      </volumes>
    </s3_storage>
  </policies>
</storage_configuration>
  ```
</details>

<details>
  <summary>Create Table Query</summary>

  ```sql
CREATE TABLE table ON CLUSTER 'cluster_1S_3R'
(
   ...
) 
ENGINE = ReplicatedMergeTree('/clickhouse/{cluster}/tables/{shard}/{database}/{table}', '{replica}')
ORDER BY (timestamp)
SETTINGS storage_policy='object_storage'
  ```
</details>

- Create a table using `object_storage` policy and insert data
- Check S3 bucket size - seems to be duplicated per replica
- Same steps with `s3_storage` policy instead resulted in expected bucket size.

**Expected behavior**

Only 1 copy of the data on S3.

**Additional context**

Apologies if this is avoidable through additional configuration, could not find much documentation on this.

Edit: I tried `cache_enabled` on the S3 disk and also ran into the same issue using  `s3_storage` policy

**Comment by alesapin** [comment]
Added cache to zero-copy replication test https://github.com/ClickHouse/ClickHouse/pull/40780. This test count amount of blobs created in S3: https://github.com/ClickHouse/ClickHouse/blob/ac41de73df41ed7c754bd9cad399936ae01effed/tests/integration/test_replicated_merge_tree_s3_zero_copy/test.py#L116-L129. This test path (with enabled cache) on both `master` and `22.8.2.11`. On both versions I see messages about zero copy replication in logs and it actually works (number of blobs in S3 is correct). Any ideas how to reproduce?

**Comment by ryoid** [comment]
Just realised I was making a mistake with the `merge_tree` config being inside the `storage_configuration`. It is working as expected.
