### ISSUE TITLE
xxx file not found when building native llvm-tblgen

### ISSUE THREAD

**Issue by Joeywzr** [ClickHouse/ClickHouse#40783]
**ClickHouse version**
ClickHouse-22.7.3.5-stable

**Operating system**
CentOS Linux release 7.2.1511 (Core)

**Cmake version**
3.15.5

**Ninja version**
1.9.0.git

**Compiler name and version**
clang 12.0

**Full cmake and/or ninja output**

CC=/home/amos/gentoo/usr/local/bin/clang CXX=/home/amos/gentoo/usr/local/bin/clang++ cmake .. -DENABLE_TESTS=0

> [0/2] Re-checking globbed directories...
[0/4931] Building native llvm-tblgen...
[1/213] Building CXX object li...LVMDemangle.dir/Demangle.cpp.o
FAILED: lib/Demangle/CMakeFiles/LLVMDemangle.dir/Demangle.cpp.o 
/home/amos/gentoo/usr/local/bin/clang++  -DGTEST_HAS_RTTI=0 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Ilib/Demangle -I/mnt/disk2/ck22/contrib/llvm/llvm/lib/Demangle -Iinclude -I/mnt/disk2/ck22/contrib/llvm/llvm/include -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -fdiagnostics-color -ffunction-sections -fdata-sections -O3 -DNDEBUG   -g0  -fno-exceptions -fno-rtti -std=c++14 -MD -MT lib/Demangle/CMakeFiles/LLVMDemangle.dir/Demangle.cpp.o -MF lib/Demangle/CMakeFiles/LLVMDemangle.dir/Demangle.cpp.o.d -o lib/Demangle/CMakeFiles/LLVMDemangle.dir/Demangle.cpp.o -c /mnt/disk2/ck22/contrib/llvm/llvm/lib/Demangle/Demangle.cpp
In file included from /mnt/disk2/ck22/contrib/llvm/llvm/lib/Demangle/Demangle.cpp:13:
/mnt/disk2/ck22/contrib/llvm/llvm/include/llvm/Demangle/Demangle.h:12:10: fatal error: 'cstddef' file not found
#include <cstddef>
         ^~~~~~~~~
1 error generated.
[2/213] Building CXX object li...MSupport.dir/BuryPointer.cpp.o
FAILED: lib/Support/CMakeFiles/LLVMSupport.dir/BuryPointer.cpp.o 
/home/amos/gentoo/usr/local/bin/clang++  -DGTEST_HAS_RTTI=0 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Ilib/Support -I/mnt/disk2/ck22/contrib/llvm/llvm/lib/Support -Iinclude -I/mnt/disk2/ck22/contrib/llvm/llvm/include -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -fdiagnostics-color -ffunction-sections -fdata-sections -O3 -DNDEBUG   -g0 -std=c++14  -fno-exceptions -fno-rtti -MD -MT lib/Support/CMakeFiles/LLVMSupport.dir/BuryPointer.cpp.o -MF lib/Support/CMakeFiles/LLVMSupport.dir/BuryPointer.cpp.o.d -o lib/Support/CMakeFiles/LLVMSupport.dir/BuryPointer.cpp.o -c /mnt/disk2/ck22/contrib/llvm/llvm/lib/Support/BuryPointer.cpp
In file included from /mnt/disk2/ck22/contrib/llvm/llvm/lib/Support/BuryPointer.cpp:9:
/mnt/disk2/ck22/contrib/llvm/llvm/include/llvm/Support/BuryPointer.h:12:10: fatal error: 'memory' file not found
#include <memory>
         ^~~~~~~~
1 error generated.
[3/213] Building CXX object li...pport.dir/DeltaAlgorithm.cpp.o
FAILED: lib/Support/CMakeFiles/LLVMSupport.dir/DeltaAlgorithm.cpp.o 
/home/amos/gentoo/usr/local/bin/clang++  -DGTEST_HAS_RTTI=0 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Ilib/Support -I/mnt/disk2/ck22/contrib/llvm/llvm/lib/Support -Iinclude -I/mnt/disk2/ck22/contrib/llvm/llvm/include -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -fdiagnostics-color -ffunction-sections -fdata-sections -O3 -DNDEBUG   -g0 -std=c++14  -fno-exceptions -fno-rtti -MD -MT lib/Support/CMakeFiles/LLVMSupport.dir/DeltaAlgorithm.cpp.o -MF lib/Support/CMakeFiles/LLVMSupport.dir/DeltaAlgorithm.cpp.o.d -o lib/Support/CMakeFiles/LLVMSupport.dir/DeltaAlgorithm.cpp.o -c /mnt/disk2/ck22/contrib/llvm/llvm/lib/Support/DeltaAlgorithm.cpp
In file included from /mnt/disk2/ck22/contrib/llvm/llvm/lib/Support/DeltaAlgorithm.cpp:8:
/mnt/disk2/ck22/contrib/llvm/llvm/include/llvm/ADT/DeltaAlgorithm.h:11:10: fatal error: 'set' file not found
#include <set>
         ^~~~~
1 error generated.
[4/213] Building CXX object li...pport.dir/BlockFrequency.cpp.o
FAILED: lib/Support/CMakeFiles/LLVMSupport.dir/BlockFrequency.cpp.o 
/home/amos/gentoo/usr/local/bin/clang++  -DGTEST_HAS_RTTI=0 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Ilib/Support -I/mnt/disk2/ck22/contrib/llvm/llvm/lib/Support -Iinclude -I/mnt/disk2/ck22/contrib/llvm/llvm/include -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -fdiagnostics-color -ffunction-sections -fdata-sections -O3 -DNDEBUG   -g0 -std=c++14  -fno-exceptions -fno-rtti -MD -MT lib/Support/CMakeFiles/LLVMSupport.dir/BlockFrequency.cpp.o -MF lib/Support/CMakeFiles/LLVMSupport.dir/BlockFrequency.cpp.o.d -o lib/Support/CMakeFiles/LLVMSupport.dir/BlockFrequency.cpp.o -c /mnt/disk2/ck22/contrib/llvm/llvm/lib/Support/BlockFrequency.cpp
In file included from /mnt/disk2/ck22/contrib/llvm/llvm/lib/Support/BlockFrequency.cpp:13:
In file included from /mnt/disk2/ck22/contrib/llvm/llvm/include/llvm/Support/BlockFrequency.h:16:
/mnt/disk2/ck22/contrib/llvm/llvm/include/llvm/Support/BranchProbability.h:17:10: fatal error: 'algorithm' file not found
#include <algorithm>

**Comment by rschu1ze** [comment]
Could you check if directory "contrib/llvm/" is non-empty? Chances are that you don't have all submodules checked out. 

Try to run
```
git submodule update --init --recursive
```
and see [here](https://clickhouse.com/docs/en/development/developer-instruction) for the compilation guide.

**Comment by Joeywzr** [comment]
It's my clang's problem. I tried [this](https://github.com/amosbird/ldb_toolchain_gen) and it worked.
