### ISSUE TITLE
Efficiently joining tables which are already ordered by the join key

### ISSUE THREAD

**Issue by srikanthccv** [ClickHouse/ClickHouse#40791]
Hello 👋,

I have two tables which are already been ordered by column used in joining tables. For example 

```sql
CREATE TABLE IF NOT EXISTS A (
    id UInt64,
    time Int64,
    value Float64 
)
ENGINE = MergeTree
    ORDER BY (id, time)
```

And the another table `B` is 

```sql
CREATE TABLE IF NOT EXISTS B (
    id UInt64,
    json String,
)
ENGINE = ReplacingMergeTree
    ORDER BY (id)
```

Some of my typical queries involve joining the two tables on the id column which is already ordered by. So I would like to use this property of data to get the joining done in a linear scan with two pointer technique. How can I achieve this with ClickHouse today? I noticed there is something called `partial_merge`. Could you please elaborate on its inner workings of it? What does it do under the hood? Does it again unnecessarily sort the data which is already sorted? How can I avoid that in my usecase?

**Comment by canhld94** [comment]
Looks at #34236 seem need to wait for real sort merge join for your case.

**Comment by alexey-milovidov** [comment]
This feature is being implemented by @vdimir
