### ISSUE TITLE
ClickHouse never remove part_moves_shard task node when using 'move parition to shard'.

### ISSUE THREAD

**Issue by zhaojintaozhao** [ClickHouse/ClickHouse#40814]
ClickHouse never remove part_moves_shard task node when using 'move parition to shard'.

Hi all.
In my system, there are two shards and two replicas，I use 'move partition to shard' to move part between shards. I find that after part moving task, ClickHouse never remove part_moves_shard task node in zookeeper.

The procedure is as follows:
1st, create a ReplicatedMergeTree table on cluster.
2nd, import data to the shard1 replica1 node.
3rd, move partition to shard2 in shard1replica1. #17871
4th. after task finished, check task node under part_moves_shard, thease task node like 'task-0000000000' never remove.

How to reproduce:

In shard1 replica1:
1st: create table test on cluster '{cluster}' (key UInt32, value1 String, value2 String, value3 String) engine=ReplicatedMergeTree('/clickhouse/{shard}/test', '{replica}') order by key partition by (key % 4) 

2nd: insert into test select * from generateRandom('key UInt32, value1 String, value2 String, value3 String') limit 1000000

3rd: alter table test move part '0_0_0_0' to shard '/clickhouse/02/test';

In shard2 replica1:
4th: select * from test limit 2, we can query data from shard2replica1;

5th: check part move task node under '/clickhouse/01/test/part_moves_shard'

We can find part move task like '/clickhouse/01/test/part_moves_shard/task-0000000000'. Though task state of 'task-0000000000' is 'done', but this node will never to be removed.

Do other friends have similar problems?

**Comment by zhaojintaozhao** [comment]
Hi  @alesapin , Do you have the same problem?

**Comment by alexey-milovidov** [comment]
We don't use the "move partition to shard" experimental feature, which was added by Cloudflare and is not supported.

**Comment by zhaojintaozhao** [comment]
> We don't use the "move partition to shard" experimental feature, which was added by Cloudflare and is not supported.

Hi alexey:  

What's kown issues abount “move partition to shard”  this experimental feature? 
What do you recommend if we want to move parts between shards (for example, in a scale-in scenario)?

Thank you.

**Comment by nvartolomei** [comment]
I think we can add something like `part_moves_between_shards_to_keep` similar to mutations

```bash
 → ag finished_mutations_to_keep
Storages/MergeTree/MergeTreeSettings.h
113:    M(UInt64, finished_mutations_to_keep, 100, "How many records about mutations that are done to keep. If zero, then keep all of them.", 0) \
```

Should be pretty simple if you have time to work on it.
