### ISSUE TITLE
 Data is not distributed in real-time writing scenarios, suspected that the BgDistSchPool exited unexpectedly.

### ISSUE THREAD

**Issue by Smelly-calf** [ClickHouse/ClickHouse#40829]
(you don't have to strictly follow this form)

**Describe the issue**
1. The user queries the distributed table and finds that 3 pieces of data are missing，and there are exactly written_rows=3 success log in the system.query_log.
2. observed monitor found：
![DistributeFilesToInsert](https://user-images.githubusercontent.com/44859819/187581278-fcdeb054-d5b1-4c2b-95d4-a6a99f7509f5.jpg)
3. `ps -T -p clickhouse_pid | grep BgDistSchPool`：
![BgDistSchPool](https://user-images.githubusercontent.com/44859819/187586345-a31c9352-66da-4744-adc4-5c4e96459903.png)

**How to reproduce**
Not reproduce yet.
* Which ClickHouse server versions are incompatible
v22.3
* `CREATE TABLE` statements for all tables involved
Normal ReplicatedMergeTree Table
* Queries to run that lead to unexpected result
Just `select * from _all` query.

**Error message and/or stacktrace**
None

**Additional context**
None

**Comment by filimonov** [comment]
I saw something similar when cluckhouse were reaching the limit of opened files (nofile ulimit), repro is needed.

**Comment by Smelly-calf** [comment]
> I saw something similar when cluckhouse were reaching the limit of opened files (nofile ulimit), repro is needed.
