### ISSUE TITLE
query execution is slower than I expect if I use digitalocean droplet

### ISSUE THREAD

**Issue by keruk** [ClickHouse/ClickHouse#40824]
(you don't have to strictly follow this form)

**Describe the situation**
What exactly works slower than expected? under 3 seconds

**How to reproduce**
* Which ClickHouse server version to use  -> 21.11.6
* Which interface to use, if matters droplet digitalocean

SELECT count()
FROM
(
    SELECT DISTINCT email
    FROM table_list
    LIMIT 5 BY place.value1
)

Query id: 4be7121c-d2ea-445d-bddb-42758fb933a4

┌─count()─┐
│ 2594988 │
└─────────┘

1 rows in set. Elapsed: 15.697 sec. Processed 26.78 million rows, 1.70 GB (1.71 million rows/s., 108.34 MB/s.)

**Comment by alexey-milovidov** [comment]
How to reproduce?

**Comment by keruk** [comment]
-- Performance of the SQL is very slow output.
column place.value1 has the data set and we need only 5 from the place.value1 

I have created index on the column of place.value1 it did not pick that index. The column is the string.
- creating right index improve the performance.
- Partition list partition on place.value1 will help? We have limitation of partitioning, i will be looking list partitioning.

Thanks,

Keru
Query id: 4be7121c-d2e

**Comment by alexey-milovidov** [comment]
We need steps to reproduce.
