### ISSUE TITLE
skip_unavailable_shards should skip generally problematic instances

### ISSUE THREAD

**Issue by knoguchi** [ClickHouse/ClickHouse#40823]
**Use case**
As of now `skip_unavailable_shards` skips CH instances that are not connectable in terms of network as documented.
- not connectable
- not resolvable by DNS

I would like to expand the functionality of this settings in order to skip instances with non-network problems

 
> A clear and concise description of what is the intended usage scenario is.

- skip shards where TCP connection is established but can't respond to queries.  For example memory exceeded error.
- Non existing database/table is not really error but maybe considered unavailable. 
 
> A clear and concise description of what you want to happen.

queries on Distributed table should not fail.   Warnings should be logged.

**Comment by alexey-milovidov** [comment]
In a previous discussion about this feature, we concluded that it can introduce cascade failures, and should better be avoided.

**Comment by den-crane** [comment]
@knoguchi 

>Non existing database/table is not really error but maybe considered unavailable.

It's already like this https://github.com/ClickHouse/ClickHouse/issues/39580
