### ISSUE TITLE
Setting date_time_input_format in config.xml

### ISSUE THREAD

**Issue by sossaman** [ClickHouse/ClickHouse#40859]
Following the documentation I created a config file : config.xml with this content:
```
<clickhouse>
    <rabbitmq>
        <username>username</username>
        <password>password</password>
    </rabbitmq>
    <profiles>
        <default>
            <date_time_input_format>best_effort</date_time_input_format>
        </default>
    </profiles>
</clickhouse>
```
The file is mounted into the container at this path: ``` /etc/clickhouse-server/config.d/config.xml ```
The rabbitmq credentials have been read, but the setting of  date_time_input_format not.
```SELECT * FROM system.settings WHERE name LIKE 'date_time_input_format';```  still returns ```basic ```

I am not sure if this is unexpected behavior, but the documentation is not clear to me

**Comment by den-crane** [comment]
`<profiles>` are users settings. They should be in `users.d` folder not `config.d`.

https://kb.altinity.com/altinity-kb-setup-and-maintenance/altinity-kb-server-config-files/

**Comment by sossaman** [comment]
Problem resolved!
Many thanks
