### ISSUE TITLE
toDecimal128 works unexpectedly

### ISSUE THREAD

**Issue by HeenaBansal2009** [ClickHouse/ClickHouse#40872]
**Describe the unexpected behaviour**
toDecimal128 is throwing  (ARGUMENT_OUT_OF_BOUND) error. Without String casting , todecimal128 returns decimal overflow which is wrong too. 

 ```
:) select toDecimal128(1234567.056782763549::String, 37)

SELECT toDecimal128(CAST('1234567.056782763549', 'String'), 37)

Query id: 1a708e54-6587-47ab-8bc9-996a49cb89bd


0 rows in set. Elapsed: 0.012 sec. 

Received exception from server (version 22.9.1):
Code: 69. DB::Exception: Received from localhost:9000. DB::Exception: Decimal value is too big: 19 digits were read: 1234567056782763549e-12. Expected to read decimal with scale 37 and precision 38: While processing toDecimal128(CAST('1234567.056782763549', 'String'), 37). (ARGUMENT_OUT_OF_BOUND)


```
However , The similar query works with toDecimal128 works. 

```
 :) SELECT  toDecimal128(01.05645678990334455345566789234567765432::String, 37)

SELECT toDecimal128(CAST('01.05645678990334455345566789234567765432', 'String'), 37)

Query id: 1ecbe805-8726-428b-adcf-5525ea7b9158

┌─toDecimal128(CAST('01.05645678990334455345566789234567765432', 'String'), 37)─┐
│                                       1.0564567899033445534556678923456776543 │
└───────────────────────────────────────────────────────────────────────────────┘

1 row in set. Elapsed: 0.019 sec. 

```

* Which ClickHouse server version to use
 22.8 LTS

**Expected behavior**
Query should run successfully. 

**Additional Context:**
Executing same query without casting in string returned DECIMAL OVERFLOW execution:

```
select toDecimal128(1234567.056782763549, 37)

SELECT toDecimal128(1234567.0567827635, 37)

Query id: e97763b0-f849-4d37-aa30-2685559de1f4


0 rows in set. Elapsed: 1.548 sec. 

Received exception from server (version 22.9.1):
Code: 407. DB::Exception: Received from localhost:9000. DB::Exception: Decimal convert overflow. Float is out of Decimal range: While processing toDecimal128(1234567.0567827635, 37). (DECIMAL_OVERFLOW)


```

**Comment by HeenaBansal2009** [comment]
Thanks @den-crane for clarification.
Can you help me to  read decimal upto 33 scale for 128 bit wide decimal numbers.

**Comment by den-crane** [comment]
33 digits on the right of decimal point????? You're kidding.

I think you need something else, not Decimal.

**Comment by HeenaBansal2009** [comment]
> 33 digits on the right of decimal point????? You're kidding.
> 
> I think you need something else, not Decimal.

I meant by 33 digits of precision

**Comment by den-crane** [comment]
It's insane accuracy. Nobody in this galaxy needs it.

**Comment by HeenaBansal2009** [comment]
I don't think its insane when  you are not sure what I am upto. I am trying to create one more datatype similar to datatype for my application . 
Anyway , I figured it out . 
Thanks!
