### ISSUE TITLE
dropping a target table before corresponding Materialized View is dropped should be prohibited

### ISSUE THREAD

**Issue by FrankChen021** [ClickHouse/ClickHouse#40882]
**Describe the issue**
A table(let's say TARGET) can be dropped if its as a target table of one materialized view before that materialized view is dropped. 

If this happens, the INSERT on source table(let's say SOURCE) of corresponding materialized view fails, reporting a misleading error message that TARGET does not exist.

Users might ask why it reports TARGET does not exist while they're inserting data into a table named as SOURCE. And it might take very long time to realise that TARGET is a target table of a materialized view.

Even we know that it's a good pratice that materialized view should be dropped first before its target table is dropped, we can't ensure every user always follow this practice.

To avoid such problem at user side, I think it would be better to disallow dropping a target table if it's still rerferenced in a materialized view.

I'd like hear what others think about this proposal. If there's no problem, I will open a PR to do this.

**Comment by tavplubix** [comment]
Yes, we should add a setting that does not allow to drop target table before MV, see also https://github.com/ClickHouse/ClickHouse/issues/38326

It can be implemented as an extension for https://github.com/ClickHouse/ClickHouse/pull/30977
But something similar is being implemented in https://github.com/ClickHouse/ClickHouse/pull/39825, so another PR will probably conflict with this one

**Comment by FrankChen021** [comment]
If #39825 meets this requirement, we can wait for it. 

Another point is if a setting is introduced to control this new behavior, when the setting is not enabled, I think we still need to make some adjustment on current misleading error message that target table of one MV does not exist when insert data to source table, like 'target table (%s) of Materialized View(%s) does not exist'.

**Comment by Algunenano** [comment]
This seems to be covered by https://github.com/ClickHouse/ClickHouse/pull/45936

```
ClickHouse local version 23.3.1.2537.

Mordor :) set check_referential_table_dependencies=1

SET check_referential_table_dependencies = 1

Query id: bc5d9b6f-8878-475a-92bf-8bb58c6a41c0

Ok.

0 rows in set. Elapsed: 0.000 sec. 

Mordor :) create table t (a Int64) Engine = MergeTree() order by a;

CREATE TABLE t
(
    `a` Int64
)
ENGINE = MergeTree
ORDER BY a

Query id: 48139514-3377-47f8-adf8-de6c087878c5

Ok.

0 rows in set. Elapsed: 0.009 sec. 

Mordor :) create table t2 (a Int64) Engine = MergeTree() order by a;

CREATE TABLE t2
(
    `a` Int64
)
ENGINE = MergeTree
ORDER BY a

Query id: 9429df37-36ee-4d3d-abb7-013437944da6

Ok.

0 rows in set. Elapsed: 0.002 sec. 


Mordor :) create materialized view t_t2 to t2 as Select * from t;

CREATE MATERIALIZED VIEW t_t2 TO t2 AS
SELECT *
FROM t

Query id: 55222087-3eb7-4735-989e-33b5022d7e33

Ok.

0 rows in set. Elapsed: 0.001 sec. 

Mordor :) drop table t2;

DROP TABLE t2

Query id: 23a61f86-f393-402b-a7cc-55a7c37196fe


0 rows in set. Elapsed: 0.014 sec. 

Received exception:
Code: 630. DB::Exception: Cannot drop or rename _local.t2, because some tables depend on it: _local.t_t2. (HAVE_DEPENDENT_OBJECTS)

Mordor :) drop table t;

DROP TABLE t

Query id: f090c9b1-9271-4b24-a3e6-fd5cebb991cd


0 rows in set. Elapsed: 0.000 sec. 

Received exception:
Code: 630. DB::Exception: Cannot drop or rename _local.t, because some tables depend on it: _local.t_t2. (HAVE_DEPENDENT_OBJECTS)
```
