### ISSUE TITLE
Functions with -OrNull suffix does not recognized as constant

### ISSUE THREAD

**Issue by GuokuaiHuang** [ClickHouse/ClickHouse#40885]
Suppose the following table exists:
```SQL
CREATE TABLE events (
    date_time DateTime,
    value UInt32
)
Engine = MergeTree
PRIMARY KEY date_time
;
```
We use the following query template for counting the number of events for the given client on the given date:
```SQL
SELECT COUNT(*)
FROM events
WHERE date_time >= parseDateTimeBestEffortOrNull(<Constant Formatted DateTime String>)
;
```
This is expected to hit the primary key index filter. Unfortunately, this is not.

In addition, I found that functions with -OrNull suffix does not recognized as constant, whether it is `parseDateTimeBestEffortOrNull` or `toDateTimeOrNull`. `parseDateTimeBestEffortOrZero`, `toDateTimeOrZero`, `parseDateTimeBestEffortOrZero` and `toDateTimeOrZero` work just fine.

**Comment by den-crane** [comment]
CH version?

Are you sure?


22.8
```
SELECT isConstant(parseDateTimeBestEffortOrNull(''))

Query id: 66eecd04-7ed9-411b-93e6-2ccaf6e4516f

┌─isConstant(parseDateTimeBestEffortOrNull(''))─┐
│                                             1 │
└───────────────────────────────────────────────┘
```

Do you mean CH does not use primary index ? But it does use

```sql

CREATE TABLE events
(
    `date_time` DateTime,
    `value` UInt32
)
ENGINE = MergeTree
PRIMARY KEY date_time

insert into events select now(),1 from numbers(1e6);

select count() from events where date_time >= parseDateTimeBestEffortOrNull('2025-01-01') 
settings force_primary_key=1;

┌─count()─┐
│       0 │
└─────────┘

1 row in set. Elapsed: 0.001 sec.
```

**Comment by den-crane** [comment]
It seems it's working after 21.8

21.7
https://fiddle.clickhouse.com/bf956ad2-8264-4b05-a0af-00415e891e8d
Received exception from server (version 21.7.11):
Code: 277. DB::Exception: Received from localhost:9000. DB::Exception: Primary key (date_time) is not used and setting 'force_primary_key' is set.. 

https://fiddle.clickhouse.com/0e6e6eee-45aa-49a8-a78f-5c805f2d44e9
0

**Comment by GuokuaiHuang** [comment]
@den-crane Thanks for your reply. 
I tried to execute SQL with force_primary_key parameters.
```SQL
SELECT count()
FROM events
WHERE`date_time` >= parseDateTimeBestEffortOrNull('2022-09-01 00:00:00')
settings force_primary_key=1
```
Get the error message below.
```
ClickHouse exception, code: 277, host: xxx.xxx.xxx.xxx, port: 46574; Code: 277, e.displayText() = DB::Exception: Primary key (date_time) is not used and setting 'force_primary_key' is set. (version 21.8.2.1)
```
As the error message shows, the version of CH is 21.8.2.1. This cluster was purchased from Alibaba Cloud, and I'm not sure if this version is the community version.

**Comment by den-crane** [comment]
Anyway 21.8 is out of support.
