### ISSUE TITLE
Separately grants for every named connection

### ISSUE THREAD

**Issue by alexsubota** [ClickHouse/ClickHouse#40894]
Can we have separately grants for every named connections?

For example if we have this named connections
```
<named_collections>
    <mysql_connection>
        <user>user</user>
        <password>password</password>
        <host>host</host>
        <port>port</port>
        <database>database</database>
    </mysql_connection>
    <mysql_connection_another_user>
        <user>another_user_with_another_grants</user>
        <password>password</password>
        <host>host</host>
        <port>port</port>
        <database>database</database>
    </mysql_connection_another_user>
</named_collections>
```

Use Case:
We can give mysql_connection named connection for one CH user, and mysql_connection_another_user for another CH user with another grants at mysql db. And user ONE will not able to use mysql_connection_another_user named connection and vice versa

**Comment by alexey-milovidov** [comment]
This feature will be implemented with the dynamic storage of named collections, @kssenii is working on it.
