### ISSUE TITLE
Separate nodes for read and write 

### ISSUE THREAD

**Issue by sdarshil** [ClickHouse/ClickHouse#40895]
i am trying to optimize my clickhouse architecture and i was thinking that what if i use two replicas insted of one in my clickhouse cluster and the use one clickhouse replica for select queries only and use one replica for insert queries only !
will it improvise my architecture for more speed in the frontend microservice as it just uses only select queries ??

current architecture:
One clickhouse node with one zookeeper with clickhouse-operator from altinity
tables are created with replicatedmergetree() as in future we are willing to add replicas to our clickhousecluster !
no distributed are being used as suggested by the altinity team as we dont have terrabytes of data getting inserted .

**Comment by alexey-milovidov** [comment]
Having two identical replicas, one for reads and one for writes, is unlikely to improve performance, compared to using them for both types of queries. However, if you use replicas of different sizes or subsets with different numbers of replicas, it can be more efficient, but it is difficult to find the balance. Anyway, separating replicas by purpose can help with workload isolation.
