### ISSUE TITLE
An option to prevent creating a user identified with no password when the section IDENTIFIED WITH is omitted.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#40913]
**Describe the solution you'd like**

An option to make the `IDENTIFIED WITH` section mandatory.

**Comment by evillique** [comment]
It seems like we can already forbid creating users without a password with `allow_no_password` setting in config [here](https://github.com/ClickHouse/ClickHouse/blob/master/programs/server/config.xml#L466). There are even examples of its work in [this](https://github.com/ClickHouse/ClickHouse/blob/master/tests/queries/0_stateless/02207_allow_plaintext_and_no_password.sh) test.

Or is it something different?

**Comment by alexey-milovidov** [comment]
Yes, it is different.

It allows creating users with no password when you write `IDENTIFIED WITH NO_PASSWORD`.
