### ISSUE TITLE
About system.errors data

### ISSUE THREAD

**Issue by chu1070y** [ClickHouse/ClickHouse#40916]
Hi

I wonder if data on system.errors will be deleted after time flies.
Is the table applied of TTL?

**Comment by genzgd** [comment]
The system.errors table is a small structure (just an error code, counter, and some metadata about the last occurrence) kept entirely in memory.  At most it might grow to several dozen kilobytes or so. It is cleared each time that ClickHouse is started, and there is no separate TTL.
