### ISSUE TITLE
Two tables associated updates

### ISSUE THREAD

**Issue by cmdares** [ClickHouse/ClickHouse#4092]
---oracle
merge into t1
using (select t2.fname,t2.fmoney from t2) t
on (t.fname = t1.fname)
when matched then update  set t1.fmoney = t.fmoney;

----postgresql
update mv_table_user U  
set (province_id,province_name,city_id, city_name) =  (select T.province_id,T.province_name,T.city_id,T.city_name  FROM mv_table_tmp T WHERE T.ID = U.ID)  
where EXISTS (select 1 FROM mv_table_tmp T WHERE T.ID = U.ID)

---clickhouse
??????????

**Comment by blinkov** [comment]
@cmdares, is this question still relevant?

**Comment by blinkov** [comment]
@cmdares, do you have any further questions?

**Comment by alexey-milovidov** [comment]
You can get the desired result if you CREATE DICTIONARY or create a table with Join engine, and then do an update with `dictGet` or `joinGet` function.
