### ISSUE TITLE
2 nodes in the cluster stuck in the infinite loop sync parts

### ISSUE THREAD

**Issue by yandooo** [ClickHouse/ClickHouse#40925]
2 nodes are stuck in the loop trying to sync up parts.

Primary node: 

2022.09.02 09:57:25.901336 [ 221 ] {} <Warning> prd_001.metrics_v12 (ReplicatedMergeTreePartCheckThread): Checking part 202208_754480_755274_7
2022.09.02 09:57:25.901358 [ 64 ] {} <Information> MergeFromLogEntryTask: DB::Exception: No active replica has part 202208_754480_755274_7 or covering part
2022.09.02 09:57:25.901456 [ 56 ] {} <Debug> MergeFromLogEntryTask: Don't have all parts (at least part 202208_754712_754897_6 is missing) for merge 202208_754480_755274_7; will try to fetch it instead
2022.09.02 09:57:25.902138 [ 221 ] {} <Warning> prd_001.metrics_v12 (ReplicatedMergeTreePartCheckThread): Checking if anyone has a part 202208_754480_755274_7 or covering part.
2022.09.02 09:57:25.904006 [ 221 ] {} <Information> prd_001.metrics_v12 (ReplicatedMergeTreePartCheckThread): Found parts with the same min block and with the same max block as the missing part 202208_754480_755274_7 on replica chi-ch-001-ch-001-0-1. Hoping that it will eventually appear as a result of a merge.
2022.09.02 09:57:25.904193 [ 152 ] {} <Warning> prd_001.metrics_v12 (ReplicatedMergeTreePartCheckThread): Checking part 202208_754480_755274_7
2022.09.02 09:57:25.904218 [ 56 ] {} <Information> MergeFromLogEntryTask: DB::Exception: No active replica has part 202208_754480_755274_7 or covering part
2022.09.02 09:57:25.904316 [ 61 ] {} <Debug> MergeFromLogEntryTask: Don't have all parts (at least part 202208_754712_754897_6 is missing) for merge 202208_754480_755274_7; will try to fetch it instead
2022.09.02 09:57:25.904948 [ 152 ] {} <Warning> prd_001.metrics_v12 (ReplicatedMergeTreePartCheckThread): Checking if anyone has a part 202208_754480_755274_7 or covering part.

Replica:

2022.09.02 09:57:32.602253 [ 103 ] {} <Information> prd_001.metrics_v12 (ReplicatedMergeTreePartCheckThread): Found parts with the same min block and with the same max block as the missing part 202208_754480_755274_7 on replica chi-ch-001-ch-001-0-0. Hoping that it will eventually appear as a result of a merge.
2022.09.02 09:57:32.602418 [ 152 ] {} <Warning> prd_001.metrics_v12 (ReplicatedMergeTreePartCheckThread): Checking part 202208_754480_755274_7
2022.09.02 09:57:32.602441 [ 66 ] {} <Information> MergeFromLogEntryTask: DB::Exception: No active replica has part 202208_754480_755274_7 or covering part
2022.09.02 09:57:32.602542 [ 59 ] {} <Debug> MergeFromLogEntryTask: Don't have all parts (at least part 202208_754712_754897_6 is missing) for merge 202208_754480_755274_7; will try to fetch it instead
2022.09.02 09:57:32.603033 [ 152 ] {} <Warning> prd_001.metrics_v12 (ReplicatedMergeTreePartCheckThread): Checking if anyone has a part 202208_754480_755274_7 or covering part.
2022.09.02 09:57:32.604428 [ 152 ] {} <Information> prd_001.metrics_v12 (ReplicatedMergeTreePartCheckThread): Found parts with the same min block and with the same max block as the missing part 202208_754480_755274_7 on replica chi-ch-001-ch-001-0-0. Hoping that it will eventually appear as a result of a merge.
2022.09.02 09:57:32.604624 [ 232 ] {} <Warning> prd_001.metrics_v12 (ReplicatedMergeTreePartCheckThread): Checking part 202208_754480_755274_7
2022.09.02 09:57:32.604644 [ 59 ] {} <Information> MergeFromLogEntryTask: DB::Exception: No active replica has part 202208_754480_755274_7 or covering part
2022.09.02 09:57:32.604757 [ 67 ] {} <Debug> MergeFromLogEntryTask: Don't have all parts (at least part 202208_754712_754897_6 is missing) for merge 202208_754480_755274_7; will try to fetch it instead
2022.09.02 09:57:32.605251 [ 232 ] {} <Warning> prd_001.metrics_v12 (ReplicatedMergeTreePartCheckThread): Checking if anyone has a part 202208_754480_755274_7 or covering part

> A clear and concise description of what works not as it is supposed to.

Happened 2 days ago and the system can't recover since.

`Clickhouse version:`

SELECT version()

┌─version()─┐
│ 22.6.7.7  │
└───────────┘

These parts are totally missing from system.zookeeper table too. How to recover cluster nodes from this infinite dead loop?

**Comment by tavplubix** [comment]
Is replica chi-ch-001-ch-001-0-0 active?

**Comment by yandooo** [comment]
> Is replica chi-ch-001-ch-001-0-0 active?
Yes, it is. There was a ZK cluster outage somewhere around this happened.

**Comment by yandooo** [comment]
Given no other options left we had to delete the entire partition on primary node and it looks like resynching data from replica now

**Comment by yandooo** [comment]
@tavplubix primary and replica were online and constantly filling up logs with the errors mentioned in the ticket description. Restarting replica and/or primary didn't help.

**Comment by tavplubix** [comment]
What do you mean by "primary and replica"? ClickHouse does not have primary and secondary replicas (or masters and slaves), all ClickHouse replicas are equal. 

Anyway, provided logs are not enough to understand what happened. For example, what happened to part `202208_754712_754897_6`? Eventually it should have been either downloaded from some replica or replaced with empty part because it's "lost forever" . It might not happen in three cases:
 - Replica that has this part does not operate normally and part cannot be fetched
 - There's another (third) replica that is registered in zk and has this part according to zk, but actually that replica is dead or unavailable.
 - It's unknown bug in replication queue processing (highly unlikely)

If you're sure that it's the third case, then please share archives with full logs from all replicas.

**Comment by yandooo** [comment]
Yeah, they are all equal servers at the end of the day but given we explicitly define pair of "replicas" for each shard in the config file in order to differentiate just gave them names "primary" and "replica"/"secondary" in this ticket. Sorry if it's confusing.

```
<yandex>
    <remote_servers>
        <!-- User-specified clusters -->
        <ch-001>
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                    <host>chi-ch-001-ch-001-0-0</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>chi-ch-001-ch-001-0-1</host>
                    <port>9000</port>
                </replica>
            </shard>
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                    <host>chi-ch-001-ch-001-1-0</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>chi-ch-001-ch-001-1-1</host>
                    <port>9000</port>
                </replica>
            </shard>
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                    <host>chi-ch-001-ch-001-2-0</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>chi-ch-001-ch-001-2-1</host>
                    <port>9000</port>
                </replica>
            </shard>
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                    <host>chi-ch-001-ch-001-3-0</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>chi-ch-001-ch-001-3-1</host>
                    <port>9000</port>
                </replica>
            </shard>
        </ch-001>
```

```
select * from system.clusters
```

```
┌─cluster─────────────────────────────────────────┬─shard_num─┬─shard_weight─┬─replica_num─┬─host_name─────────────┬─host_address──────────────┬─port─┬─is_local─┬─user────┬─default_database─┬─errors_count─┬─slowdowns_count─┬─estimated_recovery_time─┐
│ all-replicated                                  │         1 │            1 │           1 │ chi-ch-001-ch-001-0-0 │ 2600:1f18:6c:4703:4a3a::1 │ 9000 │        0 │ default │                  │            0 │               0 │                       0 │
│ all-replicated                                  │         1 │            1 │           2 │ chi-ch-001-ch-001-0-1 │ 127.0.0.1                 │ 9000 │        1 │ default │                  │            0 │               0 │                       0 │
│ all-replicated                                  │         1 │            1 │           3 │ chi-ch-001-ch-001-1-0 │ 2600:1f18:6c:4704:11fb::2 │ 9000 │        0 │ default │                  │            0 │               0 │                       0 │
│ all-replicated                                  │         1 │            1 │           4 │ chi-ch-001-ch-001-1-1 │ 2600:1f18:6c:4705:d979::2 │ 9000 │        0 │ default │                  │            0 │               0 │                       0 │
│ all-replicated                                  │         1 │            1 │           5 │ chi-ch-001-ch-001-2-0 │ 2600:1f18:6c:4703:46e9::1 │ 9000 │        0 │ default │                  │            0 │               0 │                       0 │
│ all-replicated                                  │         1 │            1 │           6 │ chi-ch-001-ch-001-2-1 │ 2600:1f18:6c:4704:6db::2  │ 9000 │        0 │ default │                  │            0 │               0 │                       0 │
│ all-replicated                                  │         1 │            1 │           7 │ chi-ch-001-ch-001-3-0 │ 2600:1f18:6c:4705:1f1b::1 │ 9000 │        0 │ default │                  │            0 │               0 │                       0 │
│ all-replicated                                  │         1 │            1 │           8 │ chi-ch-001-ch-001-3-1 │ 2600:1f18:6c:4704:6ef9::1 │ 9000 │        0 │ default │                  │            0 │               0 │                       0
```

>  For example, what happened to part 202208_754712_754897_6? 
That's really the question here. Is there any set of commands to run to troubleshoot the issue next time? At the point of troubleshooting (few hours ago) this part `202208_754480_755274_7` is a future merge, `202208_754712_754897_6` were not able to locate in ZK paths nor on the file system for both replicas.

**Comment by tavplubix** [comment]
According to the result of `select * from system.clusters` you actually have (at least) 8 replicas, that's weird and probably some misconfiguration took place. I'm pretty sure that it was the first or the second case from my comment above. 

> were not able to locate in ZK paths  **_for both replicas_**.

Please check the rest 6 replicas. Also it make sense to look for all [non-disjoint](https://github.com/ClickHouse/ClickHouse/blob/4859e11c2701be4113d0ce262fa8b30e2fe1b676/src/Storages/MergeTree/MergeTreePartInfo.h#L92-L96) part, not only for exact part name 

> Is there any set of commands to run to troubleshoot the issue next time?

It's not clear what is the root case of the issue, so it's impossible to answer this question.
But usually there are two options:
 - wait for replica X to come back (ClickHouse will resolve the issue automatically and error will disappear)
 - run SYSTEM DROP REPLICA to drop faulty replica (and lose some data parts)

**Comment by yandooo** [comment]
@tavplubix the previous cluster config copy-paster didn't catch rest of records from `select * from system.clusters`:

```
┌─cluster─────────────────────────────────────────┬─shard_num─┬─shard_weight─┬─replica_num─┬─host_name─────────────┬─host_address──────────────┬─port─┬─is_local─┬─user────┬─default_database─┬─errors_count─┬─slowdowns_count─┬─estimated_recovery_time─┐
│ all-replicated                                  │         1 │            1 │           1 │ chi-ch-001-ch-001-0-0 │ 2600:1f18:6c:4703:4a3a::1 │ 9000 │        0 │ default │                  │            0 │               0 │                       0 │
│ all-replicated                                  │         1 │            1 │           2 │ chi-ch-001-ch-001-0-1 │ 127.0.0.1                 │ 9000 │        1 │ default │                  │            0 │               0 │                       0 │
│ all-replicated                                  │         1 │            1 │           3 │ chi-ch-001-ch-001-1-0 │ 2600:1f18:6c:4704:20aa::1 │ 9000 │        0 │ default │                  │            0 │               0 │                       0 │
│ all-replicated                                  │         1 │            1 │           4 │ chi-ch-001-ch-001-1-1 │ 2600:1f18:6c:4705:d979::2 │ 9000 │        0 │ default │                  │            0 │               0 │                       0 │
│ all-replicated                                  │         1 │            1 │           5 │ chi-ch-001-ch-001-2-0 │ 2600:1f18:6c:4703:46e9::1 │ 9000 │        0 │ default │                  │            0 │               0 │                       0 │
│ all-replicated                                  │         1 │            1 │           6 │ chi-ch-001-ch-001-2-1 │ 2600:1f18:6c:4704:d5c9::2 │ 9000 │        0 │ default │                  │            0 │               0 │                       0 │
│ all-replicated                                  │         1 │            1 │           7 │ chi-ch-001-ch-001-3-0 │ 2600:1f18:6c:4705:1f1b::1 │ 9000 │        0 │ default │                  │            0 │               0 │                       0 │
│ all-replicated                                  │         1 │            1 │           8 │ chi-ch-001-ch-001-3-1 │ 2600:1f18:6c:4704:aac::2  │ 9000 │        0 │ default │                  │            0 │               0 │                       0 │
│ all-sharded                                     │         1 │            1 │           1 │ chi-ch-001-ch-001-0-0 │ 2600:1f18:6c:4703:4a3a::1 │ 9000 │        0 │ default │                  │            0 │               0 │                       0 │
│ all-sharded                                     │         2 │            1 │           1 │ chi-ch-001-ch-001-0-1 │ 127.0.0.1                 │ 9000 │        1 │ default │                  │            0 │               0 │                       0 │
│ all-sharded                                     │         3 │            1 │           1 │ chi-ch-001-ch-001-1-0 │ 2600:1f18:6c:4704:20aa::1 │ 9000 │        0 │ default │                  │            0 │               0 │                       0 │
│ all-sharded                                     │         4 │            1 │           1 │ chi-ch-001-ch-001-1-1 │ 2600:1f18:6c:4705:d979::2 │ 9000 │        0 │ default │                  │            0 │               0 │                       0 │
│ all-sharded                                     │         5 │            1 │           1 │ chi-ch-001-ch-001-2-0 │ 2600:1f18:6c:4703:46e9::1 │ 9000 │        0 │ default │                  │            0 │               0 │                       0 │
│ all-sharded                                     │         6 │            1 │           1 │ chi-ch-001-ch-001-2-1 │ 2600:1f18:6c:4704:d5c9::2 │ 9000 │        0 │ default │                  │            0 │               0 │                       0 │
│ all-sharded                                     │         7 │            1 │           1 │ chi-ch-001-ch-001-3-0 │ 2600:1f18:6c:4705:1f1b::1 │ 9000 │        0 │ default │                  │            0 │               0 │                       0 │
│ all-sharded                                     │         8 │            1 │           1 │ chi-ch-001-ch-001-3-1 │ 2600:1f18:6c:4704:aac::2  │ 9000 │        0 │ default │                  │            0 │               0 │                       0 │
│ ch-001                                          │         1 │            1 │           1 │ chi-ch-001-ch-001-0-0 │ 2600:1f18:6c:4703:4a3a::1 │ 9000 │        0 │ default │                  │            0 │               0 │                       0 │
│ ch-001                                          │         1 │            1 │           2 │ chi-ch-001-ch-001-0-1 │ 127.0.0.1                 │ 9000 │        1 │ default │                  │            0 │               0 │                       0 │
│ ch-001                                          │         2 │            1 │           1 │ chi-ch-001-ch-001-1-0 │ 2600:1f18:6c:4704:20aa::1 │ 9000 │        0 │ default │                  │            0 │               0 │                       0 │
│ ch-001                                          │         2 │            1 │           2 │ chi-ch-001-ch-001-1-1 │ 2600:1f18:6c:4705:d979::2 │ 9000 │        0 │ default │                  │            0 │               0 │                       0 │
│ ch-001                                          │         3 │            1 │           1 │ chi-ch-001-ch-001-2-0 │ 2600:1f18:6c:4703:46e9::1 │ 9000 │        0 │ default │                  │            0 │               0 │                       0 │
│ ch-001                                          │         3 │            1 │           2 │ chi-ch-001-ch-001-2-1 │ 2600:1f18:6c:4704:d5c9::2 │ 9000 │        0 │ default │                  │            0 │               0 │                       0 │
│ ch-001                                          │         4 │            1 │           1 │ chi-ch-001-ch-001-3-0 │ 2600:1f18:6c:4705:1f1b::1 │ 9000 │        0 │ default │                  │            0 │               0 │                       0 │
│ ch-001                                          │         4 │            1 │           2 │ chi-ch-001-ch-001-3-1 │ 2600:1f18:6c:4704:aac::2  │ 9000 │        0 │ default │                  │            0 │               0 │                       0
```

the actual cluster config is `ch-001`

thanks for giving advise on running drop replica.

**Comment by tbragin** [comment]
Question appears answered, closing.
