### ISSUE TITLE
Build Failed on  macOS 12.5.1  llvm13

### ISSUE THREAD

**Issue by Lucky-Chang** [ClickHouse/ClickHouse#40937]
The entire build process succeed. But clickhouse-server binary startup with segmentfault.
It seems that OwnSplitChannel.h is ambiguous in same binary because of different `WITH_TEXT_LOG` compile flag.

**Operating system**
macOS 12.5.1

**Cmake version**
cmake version 3.22.2

**Ninja version**
1.10.2

**Compiler name and version**
llvm13

**Full cmake and/or ninja output**

**Comment by Lucky-Chang** [comment]
https://github.com/ClickHouse/ClickHouse/pull/40938

**Comment by alexey-milovidov** [comment]
We use LLVM 14, not LLVM 13.
Build logs and binaries are here: https://s3.amazonaws.com/clickhouse-builds/0/51e7fd1668630f668e15b91a0ee02bedc0d402ef/clickhouse_special_build_check/report.html
