### ISSUE TITLE
Column name lost to default expression name

### ISSUE THREAD

**Issue by liumaojing** [ClickHouse/ClickHouse#40932]
**Describe the issue**
CREATE TABLE t7
(
    `id` Int32,
    `insert_time` String DEFAULT 'aa',
    `_all` String MATERIALIZED formatRow('JSONEachRow', insert_time)
)
ENGINE = MergeTree
ORDER BY id

insert into table t7 (id) values (1);
**How to reproduce**
select _all from t7;

_all
 {"CAST('aa', 'String')":"aa"}

**Expected behavior**
_all
  {"insert_time":"aa"}

**Comment by rfraposa** [comment]
@liumaojing - if you `MATERIALIZE` the materialized column, you get the expected value:

```
ALTER TABLE t7 MATERIALIZE COLUMN _all
```

```
select _all from t7;

{"insert_time":"aa"}
```

**Comment by liumaojing** [comment]
> @liumaojing - if you `MATERIALIZE` the materialized column, you get the expected value:
> 
> ```
> ALTER TABLE t7 MATERIALIZE COLUMN _all
> ```
> 
> ```
> select _all from t7;
> 
> {"insert_time":"aa"}
> ```

I tried it and it worked  ,(version:22.3), I don't understand why the materialized view column can't be generated directly when it's rewritten, so it needs to be materialized again

**Comment by rfraposa** [comment]
Good question. Imagine a table with 1 billion rows, and you add a new materialized column. That could take a very long to populate the new column! By not materializing it automatically, this allows you to control the behavior and materialize how and when you want to.

**Comment by liumaojing** [comment]
i got it,But according to my example,the materialized view field wants to generate Json behavior that takes effect when writting is performed, not after I perform 'ALTER MATERIALIZE COLUMN' ,why?

**Comment by rfraposa** [comment]
I think you still need to call `ALTER TABLE t7 MATERIALIZE COLUMN _all` whether it's before or after you have inserted rows. The docs show it this way too - even though it is not specifically mentioned in the docs that you must call MATERIALIZE: https://clickhouse.com/docs/en/sql-reference/statements/alter/column/#materialize-column

**Comment by liumaojing** [comment]
> ALTER TABLE t7 MATERIALIZE COLUMN _all

For materialized column,I find the default expression value  that you can write to directly,but I still don't understand why the change of column name and expression name needs to be 'ALTER MATERIALIZE COLUMN' .
I think that need to add ColumnsWithTypeAndName of Block with the original column name instead of the expression column name
