### ISSUE TITLE
Allow macro substitution in endpoint config parameter in storage_configuration section

### ISSUE THREAD

**Issue by ekonkov** [ClickHouse/ClickHouse#40951]
It is convenient for managing huge clusters to allow using macros in endpoint config parameter in storage_configuration section similar to zookeeper paths - https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/replication#creating-replicated-tables

This will allow to place files in S3 buckets on per shard basis for example.

**Comment by alesapin** [comment]
can you provide several examples what you exactly want (config, create query and so on)

**Comment by ekonkov** [comment]
Config fragment same for all hosts in cluster should look like this, contains secret credentials:
```
<yandex>
     <macros incl="macros" optional="true" replace="true" />
    <storage_configuration>
        <disks>
            <s3_some_disk>
                <type>s3</type>
                <endpoint>https://s3-host.net/<bucket-name>/some-sub-dir/{shard}/</endpoint>
                <access_key_id>xxxxxxxxx</access_key_id>
                <secret_access_key>xxxxxxxxxxx</secret_access_key>
            </s3_some_disk>
        </disks>
        <policies>
 ...
        </policies>
    </storage_configuration>
</yandex>
```

Included file - autogenerated on each host in huge cluster with its own values in shard and replica tags:
```
<yandex>
        <macros>
                <shard>001</shard>
                <replica>somehost001-1.somedomain.net</replica>
        </macros>
</yandex>
```

This will allow us to place files for different shards in different folders in S3 or even in different buckets - one per shard.
