### ISSUE TITLE
Sporadic: 02277_full_sort_join_misc fails

### ISSUE THREAD

**Issue by devcrafter** [ClickHouse/ClickHouse#40977]
**Describe the bug**
02277_full_sort_join_misc fails sporadically

See CI database:
https://play.clickhouse.com/play?user=play&url=https%3A%2F%2Fplay.clickhouse.com%2F#U0VMRUNUICogRlJPTSBjaGVja3MgV0hFUkUgdGVzdF9zdGF0dXMgPSAnRkFJTCcgQU5EIHRlc3RfbmFtZSA9ICcwMjI3N19mdWxsX3NvcnRfam9pbl9taXNjJwpPUkRFUiBCWSBjaGVja19zdGFydF90aW1lIERFU0MK

**Error message and/or stacktrace**
- https://s3.amazonaws.com/clickhouse-test-reports/40305/5d7fa55f36c6b35a2c8afcc6b7d6f82a52e150bb/stateless_tests__ubsan_.html
- https://s3.amazonaws.com/clickhouse-test-reports/40305/5d7fa55f36c6b35a2c8afcc6b7d6f82a52e150bb/stateless_tests__aarch64_.html

**Comment by vdimir** [comment]
https://github.com/ClickHouse/ClickHouse/pull/40966
