### ISSUE TITLE
replaceRegexpAll for UTF8 languages with w as a word regex

### ISSUE THREAD

**Issue by SharonCastel** [ClickHouse/ClickHouse#40970]
Hi Guys,
I would like to have the word regex of every sentence in every lang without symbols.
When executing the replaceRegexpAll function on other languages as Hebrew / Chinese / Portuguese and others with special characters,  I'm getting an empty string:
select trim(replaceRegexpAll(lower('ירושלים'), '[^\w]+', ' '))
returns an empty string 
so I understand that for every lang I need to add the specific case in the regex like this:
select trim(replaceRegexpAll(lower('ירושלים'), '[^\wא-ת]+', ' '))
and if I have special characters I need also to replace them with regulars with otherwise it also return empty string:
select trim(replaceRegexpAll(lower('áéíóúÁÉÍÓÚÖöÜüĞİŞşÇəı'), '[^\wא-ת]+', ' '))
so I need this:
select trim(replaceRegexpAll(lower(translateUTF8('áéíóúÁÉÍÓÚÖöÜüĞİŞşÇəı', 'áéíóúÁÉÍÓÚÖöÜüĞİŞşÇəı', 'aeiouAEIOUOoUuGISsCei')), '[^\wא-ת]+', ' '))
which returns the result: aeiouaeiouoouugisscei
I feel like for multi language dictionary the preprocessing like this will take forever.
So I hope I miss something and you will have me the magic function for all together if there is...
Thank,
Sharon.

**Comment by rschu1ze** [comment]
Hi Sharon,

I am not sure if I understand your question correctly.

You goal is to build a regex which matches a "word" in all languages, right? I am not a trained linguist but AFAIK in all western writing systems (including Portugese) and in Hebrew and in Chinese and in Arabic, "words" are separated by whitespaces. And that can be expressed in [re2 syntax](https://github.com/google/re2/wiki/Syntax) using `\w`, `\W`, `\b` etc.

Or do you want to to build a regex which matches "sentences" in all languages. Again, in the languages I know of that can be achieved by matching a sequence of "words" (see above) that end in a sentence stop symbol, e.g. `.`, `!`, `?` etc. (In fact, Spanish has `¿` as a sentence stop symbol, meaning that any such regex can only be language-specific...)

> select trim(replaceRegexpAll(lower('ירושלים'), '[^\w]+', ' '))

So this regex matches all (non-empty) sequences of non-word characters. This includes ` ` (single space) and `.` (dot). It actually matches everything which is not [0-9A-Za-z_], in particular Hebrew characters. So I think this will not produce correct results for all languages. Re2 offers Unicode character for specific languages, e.g. `Hebrew`, perhaps you want to try these?

> 
select trim(replaceRegexpAll(lower(translateUTF8('áéíóúÁÉÍÓÚÖöÜüĞİŞşÇəı', 'áéíóúÁÉÍÓÚÖöÜüĞİŞşÇəı', 'aeiouAEIOUOoUuGISsCei')), '[^\wא-ת]+', ' '))

If I read correctly, this regex does the job but it is slow, right? Again, I suggest to match against the unicode character classes to avoid usage of `translateUTF8()`.

**Comment by SharonCastel** [comment]
Hi Robert, 
Thank you for a nice explained answer!
I would like to have the word regex of every sentence in every language without symbols.
The wishful thinking was '[^\w]+ would be good enough for all languages.
But then I figured it out and got for some langs empty string instead of the right results with that language word.
So for every new language that I find for each customer its different and I wish it was compatible for all.
As I understand from your answer there is no simple way, right?
Also as you recommend, can I replace the translateUTF8 with map? like Denny wrote here: https://stackoverflow.com/questions/69150435/how-replace-each-accented-characters-with-non-accented-characters-foreach-word-i

**Comment by rschu1ze** [comment]
Regexp `[^\w]+` (which is equivalent to `[\W]+`) matches one or more non-"word characters", i.e. everything which is not A-Z, a-z, 0-9, or the underscore _. That includes whitespaces, punctuation characters but also special letters like äöüß in my language (German). In the sense of the definition, some languages (= non-western languages to be precise), e.g. Hebrew and Arabic, are entirely made up of non-"word characters".

So the regex doesn't match "words" at all, it matches everything except words. I think you would like to reverse it to `[\w]+`.

Let's try matching with some (absurd) examples. Will use `extractAll()` for simplicitly.

```sql
select extractAll('Hallo Welt', '[\w]+')
-- ['Hallo','Welt']

select extractAll('Hällo Wölt', '[\w]+')
-- ['H','llo','W','lt'] -- "unexpected" result because the regex doesn't match [special characters](https://en.wikipedia.org/wiki/German_orthography#Special_letters)

select extractAll('Hällo Wölt', '[\wäö]+')
-- ['Hällo','Wölt'] -- with an extended regex the result matches a "word" again

select extractAll('Hällo Wölt Αθηνά', '[\wäö]+')
-- ['Hällo','Wölt'] -- the same regex doesn't match Greek characters

select extractAll('Hällo Wölt Αθηνά', '[\wäö\p{Greek}]+')
-- ['Hällo','Wölt','Αθηνά'] -- but we can extend it with the ["Greek" character class](https://github.com/google/re2/wiki/Syntax)

```

I think that you can achieve your goal like in the last example by matching against as many character classes as you need. You wouldn't need to do slow replacements like `translateUTF8()` or the map trick you referenced.

**Comment by SharonCastel** [comment]
Just to update you Robert...
I found my solution with the regex \p{L}:
\p{L} => matches any kind of letter from any language
as I checked until now it gave me the expected result.
Thanks for the help.
