### ISSUE TITLE
URL --> Parquet Schema Inference

### ISSUE THREAD

**Issue by alanpaulkwan** [ClickHouse/ClickHouse#40985]
Would it be possible to do this?
```

SELECT *
FROM url('https://www.dropbox.com/s/kocnhtzxgaih2rg/crsp_dsenames.parquet?dl=1', Parquet)

```

Right now it complains I have to specify structure, but it's a Parquet file and Clickhouse otherwise supports schema inference on Parquet files. I hope it's straightforward to shoehorn that code. Thanks!

**Comment by Avogar** [comment]
There is a problem with redirects while senging requests to this URI, at some point we get relative path in Location header:
`Location: /s/dl/kocnhtzxgaih2rg/crsp_dsenames.parquet` and we don't expect it. We can improve this place

**Comment by alanpaulkwan** [comment]
Amazing!
