### ISSUE TITLE
Disable MySQL and PostgreSQL interfaces

### ISSUE THREAD

**Issue by FedericoCeratto** [ClickHouse/ClickHouse#40994]
The documentation on https://clickhouse.com/docs/en/interfaces/mysql and https://clickhouse.com/docs/en/interfaces/postgresql does not describe if it's possible to stop listening on the two local TCP ports and how to do it.

On ClickHouse 21.8.14.5 the ports are enabled by default. IMHO, if possible they should be disabled by default for better security.

**Comment by vdimir** [comment]
To disable it, you may remove `<mysql_port>...</mysql_port>` and `<postgresql_port>...</postgresql_port>` from the config.

Example config:

<details>
<summary>config.xml</summary>

```xml
<?xml version="1.0"?>
<clickhouse>
    <logger>
        <level>trace</level>
        <console>true</console>
    </logger>

    <http_port>8123</http_port>
    <tcp_port>9000</tcp_port>
    <!-- <mysql_port>9004</mysql_port> -->
    <!-- <postgresql_port>9005</postgresql_port> -->

    <path>./</path>

    <mlock_executable>true</mlock_executable>

    <users>
        <default>
            <password></password>

            <networks>
                <ip>::/0</ip>
            </networks>

            <profile>default</profile>
            <quota>default</quota>
            <access_management>1</access_management>
        </default>
    </users>

    <profiles>
        <default/>
    </profiles>

    <quotas>
        <default />
    </quotas>
</clickhouse>
```

</details>

Or if you don't use external config:

```
clickhouse server  -- --mysql_port='' --postgresql_port=''
```

**Comment by vdimir** [comment]
What if you just remove entries from the config?

**Comment by alexey-milovidov** [comment]
ClickHouse 21.8 is not supported anymore, you should upgrade to a recent version.

**Comment by den-crane** [comment]
@FedericoCeratto try

```xml
# cat /etc/clickhouse-server/config.d/xxx.xml

<?xml version="1.0" ?>
<yandex>
    <mysql_port remove="1"/>
    <postgresql_port remove="1"/>
</yandex>
```

**Comment by FedericoCeratto** [comment]
@den-crane that worked, thank you!
