### ISSUE TITLE
clickhouse query result show ellipsis

### ISSUE THREAD

**Issue by wang233work** [ClickHouse/ClickHouse#40992]
if i insert into clickhouse a  long string ,then i query ,i find the result incomplete display,what can i do to slove this .

**Comment by wang233work** [comment]
the config all default

**Comment by vdimir** [comment]
It depends on the output format you use.
By default it's `PrettyCompact` in the interactive mode, it can trim strings
You can use any you need with `SELECT ... FROMAT <format_name>`. https://clickhouse.com/docs/en/interfaces/formats

```bash
$ clickhouse client -q "select repeat('a', 100000) FORMAT PrettyCompact" | wc -c
11518
$ clickhouse client -q "select repeat('a', 100000) FORMAT TSV" | wc -c
100001
```

**Comment by den-crane** [comment]
There are settings

  --output_format_pretty_max_column_pad_width arg                      Maximum width to pad all values in a column in Pretty formats.
  --output_format_pretty_max_value_width arg                           Maximum width of value to display in Pretty formats. If greater - it will be cut.

**Comment by wang233work** [comment]
i see https://clickhouse.com/docs/en/operations/settings/settings/#output_format_pretty_max_value_width ,but my clickhouse version is 20.3.9.70,it depends on sentry version 22.6.0,and it did not have output_format_pretty_max_value_width ,can i insert one?
from sentry i can see the message like this 
![image](https://user-images.githubusercontent.com/57163477/188557082-0615d054-0e8c-45f1-b87c-65b4af436ac7.png)

**Comment by wang233work** [comment]
now i try other outputformat to solve this problem
