### ISSUE TITLE
parseKeyValue function

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#41009]
**Use case**

Parsing semistructured key-value data (logs etc).

**Describe the solution you'd like**

```
SELECT parseKeyValue('a=b, b=c', ',' /* list of characters / item separators  */, '=' /* character separating the key and value */;

{'a': 'b', 'b': 'c'}

SELECT parseKeyValue('2582511992885811767 Qfic=QELUWB, BciBbb=9, IeyClzKmrs {Pvkrq=86093, Glhbmwg=5, FtuzyjOsf=66, YssMbiUswk=0, AxuDcgzkpx=1, KacsIbu=277, MgmjkhKh=9q60pqp43s246u2745, KucFjl=61350852, SdfbJshj=5462619308589345326}, UzfFmg {IsaRubn=3, PqgPmah=954, JagRddm=31692}, KnxKigysBjo {Mnfmybl=7941, Vnvpht=xghk, BgqvTj=9843, UlnrrCr=72940085719217638, YawhzZkqv=260753, QyxbSqamh=627.4022, Ulejhjgk=-0, DjyecbleCqazeZdyc=2229740235971220001, YocxsggkXvxwWzgd=2320663994026035210, NhntkbcQzghj=6}, Rdodi {OSERVWEI_MIVZAPPDLCR_JT="068G14THM", KFQMUR_HXEVFA="XZSQ", DVCRIJ_ZOUMQ_DD="P0889542750958729205", XNFHGSSF_RHRUZHVBS_KWBT="F", DIOQZO_PVNNTGISHEH_VB="bmhncvchhrepqnxb", BHMYYKME_VCPWN_QR=754501869725462264, SYZIWCHJK=2z1791877467804982}, Zfv {AyvbOrexdlUdzj="GESF", FescvXwmfFlgijw="RPUGI|RULHKBESCT", RvnzbdkCwjt="3087"}, UetXuhy {R_YU_FVBD_TCGUTEDZU_BBVAK=0422461531412992163, G_OV_WBLZ_WMMJKMHQZ=5216958198816473961, B_REU_XUQXBYR_LVOIMULK_MMSN=IcmniychTgxn{unsaurbrLnaqQc=1, fbqiUtcjYul=20911}}, AuorsGvyImnh {P_EWJN="JFVL"}', ',', '=');

{'Qfic': 'QELUWB', 'BciBbb': '9', 'Pvkrq': '86093', 'Glhbmwg': '5', 'FtuzyjOsf': '66', 'YssMbiUswk': '0', 'AxuDcgzkpx': '1', 'KacsIbu': '277', 'MgmjkhKh': '9q60pqp43s246u2745', 'KucFjl': '61350852', 'SdfbJshj': '5462619308589345326', 'IsaRubn': '3', 'PqgPmah': '954', 'JagRddm': '31692', 'Mnfmybl': '7941', 'Vnvpht': 'xghk', 'BgqvTj': '9843', 'UlnrrCr': '72940085719217638', 'YawhzZkqv': '260753', 'QyxbSqamh': '627', 'Ulejhjgk': '', 'DjyecbleCqazeZdyc': '2229740235971220001', 'YocxsggkXvxwWzgd': '2320663994026035210', 'NhntkbcQzghj': '6', 'OSERVWEI_MIVZAPPDLCR_JT': '068G14THM', 'KFQMUR_HXEVFA': 'XZSQ', 'DVCRIJ_ZOUMQ_DD': 'P0889542750958729205', 'XNFHGSSF_RHRUZHVBS_KWBT': 'F', 'DIOQZO_PVNNTGISHEH_VB': 'bmhncvchhrepqnxb', 'BHMYYKME_VCPWN_QR': '754501869725462264', 'SYZIWCHJK': '2z1791877467804982', 'AyvbOrexdlUdzj': 'GESF', 'FescvXwmfFlgijw': 'RPUGI|RULHKBESCT', 'RvnzbdkCwjt': '3087', 'R_YU_FVBD_TCGUTEDZU_BBVAK': '0422461531412992163', 'G_OV_WBLZ_WMMJKMHQZ': '5216958198816473961', 'B_REU_XUQXBYR_LVOIMULK_MMSN': 'IcmniychTgxn', 'unsaurbrLnaqQc': '1', 'fbqiUtcjYul': '20911', 'P_EWJN': 'JFVL'}
```

It should also support quoted strings/values. 

**Describe alternatives you've considered**

* Regexp - slow, looks ugly.
* JSON parsers - don't work if key-value pairs are not JSON.
* URL parsers - work only for URL.
* UDF - also rather slower, and spliting key-value pairs it quite common task for logs.

**Additional context**

Log parsing engines line splunk / datadog 
https://www.splunk.com/en_us/blog/tips-and-tricks/key-value-pair-extraction-definition-examples-and-solutions.html
https://docs.datadoghq.com/logs/log_configuration/parsing/?tab=matchers#key-value-or-logfmt

**Comment by alexey-milovidov** [comment]
The main concern is the escaping rules. They are too ambiguous for these type of formats.
But if they are unspecified, it makes it worse.

A viable alternative will be `parseRow` function which will use one of the available ClickHouse formats, like TSKV.
The advantage is that all ClickHouse formats are well specified.

**Comment by filimonov** [comment]
> A viable alternative will be parseRow function which will use one of the available ClickHouse formats, like TSKV.
> The advantage is that all ClickHouse formats are well specified.

Yep, that would be great but does not solve the task (maybe unless we will add something like {kvpairs} placeholder to Template).

> The main concern is the escaping rules. They are too ambiguous for these type of formats.
 
I think 'best effort' should be enough, in datadog that's also configurable (see https://docs.datadoghq.com/logs/log_configuration/parsing/?tab=matchers#key-value-or-logfmt ) 

Question: is it possible for that function to return Object(JSON) with subcolumns? How big effort is needed? That would be even better than Map...

**Comment by arthurpassos** [comment]
Another interesting ref: https://docs.vmware.com/en/vRealize-Log-Insight/8.8/com.vmware.log-insight.agent.admin.doc/GUID-CBCCEA48-35E2-44F0-BDBE-8CC53621886F.html

**Comment by filimonov** [comment]
More references:

* datadog https://docs.datadoghq.com/logs/log_configuration/parsing/?tab=matchers#key-value-or-logfmt
* vector.dev https://vector.dev/docs/reference/vrl/functions/#parse_key_value + https://vector.dev/docs/reference/vrl/functions/#parse_logfmt ( see also https://brandur.org/logfmt)
* fluentd https://shihadeh.dev/ruby-gems/Key-ValueParser/
* logstash https://www.elastic.co/guide/en/logstash/current/plugins-filters-kv.html 
* splunk https://docs.splunk.com/Documentation/SplunkCloud/latest/SearchReference/Extract + https://docs.splunk.com/Documentation/Splunk/9.0.4/Admin/Propsconf


https://pkg.go.dev/github.com/kr/logfmt
