### ISSUE TITLE
SQL hanging for days after Exception Cannot write to ostream at offset

### ISSUE THREAD

**Issue by qmdt** [ClickHouse/ClickHouse#41003]
Hi guys, 
I have many tables created in MySQL engine, and I  found that when I run the query "select * from system.tables"，the server would try to test the connection with MySQL through Ping, and this will cost much time ,as i have got about 1300 tables created in MySQL engine, the query returns in about half an hour. 

the problem is that **I found the query still stay in system.processes after i ran it a few days ago.** the log of the query thread is like below:
![image](https://user-images.githubusercontent.com/8369775/188465839-b6640194-102f-444d-9c4e-3489cd9dc80f.png)

can anyone tell me why the query was not deleted after the exception "cannot write to ostream at offset xxx"， or is there any relation between  the two things? 

thanks a lot.

BTW，my version is 21.3.4.25

**Comment by den-crane** [comment]
21.3.4.25 is out of support. Check this issue in supported versions, for example 22.8.
