### ISSUE TITLE
FROM table SELECT column

### ISSUE THREAD

**Issue by ramazanpolat** [ClickHouse/ClickHouse#41018]
**Use case**

We're building a publicly available CH query interface (like Play UI but with enhanced capabilities like exploring the data and other goodies).
Essentially, it will contain TBs of publicly available blockchain analytics data served over browser and powered by CH.
Thousands of users are expected to use the UI and send arbitrary SQL statements to our CH cluster.
For the best experience, we want to provide fast, intuitive and seamless environment for the users.

As you can guess, the product is all about writing ad-hoc queries. 
Considering the number of tables, it becomes really hard to use the mouse to explore the data and to type the table/column names with the keyboard.
This is why we have implemented autocomplete into our SQL editor.
One significant problem about the autocomplete is that the system cannot know beforehand the column names of the table unless the table name is provided.

**Describe the solution you'd like**

If somehow users provide the table name first then all the column names would be inferred and could be autocompleted, only if CH supports this:

```sql
FROM table
SELECT *
```
It is a simple yet powerfull way to increase the user experience. This project will also lead lots of users to get to know CH and show the world that there is a better DBMS.

**Comment by den-crane** [comment]
You should implement own DSL which is aware about your object and business domain.

**Comment by alexey-milovidov** [comment]
@den-crane I'd disagree.

ClickHouse may be the only DBMS that you can use to provide raw SQL access to a wide user base and get away with it,
because it has good support for query limitations, RBAC, row-level security, out-of-band filters, resource metering, and quotas.

While it cannot even be imagined with MySQL or Postgres, this scenario works perfectly with ClickHouse.

The SQL language is way more friendly than in other SQL DBMS.
We should encourage providing direct ClickHouse SQL querying capabilities to users.

**Comment by den-crane** [comment]
I don't mind about this feature.
I just see how DSL will simplify and improve everything in this use-case.

**Comment by filimonov** [comment]
Some related discussions:
https://softwareengineering.stackexchange.com/questions/127706/why-is-the-select-before-the-from-in-an-sql-query
https://stackoverflow.com/questions/5074044/shouldnt-from-come-before-select-in-sql

In MS Linq it's done this way.
https://docs.microsoft.com/en-us/dotnet/csharp/linq/query-expression-basics

I don't have any strong option about that. Changing the dialect just for better intellisense... 
I it will be taken - I would prefer to see a good tests coverage for checking complex cases (with subqueries, ctes, aliases, joins, unions etc etc), also checking the behaviour for ambiguis cases (FROM x SELECT a FROM y) etc.
