### ISSUE TITLE
 RENAME EXCHANGE is not supported on  22.8.4

### ISSUE THREAD

**Issue by yangshike** [ClickHouse/ClickHouse#41024]
hello. wen i running exchange tables i got error :

ck2 :) exchange  tables  bigdata.service_stat_new and bigdata.service_stat_new1;

EXCHANGE TABLES bigdata.service_stat_new AND bigdata.service_stat_new1

Query id: df996a77-f2ed-4b32-a45b-7bf2f9b8f403

0 rows in set. Elapsed: 0.001 sec.

Received exception from server (version 22.8.4):
Code: 48. DB::Exception: Received from 127.0.0.1:9000. DB::Exception: RENAME EXCHANGE is not supported. (NOT_IMPLEMENTED)

ck2 :) show create database bigdata;

SHOW CREATE DATABASE bigdata

Query id: b89e10c8-8a92-4fdb-9e96-fdf359a4b1d2

┌─statement──────────────────────────────────┐
│ CREATE DATABASE bigdata
ENGINE = Atomic │
└────────────────────────────────────────────┘

1 row in set. Elapsed: 0.001 sec.

This is My OS information：
#cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core)
# uname -a
Linux ck2 3.10.0-1160.36.2.el7.x86_64 #1 SMP Wed Jul 21 11:57:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Did I forget what configuration？

**Comment by den-crane** [comment]
What file system do you use?

It seems kernel 3.10.0 does not support  RENAME_EXCHANGE https://man7.org/linux/man-pages/man2/rename.2.html

**Comment by yangshike** [comment]
thank you,
system is xfs and ext4 .
