### ISSUE TITLE
The changelog in Chinese has unreasonable and outdated mistranslations

### ISSUE THREAD

**Issue by linghengqian** [ClickHouse/ClickHouse#41043]
(you don't have to strictly follow this form)

**Describe the issue**
A clear and concise description of what's wrong in documentation.

- The changelog in Chinese has unreasonable and outdated mistranslations.  For example, `碌莽禄release拢.0755-88888888` is actually a malicious advertising call, which will mislead people viewing the document. Refer to https://clickhouse.com/docs/zh/changelog/ and https://clickhouse.com/docs/en/whats-new/changelog/  .
- The documentation has some unreasonable translation behavior. For example, there are machine translations of `阿利沙平`, `阿列克谢-米洛维多夫`, but there are English names like `Ilya Yatsishin`. As a habit, I think the English name of github should be used uniformly for people's names. 
- 
![image](https://user-images.githubusercontent.com/20187731/188630976-fda2afab-c423-4756-8887-5606fcf00ede.png)
- 
![image](https://user-images.githubusercontent.com/20187731/188631051-665f290b-fcea-4615-acd8-c29c07b7c468.png)

**Additional context**

- I will try to submit a documentation PR that adds the missing new version changelog.

**Comment by vdimir** [comment]
Chinese documentation is community supported so it can be outdated, unfortunately.

> I will try to submit a documentation PR that adds the missing new version changelog

Thank you, @linghengqian. We appreciate it!

You can link PR to this issue

**Comment by alexey-milovidov** [comment]
The Chinese changelog was machine translated (a.k.a. garbage). Let's remove it completely.

**Comment by alexey-milovidov** [comment]
Machine translation to/from Chinese is like

![spit-water](https://user-images.githubusercontent.com/18581488/189005608-e0e97da3-72c6-41f9-9239-521aaefdc92c.gif)
