### ISSUE TITLE
insert_deduplication_token and data consistency between replicas

### ISSUE THREAD

**Issue by vigliag** [ClickHouse/ClickHouse#41048]
Hi, we were looking into `insert_deduplication_token` and we think we found a case when it could lead to data inconsistencies between replicas.

Our scenario is the following:

- a worker continually inserts data into a ReplicatedMergeTree table via the HTTP API
- the table where we insert the data has a timestamp column defaulting to now()
- replication is currently lagging behind

Steps:

1. the worker tries to insert some data on replica A, using `insert_deduplication_token=abc`. Data was inserted correctly in A and ClickHouse sets the timestamp column to default value of `now() = 123`, but due to a network error the worker does not receive the response.
2. the worker retries the same exact insert on replica B. When running the query, B sets the timestamp column to the default value of `now() = 124`. B detects the data duplication (the `block_id` matches because of `insert_deduplication_token`), and since it does not yet have a copy of the data (replication is lagging), it writes the received data to disk as though it was received via replication.
3. at this point the two replicas have different data. A client querying replica A will see timestamp=123, while querying replica B will see timestamp=124

Our understanding is that the affected data in A and B will stay different until the part containing it gets merged and replicated. Is our understanding correct?

This behavior of `insert_deduplication_token` when replication is lagging is surprising and possibly undesired. It might be useful to adopt (or allow the user to opt in) a different semantic and have CH return an error instead.

**Comment by vigliag** [comment]
cc @nvartolomei

**Comment by den-crane** [comment]
insert_deduplication_token is not related to replication, it does not matter how large the replication lag.

insert_deduplication_token and usual deduplication creates a record in ZK on insert

https://kb.altinity.com/altinity-kb-schema-design/insert_deduplication/

**Comment by den-crane** [comment]
>B detects the data duplication (the block_id matches because of insert_deduplication_token), 
>and since it does not yet have a copy of the data (replication is lagging),
> it writes the received data to disk as though it was received via replication.

I see, you mean that it is possible to insert different data (with different part checksum) using insert_deduplication_token into 2 replicas.

**Comment by vigliag** [comment]
Hi @den-crane, yes. In particular due to the logic around this line https://github.com/ClickHouse/ClickHouse/blob/master/src/Storages/MergeTree/ReplicatedMergeTreeSink.cpp#L458-L461 according to which, once a block is detected as a duplicate of a block in another replica, it is written locally as if it was that one instead of waiting for replication.

**Comment by den-crane** [comment]
yes it was implemented in https://github.com/ClickHouse/ClickHouse/pull/11684

**Comment by den-crane** [comment]
BTW it could be an issue  even without replication lag and a single replica if you use `now()` for partitioning column because insert_deduplication_token is checked for a partition.

**Comment by den-crane** [comment]
repro:

```sql

replica1: create table test1(A Int64, B String)Engine=ReplicatedMergeTree('/clickhouse/{cluster}/tables/test1', '{replica}') order by A;
replica2: create table test1(A Int64, B String)Engine=ReplicatedMergeTree('/clickhouse/{cluster}/tables/test1', '{replica}') order by A;

replica2: system stop fetches test1;

replica1: insert into test1 values settings insert_deduplication_token = 'test' (1,1) ;
select * from test1;
┌─A─┬─B─┐
│ 1 │ 1 │
└───┴───┘

replica2: insert into test1 values settings insert_deduplication_token = 'test' (1,2) ;
select * from test1;
┌─A─┬─B─┐
│ 1 │ 2 │
└───┴───┘

replica2: system start fetches test1;

replica2: optimize table test1 final;
replica2: select * from test1;
┌─A─┬─B─┐
│ 1 │ 1 │
└───┴───┘


replica1: select * from test1;
 ┌─A─┬─B─┐
│ 1 │ 1 │
└───┴───┘
```

**Comment by nvartolomei** [comment]
> @den-crane "so the issue will be resolved with a next merge"

That's not guaranteed to happen and you could interpret this behaviour as "data loss" rather than "resolving the issue".

Re guaranteed: a) A part can be inserted in an old partition on a busy server that won't ever schedule merges for that old partition; b) A part can be inserted into a partition where parts are already large enough and merges won't be scheduled.

Re "data loss": Imagine a client using deduplication token in a slightly wrong way and inserting different data to different replicas. When the merge happens, ClickHouse will throw away one part for which it previously returned "Success" response on insert. I think it would be better if ClickHouse would not have surprising behaviour like this and instead would return an error to the client informing that they are writing different data to different replicas, imho.

**Comment by den-crane** [comment]
I agree that it could be solved by a better way.

>Re guaranteed: a) A part can be inserted in an old partition on a busy server that won't ever schedule merges for that old 
>partition; b) A part can be inserted into a partition where parts are already large enough and merges won't be scheduled.

AFAIK merge is not necessary CH rechecks part checksums periodically.
So eventually it will be resolved automatically even without merge.


>Re "data loss": Imagine a client using deduplication token in a slightly wrong way and inserting different data to different replicas. When the merge happens, ClickHouse will throw away one part for which it previously returned "Success" response on insert. I think it would be better if ClickHouse would not have surprising behaviour like this and instead would return an error to the client informing that they are writing different data to different replicas, imho.

But it's the same if you insert different data with the same insert_deduplication_token CH reports about successful insert and throws inserted data away.

```sql
create table test1(A Int64, B String)Engine=ReplicatedMergeTree('/clickhouse/{cluster}/tables/test11', '{replica}') order by A;

insert into test1 values settings insert_deduplication_token = 'test' (1,'data') ;
insert into test1 values settings insert_deduplication_token = 'test' (1,'very important data') ;

select * from test1;
┌─A─┬─B────┐
│ 1 │ data │
└───┴──────┘
```

**Comment by nvartolomei** [comment]
> But it's the same if you insert different data with the same insert_deduplication_token CH reports about successful insert and throws inserted data away.

Exactly. However, if ClickHouse were to verify checksums then this issue wouldn't be present.
