### ISSUE TITLE
In a degenerate scenario with concurrent writes, Keeper performance is about 10x lower than zookeeper

### ISSUE THREAD

**Issue by zk-kiger** [ClickHouse/ClickHouse#41045]
I deploy a three-node cluster with the following configuration:
32 vCPUs + 126 GB Memory + 2.0T SSD * 1
32 vCPUs + 126 GB Memory + 500G SSD * 2
client use: 96 vCPUs + 278 GB Memory + 2.0T SSD

I use YCSB benchmark tools to test Keeper/zookeeper read and write performance, the test script is:
```
# load data
./bin/ycsb load zookeeper -s -threads 100 -P workloads/workloadb -p zookeeper.connectString=9.135.246.21:7181,9.135.246.41:7181,9.135.247.117:7181/benchmark -p recordcount=10000 > outputLoad.txt
# read data
./bin/ycsb run zookeeper -s -threads 100 -P workloads/workloadb -p zookeeper.connectString=9.135.246.21:7181,9.135.246.41:7181,9.135.247.117:7181/benchmark -p operationcount=10000 -p readproportion=1 -p updateproportion=0 > outputLoad.txt
```
Keeper Read QPS: 74 ,Write QPS: 905.
Zookeeper Read QPS: 5165, Write QPS: 8634.

Keeper config:
```
 <coordination_settings>
          <operation_timeout_ms>10000</operation_timeout_ms>
          <session_timeout_ms>30000</session_timeout_ms>
          <raft_logs_level>warning</raft_logs_level>
          <quorum_reads>false</quorum_reads>
          <compress_logs>false</compress_logs>
          <max_requests_batch_size>1000</max_requests_batch_size>
          <compress_snapshots_with_zstd_format>false</compress_snapshots_with_zstd_format>
</coordination_settings>
```

note: When I configure `quroum_read=true` and want to test linearizable read, both read and write cannot be tested, and a large number of session timeout exceptions are thrown.

**Comment by tavplubix** [comment]
> Keeper Read QPS: 74 

It definitely looks like some misconfiguration, there's no way it can process only 74 read requests per second. Please share full Keeper config. Also what binary do you use (version, build id)? Is it standalone Keeper binary or static ClickHouse binary?

**Comment by zk-kiger** [comment]
@tavplubix I also couldn't believe it, so I re-tested and this time the QPS went up to 89 🥲

I am using clickhouse-common-static-22.8.3.13-amd64.tgz. 
standalone Keeper using command `clickhouse keeper -C /data/clickhouse/config/config.xml`
this is the complete keeper configuration:
```
<keeper_server>
    <tcp_port>7181</tcp_port>
    <server_id>1</server_id>
    <log_storage_path>/data/clickhouse/coordination/log</log_storage_path>
    <snapshot_storage_path>/data/clickhouse/coordination/snapshots</snapshot_storage_path>

    <coordination_settings>
            <operation_timeout_ms>10000</operation_timeout_ms>
            <session_timeout_ms>30000</session_timeout_ms>
            <raft_logs_level>warning</raft_logs_level>
            <quorum_reads>false</quorum_reads>
            <compress_logs>false</compress_logs>
            <max_requests_batch_size>1000</max_requests_batch_size>
            <compress_snapshots_with_zstd_format>false</compress_snapshots_with_zstd_format>
    </coordination_settings>

    <raft_configuration>
            <server>
                <id>1</id>
                <hostname>9.135.246.21</hostname>
                <port>9444</port>
            </server>
            <server>
                <id>2</id>
                <hostname>9.135.246.41</hostname>
                <port>9444</port>
            </server>
            <server>
                <id>3</id>
                <hostname>9.135.247.117</hostname>
                <port>9444</port>
            </server>
    </raft_configuration>
</keeper_server>
```

**Comment by tavplubix** [comment]
> this time the QPS went up to 89 

0_o

The configuration looks okay. Please also share the output of `clickhouse local -q "select * from system.build_options"`. How much is round trip time between hosts?

**Comment by zk-kiger** [comment]
VERSION_FULL    ClickHouse 22.8.3.13
VERSION_DESCRIBE        v22.8.3.13-stable
VERSION_INTEGER 22008003
SYSTEM  Linux
VERSION_GITHASH 6a15b73faea4f9bb78c559fad5eec8814878f19d
VERSION_REVISION        54465
VERSION_DATE
BUILD_TYPE      RelWithDebInfo
SYSTEM_PROCESSOR        x86_64
CMAKE_VERSION   3.16.3
C_COMPILER      /usr/bin/clang-14
C_COMPILER_VERSION      14.0.6
CXX_COMPILER    /usr/bin/clang++-14
CXX_COMPILER_VERSION    14.0.6
C_FLAGS  --gcc-toolchain=./cmake/linux/../../contrib/sysroot/linux-x86_64 -fdiagnostics-color=always -Xclang -fuse-ctor-homing  -gdwarf-aranges -pipe -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -fasynchronous-unwind-tables -ffile-prefix-map=.=. -falign-functions=32 -mbranches-within-32B-boundaries  -fdiagnostics-absolute-paths -fexperimental-new-pass-manager -Wframe-larger-than=65536 -Weverything -Wpedantic -Wno-zero-length-array -Wno-c++98-compat-pedantic -Wno-c++98-compat -Wno-c++20-compat -Wno-conversion -Wno-ctad-maybe-unsupported -Wno-disabled-macro-expansion -Wno-documentation-unknown-command -Wno-double-promotion -Wno-exit-time-destructors -Wno-float-equal -Wno-global-constructors -Wno-missing-prototypes -Wno-missing-variable-declarations -Wno-padded -Wno-switch-enum -Wno-undefined-func-template -Wno-unused-template -Wno-vla -Wno-weak-template-vtables -Wno-weak-vtables -Wno-thread-safety-negative -O2 -g -DNDEBUG -O3 -g -gdwarf-4  -flto=thin -fwhole-program-vtables -fno-pie
CXX_FLAGS        --gcc-toolchain=./cmake/linux/../../contrib/sysroot/linux-x86_64 -std=c++20 -fdiagnostics-color=always -Xclang -fuse-ctor-homing -fsized-deallocation  -gdwarf-aranges -pipe -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -fasynchronous-unwind-tables -ffile-prefix-map=.=. -falign-functions=32 -mbranches-within-32B-boundaries -fdiagnostics-absolute-paths -fstrict-vtable-pointers -fexperimental-new-pass-manager -Wall -Wextra -Wframe-larger-than=65536 -Weverything -Wpedantic -Wno-zero-length-array -Wno-c++98-compat-pedantic -Wno-c++98-compat -Wno-c++20-compat -Wno-conversion -Wno-ctad-maybe-unsupported -Wno-disabled-macro-expansion -Wno-documentation-unknown-command -Wno-double-promotion -Wno-exit-time-destructors -Wno-float-equal -Wno-global-constructors -Wno-missing-prototypes -Wno-missing-variable-declarations -Wno-padded -Wno-switch-enum -Wno-undefined-func-template -Wno-unused-template -Wno-vla -Wno-weak-template-vtables -Wno-weak-vtables -Wno-thread-safety-negative -O2 -g -DNDEBUG -O3 -g -gdwarf-4  -flto=thin -fwhole-program-vtables -fno-pie
LINK_FLAGS       --gcc-toolchain=./cmake/linux/../../contrib/sysroot/linux-x86_64 --ld-path=/usr/bin/ld.lld-14 -rdynamic -no-pie -Wl,-no-pie  -flto=thin -fwhole-program-vtables
BUILD_COMPILE_DEFINITIONS       HAS_RESERVED_IDENTIFIER
STATIC  ON
USE_EMBEDDED_COMPILER   1
USE_GLIBC_COMPATIBILITY ON
USE_JEMALLOC    ON
USE_UNWIND      ON
USE_ICU 1
USE_H3  1
USE_MYSQL       1
USE_RDKAFKA     1
USE_CAPNP       1
USE_BASE64      1
USE_HDFS        1
USE_SNAPPY      1
USE_PARQUET     1
USE_PROTOBUF    1
USE_BROTLI      1
USE_SSL 1
OPENSSL_VERSION 1.1.1g
OPENSSL_IS_BORING_SSL   1
USE_VECTORSCAN  ON
USE_SIMDJSON    1
USE_ODBC        1
USE_GRPC        1
USE_LDAP        1
TZDATA_VERSION  2022b
USE_KRB5        1
USE_FILELOG     1
USE_BZIP2       1
USE_AMQPCPP     1
USE_ROCKSDB     1
USE_NURAFT      1
USE_NLP 1
USE_SQLITE      1
USE_LIBPQXX     1
USE_AZURE_BLOB_STORAGE  1
USE_AWS_S3      1
USE_CASSANDRA   1
USE_YAML_CPP    1
USE_SENTRY      1
USE_DATASKETCHES        1
USE_AVRO        1
USE_ARROW       1
USE_ORC 1
USE_MSGPACK     1
GIT_HASH        6a15b73faea4f9bb78c559fad5eec8814878f19d
GIT_BRANCH      22.8
GIT_DATE        2022-08-27 00:42:48 +0000
GIT_COMMIT_SUBJECT      Merge pull request #40694 from ClickHouse/backport/22.8/40681

**Comment by tavplubix** [comment]
Looks like normal release build, so I ran out of ideas.

@antonio2368, could you please take a look?

**Comment by antonio2368** [comment]
It's possible that it doesn't work well with multiple clients.
I tested it out locally a bit and I really do get similar results (Keeper is really bad, while ZK works much faster).
We use the same session in a single CH instance so maybe that's the reason we didn't notice something like this before.

#38200 works much better with this benchmark because it handles multiple sessions much better but I didn't test it enough to say how is it compared to ZK in the same env.

**Comment by zk-kiger** [comment]
> It's possible that it doesn't work well with multiple clients.

ok, according to the reasons you mentioned , I re-tested the performance of Zookeeper and Keeper under a single client, and unfortunately I got the following results 🤯, (note: I didn't set `quorum_read=true`):
load data: zk qps=312, keeper qps=97
read data: zk qps=939, keeper qps=184

this is my test command:
load data `./bin/ycsb load zookeeper -s -P workloads/workloadb -p zookeeper.connectString=9.135.247.117:7181/benchmark -p recordcount=10000 > outputLoad.txt`

read data `./bin/ycsb run zookeeper -s -P workloads/workloadb -p zookeeper.connectString=9.135.246.21:7181,9.135.246.41:7181,9.135.247.117:7181/benchmark -p operationcount=10000 -p readproportion=1 -p updateproportion=0 > outputLoad.txt`

**Comment by zk-kiger** [comment]
@antonio2368 hi, I summarize the test results.
single-machine test
>single-client
write: Keeper is about 2x slower than ZK
multi-client
write: Keeper is about 10x slower than ZK
Fortunately, Keeper's read performance is on par with ZK whether it is single-client or multi-client.

cluster-test
>single-client
write: Keeper is about 3x slower than ZK
read: Keeper is about 5x slower than ZK
multi-client
write: Keeper is about 50x slower than ZK
read: Keeper is about 9x slower than ZK

I propose the following ideas:
- whether there is log replication between nodes that can be optimized?
- Is write performance related to raft and ZAB algorithms?
- when I looked at the flame graph, I found that BgSchPool has a large number of [unknown] methods that take a lot of time to be called. Is it the reason that affects performance?

I would like to optimize keeper as a component of our system and would love to give me some prying points, thanks~

**Comment by jiangbiao910** [comment]
@zk-kiger Hello,I try to test the QPS by YCSB,But there is error like `2022-09-14 16:57:58 WARN  ClientCnxn:1290 - Session 0x0 for sever localhost/127.0.0.1:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException.
EndOfStreamException: Unable to read additional data from server sessionid 0x0, likely server has closed socket
        at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:77)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1280)
2022-09-14 16:57:58 ERROR ZKClient:138 - Error when inserting a path:/user6284781860667377211,tableName:usertable
org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /user6284781860667377211
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:102)
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
        at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:1347)
        at site.ycsb.db.zookeeper.ZKClient.insert(ZKClient.java:132)
        at site.ycsb.DBWrapper.insert(DBWrapper.java:227)
        at site.ycsb.workloads.CoreWorkload.doInsert(CoreWorkload.java:621)
        at site.ycsb.ClientThread.run(ClientThread.java:135)
        at java.base/java.lang.Thread.run(Thread.java:829)
Error inserting, not retrying any more. number of attempts: 1Insertion Retry Limit: 0
`
when I run `./bin/ycsb load zookeeper -s -P workloads/workloadb -p zookeeper.connectString=127.0.0.1:2181/benchmark -p recordcount=10000
` 
CYSB is from master .
Can you help me ?

**Comment by zk-kiger** [comment]
@jiangbiao910 did you have create `/benchmark` node in zk?

**Comment by jiangbiao910** [comment]
@zk-kiger thank you，
when I  create /benchmark node in zk ,I can use YCSB benchmark tools
but there some warn like this, is this normal?
```
2022-09-15 10:58:06 WARN  ClientCnxn:1284 - An exception was thrown while closing send thread for session 0xcd.
EndOfStreamException: Unable to read additional data from server sessionid 0xcd, likely server has closed socket
        at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:77)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1280)
```
./bin/ycsb load  is write?

```
[root@ck01 ycsb-zookeeper-binding-0.18.0-SNAPSHOT]# cat ckload.txt
[OVERALL], RunTime(ms), 26663
[OVERALL], Throughput(ops/sec), 375.05156959081876
[TOTAL_GCS_Copy], Count, 17
[TOTAL_GC_TIME_Copy], Time(ms), 31
[TOTAL_GC_TIME_%_Copy], Time(%), 0.1162659865731538
[TOTAL_GCS_MarkSweepCompact], Count, 0
[TOTAL_GC_TIME_MarkSweepCompact], Time(ms), 0
[TOTAL_GC_TIME_%_MarkSweepCompact], Time(%), 0.0
[TOTAL_GCs], Count, 17
[TOTAL_GC_TIME], Time(ms), 31
[TOTAL_GC_TIME_%], Time(%), 0.1162659865731538
[CLEANUP], Operations, 100
[CLEANUP], AverageLatency(us), 1554689.28
[CLEANUP], MinLatency(us), 182528
[CLEANUP], MaxLatency(us), 3276799
[CLEANUP], 95thPercentileLatency(us), 2904063
[CLEANUP], 99thPercentileLatency(us), 3176447
[INSERT], Operations, 10000
[INSERT], AverageLatency(us), 182264.1776
[INSERT], MinLatency(us), 30352
[INSERT], MaxLatency(us), 2351103
[INSERT], 95thPercentileLatency(us), 337151
[INSERT], 99thPercentileLatency(us), 1238015
[INSERT], Return=OK, 10000
[root@ck01 ycsb-zookeeper-binding-0.18.0-SNAPSHOT]# cat ckrun.txt
[OVERALL], RunTime(ms), 12105
[OVERALL], Throughput(ops/sec), 826.1049153242462
[TOTAL_GCS_Copy], Count, 19
[TOTAL_GC_TIME_Copy], Time(ms), 23
[TOTAL_GC_TIME_%_Copy], Time(%), 0.19000413052457663
[TOTAL_GCS_MarkSweepCompact], Count, 0
[TOTAL_GC_TIME_MarkSweepCompact], Time(ms), 0
[TOTAL_GC_TIME_%_MarkSweepCompact], Time(%), 0.0
[TOTAL_GCs], Count, 19
[TOTAL_GC_TIME], Time(ms), 23
[TOTAL_GC_TIME_%], Time(%), 0.19000413052457663
[READ], Operations, 10000
[READ], AverageLatency(us), 56987.9393
[READ], MinLatency(us), 51
[READ], MaxLatency(us), 1716223
[READ], 95thPercentileLatency(us), 318719
[READ], 99thPercentileLatency(us), 1206271
[READ], Return=OK, 10000
[CLEANUP], Operations, 100
[CLEANUP], AverageLatency(us), 1019674.56
[CLEANUP], MinLatency(us), 104448
[CLEANUP], MaxLatency(us), 2342911
[CLEANUP], 95thPercentileLatency(us), 1724415
[CLEANUP], 99thPercentileLatency(us), 2254847
[root@ck01 ycsb-zookeeper-binding-0.18.0-SNAPSHOT]#
```

[root@ck01 ycsb-zookeeper-binding-0.18.0-SNAPSHOT]# cat zkload.txt
[OVERALL], RunTime(ms), 10547
[OVERALL], Throughput(ops/sec), 948.1369109699441
[TOTAL_GCS_Copy], Count, 17
[TOTAL_GC_TIME_Copy], Time(ms), 34
[TOTAL_GC_TIME_%_Copy], Time(%), 0.32236654972978096
[TOTAL_GCS_MarkSweepCompact], Count, 0
[TOTAL_GC_TIME_MarkSweepCompact], Time(ms), 0
[TOTAL_GC_TIME_%_MarkSweepCompact], Time(%), 0.0
[TOTAL_GCs], Count, 17
[TOTAL_GC_TIME], Time(ms), 34
[TOTAL_GC_TIME_%], Time(%), 0.32236654972978096
[CLEANUP], Operations, 100
[CLEANUP], AverageLatency(us), 1145322.24
[CLEANUP], MinLatency(us), 110016
[CLEANUP], MaxLatency(us), 3131391
[CLEANUP], 95thPercentileLatency(us), 2623487
[CLEANUP], 99thPercentileLatency(us), 3024895
[INSERT], Operations, 10000
[INSERT], AverageLatency(us), 51097.3562
[INSERT], MinLatency(us), 1394
[INSERT], MaxLatency(us), 2428927
[INSERT], 95thPercentileLatency(us), 130111
[INSERT], 99thPercentileLatency(us), 415231
[INSERT], Return=OK, 10000
[root@ck01 ycsb-zookeeper-binding-0.18.0-SNAPSHOT]# cat zkrun.txt
[OVERALL], RunTime(ms), 9251
[OVERALL], Throughput(ops/sec), 1080.9642200843152
[TOTAL_GCS_Copy], Count, 19
[TOTAL_GC_TIME_Copy], Time(ms), 26
[TOTAL_GC_TIME_%_Copy], Time(%), 0.28105069722192194
[TOTAL_GCS_MarkSweepCompact], Count, 0
[TOTAL_GC_TIME_MarkSweepCompact], Time(ms), 0
[TOTAL_GC_TIME_%_MarkSweepCompact], Time(%), 0.0
[TOTAL_GCs], Count, 19
[TOTAL_GC_TIME], Time(ms), 26
[TOTAL_GC_TIME_%], Time(%), 0.28105069722192194
[READ], Operations, 10000
[READ], AverageLatency(us), 43352.8252
[READ], MinLatency(us), 233
[READ], MaxLatency(us), 812031
[READ], 95thPercentileLatency(us), 213759
[READ], 99thPercentileLatency(us), 405759
[READ], Return=OK, 10000
[CLEANUP], Operations, 100
[CLEANUP], AverageLatency(us), 437583.04
[CLEANUP], MinLatency(us), 103168
[CLEANUP], MaxLatency(us), 1612799
[CLEANUP], 95thPercentileLatency(us), 992767
[CLEANUP], 99thPercentileLatency(us), 1206271
[root@ck01 ycsb-zookeeper-binding-0.18.0-SNAPSHOT]#

**load  zk is 948   ck is 375
run   zk is 1080  ck is  826**
My machine is virtual in local.

**Comment by zk-kiger** [comment]
> load zk is 948 ck is 375
run zk is 1080 ck is 826

@jiangbiao910 I think your test results are correct. According to my test, writing Keeper under a single node is 2-3 times slower than zk, and the read performance is comparable.I think the current first step is to optimize the write capability of Keeper on a single machine.If you have some ideas, we can discuss them together.

**Comment by jiangbiao910** [comment]
@zk-kiger Our team want to remove ZK  and use Keeper ,By this  YCSB test ，maybe we should wait next version？
I test Clickhouse Version is **22.8.1.2097**

**Comment by antonio2368** [comment]
Sorry for not replying, @zk-kiger @jiangbiao910 

I'm working on further improving the performance in https://github.com/ClickHouse/ClickHouse/pull/41485
I get much better results than before. I'll ping you when the version of Keeper with the above PR is published to check out the results on your setup. Is that okay with you?

**Comment by zk-kiger** [comment]
@antonio2368 that's great, I will focus on this PR.

**Comment by zk-kiger** [comment]
@antonio2368 Summarizing some results from a recent test of Keeper(The following tests are single machine).
I use script followe, the code is https://github.com/ClickHouse/ClickHouse/pull/41485 branch:
```
./bin/ycsb load zookeeper -s -P workloads/workloadb -p zookeeper.connectString=127.0.0.1:2181/benchmark -p recordcount=10000
```

1.When I changed the zk(dataDir) and keeper(log_storage_path) from disk to memory, their read and write performance was comparable.
2.So I guess the reason for the slow write performance of keeper is due to the bottleneck of writing to the disk, then I used iostat to observe the io of keeper and zk, and got the following data.
keeper:
![image](https://user-images.githubusercontent.com/40687890/195077112-10132046-037d-4759-8014-81696ed84f40.png)
zk:
![image](https://user-images.githubusercontent.com/40687890/195077267-9b5282af-d722-40dd-8cb4-2f13ac49e0c8.png)
zk used less disk io times but got higher QPS (zk: 542, keeper: 253), and noticed that zk is more efficient for io merging, which may be a point that keeper can optimize.

**Comment by antonio2368** [comment]
@zk-kiger could you try setting `force_sync` to `false` under `keeper_server.coordination_settings`?
This will disable flush on each Raft log (just for benchmarking purposes). I'm not sure what ZK does in this case.

**Comment by lingpeng0314** [comment]
@antonio2368 The performance degrading in only happens in `22.8.3`? i was using keeper 22.7.7.24 and 22.8.3,  22.8.3 is lower obviously than 22.7.7.

**Comment by yywing** [comment]
How is it going？

**Comment by antonio2368** [comment]
There were some performance improvements for write path:
https://github.com/ClickHouse/ClickHouse/pull/43686
https://github.com/ClickHouse/ClickHouse/pull/43450

They should be part of 22.12 release, but they can be already tested with [head images](https://hub.docker.com/layers/clickhouse/clickhouse-keeper/head-alpine/images/sha256-679f941d01dfe3f694c6c717bbd21c841a96e84e9026edb9e1a97296962a30dc?context=explore).

**Comment by bobelev** [comment]
> There were some performance improvements for write path: #43686 #43450
> 
> They should be part of 22.12 release, but they can be already tested with [head images](https://hub.docker.com/layers/clickhouse/clickhouse-keeper/head-alpine/images/sha256-679f941d01dfe3f694c6c717bbd21c841a96e84e9026edb9e1a97296962a30dc?context=explore).

Will improvements be merged into LTS branches?

**Comment by alexey-milovidov** [comment]
@bobelev LTS branches only receive security and stability fixes.
