### ISSUE TITLE
The specified key does not exist (functional tests)

### ISSUE THREAD

**Issue by tavplubix** [ClickHouse/ClickHouse#41040]
https://s3.amazonaws.com/clickhouse-test-reports/0/6339b106beb18fb57739a841d9ad9a258c529258/stateless_tests__release__s3_storage_.html

**Comment by tavplubix** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/0/59bd94dcf8142f16225f6aa1d27098d875315c62/stateless_tests__release__s3_storage_.html

**Comment by qoega** [comment]
01171_mv_select_insert_isolation_long
https://s3.amazonaws.com/clickhouse-test-reports/0/e8d8f246725ea79e8a8212efa1c6eecd8bccab68/stateless_tests__release__s3_storage_.html

**Comment by tavplubix** [comment]
00988_parallel_parts_removal
https://s3.amazonaws.com/clickhouse-test-reports/41146/ed3c95c28f40451d13f0958e973f96b9cfdebf14/stateless_tests__tsan__s3_storage__[1/3].html

it's not related to specific tests

**Comment by alexey-milovidov** [comment]
Duplicate of #48474.
