### ISSUE TITLE
config.xml and users.xml overwritten on update

### ISSUE THREAD

**Issue by andycol** [ClickHouse/ClickHouse#41053]
I have noticed when you update your version of clickhouse-server the config.xml and users.xml are overwritten 
So my question is, would it not be better to rather create a config.xml.example and users.xml.example

i know i can create custom files in config.d/ but i i find it easier to edit config.xml for listen_host etc

anyway just a observastion and suggestion

**Comment by genzgd** [comment]
I think you answered your own question?  The best practice is to create custom files with override elements in the /var/lib/clickhouse-server/config.d file.  That way the config.xml and users.xml files are guaranteed to work with your updated version of clickhouse, and the clickhouse binaries (clickhouse server, clickhouse local, and clickhouse client) work for all users "out of the box" (including in particular easy installation into containers) without having to copy or move files from 'example' versions.

**Comment by tavplubix** [comment]
> The best practice is to create custom files with override elements in the /var/lib/clickhouse-server/config.d file.

It's true, but AFAIK a package manager should ask what to do if the original config file was modified by user and new version of a package wants to overwrite it. Maybe administrator ignored that and just chose "overwrite" option. Or maybe something's wrong with our packages or `clickhouse-install`.

**Comment by andycol** [comment]
> > The best practice is to create custom files with override elements in the /var/lib/clickhouse-server/config.d file.
> 
> It's true, but AFAIK a package manager should ask what to do if the original config file was modified by user and new version of a package wants to overwrite it. Maybe administrator ignored that and just chose "overwrite" option. Or maybe something's wrong with our packages or `clickhouse-install`.

Its seems on all new yum install clickhouse-server or yum update etc it overwrites the default config.
I understand the reasoning now but dont personally agree with it in terms of best practice
just my 2 cents

**Comment by den-crane** [comment]
it's possible https://www.cl.cam.ac.uk/~jw35/docs/rpm_config.html

But actually it's a bad idea to modify config.xml and users.xml. 
There are several occurrences when CH was unable to start after upgrade because developers have added a mandatory setting into config.xml and obviously this setting was missing in the modified config.xml .

**Comment by alexey-milovidov** [comment]
ClickHouse is always able to parse the config of the previous version, so changing the default to "noreplace" in rpm will be good.
