### ISSUE TITLE
【Merge Engine related】How to use Merge Engine for distributed query ?

### ISSUE THREAD

**Issue by mo-avatar** [ClickHouse/ClickHouse#41051]
Build distributed engine  on Merge Engine and Merge Engine on ReplicatedMergeTree Engine,
Or build Merge Engine on distributed engine and  distributed engine on merge tree,
which is better ?

Thank you guys.

**Comment by den-crane** [comment]
You can do any.

Suggested / supposed: `Distributed -> Merge -> ReplicatedMergeTree`

Some users use: `Merge -> Distributed -> ReplicatedMergeTree` but for some very rare use-cases.

**Comment by rkozlo** [comment]
We are using second setting. For some reason first one was noticeable slower

**Comment by mo-avatar** [comment]
Thanks for your guys answering.
