### ISSUE TITLE
"Size of marks file is inconsistent" for huge inserts into tables with Engine=Log

### ISSUE THREAD

**Issue by gongweibiao1986** [ClickHouse/ClickHouse#4107]
The engine I'm using is a log, and I'm feeding 14 billion data into the table, and it's giving me this error when I query it "Size of marks file is inconsistent"

**Comment by KochetovNicolai** [comment]
That error may happen if insertion into `Log` table failed. [`Log` engine](https://clickhouse.yandex/docs/en/operations/table_engines/log/) is only for small data, testing or demonstration purposes. Generally, it's better to use `MergeTree` family engines.

**Comment by alexey-milovidov** [comment]
Fixed in #12426.
