### ISSUE TITLE
makes pool_size and queue size configurable for S3 reader&writer

### ISSUE THREAD

**Issue by young-scott** [ClickHouse/ClickHouse#41070]
in IDiskRemote::getThreadPoolWriter & IDiskRemote::getThreadPoolReader

reader&writer queue size is 1M . it's too large, my multi object upload size is 16M,  and it will cause OOM when there are many moving task copying objects to  low performance s3 server.

reader&writer pool  can also not changed .

**Comment by lesandie** [comment]
Hey @kssenii could this feature be backported to 22.3/22.8 LTS?. After this fix S3 to minio and backblaze work nicely both table functions and backed mergetree and no timeouts/problems

**Comment by kssenii** [comment]
22.3 - no for sure, because this PR touched a lot of parts of the code and it would conflict with 22.3 enormously. 22.8 is probably no too, the code changes quickly and probably it will be too difficult to backport because the code touched too many parts...
