### ISSUE TITLE
About MDX query language on ClickHouse

### ISSUE THREAD

**Issue by qmdt** [ClickHouse/ClickHouse#41081]
Hi， 
In ClickHouse doc, there's the following description: "Note that for CPU efficiency, the query language must be declarative (SQL or MDX)," According to this description, I think that the ClickHouse supports the DMX query language.

After checking the syntax of the DMX language,  maybe need to create a cube for query. Is there a reference for creating a cube?
![image](https://user-images.githubusercontent.com/8369775/188876082-e95e9b0e-a966-444d-99c7-68eea019e37f.png)

Thank you for your hard work, look forward to your early reply, best wishes to you, thank you.

**Comment by UnamedRus** [comment]
> I think that the ClickHouse supports the DMX query language.

ClickHouse doesn't support MDX.

But there is some experience with using Mondrian with ClickHouse. 
https://altinity.com/blog/accessing-clickhouse-from-excel-using-mondrian-rolap-engine

**Comment by qmdt** [comment]
thank you for your replay, @UnamedRus 
According to the description in the reference link, Accessing ClickHouse from Excel using Mondrian ROLAP engine, I understand that the Mondrian ROLAP engine converts the DMX query language into the SQL query language, and then obtains the data from the ClickHouse query. Is this correct?
