### ISSUE TITLE
In a non-Kerberos cluster, the latest libhdfs3 branch code causes a clickhouse crash.

### ISSUE THREAD

**Issue by lingnancfy** [ClickHouse/ClickHouse#41098]
> You have to provide the following information whenever possible.

I want to compile the latest libhdfs3 version to solve some problems. However, when an HDFS engine table is created in a common cluster for access, clickhouse crash occurs and the following stack information is displayed:
clickhouse-client --host 192.168.10.110 --user cfy1 --password 123456
ClickHouse client version 22.9.1.1.
Connecting to 192.168.10.110:9000 as user cfy1.
Connected to ClickHouse server version 22.9.1 revision 54460.

node-master1mjpR :) select * from hdfs_engine_table;

SELECT *
FROM hdfs_engine_table

Query id: b79d2562-aa62-4d62-acb2-dcbe98af0196

[node-master1mjpR] 2022.09.08 16:07:40.368172 [ 950367 ] <Fatal> BaseDaemon: ########################################
[node-master1mjpR] 2022.09.08 16:07:40.368246 [ 950367 ] <Fatal> BaseDaemon: (version 22.9.1.1, build id: E92376CAC71C67762DCE0123A03329FD916A61FA) (from thread 947539) (query_id: b79d2562-aa62-4d62-acb2-dcbe98af0196) (query: select * from hdfs_engine_table;) Received signal Segmentation fault (11)
[node-master1mjpR] 2022.09.08 16:07:40.368285 [ 950367 ] <Fatal> BaseDaemon: Address: 0x12 Access: read. Address not mapped to object.
[node-master1mjpR] 2022.09.08 16:07:40.368316 [ 950367 ] <Fatal> BaseDaemon: Stack trace: 0xb6fa2e8 0xb8b614d 0x7f64093ba320
[node-master1mjpR] 2022.09.08 16:07:40.373622 [ 950367 ] <Fatal> BaseDaemon: 0.1. inlined from ./build/../src/Common/StackTrace.cpp:331: StackTrace::tryCapture()
[node-master1mjpR] 2022.09.08 16:07:40.373661 [ 950367 ] <Fatal> BaseDaemon: 0. ../src/Common/StackTrace.cpp:297: StackTrace::StackTrace(ucontext_t const&) in /usr/bin/clickhouse
[node-master1mjpR] 2022.09.08 16:07:40.385044 [ 950367 ] <Fatal> BaseDaemon: 1. ./build/../src/Daemon/BaseDaemon.cpp:0: signalHandler(int, siginfo_t*, void*) in /usr/bin/clickhouse
[node-master1mjpR] 2022.09.08 16:07:40.385158 [ 950367 ] <Fatal> BaseDaemon: 2. ? in /usr/lib64/libpthread-2.28.so
[node-master1mjpR] 2022.09.08 16:07:40.513404 [ 950367 ] <Fatal> BaseDaemon: Integrity check of the executable skipped because the reference checksum could not be read. (calculated checksum: 8A925299ED10893750CEE068956B9E9C)
Exception on client:
Code: 32. DB::Exception: Attempt to read after eof: while receiving packet from 192.168.10.110:9000. (ATTEMPT_TO_READ_AFTER_EOF)

Connecting to 192.168.10.110:9000 as user cfy1.
Code: 210. DB::NetException: Connection refused (192.168.10.110:9000). (NETWORK_ERROR)

**How to reproduce**
1. git clone master branch code;
2. cd /ClickHouse/contrib/libhdfs3 , git checkout cb9a82ac13950a0d3e428048e8f80da6b212041b
![image](https://user-images.githubusercontent.com/22337511/189072823-0850dcff-1d4a-497b-9c45-e6e944e1b3e3.png)
4. and build it；

* Which ClickHouse server version to use
22.9.1.1 master

* `CREATE TABLE` statements for all tables involved
CREATE TABLE default.hdfs_engine_table (`name` String, `value` UInt32) ENGINE = HDFS('hdfs://192.168.10.211:8020/tmp/cfy/cfy_secure_ck.txt', 'TSV')

and I want to fix by [#PR26](https://github.com/ClickHouse/libhdfs3/pull/26)

**Comment by vdimir** [comment]
Does failure reproduced only with non-official build with updated libhdfs3 ?

**Comment by lingnancfy** [comment]
> Does failure reproduced only with non-official build with updated libhdfs3 ?

yes,

**Comment by alexey-milovidov** [comment]
We don't support alternative builds at all.
They can contain bugs. But if you build ClickHouse with some non-standard options, it is your problem.
