### ISSUE TITLE
Using snowflake ID,  bitmap Memory usage to much

### ISSUE THREAD

**Issue by xujinlong0314** [ClickHouse/ClickHouse#41102]
> Make sure to check documentation https://clickhouse.com/docs/en/ first. If the question is concise and probably has a short answer, asking it in Telegram chat https://telegram.me/clickhouse_en is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

> If you still prefer GitHub issues, remove all this text and ask your question here.

Using snowflake ID, if the value is too large, the memory usage  by bitmap will also be too large. What are the optimization methods？

**Comment by den-crane** [comment]
Why do you need to store snowflake ID in the bitmap ?

**Comment by xujinlong0314** [comment]
> Why do you need to store snowflake ID in the bitmap ?

Because it is user_ id, we use bitamp for multi-day retention

**Comment by xujinlong0314** [comment]
> > Why do you need to store snowflake ID in the bitmap ?
> 
> Because it is user_ id, we use bitamp for multi-day retention

example of seven day retention:
`SELECT a.dt as first_dt,
       b.dt as second_dt,
       dateDiff('day', parseDateTimeBestEffortOrZero(toString(first_dt)), parseDateTimeBestEffortOrZero(toString(second_dt))) + 1 AS idx,
       bitmapCardinality(a.measure)                                as first_uv,
       bitmapAndCardinality(a.measure, b.measure)            as union_uv
    (select bitmap, dt from tab where dt >= 20220801 and dt <= 20220905)a
cross join
(select bitmap,dt from tab where dt>=20220802 and dt <=20220909)  b
where a.dt <b.dt
and idx <=7
order by a.dt,b.dt`

**Comment by xujinlong0314** [comment]
> > > Why do you need to store snowflake ID in the bitmap ?
> > 
> > 
> > Because it is user_ id, we use bitamp for multi-day retention
> 
> example of seven day retention: `SELECT a.dt as first_dt, b.dt as second_dt, dateDiff('day', parseDateTimeBestEffortOrZero(toString(first_dt)), parseDateTimeBestEffortOrZero(toString(second_dt))) + 1 AS idx, bitmapCardinality(a.measure) as first_uv, bitmapAndCardinality(a.measure, b.measure) as union_uv from (select bitmap, dt from tab where dt >= 20220801 and dt <= 20220905)a cross join (select bitmap,dt from tab where dt>=20220802 and dt <=20220909) b where a.dt <b.dt and idx <=7 order by a.dt,b.dt`

**Comment by aikuyun** [comment]
Have you solved it？
