### ISSUE TITLE
suspicious pointer-to-bool conversion

### ISSUE THREAD

**Issue by kvtb** [ClickHouse/ClickHouse#41168]
**Describe the bug**
`sync` here is a pointer to a global `sync` function implicitly converted to a bool:

https://github.com/ClickHouse/ClickHouse/blob/624ccd5206a7be7c8a56f2f7590e13d57a074008/src/Databases/DatabaseReplicated.cpp#L797

**How to reproduce**
compile `master` or `v22.8.4.7-lts` with warnings enabled

**Error message and/or stacktrace**

**Comment by alexey-milovidov** [comment]
@kvtb Thank you!
We also compile with all warnings enabled (-Weverything).
We additionally use clang-tidy with all checks enabled by default and some of the checks disabled.
What we should enable to get this warning?

**Comment by kvtb** [comment]
> @kvtb Thank you! We also compile with all warnings enabled (-Weverything). We additionally use clang-tidy with all checks enabled by default and some of the checks disabled. What we should enable to get this warning?

I used recently released `clang-15.0.0`, maybe older `clang`s skips this.
