### ISSUE TITLE
Kafka engine CSV format_csv_delimiter parameter

### ISSUE THREAD

**Issue by adiletkabylbekov** [ClickHouse/ClickHouse#4116]
Is there way to set format_csv_delimiter parameter for CSV type in kafka engine?

In documentary of CK described default value fo CSV input as ",". In our files the delimiter is "|", so we need to change the default value. But i didn't find any documented possibility for set format_csv_delimiter in kafka engine table for csv input type.

**Comment by alexey-milovidov** [comment]
The same as #8056
