### ISSUE TITLE
Feature: support array of records as a root node in Avro input format

### ISSUE THREAD

**Issue by yusufozturk** [ClickHouse/ClickHouse#41179]
**Describe the unexpected behaviour**
Avro input does not accept "array" type

**How to reproduce**
* Which ClickHouse server version to use: 22.8.4.7

Following avro schema works:
```
{
    "type": "record",
    "name": "dashboarddata",
    "namespace": "com.virtualmetric",
    "fields" : [
        {"name": "column0", "type": "string"},
        {"name": "column1", "type": "string"}
    ]
}
```

But we send the events in batches to Kafka, so we use following schema:

```
{
   "type": "array", 
   "items": {
       "type": "record",
       "name": "dashboarddata",
       "fields" : [
        {"name": "column0", "type": "string"},
        {"name": "column1", "type": "string"}
       ]
   }
}
```

Kafka accepts Avro array but Clickhouse gives following error: Root schema must be a record

`<Error> void DB::StorageKafka::threadFunc(size_t): Code: 53. DB::Exception: Root schema must be a record: while parsing Kafka message (topic: 10tsato3-syslog2, partition: 0, offset: 0)': While executing Kafka. (TYPE_MISMATCH), Stack trace (when copying this message, always include the lines below):`

**Expected behavior**
Avro input should also support "array" type for bulk inserts.

Following PR resolves some issues but I don't think it supports array of records:
https://github.com/ClickHouse/ClickHouse/pull/37525

Your input is highly appreciated @Avogar , thanks for the Avro implementation.

**Comment by Avogar** [comment]
Yes, we expect that root node is a record (but inside this record we support array of records). I will take a look if we can support array of records as a root node.

**Comment by yusufozturk** [comment]
Thanks @Avogar . Being able to send records in array will reduce the latency on our backend code.

**Comment by yusufozturk** [comment]
@Avogar we changed the design and now we are sending array of records, instead of "array" type and records under it. During our tests, there was only 5-10ms difference for 50K records. So we thought it's acceptable.

So please feel free to stop working on it. I don't think anyone would need it when the latency is so low. But thanks anyway.
