### ISSUE TITLE
which source table should be use in Materialized view

### ISSUE THREAD

**Issue by ryanshummmm** [ClickHouse/ClickHouse#41172]
Hi, I met this issue right now, and can't find some doc to get the answer, thx for the help first~

Now I created two tables xxxx_local and xxxx (distributed table)
and I insert data into xxxx directly instead of xxxx_local.

after that, I need the materialized view, I also created two tables for it:yyyy_local and yyyy (distributed table)
I wonder which source table should I choose as the 'select from table', there's some combination here

 'create materialized view yyyy_view to yyyy_local as select a,b,c from xxxx_local'
 'create materialized view yyyy_view to yyyy_local as select a,b,c from xxxx'
 'create materialized view yyyy_view to yyyy as select a,b,c from xxxx_local'
 'create materialized view yyyy_view to yyyy as select a,b,c from xxxx'

which one is correct?

**Comment by den-crane** [comment]
All combinations are possible https://den-crane.github.io/Everything_you_should_know_about_materialized_views_commented.pdf page 27

**Comment by ryanshummmm** [comment]
> All combinations are possible https://den-crane.github.io/Everything_you_should_know_about_materialized_views_commented.pdf page 27

thx, i insert distributed table , and mv read from local, seems got double data of distributed table..

**Comment by den-crane** [comment]
it should work. You probably configured something. Check internal_replication in remote servers.
