### ISSUE TITLE
Random results of ORDER BY with LIMIT and a segfault

### ISSUE THREAD

**Issue by geronimogoemon** [ClickHouse/ClickHouse#41182]
Hello! It seems I have managed to produce a segfault in my ClickHouse server.

I have a table that looks like this:
```
CREATE TABLE test_table (
	"column_1" String NOT NULL,
	"column_2" LowCardinality(String) NOT NULL,
	"column_3" LowCardinality(String) NOT NULL,
	"timestamp" Datetime64(6) NOT NULL
)
ENGINE = AggregatingMergeTree()
PARTITION BY toYYYYMM("timestamp")
PRIMARY KEY ("column_1", "column_2", "timestamp", "column_3")
;
```

Then I run a query that looks likes this
```
SELECT max(timestamp) FROM (
	SELECT timestamp, column_1, column_2, column_3
	FROM test_table
	ORDER BY timestamp asc
	LIMIT 1500
)
```

Next, 3 strange things happen:
1. I am a getting a different result timestamp every time I run this query (no data is being inserted into the table and I ran OPTIMIZE FINAL earlier to make sure no merging is happening in the background)
2. If I change the limit to anything below 1500 (even 1499) the problem disappears.
3. When testing this query on my production server that has a lot other queries running on it at the same time I managed to crash the server and I got a stack trace that looks like this
```
2022.09.08 09:20:56.777322 [ 2857169 ] {} <Fatal> BaseDaemon: ########################################
2022.09.08 09:20:56.777425 [ 2857169 ] {} <Fatal> BaseDaemon: (version 22.6.2.12 (official build), build id: 52AFD84A0FEDD1BA) (from thread 2857119) (query_id: c94aa1c3-4b1e-4d34-a35a-a94c22d7e3ea) (query: select max(timestamp) from ( SELECT timestamp, column_1, column_2, column_3 FROM test_table
 order by timestamp asc, id asc limit 1500 )) Received signal Segmentation fault (11)
2022.09.08 09:20:56.777461 [ 2857169 ] {} <Fatal> BaseDaemon: Address: 0x6 Access: read. Address not mapped to object.
2022.09.08 09:20:56.777500 [ 2857169 ] {} <Fatal> BaseDaemon: Stack trace: 0x1668ecb5 0x1739af43 0x12df9570 0x171903a7 0x171af8da 0x171a47fe 0x171a60c4 0xb94d077 0xb95049d 0x7fabdf964609 0x7fabdf889133
2022.09.08 09:20:56.777560 [ 2857169 ] {} <Fatal> BaseDaemon: 2. DB::ColumnString::compareAt(unsigned long, unsigned long, DB::IColumn const&, int) const @ 0x1668ecb5 in /usr/bin/clickhouse
2022.09.08 09:20:56.777583 [ 2857169 ] {} <Fatal> BaseDaemon: 3. DB::PartialSortingTransform::transform(DB::Chunk&) @ 0x1739af43 in /usr/bin/clickhouse
2022.09.08 09:20:56.777604 [ 2857169 ] {} <Fatal> BaseDaemon: 4. DB::ISimpleTransform::transform(DB::Chunk&, DB::Chunk&) @ 0x12df9570 in /usr/bin/clickhouse
2022.09.08 09:20:56.777627 [ 2857169 ] {} <Fatal> BaseDaemon: 5. DB::ISimpleTransform::work() @ 0x171903a7 in /usr/bin/clickhouse
2022.09.08 09:20:56.777644 [ 2857169 ] {} <Fatal> BaseDaemon: 6. DB::ExecutionThreadContext::executeTask() @ 0x171af8da in /usr/bin/clickhouse
2022.09.08 09:20:56.777664 [ 2857169 ] {} <Fatal> BaseDaemon: 7. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x171a47fe in /usr/bin/clickhouse
2022.09.08 09:20:56.777691 [ 2857169 ] {} <Fatal> BaseDaemon: 8. ? @ 0x171a60c4 in /usr/bin/clickhouse
2022.09.08 09:20:56.777714 [ 2857169 ] {} <Fatal> BaseDaemon: 9. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xb94d077 in /usr/bin/clickhouse
2022.09.08 09:20:56.777774 [ 2857169 ] {} <Fatal> BaseDaemon: 10. ? @ 0xb95049d in /usr/bin/clickhouse
2022.09.08 09:20:56.777792 [ 2857169 ] {} <Fatal> BaseDaemon: 11. ? @ 0x7fabdf964609 in ?
2022.09.08 09:20:56.777805 [ 2857169 ] {} <Fatal> BaseDaemon: 12. clone @ 0x7fabdf889133 in ?
2022.09.08 09:20:56.971010 [ 2857169 ] {} <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: 894C4AAB85FCB9AAC26136BC446CC5AF)
```

I froze the partition and attached it to local clickhouse server running newest 22.8 version and the random timestamp problem was still there. I couldn't get it to produce a segfault but the local instance has no other query running on it so that's not really comparable.

Has someone seen anything like this before?

I would be happy to share the partition since that's probably where the problem lies but the data stored on it is private. Is there some method of randomizing/encrypting the column_* columns without affecting the primary key?

**Comment by den-crane** [comment]
is the result consistent if you add `settings optimize_read_in_order=0` to the end of the query ?

**Comment by geronimogoemon** [comment]
Unfortunately, nothing changes. I ran this
```
SELECT max(timestamp) FROM (
	SELECT timestamp, column_1, column_2, column_3
	FROM test_table
	ORDER BY timestamp asc
	LIMIT 1500
        SETTINGS optimize_read_in_order=0
)
```

**Comment by alexey-milovidov** [comment]
@geronimogoemon Does it reproduce on another server?
Also, run this to check if the server has bad RAM:

```
for i in {1..100}; do clickhouse-client --max_block_size 10M --query "SELECT materialize(1) AS x FROM numbers_mt(1e10) WHERE x != 1"; done
```

**Comment by geronimogoemon** [comment]
I managed to reproduce the issues on the following combinations:
- Personal laptop with ClickHouse v22.6.2.12
- Personal laptop with ClickHouse v22.8.3.13
- Production server with ClickHouse v22.6.2.12

I ran the query you have given for my personal laptop as well as the production server and they have given no output.

**Comment by den-crane** [comment]
>I managed to reproduce the issues on the following combinations:

Do you mean you managed to reproduce with your data or with synthetic data?
How big is your dataset? Can you send it to support@clickhouse.com ?

**Comment by geronimogoemon** [comment]
I managed to reproduce the issue only with my data. Synthetic data never had the problem.

The partition file has only 71MB. I would love to share it but I am not allowed to share the data stored in the `column_*` columns. Can I somehow extract only the timestamp column? Or can I somehow manipulate the partition files to obfuscate the `column_*` columns?

Here are the settings for my personal laptop:
```
load_balancing	random
allow_experimental_live_view	1
allow_experimental_object_type	1
```

And here for the production server
```
load_balancing	random
max_bytes_before_external_group_by	8589934592
max_bytes_before_external_sort	8589934592
readonly	2
max_memory_usage	21474836480
```

**Comment by den-crane** [comment]
@geronimogoemon does it reproduce if you create a new table with another name and Engine=MergeTree and insert data where?

**Comment by geronimogoemon** [comment]
Yes, it reproduces on Engine=MergeTree.

Just to clarify, I am copying the data when testing by running `ATTACH PARTITION`. Inserting doesn't reproduce the problem because whenever I try to SELECT data it returns random subset of the data and this subset produces stable results.

It seems to be some kind of corruption of the partition. I did run `CHECK TABLE` and it didn't show any problems.

**Comment by den-crane** [comment]
@geronimogoemon can you check please this query

```sql
SELECT max(timestamp) FROM (
	SELECT timestamp, column_1, column_2, column_3
	FROM test_table
	ORDER BY identity(timestamp)
	LIMIT 1500
)
```

**Comment by geronimogoemon** [comment]
Oh that did it! I downgraded to CH 22.3.12 and the problem went away. The problem is gone no matter if I use `identity(timestamp)`, `AggregatingMergeTree` or `MergeTree`. It just works!

I did a binary search on clickhouse versions to find the exact one after this problem appears and it looks like the bug appears when updating from `22.5.4.19` (he last 22.5) to '22.6.1.1985` (the first 22.6). Looking at the [change log](https://clickhouse.com/docs/en/whats-new/changelog/) it looks like this improvement could be connected 
```
Improve performance of ORDER BY with LIMIT. [#37481](https://github.com/ClickHouse/ClickHouse/pull/37481)
```

Though I am unable to see in the code what could go wrong.

**Comment by den-crane** [comment]
@geronimogoemon can you please share

```
select name, rows, min_date, max_date, min_time, max_time 
from system.parts 
where table = 'test_table' and active=1
```

**Comment by geronimogoemon** [comment]
Here is the result when running the query on my personal laptop.

|name|rows|min_date|max_date|min_time|max_time|
|----|----|--------|--------|--------|--------|
|202208_2_2_190|5337323|1970-01-01|1970-01-01|2022-08-01 00:00:01.000000000|2022-08-31 23:59:58.000000000|

**Comment by den-crane** [comment]
Does it reproduce if you query only `timestamp` column ?


```sql
SELECT max(timestamp) FROM (
	SELECT timestamp
	FROM test_table
	ORDER BY timestamp asc
	LIMIT 1500
)

```

Try

```
CREATE TABLE test_table1 (
	"timestamp" Datetime64(6) NOT NULL
) ENGINE = Memory


insert into test_table1 select timestamp from test_table
order by "column_1", "column_2", "timestamp", "column_3" 
settings max_threads=1, max_block_size=10000000;

SELECT max(timestamp) FROM (
	SELECT timestamp
	FROM test_table1
	ORDER BY timestamp asc
	LIMIT 1500
)
```

**Comment by geronimogoemon** [comment]
Querying only timestamp does reproduce it.

Running the second code snippet produces consistent results without the bug.

**Comment by den-crane** [comment]
Try `MergeTree order by tuple()`

```
CREATE TABLE test_table1 (
	"timestamp" Datetime64(6) NOT NULL
) ENGINE = MergeTree order by tuple()


insert into test_table1 select timestamp from test_table
order by "column_1", "column_2", "timestamp", "column_3" 
settings max_threads=1, max_block_size=10000000;

SELECT max(timestamp) FROM (
	SELECT timestamp
	FROM test_table1
	ORDER BY timestamp asc
	LIMIT 1500
)
```

**Comment by geronimogoemon** [comment]
`MergeTree order by tuple()` reproduces the bug

**Comment by geronimogoemon** [comment]
Oh that is so clever! Of course I can! How can I share the table parts? Should I just zip the directory `/var/lib/clickhouse/data/default/test_table1/` and send it to [support@clickhouse.com](mailto:support@clickhouse.com) ?

**Comment by geronimogoemon** [comment]
Email sent!

Just to be clear I produced the table parts using clickhouse version 22.6.1.1985. So the first version where the bug starts appearing.

**Comment by KochetovNicolai** [comment]
@geronimogoemon thank you. I was able to reproduce it with your data. Can see different result for a query on latest master as well.

**Comment by KochetovNicolai** [comment]
Have compared a result set. Sometimes I see that repeated timestamps sometimes disappear from it.
```
SELECT count()
FROM test_table1
WHERE timestamp = '2022-08-01 00:02:04.000000'

┌─count()─┐
│       4 │
└─────────┘

```

```
correct
│ 2022-08-01 00:02:03.628000 │
│ 2022-08-01 00:02:04.000000 │
│ 2022-08-01 00:02:04.000000 │
│ 2022-08-01 00:02:04.000000 │
│ 2022-08-01 00:02:04.000000 │
│ 2022-08-01 00:02:04.152000 │
wrong
│ 2022-08-01 00:02:03.628000 │
│ 2022-08-01 00:02:04.000000 │
│ 2022-08-01 00:02:04.000000 │
│ 2022-08-01 00:02:04.000000 │
│ 2022-08-01 00:02:04.152000 │
```

**Comment by KochetovNicolai** [comment]
Perfectly reproduces for a single thread
```
SELECT
    max(timestamp),
    countIf(timestamp = '2022-08-01 00:02:04.000000')
FROM
(
    SELECT timestamp
    FROM test_table1
    ORDER BY timestamp ASC
    LIMIT 1500
)
SETTINGS max_threads = 1

Query id: 1c39b704-97ee-4de4-aebf-08636a9e0115

┌─────────────max(timestamp)─┬─countIf(equals(timestamp, '2022-08-01 00:02:04.000000'))─┐
│ 2022-08-01 00:17:02.771000 │                                                        1 │
└────────────────────────────┴──────────────────────────────────────────────────────────┘
```
