### ISSUE TITLE
dim_channel 表不能执行 select *   from dim_channel  limit  1 

### ISSUE THREAD

**Issue by icexk** [ClickHouse/ClickHouse#41184]
hello：
dim_channel    The table has only 146 rows of data, but the following statement cannot be executed
select *   from dim_channel  limit  1  
DROP TABLE IF EXISTS  dws_data.dim_channel

implement  
SELECT * FROM   `system`.processes p ;
It has been staying here
<img width="631" alt="image" src="https://user-images.githubusercontent.com/43198678/189508034-df4646bd-a91e-4c32-b44c-f8c25cfd7ed0.png">

**Comment by DerekChia** [comment]
Hello, can you check if you query has finished running? 

```
SELECT * FROM system.query_log WHERE query = 'select * from dim_channel limit 1'
```

**Comment by icexk** [comment]
Hello, the query has not been executed yet

**Comment by DerekChia** [comment]
I don't understand, the query has not been executed and yet it is staying in the `system.processes`? Is this what you mean?

**Comment by icexk** [comment]
yes ，the query has not been executed and yet it is staying in the system.processes

**Comment by alexey-milovidov** [comment]
You can check what the query is doing using the Query Profiler: https://clickhouse.com/docs/en/operations/optimizing-performance/sampling-query-profiler/
