### ISSUE TITLE
In system.query_log table thread_ids column contain a lot of duplicate thread_id

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#41180]
**Describe the unexpected behaviour**
A lot of duplicate values in thread_ids column in query_log.

**How to reproduce**
```
ClickHouse version 22.8
SET opentelemetry_trace_processors=1;
SET opentelemetry_start_trace_probability=1;


SELECT
    length(thread_ids),
    length(arrayDistinct(thread_ids))
FROM system.query_log
WHERE query_id = '438a2095-d737-4460-8b13-102408f2f20a'
FORMAT Vertical

Query id: 97718237-f6f9-4a91-9f81-2cd180057f52

Row 1:
──────
length(thread_ids):                0
length(arrayDistinct(thread_ids)): 0

Row 2:
──────
length(thread_ids):                42741
length(arrayDistinct(thread_ids)): 39
```

**Expected behavior**
Only uniq thread_ids will be stored in query_log

**Comment by Algunenano** [comment]
Same as #40019 right? Maybe it should show unique ids; I don't see how having 42k repeated ids can be useful

**Comment by UnamedRus** [comment]
> Same as https://github.com/ClickHouse/ClickHouse/issues/40019 right?

Yeah, i think so.

>Maybe it should show unique ids; 
Yes.

**Comment by alexey-milovidov** [comment]
This behavior is correct.

If you don't like the `thread_ids` column, don't look there.
It is intended for ClickHouse developers and does not affect query processing.

Although I don't mind if we will put only unique thread ids there.

**Comment by UnamedRus** [comment]
> If you don't like the thread_ids column, don't look there.

I have concern about system.query_log size grow with 40k elements in single column.

**Comment by SaltTan** [comment]
FYI
```
result_rows | result_bytes | query                                                                                                                                                            
------------+--------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------
          3 |     84148224 | select thread_ids from system.query_log where event_date=today() and query_kind='Select' and result_bytes>5000000 limit 100 FORMAT TabSeparatedWithNamesAndTypes;
```

**Comment by UnamedRus** [comment]
Fix https://github.com/ClickHouse/ClickHouse/pull/42180
