### ISSUE TITLE
Support DWARF-5

### ISSUE THREAD

**Issue by azat** [ClickHouse/ClickHouse#41191]
*So I decided to create an issues, to include all the details in one place, instead of lots of random comments. So this issues is just and index of related issues.*

Right now there are multiple issues with DWARF-5:

- the parser does not supports it (though patches are ready - #40710, #40772, #41063)
- gdb that is used in stress tests is too old to support it
  - [Gdb < 10.1 can’t read clang’s DWARF v5](https://discourse.llvm.org/t/gdb-10-1-cant-read-clangs-dwarf-v5/6035) - even though it seems that version that images has should include the fix, but apparently it is not enough - https://github.com/ClickHouse/ClickHouse/pull/40772#issuecomment-1236331323
  - It seems it also may play bad with SDT - https://github.com/ClickHouse/ClickHouse/pull/41063#issuecomment-1242992314

**Comment by alexey-milovidov** [comment]
@al13n321, is it supported already?
