### ISSUE TITLE
Add MergeTree Option to automaticly drop old partition

### ISSUE THREAD

**Issue by mcarbonneaux** [ClickHouse/ClickHouse#4119]
while be useful to add MergeTree engine option to automatically drop old partition based on criteria on the partition key.

in that way table are automaticly purged without extrenal script/program...

**Comment by alexey-milovidov** [comment]
This task is assigned to https://github.com/CurtizJ.
He will implement custom TTL expressions for columns.

**Comment by mcarbonneaux** [comment]
https://github.com/yandex/ClickHouse/pull/4212

It's the ttl expression?

**Comment by filimonov** [comment]
Implemented long ago
https://clickhouse.yandex/docs/en/operations/table_engines/mergetree/#table_engine-mergetree-ttl
