### ISSUE TITLE
Upgrade librdkafka version

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#41216]
See https://github.com/edenhill/librdkafka/blob/master/CHANGELOG.md

That should fix 
https://github.com/ClickHouse/ClickHouse/issues/40238

And maybe
https://github.com/ClickHouse/ClickHouse/issues/30989 
https://github.com/ClickHouse/ClickHouse/issues/15473

I've tried upgrade to 1.7.0 some time ago, and there were some issues with openssl (probably caused by https://github.com/edenhill/librdkafka/pull/3315 and may be by https://github.com/ClickHouse/librdkafka/commit/f68f261ceafb887824deb7848e1ff8d2eb33f956  )

**Comment by azat** [comment]
@filimonov which particular changelog entry should fix #40238?

**Comment by alexey-milovidov** [comment]
@filimonov Let's continue.

**Comment by alexey-milovidov** [comment]
@filimonov, Nothing was done - closing.

**Comment by filimonov** [comment]
It was a lot done actually.

The problem ie that there were no version of librdkafka newer than 2.0beta which can pass our CI/CD tests. :/ fixing it requires diving too deep into their code (it's a race), so we just reported that (long ago) to the library maintainers. Recently there was a PR which fixes the exact issue which lead to failures, but after appling that the another issue pops up...

We still not losing hope...
