### ISSUE TITLE
BC check: Part was found on disk `local_cache` which is not defined in the storage policy

### ISSUE THREAD

**Issue by tavplubix** [ClickHouse/ClickHouse#41218]
https://s3.amazonaws.com/clickhouse-test-reports/41129/6eead4ea1e7cb85f1a170cd0f766bbc983603865/stress_test__ubsan_.html

Probably introduced in https://github.com/ClickHouse/ClickHouse/pull/36171

cc: @kssenii

**Comment by kssenii** [comment]
hmm, I added this https://github.com/ClickHouse/ClickHouse/blob/70066986e97f2684dc81b859db42002265e67be0/docker/test/stress/run.sh#L374-L376  to fix this issue

**Comment by tavplubix** [comment]
In this case if fails when we try to start new version after running stress tests with old version

**Comment by novikd** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/40762/c236706703f9474d654482537284564abafed471/stress_test__ubsan_.html

**Comment by tavplubix** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/41263/f2acb53887807ce0d1b681a455b0be77589500d1/stress_test__ubsan_.html

**Comment by tavplubix** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/0/8922f813997b7d17aa763e0f682fb7dcadbc579a/stress_test__ubsan_.html

**Comment by tavplubix** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/0/e20bc9953cfc89216e8f2fc02fcd3fa453fd3eac/stress_test__debug_.html

**Comment by tavplubix** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/41654/224ed6174dee877f639d5ca3f389786a970a8f1f/stress_test__debug_.html

**Comment by antonio2368** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/41784/728fe5d06fcb4e0866b8db584dcd5b6475473a4b/stress_test__msan_.html

**Comment by tavplubix** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/41945/035be1feae943e9a18e6ed6279867ef5a3a52943/stress_test__msan_.html

**Comment by tavplubix** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/42406/fffecbb9adc8d3de095352a0e2a4822343ede7e5/stress_test__msan_.html

**Comment by tavplubix** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/42522/e2417eb518540b631f83b5c34adb00a0f136442c/stress_test__asan_.html

**Comment by tavplubix** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/42878/eb19df0094bc6bda65d5b39c222fb8c501d02f75/stress_test__ubsan_.html

**Comment by tavplubix** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/43781/e45105bf44703b6396c55b66133b5dba1ebebb0e/stress_test__ubsan_.html

**Comment by tavplubix** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/42807/eb4f755a8e0bb9c5e364c896d9c55cfef777ce55/stress_test__ubsan_.html

**Comment by tavplubix** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/44513/8d0ad4bbcdad4f7dd17a7645821bcbb080fd1ce1/stress_test__tsan_.html
