### ISSUE TITLE
Rename of TinyLog table in Ordinary database fails with error

### ISSUE THREAD

**Issue by saradickinson** [ClickHouse/ClickHouse#41259]
An attempt to move an `ENGINE=TinyLog`  table from an `Ordinary` database to an `Atomic` one via a `RENAME` fails with error
`Received exception from server (version 22.3.6):
Code: 1001. DB::Exception: Received from localhost:9000. DB::Exception: std::__1::__fs::filesystem::filesystem_error: filesystem error: in rename: No such file or directory [/var/lib/clickhouse/data/db1/log_table/] [/var/lib/clickhouse/store/9c4/9c4a1974-adf7-4e3e-98e6-a3e49f805860/]. (STD_EXCEPTION)` . The table is also no longer listed in the original database. 

This works fine if moving within a single `Ordinary` database, or if moving from an `Atomic` database.

Problem seem on 22.3.6.5

**How to reproduce**

* Which ClickHouse server version to use

22.3.6.5

* `CREATE TABLE` statements for all tables involved

CREATE DATABASE db1 ENGINE = Ordinary;
CREATE DATABASE db2 ENGINE = Atomic;
CREATE TABLE db1.log_table (`int` UInt16 DEFAULT CAST(0, 'UInt16') ) ENGINE = TinyLog;
SHOW TABLES FROM db1

┌─name──────┐
│ log_table │
└───────────┘

1 rows in set. Elapsed: 0.003 sec.

* Sample data for all these tables

INSERT into db1.log_table values (1);

* Queries to run that lead to unexpected result

RENAME TABLE db1.log_table TO db2.log_table

`Received exception from server (version 22.3.6):
Code: 1001. DB::Exception: Received from localhost:9000. DB::Exception: std::__1::__fs::filesystem::filesystem_error: filesystem error: in rename: No such file or directory [/var/lib/clickhouse/data/db1/log_table/] [/var/lib/clickhouse/store/9c4/9c4a1974-adf7-4e3e-98e6-a3e49f805860/]. (STD_EXCEPTION)`

SHOW tables in db1

`Ok.

0 rows in set. Elapsed: 0.004 sec.`

**Expected behavior**

Rename should succeed (as it does when db1 is of ENGINE Atomic) or should get a graceful fail with e.g. NOT_IMPLEMENTED and the table is left unchanged. However, the rename fails and the table is no longer listed in db1.

Looking on disk it is true that the directory `/var/lib/clickhouse/store/9c4/9c4a1974-adf7-4e3e-98e6-a3e49f805860/` does not exist. The other directory does exist:
`sudo ls -l /var/lib/clickhouse/data/db1/log_table
total 8
-rw-r----- 1 clickhouse clickhouse 28 Sep 13 12:23 int.bin
-rw-r----- 1 clickhouse clickhouse 42 Sep 13 12:23 sizes.json`

**Additional context**

We are trying to migrate from Ordinary database to Atomic and using rename is the obvious method.

**Comment by tavplubix** [comment]
This bug was fixed in https://github.com/ClickHouse/ClickHouse/pull/39933

**Comment by saradickinson** [comment]
@tavplubix Thanks for quick reply - looks like this option went into 22.8 - any plans to back port to 22.3?

**Comment by saradickinson** [comment]
@tavplubix Thank you!
