### ISSUE TITLE
(zero copy replication) There are too many nodes under zero-copy-s3 path.

### ISSUE THREAD

**Issue by zhaojintaozhao** [ClickHouse/ClickHouse#41265]
There are too many nodes under zero-copy-s3 path.

**Describe the bug**
Hi all.
In my system, There are 100 shards and 1000 tables and using zero copy replication. There are different table_shared_id between shards and tables.  ClickHouse lock shared data under /clickhouse/zero_copy/zero_copy_s3. 

There are 100 000 UUID nodes under zero-copy-s3 path, That's too many.

Does anyone face the same problem?

**Comment by sunny19930321** [comment]
yes，I had this problem，are there any good solutions @zhaojintaozhao
