### ISSUE TITLE
Clickhouse got stuck and had thrown a coredump

### ISSUE THREAD

**Issue by patrick-me** [ClickHouse/ClickHouse#41269]
Clickhouse got stuck and had thrown a coredump
Optimize table process has been started there before the fail

**Does it reproduce on recent release?**

v22.3.6.5-lts

**Error message and/or stacktrace**

https://pastila.nl/?00ea0713/9ad972e00fde60564ff00853050fcc1d

Can't provide the coredump file for NDA reason, but ready to analyse it

**Comment by den-crane** [comment]
Do you have complex default/materialize expressions on the table (Optimize table ) ?

>(from thread 22808) (query_id: c3a943ed-92af-41dd-953d-0ab6226a18a6) (query: SELECT

Can you share SELECT and show create table ?

**Comment by patrick-me** [comment]
> Do you have complex default/materialize expressions on the table (Optimize table ) ?

No, we don't, but I'll find those tables and check
>Can you share SELECT and show create table ?

One of them is here https://pastila.nl/?04432e0c/1844e3e6290e72a5b3da5eff1e66e80b
There is a typical scheme for all our tables: local_table + distributed one

**Comment by alexey-milovidov** [comment]
Need to upgrade to 22.3.12 to get the latest patches and security updates.

**Comment by syominsergey** [comment]
we have updated ClickHouse up to version 22.3.12
but problem remains
output of `zgrep -Fa Fatal /var/log/clickhouse-server/* |& tee fatal.txt` attached
[fatal.txt](https://github.com/ClickHouse/ClickHouse/files/9609525/fatal.txt)
(just for info for yandex-market employees - that was from welder09h)
core dump named `core.20220920184601.HTTPHandler.11.welder09h.5195.c9724acfa2bb74ee360ee86510c05840` remains on our host. It has size 278G.
if you can provide some instructions how to investigate problem using this core dump - please, write them

**Comment by syominsergey** [comment]
[fatal.txt](https://github.com/ClickHouse/ClickHouse/files/9609993/fatal.txt)
more informative log for last case with query

**Comment by syominsergey** [comment]
and here is `show create table market.main_report` for more information
[show-create-table-market-main_report.txt](https://github.com/ClickHouse/ClickHouse/files/9610121/show-create-table-market-main_report.txt)

**Comment by KochetovNicolai** [comment]
@syominsergey you have attached a table schema and logs, but I still can't find the select query caused it.
Can you do `zgrep -a c3a943ed-92af-41dd-953d-0ab6226a18a6 /var/log/clickhouse-server/*` and send the result? Without it it would be almost impossible to find a bug.
