### ISSUE TITLE
Not working table\dict with ODBC connection to Oracle DB after upgrade ClickHouse version.

### ISSUE THREAD

**Issue by alexsubota** [ClickHouse/ClickHouse#41266]
Select table\dict with odbc connection stop working after upgrade ClickHouse version.

How to reproduce:
1) Deploy ClickHouse
2) Install ODBC\TDS libraries (unixodbc, tdsodbc)
3) Configure config files for Oracle DB connection
4) Create table at ClickHouse with `ENGINE = ODBC('DSN=my_connection', 'MY_SCHEMA', 'MY_TABLE')`
5) Try to select table from step 4

Expected behavior:
Selected data from Oracle DB at ClickHouse

Current behavior:
got error ```Received error from remote server /identifier_quote?version=1&connection_string=DSN%3Dmy_connection. HTTP status code: 500 Internal Server Error, body: Error getting identifier quote style from ODBC 'std::exception. Code: 1001, type: nanodbc::database_error, e.what() = ../contrib/nanodbc/nanodbc/nanodbc.cpp:1046: 0100: [unixODBC][Driver Manager]Can't open lib '/opt/oracle/instantclient_21_6/libsqora.so.21.1' : file ```

But file '/opt/oracle/instantclient_21_6/libsqora.so.21.1' exists

Tested on:
22.8.4.7 - not working
22.7.5.13 - not working
22.6.7.7 - not working
22.5.4.19 - not working
22.3.12.19 - working!

**Comment by kssenii** [comment]
hm, are you sure about the versions you checked? I checked all commits between versions 22.3 and 22.4 and there were no commits that change any logic in odbc bridge code, let alone the nanodbc library.

**Comment by den-crane** [comment]
@alexsubota do you use systemd or systemV (init.d) ?

can you share `cat /etc/default/clickhouse` ?

**Comment by alexsubota** [comment]
> hm, are you sure about the versions you checked? I checked all commits between versions 22.3 and 22.4 and there were no commits that change anything serious in odbc bridge code, let alone the nanodbc library.

My bad, 22.4.6.53 not tested

**Comment by den-crane** [comment]
> ClickHouse running by Docker

Then how you setup and configure ORACLE client? Or do you run odbc-bridge using another docker?

**Comment by alexsubota** [comment]
> > ClickHouse running by Docker
> 
> Then how you setup and configure ORACLE client? Or do you run odbc-bridge using another docker?

Dockerfile

`from clickhouse/clickhouse-server:22.3.12.19

RUN apt-get update \
      && apt-get install -y curl unzip \
      && apt-get autoremove -yqq --purge \
      && apt-get clean \
      && rm -rf /var/lib/apt/lists/*

# setup oracle odbc
RUN curl https://download.oracle.com/otn_software/linux/instantclient/instantclient-basic-linuxx64.zip -o /tmp/instantclient.zip \
&& unzip /tmp/instantclient.zip -d /opt/oracle \
&& rm /tmp/instantclient.zip

RUN curl https://download.oracle.com/otn_software/linux/instantclient/instantclient-odbc-linuxx64.zip -o /tmp/instantclient-odbc.zip \
&& unzip /tmp/instantclient-odbc.zip -d /opt/oracle \
&& rm /tmp/instantclient-odbc.zip

ENV LD_LIBRARY_PATH /opt/oracle/instantclient_21_6:$LD_LIBRARY_PATH

RUN apt-get update \
      && apt-get install -y unixodbc tdsodbc libaio1 \
      && apt-get autoremove -yqq --purge \
      && apt-get clean \
      && rm -rf /var/lib/apt/lists/*`

**Comment by den-crane** [comment]
https://github.com/ClickHouse/ClickHouse/pull/37211 @azat  @alexey-milovidov

**Comment by alexey-milovidov** [comment]
@alexsubota Put the library into /usr/lib or a similar location so you don't have to set up LD_LIBRARY_PATH.

**Comment by alexsubota** [comment]
> @alexsubota Put the library into /usr/lib or a similar location so you don't have to set up LD_LIBRARY_PATH.

Tried copying libsqora.so.21.1 file and instantclient_21_6 folder to /usr/lib and /usr/lib64, but nothing helps

**Comment by den-crane** [comment]
@alexsubota try 
```
cp /opt/oracle/instantclient_21_6/*so*  /usr/lib64
cp /opt/oracle/instantclient_21_6/*so*  /usr/lib
cp /opt/oracle/instantclient_21_6/*so*  /lib
```

**Comment by alexsubota** [comment]
> @alexsubota try
> 
> ```
> cp /opt/oracle/instantclient_21_6/*so*  /usr/lib64
> cp /opt/oracle/instantclient_21_6/*so*  /usr/lib
> cp /opt/oracle/instantclient_21_6/*so*  /lib
> ```

It helps, thanks!

**Comment by den-crane** [comment]
I guess only one `cp` is required. You can test which one works for you.
