### ISSUE TITLE
Unable to use HDFS as remote storage

### ISSUE THREAD

**Issue by pulkitkalia1994** [ClickHouse/ClickHouse#41279]
Hi!

I am using HDFS as a remote/external storage for Clickhouse and getting the below error-

**2022.09.13 18:13:59.244733 [ 65572 ] {} <Error> void DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::routine(DB::TaskRuntimeDataPtr) [Queue = DB::MergeMutateRuntimeQueue]: Code: 33. DB::Exception: Cannot read all marks from file store/ae0/ae031c70-4a4c-43c2-a3f7-cc7bb954cf46/1_1_1_0/data.mrk3. (CANNOT_READ_ALL_DATA), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa4dde1a in /usr/bin/clickhouse
1. DB::MergeTreeMarksLoader::loadMarksImpl() @ 0x14fa5e6c in /usr/bin/clickhouse
2. DB::MergeTreeMarksLoader::loadMarks() @ 0x14fa4b48 in /usr/bin/clickhouse
3. DB::MergeTreeReaderCompact::getReadBufferSize(std::__1::shared_ptr<DB::IMergeTreeDataPart const> const&, DB::MergeTreeMarksLoader&, std::__1::vector<std::__1::optional<unsigned long>, std::__1::allocator<std::__1::optional<unsigned long> > > const&, std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange> > const&) @ 0x14f9e14e in /usr/bin/clickhouse
4. DB::MergeTreeReaderCompact::MergeTreeReaderCompact(std::__1::shared_ptr<DB::MergeTreeDataPartCompact const>, DB::NamesAndTypesList, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::UncompressedCache*, DB::MarkCache*, std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange> >, DB::MergeTreeReaderSettings, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, double, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, double> > >, std::__1::function<void (DB::ReadBufferFromFileBase::ProfileInfo)> const&, int) @ 0x14f9cf9e in /usr/bin/clickhouse
5. DB::MergeTreeDataPartCompact::getReader(DB::NamesAndTypesList const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange> > const&, DB::UncompressedCache*, DB::MarkCache*, DB::MergeTreeReaderSettings const&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, double, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, double> > > const&, std::__1::function<void (DB::ReadBufferFromFileBase::ProfileInfo)> const&) const @ 0x14f05353 in /usr/bin/clickhouse
6. DB::MergeTreeSequentialSource::MergeTreeSequentialSource(DB::MergeTreeData const&, std::__1::shared_ptr<DB::StorageSnapshot const> const&, std::__1::shared_ptr<DB::IMergeTreeDataPart const>, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >, bool, bool, bool) @ 0x14fb4fb6 in /usr/bin/clickhouse
7. DB::MergeTask::ExecuteAndFinalizeHorizontalPart::createMergedStream() @ 0x14e51b55 in /usr/bin/clickhouse
8. DB::MergeTask::ExecuteAndFinalizeHorizontalPart::prepare() @ 0x14e4f894 in /usr/bin/clickhouse
9. bool std::__1::__function::__policy_invoker<bool ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::MergeTask::ExecuteAndFinalizeHorizontalPart::subtasks::'lambda'(), bool ()> >(std::__1::__function::__policy_storage const*) @ 0x14e5df89 in /usr/bin/clickhouse
10. DB::MergeTask::ExecuteAndFinalizeHorizontalPart::execute() @ 0x14e5450b in /usr/bin/clickhouse
11. DB::MergeTask::execute() @ 0x14e5945a in /usr/bin/clickhouse
12. DB::MergePlainMergeTreeTask::executeStep() @ 0x14e4ad8c in /usr/bin/clickhouse
13. DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::routine(std::__1::shared_ptr<DB::TaskRuntimeData>) @ 0xa4c3aab in /usr/bin/clickhouse
14. DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::threadFunction() @ 0xa4c36f9 in /usr/bin/clickhouse
15. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0xa5878ca in /usr/bin/clickhouse
16. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()&&...)::'lambda'()::operator()() @ 0xa589a64 in /usr/bin/clickhouse
17. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa584c97 in /usr/bin/clickhouse
18. ? @ 0xa58881d in /usr/bin/clickhouse
19. start_thread @ 0x76db in /lib/x86_64-linux-gnu/libpthread-2.27.so
20. __clone @ 0x12188f in /lib/x86_64-linux-gnu/libc-2.27.so
(version 22.3.2.1)
2022.09.13 18:13:59.250230 [ 65590 ] {} <Error> void DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::routine(DB::TaskRuntimeDataPtr) [Queue = DB::MergeMutateRuntimeQueue]: Code: 33. DB::Exception: Cannot read all marks from file store/ae0/ae031c70-4a4c-43c2-a3f7-cc7bb954cf46/1_1_1_0/data.mrk3. (CANNOT_READ_ALL_DATA), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa4dde1a in /usr/bin/clickhouse
1. DB::MergeTreeMarksLoader::loadMarksImpl() @ 0x14fa5e6c in /usr/bin/clickhouse
2. DB::MergeTreeMarksLoader::loadMarks() @ 0x14fa4b48 in /usr/bin/clickhouse
3. DB::MergeTreeReaderCompact::getReadBufferSize(std::__1::shared_ptr<DB::IMergeTreeDataPart const> const&, DB::MergeTreeMarksLoader&, std::__1::vector<std::__1::optional<unsigned long>, std::__1::allocator<std::__1::optional<unsigned long> > > const&, std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange> > const&) @ 0x14f9e14e in /usr/bin/clickhouse
4. DB::MergeTreeReaderCompact::MergeTreeReaderCompact(std::__1::shared_ptr<DB::MergeTreeDataPartCompact const>, DB::NamesAndTypesList, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::UncompressedCache*, DB::MarkCache*, std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange> >, DB::MergeTreeReaderSettings, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, double, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, double> > >, std::__1::function<void (DB::ReadBufferFromFileBase::ProfileInfo)> const&, int) @ 0x14f9cf9e in /usr/bin/clickhouse
5. DB::MergeTreeDataPartCompact::getReader(DB::NamesAndTypesList const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange> > const&, DB::UncompressedCache*, DB::MarkCache*, DB::MergeTreeReaderSettings const&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, double, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, double> > > const&, std::__1::function<void (DB::ReadBufferFromFileBase::ProfileInfo)> const&) const @ 0x14f05353 in /usr/bin/clickhouse
6. DB::MergeTreeSequentialSource::MergeTreeSequentialSource(DB::MergeTreeData const&, std::__1::shared_ptr<DB::StorageSnapshot const> const&, std::__1::shared_ptr<DB::IMergeTreeDataPart const>, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >, bool, bool, bool) @ 0x14fb4fb6 in /usr/bin/clickhouse
7. DB::MergeTask::ExecuteAndFinalizeHorizontalPart::createMergedStream() @ 0x14e51b55 in /usr/bin/clickhouse
8. DB::MergeTask::ExecuteAndFinalizeHorizontalPart::prepare() @ 0x14e4f894 in /usr/bin/clickhouse
9. bool std::__1::__function::__policy_invoker<bool ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::MergeTask::ExecuteAndFinalizeHorizontalPart::subtasks::'lambda'(), bool ()> >(std::__1::__function::__policy_storage const*) @ 0x14e5df89 in /usr/bin/clickhouse
10. DB::MergeTask::ExecuteAndFinalizeHorizontalPart::execute() @ 0x14e5450b in /usr/bin/clickhouse
11. DB::MergeTask::execute() @ 0x14e5945a in /usr/bin/clickhouse
12. DB::MergePlainMergeTreeTask::executeStep() @ 0x14e4ad8c in /usr/bin/clickhouse
13. DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::routine(std::__1::shared_ptr<DB::TaskRuntimeData>) @ 0xa4c3aab in /usr/bin/clickhouse
14. DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::threadFunction() @ 0xa4c36f9 in /usr/bin/clickhouse
15. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0xa5878ca in /usr/bin/clickhouse
16. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()&&...)::'lambda'()::operator()() @ 0xa589a64 in /usr/bin/clickhouse
17. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa584c97 in /usr/bin/clickhouse
18. ? @ 0xa58881d in /usr/bin/clickhouse
19. start_thread @ 0x76db in /lib/x86_64-linux-gnu/libpthread-2.27.so
20. __clone @ 0x12188f in /lib/x86_64-linux-gnu/libc-2.27.so
(version 22.3.2.1)**

Version - 22.3.2.1 

PS: I am able to insert the data into HDFS but get the above error when querying the data.

**Comment by ArsenyClean** [comment]
@pulkitkalia1994 Hi!
Did you solve?

**Comment by pulkitkalia1994** [comment]
@ArsenyClean - Sadly, no.

**Comment by kssenii** [comment]
Please show table structure and used storage configuration. I see in the stack trace you attached that the error happened during merge. But it also happens during read? Reproduces each time you query? Just trying to understand what is different in your case, because we have quite a lot of tests in CI for hdfs as remote storage and they still pass. May be you can make an example of steps to do to reproduce?

**Comment by alexey-milovidov** [comment]
No info provided.
