### ISSUE TITLE
If user accessing a package listing at the old package repository `repo.clickhouse.com` or `repo.clickhouse.tech` from a browser, it should redirect to `packages.clickhouse.com`

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#41289]
It is needed to gradually obsolete the old package repository.

Listing pages are like https://repo.clickhouse.com/deb/stable/main/
and browsers are like `^Mozilla/`.

**Comment by Felixoid** [comment]
Hmm, we can redirect everything ending with `/` to packages top level index, yes
