### ISSUE TITLE
Non human readable partition names are created when using Date32 column in PARTITION BY

### ISSUE THREAD

**Issue by rvasin** [ClickHouse/ClickHouse#41295]
**Describe what's wrong**

When partitions are created based on Date32 columns ClickHouse produces partitions with wrong names like -6991 or -6940

**Does it reproduce on recent release?**

Yes.

* Which ClickHouse server version to use
22.9.1.1.

**How to reproduce**

```
create table test_tbl (vend_nm String, ship_dt Date32) engine MergeTree partition by ship_dt order by vend_nm;

insert into test_tbl values('1', '1950-11-11'), ('1', '1951-01-01');

select _partition_id, * From test_tbl where ship_dt >= toDate32('1950-11-01') and ship_dt <= toDate32('1951-05-05') order by ship_dt;

select _partition_id, * From test_tbl where ship_dt >= toDate32('1950-11-01') and ship_dt <= toDate32('1951-05-05') order by ship_dt;

drop table test_tbl;
```

Output:

```
-6991	1	1950-11-11
-6940	1	1951-01-01
-6991	1	1950-11-11
-6940	1	1951-01-01
```

Verify partition names in file system (without prior table dropping):

```
cd /var/lib/clickhouse/data/default/test_tbl
ls -lh
```

Output:

```
drwxr-x--- 2 rvasin rvasin 4.0K Sep 14 08:59 -6940_2_2_0
drwxr-x--- 2 rvasin rvasin 4.0K Sep 14 08:59 -6991_1_1_0
drwxr-x--- 2 rvasin rvasin 4.0K Sep 14 08:59 detached
-rw-r----- 1 rvasin rvasin    1 Sep 14 08:59 format_version.txt
```

**Expected behavior**

Output should be:
```
19501111	1	1950-11-11
19510101	1	1951-01-01
19501111	1	1950-11-11
19510101	1	1951-01-01
```

**Correct behavior for Date type in partition name**

```
create table test_tbl (vend_nm String, ship_dt Date) engine MergeTree partition by ship_dt order by vend_nm;

insert into test_tbl values('1', '1980-11-11'), ('1', '1981-01-01');

select _partition_id, * From test_tbl where ship_dt >= toDate('1980-11-01') and ship_dt <= toDate('1981-05-05') order by ship_dt;

select _partition_id, * From test_tbl where ship_dt >= toDate('1980-11-01') and ship_dt <= toDate('1981-05-05') order by ship_dt;

drop table test_tbl;
```

Output:
```
19801111	1	1980-11-11
19810101	1	1981-01-01
19801111	1	1980-11-11
19810101	1	1981-01-01
```

**Comment by tavplubix** [comment]
> Output should be:

It does not have to, partition ids are implementation defined. Internal representation of Date32 is Int32 (however, I don't why not UInt32 and why '1950-11-11' produces negative value), so it's simply serialized as Int32. Yes, human-readable partition id is provided for `Date` data type (see `MergeTreePartition::getID` and `MergeTreePartition::tryParseValueFromID`) and we could also provide it for `Date32`, but we forgot to initially add it in https://github.com/ClickHouse/ClickHouse/pull/26364, so now it's really hard to change without breaking backward compatibility.

**Comment by UnamedRus** [comment]
>  (however, I don't why not UInt32)
>  why '1950-11-11' produces negative value)

I guess, because it was implemented just like DateTime64 (except of not using Decimal as there is no millidays)
So all dates before epoch is negative:

```
┌─CAST(toDate32('1969-12-31'), 'Int32')─┐
│                                    -1 │
└───────────────────────────────────────┘
```

**Comment by rvasin** [comment]
@tavplubix thank you for clarification about the partition ids.
Could you please comment about such scenarios:
1. Right now customers have in their file system partitions with IDs like -6991.
2. Someone implements in PR new behavior: when partition ID is based on Date32 it will be human readable form like 19501111 
3. Customer install CH update for all NEW partitions created after, for example, after executing INSERT some data partitions are created in human readable form like 19501111 while file system will continue to keep old data in partitions with non human readable form like -6991.
Will it break backward compatibility? Or is it technically impossible? 

What I see in `MergeTreePartition::getID i`t's probably partition ID is generated "on fly" based on `Block & partition_key_sample` so it seems like it's technically impossible to keep old -6991 and new 19501111  partition IDs at the same time for different data.

**Comment by alexey-milovidov** [comment]
Even if it is possible to change, let's not implement this feature.

**Comment by rvasin** [comment]
Yes, it's not worth to implement because of many potential risks as explained @tavplubix
