### ISSUE TITLE
Why is the efficiency of clickhouse two queries inconsistent? The first time is time-consuming, and the second time is much more efficient

### ISSUE THREAD

**Issue by shenhaifeng22** [ClickHouse/ClickHouse#41298]
I use the clickhouse query, but the efficiency is not the same twice. 
clickhouse version 22.9.1.1555
For example
 `select * from asharefinancialindicator_s_fa_eps_basic_s3 limit 10;`

1. the first time 

      10 rows in set. Elapsed: 7.615 sec

2. the second time
    10 rows in set. Elapsed: 3.229 sec.

When I use the local cache, it doesn't seem to affect the query performance, what is the reason?
reference：https://clickhouse.com/docs/en/operations/storing-data/#using-local-cache
My configuration is as follows：
`<cache>
	<type>cache</type>
	<disk>s3_minio</disk>
	<path>/var/lib/clickhouse/disks/s3_minio/data_cache/</path>
	<max_size>1000000000</max_size>
	<enable_filesystem_cache>1</enable_filesystem_cache>
	<read_from_filesystem_cache_if_exists_otherwise_bypass_cache>1</read_from_filesystem_cache_if_exists_otherwise_bypass_cache>
	<enable_filesystem_query_cache_limit>1</enable_filesystem_query_cache_limit>
	<max_query_cache_size>256000000</max_query_cache_size>
</cache>`

**Comment by kssenii** [comment]
first time is slower than the second and you are using cache, why such behaviour is unexpected?

also you use `read_from_filesystem_cache_if_exists_otherwise_bypass_cache=1` in disk config? this settings is a user level settings, so adding it to disk config is pointless.

**Comment by shenhaifeng22** [comment]
Maybe I didn't describe the problem clearly，When I remove the configuration of local cache and do not do any configuration, the first time is slower than the second time, which is related to what mechanism of clickhouse?

`<!--<cache> <type>cache</type> <disk>s3_minio</disk> <path>/var/lib/clickhouse/disks/s3_minio/data_cache/</path> <max_size>1000000000</max_size> <enable_filesystem_cache>1</enable_filesystem_cache> <read_from_filesystem_cache_if_exists_otherwise_bypass_cache>1</read_from_filesystem_cache_if_exists_otherwise_bypass_cache> <enable_filesystem_query_cache_limit>1</enable_filesystem_query_cache_limit> <max_query_cache_size>256000000</max_query_cache_size> </cache>-->`

 I have commented it out in the config file

**Comment by shenhaifeng22** [comment]
Dear Sumarokova,
  Many thanks for your great support and guidence. Let me just clarify my testing approach and question.
  
  My test steps:
    1. without any configuration (do not add any local cache config in disk.xml)
    2. execute SQL: select * from table(5000 columns) limit 10
	 
	Result:
	1st time SQL execution: 10 rows in set. Elapsed: 7.615 sec
	Run the same SQL once again, I got second elapsed time 3.229 sec. 
	We understand, the 2nd run is faster than the 1st run is reasonable, but we want to enhance the performance via add local cache configration. 
	Therefore, we add some relative local cache configration into disk.xml
	As follow: 
	<cache>
	<type>cache</type> 
	<disk>s3_minio</disk>
	<path>/var/lib/clickhouse/disks/s3_minio/data_cache/</path> 
	<max_size>1000000000</max_size> 
	<enable_filesystem_cache>1</enable_filesystem_cache> 
	<read_from_filesystem_cache_if_exists_otherwise_bypass_cache>1</read_from_filesystem_cache_if_exists_otherwise_bypass_cache>
	<enable_filesystem_query_cache_limit>1</enable_filesystem_query_cache_limit> 
	<max_query_cache_size>256000000</max_query_cache_size> 
	</cache>
	
	Our question:
	Running the same SQL, we compare the performance with the previously, the SQL execution elapsed time both for the 1st/2nd don't have any difference.
	
	So, We are confused, why the local cache configration we added, it doesn't take any effect?

**Comment by shenhaifeng22** [comment]
I checked the usage of the local cache. It seems that it doesn't work

DESCRIBE CACHE cache

Query id: 7dcf3b81-0fda-44bb-b2bc-c4f36b0af48e

┌─max_size─┬─max_elements─┬─max_file_segment_size─┬─cache_on_write_operations─┬─enable_cache_hits_threshold─┬─current_size─┬─current_elements─┬─path───────────────────────────────────────────┬─do_not_evict_index_and_mark_files─┐
│ 10000000 │      1048576 │             104857600 │                         0 │                           0 │            0 │                0 │ /var/lib/clickhouse/disks/s3_minio/data_cache/ │                                 1 │
└──────────┴──────────────┴───────────────────────┴───────────────────────────┴─────────────────────────────┴──────────────┴──────────────────┴────────────────────────────────────────────────┴───────────────────────────────────┘
current_size and  current_elements is  0？

**Comment by kssenii** [comment]
did you also change storage policy after adding this cache configuration? it is not enough to just add cache disk configuration

**Comment by kssenii** [comment]
please see https://github.com/ClickHouse/ClickHouse/pull/41354/files#
