### ISSUE TITLE
【Docker】【Distributed】ON CLUSTER SQL statment TIMEOUT

### ISSUE THREAD

**Issue by Silentharry94** [ClickHouse/ClickHouse#41300]
` CREATE DATABASE IF NOT EXISTS images ON CLUSTER cluster_3s_1r;`

CREATE DATABASE IF NOT EXISTS images ON CLUSTER cluster_3s_1r

Query id: 274cbf52-46a3-4fbc-a7f8-64fac65f12b1

0 rows in set. Elapsed: 180.788 sec.

Received exception from server (version 21.12.3):
Code: 159. DB::Exception: Received from localhost:9000. DB::Exception: Watching task /clickhouse/task_queue/ddl/query-0000000019 is executing longer than distributed_ddl_task_timeout (=180) seconds. There are 6 unfinished hosts (0 of them are currently active), they are going to execute the query in background. (TIMEOUT_EXCEEDED)

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/37281418/190120887-767a126d-d122-4c88-9e74-be3428bbf5aa.png">

**Comment by tavplubix** [comment]
It literally means that task is executing longer than 180 seconds and some hosts will execute the query in background.
