### ISSUE TITLE
The merge operation leads to the deterioration of the s3 write ability

### ISSUE THREAD

**Issue by qzhello** [ClickHouse/ClickHouse#41316]
Description:
Hello, I used s3's cold storage, but found a problem, the write performance will drop every once in a while with a lot of s3 delete operations.

Does clickhouse merge every once in a while and then perform the delete operation of s3?
When there is a delete operation of s3, it takes longer and longer for the client to send a write request, and it will time out.

Are there any optimized parameters or methods? 
Thanks!!!

Version: 22.3.2.2.4
Client Thread Number: 5
Batch Size: 5000
How to operate:  keep bulk write

Standalone mode.

Config:
```
<clickhouse>
    <storage_configuration>
        <disks>
            <s3_main>
                <type>s3</type>
                <endpoint>http://127.0.0.1:8333/clickhouse/oss/tables/</endpoint>
                <access_key_id>bHkzMjEuUVc</access_key_id>
                <secret_access_key>cXV6aGloYW8</secret_access_key>
                <region></region>
                <metadata_path>/data/clickhouse/s3/</metadata_path>

                <request_timeout_ms>15000</request_timeout_ms>
                <retry_attempts>5</retry_attempts>
                <!-- <retry_attempts>10</retry_attempts>
                <single_read_retries>4</single_read_retries>
                <min_bytes_for_seek>1000</min_bytes_for_seek>
                <skip_access_check>false</skip_access_check> -->
            </s3_main>
        </disks>
        <policies>
            <s3_only>
                <volumes>
                    <s3_main>
                        <disk>s3_main</disk>
                        <perform_ttl_move_on_insert>0</perform_ttl_move_on_insert>
                    </s3_main>
                </volumes>
            </s3_only>
        </policies>
    </storage_configuration>
</clickhouse>
```

Table:
```
CREATE TABLE lineorder_oss
  (
                                        LO_ORDERKEY             UInt32,
                                        LO_LINENUMBER           UInt8,
                                        LO_CUSTKEY              UInt32,
                                        LO_PARTKEY              UInt32,
                                        LO_SUPPKEY              UInt32,
                                        LO_ORDERDATE            Date,
                                        LO_ORDERPRIORITY        LowCardinality(String),
                                        LO_SHIPPRIORITY         UInt8,
                                        LO_QUANTITY             UInt8,
                                        LO_EXTENDEDPRICE        UInt32,
                                        LO_ORDTOTALPRICE        UInt32,
                                        LO_DISCOUNT             UInt8,
                                        LO_REVENUE              UInt32,
                                        LO_SUPPLYCOST           UInt32,
                                        LO_TAX                  UInt8,
                                        LO_COMMITDATE           Date,
                                        LO_SHIPMODE             LowCardinality(String)
                                    )
      ENGINE = MergeTree PARTITION BY toYear(LO_ORDERDATE) ORDER BY (LO_ORDERDATE, LO_ORDERKEY)  SETTINGS storage_policy='s3_only';
```

<img width="1331" alt="image" src="https://user-images.githubusercontent.com/14229565/190172625-827373ad-69c2-45ed-b73d-43f5fb1fdfeb.png">

**Comment by genzgd** [comment]
Assuming you don't actually want to do merges on S3 (which is indeed a major performance it, add `prefer_not_to_merge` into your storage configurate.  See https://clickhouse.com/docs/en/operations/system-tables/storage_policies/

**Comment by qzhello** [comment]
Thank you for your reply.  
（1）Can you tell me why there are so many delete operations all of a sudden? Is it triggered by a scheduled task?
（2）How can deletes affect writes so much? Even reduced write capability?

**Comment by genzgd** [comment]
If you have merges enabled that will cause deletes as ClickHouse tries to merge the data parts on S3.  Merges are not explicitly scheduled, but will happen continuously in the background.  It may be just a set of large parts that were stored on S3 were selected for a merge.

As for write capacity, that can depend upon many factors, but when ClickHouse is merging data from S3, it has to pull all of the data across the network from S3, write that data to a tmp file, and then write it all back across the network again.  So you adding a lot of writes to your standard "insert" writes.

**Comment by qzhello** [comment]
Thank you! here's another question.
It looks like "prefer_not_to_merge" is set to true or "stop system merges", the merge limit will not be applied, but an error occurs: "Too many parts (304)", I only inserted one piece of data.

**Comment by genzgd** [comment]
Are you using local storage for "hot" data before moving it to S3?  If you don't have any local/block storage you may have to live with merges on S3, in which case you might need to adjust your insert size or merge settings.

**Comment by alexey-milovidov** [comment]
We don't see this problem with AWS S3. Merges work fine.
Yes, the merge operation will lead to subsequent delete operations.

`prefer_not_to_merge` is generally a bad idea and I don't recommend using this setting.

**Comment by qzhello** [comment]
Yes, no problem on AWS S3,  but when the delete operation is performed to s3 after the background merge is completed, the performance of insert is reduced.
Trying to insert a batch of data (5000) takes even a dozen seconds.

**Comment by qzhello** [comment]
Hello, why some parts are not moved? It's been 4 hours and it still hasn't been moved. (It's 10:40 here)
![image](https://user-images.githubusercontent.com/14229565/191646244-19e8db1e-c4fe-4610-982c-86a8974147a0.png)

**Comment by genzgd** [comment]
What does your system.merges table show?  Are there errors for these merges in the replication queue?

**Comment by qzhello** [comment]
Thank you for reminding me. We have some problems with object storage.
There are the following errors:
```
2022.09.23 23:31:37.367648 [ 65 ] {5b9602ea-fa7c-4d97-afce-89e0af2bcdf5::20220923-15_521421_540063_6} <Warning> AWSClient: Request failed, now waiting 100 ms before attempting again.
2022.09.23 23:31:37.474071 [ 55 ] {5b9602ea-fa7c-4d97-afce-89e0af2bcdf5::20220923-14_513506_518593_5} <Error> AWSClient: Failed to make request to: http://xxxxxxx:8333/clickhouse/oss/tables/jfunmecgtpuzfjtbdhrmglsejrhfjlmp: Poco::Exception. Code: 1000, e.code() = 0, Timeout, Stack trace (when copying this message, always include the lines below):
...

2022.09.23 23:33:23.532294 [ 55 ] {5b9602ea-fa7c-4d97-afce-89e0af2bcdf5::20220923-14_513506_518593_5} <Warning> AWSClient: If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.
2022.09.23 23:33:23.532315 [ 55 ] {5b9602ea-fa7c-4d97-afce-89e0af2bcdf5::20220923-14_513506_518593_5} <Warning> AWSClient: Request failed, now waiting 200 ms before attempting again.
```

**Comment by alexey-milovidov** [comment]
ClickHouse should not do 10 000 PUT operations per second as in your screenshot.
