### ISSUE TITLE
CH version 22.8.x.x Abort in ParallelParsingInputFormat

### ISSUE THREAD

**Issue by WillMeng** [ClickHouse/ClickHouse#41337]
We haved test all 22.8 version, all failed.

**Sql**
`
INSERT INTO pub_summary_db_feed_baidu.new_account_31da14c4345711ed8ad9fa163e676c73_20220915144232 (chan_pub_id, channel_id, publisher_id, pub_account_id, pub_account_name, balance, budget, balance_package, user_status, ua_status, valid_flows, delete_time) WITH except_table AS
    (
        SELECT DISTINCT chan_pub_id
        FROM pub_summary_db_feed_baidu.pub_setting_feed_account_baidu
        WHERE chan_pub_id IN (
            SELECT chan_pub_id
            FROM pub_summary_db_feed_baidu.temp_account_31da14c4345711ed8ad9fa163e676c73_1663224152801662992
        )
        EXCEPT
        SELECT chan_pub_id
        FROM file('/data/clickhouse/data/user_files/download/202209/1663224141425/wAw10vjsIQXkPiL1/*.gz', 'CSV', 'chan_pub_id Int64,channel_id Int32,publisher_id Int32,pub_account_id Int64,pub_account_name String,balance Float64,budget Float64,balance_package Float64,user_status Int32,ua_status Int32,valid_flows String')
    )
SELECT
    details.chan_pub_id AS chan_pub_id,
    details.channel_id AS channel_id,
    details.publisher_id AS publisher_id,
    details.pub_account_id AS pub_account_id,
    details.pub_account_name AS pub_account_name,
    details.balance AS balance,
    details.budget AS budget,
    details.balance_package AS balance_package,
    details.user_status AS user_status,
    details.ua_status AS ua_status,
    details.valid_flows AS valid_flows,
    details.delete_time AS delete_time
FROM
(
    SELECT
        chan_pub_id,
        channel_id,
        publisher_id,
        pub_account_id,
        pub_account_name,
        balance,
        budget,
        balance_package,
        user_status,
        ua_status,
        valid_flows,
        IFNULL(delete_time, NOW()) AS delete_time
    FROM pub_summary_db_feed_baidu.pub_setting_feed_account_baidu AS his_table
    ANY INNER JOIN except_table ON his_table.chan_pub_id = except_table.chan_pub_id
    WHERE chan_pub_id IN (
        SELECT chan_pub_id
        FROM pub_summary_db_feed_baidu.temp_account_31da14c4345711ed8ad9fa163e676c73_1663224152801662992
    )
) AS details
WHERE ((formatDateTime(details.delete_time, '%Y-%m-%d') > '2022-09-07') AND (details.chan_pub_id IN (
    SELECT chan_pub_id
    FROM pub_summary_db_feed_baidu.temp_account_31da14c4345711ed8ad9fa163e676c73_1663224152811677745_7
))) OR ((formatDateTime(details.delete_time, '%Y-%m-%d') > '2022-06-16') AND (details.chan_pub_id NOT IN (
    SELECT chan_pub_id
    FROM pub_summary_db_feed_baidu.temp_account_31da14c4345711ed8ad9fa163e676c73_1663224152828650555_ttl
)))
UNION ALL
SELECT
    chan_pub_id,
    channel_id,
    publisher_id,
    pub_account_id,
    pub_account_name,
    balance,
    budget,
    balance_package,
    user_status,
    ua_status,
    valid_flows,
    NULL AS delete_time
FROM file('/data/clickhouse/data/user_files/download/202209/1663224141425/wAw10vjsIQXkPiL1/*.gz', 'CSV', 'chan_pub_id Int64,channel_id Int32,publisher_id Int32,pub_account_id Int64,pub_account_name String,balance Float64,budget Float64,balance_package Float64,user_status Int32,ua_status Int32,valid_flows String')
`

When concurrent queries more then 5, the clickhosue server is restart. We degrade version 22.3.x.x, it works well.

**Error log**
`
2022.09.15 14:42:33.242299 [ 32746 ] {} <Fatal> BaseDaemon: ########################################
2022.09.15 14:42:33.242410 [ 32746 ] {} <Fatal> BaseDaemon: (version 22.8.5.29 (official build), build id: 92504ACA0B8E2267) (from thread 32730) (query_id: 31da14c4345711ed8ad9fa163e676c73_0) (query:  insert into pub_summary_db_feed_baidu.new_account_31da14c4345711ed8ad9fa163e676c73_20220915144232 ( chan_pub_id,channel_id,publisher_id,pub_account_id,pub_account_name,balance,budget,balance_package,user_status,ua_status,valid_flows,delete_time ) with except_table as ( select distinct chan_pub_id from pub_summary_db_feed_baidu.pub_setting_feed_account_baidu where chan_pub_id in (select chan_pub_id from pub_summary_db_feed_baidu.temp_account_31da14c4345711ed8ad9fa163e676c73_1663224152801662992) except select chan_pub_id from file('/data/clickhouse/data/user_files/download/202209/1663224141425/wAw10vjsIQXkPiL1/*.gz', 'CSV', 'chan_pub_id Int64,channel_id Int32,publisher_id Int32,pub_account_id Int64,pub_account_name String,balance Float64,budget Float64,balance_package Float64,user_status Int32,ua_status Int32,valid_flows String') ) select details.chan_pub_id as chan_pub_id,details.channel_id as channel_id,details.publisher_id as publisher_id,details.pub_account_id as pub_account_id,details.pub_account_name as pub_account_name,details.balance as balance,details.budget as budget,details.balance_package as balance_package,details.user_status as user_status,details.ua_status as ua_status,details.valid_flows as valid_flows,details.delete_time as delete_time from ( select chan_pub_id,channel_id,publisher_id,pub_account_id,pub_account_name,balance,budget,balance_package,user_status,ua_status,valid_flows,IFNULL(delete_time, NOW()) as delete_time from pub_summary_db_feed_baidu.pub_setting_feed_account_baidu as his_table inner any join except_table on (his_table.chan_pub_id=except_table.chan_pub_id) where chan_pub_id in (select chan_pub_id from pub_summary_db_feed_baidu.temp_account_31da14c4345711ed8ad9fa163e676c73_1663224152801662992) ) details where formatDateTime(details.delete_time, '%Y-%m-%d') > '2022-09-07' and details.chan_pub_id in (select chan_pub_id from pub_summary_db_feed_baidu.temp_account_31da14c4345711ed8ad9fa163e676c73_1663224152811677745_7) or formatDateTime(details.delete_time, '%Y-%m-%d') > '2022-06-16' and details.chan_pub_id not in (select chan_pub_id from pub_summary_db_feed_baidu.temp_account_31da14c4345711ed8ad9fa163e676c73_1663224152828650555_ttl) union all select chan_pub_id,channel_id,publisher_id,pub_account_id,pub_account_name,balance,budget,balance_package,user_status,ua_status,valid_flows,null as delete_time from file('/data/clickhouse/data/user_files/download/202209/1663224141425/wAw10vjsIQXkPiL1/*.gz', 'CSV', 'chan_pub_id Int64,channel_id Int32,publisher_id Int32,pub_account_id Int64,pub_account_name String,balance Float64,budget Float64,balance_package Float64,user_status Int32,ua_status Int32,valid_flows String') ) Received signal Aborted (6)
2022.09.15 14:42:33.242453 [ 32746 ] {} <Fatal> BaseDaemon:
2022.09.15 14:42:33.242485 [ 32746 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f29ce4f2387 0x7f29ce4f3a78 0x15cfbbcf 0x1402338f 0x1535eac3 0x15bf1575 0x15bf10c6 0x15c0db4a 0x15c020bb 0x15c04959 0xa487348 0xa48a55d 0x7f29ce891ea5 0x7f29ce5bab0d
2022.09.15 14:42:33.242527 [ 32746 ] {} <Fatal> BaseDaemon: 2. gsignal @ 0x36387 in /usr/lib64/libc-2.17.so
2022.09.15 14:42:33.242548 [ 32746 ] {} <Fatal> BaseDaemon: 3. abort @ 0x37a78 in /usr/lib64/libc-2.17.so
2022.09.15 14:42:33.242581 [ 32746 ] {} <Fatal> BaseDaemon: 4. DB::ParallelParsingInputFormat::~ParallelParsingInputFormat() @ 0x15cfbbcf in /usr/bin/clickhouse
2022.09.15 14:42:33.242603 [ 32746 ] {} <Fatal> BaseDaemon: 5. DB::QueryPipeline::~QueryPipeline() @ 0x1402338f in /usr/bin/clickhouse
2022.09.15 14:42:33.242634 [ 32746 ] {} <Fatal> BaseDaemon: 6. DB::StorageFileSource::generate() @ 0x1535eac3 in /usr/bin/clickhouse
2022.09.15 14:42:33.242657 [ 32746 ] {} <Fatal> BaseDaemon: 7. DB::ISource::tryGenerate() @ 0x15bf1575 in /usr/bin/clickhouse
2022.09.15 14:42:33.242677 [ 32746 ] {} <Fatal> BaseDaemon: 8. DB::ISource::work() @ 0x15bf10c6 in /usr/bin/clickhouse
2022.09.15 14:42:33.242692 [ 32746 ] {} <Fatal> BaseDaemon: 9. DB::ExecutionThreadContext::executeTask() @ 0x15c0db4a in /usr/bin/clickhouse
2022.09.15 14:42:33.242716 [ 32746 ] {} <Fatal> BaseDaemon: 10. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x15c020bb in /usr/bin/clickhouse
2022.09.15 14:42:33.242741 [ 32746 ] {} <Fatal> BaseDaemon: 11. ? @ 0x15c04959 in /usr/bin/clickhouse
2022.09.15 14:42:33.242769 [ 32746 ] {} <Fatal> BaseDaemon: 12. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa487348 in /usr/bin/clickhouse
2022.09.15 14:42:33.242789 [ 32746 ] {} <Fatal> BaseDaemon: 13. ? @ 0xa48a55d in /usr/bin/clickhouse
2022.09.15 14:42:33.242806 [ 32746 ] {} <Fatal> BaseDaemon: 14. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
2022.09.15 14:42:33.242830 [ 32746 ] {} <Fatal> BaseDaemon: 15. clone @ 0xfeb0d in /usr/lib64/libc-2.17.so
2022.09.15 14:42:33.398346 [ 32746 ] {} <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: 4307279F3D40D9F1C04061BC7A071239)
2022.09.15 14:42:54.133511 [ 32278 ] {} <Fatal> Application: Child process was terminated by signal 6.
2022.09.15 14:43:24.371132 [ 32755 ] {} <Warning> Context: Linux is not using a fast TSC clock source. Performance can be degraded. Check /sys/devices/system/clocksource/clocksource0/current_clocksource
2022.09.15 14:43:24.371196 [ 32755 ] {} <Warning> Context: Linux transparent hugepages are set to "always". Check /sys/kernel/mm/transparent_hugepage/enabled
2022.09.15 14:43:24.570615 [ 32755 ] {} <Error> CertificateReloader: Cannot obtain modification time for certificate file /etc/clickhouse-server/server.crt, skipping update. errno: 2, strerror: No such file or directory
2022.09.15 14:43:24.570632 [ 32755 ] {} <Error> CertificateReloader: Cannot obtain modification time for key file /etc/clickhouse-server/server.key, skipping update. errno: 2, strerror: No such file or directory
2022.09.15 14:43:24.574137 [ 32755 ] {} <Error> CertificateReloader: Poco::Exception. Code: 1000, e.code() = 0, SSL context exception: Error loading private key from file /etc/clickhouse-server/server.key: error:02000002:system library:OPENSSL_internal:No such file or directory (version 22.8.5.29 (official build))

`

**Comment by tavplubix** [comment]
May be related to https://github.com/ClickHouse/ClickHouse/issues/37649, https://github.com/ClickHouse/ClickHouse/issues/37649

cc: @nikitamikhaylov

**Comment by alexey-milovidov** [comment]
@WillMeng, we need more diagnostics about this issue.
Does it appear in the latest ClickHouse release?

**Comment by WillMeng** [comment]
> 



> @WillMeng, we need more diagnostics about this issue. Does it appear in the latest ClickHouse release?

Did you mean 22.8.11.15 or 22.12.x.x ? Both of us havent tried.

**Comment by WillMeng** [comment]
@alexey-milovidov

**Comment by alexey-milovidov** [comment]
All relevant issues have been fixed.
