### ISSUE TITLE
Distribution of data in executable user-defined functions

### ISSUE THREAD

**Issue by m1khal3v** [ClickHouse/ClickHouse#41331]
This topic is poorly covered in the documentation. Let's say there are 4 asynchronous inserts (NOT async_insert=1) that insert 100k rows each, then the materialized view is triggered, which uses an external function. How many processes from the pool will get the data? 4? (here you can omit the fact that before getting into the view, the data may already be slightly divided into pieces)

And a little from the telegram chat:

```
difference between executable_pool and executable
in theory, only that the executable is launched as much as necessary (and probably ends after the end of the request ...)
and executable_pool starts several processes at once from pool_size
and if you need to calculate the function, then some kind of "free" is selected
but it is not clear what will happen if the pool is completely full ...
and how is the distribution going... one process per query or one process per block...
```

There is some uncertainty in how it all works, I would be grateful if someone clarifies

**Comment by m1khal3v** [comment]
@kitaisreal Maxim, I'll tag you, because it seems that this functionality was developed by you for the most part. If you have time please explain how it works.

**Comment by kitaisreal** [comment]
Executable UDF function is executed on block of data.
For `executable` separate process will be created for each block. It will not be efficient if your script startup take some time.
For `executable_pool` there is pool of processes where number is configured in executable UDF configuration. Some process from pool will be reused. If there are no free process in pool, thread that try to execute function will wait with `max_command_execution_time` timeout, then there are two possible solution, some process is returned to the pool or timeout expired and exception is thrown.

For high performance workload we recomment to use `executable_pool` with `send_chunk_header` enabled (if this setting is set, then before block is written into udf pipe, additional metadata is written that contains block rows size, this could be helpful for preallocation).

Related to your question how many executable functions will be executed concurrently, it is very hard to answer without reproducible example. I would expect 4.

**Comment by Slach** [comment]
@kitaisreal 
what mean "block" for this use case?
for insert 1M rows (max_insert_block_size)? for select this is 65535 rows after decompression or whole data part?

**Comment by kitaisreal** [comment]
@Slach very interesting, after I created test, during materialized view insertion, we process data in `max_insert_block_size` block size.
So all functions that are specified in materialized view SELECT statement including executable user defined functions can be potentially executed with `max_insert_block_size`, for example during INSERT SELECT.
