### ISSUE TITLE
Column Aliasing not working when doing Group BY

### ISSUE THREAD

**Issue by ThierryH** [ClickHouse/ClickHouse#41367]
Clickhouse Version : 22.1.3.7
Running in Docker 
Default Configuration 

The following request  
`select toStartOfDay(toDateTime(event_time)) as event_time,count(1) from system.query_log group by toStartOfDay(toDateTime(event_time)) `
fails with Code 215 : Column event_time is not under aggregate function and not in Group BY.

Renaming the first event_time as follow 
`select toStartOfDay(toDateTime(event_time)) as evt_tm,count(1) from system.query_log group by toStartOfDay(toDateTime(event_time)) `
 allow to make the query properly but in my context ( i'm using Superset ) the query is generated by the tool and i cannot change it. 

Thanks in advance

**Comment by den-crane** [comment]
Clickhouse column aliases works another way than in other databases.

you aliased `toStartOfDay(toDateTime(event_time)) as event_time` - event_time became an expression not the column

because of that 

```sql
SELECT
    toStartOfDay(toDateTime(event_time)) AS event_time,
    count(1)
FROM system.query_log
GROUP BY event_time


┌──────────event_time─┬─count()─┐
│ 2022-09-14 00:00:00 │     128 │
│ 2022-09-15 00:00:00 │      16 │
└─────────────────────┴─────────┘
```

If you want to address to a column, you need to use table alias

```
SELECT
    toStartOfDay(toDateTime(event_time)) AS event_time,
    count(1)
FROM system.query_log
GROUP BY toStartOfDay(toDateTime(query_log.event_time))

┌──────────event_time─┬─count()─┐
│ 2022-09-14 00:00:00 │     128 │
│ 2022-09-15 00:00:00 │      22 │
└─────────────────────┴─────────┘
```

**Comment by den-crane** [comment]
Aliases in CH can be introduces anywhere

```sql
SELECT
    toStartOfDay(toDateTime(event_time)) AS event_time,
    count(1),
    xxxxxx
FROM system.query_log
GROUP BY
    toStartOfDay(toDateTime(query_log.event_time) AS xxxxxx),
    xxxxxx

Query id: 33d9944d-5639-4630-a133-848bbfbea75c

┌──────────event_time─┬─count()─┬──────────────xxxxxx─┐
│ 2022-09-15 00:00:00 │       2 │ 2022-09-15 15:03:37 │
│ 2022-09-14 00:00:00 │       1 │ 2022-09-14 22:02:59 │
│ 2022-09-15 00:00:00 │       1 │ 2022-09-15 18:50:34 │
│ 2022-09-14 00:00:00 │       2 │ 2022-09-14 22:21:18 │
│ 2022-09-14 00:00:00 │       2 │ 2022-09-14 22:28:16 │
│ 2022-09-14 00:00:00 │       2 │ 2022-09-14 21:59:14 │
```
