### ISSUE TITLE
Metadata loss in `DiskObjectStorageMetadata`

### ISSUE THREAD

**Issue by tavplubix** [ClickHouse/ClickHouse#41409]
After server restart it appeared that S3 metadata file is empty, but it's not clear why
https://pastila.nl/?00ec9776/82db3efc07df710b53b4633027248fb6

https://s3.amazonaws.com/clickhouse-test-reports/41379/8301f5758b8831dac047c1d080566c52dc24390c/stress_test__debug_.html

**Comment by alexey-milovidov** [comment]
WTF
