### ISSUE TITLE
CH version 22.8.4.7 Invalid number of rows in Chunk column Int64 position 0

### ISSUE THREAD

**Issue by WillMeng** [ClickHouse/ClickHouse#41404]
**Table schema**
`
-- pub_summary_db_sem_haosou.pub_setting_sem_keyword definition

CREATE TABLE pub_summary_db_sem_haosou.pub_setting_sem_keyword
(

    `publisher_id` Int32,

    `price` Float64,

    `wap_price_guide` Float64,

    `channel_id` Int32,

    `wmatch_prefer` Int32,

    `wap_reason` Int32,

    `chan_pub_id` Int64,

    `wap_business_relationship` Int32,

    `pub_campaign_id` Int64,

    `wap_landpage_experience` Int32,

    `status` Int32,

    `pc_quality` Int32,

    `pub_keyword_id` Int64,

    `pub_adgroup_name` String,

    `delete_time` Nullable(DateTime),

    `wap_destination_url` String,

    `match_type` Int32,

    `pc_reason` Int32,

    `wap_reliable` Int32,

    `tabs` String,

    `wap_estimated_click_rate` Int32,

    `pc_estimated_click_rate` Int32,

    `phrase_type` Int32,

    `pc_reliable` Int32,

    `pause` Int32,

    `wap_quality` Int32,

    `pub_keyword` String,

    `pub_account_name` String,

    `pub_account_id` Int64,

    `pc_left3_price_guide` Float64,

    `pc_landpage_experience` Int32,

    `pub_campaign_name` String,

    `pub_adgroup_id` Int64,

    `keyword_length` Int32,

    `pc_left_price_guide` Float64,

    `pc_business_relationship` Int32,

    `pc_destination_url` String,

    `deeplink_url` String
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/pub_summary_db_sem_haosou/new_keyword_6eab1486344611ed928dfa163e676c73_20220915015242',
 '{replica}')
PRIMARY KEY (chan_pub_id,
 pub_campaign_id,
 pub_adgroup_id,
 pub_keyword_id)
ORDER BY (chan_pub_id,
 pub_campaign_id,
 pub_adgroup_id,
 pub_keyword_id)
SETTINGS index_granularity = 8192;
`

**Query**
`
SELECT
    chan_pub_id,
    count() AS c_number
FROM pub_summary_db_sem_haosou.pub_setting_sem_keyword
WHERE status = 4900
GROUP BY chan_pub_id
HAVING c_number > 10000000
ORDER BY c_number DESC

2022.09.16 17:52:02.922436 [ 2833 ] {df1a1cf9-6203-415f-a041-137806e67017} <Error> executeQuery: Code: 49. DB::Exception: Invalid number of rows in Chunk column Int64 position 0: expected 65505, got 5304: While executing MergeTreeThread. (LOGICAL_ERROR) (version 22.8.4.7 (official build)) (from 10.252.4.8:53837) (in query: select chan_pub_id, count() as c_number from pub_summary_db_sem_haosou.pub_setting_sem_keyword where status = 4900 group by chan_pub_id having c_number > 10000000 order by c_number desc LIMIT 0, 200 FORMAT TabSeparatedWithNamesAndTypes;), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa3c367a in /usr/bin/clickhouse
1. DB::Chunk::checkNumRowsIsConsistent() @ 0x15bd044e in /usr/bin/clickhouse
2. DB::MergeTreeBaseSelectProcessor::generate() @ 0x15f5cba0 in /usr/bin/clickhouse
3. DB::ISource::tryGenerate() @ 0x15be2915 in /usr/bin/clickhouse
4. DB::ISource::work() @ 0x15be2466 in /usr/bin/clickhouse
5. DB::ExecutionThreadContext::executeTask() @ 0x15bfeeea in /usr/bin/clickhouse
6. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x15bf345b in /usr/bin/clickhouse
7. ? @ 0x15bf5cf9 in /usr/bin/clickhouse
8. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa485048 in /usr/bin/clickhouse
9. ? @ 0xa48825d in /usr/bin/clickhouse
10. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
11. clone @ 0xfeb0d in /usr/lib64/libc-2.17.so
`

**We changed sql to** 
`
SELECT
    chan_pub_id,
    count() AS c_number
FROM pub_summary_db_sem_haosou.pub_setting_sem_keyword
WHERE status = '4900'
GROUP BY chan_pub_id
HAVING c_number > 10000000
ORDER BY c_number DESC

It works well
`

**Comment by WillMeng** [comment]
And we downgrade 22.3, it works well

**Comment by davenger** [comment]
From issue #41399 it looks like lightweight delete functinality was used with the table. If so, this might be related or the same issue as in #40651

**Comment by davenger** [comment]
@WillMeng this release https://github.com/ClickHouse/ClickHouse/releases/tag/v22.8.12.45-lts includes the fix for 'Invalid number of rows in Chunk' bug https://github.com/ClickHouse/ClickHouse/pull/42126
Could you please try this release to see if the issue is fixed for you?
