### ISSUE TITLE
Duplicate accept request on self-signed server certificate

### ISSUE THREAD

**Issue by yakov-olkhovskiy** [ClickHouse/ClickHouse#41416]
**Describe the unexpected behaviour**
On connection with server having self-signed certificate warning message and acceptance request issued twice.

**How to reproduce**
Provide server with self-signed certificate and make a secure connection.

**Expected behavior**
Only one warning message and acceptance request should be issued.

**Error message and/or stacktrace**
```
ubuntu@ip-172-31-42-195:~/ClickHouse-comb/build_debug/programs$ ./clickhouse-client -s --port 9541
ClickHouse client version 22.9.1.1.
Connecting to localhost:9541 as user default.

WARNING: Certificate verification failed
----------------------------------------
Issuer Name:  /CN=another
Subject Name: /CN=another

The certificate yielded the error: self signed certificate

The error occurred in the certificate chain at position 0
Accept the certificate (y,n)? y
Connected to ClickHouse server version 22.9.1 revision 54460.

Warnings:
 * Server was built in debug mode. It will work slowly.

ip-172-31-42-195.us-east-2.compute.internal :)
WARNING: Certificate verification failed
----------------------------------------
Issuer Name:  /CN=another
Subject Name: /CN=another

The certificate yielded the error: self signed certificate

The error occurred in the certificate chain at position 0
Accept the certificate (y,n)?
```

**Comment by alexey-milovidov** [comment]
It is not supposed to work at all.

A prompt in the terminal is just an unwanted side effect from the SSL library.
We did not order it and we don't need it.

**Comment by yakov-olkhovskiy** [comment]
> It is not supposed to work at all.

you mean it should exit with error? I actually think the correct behavior is to allow to work with some command line switch and provide just a warning.

**Comment by alexey-milovidov** [comment]
> allow to work with some command line switch and provide just a warning

Yes, this will be ok.

> you mean it should exit with error?

No, I just mean that this dialog is not something we expected.
