### ISSUE TITLE
max_suspicious_broken_parts = 10 (default) is too low

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#41423]
We often see complaints about startup issue `Suspiciously many (12 parts, 0.00 B in total) broken parts to remove while maximum allowed broken parts count is 10` and in 100% cases it's because of and unexpected restart and files with 0 size or parts without half of files. The maximum number that I saw in public chats or from Altinity clients is 70 broken parts.

(it seems the modern hardware (ssd) + arbitrary partitioning allow to create a more parts per second than it was in 2016 when  max_suspicious_broken_parts = 10 was good enough)

Personally I set max_suspicious_broken_parts = 100.

So my proposal is to increase the default to 100 or at least to 50.

**Comment by UnamedRus** [comment]
I think, it's happens quite often with really small test/tmp tables.

May be we should have another threshold about size in bytes for broken parts?

**Comment by den-crane** [comment]
@UnamedRus 

```
SELECT *
FROM system.merge_tree_settings
WHERE name LIKE '%max_suspicious_broken_parts%'

┌─name──────────────────────────────┬─value──────┬─changed─┬─description──────────────────────────────────────────────────────┬─type───┐
│ max_suspicious_broken_parts       │ 10         │       0 │ Max broken parts, if more - deny automatic deletion.             │ UInt64 │
│ max_suspicious_broken_parts_bytes │ 1073741824 │       0 │ Max size of all broken parts, if more - deny automatic deletion. │ UInt64 │
└───────────────────────────────────┴────────────┴─────────┴──────────────────────────────────────────────────────────────────┴────────┘
```

I think the issue you thinking happens because of replicated_max_ratio_of_wrong_parts

```
SELECT *
FROM system.merge_tree_settings
WHERE name LIKE '%replicated_max_ratio_of_wrong_parts%'

Query id: 215bcb38-91e2-49d2-a0f1-f3a7a78961ca

┌─name────────────────────────────────┬─value─┬─changed─┬─description──────────────────────────────────────────────────────────────────────────┬─type──┐
│ replicated_max_ratio_of_wrong_parts │ 0.5   │       0 │ If ratio of wrong parts to total number of parts is less than this - allow to start. │ Float │
└─────────────────────────────────────┴───────┴─────────┴──────────────────────────────────────────────────────────────────────────────────────┴───────┘
```
