### ISSUE TITLE
Fix JIT for GROUP BY wtihout keys

### ISSUE THREAD

**Issue by azat** [ClickHouse/ClickHouse#41461]
Right now the server will crash, so the code disables it:
- https://github.com/ClickHouse/ClickHouse/blob/76aaecf1aa096d22b7d35f65a4c6cb2e0525e254/src/Interpreters/Aggregator.cpp#L1433-L1440 (added by @kitaisreal in #27574)
- https://github.com/ClickHouse/ClickHouse/blob/76aaecf1aa096d22b7d35f65a4c6cb2e0525e254/src/Interpreters/JIT/compileFunction.cpp#L742-L745 (added by @azat in #41046, for details please see https://github.com/ClickHouse/ClickHouse/pull/41046/commits/ba4174402a47512c298e4f3f7804cc772f2802a6)

**Comment by alexey-milovidov** [comment]
It is being added in this PR: https://github.com/ClickHouse/ClickHouse/pull/27611

**Comment by alexey-milovidov** [comment]
The PR is unfinished.
