### ISSUE TITLE
MergeMutateRuntimeQueue  (MEMORY_LIMIT_EXCEEDED)

### ISSUE THREAD

**Issue by jinusean** [ClickHouse/ClickHouse#41465]
Every day I am getting this error and the only way to solve it is to restart clickhouse. 
Can somebody please help me fix this?
```
<Empty trace>
 (version 22.7.2.1)
2022.09.18 19:12:45.017107 [ 10933200 ] {} <Error> void DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::routine(DB::TaskRuntimeDataPtr) [Queue = DB::MergeMutateRuntimeQueue]: Code: 241. DB::Exception: Memory limit (total) exceeded: would use 20.83 GiB (attempt to allocate chunk of 5219637 bytes), maximum: 12.80 GiB. OvercommitTracker decision: Memory overcommit isn't used. Waiting time or orvercommit denominator are set to zero.. (MEMORY_LIMIT_EXCEEDED), Stack trace (when copying this message, always include the lines below):
```

**Comment by ilya-zlobintsev** [comment]
Related issue: #41465

**Comment by nikitamikhaylov** [comment]
This is Ok. Try to tune `merge_max_block_size_bytes` / `merge_max_block_size` or relax the conditions for vertical merge e.g.: 
- `vertical_merge_algorithm_min_rows_to_activate`
- `vertical_merge_algorithm_min_bytes_to_activate`
- `vertical_merge_algorithm_min_columns_to_activate`

Sometimes ClickHouse needs a lot of memory for merging, especially for big tables with big number of columns. However, the situation was improved in recent versions, so try to upgrade.
