### ISSUE TITLE
Расширение функциональности topK

### ISSUE THREAD

**Issue by MakarovYaroslav** [ClickHouse/ClickHouse#4147]
Хотелось бы, чтобы агрегатная функция topK умела возвращать не только топ по частоте встречаемости, но и, например, по сумме какого-либо числового поля.
Например, есть колонка URL и колонка bytes_sum.
Вызвать topK(10)(URL, bytes_sum) и получить 10 URL, по которым больше всего суммарное количество байт.

Кроме этого, возможно ли возвращать еще и это суммарное количество? Например, в формате, похожем на выдачу sumMap.
Все равно эти значения подсчитываются для формирования топа,

В этом случае, может быть, объединить две вышеуказанные функциональности в отдельную функцию?

**Comment by alexey-milovidov** [comment]
First part: #4245
