### ISSUE TITLE
21.9+: Illegal column Nullable(FixedString(32)) of first argument of function toString

### ISSUE THREAD

**Issue by Slach** [ClickHouse/ClickHouse#41490]
**Describe what's wrong**

```sql
SELECT toTypeName(s), toString(s) FROM
(
 SELECT toFixedString('',32) AS s 
 UNION ALL
 SELECT null AS s 
)
```

this query works in all versions from 19.17 to 21.8, but stop works after 21.9+ 

https://fiddle.clickhouse.com/7bd65b36-a6e6-470a-8bdc-4c98a33ff453
21.8 works

https://fiddle.clickhouse.com/9e40a424-4027-4c7f-bd41-b20935ae9129
21.9 doesn't work
```
Received exception from server (version 21.9.6):
Code: 44. DB::Exception: Received from localhost:9000. DB::Exception: Illegal column Nullable(FixedString(32)) of first argument of function toString. (ILLEGAL_COLUMN)
```

this query works in all versions

```sql
SELECT toTypeName(s), toString(s) FROM
(
 SELECT '' AS s 
 UNION ALL
 SELECT null AS s 
)
```
https://fiddle.clickhouse.com/4f810f03-1644-4eb7-b696-0341b1bbdbc4

**Does it reproduce on recent release?**
Yes, reproduce in all releases 21.9+

**Comment by filimonov** [comment]
Simpler test:

```sql
SELECT CAST('a', 'Nullable(FixedString(1))') as s,  toTypeName(s), toString(s);
```

**Comment by canhld94** [comment]
@filimonov probably related #26123
There's some logic looks very suspicious in `FunctionsConvertion`
```cpp
bool useDefaultImplementationForNulls() const override
{
    bool to_nullable_string = to_nullable && std::is_same_v<ToDataType, DataTypeString>;
    return checked_return_type && !to_nullable_string;
}
```
