### ISSUE TITLE
metric_log / asynchronous_metric_log and slowly starting server = Too many parts.

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#41527]
### scenario:

server start time is more than 60 minutes (a lot of tables & parts).

During that Too many parts from metric_log is triggered. 

```
DB::SystemLog<DB::MetricLogElement>::flushImpl ... Too many parts
```

![image](https://user-images.githubusercontent.com/1549571/191024830-d0cee7f4-6e46-40d7-801c-61465dbed5c6.png)

### Reason: 

- since 21.8 the system.metric_log & system.asynchronous_metric_log are enabled by default
-  during server startup & while the tables are loading the metrics are collected.
- merges are not happening while the tables are loading
- system.asynchronous_metric_log is flushed (with default config) every 7 seconds, 7*300 = after 2100 seconds it will do 300 flushes/inserts (and no merges)  - enough to start triggering 'Too many parts' 
- system.metric_log is flushed (with default config) every 7.5 seconds, 7*300 = after 2250 seconds it will do 300 flushes - enough to start triggering 'Too many parts' 

https://github.com/ClickHouse/ClickHouse/blob/5802c2fdd2e619317de45051fe39300556899401/programs/server/config.xml#L1113

### Workarounds:

1) just ignore it, you will have some events missing in `system.metric_log` / `system.asynchronous_metric_log` tables

2) relax the limits - for example, 1000 will allow collecting parts for 2 hours without merges happening

```xml
<!-- /etc/clickhouse-server/config.d/logs_tables.xml -->
<clickhouse>
  <asynchronous_metric_log replace="1">
   <database>system</database>
   <table>asynchronous_metric_log</table>
   <flush_interval_milliseconds>30000</flush_interval_milliseconds>
   <engine>
ENGINE = MergeTree
PARTITION BY event_date
ORDER BY (event_time)
TTL event_date + interval 90 day
SETTINGS ttl_only_drop_parts=1, parts_to_delay_insert=800, parts_to_throw_insert=1000
    </engine>
  </asynchronous_metric_log>

  <metric_log replace="1">
    <database>system</database>
    <table>metric_log</table>
    <flush_interval_milliseconds>7500</flush_interval_milliseconds>
    <collect_interval_milliseconds>1000</collect_interval_milliseconds>
    <engine>
ENGINE = MergeTree
PARTITION BY event_date
ORDER BY (event_time)
TTL event_date + interval 90 day
SETTINGS ttl_only_drop_parts=1, parts_to_delay_insert=800, parts_to_throw_insert=1000
    </engine>
  </metric_log>
</clickhouse>
```

3) disable metric_log / asynchronous_metric_log completely (of course if you have other reliable monitoring tools). 

```xml
<!-- /etc/clickhouse-server/config.d/disable_metric_logs.xml -->
<clickhouse>
    <metric_log remove="1" />
    <asynchronous_metric_log remove="1" />
</clickhouse>
```

**Comment by alexey-milovidov** [comment]
> just ignore it, you will have some events missing in system.metric_log / system.asynchronous_metric_log tables

This is ok for me.
