### ISSUE TITLE
How to copy table effectively in the single instance ClickHouse server

### ISSUE THREAD

**Issue by srikanthccv** [ClickHouse/ClickHouse#41536]
Hello 👋 ,

Prescript - I have read about the `clickhouse-copier` tool but that doesn't seem like tool that I can use in this case.

I have a table in the ClickHouse server with a table of 600M rows and sizes of `6.86 GiB` and `265.12 GiB`. I am trying to make a copy of this table with a different primary key but the `INSERT ... SELECT` variant of copying data quickly runs into a memory limit exceeded problem. How can I copy the table into the same server instance without this problem? The machine has 32 CPUs and 64 GB of RAM.

I have a map column which is of type `Map(LowCardinality(String), LowCardinality(String)) CODEC(LZ4)` and there is an index on it with `mapKeys` and `mapValues` to enable the skip indexes. Following is the error message.

```
Code: 241. DB::Exception: Received from localhost:9000. DB::Exception: Memory limit (for query) exceeded: would use 51.26 GiB (attempt to allocate chunk of 4294967360 bytes), maximum: 51.22 GiB: while executing 'FUNCTION mapKeys(labels : 2) -> mapKeys(labels) Array(String) : 3'. (MEMORY_LIMIT_EXCEEDED)
```

**Comment by UnamedRus** [comment]
Related issue: https://github.com/ClickHouse/ClickHouse/issues/41537

**Comment by UnamedRus** [comment]
> How can I copy the table into the same server instance without this problem? 

How many columns do you have in table?

Probable the most easiest way is to copy your table by partitions for now.

**Comment by srikanthccv** [comment]
The number of columns I have is just 6 but one of the columns uses the map to store the JSON-like data which is relatively big.

**Comment by srikanthccv** [comment]
>How many elements in average map?

The number of elements can range from 50 - 180.

>Can you show exact error message?

Updated the description
```
Code: 241. DB::Exception: Received from localhost:9000. DB::Exception: Memory limit (for query) exceeded: would use 51.26 GiB (attempt to allocate chunk of 4294967360 bytes), maximum: 51.22 GiB: while executing 'FUNCTION mapKeys(labels : 2) -> mapKeys(labels) Array(String) : 3'. (MEMORY_LIMIT_EXCEEDED)
```

> you can use LowCardinality

Yes, I am using it already.

**Comment by DerekChia** [comment]
As @UnamedRus suggests, you can try to copy your table by partition using the `ATTACH PARTITION FROM` command. More details here - https://clickhouse.com/docs/en/sql-reference/statements/alter/partition/#attach-partition-from

**Comment by DerekChia** [comment]
To avoid the memory error, you can also reduce your [`max_threads`](https://clickhouse.com/docs/en/operations/settings/settings/#settings-max_threads) to 1 and [`min_insert_block_size_rows`](https://clickhouse.com/docs/en/operations/settings/settings/#min-insert-block-size-rows) to 1024 for this `INSERT ... SELECT` query
