### ISSUE TITLE
clickhouse crash LZ4_compress_fast_extState

### ISSUE THREAD

**Issue by Cherry-Puppy** [ClickHouse/ClickHouse#41545]
####### Below is the log

2022.09.20 08:54:43.699105 [ 14928 ] {} <Fatal> BaseDaemon: ########################################
2022.09.20 08:54:43.699170 [ 14928 ] {} <Fatal> BaseDaemon: (version 21.8.12.1, build id: 995BD17632A0B5217A0062976FD485521F0169AD) (from thread 12698) (query_id: daf3556a-4552-4886-8705-17db8c013789) Received signal Segmentation fault (11)
2022.09.20 08:54:43.699221 [ 14928 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
2022.09.20 08:54:43.699246 [ 14928 ] {} <Fatal> BaseDaemon: Stack trace: 0x103278dc 0x1032d05f 0xb05d192 0xb056752 0xbabebca 0xbb5fa57 0xba756ed 0x4550e2b 0x45506cf 0x7f62a13b9e25 0x7f62a0cda35d
2022.09.20 08:54:43.699341 [ 14928 ] {} <Fatal> BaseDaemon: 3. LZ4_compress_fast_extState @ 0x103278dc in /usr/bin/clickhouse
2022.09.20 08:54:43.699365 [ 14928 ] {} <Fatal> BaseDaemon: 4. LZ4_compress_fast @ 0x1032d05f in /usr/bin/clickhouse
2022.09.20 08:54:43.699433 [ 14928 ] {} <Fatal> BaseDaemon: 5. DB::ICompressionCodec::compress(char const*, unsigned int, char*) const @ 0xb05d192 in /usr/bin/clickhouse
2022.09.20 08:54:43.699492 [ 14928 ] {} <Fatal> BaseDaemon: 6. DB::CompressedWriteBuffer::nextImpl() @ 0xb056752 in /usr/bin/clickhouse
2022.09.20 08:54:43.699527 [ 14928 ] {} <Fatal> BaseDaemon: 7. DB::IOutputFormat::flush() @ 0xbabebca in /usr/bin/clickhouse
2022.09.20 08:54:43.699589 [ 14928 ] {} <Fatal> BaseDaemon: 8. DB::ParallelFormattingOutputFormat::collectorThreadFunction(std::__1::shared_ptr<DB::ThreadGroupStatus> const&) @ 0xbb5fa57 in /usr/bin/clickhouse
2022.09.20 08:54:43.699649 [ 14928 ] {} <Fatal> BaseDaemon: 9. ThreadFromGlobalPool::ThreadFromGlobalPool<DB::ParallelFormattingOutputFormat::ParallelFormattingOutputFormat(DB::ParallelFormattingOutputFormat::Params)::'lambda'()>(DB::ParallelFormattingOutputFormat::ParallelFormattingOutputFormat(DB::ParallelFormattingOutputFormat::Params)::'lambda'()&&)::'lambda'()::operator()() @ 0xba756ed in /usr/bin/clickhouse
2022.09.20 08:54:43.699722 [ 14928 ] {} <Fatal> BaseDaemon: 10. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x4550e2b in /usr/bin/clickhouse
2022.09.20 08:54:43.699738 [ 14928 ] {} <Fatal> BaseDaemon: 11. ? @ 0x45506cf in /usr/bin/clickhouse
2022.09.20 08:54:43.700449 [ 14928 ] {} <Fatal> BaseDaemon: 12. start_thread @ 0x7e25 in /usr/lib64/libpthread-2.17.so
2022.09.20 08:54:43.700503 [ 14928 ] {} <Fatal> BaseDaemon: 13. clone @ 0xf835d in /usr/lib64/libc-2.17.so
2022.09.20 08:54:43.946563 [ 14928 ] {} <Fatal> BaseDaemon: Calculated checksum of the binary: 7C9F819508B83413774979D1E4856697. There is no information about the reference checksum.
2022.09.20 08:54:45.867051 [ 431718 ] {} <Fatal> Application: Child process was terminated by signal 11.

**Comment by Cherry-Puppy** [comment]
Occasionally

**Comment by Cherry-Puppy** [comment]
anyone there?

**Comment by DerekChia** [comment]
Would you consider upgrading to a stable or LTS release? There are a few updates on LZ4 since then. See changelog [2022](https://clickhouse.com/docs/en/whats-new/changelog/) and [2021](https://clickhouse.com/docs/en/whats-new/changelog/2021/).

**Comment by Cherry-Puppy** [comment]
> Would you consider upgrading to a stable or LTS release? There are a few updates on LZ4 since then. See changelog [2022](https://clickhouse.com/docs/en/whats-new/changelog/) and [2021](https://clickhouse.com/docs/en/whats-new/changelog/2021/).

Hi, is there any way to avoid it?

**Comment by den-crane** [comment]
>version 21.8.12.1, build id: 995BD17632A0B5217A0062976FD485521F0169AD

@Cherry-Puppy As I understand you build CH by yourself.
1. 21.8 is obsolete.
2. we don't support alternative builds.
