### ISSUE TITLE
Flaky test_hive_query/test.py::test_text_count

### ISSUE THREAD

**Issue by vdimir** [ClickHouse/ClickHouse#41547]
Failing in master last three days
[play ci](https://play.clickhouse.com/play?user=play#CiAgICBTRUxFQ1QKICAgICAgICBjaGVja19uYW1lLAogICAgICAgIGdyb3VwQXJyYXlEaXN0aW5jdCh0ZXN0X25hbWUpLAogICAgICAgIHRvU3RhcnRPZkRheShjaGVja19zdGFydF90aW1lKSwKICAgICAgICBjb3VudCgpCiAgICBGUk9NIGNoZWNrcwogICAgV0hFUkUgdGVzdF9zdGF0dXMgbm90IGluICgnT0snLCAnU0tJUFBFRCcpCiAgICAgICAgQU5EIHRlc3RfbmFtZSBpbGlrZSAnJXRlc3RfaGl2ZV9xdWVyeSUnCiAgICAgICAgQU5EIG5vdygpIC0gSU5URVJWQUwgJzEwJyBkYXkgPD0gY2hlY2tfc3RhcnRfdGltZQogICAgICAgIEFORCBwdWxsX3JlcXVlc3RfbnVtYmVyID09IDAKICAgIEdST1VQIEJZIGNoZWNrX25hbWUsIHRvU3RhcnRPZkRheShjaGVja19zdGFydF90aW1lKSAgIAogICAgT1JERVIgQlkKICAgICAgICB0b1N0YXJ0T2ZEYXkoY2hlY2tfc3RhcnRfdGltZSkgREVTQwogICAgTElNSVQgMjAKCg==)

**Comment by azat** [comment]
Will close then, since I don't see failures for 2022-09-20 for this test in `checks`
