### ISSUE TITLE
Logical error: EphemeralLock is not created

### ISSUE THREAD

**Issue by Cherry-Puppy** [ClickHouse/ClickHouse#41571]
--------The log is as follows

2022.09.20 21:08:31.191386 [ 699800 ] {dc773ea0-31e3-4461-8ace-41fa94bc8899} <Error> executeQuery: Code: 49, e.displayText() = DB::Exception: EphemeralLock is not created (version 21.8.12.29) (from 192.168.12.145:11741) (in query: INSERT INTO

---------zookeeper lost lock

**Comment by tavplubix** [comment]
Please share `zgrep -A30 -Fa "dc773ea0-31e3-4461-8ace-41fa94bc8899" /var/log/clickhouse-server/*`

Also version 21.8 is obsolete and not supported, please upgrade to newer version

**Comment by Cherry-Puppy** [comment]
> 

2022.09.27 15:40:29.407223 [ 935399 ] {9bbc1560-1072-4094-993c-1f773fbcb449} <Error> executeQuery: Code: 49, e.displayText() = DB::Exception: EphemeralLock is not created (version 21.8.12.29) (from 192.168.12.146:29526) (in query: INSERT INTO `table_name`(`dt`, `md5`, `fee_id`, `re_id`, `user_id`, `name`, `type`, `content`, `original`, `images`, `attaches`, `videos`, `create_time`) FORMAT TabSeparated ), Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xeb0f70d in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x44efc7a in /usr/bin/clickhouse
2. ? @ 0x3f61843 in /usr/bin/clickhouse
3. DB::ReplicatedMergeTreeBlockOutputStream::write(DB::Block const&) @ 0xb95577d in /usr/bin/clickhouse
4. DB::PushingToViewsBlockOutputStream::write(DB::Block const&) @ 0xbdb33d6 in /usr/bin/clickhouse
5. DB::AddingDefaultBlockOutputStream::write(DB::Block const&) @ 0xbd9a4a8 in /usr/bin/clickhouse
6. DB::SquashingBlockOutputStream::finalize() @ 0xbdb8580 in /usr/bin/clickhouse
7. DB::SquashingBlockOutputStream::writeSuffix() @ 0xbdb8689 in /usr/bin/clickhouse
8. DB::NullAndDoCopyBlockInputStream::readImpl() @ 0xb2d549d in /usr/bin/clickhouse
9. DB::IBlockInputStream::read() @ 0xb06f02b in /usr/bin/clickhouse
10. void DB::copyDataImpl<std::__1::function<bool ()> const&, std::__1::function<void (DB::Block const&)> const&>(DB::IBlockInputStream&, DB::IBlockOutputStream&, std::__1::function<bool ()> const&, std::__1::function<void (DB::Block const&)> const&) @ 0xb0914c3 in /usr/bin/clickhouse
11. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::__1::shared_ptr<DB::Context>, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>, std::__1::optional<DB::FormatSettings> const&) @ 0xb443d7d in /usr/bin/clickhouse
12. DB::HTTPHandler::processQuery(std::__1::shared_ptr<DB::Context>, DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::__1::optional<DB::CurrentThread::QueryScope>&) @ 0xc2e4afd in /usr/bin/clickhouse
13. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0xc2e8a79 in /usr/bin/clickhouse
14. DB::HTTPServerConnection::run() @ 0xc30219f in /usr/bin/clickhouse
15. Poco::Net::TCPServerConnection::start() @ 0xea6e6c7 in /usr/bin/clickhouse
16. Poco::Net::TCPServerDispatcher::run() @ 0xea6ecda in /usr/bin/clickhouse
17. Poco::PooledThread::run() @ 0xeb79efe in /usr/bin/clickhouse
18. Poco::ThreadImpl::runnableEntry(void*) @ 0xeb77449 in /usr/bin/clickhouse
19. start_thread @ 0x7e25 in /usr/lib64/libpthread-2.17.so
20. clone @ 0xf835d in /usr/lib64/libc-2.17.so

**Comment by Cherry-Puppy** [comment]
Are there workarounds and solutions？？？

**Comment by Cherry-Puppy** [comment]
> First of all you should upgrade to supported version.
> 
> Also more information is needed. Did it happen only once? Or is it always reproducible? If so, then how to reproduce it? What else the query logged? (`zgrep -Fa "dc773ea0-31e3-4461-8ace-41fa94bc8899" /var/log/clickhouse-server/*`, other messages from this query are also useful)

   displayText() = DB::Exception: EphemeralLock is not created (version 21.8.12.29) (from 192.168.12.146:29526) (in query: INSERT INTO `table_name`(`dt`, `md5`, `feedback_id`, `reply_id`, `user_id`, `user_name`, `type`, `content`, `original_content`, `images`, `attaches`, `videos`, `create_time`) FORMAT TabSeparated ), Stack trace (when copying this message, always include the lines below):
/data/clickhouse/clickhouse-server/logs/clickhouse-server.err.log.1.gz:2022.09.27 15:40:29.407483 [ 935399 ] {9bbc1560-1072-4094-993c-1f773fbcb449} <Error> DynamicQueryHandler: Code: 49, e.displayText() = DB::Exception: EphemeralLock is not created, Stack trace (when copying this message, always include the lines below):

**Comment by Cherry-Puppy** [comment]
> > First of all you should upgrade to supported version.
> > Also more information is needed. Did it happen only once? Or is it always reproducible? If so, then how to reproduce it? What else the query logged? (`zgrep -Fa "dc773ea0-31e3-4461-8ace-41fa94bc8899" /var/log/clickhouse-server/*`, other messages from this query are also useful)
> 
> displayText() = DB::Exception: EphemeralLock is not created (version 21.8.12.29) (from 192.168.12.146:29526) (in query: INSERT INTO `table_name`(`dt`, `md5`, `feedback_id`, `reply_id`, `user_id`, `user_name`, `type`, `content`, `original_content`, `images`, `attaches`, `videos`, `create_time`) FORMAT TabSeparated ), Stack trace (when copying this message, always include the lines below): /data/clickhouse/clickhouse-server/logs/clickhouse-server.err.log.1.gz:2022.09.27 15:40:29.407483 [ 935399 ] {9bbc1560-1072-4094-993c-1f773fbcb449} DynamicQueryHandler: Code: 49, e.displayText() = DB::Exception: EphemeralLock is not created, Stack trace (when copying this message, always include the lines below):

/data/clickhouse/clickhouse-server/logs/clickhouse-server.err.log.1.gz:2022.09.27 15:40:29.407223 [ 935399 ] {9bbc1560-1072-4094-993c-1f773fbcb449} <Error> executeQuery: Code: 49, e.displayText() = DB::Exception: EphemeralLock is not created (version 21.8.12.29) (from 192.168.12.146:29526) (in query: INSERT INTO `t_gy_feedback_reply`(`dt`, `md5`, `feedback_id`, `reply_id`, `user_id`, `user_name`, `type`, `content`, `original_content`, `images`, `attaches`, `videos`, `create_time`) FORMAT TabSeparated ), Stack trace (when copying this message, always include the lines below):
/data/clickhouse/clickhouse-server/logs/clickhouse-server.err.log.1.gz:2022.09.27 15:40:29.407483 [ 935399 ] {9bbc1560-1072-4094-993c-1f773fbcb449} <Error> DynamicQueryHandler: Code: 49, e.displayText() = DB::Exception: EphemeralLock is not created, Stack trace (when copying this message, always include the lines below):
/data/clickhouse/clickhouse-server/logs/clickhouse-server.log.2.gz:2022.09.27 15:40:29.404617 [ 935399 ] {9bbc1560-1072-4094-993c-1f773fbcb449} <Debug> executeQuery: (from 192.168.12.146:29526, user: ianqu) INSERT INTO `table_name`(`dt`, `md5`, `feedback_id`, `reply_id`, `user_id`, `user_name`, `type`, `content`, `original_content`, `images`, `attaches`, `videos`, `create_time`) FORMAT TabSeparated 
/data/clickhouse/clickhouse-server/logs/clickhouse-server.log.2.gz:2022.09.27 15:40:29.404722 [ 935399 ] {9bbc1560-1072-4094-993c-1f773fbcb449} <Trace> ContextAccess (ianqu): Access granted: INSERT(dt, md5, feedback_id, reply_id, user_id, user_name, type, content, original_content, images, attaches, videos, create_time) ON gy_open_ch_bi.t_gy_feedback_reply
/data/clickhouse/clickhouse-server/logs/clickhouse-server.log.2.gz:2022.09.27 15:40:29.404827 [ 935399 ] {9bbc1560-1072-4094-993c-1f773fbcb449} <Trace> ParallelParsingInputFormat: Parallel parsing is used
/data/clickhouse/clickhouse-server/logs/clickhouse-server.log.2.gz:2022.09.27 15:40:29.404864 [ 935399 ] {9bbc1560-1072-4094-993c-1f773fbcb449} <Debug> executeQuery: Query pipeline:
/data/clickhouse/clickhouse-server/logs/clickhouse-server.log.2.gz:2022.09.27 15:40:29.404885 [ 935399 ] {9bbc1560-1072-4094-993c-1f773fbcb449} <Trace> ParallelFormattingOutputFormat: Parallel formatting is being used
/data/clickhouse/clickhouse-server/logs/clickhouse-server.log.2.gz:2022.09.27 15:40:29.405517 [ 935399 ] {9bbc1560-1072-4094-993c-1f773fbcb449} <Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 9.81 TiB.
/data/clickhouse/clickhouse-server/logs/clickhouse-server.log.2.gz:2022.09.27 15:40:29.406027 [ 935399 ] {9bbc1560-1072-4094-993c-1f773fbcb449} <Debug> db.table_name (Replicated OutputStream): Wrote block with ID '202209_885012217524877533_2454686918613507424', 4 rows
/data/clickhouse/clickhouse-server/logs/clickhouse-server.log.2.gz:2022.09.27 15:40:29.407223 [ 935399 ] {9bbc1560-1072-4094-993c-1f773fbcb449} <Error> executeQuery: Code: 49, e.displayText() = DB::Exception: EphemeralLock is not created (version 21.8.12.29) (from 192.168.12.146:29526) (in query: INSERT INTO `table_name`(`dt`, `md5`, `feedback_id`, `reply_id`, `user_id`, `user_name`, `type`, `content`, `original_content`, `images`, `attaches`, `videos`, `create_time`) FORMAT TabSeparated ), Stack trace (when copying this message, always include the lines below):
/data/clickhouse/clickhouse-server/logs/clickhouse-server.log.2.gz:2022.09.27 15:40:29.407483 [ 935399 ] {9bbc1560-1072-4094-993c-1f773fbcb449} <Error> DynamicQueryHandler: Code: 49, e.displayText() = DB::Exception: EphemeralLock is not created, Stack trace (when copying this message, always include the lines below):
/data/clickhouse/clickhouse-server/logs/clickhouse-server.log.2.gz:2022.09.27 15:40:29.407591 [ 935399 ] {9bbc1560-1072-4094-993c-1f773fbcb449} <Debug> MemoryTracker: Peak memory usage (for query): 12.09 MiB.

**Comment by Cherry-Puppy** [comment]
> First of all you should upgrade to supported version.
> 
> Also more information is needed. Did it happen only once? Or is it always reproducible? If so, then how to reproduce it? What else the query logged? (`zgrep -Fa "dc773ea0-31e3-4461-8ace-41fa94bc8899" /var/log/clickhouse-server/*`, other messages from this query are also useful)

/data/clickhouse/clickhouse-server/logs/clickhouse-server.err.log.1.gz:2022.09.27 15:40:29.407223 [ 935399 ] {9bbc1560-1072-4094-993c-1f773fbcb449} <Error> executeQuery: Code: 49, e.displayText() = DB::Exception: EphemeralLock is not created (version 21.8.12.29) (from 192.168.12.146:29526) (in query: INSERT INTO `table_name`(`dt`, `md5`, `feedback_id`, `reply_id`, `user_id`, `user_name`, `type`, `content`, `original_content`, `images`, `attaches`, `videos`, `create_time`) FORMAT TabSeparated ), Stack trace (when copying this message, always include the lines below):
/data/clickhouse/clickhouse-server/logs/clickhouse-server.err.log.1.gz:2022.09.27 15:40:29.407483 [ 935399 ] {9bbc1560-1072-4094-993c-1f773fbcb449} <Error> DynamicQueryHandler: Code: 49, e.displayText() = DB::Exception: EphemeralLock is not created, Stack trace (when copying this message, always include the lines below):
/data/clickhouse/clickhouse-server/logs/clickhouse-server.log.2.gz:2022.09.27 15:40:29.404617 [ 935399 ] {9bbc1560-1072-4094-993c-1f773fbcb449} <Debug> executeQuery: (from 192.168.12.146:29526, user: ianqu) INSERT INTO `table_name`(`dt`, `md5`, `feedback_id`, `reply_id`, `user_id`, `user_name`, `type`, `content`, `original_content`, `images`, `attaches`, `videos`, `create_time`) FORMAT TabSeparated 
/data/clickhouse/clickhouse-server/logs/clickhouse-server.log.2.gz:2022.09.27 15:40:29.404722 [ 935399 ] {9bbc1560-1072-4094-993c-1f773fbcb449} <Trace> ContextAccess (ianqu): Access granted: INSERT(dt, md5, feedback_id, reply_id, user_id, user_name, type, content, original_content, images, attaches, videos, create_time) ON gy_open_ch_bi.t_gy_feedback_reply
/data/clickhouse/clickhouse-server/logs/clickhouse-server.log.2.gz:2022.09.27 15:40:29.404827 [ 935399 ] {9bbc1560-1072-4094-993c-1f773fbcb449} <Trace> ParallelParsingInputFormat: Parallel parsing is used
/data/clickhouse/clickhouse-server/logs/clickhouse-server.log.2.gz:2022.09.27 15:40:29.404864 [ 935399 ] {9bbc1560-1072-4094-993c-1f773fbcb449} <Debug> executeQuery: Query pipeline:
/data/clickhouse/clickhouse-server/logs/clickhouse-server.log.2.gz:2022.09.27 15:40:29.404885 [ 935399 ] {9bbc1560-1072-4094-993c-1f773fbcb449} <Trace> ParallelFormattingOutputFormat: Parallel formatting is being used
/data/clickhouse/clickhouse-server/logs/clickhouse-server.log.2.gz:2022.09.27 15:40:29.405517 [ 935399 ] {9bbc1560-1072-4094-993c-1f773fbcb449} <Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 9.81 TiB.
/data/clickhouse/clickhouse-server/logs/clickhouse-server.log.2.gz:2022.09.27 15:40:29.406027 [ 935399 ] {9bbc1560-1072-4094-993c-1f773fbcb449} <Debug> db.table_name (Replicated OutputStream): Wrote block with ID '202209_885012217524877533_2454686918613507424', 4 rows
/data/clickhouse/clickhouse-server/logs/clickhouse-server.log.2.gz:2022.09.27 15:40:29.407223 [ 935399 ] {9bbc1560-1072-4094-993c-1f773fbcb449} <Error> executeQuery: Code: 49, e.displayText() = DB::Exception: EphemeralLock is not created (version 21.8.12.29) (from 192.168.12.146:29526) (in query: INSERT INTO `table_name`(`dt`, `md5`, `feedback_id`, `reply_id`, `user_id`, `user_name`, `type`, `content`, `original_content`, `images`, `attaches`, `videos`, `create_time`) FORMAT TabSeparated ), Stack trace (when copying this message, always include the lines below):
/data/clickhouse/clickhouse-server/logs/clickhouse-server.log.2.gz:2022.09.27 15:40:29.407483 [ 935399 ] {9bbc1560-1072-4094-993c-1f773fbcb449} <Error> DynamicQueryHandler: Code: 49, e.displayText() = DB::Exception: EphemeralLock is not created, Stack trace (when copying this message, always include the lines below):
/data/clickhouse/clickhouse-server/logs/clickhouse-server.log.2.gz:2022.09.27 15:40:29.407591 [ 935399 ] {9bbc1560-1072-4094-993c-1f773fbcb449} <Debug> MemoryTracker: Peak memory usage (for query): 12.09 MiB.

**Comment by tavplubix** [comment]
Please answer the remaining questions:
> Did it happen only once? Or is it always reproducible? If so, then how to reproduce it?

**Comment by Cherry-Puppy** [comment]
> Please answer the remaining questions:
> 
> > Did it happen only once? Or is it always reproducible? If so, then how to reproduce it?

It is now frequent

**Comment by alexey-milovidov** [comment]
Let's reopen if it's still relevant after upgrading.
