### ISSUE TITLE
Meet Memory limit (for query) exceeded issue when load data from one CSV file on S3

### ISSUE THREAD

**Issue by redinstorm** [ClickHouse/ClickHouse#41625]
We use the S3 function to load data from one CSV file which  is about 10GB on S3.  Our Cluster is 3 nodes and 3 replicated nodes with 8C24G and version is  21.7.7.47.
First, we create the local table like abc on each node and one distributed table all_abc and then use the S3 function to load data
insert into all_abc
select *
from S3('file_URL',CSV, '<column info>')
;

And we met the Meet Memory limit (for query) exceeded issue after the query run about 400s.  But the CSV is only 10GB.  
Do we have the formulation for calculate how much memory will be used with one CSV file?

PS:when we used one 3GB CSV file, the query worked fine.

**Comment by DerekChia** [comment]
How much memory do you have in your nodes? Did you change any of the memory settings in ClickHouse?

**Comment by redinstorm** [comment]
The memory is 24GB each node. We enlarged the memory limit in the XML to about 20GB.

**Comment by DerekChia** [comment]
Can you show the output of the following query? You should see a lot of information on your failed queries, including memory_usage, stack_trace, settings, etc. Remember to remove your S3 credentials before sharing here.

```
SELECT * FROM system.query_log 
WHERE type = 'ExceptionWhileProcessing' 
ORDER BY memory_usage 
DESC FORMAT Vertical
```
