### ISSUE TITLE
alter update behaviour depends on where (can fail with DB::Exception)

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#4165]
Create table sample (a Date, id String) engine=MergeTree order by tuple();
Insert into sample values('2019-01-02','1');

Alter table sample update  a='2019-02-20' where id = '1';
**DB::Exception: There is no supertype for types String, Date because some of them are String/FixedString and some of them are not**

Alter table sample update  a='2019-02-20' where 1
**Ok**

Alter table sample update  a=toDate('2019-02-20') where id = '1';
**Ok**

CH 18.14.18 - 19.1.6

**Comment by alexey-milovidov** [comment]
Details: 
`update a = x where cond` is translated to `update a = cond ? x : a`
Function if: `date ? '2019-01-01' : date` does not support conversion from constant string to date.

**Comment by filimonov** [comment]
Same #3746

**Comment by den-crane** [comment]
.

**Comment by silence44** [comment]
I also have same problem but with integers. Described more detailed at #2111
