### ISSUE TITLE
MultiIf clauses can have executable SQL ?

### ISSUE THREAD

**Issue by HeenaBansal2009** [ClickHouse/ClickHouse#41658]
Below SQL is throwing exception:
`SELECT multiIf((toTypeName(1546300899) = 'String') OR (toTypeName(1546300899) = 'UUID') OR (toTypeName(1546300899) = 'DateTime64(3)'), 'Only Accepted arguments are float , int and double',toDateTime64(1546300899, 9, 'UTC'))` 

outputs exception as below

`Code: 386. DB::Exception: There is no supertype for types String, DateTime64(9, 'UTC') because some of them are String/FixedString and some of them are not: While processing if(toTypeName(1546300899) IN ('DateTime64(3)', 'String', 'UUID'), 'Only Accepted arguments are float , int and double', toDateTime64(1546300899, 9, 'UTC')). (NO_COMMON_TYPE) (version 22.9.1.2440 (official build))

`
However , converting the else clause to toString works. 
`SELECT multiIf((toTypeName(1546300899) = 'String') OR (toTypeName(1546300899) = 'UUID') OR (toTypeName(1546300899) = 'DateTime64(3)'), 'Only Accepted arguments are float , int and double', toString(toDateTime64(1546300899, 9, 'UTC')))`

Does multiIf only accepts String return type on then values. If yes , is there any other alternative to achieve above intended sql operation.

Thanks in advance.

**Comment by UnamedRus** [comment]
> Does multiIf only accepts String return type on then values.

No

> If yes , is there any other alternative to achieve above intended sql operation.

Your multiIf clause in all branches should return the **same data type**, it's core reason of this exception:
One branch return String: 'Only Accepted arguments are float , int and double'
Second branch return DateTime: toDateTime64(1546300899, 9, 'UTC')
