### ISSUE TITLE
should the {shard} tag be defined in <clickhouse_remote_servers><my_cluster_name>...</></>

### ISSUE THREAD

**Issue by 2640304460** [ClickHouse/ClickHouse#41673]
For example:
      there are four nodes:  
       node-a:{shard}=001 ; 
       node-b:{shard}=001;
       node-c:{shard}=002;
       node-d:{shard}=002

      If define 1 shard 1 rep as follow sql, that is ok.
      CREATE TABLE test_1_local ON CLUSTER  my_cluster_name (
           id  UInt64
       )ENGINE=ReplicatedMergeTree('/clickhouse/tables/{shard}/test_1','{replica}')
      ORDER BY id

      But, if define 4 shard 0 rep , there is no way to create table like upper sql, because of the same {shard}.

      So should the {shard} tag be defined in <clickhouse_remote_servers><my_cluster_name>...</></>
      For example :
         <clickhouse_remote_servers>
                  <my_cluster_name>
                      <shard>
                             <value>0001</value>
                            <replica>
                                  <host>node-a</host>
                            </replica>
                            <replica>
                                  <host>node-c</host>
                            </replica>
                      </shard>
                      <shard>
                            <value>0002</value>
                            <replica>
                                  <host>node-b</host>
                            </replica>
                            <replica>
                                  <host>node-d</host>
                            </replica>
                      </shard>
          
                 </my_cluster_name>
         </my_cluster_name>

**Comment by den-crane** [comment]
It should be

```
node-a:{shard}=001 ;
node-c:{shard}=001;
node-b:{shard}=002;
node-d:{shard}=002;
```

because from this

```
     <clickhouse_remote_servers>
              <my_cluster_name>
                  <shard>                        ----- shard1
                        <replica>
                              <host>node-a</host>
                        </replica>
                        <replica>
                              <host>node-c</host>
                        </replica>
                  </shard>
                  <shard>                      -----  shard2
                        <replica>
                              <host>node-b</host>
                        </replica>
                        <replica>
                              <host>node-d</host>
                        </replica>
                  </shard>
     </my_cluster_name>
```

shards deduced automatically from `<shard>` tag order
