### ISSUE TITLE
(text in Russian) Разный результат выполнения запроса при переключении опции allow_experimental_projection_optimization

### ISSUE THREAD

**Issue by katigri** [ClickHouse/ClickHouse#41704]
ClickHouse версия 22.1.3.7 
Разный результат при переключении опции allow_experimental_projection_optimization
При использовании проекции получаю один результат, при отключенных проекциях - другой.

SELECT hostname() AS h, wbcount
FROM clusterAllReplicas('somecluster', 'somedb.some_replicated_mergetree_table')
WHERE (id = 15380171) AND (word = 'зубная паста') AND (data = today())
SETTINGS allow_experimental_projection_optimization = 1

┌─h─────┬─wbcount─┐
│ sx011 │  503037 │
└───────┴─────────┘
┌─h─────┬─wbcount─┐
│ sx111 │       0 │
└───────┴─────────┘

SELECT hostname() AS h, wbcount
FROM clusterAllReplicas('somecluster', 'somedb.some_replicated_mergetree_table')
WHERE (id = 15380171) AND (word = 'зубная паста') AND (data = today())
SETTINGS allow_experimental_projection_optimization = 0

┌─h─────┬─wbcount─┐
│ sx111 │  503037 │
└───────┴─────────┘
┌─h─────┬─wbcount─┐
│ sx011 │  503037 │
└───────┴─────────┘

CREATE TABLE somedb.some_replicated_mergetree_table
(
    `id` UInt32,
    `data` Date,
    `wid` UInt32,
    `word` String,
    `position` UInt16,
    `count` UInt32,
    `wbcount` UInt32,
    `wordmodify` UInt8,
    `totalfound` UInt32,
    `promotextcat` LowCardinality(String),
    PROJECTION proj_sometable_id
    (
        SELECT *
        ORDER BY (id, data)
    ),
    PROJECTION proj_sometable_worddata
    (
        SELECT *
        ORDER BY (word, data)
    )
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/somepath.{shard}', '{replica}')
PARTITION BY toYYYYMM(data)
ORDER BY (data, word)
SETTINGS index_granularity = 16384 

https://pastila.nl/?00a87494/37b2cd036f417608220d69c3077517fb

При вызове запросов непосредственно на sx111 аналогичное поведение;
При вызове запросов на sx011 в обоих вариантах получаю корректное поведение и корректные результаты;
optimize table final выполнялся на всякий случай, к изменению поведения это не привело;
select now(), timezone(), version() показывает одинаковые значения на обоих серверах;
В папке файлов проекции на первой и второй репликах одинаковое число файлов, одинакового размера, одинакового суммарного размера, побайтовой проверки не проводил, но вариантов порчи файлов другими процессами не вижу - сервера изолированные, на них только CH.

**Comment by amosbird** [comment]
Projection is not production ready in version < 22.3 . Is the issue reproducible in newer versions?
