### ISSUE TITLE
RPM repo reporting Bad GPG signature

### ISSUE THREAD

**Issue by djuarezg** [ClickHouse/ClickHouse#41718]
When configuring the ClickHouse repositories for RPM (ref. https://clickhouse.com/docs/en/getting-started/install/#from-rpm-packages), I get `Error: Failed to download metadata for repo 'clickhouse-stable': repomd.xml GPG signature verification error: Bad GPG signature`

A cache cleaning does not help.

```
dnf check-update -v
(...)
ClickHouse - Stable Repository                                                                                                                                 57 kB/s | 5.7 kB     00:00    
repo clickhouse-stable: 0x8919F6BD2B48D754 already imported
ClickHouse - Stable Repository                                                                                                                                3.2 kB/s | 833  B     00:00    
Error: Failed to download metadata for repo 'clickhouse-stable': repomd.xml GPG signature verification error: Bad GPG signature
```

**Comment by djuarezg** [comment]
Importing the key manually does not help. Removing it manually from `rpm -e` does not help either. It does not request for the usual prompt asking to import keys.

Running on Rocky Linux 8

**Comment by blinkov** [comment]
cc @Felixoid

**Comment by Felixoid** [comment]
Interesting. I've tried it on `docker run -it rockylinux:8`, the following commands work:

```
[root@e8eda5ac2a74 /]# yum install -y yum-utils
Rocky Linux 8 - AppStream                                                7.1 MB/s |  11 MB     00:01    
Rocky Linux 8 - BaseOS                                                   7.4 MB/s | 7.9 MB     00:01    
Rocky Linux 8 - Extras                                                    41 kB/s |  12 kB     00:00    
Last metadata expiration check: 0:00:01 ago on Fri Sep 23 12:50:34 2022.
Dependencies resolved.
=========================================================================================================
 Package                             Architecture      Version                   Repository         Size
=========================================================================================================
Installing:
 yum-utils                           noarch            4.0.21-11.el8             baseos             72 k
Installing dependencies:
 dbus-glib                           x86_64            0.110-2.el8               baseos            126 k
 dnf-plugins-core                    noarch            4.0.21-11.el8             baseos             70 k
 python3-dateutil                    noarch            1:2.6.1-6.el8             baseos            250 k
 python3-dbus                        x86_64            1.2.4-15.el8              baseos            133 k
 python3-dnf-plugins-core            noarch            4.0.21-11.el8             baseos            239 k
 python3-six                         noarch            1.11.0-8.el8              baseos             37 k

Transaction Summary
=========================================================================================================
Install  7 Packages

Total download size: 927 k
Installed size: 2.3 M
Downloading Packages:
(1/7): dnf-plugins-core-4.0.21-11.el8.noarch.rpm                         464 kB/s |  70 kB     00:00    
(2/7): dbus-glib-0.110-2.el8.x86_64.rpm                                  712 kB/s | 126 kB     00:00    
(3/7): python3-dateutil-2.6.1-6.el8.noarch.rpm                           1.3 MB/s | 250 kB     00:00    
(4/7): python3-dbus-1.2.4-15.el8.x86_64.rpm                              2.3 MB/s | 133 kB     00:00    
(5/7): python3-six-1.11.0-8.el8.noarch.rpm                               905 kB/s |  37 kB     00:00    
(6/7): python3-dnf-plugins-core-4.0.21-11.el8.noarch.rpm                 3.8 MB/s | 239 kB     00:00    
(7/7): yum-utils-4.0.21-11.el8.noarch.rpm                                1.4 MB/s |  72 kB     00:00    
---------------------------------------------------------------------------------------------------------
Total                                                                    1.8 MB/s | 927 kB     00:00     
Rocky Linux 8 - BaseOS                                                   1.6 MB/s | 1.6 kB     00:00    
Importing GPG key 0x6D745A60:
 Userid     : "Release Engineering <infrastructure@rockylinux.org>"
 Fingerprint: 7051 C470 A929 F454 CEBE 37B7 15AF 5DAC 6D74 5A60
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-rockyofficial
Key imported successfully
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                 1/1 
  Installing       : python3-six-1.11.0-8.el8.noarch                                                 1/7 
  Installing       : python3-dateutil-1:2.6.1-6.el8.noarch                                           2/7 
  Installing       : dbus-glib-0.110-2.el8.x86_64                                                    3/7 
  Running scriptlet: dbus-glib-0.110-2.el8.x86_64                                                    3/7 
  Installing       : python3-dbus-1.2.4-15.el8.x86_64                                                4/7 
  Installing       : python3-dnf-plugins-core-4.0.21-11.el8.noarch                                   5/7 
  Installing       : dnf-plugins-core-4.0.21-11.el8.noarch                                           6/7 
  Installing       : yum-utils-4.0.21-11.el8.noarch                                                  7/7 
  Running scriptlet: yum-utils-4.0.21-11.el8.noarch                                                  7/7 
  Verifying        : dbus-glib-0.110-2.el8.x86_64                                                    1/7 
  Verifying        : dnf-plugins-core-4.0.21-11.el8.noarch                                           2/7 
  Verifying        : python3-dateutil-1:2.6.1-6.el8.noarch                                           3/7 
  Verifying        : python3-dbus-1.2.4-15.el8.x86_64                                                4/7 
  Verifying        : python3-dnf-plugins-core-4.0.21-11.el8.noarch                                   5/7 
  Verifying        : python3-six-1.11.0-8.el8.noarch                                                 6/7 
  Verifying        : yum-utils-4.0.21-11.el8.noarch                                                  7/7 

Installed:
  dbus-glib-0.110-2.el8.x86_64                            dnf-plugins-core-4.0.21-11.el8.noarch          
  python3-dateutil-1:2.6.1-6.el8.noarch                   python3-dbus-1.2.4-15.el8.x86_64               
  python3-dnf-plugins-core-4.0.21-11.el8.noarch           python3-six-1.11.0-8.el8.noarch                
  yum-utils-4.0.21-11.el8.noarch                         

Complete!
[root@e8eda5ac2a74 /]# yum-config-manager --add-repo https://packages.clickhouse.com/rpm/clickhouse.repo
Adding repo from: https://packages.clickhouse.com/rpm/clickhouse.repo
[root@e8eda5ac2a74 /]# yum install -y clickhouse-server clickhouse-client
ClickHouse - Stable Repository                                           1.1 kB/s | 833  B     00:00    
ClickHouse - Stable Repository                                            13 kB/s | 5.7 kB     00:00    
Importing GPG key 0x2B48D754:
 Userid     : "ClickHouse Inc. Repositories Key <packages@clickhouse.com>"
 Fingerprint: 3A9E A119 3A97 B548 BE14 57D4 8919 F6BD 2B48 D754
 From       : https://packages.clickhouse.com/rpm/stable/repodata/repomd.xml.key
ClickHouse - Stable Repository                                            53 kB/s |  57 kB     00:01    
Dependencies resolved.
=========================================================================================================
 Package                           Architecture    Version              Repository                  Size
=========================================================================================================
Installing:
 clickhouse-client                 x86_64          22.9.2.7-1           clickhouse-stable           86 k
 clickhouse-server                 x86_64          22.9.2.7-1           clickhouse-stable          112 k
Installing dependencies:
 clickhouse-common-static          x86_64          22.9.2.7-1           clickhouse-stable          237 M

Transaction Summary
=========================================================================================================
Install  3 Packages

Total download size: 237 M
Installed size: 668 M
Downloading Packages:
(1/3): clickhouse-client-22.9.2.7.x86_64.rpm                             149 kB/s |  86 kB     00:00    
(2/3): clickhouse-server-22.9.2.7.x86_64.rpm                             193 kB/s | 112 kB     00:00    
(3/3): clickhouse-common-static-22.9.2.7.x86_64.rpm                       12 MB/s | 237 MB     00:19    
---------------------------------------------------------------------------------------------------------
Total                                                                     12 MB/s | 237 MB     00:19     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                 1/1 
  Installing       : clickhouse-common-static-22.9.2.7-1.x86_64                                      1/3 
  Installing       : clickhouse-client-22.9.2.7-1.x86_64                                             2/3 
  Installing       : clickhouse-server-22.9.2.7-1.x86_64                                             3/3 
  Running scriptlet: clickhouse-server-22.9.2.7-1.x86_64                                             3/3 
Cannot set 'net_admin' or 'ipc_lock' or 'sys_nice' or 'net_bind_service' capability for clickhouse binary. This is optional. Taskstats accounting will be disabled. To enable taskstats accounting you may add the required capability later manually.
ClickHouse binary is already located at /usr/bin/clickhouse
Symlink /usr/bin/clickhouse-server already exists but it points to /clickhouse. Will replace the old symlink to /usr/bin/clickhouse.
Creating symlink /usr/bin/clickhouse-server to /usr/bin/clickhouse.
Symlink /usr/bin/clickhouse-client already exists but it points to /clickhouse. Will replace the old symlink to /usr/bin/clickhouse.
Creating symlink /usr/bin/clickhouse-client to /usr/bin/clickhouse.
Symlink /usr/bin/clickhouse-local already exists but it points to /clickhouse. Will replace the old symlink to /usr/bin/clickhouse.
Creating symlink /usr/bin/clickhouse-local to /usr/bin/clickhouse.
Symlink /usr/bin/clickhouse-benchmark already exists but it points to /clickhouse. Will replace the old symlink to /usr/bin/clickhouse.
Creating symlink /usr/bin/clickhouse-benchmark to /usr/bin/clickhouse.
Symlink /usr/bin/clickhouse-copier already exists but it points to /clickhouse. Will replace the old symlink to /usr/bin/clickhouse.
Creating symlink /usr/bin/clickhouse-copier to /usr/bin/clickhouse.
Symlink /usr/bin/clickhouse-obfuscator already exists but it points to /clickhouse. Will replace the old symlink to /usr/bin/clickhouse.
Creating symlink /usr/bin/clickhouse-obfuscator to /usr/bin/clickhouse.
Creating symlink /usr/bin/clickhouse-git-import to /usr/bin/clickhouse.
Symlink /usr/bin/clickhouse-compressor already exists but it points to /clickhouse. Will replace the old symlink to /usr/bin/clickhouse.
Creating symlink /usr/bin/clickhouse-compressor to /usr/bin/clickhouse.
Symlink /usr/bin/clickhouse-format already exists but it points to /clickhouse. Will replace the old symlink to /usr/bin/clickhouse.
Creating symlink /usr/bin/clickhouse-format to /usr/bin/clickhouse.
Symlink /usr/bin/clickhouse-extract-from-config already exists but it points to /clickhouse. Will replace the old symlink to /usr/bin/clickhouse.
Creating symlink /usr/bin/clickhouse-extract-from-config to /usr/bin/clickhouse.
Symlink /usr/bin/clickhouse-keeper already exists but it points to /clickhouse. Will replace the old symlink to /usr/bin/clickhouse.
Creating symlink /usr/bin/clickhouse-keeper to /usr/bin/clickhouse.
Creating symlink /usr/bin/clickhouse-keeper-converter to /usr/bin/clickhouse.
Creating symlink /usr/bin/clickhouse-disks to /usr/bin/clickhouse.
Creating clickhouse group if it does not exist.
 groupadd -r clickhouse
Creating clickhouse user if it does not exist.
 useradd -r --shell /bin/false --home-dir /nonexistent -g clickhouse clickhouse
Will set ulimits for clickhouse user in /etc/security/limits.d/clickhouse.conf.
Creating config directory /etc/clickhouse-server/config.d that is used for tweaks of main server configuration.
Creating config directory /etc/clickhouse-server/users.d that is used for tweaks of users configuration.
Config file /etc/clickhouse-server/config.xml already exists, will keep it and extract path info from it.
/etc/clickhouse-server/config.xml has /var/lib/clickhouse/ as data path.
/etc/clickhouse-server/config.xml has /var/log/clickhouse-server/ as log path.
Users config file /etc/clickhouse-server/users.xml already exists, will keep it and extract users info from it.
Creating log directory /var/log/clickhouse-server/.
Creating data directory /var/lib/clickhouse/.
Creating pid directory /var/run/clickhouse-server.
 chown -R clickhouse:clickhouse '/var/log/clickhouse-server/'
 chown -R clickhouse:clickhouse '/var/run/clickhouse-server'
 chown  clickhouse:clickhouse '/var/lib/clickhouse/'
 groupadd -r clickhouse-bridge
 useradd -r --shell /bin/false --home-dir /nonexistent -g clickhouse-bridge clickhouse-bridge
 chown -R clickhouse-bridge:clickhouse-bridge '/usr/bin/clickhouse-odbc-bridge'
 chown -R clickhouse-bridge:clickhouse-bridge '/usr/bin/clickhouse-library-bridge'
Password for default user is empty string. See /etc/clickhouse-server/users.xml and /etc/clickhouse-server/users.d to change it.
Setting capabilities for clickhouse binary. This is optional.
 chown -R clickhouse:clickhouse '/etc/clickhouse-server'

ClickHouse has been successfully installed.

Start clickhouse-server with:
 sudo clickhouse start

Start clickhouse-client with:
 clickhouse-client



  Verifying        : clickhouse-client-22.9.2.7-1.x86_64                                             1/3 
  Verifying        : clickhouse-common-static-22.9.2.7-1.x86_64                                      2/3 
  Verifying        : clickhouse-server-22.9.2.7-1.x86_64                                             3/3 

Installed:
  clickhouse-client-22.9.2.7-1.x86_64             clickhouse-common-static-22.9.2.7-1.x86_64            
  clickhouse-server-22.9.2.7-1.x86_64            

Complete!
[root@e8eda5ac2a74 /]# 
```

I am not an RPM-based distros expert. But it looks like the same issue as with DEB repos to me https://github.com/ClickHouse/ClickHouse/issues/41420#issuecomment-1255140142

**Comment by djuarezg** [comment]
> Interesting. I've tried it on `docker run -it rockylinux:8`, the following commands work:
> 
> ```
> [root@e8eda5ac2a74 /]# yum install -y yum-utils
> Rocky Linux 8 - AppStream                                                7.1 MB/s |  11 MB     00:01    
> Rocky Linux 8 - BaseOS                                                   7.4 MB/s | 7.9 MB     00:01    
> Rocky Linux 8 - Extras                                                    41 kB/s |  12 kB     00:00    
> Last metadata expiration check: 0:00:01 ago on Fri Sep 23 12:50:34 2022.
> Dependencies resolved.
> =========================================================================================================
>  Package                             Architecture      Version                   Repository         Size
> =========================================================================================================
> Installing:
>  yum-utils                           noarch            4.0.21-11.el8             baseos             72 k
> Installing dependencies:
>  dbus-glib                           x86_64            0.110-2.el8               baseos            126 k
>  dnf-plugins-core                    noarch            4.0.21-11.el8             baseos             70 k
>  python3-dateutil                    noarch            1:2.6.1-6.el8             baseos            250 k
>  python3-dbus                        x86_64            1.2.4-15.el8              baseos            133 k
>  python3-dnf-plugins-core            noarch            4.0.21-11.el8             baseos            239 k
>  python3-six                         noarch            1.11.0-8.el8              baseos             37 k
> 
> Transaction Summary
> =========================================================================================================
> Install  7 Packages
> 
> Total download size: 927 k
> Installed size: 2.3 M
> Downloading Packages:
> (1/7): dnf-plugins-core-4.0.21-11.el8.noarch.rpm                         464 kB/s |  70 kB     00:00    
> (2/7): dbus-glib-0.110-2.el8.x86_64.rpm                                  712 kB/s | 126 kB     00:00    
> (3/7): python3-dateutil-2.6.1-6.el8.noarch.rpm                           1.3 MB/s | 250 kB     00:00    
> (4/7): python3-dbus-1.2.4-15.el8.x86_64.rpm                              2.3 MB/s | 133 kB     00:00    
> (5/7): python3-six-1.11.0-8.el8.noarch.rpm                               905 kB/s |  37 kB     00:00    
> (6/7): python3-dnf-plugins-core-4.0.21-11.el8.noarch.rpm                 3.8 MB/s | 239 kB     00:00    
> (7/7): yum-utils-4.0.21-11.el8.noarch.rpm                                1.4 MB/s |  72 kB     00:00    
> ---------------------------------------------------------------------------------------------------------
> Total                                                                    1.8 MB/s | 927 kB     00:00     
> Rocky Linux 8 - BaseOS                                                   1.6 MB/s | 1.6 kB     00:00    
> Importing GPG key 0x6D745A60:
>  Userid     : "Release Engineering <infrastructure@rockylinux.org>"
>  Fingerprint: 7051 C470 A929 F454 CEBE 37B7 15AF 5DAC 6D74 5A60
>  From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-rockyofficial
> Key imported successfully
> Running transaction check
> Transaction check succeeded.
> Running transaction test
> Transaction test succeeded.
> Running transaction
>   Preparing        :                                                                                 1/1 
>   Installing       : python3-six-1.11.0-8.el8.noarch                                                 1/7 
>   Installing       : python3-dateutil-1:2.6.1-6.el8.noarch                                           2/7 
>   Installing       : dbus-glib-0.110-2.el8.x86_64                                                    3/7 
>   Running scriptlet: dbus-glib-0.110-2.el8.x86_64                                                    3/7 
>   Installing       : python3-dbus-1.2.4-15.el8.x86_64                                                4/7 
>   Installing       : python3-dnf-plugins-core-4.0.21-11.el8.noarch                                   5/7 
>   Installing       : dnf-plugins-core-4.0.21-11.el8.noarch                                           6/7 
>   Installing       : yum-utils-4.0.21-11.el8.noarch                                                  7/7 
>   Running scriptlet: yum-utils-4.0.21-11.el8.noarch                                                  7/7 
>   Verifying        : dbus-glib-0.110-2.el8.x86_64                                                    1/7 
>   Verifying        : dnf-plugins-core-4.0.21-11.el8.noarch                                           2/7 
>   Verifying        : python3-dateutil-1:2.6.1-6.el8.noarch                                           3/7 
>   Verifying        : python3-dbus-1.2.4-15.el8.x86_64                                                4/7 
>   Verifying        : python3-dnf-plugins-core-4.0.21-11.el8.noarch                                   5/7 
>   Verifying        : python3-six-1.11.0-8.el8.noarch                                                 6/7 
>   Verifying        : yum-utils-4.0.21-11.el8.noarch                                                  7/7 
> 
> Installed:
>   dbus-glib-0.110-2.el8.x86_64                            dnf-plugins-core-4.0.21-11.el8.noarch          
>   python3-dateutil-1:2.6.1-6.el8.noarch                   python3-dbus-1.2.4-15.el8.x86_64               
>   python3-dnf-plugins-core-4.0.21-11.el8.noarch           python3-six-1.11.0-8.el8.noarch                
>   yum-utils-4.0.21-11.el8.noarch                         
> 
> Complete!
> [root@e8eda5ac2a74 /]# yum-config-manager --add-repo https://packages.clickhouse.com/rpm/clickhouse.repo
> Adding repo from: https://packages.clickhouse.com/rpm/clickhouse.repo
> [root@e8eda5ac2a74 /]# yum install -y clickhouse-server clickhouse-client
> ClickHouse - Stable Repository                                           1.1 kB/s | 833  B     00:00    
> ClickHouse - Stable Repository                                            13 kB/s | 5.7 kB     00:00    
> Importing GPG key 0x2B48D754:
>  Userid     : "ClickHouse Inc. Repositories Key <packages@clickhouse.com>"
>  Fingerprint: 3A9E A119 3A97 B548 BE14 57D4 8919 F6BD 2B48 D754
>  From       : https://packages.clickhouse.com/rpm/stable/repodata/repomd.xml.key
> ClickHouse - Stable Repository                                            53 kB/s |  57 kB     00:01    
> Dependencies resolved.
> =========================================================================================================
>  Package                           Architecture    Version              Repository                  Size
> =========================================================================================================
> Installing:
>  clickhouse-client                 x86_64          22.9.2.7-1           clickhouse-stable           86 k
>  clickhouse-server                 x86_64          22.9.2.7-1           clickhouse-stable          112 k
> Installing dependencies:
>  clickhouse-common-static          x86_64          22.9.2.7-1           clickhouse-stable          237 M
> 
> Transaction Summary
> =========================================================================================================
> Install  3 Packages
> 
> Total download size: 237 M
> Installed size: 668 M
> Downloading Packages:
> (1/3): clickhouse-client-22.9.2.7.x86_64.rpm                             149 kB/s |  86 kB     00:00    
> (2/3): clickhouse-server-22.9.2.7.x86_64.rpm                             193 kB/s | 112 kB     00:00    
> (3/3): clickhouse-common-static-22.9.2.7.x86_64.rpm                       12 MB/s | 237 MB     00:19    
> ---------------------------------------------------------------------------------------------------------
> Total                                                                     12 MB/s | 237 MB     00:19     
> Running transaction check
> Transaction check succeeded.
> Running transaction test
> Transaction test succeeded.
> Running transaction
>   Preparing        :                                                                                 1/1 
>   Installing       : clickhouse-common-static-22.9.2.7-1.x86_64                                      1/3 
>   Installing       : clickhouse-client-22.9.2.7-1.x86_64                                             2/3 
>   Installing       : clickhouse-server-22.9.2.7-1.x86_64                                             3/3 
>   Running scriptlet: clickhouse-server-22.9.2.7-1.x86_64                                             3/3 
> Cannot set 'net_admin' or 'ipc_lock' or 'sys_nice' or 'net_bind_service' capability for clickhouse binary. This is optional. Taskstats accounting will be disabled. To enable taskstats accounting you may add the required capability later manually.
> ClickHouse binary is already located at /usr/bin/clickhouse
> Symlink /usr/bin/clickhouse-server already exists but it points to /clickhouse. Will replace the old symlink to /usr/bin/clickhouse.
> Creating symlink /usr/bin/clickhouse-server to /usr/bin/clickhouse.
> Symlink /usr/bin/clickhouse-client already exists but it points to /clickhouse. Will replace the old symlink to /usr/bin/clickhouse.
> Creating symlink /usr/bin/clickhouse-client to /usr/bin/clickhouse.
> Symlink /usr/bin/clickhouse-local already exists but it points to /clickhouse. Will replace the old symlink to /usr/bin/clickhouse.
> Creating symlink /usr/bin/clickhouse-local to /usr/bin/clickhouse.
> Symlink /usr/bin/clickhouse-benchmark already exists but it points to /clickhouse. Will replace the old symlink to /usr/bin/clickhouse.
> Creating symlink /usr/bin/clickhouse-benchmark to /usr/bin/clickhouse.
> Symlink /usr/bin/clickhouse-copier already exists but it points to /clickhouse. Will replace the old symlink to /usr/bin/clickhouse.
> Creating symlink /usr/bin/clickhouse-copier to /usr/bin/clickhouse.
> Symlink /usr/bin/clickhouse-obfuscator already exists but it points to /clickhouse. Will replace the old symlink to /usr/bin/clickhouse.
> Creating symlink /usr/bin/clickhouse-obfuscator to /usr/bin/clickhouse.
> Creating symlink /usr/bin/clickhouse-git-import to /usr/bin/clickhouse.
> Symlink /usr/bin/clickhouse-compressor already exists but it points to /clickhouse. Will replace the old symlink to /usr/bin/clickhouse.
> Creating symlink /usr/bin/clickhouse-compressor to /usr/bin/clickhouse.
> Symlink /usr/bin/clickhouse-format already exists but it points to /clickhouse. Will replace the old symlink to /usr/bin/clickhouse.
> Creating symlink /usr/bin/clickhouse-format to /usr/bin/clickhouse.
> Symlink /usr/bin/clickhouse-extract-from-config already exists but it points to /clickhouse. Will replace the old symlink to /usr/bin/clickhouse.
> Creating symlink /usr/bin/clickhouse-extract-from-config to /usr/bin/clickhouse.
> Symlink /usr/bin/clickhouse-keeper already exists but it points to /clickhouse. Will replace the old symlink to /usr/bin/clickhouse.
> Creating symlink /usr/bin/clickhouse-keeper to /usr/bin/clickhouse.
> Creating symlink /usr/bin/clickhouse-keeper-converter to /usr/bin/clickhouse.
> Creating symlink /usr/bin/clickhouse-disks to /usr/bin/clickhouse.
> Creating clickhouse group if it does not exist.
>  groupadd -r clickhouse
> Creating clickhouse user if it does not exist.
>  useradd -r --shell /bin/false --home-dir /nonexistent -g clickhouse clickhouse
> Will set ulimits for clickhouse user in /etc/security/limits.d/clickhouse.conf.
> Creating config directory /etc/clickhouse-server/config.d that is used for tweaks of main server configuration.
> Creating config directory /etc/clickhouse-server/users.d that is used for tweaks of users configuration.
> Config file /etc/clickhouse-server/config.xml already exists, will keep it and extract path info from it.
> /etc/clickhouse-server/config.xml has /var/lib/clickhouse/ as data path.
> /etc/clickhouse-server/config.xml has /var/log/clickhouse-server/ as log path.
> Users config file /etc/clickhouse-server/users.xml already exists, will keep it and extract users info from it.
> Creating log directory /var/log/clickhouse-server/.
> Creating data directory /var/lib/clickhouse/.
> Creating pid directory /var/run/clickhouse-server.
>  chown -R clickhouse:clickhouse '/var/log/clickhouse-server/'
>  chown -R clickhouse:clickhouse '/var/run/clickhouse-server'
>  chown  clickhouse:clickhouse '/var/lib/clickhouse/'
>  groupadd -r clickhouse-bridge
>  useradd -r --shell /bin/false --home-dir /nonexistent -g clickhouse-bridge clickhouse-bridge
>  chown -R clickhouse-bridge:clickhouse-bridge '/usr/bin/clickhouse-odbc-bridge'
>  chown -R clickhouse-bridge:clickhouse-bridge '/usr/bin/clickhouse-library-bridge'
> Password for default user is empty string. See /etc/clickhouse-server/users.xml and /etc/clickhouse-server/users.d to change it.
> Setting capabilities for clickhouse binary. This is optional.
>  chown -R clickhouse:clickhouse '/etc/clickhouse-server'
> 
> ClickHouse has been successfully installed.
> 
> Start clickhouse-server with:
>  sudo clickhouse start
> 
> Start clickhouse-client with:
>  clickhouse-client
> 
> 
> 
>   Verifying        : clickhouse-client-22.9.2.7-1.x86_64                                             1/3 
>   Verifying        : clickhouse-common-static-22.9.2.7-1.x86_64                                      2/3 
>   Verifying        : clickhouse-server-22.9.2.7-1.x86_64                                             3/3 
> 
> Installed:
>   clickhouse-client-22.9.2.7-1.x86_64             clickhouse-common-static-22.9.2.7-1.x86_64            
>   clickhouse-server-22.9.2.7-1.x86_64            
> 
> Complete!
> [root@e8eda5ac2a74 /]# 
> ```
> 
> I am not an RPM-based distros expert. But it looks like the same issue as with DEB repos to me [#41420 (comment)](https://github.com/ClickHouse/ClickHouse/issues/41420#issuecomment-1255140142)

It may very well be, which I also suspect collides with a rare `yum/dnf` bug that does not update the import key.

If someone finds themselves in the same situation, cleaning the cache with `yum/dnf clean all` did not help for me, but a manual `rm -Rf /var/cache/yum/` *and* `rm -Rf /var/cache/dnf/` did the trick. Next time you are asked about importing the key and it all goes back to normal.

**Comment by Felixoid** [comment]
Thanks a lot, I am closing it then
