### ISSUE TITLE
Will clickhosue memory or CPU usage be high when the kafka topic  does not exist

### ISSUE THREAD

**Issue by Haun-Lin** [ClickHouse/ClickHouse#41710]
here is my sql,
CREATE TABLE test_table
(
   id String COMMENT 'id',
   name String COMMENT 'name'
)
ENGINE = Kafka
SETTINGS kafka_broker_list = 'xxx:9092', kafka_topic_list = 'test-topic', kafka_group_name = 'test_consumer', kafka_format = 'JSONEachRow', kafka_skip_broken_messages = 999, kafka_num_consumers = 3;

Will CK memory or CPU usage be high when the kafka topic(test-topic)  does not exist.
Can someone help with this? Thanks so much

**Comment by filimonov** [comment]
It will have several threads working in the background (every consumer: one thread per broker + few service threads). 

NOrmally the load created by them (if they do nothing) should not be big, but if you have a lot of brokers and / or small clickhouse instance it can be visible.
