### ISSUE TITLE
Lightweight delete causes segfault when table is created with _row_exists column

### ISSUE THREAD

**Issue by jzombi** [ClickHouse/ClickHouse#41716]
**Describe the unexpected behaviour**
The lightweight delete feature implementation causes server side segfault when table is created with a `_row_exists` column.

**How to reproduce**
Tested on ~~master branch (commit `74ffb8438`)~~ tag `v22.8.5.29-lts`.

Edit: WARNING: be careful when testing, the created table cannot be dropped from CH!

```
CREATE TABLE test(
    whatever String,
    _row_exists String
)
ENGINE = MergeTree()
ORDER BY whatever;  -- Works

INSERT INTO test values('1', '1');  -- Still works

SELECT * FROM test;  -- Fails in client, sometimes segfault in server?

DROP TABLE test; -- Client hangs for a while, then exits, segfault in server
```

**Expected behavior**
If it is not possible to use tables with explicitly created `_row_exists` column, the create statement should raise an error, and this restriction should be documented IMHO. (It would be a nice feature if the column name containing the delete mask could be specified in the MergeTree parameters upon table creation, defaulting to `_row_exists`.)

**Error message and/or stacktrace**
Failure message in client after `SELECT`:
```
Received exception from server (version 22.8.5):
Code: 352. DB::Exception: Received from localhost:9000. DB::Exception: Block structure mismatch in (columns with identical name must have identical structure) stream: different types:
_row_exists String String(size = 1)
_row_exists UInt8 UInt8(size = 1): While executing MergeTreeInOrder. (AMBIGUOUS_COLUMN_NAME)
```

Error message in server after `SELECT`:
```
2022.09.23 10:17:31.352611 [ 306928 ] {6906df8e-36b2-4ec3-9012-3f1faaa00fc3} <Error> executeQuery: Code: 352. DB::Exception: Block structure mismatch in (columns with identical name must have identical structure) stream: different types:
_row_exists String String(size = 1)
_row_exists UInt8 UInt8(size = 1): While executing MergeTreeThread. (AMBIGUOUS_COLUMN_NAME) (version 22.8.5.1) (from [::1]:34452) (in query: select * from test;), Stack trace (when copying this message, always include the lines below):

0. /home/clickhouse/build/./contrib/libcxx/include/exception:133: Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x183f3aac in /home/clickhouse/build/programs/clickhouse
1. /home/clickhouse/build/./src/Common/Exception.cpp:69: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x1035f348 in /home/clickhouse/build/programs/clickhouse
2. /home/clickhouse/build/./src/Core/Block.cpp:36: void DB::checkColumnStructure<void>(DB::ColumnWithTypeAndName const&, DB::ColumnWithTypeAndName const&, std::__1::basic_string_view<char, std::__1::char_traits<char> >, bool, int) @ 0x1471e8cb in /home/clickhouse/build/programs/clickhouse
3. /home/clickhouse/build/./contrib/libcxx/include/vector:1575: DB::Block::insert(DB::ColumnWithTypeAndName) @ 0x1471f094 in /home/clickhouse/build/programs/clickhouse
4. /home/clickhouse/build/./contrib/libcxx/include/string:1445: DB::MergeTreeBaseSelectProcessor::injectVirtualColumns(DB::Block&, unsigned long, DB::MergeTreeReadTask*, std::__1::shared_ptr<DB::IDataType const> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x1641590e in /home/clickhouse/build/programs/clickhouse
5. /home/clickhouse/build/./src/Storages/MergeTree/MergeTreeBaseSelectProcessor.cpp:216: DB::MergeTreeBaseSelectProcessor::generate() @ 0x16414dbd in /home/clickhouse/build/programs/clickhouse
6. /home/clickhouse/build/./src/Processors/Chunk.h:90: DB::ISource::tryGenerate() @ 0x160ee323 in /home/clickhouse/build/programs/clickhouse
7. /home/clickhouse/build/./contrib/libcxx/include/optional:321: DB::ISource::work() @ 0x160edf92 in /home/clickhouse/build/programs/clickhouse
8. /home/clickhouse/build/./src/Processors/Executors/ExecutionThreadContext.cpp:0: DB::ExecutionThreadContext::executeTask() @ 0x16107bc0 in /home/clickhouse/build/programs/clickhouse
9. /home/clickhouse/build/./src/Processors/Executors/PipelineExecutor.cpp:228: DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x160fdcba in /home/clickhouse/build/programs/clickhouse
10. /home/clickhouse/build/./src/Processors/Executors/PipelineExecutor.cpp:0: void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) @ 0x160ff1fe in /home/clickhouse/build/programs/clickhouse
11. /home/clickhouse/build/./contrib/libcxx/include/__functional/function.h:832: ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x103f435f in /home/clickhouse/build/programs/clickhouse
12. /home/clickhouse/build/./contrib/libcxx/include/__memory/unique_ptr.h:312: void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) @ 0x103f67c0 in /home/clickhouse/build/programs/clickhouse
13. ? @ 0x7efea9f4078d in ?
14. clone @ 0x7efea9fc18e4 in ?
```

Failure message in client after `DROP`:
```
Exception on client:
Code: 32. DB::Exception: Attempt to read after eof: while receiving packet from localhost:9000. (ATTEMPT_TO_READ_AFTER_EOF)

Connecting to localhost:9000 as user default.
Code: 210. DB::NetException: Connection refused (localhost:9000). (NETWORK_ERROR)
```

Server after `SELECT` / `DROP`:
```
Segmentation fault (core dumped)
```

**Additional context**
Tested on ~~master branch (commit `74ffb8438`)~~ `v22.8.5.29-lts`.

**Comment by lqhl** [comment]
@zhangjmruc

**Comment by zhangjmruc** [comment]
Tried on latest CH 22.9, but failed to reproduce the Segmentation fault on server. Only see the error with AMBIGUOUS_COLUMN_NAME.

By the way,  tables with other virtual columns like, _part, _database, the same error occurs.

=== details ===
clickhouse-client -mn
ClickHouse client version 22.9.1.2603 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 22.9.1 revision 54460.

VM-7-13-ubuntu :) select * from test;

SELECT *
FROM test

Query id: b37c40e4-b361-439e-8749-2462d0ea8e49


0 rows in set. Elapsed: 0.054 sec.

Received exception from server (version 22.9.1):
Code: 352. DB::Exception: Received from localhost:9000. DB::Exception: Block structure mismatch in (columns with identical name must have identical structure) stream: different types:
_row_exists String String(size = 1)
_row_exists UInt8 UInt8(size = 1): While executing MergeTreeInOrder. (AMBIGUOUS_COLUMN_NAME)

VM-7-13-ubuntu :) show create table test;

SHOW CREATE TABLE test

Query id: efcb19db-506d-4492-9478-2e509ea78d3b

┌─statement─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ CREATE TABLE default.test
(
    `whatever` String,
    `_row_exists` String
)
ENGINE = MergeTree
ORDER BY whatever
SETTINGS index_granularity = 8192 │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

1 row in set. Elapsed: 0.001 sec.

VM-7-13-ubuntu :) drop table test;

DROP TABLE test

Query id: cdda5eb8-329c-44d0-bc08-9967d804d4d5

Ok.

0 rows in set. Elapsed: 0.001 sec.

**Comment by jzombi** [comment]
Thanks for the quick reply.

> Tried on latest CH 22.9, but failed to reproduce the Segmentation fault on server. Only see the error with AMBIGUOUS_COLUMN_NAME.
The commit specified in my OP was incorrect, sorry. I used `v22.8.5.29-lts` tag and compiled ClickHouse myself. So the difference might be caused by either the difference in commits between this and v22.9, or by different compile flags / dependency versions used to build CH. Could you please check it with v22.8?

> By the way, tables with other virtual columns like, _part, _database, the same error occurs.
I was not aware of other virtual columns, then it is not restricted to lightweight delete. ClickHouse should refuse to create tables with these columns then.

**Comment by tavplubix** [comment]
cc: @davenger

**Comment by zhangjmruc** [comment]
> Could you please check it with v22.8?
@jzombi I tried with official build deb packages on v22.8.5.29-lts, same behaviors as CH 22.9. The select fails but the server is ok and table can be dropped.

> I was not aware of other virtual columns, then it is not restricted to lightweight delete. ClickHouse should refuse to create tables with these columns then.

Will add some checks for this virtual columns when creating tables.

===== details ===
$ clickhouse-client -mn
ClickHouse client version 22.8.5.29 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 22.8.5 revision 54460.

Warnings:
 * Linux is not using a fast TSC clock source. Performance can be degraded. Check /sys/devices/system/clocksource/clocksource0/current_clocksource

VM-7-13-ubuntu :) CREATE TABLE test(
                      whatever String,
                      _row_exists String
                  )
                  ENGINE = MergeTree()
                  ORDER BY whatever;

CREATE TABLE test
(
    `whatever` String,
    `_row_exists` String
)
ENGINE = MergeTree
ORDER BY whatever

Query id: 9b329806-0b49-4ee5-9bab-b73928533675

Ok.

0 rows in set. Elapsed: 0.015 sec.

VM-7-13-ubuntu :) INSERT INTO test values('1', '1');

INSERT INTO test FORMAT Values

Query id: c8ec6848-e011-45ab-bfa0-38f0cb36d544

Ok.

1 row in set. Elapsed: 0.002 sec.

VM-7-13-ubuntu :) SELECT * FROM test;

SELECT *
FROM test

Query id: 459cb126-a83f-4aff-b56c-f282c7d5fea2


0 rows in set. Elapsed: 0.002 sec.

Received exception from server (version 22.8.5):
Code: 352. DB::Exception: Received from localhost:9000. DB::Exception: Block structure mismatch in (columns with identical name must have identical structure) stream: different types:
_row_exists String String(size = 1)
_row_exists UInt8 UInt8(size = 1): While executing MergeTreeInOrder. (AMBIGUOUS_COLUMN_NAME)

VM-7-13-ubuntu :) show create table test;

SHOW CREATE TABLE test

Query id: 724ba536-e46b-4333-ae25-0cee010ab58b

┌─statement─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ CREATE TABLE default.test
(
    `whatever` String,
    `_row_exists` String
)
ENGINE = MergeTree
ORDER BY whatever
SETTINGS index_granularity = 8192 │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

1 row in set. Elapsed: 0.001 sec.

VM-7-13-ubuntu :) drop table test;

DROP TABLE test

Query id: bb88d05d-1c8e-426d-8cbd-f4e27e38b9ba

Ok.

0 rows in set. Elapsed: 0.001 sec.

VM-7-13-ubuntu :) quit;
Bye.
ubuntu@VM-7-13-ubuntu:~/app$ sudo clickhouse status
/var/run/clickhouse-server/clickhouse-server.pid file exists and contains pid = 3766212.
The process with pid = 3766212 is running.

**Comment by jzombi** [comment]
Thanks @zhangjmruc, then the the segfault problem is only with my build.

> Will add some checks for this virtual columns when creating tables.

Would be great, thanks!
