### ISSUE TITLE
replication_alter_partitions_sync=2   , it doesn't work

### ISSUE THREAD

**Issue by liumaojing** [ClickHouse/ClickHouse#41711]
clickhouse client execute query:

alter table tab on cluster test add column col1 UInt8 settings replication_alter_partitions_sync=2

bug:(21.3.14)
The table engine is  ReplicatedMergeTree,i find that the local table of each node  settings replication_alter_partitions_sync=1  ,why? and  i also read  source code ,i find local node context setting  replication_alter_partitions_sync=1。

**Comment by tavplubix** [comment]
> 21.3.14

This version is obsolete, please upgrade to supported version: https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md

> the local table of each node settings replication_alter_partitions_sync=1 ,why?

See https://github.com/ClickHouse/ClickHouse/issues/6107
