### ISSUE TITLE
Support for importing serialized T-Digests

### ISSUE THREAD

**Issue by oplehto** [ClickHouse/ClickHouse#41719]
**Use case**

We need to produce aggregate quantile calculations from huge amounts of raw data from a large number of sources. 

**Describe the solution you'd like**

- Data source calcluates a sketch or digest (T-Digest seems to be the best supported now in CH so that's fine)
- Ship the serialized digest data over a message bus
- Write it into ClickHouse using a standard column format (pair of arrays?)
- Import the serialized data into a quantileTDigestState aggregate using a ClickHouse function.

Thus it seems to me that the only thing really needed would be a fairly simple function to convert serialized T-Digest data into the `quantileTDigestState` internal representation. 

**Describe alternatives you've considered**

- Writing the data to a `quantileTDigestState` data structure directly as binary blocks could probably be possible but that would require some low-level work on the ClickHouse driver. 
- Processing the raw data into `quantileTDigestState` using clickhouse-local and writing it remotely might be an alternative for low volumes of data and low number of hosts but in this case that is not feasible.

**Comment by den-crane** [comment]
smth like 

```
build('quantileTDigestState', ([345435][111]) )

build('uniqState', ([345435][111]) )
```

or

```
buildQuantileTDigestState ([345435][111]) )

buildUniqState, ([345435][111]) )
```

**Comment by zvonand** [comment]
Currently working on this

**Comment by aadant** [comment]
see also https://docs.snowflake.com/en/user-guide/querying-approximate-percentile-values
https://docs.snowflake.com/en/sql-reference/functions/approx_percentile

**Comment by yalon** [comment]
Hi, I understand that until official support is added we'll have to patiently wait.

I wonder though if there's any semi-efficient way to batch insert partially aggregated data - something like inserting to a table with two arrays and then a materialized view that creates a _quantilesTDigestWeightedState_ from which we can then derive the desired state?

Any pointers are more than welcome :)

**Comment by thomoco** [comment]
requested in Community Slack also: https://clickhousedb.slack.com/archives/CU478UEQZ/p1683469703427989

**Comment by filimonov** [comment]
Some thoughts:
* some external system have TDigest you want to import into clickhouse (so the external system need to serialize TDigest data, and clickhouse need to deserialize it).
* AFAIK there is no standard serialization format for TDigest (https://github.com/tdunning/t-digest/issues/87), so any format which we will pick for serialization will be something 'non-standard'
* If we need to create some custom / non-standard serialization format - maybe we can just follow the serialization format used by the ClickHouse Aggregate function state?  (it is efficient and native for clickhouse). The current serialization format of TDigest is quite simple https://github.com/ClickHouse/ClickHouse/blob/c2f6999aca66b822f57689872233d1b10fdaa91f/src/AggregateFunctions/QuantileTDigest.h#L299-L312

Additionally, internally TDigest inside clickhouse slightly differs from the baseline implementation (not sure if it can impact the results, probably it shouldn't).

**Comment by alexey-milovidov** [comment]
I agree, the serialization format is easy, and you can write the data directly.
Alternatively, you can prepare it with clickhouse-local.

Keep in mind, that TDigest, while being popular, is not the best quantile estimation algorithm.

**Comment by den-crane** [comment]
One more option is to use Bitmaps (clichkouse-jdbc supports Bitmaps) and convert Bitmaps to T-Digests during insertion using ephemeral column.

**Comment by UnamedRus** [comment]
https://kb.altinity.com/altinity-kb-functions/how-to-encode-decode-quantiletdigest-state/

```sql
SELECT quantileTDigest(CAST(number, 'UInt32')) AS result
FROM numbers(10)

┌─result─┐
│      4 │
└────────┘

SELECT decodeTDigestState(quantileTDigestState(CAST(number, 'UInt32'))) AS state
FROM numbers(10)

┌─state─────────────────────────────────────────────────────────┐
│ [(0,1),(1,1),(2,1),(3,1),(4,1),(5,1),(6,1),(7,1),(8,1),(9,1)] │
└───────────────────────────────────────────────────────────────┘

SELECT finalizeAggregation(encodeTDigestState(CAST('[(0,1),(1,1),(2,1),(3,1),(4,1),(5,1),(6,1),(7,1),(8,1),(9,1)]', 'Array(Tuple(Float32, Float32))'))) AS result

┌─result─┐
│      4 │
└────────┘
```
