### ISSUE TITLE
How to disable UDF concurrent calculation

### ISSUE THREAD

**Issue by zeropool** [ClickHouse/ClickHouse#41713]
The UDF I wrote needs to rely on the calculation results of the previous row. Debugging found that the clickhouse is executed concurrently. How can I let the clickhouse disable the concurrent execution feature and send all the row results to the UDF entry at once

**Comment by kitaisreal** [comment]
There is no easy way to disable concurrent execution completely. You can try to use `max_threads` = 1.
Another way is to use `executable` function type, and make serial execution on your side.
But you cannot rely on order of data that will be input for your UDF function (if you will not specify ORDER BY).
