### ISSUE TITLE
Exception: Column name in Block cannot be empty: while executing 'FUNCTION

### ISSUE THREAD

**Issue by abezverkhikh** [ClickHouse/ClickHouse#41727]
ClickHouse version 22.3.12.19

When I execute the following request
`
with c as (
	select 1 ID, today() dt, 0 p
)
select     
	multiIf(t.ID = 1, formatRowNoNewline('JSONEachRow', dd), '') AS params	
from (			
	select ID, case when p = 0 then toString(date_add(hour, p, dt)) else '2022-01-01' end as dd
	from c        
)  t
`

I get an error
`SQL Error [1002]: ClickHouse exception, code: 1002, host: host, port: 8123; Code: 352. DB::Exception: Column name in Block cannot be empty: while executing 'FUNCTION multiIf(equals(ID, 1) :: 0, formatRowNoNewline('JSONEachRow', dd) :: 8, '' :: 7) -> multiIf(equals(ID, 1), formatRowNoNewline('JSONEachRow', dd), '') String : 4'. (AMBIGUOUS_COLUMN_NAME) (version 22.3.12.19 (official build))
`

But if you add dd column, the query succeeds.

`
with c as (
	select 1 ID, today() dt, 0 p
)
select     
	multiIf(t.ID = 1, formatRowNoNewline('JSONEachRow', dd), '') AS params, dd
from (			
	select ID, case when p = 0 then toString(date_add(hour, p, dt)) else '2022-01-01' end as dd
	from c        
)  t
`

**Comment by sokolov-alexey** [comment]
I simplified the example to this:
```
select
    if(
        outer_table.condition_value = 1,
        formatRowNoNewline('JSONEachRow', outer_table.result_date),
        ''
    ) as json
from (
        select
            1 as condition_value,
            date_add(month, inner_table.offset, today()) as result_date
        from (
            select
                2 as offset
            ) inner_table
    ) outer_table
```
and it throws that exception in all versions up to the latest 22.10.

But when I add 
```
settings short_circuit_function_evaluation = 'disable'
```
exception disappears.

So the problem is somewhere in the depth of short circuit function optimization I guess.
