### ISSUE TITLE
`input_format_csv_use_best_effort_in_schema_inference` does not work as expected

### ISSUE THREAD

**Issue by DerekChia** [ClickHouse/ClickHouse#41735]
**Describe the unexpected behaviour**
Version 22.8

When using S3 table function to read in a bunch of CSVs through wildcard expression without providing schema hints, it can often fail due to ParsingException, such as `DB::ParsingException: Cannot parse number with a sign character but without any numeric character. (CANNOT_PARSE_NUMBER)`.

When this happens, if a user retries the same query with `SETTINGS input_format_csv_use_best_effort_in_schema_inference = 0` setting, the user will face the error again despite expecting ClickHouse not to infer any schema and [treat all fields as string](https://clickhouse.com/docs/en/operations/settings/settings/#input_format_csv_use_best_effort_in_schema_inference). It is suspected that the cache is already populated with the schema. 

In order to resolve the problem (without clearing any cache), user will need to apply two settings `input_format_csv_use_best_effort_in_schema_inference = 0` and `schema_inference_use_cache_for_s3 = 0` instead. 

As both `input_format_csv_use_best_effort_in_schema_inference` and `schema_inference_use_cache_for_s3` are turned on by default, it may not be intuitive for the user to look for `schema_inference_use_cache_for_s3` and turn it off. 

Another workaround is to run `SYSTEM DROP SCHEMA CACHE FOR S3` after the first failure and then set `input_format_csv_use_best_effort_in_schema_inference = 0`, but that still does not reflect what turning off `input_format_csv_use_best_effort_in_schema_inference` is always intended to do.

**How to reproduce**

First attempt will trigger the `ParsingException`
```
SELECT * FROM s3('https://BUCKET_NAME.s3.amazonaws.com/folder/*', 'ACCESS_KEY', 'SECRET_KEY', 'CSVWithNames');
```

Second attempt with `input_format_csv_use_best_effort_in_schema_inference = 0` will fail as well (same `ParsingException` error), something unexpected as user would expect all fields to be treated as string. 
```
SELECT * FROM s3('https://BUCKET_NAME.s3.amazonaws.com/folder/*', 'ACCESS_KEY', 'SECRET_KEY', 'CSVWithNames') 
SETTINGS input_format_csv_use_best_effort_in_schema_inference = 0;
```

Third attempt with both settings turn off will work
```
SELECT * FROM s3('https://BUCKET_NAME.s3.amazonaws.com/folder/*', 'ACCESS_KEY', 'SECRET_KEY', 'CSVWithNames') 
SETTINGS input_format_csv_use_best_effort_in_schema_inference = 0, schema_inference_use_cache_for_s3 = 0;
```

Third attempt after clearing cache will also work
```
SYSTEM DROP SCHEMA CACHE FOR S3
SELECT * FROM s3('https://BUCKET_NAME.s3.amazonaws.com/folder/*', 'ACCESS_KEY', 'SECRET_KEY', 'CSVWithNames') 
SETTINGS input_format_csv_use_best_effort_in_schema_inference = 0;
```

**Expected behavior**

Disabling `input_format_csv_use_best_effort_in_schema_inference` will treat all fields as string, in all cases, regardless of cache.
```
SELECT * FROM s3('https://BUCKET_NAME.s3.amazonaws.com/folder/*', 'ACCESS_KEY', 'SECRET_KEY', 'CSVWithNames') 
SETTINGS input_format_csv_use_best_effort_in_schema_inference = 0;
```

**Comment by DerekChia** [comment]
cc: @Avogar

**Comment by Avogar** [comment]
Ohh, I just realized that this problem happens because of stupid typo in the code. I will fix it. Thanks for the ping)
