### ISSUE TITLE
Insert data part finished but still large write IO into disk last for a period of time

### ISSUE THREAD

**Issue by LiuYangkuan** [ClickHouse/ClickHouse#41749]
**Describe the unexpected behaviour**
I use clickhouse-client to insert data into MergeTree table rapidly set max_insert_threads=16, and it returns quickly.
But there is still large write IO into disk last for a period of time even I stop merges.
So insert data finished and return without data persistent?

**Additional context**
My ClickHouse version is 22.8

**Comment by UnamedRus** [comment]
ClickHouse don't do fsync by default.


https://github.com/ClickHouse/ClickHouse/issues/10286

**Comment by alexey-milovidov** [comment]
@LiuYangkuan The IO load after data insertion is related to background merging.
