### ISSUE TITLE
Better query introspection 

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#41744]
**Use case**

Right now we have numerous of different possibilities to introspect single query:

Tables: (and id's of entity)
system.query_log (query_id)
system.query_thread_log (query_id, thread_id)
system.opentelemetry_span_log (query_id, thread_id, span_id, operation_name)
system.processors_profile_log (query_id, id, name)
system.trace_log (query_id, thread_id)

Queries:

EXPLAIN (AST/PLAN/PIPELINE/SYNTAX/ESTIMATES) SELECT .... (name)

Etc:
Trace logs: set send_logs_level='trace'; (query_id, thread_id, name)

And we have several problems here:
We can't easily correlate data from different sources:
IE, `system.processors_profile_log` table has column named `name`, but you can't map it easily to steps from: `EXPLAIN PLAN ...`

We can't easily aggregate the same step from multiple processors actions:
Example of graph from `system.processors_profile_log` table.

![image](https://user-images.githubusercontent.com/9449405/192090137-4a8a1dfe-d8f9-46c4-9fae-d997bf7e1d04.png)

Despite, that table has columns like plan_group, plan_step, they ATM doesn't provide all necessary information in order to group rows:
plan_group **is always** 0.
plan_step also 0, if previous action has multiple Transforms: (for example JoiningTransform, second ExpressionTransform, MergeTreeThread)

Some Transforms has meaning only for ClickHouse and doesn't really needed for people: *Resize.
They also should be grouped with corresponding Transforms.

Some plan steps doesn't have Transform: UNION

CTE can't be distinguished from subqueries in EXPLAIN PLAN 

**Describe the solution you'd like**

Add (another) explicit identifier, which will help with merging data from different sources. 
Because, there is no 1-1 mapping between steps from different sources, it should allow to generate id's in such way, that it's will include both group_id, (sub_group_id,) and step_id

**Comment by alexey-milovidov** [comment]
This task didn't get attention.

**Comment by UnamedRus** [comment]
Related https://github.com/ClickHouse/ClickHouse/pull/63518
