### ISSUE TITLE
Kafka engine table doesn't write data to the nodes of one shard of my clickhouse cluster

### ISSUE THREAD

**Issue by xinobu** [ClickHouse/ClickHouse#41759]
# Environment
ClickHouse server version:22.1.3.7

# Background
I have a clickhouse cluster with 6 nodes, configured with 2shards and 3replicas:
- shard1: cdh01, cdh02, cdh03
- shard2: cdh04, cdh05, cdh06

I use the sql below to read kafka data to replicated table on each node:
`CREATE TABLE network_2s_3r.t_ssolog_local ON CLUSTER bigdata
(
  id UInt64,
  ...
)
ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/cas_sso_logs/{shard}', '{replica}')
PARTITION BY toYYYYMMDD(timestamp)
ORDER BY (timestamp)
SETTINGS index_granularity = 8192`

`CREATE TABLE network_2s_3r.kafka_ssolog ON CLUSTER bigdata
(
  id UInt64,
 ...
) ENGINE = Kafka()
SETTINGS kafka_broker_list = 'cdh01:9092,cdh02:9092,cdh03:9092,cdh04:9092,cdh05:9092,cdh06:9092',
       kafka_topic_list = '{topic}',
       kafka_group_name = '{group}',
       kafka_format = 'JSONEachRow',
       kafka_skip_broken_messages = 100,
       kafka_num_consumers = 3;`

`CREATE MATERIALIZED VIEW network_2s_3r.mv_ssolog ON CLUSTER bigdata TO network_2s_3r.t_ssolog_local
AS SELECT
  id, ...
FROM network_2s_3r.kafka_ssolog;`
I have created tables with similar sqls before and they work well now. But from some time on, when I create the tables with the sql above, I meet the problem below.

# Problem
I execute
`select count() from t_ssolog_local` 
on each node, and found only nodes of shard1 have data, and on nodes of shard2(cdh04,cdh05, cdh06), I got 0. And the amount of data on shard1 is also seemed to be not correct.
I collected the logs on cdh04 as shown below.

> 2022.09.26 11:25:14.133734 [ 25036 ] {} <Trace> PushingToViews: Pushing (sequentially) from network_2s_3r.kafka_ssolog 
> (e59aad2e-cb48-4235-9a44-df488d386283) to network_2s_3r.mv_ssolog (b79bddaa-778a-4bf4-aa3c-06db861f9f17) took 0 ms.
> 2022.09.26 11:25:14.133923 [ 25036 ] {} <Trace> StorageKafka (kafka_ssolog): Nothing to commit.
> 2022.09.26 11:25:14.134011 [ 25036 ] {} <Trace> StorageKafka (kafka_ssolog): Nothing to commit.
> 2022.09.26 11:25:14.134034 [ 25036 ] {} <Debug> StorageKafka (kafka_ssolog): Pushing 0.00 rows to network_2s_3r.kafka_ssolog (e59aad2e-cb48-4235-9a44-df488d386283) took 7506 ms.
> 2022.09.26 11:25:14.136586 [ 25036 ] {} <Trace> StorageKafka (kafka_ssolog): Stream(s) stalled. Reschedule.
> 2022.09.26 11:25:14.136634 [ 25036 ] {} <Trace> StorageKafka (kafka_ssolog): Execution took 7509 ms.
> 2022.09.26 11:25:14.636801 [ 25036 ] {} <Debug> StorageKafka (kafka_ssolog): Started streaming to 1 attached views
> 2022.09.26 11:25:14.638965 [ 25036 ] {} <Trace> StorageKafka (kafka_ssolog): Already subscribed to topics: [source_sso_log]
> 2022.09.26 11:25:14.639016 [ 25036 ] {} <Trace> StorageKafka (kafka_ssolog): Already assigned to: [  ]
> 2022.09.26 11:25:15.139344 [ 25036 ] {} <Trace> StorageKafka (kafka_ssolog): Empty assignment.
> 2022.09.26 11:25:15.639787 [ 25036 ] {} <Trace> StorageKafka (kafka_ssolog): Empty assignment.
> 2022.09.26 11:25:16.140087 [ 25036 ] {} <Trace> StorageKafka (kafka_ssolog): Empty assignment.
> 2022.09.26 11:25:16.640361 [ 25036 ] {} <Trace> StorageKafka (kafka_ssolog): Empty assignment.
> 2022.09.26 11:25:17.140678 [ 25036 ] {} <Trace> StorageKafka (kafka_ssolog): Empty assignment.
> 2022.09.26 11:25:17.640972 [ 25036 ] {} <Trace> StorageKafka (kafka_ssolog): Empty assignment.
> 2022.09.26 11:25:18.141259 [ 25036 ] {} <Trace> StorageKafka (kafka_ssolog): Empty assignment.
> 2022.09.26 11:25:18.641544 [ 25036 ] {} <Trace> StorageKafka (kafka_ssolog): Empty assignment.
> 2022.09.26 11:25:19.141828 [ 25036 ] {} <Trace> StorageKafka (kafka_ssolog): Empty assignment.
> 2022.09.26 11:25:19.642126 [ 25036 ] {} <Trace> StorageKafka (kafka_ssolog): Empty assignment.
> 2022.09.26 11:25:19.642315 [ 25036 ] {} <Trace> StorageKafka (kafka_ssolog): Already subscribed to topics: [source_sso_log]
> 2022.09.26 11:25:19.642340 [ 25036 ] {} <Trace> StorageKafka (kafka_ssolog): Already assigned to: [  ]
> 2022.09.26 11:25:20.142679 [ 25036 ] {} <Trace> StorageKafka (kafka_ssolog): Empty assignment.
> 2022.09.26 11:25:20.642986 [ 25036 ] {} <Trace> StorageKafka (kafka_ssolog): Empty assignment.
> 2022.09.26 11:25:21.143279 [ 25036 ] {} <Trace> StorageKafka (kafka_ssolog): Empty assignment.
> 2022.09.26 11:25:21.643566 [ 25036 ] {} <Trace> StorageKafka (kafka_ssolog): Empty assignment.
> 2022.09.26 11:25:22.143861 [ 25036 ] {} <Trace> StorageKafka (kafka_ssolog): Empty assignment.

I checked the consumer group and got, no errors are found in kafka server logs :
> school_data     source_sso_log         0          12858648        12858648        0               ClickHouse-cdh01-network_2s_3r-kafka_ssolog-0-fabc460c-a0ee-459c-9516-41d4c31c25aa        /10.251.1.22    ClickHouse-cdh01-network_2s_3r-kafka_ssolog-0
> school_data     source_sso_log         2          12494450        12494450        0               ClickHouse-cdh01-network_2s_3r-kafka_ssolog-2-6cc3a26d-e222-439a-8b22-677083967c3b        /10.251.1.22    ClickHouse-cdh01-network_2s_3r-kafka_ssolog-2
> school_data     source_sso_log         1          12855865        12855865        0               ClickHouse-cdh01-network_2s_3r-kafka_ssolog-1-4effdb46-d33a-46a5-8375-ad3dd10163ec        /10.251.1.22    ClickHouse-cdh01-network_2s_3r-kafka_ssolog-1

**Comment by xinobu** [comment]
I restart the clickhouse servers and get err logs on the nodes of shard 1(cdh01-03) as follows, seems like it can not connect to the nodes of shard2.
> : While sending /data/clickhouse/store/da8/da80bfd4-7a20-489a-b867-4f7a93399920/shard2_all_replicas/1.bin. (ALL_CONNECTION_TRIES_FAILED), Stack trace (when copying this message, always include the lines below):
> 
> 0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa82d07a in /usr/bin/clickhouse
> 1. PoolWithFailoverBase<DB::IConnectionPool>::getMany(unsigned long, unsigned long, unsigned long, unsigned long, bool, std::__1::function<PoolWithFailoverBase<DB::IConnectionPool>::TryResult (DB::IConnectionPool&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)> const&, std::__1::function<unsigned long (unsigned long)> const&) @ 0x145327bb in /usr/bin/clickhouse
> 2. PoolWithFailoverBase<DB::IConnectionPool>::get(unsigned long, bool, std::__1::function<PoolWithFailoverBase<DB::IConnectionPool>::TryResult (DB::IConnectionPool&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)> const&, std::__1::function<unsigned long (unsigned long)> const&) @ 0x1453033f in /usr/bin/clickhouse
> 3. DB::ConnectionPoolWithFailover::get(DB::ConnectionTimeouts const&, DB::Settings const*, bool) @ 0x14530230 in /usr/bin/clickhouse
> 4. DB::StorageDistributedDirectoryMonitor::processFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x14193e05 in /usr/bin/clickhouse
> 5. DB::StorageDistributedDirectoryMonitor::run() @ 0x1418fa78 in /usr/bin/clickhouse
> 6. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x12f8470e in /usr/bin/clickhouse
> 7. DB::BackgroundSchedulePool::threadFunction() @ 0x12f870a7 in /usr/bin/clickhouse
> 8. ? @ 0x12f88170 in /usr/bin/clickhouse
> 9. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa86f4b7 in /usr/bin/clickhouse
> 10. ? @ 0xa872ebd in /usr/bin/clickhouse
> 11. start_thread @ 0x76db in /lib/x86_64-linux-gnu/libpthread-2.27.so
> 12. /build/glibc-uZu3wS/glibc-2.27/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:97: clone @ 0x12161f in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.27.so
>  (version 22.1.3.7 (official build))
> 2022.09.28 13:21:35.291411 [ 35082 ] {} <Warning> ConnectionPoolWithFailover: Connection failed at try №1, reason: Code: 210. DB::NetException: Connection refused (cdh06:9000). (NETWORK_ERROR) (version 22.1.3.7 (official build))
> 2022.09.28 13:21:35.291931 [ 35082 ] {} <Warning> ConnectionPoolWithFailover: Connection failed at try №1, reason: Code: 210. DB::NetException: Connection refused (cdh04:9000). (NETWORK_ERROR) (version 22.1.3.7 (official build))
> 2022.09.28 13:21:35.292482 [ 35082 ] {} <Warning> ConnectionPoolWithFailover: Connection failed at try №1, reason: Code: 210. DB::NetException: Connection refused (cdh05:9000). (NETWORK_ERROR) (version 22.1.3.7 (official build))
> 2022.09.28 13:21:35.292836 [ 35082 ] {} <Error> network_2s_3r.t_dhcp_all.DirectoryMonitor: Code: 279. DB::NetException: All connection tries failed. Log:
> 
> Code: 210. DB::NetException: Connection refused (cdh06:9000). (NETWORK_ERROR) (version 22.1.3.7 (official build))
> Code: 210. DB::NetException: Connection refused (cdh04:9000). (NETWORK_ERROR) (version 22.1.3.7 (official build))
> Code: 210. DB::NetException: Connection refused (cdh05:9000). (NETWORK_ERROR) (version 22.1.3.7 (official build))

**Comment by xinobu** [comment]
Are there workarounds and solutions? The problem has blocked the progress of my task.

**Comment by filimonov** [comment]
You have a connectivity issue + you use old and unsupported version of clickhouse

shard2_all_replicas:
Connection refused (cdh06:9000).
Connection refused (cdh04:9000).
Connection refused (cdh05:9000).
