### ISSUE TITLE
ClickHouse version 21.12.4.1 use BACKUP table async

### ISSUE THREAD

**Issue by hbzhu** [ClickHouse/ClickHouse#41758]
ClickHouse version 21.12.4.1 

BACKUP database default  TO Disk('backups', 'backup-20220926/') ASYNC

Code: 62. DB::Exception: Syntax error: failed at position 115 ('ASYNC'): ASYNC. Expected one of: FILTER, OVER, SETTINGS, end of query. (SYNTAX_ERROR) (version 21.12.4.1 (official build))

**Comment by den-crane** [comment]
`BACKUP database` command is available in the later releases. You need to upgrade to 22.9.

**Comment by hbzhu** [comment]
Thanks，asynchronous backup tables need to upgrade to 22.9 to？

**Comment by den-crane** [comment]
> Thanks，asynchronous backup tables need to upgrade to 22.9 to？

Yes.

**Comment by hbzhu** [comment]
Thank you very much,I upgrated to 22.9.2.7,BACKUP commond  very nice!!!
