### ISSUE TITLE
Getting error of UNKNOWN FUNCTION UNIQSTATE while creating materialized view

### ISSUE THREAD

**Issue by piyushaggarwal10** [ClickHouse/ClickHouse#41764]
I am creating a materialized view using aggregated merge tree engine:

create materialized view m1
engine=AggregatingMergeTree()
partition by date
order by (date,name,class,section,subsection,v1,s1)
AS
SELECT
        date as date,name,class,section,subsection,
        uniqState(vector) as "v1",
        uniqState(sno.) as "s1"
    
from students
group by (date,name,class,section,subsection,v1,s1)

I am getting error as : "Unknown function uniqState. (UNKNOWN_FUNCTION) (version 22.2.2.1)"

If i remove v1 and s1 from the group by and order by clause then the view is corrupted with garbage value so i have to include them.

**Comment by den-crane** [comment]
because of `( )` in groupby

try

```sql
create materialized view m1
engine=AggregatingMergeTree()
partition by date
order by (date,name,class,section,subsection,v1,s1)
AS
SELECT
date as date,name,class,section,subsection,
uniqState(vector) as "v1",
uniqState(sno.) as "s1"

from students
group by date,name,class,section,subsection,v1,s1
```

**Comment by piyushaggarwal10** [comment]
tried    group by date,name,class,section,subsection,v1,s1

But still getting the same error of UNKNOWN FUNCTION DISTINCT

**Comment by piyushaggarwal10** [comment]
Create table students
`date` Date,
`name` String,
'class' string,
'section' string,
'subsection' string,
'vector' string.
'sno.' string

engine=MergeTree
partition by date
order by (date,vector,sno.)

**Comment by piyushaggarwal10** [comment]
i want to the output of both the following queries to be the same

{
     select date,uniq(vector)
     from students
     where class='tenth'
     group by date
}


{
   select date,uniqMerge(v1)
   from m1
   where class='tenth'
   group by date
}

But at present i am not getting same result

**Comment by den-crane** [comment]
1. You need to use backticks or double quotes for `sno.` column

2. You should not include `uniqState` -- aggregate functions into groupby and table ORDERBY

```sql
create table students(
date Date,
name String,
class String,
section String,
subsection String,
vector String,
`sno.` String
)
engine=MergeTree
partition by date
order by (date,vector,`sno.`)


create materialized view m1
engine=AggregatingMergeTree()
partition by date
order by (date,name,class,section,subsection)
AS
SELECT date as date,name,class,section,subsection,
uniqState(vector) as "v1",
uniqState(`sno.`) as "s1"
from students
group by date,name,class,section,subsection
```

**Comment by piyushaggarwal10** [comment]
i created a view without using both v1 and s1 in the order by clause but then the view is storing garbage values in these columns and i am not getting correct result while querying.

**Comment by piyushaggarwal10** [comment]
create materialized view m1
engine=AggregatingMergeTree()
partition by date
order by (date,name,class,section,subsection)
AS
SELECT date as date,name,class,section,subsection,
uniqState(vector) as "v1",
uniqState(sno.) as "s1"
from students
group by date,name,class,section,subsection


created this view but it is storing garbage values in v1 and s1 columns and when i query there is discrepancy

**Comment by den-crane** [comment]
>created this view but it is storing garbage values in v1 and s1 columns and when i query there is discrepancy

Provide an insert and select queries with examples.

**Comment by piyushaggarwal10** [comment]
insert into students
values ('2022-06-01' , 'sam' , 'tenth' , 'a' , ' ' , 'a1stu' , 'a1' )
values('2022-06-01' , 'Tina' , 'tenth' , 'b' , ' ' , b2stu' , 'b2' )
values('2022-06-01' , 'Ram' , 'tenth' , 'a' , ' ' , 'a3stu' , 'a3' )
values('2022-06-01' , 'gaurav' , 'ninth' , 'b' , ' ' , 'b2stu' , 'b2' )
values('2022-06-01' , 'Bob' , 'tenth' , 'a' , ' ' , 'a4stu' , 'a4' )
values('2022-06-01' , 'Anjali' , 'tenth' , 'b' , ' ' , 'b5stu' , 'b5' )
values('2022-06-01' , 'vishesh' , 'ninth' , 'b' , ' ' , 'b5stu' , 'b5' )
values('2022-06-01' , 'aditya' , 'tenth' , 'a' , ' ' , 'a6stu' ,  'a6' )
values('2022-06-01' , 'vishesh' , 'ninth' , 'a' , ' ' , 'a6stu' , 'a6' )



select date,uniq(vector)
from students
group by date

**Comment by piyushaggarwal10** [comment]
2022-06-01	��Q	\0\'��D	\0ג;�
2022-06-01	0�ZK4	\0J�&V	\0\r$J 
.
.

The view in which v1 and s1 are not there in the group by and order by clause gives the above output when i query

select date,v1,s1
from m1
group by date

**Comment by den-crane** [comment]
```sql
insert into students
              values
              ('2022-06-01' , 'sam' ,    'tenth' , 'a' , ' ' , 'a1stu' , 'a1' )
              ('2022-06-01' , 'Tina' ,   'tenth' , 'b' , ' ' , 'b2stu' , 'b2' )
              ('2022-06-01' , 'Ram' ,    'tenth' , 'a' , ' ' , 'a3stu' , 'a3' )
              ('2022-06-01' , 'gaurav' , 'ninth' , 'b' , ' ' , 'b2stu' , 'b2' )
              ('2022-06-01' , 'Bob' ,    'tenth' , 'a' , ' ' , 'a4stu' , 'a4' )
              ('2022-06-01' , 'Anjali',  'tenth' , 'b' , ' ' , 'b5stu' , 'b5' )
              ('2022-06-01' , 'vishesh', 'ninth' , 'b' , ' ' , 'b5stu' , 'b5' )
              ('2022-06-01' , 'aditya' , 'tenth' , 'a' , ' ' , 'a6stu' , 'a6' )
              ('2022-06-01' , 'vishesh', 'ninth' , 'a' , ' ' , 'a6stu' , 'a6' );

select date,uniq(vector)
              from students
              group by date;
┌───────date─┬─uniq(vector)─┐
│ 2022-06-01 │            6 │
└────────────┴──────────────┘

select date,uniqMerge(v1)
              from m1
              group by date;
┌───────date─┬─uniqMerge(v1)─┐
│ 2022-06-01 │             6 │
└────────────┴───────────────┘


select date,name,class,section,subsection, finalizeAggregation(v1) from m1;
┌───────date─┬─name────┬─class─┬─section─┬─subsection─┬─finalizeAggregation(v1)─┐
│ 2022-06-01 │ Anjali  │ tenth │ b       │            │                       1 │
│ 2022-06-01 │ Bob     │ tenth │ a       │            │                       1 │
│ 2022-06-01 │ Ram     │ tenth │ a       │            │                       1 │
│ 2022-06-01 │ Tina    │ tenth │ b       │            │                       1 │
│ 2022-06-01 │ aditya  │ tenth │ a       │            │                       1 │
│ 2022-06-01 │ gaurav  │ ninth │ b       │            │                       1 │
│ 2022-06-01 │ sam     │ tenth │ a       │            │                       1 │
│ 2022-06-01 │ vishesh │ ninth │ a       │            │                       1 │
│ 2022-06-01 │ vishesh │ ninth │ b       │            │                       1 │
└────────────┴─────────┴───────┴─────────┴────────────┴─────────────────────────┘

```

**Comment by piyushaggarwal10** [comment]
The queries with uniqMerge are working for me if say i have 1000 rows but in my case i have millions of rows in my 
table and after querying uniqMerge(v1) from the mview  i am getting error of close to 15%.
So is there any way by which i can eliminate the error?
