### ISSUE TITLE
Ramifications and status of 'Separation of Storage and Compute' (mentioned in 2022 Roadmap)

### ISSUE THREAD

**Issue by tasdflkjweio** [ClickHouse/ClickHouse#41791]
Per the [2022 Roadmap](https://github.com/ClickHouse/ClickHouse/issues/32513), a goal is to separate storage from compute. If it's what I think it is, it would mean we can dynamically scale the ClickHouse server horizontally, effectively meaning the compute is stateless. Storage then becomes the point of contention, so I could use some high-throughput, replicated managed disk offering. Is this the goal? 

I'm in the process of migrating our environment to Azure, and would love to configure ClickHouse in this way. Has this feature been completed and, if so, is there any documentation on it? To set this up, would it be just another engine type?

As an aside, I'm very excited about the phenomenal work you've been putting into ClickHouse. Thank you for your commitment to making such a high-quality product!

**Comment by DerekChia** [comment]
hey @tasdflkjweio ClickHouse already support the usage of S3 and HDFS as table engine. By using them, you are effectively separating compute and storage, and you can scale either of them independently. 

Reference: 
- https://clickhouse.com/docs/en/engines/table-engines/integrations/s3
- https://clickhouse.com/docs/en/engines/table-engines/integrations/hdfs

**Comment by DerekChia** [comment]
You can check out the changelog page for 2022 [here](https://clickhouse.com/docs/en/whats-new/changelog/) and correlate the relevant updates.

For example, I spotted several features, fixes and performance improvements related to "parallel reads" (first point under Separation of Storage and Compute). Just search for the word "parallel" on that page and have fun reading!

**Comment by tasdflkjweio** [comment]
I'd already looked through the changelog, but it doesn't answer the question of what the _intent_ for roadmap item is. My question was aimed at what is the goal/feature being developed. It's difficult to gleam that from a bunch of commits, which may be minor steps along the way to some broader objective.

**Comment by tasdflkjweio** [comment]
I guess no clarity will be given

**Comment by chloro-pn** [comment]
> I guess no clarity will be given

Maybe this can help you, if you can understand Chinese

https://github.com/cloudnativecube/octopus/issues/48
