### ISSUE TITLE
Implement SYSTEM DROP DATABASE REPLICA

### ISSUE THREAD

**Issue by tsolodov** [ClickHouse/ClickHouse#41794]
**Describe the unexpected behaviour**
SYSTEM DROP REPLICA '_REPLICA_NAME_' does remove data under:
`/clickhouse/tables/*/default/replicas/_REPLICA_NAME_`
but it does not under:
`/clickhouse/databases/_DB_NAME/replicas/_DB_NAME|_REPLICA_NAME_/`

Could you please fix or add additional option to delete data under `/clickhouse/databases/_DB_NAME/replicas/_DB_NAME|_REPLICA_NAME_/`

**Comment by tsolodov** [comment]
> 



> What is `replicas/_DB_NAME|_REPLICA_NAME_/` ?
> 
> In your case `_REPLICA_NAME_` = `_DB_NAME|_REPLICA_NAME_` ?

I guess it is related to replicated database engine, in ZK you will see

`/XXXX/databases/_DB_NAME_/replicas/_DB_NAME| REPLICA_NAME_`

**Comment by tavplubix** [comment]
It works as expected, `SYSTEM DROP REPLICA` removes metadata of `ReplicatedMergeTree` tables and it's not related to `Replicated` databases. Another command for removing metadata of `Replicated` databases should be implemented.
