### ISSUE TITLE
Why ClickHouse Keeper doesn't support multi-raft?

### ISSUE THREAD

**Issue by zk-kiger** [ClickHouse/ClickHouse#41815]
At present, Keeper saves the full amount of data. Can it support multi-raft to improve the write performance bottleneck?

**Comment by antonio2368** [comment]
Have in mind that the development of Keeper started relatively recently.
Multi-raft is a great thing to have to improve the write performance but for now, there are many different things that need to be solved that are more critical (+ we need to work on improving single cluster performance then we can start to talk about scaling it better).
Add to that many different usability features for Keeper (mostly interaction with it) and the complexity itself of implementing multi-raft and you should see why it isn't on top of our list right now.

Having said all of that, I also think that it would be nice to add support for multi-raft and agree that it should be implemented at some point.
