### ISSUE TITLE
Flaky test `02122_join_group_by_timeout`

### ISSUE THREAD

**Issue by antonio2368** [ClickHouse/ClickHouse#41820]
https://s3.amazonaws.com/clickhouse-test-reports/41730/8cc53a48ae99a765085f44a75fa49314d1f1cc7d/stateless_tests__debug__s3_storage__[1/3].html

It seems it fails to send exception in the expected time (5s). 
The execution timeout is detected in those 5 seconds, but it tries to send it to the client 4-5 seconds later when the client is already killed.
I can try increasing the waiting to 10 sec but it's strange that it started to fail recently.

**Comment by tavplubix** [comment]
Related to https://github.com/ClickHouse/ClickHouse/pull/41253
Seems like settings randomization was not the only reason
cc: @kssenii

**Comment by alexey-milovidov** [comment]
Not fixed: https://s3.amazonaws.com/clickhouse-test-reports/60197/b738928c34da78c009f89968450947a6c09a4d49/stateless_tests__asan__[1_2].html
