### ISSUE TITLE
Higher memory usage after update

### ISSUE THREAD

**Issue by aubweb9** [ClickHouse/ClickHouse#41841]
Hello,

I recently updated our staging env. from 22.3.2.1 to 22.9.2.7.

Since the update I have a lot of queries that fails with the below error message 
```
HttpCode:500 ;  ;Code: 241. DB::Exception: Memory limit (total) exceeded: would use 31.87 GiB (attempt to allocate chunk of 4194496 bytes), maximum: 28.27 GiB. OvercommitTracker decision: Query was selected to stop by OvercommitTracker.: While executing ConvertingAggregatedToChunksSource. (MEMORY_LIMIT_EXCEEDED) (version 22.9.2.7 (official build))
```

The exact same query was working fine prior the update and it's still running well on the production env which is still on 22.3.2.1.

If I run this on staging 
```
SELECT event_date,  formatReadableSize(avg(memory_usage)), avg(result_rows) , avg(read_rows), avg(written_rows)
FROM system.query_log
WHERE event_date >= toDate('2022-29-26')
GROUP BY event_date;
``` 
event_date|formatReadableSize(avg(memory_usage))|avg(result_rows)  |avg(read_rows)   |avg(written_rows) |
----------+-------------------------------------+------------------+-----------------+------------------+
2022-09-26|120.24 MiB                           |10067.476594407792|5570701.956880301|10426.689836632107|
2022-09-27|170.46 MiB                           | 9449.651763022182|3134934.810175932| 8972.480075011721|

the same on production :

event_date|formatReadableSize(avg(memory_usage))|avg(result_rows)  |avg(read_rows)    |avg(written_rows)|
----------+-------------------------------------+------------------+------------------+-----------------+
2022-09-26|42.38 MiB                            |11861.727904185094|18832358.821041428|9904.608121937992|
2022-09-27|43.38 MiB                            |12148.634991901115| 19044619.46424958|9974.605479459236|

I also had to turn off the enable_positional_arguments as it was breaking some queries.

Here are my custom settings : 
```
<clickhouse>
        <profiles>
               <default>
                        <external_storage_rw_timeout_sec>301</external_storage_rw_timeout_sec>
                        <external_storage_connect_timeout_sec>30</external_storage_connect_timeout_sec>
                        <enable_http_compression>1</enable_http_compression>
                        <load_balancing>random</load_balancing>
                        <max_partitions_per_insert_block>1000</max_partitions_per_insert_block>
                        <max_memory_usage>160000000000</max_memory_usage>
                        <enable_positional_arguments>0</enable_positional_arguments>
                </default>
        </profiles>
</clickhouse>
```
Server memory : 
```
free -m
              total        used        free      shared  buff/cache   available
Mem:          32160       14851        4464          44       12844       17658
Swap:          1023         357         666
```

Is there anything in the settings that could have changed after the update ? 

Thanks,
Aubry

**Comment by den-crane** [comment]
>Is there anything in the settings that could have changed after the update ?

No, nothing.


>The exact same query was working fine prior the update and it's still running well on the production env which is still on 

Please provide reproducible example.

>I also had to turn off the enable_positional_arguments as it was breaking some queries.

Please provide reproducible example.

**Comment by aubweb9** [comment]
Hi Den,
Please find the query and log from system for both staging & prod env + query and ddl of destination table
The same query takes 1.8G on prod while on staging is taking 15.06G

[NFO from query log ON PRODUCTION ENV.txt](https://github.com/ClickHouse/ClickHouse/files/9657819/NFO.from.query.log.ON.PRODUCTION.ENV.txt)

[failing_query.txt](https://github.com/ClickHouse/ClickHouse/files/9657834/failing_query.txt)

[INFO from query log ON STAGING ENV.txt](https://github.com/ClickHouse/ClickHouse/files/9657835/INFO.from.query.log.ON.STAGING.ENV.txt)

**Comment by alexey-milovidov** [comment]
@den-crane, please find the attached logs above.

**Comment by alexey-milovidov** [comment]
@den-crane, you didn't analyze the logs, but almost one year has passed. Closing.
