### ISSUE TITLE
CI tasks are not restarted if runner was killed

### ISSUE THREAD

**Issue by tavplubix** [ClickHouse/ClickHouse#41850]
Example: https://github.com/ClickHouse/ClickHouse/pull/41509#issuecomment-1252304872

Another example:
https://github.com/ClickHouse/ClickHouse/actions/runs/3135207711/jobs/5095593603
https://s3.amazonaws.com/clickhouse-test-reports/41796/19062e9d9743f6a926d24fa26abe1f3b56cd2354/performance_comparison_[1/4]/compare.log

**Comment by Felixoid** [comment]
The tests don't restart if the commit statuses are created. For some tests, it's done intentionally to not burn the processors.

It's done intentionally, but we can discuss what we can improve here.

**Comment by Felixoid** [comment]
https://github.com/ClickHouse/ClickHouse/actions/runs/3084878093/jobs/4989156470#step:7:3876 - not sure what happened there, the logs are trimmed, unfortunately. But it looks like python still sent the data to s3 and created the status, so we don't run the job again on the following restarts.

For performance comparison it's the same, the status was created https://github.com/ClickHouse/ClickHouse/actions/runs/3135207711/jobs/5092102127#step:7:3874. But here the runner is went south  
![image](https://user-images.githubusercontent.com/3025537/192653002-d6803ac4-1627-4d38-8ee4-c915f378d028.png)

Not sure yet what happens with performance tests, here's the same https://github.com/ClickHouse/ClickHouse/actions/runs/3130890720/attempts/1

**Comment by Felixoid** [comment]
Recently I've posted the solution in slack, so it would help in such cases

> the command `gh api repos/ClickHouse/ClickHouse/statuses/{{commit}} -X POST -F state=pending -F description="Manually unset to rerun" -F context="{{failed status name}}"` will mark the `{{failed status name}}` as pending, and rerun helper will consider it as non-finished. It should help with tests like integration and functional

When a leather bug is 100% sure that the task should be restarted

**Comment by tavplubix** [comment]
Manually restarting checks is not a proper solution. I would better ignore failure like this, mention you again and merge rather than run some obscure command to manually restart check and wait a few hours more for restarted check to finish. 

> But it looks like python still sent the data to s3 and created the status, so we don't run the job again on the following restarts.

It looks like a bug in our python code that runs checks and posts statuses, isn't it? Should we try to debug it?

Another question: is it possible to automatically execute this command and restart check (from some lambda or whatever) if a task failed with trimmed logs?

**Comment by Felixoid** [comment]
> Manually restarting checks is not a proper solution.

In this particular case, I'd rather argue. The issue here is the order in which the `shut down` sends the signals to working processes. If docker died fast enough, and then python has enough time, it will finish its own tasks. It's my speculative assumption, but it explains the result.

> It looks like a bug in our python code that runs checks and posts statuses, isn't it? Should we try to debug it?

Not sure how unfortunately. The best thing that comes to my mind is shutting down the hosts. Do you have something too?

> I would better ignore failure like this, mention you again and merge rather than run some obscure command to manually restart check and wait a few hours more for restarted check to finish.

I'd then provide the command once again to show, how to restart it in rarely failing cases. We don't have a relation `failing status to failing job` unfortunately. Because of that, the task of writing a lambda is not a day, but some refactoring of the whole infrastructure. That would be an answer to the latest question.

**Comment by tavplubix** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/44160/db7f2ed42b315db28877964bc3f7b0877347ac83/stress_test__tsan_.html

**Comment by tavplubix** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/44157/d54f739836fa998f0e32458bcaf3dad545e25526/stress_test__msan_.html

**Comment by Felixoid** [comment]
Both died on timeout 
![image](https://user-images.githubusercontent.com/3025537/207369921-28b05992-2bb5-4cc6-901f-76917cb7d84e.png)

**Comment by Felixoid** [comment]
ok, I mean, the task is for sure finished. Or do you say it is killed, but the status is posted?

I think. we can set the timeout here https://github.com/ClickHouse/ClickHouse/blob/master/tests/ci/stress_check.py#L148

according to the [query](https://play.clickhouse.com/play?user=play&url=https%3A%2F%2Fplay.clickhouse.com%2F#U0VMRUNUICogRlJPTSBjaGVja3MgV0hFUkUgY2hlY2tfbmFtZSBMSUtFICdTdHJlc3MlJwpPUkRFUiBCWSBjaGVja19zdGFydF90aW1lIERFU0M=), something around 2.5h looks like a reasonable ceiling to me

**Comment by tavplubix** [comment]
Seems like I found another example: https://s3.amazonaws.com/clickhouse-test-reports/44466/8cdb5d9ae170c5365f885c9b7619dc38ff4e9db5/stress_test__tsan_.html

[Attempt 2](https://github.com/ClickHouse/ClickHouse/actions/runs/3831396965/attempts/2) - [StressTestTsan](https://github.com/ClickHouse/ClickHouse/actions/runs/3831396965/jobs/6523000981) failed in 1h 26m 54s, because spot instance was killed (`The self-hosted runner: i-078c873b6bfaa94b4 lost communication with the server...`). Seems like it uploaded some logs, but the task was not completely finished
Attempt 3 - [StressTestTsan](https://github.com/ClickHouse/ClickHouse/actions/runs/3831396965/jobs/6525008679) does nothing because `INFO:root:Check is already finished according to github status, exiting`

As a result, we got the incomplete task with incomplete logs, `check_status.tsv doesn't exists` status and red cross. Also there's something weird in run.log, so it can be a bug in github actions:
```
2023-01-04 01:39:25,575 Finished 11 from 16 processes

API: SYSTEM()
Time: 22:39:42 UTC 01/03/2023
DeploymentID: 2441ba39-a7bf-4f90-9d6f-77d5cea302e3
Error: Operation timed out (cmd.OperationTimedOut)
       2: cmd/data-scanner.go:152:cmd.runDataScanner()
       1: cmd/data-scanner.go:76:cmd.initDataScanner.func1()

API: PutObject(bucket=test, object=test/rww/fhwqdbcyvdnvuqjierlnbslayedqx)
Time: 22:39:42 UTC 01/03/2023
DeploymentID: 2441ba39-a7bf-4f90-9d6f-77d5cea302e3
RequestID: 1736EC1A9D881277
RemoteHost: ::1
Host: localhost:11111
UserAgent: aws-sdk-cpp/1.8.121/S3/Linux/5.15.0-1023-aws x86_64 Clang/15.0.6
Error: Operation timed out (cmd.OperationTimedOut)
       3: cmd/fs-v1.go:1002:cmd.(*FSObjects).PutObject()
       2: cmd/object-handlers.go:1798:cmd.objectAPIHandlers.PutObjectHandler()
       1: net/http/server.go:2047:http.HandlerFunc.ServeHTTP()
2023-01-04 01:39:47,089 All processes finished
2023-01-04 01:39:47,089 Compressing stress logs
2023-01-04 01:39:48,187 Logs compressed
2023-01-04 01:39:48,187 Stress test finished
+ echo -e 'Backward compatibility check: Test script exit code\tOK'
```

**Comment by Felixoid** [comment]
![image](https://user-images.githubusercontent.com/3025537/211674627-04662ff4-5461-42ce-a64e-a41f74bb7d09.png)
The mentioned attempt 2 failed at 11:03+0100 on Jan 3

![image](https://user-images.githubusercontent.com/3025537/211674810-7a2f47d9-4b7f-4829-a73e-b445fc2a110e.png)


The runners are written in .NET, and the stack from logs is go-related. It looks like it's something wrong with container, since the runner worked for 1 day more after that

**Comment by Felixoid** [comment]
Should be addressed in #49283.

Besides that, we haven't seen it for long

**Comment by tavplubix** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/52519/695d5cd5e55388ec34548cab0cd5e535fe0240f3/stress_test__ubsan_.html

**Comment by Felixoid** [comment]
Sorry, I can't investigate it. The [job_logs.txt](https://github.com/ClickHouse/ClickHouse/files/12226787/job_logs.txt) shows that the job itself was cancelled, and the summary shows the next message `The self-hosted runner: i-0b9317a049e63c7ba lost communication with the server. Verify the machine is running and has a healthy network connection. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error.`

But unfortunately, we have only 3 days of logs in CloudWatch, so they are already devnulled

**Comment by alexey-milovidov** [comment]
I've raised this issue multiple times, but all the time, it was considered non-fixable.
