### ISSUE TITLE
runtime error: shift exponent 64 is too large for 64-bit type 'DB::UInt64' (aka 'unsigned long')

### ISSUE THREAD

**Issue by yakov-olkhovskiy** [ClickHouse/ClickHouse#41859]
**Describe the bug**
https://s3.amazonaws.com/clickhouse-test-reports/41743/ff8c74800d261d0659a179c6924bf9d8042e7e2b/fuzzer_astfuzzerubsan//report.html

../src/Columns/ColumnVector.h:407:1: runtime error: shift exponent 64 is too large for 64-bit type 'DB::UInt64' (aka 'unsigned long') Received signal -3 Received signal Unknown signal (-3)

**Comment by alexey-milovidov** [comment]
@yakov-olkhovskiy There is no such line of code in the master branch.

**Comment by alexey-milovidov** [comment]
Yes, I reverted it.

**Comment by alexey-milovidov** [comment]
#41797
#41752
