### ISSUE TITLE
QUERY_WITH_SAME_ID_IS_ALREADY_RUNNING

### ISSUE THREAD

**Issue by muratferdi** [ClickHouse/ClickHouse#41869]
ClickHouse version 22.9.2.7 (official build)
Intel Xeon CPU E5-2650 - 250 GB Ram
100 Column Table with 4 Billion rows

Source Database  MSSQL 2019
Used Program Pentaho - Spoon 9.2
clickhouse-Jdbc-0.3.2-patch7-all
mssql-jdbc-10.2.0.jre8
Commit Size 10.000 in pentaho table output

2022/09/28 03:12:54 - send_to_job.0 - ERROR (version 9.2.0.0-290, build 9.2.0.0-290 from 2021-06-02 06.36.08 by buildguy) : Because of an error, this step can't continue:
2022/09/28 03:12:54 - send_to_job.0 - ERROR (version 9.2.0.0-290, build 9.2.0.0-290 from 2021-06-02 06.36.08 by buildguy) : org.pentaho.di.core.exception.KettleException: 
2022/09/28 03:12:54 - send_to_job.0 - Error batch inserting rows into table [TABLE_FULL].
2022/09/28 03:12:54 - send_to_job.0 - Errors encountered (first 10):
2022/09/28 03:12:54 - send_to_job.0 - 
2022/09/28 03:12:54 - send_to_job.0 - 
2022/09/28 03:12:54 - send_to_job.0 - Error updating batch
2022/09/28 03:12:54 - send_to_job.0 - Code: 216. DB::Exception: Query with id = 3f5bb847-a8cd-4af4-91c6-bf68c06036c2 is already running. (QUERY_WITH_SAME_ID_IS_ALREADY_RUNNING) (version 22.9.2.7 (official build))
, server ClickHouseNode(addr=http:71.71.71.187:8123, db=default)@-702972333
2022/09/28 03:12:54 - send_to_job.0 - 
2022/09/28 03:12:54 - send_to_job.0 - 
2022/09/28 03:12:54 - send_to_job.0 - 	at org.pentaho.di.trans.steps.tableoutput.TableOutput.writeToTable(TableOutput.java:348)
2022/09/28 03:12:54 - send_to_job.0 - 	at org.pentaho.di.trans.steps.tableoutput.TableOutput.processRow(TableOutput.java:125)
2022/09/28 03:12:54 - send_to_job.0 - 	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
2022/09/28 03:12:54 - send_to_job.0 - 	at java.lang.Thread.run(Unknown Source)
2022/09/28 03:12:54 - send_to_job.0 - Caused by: org.pentaho.di.core.exception.KettleDatabaseBatchException: 
2022/09/28 03:12:54 - send_to_job.0 - Error updating batch
2022/09/28 03:12:54 - send_to_job.0 - Code: 216. DB::Exception: Query with id = 3f5bb847-a8cd-4af4-91c6-bf68c06036c2 is already running. (QUERY_WITH_SAME_ID_IS_ALREADY_RUNNING) (version 22.9.2.7 (official build))
, server ClickHouseNode(addr=http:71.71.71.187:8123, db=default)@-702972333
2022/09/28 03:12:54 - send_to_job.0 - 
2022/09/28 03:12:54 - send_to_job.0 - 	at org.pentaho.di.core.database.Database.createKettleDatabaseBatchException(Database.java:1440)
2022/09/28 03:12:54 - send_to_job.0 - 	at org.pentaho.di.trans.steps.tableoutput.TableOutput.writeToTable(TableOutput.java:295)
2022/09/28 03:12:54 - send_to_job.0 - 	... 3 more
2022/09/28 03:12:54 - send_to_job.0 - Caused by: java.sql.BatchUpdateException: Code: 216. DB::Exception: Query with id = 3f5bb847-a8cd-4af4-91c6-bf68c06036c2 is already running. (QUERY_WITH_SAME_ID_IS_ALREADY_RUNNING) (version 22.9.2.7 (official build))
, server ClickHouseNode(addr=http:71.71.71.187:8123, db=default)@-702972333
2022/09/28 03:12:54 - send_to_job.0 - 	at com.clickhouse.jdbc.SqlExceptionUtils.batchUpdateError(SqlExceptionUtils.java:90)
2022/09/28 03:12:54 - send_to_job.0 - 	at com.clickhouse.jdbc.internal.InputBasedPreparedStatement.executeAny(InputBasedPreparedStatement.java:130)
2022/09/28 03:12:54 - send_to_job.0 - 	at com.clickhouse.jdbc.internal.AbstractPreparedStatement.executeLargeBatch(AbstractPreparedStatement.java:85)
2022/09/28 03:12:54 - send_to_job.0 - 	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.executeBatch(ClickHouseStatementImpl.java:539)
2022/09/28 03:12:54 - send_to_job.0 - 	at org.pentaho.di.trans.steps.tableoutput.TableOutput.writeToTable(TableOutput.java:291)
2022/09/28 03:12:54 - send_to_job.0 - 	... 3 more
2022/09/28 03:12:54 - send_to_job.0 - ERROR (version 9.2.0.0-290, build 9.2.0.0-290 from 2021-06-02 06.36.08 by buildguy) : Unexpected batch update error committing the database connection.
2022/09/28 03:12:54 - send_to_job.0 - ERROR (version 9.2.0.0-290, build 9.2.0.0-290 from 2021-06-02 06.36.08 by buildguy) : org.pentaho.di.core.exception.KettleDatabaseBatchException: 
2022/09/28 03:12:54 - send_to_job.0 - Error updating batch
2022/09/28 03:12:54 - send_to_job.0 - Please call addBatch method at least once before batch execution
2022/09/28 03:12:54 - send_to_job.0 - 
2022/09/28 03:12:54 - send_to_job.0 - 	at org.pentaho.di.core.database.Database.createKettleDatabaseBatchException(Database.java:1440)
2022/09/28 03:12:54 - send_to_job.0 - 	at org.pentaho.di.core.database.Database.emptyAndCommit(Database.java:1432)
2022/09/28 03:12:54 - send_to_job.0 - 	at org.pentaho.di.trans.steps.tableoutput.TableOutput.dispose(TableOutput.java:590)
2022/09/28 03:12:54 - send_to_job.0 - 	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:97)
2022/09/28 03:12:54 - send_to_job.0 - 	at java.lang.Thread.run(Unknown Source)
2022/09/28 03:12:54 - send_to_job.0 - Caused by: java.sql.SQLException: Please call addBatch method at least once before batch execution
2022/09/28 03:12:54 - send_to_job.0 - 	at com.clickhouse.jdbc.SqlExceptionUtils.clientError(SqlExceptionUtils.java:43)
2022/09/28 03:12:54 - send_to_job.0 - 	at com.clickhouse.jdbc.SqlExceptionUtils.emptyBatchError(SqlExceptionUtils.java:111)
2022/09/28 03:12:54 - send_to_job.0 - 	at com.clickhouse.jdbc.internal.InputBasedPreparedStatement.executeAny(InputBasedPreparedStatement.java:96)
2022/09/28 03:12:54 - send_to_job.0 - 	at com.clickhouse.jdbc.internal.AbstractPreparedStatement.executeLargeBatch(AbstractPreparedStatement.java:85)
2022/09/28 03:12:54 - send_to_job.0 - 	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.executeBatch(ClickHouseStatementImpl.java:539)
2022/09/28 03:12:54 - send_to_job.0 - 	at org.pentaho.di.core.database.Database.emptyAndCommit(Database.java:1416)
2022/09/28 03:12:54 - send_to_job.0 - 	... 3 more
2022/09/28 03:12:54 - tablo_aktar - ERROR (version 9.2.0.0-290, build 9.2.0.0-290 from 2021-06-02 06.36.08 by buildguy) : Errors detected!
2022/09/28 03:12:54 - send_to_job.0 - Finished processing (I=0, O=47220000, R=47230000, W=47220000, U=0, E=1)
2022/09/28 03:12:54 - tablo_aktar - Transformation detected one or more steps with errors.
2022/09/28 03:12:54 - tablo_aktar - Transformation is killing the other steps!
2022/09/28 03:12:54 - verileri_getir.0 - !TableInput.Log.FinishedReadingQuery!
2022/09/28 03:22:13 - verileri_getir.0 - Finished processing (I=47240002, O=0, R=0, W=47240001, U=0, E=0)
2022/09/28 03:22:13 - tablo_aktar - ERROR (version 9.2.0.0-290, build 9.2.0.0-290 from 2021-06-02 06.36.08 by buildguy) : Errors detected!
2022/09/28 03:22:13 - full - Finished job entry [tablo_aktar] (result=[false])
2022/09/28 03:22:13 - full - Finished job entry [tablo_adlari] (result=[false])
2022/09/28 03:22:13 - full - Job execution finished
2022/09/28 03:22:13 - Spoon - Job has ended.

**Comment by den-crane** [comment]
It's not a Ch-server issue. Ask this in https://github.com/ClickHouse/clickhouse-jdbc

**Comment by mih-kopylov** [comment]
https://github.com/ClickHouse/clickhouse-java/issues/1529
