### ISSUE TITLE
SQLException：Unknown error 1002， Server ClickHouseNode

### ISSUE THREAD

**Issue by TaoPanfeng** [ClickHouse/ClickHouse#41865]
![image](https://user-images.githubusercontent.com/48585565/192668904-24af1653-1f48-4ab6-a5a7-7fd10cc2ff79.png)

**Comment by den-crane** [comment]
JDBC issue, open issue there https://github.com/yandex/ClickHouse-jdbc/

**Comment by seraphv3** [comment]
@TaoPanfeng Have you solved this problem? I encounted the same problem, would you please tell me how to solved this problem?

**Comment by ludlows** [comment]
same problem here
