### ISSUE TITLE
How to check whether Clickhouse server-settings is really applied?

### ISSUE THREAD

**Issue by xpleaf** [ClickHouse/ClickHouse#41868]
## ClickHouse Version

```
21.8.4
```

## Quesion

I changed the maximum concurrency in config.xml
```
<max_concurrent_queries>200</max_concurrent_queries>
```

I want to know if this configuration has taken effect, but there is no relevant parameter to check, Only the following two were found: 

```
SHOW SETTINGS LIKE '%max_concurrent_queries%'

Query id: d34dfeea-ad26-47b4-a6de-18aafa496d3c

┌─name─────────────────────────────────┬─type───┬─value─┐
│ max_concurrent_queries_for_all_users │ UInt64 │ 0     │
│ max_concurrent_queries_for_user      │ UInt64 │ 0     │
└──────────────────────────────────────┴────────┴───────┘
```

How to check whether Clickhouse server-settings is really applied?

**Comment by DerekChia** [comment]
`max_concurrent_queries` setting can be found under `system.merge_tree_settings`.

```
22b37ed6b244 :) select * from system.merge_tree_settings where name = 'max_concurrent_queries'

SELECT *
FROM system.merge_tree_settings
WHERE name = 'max_concurrent_queries'

Query id: 9c7db226-a695-45c4-8c85-a1081ed2d435

┌─name───────────────────┬─value─┬─changed─┬─description────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─type───┐
│ max_concurrent_queries │ 0     │       0 │ Max number of concurrently executed queries related to the MergeTree table (0 - disabled). Queries will still be limited by other max_concurrent_queries settings. │ UInt64 │
└────────────────────────┴───────┴─────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴────────┘

1 row in set. Elapsed: 0.026 sec.
```

**Comment by xpleaf** [comment]
@DerekChia Thanks，I found this configuration, but from the query result, the value and changed displayed here are both 0, there is still no way to confirm it, do you have a better method?

```
SELECT *
FROM system.merge_tree_settings
WHERE name = 'max_concurrent_queries'

Query id: 2b3394ba-67c6-41bb-9fed-6f94a110cad8

Connecting to database system at localhost:9000 as user gdc_sa.
Connected to ClickHouse server version 21.8.3 revision 54449.

┌─name───────────────────┬─value─┬─changed─┬─description────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─type───┐
│ max_concurrent_queries │ 0     │       0 │ Max number of concurrently executed queries related to the MergeTree table (0 - disabled). Queries will still be limited by other max_concurrent_queries settings. │ UInt64 │
└────────────────────────┴───────┴─────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴────────┘

1 rows in set. Elapsed: 0.002 sec. 
```

**Comment by DerekChia** [comment]
May I know why you are looking to change this setting? Ideally, you'd want to change `max_concurrent_queries_for_user` and `max_concurrent_queries_per_user` instead.

Putting a link to a similar issue here - https://github.com/ClickHouse/ClickHouse/issues/38870

And I quote a reply by @genzgd below:

> After discussion with the devs, the `max_concurrent_queries` configuration value is not visible in system.settings because it is global and unmodifiable by the user at a profile or query level (similar to various other config.xml settings such as `listen_host` or `http_port`). It's confusing because it's mentioned in the docs in connection with other profile/user level settings.
> 
> At some point we hope to make all configuration setting available within ClickHouse (for a user with appropriate permissions).

**Comment by xpleaf** [comment]
> May I know why you are looking to change this setting? Ideally, you'd want to change `max_concurrent_queries_for_user` and `max_concurrent_queries_per_user` instead.
> 
> Putting a link to a similar issue here - #38870
> 
> And I quote a reply by @genzgd below:
> 
> > After discussion with the devs, the `max_concurrent_queries` configuration value is not visible in system.settings because it is global and unmodifiable by the user at a profile or query level (similar to various other config.xml settings such as `listen_host` or `http_port`). It's confusing because it's mentioned in the docs in connection with other profile/user level settings.
> > At some point we hope to make all configuration setting available within ClickHouse (for a user with appropriate permissions).

To ensure service stability, we set strict limits on the number of memory and threads per query to evaluate the max_concurrent_queries a machine can carry. So it's just a matter of not being able to find the runtime parameters to verify that this configuration works.
