### ISSUE TITLE
Codecs for Decimal128 / Decimal256

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#41871]
Main usecase there are long ranges of very small values, followed by long ranges of relatively high values. 

I.e. 

CREATE TABLE ... ( customerid , amount Decimal256) engine=MergeTree ORDER BY customer_id; 

customerid1 uses cryptocurrencies and need ~30 decimal digits (and usually values sit in the range 0.00000001 - 0.0003),
customerid2 uses Indonesian rupiah and does not use decimal point at all (and usually values sit in the range 10000-1000000).

I think that something like T64 may work great here.

**Comment by alexey-milovidov** [comment]
It is difficult to believe that custom codecs can work better than ZSTD.
