### ISSUE TITLE
 Can't format ASTInsertQuery with data, since data will be lost

### ISSUE THREAD

**Issue by was-av** [ClickHouse/ClickHouse#41872]
We use clickhouse-format as clickhouse queries linter. 
clickhouse-format has raised an error when receiving valid query 'insert into values'.

**Does it reproduce on a recent release?**

ClickHouse client version 22.8.5.29 (official build).

Yes

**How to reproduce**

1. Create file 'query.sql' with query
```
-- query.sql
INSERT INTO db.table (c1, c2, c3) VALUES (v11, v12, v13), (v21, v22, v23)
```

2. Run command clickhouse-format < query.sql

**Expected behavior**

Command clickhouse-format finished with exit code 0

**Error message and/or stacktrace**

```
Code: 578. DB::Exception: Can't format ASTInsertQuery with data, since data will be lost. (INVALID_FORMAT_INSERT_QUERY_WITH_DATA), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x8dcd368 in /usr/bin/clickhouse
1. mainEntryClickHouseFormat(int, char**) @ 0x8f7ac3c in /usr/bin/clickhouse
2. main @ 0x8dbb204 in /usr/bin/clickhouse
3. __libc_start_main @ 0x24218 in /lib/aarch64-linux-gnu/libc-2.31.so
 (version 22.8.5.29 (official build))
```

**Comment by alexey-milovidov** [comment]
You cannot format the INSERT query with data using `clickhouse-format`.
ClickHouse does not place the INSERT data into the Abstract Syntax Tree and does not use the SQL parser for data.
The error message tells you about this fact.
