### ISSUE TITLE
Feature request: Add support for MongoDB clusters as external dictionaries

### ISSUE THREAD

**Issue by uncletimmy3** [ClickHouse/ClickHouse#4190]
Recently I stumbled upon a problem external dictionary (linked to MongoDB) was empty. There was nothing releted to the problem in clickhouse log, but in MongoDB log I found this:
```
2019-01-29T12:09:24.023+0300 I NETWORK  [initandlisten] connection accepted from 192.168.231.108:54764 #3208444 (217 connections now open)
2019-01-29T12:09:24.068+0300 I QUERY    [conn3208444] assertion 13435 not master and slaveOk=false ns:NormativSrs.UserOutliers query:{}
```
**not master and slaveOk=false** causes CH not to read data, if server specified in the configuration is not a master anymore.

It seems that if you replace it:
https://github.com/yandex/ClickHouse/blob/a19d3620a3b612fc7d442368bbfc2e91a2bb8975/dbms/src/Dictionaries/MongoDBDictionarySource.cpp#L189
with this:
```
Connection(
    const std::string & uri,
    SocketFactory & socketFactory
);
```
it will be possible to set slaveOk=true.

**Comment by maddhuapplicate** [comment]
Does Clickhouse dictionary support Mongo cluster as source? Most production systems will be on clusters. When we tried the cluster URI as host, Clickhouse did not connect to the cluster.

**Comment by uncletimmy3** [comment]
Hi! Dont close issue pls :)
Or may be this has been fixed?

**Comment by SychovOleh** [comment]
It is a really easy task. But, unfortunately, looks like no one wants to fix it.

**Comment by ekbfh** [comment]
Up

**Comment by alexey-milovidov** [comment]
We will try to find someone from community who are interested to implement this feature.

**Comment by manish53** [comment]
Hi alexey,
Sometime ago i faced same issue and successfully fixed it by updating poco version in clickhouse. 
You can see PR https://github.com/ClickHouse/ClickHouse/pull/5387

**Comment by manish53** [comment]
And https://github.com/ClickHouse/ClickHouse/pull/5388

**Comment by alexey-milovidov** [comment]
This PR is assigned to Alexander Kuzmenkov @akuzm, he decided to take it for this week at last.

**Comment by Olegt0rr** [comment]
Reminder :)

**Comment by akuzm** [comment]
> Seems like #5388 #5387 #10915 are closed.
> But still can't add MongoDB Atlas ReplicaSet as external dictionary.

Yes, I added only the very basic URI support. The hard part was updating Poco library to a version that has the necessary MongoDB API. Now the external contributors can use this API to continue working on related features. As far as I know, we don't plan to continue this work ourselves, but will happily accept contributions.

**Comment by Olegt0rr** [comment]
@akuzm, could you help to draw up the detailed requirements for the necessary contribution?
I'll try to find someone and pay for his work

**Comment by akuzm** [comment]
> @akuzm, could you help to draw up the detailed requirements for the necessary contribution?
> I'll try to find someone and pay for his work ([ru link](https://freelance.habr.com/tasks/304258))

Just implement what you need and send a PR, we don't have any particular requirements other than working code + docs + tests. Even a prototype is OK, it will let us to discuss the task in more detail.
The main difficulty may turn out to be with Poco -- if it doesn't support the kind of URI you need, it will have to be added upstream first (https://github.com/pocoproject/poco). They do accept contributions, although it may take some time. Then they'll publish a release with this feature, we'll update our Poco version to this release, and only after that we can merge the ClickHouse feature itself. In a prototype PR, Poco can be switched to whatever fork or version you need.

**Comment by alexey-milovidov** [comment]
@akuzm why not? :wink:

**Comment by artem-yadr** [comment]
Hi! Made a pull request a few months ago to support additional uri type in poco, but they haven't responded. Is there another way to make changes or speed up the verification process in poco? Here my pr: https://github.com/pocoproject/poco/pull/3868

**Comment by artem-yadr** [comment]
@alexey-milovidov can you help with this?

**Comment by alexey-milovidov** [comment]
Poco is an inactive project; please submit it here: https://github.com/ClickHouse/poco/, and we can merge it quickly.
