### ISSUE TITLE
client can not work properly

### ISSUE THREAD

**Issue by awesomeleo** [ClickHouse/ClickHouse#41919]
> You have to provide the following information whenever possible.

**Describe what's wrong**
The client shows “localhost :) select dedprice * (1 - l_discount)) as revenue,o_orderdate,o_shippriority from customer,orders,lineitem where c_mktsegment = 'BUILDING' and c_custkey = o_custkey and l_orderkey = o_orderkey and o_orderdate < date '1995-03-15' and l_shipdate > date '1995-03-15' group by 
Display all 5338 possibilities? (y or n)
” when i paste a long query. The old version (such as v21.8 ) does not has this problem. I have tested with both sinle line query and mulit-line query.

**Does it reproduce on recent release?**
I don't know, I just tested the version 22.8.5.29

**How to reproduce**
Just paste a long query to the client.

* Which ClickHouse server version to use
* ┌─version()─┐
│ 22.8.5.29 │
└───────────┘

* Which interface to use, if matters
*clickhouse-client
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
I tested with tpch queries.
such as this one
select
	l_orderkey,
	sum(l_extendedprice * (1 - l_discount)) as revenue,
	o_orderdate,
	o_shippriority
from customer,
	orders,
	lineitem
where c_mktsegment = 'BUILDING'
	and c_custkey = o_custkey
	and l_orderkey = o_orderkey
	and o_orderdate < date '1995-03-15'
	and l_shipdate > date '1995-03-15'
group by
	l_orderkey,
	o_orderdate,
	o_shippriority
order by
	revenue desc,
	o_orderdate
limit 10 

**Expected behavior**
work properly

**Comment by alexey-milovidov** [comment]
Workaround: replace tabs with spaces in your query.

@amosbird I assume bracketed paste should work correctly for queries with tabs?

**Comment by amosbird** [comment]
It definitely works with tabs which will be rendered as `^I`.

I don't understand the problem. Please provide the exact clipboard content that can reproduce.

**Comment by awesomeleo** [comment]
@amosbird  pls see the above comments.

**Comment by amosbird** [comment]
I cannot reproduce it with either `-n` or `-m`. What OS do you use? Is it official clickhouse build?

**Comment by awesomeleo** [comment]
> I cannot reproduce it with either `-n` or `-m`. What OS do you use? Is it official clickhouse build?
I use centos7.6.   Yes, it's an official build. I download the binary  from github.
![image](https://user-images.githubusercontent.com/6779544/194685011-34810e0b-2298-49fb-ac2a-c5a5bfd17342.png)

**Comment by awesomeleo** [comment]
I test with select 'tab' 1 and  it also can not work. 
1. write select  'this is a tab' 1 in notepad++;
2. copy and paste to the client.
I use xshell, I don't know whether relate to it.

**Comment by amosbird** [comment]
What terminal emulator do you use? Please also provide the output of `echo $TERM`.

**Comment by awesomeleo** [comment]
[root@localhost ]# echo $TERM
xterm-256color
I use xshell，I  don't know whether releated to it.

**Comment by amosbird** [comment]
> I use xshell，I don't know whether releated to it.

Most likely yes. You can check if bracketed paste is supported via https://jdhao.github.io/2021/02/01/bracketed_paste_mode/#how-enable-and-disale-it-in-terminal

I think we can bring back the old behavior (polling stdin to check if it's a paste) for compatibility.

**Comment by awesomeleo** [comment]
bracketed paste mode does not work in my shell.  I have logged in with windows power shell, and it also has this issue.  Anyway, It's an insignificant issue. I can replace the tab with space.
