### ISSUE TITLE
Calculate avg from distributed tables returns wrong value

### ISSUE THREAD

**Issue by alazo8807** [ClickHouse/ClickHouse#41914]
We having an issue where for a specific dataset (not happening for other customers), the result of calling avg(measurement) always returns 18446744073709552000 which looks like an overflown value and measurement column is of type int64.
This only happens when running the query agains a virtual distributed table, if we query the actual replicated table it returns the correct value.
We found a workaround, if we cast measurement value to int64, the avg value returns correct. This is very odd since the column is already an int64 value. The workaround looks something like:
`SELECT avg(toInt64(measurement)) FROM distributed_table`
Not sure why when recasting to int64 or querying the replicated table works and not when querying the distributed table, so we were wondering if this is a known issue or a potential bug.

**Comment by den-crane** [comment]
Please provide `show create table distributed_table` and `show create table local_table` 
Check that columns in both tables have the same types.

**Comment by alazo8807** [comment]
Thanks @den-crane. The distributed table is a virtual one, so the type of the column is the same. 
This is a simplified version of our table definition. In our client application we query the distributed virtual table.


```
CREATE TABLE IF NOT EXISTS data.replicated_table_v1
ON CLUSTER '{cluster}'
(
    date Date DEFAULT toDate(timestamp, 'UTC') Codec(ZSTD),
    timestamp UInt64 Codec(DoubleDelta, LZ4),
    measure_int Int64 Codec(Gorilla, LZ4),
    ...
)
ENGINE = ReplicatedMergeTree(
    '/clickhouse/tables/{shard}/data/replicated_table_v1,
    '{replica}'
)
PARTITION BY toStartOfMonth(date)
ORDER BY (
    timestamp
)
TTL date + INTERVAL ${TTL_INTERVAL} DELETE
```

Then we have a merge virtual table that pulls from all the replicated
```
CREATE TABLE IF NOT EXISTS entity.merged_table
ON CLUSTER '{cluster}'
AS data.replicated_table_v1
ENGINE = Merge(
    data,
    '^replicated_table_v1'
)
```

And finally another virtual distributed table that pulls from the merged_table
```
CREATE TABLE IF NOT EXISTS entity.distributed_table
AS data.replicated_table_v1
ENGINE = Distributed(
    '{cluster}',
    data,
    merged_table
)

```

**Comment by den-crane** [comment]
>This is a simplified version of our table definition.

No requested info. Closing.

**Comment by den-crane** [comment]
here is an example

```
create table local( A Int32, B Int32) Engine=MergeTree order by A;
create table distr as local Engine=Distributed('test_shard_localhost', currentDatabase(), local, rand());

alter table local modify column B Int64;

desc local
┌─name─┬─type──
│ A    │ Int32
│ B    │ Int64
└──────┴───────

desc distr;
┌─name─┬─type──
│ A    │ Int32
│ B    │ Int32
└──────┴───────
insert into local values ( 1, toUInt64(-1)/2-100);

select *from local;
┌─A─┬───────────────────B─┐
│ 1 │ 9223372036854775807 │
└───┴─────────────────────┘

 select *from distr;
┌─A─┬──B─┐
│ 1 │ -1 │
└───┴────┘

alter table distr modify column B Int64;

select *from distr;
┌─A─┬───────────────────B─┐
│ 1 │ 9223372036854775807 │
└───┴─────────────────────┘
```

**Comment by den-crane** [comment]
Please share the result of 

```sql
SELECT
    type,
    count()
FROM clusterAllReplicas('{cluster}', system.columns)
WHERE name = 'measurement'
GROUP BY type```

**Comment by alazo8807** [comment]
It looks like measurement is defined as uint64 in one of our materialized views. Thanks for all the help
