### ISSUE TITLE
Settings store constantly in tmp files(.bin) when insert Distributed table in asynchronous mode

### ISSUE THREAD

**Issue by lzydmxy** [ClickHouse/ClickHouse#41924]
Since I set `max_concurrent_queries_for_user` with a very small value to the user, a lot pending files in distributed table. A large number of writes to remote table failed because of Exception `Code: 202. DB::Exception: Too many simultaneous queries for user default. Current: 6, maximum: 2.`
```sql
SELECT *
FROM system.metrics
WHERE metric = 'DistributedFilesToInsert'

Query id: ea862251-9475-465d-be3b-458f62697573

┌─metric───────────────────┬─value─┬─description───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ DistributedFilesToInsert │ 13787 │ Number of pending files to process for asynchronous insertion into Distributed tables. Number of files for every shard is summed. │
└──────────────────────────┴───────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

1 rows in set. Elapsed: 0.003 sec.
```
I try to set `max_concurrent_queries_for_user` to 40, however I still got Exception `Code: 202. DB::Exception: Too many simultaneous queries for user default. Current: 6, maximum: 2.` 

I found that Settings store constantly in tmp files
```shell
vim 8094.bin
...max_concurrent_queries_for_user^@^A2...
```
The code also verifies
```c++
void StorageDistributedDirectoryMonitor::processFile(const std::string & file_path)
{
    ...
        RemoteInserter remote{*connection, timeouts,
            distributed_header.insert_query,
            distributed_header.insert_settings,
            distributed_header.client_info};
        bool compression_expected = connection->getCompression() == Protocol::Compression::Enable;
        writeRemoteConvert(distributed_header, remote, compression_expected, in, log);
    ...
}
```
Because of `max_concurrent_queries_for_user` limits , old writes are pending all the time. The writing process is asynchronous, should the new configuration take effect on the old write?  In other words, do we have a better solution to the problem I'm facing？

**Comment by azat** [comment]
>Because of max_concurrent_queries_for_user limits , old writes are pending all the time. The writing process is asynchronous, should the new configuration take effect on the old write? 

Indeed, right now it is so.

>In other words, do we have a better solution to the problem I'm facing？

I don't think so, you can add settings constraints on the receiver side however, this should work (constraints throws only for initial queries (`INITIAL_QUERY`) if they are not satisfied, however INSERTs that will be send by the initiator will be send as `SECONDARY_QUERY`)

Another option is to add a setting that will ignore user settings for INSERT (on query and table level), but this may be a security breach.

**Comment by sunny19930321** [comment]
> > Because of max_concurrent_queries_for_user limits , old writes are pending all the time. The writing process is asynchronous, should the new configuration take effect on the old write?
> 
> Indeed, right now it is so.
> 
> > In other words, do we have a better solution to the problem I'm facing？
> 
> I don't think so, you can add settings constraints on the receiver side however, this should work (constraints throws only for initial queries (`INITIAL_QUERY`) if they are not satisfied, however INSERTs that will be send by the initiator will be send as `SECONDARY_QUERY`)
> 
> Another option is to add a setting that will ignore user settings for INSERT (on query and table level), but this may be a security breach.

I agree with the first one, which controls whether it is limited by the initial account by configuration

**Comment by lzydmxy** [comment]
> Another option is to add a setting that will ignore user settings for INSERT (on query and table level), but this may be a security breach.

Maybe we can add settings in `SYSTEM FLUSH DISTRIBUTED` Statements. For example, `SYSTEM FLUSH DISTRIBUTED SETTINGS  max_concurrent_queries_for_user = 10`, so that we can ignore user settings for pending INSERT.

**Comment by azat** [comment]
>Maybe we can add settings in SYSTEM FLUSH DISTRIBUTED Statements. For example, SYSTEM FLUSH DISTRIBUTED SETTINGS  max_concurrent_queries_for_user = 10, so that we can ignore user settings for pending INSERT.

@lzydmxy Yes, this is a good idea!
I will take a look after some refactoring of that place - #45491

**Comment by lzydmxy** [comment]
@azat Hi, is `SYSTEM FLUSH DISTRIBUTED SETTINGS` supported now?

**Comment by sunny19930321** [comment]
let me solve this problem @lzydmxy @azat
