### ISSUE TITLE
Optimize does not merge the partition file into a folder; But it can actually be merged into a folder

### ISSUE THREAD

**Issue by shadowDy** [ClickHouse/ClickHouse#41927]
clickhouse version：22.9.2.7

ls clickhouse data:
`ls data/database
20220920_1_1_0  20220920_2_2_0  20220920_3_3_0  20220920_4_4_0  20220920_5_5_0  20220920_6_6_0  detached  format_version.txt
`

execute：OPTIMIZE TABLE feed.test_local FINAL

then ls clickhouse data:
`ls data/database
20220920_1_1_0  20220920_1_6_1  20220920_1_6_2  20220920_2_2_0  20220920_3_3_0  20220920_4_4_0  20220920_5_5_0  20220920_6_6_0  detached  format_version.txt
`

expected behaviour：only remain the 20220920_1_6_1 floder and old floder like 20220920_1_1_0 will be drop when optimize final finished；

log：
`
2022.09.29 17:22:36.877762 [ 8086 ] {b07cf380-85af-49cd-86b4-757ddc7c148f} <Debug> executeQuery: (from 0.0.0.0:0, user: ) OPTIMIZE TABLE db.table FINAL (stage: Complete)
2022.09.29 17:22:36.877877 [ 8086 ] {b07cf380-85af-49cd-86b4-757ddc7c148f} <Trace> ContextAccess (default): Access granted: OPTIMIZE ON db.table
2022.09.29 17:22:36.878212 [ 8100 ] {db.table::20220920_1_6_1} <Debug> MergeTreeSequentialSource: Reading 2 marks from part 20220920_2_2_0, total 58 rows starting from the beginning of the part
2022.09.29 17:22:36.878644 [ 8100 ] {db.table::20220920_1_6_1} <Debug> MergeTreeSequentialSource: Reading 2 marks from part 20220920_3_3_0, total 58 rows starting from the beginning of the part
2022.09.29 17:22:36.879022 [ 8100 ] {db.table::20220920_1_6_1} <Debug> MergeTreeSequentialSource: Reading 2 marks from part 20220920_4_4_0, total 58 rows starting from the beginning of the part
2022.09.29 17:22:36.879433 [ 8100 ] {db.table::20220920_1_6_1} <Debug> MergeTreeSequentialSource: Reading 2 marks from part 20220920_5_5_0, total 58 rows starting from the beginning of the part
2022.09.29 17:22:36.879720 [ 8086 ] {b07cf380-85af-49cd-86b4-757ddc7c148f} <Debug> db.table: Waiting for currently running merges (6 parts are merging right now) to perform OPTIMIZE FINAL
2022.09.29 17:22:36.879840 [ 8100 ] {db.table::20220920_1_6_1} <Debug> MergeTreeSequentialSource: Reading 2 marks from part 20220920_6_6_0, total 58 rows starting from the beginning of the part
2022.09.29 17:22:36.887453 [ 8106 ] {db.table::20220920_1_6_1} <Debug> MergeTask::MergeProjectionsStage: Merge sorted 348 rows, containing 75 columns (75 merged, 0 gathered) in 0.011963292 sec., 29088.9831996076 rows/sec., 68.48 MiB/sec.
2022.09.29 17:22:36.887504 [ 8106 ] {db.table::20220920_1_6_1} <Debug> MergeTask::MergeProjectionsStage: Selected 6 projection_parts from p_b_column to p_b_column
2022.09.29 17:22:36.887569 [ 8106 ] {db.table::20220920_1_6_1} <Debug> MergeTask::PrepareStage: Merging 6 parts: from p_b_column to p_b_column into Compact
2022.09.29 17:22:36.887627 [ 8106 ] {db.table::20220920_1_6_1} <Debug> MergeTask::PrepareStage: Selected MergeAlgorithm: Horizontal
2022.09.29 17:22:36.887646 [ 8106 ] {db.table::20220920_1_6_1} <Debug> MergeTreeSequentialSource: Reading 2 marks from part p_b_column, total 4 rows starting from the beginning of the part, column b_column
2022.09.29 17:22:36.887828 [ 8106 ] {db.table::20220920_1_6_1} <Debug> MergeTreeSequentialSource: Reading 2 marks from part p_b_column, total 4 rows starting from the beginning of the part, column b_column
2022.09.29 17:22:36.887949 [ 8106 ] {db.table::20220920_1_6_1} <Debug> MergeTreeSequentialSource: Reading 2 marks from part p_b_column, total 4 rows starting from the beginning of the part, column b_column
2022.09.29 17:22:36.888050 [ 8106 ] {db.table::20220920_1_6_1} <Debug> MergeTreeSequentialSource: Reading 2 marks from part p_b_column, total 4 rows starting from the beginning of the part, column b_column
2022.09.29 17:22:36.888143 [ 8106 ] {db.table::20220920_1_6_1} <Debug> MergeTreeSequentialSource: Reading 2 marks from part p_b_column, total 4 rows starting from the beginning of the part, column b_column
2022.09.29 17:22:36.888217 [ 8106 ] {db.table::20220920_1_6_1} <Debug> MergeTreeSequentialSource: Reading 2 marks from part p_b_column, total 4 rows starting from the beginning of the part, column b_column
2022.09.29 17:22:36.888760 [ 8117 ] {db.table::20220920_1_6_1} <Debug> MergeTask::MergeProjectionsStage: Merge sorted 24 rows, containing 1 columns (1 merged, 0 gathered) in 0.001224832 sec., 19594.523983697356 rows/sec., 196.14 KiB/sec.
2022.09.29 17:22:36.889474 [ 8117 ] {db.table::20220920_1_6_1} <Trace> MergedBlockOutputStream: filled checksums p_b_column (state Active)
2022.09.29 17:22:36.891122 [ 8117 ] {db.table::20220920_1_6_1} <Trace> MergedBlockOutputStream: filled checksums 20220920_1_6_1 (state Temporary)
2022.09.29 17:22:36.891557 [ 8117 ] {db.table::20220920_1_6_1} <Trace> db.table: Renaming temporary part tmp_merge_20220920_1_6_1 to 20220920_1_6_1.
2022.09.29 17:22:36.891641 [ 8117 ] {db.table::20220920_1_6_1} <Trace> db.table (MergerMutator): Merged 6 parts: from 20220920_1_1_0 to 20220920_6_6_0
2022.09.29 17:22:36.891833 [ 8117 ] {} <Debug> MemoryTracker: Peak memory usage to apply mutate/merge in db.table::20220920_1_6_1: 8.15 MiB.
2022.09.29 17:22:36.891888 [ 8086 ] {b07cf380-85af-49cd-86b4-757ddc7c148f} <Debug> db.table (MergerMutator): Selected 1 parts from 20220920_1_6_1 to 20220920_1_6_1
2022.09.29 17:22:36.891927 [ 8086 ] {b07cf380-85af-49cd-86b4-757ddc7c148f} <Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 65.07 GiB.
2022.09.29 17:22:36.891954 [ 8086 ] {db.table::20220920_1_6_2} <Debug> MergeTask::PrepareStage: Merging 1 parts: from 20220920_1_6_1 to 20220920_1_6_1 into Compact
2022.09.29 17:22:36.892189 [ 8086 ] {db.table::20220920_1_6_2} <Debug> MergeTask::PrepareStage: Selected MergeAlgorithm: Horizontal
2022.09.29 17:22:36.892269 [ 8086 ] {db.table::20220920_1_6_2} <Debug> MergeTreeSequentialSource: Reading 2 marks from part 20220920_1_6_1, total 348 rows starting from the beginning of the part
2022.09.29 17:22:36.896400 [ 8086 ] {db.table::20220920_1_6_2} <Debug> MergeTask::MergeProjectionsStage: Merge sorted 348 rows, containing 75 columns (75 merged, 0 gathered) in 0.004441343 sec., 78354.67785307282 rows/sec., 184.46 MiB/sec.
2022.09.29 17:22:36.896444 [ 8086 ] {db.table::20220920_1_6_2} <Debug> MergeTask::MergeProjectionsStage: Selected 1 projection_parts from p_b_column to p_b_column
2022.09.29 17:22:36.896465 [ 8086 ] {db.table::20220920_1_6_2} <Debug> MergeTask::PrepareStage: Merging 1 parts: from p_b_column to p_b_column into Compact
2022.09.29 17:22:36.896511 [ 8086 ] {db.table::20220920_1_6_2} <Debug> MergeTask::PrepareStage: Selected MergeAlgorithm: Horizontal
2022.09.29 17:22:36.896534 [ 8086 ] {db.table::20220920_1_6_2} <Debug> MergeTreeSequentialSource: Reading 2 marks from part p_b_column, total 4 rows starting from the beginning of the part, column b_column
2022.09.29 17:22:36.896926 [ 8086 ] {db.table::20220920_1_6_2} <Debug> MergeTask::MergeProjectionsStage: Merge sorted 4 rows, containing 1 columns (1 merged, 0 gathered) in 0.0004653 sec., 8596.604341285192 rows/sec., 86.05 KiB/sec.
2022.09.29 17:22:36.897562 [ 8086 ] {db.table::20220920_1_6_2} <Trace> MergedBlockOutputStream: filled checksums p_b_column (state Active)
2022.09.29 17:22:36.899119 [ 8086 ] {db.table::20220920_1_6_2} <Trace> MergedBlockOutputStream: filled checksums 20220920_1_6_2 (state Temporary)
2022.09.29 17:22:36.899511 [ 8086 ] {db.table::20220920_1_6_2} <Trace> db.table: Renaming temporary part tmp_merge_20220920_1_6_2 to 20220920_1_6_2.
2022.09.29 17:22:36.899572 [ 8086 ] {db.table::20220920_1_6_2} <Trace> db.table (MergerMutator): Merged 1 parts: from 20220920_1_6_1 to 20220920_1_6_1
2022.09.29 17:22:36.899678 [ 8086 ] {b07cf380-85af-49cd-86b4-757ddc7c148f} <Debug> MemoryTracker: Peak memory usage to apply mutate/merge in db.table::20220920_1_6_2: 8.24 MiB.
2022.09.29 17:22:36.899766 [ 8086 ] {b07cf380-85af-49cd-86b4-757ddc7c148f} <Debug> MemoryTracker: Peak memory usage (for query): 0.00 B.
`

**Comment by tavplubix** [comment]
Outdated parts cleanup is asynchronous

**Comment by den-crane** [comment]
https://clickhouse.com/docs/en/operations/settings/merge-tree-settings/#old-parts-lifetime
Default value: 480.

**Comment by shadowDy** [comment]
> Outdated parts cleanup is asynchronous

Can this setting be changed to synchronization？

**Comment by shadowDy** [comment]
> https://clickhouse.com/docs/en/operations/settings/merge-tree-settings/#old-parts-lifetime Default value: 480.

Can this setting be changed to synchronization？Can this configuration be added to the configuration parameters of clickhouse local？
