### ISSUE TITLE
Dear all, which version support full-text

### ISSUE THREAD

**Issue by lijiang1983** [ClickHouse/ClickHouse#41930]
Hi:
     Is clickhouse support full-text search?
     If clickhouse support,  How do I configure?

**Comment by rfyiamcool** [comment]
you can use tokenbf skipindex.

**Comment by lijiang1983** [comment]
> tokenbf skipindex.

Can you provide a specific use step？

**Comment by den-crane** [comment]
https://altinity.com/blog/skipping-indices-part-2-bloom-filters

https://altinity.com/blog/clickhouse-black-magic-skipping-indices

**Comment by lijiang1983** [comment]
When I use order by, I'm search slower.
How to analyze this problem
