### ISSUE TITLE
Possible workaround writing JSON (Object) type to buffer table

### ISSUE THREAD

**Issue by mikhno-s** [ClickHouse/ClickHouse#41942]
Hi,

The current writing scheme looks like this:
writer -> clickhouse buffer table -> clickhouse merge-tree table

Currently we put object as a strings and parse them during executing queries. Now we want to test and migrate such object string-encoded columns to JSON type.

But because storage Buffer doesn't support dynamic subcolumns we cannot use buffer table. However we need buffer table, because it helps us to optimize our writing process. 
Any possible advice and workaround here?

Thanks for the answers

**Comment by Algunenano** [comment]
JSON object is going to be deprecated. No workaround will be added
