### ISSUE TITLE
Постепенно пропадает память

### ISSUE THREAD

**Issue by Rakovskiy28** [ClickHouse/ClickHouse#4194]
Имеется несколько таблиц MergeTree и несколько таблиц Buffer которые по условию

Buffer(`default`, `log`, 1, 1, 1, 500, 3000, 10000000, 100000000)

отправляют данные в MergeTree таблицы.
После запуска "всех  мощностей" записи в КХ используется в пределах 20ГБ памяти, но после этого с каждым часов прибавляется по 5-10 ГБ.

Кол-во инсертов за это время меняется незначительно.

**Comment by filimonov** [comment]
Возможно дубликат:
https://github.com/yandex/ClickHouse/issues/3976 
https://github.com/yandex/ClickHouse/issues/4104

**Comment by alesapin** [comment]
@Rakovskiy28 Напишите версию сервера пожалуйста.

**Comment by Rakovskiy28** [comment]
> @Rakovskiy28 Напишите версию сервера пожалуйста.

ClickHouse server version 18.16.1 revision 54412.

Ещё заметил такой момент. Работал скрипт, данные писались в БД, на этот момент юзалось 70гб RAM, после чего остановил скрипт и часов 5-7 КХ вообще не юзал, но htop показывает, что КХ так и использует 70гб RAM. Т.е. память не освобождается.

**Comment by pikhovkin** [comment]
Здравствуйте!
Почти такая же проблема с памятью. Только память уходит значительно быстрее после определенного кол-ва вставленных строк и по разному на разных табличных движках.

CH 19.3.3 revision 54415.
ОЗУ 32Гб.

Надо импортировать 50млн записей. Каждая запись 90 колонок, заполнено в среднем колонок 20 числами, пару колонок со временем. Индекс сортировки по 3-ем колонкам. Дублей примерно 1\3 от общего кол-ва, расположены примерно равномерно. Записи вставляются по одной.

Движок `ReplacingMergeTree`:
Перед вставкой каждой записи проверяется наличие ключа в таблице, если ключ есть - производится `ALTER TABLE table UPDATE fields=... WHERE expr`, иначе вставка записи.
Таким образом удалось вставить примерно 100тыс. записей.

Движок `ReplacingMergeTree`:
Перед вставкой каждой записи проверяется наличие ключа в таблице, если ключ есть - производится `ALTER TABLE table DELETE WHERE expr` и после этого вставка.
До вставки 100 тыс. записей память примерно колеблется в районе 10 Гб, после этого начинает значительно прирастать, пока не кончается память. Удалось вставить примерно 200 тыс. записей.

Движок `MergeTree`:
Перед вставкой каждой записи проверяется наличие ключа в таблице, если ключ есть - производится `ALTER TABLE table DELETE WHERE expr`. Удалось вставить примерно 800 тыс.

**Comment by blinkov** [comment]
@Rakovskiy28 память по задумке и не должна освобождаться в операционную систему, но должна переиспользоваться при дальнейшей работе clickhouse-server.

@pikhovkin не стоит делать дедупликацию и замену при вставке через ALTER TABLE. Для этого лучше сохранять предыдущие значения в любом внешним хранилище, оптимизированном под точечные записи и чтения. Для дедупликации просто не вставлять новое, а для замены использовать CollapsingMergeTree.

**Comment by pikhovkin** [comment]
@blinkov движки *MergeTree не гарантируют уникальность записей. А при выборке с агрегацией нет возможности получить строковое поле или min\max. Из-за адски быстрой работы выборки в CH меня устраивает медленная запись при дедупликации (~16rps). Но куда расходуется память?

**Comment by filimonov** [comment]
@pikhovkin я закрываю тикет (потому что очень старый). Если вы нашли причину или смогли устранить проблему - пожалуйста напишите пару слов о том как вы это сделали, если проблема всё ещё актуальна и проявляется на новых версиях кликхауса - создайте новый тикет с описанием шагов для воспроизведения проблемы (пример схемы, пример данных, описание способа вставки).
