### ISSUE TITLE
s3Cluster support for named collections

### ISSUE THREAD

**Issue by matiasdominguez** [ClickHouse/ClickHouse#41946]
**Use case**

Not using credentials in queries, just like using named collections with the `s3()` table function or `postgres()`.

**Describe the solution you'd like**

Exactly the same behavior as using named collections when using the `s3` table function with named collections.

**Comment by Khatskevich** [comment]
It seems to be working. Docs just were updated https://clickhouse.com/docs/en/sql-reference/table-functions/s3Cluster
Make sure to put `cluster_name` first and then `named_collection`.
