### ISSUE TITLE
Table system.opentelemetry_span_log doesn't exist.

### ISSUE THREAD

**Issue by zdyj3170101136** [ClickHouse/ClickHouse#41962]
i am using clickhouse 22.9.2.7.

and query with:
```
select * from system.opentelemetry_span_log
```

but the result is:
```
Table system.opentelemetry_span_log doesn't exist. (UNKNOWN_TABLE)
```

**Comment by mo-avatar** [comment]
Have you configured it in the config.xml. This table seems can be used only after configuration
    <opentelemetry_span_log>
        
        <engine>
            engine MergeTree
            partition by toYYYYMM(finish_date)
            order by (finish_date, finish_time_us, trace_id)
        </engine>
        <database>system</database>
        <table>opentelemetry_span_log</table>
        <flush_interval_milliseconds>7500</flush_interval_milliseconds>
    </opentelemetry_span_log>

**Comment by zdyj3170101136** [comment]
after set opentelemetry_start_trace_probability=1, i find the table was created.

so seems that this means my http header do not contain correct oeentelemetry information?

**Comment by zdyj3170101136** [comment]
i using https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/instrumentation/net/http/otelhttp.
And  go.opentelemetry.io/otel@v1.10.0/propagation/trace_context.go:41 to inject trace context into http header.

![Uploading 截屏2022-09-30 下午3.46.17.png…]()

**Comment by zdyj3170101136** [comment]
this is the http header we send to clickhouse-server:
```
POST /?database=default&default_format=Native HTTP/1.1
Host: 10.14.65.178:3002
User-Agent: Go-http-client/1.1
Content-Length: 44
Authorization: Basic cGxhdF9pbmZyYTo3NnIyMDJyWlUxSElhRVJ5aGxqZA==
Traceparent: 00-24a7b464f3024d0bff2a87f1353d2c98-1dacccfcfd3252ed-01
Accept-Encoding: gzip

HTTP/1.1 200 OK
Date: Fri, 30 Sep 2022 08:02:14 GMT
Connection: Keep-Alive
Content-Type: application/octet-stream
X-ClickHouse-Server-Display-Name: clickhouse
Transfer-Encoding: chunked
X-ClickHouse-Query-Id: bfee220c-e5c1-4758-9975-dd1e69811e43
X-ClickHouse-Format: Native
X-ClickHouse-Timezone: Asia/Shanghai
Keep-Alive: timeout=300
X-ClickHouse-Summary: {"read_rows":"8","read_bytes":"804","written_rows":"0","written_bytes":"0","total_rows_to_read":"0"}
```

**Comment by zdyj3170101136** [comment]
oo, my problem, seems everything work right

**Comment by crakjie** [comment]
How did you correct the issue ?

**Comment by fjmjuhqc** [comment]
How did you take system.opentelemetry_span_log exist?

**Comment by fjmjuhqc** [comment]
im use clickhouse 22.8.4.7 ,it seem has some issue,i update to 22.8.16.32，and set opentelemetry_start_trace_probability=1，system.opentelemetry_span_log will auto create

**Comment by fjmjuhqc** [comment]
i am use clickhouse 22.8.4.7 ,it seem has some issue,i update to 22.8.16.32，and set opentelemetry_start_trace_probability=1，system.opentelemetry_span_log will auto create

**Comment by chancez** [comment]
I'm encountering this too, but I don't want to set `opentelemetry_start_trace_probability` because I only want spans created when an application querying CH is providing a trace. Is it possible the table is only created lazily?

**Comment by guanh-dev** [comment]
Hi @chancez , did you ever find a solution to this? We're hitting the same issue — `system.opentelemetry_span_log `doesn't exist when our init scripts run at startup. Curious if you found a clean fix without setting `opentelemetry_start_trace_probability=1`
