### ISSUE TITLE
Query with S3 Table function not working in ClickHouse server running in docker

### ISSUE THREAD

**Issue by kiwionly** [ClickHouse/ClickHouse#41966]
I am try to running query with s3 function in ClickHouse which running using docker and get error as below. However running query with S3 function in local install ClickHouse server is working properly.

**Describe what's wrong**

Error as below:
```
SELECT *
FROM s3('https://datasets-documentation.s3.eu-west-3.amazonaws.com/nyc-taxi/trips_*.gz', 'TabSeparatedWithNames')
LIMIT 10

Query id: c06f85bd-655f-425c-9ad1-3b410bd464b7


0 rows in set. Elapsed: 0.003 sec.

Received exception from server (version 22.1.3):
Code: 42. DB::Exception: Received from clickhouse-server:9000. DB::Exception: The signature of table function s3 could be the following:
 - url, format
 - url, format, structure
 - url, format, structure, compression_method
 - url, access_key_id, secret_access_key, format, structure
 - url, access_key_id, secret_access_key, format, structure, compression_method. (NUMBER_OF_ARGUMENTS_DOESNT_MATCH)
```

> A clear and concise description of what works not as it is supposed to.

**Does it reproduce on recent release?**
Not sure

[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

**Enable crash reporting**

> If possible, change "enabled" to true in "send_crash_reports" section in `config.xml`:

```
<send_crash_reports>
        <!-- Changing <enabled> to true allows sending crash reports to -->
        <!-- the ClickHouse core developers team via Sentry https://sentry.io -->
        <enabled>false</enabled>
```

**How to reproduce**

Follow clickhouse docker hub page to running docker.

1) start server instance >  docker run -d --name some-clickhouse-server --ulimit nofile=262144:262144 yandex/clickhouse-server
2) connect to it from a native client > docker run -it --rm --link some-clickhouse-server:clickhouse-server yandex/clickhouse-client --host clickhouse-server
3) Run S3 query from clickhouse doc [S3 table function](https://clickhouse.com/docs/en/integrations/s3/s3-table-functions)  > SELECT * FROM s3('https://datasets-documentation.s3.eu-west-3.amazonaws.com/nyc-taxi/trips_*.gz', 'TabSeparatedWithNames') LIMIT 10; 

* Which ClickHouse server version to use 
22.1.3
* Which interface to use, if matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

**Expected behavior**
That should be records return without error.

**Error message and/or stacktrace**

> If applicable, add screenshots to help explain your problem.

**Additional context**

That is no issue when running S3 query in clickhouse install on machine. ( not run in docker ).

> Add any other context about the problem here.

**Comment by den-crane** [comment]
22.1 is obsolete.
yandex/clickhouse-server is obsolete.

Try with modern CH version 22.9. Check that docker container has access to internet.
