### ISSUE TITLE
libhdfs3 is not built on macOS, is there any plan to support it?

### ISSUE THREAD

**Issue by FrankChen021** [ClickHouse/ClickHouse#41963]
**Operating system**

Mac M1/Intel

We're using Mac for daily work including build and debugging, but libhdfs3 currently is not supported to be built on macOS.

**Comment by yxheartipp** [comment]
Hello, I would like to work on adding support for building libhdfs3 on both M1 and Intel-based Mac. Could you please assign this issue to me? Thank you!

**Comment by alexey-milovidov** [comment]
@yxheartipp, thanks, this will be very helpful!

**Comment by yxheartipp** [comment]
@alexey-milovidov Hello, I have submitted my PR. Could you please take a look and review it when you have time? Thanks!
