### ISSUE TITLE
Not all RPM packages are signed

### ISSUE THREAD

**Issue by mcodato** [ClickHouse/ClickHouse#41968]
**Describe what's wrong**

Not all RPM packages in https://packages.clickhouse.com/rpm/stable/ are signed with the key defined inside the repo definition
https://packages.clickhouse.com/rpm/clickhouse.repo

**Expected behavior**

We expect that all RPM packages are signed and can be verified with the GPG key specified inside the repo definition.
Note that currently the `gpgcheck` is set to `0`

**Comment by Felixoid** [comment]
We don't sign packages, `gpgcheck=0` is set in https://packages.clickhouse.com/rpm/clickhouse.repo

**Comment by Felixoid** [comment]
I am unfamiliar with RPM repos infrastructure and so on, what's the reason for having packages singed as well as the repo?

Is it just an additional authentication layer? Formerly we have signed PRMs, but not the repo, see https://repo.yandex.ru/clickhouse/rpm/stable/x86_64/repodata/

In February we moved to another scheme, so now we have a signed repo.

It's pretty much the same scheme the Debian repository have.

**Comment by veqryn** [comment]
@Felixoid Is the following error I am getting related?

```
MinGW 04:12:19 ~/workspace$ docker run -it --rm clickhouse/clickhouse-server:22.3.2.2 bash
root@d4a70c56d140:/#
root@d4a70c56d140:/# apt-get update
Get:1 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Get:2 http://archive.ubuntu.com/ubuntu focal InRelease [265 kB]
Get:3 http://security.ubuntu.com/ubuntu focal-security/universe amd64 Packages [915 kB]
Get:4 https://packages.clickhouse.com/deb stable InRelease [2,484 B]
Err:4 https://packages.clickhouse.com/deb stable InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 3E4AD4719DDE9A38
Get:5 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Get:6 http://security.ubuntu.com/ubuntu focal-security/restricted amd64 Packages [1,556 kB]
Get:7 http://archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
Get:8 http://archive.ubuntu.com/ubuntu focal/main amd64 Packages [1,275 kB]
Get:9 http://security.ubuntu.com/ubuntu focal-security/multiverse amd64 Packages [27.5 kB]
Get:10 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages [2,183 kB]
Get:11 http://archive.ubuntu.com/ubuntu focal/universe amd64 Packages [11.3 MB]
Get:12 http://archive.ubuntu.com/ubuntu focal/multiverse amd64 Packages [177 kB]
Get:13 http://archive.ubuntu.com/ubuntu focal/restricted amd64 Packages [33.4 kB]
Get:14 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [1,212 kB]
Get:15 http://archive.ubuntu.com/ubuntu focal-updates/restricted amd64 Packages [1,671 kB]
Get:16 http://archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 Packages [30.2 kB]
Get:17 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [2,650 kB]
Get:18 http://archive.ubuntu.com/ubuntu focal-backports/universe amd64 Packages [27.4 kB]
Get:19 http://archive.ubuntu.com/ubuntu focal-backports/main amd64 Packages [55.2 kB]
Reading package lists... Done
W: GPG error: https://packages.clickhouse.com/deb stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 3E4AD4719DDE9A38
E: The repository 'https://packages.clickhouse.com/deb stable InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
root@d4a70c56d140:/#
```

I should be able to run `apt-get update` when inside clickhouse docker containers.  Right now, that is failing and it broke one of our builds.

**Comment by Felixoid** [comment]
22.3.2.2 is an old image and doesn't have an updated key. It can be fixed by adding `apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 8919F6BD2B48D754`

But I'd rather suggest using `22.3.13.80`.

**Comment by 11qeq11** [comment]
For anyone wondering about the question of which I was thinking myself when came up here:
**Is it safe enough to use `gpgcheck=0` with `repo_gpgcheck=1` ?**

As @Felixoid mentioned, lots of Debian repositories don't have signed packages, but have signed repository metadata, which provides both authenticity and integrity check by [following scheme](https://www.debian.org/doc/manuals/securing-debian-manual/deb-pack-sign.en.html#:~:text=7.5.1.%C2%A0The%20current%20scheme%20for%20package%20signature%20checks).

To my surprise, I wasn't able to find a similar scheme described by RHEL for YUM package manager. However, YUM repos do store metadata similarly: we have a signed `repomd.xml`, which contains checksum of all other metadata files, including checksum of `*-primary.xml.gz`, which contains various metadata about all the packages in the repository, including their checksums.

In my eyes, it would make sense to check downloaded `rpm` checksum against one provided in metadata for integrity, even without GPG sign, **and YUM does**, yet, once again, to my surprise, I did not find an exact statement in RHEL documentation about it. Luckily, looks like I was able to find it in [YUM codebase](https://github.com/rpm-software-management/yum/blob/master/yum/__init__.py#L2397-L2416), one can also check how YUM is parsing metadata [here](https://github.com/rpm-software-management/yum/blob/master/yum/packages.py#L428).

So, it seems like YUM is performing the same procedure as `apt`, and it should be safe enough to not sign all packages, but only repo metadata (just as safe as you would download many packages from official Debian repos). Though, it doesn't mean that you can't have both signed repo metadata and packages.

**P.S.** Please, correct me if I'm wrong in terms of RHEL documentation, but I really couldn't find statements about checking checksums from metadata.

**Comment by Felixoid** [comment]
Thank you for the detailed explanation. It reflects my assumptions for 100%

**Comment by benjamingroeber** [comment]
Maybe I can offer an additional point of view. Our infrastructure is fully Red Hat / RPM based and mostly isolated from the internet. We're mirroring all software with their dependencies internally with Pulp. Not always do we mirror the entire source repositories though.

If the RPM is signed, there is a quite nice option, where Pulp will refuse to mirror any package to a repository that is not signed by a given Key (e.g. in this case yours). The entire mirroring process thus can be automated and transparent and the signature of the RPM both on upload to the repo as well as on the installing machine will be checked against your public key.

If this is not the case, we've implemented a process as workaround, which requires a human interaction for verifying the origin of the RPMs to be mirrored, re-signing the packages with a dedicated key, and publishing them to a dedicated repo for this software - again - accepting only RPMs signed by - in this case - our dedicated private key.
