### ISSUE TITLE
Possible ways of returning second value from json with duplicated keys. 

### ISSUE THREAD

**Issue by ditraut** [ClickHouse/ClickHouse#41967]
Hello everyone . Could someone please help me? 
I'm working with visitParamExtract, but  in case of multiple matching field , this function is  returns  the first occurrence. 
Is it possible to get second matched field ? 
query: 

SELECT time, visitParamExtractSting(message, 'interval') as interval
FROM stage.logs dl 
WHERE time >= '2022-09-29 23:00:00'
order by time 

result: 
time                                    interval
2022-10-30 20:02:01.333   SECOND

data in "message" is looks like : 
{"body":[{"value":3,"interval":"SECOND","intervalNum":10},{"value":205015,"interval":"DAY","intervalNum":1}],"code":200,"endpoint":"/api/v3/rateLimit/order"} 

I need return interval = DAY . So query shoud return

time                                    interval
2022-10-30 20:02:01.333   DAY

https://stackoverflow.com/questions/73905713/clichouse-visitparamextract-extract-second-value-by-key-in-case-with-duplicate

**Comment by den-crane** [comment]
visitParam simple function and very fast because of that it's not possible.

You have to use JSONExtract* functions.


```
SELECT tupleElement(JSONExtract('{"body":[{"value":3,"interval":"SECOND","intervalNum":10},{"value":205015,"interval":"DAY","intervalNum":1}],"code":200,"endpoint":"/api/v3/rateLimit/order"}', 'body', 'Array(Tuple(value Int64, interval String, intervalNum Int64))'), 'interval') AS j

┌─j────────────────┐
│ ['SECOND','DAY'] │
└──────────────────┘
```
