### ISSUE TITLE
Unable to connect hdfs: getrandom call from HDFS brake compatibility with older kernels & glibc 

### ISSUE THREAD

**Issue by Rauda** [ClickHouse/ClickHouse#4197]
Hi,

I am trying using HDFS as datasource for CH 18.16.1. 
Hence, I am trying out feature as in : https://github.com/yandex/ClickHouse/tree/master/dbms/tests/integration/test_storage_hdfs (test.py)

To add:  HDFS reside into different machine than clickhouse node.

Table is created via:
`create table test_hdfs (id UInt32, name String, weight Float64) ENGINE = HDFS('hdfs://172.82.99.12:9000/test_hdfs', 'TSV');`

Select fails:
`select * from test_hdfs;`
**Message**:
2019.01.30 17:12:54.544072 [ 26 ] {} <Error> HTTPHandler: Code: 210, e.displayText() = DB::Exception: Unable to connect to HDFS: getrandom, e.what() = DB::Exception, Stack trace:

0. clickhouse-server(StackTrace::StackTrace()+0x16) [0x5e3f7e6]
1. clickhouse-server(DB::Exception::Exception(std::string const&, int)+0x1f) [0x2bce50f]
2. clickhouse-server(DB::ReadBufferFromHDFS::ReadBufferFromHDFS(std::string const&, unsigned long)+0x2f2) [0x4f811a2]
3. clickhouse-server(DB::StorageHDFS::read(std::vector<std::string, std::allocator<std::string> > const&, DB::SelectQueryInfo const&, DB::Context const&, DB::QueryProcessingStage::Enum, unsigned long, unsigned int)+0x26f) [0x4f7fc9f]
4. clickhouse-server(DB::InterpreterSelectQuery::executeFetchColumns(DB::QueryProcessingStage::Enum, DB::InterpreterSelectQuery::Pipeline&, std::shared_ptr<DB::PrewhereInfo> const&, std::vector<std::string, std::allocator<std::string> > const&)+0x14de) [0x4dce87e]
5. clickhouse-server(DB::InterpreterSelectQuery::executeImpl(DB::InterpreterSelectQuery::Pipeline&, std::shared_ptr<DB::IBlockInputStream> const&, bool)+0x3f5) [0x4dd0a15]
6. clickhouse-server(DB::InterpreterSelectQuery::executeWithMultipleStreams()+0x3a) [0x4dd343a]
7. clickhouse-server(DB::InterpreterSelectWithUnionQuery::executeWithMultipleStreams()+0x5c) [0x4ddd6bc]
8. clickhouse-server(DB::InterpreterSelectWithUnionQuery::execute()+0x26) [0x4ddd956]
9. clickhouse-server() [0x4eadddc]
10. clickhouse-server(DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, DB::Context&, std::function<void (std::string const&)>)+0xf2) [0x4eb0012]
11. clickhouse-server(DB::HTTPHandler::processQuery(Poco::Net::HTTPServerRequest&, HTMLForm&, Poco::Net::HTTPServerResponse&, DB::HTTPHandler::Output&)+0x321c) [0x2beaa3c]
12. clickhouse-server(DB::HTTPHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&)+0x42c) [0x2bed14c]
13. clickhouse-server(Poco::Net::HTTPServerConnection::run()+0x2af) [0x5fccf8f]
14. clickhouse-server(Poco::Net::TCPServerConnection::start()+0xf) [0x5fc3cef]
15. clickhouse-server(Poco::Net::TCPServerDispatcher::run()+0x166) [0x5fc40b6]
16. clickhouse-server(Poco::PooledThread::run()+0x77) [0x62755a7]
17. clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0x38) [0x6271768]
18. clickhouse-server() [0x6a7fa8f]
19. /lib64/libpthread.so.0(+0x7dc5) [0x7fc191e25dc5]
20. /lib64/libc.so.6(clone+0x6d) [0x7fc19164a73d]

**Write fails:**
`insert into test_hdfs values (10, 'tomas', 55.55), (11, 'jack', 32.54);`

Message
2019.01.30 20:16:27.211506 [ 26 ] {82c8dac1-2185-4bee-a8e4-b7de9de3e922} <Error> executeQuery: Code: 48, e.displayText() = DB::Exception: StorageHDFS write is not supported yet, e.what() = DB::Exception (from 10.150.72.16:61698) (in query: insert into saurabh_hdfs values), Stack trace:

0. clickhouse-server(StackTrace::StackTrace()+0x16) [0x5e3f7e6]
1. clickhouse-server(DB::Exception::Exception(std::string const&, int)+0x1f) [0x2bce50f]
2. clickhouse-server(DB::StorageHDFS::write(std::shared_ptr<DB::IAST> const&, DB::Settings const&)+0x3c) [0x4f7ef5c]
3. clickhouse-server(DB::PushingToViewsBlockOutputStream::PushingToViewsBlockOutputStream(std::string const&, std::string const&, std::shared_ptr<DB::IStorage> const&, DB::Context const&, std::shared_ptr<DB::IAST> const&, bool)+0x2a2) [0x522c2f2]
4. clickhouse-server(DB::InterpreterInsertQuery::execute()+0x18b) [0x4dbb25b]
5. clickhouse-server() [0x4eadddc]
6. clickhouse-server(DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, DB::Context&, std::function<void (std::string const&)>)+0xf2) [0x4eb0012]
7. clickhouse-server(DB::HTTPHandler::processQuery(Poco::Net::HTTPServerRequest&, HTMLForm&, Poco::Net::HTTPServerResponse&, DB::HTTPHandler::Output&)+0x321c) [0x2beaa3c]
8. clickhouse-server(DB::HTTPHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&)+0x42c) [0x2bed14c]
9. clickhouse-server(Poco::Net::HTTPServerConnection::run()+0x2af) [0x5fccf8f]
10. clickhouse-server(Poco::Net::TCPServerConnection::start()+0xf) [0x5fc3cef]
11. clickhouse-server(Poco::Net::TCPServerDispatcher::run()+0x166) [0x5fc40b6]
12. clickhouse-server(Poco::PooledThread::run()+0x77) [0x62755a7]
13. clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0x38) [0x6271768]

**Comment by Rauda** [comment]
Hi,

We are using:
cat /proc/version
Linux version 3.10.0-327.10.1.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.3 20140911 (Red Hat 4.8.3-9) (GCC) ) #1 SMP Tue Feb 16 17:03:50 UTC 2016

 cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

**Comment by blinkov** [comment]
сс @chenxing-xc

**Comment by chenxing-xc** [comment]
for the read problem, could you please check if the namenode:port  '172.82.99.12:9000' is correct?

**Comment by alesapin** [comment]
Unfortunately libhdfs call SYS_getrandom syscall. Seems like this syscall is absent in your kernel. We will try to fix this in next release.

**Comment by alexey-milovidov** [comment]
Fixed by @amosbird long time ago.
