### ISSUE TITLE
topK with counts

### ISSUE THREAD

**Issue by schneefux** [ClickHouse/ClickHouse#42029]
**Describe the unexpected behaviour**
Similar to #34807, I'd like to query counts for `topK` elements. 

I checked the source code and Clickhouse's SpaceSaving algorithm implements both the approximate count and error properties that I'm looking for:
https://github.com/ClickHouse/ClickHouse/blob/bf574b91547aec799364d032564606feb5a8bf03/src/Common/SpaceSaving.h#L117
but there is only a query function to return the keys themselves:
https://github.com/ClickHouse/ClickHouse/blob/778cd76987a8222217f7bf9f0c8fcb692b82b673/src/AggregateFunctions/AggregateFunctionTopK.h#L224
For a complete SpaceSaving `topK` implementation, there should be additional aggregation functions like `topKCounts` and `topKErrors` which return arrays with the count and error properties from the counter vector.

I considered the workaround suggested by @UnamedRus, but my elements have high cardinality so creating an additional map with counts is not viable.

**Comment by UnamedRus** [comment]
Or maybe it can be specified as parameters:

```
topK(column) = [val_1,val_2,val_3]
topK('value, count, error')(column) = [(val_1, count_val_1, err_val_1), (val_2, count_val_2, err_val_2), (val_3, count_val_3, err_val_3) ]
```

**Comment by nevermoressss** [comment]
whether the problem has been resolved?

**Comment by UnamedRus** [comment]
No

**Comment by UnamedRus** [comment]
Similar features in other DBMS: 
BigQuery https://cloud.google.com/bigquery/docs/reference/standard-sql/approximate_aggregate_functions#approx_top_count
SnowFlake https://docs.snowflake.com/en/sql-reference/functions/approx_top_k
DataBricks https://docs.gcp.databricks.com/sql/language-manual/functions/approx_top_k.html
StarRocks https://github.com/StarRocks/starrocks/issues/25684

**Comment by franz101** [comment]
Can be closed no? For example 
https://github.com/ClickHouse/ClickHouse/pull/54508
https://clickhouse.com/docs/en/sql-reference/aggregate-functions/reference/topkweighted

**Comment by UnamedRus** [comment]
```
SELECT topK(2, 10, 'counts')(k)
FROM VALUES('k Char, w UInt64', ('y', 1), ('y', 1), ('x', 5), ('y', 1), ('z', 10))

Query id: ebfde514-ff9d-483a-a230-9987a2375a96

┌─topK(2, 10, 'counts')(k)─┐
│ [('y',3,0),('x',1,0)]    │
└──────────────────────────┘
```

**Comment by UnamedRus** [comment]
https://github.com/Algunenano

Can close this one as well
