### ISSUE TITLE
materialized views deduplication behavior

### ISSUE THREAD

**Issue by xuyatian** [ClickHouse/ClickHouse#42035]
in the clickhouse doc:

> By default, deduplication is not performed for materialized views but is done upstream, in the source table. If an INSERTed block is skipped due to deduplication in the source table, there will be no insertion into attached materialized views. 
but in my test, it does not work as expected:

```
CREATE TABLE test
(
    `itime` DateTime,
    `loguid` UInt64
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(itime)
ORDER BY (itime, loguid)
SETTINGS index_granularity = 8192, non_replicated_deduplication_window = 100

CREATE TABLE test_mv_tbl
(
    `itime` DateTime,
    `logcnt` AggregateFunction(count)
)
ENGINE = AggregatingMergeTree
PARTITION BY toYYYYMMDD(itime)
ORDER BY toYYYYMMDD(itime)
SETTINGS index_granularity = 8192

CREATE MATERIALIZED VIEW mv TO test_mv_tbl AS
SELECT
    toDate(itime) AS itime,
    countState() AS logcnt
FROM test
GROUP BY itime

insert into test SETTINGS insert_deduplication_token = '1' values(now(), rand32())
insert into test SETTINGS insert_deduplication_token = '1' values(now(), rand32())
```

SELECT *
FROM test

Query id: b8ae8b35-81b4-42da-ad42-862884655853

┌───────────────itime─┬─────loguid─┐
│ 2022-10-03 09:50:40 │ 3498702400 │
└─────────────────────┴────────────┘
**deduplication works: only one row in the table**

SELECT
    itime,
    countMerge(logcnt)
FROM test_mv_tbl
GROUP BY itime

Query id: 72571265-2081-4835-a845-10bf5c92948c

┌───────────────itime─┬─countMerge(logcnt)─┐
│ 2022-10-03 00:00:00 │                  2 │
└─────────────────────┴────────────────────┘

**But in mv table, there are 2 rows, is it expected?**

**Comment by tbragin** [comment]
Note that behavior of deduplication in materialized views is getting reworked substantially. See this issue and linked comments and PRs for progress: https://github.com/ClickHouse/ClickHouse/issues/60008
