### ISSUE TITLE
Application: DB::Exception: No key in S3 uri - connecting Clickhouse to Oracle S3

### ISSUE THREAD

**Issue by athlatif** [ClickHouse/ClickHouse#42043]
(you don't have to strictly follow this form)

**Describe the unexpected behaviour**
I am trying to connect clickhouse with Oracle S3, and I am facing the following error:

[1] config.xml

`        <clickhouse>
          <storage_configuration>
            <disks>
              <s3_disk>
                <type>s3</type>
                <endpoint>https://xxx.compat.objectstorage.region.oraclecloud.com/clickhouse/</endpoint>
                <access_key_id>xxxx</access_key_id>
                <secret_access_key>xxxx</secret_access_key>
                <metadata_path>/var/lib/clickhouse/disks/s3_disk/</metadata_path>
                <cache_enabled>true</cache_enabled>
                <data_cache_enabled>true</data_cache_enabled>
                <cache_path>/var/lib/clickhouse/disks/s3_disk/cache/</cache_path>
              </s3_disk>
            </disks>
            <policies>
              <s3_main>
                <volumes>
                  <main>
                    <disk>s3_disk</disk>
                  </main>
                </volumes>
              </s3_main>
            </policies>
          </storage_configuration>
        </clickhouse>`

[2] Error
` <Error> Application: DB::Exception: No key in S3 uri: https://xxx.compat.objectstorage.region.oraclecloud.com/clickhouse3/: Cannot attach table `system`.`asynchronous_metric_log` from metadata file /var/lib/clickhouse/store/fxxxxx\asynchronous_metric_log.sql from query ATTACH TABLE system.asynchronous_metric_log UUID 'xxxxxxx' (`event_date` Date CODEC(Delta(2), ZSTD(1)), `event_time` DateTime CODEC(Delta(4), ZSTD(1)), `metric` LowCardinality(String) CODEC(ZSTD(1)), `value` Float64 CODEC(ZSTD(3))) ENGINE = MergeTree PARTITION BY toYYYYMM(event_date) ORDER BY (metric, event_date, event_time) SETTINGS index_granularity = 8192`

**Comment by antoniojtorres** [comment]
Having a similar issue with Wasabi. 

```
<clickhouse>
  <storage_configuration>
    <disks>
      <s3_disk>
        <type>s3</type>
        <endpoint>https://s3.eu-central-2.wasabisys.com/bucketino/</endpoint>
        <access_key_id>xxxxx</access_key_id>
        <secret_access_key>xxxxx</secret_access_key>
      </s3_disk>
    </disks>
    <policies>
      <s3_main>
        <volumes>
          <main>
            <disk>s3_disk</disk>
          </main>
        </volumes>
      </s3_main>
    </policies>
  </storage_configuration>

</clickhouse>
```

Getting a similar error too

```
2022.11.10 00:53:25.883770 [ 30562 ] {} <Error> Application: DB::Exception: No key in S3 uri: https://s3.eu-central-2.wasabisys.com/bucketino/: Cannot attach table `system`.`asynchronous_metric_log` from metadata file /var/lib/clickhouse/store/568/56841bd3-f052-466b-b7e5-xxxxxxxxx/asynchronous_metric_log.sql from query ATTACH TABLE system.asynchronous_metric_log UUID 'd4cdbe7b-55f9-4587-b01e-xxxxxxxx' (`event_date` Date CODEC(Delta(2), ZSTD(1)), `event_time` DateTime CODEC(Delta(4), ZSTD(1)), `metric` LowCardinality(String) CODEC(ZSTD(1)), `value` Float64 CODEC(ZSTD(3))) ENGINE = MergeTree PARTITION BY toYYYYMM(event_date) ORDER BY (metric, event_date, event_time) SETTINGS index_granularity = 8192
```

I've tried the endpoint url as http://[ACCESS_KEY]@s3.eu-central-2.wasabisys.com/network/ and that did not work either. 

I tested the access in a separate ftp type program and it worked just fine.

**Comment by den-crane** [comment]
>https://s3.eu-central-2.wasabisys.com/bucketino/

Path should contain a bucket and a folder, try `https://s3.eu-central-2.wasabisys.com/bucketino/qqq/` or doubleslash `https://s3.eu-central-2.wasabisys.com/bucketino//`
