### ISSUE TITLE
using minio as S3 backed mergetree: endpoint definition is wrong 

### ISSUE THREAD

**Issue by lesandie** [ClickHouse/ClickHouse#42058]
**Describe the unexpected behaviour**
As stated in documentation for s3 backed mergetree configuration the endpoint should finish with a backslash (/)
but for minio, it is not working with error:

```
2022.10.04 12:43:54.997058 [ 1 ] {} <Information> Application: Shutting down storages.
2022.10.04 12:43:54.997209 [ 1 ] {} <Debug> Application: Shut down storages.
2022.10.04 12:43:55.987739 [ 1 ] {} <Debug> Application: Destroyed global context.
2022.10.04 12:43:55.998631 [ 1 ] {} <Error> Application: DB::Exception: No key in S3 uri: http://xxx.xxx.xxx.xxx:9000/tests/: Cannot attach table `system`.`asynchronous_metric_log` from metadata file /var/lib/clickhouse/store/6c6/6c68b8cd-d03a-4544-ac68-b8cdd03a9544/asynchronous_metric_log.sql from query ATTACH TABLE system.asynchronous_metric_log UUID '40d858b5-21a7-4267-a69d-dcd4f22e418f' (`event_date` Date, `event_time` DateTime, `event_time_microseconds` DateTime64(6), `metric` LowCardinality(String), `value` Float64) ENGINE = MergeTree PARTITION BY toYYYYMM(event_date) ORDER BY (event_date, event_time) SETTINGS index_granularity = 8192
2022.10.04 12:43:55.998665 [ 1 ] {} <Information> Application: shutting down
2022.10.04 12:43:55.998670 [ 1 ] {} <Debug> Application: Uninitializing subsystem: Logging Subsystem
2022.10.04 12:43:55.998749 [ 33 ] {} <Trace> BaseDaemon: Received signal -2
2022.10.04 12:43:55.998788 [ 33 ] {} <Information> BaseDaemon: Stop SignalListener thread
```
and ClickHouse is not starting

**How to reproduce**
Simply adding an additional backslash works:
```
<endpoint>http://xxx.xxx.xxx.xxx:9000/testbucket//</endpoint>
```
But these are not needed for AWS or backblaze providers:
<endpoint>https://s3.amazonaws.com/testbucket/</endpoint>

* Which ClickHouse server version to use
Happens in 21.8+

**Expected behavior**
I would expect using only 1 backslash as AWS and other s3 providers

**Comment by DerekChia** [comment]
I'm curious, which exact MinIO and ClickHouse version are you using?

**Comment by lesandie** [comment]
Minio: minio/minio:RELEASE.2022-04-16T04-26-02Z and also minio/minio:RELEASE.2022-10-05T14-58-27Z
Clickhouse different versions, 21.8, 22.3, 22.6, 22.8

**Comment by lesandie** [comment]
As @UnamedRus commented vould it be that the double slash is related to the bucket root?. Still it is merely cosmetic but misleading.

**Comment by lesandie** [comment]
Updated documentation ... PR https://github.com/ClickHouse/clickhouse-docs/pull/384

**Comment by alexey-milovidov** [comment]
As the docs are updated, let's close this issue.
