### ISSUE TITLE
ClickHouse CLI --help output is huge

### ISSUE THREAD

**Issue by mshustov** [ClickHouse/ClickHouse#42061]
**Describe the issue**
When I run `./clickhouse client --help`, the result doesn't fit on a single screen and overflows the scroll buffer (1000 in my settings).
Such a huge is not the best UX since it's hard to navigate.

**How to reproduce**
* ClickHouse server version: `v22.9` 

**Expected behavior**
I'd expect a smaller output that a human can read.

**Comment by den-crane** [comment]
Can you use paging ?

`./clickhouse client --help|more`

**Comment by den-crane** [comment]
for example curl 230 lines
```
curl --help|wc -l
230
```

```
clickhouse-client --help|wc -l
717
```

**Comment by alexey-milovidov** [comment]
Maybe list the names of the settings without descriptions, without line breaks?
Or replace the list of query-level settings with the link to the docs?

**Comment by Algunenano** [comment]
To me having the list of settings in the client is helpful since I usually do something like `clickhouse client --help | grep whatever` when I want to look for something.

Maybe there is a better way to do this based on categories. For example, in recent curl (did they get this same discussion recently?) I get way less lines:
```
$ curl --help
Usage: curl [options...] <url>
 -d, --data <data>          HTTP POST data
 -f, --fail                 Fail fast with no output on HTTP errors
 -h, --help <category>      Get help for commands
 -i, --include              Include protocol response headers in the output
 -o, --output <file>        Write to file instead of stdout
 -O, --remote-name          Write output to a file named as the remote file
 -s, --silent               Silent mode
 -T, --upload-file <file>   Transfer local FILE to destination
 -u, --user <user:password> Server user and password
 -A, --user-agent <name>    Send User-Agent <name> to server
 -v, --verbose              Make the operation more talkative
 -V, --version              Show version number and quit

This is not the full help, this menu is stripped into categories.
Use "--help category" to get an overview of all categories.
For all options use the manual or "--help all"
```

What about something copying `--help <category>` and have some categories like connectivity (port, host), client (echo, queries-file...), query settings (max_threads, max_rows_to_read)... Just a thought.

**Comment by azat** [comment]
Maybe it will be good to implement auto-pager like git has, i.e. `git diff --help`

>To me having the list of settings in the client is helpful since I usually do something like clickhouse client --help | grep whatever when I want to look for something.

They are also used for autocompletion (but it exists only for bash right now), so instead of grepping you can simply use `clickhouse-client --max<tab><tab>`
