### ISSUE TITLE
cannot use `CREATE DATABASE ... ENGINE=MySQL`  and hidden password for users

### ISSUE THREAD

**Issue by lksv** [ClickHouse/ClickHouse#42087]
I have configured mysql as:
 
```xml
    <named_collections>
      <sklik_money>
            <user>clickhouse_ro</user>
            <password>xxxxxxxx</password>
            <host>xxxx.xxx.xxxx.cz</host>
            <port>3306</port>
            <database>sklik_money</database>
            <connection_pool_size>4</connection_pool_size>
            <on_duplicate_clause>1</on_duplicate_clause>
            <replace_query>1</replace_query>
      </sklik_money>
      ...
      </named_collections>
```

Then created database with MySQL Engine:

```sql
CREATE DATABASE sklik_money ENGINE = MySQL(sklik_money);
```

then all users with `GRANT SELECT` can see the passowrd:

```sql
│ CREATE TABLE sklik_money.api_credit
(
    ...
)
ENGINE = MySQL('xxx.xxx.xxx.cz:3306', 'sklik_money', 'api_credit', 'clickhouse_ro', 'PASWORD-IS-VISSIBLE-HERE') │
```

Workaround exists, but not comfortable:

1. If uses do remember table names, they can use directly mysql engine:
   ```sql
   SELECT count() FROM mysql(sklik_money, table = 'api_credit');
   ```
   They can even use `DESCRIBE mysql(sklik_money, table = 'api_credit')` to see column definition (but they needs to know it, it's not straight for them).
2. write a script which:
    for each table in mysql database run:
        `CREATE TABLE $table ENGINE = MySQL(sklik_money, table = '$table') EMPTY AS SELECT * FROM mysql(sklik_money, table = '$table')`

Ideal solution would be that `CREATE DATABASE sklik_money ENGINE = MySQL(sklik_money)`  create tables with engine configuration `ENGINE = mysql(sklik_money, table = '...')` insead of ` MySQL(URLl, 'sklik_money', TABLE, USER, VISIBLE_PASSWORD)`

**Comment by kssenii** [comment]
it works as you expect it to work it seems:
```
ip-172-31-4-213.eu-west-1.compute.internal :) create database mysql engine=MySQL(mysql);

CREATE DATABASE mysql
ENGINE = MySQL(mysql)

Query id: e77b895d-90f4-4e94-9c8e-b3fd2ac3790f

Ok.

0 rows in set. Elapsed: 0.223 sec.

ip-172-31-4-213.eu-west-1.compute.internal :) show tables from mysql

SHOW TABLES FROM mysql

Query id: ebf25d94-ae57-446d-8eed-791481b8e544

┌─name─┐
│ test │
└──────┘

1 row in set. Elapsed: 0.121 sec.

ip-172-31-4-213.eu-west-1.compute.internal :) show create table mysql.test

SHOW CREATE TABLE mysql.test

Query id: ad967612-44f6-4c7d-a0b1-0017b9d77a05

┌─statement─────────────────────────────────────────────────────────────────────────────┐
│ CREATE TABLE mysql.test
(
    `a` Nullable(Int32)
)
ENGINE = MySQL(mysql, table = 'test') │
└───────────────────────────────────────────────────────────────────────────────────────┘

1 row in set. Elapsed: 0.032 sec.

ip-172-31-4-213.eu-west-1.compute.internal :)
```

**Comment by den-crane** [comment]
@lksv What Clickhouse version do you use?

**Comment by lksv** [comment]
I use `22.9.3.18`:

```bash
root@clickhouse:~# apt-cache policy clickhouse-server
clickhouse-server:
  Installed: 22.9.3.18
  Candidate: 22.9.3.18
  Version table:
 *** 22.9.3.18 500
        500 https://packages.clickhouse.com/deb stable/main amd64 Packages
        100 /var/lib/dpkg/status
...
```

The problem is probably on my side, I tested it again and all work:
* When I use `CREATE DATABASE sklik_money ENGINE=MySQL('sklik_money', 'user', 'password');` then the password is accessible in show create table,
* but when I use `CREATE DATABASE sklik_money ENGINE=MySQL(sklik_money);`  then the password in not visible (all tables use mysql engine with named collection configuration).

I am sorry. It mistake on my side, closing the issue.
