### ISSUE TITLE
MaterializedMySQL  high CPU usage and load averages

### ISSUE THREAD

**Issue by invipal** [ClickHouse/ClickHouse#42105]
**Describe the unexpected behaviour**
Hi, we are using MaterializedMySQL for our chat messages, everything going well for first 1 or 2 days (daily 100K messages, total 3M messages). And then, CPU usage goes to %1000 and load averages goes to 90s. There is no error log etc. 

When we create new MaterializedMySQL database with same settings and drop old one, everything working as expected. And this circle start again after 1 or 2 days. 

I know, MaterializedMySQL is experimental but, I want to ask do you have any experience about this type problem, and if yes, how did you solve it?

**How to reproduce**
ClickHouse Version: 22.10.1.149

```
CREATE DATABASE chat
ENGINE = MaterializedMySQL(
  '127.0.0.1:3306', 
  'mysql_db', 
  'mysql_user', 
  'mysql_password'
)
SETTINGS
        max_rows_in_buffer=130000,
        max_bytes_in_buffer=1073741824,
        max_flush_data_time=3000,
        allows_query_when_mysql_lost=true,
        max_wait_time_when_mysql_unavailable=10000;
```

**Additional context**
We have the same problem when we use MaterializedMySQL with its default settings.

**Comment by alexey-milovidov** [comment]
@stigsb your help is needed.

**Comment by stigsb** [comment]
@invipal are there a lot of parts in your tables? Can you share primary keys from them?

The replication process itself is single threaded, so those 1000% must be from merges or queries. Check system.merges and .query_log for insight?

**Comment by stigsb** [comment]
@invipal try some of these queries:

See if the number of parts has increased in your queries over the last 2 days:

```sql
SELECT
    toStartOfHour(event_time) AS event_hour, tables[1] AS table,
    round(avg(ProfileEvents['SelectedParts']),1) AS avg_parts
FROM system.query_log
WHERE event_time >= now() - INTERVAL 2 DAY AND has(databases, 'your-db') AND ProfileEvents['SelectedParts'] > 0
GROUP BY event_hour, table
ORDER BY event_hour, table
```

(This assumes you're not doing any joins, if you do then replace `tables[1] AS table` with just `tables`.)

If there's an upward trend here, it means ClickHouse is not able to keep up with merges, leaving you with a lot of small parts which slows things down. Adjust your buffer settings to manage the size of your inserted parts. I noticed that you are only setting `max_rows_in_buffer` and `max_bytes_in_buffer, and not the `max_rows_in_buffers` / `max_bytes_in_buffers` settings. The latter two control the buffer for all tables, the former two control the buffer per table. The default value is 1MiB, so that could be your problem.

You can try verifying by checking merge activity:

```sql
SELECT
    toStartOfHour(event_time) AS event_hour,
    round(avg(CurrentMetric_Merge),1) AS avg_merges,
    min(CurrentMetric_Merge) AS min_merges,
    max(CurrentMetric_Merge) AS max_merges
FROM system.metric_log
WHERE event_time >= now() - INTERVAL 2 DAY
GROUP BY event_hour
ORDER BY event_hour
```

**Comment by Alpha-su** [comment]
Thanks for your answer @stigsb It's also very inspiring to me. But I ran into another problem while using MaterializedMysql. That is, MaterializedMysql's synchronization significantly **lags behind** Mysql-Server. For Example, the latest data in mysql is 2022-10-13. but the latest data in MaterializedMysql is 2022-10-01, and there is no error or exception raising.  I will appreciate very much if you can give me some advise to find and solve this problem.

**Comment by stigsb** [comment]
> Thanks for your answer @stigsb It's also very inspiring to me. But I ran into another problem while using MaterializedMysql. That is, MaterializedMysql's synchronization significantly **lags behind** Mysql-Server. For Example, the latest data in mysql is 2022-10-13. but the latest data in MaterializedMysql is 2022-10-01, and there is no error or exception raising.  I will appreciate very much if you can give me some advise to find and solve this problem. 

Please create a separate issue for this, including some details about the number of tables, total number of columns and rate of changes in the binlog.

**Comment by stigsb** [comment]
What did you find out @invipal ?

**Comment by hipotures** [comment]
In our case (high load, lag replication) there was millions deletes in mysql in short time. We change virtual server from 1 cpu do 16 cpu (GCP). IO load jumped from few % to 100%, cpu to 1600%, but after 4-6 hours everything finished, cpu load dropped to normal (~0.5), io load similar, replication lag drop to 0. Clichouse doesn't like mass updates/deletes.

**Comment by stigsb** [comment]
Each row deleted translates to a row inserted in MaterializedMySQL, with whatever that means for system load. CPU jumping to 1600% with 16 cores just means ClickHouse is able to fully utilize the hardware ;-)

I believe this issue can be closed now, @alexey-milovidov
