### ISSUE TITLE
Allow to set up a limit on the maximum number of databases, tables, and the maximum number of tables in a database.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#42109]
**Describe the solution you'd like**

These limits can be implemented as query-level settings and checked on CREATE, ATTACH and RENAME queries.

They will be query-level settings, and can be set up on a per-user basis, but checked regardless of what user created what tables, just by the total number of tables and databases at the time of the query.

The databases with implicit table creation (MySQL, PostgreSQL, SQLite, MaterializedMySQL, MaterializedPostgreSQL, and our future S3, HDFS, and File database engines) should not contribute to the counters.

The setting about the maximum number of tables in a database will check against the database where the table is going to be created.

For the total number of tables and databases, CurrentMetrics can be used.

The limitations are not checked on server startup and on the repair of Replicated database, nor on the replication of the Replicated database. Only user-initiated queries are checked.

REPLACE TABLE query may check the limitations (if they are already exceeded), although it's also ok to omit the check.

**Comment by UnamedRus** [comment]
Suggested limits:

Number of tables (system-wide, across all databases)

non-replicated MergeTree-family tables = few thousands is still acceptable, if you don’t do realtime inserts in more that few dozens of them. See [#32259](https://github.com/ClickHouse/ClickHouse/issues/32259)
ReplicatedXXXMergeTree = few hundreds is still acceptable, if you don’t do realtime inserts in more that few dozens of them. Every Replicated table comes with it’s own cost (need to do housekeepeing operations, monitoing replication queues etc). See [#31919](https://github.com/ClickHouse/ClickHouse/issues/31919)
Log family table = even dozens of thousands is still ok, especially if database engine = Lazy is used.

Number of databases
Fewer than number of tables (above). Dozens / hundreds is usually still acceptable.

[source](https://kb.altinity.com/altinity-kb-schema-design/how-much-is-too-much/#number-of-tables-system-wide-across-all-databases)

**Comment by Slach** [comment]
Just for google search
look 
https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings#max-table-num-to-throw
and
https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings#max-table-num-to-throw
