### ISSUE TITLE
Can I use regular expression on Kafka topic list?

### ISSUE THREAD

**Issue by chu1070y** [ClickHouse/ClickHouse#42113]
Hi

I have many topics from multiple tables on kafka and I need to load data to clickhouse,
I tried to use regular expression to kafka topic list on kafka engine.
I don't think it works..

It doesn't support regex, right?

**Comment by filimonov** [comment]
The underlying library (librdkafka) supports that, so it should also work in clickhouse (but it was not tested):

```
 * Wildcard (regex) topics are supported:
 * any topic name in the \p topics list that is prefixed with \c \"^\" will
 * be regex-matched to the full list of topics in the cluster and matching
 * topics will be added to the subscription list.
 *
 * The full topic list is retrieved every \c topic.metadata.refresh.interval.ms
 * to pick up new or delete topics that match the subscription.
 * If there is any change to the matched topics the consumer will
 * immediately rejoin the group with the updated set of subscribed topics
```

https://github.com/edenhill/librdkafka/blob/b871fdabab84b2ea1be3866a2ded4def7e31b006/src/rdkafka.h#L3899-L3938

So to make librdkafka understand that you provided the regexp - it should have `^` symbol, i.e. try using 
```
kafka_topic_list='^regex.*'
```

Please comment if it works.

P.S. Also there is a librdkafka setting `topic.blacklist`. which can be used to exclude something which should not be added to subscription.

**Comment by chu1070y** [comment]
it worked. Thank you :)
