### ISSUE TITLE
Unable to start *clickhouse.DDLSource

### ISSUE THREAD

**Issue by kendrickzae** [ClickHouse/ClickHouse#42133]
I'm getting this error:

_**Unable to Activate
 error unable to upload (v2): upload failed: unable upload part /research."all_serp_competitor"(all_32419_34397_6_34830): unable to start *clickhouse.DDLSource event source: unable to apply DDLs: error executing DDL: unable to adjust DDL: unable to set replicated table engine: unable to parse engine from ddl: Unsupported engine: 'CREATE TABLE IF NOT EXISTS research.all_serp_competitor UUID 'fe7491ee-102b-40b1-be74-91ee102b90b1'  ON CLUSTER `chclpinrb4126vagc689` (`timestamp` DateTime DEFAULT now(), `keyword` String, `country` String, `lang` String, `organicRank` UInt8, `search_volume` UInt64, `url` String, `subDomain` String, `domain` String, `path` String, `etv` UInt64, `clickstream_etv` Float64, `related` Array(String), `estimated_traffic` UInt64 DEFAULT CAST(multiIf(organicRank = 1, search_volume * 0.3197, organicRank = 2, search_volume * 0.1551, organicRank = 3, search_volume * 0.0932, organicRank = 4, search_volume * 0.0593, organicRank = 5, search_volume * 0.041, organicRank = 6, search_volume * 0.029, organicRank = 7, search_volume * 0.0213, organicRank = 8, search_volume * 0.0163, organicRank = 9, search_volume * 0.0131, organicRank = 10, search_volume * 0.0108, organicRank = 11, search_volume * 0.01, organicRank = 12, search_volume * 0.0112, organicRank = 13, search_volume * 0.0124, organicRank = 14, search_volume * 0.0114, organicRank = 15, search_volume * 0.0103, organicRank = 16, search_volume * 0.0099, organicRank = 17, search_volume * 0.0094, organicRank = 18, search_volume * 0.0081, organicRank = 19, search_volume * 0.0076, organicRank = 20, search_volume * 0.0067, 0.), 'Int64'), INDEX timestamp_minmax timestamp TYPE minmax GRANULARITY 8192, INDEX domain_bf domain TYPE bloom_filter GRANULARITY 65536, PROJECTION order_by_keyword__domain_country_lang_organic_rank (SELECT keyword, domain, country, lang, organicRank ORDER BY keyword), PROJECTION order_by_organic_rank__keyword_domain_country_lang_organic_rank (SELECT keyword, domain, country, lang, organicRank ORDER BY organicRank)) ENGINE = MergeTree ORDER BY (country, domain) SETTINGS index_granularity = 8192'**_

I already transferred two tables from this database to managed cluster, but this one raises an error.

Are you guys familiar with this error? please help.

**Comment by den-crane** [comment]
What you mean by "managed cluster" ?

>Unsupported engine

This is not Clickhouse error.
