### ISSUE TITLE
How can I backfill one column from another column in the same row?

### ISSUE THREAD

**Issue by yandongl** [ClickHouse/ClickHouse#42183]
for example, I have one table like

```
CREATE TABLE argus_local.content_info ( 
`timestamp` Int64, 
`content_id` String) 
ENGINE = MergeTree 
PARTITION BY toDate(CAST(intDiv(timestamp, 1000), 'DateTime')) 
ORDER BY timestamp TTL toDateTime(timestamp / 1000) + toIntervalDay(90) 
SETTINGS index_granularity = 8192
```

timestamp  | content_id
------------- | -------------
1,657,447,200,000   | 1000257103
1,657,417,200,000  | 1000257104
1,657,835,200,000   | 1000257105
1,657,873,200,000  | 1000257106
1,657,974,200,000   | 1000257107
1,657,097,200,000  | 1000257108
1,657,491,200,000   | 1000257109
1,657,074,200,000  | 1000257110

NOW, I want to add a new col named `content_id_2` String, and use content_id in the same row to backfill.
like:

timestamp  | content_id | content_id_2
------------- | ------------- | -------------
1,657,447,200,000   | 1000257103 | 1000257103
1,657,417,200,000  | 1000257104 | 1000257104
1,657,835,200,000   | 1000257105 | 1000257105
1,657,873,200,000  | 1000257106 | 1000257106
1,657,974,200,000   | 1000257107 | 1000257107
1,657,097,200,000  | 1000257108 | 1000257108
1,657,491,200,000   | 1000257109 | 1000257109
1,657,074,200,000  | 1000257110 | 1000257110

So, How can I backfill one column from another column in the same row?

Thanks in advance

**Comment by genzgd** [comment]
```
ALTER TABLE argus_local.content_info ADD COLUMN content_id_2 String
ALTER TABLE argus_local.content_info UPDATE content_id_2 = content_id_1 WHERE 1
```

You could also do something like this:
```
ALTER TABLE argus_local.content_info ADD COLUMN content_id_2 String DEFAULT content_id_1
```

In that case the `content_id_2` column will return the value of `content_id_1` unless it is set explicitly.

**Comment by yandongl** [comment]
thanks @genzgd

**Comment by Recodify** [comment]
@genzgd Also you might want to checkout this PR: https://github.com/ClickHouse/ClickHouse/issues/33203
For a possibly solution for you right now, see my comment: https://github.com/ClickHouse/ClickHouse/issues/33203#issuecomment-1473590370
