### ISSUE TITLE
Is this LTS website worked? https://repo.yandex.ru/clickhouse/rpm/lts/x86_64/

### ISSUE THREAD

**Issue by intfish123** [ClickHouse/ClickHouse#42182]
https://repo.yandex.ru/clickhouse/rpm/lts/x86_64/

**Comment by alexey-milovidov** [comment]
No, this is the obsolete repository, we no longer have access to it.

**Comment by Felixoid** [comment]
https://clickhouse.com/docs/en/install/#from-rpm-packages

**Comment by Felixoid** [comment]
Tonight the archiving of [https://repo.yandex.ru/clickhouse/](https://repo.yandex.ru/clickhouse/rpm/lts/x86_64/) is done and now available at https://packages.clickhouse.com/repo-archive/

**Comment by intfish123** [comment]
ok, thank u
