### ISSUE TITLE
Documentation about Primary index is incorrect

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#42205]
https://clickhouse.com/docs/en/guides/improving-query-performance/sparse-primary-indexes/sparse-primary-indexes-design/#the-primary-index-has-one-entry-per-granule

_Index entries (index marks) are not based on specific rows from our table but on granules. E.g. for index entry ‘mark 0’ in the diagram above there is no row in our table where UserID is 240.923 and URL is "goal://metry=10000467796a411...", instead, there is a granule 0 for the table where within that granule the minimum UserID vale is 240.923 and the minimum URL value is "goal://metry=10000467796a411..." and these two values are from separate rows._

https://stackoverflow.com/questions/74001911/is-clickhouse-primary-key-first-row-of-the-granule-or-not

Primary index does contain values from the first row of the granule not some minimum value of the column of the granule. 
Pictures are incorrect as well.

**Comment by den-crane** [comment]
```
select * from hits_UserID_URL order by UserID, URL, EventTime limit 1;
┌─UserID─┬─URL──────────────────────────────────────────────────────────────────────────────────────────────────────┬───────────EventTime─┐
│ 240923 │ http://showtopics.html%3Fhtml&gm=1&language=55.8122143017261877709589/prv--barsename/frm_index.ru/logoda │ 2014-03-23 04:39:21 │
└────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────┴─────────────────────┘


select * from hits_UserID_URL order by UserID, URL, EventTime limit 8192,1;
┌──UserID─┬─URL──────────────────┬───────────EventTime─┐
│ 4073710 │ http://mk.ru&pos=3_0 │ 2014-03-21 00:27:07 │
└─────────┴──────────────────────┴─────────────────────┘

select * from hits_UserID_URL order by UserID, URL, EventTime limit 16384,1;
┌───UserID─┬─URL─────────────────────────────────────────────────────────────────────────────────────┬───────────EventTime─┐
│ 10487847 │ http://marinance.ua/clck/jsredircnt=1395294/price_val2=40&hiddeo.mail.yandsearch?cl4url │ 2014-03-17 09:36:40 │
└──────────┴─────────────────────────────────────────────────────────────────────────────────────────┴─────────────────────┘

# strings primary.idx |head -3
hhttp://showtopics.html%3Fhtml&gm=1&language=55.8122143017261877709589/prv--barsename/frm_index.ru/logoda
http://mk.ru&pos=3_0'
Whttp://marinance.ua/clck/jsredircnt=1395294/price_val2=40&hiddeo.mail.yandsearch?cl4url
```

**Comment by alexey-milovidov** [comment]
@tom-clickhouse confirmed the mistake and is going to apply the necessary changes to the docs.

**Comment by tom-clickhouse** [comment]
Fixed by https://github.com/ClickHouse/clickhouse-docs/pull/640 and https://github.com/ClickHouse/clickhouse-docs/pull/642
