### ISSUE TITLE
Data replicated in cluster shares

### ISSUE THREAD

**Issue by taotaizhu-pw** [ClickHouse/ClickHouse#42200]
2 shares 2 relica. 

share1: chserver1, chserver3
share2: chserver2, chserver4

When insert one record into chserver1, it was inserted into all the 4 node tables. It should be exist in chserver1 and chserver3 

Any incorrect config? 

confile.xml
![image](https://user-images.githubusercontent.com/79344970/194739662-d58acecb-1055-4e40-9196-fc6498c4256f.png)

metrika.xml
![image](https://user-images.githubusercontent.com/79344970/194739805-d235d694-6da1-4585-aafd-6627d3906e5a.png)

[metrika.txt](https://github.com/ClickHouse/ClickHouse/files/9740809/metrika.txt)
[config.txt](https://github.com/ClickHouse/ClickHouse/files/9740810/config.txt)

**Comment by den-crane** [comment]
Here is the probable cause: Clickhouse Replicated tables know nothing about `remote_servers` config, they simply don't use it. Replication works using ZK path which is in the table definition. You did not provide any information how you have created Replicated tables, so it's impossible to answer more.

This should be different on each server:

```
    <macros>
        <shard>node01</shard>
        <replica>chserver1</replica>
    </macros>
```

**Comment by den-crane** [comment]
You macros configuration is incorrect.

It should be

```
<macros>
    <shard>1</shard>
    <replica>chserver1</replica>
</macros>

<macros>
    <shard>2</shard>
    <replica>chserver2</replica>
</macros>

<macros>
    <shard>1</shard>
    <replica>chserver3</replica>
</macros>

<macros>
    <shard>2</shard>
    <replica>chserver4</replica>
</macros>
```

**Comment by taotaizhu-pw** [comment]
> You macros configuration is incorrect.
> 
> It should be
> 
> ```
> <macros>
>     <shard>1</shard>
>     <replica>chserver1</replica>
> </macros>
> 
> <macros>
>     <shard>2</shard>
>     <replica>chserver2</replica>
> </macros>
> 
> <macros>
>     <shard>1</shard>
>     <replica>chserver3</replica>
> </macros>
> 
> <macros>
>     <shard>2</shard>
>     <replica>chserver4</replica>
> </macros>
> ```

Thanks, works fine
