### ISSUE TITLE
Create view on cluster fails with group by

### ISSUE THREAD

**Issue by jeejeeone** [ClickHouse/ClickHouse#42218]
Using version 22.3.12.20.altinitystable create view with on cluster and group by fails. Reproduce (in default db):

```
use default;

CREATE TABLE test_table ON CLUSTER '{cluster}' (id UInt64, sub_id UInt64, name String) ENGINE = TinyLog;
INSERT INTO test_table VALUES (1, 2, 'zap');

CREATE VIEW test_table_view ON CLUSTER '{cluster}' AS SELECT id FROM test_table GROUP BY (id, sub_id);
``` 

Error in all nodes:
```
Code: 215. DB::Exception: Column `id` is not under aggregate function and not in GROUP BY: While processing id. (NOT_AN_AGGREGATE) (version 22.3.12.20.altinitystable (altinity build))
```

As far as I understand there is nothing wrong with the query and view should be successfully created. Create view without on cluster clause works, query run separately works.

**Comment by den-crane** [comment]
You need to remove `( )` -- `FROM test_table GROUP BY id, sub_id;`

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/36016
