### ISSUE TITLE
Introduce parallelism while "staging" block in AzureBlobStorage storage policy

### ISSUE THREAD

**Issue by jmassiot** [ClickHouse/ClickHouse#42219]
**Describe the situation**

This request come after what has already been done in #41754 & #42041.
It aims at having on the `AsureBlobStorage` storage policy the same "strategy" as what we have for S3 in term of parallelization of "block"/"multi-part" uploads.

In S3, multi-parts are uploaded in parallel through the use of a `ThreadPoolWriter` (https://github.com/ClickHouse/ClickHouse/blob/v22.8.3.13-lts/src/Disks/ObjectStorages/IObjectStorage.h#L133)

The idea here will be to have the same kind of parallelization on Azure when "blocks" are "staged" (`stageBlock` call to the Azure API).

I do not have evidence that it will improve significantly the performance (tests maybe to be planned in the context of this feature request), but in theory, it should help.

**Comment by alexey-milovidov** [comment]
Let's ask @jkuklis

**Comment by alexey-milovidov** [comment]
@jkuklis is currently the only maintainer of the Azure blob storage integration.
