### ISSUE TITLE
RFC: 'autotier'-alike disks

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#42212]
Reference https://github.com/45Drives/autotier

Usecase: keep files that are actively used on the fast&expensive disks (SSD / NVMe) and the stuff which is not used often on slow & cheap disks.

Alternatives:
* multitier setup with part size or with TTL: often confusing/hard to set up/works on the level of whole parts (so you can not move away a single column, which is not used often to another drive, or just pk / marks). 
* cache disks: it actually creates copies of the data, which is already stored on some slow disks. Cache data is considered temporary / can be dropped, only a single 'boost tier' is available.

Also may be it's possible to reimplement the current multitiered setup with some other kind of 'smart' disks, if the disk will know 'something' about the structure of paths/filders / i.e. age & size of parts (questionable).

**Comment by alexey-milovidov** [comment]
Cache works quite alright, we use it.

**Comment by filimonov** [comment]
Imagine you need to write the data fast. If you will 'write through' via cache, you limit the write speed to the speed of the slow storage.

**Comment by alexey-milovidov** [comment]
You can check ClickHouse Cloud, which is using object storage and allows writing data fast.
