### ISSUE TITLE
Unable to update clickhouse-server, 404 Not found

### ISSUE THREAD

**Issue by Borks** [ClickHouse/ClickHouse#42215]
**Describe the unexpected behaviour**
using sudo apt-get install clickhouse-client clickhouse-server results in 404

**How to reproduce**
Try to update clickhouse via deb package

**Expected behavior**
Clickhouse updates.

**Error message and/or stacktrace**
![image](https://user-images.githubusercontent.com/5571023/194841901-cce4c352-aeb8-4c52-99db-1d024003cbeb.png)

**Additional context**
also public key not available when running sudo apt-get update
![image](https://user-images.githubusercontent.com/5571023/194842023-a068483c-2b19-4c29-907e-8aa0948caa6d.png)

**Comment by Felixoid** [comment]
Please, update the public key
