### ISSUE TITLE
Unexpected / incorrect result when selecting from Buffer table with ORDER BY DESC

### ISSUE THREAD

**Issue by jzombi** [ClickHouse/ClickHouse#42226]
**Describe what's wrong**

Selecting from a Buffer table with ORDER BY <col> DESC clause returns wrong rows, and the returned rows are not ordered.

**Does it reproduce on recent release?**

Tested version: 22.7.2.15

**How to reproduce**

* Which ClickHouse server version to use
22.7.2.15
* `CREATE TABLE` statements for all tables involved

        CREATE TABLE mydb.mytable_stored
        (
            `a` UInt8
        )
        ENGINE = MergeTree
        ORDER BY a;

        CREATE TABLE mydb.mytable
        (
            `a` UInt8
        )
        ENGINE = Buffer('mydb', 'mytable_stored', 4, 600, 3600, 10, 100, 10000, 10000000);

* Sample data for all these tables
Note: rows must be inserted one-by-one:

        INSERT INTO mydb.mytable VALUES (0);
        INSERT INTO mydb.mytable VALUES (1);
        INSERT INTO mydb.mytable VALUES (2);
        INSERT INTO mydb.mytable VALUES (3);
        INSERT INTO mydb.mytable VALUES (4);
        INSERT INTO mydb.mytable VALUES (5);
        INSERT INTO mydb.mytable VALUES (6);
        INSERT INTO mydb.mytable VALUES (7);
        INSERT INTO mydb.mytable VALUES (8);
        INSERT INTO mydb.mytable VALUES (9);

* Queries to run that lead to unexpected result

        SELECT a FROM mydb.mytable ORDER BY a DESC LIMIT 5;
        ┌─a─┐
        │ 3 │
        │ 7 │
        └───┘
        ┌─a─┐
        │ 2 │
        │ 6 │
        └───┘
        ┌─a─┐
        │ 1 │
        └───┘
        5 rows in set. Elapsed: 0.007 sec.

(Interestingly, ascending order *seems* to work, did not test it thoroughly though.)

**Expected behavior**

Get the results in descending order, ie. `9, 8, 7, 6, 5`.

**Additional context**

Selecting the maximal value works:

        SELECT max(a) FROM mydb.mytable;
        ┌─max(a)─┐
        │      9 │
        └────────┘
        1 row in set. Elapsed: 0.007 sec.

After the rows are flushed to the backing MergeTree table, the results are good.

        OPTIMIZE TABLE mydb.mytable;
        SELECT a FROM mydb.mytable ORDER BY a DESC LIMIT 5;
        ┌─a─┐
        │ 9 │
        │ 8 │
        │ 7 │
        │ 6 │
        │ 5 │
        └───┘
        5 rows in set. Elapsed: 0.008 sec.

**Comment by den-crane** [comment]
https://fiddle.clickhouse.com/f6b5f181-1316-4588-adca-9aa0cb72e8d3

```sql
SELECT a FROM mytable ORDER BY a DESC LIMIT 5 settings optimize_read_in_order=0;
9
8
7
6
5

```

**Comment by canhld94** [comment]
```
EXPLAIN PIPELINE
SELECT a
FROM mydb.mytable
ORDER BY a DESC
LIMIT 5

Query id: 10d59ddd-9f8f-4364-9c0e-c9f2e49066b0

┌─explain──────────────────────────┐
│ (Expression)                     │
│ ExpressionTransform              │
│   (Limit)                        │
│   Limit                          │
│     (Sorting)                    │
│     MergingSortedTransform 4 → 1 │
│       (Expression)               │
│       ExpressionTransform × 4    │
│         (ReadFromPreparedSource) │
│         Buffer × 4 0 → 1         │
└──────────────────────────────────┘
```

Missing `ReverseTransform` when reading from buffer with `optimize_read_in_order` DESC
