### ISSUE TITLE
STS Assume Role from profile is not supported

### ISSUE THREAD

**Issue by pkit** [ClickHouse/ClickHouse#42221]
Kind of a re-raise of #39526
The problem is:
Clickhouse uses a pretty old `aws-sdk-cpp` and re-implements some "later" features on top of it.
But that version does not support the so called `STSProfileCredentialsProvider` which is used for delegation via profiles (see [here](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-role.html#cli-configure-role-xaccount))

I.e. this one doesn't work:
```
[profile crossaccountrole]
role_arn = arn:aws:iam::234567890123:role/SomeRole
source_profile = default
external_id = 123456
```

I think it can be fixed by reusing a newer `aws-sdk-cpp` ([here](https://github.com/aws/aws-sdk-cpp/blob/bb1fdce01cc7e8ae2fe7162f24c8836e9d3ab0a2/aws-cpp-sdk-identity-management/source/auth/STSProfileCredentialsProvider.cpp))
I can start working on it.

**Comment by alexey-milovidov** [comment]
S3 SDK should be updated.

**Comment by alexey-milovidov** [comment]
> I can start working on it.

https://github.com/ClickHouse/ClickHouse/pull/43020

**Comment by pkit** [comment]
@alexey-milovidov sorry, still working on Morton index rn

**Comment by jspri** [comment]
Did anyone test this? I have a similar setup to the OP and have been unable to get it to work.

```
[default]
aws_access_key_id = xxxxxxxxxxxx
aws_secret_access_key = xxxxxxxxx
role_arn = arn:aws:iam::xxx:role/xxx
source_profile = default
```

**Comment by prasanth-seedata-io** [comment]
this still doesn't work

cat ~/.aws/credentials 
[default]
aws_access_key_id=xxx
aws_secret_access_key=yyy
role_arn=arn:aws:iam::zzz:role/OrganizationAccountAccessRole
external_id=123456
source_profile = default

cat /etc/clickhouse-server/config.d/s3.xml 
<clickhouse>
    <s3>
        <endpoint-name>
		<endpoint>https://blabla-conn.s3.eu-west-2.amazonaws.com</endpoint>
		<use_environment_credentials>true</use_environment_credentials>
        </endpoint-name>
    </s3>
</clickhouse>

would love to know how I can use this functionality @pkit

**Comment by xianzheTM** [comment]
hello，It still seems to have issues. Is this feature not finished?
