### ISSUE TITLE
Clickhouse POCO Exception on Grafana

### ISSUE THREAD

**Issue by dwaipayan05** [ClickHouse/ClickHouse#42231]
(you don't have to strictly follow this form)

**Describe the unexpected behaviour**
Clickhouse Client throwing unexpected error when using a Proxy on Grafana

**How to reproduce**
* Clickhouse running on percona (docker)
* Using a proxy for the percona docker
* When a request is routed through `/api/datasource/proxy/` of the proxy, it throws the error 

```
Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = No authentication information found: Basic authentication expected (version 21.3.14.1 (official build))

```

**Expected behavior**
The Query should return a normal response 

Any suggested solution for the given error ? Since it sounds quite vague. When running the same on percona's IP the clickhouse query returns proper response. How is the authentication passed, are there any particular headers that need to be passed.

**Comment by den-crane** [comment]
21.3.14.1 obsolete, out of support. Minimal supported version is 22.3.

`Clickhouse Client` what do you mean by Clickhouse Client? Graphana plugin ? or clickhouse-client ?

**Comment by alexey-milovidov** [comment]
This question is most likely addressed to PMM (Percona Monitoring) and not related to ClickHouse.
Please create an issue for them.
