### ISSUE TITLE
User defined function does not raise an exception when not all parameters are input variables are listed

### ISSUE THREAD

**Issue by jzombi** [ClickHouse/ClickHouse#42230]
**Describe the issue**
The [documentation](https://clickhouse.com/docs/en/sql-reference/statements/create/function/) for `CREATE FUNCTION` states the following (emphasis is mine):

> There are a few restrictions:
> 
> -   The name of a function must be unique among user defined and system functions.
> -   Recursive functions are not allowed.
> -   **All variables used by a function must be specified in its parameter list.**
> 
> **If any restriction is violated then an exception is raised.**

But the following does not raise an exception:

    CREATE FUNCTION a AS () -> number*2;
    SELECT a() FROM numbers(3);

https://fiddle.clickhouse.com/b2691089-bc4b-404b-bbec-1f3b756b36f8

(Not attempting to fix the documentation, since I'm unsure whether it is a bug in the documentation, or in the behaviour.)

**Comment by jzombi** [comment]
(Maybe it is just a misunderstanding from my part, and in this case `number` is not considered as a variable?)

**Comment by den-crane** [comment]
It's by design. 
Currently FUNCTIONs are implemented as kinda substitutions, so `a()` in your select query is replaced with `number*2` and it works as `SELECT number*2 FROM numbers(3);`
