### ISSUE TITLE
The query optimizer did not choose all primary key as indexes 

### ISSUE THREAD

**Issue by jadetang** [ClickHouse/ClickHouse#42238]
Hello, I have a question regarding how the ClickHouse choose the primary key as indexes. 
So we have a table defined like this 
```
create table our_table {
   id uuid
   a
   b
   c
   d
   e
   f
   g
   primary key a, b, c, d
   order by a, b, c, d, e, f, g
}
```
and our queries follows this patterns 
```
select * from our_table where a = ? and d <= ?
and (b, c, id) in
(select b, c, aggregationFunction(id) as id from our_table group by b, c )
```

For the outer query, the execution plan sometimes chooses `a and c` as part of the primary key indexes, sometimes chooses `a and b`
My expectation is the execution plan will choose all primary key `a, b, c, d ` for the outer join.
I want to understand, what is the criteria when the query optimizer decides the primary key, so I can design my table more efficiently.

**Comment by alexey-milovidov** [comment]
ClickHouse does not choose which columns from the primary key to use. It always uses the primary key as a whole.
The primary key is a single index by the tuple of all the columns, not by each column separately.

Here is a more detailed explanation: https://clickhouse.com/docs/en/guides/improving-query-performance/sparse-primary-indexes
