### ISSUE TITLE
order by part of primary index in reverse order is unnormal slow

### ISSUE THREAD

**Issue by zdyj3170101136** [ClickHouse/ClickHouse#42240]
#### version
```
ClickHouse server version 21.8.2 
```
#### detail
i had a table:
```
CREATE TABLE default.jaeger_index_local
(
    `timestamp` DateTime('UTC') CODEC(Delta(4), ZSTD(1)),
    `service` LowCardinality(String) CODEC(ZSTD(1)),
    `operation` LowCardinality(String) CODEC(ZSTD(1)),
)
ENGINE = MergeTree
PARTITION BY toDate(timestamp)
ORDER BY (timestamp, service, operation)
```

and seems that query with different order with part of primary key is very slow:
- order by part of primary key in reverse order
```
SELECT DISTINCT traceID
FROM jaeger_index
WHERE (service = 'jaeger-clickhouse') AND (timestamp >= '2022-10-11 01:24:36') AND (timestamp <= '2022-10-11 07:34:36')
ORDER BY timestamp DESC
LIMIT 2

2 rows in set. Elapsed: 21.627 sec. Processed 207.23 million rows, 1.84 GB
```

- order by part of primary key
```
SELECT DISTINCT traceID
FROM jaeger_index
WHERE (service = 'jaeger-clickhouse') AND (timestamp >= '2022-10-11 01:24:36') AND (timestamp <= '2022-10-11 07:34:36')
ORDER BY timestamp 
LIMIT 2
2 rows in set. Elapsed: 1.039 sec. Processed 213.51 million rows, 223.19 MB 
```

it is really stranger.

#### helpful information
jaeger-clickhouse is a service that have much lower data:
```
select count() 
FROM jaeger_index
WHERE (service = 'jaeger-clickhouse') AND (timestamp >= '2022-10-11 01:24:36') AND (timestamp <= '2022-10-11 07:34:36')
```

result:
```
┌─count()─┐
│     515 │
└─────────┘
```
#### other test
- order by full primary key in reverse order 
```
SELECT DISTINCT traceID
FROM jaeger_index
WHERE (service = 'jaeger-clickhouse') AND (timestamp >= '2022-10-11 01:24:36') AND (timestamp <= '2022-10-11 07:34:36')
ORDER BY (timestamp, service, operation)  DESC
LIMIT 2 

2 rows in set. Elapsed: 1.283 sec. Processed 308.45 million rows, 371.81 MB
```

- order by full primary key
```
SELECT DISTINCT traceID
FROM jaeger_index
WHERE (service = 'jaeger-clickhouse') AND (timestamp >= '2022-10-11 01:24:36') AND (timestamp <= '2022-10-11 07:34:36')
ORDER BY (timestamp, service, operation) 
LIMIT 2

2 rows in set. Elapsed: 0.978 sec. Processed 308.45 million rows, 373.17 MB 
```

**Comment by zdyj3170101136** [comment]
seems the reason is that some parts is in cold disk.

**Comment by zdyj3170101136** [comment]
> set optimize_read_in_order=false

after check clickhouse version:
```
 22.9.2 
```

seems the problem is solved。

in my situation, there is three solution to solve this problem:
- upgrade clickhouse server to 22.9 (which is impossible to me)
- close optimize_read_in_order(seems weired)
- recreate table, order by (-toUnixtimestamp(timestamp), service, operation) and query with order by -toUnixtimestamp(timestamp)

do you have any other great solution?

**Comment by zdyj3170101136** [comment]
> 21.8 已过时。检查 22.9。


after check clickhouse version:
```
 22.9.2 
```

seems the problem is solved。

in my situation, there is three solution to solve this problem:
- upgrade clickhouse server to 22.9 (which is impossible to me)
- close optimize_read_in_order(seems weired)
- recreate table, order by (-toUnixtimestamp(timestamp), service, operation) and query with order by -toUnixtimestamp(timestamp)

do you have any other great solution?

**Comment by den-crane** [comment]
make upgrade of clickhouse is possible.

**Comment by zdyj3170101136** [comment]
> 使 clickhouse 的升级成为可能。

last day, the clickhouse server which i itest is not use the same raw data, so my opinion that the latest clickhouse had solve this problem is wrong.

there is a same issue: https://github.com/ClickHouse/ClickHouse/issues/40583
and i use the test from there, the latest clickhouse do not solve this problem:
```
SET optimize_read_in_order = 0;
```
![截屏2022-10-12 下午3 07 52](https://user-images.githubusercontent.com/52686065/195273676-e8a8acad-7bd3-4ec6-a8c3-0612de0f5c63.png)

```
SET optimize_read_in_order = 1;
```
![截屏2022-10-12 下午3 08 12](https://user-images.githubusercontent.com/52686065/195273748-6614ab4f-92de-4c7d-b90e-d07cc2c41bde.png)

and  the final solution from clickhouse maintainer is https://github.com/ClickHouse/ClickHouse/issues/40675:

```
this is a feature not a bug
```

**Comment by zdyj3170101136** [comment]
> > 使clickhouse的升级成为可能。
> 
> 昨天，我测试的clickhouse服务器没有使用相同的原始数据，所以我认为最新的clickhouse解决了这个问题是错误的。
> 
> 有同样的问题：#40583 我从那里使用测试，最新的 clickhouse 不能解决这个问题：
> 
> ```
> SET optimize_read_in_order = 0;
> ```
> 
> ![截屏2022-10-12 下午3 07 52](https://user-images.githubusercontent.com/52686065/195273676-e8a8acad-7bd3-4ec6-a8c3-0612de0f5c63.png)
> 
> ```
> SET optimize_read_in_order = 1;
> ```
> 
> ![截屏2022-10-12 下午3 08 12](https://user-images.githubusercontent.com/52686065/195273748-6614ab4f-92de-4c7d-b90e-d07cc2c41bde.png)
> 
> clickhouse 维护者的最终解决方案是#40675：
> 
> ```
> this is a feature not a bug
> ```

ignore it, not same problem
