### ISSUE TITLE
Dashboard: title not displayed

### ISSUE THREAD

**Issue by cangyin** [ClickHouse/ClickHouse#42241]
For js string method `replaceAll` used here:
https://github.com/ClickHouse/ClickHouse/blob/7c8e540dea0d1c357d34fb2394ca9a988c3ef8a1/programs/server/dashboard.html#L823
is not supported in chrome version under 85, see https://stackoverflow.com/questions/62825358/javascript-replaceall-is-not-a-function-type-error

the charts in dashboard  will not display titles.

Simply replacing `replaceAll` with `replace` works fine for me, with chrome 83.

**Comment by den-crane** [comment]
But the current chrome version is 106, why do you use  chrome 83 ?

**Comment by alexey-milovidov** [comment]
If this version of Chrome is rare and did not stick in many user devices, and the only issue is the lack of title, it looks like a reasonable degradation for an old browser.

**Comment by alexey-milovidov** [comment]
The dashboard is made with the "do less, cut corners" principle...
If it's easy to fix, let's do it; if not, let's not bother.
