### ISSUE TITLE
any way can  optimization way  for in ?

### ISSUE THREAD

**Issue by vegastar002** [ClickHouse/ClickHouse#42246]
Table ta has field id (unique), table tb also has field id (non-unique), ta has 1 million records, tb has 5 million records, for sql:
```sql
select * from ta where id in ( select * from tb )
```
Is there a good optimization way?

**Comment by den-crane** [comment]
`select * from ta where id in ( select id from tb where id in (select id from ta))`

**Comment by vegastar002** [comment]
> `select * from ta where id in ( select id from tb where id in (select id from ta))`

can bitmap do it ?

**Comment by alexey-milovidov** [comment]
I don't think bitmaps should be used here.
