### ISSUE TITLE
`MaterializedPostgreSQL` replication isn’t working as expected

### ISSUE THREAD

**Issue by dziubakseniia** [ClickHouse/ClickHouse#42247]
Since we need to save a PostgreSQL (ver. 13.7) replica to ClickHouse (ver. 22.9.1.1761), we decided to use `MaterializedPostgreSQL` for it.

Unfortunately, we faced an issue there. It’s, definetely, creates new database and tables with data copied from PostgreSQL, but further `UPDATE` and `DELETE` commands on the PostgreSQL DB have no impact to the ClickHouse.

**Comment by kssenii** [comment]
Hi, please check logs for error messages in clickhouse log. It should work unless something went wrong.

**Comment by kssenii** [comment]
Please reopen if the logs can be provided, cannot investigate without any information.
