### ISSUE TITLE
Chained materialized views broken after database conversion to atomic

### ISSUE THREAD

**Issue by nvartolomei** [ClickHouse/ClickHouse#42250]
#39933 add a feature to convert Ordinary engine databases to Atomic. If database contains chained materialized views, they don't work as expected after conversion due to incomplete conversion code.

Step 1: create ordinary database

```sql
drop database if exists test NO DELAY;
create database test engine=Ordinary;
use test;

---

create table t(v UInt8) engine=MergeTree() order by tuple();
create materialized view t1 engine=MergeTree() order by tuple() as select * from t;
create materialized view t2 engine=MergeTree() order by tuple() as select * from `.inner.t1`;

---

insert into t values (1);

select '-- from t1 --';
select * from t1;

select '-- from t2 --';
select * from t2;
```

Step 2: `touch flags/convert_ordinary_to_atomic`

Step 3:

```sql
insert into t values (2);

select '-- from t1 --';
select * from t1;

select '-- from t2 --';
select * from t2;
```

Expected output:

```
-- from t1 --
2
1
-- from t2 --
2
1
```

Actual output:

```
-- from t1 --
2
1
-- from t2 --
1
```

The second write (after conversion) didn't reach the t2 table.

That is because the `FROM` statement wasn't rewritten:

```sql
show create table t2
```

```
 CREATE MATERIALIZED VIEW test.t2
(
    `v` UInt8
)
ENGINE = MergeTree
ORDER BY tuple()
SETTINGS index_granularity = 8192 AS
SELECT *
FROM test.`.inner.t1`
```

```sql
show tables
```

```
.inner_id.8b806d74-a4ed-4a91-9759-f02f6d5f0846
.inner_id.bf8ae668-5aae-4408-ab0c-9fee7ea33162
t
t1
t2
```

cc @tavplubix

**Comment by tavplubix** [comment]
It's not clear how to rewrite FROM statement, because we cannot know for sure if `.inner.t1` is a part of some MV or an independent table (maybe someone just created a table with weird name for some reason). Also it's usually bad idea to rely on some "internal" names. 

However, I expected that
```
create table t(v UInt8) engine=MergeTree() order by tuple();
create materialized view t1 engine=MergeTree() order by tuple() as select * from t;
create materialized view t2 engine=MergeTree() order by tuple() as select * from t1;
```
works fine. But actually it does not, no data is inserted into t2 when inserting into t. So now I understand why someone may create an MV like `from ".inner.t1"`. Maybe we should support MV name in FROM.

**Comment by tavplubix** [comment]
What we can do:
 - Support MV name in FROM, so it will not be required to specify some internal name there
 - Check before conversion that names in FROM do not start with `.inner.`, throw an exception that asks user to replace it with MV name or rename table table to some sane name or create another flag to ignore this check

**Comment by victor-perov** [comment]
Hello, @tavplubix! I'm just wondering if you have some progress with this issue. It feels like supporting MV name in FROM directive is the way to go though might not be backward compatible.

**Comment by tavplubix** [comment]
Hello, no progress for now. 

Some help will be highly appreciated.

**Comment by alexey-milovidov** [comment]
We deprecated Ordinary databases a long time ago, better to close than do anything further here.
