### ISSUE TITLE
create table if not exists demo_test on cluster r_demo timeout

### ISSUE THREAD

**Issue by mrhanhan** [ClickHouse/ClickHouse#42258]
![image](https://user-images.githubusercontent.com/29645442/195310158-caa6fdc1-0d13-4eef-b7a9-0ff442ddd17f.png)
read timed out
![image](https://user-images.githubusercontent.com/29645442/195310305-df121949-985f-475c-8fde-0feba69a8873.png)
![image](https://user-images.githubusercontent.com/29645442/195310351-395bb669-53d7-4c99-9234-950179f0219c.png)

![image](https://user-images.githubusercontent.com/29645442/195310445-56aa76a9-2890-414d-8296-6586d3f3536f.png)

**Comment by mrhanhan** [comment]
💕 thank you for your reply @mo-avatar 

## Environment
deployed two clickhouse-servers at 192.168.0.148 using docker
node1 : 192.168.0.148:19000
node2 : 192.168.0.148:29000
![image](https://user-images.githubusercontent.com/29645442/195482054-77efcba8-fa12-459e-b4af-e18fb3897bd2.png)
![image](https://user-images.githubusercontent.com/29645442/195482178-d6af36f2-1fa4-4b41-a840-2127863a1584.png)

## Config
### node1 
![image](https://user-images.githubusercontent.com/29645442/195482585-58356464-d337-44cf-af5c-8329aa5c479e.png)
### node2
![image](https://user-images.githubusercontent.com/29645442/195482673-a0086649-55d8-4e31-98b9-3747064ffbfd.png)

I think I have this configuration because it should be fine

**Comment by mrhanhan** [comment]
@mo-avatar 你好😁

**Comment by mo-avatar** [comment]
See the macro part of https://www.modb.pro/db/81185,  and remember to set internal_replication=true. Search engine is good enough to solve your problem, It may not be a proper way to raise an issue.
