### ISSUE TITLE
CANNOT_PARSE_INPUT_ASSERTION_FAILED when using External Data

### ISSUE THREAD

**Issue by debugger-zhang** [ClickHouse/ClickHouse#42259]
**Describe the unexpected behaviour**
When running some queries the external input fails to parse.

**How to reproduce**
* Which ClickHouse server version to use: 22.10.1.1168
* Which interface to use, if matters: clickhouse client
* Non-default settings, if any: no
* `CREATE TABLE` statements for all tables involved: no

Reproduce:
* Follow https://clickhouse.com/docs/en/quick-start/ to install ClickHouse and creating an example database and table (creating example database and table is optional).
* Create test.txt using `echo YWJjCmRlZgpnaGkK | base64 -d > test.txt`
* Run `clickhouse client --external --file=test.txt --types=String`
* Execute `select * from _data`. This query will execute normally
* Execute the same query again. The following error is displayed.
* Also, other queries can not be run either even if they are nothing to do with _data

**Expected behavior**
The query should execute normally

**Error message and/or stacktrace**

```
SELECT *
FROM _data

Query id: 4567c842-bc4d-493f-82c2-1c8fcd0bfa0e

Exception on client:
Code: 27. DB::ParsingException: Cannot parse input: expected '\t' before: '\ndef\nghi\n': 
Row 1:
Column 0,   name: _1, type: String, parsed text: "abc"
ERROR: Line feed found where tab is expected. It's like your file has less columns than expected.
And if your file has the right number of columns, maybe it has an unescaped backslash in value before tab, which causes the tab to be escaped.

: While executing ParallelParsingBlockInputFormat: (in file/uri test.txt): (at row 1)
. (CANNOT_PARSE_INPUT_ASSERTION_FAILED)
```

**Comment by fm4v** [comment]
Fixed in 24.5
https://github.com/ClickHouse/ClickHouse/pull/62964
