### ISSUE TITLE
is set engin only one field?

### ISSUE THREAD

**Issue by vegastar002** [ClickHouse/ClickHouse#42257]
```sql
CREATE TABLE set_1
(
    name String,
    city  String
)
ENGINE = Set;
```
set engin  can have 2 field ?
how  to use ?

**Comment by mo-avatar** [comment]
May be you could use tuple datatype to combine the two field. To my knowledge it may solve your problem

**Comment by mo-avatar** [comment]
Foget last repose, the set works well with more than one field, in the newest version of clickhouse

**Comment by vegastar002** [comment]
> Forget previouse reponse, the set works well with more than one field, in the newest version of clickhouse

how to use the filed, maybe like this ?
```sql
select * from tb1  where name  in set_1.name ;
```

**Comment by mo-avatar** [comment]
It seems that I have mis-understand what you want.  you can have two field in an SET engine, but when you want to use it,  it seems you must offer an  tuple (the same type and length with the set engine), the way you use set engine is just not implemented.

**Comment by alexey-milovidov** [comment]
@vegastar002 if you created a set with two fields, you can only used it with two fields:

```
SELECT ... WHERE (a, b) IN set
```

You cannot use it with a subset of fields. For example, if `set` has two fields, the following query won't work:

```
SELECT ... WHERE a IN set
```

And you need to create another set table, containing only the `a` field.

PS. Why it works this way? The fields can be hashed and the set may not contain the info about every original value.
