### ISSUE TITLE
Why function geoDistance use unconventional parameters order?

### ISSUE THREAD

**Issue by dimkas78** [ClickHouse/ClickHouse#42255]
Documentation of function geoDistance - https://clickhouse.com/docs/en/sql-reference/functions/geo/coordinates/#geodistance
do not have any input parameter's description, but by tests we can define that function geoDistance have exactly same parameters set as function greatCircleDistance:
```
Input parameters
lon1Deg — Longitude of the first point in degrees. Range: [-180°, 180°].
lat1Deg — Latitude of the first point in degrees. Range: [-90°, 90°].
lon2Deg — Longitude of the second point in degrees. Range: [-180°, 180°].
lat2Deg — Latitude of the second point in degrees. Range: [-90°, 90°].
```
But this is not conventional parameters order - all geo-informatical system use pairs (latitude, longitude), not (longitude, latitude).
For function greatCircleDistance parameters order does not matter, due to the sphere simmetricity, but on WGS-84 ellipsoid paramers order do difference.
Even example of function greatCircleDistance use coodinates (55.755831, 37.617673), which seems like Russian "zero kilometer point", but after parameters replacing this point will be in very different place.

**Comment by alexey-milovidov** [comment]
It is not universally agreed among various systems, what the parameter order should be.

http://web.archive.org/web/20220910040559/https://macwright.com/lonlat/

The order of parameters in ClickHouse originated in this pull request about `greatCircleDistance` function:
https://github.com/ClickHouse/ClickHouse/pull/72/files#diff-3d0bfad182e0d56ec7554e4753c046062cbfc3e53d805832d30c0b108ff0a8caR96

When we added `geoDistance`, I was also confused about why we use this order and what order is correct but decided to keep it as is.

Finally, we have added support for WKT, and it is using (lon, lat) as well.

It is easy to memorize the order: when you are looking at some rectangular map projection, (lon, lat) will be (x, y).
