### ISSUE TITLE
Size of parts in system.detached_parts

### ISSUE THREAD

**Issue by Alex-Burmak** [ClickHouse/ClickHouse#42264]
Right now size of data parts is available only for non-detached parts in `system.parts`, but `system.detached_parts` lacks this information. It will be useful for analyzing disk space usage.

**Comment by dentiscalprum** [comment]
I'd like to pick up this issue. Could you please assign this task to me?
Thanks !

**Comment by alexey-milovidov** [comment]
@Alex-Burmak, very questionable.
My point - the server should not care at all about the detached parts.
Or at least - not try to read and analyze them.
