### ISSUE TITLE
How to migrate from deprecated_syntax_for_merge_tree to new one?

### ISSUE THREAD

**Issue by nvartolomei** [ClickHouse/ClickHouse#42267]
Hi. Since #38335 I'm wondering how to migrate these old tables to the new syntax? I thought I could just update the metadata, but things are failing with `MergeTree data format version on disk doesn't support custom partitioning.`...

Help appreciated.

**Comment by den-crane** [comment]
There is no such feature. Related https://github.com/ClickHouse/ClickHouse/issues/30821
