### ISSUE TITLE
how to copy clickhouse-keeper cluster

### ISSUE THREAD

**Issue by 825644691** [ClickHouse/ClickHouse#42272]
I want to copy the data of the clickhouse-keeper cluster to another clickhouse-keeper cluster

origin keeper cluster
ip1 master
ip2
ip3

target keeper cluster
ip4
ip5
ip6

I scp ip1 coordination/ （data directory） to ip4, ip5 and ip6 and start the clickhouse-keeper, the result is bad
ALL OF THE THREE NEW NODES HAS THIS ERR

[PRE-VOTE RESP] peer 1 (X), term 0, resp term 0, my role follower, dead 1, live 2, num voting members 3, quorum 2
[PRE-VOTE] rejected by quorum, count 20

**Comment by 825644691** [comment]
/zookeeper^@^A]^P/quota]^K/clickhouse^@^N<94>i8?{^A^@^C^@^@^@^X^\^Q<8D>^A]^R/tables<B6><B6>&_;^R^R^@^@^@x^Lx    ^R^U/11,^A{3^Y^@^@^@<82><92>w<BA>
and i find  those (origin cluster info ) in the head of the snapshot file

**Comment by alexey-milovidov** [comment]
ClickHouse Keeper is saving the info about the host addresses to the log,
that's why it's not possible to simply move it to the nodes with different addresses.

Let's ask @antonio2368 how to do it properly.

**Comment by antonio2368** [comment]
@825644691 this part is important
> ClickHouse Keeper is saving the info about the host addresses to the log

Cluster information is modified and stored using Raft so it's not simple to reconfigure the entire cluster.
The way to do it would be by following these steps:
https://clickhouse.com/docs/en/operations/clickhouse-keeper/#recovering-after-losing-quorum

If you have any problems with those steps please tell me.

**Comment by 825644691** [comment]
> @825644691这部分很重要
> 
> > ClickHouse Keeper 正在将有关主机地址的信息保存到日志中
> 
> 集群信息是使用 Raft 修改和存储的，因此重新配置整个集群并不简单。 执行此操作的方法是按照以下步骤操作： [https](https://clickhouse.com/docs/en/operations/clickhouse-keeper/#recovering-after-losing-quorum) ://clickhouse.com/docs/en/operations/clickhouse-keeper/#recovering-after-losing-quorum 不同之处在于应该停止所有新节点一开始，你用`--force-recovery`标志开始第一个。 之后，您将一个接一个地启动其他节点。
> 
> 如果您对这些步骤有任何问题，请告诉我。

hello， keeper version is 22365
/apps//svr/clickhouse22365/usr/bin/clickhouse-keeper -C /apps//conf/clickhouse-server/keeper.xml -L /apps/logs/clickhouse-server/keeper.log -E /apps//logs/clickhouse-server/keeper.err.log --pidfile=/apps/tmp/keeper.pid --force-recovery
Unknown option specified: force-recovery
