### ISSUE TITLE
How to scan groupArray(tuple(str_type,array_type))

### ISSUE THREAD

**Issue by fuzzywang** [ClickHouse/ClickHouse#42271]
I'm trying to scan groupArray(tuple(str_type,array_type)), sql is `select  groupArray(tuple(str_type,array_type)) from xxx`. Which works well by http api, the result like: `[('a string',['time1', 'time2'])]`. But by Golang, the only correct way for me is scan to `[][]interface {}`, which only return the first column. 
```
var data [][]interface{}
rows, _ := tx.Query("select  groupArray(tuple(str_type,array_type)) from xxx")
rows.Scan(&data) // the result is  `[('a string')]`, missing array_type
```

What's the correct way to scan it? Thx!

**Comment by den-crane** [comment]
You should ask it in go lang repo https://github.com/ClickHouse/clickhouse-go/issues 
we support only clickhouse-server here.

BTW, You can query it as two separate Array columns 

```
select  (groupArray(tuple(str_type,array_type)) as x).1 , x.2 from xxx

or 

select  groupArray(str_type), groupArray(array_type) from xxx
```

Also probably it should be `var data [][[]]interface{}` not `[][]`
