### ISSUE TITLE
Hive engine: Support for codec 'zstd' not built

### ISSUE THREAD

**Issue by ramseyxu** [ClickHouse/ClickHouse#42278]
(you don't have to strictly follow this form)

**Describe the unexpected behaviour**
Can not query Hive table

Code: 33. DB::Exception: Received from localhost:9000. DB::ParsingException. DB::ParsingException: Error while reading Parquet data: NotImplemented: Support for codec 'zstd' not built: While executing ParquetBlockInputFormat: While executing Hive. (CANNOT_READ_ALL_DATA)

**How to reproduce**
* Which ClickHouse server version to use
22.5.1.1 
commit ID c3f177f0ac0726424d3ecee1d444ae9045438e5b
* Which interface to use, if matters
clickhouse-client
* `CREATE TABLE` statements for all tables involved
```
CREATE TABLE default.hive_test
(
    `utc_date` Date,
    `utc_hour` Int32,
    `region` String,
    `ab_test` String
)
ENGINE = Hive('xxx', 'db', 'table')
PARTITION BY (utc_date, utc_hour, region)
```

* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result
select count(*) from hive_test

**Expected behavior**
return value

**Error message and/or stacktrace**
Code: 33. DB::Exception: Received from localhost:9000. DB::ParsingException. DB::ParsingException: Error while reading Parquet data: NotImplemented: Support for codec 'zstd' not built: While executing ParquetBlockInputFormat: While executing Hive. (CANNOT_READ_ALL_DATA)

**Additional context**

**Comment by alexey-milovidov** [comment]
Need help from @lgbo-ustc (the developer of Hive integration).

**Comment by ramseyxu** [comment]
> Need help from @lgbo-ustc (the developer of Hive integration).

Thank you for the reply
The ZSTD lib is not just used by Hive. It's a compress algorithm supported by ClickHouse.
And in 21.8 ZSTD is supported defaultly
