### ISSUE TITLE
Not AD authorization because many groups in LDAP memberOf container

### ISSUE THREAD

**Issue by lavasser** [ClickHouse/ClickHouse#42276]
**Problem:** 
Some AD users can't log in, they get the error:
`Authentification failed: password is incorrect or there is no user with such name`

Clickhouse version 22.3.2.1

**There is an error in Clickhouse logs:**
`<Error> Access(user directories): from: 10.11.12.13, user: AD_USERNAME: Authentification failed: Code: 532. DB::Exception: Size limit exceeded. (LDAP_ERROR)`

This error occurs for AD users who have many groups in the **memberOf** LDAP container.

**I checked the number of groups for 4 accounts:**

AD_USERNAME_1 - 107 groups - ERROR Authentification failed
AD_USERNAME_2 - 120 groups - ERROR Authentification failed
AD_USERNAME_3 - 54   groups - OK
AD_USERNAME_4 - 38   groups - OK

**I checked the search groups through the Ldapsearch program:**

Ldapsearch gave all 107 groups for the account without errors:
`ldapsearch -H "ldaps://hostname:636" -D 'CN=AD_USERNAME_1,OU=Users,DC=company,DC=corp.DC=net' -b 'DC=company,DC=corp.DC=net' '(&(objectClass=group)(member=CN=AD_USERNAME_1,OU=Groups,DC=company,DC=corp.DC=net))'`

**Probable cause of the error:** 
Clickhouse receives a list of groups which mapping from AD and cannot process a large string/array.

**Comment by alexey-milovidov** [comment]
Need help from @traceon who is the developer of LDAP integration.

**Comment by traceon** [comment]
It is with a 99% chance could be solved by just increasing this value, which is currently hardcoded, but, if it helps, could be made configurable through the server config:

https://github.com/ClickHouse/ClickHouse/blob/cc24fcd6d5dfb67f5f66f5483e986bd1010ad9cf/src/Access/LDAPClient.h#L122

**Comment by alexey-milovidov** [comment]
@traceon FYI `boost::hash_combine` is the wrong way to construct a hash value from a tuple.

**Comment by alexey-milovidov** [comment]
@traceon the file `LDAPClient.h` lacks comments.

**Comment by alexey-milovidov** [comment]
@traceon 

```
MAYBE_NORETURN void diag(int rc, String text = "");
```

Bad function name (we never use abbrs), it can be confused with:
- diagnostics;
- diagonal;
- diagram;

**Comment by alexey-milovidov** [comment]
@traceon 

```
        // If the critical server params have changed while we were checking the password, we discard the current result.
        if (params_hash != new_params_hash)
            return false;
```

There is an error: either this code is unneeded or we need to use a cryptographic hash.

**Comment by traceon** [comment]
Adding @alex-zaitsev to budget time for the requested changes.

**Comment by traceon** [comment]
> There is an error: either this code is unneeded or we need to use a cryptographic hash.

Yes, the right way to go is using a cryptographic hash.

**Comment by vzakaznikov** [comment]
Confirmed that this issue hits the `100` groups hard coded limit. If the number of LDAP groups is `<=100` then the authentication works as expected.

**Comment by lavasser** [comment]
Is it possible to merge fix into 22.3.2 version?

**Comment by lavasser** [comment]
Hello! When can expect fix?

**Comment by victorvde** [comment]
As a workaround it is possible to change the search_filter to return less rows. For example if you only care about groups with prefix "clickhouse_" then you can change from

```
<search_filter>(&amp;(objectClass=group)(member={user_dn}))</search_filter>
```

to

```
<search_filter>(&amp;(objectClass=group)(member={user_dn})(cn=clickhouse_*))</search_filter>
```
