### ISSUE TITLE
Selecting over a with clause that contains union all

### ISSUE THREAD

**Issue by ozhangulen** [ClickHouse/ClickHouse#42283]
Assume that you have a student table in clickhouse.

The query is here:

```
select * from ( 
with a as (select id from student)
select id from a
union all
select id from a
)
```
I am getting table Default.a doesnt exist (unknown table).

If I remove the select part which is after the union all, then query is running properly.

I allready tried enable_global_with_statement=1 setting and it isnt working.

Same query is running on postgres or mysql as expected.

(I already know that outer select is unnecessary. But my actual query needs to contain outer select)

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/41426

**Comment by ozhangulen** [comment]
My case is not duplication of #41426. Because i am getting this error on mergetree engine or postgresql engined tables.

**Comment by den-crane** [comment]
Be kind and provide a reproducible example, please.
