### ISSUE TITLE
Monitor rows written per second

### ISSUE THREAD

**Issue by dz902** [ClickHouse/ClickHouse#42281]
Hi,

I could not find on the docs a way to monitor rows written per second, however I'm able to find it on Datadog integration, and managed ClickHouse service provided by clouds. The ClickHouse dashboard on Grafana seems not to be accurate.

Is there an official way to do this and get an accurate number of rows written per second?

Thanks!

**Comment by den-crane** [comment]
There is a big confusion what is to count as rows written.

`select * from system.events  where event ilike '%InsertedRows%';` 
Includes rows inserted into Distributed/MergeTree/MatViews. Technically it's correct, so when you insert 1000 rows - InsertedRows can increase to n*1000.


So the question why do you need this number? And what is "number of rows written" from your perspective? What should be counted?

**Comment by dz902** [comment]
Thanks for the info. We need this because one of our servers sees slow insertions, but CPU and memory utilization are very low (<10% for CPU). Data are inserted by individual `INSERT` statements, into multiple tables, from Kafka cluster.

We have two ClickHouse clusters, one of them can do 350 rows per second, but the other can only do <100 rows. We are debugging this issue. Is there any configuration we can use to make better use of the resources are accelerate insertions?

Thanks!

**Comment by alexey-milovidov** [comment]
350 rows per second is too low.

Either you are inserting every single row in a separate INSERT query - then you need to use batching.
Or you meant 350 thousand rows per second, which is more realistic.

**Comment by alexey-milovidov** [comment]
ClickHouse dashboard shows the number of INSERTed rows per second on a host:

https://play.clickhouse.com/dashboard#eyJob3N0IjoiaHR0cHM6Ly9wbGF5LmNsaWNraG91c2UuY29tIiwidXNlciI6InBsYXkiLCJxdWVyaWVzIjpbeyJ0aXRsZSI6IlF1ZXJpZXMvc2Vjb25kIiwicXVlcnkiOiJTRUxFQ1QgdG9TdGFydE9mSW50ZXJ2YWwoZXZlbnRfdGltZSwgSU5URVJWQUwge3JvdW5kaW5nOlVJbnQzMn0gU0VDT05EKTo6SU5UIEFTIHQsIGF2ZyhQcm9maWxlRXZlbnRfUXVlcnkpXG5GUk9NIHN5c3RlbS5tZXRyaWNfbG9nXG5XSEVSRSBldmVudF9kYXRlID49IHRvRGF0ZShub3coKSAtIHtzZWNvbmRzOlVJbnQzMn0pIEFORCBldmVudF90aW1lID49IG5vdygpIC0ge3NlY29uZHM6VUludDMyfVxuR1JPVVAgQlkgdFxuT1JERVIgQlkgdCJ9LHsidGl0bGUiOiJDUFUgVXNhZ2UgKGNvcmVzKSIsInF1ZXJ5IjoiU0VMRUNUIHRvU3RhcnRPZkludGVydmFsKGV2ZW50X3RpbWUsIElOVEVSVkFMIHtyb3VuZGluZzpVSW50MzJ9IFNFQ09ORCk6OklOVCBBUyB0LCBhdmcoUHJvZmlsZUV2ZW50X09TQ1BVVmlydHVhbFRpbWVNaWNyb3NlY29uZHMpIC8gMTAwMDAwMFxuRlJPTSBzeXN0ZW0ubWV0cmljX2xvZ1xuV0hFUkUgZXZlbnRfZGF0ZSA+PSB0b0RhdGUobm93KCkgLSB7c2Vjb25kczpVSW50MzJ9KSBBTkQgZXZlbnRfdGltZSA+PSBub3coKSAtIHtzZWNvbmRzOlVJbnQzMn1cbkdST1VQIEJZIHRcbk9SREVSIEJZIHQifSx7InRpdGxlIjoiUXVlcmllcyBSdW5uaW5nIiwicXVlcnkiOiJTRUxFQ1QgdG9TdGFydE9mSW50ZXJ2YWwoZXZlbnRfdGltZSwgSU5URVJWQUwge3JvdW5kaW5nOlVJbnQzMn0gU0VDT05EKTo6SU5UIEFTIHQsIGF2ZyhDdXJyZW50TWV0cmljX1F1ZXJ5KVxuRlJPTSBzeXN0ZW0ubWV0cmljX2xvZ1xuV0hFUkUgZXZlbnRfZGF0ZSA+PSB0b0RhdGUobm93KCkgLSB7c2Vjb25kczpVSW50MzJ9KSBBTkQgZXZlbnRfdGltZSA+PSBub3coKSAtIHtzZWNvbmRzOlVJbnQzMn1cbkdST1VQIEJZIHRcbk9SREVSIEJZIHQifSx7InRpdGxlIjoiTWVyZ2VzIFJ1bm5pbmciLCJxdWVyeSI6IlNFTEVDVCB0b1N0YXJ0T2ZJbnRlcnZhbChldmVudF90aW1lLCBJTlRFUlZBTCB7cm91bmRpbmc6VUludDMyfSBTRUNPTkQpOjpJTlQgQVMgdCwgYXZnKEN1cnJlbnRNZXRyaWNfTWVyZ2UpXG5GUk9NIHN5c3RlbS5tZXRyaWNfbG9nXG5XSEVSRSBldmVudF9kYXRlID49IHRvRGF0ZShub3coKSAtIHtzZWNvbmRzOlVJbnQzMn0pIEFORCBldmVudF90aW1lID49IG5vdygpIC0ge3NlY29uZHM6VUludDMyfVxuR1JPVVAgQlkgdFxuT1JERVIgQlkgdCJ9LHsidGl0bGUiOiJTZWxlY3RlZCBCeXRlcy9zZWNvbmQiLCJxdWVyeSI6IlNFTEVDVCB0b1N0YXJ0T2ZJbnRlcnZhbChldmVudF90aW1lLCBJTlRFUlZBTCB7cm91bmRpbmc6VUludDMyfSBTRUNPTkQpOjpJTlQgQVMgdCwgYXZnKFByb2ZpbGVFdmVudF9TZWxlY3RlZEJ5dGVzKVxuRlJPTSBzeXN0ZW0ubWV0cmljX2xvZ1xuV0hFUkUgZXZlbnRfZGF0ZSA+PSB0b0RhdGUobm93KCkgLSB7c2Vjb25kczpVSW50MzJ9KSBBTkQgZXZlbnRfdGltZSA+PSBub3coKSAtIHtzZWNvbmRzOlVJbnQzMn1cbkdST1VQIEJZIHRcbk9SREVSIEJZIHQifSx7InRpdGxlIjoiSU8gV2FpdCIsInF1ZXJ5IjoiU0VMRUNUIHRvU3RhcnRPZkludGVydmFsKGV2ZW50X3RpbWUsIElOVEVSVkFMIHtyb3VuZGluZzpVSW50MzJ9IFNFQ09ORCk6OklOVCBBUyB0LCBhdmcoUHJvZmlsZUV2ZW50X09TSU9XYWl0TWljcm9zZWNvbmRzKSAvIDEwMDAwMDBcbkZST00gc3lzdGVtLm1ldHJpY19sb2dcbldIRVJFIGV2ZW50X2RhdGUgPj0gdG9EYXRlKG5vdygpIC0ge3NlY29uZHM6VUludDMyfSkgQU5EIGV2ZW50X3RpbWUgPj0gbm93KCkgLSB7c2Vjb25kczpVSW50MzJ9XG5HUk9VUCBCWSB0XG5PUkRFUiBCWSB0In0seyJ0aXRsZSI6IkNQVSBXYWl0IiwicXVlcnkiOiJTRUxFQ1QgdG9TdGFydE9mSW50ZXJ2YWwoZXZlbnRfdGltZSwgSU5URVJWQUwge3JvdW5kaW5nOlVJbnQzMn0gU0VDT05EKTo6SU5UIEFTIHQsIGF2ZyhQcm9maWxlRXZlbnRfT1NDUFVXYWl0TWljcm9zZWNvbmRzKSAvIDEwMDAwMDBcbkZST00gc3lzdGVtLm1ldHJpY19sb2dcbldIRVJFIGV2ZW50X2RhdGUgPj0gdG9EYXRlKG5vdygpIC0ge3NlY29uZHM6VUludDMyfSkgQU5EIGV2ZW50X3RpbWUgPj0gbm93KCkgLSB7c2Vjb25kczpVSW50MzJ9XG5HUk9VUCBCWSB0XG5PUkRFUiBCWSB0In0seyJ0aXRsZSI6Ik9TIENQVSBVc2FnZSAoVXNlcnNwYWNlKSIsInF1ZXJ5IjoiU0VMRUNUIHRvU3RhcnRPZkludGVydmFsKGV2ZW50X3RpbWUsIElOVEVSVkFMIHtyb3VuZGluZzpVSW50MzJ9IFNFQ09ORCk6OklOVCBBUyB0LCBhdmcodmFsdWUpXG5GUk9NIHN5c3RlbS5hc3luY2hyb25vdXNfbWV0cmljX2xvZ1xuV0hFUkUgZXZlbnRfZGF0ZSA+PSB0b0RhdGUobm93KCkgLSB7c2Vjb25kczpVSW50MzJ9KSBBTkQgZXZlbnRfdGltZSA+PSBub3coKSAtIHtzZWNvbmRzOlVJbnQzMn1cbkFORCBtZXRyaWMgPSAnT1NVc2VyVGltZU5vcm1hbGl6ZWQnXG5HUk9VUCBCWSB0XG5PUkRFUiBCWSB0In0seyJ0aXRsZSI6Ik9TIENQVSBVc2FnZSAoS2VybmVsKSIsInF1ZXJ5IjoiU0VMRUNUIHRvU3RhcnRPZkludGVydmFsKGV2ZW50X3RpbWUsIElOVEVSVkFMIHtyb3VuZGluZzpVSW50MzJ9IFNFQ09ORCk6OklOVCBBUyB0LCBhdmcodmFsdWUpXG5GUk9NIHN5c3RlbS5hc3luY2hyb25vdXNfbWV0cmljX2xvZ1xuV0hFUkUgZXZlbnRfZGF0ZSA+PSB0b0RhdGUobm93KCkgLSB7c2Vjb25kczpVSW50MzJ9KSBBTkQgZXZlbnRfdGltZSA+PSBub3coKSAtIHtzZWNvbmRzOlVJbnQzMn1cbkFORCBtZXRyaWMgPSAnT1NTeXN0ZW1UaW1lTm9ybWFsaXplZCdcbkdST1VQIEJZIHRcbk9SREVSIEJZIHQifSx7InRpdGxlIjoiUmVhZCBGcm9tIERpc2siLCJxdWVyeSI6IlNFTEVDVCB0b1N0YXJ0T2ZJbnRlcnZhbChldmVudF90aW1lLCBJTlRFUlZBTCB7cm91bmRpbmc6VUludDMyfSBTRUNPTkQpOjpJTlQgQVMgdCwgYXZnKFByb2ZpbGVFdmVudF9PU1JlYWRCeXRlcylcbkZST00gc3lzdGVtLm1ldHJpY19sb2dcbldIRVJFIGV2ZW50X2RhdGUgPj0gdG9EYXRlKG5vdygpIC0ge3NlY29uZHM6VUludDMyfSkgQU5EIGV2ZW50X3RpbWUgPj0gbm93KCkgLSB7c2Vjb25kczpVSW50MzJ9XG5HUk9VUCBCWSB0XG5PUkRFUiBCWSB0In0seyJ0aXRsZSI6IlJlYWQgRnJvbSBGaWxlc3lzdGVtIiwicXVlcnkiOiJTRUxFQ1QgdG9TdGFydE9mSW50ZXJ2YWwoZXZlbnRfdGltZSwgSU5URVJWQUwge3JvdW5kaW5nOlVJbnQzMn0gU0VDT05EKTo6SU5UIEFTIHQsIGF2ZyhQcm9maWxlRXZlbnRfT1NSZWFkQ2hhcnMpXG5GUk9NIHN5c3RlbS5tZXRyaWNfbG9nXG5XSEVSRSBldmVudF9kYXRlID49IHRvRGF0ZShub3coKSAtIHtzZWNvbmRzOlVJbnQzMn0pIEFORCBldmVudF90aW1lID49IG5vdygpIC0ge3NlY29uZHM6VUludDMyfVxuR1JPVVAgQlkgdFxuT1JERVIgQlkgdCJ9LHsidGl0bGUiOiJNZW1vcnkgKHRyYWNrZWQpIiwicXVlcnkiOiJTRUxFQ1QgdG9TdGFydE9mSW50ZXJ2YWwoZXZlbnRfdGltZSwgSU5URVJWQUwge3JvdW5kaW5nOlVJbnQzMn0gU0VDT05EKTo6SU5UIEFTIHQsIGF2ZyhDdXJyZW50TWV0cmljX01lbW9yeVRyYWNraW5nKVxuRlJPTSBzeXN0ZW0ubWV0cmljX2xvZ1xuV0hFUkUgZXZlbnRfZGF0ZSA+PSB0b0RhdGUobm93KCkgLSB7c2Vjb25kczpVSW50MzJ9KSBBTkQgZXZlbnRfdGltZSA+PSBub3coKSAtIHtzZWNvbmRzOlVJbnQzMn1cbkdST1VQIEJZIHRcbk9SREVSIEJZIHQifSx7InRpdGxlIjoiTG9hZCBBdmVyYWdlICgxNSBtaW51dGVzKSIsInF1ZXJ5IjoiU0VMRUNUIHRvU3RhcnRPZkludGVydmFsKGV2ZW50X3RpbWUsIElOVEVSVkFMIHtyb3VuZGluZzpVSW50MzJ9IFNFQ09ORCk6OklOVCBBUyB0LCBhdmcodmFsdWUpXG5GUk9NIHN5c3RlbS5hc3luY2hyb25vdXNfbWV0cmljX2xvZ1xuV0hFUkUgZXZlbnRfZGF0ZSA+PSB0b0RhdGUobm93KCkgLSB7c2Vjb25kczpVSW50MzJ9KSBBTkQgZXZlbnRfdGltZSA+PSBub3coKSAtIHtzZWNvbmRzOlVJbnQzMn1cbkFORCBtZXRyaWMgPSAnTG9hZEF2ZXJhZ2UxNSdcbkdST1VQIEJZIHRcbk9SREVSIEJZIHQifSx7InRpdGxlIjoiU2VsZWN0ZWQgUm93cy9zZWNvbmQiLCJxdWVyeSI6IlNFTEVDVCB0b1N0YXJ0T2ZJbnRlcnZhbChldmVudF90aW1lLCBJTlRFUlZBTCB7cm91bmRpbmc6VUludDMyfSBTRUNPTkQpOjpJTlQgQVMgdCwgYXZnKFByb2ZpbGVFdmVudF9TZWxlY3RlZFJvd3MpXG5GUk9NIHN5c3RlbS5tZXRyaWNfbG9nXG5XSEVSRSBldmVudF9kYXRlID49IHRvRGF0ZShub3coKSAtIHtzZWNvbmRzOlVJbnQzMn0pIEFORCBldmVudF90aW1lID49IG5vdygpIC0ge3NlY29uZHM6VUludDMyfVxuR1JPVVAgQlkgdFxuT1JERVIgQlkgdCJ9LHsidGl0bGUiOiJJbnNlcnRlZCBSb3dzL3NlY29uZCIsInF1ZXJ5IjoiU0VMRUNUIHRvU3RhcnRPZkludGVydmFsKGV2ZW50X3RpbWUsIElOVEVSVkFMIHtyb3VuZGluZzpVSW50MzJ9IFNFQ09ORCk6OklOVCBBUyB0LCBhdmcoUHJvZmlsZUV2ZW50X0luc2VydGVkUm93cylcbkZST00gc3lzdGVtLm1ldHJpY19sb2dcbldIRVJFIGV2ZW50X2RhdGUgPj0gdG9EYXRlKG5vdygpIC0ge3NlY29uZHM6VUludDMyfSkgQU5EIGV2ZW50X3RpbWUgPj0gbm93KCkgLSB7c2Vjb25kczpVSW50MzJ9XG5HUk9VUCBCWSB0XG5PUkRFUiBCWSB0In0seyJ0aXRsZSI6IlRvdGFsIE1lcmdlVHJlZSBQYXJ0cyIsInF1ZXJ5IjoiU0VMRUNUIHRvU3RhcnRPZkludGVydmFsKGV2ZW50X3RpbWUsIElOVEVSVkFMIHtyb3VuZGluZzpVSW50MzJ9IFNFQ09ORCk6OklOVCBBUyB0LCBhdmcodmFsdWUpXG5GUk9NIHN5c3RlbS5hc3luY2hyb25vdXNfbWV0cmljX2xvZ1xuV0hFUkUgZXZlbnRfZGF0ZSA+PSB0b0RhdGUobm93KCkgLSB7c2Vjb25kczpVSW50MzJ9KSBBTkQgZXZlbnRfdGltZSA+PSBub3coKSAtIHtzZWNvbmRzOlVJbnQzMn1cbkFORCBtZXRyaWMgPSAnVG90YWxQYXJ0c09mTWVyZ2VUcmVlVGFibGVzJ1xuR1JPVVAgQlkgdFxuT1JERVIgQlkgdCJ9LHsidGl0bGUiOiJNYXggUGFydHMgRm9yIFBhcnRpdGlvbiIsInF1ZXJ5IjoiU0VMRUNUIHRvU3RhcnRPZkludGVydmFsKGV2ZW50X3RpbWUsIElOVEVSVkFMIHtyb3VuZGluZzpVSW50MzJ9IFNFQ09ORCk6OklOVCBBUyB0LCBtYXgodmFsdWUpXG5GUk9NIHN5c3RlbS5hc3luY2hyb25vdXNfbWV0cmljX2xvZ1xuV0hFUkUgZXZlbnRfZGF0ZSA+PSB0b0RhdGUobm93KCkgLSB7c2Vjb25kczpVSW50MzJ9KSBBTkQgZXZlbnRfdGltZSA+PSBub3coKSAtIHtzZWNvbmRzOlVJbnQzMn1cbkFORCBtZXRyaWMgPSAnTWF4UGFydENvdW50Rm9yUGFydGl0aW9uJ1xuR1JPVVAgQlkgdFxuT1JERVIgQlkgdCJ9XSwicGFyYW1zIjp7InJvdW5kaW5nIjoiNjAiLCJzZWNvbmRzIjoiODY0MDAifX0=
