### ISSUE TITLE
Cannot recover from `readonly` mode

### ISSUE THREAD

**Issue by OmarBazaraa** [ClickHouse/ClickHouse#42280]
One of the replicas in our clusters turned into `readonly` mode and we cannot recover it back. It has been in that way for days now.

- I restarted the affected replica multiple times.
- I restarted all the servers in the cluster.
- I ran `SYSTEM RESTART REPLICA my_db.my_table` multiple times on the affected replica.
- I made sure ZooKeeper cluster is working properly and I even restarted all its machines.

All of that with no luck to recover from the `readonly` mode.

When I checked the metadata in ZooKeeper, I noticed that the znode `/clickhouse/tables/my_db/my_table/1-2/replicas/1/is_active` is not present for the `readonly` replica.

We are currently running on `clickhouse-server v22.3.13.80`.

**Comment by den-crane** [comment]
It's probably intersecting parts issue. You can see the error in Clickhouse-server.log right after `detach / attach table`.

'brutal' recovery option: https://github.com/ClickHouse/ClickHouse/issues/35863#issuecomment-1092787460

In specific cases you may use more gentle solutions, manual ZK clean-up.

**Comment by OmarBazaraa** [comment]
Running the following commands solved the issue:

```sql
DETACH TABLE my_db.my_table;
SYSTEM DROP REPLICA '3' FROM ZKPATH '/clickhouse/tables/my_db/my_table/1-2';
ATTACH TABLE my_db.my_table;
SYSTEM RESTORE REPLICA my_db.my_table;
SYSTEM SYNC REPLICA my_db.my_table;
```

But I noticed the number of rows in the table dropped by around 1 billion records. Why is that?

**Comment by den-crane** [comment]
Check detached folder or system.detached_parts on all replicas.

**Comment by OmarBazaraa** [comment]
There are lots of detached parts indeed. How to know which parts to attach without causing duplications?

**Comment by den-crane** [comment]
I would read logs for a time of `ATTACH TABLE my_db.my_table;`

Detached parts have different prefixes, I would attach parts with prefix unexpected_ "detached" today  to another tmp merge tree table and check the data using select after that you can move them into real table using `alter table attch partition from`.
