### ISSUE TITLE
ColumnString::index Code Bug?

### ISSUE THREAD

**Issue by liql2007** [ClickHouse/ClickHouse#42294]
# ColumnString::indexImpl implementation
https://github.com/ClickHouse/ClickHouse/blob/0dd807d19df602cb2b07452a0e81431fcbf72e03/src/Columns/ColumnString.cpp#L260

![image](https://user-images.githubusercontent.com/5180230/195747160-97cced0e-0825-46ba-a110-aaab54b4ba06.png)

# IColumn::index comment
https://github.com/ClickHouse/ClickHouse/blob/0dd807d19df602cb2b07452a0e81431fcbf72e03/src/Columns/IColumn.h#L269
![image](https://user-images.githubusercontent.com/5180230/195747390-17ef7efa-fdf5-437e-b9bf-93ee81a122bf.png)

# Issue
The `index` implementation of `ColumnString` conflicts with `index` api specification  of base class， is this a bug ?

**Comment by evillique** [comment]
The comment refers to the function `index` which is implemented in the ColumnString with the function `selectIndexImpl`:

https://github.com/ClickHouse/ClickHouse/blob/master/src/Columns/ColumnString.cpp#L253

selectIndexImpl function, on the other hand does this exactly as described:

https://github.com/ClickHouse/ClickHouse/blob/master/src/Columns/ColumnsCommon.h#L111
