### ISSUE TITLE
ClickHouse Exception: Too many simultaneous queries Maximum: 350

### ISSUE THREAD

**Issue by wuchunfu** [ClickHouse/ClickHouse#42295]
I encountered a strange problem today, when I run ClickHouse sql, every now and then a node will have `Too many simultaneous queries Maximum: 350.` error, I have adjusted the relevant settings but it still happens, I How to solve this problem.

Below is the error message:

```
ru.yandex.clickhouse.except.ClickHouseUnknownException: ClickHouse exception: Code: 1002, host: 10.1.1.1, port 8123,Code: 202, DB::Exception Received from 10.1.1.2:9100 Too many simultaneous queries Maximum: 350. (TOO_MANY_SIMULTANEOUS_QUERIES)(version 21.9.2.1)
```

![image](https://user-images.githubusercontent.com/29206593/195749243-87b4e9da-eea2-4b45-bbe5-d9ed861e900b.png)

**Comment by evillique** [comment]
What are the mean values for this query in your workload?
```
SELECT count(*) FROM system.processes
```

**Comment by den-crane** [comment]
Provide a reproducible example.
Probably you made an endless loop using Distributed tables pointed to Engine Merge tables which points back to Distributed tables.

**Comment by wuchunfu** [comment]
@alexey-milovidov @den-crane actually we need to batch insert data to each shard in a high speed, avg about `40MB/s`，and `Too many simultaneous queries` error just happen only on some certain node, so i just wonder if it is releated to my hardware, but i cannot find clear proof. Every time it happens, i just find that its  connection with `zookeeper` was lost or in a `CLOSE_WAIT` state.  Any good suggestions to debug this problem?  Antoher question is that if it happens, how can i skip this error node when i want to select a dist table?

**Comment by wuchunfu** [comment]
@alexey-milovidov @den-crane PTAL, thanks.

**Comment by DerekChia** [comment]
> @alexey-milovidov @den-crane actually we need to batch insert data to each shard in a high speed, avg about `40MB/s`，and `Too many simultaneous queries` error just happen only on some certain node, so i just wonder if it is releated to my hardware, but i cannot find clear proof. Every time it happens, i just find that its connection with `zookeeper` was lost or in a `CLOSE_WAIT` state. Any good suggestions to debug this problem? Antoher question is that if it happens, how can i skip this error node when i want to select a dist table?

Try ClickHouse Keeper :)
