### ISSUE TITLE
Does Clickhouse 21.8-lts package have clickhouse-keeper?

### ISSUE THREAD

**Issue by intfish123** [ClickHouse/ClickHouse#42304]
clickhouse-version: `ClickHouse server version 21.8.14.5 (official build).` 

I want to replace zookeeper with clickhouse-keeper, but I don't find the command `clickhouse-keeper` in shell.
```
[root@ceph213 ~]# clickhouse-keeper
-bash: clickhouse-keeper: command not found
```

**Comment by den-crane** [comment]
No it does not have.
You can start it as `clickhouse keeper` (using space)
Or you can create a symlink manually `ln -s /usr/bin/clickhouse /usr/bin/clickhouse-keeper`

21.8 Keeper was experimental, it was announced not experimental on the end of 2021.
I suggest to use keeper version 22.9 (you can use different versions of keeper and server).
