### ISSUE TITLE
How to analyze ReplicasMaxAbsoluteDelay return current time problem?

### ISSUE THREAD

**Issue by hehuyi** [ClickHouse/ClickHouse#42305]
Hi,

Sometimes when the zabbix monitor executes the sql "select value from system.asynchronous_metrics where metric='ReplicasMaxAbsoluteDelay';", it will return a very large value like "52y 9m 18d".

According to the getAbsoluteDelay() function, we knew when queue_update_finish_time is null, this function will return current_time. 

But we want to analyze when and why queue_update_finish_time is null, what can we check from clickhouse system table or log ? We've checked the error log and zookeeper log, but it seems there is no infomation about this problem. 

Thanks.

**Comment by hehuyi** [comment]
getAbsoluteDelay() function

https://clickhouse.com/codebrowser/ClickHouse/src/Storages/StorageReplicatedMergeTree.cpp.html#_ZNK2DB26StorageReplicatedMergeTree16getAbsoluteDelayEv

**Comment by alexey-milovidov** [comment]
It is possible when there were no previous queue updates yet, for example, at server startup.
I also suspect the same effect on re-establishing the session with ZooKeeper.

**Comment by hehuyi** [comment]
> It is possible when there were no previous queue updates yet, for example, at server startup. I also suspect the same effect on re-establishing the session with ZooKeeper.

Thanks for your analyzation. 

According to the asynchronous_metric_log table,it happens every day. So I think it has no relation with server startup.
![image](https://user-images.githubusercontent.com/115774635/196125999-dd0edd36-89df-4f06-83ae-c5b4cd7caca6.png)

For re-establishing the session with ZooKeeper,is there any log or system table I can check? Thanks.

**Comment by hehuyi** [comment]
I've also checked the system.replicas table,and there is no readonly or zookeeper_exception record.
![image](https://user-images.githubusercontent.com/115774635/196156750-139c8a3e-f5eb-4d6a-b4ef-147d5395e63d.png)
