### ISSUE TITLE
What is the ratio between max_connections and the number of ClickHouse server nodes?

### ISSUE THREAD

**Issue by nicelulu** [ClickHouse/ClickHouse#42309]
I have 160 nodes, 80 shard 2 replicas. It has a particularly high number of tcp connections. Why is this happening?
![image](https://user-images.githubusercontent.com/18606973/195801614-d39b0d3c-cd87-49b1-9434-d795000e83af.png)

In another cluster there are only 60 nodes, 20 shards and 3 replicas. It has a lot less tcp connections.
![image](https://user-images.githubusercontent.com/18606973/195808378-09e5f7b3-dac5-4dc3-a21c-3ee9fe94f784.png)

**Comment by den-crane** [comment]
To execute distributes queries each node holds a pool of open TCP connections to connect to all other nodes. 

```sql
select * from system.settings where name = 'distributed_connections_pool_size';
┌─name──────────────────────────────┬─value─┬─changed─┬─description───────────────────────────────────────────────────────┬─min──┬─max──┬─readonly─┬─type───┐
│ distributed_connections_pool_size │ 1024  │       0 │ Maximum number of connections with one remote server in the pool. │ ᴺᵁᴸᴸ │ ᴺᵁᴸᴸ │        0 │ UInt64 │
└───────────────────────────────────┴───────┴─────────┴───────────────────────────────────────────────────────────────────┴──────┴──────┴──────────┴────────┘
```

Probably the second cluster executes less queries per second.

**Comment by nicelulu** [comment]
> Also it has less shards, need to make less connections to execute a distributed query.

The ClickHouseMetrics_TCPConnection metric is server-side, a distributed query, and only a connection for other shards.

**Comment by nicelulu** [comment]
Clusters with many connections only have 1 query per second. 4 queries per second for clusters with few connections.
![image](https://user-images.githubusercontent.com/18606973/195813797-d9ea875c-6161-4f89-adfe-5cafc6f9db15.png)
![image](https://user-images.githubusercontent.com/18606973/195814138-24642e23-17ed-4b32-9539-f16baa4a4c7a.png)

**Comment by den-crane** [comment]
I guess `netstat -ant|grep 9000` will explains more.

**Comment by nvartolomei** [comment]
1 QPS, but how long the queries are running? Number of open tcp connections directly proportional to number of concurrent queries running (`CurrentMetric_Query` column in `system.metric_log`).
