### ISSUE TITLE
max_server_memory_usage_to_ram_ratio > 1

### ISSUE THREAD

**Issue by acoj1993** [ClickHouse/ClickHouse#42307]
Hi,

I would like to ask about the ClickHouse behavior with the following:
Here is a [StackOverflow post](https://stackoverflow.com/questions/68592186/clickhouse-memory-issue) that pretty much summarizes our issue. The OP's fix that solved the out-of-memory exceptions was to use set max_server_memory_usage_to_ram_ratio to 1.2. 
Furthermore, a comment in the ClickHouse config.xml says that in memory-constrained environments, you may have to set this to a value larger than 1.

I would like to know, how does that then work? How does Clickhouse reach (or use) 120% of available physical RAM?

We run our ClickHouse in Kubernetes and have so far allowed it to use 90% of the available 100GB of RAM. We have a query with “group by” that wants to use more than the available 90% and the ClickHouse throws an exception. What would you suggest we should do?

**Comment by den-crane** [comment]
1. It will use SWAP.
2. Old versions of Clickhouse has an issue in MemoryTracker, MemoryTracker accounted more memory than really was used, in some cases to overcome this bug it was needed to set max_server_memory_usage_to_ram_ratio=10.
