### ISSUE TITLE
Example of how to use `remove` override in yaml format?

### ISSUE THREAD

**Issue by tasdflkjweio** [ClickHouse/ClickHouse#42318]
I'd like to leave the main config file untouched and simply remove the entries for `postgresql_port` and `mysql_port` in a separate config file. I'm using yaml rather than XML. I'm not seeing an example of this in the docs. Thanks!

**Comment by den-crane** [comment]
```
# cat /etc/clickhouse-server/users.d/xxxxx.yaml
users:
  default:
    "@remove": remove
```

**Comment by tasdflkjweio** [comment]
many thanks!
