### ISSUE TITLE
AWS S3 multipart upload improvements

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#42335]
**Describe the situation**
According to s3 documentation 

>https://docs.aws.amazon.com/whitepapers/latest/s3-optimizing-performance-best-practices/use-byte-range-fetches.html
>Typical sizes for byte-range requests are 8 MB or 16 MB. If objects are PUT using a multipart upload, it’s a good practice to GET them in the same part sizes (or at least aligned to part boundaries) for best performance. GET requests can directly address individual parts; for example, GET ?partNumber=N. 

Basically, it does mean that AWS S3 does not concat multipart uploaded objects and they reside in different "shards" as is.
Right now ClickHouse uses exponential formula to calculate upload part size: https://github.com/ClickHouse/ClickHouse/pull/34422
Which can be sub optimal in case of MergeTree tables. 

Proposal:
Do not use exponential formula for MergeTree files upload, just split them in even parts, as we know estimated/total size of uploaded file.

**Additional context**

https://github.com/ClickHouse/ClickHouse/pull/25615#issuecomment-906660521
https://github.com/ClickHouse/ClickHouse/pull/29205

**Comment by alexey-milovidov** [comment]
We don't know the estimated size of the uploaded file.

**Comment by UnamedRus** [comment]
For merge tree we can quite easily estimate possible file size. 

it highly unlikely will be smaller than one of merge file size and no bigger than 2x of total file size.
