### ISSUE TITLE
No late materialization for order by with limit

### ISSUE THREAD

**Issue by worthdone** [ClickHouse/ClickHouse#42331]
**Describe the situation**
I was expecting late materialization for reading columns, but it's not there.

**How to reproduce**
I use https://play.clickhouse.com/play

```
select created_date from reddit order by created_date desc limit 100;
```

Elapsed: 0.474 sec, read 9.95 billion rows, 19.89 GB.

```
select created_date, body from reddit order by created_date desc limit 100;
```

Code: 160. DB::Exception: Estimated query execution time (85.33208355068749 seconds) is too long. Maximum: 60. Estimated rows to process: 9946243959: While executing MergeTreeThread. (TOO_SLOW) (version 22.10.1.566 (official build))

**Expected performance**
I think late materialization can greatly increase performance.

**Comment by UnamedRus** [comment]
Duplicate https://github.com/ClickHouse/ClickHouse/issues/5329#issuecomment-578454900
