### ISSUE TITLE
Clarification about the cardinality limit for `Array(LowCardinality(String))`?

### ISSUE THREAD

**Issue by srikanthccv** [ClickHouse/ClickHouse#42334]
Hello,

The description for `LowCardinality` type says that https://clickhouse.com/docs/en/sql-reference/data-types/lowcardinality/#description.

> The efficiency of using LowCardinality data type depends on data diversity. If a dictionary contains less than 10,000 distinct values, then ClickHouse mostly shows higher efficiency of data reading and storing. If a dictionary contains more than 100,000 distinct values, then ClickHouse can perform worse in comparison with using ordinary data types.

My understanding is, If I have a column with this type and the data is more diverse (e.g few million distinct points) then it tends to perform poorly. 

How does this apply to the column type `Array(LowCardinality(String))`? Is that limit applied to all of the values combined in all of the arrays? or is it just a limit on one row of data? It's not clear from the documentation and I am looking for some clarification. Because I have a sample dataset that has more than the suggested theoretical limit and it appears to be still outperforming (~2x as fast) the regular `String` type. Could it be because of the number of data parts ( I have ~ 230 parts at the moment)?

**Comment by UnamedRus** [comment]
Check this discussion about how LC works

https://github.com/ClickHouse/ClickHouse/issues/36428

> or is it just a limit on one row of data? 
It's limit per some block of rows.

Array doesn't change a lot of things here

**Comment by alexey-milovidov** [comment]
> Is that limit applied to all of the values combined in all of the arrays?

This.

> Because I have a sample dataset that has more than the suggested theoretical limit and it appears to be still outperforming (~2x as fast) the regular String type. Could it be because of the number of data parts ( I have ~ 230 parts at the moment)?

There is no hard limit on the number of distinct values for `LowCardinality`.
If the number is large, it will still work fine, although can be less performant than without LowCardinality.
The LowCardinality data type does not use one giant dictionary - it can use multiple smaller dictionaries for different ranges of data.

**Comment by srikanthccv** [comment]
@alexey-milovidov Thank for the info. Is there a some heuristic approach how ClickHouse decides to maintain the dictionary for range of data. Is it some X number of granules or rows or something similar?
