### ISSUE TITLE
converting `Int` or `UInt` type to `Date`, gets different results 

### ISSUE THREAD

**Issue by cangyin** [ClickHouse/ClickHouse#42365]
**Describe the unexpected behaviour**
**Int64 vs UInt64**
```sql
select toYYYYMMDD(toDate(recordTimestamp)),toDate(recordTimestamp), toInt64(1665519765) as recordTimestamp
┌─toYYYYMMDD(toDate(toInt64(1665519765)))─┬─toDate(toInt64(1665519765))─┬─recordTimestamp─┐
│                                21490606 │                  2149-06-06 │      1665519765 │
└─────────────────────────────────────────┴─────────────────────────────┴─────────────────┘
```
```sql
select toYYYYMMDD(toDate(recordTimestamp)),toDate(recordTimestamp), toUInt64(1665519765) as recordTimestamp

┌─toYYYYMMDD(toDate(toUInt64(1665519765)))─┬─toDate(toUInt64(1665519765))─┬─recordTimestamp─┐
│                                 20221012 │                   2022-10-12 │      1665519765 │
└──────────────────────────────────────────┴──────────────────────────────┴─────────────────┘
```
**Int32 vs UInt32**
```sql
select toYYYYMMDD(toDate(recordTimestamp)),toDate(recordTimestamp), toInt32(1665519765) as recordTimestamp,toTypeName                                                                  (recordTimestamp)
┌─toYYYYMMDD(toDate(toInt32(1665519765)))─┬─toDate(toInt32(1665519765))─┬─recordTimestamp─┬─toTypeName(toInt32(1665519765))─┐
│                                21490606 │                  2149-06-06 │      1665519765 │ Int32                           │
└─────────────────────────────────────────┴─────────────────────────────┴─────────────────┴─────────────────────────────────┘
```
```sql
select toYYYYMMDD(toDate(recordTimestamp)),toDate(recordTimestamp), toUInt32(1665519765) as recordTimestamp,toTypeName(recordTimestamp)

┌─toYYYYMMDD(toDate(toUInt32(1665519765)))─┬─toDate(toUInt32(1665519765))─┬─recordTimestamp─┬─toTypeName(toUInt32(1665519765))─┐
│                                 20221012 │                   2022-10-12 │      1665519765 │ UInt32                           │
└──────────────────────────────────────────┴──────────────────────────────┴─────────────────┴──────────────────────────────────┘
```

**Expected behavior**
`Int` and `UInt` with same value converts to same DateTime result.

**ClickHouse server version**
v22.9.1.1

**Comment by cangyin** [comment]
Is the issue related about PR [#40217](https://github.com/ClickHouse/ClickHouse/pull/40217) ?

**Comment by alexey-milovidov** [comment]
Yes, it's a regression. Let's revert https://github.com/ClickHouse/ClickHouse/pull/40217

**Comment by zvonand** [comment]
Well, not a good way to solve a problem.
In existing logic (I am not the creator of this logic), UInt32 is treated as DateTime, and Int32 is Date32.
Are you sure this issue was introduced by my pr?

**Comment by cangyin** [comment]
> Are you sure this issue was introduced by my pr?
Not quite for sure. Doing a quick testing at [ClickFiddle](https://fiddle.clickhouse.com/c75374ce-48ea-46e3-8f59-d0229f6f0169), helps narrowing down the version range. And found the behavior only in versions 22.9.*.

I am just stating that the PR found in [changelog](https://clickhouse.com/docs/en/whats-new/changelog/#-clickhouse-release-227-2022-07-21:~:text=More%20natural%20conversion%20of%20Date32%2C%20DateTime64%2C%20Date%20to%20narrower%20types%3A%20upper%20or%20lower%20normal%20value%20is%20considered%20when%20out%20of%20normal%20range) looks as related.

**Comment by alexey-milovidov** [comment]
@zvonand Either your PR or @rvasin 's PR.

**Comment by alexey-milovidov** [comment]
@zvonand it's your PR because reverting helps: https://s3.amazonaws.com/clickhouse-test-reports/42367/2023f38764dea3df043f912db7bcbb19c8221dd1/fast_test.html (I've added a test).

**Comment by alexey-milovidov** [comment]
@zvonand 

> Well, not a good way to solve a problem.

We use the "revert early, revert often" approach. If something introduces a bug, it should be reverted first, then investigated further.

**Comment by zvonand** [comment]
Ok, I'll fix it and make a new one
