### ISSUE TITLE
DB::ErrnoException: Allocator: Cannot mremap memory chunk from 2.00 GiB to 4.00 GiB., errno: 14, strerror: Bad address. (CANNOT_MREMAP)

### ISSUE THREAD

**Issue by selfboot** [ClickHouse/ClickHouse#42368]
(you don't have to strictly follow this form)

**Describe the unexpected behaviour**
I have a sql fails to run and give message : 
> Error on processing query: Code: 240. DB::ErrnoException: Allocator: Cannot mremap memory chunk from 2.00 GiB to 4.00 GiB., errno: 14, strerror: Bad address. (CANNOT_MREMAP) (version 22.2.2.1)

**How to reproduce**
* Which ClickHouse server version to use
ClickHouse server version 21.8.12 revision 54449.
ClickHouse client version 22.2.2.1.

* Queries to run that lead to unexpected result

```
WITH toDate('2017-01-01') as baseDate,
 toDate('2019-07-01') as calMonth,
 dateDiff('month', baseDate, calMonth) as monthIdx
 SELECT concat(toString(vid), '#', toString(bookid), '#', toString(monthIdx)) as key,
 groupArray(info) as meta
 FROM
 (SELECT dateDiff('day', baseDate, toDate(date)) AS diff,
 vid,
 bookid,
 sum(readtime) AS total,
 concat(toString(diff), ':', toString(total)) AS info
 FROM table_name
 WHERE toStartOfMonth(toDate(date)) = toStartOfMonth(calMonth)
 GROUP BY vid,
 bookid, date)
 GROUP BY vid, bookid
```
(Most  calMonth works fun, but some run fail)

**Expected behavior**
Give the right data.

**Comment by alexey-milovidov** [comment]
It is possible in case of memory shortage.

**Comment by selfboot** [comment]
> 

I increase the memory limit by  `--max_memory_usage=50G ` , it's enough.

**Comment by selfboot** [comment]
Get memory use:
```
SELECT
    event_time, query_duration_ms / 1000 AS secs,
    formatReadableSize(memory_usage) AS memory,
    Settings['max_threads'] AS threads,
    query
FROM system.query_log AS ql
WHERE type = 'QueryFinish'
ORDER BY event_time DESC
LIMIT 50
```

<img width="701" alt="image" src="https://user-images.githubusercontent.com/2769831/196329607-843ce218-c446-4528-90ab-d67430c2cfa0.png">
