### ISSUE TITLE
query MaterializedMySQL table error

### ISSUE THREAD

**Issue by onine007** [ClickHouse/ClickHouse#42373]
2022.10.17 14:05:37.485578 [ 14660 ] {8008c835-90e9-4939-9176-48f4d0d39644} <Error> executeQuery: Code: 49. DB::Exception: GTIDSets updates other: 2161866999 invalid successor to 2161867000. (LOGICAL_ERROR) (version 22.8.6.71 (official build)) (from [::ffff:172.25.10.176]:39418) (in query: select iso2, name_en, pic from hwsj_admin.country_info where iso2 in ( 'BR' , 'BR' , 'BR' , 'BR' , 'BR' , 'BR' , 'BR' , 'BR' , 'BR' , 'BR' , 'BR' , 'BR' , 'BR' , 'BR' , 'BR' , 'BR' , 'BR' , 'BR' , 'BR' , 'BR' , 'BR' , 'BR' , 'BR' , 'BR' , 'BR' , 'BR' , 'BR' , 'BR' , 'BR' , 'BR' , 'BR' , 'BR' , 'BR' , 'BR' , 'BR' , 'BR' , 'BR' , 'BR' , 'BR' , 'BR' , 'BR' , 'BR' , 'BR' , 'BR' , 'BR' , 'BR' , 'BR' , 'BR' , 'BR' , 'BR' ) FORMAT TabSeparatedWithNamesAndTypes;), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa3ec73a in /usr/bin/clickhouse
1. DB::GTIDSets::update(DB::GTID const&) @ 0x142dda7a in /usr/bin/clickhouse
2. DB::MySQLReplication::Position::update(std::__1::shared_ptr<DB::MySQLReplication::EventBase>) @ 0x142e86ba in /usr/bin/clickhouse
3. DB::MySQLReplication::MySQLFlavor::readPayloadImpl(DB::ReadBuffer&) @ 0x142e973d in /usr/bin/clickhouse
4. DB::MySQLProtocol::IMySQLReadPacket::readPayload(DB::ReadBuffer&, unsigned char&) @ 0x142d41cb in /usr/bin/clickhouse
5. DB::MySQLProtocol::PacketEndpoint::tryReceivePacket(DB::MySQLProtocol::IMySQLReadPacket&, unsigned long) @ 0x142d4cad in /usr/bin/clickhouse
6. DB::MaterializedMySQLSyncThread::synchronization() @ 0x144f1d8e in /usr/bin/clickhouse
7. ? @ 0x145008ac in /usr/bin/clickhouse
8. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa4ae1a8 in /usr/bin/clickhouse
9. ? @ 0xa4b13bd in /usr/bin/clickhouse
10. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
11. clone @ 0xfeb0d in /usr/lib64/libc-2.17.so

2022.10.17 14:05:37.485683 [ 14660 ] {8008c835-90e9-4939-9176-48f4d0d39644} <Error> DynamicQueryHandler: Code: 49. DB::Exception: GTIDSets updates other: 2161866999 invalid successor to 2161867000. (LOGICAL_ERROR), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa3ec73a in /usr/bin/clickhouse
1. DB::GTIDSets::update(DB::GTID const&) @ 0x142dda7a in /usr/bin/clickhouse
2. DB::MySQLReplication::Position::update(std::__1::shared_ptr<DB::MySQLReplication::EventBase>) @ 0x142e86ba in /usr/bin/clickhouse
3. DB::MySQLReplication::MySQLFlavor::readPayloadImpl(DB::ReadBuffer&) @ 0x142e973d in /usr/bin/clickhouse
4. DB::MySQLProtocol::IMySQLReadPacket::readPayload(DB::ReadBuffer&, unsigned char&) @ 0x142d41cb in /usr/bin/clickhouse
5. DB::MySQLProtocol::PacketEndpoint::tryReceivePacket(DB::MySQLProtocol::IMySQLReadPacket&, unsigned long) @ 0x142d4cad in /usr/bin/clickhouse
6. DB::MaterializedMySQLSyncThread::synchronization() @ 0x144f1d8e in /usr/bin/clickhouse
7. ? @ 0x145008ac in /usr/bin/clickhouse
8. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa4ae1a8 in /usr/bin/clickhouse
9. ? @ 0xa4b13bd in /usr/bin/clickhouse
10. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
11. clone @ 0xfeb0d in /usr/lib64/libc-2.17.so
 (version 22.8.6.71 (official build))

**Comment by alexey-milovidov** [comment]
Need help from @stigsb who is the only remaining maintainer of the MaterializedMySQL.

**Comment by stigsb** [comment]
Check your `binlog_order_commits` MySQL server setting? If it's disabled, that's the problem. MaterializedMySQL does not currently handle unordered commits in the binlog.

**Comment by welyss** [comment]
same, and binlog_order_commits is enabled
