### ISSUE TITLE
Is there a way to wait while a replicated table will have consistent state between masters?

### ISSUE THREAD

**Issue by svetlyak40wt** [ClickHouse/ClickHouse#42375]
In my project I often rename table or alter it's partitions. When the next time process connects to other master, it might try to change table where partitions wasn't changed yet. And this leads to data loss and mysterious behaviour.

 If there a way to wait while all manipulations with a replicated table are done on all masters before I'll apply further changes?

**Comment by den-crane** [comment]
`alter table ..... settings mutations_sync=2,replication_alter_partitions_sync=2`

mutations_sync - Wait for synchronous execution of ALTER TABLE UPDATE/DELETE queries (mutations). 0 - execute asynchronously. 1 - wait current server. 2 - wait all replicas if they exist.


replication_alter_partitions_sync - Wait for actions to manipulate the partitions. 0 - do not wait, 1 - wait for execution only of itself, 2 - wait for everyone.

**Comment by svetlyak40wt** [comment]
Cool! Thank you, Den!

Is there something like this for RENAME TABLE and EXCHANGE TABLES?

**Comment by azat** [comment]
For `RENAME`/`EXCHANGE` you can use `ON CLUSTER`
