### ISSUE TITLE
What is the insertion speed of clickhouse？

### ISSUE THREAD

**Issue by JavaAndPython55** [ClickHouse/ClickHouse#42374]
I tested clickhouse and got about 400,000 inserts per second. After I upgraded the hardware and the cpu, the insertion rate still didn't improve. Then I went to multithreading and generated 10 threads processing 1 million data per batch. There was no significant change. How can I steadily increase clickhouse insertion speed? Our data is about 60 watts per second coming from kafka

**Comment by genzgd** [comment]
There are many factors that can affect insertion speed -- the size and format of your data, the speed of your disk, the amount of memory you have for processing inserts, the number of cores, and if you are coming from Kafka, possibly the number of partitions you have in your topic.  400k records per second on a single host for large event records is reasonable.

You should look at your server metrics to see where you are hitting a bottleneck (memory/disk/CPU) and possible tune your Kafka engine to ensure you are consuming one partition per thread/CPU core.

**Comment by alexey-milovidov** [comment]
> Our data is about 60 watts per second coming from kafka

What does it mean "60 watts per second"?

**Comment by JavaAndPython55** [comment]
@alexey-milovidov 600,000 the data is inserted every second

**Comment by alexey-milovidov** [comment]
400 000 rows per second can be normal for a moderately wide table and a mediocre server for single-threaded insertion.

For example, a table `hits` from [ClickBench](https://github.com/ClickHouse/ClickBench/) contains 105 columns, and every row is around 748 bytes per row in TSV format.

The insertion of 99 997 497 in a single thread with the following query:
```
INSERT INTO hits2 FROM INFILE 'hits.tsv'
```
took 176.6 seconds on my machine, 
which is 566 026 rows per second.
