### ISSUE TITLE
May I ask where I can change the default password I set when I start docker? thanks

### ISSUE THREAD

**Issue by xintains** [ClickHouse/ClickHouse#42381]
![image](https://user-images.githubusercontent.com/85427915/196158389-ee3768f7-ade8-4d31-959c-3c11eb059194.png)

**Comment by filimonov** [comment]
setup CLICKHOUSE_PASSWORD env. 

Or mount it the config file with needed user.

https://github.com/ClickHouse/ClickHouse/blob/c9aa6a655cf3f6621a27c45ea921304297c33f19/docker/server/entrypoint.sh#L83

**Comment by xintains** [comment]
> setup CLICKHOUSE_PASSWORD env.
> 
> Or mount it the config file with needed user.
> 
> https://github.com/ClickHouse/ClickHouse/blob/c9aa6a655cf3f6621a27c45ea921304297c33f19/docker/server/entrypoint.sh#L83
I mean to change the password that has already been configured. I've found a place where I can change the password in /var/lib/docker/container/${containerId}/config.v2.json.
But still thank you
