### ISSUE TITLE
Row policy is not working properly

### ISSUE THREAD

**Issue by OmarBazaraa** [ClickHouse/ClickHouse#42394]
I have created the following `ROW POLICY`...

```sql
CREATE ROW POLICY IF NOT EXISTS my_row_policy
ON CLUSTER clickhouse_cluster
ON my_db.my_table
USING <condition>
AS RESTRICTIVE
TO user_1;
```

And according to the docs, I also have to add a default policy for other users...

```sql
CREATE ROW POLICY IF NOT EXISTS my_default_row_policy
ON CLUSTER clickhouse_cluster
ON my_db.my_table
USING 1
TO ALL EXCEPT user_1;
```

After adding these policies, I no longer get any results upon running any query from any user (i.e., not just `user_1`).
Is this the correct way of adding `ROW POLICIES`? Why other users are affected? And why the queries issued from `user_1` are not returning correct results?

**Note:** We are running on `clickhouse-server v22.3`.

**Comment by vitlibar** [comment]
You can fix that by setting `users_without_row_policies_can_read_rows` to true [here](https://github.com/ClickHouse/ClickHouse/blob/5ffd026261a4d91d634b235e254f2ee326040f0f/programs/server/config.xml#L647)

**Comment by OmarBazaraa** [comment]
I still don't get any results for queries issued by `user_1` when I should.

```SQL
CREATE ROW POLICY IF NOT EXISTS my_row_policy
ON CLUSTER clickhouse_cluster
ON my_db.my_table
USING A = 1
AS RESTRICTIVE
TO user_1;
```

After adding this ROW POLICY, the following query returns 0 when it shouldn't...

```SQL
SELECT count()
FROM my_db.my_table
```

Note that column `A` has many different values.

**Comment by raspreet-vunet** [comment]
Can this issue be reopened? What @OmarBazaraa is talking about and what the `users_without_row_policies_can_read_rows` setting does are two different things. 

The issue is that when only 1 policy is applied to a table and that policy is restrictive, the select query returns 0 rows even if the condition defined in the policy matches some rows.
