### ISSUE TITLE
Replicated DB Engine: is there possibility to execute local DDL e.g. drop table on single node only?

### ISSUE THREAD

**Issue by pavel-naumenko** [ClickHouse/ClickHouse#42390]
Suppose there is Replicated db created with ReplicatedMergeTree table.
Then for some reason one node is corrupted and want to recreate local table as full sync from other node.

On single DB i.e. Atomic in worst scenario it is possible to simply recreate table
i.e. 
- clean corrupted data by using DROP TABLE w/o ON CLUSTER clause 
- then clean metadata by SYSTEM DROP REPLICA,
- then recreate table
- data will be replicated.

On Replicated DB, if you try DROP table DDL will be executed on replicated db instances.
So is there any other way to drop table on single node only?
Also documentation says   ALTER TABLE DETACH PARTITION|PART queries are allowed but not replicated. 
Is this still valid e.g. in 22.9.2.7 it looks that if you DETACH part/partition DDL is also executed on all replicated db nodes, not just local node?

**Comment by alexey-milovidov** [comment]
As far as I know, Replicated database replicates all the DDL queries and does not allow running any DDL queries on a single node.

> Also documentation says ALTER TABLE DETACH PARTITION|PART queries are allowed but not replicated.

The documentation looks correct but is not clear enough. When you run ALTER TABLE for Replicated tables, the statement is replicated by the table engine, not the database engine. So, the queries are replicated nevertheless.

**Comment by alexey-milovidov** [comment]
Recreating a single replica of a table is unsolved for Replicated database.
