### ISSUE TITLE
How to pass clickhouse server related settings while loading a table from PySpark

### ISSUE THREAD

**Issue by swarupsarangi113** [ClickHouse/ClickHouse#42425]
### What am I doing?

I am running an ETL Job which is loading data from S3 to Clickhouse using PySpark.

### What is the issue?

I am getting this error - 

```
DB::Exception: Too many partitions for single INSERT block (more than 100). The limit is controlled by 'max_partitions_per_insert_block' setting. Large number of partitions is a common misconception. It will lead to severe negative performance impact, including slow server startup, slow INSERT queries and slow SELECT queries. Recommended total number of partitions for a table is under 1000..10000. Please note, that partitioning is not intended to speed up SELECT queries (ORDER BY key is sufficient to make range queries fast). Partitions are intended for data manipulation (DROP PARTITION, etc). (version 21.8.10.1.altinitystable (altinity build))
```
### What I did 

I was able to set the parameter `SET max_partitions_per_insert_block = 0` in clickhouse-client and load the data directly from S3 to Clickhouse using
```
INSERT INTO my_table SELECT * FROM s3(s3_path,'Parquet','column column_type'....)
SETTINGS max_partitions_per_insert_block = 0,max_threads = 4, max_insert_threads = 4;
```

But I want to pass the setting `SET max_partitions_per_insert_block = 0` via PySpark code and not using `INSERT INTO ....`

Also, I did try this code snippet - 

```
    def load_into_clickhouse(self, dataframe, dest_db_name, dest_table_name, create_table_options):
        dataframe.write \
            .format("jdbc") \
            .mode("overwrite") \
            .option("driver", "com.clickhouse.jdbc.ClickHouseDriver") \
            .option("url", self.url) \
            .option("createTableOptions", """engine=MergeTree()
                                primary key (prospectid)
                                order by (prospectid, toYYYYMM(createdon), toYYYYMM(modifiedon))
                                partition by (prospectstage, toYYYYMM(createdon))
                                SETTINGS max_partitions_per_insert_block = 0
								""") \
            .option("user", self.user_name) \
            .option("password", self.password) \
            .option("dbtable", f"{dest_db_name}.{dest_table_name}") \
            .option("batchsize", "50000") \
            .option("truncate", "true") \
            .save()
```
But I got this error again which is expected - 

`DB::Exception: Unknown setting max_partitions_per_insert_block: for storage MergeTree (version 21.8.10.1.altinitystable (altinity build))`

So how to pass these server related parameters from pyspark code ?

Can anyone help me on this?

**Comment by SaltTan** [comment]
You need to pass this setting with the INSERT statement, not with CREATE TABLE.

**Comment by swarupsarangi113** [comment]
I want to pass the SETTINGS in my PySpark code because I have the final processed dataframe there and I don't want to store the final dataframe in S3 thats why I can't use `INSERT` command therefore can't pass the SETTINGS with INSERT command

**Comment by alexey-milovidov** [comment]
> (version 21.8.10.1.altinitystable (altinity build))

This version is unofficial, and it is unsupported.
Altinity builds known for having bugs and security vulnerabilities.
