### ISSUE TITLE
toYYYYMMDD function error

### ISSUE THREAD

**Issue by vasonyang** [ClickHouse/ClickHouse#42422]
**Describe the unexpected behaviour**
Clickhouse server version: 21.12.3.32
a column createTime value is 1665851614897
createTime/1000  result is 1665851614.897
toDateTime(createTime / 1000) result is 2022-10-16 00:33:34.000
but toYYYYMMDD(toDateTime(createTime / 1000))  result is 20221015

**How to reproduce**
select 1665851614897 as createTime, 1665851614897/1000, toDateTime(1665851614897 / 1000), toYYYYMMDD(toDateTime(1665851614897 / 1000))

**Expected behavior**
the toYYYYMMDD(toDateTime(1665851614897 / 1000))  result should be 20221016

**Comment by tavplubix** [comment]
It's because values of `DateTime` type are printed in local timezone by default:
```
dell9510 :) with 1665851614897 as createTime select timezone(), toDateTime(createTime / 1000) as local_time, toDateTime(createTime / 1000, 'UTC') as utc_time, toYYYYMMDD(toDateTime(createTime / 1000)) as yyyymmdd

WITH 1665851614897 AS createTime
SELECT
    timezone(),
    toDateTime(createTime / 1000) AS local_time,
    toDateTime(createTime / 1000, 'UTC') AS utc_time,
    toYYYYMMDD(toDateTime(createTime / 1000)) AS yyyymmdd

Query id: c910ee59-f500-474e-a0dd-d5f4e904f7fa

┌─timezone()───────┬──────────local_time─┬────────────utc_time─┬─yyyymmdd─┐
│ Europe/Amsterdam │ 2022-10-15 18:33:34 │ 2022-10-15 16:33:34 │ 20221015 │
└──────────────────┴─────────────────────┴─────────────────────┴──────────┘

1 row in set. Elapsed: 0.007 sec.
```
However, internal representation of `DateTime` does not depend on timezone, it only affects how dates are printed:
```
dell9510 :) with 1665851614897 as createTime select toDateTime(createTime / 1000) = toDateTime(createTime / 1000, 'UTC')

WITH 1665851614897 AS createTime
SELECT toDateTime(createTime / 1000) = toDateTime(createTime / 1000, 'UTC')

Query id: 5b3deea3-bcf2-45d8-afd5-5c9f220b2df6

┌─equals(toDateTime(divide(createTime, 1000)), toDateTime(divide(createTime, 1000), 'UTC'))─┐
│                                                                                         1 │
└───────────────────────────────────────────────────────────────────────────────────────────┘

1 row in set. Elapsed: 0.006 sec. 

```

And `toYYYYMMDD` takes internal representation of `DateTime` in UTC and prints its date. It's possible to specify other timezone in `toYYYYMMDD`:
```
dell9510 :) with 1665851614897 as createTime select toYYYYMMDD(toDateTime(createTime / 1000), 'Asia/Singapore') as yyyymmdd

WITH 1665851614897 AS createTime
SELECT toYYYYMMDD(toDateTime(createTime / 1000), 'Asia/Singapore') AS yyyymmdd

Query id: c50a9f0f-8f38-4c1a-9e6c-8d358592617b

┌─yyyymmdd─┐
│ 20221016 │
└──────────┘

1 row in set. Elapsed: 0.082 sec. 
```

**Comment by den-crane** [comment]
>do you mean the partition by sql should be toYYYYMMDD(toDateTime(createTime / 1000), 'Asia/Singapore') ?

Avoid to use toYYYYMMDD/toYYYYMM in partition expression. Use  toStartOfDay/toStartOfMonth - `partition by toStartOfDay(toDateTime(createTime / 1000))`.

**Comment by vasonyang** [comment]
> > do you mean the partition by sql should be toYYYYMMDD(toDateTime(createTime / 1000), 'Asia/Singapore') ?
> 
> Avoid to use toYYYYMMDD/toYYYYMM in partition expression. Use toStartOfDay/toStartOfMonth - `partition by toStartOfDay(toDateTime(createTime / 1000))`.

1. why avoid to use toYYYYMMDD/toYYYYMM in partition expression? 
2. I tried  `toStartOfDay(toDateTime(createTime / 1000))` ，when the createTime is  1665851614897 the result is `2022-10-15 08:00:00.000`, but the result should be `2022-10-16 08:00:00.000`, did I  should use the function as ` partition by toStartOfDay(toDateTime(createTime / 1000), 'Asia/Singapore')` ?   I didn't see the different with `toYYYYMMDD(toDateTime(createTime / 1000), 'Asia/Singapore')`.
