### ISSUE TITLE
Weird query optimization

### ISSUE THREAD

**Issue by nvartolomei** [ClickHouse/ClickHouse#4242]
Table example:

```sql
DROP TABLE IF EXISTS constCondOptimization;
CREATE TABLE constCondOptimization
(
    d Date DEFAULT today(),
    time DateTime DEFAULT now(),
    n Int64
)
ENGINE = MergeTree(d, (time, n), 1);

INSERT INTO constCondOptimization (n) SELECT number FROM system.numbers LIMIT 1000000;
```

The following query is not optimized to use the index.
```sql
SELECT count() FROM constCondOptimization WHERE if(0, 1, n = 1000);
```

> 1 rows in set. Elapsed: 0.025 sec. Processed 1.00 million rows, 8.00 MB (40.26 million rows/s., 322.07 MB/s.)

However, this one is optimized:

```sql
SELECT count() FROM constCondOptimization WHERE if(0, 1, n = 1000) AND 1 = 1;
```

> 1 rows in set. Elapsed: 0.008 sec.

The following one is not, but could be, as 1=0 is constantly false.

```sql
SELECT count() FROM constCondOptimization WHERE if(1=0, 1, n = 1000) AND time between now() - 300 AND now();
```

> 1 rows in set. Elapsed: 0.357 sec. Processed 1.00 million rows, 8.00 MB (2.80 million rows/s., 22.44 MB/s.)

It gets a bit more weird as this query works as expected:

```sql
SELECT count() FROM constCondOptimization WHERE if(1, 1, n = 1000) AND time between now() - 300 AND now();
```

However not the following:

```sql
SELECT count() FROM constCondOptimization WHERE if(1, 1, n = 1000);
```

> Received exception from server (version 18.16.1):
Code: 47. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Unknown identifier: n.

**Comment by 4ertus2** [comment]
The last result is an error itself.

**Comment by 4ertus2** [comment]
Fix unknown identifier #4952

**Comment by nvartolomei** [comment]
It looks like there is no code at all for doing these sort of optimisations. @4ertus2 any plans on roadmap for them?

**Comment by alexey-milovidov** [comment]
Fixed.
