### ISSUE TITLE
Schema inference in clickhouse-local can work for unknown files, if the format has only one possible inferred schema.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#42501]
Example: this works:
```
cat /dev/urandom | clickhouse-local --format LineAsString --structure 'line String' --progress --query "SELECT * FROM table" > /dev/null
```
but this does not:
```
cat /dev/urandom | clickhouse-local --format LineAsString --progress --query "SELECT * FROM table" > /dev/null
```

**Comment by Avogar** [comment]
This works:
`cat /dev/urandom | clickhouse-local --input-format LineAsString --progress --query "SELECT * FROM table" > /dev/null`

Seems like we don't check format from `--format` argument properly, need to fix

**Comment by Avogar** [comment]
Hmm, no, second variant won't work, we cannot distinguish between these two types of queries:
```
$ echo "1,2" | clickhouse-local --format CSV -q "select * from table"
```
And
```
clickhouse-local --format CSV -q "select * from numbers(10)"
```
So we need to get rid of `format` argument in `clickhouse-local` I think
