### ISSUE TITLE
INSERT INTO function remoteSecure(...) max memory limit exceeded. How to increase limit (set settings) on remote side?

### ISSUE THREAD

**Issue by IvanLazarevsky** [ClickHouse/ClickHouse#42521]
While trying to copy part of a table to remote server, it fails with DB::Exception: Memory limit (for query) exceeded.

`insert into function remoteSecure(...) select * from a_table where (...)`

I have successfully copied some other tables and I would try to increase a memory limit, but I don't know how, when I use remoteSecure.

`DB::Exception: Received from  <REMOTE_HOST:PORT>. DB::Exception: Memory limit (for query) exceeded: would use 9.32 GiB (attempt to allocate chunk of 4357648 bytes), maximum: 9.31 GiB. OvercommitTracker decision: Memory overcommit isn't used. OvercommitTracker isn't set.. Stack trace:

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x78d627a in /usr/bin/clickhouse
1. ? @ 0x78c85f8 in /usr/bin/clickhouse
2. MemoryTracker::allocImpl(long, bool, MemoryTracker*) @ 0x78c80ef in /usr/bin/clickhouse
3. MemoryTracker::allocImpl(long, bool, MemoryTracker*) @ 0x78c7bc0 in /usr/bin/clickhouse
4. ? @ 0x7918475 in /usr/bin/clickhouse
5. DB::MergeTreeDataPartWriterOnDisk::Stream::Stream(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::IDataPartStorageBuilder> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::ICompressionCodec> const&, unsigned long, std::__1::shared_ptr<DB::ICompressionCodec> const&, unsigned long, DB::WriteSettings const&) @ 0x12b56692 in /usr/bin/clickhouse
6. ? @ 0x12b63e5e in /usr/bin/clickhouse
7. DB::ISerialization::enumerateStreams(DB::ISerialization::EnumerateStreamsSettings&, std::__1::function<void (DB::ISerialization::SubstreamPath const&)> const&, DB::ISerialization::SubstreamData const&) const @ 0x114cc910 in /usr/bin/clickhouse
8. DB::ISerialization::enumerateStreams(std::__1::function<void (DB::ISerialization::SubstreamPath const&)> const&, std::__1::shared_ptr<DB::IDataType const> const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn> const&) const @ 0x114ccc41 in /usr/bin/clickhouse
9. DB::MergeTreeDataPartWriterWide::addStreams(DB::NameAndTypePair const&, std::__1::shared_ptr<DB::IAST> const&) @ 0x12b5b027 in /usr/bin/clickhouse
10. DB::MergeTreeDataPartWriterWide::MergeTreeDataPartWriterWide(std::__1::shared_ptr<DB::IMergeTreeDataPart const> const&, std::__1::shared_ptr<DB::IDataPartStorageBuilder>, DB::NamesAndTypesList const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeIndex const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeIndex const> > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::ICompressionCodec> const&, DB::MergeTreeWriterSettings const&, DB::MergeTreeIndexGranularity const&) @ 0x12b5ae61 in /usr/bin/clickhouse
11. DB::MergeTreeDataPartWide::getWriter(std::__1::shared_ptr<DB::IDataPartStorageBuilder>, DB::NamesAndTypesList const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeIndex const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeIndex const> > > const&, std::__1::shared_ptr<DB::ICompressionCodec> const&, DB::MergeTreeWriterSettings const&, DB::MergeTreeIndexGranularity const&) const @ 0x12b48ec5 in /usr/bin/clickhouse
12. DB::MergedBlockOutputStream::MergedBlockOutputStream(std::__1::shared_ptr<DB::IMergeTreeDataPart const> const&, std::__1::shared_ptr<DB::IDataPartStorageBuilder>, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::NamesAndTypesList const&, std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeIndex const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeIndex const> > > const&, std::__1::shared_ptr<DB::ICompressionCodec>, std::__1::shared_ptr<DB::MergeTreeTransaction> const&, bool, bool, DB::WriteSettings const&) @ 0x12c46ea3 in /usr/bin/clickhouse
13. DB::MergeTreeDataWriter::writeTempPart(DB::BlockWithPartition&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::Context const>) @ 0x12c3f5df in /usr/bin/clickhouse
14. DB::MergeTreeSink::consume(DB::Chunk) @ 0x12d87289 in /usr/bin/clickhouse
15. DB::SinkToStorage::onConsume(DB::Chunk) @ 0x131f2f02 in /usr/bin/clickhouse
16. ? @ 0x1314b68b in /usr/bin/clickhouse
17. ? @ 0x1314b3d9 in /usr/bin/clickhouse
18. DB::ExceptionKeepingTransform::work() @ 0x1314acbf in /usr/bin/clickhouse
19. DB::ExecutionThreadContext::executeTask() @ 0x12f7b206 in /usr/bin/clickhouse
20. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x12f6f3dc in /usr/bin/clickhouse
21. DB::PipelineExecutor::executeStep(std::__1::atomic<bool>*) @ 0x12f6e068 in /usr/bin/clickhouse
22. DB::PushingPipelineExecutor::push(DB::Chunk) @ 0x12f82f86 in /usr/bin/clickhouse
23. DB::PushingPipelineExecutor::push(DB::Block) @ 0x12f831c6 in /usr/bin/clickhouse
24. DB::TCPHandler::processInsertQuery() @ 0x12f1490e in /usr/bin/clickhouse
25. DB::TCPHandler::runImpl() @ 0x12f0cbc3 in /usr/bin/clickhouse
26. DB::TCPHandler::run() @ 0x12f20839 in /usr/bin/clickhouse
27. Poco::Net::TCPServerConnection::start() @ 0x159b27af in /usr/bin/clickhouse
28. Poco::Net::TCPServerDispatcher::run() @ 0x159b4b3b in /usr/bin/clickhouse
29. Poco::PooledThread::run() @ 0x15b700d2 in /usr/bin/clickhouse
30. Poco::ThreadImpl::runnableEntry(void*) @ 0x15b6d85d in /usr/bin/clickhouse
31. ? @ 0x7fd04320e609 in ?
: Insertion status:
Wrote 4793 blocks and 885959089 rows on shard 0 replica 0, <REMOTE_HOST:PORT> (average 983 ms per block, the slowest block 1192 ms)
. Stack trace:

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x78d627a in /usr/bin/clickhouse
1. DB::readException(DB::ReadBuffer&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool) @ 0x792979e in /usr/bin/clickhouse
2. DB::Connection::receiveException() const @ 0x12df2985 in /usr/bin/clickhouse
3. DB::Connection::receivePacket() @ 0x12dfb021 in /usr/bin/clickhouse
4. DB::RemoteInserter::write(DB::Block) @ 0x129c6b8c in /usr/bin/clickhouse
5. ? @ 0x129dd7a1 in /usr/bin/clickhouse
6. DB::SinkToStorage::onConsume(DB::Chunk) @ 0x131f2f02 in /usr/bin/clickhouse
7. ? @ 0x1314b68b in /usr/bin/clickhouse
8. ? @ 0x1314b3d9 in /usr/bin/clickhouse
9. DB::ExceptionKeepingTransform::work() @ 0x1314acbf in /usr/bin/clickhouse
10. DB::ExecutionThreadContext::executeTask() @ 0x12f7b206 in /usr/bin/clickhouse
11. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x12f6f3dc in /usr/bin/clickhouse
12. DB::PipelineExecutor::executeStep(std::__1::atomic<bool>*) @ 0x12f6e068 in /usr/bin/clickhouse
13. DB::PushingPipelineExecutor::push(DB::Chunk) @ 0x12f82f86 in /usr/bin/clickhouse
14. DB::PushingPipelineExecutor::push(DB::Block) @ 0x12f831c6 in /usr/bin/clickhouse
15. ? @ 0x129dc05b in /usr/bin/clickhouse
16. ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >::worker(std::__1::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0x797c1ec in /usr/bin/clickhouse
17. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) @ 0x797ef17 in /usr/bin/clickhouse
18. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x797872c in /usr/bin/clickhouse
19. ? @ 0x797de3e in /usr/bin/clickhouse
20. ? @ 0x7fbe2e20e609 in ?
21. clone @ 0x7fbe2e133133 in ?`

**Comment by IvanLazarevsky** [comment]
Workaround for me was to create specific user on remote side with specific settings profile. But having the ability to set settings in remoteSecure and remote would be great

**Comment by alexey-milovidov** [comment]
1. In previous ClickHouse versions, there was a default memory limit for a query, set to 10 GB (9.31 GiB). In newer ClickHouse version, there is no default limit, and a query can use more memory if available.

2. It is possible to specify settings for INSERT SELECT - the settings will be pushed to the remote server. Example: `INSERT INTO FUNCTION remoteSecure(...) SELECT ... SETTINGS max_memory_usage = '20G'`
