### ISSUE TITLE
date_diff function returns incorrect results for minutes unit at the beginning of Unix epoch

### ISSUE THREAD

**Issue by rvasin** [ClickHouse/ClickHouse#42524]
**Describe what's wrong**
When server's time zone is not UTC and when one of two arguments of `dateDiff` function is `toDate('1970-01-01')` and first argument is `minutes` the function returns incorrect results. 

**Does it reproduce on recent release?**

Yes

**How to reproduce**
In config.xml set: `<timezone>Europe/Paris</timezone>`

```
SELECT dateDiff('minute', toDate('1970-01-01'), toDateTime('1970-01-02 00:00:00'));
-4294965856 - wrong, must be 1440

SELECT dateDiff('minute', toDateTime('1970-01-02 00:00:00'), toDate('1970-01-01'));
4294965856 - wrong, must be -1440

SELECT dateDiff('minute', toDate('1970-01-01'), toDateTime('1970-01-03 00:00:00'));
-4294964416 - wrong, must be 2880

SELECT dateDiff('minute', toDate('1970-01-02'), toDateTime('1970-01-03 00:00:00'));
1440 - OK

SELECT dateDiff('minute', toDate('1970-01-03'), toDateTime('1970-01-04 00:00:00'));
1440 - OK
```

**Comment by alexey-milovidov** [comment]
The `DateTime` data type supports time values starting from UNIX timestamp zero.
But 1970-01-01 00:00:00 in the time zones east to UTC happened before the UNIX epoch, and cannot be represented by the `DateTime` data type.

The negative Unix timestamp leads to implementation-defined overflow according to the docs.
