### ISSUE TITLE
Remove in-memory data parts

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#42542]
In-memory data parts implementation was unfinished, and now we need to get rid of it.
We can do it in the following steps:

1. Make the settings `min_rows_for_compact_part`, `min_bytes_for_compact_part` and `in_memory_parts_enable_wal` no-op.
In-memory data parts will be supported for reading but new in-memory parts will not be created.

2. Remove the write code path for in-memory parts. They will become read-only.

3. Remove all the code related to in-memory parts altogether.

**Comment by lqhl** [comment]
Why should we remove in-memory data parts? Isn't it benefitial for frequent small inserts?

**Comment by alexey-milovidov** [comment]
@lqhl According to the benchmarks, the benefit over compact parts is very small.

**Comment by alexey-milovidov** [comment]
We successfully removed in-memory data parts!
