### ISSUE TITLE
Incorrect elapsed time in JSON format result when a query has subqueries

### ISSUE THREAD

**Issue by nudles** [ClickHouse/ClickHouse#42555]
**Describe the unexpected behaviour**
The `elapsed` field from JSON format output is wrong (shorter) than the actual query execution time when the query has subqueries.

**How to reproduce**

Data: the hits dataset from clickbench.
Query:
```
SELECT SearchPhrase FROM (select SearchPhrase, URL, EventTime FROM hits WHERE CounterID = 62 AND EventDate >= '2013-07-01' AND EventDate <= '2013-07-31' AND DontCountHits = 0 AND IsRefresh = 0 AND URL <> '') WHERE URL LIKE '%google%' ORDER BY EventTime LIMIT 10 format JSON;
```

* Which ClickHouse server version to use
ClickHouse 22.10.1.1

* Which interface to use, if matters
Both http and tcp client.

**Expected behavior**
The time from the 'elapsed' field and that from `time` command or tcp client should be close.

**Error message and/or stacktrace**
via TCP client
![image](https://user-images.githubusercontent.com/3797447/197140453-6970f75f-85c4-403f-b317-f1906ebd404e.png)

via curl
![image](https://user-images.githubusercontent.com/3797447/197140637-aac7d509-ebb9-4ff2-bf01-12b3450e4348.png)

**Additional context**
* For HTTP requests, the cause looks like that JSONRowOutputFormat is created after the query pipeline has been created, which may take a while when there are subqueries. Consequently, the Stopwatch starts late and the measured time is then shorter.
* For TCP client, the reason could be that the JSONRowOutputFormat is created in the client after receiving the first block, which again is later than the query submission time.

**Comment by Algunenano** [comment]
I think it'd make sense to unify how the time is measured. There are currently 3 or 4 different places measuring time in the server side and they are not consistent.

I'm looking into pushing the proper time to the right watches to unify the reported time. It might still be slightly inconsistent since the JSON will be written before the technical end of the query (I think) but it should be much closer.

**Comment by Algunenano** [comment]
A simple reproducer:

```
WITH (
        SELECT sleepEachRow(1)
    ) AS sub
SELECT *
FROM
(
    SELECT *
    FROM table
)
FORMAT JSON
SETTINGS enable_global_with_statement = 1

Query id: a4db10cb-e53f-43a3-8d52-5df4d19bd478

{
        "meta":
        [
                {
                        "name": "a",
                        "type": "Int64"
                }
        ],

        "data":
        [

        ],

        "rows": 0,

        "statistics":
        {
                "elapsed": 0.000236309, <<<<<<<<<<<
                "rows_read": 1,
                "bytes_read": 1
        }
}
Ok.

0 rows in set. Elapsed: 1.002 sec.  <<<<<<<<<<<<<
```

**Comment by Algunenano** [comment]
Some notes after looking at this:
* The current approach to measuring time is very chaotic. There are a lot of places using their own watches and each one starts at a different point in the lifetime of a query.
* The start time is being ignored on some exceptions (like ExceptionBeforeStart), so you don't know how much time was spent in the query before it failed.
* The query start time might be set by the client
* The start time for the query log and the start time for the format output (like for JSON) are different.
* The time in the format output for the client is controlled by the client :upside_down_face:
* IOutputFormat has an `statistics` field which is a `std::shared_ptr<Statistics>`.`JSONRowOutputFormat` and other output formats that inherit from this class redeclare and redefine the statistics as `Statistics statistics;`.
* Parallel outputs and serial outputs are processed differently too.

So while grouping things seems possible, the chance of breaking things in the process is well over 9000. I'll try to send a PR to see what happens, but I'm fearing a never-ending PR with lots of rebase's and changes.

**Comment by Algunenano** [comment]
I've made a proposal to unify this at https://github.com/ClickHouse/ClickHouse/pull/43455. If you have any queries that could be used to test this (against master and against this PR) please let me know, so we can confirm that this change fixes your use case too (both via HTTP and the TCP client).

**Comment by nudles** [comment]
Thanks @Algunenano ! I added one comment under your PR.
