### ISSUE TITLE
Passing generated value to quantiles?

### ISSUE THREAD

**Issue by MockingMagician** [ClickHouse/ClickHouse#42578]
Hello clickhouse community,

I don't really know if it is possible to do this kind of thing, but let me explain:

I have a query like this:

```sql
select quantiles(0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95)(price)
from price
```
Is it possible to pass the generated value to quantiles? And if so, what does it look like? I would like to get something like :

```sql
select quantiles(/* list of generated quantiles, maybe with select something */)(price)
from price
```

Thanks for any kind of response approuving or desapprouving the possibility of doing it.

**Comment by CamiloSierraH** [comment]
Hi @MockingMagician ,

The quantiles `level` parameter has some kind of mixed type, is not a string neither an array, so this makes not possible to use a select to get the values as required in your example.
A workaround is use the clickhouse-client and some external command or code that will generate the list, here an example that will work in a bash script:
```
clickhouse-client --query "select quantiles($(seq -s "," 0 .05 .95))(price) FROM price;"
```

**Comment by MockingMagician** [comment]
Hi @CamiloSierraH,

Thanks a lot for your feedback... I was almost sure about the fact that you can not pass any kind of sub request as parameter to quantiles functions...

But thanks a lot for your idea of generated quantiles values, I've implemented something that looks as your idea, but I hope one day will could do it without leaving the `request scope` :smiling_face_with_tear: 

See you
