### ISSUE TITLE
s3 disk do not have cache directory

### ISSUE THREAD

**Issue by zdyj3170101136** [ClickHouse/ClickHouse#42584]
#### version
22.9.2
#### problem
i am using s3 as cold disk, it work great, except it do not have cache directory.

here is my s3 storage setting:
```
<cold_disk_s3>
                <type>s3</type>
                <endpoint></endpoint>
                <access_key_id></access_key_id>
                <secret_access_key></secret_access_key>
                <region>ap-southeast-1</region>
                <connect_timeout_ms>10000</connect_timeout_ms>
                <request_timeout_ms>5000</request_timeout_ms>
                <retry_attempts>10</retry_attempts>
                <single_read_retries>4</single_read_retries>
                <min_bytes_for_seek>1000</min_bytes_for_seek>
                <metadata_path>/home/data/clickhouse/disks/s3/</metadata_path>
                <cache_enabled>true</cache_enabled>
                <cache_path>/home/data/clickhouse/disks/s3/cache/</cache_path>
                <skip_access_check>false</skip_access_check>
</cold_disk_s3>
```
it only have store file:
```
[root@plat-sg03-infra-prod-jaeger-clickhouse005 s3]# pwd
/home/data/clickhouse/disks/s3
[root@plat-sg03-infra-prod-jaeger-clickhouse005 s3]# ls -lf
.  ..  store
[root@plat-sg03-infra-prod-jaeger-clickhouse005 s3]#
```

**Comment by xiedeyantu** [comment]
change config like this:

`<storage_configuration>
        <disks>
            <s3>
                <type>s3</type>
                <endpoint>http://minio1:9001/root/data/</endpoint>
                <access_key_id>minio</access_key_id>
                <secret_access_key>minio123</secret_access_key>
            </s3>
            <s3_cache>
                <type>cache</type>
                <disk>s3</disk>
                <path>./s3_cache/</path>
                <max_size>1000000</max_size>
            </s3_cache>
        </disks>
        <policies>
            <s3>
                <volumes>
                    <main>
                        <disk>s3</disk>
                    </main>
                </volumes>
            </s3>
            <s3_cache>
                <volumes>
                    <main>
                        <disk>s3_cache</disk>
                    </main>
                </volumes>
            </s3_cache>
        </policies>
    </storage_configuration>`

**Comment by zdyj3170101136** [comment]
> change config like this:
> 
> ```
> <storage_configuration>
>         <disks>
>             <s3>
>                 <type>s3</type>
>                 <endpoint>http://minio1:9001/root/data/</endpoint>
>                 <access_key_id>minio</access_key_id>
>                 <secret_access_key>minio123</secret_access_key>
>             </s3>
>             <s3_cache>
>                 <type>cache</type>
>                 <disk>s3</disk>
>                 <path>./s3_cache/</path>
>                 <max_size>1000000</max_size>
>             </s3_cache>
>         </disks>
>         <policies>
>             <s3>
>                 <volumes>
>                     <main>
>                         <disk>s3</disk>
>                     </main>
>                 </volumes>
>             </s3>
>             <s3_cache>
>                 <volumes>
>                     <main>
>                         <disk>s3_cache</disk>
>                     </main>
>                 </volumes>
>             </s3_cache>
>         </policies>
>     </storage_configuration>
> ```

it work!

may be you should modify clickhouse doc about mergetree.
the old configuration is copy from that.

**Comment by xiedeyantu** [comment]
configuration link here https://clickhouse.com/docs/en/operations/storing-data/#using-local-cache
