### ISSUE TITLE
Degrading  performance queries of type select when updating CH version to 22.8 LTS

### ISSUE THREAD

**Issue by i1l-ba** [ClickHouse/ClickHouse#42596]
We have a cluster consisting of 6 shards and a Distributed Table on which select queries are launched, after updating the version from 23 to 28, we got a degradation in the performance of queries(SELECT) on this table
average time of duration increase from 500ms to 2 seconds

When we show trace log, find very waiting of pthread_cond_wait()
Maybe we forgot new parameters of CH version 22.8 ?

**after 12.10.2022**

<img width="444" alt="image" src="https://user-images.githubusercontent.com/98915297/197392336-80220271-1905-4a13-9f5b-56ae1f429aae.png">

**average time**

<img width="416" alt="image" src="https://user-images.githubusercontent.com/98915297/197392396-96a1da04-86ec-4c1f-ace6-7338fe98ee10.png">

*Threads*

```
─name────────────┬─count()─┐
│ ThreadPool      │     928 │
│ TCPHandler      │     342 │
│ Fetch           │     200 │
│ MergeMutate     │     150 │
│ BgSchPool       │     150 │
│ QueryPipelineEx │      83 │
│ IntersrvHandler │      36 │
│ Common          │       8 │
│ Move            │       8 │
│ clickhouse-serv │       7 │
│ ThreadPoolRead  │       5 │
│ SystemLogFlush  │       5 │
│ QueryPullPipeEx │       3 │
│ ExterLdrReload  │       3 │
│ ConfigReloader  │       2 │
│ ZooKeeperRecv   │       1 │
│ TraceCollector  │       1 │
│ SessionCleaner  │       1 │
│ DDLWorker       │       1 │
│ HTTPHandler     │       1 │
│ DDLWorkerClnr   │       1 │
│ ZooKeeperSend   │       1 │
│ AsyncMetrics    │       1 │
│ BgSchPool/D     │       1 │
└─────────────────┴─────────┘

Totals:
┌─name─┬─count()─┐
│      │    1939 │
└──────┴─────────┘

```
```
┌─name──────────────────────────────┬─value──────┐
│ Query                             │ 1          │
│ CompiledFunctionExecute           │ 1          │
│ CompiledFunctionExecute           │ 1          │
│ SelectQuery                       │ 1          │
│ SelectQuery                       │ 1          │
│ Query                             │ 1          │
│ IOBufferAllocs                    │ 10         │
│ IOBufferAllocs                    │ 10         │
│ SelectedBytes                     │ 103.00 GiB │
│ SelectedBytes                     │ 103.00 GiB │
│ OSCPUWaitMicroseconds             │ 10984      │
│ OSCPUWaitMicroseconds             │ 10984      │
│ ArenaAllocBytes                   │ 112.00 KiB │
│ ArenaAllocBytes                   │ 112.00 KiB │
│ OSWriteChars                      │ 118.79 KiB │
│ OSWriteChars                      │ 118.79 KiB │
│ CompressedReadBufferBlocks        │ 13         │
│ CompressedReadBufferBlocks        │ 13         │
│ NetworkSendBytes                  │ 13.61 KiB  │
│ NetworkSendBytes                  │ 13.61 KiB  │
│ SelectedRows                      │ 1337014193 │
│ SelectedRows                      │ 1337014193 │
│ SystemTimeMicroseconds            │ 150477     │
│ SystemTimeMicroseconds            │ 150477     │
│ OSReadChars                       │ 266.86 KiB │
│ OSReadChars                       │ 266.86 KiB │
│ SoftPageFaults                    │ 28         │
│ ArenaAllocChunks                  │ 28         │
│ SoftPageFaults                    │ 28         │
│ ArenaAllocChunks                  │ 28         │
│ UserTimeMicroseconds              │ 294407     │
│ UserTimeMicroseconds              │ 294407     │
│ SelectQueryTimeMicroseconds       │ 30116312   │
│ QueryTimeMicroseconds             │ 30116312   │
│ ReadCompressedBytes               │ 31.50 KiB  │
│ ReadCompressedBytes               │ 31.50 KiB  │
│ FunctionExecute                   │ 33         │
│ FunctionExecute                   │ 33         │
│ NetworkReceiveElapsedMicroseconds │ 38825      │
│ NetworkReceiveElapsedMicroseconds │ 38825      │
│ RWLockAcquiredReadLocks           │ 4          │
│ RWLockAcquiredReadLocks           │ 4          │
│ OSWriteBytes                      │ 4.00 KiB   │
│ OSWriteBytes                      │ 4.00 KiB   │
│ OSCPUVirtualTimeMicroseconds      │ 444576     │
│ OSCPUVirtualTimeMicroseconds      │ 444576     │
│ IOBufferAllocBytes                │ 5.02 MiB   │
│ IOBufferAllocBytes                │ 5.02 MiB   │
│ CompressedReadBufferBytes         │ 52.98 KiB  │
│ CompressedReadBufferBytes         │ 52.98 KiB  │
│ ContextLock                       │ 67         │
│ ContextLock                       │ 69         │
│ NetworkSendElapsedMicroseconds    │ 7936       │
│ NetworkSendElapsedMicroseconds    │ 8059       │
│ NetworkReceiveBytes               │ 9.50 MiB   │
│ NetworkReceiveBytes               │ 9.50 MiB   │
│ QueryProfilerRuns                 │ 900        │
│ QueryProfilerRuns                 │ 900        │
│ RealTimeMicroseconds              │ 901730342  │
│ RealTimeMicroseconds              │ 901730342  │
└───────────────────────────────────┴────────────┘
```
*Plan of slow query*

```
┌─explain─────────────────────────────────────────────────┐
│ (Expression)                                            │
│ ExpressionTransform × 2                                 │
│   (Sorting)                                             │
│   MergeSortingTransform                                 │
│     LimitsCheckingTransform                             │
│       PartialSortingTransform                           │
│         (Expression)                                    │
│         ExpressionTransform × 2                         │
│           (TotalsHaving)                                │
│           TotalsHavingTransform 1 → 2                   │
│             Resize 28 → 1                               │
│               (MergingAggregated)                       │
│               Resize 1 → 28                             │
│                 SortingAggregatedTransform 28 → 1       │
│                   MergingAggregatedBucketTransform × 28 │
│                     Resize 1 → 28                       │
│                       GroupingAggregatedTransform 6 → 1 │
│                         (Union)                         │
│                           (Aggregating)                 │
│                           AggregatingTransform          │
│                             (Expression)                │
│                             ExpressionTransform         │
│                               (Filter)                  │
│                               FilterTransform           │
│                                 (ReadFromMergeTree)     │
│                           (ReadFromRemote)              │
└─────────────────────────────────────────────────────────┘
```
![allocs](https://user-images.githubusercontent.com/98915297/197392908-16cc07ae-b12b-4d14-9d72-ad992c3de28d.svg)
![allocs1](https://user-images.githubusercontent.com/98915297/197392912-e938954d-4e16-4c1c-ad3f-7d9d67947847.svg)
![allocs2](https://user-images.githubusercontent.com/98915297/197392914-ddc3bad8-d88b-43ea-aa59-66e9d0ced12b.svg)
![allocs3](https://user-images.githubusercontent.com/98915297/197392916-b3b7056c-92fe-49ab-bccc-43ac87d3e488.svg)

**Comment by cangyin** [comment]
the 'longest' `pthread_cond_wait` call may be the code the waits for exit signal.

https://github.com/ClickHouse/ClickHouse/blob/c0d1be9caba894a86900adaeaea8ad96e110bd73/programs/server/Server.cpp#L1847

Where `waitForTerminationRequest()` waits for exit signal forever.

https://github.com/ClickHouse/ClickHouse/blob/c0d1be9caba894a86900adaeaea8ad96e110bd73/src/Daemon/BaseDaemon.cpp#L968-L973

**Comment by nickitat** [comment]
pls check if setting `local_filesystem_read_method` have the same value and try to run your query with 
`... settings compatibility = '22.3'`

**Comment by i1l-ba** [comment]
@nickitat thank you, we check local_filesystem_read_method, parameter became the default now pread_threadpool
back in pread and all select accelerated by 10 times

our settings linux kernel
5.4.0-70-generic #78~18.04.1-Ubuntu
QEMU emulator version 2.11.1, 
servers are 10 HP gen


<img width="439" alt="image" src="https://user-images.githubusercontent.com/98915297/197510929-41ffa443-d876-4b82-b748-ef02815ffb81.png">

**Comment by nickitat** [comment]
you run on HDD? do you have raid configured? maybe storage configuration is not optimal, the only thing I could recommend is to take a look into our [docs](https://clickhouse.com/docs/en/operations/tips#storage-subsystem)

**Comment by i1l-ba** [comment]
no, you have only ssd and don't have raid for this cluster(only big system, raid10,raid50)
for this cluster have jbod
 vvvda    252:16   0    7T  0 disk /jbod0
vvvdb    252:32   0    7T  0 disk /jbod1
vvvdc    252:48   0    7T  0 disk /jbod2
vvvdd    252:64   0    7T  0 disk /jbod3
vvvdf    252:80   0    7T  0 disk /jbod4
vvvdg    252:96   0    7T  0 disk /jbod5

**Comment by cangyin** [comment]
How will the `local_filesystem_read_method` affects read performance, Is the `pread_threadpool` read method optimized for SSD or HDD ?

**Comment by nickitat** [comment]
> How will the `local_filesystem_read_method` affect read performance, Is the `pread_threadpool` read method optimized for SSD or HDD ?

it is just the mechanics of this two different devices. hdd is sequential and needs to physically rotate its head. so the default for hdd is sync methods (like `pread`) and reading from a single thread.
if you're interested in the subject I can recommend this article: https://arxiv.org/pdf/2102.11198.pdf

**Comment by cangyin** [comment]
Thanks!
