### ISSUE TITLE
22.9.*: Use toDate function parser error

### ISSUE THREAD

**Issue by CuiYanxiang** [ClickHouse/ClickHouse#42608]
### ClickHouse version 22.9.4.1
When I execute a small query:

> select toRelativeDayNum(toDate(1666368000000/1000)),toRelativeDayNum(toDate('2022-10-22'));

Error message
Query id: 6dfds4ff8-e2ca-ds8f-fs8a-d324d9b15daw

┌─toRelativeDayNum(toDate(divide(1666368000000, 1000)))─┬─toRelativeDayNum(toDate('2022-10-22'))─┐
│                                                 65535 │                                  19287 │
└───────────────────────────────────────────────────────┴────────────────────────────────────────┘

1 rows in set. Elapsed: 0.002 sec.

### Expected behavior
ClickHouse client version 22.3.6.5.

SELECT toRelativeDayNum(toDate(1666368000000 / 1000)), toRelativeDayNum(toDate('2022-10-22'))

Query id: 6df854f4-e2ca-49b1-af00-d324d9b15cae

┌─toRelativeDayNum(toDate(divide(1666368000000, 1000)))─┬─toRelativeDayNum(toDate('2022-10-22'))─┐
│                                                 19287 │                                  19287 │
└───────────────────────────────────────────────────────┴────────────────────────────────────────┘

1 rows in set. Elapsed: 0.002 sec.

**Comment by rschu1ze** [comment]
All 22.9.* versions are affected. ClickHouse <= v22.8.* and current HEAD (22.10) work as expected.

**Comment by rschu1ze** [comment]
On 22.9:

```sql
select toDateTime64(toDate(1666368000000/1000), 3),toDateTime64(toDate('2022-10-22'), 3);
```

returns `2106-02-07 06:28:15.000	     2022-10-22 00:00:00.000`. So basically, the float-to-date parsing is broken.

**Comment by rschu1ze** [comment]
Dup of #42520.
