### ISSUE TITLE
how should I use toYYYYMMDD function in partition by expression

### ISSUE THREAD

**Issue by vasonyang** [ClickHouse/ClickHouse#42636]
Clickhouse server version: 21.12.3.32
a column createTime value is 1665851614897
createTime/1000 result is 1665851614.897
toDateTime(createTime / 1000) result is 2022-10-16 00:33:34.000
but toYYYYMMDD(toDateTime(createTime / 1000)) result is 20221015

select 1665851614897 as createTime, 1665851614897/1000, toDateTime(1665851614897 / 1000), toYYYYMMDD(toDateTime(1665851614897 / 1000))

toYYYYMMDD takes internal representation of DateTime in UTC timezone  and prints its date, should I specify other timezone in toYYYYMMDD? like this `toYYYYMMDD(toDateTime(createTime / 1000), 'Asia/Singapore')` ?

if I use toYYYYMMDD function in partition by expression , how should I use it ? if I don't specify the timezone , the data whose createTime value is 1665851614897 will be assigned to unexpected partition.

**Comment by CamiloSierraH** [comment]
Hi @vasonyang ,
>toYYYYMMDD takes internal representation of DateTime in UTC timezone and prints its date

It's not the function `toYYYYMMDD` that takes an UTC representation, but how timestamps works, their value is always in UTC.

>toYYYYMMDD(toDateTime(createTime / 1000), 'Asia/Singapore')

`toYYYYMMDD` do not have a timezone parameter as only receive a timestamp.
 
But you can transform your `date + timezone` to a timestamp. for that you can use the `toDateTime` function, it will change just a little bit compare to your main idea, it will be like this: 
```
toYYYYMMDD(toDateTime(1665851614897 / 1000, 'Asia/Singapore'))
```
