### ISSUE TITLE
Temporary remove Azure Blob Storage support, because a test has failed.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#42638]
See https://github.com/Azure/azure-sdk-for-cpp/issues/4047

Note: there is no intent to remove the Azure Blob Storage support from ClickHouse.
But after upgrading to LLVM-15, it starts to complain about this issue, and we need to eliminate it to simply move forward.

**Comment by azat** [comment]
Duplicate of #42638, will close referenced issue then.

**Comment by alexey-milovidov** [comment]
@azat by the way, I did not check the code.
Maybe we simply need to update the Azure SDK?
Maybe we are using it in the wrong way?

**Comment by azat** [comment]
> I did not check the code.

Me neither

**Comment by alexey-milovidov** [comment]
Memory leak in XML parsing: https://github.com/ClickHouse/ClickHouse/issues/41104

**Comment by alexey-milovidov** [comment]
Flaky test: https://github.com/ClickHouse/ClickHouse/issues/39700

**Comment by alexey-milovidov** [comment]
@jkuklis just to clarify - we don't want to remove it,
we just need to address these failed checks... and before it will happen, we can just temporarily remove it.

**Comment by KochetovNicolai** [comment]
Another one thread leak
https://s3.amazonaws.com/clickhouse-test-reports/42681/f04f6638189bd4a0f9c9defdb43c66b3e8c5ef37/stress_test__tsan_/stderr.log

**Comment by Algunenano** [comment]
This keeps hitting the CI multiple times daily. I'm not sure if dropping it temporarily is the best option, but it seems like a valid option.

**Comment by alexey-milovidov** [comment]
Unfortunately, the "thread leak" also appeared in HDFS.
And it is not necessarily a leak as we can terminate the application with `syscall(SYS_exit...`

**Comment by alexey-milovidov** [comment]
`sudo DEBIAN_FRONTEND=noninteractive ./clickhouse install`
