### ISSUE TITLE
Half of time spent on destruction of AggregatedDataVariants

### ISSUE THREAD

**Issue by Alex-Cheng** [ClickHouse/ClickHouse#42661]
(you don't have to strictly follow this form)

**Describe the situation**
When do aggregation on big data, approximately 100M rows, the half time is spent on destruction of AggregatedDataVariants, that seems to be a big perfomance hit.

**How to reproduce**
* Which ClickHouse server version to use
22.8.5.1.208
* Which interface to use, if matters
clickhouse-client
* Non-default settings, if any

* `CREATE TABLE` statements for all tables involved
```
create table t1 engine=MergeTree order by value as select number as value from numbers(300000000);
select count(distinct value) from t1 group by toInt64(value / 10);
```

After first 1000 rows of results are shown, a few of seconds are spent for destruction.

**Expected performance**
Hope the destruction of AggregatedDataVariants costs fewer time.

**Additional context**

**Comment by nickitat** [comment]
why do you think so? first 10K result rows become available in the very beginning of merging phase, as soon as first bucket is merged. but then merging continues for other 255 buckets and takes the rest of the time.

recently we [optimised destruction](https://github.com/ClickHouse/ClickHouse/pull/37855) of aggregation states and the described scenario seems to be the only one when it actually was single-threaded:

https://github.com/ClickHouse/ClickHouse/blob/2487ba7f0006f1f020f90424aff727de57397d65/src/Processors/Transforms/AggregatingTransform.h#L82-L84
