### ISSUE TITLE
Clickhouse-keeper logical error after hardware crash

### ISSUE THREAD

**Issue by yersinkakimishev** [ClickHouse/ClickHouse#42668]
After hardware failure we faced problem with clickhouse-server and clickhouse-keeper startup. Cluster consists of 6 VMs. 3 shards with 2 replicas and 6 clickhouse-keeper. 

Clickhouse version: ClickHouse server version 22.7.2.15 (official build)
  
Clickhouse-keeper on node5 was the last leader. At startup this node has leader role but initializing fails because of logs below. 
Also tried to run clickhouse-keeper with --force-recovery key.

Do not. know how to reproduce it. 

clickhouse_keeper.xml
`<?xml version="1.0"?>
 
<yandex>
    <keeper_server>
        <tcp_port>2181</tcp_port>
        <server_id>5</server_id>
        <log_storage_path>/var/log/clickhouse-server/coordination/log</log_storage_path>
        <snapshot_storage_path>/db/clickhouse/clickhouse/coordination/snapshots</snapshot_storage_path>
	<socket_receive_timeout_sec>40000</socket_receive_timeout_sec>
	<socket_send_timeout_sec>40000</socket_send_timeout_sec>

        <coordination_settings>
            <operation_timeout_ms>10000</operation_timeout_ms>
            <session_timeout_ms>30000</session_timeout_ms>
            <raft_logs_level>trace</raft_logs_level>
        </coordination_settings>

        <raft_configuration>
            <server>
                <id>1</id>
                <hostname>node1</hostname>
                <port>9444</port>
            </server>
            <server>
                <id>2</id>
                <hostname>node2</hostname>
                <port>9444</port>
            </server>
            <server>
                <id>3</id>
                <hostname>node3</hostname>
                <port>9444</port>
            </server>
            <server>
                <id>4</id>
                <hostname>node4</hostname>
                <port>9444</port>
            </server>
            <server>
                <id>5</id>
                <hostname>node5</hostname>
                <port>9444</port>
            </server>
            <server>
                <id>6</id>
                <hostname>node6</hostname>
                <port>9444</port>
            </server>
        </raft_configuration>
    </keeper_server>
</yandex>`

`
2022.10.26 05:34:19.148136 [ 201888 ] {} <Error> void DB::KeeperDispatcher::initialize(const Poco::Util::AbstractConfiguration &, bool, bool): Code: 49. DB::Exception: Got new ZXID (2732095866) smaller or equal to current ZXID (2732096266). It's a bug. (LOGICAL_ERROR), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xba37dda in /usr/bin/clickhouse
1. DB::Exception::Exception<long&, long&>(int, fmt::v8::basic_format_string<char, fmt::v8::type_identity<long&>::type, fmt::v8::type_identity<long&>::type>, long&, long&) @ 0xbaa330c in /usr/bin/clickhouse
2. DB::KeeperStorage::preprocessRequest(std::__1::shared_ptr<Coordination::ZooKeeperRequest> const&, long, long, long, bool, std::__1::optional<DB::KeeperStorage::Digest>) @ 0x17fe7f96 in /usr/bin/clickhouse
3. DB::KeeperStateMachine::preprocess(DB::KeeperStorage::RequestForSession const&) @ 0x17fc920e in /usr/bin/clickhouse
4. DB::KeeperStateMachine::pre_commit(unsigned long, nuraft::buffer&) @ 0x17fc8e74 in /usr/bin/clickhouse
5. DB::KeeperServer::startup(Poco::Util::AbstractConfiguration const&, bool) @ 0x17f99417 in /usr/bin/clickhouse
6. DB::KeeperDispatcher::initialize(Poco::Util::AbstractConfiguration const&, bool, bool) @ 0x17f8445d in /usr/bin/clickhouse
7. DB::Context::initializeKeeperDispatcher(bool) const @ 0x1661a125 in /usr/bin/clickhouse
8. DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0xbadf9c4 in /usr/bin/clickhouse
9. Poco::Util::Application::run() @ 0x1a9a3406 in /usr/bin/clickhouse
10. DB::Server::run() @ 0xbad0d9e in /usr/bin/clickhouse
11. mainEntryClickHouseServer(int, char**) @ 0xbace39d in /usr/bin/clickhouse
12. main @ 0xba31279 in /usr/bin/clickhouse
13. ? @ 0x7fd2b6ebad90 in ?
14. __libc_start_main @ 0x7fd2b6ebae40 in ?
15. _start @ 0xb7f18ae in /usr/bin/clickhouse
 (version 22.7.2.15 (official build))
2022.10.26 05:34:19.633059 [ 201888 ] {} <Error> Application: DB::Exception: Got new ZXID (2732095866) smaller or equal to current ZXID (2732096266). It's a bug
2022.10.26 05:34:50.151730 [ 201904 ] {} <Warning> Context: Linux is not using a fast TSC clock source. Performance can be degraded. Check /sys/devices/system/clocksource/clocksource0/current_clocksource
`

`2022.10.25 23:55:53.665261 [ 199560 ] {} <Fatal> BaseDaemon: ########################################
2022.10.25 23:55:53.665384 [ 199560 ] {} <Fatal> BaseDaemon: (version 22.7.2.15 (official build), build id: A975FB2E13DEF38A) (from thread 199549) (no query) Received signal Aborted (6)
2022.10.25 23:55:53.665506 [ 199560 ] {} <Fatal> BaseDaemon: 
2022.10.25 23:55:53.665586 [ 199560 ] {} <Fatal> BaseDaemon: Stack trace: 0x7ffbafeb9a7c 0x7ffbafe65476 0x7ffbafe4b7f3 0x17fd5526 0x1a80b04b 0x1a8050ce 0x7ffbafeb7b43 0x7ffbaff49a00
2022.10.25 23:55:53.665824 [ 199560 ] {} <Fatal> BaseDaemon: 2. pthread_kill @ 0x7ffbafeb9a7c in ?
2022.10.25 23:55:53.665890 [ 199560 ] {} <Fatal> BaseDaemon: 3. gsignal @ 0x7ffbafe65476 in ?
2022.10.25 23:55:53.665947 [ 199560 ] {} <Fatal> BaseDaemon: 4. abort @ 0x7ffbafe4b7f3 in ?
2022.10.25 23:55:53.666066 [ 199560 ] {} <Fatal> BaseDaemon: 5. ? @ 0x17fd5526 in /usr/bin/clickhouse
2022.10.25 23:55:53.666204 [ 199560 ] {} <Fatal> BaseDaemon: 6. nuraft::raft_server::commit_in_bg() @ 0x1a80b04b in /usr/bin/clickhouse
2022.10.25 23:55:53.666256 [ 199560 ] {} <Fatal> BaseDaemon: 7. ? @ 0x1a8050ce in /usr/bin/clickhouse
2022.10.25 23:55:53.666345 [ 199560 ] {} <Fatal> BaseDaemon: 8. ? @ 0x7ffbafeb7b43 in ?
2022.10.25 23:55:53.666390 [ 199560 ] {} <Fatal> BaseDaemon: 9. ? @ 0x7ffbaff49a00 in ?
2022.10.25 23:55:54.071443 [ 199560 ] {} <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: 9801BC3908CB6E73893664D8990BD5D1)
`

**Comment by antonio2368** [comment]
Are other nodes functioning correctly?
This check can fail if there are some inconsistencies with stored logs, somehow you ended up with such an inconsistent state.
Did you maybe upgrade CH Keeper in meantime?

**Comment by yersinkakimishev** [comment]
@antonio2368 there wasn't upgrade. Because of RAFT failures ClickHouse cluster can't start

**Comment by antonio2368** [comment]
And other nodes have the same error?
You need 3 nodes for cluster to start

**Comment by yersinkakimishev** [comment]
Each node had the same error. 
Found node with highest ZXID and started in recovery mode. Then started the rest of nodes one by one. Cluster started successfully

**Comment by antonio2368** [comment]
Good to hear that.
