### ISSUE TITLE
Unknown column 'DATETIME_PRECISION' when try to select from mysql

### ISSUE THREAD

**Issue by alexsubota** [ClickHouse/ClickHouse#42671]
CH: 22.8.6.71
MySql: 5.5.58-0+deb8u1-log

When i try to select data from mysql table:
`select id from mysql('.....');`
Get an error
`Poco::Exception. Code: 1000, e.code() = 1054, mysqlxx::BadQuery: Unknown column 'DATETIME_PRECISION' in 'field list'`

**Comment by alexey-milovidov** [comment]
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/21335
