### ISSUE TITLE
Add system.dns_cache table

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#42690]
**Use case**

For testing and debug purposes to be able to see internal data structures.

**Describe the solution you'd like**

- To see at least `hostname`, `ipv4` or `ipv6`.
- Additionally can be useful to have time of resolution and when record will expire.

**Comment by dentiscalprum** [comment]
Hi, may I have a try on this ?

Thank you !

**Comment by dentiscalprum** [comment]
Hi, may I have a try on this?
Thank you !

**Comment by qoega** [comment]
Sure!

**Comment by KochetovNicolai** [comment]
@pykello will be working on this task.

**Comment by pufit** [comment]
@allmazz wants to try this task
