### ISSUE TITLE
After upgrade ClickHouse  to 22.7, use transaction to insert data to ReplicatedMergeTree Engine table，throw an exception.

### ISSUE THREAD

**Issue by hantaoliulinux** [ClickHouse/ClickHouse#42703]
```
CREATE TABLE default.test107 on cluster default_cluster
(
    `when` DateTime,
    `CounterID` UInt32,
    `UserID` UInt32,
    `UserID2` UInt32

)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/default/test107', '{replica}')
PARTITION BY toYYYYMMDD(when)
ORDER BY (when, intHash32(UserID))
SETTINGS index_granularity = 8192;

BEGIN TRANSACTION;
insert into default.test107 select now() - number as when,rand(),number,rand64() from numbers(2);
```

When I tried to insert data, the client showed an exception. Insertion failed
**The exception information is as follows:**
DB::Exception: CreationTID of part 20221026_0_0_0 (table default.test107 (a6829b96-a07b-441a-a928-5de3bf9c73c7)) is set to unexpected value (36, 34, 259b9bef-a594-4860-b003-8c064574e75f), it's a bug. Current transaction: <none>_

By looking at the code, I feel that this is a bug.
Because the source code goes to the point where the parameter is passed ： renamed = storage.renameTempPartAndAdd(part, NO_TRANSACTION_RAW, nullptr, &transaction);  NO_TRANSACTION_RAW is initial Value, exceptions must be thrown because they are not equal.

Does replicatedMergeTree table support transactions？

**Comment by hantaoliulinux** [comment]
@tavplubix

**Comment by Algunenano** [comment]
Transactions aren't implemented for replicated tables yet.

**Comment by hantaoliulinux** [comment]
> Transactions aren't implemented for replicated tables yet.

Thank you. When will be able to support replicated tables? Is there a plan for this?

**Comment by tavplubix** [comment]
> When will be able to support replicated tables?

Someday.

**Comment by tavplubix** [comment]
But it should never throw logical error
