### ISSUE TITLE
CORS header missing for HTTP error responses 

### ISSUE THREAD

**Issue by santrancisco** [ClickHouse/ClickHouse#42723]
**Describe what's wrong**

In normal circumstances, HTTP Endpoint respond with 200 Ok and include all the headers specified in config.xml. However, when there is an error (for example, 403 error)

**Does it reproduce on recent release?**

Yes

**How to reproduce**

* Configure config.xml with Access-Control-Allow-Origin header as per clickhouse documentation
* Send a request with valid credential - observe the above header shown in 200Ok response
* Send another request with invalid credential - observe the above header NOT included in the 403 response

Screenshot: (left is response from valid credential with the right header included)
![CleanShot 2022-10-27 at 11 28 15@2x](https://user-images.githubusercontent.com/3240146/198163678-b3171b95-d736-484a-8bc7-acba4ca92338.png)

**Expected behavior**

In both cases, the HTTP response should include the header. This is because any 3rd party browser app that connects to the database (eg SQL editor or for graphing data), can access the HTTP status code from the response without throwing a CORS issue. 

**Error message and/or stacktrace**

CORS issue in browser.

**Comment by FrankChen021** [comment]
I resolved it: https://github.com/ClickHouse/ClickHouse/pull/41792

**Comment by santrancisco** [comment]
Thanks @FrankChen021! That is exactly the fix we needed.
