### ISSUE TITLE
groupArray fails in 22.10.1 due to Nullable-type even if no Nullable is used

### ISSUE THREAD

**Issue by inkrement** [ClickHouse/ClickHouse#42735]
Since the upgrade to 22.10.1 (from 22.9) I experienced a strange bug that did not happen before. In particular, I cannot group Cells together. The query always fails with an ILLEGAL_TYPE_OF_ARGUMENT exception. 

```sql
SELECT groupArray(arrayJoin(['a']))
```

Expected behavior: 
```
['a']
```

error:
```
DB::Exception: Nested type Array(String) cannot be inside Nullable type. (ILLEGAL_TYPE_OF_ARGUMENT)
```

This is even true when I explicitly declare it as not-null:

```sql
SELECT groupArray(arrayJoin(assumeNotNull(['a'])))
```

**Comment by inkrement** [comment]
Found the error. My mistake. I am now using aggregate_functions_null_for_empty=1;

**Comment by den-crane** [comment]
https://github.com/ClickHouse/ClickHouse/issues/38738
