### ISSUE TITLE
date_diff function returns wrong result when unit=hour or minute

### ISSUE THREAD

**Issue by dreamworld** [ClickHouse/ClickHouse#42742]
**Describe what's wrong**
```sql
SELECT dateDiff('hour', toDateTime('2018-01-01 22:00:00'), toDateTime('2018-01-02 23:00:00'));
24 # expect 25, as example in the docs https://clickhouse.com/docs/en/sql-reference/functions/date-time-functions#date_diff
SELECT dateDiff('minute', toDateTime('2018-01-01 22:00:00'), toDateTime('2018-01-01 22:12:00'));
0 # expect 12
```

**Does it reproduce on recent release?**
yes

**How to reproduce**
macOS, follow quickstart to install or manually download macOS build on github

* Which ClickHouse server version to use
I tried the following versions for macOS (intel)
22.11.1.92
22.10.1.1484
22.8.8.3
22.8.6.71

* Which interface to use, if matters
cli `./clickhouse client`

**Comment by den-crane** [comment]
```
./clickhouse local
ClickHouse local version 22.11.1.92 (official build).
```

```
./clickhouse local -q "SELECT dateDiff('minute', toDateTime('2018-01-01 22:00:00'), toDateTime('2018-01-01 22:12:00'))"
0
```

**Comment by HeenaBansal2009** [comment]
It returns as expected . Isn't it?
https://play.clickhouse.com/play?user=play#U0VMRUNUIGRhdGVEaWZmKCdob3VyJywgdG9EYXRlVGltZSgnMjAxOC0wMS0wMSAyMjowMDowMCcpLCB0b0RhdGVUaW1lKCcyMDE4LTAxLTAyIDIzOjAwOjAwJykpOw==

https://play.clickhouse.com/play?user=play#U0VMRUNUIGRhdGVEaWZmKCdtaW51dGUnLCB0b0RhdGVUaW1lKCcyMDE4LTAxLTAxIDIyOjAwOjAwJyksIHRvRGF0ZVRpbWUoJzIwMTgtMDEtMDEgMjI6MTI6MDAnKSk7
