### ISSUE TITLE
system.zookeeper_log produces a LOT of files in storage, exhausts inodes

### ISSUE THREAD

**Issue by pkit** [ClickHouse/ClickHouse#42741]
This kind of stuff:
```
# df -ih /var/lib/clickhouse/store
Filesystem     Inodes IUsed IFree IUse% Mounted on
none             320K  320K     1  100% /var/lib/clickhouse
```
```
# find -name '*.sql' | perl -ple 's#.*/##;s#_\d+\.sql##' | sort | uniq -c
   1381 asynchronous_metric_log
      1 covid_data.sql
  10998 metric_log
      3 query_log
      1 query_log.sql
      3 query_thread_log
      1 query_thread_log.sql
    892 trace_log
   8290 zookeeper_log
```
Like 10k `metric_log` partitions consumes 170k inodes
Same for `zookeeper_log`
Overall all of these (no actual data, only logs) eat more than 300k of inodes

**Comment by alesapin** [comment]
How is this issue related to clickhouse-keeper?

**Comment by pkit** [comment]
`zookeeper_log` is not produced by clickhouse-keeper ?

**Comment by alesapin** [comment]
No :) It's the log of all zookeeper-client request/response operations.

**Comment by pkit** [comment]
Oh, God, ok :)
Anyway I cannot find a way to reduce amount of partitioning for that one. Is it possible?

**Comment by den-crane** [comment]
@pkit check this https://kb.altinity.com/altinity-kb-setup-and-maintenance/altinity-kb-system-tables-eat-my-disk/

**Comment by alexey-milovidov** [comment]
The `system.zookeeper_log` table contains the log of all operations with ZooKeeper.
It is expected to be large. But it isn't enabled by default, so it is entirely up to you.
