### ISSUE TITLE
Enable CIFuzz

### ISSUE THREAD

**Issue by nikitamikhaylov** [ClickHouse/ClickHouse#42766]
CIFuzz is a set of GitHub Actions to build and run fuzzers for a project using build scripts from the upstream repo. We already have a PR but it looks abandoned https://github.com/ClickHouse/ClickHouse/pull/32005
We have to add this not to break fuzzers one more time..
This part of workflow can be explicitly triggered by putting a label to PR.
One concern - the build process is executed inside a container and there is no cache. Possible we can for the upstream repo and add ccache support there (mount ccache directory inside a container) and then use it for our needs. Ccache entries could be stored on S3 and can be downloaded before launching a build.

**Comment by alexey-milovidov** [comment]
Will be solved by @yakov-olkhovskiy in a different way.
