### ISSUE TITLE
authenticated Kafka MSK with Clickhouse

### ISSUE THREAD

**Issue by MahmoudElhalwany** [ClickHouse/ClickHouse#42784]
Hello, I have an MSK with IAM role auth and SASL/SCRAM auth, but when I try to connect it gives me 
`Disconnected while requesting ApiVersion: might be caused by incorrect security.protocol configuration (connecting to a SSL listener?) or broker version is < 0.10 (see api.version.request) (after 4ms in state APIVERSION_QUERY)`

My configuration is 

```
<sasl_username>username</sasl_username>
<sasl_password>password</sasl_password>
<security_protocol>sasl_ssl</security_protocol>
<sasl_mechanisms>SCRAM-SHA-512</sasl_mechanisms>
```

any idea ? and if it can be authed by IAM role please help

**Comment by MahmoudElhalwany** [comment]
also i used these config and doesn't work

```
<sasl_username> username </sasl_username>
       <sasl_password>password</sasl_password>
       <security_protocol>sasl_ssl</security_protocol>
      <sasl_mechanism>SCRAM-SHA-512</sasl_mechanisms>
      <sasl_jaas_config>"org.apache.kafka.common.security.scram.ScramLoginModule required username=\"username\" password=\"password\";">

```

**Comment by den-crane** [comment]
see https://kb.altinity.com/altinity-kb-integrations/altinity-kb-kafka/altinity-kb-adjusting-librdkafka-settings/#saslscram
https://kb.altinity.com/altinity-kb-integrations/altinity-kb-kafka/altinity-kb-adjusting-librdkafka-settings/#how-to-test-connection-settings

```
<yandex>
  <kafka>
    <security_protocol>sasl_ssl</security_protocol>
    <sasl_mechanism>SCRAM-SHA-512</sasl_mechanism>
    <sasl_username>root</sasl_username>
    <sasl_password>toor</sasl_password>
  </kafka>
</yandex>

**Comment by MahmoudElhalwany** [comment]
> see https://kb.altinity.com/altinity-kb-integrations/altinity-kb-kafka/altinity-kb-adjusting-librdkafka-settings/#saslscram https://kb.altinity.com/altinity-kb-integrations/altinity-kb-kafka/altinity-kb-adjusting-librdkafka-settings/#how-to-test-connection-settings

Which version support these types of auth?

**Comment by MahmoudElhalwany** [comment]
> see https://kb.altinity.com/altinity-kb-integrations/altinity-kb-kafka/altinity-kb-adjusting-librdkafka-settings/#saslscram https://kb.altinity.com/altinity-kb-integrations/altinity-kb-kafka/altinity-kb-adjusting-librdkafka-settings/#how-to-test-connection-settings

My version is `ClickHouse server version 22.7.2 revision 54457`

But when I try the example in your quoted links it gives me `Disconnected while requesting ApiVersion: might be caused by incorrect security.protocol configuration (connecting to a SSL listener?) or broker version is < 0.10 (see api.version.request) (after 1ms in state APIVERSION_QUERY)`

Iam using was MSK with SASL_SSL


Thanks

**Comment by den-crane** [comment]
check with

```
kafkacat -b my_broker:9092 -C -o -10 -t my_topic \
   -X security.protocol=SASL_SSL  \
   -X sasl.mechanisms=SCRAM-SHA-512 \
   -X sasl.username=username \
   -X sasl.password=password
```

**Comment by MahmoudElhalwany** [comment]
> check with
> 
> ```
> kafkacat -b my_broker:9092 -C -o -10 -t my_topic \
>    -X security.protocol=SASL_SSL  \
>    -X sasl.mechanisms=SCRAM-SHA-512 \
>    -X sasl.username=username \
>    -X sasl.password=password
> ```
> 
> > Which version support these types of auth?
> 
> 

I tried it after installing kafkacat on the server and it works fine, but with clickhouse it gives me the quoted error I have posted in the previous comment.

**Comment by den-crane** [comment]
> > check with
> > ```
> > kafkacat -b my_broker:9092 -C -o -10 -t my_topic \
> >    -X security.protocol=SASL_SSL  \
> >    -X sasl.mechanisms=SCRAM-SHA-512 \
> >    -X sasl.username=username \
> >    -X sasl.password=password
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > > Which version support these types of auth?
> 
> I tried it after installing kafkacat on the server and it works fine, but with clickhouse it gives me the quoted error I have posted in the previous comment.

Then it should work. How exactly you have configured this? Can you show a fragment of the config file?
it should be something like this

```
<yandex>
  <kafka>
    <security_protocol>sasl_ssl</security_protocol>
    <sasl_mechanism>SCRAM-SHA-512</sasl_mechanism>
    <sasl_username>root</sasl_username>
    <sasl_password>toor</sasl_password>
  </kafka>
</yandex>
```
Did you  restart Clickhouse service?

Also try to enable debug

```
...
  <kafka>
     <debug>all</debug>
``` 

https://kb.altinity.com/altinity-kb-integrations/altinity-kb-kafka/altinity-kb-adjusting-librdkafka-settings/

**Comment by MahmoudElhalwany** [comment]
> > > check with
> > > ```
> > > kafkacat -b my_broker:9092 -C -o -10 -t my_topic \
> > >    -X security.protocol=SASL_SSL  \
> > >    -X sasl.mechanisms=SCRAM-SHA-512 \
> > >    -X sasl.username=username \
> > >    -X sasl.password=password
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > > Which version support these types of auth?
> > 
> > 
> > I tried it after installing kafkacat on the server and it works fine, but with clickhouse it gives me the quoted error I have posted in the previous comment.
> 
> Then it should work. How exactly you have configured this? Can you show a fragment of the config file? it should be something like this
> 
> ```
> <yandex>
>   <kafka>
>     <security_protocol>sasl_ssl</security_protocol>
>     <sasl_mechanism>SCRAM-SHA-512</sasl_mechanism>
>     <sasl_username>root</sasl_username>
>     <sasl_password>toor</sasl_password>
>   </kafka>
> </yandex>
> ```
> 
> Did you restart Clickhouse service?
> 
> Also try to enable debug
> 
> ```
> ...
>   <kafka>
>      <debug>all</debug>
> ```
> 
> https://kb.altinity.com/altinity-kb-integrations/altinity-kb-kafka/altinity-kb-adjusting-librdkafka-settings/

I didn't know that I should restart ClickHouse 

Thanks it worked now
