### ISSUE TITLE
What's the correct process to change IP address for all cluster servers?

### ISSUE THREAD

**Issue by taotaizhu-pw** [ClickHouse/ClickHouse#42808]
We would publish our project to production enviroment from pre-prod. The three clickhouse servers would change the IP addresses (keep the same physical servers). 

Clickhouse Version: 22.3.6.5 
we used clickhouse-keeper

In my plan:

1. stop each clickhouse server
2. update config.xml:  (1) keeper_server->raft_configuration->hostname  (2) interserver_http_host
3. update metrika.xml:   (1) clickhouse_remote_servers->shard->replica->host  (2) macros->replica  (3) zookeeper-servers->node->host
4. start clickhouse server

What's the correct process to change the IP for each server? Is there any potential issue?

**Comment by den-crane** [comment]
22.3.6.5 is out of support. Upgrade to 22.3.14.23.

Plan is correct.
Probably to start a keeper you have to use recovery mode. https://clickhouse.com/docs/en/operations/clickhouse-keeper/#recovering-after-losing-quorum

BTW, In case of DNS no reconfiguration is required.

`metrika.xml` is outdated. You can describe your cluster in `config.d/youcluster.xml`.
