### ISSUE TITLE
"partitioning is not intended to speed up SELECT queries (ORDER BY key is sufficient to make range queries fast)"

### ISSUE THREAD

**Issue by swarupsarangi113** [ClickHouse/ClickHouse#42801]
### Question

This question is more of an open-ended discussion to understand the statement in the headline. Feel free to comment if any question!

### Given

A table with following data (say 60 mil +) 

```
┌─────────id───────────────────────────┬───────createdby───────────────┬──────────modifiedby───────────────────────────┬──stage────────autoid─┬───────────────ownerid───────────────────────┬─source──────────────┬───────────createdon─┬──────────modifiedon─┐
│ 1791ca50-5245-11ea-aa39-0697d1d57d70 │ 8376ebfb-41fb-11e8-a5de-02b09d13b7e6 │ 8376ebfb-41fb-11e8-a5de-02b09d13b7e6 │ something_1 │       40693092 │ cd3f7be7-c49e-11e7-8846-021d4032d696 │                     │ 2020-02-18 11:57:44 │ 2020-08-06 06:23:09 │
│ 17a58fe6-5245-11ea-aa39-0697d1d57d70 │ 8376ebfb-41fb-11e8-a5de-02b09d13b7e6 │ cd3f7be7-c49e-11e7-8846-021d4032d696 │ something_1 │       40699682 │ cd3f7be7-c49e-11e7-8846-021d4032d696 │                     │ 2020-02-18 11:58:33 │ 2020-07-24 03:28:57 │
│ 57109f7a-b371-11e9-b231-0a3f89e00c4e │ 8376ebfb-41fb-11e8-a5de-02b09d13b7e6 │ 0cfee01d-ed2f-11ea-b50c-0697d1d57d70 │ something_2 │       29038557 │ cd3f7be7-c49e-11e7-8846-021d4032d696 │ some_random_website │ 2019-07-31 08:59:50 │ 2020-10-23 12:41:13 │
│ 861a59d2-523a-11ea-aa39-0697d1d57d70 │ 8376ebfb-41fb-11e8-a5de-02b09d13b7e6 │ cd3f7be7-c49e-11e7-8846-021d4032d696 │ something_4 │       40657760 │ cd3f7be7-c49e-11e7-8846-021d4032d696 │                     │ 2020-02-16 18:30:00 │ 2020-07-24 03:28:57 │
│ 8645e91e-523a-11ea-aa39-0697d1d57d70 │ 8376ebfb-41fb-11e8-a5de-02b09d13b7e6 │ 8376ebfb-41fb-11e8-a5de-02b09d13b7e6 │ something_4 │       40672671 │ cd3f7be7-c49e-11e7-8846-021d4032d696 │                     │ 2020-02-13 18:30:00 │ 2020-08-06 06:23:09 │
│ 8759c8a9-c6a4-11ea-992c-0697d1d57d70 │ 50a86007-c3ba-11e7-8758-0a106ee76b21 │ 0cfee01d-ed2f-11ea-b50c-0697d1d57d70 │ something_1 │       50206428 │ cd3f7be7-c49e-11e7-8846-021d4032d696 │ some_random_website │ 2020-07-15 14:07:33 │ 2020-10-23 12:51:24 │
│ abe0dcae-9891-4f7b-90c4-0bcafa90a2bc │ 61cc6045-c541-11e7-8846-021d4032d696 │ 0cfee01d-ed2f-11ea-b50c-0697d1d57d70 │ something_2 │       46657373 │ cd40e3ed-c49e-11e7-8846-021d4032d696 │                     │ 2020-05-17 08:27:55 │ 2021-09-22 13:11:12 │
└──────────────────────────────────────┴──────────────────────────────────────┴──────────────────────────────────────┴──────────────────────┴────────────────┴──────────────────────────────────────┴─────────────────────┴───────────────────────────────────
```

Now with data above, I create two tables in clickhouse with definition as below - 

`table1`

```
CREATE TABLE table1
(
    `id` String,
    `createdby` String,
    `modifiedby` String,
    `stage` String,
    `autoid` Int64,
    `ownerid` String,
    `source` String,
    `createdon` DateTime,
    `modifiedon` DateTime,
    INDEX modifiedon_ps_idx modifiedon TYPE minmax GRANULARITY 4,
    INDEX createdon_ps_idx createdon TYPE minmax GRANULARITY 4
)
ENGINE = MergeTree()
PARTITION BY stage
PRIMARY KEY id
ORDER BY (id, toYYYYMM(createdon), toYYYYMM(modifiedon))
SETTINGS index_granularity = 8192
```
No of parts: 71

`table2`

```
CREATE TABLE table2
(
    `id` String,
    `createdby` String,
    `modifiedby` String,
    `stage` String,
    `autoid` Int64,
    `ownerid` String,
    `source` String,
    `createdon` DateTime,
    `modifiedon` DateTime,
    INDEX modifiedon_ps_idx modifiedon TYPE minmax GRANULARITY 4,
    INDEX createdon_ps_idx createdon TYPE minmax GRANULARITY 4
)
ENGINE = MergeTree()
PARTITION BY (stage,toYYYYMM(createdon))
PRIMARY KEY id
ORDER BY (id, toYYYYMM(createdon), toYYYYMM(modifiedon))
SETTINGS index_granularity = 8192
```
No of parts: 1503

In `table1` we are using single partition whereas in `table2` we are using multi-partitions hence the parts is more in `table2`

No If I run the below queries in both the tables : 

```
SELECT
    count(id),
    createdon,
    modifiedon,
    createdby
FROM <table>
WHERE (stage = 'something_4') AND ((toYYYYMMDD(createdon) >= 20200501) AND (toYYYYMMDD(createdon) <= 20200531))
GROUP BY
    createdon,
    modifiedon,
    createdby
```
`table1`   263519 rows in set. Elapsed: 3.306 sec. Processed 19.20 million rows, 2.21 GB (5.81 million rows/s., 667.90 MB/s.)
`table2`  263519 rows in set. Elapsed: 0.254 sec. Processed 290.73 thousand rows, 33.43 MB (1.14 million rows/s., 131.46 MB/s.)

### Analysis

`table2` is returning the result 92% faster than `table1` only at the cost of increase no of parts by 95% (which is in permissible range of 1000 ...10000 as defined in ClickHouse docs)

### Question

Since we can clearly see that multi-partitioning is indeed speeding up `SELECT` queries (even though both tables have same `order by` keys). 

Does that mean it is recommended to use multi- `partition by` for range queries in some cases since `order by` is not enough in these cases or I could have achieved the result in some other way only by using single partition and a different `order by`

**Comment by den-crane** [comment]
>"partitioning is not intended to speed up SELECT queries (ORDER BY key is sufficient to make range queries fast)"

It's simplified explanation for newbies to discourage them to use PARTITIONING incorrectly.

see https://youtu.be/DP7l6Swkskw?t=3778

**Comment by den-crane** [comment]
>Does that mean it is recommended to use multi- partition by for range queries in some cases since order by is not enough in these cases or I could have achieved the result in some other way only by using single partition and a different order by

Yes, it does. BUT you should test your use-case in near-production load. 

>PARTITION BY (stage,toYYYYMM(createdon))

Such partitioning is viable if a cardinality of `stage` is small (less than 100). And if you insert only one stage per insert.
