### ISSUE TITLE
 gh-api.clickhouse.tech Not enough privileges

### ISSUE THREAD

**Issue by l1t1** [ClickHouse/ClickHouse#42802]
> Make sure to check documentation https://clickhouse.com/docs/en/ first. If the question is concise and probably has a short answer, asking it in Telegram chat https://telegram.me/clickhouse_en is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

> If you still prefer GitHub issues, remove all this text and ask your question here.
I can run `SELECT * FROM numbers(10);` on https://gh-api.clickhouse.tech/play?user=play as mentioned on
https://[github.com](https://github.com/ClickHouse/ClickHouse/issues/25028)/ClickHouse/ClickHouse/issues/25028

now it reports following message.
```
Code: 497. DB::Exception: play: Not enough privileges. To execute this query it's necessary to have grant CREATE TEMPORARY TABLE ON *.*. (ACCESS_DENIED) (version 22.10.1.1875 (official build))
```

while `SELECT 42 a,version();` can be run.

a | version()
-- | --
42 | 22.10.1.1875

**Comment by tavplubix** [comment]
See https://github.com/ClickHouse/ClickHouse/issues/42414
