### ISSUE TITLE
Unknown table engine HDFS and Hive

### ISSUE THREAD

**Issue by nashlibby** [ClickHouse/ClickHouse#42813]
Code: 56. DB::Exception: Unknown table engine HDFS. (UNKNOWN_STORAGE) (version 22.3.14.23 (official build))
, server ClickHouseNode(addr=http:localhost/<unresolved>:8123, db=default)@-593505357

Code: 56. DB::Exception: Unknown table engine Hive. Maybe you meant: ['File']. (UNKNOWN_STORAGE) (version 22.3.14.23 (official build))
, server ClickHouseNode(addr=http:localhost/<unresolved>:8123, db=default)@-593505357

**Comment by nashlibby** [comment]
env: mac m1
version: 22.3.14.23

**Comment by den-crane** [comment]
HDFS is not supported in MacOS build.

Try to use https://github.com/Altinity/homebrew-clickhouse or arm-docker image https://hub.docker.com/r/clickhouse/clickhouse-server/tags

**Comment by nashlibby** [comment]
tks

**Comment by nashlibby** [comment]
i tried to run it by homebrew and docker, this problem is still there, only linux?

**Comment by den-crane** [comment]
Ah, right arm image does not have HDFS support

```
select * from system.build_options where name = 'USE_HDFS';
┌─name─────┬─value─┐
│ USE_HDFS │       │
└──────────┴───────┘
```
Only intel then.

**Comment by nashlibby** [comment]
TKS, WHAT A BIG HASSLE
