### ISSUE TITLE
With distributed data query with cluster, why time taken is linear growth

### ISSUE THREAD

**Issue by flyly0755** [ClickHouse/ClickHouse#42810]
**Describe the situation**
I have a clickhouse cluster, which contains 3 machines.
There is a table tb_test in every machine under same database call tb_db.
And with a corresponding distributed table(tb_test_dist, which is actually a view, can get all data from table tb_test on all 3 machines) 
For example, There are separately 100 million data in every table tb_test(with same id in same machine, for example id xxx in machine a, yyy in machine b, zzz in machine c).
query these  100 million data from one machine take 100 seconds(select * from tb_test where id = xxx),
but query all 300 million data from tb_test_dist take about 300 seconds, is't odd(select * from tb_test_dist id in (xxx, yyy,zzz))
I think the normal situation should take about 100 seconds.
In addition, Comparison test with sql(select * from tb_test id in (xxx, yyy,zzz)) which also only take about 100 seconds.
**How to reproduce**
* Which ClickHouse server version to use
clickhouse 21.12.3.32
zookeeper 3.7.0

**Comment by den-crane** [comment]
The most probably `select * from tb_test where id = xxx` is bounded by the network or by your client application.
Check with `select * from tb_test where id = xxx format Null`

21.12.3.32 is out of support. You should upgrade to 22.10.

Also see

```
  --distributed_group_by_no_merge arg                                                  If 1, Do not merge aggregation states from different servers for distributed queries (shards will process
                                                                                       query up to the Complete stage, initiator just proxies the data from the shards). If 2 the initiator will
                                                                                       apply ORDER BY and LIMIT stages (it is not in case when shard process query up to the Complete stage)

  --optimize_distributed_group_by_sharding_key arg                                     Optimize GROUP BY sharding_key queries (by avoiding costly aggregation on the initiator server).
```
