### ISSUE TITLE
Fail to ATTACH:   Unknown data type family: DateTime64(6). Maybe you meant: ['DateTime64','DateTime32']

### ISSUE THREAD

**Issue by minhmq** [ClickHouse/ClickHouse#42817]
> You have to provide the following information whenever possible.

**Describe what's wrong**
I have a PostgreSQL DB and connect it from Clickhouse with PostgreSQL Engine. I cannot attach table of this after detach

> A clear and concise description of what works not as it is supposed to.

It can reproduce at least from 22.6.*, 22.8.8.3 and 22.10.1.1877

**How to reproduce**

* Which ClickHouse server version to use: 22.6.*, 22.8.8.3 and 22.10.1.1877
* Which interface to use, if matters: PostgreSQL Engine; DETACH, ATTACH Function

* `CREATE TABLE` statements for all tables involved

In PostgreSQL
`create table test
(
    id                uuid not null
        primary key,
    created_at        timestamp,
    updated_at        timestamp
);`

In ClickHouse
`CREATE DATABASE proxy_test ENGINE = 
    PostgreSQL(concat(dictGetString('ENV', 'value', 'DB_HOSTNAME') , ':' , dictGetString('ENV', 'value', 'DB_PORT')), dictGetString('ENV', 'value', 'DB_DB_NAME'), dictGetString('ENV', 'value', 'DB_USERNAME'), dictGetString('ENV', 'value', 'DB_PASSWORD'), 'public', 1);`

`DETACH TABLE proxy_test.test;
ATTACH TABLE proxy_test.test;`

* Queries to run that lead to unexpected result
`ATTACH TABLE proxy_test.test;`

**Expected behavior**

ATTACH TABLE SUCCESSFUL and can query data after that

**Error message and/or stacktrace**

Code: 50. DB::Exception: Unknown data type family: DateTime64(6). Maybe you meant: ['DateTime64','DateTime32']. (UNKNOWN_TYPE) (version 22.10.1.1877 (official build))
[2022-10-31 17:04:43] , server ClickHouseNode [uri=http://localhost:8123/default, options={custom_http_params=session_id=DataGrip_a25b9286-85c7-4a65-81c3-a3c195ab76c4}]@2062729531

**Comment by kssenii** [comment]
@minhmq, fix https://github.com/ClickHouse/ClickHouse/pull/42960.
