### ISSUE TITLE
When using antlrv4 to parse clause with keyword "insert"

### ISSUE THREAD

**Issue by Pkkkkkkkk** [ClickHouse/ClickHouse#42849]
There is nothing output(null) when using the **java Class** ,which is Override from "**ClickhouseParser.java**" ,compiled from .g4(grammer file) by antlr-plugin ,to parse a clause about "**INSERT INTO** ...".But the clause can be recognized corrctly in using "**ClickhouseParser.java**" dirctly.

**Comment by alexey-milovidov** [comment]
The ANTLRv4 parser is not supported.

**Comment by alexey-milovidov** [comment]
I've updated the readme: https://github.com/ClickHouse/ClickHouse/pull/42917

**Comment by Pkkkkkkkk** [comment]
I see.
If there is an way to use it(clikchouse's run-time parser ) in a maven project?

**Comment by alexey-milovidov** [comment]
No, only the imperfect ANTLR parser is available.

**Comment by Pkkkkkkkk** [comment]
Got it,thks!
