### ISSUE TITLE
Child process was terminated by signal 6

### ISSUE THREAD

**Issue by xpleaf** [ClickHouse/ClickHouse#42848]
## 1 ClickHouse Version

```
21.8
```

## 2 Question

My ClickHouse is running with the following error: 

```
2022.10.27 03:19:46.384164 [ 87689 ] {} <Fatal> Application: Child process was terminated by signal 6.
```

The ClickHouse process then exits. Is this because the C++ program can't get memory through the malloc() function? Is there any way to alleviate this problem? 
Thank you very much!

**Comment by DerekChia** [comment]
Do you have more logs to share? Signal 6 could refer to a lot of things
