### ISSUE TITLE
MaterializedMySQL got error Unsupported query event:SAVEPOINT `__EFSavePoint`

### ISSUE THREAD

**Issue by SZDRZ** [ClickHouse/ClickHouse#42856]
Hello! When I used MaterializedMySQL  to replicate data got this error: `Unsupported query event:SAVEPOINT __EFSavePoint`
Any configurations to ignore this error and continue to replication ?

**Comment by alexey-milovidov** [comment]
Need help from @stigsb

**Comment by alexey-milovidov** [comment]
@stigsb 

- missing whitespace after comma;
- SAVEPOINT is in all caps, it looks scary;
- double underscore in __EFSavePoint is scary;
- it's unclear what is EF;

Most likely these are bad programming practices from the MySQL codebase.

**Comment by stigsb** [comment]
Will contribute a rewrite of MaterializedMySQL by the end of the year that also contains a fix for SAVEPOINT.

**Comment by stigsb** [comment]
@alexey-milovidov The SAVEPOINT fix was tiny, made a PR for it here: #43086
