### ISSUE TITLE
ParsingException when importing Point data from CSV

### ISSUE THREAD

**Issue by aimfeld** [ClickHouse/ClickHouse#42858]
When importing CSV files with geo Point data, I always get this error:

> `Code: 27. DB::ParsingException: Cannot parse input: expected '"' before: '(10, 10)"'`

To reproduce the problem under simple conditions, I created a table with a Point column:
`CREATE TABLE default.geo_point (p Point) ENGINE = Memory()`

I also created a geo_point.csv file with a single point in it:
```
"(10, 10)"
```

I import the file with the clickhouse client (version 22.9.3.18) like this:
`cat geo_point.csv | clickhouse-client -q 'INSERT INTO default.geo_point FORMAT CSV'`

I get the above error, even when removing the double quotes. Not sure if this is a bug, or if I need to pass a certain flag to the clickhouse-client (I didn't find a flag that works). 

Other datatypes are imported just fine. Also, when I change the data type from Point to String, the import works fine.

**Comment by den-crane** [comment]
it should be `10,10` in CSV.

```
INSERT INTO geo_point VALUES((10, 10));

select * from default.geo_point format CSV;
10,10

insert  into default.geo_point format CSV 20,20
              ;

select * from default.geo_point;
┌─p───────┐
│ (10,10) │
│ (20,20) │
└─────────┘
```

**Comment by aimfeld** [comment]
Thanks, I tried TabSeparated format instead of CSV, and it worked. I can now import my postgres table into clickhouse, using psql and clickhouse-client:

`psql -d my_db -U postgres -h localhost -c "\COPY (SELECT * FROM my_table) TO stdout WITH (FORMAT TEXT)" | clickhouse-client  -q 'INSERT INTO my_db.my_table FORMAT TabSeparated'`
