### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by TaoPanfeng** [ClickHouse/ClickHouse#42888]
Connection refused (Connection refused), server ClickHouseNode(addr=xxx:8123, db=xxx)@-421027213

**Comment by DerekChia** [comment]
What client are you using? If it is clickhouse-jdbc, see issue #36331

**Comment by den-crane** [comment]
You need to add a file and restart Clickhouse

```sql
cat /etc/clickhouse-server/config.d/listen_host.xml
<?xml version="1.0"?>
<clickhouse>
	<listen_host>::</listen_host>
</clickhouse>
```
