### ISSUE TITLE
 <Error> Application: DB::Exception: Unknown element in config: internal_replication

### ISSUE THREAD

**Issue by superxor** [ClickHouse/ClickHouse#42885]
**Installation type**

single binary from repo

**Source of the ClickHouse**

ubuntu repo

**Expected result**

systemctl start clickhouse-server

**The actual result**

 <Error> Application: DB::Exception: Unknown element in config: internal_replication

This is a fresh new install of 22.2.2.1 on Ubuntu 22.04.1 LTS from CH repo.
I copied our existing config parts but for some reason it says internal replication is not recognized as a setting.

excerpt config:

```   
 <remote_servers>
    <4node>
        <shard>
            <internal_replication>true</internal_replication>
            <replica>
                <host>xx1</host>
                <port>9000</port>
                <user>default</user>
            </replica>
            <replica>
                <host>xx2</host>
                <port>9000</port>
                <user>default</user>
            </replica>
        </shard>
        <shard>
            <internal_replication>true</internal_replication>
            <replica>
                <host>xx3</host>
                <port>9000</port>
                <user>default</user>
            </replica>
                <replica>
                <host>xx4</host>
                <port>9000</port>
                <user>default</user>
            </replica>
        </shard>
    </4node>
    </remote_servers>```

**Comment by superxor** [comment]
@den-crane I realized I used an old repo. Upgraded now to

clickhouse-server                     22.10.2.11

Still getting the same error though

2022.11.01 03:49:35.287137 [ 46061 ] {} <Error> Application: DB::Exception: Unknown element in config: internal_replication

**Comment by superxor** [comment]
Seems the issue was that I had 4 in name...worked after I renamed it to fournode....

**Comment by den-crane** [comment]
it needs more clear error message

**Comment by superxor** [comment]
The newer version said "invalid character" so I reckoned it must be the 4.
