### ISSUE TITLE
 execute truncate got an error: DB::Exception: WRITE locking attempt on 'xxx' has timed out! (120000ms) 

### ISSUE THREAD

**Issue by fsindustry** [ClickHouse/ClickHouse#42887]
I'm trying to execute "truncate table t1" statement immediately after finishing this statement "insert into t1 select * from t2" .All these statements are written in a shell script.

Execute the script and I'm facing the error information below:

Code: 473. DB::Exception: Received from xxx.xxx.xxx.xxx:9000. DB::Exception: WRITE locking attempt on 'xxx' has timed out! (120000ms) Possible deadlock avoided. Client should retry..

But when I execute truncate statement manually after insertion for a while. It's OK. why does this case happen?
I wonder whether the insertion is not truly completed after response, and still holding the lock, so that the truncate table statement can't get the lock and throw the error？

here is the information of my environment：

1) clickhouse version: 21.8.14.5
2) records in t2: 0.5 billion
3) t2 's engine: hdfs
4) t1's engine: mergeTree

stack trace below:

2022.10.31 11:41:02.220027 [ 10949 ] {442b1d53-7de7-425a-8eea-63d1ad774b65} <Error> executeQuery: Code: 473, e.displayText() = DB::Exception: WRITE locking attempt on "gjst.sh_fetch_sale_base_fact_snap" has timed out! (120000ms) Possible deadlock avoided. Client should retry. (version [21.8.14.5](http://21.8.14.5/)) (from [0.0.0.0:0](http://0.0.0.0:0/)) (in query: /* ddl_entry=query-0000000005 */ TRUNCATE TABLE gjst.sh_fetch_sale_base_fact_snap), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x8f5c19a in /usr/local/clickhouse/bin/clickhouse
1. DB::IStorage::tryLockTimed(std::__1::shared_ptr<DB::RWLockImpl> const&, DB::RWLockImpl::Type, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000l> > const&) const @ 0x1095aba7 in /usr/local/clickhouse/bin/clickhouse
2. DB::IStorage::lockExclusively(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000l> > const&) @ 0x1095b2d5 in /usr/local/clickhouse/bin/clickhouse
3. DB::InterpreterDropQuery::executeToTableImpl(DB::ASTDropQuery&, std::__1::shared_ptr<DB::IDatabase>&, StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag>&) @ 0x101d1c88 in /usr/local/clickhouse/bin/clickhouse
4. DB::InterpreterDropQuery::executeToTable(DB::ASTDropQuery&) @ 0x101d0546 in /usr/local/clickhouse/bin/clickhouse
5. DB::InterpreterDropQuery::execute() @ 0x101d0028 in /usr/local/clickhouse/bin/clickhouse
6. DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, bool, DB::ReadBuffer*) @ 0x1078c3a4 in /usr/local/clickhouse/bin/clickhouse
7. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::__1::shared_ptr<DB::Context>, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>, std::__1::optional<DB::FormatSettings> const&) @ 0x1078fe7d in /usr/local/clickhouse/bin/clickhouse
8. DB::DDLWorker::tryExecuteQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::DDLTaskBase&, std::__1::shared_ptr<zkutil::ZooKeeper> const&) @ 0x1005cd35 in /usr/local/clickhouse/bin/clickhouse
9. DB::DDLWorker::processTask(DB::DDLTaskBase&, std::__1::shared_ptr<zkutil::ZooKeeper> const&) @ 0x1005b8f7 in /usr/local/clickhouse/bin/clickhouse
10. DB::DDLWorker::scheduleTasks(bool) @ 0x100590d3 in /usr/local/clickhouse/bin/clickhouse
11. DB::DDLWorker::runMainThread() @ 0x1005264b in /usr/local/clickhouse/bin/clickhouse
12. ThreadFromGlobalPool::ThreadFromGlobalPool<void (DB::DDLWorker::*)(), DB::DDLWorker*>(void (DB::DDLWorker::*&&)(), DB::DDLWorker*&&)::'lambda'()::operator()() @ 0x10069fb1 in /usr/local/clickhouse/bin/clickhouse
13. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x8f9cdbf in /usr/local/clickhouse/bin/clickhouse
14. void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) @ 0x8fa06a3 in /usr/local/clickhouse/bin/clickhouse
15. start_thread @ 0x7e65 in /usr/lib64/[libpthread-2.17.so](http://libpthread-2.17.so/)
16. __clone @ 0xfe88d in /usr/lib64/[libc-2.17.so](http://libc-2.17.so/)

2022.10.31 11:41:02.220280 [ 10949 ] {442b1d53-7de7-425a-8eea-63d1ad774b65} <Error> DDLWorker: Query TRUNCATE TABLE gjst.sh_fetch_sale_base_fact_snap wasn't finished successfully: Code: 473, e.displayText() = DB::Exception: WRITE locking attempt on "gjst.sh_fetch_sale_base_fact_snap" has timed out! (120000ms) Possible deadlock avoided. Client should retry., Stack trace (when copying this message, always include the lines below):

**Comment by den-crane** [comment]
21.8 is out support.
It's expected behaviour. Truncate can be blocked by a running merge. Merge cancellation were added later.
Upgrade to 22.10.

**Comment by fsindustry** [comment]
> 
ok，I got it. thanks!
if I want to clean data in table, can I use the statements below to replace truncate?

# create a tmp table with same column
create tmp_tbl as target_tbl;
# exchange tmp table with target table to be cleaned; exchange is non-blocked.
exchange table target_tbl and tmp_tbl;
# drop the old table non-blocked
drop table  tmp_tbl ;
