### ISSUE TITLE
`CREATE USER ... IDENTIFIED WITH PASSWORD` should use the preferred password hashing method

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#42915]
**Use case**

There are several ways to specify password for a user by writing it in plaintext in the query,
different by hashing mechanism (plaintext, sha256, double_sha1):
https://clickhouse.com/docs/en/sql-reference/statements/create/user/#identification

Let's allow to write 

`CREATE USER ... IDENTIFIED WITH PASSWORD '...'`

which will select the default method, specified in the configuration file.

It will allow adding `bcrypt` hashing method without explicitly switching to it in the queries.

**Comment by dentiscalprum** [comment]
Hi, may I have a try on this?
Thank you !

**Comment by alexey-milovidov** [comment]
@dentiscalprum thank you! This will be very helpful.

PS. The default should be sha256_password.
