### ISSUE TITLE
How to make a user with a remote execute privilege ?

### ISSUE THREAD

**Issue by kaynewu** [ClickHouse/ClickHouse#42923]
I have done 
GRANT CREATE TEMPORARY TABLE ON  ***.***  TO 'user_operator' on CLUSTER '{cluster}';
GRANT REMOTE ON  ***.***  TO 'user_operator' on CLUSTER '{cluster}';
to user user_operator.

clickhouse default can query with a right result:
![image](https://user-images.githubusercontent.com/5574794/199647424-bb75a03a-b7aa-4f68-9ff7-6b4857f4785f.png)

but user_operator  remote sql result still  0.
![image](https://user-images.githubusercontent.com/5574794/199647149-004ba865-a0b4-48e8-a58c-bb13e144941f.png)
what should I do more？

**Comment by alexey-milovidov** [comment]
Also, check row policies. If a row policy is set for a table, the user will not see any records unless you add a row policy for it.
