### ISSUE TITLE
about array empty elements

### ISSUE THREAD

**Issue by cambyzju** [ClickHouse/ClickHouse#42922]
Question:
Why array `[,]` means array `[0]`, not array `[0,0]`? Is it a design problem or a bug?
As we know array `[1,2]` has two elements. So I think array `[,]` represent array `[0,0]` with two elements, maybe more reasonable?

How to reproduce:
1. create table with array column:
```
CREATE TABLE test
(
    `id` UInt64,
    `ids` Array(Nullable(UInt64))
)
ENGINE = MergeTree
PRIMARY KEY id
ORDER BY id
SETTINGS index_granularity = 10;
```

2. insert some test data
```
insert into test values(1,[]);
insert into test values(2,[,]);
insert into test values(3,[,,]);
insert into test values(4,[,,4]);
```

3. query the table
```
> select * from test order by id;
+------+---------+
| id   | ids     |
+------+---------+
|    1 | []      |
|    2 | [0]     |
|    3 | [0,0]   |
|    4 | [0,0,4] |
+------+---------+
4 rows in set (0.02 sec)
```

**Comment by alexey-milovidov** [comment]
@cambyzju this is the implementation-specific detail of the Values format.
It can parse empty elements as zero and also skip the trailing comma.

As it's implementation specific, it's not a bug, but you should not rely on this behavior.
