### ISSUE TITLE
Hive Metastore expired

### ISSUE THREAD

**Issue by nashlibby** [ClickHouse/ClickHouse#42927]
create table hive_data (id Int8, name String, date String) Engine = Hive('thrift://172.18.182.251:10000', 'test', 't1') PARTITION BY date;

Received exception from server (version 22.2.2):
Code: 640. DB::Exception: Received from localhost:9000. DB::Exception: Hive Metastore expired because No more data to read.. (NO_HIVEMETASTORE)

----

hive > select * from test.t1;
two records

why no more data to read ?

**Comment by alexey-milovidov** [comment]
No one has answered, closing.
