### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by openxxx** [ClickHouse/ClickHouse#42920]
**Installation type**

Packages

**Source of the ClickHouse**

sudo apt-get install -o Dpkg::Options::="--force-confold" --allow-unauthenticated --allow-downgrades --allow-remove-essential --allow-change-held-packages -y debconf-utils
sudo apt-get install -y apt-transport-https ca-certificates dirmngr
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 8919F6BD2B48D754
echo "deb https://packages.clickhouse.com/deb stable main" | sudo tee /etc/apt/sources.list.d/clickhouse.list
sudo apt-get update

**Expected result**

success

**The actual result**

Err:1 https://packages.clickhouse.com/deb stable/main amd64 clickhouse-common-static amd64 21.11.11.1
  404  Not Found [IP: 172.66.40.249 443]
Err:2 https://packages.clickhouse.com/deb stable/main amd64 clickhouse-client all 21.11.11.1
  404  Not Found [IP: 172.66.40.249 443]
Err:3 https://packages.clickhouse.com/deb stable/main amd64 clickhouse-server all 21.11.11.1
  404  Not Found [IP: 172.66.40.249 443]
E: Failed to fetch https://packages.clickhouse.com/deb/pool/stable/clickhouse-common-static_21.11.11.1_amd64.deb  404  Not Found [IP: 172.66.40.249 443]
E: Failed to fetch https://packages.clickhouse.com/deb/pool/stable/clickhouse-client_21.11.11.1_all.deb  404  Not Found [IP: 172.66.40.249 443]
E: Failed to fetch https://packages.clickhouse.com/deb/pool/stable/clickhouse-server_21.11.11.1_all.deb  404  Not Found [IP: 172.66.40.249 443]

**Comment by cangyin** [comment]
You can manually download all three packages from [here](https://packages.clickhouse.com/deb/pool/main/c/).

Or consider other installation options like docker images.

**Comment by muzammilar** [comment]
@openxxx The URL ` https://packages.clickhouse.com/deb/pool/stable/clickhouse-common-static_21.11.11.1_amd64.deb` is incorrect. It should be pointing to `https://packages.clickhouse.com/deb/pool/main/c/clickhouse/clickhouse-client_21.11.11.1_all.deb` That said, I can't seem to replicate it. Is it still happening for you? If you it would be worth checking your APT Cache.

**Comment by muzammilar** [comment]
I disagreed with the bit about manually downloading the packages or using docker ;) It's generally difficult to preemptively provide a solution without context. Consider the scenario where the author may be trying to automate his deployments (without using docker images) and downloads is not really an option for him.

**Comment by cangyin** [comment]
> manually downloading the packages or using docker

Actually, we do deploy clickhouse cluster by downloading and archiving a stable version of clickhouse in our production environment. Automated deployment won't involve upgrading clickhouse version out of stability considerations.

If you do need automated manner, docker image are even better solution.

> provide a solution without context

You have pointed out in your own issue, that the problem is caused by 'inconsistent package manifest'. By doing a simple browsing, you also found that link addresses mismatched that provided in yum package medatada. And similar issues were also reported in clickhouse telegram group.

**Comment by Felixoid** [comment]
@openxxx I clearly see that your apt cache is old, since it points to the old state when packages where in `deb/pool/stable`

Follow the https://clickhouse.com/docs/en/operations/troubleshooting/#you-get-different-warnings-with-apt-get-update
