### ISSUE TITLE
Distributed engine: Show what query was executed on non-coordinator shards

### ISSUE THREAD

**Issue by macobo** [ClickHouse/ClickHouse#42930]
**Use case**

When debugging performance with Distributed tables, it's important to understand what exact query was sent out to non-coordinator nodes on other shards.

This information would give us the ability to know what exactly was executed, debug the query plan and understand how much data was sent over the network.

Currently `system.query_log` does report something similar to these queries, but they are not _actually_ accurate. See additional context.

**Describe the solution you'd like**

A tool to show the exact sql. This could be any of:
- `system.query_log` entry on the non-coordinator nodes (which would be more accurate)
- SQL added to `description` of `EXPLAIN` or a separate flag
- Logs containing the query `SET send_logs_level = 'trace'`

**Additional context**

Slack thread discussing this question: https://clickhousedb.slack.com/archives/CU478UEQZ/p1667462834817159

Note that query_log contains an inaccurate query currently on my test cluster (version 22.3).

Consider this toy schema and query:

```sql
CREATE TABLE sharded_sensor_values ON CLUSTER 'my_cluster' (
    timestamp DateTime,
    site_id UInt32,
    event VARCHAR,
    uuid UUID,
    metric_value Int32
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/sharded_sensor_values', '{replica}')
ORDER BY (site_id, toStartOfDay(timestamp), event, uuid)
SETTINGS index_granularity = 8192

CREATE TABLE distributed_sensor_values ON CLUSTER 'my_cluster' (
    timestamp DateTime,
    site_id UInt32,
    event VARCHAR,
    uuid UUID,
    metric_value Int32
)
ENGINE = Distributed('my_cluster', 'default', 'sharded_sensor_values', intHash64(site_id))

SELECT
    toStartOfDay(timestamp),
    avg(metric_value) as metric_value
FROM distributed_sensor_values
WHERE timestamp > '2010-01-01' and timestamp < '2023-01-01'
GROUP BY toStartOfDay(timestamp)
ORDER BY metric_value DESC
LIMIT 20
```

`EXPLAIN` for the query shows this important segment:

```
              ReadFromRemote (Read from remote replica)
              Header: toStartOfDay(timestamp) DateTime
                      avg(metric_value) AggregateFunction(avg, Int32)
```

While `system.query_log` reports this query on the other shard:

```sql
SELECT toStartOfDay(`timestamp`), avg(`metric_value`) AS `metric_value` FROM `default`.`sharded_sensor_values` WHERE (`timestamp` > '2010-01-01') AND (`timestamp` < '2023-01-01') GROUP BY toStartOfDay(`timestamp`) ORDER BY `metric_value` DESC LIMIT 20
```

I think the reported query is incorrect:
1. According to EXPLAIN, the shard is returning `avgState` not `avg` results
2. I think the LIMIT cannot be pushed down properly with this query.

Note that the query is returning valid results - I just think that query_log is inaccurate.

**Comment by UnamedRus** [comment]
It's controlled by  `--stage` parameter.
ClickHouse ask to process query up to  with_mergeable_state* stage.

```
  --stage arg (=complete)                                                              Request query processing up to specified stage: complete,fetch_columns,with_mergeable_state,with_mergeable_state_after_aggregation,with_mergeable_state_after_aggregation_and_limit
  --distributed_group_by_no_merge arg                                                  If 1, Do not merge aggregation states from different servers for distributed queries (shards will process query up to the Complete stage, initiator just proxies the data from the shards). If 2 the initiator will apply ORDER BY and LIMIT stages (it is not in case when shard process query up to the Complete stage)
```

**Comment by alexey-milovidov** [comment]
The query displayed in the `query_log` is accurate. It is exactly the query that was sent.
We are just asking the remote server to run it up to a specific stage.
