### ISSUE TITLE
How to use ClickHouse client to target a specific shard?

### ISSUE THREAD

**Issue by BenjaminSalah** [ClickHouse/ClickHouse#42945]
I have a 3 shard/3 replica cluster and i am using the clickhouse client to do file inserts into a local table. How i target a specific shard for inserts and queries? When i insert and then query, the data may not be there because i may be querying a different shard of the table. I do not want to use a distributed table.

**Comment by helifu** [comment]
I'm confused why you use 3 shards and don't want to use a distributed table 😲

**Comment by BenjaminSalah** [comment]
We were running into an issue with using two distributed tables together. To unblock us short term we wanted to create a local dimensions table and use that with our distributed fact table. The issue with that is what i mentioned above. I managed to find another similar question that should resolve my issue:
https://github.com/ClickHouse/ClickHouse/issues/40013
