### ISSUE TITLE
Inconsistent Debian Package Manifest and Missing Binaries from package.clickhouse.com

### ISSUE THREAD

**Issue by muzammilar** [ClickHouse/ClickHouse#42942]
**Installation type**
Package

Missing package.
HTTP 404 (Not Found) for https://packages.clickhouse.com/deb/pool/main/c/clickhouse/clickhouse-common-static-dbg_22.3.14.23_amd64.deb

According to the manifest here https://packages.clickhouse.com/deb/dists/stable/main/binary-amd64/Packages the debian should be available.

After following the instructions from the the installation setup

**Expected result**
Being able to download the binary.

What you expected

**The actual result**

HTTP 404 - Not Found.

```bash
root@d7e4ce21dbd6:/# apt-get install clickhouse-common-static-dbg=22.3.14.23
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
clickhouse-common-static-dbg
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 797 MB of archives.
After this operation, 944 MB of additional disk space will be used.
Err:1 https://packages.clickhouse.com/deb stable/main amd64 clickhouse-common-static-dbg amd64 22.3.14.23
404  Not Found [IP: 172.66.43.7 443]
E: Failed to fetch https://packages.clickhouse.com/deb/pool/main/c/clickhouse/clickhouse-common-static-dbg_22.3.14.23_amd64.deb  404  Not Found [IP: 172.66.43.7 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?  
```

**How to reproduce**

* In a Ubuntu 20.04 machine, try running ` apt-get install clickhouse-common-static-dbg=22.3.14.23 `

**Comment by cangyin** [comment]
similar issue #42920

**Comment by muzammilar** [comment]
The issues might be similar, however, the packages and manifest mentioned in #42920 are available in the upstream mirror here: https://packages.clickhouse.com/deb/pool/main/c/clickhouse/
https://packages.clickhouse.com/deb/dists/stable/main/binary-amd64/Packages

However, the manifest for `clickhouse-common-static-dbg=22.3.14.23` is there but the package is missing, There is a entry for it in the [Packages cache](https://packages.clickhouse.com/deb/dists/stable/main/binary-amd64/Packages) but the package is missing from the location specified.

**Comment by cangyin** [comment]
By stating these two issue as 'similar', I mean, they're both caused by 'Inconsisten package metadata', as what you stated.

Am I doing something wrong for you?

**Comment by muzammilar** [comment]
If you look at the `Filename` section here `https://packages.clickhouse.com/deb/dists/stable/main/binary-amd64/Packages`, you can actually get the path of the package. In #42920 , the path does indeed exist now (so that issue was likely fixed - or is difficult to reproduce). The path of the package in this case *does not* exist (and it's simpler to reproduce).

**Comment by cangyin** [comment]
When metadata is not well mantained, it's meaningless to differ a single link address from another.

**Comment by Felixoid** [comment]
@cangyin the issue is not related to https://github.com/ClickHouse/ClickHouse/issues/42920, since there's an outdated apt/dpkg state on the user's end.

The issue here is in our repo, and I'll fix it ASAP

**Comment by Felixoid** [comment]
The package is restored, thanks for the report

**Comment by cangyin** [comment]
Sorry for linking a non-related issue which looks similar. Just that I had encountered an issue in telegram group, in which case link addresses in package manifest were incorect by simple browsing. I empirically considered all three issue as related.

**Comment by Felixoid** [comment]
No problem, the linked issue is related to migration from jfrog artifactory to self-managed repositories, so some cache on the user-end must be cleaned manually.

We updated the Troubleshooting page, so [one](https://clickhouse.com/docs/en/operations/troubleshooting/#you-cannot-update-deb-packages-from-clickhouse-repository-with-apt-get) and [another](https://clickhouse.com/docs/en/operations/troubleshooting/#you-get-different-warnings-with-apt-get-update) part of it can be referenced to solve issues
