### ISSUE TITLE
Consider dropping StringRef from the codebase

### ISSUE THREAD

**Issue by Algunenano** [ClickHouse/ClickHouse#42958]
While investigating https://github.com/ClickHouse/ClickHouse/issues/42916 I've stumbled many times with `StringRef` used in different context without being clear what their intent is.

Do they own the data? AFAIK, never
Are they always strings? Some are, some aren't
Are the strings null terminated? Some are, some aren't.

I understand this class was added a long time ago (10 years!) just to be used in hash tables, avoiding the need of creating strings which requires copying data around. But today's C++ already has better classes for that, like `std::string_view` which some parts of the code are using and `StringRef` has gained some compatibility / transformations to and from it.

I think removing this class in favor of `std::string_view`, if possible, would be a net positive and help simplify the code. Any thoughts?

**Comment by alexey-milovidov** [comment]
@Algunenano let's remove it, but keep the usages of the default hash function and the operator ==.
