### ISSUE TITLE
How to dock rabbitmq

### ISSUE THREAD

**Issue by jdAction** [ClickHouse/ClickHouse#42953]
rabbitmq 
username root username 
password>clickhouse <password
 rabbitmq
 This information should be put in that configuration file
 Not explicitly stated in the documentation
 I'm using Docker container deployment, does the latest version support rabbitmq?

**Comment by kssenii** [comment]
> Not explicitly stated in the documentation

Actually it is:

<img width="525" alt="Screenshot 2022-11-04 at 12 32 09" src="https://user-images.githubusercontent.com/54203879/199962775-95a8c6b2-c5a2-48fb-a45a-dc2c65219c92.png">

> I'm using Docker container deployment, does the latest version support rabbitmq?

yes

**Comment by jdAction** [comment]
I know the documentation, but it doesn't say whether to write to that config, config.xml or create a new file?

**Comment by jdAction** [comment]
> > Not explicitly stated in the documentation
> 
> Actually it is:
> 
> (https://clickhouse.com/docs/en/engines/table-engines/integrations/rabbitmq/) <img alt="Screenshot 2022-11-04 at 12 32 09" width="525" src="https://user-images.githubusercontent.com/54203879/199962775-95a8c6b2-c5a2-48fb-a45a-dc2c65219c92.png">
> 
> > I'm using Docker container deployment, does the latest version support rabbitmq?
> 
> yes

I know the documentation, but it doesn't say whether to write to that config, config.xml or create a new file?

**Comment by jdAction** [comment]
What version does docker containers support rabbitmq? Here is my mirror information yandex/clickhouse-server latest d846490c0466 10 months ago 794MB
