### ISSUE TITLE
Is there any setting to limit a single user from creating too many connections?

### ISSUE THREAD

**Issue by cangyin** [ClickHouse/ClickHouse#42975]
Recently we encountered a suspicious attack. Some clickhouse servers in our cluster received over 4000 connections (tcp and http connections summed up, where `max_connections=4096`) during a short period of time, thus the attacked servers are not able to handle `ping` connections from K8S health probe, and the 'unhealthy pods' will be killed and restarted, causing cluster partial failures.

Some server logs:
```sh
# kubectl logs chi-node-1-0 -c clickhouse-server -p | grep -v "business" | grep "Got exception while starting thread for connection" -C 100
Got exception while starting thread for connection. Error code: 0, message: 'No thread available'
Got exception while starting thread for connection. Error code: 0, message: 'No thread available'
Got exception while starting thread for connection. Error code: 0, message: 'No thread available'
Got exception while starting thread for connection. Error code: 0, message: 'No thread available'
2022.11.03 18:46:59.338329 [ 36 ] {} <Information> Application: Received termination signal (Terminated)
2022.11.03 18:47:00.056151 [ 1 ] {} <Information> Application: Closed all listening sockets. Waiting for 4082 outstanding connections.
...
```

So, is there any setting to limit too many connections from a single user or address?

**Comment by DerekChia** [comment]
This should be done by a proxy. Something like chproxy (https://github.com/ContentSquare/chproxy) could help. Look into:
- https://www.chproxy.org/configuration/users
- https://www.chproxy.org/configuration/security

**Comment by cangyin** [comment]
Thanks. We are using a customized version of chproxy.

**Comment by thomoco** [comment]
Could also use USER or ROLE quotas in ClickHouse:
https://clickhouse.com/docs/en/sql-reference/statements/create/quota
