### ISSUE TITLE
Questions about proper use of PROJECTION

### ISSUE THREAD

**Issue by canhld94** [ClickHouse/ClickHouse#42996]
Hi, I have some questions about PROJECTION:

- According to the [doc](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/mergetree/#projection-storage),   if there is an ORDER BY clause, the MergeTree table uses it as its primary key expression. If we don't have ORDER BY, does the MergeTree table of the projection use the same primary key as origin table?
- Can we change the index_granularity of projection parts?
- While selecting the best projection, the logic is to estimate number of marks to be read and select the projection with lowest total marks. But to estimate number of marks, we need to run mark ranges filtering from key conditions. We found that for some big tables, running mark ranges filtering is costly. Can we have a more efficient ways to select projection? Also can we add some code to handle some cases (e.g. if there's only 1 candidate we can just choose that candidate).

Thank you.
cc @amosbird

**Comment by canhld94** [comment]
> > If we don't have ORDER BY, does the MergeTree table of the projection use the same primary key as origin table?
> 
> Nope, there will be no primary key for projection parts.
> 
@amosbird thanks for your answer. So it means if we create a projection with no `ORDER BY`, during selecting projections, it shouldn't scan the index of that projection, right? But from my testing, it will still scan the index of projections w/o ORDER BY.
Reproduce:
```sql
CREATE TABLE ad_mock
(
    `vid` UInt64,
    `click_cost` Nullable(Float64),
    `ad_score` Nullable(Int64),
    `count` Nullable(UInt64),
    PROJECTION mv_ad_mock
    (
        SELECT
            sum(click_cost),
            sum(ad_score),
            sum(count)
        GROUP BY vid
    )
)
ENGINE = MergeTree
ORDER BY vid
SAMPLE BY vid
SETTINGS index_granularity = 8192;

INSERT INTO ad_mock SELECT
    number * 2,
    1.5 * (number / 2),
    1.5 * (number / 3),
    3 * number
FROM numbers(10000);

INSERT INTO ad_mock SELECT
    number,
    1. * (number / 2),
    1. * (number / 3),
    2 * number
FROM numbers(1000);

SELECT
    vid,
    sum(ad_score)
FROM ad_mock
WHERE vid > 1000
GROUP BY vid
FORMAT `Null`
SETTINGS allow_experimental_projection_optimization = 1;
```

Check the logs, it still scan the index for projection `mv_ad_mock`. Note that it will also scan the index of origin, so for a simple query, we have 2 index scanning (potentially redundant jobs) during projection analysis.
```
2022.11.08 11:22:00.076784 [ 1059547 ] {26a2cc20-da96-4fb0-adc4-a5397c8c22fb} <Debug> default.ad_mock (620eb305-f8a4-420e-a073-3fa51fa2d96c) (SelectExecutor): Key condition: (column 0 in [1001, +Inf))
2022.11.08 11:22:00.076872 [ 1049878 ] {26a2cc20-da96-4fb0-adc4-a5397c8c22fb} <Trace> default.ad_mock (620eb305-f8a4-420e-a073-3fa51fa2d96c) (SelectExecutor): Running binary search on index range for part mv_ad_mock (2 marks)
2022.11.08 11:22:00.076871 [ 1049920 ] {26a2cc20-da96-4fb0-adc4-a5397c8c22fb} <Trace> default.ad_mock (620eb305-f8a4-420e-a073-3fa51fa2d96c) (SelectExecutor): Running binary search on index range for part mv_ad_mock (2 marks)
2022.11.08 11:22:00.076895 [ 1049878 ] {26a2cc20-da96-4fb0-adc4-a5397c8c22fb} <Trace> default.ad_mock (620eb305-f8a4-420e-a073-3fa51fa2d96c) (SelectExecutor): Found (LEFT) boundary mark: 1
2022.11.08 11:22:00.076916 [ 1049878 ] {26a2cc20-da96-4fb0-adc4-a5397c8c22fb} <Trace> default.ad_mock (620eb305-f8a4-420e-a073-3fa51fa2d96c) (SelectExecutor): Found (RIGHT) boundary mark: 2
2022.11.08 11:22:00.076923 [ 1049878 ] {26a2cc20-da96-4fb0-adc4-a5397c8c22fb} <Trace> default.ad_mock (620eb305-f8a4-420e-a073-3fa51fa2d96c) (SelectExecutor): Found empty range in 1 steps
2022.11.08 11:22:00.076919 [ 1049920 ] {26a2cc20-da96-4fb0-adc4-a5397c8c22fb} <Trace> default.ad_mock (620eb305-f8a4-420e-a073-3fa51fa2d96c) (SelectExecutor): Found (LEFT) boundary mark: 0
2022.11.08 11:22:00.076939 [ 1049920 ] {26a2cc20-da96-4fb0-adc4-a5397c8c22fb} <Trace> default.ad_mock (620eb305-f8a4-420e-a073-3fa51fa2d96c) (SelectExecutor): Found (RIGHT) boundary mark: 2
2022.11.08 11:22:00.076947 [ 1049920 ] {26a2cc20-da96-4fb0-adc4-a5397c8c22fb} <Trace> default.ad_mock (620eb305-f8a4-420e-a073-3fa51fa2d96c) (SelectExecutor): Found continuous range in 2 steps
```
Thanks!

**Comment by amosbird** [comment]
> But from my testing, it will still scan the index of projections w/o ORDER BY.

Because you have specified `GROUP BY vid` which makes `vid` the primary key of projection `mv_ad_mock`.

**Comment by canhld94** [comment]
> > But from my testing, it will still scan the index of projections w/o ORDER BY.
> 
> Because you have specified `GROUP BY vid` which makes `vid` the primary key of projection `mv_ad_mock`.

Thanks, I did some tests and confirm that with aggregation projections, default primary keys are group by keys.

Have no more question, I will close this issue.
