### ISSUE TITLE
Clickhouse deadlock in table startup if background schedule pool is too small

### ISSUE THREAD

**Issue by jorisgio** [ClickHouse/ClickHouse#42992]
Clickhouse version : 22.10.1.1
Background schedule pool size was set to 96, back then it was an increase other the default, but that might be the reason as it is now 128. 
The instance has 498 tables, and deadlocks while trying to finalize table startup, there was 103 tasks for Replicated mergeTree stuck in ReplicatedMergeTreeAttachThread : waiting here https://github.com/ClickHouse/ClickHouse/blob/9ac829d4c4beee74f3e11da2b9c16e0ac0399066/src/Storages/StorageReplicatedMergeTree.cpp#L4221
```
#2  __pthread_cond_wait (cond=0x7f248e516620, mutex=0x7f248e5165f8) at pthread_cond_wait.c:638
#3  0x0000000016629961 in Poco::EventImpl::waitImpl (this=0x7f248e5165f0)
    at ./contrib/poco/Foundation/src/Event_POSIX.cpp:106
#4  0x0000000012f0e1db in Poco::Event::wait (this=0x7f248e516648)
    at ./contrib/poco/Foundation/include/Poco/Event.h:97
#5  DB::StorageReplicatedMergeTree::startupImpl (this=0x7f248e515820)
    at ./src/Storages/StorageReplicatedMergeTree.cpp:4225
#6  0x000000001345115a in DB::ReplicatedMergeTreeAttachThread::finalizeInitialization (this=0x7f248e5168e8)
    at ./src/Storages/MergeTree/ReplicatedMergeTreeAttachThread.cpp:190
#7  0x000000001344e53e in DB::ReplicatedMergeTreeAttachThread::run (this=0x7f248e5168e8)
    at ./src/Storages/MergeTree/ReplicatedMergeTreeAttachThread.cpp:51
 ```
 Increasing background_schedule_pool_size to 256 allows the server to start, as the task were stuck in queue leading to a deadlock. 
 I'm not sure there is something to fix here, but this was hard to troubleshoot.

**Comment by tavplubix** [comment]
There's a small chance it's related to https://github.com/ClickHouse/ClickHouse/issues/42262 (but it's unlikely)

I have no ideas how small size of pool could lead to deadlock like this. Is it reproducible? Could you please provide full stacktraces of all threads? 
```
gdb -ex 'set pagination off' -ex "set logging file gdb.log" -ex 'set logging on' -ex 'backtrace' -ex 'thread apply all backtrace' -ex 'backtrace' --pid `pidof clickhouse-server`
```

**Comment by jorisgio** [comment]
It is not reproductible right now apparently, i tried a couple times this week. I didn't get a full trace like this unfortunately when it happened. One thing to note is that it happened on sunday night and so the replica stayed down a couple of hours, so the replication queue backlog was quite big, many thousands entries on all replicated tables, i'm not sure it plays a role.

**Comment by tavplubix** [comment]
Continued in https://github.com/ClickHouse/ClickHouse/issues/49962
