### ISSUE TITLE
Problem with clearing space

### ISSUE THREAD

**Issue by pbakadm** [ClickHouse/ClickHouse#42993]
Hi!

**Describe the unexpected behaviour**
I am clearing ClickHouse from unneeded data and I see that it's stuck on: 

Code: 243, e.displayText() = DB::Exception: Cannot reserve 2.52 GiB, not enough space (version 20.8.2.3 (official build))

There are available space:

SELECT *
FROM system.disks

┌─name────┬─path─────────────────┬──free_space─┬──total_space─┬─keep_free_space─┬─type──┐
│ default │ /var/lib/clickhouse/ │ 76935184384 │ 708046954496 │               0 │ local │
└─────────┴──────────────────────┴─────────────┴──────────────┴─────────────────┴───────┘

ClickHouse version: 20.8.2.3

**How to reproduce**
Just do some DELETE and every time we see that error. 

**Expected behavior**
Clear data :)

I was searching this error, but nothing found, can you please help me to sort this out?

Regards

**Comment by pbakadm** [comment]
Hi!

Any ideas?

Regards

**Comment by nickitat** [comment]
No ideas so far
