### ISSUE TITLE
FREEZE PARTITION says 'Ok' but fails

### ISSUE THREAD

**Issue by vasyaabr** [ClickHouse/ClickHouse#4300]
**Describe the bug**
After executing FREEZE PARTITION, no `/var/lib/clickhouse/shadow` exists on server, but clickhouse-client replies with 'Ok' (operation successfull). Executing same FREEZE PARTITION again reply with `DB::Exception: Detached partition 201901 already exists.. `

* ClickHouse server version 18.14.11
* Using quorum write

**Expected behavior**
Created partition hardlinks in `/var/lib/clickhouse/shadow`, or error message with description of problem.

**Error message and/or stacktrace**
Server log with error:
> 2019.02.06 15:56:06.637641 [ 131323 ] {6ea7f034-ef37-487b-9114-71e18645d215} <Debug> executeQuery: (from 10.100.20.23:35766) ALTER TABLE funprodwh.Turnovers FETCH PARTITION '201901' FROM '/clickhouse/tables/funprodwh/Turnovers'
> 2019.02.06 15:56:06.638824 [ 131323 ] {6ea7f034-ef37-487b-9114-71e18645d215} <Information> funprodwh.Turnovers (StorageReplicatedMergeTree): Will fetch partition 201901 from shard /clickhouse/tables/funprodwh/Turnovers
> 2019.02.06 15:56:06.650627 [ 131323 ] {6ea7f034-ef37-487b-9114-71e18645d215} <Information> funprodwh.Turnovers (StorageReplicatedMergeTree): Found 3 replicas, 3 of them are active. Selected site2-deac-dwh-cas3 to fetch from.
> 2019.02.06 15:56:06.651887 [ 131323 ] {6ea7f034-ef37-487b-9114-71e18645d215} <Information> funprodwh.Turnovers (StorageReplicatedMergeTree): Parts to fetch: 16
> 2019.02.06 15:56:06.651931 [ 131323 ] {6ea7f034-ef37-487b-9114-71e18645d215} <Debug> funprodwh.Turnovers (StorageReplicatedMergeTree): Fetching part 20190101_20190119_0_10925_6_9186 from /clickhouse/tables/funprodwh/Turnovers/replicas/site2-deac-dwh-cas3
> 2019.02.06 15:56:06.652878 [ 131323 ] {6ea7f034-ef37-487b-9114-71e18645d215} <Trace> funprodwh.Turnovers (StorageReplicatedMergeTree): Found local part 20190101_20190119_0_10925_6_9186 with the same checksums as 20190101_20190119_0_10925_6_9186
> 2019.02.06 15:56:06.653395 [ 131323 ] {6ea7f034-ef37-487b-9114-71e18645d215} <Debug> funprodwh.Turnovers (Data): Cloning part /var/lib/clickhouse/data/funprodwh/Turnovers/20190101_20190119_0_10925_6_9186/ to /var/lib/clickhouse/data/funprodwh/Turnovers/tmp_clone_20190101_20190119_0_10925_6_9186
> 2019.02.06 15:56:06.770074 [ 131323 ] {6ea7f034-ef37-487b-9114-71e18645d215} <Debug> funprodwh.Turnovers (StorageReplicatedMergeTree): Cloned part 20190101_20190119_0_10925_6_9186 from 20190101_20190119_0_10925_6_9186 (to 'detached' directory)
> 2019.02.06 15:56:06.770119 [ 131323 ] {6ea7f034-ef37-487b-9114-71e18645d215} <Error> funprodwh.Turnovers (Data): ~DataPart() should remove part /var/lib/clickhouse/data/funprodwh/Turnovers/detached/20190101_20190119_0_10925_6_9186/ but its name doesn't start with tmp. Too suspicious, keeping the part.

**Comment by alexey-milovidov** [comment]
You have mistakenly execute FETCH PARTITION instead of FREEZE PARTITION.
