### ISSUE TITLE
Urgent: after change IP adress for cluster, all the server cannot be started

### ISSUE THREAD

**Issue by taotaizhu-pw** [ClickHouse/ClickHouse#43028]
We publish our project to production enviroment from pre-prod. The three clickhouse servers would change the IP addresses (keep the same physical servers).

Clickhouse Version: 22.3.6.5
we used clickhouse-keeper

Steps:

1. stop each clickhouse server
2. update config.xml: (1) keeper_server->raft_configuration->hostname (2) interserver_http_host
3. update metrika.xml: (1) clickhouse_remote_servers->shard->replica->host (2) macros->replica (3) zookeeper-servers->node->host
4. start clickhouse serve

the server cannot be started. We fould the keep still use the old IP adrees to connect. The server would down after retry 70 times.

waring: RaftInstance: failed to send prevote request: peer3 (xxx.xxx.xxx.xxx, it is old IP) is busy

**Comment by den-crane** [comment]
https://clickhouse.com/docs/en/operations/clickhouse-keeper/#recovering-after-losing-quorum

**Comment by den-crane** [comment]
try restart several times. Keeper stores configuration in a snapshot, because of that it tries to connect to the old address.

**Comment by taotaizhu-pw** [comment]
> try restart several times. Keeper stores configuration in a snapshot, because of that it tries to connect to the old address.

Thanks, after restart 100 rounds in  30 minutes, it works!!!

**Comment by taotaizhu-pw** [comment]
> try restart several times. Keeper stores configuration in a snapshot, because of that it tries to connect to the old address.

After your suggestion, we restart server in several time, the servers were been started.

But, we found all the table are in readonly mode, how to fix it?

after restart servers, still readonly status

![image](https://user-images.githubusercontent.com/79344970/201063684-0dc1fcd8-8d8e-44e9-941d-7305173e7ab5.png)

**Comment by taotaizhu-pw** [comment]
any reply? thanks

**Comment by antonio2368** [comment]
Keeper stores cluster information in the Raft logs used for consistency. Because of that reason, there isn't a way to reconfigure a cluster without a quorum and without force-recovery.

If you can start cluster on old IPs you should be able to remove nodes and add them on new address **1 by 1.**
Hostnames are stored as is, if you write IP that will be stored making it hard to use if it's constantly changed. For future uses maybe using hostnames would be a better options and changing hostname -> IP address mapping on changes.

**Comment by taotaizhu-pw** [comment]
can i drop the cluster database and restore it？&nbsp;
we backup the database by clickhouse-backup before change ip



---Original---
From: "Antonio ***@***.***&gt;
Date: Mon, Nov 14, 2022 01:23 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ClickHouse/ClickHouse] Urgent: after change IP adress forcluster, all the server cannot be started (Issue #43028)




 
Keeper stores cluster information in the Raft logs used for consistency. Because of that reason, there isn't a way to reconfigure a cluster without a quorum and without force-recovery.
 
If you can start cluster on old IPs you should be able to remove nodes and add them on new address 1 by 1.
 Hostnames are stored as is, if you write IP that will be stored making it hard to use if it's constantly changed. For future uses maybe using hostnames would be a better options and changing hostname -&gt; IP address mapping on changes.

**Comment by antonio2368** [comment]
Not sure how that would help, readonly error happens if it cannot connect to ZK cluster.
In your case, Keeper cannot achieve quorum because of the old IPs meaning it cannot accept connections.

**Comment by antonio2368** [comment]
One option is to backup all Keeper data (`coordination` folder) and start clean Keeper cluster.
After that you should be able to restore metadata in Keeper with https://clickhouse.com/docs/en/sql-reference/statements/system/#restore-replica

**Comment by taotaizhu-pw** [comment]
what's the correct operation order？ it seems there are several steps. we are in prod env， cannot try to test :(



---Original---
From: "Antonio ***@***.***&gt;
Date: Mon, Nov 14, 2022 01:49 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ClickHouse/ClickHouse] Urgent: after change IP adress forcluster, all the server cannot be started (Issue #43028)




 
One option is to backup all Keeper data (coordination folder) and start clean Keeper cluster.
 After that you should be able to restore metadata in Keeper with https://clickhouse.com/docs/en/sql-reference/statements/system/#restore-replica

**Comment by antonio2368** [comment]
1. Stop cluster
2. Backup files in `/var/lib/clickhouse/coordination` folder if the default paths are used.
3. Delete all files in `coordination` folder.
4. Start cluster
5. Run `SYSTEM RESTORE REPLICA table_name ON CLUSTER cluster_name;`

**Comment by taotaizhu-pw** [comment]
got，thanks，we would try！



---Original---
From: "Antonio ***@***.***&gt;
Date: Mon, Nov 14, 2022 02:04 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ClickHouse/ClickHouse] Urgent: after change IP adress forcluster, all the server cannot be started (Issue #43028)




  
Stop cluster
 
Backup files in /var/lib/clickhouse/coordination folder if the default paths are used.
 
Delete all files in coordination folder.
 
Start cluster
 
Run SYSTEM RESTORE REPLICA table_name ON CLUSTER cluster_name;

**Comment by taotaizhu-pw** [comment]
thanks，work fine



---Original---
From: "Antonio ***@***.***&gt;
Date: Mon, Nov 14, 2022 02:04 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ClickHouse/ClickHouse] Urgent: after change IP adress forcluster, all the server cannot be started (Issue #43028)




  
Stop cluster
 
Backup files in /var/lib/clickhouse/coordination folder if the default paths are used.
 
Delete all files in coordination folder.
 
Start cluster
 
Run SYSTEM RESTORE REPLICA table_name ON CLUSTER cluster_name;
