### ISSUE TITLE
Readonly not working as documented

### ISSUE THREAD

**Issue by dbanda** [ClickHouse/ClickHouse#43068]
The docs say "[readonly](https://clickhouse.com/docs/en/operations/settings/permissions-for-queries/#settings_readonly) — Restricts permissions for all types of queries except DDL queries"

But if I do:

```
SET readonly=2
SET allow_ddl=1
create table test_ddl (id String) engine = Merge('default', 'test_ddl' )
```

I get : 

`Code: 164. DB::Exception: Received from localhost:9000. DB::Exception: default: Cannot execute query in readonly mode. (READONLY)`

what's the correct way to allow executing DDL queries in readonly mode? The docs say readonly should not restrict DDL queries.

**Comment by genzgd** [comment]
The docs on `readonly` don't say anything at all about DDL queries, but it's reasonable to assume that a readonly user wouldn't have to ability to create tables.  Regardless, there is no way to execute DDL queries if readonly is not `0`.

**Comment by genzgd** [comment]
Also, this is fairly clear:

```
1 — Only read data queries are allowed.
2 — Read data and change settings queries are allowed.
```

**Comment by dbanda** [comment]
Ok thanks for the quick response. I think what tripped me up was "all queries except DDL queries" part. To me this implied setting readonly would still allow running DDL queries.

**Comment by genzgd** [comment]
Ah, I see the confusion.  The interaction between `readonly` and `allow_ddl` is not well explained.

**Comment by tavplubix** [comment]
> The docs on readonly don't say anything at all about DDL queries

It says:
https://github.com/ClickHouse/ClickHouse/blob/899bf99d44cae2e89c3ee9170d066186f29cd98f/docs/en/operations/settings/permissions-for-queries.md?plain=1#L17-L20

So yes, this part of documentation is incorrect/outdated

**Comment by dbanda** [comment]
I think it would be sufficient to drop the except "except DDL queries" clause. This is more accurate `-   [readonly](#settings_readonly) — Restricts permissions for all types of queries.` and makes is clear that readonly overrides 'allow_ddl'
