### ISSUE TITLE
Grant privileges on nested views to role doesn't work

### ISSUE THREAD

**Issue by ustas0** [ClickHouse/ClickHouse#43079]
> You have to provide the following information whenever possible.

Version 22.8.5.29 in docker image
I have MyView1 and MyView2. And I created MyViewSummary as ...MyView1 LEFT JOIN MyView2...
Next,
GRANT SELECT ON ...MyViewSummary TO my_role;
I have a data_user with my_role.
SELECT * from MyViewSummary; -  gives me an error (ACCESS_DENIED) ... to MyView1 - It's OK!

GRANT SELECT ON ...MyView1 TO my_role;
GRANT SELECT ON ...MyView2 TO my_role;

But the same error raised!!!
And MyView1, MyView2 doesn't appears in list of views in DBeaver.

Next,
GRANT SELECT ON ...MyView1 TO data_user;
GRANT SELECT ON ...MyView2 TO data_user;

SELECT * from MyViewSummary; - It's working!!!

It seems so strange if the role have access to views and user in this role cannot use this views.

**Comment by den-crane** [comment]
by design https://github.com/ClickHouse/ClickHouse/issues/19228
