### ISSUE TITLE
after change ip and reastart server, the tables are in readonly mode(clickhouse-keeper 22.3.6.5)

### ISSUE THREAD

**Issue by taotaizhu-pw** [ClickHouse/ClickHouse#43109]
After chang IP for the cluster (clickhouse-keeper 22.3.6.5) to publish production env, the server still used the old ip address. After your suggestion, we restart server in several time, the servers were been started.
Today, we found all the table are in readonly mode, how to fix it?

![image](https://user-images.githubusercontent.com/79344970/200998164-cb90a281-ce9c-40d9-988e-dd3f9812208d.png)

**Comment by taotaizhu-pw** [comment]
after restart servers, still readonly status

**Comment by taotaizhu-pw** [comment]
any reply? thanks

**Comment by Algunenano** [comment]
If this happen to you, check the logs looking for the first error. The tables being on readonly are a consequence of other errors (no communication with keeper, invalid metadata, etc).
