### ISSUE TITLE
Drop column lead to 'Missing columns' bug with projections

### ISSUE THREAD

**Issue by sdk2** [ClickHouse/ClickHouse#43107]
ClickHouse Version 22.11.1.1

`CREATE TABLE test
(
    col1 Int64,
    dt Date
)
ENGINE = MergeTree
PARTITION BY dt
ORDER BY tuple()`

Ok.
0 rows in set. Elapsed: 0.055 sec.

`INSERT INTO test FORMAT Values (1, today())`

Ok.
1 row in set. Elapsed: 0.033 sec.

`ALTER TABLE test ADD COLUMN col2 String`

Ok.
0 rows in set. Elapsed: 0.007 sec.

`ALTER TABLE test
    ADD PROJECTION p1
    (
        SELECT
            col2,
            sum(col1)
        GROUP BY col2
    )`

Ok.
0 rows in set. Elapsed: 0.017 sec.

`ALTER TABLE test
    ADD COLUMN col3 String`

Ok.
0 rows in set. Elapsed: 0.010 sec.

`ALTER TABLE test
    DROP COLUMN col3`

0 rows in set. Elapsed: 0.044 sec.
Received exception from server (version 22.11.1):
Code: 341. DB::Exception: Received from 127.0.0.1:9000. DB::Exception: Exception happened during execution of mutation 'mutation_2.txt' with part '20221110_1_1_0' reason: 'Code: 47. DB::Exception: Missing columns: 'col2' while processing query: 'SELECT col2, sum(col1) GROUP BY col2', required columns: 'col2' 'col1' 'col2' 'col1'. (UNKNOWN_IDENTIFIER) (version 22.11.1.1)'. This error maybe retryable or not. In case of unretryable error, mutation can be killed with KILL MUTATION query. (UNFINISHED)

**Comment by amosbird** [comment]
This only affects Compact parts. Any mutation will materialize all indices/projections in Compact part, which breaks certain assumption of projection calculation. Will investigate.

**Comment by sandeeppnaik** [comment]
Experiencing this on 23.1.5 too. ( Projections were added when on 22.8)..

**Comment by amosbird** [comment]
This is a common bug among both skip indices and projections. 

```
DROP TABLE IF EXISTS test;

CREATE TABLE test ( col1 Int64, dt Date ) ENGINE = MergeTree PARTITION BY dt ORDER BY tuple();

INSERT INTO test FORMAT Values (1, today());

ALTER TABLE test ADD COLUMN col2 String;

ALTER TABLE test ADD INDEX i1 (col1, col2) TYPE set(100) GRANULARITY 1;

ALTER TABLE test MATERIALIZE INDEX i1;

ALTER TABLE test ADD COLUMN col3 String;

ALTER TABLE test DROP COLUMN col3;
```

The root cause is that the mutation interpreter doesn't add column dependencies for `DROP_COLUMN` action, but when mutating compact parts, we'll always re-materialize all indices and projections. Will try to fix it soon.

**Comment by den-crane** [comment]
related https://github.com/ClickHouse/ClickHouse/issues/47549
