### ISSUE TITLE
Nullable primary key bug

### ISSUE THREAD

**Issue by caoyang10** [ClickHouse/ClickHouse#43111]
I find a bug with primary key which use nullable datatype.
reproduce:

CREATE TABLE default.test_table
(
    `A` Nullable(String),
    `B` Nullable(String)
)
ENGINE = MergeTree()
PARTITION BY tuple()
ORDER BY (A,B)
SETTINGS index_granularity = 1, allow_nullable_key=1

insert into default.test_table values ('a', 'b'), ('a', null), (null, 'b')

select count() from default.test_table where B is null;

The correct value is 1, but it returns 0.

**Comment by canhld94** [comment]
May related #29528

**Comment by amosbird** [comment]
> May related #29528

Yes. It's related.
