### ISSUE TITLE
Sampling on view on AggregatingMergeTree  not working

### ISSUE THREAD

**Issue by dsr301** [ClickHouse/ClickHouse#4315]
We have a view created on top of AggregatingMergeTree.
We have noticed that sampling works on AggregatingMergeTree  queries but not with the views.

Sample query below:
> select count (*) from (select mainkey  from data_view  where parkey>=4035225266123964424 and parkey<=4107001385185181704 and  mainkey>=4035225266123964434 and mainkey<=4107282859893456914 )

    count without sample: 91 M (scanned 99 M)
    count with sample 0.01: 91 M (scanned 99 M)

For the same filters, below are stats for datatable AggregatingMergeTree:

    count without sample: 99 M (scanned 99 M)
    count with sample 0.01: 0.9M (scanned 99 M)

DDL for the above view and Table:

```
CREATE MATERIALIZED VIEW datatable (
  parkey UInt64,
  mainkey UInt64,
  rsrp AggregateFunction(minIf, Float32, UInt8),
  rsrq AggregateFunction(minIf, Float32, UInt8),
) ENGINE = AggregatingMergeTree PARTITION BY parkey
ORDER BY
  (mainkey, intHash64(mainkey)) SAMPLE BY intHash64(mainkey) SETTINGS index_granularity = 8192

```

```
CREATE VIEW data_view (
  parkey UInt64,
  mainkey UInt64,
  rsrp Float32,
  rsrq Float32
) AS
SELECT
  parkey,
  mainkey,
  minIfMerge(rsrp) AS rsrp,
  minIfMerge(rsrq) AS rsrq,
FROM
  data
GROUP BY
  parkey,
  mainkey
```

**Comment by TH-HA** [comment]
Hello , is there any workaround to this bug ? 
Thanks in advance.

**Comment by alexey-milovidov** [comment]
According to the documentation, sampling works only for tables of MergeTree family.
I change the category of this task to "feature".

**Comment by larry-cdn77** [comment]
👍
