### ISSUE TITLE
CI/integration test: incorrect reference to file with sanitizer report

### ISSUE THREAD

**Issue by devcrafter** [ClickHouse/ClickHouse#43168]
https://s3.amazonaws.com/clickhouse-test-reports/43122/c00f71327a3eb7f90a58b42adaaa980a6b731f73/integration_tests__tsan__[2/4].html

Test `test_merge_tree_s3/test.py::test_table_manipulations[node]` log contains reference to sanitizer report (https://s3.amazonaws.com/clickhouse-test-reports/43122/c00f71327a3eb7f90a58b42adaaa980a6b731f73/integration_tests__tsan__[2/4]/integration_run_parallel2_0.log):
```
        if sanitizer_assert_instance is not None:
>           raise Exception(
                "Sanitizer assert found in {} for instance {}".format(
                    self.docker_logs_path, sanitizer_assert_instance
                )
            )
E           Exception: Sanitizer assert found in /ClickHouse/tests/integration/test_merge_tree_s3/_instances_gw0_0/docker.log for instance ==================
E           ==================
```
Corresponding archive https://s3.amazonaws.com/clickhouse-test-reports/43122/c00f71327a3eb7f90a58b42adaaa980a6b731f73/integration_tests__tsan__[2/4]/integration_run_parallel2_0.tar.gz 
contains file `test_merge_tree_s3/_instances_gw0_0/docker.log` but there is no sanitizer report there:
```
Attaching to roottestmergetrees3_node_with_limited_disk_1, roottestmergetrees3_node_1, roottestmergetrees3_minio1_1, roottestmergetrees3_resolver_1, roottestmergetrees3_proxy1_1, roottestmergetrees3_proxy2_1
[36mminio1_1                  |[0m WARNING: MINIO_ACCESS_KEY and MINIO_SECRET_KEY are deprecated.
[36mminio1_1                  |[0m          Please use MINIO_ROOT_USER and MINIO_ROOT_PASSWORD
...
[36;1mresolver_1                |[0m Python 3.11.0 (main, Oct 26 2022, 03:01:09) [GCC 10.2.1 20210110] on linux
[36;1mresolver_1                |[0m Type "help", "copyright", "credits" or "license" for more information.
```

The actual sanitizer report I found in `test_merge_tree_s3/_instances_gw0_0/node/logs/stderr.log`, see https://pastila.nl/?00395d9b/85845abd55decd656e90e1d59a436ea1

**Comment by alexey-milovidov** [comment]
This issue is too old.
