### ISSUE TITLE
Clickhouse client

### ISSUE THREAD

**Issue by sridhard** [ClickHouse/ClickHouse#43177]
Hi,
I am new to OLAP DB and I have one basic question.

If we see OLTP DBs like mysql, they have a well defined frameworks like RubyOnRails which handles DB connectivity, maintains schemas, provide framework for DB migrations and also provide abstract query using activeRecord. Similarly we can use graphQL to query only the required data.

For clickhouse to get performance we need to tune the queries. For example to join tables we need to filter the data first and then join. Similarly there are many optimisations.

So when using clickhouse what is the recommended client to use? or we need to directly write raw queries? I think writing raw queries is not maintainable. Pls tell me your suggestion. 

Mainly I want to know how other people use clickhouse. Whether they write raw queries ?

Thanks

**Comment by alexey-milovidov** [comment]
Writing SQL queries is usually the best option.

**Comment by sridhard** [comment]
thanks

**Comment by mshustov** [comment]
> Mainly I want to know how other people use clickhouse. Whether they write raw queries ?

Cliskhouse doesn't provide official ORM or GraphQL tools, but you can find a few open-source solutions that could be used in your favorite programming language https://clickhouse.com/docs/en/interfaces/third-party/client-libraries/
