### ISSUE TITLE
Replace `kssenii/nginx-test` with `clickhouse/nginx-test`

### ISSUE THREAD

**Issue by tavplubix** [ClickHouse/ClickHouse#43182]
See https://github.com/ClickHouse/ClickHouse/pull/25251#discussion_r1019477363

**Comment by nikitamikhaylov** [comment]
@kssenii Probably you can try to remember it using the description of layers https://hub.docker.com/layers/kssenii/nginx-test/1.1/images/sha256-b11260329a6398caf564a8b0df332c39cb5e2b697d968af4a847a2be22ab6d51?context=explore

**Comment by Felixoid** [comment]
I think, I've found a source of the base image for this image, should be https://github.com/Andarius/nginx-upload/blob/00ff0a5ae2bc0c44169cba2dd74751237c6a1477/Dockerfile

@kssenii do you think, it was the source for it, and then you've changed something?

**Comment by kssenii** [comment]
I am not sure if it was the base, it was 2 years ago, so I do not remember.
