### ISSUE TITLE
MongoDB connection timeout (Mongo 5 and CH 22.10.2)

### ISSUE THREAD

**Issue by KirillKulakow** [ClickHouse/ClickHouse#43181]
Hello
I`m created on server two instance: MongoDB version 5 and Clickhouse(Server) version 22.10.2

After Create table
`CREATE TABLE default.languages ( short_code String, title String ) ENGINE = MongoDB(...)`

 I cant get response from query 
`SELECT count() FROM default.languages`
GET error: `DB::Exception: Timeout: connect timed out: 45.76.39.203:27019. (POCO_EXCEPTION)`

Trace logs:
`<Error> executeQuery: Poco::Exception. Code: 1000, e.code() = 0, Timeout: connect timed out: 45.76.39.203:27019 (version 22.10.2.11 (official build)) (from 127.0.0.1:59396) (in query: SELECT count() FROM default.languages;), Stack trace (when copying this message, always include the lines below):

0. Poco::Net::SocketImpl::connect(Poco::Net::SocketAddress const&, Poco::Timespan const&) @ 0x1635c479 in /usr/bin/clickhouse
1. DB::StorageMongoDBSocketFactory::createSocket(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, Poco::Timespan, bool) @ 0x12ce12a0 in /usr/bin/clickhouse
2. Poco::MongoDB::Connection::connect(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Poco::MongoDB::Connection::SocketFactory&) @ 0x162167dd in /usr/bin/clickhouse
3. Poco::MongoDB::Connection::Connection(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Poco::MongoDB::Connection::SocketFactory&) @ 0x16215f52 in /usr/bin/clickhouse
4. DB::StorageMongoDB::connectIfNotConnected() @ 0x12cdc958 in /usr/bin/clickhouse
5. DB::StorageMongoDB::read(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageSnapshot> const&, DB::SelectQueryInfo&, std::__1::shared_ptr<DB::Context const>, DB::QueryProcessingStage::Enum, unsigned long, unsigned long) @ 0x12cdd02c in /usr/bin/clickhouse
6. DB::IStorage::read(DB::QueryPlan&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageSnapshot> const&, DB::SelectQueryInfo&, std::__1::shared_ptr<DB::Context const>, DB::QueryProcessingStage::Enum, unsigned long, unsigned long) @ 0x12bec508 in /usr/bin/clickhouse
7. DB::InterpreterSelectQuery::executeFetchColumns(DB::QueryProcessingStage::Enum, DB::QueryPlan&) @ 0x125ecfee in /usr/bin/clickhouse
8. DB::InterpreterSelectQuery::executeImpl(DB::QueryPlan&, std::__1::optional<DB::Pipe>) @ 0x125e0b81 in /usr/bin/clickhouse
9. DB::InterpreterSelectQuery::buildQueryPlan(DB::QueryPlan&) @ 0x125dfcad in /usr/bin/clickhouse
10. DB::InterpreterSelectWithUnionQuery::buildQueryPlan(DB::QueryPlan&) @ 0x12673663 in /usr/bin/clickhouse
11. DB::InterpreterSelectWithUnionQuery::execute() @ 0x126748d7 in /usr/bin/clickhouse
12. ? @ 0x1297994b in /usr/bin/clickhouse
13. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x12976c0d in /usr/bin/clickhouse
14. DB::TCPHandler::runImpl() @ 0x1353dd04 in /usr/bin/clickhouse
15. DB::TCPHandler::run() @ 0x13551cf9 in /usr/bin/clickhouse
16. Poco::Net::TCPServerConnection::start() @ 0x1636274f in /usr/bin/clickhouse
17. Poco::Net::TCPServerDispatcher::run() @ 0x16364adb in /usr/bin/clickhouse
18. Poco::PooledThread::run() @ 0x16520372 in /usr/bin/clickhouse
19. Poco::ThreadImpl::runnableEntry(void*) @ 0x1651dafd in /usr/bin/clickhouse
20. ? @ 0x7f82684e1609 in ?
21. __clone @ 0x7f8268406133 in ?

0 rows in set. Elapsed: 20.073 sec. 

Received exception from server (version 22.10.2):
Code: 1000. DB::Exception: Received from localhost:9000. DB::Exception: Timeout: connect timed out: 45.76.39.203:27019. (POCO_EXCEPTION)`

<img width="1762" alt="Screenshot 2022-11-11 at 17 47 54" src="https://user-images.githubusercontent.com/53854091/201376147-3e30d7a4-ba59-4999-abc6-5413a2215c01.png">

**Comment by alexey-milovidov** [comment]
First, need to check network connectivity.
It can be done with the following command:
```
telnet 45.76.39.203 27019
```
You should check it on the server with clickhouse-server (inside the container if clickhouse-server is containerized).

**Comment by alexey-milovidov** [comment]
Maybe the timeout is too small. See https://github.com/ClickHouse/ClickHouse/issues/30836#issuecomment-963847832 for the solution.
