### ISSUE TITLE
The specified key does not exist in Stress Tests after BC check

### ISSUE THREAD

**Issue by novikd** [ClickHouse/ClickHouse#43183]
```
<Error> test_31.concurrent_mutate_mt_1: while loading part all_4_4_0_45 on path data/test_31/concurrent_mutate_mt_1/all_4_4_0_45: Code: 499. DB::Exception: The specified key does not exist.: while reading key: test/ers/gavqzbswzekfvjboqbdvrzcfhryim, from bucket: test. (S3_ERROR), Stack trace (when copying this message, always include the lines below):
<Error> test_31.concurrent_mutate_mt_1: Detaching broken part /var/lib/clickhouse/disks/s3/data/test_31/concurrent_mutate_mt_1/all_4_4_0_45 (size: 502.00 B). If it happened after update, it is likely because of backward incompatibility. You need to resolve this manually
```

https://s3.amazonaws.com/clickhouse-test-reports/43105/fe283af82bf7d168710440d69d28b4b6d5dbd194/stress_test__asan_.html

https://s3.amazonaws.com/clickhouse-test-reports/43105/fe283af82bf7d168710440d69d28b4b6d5dbd194/stress_test__msan_.html

https://s3.amazonaws.com/clickhouse-test-reports/43105/fe283af82bf7d168710440d69d28b4b6d5dbd194/stress_test__tsan_.html

**Comment by tavplubix** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/45449/20ebbd99b1094dd1047f20453862471def5ee2f3/stress_test__ubsan_.html

**Comment by alexey-milovidov** [comment]
Duplicate of #48474.
