### ISSUE TITLE
Unable to create remote PG table over PG view with empty array

### ISSUE THREAD

**Issue by yoavo-datricks** [ClickHouse/ClickHouse#43197]
When trying to create a table over a remote PG view with an array column, If the view is empty the CH remote creation fails with

td::exception. Code: 1001, type: pqxx::conversion_error, e.what() = Attempt to convert null to i. (version 22.10.1.1877 (official build))

**How to reproduce**

***Execute in PG***

CREATE TABLE test_remote (
	id int4 NOT NULL,	
	test_arr _int8 NULL,
	CONSTRAINT test_remote_pkey PRIMARY KEY (id)
);

CREATE VIEW test_remote_view AS SELECT * FROM test_remote;

***Execute in CH*** 
**This will fail**
create table test_remote_ch as postgresql (
	logical_remote_pg,
	table = 'test_remote'
)

**Execute in PG**

INSERT INTO test_remote (id,test_arr) VALUES
	 (1,'{0}');

And now the remote table in CH will work

* Which ClickHouse server version to use: 22.10
* Which PostgreSQL server version to use: 13.9

**Expected behavior**
This should work even on empty views

**Comment by kssenii** [comment]
The same issue https://github.com/ClickHouse/ClickHouse/issues/43186. I'll close this issue as it is a duplicate.
