### ISSUE TITLE
"date_sub" working as described?

### ISSUE THREAD

**Issue by tfrokt** [ClickHouse/ClickHouse#43205]
Afai can see, this should be working according to the [docs](https://clickhouse.com/docs/en/sql-reference/functions/date-time-functions/#date_sub).

**Query:**
```
select date_sub('day', 1, toDate('2022-01-01'));
```

```
Received exception from server:
Code: 42. DB::Exception: Number of arguments for function minus doesn't match: passed 3, should be 2: While processing minus('day', 1, toDate('2022-01-01')). (NUMBER_OF_ARGUMENTS_DOESNT_MATCH) (version 22.8.4.7 (official build))
```

**Comment by tfrokt** [comment]
Same behaviour for [timestamp_sub](https://clickhouse.com/docs/en/sql-reference/functions/date-time-functions/#timestamp_sub).

```
Query:
select timestamp_sub('day', 1, now());


Received exception from server:
Code: 42. DB::Exception: Number of arguments for function minus doesn't match: passed 3, should be 2: While processing minus('day', 1, now()). (NUMBER_OF_ARGUMENTS_DOESNT_MATCH) (version 22.8.4.7 (official build))
```

**Comment by den-crane** [comment]
`unit` is a literal `day` not a `String` `'day'`

```sql
select timestamp_sub(day, 1, now());
┌─minus(now(), toIntervalDay(1))─┐
│            2022-11-13 01:22:05 │
└────────────────────────────────┘
```

**Comment by tfrokt** [comment]
https://clickhouse.com/docs/en/sql-reference/functions/date-time-functions/#date_sub
unit — The type of interval to subtract. String <- that's confusing then

value — Value of interval to subtract. Int.
3 = Int

date — The date or date with time from which value is subtracted. Date or DateTime.
toDate(), now() yep, makes it a Date or DateTime

but DAY is not a String, 'DAY' is.

Maybe this should be Constant or Literal instead?
