### ISSUE TITLE
Exception on select after power failure

### ISSUE THREAD

**Issue by hitrow** [ClickHouse/ClickHouse#43223]
Hi 
I can't select the table after power failure.

> :) select * from default.spm_data order by inserted;
> 
> SELECT *
> FROM default.spm_data
> ORDER BY inserted ASC
> 
> Query id: 4060e6b4-8407-42b6-8f55-46d4386e7039
> 
> 
> 0 rows in set. Elapsed: 3.147 sec. 
> 
> Received exception from server (version 22.2.2):
> Code: 271. DB::Exception: Received from localhost:9000. DB::Exception: Data compressed with different methods, given method byte 0x00, previous method byte 0x82: while reading column mac at /var/lib/clickhouse/store/a51/a5187d27-4215-4ac2-80e4-85159f582f0c/: While executing Log. (CANNOT_DECOMPRESS)
> 

Please let me know how to recover this?
Thanks

**Comment by den-crane** [comment]
run using clickhouse-client

```
SET check_query_single_value_result = 0;
CHECK TABLE default.spm_data;
```

**Comment by den-crane** [comment]
22.2.2 is obsolete. You should upgrade to LTS 22.3 , 22.8 or 22.10

**Comment by hitrow** [comment]
> 22.2.2 is obsolete. You should upgrade to LTS 22.3 , 22.8 or 22.10

Clickhouse is running on ubuntu 18.04. Version 22.2.2 is the latest on http://repo.yandex.ru/clickhouse/deb/stable/main.

Please send me repository that has latest LTS version.

Thanks

**Comment by hkrutzer** [comment]
https://clickhouse.com/docs/en/install#install-from-deb-packages

**Comment by hitrow** [comment]
I upgraded to Clickhouse 22.10.2.
But still can't select to the table.

> :) SET check_query_single_value_result = 0;
> 
> SET check_query_single_value_result = 0
> 
> Query id: 09bfa09c-9bb4-44b1-8669-cfde21bed650
> 
> Ok.
> 
> 0 rows in set. Elapsed: 0.002 sec. 
> 
> :) CHECK TABLE default.spm_data;
> 
> CHECK TABLE default.spm_data
> 
> Query id: d933c970-cee0-4d40-b60e-6bb0c41c5574
> 
> ┌─part_path────┬─is_passed─┬─message─┐
> │ __marks.mrk  │         1 │         │
> │ amp.bin      │         1 │         │
> │ day.bin      │         1 │         │
> │ hz.bin       │         1 │         │
> │ inserted.bin │         1 │         │
> │ kvarh.bin    │         1 │         │
> │ kwh1.bin     │         1 │         │
> │ kwh2.bin     │         1 │         │
> │ mac.bin      │         1 │         │
> │ md.bin       │         1 │         │
> │ month.bin    │         1 │         │
> │ pf.bin       │         1 │         │
> │ volt.bin     │         1 │         │
> │ watt1.bin    │         1 │         │
> │ watt2.bin    │         1 │         │
> │ week.bin     │         1 │         │
> │ x1.bin       │         1 │         │
> │ x2.bin       │         1 │         │
> │ year.bin     │         1 │         │
> └──────────────┴───────────┴─────────┘
> 
> 19 rows in set. Elapsed: 0.002 sec. 
> 
> :)  select * from default.spm_data order by inserted;
> 
> SELECT *
> FROM default.spm_data
> ORDER BY inserted ASC
> 
> Query id: 8b71cb2c-efae-4053-9062-0d90007fc646
> 
> 
> 0 rows in set. Elapsed: 0.066 sec. 
> 
> Received exception from server (version 22.10.2):
> Code: 271. DB::Exception: Received from localhost:9000. DB::Exception: Data compressed with different methods, given method byte 0x00, previous method byte 0x82: while reading column mac at /var/lib/clickhouse/store/a51/a5187d27-4215-4ac2-80e4-85159f582f0c/: While executing Log. (CANNOT_DECOMPRESS)
>

**Comment by den-crane** [comment]
Please share `show create table  default.spm_data`

**Comment by hitrow** [comment]
> Please share `show create table default.spm_data`

Please find create table command below.

```
CREATE TABLE spm_data (
    mac FixedString(17),
    inserted DateTime,
    day UInt32,
    week UInt32,
    month UInt32,
    year Int32,
    volt Float64,
    amp Float64, 
    watt1 Float64, 
    watt2 Float64, 
    pf Float64, 
    x1 Float64, 
    hz Float64, 
    kwh1 Float64, 
    kvarh Float64, 
    kwh2 Float64,
    x2 Float64, 
    md Float64
) ENGINE = Log;
```

**Comment by den-crane** [comment]
It's expected. Engine Log tables are not durable and cannot be used as a permanent storage.
https://clickhouse.com/docs/en/engines/table-engines/log-family/log/
