### ISSUE TITLE
How to delete a backup?

### ISSUE THREAD

**Issue by sebw91** [ClickHouse/ClickHouse#43225]
I've been following the documentation for backup and restore of individual tables here: https://clickhouse.com/docs/en/manage/backups/

I don't see anything about purging old backups though. Is there a way of deleting backups? I'm backing up using S3 disk.

Thanks

**Comment by e-mars** [comment]
If you are using `BACKUP ... TO S3(...` .  There's currently no command to remove them using ClickHouse SQL.  
to remove them, remove the folder specified from S3 outside ClickHouse with either the S3 interface or using the aws cli.
Please submit an enhancement request, if this functionality is something you'd like to see in ClickHouse. 

cc: @vitlibar @alexey-milovidov

**Comment by sebw91** [comment]
Thanks @e-mars 

I'm using BACKUP TABLE ... TO Disk('s3_disk', ...)

It would be great to have a DELETE BACKUP Disk('s3_disk', ... ). I can't figure out which files in S3 correspond to which backup, so it's hard to delete manually. Also an unlimited backup policy in S3 will get expensive quickly..

**Comment by e-mars** [comment]
I see.  I would recommend a naming convention for the folder use to store the backup rather than the simple example provided, something like:
`BACKUP TABLE data TO S3('https://mars-doc-test.s3.amazonaws.com/backup-S3/<date_time>', 'ABC123', 'Abc+123')`

In the folder directory for the backup, there is a metadata file (`.backup`) that will contain the timestamp of the backup:
`<config>
	<version>1</version>
	<timestamp>2022-10-25 17:20:31</timestamp>
`
Also, if the node has not been restarted, there is an ephemeral table that will contain some info on the backup, you can use something like this:
```
clickhouse :) sSELECT * FROM system.backups FORMAT Vertical;

SELECT *
FROM system.backups
FORMAT Vertical

Query id: 3e3b28e7-9fcd-4e5a-9192-d03a3bfa3fe9

Row 1:
──────
id:                cbc3111d-3fef-47a7-be21-8d6cfe54c247
name:              S3('https://mars-doc-test.s3.amazonaws.com/backup-S3/cloud_backup', 'ABC123', 'Abc+123')
status:            BACKUP_CREATED
num_files:         9
uncompressed_size: 1914
compressed_size:   1914
error:
start_time:        2022-11-04 16:17:17
end_time:          2022-11-04 16:17:20

```

thanks.

**Comment by sebw91** [comment]
Thank you for the recommendation! I will do something along those lines then.

I will have 7 s3 disks for backup, one for every day of the week with their own directory in the same bucket:
/backup_0, /backup_1, etc.

I'll purge the directory before each daily backup, aside from sunday directory that I'll copy as the weekly backup.. and again for monthlies. A bit complex, I would've liked to control everything using clickhouse commands. Maybe I can work on this feature.
