### ISSUE TITLE
Getting curl: (52) Empty reply from server

### ISSUE THREAD

**Issue by uzairbureau** [ClickHouse/ClickHouse#43243]
Hi Team when executing below mentioned curl I am getting Empty reply from server error. I am using Clickhouse Cloud for Mumbai Region.

Curl Request:
curl -vvv --user 'user:password' --data-binary 'SELECT 1' https://cq32z7lmc5.ap-south-1.aws.clickhouse.cloud:8443

*   Trying 43.204.6.248:8443...
* Connected to cq32z7lmc5.ap-south-1.aws.clickhouse.cloud (43.204.6.248) port 8443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS header, Finished (20):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.2 (OUT), TLS header, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=ap-south-1.aws.clickhouse.cloud
*  start date: Nov 13 10:57:24 2022 GMT
*  expire date: Feb 11 10:57:23 2023 GMT
*  subjectAltName: host "cq32z7lmc5.ap-south-1.aws.clickhouse.cloud" matched cert's "*.ap-south-1.aws.clickhouse.cloud"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Server auth using Basic with user 'default'
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
> POST / HTTP/1.1
> Host: cq32z7lmc5.ap-south-1.aws.clickhouse.cloud:8443
> Authorization: Basic ZGVmYXVsdDpJYVBVb3dDcXp1UVo=
> User-Agent: curl/7.81.0
> Accept: */*
> Content-Length: 8
> Content-Type: application/x-www-form-urlencoded
>
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS alert, close notify (256):
* Empty reply from server
* Closing connection 0
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.3 (OUT), TLS alert, close notify (256):
curl: (52) Empty reply from server

**Comment by bianpengyuan** [comment]
Hi @uzairbureau thanks for reporting! Based on error message it is very likely that your call is blocked by IP allowlist checking. Looks like you've already adjusted the IP allowlist and service should be reachable now.

Let us know if you still have problem. Thanks!
