### ISSUE TITLE
AST Fuzzer finalizeAggregation AggregateFunctionMinMaxAny::read

### ISSUE THREAD

**Issue by CheSema** [ClickHouse/ClickHouse#43247]
(you don't have to strictly follow this form)

**Describe the bug**
Read incorrect data fails with UB checks.

**How to reproduce**
Build with -DSANITIZE=undefined and call request:
```
SELECT finalizeAggregation(CAST('AggregateFunction(categoricalInformationValue, Nullable(UInt8), UInt8)AggregateFunction(categoricalInformationValue, Nullable(UInt8), UInt8)', 'AggregateFunction(min, String)'))
```

**Error message and/or stacktrace**
```
../src/Common/Arena.h:144:13: runtime error: addition of unsigned offset to 0x7f22e8ecd480 overflowed to 0x7f2268ecd480 Received signal -3 Received signal Unknown signal (-3)
```

https://s3.amazonaws.com/clickhouse-test-reports/43159/ee1a1d852d6c92c4a0ff6345b30815537551a07b/fuzzer_astfuzzerubsan//report.html

<details>
<summary><b>StackTrace</b></summary>

```
2022.11.15 12:12:57.098159 [ 465270 ] {} <Fatal> BaseDaemon: 1. ./build-ubsan2/./src/Daemon/BaseDaemon.cpp:0: sanitizerDeathCallback() @ 0x20bfa696 in /home/ubuntu/work/ClickHouse/build-ubsan2/programs/clickhouse
2022.11.15 12:12:58.000175 [ 465217 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 1009.17 MiB, peak 1.04 GiB, free memory in arenas 0.00 B, will set to 1.45 GiB (RSS), difference: 473.56 MiB
2022.11.15 12:12:58.055424 [ 465270 ] {} <Fatal> BaseDaemon: 2. __sanitizer::Die() @ 0x1647c216 in /home/ubuntu/work/ClickHouse/build-ubsan2/programs/clickhouse
2022.11.15 12:12:58.990138 [ 465270 ] {} <Fatal> BaseDaemon: 3. ? @ 0x1648f973 in /home/ubuntu/work/ClickHouse/build-ubsan2/programs/clickhouse
2022.11.15 12:12:59.926332 [ 465270 ] {} <Fatal> BaseDaemon: 4. DB::Arena::alloc(unsigned long) @ 0x16bde6f3 in /home/ubuntu/work/ClickHouse/build-ubsan2/programs/clickhouse
2022.11.15 12:13:00.070144 [ 465270 ] {} <Fatal> BaseDaemon: 5. ./build-ubsan2/./src/AggregateFunctions/AggregateFunctionMinMaxAny.h:526: DB::SingleValueDataString::read(DB::ReadBuffer&, DB::ISerialization const&, DB::Arena*) @ 0x225772a0 in /home/ubuntu/work/ClickHouse/build-ubsan2/programs/clickhouse
2022.11.15 12:13:00.079025 [ 465270 ] {} <Fatal> BaseDaemon: 6. ./build-ubsan2/./src/DataTypes/Serializations/SerializationAggregateFunction.cpp:139: DB::deserializeFromString(std::__1::shared_ptr<DB::IAggregateFunction const> const&, DB::IColumn&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, unsigned long) @ 0x2b0bcecf in /home/ubuntu/work/ClickHouse/build-ubsan2/programs/clickhouse
2022.11.15 12:13:00.087310 [ 465270 ] {} <Fatal> BaseDaemon: 7.1. inlined from ./build-ubsan2/./contrib/libcxx/include/string:1499: std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::__is_long[abi:v15003]() const
2022.11.15 12:13:00.087362 [ 465270 ] {} <Fatal> BaseDaemon: 7.2. inlined from ./build-ubsan2/./contrib/libcxx/include/string:2333: ~basic_string
2022.11.15 12:13:00.087402 [ 465270 ] {} <Fatal> BaseDaemon: 7. ./build-ubsan2/./src/DataTypes/Serializations/SerializationAggregateFunction.cpp:181: DB::SerializationAggregateFunction::deserializeWholeText(DB::IColumn&, DB::ReadBuffer&, DB::FormatSettings const&) const @ 0x2b0bd4e8 in /home/ubuntu/work/ClickHouse/build-ubsan2/programs/clickhouse

```
</details>

What happens:
AggregateFunctionMinMaxAny::read expects to read the data which has been written correctly. There are no checks for correctness in read values.

https://github.com/ClickHouse/ClickHouse/blob/master/src/AggregateFunctions/AggregateFunctionMinMaxAny.h#L507
In this case, rhs_size is read as 1919379265. After it is rounded by roundUpToPowerOfTwoOrZero in 2147483648, this is overflow max(Int32). Therefore capacity become negative -2147483648.  And after that capacity is cast to size_t.

There are at least 2 options to resolve it:
1. Do not allow to cast some random string as a result of AggregateFunction. So reading in AggregateFunction always see only the data which has been written. Not generated by user.
2. Throw exception that could be either about format is invalid or about not enough memory.

**Comment by Algunenano** [comment]
PR here: https://github.com/ClickHouse/ClickHouse/pull/43249

One important thing to keep in mind with all these `CAST` that now the fuzzer knows how to do is that, in most cases (if not all), a similar input could be given in an import (via Native or other format). As long as CH allows importing into a column of that type, these deserialization functions need to be secure.

In any case, the deserialization should be strict and safe even if no malicious input is possible, since there is always the chance of data corruption and so on, and in that case it's better to get a good error and not a crash.
