### ISSUE TITLE
Update zstd 1.5.2 -> 1.5.3

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#43258]
https://github.com/facebook/zstd/blob/dev/CHANGELOG

**Comment by evillique** [comment]
It looks like zstd 1.5.3 was not a public release and therefore we should probably wait for version 1.5.4:
https://github.com/facebook/zstd/pull/3179#issuecomment-1245565667

**Comment by franchb** [comment]
v1.5.4 is ready -- https://github.com/facebook/zstd/releases/tag/v1.5.4
