### ISSUE TITLE
when use ReplicatedSummingMergeTree view  on cluster ,selected sum result is  not unexpected

### ISSUE THREAD

**Issue by WenSteven** [ClickHouse/ClickHouse#43272]
(you don't have to strictly follow this form)

**Describe the unexpected behaviour**

There is a cluster with **two nodes(and more)**, and we create a ReplicatedSummingMergeTree view  on cluster , when select from this view , we get wrong result ( eq right data * 2 )

**How to reproduce**
table is :

```sql
-- create table
CREATE TABLE user_behavior on cluster test_cluster
(
    key String,
    created_at  DateTime
)
ENGINE = ReplicatedMergeTree()
ORDER BY key;
--create view:
CREATE MATERIALIZED VIEW daily_user_behavior_view ON CLUSTER test_cluster
            (
             `key` String,
             `date` Date,
             `pv` UInt32
                )
            ENGINE = ReplicatedSummingMergeTree()
                ORDER BY (key, date)
POPULATE
AS
SELECT key,
       toDate(created_at, 'Asia/Shanghai') AS date,
       1                                   AS pv
FROM user_behavior;

--and insert data to table user_behavior:

INSERT INTO user_behavior values('u1','2022-10-17 01:27:07.000');

```

now ,we execute sql: `select pv from daily_user_behavior_view where key = 'u1'`,  get pv equal 2, expect pv is 1 .

**Comment by den-crane** [comment]
```
<test_cluster>
    <shard>
        <internal_replication>true</internal_replication>
        <replica>
            <host>host1</host>
            <port>9000</port>
        </replica>
    </shard>
    <shard>
        <internal_replication>true</internal_replication>
        <replica>
            <host>host2</host>
            <port>9000</port>
        </replica>
    </shard>
</test_cluster>

```

Have you set `internal_replication=true` ?

**Comment by WenSteven** [comment]
> 

Yes, we has set `internal_replication=true`

**Comment by WenSteven** [comment]
> ```
> <test_cluster>
>     <shard>
>         <internal_replication>true</internal_replication>
>         <replica>
>             <host>host1</host>
>             <port>9000</port>
>         </replica>
>     </shard>
>     <shard>
>         <internal_replication>true</internal_replication>
>         <replica>
>             <host>host2</host>
>             <port>9000</port>
>         </replica>
>     </shard>
> </test_cluster>
> ```
> 
> Have you set `internal_replication=true` ?

Yes,we had set `internal_replication=true`

**Comment by den-crane** [comment]
`ON CLUSTER test_cluster + POPULATE` builds MatView on each replica and each replica executes populate. Try to use without populate https://den-crane.github.io/Everything_you_should_know_about_materialized_views_commented.pdf
