### ISSUE TITLE
Clickhouse website is blank when remote fonts are disabled

### ISSUE THREAD

**Issue by jay** [ClickHouse/ClickHouse#43273]
I could not view https://clickhouse.com/ instead there was a blank page. I narrowed down this issue to remote fonts being disabled by an extension. I can reproduce in Firefox or Chrome. For example:
~~~
"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  --disable-remote-fonts https://clickhouse.com/
~~~

![clickhouse website is blank (animated)](https://user-images.githubusercontent.com/965580/202073199-0572136f-5108-4b5b-ad63-c1f3293d01bd.gif)

**Comment by tavplubix** [comment]
cc: @guykoh

**Comment by Algunenano** [comment]
Works fine now
