### ISSUE TITLE
Storage ReplicatedMergeTree doesn't support FINAL

### ISSUE THREAD

**Issue by p-pekala** [ClickHouse/ClickHouse#43290]
> You have to provide the following information whenever possible.

*Description**

*I try to use FINAL keyword on ReplicatedMergeTree and I get:
 SQL Error [181] [07000]: Code: 181. DB::Exception: Storage ReplicatedMergeTree doesn't support FINAL. (ILLEGAL_FINAL) (version 22.8.8.3 (official build))

**Does it reproduce on recent release?**

Didn't check

**How to reproduce**

* Which ClickHouse server version to use: 22.8.8.3 
* `CREATE TABLE` statements for all tables involved

CREATE TABLE IF NOT EXISTS dema.test (
  `test1`         LowCardinality(String),
  `test2`         LowCardinality(String),
  `test3`         String
) ENGINE ReplicatedMergeTree('/clickhouse/tables/{shard}/dema/test', '{replica}')
ORDER BY (cityHash64(`test1`), `test2`, `test3`);

* Queries to run that lead to unexpected result

select test1, test2, test3 from dema.test final

**Expected behavior**

According to documentation final should be available on ReplicatedMergeTree

**Error message and/or stacktrace**

SQL Error [181] [07000]: Code: 181. DB::Exception: Storage ReplicatedMergeTree doesn't support FINAL. (ILLEGAL_FINAL) (version 22.8.8.3 (official build))

**Comment by den-crane** [comment]
FINAL modifier is not supported (has no sense) for MergeTree  and GraphiteMergeTree.
Someone has changed CH documentation. See the old doc https://github.com/ClickHouse/ClickHouse/blob/fb1b8cf77855abaabe91aba92fc3cafc361a72c3/docs/en/query_language/select.md#from-clause

**Comment by den-crane** [comment]
_The FINAL modifier can be used only for a SELECT from ReplacingMergeTree, SummingMergeTree, AggregatingMergeTree, CollapsingMergeTree and VersionedCollapsingMergeTree tables_

**Comment by blinkov** [comment]
@DanRoscigno fyi

**Comment by filimonov** [comment]
Also confusing comment there: https://clickhouse.com/docs/en/sql-reference/statements/select/from/#final-modifier

**Comment by canhld94** [comment]
> _The FINAL modifier can be used only for a SELECT from ReplacingMergeTree, SummingMergeTree, AggregatingMergeTree, CollapsingMergeTree and VersionedCollapsingMergeTree tables_

I think it also supports `GraphiteMergeTree`, not sure if it's a mistake

https://github.com/ClickHouse/ClickHouse/blob/master/src/Storages/MergeTree/MergeTreeData.cpp#L373
