### ISSUE TITLE
Json parser

### ISSUE THREAD

**Issue by sabinajvdva** [ClickHouse/ClickHouse#43314]
Hi!
I have table with json column (select data from config) with following data: 
 "no_refund": {
      "name": "No refund",
      "comment": "Cancelation of the ticket only, no refund",
      "comment_internal": "This will set booking status to CANCELED."
}

How can I extract values in name, comment and comment_internal?

**Comment by den-crane** [comment]
https://clickhouse.com/docs/en/guides/developer/working-with-json


It's a valid JSON, without surrounding `{ }` ?

```
select x.1, x.2, x.3 from (select $$"no_refund": {
"name": "No refund",
"comment": "Cancelation of the ticket only, no refund",
"comment_internal": "This will set booking status to CANCELED."
}$$ j, JSONExtract('{'||j||'}', 'Tuple(Tuple(name String, comment String, comment_internal String))').1 x);


┌─tupleElement(x, 1)─┬─tupleElement(x, 2)────────────────────────┬─tupleElement(x, 3)────────────────────────┐
│ No refund          │ Cancelation of the ticket only, no refund │ This will set booking status to CANCELED. │
└────────────────────┴───────────────────────────────────────────┴───────────────────────────────────────────┘
```
