### ISSUE TITLE
how to set a lower log level for specific logger.

### ISSUE THREAD

**Issue by etah000** [ClickHouse/ClickHouse#43318]
```
<logger> 
        <level>information</level>
        <levels>
          <logger>
            <name>MemoryTracker</name>
            <level>debug</level>
          </logger>
        </levels>
   </logger>
```
Generally there are too many logs. I want to limit the default log level to "**information**", but set a specific logger level to "**debug**" as the example above. This will be more convinent for problem analysis and we won't be flushed by many unrelated logs. Now it does not support.

**Comment by realyota** [comment]
This is the correct syntax:

```
  <levels>
          <MemoryTracker>debug</MemoryTracker>
  </levels>
```
