### ISSUE TITLE
Function hasToken return incorrect result

### ISSUE THREAD

**Issue by save-my-heart** [ClickHouse/ClickHouse#43358]
**Describe the unexpected behaviour**
Function `hasToken` may return wrong result in some cases.

**How to reproduce**
See: [fiddle](https://fiddle.clickhouse.com/781c4a16-0531-4afd-b6ce-1a0b41e62abf)

**Expected behavior**
In the above case, `hasToken` should return 0.

**Additional context**
When the search text size  >= min_haystack_size_for_algorithm(default 20000), function `hasToken` use Volnitsky algorithm, with a normal fallback token searcher, these may lead to wrong result sometimes. 
Since function `hasToken` treats `ColumnString` as a whole text, so the bug is easily to be reproduced on a normal String column.
Here are some cases I met：
```
:) SELECT path FROM test WHERE  hasToken(path, 'quota');

SELECT path
FROM test
WHERE hasToken(path, 'quota')

Query id: 4630e82c-bcf8-48b9-93e1-2927ac155023

┌─path───────────────┐
│ /api/crm/podsquota │
└────────────────────┘

1 rows in set. Elapsed: 0.090 sec. Processed 851.63 thousand rows, 19.91 MB (9.47 million rows/s., 221.49 MB/s.)

:) set preferred_block_size_bytes = 10000;

SET preferred_block_size_bytes = 10000

Query id: a86af3f8-f046-4e9f-ae77-b9cfdae83422

Ok.

0 rows in set. Elapsed: 0.003 sec.

:) SELECT path FROM test WHERE  hasToken(path, 'quota');

SELECT path
FROM test
WHERE hasToken(path, 'quota')

Query id: 87d4c33c-a8fd-4061-b230-141a42ba1935

┌─path───────────────┐
│ /api/crm/podsquota │
└────────────────────┘
┌─path───────────────┐
│ /api/crm/podsquota │
└────────────────────┘

2 rows in set. Elapsed: 0.081 sec. Processed 851.63 thousand rows, 19.91 MB (10.45 million rows/s., 244.41 MB/s.)

:) set preferred_block_size_bytes = 100000000;

SET preferred_block_size_bytes = 100000000

Query id: f5377329-20b4-4aba-88f8-61fd59c581b0

Ok.

0 rows in set. Elapsed: 0.003 sec.

:) SELECT path FROM test WHERE  hasToken(path, 'quota');

SELECT path
FROM test
WHERE hasToken(path, 'quota')

Query id: bdd9fc6a-6d44-4c8e-bb8a-10f491eb4229

Ok.

0 rows in set. Elapsed: 0.076 sec. Processed 851.63 thousand rows, 19.91 MB (11.24 million rows/s., 262.86 MB/s.)
```

**Comment by fuwhu** [comment]
@Enmk

**Comment by fuwhu** [comment]
@Enmk 
Hi Vasily,

Could you please help take a look at this problem?
We will appreciate so much if you can give us some advice on how to fix it.

**Comment by alexey-milovidov** [comment]
It's fixed.

**Comment by alexey-milovidov** [comment]
It isn't fixed.

**Comment by alexey-milovidov** [comment]
I found the reason. The code was totally wrong and also overly complex (too many templates).
I've removed all the wrong code, and it started to be ok.
