### ISSUE TITLE
Data search requires data conversion.

### ISSUE THREAD

**Issue by lyanantx** [ClickHouse/ClickHouse#43354]
The data type has been defined when the table was created. Why do you need to perform data type conversion again when querying data?

![image](https://user-images.githubusercontent.com/34332907/202627859-3066dd82-5b11-450f-be2f-e46dd4622e55.png)
![image](https://user-images.githubusercontent.com/34332907/202628379-c7db4c44-ead0-4b60-87dc-4e87ce636273.png)
![image](https://user-images.githubusercontent.com/34332907/202628474-0459b058-360c-4e60-879e-3c93188f3839.png)
![image](https://user-images.githubusercontent.com/34332907/202628569-a814b9fd-e744-4aaf-a316-6c138c850e33.png)

**Comment by den-crane** [comment]
Please provide reproducible example using https://fiddle.clickhouse.com/

**Comment by den-crane** [comment]
Please provide 

```sql
select database,table,name,type  from system.columns where name = 'ts';
```

**Comment by lyanantx** [comment]
> ```sql
> select database,table,name,type  from system.columns where name = 'ts';
> ```

![12](https://user-images.githubusercontent.com/34332907/202938389-a18c1088-e2cb-4e7d-82ce-7000fa6dd0ae.png)

20.8.3.18  is no problem

[ts_kv_new_new_202211181043.csv](https://github.com/ClickHouse/ClickHouse/files/10051298/ts_kv_new_new_202211181043.csv)
The attachment csv file is the relevant data that the SQL statement above needs to query. You can test the following

Build table SQL:
CREATE TABLE cosmoiot.ts_kv_new
(
    `entity_id` String,
    `key` Int32,
    `ts` Int64,
    `bool_v` Nullable(UInt8),
    `str_v` Nullable(String),
    `long_v` Nullable(Int64),
    `dbl_v` Nullable(Float64),
    `json_v` Nullable(String)
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(toDate(ts))
PRIMARY KEY (entity_id,
 key,
 ts)
ORDER BY (entity_id,
 key,
 ts)
SETTINGS index_granularity = 8192;

**Comment by lyanantx** [comment]
Hello, has this problem of data type conversion been verified?

**Comment by lyanantx** [comment]
@den-crane Hello, has this problem of data type conversion been verified? Is there any solution?

**Comment by alexey-milovidov** [comment]
If `ts` is Int64, you don't have to convert it `toInt64` - it is redundant.
