### ISSUE TITLE
Support for killing CHECK TABLE operation

### ISSUE THREAD

**Issue by DerekChia** [ClickHouse/ClickHouse#43353]
**Use case**

The [`CHECK TABLE`](https://clickhouse.com/docs/en/sql-reference/statements/check-table/#checking-the-mergetree-family-tables) statement checks if data in the table is corrupted by comparing the actual file sizes with the expected values stored on the server. However, this single-threaded operation can take a long time to complete (and can timeout) if there are many parts stored in slower remote storage like S3 or HDFS. In the event of timeout, this operation is still running in the background there is no way to check its progress or stop (other than KILL QUERY).

**Describe the solution you'd like**

- Support operation like `STOP CHECK TABLE [db.]name` 
- Consider adding number of parts left to check in system.metrics like `PartsToCheckQueueSize`, similar to `TablesToDropQueueSize`

**Describe alternatives you've considered**

- `KILL QUERY WHERE query_id = 'query_id_for_check_table'`

**Comment by alexey-milovidov** [comment]
Low demand for this.
