### ISSUE TITLE
PARTITION BY toDate(some DateTime64 column) breaks partitioning when time zone changes

### ISSUE THREAD

**Issue by socketpair** [ClickHouse/ClickHouse#43399]
I think Clickhouse must require specifying timezone ( `PARTITION BY toDate(xxx, 'UTC')` for example), or remember in metadata timezone at the moment of table creation.

`toDate()` without second argument uses current timezone on the server, so when TZ changes, it affects ranges of timestamps corresponding to each day.

This happens silently and obviously gives wrong results of `select`.

**Comment by UnamedRus** [comment]
It's known problem. (BTW, it affect any DateTime, not only DateTime64)

Right now solutions is:

Do not change timezone of server.
If this change happened, reinsert data, which have wrong partition minmax index.
