### ISSUE TITLE
Code: 999. Coordination::Exception: Connection loss. (KEEPER_EXCEPTION)

### ISSUE THREAD

**Issue by xiaobingxia** [ClickHouse/ClickHouse#43402]
Clickhouse Version: 22.6.2.12.

I have a table which is ReplicatedMergeTree. It used to work well. But recently it starts to have following issue:
When I execute: TRUNCATE TABLE IF EXISTS <table name>, it will report following error message:

Code: 999. Coordination::Exception: Connection loss. (KEEPER_EXCEPTION) (version 22.6.2.12 (official build))

When I execute: ALTER TABLE INSTADATA_ETL.FACT_ORDER_DELIVERY_RETAILER_INSIGHTS_full_local ON CLUSTER replicated_distributed_shards DELETE WHERE 1=1; It will report following error message:

Coordination::Exception. Coordination::Exception: Session expired (Session expired): While executing DDLQueryStatus. (KEEPER_EXCEPTION)

But the interesting thing is: ATTACH/DROP PARTITION to this table still works well.

I have seen this issue more and more often recently. 
Any advices regarding how to resolve this issue is appreciated.

**Comment by m1khal3v** [comment]
Got something like this after updating 22.8.8.3 to 22.8.9.24 when execute SELECT with highload GROUP BY. Init node crashing with 

```
Code: 999. Coordination::Exception: Session expired (Session expired). (KEEPER_EXCEPTION)
```

**Comment by alexey-milovidov** [comment]
It happens if a network connection between ClickHouse and ZooKeeper is interrupted.
It is normal as the network is not 100% reliable and it will resolve automatically.
The client should retry the query.

**Comment by emirkmo** [comment]
If this is an INSERT query, is it safe to retry the specific failing query (with regards to duplicated data). Or do we need to truncate and reingest?
