### ISSUE TITLE
start clickhouse error code=exited,status=233/RUNTIME_DIRECTORY

### ISSUE THREAD

**Issue by luyuanhe** [ClickHouse/ClickHouse#43413]
systemctl status clickhouse-server

![image](https://user-images.githubusercontent.com/28947262/202982505-7ddbacc8-a784-47e3-b52f-c9e5de0a6ff0.png)

journalctl -u clickhouse-server
![image](https://user-images.githubusercontent.com/28947262/202982888-0dddcd82-8048-4df2-b296-f1d83d02321a.png)

**Comment by alexey-milovidov** [comment]
Run it with

```
sudo clickhouse start
```

and read the logs at
```
/var/lib/clickhouse-server/clickhouse-server.log
```

You have an error in your configuration file.

**Comment by luyuanhe** [comment]
Thank you,  directory permissions issue,solved it, 
①、execute the command 【chmod 777 -R /data2】  
②、execute the command 【systemctl start clickhouse-server 】
