### ISSUE TITLE
select countMerge from ReplicatedAggregatingMergeTree ,Get the wrong result.

### ISSUE THREAD

**Issue by sunjiacheng123** [ClickHouse/ClickHouse#43420]
Function: Count the number of logs of instance per minute.
question：In the query statement, the number of total_count counted out is less.Some data are not counted.

The table building statement is as follows:
`CREATE DATABASE IF NOT EXISTS test ON CLUSTER cc_cluster;
-- local MV
CREATE MATERIALIZED VIEW
IF NOT EXISTS
test.sjc_m_log_count_local
ON CLUSTER cc_cluster
ENGINE = ReplicatedAggregatingMergeTree('/clickhouse/tables/{layer}-{shard}/test.sjc_m_log_count_local', '{replica}')
PARTITION BY toYYYYMMDD(timestamp)
ORDER BY (instance_id, timestamp,log_type)
POPULATE
AS 
select
	countState() as total_count,
	instance_id,
	toDateTime(formatDateTime(toDateTime('timestamp'/1000),'%y-%m-%d %H:%M:00')) as timestamp,
	sub_type as log_type
FROM test.sjc_log 
GROUP BY instance_id, timestamp,sub_type;

-- distributed MV
CREATE TABLE IF NOT EXISTS
test.sjc_m_log_count
ON CLUSTER cc_cluster
AS test.sjc_m_log_count_local
ENGINE = Distributed(cc_cluster, test, sjc_m_log_count_local, SipHash64());

-- query
select  
	countMerge(total_count) as total_count,
	instance_id,
	timestamp,
	log_type
FROM test.sjc_m_log_count 
GROUP BY instance_id, timestamp,log_type;`

sjc_log :Distributed table of complete data

**Comment by alexey-milovidov** [comment]
How exactly do you see it is less than expected?

**Comment by den-crane** [comment]
expected behaviour: `ON CLUSTER cc_cluster ... POPULATE` is executed at all nodes. 
POPULATE multiplies number by number of replicas.
