### ISSUE TITLE
change S3 max_connections doesn't work.

### ISSUE THREAD

**Issue by vahid-sohrabloo** [ClickHouse/ClickHouse#43433]
My C++ language is not very good but I think here we have a problem
https://github.com/ClickHouse/ClickHouse/blob/22.11/src/Storages/StorageS3.cpp#L1082-L1093
all settings here only change `max_single_read_retries` it reverted on the master but the release branch has this bug.

**Comment by nickitat** [comment]
we had it for 5 months, unfortunately fix will be delivered only with the next release
