### ISSUE TITLE
mysql table engine can't sync data to MATERIALIZED VIEW  in   22.3.14.23

### ISSUE THREAD

**Issue by xmpx310** [ClickHouse/ClickHouse#43432]
i created a  table 'testck' in clickhouse use table engine mysql  to sync mysql db  table 'testmysql'  data; 
then create a MATERIALIZED VIEW  'testviewck'  with the mysql engin table;
 now i insert data to mysql db table  'testmysql'   ,data was already  sync into  'testck' but not  sync into 'testviewck'

**Comment by zzsmdfj** [comment]
mysql table engine  do not Incremental sync mysql data .  try https://clickhouse.com/docs/en/engines/database-engines/materialized-mysql
