### ISSUE TITLE
how to restore snapshot

### ISSUE THREAD

**Issue by raobilal28** [ClickHouse/ClickHouse#43459]
We can place our snapshots from /var/lib/clickhouse/coordination/snapshots to S3 storage with below block.

        <s3_snapshot>
           <endpoint>http://192.168.110.7:9090/snapshots/</endpoint>
           <access_key_id>admin</access_key_id>
           <secret_access_key>password</secret_access_key>
        </s3_snapshot>

Can you please confirm that if we have this snapshot at s3 then how we can restore it when required.

e.g
I tried by truncating the table and then putting the snapshot taken earlier in the snapshots directory, but it does not restoring the data back.

**Comment by nikitamikhaylov** [comment]
It is a feature of ClickHouse Keeper to offload old snapshots to S3. It has nothing to do with the data stored in ClickHouse. 
For the data please use BACKUP/RESTORE SQL commands: https://clickhouse.com/docs/en/operations/backup
