### ISSUE TITLE
Alias issue in multiIf or case-when-then clause, cause 'DB::Exception: Missing columns: 'XXX' while processing query'

### ISSUE THREAD

**Issue by qmdt** [ClickHouse/ClickHouse#43452]
Hi, when I execute the following SQL, 'DB::Exception: Missing columns: 'XXX' while processing query' occurs
```
SELECT
    b.*,
    multiIf(b.EventDate = '2022-01-01', (
        SELECT ver
        FROM default.tbl_replicated2
        WHERE tbl_replicated2.EventDate = b.EventDate
    ), NULL)
FROM
(
    SELECT a.EventDate AS EventDate
    FROM tbl_replicated AS a
) AS b

Query id: f63c5056-7cd2-436d-b414-c17cb7109b65
0 rows in set. Elapsed: 0.755 sec.

**Received exception from server (version 22.3.2):
Code: 47. DB::Exception: Received from ip:port. DB::Exception: Missing columns: 'b.EventDate' while processing query: 'SELECT ver FROM default.tbl_replicated2 WHERE EventDate = b.EventDate', required columns: 'ver' 'EventDate' 'b.EventDate', maybe you meant: ['ver','EventDate','EventDate']: While processing (SELECT ver FROM default.tbl_replicated2 WHERE tbl_replicated2.EventDate = b.EventDate) AS _subquery34: While processing multiIf(EventDate = '2022-01-01', (SELECT ver FROM default.tbl_replicated2 WHERE tbl_replicated2.EventDate = b.EventDate) AS _subquery34, NULL). (UNKNOWN_IDENTIFIER)**
```

**How to reproduce**
1、 create 2 tables
```
CREATE TABLE default.tbl_replicated
(
    `EventDate` DateTime,
    `CounterID` UInt32,
    `UserID` UInt32,
    `ver` UInt16
)
ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{shard}/tbl_replicated', '{replica}')
ORDER BY (CounterID, EventDate, intHash32(UserID))
SETTINGS index_granularity = 8192
CREATE TABLE default.tbl_replicated2
(
    `EventDate` DateTime,
    `CounterID` UInt32,
    `UserID` UInt32,
    `ver` UInt16
)
ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{shard}/tbl_replicated2', '{replica}')
ORDER BY (CounterID, EventDate, intHash32(UserID))
SETTINGS index_granularity = 8192
```
2、insert 2 tables
3、select with case-when-then clause using alias
```
select b.*,
                 case
                 when b.EventDate = '2022-01-01' then (select ver from default.tbl_replicated2 where tbl_replicated2.EventDate = b.EventDate)
                 else NULL
                 end
                 from(select a.EventDate as EventDate from tbl_replicated a) b;
```

* Which ClickHouse server version to use
 22.3.2.2-lts

**Expected behavior**
when I remove the alias ‘b’，the SQL execute successfully，so I want to know whether alias can not be identified in case-when-then and multiIf clause or not
![image](https://user-images.githubusercontent.com/8369775/203098284-b5aa3a64-96a3-4102-afad-9aa45f01f9d4.png)
![image](https://user-images.githubusercontent.com/8369775/203098593-e4962e9e-8c8f-4b29-9f64-73bd2635a031.png)
![image](https://user-images.githubusercontent.com/8369775/203098846-290fd0b1-67f0-49b9-9679-04cb2ad318dd.png)

**Comment by nickitat** [comment]
correlated subqueries are not supported currently. for now you need to rewrite your query using join

**Comment by qmdt** [comment]
@nickitat ,  thank you for your replay,  I try the following sql without rewrite, it seems the result is also ok

1. alias can be used in cond clause,
2.  but in then clause, the specific column name is used instead of the alias of tables or databases

![image](https://user-images.githubusercontent.com/8369775/203251526-d8a2c55a-e5ac-45f4-9e60-95bef7c8513e.png)

so I think If the table's column name is unique, then this name can be used everywhere in the SQL, not necessary for aliases? right?

**Comment by nickitat** [comment]
I don't think so. could you pls repeat this experiment, but this time prepend table name to column names like `tbl_replicated_EventDate` and `tbl_replicated2_EventDate`. 'cause my understanding is `EventTime` in `WHERE` is just resolved as `tbl_replicated2.EventDate` which is not what we want.
