### ISSUE TITLE
ALTER TABLE ON CLUSTRE UPDATE hangs forever 

### ISSUE THREAD

**Issue by frinkr** [ClickHouse/ClickHouse#43464]
**Version:** 
22.8

We tested the 'ALTER TABLE... UPDATE' sql in a cluster with two replicas (with Clickhouse Keeper), a clickhouse exception (code 1002) will raise after 10 seconds. It seems the there is a DDL never stop running on both replicas, and each replica wants to sync data from the other.

The dataset is small enough (800 rows).

**SQL**
```
ALTER TABLE the_table
ON CLUSTER 'the_cluster' 
UPDATE `the_dst_column` = joinGet(`the_join_table`, 'the_join_column', `the_key_column`) 
WHERE (1)
SETTINGS mutations_sync=1
```

And there are endless errors like:

```
2022.11.22 16:12:00.416673 [ 10826 ] {} <Debug> (ReplicatedMergeTreeQueue): Not executing log entry queue-0000000059 of type MUTATE_PART for part 31_0_0_0_1 because source parts size (4.90 KiB) is greater than the current maximum (0.00 B).

2022.11.22 16:12:34.850000 [ 10782 ] {} <Error> MutateFromLogEntryTask: Code: 40. DB::Exception: Checksums of parts don't match: hash of uncompressed files doesn't match, uncompressed hash of compressed files doesn't match. (CHECKSUM_DOESNT_MATCH) (version 22.8.5.1.318). Data after mutation is not byte-identical to data on another replicas. We will download merged part from replica to force byte-identical result.
```

Thanks.

**Comment by tavplubix** [comment]
> a clickhouse exception (code 1002) will raise after 10 seconds

What exception exactly? Please share exception message and stacktrace.

> It seems the there is a DDL never stop running on both replicas, and each replica wants to sync data from the other.

Why? Please share the logs that are related to the query.

> Checksums of parts don't match

It's expected if the mutation is not deterministic, i.e. if `joinGet` returns different results on replicas.

**Comment by young-scott** [comment]
i've the same problems。
`
path:                                  /home/service/var/clickhouse/data/data/game_center_offline/event_local_data/20221122_108_108_0_127/
hash_of_all_files:                     1f3c4b03c5d582783b6b6778895bb768
hash_of_uncompressed_files:            2da13e336d5723314fb378670cab7aec
uncompressed_hash_of_compressed_files: 2b7228ae92d10c077286d43c6e285f8e
`
the other replicas
`
path:                                  /home/service/var/clickhouse/data/data/game_center_offline/event_local_data/20221122_108_108_0_127/
hash_of_all_files:                     b2c7a23440e33400250e27e6a24aaed0
hash_of_uncompressed_files:            ec8cdaf2500a3dde094a95a07f464f08
uncompressed_hash_of_compressed_files: 11b26e3f65f82b057c9a68c96bcc21a7
`

log :
`
2022.11.24 12:51:54.059111 [ 381741 ] {game_center_offline.event_local_data::20221122_108_108_0_127} <Debug> game_center_offline.event_local_data (SelectExecutor): MinMax index condition: unknown
2022.11.24 12:51:54.059150 [ 381741 ] {game_center_offline.event_local_data::20221122_108_108_0_127} <Debug> game_center_offline.event_local_data (SelectExecutor): Selected 1/1 parts by partition key, 1 parts by primary key, 55/55 marks by primary key, 55 marks to read from 1 ranges
2022.11.24 12:51:54.059259 [ 381741 ] {game_center_offline.event_local_data::20221122_108_108_0_127} <Trace> MergeTreeInOrderSelectProcessor: Reading 1 ranges in order from part 20221122_108_108_0_126, approx. 231226 rows starting from 0
2022.11.24 12:51:54.059280 [ 381741 ] {game_center_offline.event_local_data::20221122_108_108_0_127} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2022.11.24 12:51:54.064634 [ 381874 ] {} <Debug> game_center_offline.event_local_data: There is no part 20221122_108_108_0_127 in ZooKeeper, it was only in filesystem
2022.11.24 12:51:54.068162 [ 381874 ] {} <Debug> game_center_offline.event_local_data: Removing part from filesystem 20221122_108_108_0_127
2022.11.24 12:51:54.112856 [ 381752 ] {game_center_offline.event_local_data::20221122_108_108_0_127} <Trace> game_center_offline.event_local_data: Renaming temporary part tmp_mut_20221122_108_108_0_127 to 20221122_108_108_0_127.
2022.11.24 12:51:54.113582 [ 381752 ] {game_center_offline.event_local_data::20221122_108_108_0_127} <Debug> game_center_offline.event_local_data: Undoing transaction. Removing parts: 20221122_108_108_0_127.
2022.11.24 12:51:54.113616 [ 381752 ] {game_center_offline.event_local_data::20221122_108_108_0_127} <Error> MutateFromLogEntryTask: Code: 40. DB::Exception: Checksums of parts don't match: hash of uncompressed files doesn't match, uncompressed hash of compressed files doesn't match. (CHECKSUM_DOESNT_MATCH) (version 22.3.6.5). Data after mutation is not byte-identical to data on another replicas. We will download merged part from replica to force byte-identical result.
2022.11.24 12:51:54.113653 [ 381752 ] {game_center_offline.event_local_data::20221122_108_108_0_127} <Trace> game_center_offline.event_local_data: Trying to immediately remove part 20221122_108_108_0_127 (state Outdated)
2022.11.24 12:51:54.114689 [ 381752 ] {game_center_offline.event_local_data::20221122_108_108_0_127} <Debug> game_center_offline.event_local_data: Part 20221122_108_108_0_127 should be deleted after previous attempt before fetch
2022.11.24 12:51:54.115226 [ 381732 ] {} <Trace> MutateFromLogEntryTask: Executing log entry to mutate part 20221122_108_108_0_126 to 20221122_108_108_0_127
2022.11.24 12:51:54.116410 [ 381732 ] {game_center_offline.event_local_data::20221122_108_108_0_127} <Debug> game_center_offline.event_local_data (SelectExecutor): Key condition: unknown
`

**Comment by frinkr** [comment]
> It's expected if the mutation is not deterministic, i.e. if joinGet returns different results on replicas.

Excactly. The join table was different on replicas. Thanks for replying.
