### ISSUE TITLE
BUG: where (fingerprint, service_app) IN ('f1b99486524036522d09ae0c9e5e3fe5', 'web') from mysql engine table

### ISSUE THREAD

**Issue by 201430098137** [ClickHouse/ClickHouse#43465]
I have a table analysis_error_fingerprint, this is:
create table analysis_error_fingerprint
(
    fingerprint            String,
    product_id             Nullable(Int64),
    service_app            Nullable(String),
    resolve_version        String,
    status                 Int8,
    last_mark_resolve_time Nullable(DateTime),
    create_time            DateTime,
    update_time            Nullable(DateTime),
    delete_time            Nullable(DateTime),
    env                    String
)
    engine = MySQL('xxx', 'tenant_zaun', 'analysis_error_fingerprint', 'xx', 'xxx');
I execute sql 
```
SELECT *
FROM `tenant_taun`.`log_analysis_error_fingerprint`
WHERE (fingerprint, service_app) IN (('f1b99486524036522d09ae0c9e5e3fe5','web'));
```
this return 
![image](https://user-images.githubusercontent.com/13937318/203269587-e684547b-3829-4b1c-9328-463d57cf7a41.png)

I execute the same sql on the mysql ,this return correct.

I copy the sql returned from the above command line,exeute on the mysql ,  return the same error.
I think sql formatting cause this bug

**Comment by alexey-milovidov** [comment]
This was improved in the latest ClickHouse releases.
