### ISSUE TITLE
How to trigger  In memory part flush to disk with  timeout setting?

### ISSUE THREAD

**Issue by kaynewu** [ClickHouse/ClickHouse#43462]
version: 22.9

CREATE TABLE default.hits
(
    `url` String,
    `hits` UInt32
)
ENGINE = MergeTree
PARTITION BY url
ORDER BY hits
SETTINGS min_rows_for_compact_part = 1024, min_rows_for_wide_part = 81920, in_memory_parts_insert_sync = 1, index_granularity = 8192

insert into default.hits values('www.google.com',1)

if partition 'www.google.com' never insert  records again or can't reach min_rows_for_compact_part ,  in memory part will stay in memory forever? How to make in memory part flush to disk with timeout setting?

In our production environment there is lots of small in memory part stay for days and weeks !
![image](https://user-images.githubusercontent.com/5574794/203456031-531bdeb6-f3bb-413e-bbaa-8998795f073d.png)

**Comment by realyota** [comment]
> if partition 'www.google.com' never insert records again or can't reach min_rows_for_compact_part , in memory part will stay in memory forever?

No, it will be flushed to disk when Clickhouse performs merge.

> How to make in memory part flush to disk with timeout setting?

```
OPTIMIZE TABLE default.hits FINAL;
```

**Comment by kaynewu** [comment]
> > if partition 'www.google.com' never insert records again or can't reach min_rows_for_compact_part , in memory part will stay in memory forever?
> 
> No, it will be flushed to disk when Clickhouse performs merge.
> 
> > How to make in memory part flush to disk with timeout setting?
> 
> ```
> OPTIMIZE TABLE default.hits FINAL;
> ```
@realyota But this is not timeout trigger，This requires new data insert or manual work，this is with additional， what if those condition never happen？

**Comment by UnamedRus** [comment]
What is your experience with in memory parts?
They have really low adoption (and proposed for removal), so it will be interesting to hear. 


* In memory parts
    Not well tested / commonly used.
    Known issues with table ALTERS: [issue](https://github.com/ClickHouse/ClickHouse/issues/17721)
    Being proposed for removal from ClickHouse: [issue](https://github.com/ClickHouse/ClickHouse/issues/42542)

**Comment by kaynewu** [comment]
> 
@UnamedRus 
As a memory cache for small and frequent data write, we consider Buffer table engine first， but there is no write-ahead-log to make sure no data is lost while clickhouse server is crash or shutdown abnormally.
