### ISSUE TITLE
`INSERT INTO T1 SELECT * FROM T2` causes 'Allocator: Cannot mmap 1.0Mib, errorno 12'

### ISSUE THREAD

**Issue by Alex-Cheng** [ClickHouse/ClickHouse#43474]
(you don't have to strictly follow this form)

**Describe the unexpected behaviour**
I have a table T1 which is created by SQL,
```SQL
CREATE TABLE T1 (ID UInt64, case_id Nullable(UInt64), name String)  ENGINE=MergeTree PARTITION BY if(case_id IS NULL, -1, assumeNotNull(case_id) % 32) ORDER BY (assumeNotNull(case_id), ID)
```
and I have another table T2 with same columns and contain 0.2billion rows of data. 

When I run the SQL `INSERT INTO T1 SELECT * FROM T2`, I got an error 'Allocator: Cannot mmap 1.0Mib, errorno 12', but actullay I have enough memory(memory 32GB and the clickhouse processes cost 10G at peak).

I also tried to enlarge the settings `max_memory_usage`, `mark_cache_size`, `max_server_memory_usage`, but not help at all.

version: 22.8.5.x

**Comment by tavplubix** [comment]
This exception simply shows requested size of memory and errno code returned by the kernel:
https://github.com/ClickHouse/ClickHouse/blob/f4a48cd4d6f664a1b41b4162bfeeeb033032b04a/src/Common/Allocator.h#L213-L216

12 is for `ENOMEM`, so the kernel said that you don't have enough memory, and there's nothing ClickHouse can do. 

> but actullay I have enough memory

Maybe there's some memory limit set with ulimit/cgroups/etc or there are not enough memory mapping available (`vm.max_map_count`). Check your system configuration.

**Comment by Alex-Cheng** [comment]
Thank you very much.
