### ISSUE TITLE
Cached reload dictionary used all RAM

### ISSUE THREAD

**Issue by SEDAManzana** [ClickHouse/ClickHouse#43503]
Hi and sorry for my English.
I got the same bug on [39128](https://github.com/ClickHouse/ClickHouse/issues/39128) .
My dictionary when reload uses RAM and falling with error: "Code: 241. DB::Exception: Memory limit (total) exceeded". 
But all RAM used scripts for reloading this dictionary. When i restarted ClickHouse - ram released and dictionary reloading succesfully.

How i can release RAM of cached scripts on reload dictionary without restart CH server?

Dictionary LAYOUT(SPARSE_HASHED()) or LAYOUT(HASHED())

**Comment by SEDAManzana** [comment]
I have two Shards with similar dictionaries. 
In system. dictionaries I see a different "query_count" on two dictionaries.

In Shard1 i have the error "Code: 241. DB::Exception: Memory limit (total) exceeded" and large query_count 
![image](https://user-images.githubusercontent.com/117734616/204297415-f0aafdec-e364-4b66-82a5-2f4e7c5aabca.png)

In Shard2 i have successfull reloaded dict and another query_count .
![image](https://user-images.githubusercontent.com/117734616/204297498-93b7fb91-edd8-4da8-bb13-4509356fa925.png)

What is "query_count" ? It`s a count scripts where used this dictionaries, or count keys on this dictionaries then they reloaded?

Count data in source_dict on two shards are equal.

**Comment by rschu1ze** [comment]
Moved to #23870
