### ISSUE TITLE
Enum toString cannot be filtered by IN properly

### ISSUE THREAD

**Issue by tisonkun** [ClickHouse/ClickHouse#43510]
These two queries are expected to be the same result (dataset = https://play.clickhouse.com/play?user=play), but actually _not_:

```sql
SELECT actor_login,
                    created_at,
                    toString(event_type) AS event_type,
                    toString(action) AS action, number,
                    merged_at
             FROM github_events
             WHERE repo_name = 'apache/pulsar'
               AND event_type IN
                 ('PullRequestEvent'
                 , 'PullRequestReviewCommentEvent'
                 , 'PullRequestReviewEvent'
                 , 'IssueCommentEvent')
               AND actor_login NOT IN ('github-actions[bot]'
                 , 'codecov-commenter')
AND number = 9276
```

gives:

<img width="1726" alt="image" src="https://user-images.githubusercontent.com/18818196/203365958-a7379e4d-a14d-4544-a36d-09c1bb8783be.png">

```sql
SELECT actor_login,
                    created_at,
                    toString(event_type) AS event_type,
                    toString(action) AS action, number,
                    merged_at
             FROM github_events
             WHERE repo_name = 'apache/pulsar'
               AND multiMatchAny(event_type,
                 ['PullRequestEvent'
                 , 'PullRequestReviewCommentEvent'
                 , 'PullRequestReviewEvent'
                 , 'IssueCommentEvent'])
               AND actor_login NOT IN ('github-actions[bot]'
                 , 'codecov-commenter')
AND number = 9276
```

gives:

<img width="1713" alt="image" src="https://user-images.githubusercontent.com/18818196/203366295-d6d6d55a-03f9-4be4-bb86-ab9dfc0849c6.png">

The latter is expected.

cc @alexey-milovidov

**Comment by nickitat** [comment]
more concise example:

``` sql
SELECT *
FROM github_events
WHERE (repo_name = 'apache/pulsar') AND (event_type IN ('PullRequestEvent', 'PullRequestReviewCommentEvent', 'PullRequestReviewEvent', 'IssueCommentEvent')) AND (number = 9276)

16 rows in set. Elapsed: 0.066 sec. Processed 1.09 million rows, 70.64 MB (16.38 million rows/s., 1.07 GB/s.)

SELECT *
FROM github_events
WHERE (repo_name = 'apache/pulsar') AND (toString(event_type) IN ('PullRequestEvent', 'PullRequestReviewCommentEvent', 'PullRequestReviewEvent', 'IssueCommentEvent')) AND (number = 9276)

14 rows in set. Elapsed: 0.070 sec. Processed 1.43 million rows, 77.70 MB (20.42 million rows/s., 1.11 GB/s.)
```

**Comment by tisonkun** [comment]
@nickitat Good to know. Is there a plan to upgrade the playground's (ClickHouse) kernel version?

**Comment by bxb100** [comment]
change `event_type` alias will show 16 results

```sql
SELECT actor_login,
                    created_at,
                    toString(event_type) as eventType,
                    toString(action) AS action, number,
                    merged_at
             FROM github_events
             WHERE repo_name = 'apache/pulsar'
               AND event_type IN
                 ('PullRequestEvent'
                 , 'PullRequestReviewCommentEvent'
                 , 'PullRequestReviewEvent'
                 , 'IssueCommentEvent')
               AND actor_login NOT IN ('github-actions[bot]'
                 , 'codecov-commenter')
AND number = 9276
```

<img width="1896" alt="image" src="https://user-images.githubusercontent.com/20685961/203469664-44f1bd61-6fac-412f-92e8-b6ef35ea43a7.png">

**Comment by alexey-milovidov** [comment]
@tisonkun I can upgrade it as soon as the fix will be merged in master.

@nickitat what versions are affected? Is it an old issue or a regression?

**Comment by nickitat** [comment]
looks fairly old. I've tested several versions down to 21.5, all return wrong result

**Comment by alexey-milovidov** [comment]
@tisonkun I've read your comparison with ArchLinux, and wouldn't say it is entirely correct.
You have successfully discovered a new bug in a corner case of ClickHouse, which is big luck.

**Comment by tisonkun** [comment]
@alexey-milovidov fair enough, lol.

I like ClickHouse a lot and suffer from some third-party vendor's provision binding to an extremely early version so that I cannot get many of the fixes in the nightly version and thus send the tweet XD.

Still, I'm aspire to https://github.com/ClickHouse/github-explorer/issues/10 or some affordable solution with ClickHouse Cloud.
