### ISSUE TITLE
Query and return all records is slow than elasticsearch

### ISSUE THREAD

**Issue by QipengZhou** [ClickHouse/ClickHouse#43548]
**Describe the situation**
I collect my k8s pod's log into kafka and then into clickhouse. And each pod has 300,000 log lines. When I fetch one pod's log by clickhouse http, it's very slow than elasticsearch.

**How to reproduce**
* Which ClickHouse server version to use
`22.2.2.1`
* Which interface to use, if matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
```sql
CREATE TABLE k8s_log.infrastructure_log
(

    `timestamp` DateTime,

    `timestamp64` Nullable(DateTime64(3)),

    `metadata` Nullable(String) CODEC(ZSTD(1)),

    `agent` Nullable(String) CODEC(ZSTD(1)),

    `log` Nullable(String) CODEC(ZSTD(1)),

    `stream` Nullable(String) CODEC(ZSTD(1)),

    `message` Nullable(String) CODEC(ZSTD(1)),

    `logstash_processed_at` DateTime,

    `lag_ms` Nullable(Int64),

    `offset` Nullable(Int64),

    `time_epoc` Nullable(Int64),

    `unixtime` Nullable(Int64),

    `pod_name` Nullable(String) CODEC(ZSTD(1)),

    `node_name` Nullable(String) CODEC(ZSTD(1)),

    `namespace` Nullable(String) CODEC(ZSTD(1)),

    `content` Nullable(String) CODEC(ZSTD(1)),

    `container_name` Nullable(String) CODEC(ZSTD(1)),

    `input` Nullable(String) CODEC(ZSTD(1)),

    `fields` Nullable(String) CODEC(ZSTD(1)),

    `ecs` Nullable(String) CODEC(ZSTD(1)),

    `host` Nullable(String) CODEC(ZSTD(1)),

    INDEX namespace_idx namespace TYPE minmax GRANULARITY 8192,

    INDEX container_name_idx container_name TYPE minmax GRANULARITY 8192,

    INDEX pod_name_idx pod_name TYPE minmax GRANULARITY 8192,

    INDEX stream_idx stream TYPE minmax GRANULARITY 8192,

    INDEX namespace_container_name_idx (namespace,
 container_name) TYPE minmax GRANULARITY 8192,

    INDEX namespace_pod_name_idx (namespace,
 pod_name) TYPE minmax GRANULARITY 8192
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/infrastructure_log',
 '{replica}')
PARTITION BY toYYYYMMDD(timestamp)
ORDER BY timestamp
TTL timestamp + toIntervalDay(15)
SETTINGS index_granularity = 8192;
---
CREATE TABLE k8s_log.infrastructure_log_distributed
(

    `timestamp` DateTime,

    `timestamp64` Nullable(DateTime64(3)),

    `metadata` Nullable(String) CODEC(ZSTD(1)),

    `agent` Nullable(String) CODEC(ZSTD(1)),

    `log` Nullable(String) CODEC(ZSTD(1)),

    `stream` Nullable(String) CODEC(ZSTD(1)),

    `message` Nullable(String) CODEC(ZSTD(1)),

    `logstash_processed_at` DateTime,

    `unixtime` Nullable(Int64),

    `time_epoc` Nullable(Int64),

    `offset` Nullable(Int64),

    `lag_ms` Nullable(Int64),

    `container_name` Nullable(String) CODEC(ZSTD(1)),

    `content` Nullable(String) CODEC(ZSTD(1)),

    `namespace` Nullable(String) CODEC(ZSTD(1)),

    `node_name` Nullable(String) CODEC(ZSTD(1)),

    `pod_name` Nullable(String) CODEC(ZSTD(1)),

    `input` Nullable(String) CODEC(ZSTD(1)),

    `fields` Nullable(String) CODEC(ZSTD(1)),

    `ecs` Nullable(String) CODEC(ZSTD(1)),

    `host` Nullable(String) CODEC(ZSTD(1))
)
ENGINE = Distributed('sre_ck_cluster',
 'k8s_log',
 'infrastructure_log',
 hiveHash(timestamp));
```
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to slow performance
```sql
SELECT timestamp, content, offset 
FROM k8s_log.infrastructure_log_distributed 
WHERE (timestamp >= toDateTime('1666205428', 'UTC'))
AND container_name='xxx' AND pod_name = 'xxx' AND namespace='xxxx' AND stream='xxxx' ORDER BY timestamp, `offset`
```

**Expected performance**
What are your performance expectation, why do you think they are realistic? Has it been working faster in older ClickHouse releases? Is it working faster in some specific other system?

In a pod has 130,000 log lines. I spend 40s to fetch all logs by elasticsearch scroll api, but it takes 150s by Clickhouse.

**Additional context**

I plan to replace elasticsearch by Clickhouse to store k8s pod's log. And fetch all logs for each pod.

**Comment by den-crane** [comment]
You main issue is `ORDER BY timestamp` you don't use PRIMARY INDEX to improve SELECT queries.

I suggest to use exactly this: 

```sql
PARTITION BY toYYYYMMDD(timestamp)
PRIMARY KEY (toStartOfHour(timestamp), namespace, pod_name)
ORDER BY (toStartOfHour(timestamp), namespace, pod_name, stream, timestamp)
TTL toStartOfDay(timestamp) + toIntervalDay(15);
```
ALL rows are important including changes in TTL.

-------

>What are your performance expectation, why do you think they are realistic? 

It's expected that Elastic will faster with some queries than Clickhouse. 
Elastic uses secondary indexes Clickhouse does not. 
Your minmax indexes are useless and should removed, they worsen performance.

Clickhouse ingest data faster than Elastic. Elastic queries data faster in some usecases -- this is expected.

**Comment by QipengZhou** [comment]
Thanks a lot, I will modify it.

**Comment by QipengZhou** [comment]
@den-crane I have another question by using the method you introduced. The number of rows scanned becomes 1/15 of the original, but the query time is only 3/4 of the original. Some record in the table of `system.query_log`:
![3CPs88IPY1](https://user-images.githubusercontent.com/5410298/205793681-d8b19d02-c749-4573-999d-0cf2d3147871.jpg)
My question is why the query time is reduced only a little bit compared to the number of rows scanned? Thanks.

**Comment by den-crane** [comment]
try

```
SELECT timestamp, content, offset 
FROM k8s_log.infrastructure_log_distributed 
WHERE (timestamp >= toDateTime('1666205428', 'UTC'))
AND container_name='xxx' AND pod_name = 'xxx' AND namespace='xxxx' AND stream='xxxx' 
ORDER BY toStartOfHour(timestamp), timestamp, `offset`
```

**Comment by QipengZhou** [comment]
> try
> 
> ```
> SELECT timestamp, content, offset 
> FROM k8s_log.infrastructure_log_distributed 
> WHERE (timestamp >= toDateTime('1666205428', 'UTC'))
> AND container_name='xxx' AND pod_name = 'xxx' AND namespace='xxxx' AND stream='xxxx' 
> ORDER BY toStartOfHour(timestamp), timestamp, `offset`
> ```

@den-crane Thanks, I try this query. But it seems not improve.

![image](https://user-images.githubusercontent.com/5410298/205884230-dd2a368e-7c48-4871-83a3-702556df477b.png)
