### ISSUE TITLE
Integration test `test_hive_query` is flaky

### ISSUE THREAD

**Issue by tavplubix** [ClickHouse/ClickHouse#43541]
See https://play.clickhouse.com/play?user=play#c2VsZWN0IAp0b1N0YXJ0T2ZEYXkoY2hlY2tfc3RhcnRfdGltZSkgYXMgZCwKY291bnQoKSwgIGdyb3VwVW5pcUFycmF5KHB1bGxfcmVxdWVzdF9udW1iZXIpLCAgYW55KHJlcG9ydF91cmwpCmZyb20gY2hlY2tzIHdoZXJlICcyMDIyLTA2LTAxJyA8PSBjaGVja19zdGFydF90aW1lIGFuZCB0ZXN0X25hbWUgbGlrZSAnJXRlc3RfaGl2ZV9xdWVyeSUnIGFuZCB0ZXN0X3N0YXR1cyBpbiAoJ0ZBSUwnLCAnRkxBS1knKSBncm91cCBieSBkIG9yZGVyIGJ5IGQgZGVzYw==

I will temporarily disable this test.
cc: @taiyang-li, @lgbo-ustc, @kssenii

**Comment by alesapin** [comment]
Not flaky anymore according to CIDB

**Comment by tavplubix** [comment]
> Not flaky anymore according to CIDB

Because it's disabled: https://github.com/ClickHouse/ClickHouse/blob/f44eb4e021a3e1ef2da2c8ad8790c4ef3425cf2b/tests/integration/test_hive_query/test.py#L3-L6
