### ISSUE TITLE
the same query produces different results (Distributed)

### ISSUE THREAD

**Issue by Ioann97** [ClickHouse/ClickHouse#43546]
we have clickhouse with 5 shard and of 2 replices.
i created 2 table:

`create table IF NOT EXISTS exceptions_shard on cluster '{cluster}' (content_id UUID)  engine = Memory();
 
CREATE TABLE IF NOT EXISTS exceptions_dist on cluster '{cluster}' as exceptions_shard
ENGINE = Distributed('{cluster}', database, exceptions_shard, sipHash64(content_id));`

then i inserted in table exceptions_dist 

`insert into exceptions_dist select generateUUIDv4() from numbers(100000)`

when i do select
`select count() from exceptions_dist`
i get different result
for example 5 query (within 5 seconds):
40000
60000
40000
80000
20000

if i do query 
`select count(), hostname() from exceptions_dist group by hostname()`
then I understand that i dont connected to some replices

Why? That is how it should be?

**Comment by den-crane** [comment]
read about internal_replication https://clickhouse.com/docs/en/engines/table-engines/special/distributed/
if you use `engine = Memory()` internal_replication MUST BE FALSE.
