### ISSUE TITLE
Using ClickHouse on AWS Lambda

### ISSUE THREAD

**Issue by rdettai** [ClickHouse/ClickHouse#43589]
I would like to revive https://github.com/ClickHouse/ClickHouse/issues/29378, and I think it is worth doing it in an issue for further reference.

We are trying to create a **reproducible** deployment of ClickHouse on AWS Lambda with a Lambda container image [1]. For now, we want to run it in standalone mode, so both the client and one instance of the ClickHouse server will run inside Lambda.
- We provide a Lambda container image [2] with the necessary configuration (e.g setting all file locations to `/tmp`), the Lambda Runtime Interface [3] and a Python handler that manages the ClickHouse processes [4]
- You'll notice that we use a custom base image [5]. The first challenge we faced was the one mentioned in https://github.com/ClickHouse/ClickHouse/issues/29378#issuecomment-942828362 regarding the call to `prctl`. To remove these unsuported calls we forked [6] this repo and built [7] a custom `clickhouse-server` image [8] out of it.
- We are now stuck because of an `abort` call that we cannot trace back [9]:
```
2022.11.23 15:55:59.426316 [ 12 ] <Information> Application: Forked a child process to watch
2022.11.23 15:55:59.426531 [ 12 ] <Warning> Application: Cannot do prctl to ask termination with parent.
2022.11.23 15:55:59.426725 [ 12 ] <Information> SentryWriter: Sending crash reports is disabled
2022.11.23 15:55:59.426821 [ 10 ] <Information> Application: Will watch for the process with pid 12
2022.11.23 15:55:59.427574 [ 12 ] <Trace> Pipe: Pipe capacity is 1.00 MiB
2022.11.23 15:56:01.306313 [ 12 ] <Information> : Starting ClickHouse 22.10.2.2 (revision: 54467, git hash: f3cbbf9d3c34c6084259e23cb6ea1162e4f438d2, build id: 562C100ED804125D4844DBF8AC944E730CDDF34B), PID 12
2022.11.23 15:56:01.306500 [ 12 ] <Information> Application: starting up
2022.11.23 15:56:01.306519 [ 12 ] <Information> Application: OS name: Linux, version: 4.14.255-276-224.499.amzn2.x86_64, architecture: x86_64
2022.11.23 15:56:05.394083 [ 13 ] <Trace> BaseDaemon: Received signal 6
2022.11.23 15:56:05.394291 [ 14 ] <Fatal> BaseDaemon: ########################################
2022.11.23 15:56:05.394325 [ 14 ] <Fatal> BaseDaemon: (version 22.10.2.2 (official build), build id: 562C100ED804125D4844DBF8AC944E730CDDF34B) (from thread 12) (no query) Received signal Aborted (6)
2022.11.23 15:56:05.394355 [ 14 ] <Fatal> BaseDaemon: 
2022.11.23 15:56:05.394376 [ 14 ] <Fatal> BaseDaemon: Stack trace: 0x7faaf365d00b
2022.11.23 15:56:05.394416 [ 14 ] <Fatal> BaseDaemon: 0. gsignal @ 0x7faaf365d00b in ?
```

Any ideas what the reason for this call to abort could be?

[1] https://docs.aws.amazon.com/lambda/latest/dg/images-create.html
[2] https://github.com/cloudfuse-io/lambdatization/blob/main/infra/runtime/clickhouse/build/Dockerfile
[3] https://pypi.org/project/awslambdaric/
[4] https://github.com/cloudfuse-io/lambdatization/blob/main/infra/runtime/clickhouse/build/lambda-handler.py
[5] https://github.com/cloudfuse-io/lambdatization/blob/main/infra/runtime/clickhouse/build/Dockerfile#L27
[6] https://github.com/cloudfuse-io/ClickHouse/compare/v22.10.2.11-stable...cloudfuse-io:ClickHouse:v22.10.2.11-patch
[7] https://github.com/cloudfuse-io/lambdatization/blob/main/.github/workflows/helper-clickhouse.yaml
[8] https://github.com/cloudfuse-io/lambdatization/pkgs/container/lambdatization/51544147?tag=v22.10.2.11-patch
[9] [https://github.com/cloudfuse-io/lambdatization/blob/1a6d9...7e1c/infra/runtime/clickhouse/build/README.md](https://github.com/cloudfuse-io/lambdatization/blob/1a6d9711c55606179da55bc142fc87bca57b7e1c/infra/runtime/clickhouse/build/README.md)

**Comment by rdettai** [comment]
@occasionallydavid @alexey-milovidov @pkit @mikeTWC1984 @nvartolomei did you encounter a similar issue when you ran your tests last years?

**Comment by nvartolomei** [comment]
I did disable libunwind to make exceptions work in lambda. Didn't dig further. `-DUSE_UNWIND=0` to cmake.

**Comment by nvartolomei** [comment]
In my implementation, I have built a custom (entrypoint) binary using the lambda runtime https://github.com/awslabs/aws-lambda-cpp with a handler for `aws::lambda_runtime::run_handler(handler_fn);` that looks similar to something you can see in ClickHouse's TCPServer.cpp. I never run a full fledged clickhouse-server

**Comment by alexey-milovidov** [comment]
@nvartolomei Let's commit the build type with this entrypoint to our repository. Even if it will not be checked in CI, it makes sense.

@rdettai I think we can avoid patching if we will check the availability of the `prctl` syscall in runtime.

> Application: Forked a child process to watch

Watchdog is unneeded in Lambda, you can disable it by setting the env variable `CLICKHOUSE_WATCHDOG_ENABLE=0`

Do you know how to test something for AWS Lambda without using a real service?

**Comment by rdettai** [comment]
> I did disable libunwind to make exceptions work in lambda

Thanks for the tip, but isn't libunwind precisely supposed to be what makes the stack trace work?

> I have built a custom (entrypoint) binary using the lambda runtime

Our next step on the roadmap is to create an abstraction layer with network relays (based on TCP hole punching), this is why we are running the full ClickHouse server right away.

> Watchdog is unneeded in Lambda, you can disable it by setting the env variable CLICKHOUSE_WATCHDOG_ENABLE=0

Thanks for the advice. Unfortunately, I just got rid of the first to lines of logs, but all the `<Fatal>` ones remain the same.

> Do you know how to test something for AWS Lambda without using a real service?

There are multiple simulators (e.g SAM [1]), but I don't know any that emulates the advanced constraints (forbidden system calls, exact networking...). For now I have been using plain Docker to enforce some of the constraints [2], but in the current usecase the execution is working properly locally but not inside Lambda.

[1] https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-local-invoke.html
[2] https://github.com/cloudfuse-io/lambdatization/blob/main/infra/runtime/clickhouse/build/docker-compose.yaml

**Comment by rdettai** [comment]
@nvartolomei I tried to disable libunwind [1] but the build failed [2]. This is probably some basic CMake mistake, but I am really not good at it (long live Cargo! 😄 )

[1] https://github.com/ClickHouse/ClickHouse/commit/c37ea14273efb51e4476bf42cbb74e1d3cf9c625
[2] https://github.com/cloudfuse-io/lambdatization/actions/runs/3538923273/jobs/5940251854

**Comment by UnamedRus** [comment]
Did you check this article?
https://blog.qryn.dev/wrapping-a-serverless-clickhouse-pt1

**Comment by rdettai** [comment]
Thanks @UnamedRus for the reference. But as you said, it is not able running the clickhouse server.

Anybody as any idea about what could cause this `abort`? Any clue would be nice!

**Comment by pkit** [comment]
@rdettai Judging from the build log it cannot find `libgcc_eh.a` as it doesn't exist in the sysroot and `libunwind` is disabled too.

**Comment by rdettai** [comment]
it seems that it's present in the build container:
```
> docker run clickhouse/binary-builder find /usr/lib -name "libgcc_eh.a" 
/usr/lib/gcc/x86_64-linux-gnu/9/libgcc_eh.a
/usr/lib/gcc/x86_64-linux-gnu/11/libgcc_eh.a
/usr/lib/gcc-cross/aarch64-linux-gnu/9/libgcc_eh.a
```
Do I need to help CMake find it somehow?

**Comment by pkit** [comment]
@rdettai ClickHouse uses `./contrib/sysroot` repo for the actual sysroot stuff
I didn't dig deeper but the current sysroot for Linux is https://github.com/ClickHouse/sysroot/tree/e9fb375d0a1e5ebfd74c043f088f2342552103f8/linux-x86_64-musl

**Comment by rdettai** [comment]
thanks @pkit , forcing CMake to use the system `libgcc_eh.a` solved it [1]

We now have a build that shows exceptions properly, which enabled us to debug the reason for the crash. We still had some configs that where trying to write on read only locations (`user_files`, `access` and `format_schemas`)...

So great new, we now have a lambdatized version of ClickHouse, and even greater news, ClickHouse seems to be the fastest engine, both cold and warm start [2]!

@alexey-milovidov @nvartolomei should we open PRs for:
- `prctl`: print a warning instead of raising an exception when it fails
- fix CMake so that `-DUSE_UNWIND=0` doesn't fail (add `ibgcc_eh.a` to sysroot?
Thank you all for your help so far.

[1] https://github.com/cloudfuse-io/ClickHouse/compare/v22.10.2.11-stable...cloudfuse-io:ClickHouse:v22.10.2.11-patch#diff-1bbb09a3bfa600dc211a39994cdff9b4729997eb7cf031aac9607c75b9cc7f74
[2] https://datastudio.google.com/reporting/c870737c-e8b6-467f-9860-8cd60c751f81

**Comment by danthegoodman1** [comment]
This is releant, seems that they have already been running on Lambda: https://blog.qryn.dev/wrapping-a-serverless-clickhouse-pt1

**Comment by rdettai** [comment]
Thanks @danthegoodman1, but this article was already linked earlier. We are trying to run the full server because our next objective is to run ClickHouse in distributed mode 🙂.

**Comment by danthegoodman1** [comment]
Ah missed that, sounds really interesting though!!

**Comment by rdettai** [comment]
Progress update on distributed query engine running on AWS  Lambda: we made good progress on the hole punching technology between lambdas: https://github.com/cloudfuse-io/lambdatization/pull/83. Still some stabilization required before being able to start ClickHouse on top of it, but we are definitively getting closer. Feel free to reach out if you are interested in this work 😉.

**Comment by pkit** [comment]
@rdettai my experiments were pretty much rock stable for 100 lambdas, but started to fail miserably at 1000 lambdas or larger datasets: 100GB+.
Just FYI, things to test.

**Comment by alexey-milovidov** [comment]
https://github.com/aws-samples/aws-lambda-clickhouse
