### ISSUE TITLE
Непредсказуемое поведение arrayJoin

### ISSUE THREAD

**Issue by banyrule** [ClickHouse/ClickHouse#4359]
Не уверен баг это или фича, поэтому решил завести issue-question.

Если запрос содержит два вызова `arrayJoin` с идентичными массивами в качестве аргумента, то результирующие строки будут содержать соответствующие друг другу по порядку элементы из этих массивов:
```sql
SELECT arrayJoin([1, 2, 3] as split_test_names) as test_name, arrayJoin([1, 2, 3] as split_test_groups) as test_group

1	1
2	2
3	3
```

Если же элементы массивов различны, то результирующие строки будут содержать декартово произведение двух массивов:
```sql
SELECT arrayJoin(['t1', 't2', 't3'] as split_test_names) as test_name, arrayJoin([1, 2, 3] as split_test_groups) as test_group

t1	1
t1	2
t1	3
t2	1
t2	2
t2	3
t3	1
t3	2
t3	3
```

Из [документации](https://clickhouse.yandex/docs/ru/query_language/functions/array_join/#functions_arrayjoin), как я понимаю, верно работает именно второй вариант, а первый является нежелательным поведением
> В запросе может быть использовано несколько функций arrayJoin. В этом случае, соответствующее преобразование делается несколько раз.

**Comment by den-crane** [comment]
это баг и он проявляется только для констант, видимо как оптимизация алиасится где-то внутри
[ arrayJoin([1, 2, 3]) , arrayJoin([1, 2, 3]) ] -> [ a , a as ]

**Comment by alexey-milovidov** [comment]
@den-crane Это поведение проявляется не только для констант:
`SELECT arrayJoin([x, y, z]), arrayJoin([x, y, z]) FROM (SELECT 1 AS x, materialize(2) AS y, 3 AS z)`
@banyrule Это документированное поведение: https://clickhouse.yandex/docs/ru/query_language/functions/#skleika-odinakovykh-vyrazhenii

**Comment by banyrule** [comment]
@alexey-milovidov спасибо за ответ. 
Тем не менее, такое поведение все еще похоже на баг, один из моих аргументов:

Вычисляемым _один раз_ значением функции `arrayJoin` является преобразование unfold.

> В запросе может быть использовано несколько функций arrayJoin. В этом случае, соответствующее преобразование делается несколько раз.

Если верить документации `arrayJoin`, то вычисленное единожды преобразование unfold должно применяться несколько раз: `unfold(unfold(arg))`

**Comment by alexey-milovidov** [comment]
@banyrule Да, этот способ был бы более логичным и вызывал бы меньше вопросов. Буду рад, если у нас получится это когда-нибудь исправить!

**Comment by blinkov** [comment]
@banyrule, do you have any further questions?
