### ISSUE TITLE
Rudimentary website with documentation

### ISSUE THREAD

**Issue by avraam-inside** [ClickHouse/ClickHouse#43591]
There are at least 2 instances of documentation sites, one of which is incorrect (for example, there is no information about the boolean type that has been in the database for a year):
https://content.clickhouse.tech (INCORRECT)
https://clickhouse.com

![image](https://user-images.githubusercontent.com/52919010/203622237-ef971bf5-ae11-4a79-88ad-1c2d521bc4f2.png)

This brings a lot of chaos to the understanding of reality, I already had a misunderstanding with the author of a third-party package (https://github.com/IMSMWU/RClickhouse/issues/94), who closed my request to add boolean by referring to an incorrect copy of the documentation.

Please: remove unnecessary sites with documentation from the Internet, leaving one relevant.

**Comment by alexey-milovidov** [comment]
I've shut down the website.
