### ISSUE TITLE
test_keeper_zookeeper_converter is flaky

### ISSUE THREAD

**Issue by tavplubix** [ClickHouse/ClickHouse#43594]
https://play.clickhouse.com/play?user=play#c2VsZWN0IAp0b1N0YXJ0T2ZEYXkoY2hlY2tfc3RhcnRfdGltZSkgYXMgZCwKY291bnQoKSwgIGdyb3VwVW5pcUFycmF5KHB1bGxfcmVxdWVzdF9udW1iZXIpLCAgYW55KHJlcG9ydF91cmwpCmZyb20gY2hlY2tzIHdoZXJlICcyMDIyLTA2LTAxJyA8PSBjaGVja19zdGFydF90aW1lIGFuZCB0ZXN0X25hbWUgbGlrZSAnJXRlc3Rfa2VlcGVyX3pvb2tlZXBlcl9jb252ZXJ0ZXIlJyBhbmQgdGVzdF9zdGF0dXMgaW4gKCdGQUlMJywgJ0ZMQUtZJykgZ3JvdXAgYnkgZCBvcmRlciBieSBkIGRlc2M=

**Comment by tavplubix** [comment]
Still flaky https://s3.amazonaws.com/clickhouse-test-reports/42807/eb4f755a8e0bb9c5e364c896d9c55cfef777ce55/integration_tests__tsan__[1/6].html

**Comment by qoega** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/44897/2e758f983fb86732e0467f6a9bc2deb266d51a40/integration_tests__tsan__[1/6].html

**Comment by antonio2368** [comment]
Fixed by https://github.com/ClickHouse/ClickHouse/pull/44834
