### ISSUE TITLE
Is there a plan for MaterializedMySQL distributed mode?

### ISSUE THREAD

**Issue by liliang8858** [ClickHouse/ClickHouse#43614]
> (you don't have to strictly follow this form)

****

> A clear and concise description of what is the intended usage scenario is.

**MaterializeMySQL distributed mode**

> A clear and concise description of what you want to happen.

****

> A clear and concise description of any alternative solutions or features you've considered.

****

> Add any other context or screenshots about the feature request here.

**Comment by tavplubix** [comment]
MaterializeMySQL is not officially supported, so no plans. Currently MaterializeMySQL is supported by community only. Feel free to send a pull request.

Btw, what is "distributed mode"?
