### ISSUE TITLE
Materialized view TO distributed table on ReplicatedAggregatingMergeTree

### ISSUE THREAD

**Issue by ayinakuna** [ClickHouse/ClickHouse#43625]
Our writer is currently not sharding awareness, so we tried to make Materialized view TO a distributed table.

We have 4 shards with 2 replicas on each.

Here are the tables

```
-- table a
create table table_a
    engine = ReplicatedMergeTree();


--local aggregation table 
create table table_agg
    engine = ReplicatedAggregatingMergeTree()


-- distributed aggregation table 
create table table_agg_distributed
    engine = Distributed()


--mv
CREATE MATERIALIZED VIEW default.mv_x
            TO default.table_agg_distributed
AS
SELECT *
FROM default.table_a

```

QUESTION:
We only see the above MV updating/working on shard 0, without any obvious errors in the logs. 
Is the above idea even possible? Does clickhouse supports materialised views to distributed tables?

PS: I know this following set up would work, but this is what we have..
https://github.com/ClickHouse/ClickHouse/issues/467

**Comment by den-crane** [comment]
Yes, it should work. Check that you have created all objects at all servers. Did you use on_cluster or how did you create tables / matView?

**Comment by ayinakuna** [comment]
Thanks @den-crane for the confirmation.

Yes, there was indeed a mismatch in the schemas on different replicas, fixed that and worked as expected now.
