### ISSUE TITLE
Flaky 01072_window_view_multiple_columns_groupby in tsan (timeout)

### ISSUE THREAD

**Issue by vdimir** [ClickHouse/ClickHouse#43659]
see [results in CI database](https://play.clickhouse.com/play?user=play#CiAgICBTRUxFQ1QKICAgICAgICByZXBvcnRfdXJsLAogICAgICAgIHN1YnN0cmluZyhjaGVja19uYW1lLCAxLCAxNSkgfHwgJy4uLicgfHwgc3Vic3RyaW5nKGNoZWNrX25hbWUsIC0xNSkgYXMgY2hlY2ssCiAgICAgICAgc3Vic3RyaW5nKHRlc3RfbmFtZSwgLTUwKSBhcyB0ZXN0LAogICAgICAgIGNoZWNrX3N0YXJ0X3RpbWUsCiAgICAgICAgdGVzdF9zdGF0dXMsCiAgICAgICAgdGVzdF9kdXJhdGlvbl9tcyAvIDEwMDAgQVMgZWxhcHNlZF9zZWMsCiAgICAgICAgc3Vic3RyaW5nKGNvbW1pdF9zaGEsIDEsIDEwKSBhcyBjb21taXRfc2hvcnQsCiAgICAgICAgcHVsbF9yZXF1ZXN0X251bWJlciBhcyBwcm51bSwKICAgICAgICBtdWx0aUlmKAogICAgICAgICAgICBub3coKSAtIElOVEVSVkFMICcxJyBkYXkgPD0gY2hlY2tfc3RhcnRfdGltZSwgJzwxZCcsCiAgICAgICAgICAgIG5vdygpIC0gSU5URVJWQUwgJzcnIGRheSA8PSBjaGVja19zdGFydF90aW1lLCAnPDF3JywKICAgICAgICAgICAgJycpIGFzIGxhc3QKICAgIEZST00gY2hlY2tzCiAgICBXSEVSRSB0ZXN0X3N0YXR1cyBub3QgaW4gKCdPSycsICdTS0lQUEVEJykKICAgICAgICBBTkQgdGVzdF9uYW1lIGxpa2UgJyUwMTA3Ml93aW5kb3dfdmlld19tdWx0aXBsZV9jb2x1bW5zX2dyb3VwYnklJwogICAgICAgIEFORCBub3coKSAtIElOVEVSVkFMICczMCcgZGF5IDw9IGNoZWNrX3N0YXJ0X3RpbWUKICAgICAgICAKICAgIE9SREVSIEJZCiAgICAgICAgCiAgICAgICAgY2hlY2tfc3RhcnRfdGltZSBERVNDCiAgICBMSU1JVCAxMDAKCg==)

**Comment by tavplubix** [comment]
cc: @Vxider, @kssenii

**Comment by tavplubix** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/43781/a00fc4907b74fe2f8a39729e041a2a3ee28904b2/stateless_tests__tsan__[4/5].html

**Comment by tavplubix** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/43848/c2a19fc354e17a31d22d3baecfd7511ced6be1cd/stateless_tests__tsan__[4/5].html

**Comment by tavplubix** [comment]
It's still flaky: https://s3.amazonaws.com/clickhouse-test-reports/44387/0bac667fd80e46617ecbef96e160f4bb3eea631f/stateless_tests__tsan__[4/5].html

**Comment by kssenii** [comment]
may be this will help https://github.com/ClickHouse/ClickHouse/pull/44438

**Comment by alexey-milovidov** [comment]
Does not reproduce in a month.
