### ISSUE TITLE
Add `skip_unavailable_shards` as a setting for Distributed table.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#43666]
**Use case**

It will allow to create distributed counterparts for system tables, which will work even if some replicas are unavailable.

The table-level setting will provide a default value and can be overridden with the user/query-level setting.

**Comment by alexey-milovidov** [comment]
@zhongyuankai Yes, it will help a lot!

**Comment by bianpengyuan** [comment]
@alexey-milovidov I'd like to take this. Can you assign this to me? Thanks!

**Comment by tntnatbry** [comment]
@nikitamikhaylov , @alexey-milovidov Here is the patch for this feature (exactly a year after this issue was created!): https://github.com/ClickHouse/ClickHouse/pull/57218

Please refer to the detailed comment in the PR explaining the scenario. I will appreciate it if you can review this ASAP.
