### ISSUE TITLE
Lock functions in ClickHouse (PG:  pg_advisory_lock analogue)

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#43708]
**Use case**

Provide way to use ClickHouse as shared resource lock.
It can make sense for client applications or for JOBS, when they will be implemented

Analogue for 
https://www.postgresql.org/docs/15/functions-admin.html#FUNCTIONS-ADVISORY-LOCKS

**Describe the solution you'd like**

Build on top of clickhouse-keeper ephemeral nodes? (or it should be possible to use them without (zoo)keeper as well)

**Describe alternatives you've considered**

Some nasty hacks

https://blog.qryn.dev/shared-resource-lock-powered-by-clickhouse

**Comment by filimonov** [comment]
That reminds me https://github.com/ClickHouse/ClickHouse/issues/4802

**Comment by alexey-milovidov** [comment]
It's extremely hard to use locks in a distributed system if the user of the lock does not atomically check that the lock still holds in every operation that it attempts to perform under a lock.

So, it's much better to use clickhouse-keeper directly for that.

**Comment by alexey-milovidov** [comment]
Maybe it's still ok to implement, but it's a non-trivial task - better to not pay attention for now.
