### ISSUE TITLE
"Explain query tree" disappeared

### ISSUE THREAD

**Issue by socketpair** [ClickHouse/ClickHouse#43729]
https://clickhouse.com/docs/en/sql-reference/statements/explain

at the top:

`EXPLAIN [AST | SYNTAX | PLAN | PIPELINE | ESTIMATE | TABLE OVERRIDE] [setting = value, ...]`

in the list of subjects there is `EXPLAIN QUERY TREE`. It does not work (syntax error) in my installation. Seems it's some old request. Please remove or clarify what's happening. For example, write that it disappeared in xxx version.

**Comment by evillique** [comment]
The query `EXPLAIN QUERY TREE` has been added in 22.10 and seems to work correctly: https://fiddle.clickhouse.com/aa34f945-629a-4fbc-ba98-6df1b1cc655e

**Comment by socketpair** [comment]
@evillique if so, header of the article should be updated. See the beginning of my message
