### ISSUE TITLE
List of python libraries does not mention "official" one

### ISSUE THREAD

**Issue by socketpair** [ClickHouse/ClickHouse#43730]
https://clickhouse.com/docs/en/interfaces/third-party/client-libraries

does not contain `clickhouse-connect`

It is described here:
https://clickhouse.com/docs/en/integrations/language-clients/python/intro/

As far as I understand, `clickhouse-connect` is the preferred Python library. If yes, please put some mark on.

**Comment by evillique** [comment]
As I understand it, the `clickhouse-connect` library is not only preferred but is the official client library for ClickHouse and therefore is not listed in the **third-party** libraries list.

**Comment by alexey-milovidov** [comment]
We will rework the categories to make them more obvious.
