### ISSUE TITLE
Documentation is wrong

### ISSUE THREAD

**Issue by simper66** [ClickHouse/ClickHouse#43740]
https://clickhouse.com/docs/en/operations/settings/settings#persistent

The "persistent" setting in the documentation does not appear in system.settings table

Also, if you add it con users.xml, the server does not start.

```
<?xml version="1.0"?>
<clickhouse>
    <profiles>
        <default>
            <persistent>1</persistent>
        </default>
    </profiles>
</clickhouse>
```

If the SET/JOIN tables are supposed to be always in RAM, which is the purpose of persist them on disk?

**Comment by filimonov** [comment]
Documentation bug https://github.com/ClickHouse/ClickHouse/pull/16579 

It is not a user / setting setting, it is a table-level setting 
example of the proper usage:

https://github.com/ClickHouse/ClickHouse/blob/a3276005c75425dd13500ddfaaf4c57cf6aabfe6/tests/queries/0_stateless/01493_storage_set_persistency.sql#L19
