### ISSUE TITLE
Clickhouse query using MongoDB engine not scan by index in MongoDB

### ISSUE THREAD

**Issue by YingHongBin** [ClickHouse/ClickHouse#43741]
Define a table in Clickhouse using MongoDB engine, which MongoDB collection contains about 50 million records.
Inquery simple statement like `SELECT * FROM table WHERE time between $start and $end`, and define index in `time` column in mongo.
Clickhosue received a exception
<img width="717" alt="image" src="https://user-images.githubusercontent.com/31915143/204208507-e0a9fddf-1273-4279-8c99-3a99032887b1.png">

Seems query from clickhouse not using expected index in MongoDB

**Comment by alexey-milovidov** [comment]
Yes, ClickHouse does not construct the filter expressions to be pushed down to MongoDB.
Let's consider it a feature request.
