### ISSUE TITLE
Could copier run Multithreaded processing when do copying one large table ?

### ISSUE THREAD

**Issue by Johnny-Three** [ClickHouse/ClickHouse#4374]
now the task seems to run orderly in one thread. 
I guess it will help to accelerate the progress when it runs parallel?

**Comment by alexey-milovidov** [comment]
`clickhouse-copier` can be run in multiple instances in parallel if there are multiple tasks. Each task is single partition for single shard of destination cluster.

There is no support to run single task in parallel with one `clickhouse-copier` instance.

There is a feature request to allow to split single partition into multiple tasks of smaller size to achieve better reliability.
