### ISSUE TITLE
Unnable to run query with EXISTS

### ISSUE THREAD

**Issue by miroha** [ClickHouse/ClickHouse#43747]
Greetings!
Some preview:
I've some table. Each _date_ contains data snapshots for 15 days ago and 50 days ahead. If I'll go to my table and run SELECT WHERE date = '2022-01-27' I will get rows with _block_date_ from 2022-01-13 to 2022-03-18. I need to build reports per month, so at _date_ = '2022-01-27' I need to see rows with _block_date_ from 2022-01-01 to 2022-01-31. I can find this missing information if I go back a day. At _date_ = '2022-01-26' I will find information for _block_date_ = 2022-01-12 and so on. 

For example I've these rows:

```
|date        | block_date   | total_plan_volume_grp20  |
| -----------| ------------ | -------------------------|
| 2022-01-27 | 2022-01-14   | 10                       |
| 2022-01-27 | 2022-01-13   | 20                       |
| 2022-01-26 | 2022-01-14   | 10                       | 
| 2022-01-26 | 2022-01-13   | 20                       | 
| 2022-01-26 | 2022-01-12   | 30                       | 
| 2022-01-25 | 2022-01-14   | 10                       | 
| 2022-01-25 | 2022-01-13   | 20                       |  
| 2022-01-25 | 2022-01-12   | 30                       | 
| 2022-01-25 | 2022-01-11   | 40                       |
```
I expect to get this:

```
|date        |block_date    |total_plan_volume_grp20    |
| --------   | ------------ | ------------------------- |
| 2022-01-27 | 2022-01-14   | 10                        |
| 2022-01-27 | 2022-01-13   | 20                        |
| 2022-01-27 | 2022-01-12   | 30                        |
| 2022-01-27 | 2022-01-11   | 40                        |
| 2022-01-26 | 2022-01-14   | 10                        |
| 2022-01-26 | 2022-01-13   | 20                        | 
| 2022-01-26 | 2022-01-12   | 30                        | 
| 2022-01-26 | 2022-01-11   | 40                        | 
| 2022-01-25 | 2022-01-14   | 10                        |
| 2022-01-25 | 2022-01-13   | 20                        | 
| 2022-01-25 | 2022-01-12   | 30                        | 
| 2022-01-25 | 2022-01-11   | 40                        | 
```

Early we used PostgreSQL and query below works fine with Postge. I tried to modify query a bit and run it in ClickHouse. 
Query:
```
    SELECT
      `date`,
      block_date,
      total_plan_volume_grp20
    FROM schema.table 
    UNION ALL
    SELECT 
      addDays(`date`, 1),
      block_date,
      total_plan_volume_grp20
    FROM schema.table t1
    where exists (
       select true 
       from schema.table t2 
       where t2.`date` = addDays(t1.`date`, 1))
    UNION ALL
    SELECT 
      addDays(`date`, 2),
      block_date,
      total_plan_volume_grp20
    FROM schema.table t1
    where exists (
       select true 
       from schema.table t2 
       where t2.`date` = addDays(t1.`date`, 2))
```
It throws an error:
`while processing query: 'SELECT true FROM schema.table AS t2 WHERE date = addDays(t1.date, 1)', required columns: 'date' 't1.date', maybe you meant: ['date']: While processing 1 IN (SELECT 1 FROM (SELECT true FROM schema.table AS t2 WHERE t2.date = addDays(t1.date, 1)) LIMIT 1). (UNKNOWN_IDENTIFIER) (version 22.10.2.11 (official build))`

 
How to handle this behaviour? Or any tips how can I change query? 
Sorry, If I chose category wrong.

Thanks!

**Using:
ClickHouse 22.10.2.11
DBeaver 22.2.5**

**Comment by tavplubix** [comment]
Correlated subqueries are not supported
