### ISSUE TITLE
Count distinct raises "Unknown function" error with executable UDFs

### ISSUE THREAD

**Issue by jzombi** [ClickHouse/ClickHouse#43771]
**Describe what's wrong**

Count distinct raises an error when executed on the results of an executable UDF. Interestingly distinct without count, and count without distinct seems to work.

**Does it reproduce on recent release?**

Tested on `22.8.8`, could not test on newer versions on fiddle because of UDF.

**How to reproduce**

* Which ClickHouse server version to use: `22.8.8`
* UDF `test.py`:
    ```
    #!/usr/bin/python3

    import sys

    if __name__ == '__main__':
        for line in sys.stdin:
            print(line, end='')
            sys.stdout.flush()
    ```
* UDF config xml:
    ```
    <?xml version="1.0"?>
    <functions>
        <function>
            <type>executable</type>
            <name>test</name>
            <return_type>Nullable(String)</return_type>
            <argument>
                <type>Nullable(String)</type>
                <name>value</name>
            </argument>
            <format>TabSeparated</format>
            <command>test.py</command>
        </function>
    </functions>
    ```
* Queries to run that lead to unexpected result
    ```
    SELECT COUNT(DISTINCT test((number % 2)::String)) FROM numbers(1000);
    ```

**Expected behavior**

Return a table with a single row with value `2`.

**Error message and/or stacktrace**

```
Code: 46. DB::Exception: Received from localhost:9000. DB::Exception: Unknown function test. Maybe you meant: ['left','CAST']: While processing uniqExact(test(CAST(number % 2, 'String'))). (UNKNOWN_FUNCTION)
```

**Additional context**
Might be related to #36448, but not the same, as group by works fine in this version.

**Comment by den-crane** [comment]
>UDF config xml: 

XML should be in a separate file with postfix `_function` not config.xml

like 

```
cat /etc/clickhouse-server/test_function.xml

<functions>
    <function>
        <type>executable</type>
        <name>test</name>
        <return_type>Nullable(String)</return_type>
        <argument>
            <type>Nullable(String)</type>
            <name>value</name>
        </argument>
        <format>TabSeparated</format>
        <command>test.py</command>
    </function>
</functions>

```

see https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings#server_configuration_parameters-user_defined_executable_functions_config
