### ISSUE TITLE
Monitoring ClickHouse Keeper

### ISSUE THREAD

**Issue by DanRoscigno** [ClickHouse/ClickHouse#43783]
Does ClickHouse Keeper provide metrics for monitoring?  ZooKeeper exports metrics for ingestion by Prometheus.  I am looking for the ability to populate [Grafana's ZooKeeper dashboard](https://grafana.com/grafana/dashboards/10465-zookeeper-by-prometheus/) with metrics from ClickHouse Keeper.

In the ClickHouse tests I see the different metric sets, but did not find Keeper metrics:
```
<!--↴                                                                                
  │   endpoint - mertics path (relative to root, statring with "/")↴                   
  │   port - port to setup server. If not defined or 0 than http_port used↴            
  │   metrics - send data from table system.metrics↴                                   
  │   events - send data from table system.events↴                                     
  │   asynchronous_metrics - send data from table system.asynchronous_metrics↴         
  │   status_info - send data from different component from CH, ex: Dictionaries status       ↴                                                                                        
   -->↴ 
```

ZooKeeper describes the Prometheus setup here:

https://zookeeper.apache.org/doc/r3.7.0/zookeeperMonitor.html

**Comment by alexey-milovidov** [comment]
Keeper provides monitoring with the four-letter commands, compatible with ZooKeeper:
https://zookeeper.apache.org/doc/r3.4.8/zookeeperAdmin.html#sc_zkCommands

In addition, the Prometheus endpoint is being implemented in https://github.com/ClickHouse/ClickHouse/pull/43087
