### ISSUE TITLE
How to conditionally rename or exchange a table?

### ISSUE THREAD

**Issue by tasdflkjweio** [ClickHouse/ClickHouse#43782]
Is there an equivalent to [the T-SQL `IF...ELSE`](https://learn.microsoft.com/en-us/sql/t-sql/language-elements/if-else-transact-sql?view=sql-server-ver16) keywords for control flow?

I'm trying to conditionally `EXCHANGE` tables `A` and `B` if `A` exists, otherwise just rename `B` to `A`.

**Comment by realyota** [comment]
There is no procedural language support for Clickhouse.

**Comment by tavplubix** [comment]
It's supported internally (for `[CREATE OR] REPLACE TABLE`) but not available from SQL:
https://github.com/ClickHouse/ClickHouse/blob/65474830ac3ed96fad07d6fe72f62f35d62f390f/src/Interpreters/InterpreterRenameQuery.cpp#L93-L107
Feel free to open a pull request
