### ISSUE TITLE
Flaky window_view_multiple_columns_groupby

### ISSUE THREAD

**Issue by CheSema** [ClickHouse/ClickHouse#43798]
Example
https://s3.amazonaws.com/clickhouse-test-reports/43278/0cd49e84c6c6456022e8542bdd7072be4e3ad8a4/stateless_tests__tsan__[4/5].html

Test hangs here 
https://github.com/ClickHouse/ClickHouse/blob/master/tests/queries/0_stateless/01072_window_view_multiple_columns_groupby.sh#L21

Flaky stats
https://play.clickhouse.com/play?user=play#c2VsZWN0IAp0b1N0YXJ0T2ZIb3VyKGNoZWNrX3N0YXJ0X3RpbWUpIGFzIGQsCmNvdW50KCksICBncm91cFVuaXFBcnJheShwdWxsX3JlcXVlc3RfbnVtYmVyKSwgIGFueShyZXBvcnRfdXJsKQpmcm9tIGNoZWNrcyB3aGVyZSAnMjAyMi0wNi0wMScgPD0gY2hlY2tfc3RhcnRfdGltZSBhbmQgdGVzdF9uYW1lIGxpa2UgJyUwMTA3Ml93aW5kb3dfdmlld19tdWx0aXBsZV9jb2x1bW5zX2dyb3VwYnklJyBhbmQgdGVzdF9zdGF0dXMgaW4gKCdGQUlMJywgJ0ZMQUtZJykgZ3JvdXAgYnkgZCBvcmRlciBieSBkIGRlc2M=

It never fail in master, but often in pr's.

**Comment by CheSema** [comment]
@Vxider @kssenii
May be it is interesting for you and you could help.

**Comment by vdimir** [comment]
https://github.com/ClickHouse/ClickHouse/issues/43659
