### ISSUE TITLE
Why the new `drop partition` implementation waits for parts to be dropped and files to be removed?

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#43808]
The new implementation waits for the parts to be removed from the disk and therefore it works for a while: **Elapsed: 3.591 sec**

Apparently it's implemented this way to show a user that the disk space is freed up?

But if affected parts are used in a running select, then it doesn't wait and returns control faster: **Elapsed: 0.355 sec.**

As a user, I would rather like `truncate` and `drop partition` complete instantly and remove files in the background.

**Comment by den-crane** [comment]
cc: @CheSema

**Comment by CheSema** [comment]
Nice catch!
This happened unintentionally. 
I made a call clearOldPartsFromFilesystem at the end of operation. This call __tries__ to delete unnecessary parts. If this parts still in use the call do nothing and wait nothing. But indeed, when the call goes to remove parts it does in in sync mode. The intention was to preserve the familiar behavior: you drop the parts, parts are dropped, the space is freed. 

I could propose the upgrade. 
Instead a sync call make a task to the thread pool __without any timeout__ with this call. Therefore we would preserve  the familiar behavior in the most cases.

**Comment by azat** [comment]
Actually synchronous DROP PARTITION may be interesting, so maybe it worth add SYNC/ASYNC version (under a setting or as a query syntax)?
