### ISSUE TITLE
data race was found in modify/get PartState of MergeTreeData when rollback / truncate table run concurrently

### ISSUE THREAD

**Issue by hanfei1991** [ClickHouse/ClickHouse#43803]
**Describe the bug**
found by thread fuzzer for **2421_truncate_isolation_no_merges**

**How to reproduce**
https://s3.amazonaws.com/clickhouse-test-reports/43304/ee5be80d9f266c3629ec9b414329916b09596f0d/stateless_tests__tsan__[3/5]/stderr.log

**Comment by tavplubix** [comment]
Looks like duplicate of https://github.com/ClickHouse/ClickHouse/issues/43799
