### ISSUE TITLE
Why does remote apply to subquery as well?

### ISSUE THREAD

**Issue by icetroid** [ClickHouse/ClickHouse#43823]
**Describe the unexpected behaviour**
I'm running a nested SELECT query. I only use remote for the main query, but remote also applies for subquery as well? Is this intentional? 

**How to reproduce**
version 22.2.2.1
select * from remote('192.168.10.18:9000',  'a',  'b',  'region',  'remote') where val not in (select val from a.b);

**Expected behavior**
I connect and run this query on server with ip 192.168.10.17. I expect the subquery "(select val from a.b)" to get "val" from database on the server I'm running which is 192.168.10.17, but in reality the subquery fetch data from remote server 192.168.10.18. Is this intentional?

If this intentional is there a way to make subquery to get data from 192.168.10.17, without using value 192.168.10.17 in the query (ip are set in config file, and I want to set localhost instead of "192.168.10.17" in the config file)

**Comment by den-crane** [comment]
remote -- creates a temporary Distribute table. 

> `select * from remote('192.168.10.18:9000', 'a', 'b', 'region', 'remote') where val not in (select val from a.b);`

In this case of syntax `a.b` is expected to be at the remote side.

You have two options:
1) pass `a.b` to the remote side using GLOBAL

`select * from remote('192.168.10.18:9000', 'a', 'b', 'region', 'remote') where val GLOBAL not in (select val from a.b);

2) using a subquery apply IN locally

```sql
select * from (select * from remote('192.168.10.18:9000', 'a', 'b', 'region', 'remote') limit 100000000000) t 
    where val not in (select val from a.b);
```

limit 100000000000 -- is to hack predicate pushdown

**Comment by icetroid** [comment]
@den-crane if I use operator ">" instead of "not in" it seems that "(select val from a.b)" will not run on the remote side:
`select * from remote('192.168.10.18:9000', 'a', 'b', 'region', 'remote') where val > (select max(val) from a.b)
`<br>So the behavior differs depending on the operator?

**Comment by alexey-milovidov** [comment]
@icetroid Yes, the subquery on the right-hand side of IN runs remotely, while scalar subqueries run locally.
