### ISSUE TITLE
optimize table partition slow

### ISSUE THREAD

**Issue by mofei920** [ClickHouse/ClickHouse#43822]
version: 22.3.8.39

table test1 definition：
```sql
ENGINE = ReplicatedReplacingMergeTree(version)
PARTITION BY toYYYYMM(chat_day)
```
test1 rows: 1100000000
test1 bytes_on_disk: 16G

run command:
```
clickhouse-client -h xxx -u xxx -d db1 -mn --receive_timeout 7200 --send_timeout 7200 -q "OPTIMIZE TABLE test1 PARTITION '202206' FINAL"
```

less than one hour, the clickhouse-client command still running, but no optimize table running in system.processes, no record in system.merges, there is only one row in system.parts of the partition. 
```sql
-- only one row
select *
FROM system.parts
where active
    and database='db1'
    and table in ('test1')
    and partition='202206';
```

It indicated that the optimize table partition should be finished, but until 2 hour later, i get the error log. why the clickhouse-client still running for long time after the merge finished?
```
Timeout exceeded while receiving data from server. Waited for 7200 seconds, timeout is 7200 seconds.
Error on processing query: Code: 210. DB::NetException: Connection reset by peer, while reading from socket (192.168.2.2:9000): while receiving packet from xxx:9000. (NETWORK_ERROR) (version 22.3.8.39 (official build))
```

**Comment by tbragin** [comment]
Version 22.3.8.39 is no longer supported. I would suggest upgrading to a newer version e.g. 23.8 (LTS) or ideally the latest 24.4 (see full list [here](https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md#scope-and-supported-versions)), and let us know if the problem persists. Specifically in 24.1 release there are quite a few optimizations for FINAL that may apply to this use case (https://presentations.clickhouse.com/release_24.1/).
