### ISSUE TITLE
use-of-uninitialized-value CastOverloadResolver while using new analyzer

### ISSUE THREAD

**Issue by Avogar** [ClickHouse/ClickHouse#43836]
https://s3.amazonaws.com/clickhouse-test-reports/43695/4aa3e2327084494b9ab7ae617e52d3dd02c08a2a/fuzzer_astfuzzermsan//report.html
How to reproduce:
```
select number IN (SELECT NULL GROUP BY count() OVER (ORDER BY 1)) FROM numbers(10) settings allow_experimental_analyzer=1
```

CC: @kitaisreal

**Comment by hanfei1991** [comment]
bug still exists so I will look into it
