### ISSUE TITLE
`AST fuzzer: The query formatting is broken` in query with any

### ISSUE THREAD

**Issue by vdimir** [ClickHouse/ClickHouse#43830]
https://s3.amazonaws.com/clickhouse-test-reports/38191/21f93e9f4cde9d08fbc06dd103fa7f530630d0aa/fuzzer_astfuzzermsan//report.html

Query: `SELECT '-0.0000000002', (-1 + NULL) = any('0.0000001024', (NULL + NULL) + NULL, 3.4028234663852886e38 + NULL), NULL, any((0. + NULL) + NULL), any(NULL) WITH TOTALS`

Minimized example:

```
explain syntax SELECT 1 = any(1);

EXPLAIN SYNTAX
SELECT 1 = 1


┌─explain──────┐
│ SELECT 1 = 1 │
└──────────────┘
```

**Comment by tavplubix** [comment]
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/40237
cc: @kssenii
