### ISSUE TITLE
SIGABRT in clickhouse local

### ISSUE THREAD

**Issue by vdimir** [ClickHouse/ClickHouse#43831]
https://s3.amazonaws.com/clickhouse-test-reports/38191/21f93e9f4cde9d08fbc06dd103fa7f530630d0aa/fuzzer_astfuzzermsan//report.html

Query: `SELECT '-0.0000000002', (-1 + NULL) = any('0.0000001024', (NULL + NULL) + NULL, 3.4028234663852886e38 + NULL), NULL, any((0. + NULL) + NULL), any(NULL) WITH TOTALS`

Minimized example:

```bash
$ ~/clickhouse local -q "SELECT NULL, any(NULL) WITH TOTALS"
\N	\N
fish: Job 1, '~/clickhouse local -q "SELECT N…' terminated by signal SIGABRT (Abort)```

**Comment by alexey-milovidov** [comment]
@Avogar, this is still relevant.

**Comment by alexey-milovidov** [comment]
Is it the same issue that @al13n321 has found?
