### ISSUE TITLE
NaN representation changes when some functions applied to it.

### ISSUE THREAD

**Issue by lexx-bright** [ClickHouse/ClickHouse#43844]
0x7ff0000000000002 is used in Prometheus as a stale marker. Stored in GraphiteMergeTree table with avg or sum rollup, the representation of NaN gets changed after parts merge.
```
SELECT
    reinterpretAsFloat64(9218868437227405314) AS v,
    hex(reinterpretAsUInt64(v)) AS hex,
    hex(reinterpretAsUInt64(avg(v))) AS avg,
    hex(reinterpretAsUInt64(sum(v))) AS sum

┌───v─┬─hex──────────────┬─avg──────────────┬─sum──────────────┐
│ nan │ 7FF0000000000002 │ 7FF8000000000002 │ 7FF8000000000002 │
└─────┴──────────────────┴──────────────────┴──────────────────┘

```

**Comment by jh0x** [comment]
Side comment... `0x7ff0000000000002` is a signaling `NaN` with custom payload. Any operation on such value results in a quiet `NaN` with the same payload (with difference only in the quiet bit): `0x7FF8000000000002`. So this would be "the normal" behaviour for any operation and example above seems reasonable.

I don't know about that particular use case, but I guess that what you would like to see done in some place is as below:

```sql
SELECT
    avg(data) AS avg,
    avgIf(data, isFinite(data)) AS avg1f,
    avgIf(data, NOT isNaN(data)) AS avg2f,
    avgIf(data, reinterpretAsUInt64(data) != reinterpretAsUInt64(snan)) AS avg3f,
    sum(data) AS sum,
    sumIf(data, NOT isNaN(data)) AS sum1f,
    sumIf(data, isFinite(data)) AS sum2f,
    sumIf(data, reinterpretAsUInt64(data) != reinterpretAsUInt64(snan)) AS sum3f
FROM
(
    SELECT
        reinterpretAsFloat64(9218868437227405314) AS snan,
        arrayJoin([snan, 2, 3, snan]) AS data
)

┌─avg─┬─avg1f─┬─avg2f─┬─avg3f─┬─sum─┬─sum1f─┬─sum2f─┬─sum3f─┐
│ nan │   2.5 │   2.5 │   2.5 │ nan │     5 │     5 │     5 │
└─────┴───────┴───────┴───────┴─────┴───────┴───────┴───────┘
```

- For `avg1f` and `sum1f` we filtered out all weird floating point values (retained `isFinite`).
- For `avg2f` and `sum2f` we filtered out all NaNs.
- For `avg3f` and `sum3f` we filtered out the very specific value.


I could have a further look at that, but would need a bit more context about the scenario and the bits and pieces involved.

**Comment by alexey-milovidov** [comment]
This behavior of Prometheus is a clever hack, which should be discouraged.
You can filter out these values before insertion.
