### ISSUE TITLE
Updated dashboard data does not clear previous line

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#43859]
I have a load balancer that points to several ClickHouse nodes. It looks like autorefresh in dashboard feature gets results from random nodes and leaves previous line untouched:

<img width="858" alt="Screenshot 2022-12-01 at 12 15 38" src="https://user-images.githubusercontent.com/2159081/205039551-612ae1e3-744a-4305-8dfd-78fc0476a2ad.png">

**Comment by alexey-milovidov** [comment]
How to reproduce:

1. Open the dashboard.
2. Remove all the charts except the last chart by pressing the "close" button on the first chart iteratively.
3. Edit the only remaining chart a little.

**Comment by alexey-milovidov** [comment]
Fixed by #45935.
