### ISSUE TITLE
Materialized view with join is missing partial data

### ISSUE THREAD

**Issue by pandar00** [ClickHouse/ClickHouse#43852]
Hello, 
First, thanks for the great product. Really enjoy using it
I have a stream of events about a sales order and I need to join on two different event types. In order to join at a batch of inserts, I created MV with a JOIN clause but it misses about 10% of the data. I was hoping if the experts could sanity check my setup is reasonable and get a second thought on what's exactly happening.

## Setup

I have an "Events" table which is inserted from Kafka stream. There are two types of events: "create" and "close". These are events for an order for example. All events are initially inserted to the "events" table, and then each event type is selected and inserted to "CreateEvents" and "CloseEvents " tables accordingly.
```
[KafkaEngine] - [MV] - [Events Table] ----- [MV select "create" event] --- [CreateEvents Table]
                                      \
                                       \
                                        \-- [MV select "close" event] ---- [CloseEvents Table]
```

Because joining the create and closed events table is expensive, I decided to make an MV that joins the two hoping that it would join at the increments of batch inserts to the left-side of the join clause.
```
[MV Select CloseEvents INNER JOIN CreateEvents] -- [CreateToCloseEvents Table]
```

All non-MV tables are replicated merge tree tables to 3 nodes.

## Expected Behavior
I read from [PDF Everything you should know about materialized views](https://den-crane.github.io/Everything_you_should_know_about_materialized_views_commented.pdf) that MV trigger inserts on insert to the left-side of the JOIN clause which is the close events table, so I was expecting every close events will find it's matching create event by order ID and insert it into the "CreateToCloseEvents" table. 

**This works but misses ~10% of the data. From what I see, the missed data usually happens if the "create" and "close" events happen next to each other within seconds.**

My guess is that the JOIN MV at the time of SELECT sees the "closed" event but not the "create" event. Kafka has 24 partitions so it's possible that the "create" event goes to one partition and the "close" event goes to a different partition, and CH may insert the "close" first which doesn't see the "create" event, and then the "create" event is inserted which in this case the joined result table (i.e. "CreateToCloseEvents " table) won't write the event. 

Is this a reasonable analysis?

## Options
1. The PDF linked earlier mentions that if I want to trigger insert on both left and the right side of the JOIN table, then I need to have another materialized view with the join clause tables reversed and target the same destination table. So I'm thinking if `A INNER JOIN B` missed some data because a row wasn't in B, then `B INNER JOIN A` should fill the remaining. 
2. Don't use MV but use a JOIN engine instead as suggested in the PDF doc. My concern with this is that the data in the JOIN engine is stored in RAM. What happens if the size of this table grows out of bounds? There is also some data corruption issue if the CH server restarted unexpectedly. 

Do these options and my understanding of the MV with JOIN clause fairly correct?

Thanks!

---

Also, is daisy chaining table with another table like I have above a pretty common pattern/use-case in ClickHouse? The way I'm using MV is basically a transformation function that inserts the result into the destination table . 

## Schema
<details><summary>CLICK ME</summary>
<p>

These are the simplified schema. The actual definitions has more columns but they are not used in any of the MV operations such as WHERE or JOIN ON clauses.

```sql
CREATE TABLE EventsKafka
(
    `raw` String
)
ENGINE = Kafka
SETTINGS kafka_broker_list = '<URL>', 
kafka_topic_list = '<topic>', 
kafka_group_name = '<clickhouse>', 
kafka_format = 'JSONAsString', 
kafka_handle_error_mode = 'stream'


CREATE MATERIALIZED VIEW EventsMV TO Events
(
    `event_time` DateTime64(9),
    `type` String,
    `order_id` String
) AS
SELECT
    parseDateTime64BestEffort(JSONExtractString(raw, 'event_time'), 9) AS event_time,
    JSONExtractString(raw, 'type') AS type,
    JSONExtractString(raw, 'order_id') AS order_id,
FROM EventsKafka
WHERE length(_error) = 0


CREATE TABLE Events
(
    `event_time` DateTime64(9),
    `type` String,
    `order_id` String
)
ENGINE = ReplicatedMergeTree('<PATH>', '{replica}')
PARTITION BY toYYYYMMDD(event_time)
ORDER BY event_time
SETTINGS index_granularity = 8192


CREATE MATERIALIZED VIEW CreateEventsMV TO CreateEvents
(
    `event_time` DateTime64(9),
    `type` String,
    `order_id` String
) AS
SELECT
    event_time,
    type,
    order_id
FROM Events
WHERE type = 'create'


CREATE TABLE CreateEvents
(
    `event_time` DateTime64(9),
    `type` String,
    `order_id` String
)
ENGINE = ReplicatedMergeTree('<PATH>', '{replica}')
PARTITION BY toYYYYMMDD(event_time)
PRIMARY KEY order_id
ORDER BY (order_id, event_time)
TTL date_trunc('second', event_time) + toIntervalMonth(3)
SETTINGS index_granularity = 8192


CREATE MATERIALIZED VIEW CloseEventsMV TO CloseEvents
(
    `event_time` DateTime64(9),
    `type` String,
    `order_id` String
) AS
SELECT
    event_time,
    type,
    order_id
FROM Events
WHERE type = 'close'


CREATE TABLE CloseEvents
(
    `event_time` DateTime64(9),
    `type` String,
    `order_id` String
)
ENGINE = ReplicatedMergeTree('<PATH>', '{replica}')
PARTITION BY toYYYYMMDD(event_time)
PRIMARY KEY order_id
ORDER BY (order_id, event_time)
TTL date_trunc('second', event_time) + toIntervalMonth(3)
SETTINGS index_granularity = 8192


CREATE MATERIALIZED VIEW CreateToCloseEventsMV TO CreateToCloseEvents 
(
    `order_id` String,
    `CreateOrder.event_time` DateTime64(9),
    `CloseOrder.event_time` DateTime64(9),
    `create_to_close_time_seconds` Int64
) AS
SELECT
    CloseOrder.order_id AS order_id,
    CreateOrder.event_time AS `CreateOrder.event_time`,
    CloseOrder.event_time AS `CloseOrder.event_time`,
    dateDiff('second', CreateOrder.event_time, close_ticket.event_time) AS create_to_close_time_seconds    
FROM CloseEvents AS CloseOrder
INNER JOIN CreateEvents AS CreateOrder ON CloseOrder.order_id = CreateOrder.order_id


CREATE TABLE CreateToCloseEvents
(
    `order_id` String,
    `CreateOrder.event_time` DateTime64(9),
    `CloseOrder.event_time` DateTime64(9),
    `create_to_close_time_seconds` Int64
)
ENGINE = ReplicatedMergeTree('<PATH>', '{replica}')  
PARTITION BY toYYYYMMDD(CloseOrder.event_time)
ORDER BY CloseOrder.event_time
TTL date_trunc('second', CloseOrder.event_time) + toIntervalMonth(12)
SETTINGS index_granularity = 8192
```

</p>
</details>

**Comment by den-crane** [comment]
I suggest to do it before inserting into CH (at the ETL).
Also check https://clickhouse.com/docs/en/sql-reference/statements/create/view/#window-view-experimental
https://altinity.com/blog/battle-of-the-views-clickhouse-window-view-vs-live-view

>`CreateOrder.event_time`

Don't use dots `.` in column names. Dot is reserved for Nested columns and has the special meaning. Use underscore.

Joins are not viable in this schema by many reasons. For example the ingestion happens on different replicas and becasue of the replication lag you will miss data.

You may try  another approach -- AggregatingMergeTree  

https://fiddle.clickhouse.com/96b32cc9-e4bd-458c-96f6-04fa13237328

```sql
CREATE TABLE EventsKafka(`raw` String) ENGINE = Null;

CREATE TABLE CreateToCloseEvents (
    `order_id` String,
    `CreateOrder_event_time` SimpleAggregateFunction(max, DateTime64(9)),
    `CloseOrder_event_time` SimpleAggregateFunction(max, DateTime64(9))
)ENGINE = AggregatingMergeTree
ORDER BY order_id;


CREATE MATERIALIZED VIEW EventsMV TO CreateToCloseEvents AS
SELECT
    parseDateTime64BestEffort(JSONExtractString(raw, 'event_time'), 9) AS event_time,
    JSONExtractString(raw, 'type') type,
    if ( type = 'close', toDateTime64(0, 9), event_time ) CreateOrder_event_time,
    if ( type = 'close', event_time, toDateTime64(0, 9) ) CloseOrder_event_time,  
    JSONExtractString(raw, 'order_id') AS order_id
FROM EventsKafka;

insert into EventsKafka values ('{"event_time":"2020-01-02 00:00:00.000", "type":"close", "order_id":"1"}');

insert into EventsKafka values ('{"event_time":"2020-01-01 00:00:00.000", "type":"open", "order_id":"1"}');



select order_id, max(CreateOrder_event_time), max(CloseOrder_event_time) from CreateToCloseEvents group by order_id;
SELECT
    order_id,
    max(CreateOrder_event_time),
    max(CloseOrder_event_time)
FROM CreateToCloseEvents
GROUP BY order_id

Query id: e3160a1a-26e7-49e9-b0da-1459f842ee8e

┌─order_id─┬───max(CreateOrder_event_time)─┬────max(CloseOrder_event_time)─┐
│ 1        │ 2020-01-01 00:00:00.000000000 │ 2020-01-02 00:00:00.000000000 │
└──────────┴───────────────────────────────┴───────────────────────────────┘

optimize table CreateToCloseEvents final;

select * from CreateToCloseEvents;

┌─order_id─┬────────CreateOrder_event_time─┬─────────CloseOrder_event_time─┐
│ 1        │ 2020-01-01 00:00:00.000000000 │ 2020-01-02 00:00:00.000000000 │
└──────────┴───────────────────────────────┴───────────────────────────────┘

```

https://gist.github.com/den-crane/d03524eadbbce0bafa528101afa8f794
