### ISSUE TITLE
How to create ansible playbook for clickhouse installation with source code and also git clone

### ISSUE THREAD

**Issue by targetdevos** [ClickHouse/ClickHouse#43871]
---
 - name: install install git cmake ccache python3 ninja-build
   hosts: clickhouse_server
   tasks:

           - name: Update apt-get repo and cache

             apt: update_cache=yes force_apt_get=yes cache_valid_time=3600 upgrade=dist
           - name: install list of package  git cmake ccache python3 ninja-build
             apt:
                     name:
                             - git
                             - cmake
                             - ccache
                             - python3
                             - ninja-build
                     state: present
                     update_cache: yes
           - name: git clone for clickhouse server
             git:
                     repo: https://github.com/ClickHouse/ClickHouse.git
                     dest: /home/debian/repo
                     force: yes
                     clone: yes
                     recursive: yes
                     update: yes

           - name: create directory build
             file:

                     path: build
                     state: directory
           - name: run multiple command on a line
             shell:
                     echo -e "\n Change directory to the build"
                     cd build/
           - name: run cmake clickhouse
             shell:
                     echo -e "\n start the clickhouse"
                     cmake ../ClickHouse
           - name: run the ninja
             shell:
                   echo -e "\n run the ninja"
-- INSERT --

**Comment by targetdevos** [comment]
Please help me ...My playbook not working....where is wrong?

**Comment by targetdevos** [comment]
fatal: [192.168.154.130]: FAILED! => {"changed": true, "cmd": "cd build\ncmake ../ClickHouse\nninja\n", "delta": "0:00:00.697643", "end": "2022-12-10 04:47:34.882255", "msg": "non-zero return code", "rc": 1, "start": "2022-12-10 04:47:34.184612", "stderr": "CMake Warning:\n  Ignoring extra path from command line:\n\n   \"../ClickHouse\"\n\n\nCMake Error: The source directory \"/root/ClickHouse\" does not appear to contain CMakeLists.txt.\nSpecify --help for usage, or press the help button on the CMake GUI.\nninja: error: loading 'build.ninja': No such file or directory", "stderr_lines": ["CMake Warning:", "  Ignoring extra path from command line:", "", "   \"../ClickHouse\"", "", "", "CMake Error: The source directory \"/root/ClickHouse\" does not appear to contain CMakeLists.txt.", "Specify --help for usage, or press the help button on the CMake GUI.", "ninja: error: loading 'build.ninja': No such file or directory"], "stdout": "", "stdout_lines": []}
fatal: [192.168.154.131]: FAILED! => {"changed": true, "cmd": "cd build\ncmake ../ClickHouse\nninja\n", "delta": "0:00:00.801190", "end": "2022-12-10 04:47:34.655223", "msg": "non-zero return code", "rc": 1, "start": "2022-12-10 04:47:33.854033", "stderr": "CMake Warning:\n  Ignoring extra path from command line:\n\n   \"../ClickHouse\"\n\n\nCMake Error: The source directory \"/root/ClickHouse\" does not appear to contain CMakeLists.txt.\nSpecify --help for usage, or press the help button on the CMake GUI.\nninja: error: loading 'build.ninja': No such file or directory", "stderr_lines": ["CMake Warning:", "  Ignoring extra path from command line:", "", "   \"../ClickHouse\"", "", "", "CMake Error: The source directory \"/root/ClickHouse\" does not appear to contain CMakeLists.txt.", "Specify --help for usage, or press the help button on the CMake GUI.", "ninja: error: loading 'build.ninja': No such file or directory"], "stdout": "", "stdout_lines": []}
#########This is the error send me after executed ansible playbook##############

**Comment by rschu1ze** [comment]
I am not familiar with ansible but error `ninja: error: loading 'build.ninja': No such file or directory` looks like the playbook `cd`'s into the wrong directory when starting the build. Please take a look at the build steps in the development guides ([here](https://clickhouse.com/docs/en/development/developer-instruction) and [here](https://clickhouse.com/docs/en/development/build)).
