### ISSUE TITLE
UDF not passing field value as parameter

### ISSUE THREAD

**Issue by uklft** [ClickHouse/ClickHouse#43877]
When calling an user defined function with a field of a query as argument it seems that the name of the field is passed, instead of the value:
Here is a ClickHouse fiddle:
https://fiddle.clickhouse.com/ad63433a-22ce-48b6-a4c8-767b38d0fddb

**Does it reproduce on recent release?**
Yes, i am testing on the official `22.9.5.25` docker image and fiddle on `22.11.1`.

**How to reproduce**
* Running version `22.9.5.25` within docker 
* No modifications to the config
* Tested through DBeaver

```sql
-- Setup tables
create or replace table table1(key Int32, data1 String) engine=MergeTree() order by key;
create or replace table table2(key Int32, data2 String) engine=MergeTree() order by key;
create or replace table table3(id_x Int32, data3 String) engine=MergeTree() order by id_x;

-- insert basic data
insert into table1 values(1, 'test_1_t1');
insert into table1 values(2, 'test_2_t1');
insert into table2 values(1, 'test_1_t2');
insert into table2 values(2, 'test_2_t2');
insert into table3 values(1, 'test');

-- create udf with select + join on table1 and tabl2
create or replace function test_function AS (in_param)  -> (
	select data1 
	from table1 t1 
	join table2 t2 on t1.key=t2.key 
	where t1.key = in_param
);

-- Call test_function with a value directly
select test_function(1);

-- Call test_function with the field of a query
select test_function(t3.id_x) from table3 t3 where data3 = 'test';
```

**Expected behavior**
I would expect the query to call `test_function` with a reference to the field value of `id_x`, or the value itself.
Instead, it seems to look for the column `id_x` in the fields of the query *inside* the UDF.

**Error message and/or stacktrace**
Above snipped produces this output:
```
test_1_t1

Received exception from server (version 22.11.1):
Code: 47. DB::Exception: Received from localhost:9000. DB::Exception: Missing columns: 'id_x' while processing query: 'SELECT data1 FROM table1 AS t1 ALL INNER JOIN table2 AS t2 ON key = t2.key WHERE key = id_x', required columns: 'data1' 'key' 't2.key' 'id_x', maybe you meant: ['data1','key'], joined columns: 't2.key' 'data2' '_part' '_part_index' '_part_uuid' '_partition_id' '_partition_value' '_sample_factor' '_part_offset' '_row_exists': While processing (SELECT data1 FROM table1 AS t1 INNER JOIN table2 AS t2 ON t1.key = t2.key WHERE t1.key = id_x) AS _subquery2. (UNKNOWN_IDENTIFIER)
(query: -- Call test_function with the field of a query
select test_function(t3.id_x) from table3 t3 where data3 = 'test';)
```

Apparently we are not the first ones to stumble upon this:
https://stackoverflow.com/questions/73148430/clickhouse-udf-not-passing-argumnets-as-expected

**Comment by kitaisreal** [comment]
It is valid behaviour. SQL UDF work as simple SQL substitutions, UDF arguments inside UDF body are replaced with query function call arguments, and function call in query is replaced with UDF body.
They cannot perform queries that does not work in ClickHouse.
When you write:
```sql
select test_function(t3.id_x) from table3 t3 where data3 = 'test';
```
It is transformed into:
```sql
select (select data1 from table1 t1 join table2 t2 on t1.key=t2.key where t1.key = t3.id_x) from table3 t3 where data3 = 'test';
```
Such query cannot be performed in ClickHouse because currently we do not support correlated subqueries. When correlated subqueries will be supported this query will work as expected.
