### ISSUE TITLE
Can't achive concurrent select query executions.

### ISSUE THREAD

**Issue by Rostish** [ClickHouse/ClickHouse#43896]
Hi.

It seems i cant execute select queries in parallel.

I have eight nodes cluster. Every node has next specification:
40vCPU, 256GB RAM, 22TB
CH version is 22.6.1.1985
There are no custom settings.

I have 12 java application service replicas. Every java service has ExecutorService with fixed pool of 10 threads.
It is assumed that the services execute in parallel queries using a random node from. Java services use hikari pool.
When i check metrics in zabbix, i don't see any highload. Screens in attachment. (every node has the same picture)

![image](https://user-images.githubusercontent.com/15521647/205361097-523a7c80-5785-43c9-a3eb-321b6bc58e40.png)
![image](https://user-images.githubusercontent.com/15521647/205361110-0527e256-f8fe-4c03-8e66-9a81f82eea82.png)
![image](https://user-images.githubusercontent.com/15521647/205361138-d18c9af9-8312-4b22-9ae6-ca3443f1618d.png)
![image](https://user-images.githubusercontent.com/15521647/205361166-292612c5-ed4e-4ff5-8cdb-f544b5d8fcc7.png)
![image](https://user-images.githubusercontent.com/15521647/205361194-8d0b007a-2531-4ff0-af01-f329f53a6fbd.png)
![image](https://user-images.githubusercontent.com/15521647/205361248-43b4a59b-2a54-41ce-8479-03d2b7a4c697.png)

This is my table:
`create table Test1
(
    InsertID            UUID,
    ResearchDate        Date,
    Count               UInt64,
    DRID UInt64,
    MID  UInt64,
    Attr           UInt16,
    Attr2           UInt16,
    Attr3           UInt16,
    Attr4          UInt16,
    Attr5           UInt16,
    Attr6          UInt16,
    Attr7           UInt16,
    Attr8           UInt16,
    Attr9           UInt16,
    Attr10           UInt16,
    Attr11           UInt16,
    Attr12           UInt16,
    Attr13           UInt16,
    Attr14           UInt16,
    Attr15           UInt16,
    Attr16           UInt16,
    Attr17           UInt16,
    Attr18           UInt16,
    Attr19           UInt16,
    Attr20           UInt16,
    Attr21           UInt16,
    Attr22           UInt16,
    Attr23          UInt16,
    Attr24           UInt16,
    GenerationDate      Date,
    ResearchWeek        Date,
    ResearchMonth       Date,
    ResearchQuarter     Date,
    ResearchYear        Date
)
    engine = ReplicatedMergeTree('/clickhouse/tables/{sinshard}/cr2', '{replica}')
        PARTITION BY ResearchDate
        ORDER BY (ResearchDate, DesktopRespondentID, MobileRespondentID)
        SETTINGS index_granularity = 8192;`
Queries are pretty simple, some agg with group by. Running time from seconds to several minutes.

I expect to see multiple parallel executions. About 20+ select in parallel in zabbix.

I think there is could be a problem with http client. It opens only one http connection and wait till executions is over. But i can't understand how to avoid it.

**Comment by den-crane** [comment]
1. If queries are very short they are unable to utilize all CPU.
2. queries can wait for Network / disk
3. share `select * from system.query_log` for most general/frequent query and check the column: profileEvents

**Comment by Rostish** [comment]
1. The main problem is that at any time on the zabix charts queue on the java application side up to 1000 tasks (about 1000 select quieries), but hdd, cpu, ram are not loaded at all. Only 8 http connections (avg 2), only 16gb ram from 256gb, only 8 active queries (avg 2).
2. From the java side or clickhouse side?
3. This information about two most frequent types of selects:

> {Query:1,SelectQuery:1,FileOpen:1437,Seek:18,ReadBufferFromFileDescriptorRead:2529,ReadBufferFromFileDescriptorReadBytes:402412743,ReadCompressedBytes:402284994,CompressedReadBufferBlocks:22117,CompressedReadBufferBytes:1372335968,OpenedFileCacheHits:1080,OpenedFileCacheMisses:1437,IOBufferAllocs:5039,IOBufferAllocBytes:571365695,ArenaAllocChunks:29761,ArenaAllocBytes:145121280,FunctionExecute:50304,MarkCacheHits:2517,CreatedReadBufferOrdinary:2517,DiskReadElapsedMicroseconds:484175,NetworkReceiveElapsedMicroseconds:285,NetworkReceiveBytes:86,CompiledFunctionExecute:3,SelectedParts:158,SelectedRanges:158,SelectedMarks:3441,SelectedRows:27603082,SelectedBytes:1368726888,ContextLock:2992,RWLockAcquiredReadLocks:152,RealTimeMicroseconds:15064329,UserTimeMicroseconds:7997532,SystemTimeMicroseconds:1128094,SoftPageFaults:175512,OSCPUWaitMicroseconds:10140,OSCPUVirtualTimeMicroseconds:9125294,OSReadChars:402409472,AggregationPreallocatedElementsInHashTables:1067580,AggregationHashTablesInitializedAsTwoLevel:40}

> {Query:1,SelectQuery:1,FileOpen:1114,Seek:494,ReadBufferFromFileDescriptorRead:1801,ReadBufferFromFileDescriptorReadBytes:237559615,ReadCompressedBytes:237559615,CompressedReadBufferBlocks:14477,CompressedReadBufferBytes:922549968,OpenedFileCacheHits:186,OpenedFileCacheMisses:1114,IOBufferAllocs:2605,IOBufferAllocBytes:279803015,ArenaAllocChunks:18385,ArenaAllocBytes:77373440,FunctionExecute:27896,MarkCacheHits:1300,CreatedReadBufferOrdinary:1300,DiskReadElapsedMicroseconds:103974,SelectedParts:62,SelectedRanges:62,SelectedMarks:3242,SelectedRows:26315504,SelectedBytes:921042640,ContextLock:198,RWLockAcquiredReadLocks:10,RealTimeMicroseconds:6337135,UserTimeMicroseconds:4237879,SystemTimeMicroseconds:521029,SoftPageFaults:2223,OSCPUWaitMicroseconds:5966,OSCPUVirtualTimeMicroseconds:4758928,OSReadChars:237558784}

**Comment by alexey-milovidov** [comment]
> I think there is could be a problem with http client. It opens only one http connection and wait till executions is over. But i can't understand how to avoid it.

You should open multiple connections to the server and send multiple queries in parallel.

**Comment by alexey-milovidov** [comment]
You can use `clickhouse-benchmark` tool with `--concurrency` parameter to check how the server can process concurrent requests: https://clickhouse.com/docs/en/operations/utilities/clickhouse-benchmark/
