### ISSUE TITLE
Messages about "gcc is unsupported" should be fatal.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#43912]
The problem: build continues after this message:

```
CMake Warning at cmake/tools.cmake:28 (message):
  Compilation with GCC is unsupported.  Please use Clang instead.
Call Stack (most recent call first):
  CMakeLists.txt:18 (include)


CMake Warning at cmake/tools.cmake:86 (message):
  Linking with gold is not recommended.  Please use lld.
Call Stack (most recent call first):
  CMakeLists.txt:18 (include)
```

These errors should stop the build.

Motivations: otherwise many users will accidentially build ClickHouse with GCC by mistake.
But we really don't support gcc. 

If we will make this error fatal, the professional users will still be able to edit CMakeLists to build with GCC if really needed, but we will prevent user mistakes.

**Comment by yumizhixiang** [comment]
Have you solved this issue？
