### ISSUE TITLE
How to config insert_distributed_sync for specific distributed table?

### ISSUE THREAD

**Issue by qmdt** [ClickHouse/ClickHouse#43924]
HI, this quesition is inherited from https://github.com/ClickHouse/ClickHouse/issues/28384

1.  About the configuration: insert_distributed_sync,  the following 2 methods have been found:
(1) config <insert_distributed_sync>1</insert_distributed_sync> in users.xml
(2) when insert one distributed table, in the same seesion, execute the command 'SET insert_distributed_sync = 1;'
but when I create distributed tables with settings insert_distributed_sync = 1, error occurs, Could this config Item can be set when create table?
![image](https://user-images.githubusercontent.com/8369775/205486128-8d1242a6-b03a-4825-8173-19cd00d2d1ef.png)

2. In actual use, the clickhouse-jdbc driver is used to access ClickHouse. The insert_distributed_sync needs to be set only for specific distributed tables.
but the SQL execute failed and throw exception：DB::Exception： Syntax error Multi-statements are not allowed
Is there any way to set insert_distributed_sync when use jdbc？

Sample code：
try( Connection connection = DriverManager.getConnection("jdbc::clickhouse//x.x.x.x:xxxxx", "user_name", "password");
      PreparedStatement statement = connection.prepareStatement("SET insert_distribute_sync = 1; insert into testdb.testtb values(?,?,?)")) {
      statement.setQueryTimeout(60000);
     statement.setObject(1, "2022-12-05");
     statement.setObject(2, "test");
     statement.setObject(3, "test2");
     statement.addBatch();
     statement.executeBatch();
     connection.commit();
     statement.clearBatch();
} catch (Exception e) {

}

**Comment by DerekChia** [comment]
Try `connection.prepareStatement("insert into testdb.testtb values(?,?,?) SETTINGS insert_distributed_sync=1"))`
