### ISSUE TITLE
Sparse Object(JSON)s

### ISSUE THREAD

**Issue by sinkingpoint** [ClickHouse/ClickHouse#43929]
**Use case**

We currently have relatively unstructured data that comes in (log lines) - these log lines come in as arbitrary JSON blobs, which have some structure but that structure can change over time. In general, there might be thousands of different columns, but any given log line uses ~20-30 of them.

Rather than defining columns upfront, I'd like to take advantage of the new support for dynamic columns - `Object(JSON)` and the like, but the storage layout for that makes this a bit untenable. In particular, every log line gets an entry for every column, even though the vast majority of them are not used for any given log line. 

**Describe the solution you'd like**

What I would like to be able to do is create "spare" JSON columns. i.e. I want to be able to define rows in the db that do not have all, or even most, of the values in the tuple created by the JSON column.

**Describe alternatives you've considered**

The older solution of defining multiple `Nested` columns, one per type still works (as defined in https://www.uber.com/en-NZ/blog/logging/), but this complicates querying and is inefficient in terms of storage (every variable of a given type has to be hoisted to the largest type)

**Comment by UnamedRus** [comment]
Related https://github.com/ClickHouse/ClickHouse/issues/41059 https://github.com/ClickHouse/ClickHouse/issues/23516#issuecomment-1018566829
