### ISSUE TITLE
avgWeighted function with decimal input returns garbage

### ISSUE THREAD

**Issue by antip00** [ClickHouse/ClickHouse#43928]
**Reproduce**

`select avgWeighted(toDecimal128(1, 38), toDecimal128(1, 38))`

I run this command on  22.8.7.34 and it returns 0.9332778386043761 but on  22.8.6.71 it returns 1.798977422385245

actually `select avgWeighted(1,1)` returns 1

**Comment by antip00** [comment]
On the other versions that I checked, it was also 0.9332778386043761, but I'm not sure if that is correct.

**Comment by UnamedRus** [comment]
```
SELECT avgWeighted(toDecimal128(1, 34), toDecimal128(1, 34))

Query id: 2ca1464f-372c-411a-bc95-4c6af9a01cd3

┌─avgWeighted(toDecimal128(1, 34), toDecimal128(1, 34))─┐
│                                   -64233924808.017845 │
└───────────────────────────────────────────────────────┘
```

**Comment by tavplubix** [comment]
Related to https://github.com/ClickHouse/ClickHouse/issues/31768

**Comment by myrrc** [comment]
I'll look at this bug
