### ISSUE TITLE
Fail the build if `DISABLE_HERMETIC_BUILD` is not set explicitly and a toolchain wasn't found

### ISSUE THREAD

**Issue by nvartolomei** [ClickHouse/ClickHouse#43923]
This slightly relates to #43912. I didn't want to propose it before that as it would make the life of GCC.

If we are making this change, I'd wish to add another request: Fail the build if `DISABLE_HERMETIC_BUILD` is not set explicitly and a toolchain wasn't found.

I made some changes to my environment I stopped setting the compilers explicitly to `cmake`. Instead I had installed clang-15 locally and used `update-alternatives` to override `/usr/bin/c{c,++}`. This resulted in TSAN builds failing to link and a good chunk of time spent figuring out what's wrong. Only to realize later that [PreLoad.cmake](https://github.com/ClickHouse/ClickHouse/blob/master/PreLoad.cmake#L58) has a weird logic for discovering the compiler and deciding if it is `clang`.

Requiring the user to explicitly set `DISABLE_HERMETIC_BUILD` when toolchain is not found will be mostly invisible for developers (I assume most are using clang anyway) but will make it harder to compile a wrong configuration based on the environment setting.

**Comment by rschu1ze** [comment]
preload.cmake is a bit of dark magic, CMake doesn't document the preload feature and CI builds set compiler and toolchain explicitly anyways. For the sake of simplicity, the discovery logic should generally be as least surprising as possible.

But I am a bit confused by your request. You did a build, ran `update-alternatives` (which changes the symbolic link `/usr/bin/clang` but not an env var), rebuild with `ninja` (i.e. w/o running `cmake` again) and the build broke? There is actually no way that CMake could pick up such a change. As far as I checked, CMake doesn't even pick up changed environment variables.
Looking at `preload.cmake`, I also don't get how the default toolchain (that is dependent on variable `DISABLE_HERMETIC_BUILD`) is related to the compiler choice.

To be on the safe side, the recommendation is to rebuild from scratch or pass the compiler via `-DCMAKE_C_COMPILER` directly.
