### ISSUE TITLE
Exception: the disk has unknow disk type : s3

### ISSUE THREAD

**Issue by xcsxxxxxxxx** [ClickHouse/ClickHouse#43935]
ClickHouse version:21.8.8.29

why this Exception:
DIskFactory: the disk has unknow disk type : s3

Configure ClickHouse to use the S3 bucket as a disk，my config.xml like this:
![截图](https://user-images.githubusercontent.com/109851469/205620604-e64c1441-c143-497f-9a03-5bf29c31aae0.PNG)

**Comment by den-crane** [comment]
21.8 is out of support.

Provide the full exception. It seems you use custom built clickhouse without s3 support

Check

```
 select * from system.build_options where name ilike '%s3%';
```

**Comment by xcsxxxxxxxx** [comment]
> select * from system.build_options where name ilike '%s3%';
find nothing
![ck2](https://user-images.githubusercontent.com/109851469/205836044-1884e382-3c77-41e6-9348-380a57d3f76e.PNG)

**Comment by xcsxxxxxxxx** [comment]
> 21.8 is out of support.
> 
> Provide the full exception. It seems you use custom built clickhouse without s3 support
> 
> Check
> 
> ```
>  select * from system.build_options where name ilike '%s3%';
> ```

**Comment by xcsxxxxxxxx** [comment]
> 21.8 is out of support.
> 
> Provide the full exception. It seems you use custom built clickhouse without s3 support
 full exception like this，my custom clickhouse is out of s3 support?

2022.12.05 20:40:13.608644 [ 160429 ] {} <Error> Application: Caught exception while loading metadata: Code: 137, e.displayText() = DB::Exception: DiskFactory: the disk 's3_disk' has unknown disk type: s3: Cannot attach table `system`.`query_thread_log` from metadata file /opt/neteco/clickhouse/database/store/a79/a791247a-9971-405d-a791-247a9971c05d/query_thread_log.sql from query ATTACH TABLE system.query_thread_log UUID '00fc9b38-016a-4edd-80fc-9b38016a6edd' (`event_date` Date, `event_time` DateTime, `event_time_microseconds` DateTime64(6), `query_start_time` DateTime, `query_start_time_microseconds` DateTime64(6), `query_duration_ms` UInt64, `read_rows` UInt64, `read_bytes` UInt64, `written_rows` UInt64, `written_bytes` UInt64, `memory_usage` Int64, `peak_memory_usage` Int64, `thread_name` String, `thread_id` UInt64, `master_thread_id` UInt64, `current_database` String, `query` String, `normalized_query_hash` UInt64, `is_initial_query` UInt8, `user` String, `query_id` String, `address` IPv6, `port` UInt16, `initial_user` String, `initial_query_id` String, `initial_address` IPv6, `initial_port` UInt16, `initial_query_start_time` DateTime, `initial_query_start_time_microseconds` DateTime64(6), `interface` UInt8, `os_user` String, `client_hostname` String, `client_name` String, `client_revision` UInt32, `client_version_major` UInt32, `client_version_minor` UInt32, `client_version_patch` UInt32, `http_method` UInt8, `http_user_agent` String, `http_referer` String, `forwarded_for` String, `quota_key` String, `revision` UInt32, `ProfileEvents` Map(String, UInt64), `ProfileEvents.Names` Array(String) ALIAS mapKeys(ProfileEvents), `ProfileEvents.Values` Array(UInt64) ALIAS mapValues(ProfileEvents)) ENGINE = MergeTree PARTITION BY toYYYYMM(event_date) ORDER BY (event_date, event_time) SETTINGS index_granularity = 8192: while loading database `system` from path /opt/neteco/clickhouse/database/metadata/system, Stack trace (when copying this message, always include the lines below):

0. ? @ 0x10270782 in /opt/neteco/clickhouse/usr/bin/clickhouse
1. ? @ 0x51953af in /opt/neteco/clickhouse/usr/bin/clickhouse
2. ? @ 0x4cd39b7 in /opt/neteco/clickhouse/usr/bin/clickhouse
3. ? @ 0xd72227e in /opt/neteco/clickhouse/usr/bin/clickhouse
4. ? @ 0xca7250f in /opt/neteco/clickhouse/usr/bin/clickhouse
5. ? @ 0xca7273a in /opt/neteco/clickhouse/usr/bin/clickhouse
6. ? @ 0xca728cc in /opt/neteco/clickhouse/usr/bin/clickhouse
7. ? @ 0xd0d254c in /opt/neteco/clickhouse/usr/bin/clickhouse
8. ? @ 0xd0df649 in /opt/neteco/clickhouse/usr/bin/clickhouse
9. ? @ 0xd0f8c6a in /opt/neteco/clickhouse/usr/bin/clickhouse
10. ? @ 0xdb77e3c in /opt/neteco/clickhouse/usr/bin/clickhouse
11. ? @ 0xd285092 in /opt/neteco/clickhouse/usr/bin/clickhouse
12. ? @ 0xd2885e2 in /opt/neteco/clickhouse/usr/bin/clickhouse
13. ? @ 0xcec0da2 in /opt/neteco/clickhouse/usr/bin/clickhouse
14. ? @ 0xd6f713c in /opt/neteco/clickhouse/usr/bin/clickhouse
15. ? @ 0xd6ff9d0 in /opt/neteco/clickhouse/usr/bin/clickhouse
16. ? @ 0xd7004d4 in /opt/neteco/clickhouse/usr/bin/clickhouse
17. ? @ 0x5202340 in /opt/neteco/clickhouse/usr/bin/clickhouse
18. ? @ 0x520308f in /opt/neteco/clickhouse/usr/bin/clickhouse
19. ? @ 0x52015e0 in /opt/neteco/clickhouse/usr/bin/clickhouse
20. ? @ 0x5200c1f in /opt/neteco/clickhouse/usr/bin/clickhouse
21. ? @ 0x8f3b in /usr/lib64/libpthread-2.28.so
22. clone @ 0xf8570 in /usr/lib64/libc-2.28.so
 (version 21.8.8.1)
2022.12.05 20:40:13.608770 [ 160429 ] {} <Information> Application: Shutting down storages.
2022.12.05 20:40:13.608814 [ 160429 ] {} <Debug> Application: Shut down storages.
2022.12.05 20:40:13.610061 [ 160429 ] {} <Debug> Application: Destroyed global context.
2022.12.05 20:40:13.615661 [ 160429 ] {} <Error> Application: DB::Exception: DiskFactory: the disk 's3_disk' has unknown disk type: s3: Cannot attach table `system`.`query_thread_log` from metadata file /opt/neteco/clickhouse/database/store/a79/a791247a-9971-405d-a791-247a9971c05d/query_thread_log.sql from query ATTACH TABLE system.query_thread_log UUID '00fc9b38-016a-4edd-80fc-9b38016a6edd' (`event_date` Date, `event_time` DateTime, `event_time_microseconds` DateTime64(6), `query_start_time` DateTime, `query_start_time_microseconds` DateTime64(6), `query_duration_ms` UInt64, `read_rows` UInt64, `read_bytes` UInt64, `written_rows` UInt64, `written_bytes` UInt64, `memory_usage` Int64, `peak_memory_usage` Int64, `thread_name` String, `thread_id` UInt64, `master_thread_id` UInt64, `current_database` String, `query` String, `normalized_query_hash` UInt64, `is_initial_query` UInt8, `user` String, `query_id` String, `address` IPv6, `port` UInt16, `initial_user` String, `initial_query_id` String, `initial_address` IPv6, `initial_port` UInt16, `initial_query_start_time` DateTime, `initial_query_start_time_microseconds` DateTime64(6), `interface` UInt8, `os_user` String, `client_hostname` String, `client_name` String, `client_revision` UInt32, `client_version_major` UInt32, `client_version_minor` UInt32, `client_version_patch` UInt32, `http_method` UInt8, `http_user_agent` String, `http_referer` String, `forwarded_for` String, `quota_key` String, `revision` UInt32, `ProfileEvents` Map(String, UInt64), `ProfileEvents.Names` Array(String) ALIAS mapKeys(ProfileEvents), `ProfileEvents.Values` Array(UInt64) ALIAS mapValues(ProfileEvents)) ENGINE = MergeTree PARTITION BY toYYYYMM(event_date) ORDER BY (event_date, event_time) SETTINGS index_granularity = 8192: while loading database `system` from path /opt/neteco/clickhouse/database/metadata/system
2022.12.05 20:40:13.615723 [ 160429 ] {} <Information> Application: shutting down
2022.12.05 20:40:13.615737 [ 160429 ] {} <Debug> Application: Uninitializing subsystem: Logging Subsystem
2022.12.05 20:40:13.617224 [ 160449 ] {} <Trace> BaseDaemon: Received signal -2
2022.12.05 20:40:13.617266 [ 160449 ] {} <Information> BaseDaemon: Stop SignalListener thread

**Comment by alexey-milovidov** [comment]
You are using an unofficial ClickHouse build.
Only official builds are supported.

Download it as follows:
```
curl https://clickhouse.com/ | sh
```
