### ISSUE TITLE
Sending Kubernetes logs To ClickHouse with Fluent Bit  Unable to display the original log in json format

### ISSUE THREAD

**Issue by ouyanghuangrunda** [ClickHouse/ClickHouse#43930]
>Sending Kubernetes logs To ClickHouse with Fluent Bit  Unable to display the original log in json format

>正常的java日志能看到，go语言程序输出的json日志显示不了

Normal java logs can be seen, but json logs output by go language programs cannot be displayed

**Comment by alexey-milovidov** [comment]
Not enough info was provided.
