### ISSUE TITLE
clickhouse is stored in hdfs, how do I change the number of default replicas of hdfs and blocksize of hdfs？

### ISSUE THREAD

**Issue by w182757427** [ClickHouse/ClickHouse#43931]
**This is my configuration file：** 
![image](https://user-images.githubusercontent.com/59718599/205567769-3986893c-b7dc-4959-9a0d-010885b8f30d.png)

**Whenever clickhouse creates a new block in hdfs, it always has 3 replicas and the blocksize is 64M.  How can I reduce replicas and increase the blocksize？**

**Comment by alexey-milovidov** [comment]
We don't support HDFS.
