### ISSUE TITLE
high virtual memory consumption after aggregate query run

### ISSUE THREAD

**Issue by chenxing-xc** [ClickHouse/ClickHouse#4394]
I have a question on ClickHouse virtual memory consumption, my clickhouse instance(18.14.10) consume huge virtual memory consumption:

![image](https://user-images.githubusercontent.com/34856920/52787571-40fd9180-3099-11e9-9017-dd34ca81a30d.png)

pmap also show huge [anon] blockes of this process, for example:
0000000000400000 192600K r-x-- clickhouse
000000000c016000 2600K rwx-- clickhouse
000000000c2a0000 2952K rwx-- [ anon ]
00007ea54b197000 1048576K rwx-- [ anon ]
00007ea60b197000 8388608K rwx-- [ anon ]
00007ea8bb197000 1310720K rwx-- [ anon ]
00007ea98b197000 491520K rwx-- [ anon ]
00007ea9b1197000 5505024K rwx-- [ anon ]
00007eab05197000 196608K rwx-- [ anon ]
00007eab1919b000 229376K rwx-- [ anon ]
00007eab3324b000 1474560K rwx-- [ anon ]
00007eab9c269000 262144K rwx-- [ anon ]
00007eabd5ab4000 393216K rwx-- [ anon ]
00007eabf3ac0000 196608K rwx-- [ anon ]

Does this symptom ring memory leak problem in my instance?  those anonymous block should be allocated by mmap in clickhouse, and should have been munmap back to system.

**Comment by ztlpn** [comment]
Virtual memory is not a scarce resource - there are 2^64 bytes of it :) You should instead look at the resident memory (RES in the `top` output) and it is ok in your screenshot.

Probably this is how jemalloc operates - allocate huge blocks of virtual memory and return unused physical memory to the system using the `madvise` syscall.
