### ISSUE TITLE
02422_allow_implicit_no_password and 02207_allow_plaintext_and_no_password tests are bad and need to be rewritten

### ISSUE THREAD

**Issue by nvartolomei** [ClickHouse/ClickHouse#43948]
- https://github.com/ClickHouse/ClickHouse/blob/master/tests/queries/0_stateless/02422_allow_implicit_no_password.sh
- https://github.com/ClickHouse/ClickHouse/blob/master/tests/queries/0_stateless/02207_allow_plaintext_and_no_password.sh

Issues:
- they are run only for default release build for no good reason (Tags: no-tsan, no-asan, no-ubsan, no-msan, no-parallel, no-fasttest)
- they start clickhouse using stateless directory as work dir and pollute it, bad local developer experience
- ~~they copy user.xml config to stateless directory, if they are scheduled to run in parallel one of them might start with unexpected config or fail with "file exists"~~ later add: they have no-parallel tag, it is ok

These would be much better as integration tests instead. Or, extend the bash script to create clean workdir per test.

**Comment by tavplubix** [comment]
Agree, functional tests should not run another server.

But it's even worse, these tests were just copy-pasted from `01594_too_low_memory_limits` (removed in https://github.com/ClickHouse/ClickHouse/commit/4e05c08360d2a10131d856fd2a795c52e4ef5c06). Therefore, these tests contain completely incorrect comments:
https://github.com/ClickHouse/ClickHouse/blob/master/tests/queries/0_stateless/02207_allow_plaintext_and_no_password.sh#L3-L6

> These would be much better as integration tests instead.

Not necessarily, maybe we can keep them functional, just add required configs to `tests/config/install.sh` and do not run another server.

**Comment by tavplubix** [comment]
The tests are still bad and still have to be rewritten

**Comment by Algunenano** [comment]
Still there. Still a pain.
