### ISSUE TITLE
Removing unneeded columns from CTE subquery confuses interpretation of positional argument(s)

### ISSUE THREAD

**Issue by ArctypeZach** [ClickHouse/ClickHouse#43964]
**Description**
Selecting a subset of columns contained in a CTE subquery throws a 'Positional argument out of bounds' exception.  Can be reproduced on v22.11.

**Reproduction Steps**
Executing this query against the 'UK Property Price Paid' sample dataset should trigger the error:
```
with top_counties as (
    select county,
        count(*) as transactions
    from
        pp_complete
    where
        toStartOfMonth(parseDateTimeBestEffort(time)) = '2019-09-01'
    group by
        1
    order by
        2 desc
    limit
        5
)
select county from top_counties
```
**Error message:**
```
"Code: 43. DB::Exception: Positional argument out of bounds: 2 (exprected in range [1, 1]. (ILLEGAL_TYPE_OF_ARGUMENT) (version 22.11.1.19280 (official build))\n"
```

**Expected result:**
| county             |
|--------------------|
| GREATER LONDON     |
| GREATER MANCHESTER |
| WEST YORKSHIRE     |
| WEST MIDLANDS      |
| ESSEX              |

**Comment by yakov-olkhovskiy** [comment]
Positional argument in subquery doesn't work properly - apparently it takes number of columns from outer query :

```
CREATE TABLE positional_arguments(one Int, two Int, three Int) ENGINE=Memory();
INSERT INTO positional_arguments VALUES (10, 20, 30), (20, 20, 10), (30, 10, 20);

select one from (select one, two from positional_arguments order by 2 desc);
Received exception:
Code: 43. DB::Exception: Positional argument out of bounds: 2 (exprected in range [1, 1]. (ILLEGAL_TYPE_OF_ARGUMENT)

select one, two from (select one, two from positional_arguments order by 2 desc);
┌─one─┬─two─┐
│  10 │  20 │
│  20 │  20 │
│  30 │  10 │
└─────┴─────┘
3 rows in set. Elapsed: 0.001 sec.

select one from (select one, two from positional_arguments order by two desc);
┌─one─┐
│  10 │
│  20 │
│  30 │
└─────┘
3 rows in set. Elapsed: 0.001 sec.
```

**Comment by kssenii** [comment]
> apparently it takes number of columns from outer query

not from outer query, the number is less than 2 because of column pruning, but I though I fixed it here https://github.com/ClickHouse/ClickHouse/pull/39293...
