### ISSUE TITLE
When I excute drop partition, the server crash.

### ISSUE THREAD

**Issue by Sallery-X** [ClickHouse/ClickHouse#43969]
version: 22.8.10.29

 <Fatal> BaseDaemon: Code: 49. DB::Exception: Part 1651075200_0_0_999999999_999999999 intersects next part 1651075200_0_138_135. It is a bug or a result of manual intervention in the ZooKeeper data. (LOGICAL_ERROR), Stack trace (when copying this message, always include the lines below):

**Comment by tavplubix** [comment]
> 1651075200_0_0_999999999_999999999
> 1651075200_0_138_135

Most likely it's a result of manual intervention in the ZooKeeper data. Please provide relevant logs if you're sure it's not.
