### ISSUE TITLE
insert_quorum and high available ,should enable insert_quorum ?

### ISSUE THREAD

**Issue by Yanbuc** [ClickHouse/ClickHouse#43996]
my cluster is two shard, two replica.
I make a experiment . 
Set insert_quorum =2, and kill a node , then i insert data to a node which is a replica for the node killed,
and the insert failed.
So if enable insert_quorum setting, and the cluster maybe is not high available. 
I found the description that if not enable insert_quorum setting, maybe loss data in a situation .
So  i am confused about it .

**Comment by melvynator** [comment]
This feature only addresses the use case when you want not to lose your data after successful insert on a single replica when data is not replicated and server fails.

If an insert fail, then you need to retry.
