### ISSUE TITLE
Make backup system table persistent

### ISSUE THREAD

**Issue by e-mars** [ClickHouse/ClickHouse#43995]
**Use case**
when researching status of backups/restores, table `system.backups` to script or diagnose when issues happened and on which backup/restore jobs.

Currently a restart of the node backup table is blank.

**Describe the solution you'd like**
Make the `systems.backups` table persistent even after restart of the node(s) that were used to initiate,

**Describe alternatives you've considered**
copying off the backups table to another user defined table or info queried and stored outside ClickHouse DB.

user request to be persistent not transient :
https://github.com/ClickHouse/ClickHouse/issues/43225#issuecomment-1314484470

cc: @vitlibar

**Comment by mlex** [comment]
As an alternative we could add a new `backup_logs` table that keeps track of finished (failed and successful) backups. This would be much easier to implement (and should cover most use cases as well).

`system.backups` represents the "state" of currently executing or executed backups and in general all tables without `_log` suffix are virtual ones (generated on-fly using internal data structure)

To make it "persistent" we need to make backups to survive server restart (again the same as for system.mutations ), which is another, bigger task.

**Comment by aadant** [comment]
it is a good idea to have a persisted system table for backups. It exists on commercial warehouses like this one :

https://help.sap.com/docs/SAP_IQ/a898e08b84f21015969fa437e89860c8/a5cad61984f21015a1bd99ca65775698.html

**Comment by UnamedRus** [comment]
> To make it "persistent" we need to make backups to survive server restart (again the same as for system.mutations ), which is another, bigger task.

We can use KeeperMap storage for such table, it will make it resilent to ClickHouse disk faults

**Comment by sirvickr** [comment]
Hi there. Please assign me to this task, I'm starting to work on it.

**Comment by melvynator** [comment]
@sirvickr Thank you for raising your hand! I've assigned you.

**Comment by melvynator** [comment]
The way I see it is that we need the `system.backups` table to give you information on the current backup table like the `system.processes` table so it doesn't need to be persisted. The `system.backup_log` table will have the persisted information similarly to the `query_log`

**Comment by qoega** [comment]
system.backup_log is persistent
https://github.com/ClickHouse/ClickHouse/issues/53221
