### ISSUE TITLE
 Poco::Exception. Code: 1000, e.code() = 22, Invalid argument  when use ReplicatedMergeTree 1 shard 1 replica.

### ISSUE THREAD

**Issue by phpdpy** [ClickHouse/ClickHouse#43997]
2022.12.07 10:50:05.475585 [ 15653 ] {} <Error> sr.userinfo (e91d368f-8cc8-4a2d-80ee-cbd85a5406a9): auto DB::StorageReplicatedMergeTree::processQueueEntry(ReplicatedMergeTreeQueue::SelectedEntryPtr)::(anonymous class)::operator()(DB::StorageReplicatedMergeTree::LogEntryPtr &) const: Poco::Exception. Code: 1000, e.code() = 22, Invalid argument, Stack trace (when copying this message, always include the lines below):

0. Poco::Net::SocketImpl::error(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x159abe35 in /usr/bin/clickhouse
1. Poco::Net::SocketImpl::connect(Poco::Net::SocketAddress const&, Poco::Timespan const&) @ 0x159ac3df in /usr/bin/clickhouse
2. Poco::Net::HTTPSession::connect(Poco::Net::SocketAddress const&) @ 0x1598b656 in /usr/bin/clickhouse
3. Poco::Net::HTTPClientSession::reconnect() @ 0x15977041 in /usr/bin/clickhouse
4. Poco::Net::HTTPClientSession::sendRequest(Poco::Net::HTTPRequest&) @ 0x15976203 in /usr/bin/clickhouse
5. ? @ 0x12a2dc82 in /usr/bin/clickhouse
6. ? @ 0x12a29388 in /usr/bin/clickhouse
7. ? @ 0x12a27fbf in /usr/bin/clickhouse
8. ? @ 0x12a0e65c in /usr/bin/clickhouse
9. DB::DataPartsExchange::Fetcher::fetchSelectedPart(std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::Context const>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, DB::ConnectionTimeouts const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Throttler>, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::optional<DB::CurrentlySubmergingEmergingTagger>*, bool, std::__1::shared_ptr<DB::IDisk>) @ 0x12a0aa4f in /usr/bin/clickhouse
10. ? @ 0x12805532 in /usr/bin/clickhouse
11. DB::StorageReplicatedMergeTree::fetchPart(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, unsigned long, std::__1::shared_ptr<zkutil::ZooKeeper>, bool) @ 0x127358b6 in /usr/bin/clickhouse
12. DB::StorageReplicatedMergeTree::executeFetch(DB::ReplicatedMergeTreeLogEntry&, bool) @ 0x127267cf in /usr/bin/clickhouse
13. DB::StorageReplicatedMergeTree::executeLogEntry(DB::ReplicatedMergeTreeLogEntry&) @ 0x127139e7 in /usr/bin/clickhouse
14. ? @ 0x1280329f in /usr/bin/clickhouse
15. DB::ReplicatedMergeTreeQueue::processEntry(std::__1::function<std::__1::shared_ptr<zkutil::ZooKeeper> ()>, std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&, std::__1::function<bool (std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&)>) @ 0x12ce7545 in /usr/bin/clickhouse
16. DB::StorageReplicatedMergeTree::processQueueEntry(std::__1::shared_ptr<DB::ReplicatedMergeTreeQueue::SelectedEntry>) @ 0x1275f11c in /usr/bin/clickhouse
17. ? @ 0x12803f31 in /usr/bin/clickhouse
18. DB::MergeTreeBackgroundExecutor<DB::OrdinaryRuntimeQueue>::routine(std::__1::shared_ptr<DB::TaskRuntimeData>) @ 0x78b078b in /usr/bin/clickhouse
19. DB::MergeTreeBackgroundExecutor<DB::OrdinaryRuntimeQueue>::threadFunction() @ 0x78b0410 in /usr/bin/clickhouse
20. ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >::worker(std::__1::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0x797c1ec in /usr/bin/clickhouse
21. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) @ 0x797ef17 in /usr/bin/clickhouse
22. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x797872c in /usr/bin/clickhouse
23. ? @ 0x797de3e in /usr/bin/clickhouse
24. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
25. __clone @ 0xfeb0d in /usr/lib64/libc-2.17.so
 (version 22.9.3.18 (official build))

**Comment by den-crane** [comment]
Provide the "create table" command.

**Comment by phpdpy** [comment]
> Provide the "create table" command.

create database sr ON CLUSTER cluster_1shards_1replicas;

CREATE TABLE IF NOT EXISTS sr.userinfo_consumer
(
    TIME          DateTime(),
    NAME          String,
    ADDRESS       String,
    CITY          String,
    NATION        String,
    REGION        String,
    PHONE         String,
    MKTSEGMENT    String

) ENGINE = Kafka()
SETTINGS
    kafka_broker_list = '172.168.1.209:9092',
    kafka_topic_list = 'USERINFO',
    kafka_group_name = 'USERINFOsr',
    kafka_format = 'JSONEachRow',
    kafka_skip_broken_messages = 100000;


CREATE TABLE IF NOT EXISTS sr.userinfo ON CLUSTER cluster_1shards_1replicas
(
    TIME          DateTime(),
    NAME          String,
    ADDRESS       String,
    CITY          String,
    NATION        String,
    REGION        String,
    PHONE         String,
    MKTSEGMENT    String
)
Engine = ReplicatedMergeTree('/cluster_1shards_1replicas/sr/userinfo/1', '{replica}')
PARTITION BY toYYYYMMDD(TIME)
ORDER BY toYYYYMMDD(TIME);


CREATE TABLE IF NOT EXISTS sr.userinfo_all ON CLUSTER cluster_1shards_1replicas
(
    TIME          DateTime(),
    NAME          String,
    ADDRESS       String,
    CITY          String,
    NATION        String,
    REGION        String,
    PHONE         String,
    MKTSEGMENT    String
)
Engine = Distributed(cluster_1shards_1replicas, sr, userinfo, rand());


CREATE MATERIALIZED VIEW IF NOT EXISTS sr.userinfo_transfer TO sr.userinfo_all AS
SELECT *
FROM sr.userinfo_consumer;

**Comment by phpdpy** [comment]
> Provide the "create table" command.

CREATE TABLE：

create database sr ON CLUSTER cluster_1shards_1replicas;

CREATE TABLE IF NOT EXISTS sr.userinfo_consumer
(
TIME DateTime(),
NAME String,
ADDRESS String,
CITY String,
NATION String,
REGION String,
PHONE String,
MKTSEGMENT String

) ENGINE = Kafka()
SETTINGS
kafka_broker_list = '172.168.1.209:9092',
kafka_topic_list = 'USERINFO',
kafka_group_name = 'USERINFOsr',
kafka_format = 'JSONEachRow',
kafka_skip_broken_messages = 100000;

CREATE TABLE IF NOT EXISTS sr.userinfo ON CLUSTER cluster_1shards_1replicas
(
TIME DateTime(),
NAME String,
ADDRESS String,
CITY String,
NATION String,
REGION String,
PHONE String,
MKTSEGMENT String
)
Engine = ReplicatedMergeTree('/cluster_1shards_1replicas/sr/userinfo/1', '{replica}')
PARTITION BY toYYYYMMDD(TIME)
ORDER BY toYYYYMMDD(TIME);

CREATE TABLE IF NOT EXISTS sr.userinfo_all ON CLUSTER cluster_1shards_1replicas
(
TIME DateTime(),
NAME String,
ADDRESS String,
CITY String,
NATION String,
REGION String,
PHONE String,
MKTSEGMENT String
)
Engine = Distributed(cluster_1shards_1replicas, sr, userinfo, rand());

CREATE MATERIALIZED VIEW IF NOT EXISTS sr.userinfo_transfer TO sr.userinfo_all AS
SELECT *
FROM sr.userinfo_consumer;

**Comment by alexey-milovidov** [comment]
This happens due to a misconfiguration - when a replica advertises its address incorrectly. Check the configuration file around the `interserver_host` setting.
