### ISSUE TITLE
Ephemeral columns with Map type crash the server

### ISSUE THREAD

**Issue by vlourme** [ClickHouse/ClickHouse#44010]
**Describe what's wrong**

Creating a table with a Map-type Ephemeral column will make the server crash on the restart because of wrongly save metadata.

Fiddle to reproduce: https://fiddle.clickhouse.com/81fc3a83-f7ea-43c2-afad-2e2940d04e8c

**Does it reproduce on recent release?**

Tested on version 22.11.1.1286.

**How to reproduce**

* Use version 22.11.x
* Use the fiddle above to reproduce.

**Expected behavior**

When creating a `EPHEMERAL` columns, a default value is assigned.
Example with a Int32:
```sql
CREATE TABLE name (
  example_col Int32 EPHEMERAL
) -- ... engine stuff here ...
```

Metadata will assign a default value:
```sql
CREATE TABLE name (
  example_col Int32 EPHEMERAL 0
) -- ... engine stuff here ...
```

But, with Map-type, no default value gets assigned, only a `()` (empty parenthesis).

**Error message and/or stacktrace**

```
2022.12.07 14:59:29.359153 [ 11464597 ] {} <Error> Application: DB::Exception: Syntax error (in file /Users/vlourme/Desktop/ch/store/75e/75e717de-1bbd-4011-802c-acd04e9a3409/bug_ephemeral.sql): failed at position 118 ('(') (line 4, col 41): (),
    `result` Int32 DEFAULT (data['number']) * 2
)
ENGINE = MergeTree
ORDER BY id
SETTINGS index_granularity = 8192
. Expected one of: literal, NULL, number, Bool, true, false, string literal, NOT, COMMENT, CODEC, TTL, token, Comma, ClosingRoundBracket: Cannot parse definition from metadata file /Users/vlourme/Desktop/ch/store/75e/75e717de-1bbd-4011-802c-acd04e9a3409/bug_ephemeral.sql
```

**Additional context**

The issue can't be fixed by setting a default expression after `EPHEMERAL`, this, for example will not work:
```sql
CREATE TABLE bug_ephemeral (
    id Int32,
    data Map(String, Int32) EPHEMERAL {},
    result Int DEFAULT data['number'] * 2
)
Engine = MergeTree()
ORDER BY (id);
```

But this, is accepted:
```sql
CREATE TABLE bug_ephemeral (
    id Int32,
    data Int32 EPHEMERAL 12,
    result Int DEFAULT data * 2
)
Engine = MergeTree()
ORDER BY (id);
```

**Comment by alexey-milovidov** [comment]
@yakov-olkhovskiy consider adding random DEFAULT/MATERIALIZED/ALIAS to the AST Fuzzer.
