### ISSUE TITLE
Memory leak in version 22.8.9.24.

### ISSUE THREAD

**Issue by nikola2188** [ClickHouse/ClickHouse#44029]
We use version 22.8.9.24. And apparently there are memory leaks. We use selfwritten connectors to insert data from kafka. RAM usage increases as time goes by

**Comment by alexey-milovidov** [comment]
It is possible to have memory growth up to a certain point where it will remain. It is not a memory leak.

**Comment by Angry1980** [comment]
Hey guys, you have not even given my colleague a chance to share more information :) 
memory usage grows significantly during the time, if we start from usage of half of available physical memory, after few weeks it eats almost everything and even simple queries can't be fulfilled
we have to restart clickhouse nodes periodically and it helps to decrease memory usage
i understand the reason can be something specific in our use cases, 
what can we check to give you more info about that ?

**Comment by den-crane** [comment]
@Angry1980 Because a shared Zero information. Check this https://kb.altinity.com/altinity-kb-setup-and-maintenance/altinity-kb-who-ate-my-memory/

>if we start from usage of half of available physical memory, after few weeks it eats almost everything and even simple queries can't be fulfilled

This is expected behaviour if you have 2GB of RAM and there is a solution. This is not expected behaviour if you have 200GB of RAM. 

You should provide more information if you need the proper answer.

**Comment by den-crane** [comment]
22.8.9.24 is obsolete. Supported version is 22.8.11.15

**Comment by nikola2188** [comment]
<img width="832" alt="Screenshot 2022-12-14 at 07 58 17" src="https://user-images.githubusercontent.com/120087997/207527682-7002c125-2a08-4ae1-b6e4-72791c7e78f3.png">

I will try updating the version and reopen in case the situation repeats itself.

**Comment by nikola2188** [comment]
<img width="1714" alt="image" src="https://user-images.githubusercontent.com/120087997/207809230-22f58f4f-2553-4143-8858-49f17f89382a.png">
I got statistics for a month. You can see that after a restart there is a drastic drop in memory usage. Will be back once we update the version.

**Comment by den-crane** [comment]
https://clickhouse.com/docs/en/operations/caches/ 
https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings/#server-mark-cache-size
https://clickhouse.com/docs/en/sql-reference/statements/system/#drop-mark-cache
