### ISSUE TITLE
why Local node query delay for 3s？

### ISSUE THREAD

**Issue by kaynewu** [ClickHouse/ClickHouse#44022]
Clickhouse  version： 22.9.1.4
Simple count query: select count(1) from business.http_log 
Distributed table sql start at 2022-12-08 09:21:54 , but local table query start at  2022-12-08 09:21:57,  why 3s delay?
![image](https://user-images.githubusercontent.com/5574794/206334178-9be53f0f-3b34-43e9-9e11-e599df602d38.png)

**Comment by alexey-milovidov** [comment]
You can check what the query is doing during these three seconds by using the Query Profiler or the `system.stack_trace` table: https://clickhouse.com/docs/en/operations/optimizing-performance/sampling-query-profiler/

There can be various reasons, including TCP retransmits. Old Linux kernels (3.2 and before) have three seconds for (slow) TCP retransmit timeout, as well as a bug leading to packet loss if IPv6 is enabled, even for localhost connections. Although it's unlikely that this is the reason.
