### ISSUE TITLE
Segmentation fault while sending trace_type = 'ProfileEvent' to trace log

### ISSUE THREAD

**Issue by kssenii** [ClickHouse/ClickHouse#44037]
https://s3.amazonaws.com/clickhouse-test-reports/43987/3725cf4aa7a9aa022b11d08b2f8e4f7f0dd70283/stress_test__ubsan_/gdb.log

**Comment by kssenii** [comment]
cc @CurtizJ

**Comment by kssenii** [comment]
Can be related to https://github.com/ClickHouse/ClickHouse/pull/43639

**Comment by CurtizJ** [comment]
Ah, quite stupid stackoverflow.
