### ISSUE TITLE
Kerberos & DNS: "Cannot find KDC for realm" 

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#44040]
You can get a message "Cannot find KDC for realm" in ClickHouse when trying to connect to the Kerberosed external server (Kafka, and others), while other krb5 clients on the same system with the same configuration work properly.

That can happen when the krb5.conf file have [dns_lookup_kdc=true](https://web.mit.edu/kerberos/krb5-1.19/doc/admin/conf_files/krb5_conf.html) setting which means that

> DNS SRV records should be used to locate the KDCs and other servers for a realm, if they are not listed in the krb5.conf information for the realm. 

and the KDC address for the realm was not explicitly set in krb5.conf. 

ClickHouse uses build-in krb5 lib, and the support for the DNS lookups was disabled ([see KRB5_DNS_LOOKUP](https://github.com/ClickHouse/ClickHouse/blob/da01982652d6fe8e4d1fdcc2a88b0b2040ca8568/contrib/krb5-cmake/autoconf_linux.h#L594)) at compile time (for unknown reason), so clickhouse was not able to find the KDC for the realm, while other software on the same system (with DNS lookups enabled) is able to find the KDC through the DNS and work properly. 

###  Workaround

add the realm KDC explicitly to krb5.conf, for example

```
[realms]
    ATHENA.MIT.EDU = {
        kdc = 10.0.0.10
    }
```

To fix that we need to enable  https://github.com/ClickHouse/ClickHouse/blob/da01982652d6fe8e4d1fdcc2a88b0b2040ca8568/contrib/krb5-cmake/autoconf_linux.h#L594

**Comment by Kangho-Lee** [comment]
@filimonov How can I enable `KRB5_DNS_LOOKUP` config? Is this merged latest ck version?

**Comment by filimonov** [comment]
It can be only enabled at compile time.
Afaik nobody worked on fixing that so far.

**Comment by alexey-milovidov** [comment]
We don't support alternative builds.

**Comment by Slach** [comment]
@alexey-milovidov 
This is not alternative builds, this issue related to disabled option in compile time which will have misbehavior if `kerberos` configured with some specific options

**Comment by alexey-milovidov** [comment]
Send a pull request.
