### ISSUE TITLE
Error compiling llvm of Clickhouse 

### ISSUE THREAD

**Issue by Grfire** [ClickHouse/ClickHouse#44043]
try to compiling clickhouse of the latest
Cmake version
3.22.1
Ninja version
1.10.1

FAILED: contrib/llvm-project/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/CodeGenSchedule.cpp.o 
/usr/bin/c++ -DSTD_EXCEPTION_HAS_STACK_TRACE=1 -D_GNU_SOURCE -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/mnt/chuhedb/ClickHouse/build/contrib/llvm-project/llvm/utils/TableGen -I/mnt/chuhedb/ClickHouse/contrib/llvm-project/llvm/utils/TableGen -I/mnt/chuhedb/ClickHouse/build/contrib/llvm-project/llvm/include -I/mnt/chuhedb/ClickHouse/contrib/llvm-project/llvm/include -I/mnt/chuhedb/ClickHouse/base/glibc-compatibility/memcpy -isystem /mnt/chuhedb/ClickHouse/contrib/llvm-project/libcxx/include -isystem /mnt/chuhedb/ClickHouse/contrib/llvm-project/libcxxabi/include -isystem /mnt/chuhedb/ClickHouse/contrib/libunwind/include -fdiagnostics-color=always -fsized-deallocation -fcoroutines  -pipe -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -fasynchronous-unwind-tables -ffile-prefix-map=/mnt/chuhedb/ClickHouse=. -falign-functions=32 -Wa,-mbranches-within-32B-boundaries -w -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-redundant-move -Wno-pessimizing-move -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wmisleading-indentation -fdiagnostics-color -ffunction-sections -fdata-sections -O2 -g -DNDEBUG -O3 -g -gdwarf-4  -fno-pie   -D OS_LINUX -g0 -Werror -nostdinc++ -std=c++14 -MD -MT contrib/llvm-project/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/CodeGenSchedule.cpp.o -MF contrib/llvm-project/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/CodeGenSchedule.cpp.o.d -o contrib/llvm-project/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/CodeGenSchedule.cpp.o -c /mnt/chuhedb/ClickHouse/contrib/llvm-project/llvm/utils/TableGen/CodeGenSchedule.cpp
In file included from /mnt/chuhedb/ClickHouse/contrib/llvm-project/libcxx/include/__functional/invoke.h:17,
                 from /mnt/chuhedb/ClickHouse/contrib/llvm-project/libcxx/include/type_traits:421,
                 from /mnt/chuhedb/ClickHouse/contrib/llvm-project/libcxx/include/limits:107,
                 from /mnt/chuhedb/ClickHouse/contrib/llvm-project/libcxx/include/math.h:309,
                 from /mnt/chuhedb/ClickHouse/contrib/llvm-project/libcxx/include/cmath:309,
                 from /mnt/chuhedb/ClickHouse/contrib/llvm-project/llvm/include/llvm/Support/MathExtras.h:19,
                 from /mnt/chuhedb/ClickHouse/contrib/llvm-project/llvm/include/llvm/ADT/APInt.h:19,
                 from /mnt/chuhedb/ClickHouse/contrib/llvm-project/llvm/utils/TableGen/CodeGenSchedule.h:17,
                 from /mnt/chuhedb/ClickHouse/contrib/llvm-project/llvm/utils/TableGen/CodeGenSchedule.cpp:14:
/mnt/chuhedb/ClickHouse/contrib/llvm-project/libcxx/include/__type_traits/decay.h: In instantiation of 'struct std::__1::__decay<const llvm::APInt&, true>':
/mnt/chuhedb/ClickHouse/contrib/llvm-project/libcxx/include/__type_traits/decay.h:56:89:   required from 'struct std::__1::decay<const llvm::APInt&&>'
/mnt/chuhedb/ClickHouse/contrib/llvm-project/libcxx/include/__utility/pair.h:132:16:   required by substitution of 'template<class _Tuple, typename std::__1::enable_if<typename std::__1::conditional<(std::__1::__tuple_like_with_size<_Tuple, 2, typename std::__1::remove_cv<typename std::__1::remove_reference<_Tp>::type>::type>::value && (! std::__1::is_same<typename std::__1::decay<_Tp>::type, std::__1::pair<const llvm::Record*, llvm::OpcodeInfo> >::value)), std::__1::pair<const llvm::Record*, llvm::OpcodeInfo>::_CheckTupleLikeConstructor, std::__1::__check_tuple_constructor_fail>::type::__enable_implicit<_Tuple>(), void>::type* <anonymous> > constexpr std::__1::pair<const llvm::Record*, llvm::OpcodeInfo>::pair(_Tuple&&) [with _Tuple = const llvm::APInt&&; typename std::__1::enable_if<typename std::__1::conditional<(std::__1::__tuple_like_with_size<_Tuple, 2, typename std::__1::remove_cv<typename std::__1::remove_reference<_Tp>::type>::type>::value && (! std::__1::is_same<typename std::__1::decay<_Tp>::type, std::__1::pair<const llvm::Record*, llvm::OpcodeInfo> >::value)), std::__1::pair<const llvm::Record*, llvm::OpcodeInfo>::_CheckTupleLikeConstructor, std::__1::__check_tuple_constructor_fail>::type::__enable_implicit<_Tuple>(), void>::type* <anonymous> = <missing>]'
/mnt/chuhedb/ClickHouse/contrib/llvm-project/llvm/utils/TableGen/CodeGenSchedule.cpp:372:69:   required from here
/mnt/chuhedb/ClickHouse/contrib/llvm-project/libcxx/include/__type_traits/decay.h:47:30: error: forming pointer to reference type 'std::__1::remove_extent<const llvm::APInt&>::type' {aka 'const llvm::APInt&'}
   47 |                      >::type type;
      |                              ^~~~
[35/6130] Building CXX object contrib/llvm-project/llvm/lib/MC/CMakeFiles/LLVMMC.dir/MCContext.cpp.o

**Comment by alexey-milovidov** [comment]
```
/usr/bin/c++
```

Only `clang` can be used to compile ClickHouse.
`gcc` cannot be used.

**Comment by Grfire** [comment]
sorry to review this issues too late. this reason , i used version of clang is outdated

**Comment by Grfire** [comment]
sorry to reply this issues too late. this reason , i used version of clang is outdated
