### ISSUE TITLE
Compression codec suggestor

### ISSUE THREAD

**Issue by alanpaulkwan** [ClickHouse/ClickHouse#44119]
I don't know if this feature exists, but here's something I find myself trying to do often and I wonder if there's a more systematic way. Given that clickhouse is going to create something to summarize an arbitrary dataset, I wonder if it can in doing so generate heuristics to optimally compress certain columns or the entire table. For example:

- Could it run uniqHLL12 on strings to suggest LowCardinality strings

- Could it calculate some stats on sorted versions of columns such that we could suggest resorting by this column would allow one to get gains from a standard RLE or even a delta / double delta type compression codec?
- Trivially, suggesting ZSTD for specific columns, or even estimating the compression / speed gains for specific columns given the column's current codec / specifics of its size and repeated values
- A column which looks like json might be better stored as an array or json type, or something along those lines
- A column whose max value is 10 million might not need UInt64, just UInt32 

I think the ideal implementation would only be to do so upon user request as doing so may be very expensive. Although I suppose there are some cheaper heuristics (hyperloglog or changing the data type) I imagine others may be costlier. In addition, Clickhouse would generate the series of table modification statements necessary for each recommendation.

**Comment by UnamedRus** [comment]
Related https://github.com/ClickHouse/ClickHouse/issues/18536

> A column whose max value is 10 million might not need UInt64, just UInt32

Object(JSON) already do that

**Comment by nickitat** [comment]
let's keep this discussion in https://github.com/ClickHouse/ClickHouse/issues/18536
