### ISSUE TITLE
session_log table as log file (with structure output support)

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#44128]
**Use case**

session_log which can't be altered in any way within clickhouse-server.
Most easiest solution, is to write it to file just like regular logs, and it would be great if it will also support structured logging.

**Describe the solution you'd like**

https://github.com/ClickHouse/ClickHouse/pull/22415
+
https://github.com/ClickHouse/ClickHouse/pull/39277
https://github.com/ClickHouse/ClickHouse/pull/40251

**Describe alternatives you've considered**

Create MV on top of session_log table, which will write to file, but it looks like more fragile solution, which can overwrite data from within ClickHouse server.

**Comment by alexey-milovidov** [comment]
@UnamedRus it's possible to simply change the engine of the session log in config.xml to `File`.

**Comment by UnamedRus** [comment]
@alexey-milovidov 

And what will happen, if this table will be deleted by malicious actor, who gained access to admin user of ClickHouse?
Whole idea of this is to have some solution, which can't be disabled/removed within ClickHouse server console.
