### ISSUE TITLE
Hints about column names can contain duplicates.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#44130]
**Describe the issue**
```
Code: 47. DB::Exception: Received from localhost:9000. DB::Exception: Missing columns: 'total_byte' while processing query: 'SELECT name, total_bytes FROM system.tables WHERE total_byte > 1000000000 ORDER BY total_bytes DESC', required columns: 'name' 'total_bytes' 'total_byte', maybe you meant: ['name','total_bytes','total_bytes']. (UNKNOWN_IDENTIFIER)
```

The name `total_bytes` is duplicated.

The message should be written in normal English, like:

`maybe you meant 'this', 'that' or 'whatever'`
instead of
`maybe you meant ['this', 'that', 'whatever']`

**Comment by jh0x** [comment]
I'm looking at this one. Do we want to retain the ordering of the hints here? For now I assume yes and am preparing a fix.

**Comment by alexey-milovidov** [comment]
Most likely, they are ordered by Levenstein distance, so we need to keep the order.
Thank you! :heart:
