### ISSUE TITLE
clickhouse-local fails to load database with dictionaries

### ISSUE THREAD

**Issue by azat** [ClickHouse/ClickHouse#44133]
CI: https://s3.amazonaws.com/clickhouse-test-reports/42635/e30d425869ae332d3b1c2ddf3f85866355d4e27c/stress_test__debug_/runlog.log

And sometimes you get the following error on CI while collecting logs with `clickhouse-local --only-system-tables`:

```
clickhouse-local: ../src/Interpreters/Context.cpp:3326: bool DB::Context::isServerCompletelyStarted() const: Assertion `getApplicationType() == ApplicationType::SERVER' failed.
```

This is because of the https://github.com/ClickHouse/ClickHouse/blob/9a48cf0da8badfc5f3da08611eb44961aa28e3f6/tests/queries/0_stateless/01129_dict_get_join_lose_constness.sql, that creates dictionary in `system` database.

**Comment by tavplubix** [comment]
Seems like `isServerCompletelyStarted` was called from here:
https://github.com/ClickHouse/ClickHouse/blob/690ec74bf235bd7c84b88acb8820f8d6efff9ec2/src/Dictionaries/getDictionaryConfigurationFromAST.cpp#L453-L459

It should not happen in CI. It may happen if you have metadata files created by old versions. I will update the assertion.

> CI: https://s3.amazonaws.com/clickhouse-test-reports/42635/e30d425869ae332d3b1c2ddf3f85866355d4e27c/stress_test__debug_/runlog.log

I don't see anything related to the assertion. It failed because of 
```
2022-10-25 06:32:00,737 All processes finished
2022-10-25 06:32:00,738 Compressing stress logs
2022-10-25 06:32:00,891 Logs compressed
2022-10-25 06:32:00,891 Will terminate gdb (if any)
Timeout exceeded while receiving data from server. Waited for 300 seconds, timeout is 300 seconds.
2022-10-25 06:39:10,529 Checking if some queries hung
Using queries from '/usr/share/clickhouse-test/queries' directory
Using clickhouse-client as client program (expecting split build)
Connecting to ClickHouse server... OK
Failed to create databases for tests: timed out

No queries hung.
No tests were run.
2022-10-25 06:39:41,547 Hung check failed with exit code 1
2022-10-25 06:39:41,547 Stress test finished
```
