### ISSUE TITLE
`clickhouse-client` - interpret Shift+Enter

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#44148]
This command should add a new line.

**Comment by cangyin** [comment]
I can do that with Alt+Enter :)

**Comment by alexey-milovidov** [comment]
Wow, it works!
But I get used to Slack and Telegram, where Shift+Enter and Ctrl+Enter are recognized (and maybe also Cmd+Enter on Mac).

**Comment by amosbird** [comment]
I picked `Alt+Enter` because it's the only available sequence for general terminals. Otherwise we need something like https://sw.kovidgoyal.net/kitty/keyboard-protocol/

**Comment by alexey-milovidov** [comment]
@amosbird Another question - can we make Alt+F4 to exit clickhouse-client?

**Comment by amosbird** [comment]
> can we make Alt+F4 to exit clickhouse-client?

`Alt+F4` is available in ANSI terminals. However, `Alt+F4` usually acts as `close window` in many desktop environments and window managers. I guess current `ctrl-c ctrl-c` is good enough.
