### ISSUE TITLE
Query with large resultset crashes

### ISSUE THREAD

**Issue by strokovnjaka** [ClickHouse/ClickHouse#44152]
I have a table with cca 4*10^10 rows. As I try to select a large chunk of it (cca a quarter, to put it to a csv file) the whole memory is consumed, the whole system jams, and after a few minutes `clickhouse-client` crashes with  

```
Exception on client:
Code: 32. DB::Exception: Attempt to read after eof: while receiving packet from localhost:9000. (ATTEMPT_TO_READ_AFTER_EOF)
```

Sometimes, this is followed by

```
Connecting to localhost:9000 as user default.
Code: 210. DB::NetException: Connection refused (localhost:9000). (NETWORK_ERROR)
```

I suspect this might be related to #43083 and #43967 

Tried versions: 
- v22.11.2.30-stable
- v22.11.1.1360-stable

To reproduce:

```
[xsd@srvr ~]$ clickhouse-client 
ClickHouse client version 22.11.2.30 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 22.11.2 revision 54460.

Warnings:
 * Linux transparent hugepages are set to "always". Check /sys/kernel/mm/transparent_hugepage/enabled

srvr :) select serialno, toUInt8(variable), time, value from measurements.dimensions where '2022-01-01 00:00:00' <= time and time < '2023-01-01 00:00:00' order by time    

SELECT
    serialno,
    toUInt8(variable),
    time,
    value
FROM measurements.dimensions
WHERE ('2022-01-01 00:00:00' <= time) AND (time < '2023-01-01 00:00:00')
ORDER BY time ASC

Query id: 1d58ead4-a53e-4106-aec2-d107ff6ea80a

↓ Progress: 2.93 billion rows, 49.67 GB (56.16 million rows/s., 952.76 MB/s.) ████████████████▊                                                    (0.0 CPU, 49.18 GB RAM) 18
Exception on client:
Code: 32. DB::Exception: Attempt to read after eof: while receiving packet from localhost:9000. (ATTEMPT_TO_READ_AFTER_EOF)

Connecting to localhost:9000 as user default.
Code: 210. DB::NetException: Connection refused (localhost:9000). (NETWORK_ERROR)
```

The db and table were created with

```
create database measurements;
create table if not exists measurements.dimensions (
    serialno UInt32,
    variable Enum8('V1' = 1, 'V2' = 2, 'V3' = 3, 'A1' = 4, 'A2' = 5, 'A3+' = 6, 'A4' = 7),
    time DateTime64,
    value Float32
) engine = MergeTree
order by (serialno, time, variable);
```

**Comment by nickitat** [comment]
Looks like exception is happening, not a crash of the process.
Pls provide us stack trace from the logs of the failed query.

**Comment by strokovnjaka** [comment]
@nickitat thanks! 

The thing is that the server gets jammed for a while (yesterday for a couple of minutes, I couldn't ssh to it).

The `clickhouse-client --stacktrace` gives

```
Code: 32. DB::Exception: Attempt to read after eof: while receiving packet from localhost:9000. (ATTEMPT_TO_READ_AFTER_EOF), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, int, bool) @ 0xda0fa9a in /usr/bin/clickhouse
1. ? @ 0x7e0b600 in /usr/bin/clickhouse
2. ? @ 0xda57bb3 in /usr/bin/clickhouse
3. DB::Connection::receivePacket() @ 0x14256662 in /usr/bin/clickhouse
4. ? @ 0x14230239 in /usr/bin/clickhouse
5. DB::ClientBase::receiveResult(std::__1::shared_ptr<DB::IAST>) @ 0x1422fdae in /usr/bin/clickhouse
6. DB::ClientBase::processOrdinaryQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::IAST>) @ 0x1422f656 in /usr/bin/clickhouse
7. DB::ClientBase::processParsedSingleQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::IAST>, std::__1::optional<bool>, bool) @ 0x1422e54f in /usr/bin/clickhouse
8. DB::ClientBase::processTextAsSingleQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) @ 0x1422dafe in /usr/bin/clickhouse   
9. DB::ClientBase::processQueryText(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) @ 0x142385da in /usr/bin/clickhouse
10. DB::ClientBase::runInteractive() @ 0x1423a353 in /usr/bin/clickhouse
11. DB::Client::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&) @ 0xdb0a1d6 in /usr/bin/clickhouse
12. Poco::Util::Application::run() @ 0x171c7542 in /usr/bin/clickhouse
13. mainEntryClickHouseClient(int, char**) @ 0xdb22dc1 in /usr/bin/clickhouse
14. main @ 0x7db00d3 in /usr/bin/clickhouse
15. __libc_start_main @ 0x3acf3 in /usr/lib64/libc-2.28.so
16. _start @ 0x7ab13ee in /usr/bin/clickhouse

Connecting to localhost:9000 as user default.
Code: 210. DB::NetException: Connection refused (localhost:9000). (NETWORK_ERROR)
```

The `/var/log/clickhouse-server/clickhouse-server.log` only reports memory usage and the final kill:

```
2022.12.13 06:16:41.191919 [ 212543 ] {84ede2c8-043e-40a6-b971-9355b616c73f} <Debug> MemoryTracker: Current memory usage (total): 42.00 GiB.
2022.12.13 06:16:41.265916 [ 212552 ] {84ede2c8-043e-40a6-b971-9355b616c73f} <Debug> MemoryTracker: Current memory usage (for query): 38.00 GiB.
2022.12.13 06:16:41.626217 [ 212546 ] {84ede2c8-043e-40a6-b971-9355b616c73f} <Debug> MemoryTracker: Current memory usage (total): 43.00 GiB.
2022.12.13 06:16:41.697007 [ 212552 ] {84ede2c8-043e-40a6-b971-9355b616c73f} <Debug> MemoryTracker: Current memory usage (for query): 39.00 GiB.
2022.12.13 06:16:42.001649 [ 212415 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 43.89 GiB, peak 43.89 GiB, free memory in arenas 61.92 MiB, will set to 44.08 GiB (RSS), difference: 189.34 MiB
2022.12.13 06:16:42.001691 [ 212415 ] {} <Debug> MemoryTracker: Current memory usage (total): 44.08 GiB.
2022.12.13 06:16:42.145336 [ 212543 ] {84ede2c8-043e-40a6-b971-9355b616c73f} <Debug> MemoryTracker: Current memory usage (for query): 40.00 GiB.
2022.12.13 06:16:45.127987 [ 212216 ] {} <Fatal> Application: Child process was terminated by signal 9 (KILL). If it is not done by 'forcestop' command or manually, the possible cause is OOM Killer (see 'dmesg' and look at the '/var/log/kern.log' for the details).
```

**Comment by nickitat** [comment]
> @nickitat thanks!
> 
> The thing is that the server gets jammed for a while (yesterday for a couple of minutes, I couldn't ssh to it).
> 
> The `clickhouse-client --stacktrace` gives
> 
> ```
> Code: 32. DB::Exception: Attempt to read after eof: while receiving packet from localhost:9000. (ATTEMPT_TO_READ_AFTER_EOF), Stack trace (when copying this message, always include the lines below):
> 
> 0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, int, bool) @ 0xda0fa9a in /usr/bin/clickhouse
> 1. ? @ 0x7e0b600 in /usr/bin/clickhouse
> 2. ? @ 0xda57bb3 in /usr/bin/clickhouse
> 3. DB::Connection::receivePacket() @ 0x14256662 in /usr/bin/clickhouse
> 4. ? @ 0x14230239 in /usr/bin/clickhouse
> 5. DB::ClientBase::receiveResult(std::__1::shared_ptr<DB::IAST>) @ 0x1422fdae in /usr/bin/clickhouse
> 6. DB::ClientBase::processOrdinaryQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::IAST>) @ 0x1422f656 in /usr/bin/clickhouse
> 7. DB::ClientBase::processParsedSingleQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::IAST>, std::__1::optional<bool>, bool) @ 0x1422e54f in /usr/bin/clickhouse
> 8. DB::ClientBase::processTextAsSingleQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) @ 0x1422dafe in /usr/bin/clickhouse   
> 9. DB::ClientBase::processQueryText(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) @ 0x142385da in /usr/bin/clickhouse
> 10. DB::ClientBase::runInteractive() @ 0x1423a353 in /usr/bin/clickhouse
> 11. DB::Client::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&) @ 0xdb0a1d6 in /usr/bin/clickhouse
> 12. Poco::Util::Application::run() @ 0x171c7542 in /usr/bin/clickhouse
> 13. mainEntryClickHouseClient(int, char**) @ 0xdb22dc1 in /usr/bin/clickhouse
> 14. main @ 0x7db00d3 in /usr/bin/clickhouse
> 15. __libc_start_main @ 0x3acf3 in /usr/lib64/libc-2.28.so
> 16. _start @ 0x7ab13ee in /usr/bin/clickhouse
> 
> Connecting to localhost:9000 as user default.
> Code: 210. DB::NetException: Connection refused (localhost:9000). (NETWORK_ERROR)
> ```
> 
> The `/var/log/clickhouse-server/clickhouse-server.log` only reports memory usage and the final kill:
> 
> ```
> 2022.12.13 06:16:41.191919 [ 212543 ] {84ede2c8-043e-40a6-b971-9355b616c73f} <Debug> MemoryTracker: Current memory usage (total): 42.00 GiB.
> 2022.12.13 06:16:41.265916 [ 212552 ] {84ede2c8-043e-40a6-b971-9355b616c73f} <Debug> MemoryTracker: Current memory usage (for query): 38.00 GiB.
> 2022.12.13 06:16:41.626217 [ 212546 ] {84ede2c8-043e-40a6-b971-9355b616c73f} <Debug> MemoryTracker: Current memory usage (total): 43.00 GiB.
> 2022.12.13 06:16:41.697007 [ 212552 ] {84ede2c8-043e-40a6-b971-9355b616c73f} <Debug> MemoryTracker: Current memory usage (for query): 39.00 GiB.
> 2022.12.13 06:16:42.001649 [ 212415 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 43.89 GiB, peak 43.89 GiB, free memory in arenas 61.92 MiB, will set to 44.08 GiB (RSS), difference: 189.34 MiB
> 2022.12.13 06:16:42.001691 [ 212415 ] {} <Debug> MemoryTracker: Current memory usage (total): 44.08 GiB.
> 2022.12.13 06:16:42.145336 [ 212543 ] {84ede2c8-043e-40a6-b971-9355b616c73f} <Debug> MemoryTracker: Current memory usage (for query): 40.00 GiB.
> 2022.12.13 06:16:45.127987 [ 212216 ] {} <Fatal> Application: Child process was terminated by signal 9 (KILL). If it is not done by 'forcestop' command or manually, the possible cause is OOM Killer (see 'dmesg' and look at the '/var/log/kern.log' for the details).
> ```

you should be able to find stack trace in logs by query_id

**Comment by strokovnjaka** [comment]
@nickitat which logs?
There are no stacktraces  in `/var/log/clickhouse-server/clickhouse-server.log`: only 'Current memory...' is reported when everyhing is ok, then only `<Fatal> Application: Child process was terminated/...`,

**Comment by alexey-milovidov** [comment]
> Application: Child process was terminated by signal 9 (KILL). If it is not done by 'forcestop' command or manually, the possible cause is OOM Killer (see 'dmesg' and look at the '/var/log/kern.log' for the details).

This explains the case.

See https://clickhouse.com/docs/en/sql-reference/statements/select/order-by/#implementation-details
