### ISSUE TITLE
 DB::Exception: Unknown compression method: 4: while reading column Status 

### ISSUE THREAD

**Issue by ashokkoti** [ClickHouse/ClickHouse#4415]
(you don't have to strictly follow this form)

**Describe the bug**

Below error while reading from one table (engine-log) .One week before ,there was no issue .
DB::Exception: Unknown compression method: 4: while reading column Status
![image](https://user-images.githubusercontent.com/33107730/52885857-30502880-3138-11e9-8294-548e3ca637ea.png)

**How to reproduce**

* Which ClickHouse server version to use
version 18.16.1

* Which interface to use, if matters
 clickhouse-client
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
CREATE TABLE stageaudit.caudit
(
    node_host String,
    ms_time UInt16,
    Client_ip String,
    User String,
    Status String,
    Operation String,
    `@timestamp` UInt64,
    d Date MATERIALIZED toDate(round(`@timestamp` / 1000)),
    dt DateTime MATERIALIZED toDateTime(round(`@timestamp` / 1000))
)
ENGINE = Log;

* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/yandex/ClickHouse/blob/master/dbms/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result
select Status,d,count(1)  from  stageaudit.caudit  where  d='2019-01-14' group by Status,d;
**Expected behavior**
Error while selecting on materialized column "d" 
 select Operation,d,count(1)  from  stageaudit.caudit  where  d='2019-01-14' group by Operation,d;

SELECT
    Operation,
    d,
    count(1)
FROM stageaudit.caudit
WHERE d = '2019-01-14'
GROUP BY
    Operation,
    d

┌─Operation────────────────────────────────┬──────────d─┬─count(1)─┐
│ UPDATE                                   │ 2019-01-14 │    34687 │
│ INSERT                                   │ 2019-01-14 │    34716 │
│ SELECT                                   │ 2019-01-14 │    34713 │
│ INSERT                                   │ 2019-01-14 │    34713 │
│ SELECT                                   │ 2019-01-14 │    34718 │
└──────────────────────────────────────────┴────────────┴──────────┘

5 rows in set. Elapsed: 1.369 sec. Processed 3.28 million rows, 126.48 MB (2.39 million rows/s., 92.38 MB/s.)

select Status,d,count(1)  from  stageaudit.caudit  where  d='2019-01-14' group by Status,d;

SELECT
    Status,
    d,
    count(1)
FROM stageaudit.caudit
WHERE d = '2019-01-14'
GROUP BY
    Status,
    d

↘ Progress: 2.75 million rows, 49.55 MB (2.60 million rows/s., 46.72 MB/s.) Received exception from server (version 18.16.1):
Code: 89. DB::Exception: Received from xxxxxxx:9000. DB::Exception: Unknown compression method: 4: while reading column Status at /var/lib/clickhouse/data/stageaudit/caudit.

0 rows in set. Elapsed: 1.160 sec. Processed 2.75 million rows, 49.55 MB (2.37 million rows/s., 42.71 MB/s.)
**Error message and/or stacktrace**
2019.02.15 15:29:33.409564 [ 21 ] {22431e72-a8fa-4b1c-95f2-4f355efb777d} <Error> executeQuery: Code: 89, e.displayText() = DB::Exception: Unknown compression method: 4: while reading column Status at /var/lib/clickhouse/data/stageaudit/caudit, e.what() = DB::Exception (from ) (in query: select Status,d,count(1)  from  stageaudit.caudit  where  d='2019-01-14' group by Status,d), Stack trace:

0. clickhouse-server(StackTrace::StackTrace()+0x16) [0x5e3f7e6]
1. clickhouse-server(DB::Exception::Exception(std::string const&, int)+0x1f) [0x2bce50f]
2. clickhouse-server(DB::CompressedReadBufferBase::readCompressedData(unsigned long&, unsigned long&)+0xfa6) [0x5e54ce6]
3. clickhouse-server(DB::CompressedReadBuffer::nextImpl()+0x26) [0x5e53536]
4. clickhouse-server() [0x4d2256d]
5. clickhouse-server(DB::DataTypeString::deserializeBinaryBulk(DB::IColumn&, DB::ReadBuffer&, unsigned long, double) const+0x167) [0x4d25c57]
6. clickhouse-server(DB::LogBlockInputStream::readData(std::string const&, DB::IDataType const&, DB::IColumn&, unsigned long)+0x1f6) [0x5396506]
7. clickhouse-server(DB::LogBlockInputStream::readImpl()+0x1e5) [0x539b385]
8. clickhouse-server(DB::IProfilingBlockInputStream::read()+0x21f) [0x4c80fbf]
9. clickhouse-server(DB::FilterBlockInputStream::readImpl()+0xa3) [0x51efb43]
10. clickhouse-server(DB::IProfilingBlockInputStream::read()+0x21f) [0x4c80fbf]
11. clickhouse-server(DB::ExpressionBlockInputStream::readImpl()+0x1b) [0x51eec5b]
12. clickhouse-server(DB::IProfilingBlockInputStream::read()+0x21f) [0x4c80fbf]
13. clickhouse-server(DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>::thread(std::shared_ptr<DB::ThreadGroupStatus>, unsigned long)+0x286) [0x5228c86]
14. clickhouse-server(std::thread::_State_impl<std::thread::_Invoker<std::tuple<DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>::process()::{lambda()#1}> > >::_M_run()+0x40) [0x52294d0]
15. clickhouse-server() [0x6a7fa8f]
16. /lib64/libpthread.so.0(+0x7dd5) [0x7fbf0a317dd5]
17. /lib64/libc.so.6(clone+0x6d) [0x7fbf09b36ead]

![image](https://user-images.githubusercontent.com/33107730/52885492-0d714480-3137-11e9-9313-399dea08293a.png)

**Additional context**

**Comment by alexey-milovidov** [comment]
The data in table with `Log` engine gets corrupted.
Note that `Log` table engine does not maintain data consistency. This situation is normal and documented:
https://clickhouse.tech/docs/en/engines/table-engines/log-family/

You should use full-featured table engines like ReplicatedMergeTree or MergeTree.
