### ISSUE TITLE
fix flaky test test_attach_detach_partition

### ISSUE THREAD

**Issue by CheSema** [ClickHouse/ClickHouse#44154]
test_merge_tree_hdfs/test.py::test_attach_detach_partition
Actually test needs to be adjusted. There is wrong way how to wait part deletion.

_Originally posted by @CheSema in https://github.com/ClickHouse/ClickHouse/issues/43760#issuecomment-1346272811_

**Comment by CheSema** [comment]
As an example of flaky result.
https://s3.amazonaws.com/clickhouse-test-reports/43760/a32a7ebb666715c12941a06738077c38db73f680/integration_tests__release__[3/4].html

**Comment by tavplubix** [comment]
It's still flaky
https://play.clickhouse.com/play?user=play#c2VsZWN0IAp0b1N0YXJ0T2ZEYXkoY2hlY2tfc3RhcnRfdGltZSkgYXMgZCwKY291bnQoKSwgIGdyb3VwVW5pcUFycmF5KHB1bGxfcmVxdWVzdF9udW1iZXIpLCAgYW55KHJlcG9ydF91cmwpCmZyb20gY2hlY2tzIHdoZXJlICcyMDIyLTA2LTAxJyA8PSBjaGVja19zdGFydF90aW1lIGFuZCB0ZXN0X25hbWUgbGlrZSAnJXRlc3RfbWVyZ2VfdHJlZV9oZGZzJScgYW5kIHRlc3Rfc3RhdHVzIGluICgnRkFJTCcsICdGTEFLWScpIGdyb3VwIGJ5IGQgb3JkZXIgYnkgZCBkZXNj

**Comment by alexey-milovidov** [comment]
@CheSema I have fixed it.
