### ISSUE TITLE
[RFC] Add ability to configure minimal part age for TTL MOVE

### ISSUE THREAD

**Issue by azat** [ClickHouse/ClickHouse#44187]
### Description

Usually TTL MOVE is used with S3 disk, and in case someone will insert data with expired TTL those parts will be merged/moved to the S3 on INSERT.

Yes, there is `perform_ttl_move_on_insert=false` (#15000), but it will not help a lot, because it only moves the problem to background, so with `perform_ttl_move_on_insert=false` just after INSERT merge/move will write it to S3.

### Ad hoc solutions:

- stop merges/moves:

  ```sql
  SYSTEM STOP MERGES table;
  SYSTEM STOP MOVES table;
  ```

- change ttl to include some new column that will take into account this new time

### `move_ttl_min_age`

An idea is to implement some new setting for `MergeTree`, i.e. `move_ttl_min_age`, that will **not** move parts that are younger then this age.

But some care should be taken because it is not enough to avoid MOVE for such parts but also:

- some parts can be merged and written directly to S3
  for this case the maximal `modification_time` of all parts can be used to compare with `move_ttl_min_age`.

- parts can be fetched from other replicas
  for this case znode `mtime` from replica can be used to compare with `move_ttl_min_age`.

So the question is, are there any interest in this setting, or it looks very ad-hoc and does not worth it?

### Refs:

- #10128

**Comment by UnamedRus** [comment]
I think, we need to have better control/explanation on how TTL moves/move_factor moves happens.

Because current behavior is counter intuitive for users

https://kb.altinity.com/altinity-kb-queries-and-syntax/ttl/modify-ttl/#modify-ttl-move

**Comment by azat** [comment]
@UnamedRus yeah there are lots of other issues with TTL, though it is related to some changes in TTL usually.
But this one is a different thing, and for a careful reader of the documentation ("source code") it is obvious why it works this way.

Thanks for the link, this looks to me like a `BUGS` section in the `man` pages, definitely worth to submit this changes to the official documentation, at least, from my point of view.

**Comment by den-crane** [comment]
May be minimum part size? Like a part cannot be moved by the TTL if the size of the part is less than 50GB ?

**Comment by den-crane** [comment]
> > May be minimum part size? Like a part cannot be moved by the TTL if the size of the part is less than 50GB ?
> 
> By using part size you cannot guarantee that TTL will be executed eventually.

that's true. I mention it because from my perspective `modification_time` is more confusing.
