### ISSUE TITLE
Min aggregating function compatibility

### ISSUE THREAD

**Issue by antip00** [ClickHouse/ClickHouse#44186]
Regarding https://github.com/ClickHouse/ClickHouse/pull/43038/

I create a table on the non-affected version, insert data into it, change the version to the affected version, insert one more time, change the version to the fixed version, and check output. Output should be the same if we do the same without changing versions.

Version 22.8.5.29:

`CREATE TABLE table (number Int32, s AggregateFunction(min, String)) Engine=MergeTree() ORDER BY number`
`INSERT INTO table SELECT number, minState(char(number)) AS s FROM numbers(1000) GROUP BY number`

`CREATE TABLE table_2 (number Int32, s AggregateFunction(min, String)) Engine=MergeTree() ORDER BY number`
`INSERT INTO table_2 SELECT number, minState(char(number)) AS s FROM numbers(1000) GROUP BY number`
`INSERT INTO table_2 SELECT number, minState(char(number)) AS s FROM numbers(1000) GROUP BY number`

`SELECT minMerge(s) FROM table_2` returns `\0`

changing version on 22.8.6.71:

`INSERT INTO table SELECT number, minState(char(number)) AS s FROM numbers(1000) GROUP BY number`
`SELECT minMerge(s) FROM table` #to force merge 

changing version on 22.8.10.7:

`SELECT minMerge(s) FROM table` returns empty string instead of `\0`

**Comment by vzakaznikov** [comment]
@Algunenano, can you take a look?

**Comment by tavplubix** [comment]
@vzakaznikov, can you read the changelog entry in https://github.com/ClickHouse/ClickHouse/pull/43038?

**Comment by tavplubix** [comment]
This is how it works. If a string that ends with '\0' was written by a "broken" version then trailing '\0' will be trimmed.

**Comment by vzakaznikov** [comment]
Ok, thanks. @antip00, please review the changelog and close this issue.
