### ISSUE TITLE
What's the principle of multi-volumes in ClickHouse

### ISSUE THREAD

**Issue by ggchangan** [ClickHouse/ClickHouse#44181]
1. How ClickHouse decide which is the oldest part in hot/cold case? 
2. How ClickHouse move these parts in mlti-volumes?
3. I read one article and get ClickHouse move parts based on part size because big parts are older parts https://altinity.com/blog/2019/11/29/amplifying-clickhouse-capacity-with-multi-volume-storage-part-2
However we store 4 month data and partition these data by (day, process_batch_id), and each process_batch_id are merged before attach to table, so these parts are similar size, How ClickHouse decide which parts to move in this case?
4. Does ClickHouse compare parts in the same table or parts in different tables? It's important, because different tables have different part size.

**Comment by DerekChia** [comment]
ClickHouse will check for `move_factor` and if the amount of available space gets lower than this ratio, the parts are sorted by size from largest to smallest, and the parts with total size meeting the `move_factor` condition will be moved to the next volume. So here, the largest-sized parts get moved to the next volume. 

Another setting is `max_data_part_size_bytes` where if the size of a merged part is estimated to be bigger than the value defined, the part will be written to the next volume. New parts tend to be smaller and older parts tend to be larger in size as the background merges smaller parts into larger parts. 

In your case, and going by my explanation above, `move_factor` should kick in once your current volume's available space goes lower than the `move_factor` ratio. When you say `each process_batch_id are merged before attach to table` does it mean that each partition only has one part? If not, ClickHouse will still attempt to merge these parts within the partition until a single part reaches `max_bytes_to_merge_at_max_space_in_pool` (defaults to 150 GB). 

ClickHouse monitors parts that are stored in the volume. So if your tables are stored in the same volume (e.g. hot), then the parts will be monitored and moved to the next volume (e.g. colder) when the conditions above are met.
