### ISSUE TITLE
Http/RowBinary inserts fails after upgrade 22.2.2.1 to 22.11.2.30

### ISSUE THREAD

**Issue by ermadan** [ClickHouse/ClickHouse#44198]
I'm using com.clickhouse:clickhouse-http-client:0.3.2-patch11, after upgrade of server part of RawBinary inserts (half of them) fails with the following error: 

`2022.12.13 16:13:00.728999 [ 648246 ] {8a503b6e-2602-44c1-8304-91d4c3993112} <Error> executeQuery: Code: 33. DB::Exception: Cannot read all data. Bytes read: 64. Bytes expected: 78.: (at row 1)
: While executing BinaryRowInputFormat. (CANNOT_READ_ALL_DATA) (version 22.11.2.30 (official build)) (from [::ffff:10.19.254.225]:62351) (in query: INSERT INTO default.service_library(account_id, checksum, cluster
_agent_id, entity_guid, language, name, real_agent_id, critical, critical_cnt, high, high_cnt, medium, medium_cnt, low, low_cnt) FORMAT RowBinary ), Stack trace (when copying this message, always include the lines
 below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, int, bool) @ 0xda0fa9a in /usr/bin/clickhouse
1. ? @ 0xda6acca in /usr/bin/clickhouse
2. DB::SerializationString::deserializeBinary(DB::IColumn&, DB::ReadBuffer&) const @ 0x1276b019 in /usr/bin/clickhouse
3. DB::BinaryFormatReader::readField(DB::IColumn&, std::__1::shared_ptr<DB::IDataType const> const&, std::__1::shared_ptr<DB::ISerialization const> const&, bool, std::__1::basic_string<char, std::__1::char_traits<
char>, std::__1::allocator<char>> const&) @ 0x14430611 in /usr/bin/clickhouse
4. DB::RowInputFormatWithNamesAndTypes::readRow(std::__1::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn>>>&, DB::RowReadExtension&) @ 0x14432b98 i
n /usr/bin/clickhouse
5. DB::IRowInputFormat::generate() @ 0x144246b2 in /usr/bin/clickhouse
6. DB::ISource::tryGenerate() @ 0x143b2c95 in /usr/bin/clickhouse
7. DB::ISource::work() @ 0x143b2826 in /usr/bin/clickhouse
8. DB::ExecutionThreadContext::executeTask() @ 0x143cde06 in /usr/bin/clickhouse
9. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x143c28bc in /usr/bin/clickhouse
10. DB::PipelineExecutor::executeImpl(unsigned long) @ 0x143c12f9 in /usr/bin/clickhouse
11. DB::PipelineExecutor::execute(unsigned long) @ 0x143c10fd in /usr/bin/clickhouse
12. DB::CompletedPipelineExecutor::execute() @ 0x143bfb1d in /usr/bin/clickhouse
13. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::__1::shared_ptr<DB::Context>, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&
, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<ch
ar, std::__1::char_traits<char>, std::__1::allocator<char>> const&)>, std::__1::optional<DB::FormatSettings> const&) @ 0x136ec989 in /usr/bin/clickhouse
14. DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::__1::optional<DB::CurrentThread::QueryScope>&) @ 0x14304336 in /usr/bin/clickhouse
15. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x1430846e in /usr/bin/clickhouse
16. DB::HTTPServerConnection::run() @ 0x143843f4 in /usr/bin/clickhouse
17. Poco::Net::TCPServerConnection::start() @ 0x171b0e14 in /usr/bin/clickhouse
18. Poco::Net::TCPServerDispatcher::run() @ 0x171b27bb in /usr/bin/clickhouse
19. Poco::PooledThread::run() @ 0x173415c7 in /usr/bin/clickhouse
20. Poco::ThreadImpl::runnableEntry(void*) @ 0x1733effd in /usr/bin/clickhouse
21. ? @ 0x7f4f20b7a609 in ?
22. __clone @ 0x7f4f20a9f163 in ?
`
`CREATE TABLE default.service_library (
account_id Int32,
checksum String,
cluster_agent_id Int32,
entity_guid String,
language String,
name String,
real_agent_id Int32,
version String,
critical Array(String),
high Array(String),
medium Array(String),
low Array(String),
critical_cnt Int8,
high_cnt Int8,
medium_cnt Int8,
low_cnt Int8,
created_at DateTime DEFAULT now()
)
ENGINE = ReplacingMergeTree(created_at)
ORDER BY (account_id, entity_guid, name, version, cluster_agent_id, real_agent_id )
`
Regular inserts over Http still work without issues, configuration is the default.

**Comment by ermadan** [comment]
Java code i use:
`            val request = client.connect(dataSource)
                    .write()
                    .table("default.service_library(account_id, checksum, cluster_agent_id, entity_guid, language, name, " +
                            "real_agent_id, critical, critical_cnt, high, high_cnt, medium, medium_cnt, low, low_cnt)")
                    .format(ClickHouseFormat.RowBinary)
                    .set("send_progress_in_http_headers", 1)
            val config = request.getConfig()
            stream = ClickHouseDataStreamFactory.getInstance()
                    .createPipedOutputStream(100 * 1024 * 1024, 100, 30000, null)
            future = request.data(stream!!.getInputStream()).execute()
           ---------------------------- 
                write(accountId.toInt())
                write(checksum)
                write(clusterAgentId.toInt())
                write(entityGuid)
                write(language)
                write(lib)
                write(realAgentId.toInt())
                listOf(RiskSeverity.CRITICAL, RiskSeverity.HIGH, RiskSeverity.MEDIUM, RiskSeverity.LOW).forEach { severity ->
                    val vulns = cve?.filter { it.criticality == severity }?.map { it.cveId }?.distinct()?: listOf()
                    writeArray(vulns)
                    writeInt8(vulns.size)
                }
            ---------------------
            stream?.close()
            future?.get()?.use { response ->
                val summary = response.summary
                val rows: Long = summary.getWrittenRows()
                LOG.info("sent $rows")
            }
             ----------------------------
    private fun writeInt8(int: Int) {
        BinaryStreamUtils.writeInt8(stream, int)
    }

    private fun write(obj: Any?) {
        if (obj == null) {
            BinaryStreamUtils.writeNull(stream)
        } else {
            when (obj) {
                is String -> BinaryStreamUtils.writeString(stream, obj.toByteArray())
                is Int -> BinaryStreamUtils.writeInt32(stream, obj)
                is Long -> BinaryStreamUtils.writeInt64(stream, obj)
                is LocalDate -> BinaryStreamUtils.writeDate(stream, obj)
                else -> throw java.lang.IllegalArgumentException("Wrong type $obj")
            }
        }
    }

    private fun writeArray(array: List<String>) {
        stream?.writeVarInt(array.size)
        array.forEach { v ->
            BinaryStreamUtils.writeString(stream, v.toByteArray())
        }
    }

`

**Comment by den-crane** [comment]
probably duplicate of https://github.com/ClickHouse/ClickHouse/issues/44167

**Comment by ermadan** [comment]
The issue was related to inserting a null into a non-null column. Not related to the version upgrade, sorry for the confusion
