### ISSUE TITLE
Add DELETE BACKUP command for managing backups

### ISSUE THREAD

**Issue by e-mars** [ClickHouse/ClickHouse#44199]
**Use case**
When using the `BACKUP` commands users need to be able to script removal of older backups.

**Describe the solution you'd like**

Add command `DELETE BACKUP FROM Disk(...) | S3(...)`

**Describe alternatives you've considered**

Delete files on disk or S3 manually using external catalog of backups.

see: https://github.com/ClickHouse/ClickHouse/issues/43225

**Comment by alexey-milovidov** [comment]
As an end user, I'd better see backups as something cast in stone...

Nevertheless, the possibility to manage backups in SQL will be useful.

**Comment by Slach** [comment]
@alexey-milovidov 
> As an end user, I'd better see backups as something cast in stone...

But what about backup retention policy? When I need manage complex backup deletion policy?
For example every sunday create weekly backup and other days daily backup and keep last 4 weekly backup and last 3 daily backup?
