### ISSUE TITLE
Add `BFloat16` data type

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#44206]
**Use case**

Machine learning datasets, for example, #44134

**Describe the solution you'd like**

Use the compiler-provided data type or write a trivial wrapper.
Ideally, implement the specializations for L* distances and norms.

**Describe alternatives you've considered**

The alternative is described in #44134

**Additional context**

Updating LLVM and Clang to 16 is good for this task.
https://www.phoronix.com/news/GCC-LLVM-bf16-BFloat16-Type

**Comment by lingtaolf** [comment]
May I have a try ?

**Comment by alexey-milovidov** [comment]
@lingtaolf, please do.
