### ISSUE TITLE
How to convert from base64 to bitmap in query statements

### ISSUE THREAD

**Issue by zwq199400** [ClickHouse/ClickHouse#44210]
CREATE TABLE tt1
(
    `id` String,
    `bitmap` AggregateFunction(groupBitmap, UInt32) MATERIALIZED base64Decode(bitmap_str),
    `bitmap_str` String
)
ENGINE = AggregatingMergeTree
PARTITION BY id
ORDER BY id
SETTINGS index_granularity = 8192;

Automatic conversion in create table statement, how to implement it in query statement?

**Comment by save-my-heart** [comment]
```sql
select cast(base64Decode(bitmap_str) as AggregateFunction(groupBitmap, UInt32)) from tt1
```
