### ISSUE TITLE
AggregatingMergeTree and Live View performance on system with 0.5M inserts per second hosted on EC2 m6i.xlarge (4cpu/15G

### ISSUE THREAD

**Issue by ermadan** [ClickHouse/ClickHouse#44245]
Hi, I have a system that inserts 0.5M rows per second on m6i.xlarge EC2 instance (8B rows total). It uses 15% of CPU for inserts, but when i add either AggregatingMergeTree or live view with watch CPU consumption hits 100%. Is that high level of utilization expected and i need significantly more powerful instance or i'm doing something wrong?
DDLs:
```
CREATE TABLE default.service_library (
account_id Int32,
checksum String,
cluster_agent_id Int32,
entity_guid String,
language String,
name String,
real_agent_id Int32,
version String,
critical Array(String),
high Array(String),
medium Array(String),
low Array(String),
critical_cnt Int8,
high_cnt Int8,
medium_cnt Int8,
low_cnt Int8,
created_at DateTime DEFAULT now()
)
ENGINE = ReplacingMergeTree(created_at)
ORDER BY (account_id, entity_guid, name, version, cluster_agent_id, real_agent_id )
```

```
CREATE MATERIALIZED VIEW entity_service_library
ENGINE = AggregatingMergeTree() ORDER BY (account_id, entity_guid, name, version, cluster_agent_id, real_agent_id)
AS SELECT
    account_id, checksum, entity_guid, language, name, version,
    cluster_agent_id, real_agent_id,
    argMaxState(critical, created_at) as critical,
    argMaxState(high, created_at) as high,
    argMaxState(medium, created_at) as medium,
    argMaxState(low, created_at) as low,
    argMaxState(critical_cnt, created_at) as critical_cnt,
    argMaxState(high_cnt, created_at) as high_cnt,
    argMaxState(medium_cnt, created_at) as medium_cnt,
    argMaxState(low_cnt, created_at) as low_cnt,
    maxState(created_at) AS max_created_at
FROM service_library 
GROUP BY account_id, entity_guid, checksum, language, name, version, cluster_agent_id, real_agent_id
```

`CREATE LIVE VIEW lv AS select entity_guid , length(groupUniqArray(critical)), groupUniqArray(critical) from default.service_library sl group by entity_guid having length(groupUniqArray(critical)) > 1
`

**Comment by nickitat** [comment]
by 100% you mean 1 core utilised or 4 cores?

**Comment by ermadan** [comment]
100% of 4 cores, being precise it fluctuates between 95% and 100%

**Comment by UnamedRus** [comment]
Why you don't use ReplacingMergeTree instead of AggregatingMergeTree? (It will be much simpler/cheaper for execute and store)

You also can disable `optimize_on_insert` session setting.

Or if you will switch to `ReplacingMergeTree`, you can just remove all calculation from MV and rely on optimize during part write.

**Comment by UnamedRus** [comment]
>  ReplacingMergeTree provides eventual deduplication 

It's exactly the same like AggregatingMergeTree works, it also eventual.
You just need to use FINAL in your queries 

https://kb.altinity.com/altinity-kb-queries-and-syntax/altinity-kb-final-clause-speed/

**Comment by ermadan** [comment]
my measurements show that using **final** instead of `(row_number() over (partition by account_id, name, version, cluster_agent_id, real_agent_id order by created_at desc))` is significantly slower (6 times)

**Comment by nickitat** [comment]
what CH version do you use?

**Comment by ermadan** [comment]
tested on 22.11.2.30 and 22.2.2.1

**Comment by ermadan** [comment]
Guys, can you probably say what the expected performance of **aggregating view** and **live view + watch** is - how many inserts can process 4 cores instance - 1K/sec, 10K/sec, 100K/sec and how does it scale?

**Comment by alexey-milovidov** [comment]
A higher CPU usage after AggregatingMergeTree is expected.

PS. Live views are not recommended (they are experimental and unsupported).
