### ISSUE TITLE
Empty source for external dictionaries

### ISSUE THREAD

**Issue by mayamika** [ClickHouse/ClickHouse#44240]
**Feature**

Allow creating empty dictionaries with DDL queries.

**Use case**

This feature will allow building queries and views referencing empty dictionary with `dictGet` or 'as a table', 
even if dictionary does not exist yet.

Maybe, empty dictionaries does not make sense in 'clickhouse as a part of internal infrastructure', this will 
feature may be useful in cases when clickhouse is used as a database for small application that configures
clickhouse automatically, and some dictionaries may be optional or provided by application  user.

**Describe the solution you'd like**

Provide mock source `SOURCE(EMPTY())` for dictionaries, such that every `dictGet` call will return `null_value`.

**Describe alternatives you've considered**

Make source section optional for dictionaries.

**Comment by alexey-milovidov** [comment]
Nice.

There is another use-case - if there is a cluster with a dedicated empty gateway server for accepting distributed queries, this server still needs dictionaries to be configured - for query analysis.

As we have the `Null` table engine, the dictionary source can also be named Null, if possible.
