### ISSUE TITLE
format_custom_row_after_delimiter not work when using CustomSeparatedWithNames format to import csv file via http

### ISSUE THREAD

**Issue by cy2008** [ClickHouse/ClickHouse#44247]
version: 22.8.10.29

DDL:
CREATE TABLE IF NOT EXISTS `network_health_diagnosis`
(
    `id`                     UInt64 COMMENT '主键',
    `resource_pool`          String NOT NULL COMMENT '资源池',
    `device_type`            String NOT NULL COMMENT '设备类型',
    `group_type`             String NOT NULL COMMENT '设备组',
    `analysis_time`          String NOT NULL COMMENT '诊断时间',
    `mgmt_ip`                String NOT NULL COMMENT '设备IP',
    `result_info`            String NOT NULL COMMENT '设备存在的亚健康状态',
    `task_name`              String COMMENT '任务名',
    `cmd`                    String COMMENT '采集命令',
    `multi_check_conditions` String COMMENT '判断条件',
    `multi_check_value`      String COMMENT '校验值',
    `cmd_result`             String COMMENT '阈值',
    `score`                  String COMMENT '分数',
    `number`                 Int32 COMMENT '当前健康状态下，异常信息的数量',
    `partition_field`        Int32 NOT NULL COMMENT '用于数据分区'
) ENGINE = MergeTree
      primary key (`device_type`, `resource_pool`, `analysis_time`, `mgmt_ip`);

csv file created by mysql dump with options --fields-terminated-by='φ' and --lines-terminated-by='π':
[network_health_diagnosis-n.txt](https://github.com/ClickHouse/ClickHouse/files/10232986/network_health_diagnosis-n.txt)

http query:

POST /?query=insert into network_health_diagnosis (id, resource_pool, device_type, group_type, analysis_time, mgmt_ip, result_info, task_name, cmd, multi_check_conditions, multi_check_value, cmd_result, score, number, partition_field) SETTINGS format_custom_escaping_rule = 'CSV', format_custom_field_delimiter = 'φ', format_custom_row_after_delimiter = 'π', input_format_with_names_use_header = 0 FORMAT CustomSeparatedWithNames HTTP/1.1
Host: 100.76.2.12:8123
Content-Type: text/plain
Content-Length: 22

"<file contents here>"

then got error response as follows:

Code: 27. DB::ParsingException: Cannot parse input: expected 'φ' before: '\n  LocalBasicExceptions:36229927\n  LocalFPTunExceptions:32267080\n2 seconds\n  LocalBasicExceptions:36229930\n  LocalFPTunExceptions:32267083φ100φ135φ22120319π': 
Row 42:
Column 0,   name: id,                     type: UInt64, parsed text: "789839346"
Column 1,   name: resource_pool,          type: String, parsed text: "BJJD"
Column 2,   name: device_type,            type: String, parsed text: "avrs"
Column 3,   name: group_type,             type: String, parsed text: "avrs_group"
Column 4,   name: analysis_time,          type: String, parsed text: "20221203_1900"
Column 5,   name: mgmt_ip,                type: String, parsed text: "10.184.162.183"
Column 6,   name: result_info,            type: String, parsed text: "严重亚健康"
Column 7,   name: task_name,              type: String, parsed text: "AVRS-CONNETING连接监控"
Column 8,   name: cmd,                    type: String, parsed text: "cat /tmp/SDN_Monitor/conntrack_result.txt | awk <SINGLE QUOTE>NR==3{print $3}<SINGLE QUOTE>"
Column 9,   name: multi_check_conditions, type: String, parsed text: ">="
Column 10,  name: multi_check_value,      type: String, parsed text: "20000、18000、15000、12000、0"
Column 11,  name: cmd_result,             type: String, parsed text: "0"
Column 12,  name: score,                  type: String, parsed text: "100"
Column 13,  name: number,                 type: Int32,  parsed text: "135"
Column 14,  name: partition_field,        type: Int32,  parsed text: "22120319"

Row 43:
Column 0,   name: id,                     type: UInt64, parsed text: "789839347"
Column 1,   name: resource_pool,          type: String, parsed text: "BJJD"
Column 2,   name: device_type,            type: String, parsed text: "avrs"
Column 3,   name: group_type,             type: String, parsed text: "avrs_group"
Column 4,   name: analysis_time,          type: String, parsed text: "20221203_1900"
Column 5,   name: mgmt_ip,                type: String, parsed text: "10.184.162.183"
Column 6,   name: result_info,            type: String, parsed text: "严重亚健康"
Column 7,   name: task_name,              type: String, parsed text: "AVRS-DPVI的Excetions的数值变化情况"
Column 8,   name: cmd,                    type: String, parsed text: "for i in {1..2};do echo <DOUBLE QUOTE><DOUBLE QUOTE>$i seconds<DOUBLE QUOTE><DOUBLE QUOTE>; sudo fp-cli stats | grep Local | grep Exceptions; sleep 1; done"
Column 9,   name: multi_check_conditions, type: String, parsed text: "-"
Column 10,  name: multi_check_value,      type: String, parsed text: "Failed"
Column 11,  name: cmd_result,             type: String, parsed text: "1 seconds"
ERROR: There is no delimiter between fields: expected "φ", got "<LINE FEED>  LocalBasi"

: While executing CustomSeparatedRowInputFormat: (at row 43)
. (CANNOT_PARSE_INPUT_ASSERTION_FAILED) (version 22.8.10.29 (official build))

**Comment by tavplubix** [comment]
Please check https://github.com/ClickHouse/ClickHouse/issues/42352 and https://github.com/ClickHouse/ClickHouse/issues/39620
