### ISSUE TITLE
How to improve the speed and performance of ReplacingMergeTree

### ISSUE THREAD

**Issue by cmdares** [ClickHouse/ClickHouse#4424]
Current application scenarios: 
Data table 1 billion, two minute to do etl, incremental data about 100,000, after ETL insertion, data can not be immediately merge, then need to execute the command optimize table final, after the execution of the logic is ok, there is no duplication, but because of the larger cardinal, optimize time is longer. Is there a way to do this faster? the table is support to biz real-time query and no duplicate data can occur in the application query.

or support : feature like postgresql   ref:https://github.com/yandex/ClickHouse/issues/3312
insert into tbl   
  select id,c1,c2,c3 from temp_etl_tbl 
  on conflict(id) 
  do update   
  set   
  c1=excluded.c1,
  c2=excluded.c2,
  c3=excluded.c3;  

or support:update select  ref:https://github.com/yandex/ClickHouse/issues/4092

thank!

**Comment by alexey-milovidov** [comment]
The only way is to avoid doing `OPTIMIZE`.
You can perform `SELECT ... FROM table FINAL`
or do aggregation with argMax: `SELECT k, argMax(column1, version), ... FROM table`.
