### ISSUE TITLE
ClickHouse to understand Hive partitioning (`/name=value/` in path) in S3 table function (and similar)

### ISSUE THREAD

**Issue by danthegoodman1** [ClickHouse/ClickHouse#44246]
**Use case**

The ability to inherit partitioning from S3 files, for example in parquet format

**Describe the solution you'd like**

Being able to specify a setting (and potentially the pattern of the file paths, not sure the implementation detail) to enable Hive partitioning such that queries filtering on these columns could greatly reduce the number of files that need to be listed from S3.

**Describe alternatives you've considered**

DuckDB has this natively, but lacks much of the functionality of clickhouse. You can also brute force it with the example as shown below by what seems to be listing all files.

**Additional context**

Here is a comparison between similar behavior in clickhouse and duckdb. As duckdb understands where the file name parts are, it is far faster in view creation and in query performance, where with clickhouse this is just extracted from the file name and thus we need to list all files:

Verison: `22.11.2.30`

```bash
clickhouse-local -q "
CREATE VIEW test AS
  SELECT *
    , CAST(extract(_path, 'type=(\w+)\/') as String) as type
    , extract(_path, 'year=(\w+)\/') as year
    , extract(_path, 'quarter=(\w+)\/') as quarter
  FROM (
    SELECT *, _file, _path FROM s3('https://s3.us-west-2.amazonaws.com/ookla-open-data/parquet/performance/type=*/year=*/quarter=*/*.parquet',
    'Parquet')
  )
;

SELECT _path, type, year FROM test WHERE type = 'fixed' AND year = '2019' AND quarter = '1' LIMIT 5;
"
```

Running these individually takes `2.128 sec.` and `4.561 sec.` respectively. 4-core github codespace in the US EAST region.

With DuckDB (`v0.6.1`), similar behavior shows `~900ms` for view creation, and `1.7s` for query (same env as above):

```python
import duckdb
from time import time

con = duckdb.connect(database=':memory:')

con.execute('install httpfs')
con.execute('load httpfs')
con.execute('install parquet')
con.execute('load parquet')
print('done loading')

s = time()
con.execute('''
CREATE VIEW test AS
  SELECT *, type, year, quarter, filename FROM read_parquet('s3://ookla-open-data/parquet/performance/type=*/year=*/quarter=*/*.parquet', HIVE_PARTITIONING = 1, filename=true)
''')
e = time()
print(con.fetchall(), 'in', (e-s)*1000, 'ms')

s = time()
con.execute('''
select filename from test where type = 'fixed' and year = '2022' and quarter = '1' LIMIT 5
''')
e = time()
print(con.fetchall(), 'in', (e-s)*1000, 'ms')
```

output:
```
done loading
[] in 878.9570331573486 ms
[('s3://ookla-open-data/parquet/performance/type=fixed/year=2022/quarter=1/2022-01-01_performance_fixed_tiles.parquet',), ('s3://ookla-open-data/parquet/performance/type=fixed/year=2022/quarter=1/2022-01-01_performance_fixed_tiles.parquet',), ('s3://ookla-open-data/parquet/performance/type=fixed/year=2022/quarter=1/2022-01-01_performance_fixed_tiles.parquet',), ('s3://ookla-open-data/parquet/performance/type=fixed/year=2022/quarter=1/2022-01-01_performance_fixed_tiles.parquet',), ('s3://ookla-open-data/parquet/performance/type=fixed/year=2022/quarter=1/2022-01-01_performance_fixed_tiles.parquet',)] in 1715.8644199371338 ms
```

Not sure why the view creation is so different in timing between duckdb and clickhouse as well.

**Comment by danthegoodman1** [comment]
cc @alexey-milovidov this is what I was referring to during the meeting webinar we just had, I misspoke on the call

**Comment by danthegoodman1** [comment]
* it doesn't know where the files are in s3 so it has to list them all before it can filter them down

is what I had meant to say

**Comment by danthegoodman1** [comment]
Note: it still seems like duckdb lists all files rather than understanding their location(s) in the glob pattern, however I believe that it has other optimizations, especially for parquet files, that result in the lower latencies

**Comment by danthegoodman1** [comment]
Another thought: I believe the key to performance here will be to inform CH of the pattern of the file paths specifically so it can greatly reduce the S3 ListObjects surface.

**Comment by CurtizJ** [comment]
But files (partition) pruning already exists for `S3` tables. It was impletemented in #37356. Probably the issue that condition is not pushed down to the `view`.

**Comment by danthegoodman1** [comment]
That could explain it, but does The view actually list the files? It’s not at query time where it does that?

**Comment by danthegoodman1** [comment]
Both view creation and parsing the parquet files through the query take notably longer than expected in my testing

**Comment by xiedeyantu** [comment]
> Maybe #44429 can help this issue.

**Comment by xiedeyantu** [comment]
> But files (partition) pruning already exists for `S3` tables. It was impletemented in #37356. Probably the issue is that condition is not pushed down to the `VIEW`.

Maybe https://github.com/ClickHouse/ClickHouse/pull/44429 can help this issue.

**Comment by danthegoodman1** [comment]
url table engine would be great too

**Comment by danthegoodman1** [comment]
> But files (partition) pruning already exists for `S3` tables. It was impletemented in #37356. Probably the issue is that condition is not pushed down to the `VIEW`.

I found that when making a view that has partitions defined based on these virtual columns it will actually spend time listing the files first rather than waiting until query time to list files.

**Comment by danthegoodman1** [comment]
DuckDB recently added optimizations to the file pruning from the list as well: https://github.com/duckdb/duckdb/pull/8428

**Comment by danthegoodman1** [comment]
Any progress on this? This is something that keep me using duckdb for S3 parquet since it's just easier to use.

**Comment by tbragin** [comment]
cc @melvynator @alesapin

**Comment by danthegoodman1** [comment]
Some more insight I posted in slack, also posting here for context:

I think this is one of those really high ROI QoL features that would especially benefit things like chdb. DuckDB is gaining a lot of ground because of how easy they are making analytics, and it's features like these that are deceptively important to people, especially new to columnar SQL.

For example, it often doesn't matter how rich the rest of the CH SQL flavor is if it takes me say 15 extra lines and a subquery to write regex virtual columns extracted from EACH S3 file pattern. That's the kind of work that's really important for the DB to do.

Many features or functions that DuckDB SQL might lack that CH may have I can actually just do within code downstream from the query with relative ease. While that might be a bit slower, it's often orders of magnitude faster than reading the extra S3 files, and more importantly **less error prone than SQL acrobatics like parsing hive partitioning with regex that isn't type-checked**.

**Comment by alexey-milovidov** [comment]
@yariks5s 

Implementation proposal:

For file-like table engines, look at the list of paths to read. Whenever a path contains a subdirectory in the form of `/key=value/`, let the user query virtual column `_key` of type `LowCardinality(String)`, similarly to `_path`. If the column `_key` already exists in the table, prepend another underscore to the name, until there is no ambiguity.

At this moment, we will implement it only for SELECT. Inserts with Hive partitioning are out of scope.

Variations:

1. Maybe limit detected columns to those who are valid identifiers, so `key=value` will match, but `1#h^=wtf` won't. 
2. Maybe start with `key` names instead of `_key`. @danthegoodman1, how it is done in DuckDB?
3. Maybe allow any virtual column names and resolve them dynamically, so we don't have to analyze all the paths in advance?
4. But if we have the list of paths in advance, we can use schema inference to detect types better. It looks like a complication, let's not do it for now.

**Comment by alexey-milovidov** [comment]
> HIVE_PARTITIONING = 1

We can do better, there will be no need for this screaming "HIVE_PARTITIONING" parameter.

**Comment by danthegoodman1** [comment]
@alexey-milovidov https://duckdb.org/docs/data/partitioning/hive_partitioning.html

They analyze the hive partitions dynamically

**Comment by loicalleyne** [comment]
Would this also cover the S3Queue Engine? 
I have a use case where logs are dropped in S3 with the following partitioning:

`s3://{bucket}/{log type}/year={YYYY}/month={MM}/day={DD}/hour={HH}/{filename}.parquet`

The bucket has a life-cycle policy that moves objects to Glacier after 14 days. The most relevant logs are in the recent past, in the last 7 days or less; hourly volume is ~20GB/hour and I only want to ingest the most recent data to avoid massive amounts of reads. 

ie. 
```
CREATE MATERIALIZED VIEW entity_consumer TO entity_table 
AS 
SELECT * FROM s3_queue_engine_entity 
WHERE year = toYear(timestamp_sum(12, hour, now())) 
AND month = toMonth(timestamp_sum(12, hour, now())) 
AND day = toDay(timestamp_sum(12, hour, now())) 
AND hour >= toHour(timestamp_sum(12, hour, now()))
```
I'm hoping that the solution being proposed of hive partitioning predicate push down will also apply to S3Queue Engine tables.

**Comment by danthegoodman1** [comment]
@alexey-milovidov is there a PR for this that we can look at?

**Comment by danthegoodman1** [comment]
https://github.com/ClickHouse/ClickHouse/pull/68963 maybe?

**Comment by danthegoodman1** [comment]
https://clickhouse.com/docs/en/operations/settings/settings#use_hive_partitioning

**Comment by danthegoodman1** [comment]
the tests aren't even clear, but this is probably the most clear one (ignoring the fact it's called array, you can see it matches on the file example with `array=[1,2,3]` in the path):
```
https://github.com/ClickHouse/ClickHouse/pull/68963/files#diff-f212376cff497333f600666aebd3db769b57e1df085a7d4ef24ecc3c943d1701R52-R54
```

**Comment by yariks5s** [comment]
The PR where hive partitioning was implemented is https://github.com/ClickHouse/ClickHouse/pull/65997. You sent the PR that improves the hive partitioning performance.

**Comment by danthegoodman1** [comment]
Thank you!!! Really love this feature.

Is it pushed down into views?

**Comment by yariks5s** [comment]
I believe it can be used everywhere with file(), url(), s3(), azureBlobStorage() and HDFS() functions.
