### ISSUE TITLE
 Code: 159. DB::Exception: Timeout exceeded: elapsed 5.060592159 seconds, maximum: 3. (TIMEOUT_EXCEEDED) (version 22.10.2.11 (official build))

### ISSUE THREAD

**Issue by justiceyuy** [ClickHouse/ClickHouse#44257]
Hello, I use a JAVA program to connect to clickhouse through JDBC, and an error will be reported after more than three seconds Code: 159. DB::Exception: Timeout exceeded: elapsed 5.060592159 seconds, maximum: 3. (TIMEOUT_EXCEEDED) (version 22.10.2.11 (official build))，But I don't have this problem through third-party connection tools(Such as IntelliJ IDEA)，i changed max_execution_time
![image](https://user-images.githubusercontent.com/48314460/207808109-f887c55c-ca8e-4489-beae-13e42a0e7e69.png)
Did not solve this problem, added to the JDBC connection URL socket_timeout also not Do you have any good suggestions?

**Comment by save-my-heart** [comment]
You should check your JDBC url first, is there a parameter `max_execution_time`?
If there is not, you can get some information from table `system.query_log`, field `Settings`, to find the value of key `max_execution_time`.

**Comment by justiceyuy** [comment]
> 您应该先检查您的 JDBC url，是否有参数`max_execution_time`？ 如果没有，可以从表`system.query_log`、字段中获取一些信息`Settings`，找到key的值`max_execution_time`。

![image](https://user-images.githubusercontent.com/48314460/207818960-e6c9f385-a1a6-49c1-a40c-aca711023dce.png)
Thanks for your suggestion, I tried it and it still doesn't work 
![image](https://user-images.githubusercontent.com/48314460/207819086-3b6510f4-b5b0-4215-b024-2a0815d4dfb7.png)

**Comment by DerekChia** [comment]
What version of JDBC driver are you using? In v0.3.2-patch9 and patch10, there are fixes rolled out for timeout errors

[[8eb0fa7](https://github.com/ClickHouse/clickhouse-jdbc/commit/8eb0fa7687ddce8b20d73af12810414c7159c3c0)]: Fix write timeout error (Zhichun Wu) https://github.com/ClickHouse/clickhouse-jdbc/pull/925
[[fb126fc](https://github.com/ClickHouse/clickhouse-jdbc/commit/fb126fcd619dc1010f2fdaba6d0787904eb6d749)]: Fix timeout issues (Zhichun Wu) https://github.com/ClickHouse/clickhouse-jdbc/pull/943
