### ISSUE TITLE
integration ML-algorithm lib like madlib

### ISSUE THREAD

**Issue by cmdares** [ClickHouse/ClickHouse#4425]
clickhouse+?algorithm lib? = postgresql/Greenplum+madlib
madlib ref https://github.com/apache/madlib
IF "CATBOOST"? 
how about the feature vs madlib?
when will the available version be released?

**Comment by alexey-milovidov** [comment]
A team of students attempted to integrate Apache MADLib, but they have faced multiple difficulties.
It's appeared that MADLib is too tightly integrated with Postgres, it contains many assumptions that make integration to other DBMS difficult if possible at all.
