### ISSUE TITLE
Support unioning files/tables by column name

### ISSUE THREAD

**Issue by danthegoodman1** [ClickHouse/ClickHouse#44267]
**Use case**

The ability to perform queries like `SELECT count(b) FROM file('*.parquet', 'Parquet', 'a Nullable(Int64), b Nullable(String)') WHERE b is not null` with mismatched columns, and have the resulting read fill `NULL` where columns don't exist in given rows. For example if file `a.parquet` has columns `a`, but `b.parquet` has columns `a, b`.

This is highly useful when you have an evolving schema for CSV, Parquet, etc. files.

This could be useful for other kinds of tables, but is most useful when you have a glob pattern of a file, s3, etc. table function that has varying columns per file.

**Describe the solution you'd like**

A query setting like `union_by_name=1` that would fill the missing column values in results with `NULL`, thus turning the resulting columns `Nullable`, and otherwise preventing the `Code: 7. DB::Exception: Columns is empty: While executing ParquetBlockInputFormat: While executing File. (INCORRECT_NUMBER_OF_COLUMNS)` error.

**Describe alternatives you've considered**

Nothing works if you are matching glob patterns.

**Comment by Avogar** [comment]
It will work if `input_format_parquet_allow_missing_columns=1`:
```
$ clickhouse-local -q "select 42 as a format Parquet" > data1.parquet
$ clickhouse-local -q "select 42 as a, 42 as b format Parquet" > data2.parquet
$ clickhouse-local -q "SELECT count(b) FROM file('data*.parquet', 'Parquet', 'a Nullable(Int64), b Nullable(String)') WHERE b is not null settings input_format_parquet_allow_missing_columns=1"
1
```

**Comment by danthegoodman1** [comment]
@Avogar what version? I get this error:

```
root@sec-clickhouse:~# clickhouse-local -q "select 42 as a format Parquet" > data1.parquet
root@sec-clickhouse:~# clickhouse-local -q "select 42 as a, 42 as b format Parquet" > data2.parquet
root@sec-clickhouse:~# clickhouse-local -q "SELECT count(b) FROM file('data*.parquet', 'Parquet', 'a Nullable(Int64), b Nullable(String)') WHERE b is not null settings input_format_parquet_allow_missing_columns=1"
Code: 7. DB::Exception: Columns is empty: While executing ParquetBlockInputFormat: While executing File. (INCORRECT_NUMBER_OF_COLUMNS)
root@sec-clickhouse:~# clickhouse-local --version
ClickHouse local version 22.8.4.7 (official build).
root@sec-clickhouse:~#
```

**Comment by danthegoodman1** [comment]
NVM seems I am using a version older than the commit that added it, fresh install shows it working:
```

No VM guests are running outdated hypervisor (qemu) binaries on this host.
root@ubuntu-s-8vcpu-16gb-nyc3-01:~# clickhouse-local -q "select 42 as a format Parquet" > data1.parquet
root@ubuntu-s-8vcpu-16gb-nyc3-01:~# clickhouse-local -q "select 42 as a, 42 as b format Parquet" > data2.parquet
root@ubuntu-s-8vcpu-16gb-nyc3-01:~# clickhouse-local -q "SELECT count(b) FROM file('data*.parquet', 'Parquet', 'a Nullable(Int64), b Nullable(String)') WHERE b is not null settings input_format_parquet_allow_missing_columns=1"
1
root@ubuntu-s-8vcpu-16gb-nyc3-01:~# clickhouse-local --version
ClickHouse local version 23.3.1.2823 (official build).
```
