### ISSUE TITLE
My clickhouse's zookeeper wait time is incrising rapidly

### ISSUE THREAD

**Issue by sdarshil** [ClickHouse/ClickHouse#44263]
I am getting into some kind of  issue as further described , 
My current zookeeper wait time is 7-9 seconds on and average 

How much zookeeper wait time is best ?

I am using grafana to monitor my zookeeper !

<img width="1643" alt="image" src="https://user-images.githubusercontent.com/31997374/207840210-0f965102-f106-4363-92fb-86515623d2f0.png">

I am using clickhouse with 22.11.2 version with single shard and single replica with altinity k8s operator and with single node of zookeeper

i have arround 700-750 replicated merge tree tables 
Zookeeper have 4 Gb ram with best available disk of azure

How to get root cause for this ?

**Comment by tavplubix** [comment]
> i have arround 700-750 replicated merge tree tables

See `merge_selecting_sleep_ms`, `cleanup_delay_period` and other merge tree settings that control frequency of background operation in ReplicatedMergeTree tables. Tuning these settings will help.

**Comment by den-crane** [comment]
What is `zookeeper wait time` ? I guess you calculate some sum of wait events and probably it's incorrect.

**Comment by sdarshil** [comment]
<img width="1726" alt="image" src="https://user-images.githubusercontent.com/31997374/207950679-f6f047ae-fc2d-4fd0-b799-bf2abbe7ef97.png">

i am using this query to define my zookeeper wait time and to be exact this sql query :

<img width="1253" alt="image" src="https://user-images.githubusercontent.com/31997374/207950805-21127562-bdcd-4278-b575-e9b5187c51b7.png">

**Comment by sdarshil** [comment]
> > i have arround 700-750 replicated merge tree tables
> 
> See `merge_selecting_sleep_ms`, `cleanup_delay_period` and other merge tree settings that control frequency of background operation in ReplicatedMergeTree tables. Tuning these settings will help.


I am using the default values , can you suggest some values here ?

**Comment by den-crane** [comment]
But this is MICROseconds not seconds. You need to divide it by 1000.

**Comment by sdarshil** [comment]
Actually , the Y is set for Microseconds only but the value is high so grafana converted microseconds to seconds if you can check in this snapshot :

<img width="1716" alt="image" src="https://user-images.githubusercontent.com/31997374/208225773-0fc32cae-8b93-4f1e-8a9c-2534b1e9cd03.png">

**Comment by sdarshil** [comment]
@tavplubix as per your mentioned thread i still have to downgrade version or is it fixed in 22.11 too? 
I removed znodes manually but wait time is still that only

**Comment by tavplubix** [comment]
@sdarshil, probably you have a different issue. I mentioned that thread only because you originally posted the comment there.

**Comment by sdarshil** [comment]
> @sdarshil, probably you have a different issue. I mentioned that thread only because you originally posted the comment there.

Yeah maybe , but i am not getting whats the issue there as resources are give properly and i am new in clickhouse database , how can i find root cause of this ?
@den-crane can you help here , sorry to ask

**Comment by den-crane** [comment]
@sdarshil please share the output

```
SELECT
    toStartOfHour(event_time) AS t,
    round(avg(ProfileEvent_ZooKeeperWaitMicroseconds)) AS avg,
    max(ProfileEvent_ZooKeeperWaitMicroseconds) AS max,
    round(median(ProfileEvent_ZooKeeperWaitMicroseconds)) AS median
FROM system.metric_log
WHERE event_date >= today()
GROUP BY t
ORDER BY t ASC
```

**Comment by sdarshil** [comment]
<img width="1717" alt="image" src="https://user-images.githubusercontent.com/31997374/208597291-5df2864b-9e19-46bf-9cb0-783397becea4.png">


output of clickhouse-client :
<img width="916" alt="image" src="https://user-images.githubusercontent.com/31997374/208597667-fabe2da6-c4e3-4e88-bb39-e61481e86960.png">


@den-crane

**Comment by filimonov** [comment]
Zookeeper is an async protocol. 

ClickHouse can send a lot of concurrent requests to zookeeper from different threads, and when zookeeper finally answers them all the threads get responses and stop timers. 

```
0:01 thread1 start request 
0:02 thread2 start request 
0:03 thread3 start request 

0:05 thread1 + thread2 + thread3 get responses, thread1 wait time was 4 sec,  thread2 - 3sec, thread3 -2  sec. ZooKeeperWait  will be increased by 4+3+2=9 sec
```

Check outstanding_requets on zookeeper side + delays there. 

> i have arround 700-750 replicated merge tree tables

Clickhouse is designed for BIG data, when even a single table can have terabytes / petabytes. Are you sure you have 750 of terabyte-size tables? :) See also https://kb.altinity.com/altinity-kb-schema-design/how-much-is-too-much/#number-of-tables-system-wide-across-all-databases

**Comment by sdarshil** [comment]
@filimonov 

i checked it and the outstanding requests are 0

```

# HELP outstanding_changes_removed outstanding_changes_removed
# TYPE outstanding_changes_removed counter
outstanding_changes_removed 1111138.0
# HELP outstanding_tls_handshake outstanding_tls_handshake
# TYPE outstanding_tls_handshake gauge
outstanding_tls_handshake 0.0
# HELP outstanding_changes_queued outstanding_changes_queued
# TYPE outstanding_changes_queued counter
outstanding_changes_queued 1111138.0
# HELP outstanding_requests outstanding_requests
# TYPE outstanding_requests gauge
outstanding_requests 0.0
```

while the last 5 min snaspshot of ZK_WAITTIME :
<img width="1718" alt="image" src="https://user-images.githubusercontent.com/31997374/208856062-91e8b523-6a39-46a2-b533-2d1e47d9d028.png">

**Comment by aol-59** [comment]
we used clickhouse keeper and after upgrading clickhouse we faced the same issue.
try to upgrade clickhouse keeper it may fix it.
