### ISSUE TITLE
ext4 vs xfs?

### ISSUE THREAD

**Issue by AnthonyWC** [ClickHouse/ClickHouse#44294]
Hi folks, just wondering if anyone has experience with running clickhouse on ext4 vs xfs?  And if there is any benchmark of ext4 vs xfs for clickhouse data volume?  Specifically with high IOPS (>10k) SSD EBS on AWS

Currently there isn't really any details in doc: https://clickhouse.com/docs/en/operations/tips/#file-system
https://kb.altinity.com/altinity-kb-setup-and-maintenance/filesystems/ mentions some users experienced performance issues but 1st linked issue is 5 years old.

e.g. While this isn't for clickhouse, this old benchmark suggested for high IOPS xfs would performance much better  https://scalegrid.io/blog/xfs-vs-ext4-comparing-mongodb-performance-on-aws-ec2/

**Comment by den-crane** [comment]
We have experience that XFS performs worse than Ext4 with heavy loaded HDD.

>https://scalegrid.io/blog/xfs-vs-ext4-comparing-mongodb-performance-on-aws-ec2/

The Clickhouse disk loading patter is very different from MongoDB. Mongo uses a lot of small I/O operations, Clickhouse uses infrequent large I/O operations.

**Comment by alexey-milovidov** [comment]
If you are already using XFS, don't worry, and continue using it.
While XFS can behave slightly worse than ext4 in rare cases, there is no reason to change it.
ClickHouse works well with almost every filesystem.
