### ISSUE TITLE
clickhouse-keeper doesn't contain systemd service file

### ISSUE THREAD

**Issue by Felixoid** [ClickHouse/ClickHouse#44293]
It's very unfortunate, we need to add it

**Comment by UnamedRus** [comment]
https://kb.altinity.com/altinity-kb-setup-and-maintenance/altinity-kb-zookeeper/clickhouse-keeper-service/#systemd-service

Kudos to @den-crane

**Comment by Felixoid** [comment]
The source for [systemd-service](https://kb.altinity.com/altinity-kb-setup-and-maintenance/altinity-kb-zookeeper/clickhouse-keeper-service/#systemd-service) is `clickhouse-server.service`. So I reused the original source, but still, very appreciated!
