### ISSUE TITLE
why system.tables can't show TinyLog table engine rows and size

### ISSUE THREAD

**Issue by xzy256** [ClickHouse/ClickHouse#44302]
create tinylog engine table:
```
create tbale tinylogtest (`a` uint16, `b` String) ENGINE=TinyLog
```
After inserting into some data into it, query `system.tables`, the `total_rows` and `total_bytes` is NULL

WHY?

**Comment by alexey-milovidov** [comment]
`TinyLog` tables are simple. They have no metadata allowing them to know the number of rows.
To obtain the number of rows, the data has to be read, and we don't do this for `system.tables`.

The number of bytes can be obtained easily, but we also don't do it for simplicity.

**Comment by xzy256** [comment]
except `TinyLog` engine, what others engine are same, no metedata ?
