### ISSUE TITLE
Subquery in window view, column not found error in _temporary_and_external_tables.

### ISSUE THREAD

**Issue by parthipan28** [ClickHouse/ClickHouse#44304]
Creating window view with subquery. while inserting row in source table getting error as 'DB::Exception: Column xx not found in table _temporary_and_external_tables.<query_id>

Steps to reproduce the error:
create table test.just_in_data(sno UInt32, quantity UInt32, timestamp DateTime)
ENGINE = MergeTree()
order by sno

create table test.summary(sno UInt32, counter UInt32)
ENGINE = AggregatingMergeTree()
ORDER BY sno
SETTINGS index_granularity = 512, merge_max_block_size = 512

CREATE WINDOW VIEW IF NOT EXISTS test.wv_interlude TO test.summary
AS
select sno, groupArray(ss) FROM (SELECT
    sno,
    sum(quantity) as ss
FROM test.just_in_data
GROUP BY sno,tumble(timestamp, toIntervalSecond('20')) AS w_id) GROUP BY sno

INSERT INTO test.just_in_data VALUES(112,1,toDateTime(now())) 
Received exception from server (version 22.7.1):
Code: 10. DB::Exception: Received from localhost:9000. DB::Exception: Column `ss` not found in table _temporary_and_external_tables.`_tmp_b123fc30-0ff2-4a0e-8635-252a8f0c0ec7` (b123fc30-0ff2-4a0e-8635-252a8f0c0ec7): while pushing to view test.wv_interlude (27a3234b-9eba-4361-b173-7be1084c1718). (NOT_FOUND_COLUMN_IN_BLOCK)

Tested with latest version too 22.12.1 and 22.7.1.

**Comment by pluiest** [comment]
same problem for me

**Comment by Algunenano** [comment]
No repro (missing table definitions) and using an experimental feature. Let's close
