### ISSUE TITLE
When set <mysql_port>3358</mysql_port>,  The error log as follows.

### ISSUE THREAD

**Issue by Sallery-X** [ClickHouse/ClickHouse#44305]
version:22.3LTS

2022.12.01 07:57:32.660436 [ 11131 ] {} <Error> MySQLHandler: Connection reset by peer
2022.12.01 07:57:33.831551 [ 11131 ] {} <Error> MySQLHandler: DB::Exception: Cannot read all data. Bytes read: 0. Bytes expected: 3
2022.12.01 07:57:37.662780 [ 11131 ] {} <Error> MySQLHandler: DB::Exception: Cannot read all data. Bytes read: 0. Bytes expected: 3
2022.12.01 07:57:38.836428 [ 11131 ] {} <Error> MySQLHandler: DB::Exception: Cannot read all data. Bytes read: 0. Bytes expected: 3

**Comment by alexey-milovidov** [comment]
The log message is correct. It indicates that someone has connected to port 3358, sent no data, and closed the connection.
