### ISSUE TITLE
CREATE TABLE url_engine_table (word String, value UInt64) ENGINE=URL('http://127.0.0.1:12345/', CSV);

### ISSUE THREAD

**Issue by cathhuo** [ClickHouse/ClickHouse#44303]
I create a table:
CREATE TABLE url_engine_table (word String, value UInt64) ENGINE=URL('http://127.0.0.1:12345/', CSV);

when I qurery:
SELECT *
FROM url_engine_table

Query id: e6716947-2c3b-4d3b-a7f5-05ed96526377

0 rows in set. Elapsed: 0.023 sec.

Received exception from server (version 21.11.11):
Code: 1000. DB::Exception: Received from localhost:9000. DB::Exception: Connection refused. (POCO_EXCEPTION)

but my python server work well!!!!! why????? 

why?????

**Comment by kssenii** [comment]
the only strange think that I can notice is that you have 'http://127.0.0.1:12345/' but as I remember it should be 'http://127.0.0.1:12345/table_data'

**Comment by kssenii** [comment]
so "connection refused" should mean you server does not actually accept the connection, the issue is not related to clickhouse
