### ISSUE TITLE
Primary key is unused in SELECT if it's `someHash(foo)` and WHERE has `foo = {bar}`

### ISSUE THREAD

**Issue by Twixes** [ClickHouse/ClickHouse#44316]
**Describe the situation**

We have a UUID column on an `events` table which we use for sampling AND often use it for filtering: `person_id`. Because sampling keys must be unsigned ints and for some reason UUID is not backed by an unsigned 128-bit int but by a string, we have to transform the `person_id` column to an unsigned int.

We do this by hashing `person_id` with `cityHash64`, but there is one problem: `person_id` is no longer used by ClickHouse for filtering SELECTs at all – as opposed to plain `person_id`. We only get the benefits of sorting back when ALWAYS explicitly filtering like so: `cityHash64(person_id) = cityHash64({some_target_id})`, but it's cumbersome to always do this.

**How to reproduce**

Tested this on 22.3 and 22.8, works the same.

Table:

```SQL
CREATE TABLE events
(
    uuid UUID,
    person_id UUID,
    event String,
    timestamp DateTime64(6, 'UTC'),
    team_id Int64
)
ENGINE = MergeTree()
PARTITION BY toYYYYMM(timestamp)
ORDER BY (team_id, toDate(timestamp), event, cityHash64(person_id), cityHash64(uuid))
SAMPLE BY cityHash64(person_id)
```

Query:

```SQL
SELECT  uuid, timestamp
FROM events e
WHERE team_id = 2
     AND toDateTime(timestamp, 'UTC') >= toDateTime('2022-01-01 00:00:00', 'UTC')
     AND toDateTime(timestamp, 'UTC') < toDateTime('2023-01-01 00:00:00', 'UTC')
     AND event = '$pageview'
     AND person_id = '017adbc0-98b5-0000-3f74-619a368fe65d'
```

Running the above with `EXPLAIN indexes=1` reveals that only the `team_id, event` part of the primary key is used (+ `timestamp` because partition, as far as I understand), when `cityHash64(person_id)` could safely be used too to great effect.

**Expected performance**

Ideally if the primary key contains `someHash(person_id)`, a condition such as `person_id = {some_target_id}` would automatically be converted by ClickHouse to `someHash(person_id) = someHash({some_target_id}) AND person_id = {some_target_id}`.
This way we'd get all the benefits of the primary key (condition before AND), and then relatively cheaply filter out any unlikely collisions to ensure data integrity (condition after AND).
> Second condition may not be "relatively cheap" if the first condition didn't filter out much data, so there's some nuance to this.

**Additional context**

https://github.com/PostHog/posthog/issues/12909#issuecomment-1354811131

**Comment by UnamedRus** [comment]
Duplicate https://github.com/ClickHouse/ClickHouse/issues/10685

**Comment by Twixes** [comment]
Oh cool, I really looked everywhere if such an issue existed, but I was focused on the `ORDER BY`/sorting key aspect and that one doesn't mention it explicitly. I suppose this is a more concrete instance.

**Comment by den-crane** [comment]
closed as duplicate

**Comment by UnamedRus** [comment]
BTW, index hint could work a bit better.

```
indexHint(someHash(person_id) = someHash({some_target_id})) AND person_id = {some_target_id}
```
