### ISSUE TITLE
Allow `toUInt128()` for UUIDs

### ISSUE THREAD

**Issue by Twixes** [ClickHouse/ClickHouse#44317]
**Use case**

UUID being easily castable to an unsigned integer would be immensely useful for sampling keys.
A UUID is just a string of 128 bits, but unfortunately in ClickHouse there isn't a good way of converting one to a `UInt128`. `SELECT toUInt128(generateUUIDv4())` fails with "Conversion between numeric types and UUID is not supported."

**Describe the solution you'd like**

Make `toUInt128()` work with UUIDs. Examples:
- `SELECT toUInt128(toUUID('00000000-00000000-00000000-00000000'))` should return `0`
- `SELECT toUInt128(toUUID('f82aef31-279e-431f-8b00-2899ad387aea'))` should return `329871470813054077831677335124932328170`

**Describe alternatives you've considered**

Currently using `cityHash64()` instead of `toUInt128()`, but that's much less intuitive and contributes to #44316 being a pain.

**Comment by den-crane** [comment]
```sql
SELECT reinterpret(toUUID('f82aef31-279e-431f-8b00-2899ad387aea'), 'UInt128')

┌─reinterpret(toUUID('f82aef31-279e-431f-8b00-2899ad387aea'), 'UInt128')─┐
│                                184763514886005504091012298813990650655 │
└────────────────────────────────────────────────────────────────────────┘
```

>Currently using cityHash64() instead of toUInt128(), 
>but that's much less intuitive and contributes to https://github.com/ClickHouse/ClickHouse/issues/44316 being a pain.

It won't help you. Sampling is not supported by Int128 and I guess it has no sense from performance (sampling) perspective.

**Comment by Twixes** [comment]
Oh, that's interesting, I wonder why is not supported @den-crane? While surely performance for 128-bit values is worse than for 64-bit ones, they're still much more feasible than variable length, right? And hashing necessarily causes information to be lost, which is not ideal.

**Comment by UnamedRus** [comment]
There is another "problem" with how UUID works:

Order of values/internal storage implementation is a bit counterintuitive. 
https://michcioperz.com/post/clickhouse-uuid-ordering/

> has no sense from performance (sampling) perspective.

I don't think it should be that bad, it's basically 2 conditions which should be able to use PRIMARY KEY index.

**Comment by den-crane** [comment]
A hash function is mandatory for UUID, BTW. 
UUIDs don't occupy all range of Int.

**Comment by alexey-milovidov** [comment]
I agree with all the previous points.
It could be better to support reinterpretAsUInt128.
