### ISSUE TITLE
Allow PUT instead of POST for url() writes

### ISSUE THREAD

**Issue by rhuddleston** [ClickHouse/ClickHouse#44326]
We have a use case where we want clickhouse to do PUT requests to Azure or AWS pre-signed URL's but these only work via PUT. Clickhouse by default generates a POST request which will not work in this case. We verified we could get it to work though if we send the request through an nginx proxy and change it from a POST to a PUT.

> A clear and concise description of what is the intended usage scenario is.

An optional parameter to the url() function to create a PUT request

> A clear and concise description of what you want to happen.

We sent it through an nginx proxy to try to work around the issue

> A clear and concise description of any alternative solutions or features you've considered.

s3() function is an alternative for AWS but there is no alternative for azure

> Add any other context or screenshots about the feature request here.

STR:

- https://docs.aws.amazon.com/AmazonS3/latest/userguide/PresignedUrlUploadObject.html download python example
- add `'ContentType': 'text/csv; charset=UTF-8; header=absent'` to the line in the above script: `s3_client, client_action, {'Bucket': args.bucket, 'Key': args.key, 'ContentType': 'text/csv; charset=UTF-8; header=absent'}, 1000)` this is needed as the request headers have to match exactly otherwise it rejects it
- python3 presigned.py <bucket-name> test-put put # generates a presigned URL
- INSERT INTO FUNCTION url('https://<bucket-name>.s3.amazonaws.com/test-put?...', 'CSV') SELECT * FROM generateRandom('uuid UUID, context Text, dt Datetime') LIMIT 100; # throws an error about signature not matching as it's a POST request not a PUT
- change `bucket-name>.s3.amazonaws.com` to local nginx proxy that changes POST to a PUT, now everything works

**Comment by kssenii** [comment]
It is already possible for url engine if you use named collections feature, you need to add "method" parameter to the config. 
E.g.
```xml
<named_collections>
    <url_def>
        <method>PUT</method>
    <url_def>
</named_collections>
```
```
insert into table function url(url_def, ...);   -- (or use table engine, does not matter)
```
But I will probably should rename it to "write_method" instead of "method". (But leave "method" too, for compatibility)
And after https://github.com/ClickHouse/ClickHouse/pull/44327 is merged it will be possible to add "method" as key value `url(url_def, method = PUT)` - in previous versions it was missed as key value.
It is not mentioned in documentation because this possibility to choose method for write for url was added for testing purposes.

**Comment by rhuddleston** [comment]
Thanks for the quick response! What version does that named collections syntax currently work with?

**Comment by alexey-milovidov** [comment]
@rhuddleston download the latest release as follows:
```
curl https://clickhouse.com/ | sh
```

**Comment by kssenii** [comment]
@rhuddleston, the "method" parameter for url should work starting from 21.12.
