### ISSUE TITLE
Documentation for previous releases

### ISSUE THREAD

**Issue by FedericoCeratto** [ClickHouse/ClickHouse#44322]
The documentation at https://clickhouse.com/docs/en/ does not indicate which release it was built for.
Being able to browse documentation for previous releases would be really useful.

Most organizations do not run the latest release at all times and newer documentation might be inaccurate due to syntax and feature changes.
Thanks.

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/32349

**Comment by FedericoCeratto** [comment]
@den-crane This is not the same as #32349. Publishing copies of the documentation for previous releases can be done retroactively and with limited effort.

**Comment by den-crane** [comment]
@FedericoCeratto it was like this 2 years ago, but it requires some resources and CH documentation is not aligned with CH releases. You can use github and open specific branch https://github.com/ClickHouse/ClickHouse/blob/21.8/docs/en/index.md
