### ISSUE TITLE
Materialized views do not work on system tables

### ISSUE THREAD

**Issue by rjoelnorgren** [ClickHouse/ClickHouse#44321]
**Describe the unexpected behaviour**
Trying to persist system.backups across restarts via materialized views. New records in system.backups table do not result in inserts to downstream view.

**How to reproduce**
```
create materialized view if not exists admin.backups

engine = MergeTree()
order by (start_time)
ttl start_time + interval 1 month delete
as

select
    id,
    name,
    status,
    num_files,
    uncompressed_size,
    compressed_size,
    error,
    start_time,
    end_time
from system.backups
;

backup db_name.table_name to S3('endpoint', 'id', 'secret') async;

select * from admin.backups;
```
```
SELECT *
FROM admin.backups

Query id: 03c9917e-ae25-4045-b55e-98f60446b931

Ok.

0 rows in set. Elapsed: 0.001 sec. 
```
**Which ClickHouse server version to use**
22.12.1

**Expected behavior**
Records of backups are created in materialized view.

**Error message and/or stacktrace**

**Additional context**
Having backups persist across restarts would be nice!

**Comment by tavplubix** [comment]
system.backups is a virtual table that does not store any data, there are no INSERT queries that ingest data into that table, so there's no way it can work with materialized views
