### ISSUE TITLE
Better incremental backup (using shared set of uniq files instead of specific backup)

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#44331]
**Use case**

Current "problem" with incremental backups, is that they need to have FULL backups on which they depends.
And from time to time we need to recreate such FULL backups, which could take considerably long time for big datasets.

**Describe the solution you'd like**

Instead of relying on FULL backup, increments can rely on shared set of unique files/objects.
Those objects/files names will be derived from checksums (compressed-uncompressed), it should give us reasonably low chance of collision.
ClickHouse will upload only new files which are not exist in backup destination.
Metadata of backup will include mapping: table_name/part_name/file_name -> /backup/some_hex_of_checksums object.

It will make backup delete operation much more dangerous (as it can actually remove some objects which still being in use by other backups), so during backup delete ClickHouse should read all backups metadata and count reference counters for each file in every backup. 

(Or may be we can use multi versioning in object storage and have 2 set of commands: cheap DELETE & slow CLEANUP (which will remove unneeded files))

As potential extension of that task:

Something like "Instant Restore", which will create RO table with mapping required for s3 disk from backup metadata.
https://github.com/ClickHouse/ClickHouse/issues/42154
https://github.com/ClickHouse/ClickHouse/pull/43947#issuecomment-1341009928

**Describe alternatives you've considered**

Implement such logic externally, but it will be great to have such logic in-build in ClickHouse embedded backup.

**Additional context**

Partially related to https://github.com/ClickHouse/ClickHouse/issues/30407

**Comment by alexey-milovidov** [comment]
There is another direction - accommodate refcounts directly in the tables and do zero-copy instant backups.
The proposal in this task is somewhat similar - it will require refcounts, so why do a partial solution?

**Comment by UnamedRus** [comment]
>  The proposal in this task is somewhat similar - it will require refcounts, so why do a partial solution?

Basically, it looks that implementation of that within table natively looks like a much more bigger (but also interesting from other aspects) problem.

1. Table can use different disk types and disks for data, but backup should go to one specific location.

Can be potentially covered with PITR backups (which will offload all new files to disk automatically https://github.com/ClickHouse/ClickHouse/issues/30407) but it request to implement huge adjustment to table functionality.

2. No need to keep this reference counter always, only recalculate it during cleanup. (what if you have several millions of objects, we need something better than we have RN in ZK for zero copy) 

May be will not be big problem, if we will change current ref count storage. 

3. Actual table data objects should differ from backup objects. (IE, whatever happened during normal operation ClickHouse shouldn't alter data related to backup (if it's not delete or cleanup operation))

Can be covered during implementation of 1.

**Comment by UnamedRus** [comment]
I guess, something like this could looks like end goal (probably a bit far goal :) ) for me:

```
CREATE TABLE table_date (
....)
ENGINE=ReplicatedMergeTree
ORDER BY (key)
SETTINGS storage_policy = 'tiered', archive_policy = 's3_infrequent_access'
```

And in `archive_policy` we can define disk type and parameters for slicing of table states being put and purged from archive. (ie keep each insert for latest hour, hour snapshots for 1 day and etc)

Features:

* Read table state at specific time (basically from specific snapshot)
* Materialize table state to another table. (RO is fine)
* Make ad hoc named snapshots.
* Materialize snapshot to different storage. (create full backup from snapshot storage)
* Write archive to multiple destinations (sometimes clients can ask to store backup in their S3 as well)
