### ISSUE TITLE
Parquet files should be able to count from metadata

### ISSUE THREAD

**Issue by danthegoodman1** [ClickHouse/ClickHouse#44334]
**Describe the situation**
Paruqet file counting currently reads the entire file to count rows, where this can be done with the [parquet metatdata](https://parquet.apache.org/docs/file-format/metadata/)

**How to reproduce**

`ClickHouse local version 22.12.1.1752 (official build).`
```
SELECT count(*)
FROM file('*.parquet', 'Parquet')

Query id: 4dc914c1-b45a-4097-a111-c74c2efede3a

┌───count()─┐
│ 110000000 │
└───────────┘

1 row in set. Elapsed: 1.365 sec. Processed 105.69 million rows, 1.69 GB (77.43 million rows/s., 1.24 GB/s.)
```

**Expected performance**
Could be performed in ~16ms as DuckDB does:

```python
import duckdb
from time import time

con = duckdb.connect(database=':memory:')

con.execute('install parquet')
con.execute('load parquet')
print('done loading')

s = time()
con.execute('''
select count(*) from read_parquet('./*.parquet')
''')
e = time()
print(con.fetchall(), 'in', (e-s)*1000, 'ms')
```

```
@danthegoodman1 ➜ /workspaces/codespaces-blank $ python count.py 
done loading
[(110000000,)] in 16.06297492980957 ms
```

**Comment by KlokMiraj** [comment]
Hey I'd like to take on this issues if it's still up for a grab

**Comment by danthegoodman1** [comment]
> Hey I'd like to take on this issues if it's still up for a grab

Go for it!

**Comment by Avogar** [comment]
@KlokMiraj thank you for taking this task! I will assignt it to you. If you have any questions, you can ask here, I will try to help.
Also I want to share some initial ideas about implementation:
In storages we have special method `totalRows` that returns the number of rows in this storage. If it's not implemented, we just read one column (usually with the smallest type). By now there is no implementation for this method in `File/S3/URL/HDFS` storages, so we can implement them.
Such optimization can be also useful for other data formats, not only for Parquet, so it will be good to prepare some infrastracture for all formats that will allow to implement optimal row counter for any format in an easy way.
So, it will be good to:
- Add new interface like `IRowCounter` with method `count` (maybe you will come up with better names) silimar to `IInputFormat/ISchemaReader`.
- Allow to register this row counters in format factory (see `ForamatFactory.h`) and get it by format name.
- In `totalRows` method check if row counter is implemented for required format and use it (if not implemented, return `nullopt`)

**Comment by amosbird** [comment]
It's better to apply the technique of `min_max_count_projection` for these storage types. It will work with partition pruning and other data skipping structures, also known as small materialized aggregates or zone maps.

**Comment by Avogar** [comment]
> It's better to apply the technique of min_max_count_projection for these storage types

Totally agree. But it's a but different and more complex task. I think I will do it by miself in the near future. In this task I suggest implementing trivial count and extend it for all data formats (for example in CSV format we can count rows by counting lines in the data without reading columns).

**Comment by Algunenano** [comment]
> In this task I suggest implementing trivial count and extend it for all data formats (for example in CSV format we can count rows by counting lines in the data without reading columns).

I agree with the approach but CSV is a counterexample since a single DB row might extend several lines via quotes and new lines inside strings. A format where you get 1 to 1 match would be JSONEachRow

**Comment by Avogar** [comment]
> single DB row might extend several lines via quotes and new lines inside strings

Of course we should handle such cases. We already have similar logic in parallel parsing for CSV format

**Comment by alexey-milovidov** [comment]
> for example in CSV format we can count rows by counting lines in the data without reading columns

CSV cannot:
```
"Hello
world"
```

TSV also cannot:
```
Hello\
world
```

**Comment by alexey-milovidov** [comment]
> Of course we should handle such cases. We already have similar logic in parallel parsing for CSV format

Ok.

**Comment by alexey-milovidov** [comment]
Let's unlock this task.

**Comment by danthegoodman1** [comment]
Just pinging here as this is a pretty painful one to not have

**Comment by danthegoodman1** [comment]
Recent performance test:

```
ClickHouse server version 23.7.1 revision 54464

SELECT count()
FROM s3('https://s3.us-west-2.amazonaws.com/ookla-open-data/parquet/performance/type=*/year=*/quarter=*/*.parquet', 'Parquet')

Query id: 9ffb31cb-84c9-4554-b67e-1e9f74bf2d96

┌───count()─┐
│ 185832935 │
└───────────┘

1 row in set. Elapsed: 36.758 sec. Processed 185.83 million rows, 7.17 GB (5.06 million rows/s., 195.01 MB/s.)
```

DuckDB:
```
SELECT count(*) FROM read_parquet('s3://ookla-open-data/parquet/performance/type=*/year=*/quarter=*/*.parquet')

3.87 seconds
```

**Comment by alexey-milovidov** [comment]
At this moment in time, no one is working on this task.

**Comment by danthegoodman1** [comment]
:(

**Comment by lmangani** [comment]
> At this moment in time, no one is working on this task.

That's sad to hear, since this is extremely crucial to so many use cases for ClickHouse users and itnegrators.
Is there anything the community can do to revive this effort?

**Comment by Avogar** [comment]
I will start doing it this week.

**Comment by danthegoodman1** [comment]
@Avogar bless your soul. Related, I'd say the most important issue to clickhouse parquet performance is probably #23297

**Comment by Avogar** [comment]
I know about https://github.com/ClickHouse/ClickHouse/issues/23297 and have it in my plans after I finish current tasks (if no ono does it before me)
