### ISSUE TITLE
Add `parts`, `active_parts` and `total_marks` columns to `system.tables`.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#44336]
These columns will be set for tables of the MergeTree family.

**Comment by KlokMiraj** [comment]
Hi!
Dropping by to see if I can take on this issue. 
Thanks :)

**Comment by alexey-milovidov** [comment]
@KlokMiraj Sure!

See the src/Storages/System/StorageSystemTables.{h,cpp}
and the IStorage methods.

**Comment by KlokMiraj** [comment]
Just did, by simply looking I think we need to add three more entries on storage_metadata.setColumns. 
are parts and active_parts of string datatype ? I'm guessing total_marks are of int.

**Comment by alexey-milovidov** [comment]
Yes. You can do it by analogy with the `total_rows`, `total_bytes` fields.

> are parts and active_parts of string datatype ? I'm guessing total_marks are of int.

All UInt64:
- parts - the count of data parts;
- active_parts - the count of active data parts;

See the `system.parts` table which has this info.

**Comment by KlokMiraj** [comment]
I have created a pull request for this issue please kindly check.

**Comment by alexey-milovidov** [comment]
@KlokMiraj, the pull request was incorrectly created, please open another.

**Comment by ucasfl** [comment]
Fixed in https://github.com/ClickHouse/ClickHouse/pull/46161.
