### ISSUE TITLE
Run clickhouse-sever --config-file=config.xml in aarch64, crash at DB::registerFunctionUniqTheta

### ISSUE THREAD

**Issue by weiyan1989** [ClickHouse/ClickHouse#44353]
Run clickhouse-sever --config-file=config.xml in aarch64. stack Information

0x0000ffffbe5dd640 in _int_free () from /lib64/libc.so.6
#1  0x0000aaaac809d37c in Memory::deleteSized<>(void*, unsigned long) (ptr=0xaaaad70afa20, size=128) at /workspace/work/clickhouse/ClickHouse-master/src/Common/memory.h:81
#2  operator delete (ptr=0xaaaad70afa20, size=128) at /workspace/work/clickhouse/ClickHouse-master/src/Common/new_delete.cpp:137
#3  0x0000aaaac1014920 in std::__1::__libcpp_operator_delete[abi:v15000]<void*, unsigned long>(void*, unsigned long) (__args=128, __args=128)
    at /workspace/work/clickhouse/ClickHouse-master/contrib/llvm-project/libcxx/include/new:256
#4  0x0000aaaac10148a0 in std::__1::__do_deallocate_handle_size[abi:v15000]<>(void*, unsigned long) (__ptr=0xaaaad70afa20, __size=128)
    at /workspace/work/clickhouse/ClickHouse-master/contrib/llvm-project/libcxx/include/new:282
#5  0x0000aaaac1014830 in std::__1::__libcpp_deallocate[abi:v15000](void*, unsigned long, unsigned long) (__ptr=0xaaaad70afa20, __size=128, __align=1)
    at /workspace/work/clickhouse/ClickHouse-master/contrib/llvm-project/libcxx/include/new:296
#6  0x0000aaaac10737ac in std::__1::allocator<char>::deallocate[abi:v15000](char*, unsigned long) (this=0xaaaad70af9f8, 
    __p=0xaaaad70afa20 "select finalizeAggregation(uniqThetaIntersect(arrayReduce('uniqThetaState',[1,2]), arrayReduce('uniqThetaState',[2,3,4])));", __n=128)
    at /workspace/work/clickhouse/ClickHouse-master/contrib/llvm-project/libcxx/include/__memory/allocator.h:128
#7  0x0000aaaac1073588 in std::__1::allocator_traits<std::__1::allocator<char> >::deallocate[abi:v15000](std::__1::allocator<char>&, char*, unsigned long) (__a=..., 
    __p=0xaaaad70afa20 "select finalizeAggregation(uniqThetaIntersect(arrayReduce('uniqThetaState',[1,2]), arrayReduce('uniqThetaState',[2,3,4])));", __n=128)
    at /workspace/work/clickhouse/ClickHouse-master/contrib/llvm-project/libcxx/include/__memory/allocator_traits.h:282
#8  0x0000aaaad5decc28 in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string (this=0xaaaad70af9f8)
    at /workspace/work/clickhouse/ClickHouse-master/contrib/llvm-project/libcxx/include/string:2334
#9  0x0000aaaac1030780 in std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::~pair (this=0xaaaad70af9e0) at /workspace/work/clickhouse/ClickHouse-master/contrib/llvm-project/libcxx/include/__utility/pair.h:40
#10 0x0000aaaac1030738 in std::__1::__destroy_at[abi:v15000]<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, 0>(std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >*) (__loc=0xaaaad70af9e0) at /workspace/work/clickhouse/ClickHouse-master/contrib/llvm-project/libcxx/include/__memory/construct_at.h:63
#11 0x0000aaaac10306b8 in std::__1::destroy_at[abi:v15000]<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, 0>(std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >*) (__loc=0xaaaad70af9e0) at /workspace/work/clickhouse/ClickHouse-master/contrib/llvm-project/libcxx/include/__memory/construct_at.h:88
#12 0x0000aaaac103059c in std::__1::allocator_traits<std::__1::allocator<std::__1::__tree_node<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, void*> > >::destroy[abi:v15000]<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, void, void>(std::__1::allocator<std::__1::__tree_node<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, void*> >&, std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >*) (__p=0xaaaad70af9e0)
    at /workspace/work/clickhouse/ClickHouse-master/contrib/llvm-project/libcxx/include/__memory/allocator_traits.h:317
#13 0x0000aaaac10304c4 in std::__1::__tree<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::__map_value_compare<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>, std::__1::allocator<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > >::destroy (this=0xffffffff5de8, __nd=0xaaaad70af9c0)
    at /workspace/work/clickhouse/ClickHouse-master/contrib/llvm-project/libcxx/include/__tree:1800
#14 0x0000aaaac1030428 in std::__1::__tree<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::__map_value_compare<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>, std::__1::allocator<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > >::~__tree (this=0xffffffff5de8) at /workspace/work/clickhouse/ClickHouse-master/contrib/llvm-project/libcxx/include/__tree:1788
#15 0x0000aaaac102feb8 in std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > >::~map[abi:v15000]() (this=0xffffffff5de8)
    at /workspace/work/clickhouse/ClickHouse-master/contrib/llvm-project/libcxx/include/map:1163
#16 0x0000aaaac101e14c in DB::Documentation::~Documentation (this=0xffffffff5dd0) at /workspace/work/clickhouse/ClickHouse-master/src/Common/Documentation.h:46
#17 0x0000aaaac8086378 in DB::FunctionFactory::registerFunction<DB::FunctionUniqTheta<DB::UniqThetaIntersectImpl, DB::NameUniqThetaIntersect> >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Documentation, DB::IFactoryWithAliases<std::__1::pair<std::__1::function<std::__1::shared_ptr<DB::IFunctionOverloadResolver> (std::__1::shared_ptr<DB::Context const>)>, DB::Documentation> >::CaseSensitiveness) (this=0xaaaad6b24918 <DB::FunctionFactory::instance()::ret>, name=..., doc=..., 
    case_sensitiveness=DB::IFactoryWithAliases<std::__1::pair<std::__1::function<std::__1::shared_ptr<DB::IFunctionOverloadResolver> (std::__1::shared_ptr<const DB::Context>)>, DB::Documentation> >::CaseSensitive) at /workspace/work/clickhouse/ClickHouse-master/src/Functions/FunctionFactory.h:42
--Type <RET> for more, q to quit, c to continue without paging--
#18 0x0000aaaac8085dd8 in DB::FunctionFactory::registerFunction<DB::FunctionUniqTheta<DB::UniqThetaIntersectImpl, DB::NameUniqThetaIntersect> >(DB::Documentation, DB::IFactoryWithAliases<std::__1::pair<std::__1::function<std::__1::shared_ptr<DB::IFunctionOverloadResolver> (std::__1::shared_ptr<DB::Context const>)>, DB::Documentation> >::CaseSensitiveness) (this=0xaaaad6b24918 <DB::FunctionFactory::instance()::ret>, 
    doc=..., 
    case_sensitiveness=DB::IFactoryWithAliases<std::__1::pair<std::__1::function<std::__1::shared_ptr<DB::IFunctionOverloadResolver> (std::__1::shared_ptr<const DB::Context>)>, DB::Documentation> >::CaseSensitive) at /workspace/work/clickhouse/ClickHouse-master/src/Functions/FunctionFactory.h:34
#19 0x0000aaaac8085260 in DB::registerFunctionUniqTheta (factory=...) at /workspace/work/clickhouse/ClickHouse-master/src/Functions/UniqTheta/FunctionsUniqTheta.cpp:12
#20 0x0000aaaac6e68380 in DB::registerFunctions () at /workspace/work/clickhouse/ClickHouse-master/src/Functions/registerFunctions.cpp:14
#21 0x0000aaaac81c7ad0 in DB::Server::main (this=0xffffffffe7c0) at /workspace/work/clickhouse/ClickHouse-master/programs/server/Server.cpp:756
#22 0x0000aaaad26bc36c in Poco::Util::Application::run (this=0xffffffffe7c0) at /workspace/work/clickhouse/ClickHouse-master/contrib/poco/Util/src/Application.cpp:334
#23 0x0000aaaac81c6608 in DB::Server::run (this=0xffffffffe7c0) at /workspace/work/clickhouse/ClickHouse-master/programs/server/Server.cpp:485
#24 0x0000aaaad26dd9b4 in Poco::Util::ServerApplication::run (this=0xffffffffe7c0, argc=1, argv=0xaaaad6bf26c0)
    at /workspace/work/clickhouse/ClickHouse-master/contrib/poco/Util/src/ServerApplication.cpp:611
#25 0x0000aaaac81c4120 in mainEntryClickHouseServer (argc=1, argv=0xaaaad6bf26c0) at /workspace/work/clickhouse/ClickHouse-master/programs/server/Server.cpp:192
#26 0x0000aaaac100fe10 in main (argc_=1, argv_=0xffffffffee78) at /workspace/work/clickhouse/ClickHouse-master/programs/main.cpp:482

**Comment by alexey-milovidov** [comment]
You have built a modified version of ClickHouse:

```
0x0000ffffbe5dd640 in _int_free () from /lib64/libc.so.6
```
We don't use the GLibC's allocator.

Only official builds are supported.
The official build should be downloaded as follows:
```
curl https://clickhouse.com/ | sh
```

**Comment by weiyan1989** [comment]
Thinks, I try do it
