### ISSUE TITLE
truncate distributed table not work

### ISSUE THREAD

**Issue by cy2008** [ClickHouse/ClickHouse#44352]
I truncate a distributed table but data still exist when I count the distributed table, I don't know it is correct.

**Comment by DerekChia** [comment]
It might take some time for the rows to be truncated. How long did you wait? 

If there is an inactive replica, [replication_wait_for_inactive_replica_timeout](https://clickhouse.com/docs/en/operations/settings/settings#replication-wait-for-inactive-replica-timeout) will take 120 seconds by default to wait for the inactive replica to respond. See https://clickhouse.com/docs/en/sql-reference/statements/truncate/

**Comment by cy2008** [comment]
> It might take some time for the rows to be truncated. How long did you wait?
> 
> If there is an inactive replica, [replication_wait_for_inactive_replica_timeout](https://clickhouse.com/docs/en/operations/settings/settings#replication-wait-for-inactive-replica-timeout) will take 120 seconds by default to wait for the inactive replica to respond. See https://clickhouse.com/docs/en/sql-reference/statements/truncate/

I wait for a long time and it still not work.

DDL as follows:

CREATE TABLE IF NOT EXISTS `diagnosis_scenarios`.`network_healthy_centralized` ON CLUSTER `cni`
(
    `id`                  UInt64 NOT NULL COMMENT '主键',
    `resource_pool`       String NOT NULL COMMENT 'az（资源池）',
    `device_type`         String NOT NULL COMMENT '设备类型',
    `health_status`       String NOT NULL COMMENT '设备健康状况',
    `group_name`          String COMMENT '设备组  ..._group',
    `group_health_status` String COMMENT '设备组健康状况',
    `warnning`            Int32 COMMENT '是否需要告警(0不上报，1上报)',
    `mgmt_ip`             String NOT NULL COMMENT '设备IP',
    `status`              Int32 NOT NULL COMMENT '与下一字段共同控制状态值',
    `status1`             Int32 NOT NULL COMMENT '与上一字段共同控制状态值',
    `analysis_time`       String NOT NULL COMMENT '设备分析时间',
    `partition_field`     Int32 NOT NULL COMMENT '用于数据分区'
) ENGINE = MergeTree
      primary key (`device_type`, `resource_pool`, `analysis_time`, `mgmt_ip`);

CREATE TABLE IF NOT EXISTS `diagnosis_scenarios`.`network_healthy_centralized_all` ON CLUSTER `cni`
(
    `id`                  UInt64 NOT NULL COMMENT '主键',
    `resource_pool`       String NOT NULL COMMENT 'az（资源池）',
    `device_type`         String NOT NULL COMMENT '设备类型',
    `health_status`       String NOT NULL COMMENT '设备健康状况',
    `group_name`          String COMMENT '设备组  ..._group',
    `group_health_status` String COMMENT '设备组健康状况',
    `warnning`            Int32 COMMENT '是否需要告警(0不上报，1上报)',
    `mgmt_ip`             String NOT NULL COMMENT '设备IP',
    `status`              Int32 NOT NULL COMMENT '与下一字段共同控制状态值',
    `status1`             Int32 NOT NULL COMMENT '与上一字段共同控制状态值',
    `analysis_time`       String NOT NULL COMMENT '设备分析时间',
    `partition_field`     Int32 NOT NULL COMMENT '用于数据分区'
) ENGINE = Distributed(`cni`, `diagnosis_scenarios`, `network_healthy_centralized`, javaHash(`resource_pool`));

Truncate:
TRUNCATE TABLE diagnosis_scenarios.network_healthy_centralized_all ON CLUSTER `cni`;
or
TRUNCATE TABLE diagnosis_scenarios.network_health_diagnosis_all ON CLUSTER `cni` settings replication_alter_partitions_sync = 2;

Count:
select count() from diagnosis_scenarios.network_healthy_centralized_all;

**Comment by save-my-heart** [comment]
You should do this operation on MergeTree table, not Distributed table

**Comment by DerekChia** [comment]
Yes, you should reference the underlying table instead. Distributed table does not store data of their own.

`TRUNCATE TABLE diagnosis_scenarios. network_healthy_centralized ON CLUSTER cni;` should work.

Perhaps we should improve this scenario to:
- Replace 'Ok.' with an error when truncate is done on a distributed table
- Forward the truncate request on distributed table to all remote tables
