### ISSUE TITLE
Why has the ReplacingMergeTree engine been used for 2 days without merging duplicate data

### ISSUE THREAD

**Issue by ykjxx** [ClickHouse/ClickHouse#44362]
Why has the ReplacingMergeTree engine been used for 2 days without merging duplicate data

**Comment by den-crane** [comment]
https://kb.altinity.com/engines/mergetree-table-engine-family/replacingmergetree/altinity-kb-replacingmergetree-does-not-collapse-duplicates/

see https://github.com/ClickHouse/ClickHouse/issues/35836#issuecomment-1352740295
