### ISSUE TITLE
Alias column not found in join

### ISSUE THREAD

**Issue by viktor-klestov** [ClickHouse/ClickHouse#44365]
**Describe what's wrong**

Query returns error

**Does it reproduce on recent release?**

yes

**How to reproduce**

```
create table test
(
    id           UInt64,
    val String alias 'some expression'
) ENGINE = MergeTree
order by tuple();
```
```
select val from numbers(1000) n join test t on n.number = t.id;
```

**Error message and/or stacktrace**

```
Received exception from server (version 22.8.1):
Code: 8. DB::Exception: Received from localhost:9000. DB::Exception: Cannot find column `val` in source stream, there are only columns: []. (THERE_IS_NO_COLUMN)
```

**Additional context**

Possibly related to known bug #13210 and similarly works if you swap tables

**Comment by den-crane** [comment]
workaround

```sql
select val from numbers(1000) n left join (select id,val from test) t on n.number = t.id;
```

**Comment by den-crane** [comment]
works with analyzer

https://fiddle.clickhouse.com/4cb0a63f-544b-40c5-9521-8c863d742c03

**Comment by viktor-klestov** [comment]
Unfortunately analyzer breaks other queries
https://fiddle.clickhouse.com/d8df8a89-423c-4426-ab1b-88ba0eaa5190

**Comment by den-crane** [comment]
@viktor-klestov analyzer is not ready for production.

@kitaisreal https://fiddle.clickhouse.com/d8df8a89-423c-4426-ab1b-88ba0eaa5190
