### ISSUE TITLE
Support of the mode argument in toDayOfWeek function toDayOfWeek(date[,mode])

### ISSUE THREAD

**Issue by JangalaPushkala** [ClickHouse/ClickHouse#44417]
Support of the mode argument in toDayOfWeek function **toDayOfWeek(date[,mode])**

Similar to the support of mode argument in toWeek(date[,mode]), require the support of the mode argument in toDayOfWeek function.
The second-argument 'mode' of toDayOfWeek() should configure whether the week starts on Sunday or Monday since start of week is different in different zones.

Example:
Current implementation of clickhouse supports Monday as 1, and Sunday as 7 which implies Monday as start of week.
But consider US week number which requires Sunday as 1, and Saturday as 7 which implies Sunday as start of week.

Could you please let us know if there is any other custom way this could be achieved.

**Comment by rschu1ze** [comment]
There is hope that this can be done: #44860.

**Comment by taiyang-li** [comment]
It is already supported now in https://github.com/ClickHouse/ClickHouse/pull/44860
