### ISSUE TITLE
Alias does not work on exists column

### ISSUE THREAD

**Issue by Fanvadar** [ClickHouse/ClickHouse#44412]
**Describe the unexpected behaviour**
When using `AS` on a column created using the `EXISTS` keyword, the alias is not respected. 

**How to reproduce**
* Which ClickHouse server version to use: **22.7**
* Which interface to use, if matters: **play UI (http://localhost:8123/play)**
* Queries to run that lead to unexpected result:
```
SELECT EXISTS(SELECT 1) AS mycheck
```
Returns:
| in(1, _subquery5779) |
| -- |
| 1 |

**Expected behavior**
As in MySQL, I expect: 
| mycheck |
| -- |
| 1 |

**Comment by procopym** [comment]
Hi! That's the solution for this behavior? Is it fixed in latest CH versions?
