### ISSUE TITLE
[HELP] Clickhouse does not start in Docker container

### ISSUE THREAD

**Issue by lbb211** [ClickHouse/ClickHouse#44419]
start log:
022.12.20 07:52:13.650102 [ 2639 ] {} <Information> DatabaseCatalog: Found 0 partially dropped tables. Will load them and retry removal.
2022.12.20 07:52:13.650320 [ 2639 ] {} <Information> DatabaseAtomic (default): Metadata processed, database default has 0 tables and 0 dictionaries in total.
2022.12.20 07:52:13.650337 [ 2639 ] {} <Information> TablesLoader: Parsed metadata of 0 tables in 1 databases in 4.866e-05 sec
2022.12.20 07:52:13.650348 [ 2639 ] {} <Information> TablesLoader: Loading 0 tables with 0 dependency level
2022.12.20 07:52:13.650359 [ 2639 ] {} <Information> DatabaseAtomic (default): Starting up tables.
2022.12.20 07:52:13.650369 [ 2639 ] {} <Information> DatabaseAtomic (system): Starting up tables.
2022.12.20 07:52:13.656117 [ 2639 ] {} <Information> BackgroundSchedulePool/BgSchPool: Create BackgroundSchedulePool with 128 threads
2022.12.20 07:52:13.662353 [ 2639 ] {} <Debug> Application: Loaded metadata.
2022.12.20 07:52:13.662391 [ 2639 ] {} <Information> Application: It looks like the process has no CAP_SYS_NICE capability, the setting 'os_thread_priority' will have no effect. It could happen due to incorrect ClickHouse package installation. You could resolve the problem manually with 'sudo setcap cap_sys_nice=+ep /usr/bin/clickhouse'. Note that it will not work on 'nosuid' mounted filesystems.
2022.12.20 07:52:13.711194 [ 2639 ] {} <Trace> AsynchronousMetrics: Scanning /sys/class/thermal
2022.12.20 07:52:13.711341 [ 2639 ] {} <Trace> AsynchronousMetrics: Scanning /sys/block
2022.12.20 07:52:13.711553 [ 2639 ] {} <Trace> AsynchronousMetrics: Scanning /sys/devices/system/edac
2022.12.20 07:52:13.711806 [ 2639 ] {} <Trace> AsynchronousMetrics: Scanning /sys/class/hwmon
2022.12.20 07:52:13.712921 [ 2639 ] {} <Information> Application: Shutting down storages.
2022.12.20 07:52:13.763464 [ 2639 ] {} <Trace> BackgroundSchedulePool/BgSchPool: Waiting for threads to finish.
2022.12.20 07:52:13.763661 [ 2639 ] {} <Debug> Application: Shut down storages.
2022.12.20 07:52:14.628239 [ 2639 ] {} <Debug> Application: Destroyed global context.
2022.12.20 07:52:14.629159 [ 2639 ] {} <Fatal> Application: system exception
2022.12.20 07:52:14.629190 [ 2639 ] {} <Information> Application: shutting down
2022.12.20 07:52:14.629206 [ 2639 ] {} <Debug> Application: Uninitializing subsystem: Logging Subsystem
2022.12.20 07:52:14.629425 [ 2640 ] {} <Trace> BaseDaemon: Received signal -2
2022.12.20 07:52:14.629523 [ 2640 ] {} <Information> BaseDaemon: Stop SignalListener thread
===============================================

the docker container can start when the run "docker run --dit -network host  xxx",  docker container does not start when not have -network host option , There was no problem a long time ago. It happened recently

**Comment by DerekChia** [comment]
Does this work?

```
docker network create clickhouse-net
docker run -d --name clickhouse-server --ulimit nofile=262144:262144 --network clickhouse-net -p 8123:8123 -p 9000:9000 -p 9009:9009 clickhouse/clickhouse-server:22.12
```

**Comment by lbb211** [comment]
> Does this work?
> 
> ```
> docker network create clickhouse-net
> docker run -d --name clickhouse-server --ulimit nofile=262144:262144 --network clickhouse-net -p 8123:8123 -p 9000:9000 -p 9009:9009 clickhouse/clickhouse-server:22.12
> ```
HI I test it ，but not work

**Comment by DerekChia** [comment]
> > Does this work?
> > ```
> > docker network create clickhouse-net
> > docker run -d --name clickhouse-server --ulimit nofile=262144:262144 --network clickhouse-net -p 8123:8123 -p 9000:9000 -p 9009:9009 clickhouse/clickhouse-server:22.12
> > ```
> 
> HI I test it ，but not work

Is it giving you the same error? Seems like you might have issues with docker networks.

**Comment by lbb211** [comment]
It is giving the same error.  It is not start when set --netwrok bridge . but it is start when set --network host  It happened recently
