### ISSUE TITLE
LDAP + Okta (MFA) lead to multiple notification push for each login.

### ISSUE THREAD

**Issue by zheyu001** [ClickHouse/ClickHouse#44420]
(you don't have to strictly follow this form)

**Describe the issue**
Hi there, we are trying to integrate ClickHouse Cluster with LDAP + [Okta](https://www.okta.com/), and our Okta is configured with multi factor authentication. So in each login, after type in password, it will trigger cell phone notification. Our test cluster is  1(shard) * 2 (replicas) and it triggered 2 notifications for each login. 

Since ClickHouse is not follow master/slave model. I'm assuming under the hood each replica is sending 1 request to LDAP, which triggered 2 notification. This is fine for small cluster. But when a cluster is having hundreds of hosts, it will be pretty bad. 

Is there any chance we can optimize this to only trigger one authentication? Thanks a lot!

**How to reproduce**
* 22.12
* Which interface to use, if matters
* It doesn't matter. But we are using ClickHouse CLI. 
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

**Expected behavior**
One authentication for each login. 

**Error message and/or stacktrace**

**Additional context**

**Comment by filimonov** [comment]
Do you use role mapping? Can you share the fragments of ClciKhouse configs related to LDAP?

**Comment by zheyu001** [comment]
Sure. 
```
    ldap_servers/default_server/host: LDAP_HOST
    ldap_servers/default_server/port: 636
    ldap_servers/default_server/bind_dn: uid={user_name}@XXXX.com,dc=XXXX,dc=okta,dc=com
    ldap_servers/default_server/verification_cooldown: 43200
    ldap_servers/default_server/enable_tls: yes
    ldap_servers/default_server/tls_require_cert: never
    ldap_servers/default_server/user_dn_detection/base_dn: ou=users,dc=XXXXXX,dc=okta,dc=com
    ldap_servers/default_server/user_dn_detection/search_filter: (&amp;(objectclass=person)(uid={user_name}@*))
    user_directories/ldap/server: default_server
    user_directories/ldap/roles/default_ro: ""
```

**Comment by zheyu001** [comment]
Hey, just want to do a quick follow up about this. Thanks!

**Comment by alexey-milovidov** [comment]
clickhouse-client established two connections to the server: one for interactive queries and another to fetch the hints for suggestions (autocomplete). You can disable suggestions with `-A` or `--disable-suggestion` in the command line.
