### ISSUE TITLE
sparkbar aggregate function causes server to be killed with OOM

### ISSUE THREAD

**Issue by vzakaznikov** [ClickHouse/ClickHouse#44467]
**Describe what's wrong**
Using `sparkbar` aggregate function on tables that contain large UInt64 values causes OOM (Out of Memory) Killer process to kill ClickHouse server irrespective of any memory usage restrictions set.

**Does it reproduce on recent release?**
Yes. Any version `>=21.11` including the latest `22.12`. Also reproducible on ClickHouse.Cloud.

**How to reproduce**

```sql
DROP TABLE IF EXISTS test; 
CREATE TABLE test (x UInt64, y UInt8) Engine=MergeTree ORDER BY tuple();
INSERT INTO test VALUES (18446744073709551615,255),(0,0),(0,0),(4036797895307271799,163)
SELECT sparkbar(9)(x,y) FROM test;
```

**Expected behavior**

Memory restrictions should be enforced and server should not be killed with OOM.

**Error message and/or stacktrace**

```
2022.12.20 01:48:30.983421 [ 1 ] {} <Fatal> Application: Child process was terminated by signal 9 (KILL). If it is not done by 'forcestop' command or manually, the possible cause is OOM Killer (see 'dmesg' and look at the '/var/log/kern.log' for the details).
```

**Comment by tavplubix** [comment]
Ref: https://github.com/ClickHouse/ClickHouse/pull/27481
cc: @nicelulu, @evillique
