### ISSUE TITLE
SSH clickhouse client problem！！

### ISSUE THREAD

**Issue by baishuailei666** [ClickHouse/ClickHouse#44473]
When I execute the insert statement through ssh, I always timeout, but other statements do not.
![image](https://user-images.githubusercontent.com/33680392/208808977-af87d0da-cfa2-4bc3-b56b-788f30a4de0a.png)

But it's OK to use Linux
![image](https://user-images.githubusercontent.com/33680392/208809072-ae39ac77-b9a1-4aa5-bc42-c51147aa6335.png)

I can't find anything wrong

**Comment by baishuailei666** [comment]
How should I solve it?

**Comment by filimonov** [comment]
The problem does not seem related to ClickHouse. Most probably, you (or [the library](https://github.com/hierynomus/sshj) you use for ssh) messed up something with quotes in the command

**Comment by baishuailei666** [comment]
Please ask me how to solve the problem. I have no idea
