### ISSUE TITLE
Docs Issue

### ISSUE THREAD

**Issue by htavakkoli1368** [ClickHouse/ClickHouse#44476]
hello . I am using  ClickHouse database for one year it is good but there is no useful Documents . your Documents is too short and there is not enough explanation given. for example you are talking about ```In``` and ```Global In```  but you only explain about ```In``` and there is nothing about ```Global In``` and when we are searching about ```Global In``` we can not find anything on the Internet . also as a suggestion , add related tags to your Documentation so people could find topics easier. please provide better Documents section.

thanks

**Comment by Jacobify** [comment]
I also had the similar issue , I would definitely appreciate it if there was some sort of documentation regarding `Global In` and `In`.

**Comment by Minktong** [comment]
While ClickHouse is a very powerful database engine in its own right in some areas without any competition even, the documentation lacks a lot of required items, some items are missing, it is hard to navigate, the explanations are not clear enough, some items are only mentioned without any explanation about what they are or some examples, and if you are looking for a specific topic it is hard to fid it easily. Like if you wanted to read about the use of regular expressions, you don't really know where to look for that.

**Comment by filimonov** [comment]
> there is nothing about Global In

https://clickhouse.com/docs/en/sql-reference/operators/in/#distributed-subqueries

> searching about Global In we can not find anything on the Internet  

Try first result: 
https://www.google.com/search?q=clickhouse+%22global+in%22

;)

> , the explanations are not clear enough, 

ClickHouse is open-source project, you can also help to improve the documentation. Every page have 'Edit this page' link on the bottom.

**Comment by filimonov** [comment]
At the same time: i agree that the search on the docs page itself works poor, and cross-links / navigation can be better.

**Comment by htavakkoli1368** [comment]
> > there is nothing about Global In
> 
> https://clickhouse.com/docs/en/sql-reference/operators/in/#distributed-subqueries
> 
> > searching about Global In we can not find anything on the Internet
> 
> Try first result: https://www.google.com/search?q=clickhouse+%22global+in%22
> 
> ;)
> 
> > , the explanations are not clear enough,
> 
> ClickHouse is open-source project, you can also help to improve the documentation. Every page have 'Edit this page' link on the bottom.

thanks for your response.
