### ISSUE TITLE
Maybe there is a bug about ReadBufferFromPocoSocket

### ISSUE THREAD

**Issue by chloro-pn** [ClickHouse/ClickHouse#44510]
I only found this bug in the process of reading the source code. In the function ```bool ReadBufferFromPocoSocket:: nextImpl()```:
```c++
bool ReadBufferFromPocoSocket::nextImpl()
{
    ssize_t bytes_read = 0;
    Stopwatch watch;

    SCOPE_EXIT({
        // / NOTE: it is quite inaccurate on high loads since the thread could be replaced by another one
        ProfileEvents::increment(ProfileEvents::NetworkReceiveElapsedMicroseconds, watch.elapsedMicroseconds());
        ProfileEvents::increment(ProfileEvents::NetworkReceiveBytes, bytes_read);
    });

    /// Add more details to exceptions.
    try
    {
        CurrentMetrics::Increment metric_increment(CurrentMetrics::NetworkReceive);

        /// If async_callback is specified, and read will block, run async_callback and try again later.
        /// It is expected that file descriptor may be polled externally.
        /// Note that receive timeout is not checked here. External code should check it while polling.
        while (async_callback && !socket.poll(0, Poco::Net::Socket::SELECT_READ))
            async_callback(socket.impl()->sockfd(), socket.getReceiveTimeout(), socket_description);

        bytes_read = socket.impl()->receiveBytes(internal_buffer.begin(), internal_buffer.size());
    }
    catch (const Poco::Net::NetException & e)
    {
        throw NetException(e.displayText() + ", while reading from socket (" + peer_address.toString() + ")", ErrorCodes::NETWORK_ERROR);
    }
    catch (const Poco::TimeoutException &)
    {
        throw NetException(fmt::format("Timeout exceeded while reading from socket ({}, {} ms)",
            peer_address.toString(),
            socket.impl()->getReceiveTimeout().totalMilliseconds()), ErrorCodes::SOCKET_TIMEOUT);
    }
    catch (const Poco::IOException & e)
    {
        throw NetException(e.displayText() + ", while reading from socket (" + peer_address.toString() + ")", ErrorCodes::NETWORK_ERROR);
    }

    if (bytes_read < 0)
        throw NetException("Cannot read from socket (" + peer_address.toString() + ")", ErrorCodes::CANNOT_READ_FROM_SOCKET);

    if (bytes_read)
        working_buffer.resize(bytes_read);
    else
        return false;

    return true;
}
```
The function only read as much data as possible from the socket, but the number of bytes read is uncertain. Moreover, I noticed that  the ```nextImpl``` function is called by the ```next``` function, and the ```next``` function is only called by the ```eof``` function, which means that the number of bytes we read through the ```eof``` function is not fixed.  

However, in the function ```Packet Connection::receivePacket()```，it uses function ```readStrict``` to read data, which I think is unreasonable, because the function needs at least n bytes of data in the buffer, otherwise an exception is thrown. However, we cannot guarantee that there must be enough data in the buffer after every ```eof``` call.

For example:
```c++
inline void readStringBinary(std::string & s, ReadBuffer & buf, size_t MAX_STRING_SIZE = DEFAULT_MAX_STRING_SIZE)
{
    size_t size = 0;
    readVarUInt(size, buf);

    if (size > MAX_STRING_SIZE)
        throw Poco::Exception("Too large string size.");

    s.resize(size);
    buf.readStrict(s.data(), size);
}
```

I think we need to provide a function **X** with stronger guarantee than ```eof```. After the function **X** returns, we need to ensure that the buffer has at least n bytes of data, and n is specified by the user.  
If this is not a bug, I hope someone can explain the mechanism here and thank you：）

**Comment by tavplubix** [comment]
The function X is `readStrict`.

**Comment by chloro-pn** [comment]
I mean that function **X** should call ```next``` to read data circularly until there is enough data in the buffer that users need.  
 
However, function ```readStrict``` only reads the existing data in the current buffer. If not enough data is read this time, an exception is thrown:
https://github.com/ClickHouse/ClickHouse/blob/fbff52847cf591ff0617721cd3483ccadc313634/src/IO/ReadBuffer.h#L187

**This is incorrect because TCP is a streaming protocol.**

In addition, you can search by keyword **Cannot read all data. Bytes read:**  in the project, there are many unresolved issues, like:
* https://github.com/ClickHouse/ClickHouse/issues/41756
* https://github.com/ClickHouse/ClickHouse/issues/33839
* https://github.com/ClickHouse/ClickHouse/issues/16984
* https://github.com/ClickHouse/ClickHouse/issues/4959

@den-crane

**Comment by chloro-pn** [comment]
@tavplubix

**Comment by tavplubix** [comment]
> I mean that function X should call next to read data circularly until there is enough data in the buffer that users need.

That's exactly what it does:
https://github.com/ClickHouse/ClickHouse/blob/fbff52847cf591ff0617721cd3483ccadc313634/src/IO/ReadBuffer.h#L170-L189

**Comment by tavplubix** [comment]
> In addition, you can search by keyword Cannot read all data. Bytes read: in the project, there are many unresolved issues

`Cannot read all data` is never an independent issue, it always indicates another issue like a server crash (critical bug) or broken network connectivity (infrastructure issue that we cannot handle).

**Comment by chloro-pn** [comment]
got it.. I made a mistake and sorry for that : |

**Comment by tavplubix** [comment]
No problem, our buffers are quite complicated and the interface is inconvenient and counterintuitive, so it's easy to get confused.
