### ISSUE TITLE
One Table in one ClickHouse server (out of the 3) is not being written

### ISSUE THREAD

**Issue by sundarv85** [ClickHouse/ClickHouse#44516]
**Describe the unexpected behaviour**
We have in production a 1 database (metrics) with 5 tables (events, stats etc), which is running in 3 clickhouse servers (with 1 replica for each of the 3). In that, one particular table alone (events table) the data is not being written in the 2nd clickhouse server (and its replica as well).

However, in the logs, we see that the shard is indeed being written. But no data is reported in that shard for that table alone (events table alone). It was working fine for almost a year. Only from last week, this has been breaking. We haven't changed anything in our writers or the clickhouse configurations. Note that this table has the highest data that is coming in. The rest of the tables are working in that 2nd server and its replica correctly. 

```
2022.12.22 14:18:39.835942 [ 3387 ] {} <Trace> MergeTreeSequentialSource: Reading 2 marks from part 20221218_217259_217259_0, total 3 rows starting from the beginning of the part
2022.12.22 14:18:39.836611 [ 3412 ] {} <Debug> metrics.events_shard (ReplicatedMergeTreeQueue): Pulling 1 entries to queue: log-0062294472 - log-0062294472
2022.12.22 14:18:39.837791 [ 3387 ] {} <Trace> MergeTreeSequentialSource: Reading 2 marks from part 20221218_217260_217260_0, total 9 rows starting from the beginning of the part
2022.12.22 14:18:39.839239 [ 3412 ] {} <Debug> metrics.events_shard (ReplicatedMergeTreeQueue): Pulled 1 entries to queue.
2022.12.22 14:18:39.839533 [ 3387 ] {} <Trace> MergeTreeSequentialSource: Reading 2 marks from part 20221218_217261_217261_0, total 8 rows starting from the beginning of the part
```

**How to reproduce**
* Which ClickHouse server version to use
20.5.2

* Which interface to use, if matters
native interface

Any suggestions?

**Comment by den-crane** [comment]
20.5.2 is obsolete and out of support.







Can you share `select * from system.replication_log format Vertical` from all servers.

**Comment by den-crane** [comment]
no info
