### ISSUE TITLE
All tables in a single file

### ISSUE THREAD

**Issue by alanpaulkwan** [ClickHouse/ClickHouse#44515]
**Problem**
clickhouse-local --path='somepathname'

**I make one table**

ls -lah somepathname/* /* | wc -l

**745 files**

**Why is this a problem?**

portable installation cannot be shared easily in Dropbox, for example, which is the DuckDB/SQLite use case

If there was an option to have a single file it would make the database portable like DuckDB

**Comment by alexey-milovidov** [comment]
There is no support for single-file databases in ClickHouse.
