### ISSUE TITLE
drop table error

### ISSUE THREAD

**Issue by BlackSinny** [ClickHouse/ClickHouse#44525]
- sql
```sql
DROP TABLE bas_user_32_distributed ON CLUSTER xxx;
```
- error message
```bash
std::exception. Code: 1001, type: std::__1::__fs::filesystem::filesystem_error, e.what() = filesystem error: in rename: Invalid cross-device link [/var/lib/clickhouse/store/d09/d0951232-32eb-4728-9095-123232eb4728/bas_user_32_distributed.sql] [/var/lib/clickhouse/metadata_dropped/bas.bas_user_32_distributed.50c819c2-f64f-4d82-90c8-19c2f64fcd82.sql]
```

- engine
ReplicatedReplacingMergeTree

##  What i am doing
sub table is bas_user_32, some column in subtable but not in distribute table.
so i want drop distribute table,an refresh it, but unfortunately  something went wrong

**Comment by tavplubix** [comment]
Looks like your configuration is incorrect: `/var/lib/clickhouse/store/` and `/var/lib/clickhouse/metadata_dropped` are located on different disks. See https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/mergetree#table_engine-mergetree-multiple-volumes_configure

**Comment by BlackSinny** [comment]
problem has sloved...
No soft link is configured for the directory

```bash
No soft link is configured for the directory
```
