### ISSUE TITLE
Add documentation for allowing experimental transactions

### ISSUE THREAD

**Issue by Alex-Cheng** [ClickHouse/ClickHouse#44523]
Clickhouse has more capability than what its document states. For example, the transacton capability can be enabled by setting `allow_experimental_transactions`. But you cannot find it in documentation at all. Without documentation, how can users use it?

![image](https://user-images.githubusercontent.com/1518453/209265651-03d4d0af-efea-443b-98b8-19eb917cf833.png)
No document. How can I know I should set it to be 42 rather than 1? I have to learn it via source code.

Why not write more documents?

**Comment by den-crane** [comment]
>Why not write more documents?

Lack of manpower.

**Comment by rfraposa** [comment]
Sorry @Alex-Cheng - this should be documented. Reopening so we can track the progress. Thanks!

**Comment by den-crane** [comment]
42 is just a joke, and number except 0 enables boolean settings.

**Comment by den-crane** [comment]
Transactions are supported only for MergeTree family tables  and not supported for Replicated.

There is also user's settings  `implicit_transaction`, `throw_on_unsupported_query_inside_transaction` https://github.com/ClickHouse/ClickHouse/issues/42140

**Comment by alexey-milovidov** [comment]
Transactions are under development, and the experimental setting allows testing and preview of this feature for developers. Until it is ready for production usage, no detailed documentation is needed. The lack of documentation is also crucial for the easy removal of unfinished features if needed.

**Comment by Alex-Cheng** [comment]
BTW, I enabled `implicit_transaction` and add setting `<allow_experimental_transactions>42</allow_experimental_transactions>`, but always got "transaction not implemented " on each SQL query.
