### ISSUE TITLE
Persistent virtual column `_block_number`

### ISSUE THREAD

**Issue by alesapin** [ClickHouse/ClickHouse#44532]
> (you don't have to strictly follow this form)

A lot of usecases for debugging and introspection.

> A clear and concise description of what is the intended usage scenario is.

Thanks to @davenger we have some basic infrastructure for persistent virtual columns. First example is `_row_exists` column. We need to implement `_block_number` column which will be hidden by default, but can be queried any time with explicit name in `SELECT` query. Serialization of the column should be optional (with setting).

**Comment by alexey-milovidov** [comment]
It will also help for https://github.com/ClickHouse/ClickHouse/issues/42990

**Comment by alesapin** [comment]
Additional comments:
1. Code where we write fresh inserts to disk: ordinary StorageMergeTree: https://github.com/ClickHouse/ClickHouse/blob/master/src/Storages/MergeTree/MergeTreeSink.cpp#L56, StorageReplicatedMergeTree: https://github.com/ClickHouse/ClickHouse/blob/master/src/Storages/MergeTree/ReplicatedMergeTreeSink.cpp#L296.
2. Base class for managing data parts: https://github.com/ClickHouse/ClickHouse/blob/master/src/Storages/MergeTree/MergeTreeData.cpp
3. StorageMergeTree + block number allocation https://github.com/ClickHouse/ClickHouse/blob/master/src/Storages/StorageMergeTree.cpp#L2010-L2012
But I got an interesting thought: Maybe we can avoid touching initial writing code (Sinks for INSERT queries), because we always can restore `_block_number` from zero-level parts name, like `202010_5_5_0` or `all_9999_9999_0`.

For non-zero-level parts we should persist this column during Merges and Mutations. Corresponding code can be found in:
1. MergerMutator: https://github.com/ClickHouse/ClickHouse/blob/master/src/Storages/MergeTree/MergeTreeDataMergerMutator.cpp#L514-L581
2. MergeTask and MutateTask.
So what we can do:
1. For zero level parts `_block_number` is pure virtual column. It's not stored on disk (serialized) and when user query it -- we calculate it on fly from part name.
2. During merge we materialize `_block_number` unconditionally.

So maybe it will be possible to implement `_block_number` support on IMergeTreeDataPart level?

**Comment by tavplubix** [comment]
Also please consider automatically applying `Delta` codec to that column (so it will compress perfectly)

**Comment by ucasfl** [comment]
Why we need to persistent it, we can just get it from part_info?

**Comment by SmitaRKulkarni** [comment]
The new column _block_number will have the original block number of the row. part_info only has min block & max block and number of times its been merged or the new block. But original block number is currently not stored.
