### ISSUE TITLE
PGO build

### ISSUE THREAD

**Issue by zamazan4ik** [ClickHouse/ClickHouse#44567]
**Use case**

Try to improve Clickhouse performance even more!

**Describe the solution you'd like**

There is an idea that PGO (and BOLT) could help with improving performance even more! There are a lot of examples of different software, where PGO helps a lot with performance (e.g. ScyllaDB from the database world).

I have searched over the issue tracker about the idea but didn't find earlier results regarding PGO. BOLT also could help since for some software it allows to gain performance even from the builds with PGO.

There are several options. I'd appreciate it if you could provide an easy way to build Clickhouse with PGO. And experienced users will be able to do it on their own for their own usage scenarios. Another option is to optimize Clickhouse build with a generic-enough profile.

**Comment by rschu1ze** [comment]
https://github.com/llvm/llvm-project/tree/main/bolt

It seems to me that BOLT optimization is independent of ClickHouse's build. One would need to 1. build ClickHouse as usual 2. run ClickHouse under `perf` using a workload of choice 3. optimize the ClickHouse binary using the profiler output.

**Comment by zamazan4ik** [comment]
> It seems to me that BOLT optimization is independent of ClickHouse's build. One would need to 1. build ClickHouse as usual 2. run ClickHouse under perf using a workload of choice 3. optimize the ClickHouse binary using the profiler output. And I think in one form or the other this is true for any PGO approach.

That's true. I mean from the CH build system perspective, BOLT integration could be done via developing build scripts for running CH under sample load, collecting profiles and then applying them to CH binary with BOLT.

Also, would be interesting to see how much performance could be gained from CH with BOLT.

**Comment by alexey-milovidov** [comment]
@zamazan4ik, let's test the PGO build similarly to how you've done it here: https://github.com/ydb-platform/ydb/issues/140#issuecomment-1483943715

There is a reproducible benchmark for comparison: https://github.com/ClickHouse/ClickBench

**Comment by zamazan4ik** [comment]
I will try to perform the same benchmarks for ClickHouse and report the results.

**Comment by zamazan4ik** [comment]
Here I want to share some results after playing with ClickHouse and PGO (and BOLT).

My setup:
1. OS: Fedora 38.
2. Linux kernel: 6.2.11-300 (mainline Fedora 38 kernel right now)
3. CPU: Ryzen 9 5900X 12 core
4. RAM: 48 Gib
5. SSD: Samsung 980 Pro 2 Tib
6. Compiler: Clang 16 (from Fedora repo)
7. llvm-bolt, perf2bolt versions: from Fedora 38 repositories - 16.0.0
8. ClickHouse: master branch

As a training and evaluation setup, I've used ClickBench (as @alexey-milovidov suggested earlier). As a baseline ClickHosue version was chosen a version from the master branch built locally with Clang 16 with default flags (`cmake ../ClickHouse -G Ninja && ninja`) without ThinLTO.

At first, I tried to use instrumentation PGO with Clang. Unfortunately, with Instrumentation ClickHouse works toooooo slowly. E.g. the slowest query in the usual release build on my test machine takes ~9 seconds to finish but with instrumentation, it takes smth like 2700-2800 seconds to get a result. This problem affects almost all queries, not just a few. I've expected something like that anyway.

However, even with instrumentation, I didn't get fascinating results from an improvement perspective - even some regressions (however, not sure - was it regression or just some local fluctuations in the measurements). Maybe, instrumentation needs to be tested once again. Probably a bit later I will share the run results.

Then, I performed optimization with Google AutoFDO. The main caveat with AutoFDO and BOLT is that they rely on `perf` profiles with LBR information. My system does not support such PMU events so I use the usual `perf record -b` profiles. According to the documentation, non-LBR profiles could be used but provides fewer optimization opportunities. How much less? Who knows - I didn't find a good comparison between methods. So if you have a hardware/OS with LBR support - please re-evaluate AutoFDO and BOLT (especially since according to the papers from Google and Facebook/Meta these methods both consistently bring performance improvements even for the databases).

With AutoFDO in non-LBR I got quite strange results. For some tests, I see notable improvements. For another - some regressions are found.

Optimizing with BOLT in non-LBR mode didn't bring valuable results. Note, that BOLT was used with `-strict=0` option since it uses much less RAM but could be less efficient: [link](https://github.com/llvm/llvm-project/issues/61711#issuecomment-1484659082).

Instrumentation with BOLT via `llvm-bolt -instrument` failed since it consumes an insane amount of RAM: https://github.com/llvm/llvm-project/issues/62320

ClickBench results:

- Default release build - https://pastebin.com/nDwXKri2
- Default release build + AudoFDO - https://pastebin.com/ubKie42N
- Default release build + AutoFDO + BOLT - https://pastebin.com/YqpvuquF

Some thoughts about the current results.

At first, I expected much better results from PGO. Maybe, ClickHouse for queries is especially greatly tweaked so we cannot achieve a lot from the current implementation (because as we know - "ClickHouse не тормозит" :). Maybe I just did something wrong - please let me know :) Also, I think PGO still could shine on other loads that are not covered by ClickBench because according to the stats from BOLT optimization, only 0.4% of all functions in ClickHouse binary were covered with profiles. So maybe on more diverse loads, we could try to extract more performance with PGO.

Second, Instrumentation profiling kinda unusable (or at least is not usable for such kind of load). AutoFDO and BOLT need to be tested with LBR support (Intel hardware or the most recent AMD hardware with a 6.0+ Linux kernel, I don't know about ARM processors).

One more idea: please add a mode to Clickbench to measure throughput, not just timings per query (smth like it's done in YDB load tests).

**Comment by alexey-milovidov** [comment]
This is a really great analysis!

A few notes:

1. https://pastila.nl/ can be used instead of pastebin. You can copy-paste ClickBench's HTML there, add .html to the URL, and it will give an HTML report with the comparison.

2. There is a dedicated performance regression test suite, located at https://github.com/ClickHouse/ClickHouse/tree/master/tests/performance The results can be accessed in every pull request. They contain every metric about every query, including perf events, and even the analysis, what metrics correlate with the wall clock time. But it's dangerous to use this test suite for PGO, because these tests are isolated (as close to "unit" performance tests as possible).

**Comment by rschu1ze** [comment]
Interesting, thanks a lot for doing this work.

PGO is generally an interesting direction, maybe currently not mature enough (e.g. required LBR, BOLT added to LLVM only v14).

@zamazan4ik What would be quite helpful for future follow-up is if you could paste the steps / commands you used to do the analysis, thanks!

**Comment by zamazan4ik** [comment]
@alexey-milovidov Recently I did another round of CH benchmarks. The machine is the same as above (with the same Linux kernel, hardware, etc.).

I have compared two CH versions:
* Release build (with enabled LTO)
* Release build with PGO + Context Sensitive PGO (LTO + PGO + CSPGO). What is CSPGO you can read [here](https://clang.llvm.org/docs/UsersManual.html#cmdoption-fcs-profile-generate) (TL;DR - yet another PGO approach but collects profile info after the inlining phase)

For the tests I still use ClickBench but I run the test suite via `clickhouse-benchmark` ([link](https://clickhouse.com/docs/en/operations/utilities/clickhouse-benchmark)). It allows tracking QPS and percentiles per query (quite helpful information!).

The results are here: https://pastebin.com/xbue3HMU

There is an interesting observation I cannot explain right now due to a lack of internal details about ClickHouse: for more time-consuming queries, the benefits from PGO are smaller. Maybe, it's due to the higher impact of internal CH JIT on such queries (since PGO cannot help with JIT-generated code, obviously), perhaps it's due to something else - I didn't perform profiling yet.

Since I find these results are quite promising, I think would be helpful for the end-users to mention somewhere in the CH documentation about PGO and possible performance impacts explicitly. In which way - ofc is up to you.

**Comment by alexey-milovidov** [comment]
> There is an interesting observation I cannot explain right now due to a lack of internal details about ClickHouse: for more time-consuming queries, the benefits from PGO are smaller. Maybe, it's due to the higher impact of internal CH JIT on such queries (since PGO cannot help with JIT-generated code, obviously), perhaps it's due to something else - I didn't perform profiling yet.

I'd explain it like this:
ClickHouse code at runtime consists of two parts:
- tight inner loops - they most likely cannot be improved by PGO;
- "garbage" - in between the loops, typically represented by manipulations of std::vector, string, shared_ptr, passing arguments around, etc - can be improved by PGO;
Heavy queries have more proportion of the first part, and short queries - of the second part.

**Comment by alexey-milovidov** [comment]
I see that some queries are benefited a lot! Like

> SELECT COUNT(DISTINCT SearchPhrase) FROM hits;
 >50.000%         0.420 sec.
> 50.000%         0.385 sec.

Let's put the instructions in the docs as a minimum.

**Comment by zamazan4ik** [comment]
> I'd explain it like this:
> ClickHouse code at runtime consists of two parts:
> 
> tight inner loops - they most likely cannot be improved by PGO;
> "garbage" - in between the loops, typically represented by manipulations of std::vector, string, shared_ptr, passing arguments around, etc. - can be improved by PGO;
> Heavy queries have more proportion in the first part, and short queries - in the second part.

Yeah, thanks for the explanation! I had a similar guess too :)

> Let's put the instructions in the docs as a minimum.

Thanks a lot! Not an ad (I promise) but probably you could find some useful links and other showcases about PGO here: https://github.com/ZaMaZaN4iK/awesome-pgo Feel free to reference the repo, copy-paste whatever you want directly into the CH docs, etc. I hope at least some articles would be helpful.

Honestly, I guess we are able to extract even more performance with BOLT but I need proper hardware for it to test (with LBR/BRS support). Maybe someone else could do it or somewhen later I perform the tests again somewhere (on my newer local machine or somewhere in the cloud).

**Comment by alexey-milovidov** [comment]
As the first step, we will build our compiler with PGO: https://github.com/ClickHouse/ClickHouse/pull/97031
