### ISSUE TITLE
A question about Keeper's session mechanism

### ISSUE THREAD

**Issue by chloro-pn** [ClickHouse/ClickHouse#44571]
I noticed that Keeper does not support **session restore** at present：

https://github.com/ClickHouse/ClickHouse/blob/69d08b1007be68664c9cdb13b71f6659af1ffafd/src/Server/KeeperTCPHandler.cpp#L267

***

But the **watch mechanism** is based on the **session mechanism**：

https://github.com/ClickHouse/ClickHouse/blob/69d08b1007be68664c9cdb13b71f6659af1ffafd/src/Coordination/KeeperStorage.cpp#L2233

Does this mean that when the raft node crashes or the network partition causes the raft cluster to switch leaders, the client will lose the watch object when reconnecting the raft cluster, which does not seem to provide the same guarantee as the zookeeper.

**Comment by alexey-milovidov** [comment]
Yes. The client will be unable to re-establish the existing session and will have to re-install the watches.
This does not break any guarantees because if the client is working with ZooKeeper, it should also expect that session restore might not be possible.

**Comment by chloro-pn** [comment]
get it :  )
