### ISSUE TITLE
A database and table engine for DuckDB

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#44576]
DuckDB is an embeddable database engine, with data structures and query execution similar to ClickHouse.
It is growing in popularity very quickly*.

**Use case**

Attach DuckDB's database file as a database or a table in ClickHouse.

**Describe the solution you'd like**

Similarly to SQLite integration: https://clickhouse.com/docs/en/engines/table-engines/integrations/sqlite/

\* https://play.clickhouse.com/play?user=play#U0VMRUNUCiAgICAnaHR0cHM6Ly9naXRodWIuY29tLycgfHwgcmVwb19uYW1lLAogICAgY291bnQoKSBBUyBzdGFycwpGUk9NIGdpdGh1Yl9ldmVudHMKV0hFUkUgZXZlbnRfdHlwZSA9ICdXYXRjaEV2ZW50JyBBTkQgdG9ZZWFyKGNyZWF0ZWRfYXQpID0gMjAyMgpHUk9VUCBCWSByZXBvX25hbWUKT1JERVIgQlkgc3RhcnMgREVTQwpMSU1JVCAxMDAw

```
68. Supabase
75. SurrealDB
87. DragonflyDB
188. Meilisearch
246. Budibase
280. Tabler
283. MindsDB
311. Superset
327. Grafana
419. Minio
432. Prometheus
434. Zinc
441. Redis
446. Dbeaver
471. Polars
490. Milvus
493. Directus
504. ClickHouse        <------
552. Signoz
558. Neon
579. Netdata
580. Elasticsearch
624. Sonic
665. Airflow
713. Dataease
768. Metabase
774. Etcd
832. Airbyte
868. CockroachDB
890. Plausible/Analytics
908. DoltHub
983. Rqlite
998. DuckDB            <------
```

**Comment by alanpaulkwan** [comment]
As a user of both, I'd say this is a really cool idea! 

DuckDB seems to handle Parquet faster than Clickhouse at the moment, and I'm not sure, but possibly certain types of joins. I wonder if this will confer DuckDB's capabilities in those respects into Clickhouse, with sufficient psuhdown

**Comment by alexey-milovidov** [comment]
We have a suboptimal implementation of Parquet:
- it does an extra copy instead of direct processing because the "Apache Arrow" library is used;
- it does not use the embedded min-max index inside the Parquet file;

This task is not a way to improve Parquet parsing speed, but it can be a nice side-effect.

**Comment by alanpaulkwan** [comment]
Awesome. As a side note, improved Parquet processing speed would be awesome. Would love to be able to use Parquet for reasonable performance. If this is a way to do that, that's great too.

**Comment by alexey-milovidov** [comment]
Next steps:
- include some of its extensions (httpfs is the first);
- allow the syntax to pass query string to the external engine instead of implicit pushdown.

**Comment by alexey-milovidov** [comment]
Current status - embedding it into ClickHouse increases the build size too much if it is compiled with MSan.
Turning off MSan for DuckDB is not an option because we cannot "unpoison" the memory it has initialized.
We will figure out the details. We may have to disable the debug info for DuckDB to make it smaller.

**Comment by alexey-milovidov** [comment]
Current status: if you compile DuckDB with debug info, it takes 853 MB. It is too fat.
Maybe Hannes Mühleisen can help to make it.

**Comment by alexey-milovidov** [comment]
@ghalimi is a huge fan of duckdb; let's ask for his help.

**Comment by alexey-milovidov** [comment]
No help was provided.

**Comment by alexey-milovidov** [comment]
Update: we have found and fixed the problem with duckdb; now it has the chance.

**Comment by BTheunissen** [comment]
Hi @alexey-milovidov, this feature would actually be hugely helpful for a data pipeline I've been working on. I just finalized it by exporting Arrow tables from Clickhouse which I then load into DuckDB, but I feel like this external engine could be a massive simplification. I can see the PR has been stuck for various reasons for a bit but want to just say I am still an interested party!

**Comment by aadant** [comment]
Interestingly ClickHouse now outperforms DuckDB for most SQL queries on Parquet, probably on Arrow. Why not use clickhouse local or chDB instead ?

**Comment by alanpaulkwan** [comment]
I love both and am keen for this feature. DuckDB has way better performance, for now, on TPC-H and range joins. They also have certain functions not available in Clickhouse.

**Comment by alexey-milovidov** [comment]
I'm fully in favor of merging this feature, but it needs to be finished and merged first.

It is not so easy... DuckDB is positioned as an embedded engine, but it is, in fact, very large to embed (compared to SQLite, which we also embed), and the first attempt found memory-safety errors (our tests automatically fuzz everything they can to find bugs).

**Comment by alexey-milovidov** [comment]
It does not make sense for the following reasons:
- DuckDB is not memory-safe, and it will add vulnerabilities to the code;
- currently, DuckDB is slower than ClickHouse;
- DuckDB is not a small library, and adding hundreds of megabytes to the already large ClickHouse binary will be too much;
- DuckDB's internal format is unstable - it lacks backward compatibility and frequently changes.
