### ISSUE TITLE
Parallel replicas with custom sharding key.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#44585]
Add a setting `parallel_replicas_mode` taking one of the following values:
- `sample_key` - the default, represents the existing implementation from 2015;
- `read_tasks` - the in-progress implementation by @nikitamikhaylov where replicas request tasks from the initiator;
- `custom_key` - a new method proposed here - very similar to `sample_key`, but arbitrary integer expression is used as a key;

Add a setting `parallel_replicas_custom_key` to control the sharding expression.
The replicated table with this method will work as a distributed table.

If a query with heavy high-cardinality GROUP BY, IN, DISTINCT, or JOIN operator is used, the `custom_key` method, along with #44581 can be used to optimize the queries.

The setting `parallel_replicas_custom_key` will be meant to be used automatically, but we need to get the explicit implementation first.

**Comment by antonio2368** [comment]
What do in case the query contains multiple tables and we would like to apply the `custom_key`?
Maybe do something similar to the `additional_table_filters` and write `parallel_replicas_custom_key` as a Map?

**Comment by alexey-milovidov** [comment]
Yes, using Map is a good idea.
