### ISSUE TITLE
Error: Dimension of types mismatched between inserted value and column. Dimension of value: 2. Dimension of column: 1

### ISSUE THREAD

**Issue by seandavi** [ClickHouse/ClickHouse#44583]
> You have to provide the following information whenever possible.

Loading JSONAsObject fails for some JSONs with arrays of variable length. 

> A clear and concise description of what works not as it is supposed to.

> A link to reproducer in [https://fiddle.clickhouse.com/](https://fiddle.clickhouse.com/).

I couldn't get the code working in fiddle. Here is the code that reproduces the error and the error itself.

```
select * from url('https://gist.githubusercontent.com/seandavi/2ab336bac1e7145db3cdf8c0dc9fcd80/raw/816f24f53f327cf1c58234d325deff6806b4e81d/test_clickhouse_JSONAsObject.ndjson', 'JSONAsObject');
```

Result:

```
SELECT *
FROM url('https://gist.githubusercontent.com/seandavi/2ab336bac1e7145db3cdf8c0dc9fcd80/raw/816f24f53f327cf1c58234d325deff6806b4e81d/test_clickhouse_JSONAsObject.ndjson', 'JSONAsObject')

Query id: c33c1c41-e970-460c-9922-4c210802a475

↖ Progress: 0.00 rows, 0.00 B (0.00 rows/s., 0.00 B/s.)
0 rows in set. Elapsed: 0.631 sec.

Received exception from server (version 22.12.1):
Code: 645. DB::Exception: Received from localhost:9000. DB::Exception: Dimension of types mismatched between inserted value and column. Dimension of value: 2. Dimension of column: 1: While executing ParallelParsingBlockInputFormat: While executing URL. (NUMBER_OF_DIMENSIONS_MISMATCHED)
```

**How to reproduce**

* ClickHouse server version 22.12.1.1752 (official build).
* Clickhouse client interfact

**Comment by codeselim** [comment]
Same issue here on clickhouse-server:23.3.8.21-alpine

**Comment by codeselim** [comment]
Dear @alexey-milovidov can we please know the reason for this Wont-Fix? 
are you having other merge logic in the new versions?

**Comment by alexey-milovidov** [comment]
The feature "experimental object type" never made it to production, and we are going to remove it.

**Comment by codeselim** [comment]
Thank you for your fast reply @alexey-milovidov
