### ISSUE TITLE
The setting `prefer_localhost_replica` shouldn't prevent parallel replicas to work

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#44582]
Even if `prefer_localhost_replica` is enabled, it should be possible to connect to more (non-localhost) replicas if the setting `max_parallel_replicas` is greater than 1.

**Comment by nikitamikhaylov** [comment]
Parallel replicas do not respect `prefer_localhost_replica` setting anymore. Initiator will talk to even local replica using loopback.
