### ISSUE TITLE
Always remains something in zookeeper after deleted database

### ISSUE THREAD

**Issue by Alex-Cheng** [ClickHouse/ClickHouse#44589]
**Describe the unexpected behaviour**
When I create and then delete a database with `ON CLUSTER` clause, there is possibility that something remained in zookeeper. It causes unexpected behaviour. 

IMO, the distributed DDL is bug-prone for the reason. Databases/tables are removed but the zk node still exists. Another issue is that the table are created with `ON CLUSTER` but one replica does not have corresponding zk node in zookeeper. 

Cluster of Clickhouse is bug-prone. We are struggling with them now.

**Comment by Alex-Cheng** [comment]
when creating a ReplicatedMergeTree tables on cluster and got failure, it turns out that something remains in zookeeper or somewhere else. It won't do clean-up.

**Comment by Alex-Cheng** [comment]
![image](https://user-images.githubusercontent.com/1518453/209535952-81e18eae-7f70-4617-b769-e573d59cc3c2.png)

Some distrbuted DDL keep loop forever.

**Comment by den-crane** [comment]
Provide reproducible example, Clickhouse version, and config xml files, description of your setup.

**Comment by Alex-Cheng** [comment]
Version: 22.8
Config: [cluster_dev (2).zip](https://github.com/ClickHouse/ClickHouse/files/10305543/cluster_dev.2.zip)
Reproduction steps: 
Get SQL script from [test.zip](https://github.com/ClickHouse/ClickHouse/files/10305567/test.zip)
1. run the line 1~7 to create table and insert data, with two healthy cluster nodes are available.
2. shutdown `node02`, to simulate a fatal error. 
3. run the line 9~11, with only node01 as leader is available.

Randomly encounter some error described above.

**Comment by den-crane** [comment]
>Always remains something in zookeeper after deleted database

BTW do you aware that Atomic databases drop objects with the delay of 8 minutes ?
If you need immediate drop you can use `drop database/table .... sync` or reduce `<database_atomic_delay_before_drop_table_sec>1` https://kb.altinity.com/engines/altinity-kb-atomic-database-engine/

About the errors. I think it is related to `... settings mutations_sync=2;` try `mutations_sync=1`.
