### ISSUE TITLE
Table becomes 'READONLY' mode 

### ISSUE THREAD

**Issue by Alex-Cheng** [ClickHouse/ClickHouse#44597]
I got the below error and the table engine is ReplicatedMergeTree. 
```
2022.12.26 20:44:29.956024 [ 18427 ] {} <Error> db_cube_43192_19493.`$cases$formtable_main_1753_table1` (fde93948-d6a0-4b03-a8cc-db4d1f358c5e): void DB::StorageReplicatedMergeTree::mutationsFinalizingTask(): Code: 242. DB::Exception: Table is in readonly mode (replica path: /clickhouse/tables/01/fde93948-d6a0-4b03-a8cc-db4d1f358c5e/replicas/node02). (TABLE_IS_READ_ONLY), Stack trace (when copying this message, always include the lines below):
```

**Comment by den-crane** [comment]
This is normal behavior and happens when a network connection is lost.
The problem resolves automatically.

**Comment by Alex-Cheng** [comment]
Thank you for reply. But the issue was not gone when network connection resumed. I finally addressed the issue by the below two steps:
1. sudo -u clickhouse touch /var/lib/clickhouse/flags/force_restore_data
2. restart the server.

However I cannot address such an issue manually each time. I want to get an automatic approach.

**Comment by den-crane** [comment]
You need to share more logs. It's impossible to address because of lack of information. 
The error TABLE_IS_READ_ONLY is too general and has 3888 possible reasons.

**Comment by Alex-Cheng** [comment]
@den-crane I have attached the log file, some table names are changed for sensitive information and policy. But the log itself is integral. 
Thank you very much for your help.

[2022.12.26 20-25-51-readonly-tables.log](https://github.com/ClickHouse/ClickHouse/files/10312706/2022.12.26.20-25-51-readonly-tables.log)

**Comment by den-crane** [comment]
Check zookeeper logs for the same period of time. 

please share

```
select count() from system.parts where table = 'formtable_main_2277' and database = 'db_cube_42816_19153'
```

**Comment by Alex-Cheng** [comment]
:) select count() from system.parts where table = 'formtable_main_2277' and database = 'db_cube_42816_19153'

SELECT count()
FROM system.parts
WHERE (table = 'formtable_main_2277') AND (database = 'db_cube_42816_19153')

Query id: df585475-ee95-4446-be4f-f55246fd85cd

┌─count()─┐
│       1        │
└──────┘

**Comment by Alex-Cheng** [comment]
the keeper's log is not available. I forgot setting log path for keeper.xml, so that no log were recorded at that moment.
