### ISSUE TITLE
What is the best practice about Clickhouse load-balancing?

### ISSUE THREAD

**Issue by Alex-Cheng** [ClickHouse/ClickHouse#44624]
What is the proper solution for Clickhouse load-balancing? Someone suggests adopting CHProxy while some articles describe the solution of Nginx + CH. 

What is the best practice about Clickhouse load-balancing?

**Comment by alexey-milovidov** [comment]
The bullet-proof option for geographically distributed clusters is:
Client-side load balancing + round-robin DNS + BGP anycast + IPVS + ClickHouse server.

The minimal option is:
Client-side load balancing + ClickHouse server.

Nginx or HAProxy, or Envoy is not necessarily to use - they can be used if client-side load balancing is not possible.

**Comment by alexey-milovidov** [comment]
PS. Envoy works pretty well with ClickHouse.

**Comment by Alex-Cheng** [comment]
Thank you very much. How about CHProxy? I was suggested to use CHProxy in a group disucssion.

**Comment by Alex-Cheng** [comment]
I searched 'clickhouse envoy' and got https://tray.io/connectors/clickhouse-envoy-integrations. Is it what you mentioned about envoy? 
BTW, what is 'Client-side load balancing'? I didn't get any  information about it via google.

Thank you very much.

**Comment by alexey-milovidov** [comment]
Client-side load balancing is a logic in your application connecting to ClickHouse - it will be configured with more than one ClickHouse host and try to connect with a reasonable timeout and exponential backoff to each of them, with a few retries in a loop.

**Comment by alexey-milovidov** [comment]
> https://tray.io/connectors/clickhouse-envoy-integrations

Looks unrelated.

**Comment by alexey-milovidov** [comment]
CH Proxy can be ok, but I did not use it.

**Comment by Alex-Cheng** [comment]
> Client-side load balancing is a logic in your application connecting to ClickHouse - it will be configured with more than one ClickHouse host and try to connect with a reasonable timeout and exponential backoff to each of them, with a few retries in a loop.

It seems to be a middleware, and I feel I don't need to develop such a middleware ourselves. Is there any existing stable implementation? 

Thank you very much.
