### ISSUE TITLE
Is 'ON CLUSTER' clause necessary for 'ALTER TABLE DELETE|UPDATE|ADD|DROP' for ReplicatedMergeTree?

### ISSUE THREAD

**Issue by Alex-Cheng** [ClickHouse/ClickHouse#44621]
Saying I have a ReplicatedMergeTree `t1` created by the folllowing query:
```SQL
create table db1.events on cluster 'ch-pro-cluster' (ID Int64, x01 String, x02 String) ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/dd', '{replica}') order by ID partition by ID % 5  settings min_rows_for_wide_part=10, min_bytes_for_wide_part=1;
```

And the table's data has been initialized by query 

`insert into db1.events(ID, x01, x02) select number, leftPad(toString(number + 01), 8, '0'), toString(number + 02) from numbers(5000000)`.

Then I want to delete, update, add or drop table. I found omitting 'ON CLUSTER' the synchronization can be also done by mechanism of ReplicatedMergeTree.

For example, `alter table db1.events delete where ID % 10 = 3 settings mutations_sync=2;` can spread the changes over cluster. Of course, query `alter table db1.events on cluster 'ch-pro-cluster' delete where ID % 10 = 3 settings mutations_sync=2;` also work but the difference is that the later query will add a zk node in `/clickhouse/task_queue/ddl ` and the first query won't. 

What is the best practice? Shall I omit 'ON CLUSTER' for doing 'ALTER TABLE ...' on ReplicatedMergeTree tables?

**Comment by save-my-heart** [comment]
Only `ON CLUSTER` clause can spread the changes over cluster.
Without `ON CLUSTER`, ALTER queries only works on single node, or all replica nodes in a shard.

**Comment by Alex-Cheng** [comment]
My cluster is one shard, multiple replicas. So I think without 'ON CLUSTER', ALTER queries work well.

**Comment by den-crane** [comment]
ReplicatedMergeTree performs `ALTER TABLE DELETE|UPDATE|ADD column|DROP column` at all replicas by Replication mechanism, no need  'ON CLUSTER'.

to perform `create table / drop table` you need to use ON CLUSTER

**Comment by Alex-Cheng** [comment]
@den-crane  I highly appreciate your help. More question: if I have a multiple shards cluster and table engine is ReplicatedMergeTree, shall I use ON CLUSTER in ALTER TABLE?

**Comment by den-crane** [comment]
>More question: if I have a multiple shards cluster and table engine is ReplicatedMergeTree, shall I use ON CLUSTER in ALTER TABLE?

Yes, you shall.
