### ISSUE TITLE
Warn user if CREATE MATERIALIZED VIEW do not have any valid source table in select query

### ISSUE THREAD

**Issue by tema-popov** [ClickHouse/ClickHouse#44691]
**Use case**
Materialized views have strict limitations on what can be used in cases, where I ended up creating non-working materialized views without any way to know where is the problem without researching it myself:

1. Using view as a source table
2. Using distributed table instead of a local as a source table

I would love to have a way to know that I did something wrong from a DB itself. 

Also, would be great to add these cases of misuse in a [documentation](https://clickhouse.com/docs/en/sql-reference/statements/create/view/#materialized-view)

As I understand, it is not possible to return an error because materialized views could be created before source tables even exist. 

**Describe the solution you'd like**

I want to have a warning in the style "materialized view was created but we didn't find any valid source table in select query exist at the moment"

**Describe alternatives you've considered**

At least updating the documentation. as it is not clear what could be used as a source table (only local, physical table AFAIK)

**Additional context**

[Discussion thread in Slack](https://clickhousedb.slack.com/archives/CU478UEQZ/p1672253616620209)

**Comment by den-crane** [comment]
>Using distributed table instead of a local as a source table

It's a valid usecase. I use MatViews with FROM distributed table all time.


>As I understand, it is not possible to return an error because materialized views could be created before source tables even exist.

Really?

```
create materialized view test Engine=Memory as select * from xxxxxx;

DB::Exception: Table dw.xxxxxx doesn't exist. (UNKNOWN_TABLE)

```

**Comment by tema-popov** [comment]
> Really?

I didn't check it myself, it was based on a discussion thread response in [Slack](https://clickhousedb.slack.com/archives/CU478UEQZ/p1672253616620209)

> It's a valid use case. I use MatViews with FROM distributed table all time.
Hmm, interesting, I spent some time yesterday trying to figure out why my materialized views don't work over the distributed table and ended up thinking it works only if I create local materialized views over local tables. Maybe I should try to reproduce that on a simple example if it should work.

**Comment by den-crane** [comment]
https://den-crane.github.io/Everything_you_should_know_about_materialized_views_commented.pdf

https://youtu.be/1LVJ_WcLgF8?list=PLO3lfQbpDVI-hyw4MyqxEk3rDHw95SzxJ&t=7597

**Comment by tema-popov** [comment]
I think the reason why I could have distributed table not working is that in our configuration actual inserts are made on local tables instead of distributed ones. That would explain the difference in behavior, I assume the insert trigger would propagate to the local table from distributed if the insert was made on distributed but not the other way around. 

Thanks for helping understand that!
