### ISSUE TITLE
Can't ALTER DEFAULT expression for a key column

### ISSUE THREAD

**Issue by Kozloff** [ClickHouse/ClickHouse#4469]
Required:
- want modify default value of column
- MergeTree engine
- sorting key by any function of target column
- v19.1.6

**How to reproduce**

1. Create MergeTree table:

`CREATE TABLE test(s String)  ENGINE MergeTree() ORDER BY (cityHash64(s));`

2. After try to modify default value:

`ALTER TABLE test MODIFY COLUMN s DEFAULT 'test';`

3. And result:

`Code: 44, e.displayText() = DB::Exception: trying to ALTER key column s, e.what() = DB::Exception`

**Comment by kaushik141** [comment]
As a work around you can,
1. DETACH the table
2. Modify the table .sql file in metadata to reflect the modification on the column of your choice
3. ATTACH the table

**Comment by filimonov** [comment]
> Возможные проблемы: 
> 1) Мы можем сделать materialize index на колонку, которая сама еще не материализована
> И если поменять default, то индекс и колонка разбегутся
> 
> 2) вот это: https://github.com/ClickHouse/ClickHouse/issues/6913
> 
> Наверное правильно - запретить делать MATERIALIZE INDEX в частях где колонка отсутствует, а CLEAR COLUMN должен удалять индексы зависящие от колонки (хотя это же skipping index, и он готов к false positive).
>

**Comment by alexey-milovidov** [comment]
Fixed in master:

```
milovidov-desktop :) CREATE TABLE test_alter (x Date, s String) ENGINE = MergeTree ORDER BY s PARTITION BY x

CREATE TABLE test_alter
(
    `x` Date, 
    `s` String
)
ENGINE = MergeTree
PARTITION BY x
ORDER BY s

Ok.

0 rows in set. Elapsed: 0.002 sec. 

milovidov-desktop :) ALTER TABLE test_alter MODIFY COLUMN s DEFAULT 'Hello'

ALTER TABLE test_alter
    MODIFY COLUMN 
    `s` DEFAULT 'Hello'


Ok.

0 rows in set. Elapsed: 0.002 sec. 

milovidov-desktop :) ALTER TABLE test_alter MODIFY COLUMN x DEFAULT '2000-01-01'

ALTER TABLE test_alter
    MODIFY COLUMN 
    `x` DEFAULT '2000-01-01'


Ok.

0 rows in set. Elapsed: 0.001 sec.
```

**Comment by alexey-milovidov** [comment]
It will be released in version 20.4.

**Comment by alexey-milovidov** [comment]
Implemented in #10382 and #8361 #9606 #8439 #8456 #8701.
