### ISSUE TITLE
Support using vies as a source in CREATE MATERIALIZED VIEW

### ISSUE THREAD

**Issue by tema-popov** [ClickHouse/ClickHouse#44692]
**Use case**

I have a view `view` over a table `source_table` that enriches raw data with a bunch of aliases. 

I would like to create a materialized view and use `view` as the source, basically using it as an alias for a subquery I would like to use in materialized view SELECT. Right now, the materialized view on `view` is created but does not work when data is inserted in `source_table`. 

As a workaround, I just copy the view query and use it as a subquery in the materialized view and it works as expected. I think it could be done automatically by Clickhouse instead of me. 
 
**Additional context**

[discussion thread in Slack](https://clickhousedb.slack.com/archives/CU478UEQZ/p1672253616620209)

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/33919

**Comment by tema-popov** [comment]
Sorry, I don't understand why it is a duplicate of #33919. My case is about still using materialized view as an insert trigger on a view dependent on the source table. I don't understand the difference between using a view as a link to a subquery and an actual subquery in a materialized view SELECT section.

**Comment by den-crane** [comment]
It's too complicated and impossible in general. View can contain complex queries and it will be not obvious for users why it does not work.
