### ISSUE TITLE
Can't run tests with openssl 1.1.1a-1 installed

### ISSUE THREAD

**Issue by nvartolomei** [ClickHouse/ClickHouse#4470]
Building and running tests for 19.1.9/19.3.x/master branches fails with openssl=1.1.1a-1 installed.
```
2019.02.21 17:27:09.565441 [ 1 ] {} <Information> Application: starting up
Auto configuration failed
140088262211248:error:25FFF06C:DSO support routines:CRYPTO_internal:functionality not supported:/root/clickhouse/contrib/ssl/crypto/dso/dso_lib.c:224:
140088262211248:error:0EFFF06E:configuration file routines:CRYPTO_internal:error loading dso:/root/clickhouse/contrib/ssl/crypto/conf/conf_mod.c:273:module=ssl_conf, path=ssl_conf
140088262211248:error:0EFFF071:configuration file routines:CRYPTO_internal:unknown module name:/root/clickhouse/contrib/ssl/crypto/conf/conf_mod.c:214:module=ssl_conf
```

Both server and client fail with the same error.

Downgrading system openssl to `1.1.0j-1~deb9u1` fixed the problem.

```bash
cmake  -B/clickhouse-build -G Ninja -DPARALLEL_COMPILE_JOBS=4 -DPARALLEL_LINK_JOBS=8 -DENABLE_RDKAFKA=OFF -DENABLE_MYSQL=OFF -DENABLE_ODBC=OFF -DENABLE_HDFS=OFF -DENABLE_TESTS=1 /root/clickhouse
```

**Comment by tux3** [comment]
I landed on this issue from Google, I'm running into the same error in a different project.

I don't have a proper fix, but a workaround is to comment the `ssl_conf = ssl_sect` line you may have in your `/etc/ssl/openssl.cnf` under `[default_conf]` (note that this may actually change your system SSL config!)
I have no idea why exactly, but it seems that the new openssl version only accepts `oid_section` or `engines` keys under `[default_conf]`.

**Comment by den-crane** [comment]
The same problem with official 19.4.3.11 & debian 10 (buster)

cat /etc/debian_version
10.0

openssl             1.1.1b-2

**Comment by davtoro** [comment]
any news on this? Can't use clickhouse-server or client without openssl.conf workaround on Debian 10 Buster default installation.

**Comment by PhantomPhreak** [comment]
Same problem with CH v19.15.3.6, openssl 1.1.1c-1, debian buster 10.0

**Comment by rtbsolutions** [comment]
same here
launched via docker image as a temporary solution

**Comment by smakhtin** [comment]
Same here - Debian 10

**Comment by alexey-milovidov** [comment]
Need to check on version 20.1 prestable.

**Comment by dstruck** [comment]
Tested with version 20.3.4.10 on Debian Buster. Fix was not needed.

**Comment by fancyqlx** [comment]
hi, how do we fix this problem in new clickhouse version? we have the sample problem when deploy clickhouse on debian10, but its hard for us to upgrade clickhouse. Is there any way to fix instead?
