### ISSUE TITLE
INSERT INTO SELECT FROM query did not return response to HTTP.

### ISSUE THREAD

**Issue by wilsonwang213** [ClickHouse/ClickHouse#44729]
I am using "INSERT INTO xxx SELECT FROM remote()" query to insert some data.

With clickhouse-client (port 9000), it will be completed in 10mins, total row count is 23M records.

With http interface (port 8123), I am using Postman, the query did not return any response and hangs forever.  After setting:
receive_timeout=10000 
send_timeout=10000
http_send_timeout=10000
http_receive_timeout=10000
max_execution_time=10000
connect_timeout=10000

Still got the same result.

For shorter query which can be completed within 2 mins, the query can return 200 response.

**Comment by den-crane** [comment]
These settings 

```
receive_timeout=10000
send_timeout=10000
http_send_timeout=10000
http_receive_timeout=10000
max_execution_time=10000
connect_timeout=10000
``` 

are irrelevant in this case.

You need to configure postman https://learning.postman.com/docs/getting-started/settings/
