### ISSUE TITLE
Possible http requests queue

### ISSUE THREAD

**Issue by levandy** [ClickHouse/ClickHouse#44753]
Hello!

I have some health metrics in service working with CH cluster (8 nodes) including `'select 1'` execution time as metric. This select works via `jdbc-clickhouse-driver` and `java.sql.PreparedStatement`. It's invoked every minute for each node. Critical situation arises when query execution time more than 5 seconds.

Sometimes there are many simultaneous executing heavy (many inner joins with big right table; lots of data) queries on node (300-500) which can take a long time (20 seconds - 2-3 minutes). As I could see in `system.query_log`, `'select 1'` queries had max execution time ~200-300ms which is much less than 5 seconds (when the alert appeared). Also, there is `max_concurrent_queries=500` setting in server config.

So the questions are:
1. Is there any http requests queue (pool) on server, where I can loose ~5 seconds of execution time of `PreparedStatement` with `'select 1'`?
2. If so, can I adjust this queue or pool size?
3. Can I set priority for this `'select 1'` query? I know about `priority` setting, but it seems useless and unpredictable.
4. Is there any other way to check query execution time on CH cluster separately from users queries?

**Comment by den-crane** [comment]
1. There is `connection_pool_max_wait_ms` but it is disabled by default.
```sql
select * from system.settings where name = 'connection_pool_max_wait_ms';
┌─name────────────────────────┬─value─┬─changed─┬─description─────────────────────────────────────┬─min──┬─max──┬─readonly─┬─type─────────┐
│ connection_pool_max_wait_ms │ 0     │       0 │ The wait time when the connection pool is full. │ ᴺᵁᴸᴸ │ ᴺᵁᴸᴸ │        0 │ Milliseconds │
└─────────────────────────────┴───────┴─────────┴─────────────────────────────────────────────────┴──────┴──────┴──────────┴──────────────┘

There is no introspection for connection_pool.

2. No you cannot.

3. No, probably not. You need resource pools and they are not implemented yet.

4. No.

You can check `ProfileEvents` column in `system.processes` or `system.query_log` for these long `select 1` queries. It may give a clue. Also you can check /var/log/clickhouse-server/clickhouse-server.log for a trace information for these queries.
