### ISSUE TITLE
Roadmap 2023

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#44767]
This is ClickHouse roadmap 2023.
Descriptions and links are to be filled.

This roadmap does not cover the tasks related to infrastructure, orchestration, documentation, marketing, external integrations, drivers, etc.

See also:

Roadmap 2022: #32513
Roadmap 2021: #17623
Roadmap 2020: [link](https://github.com/ClickHouse/ClickHouse/blob/be29057de1835f6f4a17e03a422b45b81efe6833/docs/ru/whats-new/extended-roadmap.md)

## Testing and hardening

Fuzzer of data formats.
Fuzzer of network protocols.
✔️ Fuzzer of MergeTree settings.
Server-side AST query fuzzer.
Generic fuzzer for query text.
Randomization of DETACH/ATTACH in tests.
✔️ Integrate with SQLogicTest.
✔️ GWP-ASan integration.
✔️ Fully-static ClickHouse builds.
Embedded documentation.
Green CI: https://aretestsgreenyet.com/

## Query analysis and optimization

Enable Analyzer by default.
Remove old predicate pushdown mechanics.
✔️ Support for all types of CASE operators with values.
Transforming anti-join: LEFT JOIN ... WHERE ... IS NULL to NOT IN.
Deriving index condition from the right-hand side of INNER JOIN.
JOINs reordering and extended pushdown.
Correlated subqueries (with decorrelation).
Parallel in-order GROUP BY.
GROUP BY optimizations based on query rewrite.
Use table sorting for DISTINCT optimization.
Use table sorting for merge JOIN.
Alias columns in views.
Recursive CTE.

## Separation of storage and compute :cloud: 

✔️ Increased prefetching for VFS.
✔️ Lazy initialization of tables and data parts.
✔️ Cooperation of temporary data for query processing with VFS cache.
✔️ Multiplexed data parts format for lowering the number of writes :cloud:
Parallel replicas with task callbacks (production readiness).
✔️ Parallel replicas with custom sharding key.
✔️ SharedMergeTree - a table engine with a shared set of data parts. :cloud:
✔️ Shared metadata storage - no local metadata on replicas. :cloud:
Optimization of high-cardinality operations with the help of parallel replicas.
Query offloading to dynamic stateless workers.
Instant attaching tables from backups.

## Security and access control

Untangle auth methods for S3.
✔️ Managing named collections with SQL.
Secure storage for named collections. :cloud: 
Dynamic managing of custom query handlers.
✔️ Default password hashing schema.
✔️ Bcrypt or other PBKDF.
Resource scheduler.
TLS for the PostgreSQL compatibility protocol.
Data masking in row-level security.
JWT support. :cloud: 

## Formats and integrations

✔️ Headers autodetect for -WithNames formats.
✔️ Support s3-style URLs along with gs and others.
✔️ Support for Apache Iceberg.
✔️ Optimization of reading for Parquet.
✔️ Overlay databases and File database engine.
✔️ Streaming consumption from a bunch of files.
✔️ Support for embedded indices inside Parquet.
Schema inference for table function `mongodb`.
Table function `zookeeper`.
Simple HTTP PUT or form file API for data insertion.
Asynchronous inserts by default.

## Data storage

✔️ Lightweight deletes - production readiness.
Transactions for ReplicatedMergeTree
✔️ Indexing with space-filling curves.
Uniform treatment of LowCardinality, Sparse, and Const columns.
Grouping a huge number of columns together.
✔️ Deprecate in-memory data parts or make them production ready.

## Experimental features and research

✔️ Query results cache.
✔️ Regexp-Tree dictionaries.
✔️ Batch jobs and refreshable materialized views.
Streaming queries.
Freeform text format.
Semistructured data support - production readiness.
Websocket protocol for ClickHouse.
ssh protocol for ClickHouse.
Key-value data marts.
Unique Key Constraint.
✔️ PRQL as a dialect.
✔️ Kusto support.

**Comment by nolar** [comment]
Hi. Thanks for this topic where I can share my thoughts. We use ClickHoue to store some basic, not very complicated data (but in big volume). What we have found lacking is the ecosystem of ClickHouse, not ClickHouse's features.

Specifically, it means Python ecosystem: both the low-level driver and common frameworks integrations. As an example, `clickhouse-sqlalchemy` connector does not work properly with SQLAlchemy 1.4+, there is an issue (or several issues), but the maintainer probably cannot dedicate much time to the project (as an author of another (unrelated) project, I totally understand this). And none of us is a sufficiently good SQLAlchemy expert to understand the depth of its integration. And we had numerous issues with integration earlier (mostly resolved or worked around).

I might assume other languages and frameworks have the same problems.

I don't know what is a good solution here. Maybe to support those maintainers somehow. Or hire contractors to fix the issues.

But either way, in my belief, the ecosystem **around** ClickHouse is important enough for ClickHouse's wider adoption — maybe even more important than narrow use cases for performance **inside** ClickHouse.  Sadly, I see no line about this in the roadmap. It would be good to have one.

**Comment by nolar** [comment]
PS: Another feature request, though but maybe overly specific (which does not mean easy) — but it came to my mind after seeing _"Fully-static ClickHouse builds"_: 

Is it possible to reduce the size of `clickhouse-client` dramatically (100-fold)? I once tried to add it to an Ubuntu image, and it added 800 MB — quite a lot for Docker images for a supplementary tool used for debugging.

The idea is to have this client (so as psql for Postgres) installed in the runtime containers, where it is called not directly but through a wrapper command which feeds it the proper credentials from the container's secrets (app- & env-specific). E.g. `/app/manage postgres shell`, `/app/manage clickhouse shell`.

**Comment by Slach** [comment]
@nolar ;) try https://github.com/ClickHouse/clickhouse-connect/ instead of clickhouse-sqlalchemy

**Comment by azat** [comment]
>Is it possible to reduce the size of clickhouse-client dramatically (100-fold)? I once tried to add it to an Ubuntu image, and it added 800 MB — quite a lot for Docker images for a supplementary tool used for debugging.

@nolar about binary size:

debug symbols takes most of the space, official packages has them in a separate package, so, if you will add only `clickhouse-client` package from the official repository, then you will have `clickhouse` binary that takes 421M.

But it is not possible to strip it even further, at least now, since ClickHouse uses one binary for everything, this approach has advantages, like client can parse query and fail it if the syntax is wrong without sending it to the server, there is also `clickhouse-local` which is like a client+server in a standalone binary.

However, clickhouse support mysql (default port `9004`)/postgresql protocols (and http as well), and you can actually use those clients instead to send queries to clickhouse, though I wouldn't recommend this, since those clients are not that feature reach as ClickHouse's client.

**Comment by andrea-s** [comment]
Is there any work planned on improving the state of window functions? At the moment they are technically working but very slow for a number of realistic use cases (see e.g. https://github.com/ClickHouse/ClickHouse/issues/40781).

**Comment by alanpaulkwan** [comment]
Love the proposed Parquet speed improvements, join improvements. Join improvements and data-duplication are my biggest paint points.

For some reason, full sorting merge seems to blow up in memory usage even if the right table is small - I imagine this is related to the use of table indices but I wonder there is a need to make it use disk? So I wonder if that can be part of the merge join fixes. Also for some reason various of the join algorithms seem to have misleading query progress (stuck at 99% for ten minutes when 0 to 99 was 30seconds). Also true with grace hash.

Also, any chance of this? https://github.com/ClickHouse/ClickHouse/issues/18536

It's the other thing I spend time maintaining, finding terribly compressed columns and optimizing them.

**Comment by alexey-milovidov** [comment]
@andrea-s This particular case https://github.com/ClickHouse/ClickHouse/issues/40781 is interesting - it looks easy, but actually, it can be challenging to implement. We have to discuss the possible approaches to this task - we did not brain-storm it yet.

There are many other optimizations for window functions that we have to implement - for example, the re-use of the ordering of the data stream to optimize ORDER BY / PARTITION BY inside the window function.

**Comment by ucasfl** [comment]
@alexey-milovidov I'm working on `Unique Key Constraint` currentlly, and have proposed the initial pull request: https://github.com/ClickHouse/ClickHouse/pull/44534. Could you or someone else help with review it? This feature is useful in many scenarios, I'd like to continue until finish it.

**Comment by alexey-milovidov** [comment]
@alanpaulkwan 

> For some reason, full sorting merge seems to blow up in memory usage even if the right table is small - I imagine this is related to the use of table indices but I wonder there is a need to make it use disk? So I wonder if that can be part of the merge join fixes. Also for some reason various of the join algorithms seem to have misleading query progress (stuck at 99% for ten minutes when 0 to 99 was 30seconds). Also true with grace hash.

Currently, we have only a nascent low-level implementation of a few JOIN algorithms in external memory:

1. Many algorithms are implemented (`hash`, `parallel_hash`, `partial_merge`, `full_sorting_merge`, `grace_hash`), but there is no good default choice or automatic choice between them. Even `parallel_hash`, while being faster than the `hash` in most cases, is not enabled by default.
2. Merge JOIN algorithms don't take advantage of the table's / data stream sorting.
3. While some algorithms can spill data to disk, the control of the memory usage before spilling is non-obvious.

I see it as a halfway implementation: the fundamental parts are there, but only experts can use them by manually tuning the settings. I have big expectations to improve it in 2023.

**Comment by alexey-milovidov** [comment]
> Also for some reason various of the join algorithms seem to have misleading query progress (stuck at 99% for ten minutes when 0 to 99 was 30seconds). Also true with grace hash.

Query progress is very simple - it is the number of rows already read from the tables divided by the number of expected rows to read. I think we will keep the progress simple, as it is. But there is going to be one improvement: https://github.com/ClickHouse/ClickHouse/issues/39694

**Comment by alexey-milovidov** [comment]
> Also, any chance of this? https://github.com/ClickHouse/ClickHouse/issues/18536

It's not in the plans. Can be good for a contribution. But there are some considerations about this task, I will write them there.

**Comment by alexey-milovidov** [comment]
@ucasfl This PR will be reviewed. Today the majority of the team is on vacation, so maybe next week :)

**Comment by alexey-milovidov** [comment]
> Do you think Clickhouse will close the gap on TPC-H type workloads?

Yes! But not "close", maybe "approach" :)
We have benchmarks with TPC-DS, TPC-H, and Start Schema Benchmark, and for many queries, the results can be improved with low-hanging fruits.

**Comment by lgbo-ustc** [comment]
> Support for embedded indices inside Parquet.

Is it the same issue as #44484 ?

**Comment by mo-avatar** [comment]
Is it possible to shuffle data within the cluster to accelerate join in clickhouse, which means spread data  with the same hash value to certain shard? Other big data component such as spark seem to have feature like this?

**Comment by stergiotis** [comment]
ClickHouse has a nice set of functions for working with arrays already. I would see great value in expanding its capabilites in the following directions:
* Supporting sorted arrays (e.g. with functions like `arrayIntersectSorted(...)`, `hasSorted(arr,val)`, `indexOfSorted(arr,val)`, ...)
* Introducing sorted arrays in the type system
* Use Eytzinger layout to accelerate search in arrays
* Use binary search on sorted arrays
* Introduce a `indicesOf(arr,val)` function similiar to the `indexOf(arr,val)` function
* Make co-arrays invariants first class (e.g. `arrayCoSort(func,arr1,arr2,...)`)

Further it would be nice to have ClickHouse query parser and analyzer exposed by SQL e.g. for pretty-printing, parsing or canonicalizing queries. This could be implemented by extending `EXPLAIN AST`.

**Comment by MaxWk** [comment]
Is there any document about the `Separation of storage and compute ` version?

**Comment by ucasfl** [comment]
> Is there any document about the `Separation of storage and compute ` version?

Looks like currently it's developing in private.

**Comment by Pipboyguy** [comment]
What's happening to catboost integration? Is it still being supported or actively developed?

**Comment by zhanglistar** [comment]
Still no shuffle support?

**Comment by lgbo-ustc** [comment]
https://github.com/ByConity/ByConity/blob/master/src/QueryPlan/RemoteExchangeSourceStep.h

This looks like a shuffle implementation

**Comment by rhuddleston** [comment]
Azure blob store support? https://github.com/ClickHouse/ClickHouse/issues/19307

**Comment by AlekseiSaff** [comment]
object JSON ready for production in 2023?

**Comment by jackieli-tes** [comment]
I vote recursive CTE

**Comment by rupurt** [comment]
For Iceberg it would be useful to include support for Puffin files https://iceberg.apache.org/puffin-spec/. That would compete with `Support for embedded indices inside Parquet.`.

This is a good overview of the `why?` https://www.dremio.com/subsurface/puffins-and-icebergs-additional-stats-for-apache-iceberg-tables/

Another great addition to Iceberg would be support for branch/merge/tag semantics along with support for [nessie](https://projectnessie.org/)

**Comment by mga-chka** [comment]
> 1. Many algorithms are implemented (`hash`, `parallel_hash`, `partial_merge`, `full_sorting_merge`, `grace_hash`), but there is no good default choice or automatic choice between them. Even `parallel_hash`, while being faster than the `hash` in most cases, is not enabled by default.
Hi,
Can you give the reason why parallel_hash is not the default join algorithm? Because from afar, it seems much faster than hash (for large dataset) while having a memory overhead ok enough (from the discussion I saw on the PR).

nb: I haven't played with it yet but I was planning to test it and maybe use it in our production clusters to speed up some edge cases.

**Comment by bputt-e** [comment]
Would love it if unique key constraints got added this year

**Comment by franchb** [comment]
BigQuery table engine would allow Clickhouse users to leverage the wider BigQuery ecosystem https://github.com/ClickHouse/ClickHouse/issues/25173

BigQuery table engine will help to integrate with Malloy - an open source language that offers a new way to compose with data, to expose the intelligence you need, all with a single query.

https://www.malloydata.dev/home

**Comment by xbodx** [comment]
Faiss for efficient similarity search and clustering of dense vectors [pull/37011](https://github.com/ClickHouse/ClickHouse/pull/37011)

**Comment by chhetripradeep** [comment]
I would personally like to see ClickHouse having extensions support something similar to PostgreSQL extensions.

**Comment by alanpaulkwan** [comment]
If Parquet improvements are on the table, can Clickhouse update the writer to support alternative codecs (ZSTD, in particular).

**Comment by olafbuitelaar** [comment]
it would be great if the table [file](https://clickhouse.com/docs/en/sql-reference/table-functions/file/) function had a 4th argument, which controls if it would result in an empty result set (if none of the path's exist) instead of an error (Cannot stat file), in case none of the files in the path/glob exists.

**Comment by bputt-e** [comment]
Add support for json object for distributed tables

https://github.com/ClickHouse/ClickHouse/issues/37584

**Comment by bputt-e** [comment]
Improve clickkeeper so that it's stable in a kubernetes environment

**Comment by ahmed-adly-khalil** [comment]
is it too much to ask for JWT auth for the REST api?

**Comment by UnamedRus** [comment]
@ahmed-adly-khalil 
Issue https://github.com/ClickHouse/ClickHouse/issues/17270

**Comment by ccat3z** [comment]
Hi, is there any plan or description for shared metadata storage? Does shared metadata mean table metadata (mentioned in the https://github.com/ClickHouse/ClickHouse/issues/46813), or general metadata (e.g. db ddl txts in the `metadata/`)?

**Comment by zjial** [comment]
> Hi, is there any plan or description for shared metadata storage? Does shared metadata mean table metadata (mentioned in the #46813), or general metadata (e.g. db ddl txts in the `metadata/`)?

Hi @alexey-milovidov , we have implemented a unified metadata storage solution, and we would like to discuss with community the specific needs of this feature, so that if everyone's needs are relatively consistent, we can directly contribute our implementation to the community.

**Comment by zjial** [comment]
Hi @UnamedRus , I am with you on that, it seems that there is no issue about metadata storage yet, we can do this if community has not yet finalized the design.

**Comment by rvasin** [comment]
> Named collections contain hostname, user, and password for remote systems. I think it suggests to hide sensitive information.

Are there already any issues/discussions about securing the named collections? Because I identified very similar problem in interserver_http_credentials. See the [issue](interserver_http_credentials).

**Comment by zjial** [comment]
@UnamedRus @alexey-milovidov Hi, this is the issue of the proposed solution for Shared metadata storage, we can discuss it in this [issue](https://github.com/ClickHouse/ClickHouse/issues/48620).

**Comment by Nonegrace** [comment]
Hi, we are using JSON type column and facing the mutation bug now. Here are some related issues #37730 #38517 #40990.
Is there any plan for this issue?

**Comment by bkuspayev** [comment]
Waiting for kinesis connector in aws clickhouse cloud

**Comment by aadant** [comment]
Do you plan to support lightweight updates ? It looks like it was in https://github.com/ClickHouse/ClickHouse/issues/32513 but fell into the cracks :-)

**Comment by lqhl** [comment]
Saw the blog [ClickHouse Cloud boosts performance with SharedMergeTree and Lightweight Updates](https://clickhouse.com/blog/clickhouse-cloud-boosts-performance-with-sharedmergetree-and-lightweight-updates). Will `SharedMergeTree` be open sourced?

**Comment by alexey-milovidov** [comment]
@lqhl, Currently, no - it's one of a few cloud-only modifications.

**Comment by devoxi** [comment]
@alexey-milovidov, will the the zero-replication feature be deprecated as a consequence? Or will you keep investing on it and stabilise it?

**Comment by alexey-milovidov** [comment]
Zero-copy replication is clunky but mostly ok for now. We have fixed a ton of bugs in it.

**Comment by cangyin** [comment]
> @lqhl, Currently, no - it's one of a few cloud-only modifications.

Is there a cloud version binary package that I can download and take a trial?

**Comment by alexey-milovidov** [comment]
@cangyin No, the cloud version is not redistributed.

**Comment by hkrutzer** [comment]
>Currently, no - it's one of a few cloud-only modifications.

@alexey-milovidov will the corporation publish or has it already published what its stance is on cloud-only features? I don't think there is a technical reason for having this feature be cloud only. I understand the corporation needs to make money, that is fine. But without clear expectations of which features will be and will remain in the open source version, community trust can start to erode. For example, now that some features are cloud only, one might start to wonder what if  Clickhouse Inc. finds its cloud offering is not taking off sufficiently, and starts to remove features from the open source version, or starts including important new features only to its cloud version.

**Comment by alexey-milovidov** [comment]
It's good to have a small, limited number of modifications exclusive to ClickHouse Cloud, but only those that do not compromise the features or operation in self-managed usages, but in the same way, are crucial and distinguishing for the Cloud.

SharedMergeTree is a perfect choice - it gives advantages for ClickHouse Cloud with dynamic scaling; it could give an advantage to other cloud providers and, maybe, for large companies with many clusters and multi-tenant setups. It does not prevent using ClickHouse in distributed setups, with large and small clusters, local or shared storage, multi-region setups, etc. We keep in mind that we still need to provide improvements for self-managed operation, such as - support for re-sharding and easy setup on clusters.

**Comment by misaka-will** [comment]
@alexey-milovidov 
Will ClickHouse Inc merge in master branch community driven attempts to implement features like shared metadata storage? (https://github.com/ClickHouse/ClickHouse/issues/48620 for example)

**Comment by alexey-milovidov** [comment]
@misaka-will, This is a large feature, and it would take a lot of resources to implement and validate. It makes sense to send a pull request - to run CI checks and allow review and discussion with other community members.

There were cases when we received multiple competing implementations for a single feature and used parts of both to merge. We merge the vast majority of pull requests, but many others are closed due to conflicts in architecture or difficulties in support.

An alternative shared metadata might intersect and conflict with the private implementation, so it is at risk. But also there is a chance it can be merged and used for a broader area.

**Comment by alex-zaitsev** [comment]
@alexey-milovidov , the Roadmap in this current form looks confusing. It mixes features for open source and closed source version. What do you think about splitting the Roadmap to an open source version, and the separate one for the closed source / cloud one. That would make it more transparent for the users and community.

**Comment by rvasin** [comment]
It's nice to hear what is the closed source version? I think the closed source is everything related to ClickHouse Cloud, for example the cloud's backend and frontend scripts. ClickHouse, Inc. already sells the cloud subscriptions. Or @ mga-chka do you mean the selling the cloud closed source scripts to run own private cloud?

**Comment by mga-chka** [comment]
I mean selling the binary of clickhouse (and the related scripts + the documentation) that contains non-open source features (like the SharedMergeTree) so that external companies can use these features.

Because for larger companies like mine (contentsquare), the amount of data becomes too big and having an object-storage based database becomes a necessity. But, with the current move of clickhouse.inc, I'm not sure if we can rely on the open source object-storage related features since their support are unclear (like the zero-replication feature we wanted to use, cf a few msg before)

**Comment by hkrutzer** [comment]
>did you consider changing the license

To do that they would first have to get permission from all open source contributors that have not signed a CLA, or get rid of their code.

**Comment by athanhat** [comment]
### ClickHouse as an alternative storage engine for CozoDB

Hi, my main interest is the integration and analysis of very large databases, knowledge bases, graph databases with extremely complex schema. I have used ClickHouse in the past and I am aware about its superb performance. 

My problem for the case I described is that SQL with joins cannot cope with the complexity of schemas and graph data models. Nevertheless with ClickHouse merge tree table you can store triplets, or in fact any n-ary relation efficiently.

On the other hand I have been experimenting for some time with Datalog systems that utilize a backend for storage, quite often this is a KV store. A declarative logic programming language like datalog seems an excellent approach here but these systems really suffer in reading and writing on disk.

My question is whether a system like Clickhouse can be used as a backend with a datalog based system that supports relational database operations. Recently I have been exploring CozoDB and I have opened an issue, cozodb/cozo#175,  here.

I will be very interested in reading your views on that topic.

**Comment by javisantana** [comment]
> An alternative shared metadata might intersect and conflict with the private implementation, so it is at risk.

I think is totally fine you keep part of the code but it'd be great to be clear with the people contributing to the core (*) about the technical restrictions and the policy. It's clear the S3 and zero-copy design requires some iterations and, eventually, someone in the community was going to work on that regardless of your work in SharedMergeTree.

It does not make any sense to work for weeks on an alternative that may change something that you are not accepting. An alternative would be to be more open to talking to the community so we could discuss these kinds of things.


(*) writing as someone who is paying people full-time to contribute

**Comment by alexey-milovidov** [comment]
@javisantana, This also worries me - a production-quality implementation of an alternative to SharedMergeTree will require not weeks but over a year for multiple engineers and the resources to test it on many various workloads. A realistic way will be to split it into multiple small steps so every step can be tested in isolation and has some incremental value on its own.

**Comment by mcarbonneaux** [comment]
automatic shard rebalancing when add shard to a cluster (background rebalancing) ?

**Comment by cangyin** [comment]
What's the status of development on inverted index. Can we expect a time line for it to be production ready or is there a task schedule?

Specifically, I think these two optimizations are most outstanding: 
- inverted index pushed down to return result row id list directly, avoiding further data scan, as mentioned [here](https://github.com/ClickHouse/ClickHouse/pull/38667#discussion_r940849523). Current implementation can cause high IO load during index file reading and make inverted index slower than simple full scan.
- possible refactor of parts merging logic to reduce memory usage during merges, as mentioned [here](https://github.com/ClickHouse/ClickHouse/issues/47875#issuecomment-1479494381)

**Comment by alexey-milovidov** [comment]
Inverted indices have a lower priority than other things, and currently, it is not in progress.

**Comment by olly-writes-code** [comment]
Adding a request for more GIS features. One important one is the ability to transform a geometry to a specified SRID. Redshift docs [here](https://docs.aws.amazon.com/redshift/latest/dg/ST_Transform-function.html)

**Comment by alexey-milovidov** [comment]
@fantom0005, there are several remaining issues with the Replicated database engine:

1. It always waits for all replicas, even if some of them are unavailable. It gives a false impression of downtime when it's ok to wait only for available replicas.
2. It does not support CREATE ... AS SELECT.
3. DDL operations are run sequentially, and in the presence of many operations, the queue can grow too large.

We want to finish its implementation.

**Comment by alexey-milovidov** [comment]
2024: https://github.com/ClickHouse/ClickHouse/issues/58392
