### ISSUE TITLE
need docs for insert_keeper_max_retries

### ISSUE THREAD

**Issue by DanRoscigno** [ClickHouse/ClickHouse#44770]
(you don't have to strictly follow this form)

**Describe the issue**
A clear and concise description of what's wrong in documentation.

**Additional context**

**Comment by DanRoscigno** [comment]
@devcrafter can you help me with documenting this setting?  When should it be used, how can the user determine a good starting value, and how can they tell if the setting is working well?

Thanks!

**Comment by rfraposa** [comment]
I took a stab at it here: https://github.com/ClickHouse/ClickHouse/pull/45627
