### ISSUE TITLE
need docs for inferring dates

### ISSUE THREAD

**Issue by DanRoscigno** [ClickHouse/ClickHouse#44780]
https://github.com/ClickHouse/ClickHouse/pull/39186

Probably already in the new schema inference docs

**Comment by Avogar** [comment]
It is: https://github.com/ClickHouse/ClickHouse/blob/master/docs/en/interfaces/schema-inference.md#input_format_try_infer_dates

**Comment by DanRoscigno** [comment]
Thanks, I knew I read it. I was going through a long list of missing docs from a couple weeks ago.  Thanks for confirming!
