### ISSUE TITLE
need docs for partition by 

### ISSUE THREAD

**Issue by DanRoscigno** [ClickHouse/ClickHouse#44796]
https://github.com/ClickHouse/ClickHouse/pull/30690

**Comment by DanRoscigno** [comment]
@kssenii should HDFS, FILE, and URL table function docs all have this text (copied from Metgtree):

### PARTITION BY

`PARTITION BY` — The [partitioning key](/docs/en/engines/table-engines/mergetree-family/custom-partitioning-key.md). Optional. In most cases you don't need partition key, and in most other cases you don't need partition key more granular than by months. Partitioning does not speed up queries (in contrast to the ORDER BY expression). You should never use too granular partitioning. Don't partition your data by client identifiers or names (instead make client identifier or name the first column in the ORDER BY expression).

**Comment by kssenii** [comment]
Hi, also `S3` engine must be in this list.

Please also check this issue https://github.com/ClickHouse/ClickHouse/issues/15171.

These engines are different from canonical engines where PARTITION BY can be added.
So worth to add an example how it can later be read. E.g. I mean if you try to read from a partitioned s3 table you will get an exception - which is not obvious and should be mentioned in docs. So you can have a partitioned table engine but can only write with it. Partitioned writes can be done with table function as well. Reading partitioned data can be done only with table functions or table engines without partition by. Also it is useful to read this data with wildcards.
