### ISSUE TITLE
need docs for text classification

### ISSUE THREAD

**Issue by DanRoscigno** [ClickHouse/ClickHouse#44790]
https://github.com/ClickHouse/ClickHouse/pull/33314

**Comment by rfraposa** [comment]
The functions are:

- [ ] detectCharset
- [ ] detectLanguageUnknown
- [ ] detectLanguageMixed
- [ ] detectLanguage
- [ ] detectProgrammingLanguage
- [ ] detectTonality

**Comment by rfraposa** [comment]
Rumor has it `detectProgrammingLanguage` is on its way out, and `detectTonality` only works for RU text, so I am going to skip those two in the docs.

**Comment by rfraposa** [comment]
Completed with https://github.com/ClickHouse/ClickHouse/pull/45137
