### ISSUE TITLE
need docs for cramersV

### ISSUE THREAD

**Issue by DanRoscigno** [ClickHouse/ClickHouse#44793]
https://github.com/ClickHouse/ClickHouse/pull/33366

**Comment by rfraposa** [comment]
There are actually 4 missing agg functions in the docs from that PR: `cramersV`, `cramersVBiasCorrected`, `theilsU` and `contingency`.

**Comment by rfraposa** [comment]
Added here: https://github.com/ClickHouse/ClickHouse/pull/45091
