### ISSUE TITLE
need docs for toUUIDOrDefault

### ISSUE THREAD

**Issue by DanRoscigno** [ClickHouse/ClickHouse#44802]

**Comment by DanRoscigno** [comment]
@kitaisreal can you help with this please?  I looked at the queries in test, but I don't understand what this can be used for.

Here is original PR: https://github.com/ClickHouse/ClickHouse/pull/21330

**Comment by kitaisreal** [comment]
@DanRoscigno `toTypeOrDefault` is necessary if you need to convert column to target type, but some values in column are invalid for target type, that way for these specific values, default value will be used.

**Comment by DanRoscigno** [comment]
Thanks, now I get it.  The PR added the toDefault for those functions.  Thanks very much!
