### ISSUE TITLE
CREATE OR REPLACE and EXCHANGE TABLES for Memory database

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#44817]
**Use case**

`Memory` database engine is used in `clickhouse-local`, and nothing prevents implementing these queries.

**Describe the solution you'd like**

A mutex.

**Comment by evillique** [comment]
The Memory database engine does not use UUIDs in tables and databases, and if the table stores data on the disk then the table data is stored directly in the `data/database_name/table_name` folder and not in (for example) `store/xxx/1e8dfeba-73a1-4b40-8238-63e58c9a3893`.

So in the case of RENAME query, we would need to either modify every table engine that stores data to have the ability to move its data from `data/database_name/table_name` to `data/database_name/new_table_name` (and hope that nothing breaks) or to use UUIDs and store the data in the `store/` directory which kind of makes it not temporary and basically an Atomic engine without saving metadata.

Is there a reason for using the Memory engine in clickhouse-local? Either way, we will store the data in the `/tmp/clickhouse-local-.../` directory and it seems like the better solution would be to just use the Atomic engine.

**Comment by alexey-milovidov** [comment]
Memory database engine is like another database engine, but without persisting the .sql files.
Currently, it is modeled after the Ordinary database engine.
But the Ordinary database engine is obsolete. Let's make the tables' paths like in the Atomic database engine.

Let's not worry about compatibility because it's expected that everything in the Memory database is temporary.

PS. These operations should be supported:

`REPLACE TABLE`
`CREATE OR REPLACE TABLE`
`EXCHANGE TABLES`
`ATTACH TABLE ... UUID '...'`

PS. Maybe we can decouple the way how DB's metadata is stored with the way how the table's paths are determined? But this will be a much broader task, let's consider it only after making the first solution.
