### ISSUE TITLE
Materialized Views on distributed tables with `TO [db].[table]`

### ISSUE THREAD

**Issue by makeavish** [ClickHouse/ClickHouse#44863]
I am running distributed clickhouse cluster.
If we are using `TO [db].[table]` then should the underlying [table] be distributed or not?
Following issue is related but discusses on creating MV without `TO [db].[table]` 
https://github.com/ClickHouse/ClickHouse/issues/467

**Comment by den-crane** [comment]
Check https://den-crane.github.io/Everything_you_should_know_about_materialized_views_commented.pdf page 27 -

**Comment by makeavish** [comment]
@den-crane Thanks for response but this doesn't answer my question.

**Comment by den-crane** [comment]
It should not. But it can if you need. For example: _if you need to shard data in MV by another sharding
key. Let's say a source table is sharded by transaction identifier but MV has to be
sharded by user identifier._

**Comment by pkit** [comment]
@den-crane it's not that simple. Let's consider two matviews feeding from each other:
`t1 -> mv1 -> t2 -> mv2 -> t3`
In case of non-clustered CH all is well.
But in case of clustered CH, mv push would not propagate if it's connected not directly.
I.e. if you connect mv1 to the replicated t2 then mv2 must be connected to the replicated t2.
And if you connect it to the distributed t2 then mv2 needs to feed off the distributed t2 too.
So the simplest approach would be to always use distributed. But probably it is less performant, didn't check it yet.
