### ISSUE TITLE
Why is map access working with linear complexity?

### ISSUE THREAD

**Issue by andrea-s** [ClickHouse/ClickHouse#44904]
In reference to https://clickhouse.com/docs/en/sql-reference/data-types/map, we learn that accessing a Map value, e.g. a['key'] is currently working with linear complexity.

This means that a query like the following, which produces an inline map of significant size, is quite slow:

```
SELECT
    number,
    (
        SELECT anyMap(map(toString(number), number + 1))
        FROM
        (
            SELECT *
            FROM system.numbers
            LIMIT 100000
        )
    )[toString(number)] as nnext
FROM system.numbers
LIMIT 100000
```

Is there a way, or is it planned, to have Maps work with sorted keys so that we can access their values in constant time?

The use case for this is similar to a dictionary, but specific for the situations in which we need to calculate the values just in time.

**Comment by den-crane** [comment]
see https://github.com/ClickHouse/ClickHouse/issues/33449#issuecomment-1007688282

**Comment by andrea-s** [comment]
Thank you @den-crane, I understand the context better now.

Unfortunately the transform() function requires the arrays to be constant, which is not applicable to my case. Is there a function similar to transform() but which can actually build the hashmap on the fly?
