### ISSUE TITLE
Wrong output with transform function, when output is float32

### ISSUE THREAD

**Issue by larspars** [ClickHouse/ClickHouse#44918]
**Describe what's wrong**

The following:

    select transform(number, [1], [toFloat32(1)], toFloat32(1)) from numbers(3)

outputs:

    1
    0
    1

**Expected behavior**

It should output:

    1
    1
    1

It seems like anything matching the `array_from` argument will output 0, when the output type is float32. It seems to work as it should with other types.

**Does it reproduce on recent release?**

I've reproduced on ClickHouse playground, I assume that's running the latest version.

**Comment by den-crane** [comment]
```sql
select transform(number, [3], [toFloat32(1)], toFloat32(1)) from numbers(6);

┌─transform(number, [3], array(toFloat32(1)), toFloat32(1))─┐
│                                                         1 │
│                                                         1 │
│                                                         1 │
│                                                         0 │
│                                                         1 │
│                                                         1 │
└───────────────────────────────────────────────────────────┘
```

20.8
```sql
select transform(number, [3], [toFloat32(1)], toFloat32(1)) from numbers(6);
0
0
0
0
0
0
```

**Comment by alexey-milovidov** [comment]
It's fixed.
