### ISSUE TITLE
Support for SQL scripts in clickhouse-client

### ISSUE THREAD

**Issue by jangorecki** [ClickHouse/ClickHouse#4491]
It is very common use case to run a series of sql queries stored in a SQL script. Currently client doesn't seems to support that. Thus this request.
Ideally the API something like
```sh
clickhouse-client script.sql
```
I am aware of running client for each query separately and `multiline` parameter.

**Comment by den-crane** [comment]
cat script.sql | clickhouse-client -mn

cat qq.sh
#!/bin/bash
cat $1| clickhouse-client -mn

**Comment by jangorecki** [comment]
Thanks again, will leave that open as I think it is still worth to support script files and not just piping them it. Feel free to close if there is no plans to incorporate that.

**Comment by etah000** [comment]
snowball-client --multiquery < script.sql

**Comment by akuzm** [comment]
Implemented in https://github.com/ClickHouse/ClickHouse/pull/15930
