### ISSUE TITLE
UDF: Cannot write into pipe, errno: 32, strerror: Broken pipe

### ISSUE THREAD

**Issue by srikanthccv** [ClickHouse/ClickHouse#44926]
Hello 👋 ,

I am running into the following error when working with the executable UDF. I need a minor variation of `runningDifference` function that works with a monotonic counter value. It should be reset/restart aware, i.e. the subsequent difference at the reset points should not be negative. I thought using a UDF would be the best option and go it to work but when I have a higher number of values to run against it fails with cannot write to file descriptor error.

Error message:

```
Code: 75. DB::Exception: Received from localhost:9000. DB::ErrnoException. DB::ErrnoException: Cannot write into pipe, errno: 32, strerror: Broken pipe: While executing CSVRowOutputFormat: while executing 'FUNCTION runningDifferenceCustom(groupArray(value) :: 0) -> runningDifferenceCustom(groupArray(value)) Array(Float64) : 1'. (CANNOT_WRITE_TO_FILE_DESCRIPTOR)
```

Here is the UDF code:

```go
package main

import (
	"bufio"
	"fmt"
	"os"
	"strconv"
	"strings"
)

// NOTE: executable must be built with target OS and architecture set
// env GOOS=linux GOARCH=arm64 go build -o runningDifferenceCustom runningDifferenceCustom.go

func main() {
	scanner := bufio.NewScanner(os.Stdin)
	for scanner.Scan() {
		text := scanner.Text()
		var numbers []float64
		text = text[2 : len(text)-2]
		for _, num := range strings.Split(text, ",") {
			num = strings.TrimSpace(num)
			number, err := strconv.ParseFloat(num, 64)
			if err == nil {
				numbers = append(numbers, number)
			}
		}
		var prev float64
		var diffArray []float64
		for _, num := range numbers {
			diff := num - prev
			if prev > num {
				diff += prev
			}
			diffArray = append(diffArray, diff)
			prev = num
		}
		fmt.Print("\"[")
		for idx, num := range diffArray {
			fmt.Print(num)
			if idx < len(diffArray)-1 {
				fmt.Print(",")
			}
		}
		fmt.Print("]\"")
		fmt.Print("\n")
	}

	if err := scanner.Err(); err != nil {
		fmt.Fprintln(os.Stderr, "reading standard input:", err)
	}
}
```

Function XML Config:

```
<functions>
    <function>
        <type>executable</type>
        <name>runningDifferenceCustom</name>
        <return_type>Array(Float64)</return_type>
        <argument>
            <type>Array(Float64)</type>
            <name>value</name>
        </argument>
        <format>CSV</format>
        <command>./runningDifferenceCustom</command>
    </function>
</functions>
```

Query with small range of numbers that doesn't trigger broken pipe error

```sql
SELECT arrayJoin(runningDifferenceCustom(groupArray(value)))
FROM
(
    SELECT number AS value
    FROM numbers(69)
)
```

Query that triggers the broken pipe error
```sql
SELECT arrayJoin(runningDifferenceCustom(groupArray(value)))
FROM
(
    SELECT number AS value
    FROM numbers(100000)
)
```

Am I missing something? Is UDF a right fit for the use cases? And can UDFs be used to work with tens or hundreds of millions of values? I would really appreciate some help here.

**Comment by srikanthccv** [comment]
I was able to figure this out. There is a limitation with the `bufio.NewScanner` that it has a max buffer of 64k, which is not sufficient for 100k lines of numbers. This returns an error and exits but ClickHouse, not knowing that it is probably writing to the file descriptor that is not available, leads to the broken pipe not being able to write to the fd error.

**Comment by vlourme** [comment]
I lost a lot of time finding out of this. I think `bufio.NewScanner` should not be used when making a ClickHouse UDF, instead use `NewReader` for no buffer limitation:
```go
rd := bufio.NewReader(os.Stdin)

for {
	b, err := rd.ReadBytes('\n')
	if err != nil {
		break
	}

	text := string(b)
}
```
