### ISSUE TITLE
How do I reuse operator results, such as FilterTranform?

### ISSUE THREAD

**Issue by caiwanli** [ClickHouse/ClickHouse#44927]
I want to implement an operator cache, output the results calculated by the Filter operator to redis, and then execute the same query again (predicate conditions have inclusion relations can also reuse the results), the Filter results will be directly obtained from redis.I'm "void FilterTransform: : transform (the Chunk & input_chunk, the Chunk & output_chunk)" stored in result, converting the Chunk parquet in the redis, Then obtain the cached results on IProcessor::Status FilterTransform::prepare().Here I'm going to reuse "void FilterTransform: : transform (the Chunk & the Chunk)" method, because the cached results may be a superset of the current query. For example, the result I cached might be 20<age<30, when I query the condition is 20<age<25, I can reuse the transform method directly on top of the cached results. When I reuse transform directly, it always returns zero rows, which confuses me, and should theoretically return a match 20<age<25. I tried to figure out the logic of transform, but there were too few code comments. Also, I am a c++ novice and do not understand the advanced usage of gdb debugging. As a result, it was hard to keep track of variable changes when I was debugging clickhouse. I'd like some tips from the clickhouse developers on debugging clickhouse and why reusing transform always returns an empty result. My code address is [https://github.com/caiwanli/ClickHouse/blob/sub_filter/src/Processors/Transforms/FilterTransform.cpp](url)

**Comment by alexey-milovidov** [comment]
When Transform has already processed data to the end, it has the ports closed and does not request newer data.
The Transform should be recreated.
