### ISSUE TITLE
Alter cannot be assigned because of Zookeeper error

### ISSUE THREAD

**Issue by 825644691** [ClickHouse/ClickHouse#44931]
alter table　  vipcube.ads_cube_mer_item_dim_order_rt_df_local　add　  column `app_type` String ,　add　  column `biz_flag` Int64 ;

ALTER TABLE vipcube.ads_cube_mer_item_dim_order_rt_df_local
    ADD COLUMN `app_type` String,     ADD COLUMN `biz_flag` Int64

Query id: 2f60a7ba-d3ca-4a3e-8dd0-9537149cfcd4

0 rows in set. Elapsed: 0.004 sec. 

Received exception from server (version 22.3.3):
Code: 999. DB::Exception: Received from localhost:9000. DB::Exception: Alter cannot be assigned because of Zookeeper error (Node exists). 

how to deal this problem?

**Comment by den-crane** [comment]
22.3.3 is obsolete. Try 22.3.15.33.
