### ISSUE TITLE
Clickhouse-Local Doesn't Save to Parquet

### ISSUE THREAD

**Issue by marcelteraflow** [ClickHouse/ClickHouse#44944]
I followed [this tutorial](https://clickhouse.com/blog/extracting-converting-querying-local-files-with-sql-clickhouse-local?utm_source=linkedin&utm_medium=social&utm_campaign=blog) and noticed the following:

```shell
clickhouse local -q "select * from file('clickhouse_hacker_news.csv' , 'CSVWithNames') into outfile 'hackernews.parquet' format parquet;"
```

```console
Code: 76. DB::Exception: Code: 76. DB::Exception: Code: 76. DB::ErrnoException: Cannot open file hackernews.parquet, errno: 17, strerror: File exists. (CANNOT_OPEN_FILE) (version 22.13.1.1301 (official build)). (CANNOT_OPEN_FILE) (version 22.13.1.1301 (official build)). (CANNOT_OPEN_FILE)
```
The file does not exist on disk prior to running this command.

Platform: macos arm64
Version: ClickHouse local version 22.13.1.1301 (official build).

**Comment by nikitamikhaylov** [comment]
I did the same and this appears not to be true. Check the directory from where you launched `clickhouse-local`, the file should be there.

**Comment by marcelteraflow** [comment]
The case sensitivity of both "Parquet" vs "PARQUET" and "csv" vs "CSV" in the FORMAT clause is throwing me of
