### ISSUE TITLE
How to return several raws in executable UDF?

### ISSUE THREAD

**Issue by d1bevz** [ClickHouse/ClickHouse#44958]
Hey guys!
I really appreciate your work at clickhouse, UDF is a really nice-to-have thing!

I did not figure out how to return several raws while executing UDF? 

For example, I have a function parses some data via `requests` and returns 2d matrix. I want to parse this 2d matrix as columns and rows in Clickhouse. 

It seems like I can use CSV format in output, but it is not covered in docs.

**Comment by Algunenano** [comment]
UDF's are functions, and as such must return exactly 1 value/cell per input row. You can try returning an array and then using [ARRAY JOIN](https://clickhouse.com/docs/en/sql-reference/statements/select/array-join).
