### ISSUE TITLE
Quorum is not updated on empty parts cleanup

### ISSUE THREAD

**Issue by Alex-Cheng** [ClickHouse/ClickHouse#44972]
When turn on the setting `select_sequential_consistency ` and create a ReplicatedMergeTree table with some data filled in, the REPLICA_IS_NOT_IN_QUORUM excpetion will occur after deleted all data of the table, because that the `quorum/last_part` contains a data part to check and all data parts have been removed in local after deleting all data.

The below code throws the exception. If `!getActiveContainingPart(added_part.second)` returns true, then exception will be thrown.

```C++
    String added_parts_str;
    if (zookeeper->tryGet(fs::path(zookeeper_path) / "quorum" / "last_part", added_parts_str))
    {
        if (!added_parts_str.empty())
        {
            ReplicatedMergeTreeQuorumAddedParts part_with_quorum(format_version);
            part_with_quorum.fromString(added_parts_str);

            auto added_parts = part_with_quorum.added_parts;

            for (const auto & added_part : added_parts)
                if (!getActiveContainingPart(added_part.second))
                    throw Exception(
                        "Replica doesn't have part " + added_part.second
                            + " which was successfully written to quorum of other replicas."
                              " Send query to another replica or disable 'select_sequential_consistency' setting.",
                        ErrorCodes::REPLICA_IS_NOT_IN_QUORUM);

            for (const auto & max_block : part_with_quorum.getMaxInsertedBlocks())
                max_added_blocks[max_block.first] = max_block.second;
        }
    }
```

> A link to reproducer in [https://fiddle.clickhouse.com/90496470-8acc-47b6-b078-03e007d2c0a8/](https://fiddle.clickhouse.com/90496470-8acc-47b6-b078-03e007d2c0a8).
It needs to be run on cluster(ond shard, multi-replicas).

**Does it reproduce on recent release?**
v22.8.5.29-lts

**How to reproduce**

* Which ClickHouse server version to use
v22.8.5.29-lts

* Which interface to use, if matters
clickhouse-client

* Non-default settings, if any
select_sequential_consistency =1

* `CREATE TABLE` statements for all tables involved
Run following SQL script in the cluster `ch-pro-cluster` with two nodes: node01 and node02. Run SQL script in node01 to reproduce.
```
create database test_001 ON CLUSTER 'ch-pro-cluster';

CREATE TABLE `test_001`.`events5` ON CLUSTER 'ch-pro-cluster'
(
    ID UInt64,
    v Int64,
    n String,
    case_id String
) ENGINE = ReplicatedMergeTree('/clickhouse/tables/{uuid}', '{replica}')
ORDER BY ID;

insert into `test_001`.`events5`(ID, v, n, case_id) select number, rand(), 'haha', toString(number / 10) from numbers(1000);

OPTIMIZE TABLE `test_001`.`events5` FINAL;
```

* Queries to run that lead to unexpected result
```
ALTER TABLE `test_001`.`events5` DELETE  WHERE 1;

-- wait for a while 

SELECT * FROM `test_001`.`events5`;
```

**Expected behavior**
Query `SELECT * FROM `test_001`.`events5`;` should not throw exception.

**Comment by tavplubix** [comment]
Cannot reproduce: https://pastila.nl/?02d75660/9c72e75686e787e2c3082d9734091495
The exception message means that the replica is not up to date. Probably you forgot to add `SYSTEM SYNC REPLICA` before selecting.

**Comment by Alex-Cheng** [comment]
Please wait for a while until all parts are removed by background worker thread, after executed `ALTER TABLE ... DELETE`.

**Comment by Alex-Cheng** [comment]
BTW, how often should I run `SYSTEM SYNC REPLIC` on each replica?

**Comment by Alex-Cheng** [comment]
@tavplubix Please try again with my advice. I have reproduced the issue twice more. 

After deleting all data, the all parts will be removed in background thread. Please wait a moment until no parts remain for the table. Query `select name, path from system.parts where database='test_001' and table='events5';` can check it. 

Then check the zookeeper path `/{replicated merge tree table path}/quorum`, for example in my env, the query is `select * from system.zookeeper where path='/clickhouse/tables/c4fe2b6b-0f34-44a3-81c4-44ae6a549c7e/quorum'`. The result is:

```
SELECT *
FROM system.zookeeper
WHERE path = '/clickhouse/tables/c4fe2b6b-0f34-44a3-81c4-44ae6a549c7e/quorum'

Query id: 18f73865-cb23-4871-abbc-3479a8861629

┌─name─────────┬─value────────────────────────────────────┬─path───────────────────────────────────────────────────────────┐
│ failed_parts │                                          │ /clickhouse/tables/c4fe2b6b-0f34-44a3-81c4-44ae6a549c7e/quorum │
│ last_part    │ version: 2
parts count: 1
all     all_0_0_0
 │ /clickhouse/tables/c4fe2b6b-0f34-44a3-81c4-44ae6a549c7e/quorum │
│ parallel     │                                          │ /clickhouse/tables/c4fe2b6b-0f34-44a3-81c4-44ae6a549c7e/quorum │
└──────────────┴──────────────────────────────────────────┴────────────────────────────────────────────────────────────────┘
```

The `last_part` content is 
```
version: 2
parts count: 1
all     all_0_0_0
```
But the part `all_0_0_0` for table `events5` does not exist(no parts exist for the table after deleting all data).

That causes the exception and `SYSTEM SYNC REPLIC` cannot resolve the problem.

**Comment by Alex-Cheng** [comment]
I think we need to clearn up the `/{table zk path}/quorum/last_part` znode after deleting all data.

**Comment by tavplubix** [comment]
Thanks for the additional information, I finally reproduced it with `insert_quorum_parallel=0` (there's another issue: `select_sequential_consistency=1` just does not work with `insert_quorum_parallel=1` (default) without any errors/warnings).

Looks like the problem is that quorum information in zk is not updated on empty parts cleanup. Workaround: disable `remove_empty_parts` settings. Also it works fine with ALTER DROP PARTITION.

**Comment by filimonov** [comment]
I suspect something similar can happen if the part was lost (`Part 20230218_3334_3334_0 does not exist on any replica. (NO_REPLICA_HAS_PART)`) but the quorum record is still there.

**Comment by R-omk** [comment]
related https://github.com/ClickHouse/ClickHouse/issues/38964

**Comment by raosong** [comment]
@tavplubix , After I added <remove_empty_parts>0</remove_empty_parts> in the users.xml file, clickhouse throws "unknown setting remove_empty_parts".  Our clickhouse version 22.8. thank you.
