### ISSUE TITLE
S3 access via ServiceAccount

### ISSUE THREAD

**Issue by yannick** [ClickHouse/ClickHouse#44980]
when running on AWS / EKS permissions are usually granted via policies attached to ServiceAccounts. it should there for not be needed to supply access keys. 

 
 
 replaces https://github.com/ClickHouse/ClickHouse/issues/44974

**Comment by yannick** [comment]
`use_environment_credentials` fixes it, i missed that one. sorry.
 i think this should/could be default if no keys are given as with basically anything else using aws sdk's. 
 
 Couldnt https://github.com/ClickHouse/ClickHouse/blob/573d3283b09c8ac7752b5cbf4634f117e2667d78/src/IO/S3Common.cpp#L601 
 just check for emptyness of &credentials and then run this code, because empty credentials will fail anyway later?!

**Comment by yannick** [comment]
maybe the docs are unclear but from what i understand this setting should also work for the S3 Table Engine but i am getting permission errors.

**Comment by den-crane** [comment]
>i think this should/could be default if no keys are given as is standard behavior with basically any app using aws sdk's.

It's the interesting idea.

S3 Table Engine does not support `use_environment_credentials=1`.

**Comment by yannick** [comment]
it might be as simple as 
```
Aws::Auth::DefaultAWSCredentialsProviderChain provider;
auto credentials = provider.GetAWSCredentials();
```
in 
https://github.com/ClickHouse/ClickHouse/blob/5c8fb627b3657a7cd64cdd23fe0fe37724e77fc5/src/Storages/StorageS3.cpp#L1251 if settings are empty.

**Comment by alexey-milovidov** [comment]
We have enabled environment credentials by default - now they work for s3 table functions, and even in clickhouse-local.
