### ISSUE TITLE
Incorrect documentation  for MySQL engine 

### ISSUE THREAD

**Issue by pragmaton** [ClickHouse/ClickHouse#4500]
In [MySQL - ClickHouse Documentation](https://clickhouse.yandex/docs/en/operations/table_engines/mysql/)

> The MySQL engine does not support the Nullable data type, so when reading data from MySQL tables, NULL is converted to default values for the specified column type (usually 0 or an empty string).

Looks like this is wrong for version 19.3.4 - you can get NULL value

For example

```
SELECT 
    TABLE_ROWS, 
    isNull(TABLE_ROWS)
FROM mysql('localhost:3306', 'information_schema', 'TABLES', 'user', 'pass') 
LIMIT 1

┌─TABLE_ROWS─┬─isNull(TABLE_ROWS)─┐
│       ᴺᵁᴸᴸ                  │                1                      │
└────────────┴───────────────┘

1 rows in set. Elapsed: 0.128 sec. 

```

Another thing, if you try to use it exactly as  `MySQL()` (as you see in documentation) you get

> Code: 46. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Unknown table function MySQL.

It should be lowercase `mysql`

**Comment by BayoNet** [comment]
Fixed in #5487
