### ISSUE TITLE
cityHash64 of ipv4 

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#45020]
22.12
```sql
SELECT cityHash64(toIPv4('1.2.3.4'))
--
5715546585361069049
```

22.13
```sql
SELECT cityHash64(toIPv4('1.2.3.4'))
--
3462390757903342180
```

I found it accidentally. It seems it's only with cityHash64 and IPv4. 
It seems it's OK with other hash functions (sipHash / xxHash32) and IPv6.
May be it's only issue with MacOs build.

If it's the real issue, probably it's worth to check all hash functions.

**Comment by yakov-olkhovskiy** [comment]
please merge this test after #45024 is merged
