### ISSUE TITLE
support multidimensional cosine distance and euclidean distance function

### ISSUE THREAD

**Issue by cmdares** [ClickHouse/ClickHouse#4509]
Multidimensional vector cosine distance and euclidean distance

----tbl----
id,dim1,dim2,dim3,dim4,dim5
1,0.13,024,0.37,1.2,1.1
2,0.13,024,0.46,1.27,0.7
3,0.11,024,0.37,1.2,0.3
4,0.23,028,0.17,1.2.0.311

query term: 0.12,023,0.37,1.2,0.31
calculate Euclidean distance and cos distance with every row

**Comment by alexey-milovidov** [comment]
So, we need tuple-wise addition and subtraction operators, and also scalar product function and l2Distance, l2Norm and cosineDistance functions.

**Comment by mathalex** [comment]
There will be L1, L2, Linf, Lp versions for the Distance and Norm functions.
