### ISSUE TITLE
Distributed Query fails with DNS_ERROR if one replica is offline

### ISSUE THREAD

**Issue by derbauer97** [ClickHouse/ClickHouse#45096]
**Describe the unexpected behaviour**
We have a Distributed Table:
`Distributed('instana', 'shared', 'calls_v3', cityHash64(lower(hex(substring(trace_id, -8, 8)))))`

Which points to an ReplicatedMergeTree Table. We are using the Altinity Clickhouse Operator which creates One DNS Record for each Replica.

Our Cluster Layout is currently: 2 Shards with 2 Replicas each with internal_replication = true.

If one of those Replicas is offline (e.g. during an rolling Update of the nodes) our Read Queries to the Distributed Table sometimes fails with the follwing error:
```
SELECT call_id
FROM shared.all_calls_v3
LIMIT 1

Query id: 70ff37c9-0384-43b3-9a47-a6f8de106f51


0 rows in set. Elapsed: 0.197 sec.

Received exception from server (version 22.12.1):
Code: 198. DB::Exception: Received from localhost:9000. DB::Exception: Not found address of host: chi-instana-clickhouse-instana-1-0: While executing Remote. (DNS_ERROR)

```

I tried the same with skip_unavailable_shards = 1 which seems to fit for this kind of situation but i still get the same exception

Output of system.clusters when Node is offline:

```
┌─cluster─┬─shard_num─┬─shard_weight─┬─replica_num─┬─host_name──────────────────────────┬─host_address───┬─port─┬─is_local─┬─user────┬─default_database─┬─errors_count─┬─slowdowns_count─┬─estimated_recovery_time─┐
│ instana │         1 │            1 │           1 │ chi-instana-clickhouse-instana-0-0 │ 127.0.0.1      │ 9000 │        1 │ default │                  │            0 │               0 │                       0 │
│ instana │         1 │            1 │           2 │ chi-instana-clickhouse-instana-0-1 │ 192.168.19.156 │ 9000 │        0 │ default │                  │            0 │               0 │                       0 │
│ instana │         2 │            1 │           1 │ chi-instana-clickhouse-instana-1-0 │                │ 9000 │        0 │ default │                  │            0 │               0 │                       0 │
│ instana │         2 │            1 │           2 │ chi-instana-clickhouse-instana-1-1 │ 192.168.7.155  │ 9000 │        0 │ default │                  │            0 │               0 │                       0 │
└─────────┴───────────┴──────────────┴─────────────┴────────────────────────────────────┴────────────────┴──────┴──────────┴─────────┴──────────────────┴──────────────┴─────────────────┴─────────────────────────┘
```

* Which ClickHouse server version to use
22.12.1.1752

* Non-default settings, if any

skip_unavailable_shards = 1

**Expected behavior**
Clickhouse perfroms the query against the alive replica and does not throw an exception

**Comment by tavplubix** [comment]
Related to https://github.com/ClickHouse/ClickHouse/pull/43179

**Comment by derbauer97** [comment]
Hey @tavplubix,

thanks for the quick answer that means there is an unaffected version which should work?

**Comment by tavplubix** [comment]
it does not mean that

**Comment by derbauer97** [comment]
I downgraded to 22.8.12.45 and it does not occur with this version. Maybe there are other issue with this version but for the moment it works for me.
