### ISSUE TITLE
Can't parse DateTime from String with milliseconds

### ISSUE THREAD

**Issue by IncubusRK** [ClickHouse/ClickHouse#45092]
Convert a String with milliseconds to a **date** work fine:
`SELECT toDate('2023-01-03 00:00:00.000000')`
Convert a String with milliseconds to a **datetime** don't work:
`SELECT toDateTime('2023-01-03 00:00:00.000000')`

SQL Error:
```
DB::Exception: Cannot parse string '2023-01-03 00:00:00.000000' as DateTime: syntax error at position 19 (parsed just '2023-01-03 00:00:00'): While processing toDateTime('2023-01-03 00:00:00.000000'). (CANNOT_PARSE_TEXT) (version 22.12.2.25 (official build))
, server ClickHouseNode
```

ClickHouse server version 22.12.2.25

**Comment by den-crane** [comment]
This is expected behaviour. By performance reasons toDate and toDateTime support only specific format YYYY-MM-DD and YYYY-MM-DD HH:mm:SS.

You can use 

```sql
SELECT toDate(parseDateTimeBestEffort('2023-01-03 00:00:00.000000'))
┌─toDate(parseDateTimeBestEffort('2023-01-03 00:00:00.000000'))─┐
│                                                    2023-01-03 │
└───────────────────────────────────────────────────────────────┘

SELECT parseDateTimeBestEffort('2023-01-03 00:00:00.000000');
┌─parseDateTimeBestEffort('2023-01-03 00:00:00.000000')─┐
│                                   2023-01-03 00:00:00 │
└───────────────────────────────────────────────────────┘
```

**Comment by IncubusRK** [comment]
> This is expected behaviour. By performance reasons toDate and toDateTime support only specific formats "YYYY-MM-DD" and "YYYY-MM-DD HH:mm:SS".

As I mentioned above SELECT toDate('2023-01-03 00:00:00.000000') work, so toDate support desired format, but toDateTime is not. IMHO this is strange behaviour.
