### ISSUE TITLE
Metadata on replica is not up to date with common metadata in Zookeeper after problem when creating index

### ISSUE THREAD

**Issue by gregleongf** [ClickHouse/ClickHouse#45117]
I've tried running SQL query that creates index:
```
ALTER TABLE sharded_events
ADD INDEX sessionIdIX $session_id TYPE set(0) GRANULARITY 2;
```
But the query ran for a very long time and it failed. Now every time i try to modify sharded_events table I get
`Metadata on replica is not up to date with common metadata in Zookeeper` error

Now when I run `SHOW CREATE TABLE shared_events` the index is not visible but the meta data in zookeper does have information about the index:
```
metadata format version: 1
date column: 
sampling expression: cityHash64(distinct_id)
index granularity: 8192
mode: 5
sign column: 
primary key: team_id, toDate(timestamp), event, cityHash64(distinct_id), cityHash64(uuid)
data format version: 1
partition key: toYYYYMM(timestamp)

indices: sessionIdIX `$session_id` TYPE set(0) GRANULARITY 1

granularity bytes: 10485760
```

Is there a way to sync zookeeper metadata?

What I've tried:

1. DETACH/ATTACH the table
2. SYSTEM RESTART REPLICA

But nothing seems to work.

The full error:
```
2023.01.10 13:12:20.203365 [ 5400 ] {23450527-a818-4a9b-8b51-5cf0ce66471d} <Error> DynamicQueryHandler: Code: 517. DB::Exception: Metadata on replica is not up to date with common metadata in Zookeeper. It means that this replica still not applied some of previous alters. Probably too many alters executing concurrently (highly not recommended). You can retry this error. (CANNOT_ASSIGN_ALTER), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xb39c11a in /usr/bin/clickhouse
1. DB::StorageReplicatedMergeTree::alter(DB::AlterCommands const&, std::__1::shared_ptr<DB::Context const>, std::__1::unique_lock<std::__1::timed_mutex>&) @ 0x15ef5df1 in /usr/bin/clickhouse
2. DB::InterpreterAlterQuery::executeToTable(DB::ASTAlterQuery const&) @ 0x15850ff7 in /usr/bin/clickhouse
3. DB::InterpreterAlterQuery::execute() @ 0x1584ec92 in /usr/bin/clickhouse
4. ? @ 0x15bb67ef in /usr/bin/clickhouse
5. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::__1::shared_ptr<DB::Context>, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>, std::__1::optional<DB::FormatSettings> const&) @ 0x15bb9a4a in /usr/bin/clickhouse
6. DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::__1::optional<DB::CurrentThread::QueryScope>&) @ 0x164cbf48 in /usr/bin/clickhouse
7. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x164d06f2 in /usr/bin/clickhouse
8. DB::HTTPServerConnection::run() @ 0x167576fb in /usr/bin/clickhouse
9. Poco::Net::TCPServerConnection::start() @ 0x19a16f8f in /usr/bin/clickhouse
10. Poco::Net::TCPServerDispatcher::run() @ 0x19a193e1 in /usr/bin/clickhouse
11. Poco::PooledThread::run() @ 0x19bd63a9 in /usr/bin/clickhouse
12. Poco::ThreadImpl::runnableEntry(void*) @ 0x19bd3700 in /usr/bin/clickhouse
13. ? @ 0x7f22809b2609 in ?
14. clone @ 0x7f22808d7133 in ?
 (version 22.3.13.80 (official build))
```

**Comment by den-crane** [comment]
check / share `select * from system.mutations where not is_done \G` from ALL REPLICAS.

**Comment by gregleongf** [comment]
There are 9 rows there but the ones related to sessionId index are:

posthog	sharded_events	0000000006	MATERIALIZE INDEX sessionIX
posthog	sharded_events	0000000007	MATERIALIZE INDEX sessionIX
posthog	sharded_events	0000000008	DROP INDEX sessionIX

But these are probably from the time I wanted to create new index after I've noticed the old on wasn't created.
sessionIdIX was the original index name and sessionIX was second try.

Latest fail time for all of those is 1970-01-01 00:00:00 which I assume means they didn't fail and instead are stuck.

**Comment by den-crane** [comment]
no required info provided.

**Comment by den-crane** [comment]
>There are 9 rows there but the ones related to sessionId index are:

I asked specific question. You provided some meaningless info. You should understand that time is expensive and we don't have spare time to read some noise.

**Comment by den-crane** [comment]
I will reopen this when you provide `select * from system.mutations where not is_done \G` from ALL REPLICAS.

**Comment by gregleongf** [comment]
database | table | mutation_id | command | create_time | block_numbers.partition_id | block_numbers.number | parts_to_do_names | parts_to_do | is_done | latest_failed_part | latest_fail_time | latest_fail_reason
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
posthog | sharded_events | 0 | UPDATE `mat_$browser` = `mat_$browser`, `mat_$geoip_country_code` =   `mat_$geoip_country_code` WHERE timestamp > '2022-05-29' | ######## | ["202207","202208"] | [3348,297929] | ["202208_0_54455_10891"] | 1 | 0 |   | ######## |  
posthog | sharded_events | 1 | UPDATE `mat_$host` = `mat_$host`, mat_ref = mat_ref, mat_index =   mat_index, `mat_$current_url` = `mat_$current_url` WHERE timestamp >   '2022-06-05' | ######## | ["202207","202208","202209"] | [3349,350896,24421] | ["202208_0_54455_10891"] | 1 | 0 |   | ######## |  
posthog | sharded_events | 2 | UPDATE `mat_$referring_domain` = `mat_$referring_domain`, `mat_$referrer`   = `mat_$referrer`, mat_ref_code = mat_ref_code, mat_project_id =   mat_project_id WHERE timestamp > '2022-06-12' | ######## | ["202207","202208","202209"] | [3350,350897,101848] | ["202208_0_54455_10891"] | 1 | 0 |   | ######## |  
posthog | sharded_events | 3 | UPDATE `mat_$geoip_country_name` = `mat_$geoip_country_name`,   `mat_$geoip_subdivision_1_name` = `mat_$geoip_subdivision_1_name`,   `mat_$geoip_continent_name` = `mat_$geoip_continent_name`, mat_hour =   mat_hour, `mat_$geoip_continent_code` = `mat_$geoip_continent_code`,   mat_request_context_project_version = mat_request_context_project_version   WHERE timestamp > '2022-06-19' | ######## | ["202207","202208","202209"] | [3351,350898,179301] | ["202208_0_54455_10891"] | 1 | 0 |   | ######## |  
posthog | sharded_events | 4 | UPDATE mat_request_context_project_url_name =   mat_request_context_project_url_name, mat_request_context_creator_url_name =   mat_request_context_creator_url_name, mat_request_context_project_phase =   mat_request_context_project_phase, mat_experiment_project_recommendation_algorithm   = mat_experiment_project_recommendation_algorithm, `mat_$time` = `mat_$time`,   `mat_$pathname` = `mat_$pathname`, mat_utm_medium = mat_utm_medium WHERE   timestamp > '2022-06-26' | ######## | ["202207","202208","202209"] | [3352,350899,242755] | ["202208_0_54455_10891"] | 1 | 0 |   | ######## |  
posthog | sharded_events | 5 | UPDATE person_id = if(empty(person_id),   toUUID(dictGet('posthog.person_distinct_id2_dict', 'person_id', (team_id,   distinct_id))), person_id), person_properties = if(person_properties = '',   dictGetStringOrDefault('posthog.person_dict', 'properties', (team_id,   toUUID(dictGet('posthog.person_distinct_id2_dict', 'person_id', (team_id,   distinct_id)))), toJSONString(map())), person_properties), person_created_at   = if(person_created_at = toDateTime(0),   dictGetDateTime('posthog.person_dict', 'created_at', (team_id,   toUUID(dictGet('posthog.person_distinct_id2_dict', 'person_id', (team_id,   distinct_id))))), person_created_at), group0_properties =   if(group0_properties = '', dictGetStringOrDefault('posthog.groups_dict',   'group_properties', (team_id, 0, `$group_0`), toJSONString(map())),   group0_properties), group1_properties = if(group1_properties = '',   dictGetStringOrDefault('posthog.groups_dict', 'group_properties', (team_id,   1, `$group_1`), toJSONString(map())), group1_properties), group2_properties =   if(group2_properties = '', dictGetStringOrDefault('posthog.groups_dict',   'group_properties', (team_id, 2, `$group_2`), toJSONString(map())),   group2_properties), group3_properties = if(group3_properties = '',   dictGetStringOrDefault('posthog.groups_dict', 'group_properties', (team_id,   3, `$group_3`), toJSONString(map())), group3_properties), group4_properties =   if(group4_properties = '', dictGetStringOrDefault('posthog.groups_dict',   'group_properties', (team_id, 4, `$group_4`), toJSONString(map())),   group4_properties), group0_created_at = if(group0_created_at = toDateTime(0),   dictGetDateTime('posthog.groups_dict', 'created_at', (team_id, 0,   `$group_0`)), group0_created_at), group1_created_at = if(group1_created_at =   toDateTime(0), dictGetDateTime('posthog.groups_dict', 'created_at', (team_id,   1, `$group_1`)), group1_created_at), group2_created_at = if(group2_created_at   = toDateTime(0), dictGetDateTime('posthog.groups_dict', 'created_at',   (team_id, 2, `$group_2`)), group2_created_at), group3_created_at = if(group3_created_at   = toDateTime(0), dictGetDateTime('posthog.groups_dict', 'created_at',   (team_id, 3, `$group_3`)), group3_created_at), group4_created_at =   if(group4_created_at = toDateTime(0), dictGetDateTime('posthog.groups_dict',   'created_at', (team_id, 4, `$group_4`)), group4_created_at) WHERE (timestamp   > toDateTime('2020-01-01')) AND (timestamp < toDateTime('2024-01-01')) | ######## | ["202207","202208","202209","202210","202211","202212"] | [3353,350900,292672,1605366,1429320,723429] | ["202208_0_54455_10891"] | 1 | 0 |   | ######## |  
posthog | sharded_events | 6 | MATERIALIZE INDEX sesionIX | ######## | ["202207","202208","202209","202210","202211","202212","202301"] | [3354,350901,292673,1605367,1429321,851061,49555] | ["202208_0_54455_10891"] | 1 | 0 |   | ######## |  
posthog | sharded_events | 7 | MATERIALIZE INDEX sesionIX | ######## | ["202207","202208","202209","202210","202211","202212","202301"] | [3355,350902,292674,1605368,1429322,851062,49558] | ["202208_0_54455_10891"] | 1 | 0 |   | ######## |  
posthog | sharded_events | 8 | DROP INDEX sesionIX | ######## | ["202207","202208","202209","202210","202211","202212","202301"] | [3356,350903,292675,1605369,1429323,851063,50356] | ["202208_0_54455_10891"] | 1 | 0 |   | ######## |  



</body>

</html>

**Comment by den-crane** [comment]
As you can see `parts_to_do_names` = 202208_0_54455_10891 for all them.
Most probably this part is lost forever.

https://kb.altinity.com/altinity-kb-useful-queries/parts-consistency/#compare-the-list-of-parts-in-zookeeper-with-the-list-of-parts-on-disk

Check this query

```sql
select 'delete '||part_zoo
from (
select zoo.p_path as part_zoo, zoo.ctime, zoo.mtime, disk.p_path as part_disk
from
(
  select concat(path,'/',name) as p_path, ctime, mtime
  from system.zookeeper where path in (select concat(replica_path,'/parts') from system.replicas)
) zoo
left join 
(
  select concat(replica_path,'/parts/',name) as p_path
  from system.parts inner join system.replicas using (database, table)
) disk on zoo.p_path = disk.p_path
where part_disk='' and zoo.mtime <= now() - interval 1 day
order by part_zoo) format TSVRaw;
```

If you get `202208_0_54455_10891` in the result then remove this znode from Zookeeper and execute `system restart replica posthog.sharded_events` after.
All mutations should be finished.

**Comment by gregleongf** [comment]
The query above returns 0 rows.

When I query
```
select
    concat(path, '/', name) as p_path,
    ctime,
    mtime
from
    system.zookeeper
where
    path in (
        select
            concat(replica_path, '/parts')
        from
            system.replicas
    )
and p_path like '%202208_0%';
```
I only get these parts

p_path | ctime | mtime
-- | -- | --
/clickhouse/prod/tables/noshard/posthog/infi_clickhouse_orm_migrations/replicas/chi-posthog-posthog-0-0-0/parts/202208_0_30_6 | 8/2/2022 13:11 | 8/2/2022 13:11
/clickhouse/tables/0/posthog.events/replicas/chi-posthog-posthog-0-0/parts/202208_0_54450_10890 | 8/2/2022 11:18 | 8/2/2022 11:18

Similarly when I query
```SELECT * FROM system.parts where name like '%202208_0%'```
I also get those parts

partition | name | uuid | part_type | active | marks | rows
-- | -- | -- | -- | -- | -- | --
202208 | 202208_0_30_6 | 00000000-0000-0000-0000-000000000000 | Compact | 1 | 2 | 31
202208 | 202208_0_54450_10890 | 00000000-0000-0000-0000-000000000000 | Compact | 1 | 2 | 2197

But I can't seem to find part 202208_0_54455_10891 anywhere.

**Comment by gregleongf** [comment]
Ok. I've found the part in system.detached_parts with some other

`SELECT * FROM system.detached_parts where table = 'sharded_events'` returns

database | table | partition_id | name | disk | reason | min_block_number | max_block_number | level
-- | -- | -- | -- | -- | -- | -- | -- | --
posthog | sharded_events | 202208 | broken-on-start_202208_54455_54455_0 | default | broken-on-start | 54455 | 54455 | 0
posthog | sharded_events | 202208 | broken-on-start_202208_54453_54453_0 | default | broken-on-start | 54453 | 54453 | 0
posthog | sharded_events | 202208 | broken-on-start_202208_54452_54452_0 | default | broken-on-start | 54452 | 54452 | 0
posthog | sharded_events | 202208 | covered-by-broken_202208_0_54450_10890 | default | covered-by-broken | 0 | 54450 | 10890
posthog | sharded_events | 202208 | covered-by-broken_202208_54451_54451_0 | default | covered-by-broken | 54451 | 54451 | 0
posthog | sharded_events | 202208 | broken-on-start_202208_0_54455_10891 | default | broken-on-start | 0 | 54455 | 10891
posthog | sharded_events | 202208 | broken-on-start_202208_54454_54454_0 | default | broken-on-start | 54454 | 54454 | 0

**Comment by den-crane** [comment]
detached_parts don't matters.
Try `system restart replica posthog.sharded_events`

**Comment by gregleongf** [comment]
Did not help. Mutations are still stuck.

When I query `SELECT * FROM system.replication_queue LIMIT 10;` i get

database | table | replica_name | position | node_name | type | create_time | required_quorum | source_replica | new_part_name | parts_to_merge | is_detach | is_currently_executing | num_tries | last_exception | last_attempt_time | num_postponed | postpone_reason | last_postpone_time | merge_type
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
posthog | sharded_events | chi-posthog-posthog-0-0 | 0 | queue-0000069370 | GET_PART | 02.08.2022 11:19 | 0 |   | 202208_0_54455_10891 | [] | 0 | 0 | 635 | Code: 234. DB::Exception: No active replica has   part 202208_0_54455_10891 or covering part. (NO_REPLICA_HAS_PART) (version   22.3.13.80 (official build)) | 13.01.2023 08:09 | 0 |   | 01.01.1970 00:00 |  

num_tries is 635 and it's stuck no matter what. 

I'm using version 22.3.13.80 BTW.

**Comment by gregleongf** [comment]
I've tried doing this: https://kb.altinity.com/upgrade/removing-lost-parts/
But this query filters `where cnt_active=0` and the partition that is stuck has `cnt_active` value of 7

**Comment by den-crane** [comment]
The issue is related to only `202208_0_54455_10891`

Please share

```sql
select name, rows, active
from system.parts
where partition_id = '202208'
and table = 'sharded_events'
order by name
```

**Comment by gregleongf** [comment]
name | rows | active
-- | -- | --
202208_0_54450_10890 | 2197 | 1
202208_350891_350895_1_350907 | 125 | 1
202208_54451_54451_0 | 1 | 1
202208_54452_54452_0 | 0 | 1
202208_54453_54453_0 | 0 | 1
202208_54455_54455_0 | 0 | 1
202208_54459_350890_138746_350907 | 4795126 | 1

**Comment by den-crane** [comment]
Check `select * from system.merges`

**Comment by gregleongf** [comment]
`select * from system.merges` returns 0 rows

I've already shared system.replication_queue before. Here it is again:


database | table | replica_name | position | node_name | type | create_time | required_quorum | source_replica | new_part_name | parts_to_merge | is_detach | is_currently_executing | num_tries | last_exception | last_attempt_time | num_postponed | postpone_reason | last_postpone_time | merge_type
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
posthog | sharded_events | chi-posthog-posthog-0-0 | 0 | queue-0000069370 | GET_PART | ######## | 0 |   | 202208_0_54455_10891 | [] | 0 | 0 | 487451 | Code: 234. DB::Exception: No active replica has part 202208_0_54455_10891   or covering part. (NO_REPLICA_HAS_PART) (version 22.3.13.80 (official build)) | ######## | 0 |   | ######## |

**Comment by gregleongf** [comment]
I've detached and attached '202208' partition and the replication_queue is empty now. The problem seems to be resolved.
Thanks for the help.
