### ISSUE TITLE
The output for Date and DateTime types is incorrect for JDBC-driver with com.clickhouse.jdbc.ClickHouseDriver class

### ISSUE THREAD

**Issue by InquisitorGray** [ClickHouse/ClickHouse#45115]
The output for Date and DateTime types is incorrect if JDBC-driver (versions 0.3.2.9, 0.3.2.11) with the com.clickhouse.jdbc.ClickHouseDriver class is used. (The JDBC-driver with ru.yandex.clickhouse.ClickHouseDriver class returns correct results)
For example, the query
`SELECT (fromUnixTimestamp64Micro(-1262304000000001))`
 is expected to return `1930-01-01 00:00:00.000001`, but incorrectly returns `1929-12-31T23:59:59.999999`

The internal DBMS representation of Date and DateTime types is still correct, since the query
`SELECT toString(fromUnixTimestamp64Micro(-1262304000000001));`
returns the string `"1930-01-01 00:00:00.000001"`

The link to reproducer is [https://fiddle.clickhouse.com/f91be425-4d25-47f0-832c-6112aef8218b](https://fiddle.clickhouse.com/f91be425-4d25-47f0-832c-6112aef8218b).

The issue reproduces on recent release, since it is in JDBC-driver, not in DBMS itself.

**Comment by den-crane** [comment]
We don't support JDBC driver here. Ask this question in https://github.com/ClickHouse/clickhouse-jdbc/issues
