### ISSUE TITLE
22.8 Changing the name of self-extracting binary results in error.

### ISSUE THREAD

**Issue by MyroTk** [ClickHouse/ClickHouse#45128]
**Describe the unexpected behaviour**
Changing the name of a self-extracting binary from `clickhouse`  before it extracts (for example, downloading from s3 as `clickhouse_0` ) results in error when trying to use it.

```
$ ./clickhouse_0 server
No target executable - decompression only was performed 
```

**Comment by MyroTk** [comment]
@yakov-olkhovskiy

**Comment by vzakaznikov** [comment]
This is 22.8 issue. On binaries from master it is not reproducible.

**Comment by vzakaznikov** [comment]
```

**Comment by yakov-olkhovskiy** [comment]
should be fixed here
https://github.com/ClickHouse/ClickHouse/pull/40426

**Comment by tavplubix** [comment]
> should be fixed here
> #40426

Should we backport it then?

**Comment by yakov-olkhovskiy** [comment]
@tavplubix I don't think it's that critical
