### ISSUE TITLE
Dropping key for a Map field

### ISSUE THREAD

**Issue by jmvina** [ClickHouse/ClickHouse#45135]
Hi, 
I would like to know if it is possible to drop keys from a key-value field.

For example, If I have a table like this

CREATE TABLE schema.test_query_time_kv
(
    `time` DateTime('Europe/Madrid'),
    `dim1` String,
    `a` Map(String, UInt64)
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(time)
ORDER BY (time, dim1)

and I have populated with keys 'counter_1', 'counter_2',...

2022-01-01 01:00:00  dim1_0 {counter_1=34, counter_2=3, counter_3=4, counter_4=12, counter_5=3}
2022-01-01 01:00:00  dim1_1 {counter_1=1, counter_2=34, counter_3=4, counter_4=34, counter_5=8}
2022-01-01 01:00:00  dim1_2 {counter_1=5, counter_2=6, counter_3=3 counter_4=88, counter_5=1}

I would like to know if it is possible to drop all 'counter_2' keys (and values) of the table. I do not see any about it in the documentation.

Thanks in advance for your help.

**Comment by UnamedRus** [comment]
```
ALTER TABLE kalix.kalix_test_query_time_kv UPDATE a = mapFilter((k, v) ->k != 'counter_2', a) WHERE 1;
```

https://clickhouse.com/docs/en/sql-reference/functions/tuple-map-functions/#mapfilter

**Comment by jmvina** [comment]
Thanks for your help.
Theoretically mapFilter works fine (at least in a select query), but it's not dropping the counter

**Comment by jmvina** [comment]
> ```
> ALTER TABLE kalix.kalix_test_query_time_kv UPDATE a = mapFilter((k, v) ->k != 'counter_2', a) WHERE 1;
> ```
> 
> https://clickhouse.com/docs/en/sql-reference/functions/tuple-map-functions/#mapfilter

Thanks for your help.
Theoretically mapFilter works fine (at least in a select query), but it's not dropping the counter

**Comment by den-crane** [comment]
works for me

```sql
CREATE TABLE test_query_time_kv
(
    `time` DateTime('Europe/Madrid'),
    `dim1` String,
    `a` Map(String, UInt64)
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(time)
ORDER BY (time, dim1)

insert into test_query_time_kv select '2022-01-01 01:00:00', 'dim1_0', '{counter_1=34, counter_2=3, counter_3=4, counter_4=12, counter_5=3}';

ALTER TABLE test_query_time_kv  UPDATE a = mapFilter((k, v) ->k != 'counter_2', a) WHERE 1;

select * from test_query_time_kv;
┌────────────────time─┬─dim1───┬─a───────────────────────────────────────────────────────────┐
│ 2022-01-01 01:00:00 │ dim1_0 │ {'counter_1':34,'counter_3':4,'counter_4':12,'counter_5':3} │
└─────────────────────┴────────┴─────────────────────────────────────────────────────────────┘
```
