### ISSUE TITLE
How to login clickhouse under Kerberos authentication ?

### ISSUE THREAD

**Issue by IsisPolei** [ClickHouse/ClickHouse#45143]
I can not login clickhouse under Kerberos authentication.
----------------------------------
config.xml
![image](https://user-images.githubusercontent.com/41672192/211713221-02346132-639d-4c4c-bf39-10d4caae91f8.png)

----------------------------------
user.xml
![image](https://user-images.githubusercontent.com/41672192/211713183-5fb76567-7fb0-49b6-948d-5d864b2976c4.png)

----------------------------------
klist result:
![image](https://user-images.githubusercontent.com/41672192/211712711-fa15dd32-9721-4d52-9929-2636b0567398.png)
----------------------------------
login:
![image](https://user-images.githubusercontent.com/41672192/211712814-18f81ac6-e45c-4a3d-aba6-cdfeaef70073.png)
----------------------------------
Please tell me where i did wrong.

**Comment by IsisPolei** [comment]
![image](https://user-images.githubusercontent.com/41672192/211713360-1e27b526-8ee6-4847-986d-439c1600b9be.png)

**Comment by Algunenano** [comment]
https://clickhouse.com/docs/en/operations/external-authenticators/kerberos

`Currently, only requests over the HTTP interface can be kerberized (via GSS-SPNEGO mechanism).` Only HTTP, not TCP (https://github.com/ClickHouse/ClickHouse/issues/53132)
