### ISSUE TITLE
Kafka + Materialized View + MergeTree, result is empty

### ISSUE THREAD

**Issue by mdraevich** [ClickHouse/ClickHouse#45157]
Hi,

### About Clickhouse
Docker Hub `clickhouse/clickhouse-server:22.12.3.5-alpine`
All default settings.

How to run:
```shell
docker run -it -d --name test --rm -p 8123:8123 clickhouse/clickhouse-server:22.12.3.5-alpine
```

### Scenario
1. Extracting data from **Kafka Broker** using `Kafka` engine;
2. Insert extracted data to `MergeTree` by the means of `Materialized View`.

### About Kafka 
2 brokers, topic `sip`, 1 partition, 2 replicas.
An entry in the topic looks as follows:
```json
{
  "4": 17,
  "7": 5061,
  "8": "200.57.7.205",
  "11": 5060,
  "12": "200.57.7.195",
  "21": 1673430619,
  "22": 1673430509,
  "35632.132": "Ivan <sip:Ivan@Verso.com>",
  "35632.131": "Ivan <sip:Ivan@Verso.com>",
  "35632.134": 0,
  "35632.135": 0,
  "35632.136": 0,
  "35632.137": 0,
  "35632.138": 0,
  "35632.139": 0,
  "35632.140": 0,
  "35632.141": 0,
  "35632.142": 0,
  "35632.147": 200,
  "35632.148": 0
}
```

### Clickhouse SQL
```sql
CREATE TABLE default.cdr (
	`22`        DateTime,
	`21`        DateTime
) ENGINE = Kafka('192.168.1.8:9092', 'sip', 'ch-group', 'JSONEachRow');


CREATE TABLE default.dstcdr AS default.cdr
ENGINE = MergeTree
ORDER BY (`22`, `21`);


CREATE MATERIALIZED VIEW default.cdr_matview TO default.dstcdr AS 
SELECT (
	`22`,
	`21`
) FROM default.cdr;
```

### Problem
`select * from default.dstcdr;` shows empty result, no data inserted.

**However** if create `Materialized View` in the following way, the data is inserted as expected:
```sql
CREATE MATERIALIZED VIEW default.cdr_matview TO default.dstcdr AS 
SELECT * FROM default.cdr;
```
So, if `SELECT` specifies exactly what columns to extract, the insertion is failed without any log message.

### Log messages
Log messages were extracted after a few minutes after initial configuration with empty result.
Due to size of logs I've uploaded them to Gist: 
https://gist.github.com/mdraevich/464b432265871d13453f9de715dd7c09

### Question
Is empty result when querying specific columns expected? 
To me it looks like a bug, but still concerned about me missed something important in docs....

**Comment by den-crane** [comment]
see https://clickhouse.com/docs/en/sql-reference/data-types/tuple/#creating-a-tuple

In Clickhouse 
```
select (`22`, `21`)   -- one column - tuple type
```
 is not equal 
```
select `22`, `21`   -- two columns
```

try

```sql
CREATE MATERIALIZED VIEW default.cdr_matview TO default.dstcdr AS 
SELECT 
	`22`,
	`21`
FROM default.cdr;
```

**Comment by mdraevich** [comment]
@den-crane 
That was my fault, I got the idea.

Thank you for pointing me to the mistake.
