### ISSUE TITLE
ReplicatedMergeTree seems do not working

### ISSUE THREAD

**Issue by huwngnosleep** [ClickHouse/ClickHouse#45164]
I have a Cluster with 2 Shard, each Shard has 2-3 Replicas.

I created a ReplicatedMergeTree in each replica and insert data to them through a Distributed table with rand() sharding key.

I have internal_replication = true, after inserted 1.1M records then this is the result I got:

Shard 1 - Rep 1: 530K records

Shard 1 - Rep 2: 20K records

Shard 1 - Rep 3: 0 records

Shard 2 - Rep 1: 550K records (I run insert command on this node)

Shard 2 - Rep 2: 0 records

I ran count() query on Distributed table and got 1.08M (expected 1.1M) seem ClickHouse only get data from one Replica of each Shard.

How can I make it get data from all Replica in each Shard and insert balance into each Replica (expected ~200K records per Replica in Shard 1 and ~300K records for Shard 2)

My cluster config

```
<listen_host>0.0.0.0</listen_host>
<http_port>7481</http_port>
<tcp_port>9481</tcp_port>
<interserver_http_port>9009</interserver_http_port>
<interserver_http_host>0.0.0.0</interserver_http_host>

<remote_servers>
    <hungnt3_test_cluster>
        <shard>
            <internal_replication>true</internal_replication>
            <replica>
                <host>10.24.102.11</host>
                <port>9481</port>
            </replica>
            <replica>
                <host>10.24.102.14</host>
                <port>9481</port>
            </replica>
            <replica>
                <host>10.24.102.15</host>
                <port>9481</port>
            </replica>
        </shard>
        <shard>
            <internal_replication>true</internal_replication>
            <replica>
                <host>10.24.102.12</host>
                <port>9481</port>
            </replica>
            <replica>
                <host>10.24.102.13</host>
                <port>9481</port>
            </replica>
        </shard>
    </hungnt3_test_cluster>
</remote_servers>
<zookeeper>
    <node>
        <host>10.24.102.11</host>
        <port>9181</port>
    </node>
    <node>
        <host>10.24.102.12</host>
        <port>9181</port>
    </node>
    <node>
        <host>10.24.102.13</host>
        <port>9181</port>
    </node>
    <node>
        <host>10.24.102.14</host>
        <port>9181</port>
    </node>
    <node>
        <host>10.24.102.15</host>
        <port>9181</port>
    </node>
</zookeeper>

<macros>
    <shard>01</shard>
    <replica>10.24.102.11</replica>
</macros>

<keeper_server>
    <tcp_port>9181</tcp_port>
    <server_id>1</server_id>

    <coordination_settings>
        <operation_timeout_ms>10000</operation_timeout_ms>
        <session_timeout_ms>30000</session_timeout_ms>
        <raft_logs_level>trace</raft_logs_level>
    </coordination_settings>

    <raft_configuration>
        <server>
            <id>1</id>
            <hostname>10.24.102.11</hostname>
            <port>9710</port>
        </server>
        <server>
            <id>2</id>
            <hostname>10.24.102.12</hostname>
            <port>9710</port>
        </server>
        <server>
            <id>3</id>
            <hostname>10.24.102.13</hostname>
            <port>9710</port>
        </server>
        <server>
            <id>4</id>
            <hostname>10.24.102.14</hostname>
            <port>9710</port>
        </server>
        <server>
            <id>5</id>
            <hostname>10.24.102.15</hostname>
            <port>9710</port>
        </server>
    </raft_configuration>
</keeper_server>
```

**Comment by den-crane** [comment]
This is very important to understand: ReplicatedMergeTree **does not use** `<remote_servers>`. 

Replication is defined by ZK path in the table Engine.

Please provide `show create table your_table` and `select * from system.macros` **FROM ALL SERVERS**

**Comment by huwngnosleep** [comment]
Here is my create table comment
```
CREATE TABLE test_cluster.retailer on cluster 'hungnt3_test_cluster'
  (
      retailer_key BIGINT,
      real_key BIGINT,
      contract_type VARCHAR(255),
      expiry_date VARCHAR(255),
      created_date VARCHAR(255),
      modified_date VARCHAR(255),
      is_retailer_test VARCHAR(255),
      industry_key VARCHAR(255),
      server_key VARCHAR(255),
      last_transaction_date VARCHAR(255),
      business_model VARCHAR(255),
      is_using_new_fnb VARCHAR(255),
      hashed_code VARCHAR(255),
      hashed_phone VARCHAR(255)
  ) ENGINE=ReplicatedMergeTree('/clickhouse/tables/{shard}/retailer/{uuid}', '{replica}') ORDER BY (retailer_key);
```

And all server macros
- host 10.24.102.11
┌─macro───┬─substitution─┐
│ replica │ 10.24.102.11 │
│ shard   │ 01           │
└─────────┴──────────────┘

- host 10.24.102.12
┌─macro───┬─substitution─┐
│ replica │ 10.24.102.12 │
│ shard   │ 02           │
└─────────┴──────────────┘

- host 10-24-102-13
┌─macro───┬─substitution─┐
│ replica │ 10.24.102.13 │
│ shard   │ 02           │
└─────────┴──────────────┘

- host 10.24.102.14
┌─macro───┬─substitution─┐
│ replica │ 10.24.102.14 │
│ shard   │ 01           │
└─────────┴──────────────┘

- host 10-24-102-15
┌─macro───┬─substitution─┐
│ replica │ 10.24.102.15 │
│ shard   │ 01           │
└─────────┴──────────────┘

**Comment by den-crane** [comment]
Please check that uuid is the same for all nodes using

```
set show_table_uuid_in_table_create_query_if_not_nil=1;

show create table test_cluster.retailer
```

Another way to check ZK path is

```
SELECT
    fqdn(),replica_name, 
    zookeeper_path, 
    replica_path
FROM clusterAllReplicas('hungnt3_test_cluster', system.replicas)
WHERE (table = 'retailer') AND (database = 'test_cluster')
```

**Comment by huwngnosleep** [comment]
for replication_queue I got is error
No interserver IO endpoint named DataPartsExchange:/clickhouse/tables/bla/retailer/test/replicas/10.24.102.11. (NO_SUCH_INTERSERVER_IO_ENDPOINT), Stack trace (when copying this message, always include the lines below)

thank you so much
